### ISSUE TITLE
Implement a basic "Open Solution" IDE test...

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#10016]
Implement a test that can:

1.  Start VS
2.  Open a Solution
3.  Wait some fixed amount of time (or until idle)
4.  Close VS

This test should measure CPU time and managed allocations (CLR_BytesAllocated_Total_devenv).

**Comment by mavasani** [comment]
It would be beneficial if we can do a run with and without analyzers - possibly lot more analyzers than just the built in ones to test real end user scenarios. Can we also test against some big real world code solution?

**Comment by KevinH-MS** [comment]
Done!
