### ISSUE TITLE
Writing a VS Item Template results in minimum of two errors.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#10019]
**Version Used**: 
```
Microsoft Visual Studio Community 2015
Version 14.0.25029.00 Update 2 RC
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA613
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA613
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA613
Microsoft Visual C++ 2015
```

**Steps to Reproduce**:
Let say I'm producing the following VS2015 Item Template.
```VB.net
Public Structure $itemname$

End Structure
```

**Actual Behavior**:

Red squiggle under the first dollar sign `$`.
```VB.net
Public Structure $itemname$

End Structure
```
Along with the following two errors,
```
Severity	Code	Description
Error	BC30037	Character is not valid.
Error	BC30203	Identifier expected.
```

**Expected Behavior**:

I prefer if the IDE / Compiler was aware that I'm producing a item template. Maybe an attribute would help?
```VB.net
<VisualStudio.Template.Item(Language.VB)>
Public Structure $itemname$

End Structure
```
The compiler then could check for that attribute and modify it's behaviour to parse the code correctly.

**Comment by Pilchie** [comment]
This doesn't sound like functionality that the compiler would ever support.  It's possible that someone could build IDE support to do it using `IProjectionBuffer`, but given the number of people who write templates, and the other work on our backlog, I can't see us doing it either.
