### ISSUE TITLE
The expression compiler tests aren't running in Jenkins

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#1002]
They're unit tests and should be part of the suite.

**Comment by jaredpar** [comment]
Thanks for filing this bug.  I filed a bug a for some of the other suites that failed on Jenkins when we moved to CTP6 but missed this one :frowning: 

IIRC this was failing due to to MS.Debugging.Engine trying to run even though it was only delay signed.

**Comment by amcasey** [comment]
Yeah, I'm pretty sure we're not fake-signing the copies we ILASM.  What surprises me is that the ResultProvider tests *are* running.  They consume the same binaries.

**Comment by amcasey** [comment]
<![CDATA[System.IO.FileLoadException : Could not load file or assembly 'Microsoft.VisualStudio.Debugger.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---- System.Security.SecurityException : Strong name validation failed. (Exception from HRESULT: 0x8013141A)]]>

**Comment by amcasey** [comment]
The public key token of the Microsoft.VisualStudio.Debugger.Engine in the output folder is (correctly) b03f5f7f11d50a3a.  I suspect that we're actually loading a different copy at runtime.

**Comment by amcasey** [comment]
Nope, procmon shows that we are loading the correct copy.  I guess I get to learn more about strong names. :)

**Comment by AdamSpeight2008** [comment]
Also see #1006

**Comment by amcasey** [comment]
https://github.com/amcasey/roslyn/commit/87f7716f9dc530db2fef7af2fa72b6ea90ac4aa2

**Comment by amcasey** [comment]
These have been running for a while now.
