### ISSUE TITLE
[Loc Unit Test Failure ] Microsoft.CodeAnalysis.CSharp.UnitTests.OperationAnalyzerTests.LongArithmeticExpressionCSharp [FAIL]

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#10028]
Expected: True
      Actual:   False
      Stack Trace:
           êŠ Xunit.Assert.True(Nullable`1 condition, String userMessage)
           êŠ Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
           êŠ Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyAnalyzerDiagnostics[TCompilation](TCompilation c, DiagnosticAnalyzer[] analyzers, Boolean reportSuppressedDiagnostics, AnalyzerOptions options, Action`3 onAnalyzerException, Boolean logAnalyzerExceptionAsDiagnostics, DiagnosticDescription[] expected)
           êŠ Microsoft.CodeAnalysis.CSharp.UnitTests.OperationAnalyzerTests.LongArithmeticExpressionCSharp()

**Comment by jinujoseph** [comment]
This are for standalone 
 please contact @mattscheffer for more information

**Comment by TyOverby** [comment]
@jinujoseph @mattscheffer: What language is this failing in?

**Comment by TyOverby** [comment]
Closed by https://github.com/dotnet/roslyn/pull/12837
