### ISSUE TITLE
[Loc Unit Test Failure ] InternalsVisibleToAndStrongNameTests.AssemblySignatureKeyAttribute_3

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#10027]
InternalsVisibleToAndStrongNameTests.AssemblySignatureKeyAttribute_3 [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
           êŠ Xunit.Assert.True(Nullable`1 condition, String userMessage)
           êŠ InternalsVisibleToAndStrongNameTests.AssemblySignatureKeyAttribute_3()

**Comment by jinujoseph** [comment]
This are for standalone 
 please contact @mattscheffer for more information

**Comment by TyOverby** [comment]
Closed in https://github.com/dotnet/roslyn/pull/17035
