### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.CommandLineTests.FileShareDeleteCompatibility_Xplat [FAIL]

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#10022]
Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.CommandLineTests.FileShareDeleteCompatibility_Xplat [FAIL]

```
  Actual:
  Microsoft (R) Visual C# Compiler ƒo[ƒWƒ‡ƒ“ 1.2.0.60315
  Copyright (C) Microsoft Corporation. All rights reserved.
  Differences:
  ++> Microsoft (R) Visual C# Compiler ƒo[ƒWƒ‡ƒ“ 1.2.0.60315
  --> Microsoft (R) Visual C# Compiler version 1.2.0.60315
      Copyright (C) Microsoft Corporation. All rights reserved.

  Expected: True
  Actual:   False
  Stack Trace:
       êŠ Xunit.Assert.True(Nullable`1 condition, String userMessage)
       êŠ Roslyn.Test.Utilities.AssertEx.AssertEqualToleratingWhitespaceDifferences(String expected, String actual, Boolean escapeQuotes, String expectedValueSourcePath, Int32 expectedValueSourceLine)
       êŠ Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.CommandLineTests.FileShareDeleteCompatibility_Xplat()
```

**Comment by jinujoseph** [comment]
This are for standalone 
please contact @mattscheffer  for more information

**Comment by TyOverby** [comment]
@jaredpar: I don't think this bug can be "solved" in any foolproof way.  We don't get to control which culture a new process is spawned with, so we have no real way of knowing at test-time what the localized string could be.

**Comment by jaredpar** [comment]
Can we limit this test to English only then for now?

**Comment by TyOverby** [comment]
@jaredpar That seems reasonable, though a rogue test that sets CurrentUICulture and doesn't un-set it could break this test in the future.

**Comment by TyOverby** [comment]
@jaredpar Done in https://github.com/dotnet/roslyn/pull/17035
