### ISSUE TITLE
Project System: Project references should have a different icon to binary references

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10039]
It's hard to tell in the References tree, which is a project reference vs a binary reference:

![image](https://cloud.githubusercontent.com/assets/1103906/14004581/64b2ad54-f118-11e5-9989-b4a58f5882fa.png)

We should choose a better icon, similar to what we did with NuGet, to better differentiate.

**Comment by ErikSchierboom** [comment]
Great suggestion!

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#115
