### ISSUE TITLE
[Test Failure] No Console Session in prtest/win/dbg/eta on PR #10057

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#10058]
PR: [#10057](https://github.com/dotnet/roslyn/pull/10057) *Make IDEDiagnosticIDs distinct* by @dpoeschl
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/5418/

**Issue 1: No Console Session**
Tao cannot take screenshots, so we're probably not running in a console session. Halting the test run because this can cause unexpected test failures.
No tests were run because the test runner was unable to take screenshots. If this happens on a CI machine, make sure all user sessions are properly disconnected. Please notify @dotnet/roslyn-infrastructure if you see this error.

**Comment by dpoeschl** [comment]
FYI @gafter @ManishJayaswal

**Comment by ManishJayaswal** [comment]
@dpoeschl what needs to happen here?

**Comment by davkean** [comment]
The cause is because someone has logged onto the machine and disconnected without running Disconnect script. Someone needs to go onto the affected machine and do that. Instructions are in the swat Onenote.

**Comment by jinujoseph** [comment]
@mmitche cleared the console from those machine , verified that retesting prtest/win/dbg/eta  worked
