### ISSUE TITLE
Project System: Renaming project should rename folder

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10062]
UserVoice: https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/3282247-rename-project-folders-and-files

Today, it is extremely painful to rename a project and then rename the folders that contain it (you have to remove the project from the solution, and then readd it).

We should just rename the containing folder if it matches the name of the project.

**Comment by hmemcpy** [comment]
+100000

**Comment by ilmax** [comment]
+100000000

**Comment by D3-LucaPiombino** [comment]
Remember that this should also play nice with source control integration providers :)

**Comment by MgSam** [comment]
I weep then I think of the years of my life I've wasted removing projects from solutions so I can rename the folder to match our naming conventions and then it.

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#111
