### ISSUE TITLE
Project System: Allow editing the project file without unloading

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10065]
Related UserVoice: https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/2654545-don-t-close-all-files-when-a-project-file-is-edite

![image](https://cloud.githubusercontent.com/assets/1103906/14025521/b82a1344-f1ab-11e5-91e7-e826a925f778.png)

Currently we force you to reload a project when you want to edit it or it changes on disk. We shouldn't require that, we should let you edit it via a gesture (such as Edit on project context menu) and we should be smarter when it changes on disk, to only load the diffs - especially if it's only the addition of files.

**Comment by shaggygi** [comment]
Looking forward to this feature :smile:

**Comment by thecodejunkie** [comment]
I have to say that this is an absolute must and has been one of the real strengths of `project.json` .. it's changed my workflow quite a lot and speed it up. I don't want to use clunky UI tools to set basic project properties and bring in references etc.. the auto complete support for `project.json` was great

**Comment by Yantrio** [comment]
I have some concern with the original wording of the issue, I feel that the project file shouldn't have to be edited `via a gesture` at all, the project.json project system allowed us to edit the file directly, and the current csproj system requires us (in visual studio) to unload to edit, or use "gestures". 

Would it be possible to introduce a system where we don't have to unload or go through a GUI to edit the project file?

**Comment by davkean** [comment]
The wording was written before the xproj -> csproj merge.  Based on recent developments we'll make sure we bring/develop a somewhat similar experience to what you have in xproj.

**Comment by Yantrio** [comment]
Okay, I will await the discussion to come once the design has been fleshed out a bit post-merge announcement.

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#107
