### ISSUE TITLE
Project System: Should be able to copy and paste files between VS instances

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10061]
Today we don't let you copy and paste files between VS instances, we should allow that.

https://twitter.com/davkean/status/636761909614608384

File properties should flow with it.

**Comment by hmemcpy** [comment]
Also, project references! Copy/pasting them between projects in the same solution would also be awesome!

**Comment by davkean** [comment]
Yep, great idea. Filed: https://github.com/dotnet/roslyn/issues/10063

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#112
