### ISSUE TITLE
Project System: "Copy as Path" for folders/files

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10077]
It would be helpful to have a "Copy as Path" for folders/files in a project.

**Comment by davkean** [comment]
Maybe only when SHIFT is held down? Do we have other examples of modifiers controlling the visible context commands?

**Comment by NoneGiven** [comment]
Wouldn't that just be "Copy Path?" And why a modifier key?

I would just expect it à la:
![img](https://cloud.githubusercontent.com/assets/2163967/14044933/d912f286-f26b-11e5-9e38-f24ebb9181ea.png)

**Comment by davkean** [comment]
To mimic Explorer.
________________________________

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#99
