### ISSUE TITLE
Remove ETW loggers from the compiler

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#1007]
We were previously using some ETW loggers in the compiler to profile. We're not using the information anymore and several times it has been accidentally enabled and caused perf regressions due to the high amount of traces being logged. We should remove the logging and re-add it in more interesting places if we want to investigate similar problems in the future.

**Comment by pharring** [comment]
I'll take a look at this.

**Comment by pharring** [comment]
@agocke See PR #1057

**Comment by agocke** [comment]
Closed by #1057
