### ISSUE TITLE
Feature Request-Compress Project with Linked files for "Sharing"

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#10079]
**Version Used**: 
All
**Steps to Reproduce**:

1. Create new project and then add link to any existing file to the project
2. Use Zip or other (compression) tool to package the file to share with someone (like needing to post here)
3. Uncompress/Unzip the file on another computer and try to open the project, all the linked files will be missing, which is expected but not useful.

**Expected Behavior**:
It works as expected assuming I know that the project I was working on had linked files. But what I want is a way to have the linked files included. Since no existing tools understand the Visual Studio project structure any tool needs to be part of Visual Studio.
**Actual Behavior**:
All linked files are missing from the compressed file.

**Comment by gafter** [comment]
Roslyn is an open-source project providing libraries and tools for program analysis. The kinds of things you're asking for are outside the scope of Roslyn's charter.

**Comment by paul1956** [comment]
@gafter is there a more appropriate place for this issue, I will post there and close here.
