### ISSUE TITLE
Snippets - VB "adoAccess" snippet in web site fails with popup when trying to add references

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#10074]
Ported from internal bug 157136
1. Create a new VB ASP.NET Empty Web Site (File -> New -> Web Site... -> Templates -> Visual Basic -> ASP.NET Empty Web Site).
2. Create a new VB Web Form (File -> New -> File... -> Visual Basic -> Web Form).
3. In the new Web Form (Default.aspx), inside the "div" tags, insert the text "<% adoAccess %>".
   ![image](https://cloud.githubusercontent.com/assets/235241/14027109/4f2a33f8-f1b3-11e5-99b2-45a4ffd7fcb2.png)
4. Place your cursor at the end of "adoAccess" and press the "Tab" key.

**Actual Results**: The "adoAccess" snippet is inserted, but the following error message is displayed:
    ![image](https://cloud.githubusercontent.com/assets/235241/14027119/5b4258aa-f1b3-11e5-9c8f-ec658ce2987b.png)

/cc: @v-codeel

**Comment by CyrusNajmabadi** [comment]
All those snippets are in legacy maintenance mode.  NOt touching without a strong supporting reason.
