### ISSUE TITLE
Solution-wide operations should not cause multiple file save dialogs

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#10088]
Port of internal bugs 131942 and 146490, which both report this issue when performing Remove Unused Usings on the Solution.

**Comment by dpoeschl** [comment]
Note from @Pilchie "We already *try* to do this in http://source.roslyn.io/Microsoft.VisualStudio.LanguageServices/R/6e1dabb716227b82.html. I wonder what's going wrong?"

**Comment by CyrusNajmabadi** [comment]
Can't repro this.
