### ISSUE TITLE
GetOperation returns incorrect operation for ArgumentSyntax

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#10082]
```C#
new TextSpan(int.Parse(a), int.Parse(b))
```

I had the ArgumentSyntax node for ```int.Parse(a)``` and I expected GetOperation to return an IArgument. Instead, I get a BoundObjectCreationExpression.

**Comment by JohnHamby** [comment]
IArgument occurs only within an invocation. Get the operation for the entire call and then traverse the arguments.

I'm not sure what GetOperation should do when presented an argument syntax node in isolation. In particular, I'm not sure that it can do what @kuhlenh is expecting.

**Comment by genlu** [comment]
As @JohnHamby mentioned, `IArgument` is created during the process of creating an invocation operation (as the argument itself is not a bound node, the expression included is), so you need to get it from an invocation instead.

**Comment by kuhlenh** [comment]
Cool, thanks @genlu!
