### ISSUE TITLE
Improve cancellation of solution-wide refactorings

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#10097]
Ported/Adapted from internal bug 131358
1. Have better progress reporting
2. Respond to cancellation more quickly
3. Disable cancellation & update text once we start making changes

**Comment by Pilchie** [comment]
This is something that will be important as we start to have more fixers that people want to apply solution-wide.

**Comment by CyrusNajmabadi** [comment]
This work was done when fix-all was rewritten.
