### ISSUE TITLE
CSharpSendToInteractive vsi test fails in standalone due to unexpected result in the window

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#10109]
**Version Used**: 
ML 25124.01
**Steps to Reproduce**:
Run CSharpSendTointeractive on a machine w/o building roslyn (standalone context)

Test failure occurs during InitTest at the SubmitReplText section. 
**Expected Behavior**:
Test should attempt to submit 'using System;' to the immediate window and receive a blank line in return.
**Actual Behavior**:
CSharpInteractive has a large amount of extra text that shouldn't be in the test at all. It is likely that the test still contains info from an earlier C# interactive test.

**Comment by mattscheffer** [comment]
![image](https://cloud.githubusercontent.com/assets/10537189/14051259/c35ea3aa-f27e-11e5-8b31-82408a68d9f1.png)

I'm guessing this needs either a reset action or clear action before the initial submit repl text. Test before this is CSharpReplClassification which I'm guessing is the culprit here. So you may need to run that test first for proper repro. 

However, even if there is no interference, this test fails to another issue, which I'm logging a bug for now.

**Comment by mattscheffer** [comment]
@davkean

**Comment by mattscheffer** [comment]
2nd failure is #8434

**Comment by ManishJayaswal** [comment]
removing urgency now label as the scenario is covered in manual script.

**Comment by heejaechang** [comment]
similar issue - https://github.com/dotnet/roslyn/pull/10950

**Comment by heejaechang** [comment]
build with similar issue  - http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/682/

**Comment by ManishJayaswal** [comment]
Closing as we are updating all integration tests for willow and once it is enabled we will file issues for tests that have problems.
