### ISSUE TITLE
[Test Failure] No console session on dci-win-ibld-3

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10101]
PR: [#10052#partial-pull-merging](https://github.com/dotnet/roslyn/pull/10052#partial-pull-merging) *Enc: async/iterator editing regression fix* by @tmat
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/5412/

```
Tao cannot take screenshots, so we're probably not running in a console session. Halting the test run because this can cause unexpected test failures. No tests were run because the test runner was unable to take screenshots. If this happens on a CI machine, make sure all user sessions are properly disconnected. Please notify @dotnet/roslyn-infrastructure if you see this error.
```

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure

**Comment by davkean** [comment]
I've taken the machine offline: https://github.com/dotnet/roslyn/issues/10101

**Comment by ManishJayaswal** [comment]
@jinujoseph @mmitche Did we miss this machine when we fixed up the others yesterday?

**Comment by mmitche** [comment]
No, that run was over a day ago.  It was cleaned up after that.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by ManishJayaswal** [comment]
@jasonmalinowski can you take a look?

**Comment by davkean** [comment]
I ended up resolving this. This should be the job of the Viper to make sure these machines are online, we also had 3 other machines offline:https://github.com/dotnet/roslyn/issues/10131
