### ISSUE TITLE
BasicEditAndContinue vsi test failed in standalone with NuGetPackageload failure.

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#10107]
**Version Used**: 
ML 25124.01
**Steps to Reproduce**:
Run BasicEditAndContinue on a machine w/o building roslyn (standalone context)

**Expected Behavior**:
Test succeeds
**Actual Behavior**:
Test fails with a NugetPackage load failure. Info from activity log below:
	<errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Services.Client, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>

This occurs at the 'EnC while debugging from Immediate window' scenario during the debug step after setting a breakpoint.

**Comment by mattscheffer** [comment]
@davkean

**Comment by tmat** [comment]
Looks like TFS bug: https://github.com/dotnet/roslyn/issues/9510

**Comment by mattscheffer** [comment]
Not a dupe of 9510. I logged a related bug in VSO 203945. It was resolved as a dupe after people talked to the NuGet team. Issue was fixed in master and flowed to ML.

Issue no longer repros and closed.
