### ISSUE TITLE
Various Standalone VSI tests failing due to testhook being unable to open the Generate Type Dialog window

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#10110]
Tests affected:
BasicGenerateTypeDialog.xml
CSharpGenerateTypeDialog.xml
CSharpVenus.xml

**Version Used**: 
VSUML 25125.00
**Steps to Reproduce**:
1. Run BasicGenerateTypeDialog on a machine w/o building roslyn (standalone context)

Failure occurs at first GenerateTypeDialog action
**Expected Behavior**:
Line is selected and the prompt opens up correctly
**Actual Behavior**:
Testhook is unable to open the prompt and timesout after 5 mins.

Begin Waiting for Apex Communication
  Scenario: Generate Type Dialog VB-to-C#
     Executing action [3/25/2016 5:39:53 AM] AddProject
     Executing action [3/25/2016 5:40:04 AM] AddProject
     Executing action [3/25/2016 5:40:15 AM] AddItem
     Executing action [3/25/2016 5:40:15 AM] OpenFile
 DEBUG: executed DTE command File.OpenFile.
 DEBUG: start polling for code window
 DEBUG: polling complete
     Executing action [3/25/2016 5:40:15 AM] SetEditorText
     Executing action [3/25/2016 5:40:15 AM] PlaceCursor
     Executing action [3/25/2016 5:40:15 AM] GenerateTypeDialog

---

 System.Exception: Timed out waiting for Generate Type dialog after 300 seconds.
    at Roslyn.VSHosting.Test.GenerateTypeDialogAction.Execute(TaoEngine engine)
    at Tao.Engine.DebuggableActionExecutor.Execute()
    at Tao.Engine.DefaultActionExecutor.Execute()
 ================================
![image](https://cloud.githubusercontent.com/assets/10537189/14052850/6a0d2b80-f28a-11e5-9567-94cccb00c814.png)

**Comment by mattscheffer** [comment]
From what I'm seeing, the quick action GenerateType isn't visible anymore when the whole line is selected. Its only present when on the last 'A' is highlighted. At that point you're able to Generate type correctly. 

I'm guessing there was a recent change in behavior here?

**Comment by mattscheffer** [comment]
@davkean  Not sure if this has been seen yet.

**Comment by jasonmalinowski** [comment]
@jmarolf, what's the status of this bug?

**Comment by jmarolf** [comment]
>From what I'm seeing, the quick action GenerateType isn't visible anymore when the whole line is selected. Its only present when on the last 'A' is highlighted. At that point you're able to Generate type correctly.

I'm not observing this behavior.  As long as the cursor is on the same line as the type we want to generate, the lightbulb is available.
![image](https://cloud.githubusercontent.com/assets/9797472/15000949/617b9452-1148-11e6-8879-5d6ae8fc30ba.png)

If you double click the line the cursor drops to the next line, in which case you will not see the lightbulb
![image](https://cloud.githubusercontent.com/assets/9797472/15000977/9b8a78d4-1148-11e6-9402-680bed731d98.png)

You say we need to do these steps `w/o building roslyn (standalone context)` Does that mean an unmodified build of VSUML or does Roslyn.Test.Setup need to be installed?  Using a version of VS that had locally built extensions installed I was not able to repro this failure.

**Comment by mattscheffer** [comment]
This seems to have turned into more of an intermittent issue since I've logged the bug. The last failure I've had was on friday with ML. Nothing this week so far. I'll get a machine going with that build and will send a message when it's available. 

Yes standalone context is an unmodified build of VS except for Roslyn.Test.Setup. Tao runs using VS's binaries rather then the built ones.

**Comment by mattscheffer** [comment]
I have the machine available and I'll pm you the info. 

You're correct that the lightbulb pops up on the left when the cursor is on the same line, and if you click it, it does show all of the options. However, if you select the entire line, have the cursor there, right click to bring up the context menu and select 'Quick Actions and Refactoring', nothing shows up. The lightbulb blinks out for a second, before returning. 

It does appear correctly if you place the cursor on the error itself. However, I believe the context menu version and the lightbulb on the left should both pull up everything on that line.

**Comment by Pilchie** [comment]
Is this still an issue with the work @mavasani and others have done on getting D15 support working?

**Comment by jmarolf** [comment]
Test passes locally on my RC only machine.
