### ISSUE TITLE
Naming styles: No fix offered to remove '_' from names

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#10111]
**Version Used**: 

**Steps to Reproduce**:
1. Define a naming rule that fields should be `camelCased`.
2. Create a field: `int _field;`
3. Invoke the lightbulb on it.

**Expected Behavior**:
Should have an option to rename.

**Actual Behavior**:
No rename, just the button to change styles. :crying_cat_face:

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
