### ISSUE TITLE
MSBuild race to write portable assembly attributes file

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#10116]
Many of our builds are failing with the following:

``` txt
error MSB3491:  Could not write lines to file "d:\j\workspace\roslyn_master---e026a511\Binaries\Temp\.NETPortable,Version=v5.0.AssemblyAttributes.cs". 
The process cannot access the file 'd:\j\workspace\roslyn_master---e026a511\Binaries\Temp\.NETPortable,Version=v5.0.AssemblyAttributes.cs' because it is being used by another process. 
[d:\j\workspace\roslyn_master---e026a511\src\Tools\Source\CompilerGeneratorTools\Source\CSharpErrorFactsGenerator\CSharpErrorFactsGenerator.csproj] ->      
6>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2992,5):
```

This is a race condition in MSBuild writing out the temporary files which was previously won't fixed.  This is causing build breaks as we are promoting this to an error.  For now leaving this as a warning that we ignore.  

Root cause: http://vstfdevdiv:8080/DevDiv2/DevDiv/_workItems?id=403105&_a=edit

**Comment by jasonmalinowski** [comment]
@jaredpar Do we need a bug over on MSBuild for this?

**Comment by jaredpar** [comment]
@jasonmalinowski has this come up again recently?

**Comment by jasonmalinowski** [comment]
@jaredpar No, just digging through ancient infrastructure bugs.

**Comment by jaredpar** [comment]
CC @rainersigwald

I'm having trouble tracking down where this behavior comes from.  I dug through the MSBuild source and couldn't find anything relevant.  It happens as a part of the portable targets in this specific bug so it's possible it's there.

Either way there should be a safe way of doing this (safe as in no warning).
