### ISSUE TITLE
Failure to initialize ForegroundThreadAffinitizedObject

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#10121]
In sporadic Jenkins runs the following check in `ForegroundThreadAffinitizedObject` is failing:

```
public bool IsValid()
{
    return _foregroundThreadData.Kind != Unknown;
}
```

This essentially means we were unable to setup the correct foreground thread before unit tests began running.  This essentially means all subsequent checks for foreground / background will also fail.  

Example exception from the dump file:

```
StackTrace (generated):
    SP       IP       Function
    073BCD48 1A5D39AD Microsoft_CodeAnalysis_Workspaces!Roslyn.Utilities.Contract.Fail(System.String)+0x3d
    073BCD58 07450CCA Microsoft_CodeAnalysis_Workspaces!Roslyn.Utilities.Contract.ThrowIfFalse(Boolean, System.String)+0x6a
    073BCD74 1C7D64F1 Microsoft_CodeAnalysis_EditorFeatures!Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService..ctor()+0x89
```

This is the root cause of #7825.

**Comment by CyrusNajmabadi** [comment]
Closing this out as we don't seem to be hitting this and the unit test deadlocks seem to have been adddressed.
