### ISSUE TITLE
Extract Local should support simple names in some cases

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#10123]
I'd like to be able to use extract local on field and property names (to avoid repeated accesses, especially in multi-threaded scenarios).  I can also imagine wanting to use extract local on something like a `foreach` iteration variable (for capturing or mutation purposes), but that's much less interesting.

**Comment by amcasey** [comment]
FYI @Pilchie - we talked about this over lunch.

**Comment by Pilchie** [comment]
@CyrusNajmabadi/@DustinCampbell - any concerns here?  @amcasey was expressing that he didn't understand when this refactoring did and didn't show up.  I think we should probably just make it more consistent, even if it shows in a few cases where it's less likely to be useful.

**Comment by DustinCampbell** [comment]
I'm good with us. I think actually think this refactoring should pretty much always be available. We shouldn't arbitrarily restrict this particular refactoring because it can be a really useful when used to quickly introduce variables as part of a larger refactoring.

**Comment by jcouv** [comment]
Could you provide a specific example to clarify? As far as I can tell, IntroduceLocal works on a field access.

![image](https://user-images.githubusercontent.com/12466233/37428774-8e9b8050-278a-11e8-9fad-1c8bc5735673.png)

**Comment by CyrusNajmabadi** [comment]
I think the concern here was noisyness.  However, i suppose if it only shows up if you select the identifier fully then it's not a problem... (maybe).

**Comment by jcouv** [comment]
PR in progress: https://github.com/dotnet/roslyn/pull/25856

**Comment by jcouv** [comment]
Fix should be in 15.7 preview 4.
