### ISSUE TITLE
[scriptcs] handling importing of invalid namespaces in the REPL

### ISSUE THREAD

**Issue by filipw** [dotnet/roslyn#1012]
In the old Roslyn CTP we used a bit of a hack to recognize invalid namespaces in user's submission.

The code is located [here](https://github.com/scriptcs/scriptcs/blob/148e0f642282933fb1ac0c7e0c3515660609a931/src/ScriptCs.Engine.Roslyn/RoslynScriptEngine.cs#L137) and it used reflection against a field called `pendingNamespaces` 

What what happen is that if user tried to do something like this in a REPL:

    using System.Text; //valid
    using Foo; //invalid

Old Roslyn CTP would throw an exception about invalid namespace. We'd catch the script exception [here](https://github.com/scriptcs/scriptcs/blob/148e0f642282933fb1ac0c7e0c3515660609a931/src/ScriptCs.Engine.Roslyn/RoslynScriptEngine.cs#L188) and then use the aforementioned `pendingNamespaces` to pluck the offending namespaces.

There reason for this is to prevent a situation where submission was left in a "broken" state, without that it was impossible to make a subsequent submission as it would keep erroring out (complaing previous submission was botched) - it was hardly elegant but it worked.

I don't know what is the equivalent solution for us in the new scripting bits? When we add invalid namespace to `ScriptOptions` and later call `CSharpScript.Run` with such invalid options, it does not produce any errors that's surfaced in `ScriptState`.
However REPL becomes unusable as on subsequent submissions this validation is failing: https://github.com/dotnet/roslyn/blob/dd46bc10a225e24c213dd3f62ce7e3fa6b2f36ee/src/Compilers/Core/Portable/Compilation/Compilation.cs#L115 

![screenshot 2015-03-04 12 10 43](https://cloud.githubusercontent.com/assets/1710369/6482572/7ef1f8e0-c267-11e4-98f2-935fbb6f27f8.png)

**Comment by filipw** [comment]
@kuhlenh looks like only team members can assign labels

**Comment by ManishJayaswal** [comment]
This does not seem to be the issue anymore. Now we give an error:

(1,7): error CS0246: The type or namespace name 'foo' could not be found (are you missing a using directive or an assembly reference?)

And the subsequent submissions  work fine.
