### ISSUE TITLE
[VB] Extend null-propagation operator to include XML Literal.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#10137]
It would be useful to have the null-propagation operator to include XML Literal syntax for accessing attributes on the xml node.

**Existing**
```VB
Dim xe = <Foo a0='a' a1='b' a3='c' />
Dim a2 = xe.@a2
' Error
Dim a1 = xe.@a1
```
**Proposal**
```VB
Dim xe = <Foo a0='a' a1='b' a3='c' />
Dim a2 = xe.?@a2
Dim a1 = xe.?@a1
' a2 = Nothing
' a1 = "b"
```

**Comment by HaloFour** [comment]
Your **Existing** code isn't failing in VB2015.  The variable `a2` is being assigned `Nothing`.  This is the case regardless of whether `xe` is an `XElement` or an `IEnumerable(Of XElement)`.

**Comment by gafter** [comment]
@AdamSpeight2008 : @HaloFour is correct, your existing code does not error. Moreover, the following works today.

```vb
Dim xe = <Foo a0='a' a1='b' a3='c'/>
xe = Nothing
Dim a2 = xe?.@a2
Dim a1 = xe?.@a1
```
