### ISSUE TITLE
Question: How to determine language version from within an analyzer?

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#10147]
I would like to suppress reporting, based on available language features.

**Comment by DavidArno** [comment]
Could you explain further what it is you are hoping to achive? If you are using a Roslyn analyzer for C#, then the language version is 6. V6 languages features work, to an extent, regardless of the framework version targeted.

**Comment by jasonmalinowski** [comment]
Look at `SyntaxTree.ParseOptions.LanguageVerson`, but @dotnet/roslyn-compiler might have a better answer for detecting specific features.

**Comment by gafter** [comment]
Yes, Jason's answer is best. We have an internal way of checking whether a particular feature is enabled (https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/CSharpParseOptions.cs#L211-L221) but we don't have plans to make that public.

**Comment by bkoelman** [comment]
Thanks, that's what I was looking for!

I see a publicly exposed `.Features` (http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/CSharpParseOptions.cs,203):

```csharp
            var opt = (CSharpParseOptions)syntaxContext.Node.SyntaxTree.Options;
            IReadOnlyDictionary<string, string> f = opt.Features;
```

but it is empty in my case. I guess the experimental features will be put in there, once available in intellisense build...

I'm working on an experimental analyzer that should only report when nullable reference types are enabled (`MessageID.IDS_FeatureStaticNullChecking`).

**Comment by gafter** [comment]
Those `.Features` are the values set using the `/features` command-line option. If you don't use that option (or the equivalent in the .project file) then it will remain empty.
