### ISSUE TITLE
public BoundExpression Property(BoundExpression receiver, WellKnownMember member) doesn't verify that get method exists and is good

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#10148]

**Comment by gafter** [comment]
I suspect this is referring to part of the implementation of recursive pattern-matching.

**Comment by AlekseyTs** [comment]
This is referring to a method of the given signature in SyntheticBoundNodeFactory.

**Comment by gafter** [comment]
Looking at the code today, I see it does perform the check indirectly through a helper method.
