### ISSUE TITLE
Current Assemblies Count Increases continually as does memory usage.

### ISSUE THREAD

**Issue by jonathh21** [dotnet/roslyn#10164]
**Version Used**: 
Latest stable.

**Steps to Reproduce**:

1. Create simple loop that calls 'CSharpScript.Create<T>', CreatesDeletegate and Invoke.
2. Iterate 1,000,000 times or more

**Expected Behavior**:

Current loaded assemblies to stay roughly level as created 'Script's go out of scope, Memory usage to stay roughly level.
**Actual Behavior**:

Currently loaded assemblies goes through the ceiling, and memory usage steadily increases.

Note:
I recognise this isn't ideal conditions but I was expecting/hoping that in a simple closed loop that there would be no leakage. It seems to be create a temporary assembly for each and every call to 'Create' that has a subsequent CreateDeletegate call.

I hope and prey I am just doing something wrong as I am looking to use Roslyn API Script for a piece I am working on.

        static void Main(string[] args)
        {
            for (int i = 0; i < 1000000; i++)
            {
                RunTest(global, i, displayMod);
                GC.Collect();
            }
        }

        private static void RunTest(Globals global, int i, double displayMod)
        {
            ScriptOptions scriptOptions;

            scriptOptions = ScriptOptions.Default.WithReferences("System.Linq")
                .WithImports("System.Linq");

            var formula = "\"Hello World:\" + Counter";

            Script<string> script = CSharpScript.Create<string>(formula, scriptOptions, typeof (Globals));
            var @delegate = script.CreateDelegate();

            global.Counter = i;

            var invoked = @delegate.Invoke(global);
        }

**Comment by tmat** [comment]
No, you're not doing anything wrong. Each script compilation create an assembly that can't be unloaded once loaded. The CLR unfortunately doesn't support collecting assemblies loaded from byte[].

See also UserVoice request: https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/6120992-support-for-collectible-assemblies

**Comment by jonathh21** [comment]
Is there no way to create the delegate or expression tree without it being in its own assembly?

I have been looking at Dynamic Expresso - which, although simpler doesn't have this limitation..

**Comment by tmat** [comment]
No, we don't support that currently (feel free to file an issue). As you say it would be limited to a small subset of C#. Scripting supports full C#.

**Comment by jonathh21** [comment]
I'll look to add a separate issue, but for me is the death knell for our usage of the Scripting API.

Love the power, flexibility but an ever growing list of assemblies will eventually cause a problem and I can't start out knowing that, and knowing there is nothing I can do about it.

**Comment by jonathh21** [comment]
Ok,

So I have an idea. Rather than have 300 'expressions' I am going to try and
batch them up, wrap them in a method call and return a dynamic. There will
be a main method that as well as building the methods will build a
'switch/case' block to determine at runtime which method to run.

The idea is that a dictionary of identifier/expression such as

Dictionary<string, string> expressions = new Dictionary<string, string>()
            {
                {"1234", "x + y"},
                {"5678", "x"}
            };

can produce code like

        public class class_name
        {
            dynamic F1234() { return x + y; } dynamic F5678() { return x; }

            public dynamic Go(string identifer)
            {
                switch (identifer)
                {
                    case "F1234":
                        return F1234();
                    case "F5678":
                        return F1234();
                    default:
                        throw new Exception();
                }
            }

        }

then on excution I can pass in my 'Globals' that contain x and y, and also
the identifer to allow the correct 'expression' to be called.

I am generating the code ok, but I am getting an error because it can't
find x or y

error CS0120: An object reference is required for the non-static field,
method, or property 'Globals.y'

this isn't suprising to me as this isn't an expression anymore, but if
anyone can give me any pointers?? is there a way to use Globals?

also, i need to call 'Go' and pass in the identifier.....

Thank you all in advance.

**Comment by svick** [comment]
@jonathh21 I believe that globals can be accessed from top-level statements in a script, but not from classes defined in a script. To work around that, you can have a top-level statement that accesses the globals and passes them to your class. And you can pass identifier the same way as passing x and y.

[Here is full code that works for me.](https://gist.github.com/svick/da22b8f623dd563a2e54ab1110768a57)
