### ISSUE TITLE
Inline Temp should keep comments

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#1017]
Ported from TFS WorkItem: **580497**

🔗 Also filed as [AB#1292137](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1292137)

---

**Repro Steps:**

``` VB
Module Program
    Sub Main()
        Dim a = 1, ' comment
            b = 1
        Dim c = a
    End Sub
End Module
```

Inline a.

**ACTUAL:**

``` VB
Module Program
    Sub Main()
        Dim b = 1
        Dim c = 1
    End Sub
End Module
```

**EXPECTED:**

``` VB
Module Program
    Sub Main()
        ' comment
        Dim b = 1
        Dim c = 1
    End Sub
End Module
```

---

**Revisions:**

1) Created By Vladimir Reshetnikov (1/17/2013 10:43:16 AM)

---

2) Edited By Collin Deel (Chinasoft) (4/11/2014 12:55:31 PM)

Results are now:

``` VB
Module Program
    Sub Main()
        Dim
            b = 1
        Dim c = 1
    End Sub
End Module
```

The comment still disappears, and not removing the line break introduces some errors.

---

3) Edited By Balaji Krishnan (6/18/2014 10:56:18 AM)

Notes: introducing compilation errors is a bug. 

Without breaking compilation, the current code's intent is to preserve/move trivia if the local declaration has more than 1 declarators, with a single or multi-line comment and &quot;delete&quot; them completely if there was only 1 variable declarator. 

Check how it actually works though. 

This is also related with how the feature handles pre-processor directives (Bug 527376)

**Comment by Pilchie** [comment]
Moving to 1.1 based on current bug bar.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
