### ISSUE TITLE
Intellisense issue in var pattern in property pattern

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#10170]
Reported by @MadsTorgersen 

The IDE fighting back a bit in property patterns…

<img width="600" alt="img1" src="https://cloud.githubusercontent.com/assets/3804346/14119117/7e1d2188-f5a1-11e5-9573-cf68fb2a1a09.png">

**Comment by DustinCampbell** [comment]
Feel free to assign to me. I'll fix it today.
