### ISSUE TITLE
Background compiler requires more references to succeed than a command-line compile

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10183]
Getting build errors in future for Roslyn.sln, inside Visual Studio:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'CreateCSharpCompilation' does not exist in the current context	CSharpCompilerPerformanceTest	C:\Roslyn With Spaces\src\Compilers\CSharp\Test\Performance\CompilationBenchmarks.cs	15	Active
Error	CS0012	The type 'CommonTestBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Roslyn.Test.Utilities, Version=42.42.42.42, Culture=neutral, 
```

From the command-line or if I just choose show Build messages from the drop down in the Error List, there are no errors.

It looks like we're getting confused and for some reason thinking that `CommonTestBase` comes from `Roslyn.Test.Utilities` whereas, it actually comes from `Roslyn.Test.Utilities.Desktop` in the above case (it's duplicated in both).

**Comment by Pilchie** [comment]
Can you take a look?  Seems most likely to be a project system/workspace issue.

**Comment by jasonmalinowski** [comment]
I'm not able to reproduce this now; without repro steps (or at least a workspace log) there's not much more I can do here.
