### ISSUE TITLE
Alt+Up and Alt+Down should follow indentation

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#10180]
As lines get moved up and down with "Alt+Up" and "Alt+Down" they should get indented properly.

**Comment by SLaks** [comment]
Should the indentation changes be in the same Undo transaction as the line move or not?
I think yes, but I'm not sure.

**Comment by Pilchie** [comment]
Can you please follow up with the editor team, the implementation of Alt+Up/Down is handled there.
