### ISSUE TITLE
Signature help doesn't agree on number of overloads when some are hidden via Browsable(false)

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#10197]
**Version Used**: 14.0.25029.00 Update 2 RC

**Steps to Reproduce**:
1. Create a new WPF project.
2. Go to code behind and in the constructor, start typing Dispatcher.BeginInvoke(

**Actual Behavior**:

Note that there are two overloads indicated by autocompletion and overload selection:

![capture](https://cloud.githubusercontent.com/assets/10546952/14139559/c0c3de12-f66b-11e5-90a8-6f2e57b55e77.PNG)

Neither of them begins with the suggested enum though. The tooltip, however, suggests 5 overloads:

![capture](https://cloud.githubusercontent.com/assets/10546952/14139835/7a7c531a-f66d-11e5-8edf-fe5889b19daf.PNG)

...and you can use them and see them in F12 and the code compiles fine.

**Expected Behavior**:

To see all the available overloads.

EDIT: This might be consequence of #7898 and results in (otherwise fixed) #8230.

**Comment by AlgorithmsAreCool** [comment]
Could this be because 3 of the 5 overloads are marked `[Browsable(false)]` ?

https://msdn.microsoft.com/en-us/library/ms591208(v=vs.110).aspx

**Comment by miloush** [comment]
Indeed. Then the issues are:
- the discrepancy between +1 overload and +4 overloads in tooltips
- the autocomplete following a non-browsable overload
- should non-browsable attribute ensure there is no help at all or only hide the member from member list?

I would probably argue that once you call the member, you should get full experience, it is really weird to edit existing code with the intellisense showing you are using different overload than you actually are.

**Comment by miloush** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10546952/15270085/55cfd8ea-1a0b-11e6-89f2-2438ab042b14.png)

There does not seem to be any `Type.GetType()` overload with `[Browsable(false)]` attribute though, what is the +1 for?

(15.0.25302.0)

**Comment by 0xd4d** [comment]
It's `object.GetType()`

**Comment by miloush** [comment]
I see, thanks! Confused me as it is not shown in the overloads tooltip, but probably a different issue...

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
