### ISSUE TITLE
DeclarePublicAPI fixer adds a duplicate entry in PubicAPI.txt for public expression bodied members

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#1020]
Note: This repros only in RoslynDev hive not in main hive, but probably will start reproing once we update our toolset compilers/analyzers.

Repro steps:

1. Open a source file in CSharpCodeAnalysis.csproj and add a public method to CSharpCompilation so as to fire the DeclarePublicAPI diagnostic.
2. Ctrl + . and select Fix all occurrences in project and apply changes.
3. Compare the local copy of PublicAPI.txt with the unmodified version.

Got: Apart from the addition for the edit in step (1), I also get the below add in PublicAPI.txt

_Microsoft.CodeAnalysis.CSharp.Syntax.AnonymousMethodExpressionSyntax.Block { get; }_

Note that the PublicAPI.txt already contains an entry for _Microsoft.CodeAnalysis.CSharp.Syntax.AnonymousMethodExpressionSyntax.Block.get_, so probably there is some mismatch in symbol display strings for expression bodied property getter symbol?

@tmeschter  you may want to take a look. This probably started happening after #911

**Comment by tmeschter** [comment]
Fixed by e86ac3d5b312ecaff0e9c18a0b8528c6609e66d3.

**Comment by tmeschter** [comment]
Re-assigning to @mavasani for verification.
