### ISSUE TITLE
Add more test coverage for EnC

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#10203]
We should do the following:
1. Add tests for all active bugs
2. Review manual tests and see if some of them can be automated 
3. Convert EnC tests to use new helpers that provide more coverage 
4. Ensure we are dogfooding the bits

internal link to manual scripts - https://microsoft.sharepoint.com/teams/managedlanguages/_layouts/OneNote.aspx?id=%2Fteams%2Fmanagedlanguages%2Ffiles%2FTeam%20Notebook%2FRoslyn%20Team%20Notebook&wd=target%28Dev12%20Automation%20Run%20Status.one%7C86B04168-2261-480C-B8B0-F275CB54F3BB%2FManual%20Validation%7C982440AE-5286-4536-8DBC-346C9A4CEE18%2F%29
onenote:https://microsoft.sharepoint.com/teams/managedlanguages/files/Team%20Notebook/Roslyn%20Team%20Notebook/Dev12%20Automation%20Run%20Status.one#Manual%20Validation&section-id={86B04168-2261-480C-B8B0-F275CB54F3BB}&page-id={982440AE-5286-4536-8DBC-346C9A4CEE18}&end

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/36727
