### ISSUE TITLE
Project System: We should do a better job when a flavor/tooling isn't installed

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10204]
VS let's you open and explore extensibility projects even when the flavor or tools aren't installed. We should do a better job for other project types so that you can (at least) inspect the code.

![image](https://cloud.githubusercontent.com/assets/1103906/14153999/32bf48aa-f66f-11e5-8383-a2e1b6c282d5.png)
 
See: https://twitter.com/hmemcpy/status/715252172955508736

**Comment by hmemcpy** [comment]
Thanks a lot for the suggestion! I was (pleasantly) surprised by this notification, because I usually get an "Unsupported" message from the VS, having me removing GUIDs from projects :)
:+1:

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#69
