### ISSUE TITLE
Documentation for consuming feature flags is unclear

### ISSUE THREAD

**Issue by WreckedAvent** [dotnet/roslyn#10219]
**Version Used**: 
VS "15" Preview

**Steps to Reproduce**:

1. Create a new C# project
2. Add the feature flag `/features:patterns` to the command line arguments in the properties page
3. Use any pattern matching syntax
4. Error telling you to do step 2

**Expected Behavior**:

No error at step 4.

**Actual Behavior**:

![image](https://cloud.githubusercontent.com/assets/2645770/14163300/02930650-f6c2-11e5-8621-b45d585d7581.png)

**Notes**:

Also tried adding as an argument to the shortcut to launch "15", but that just triggered a help window describing what valid flags were available. 

Apologies if this is not where you enable feature flags, but I can't appear to find any documentation *at all* talking about them. Kind of weird, considering it's advertised on the download page.

**Comment by Pilchie** [comment]
That page is for specifying options to the program you want to debug, not to the compiler.  Also, `devenv.exe` (the shortcut) is the IDE, not the compiler.  To do this, you'll need to do it by editing the .csproj file directly.  Tagging @jasonmalinowski for an example property to add to the .csproj file.

**Comment by jasonmalinowski** [comment]
Yep, if you want to test a language feature, add:

    <Features>patterns</Features>

To your project file in the first `<PropertyGroup>` section.

**Comment by WreckedAvent** [comment]
Adding something in the csproj got it. Is that documented anywhere other than this page?

**Comment by jasonmalinowski** [comment]
Not that I know of. @jaredpar or @kuhlenh might know?

**Comment by WreckedAvent** [comment]
Let me put the error down for sake of google then:

    error CS8058: Feature 'pattern matching' is experimental and unsupported; use '/features:patterns' to enable.

**Comment by TheGrandUser** [comment]
Putting the features in the first property group (nor in any of the others) is not working for me, in both the enterprise and light weight installs of VS 15, so is there something else that needs to be done?

**Comment by WreckedAvent** [comment]
@TheGrandUser Hmm, I was able to make it work just by adding to the csproj as @jasonmalinowski indicated. Here's a screenshot of what's working for me:

![image](https://cloud.githubusercontent.com/assets/2645770/14213750/a9ea555c-f807-11e5-963d-19c0b1d5d23a.png)

(The IDE will complain it's not a valid element, but it will load just file)

**Comment by WreckedAvent** [comment]
Also, I forgot to reply to @Pilchie 

Yes, I know what the page is for, and I know that the shortcut goes to devenv, but there was no documentation I could find about where to apply a feature toggle. Usually, "feature toggles" would be switches to applications you'd run (ie something you'd want to add to your shortcut). Since devenv gives you a cold shoulder to this one, there's no more information scent about where you could possibly add one. 

I can't say editing the csproj is particularly intuitive. I'm certainly not the only one to then try the [debug page out of desperation](http://stackoverflow.com/questions/35075529/roslyn-features-patterns-branch-c-7-how-to-enable-the-experimental-language). Some people gave up [trying to find feature toggles all together](http://www.strathweb.com/2016/03/enabling-c-7-features-in-visual-studio-15-preview/). Even if I *had* the idea to try and play with the csproj, the IDE says that `Features` isn't a valid element.

I'm definitely not going to be the only one getting stuck on this. Some documentation or a page in properties somewhere would be perfect. Currently, the debug page is the only one that gives even remotely the correct information scent about accepting feature toggles, and it's not correct either.

Hopefully that gives you some insight as to how I ended up there, and ultimately here.

**Comment by jaredpar** [comment]
The feature flags need to be separated by a `;`

``` xml
<Features>patterns;patternsExperimental</Features>
```

**Comment by WreckedAvent** [comment]
@jaredpar either `;` or a new line works for me

**Comment by MgSam** [comment]
Can someone update the docs at https://www.visualstudio.com/news/vs15-preview-vs#CsharpAndVB to add this documentation?

**Comment by TheGrandUser** [comment]
Ok, I can confirm that fixes it. The problem seems to have been I put
```
<Features>patterns</Features>
<Features>localFunctions</Features>
```
which I think was causing it to overwrite the earlier one.

**Comment by jasonmalinowski** [comment]
@TheGrandUser: correct, that just overwrites. @MgSam, we'll look at getting that updated.

**Comment by Eyas** [comment]
For my PCL library, I added `<Features>patterns</Features>` and it worked wonderfully. Yet, for a UWP app project that I have, adding the same flag to the `.csproj` file doesn't seem to help, I still get:

    error CS8058: Feature 'pattern matching' is experimental and unsupported; use '/features:patterns' to enable.

**Comment by jasonmalinowski** [comment]
@Eyas, same NuGet package for each? I guess it's possible we may have a bug where projects consuming the compiler via project.json might be broken...

**Comment by jasonmalinowski** [comment]
@kuhlenh, can I give this to you to get the release notes updated? (cc @DustinCampbell, @Pilchie)

**Comment by kuhlenh** [comment]
Updated the documentation here: https://www.visualstudio.com/news/releasenotes/vs15/vs15-relnotes#cshappvb.

Hope that helps!

**Comment by WreckedAvent** [comment]
@kuhlenh that's much better!
