### ISSUE TITLE
Jenkins does not set the HOME environment variable on Unix machines

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#10210]
This is a big problem. The HOME variable *must* be set according to the [POSIX specification](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html):
```
HOME
The system shall initialize this variable at the time of login to be a pathname of the user's home directory. See <pwd.h>.
```

So theoretically any conforming application can break . You can see an example in this PR: https://github.com/dotnet/roslyn/pull/10161 and there are workarounds in the `Makefile` and `restore.sh` to work around this problem.

**Comment by agocke** [comment]
@mmitche I think you mean login shell, not interactive shell.

Regardless, I'm not sure if that's meaningful. We're testing code with certain expectations, including the presence of a home directory for some of them (NuGet being the big one, since NuGet packages are stored in `$HOME/.nuget/packages` by default).

That may mean we do need to create a "logged in user" (by running a login shell) for things which expect to be run in a user session. If we were testing daemons I would agree with you, but we're not. It's similar to arguing that we should be testing Visual Studio without a graphical environment because graphical environments are not runnable as daemons and are tied to a user session. The response would be (and is) that we need a user session, not that we need to disconnect our code from all user sessions.

**Comment by jasonmalinowski** [comment]
@agocke: is this still a problem?

**Comment by agocke** [comment]
@jasonmalinowski I have implemented what I believe to be a suitable workaround.

**Comment by jasonmalinowski** [comment]
@agocke Can we close this then?
