### ISSUE TITLE
Redundant Cast suggests removing cast to argument passed to params parameter when it shouldn't

### ISSUE THREAD

**Issue by markhurd** [dotnet/roslyn#10220]
**Version Used**: 
VS2015 Update 1

(I expect this is a duplicate, but I didn't find it.)

**Steps to Reproduce**:
1. Place this code in a C# Console program:

```
    class Program
    {
        static void Main(string[] args)
        {
            object[] arr = { 1, 2, "3", null, 5 };
            testParams(arr);
            testParams((object)arr);

            if (Debugger.IsAttached)
                Console.ReadLine();
        }

        static void testParams(params object[] ps)
        {
            Console.WriteLine(ps.Length);
        }

    }

```

**Expected Behavior**:
WIth the "redundant" `(object)` cast the output is 5, 1.

**Actual Behavior**:
If you allow the cast to be removed you obviously get 5, 5.

**Comment by WreckedAvent** [comment]
Another area where this issue appears:

```C#
public abstract class Result<T>
{
    internal Result() { }
}

public sealed class Success<T> : Result<T>
{
    public T Result { get; set; }
}

public sealed class Failure<T> : Result<T>
{
    public string Message { get; set; }
}

public static class ResultExtensions
{
    public static string DescribeResult<T>(this Result<T> res) => res match (
        case Success<T> succ : (Object)succ.Result match (
            case string s : s
            case int i : i.ToString("N")
            case var x : x.ToString()
        )

        case Failure<T> f : $"Error: {f.Message}"
    );
}
```

The part `(Object)succ.Result` says that the cast is redundant, but the boxing is necessary for the program to compile.

**Comment by markhurd** [comment]
I would hope a future version of the `match case` feature wouldn't need the `(object)` cast and would know the `case` matched at JIT compile of a concrete `T`.

**Comment by DustinCampbell** [comment]
@WreckedAvent -- could you file a separate issue for your repro? That's a very difference scenario for Remove Redundant Cast.

**Comment by WreckedAvent** [comment]
@DustinCampbell sure thing

**Comment by CyrusNajmabadi** [comment]
This no longer reproes.  Added https://github.com/dotnet/roslyn/pull/42073 to ensure this doesn't regress.
