### ISSUE TITLE
Code Style: 'this.' preferences fade out identifiers when the option says that 'this.' is required

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#10223]
Fading should be reserved for things that are unnecessary, such as when the options say that 'this.' is not required but it appears in the code. It's breaks the idiom of faded code to fade an identifier when something needs to be added.

**Comment by Pilchie** [comment]
Agreed.

**Comment by Pilchie** [comment]
@kuhlenh and I were talking about the design here.  We think that:
1. We need to implement #9582.
2. Redundant code should be faded for any severity other than None.
3. We need to define a UI treatment for #9582 when the issue isn't just redundant code, and use that here.
4. Warning and Error level severity should always have a squiggle of the appropriate color.

**Comment by DustinCampbell** [comment]
@pilchie, @kuhlenh, those design principles make sense to me. Do our existing faded code analyzers (unused usings, unnecessary casts) produce diagnostics with a severity of Hidden? We should probably figure out where they fit into the severities outlined by #9582.

**Comment by Pilchie** [comment]
We have the suggestion ellipsis now - we should remove the fading in this case.
