### ISSUE TITLE
Code Style: 'this.' preferences is missing an option

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#10222]
Currently, 'this.' preferences have two options:
- Prefer 'this.'
- Don't prefer 'this.'

There's a third option that is missing here, which is 'don't bother me'.

**Comment by Pilchie** [comment]
I think the right thing here is to enable the "enforcement level" column for this option.

**Comment by Pilchie** [comment]
@balajikris You just added the enforcement recently, right?

**Comment by balajikris** [comment]
@brettfo took care of this as well. Its in.

**Comment by Pilchie** [comment]
This is done now in the new UI.
