### ISSUE TITLE
Compilers shouldn't overwrite output assembly if it already exists and is byte-by-byte-identical

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#1022]
One of the main reasons of overbuilding and poor build incrementality is that any assembly change triggers cascading rebuilds of all dependent assemblies transitively.

Work is happening to make the Roslyn compiler deterministic, i.e. subsequent invocations on same inputs produce byte-by-byte identical outputs. One last piece remaining is making sure we don't overwrite the output assembly if the bytes didn't change. Even changing the timestamp of the output assembly is enough for the build tools to trigger a rebuild of dependencies. Note that we can't retroactively stamp a modified date after overwriting an assembly because project systems have FileSystemWatchers that will catch anyone writing to the file.

Fortunately Roslyn writes its output to a temporary file anyway, and then only overwrites the output at the end.

I propose to add this logic for intelligent overwriting the output from the temporary file:
 1. If the output doesn't exist, go ahead and copy
 2. If the output exists, but the file size is different than the temporary file we generated, go ahead and overwrite
 3. If the output exists, and the file size is same as the temporary file, read both files byte by byte and determine if the contents are exactly same. 
 * If there any byte that's different, go ahead and overwrite. 
 * If all bytes are equal, do nothing and exit.

The theory is that if any bytes are different, we'll encounter the difference early enough (within the first read block, since the hash is stored at the beginning of the file). Maybe just reading the hash would be sufficient. So we'll only have to read through both files and pay the IO price if they're identical - and we want it that way, to make absolutely sure we don't copy the file IFF the contents are exactly same.

Here's the current logic that deletes the existing output and moves the temp file to the final output location:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Desktop/CommandLine/CommonCompiler.cs,485

See also: #372, @gafter

**Comment by gafter** [comment]
I am skeptical that this is an appropriate thing for a command-line compiler to do.

**Comment by KirillOsenkov** [comment]
I've spoken with the build team and they agree this is something that probably belongs on the build system side. 

They could do content-based up-to-date check as opposed to timestamp comparison when copying from Intermediate (obj) to Output (bin).

**Comment by SamB** [comment]
When I've tried this sort of thing in the past, it's lead to future builds thinking that the file we avoided writing is out-of-date, since the inputs are still newer than the outputs, so the build system would try to build *that file* every time.  Is there a reason that this won't be a problem for you?

**Comment by KirillOsenkov** [comment]
That's a good point. Having this fix would break fast up-to-date check because both the build system and the project system would think the project still needs rebuilding.

Ah well. The bug is Won't Fix anyway.
