### ISSUE TITLE
Code Style: I don't see any code styles enforced unless I make an edit to a method

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#10224]
I'm not sure if this is my franken-build or a real product issue, but it's really annoying.

**Comment by Pilchie** [comment]
This seems to apply only to the "use var" rules.  Perhaps it needs to listen to an option changed event?

**Comment by Pilchie** [comment]
@dpoeschl didn't you just fix this?

**Comment by dpoeschl** [comment]
@DustinCampbell Are you talking about after making a change to your settings? Or just in general?

**Comment by dpoeschl** [comment]
If it's the former, it's now fixed by https://github.com/dotnet/roslyn/pull/13841 and this can be closed.

**Comment by DustinCampbell** [comment]
Yeah, I don't remember things 6 months ago from when I was scrambling for //build. :-)

**Comment by dpoeschl** [comment]
I'll just believe it was the former and close this.
