### ISSUE TITLE
Naming Style dialogs do not scale with their contents at higher environment font sizes

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#10225]
The dialog frames of the symbol specification and other dialogs do not increase in size when the controls within them are scaled for higher DPIs. Thus, the dialogs have to be resized manually because some controls (such as the OK and Cancel buttons) are no longer visible.

Note: This is also a problem for the Generate Type dialog.

**Comment by Pilchie** [comment]
Note - the core core Code Style\General and Naming Styles pages have issues here too.

**Comment by dpoeschl** [comment]
In the dialog constructors, do something like this (using ChangeSig as an example) instead of setting the Height/Width in xaml:
```C#
            Width = DpiHelper.LogicalToDeviceUnitsX(560);
            Height = DpiHelper.LogicalToDeviceUnitsY(420);

```

**Comment by dpoeschl** [comment]
There's all sorts of problems when you increase the environment font.

**Comment by Pilchie** [comment]
Are these usable if the user resizes Tools\Options, or are there any "must-fix" issues from a tenet perspective?

**Comment by dpoeschl** [comment]
Nothing "must-fix" for RTW. Moving to 2.1 (instead of 3.0 because that's the timeframe we'll need to fix this and all tons of other accessibility bugs)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
