### ISSUE TITLE
Code Style: Prefer 'this.' needs fix all provider for Document, Project or Solution

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#10227]

**Comment by Pilchie** [comment]
Thanks for filing.  I had started doing this on Friday, and just found the tab that hadn't saved it :smile:

**Comment by Pilchie** [comment]
@balajikris didn't you recently implement this?

**Comment by balajikris** [comment]
I think @brettfo took care of it. Pretty sure its in, just verify and close :)

**Comment by Pilchie** [comment]
@brettfo can you verify and close please?

**Comment by brettfo** [comment]
Confirmed that this works in 2017 RC.
