### ISSUE TITLE
Removing unused using formats/changes other parts of the document

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10237]
1) Remove unused usings from the following:

``` VB
Imports System

Module Module1

Sub Main()

End Sub

End Module
```

``` C#
using System;

namespace ConsoleApplication68
{
class Program
{
}
}
```

**Expected:**

``` VB
Module Module1

Sub Main()

End Sub

End Module
```

``` C#
namespace ConsoleApplication68
{
class Program
{
}
}
```

**Actual:**

``` VB
Module Module1

    Sub Main()

    End Sub

End Module
```

``` C#
namespace ConsoleApplication68
{
    class Program
{
}
}
```

Make note, while in a single file this might seem that bad - when applying this across a significant project, the Preview window shows very strange diffs like below that caused me not to trust it as it's not obvious what's changing:

![image](https://cloud.githubusercontent.com/assets/1103906/14192695/22000280-f754-11e5-92d0-7cbb5050957a.png)

**Comment by CyrusNajmabadi** [comment]
Would take a small PR here.  Remove unused usings should not touch anything but usings and *only* whitespace directly around them.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/76038.
