### ISSUE TITLE
Quick Info word wrap expands to span entire screen

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#10234]
![image](https://cloud.githubusercontent.com/assets/1402694/14190026/630b167a-f745-11e5-93a6-9bc13398a254.png)

It's less readable when it spans my whole screen...would be great to wrap at the end of the signature

**Comment by diryboy** [comment]
Commenting to get notification

**Comment by Pilchie** [comment]
I believe that since we put glyphs and colored runs in Quick Info now, we would be responsible for line wrapping.

**Comment by kuhlenh** [comment]
Ah finally found it! This is a dupe of #5.
