### ISSUE TITLE
Roslyn analyzer that restricts implementation of ISymbol should be specialized

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#1023]
The Roslyn analyzer that checks for `InternalImplementationOnlyAttribute` should be revised to remove that attribute and instead specialize the implementation to specifically test for types that contain `ISymbol` or one of its subinterfaces in the base clause.

(Action item from the 2015-03-04 LDM)

**Comment by srivatsn** [comment]
This is the same as #1510 - keeping that one since it has more history.
