### ISSUE TITLE
Missing source files error in VB breaks empty VSIX projects

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#10239]
I ran into the new missing source files VB compiler error when I created a Roslyn VB Refactoring extension in VS Update 2 (using the project template that ships as part of the Roslyn SDK) i.e. the solution we create in this case includes a VSIX project with no source files. 

The error is a result of a recent compiler (breaking) change and will break any such existing VSIX projects (regardless of whether they were created using the Roslyn SDK project templates or otherwise).

We either need to roll back this breaking change in the VB compiler
OR 
We at least need to update the VB templates included in the Roslyn SDK to generate VSIX projects with at least one (dummy) source file (ideally we should do this before we ship the next version of the Roslyn SDK).

**Comment by shyamnamboodiripad** [comment]
fyi @jaredpar @jmarolf

**Comment by davkean** [comment]
We knew about this: https://github.com/dotnet/roslyn/issues/9964. Looks like Adam closed the issue though.

The "breaking change" as per past discussions is by design to bring it inline with the native compiler 

Though, I'm not convinced that was a requirement because, it's extremely unlikely that someone was relying on this error.

**Comment by AdamSpeight2008** [comment]
@davkean This is still an issue, I've ruled out installation issues.
When I closed #9964 it was V2015 update 1

Since updated to update 2 RTM 
```
Version 14.0.25123.00 Update 2
Visual Basic 2015   00322-80000-00000-AA981
```

Maybe we should separate out the templates / samples into there own VSIXs. So can be versioned independently of the compiler?

**Comment by AdamSpeight2008** [comment]
Also the template really needs a way of specifying the NuGet version.
``
  <Target Name="AfterBuild">
    <GetAssemblyIdentity AssemblyFiles="$(OutDir)\$(AssemblyName).dll">
      <Output TaskParameter="Assemblies" ItemName="AnalyzerAssemblyInfo" />
    </GetAssemblyIdentity>
    <Exec Command="&quot;$(SolutionDir)packages\NuGet.CommandLine.3.3.0\tools\NuGet.exe&quot; pack Diagnostic.nuspec -NoPackageAnalysis -Version %(AnalyzerAssemblyInfo.Version) -OutputDirectory ." WorkingDirectory="$(OutDir)" LogStandardErrorAsError="true" ConsoleToMSBuild="true">
      <Output TaskParameter="ConsoleOutput" PropertyName="OutputOfExec" />
    </Exec>
  </Target>
```

**Comment by AdamSpeight2008** [comment]
I did what is essentially #9274

**Comment by jaredpar** [comment]
Cannot get clarity on what the correct behavior is here.  Moving out.

**Comment by gafter** [comment]
I think we want to keep the help output.

Vbc with no arguments:
    prints the command-line help text and exits

So our choices for Vbc with arguments but no source file are
1.	allowed, but often some kind of error like
`error BC30420: 'Sub Main' was not found in 'Module1'.`
2.	error BC2008: no input sources specified

I think (2) is more helpful to the users.

**Comment by davkean** [comment]
@gafter It's not helpful in the case that was broken. VSIX projects are C#/VB projects  - if you have a VSIX project that basically just references other projects and doesn't have any code itself, runs into this situation.

**Comment by jaredpar** [comment]
This behavior is by design.  Repeated attempts to ask the affected parties how this should resolve have not produced a good answer.

**Comment by jmarolf** [comment]
@jaredpar 

>Repeated attempts to ask the affected parties how this should resolve have not produced a good answer.

Who was asked and why is this unresolvable?  It seems we should issue a warning the same way C# does.  

**Warning**
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0>csc /out:cat.dll /target:library
Microsoft (R) Visual C# Compiler version 1.3.1.60616
Copyright (C) Microsoft Corporation. All rights reserved.

warning CS2008: No source files specified.
```

**Error**
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0>vbc /out:cat.dll /target:library
Microsoft (R) Visual Basic Compiler version 1.3.1.60616
Copyright (C) Microsoft Corporation. All rights reserved.

vbc : error BC2008: no input sources specified
```

If we think that the error behavior is superior, then we should change C# to have CS2008 be an error.

**Comment by AnthonyDGreen** [comment]
In C# the error is suppressed if the /out option is passed explicitly. A compromise would be to follow C# here and if /out is given not report the error. This would still preserve the behavior that if a user invokes the command-line without source files by default it will give an error.

**Comment by AnthonyDGreen** [comment]
Not, today, while C# reports a warning in this case csc.exe _also_ reports an **error** saying that if no sources are specified /out _must_ be specified.
