### ISSUE TITLE
Navigation bar in Visual Basic fully qualifies parents for nested types when it doesn't for other types

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10238]
Visual Basic fully qualifies the parent type of a nested type:

![image](https://cloud.githubusercontent.com/assets/1103906/14193309/89656f88-f758-11e5-9f4c-ba7c35ce70ad.png)

Which is a little inconsistent, I would expect it to say:

`MyAppTextWriter (MyApplicationProperties)`

**Comment by AnthonyDGreen** [comment]
Agreed on the qualification.

Also, the parenthetical doesn't imply a container relationship to me. I'd rather it say "MyApplicationProperties.MyAppTextWriter" or "MyApplicationTextWriter (Nested in MyApplicationProperties)" or  or "MyApplicationTextWriter (in MyApplicationProperties)".

For sorting reasons I'd prefer the first.

**Comment by CyrusNajmabadi** [comment]
Closing out as we're not chaning these vb experiences.
