### ISSUE TITLE
[Question] Pattern matching all kinds of a generic class?

### ISSUE THREAD

**Issue by WreckedAvent** [dotnet/roslyn#10243]
Basically, I want to replicate something like this, from F#:

```F#
type Result<'a> =
| Success of 'a
| Error of string

let print result = 
  match result with
  | Error(err) -> err
  | Success(x) -> match box x with // this line in particular
                  | :? string as str -> str
                  | :? int as i      -> i.ToString("N")
                  | _                -> (string x)
```

Ignoring for a moment there is no discriminated union support in the current "15" build, I got this far:

```C#
abstract class Result { }
abstract class Success : Result
{
    public static Result From<T>(T val) => new Success<T> { Result = val };
}

class Success<T> : Success
{
    public T Result { get; set; }
}

class Failure : Result
{
    public static Result From(string err) => new Failure { Message = err };
    public string Message { get; set; }
}
```

But I can't figure out how to replicate that one line with the current C# pattern matching syntax. I cannot just simply do this:

```C#
let result = Result.From(25);

if (result is Success<object>) { ... }
```

Since there needs to be a boxing operation that occurs *after* the match to `Success`, and one cannot cast `Success<int>` to `Success<object>`. 

Maybe it's a generics problem, and that would make sense, since the F# code uses automatic generalization. However, I don't see any way to replicate the mechanics correctly in C# at any level. 

At a rough translation:

```C#
static string Print<T>(Result res) => res match (
    case Success<T> succ : ((Object)succ.Result) match (
        case string s : s
        case int i: i.ToString("N")
        case var x: x.ToString()
    )

    case Failure f: f.Message
);
```

This works, but only if we know the type of what `Success` is, and we're right back to square one. -1 actually, since now we have to specify the type manually when calling the function.

Will there be any way to pattern match against "all" kinds of a generic class, like the automatically generic `'a` and friends from F#? Or is this just not ever going to be possible in C# semantics without some kind of kludge, like:

```C#
abstract class Success : Result
{
    public abstract object GetResult();
    public static Result From<T>(T val) => new Success<T> { Result = val };
}

class Success<T> : Success
{
    public T Result { get; set; }
    public override object GetResult() => Result;
}

static string Print(Result res) => res match (
    case Success succ : succ.GetResult() match (
        case string s : s
        case int i: i.ToString("N")
        case var x: x.ToString()
    )

    case Failure f: f.Message
);
```

**Comment by gafter** [comment]
In your F# code, Result is generic. In your C# code, it isn't. As a consequence your F# code gets the right kind of result right from the start, but your C# code doesn't. Make Print generic on T and take a Result<T>.

The CLR doesn't have any way of efficiently (i.e. without resorting to reflection) doing the kind of matching you're asking about, which is why you can't do it without having a static type in either F# or C#.

**Comment by WreckedAvent** [comment]
Hmm, that seems like it might work. The C# compiler should be able to infer generic of T in that case if Result is also generic on T. 

That would move the problem up one further wherein one couldn't match any `Result`, but that's probably acceptable for the use cases I'm imagining.

**Comment by WreckedAvent** [comment]
Though slightly verbose and not usual for C#, that did work. Here's what I came up with, in case anyone else tries this:

```C#
public abstract class Result<T>
{
    internal Result() { }
}

public sealed class Success<T> : Result<T>
{
    public T Result { get; set; }
}

public sealed class Failure<T> : Result<T>
{
    public string Message { get; set; }
}

public static class Result
{
    public static string GetValue<T>(this Result<T> res) => res match (
        case Success<T> succ : (Object)succ.Result match (
            case string s : s
            case int i : i.ToString("N")
            case var x : x.ToString()
        )

        case Failure<T> f : $"Error: {f.Message}"
    );

    public static Result<R> Map<T, R>(this Result<T> r, Func<T, R> transform) => r match (
        case Success<T> s : Success.From(transform(s.Result))
        case Failure<T> f : Failure.From<R>(f.Message)
    );
}
```

Signature for `map` is a bloody ripper, but at least the actual implementation is quite simple.
