### ISSUE TITLE
Proposal: Add the null-aware assignment operator

### ISSUE THREAD

**Issue by jolleekin** [dotnet/roslyn#10249]
It will be very helpful if C# can support the null-aware assignment operator.

``` c#
// If [x] is null, assign [y] to [x].
x ??= y;
```

This operator is inspired by [Dart](http://news.dartlang.org/2015/08/dart-112-released-with-null-aware.html)

**Comment by HaloFour** [comment]
Dupe of #9529, #8894, #3366, #205

**Comment by gafter** [comment]
Discussion moved to https://github.com/dotnet/csharplang/issues/34.
