### ISSUE TITLE
nameof isn't listed as valid input of an attribute in error message.

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/roslyn#10242]
**Version Used**: 
VisualStudio 14.0.24720.00 Update 1
**Steps to Reproduce**:

1. Add attribute accepting parameters in valid location (ie, Xunit's `InlineData` to a method).
2. Add some non-compile-time (or otherwise invalid) parameter (ie, `[InlineData(Environment.ProcessorCount)]`
3. Check error message, either via mouseover or build.

**Expected Behavior**:
The error string should include `nameof` as an acceptable expression, such as:
> An attribute argument must be a constant expression, typeof expression, **nameof expression,** or array creation expression of an attribute parameter type

**Actual Behavior**:
The error string states:
> An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type

**Comment by Clockwork-Muse** [comment]
side note: Oxford comma?

**Comment by gafter** [comment]
a nameof expression is a kind of constant expression, so the error message is actually complete.

**Comment by Clockwork-Muse** [comment]
@gafter - okay, but then (curious) why is `typeof` listed as well?  Feels a little strange to call out one and not others.

**Comment by gafter** [comment]
Because `typeof` does not give a constant.
