### ISSUE TITLE
Instrument parts of synthesized methods that come from explicit program code

### ISSUE THREAD

**Issue by JohnHamby** [dotnet/roslyn#10266]
.e.g. field initializes, both static and instance.

At present instrumentation is omitting synthesized methods, which is incorrect when the method bodies include code that comes from program text.

**Comment by amcasey** [comment]
Field-like events should probably have the same level of instrumentation as auto-props, even though the accessors of the former lack syntax.

**Comment by JohnHamby** [comment]
Fixed, for member initializers
