### ISSUE TITLE
Ability to track issue priorities

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#10267]

**Comment by gafter** [comment]
What does this mean?

**Comment by Pilchie** [comment]
The IDE team wants to eliminate the strong areas of ownership we have among features, instead having everyone pick the "most important" items to work on first, instead of whatever happens to be assigned to them.  However, GitHub doesn't provide a very good way to give an ordering to bugs, so we're thinking of building a simple external site that would just map issue->ordinal.

**Comment by CyrusNajmabadi** [comment]
Closing out.
