### ISSUE TITLE
Remove NamedTypeSymbol.TypeArguments and other dangerous properties

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#10265]
This issue was originally tracking fixing analyzers to prevent us from using this property and some other ones like it. Aleksey suggested we might as well remove those dangerous properties instead.

----

`TypeArguments` is banned inside the compiler, it looks like we missed this in analyzer.

`TypeArgumentsNoUseSiteDiagnostics` should be used instead if you are not interested in use-site diagnostics, and `TypeArgumentsWithDefinitionUseSiteDiagnostics` if you are. The goal to make this choice explicit.

**Comment by jcouv** [comment]
This came up in the discussion for #10187

**Comment by srivatsn** [comment]
This analyzer is specific to the compiler code. Moving to the compiler team after talking with @jaredpar

**Comment by jcouv** [comment]
`TypeArguments` has already been updated (it now calls `TypeArgumentsNoUseSiteDiagnostics`). The other dangerous properties have be updated as well.
Closing this issue.
