### ISSUE TITLE
Request: Allow Roslyn to be used for other compilers

### ISSUE THREAD

**Issue by leppie** [dotnet/roslyn#10260]
I have started to investigate how to use Roslyn to write your own compiler.

When analyzing some of the basic structures used in the Core library (`Microsoft.CodeAnalysis`), I noted that some `abstract` classes have `internal abstract` members [1]. Obviously as internals are visible to the C# and VB.NET compilers, this is not a problem, but it makes it impossible to use the Core library for your own compiler.

I have not done a full analysis, but it would be helpful to remove these limitations, so that the publicly available library could be used without having to resort to a custom build of Roslyn (which will have other implications too).

As a start, I will try to make a minimal compiler example (something like a calculator) to identify these limitations. The idea is to only use `Microsoft.CodeAnalysis` (as I believe the original intention of the CCI was).

One of the eventual aims here is to expose language-agnostic compiler passes to any language.

**Note:** This is a work-in-progress.

[1] Notably in the `Compilation` class.

**Comment by gafter** [comment]
You are essentially asking us to make the existing `internal` members `public` instead, thereby requiring us to freeze them in their current API form for compatibility reasons.

**Comment by leppie** [comment]
@gafter Not really, but more specifically asking `internal abstract` to be marked `protected abstract` instead. I understand there might be compat issues, but at least it can be discussed, or another gateway can be exposed that will not interfere.

**Comment by DavidArno** [comment]
@leppie, `protected` is still part of the public API and thus would require them to be frozen as @gafter says.

I'm not part of the language team, so what I'm describing here may not be the way Microsoft do such things. Normal behaviour though with open-source projects would be to follow the principles of encapsulation and only mark things `protected`/`public` when absolutely necessary, as it's easy to go from `internal` to `public`, but going the other way becomes a breaking change. So you could try forking the code, then make only make `public`/`protected` the bear minimum to get your compiler working, then submit those changes as a pull-request with details of why you needed to make those changes.

**Comment by svick** [comment]
Is the guarantee of "whatever is public will not break" absolute?

Would it be possible for example to create `Microsoft.CodeAnalysis.Internals`, which would have access to internals of `Microsoft.CodeAnalysis` and would expose them as `public`/`protected`? `Microsoft.CodeAnalysis.Internals` would be very explicitly documented as not having the same compatibility guarantees as the rest of Roslyn API.

It is a hacky solution, but that might be acceptable for something like this.

**Comment by leppie** [comment]
I thought about this more and it seems @svick's suggestion is the most viable at the moment. This way the `public` API can grow in an experimental way. 

Now to start hacking :)

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
