### ISSUE TITLE
Navigation: Support forward and backward slashes in Navigate To

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#10275]
Filed on behalf of a customer from interviews.

**Comment by DustinCampbell** [comment]
Is there a description of what the expected behavior should be?

**Comment by Pilchie** [comment]
I assume this is intended for finding file names?  If so, we should file against the VS Platform team, since they own the file name provider.

**Comment by DustinCampbell** [comment]
Let's start with filing this on the Platform team.

**Comment by CyrusNajmabadi** [comment]
Tagging @olegtk @veler .  Closing this out on the roslyn side.
