### ISSUE TITLE
Core Editing: IntelliSense is fighting me when I type things that don't exist yet

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#10279]
Filed on behalf of a customer from interviews.

**Comment by dfkeenan** [comment]
Isn't that what Completion Mode is for? (Toggle Completion Mode Ctrl+Alt+Space).

Though I never remember what that shortcut is. Maybe a toggle button on the completion window would help.

**Comment by Pilchie** [comment]
There is already a toggle button on the main VS toolbar, though I agree it's not very discoverable.

Perhaps a new toggle on the completion list itself would fit in with the other filters we're doing.  Thoughts @kuhlenh @DustinCampbell @CyrusNajmabadi?

Also, maybe we should persist the value of the toggle between VS sessions.

**Comment by CyrusNajmabadi** [comment]
We need to know why existing solutions don't work for customers here.
