### ISSUE TITLE
Code Style: Add fix to toggle between "using" and "using static"

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#10274]
Filed on behalf of a customer from interviews.

**Comment by Pilchie** [comment]
Do you have a good picture of how this would work?  A regular `using` imports the whole namespace, what if more than one type is used from that namespace?  Or is is this only if you have something like `using ConsoleColors = System.ConsoleColors;`?

**Comment by DustinCampbell** [comment]
Hey @kuhlenh -- @Pilchie and I aren't sure what this request actually is. If you have more info, that'd be great! Thanks!
