### ISSUE TITLE
Navigation: I can't remember the shortcut key for Navigate To

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#10286]
Filed on behalf of a customer from interviews.

Note: this speaks to our larger issue of feature discoverability.

**Comment by DustinCampbell** [comment]
This isn't actionable @kuhlenh

**Comment by Pilchie** [comment]
Agreed - I remember it just fine :)

**Comment by Pilchie** [comment]
Note that we added `Ctrl+T` as an easier shortcut for "Go To"
