### ISSUE TITLE
Breaking change: VB can no longer assign to static readonly field of another instantiation

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#1028]
The following code compiled and ran on previous versions of VB. In Roslyn this does not compile:

```vb
Class Foo(Of T)
    Shared Sub New()
        Foo(Of Integer).X = 12
    End Sub

    Public Shared ReadOnly X As Integer
End Class
```

The native compiler allowed this code, and the code runs “correctly” when the verifier is disabled. However, it is certainly not allowed by the intent of the language specification, the code almost certainly contains an error, and the generated code violates the CLI specification (for the init-only constraint). The verifier rejects the generated code, but most invocations of the CLR skip the verifier.

I propose we continue to reject this code in Roslyn and document the incompatibility that results from the fact that the implementation has been tightened.

See also #990 

@ljw1004 @AlekseyTs @AnthonyDGreen What do you think?

**Comment by ljw1004** [comment]
I agree that the code should be rejected in Roslyn. We've always considered a compiler bug when we generate unverifiable code.

**Comment by gafter** [comment]
@AnthonyDGreen @DustinCampbell @ljw1004 @MadsTorgersen @gafter @srivatsn @theoy Paging the compat council to consider the proposed outcome.

**Comment by theoy** [comment]
Since the C# workitem was rc2, also putting this in rc2.

**Comment by gafter** [comment]
Compat council outcome was same as for C#: code should be accepted even though incorrect, and diagnosed under `/feature:strict` and in the first warning wave.

**Comment by gafter** [comment]
@VladimirReshetnikov Can you please "Verify" this fix?
