### ISSUE TITLE
Navigation: Have a way to do "reverse navigation"

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#10288]
Filed on behalf of a customer from interviews.

Customers are writing (with pen and paper) the files and types they have visited in their "exploration" or "deep dive" sessions in order to navigate back to where they first started drilling down.

**Comment by svick** [comment]
Isn't that what Navigate Backward (first button in the Standard toolbar, shortcut <kbd>Ctrl</kbd>+<kbd>-</kbd>) is for?

**Comment by Pilchie** [comment]
I think that plus bookmarks: <kbd>Ctrl</kbd>+<kbd>K</kbd>,<kbd>Ctrl</kbd>+<kbd>K</kbd>, would help if more people knew about them.

(Mice with back buttons also have them mapped to Edit.NavigateBackward, btw.

**Comment by kuhlenh** [comment]
Yeah, it seems like very few people know about or use these features...

**Comment by Pilchie** [comment]
There's also a big "Back" button on the toolbar, like a browser, that invokes Navigate Backward.

I think we need a more concrete proposal here.

**Comment by Pilchie** [comment]
Potentially related to #14496
