### ISSUE TITLE
[Proposal] VB Feature Implicit Default Optional Parameter

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#10293]
The grammar definition for an `Optional Parameter` is something similar to this.

```
OptionalParameter ::= "Optional" ParameterName Typing? DefaultToValue?
           Typing ::= "As" TypeIdentifier
   DefaultToValue ::= "=" ( "Nothing" | ConstantValue )
```

**Examples**

``` vb.net
Foo( Optional arg0 ) ' --> Foo( Optional arg0 As Object = Nothing )
Foo( Optional arg1 As String ) ' --> Foo( Optional arg1 As String = Nothing )
Foo( Optional arg2 As String = Nothing ) ' --> Foo( Optional arg2 As String = Nothing )
Foo( Optional arg3 = "" ) ' --> Foo( Optional arg3 As String = "" )
Foo( Optional arg4 As Integer ) ' --> Foo( Optional arg4 As Integer = Nothing )
Foo( Optional arg5 As Integer = 0 ) ' --> Foo( Optional arg5 As Integer = 0 )
Foo( Optional arg6 As Integer = 1 ) ' --> Foo( Optional arg6 As Integer = 1 )
Foo( Optional arg7 = 7 ) ' --> Foo( Optional arg7 As Integer = 7 )
```

It will simplify the common cases of optional parameter.

**Comment by AnthonyDGreen** [comment]
Hey @AdamSpeight2008, love this idea!

I think defaulting the default value of the parameter to the default value of the type of the parameter, in the absence of an explicit default value is the way to go. Would save a lot of typing. I'm hesitant about inferring the type of the parameter from the default value expression. We generally avoid expanding type inference outside of local variables for a lot of reasons. A thing I do when I have language change ideas like this is to comb large VB codebases like Roslyn to see how much code would be impacted by my proposal. So in your case I wrote this little script (using the Roslyn Console App template in the Roslyn SDK):

``` VB.NET
Imports System.Console
Imports System.IO

Module Program

    Sub Main()
        Dim log = New StringWriter()

        Dim nothingDefaultCount = 0,
            nonNothingDefaultCount = 0

        For Each filename In Directory.EnumerateFiles("<roslyn-repo-path>", "*.vb", SearchOption.AllDirectories)
            Dim tree = VisualBasicSyntaxTree.ParseText(File.ReadAllText(filename))

            Dim root = tree.GetRoot()

            For Each decl In root.DescendantNodes.OfType(Of ParameterSyntax)
                If decl.Default Is Nothing Then Continue For

                If decl.Default.Value.IsKind(SyntaxKind.NothingLiteralExpression) OrElse
                   decl.Default.Value.IsKind(SyntaxKind.FalseLiteralExpression) OrElse
                   decl.Default.Value.ToString() = "0" _
                Then
                    nothingDefaultCount += 1
                Else
                    nonNothingDefaultCount += 1

                    Dim text = decl.ToString()
                    WriteLine(text)
                    log.WriteLine(text)
                End If
            Next
        Next

        WriteLine(nothingDefaultCount)
        WriteLine(nonNothingDefaultCount)

        My.Computer.Clipboard.SetText(log.ToString())
    End Sub
End Module
```

Running it on my roslyn repo clone it reports that of all the optional parameter declarations in VB in Roslyn 2229 out of 2612 of them, or > 85% use the default value of the parameter type as the default value of the parameter. So your suggestion would clean up **85%** of the uses of Optional in Roslyn. Sounds like value to me!

**Send. A. Pull. Request.**

Regards,

**-ADG**

**Comment by AdamSpeight2008** [comment]
@AnthonyDGreen Could you tag it `up for grabs`. As it was proposal / spec for a language feature not an implementation.

**Comment by AdamSpeight2008** [comment]
@AnthonyDGreen Out of curiosity would this a breaking change?
As if we currently forget the **default value** aspect we should get the following errors.
```
error BC30812: Optional parameters must specify a default value.
error BC30201: Expression expected.

```

**Comment by AdamSpeight2008** [comment]
@AnthonyDGreen + @gafter 
I have an implementation of this, just wait for the repo and branch to sync and push.

**Comment by AnthonyDGreen** [comment]
You are correct, it's not a breaking change.

**Comment by AdamSpeight2008** [comment]
@AnthonyDGreen Here is a screenshot of my implementation working. (Just needs the UnitTest fixing)
![optionalvalueaspectforoptionalparameters](https://cloud.githubusercontent.com/assets/900107/15130566/598bea78-1641-11e6-8c8d-0ba009b66c09.jpg)

**Comment by AdamSpeight2008** [comment]
This the [Development Branch](https://github.com/AdamSpeight2008/roslyn-AdamSpeight2008/tree/Implements_10293) I am work with.

**Comment by AdamSpeight2008** [comment]
When the run the following code (should be semantically equivalent ).
**Currently**
```vb
Imports System.Runtime.CompilerServices
Module Module1

    Sub Main()
        Dim r = Foo()
        Console.WriteLine(r)
    End Sub

    Function Foo(<CallerLineNumber> Optional x As Integer = 0) As Integer
        Console.WriteLine(x)
        Return x
    End Function

End Module
```
output
```
R=5
X=5
```

**Proposed**

```vb
Imports System.Runtime.CompilerServices
Module Module1

    Sub Main()
        Dim r = Foo()
        Console.WriteLine(r)
    End Sub

    Function Foo(<CallerLineNumber> Optional x As Integer) As Integer
        Console.WriteLine(x)
        Return x
    End Function

End Module
```
output
```
R=0
X=0
```

This is the current block to progressing with this. Seem that it doesn't emit the correct code.
Putting in the ` = 0` on the parameter returns the expected values.

**Comment by gafter** [comment]
@AdamSpeight2008 We want both versions to print `R=5 X=5`. When you have it working, please add a unit test to demonstrate that is the way it works.

**Comment by AdamSpeight2008** [comment]
@gafter 
The unit tests already exist as they're based on the existing ones, just tweaked for the feature. [Here](roslyn-AdamSpeight2008/src/Compilers/VisualBasic/Test/Semantic/Semantics/OptionalArgumentTests_ImplicitDefaultValue.vb)

I've been trying to ask why / what could cause this particular case not work.

**Comment by AdamSpeight2008** [comment]
Looks like the Foo arguments are being passed in correctly. Just not being assigned to the parameter.

**Comment by AdamSpeight2008** [comment]
Currently the Implementation is tentatively producing the expected output.

**Comment by AdamSpeight2008** [comment]
Somehow it has messed up overload resolution. I try and fix that.

**Comment by AdamSpeight2008** [comment]
_@AnthonyDGreen As I've been struggling to implement this feature, I thought I'd stop and get some feedback. To see if I'm approaching this in the correct / wrong way._

# Implicit Default Value On Optional Parameter

The aim of the proposal is to see if it possible to make the **default value**, that currently as to explicitly expressed can be made optional.

### Examples

The existing code
```vb.net
Public Function Example( Optional x As Integer = 0, Optional s As String = Nothing )

End Function
```
can written as
```vb.net
Public Function Example( Optional x As Integer, Optional s As String )

End Function
```

This would reduce a lot of boiler-plate code for the likely common usage of just needing the default value of the type (eg ` parameter = default(T)` ).
Will still permitting the expressing of a different value, should the coder require one.

----------------------------------------

# Research


## Grammar Definition 
```
Parameter
    : Attributes? ParameterModifier* ParameterIdentifier ( 'As' TypeName )?
      ( Equals ConstantExpression )?
    ;
```
So the Visual Basic Grammer (VB14) allows for an optional default value `( Equals ConstantExpression )?`.

### Errors

`Default Value For Non Optional Parameter`
```vb
Method( x As Integer = 0)
```
`Obsolete Optional Without Value`

```vb
Method( Optional x As Integer)
```

==Compat== Must maintain this when language version doesn't support Implicit Default Value On Optional Parameter.

**Caller Information Attributes**
```vb
( <CallerLineNumber> Optional line As Integer = 0 )
( <CallerMethodName> Optional method As String = Nothing )
( <CallerFilename>   Optional filename As String = Nothing )
```
**(Compat)** These should continue work, even when using the feature.

----------------

## __Code Examination__

## __Parser__

After a search of the Parser code
 + [ParseParameter](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Parser/Parser.vb,4576)
```vb
Dim equals As PunctuationSyntax = Nothing
Dim value As ExpressionSyntax = Nothing

' TODO - Move these errors (ERRID.ERR_DefaultValueForNonOptionalParamout, ERRID.ERR_ObsoleteOptionalWithoutValue) of the parser. 
' These are semantic errors. The grammar allows the syntax. 
If TryGetTokenAndEatNewLine(SyntaxKind.EqualsToken, equals) Then

	If Not (modifiers.Any AndAlso modifiers.Any(SyntaxKind.OptionalKeyword)) Then
		equals = ReportSyntaxError(equals, ERRID.ERR_DefaultValueForNonOptionalParam)
    End If

    value = ParseExpressionCore()

ElseIf modifiers.Any AndAlso modifiers.Any(SyntaxKind.OptionalKeyword) Then

    equals = ReportSyntaxError(InternalSyntaxFactory.MissingPunctuation(SyntaxKind.EqualsToken), ERRID.ERR_ObsoleteOptionalWithoutValue)
    value = ParseExpressionCore()

End If
```
Make the body of the second condition dependant on the feature's availability.

```vb
Dim initializer As EqualsValueSyntax = Nothing

If value IsNot Nothing Then

	If value.ContainsDiagnostics Then
		value = ResyncAt(value, SyntaxKind.CommaToken, SyntaxKind.CloseParenToken)
	End If

    initializer = SyntaxFactory.EqualsValue(equals, value)
End If

Return SyntaxFactory.Parameter(attributes, modifiers, paramName, optionalAsClause, initializer)

```
Depending on the code change, the following could be null `value = nothing` and `equals = nothing`.
We would require to modify these conditions. 

 + [ParseParameters](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Parser/Parser.vb,4419)

 I do not see any potential issue within this function, when using the feature.

 + [ParseParameterList](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Parser/Parser.vb,3671)

I do not see any potential issue within this function, when using the feature.


## __Syntax__

**`SyntaxFactory.Parameter`**


## __Semantics__

### Overload Resolution

[OverloadResolution.OptionalArgument](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Semantics/OverloadResolution.vb,509) **(Potential Issue)**
 + What if `DefaultValue = Nothing` ?
 + Is it expected to be non-null?

 Handle [Optional Parameters](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Semantics/OverloadResolution.vb,3056) **(Potential Issue)**
 + If this returns `null` then should I do check for the feature and assign "default" value to `default argument`?

## __Symbol__


[ParameterSymbol](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Symbols/ParameterSymbol.vb,138) **(Potential Issue)**
```vb
''' <summary>
''' Returns the default value of this parameter. If <see cref="HasExplicitDefaultValue"/>
''' returns false, then this property throws an InvalidOperationException.
''' </summary>
Public ReadOnly Property ExplicitDefaultValue As Object
    Get
        If HasExplicitDefaultValue Then
            Return ExplicitDefaultConstantValue.Value
        End If
 
        Throw New InvalidOperationException
    End Get
End Property
```

This feature would not have an explicit default value, as it let's the coder not declare one.
So the options are:-
 + Add an additional condition based on the on feature's availiblity, to return a different value.
 + At the usage sites, catch the exception then, modify the usage.

 [Emit.ParameterSymbolAdapter](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Emit/ParameterSymbolAdapter.vb,f2e85a004c64ee62) **(Potential Issue)**
  + `HasMetadateConstantValue`
  + `GetMetadataConstantValue`
  + `IParameterDefinition_HasDefaultValue`

 
  [Emit.NoPia.EmbeddedParameter](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Emit/NoPia/EmbeddedParameter.vb) **(Potential Issue)**
   + `HasDefaultValue`
   + `GetDefaultValue`

## __Binding__


[Binding.Binder_Invocation](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Binding/Binder_Invocation.vb,3025) **(Potential Issue)**

+ Comment `HasDefaultValue` indicates `(Parameter.IsOptional == True) && (Parameter.DefaultValue <> null)`
+ Deals with **Caller Info Attributes** eg `<CallerLineNumber>`, `<CallerMethodName>`, `<CallerFilename>`
+ `ElseIf param.IsOptional Then` [Here](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Binding/Binder_Invocation.vb,3153)
  + Suggests that this branch is taken on `( Optional p As Integer )`
  + If it is the **Caller Info Attributes** are ignored (_bug?_)

+ [BindParameterDefaultValue](https://github.com/dotnet/roslyn/blob/586f37ae8ee27162ea334a22d6b431cdd5e05a14/src/Compilers/VisualBasic/Portable/Binding/Binder_Initializers.vb#L641)
+ [InitializerSemanticModule.BindInitializer](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Binding/InitializerSemanticModel.vb,139)

**Comment by AdamSpeight2008** [comment]
Think I've solved the issue with overload resolution.
I also have implemented an Analyser + Code Fix for the feature.

**Comment by AdamSpeight2008** [comment]
![optionalparameterswithimplictdefault](https://cloud.githubusercontent.com/assets/900107/17146359/0b212aa4-5356-11e6-809b-858d7b6586a8.png)

Still needs a a little work on it to make it check for the feature's presence first.

**Comment by jaredpar** [comment]
Given this is a language proposal we should move this to dotnet/vblang.  Closing here.

**Comment by AdamSpeight2008** [comment]
[Ported to VBLang ](https://github.com/dotnet/vblang/issues/29)
