### ISSUE TITLE
[Proposal] Make From Base

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#10297]
This proposal is for the compiler (and or) runtime to automatically implement aspects of a derived implementation based on its base.

[Example](https://github.com/AdamSpeight2008/Ideas/blob/master/MakeFromBase/Example.vb)

Those `make` marked methods are `protected friend` (or not implement) within the base, they are to constructed into the derived implementation. eg if I cast my derived type to it's base, then the operators are not available.

The derived implementation's type is indicated with `@base`. If the base class was called foo the it'll be `@foo`. If it was generic `@base<T>`
It also acts as constraint that the derived must inherit it. 

```
dim  empty0 = Tokens.Empty()  ' The Empty singleton for type Tokens
dim  empty1 = Issues.Empty()   ' The Empty singleton for type Issues
dim  empty2 = Pile<Issue>.Empty ' <-- Error.

dim  foo = empty0 + empty1 ' <-- Error: Tokens does't implement operator [+](Tokens, Issue)
```

**Comment by gafter** [comment]
Closing as discussion appears to have died down.
