### ISSUE TITLE
VSIX Problems

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#10296]
Related to #10239 

**Version Used**: 
```
Microsoft Visual Studio Enterprise 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038


Visual Basic 2015   00322-80000-00000-AA981
Microsoft Visual Basic 2015
```

**steps**

Ok I've managed to get the vsix to build (using #9274)
On debugging / running the Vsix I get the following error in the Roslyn Instance of VS

```
Warning	AD1000	An instance of analyzer VS_Analyser.Analyzer1Analyzer cannot be created from {snip}\VS_Analyser.dll:
 Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..			1	Active
```

It's as if the dependency on Roslyn DLL are not being copied in to vsix.
Ok so I've manual inserted the dlls into the vsix. via the `.zip` method.

Ok the vsix can be installed 
Now issue is
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	BC42377	The assembly {snip}\VS_Analyser.dll does not contain any analyzers.	ConsoleApplication1		1	Active

```

I've check the DLL via inspecting with ILSpy it does contain at least on analyser.

**Comment by srivatsn** [comment]
Which VSIX are you talking about? How do we repro this issue?

**Comment by AdamSpeight2008** [comment]
Same steps as #9964

**Comment by srivatsn** [comment]
The repro steps for #9964 says you've created a VB analyzer from the template and just hit F5. Since you have update 2, your analyzer should be referencing Microsoft.CodeAnalysis v1.2. However the error you've pasted says it's unable to find Microsoft.CodeAnalysis v 2.0 (which is from from the future branch). So you must have some mixed up binaries\references that's causing the problem.

**Comment by Pilchie** [comment]
Note - I'm pretty sure the templates actually still reference 1.0 packages, since there isn't significant new surface area in 1.2 that would make it worth most analyzers not running on 1.0/1.1.

cc @jmarolf

**Comment by jmarolf** [comment]
@AdamSpeight2008 you should be using the 1.0 version of the Microsoft.CodeAnalysis nuget packages.  https://github.com/dotnet/roslyn/issues/10239 Will break all of your analyzer or codefix projects so I would either add a dummy VB file to get around the compiler error, or not upgrade to Update 2 at this time.

**Comment by AdamSpeight2008** [comment]
Microsoft.CodeAnalysis v2.0 is likely being pulled in via NuGet, if I have included pre-release ticked. I still would have expected it to work, or it to give warnings if it potentially won't.

---- Srivatsn Narayanan wrote ----

**Comment by srivatsn** [comment]
If you are building the analyzer against v2.0 then when launching VS, VS would need to have 2.0 binaries loaded whereas Update 2 has the 1.2 binaries loaded in memory and so it won't work.

**Comment by BADF00D** [comment]
Hi, sorry for posting in this closed issue, but I think I have a related problem. 
@srivatsn Does this imply, in order to support multiple version of an VS Extension using analyzers, I have to publish multiple VS Extension. Like the guy from roslynator? he is publishing a Roslynator 2017 and a Roslynator 2019 separately.

**Comment by jmarolf** [comment]
@BADF00D you need to target the lowest api version that you intend to support. Roslynator needs to do this because they want to take advantage of the new apis for vs 2019 while still offering a compatible version for vs 2017

**Comment by BADF00D** [comment]
@jmarolf Thanks for the reply. I finally found an office Microsoft overview about the roslyn version to use in a certain Visual studio Version: [Roslyn version support](https://docs.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2019)
