### ISSUE TITLE
[Bug] Redundant "Remove Unnecessary Cast" with pattern-matching

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/roslyn#10306]
**Version Used**: 
Microsoft Visual Studio Enterprise 15 Preview
Version 15.0.25123.0 PREVIEW
Microsoft .NET Framework
Version 4.6.01038

**Steps to Reproduce**:
Write a code:
```cs
static class Program
{
  static void Main(string[] args) {
    switch((object)args) {
        // ^~~~~~~^ cast marked as IDE0004  C# Cast is redundant.
    case int[] i:
      break;
    }
  }
}
```
1. Compile code: succeeded
2. Remove cast and compile code: error CS0030: Cannot convert type 'string[]' to 'int[]'

**Expected Behavior**:
Do not suggest to remove a type cast.

**Comment by Pilchie** [comment]
Moving back to compilers.

**Comment by gafter** [comment]
@Pilchie What would you like the compiler to do differently here?

**Comment by alrz** [comment]
A) Due to `CS0553` downcasts in pattern-matching `switch` are always redundant.
B) In this example `case int[] i` is known to be unreachable for `string[] args`.
C) There is no bug.

**Comment by gafter** [comment]
I will dig into the IDE implementation and see why this is failing.

**Comment by gafter** [comment]
This has nothing to do with the compiler, but fixed anyway in #13798

**Comment by ViIvanov** [comment]
@gafter Thanks, but is condition
    …expressionToCastType.IsUnboxing
will be `true` for casting from `string[]` to `object`?

**Comment by gafter** [comment]
@ViIvanov no, that's an implicit *reference* conversion.

**Comment by ViIvanov** [comment]
Thanks, looks like I do not understand something, but how you commit fixes my issue?
May be, my issue fixed with some other commit? In any case I will check it in the next Preview :o))

**Comment by gafter** [comment]
The commit fixes the issue by adding the unboxing conversion (e.g. from `object` to `int`) to the set of conversions that have semantic behavior, and therefore cannot be removed.

**Comment by ViIvanov** [comment]
@gafter Thank you for explanation, will try to understand it
