### ISSUE TITLE
Wrong "Cast is redundant" suggestion when returning negated bool

### ISSUE THREAD

**Issue by peter-h4nsen** [dotnet/roslyn#10311]
**Version used**:
Microsoft Visual Studio Enterprise 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038

**Steps to Reproduce**:
Write the following code:

    public bool NegateBool(object value)
    {
        // "Cast is redundant".
        return !(bool)value;
    }

2. Follow the suggestion to "Remove Unnecessary Cast".

3. Now the code can't compile: Operator '!' cannot be applied to operand of type 'object'

**Expected Behavior**:
Should not suggest to remove the cast.

**Comment by mburbea** [comment]
Amazingly enough, arrow notation does not declare the cast redundant
```csharp
public bool NegateBool=>!(bool)value;
```
