### ISSUE TITLE
SyntaxGenerator should keep modifiers and statement blocks consistent

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#10327]
When you make a method abstract with WithModifiers API the resulting node should not have a statement block, because that is not legal syntax, VB or C#

When you make a method not abstract with WithModifiers API the resulting node should have statements, because without statements is not legal syntax, VB or C#

When you add statements to a method that is currently abstract, that method should change to virtual to make it consistent with the statements being added.

**Comment by svick** [comment]
> When you add statements to a method that is currently abstract, that method should change to virtual to make it consistent with the statements being added.

I'm not sure what is the design philosophy of `SyntaxGenerator`, but this doesn't sound like the obvious behavior to me. Wouldn't throwing an exception in such case be a better option?

In other words, if I do want to change `abstract` method to non-`abstract`, I think requiring me to be explicit about it makes sense.

**Comment by mattwar** [comment]
@svick, it is possible that one is a bit of a reach.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
