### ISSUE TITLE
Test Microsoft.CodeAnalysis.UnitTests.Interactive.InteractiveHostTests.StackOverflow is flaky

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#10323]
Previous failures:

- http://dotnet-ci.cloudapp.net/job/roslyn_future_win_rel_unit32/169/
- http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/5846/

**Comment by ManishJayaswal** [comment]
@tmat  can you take a look at this?
