### ISSUE TITLE
[Test Failure] Compile Error in prtest/lin/dbg/unit32 on PR #10263

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#10336]
PR: [#10263](https://github.com/dotnet/roslyn/pull/10263) *Merge from future into features/patterns* by @gafter
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/5806/

**Issue 1: Compile Error**
error CS2001: Source file '/mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/Binaries/Obj/CSharpCodeAnalysis/Debug/BoundNodes.xml.Generated.cs' could not be found. [/mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj]

**Comment by jaredpar** [comment]
Not reproducing for some time.
