### ISSUE TITLE
Feature Request: Add quick fixes for reference to inaccessible type

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#10337]
If I use a type from a location it isn't visible to, I get a CS0122 for the reference, but no quick fixes at all.

This should offer the usual quick fix to create a new type, plus, if it's not from metadata, a new action to make the type public (ideally recursively publicising all types of now-public members)

**Comment by CyrusNajmabadi** [comment]
We would probably take a PR for this.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
