### ISSUE TITLE
[Feature Request] Add Pattern Matching feature in LINQ

### ISSUE THREAD

**Issue by t-smirnov** [dotnet/roslyn#10340]
Sorry, if duplicate

So, are you considering feature, that provides using keyword 'match' (like we're using it in F#) in LINQ queries? Is it possible to implement 'match' in C# using F# way?

**Comment by DavidArno** [comment]
It is a duplicate. Please see #10153. It might be called `match`, or it might end up as `switch`, but pattern-matching expressions are being prototyped and hopefully will make it into C# 7.

**Comment by t-smirnov** [comment]
@DavidArno oh, thanks.

**Comment by HaloFour** [comment]
And #6877, which is probably less likely to make the C# 7.0 cut.
