### ISSUE TITLE
Update all PublicAPI.txt in Roslyn.sln and move to a newer toolset

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#1034]
#359 updated DeclarePublicAPI analyzer to include returns types in symbol names. However, we haven't updated our toolset analyzers to include the fix. This makes Roslyn.sln unsuable in RoslynDev hive for debugging dogfooding issues. Almost all public APIs have squiggles as the PublicAPI.txt for all projects still have the format without return types.
Additionally when someone tries to update the toolset, they'll run into this issue of having to update all PublicAPI.txt.
We should save them some trouble and pro-actively update the toolset and all PublicAPI.txt

**Comment by srivatsn** [comment]
@tmeschter aren't you in the middle of updating the toolset?

**Comment by tmeschter** [comment]
Fixed by 7ffca327b90d476c9fadef150d2d0c14860f25c8.

**Comment by tmeschter** [comment]
Re-assigning to @mavasani for verification.
