### ISSUE TITLE
Bring back completion mode in immediate window and expression evaluator intellisense

### ISSUE THREAD

**Issue by davidroth** [dotnet/roslyn#10343]
Since VS 2015 RTM, intellisense completion mode switching is broken in immediate window / expression evaluator.

Currently, the mode is fixed to _suggestion_ , which does not make sense at all.
This is driving me crazy, as I now have to permanently press TAB+"." to navigate into properties/namespaces.

Please re-enable switching between _completion_ and _suggestion_  and set the default to _completion_ mode as this is the only mode that makes sense in these 2 windows.

**Comment by Pilchie** [comment]
The reason it's fixed to suggestion mode is because there are lots of things that can be typed in the watch window that are not shown in completion (for example, members that would be considered inaccessible in at that point in the program).

However, maybe we should *default* to suggestion mode, but allow it to change?

**Comment by davidroth** [comment]
@Pilchie Yes please allow it to be changed again. 
There is no reason for disabling this option, especially as in all previous versions of VS (_2010,2012, 2013_), the default mode was _Completion_.
And if you are used to the _Completion_ mode like myself, being forced to use _Suggestion_ mode is extremely annoying. 

Regarding your argument that _Suggestion_ is useful because of members considered inaccessible: I cannot speak for others, but as for myself, in 99% of the cases I am typing against members available in the current context, so the _Completion_ mode would be the correct one.

Do you have numbers which show that _Suggestion_ is a sound default?

**Comment by Pilchie** [comment]
Thinking about this, in the watch window, we suspect that the only things that aren't shown at the top level are debugger special variables (`$exception`, object ids, etc).

It's true that after a `.`, we don't show inaccessible members, but we never did in the past either, so maybe that isn't a big deal after a `.`.

For the Immediate Window however, completion doesn't know about variables declared in the Immediate Window, so at the top-level, we should remain in Suggestion Mode until we get an API that would allow us to put those locals in.

**Comment by miloush** [comment]
I agree that this is very annoying change from VS 2013. I don't mind any default as long as I can switch between them.

**Comment by rchande** [comment]
@Pilchie Do you still think we should leave the Immediate Window in suggestion mode until we can get locals declared in the immediate window included in the list? If so, does that part go to `Area-Interactive`?

**Comment by rchande** [comment]
It looks like this got fixed when we refactored completion in VS 2017--you can now toggle between builder/no builder in the watch and immediate windows.

**Comment by miloush** [comment]
Yes 🎉  although I believe anytime the Immediate window receives focus it starts in suggestion mode, however, the state seems to believe it's in completion mode. If you press Ctrl+Alt+Space, it toggles to suggestion mode (i.e. no change) and then if you press it second time it switches to completion mode.

It used to be in completion mode by default, so the inner state seem to be correct about that.

**Comment by miloush** [comment]
The happiness was a bit too early. It actually resets on every appearance of the autocompletion list, i.e. you switch to completion mode during typing Console, you press dot and the new list is back in suggestion mode. The setting should be preserved for the window at least for the duration of IDE session.
