### ISSUE TITLE
Code Snippets now strip trailing newlines

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#10342]
I have a code snippet that ends in a newline (to introduce an XML doc comment, invoked from the beginning of the next line).

After installing Update 2, all trailing newlines are stripped on insertion.

I don't know if this is a Roslyn change or a VS change.

**Comment by dpoeschl** [comment]
I don't think Roslyn changed anything here between Update 1 and Update 2. 

@tinaschrepfer - does anything immediately come to mind? If not, I'll start digging...

**Comment by tinaschrepfer** [comment]
Yes, this is a platform bug with the new expansion service.  It's been fixed already and will go out for Update 3.  Sorry for the inconvenience!

**Comment by dpoeschl** [comment]
Awesome, thanks @tinaschrepfer! Closing this as Resolved-External.
