### ISSUE TITLE
[Test Failure] Open to Internal Commit Pump not running in prtest/win/dbg/eta on PR #9362

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#10355]
PR: [#9362](https://github.com/dotnet/roslyn/pull/9362) *Support 'generate type' on complex patterns.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4971/

**Issue 1: Open to Internal Commit Pump not running**
Unable to find the appropriate revision to build. 

Merge conflicts? If so, resolve them and update PR.

Feature branch? If yes, then this failure is expected - we do not currently support running internal jobs against feature branches.

Future, master or stabilization? If yes, then its likely the commit pump between Roslyn to Roslyn internal is not running. Contact mlinfraswat@microsoft.com.

**Comment by jasonmalinowski** [comment]
This would have been fixed by now.
