### ISSUE TITLE
NavigateTo not finding symbols.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#10367]
Search for 'SwitchStatementSyntax' in roslyn.

Actual:
No results come up.  

Expected: 
Results

I believe this is because SwitchStatementSyntax is defined in a generated file.  But so what?  It should still show up in NavigateTo.  That's the entire purpose of navigate to.

**Comment by balajikris** [comment]
+1 for this. I also find it hard after we blocked generated files. /cc @brettfo

**Comment by Pilchie** [comment]
Duplicate of #8009.
