### ISSUE TITLE
Analyzer diagnostics with location in doc comments are inconsistent between build and intellisense

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#10383]
**Version Used**: VS2015 Update2

**Steps to Reproduce**:

1. Create any C# project and add a doc comment to a symbol such that it contains tabs.
2. Turn off XML documentation comments for the project (Project -> Properties -> Build)
3. Manage Nuget Packages -> Install StyleCop.Analyzers 1.0.0
4. Build project
5. Verify SA1027 diagnostics in the error list in "Intellisense Only" and "Build Only" modes.

**Expected Behavior**:
Equivalent diagnostcs

**Actual Behavior**:
SA1027 is reported in doc comments in intellisense, but not during command line build.

Command line compiler seems to explicitly filter out diagnostics with locations in doc comments when XML comment DocumentationMode is not set to Diagnose. We need to add this logic to the analyzer driver so that the behavior is consistent between Intellisense and Build.

**Comment by srivatsn** [comment]
This is by design currently. The compiler doesn't bind anything in the doc comments unless doc comment generation is on. The IDE sets the parse option to Diagnose so that it can offer language services in the doc comments.
