### ISSUE TITLE
Local functions: Validate that syntax is unambiguous in successful parsing and error recovery

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#10388]
From the local functions work file:

> Some thought done, not complete
> - Currently thought to be unambiguous past the parameter list (starting at
>    `{` or `=>`), but that requires lots of lookahead.
> - See LanguageParser.cs for comments on both ambiguity in standard parsing,
>    and ambiguity in error recovery.

The conditions thought to be most likely to produce ambiguities are:
- await
- lambda expressions

When tuples are integrated further, it's probably worth examining them as well.

**Comment by agocke** [comment]
We've added a significant number of additional parsing tests. I'm satisfied that parsing is unambiguous.

**Comment by gafter** [comment]
There is a skipped test with this issue as the skip reason.
