### ISSUE TITLE
Review fallback behavior when we can't set the OutputEncoding with the /utf8output flag

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#1039]
Jared pointed out in https://github.com/agocke/roslyn/pull/1 that we thow an exception if we try to set the console encoding to Utf8 and fail, but we silently swallow the exception if we fail to reset the encoding after setting it. We should review this decision. See http://source.roslyn.io/#csc/Csc.cs,28 for an example.

**Comment by agocke** [comment]
My feeling is that we probably shouldn't let the exception bubble out like we currently do, but we also shouldn't silently fail to obey the user's request for UTF-8 output. I think we should catch the exception in all instances and surface a diagnostc.

**Comment by jaredpar** [comment]
Moving to 1.1.  I agree this scenario is important but 

- At this time it doesn't silently fail.
- Changing the failure to be more palatable post v1 is a non-back compat breaking change.

**Comment by jaredpar** [comment]
Closing due to having no customer reports of an issue here.
