### ISSUE TITLE
Local functions: Disallow referring  to local functions in expression trees (for now)

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#10390]

**Comment by jaredpar** [comment]
Isn't the decision here to disallow local functions in expression trees?

**Comment by agocke** [comment]
Yes, disallowing is our current plan, to possibly be allowed in subsequent releases.

**Comment by jcouv** [comment]
Tracked by VSO https://devdiv.visualstudio.com/DevDiv/_workitems?id=369818

**Comment by VSadov** [comment]
Turns out thsi has been already fixed in 
https://github.com/dotnet/roslyn/commit/835b3877c789c13bb1b56e97f9031359acef19ce
