### ISSUE TITLE
Portable pdb output produces corrupted files

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#10401]
**Version Used**: 1.2.0.60317

**Steps to Reproduce**:

1. git clone https://github.com/mono/mono + clone submodules
2. copy `mono\mcs\build\common\Consts.cs.in` to `mono\mcs\build\common\Consts.cs`
3. go to `mono\mcs\class\corlib`
4. compile using your local csc (should work on windows) using command line arguments
`
/codepage:65001 /nologo /noconfig /deterministic -unsafe -nostdlib -nowarn:612,618,1635 -d:INSIDE_CORLIB,MONO_CULTURE_DATA -d:LIBC -d:FEATURE_PAL,GENERICS_WORK,FEATURE_LIST_PREDICATES,FEATURE_SERIALIZATION,FEATURE_ASCII,FEATURE_LATIN1,FEATURE_UTF7,FEATURE_UTF32,MONO_HYBRID_ENCODING_SUPPORT,FEATURE_ASYNC_IO,NEW_EXPERIMENTAL_ASYNC_IO,FEATURE_UTF32,FEATURE_EXCEPTIONDISPATCHINFO,FEATURE_CORRUPTING_EXCEPTIONS,FEATURE_EXCEPTION_NOTIFICATIONS,FEATURE_STRONGNAME_MIGRATION,FEATURE_USE_LCID,FEATURE_FUSION,FEATURE_CRYPTO,FEATURE_X509_SECURESTRINGS,FEATURE_SYNCHRONIZATIONCONTEXT,FEATURE_SYNCHRONIZATIONCONTEXT_WAIT -d:FEATURE_REMOTING,MONO_COM,FEATURE_COMINTEROP,FEATURE_ROLE_BASED_SECURITY -d:MONO_FEATURE_THREAD_ABORT -d:MONO_FEATURE_THREAD_SUSPEND_RESUME -d:MONO_FEATURE_MULTIPLE_APPDOMAINS  -d:NET_4_0 -d:NET_4_5 -d:NET_4_6 -d:MONO -d:DISABLE_CAS_USE  -nowarn:1699 -nostdlib  /debug:portable -optimize   -d:FEATURE_PAL,GENERICS_WORK,FEATURE_LIST_PREDICATES,FEATURE_SERIALIZATION,FEATURE_ASCII,FEATURE_LATIN1,FEATURE_UTF7,FEATURE_UTF32,MONO_HYBRID_ENCODING_SUPPORT,FEATURE_ASYNC_IO,NEW_EXPERIMENTAL_ASYNC_IO,FEATURE_UTF32,FEATURE_EXCEPTIONDISPATCHINFO,FEATURE_CORRUPTING_EXCEPTIONS,FEATURE_EXCEPTION_NOTIFICATIONS,FEATURE_STRONGNAME_MIGRATION,FEATURE_USE_LCID,FEATURE_FUSION,FEATURE_CRYPTO,FEATURE_X509_SECURESTRINGS,FEATURE_SYNCHRONIZATIONCONTEXT,FEATURE_SYNCHRONIZATIONCONTEXT_WAIT -d:FEATURE_REMOTING,MONO_COM,FEATURE_COMINTEROP,FEATURE_ROLE_BASED_SECURITY -d:MONO_FEATURE_THREAD_ABORT -d:MONO_FEATURE_THREAD_SUSPEND_RESUME -d:MONO_FEATURE_MULTIPLE_APPDOMAINS -target:library @corlib.dll.sources
`

**Expected Behavior**:

Valid pdb output.

**Actual Behavior**:

Compiled pdb has corrupted data. Using `pdb2xml` from roslyn's tools to inspect the data you can find e.g. following (btw our own tooling shows same)

```
    <method containingType="System.Object" name="FieldGetter" parameterNames="typeName, fieldName, val">
      <sequencePoints>
        <entry offset="0x0" startLine="327" startColumn="13" endLine="327" endColumn="71" document="251" />
        <entry offset="0x2" startLine="329" startColumn="13" endLine="329" endColumn="34" document="251" />
        <entry offset="0x5" startLine="330" startColumn="17" endLine="330" endColumn="61" document="251" />
        <entry offset="0x10" startLine="332" startColumn="13" endLine="332" endColumn="40" document="251" />
        <entry offset="0x18" startLine="334" startColumn="17" endLine="334" endColumn="60" document="251" />
        <entry offset="0x22" startLine="341" startColumn="13" endLine="341" endColumn="63" document="251" />
        <entry offset="0x24" startLine="342" startColumn="13" endLine="342" endColumn="62" document="251" />
        <entry offset="0x26" startLine="343" startColumn="13" endLine="343" endColumn="42" document="251" />
        <entry offset="0x2e" startLine="345" startColumn="17" endLine="345" endColumn="47" document="251" />
        <entry offset="0x31" startLine="346" startColumn="21" endLine="346" endColumn="74" document="251" />
        <entry offset="0x37" startLine="347" startColumn="17" endLine="347" endColumn="41" document="251" />
        <entry offset="0x3b" startLine="348" startColumn="21" endLine="349" endColumn="93" document="251" />
        <entry offset="0x44" startLine="353" startColumn="13" endLine="353" endColumn="110" document="251" />
      </sequencePoints>
      <scope startOffset="0x0" endOffset="0x54">
        <local name="stackMark" il_index="0" il_start="0x0" il_end="0x54" attributes="0" />
        <local name="capturedSyncContext" il_index="1" il_start="0x0" il_end="0x54" attributes="0" />
        <local name="capturedExecutionContext" il_index="2" il_start="0x0" il_end="0x54" attributes="0" />
      </scope>
    </method>
``` 

which is wrong because method is declared like https://github.com/mono/mono/blob/346cd3d86c5dc439f7e39217d7764a8b603e96d1/mcs/class/corlib/System/Object.cs#L131 (no body) the actual body is from method in file `/mono/external/referencesource/mscorlib/system/threading/CancellationToken.cs` and method `Register` which header is missing.

I though this could be a race in /parallel handling but using /parallel- makes the output pdb 4kb **smaller** ! but data seems to be corrupted in same way.

This is pretty major issue which renders Roslyn compiler ppdb support unusable.

**Comment by tmat** [comment]
I don't see the same error, but CustomDebugInformation table is bad. It might be related.

**Comment by tmat** [comment]
Figured it out. There is a tiny bug in the reader with great consequences for CustomDebugInformation table. The writer (Roslyn compiler) is good. Deterministic build (even with  /parallel+) produces bit-for-bit identical .dll and .pdb. Can you double-check in your environment whether the build produces exactly the same output when run multiple times (.dll and .pdb)?

**Comment by marek-safar** [comment]
The build does not produce same output. It almost looks like every build produces pretty different pdb.

Here is short overview to see the output (copied files) from 3 subsequent compilations of exactly same csc command line

>
-rw-r--r--+ 1 marek  staff  3526656 13 Apr 19:15 1.dll
-rw-r--r--+ 1 marek  staff  1406188 13 Apr 19:15 1.pdb
-rw-r--r--+ 1 marek  staff  3526656 13 Apr 19:16 2.dll
-rw-r--r--+ 1 marek  staff  1407200 13 Apr 19:16 2.pdb
-rw-r--r--+ 1 marek  staff  3526656 13 Apr 19:17 3.dll
-rw-r--r--+ 1 marek  staff  1407544 13 Apr 19:17 3.pdb

I could upload the files somewhere if you want.

**Comment by tmat** [comment]
Please upload them, I'll take a look why they are different.

**Comment by marek-safar** [comment]
[corlib-dll+pdb.zip](https://github.com/dotnet/roslyn/files/217667/corlib-dll.pdb.zip)

**Comment by tmat** [comment]
@marek-safar It looks like a bug we have already fixed - the import scopes are generated non-deterministically: https://github.com/dotnet/roslyn/commit/92b4ad679d0418c3d34f70550f3d764f40efc648 

Could you try the latest Roslyn bits?

**Comment by marek-safar** [comment]
@tmat by latest you mean 1.3 or 2.0 ?

**Comment by tmat** [comment]
Either should have this particular bug fixed. I'd go with 2.0 if you can.

**Comment by marek-safar** [comment]
@tmat none of the tags or branches contain the fix, only master has it :-(

**Comment by tmat** [comment]
Future branch (v2.0) should have it as well (we integrate from master to future on daily basis).
Nugets from this branch are published here: http://myget.org/gallery/roslyn-future-nightly

**Comment by marek-safar** [comment]
Internal build `Microsoft.Net.Compilers.2.0.0-beta1-20160419-04` seems to work as expected

**Comment by tmat** [comment]
Excellent.
