### ISSUE TITLE
Conflicts resolved during rename should be formatted if appropriate.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#10406]
Related to #8334 (cc @bmay2, @dpoeschl)
1.  Paste into a VB editor:

``` VB
Imports System.Runtime.CompilerServices

Module E
    <Extension>
    Public Function Bar(x As C, i As Integer) As C
        Return x
    End Function
End Module

Class C
    Function Foo(i As Integer) As Integer
        Return Me.Bar(1).Foo(2)
    End Function
End Class
```
1.  Rename 'Bar' to 'Foo'

RESULT:
`return E.Foo(Me,1).Foo(2)`
There is no space before the 1.

EXPECTED:
`return E.Foo(Me, 1).Foo(2)`
There should be a space before the 1.

**Comment by CyrusNajmabadi** [comment]
Need info if this is actually something worth investing in.
