### ISSUE TITLE
SSDT Unable to Schema Compare Databases with Hyphens in the name '-'

### ISSUE THREAD

**Issue by TheOpenDevProject** [dotnet/roslyn#10400]
**Version Used**: 
Visual Studio Enterprise 2015 `Version 14.0.25029.00 Update 2 RC`
**Steps to Reproduce**:

1. Create a database in MSSQL with a hyphen in the name. E.g `My-Database`
2. Using SSDT do a schema compare of the database (From within a SQL project)

**Expected Behavior**:
Should show schema differences between local SQL project and remote SQL server

**Actual Behavior**:
Comparison refuses to start but does not give an error.

@Pilchie Could this have to do with the parsing engine within VS not being able to understand certain characters?.

Again sorry if this is the wrong place but you guys are the best when it comes to getting an answer as well as this being the most effective place for a MSDev to be able to fix the issue do to the greatest visibility.

**Comment by Pilchie** [comment]
Sorry - I don't think anyone here knows anything about SSDT (I don't even know what it is!).

You're best bet is probably to file this on Connect.
