### ISSUE TITLE
Build warning (double-write?): MS.DiaSymReader.Native.arm.dll

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#10402]
Building latest Roslyn from master. Seeing this build warning:

00:08:45.786   124>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.Curr
entVersion.targets(3962,5): warning MSB3026: Could not copy "C:\Users\kirill\.n
uget\packages\Microsoft.DiaSymReader.Native\1.3.3\runtimes\win\native\Microsoft.
DiaSymReader.Native.arm.dll" to "F:\SourcesToIndex\Roslyn\Open\Binaries\Debug\Mi
crosoft.DiaSymReader.Native.arm.dll". Beginning retry 1 in 1000ms. The process c
annot access the file 'F:\SourcesToIndex\Roslyn\Open\Binaries\Debug\Microsoft.Di
aSymReader.Native.arm.dll' because it is being used by another process. [F:\Sour
cesToIndex\Roslyn\Open\src\Scripting\VisualBasicTest.Desktop\BasicScriptingTest.
Desktop.vbproj]

Is this a double-write? Or some other sort of race? I didn't save the build log unfortunately.

**Comment by tmat** [comment]
Has this been seen since? Closing for now, reopen please if this shows up again.

**Comment by alrz** [comment]
Deleting Binaries directory and rebuild seems to be working (I get different errors), but this is still open.

**Comment by KirillOsenkov** [comment]
Historical note: this is what prompted me to write http://msbuildlog.com. 

If you see this problem after the build, inspect the .binlog (I think Roslyn build outputs the binlog by default). If you can share it (no personal information in Environment variables or anything like that) feel free to share the .binlog with Tomas or I (kirill . osenkov at microsoft). We can take another look.
