### ISSUE TITLE
VSI integration tests need to install the compiler extension

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#10414]
See comment [here](https://github.com/dotnet/roslyn-internal/pull/805#issuecomment-207134857). We should be deploying the locally built Roslyn compiler bits and using them instead.

**Comment by mavasani** [comment]
Tagging @ManishJayaswal as we may want to consider this to be an Urgency-Soon bug.

**Comment by ManishJayaswal** [comment]
FYI @jasonmalinowski. 
@dpoeschl - We do run VSI tests on standalone installs everyday but we should fix this quickly.

**Comment by dpoeschl** [comment]
Currently working on https://github.com/dotnet/roslyn/issues/10132. Removing Urgency-Now for now...

**Comment by dpoeschl** [comment]
@jasonmalinowski Should this be on the infrastructure backlog?

**Comment by ManishJayaswal** [comment]
@jasonmalinowski please assign to a swat member based on workload.

**Comment by jasonmalinowski** [comment]
Put on backlog; this isn't higher than other priorities we have right now.

**Comment by tannergooding** [comment]
This is being done as of the current test runner sources.
