### ISSUE TITLE
Flaky TAO tests CSharpInteractiveDirectives.xml 

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#10425]
Identified problems

Individual TAO Test Failure

Failing integration tests: CSharpInteractiveDirectives.xml 
Indication 1 

Compile Error

error CS7010: Quoted file name expected
Indication 2 

See
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/582/

The tests pass on rerun.

**Comment by ManishJayaswal** [comment]
@drognanar You were looking at this one right? Do we have a mitigation?

**Comment by ManishJayaswal** [comment]
@drognanar Is this test still failing? If not then can you close this out?

**Comment by ManishJayaswal** [comment]
Closing it out as we haven't seen this issue recently.
