### ISSUE TITLE
Streamline deployment of CompilerExtension + VisualStudioSetup VSIX

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#10422]
It's confusing and awkward today how we have to install two VSIXs (CompilerExtension + VisualStudioSetup) to test our compiler changes. @jasonmalinowski said "file a bug; we can make this better".

_Let's step back and spell out the customer scenarios:_

**SCENARIO1**: the Visual Studio product itself ships with a modified component of VisualStudioSetup VSIX.

**SCENARIO2**: Compiler/IDE devs who alter Roslyn and wish to test their changes on their local machine. They currently must install both CompilerExtension VSIX and VisualStudioSetup VSIX, so they can test their changes both in the IDE and when they do Ctrl+Shift+B. This is awkward and hard to discover.

**SCENARIO3**: Compiler/IDE devs who wish to distribute their prototype compiler changes for other people to experiment with from within VS. They currently must distribute the two VSIXs, and ask their audience to install both of them, then later uninstall both of them.

**SCENARIO4**: Compiler/IDE devs who've written a prototype compiler change that's so popular that customers end up taking a serious production dependency on the prototype. They currently must distribute the two VSIXs, and also (for the sake of build machines) they must somehow author a NuGet package that contains the updated compiler and makes it so that projects which reference this NuGet package will compile on the build server using the updated compiler. Ideally they'd also ship a third VSIX that contains an analyzer whose sole behavior is to add a reference to this NuGet package.

I think we should streamline Scenarios 2 & 3 by making it so that the CompilerExtension VSIX is a "one-stop-shop" which incorporates within it the functionality of VisualStudioSetup VSIX. That way, devs need only distribute a single self-contained VSIX, and consumers of it need only install/uninstall it once and will never get out of sync.

I think we can safely scope out the rest of Scenario4 (NuGet + analyzer stuff). That's a bit too weird, and it's arguably not even good to encourage production dependencies on CTPs. I know we did it for the async CTP but that was the exception, not the rule.

**Comment by ljw1004** [comment]
I've been having a hard time distributing my modified version of the language. I'll use this thread to outline some issues...

**Comment by ljw1004** [comment]
## Issue: have to install at least three VSIXs, and maybe more (unknown)

I tried installing just `Roslyn.VisualStudio.Setup.vsix` but this didn't help with Project.Build.

I tried additionally installing `Roslyn.Compilers.Extension.vsix`. Now I can do Project.Build using my new version of the compiler, but while I'm debugging, the tooltips and watch windows don't show values correctly.

I tried additionally installing `ExpressionEvaluatorPackage.vsix`. This seems to have solved the debugger issues...

But now my install of VS is kind of flakey. Every few hours, I haven't been able to get a clear sense of what triggers it, but I get crashes. Here's one screenshot I got:
![screenshot 3](https://cloud.githubusercontent.com/assets/3316258/14768806/40eadc7e-0a00-11e6-98a4-1bb210d169c3.png)

Other times (sorry I didn't capture screenshots) there were error messages popping up that I think were about about refactoring-related VSIXs. Can't remember the details.

I get the impression that they're due to some other parts of Roslyn not being up-to-date with my compiler changes and that I should have installed as well? But I don't know which other parts of Roslyn that would even be. I notice that Roslyn builds a load of VSIXs. Do I really need to be installing *all* of them?
```
ConvertToAutoPropertyCS.vsix
ConvertToAutoPropertyVB.vsix
ConvertToConditionalCS.vsix
ImplementNotifyPropertyChangedCS.vsix
ImplementNotifyPropertyChangedVB.vsix
MakeConstCS.vsix
MakeConstVB.vsix
RemoveByValVB.vsix
Roslyn.Samples.CodeAction.AddOrRemoveRefOutModifier.vsix
Roslyn.Samples.CodeAction.CopyPasteWithUsing.vsix
```

**Comment by ljw1004** [comment]
## Issue: uninstall doesn't work

I installed the three VSIXs on my machine (Roslyn.VisualStudio.Setup.vsix, Roslyn.Compilers.Extension.vsix, ExpressionEvaluatorPackage.vsix). I did work with it, and it was fine.

Then I tried to uninstall the three packages. It's hard to know exactly what you have to uninstall, and in which order. I guessed that I could search for "Roslyn" and delete all the experimental ones, while leaving the SDK behind. The Extensions dialog complained that I had to uninstall them in the correct order, and by trial and error I found that uninstalling Roslyn.VisualStudio.Setup.vsix *last* seems to work.

But subsequently, when I restart VS and try to open an existing C# project or create a new one, it gives package load failures:
![screenshot 4](https://cloud.githubusercontent.com/assets/3316258/14768897/7aa9d0fe-0a01-11e6-981a-23c337bf6fe3.png)
[ActivityLog.zip](https://github.com/dotnet/roslyn/files/233541/ActivityLog.zip)

I discovered that I can work around this, and get VS working again for C#, by quiting VS then deleting these entire folders then restarting VS:
```
%userprofile%\appdata\local\microsoft\VisualStudio
%userprofile%\appdata\roaming\microsoft\VisualStudio
```
(One of the folders can't be completely deleted until you go to Task Manager and terminate `Microsoft.VsHub.Server.HttpHost.exe`, which continues to run even after you've terminated VS).

Unfortunately, deleting the files causes my VS settings to all be forgotten.

Now I don't know if this uninstall problem is universal, or if it's an accident due to my machine not yet having VS2015 Update 2 on it, or what.


**WHAT I EXPECT**

*Minimum:* Uninstalling the things from the Extensions dialog should work.

*Better:* There should be clear unambiguous naming convention so I know exactly which ones to uninstall and in which order, and this information should be disseminated

*Best:* There should be just one single VSIX to uninstall from the Extensions dialog, not several.

**Comment by ljw1004** [comment]
## Issue: can't install into experimental hive

I want to run my modified version of the compiler in an experimental hive. That might be because I'm doing F5 debugging, or it might be because I'm sharing a prototype with folks who want to experiment with my prototype in one hive, while retaining their normal hive "pure".

It's really hard to install VSIXs into experimental hives! The official suggestion is to install them into the regular hive, then copy a bunch of files over from one hive to another, but that's way too complicated.

F5 is able to copy the extension *I'm currently debugging* into an experimental hive, which would be great. The problem however is that I need 3 or more different VSIXs to be placed into the hive. I experimented with setting one project as my startup project and pressing F5 to install it into the experimental hive, then quit the debugee VS, then set the next project as my startup project and press F5 to install it, then set the third project as my startup project as press F5 to install it again. That's a pretty fraught and error-prone process, very easy to accidentally forget one of them and end up with an inconsistent state.

(The single most important part of debugging a modified Roslyn is to make sure you're running a consistent install of it, so you don't waste time tracking down stupid issues).


I believe that when folks start an experimental hive and then go to Tools.Extensions and browse to find an extension and click the install button, then it does download+install it into the experimental hive. This would be feasible for folks to test my language prototype. But alas it's not feasible to upload my prototype to the extensions gallery -- too many VSIXs (as per above) and no way to name them (see below).


**WHAT I EXPECT**

First, some forcing function into the "pit of success" of always having a complete consistent install of my Roslyn prototype into an experimental hive.

Second, some default way for me as a Roslyn developer to F5 into an experimental hive with a consistent install of my prototype.

Third, some way for folks to acquire my prototype and install it into an experimental hive on their machine.

**Comment by ljw1004** [comment]
## Issue: can't name my own prototype

I want to give my prototype language version its own name and version number:
* I want distinctive names for my VSIXs
* I want distinctive text in the VSIX install dialog, that shows you're installing my specific language prototype
* I want the Tools.Extensions dialog to list my VSIX under its distinct name (not just "experimental Roslyn") so folks know exactly *which* experimental prototype they happen to have installed
* I want to have a distinct name so I can upload my prototype to the Extensions gallery and have it recognizably different from other prototypes
* I want to use version numbers myself, rather than just the 42.42.42.42 version number that appears to be default. I'll use this so that folks who consume my prototype will know what they're getting.


I tried to change all of these things in one go, but then my VSIX didn't install right. (Sorry, it was several weeks ago, and I can't remember the details). I don't know what things can be changed and what things can't.


**WHAT I EXPECT**

*Minimum:* It should be possible to give my protoype VSIXs a distinct name+version+filename so that when folks download my prototype (or get it direct from the Tools.Extensions.Online dialog) they know which prototype they're getting.

*Best:* There should be guidance on how to do this, and what things to change!

**Comment by ljw1004** [comment]
## Issue: not sure how to give a distinct compiler banner

I'd like my prototype to print out a distinct banner message - something like "C# compiler version 5, with [XYZ] prototype feature".

I was able to change the banner, of course, but when I did "cibuild.cmd" it turns out there are some of the unit tests which check the exact text of the banner message. It was too much friction to alter these tests for my branch, so I just gave up and reverted my banner message.


Ideally the experience I'd like is that everyone who builds with my prototype can see loud and clear that they're using my experimental prototype. And compiler banner messages aren't even good enough for that, since they don't show up by default in the IDE "Output" window when you do Project.BuildAll.

I had a thought that the best way would be a warning (one that can never be silenced and never treated as error) which says "Warning: you are compiling against an experimental prototype of C#". But that would break every single unit test in existence, so I can't really go down that route.


**WHAT I EXPECT**

*Minimum:* Remove the unit test that checks for the exact text of the compiler banner message. (It would be fine to merely check the first however many characters, say).

*Best:* Figure out some other front-and-center mechanism so that users of my prototype are reminded loudly that they're using my prototype when they build.

**Comment by ljw1004** [comment]
## Issue: feature flag vs VSIX install

Users have a pretty confusing model for how to enable experimental language features...
* Pass a /langfeature flag to the compiler (doesn't help the IDE)
* Install VS15 Preview and set __DEMO_EXPERIMENTAL__ conditional constant
* Install a VSIX

And when I implement my prototype, what am I supposed to do with it? Should I plumb through a /langfeature flag for it as well? -- **NO!** Users have already performed an affirmative step to get hold of my language feature (by installing the VSIX) and they shouldn't have to go through any more steps.


**WHAT I EXPECT**

We should get rid of the /langfeature flag. It's an idea that simply didn't pan cleanly enough.

The sole mechanism for getting experimental versions of the compiler should be to install a VSIX (via an easier route than what we have at the moment). Once you've installed a VSIX, that's a clear signal of your intention, and you shouldn't have to do additional steps.

Experimental language prototypes can go in their own individual VSIXs. Microsoft team can also have its own "future" branch+VSIX, which incorporates the code of all the individual prototypes that we think have a good chance of getting in. This VSIX should be decoupled from VS15 Preview.

If one day we need to start giving go-live licenses for a future branch, we might decide that we only support it within the context of VS, or we might go the extra mile and do the NuGet stuff I mentioned earlier.

**Comment by ljw1004** [comment]
## Issue: dotnet-cli use of prototype language features

Sure I can do some testing within VS. But pretty soon, many of my important scenarios will be dotnet-cli ones. I'll need a vehicle for getting my prototype language feature into dotnet-cli.

I have no idea how to do that! I have no idea how dotnet-cli even works! Which csc.exe does it pick up?

**Comment by ljw1004** [comment]
Adding @jaredpar to this thread. Jared, you'd been talking about your vision of how experimental language prototypes should be easier to distribute+install. In this thread I've drawn together the various ways I've been struggling to test+distribute my prototype.

**Comment by jaredpar** [comment]
There is an effort to make this process betteur, more streamlined and really take Github completely out of the mix here.  Have you checked your email since Friday noon?  Prototype version of a tool went out, going to release it publicly soon after some dogfooding.

**Comment by jasonmalinowski** [comment]
We aren't really planning any huge investments into this area at this point.
