### ISSUE TITLE
Formatting of empty for loops: "for(;;)"

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#10428]
Paste

``` C#
for (;;)
```

**Expected Behavior**:

``` C#
for ( ; ; )
```

**Actual Behavior**:

``` C#
for (;;)
```

**Comment by svick** [comment]
Why would `for ( ; ; )` be the expected behavior? Isn't `for (;;)` more common, if you decide to write an infinite loop as `for`?

**Comment by Pilchie** [comment]
VS2005 through VS2013 all formatted it as `for ( ; ; )`, so I would expect that to be more common.

**Comment by 0xd4d** [comment]
I tested VS2010, VS2012, VS2013 (all settings were reset to the default values) and they all format it as `for (; ; )`, i.e., no space after `(`.

I personally prefer `for (;;)` though.

**Comment by HaloFour** [comment]
Sounds like neither is correct given that both ignore the formatting options specified by the user.  Either it should be `for (; ; )` by default, or there should be another option pertaining to the format of for loops without initializers, conditions and/or iterators.

**Comment by Pilchie** [comment]
@HaloFour The old formatting engine had a special case for this IIRC, it's not necessarily worth another option.
