### ISSUE TITLE
Move SQM to AI [StanCore - CodeAnalysis]

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#10432]
SQM is going away.

we need to either delete SQM or move to AI.

**Comment by heejaechang** [comment]
@srivatsn this is something asked by DEVDIV to finish soon.

**Comment by heejaechang** [comment]
please let me know by 5/16 what is plan for existing SQM (remove, replace)
actual code should be checked in by 7/25

**Comment by heejaechang** [comment]
@mavasani  deadline is updated to 7/9

**Comment by mavasani** [comment]
This is done now.
