### ISSUE TITLE
Move SQM to AI [Compiler]

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#10433]
SQM is going away. compiler needs to either remove SQM or move to AI.

**Comment by heejaechang** [comment]
please let me know by 5/16 what is plan for existing SQM (remove, replace)
actual code should be checked in by 7/25

**Comment by heejaechang** [comment]
@jaredpar  deadline is updated to 7/9

**Comment by jaredpar** [comment]
Keeping this one open for now.  Need it to track our decision on AI in the compiler.

**Comment by jaredpar** [comment]
At this time there is no apparent path forward for AI and the compiler in the 2.0 time frame.  Moving out to 2.1.

**Comment by jaredpar** [comment]
This code was eventually deleted.
