### ISSUE TITLE
IConversionExpression should expose more about the semantics of conversions

### ISSUE THREAD

**Issue by msJohnHamby** [dotnet/roslyn#10447]
A consumer of IConversionExpression should be given more information and required to infer less than with the current interface.

@CyrusNajmabadi suggests, as a starting point:

Widening/Narrowing, Identity, Numeric, Nullable, Reference, NullLiteral

**Comment by CyrusNajmabadi** [comment]
Yes.  We still need to do something here.  Right now IOperation is lossy wrt the semantic model.  We either need a common way to expose conversion info.  Or we at least need to allow the user to easily get to the languge specific Conversion struct so they can handle it.  (The former would be preferred, but as we've dug deep it is constantly difficult to make these common as the languages are so different).

**Comment by jinujoseph** [comment]
this is done
