### ISSUE TITLE
Error dialog shown when selecting an ambiguous completion list entry

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#10444]
An `InvalidOperationException` - "Sequence contains no elements" - is thrown at [AbstractMemberInsertingCompletionProvider.cs#L157](https://github.com/dotnet/roslyn/blob/6934bcb5fe8ec871b2f3c6da41a2ce1520facdc2/src/EditorFeatures/Core/Implementation/IntelliSense/Completion/CompletionProviders/AbstractMemberInsertingCompletionProvider.cs#L157), when selecting an ambiguous entry from the completion list. VS shows an error dialog, but doesn't crash.

Given the following code, it seems like a simple typo: `First` should instead be `FirstOrDefault`.

**Comment by lorcanmooney** [comment]
Here's a small repro, with three files:

A.cs
```internal abstract class A { internal abstract T Foo<T>(); }```

B.cs
```internal abstract class A { internal abstract T Foo<T>(); }```

C.cs
```
private class C : A
{
internal sealed override 
}
```

Getting this to reproduce depends on how the code is formatted (since the call to Span.IntersectsWith, isn't guarded to ensure the spans are from the same document). The minimal whitespace version shown above should trigger it.

**Comment by Pilchie** [comment]
Thanks for the report.  Given the fact that this requires two identical types with the same locations, we think it's not urgent to fix, but would welcome a PR.

**Comment by lorcanmooney** [comment]
> ...we think it's not urgent to fix...

No argument there.

I'll submit a PR once I figure out how to get some test coverage for it,

**Comment by lorcanmooney** [comment]
This seems to have been fixed by a recent change to the completion providers. Closing.
