### ISSUE TITLE
Incorrect CS1998 (make method synchronous) fix proposal in overridden methods with async

### ISSUE THREAD

**Issue by hmemcpy** [dotnet/roslyn#10456]
Given a base class:

```csharp
class Base
{
    public virtual Task OnStart() { .. }
}

class Derived : Base 
{
    public override async Task OnStart {  } // CS1998 suggested here
}
```
![image](https://cloud.githubusercontent.com/assets/601206/14426272/9234452a-fff6-11e5-968c-f599ce688d77.png)

The resulting fix incorrectly replaces `async Task` with `void`, causing a compilation error.

**Version Used**: 

VS2015 Update 2, Microsoft.CodeAnalysis.dll version 1.2.0.60317

**Comment by i3arnon** [comment]
What do you expect it to try to change to? Simply `override Task`?

**Comment by hmemcpy** [comment]
@i3arnon that's the original signature, so yes.

**Comment by CyrusNajmabadi** [comment]
Fixed with: https://github.com/dotnet/roslyn/pull/10472
