### ISSUE TITLE
Shortcomings in Syntax Tree API - no common base class or interface for  MethodDeclarationSyntax, FieldDeclarationSyntax etc. for important common properties

### ISSUE THREAD

**Issue by gmamaladze** [dotnet/roslyn#10455]
**Version Used**: 
[Visual Studio 2015 Update 2](https://github.com/dotnet/roslyn/releases/tag/Visual-Studio-2015-Update-2)

**Shortcomings in Syntax Tree API**:
While writing code for a code refactoring very often you need to perform similar checks or modifications on members containing actual code: methods, property accessors, indexer accessors etc. Most of them have common properties like `Body`, `Modifiers`, `AttributeLists`, `ArgumentList`. 

There is no common base class or a common interface which would expose these common properties. That's why you end up with a lot of code duplication, with all consequences as shown in example below:

```
private static bool IsPrivate(MethodDeclarationSyntax method)
{
    return method.Modifiers.Any(IsPrivateModifier);
}

private static bool IsPrivate(FieldDeclarationSyntax field)
{
    return field.Modifiers.Any(IsPrivateModifier);
}

private static bool IsPrivate(PropertyDeclarationSyntax property)
{
    return property.Modifiers.Any(IsPrivateModifier);
}

private static bool IsPrivate(IndexerDeclarationSyntax indexer)
{
    return indexer.Modifiers.Any(IsPrivateModifier);
}

private static bool IsPrivateModifier(SyntaxToken modifier)
{
    return modifier.Kind() == SyntaxKind.PrivateKeyword;
}
```

**Suggestion**:
- One way would be to provide a common interface for all "method like" SyntaxNode-s.
- Another way is to provide adapter classes to adapt "method like" SyntaxNode-s to some interface which provides uniform and convenient access to properties like `Modifiers`, `AttributeLists`, `Body`, `ArgumentList`. This solution will have less implementation and runtime impact.

Related to: #9908

**Comment by ap0llo** [comment]
Should I give this issue a try or is there already someone working on this?

**Comment by CyrusNajmabadi** [comment]
These share MemberDeclarationSyntax which do expose things like Modifiers.  Closing out.
