### ISSUE TITLE
VS Feedback: When I type intellisense adds extra stuff that I didn't type and don't want 

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#10461]
Reported through VS Feedback.

> When I type I get extra stuff added. For example I type
> 
> If Parameter.Locations.length >
> 
> And I get 
> 
> If Parameter.Locations.length Then>
> 

@paul1956 - it looks like this was filed by you.  Can you help us understand exactly what you typed to trigger this?  Line Commit should only insert the "Then" when you move off the line, or VS loses focus...

**Comment by paul1956** [comment]
I uploaded a recording to VS Feedback. Almost anything I type has the wrong intellense choices and when I accept the one I want extra stuff is added. In the example below I type > and end up with And> This started with Update 2.

![image](https://cloud.githubusercontent.com/assets/12789369/14442249/80915ed8-ffed-11e5-9c1d-772c4da3f406.png)

**Comment by Pilchie** [comment]
Can you try it without the Bing Developer Assistant enabled?

**Comment by Pilchie** [comment]
(also, sorry for the ask for more info - it seems the problem steps recorder's screenshots never included the completion list, so we didn't really get a sense for what you were doing).

**Comment by paul1956** [comment]
@Pilchie Disabling Developer Assistant 1.2.0.51222 solves the issue.
Thanks
 You can close this issue here and I will try to close on VS Feedback.

**Comment by Pilchie** [comment]
Thanks for the confirmation.  I'll also let the Bing Developer Assistant guys know about this.

**Comment by hjain033** [comment]
Thanks Pilchie for following this up. And thanks paul1956 for the feedback.
I am from the Bing Developer Assistant team and we are looking into this issue. Will update soon.
