### ISSUE TITLE
Should determinism affect generated interop dlls?

### ISSUE THREAD

**Issue by bbarry** [dotnet/roslyn#10460]
**Version Used**: VS2015 Update 2 (14.0.25123.00)

**Steps to Reproduce**:

1. create a COM+ C++ dll and register com application
2. create a new C# project and reference this COM+ library
3. in reference properties, mark "Embed Interop Types" false
4. unload project, edit csproj, add `<Deterministic>true</Deterministic>` to common property group
5. reload and build release mode
6. make a copy of the interop dll
7. rebuild

**Expected Behavior**:

Should interop dll be deterministic?

**Comment by jaredpar** [comment]
The deterministic switch only controls the behavior of the C# / VB compiler.  It will guarantee that given the same inputs, it will produce the same outputs.  In this case the interop DLL is being produced by a different tool.  I'm unsure if that's deterministic or not, guessing no though.
