### ISSUE TITLE
Portable Class library  - > Platform target 'AnyCPU' is not supported by one or more of the project's targets.

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#10471]
Repo Steps 
- Create a new portable class library 
- Change the target to .NetStandard > 1.2
- Build 

Expected 
- Builds with no error 

Actual 
![capture](https://cloud.githubusercontent.com/assets/12449387/14441539/0c7d67a6-ffea-11e5-94e7-57b5c24d0c6d.JPG)

**Comment by davkean** [comment]
AnyCPU is the default, so are you saying that by default, targeting .NET Standard shows an error in the Error List?

**Comment by jinujoseph** [comment]
yes

**Comment by davkean** [comment]
This isn't ours, this is portable.

**Comment by DustinCampbell** [comment]
Should this still be assigned to @jinujoseph?

**Comment by davkean** [comment]
No

**Comment by olegtk** [comment]
Any workaround?

**Comment by davkean** [comment]
@rchande's has a private fix you want one.

**Comment by rchande** [comment]
Can you verify this?

**Comment by weshaggard** [comment]
I'm seeing this error as well. What do I need to do the verify your fix?

**Comment by rchande** [comment]
Install a build of VSUML > 25319.00.

**Comment by Eyas** [comment]
I'm also seeing this with NetStandard 1.0 in VS "15" Preview 2.

I'm curious about this from my perspective as an author of a library trying out VS "15" and NetStandard. I innocuously clicked the "Target .NET Standard" button in the VS Project Properties window, chose to target NetStandard 1.0, updated some dependencies, and am seeing this failure. I'm not even sure what it means, and whether I should assume its a VS Preview/packaging bug or I have my dependencies set up wrong.

I'm not even sure what AnyCPU really implies about the framework used:

1. Does it mean "anything but .NET Native" (i.e. either .NET Core w CLR or .NET Framework?)
  - if so, I still expect NetStandard 1.0 to support these
2. Does it mean .NET Framework?
  - NetStandard 1.0 would cover 4.6, no?

**Comment by rchande** [comment]
@Eyas This particular error (about "AnyCPU") is a bug in Visual Studio and has no bearing on where or where not NetStandard projects can run. In fact, you should be able to ignore it and still be able to build/run your projects. This will be fixed in the next update.

**Comment by jinujoseph** [comment]
Verified this on build 14.0.25323.00 update 3 RC

**Comment by alfredmyers** [comment]
I'm able to reproduce the error using Visual Studio 2015 Update 2 targeting .NETStandard1.5.
