### ISSUE TITLE
Project reference fails from csproj to xproj (with .NetStandard  target reference) 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#10481]
Repro steps 
- Create a .Net Core Class Library (xProj)
- By default it points to
 "frameworks": {
    "netstandard1.5": {}
  }

- Now create .Net Console Aplication (csProj) 
- point the .netframework to 4.6.2 
- Add project.json file to the same and add 
{
  "frameworks": {
    "net462": { }
  },
  "runtimes": {
    "win": { }
  }
}

- Build both projects and make sure it builds fine.
- Now refer the class library project from console app.

Expected 
Reference works and Builds successfully 

Actual 
Reference maps but build fails with this error 
2>C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error : Object reference not set to an instance of an object.
2>C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error :    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.<GetPackagesFromTarget>d__104.MoveNext()
2>C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error :    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.GetReferences(JObject lockFile)
2>C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error :    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.ExecuteCore()
2>C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error :    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.Execute()

Note
If you do a binary reference to the class library the build succeeded but at run time threw this error 
![unhandledexception](https://cloud.githubusercontent.com/assets/12449387/14444520/e8f160a6-fffa-11e5-9ce4-a95c92d6d74b.jpg)

**Comment by jasonmalinowski** [comment]
Migrated to NuGet/Home#2525.
