### ISSUE TITLE
QuickInfo incorrectly assumes mouse position and cursor are in same context

### ISSUE THREAD

**Issue by jsschultz** [dotnet/roslyn#10482]
**Version Used**: Roslyn-Stabilization-Signed-Release 20160325

**Steps to Reproduce**: 
1. Install VS 2015 with Update 2
2. Create WebSite project Razor 3 from default template
3. Set bp anywhere in C# code within cshtml file
4. F5
5. Click in html code to place cursor there
6. With mouse, hover over a local variable in C# code

**Expected Behavior**: Debugger DataTip appears with local variable evaluated (same as in Watch window)

**Actual Behavior**: Tooltip appears with with type info (as if not debugging because the language service does not hand QuickInfo off to debugger). Only when the cursor is placed in C# code, does it correctly show a DataTip from debugger. Based on a cursory investigation, the language service determines the context of the QuickInfo request on the current position of the cursor, rather than the mouse position (which triggers the QuickInfo request). Seems like it should be based on the mouse position.

**Comment by CyrusNajmabadi** [comment]
Need info if this is actually impacting users to the level that warrants investment.
