### ISSUE TITLE
CObj on literal Nothing confused

### ISSUE THREAD

**Issue by markhurd** [dotnet/roslyn#10494]
**Version Used**: 
VS2015 Update 2

**Steps to Reproduce**:

This code (with `Option Strict On`, part of a bigger test against another scenario when strictness changes the code -- reported separately at #10495 , even though it's these two cases that switch):

```
    Sub Main()
        Dim arr() As Object = {1, 2, 3}
        paramsTest("Array", arr)
        paramsTest("Array cast as Object", CObj(arr))
        paramsTest("Nothing", Nothing)
        paramsTest("Nothing cast as Object", CObj(Nothing))
        paramsTest("Nothing cast as String", CStr(Nothing))
        paramsTest("Nothing cast as String cast as Object", CObj(CStr(Nothing)))
        Dim n As Object = Nothing
        paramsTest("Nothing in an Object variable", n)
        paramsTest("Nothing cast as Array", DirectCast(Nothing, Object()))
        paramsTest("Empty")
        If Debugger.IsAttached Then _
            Console.ReadLine()
    End Sub

    Sub paramsTest(Test As String, ParamArray arr As Object())
        Console.WriteLine($"{Test}:")
        Console.WriteLine($"ParamArray: {If(arr?.Length.ToString, "Nothing")}{Environment.NewLine}")
    End Sub

```

**Expected Behavior**:
It should compile.

**Actual Behavior**:
The `CObj(...Nothing...)` cases fail to compile with
> Module1.vb(10,46): error BC30512: Option Strict On disallows implicit conversions from 'Object' to 'Object()'.
> Module1.vb(12,61): error BC30512: Option Strict On disallows implicit conversions from 'Object' to 'Object()'.

If it wasn't for the change in behaviour due to strictness reported separately at #10495 , I could just believe the `CObj(Nothing)` case was intended, but I still don't expect `CObj(CStr(Nothing))` to fail.

**Comment by jaredpar** [comment]
Thanks for reporting this issue.  This behavior though is "By Design".  I verified that it reproduces with Visual Studio 2013 as well.

**Comment by markhurd** [comment]
So there is no way to get a single literal `Nothing` as a parameter to a `ParamArray` in VB.NET?

I note `Console.WriteLine` caters for this by passing two `null`s, so `Console.WriteLine("0:{0} 1:{1}", Nothing)` doesn't throw.

**Comment by jaredpar** [comment]
It should be possible with `CType(Nothing, Object())`.  In the sample below it passes `Nothing` as the `ParamArray` in both `Option Strict On` and `Off`:

``` vb
Option Strict On

Module Module1
    Sub Main()
        ParamsTest(CType(Nothing, Object()))
    End Sub

    Sub ParamsTest(ParamArray p As Object())
        Console.WriteLine($"Called ParamArray version {p Is Nothing}")
    End Sub

    Sub ParamsTest(o As Object)
        Console.WriteLine("Called Object version")
    End Sub
End Module
```

**Comment by markhurd** [comment]
No that's what you aleady get with an unadorned `Nothing`. I want what you get when you pass an `Object` variable containing `Nothing`, but using a literal `Nothing`.

That is,



    Dim n As Object = Nothing
    ParamsTest(n)

without the `As Object` overload.

**Comment by markhurd** [comment]
If you really want a literal `Nothing` to be seen as such for a single `ParamArray` parameter you can use inline `If`, in an opposite effect to http://stackoverflow.com/a/14663808/256431 where I point out not using `Nothing` can force a different type.

So



```
    ParamsTest(If(True, Nothing, New Object))
```
does compile down to what I'd expect `ParamsTest(DirectCast(Nothing, Object))` to.
