### ISSUE TITLE
Completion bug writing 'Task.'

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#10502]
It's a bug from the monodevelop bug tracker but affects VS.NET as well.

See: http://screencast.com/t/Xebulsw8

Seems to be always in that case:

Task.$ await Task

**Comment by DustinCampbell** [comment]
This is a tricky parser issue. The problem is that the parser is parsing as a local declaration there the variable name is `Task` and the type is `Task.await`. Passing to the compiler team to see if there's something better we can do here.

**Comment by Suchiman** [comment]
I'm not sure if that's the same problem but here's a very similiar case:
```csharp
using System.Threading.Tasks;

namespace IntelliSenseRepro
{
    public class SharingController
    {
        private Test Service => new Test();

        public async Task Test()
        {
            $
            await Service.SaveChangesAsync();
        }
    }

    public class Test
    {
        public async Task SaveChangesAsync() { }
    }
}
```
Go to $ and type `Service.`. Everything in the method is red underlined then 😉 

If you change the Code to:
```csharp
using System.Threading.Tasks;

namespace IntelliSenseRepro
{
    public class SharingController
    {
        public async Task Test()
        {
            Test Service = new Test();
            $
            await Service.SaveChangesAsync();
        }
    }

    public class Test
    {
        public async Task SaveChangesAsync() { }
    }
}
```
then everything after $ is still red squigglied but at least IntelliSense pops up and gives correct completion.

**Comment by jaredpar** [comment]
@gafter recovery work appears to have fixed this too. No longer repros on VS 2017.
