### ISSUE TITLE
Please provide nameof() for generic type paremeter's properties

### ISSUE THREAD

**Issue by m08pvv** [dotnet/roslyn#10504]
**Version Used**: shipped with VS 2015 Update 2

For this code:

``` csharp
class GenericsTest
{
    interface ISomeInterface
    {
        string SomeValue { get; set; }
    }

    class SomeInterfaceImpl : ISomeInterface
    {
        public string SomeValue { get; set; }
    }

    private void Method<T>()
        where T : ISomeInterface
    {
        var ok = nameof(SomeInterfaceImpl.SomeValue);
        var error = nameof(T.SomeValue);
    }
}
```

**Expected Behavior**:
both nameof() should be allowed

**Actual Behavior**:
nameof() for type parameter is not allowed

**Comment by jamesbascle** [comment]
Could do nameof(ISomeInterface.SomeValue).  What is the advantage of using T?  It seems counter to the way all the other nameof stuff works, where you reference the compile time types, rather than parameters or type parameters.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #810](https://github.com/dotnet/csharplang/issues/810) via [**ZenHub**](https://www.zenhub.com/)
