### ISSUE TITLE
An integration from master into future is blocked due to failure of CSharpErrorList tests

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#10528]
See PR https://github.com/dotnet/roslyn/pull/10524

Test results http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/594/

**Comment by srivatsn** [comment]
@heejaechang can you take a look?

**Comment by heejaechang** [comment]
Looking.


-          heejae

**Comment by heejaechang** [comment]
this is due to mismatch between solution explorer and msbuild. I am trying to see why msbuild still think there is class1.cs when solution explorer already deleted it.

**Comment by heejaechang** [comment]
I sent email to people to see whether it is okay to check my PR in. the issue has not been repro for a while though.

**Comment by heejaechang** [comment]
this has been repro for a while. I am closing this bug, reopen if it repro.

**Comment by mavasani** [comment]
Re-opening as the test still seems to be disabled: https://github.com/dotnet/roslyn-internal/blob/master/Closed/Hosting/Test/Execution/TestLocator.cs#L22

**Comment by heejaechang** [comment]
I am going to check this in (https://github.com/dotnet/roslyn-internal/pull/829) as a workaround for this bug. I have this bug open for actual issue (#10547)
