### ISSUE TITLE
recent binder changes in features/patterns branch break binding in incomplete code

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#10521]
The following test is suitable for adding to LocalFunctionTests.cs and demonstrates a compiler crash recently introduced in the binder refactoring on the features/patterns branch.

```cs
        [Fact]
        public void LocalFunctionInIf()
        {
            var source = @"
class Program
{
    static void Main(string[] args)
    {
        if () // typing at this point
        int Add(int x, int y) => x + y;
    }
}
";
            VerifyDiagnostics(source,
                // (6,13): error CS1525: Invalid expression term ')'
                //         if () // typing at this point
                Diagnostic(ErrorCode.ERR_InvalidExprTerm, ")").WithArguments(")").WithLocation(6, 13),
                // (7,9): error CS1023: Embedded statement cannot be a declaration or labeled statement
                //         int Add(int x, int y) => x + y;
                Diagnostic(ErrorCode.ERR_BadEmbeddedStmt, "int Add(int x, int y) => x + y;").WithLocation(7, 9)
                );
        }
```

**Comment by gafter** [comment]
This is blocking some testing of pattern-matching.

**Comment by AlekseyTs** [comment]
@gafter Could you, please, include a call stack for issues about crashes and asserts?

**Comment by gafter** [comment]
It was suggested in https://github.com/dotnet/roslyn/pull/10522#issuecomment-209200635 to "try adding handling for local functions in the LocalBinderFactory.VisitPossibleEmbeddedStatement? Similar how local declaration statements are handled. I suspect that could address the issue."

**Comment by gafter** [comment]
Fixed in `features/patterns` branch.
