### ISSUE TITLE
Is the Roslyn update 2 branch available that can be built?

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#10532]
**Version Used**: 
Visual Studio 2015 update 2
**Steps to Reproduce**:

1. Can't find source for Update 2 of Roslyn on https://github.com/dotnet/roslyn/
2. 
3. 

**Expected Behavior**:
Update-2 would be listed under Branches
**Actual Behavior
Update 1 is listed but no Update 2
![image](https://cloud.githubusercontent.com/assets/12789369/14502208/0c5c944c-015f-11e6-9e9a-0c85874462c3.png)

**Comment by Pilchie** [comment]
It's actually a tag, not a branch.  Depending on whether you have the MicroUpdate installed, you should have either https://github.com/dotnet/roslyn/tree/version-1.2.0 or https://github.com/dotnet/roslyn/tree/version-1.2.1
