### ISSUE TITLE
Rename doesn't disambiguate expression-bodied members

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1053]
Source:

```C#
class C {
	int f = new C().N(0);
	int M(int b) => N(0);
	int N(long b) => M(0);
}
```

Renaming `M` to `N` (or vice-versa) will correctly disambiguate the first line, but will show an unresolvable conflict on the second.

**Comment by dpoeschl** [comment]
Found a related but distinct case that I'll fix as part of this:
```C#
class C
{
    static int M(int b) => N(0); // Rename M to N
    static int N(long b) => M(0);
    System.Func<int, int> z = d => N(d); // This reference to N isn't updated
}
```

**Comment by dpoeschl** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/2622

**Comment by dpoeschl** [comment]
@balajikris Can you verify this? Thanks!
