### ISSUE TITLE
fix the race between DTE and msbuild/build

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#10547]
this bug is related to (https://github.com/dotnet/roslyn/issues/10528)

the issue here looks like a race.

...

Basically, what I see from the log is that, VS (solution explorer) sees only 1 file in the project, but the build sees another file (Class1.cs) and it is passed to csc and csc reports it as missing file.

The “class1.cs” is coming from project creation, right after creating a project, our AddProjectAction uses DTE to delete that file. And then this particular test, execute “Build”.

The test verified that DTE believe the file “class1.cs” no longer belong to the project we created, but msbuild believe it is still there. I tried to debug and it looks like VS update underlying data structure (build task) when either project is saved or refreshed. Which “Build” command should do before executing “Build”. but it looks like time to time that doesn’t seems to happen causing our test to fail.

...

regardless of making the test not flaky (https://github.com/dotnet/roslyn-internal/pull/829), this looks like product issue.

@jasonmalinowski says it is an issue in project system, so I am opening bug to @dotnet/roslyn-analysis

**Comment by heejaechang** [comment]
I spent 2-3 hours to go through code but too much new code. couldn't figure out in that time frame what part went wrong.

**Comment by heejaechang** [comment]
link to log
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/594/artifact/Open/Binaries/Release/VSIntegrationTestLogs/CSharpErrorList.html

link to build
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/594/

this build is marked as to keep until someone can investigate.

**Comment by DustinCampbell** [comment]
@jasonmalinowski -- what do we want to do here? Should this be fixed in the project system, or worked around in the test infrastructure? FWIW, it seems like the test infrastructure could be more robust anyway since it took HeeJae so long to locate the problem.

**Comment by jasonmalinowski** [comment]
I'm OK continuing with the workaround for now, but something seems very fishy there and I'm not sure what else might be broken.

**Comment by jasonmalinowski** [comment]
Not sure I remember enough of the context here.
