### ISSUE TITLE
NuGet analyzer does not start in DNX project

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#10543]
**Version Used**: 
VS2015 Update2

**Steps to Reproduce**:
1. Create new project of type Console Application (Package)
2. install-package jetbrains.annotations
3. install-package resharpercodecontractnullability

**Expected Behavior**:
Analyzer runs and reports two warnings.

**Actual Behavior**:
Analyzer from step 3 keeps silent. Running the above steps on a normal Console Application works. Replacing the last step with extension version (Tools > Extensions and Updates, search for "resharper code contract nullability") works on both project types.

I then built resharpercodecontractnullability from source and stripped all code, replacing it with a direct report on all parameters. Does not work either. Then I tried to install StyleCop.Analyzers in the DNX project, which also does not report anything. Also I noticed that Solution Explorer does not contain an Analyzers node for DNX.

**Comment by jmarolf** [comment]
This is not a Roslyn issue, Analyzer were not supported by the DNX project system.  The compiler fully supports these analyzers, it is just that the DNX infrastucture is not passing them to the compiler. DNX has merged into https://github.com/dotnet/cli.  My current understanding is that analyzer will work in dotnet-cli so you should see support in future releases.

**Comment by jmarolf** [comment]
Looks like analyser support was being tracked here: https://github.com/dotnet/cli/issues/83 and support was added by @agocke here: https://github.com/dotnet/cli/pull/927
