### ISSUE TITLE
Pull requests to roslyn-internal should always run VSI tests

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#10549]
We've recently had a number of breaks that slipped through because roslyn-internal PRs don't run VSI tests. This seems surprising, since the only time you're ever pushing to roslyn-internal is to either:

1. Update VSI tests.
2. Update our various setup build stuff (which only runs as a part of VSI builds)
3. Update various non-public VS integration bits.

These activities are both rare, and already would require the developer to run VSI tests before merging. So we should do it automatically.

**Comment by dpoeschl** [comment]
It appears to be working.
