### ISSUE TITLE
Proposal: null-conditional assignment

### ISSUE THREAD

**Issue by Ricciolo** [dotnet/roslyn#10556]
Hi guys!
Since we've null-conditional operator, why we cannot have a null-conditional assignment, like:
```c#
string var1 = "value1";
string var2 = null;
var1 ?= var2;`

Assert.AreEqual("value1", var1);
```

You may say that I can write the same thing using
```c#
string var1 = "value1";
string var2 = null;
var1 = var2 ?? var1;
```
but here I'm setting var1 to var1 even **if not necessary**.
With null-conditional assignment the compiler produce this code:
```c#
string var1 = "value1";
string var2 = null;
if (var2 != null) var1 = var2;
```
With null-conditional operator instead:
```c#
string var1 = "value1";
string var2 = null;
var1 = (var2 != null) ? var2 : var1;
```

What do you think?

**Comment by HaloFour** [comment]
Dupe of #10249, #9529, #8894, #5163, #3366 and #205.

The resolution of #205 was "won't fix", so I don't think that the operator is under consideration.

**Comment by Ricciolo** [comment]
ops, sorry :-(
