### ISSUE TITLE
CSProj->xProj In Compatible Reference provides a confusing Error Message

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#10563]
Repro Steps 

- Create a new .Net Core Class Library (By default it creates with .NetStandard 1.5) 
- Create a Windows Console Application
- Add a "project.Json" File to the same
Add following text to it 

{
  "frameworks": {
    "net461": { }
  },
  "runtimes": {
    "win": { }
  }
}

Also go to the properties of the console application and make it point to 4.6.1 

- Build both the projects.
- Now reference the Class Library from the console application.

Expected 
You should get a Error Message that the corresponding reference is incompatible 

Actual 
![incompatible](https://cloud.githubusercontent.com/assets/12449387/14538346/2fefe176-0230-11e6-990c-b875ef4854a8.JPG)

**Comment by Pilchie** [comment]
Given the convergence on csproj, we're not fixing this particular bug.
