### ISSUE TITLE
CSharpRenameTrackingCodeFixProvider crashes on tuples

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#10567]
See illustration below.

![image](https://cloud.githubusercontent.com/assets/12466233/14755091/8e1084a8-0894-11e6-9dbd-1743c473c733.png)

![rename-tuple](https://cloud.githubusercontent.com/assets/12466233/14540213/bf958666-0238-11e6-9a2d-979741580e70.png)

**Comment by VSadov** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/10903
