### ISSUE TITLE
Tuple types should be prettier in debugger

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#10572]
See snapshot below. The tuple portion should show as `(int, int)`.

![debugger-tuple-signature](https://cloud.githubusercontent.com/assets/12466233/14540466/018321fe-023a-11e6-940c-e94c644106b2.png)

**Comment by jcouv** [comment]
@cston, I think your PR https://github.com/dotnet/roslyn/pull/13392 already fixed this. Can be closed?

**Comment by jcouv** [comment]
@cston, I just tried it and the printing of the method signature still matches the snapshot above.

**Comment by cston** [comment]
@jcouv That string appears to be from `ToString()` on the underlying `MethodInfo`. The EE does not currently special-case the display of delegates.
```
f.Method.ToString()
"System.ValueTuple`2[System.Int32,System.Int32] _Lambda$__0-0()"
```

**Comment by jcouv** [comment]
I see. Resolve as By Design?
