### ISSUE TITLE
Codelens on split line annotates wrong line

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#10575]
The snapshot says it all.

![codelens-split-line](https://cloud.githubusercontent.com/assets/12466233/14540599/b4e9dc2e-023a-11e6-987c-6c86b915c73e.png)

**Comment by Pilchie** [comment]
Clearing assignment so this will show up in triage queries.

**Comment by Pilchie** [comment]
I don't think that sort of formatting occurs frequently enough to warrant fixing.  Unfortunately, the code for the tagger that determins that location is closed source, or I would just make it "Up for Grabs".

**Comment by jcouv** [comment]
Another report of this issue at https://developercommunity.visualstudio.com/content/problem/1888/codelens-not-appearing-in-correct-place.html
