### ISSUE TITLE
Intellisense does not help name members in tuple literals

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#10586]
Intellisense doesn’t help when typing the parameters to a method that has tuples parameter

![tuple-return-intellisense](https://cloud.githubusercontent.com/assets/12466233/14541174/7d2328ba-023d-11e6-8071-8f26e46affe5.png)

There may be other scenarios where Intellisense could help type tuple member names:

``` C#
(int Alice, string Bob) M()
{
    return (Ali***
}
```

From discussion with Cyrus, this would likely be a new completion provider, possibly similar to `NamedParameterProvider`.

**Comment by jaredpar** [comment]
To clarify: when we can target type tuple literals we should give member name completion in Intellisense.

**Comment by jcouv** [comment]
Update: after the unification work last week, this works now.
![image](https://cloud.githubusercontent.com/assets/12466233/15154688/baae1504-1693-11e6-9fc1-81a55eeb055a.png)

I'll add some test automation.

**Comment by jcouv** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/16565
