### ISSUE TITLE
pre, post and test blocks

### ISSUE THREAD

**Issue by mhomde** [dotnet/roslyn#106]
Id really like to see code contracts and unit testing be more integrated with the language and tools, less verbose and requiring less to setup. Being able to let the "meat" of a method be separated from all the error-checking, post, pre conditions etc would really make things cleaner (and you could easily collapse the other blocks).

Current implementation of code contracts feels like it requires too much setup with separate classes, duplicate method signatures in several places etc etc. It would be nice to have something like

  public int SomeMethod(int a, int b)

  pre 
  { 
    Requires (a > 5, () => return 0);
    Requires (b >= 0, new Exception("something something"));
  }

  {
     // DoStuffHere
  }

  post
  {
    Ensures (result > 0, new Exception("needs to be above 0"));
  }

**Separate from main code**

It would be good if you could separate this code from the main code to make it less cluttered, with or without duplicating signature depending if you wanted to target specific overloads

Full signature would simply be without the body:

  public int SomeMethod(int a, int b)

  pre
  {
    Requires (a > 5);
    Requires (b >= 0 ,new Exception("something something"));
  }

  post
  {
    Ensures (result > 0);
  }

**Conditions without specific signature**

This is trickier but would be nice since you could use same conditions for several overloads, and just target the variables that are included in each:

  Conditions.SomeMethod
  {
    pre
    {
      Requires (a > 5);
      Requires (b >= 0, new Exception("something something"));
    }

   post
   {
     Ensures (result > 0);
   }
  }

**Test Blocks**

Might be a little apple and oranges but... A test block would also be really nice and for instance let Visual studio  run light-weight kind of unit tests in the background as you programmed and mark the whole method as functioning or not. Also allowing you to write quick inline test would lessen the friction for unit-testing.  Imagine having a sort method and throw in something like:

  public IEnumerable<int> Sort (IEnumerable<int> list, Order order)
  test
  {
     (list={3,5,6,2}, order=Order.Ascending) => result == {2,3,5,6};
     (list={3,5,6,2}, order=Order.Descending) => result == {6,5,3,2}
  }

VS could highlight the failed test(s) directly in the editor as you coded

**Comment by gafter** [comment]
We are tracking contracts in #119.
