### ISSUE TITLE
Should property patterns be capable of referencing an indexed property?

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#10600]
If we want property patterns to be capable of referencing an indexed property, we will need to extend the bound nodes that represent them. Similarly for dynamic indexers and events. See also #9515.

**Comment by AdamSpeight2008** [comment]
What would (if any) be on the index?
* Constants `P { X[ 0 ] is var x }`
* Reference `P { X[ index ] is var x }`
* What about the checking of the index bounds? `Index <0 || Index >= X.Length`
* (VB) Is the dictionary lookup operator also allowed? `P { X!foo is var x }`

**Comment by gafter** [comment]
@AdamSpeight2008 

If we do it, certainly constant indices would be allowed. However, given that indexed properties are not supported in a first-class way in C#, it seems unlikely we would do it.

We would not support VB operators in C#.

**Comment by AdamSpeight2008** [comment]
My comment was more about, what would be allowed should pattern-matching be brought into VB

**Comment by AdamSpeight2008** [comment]
My Comment was more about, what is should be allowed if pattern-matching is added to VB

**Comment by alrz** [comment]
Also indexers themselves, `P { [ 0 ] is var x }`. Related: #5811.
