### ISSUE TITLE
Should the filter for pattern variables stay?

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#10605]
@AlekseyTs 

The below comment was found in `DataFlowPass.VisitUsingStatement`. I'm not sure what the reason for the question is; perhaps it has something to do with separating the scope of the pattern variables from the scope of the using variables? Whatever it is, please explain in this issue, as I'm removing the PROTOTYPE comments in preparation for integration into `future`.

```cs
            // PROTOTYPE(patterns): Should the filter for pattern variables stay?
            Debug.Assert(localsOpt.Where(l => l.DeclarationKind != LocalDeclarationKind.PatternVariable).All(_usedVariables.Contains));
```

**Comment by AlekseyTs** [comment]
The question is whether there is a good reason for the Where used inside the Assert, it is filtering out pattern variables. Should it?

**Comment by gafter** [comment]
The assert is asserting that the variables declared by a using (except for pattern variables) is used. That specifically applies to the using statement's own variable. Yes, the filter is necessary for correctness of the assertion.
