### ISSUE TITLE
Codegen in debug mode fails on iterating over IEnumerable function in base class

### ISSUE THREAD

**Issue by rf232** [dotnet/roslyn#10611]
**Version Used**: Future branch head and VS15 Preview

**Steps to Reproduce**:

[Bug.zip](https://github.com/dotnet/roslyn/files/220577/Bug.zip)

1. Compile attached CS file in Debug configuration

**Expected Behavior**:

A successful compilation

**Actual Behavior**:

Crashing csharp compiler, when attaching to the crashing compiler it appears to try to do 
`Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GetLocalDebugName` on the `base.F()` on line 17, which fails because `CalculateLocalSyntaxOffset` fails on the `MoveNext`

**Comment by tmat** [comment]
This is future specific bug.

**Comment by jaredpar** [comment]
Thanks for reporting this.  This ended up also getting tracked via #11649 which we recently checked in a fix for.
