### ISSUE TITLE
Open issues in tuple conversions and overload resolution

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#10621]
There are subtle interactions between tuple literal conversion, a hypothetical tuple widening conversion that was proposed in a recent LDM, and overload resolution. It would be incompatible to change the way this works later, so we need to iron out the details before tuples ship.

Here are some of the interesting conversions that affect overload resolution:

Does the conversion from (1, 2) to (int, int) satisfy the bullet

> •	E has a type S and an identity conversion exists from S to T1 but not from S to T2

(because (1, 2) has the natural type (int, int) thereby making it better than any other conversion from expression, for example to (byte, byte)?

Does the conversion from (1, null) to (int, object) satisfy a hypothetical recursive bullet in the "Better conversion from expression" section making it a better conversion than, say, the conversion to (byte, string)? Or is the latter a better conversion target by virtue of there being an implicit (widening tuple) conversion from (byte, string) to (int, object), making it a "better conversion target"?

CC @VSadov @jcouv @MadsTorgersen @AlekseyTs @dotnet/roslyn-compiler @dotnet/ldm

**Comment by CyrusNajmabadi** [comment]
It might be good to have a list of interesting permutations.  I’d like to see that list so I could figure out what my intuition would be in those cases.  Based on that I would have an easier time working back to actual language rules.

           -- Cyrus

**Comment by gafter** [comment]
The answer is that the "better conversion from expression" has special handling for tuple literals, so the type of a tuple literal won't make any difference. This is already spec'd and implemented.
