### ISSUE TITLE
Move SQM TO AI [Project System]

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#10625]
SQM is going away. project system needs to either remove SQM or move to AI.

**Comment by heejaechang** [comment]
related to https://github.com/dotnet/roslyn/issues/10433 and https://github.com/dotnet/roslyn/issues/10432

**Comment by heejaechang** [comment]
please let me know by 5/16 what is plan for existing SQM (remove, replace)
actual code should be checked in by 7/25

**Comment by heejaechang** [comment]
@jmarolf deadline is updated to 7/9

**Comment by Pilchie** [comment]
What happened here?

**Comment by MattGertz** [comment]
This got done a long time ago.
