### ISSUE TITLE
Possible unification of type pattern, positional pattern, and property pattern

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#10636]
This is a possible unification of the syntax for the positional pattern, property pattern, tuple pattern, var pattern, and type pattern.

The syntactic constraints on the syntax for _recursive_pattern_ are as follows:
- At least one of the parts before the _identifier_ is required.
- The _pattern_type_ may not be a tuple type.

Furthermore, when a _positional_subpattern_ is present, a _identifier_ or _property_subpattern_ may only be present if the _positional_subpattern_ binds to a _tuple type_ or a type with a _self-typed_ deconstructor.

``` antlr
recursive_pattern
    : pattern_type? positional_subpattern? property_subpattern? identifier?
    ;

pattern_type
    : `var`
    | type
    ;

positional_subpattern
    :  '(' subpattern_list? ')'
    ;

subpattern_list
    : subpattern
    | subpattern ',' subpattern_list
    ;

subpattern
    : argument_name? pattern
    ;

property_subpattern
    : '{' property_pattern_list? '}'
    ;

property_pattern_list
    : property_pattern
    | property_pattern ',' property_pattern_list
    ;

property_pattern
    : identifier 'is' pattern
    ;
```

**Comment by gafter** [comment]
@AlekseyTs @agocke FYI

**Comment by bbarry** [comment]
Effectively a change something like this to patterns.md?

```antlr
positional_pattern
    :  type? '(' subpattern_list? ')'
    ;

property_pattern
    :  type identifier? '{' property_subpattern_list? '}'
    |  '{' property_subpattern_list? '}'
    | var identifier '{' property_subpattern_list? '}'
    ;
```

**Comment by gafter** [comment]
@bbarry No, that wouldn't allow

```cs
    Point M() => ...;

    if (M() is (var x, var y) p { Length is 5 }) Console.WriteLine(p);
```

**Comment by alrz** [comment]
I believe @bbarry meant the ability to name the whole pattern in positional patterns,
```diff
positional_pattern
-   :  type? '(' subpattern_list? ')'
+   :  type? '(' subpattern_list? ')' identifier?
    ;
```
Obviously you wouldn't be able to omit the *type* when you are not matching against a tuple but identifier part still makes sense. It seems that it's just missing.

**Comment by alrz** [comment]
I believe @bbarry meant the ability to name the whole pattern in positional patterns,
```diff
positional_pattern
-   : type? '(' subpattern_list? ')'
+   : type? '(' subpattern_list? ')' identifier?
    ;
```

Also, I think it reads better if you put the identifier at the end in property patterns, 
```diff
property_pattern
-   : type? '{' property_subpattern_list? '}'
-   | type identifier '{' property_subpattern_list? '}'
-   | var identifier '{' property_subpattern_list? '}'
+   : type? '{' property_subpattern_list? '}' identifier?
    ;
```
It makes the `var` unnecessary, regardless of the presence of the type itself. 

I suppose it would be possible to use both positional and property patterns at the same time,
```cs
case Point p:
case Point ( .. ) p:
case Point { .. } p:
case Point ( .. ) { .. } p:
```

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #473](https://github.com/dotnet/csharplang/issues/473) via [**ZenHub**](https://www.zenhub.com/)
