### ISSUE TITLE
Pattern-matching when value out of range?

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#10632]
- [ ] In what situations should the compiler be required by specification to warn about a match that must fail? E.g. switch on a `byte` but case label is out of range?

**Comment by AdamSpeight2008** [comment]
The indice of the following?
* Constant Strings
* Initialized Fixed Length Arrays
* Initialized ReadOnly Collections

**Comment by gafter** [comment]
@AdamSpeight2008 A constant string doesn't have an "indice". And neither of your latter two bullets are pattern-matching forms.

**Comment by AdamSpeight2008** [comment]
@gafter   You sure? What about `"gafter"[0] ` ?

**Comment by gafter** [comment]
@AdamSpeight2008 That's not a pattern. That's an expression.

**Comment by gafter** [comment]
We use the existing rules: the case expression is converted to the type of the switch expression. If it is out of range there is no such implicit conversion, and a compile-time error is given. This is all implemented in master and will be in dev15 preview 4.
