### ISSUE TITLE
Cleanup interop code

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#10637]
The following APIs are obsolete on netstandard1.3/FX 4.6:

```
Marshal.GetNativeVariantForObject
```

**Comment by tmat** [comment]
This is actually in the compiler code base.

**Comment by jaredpar** [comment]
This may be in the compiler code base but the work isn't trackde by my team at the moment.  Hence interactive seems more appropriate.

**Comment by tmat** [comment]
Fixed by #22611
