### ISSUE TITLE
Fix detection of DeprecatedAttribute to understand TH2 format .

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#10630]
Practically, the DeprecatedAttribute can have the following signatures.

- DeprecatedAttribute(String, DeprecationType, UInt32) – this is the Win8 and Win8.1 format for the deprecated attribute
- DeprecatedAttribute(String, DeprecationType, UInt32, Type) – this is the TH1 format for the deprecated attribute. Note that this form of the attribute constructor does NOT appear in the metadata for TH2 and beyond, just in the TH1 metadata.
- DeprecatedAttribute(String, DeprecationType, UInt32, String) – this is the TH2 format for the deprecated attribute. This is the form that will appear for TH2 and future releases.

We are currently looking for

```C#
            switch (attributeInfo.SignatureIndex)
            {
                case 0: // DeprecatedAttribute(String, DeprecationType, UInt32) 
                case 1: // DeprecatedAttribute(String, DeprecationType, UInt32, Platform) 
                case 2: // DeprecatedAttribute(String, DeprecationType, UInt32, Type)
```

we should add a case for 

```C#
 case 3: // DeprecatedAttribute(String, DeprecationType, UInt32, String)
```
and change underlying implementation accordingly.

**Comment by markhurd** [comment]
You obviously know what you mean, but, currently, your "changed" case 1 isn't different :-)

**Comment by VSadov** [comment]
@markhurd - right. copy paste issue. Obviously the replacement should be different.

**Comment by VSadov** [comment]
Turns out that is not so trivial to arrange reliably. 
(kind of a long story, but in some cases Deprecated attributes with same number of parameters look the same, so selectively disallowing one has effect on another) 

There is also a compat concern – if there is a chance that someone used the overload with Platform, he will find that the attribute no longer works after installing VS update. That would be unexpected. After all this constructor is public and documented. ( https://msdn.microsoft.com/en-us/library/dn264126 )

At this point, I think  the better course of action is to just add the TH2 signature to the recognized set and keep the others as is. 
If the overload with Platform never happens in the wild – noone would care. If it somehow does – there would be no observable change resulting from compiler update.
