### ISSUE TITLE
Improve error message of warning RS0007: Avoid unnecessary zero-length array allocations.

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#10647]
Currently the warning message uses C# syntax even for VB:
```
warning RS0007: Avoid unnecessary zero-length array allocations.  Use Array.Empty<T>() instead
```

It would also be useful to display the actual type instead of generic T.

**Comment by AdamSpeight2008** [comment]
@tmat 
It should also provide a code-fix.

**Comment by srivatsn** [comment]
Moved to the roslyn-analyzers repo.
