### ISSUE TITLE
seal Diagnostic type

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#1064]
currently Diagnostic is public abstract type so all abstract/virtual method can

1. throw
2. can return null

either we need to audit all of our engine code to properly deal with them or we should seal the diagnostic type.

**Comment by heejaechang** [comment]
for 1, we could do what we did for descriptor. for 2, we can use the pattern compiler uses (abstracts are all protected, and public ones can't be overriden)

**Comment by mavasani** [comment]
I should add that this is not an immediate concern for rc2 milestone as Diagnostic has internal abstract methods, so we can only have internal implementations. We should address this for the long term though.

**Comment by heejaechang** [comment]
@mavasani we are lucky :) 

looks like we have these two methods WithLocation and WithSeverity that are internal abstract.

**Comment by srivatsn** [comment]
Since no one can derive from Diagnostic, the value of sealing seems limited. Won't fixing this issue.
