### ISSUE TITLE
Is the Roslyn roadmap dated?

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#10640]
Some features like the Interactive Window exists since VS2015 Update 1 and probably few more things so maybe someone can have a look and update the [project roadmap](https://github.com/dotnet/roslyn/wiki/Roadmap) page? :)

P.S. Just an idea, it would be great if features of VB.NET and C# were categorized by versions so we would know what was implemented in previous releases since the first release of Roslyn and what is going to be implemented in the upcoming release/releases or at least ideas much like the [TypeScript](https://github.com/Microsoft/TypeScript/wiki/Roadmap) team does it.

If this is not possible then maybe add the most recent design notes for each related version or something like that.

**Comment by MgSam** [comment]
They put this together recently: https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md

I don't know if it's linked anywhere.

**Comment by eyalsk** [comment]
Thanks! hopefully they will update the roadmap page so people would know about it too! :)

**Comment by gafter** [comment]
The Roslyn repo does not contain any roadmap for features other than language features. The language feature status pages are fairly up-to-date.

**Comment by eyalsk** [comment]
@gafter okay, thank you for clarifying this.

**Comment by DavidArno** [comment]
@eyalsk,

It's definitely worth keeping an eye on the page too as it does change, eg records are no longer listed as likely to be in C# 7, whereas they were before...

**Comment by eyalsk** [comment]
@DavidArno yeah, I'll do that, didn't know it exists, I generally filter issues. :)
