### ISSUE TITLE
[VB] Implements and Inherits on same line of a class / structure definition.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#10652]
Is it possible to make the EoL optional? In the cases of `Implements` and `Inherits`
```VB
Class Foo
  Inherits ThisBase
End Classs
```
```VB
Class Foo Inherits ThisBase
End Classs
```
```VB
Class Foo
  Implements ThisInterface
End Classs
```
```VB
Class Foo Implements ThisInterface
End Classs
```

**Comment by HaloFour** [comment]
It's funny, I always just got into the habit of using the `:` character to maintain them on the same line:

```vb
Class Foo : Inherits ThisBase
End Class
Class Foo : Implements ThisInterface
End Class
```

**Comment by AdamSpeight2008** [comment]
@HaloFour 
Personally I don't consider `Inherits` and `Implements` as **statements** but as part of the class / structure signature. The use of `:` is a bit hacky. _(imho)_ also makes it look like you can use them anywhere. eg like within a method.

**Comment by gafter** [comment]
Since you can already use them on the same line (with a colon) I don't think any further action on our part is necessary.
