### ISSUE TITLE
Build failure on mac with Unable to load DLL 'System.Security.Cryptography.Native'

### ISSUE THREAD

**Issue by ckkashyap** [dotnet/roslyn#10668]
**Version Used**: 332810056e84bd520821a177f7bd7cb7520d1435

**Steps to Reproduce**:

1. On mac OSX El Capitan 10.11.4
2. git clone https://github.com/dotnet/roslyn.git
3. cd roslyn; make

**Expected Behavior**: successful build

**Actual Behavior**:

Restoring toolset packages
log  : Restoring packages for /Users/kashyap/Documents/dev/MS-CLR/roslyn/build/ToolsetPackages/project.json...
error: Unable to load the service index for source https://www.myget.org/F/dotnet-coreclr/api/v3/index.json.
error:   The type initializer for 'Crypto' threw an exception.
error:   Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
error:    (Exception from HRESULT: 0x8007007E)
Restore CrossPlatform.sln
error: Unable to load the service index for source https://www.myget.org/F/dotnet-coreclr/api/v3/index.json.
error:   The type initializer for 'Crypto' threw an exception.
error:   Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
error:    (Exception from HRESULT: 0x8007007E)
Restore failed
make: *** [/Users/kashyap/Documents/dev/MS-CLR/roslyn/Binaries/toolset/restore.semaphore] Error 255

**Comment by DustinCampbell** [comment]
I suspect you need to install openssl on your Mac. Try the following:

1. Open a terminal window
2. `brew update`
3. `brew install openssl`

**Comment by ckkashyap** [comment]
I installed openssl using brew - but I continue to get the same error

**Comment by DustinCampbell** [comment]
For reference: https://github.com/dotnet/cli/issues/2229

**Comment by jaredpar** [comment]
CC @agocke

**Comment by agocke** [comment]
@ckkashyap Did you resolve this offline with CoreFX? This is a CoreCLR/CoreFX dependency, so Roslyn shouldn't have anything to say here.
