### ISSUE TITLE
Unable to perform EnC inside of iterator functions in VB.

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#10669]
**Version Used**: 
VSUML 25218.00
**Steps to Reproduce**:
1. Create a new VB project.
2. Use the following code and create a breakpoint at the start of the main method:

```
Module Module1
Sub Main()
    For Each x As Integer In F()
        Console.WriteLine(x)
    Next

    Console.ReadLine()
End Sub

Iterator Function F() As IEnumerable(Of Integer)
    Yield 10
End Function

End Module
```
1. Start Debugging.
2. Update 10 inside F() to a new value.
3. Hit Continue

**Expected Behavior**:
Output should show the new value
**Actual Behavior**:
Debugging fails to continue. Gives the pop up saying that it's not valid. No error messages appear in error list. See picture below:

![image](https://cloud.githubusercontent.com/assets/10537189/14623212/e815f996-0584-11e6-90c9-f179e6c1ceab.png)

**Comment by mattscheffer** [comment]
Note that this only occurs in VB. C# can still handle these scenarios fine.

**Comment by jinujoseph** [comment]
@ivanbasov , looks like this is regression , can you take a look 
cc/ @tmat

**Comment by ivanbasov** [comment]
I have tried to reproduce this with Version 15.3 (26430.0-Preview) d15rel Internal Preview - Dogfood. It seems to work fine. No problem found. @mattscheffer, could you please verify on your side or provide more information?

**Comment by mattscheffer** [comment]
Looks like this has been fixed since the bug was made over a year ago. Confirmed with recent internal 15.3 build.

**Comment by tmat** [comment]
Cool. I guess we have accidentally broke this and then accidentally fixed it too :-o. @ivanbasov do we have the right unit tests in place?

**Comment by ivanbasov** [comment]
Thank you! I created https://github.com/dotnet/roslyn/issues/19755 to cover this with a unit test.
