### ISSUE TITLE
Edit.QuickInfo doesn't reveal error details

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#10661]
Using Visual Studio 2015 update 2, it is possible to reveal the details of an error by bringing the mouse over to the squiggled text. But there is no way to reveal those details using the keyboard only.

`Edit.QuickInfo` seems the appropriate command to handle that. In some scenarios it works (when the error is not so severe and there is type information for the squiggled text). But in other cases it just does nothing (for instance, if you type `System.Blah;`)

**Comment by dpoeschl** [comment]
@rchande Can we get your PR for this merged in for the `2.0 (RC)` milestone?

**Comment by rchande** [comment]
@jcouv @dpoeschl The fix for this is now merged.

**Comment by jcouv** [comment]
Nice. Thanks!

**Comment by rchande** [comment]
The fix for this was reverted.

**Comment by dpoeschl** [comment]
Investigating to see if this needs to stay in 15.3. @rchande - Do we have ideas for how to fix this more betterly?
