### ISSUE TITLE
Proposal: Class Instance Variables

### ISSUE THREAD

**Issue by bawNg** [dotnet/roslyn#10678]
Static variables in C# are severely limited compared to options available in some other languages, this makes static methods a lot less useful when it comes to derived classes. Making better use of the class level can allow for cleaner, more efficient implementations which require less code.

I propose that a new kind of variable scope be created which allows declaring variables which are on a class level but are not shared between derived classes. This would give derived classes far more flexibility when it comes to making use of base class functionality. I have put together an example using the following minimal implementation to show why this would be useful.

**Example Implementation**
- A new keyword would be needed, I will use `substatic` for my example.
- For each `substatic` variable in a derived class, the compiler would have to generate a static variable which has an identifier for the derived class appended to the name.
- References made to `substatic` variables by base classes should resolve to the static variable which belongs to the most derived class for the given object.
- The return value of a `substatic` method called on a derived class should be automatically cast to the derived type if the return type is the base class.

**Example Usage**
```csharp
public abstract class MongoDocument
{
    public static void Setup<T>()
    {
        var name = typeof(T).GetCustomAttribute<DatabaseAttribute>().Name;
        database = MongoDriver.GetDatabase(name);
        foreach (var field in typeof(T).GetFields())
        {
            fields.Add(new Field(field.GetType().GetCustomAttribute<FieldAttribute>().Name));
        }
    }

    public substatic MongoDocument Find(int id) => database.Find(id);

    protected substatic MongoDatabase database { get; private set; }
    protected substatic List<Field> fields = new List<Field>();
}

[Database("users")]
public class User : MongoDocument
{
    [Field("name")]
    public string Name;
}

static void RunTest()
{
    MongoDocument.Setup<User>();

    // The MongoDocument instance is automatically cast to User when the substatic method
    // is called on the User class
    var user = User.Find(1);
    Console.WriteLine(user.Name);
}
```

Additional improvements could include support for virtual static methods and support for expressions in a class body so that static fields/properties can be set and static methods can be called without requiring a static constructor.

**Comment by DavidArno** [comment]
Why are you trying to mix statics and derived classes? In what way won't your solution work by just making the members of `MongoDocument`, instance members?

**Comment by bawNg** [comment]
@DavidArno 
The whole point of this proposal is to extend support for static methods. You can't use `User.Find` as shown in the example unless the derived class can store state specific to itself.

**Comment by DavidArno** [comment]
> The whole point of this proposal is to extend support for static methods
Sure, I get that. But it's unclear why you *want* to do that as your example could easily be reworked using instance members. It's unclear what benefit your proposal would bring to the language and how that benefit would outweigh the added complexity.

**Comment by bawNg** [comment]
The benefit is cleaner, simpler implementation and usage. By being able to make better use of the class level for derived classes, you can build a cleaner API without having to wrap every derived class with a singleton object.

**Comment by HaloFour** [comment]
If you keep the MongoDatabase separate from the document classes (which you should be doing anyway so that you can actually write proper tests) then there's no need for a language feature like this.  Simply have the database instance have a generic method to retrieve a document class, no casting or voodoo necessary.

**Comment by eyalsk** [comment]
@bawNg I'm sure you heard this mantra a lot but it's a bad idea to store state in a static variable, singletons are better used in factories, I'd also invert the control flow through IoC and use something like IoC Container to inject dependencies and control the life time of the objects through the container rather than hard-code them in the application which brings me to another point and is favor composition over inheritance.

User **is not** a MongoDocument and therefor I'd say that you would open yourself for a much better design if you created an instance of MongoDocument per User the only thing you would need to pass is `this` like this:

```CSharp
[Database("users")]
public class User
{
	MongoDocument _mongo;

	public User()
	{
		_mongo = new MongoDocument(this);
	}

	[Field("name")]
    public string Name;
}
```
But even much superior design is doing something like this:
```CSharp
	MongoDocument mongo = new MongoDocument();

	mongo.Create<User>();
```
I understand that this is a proposal but I just thought that few tips might help you out. :)

**Comment by bawNg** [comment]
@HaloFour 
You are correct that generic classes can be used for this example, as they generate a separate class for each type which does not share static variables with other types. I overlooked using a generic type for the return of the base class method in the example when I originally put this proposal together.

@eyalsk
I understand your reasoning behind your suggestions, and in many cases they would be a good option, but they are not necessarily a good fit for high performance environments. If the implementation does not require the flexibility, I would rather save on heap allocations and CPU time by simplifying the implementation.

I'm going to go ahead and close this in favor of using generic classes instead.

**Comment by eyalsk** [comment]
@bawNg this has nothing to do with high performance! there's no reason to trade bad design with performance and in your case it's not about performance but something else but good luck with that mindset.

**Comment by bawNg** [comment]
@eyalsk 
In high performance environments such as large FPS game servers with hundreds of players, GC pressure caused by accumulated heap allocations and CPU time from excessive IL instructions and distant heap references can matter a lot more than you realize. Additional optimization has to be done with rewriting the IL after compilation in certain cases.

I also heavily favor clean and completely DRY APIs where possible, and therefore would choose `User.Create` over `mongo.Create<User>` as it would save a lot of verbose syntax and increase the overall readability of implementation. Since almost everything I implement has to make use of object pooling, that already increases the verbosity of syntax and creates a lot of additional line noise.

**Comment by eyalsk** [comment]
@bawNg I don't claim to know what you're doing but I referred specifically to your initial post where the design is quite _weird_ in terms of software design and trading it for a better design _shouldn't_ impact performance at all.

Introducing a factory method such as `Create` means your `User` class besides representing a `User` now deals with creating it, not to mention that you're locking your software into specific database knowledge, I don't know what's clean about this design.

Derived classes of `User` will have to introduce their own factory methods and yet you're claiming that you're in favor of DRY.

Generally, over engineering stuff and over complicating stuff leads to bad performance not a better design.

Anyway, this is just my personal opinion about the code that you posted, good luck. :)

**Comment by bawNg** [comment]
@eyalsk The initial example was just a small sample I threw together to demonstrate possible usage. It was by no means intended to be taken as production code. Thank you for trying to help though, I completely understand where you are coming from.
