### ISSUE TITLE
CSProj portable ClassLibrary Reference to xProj Class Library Not working 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#10689]
**Steps to Reproduce**:

1. Create a portable class library , 
2. point the same to "Target .Net Standard " and point to Netstandard 1.5 
3. This should add a project.json with below information 
{
  "supports": {},
  "dependencies": {
    "NETStandard.Library": "1.0.0-rc2-23910"
  },
  "frameworks": {
    "netstandard1.5": {}
  }
}
4. Build it 
5. Now create a Core Class Library , by default it points to .netstandard1.5
Project.json will have below information 
{
  "version": "1.0.0.0",

  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24008"
  },

  "frameworks": {
    "netstandard1.5": {}
  }
}
6. Now reference core class library from portable class library.

**Expected Behavior**:
Reference Works since they are compatible 

**Actual Behavior**:

![pcl_core](https://cloud.githubusercontent.com/assets/12449387/14650364/5962b85a-0620-11e6-859d-67977a7144fd.JPG)

**Comment by jinujoseph** [comment]
This might be related to this bug https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&newQuery=true&id=214260&triage=true

**Comment by rchande** [comment]
@jasonmalinowski I tried to debug this, but, as far as I can tell, the PCL flavor isn't even getting asked if this reference is possible. Is this an issue with csproj -> xproj?

**Comment by Pilchie** [comment]
My guess is that PCL is asking - "What is your output path for a target framework of `.NETPortable,Version=v5.0` and xproj doesn't know.  We need to think about how we flow the netstandard version from project.json into this.

I think same issue is affecting adding a reference the other way.

**Comment by davkean** [comment]
This looks like a csproj issue - not a PCL issue, we're not involved at this point. See IDS_LANGBLD_E_CANNOT_REFERENCE_COMPLUS_NONDLL in csproj.

**Comment by Pilchie** [comment]
Given the plan to converge project.json with msbuild, we don't plan to enable this support at this point.
