### ISSUE TITLE
EnC: Avoid checking for semantic errors on the entire compilation

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#10683]
It's expensive, can we avoid it?

http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/EditAndContinue/AbstractEditAndContinueAnalyzer.cs,441

**Comment by gavinhuet** [comment]
This issue is making EnC unusable in our application. It can take 20s to over a minute to make the simplest of changes. 
Stopping debugging and rebuilding the app is quicker!

**Comment by ManishJayaswal** [comment]
Another customer is seeing perf issues during debugging because of this. We should see if we can prioratize this and get it fixed for RTM.

**Comment by gavinhuet** [comment]
What is the status of this issue? Would love to have it resolved sooner rather than later.

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/19167.
