### ISSUE TITLE
Enable Object Browser Support for xproj references 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#10685]
**Steps to Reproduce**:
1.  Create a Windows Console Application 
2.  Add project.json file with the below content  and build.
    {
       "frameworks": {
       "net462": { }
   },
      "runtimes": {
      "win": { }
   }
   }
3.  Now Add a Core class library , build
4. Reference the class library from the console application.
5. Double click the reference from the solution explorer

**Expected Behavior**:
It takes you to the object browser view of the reference

**Actual Behavior**:
![objectbrowser](https://cloud.githubusercontent.com/assets/12449387/14648688/60e4abf4-0618-11e6-8d3d-19729e07ab07.JPG)

**Comment by Pilchie** [comment]
@DustinCampbell - you said you thought you had an internal bug on this too.

**Comment by Pilchie** [comment]
Is this still an issue with .NET Core projects?
