### ISSUE TITLE
Can't download Scripting API from NuGet

### ISSUE THREAD

**Issue by Robbertie** [dotnet/roslyn#10699]
**Version Used**: 2.0.0-beta1

**Steps to Reproduce**:

1. I just download the package and it gives me the error

**Expected Behavior**: I want to download the package but it just doesn't want to work

**Actual Behavior**: Could not install package 'System.AppContext 4.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly 
references or content files that are compatible with that framework

**Comment by tmat** [comment]
Scripting requires .NET Framework 4.6 or higher.

https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples#supported-platforms
