### ISSUE TITLE
Reduce Critical Path JIT Time for csc.exe on .NET Core

### ISSUE THREAD

**Issue by brianrob** [dotnet/roslyn#10691]
Today on .NET Core, Roslyn is compiled with Ready2Run, which doesn't yet pre-compile generics.  One thing that can be done to help alleviate JIT time for RC2 is to enable Multi-Core JIT.  Multi-Core JIT records a profile of methods that are JIT compiled, writes them out to disk, and then on subsequent runs, JIT compiles those methods in the background (hopefully) before they're needed by the program.

In my experiments, enabling Multi-Core JIT in csccore\csc.exe dropped critical path JIT time by 32%.

**Comment by jaredpar** [comment]
@brianrob how would we do this?

**Comment by brianrob** [comment]
Right after you set the default AssemblyLoadContext, call these two APIs:

`AssemblyLoadContext.Default.SetProfileOptimizationRoot(<path to writable directory for profile>);
AssemblyLoadContext.Default.StartProfileOptimization(<profile name that you make up>);`

The optimization root needs to be a writable location.  The profile name represents the actual file that will be written (and persisted to the next run of the app).

Once you do this, the first run will produce the profile and all subsequent runs will aggressively JIT anything that's in the profile as well as re-write the profile to make sure that it's up-to-date.

**Comment by jaredpar** [comment]
@brianrob if this involves `AssemblyLoadContext` then we need to sit down and have a talk.  The lack of documentation in this area is a becoming a **fundamental** blocking issue for Roslyn.  I can't see us taking a further dependency here until we understand better the implications and design of this feature.

**Comment by brianrob** [comment]
@jaredpar, I'm happy to chat about this.  Perhaps we can meet with @gkhanna79 at the same time and make sure that all of your questions are answered?

**Comment by jaredpar** [comment]
@brianrob sure, I'll set something up.

**Comment by agocke** [comment]
Fixed by #23173
