### ISSUE TITLE
Easy constructor for properties binding

### ISSUE THREAD

**Issue by eklam** [dotnet/roslyn#107]
Proposition
-----------

An easy way to implement default constructor that only bind the parameter of class properties

Situation
---------

When you have a class/struct and want to enforce the initialization through constructor we have to do something like this:

```csharp
public class Access
{
    public string Name { get; set; }
    public bool IsActive { get; set; }
    
    
    public Access( // It's obvious that it's the constructos for Access class, is's inside it!
        string name, // Have to duplicate the name and type of the property
        bool isActive) // Again the name and type of the property
    {
        this.Name = name; // Obvious associations
        this.IsActive = isActive; // Obvious associations
    }
}
```

Why not write something like:

```csharp
public class Access
{
    public string Name { get; set; }
    public bool IsActive { get; set; }
    
    public(Name, IsActive = true)
}
```

We could even use DataContracts and remove the necessity to validate the parameters, it would be very helpful for creating small helper classes.

```csharp
public class Access
{
    public string Name { get; set; }
    public bool IsActive { get; set; }
    
    public([NotNull]Name, IsActive = true)
}
```

**Comment by svick** [comment]
This sounds very much like [primary constructors](http://odetocode.com/blogs/scott/archive/2014/08/14/c-6-0-features-part-ii-primary-constructors.aspx), a feature proposed and then [dropped](https://roslyn.codeplex.com/discussions/568820) from C# 6, mostly due to time constraints.

I believe it's quite likely that some form of this will make it into C# 7.

**Comment by gafter** [comment]
This is specified in #206.
