### ISSUE TITLE
Rename refactoring does not work in Delegate properties with initializers.

### ISSUE THREAD

**Issue by ghord** [dotnet/roslyn#10714]
**Version Used**: Visual Studio 2015 Update 2

**Steps to Reproduce**:
1. Paste following code:

``` C#
     class Program
     {
        public Action<object> Test { get; set; } = test =>
        {
            var foo = 1;
            foo = 3;
        };

        static void Main(string[] args)
        {
        }
    }
```
1. Try to rename `foo` identifier

**Expected Behavior**:

Both uses of foo get renamed

**Actual Behavior**:

Only the foo directly at the caret position gets renamed.

**Comment by DustinCampbell** [comment]
Highlight references, find all references and rename are all AWOL on locals defined in a property initializer.
