### ISSUE TITLE
Create NuGet package for CPC/Consumption

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#10719]
Per discussion yesterday, we should go ahead and create a nuget package for these dependencies of the perf tests (and remove dependency on file shares in the perf scripts).

**Comment by KevinH-MS** [comment]
@basoundr I'll leave it to you to try to get your changes to CPC pushed back into the main tree.  Even if that's not going to happen in the near term, we should create a nuget with our current privates.

**Comment by KevinH-MS** [comment]
@jaredpar is there a specific license link we should use for this (is there precedent)?  There is the one we use for https://www.nuget.org/packages/Microsoft.CodeAnalysis.Test.Resources.Proprietary/1.1.0-beta1-20150824-02, but this is slightly different.

**Comment by KevinH-MS** [comment]
Note:  This package should be (and probably forever remain) "prerelease".

**Comment by KevinH-MS** [comment]
As part of this item, we allso need to move the CPC output to the temp folder inside the PerfTests (or some other suitable location).

**Comment by mavasani** [comment]
I am going to close this out as this looks pretty stale. Please re-activate if otherwise.
