### ISSUE TITLE
Redundant cast suggests removing boxing cast when it shouldn't

### ISSUE THREAD

**Issue by WreckedAvent** [dotnet/roslyn#10711]
**Version Used**: 
VS "15" preview

**Steps to Reproduce**:
1. Enter in this code

``` C#
public abstract class Result<T>
{
    internal Result() { }
}

public sealed class Success<T> : Result<T>
{
    public T Result { get; set; }
}

public sealed class Failure<T> : Result<T>
{
    public string Message { get; set; }
}

public static class ResultExtensions
{
    public static string DescribeResult<T>(this Result<T> res) => res match (
        case Success<T> succ : (Object)succ.Result match (
            case string s : s
            case int i : i.ToString("N")
            case var x : x.ToString()
        )

        case Failure<T> f : $"Error: {f.Message}"
    );
}
```
1. Observe suggestion to "remove redundant cast" of `(Object)succ.Result`

**Expected Behavior**:

No warnings or suggestions. The code is written as it needs to be to compile, there are no redundant casts.

**Actual Behavior**:

A warning to remove a "redundant" cast.

(per suggestion of @DustinCampbell in #10220)

**Comment by markhurd** [comment]
(Transferring my comment over too.)
I would hope a future version of the `match case` feature wouldn't need the `(object)` cast and would know the `case` matched at JIT compile of a concrete `T`.

**Comment by alrz** [comment]
@markhurd Why would you want to hijack generics that way? If you are casting a generic type to object, there are chances that your code is not generic at all, search for code smells.

**Comment by markhurd** [comment]
@alrz We may not normally code this way, but this is just simple code exercising the compiler or the IDE.

**Comment by gafter** [comment]
The cast *should* be redundant. If it isn't, then that is a bug.

**Comment by gafter** [comment]
@WreckedAvent What branch were you testing on?

**Comment by WreckedAvent** [comment]
This was just the "15" preview, so whatever version was present in that as of three or so weeks ago.

**Comment by WreckedAvent** [comment]
@alrz I'd absolutely love to not write the code with generics, as C#'s generic inference isn't too amazing. There doesn't appear to be any other way to get the type safety of having a `Result` of a certain type while being to also pattern match against *all* `Result`s

**Comment by breyed** [comment]
The bug occurs whether or not boxing takes place. It seems like a bug or missing feature that the cast is required in the first place.

```
class B { }
class D : B { }

void F<T>(T value) where T : B
{
	if ((B)value is D d) { }
}

```

**Comment by alrz** [comment]
@breyed [it's indeed redundant in latest bits](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWACg9CiAWciwgJnwGF8BvS/Hy7W/ADEAPABUAfAApR+AG4QANgFc4ASnwB3ABaI4+GSHwAhSlwoBIAJYAzfJPnK9lqPgAi+FOo74AvpT+MPLyBwQF8LEacvuFu+IaR3gFAA===).

**Comment by gafter** [comment]
The cast is no longer required in C# 7.1. However, we do not support the `match` expression yet.
