### ISSUE TITLE
WorkCoordinatorRegistrationService_Reanalyze telemetry should include meaningful "Analyzer" value

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#10735]
Currently, in SolutionCrawlerLogger.cs:
```
        public static void LogReanalyze(int correlationId, IIncrementalAnalyzer analyzer, IEnumerable<DocumentId> documentIds, bool highPriority)
        {
            Logger.Log(FunctionId.WorkCoordinatorRegistrationService_Reanalyze, KeyValueLogMessage.Create(m =>
            {
                m[Id] = correlationId;
                m[Analyzer] = analyzer.ToString();
                m[DocumentCount] = documentIds == null ? 0 : documentIds.Count();
                m[HighPriority] = highPriority;
            }));
        }
```

The value of ```analyzer.ToString()``` is always "```IncrementalAnalyzerDelegatee```".  This is pretty much a waste of electrons.  Ideally, it would be good to show the specific analyzers that were running, but alternatively, it would be more helpful to at least show a total count of the number of analyzers being invoked.  I couldn't see any easy way to do this though...

**Comment by KevinH-MS** [comment]
FYI @heejaechang ... not sure if you have any thoughts on this.

**Comment by heejaechang** [comment]
that means it is DiagnosticEngine. here analyzer is not DiagnosticAnalyzer. it is SolutionCrawler Incremental Analyzer. DiagnosticEngine is implemented as SolutionCrawler's Incremental Analyzer.

http://index/#Microsoft.CodeAnalysis.Features/Diagnostics/DiagnosticAnalyzerService_IncrementalAnalyzer.cs,60

we could rename it if name is confusing.

...

by the way, if other incremental analyzer is asked to re-analyze (currently, I believe except diagnostic engine, no other incremental analyzer ever have need to re-analyze), it will log its name such as TodoCommentIncrementalAnalyzer and etc.

http://index/#Microsoft.CodeAnalysis.Features/SolutionCrawler/IIncrementalAnalyzer.cs,19d22ac10d0ea1f3,references

**Comment by KevinH-MS** [comment]
I see.  Based on your offline explanation, I don't see a better solution.  I guess something along the lines of "SolutionChangeObserver" might be less confusing (as "Analyzer" most immediately associated with "Roslyn Diagnostic Analyzers"), but the ship has probably sailed on changing the names at this point.
