### ISSUE TITLE
Failing integration tests: CSharpErrorLog.xml CSharpFixAllOccurrences.xml are blocking integration from master to future

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#10730]
Note, the tests are failing on two independent PRs: 
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/645/
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p2/367/

**Comment by mavasani** [comment]
@mattscheffer confirmed that these integration tests were broken only for small duration. They are running fine now: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/652/console
