### ISSUE TITLE
The C# and VB compiler command-line switches should be added to our docs

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#1074]

**Comment by billchi-ms** [comment]
We have these topics:
 https://msdn.microsoft.com/en-us/library/6ds95cz0.aspx 
 https://msdn.microsoft.com/en-us/library/6s2x2bzy.aspx 
 https://msdn.microsoft.com/en-us/library/w95cx9k1.aspx 
 https://msdn.microsoft.com/en-us/library/c03639ab.aspx 

If there are specific issues you're aware of, please identify them.

**Comment by gafter** [comment]
These documents do not correspond to the Roslyn command-line, nor are they kept up-to-date with the Roslyn implementation as it changes.

**Comment by billchi-ms** [comment]
If no one opened a bug or communicated changes in the past, then the topics may be out of date.  It is not a universal truth that they are not kept up to date if by chance they are not up to date at this time.  If there are discrepancies, please attach the specs for both.  When I confirmed changes for vs2015, there were no cmd ln switches mentioned.  If you're trying to say that you want markdown files in the Roslyn sources, then we can discuss that as a feature or wait until we can convert topics and pull from git to MSDN.

**Comment by gafter** [comment]
@billchi-ms This issue is filed here for Roslyn, the open-source project. VS2015, the Microsoft product that plans to include Roslyn, is a separate thing tracked separately.
