### ISSUE TITLE
Formatter indentation broken for tabs

### ISSUE THREAD

**Issue by michalhosala** [dotnet/roslyn#10742]
**Version Used**: SHA 1569c002a5998ebeb3b3a31182946583be773c6a

**Steps to Reproduce**:

1. Create VB console application, call it VbTest.sln,
2. Replace code in Module1.vb with following code (**Use spaces for indentation**):

    ```
    Public Class SomeClass
        Public Const SomeConst1 = 1    ' Comment1
        Public Const SomeConst2 = 2    ' Comment2
    End Class
    ```

3. Now open Samples.sln which is part of Roslyn,
4. Navigate to FormatSolutionCS project and add following line right after workspace initialization:

    ```
    workspace.Options = workspace.Options.WithChangedOption(FormattingOptions.UseTabs, LanguageNames.VisualBasic, true);
    ```

5. Also modify the line below to open VbTest.sln instead of default one,
6. Run the formatter and check the formatted Module1.vb file:
    * `SomeConst1` is properly indented by 1 tab,
    * `SomeConst2` **is indented using 4 spaces and that is a bug**.

**Expected Behavior**:
When `UseTabs` option is true then all lines should be indented using tabs.

**Actual Behavior**:
When `UseTabs` option is true then some lines are not indented using tabs.

**Remarks**:
* If you delete `' Comment1` and re-run the formatting then the indentation is as expected.
* Problem is with formatting of complex trivias in VB.NET only, pull request to address this issue is #10748

**Comment by Pilchie** [comment]
Fixed by #10748
