### ISSUE TITLE
With csproj->xproj references, intellisense and "go to" in the csproj doesn't work with xproj types

### ISSUE THREAD

**Issue by spadapet** [dotnet/roslyn#10753]
**Version Used**:
VS 2015 Update 2 (14.0.25123.00) with the latest dotnet tooling and patches for csproj->xproj support (ask @spadapet if you need links)

**Steps to Reproduce**:

1. Open a solution that has an xproj project, and a csproj/project.json project that references the xproj.
2. Here is a zipped solution, so use this: [refs.zip](https://github.com/dotnet/roslyn/files/232419/refs.zip)
3. Open Program.cs in the MainExe project (csproj).

**Expected Behavior**:
The usage of CoreLib2.Math.Add shouldn't have an error, it should show up in intellisense, and "go to code" on Add should go to the Math2.cs source file.

**Actual Behavior**:
CoreLib2.Math.Add has an error, intellisense doesn't show that function, "go to code" does nothing.
After a full build, then those work, except that "go to code" goes to the built DLL for CoreLib2 rather than the source file. It should go to the source file.

**Comment by jasonmalinowski** [comment]
This is happening because there's a mismatch between the build output location from the command line build and where the xproj project system says the output is. The xproj projects think they are being written to

     artifacts\CoreLib2\bin\Debug\net45\win\CoreLib2.dll

but the reference on disk is:

    artifacts\CoreLib2\bin\Debug\net45\CoreLib2.dll

Note the difference of the `win` RID.

**Comment by jasonmalinowski** [comment]
This is an issue on the xproj project system side of things; we're now tracking this with internal bug 217081.
