### ISSUE TITLE
Block __arglist in local functions

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#10765]
Currently, `__arglist` is allowed in the parameter list of local functions, but it is not allowed in the body. This means that the only legal use of `__arglist` in a local function is to declare a method which takes but never uses the `__arglist` parameter.

We should disallow `__arglist` entirely, both from the parameter list and the method body.

**Comment by jcouv** [comment]
Tracked by VSO https://devdiv.visualstudio.com/DevDiv/_workitems/edit/369813

**Comment by jcouv** [comment]
Moving out as this is a corner case that won't meet the current shiproom bar.

**Comment by TessenR** [comment]
@jcouv Is it going to be a breaking change later? Right now I can compile a local function with an __arglist parameter.

**Comment by jcouv** [comment]
@agocke Please confirm if this is currently an error or not. If it's not an error, we'll try to bring it back to RTM.

**Comment by agocke** [comment]
@jcouv It's currently an error to use `__arglist` within a local function.

@TessenR It would technically be a breaking change to do this later, but since it would be impossible to refer to the arglist parameter (meaning the parameter is useless) we may be willing to take the breaking change later.

**Comment by jcouv** [comment]
Ping @jaredpar
