### ISSUE TITLE
[Test Failure] Packages need to be updated in prtest/win/dbg/unit64 on PR #10760

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#10761]
PR: [#10760](https://github.com/dotnet/roslyn/pull/10760) *fixed live diagnostic argId leak* by @heejaechang
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/6413/

**Issue 1: Packages need to be updated**
A new package was introduced, but the Azure store of the packages was not updated. Please follow: https://github.com/dotnet/roslyn/blob/master/docs/infrastructure/Updating%20NuGet%20ZIP%20file.

error : The package Microsoft.VisualStudio.Composition with version 14.0.50715-pre could not be found in C:\Users\dotnet-bot\.nuget\packages. Run a NuGet package restore to download the package. [D:\j\workspace\roslyn_prtest---45fcf4bc\src\EditorFeatures\Test\EditorServicesTest.csproj]

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure is this a known issue?

**Comment by jasonmalinowski** [comment]
Not known. The instructions are also really bad, which I'm immediately fixing right now.

**Comment by jasonmalinowski** [comment]
Oops, looks like I never closed this.
