### ISSUE TITLE
[Test Failure] No identified problem in prtest/win/vsi/p0 on PR #10747

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#10763]
PR: [#10747](https://github.com/dotnet/roslyn/pull/10747) *Large cleanup of FixAllContext and subclasses.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/629/

**Issue 1: No identified problem**
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.

11:08:46  ToolsetPackages (>= 1.0.0) -> Roslyn.Build.Util (>= 0.9.4-portable) -> Microsoft.Build.Framework (>= 0.1.0-preview-00005)
11:08:46 Restoring packages: Samples
11:08:52 Restoring packages: Roslyn (this may take some time)
11:09:10 Restoring packages: Closed Roslyn.sln
11:09:39 Unrecognized argument: -dependencies:true
11:09:39 
11:09:39 
11:09:39 Usage: Test.exe [build] [clean] [deployextensions] [trackfileaccess] [officialbuild] [realsignbuild] [delaysignbuild] [cibuild] [unit] [eta] [vs] [vspartitioncount] [vsrunpartition] [release] [dogfood] [parallel] [csharp] [vb] [compilers] [services] [editor] [diagnostic] [interactive] [expressionevaluator] [ee] [samples] [setupproj] [devdivinsertionfiles] [dump] [crashdump] [coverage] [profiler] [lowpriority] [x64] [filelog] [verifypowershell]

**Comment by jasonmalinowski** [comment]
@tmat, this was rolled back?

**Comment by tmat** [comment]
@jasonmalinowski Yes.
