### ISSUE TITLE
[Test Failure] No identified problem in prtest/lin/dbg/unit32 on PR #10758

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#10767]
PR: [#10758](https://github.com/dotnet/roslyn/pull/10758) *turn off csharp full solution analysis.* by @heejaechang
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/6401/

**Issue 1: No identified problem**
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.

it looks like msbuild.exe doesn't exist
...

13:23:33 Cannot open assembly '/home/dotnet-bot/.nuget/packages/Microsoft.Build.Mono.Debug/14.1.0-prerelease/lib/MSBuild.exe': No such file or directory.
13:23:33 Cannot open assembly '/home/dotnet-bot/.nuget/packages/Microsoft.Build.Mono.Debug/14.1.0-prerelease/lib/MSBuild.exe': No such file or directory.
13:23:33 cp: cannot stat ‘Binaries/Debug/csccore/*’: No such file or directory
13:23:33 cp: cannot stat ‘Binaries/Debug/vbccore/*’: No such file or directory
13:23:33 make: *** [bootstrap] Error 1
13:23:33 Build retry 5
13:23:33 Build failed
13:23:33 Build step 'Execute shell' marked build as failure
13:23:33 [xUnit] [INFO] - Starting to record.
13:23:33 [xUnit] [INFO] - Processing xUnit.Net-v2 (default)
13:23:33 [xUnit] [INFO] - [xUnit.Net-v2 (default)] - No test report file(s) were found with the pattern '**/xUnitResults/*.xml' relative to '/mnt/j/workspace/roslyn_prtest_lin_dbg_unit32' for the testing framework 'xUnit.Net-v2 (default)'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'xUnit.Net-v2 (default)'?
13:23:33 [xUnit] [ERROR] - No test reports found for the metric 'xUnit.Net' with the resolved pattern '**/xUnitResults/*.xml'. Configuration error?.
13:23:33 [xUnit] [INFO] - Failing BUILD.
13:23:33 [xUnit] [INFO] - There are errors when processing test results.
13:23:33 [xUnit] [INFO] - Skipping tests recording.
13:23:33 [xUnit] [INFO] - Stop build.
13:23:33 Skipped archiving because build is not successful
13:23:33 [BFA] Scanning build for known causes...
13:23:34 [BFA] No failure causes found
13:23:34 [BFA] Done. 0s
13:23:34 Setting status of c39449059df8b9c156c548c03f4d392858ca3091 to FAILURE with url http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/6401/ and message: 'Build finished. No test results found.'
13:23:34 Using context: prtest/lin/dbg/unit32
13:23:34 [WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done

**Comment by jcouv** [comment]
Seems like the same issue @VSadov is running into here https://ci.dot.net/job/dotnet_roslyn/job/dev15-rc/job/windows_debug_unit32_prtest/5/ (for PR https://github.com/dotnet/roslyn/pull/14418)
