### ISSUE TITLE
.NET Core csc output non-ASCII characters correctly in the Console output

### ISSUE THREAD

**Issue by eerhardt** [dotnet/roslyn#10785]
This issue is spawned from: https://github.com/dotnet/cli/issues/2486, which is an RC2 partner blocking bug (VS Code).

**Version Used**: 1.3.0.60410

**Steps to Reproduce**:
1. I have an .rsp file with the following input file:

```
"C:\Users\eerhardt\Tést\Program.cs"
```

And that Program.cs file contains a build error.
1. Compile it using the .NET Core csc
   - C:\cli\artifacts\win10-x64\stage1\dotnet.exe C:\cli\artifacts\win10-x64\stage1\sdk\1.0.0-rc2-002476\csc.dll @C:\Temp\dotnet-compile-csc.rsp

**OLD REPRO:**
    cd /d %USERPROFILE%
    mkdir Tést
    cd Tést
    dotnet new
    dotnet restore
    dotnet build

**Expected Behavior**:

The strings written to the console should contain the correct path:

```
C:\Users\eerhardt\Tést\Program.cs(9,17): error CS1001: Identifier expected
C:\Users\eerhardt\Tést\Program.cs(9,17): error CS1002: ; expected
```

**Actual Behavior**:

Incorrect strings are written to the console:

```
C:\Users\eerhardt\T├⌐st\Program.cs(9,17): error CS1001: Identifier expected
C:\Users\eerhardt\T├⌐st\Program.cs(9,17): error CS1002: ; expected
```

**OLD behavior:**
On my machine I'm seeing a crash in the csc process:

```
Unhandled Exception: System.IO.FileNotFoundException: C:\cli\artifacts\win10-x64\stage1\sdk\1.0.0-rc2-002476\Microsoft.CodeAnalysis.dll
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Roslyn.Utilities.PortableShim.Misc.GetFileVersion(String path)
   at Microsoft.CodeAnalysis.CommonCompiler.GetAssemblyFileVersion()
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.PrintLogo(TextWriter consoleOutput)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
```

I can pare the "dotnet build" call down to starting the following process:

```
C:\Users\eerhardt\Tést>C:\cli\artifacts\win10-x64\stage1\dotnet.exe C:\cli\artifacts\win10-x64\stage1\sdk\1.0.0-rc2-002476\csc.dll -noconfig @C:\Users\eerhardt\Tést\obj\Debug\netcoreapp1.0\dotnet-compile-csc.rsp
```

Looking through the callstack, it is trying to write the logo, so I shut that off:

```
C:\Users\eerhardt\Tést>C:\cli\artifacts\win10-x64\stage1\dotnet.exe C:\cli\artifacts\win10-x64\stage1\sdk\1.0.0-rc2-002476\csc.dll -nologo -noconfig @C:\Users\eerhardt\Tést\obj\Debug\netcoreapp1.0\dotnet-compile-csc.rsp
```

and now I get:

```
error CS2011: Error opening response file 'C:\Users\eerhardt\T├â┬⌐st\obj\Debug\netcoreapp1.0\dotnet-compile-csc.rsp'
warning CS2008: No source files specified.
error CS1562: Outputs without source must have the /out option specified
```
# Solution

The underlying problem is a difference in encoding handling in .NET Core vs. .NET Framework. (See the ".NET Core Notes" section in https://msdn.microsoft.com/en-us/library/system.diagnostics.process(v=vs.110).aspx) .NET Core uses a minimal set of code pages, and falls back to Utf8 when it can't find the right code page. In order to get the same behavior as the .NET Framework, console apps have to add the correct code pages into their process.

One possible way of doing this is:

``` C#
using System.Text;
...
    Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
```

~~In order to fix https://github.com/dotnet/cli/issues/2486, we need to make that same call in the CLI's Main method.  But to fully fix the scenario, we need Roslyn to also add this call in the .NET Core version of csc.exe's Main method.~~

/cc @Petermarcu @jaredpar 
/bcc @tarekgh - who provided me guidance on the .NET Core behavior difference

**Comment by agocke** [comment]
@eerhardt Your post seems to contradict itself: you mention that Unicode characters are the issue, but you mention that .NET Core falls back to UTF-8 (Unicode) when it can't find a code page.

It seems like you're asking for support for sets of *non-Unicode* codepages, no?

**Comment by agocke** [comment]
Quoting from @eerhardt's offline thread about this:

> To try to isolate the problem, I made my own Console App that just writes the args out to a file:
> 
>         public static void Main(string[] args)
>         {
>             File.WriteAllLines("output.txt", args);
>         }
> 
> And when I invoke that console app through dotnet.exe:
> 
> C:\cli\artifacts\win10-x64\stage1\dotnet.exe exec --additionalprobingpath C:\Users\eerhardt\.nuget\packages C:\DotNetTest\ConsoleApp2\bin\Debug\netcoreapp1.0\ConsoleApp2.dll Tést
> 
> I get the following in my output.txt file:
> 
> TÃ©st
> 
> 
> So I think this is a host problem not handling the characters correctly, and passing through an incorrect string to the managed app.
>

**Comment by eerhardt** [comment]
@agocke's comment is correct.  The blocking issue I ran into is actually a dotnet.exe corehost issue not passing in the command line parameters correctly to the managed code.

Re-naming and re-purposing (and lowering the priority) this issue for Roslyn to handle non-ASCII characters in their Console output correctly.

To quote from https://github.com/dotnet/corefx/issues/7935#issuecomment-212691693

> Also the control of the console encoding can be done either from the system settings or from the console process itself (through Console.InputEncoding and Console.OutputEncoding). 

To repro:

I have an .rsp file with the following input file:

```
"C:\Users\eerhardt\Tést\Program.cs"
```

And that Program.cs file contains a build error.

I compile it using the desktop .NET Framework's csc.exe and I get the following output written to the console:

```
C:\DotNetTest\ConsoleApp2>csc.exe @C:\Temp\dotnet-compile-csc.rsp
C:\Users\eerhardt\Tést\Program.cs(9,17): error CS1001: Identifier expected
C:\Users\eerhardt\Tést\Program.cs(9,17): error CS1002: ; expected
```

But when I compile it using the .NET Core's csc, I don't get `Tést` written correctly:

```
C:\DotNetTest\ConsoleApp2>C:\cli\artifacts\win10-x64\stage1\dotnet.exe C:\cli\artifacts\win10-x64\stage1\sdk\1.0.0-rc2-002476\csc.dll @C:\Temp\dotnet-compile-csc.rsp
C:\Users\eerhardt\T├⌐st\Program.cs(9,17): error CS1001: Identifier expected
C:\Users\eerhardt\T├⌐st\Program.cs(9,17): error CS1002: ; expected
```

**Comment by agocke** [comment]
I think the problem here is that CscCore doesn't attempt to load the system codepages or use them for printing to the console.

It's probably reasonable to load them for printing to the console since that's inherently non-portable and there's no Windows CMD that supports Unicode, but I want to be careful not to allow using the default system codepage for handling file paths or content in CscCore.

**Comment by tarekgh** [comment]
> there's no Windows CMD that supports Unicode

This is not true, anyone can set the console codepage to UTF8 or configure the system to use UTF8. but I agree by default we don't get Unicode.

**Comment by agocke** [comment]
@tarekgh Right, by that I meant there's no shipped Windows config where CMD uses UTF-8 by default.

**Comment by gafter** [comment]
@agocke I'm not sure what compiler-team request remains in this issue. Can you please help me identify a specific requested action?

**Comment by eerhardt** [comment]
The specific requested action is to add the following line at the beginning of the "Main" method for csc.exe when it is compiled for .NET Core:

```C#
// by default, .NET Core doesn't have all code pages needed for Console apps.
// see the .NET Core Notes in https://msdn.microsoft.com/en-us/library/system.diagnostics.process(v=vs.110).aspx
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
```

We do the same thing in the CLI:

https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/Program.cs#L188-L193

This allows the csc command to output the correct strings to the console.

See this comment (https://github.com/dotnet/roslyn/issues/10785#issuecomment-213528878) for the repro steps that illustrate why this is needed.

**Comment by agocke** [comment]
@eerhardt That's not necessarily sufficient. That allows for more encodings to be used, but doesn't choose an encoding. We could make the machine encoding as made available by the CodePagesEncodingProvider the default encoding, but that is inherently non-portable.

Was this decision explicitly made by dotnet-CLI? Can you point me to the discussion w/ justification?

**Comment by eerhardt** [comment]
> That allows for more encodings to be used, but doesn't choose an encoding.

The encoding is chosen by the console that the user is running.  For example, it could be CMD on Windows, Terminal on Mac.  Etc.  Even on CMD in Windows, the user can change the encoding as they would like.

> Can you point me to the discussion w/ justification?

Here is the PR that brought the change into the CLI:  https://github.com/dotnet/cli/pull/2680.

Also see https://github.com/dotnet/corefx/issues/7935#issuecomment-212678663

Specifically this part:

```
because .NET core by default doesn't support all encodings we used to support in the desktop
(https://msdn.microsoft.com/en-us/library/system.text.encodingprovider(v=vs.110).aspx), the encoding
used by the console session is not one of the default supported encoding and then we'll fallback to
use UTF8 encoding which produce different output than the original console encoding.

To make this work, will need to opt-in of using the full encoding. you do that by referencing
System.Text.Encoding.CodePages in your project.json and then call
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance); in your initialization code and
everything will fully work.
```



If you have any further questions, please let @tarekgh know.

**Comment by agocke** [comment]
@eerhardt Thanks!

**Comment by jaredpar** [comment]
Bringing up the pertinent code:

``` csharp
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
```

This is already being done in the compiler in [GetFallbackEncoding](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/EncodedStringText.cs#L29).  Is this sufficient or is it being done too late in the process to help out here?

**Comment by agocke** [comment]
@jaredpar I suspect that's too late, but that was my first thought as well.

**Comment by jaredpar** [comment]
That code still needs to exist in `GetFallbackEncoding`.  But we could also just duplicate it in our CoreClr main methods.  I assume it's an idempotent method.

**Comment by agocke** [comment]
@jaredpar Yup. As soon as we touch `Console` the static constructors eventually flow through to https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/Common/src/System/Text/EncodingHelper.cs#L27

As long as we add the call early enough in CscCore we should get there first.

**Comment by nguerrera** [comment]
@jaredpar @agocke This is also a World Ready tenet blocker for .NET CLI. See #15888. It needs to be fixed in VS 2017 timeframe and before roslyn satellites land in CLI. In the localized case, it can make diagnostics unintelligible.

**Comment by jaredpar** [comment]
This is fixed now in the rc3 branch.

**Comment by tarekgh** [comment]
@jaredpar if Roslyn using the encoding only for for having the console out the text with the right encoding, then you may not register the encoding providers at all after dotnet/corefx#14496 fix. but if Roslyn need the encoding for other purposes then registering the encoding will be required.

**Comment by nguerrera** [comment]
@tarekgh What version of the core clr runtime / shared framework will have that fix?

**Comment by tarekgh** [comment]
it should be in one of the latest published packages https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.App but these are still Beta packages and not RTM.
