### ISSUE TITLE
[Test Failure] BasicWinForms failed in prtest/win/vsi/p1 on PR #887

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#10788]
PR: [#887](https://github.com/dotnet/roslyn-internal/pull/887) *Remove more -dependencies* by @tmat
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p1/386/

**Comment by jasonmalinowski** [comment]
Results are no longer available to look at.
