### ISSUE TITLE
[Test Failure] BasicFormatting failed in prtest/win/vsi/p0 on PR #887

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#10787]
PR: [#887](https://github.com/dotnet/roslyn-internal/pull/887) *Remove more -dependencies* by @tmat
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p0/370/

**Comment by davkean** [comment]
Looks similar to: https://github.com/dotnet/roslyn/issues/10781

**Comment by jasonmalinowski** [comment]
Results are no longer available to look at.
