### ISSUE TITLE
CSProj ClassLibrary Reference to xProj Class Library Not working

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#10786]
**Steps to Reproduce:**

Create a windows class library 
Add a project.json file to the same  
Add below code to the same
```<{
  "frameworks": {
    "net462": { }
  },
  "runtimes": {
    "win": { }
  }
} 
```
Make sure you go and change the properties to target .net framework 4.6.2
Build it 

Now create a Core Class Library , by default it points to .netstandard1.5
 Project.json will have below information 

```<{
 "version": "1.0.0.0",

"dependencies": {
 "NETStandard.Library": "1.5.0-rc2-24008"
 },

"frameworks": {
 "netstandard1.5": {}
 }
 }
```

Now reference core class library from class library.

**Expected Behavior:**
You are able to reference, build and should be able to call the ref api's 

**Actual Behavior:**
It adds the references fine, builds successfully 
when you try to call the api in the reference , it can't seems to resolve it 

![ref](https://cloud.githubusercontent.com/assets/12449387/14753664/9b0ac730-088b-11e6-912b-52ef2ed129dc.JPG)

**Comment by Pilchie** [comment]
Is this the same as #10753?  @jinujoseph what happens if you build?

**Comment by jinujoseph** [comment]
It is not , 10753 refers to an issue where csproj(console) refers to xproj(classLibrary) which has a dependency on another xproj(class Library) intellisense fails without a full build.

This scenario is csproj(classLibrary) referring to xproj(classLibrary) fails with clean full build too.

**Comment by jasonmalinowski** [comment]
#10753's root cause could mean enough is broken here to accurately diagnose this one. I'm going to hold off on this one for a day or two until we have some new bits for that one.

**Comment by Pilchie** [comment]
Given the convergence on csproj, we're not going to fix this.
