### ISSUE TITLE
PCL projects targeting netstandard issue an error about embedded resources

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#10792]
Severity    Code    Description Project File    Line    Suppression State
Error       Build action 'EmbeddedResource' is not supported by one or more of the project's targets.   CodeAnalysis    F:\roslyn-internal\Open\src\Compilers\Core\Portable\Resources\default.win32manifest 0

**Comment by jinujoseph** [comment]
@Pilchie , I can still repro this ...

**Repro steps **
Create a PCL targetting to .netstandard1.1 
Add a resource file to the same 
Builds successfully and every thing works good
Now change the target to point to .netstandard1.2 
Rebuild and you get the below error 

![mu7](https://cloud.githubusercontent.com/assets/12449387/15128553/4875f72e-15f1-11e6-9789-3cdfb2d730a7.JPG)

**Comment by rchande** [comment]
Looks like something is happening after retarget that's messing up DTAR/type checks. Trying to figure it out but I don't think this will block Roslyn from moving to netstandard.

**Comment by rchande** [comment]
@rchande Is this fixed now?

**Comment by rchande** [comment]
This appears to be fixed.
