### ISSUE TITLE
PCL projects targeting netstandard issue an error about unsafe code

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#10791]
Severity    Code    Description Project File    Line    Suppression State
Error       'Allow unsafe code' is not supported by one or more of the project's targets.   CodeAnalysis    F:\roslyn-internal\Open\src\Compilers\Core\Portable\CodeAnalysis.csproj 0

**Comment by jinujoseph** [comment]
Still repros 

![image](https://cloud.githubusercontent.com/assets/12449387/15128615/b8fd4c40-15f1-11e6-834e-b66a9f60888a.png)


Note that 

This fails only if you change the target , once you change the target this error appears ..

WorkAround 

Uncheck the "Allow unsafe code" , build and then re-add the check.

**Comment by Pilchie** [comment]
@rchande: The current state is that this fails immediate after retargeting, but works on project open, right?

**Comment by rchande** [comment]
@Pilchie: That's correct.

**Comment by rchande** [comment]
@rchande Is this fixed now?

**Comment by Pilchie** [comment]
I don't think we'll fix this anymore.
