### ISSUE TITLE
ObsoleteAttribute is not evaluated properly on method override

### ISSUE THREAD

**Issue by voloda** [dotnet/roslyn#108]
On the code sample below the method ```PasswordDeriveBytes.GetBytes()``` is obsolete. 

Apparently compiler does not display the expected warning. I tested this via https://dotnetfiddle.net/chx7cX.

Interrestingly I do have same issue on VS2013

```C#
using System;
using System.Security.Cryptography;

namespace IoCWithoutUnity
{
    public class Program
    {
        public static void Main(string[] args)
        {
            PasswordDeriveBytes password = new PasswordDeriveBytes(
                                                            "aa",
                                                            new byte[]{0x0},
                                                            "asdasd",
                                                            2);

            byte[] keyBytes = password.GetBytes(64 / 8);
        }
    }
}
```

**Comment by gafter** [comment]
According to the language specification, the invocation binds to the method on the base class, which is not marked obsolete. So the compiler is correct not to complain.

**Comment by gafter** [comment]
@VladimirReshetnikov Can you please "Verify" this resolution?
