### ISSUE TITLE
GetRelatedDocumentsWithChanges is inaccessible

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#10809]
**Version Used**: 
Visual Studio Update 2, Roslyn tag 1.2.1
**Steps to Reproduce**:
1. Load Samples.sln from Roslyn source
2. Fix all the missing NuGet Packages (separate issue)
3. in PasteHandler.cs and ViewCreationListener.cs GetRelatedDocumentsWithChanges is inaccessible due to its protection level

**Expected Behavior**:
No error
**Actual Behavior**:

```
Error   CS0122  'TextExtensions.GetRelatedDocumentsWithChanges(SourceText)' is inaccessible due to its protection level CopyPasteWithUsing  ..\repos\roslyn-version-1.2.1\src\Samples\CSharp\CopyPasteWithUsing\PasteHandler.cs 58  Active
Error   CS0122  'TextExtensions.GetRelatedDocumentsWithChanges(SourceText)' is inaccessible due to its protection level CopyPasteWithUsing  ..\repos\roslyn-version-1.2.1\src\Samples\CSharp\CopyPasteWithUsing\ViewCreationListener.cs 160 Active
```

**Comment by Pilchie** [comment]
It looks like we have two copies of that method - one in Workspaces and one in EditorFeatures.Text, and it's the latter one that is public.

http://source.roslyn.io/Microsoft.CodeAnalysis.EditorFeatures.Text/R/5faa3f57c5b4e137.html

Do you have a reference to the EditorFeatures.Text nuget package and `using Microsoft.CodeAnalysis.Text;`?

**Comment by paul1956** [comment]
I didn't have the NuGet Package EditorFeatures.Text and I wasn't recommended to install it. Adding it fixes the issues. None of this is my code, it is the Roslyn Sample.sln from Update 2 I was trying to test.

**Comment by jmarolf** [comment]
@paul1956 can you submit a PR with the added nuget package?

**Comment by paul1956** [comment]
If I knew how to submit a PR I would be happy to. Sorry.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #55](https://github.com/dotnet/roslyn-sdk/issues/55) via [**ZenHub**](https://www.zenhub.com/)
