### ISSUE TITLE
Implement recursive "Betterness" comparison of tuple types that differ only by names.

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#10800]
Proposal says:

For two types T1 and T2 that are identity convertible to each other, T1 is preferable to T2 if at least one of the following holds

*	T1 and T2 are exactly the same
*	T1 and T2 are tuple types, the element types of T1 are pairwise preferable to those of T2, and one of the following holds:
	T1 has no names  
	T1 and T2 have the same names in the same positions  
	T1 and T2 are instantiations of a generic type, and for each type argument, T1’s is preferable to T2’s  
*	T1 and T2 are array types and the element type of T1 is preferable to that of T2
*	Etc… ?

Compared to current trivial implementation

* It will have to be recursive through tuples and other composite types (arrays. List<T>, so on)
* We will need to involve dynamic too, since we do not want to choose something with objects, just because it also has tuples with no names.
* It may be easier to implement this once we have serialization logic for metadata export. - we would essentially need to compare results of serialization.

The betterness is applicable to cases where we need to choose between two type candidates that otherwise equal to another. 
That can happen in type inference, ternary operators, lambdas with multiple returns and so on

**Comment by jcouv** [comment]
This is no longer relevant. The design for this changed. We drop names in tuples when there are ambiguities.
