### ISSUE TITLE
Allow specifying the entry point metadata token

### ISSUE THREAD

**Issue by davidfowl** [dotnet/roslyn#1081]
Today when you make a console application with csc, the compiler assumes the entry point should be Program.Main, that's fine but it would be great if the compiler APIs allows an arbitrary metadata token to be set as the assembly entry point.

/cc @tmat

**Comment by jaredpar** [comment]
@davidfowl I can see specifying an arbitrary entry point besides `Main`.  I'm not sure metadata tokens are the right way of identifying the entry point as compilations, in general, are created before metadata tokens are defined.  My initial thought was to have an API which took a string which could be resolved as an entry point.

**Comment by gafter** [comment]
The csc help page (type `csc /?`) documents the following command-line flag:

```none
/main:<type>                   Specify the type that contains the entry point (ignore all other possible entry points)
                               (Short form: /m)
```

**Comment by tmat** [comment]
@gafter This is not sufficient. DNX needs to distinguish between debugger entry point (in PDB) and PE header entry point (/main). I'm looking into it.
