### ISSUE TITLE
Securely Sandboxing Roslyn Code Execution

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/roslyn#10830]
Is there a secure method of sandboxing Roslyn's code execution. I'm thinking something along the lines of what [dotnetfiddle.net](http://dotnetfiddle.net/) is doing?

With such a huge .NET framework, how do you go about choosing what code is allowed to execute?

**Comment by ManishJayaswal** [comment]
We currently don't have any means to do so in the interactive window but it is an interesting idea.

**Comment by tmat** [comment]
Run the code in an isolated process.

**Comment by RehanSaeed** [comment]
@tmat Things like the file system, P/Invoke and Assembly loading need to be blocked, as well as a whole host of other things. Doing this securely is quite difficult. It would be great if there were some kind of curated list of API's that Roslyn could be restricted to.

dotnetfiddle does this but is not open source. They have a [UserVoice](https://dotnetfiddle.uservoice.com/forums/228764--net-fiddle-ideas/suggestions/7078344-share-the-code-of-dotnetfiddle-open-source-on-gith) entry asking for it to be made open source.

**Comment by fekberg** [comment]
This is a very old post that I wrote, but it gives a few ideas on how to approach this, keep in mind the API has changed a lot since I wrote this:

http://www.filipekberg.se/2011/12/08/hosted-execution-of-smaller-code-snippets-with-roslyn/

**Comment by RehanSaeed** [comment]
Haha, I was just reading that and posted this issue to your blog. I think your blog post provides a good start. There is another blog post from the creators of dotnetfiddle where they also talk about timing out the execution and setting limits for memory and things like that. Building a bulletproof sandbox is not very straight forward it seems.

**Comment by RehanSaeed** [comment]
For those interested I put together a [Roslyn.Sandbox](https://github.com/RehanSaeed/Roslyn.Sandbox) project on GitHub with a very rudimentary implementation so far.

Roslyn seems to want a lot of permissions, so when I tried to use the Internet zone on my AppDomain I got a bunch of security exceptions. I had to switch to the My Computer zone for now, to get things working.

@fekberg I guess you did not come accross this issue?

**Comment by kraghavk** [comment]
@RehanSaeed & @fekberg, thanks for the code you guys have put out. It seems like they will work on .NET Framework only? Can you please confirm it is cross-platform compatible?

**Comment by molinch** [comment]
Hi it would be much easier to implement a "light" sandbox if ScriptOptions constructor was public.
Then we could restrict the list of assemblies, namespaces.

Could we change that?

**Comment by mprothme** [comment]
Any updates on this issue or when it might be complete. I'd like to be able to allow my users to write and execute their own scripts while limiting things like memory usage, access to File IO, etc.

**Comment by gafter** [comment]
@mprothme this is not being worked on at the moment. Contributions are welcome.

**Comment by molinch** [comment]
@gafter What about my suggestion of opening ScripOptions? I can make a PR

**Comment by tmat** [comment]
@molinch https://github.com/dotnet/roslyn/pull/32668 is adding more ScriptOptions but we are not making the constructor public.

**Comment by tmat** [comment]
@molinch  I don't actually see why would you need it to be public.

**Comment by tmat** [comment]
@mprothme As a suggested above, the _only_ way to isolate the script securely is to run it in a separate process with limited permissions. Any in-process sandbox can be circumvented and is not secure.

**Comment by molinch** [comment]
@tmat If you have your own API and want to limit executation to that defined surface area only, then we could leverage the script options to provide our "surface area assembly" only, nothing else.
Currently we cannot do that since we cannot change the references from ScriptOptions.

As an alternative we could also analyze the syntax tree and check that all calls are made to our surface API only, but I would rather keep it simple.

**Comment by CodeTherapist** [comment]
@molinch As far as I can see [WithReferences](https://github.com/dotnet/roslyn/blob/d260ee0c20ed31e1ef057bdc179a451e76cf24da/src/Scripting/Core/ScriptOptions.cs#L166) does already exists, or did I missed something?

> As an alternative we could also analyze the syntax tree and check that all calls are made to our surface API only, but I would rather keep it simple.

This would hard to accomplish - How would you ensure that reflection or dynamic code wouldn't call forbidden API's?

**Comment by tmat** [comment]
> Would you be OK, if I submitted a new method to ScriptOptions: WithReferences ?

If you mean that you would pass in reference assemblies that have limited APIs exposed then no, that's not possible currently since the scripting compilation assumes that given references are implementation assemblies. We do not support reference assemblies. Although that is something we would definitely want to support at some point, it's a non-trivial change. Perhaps you could try using custom facade assemblies - assemblies that type-forward to the real implementation assemblies. That only allows you to limit the set of types though, not the set of members. Another problem is that we add reference to mscorlib by default as we need primitive types like System.Object and others to even construct script code context. So, you can't avoid mscorlib types being added, which means Reflection APIs are available and thus the script can really do pretty much anything.

**Comment by paillave** [comment]
I am actually very surprised that such a feature is not available.
At the end of the day Roslyn is a fantastic tool for "metadevelopment" (development of development tools), but 100% useless for business application development (dislike claimed on a microsoft presentation that mentions that roslyn would also provide the ability for the develop to create user defined rule engine). It is indeed strictly impossible to let any user the possibility to call anything from the framework like changing something is the file system, or making a call in a database.

At my side I came up using the code semantic analysis part of Roslyn to analyse the code by ensuring that ANY call of a function is allowed. It is not perfect as it can't detect embedded functions. And for some reasons, it can't resolve ambiguities whereas there is no pb at runtime.

Here is an extract of what I did:

```csharp
            var comp = CSharpScript.Create<O>(this._rule,
                    ScriptOptions.Default
                        .WithImports(this._imports)
                        .AddReferences(this._assemblyReferences),
                    typeof(G)).GetCompilation();
            var actualTree = comp.SyntaxTrees.First();
            var model = comp.GetSemanticModel(comp.SyntaxTrees.First());
            var root = (CompilationUnitSyntax)actualTree.GetRoot();
            var invocationExpressions = root.DescendantNodes().Where(i => i.IsKind(SyntaxKind.InvocationExpression)).OfType<InvocationExpressionSyntax>();
            bool forbiddenCall = false;
            var allowedClassesCalls = _allowedTypes.Select(i => i.FullName).ToHashSet();
            foreach (var invocationExpression in invocationExpressions)
            {
                var memberAccessExpressionSyntax = invocationExpression.Expression as MemberAccessExpressionSyntax;
                var symbolInfo = model.GetSymbolInfo(memberAccessExpressionSyntax);
                if (symbolInfo.Symbol != null)
                {
                    if (!allowedClassesCalls.Contains(symbolInfo.Symbol.ContainingSymbol.ToString()))
                    {
                        forbiddenCall = true;
                        var location = invocationExpression.GetLocation();
                        // item.GetLocation(); // this is the way to get the place where the bad code is called
                    }
                }
                else if (symbolInfo.CandidateSymbols != null)
                {
                    foreach (var symbol in symbolInfo.CandidateSymbols) // is any ambiguity in the method, candidates are here. Surprisingly, for the actual execution roslyn ahs no pb choosing the right one
                    {
                        if (!allowedClassesCalls.Contains(symbol.ContainingSymbol.ToString()))
                        {
                            forbiddenCall = true;
                            var location = invocationExpression.GetLocation();
                            // item.GetLocation(); // this is the way to get the place where the bad code is called
                        }
                    }
                }
            }
            return !forbiddenCall;
```

**Comment by haacked** [comment]
@paillave There's a potential flaw in your code. It's only looking at invocations expressions. However a property access could circumvent it. For example, I changed your code to take in the code as a string, and then wrote this xunit test for it.

```csharp
[Theory]
[InlineData(@"var s = Environment.GetEnvironmentVariable(""test"");")]. // Passes
[InlineData("var s = Environment.CommandLine;")] // Fails
public void Test(string code)
{
    Assert.False(CanExecute(code));
}
```

`CanExecute` returned `true` for `Environment.CommandLine` even though `System.Environment` was not in my list of allowed types.

I wrote a Roslyn Analyzer that seems to do the trick. Check it out and let me know if it works for you.

https://gist.github.com/haacked/00de560d00692b7f4859336c747af10e

**Comment by tmat** [comment]
@paillave If your goal is to run untrusted code you need to run in in a separate process. That's the only guaranteed security boundary. That's why .NET Core does not support Code Access Security - it has never worked well.

**Comment by paillave** [comment]
@haacked Sure... this is only an extract as an example that checks only method calls. Of course, constructors and properties must be checked as well!

@tmat you are right, nothing will never be as safe as a sandbox/different process. Nevertheless, if, like I mentioned above, you check constructors and properties, you code gets extremely safe (but still less than a sandbox). You solution to run something in a different process, you get a complexity of communication between them that can cause a lot of bugs as well. As a matter of a fact, we all dream of the new equivalent of the ApplicationDomain that existed on the framework. It is by far the best we can dream of.

**Comment by paillave** [comment]
@haacked just checked your code. It is OK, but in security, like firewalls for example, everything should be considered as not allowed, unless it is granted. In what I understood from your code, everything is granted, except what is forbidden. If you ever make a mistake in your code, or if an unsafe API is ever added in what was granted before, your code gets dangerous.

**Comment by haacked** [comment]
Looks like the Roslyn team has something that does what we want. https://github.com/dotnet/roslyn-analyzers/tree/master/src/Microsoft.CodeAnalysis.BannedApiAnalyzers

**Comment by paillave** [comment]
> Looks like the Roslyn team has something that does what we want. https://github.com/dotnet/roslyn-analyzers/tree/master/src/Microsoft.CodeAnalysis.BannedApiAnalyzers

Very interesting indeed... But it seems to works by banning a few, instead of granting a few. Am I right?

**Comment by haacked** [comment]
Yes, but it would be easy to invert the logic.

**Comment by paillave** [comment]
@haacked Just checked the code that is in it... There is not too much, but it is very... intense! :D

Not impossible, but still, many hours of pain to invert the purpose I think. I'll consider taking on this challenge at some point I believe. Thanks for the tip!

**Comment by jasekiw** [comment]
Has any progress been made in the last year?

**Comment by tmat** [comment]
Closing this issue as we do not plan to provide any security sandbox.

**Comment by paillave** [comment]
> Closing this issue as we do not plan to provide any security sandbox.
> 
> The recommendation is still to run untrusted scripts in a separate process.

It is a pity. This means that unlike what was advertised, it is not possible to make a proper rule engine for end user because it is not possible to communicate properly with this separate process. Unless you have an advice to accomplish it.

**Comment by CyrusNajmabadi** [comment]
> because it is not possible to communicate properly with this separate process. 

Can you clarify that? There seem to be an abundance of mechanisms to communicate with a separate process.

**Comment by paillave** [comment]
> > because it is not possible to communicate properly with this separate process.
> 
> Can you clarify that? There seem to be an abundance of mechanisms to communicate with a separate process.

There are many ways indeed, but to speak frankly, achieving a reliable and secured rule engine where end users can write their own rule is quiet a piece of work if we take everything that is at stake.

If the duty is not as big as I think, an example in the documentation would be more than welcome!

**Comment by CyrusNajmabadi** [comment]
I feel like you could use any off the shelf rpc library and do this. Can you explain why multiproc is a deal breaker here. To be clear, this isn't really a roslyn decision.  Security isolation within a prices isn't really a thing. You need separate processes for securely sandboxing. So it's not like this is something we could actually solve. Instead you should use the right tech for the actually underlying os platform of you want a real secured sandbox.

**Comment by paillave** [comment]
Indeed, I understand. Nothing to do with Roslyn. 

Like I mentioned higher in this thread:

Even if it is the safest given the context, the solution to run something in a different process gives a complexity of communication between processes that can cause bugs as well. The most elegant solution is the ApplicationDomain that existed on the framework and that doesn't have any equivalent anymore. 

Whatever the solution you can talk about (rpc, or whatever), we must do some wiring that the application domain was gracefully doing for us (or something that seems to work this way at least :) ). Not having this system anymore changes something that was easily accessible for average/lazy developer into something that is **WAY more cumbersome and more tricky to apprehend than ApplicationDomain**. 

So well, as a conclusion, yes, you are right, **indeed, this problem doesn't belong to Roslyn.**

**Comment by jasekiw** [comment]
@CyrusNajmabadi 

Below are links I found when trying to find what is needed to securely sandbox a C# process.

https://www.opensourceforu.com/2016/07/many-approaches-sandboxing-linux/
https://blog.cloudflare.com/sandboxing-in-linux-with-zero-lines-of-code/

Are these options or are there additional considerations to look at? Are there any other options to sandbox a process to kill network access, disk usage limitation, memory usage limitation that you know of?

Thanks!
