### ISSUE TITLE
Ensure that tuple symbol implements "members" correctly

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#10849]
Currently tuple type returns only the "new" members introduced by it being a tuple.
Lookup needs to explicitly look into underlying type to get the rest of the members.

The problem here is that all the places where we look for members of a tuple need to do something similar. 
In addition we have public "Members" API and the most reasonable behavior for that is to return combined set of tuple members and those symbols better have containing type as the typle symbol.

There are alternative ways to implement this.
 - We can either wrap all the "inherited" members of the underlying type into proxies which are same just with tuple as a parent.  

- We can make tuple symbol not have underlying type, but just be an extended kind of symbol - by itself sufficient to represent the underlying type and optionally having extra named fields.

The second approach seems more promising at the moment in terms of amount of special casing introduced to the existing codebase.

Regardless whichever way we go, we should thoroughly test the areas related to memers and containing types. In particular when such members are "inherited" from the ValueTuple implementation.

**Comment by jcouv** [comment]
@VSadov @AlekseyTs  I think this issue can be resolved after the unification work last week. The tests cover the `GetMembers()` API extensively now. 
Is there any open issue left in your mind?

**Comment by AlekseyTs** [comment]
I think we need to add testing to cover all remaining kinds of members that could be declared inside ValueTuple. Operators and such. For example, I discovered that conversion operators couldn't be declared because types were not the same due to unification. Basically we need to cover all kinds of declarations that could go into a type and make sure they are usable through tuples.

**Comment by AlekseyTs** [comment]
Also should cover access to non-public members from inside of the ValueTuple type through tuples.

**Comment by jcouv** [comment]
> We can make tuple symbol not have underlying type, but just be an extended kind of symbol - by itself sufficient to represent the underlying type and optionally having extra named fields.

After tuple type unification, we're doing this (the second approach).
