### ISSUE TITLE
Can't build Roslyn.sln

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#10845]
11>Project 'DeployTestDependencies' is not up to date. Missing output file 'C:\GitHub\roslyn-internal\Open\Binaries\Debug\ProjectSystem.dll'.
11>CSC : error CS0006: Metadata file 'C:\GitHub\roslyn-internal\Open\Binaries\Debug\ProjectSystem\Microsoft.VisualStudio.AppDesigner.dll' could not be found
11>CSC : error CS0006: Metadata file 'C:\GitHub\roslyn-internal\Open\Binaries\Debug\ProjectSystem\Microsoft.VisualStudio.Editors.dll' could not be found

tagging @davkean

**Comment by CyrusNajmabadi** [comment]
I'm in future.

**Comment by davkean** [comment]
Ah, yes, this is a real issue. It will disappear once this merge from master -> future occurs: -internal/pull/901

**Comment by davkean** [comment]
Roslyn.sln ceases to exist after that merge, and no longer will Roslyn.sln in open and Roslyn.sln in internal be out of sync.

**Comment by srivatsn** [comment]
Is this still an issue? Can this be closed?

**Comment by davkean** [comment]
It should be resolved.
