### ISSUE TITLE
[Test Failure] Too many files open on PR #10833

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#10844]
PR: [#10833](https://github.com/dotnet/roslyn/pull/10833) *Metadata writer refactoring (4F)* by @tmat
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/6499/

The restore is failing due to too many files being open. 

11:26:46 Unhandled Exception: System.IO.IOException: Too many open files
11:26:46    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
11:26:46    at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
11:26:46    at System.ConsolePal.OpenStandardOutput()

**Comment by agocke** [comment]
Fixed in #10768

**Comment by mattwar** [comment]
@agocke are the build machines still using older bits?

**Comment by agocke** [comment]
@mattwar It looks like that failure is just because a merge to future hasn't been completed. The commit isn't present in future.

**Comment by davkean** [comment]
Hit this again: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/6537/console
