### ISSUE TITLE
Simplifier reduces generic Array.BinarySearch<T>() to boxed Array.BinarySearch()

### ISSUE THREAD

**Issue by cartermp** [dotnet/roslyn#10840]
**Version Used**: 

.NET Compiler Platform SDK v1.1.1:

`<package id="Microsoft.CodeAnalysis" version="1.1.1" targetFramework="net452" />`

**Steps to Reproduce**:

(I can attempt to build out a simple test project if these steps aren't good enough)
1. Open Immutable Collections solution [from corefx](https://github.com/dotnet/corefx/tree/master/src/System.Collections.Immutable) in Visual Studio.
2. Run the [import-comments tool](https://github.com/dotnet/import-comments) on the `/src` directory with the following arguments:
   
   i. Path to intellisense directory ([intellisense located here](https://github.com/cartermp/intellisense461))
   ii. Path to `/System.Immutable/src`
   ii. Path to `/System.Collections.Immutable/src/System.Collections.Immutable.sln`
3. Look at diff for changes.

**Expected Behavior**:

Things like `cref`s in XML comments are simplified, but changing the overload of a particular method call are not.

**Actual Behavior**:

A call to the generic `Array.BinarySearch<T>(T[] array, T value)` is changed to a call to boxed `Array.BinarySearch(Array array, object value)`.

Diff:
![diff](https://cloud.githubusercontent.com/assets/6309070/14793669/3e46c246-0ad5-11e6-84c8-8e9f0569b373.PNG)

Previous call:
![generic](https://cloud.githubusercontent.com/assets/6309070/14793671/426d7bf8-0ad5-11e6-99c5-d0be8371c862.PNG)

After simplifier:
![boxed](https://cloud.githubusercontent.com/assets/6309070/14793682/4e2e02f0-0ad5-11e6-94d0-6c44354e14fa.PNG)

**Comment by CyrusNajmabadi** [comment]
@DustinCampbell Very curious.  This seems to do the right thing when @dpoeschl and i try this out.   The compiler picks teh right generic overload.  We're not certain why this is reproing differently for @cartermp

**Comment by cartermp** [comment]
@CyrusNajmabadi @dpoeschl are your results stemming from the repro steps I laid out, or from opening up the System.Collections.Immutable solution in VS and having Roslyn notice the improvements?

**Comment by CyrusNajmabadi** [comment]
I cna't repro this anymore, and this fixer was rewritten at one point.  So closing out as likely-fixed a long time ago.

**Comment by cartermp** [comment]
Oh wow, I remember when I ran into this! First time ever filing something here or even using a roslyn-based tool in earnest. Nice little ride down memory lane. I trust that this is resolved 🙂
