### ISSUE TITLE
Replace the open to closed pump with a proper web hook running in Azure

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#10854]
Our current tool has many problems with it:
1. It's running on a fixed machine, which means we lose the pump if the machine goes offline.
2. It has a configured set of branches, when it should really work on all branches as long as the same name exists in opened and closed.
3. It's mirroring to VSTS as well, which we are obsoleting with [the move to MicroBuild v2](https://github.com/dotnet/roslyn/issues/10519)

@jaredpar has proposed that if we replace this with a GitHub webhook that responds on a push to our branch, and that the webhook just lives in Azure, then we can solve both of these issues.

**Comment by agocke** [comment]
This is obsolete -- we shouldn't need a pump any more.

**Comment by jasonmalinowski** [comment]
@agocke We still have the pump for integration testing. What's the plan for that?

**Comment by agocke** [comment]
@jasonmalinowski Ah I forgot about that.

**Comment by jasonmalinowski** [comment]
It's definitely obsolete now. :-)
