### ISSUE TITLE
Make sure that tuple conversions are well speced and implementation matches the spec.

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#10852]
We have introduced a new kind of implicit conversion in the language (ConversionKind.ImplicitTuple)

This is a fairly significant change. 
There is a possibility we will add another for implicit tuple _type_ conversions

We need to make sure that these changes and their consequences are well represented in APIs and tests.

**Comment by jcouv** [comment]
Please update the tuples.md.

**Comment by VSadov** [comment]
not critical for RTM

**Comment by VSadov** [comment]
Tuple supports all kind of conversions now. - implicit/explicit/literal/user-defined conversions.

As a more detailed write up of what is how supported, this can be used: http://mustoverride.com/tuples_conversions/
