### ISSUE TITLE
Implement IOperation support for tuple literals

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#10856]
Design and implement  IOperation support for tuple literals.

Current implementation intentionally implements this as OperationKind.None

The right alternative seems to be introducing a specific operation kind and make visitor visit all the arguments of the literal.

Alternatively we may make tuple literals look like ObjectCreation (which it is indirectly), but it does not feel right conceptually.

**Comment by mavasani** [comment]
Possible API shape:
```
public interface ITupleExpression : IOperation
    {
        /// <summary>
        /// Arguments for tuple expression.
        /// </summary>
        ImmutableArray<IOperation> Arguments { get; }
    }
```

Point to discuss: Bound tree has a separate BoundConvertedTupleLiteral node, which is identical to BoundTupleLiteral, except it represents a tuple literal with source type and destianation. I don't believe we should have this in the IOperation API - instead we should just wrap an ITupleExpression with an IConversion for a BoundConvertedTupleLiteral.

**Comment by mavasani** [comment]
Adding some design issues raised by Aleksey in the PR to implement this:

1. Need to expose declaration expression nodes as a special Operation type: https://github.com/dotnet/roslyn/pull/19636#discussion_r118307056
2. Bunch of unexpected conversions: https://github.com/dotnet/roslyn/pull/19636#discussion_r118124263. Is this a compiler issue or Operation factory needs to filter out unwanted conversion nodes? @AlekseyTs suggested we need to have a design discussion around tuple conversions: https://github.com/dotnet/roslyn/pull/19636#issuecomment-303563841

**Comment by CyrusNajmabadi** [comment]
Keep tuple tests with semantic model tests around tuples.
Try to keep IOperation for tuples in sync with semanticmodel.GetTypeInfo.   That way we don't have two separate APIs that people can use that have inconsistent results.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/20749
