### ISSUE TITLE
Add specific errors for attempts to declare tuples with < 2 fields.

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#10851]
Add specific errors for attempts to declare tuples with < 2 fields.

Currently code reports ERR_PrototypeNotYetImplemented - not what we want.

**Comment by jcouv** [comment]
I may have fixed this already, using `ERR_TupleTooFewElements`, in change [#10842](https://github.com/dotnet/roslyn/pull/10842/files).

**Comment by jcouv** [comment]
@VSadov Please confirm that #10842 does what you want.
