### ISSUE TITLE
Implement Display for tuple expressions when they have no natural type

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#10857]
Current implementation only handles cases when tuple has natural type. 
In other case it just says "<tuple>", which is consistent with lambdas, but not very informative.

In a case of having no type, we should consider manufacturing a "partial" display based on types of underlying arguments.

Regardless, if we choose current implementaiton, the name should come from the MessageID and be localized.

**Comment by jcouv** [comment]
That was fixed already. There is no more fallback to "<tuple>".
