### ISSUE TITLE
Move insertion tool to run as an Azure WebJob

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#10868]
Currently, the insertion tool runs on an internal VM on a fixed machine. We should convert this to an Azure WebJob.

**Comment by jmarolf** [comment]
can Azure WebJobs be run on pre-configured VMs? the insertion tool required a DevDiv enlistment to create the pull requests.  Looking at the [documentation](https://azure.microsoft.com/en-us/documentation/articles/web-sites-create-web-jobs/), this does not seem possible.

**Comment by jasonmalinowski** [comment]
@jaredpar, you have experience here?

**Comment by jasonmalinowski** [comment]
Oops just filed #17289 not realizing this was still around. That other bug is the new plan.
