### ISSUE TITLE
Object.GetType() is Flawed

### ISSUE THREAD

**Issue by martinvahi** [dotnet/roslyn#10865]
The test case in MonoDevelop format might be available at 

[http://temporary.softf1.com/2016/2016_CSharp_Reflection_GetType_flaw_1.zip](http://temporary.softf1.com/2016/2016_CSharp_Reflection_GetType_flaw_1.zip)

The test case, as tried on 64bit openSUSE Linux mono:
    
    using System;
    using System.Reflection;
    
    namespace _CSharp_Reflection_GetType_flaw_1
    {
    
        class Moonshine
        {
            public int i_aa_ = 0;
            public int i_bb_ = 0;
    
            public Moonshine (int i_aa_in, int i_bb_in)
            {
                i_aa_ = i_aa_in;
                i_bb_ = i_bb_in;
            }
        }
    
    
        class MainClass
        {
    
            public static void reflection_does_not_work_in_here<T_TYPE> (
                ref int x_in, ref T_TYPE y_in)
            {
                Console.WriteLine ("Observation: y_in=="+y_in.ToString());
                Console.WriteLine ("Observation: x_in=="+x_in.ToString());
                Console.WriteLine ("-----------");
                Type cl_x = x_in.GetType ();
                if (cl_x.ReflectedType == null) {
                    Console.WriteLine ("Observation: cl_x.ReflectedType==null");
                } 
                Type cl_y = y_in.GetType ();
                if (cl_y.ReflectedType == null) {
                    Console.WriteLine ("Observation: cl_y.ReflectedType==null");
                } 
            }
    
    
            public static void Main (string[] args)
            {
                int x = 42;
                Moonshine 　y = new Moonshine (55, 92);
                reflection_does_not_work_in_here<Moonshine> (ref x, ref y);
            }
        }
    }
    
    /*
    
    // Console output:
    
    Observation: y_in==_CSharp_Reflection_GetType_flaw_1.Moonshine
    Observation: x_in==42
    -----------
    Observation: cl_x.ReflectedType==null
    Observation: cl_y.ReflectedType==null
    
    
    */
    
The issue is that although the x and y are available, accessible, 
at the function that receives their references, part of the reflection library,
namely, Object.GetType(), is not able to access the instances, the x and y.
Reflection is for studying data structures during run-time, so even if the 
compiler is lacking some information during compile-time, the 
run-time studying should still work flawlessly. The x_in is used
for demonstrating that the Object.GetType() fails even with 
the "simplest cases".

**Comment by gafter** [comment]
I think this is misfiled in the Roslyn repo.

**Comment by martinvahi** [comment]
I resubmitted it as a commet to 
[https://bugzilla.xamarin.com/show_bug.cgi?id=37772](https://bugzilla.xamarin.com/show_bug.cgi?id=37772).
