### ISSUE TITLE
Bug in test runner for buildandtest

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#10878]
![image](https://cloud.githubusercontent.com/assets/3804346/14807052/606bee8e-0b2d-11e6-9a51-541c76cd8afa.png)

**Comment by gafter** [comment]
@jaredpar I think this might be yours?

**Comment by jaredpar** [comment]
Looks like a duplicate of #10718 

https://github.com/dotnet/roslyn/issues/10718
