### ISSUE TITLE
[Proposal] Text sequence generators

### ISSUE THREAD

**Issue by andreychizhov** [dotnet/roslyn#10884]
Extend the language with ability of creating iterable sequences from string on language level. 
An idea is similar to string interpolation and anonymous iterators.
E.g. generating the sequence of strings using pattern like that
`
var string! = "Foo{"Bar1", "Bar2", "Bar3, ... , BarN"}Boo";
`
The ! mark is needed (as seems to me) to tell to compiler that string should be treated as sequence, `IEnumerable<string>`, so compiler could infer it correctly.

The result of expression above will be the following { "FooBar1Boo", "FooBar2Boo", "FooBar3Boo", ..., "FooBarNBoo" }.

The linq-based equivalent of that expression looks like the following code
`
{"Bar1", "Bar2", "Bar3, ... , BarN"}.Select(s => string.Format("Foo{0}Boo", s))
`

**Comment by alrz** [comment]
```cs
static string S(string format, params string[] strings) {
  var sb = new StringBuilder();
  foreach(var s in strings) {
    sb.AppendFormat(format, s);
  }
  return sb.ToString();
}

var wat = S("Foo{0}Boo", "Bar1", "Bar2", "Bar3" , ... , "BarN"); 
```

**Comment by bbarry** [comment]
It would have to be more like this: `!"Foo{...}"` (the expression on the right side of the assignment would need to express the fact that the type is enumerable this way).

That said, I am not sure a language feature is necessary for this. 

Suppose you have some `IEnumerable` variable `values`; you could today (C#6) write this:

```csharp
var result = GenerateSequences($"Foo{values}Boo");
```

Where this method is:

```csharp
public static IEnumerable<string> GenerateSequences(FormattableString formatexpr)
{
    if (formatexpr == null) yield break;
    if (formatexpr.ArgumentCount == 0)
    {
        yield return formatexpr.Format;
        yield break;
    }
    foreach (var result in GenerateSequencesImpl(formatexpr.Format, Array.Empty<object>(), formatexpr.GetArguments()))
    {
        yield return result;
    }
}

private static IEnumerable<string> GenerateSequencesImpl(string format, object[] fixedArguments, object[] restArguments)
{
    if (restArguments.Length == 0) return new [] { string.Format(format, fixedArguments) };
    var rest = restArguments.Skip(1).ToArray();
    var next = restArguments[0];
    return  FixArgument(fixedArguments, next).SelectMany(@fixed => GenerateSequencesImpl(format, @fixed, rest));
}

private static IEnumerable<object[]> FixArgument(object[] previouslyfixed, object next)
{
    var enumerable = next as IEnumerable;
    if (enumerable==null || next is string)
    {
        return new[] {previouslyfixed.Concat(new[] { next }).ToArray() };
    }
    return enumerable.Cast<object>().Select(i => previouslyfixed.Concat(new[] {i}).ToArray());
}
```

Warning, that code is full of allocations and other possible avenues of improvement.

**Comment by gafter** [comment]
I don't understand why you wouldn't just do this in an API instead of a language feature. I cannot think of a single place in Roslyn where we would use this feature.

**Comment by andreychizhov** [comment]
For the same reason we want to use code like this `$"Abc{variable}"` instead of this `string.Format("ABC{0}", variable)`. It is just more short and convinient way to do routine things. Of course we can do the same things with additional coding.
