### ISSUE TITLE
Project System: Up-to-date check

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10886]
CPS does not provide a project system up-to-date check out of the box - to get a similar experience to csproj/msvbproj where they only call MSBuild after they've determined that they are out of date, we should implement one.

Things to note:

1) Unlike csproj/msvbproj, we should always write to the output window why we ended up calling MSBuild. Currently, you need to set a registry key to do this in csproj, extremely undiscoverable.

2) Make sure we handle situations, such as WinMDs - where the binary copied to the output is the not the same as the binary as csc produced.

3) Make sure we handle empty VSIX projects where CopyBuildOutputToOutputDirectory is set to false.

4) Ideally, we'll add some telemetry to also track why the project system choose to rebuild, then we can find and fix top issues.

**Comment by davkean** [comment]
tag @KirillOsenkov

**Comment by davkean** [comment]
Please also factor in concerns raised here: https://connect.microsoft.com/VisualStudio/feedback/details/2468519/visual-studio-incremental-build-issue-fastuptodatecheck-doesnt-monitor-xml-documentation-files

**Comment by KirillOsenkov** [comment]
tag @ljcollins25

**Comment by davkean** [comment]
It looks like <UseCommonOutputDirectory>true</UseCommonOutputDirectory> also breaks csproj's update to-date-check:

```
1>Project 'Microsoft.VisualStudio.ProjectSystem.Managed' is not up to date. CopyLocal reference 'C:\Roslyn With Spaces\Binaries\Debug\Microsoft.Build.dll' is missing from output location.
```

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#62
