### ISSUE TITLE
Design and enable Rename refactoring for tuple fields

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#10898]
The functionality is currently blocked to prevent accidental crashes because tuples do not expose enough positional information to make renames possible.

See RenameUtilities.cs

Once compiler provides sufficient info for the locations of tuple field declarations, the rename should be enabled.

There could be many scenarios specific to tuples, so it might make sense to design/discuss what behavior is actually expected.

**Comment by TheOpenDevProject** [comment]
@VSadov Funnily we were discussing the usefulness of this at length between one of our dev teams. It was thought that the syntax might involve some kind of Meta tagging within the template. Will provide example when in office.

**Comment by jcouv** [comment]
If you write `var t = (Alice: 1, Bob: 2);` and attempt a rename on `t.Alice`. It now works.
But if you instead wrote `var t = flag ? (Alice: 1, Bob: 2) : (Alice: 3, Bob: 4);`, then only the first instance of "Alice" gets renamed. 

A similar scenario with anonymous variables (`var t = { Alice = 1, Bob = 2 }`) manages to rename both.

**Comment by jcouv** [comment]
@kuhlenh We're tidying up the issues that have RC marker, so that we have clearer understanding of work left this sprint. 
Does this issue belong in RC?

**Comment by jcouv** [comment]
From discussion with Vlad, it would be up to the IDE to do cascading renaming in the scenario with the ternary operator. There is a tuple type which is introduced and has merged names, but those don't have a `Location`.
`var t = flag ? (Alice: 1, Bob: 2) : (Alice: 3, Bob: 4);`

**Comment by kuhlenh** [comment]
@jcouv I will put together a design mtg next week when @DustinCampbell is back and get something to you ASAP!

**Comment by TheOpenDevProject** [comment]
When can we expect this to land in terms of full release?

**Comment by kuhlenh** [comment]
@jcouv is there any design aspect left on this? I believe @DustinCampbell communicated something wrt this design.

**Comment by Pilchie** [comment]
@kuhlenh Moving to RTW, but the window to react to anything here is getting *very* short for Dev15.

**Comment by Pilchie** [comment]
Using https://github.com/dotnet/roslyn/issues/16566 to track this now.
