### ISSUE TITLE
Building instrumented code throws for auto initialized properties when building Debug bits

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#10896]
Looks like we would have caught this issue if we had tests that build Debug bits but all tests for the instrumentation are building Release bits. We should add at least some tests the build Debug bits as part of the fix for this issue.

**Comment by shyamnamboodiripad** [comment]
The issue was originally found by @drognanar 

FYI @ManishJayaswal @genlu @JohnHamby

**Comment by ManishJayaswal** [comment]
@drognanar is fixing the compiler ( with help from John). Can you also add tests for these was part of the fix?

**Comment by JohnHamby** [comment]
There is no way that the fix will get through code review without a test. I think that @drognanar and @tannergooding have already modified an existing test to be built as Debug in order to cover this.

**Comment by jaredpar** [comment]
Why did we put this bug in area-compilers?  This work doesn't look like something the compiler team will be doing.

**Comment by JohnHamby** [comment]
The edits are in the compiler.

**Comment by jaredpar** [comment]
Area path tracks teams though, not code base location.
