### ISSUE TITLE
Would like better documentation for "editor features"

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#109]
The Roslyn Team just add editor features into the available sourcecode. 
Documentation for integrating things into Visual Studio is "iffy" and rare. I would be good to have a walk-through on what each part does, why it used. etc etc.

Say we have a Roslyn Diagnostic and we want to it to an Editor Feature.

**Comment by sharwell** [comment]
:laughing:

Seriously though, it's a *huge* code base and the documentation extends far beyond it into the Visual Studio SDK. In the meantime, if you have a question about how something particular works there are quite a few people around who can help with targeted explanations.

**Comment by AdamSpeight2008** [comment]
@sharwell 
I have asked questions.
* [Question 1](http://stackoverflow.com/questions/24012101/roslyn-code-diagnostic-report-other-than-text)
* [Question 2](http://stackoverflow.com/questions/27238761/roslyn-diagnostic-visual-studio-colorisation)

 Look at the existing examples, for extending Visual Studio. Even the SDK.
**Highlight all of the occurences of a word / letter.**

It matching on text, not code.

Making these editor features open-sourced does extend the number of available VS Editor Feature examples. I haven't fully looked through and investigated them.

I think it would be useful for to have a more complex one (but not too complex), to learn from. What to implement.
Eg.Using Roslyn to colourise Implicit conversions.

* Roslyn to analyse the source
* Syntax Highlighting
* Style Tagging

**Comment by dsaf** [comment]
I know, right? IDE and Roslyn teams really need to work together. It could be very powerful. And I wish DGML was part of Community Edition as well - imagine the diagraming possibilities.

https://github.com/dotnet/roslyn/issues/535

**Comment by Pilchie** [comment]
This is not something the team is likely to work on, however, we'd be happy to incorporate or link to samples others want to write.
