### ISSUE TITLE
IDELatestDiagnosticGetter in v2 engine doesn't respect document scope for requests

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#10904]
1. Enable IDE v2 diagnostics engine and FSD for C#
2. Unzip \Closed\Test\Solutions\Newtonsoft.Json.zip
3. Open Closed\Test\Solutions\Newtonsoft.Json\Newtonsoft.Json\Newtonsoft.Json.Portable.sln
4. Open file Linq\JsonLoadSettings - you should see a bunch of SA1101 diagnostics with a code fix "Prefix with this"
5. Attempt a FixAll in Document for this diagnostic

**Got:**
VS crashes - ArgumentOutOfRange exception seems to be coming from StyleCop code fixer.

There are couple of issues here:

1. v2 engine is computing and returning diagnostics for entire project (instead of just the document). We probably need to compute across the project due to compilation diagnostics, but the returned diagnostics by the IDELatestDiagnosticGetter should be filtered to request scope. You can set a breakpoint at the end of `FixAllContext.GetDocumentDiagnosticsAsync` to confirm this behavior.
Note that `FixAllContext.GetDocumentDiagnosticsAsync` is a public API.

2. Seems our code fix/fix all engine is allowing exception from FixAllProvider to escape, crashing VS - I will file a separate bug to track that issue.

**Comment by mavasani** [comment]
FYI @heejaechang

**Comment by mavasani** [comment]
Ah, I think 2nd issue is only from devhive as extension manager will crash if any fixer crashes. It won't repro on real product, so I am ignoring issue 2.

**Comment by heejaechang** [comment]
this should be fixed now.
