### ISSUE TITLE
Fuzzy matching only works when you're missing a namespace using

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10913]
I know this is because of where it's plugged in, but it feels odd that we'll only fix up a name if the namespace is not in scope. I expect to be offered to convert from "Bar" -> "BarService".

``` C#
using Foo;

namespace Namespace
{
    class Program
    {
        static void Main(string[] args)
        {
            Bar bar = new Bar();
        }
    }
}

namespace Foo
{
    class BarService
    {
    }
}

```

![image](https://cloud.githubusercontent.com/assets/1103906/14858987/06238858-0c57-11e6-8607-8b8fac077f1e.png)

**Comment by Pilchie** [comment]
@CyrusNajmabadi enabled spell checking for C# since Update 2, so this works with current bits:
![image](https://cloud.githubusercontent.com/assets/312835/14862383/f8224b18-0c65-11e6-8580-e19fc444e12d.png)

**Comment by davkean** [comment]
As in post Update 2?

**Comment by Pilchie** [comment]
Yes.  That's why I said "since Update 2" :)
