### ISSUE TITLE
VSI test BasicLineSeparators fails intermittently

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#10916]
See http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p0/423/VS_Integration_Test_Logs/ and https://github.com/dotnet/roslyn/pull/10814#issuecomment-214896422

**Comment by JohnHamby** [comment]
@Pilchie will be very disappointed to see this.

**Comment by Pilchie** [comment]
I am indeed :crying_cat_face:

**Comment by Pilchie** [comment]
Apparently this affects C# too :(

**Comment by jasonmalinowski** [comment]
@Pilchie, what's the status update here? Per @jaredpar's tool it looks like this is the current flakiest integration test we've seen in the last week.

**Comment by balajikris** [comment]
Reporting more instances of this failure (note that this bug now tracks both C# and VB Line separator tests as the above duped bugs indicate):
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p2/1309/

**Comment by mavasani** [comment]
Failed again: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/5/

**Comment by jaredpar** [comment]
Flaky for 23 days ...  time to disable?

**Comment by Pilchie** [comment]
This hasn't seemed to repro since I added the crashing code in #1138 :'-(

Let's re-activate if this happens again.

**Comment by mavasani** [comment]
Re-opening, CSharpLineSeparators failed today: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/356/console

**Comment by dpoeschl** [comment]
@Pilchie The OneNote says you're working on porting these to the new test framework. Should I assign this to you, or clear out your name in the OneNote? Regardless, I'd like to just ignore this and see how the ported version works out. Does that seem okay?

**Comment by Pilchie** [comment]
Yes.  I started working on this, but didn't get very far, and I'm pretty sure I lost the branch :(

**Comment by dpoeschl** [comment]
Okay, I've removed your name from those entries in the OneNote. Maybe @rchande will be interested. :smile:
