### ISSUE TITLE
What interfaces should get listed when implementing multiple tuple interfaces with different names?

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#10923]
See `OverrideGenericInterfaceWithDifferentNames` and PR #10900.

The scenario is:
```
class Base : I<(int a, int b)>
...
class Derived : Base, I<(int c, int d)>
```
What should `AllInterfaces` show on the symbol for `Derived`.

**Comment by EamonNerbonne** [comment]
I'm assuming `Base : I<(int a, int b)>, I<(int c, int d)>` would be a compile time error?  Then shouldn't this be a compile-time error too?

**Comment by jcouv** [comment]
@EamonNerbonne Yes, that is correct. At the time the issue was filed, we were still contemplating different ways of making `Base : I<(int a, int b)>, I<(int c, int d)>` work.
I'm currently working to make this an error though (PR #12689), so this issue will be resolved together.

**Comment by jcouv** [comment]
This is now an error and I'm adding explicit validation for `AllInterfaces` API in test `DuplicateInterfaceDetectionWithDifferentTupleNames`.
