### ISSUE TITLE
Consider if CSharpSuggestionModeCompletionProvider needs to use a different builder for tuples

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#10922]
Re: src\Features\CSharp\Portable\Completion\SuggestionMode\CSharpSuggestionModeCompletionProvider.cs

We are reusing the same logic in GetBuilderAsync for both tuples and anonymous types. 
This needs to be reviewed for whether tuples need anything special.

**Comment by rchande** [comment]
@VSadov I think @jcouv already covered this unless you were thinking of something else: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/ContextQuery/SyntaxTreeExtensions.cs,d695a6ea5b0dd06e
