### ISSUE TITLE
VisualBasic With statement's expression variable sometimes doesn't get renamed

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#10929]
![vbwithissue](https://cloud.githubusercontent.com/assets/1060731/14870004/87986a18-0cd7-11e6-944a-bc77dcdabf06.png)

**Version Used**: 

VS2015 Update 2

**Steps to Reproduce**:

1. Create a new VB console application targeting .NET Framework 4.6
2. Add a JSON file called project.json and paste the content below to it. You might need to restart VS or close and reopen the solution.
3. Paste the VB code below to Module1.vb
4. Try to rename `vbNode` in the argument list, or place the caret on it

project.json
```JSON
{
	"dependencies": {
		"Microsoft.CodeAnalysis.VisualBasic": "1.2.1"
	},
	"frameworks": {
		"net46": { }
	},
	"runtimes": {
		"win": { }
	}
}
```

VB code
```VB
Imports Microsoft.CodeAnalysis
Imports Microsoft.CodeAnalysis.VisualBasic

Namespace N
	Class C
		Sub M(vbNode As VisualBasicSyntaxNode)
			With vbNode
				If .GetCurrentNode(vbNode) Is Nothing Then
				End If
				'Non-extension methods work if you comment above code
				'If .Contains(vbNode) Then
				'End If
			End With
		End Sub
	End Class
End Namespace
```

**Expected Behavior**:

I expect the rename to also rename `vbNode` in `With vbNode` and that it also gets highlighted if the caret is placed on `vbNode` in the argument list.

**Actual Behavior**:

`vbNode` in `With vbNode` is unknown to the IDE and doesn't get renamed or highlighted.

**Notes**:

I can reproduce it if the method is an extension method, but not a normal method, see the code above.

**Comment by Pilchie** [comment]
Moving to compiler, because it looks like something goes wrong with `GetSymbolInfo()` in this case - all IDE features stop working (Quick Info, Go to Definition, etc).

**Comment by AlekseyTs** [comment]
@Pilchie Would it be possible to provide more details about what API exactly and for which syntax node doesn't behave as expected?
