### ISSUE TITLE
Allow to Switch Back to VS2013 Style XML Comment Outlining

### ISSUE THREAD

**Issue by ilexp** [dotnet/roslyn#10937]
**Version Used**: VS2013, VS2015, no Preview version.

**Steps to Reproduce**:
1. Open a code file that contains XML comments
2. Enable outlining if not enabled anyway.
3. Fold all comments and observe the result.

**Expected Behavior**:

![vs2013](https://cloud.githubusercontent.com/assets/14859411/14877320/4735d01a-0d1c-11e6-8ae8-2e75269afea1.png)

**Actual Behavior**:

![vs2015](https://cloud.githubusercontent.com/assets/14859411/14877323/4bf427d2-0d1c-11e6-861d-20a081caec30.png)

---

I'd really like to have a way to opt-out of the new style. Folding XML comments is a way for me to get a rough overview of a class without having my view obstructed by the documentation I'm currently not interested in. I fold them in order to _not_ see their contents and, judging from this point of view, would not consider the new behavior an improvement.

I suspect that there might be a setting to toggle this. I've searched the IDE for that option to choose which outlining style should be used and somehow revert it back to the one used in VS2013, but didn't find a way. Please let me know if I missed something and feel free to close the issue if this is the case.

**Comment by Pilchie** [comment]
There isn't currently an option for this, but it's one we should consider introducing - I think this is the 3rd (and 4th) times I've heard this request.

**Comment by CyrusNajmabadi** [comment]
Need more info how widespread this request is.
