### ISSUE TITLE
Quick action terminates inserting code snippet

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#10938]
**Version Used**: 15.0.25123.0 PREVIEW

**Steps to Reproduce**:
1. Create a new console application.
2. Use e.g. propfull snippet to start creating a new property
3. Use `File` as property type. A quick action will be offered to add `using System.IO` ... (sort of you just need to deal with the annoying but useless `FileStyleUriParser` ;-))
4. Add the using as offered by the quick action.

**Expected Behavior**:
Be able to continue editing the snippet, i.e. using Tab to switch between snippet fields and `File` to be used in the other place of propfull.

**Actual Behavior**:
The snippet editing is terminated by the quick action. The property is left with `File` and `int`.

This is a regression from VS 2013.

**Comment by CyrusNajmabadi** [comment]
CLosing out as something we just haven't heard about from other customers.
