### ISSUE TITLE
Support proposed "type pattern" in switch

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#10941]
LDM proposed to support `case int` and `case int[]`, `case System.Int32` etc. The latter must be parsed as a constant expression (for compatibility) but bound as a type.

**Comment by alrz** [comment]
Is this only applicable to switch statement? What about `o is T(X: U)` or `o is T { X: U }`? Any plans to support OR patterns in 3.0 at least? One nice thing that this would allow is `o is T or U` which I'd greatly appreciate!

**Comment by gafter** [comment]
@alrz This issue is about C# 7.

**Comment by alrz** [comment]
Oh right, forgot about scissors for a moment. would love to see this anyways.

**Comment by gafter** [comment]
The current position is that a type pattern requires an identifier. This removes some nasty ambiguities. We can look at relaxing it later.
