### ISSUE TITLE
VS crash in Analyzers with latest Roslyn

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#1094]
![See image](https://cloud.githubusercontent.com/assets/3804346/6534659/f85ac80a-c3f3-11e4-88f7-1f692ef231d8.png)

**Comment by gafter** [comment]
@srivatsn This is preventing Roslyn development.

**Comment by srivatsn** [comment]
Looks to be the same as #1093. @heejaechang please prioritize this bug.

**Comment by gafter** [comment]
Worked around this by installing the 20150304.1 dogfood update.
