### ISSUE TITLE
Public API for tuples - open design issues

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#10948]
There are a number of open questions on the design of the public API for tuples.

- Tuple types. When you mention a type such as `System.Tuple<int, int>`, we intend to turn that into a special "tuple" type which differs from the simple constructed type in a number of ways. For example, it has `Arity` of `0`. I suggest

- [x] Its `Symbol.Kind` be `TupleTypeSymbol`, or alternately `NamedTypeSymbol`. In either case its `TypeKind` would be `TupleType`. (**answer**: the Symbol.Kind is NamedTypeSymbol and its TypeKind is Struct, or whatever the underlying type's kind is.)
- [x] Add `ITupleType` which derives from `NamedTypeSymbol` and additionally adds a member
`ReadOnlyArray<FieldSymbol> TupleElements { get; }`, which returns the *elements* of the tuple type in the order in which they are considered to be tuple elements by the language. These fields would also appear among the `Members`. (**answer**: this can be done as an extension method, and we can pull it in later if it seems widely used)
- [x] For an `ITupleType`, there should be an accessor (proposed `TupleUnderlyingType`) that gets you the underlying constructed named type; in the case of the tuple type `(int x, int y)` it should return `System.ValueTuple<int, int>`. (**answer**: we're not doing ITupleType)
- [x] Do we need a way to get from a tuple type's element field to the underlying type's field? That mapping is nontrivial for tuple types with more than 7 elements. (**answer**: maybe. If widely requested we will add it later.)
- [x] We need a proposal for how to handle `GetDeclaredSymbol` for `int x` in the type `(int x, int y)`. I believe it should return the `FieldSymbol` that is an element of the `ITupleType`'s `TupleElements`. The `Locations` of `x` should indicate the source positions of where the identifier `x` occurred in source. (**answer**: this API exists.)
- [x] Currently, we have a number of public methods and properties that have been added to `TypeSymbol` in support of Tuples. It feels like those belong on `TupleTypeSymbol`, or perhaps `NamedTypeSymbol`.
- [x] Equality of tuple types appears to ignore names. I suspect that isn't right. (**answer**: type comparison including tuple names is implemented)
- [x] We explicitly designed a 0-element tuple type into the schema, but the implementation appears to assert that no such tuple type exists. (**answer**: it is not observable in the language whether System.ValueTuple - the non-generic version - is a tuple type. However, there is the slight difference that INamedTypeSymbol.TupleElementNames returns a default rather than an empty array. Similarly, IsTupleType returns `false`. But the implied language behavior is as specified either way.)

What other issues are there in the behavior of the symbol table API and the semantic model?

**Comment by jcouv** [comment]
To move this thread forward, I'm collecting information about the current implementation:

- TypeKind is the TypeKind of the underlying type. We have an open issue to restrict the underlying type to be a struct.
- We don't have an `ITupleType`. Instead, we have tuple-specific properties are available directly via `TypeSymbol`, such as `IsTupleType`, `TupleUnderlyingType`, `TupleElementNames`, `TupleElementFields` and also two methods related to tuple compatibility.
- We have something similar for tuple fields, with `FieldSymbol` declaring `IsTupleField`, `TupleUnderlyingField` and `TupleElementIndex`.
- I will add a test for `GetDeclaredSymbol` explicitly, but we already have the field pointing to the proper syntax as it's declaring syntax. See `GenericTupleWithoutTupleLibrary_01`.
- Tuple equality doesn't ignore names, but it currently uses a single flag to mean both "ignore dynamic" and "ignore tuple element names". To support OHI scenarios, I'm in the process of have two separate flags.
- Regarding 0-tuple, we have `ValueTuple` of arity 0 implemented in the VT library, but there is no support in language or API. Regarding 1-tuple, they are not supported in the language, but because they appear indirectly (when you create an 8-tuple, then access the `Rest` field), we do have API support for it.

**Comment by gafter** [comment]
I would add to this list an issue that, while the type `Dictionary<int, int>` or `Tuple<int, int>` appearing in source have `.Arity` 2 and have 2 type arguments and type parameters, the same is not true for `ValueTuple<int, int>`. I think that is a flaw that should be corrected by RC. The type parameters and `ConstructedFrom` could be built lazily only when requested through the API so there would be little cost associated with fixing this.

**Comment by jcouv** [comment]
Regarding `Arity`, if I recall correctly, this was brought up and discussed in LDM. It was made clear and agreed that tuple types (and `ValueTuple` by virtue of unification) would be non-generic. 
I'll look for notes and schedule some time to discuss.

**Comment by VSadov** [comment]
Yes. We have spent quite a lot of time arguing about Arity and went through 2 alternative implementations where tuples were generic. The conclusion was that there would be rough edges around representing underlying `ValueTuple<T,T>` types and auto-wrapping them into corresponding tuple types is the the best approach in a sense that the inconsistencies are the least disrupting to the mainline scenarios.

**Comment by jcouv** [comment]
Some notes from today's discussion.

We’ll probably have some further discussion on option 4, which may be a reasonable trade-off (but requires more work). 

Option 0: 
ValueTuple automatically gets wrapped into a tuple type
                This is implemented today and was reviewed with LDM, but is a bit strange.
                The arity on ValueTuple<int, int> is zero, which is strange. 
There is still an API backdoor to construct a naked NamedTypeSymbol for VT.

Option 1: 
The Arity for a long tuple should be 8
                This was Neal’s proposal coming to the discussion. But it runs into problems with long tuples. 
What is the OriginalDefinition for (int, …, int)?

Option 2: 
Disallow usage of ValueTuple in source
                This avoid the duality between NamedTypeSymbol and TupleTypeSymbol. But then we can’t write the ValueTuple library itself.
                Also, it is strange to disallow using a type that exists.

Option 3: 
Only wrap a ValueTuple to become a tuple if the attribute is present (can be left empty if no names)
                In that case, the ValueTuple can have Arity up-to 8 and only has its naturally declared members (`Item1`, `Rest`, but no `Item12`). 
A tuple has an Arity of 0.
You can convert back and forth.
VT and tuple would not be considered equivalent for override, hiding, type unification, …
There is no Item9 on `new ValueTuple<int, …., ValueTuple<int, int>>`.

Option 4: 
VT and tuple are different, but VT from metadata gets automatically wrapped
                This is similar to option 3, but it makes it easier to interop with other languages.
                What happens with `(int, int) t2 = ValueTuple.Create((byte) 1, (byte) 2);`?
                There is an inconsistency when building from source, P2P or from metadata.

**Comment by gafter** [comment]
We seem to be re-closing on consensus that option 0 has warts, but the fewest warts among the alternatives.

**Comment by jcouv** [comment]
Per discussion, we'll keep the current design (Option 0).
Closing this issue, as we resolved the various questions.
