### ISSUE TITLE
[Test Failure] No identified problem in prtest/win/dbg/unit32 on PR #10967

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#10977]
PR: [#10967](https://github.com/dotnet/roslyn/pull/10967) *Update corefx refs to -rc2-24027* by @agocke
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/6722/

**1 Test Failures:**
Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences.FindReferencesTests.TestException3_Inverse

**Issue 1: No identified problem**
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.

**Comment by dpoeschl** [comment]
Failure link no longer works. :crying_cat_face:

**Comment by dpoeschl** [comment]
Cross-language FindRefs failure. I thought all the known cross-language test failures were all accounted for, but I'm not sure what's happened in the last 29 days... Any insights @jasonmalinowski or @Pilchie?

**Comment by dpoeschl** [comment]
@jmarolf - You seem interested in this.............

**Comment by jasonmalinowski** [comment]
Not aware of any failures here recently.
