### ISSUE TITLE
Project System: Hosting process

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10995]
We need to determine if we're going to implement the hosting process. We're waiting on the debugger team to provide data on how much time this saves on F5.

We'll also need an async way of initializing this - it's currently the top three of UI delays.

**Comment by mikedn** [comment]
FWIW I consider the hosting process an annoyance because it pollutes the project output directory with unwanted files and changes the name of the process being debugged. Usually I turn off the hosting process and I never noticed any F5 delays or any other kind of problems.

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#50
