### ISSUE TITLE
Error list does not show project to project references exist even though build succeeds

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#10997]
**Version Used**: master branch build 1.3.0.60429

**Steps to Reproduce**:

1. Download [this](https://github.com/dotnet/roslyn-insider-tool/archive/cbf959fb08fd278dbe0c7a940b6ca1d980cfb503.zip) repository
2. Open solution and build

**Expected Behavior**:
Build succeeds without errors

**Actual Behavior**:

Build succeeds but following intellisense error are shown

![image](https://cloud.githubusercontent.com/assets/9797472/14931716/8a78b32c-0e22-11e6-997b-30c0ab7636d5.png)

**Comment by jmarolf** [comment]
@heejaechang

**Comment by heejaechang** [comment]
@jmarolf if you open reference node in solution explorer, does it show references as normal reference?

**Comment by heejaechang** [comment]
by the way, what is VS used? update 1 or update 2?

**Comment by jmarolf** [comment]
@heejaechang master branch build 1.3.0.60429 is used so, Update 2+. I filed this because this should contain the analyzers V2 switch.  I have full solution analysis on, and yes, the project to project reference shows in solution explorer.

**Comment by heejaechang** [comment]
have sat down with @jmarolf and reproed it. it looks like an issue with workspace itself. workspace looks like lost on certain p2p reference info.

explicit adding and removing p2p fixed the issue. but initial solution load didn't know about the p2p references.

moving the bug to @dotnet/roslyn-ide

**Comment by jasonmalinowski** [comment]
@jmarolf, I'm unable to get this project to even build on the command line. Errors include things like:

    1>CSC : warning AD0001: Analyzer 'RefactoringEssentials.CSharp.RoslynUsageAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'.
    5>C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(268,9): error BG1002: File 'Resources\Icons.xaml' cannot be found.

Also, the project defaulted to an Any CPU solution configuration that seems highly broken as well.

**Comment by jcouv** [comment]
This regularly repros for me when working on Roslyn (building works, but intellisense dropped references). I captured and shared a [workspace info log]("\\jcouvdev\shared-dumps\RoslynWorkspaceInfo.xml") in case that helps.

**Comment by jasonmalinowski** [comment]
@jcouv: that link seems broken. In any case, let's let this bug track @jmarolf's issue; please open another one.

**Comment by jcouv** [comment]
@jasonmalinowski Heejae looked at my repro and pointed me to this issue. I believe it's the same one. Here is the working link for the log `\\jcouvdev\shared-dumps\RoslynWorkspaceInfo.xml`.

**Comment by jmarolf** [comment]
Can't get this to repro on latest build

**Comment by jcouv** [comment]
I have not encountered this for a while either. Thanks
