### ISSUE TITLE
Unable to compile conditional access expression in context of expression-bodied void method/lambda expression

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#11]
Related commit: https://github.com/dotnet/roslyn/commit/dd8f041fdd15503f0fc691d9aff28440a39cb923

> ?. invocation in context of a statement-expression should be allowed even if result type of the invocation cannot be made nullable.

I'm expecting it also to work with void methods in expression-bodied form, as well as void lambda expressions:

```c#
using System;

class C<T> {
    void F1(C<T> c) {
        c?.M(); // compiles fine
        
        // error CS0023: Operator '?' cannot be applied to operand of type 'T'
        Action a = () => c?.M();
    }

    // error CS0023: Operator '?' cannot be applied to operand of type 'T'
    void F2(C<T> c) => c?.M();

    
    T M() => default(T);
}
```

**Comment by controlflow** [comment]
And from language design perspective: this whole idea of allowing more conditional access expressions to compile in context where value is ignored (is it defined by spec?) feels awkward and ad-hoc. What kind of scenarios this solves?

As a tooling developer, I have to disable 'introduce variable' refactoring for such expressions and this may be confusing for developers. Also I have no idea of what semantic model should tell about type of such `c?.M()` expression. Is it `T` (I think so) or `void`?

Maybe (I'm not sure), it's better to allow such calls of methods with non-liftable return types in any context, but simply lift unconstrained `T` type (and other non-liftable types) to `void` type?

**Comment by theoy** [comment]
I think the goal is more to allow it in contexts where the normal '.' dispatching is allowed - for example method calls that return a value are allowed as statement expressions.

The user intention is to find places where a NullReferenceException would normally occur and instead allow for a graceful null-propagation (or at least a lack of throwing) to occur.

**Comment by theoy** [comment]
By the way, great catch! I'm thrilled for all of the valuable points that you've been able to help us find as we are trying to land Roslyn v1. :smile:

**Comment by controlflow** [comment]
:wink:

**Comment by VSadov** [comment]
It is allowed to have void returning conditional accesses in statement expression scenarios. Scenarios like  resource?.Dispose()   or   event1?.Invoke()  seems very useful. 
Once we agree on allowing void in such scenarios, it makes sense to remove nullability requirement as well.

**Comment by AlekseyTs** [comment]
I believe this issue has been addressed already. @VladimirReshetnikov, please verify and close if appropriate.
