### ISSUE TITLE
Diagnostics test for validating that Roslyn.sln is dogfoodable with Roslyn signed drops

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#1101]
Lately we have been bitten multiple times by changes to Roslyn analyzers/diagnostic engine causing certain difficult to test issues to be caught during dogfooding Roslyn.sln with the newer signed drops. We have also seen certain Roslyn analyzers not staying clean on Roslyn.sln, causing us pain in moving to newer diagnostics toolset when some other bug fixes have caused the analyzer/fixer behavior to change from expected.
We should write a test, that possibly runs as part of signed build validation or on a nightly basis and helps us stay clean on these scenarios.

**Comment by srivatsn** [comment]
Until the toolset is updated there is no way to run the analyzers on Roslyn.sln. If we do update the toolset, then a simple build would catch these issues. Am I missing something here?

**Comment by mavasani** [comment]
One sanity check could be to build Roslyn.sln and start an instance of VS in RoslynDev hive and open Roslyn.sln in it and verify no analyzer diagnostics show up in error list.
