### ISSUE TITLE
prtest/lin/dbg/unit32 fails at restore step

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#11017]
See http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/6722/console

```
11:44:55 bash: build/scripts/restore.sh: Permission denied
11:44:57 make: *** [/mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/Binaries/toolset/restore.semaphore] Error 126
11:44:57 Build step 'Execute shell' marked build as failure
```

**Comment by mavasani** [comment]
Another failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/6744

**Comment by jasonmalinowski** [comment]
@mattwar, can you investigate?

**Comment by mavasani** [comment]
Seems to be failing consistently: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/6749/console

**Comment by mattwar** [comment]
That one is failing due to a merge conflict.  Was there a different one? I have been investigating the linux restore problem.

**Comment by mattwar** [comment]
@agocke is this related to the ulimit line in the restore.sh file?  It doesn't seem to get to the actual restore commands because none of the messages were echoed.  So that only leaves the ulimit call.  Does this require elevated privileges on linux?

**Comment by agocke** [comment]
@mattwar It may. There is a hard limit on how high userspace is allowed to set the number of handles. Apparently this limit is higher on our Mac machines than on our Linux machines.

**Comment by mavasani** [comment]
FYI: This is still failing on my [PR](https://github.com/dotnet/roslyn/pull/10312): http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/7340/

**Comment by agocke** [comment]
@mavasani You changed the `restore.sh` file. Your PR is the problem.

**Comment by mavasani** [comment]
@agocke That's weird - I didn't touch that file and the local file history on my branch says it was last edited by you with commit 88b6321c

How do I revert that change locally?

**Comment by mavasani** [comment]
Okay, `git update-index --add --chmod=+x .\build\scripts\restore.sh` did the trick.. seems like this got changed during a merge..

**Comment by mavasani** [comment]
I don't see this issue on the PR anymore.
