### ISSUE TITLE
Add an "AdditionalArguments" option to the Csc/Vbc build task

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#11011]
Right now, every time the compiler adds a command line argument, the build task and the project system have to be manually fixed to thread that option through to both MSBuild and the IDE.

A better system would just allow users to specify "additional arguments" in an MSBuild property that automatically gets added to the csc command line and the IDE options.

**Comment by agocke** [comment]
Moving to 2.0 -- wiring through the IDE is the tricky part. Let's not mess too deeply into the project system in 1.3.

**Comment by jaredpar** [comment]
Why didn't https://github.com/dotnet/roslyn/commit/62f3a4afdd727fd56c0bf2cd31a664f8047b1ce7 cover this?

**Comment by agocke** [comment]
@jaredpar We still need an actual MSBuild property that will allow you to append things to the command line.

@jasonmalinowski What was the limitation with Jared's linked PR that prevents us from passing along command line options in this manner?

**Comment by jasonmalinowski** [comment]
@agocke: The commit @jaredpar linked to did the work to mean the project system no longer needed a modification. I'm wondering if this bug was filed without the awareness of that work?

**Comment by agocke** [comment]
Probably? I'm going to close it as resolved.
