### ISSUE TITLE
Fixed Sized Buffers should support formatted value types that contain only the already supported types.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#11018]
At present, fixed size buffers only support `bool`, `byte`, `char`, `short`, `int`, `long`, `sbyte`, `ushort`, `uint`, `ulong`, `float`, and `double`.

This should be expanded to also support formatted value types (structs) that contain only the above supported types.

This would allow interop code, such as the following, to be written:

```
public struct DXGI_RGB
{
    public float Red;
    public float Green;
    public float Blue;
}

unsafe public struct DXGI_GAMMA_CONTROL
{
    public DXGI_RGB Scale;
    public DXGI_RGB Offset;
    public fixed DXGI_RGB GammaCurve[1025];
}
```

**Other Thoughts:**
The existing `backing structure` that is emitted by the compiler to support fixed sized buffers would likely need to be modified to support this.

With the current 'backing structure' a modification to the private fields in a struct would cause a break in the generated code. For example:

Assembly A:

``` C#
public struct S1
{
    private float _x;
}
```

Assembly B:

``` C#
unsafe public struct S2
{
    public fixed S1 Buffer[10];
}
```

The above code will generate something akin to the following:

Assembly A:

``` C#
public struct S1
{
    private float _x;
}
```

Assembly B:

``` C#
unsafe public struct S2
{
    [CompilerGenerated, StructLayout(LayoutKind.Sequential, Pack = 0, Size = 40), UnsafeValueType]
    public struct <Buffer>e__FixedBuffer
    {
        public S1 FixedElementField;
    }

    [FixedBufferAttribute(typeof(S1), 10)]
    public <Buffer>e__FixedBuffer Buffer;
}
```

Then, modifying Assembly A in the following manner will cause a break (the fixed buffer has a size of 40, when it should have a size of 80, due to the additional field added).

``` C#
public struct S1
{
    private float _x;
    private float _y;
}
```

This could be worked around, by modifying the generated structure in the following manner:

``` C#
unsafe public struct S2
{
    [CompilerGenerated, StructLayout(LayoutKind.Sequential, Pack = 1), UnsafeValueType]
    public struct <Buffer>e__FixedBuffer
    {
        public S1 _0;
        public S1 _1;
        public S1 _2;
        public S1 _3;
        public S1 _4;
        public S1 _5;
        public S1 _6;
        public S1 _7;
        public S1 _8;
        public S1 _9;
    }

    [FixedBufferAttribute(typeof(S1), 10)]
    public <Buffer>e__FixedBuffer Buffer;
}
```

Under the newly generated code, the modification to Assembly A would allow Assembly B to still work. This is because the size is computed dynamically, based on the number of elements.

Another interesting scenario is that, with the new system, the emitted structure could be modified even further, so-as to provide a type of 'safe' fixed buffer.

``` C#
unsafe public struct S2
{
    [CompilerGenerated, StructLayout(LayoutKind.Sequential, Pack = 1), UnsafeValueType]
    public struct <Buffer>e__FixedBuffer
    {
        private S1 _0;
        private S1 _1;
        private S1 _2;
        private S1 _3;
        private S1 _4;
        private S1 _5;
        private S1 _6;
        private S1 _7;
        private S1 _8;
        private S1 _9;

        public S1 this[int index]
        {
            get
            {
                if ((index < 0) || (index > 10)) // This would ideally be replaced with an actual array range check so that IndexOutOfRangeException is thrown.
                {
                    throw new ArgumentOutOfRangeException(nameof(index));
                }

                fixed (S1* pFixedBuffer = &_0)
                {
                    return pFixedBuffer[index];
                }
            }

            set
            {
                if ((index < 0) || (index > 10)) // This would ideally be replaced with an actual array range check so that IndexOutOfRangeException is thrown.
                {
                    throw new ArgumentOutOfRangeException(nameof(index));
                }

                fixed (S1* pFixedBuffer = &_0)
                {
                    pFixedBuffer[index] = value;
                }
            }
        }
    }

    [FixedBufferAttribute(typeof(S1), 10)]
    public <Buffer>e__FixedBuffer Buffer;
}
```

Doing this allows validating the index is within the bounds of the fixed array (which is known).

Having this support for fixed buffer structs (especially in a safe manner) would greatly improve the ability to create/work with `SOA` and `AOSOA`.

It is probably also worth noting, that if the fixed buffers where modified to emit a backing structure in the last manner, they could be extended to support all blittable types (including those that do not have a fixed size, such as `IntPtr` and `UIntPtr`

**Comment by tannergooding** [comment]
PR that implements this functionality here: https://github.com/dotnet/roslyn/pull/13064

**Comment by gafter** [comment]
The compiler currently implements the language specification correctly. Relaxing this as requested would cause us to violate the language specification. In other words, this is a language feature request.

**Comment by gafter** [comment]
The best way to move this forward would be to find a member of the LDM to act as a champion and shepherd this feature request through.

**Comment by tannergooding** [comment]
Sounds reasonable to me.

**Comment by tannergooding** [comment]
Added some additional thoughts on the issues that can arrise and the some of the possible benefits (such as ease of implementing SOA and AOSOA types).

**Comment by tannergooding** [comment]
This has been ported to https://github.com/dotnet/csharplang/issues/78
