### ISSUE TITLE
RPS scenario for full solution analysis

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#11029]
We turned off full solution analysis by default for C# with https://github.com/dotnet/roslyn/pull/10828. Now we don't have any RPS coverage for background analysis perf. We are planning to add rolling perf tests to cover this scenario, but we should consider adding RPS scenario for this test as well.

**Comment by mavasani** [comment]
FYI @basoundr @KevinH-MS @srivatsn @heejaechang 

@KevinH-MS stated in [this](https://github.com/dotnet/roslyn/pull/10828#issuecomment-214429982) comment that we may want to leave out FSD in RPS tests.
Given the high radar for performance, is it ok to let this scenario be tracked just by our rolling perf runs? If we indeed decide not to add an RPS scenario, we absolutely *must* treat any regression in the rolling perf test as a high priority issue. I am just worried that such a high bar won't be maintained for our rolling perf tests and the regressions will sneak through.

**Comment by srivatsn** [comment]
We don't have any plans to do this.
