### ISSUE TITLE
Project System: Should be able to drag an item to another to automatically add "DependentUpon"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11030]
It would be great to be able to drag an item to another item in the tree to automatically add the the "DependentUpon" metadata.

**Comment by birbilis** [comment]
btw, I think there was a Visual Studio extension that allowed one to do just that

**Comment by davkean** [comment]
Thanks, I see that File Nesting](https://visualstudiogallery.msdn.microsoft.com/3ebde8fb-26d8-4374-a0eb-1e4e2665070c), and VS Commands does this.

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#49
