### ISSUE TITLE
Clean all diagnostics related VSIntegration tests when all Roslyn/FxCop analyzers are installed

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#1104]
Our setup for running VSIntegration tests on our build machines doesn't include installing the Roslyn analyzers and FXCop analyzers. However, doing a local build of Roslyn.sln installs these in the RoslynDev hive. Additionally, doing an InstallDogdood of latest signed drop installs the Roslyn analyzers. In both these scenarios, certain diagnostics related VSIntegration tests fail due to additional unexpected diagnostics. This makes running VSIntegration tests locally non-trivial and also causes developers to unnecessary spend time identifying the additional VSIX analyzers as the root cause for these failures.
We should clean up our Integration tests to run fine in all the 3 setup scenarios mentioned here.

**Comment by srivatsn** [comment]
Ideally the vsintegrations tests when run locally should run in the same environment as the lab - maybe in a separate hive that doesn't have the roslyn analyzers installed. We should probably just change the script that installs the vsixes for a vsintegration test to install to a hive with a different name thus keeping it clean,.

**Comment by mavasani** [comment]
I don't think we need this anymore.
