### ISSUE TITLE
Some methods in System.IO.File is inaccessible

### ISSUE THREAD

**Issue by mylibero** [dotnet/roslyn#11051]
**Steps to Reproduce**:

```
using System;
using System.IO;

public class Test{
public static void Main(){
if(File.Exists("input"))
Console.WriteLine("Exists!");
}
}
```

In the csccore directory, `./csc /lib:. /r:mscorlib.dll Program.cs`

**Expected Behavior**:
It's a simple example that should be compiled.
I checked that mono compiles it successfully.

**Actual Behavior**:

```
Microsoft (R) Visual C# Compiler version 42.42.42.42
Copyright (C) Microsoft Corporation. All rights reserved.

/home/dongyun/Program.cs(6,12): error CS0122: 'File' is inaccessible due to its protection level

```

**Comment by leppie** [comment]
As you are compiling for core, you need to add a reference to `System.IO.dll`, no?

**Comment by mylibero** [comment]
`./csc /lib:. /r:mscorlib.dll /r:System.IO.dll Program.cs`
gives me the same error.

**Comment by mylibero** [comment]
@leppie @myungjoo
One the other hand,
`./csc /lib:. /r:mscorlib.dll /r:System.Runtime.dll /r:System.IO.FileSystem.dll Program.cs`
compiles well.

If I have to specify all necessary libraries, what does `/lib:.` do?

**Comment by myungjoo** [comment]
My impression is that `/lib` == `-L` or `-B` and `/r` == `-I` in clang/gcc.

**Comment by jaredpar** [comment]
The `/lib:` option specifies extra directories the compiler should use for resolving references that have relative paths.
