### ISSUE TITLE
IntelliSense does not understand lambda parameter type, when overloaded with defaultValue

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#11053]
**Version Used**: VS2015.2

**Steps to Reproduce**:

```csharp
using System;
using System.Collections.Generic;

public static class Program
{
    public static void Main()
    {
        var parameter = new List<string>();
        var result = parameter.FirstOrDefault(x => x$);
    }
}

public static class Enumerable
{
    public static TSource FirstOrDefault<TSource>(this IEnumerable<TSource> source, TSource defaultValue)
    {
        return default(TSource);
    }

    public static TSource FirstOrDefault<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate, TSource defaultValue)
    {
        return default(TSource);
    }
}
```

1. Set cursor to $
2. Type `.` and get no IntelliSense

**Expected Behavior**:
IntelliSense picks the correct overload and suggests that the type of `x` is `string`, providing member completion.

**Actual Behavior**:
![IntelliSense showing `(Parameter) ? x`](https://cloud.githubusercontent.com/assets/7110884/15010871/d3f8dda4-11ee-11e6-92f0-219d7a151d02.png)
If you change the `FirstOrDefault<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate, TSource defaultValue)` overload to `FirstOrDefault<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)`, then it works as expected

**Comment by Pilchie** [comment]
I suspect that this is an issue with `SemanticModel.LookupSymbols`, but can you double-check and move to compiler if so?

**Comment by rchande** [comment]
@cston I debugged this and it looks like GetSymbolInfo/GetTypeInfo on the reference to `x` both return nothing after you type `.`.

The relevant IDE code is [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Recommendations/CSharpRecommendationService.cs,362)

**Comment by rchande** [comment]
Moving to compiler.

**Comment by jaredpar** [comment]
@Pilchie, @DustinCampbell is this just another instance of #11619?
