### ISSUE TITLE
Unable to use Visual Studio when no unique temporary file name is available

### ISSUE THREAD

**Issue by kindermannhubert** [dotnet/roslyn#11059]
**Version Used**: 
Visual Studio 2015 Update 2

**Steps to Reproduce**:

1. Run following code and wait until it fails (can take a while). It will fail with IOException "The file exists.".
```C#
        static void Main(string[] args)
        {
            while (true)
            {
                Path.GetTempFileName(); 
            }
        }
```
2. Restart Studio.

**Expected Behavior**:
VS will work normally or tell me what is going on.

**Actual Behavior**:
Possible results (depends on yout settings): Crash / Shows only black window / Starts normaly.
If it starts normaly, try to open Error List window and it will crash.

**Comment by Pilchie** [comment]
This is not a Roslyn issue.  Please see the discussion in https://github.com/dotnet/roslyn/issues/5061.  If that doesn't resolve it, http://connect.microsoft.com is a better place to file this.
