### ISSUE TITLE
C# /* */ comments: an extra invalid * gets added when pressing enter

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#11057]
![bug2-1](https://cloud.githubusercontent.com/assets/1060731/15015334/9a5cdbc8-120b-11e6-9079-2c31f50c7f57.png)
![bug2-2](https://cloud.githubusercontent.com/assets/1060731/15015335/9b16fe72-120b-11e6-9564-bba98d9f2e7a.png)

**Version Used**: 

VS2015 Update 2

**Steps to Reproduce**:

- Create a new C# Console project or use an existing C# project
- Add a new line and add this comment: /**/ (can't have a space after the first *)
- Move the caret to just before the first /* example: |/* where | is the caret
- Press ENTER

**Expected Behavior**:

A new line is added, but no extra `*` character(s)

**Actual Behavior**:

A new `*` is added before `/*`.

**Comment by davkean** [comment]
Nice one, thanks! cc @diryboy

**Comment by diryboy** [comment]
Ops, let me fix it. Thanks.

**Comment by davkean** [comment]
Once again, thanks for the bug report, this will appear in the next update of Visual Studio 2015.
