### ISSUE TITLE
Interactive window should allow to add commands to history without execution

### ISSUE THREAD

**Issue by AlexanderSher** [dotnet/roslyn#11068]
Command should be available both in history and in text buffer. Command shouldn't interfere with current user input.
In [RTVS](https://github.com/Microsoft/RTVS/), we have at least 2 scenarios that require this feature:
- When user works inside project, all his input into R Interactive Window is saved into file that should be loaded when project is opened again.
- There are several operations (e.g. installing package with Package Manager) that are executed outside of main R session, therefore they aren't visible in R Interactive Window. Users want to see these commands in R Interactive Window as if they were typed manually.

**Comment by ManishJayaswal** [comment]
@tmat to take a look.
