### ISSUE TITLE
[Test Failure] BasicKeywordHighlighting

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#11079]
See http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p0/514/testReport/

```
Executing action [5/5/2016 12:36:55 AM] VerifyKeywordHighlightTags
--------------------------------
System.Exception: Tag count mismatch: 
Expected: 2
Actual: 0
Current editor text:
Class Program
    Shared Sub Main()
        Do
        Loop
    End Sub
End Class
```

**Comment by Pilchie** [comment]
Given the LineSeparator failures, I wonder if there is a general problem with tag verification actions :-(

**Comment by Pilchie** [comment]
The same diagnostic code added to track down #10916, should help here, but we haven't had a failure in a month.
