### ISSUE TITLE
Get offered to add a using that will not solve a conflict

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11071]
I was using SuppressMessage from System.Diagnostics.CodeAnalysis via CodeAnalysis.SuppressMessage, added a reference to Roslyn, and ended up get offered to add a qualification to Microsoft.CodeAnalysis, that will not solve the problem (SuppressMessage doesn't exist in Microsoft.CodeAnalysis):

![image](https://cloud.githubusercontent.com/assets/1103906/15031556/7645fad2-120e-11e6-8c88-220a7c2b8225.png)

**Comment by Pilchie** [comment]
@CyrusNajmabadi what do you think here?  My guess is that this is happening, because we're not considering the additional names to the right.  How much work would it be to do so?

**Comment by CyrusNajmabadi** [comment]
It's not clear to me that this fix is 'wrong'.  Yes it doesn't fully correct the code, but it fixes *an* error in the code and allows you to make further progress.  Namely, it means that "CodeAnalysis" is not correctly bound.  If the user then invokes this fix, they can then invoke a fix like "GenerateType" to make generate the "SupressMessageAttribute" class.  

Our quick fixes are designed to work for people who 'forward type'.  So, to me, the feature is doing the right thing for that user.

**Comment by davkean** [comment]
Let's ask this a different way - out of the top two fixes, which fix do you think is the most likely used in this case?  One that resolves to existing type or one that resolves to an existing namespace, only to then require an additional step to generate the type?

In my mind, I would almost guarantee that it's the former over the later - please put that one on top.

**Comment by CyrusNajmabadi** [comment]
That seems reasonable.
