### ISSUE TITLE
Local Functions Questions.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#11081]
Say we have the following method, which contains local functions.
```c#
... preChecks<T..>( string! fs, T.. obj[] )
{
  const int framework_limit = 1_000_000;
  var ix = 0;
  var q = fs.length;

  void parse_whitespace( string! fs, ref ix ) { while ( ix < q && fs[ix] == ' ' ) { ix++ }  }
...
```
**Questions**
+ Is it valid to have variable / constants declared before the `local function`?
 + Is it legal to intermingle them between `local functions`?
+ What happens if a `local function` has a parameter with the same identifier, as variable in an outer scope?
+ Is it possible to define a variable within `local function` with an identifier, as variable in an outer scope?

**Comment by gafter** [comment]
This would simply be a syntax error on `string!`. There is no such type syntax.

Local function declarations are just statements and can be intermingled with other statements.

The rules for the reuse of names are the same as for lambdas.
