### ISSUE TITLE
Windows Phone Silverlight projects does't work in MsBuildWorkspace

### ISSUE THREAD

**Issue by HermannCalculationWorks** [dotnet/roslyn#11096]
**Version Used**: 1.2.1 - 2.0.0-beta1 03/31/2016

**Steps to Reproduce**: 
1. Use VS2013 or VS2015
2. create new c# project 'Windows Phone Silverlight' 8.0 or 8.1 - app or library
3. try to open and compile the created solution or project within a MsBuildWorkspace

**Expected Behavior**:
getting a compilation with CS8019 (usings) only diagnostics

**Actual Behavior**:
CS0518 (predefined type not defined) and much more diagnostics

**Comment by HermannCalculationWorks** [comment]
Validated on a fresh box with current master branch. It doesn't work as expected.
Remark:
- "Windows Phone" projects works as expected.
- "Windows Phone Silverlight" projects fail.

**Comment by HermannCalculationWorks** [comment]
It seems to be an issue in MsBuild wich is fixed in current master [https://github.com/Microsoft/msbuild](url).
Is there a known workaround how to use "Windows Phone Silverlight" projects with MsBuildWorkspace 1.2.1?

**Comment by Pilchie** [comment]
What known issue do you think it is?

My guess is that the problem here is that your app will need to add binding redirects for msbuild so that tasks built against msbuild 4.0 will work.  See https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CoreTest/app.config for example.

**Comment by HermannCalculationWorks** [comment]
You are right. Binding redirects are the way!
I encountered an internal InvalidCastException inside MsBuild when I was investigating the issue. Finally I merged Roslyn and MsBuild solutions for debugging - and the problem was gone. So I thought it was fixed inside MsBuild. My bad.

Thank you for the response - you saved my weekend.
