### ISSUE TITLE
Make Brace Matching API public

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#11101]
Needs to be moved to Features layer and redesigned for better separation between model and view.

Follow model for Completion API.

**Comment by DustinCampbell** [comment]
Probably small, but putting in the "Unknown" milestone initially. It doesn't feel like the highest priority API to do next.

**Comment by CyrusNajmabadi** [comment]
@sharwell @tmat .  I think we should likely close this out.  It feels like this should go through LSP.

**Comment by CyrusNajmabadi** [comment]
Tracking through https://github.com/dotnet/roslyn/issues/42427
