### ISSUE TITLE
Make Classification API public

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#11100]
Needs to be moved to Features layer and redesigned for better separation between model and view.

Follow model for Completion API.

**Comment by DustinCampbell** [comment]
Putting this in Unknown. It's not clear this is high priority.

**Comment by CyrusNajmabadi** [comment]
@sharwell @tmat .  I think we should likely close this out.  It feels like this should go through LSP.

**Comment by CyrusNajmabadi** [comment]
Tracking through https://github.com/dotnet/roslyn/issues/42427
