### ISSUE TITLE
Make NavigateTo service API public

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#11105]
Needs to be moved to Features layer and redesigned for better separation between model and view.

Follow model for Completion API.

Needs redesign of navigable item so it doesn't actively change editor focus, instead it is a universal representation of location that the host can use to change focus.

**Comment by CyrusNajmabadi** [comment]
@sharwell @tmat .  I think we should likely close this out.  It feels like this should go through LSP.

**Comment by CyrusNajmabadi** [comment]
Tracking through https://github.com/dotnet/roslyn/issues/42427
