### ISSUE TITLE
Make Highlighting API public

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#11102]
Needs to be moved to Features layer and redesigned for better separation between model and view.

Follow model for Completion API.

IHighlighter, convert to doc only, need to convert singleton MEF API to public static

**Comment by dfkeenan** [comment]
Bit curious about this one, and others.  There are a bunch of issues along the lines of "Make service X API public". They seem to mostly to do with "editor features". Is there a group issue keeping track of all of theses?

Will be interesting to see how easy it would be to use these APIs with the likes of the AvalonEdit TextEditor WPF control.

**Comment by mattwar** [comment]
@dfkeenan there is not a group issue for all of these.  I'm keeping track of them as separate issues.

Yes, the purpose of making these API's public is to make it possible to use these features with other editors. Most of these feature API's exist today in the editor-features DLL that is tied to the VS editor.  Some just need an overhaul before making public.

**Comment by dfkeenan** [comment]
@mattwar That's cool just making sure I didn't miss it in my searching if it did exist.  I can always subscribe to each issue or something. I really appreciate you guys making these sort of APIs public.  Do you have a rough priority order in mind? I'm not asking you to make any promises. Just asking out of curiosity.

**Comment by mattwar** [comment]
Signature help is being worked on now.  That's the popup text that shows the various possible method signatures as you are typing a method invocation.

**Comment by CyrusNajmabadi** [comment]
@sharwell @tmat .  I think we should likely close this out.  It feels like this should go through LSP.

**Comment by CyrusNajmabadi** [comment]
Tracking through https://github.com/dotnet/roslyn/issues/42427
