### ISSUE TITLE
Make ReferenceHighlighting service API public

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#11108]
Needs to be moved to Features layer and redesigned for better separation between model and view.

Follow model for Completion API.

IDocumentHighlightsService - LanguageService, doc only
IReferenceHighlightingAdditionalReferenceProvider - LanguageService, doc only

**Comment by CyrusNajmabadi** [comment]
@sharwell @tmat .  I think we should likely close this out.  It feels like this should go through LSP.

**Comment by CyrusNajmabadi** [comment]
Tracking through https://github.com/dotnet/roslyn/issues/42427
