### ISSUE TITLE
re-enable CompilationErrorTelemetryIncrementalAnalyzer once AI is sorted out

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#11133]
as per discussion with @MattGal I am disabling this analyzer. once things sorted out, it should be either removed or re-enabled.

**Comment by heejaechang** [comment]
related to https://github.com/dotnet/roslyn/pull/11158

**Comment by heejaechang** [comment]
here issue is it is sending too much AI. more than AI expects.

**Comment by mavasani** [comment]
@heejaechang What is AI? Can you add some more context here?

**Comment by heejaechang** [comment]
AppInsight.

**Comment by srivatsn** [comment]
@MattGal can this be reenabled now?

**Comment by srivatsn** [comment]
Turns out we don't need this anymore. So we should just delete the code.
