### ISSUE TITLE
Formatter indentation broken before Case keyword

### ISSUE THREAD

**Issue by michalhosala** [dotnet/roslyn#11142]
**Version Used**: SHA 1569c002a5998ebeb3b3a31182946583be773c6a

**Steps to Reproduce**:
1. Create VB console application, call it VbTest.sln,
2. Replace code in Module1.vb with following code:
   
   ```
   Friend Module Module1
   Public Sub Main()
       Dim foo = "foo"
       Select Case (foo)
           Case "a"
                           ' a
               Dim bar = "bar"
                           ' b
           Case "b"
       End Select
   End Sub
   End Module
   ```
3. Now open Samples.sln which is part of Roslyn,
4. Modify the line below to open VbTest.sln instead of default one:
   
   ```
   Solution originalSolution = workspace.OpenSolutionAsync(@"VbTest.sln").Result;
   ```
5. Run the formatter and check the formatted Module1.vb file.

**Expected Behavior**:
Comment `' b` should be aligned with the `Dim` keyword above.

**Actual Behavior**:
Comment `' b` stays where it was, it is not aligned with neither `Dim` nor `Case`.

**Remarks**:
- My expectations are in line with how Visual Studio 2012 is performing formatting in this situation, i.e. it aligns `' b` with above `Dim` keyword.
- I see there is a code in Roslyn to leave the trivia untouched in this situation, but I do not think it is correct, consider the given example, `' b` is not aligned with anything once the formatting is done.
- Issue introduced as part of #4315

**Comment by zippec** [comment]
Another indentation issue which may (or may not) be related #10500

**Comment by michalhosala** [comment]
@zippec this is an unrelated issue, specific to VB.NET and this particular scenario as one can find out by reviewing changes from the #4315 that I already linked.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in this scenario.
