### ISSUE TITLE
Create missing method should factor out generic arguments 

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#11141]
Got that as feature request:
------------------------------------------------
Create missing method should factor out generic arguments

    Priority = EnumFromProperty<Priority> (obj.Property ("priority")),

results in

    static Priority EnumFromProperty<T> (JProperty jProperty)
    {
        throw new NotImplementedException ();
    }

but it should be

    static Priority EnumFromProperty<T> (T @property)
    {
        throw new NotImplementedException ();
    }
------------------------------------------------

However I'm not sure how much can/should be done there. It's clearly a do what I mean feature - however maybe an idea to improve method generation.

**Comment by Pilchie** [comment]
A complete repro:

```C#
using Newtonsoft.Json.Linq;

namespace ConsoleApplication4
{
    public enum Priority
    {
        High,
    }
    class Program
    {
        static Priority Priority { get; set; }

        static void Main(object state)
        {
            JObject obj = null;
            Priority = EnumFromProperty<Priority>(obj.Property("priority"));
         
        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Do you mean that it should be:

```c#
static T EnumFromProperty<T> (JProperty property)
{
    throw new NotImplementedException ();
}
```

?

**Comment by CyrusNajmabadi** [comment]
Seems like this is potentially doable.
