### ISSUE TITLE
Exception Filter can cause different behavior when invoked via reflection.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#1114]
*This was found in an article posted by someone in the community.*

The expected behavior in an exception thrown by the filter should be ignored/treated as false. This is what occurs when the method is invoked directly. However, when the method is invoked via reflection, the exception thrown by the filter is not ignored and causes the invocation to fail.

Console Application:
```csharp
using System;

public class Program
{
    public static void Main(string[] args)
    {
        Console.WriteLine($"{nameof(TestExceptionFilter)}() Direct Invocation");
        Invoke(() => TestExceptionFilter());
        Console.WriteLine();

        Console.WriteLine($"{nameof(TestExceptionFilter)}() Invocation via Reflection");
        Invoke(() => typeof(Program).GetMethod(nameof(TestExceptionFilter)).Invoke(null, new object[0]));
        Console.WriteLine();

#if DEBUG
        Console.WriteLine("Press any key to exit...");
        Console.ReadKey();
#endif
    }

    public static void Invoke(Action action)
    {
        try
        {
            action();
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }

    public static void TestExceptionFilter()
    {
        try
        {
            throw new Exception("Original Exception");
        }
        catch (Exception ex) when (MyCondition())
        {
            Console.WriteLine(ex);
        }
    }

    public static bool MyCondition()
    {
        throw new Exception("Condition Exception");
    }
}
```

Expected Output:
> TestExceptionFilter() Direct Invocation
> System.Exception: Original Exception
>    at Program.TestExceptionFilter() in Program.cs:line 57
>    at Program.<>c.<Main>b__0_2() in Program.cs:line 16
>    at Program.Invoke(Action action) in Program.cs:line 33
> 
> TestExceptionFilter() Invocation via Reflection
> System.Exception: Original Exception - With Filter
>    at Program.TestExceptionFilter() in Program.cs:line 57
>    at Program.<>c.<Main>b__0_2() in Program.cs:line 16
>    at Program.Invoke(Action action) in Program.cs:line 33
> 
> Press any key to exit...

Actual Output:
> TestExceptionFilter() Direct Invocation
> System.Exception: Original Exception
>    at Program.TestExceptionFilter() in Program.cs:line 57
>    at Program.<>c.<Main>b__0_2() in Program.cs:line 16
>    at Program.Invoke(Action action) in Program.cs:line 33
> 
> TestExceptionFilter() Invocation via Reflection
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Condition Exception
>    at Program.MyCondition() in Program.cs:line 67
>    at Program.TestExceptionFilter() in Program.cs:line 59
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
>    at Program.<>c.<Main>b__0_3() in Program.cs:line 20
>    at Program.Invoke(Action action) in Program.cs:line 33
> 
> Press any key to exit...

**Comment by tmat** [comment]
This is by design. Reflection wraps exceptions in TargetInvocationException.

**Comment by tmat** [comment]
Also throwing exception in a filter is the same as returning false. The exception is swallowed by the CLR.

**Comment by tannergooding** [comment]
Then shouldn't the expected behavior be that the TargetInvocationException wraps the original exception and not the exception thrown by the filter (which, as you indicated, should be swallowed)?

**Comment by tmat** [comment]
I did not notice that "Condition Exception" is the message. Strange. Anyways, if the filter just returns false instead of throwing the behavior is expected, right? 

So the only problem is that somehow the swallowed exception ends up wrapped in TargetInvocationException. If so then that could be bug somewhere in CLR that nobody probably cares about fixing -- just don't throw exceptions from filters.

**Comment by VladimirReshetnikov** [comment]
Can we check if the behavior was different in the native VB compiler to see if this is codegen-related or just a CLR problem?

**Comment by gafter** [comment]
This sounds like a CLR/reflection problem. @tannergooding Why did you file it against Roslyn?

**Comment by tannergooding** [comment]
It looks to be a CLR problem (see below). Shall I open a bug under dotnet\coreclr?

Console Application:
```VB
Imports System

Public Class Program

    Public Shared Sub Main()
        Console.WriteLine("TestExceptionFilter() Direct Invocation")
        Invoke(Sub() TestExceptionFilter())
        Console.WriteLine()

        Console.WriteLine("TestExceptionFilter() Invocation via Reflection")
        Invoke(Sub() GetType(Program).GetMethod("TestExceptionFilter").Invoke(Nothing, New Object() {}))
        Console.WriteLine()

#If DEBUG Then
        Console.WriteLine("Press any key to exit...")
        Console.ReadKey()
#End If

    End Sub

    Public Shared Sub Invoke(ByRef action As Action)
        Try
            action()
        Catch ex As Exception
            Console.WriteLine(ex)
        End Try
    End Sub

    Public Shared Sub TestExceptionFilter()
        Try
            Throw New Exception("Original Exception")
        Catch ex As Exception When MyCondition()
            Console.WriteLine(ex)
        End Try
    End Sub

    Public Shared Function MyCondition() As Boolean
        Throw New Exception("Condition Exception")
    End Function

End Class
```

Output:
> TestExceptionFilter() Direct Invocation
> System.Exception: Original Exception
>    at ConsoleApplication1.Program.TestExceptionFilter() in Program.vb:line 31
>    at ConsoleApplication1.Program._Lambda$__1() in Program.vb:line 7
>    at ConsoleApplication1.Program.Invoke(Action& action) in Program.vb:line 23
> 
> TestExceptionFilter() Invocation via Reflection
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Condition Exception
>    at ConsoleApplication1.Program.MyCondition() in Program.vb:line 38
>    at ConsoleApplication1.Program.TestExceptionFilter() in Program.vb:line 32
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
>    at ConsoleApplication1.Program._Lambda$__2() in Program.vb:line 11
>    at ConsoleApplication1.Program.Invoke(Action& action) in Program.vb:line 23
> 
> Press any key to exit...

**Comment by tmat** [comment]
Sure.

**Comment by tannergooding** [comment]
@gafter, misjudgement on my part. Base on my initial investigation I assumed it should have been logged under Roslyn instead of CoreCLR.

The issue has been relogged under dotnet\coreclr as Issue #[410](https://github.com/dotnet/coreclr/issues/410).

**Comment by gafter** [comment]
@tannergooding Thanks!
