### ISSUE TITLE
Portable projects displaying an error on startup 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11144]
This is on Update 2.

Open this solution at this commit: https://github.com/dotnet/roslyn-project-system/commit/6178ae83012bcd20983dc888af4bd1ff56f3838a.

Get a dialog telling you an error has occurred and to look in the activity log:

Stack:

```
Exception handling callback for OnAfterOpenProject: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Newtonsoft.Json.JsonSerializationException: Additional text found in JSON string after finishing deserializing object. at
Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.TryGetProperty(IVsHierarchy hierarchy, HierarchyId id, ProjectProperty property, Object& value) at 
Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.<>c__DisplayClass8_0`1.<GetProperty>b__0() at Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.GetProperty[T](Func`1 propertyGetter) at Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.GetProperty[T](IVsHierarchy hierarchy, ProjectProperty property) at 
Microsoft.VisualStudio.ProjectFlavoring.UnconfiguredProjectProperties.get_ProjectTargets() at 
Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyWatch.PlatformArchitecturesValidator.Validate(IProjectSystem project, ProjectConfigurationProperties3 source) at 
Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyWatch.PropertyValidator`1.Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyWatch.IPropertyValidator.Validate(IProjectSystem project, Object source) at Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyWatch.InvalidPropertyWatcher.ValidateProperty(Object source, IPropertyValidator validator) at Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyWatch.InvalidPropertyWatcher.ValidateAllProperties() at 
Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyWatch.InvalidPropertyWatcher.Run() at 
Microsoft.VisualStudio.ProjectFlavoring.Startup.ProjectStartupManager.OnAfterOpenProject(Object sender, OpenProjectEventArgs e) --- End of inner exception stack trace --- at 
System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Microsoft.VisualStudio.Shell.Events.EventSource.DispatchCallbacks(IEnumerable`1 callbacks, Object sender, EventArgs eventArgs, String key)

```

I've looked at the portable projects and their project.json, and they all look well-formed, so I'm not sure where this is coming from.

**Comment by davkean** [comment]
Actually, maybe this wasn't on startup - looks like we might just leak this error when the project.json is invalid. We should handle this.

**Comment by davkean** [comment]
Here's another one: 

>	Newtonsoft.Json.dll!Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Newtonsoft.Json.JsonReader reader, System.Type objectType, bool checkAdditionalContent)	Unknown
 	Newtonsoft.Json.dll!Newtonsoft.Json.JsonSerializer.DeserializeInternal(Newtonsoft.Json.JsonReader reader, System.Type objectType)	Unknown
 	Newtonsoft.Json.dll!Newtonsoft.Json.JsonSerializer.Deserialize(Newtonsoft.Json.JsonReader reader, System.Type objectType)	Unknown
 	Newtonsoft.Json.dll!Newtonsoft.Json.JsonConvert.DeserializeObject(string value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings)	Unknown
 	Newtonsoft.Json.dll!Newtonsoft.Json.JsonConvert.DeserializeObject(string value, System.Type type, Newtonsoft.Json.JsonConverter[] converters)	Unknown
 	Newtonsoft.Json.dll!Newtonsoft.Json.JsonConvert.DeserializeObject<Microsoft.VisualStudio.ProjectFlavoring.Retargeting.Management.ProjectJsonManager.ProjectJson>(string value, Newtonsoft.Json.JsonConverter[] converters)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Retargeting.Management.ProjectJsonManager.ReadProjectJson(string path)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Retargeting.Management.ProjectJsonManager.ReadFrameworks(string path)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.ProjectTargetingInfoPropertyHandler.GetDotnetTargetsFromProjectJson()	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.ProjectTargetingInfoPropertyHandler.GetCurrentTarget()	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.ProjectTargetingInfoPropertyHandler.GetProperty(Microsoft.VisualStudio.ProjectFlavoring.Retargeting.IProjectTargetingInfo currentValue)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.ProjectPropertyHandler<Microsoft.VisualStudio.ProjectFlavoring.Retargeting.IProjectTargetingInfo>.GetProperty(Microsoft.VisualStudio.ProjectFlavoring.HierarchyId id, Microsoft.VisualStudio.ProjectFlavoring.ProjectProperty property, object currentValue)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.ProjectPropertyProviderManager.TryGetProperty(Microsoft.VisualStudio.ProjectFlavoring.Configuration.IPropertyProvider provider, Microsoft.VisualStudio.ProjectFlavoring.HierarchyId id, Microsoft.VisualStudio.ProjectFlavoring.ProjectProperty property, object currentValue, out Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyResult result)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.ProjectPropertyProviderManager.GetProperty(uint itemId, int propId, out object value)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.ProjectFlavor.GetProperty(uint itemId, int propId, out object currentValue)	Unknown
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.Flavor.FlavoredProjectBase.Microsoft.VisualStudio.Shell.Interop.IVsHierarchy.GetProperty(uint itemId, int propId, out object property)	Unknown
 	[Native to Managed Transition]	
 	ProjectAggregator.dll!<Unknown function>	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for ProjectAggregator.dll]	
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.TryGetProperty(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy hierarchy, Microsoft.VisualStudio.ProjectFlavoring.HierarchyId id, Microsoft.VisualStudio.ProjectFlavoring.ProjectProperty property, out object value)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.GetProperty(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy hierarchy, Microsoft.VisualStudio.ProjectFlavoring.HierarchyId id, Microsoft.VisualStudio.ProjectFlavoring.ProjectProperty property)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.GetProperty(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy hierarchy, Microsoft.VisualStudio.ProjectFlavoring.ProjectProperty property)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.GetProperty.AnonymousMethod__0()	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.GetProperty<Microsoft.VisualStudio.ProjectFlavoring.Retargeting.IProjectTargetingInfo>(System.Func<object> propertyGetter)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.GetProperty<Microsoft.VisualStudio.ProjectFlavoring.Retargeting.IProjectTargetingInfo>(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy hierarchy, Microsoft.VisualStudio.ProjectFlavoring.ProjectProperty property)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.Handlers.ProjectTargetsPropertyHandler.GetCurrentTargets()	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.Handlers.ProjectTargetsPropertyHandler.GetProperty(Microsoft.VisualStudio.ProjectFlavoring.Retargeting.Management.ProjectTarget[] currentValue)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.ProjectPropertyHandler<Microsoft.VisualStudio.ProjectFlavoring.Retargeting.Management.ProjectTarget[]>.GetProperty(Microsoft.VisualStudio.ProjectFlavoring.HierarchyId id, Microsoft.VisualStudio.ProjectFlavoring.ProjectProperty property, object currentValue)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.ProjectPropertyProviderManager.TryGetProperty(Microsoft.VisualStudio.ProjectFlavoring.Configuration.IPropertyProvider provider, Microsoft.VisualStudio.ProjectFlavoring.HierarchyId id, Microsoft.VisualStudio.ProjectFlavoring.ProjectProperty property, object currentValue, out Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyResult result)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.ProjectPropertyProviderManager.GetProperty(uint itemId, int propId, out object value)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.ProjectFlavor.GetProperty(uint itemId, int propId, out object currentValue)	Unknown
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.Flavor.FlavoredProjectBase.Microsoft.VisualStudio.Shell.Interop.IVsHierarchy.GetProperty(uint itemId, int propId, out object property)	Unknown
 	[Native to Managed Transition]	
 	ProjectAggregator.dll!<Unknown function>	Unknown
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.TryGetProperty(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy hierarchy, Microsoft.VisualStudio.ProjectFlavoring.HierarchyId id, Microsoft.VisualStudio.ProjectFlavoring.ProjectProperty property, out object value)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.GetProperty(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy hierarchy, Microsoft.VisualStudio.ProjectFlavoring.HierarchyId id, Microsoft.VisualStudio.ProjectFlavoring.ProjectProperty property)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.GetProperty(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy hierarchy, Microsoft.VisualStudio.ProjectFlavoring.ProjectProperty property)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.GetProperty.AnonymousMethod__0()	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.GetProperty<Microsoft.VisualStudio.ProjectFlavoring.Retargeting.Management.ProjectTarget[]>(System.Func<object> propertyGetter)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.Shell.Interop.VsPropertyExtensions.GetProperty<Microsoft.VisualStudio.ProjectFlavoring.Retargeting.Management.ProjectTarget[]>(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy hierarchy, Microsoft.VisualStudio.ProjectFlavoring.ProjectProperty property)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.UnconfiguredProjectProperties.ProjectTargets.get()	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyWatch.PlatformArchitecturesValidator.Validate(Microsoft.VisualStudio.ProjectFlavoring.IProjectSystem project, VSLangProj80.ProjectConfigurationProperties3 source)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyWatch.PropertyValidator<VSLangProj80.ProjectConfigurationProperties3>.Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyWatch.IPropertyValidator.Validate(Microsoft.VisualStudio.ProjectFlavoring.IProjectSystem project, object source)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyWatch.InvalidPropertyWatcher.ValidateProperty(object source, Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyWatch.IPropertyValidator validator)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyWatch.InvalidPropertyWatcher.ValidateAllProperties()	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyWatch.InvalidPropertyWatcher.Run()	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyWatch.InvalidPropertyWatcher.OnListenersChanged(object sender, System.EventArgs e)	Unknown
 	Microsoft.VisualStudio.ProjectFlavoring.dll!Microsoft.VisualStudio.ProjectFlavoring.Configuration.PropertyWatch.PropertyListenerProvider.Microsoft.VisualStudio.Shell.Interop.IVsUpdateSolutionEvents.OnActiveProjectCfgChange(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy pIVsHierarchy)	Unknown

**Comment by rchande** [comment]
Fixed in lab/ml
