### ISSUE TITLE
[Test Failure] Failing integration tests: CSharpSmartIndenter.xml CSharpSnippets.xml OptionPagesDTE.xml  in roslyn_prtest_win_vsi3 on PR #11139

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#11150]
PR: [#11139](https://github.com/dotnet/roslyn/pull/11139) *Do not crash if we are passed a null compilation in EnumerateSymbols* by @jmarolf
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_vsi3/12/

Failing integration tests: CSharpSmartIndenter.xml CSharpSnippets.xml OptionPagesDTE.xml 
Indication 1 

```
12:44:55 System.Exception: Actual and expected items don't match:
12:44:55 Expected: namespace N1
12:44:55 {
12:44:55 	class Program
12:44:55 	{
12:44:55 		/// <summary>
12:44:55 		/// MARKER
12:44:55 		/// 
12:44:55 		/// </summary>
12:44:55 		static void Main(string[] args)
12:44:55 		{
12:44:55 		}
12:44:55 	}
12:44:55 }
12:44:55 Actual: namespace N1
12:44:55 {
12:44:55 	class Program
12:44:55 	{
12:44:55 		/// <summary>
12:44:55 		/// MARKER
12:44:55         /// 
12:44:55 		/// </summary>
12:44:55 		static void Main(string[] args)
12:44:55 		{
12:44:55 		}
12:44:55 	}
12:44:55 }
```

**Comment by DustinCampbell** [comment]
I hear @jasonmalinowski fixed this yesterday.

**Comment by jasonmalinowski** [comment]
I fixed OptionPagesDTE in future _only_. This was against master, and the other failures aren't known or fixed.

**Comment by balajikris** [comment]
The given link is no longer active and no more occurrences of these have been observed yet. Closing this bug, will file new ones if they pop up again.

**Comment by jinujoseph** [comment]
i am seeing OptionPagesDTE.xml  mergeing stablization into master

**Comment by Pilchie** [comment]
@jinujoseph @jasonmalinowski What is the current state here?  I suspect this is fixed now?

**Comment by Pilchie** [comment]
Did I see that you cleaned this up again?  Is it passing now?

**Comment by Pilchie** [comment]
No repros in the last month.
