### ISSUE TITLE
Support linked files so solution can Zipped

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#11164]
**Version Used**: 
Feature Request
**Steps to Reproduce**:

1. ZIP a solution with Linked Files using underlying OS
2. Copy ZIP file to another computer and unZIP
3. build solution

**Expected Behavior**:
It has all the source files to build
**Actual Behavior**:
All linked files are missing

There needs to be a way to find and replace all linked files with physical files and then reverse it. I am looking for an easy solution other then to stop using linked files. I also don't want to have to find all the linked files in file system, manually copy them, ZIP then delete. This seems very error prone. The ability to highlight all Linked Files in Project system and convert linked to physical and visa versa, or a built in source packaging command could help. I am no proposing any specific solution.

**Comment by gafter** [comment]
I am not sure what this has to do with Roslyn. This appears to be more about how you organized your files in the filesystem and the way you use zip.

**Comment by paul1956** [comment]
I was asked to post it in the new project system, and thought I did. If I didn't can someone point me to the correct site.

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#43
