### ISSUE TITLE
[Proposal] Grouped Const.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#11165]
## Grouped Const

In the big open-source projects (I've seen) using C# or VB.net, tend to contain a lot of constants.
Eg [Roslyn Project System](https://github.com/dotnet/roslyn-project-system/blob/master/src/Common/IVsSqm.vb)

``` vb.net
        Public Const Undefined As UInt32 = 0
        Public Const DATAID_SQM_ACTIVATEDOCWINDOW As UInt32 = 1    ' (Stream) 
        Public Const DATAID_SQM_UICONTEXTCHANGED As UInt32 = 2    ' (Stream) 
        Public Const DATAID_SQM_PERFMEMORY As UInt32 = 3
        Public Const DATAID_SQM_STARTUPOS As UInt32 = 4
        Public Const DATAID_SQM_STARTUPOSVERSION As UInt32 = 5
        Public Const DATAID_SQM_STARTUPOSBUILD As UInt32 = 6
        Public Const DATAID_SQM_STARTUPOSSERVICEPACK As UInt32 = 7
        Public Const DATAID_SQM_STARTUPAPPID As UInt32 = 8
        Public Const DATAID_SQM_STARTUPAPPBUILDTYPE As UInt32 = 9
        Public Const DATAID_SQM_STARTUPAPPVERSION As UInt32 = 10
```

I think it would help if there was an alternative syntax for writing them. In c# and VB.net we have a nice syntax for writing `Enums` values. Why not have a similar syntax for constants.
## Proposed Syntaxes

**VB.net**

``` vb.net
Public Const UInt32
  Undefined                       =  0,
  DATAID_SQM_ACTIVATEDOCWINDOW    =  1, ' (Stream) 
  DATAID_SQM_UICONTEXTCHANGED     =  2, ' (Stream) 
  DATAID_SQM_PERFMEMORY           =  3,
  DATAID_SQM_STARTUPOS            =  4,
  DATAID_SQM_STARTUPOSVERSION     =  5,
  DATAID_SQM_STARTUPOSBUILD       =  6,
  DATAID_SQM_STARTUPOSSERVICEPACK =  7,
  DATAID_SQM_STARTUPAPPID         =  8,
  DATAID_SQM_STARTUPAPPBUILDTYPE  =  9,
  DATAID_SQM_STARTUPAPPVERSION    = 10
End Const
```

The compiler would consider this to be equivalently to as if it was the first.

**C#**

``` c#
public const uint32
{
  Undefined                       =  0,
  DATAID_SQM_ACTIVATEDOCWINDOW    =  1, // (Stream) 
  DATAID_SQM_UICONTEXTCHANGED     =  2, // (Stream) 
  DATAID_SQM_PERFMEMORY           =  3,
  DATAID_SQM_STARTUPOS            =  4,
  DATAID_SQM_STARTUPOSVERSION     =  5,
  DATAID_SQM_STARTUPOSBUILD       =  6,
  DATAID_SQM_STARTUPOSSERVICEPACK =  7,
  DATAID_SQM_STARTUPAPPID         =  8,
  DATAID_SQM_STARTUPAPPBUILDTYPE  =  9,
  DATAID_SQM_STARTUPAPPVERSION    = 10

}
```

**Caveats**
- All of the constants defined within a **grouped const** have the same type  
  - In this example `UInt32`
- All of the constants defined within a **grouped const** have the same visibility.
  - In this example: `Public`
- You can not change the type / visibility of an entry within a **grouped const**
  - eg `Private  DATAID_SQM_STARTUPOSSERVICEPACK =  7,` **error**

**Comment by DavidArno** [comment]
I think this is a brilliant suggestion: simple, elegant and very useful in a wide range of situations.

**Comment by AdamSpeight2008** [comment]
@gafter Applicable to C# too.

**Comment by AnthonyDGreen** [comment]
How is this _not_ the same as an enum?

**Comment by DavidArno** [comment]
@AnthonyDGreen,

Not sure about VB.NET, but in C# the answer is "because enums aren't constants", eg the following code will give a "cannot convert from enum to uint" error:
```cs
public enum Stuff
{
  Undefined                       =  0,
  DATAID_SQM_ACTIVATEDOCWINDOW = 1, // (Stream) 
  DATAID_SQM_UICONTEXTCHANGED = 2, // (Stream) 
  DATAID_SQM_PERFMEMORY = 3,
  DATAID_SQM_STARTUPOS = 4,
  DATAID_SQM_STARTUPOSVERSION = 5,
  DATAID_SQM_STARTUPOSBUILD = 6,
  DATAID_SQM_STARTUPOSSERVICEPACK = 7,
  DATAID_SQM_STARTUPAPPID = 8,
  DATAID_SQM_STARTUPAPPBUILDTYPE = 9,
  DATAID_SQM_STARTUPAPPVERSION = 10

}

...
UInt32 x = Stuff.DATAID_SQM_ACTIVATEDOCWINDOW;
```

**Comment by bondsbw** [comment]
Is there some reason enums cannot be made to work where constants are expected?

**Comment by AdamSpeight2008** [comment]
@AnthonyDGreen `Enums` can't be defined within a method, `const` can.

**Comment by tannergooding** [comment]
@DavidArno,

The given code may not be allowed:
`uint x = Stuff.DATAID_SQM_ACTIVATEDOCWINDOW;`

but the following is:
`uint x = (uint)Stuff.DATAID_SQM_ACTIVATEDOCWINDOW;`

you can even do:
`const uint x = (uint)Stuff.DATAID_SQM_ACTIVATEDOCWINDOW;`


In fact, the IL generated for:
```
public enum Stuff
{
    Undefined = 0,
    DATAID_SQM_ACTIVATEDOCWINDOW = 1, // (Stream)
    DATAID_SQM_UICONTEXTCHANGED = 2, // (Stream)
    DATAID_SQM_PERFMEMORY = 3,
    DATAID_SQM_STARTUPOS = 4,
    DATAID_SQM_STARTUPOSVERSION = 5,
    DATAID_SQM_STARTUPOSBUILD = 6,
    DATAID_SQM_STARTUPOSSERVICEPACK = 7,
    DATAID_SQM_STARTUPAPPID = 8,
    DATAID_SQM_STARTUPAPPBUILDTYPE = 9,
    DATAID_SQM_STARTUPAPPVERSION = 10
}
```
and for
```
public sealed class Stuff
{
    public const int Undefined = 0;
    public const int DATAID_SQM_ACTIVATEDOCWINDOW = 1; // (Stream)
    public const int DATAID_SQM_UICONTEXTCHANGED = 2; // (Stream)
    public const int DATAID_SQM_PERFMEMORY = 3;
    public const int DATAID_SQM_STARTUPOS = 4;
    public const int DATAID_SQM_STARTUPOSVERSION = 5;
    public const int DATAID_SQM_STARTUPOSBUILD = 6;
    public const int DATAID_SQM_STARTUPOSSERVICEPACK = 7;
    public const int DATAID_SQM_STARTUPAPPID = 8;
    public const int DATAID_SQM_STARTUPAPPBUILDTYPE = 9;
    public const int DATAID_SQM_STARTUPAPPVERSION = 10;
}
```
is identical, other than the the inheritance from `System.Enum` and the generation of a special field in which the value of the enum can be held.

**Comment by DavidArno** [comment]
@bondsbw,

The problem there is that `DATAID_SQM_ACTIVATEDOCWINDOW = 1` implies an `Int32`. So the compilers could be made to convert that enum to an `int`, a cast from `int` to `uint` isn't a safe cast and so would still require an explicit cast. @AdamSpeight2008's suggestion gets around that by making the type clear.

An alternative approach could be to allow enums to define their casting type and so allow implicit conversions:
```cs
public enum<Uint32> Stuff
{
  Undefined                       =  0,
  DATAID_SQM_ACTIVATEDOCWINDOW = 1, // (Stream) 
  DATAID_SQM_UICONTEXTCHANGED = 2, // (Stream) 
  DATAID_SQM_PERFMEMORY = 3,
  DATAID_SQM_STARTUPOS = 4,
  DATAID_SQM_STARTUPOSVERSION = 5,
  DATAID_SQM_STARTUPOSBUILD = 6,
  DATAID_SQM_STARTUPOSSERVICEPACK = 7,
  DATAID_SQM_STARTUPAPPID = 8,
  DATAID_SQM_STARTUPAPPBUILDTYPE = 9,
  DATAID_SQM_STARTUPAPPVERSION = 10
}
...
UInt32 x = Stuff.DATAID_SQM_ACTIVATEDOCWINDOW; // works just fine
```

**Comment by tannergooding** [comment]
@DavidArno, you can define the type for an enum.

Try:
```
public enum Stuff : uint
{
  Undefined                       =  0,
  DATAID_SQM_ACTIVATEDOCWINDOW = 1, // (Stream) 
  DATAID_SQM_UICONTEXTCHANGED = 2, // (Stream) 
  DATAID_SQM_PERFMEMORY = 3,
  DATAID_SQM_STARTUPOS = 4,
  DATAID_SQM_STARTUPOSVERSION = 5,
  DATAID_SQM_STARTUPOSBUILD = 6,
  DATAID_SQM_STARTUPOSSERVICEPACK = 7,
  DATAID_SQM_STARTUPAPPID = 8,
  DATAID_SQM_STARTUPAPPBUILDTYPE = 9,
  DATAID_SQM_STARTUPAPPVERSION = 10
}
```

It still won't allow implicit conversions, but it is allowed and is then stored internally as a unit.

**Comment by DavidArno** [comment]
@tannergooding ,

> It still won't allow implicit conversions,

... and so you are still proposing a messy alternative to a simple syntactic-sugar solution to defining lots of constants of the same type.

**Comment by AdamSpeight2008** [comment]
@AnthonyDGreen 
> How is this not the same as an enum?

I would have used an `enum` it the case I linked to, but for some unknown reason they choose to use `const`s. I the case we they do, we should make they're programming experience a little better.

**Comment by gafter** [comment]
@AdamSpeight2008 
> @gafter Applicable to C# too.

I'll work on getting that retrofitted to C# 1.0

```cs
        const int
            A = 1,
            B = 2;
```

**Comment by AdamSpeight2008** [comment]
@AnthonyDGreen  `Enum` can't be of type `string`

Usage Example with const string.
[Currently](roslyn-project-system/src/Microsoft.VisualStudio.Editors/HelpKeywords.vb)
[Using Grouped Const](https://gist.github.com/AdamSpeight2008/031800722746667e43f0852231852938)

**Comment by gafter** [comment]
OK, I've gone back and updated previous versions of C#. They now support this. ;)

**Comment by AdamSpeight2008** [comment]
Would make converting the code to `enum` to `grouped const` or visa-versa easier.

**Comment by DavidArno** [comment]
@gafter,

Oh my, total brain-failure on my part. Of course it's already possible in C#...

```cs
public const uint32
    Undefined                       =  0,
    DATAID_SQM_ACTIVATEDOCWINDOW    =  1, // (Stream) 
    DATAID_SQM_UICONTEXTCHANGED     =  2, // (Stream) 
    DATAID_SQM_PERFMEMORY           =  3,
    DATAID_SQM_STARTUPOS            =  4,
    DATAID_SQM_STARTUPOSVERSION     =  5,
    DATAID_SQM_STARTUPOSBUILD       =  6,
    DATAID_SQM_STARTUPOSSERVICEPACK =  7,
    DATAID_SQM_STARTUPAPPID         =  8,
    DATAID_SQM_STARTUPAPPBUILDTYPE  =  9,
    DATAID_SQM_STARTUPAPPVERSION    = 10 ...
```

**Comment by Joe4evr** [comment]
Re:
> How is this *not* the same as an enum?

While it's pretty much the same as an enum for numeric types, you wouldn't be able to do the same for `const string`s.

**Comment by alrz** [comment]
@Joe4evr While the original post is not about strings at all, but here you go,
```cs
public const string
  String1 = "..",
  String2 = "..";
```

**Comment by Thaina** [comment]
I just think.... Why we can't use constant enum
And why we can't let enum implicitly cast to its base type

For such a long time even we have `enum N : int { A = 0,B = 1,C = 2 }` we must explicitly cast from N to int

Surely, cast from int to enum N should be explicit. But from N to int should be just implicit everywhere

Same go for constant. At least `const int A = N.A` should be possible. At least it could replace at compile time instead of error

**Comment by svick** [comment]
@Thaina 

> And why we can't let enum implicitly cast to its base type

For one, it would be a breaking change: If you have `void M(N n)` in base type and `void M(int i)` in derived type, then calling `M(N.A)` from the derived type will currently call the base type method but if you add the implicit conversion, it will start calling the derived type method.

Another good reason is that most of the time, `enum`s are not used as numerical values.

Consider these two expressions:

```c#
someString.IndexOf("A", 0, StringComparison.Ordinal)
someString.IndexOf('A', 0, StringComparison.Ordinal)
```

Both look fine, right? Actually, no, the second one is a compile-time error: there is no `IndexOf(char, int, StringComparison)` overload. But there is this overload: `IndexOf(char, int, int)`, which means that if `StringComparison` was implicitly convertible to `int`, the second expression would be a bug.

**Comment by Thaina** [comment]
I think normally for overload function it mostly match the closest derived chain if it is a class. It should be the same for enum if we explicitly derived from a type

for example, 2 functions with same name, with parameter object and another one is string. you can put string and it would choose a latter

**Comment by HaloFour** [comment]
@Thaina 

> Same go for constant. At least const int A = N.A should be possible. At least it could replace at compile time instead of error

```cs
const N A = N.A;
```

Taking the constant isn't the issue, it's the implicit conversion.  However, C# does allow explicit conversion syntax in that case:

```cs
const int A = (int)N.A;
```

**Comment by markhurd** [comment]
I would suggest these are "anonymous" Enums, but could include Strings and Dates, of course. My preferred syntax would be:

```
    Public Const As Integer
        V1 = 1
        V2 = 2
        V3 = 3
    End Const
```

cf the current Enum syntax:

```
    Public Enum E1 As Integer
        V1 = 1
        V2 = 2
        V3 = 3
    End Enum
```

**Comment by AdamSpeight2008** [comment]
+ They're not anonymous, as they have an identifie
+ I think name *anonymous enums* wouldn't sit well, in the vocabulary of your average VB programmer. *Sorry. Please don't stone me.* .
+ `Enum`s require a comma to separate the values.

**Comment by markhurd** [comment]
@AdamSpeight2008 I was suggesting what they are conceptually. My `Enum` syntax example is current VB.

**Comment by AdamSpeight2008** [comment]
[Ported to VBLang](https://github.com/dotnet/roslyn/issues/11165)
