### ISSUE TITLE
Certain generic extension methods do not show up in AutoComplete.

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#11166]
**Version Used**: 
Visual Studio 2015 Update 2.

**Steps to Reproduce**:
Put this code into your IDE:

````
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WpfApplication3.Errors {
    public static class TestClass {
        public static void Test() {
            var Instance = new BaseClass<int>();
            //Typing "Instance." does not show the "SetMember" function listed in AutoComplete, but it still compiles.
            Instance.SetMember(32);
        }
    }


    public static class Extensions {

        public static BC SetMember<BC, TMember>(this BC This, TMember NewValue) where BC : BaseClass<TMember> {
            This.Member = NewValue;
            return This;
        }

    }

    public class BaseClass<TMember> {
        public TMember Member { get; set; }
    }

}

````
**Expected Behavior**:
Typing "Instance." shows the "SetMember" extension method in the drop down list.

**Actual Behavior**:
The "SetMember" extension method does not show up.

**Comment by gafter** [comment]
Let us know if this turns out to be due to misbehavior of any compiler APIs.

**Comment by rchande** [comment]
@gafter: The IDE is calling LookupSymbols with `BaseClass<int32>` as the `container` and `includeReducedExtensionMethods:true`. It's not returning `SetMember`--sounds like a compiler issue?

**Comment by rchande** [comment]
This is the IDE code: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Recommendations/CSharpRecommendationService.cs,523
