### ISSUE TITLE
[Request for help] using DeclarePublicAPIAnalyzer in third-party code?

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/roslyn#11167]
Hi! I've noted that [this page](https://github.com/dotnet/roslyn/blob/master/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md) mentions analyser that uses PublicAPI.Shipped.txt and PublicAPI.Unshipped.txt to detect breaking public API changes. As far I can see it's a DeclarePublicAPIAnalyzer.

We have a project with a large public API surface that we want to freeze. Is it possible to use the DeclarePublicAPIAnalyzer in our case? If yes, what steps should I perform?

**Comment by gafter** [comment]
@jaredpar Can you please direct @ig-sinicyn to more information on the public API analyzer?

**Comment by jaredpar** [comment]
@ig-sinicyn the actual analyzer lives over here:

> https://github.com/dotnet/roslyn-analyzers

Lets move the conversation over there.  A brief answer though: this analyzer was designed specifically for Roslyn and it has a couple of assumption about our versioning model baked in. It probably needs a bit of work before it could be made more general purpose.

**Comment by ig-sinicyn** [comment]
@jaredpar sorry for late reply and thanks for the answer!

I'll create an issue in the roslyn-analyzers. Should I close this one?

**Comment by jaredpar** [comment]
Yeah let's close this one and let the other be the primary.
