### ISSUE TITLE
Add chained comparison

### ISSUE THREAD

**Issue by arhont375** [dotnet/roslyn#11176]
This tiny request for simplifiing equl comparision it is possible to make chained comparison?
I said about^
`if (a == b == c)
{
//do something
}`
or 
`if (a > b > c)
{
// do something
} `

It's very clear and can save some time for understanding or typing.

**Comment by gafter** [comment]
That syntax is already legal. For example, the following program prints `True`. This proposal would change that, and therefore it would change the behavior of existing code.

```cs
        bool b = true, c = false, d = false;
        Console.WriteLine(b == c == d);
```

**Comment by alrz** [comment]
Also a dup of #136
