### ISSUE TITLE
[MU Testing ] PCL pointed to .netstandard1.5 fails at Runtime

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#11177]
**Whats installed**

Dev14 U2 RTW: \\cpvsbuild\drops\VS\d14rel\layouts\x86ret\25123.00.00\enu\vs\enterprisetrial30\dvd\ 
Micro update :\\mlangfs1\public\rchande\VS14-KB3151378\VS14-KB3151378.exe

**Repro Steps**

1. Create a PCL and target to .NetStandard1.5 
2. Add a static method to the same
3. Create console application and point to 4.6.2
4. Reference PCL from console application 
5. Call the static method in the main 
6. Build 
7. Set console application as startup project and Run 

**Expected**
You can call the pcl method and every thing works 

**Actual**
![mu1](https://cloud.githubusercontent.com/assets/12449387/15120213/7e099e68-15c9-11e6-8719-7dcd6fc4cf6e.JPG)

**Note**:
This failure is seen only if we point to .netstandard1.5 , any thing lower works.

**Comment by jinujoseph** [comment]
@rchande

**Comment by Pilchie** [comment]
@jinujoseph: Do you see warnings about mismatching references?  What happens if you add `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>` to the console app's .csproj file?

**Comment by jinujoseph** [comment]
@Pilchie , I don't see any warning , errorlist and output is clean ..
<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>  is already set

**Comment by Pilchie** [comment]
+ @ericstj - Is this expected?

**Comment by ericstj** [comment]
We have a coreFx issue tracking it: https://github.com/dotnet/corefx/issues/7702

Something is tripping up RAR generating bindingRedirects.

**Comment by DustinCampbell** [comment]
Resolving as external since CoreFX is already tracking the problem.

**Comment by ericstj** [comment]
Actually I might have misspoke on this one.  I think the problem here is that the desktop project is still using packages.config, so it doesn't get any of the packages used by the PCL.  Can you add a project.json to the desktop app and see if it fixes this.

**Comment by jinujoseph** [comment]
Desktop app referencing to portable lib need not have project.json right?
any thing other than NetStandard1.5 works fine without project.json. I don't think this is related to project.json file. I have added project.json and that did not seems to have any effect.
