### ISSUE TITLE
Remove System.Xml.XmlDocument dependency

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn#11188]
While investigating the steps for #9769, I did not actually find any references to the JsonDataContractSerializer in project.json  or nuspec files. However, the original issue with JsonDataContractSerializer mentioned its dependency on XmlDocument and I do see System.Xml.XmlDocument in project.json and nuspec files. The usage of XmlDocument appears to be very minimal (tests only) and can likely be switched easily to XDocument.

**Comment by jaredpar** [comment]
@nguerrera  What value gets added here if we remove this?  The longer term POR is to switch to the Net Standard 1.3 / 2.0 meta package.  At that point we'd get this included anyways as an available reference.  Hence not sure of the value of removing it now.

**Comment by nguerrera** [comment]
I thought I had replied already. Just for the record, I agree with the conclusion not to do anything based on POR to move to meta package.
