### ISSUE TITLE
[MU Testing ] Conpatiblity checks happen only when we add a new reference 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#11181]
Whats installed

Dev14 U2 RTW: \cpvsbuild\drops\VS\d14rel\layouts\x86ret\25123.00.00\enu\vs\enterprisetrial30\dvd\ 
 Micro update :\mlangfs1\public\rchande\VS14-KB3151378\VS14-KB3151378.exe

**Steps to Reproduce**:

1.Create a PCL and target to .NetStandard1.4 
2.Add a static method to the same
3.Create console application and point to 4.5.2
4.Reference PCL from console application 
![mu2](https://cloud.githubusercontent.com/assets/12449387/15124862/e160ef1a-15de-11e6-80fe-26023f4c25de.JPG)

This is expected.
5.Now change the console application to compatible version 4.6.1 
6. Add reference 
7. Build and every thing works 
8. Now change the console application version back to 4.5.2 

**Expected **
I would have expected the build to fail with incompatibility failure 

**Actual **
Build/ Execution works with a warning about incompatibility

**Comment by jinujoseph** [comment]
@Pilchie

**Comment by Pilchie** [comment]
I believe this is standard msbuild behavior.  @jasonmalinowski - does that sound right to you?

**Comment by DustinCampbell** [comment]
@Pilchie believes this is by design. @jasonmalinowski, holler if he's wrong again.

**Comment by jasonmalinowski** [comment]
@Pilchie was correct.
