### ISSUE TITLE
[MU Testing ] PCL editing the project.json file doesn't change the project properties 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#11187]
**Whats installed**

Dev14 U2 RTW: \cpvsbuild\drops\VS\d14rel\layouts\x86ret\25123.00.00\enu\vs\enterprisetrial30\dvd\ 
Micro update :\mlangfs1\public\rchande\VS14-KB3151378\VS14-KB3151378.exe

**Steps to Reproduce:**
Create a pcl with below selection and that generated the correcponding project.json file 
![mu3](https://cloud.githubusercontent.com/assets/12449387/15127639/569efc88-15ec-11e6-9952-1bf3980b5d24.JPG)

Edit the project.json file and point to profile 7 
"frameworks": {
    ".NETPortable,Version=v4.5,Profile=Profile7": {}
  }

Compile shows this error 

![mu4](https://cloud.githubusercontent.com/assets/12449387/15127703/9f8d20c8-15ec-11e6-81a7-ef070c5b9022.JPG)

**Comment by DustinCampbell** [comment]
Unfortunately, the information is duplicated between the project file and the project.json, and changing directly in the project.json won't update the .csproj. The UI needs to be used. `<editorial>`It's an unfortunate design. :cry:`</editorial>`
