### ISSUE TITLE
[MU Testing ] PCL with profile 7 switched to .netstandard and back puts the project to profile111

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#11189]
**Whats installed**

Dev14 U2 RTW: \cpvsbuild\drops\VS\d14rel\layouts\x86ret\25123.00.00\enu\vs\enterprisetrial30\dvd\ 
Micro update :\mlangfs1\public\rchande\VS14-KB3151378\VS14-KB3151378.exe

**Steps to Reproduce:**

Create a PCL with below selection , which adds a project.json file with profile 7 in the framework
![mu5](https://cloud.githubusercontent.com/assets/12449387/15127978/1712bf94-15ee-11e6-8059-a076d66c1727.JPG)

Now change the "Target Platform standard"  to 1.1 and then change it immediately back to "Target Portable Class Library Profile"
![mu6](https://cloud.githubusercontent.com/assets/12449387/15128059/83fabc60-15ee-11e6-911c-a116ab0f5d38.JPG)

Removing the Windows phone 8.1 puts it back to profile 7 but is it expected ?

**Comment by DustinCampbell** [comment]
@rchande, is this expected?

**Comment by rchande** [comment]
@jinujoseph @DustinCampbell This is expected. Every netstandard version converts back to a specific set of PCL targets without considering what you profile you converted from originally.

**Comment by jinujoseph** [comment]
@rchande , Ah i see ..does that mean it will add in more dependencies with out user  actually asking for it ? in this case Windows Phone 8.1.
