### ISSUE TITLE
Sane errors for merge-conflict markers

### ISSUE THREAD

**Issue by sabastiaan** [dotnet/roslyn#11185]
Inspired by what gcc recently added I wondered if we could also have sane errors for merge conflicts markers?

example
error: version control conflict marker in file
 <<<<<<< HEAD
 ^~~~~~~

**Comment by AdamSpeight2008** [comment]
Have them treated has compiler directives.
```
<<<<<<< HEAD

^~~~~~~
```

**Comment by Suchiman** [comment]
duplicates #5028
