### ISSUE TITLE
Extract Method refactoring should refactor tuples even without System.ValueTuple type

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#11196]
The repro is the test below from `ExtractMethodTests.cs`. The refactoring should produce a proper tuple type, not `object` type.

In short, the round-tripping of `System.ValueTuple (missing)` into a `SymbolKey` and back produces `ValueTuple (missing)` rather than `System.ValueTuple (missing). Without`System`, a tuple symbol cannot be created from this underlying type, as it is not recognized as tuple-compatible.

More info:

`(int, int)` has underlying type `System.ValueTuple` which is an error type. When that type is described by a `SymbolKey` it is an `ErrorTypeSymbolKey` with various containers for the namespace. The top-most container has an "assembly" namespace kind.

This means that when the Symbol key gets resolved back to a symbol by the refactoring framework, it will try to resolve `System` within the assembly (which it won't find, it only exists in the compilation, not the assembly or module), then it will try to resolve `ValueTuple` (without `System`). But `ValueTuple` is not recognized as tuple-compatible, because it is missing a `System` namespace. 

See `ResolveErrorTypes` and notice that it doesn't pass any container in this fallback case: `CreateErrorTypeSymbol(compilation, null, _name, _arity)`.

Aleksey suggested that when it could not resolve the container, the refactoring framework should still make one and pass it into `CreateErrorTypeSymbol`.

This is related to #11160. 

Other tests have been marked with `[WorkItem(11196, "https://github.com/dotnet/roslyn/issues/11196")]` as well. When this issue is resolved, those tests won't need to include the source code for ValueTuple anymore.

``` C#
        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsExtractMethod), Test.Utilities.CompilerTrait(Test.Utilities.CompilerFeature.Tuples)]
        public async Task RefactorWithoutSystemValueTuple()
        {
            await TestAsync(
@"class Program { static void Main ( string [ ] args ) { [| var x = (c: 1, d: 2); |]  System . Console . WriteLine ( x.c ); } } ",
@"class Program { static void Main ( string [ ] args ) { object x = {|Rename:NewMethod|}(); System.Console.WriteLine(x.c); } private static object NewMethod() { return (c: 1, d: 2); } }", 
index: 0,
parseOptions: TestOptions.Regular.WithTuplesFeature(),
withScriptOption: true);
        }
```

**Comment by DustinCampbell** [comment]
Not sure why this is on IDE at this point. Compiler should probably take a look? Note that the suggestion may not even be possible. I don't believe `CreateErrorTypeSymbol` is a public API.

**Comment by jcouv** [comment]
@DustinCampbell 
The refactoring code already invokes `CreateErrorTypeSymbol` (which is public API). The problem is that it passes a `null` parameter as the second parameter, which in this case will return `ValueTuple` error type instead of `System.ValueTuple`. That's why I assigned to IDE.

If there you do need a new compiler API to make it work, let me know.

**Comment by DustinCampbell** [comment]
No worries -- I didn't remember where we landed with that API. At one point, there was an effort to make it internal.

**Comment by jcouv** [comment]
This was fixed in IDE layer by https://github.com/dotnet/roslyn/pull/16232.
There is a follow-up issue to improve the underlying compiler API to accept an error type as an underlying type (if it's named "ValueTuple").
