### ISSUE TITLE
Source Generators: IDE keyword recommender should know about "replace"

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#11191]
member declarations now can start with "replace".
Keyword recommender should not force that into things like  "DecoderReplacementFallback"

**Comment by DustinCampbell** [comment]
Moving language feature bug to compiler. @jaredpar as FYI

**Comment by VSadov** [comment]
It is actually fixed by the 
https://github.com/dotnet/roslyn/pull/11231
