### ISSUE TITLE
[MU Testing ] PCL (netstandard) referencing another PCL (profile) causes compatiblity issue

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#11200]
**Whats installed**

Dev14 U2 RTW: \cpvsbuild\drops\VS\d14rel\layouts\x86ret\25123.00.00\enu\vs\enterprisetrial30\dvd\ 
Micro update :\mlangfs1\public\rchande\VS14-KB3151378\VS14-KB3151378.exe

**Steps to Reproduce:**

Create two separate pcl with identical configuration (pcl3 & pcl4) 

![image](https://cloud.githubusercontent.com/assets/12449387/15129446/795f2180-15f6-11e6-912b-c76e1f22dd3f.png)

Make sure one can reference another.
then remove the reference and now change pcl3 to "Target .Net platform standard"
 By default it picks .Netstandard1.0
Add the reference again 

![image](https://cloud.githubusercontent.com/assets/12449387/15129529/fd100058-15f6-11e6-841c-cd46ec5ee84b.png)

**Comment by DustinCampbell** [comment]
@Pilchie sez, "we probably shouldn't block this reference since it should work if the user adds an import clause to their project.json for the profile."

**Comment by rchande** [comment]
This should be fixed. Can you verify?

**Comment by jinujoseph** [comment]
Do u have a MU with the fix ? how do  i pick the fix ?

**Comment by rchande** [comment]
Just sent mail, it may still be in my outbox.

**Comment by jinujoseph** [comment]
Verifying in Verified this on build 14.0.25323.00 update 3 RC 

This lets me reference but build fails with warning 
warning MSB3274: The primary reference "C:\Projects\net_PCL\pcl1\bin\Debug\pcl1.dll" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile49".


![new1](https://cloud.githubusercontent.com/assets/12449387/15522226/d8066cfe-21c5-11e6-85ff-6f588979b40f.JPG)

**Comment by rchande** [comment]
@jinujoseph, that's a known issue, tracked by https://github.com/dotnet/roslyn/issues/11067
