### ISSUE TITLE
IntelliSense stopped working after `fixed` statements

### ISSUE THREAD

**Issue by CnSimonChan** [dotnet/roslyn#11213]
**Version Used**: 

Visual Studio 2015 Update 2 *and* Newest `features/patterns` branch.

**Steps to Reproduce**:

1. Create a new C# project and allow unsafe code
2. Type the following code:

        unsafe
        {
            var buffer = new byte[100];
            fixed (byte* b = buffer) |
        }

3. Press `Ctrl + J` at `|`

**Expected Behavior**:

IntelliSense pops up a list of available items.

**Actual Behavior**:

Nothing happened.

**And**:

Multiple continuous `fixed` statements should have same indention like `using` statements.

**Comment by DustinCampbell** [comment]
It works if braces are added. I bet this isn't considered a statement context by the IDE (though it should be).

**Comment by lorcanmooney** [comment]
@DustinCampbell you're right, that was the issue.

The formatting/indentation behaviour is also a little weird when a `fixed` statement doesn't have an associated `BlockSyntax`. I've followed the implementation for `using`, and think I've tracked down all the places that need to be updated.
