### ISSUE TITLE
Project System: Stop opening component designer by default

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11236]
Today if you double-click on a type that implements IComponent in Solution Explorer, we open the component designer. 

While that's useful for forms, and user controls, it's not very useful for controls, or other components that contain just code and nothing "designable". 

We should consider open code view by default. Let's pull the telemetry on whom double-click on a component, only to immediately close it and choose View Code.

**Comment by paul1956** [comment]
That will make working with Forms (and user controls) more difficult. Can you have two defaults, one for things what make sense (at least forms) and one where code view would be better.

**Comment by davkean** [comment]
Sorry - I didn't make it clear in the original issue, "Forms" and "UserControls" should continue to open in the designer by default, I'm only talking about things that get the "component designer" not the user control/winforms designer

**Comment by davkean** [comment]
As part of this - this would cover the automatically adding of `<SubType>Component</SubType>` to components.

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#39
