### ISSUE TITLE
Expand analyzer analysis to compilation level

### ISSUE THREAD

**Issue by Vannevelj** [dotnet/roslyn#11232]
This comes from https://github.com/dotnet/roslyn/issues/3394#issuecomment-218290922

> I could really use this [_API to find references to a symbol_] for a few analyzers I've written so far.
> 
> **NonEncapsulatedOrMutableFieldAnalyzer** (https://github.com/VSDiagnostics/VSDiagnostics/issues/292):
> I need to find all the references (in this class and outside of it) to a specific field so I can determine if it is ever passed as `ref` or `out`. If it is, I can't change it to a property (which is what the corresponding code fix does).
> 
> **RedundantPrivateSetter** (https://github.com/VSDiagnostics/VSDiagnostics/issues/58): 
> I have to find out whether the property is being set somewhere or not. Now I manually look through all the nodes in the inner class but accounting for partial classes and all that jazz becomes cumbersome.

@jmarolf suggested the following API:

```csharp
public static Task<IEnumerable<ReferencedSymbol>> FindReferencesAsync(
            ISymbol symbol,
            Compilation compilation,
            CancellationToken cancellationToken = default(CancellationToken))
```

Relevant comment by @srivatsn 

> I don't think you want a SymbolFinder like API in the compiler layer - it's going to go through the entire compilation on demand and kill analyzer perf. I think this issue is about adding a `RegisterSymbolReferenceAction(callback, ISymbol)`. The callback will get called whenever there's a reference to the passed in symbol. That way the references are computed as the compiler goes through the project and any cumulative actions can be taken at `CompilationEnd`.

**Comment by srivatsn** [comment]
For the perf reason mentioned above, I don't think we want to have a FindReferences api at the compiler layer. We'll continue to use #3394 to track RegisterSymbolReferenceAction API.
