### ISSUE TITLE
Feature Request: Private extension methods

### ISSUE THREAD

**Issue by chaoaretasty** [dotnet/roslyn#11248]
Currently extension methods have to be public methods on public static classes but this means an extension method is available everywhere (internal and private extension methods accessible from public ones not withstanding and yes you can namespace them but with many tools offering automatic using statements on intellisense an extension method is constantly available anywhere in your code).

This becomes a problem when dealing with fluent classes, particularly complex configuration objects where you might have several common settings you want to reuse in a specific context. Currently the choices are to break DRY and repeat them all, to have a public extension method despite not being applicable elsewhere or to mix fluent and non-fluent code.

Allowing extension methods to be declared in a private nested class would solve this

```
public class ToExtend
{

}

public class MyClass {
	public DoThing() {
		var a = new ToExtend();
		//This would work
		a.ExtensionMethod()
	}
	private static NonPublicExtensions {
		public static ToExtend ExtensionMethod (this ToExtend toExtend) {
			//Do some work
			return toExtend;
		}
	}
}

public class MyOtherClass {
	public DoThing(){
		var a = new ToExtend();
		//This would not work as NonPublicExtensions is not visible
		a.ExtensionMethod()
	}
}
```

**Comment by alrz** [comment]
Dup of #4565
