### ISSUE TITLE
Spell checker/Namespace resolver should have the same order regardless of whether namespace import/fully qualify

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11240]
1. Add a reference to WPF/WinForms and attempt to resolve TextBox
``` VB
Namespace Microsoft.VisualStudio.Editors.PropertyPages

    Public Class TextBoxEx
        Inherits TextBox

    End Class

End Namespace
```

![image](https://cloud.githubusercontent.com/assets/1103906/15172073/4503da44-1708-11e6-8378-c07b82d0e6db.png)

The order should the same regardless of whether i'm importing the name or fully qualifying the namespace.

I prefer the order whether we put namespaces on top in alphabetical order, followed by nested types.

**Comment by CyrusNajmabadi** [comment]
With my fix:

![image](https://cloud.githubusercontent.com/assets/4564579/15792494/75e9940e-2992-11e6-9f06-3f072914300a.png)

**Comment by davkean** [comment]
:+1:
