### ISSUE TITLE
Accessors of readonly/writeonly properties are marked as ImplicitlyDeclared for VB, causing no analyzer callbacks for these symbols

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#11258]
VB compiler marks the accessors of readonly/writeonly properties with no body (e.g. `Public ReadOnly Property MyProperty As Integer = 0` as ImplicitlyDeclared, while the C# compiler which marks the getter for ArrowExpression property (e.g. `public int ArrowExpressionProperty => 0;`) as not implicitly declared.

A noticeable effect of this is that we never make callbacks into symbol analyzers for accessors of readonly/writeonly properties in VB.
Analyzer driver skips callbacks for all implicitly declared symbols, and hence the DeclarePublicAPIAnalyzer never gets a callback for these accessor methods in VB (see https://github.com/dotnet/roslyn-analyzers/issues/821).

**Comment by AlekseyTs** [comment]
I believe behavior of the compiler is By Design - there is no syntax that corresponds to either accessor. The ``` = 0``` is an initializer and it is used to initialize the property inside constructor.

@mavasani FYI
