### ISSUE TITLE
You Cannot Rename This Element

### ISSUE THREAD

**Issue by markolbert** [dotnet/roslyn#11250]
Microsoft Visual Studio Professional 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038
Installed Version: Professional
1. Rename an element (e.g., class)
2. Try to rename another element
3. Error produced

Expected Behavior: I should be able to continue editing element names

Actual Behavior: cannot rename element. Cannot, for that matter, edit the file that the unnameable element is in.

The only workaround I've found is to quit and restart Visual Studio...which is annoying :)

**Comment by SLaks** [comment]
It sounds like you're still inside the first rename flow.  Try pressing Escape.

**Comment by matteliot** [comment]
Same thing happened to me- I pressed esc, etc, without any difference.

> Microsoft Visual Studio Enterprise 2015
> Version 14.0.25123.00 Update 2
> Microsoft .NET Framework
> Version 4.6.01055
> 
> Installed Version: Enterprise
> 
> Architecture and Modeling Tools   00322-80000-00000-AA397
> Microsoft Architecture and Modeling Tools
>     
> UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.
> 
> Visual Basic 2015   00322-80000-00000-AA397
> Microsoft Visual Basic 2015
> 
> Visual C# 2015   00322-80000-00000-AA397
> Microsoft Visual C# 2015
> 
> Visual C++ 2015   00322-80000-00000-AA397
> Microsoft Visual C++ 2015
> 
> Application Insights Tools for Visual Studio Package   5.2.60328.3
> Application Insights Tools for Visual Studio
> 
> ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11106.0
> ASP.NET and Web Tools 2015.1 (Beta8)
> 
> ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
> For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563
> 
> ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
> For additional information, visit http://www.asp.net/
> 
> Common Azure Tools   1.7
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> GitHub.VisualStudio   1.0
> A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> Microsoft Azure Mobile Services Tools   1.4
> Microsoft Azure Mobile Services Tools
> 
> NuGet Package Manager   3.4.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> PreEmptive Analytics Visualizer   1.2
> Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.
> 
> Python Tools for Visual Studio   2.2.40315.00
> Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.
> 
> Python Tools for Visual Studio - Django Integration   2.2.40315.00
> Provides templates and integration for the Django web framework.
> 
> Python Tools for Visual Studio - Profiling Support   2.2.40315.00
> Profiling support for Python projects.
> 
> SQL Server Data Tools   14.0.60311.1
> Microsoft SQL Server Data Tools
> 
> Text Macros for Visual Studio 2012/2013/2015   1.7
> Brings back text-editing macro support in Visual Studio 2012/2013/2015
> 
> TypeScript   1.8.30.0
> TypeScript tools for Visual Studio
> 
> Workflow Manager Tools 1.0   1.0
> This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by marknn3** [comment]
Same for me.
First error after refactor rename was "unexpected null". 
Then I closed all documents. Now the error is "you cannot rename this element".

Microsoft Visual Studio Community 2015
Version 14.0.25424.00 Update 3
Microsoft .NET Framework
Version 4.6.01586

**Comment by davidrensh** [comment]
"you cannot rename this element" happens at angular2 project when there are var yourVar: string and template reference {{yourVar}}, then you cannot rename. Otherwise, it's perfect.

**Comment by rchande** [comment]
@davidrensh Is that in a TypeScript file?

**Comment by Pilchie** [comment]
Sorry, we've been unable to reproduce this so far.

**Comment by Montago** [comment]
I just got this error... 

I renamed 4 other methods in a static class in TypeScript... but the 5th refused !

**Comment by therohansanap** [comment]
Same error

**Comment by bugybunny** [comment]
Visual Studio 15.8.9, ASP.NET MVC5 project. I just created a new local variable in a static method, the whole line was already legal C# (can‘t remember if I‘ve already saved the file but I guess so). Then I pressed Ctrl+R, Ctrl+R and at the second R press (on keydown) I got the error that an error happened and I should have a look at the ActivityLog.xml in %appdata%/Microsoft/VisualStudio/15.0…

The most recent entry was

```
  <entry>
    <record>1248</record>
    <time>2018/11/12 14:19:19.018</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Collections.Generic.KeyNotFoundException: context&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.Undo.VsUndoHistoryRegistry.GetHistory(Object context)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioTextUndoHistoryWorkspaceServiceFactory.TextUndoHistoryWorkspaceService.TryGetTextUndoHistory(Workspace editorWorkspace, ITextBuffer textBuffer, ITextUndoHistory&amp; undoHistory)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.InlineRename.VisualStudioInlineRenameUndoManagerServiceFactory.InlineRenameUndoManager.CreateStartRenameUndoTransaction(Workspace workspace, ITextBuffer subjectBuffer, InlineRenameSession inlineRenameSession)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.OpenTextBufferManager..ctor(InlineRenameSession session, ITextBuffer subjectBuffer, Workspace workspace, IEnumerable`1 documents, ITextBufferFactoryService textBufferFactoryService)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.TryPopulateOpenTextBufferManagerForBuffer(ITextBuffer buffer, IEnumerable`1 documents)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.InitializeOpenBuffers(SnapshotSpan triggerSpan)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession..ctor(InlineRenameService renameService, Workspace workspace, SnapshotSpan triggerSpan, IInlineRenameInfo renameInfo, IWaitIndicator waitIndicator, ITextBufferAssociatedViewService textBufferAssociatedViewService, ITextBufferFactoryService textBufferFactoryService, IEnumerable`1 refactorNotifyServices, IAsynchronousOperationListener asyncListener)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameService.StartInlineSession(Document document, TextSpan textSpan, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.ExecuteRenameWorker(RenameCommandArgs args, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.ExecuteCommand(RenameCommandArgs args, CommandExecutionContext context)&#x000D;&#x000A;   at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)&#x000D;&#x000A;   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.&lt;&gt;c__DisplayClass14_1`1.&lt;Execute&gt;b__1()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call, Predicate`1 exceptionFilter)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```

Every try to rename the local variable later resulted in a error dialog with "You Cannot Rename This Element". I pressed Esc, Enter etc. to make sure I‘m not in a renaming. 
Only restarting Visual Studio solved my problem. Maybe other people also first had such an error.

**Comment by soydivision** [comment]
Just use _Ctrl + h_ for replacing.
