### ISSUE TITLE
Introduce immutable modifier

### ISSUE THREAD

**Issue by biqas** [dotnet/roslyn#1125]
Introducing immutable modifier on class, field, property, event, indexer and method level.

Benefits could be:

- could help express the intention to better understand the class design and behavior
- could make some assumption/prediction/facts for garbage collection.
- could have some inference chain for not mixing immutable with mutable things.
- could have positive effects for lock's

```CSharp
public immutable class A
{
    // so everything is immutable in the class
    public A Foo()
    {
        // not allowed.
        // return this;

        return new A();
    }
}
```

```CSharp
public class A
{
    private immutable int fieldA = 3;

    public A()
    {
        // allowed
        this.fieldA = 0;
    }

    public immutable A Foo()
    {
        // not allowed !!!
        this.fieldA = 42;

        return new A();
    }
}
```

So chain of immutable must be inspected to guarantee immutable remains immutable.

**Comment by pharring** [comment]
@biqas Thanks for the proposal. Immutability and immutable types are discussed in #159. Please review it and see if it covers all the scenarios you were thinking of. If there's something else, it's best to discuss it there.

Note that ```readonly``` on fields already takes care of your second example.
