### ISSUE TITLE
Make sure all results are uploaded to job group Roslyn-master

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#11253]
Right now, we have results in job groups Roslyn-master, Roslyn-stabilization, Roslyn-future, Roslyn-HEAD, etc (basically, every branch we've ever checked out).  We should figure out where this value is being picked up from and set it to **Roslyn-master** for all runs based on master.

**Comment by gafter** [comment]
@KevinH-MS Can you please provide more information in the description of this issue?

**Comment by KevinH-MS** [comment]
When we move to triggering runs from Jenkins, we won't be uploading to Benchview (at least for the time being), so closing for now.
