### ISSUE TITLE
Option to insert * in multiline comment does not persist

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#11264]
It looks like the option to "Insert * at the start of new lines when writing /* */" does not actually persist. There have been a number of issues filed on Microsoft Connect reporting this issue:

* https://connect.microsoft.com/VisualStudio/feedback/details/2576628/settings-for-comments-in-editor-help-not-saving
* https://connect.microsoft.com/VisualStudio/feedback/details/2645377/comment-handling-broken-in-update-2

**Comment by DustinCampbell** [comment]
@diryboy, did you want to take a look?

**Comment by diryboy** [comment]
Sure, I believe the second issue was fixed in #11073 yesterday. I pretty much copy & modified the code for the settings, let me see what was missing.
