### ISSUE TITLE
support simple pattern matching, start with %2 to &1 

### ISSUE THREAD

**Issue by SunnyWar** [dotnet/roslyn#11268]
I cannot re-open #11261. so I'm posting it AGAIN. GRRRRR!!!!

@gafter  didn't get it so I'll explain it in simple terms...

The good back end compiler will recognized patterns and substitute other code that can be or is optimized. In the example below Roslyn should see (x%2) and recognize it that an integer is simply be checked for odd or evenness. Is should substitute (x & 1). This makes is easier for the JIT'er to optimize the code because the hard work has been done for it.

Second, the main point is that Roslyn or the JIT'er should be doing pretty much everything listed here (and more): [Introducing a new, advanced Visual C++ code optimizer](https://blogs.msdn.microsoft.com/vcblog/2016/05/04/new-code-optimizer/)

Finally. if this NOT the right place for this problem then please direct me to the right repo. CLI already sent me over here by the way and I'm tired of wasting my time posting the same thing over and over.

Steps to reproduce

compare how the compile deals with x%2 versus x&1. It should be the same but isn't.

for (var i = 0; i < iterations; i++) { var x = i%2; if (x == 0) { count++; } } 

Look at the generated assembly for the i%2 part:
 00DE2E13 mov eax,edx

00DE2E15 and eax,80000001h

00DE2E1A jns 00DE2E21

00DE2E1C dec eax

00DE2E1D or eax,0FFFFFFFEh

00DE2E20 inc eax

00DE2E21 test eax,eax

00DE2E23 jne 00DE2E26 

compare it to this:
 for (var i = 0; i < iterations; i++) { var x = i & 1; if (x == 0) { count++; } } 

00672E9B test edx,1

00672EA1 jne 00672EA

Expected behavior

recognized the %2 pattern and replace it with &1 so that it can be optimized.

Actual behavior

It's not optimal.

**Comment by SunnyWar** [comment]
Sorry for sounding irritated. I get that way when I'm irritated. 

I'll try to be more verbose... it's well known that the CLI is not an optimized compiler. It cares more about speed of compiling than it does about the speed of the executable. So getting a program to be optimized falls heavily on the shoulders of Rolsyn. Roslyn needs to produce IL that will then produce highly optimized machine code. One of the simplest ways to do this is to _identify patterns in code_ and then _substitute optimizable replacements_. That's what this issue is about.

I showed a simple example that exists in hundreds of places in the dotnet code base...the use of %2 to determine if an integer is odd or even can be replaces with &1. In this simple case a simple substitution will produce a more optimal, and identical result.

**Comment by gafter** [comment]
@SunnyWar Yes, this is one of hundreds of optimizations we could do. We do not specialize a multiply by 0, or 1, or 2 either. It is the CLI's job to perform local optimizations of this sort. If it does not do so that is a bug. I'll leave this issue open for you to add any futher comments.

**Comment by svick** [comment]
As far as I know, Roslyn doesn't do many optimizations, because it's expected that the CLR will do them. So, what you're proposing would be a major shift in the design of the .Net ecosystem.

Specifically about your example, what IL do you expect to be generated? Consider that `%2` can't simply be replaced with `&1`, because it has different behavior for negative numbers. (`-1%2 == -1`, but `-1&1 == 1`).

**Comment by gafter** [comment]
@HaloFour Yes, I removed the local optimizations from javac in version 1.3.

**Comment by gafter** [comment]
@SunnyWar You probably want to direct your reports to https://github.com/dotnet/coreclr

**Comment by svick** [comment]
Oh, and it seems that tiered JIT (dotnet/coreclr#4331) is being considered for CoreCLR, which should make aggressive optimizations possible even without .Net Native-like AOT compilation.

**Comment by SunnyWar** [comment]
@svick Go ahead and close this. I learned that that CoreCLR thinks that it's Rosyln's problem and Roslyn thinks this is CoreCLR's problem. That means MS has no idea where to put optimizations in .Net. Very sad. I had such high hopes.

Typically when an optimization is recommend to CoreCLR they respond with, "We could do this but it would impact the assembly load time so we won't"....and another optimization opportunity is lost. There has to be an answer to this conumdrum. One possible answer is to have Roslyn do as much as the heavy lifting as it can and product IL that it knows the CoreCLR will optimize. 

Since the idea of a server JIT'er has been shot down many times...I think this is the _only_ option that is workable today, unless there is another I've not heard of.

Now, concerning the question of negative numbers...just do it for unsigned ints unless you can guarantee the number will always be positive.

**Comment by svick** [comment]
@SunnyWar I don't have the power to close this issue. I believe only the original author (you) or someone from MS (not me) can do that.

**Comment by SunnyWar** [comment]
@svick good to know. thanks.
