### ISSUE TITLE
Build Server cannot locate Microsoft.CodeAnalysis 1.2

### ISSUE THREAD

**Issue by twenzel** [dotnet/roslyn#11262]
**Version Used**: Microsoft.CodeAnalysis.Common.1.2.1 (NuGet)

**Steps to Reproduce**:

1. We've updated our custom CodeAnalyzers to the latest NuGet packages
```
<package id="Microsoft.CodeAnalysis.Analyzers" version="1.1.0" targetFramework="portable45-net45+win8" />
  <package id="Microsoft.CodeAnalysis.Common" version="1.2.1" targetFramework="portable45-net45+win8" />
  <package id="Microsoft.CodeAnalysis.VisualBasic" version="1.2.1" targetFramework="portable45-net45+win8" />
  <package id="Microsoft.CodeAnalysis.VisualBasic.Workspaces" version="1.2.1" targetFramework="portable45-net45+win8" />
  <package id="Microsoft.CodeAnalysis.Workspaces.Common" version="1.2.1" targetFramework="portable45-net45+win8" />
  <package id="Microsoft.Composition" version="1.0.30" targetFramework="portable45-net45+win8" />
  <package id="NuGet.CommandLine" version="3.4.3" targetFramework="portable45-net45+win8" developmentDependency="true" />
  <package id="System.Collections.Immutable" version="1.1.37" targetFramework="portable45-net45+win8" />
  <package id="System.Reflection.Metadata" version="1.2.0" targetFramework="portable45-net45+win8" />
```
2. These analyzers are used within our main projects. They're working fine in Visual Studio 2015 Update 2.
3. When our main project is build on the build server (using Jenkins, MSBuild) following error occurs

```
vbc : warning BC42376: Eine Instanz des CHGCodeAnalyzers.Analyzer.VisualBasic.DefineOneOrMoreFieldsForSelectStatementsAnalyzer-Analyzers kann nicht aus xxxxxxx\packages\CHGCodeAnalyzers_VB.1.0.5975.16520\analyzers\dotnet\vb\CHGCodeAnalyzers_VB.dll erstellt werden: File or Assembly "Microsoft.CodeAnalysis, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.. [xxxxx\CHG.iCLASSFW.Maintenance.UI.Win\CHG.iCLASSFW.Maintenance.UI.Win.vbproj]
```

How do I get this to run on a build server using msbuild? Should I update the Build Tools? But there's a version of end-of-2015 only..

When I pack all referenced assemblies (Microsoft.CodeAnalysis.*, System.Collection.Immutable,...) within my Analyzer NuGet package, Visual Studio won't recognize the analyzer any more.

**Comment by srivatsn** [comment]
On your build server you'll need version 1.2 of the compilers as well. You can either install VS 2015 U2 on that machine to get that version of the compilers or you can make your projects use the [Microsoft.Net.Compilers](http://www.nuget.org/packages/Microsoft.Net.Compilers/2.0.0-beta1) package which makes these projects build with a specific version of the compilers.
