### ISSUE TITLE
Add Commit ID to fileversion in assemblies

### ISSUE THREAD

**Issue by paulvanbrenk** [dotnet/roslyn#11272]
By adding the CommitId to the informational fileversion of an assembly it's super issue to sync to the commit used to build that assembly. Is that something you can do? (Preferably the commit from the public repo).

[screenshot since uploading failed](https://onedrive.live.com/redir?resid=61B2A99B031C634!1271480&authkey=!AAcgQZ7J1X7mMTU&v=3&ithint=photo%2cpng)

**Comment by jaredpar** [comment]
Thanks for filing.

This is something i've considered adding for similar reasons.  There are a lot of compiler versions floating around now (especially since we upload nightly builds).  Having this would make it simpler to track the commit it came from.

**Comment by jaredpar** [comment]
@agocke committed this a few weeks ago.  Resolving.
