### ISSUE TITLE
Cannot compile dynamic classes separately using Roslyn and combine them together into an assembly

### ISSUE THREAD

**Issue by npolyak** [dotnet/roslyn#11297]
roslyn-master from May-12, 2016

**Steps to Reproduce**
I have a set of disjoint dynamically written classes, I want to compile (and fix compilation errors) individually. Then I want to combine them into the same assembly. Since they have been already compiled, I do not want to simply pass their syntax trees to the assembly compilation (in order to avoid compiling twice). I was trying to compile them into netmodules, and then use those netmodules as reference to an assembly but the resulting assembly does not have the required types.

Here is my test code (very similar to Roslyn's CompilationEmitTests.MultipleNetmodulesWithPrivateImplementationDetails())
`public class Program
{
public static void Main()
{
    var s1 = @"public class A {internal object o1 = new { hello = 1, world = 2 }; public static string M1() {    return ""Hello, "";}}";
    var s2 = @"public class B : A{internal object o2 = new { hello = 1, world = 2 };public static string M2(){    return ""world!"";}}";
    var s3 = @"public class Program{public static void Main(){    System.Console.Write(A.M1());    System.Console.WriteLine(B.M2());}}";
    var comp1 = CreateCompilationWithMscorlib("a1", s1, compilerOptions: TestOptions.ReleaseModule);
    var ref1 = comp1.EmitToImageReference();

    var comp2 = CreateCompilationWithMscorlib("a2", s2, compilerOptions: TestOptions.ReleaseModule, references: new[] { ref1 });
    var ref2 = comp2.EmitToImageReference();

    var comp3 = CreateCompilationWithMscorlib("a3", s3, compilerOptions: TestOptions.ReleaseExe.WithModuleName("C"), references: new[] { ref1, ref2 });

    var ref3 = comp3.EmitToImageReference();

    IEnumerable<byte> result = comp3.EmitToArray();

    Assembly assembly = Assembly.Load(result.ToArray());

    Module module = assembly.GetModule("C");

    Type prog = module.GetType("Program");

    object instance = Activator.CreateInstance(prog);

    MethodInfo method = prog.GetMethod("Main");

    method.Invoke(null, null);
}

public static ImmutableArray<byte> ToImmutable(this MemoryStream stream)
{
    return ImmutableArray.Create<byte>(stream.ToArray());
}

internal static ImmutableArray<byte> EmitToArray
(
    this Compilation compilation,
    EmitOptions options = null,
    Stream pdbStream = null
)
{
    var stream = new MemoryStream();

    if (pdbStream == null && compilation.Options.OptimizationLevel == OptimizationLevel.Debug)
    {
        pdbStream = new MemoryStream();
    }

    var emitResult = compilation.Emit(
        peStream: stream,
        pdbStream: pdbStream,
        xmlDocumentationStream: null,
        win32Resources: null,
        manifestResources: null,
        options: options);

    return stream.ToImmutable();
}
public static MetadataReference EmitToImageReference(
    this Compilation comp
)
{
    var image = comp.EmitToArray();
    if (comp.Options.OutputKind == OutputKind.NetModule)
    {
        return ModuleMetadata.CreateFromImage(image).GetReference(display: comp.AssemblyName);
    }
    else
    {
        return AssemblyMetadata.CreateFromImage(image).GetReference(display: comp.AssemblyName);
    }
}

private static CSharpCompilation CreateCompilationWithMscorlib(string assemblyName, string code, CSharpCompilationOptions compilerOptions = null, IEnumerable<MetadataReference> references = null)
{
    SourceText sourceText = SourceText.From(code, Encoding.UTF8);
    SyntaxTree syntaxTree = SyntaxFactory.ParseSyntaxTree(sourceText, null, "");

    MetadataReference mscoreLibReference = AssemblyMetadata.CreateFromFile(typeof(string).Assembly.Location).GetReference();

    IEnumerable<MetadataReference> allReferences = new MetadataReference[] { mscoreLibReference };

    if (references != null)
    {
        allReferences = allReferences.Concat(references);
    }

    CSharpCompilation compilation = CSharpCompilation.Create
    (
        assemblyName,
        new[] {syntaxTree},
        options : compilerOptions,
        references: allReferences
    );

    return compilation;
}
}`

**Expected Behavior**:
I expected the compiled dynamic Program to run and print "Hello World"

**Actual Behavior**:
It crashes with an exception stating that it cannot find classes A and B located in the two net modules.

**Comment by 0xd4d** [comment]
You must call `LoadModule` before the netmodules need to be accessed

```C#
assembly.LoadModule("a1.netmodule", a1_netmodule_bytes);
assembly.LoadModule("a2.netmodule", a2_netmodule_bytes);
```

**Comment by npolyak** [comment]
I tried your approach, but apparently I cannot modify an assembly after loading it:


            Assembly assembly = Assembly.Load(result.ToArray());

            assembly.LoadModule("a1", module1);

results in an exception with "Specified file name was invalid." message.

Thanks
Nick

**Comment by 0xd4d** [comment]
You must use the exact name of the netmodule, eg. "a1.netmodule", not "a1"

**Comment by npolyak** [comment]
Amazingly it works!!!
Thank you very much. 
What did you mean by saying that if I saved them to the disk I would not have to do it?
Will Compilation.Emit merge the netmodules into the result, if the output stream is a File stream?

**Comment by npolyak** [comment]
I'll close the issue, since it has been resolved due to 0xd4d answer.

**Comment by pablonardone** [comment]
Hello, can someone summit a complete example of the solution, because I can't make it work.
Thanks.

**Comment by npolyak** [comment]
What exactly does not work?
My code is quite distributed, so it is better that you describe your solution. 
In general first you create the your Modules. You need to compile them with OutputKind NetModule. Make sure there are no compilation errors. 
Then you create an empty assembly. It should reference all the modules you'd created before. To convert a module code into module reference use ModuleMetadata.CreateFromImage(moduleResult.TheResult).GetReference()
method. Also the OutputKind of the assembly should be OutputKind.DynamicallyLinkedLibrary. Also I noticed that for some reason I was using allowUnsafe compilation option set to true for both modules and the assembly. 
Then load the Assembly:
Assembly myAssembly = Assembly.Load(result);
where the result is a byte array of the assembly obtained at the previous step. 
Finally do
myAssembly.LoadModule(<moduleName>, moduleResult);
for each of the modules.
Hope it will help.

**Comment by pablonardone** [comment]
Thank you Nick for your replay. Sorry for not being clear. I just made a new repository at [github](https://github.com/pablonardone/RoslynTest1) with your code in order to test it and share it with you, hoping that you can test it as well. What does not work is the LoadModule that fails with System.IO.FileLoadException.
Thank you very much.

**Comment by npolyak** [comment]
I'll try to get back to you on this. Give me a day or two.

**Comment by npolyak** [comment]
Hey Pablo,
sorry for the delay, I finally made it work! (it only took me half a day:) )
the working solution is under https://github.com/npolyak/SimpleRoslynAssembly/tree/master/RoslynTest1
The key is that Every time you call Emit (in our case within EmitToArray), the emitted result is slightly different (perhaps due to the versioning). So the key is that you have to use the same byte array for creating the module and its reference - while in the code above, the reference had its own Emit. As a result the reference hash did not match the module hash resulting in an error. 
Please tell me if my solution works for you.

**Comment by pablonardone** [comment]
Now it's working perfectly!!. Thank your very much Nick.
If you do not mind I'll leave the working code at [github](https://github.com/pablonardone/RoslynTest1) in case it could be useful for someone else.

**Comment by npolyak** [comment]
absolutely! I am writing a small code project article on this topic. will send you a link when done.

**Comment by npolyak** [comment]
https://www.codeproject.com/Articles/1215168/Using-Roslyn-for-Compiling-Code-into-Separate-Net
here is the article - I think you owe me a 5:)

**Comment by npolyak** [comment]
I removed the old repository and added the code from the article instead: https://github.com/npolyak/RoslynAssembly/tree/master

**Comment by pablonardone** [comment]
Great job!!
