### ISSUE TITLE
Proposal: Simplified switch statement

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#11292]
## Proposal: Simplified switch statement

Almost every statement in C# accepts an _embedded-statement_ so that you can use a simplified form when you just need a single statement. Except for `switch`. In expression context, however, we will have `match` which accept a single expression in each `case` label.

``` cs
return e match {
  case T t: t.Foo(),
  case U u: u.Foo(),
};
```

But when you don't need an expression, you will be stuck with `switch` and `break`.

``` cs
switch(e) {
  case T t: t.Foo(); break;
  case U u: u.Foo(); break;
}
```

I want to propose a simplified form of `switch` which only accepts a single statement (from C++):

``` cs
switch(e)
case 1:
case 2: Foo();
```

_EDIT:_ Only a single case body is allowed, because the semicolon is part of the embedded statement.

**Comment by HaloFour** [comment]
I think that the syntax is too similar to the existing `switch` statement and that would result in confusion.

**Comment by alrz** [comment]
@HaloFour That's the point, 
```cs
if(..) F(..); else G(..);
if(..) { F(..); } else { G(..); }
using(..) M(..);
using(..) { M(..); }
switch(..) case 0: F(..), case 1: G(..);
switch(..) { case 0: F(..); break; case 1: G(..); break; }
```
Which part is exactly confusing?

**Comment by svick** [comment]
How terrible would it be to allow using `match` as a statement instead?

**Comment by gafter** [comment]
One part that is confusing is that you have embedded statements without their closing semicolon, which is part of the syntax of the embedded statement itself.

**Comment by alrz** [comment]
@gafter

 That's the reason why C++ doesn't support comma delimited `case` labels. Still, the simple form might be useful.

@svick

 It would make the language "terribly" ambiguous,
```cs
e match { ... } // expression or statement?
.ToString();     // it was an expression
```
C# has separate syntaxes for expression and statements, therefore, the two forms must be distinguishable.

**Comment by svick** [comment]
@alrz How is that different from other expressions that are already allowed as statements, like `new`?

```c#
new object() // expression or statement?
.ToString(); // it was an expression
```

**Comment by alrz** [comment]
@svick It's always an expression, and terminates with a semicolon in an *expression-statement*, even if we allow `match` in a *statement-expression* (besides of being terminated with a semicolon which can be confusing), `case` label bodies remains an expression, so you still can't use `break`, `continue` or `return` in that context because they are heartless statements. Although, I believe allowing these in the expression context can be useful (just like `throw`), e.g.
```cs
do {
  let result = F() match {
    case Some(var value): value,
    case None(): continue,
  };
} while( ... );
```
But since C# is not an expression-based language all of these statements must treated differently to be allowed in an expression context (same work that has been done for `throw`).

**Comment by alrz** [comment]
@svick 

>```cs
e match {
  case T t: t.Foo(),
  case U u: u.Foo(),
};
```

and still if `Foo` returns `void` it won't be compiled just like the following,
```cs
void F(bool b) => b ? Foo() : Foo();
```
