### ISSUE TITLE
Automatic brace completion (and virtual space) not preserved

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#11295]
**Version Used**: 15.0.25302.0, first appeared in Preview 1, still occurring in Preview 2.

**Expected Behavior**:
Disabling automatic brace completion (and enabling virtual space) setting should be preserved - like in VS2015.

**Actual Behavior**:
Automatic brace completion is automatically enabled again and again.
(Virtual space is automatically disabled again and again.)

Repros on all computers I tried but I don't know what triggers the reset. If there is a way how can I find out (like attaching debugger to VS and setting a breakpoint?), I am happy to help.

Additional info: I do not roam settings. I set these settings on All Languages tab.

**Comment by miloush** [comment]
Looks like it would be good to start with when you uncheck automatic brace completion on All Languages, close and re-open the settings, it does not stay unchecked, despite that if you go through individual text editors, it is unchecked in each of them. I believe in 2015 it stayed unchecked.

**Comment by Pilchie** [comment]
@olegtk - these are both core editor settings.  Are you aware of any issues here?

**Comment by olegtk** [comment]
It's a known issue, but it's on a backlog currently. I don't believe it's limited to VS 15, VS 2015 behaves the same.
"All Languages" is a virtual node that represents aggregated results for all language services. It only takes one language service to not follow a convention to get a checkbox "partially checked".
What's the actual impact of this though? Can't you just uncheck it for C# ?

**Comment by miloush** [comment]
Correct I don't mind checkbox in "undetermined state" even if it was a new behavior, the issue is that these settings are periodically reset (at least for C#) and it's currently the most annoying thing in VS15. I can reproduce it in almost all sessions on different computers.

**Comment by olegtk** [comment]
I guess it has something to do with roaming settings (if you sign into VS). Please file a bug via http://connect.microsoft.com/VisualStudio

**Comment by Pilchie** [comment]
@miloush Are you comfortable filing it on connect?

**Comment by miloush** [comment]
@olegtk I do not roam settings (I am rarely signed into VS).

@Pilchie yes I am happy to file at connect, thanks.
