### ISSUE TITLE
How to change the LangVersion used by the compiler?

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#11309]
I'm work on a language feature for VB, which will be language version dependent. So I've update my version of the compiler to include a higher version, to use. Cheekily it is `VisualBasic15`
Modified the CommandLineParser to be aware of the is version.

Everything appears to work When I run I run it in the new instance of VS

Until I try to use it in project.

I've tried including `<LangVersion>15.0</LangVersion>` in the project definition.
```
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{E063EB58-7A0F-41DB-B9C2-1C27D883CF68}</ProjectGuid>
    <OutputType>Exe</OutputType>
    <StartupObject>ConsoleApplication7.Module1</StartupObject>
    <RootNamespace>ConsoleApplication7</RootNamespace>
    <AssemblyName>ConsoleApplication7</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <MyType>Console</MyType>
    <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <LangVersion>15</LangVersion>
  </PropertyGroup>
```
But it uses the VB14.

**Comment by gafter** [comment]
We do not support any new language versions at this time. Use a "feature" flag to control new features. See the existing code to see how that is done. When we support a new version of the language we'll promote the feature to the language version flag.

**Comment by AdamSpeight2008** [comment]
@gafter I could be target an older version, so the question still applies.
