### ISSUE TITLE
PeekAheadForToken can return incorrect information.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#11304]
[PeekAheadForToken](https://github.com/dotnet/roslyn/blob/56f605c41915317ccdb925f66974ee52282609e7/src/Compilers/VisualBasic/Portable/Parser/ParseScan.vb#L205)
If  the following function returns 0, it could be in one of two ways.
```vb
        Private Function PeekAheadFor(Of TArg)(predicate As Func(Of SyntaxToken, TArg, Boolean), arg As TArg, <Out()> ByRef token As SyntaxToken) As Integer
            Dim nextToken = CurrentToken

            Dim i As Integer = 0
            While Not IsValidStatementTerminator(nextToken)
                If predicate(nextToken, arg) Then
                    token = nextToken
                    Return i
                End If

                i += 1
                nextToken = PeekToken(i)
            End While

            token = Nothing
            Return 0
        End Function
```
Found on the first requested token or not found any on the tokens. This conflicting information. was it found or not found?

but when utilised in this function.
```VB
        Private Function PeekAheadForToken(ParamArray kinds As SyntaxKind()) As Integer
            Dim token As SyntaxToken = Nothing
            Dim index = PeekAheadFor(s_isTokenOrKeywordFunc, kinds, token)
            Return index
        End Function
```
That possibility isn't accounted for. 
Eg If it cant find one on the requested tokens. It return `0` but it should return something to indication no matching token found.

**Comment by gafter** [comment]
Please provide a test case where this results in incorrect compiler behavior.

**Comment by gafter** [comment]
The case you're asking about is disambiguated by whether the `<Out()> ByRef token As SyntaxToken` is `Nothing` or not.

**Comment by AdamSpeight2008** [comment]
@gafter 
I pointed that out in the original post, where I was actually mentioning the use site.

**Comment by gafter** [comment]
@AdamSpeight2008 That is not a test case. A test case would be a VB program that is not compiled correctly. You pointed out some dead code in the compiler.
