### ISSUE TITLE
"Go to Implementation" doesn't have a display name in Tools -> Customize

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11300]
![image](https://cloud.githubusercontent.com/assets/1103906/15255419/babf8460-18f0-11e6-902e-d1b404bed49d.png)

**Comment by CyrusNajmabadi** [comment]
@olegtk Is this handled by VisualStudio?  I can't find anything in Roslyn taht would control this.

**Comment by davkean** [comment]
Who defines the command?

**Comment by davkean** [comment]
It's defined here: https://github.com/dotnet/roslyn/blob/7d97db435f1d30285efdc8f77e1d573ea8b5075a/src/VisualStudio/Core/Def/Commands.vsct#L346. Looking around the tree, other commands define "MenuText" that _might_ control it or appear to set `<CommandFlag>TextMenuUseButton</CommandFlag>` (I'm not sure if this works or not).

**Comment by davkean** [comment]
Or maybe `CommandName` I'm not sure.

**Comment by olegtk** [comment]
Yes, CommandName is used in this dialog, see http://alinconstantin.blogspot.com/2011/08/element-in-vsct-files-buttontext.html

**Comment by CyrusNajmabadi** [comment]
Thanks!  I'll fix this :)
