### ISSUE TITLE
Snippet resolved if the keyword matches enum value

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#11303]
Nothing critical, but...
![untitled](https://cloud.githubusercontent.com/assets/10546952/15259366/d0a7479c-1948-11e6-80d9-5452f7b50f29.png)

Is the `Note: Tab twice to insert the 'Struct' snippet.` expected here? The tab twice thing works, but not for any other snippets. Also note that it is actually 'struct' snippet, not 'Struct'.

**Version Used**: 15.0.25302.0

**Comment by SergeyZhurikhin** [comment]
I agree to: AttributeTargets.Class, Enum, Interface, Struct.

In addition, any enum the names of members whose names match the fragments have this behavior:
```C#
enum MyEnum
{
    Class,
    Prop
}
...
MyEnum.Prop|  => [Tab] =>   MyEnum.public int MyProperty { get; set; } 

```

**Comment by Pilchie** [comment]
Is it expected that we match the shortcut case insensitively?

**Comment by dpoeschl** [comment]
It's supposed to be case sensitive (based on the behavior of VS 2013).

**Comment by dpoeschl** [comment]
We always call `IVsExpansion.InsertExpansion` regardless of whether we think we have a snippet shortcut or not, which always does a `StringComparison.CurrentCultureIgnoreCase`.

To achieve case sensitivity, it looks like we'll need to first do a check of the text to see if it matches a known snippet shortcut. 

For the case where tab is hit after some text but the asynchronous snippet load has not completed, we probably have to block on it ourselves. The only other _somewhat_ reasonable alternative I'm considering would be to just send it to `InsertExpansion` like we do today, which will block and then expand case insensitively... this would be easier to implement and test thoroughly on the Roslyn side, but less correct in a tiny fraction of cases -- the time during which the snippets haven't been loaded is usually very short, so the case insensitivity would impact a tiny percentage of snippet expansions, only a small fraction of which would then be annoying in the way described in this bug.

**Comment by Pilchie** [comment]
What about adding something to the API so that the core editor could know what sort of comparison to use?

**Comment by rchande** [comment]
Ping @dpoeschl

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
