### ISSUE TITLE
Quick-fixes which insert #pragma warning disable XXXX are incompatible with previous versions

### ISSUE THREAD

**Issue by Ibmurai** [dotnet/roslyn#1130]
The quick-fix will insert #pragma warnings in the style of:

```
#pragma warning disable CS4096
```

Where the older compiler only understands:

```
#pragma warning disable 4096
```

This is an annoyance...

**Comment by CyrusNajmabadi** [comment]
@jaredpar there seems to have been no other reports of this in 7 years.  I think we can close out.
