### ISSUE TITLE
Move SQM TO AI [Code Lens]

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#11305]
SQM is going away. project system needs to either remove SQM or move to AI.

**Comment by heejaechang** [comment]
related to #10625

**Comment by heejaechang** [comment]
please let me know by 5/16 what is plan for existing SQM (remove, replace)
actual code should be checked in by 7/25

**Comment by heejaechang** [comment]
@balajikris deadline is updated to 7/9

**Comment by heejaechang** [comment]
this is done

**Comment by balajikris** [comment]
thanks for updating..
