### ISSUE TITLE
[IDE, BUG] Indenting within CDATA

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#11314]
If you type a return after the opening brace, within in CDATA node. It indents and aligns on the next line, it shouldn't as XML has signifacant whitespace. Suspect it may also do the same for `{ [ < `
```vb
<![CDATA[(foo
)]]>
```
becomes
```vb
<![CDATA[(
          foo

)]]>
```

**Comment by Pilchie** [comment]
@AdamSpeight2008 We were unable to repro this with VS2015 Update 2.  Can you give a more precise set of steps?
