### ISSUE TITLE
Find reference results don't update the project context, and other confusion

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#11319]
**Version Used**: 14.0.25123.00 Update 2

**Steps to Reproduce**:

1. Open UnicodeCharacterUtilities.cs from the Roslyn code-base.
2. In that file, do a Find All References on `IsIdentifierStartCharacter`
3. Look at the results window, and get really confused.

**Expected Behavior**:

I was quite confused initially since I didn't realise the file was linked into multiple projects, and the different project contexts shown in the results weren't immediately obvious.

1. Some UI affordance should make it clear there are linked files involved, even if that's only making the different project contexts more obvious. It would also help to call out which context I initiated the search from.
2. Double clicking a result from a different project context should switch the editor to the correct project context and, if "Track Active Item in solution Explorer" is enabled, the active item should be updated.
3. The number of results shown in the result window caption should be accurate.

**Actual Behavior**:
![findrefs](https://cloud.githubusercontent.com/assets/13181165/15275561/2cd90d8c-1ac7-11e6-9e5d-90c19b7a3d5a.png)
The search finds uses of the member across all project contexts, but regardless of which result I click on, neither the editor or solution explorer update to the correct context.

Also, the "# matches found" text isn't accurate. It's actually displaying the number of times the file is in the solution - not the number of results.

Possibly related to #903. I find new structure hard to read. If there's any more than a handful of entries, it just becomes a wall of text, to my eyes at least.

**Comment by Pilchie** [comment]
For the context issue, when we added multiple context support, we made a deliberate decision to never change the context "automagically", because we weren't sure we could do reliably do it in all cases, and we thought that it was more consistent to just never switch it automatically than have some things update it automatically and others not :-(

For the presentation, it's definitely related to #903, which we're working on addressing for the next version of Visual Studio along with the platform team.  Tag @markw-t to see this when he gets back from vacation.

**Comment by lorcanmooney** [comment]
> ...because we weren't sure we could do reliably do it in all cases, and we thought that it was more consistent to just never switch...

Understood. Does this apply to the active-item-tracking in solution explorer as well?

**Comment by Pilchie** [comment]
I've never actually looked at the code for that, but I can't imagine it working any other way than by following the document's IVsHierarchy in the IVsRunningDocumentTable, so I assume so.

**Comment by lorcanmooney** [comment]
Ok, sounds like there's nothing to fix here. Closing.
