### ISSUE TITLE
Tuple literals should not be allowed if the corresponding VT cannot be unambiguously looked up.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#11322]
Based on the latest LDM decision:
- Tuple literals are not allowed if the corresponding VT cannot be unambiguously looked up.

I'll submit unit-tests shortly. The tests are passing right now because they reflect existing behavior, but comments are indicating places that should change behavior according to the decision above.

**Comment by AlekseyTs** [comment]
@vsadov, @jcouv FYI.

**Comment by jcouv** [comment]
Fixed by #11389
