### ISSUE TITLE
Conversions between instances of tuple types backed by different VT definitions should be supported.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#11325]
I will submit a unit-test shortly. It reflects the current behavior, but there is a comment indicating where it should be  different.

**Comment by AlekseyTs** [comment]
@vsadov, @jcouv FYI.

**Comment by jcouv** [comment]
This should already work. Vlad will point to some tests.

**Comment by jcouv** [comment]
@AlekseyTs I think this already works. See [this test](http://source.roslyn.io/#Roslyn.Compilers.CSharp.Emit.UnitTests/CodeGen/CodeGenTupleTest.cs,ad9e8fb3901019da).
Can you confirm and resolve if appropriate?

**Comment by AlekseyTs** [comment]
Looks fixed.
