### ISSUE TITLE
Re-generate error log baselines for VSI tests

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#11332]
https://github.com/dotnet/roslyn/pull/11233 moves compiler error logger to a newer version, we need to update the error log baseline in VSI tests once that is merged in.

**Comment by nguerrera** [comment]
#11390 changes version to 1.0.0 and requires a new baseline again. Re-using same issue.

**Comment by nguerrera** [comment]
@mavasani I'm having a tough time with the rebaselining instructions. I think I've followed them, but tests are failing with things looking unrelated. I need your help to debug if you can stop by.

**Comment by nguerrera** [comment]
That closure was generated against a previous rebaseline, but it has since been rebaselined again and all is well so this can stay closed. :)
