### ISSUE TITLE
Adding Existing .xaml files

### ISSUE THREAD

**Issue by reader-man** [dotnet/roslyn#11339]
**Version Used**: VS 2015 u2

**Steps to Reproduce**:

1.  Make a new solution(Blank Xamarin.Forms Portable)
2. Click on the PCL project, and select add Existing item
3. Select any .xaml files you have that are related to xamarin
4. If you add multiple .xaml files, their backing code .cs, will not get included.
5. if you add the .xaml file, one by one, the backing code .cs will be included, but its properties are:

_Build Action: Page
Custom Tool: MSBuild:Compile_
which should not be the default values.

**Expected Behavior**:
It should add multiple .xaml files, and include their backing code .cs file.
also, it should set the .xaml properties as:
_Build Action: Embedded Resource
Custom Tool: MSBuild:UpdateDesignTimeXaml_

**Actual Behavior**:
It adds multiple selected .xaml files without their backing .cs file.
and if you add .xaml file, one by one, it makes its properties as:
_Build Action: Page
Custom Tool: MSBuild:Compile_

**Comment by Pilchie** [comment]
@davkean @rchande Do you know if this is an issue in the PCL flavor?

**Comment by davkean** [comment]
I think we're setting the Build Action explicitly, about not adding their backing .cs files would be csproj.

**Comment by Pilchie** [comment]
At this point, this isn't something that we'll fix in the old project system.  @davkean @srivatsn can you migrate the project system repo?

**Comment by srivatsn** [comment]
Ported to https://github.com/dotnet/roslyn-project-system/issues/525
