### ISSUE TITLE
Issues with Compilation.CreateTupleTypeSymbol API

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#11347]
The current API for `Compilation.CreateTupleTypeSymbol` in [this PR](https://github.com/dotnet/roslyn/pull/11160) has two issues:

1. It supports creation of "tuple" types that should not arise in any correct program, and
2. Exposes a non-language concept of "tuple underlying type", when the language specification says that a tuple type and its underlying type *are the same*.

When creating a tuple type symbol, I propose the supported API should be

```cs
        public INamedTypeSymbol CSharpCompilation.CreateTupleTypeSymbol(
             ImmutableArray<ITypeSymbol> elementTypes,
             ImmutableArray<string> elementNames = default(ImmutableArray<string>),
             IAsemblySymbol containingAssembly = null) ...
```

This creates a tuple type from element types and (optional) element names, optionally specifying the assembly from which the underlying `System.ValueTuple` types should be taken. This corresponds to the source operation of writing a tuple type (in the given assembly), i.e. `(int a, int b)`. When you do that you don't get to select the underlying type; it is automatically taken from the (given or source) assembly's unique `System.ValueTuple` types. This makes the most sense if we require that every tuple type uses "continuation" tuple types from the same assembly. A tuple type with continuations from mixed assembles is not a supported scenario, and so would not be considered a tuple type by the compiler.

Optionally, if we decide that the public API must expose a separate "tuple underlying type" that is different from a "tuple type", we could provide an API to get the corresponding tuple type from its "underlying" type:

```cs
        public INamedTypeSymbol CSharpCompilation.CreateTupleTypeSymbol(
             INamedTypeSymbol underlyingType) ...
```

This would create a tuple type directly from an underlying type, but without specifying element names, element types, or an assembly. This corresponds to the source operation of constructing `System.ValueTuple`, by writing an underlying type, i.e. `System.ValueTuple<int, int>`. When you do that you don't get to select the element names; they are always `Item1`, etc. If the provided type doesn't follow the pattern of what is a valid tuple type (e.g. the continuation of `VT'8` isn't a `ValueTuple` from the same assembly) then it returns null. Such a type is a `NamedTypeSymbol` but not a tuple type. This API might be handy if we decide that it would be useful to support tuple types with modifiers on the element types.

The API in [this PR](https://github.com/dotnet/roslyn/pull/11160) combines both, allowing both providing an underlying type and element names. That isn't something you can do in the language, and I don't think we should support it in the APIs.

**Comment by jcouv** [comment]
Thanks for the summary.

**Comment by jcouv** [comment]
Quick summary of the API design meeting last week: 
The plan of record (keeping the two public APIs and the concept of underlying type) was deemed reasonable to proceed with. That said, there is room to revisit if the details of the alternative proposal are fleshed out.
Let me know if the issue should remain open.

**Comment by gafter** [comment]
The PR introduced only one API for creating tuple types. It lacks an API for creating a tuple type given element types and element names. So this issue should remain open at least until that is addressed.

**Comment by jcouv** [comment]
That API already exists in the future branch [here](https://github.com/dotnet/roslyn/blob/future/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs#L2759).

**Comment by gafter** [comment]
That is not a public API.

**Comment by jcouv** [comment]
Sorry, I pointed to the wrong file. The public API is [here](https://github.com/dotnet/roslyn/blob/future/src/Compilers/Core/Portable/Compilation/Compilation.cs#L835).

**Comment by gafter** [comment]
I see. Thanks!

**Comment by jcouv** [comment]
Let me know if the issue should remain open.

**Comment by gafter** [comment]
> Let me know if the issue should remain open.

I'm afraid that representing a tuple type such as `(int, int)` as a *different type* from its underlying type `ValueTuple<int, int>`, does not match the likely language specification, which I expect will say that they are *the same type*. Such a difference between the spec and implementation will be observable in the language. See, for example, #11986.

As for this issue, you decide if that affects the public APIs. You could close this issue now and reopen it (or create a new issue) if we discover that addressing a mismatch requires API changes.

**Comment by jcouv** [comment]
Yes, let's do that. Closing for now as current public API seems reasonable.
