### ISSUE TITLE
MSBuildWorkspace cannot load xproj files

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/roslyn#11342]
**Version Used**: 
1.2.1

**Steps to Reproduce**:

1. Create a solution with projects using the xproj system (ASP.NET/.NET Core project.json)
2. Run the following code:

```csharp
using Microsoft.CodeAnalysis.MSBuild;
using System;
using System.Threading.Tasks;

namespace ConsoleApplication2
{
    class Program
    {
        static void Main(string[] args)
        {
            RunAsync().Wait();
        }

        private static async Task RunAsync()
        {
            var solution = await MSBuildWorkspace.Create()
                .OpenSolutionAsync(pathToSolution);

            Console.WriteLine("Projects:");

            foreach (var project in solution.Projects)
            {
                Console.WriteLine(project.Name);
            }
        }
    }
}
``` 

**Expected Behavior**:
List of projects

**Actual Behavior**:
Empty list

**Comment by jaredpar** [comment]
Moving to @srivatsn as they own xproj.

**Comment by srivatsn** [comment]
xproj itself is just a wrapper over project.json and you'd have to use the ProjectJsonWorkspace in [this package](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Workspaces.Dnx/) to read the project.json files. Note, however that project.json will be replaced with MSBuild-based csproj in the future and at that point MSBuildWorkspace will be able to open those projects.

**Comment by AlexeiScherbakov** [comment]
I have same problem. After converting library to .NET Core I can't use my codegenerator for xproj.
Package Microsoft.CodeAnalysis.Workspaces.Dnx supports only dnx451, so it cannot be used with .NET Framework, or with .NET Core - so there are no ways to use it now :-)

**Comment by srivatsn** [comment]
For .NETCore projects you'll likely have to use the ProjectJsonWorkspace from the [Microsoft.DotNet.ProjectModel.Workspaces](https://www.nuget.org/packages/Microsoft.DotNet.ProjectModel.Workspaces/1.0.0-preview2-003121) package

**Comment by AlexeiScherbakov** [comment]
Hm, I'l try this package, thanks. I tried only stable packages

**Comment by AlexeiScherbakov** [comment]
Under .NET Core it is not working
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)

But under .NET Framework it works in readonly mode by default.
After call jsonWorkspace.TryApplyChanges(parserProject.Solution); it throws:
An unhandled exception of type 'System.NotSupportedException' occurred in Microsoft.CodeAnalysis.Workspaces.dll
Additional information: Changing documents is not supported.


Only when I updated **ALL** dependencies to unstable variants - it begin working as expected
