### ISSUE TITLE
Compiler server should handle OOMs when loading metadata 

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#11352]
MetadataAndSymbolCache should catch and handle OutOfMemoryException when calling to `ModuleMetadata.CreateFromStream`. When "prefetch" option is specified the metadata reader attempts to read the entire metadata section (or PE image) into a single chunk of native memory. 

Allocating such chunk can result in a recoverable OOM. The server can retry after emptying caches, restart the process or report an error that the metadata file is tool large to fit into memory instead of crashing.

**Comment by jaredpar** [comment]
There seem to be two cases here to consider:

1. The metadata is malformed and is causing an OOM 
1. The compiler server is low on memory and hence a valid image is causing an OOM

In practice we haven't seen 1 very much, if at all.  I don't see it as a motivating factor for this bug. 

It seems unlikely that 2 is an issue in practice as we run the server in 64 bit mode by default.  Hence hard to see a valid PE causing an OOM in that case.  Even if it did, falling back to csc is an acceptable trade off here.  

Closing until we see some real world scenarios here.
