### ISSUE TITLE
Quick watch doesn't understands open generics

### ISSUE THREAD

**Issue by mariaghiondea-msft** [dotnet/roslyn#1135]
From customer reported through SaS:

Quick watch doesn't understands open generics, e.g.
following code: typeof(List<>)
leads to the error: (1,12): error CS1026: ) expected

**Comment by Suchiman** [comment]
Hi, i did report this, thanks for delegating this to the right devision @mariaghiondea-msft 

Additional Information:
If the generic type has only one argument, you get the error as described:
![quickwatch_2015-03-15_15-45-18](https://cloud.githubusercontent.com/assets/7110884/6656415/955af75a-cb2a-11e4-9db3-126b0798c53f.png)

If you try it on a generic type with more than one argument it seems to work though
![quickwatch_2015-03-15_15-43-20](https://cloud.githubusercontent.com/assets/7110884/6656405/3466d388-cb2a-11e4-9774-28a38a512625.png)

**Comment by Suchiman** [comment]
Probably fixed by #1408

**Comment by KevinH-MS** [comment]
@Suchiman, thanks!  Yes, this is fixed by commit 7683a0a.  I was looking at the Send a Smile report when I fixed the bug, and I neglected to notice the GitHub issue was the same.
