### ISSUE TITLE
Duplicate project diagnostics from build/intellisense in the error list

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#11350]
**Version Used**: 1.2.1

**Steps to Reproduce**:

1. Create a C# class library project
2. Delete the AssemblyInfo.cs file from the project
3. Add NuGet package reference to Microsoft.CodeAnalysis.FxCopAnalyzers (1.2.0-beta1)
4. Edit the C# project file to enable IOperation analyzers by adding the following property: `<Features>IOperation</Features>`
5. Build and wait for intellisense and build diagnostics from the project - filter error list to show only CA1016 issues.

**Expected Behavior**:
No duplicate CA1016 (Mark assemblies with assembly version)

**Actual Behavior**:
I see duplicate diagnostics from build and intellisense:
```
Severity	Code	Description	Project	File	Line	Source	Tool	Suppression State
Warning	CA1016	Mark assemblies with assembly version	ClassLibrary1		1	IntelliSense	Microsoft.ApiDesignGuidelines.Analyzers	Active
Warning		Mark assemblies with assembly version	ClassLibrary1	C:\Users\mavasani\Documents\Visual Studio 2015\Projects\ClassLibrary1\ClassLibrary1\CSC		Build		
```

Below is the output window:
```
1>------ Rebuild All started: Project: ClassLibrary1, Configuration: Debug Any CPU ------
1>CSC : warning CA1016: Mark assemblies with assembly version
1>  ClassLibrary1 -> C:\Users\mavasani\Documents\Visual Studio 2015\Projects\ClassLibrary1\ClassLibrary1\bin\Debug\ClassLibrary1.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

```

**Comment by mavasani** [comment]
FYI @heejaechang

**Comment by heejaechang** [comment]
interesting, I am taking a look.

**Comment by heejaechang** [comment]
@mavasani I get bunch of these.

do I need binary redirection somewhere?

..
Severity	Code	Description	Project	File	Line	Suppression State
Warning		An instance of analyzer Microsoft.ApiDesignGuidelines.Analyzers.UseIntegralOrStringArgumentForIndexersAnalyzer cannot be created from c:\users\hechang\documents\visual studio 2015\Projects\ClassLibrary4\packages\Microsoft.ApiDesignGuidelines.Analyzers.1.2.0-beta1\analyzers\dotnet\cs\Microsoft.ApiDesignGuidelines.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	ClassLibrary4	c:\users\hechang\documents\visual studio 2015\Projects\ClassLibrary4\ClassLibrary4\CSC

**Comment by mavasani** [comment]
Did you build with OfficialBuild = true?

**Comment by heejaechang** [comment]
hmmm.. I am building from VS. inside of VS, it works fine. but VS build shows that.

**Comment by heejaechang** [comment]
how can I add binary redirection for build inside of VS? I guess I need to update csc or build server binary redirection somewhere?

**Comment by heejaechang** [comment]
@mavasani ping?

**Comment by mavasani** [comment]
Probably its using MSbuild toolset that comes with VS. you need to install locally built compiler VSIX into dev hive manually.

**Comment by mavasani** [comment]
You can increase msbuild output verbosity and see where it's picking up csc

**Comment by heejaechang** [comment]
@mavasani what is the name of compiler vsix? if I update to latest signbit from installdogfood, will that fix it?

**Comment by heejaechang** [comment]
@mavasani this is where it is picking up. 

...

1>CscToolExe = csc.exe
1>CscToolPath = C:\USERS\HECHANG\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0ROSLYNDEV\EXTENSIONS\MICROSOFT\ROSLYN COMPILERS\42.42.42.42
1>CSharpCoreTargetsPath = C:\USERS\HECHANG\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0ROSLYNDEV\EXTENSIONS\MICROSOFT\ROSLYN COMPILERS\42.42.42.42\Microsoft.CSharp.Core.targets
1>CSharpTargetsPath = C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets
1>CurrentSolutionConfigurationContents = <SolutionConfiguration>
1><ProjectConfiguration Project="{cceac78c-71b5-486f-94b4-c570ef41d71b}" AbsolutePath="C:\Users\hechang\documents\visual studio 2015\Projects\ClassLibrary4\ClassLibrary4\ClassLibrary4.csproj">Debug|AnyCPU</ProjectConfiguration>
1></SolutionConfiguration>
1>CustomAfterMicrosoftCommonProps = C:\Program Files (x86)\MSBuild\v14.0\Custom.After.Microsoft.Common.props
1>CustomAfterMicrosoftCommonTargets = C:\Program Files (x86)\MSBuild\v14.0\Custom.After.Microsoft.Common.targets
1>CustomAfterMicrosoftCSharpTargets = C:\Program Files (x86)\MSBuild\v14.0\Custom.After.Microsoft.CSharp.targets
1>CustomBeforeMicrosoftCommonProps = C:\Program Files (x86)\MSBuild\v14.0\Custom.Before.Microsoft.Common.props
1>CustomBeforeMicrosoftCommonTargets = C:\Program Files (x86)\MSBuild\v14.0\Custom.Before.Microsoft.Common.targets
1>CustomBeforeMicrosoftCSharpTargets = C:\Program Files (x86)\MSBuild\v14.0\Custom.Before.Microsoft.CSharp.targets
1>DebugSymbols = true

**Comment by mavasani** [comment]
Are you building from dev hive or regular hive? Roslyn.Compilers.Extension.vsix

**Comment by mavasani** [comment]
Yep - 42.42.42.42 that's the problem. Clean your hive and rebuild entire Roslyn.sln with OfficialBuild = true

**Comment by heejaechang** [comment]
@mavasani I see. I just changed binary redirect to 42.42.42.42

**Comment by heejaechang** [comment]
@mavasani is this ever worked. I see this.

http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/TaskList/ProjectExternalErrorReporter.cs,146

this code is from legacy code base, so I believe we never dealt with error from build that doesnt have location or at least location reported as -1, -1 rather than 0, 0

**Comment by mavasani** [comment]
It likely never worked before.

**Comment by heejaechang** [comment]
@mavasani just curious. how RoslynDev VS works then? is local bit create different binary redirect for VS? but not compiler?

**Comment by heejaechang** [comment]
@mavasani if I change us to accept project errors, it fixes the issue. (just tested), but have no idea what will break...

**Comment by heejaechang** [comment]
it seems... fine..will create PR.
