### ISSUE TITLE
Please make InvisibleEditor public API

### ISSUE THREAD

**Issue by Mylan719** [dotnet/roslyn#11363]
http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/InvisibleEditor.cs,16
`InvisibleEditor` provides very nice visualstudio consistent way of editing files. 

There are 2 ways of editing project files that are not open in active window in visualstudio:
1.  Standard `using (StreamWriter sw = ...)` This is quite inconvenient and does not work well if file is open on another tab.
2. Using `EnvDTE.Document` and `EnvDTE.TextDocument.CreateEditPoint()` This is very old API that has too few methods which are pretty low-level. On top of that `EnvDTE.TextDocument.MoveToAbsoluteOffset(0)` treats characters differently than rest of VS API.

As far as I searched `InvisibleEditor` is the best way to make edits so it would help a lot to have it publicly accessible.

**Comment by CyrusNajmabadi** [comment]
This is an extremely low level API that we would not want to have to support in the future.  If customers need a `very nice visualstudio consistent way of editing files`, that should come from VisualStudio itself, not through Roslyn.

Note that the VS editor was completely rewritten, and there are a ton of modern APIs for working with the editor that would be preferred over using this older type.
