### ISSUE TITLE
Proposal: Handling all exceptions in a central class, which is triggered in a try/catch block

### ISSUE THREAD

**Issue by AlbatrossOnBoard** [dotnet/roslyn#11362]
Mostly, if an exception occurs, it is logged and thrown again. The idea is collecting all these exceptions at a central place, i.e. in a class, and handle exceptions in that class. The advantages are better code readability and maintenance.

Example:
```
public class MyClass
{
    ....
    public void MyFunction()
    {
        ...
        try : new MyExceptionHandlerClass("This is MyFunction")
        {
            int a = 5, b = 0;
            int c = a / b;
        } // here no catch block
    }
}

public class MyExceptionHandlerClass
{
    private string _message;

    public MyExceptionHandlerClass(string message)
    {
        _message = message;
    }

    // here no try block
    catch(DivideByZeroException e)
    {
        Log.LogIt(e, _message);
        throw e;
    }
}

```

**Comment by svick** [comment]
1. You're introducing a lot of new special syntax, for a very narrow use case, I don't like that.

2. If you rethrow an exception using `throw e;`, you reset its stack trace, making it harder to debug. (And maybe if you didn't do that, you wouldn't need the "catch, log and rethrow" pattern at all.)

3. You can already get pretty close to what you want with exception filters:

 ```c#
class MyExceptionHandlerClass
{
		public bool Handle(Exception ex)
		{
			if (ex is DivideByZeroException)
			{
				Log.LogIt(ex);
				return false;
			}
		
			if (ex is IOException)
			{
				// don't rethrow
				return true;
			}
		
			return false;
		}
}

…
try
{
		// …
}
catch (Exception ex) when (new MyExceptionHandlerClass().Handle(ex))
{
}
```

 This means you have to do your own dispatch, but [pattern matching](https://github.com/dotnet/roslyn/blob/future/docs/features/patterns.md) is going to make that better.

**Comment by AlbatrossOnBoard** [comment]
Thank you for your comprehensive explanation. I think, it is better to solve the issue as you proposed.
