### ISSUE TITLE
Error list reports errors even though project builds without issue

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#11369]
Severity | Code | Description | Project | File | Line | Suppression State
--- | ------ | ------ | ------ | ------ | ------ | ------ | 
Error | CS1069 | The type name 'ResourceManager' could not be found in the namespace 'System.Resources'. This type has been forwarded to assembly 'System.Resources.ResourceManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly. | MSBuildTask | C:\r\roslyn\Open\src\Compilers\Core\MSBuildTask\Shared\ErrorString.Designer.cs | 44 | Active
Error | CS1061 | 'IEnumerable<string>' does not contain a definition for 'Concat' and no extension method 'Concat' accepting a first argument of type 'IEnumerable<string>' could be found (are you missing a using directive or an assembly reference?) | MSBuildTask | C:\r\roslyn\Open\src\Compilers\Core\MSBuildTask\Shared\InteractiveCompiler.cs | 286 | Active
Error | CS1061 | 'IEnumerable<string>' does not contain a definition for 'Concat' and no extension method 'Concat' accepting a first argument of type 'IEnumerable<string>' could be found (are you missing a using directive or an assembly reference?) | MSBuildTask | C:\r\roslyn\Open\src\Compilers\Core\MSBuildTask\Shared\ManagedCompiler.cs | 578 | Active
Error | CS1061 | 'IEnumerable<string>' does not contain a definition for 'Select' and no extension method 'Select' accepting a first argument of type 'IEnumerable<string>' could be found (are you missing a using directive or an assembly reference?) | MSBuildTask | C:\r\roslyn\Open\src\Compilers\Core\CommandLine\BuildClient.cs | 78 | Active
Error | CS1061 | 'IEnumerable<string>' does not contain a definition for 'Skip' and no extension method 'Skip' accepting a first argument of type 'IEnumerable<string>' could be found (are you missing a using directive or an assembly reference?) | MSBuildTask | C:\r\roslyn\Open\src\Compilers\Core\CommandLine\BuildClient.cs | 234 | Active
Error | CS1061 | 'string[]' does not contain a definition for 'Select' and no extension method 'Select' accepting a first argument of type 'string[]' could be found (are you missing a using directive or an assembly reference?) | MSBuildTask | C:\r\roslyn\Open\src\Compilers\Core\MSBuildTask\Shared\InteractiveCompiler.cs | 189 | Active
Error | CS1061 | 'string[]' does not contain a definition for 'Select' and no extension method 'Select' accepting a first argument of type 'string[]' could be found (are you missing a using directive or an assembly reference?) | MSBuildTask | C:\r\roslyn\Open\src\Compilers\Core\MSBuildTask\Shared\ManagedCompiler.cs | 355 | Active
Error | CS1061 | 'string[]' does not contain a definition for 'ToList' and no extension method 'ToList' accepting a first argument of type 'string[]' could be found (are you missing a using directive or an assembly reference?) | MSBuildTask | C:\r\roslyn\Open\src\Compilers\Core\MSBuildTask\Shared\ManagedCompiler.cs | 394 | Active
Error | CS1503 | Argument 1: cannot convert from 'T[]' to 'System.Collections.Generic.IEnumerable<string>' | MSBuildTask | C:\r\roslyn\Open\src\Compilers\Core\CommandLine\BuildClient.cs | 86 | Active
Error | CS0012 | The type 'ResourceManager' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Resources.ResourceManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. | MSBuildTask | C:\r\roslyn\Open\src\Compilers\Core\MSBuildTask\Shared\InteractiveCompiler.cs | 22 | Active
Error | CS0012 | The type 'ResourceManager' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Resources.ResourceManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. | MSBuildTask | C:\r\roslyn\Open\src\Compilers\Core\MSBuildTask\Shared\ManagedCompiler.cs | 30 | Active
Error | CS1069 | The type name 'ResourceManager' could not be found in the namespace 'System.Resources'. This type has been forwarded to assembly 'System.Resources.ResourceManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly. | MSBuildTask | C:\r\roslyn\Open\src\Compilers\Core\MSBuildTask\Shared\ErrorString.Designer.cs | 29 | Active
Error | CS1069 | The type name 'ResourceManager' could not be found in the namespace 'System.Resources'. This type has been forwarded to assembly 'System.Resources.ResourceManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly. | MSBuildTask | C:\r\roslyn\Open\src\Compilers\Core\MSBuildTask\Shared\ErrorString.Designer.cs | 41 | Active
Error | CS1069 | The type name 'ResourceManager' could not be found in the namespace 'System.Resources'. This type has been forwarded to assembly 'System.Resources.ResourceManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly. | MSBuildTask | C:\r\roslyn\Open\src\Compilers\Core\MSBuildTask\Shared\ErrorString.Designer.cs | 44 | Active

Complete workspace log is [here](https://1drv.ms/u/s!ApLe5JFIykQgju9BE8mDakg9-kJiFw)

**Comment by heejaechang** [comment]
this is usual symptom of in proc compilation being broken inside of IDE. with all changes in project system , probably already fixed. please re-open bug to IDE team if it happens again.
