### ISSUE TITLE
Add reference doesn't work in portable projects

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#11372]
**Version Used**: 
VS15 Preview 2 (with Add reference assembly option turned on)

I add a using for Serialization but it doesn't bind (in a portable project...was working on writing an analyzer):
![image](https://cloud.githubusercontent.com/assets/1402694/15336964/f822041e-1c2d-11e6-9af7-a48ded552f1c.png)

**Comment by davkean** [comment]
ISerializable is only available on .NET Framework, not anywhere else - so portable doesn't allow it. It's by design, but given recent changes in .NET Core - it's coming back
