### ISSUE TITLE
Cannot suppress errors/warnings when "Build Only" is selected

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11371]
I only get the option to suppress a code analysis warning/error if IntelliSense errors are show:
![image](https://cloud.githubusercontent.com/assets/1103906/15336908/af63f2f0-1c2d-11e6-8bbd-61a670a564c9.png)

Build only:
![image](https://cloud.githubusercontent.com/assets/1103906/15336892/929be592-1c2d-11e6-94c9-ed531fa0e68a.png)

**Comment by davkean** [comment]
tag @mavasani

**Comment by mavasani** [comment]
This is by design - build diagnostics might be stale, so we offer suppression fixes only for live diagnostics in error list

**Comment by davkean** [comment]
This is confusing, you should at least show the Suppress if there's a live diagnostic. Live diagnostics can also get out of sync, how's that different?

**Comment by mavasani** [comment]
Tagging @srivatsn @heejaechang 

This is the primary design issue with offering any code fix in error list. For intellisense diagnostics, when you right click, we recompute the intellisense diagnsotics for the document/project and offer the suppression fix only if it is still a valid diagnostic. Build diagnostics need an explicit build to be kicked off and hence we cannot guarantee any code fix with diagnostics from last build with work on latest solution snapshot. We decided to not offer suppression fix for any build diagnostic.

**Comment by davkean** [comment]
From user standpoint, it looks like error is the same regardless of whether it came from IntelliSense or Build. How does this work for FxCop?

**Comment by mavasani** [comment]
We talked about offering a better visual indication on why the suppression fix is not available for build diagnostics - that didn't happen though.

FXCop - this is completely based off the diagnostics from explicit CA run, and this has the same known issues where it won't work as the current solution is updated.

Basically, offering a code fix should only be restricted to diagnostics that can be computed for the current snapshot - for the rest its never going to be reliable.

**Comment by heejaechang** [comment]
is the confusion the part matter or not supporting it is the issue?

if the confusion is the problem, how about we show the context menu, but either gray out or something, and show tooltip that says build error doesn't support suppression.

if feature not support is the issue, we probably need to talk how to make it work in one of our team meeting.

**Comment by davkean** [comment]
The confusion is that I thought the product was broken because I couldn't suppress the warning.

**Comment by heejaechang** [comment]
ah, then as long as It clearly states that build errors can't be suppressed, there is no confusion.
