### ISSUE TITLE
Build is now confusing when "Enable full solution analysis" is off

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11378]
When "Enable full solution analysis" is off, build is now very confusing:

1. Sync to https://github.com/dotnet/roslyn-project-system/commit/b6f9b16d1558bdc10efb588f322f037fe3fe2058
2. Run build.cmd from a VS 15 command prompt
3. Open src\ProjectSystem.sln
4. Turn off __Enable full solution analysis__
5. In the Error List, switch to Build + IntelliSense
5. Build 

__Expected:__ Build fails, with the following Errors in the error list:

```
Warning	RS0003	Do not directly await a Task without calling ConfigureAwait	Microsoft.VisualStudio.ProjectSystem.Managed.VS	C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\Build\LanguageServiceErrorListProvider.cs	86	Active
Error	RS0006	Attribute 'AppliesToAttribute' comes from a different version of MEF than the export attribute on 'Microsoft.VisualStudio.ProjectSystem.VS.Build.LanguageServiceErrorListProvider'	Microsoft.VisualStudio.ProjectSystem.Managed.VS	C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\Build\LanguageServiceErrorListProvider.cs	17	Active
Warning	RS0003	Do not directly await a Task without calling ConfigureAwait	Microsoft.VisualStudio.ProjectSystem.Managed.VS	C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\Build\LanguageServiceErrorListProvider.cs	86	Active
```
__Actual:__ Build fails, no errors or warnings are displayed in the errorlist

If I switch to build-only, I see the above errors.

**Comment by heejaechang** [comment]
I tested this on simple solution and it worked. does both of you have latest Roslyn bits installed?

**Comment by davkean** [comment]
I'm on 1.2.1, NIck's on 1.3.

**Comment by nguerrera** [comment]
Maybe I'm not quite on 1.3. I followed the steps here: https://github.com/dotnet/roslyn-internal/tree/master/Closed/Test/Solutions/RegenerateNewtonsoftErrorLogBaseline.txt and am running devenv /rootSuffix RoslynDev.  Does that give me up to date error list bits?

**Comment by nguerrera** [comment]
Can you try the solution referenced there?

**Comment by heejaechang** [comment]
this repro require dev15, so let me try nick's repro.
