### ISSUE TITLE
The Preview window for suppressing a warning, shows confusing diff

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11373]
I suppressed a single instance of a warning, and the preview window is showing as if it added two suppressions:

![image](https://cloud.githubusercontent.com/assets/1103906/15336970/01acffa2-1c2e-11e6-9109-aa00850ea9bf.png)

Here's the real diff:

![image](https://cloud.githubusercontent.com/assets/1103906/15337000/20d5a960-1c2e-11e6-9ccf-8dc7e83efbdd.png)

**Comment by davkean** [comment]
Wonder if this because the end of line changed: https://github.com/dotnet/roslyn-project-system/pull/160/files. Looks like we removed the trailing new line.

**Comment by Pilchie** [comment]
I expect that the eol is the issue.

**Comment by Pilchie** [comment]
I don't think we would do anything here unless/until we overhaul the whole preview change dialog.

**Comment by CyrusNajmabadi** [comment]
Agree with Kevin.  This area is in maintenance mode.  Perhaps new LSP approach may make it better.
