### ISSUE TITLE
Up to date check for CSharpCodeAnalysis is not working.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#11374]
Even if i do a full build, the next build still ends up building CSharpCodeAnalysis and all dependencies.

**Comment by Pilchie** [comment]
@CyrusNajmabadi you might want to look at https://blogs.msdn.microsoft.com/kirillosenkov/2014/08/04/how-to-investigate-rebuilding-in-visual-studio-when-nothing-has-changed/ to see if you can identify what's going on here.

**Comment by CyrusNajmabadi** [comment]
So this is what i'm seeing:

9>Project 'CSharpCodeAnalysis' is not up to date. CopyLocal reference 'C:\GitHub\roslyn-internal\Open\Binaries\Debug\DeployCompilerGeneratorToolsRuntime_DoNotUse.exe' is missing from output location.
9>------ Build started: Project: CSharpCodeAnalysis, Configuration: Debug Any CPU ------

This is really brutal.  Every build is effectively a full build.

**Comment by CyrusNajmabadi** [comment]
Who owns DeployCompilerGeneratorToolsRuntime_DoNotUse.exe and can we get it to properly incrementally build?

**Comment by tmat** [comment]
@agocke FYI

**Comment by jaredpar** [comment]
This should be fixed now with the build changes.
