### ISSUE TITLE
Tuple Type vs Tuple Underlying Type in the Roslyn APIs

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#11382]
This describes a possible approach to the way we surface *tuple types* in the Roslyn APIs that attempts to keep the API surface area as close as possible to the shape of the language specification. It has some assumptions and constraints on the way tuples work in the language, particularly in scenarios where there are multiple definitions for `System.ValueTuple` across different referenced assembles. The impact for these scenarios will be discussed.

The primary principle that drives this design is to **align the API surface area with the shape of the language specification**, and to keep the API as simple as possible to reflect the shape of the language. The most important spec issue is that a tuple type such as `(int, int)` is considered *equivalent* to the constructed type `System.ValueTuple<int, int>`.

Secondary concerns are to reduce the implementation costs (both complexity of code and time and space of running the compiler).

The effects on the public APIs are:

### Type.TupleUnderlyingType

The principal effect of this change is that it removes the concept of *tuple underlying type* from the compiler's public API. A tuple type without names imposed on its elements is simply the same (from the point of view of the public API) as its underlying type.

### Generic Arity

Given that the types `(int,int)` and `VT<int,int>` are *equivalent* types, they are either both generic or both non-generic, and they should have the same number of type arguments. Since this particular type is generic with arity 2, both of them would be surfaced as `NamedTypeSymbol`s with arity 2.

### Type Equality

Given that the types `(int,int)` and `VT<int,int>` are *equivalent* types, they would be treated as being *equal* in most senses of equality, e.g. `==` and `object.Equals`, though like most types they are not necessarily reference equal. The addition of names to a tuple type would cause it to be different from (not equal to) the corresponding unnamed tuple equivalent.

### TypeSymbol.Construct

Given that the types `(int,int)` and `VT<int,int>` are *equivalent* types, *Constructing* the type `System.ValueTuple'2` with type arguments `int,int` should produce the type `(int,int)`. In other words, in the compiler API, after "looking up" the type `System.ValueTuple'2` in the global namespace, the result of `type.Construct(intType, intType)` should be the same type as the result of creating a tuple type with the element types `int` and `int`.

If we retain a separate concept of `TupleTypeSymbol` internal to the compiler, which is different from its "underlying type", we may have to separate the compiler-internal generic type construction API (which might only produce an underlying type) from the public type construction API (which would produce tuple types when appropriate).

### IsTupleType

Whether a type *is a tuple type* is a question that only makes sense with respect to a particular compilation, or with respect to a particular assembly, in either case providing a place from which to look up `System.ValueTuple` to check. As a consequence, the property `NamedTypeSymbol.IsTupleType` becomes a method that takes a `Compilation` or `Assembly` in which to resolve the names.

### CreateTupleTypeSymbol

To create a tuple type for a given compilation, it is necessary to look up the unique `System.ValueTuple` types needed for the construction. A client of the compiler APIs can do that directly, by constructing the equivalent of the tuple underlying type. The result is an unnamed tuple type. Alternately, we would provide a mechanism for creating an optionally *named* tuple type given the element types and names

```cs
    INamedTypeSymbol Assembly.CreateTupleType(
        ImmutableArray<ITypeSymbol> elementTypes,
        ImmutableArray<string> elementNames = default(ImmutableArray<string>));
```

We would probably provide this API on `Compilation` for convenience as well (it would delegate to the underlying source assembly).

### Effect on metadata loading

It is possible at compile-time to reference multiple assemblies each of which has a different idea of what `System.ValueTuple` is. This does not necessarily prevent the referencing compilation from having a unique result for the lookup of `System.ValueTuple`, as some assemblies may be referenced through an extern alias.

I propose that the semantics of this situation are as follows:

1. We define what it means for a type to be a tuple type in a given assembly. Those rules include that all of the `ValueTuple` types in a chain (for tuples of cardinality 8 or higher) are defined in the same assembly, and correspond to the unique result of looking up the name `System.ValueTuple` in that assembly or (failing that) its referenced assemblies.

2. If a type is a tuple type *in the context of the assembly that produced it*, then it has as members any synthetic members that would be appropriate if it were a tuple type. Specifically, it gets any element names provided in the API in the assembly (through compiler-produced attributes), for example `x` and `y` in the tuple type `(int x, int y)` of a method declared to return that type. In addition, for tuples of cardinality 8 or higher we also provide a synthetic `Deconstruct` method.

3. These members are available and usable in any referencing compilation. That means, for example, that tuple deconstruction works even if the type is referenced in a compilation where it is not considered a tuple type. However, additional tuple semantics are only available in a compilation if the type is a tuple type *with respect to the compilation*:
  - The tuple literal conversion
  - The tuple type conversion (elementwise)
  - Exact match from expression
  - Betterness and type inference rules that dive into tuple element types

/cc @jcouv @CyrusNajmabadi @VSadov @MadsTorgersen @AnthonyDGreen @DustinCampbell 

@AlekseyTs Suggested I write this up. It may provide some fodder for tomorrow's design session

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/issues/11803

**Comment by jcouv** [comment]
All the above issues have been discussed and reviewed. We're good.
