### ISSUE TITLE
Compiler emits duplicate rules metadata entries with ErrorLogger version 1.0.0-beta.5

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#11383]
**Version Used**: Latest Roslyn bits

**Steps to Reproduce**:

1. Unzip `Closed\Test\Solutions\Newtonsoft.json.zip` from the roslyn-internal repo

2. Clean your RoslynDev hive: "C:\Users\<%USER_NAME%>\AppData\Local\Microsoft\VisualStudio\14.0RoslynDev"

3. Build Roslyn.sln with 'OfficialBuild = true' using the below command. This will build and deploy latest Roslyn bits (and hence compiler ErrorLogger) into the RoslynDev hive.

     > msbuild /m Roslyn.sln /t:rebuild /p:OfficialBuild=true
4. devenv /rootSuffix RoslynDev

5. Open and build `\Closed\Test\Solutions\Newtonsoft.Json\Newtonsoft.Json\Newtonsoft.Json.Portable.sln` 

6. Open `\Closed\Test\Solutions\Newtonsoft.Json\Newtonsoft.Json\ErrorLog.json`

**Expected Behavior**:
No duplicate metadata entries for any rules (there are no rules with duplicate IDs)

**Actual Behavior**:
Duplicate entries SA1001 and SA1001.001
```
        "SA1003": {
          "id": "SA1003",
          "shortDescription": "Symbols must be spaced correctly",
          "fullDescription": "The spacing around an operator symbol is incorrect, within a C# code file.",
          "defaultLevel": "warning",
          "helpUri": "https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1003.md",
          "properties": {
            "category": "StyleCop.CSharp.SpacingRules",
            "isEnabledByDefault": true
          }
        },
        "SA1003.001": {
          "id": "SA1003",
          "shortDescription": "Symbols must be spaced correctly",
          "fullDescription": "The spacing around an operator symbol is incorrect, within a C# code file.",
          "defaultLevel": "warning",
          "helpUri": "https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1003.md",
          "properties": {
            "category": "StyleCop.CSharp.SpacingRules",
            "isEnabledByDefault": true
          }
        },```

**Comment by nguerrera** [comment]
On it.
