### ISSUE TITLE
Get offered to simplify a call to a instance method incorrectly

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11380]
``` C#
using System;
class Program
{
    static void Main(string[] args)
    {
        Console.Equals("");
    }
}

```

![image](https://cloud.githubusercontent.com/assets/1103906/15339019/3d2d8eb2-1c37-11e6-8406-9bc4eed734b9.png)

**Comment by Pilchie** [comment]
While strange - this seems to be unique to `Console` for some reason.

**Comment by davkean** [comment]
No, it's happens for any type:

```
```
![image](https://cloud.githubusercontent.com/assets/1103906/16125791/042cbc98-33aa-11e6-8a4c-da93be91503e.png)

**Comment by Pilchie** [comment]
Hmm.  What I meant was that I couldn't make it happen for my own set of types with a similar pair of overloads to `Equals`.

**Comment by CyrusNajmabadi** [comment]
This no longer repros.  Will add test to demonstrate that.
