### ISSUE TITLE
Tidy up the error codes introduced for C# 7, before shipping

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#11405]
For instance, the error codes for tuples can be compacted together with pre-existing ones.

src/Compilers/CSharp/Portable/Errors/ErrorCode.cs

https://github.com/dotnet/roslyn/pull/11384#discussion-diff-63765896

**Comment by jcouv** [comment]
@gafter I discussed with @VSadov and he's suggesting to leave as-is. I can go either way...

**Comment by gafter** [comment]
@jcouv I'd prefer to compact, as we had agreed to do when we spread them out in the first place.
