### ISSUE TITLE
[Proposal] Implement `IReadOnlyDictionary<string, object>` on anonymous types

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#1141]
#### Problem

Anonymous types are sometimes used to provide a set of extra arguments using a concise syntax. Most noticeable examples belong to ASP.NET, e.g. in routing and html helpers:

``` csharp
@Html.TextBox("name", new { maxlength = 50 })
```

``` csharp
routes.MapRoute(
    "Default",
    "{controller}/{action}/{id}",
    new { controller = "Home", action = "Index", id = "" }
);
```

However there is no easy way to get values from anonymous type instance without using reflection -- so in best case developer has to use a cache, and in worst case they will write slow code.
#### Proposal

Implemented `IReadOnlyDictionary<string, object>` on anonymous types.
#### Pros
1. Makes anonymous type usage for extra arguments fast-by-default.
2. Provides a clear way to use anonymous types provided externally.
3. Allows serializers that support dictionaries to handle anonymous types by default.
#### Cons
1. (Compatibility) Will change overload selection in the following code:
   
   ```
   public void M(object x);
   public void M(IReadOnlyDictionary<string, object> x);
   // ...
   M(new { A = a });
   ```
2. (Compatibility) Might break existing serializers.
#### Community
1. StackOverflow: [In c# convert anonymous type into key/value array?](http://stackoverflow.com/questions/3481923/in-c-sharp-convert-anonymous-type-into-key-value-array): 29 votes (+51 answer), 7 :star:

**Comment by jaredpar** [comment]
How do you propose to handle case sensitivity?  In particular should VB anonymous types essentially use `StringComparison.OrdinalIgnoreCase` or do both use `StringComparer.Ordinal` for name comparison?

**Comment by paulomorgado** [comment]
I would vote for them to changing that API.

**Comment by MgSam** [comment]
From an API point of view this is an interesting proposal, but from a performance perspective it seems like this would change the whole performance characteristic of an anonymous type because it now needs to build an internal dictionary. 

My guess is that scenarios like that in your motivating example are already not performance sensitive (you presumably only need to map your routes once), so it seems like language-level optimization here is overkill. 

You're essentially proposing a performance optimization for a somewhat rare use case (using anonymous types as dictionaries) in a scenario where it would probably have no meaningful performance benefit in exchange for a language-wide performance hit whenever you use anonymous types. For that reason, I vote against this feature.

**Comment by ashmind** [comment]
@jaredpar
> In particular should VB anonymous types essentially use StringComparison.OrdinalIgnoreCase
Seems reasonable -- are there any disadvantages?

@MgSam
> from a performance perspective it seems like this would change the whole performance characteristic of an anonymous type because it now needs to build an internal dictionary.

Why? It would essentially be an on-demand `switch`. It could build a lazy dictionary too, I suppose, though it feels like an overkill.

**Comment by ashmind** [comment]
@MgSam
Here is a possible implementation (explicitness removed for readability):
```csharp
object this[string key] { 
    get {
        switch (key) { // considering only C# for simplicity, but could be a set of ifs just as well
            case "X": return X;
            case "Y": return Y;
            default: throw new KeyNotFoundException(...);
        }
    }
}

int Count {
    get { return 2; }
}

public IEnumerable<string> Keys {
    get {
        yield return "X";
        yield return "Y";
    }
}

public IEnumerable<object> Values {
    get {
        yield return X;
        yield return Y;
    }
}

// ... IEnumerable
```

**Comment by jaredpar** [comment]
@ashmind the disadvantage is that it means anonymous types defined in different languages behave differently when viewed as `IReadOnlyDictionary<string, object>`

**Comment by ashmind** [comment]
@jaredpar That's a fair point, but I think it would not be unexpected by dictionary-using APIs -- those aren't guaranteed any particular comparer anyway. Also VB refactorings can probably change case in examples like `routes.MapRoute(..., new {  id = "" })` without expecting it to break anything.

**Comment by svick** [comment]
There's already an existing issue for this: #51. Since this one seems to be more fleshed-out, should the that one be closed?

**Comment by ashmind** [comment]
@svick Right! And I even searched before making a proposal, but somehow missed it.

**Comment by mburbea** [comment]
My biggest concern with this feature is that how do you interact with old code that was compiled before this feature. That's why I was suggesting perhaps a different notation like `new ${}`. That way its not backward incompatible as they are technically different types.

**Comment by ashmind** [comment]
> My biggest concern with this feature is that how do you interact with old code that was compiled before this feature. That's why I was suggesting perhaps a different notation like new ${}. That way its not backward incompatible as they are technically different types.

Since anonymous types are mostly created in the user code to be passed into frameworks (as in examples I provided) and not other way around, it doesn't feel like a huge problem.

If you need to support old code passing untyped anonymous objects into your framework, you can do that -- and you will still be able to gain a performance benefit if you test-cast to dictionary first.

However, depending on your code, you might just as easily say "I accept dictionaries only", and then it would be a responsibility of the caller to sort it out -- either compile with newer C# or create dictionary themselves.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
