### ISSUE TITLE
Intellisense not working for lambdas with parameters

### ISSUE THREAD

**Issue by javiercn** [dotnet/roslyn#11412]
**Version Used**: 
1.3.0-beta1-20160429-01  (bundled with asp.net core rc2)
I also reproed it on a console app. (So VS2015 Update 2).

**Steps to Reproduce**:

1. Type the following on a console app.
```
namespace EditorLambdaRepro
{
    class Program
    {
        static void Main(string[] args)
        {
            IHelper<Customer> helper = null;
        }
    }
 
    public interface IHelper<T>
    {
        void TakingExpression<K>(Expression<Func<T, K>> expression);
        void TakingExpressionAndParameters<K>(Expression<Func<T, K>> expression, object parameter1);
        void TakingExpressionAndParameters<K>(Expression<Func<T, K>> expression, object parameter1, object parameter2);
    }
 
    public class Customer
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
```

2. Type the following on the line below the helper declaration
```helper.TakingExpressionAndParameters(e => e.)``` 

**Expected Behavior**:
Intellisense should be displayed for the members of Customer
 
**Actual Behavior**:
No intellisense available.
If I hover over e with the mouse, it tells me its of type '?'
If I do the same thing for the method TakingExpression, intellisense is always displayed correctly.

*This is the case working fine*
![image](https://cloud.githubusercontent.com/assets/6995051/15377487/d72355a4-1d10-11e6-96d5-9da580c8ad62.png)

*This is the case with the issue*
![image](https://cloud.githubusercontent.com/assets/6995051/15377492/e82093bc-1d10-11e6-8051-0ef350d147f5.png)

**Impact**
This is somewhat a common pattern in Razor (Asp.Net view engine) where we have a lot of helpers for generating HTML in the form of ```@Html.RadioButtonFor(x => x.Member, value)``` in order to generate forms inputs and other HTML controls. This is also something common in other modeling/mapping frameworks.

**Comment by gafter** [comment]
Related to #11358

**Comment by gafter** [comment]
This is fixed in #11981

**Comment by javiercn** [comment]
Thanks for the fix! Is there a way we can try this out in VS? (The scenario here involves the Razor editor and want to make sure it works E2E)

**Comment by Pilchie** [comment]
Try installing the VSIX for VS2015 from https://dotnet.myget.org/gallery/roslyn-master-nightly and see if it fixes the scenario.
