### ISSUE TITLE
Qualify Field Access is failing OptionPagesDTE Integration test in both C# and VB.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#11430]
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_future_win_vsi_p3/376/consoleFull#-163028854861aefe2b-268e-4e71-8c03-11b4c0acbfbc

**Test Result (2 failures)**
OptionPagesDTE.Verify C# changes are persisted
OptionPagesDTE.Verify VB changes are persisted

**Individual TAO Test Failure**
Failing integration tests: OptionPagesDTE.xml 

```
16:58:59    Executing action [5/18/2016 11:53:41 PM] VerifyToolsOption
16:58:59 Verifying option: TextEditor > CSharp-Specific > Style_QualifyFieldAccess = 1)
16:58:59 --------------------------------
16:58:59 System.Exception: Actual and expected items don't match:
16:58:59 Expected: 1
16:58:59 Actual: 0
16:58:59 
16:58:59    at Roslyn.VSHosting.Test.Utilities.CompareAndThrowIfNotEqual[TItem](TItem expected, TItem actual) in d:\j\workspace\roslyn-intern---4a2efb80\Closed\Hosting\Test\Actions\VisualStudio\Utilities\Utilities.cs:line 15
16:58:59    at Roslyn.VSHosting.Test.VerifyToolsOptionAction.Execute(TaoEngine engine) in d:\j\workspace\roslyn-intern---4a2efb80\Closed\Hosting\Test\Actions\VisualStudio\VerifyToolsOptionAction.cs:line 17
16:58:59    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
16:58:59    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
```

```
16:58:59 Verifying option: TextEditor > Basic-Specific > Style_QualifyFieldAccess = True)
16:58:59 --------------------------------
16:58:59 System.Exception: Actual and expected items don't match:
16:58:59 Expected: True
16:58:59 Actual: False
16:58:59 
16:58:59    at Roslyn.VSHosting.Test.Utilities.CompareAndThrowIfNotEqual[TItem](TItem expected, TItem actual) in d:\j\workspace\roslyn-intern---4a2efb80\Closed\Hosting\Test\Actions\VisualStudio\Utilities\Utilities.cs:line 15
16:58:59    at Roslyn.VSHosting.Test.VerifyToolsOptionAction.Execute(TaoEngine engine) in d:\j\workspace\roslyn-intern---4a2efb80\Closed\Hosting\Test\Actions\VisualStudio\VerifyToolsOptionAction.cs:line 17
16:58:59    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
16:58:59    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
16:58:59 ================================
```

**Comment by brettfo** [comment]
This failure is from before the changes to complex XML in #11227 and all VSI tests are currently passing in future so I'm going to optimistically close this since there have been a lot of changes.

That and the fact that Jenkins has already cleaned up this run.

**Comment by heejaechang** [comment]
failed build link - http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/stabilization/job/windows_vsi_p3_open_prtest/3/

**Comment by Pilchie** [comment]
This just failed again in https://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_dev15_p3/1/

Still with only one failure in the last month, moving out of Preview 4.

**Comment by mavasani** [comment]
Failed again: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_prtest/473/console

**Comment by mavasani** [comment]
Test failed again today, due to a different verification failure: 

http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_prtest/476/VS_Integration_Test_Logs/

```
Verifying option: TextEditor > CSharp-Specific > SortUsings_PlaceSystemFirst = 0
 --------------------------------
 System.Exception: Actual and expected items don't match:
 Expected: 0
 Actual: 1

    at Roslyn.VSHosting.Test.Utilities.CompareAndThrowIfNotEqual[TItem](TItem expected, TItem actual) in d:\j\workspace\windows_vsi_p---5e702c54\Closed\Hosting\Test\Actions\VisualStudio\Utilities\Utilities.cs:line 15
    at Roslyn.VSHosting.Test.VerifyToolsOptionAction.Execute(TaoEngine engine) in d:\j\workspace\windows_vsi_p---5e702c54\Closed\Hosting\Test\Actions\VisualStudio\VerifyToolsOptionAction.cs:line 40
    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\omni\TAO\Tao.Engine\ActionExecutor.cs:line 139
    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\omni\TAO\Tao.Engine\ActionExecutor.cs:line 36
 ================================
```

I'll mark this Urgency-Now if it fails again soon.

**Comment by mavasani** [comment]
Test failed again: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_open_prtest/334/console

Marking this Urgency-Now.

```
15:04:18 Verifying option: TextEditor > CSharp-Specific > SortUsings_PlaceSystemFirst = 0
15:04:18 --------------------------------
15:04:18 System.Exception: Actual and expected items don't match:
15:04:18 Expected: 0
15:04:18 Actual: 1
```

**Comment by mavasani** [comment]
This test has failed at least 4-5 times today. I am skipping the test - please re-enable when you fix it.

http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_prtest/500/

http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_prtest/497/

http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_prtest/498/

**Comment by Pilchie** [comment]
Is this still an issue?

**Comment by Pilchie** [comment]
Is this related to the other options bugs you have?

**Comment by heejaechang** [comment]
@Pilchie I assume, here you is @jmarolf ? not me about bool? option persist changes for FSA?

**Comment by Pilchie** [comment]
Yes, @jmarolf has other option persistence bugs with roaming settings.

**Comment by sharwell** [comment]
Where is this test? I can't find it to fix it...

**Comment by CyrusNajmabadi** [comment]
I can't find this test.  closing out.
