### ISSUE TITLE
Some test runs don't archive artifacts

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#11431]
For example,
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_vsi0/135
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_vsi0/110
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_vsi1/132/
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/80/

Not having artifacts available makes it hard to investigate intermittent issues.

**Comment by mavasani** [comment]
+1

This blocks investigation for intermittent failures in Jenkins.
