### ISSUE TITLE
CI failing due to failure to publish HTML (looking in wrong dir)

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn#11452]
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_debug_eta_prtest/1/console

```
03:35:52 ERROR: Specified HTML directory 'd:\j\workspace\windows_debug---34d39bc5\Open\Binaries\Release\ETAIntegrationTestLogs' does not exist.
03:35:52 Build step 'Publish HTML reports' changed build result to FAILURE
```

@jaredpar, might this have anything to do with recent Jenkins change?

**Comment by nguerrera** [comment]
Hit this again on retest. :( Guessing that the fact that this is a *debug* build but it's looks for \Open\Binaries\*Release* is the issue.

**Comment by nguerrera** [comment]
I believe I've found the issue and submitted a PR with potential fix.

**Comment by nguerrera** [comment]
I now have a theory that I can't just update the groovy in a PR. Assigning to @jaredpar to apply fix as appropriate.

**Comment by jaredpar** [comment]
@nguerrera when you PR a groovy script you won't see the effect of the change in the PR.  It has to actually be committed to see it running.  There is a way to generate the jobs from the change but they won't run against the PR.

**Comment by jaredpar** [comment]
Confirmed @nguerrera fix does fix the issue. Closing.
