### ISSUE TITLE
"Build + Intellisense" in error list behaving as "IntelliSense Only"

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn#11462]
I am not seeing all analyzer warnings from the build in the error list unless I select "Build only"

**Version Used**: 1.3 (synced to master at https://github.com/dotnet/roslyn/commit/cd21f84c035b516ce25ae79d9d21b4fefbcb1126)

**Steps to Reproduce**:

1. Follow https://github.com/dotnet/roslyn-internal/tree/master/Closed/Test/Solutions/RegenerateNewtonsoftErrorLogBaseline.txt up to step 7 (build solution)
2. Switch between "Build Only", "Build + IntelliSense" and "IntelliSense Only"
3. Contrast warning counts

**Expected Behavior**:
When I have Build + IntelliSense selected:
-  I get a superset of Build results in my error list.
- At least all of the warnings from the build in the output  window are in my error list

**Actual Behavior**:
Build + IntelliSense is behaving as IntelliSense only. There are thousands of warnings in the build, but with 'Build + IntelliSense' I see only the warnings for opened files.

**Comment by nguerrera** [comment]
@mavasani not sure how to tag, route this.

**Comment by mavasani** [comment]
Tagging @heejaechang

**Comment by mavasani** [comment]
Nick, you can add label Area-Analyzers.

**Comment by davkean** [comment]
Looks like this: https://github.com/dotnet/roslyn/issues/11378

**Comment by nguerrera** [comment]
Yep. Closing as dup.
