### ISSUE TITLE
Completion-API is still not public enough.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#11463]
Even after making our Completion API public, TypeScript still needs access to some internal parts of the API.  Specifically, they need to provide their own CompletionHelper to provide some flexible sorting/matching that our public API doesn't support.  You can see that code here:

https://devdiv.visualstudio.com/DevDiv/_git/TypeScript?path=%2FVS%2FLanguageService%2FTypeScriptLanguageService%2FFeatures%2FCompletion%2FTypeScriptCompletionHelper.cs&version=GBmaster-update3&_a=contents

The use case for them is when they're in a .js file.  In .js files they provide "strong" completions that are provided by the compiler actually analyzing code, and "weak" completions which are essentially all the identifiers in the whole project.  "strong" completions come first and should always be matched over "weak" completions.  

While i believe that sorting would be possible (as CompletionItem has a sort string), there is no way to customize matching behavior.  For TS they want "strong" match to beat any "weak" match.  i.e. a substring "strong" match should still beat an exact "weak" match.

If we can provide this behavior, then TS would not need access to this API.

**Comment by CyrusNajmabadi** [comment]
Tagging @mattwar  and @paulvanbrenk

**Comment by mattwar** [comment]
It would be better to find ways to add behavior describing data to the existing completion service API than make the CompletionHelper public.  It only exists due to failing to be able to cleanly describe some behavior differences between CSharp and VB completion.

**Comment by CyrusNajmabadi** [comment]
Right, i'm not asking for CompletoinHelper to be public.  I'm asking for there to be a way for C#/VB/TS to customize this behavior only using the public API.  Note that right now even C#/VB use internals.  That's really not something we should be doing.  If our own languages need internal access, then ti's highly likely (as we've seen here) that other languages will as well.
