### ISSUE TITLE
Workspaces should not be outputing an explicit BOM

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#1146]
Consider the code inside `Workspace.ApplyDocumentTextChange`:

- https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Desktop/Workspace/MSBuild/MSBuildWorkspace.cs#L972

This code is using an explicit UTF8 BOM in the case an encoding can't be detected.  This seems like a bug.  Shouldn't the default be a no-BOM UTF8 encoding?

**Comment by Pilchie** [comment]
Well, it *was* the design, since that's been the typical thing VS does.  However, given that most non-Windows editors don't handle BOMs well, we should consider changing it.
