### ISSUE TITLE
vbc can't not reference mscorlib

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/roslyn#11472]
**Version Used**: master as of 5/20

**Steps to Reproduce**:

Compile something targeting .NET Core (System.Runtime)

**Expected Behavior**:

Generates a .DLL with no reference to mscorlib

**Actual Behavior**:

Generates a .DLL with reference to mscorlib.

I think the problem is around line 1360 in VisualBasicCommandLineParser.vb. System.Runtime in .NET Core currently _has_ references (I checked with ildasm).

I'm probably going to change my local copy to make /nostdlib not call this function either. Better would be adding a /nomscorlib but ...

**Comment by davkean** [comment]
The System.Runtime.dll containing System.Object should not contain references. System.Runtime "the facade" will contain references, including mscorlib. Which System.Runtime are you referring to?

**Comment by jhudsoncedaron** [comment]
I have installed the sdk for .NET Core. There is only one copy of System.Runtime under c:\program files\dotnet.

**Comment by davkean** [comment]
The version of System.Runtime.dll under C:\Program Files\DotNet is not expected to be referenced directly - the System.Runtime you want to reference is from the System.Runtime nuget package.

**Comment by jhudsoncedaron** [comment]
All right, that got it working. Nice 613 character command line.

Incidentally I got here because dotnet-compile-vbc is smashed so bad it throws missing reference errors trying to compile.

I guess all we need to do is improve the documents.

As far as I can tell, getting all the reference dlls out of nuget packages (and that is a pain when you can't use a project file) makes /sdkpath worthless.

The minimal list of references are
System.Runtime.dll
System.ComponentModel.dll
System.Diagnostics.Debug.dll
System.Diagnostics.Tools.dll

Microsoft.VisualBasic.dll appears to be hosed ATM so I had to write my own to satisfy the stuff the compiler generates references to.

**Comment by jhudsoncedaron** [comment]
Closing as .NET Core 2.0 toolchain builds vb projects out of box.
