### ISSUE TITLE
When implementing an abstract base class in non-abstract class, offer to generate "public" constructor

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11477]
When implementing an abstract base class, in non-abstract class, I get offered to generate a "protected" constructor, but in this case, I almost always want a public constructor:

![image](https://cloud.githubusercontent.com/assets/1103906/15446236/bb35964a-1ecd-11e6-8999-de9e19ff9e6f.png)

I only want protected constructor if I'm also an abstract class.

**Comment by DustinCampbell** [comment]
Yes! Did I never file this? It's been driving me nuts.

**Comment by CyrusNajmabadi** [comment]
Hrmm... I don't repro this:

![image](https://cloud.githubusercontent.com/assets/4564579/17500748/21a072f8-5da6-11e6-8514-2910b5555f13.png)

Do you have more of a repro for this?

**Comment by CyrusNajmabadi** [comment]
Also, the code that controls this is:

```c#
                var constructor = CodeGenerationSymbolFactory.CreateConstructorSymbol(
                    attributes: null,
                    accessibility: Accessibility.Public,
                    modifiers: default(DeclarationModifiers),
```

And that code has been that way as far back as i have tracked this file (about a year).  So i'm a bit confused as to how this was ever showing up as protected.

**Comment by davkean** [comment]
Yeah, weird, for some reason I can only repro the reverse:

```
   internal abstract class Bar
    {
        protected Bar(string bar, string foo = null)
        {
        }
    }

    internal abstract class Foo : Bar
    {
        
    }
```

Above get offered to add public constructor.

**Comment by CyrusNajmabadi** [comment]
I'm going to close this then.  If you happen to figure out a repro for this, let me know.
