### ISSUE TITLE
Insertion tool should mark inserted builds with "retain indefinitely"

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#11473]
The current process for inserting builds requires that they get marked retain indefinitely as a manual process after they are inserted. The tool should do that automatically, and a follow up process should clean those up if they aren't needed.

**Comment by panopticoncentral** [comment]
I think we did the first part but I don't believe we did the second part (cleanup).

**Comment by jasonmalinowski** [comment]
Oops this is a dupe of #9314.
