### ISSUE TITLE
Auto-suggest <paramref names, similar to <param

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11488]
Today I get offered automatically inside completion window to add `<param/>` with the names pre-entered (such as capability below), it would be great to apply this same thing to `<paramref/>`:

![image](https://cloud.githubusercontent.com/assets/1103906/15451267/c611632c-1f6e-11e6-9f29-96e14abf4848.png)

**Comment by aochagavia** [comment]
I would like to tackle this. Following @pdelvo's suggestion on Gitter, I will first look at [this completion provider](https://github.com/pdelvo/roslyn/blob/53577948f6f3416147a10f6f54a69cf8ac37629b/src/EditorFeatures/CSharp/Completion/CompletionProviders/XmlDocCommentCompletion/XmlDocCommentCompletionProvider.cs#L246) and go on from there.
