### ISSUE TITLE
Comparing two versions of same dll

### ISSUE THREAD

**Issue by acesiddhu** [dotnet/roslyn#11492]
Hi,
My requirement is to enumerate all the methods that are changed between two versions of same assembly. Essentially comparing IL of the two dlls. This should work cross plat as well. Any pointers would really help. Thanks

**Comment by acesiddhu** [comment]
Ping :)

**Comment by jmarolf** [comment]
I assume you can use the metadata reader to do this.  @tmat would know the specifics.

**Comment by acesiddhu** [comment]
@tmat any pointers here?

**Comment by jcouv** [comment]
@acesiddhu You'll want to use the MetadataReader type from this [nupkg](https://www.nuget.org/packages/System.Reflection.Metadata).

You can take a look at the methods called `DumpXYZ` in [MetadataReaderUtils](https://github.com/dotnet/roslyn/blob/master/src/Test/Utilities/Portable/Metadata/MetadataReaderUtils.cs#L250) for some inspiration on how to use the API to dig into the metadata.
