### ISSUE TITLE
Got unnecessary cast when upgrading a WinForms dialog from 2.0 -> 4.0

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11495]
Upgraded a dialog from 2.0 -> 4.0 here: https://github.com/dotnet/roslyn-project-system/pull/177/commits/4fb9d33f7a3fe7cd3a01086b8a9575c0f5d51f63

This resulted in the following unnecessary cast inserted into the code gen:

``` VB
Me.Macro = CType(New System.Windows.Forms.ColumnHeader(), System.Windows.Forms.ColumnHeader)
```

Not sure if this is a WinForms or Roslyn issue, so filed it here first.

**Comment by DustinCampbell** [comment]
Does it happen in VS 2013?

**Comment by DustinCampbell** [comment]
FWIW, if this is in the InitializeComponent method, it is almost certainly WinForms. WinForms generates that code with CodeDom and inserts it directly into the buffer.
