### ISSUE TITLE
IDE Features should work on preprocessor symbols (rename, FAR, GTD, completion, etc)

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#11499]
Would be great if the autocomplete for `#if` directive (which now only contains `true` and `false` values) could contain all symbols currently defined in the scope.

- [ ] Completion workitem https://github.com/dotnet/roslyn/issues/49694

**Comment by Pilchie** [comment]
Yes, this is something we've wanted to do for a while now - in fact we were tracking it on our internal backlog as 124326, but we'll use this now.

**Comment by Pilchie** [comment]
Updating title since this is actually a more general set of features.

**Comment by jaredpar** [comment]
I just started working on a multi-targetted project. The ability to complete all of the conditional defines after I type `#if ` would have been an enormous help. Lacking that I'm just guessing at what the mapping between TF and `#define` is.

**Comment by CyrusNajmabadi** [comment]
We support completion for this now, as well as FAR.  Closing out as sufficient.
