### ISSUE TITLE
Quick action to convert expression body to normal body and back

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#11491]
Would be great if I could convert
```C#
static int Add(int, int y)
{
    return x + y;
}
```
to
```C#
static int Add(int x, int y) => x + y;
```
and back using quick actions (could even be code style)

And would be helpful for extracting fields from expression body too (#528).

**Comment by MillKaDe** [comment]
That is already available as a 3rd party extension for Visual Studio.
Unfortunately I can't figure out, which one - but it must be one of these two:
- "Refactoring Essentials for Visual Studio" (by IC#Code)
- "C# Essentials" (by Dustin Campbell)

**Comment by Pilchie** [comment]
We're already tracking the conversion *to* expression bodied members in https://github.com/dotnet/roslyn/issues/7045.  I'll make note there that we should also support going back.

@MillKaDe It's in C# Essentials right now.
