### ISSUE TITLE
#if preprocessor autocomplete trimmed

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#11498]
**Version Used**: 15.0.25302.0

**Steps to Reproduce**:

1. Create a console application.
2. Anywhere in the class, start typing `#if MYGREATVARIABLE`
3. Observe.

**Actual Behavior**:
The written text is used in the autocomplete (as it was a delegate name) and gets trimmed:
![untitled](https://cloud.githubusercontent.com/assets/10546952/15470927/2e98befe-20eb-11e6-89af-6a0d5320e1be.png)

**Expected Behavior**:
Either do not use the text written in the autocomplete list, like **usually** is the case at the end of the file:
![untitled](https://cloud.githubusercontent.com/assets/10546952/15470950/5662d58c-20eb-11e6-8cb5-f500cfc97a0c.png)
or expand it appropriately.

**Comment by Pilchie** [comment]
Since we haven't implemented #11499 yet, we show the completion in suggestion mode, so that it doesn't stomp on what you're trying to type.  At the same time, I believe that the editor picks the width of completion from the initial size of the elements and doesn't resize during the session, which is why this happens.  @olegtk - does that sound right to you?

**Comment by olegtk** [comment]
Yes, sounds right to me. We recently fixed a related issue of completion clipping during filtering (e.g. when you type "<h1" and then hit backspace) - now completion can grow wider (but not shrink) on ICompletionSession.Filter(), but there is no filtering in this scenario. File a bug if it's bad enough.

**Comment by Pilchie** [comment]
@miloush do you want to file a bug on Connect for the editor, or do you want me to file one on your behalf?

**Comment by miloush** [comment]
@Pilchie Filed, thanks. [2846395](https://connect.microsoft.com/VisualStudio/feedback/details/2846395)
