### ISSUE TITLE
add DisasterRecoveryManager support before we crash.

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#11508]
right now, disaster recovery manager doesnt expose API for others to consume its functionality in VS.

we should make it to expose that and consume its API in some cases where we crash VS. in some exception, we might not be able to, but there will be cases where we can. (ex, low mem situation)

cc: @bertanaygun Bertan is the expert when we decide to implement it.

**Comment by heejaechang** [comment]
related to https://github.com/dotnet/roslyn/pull/11479

**Comment by Pilchie** [comment]
Does this API exist yet?  Is it something we can consume for RC?

**Comment by heejaechang** [comment]
@dpoeschl I have no idea. opened a bug since someone suggested to open a bug to track this. basically, when we intentionally crash host (FatalError), try save all users data before we do.

**Comment by heejaechang** [comment]
@dpoeschl by the way, if we are not going to implement this, we should close this bug rather than giving it to me.

**Comment by dpoeschl** [comment]
@tmeschter This is under `Tenet-Reliability` - can you re-triage appropriately?

**Comment by heejaechang** [comment]
@Pilchie @dpoeschl @tmeschter I will close this bug. if IDE wants it, please re-open.
