### ISSUE TITLE
Make Diagnostic Arguments property public

### ISSUE THREAD

**Issue by fabiocav** [dotnet/roslyn#11523]
**Version Used**: 
1.2.2
**Steps to Reproduce**:
1. Attempt to use the Arguments property on `Microsoft.CodeAnalysis.Diagnostic

**Expected Behavior**:
Ability to use the property from user code

**Actual Behavior**:
Unable to use the property. Property is currently internal.

It would be helpful to have access to diagnostics arguments as it is needed in some scenarios (e.g. we run into limitations in the Azure Functions runtime when trying to provide additional diagnostic details that need that information)

**Comment by srivatsn** [comment]
The Diagnostic type is serializable and so we don't want to expose an enumerable of object natively on the type. What is your scenario for needing Arguments? Can you use the Properties dictionary on the type to stuff extra information?

**Comment by srivatsn** [comment]
Closing this issue since Arguments can't be opened up because of the serializability restriction. If the Properties dictionary doesn't suffice let us know.

**Comment by fabiocav** [comment]
@srivatsn sorry about the delayed response. Properties would be fine if we were storing custom state, the diagnostic arguments used to format the message are not available there. We need to use the arguments in order to display meaningful messages to users (derived from the original diagnostic issue). For example, when handling CS0103, there's no simple way to get the argument name out of the diagnostic and we're forced to resort to private reflection or message parsing.

**Comment by srivatsn** [comment]
Your scenario is that you are getting diagnostics from elsewhere (from the compiler in this case) and you want to inspect it to extract the fillins? Unfortunately there's no guarantee that the Arguments would be available because we could serialize the diagnostic to disk (so that we don't keep a large number of diagnostics in memory) and then bring it back when needed. In those cases all we'll have is the message string. I think, in this case, you'll have to resort to message parsing.

**Comment by CyrusNajmabadi** [comment]
We can't expose arguments because we'd then have to ensure that arguments could all be serialized. Part of our design is that diagnostics are computed in another process and then marshaled back to the host.  This is easy for things like the reified string message. It would not be possible to do the same with the arguments (which are rich objects and which are an impl detail). 

> I need the type info for both A and B, but the types are defined in some referenced dll and nested in namespaces

We do not provide any contract for diagnostics. So those arguments are just as likely to just be strings. 

If you want this info, you'll have to analyze the source itself to figure this out. Or propose a dedicated (non-diagnostic) API for this.

**Comment by TymurGubayev** [comment]
Would something like an alternate message string where the type names are serialized with `FullyQualifiedSymbolFormat` be possible?

**Comment by CyrusNajmabadi** [comment]
@TymurGubayev no. Diagnostics are explicitly *not* a contract in Roslyn.

**Comment by TymurGubayev** [comment]
> @TymurGubayev no. Diagnostics are explicitly _not_ a contract in Roslyn.

what does this actually mean? What is the `SemanticModel.GetDiagnostics` returning?

**Comment by CyrusNajmabadi** [comment]
Opaque objects with just a message,  ID and span.  None of which are
guaranteed.

By saying "not a contract" we mean that we will buy sign up to anyone
trying to decompose a diagnostic to extract out additional details (like
type names). Our semantic apis are for that purpose.

**Comment by TymurGubayev** [comment]
is it possible to add another not-guaranteed property in addition to what the Diagnostic already has?

Alternatively, how about an overload of `SemanticModel.GetDiagnostics` (and its siblings) with an `out Dictionary<Diagnostic, AdditionalInfo>`?

**Comment by CyrusNajmabadi** [comment]
> is it possible to add another not-guaranteed property in addition to what the Diagnostic already has?

Yes. But being "not guaranteed" would make it useful for your purposes. For example, in VS we likely wouldn't preserve it across processes. 

> Alternatively, how about an overload of SemanticModel.GetDiagnostics (and its siblings) with an out Dictionary<Diagnostic, AdditionalInfo>?

That already exists. What you are describing is the documented and supported API that semanticmodel exposes.  We are very willing to invest there. It just wouldn't be tied to diagnostics.  It will be tied to nodes, symbols, operations, etc.

**Comment by TymurGubayev** [comment]
> > is it possible to add another not-guaranteed property in addition to what the Diagnostic already has?
> 
> Yes. But being "not guaranteed" would make it useful for your purposes. For example, in VS we likely wouldn't preserve it across processes.

In my case, I'm using it from a stand-alone tool, so no VS instance is involved.

> > Alternatively, how about an overload of SemanticModel.GetDiagnostics (and its siblings) with an out Dictionary<Diagnostic, AdditionalInfo>?
> 
> That already exists. What you are describing is the documented and supported API that semanticmodel exposes. We are very willing to invest there. It just wouldn't be tied to diagnostics. It will be tied to nodes, symbols, operations, etc.

Which overload of `SemanticModel.GetDiagnostics` would give me for the diagnostic with `id="BC30512"` the type symbols involved?

**Comment by CyrusNajmabadi** [comment]
> Which overload of SemanticModel.GetDiagnostics would give me for the diagnostic with id="BC30512" the type symbols involved?

You'd likely need to examine the data returned from GetSymbolInfo, GetTypeInfo or GetOperation.
