### ISSUE TITLE
Inline temporary variable does not parenthesize awaited call

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#11527]
**Version Used**: VS2015.2

**Steps to Reproduce**:

``` csharp
using System.Linq;
using System.Threading.Tasks;

class Program
{
    static void Main(string[] args)
    {
        AsyncMain().Wait();
    }

    static async Task AsyncMain()
    {
        var $$text = await GetText();
        bool hasText = text.Any();
    }

    static async Task<string> GetText()
    {
        return "Hello";
    }
}
```
1. Set cursor to `$$`
2. Press `CTRL + .` to bring up the refactorings
3. Choose `Inline temporary variable`

**Expected Behavior**:

``` csharp
bool hasText = (await GetText()).Any();
```

**Actual Behavior**:

``` csharp
bool hasText = await GetText().Any();
```

causing error CS1061 since `Task<string>` does not contain a method named Any

**Comment by Pilchie** [comment]
I feel like I saw a PR for something related recently?  @CyrusNajmabadi Was that you?

**Comment by alrz** [comment]
#15530?

**Comment by Pilchie** [comment]
Thanks!  Dupe of https://github.com/dotnet/roslyn/issues/15530
