### ISSUE TITLE
Proposal: Open up the existing code generation framework

### ISSUE THREAD

**Issue by JackUkleja** [dotnet/roslyn#11520]
There are lots of potentially useful parts of Roslyn that I would like to use for code generation that are currently internal classes. 

For example `TypeSyntaxGeneratorVisitor` - a class that generates syntax trees from type symbols. It is used in the `MetadataAsSource` pipeline, which most Visual Studio users will be familiar with - I think it's what lets them browse "source code" for libraries for which they don't have the actual source.

I understand there is a cost in making internal classes public, but as I think there would be many people looking to generate code based on existing symbols (for example generating stubs, interfaces, decorators, WCF services etc) it could be a good investment.

**Comment by Pilchie** [comment]
@JackUkleja Have you seen the [SyntaxGenerator](http://source.roslyn.io/Microsoft.CodeAnalysis.Workspaces/R/3c40e627ffcd3bf7.html) type that is public?

Tag @mattwar

**Comment by Pilchie** [comment]
Please take a look at `SyntaxGenerator` and let us know what is missing that you need.
