### ISSUE TITLE
give an hint when using Action as parameter in an async call

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/roslyn#11525]
After two days fighting to find the problem I would like to ask if is possible to give this kind of warning, because could be a source of headache.
I explain the scenario:
I have a few services class wtih async methods inside an mvc application, and since I would like to improve in a simple way the logging I tried to add a `Action<string>WriteLog` parameter to the function  calls, using it simply to write the string to write in the log file. I did a few test and worked fine, so I added this logging to all the calls, but after this I started to have a few problems, with server calls execute but doing nothing without any exception.
In short I solved the problem using a `Func<string,Task>WriteLog` parameter, awating all the calls: if I remember well inside an async function the code is rewrote as a state machine to support the async operations, and looks like that executing an external non async function inside could lead to odd behaviors.

Trying to log the mvc call I found this:

```
public async Task<ActionResult> DoCall()
{
  WriteLog("Start");
  await Service.DoCall(WriteLog);
  WriteLog("End");
....
}
```

In the Log I found that both the start row and end row is writte, a test call inside the service call is executed, but nothing else is executed inside the service call.
Honestly I needed a bit of time to understand the problem, especially because an apparently simple change broke working code, and I had different behavior running in debug.

btw: converting to async from **void WriteLog** to **async Task WriteLog** reminded me that async introduce a sort of polymorphism in the return value, because depending on the presence of await or not the return value is different, and especially when I change from void to async Task I have be very careful updating all the call to the method, otherwise the runtime behavior change and the caller continues the execution before the method is completed.
Is there any way to check this potential problem?

**Comment by gafter** [comment]
Can you please a concise but complete example demonstrating the scenario and the diagnostic you'd like for that scenario?

**Comment by lucamorelli** [comment]
Let's start explaining the situation:
originally in the controller I had this situation

```
private void WriteLog(string messaggio)
{
     var basePath = this.HttpContext.Server.MapPath("~/App_Data");
     using (TextWriter sw = new StreamWriter(Path.Combine(basePath, "Log.Txt"), true))
     {
          await sw.WriteLineAsync(DateTime.Now.ToString("dd/MM/yyyy HH:mm") + " > " + messaggio);
     }
}

public ActionResult ScriviSettori(int id)
{
    var settings = new Settings();
    try
    {
        WriteLog("ScriviSettori(int id) inizio");
        var risultato = await ArchivioService.ScriviSettori(id, settings.gisDataPath, settings.prgSettori);
        WriteLog("ScriviSettori(int id) fine");
        return Json(risultato, JsonRequestBehavior.AllowGet);
    }
    catch (Exception exc) {
        WriteLog(exc.Message + Environment.NewLine + exc.StackTrace, "eccezioni");
        throw;
   }
}
```

this way worked fine because all the async closed was closed inside the call. I changed this way

```
public async Task<ActionResult> ScriviSettori(int id)
{
     var settings = new Settings();
     try
     {
          WriteLog("ScriviSettori(int id) inizio");
          var risultato = await ArchivioService.ScriviSettori(id, settings.gisDataPath, settings.prgSettori, WriteLog);
          WriteLog("ScriviSettori(int id) fine");
          return Json(risultato, JsonRequestBehavior.AllowGet);
    }
    catch (Exception exc) {
        WriteLog(exc.Message + Environment.NewLine + exc.StackTrace);
        throw;
    }
}

and this was the content of the called function

public async Task<bool> ScriviSettori(int id, string settingsGisDataPath, string settingsPrgSettori, Action<string>WriteLog)
        {
            WriteLog?.Invoke("Inizio Scrittura IdProgetto :" + id);
            using (adminEntities adm = adminEntities.GetDefaultServerConn())
            {
                ....

```

At this point I started to have problems, both the call to the logging routine worked fine, the first call to the WriteLog inside the routine execute correctly but, without any error or exception, the subsequent code was never execute.

When I figured out the problem I changed the code this way

```
private async Task WriteLog(string messaggio)
{
    var basePath = this.HttpContext.Server.MapPath("~/App_Data");
    using (TextWriter sw = new StreamWriter(Path.Combine(basePath, "Log.Txt"), true))
    {
        await sw.WriteLineAsync(DateTime.Now.ToString("dd/MM/yyyy HH:mm") + " > " + messaggio);
    }
}

public async Task<ActionResult> ScriviSettori(int id)
{
    var settings = new Settings();
    try
    {
        await WriteLog("ScriviSettori(int id) inizio");
        var risultato = await ArchivioService.ScriviSettori(id, settings.gisDataPath, settings.prgSettori, WriteLog);
       await WriteDailyLog("ScriviSettori(int id) fine");
       return Json(risultato, JsonRequestBehavior.AllowGet);
    }
    catch (Exception exc) {
        await WriteLog(exc.Message + Environment.NewLine + exc.StackTrace, "eccezioni");
        throw;
    }

public async Task<bool> ScriviSettori(int id, string settingsGisDataPath, string settingsPrgSettori, Func<string, Task>WriteLog)
{
    await WriteLog?.Invoke("Inizio Scrittura IdProgetto :" + id);
    using (adminEntities adm = adminEntities.GetDefaultServerConn())
    {
......

```

Now everything seems to work fine.
If the problem is the one I suppose, and call a sync action inside an async function alters the execution of the program this way, I suppose that  by default the declaration of an action parameter in this context is dangerous, and could be signaled in the code analyzers way.

About the second request, as you can see, I changed the logging routine prototype from 
`private void WriteLog(string messaggio)`
to 
`private async Task WriteLog(string messaggio)`

and this change the behavior of the several calls to

```
     try
     {
        WriteLog("ScriviSettori(int id) inizio");
```
 that I already had in the code and I had to find every call and add the await.
Generally speaking I think that is sospicious because could lead to unexpected behavior, especially in a mvc call, where all the resources tend to be freed after the and of the action call.
Even in this case I think could be useful to add a code analyzer, or something similar, that evidence this problem.

I hope I made clear the problem

**Comment by svick** [comment]
> call a sync action inside an async function alters the execution of the program

Calling sync method from async method is perfectly fine (even if it might not be the best practice). Though I am confused by your code: you claim it is sync, but then you use `await` inside `void WriteLine`, which wouldn't compile. If you actually had `async void WriteLine`, this could have been the source of your problem: you should use `async void` only when you have to.

---

>  I had to find every call and add the await

This already causes a warning:

> CS4014	Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.

---

Also, this code is wrong:

```c#
await WriteLog?.Invoke("Inizio Scrittura IdProgetto :" + id);
```

When the (confusingly named) `WriteLog` parameter is `null`, you will get a `NullReferenceException` when you try to `await null`. Maybe this would be worth a warning?

**Comment by lucamorelli** [comment]
sorry for the mistake, I was reconstructing the previous code. I corrected it now,

> Calling sync method from async method is perfectly fine (even if it might not be the best practice).  

Honestly I don't know: the problems started adding the action inside the async function and disappeared moving to a Func

> await WriteLog?.Invoke("Inizio Scrittura IdProgetto :" + id);
> When the (confusingly named) WriteLog parameter is null, you will get a NullReferenceException when you try to await null. Maybe this would be worth a warning?
You are right, at the moment I just followed the indication of the code Analyzer, but at the moment is not an issue: the controller is quite short and I check the correctness of the call

**Comment by AdamCLarsen** [comment]
We encountered a slimier issues, here are some examples we found where CS4014 doesn't get raised, but result in unawaited async code.

```
public class ExampleAsync
{
	#region Should warn

	public void DoWorkPassInAction()
	{
		// Should warn not awaited.
		Action<string, int> a = async (s, i) =>
		{
			await TestAsync(s);
		};

		DoWork(a);

		// Should warn not awaited.
		DoWork(async (s, i) =>
		{
			await TestAsync(s);
		});
	}

	public void DoWorkPassInFuncOfT()
	{
		Func<string, int, Task> f = async (s, i) =>
		{
			await TestAsync(s);
		};

		// Would be nice if warn not awaited.
		DoWorkOfT(f);
	}

	public Action<string, int> DoWorkAction(string st)
	{
		// Should warn not awaited.
		return async (s, i) =>
		{
			await TestAsync(s);
		};
	}

	private void DoWork(Func<string, int, Task> a)
	{
		// Should warn not awaited.
		a("Bob", 1);
	}

	#endregion

	#region Called Methods

	private T DoWorkOfT<T>(Func<string, int, T> a)
	{
		return a("Bob", 1);
	}

	private void DoWork(Action<string, int> a)
	{
		a("Bob", 1);
	}

	private static async Task TestAsync(string s)
	{
		await Task.Delay(100);
	}

	#endregion
}
```

**Comment by AdamCLarsen** [comment]
I did some more digging, and it looks like this is behaving the same way any async void return is working.
