### ISSUE TITLE
Handle CSharp design rule suppressions in future

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/roslyn#11538]
Today's merge from master to future brought along turning on some new rule checks for design rules. I had to suppress several of them in Core and CSharp, mostly for new APIs related to tuples. These suppressions need to be reviewed and fixed.

**Comment by jcouv** [comment]
@panopticoncentral @VSadov Could you point me to the list of suppressions that need to be reviewed, or the commit that introduced them?

**Comment by VSadov** [comment]
I am not familiar with what we are talking about here. Is that some kind of style-cop things?

**Comment by jcouv** [comment]
I think it is related to this commit: https://github.com/dotnet/roslyn/commit/37ce424f36389de955465377471b90083ca6c2e9 (which is on the same day as this issue was opened).

**Comment by jcouv** [comment]
@jaredpar @gafter @VSadov Updated to RC as this impacts public API.

**Comment by jcouv** [comment]
The public API change was reviewed by the team and deemed ok. We kept the suppression.
