### ISSUE TITLE
[Area-IDE] The CSPROJ and Git problem

### ISSUE THREAD

**Issue by TheOpenDevProject** [dotnet/roslyn#11546]
Hey Guys,

So as we all know the `csproj` files are XML and are used to describe the project to visual studio. The problem seems to be when branching and merging this file format things very often don't merge properly at all and you have to rebuild the `csproj` XML yourself. This causes big issues in very large projects. I am not sure if another file format would be better suited and have easier merge results or if there is something I am missing.

Edit:
It seems people and the VS IDE team have the same idea as me.
https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/4512873-vs-ide-should-support-file-patterns-in-project-fil

**Comment by diryboy** [comment]
I [heard](https://www.youtube.com/watch?v=P9HqMZviaMg&list=PL0M0zPgJ3HSftTAAHttA3JQU4vOjXFquF&index=0) that the next version of VS would not insist adding entries for files one by one?

**Comment by TheOpenDevProject** [comment]
That would be fantastic

**Comment by drewnoakes** [comment]
I think the upcoming `project.json` (and xproj) stuff addresses the problem of csproj churn.

**Comment by DavidArno** [comment]
@drewnoakes,

`project.json` would indeed have fixed this. Frustratingly, MS - in all their alleged "openness" - [have unilaterally decided to kill off `project.json` and to switch .net core over to using `.csproj` files](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/). 

Whilst they are of course free to do this, it makes a complete mockery of their "developing in the open" claims. :disappointed:

**Comment by davkean** [comment]
Hey, thanks for the bug, we're tracking this over on new project system repro here: https://github.com/dotnet/roslyn-project-system/issues/106
