### ISSUE TITLE
Update nuget dependencies to RTM

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#11544]
Currently the following nuspecs under src\NuSpec depend on prerelease .net core packages.

> Microsoft.CodeAnalysis.BuildTask.Portable.nuspec
> Microsoft.CodeAnalysis.Common.nuspec
> Microsoft.CodeAnalysis.Scripting.Common.nuspec

e.g. `<dependency id="System.IO.Pipes" version="4.0.0-beta-23428" />`

We need to switch these to release packages by the time we are ready to ship 1.3 RTM.

**Comment by shyamnamboodiripad** [comment]
@jinujoseph This is probably already fixed but we should double check

**Comment by MattGertz** [comment]
@jinujoseph I'm assuming this is a non-issue now, so moving it out of 2.0 to get it off the radar.  If you concur, please close.

**Comment by jasonmalinowski** [comment]
Moving back to 2.0, as we have one more case to fix before we ship our 2.0 NuGets.

**Comment by jasonmalinowski** [comment]
This is actually done now.
