### ISSUE TITLE
Error when trying to run MSBuildToolset

### ISSUE THREAD

**Issue by omajid** [dotnet/roslyn#11558]
**Version Used**: 

roslyn: commit 41a4946757bf2a3bbf5911bf221c04a04e64f573
`dotnet --version` is `1.0.0-preview1-002702`

**Steps to Reproduce**:

I did these steps on a RHEL 7 box.

1. clone roslyn.
2. switch to version-1.3.0-beta1-20160429-01 branch
3. cd build/MSBuildToolset
4. Add `"rhel.7.2-x64": { },` to `runtimes`
5. /path/to/dotnet/dotnet restore
6. /path/to/dotnet/dotnet run

**Expected Behavior**:

Running MSBuildToolset works, or fails with an error message about using the MSBuildToolset program with incorrect arguments

**Actual Behavior**:

MSBuildToolset fails with `Failed to initialize CoreCLR, HRESULT: 0x80004005`

I know RHEL is not officially supported for building roslyn. But I would like to fix that. I am willing to contribute patches for RHEL specific bits. This particular problem, though, I am not sure about.

**Comment by jasonmalinowski** [comment]
@omajid: apologies, but this slipped through the cracks. If you're still running into issues let me know, as I'll help you route this to the correct owners.
