### ISSUE TITLE
IntelliSense crashes if you change filters to a type with no suggestions

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#11559]
**Version Used**: 
VS '15' Preview 2

**Steps to Reproduce**:
1. type something to bring up intellisense
2. filter by a type
3. change your filter to a different type that displays no items

**Expected Behavior**:
I see "No Suggestions Available" in the intellisense menu
**Actual Behavior**:
VS crashes

**Comment by Pilchie** [comment]
Actually, I'll take a look at this, since I have an debug environment already set up.
