### ISSUE TITLE
Roslyn should have an API reference website

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#11557]
I believe that API reference is an important part of library's documentation, and that there should be a website that contains at least the contents of XML documentation comments, ideally more. MSDN used to be the place for this for all MS products, but that doesn't seem to be the case anymore: [.Net Core has API reference section on its separate documentation site](http://dotnet.github.io/api/index.html) and [so does ASP.NET](https://docs.asp.net/projects/api/en/latest/) (even if it's out of date).

The closest thing I could find for Roslyn is [an ad-supported anonymous site](http://www.coderesx.com/roslyn/html/Welcome.htm).

**Comment by daveaglick** [comment]
The reference source site with browsable, cross-referenced source code is at http://source.roslyn.io

**Comment by svick** [comment]
@daveaglick That's not quite the same. I don't want to look at how Roslyn is implemented, I just want to know how to use it. Reference source kind of works for that, but with *a lot* of noise.

**Comment by BillWagner** [comment]
I recommend closing this as we are tracking the work on the docs side here: https://github.com/dotnet/docs/issues/2412
