### ISSUE TITLE
[Infrastructure] MSbuild reusing nodes even with `/nr:false`

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#11567]
MSbuild seems to reuse nodes even with `/nr:false` passed on the command line.

This causes build failures, such as:

```
error CS7032: Key file 'D:\j\workspace\windows_relea---d0ec00e7\build\Targets\..\Signing\35MSSharedLib1024.snk' is missing the private key needed for signing [D:\j\workspace\windows_relea---d0ec00e7\src\Runtime\Runtime\Runtime.csproj]
```

The code-base in question only calls MSBuild from one location (and always passes `/nr:false`) and all projects are referencing v2.0.0.0 of the Compiler toolset.

**Comment by jaredpar** [comment]
Not a Roslyn issue.

**Comment by tannergooding** [comment]
Closing this, as it looks like they have a separate bug tracking this: https://github.com/Microsoft/msbuild/issues/339

FYI. @rainersigwald
