### ISSUE TITLE
VB partial completion provider qualifies type names when there's a matching member name

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#11569]
**Version Used**: Version 14.0.25123.00 Update 2

**Steps to Reproduce**:

```
Class Foo(Of T)
    Sub Foo()
    End Sub
End Class

Partial Class $$Foo(Of T)
End Class
```

Trigger the completion list at $$.

**Expected Behavior**:
The type name in the completion list should not be qualified.

**Actual Behavior**:
The completion list item is qualified with either the containing namespace name or `Global`.

Found as part of #7213 and #4137, but it's not fixed by my current changes.

**Comment by CyrusNajmabadi** [comment]
Closing out as not having heard more customer feedback on this.
