### ISSUE TITLE
Invalid format string for string.Format method

### ISSUE THREAD

**Issue by SergeyTeplyakov** [dotnet/roslyn#11574]
It seems that format string provided to `stirng.Format` in this [place](https://github.com/dotnet/roslyn/blob/56f605c41915317ccdb925f66974ee52282609e7/src/EditorFeatures/Core/Shared/Utilities/VirtualTreePoint.cs#L128) is invalid:

```csharp
public override string ToString()
{
    return string.Format("VirtualTreePoint { Tree: '{0}', Text: '{1}', Position: '{2}', VirtualSpaces '{3}' }", Tree, Text, Position, VirtualSpaces);
}
```

This code will fail with format exception because open and close braces should be escaped.

P.S. I've found this bug using my [ErrorProne.Net](https://github.com/SergeyTeplyakov/ErrorProne.NET) analyzer.

**Comment by Pilchie** [comment]
Fixed by #11584.  Thanks for the report @SergeyTeplyakov, and the fix @AdamSpeight2008
