### ISSUE TITLE
RoslynDeployment suggestions

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#11586]
@jmarolf 

(1) In SolutionExplorer the project which generates RoslynDeployment.VSIX is just called "Roslyn". This is a confusing name, because the name "Roslyn" really refers to every aspect of Roslyn -- not just deployment. I think you should call this project "RoslynDeploymentVSIX" so we know exactly what it's for.

(2) When I set this project as startup and hit F5, it should launch an experimental hive of VS with the vsix installed. Currently it just pops up an error dialog "The debug target RoslynDeployment.dll is missing"

(3) When I install RoslynDeployment.VSIX into VS, then under Tools>Extensions it is listed under the title "Roslyn Insiders". I think you should unify+standardize the names. Give the VSIX the title "RoslynDeployment" as well.

**Comment by jmarolf** [comment]
@ljw1004 
1. We should change the name to something sensible.  I can get a pr out for this today. 
2. Is obviously something we should fix.  
3. This is something that a feel we need to discuss.  The hope is that very soon we will ship builds to customers using this VSIX.  Whatever language that we use should be consistent  RoslynDeploymentVSIX may be fine, but I fear it could be confusing as customers try to reason about what is installed in Visual Studio

**Comment by ljw1004** [comment]
3. Maybe a name like "Roslyn Plugin For VS" would be descriptive and suitable for both solution explorer and Tools&Extensions. The Tools&Extensions one could call it with the suffix "(experimental)" to be even more clear.

**Comment by AdamSpeight2008** [comment]
Could be related to #10239

**Comment by jmarolf** [comment]
Don't see how this is related to #10239, This has nothing to to with the Roslyn SDK templates, this is about building and deploying Roslyn itself.

**Comment by jasonmalinowski** [comment]
We've gotten rid of RoslynDeployment at this point.
