### ISSUE TITLE
Discussion: async/iterator local function captures

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#11585]
A common use case for local functions is to avoid state machine creation in async or iterator functions before parameter validation, etc. But if you capture any variable or parameter, the corresponding fields will be added to a `class` that we were intended to avoid creating in the first place. The only workaround is to pass every parameter to the local function which has to have a different name.

It would be nice to generate a separate `struct` for captured variables in async/iterator local functions, or permit a local function to shadow outer function's parameters.

Related: #11308

**Comment by gafter** [comment]
@ljw1004 You may be interested in this.

**Comment by svick** [comment]
A simple `struct` wouldn't work, because the local function might modify a captured variable, which is then read by the parent method. Though this is probably not the common use case, so I think some optimizations regarding the closure allocation would be worthwhile.

**Comment by alrz** [comment]
@svick Note that this only happens when your local function is async or iterator; otherwise a `struct` will be passed by ref. So this is probably due to the fact that async/iterator functions cannot accept refs as parameter. Anyhow, the use case you've mentioned is 1% of the times, really, I'd never capture locals in a local function and then mutate them, that'd be a messy code, indeed. Since local functions cannot have something like capture lists, this can be a source of bugs. I'd like to be able to use same parameter names as the outer function for the local one, though.

**Comment by alrz** [comment]
@gafter Can I reword this issue as a feature request to allow local function's parameters to shadow the outer method's parameter names, or is that a no-go?

```

**Comment by gafter** [comment]
@alrz I think repurposing this issue would be confusing. Please create a fresh feature request and include the motivating example(s).

**Comment by alrz** [comment]
@gafter Right on. It's filed over at #15793
