### ISSUE TITLE
[packaging] The nuspecs still use the old .NET Core TFMs

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#11597]
I was taking a look through the repo and notice that the old .NET Core TFMs (`dnxcore50` and `dotnet`) were still being used in the packaging: [example](https://github.com/dotnet/roslyn/blob/master/src/NuGet/Microsoft.Net.CSharp.Interactive.netcore.nuspec#L19) (if you're on a Linux system you can list all of them yourself by doing `cd src/NuGet && grep -Er 'dnxcore|dotnet'`).

Now that .NET Core RC2 has been released, should these be updated to use the `netstandard` moniker?

**Comment by jasonmalinowski** [comment]
We finally got this all fixed as a part of #11646 and other PRs.
