### ISSUE TITLE
Csc MSBuild task doesn't support auto detecting the host nor passing it in.

### ISSUE THREAD

**Issue by joperezr** [dotnet/roslyn#11598]
In corefx when building x-plat we use .Net Core MSBuild. The problem is that when msbuild calls the Csc task, the task will try to run it like: `corerun.exe csc.exe` which in windows is fine, but when you are running it x-plat it should change the host to be `corerun csc.exe`. Also, corerun is not the only host in which csc is able to run with, since you could also call it using the dotnet cli as a host, so if we wanted(which we do want right now) to not need corerun to be restored and use dotnet as the host it wouldn't work. Ideally, the csc task would invoke csc.exe using the same host that was used to invoke msbuild in the first place, and if this auto-detection is not possible, at least there should be a parameter that lets you override the host.

In corefx we currently have a 'hack' in place which will [rename the linux host to the windows one](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh#L90) so that we may use it, but given that we want to use dotnet now as a host we can't do this anymore and we are blocked by this.

I'm not 100% sure that this is a roslyn issue or if msbuild owns the task library where csc task is. In case they do, I'm adding @rainersigwald 

cc: @weshaggard

**Comment by jaredpar** [comment]
Roslyn owns this task and the general experience here.  

I think forcing the use of `corerun` here is wrong though.  It's baking in a runtime where one may not be desired.  For instance what if I want to use my own CoreCLR, Mono, etc ...  Instead it would seem to make sense that we always invoke `csc.exe`, or perhaps `csc` on xplat.  It would be the responsibility of the task host to ensure the files are setup to use the runtimes they desire.

**Comment by joperezr** [comment]
what about keeping it as is with corerun.exe for now, but making the parameter `ToolName` Overridable such that if we need to use a different host we can pass it in to the task?

**Comment by weshaggard** [comment]
I agree we shouldn't force corerun, we need a way to make it parameterized so people can setup their own host.

**Comment by agocke** [comment]
I'm with @jaredpar here: the task is responsible for calling `csc`. If a host needs to run then the `csc` target can be a shell script that calls the host first.

**Comment by jaredpar** [comment]
Closing as I don't feel this is Roslyn's responsibility to handle.  Our build task needs to be flexible enough such that MSBuild, CLI, or any other host can use corerun.exe, mono.exe, etc ... to drive the compiler.  That can be done via a combination of `ToolName` and scripts.

The decision on whether or not to use corerun.exe lies with the host and we should track the bug in the host repo.

**Comment by weshaggard** [comment]
@jaredpar is your expectation then that the msbuild targets should be the one setting the host? 

@rainersigwald is this something on the msbuild radar?

**Comment by jaredpar** [comment]
@weshaggard i think it's a layered solution:

1. CSC as a task must consider it's used under a number of host and be flexible to them. 
2. MSBuild core tasks must consider the same in it's tasks / targets.
3. MSBuild as a product and installer is defining a host and needs to override the host as dictated by 2.  
4. Mono / CLI / etc ... should also do the same as 3

**Comment by weshaggard** [comment]
@jaredpar that makes sense, I was just trying to ensure that we weren't expecting projects to somehow setup the host for these tasks.

**Comment by jaredpar** [comment]
@weshaggard agree it shouldn't be up to the projects by default.  They should always have the option of forcing a tool override but vast majority should just inherit the decision from the host.
