### ISSUE TITLE
Create VSI test for telemetry so that we can make sure it doesnt get broken by code change

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#11593]
our logging is done by static Logger type so making it unit test is not simple since there is no easy way to know which test called the Logger.

so unfortunately, the test need to be integration test. but regardless we should make sure we have a test to make sure telemetry doesn't get broken by code changes.

**Comment by heejaechang** [comment]
have PR, but can't check in until we move to dev15 dependencies.

**Comment by heejaechang** [comment]
vsi tests are still unreliable. holding onto PR. not product change though

**Comment by jasonmalinowski** [comment]
@heejaechang Can you share the PR?

**Comment by heejaechang** [comment]
you mean this ?
https://github.com/dotnet/roslyn-internal/pull/1432

**Comment by jasonmalinowski** [comment]
Ah yes, that. What's holding it up?

**Comment by heejaechang** [comment]
previously, VSI were all failing. I haven't tried for a while. so all might be okay now.
