### ISSUE TITLE
Transferring a document to Misc files loses all C# intellisense

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/roslyn#11599]
Dev14 U2

Are there known issues around this? Simplest repro
1.  New website, Select Empty C# website
2.  Add App_code folder
3.  Add a new class to App_Code
4.  File\SaveAs – save the new class outside the project cone. This causes a call to transfer the item to the misc files project

The open document has no colorization and the left navigation dropdown is empty where it should show Miscellaneous files. The transfer to miscellaneous files did succeed. 

I only noticed this trying to fix Save As for .Net Core projects which need to transfer the open document to Misc files if it is saved outside the project (basically, the same as websites).

**Comment by CyrusNajmabadi** [comment]
Need info how many people are hitting this to justify investment here
