### ISSUE TITLE
Default value of properties  

### ISSUE THREAD

**Issue by Mafii** [dotnet/roslyn#11609]
Steps to Reproduce: [TryRoslyn](http://tryroslyn.azurewebsites.net/#K4Zwlgdg5gBAygTxAFwKYFsDcAoADsAIwBswBjGUogQxBBgGEYBvbbGdmfYshgCgEo2HFh1EwAHjAC8MACw5RAX1aiuJcpGQTmMKKmSYYi6TACsObIqA)

When I have a default value for a property and I set the value directly in one of my constructors, the default value is redundant. 
Shouldn't the compiler optimize out the first assignment?

    public C(int y)
    {
        x = y;
    }

    public int x { get; } = 5;
 
   This is the generated code:

    public C(int y)
    {
        this.<x>k__BackingField = 5;
        base(); // This is not valid C#, but it represents the IL correctly.

        this.<x>k__BackingField = y;
    } 

Doesn't seem optimized for me. Is it because of possible side-effects?

My suggestion is that when the value is set already inside the constructor, the default value of the property is being ignored.

**Comment by HaloFour** [comment]
It is possible for a base class to cause access to the field prior to the constructor explicitly assigning it a value.  For example, a base constructor may invoke a `virtual` method which is overridden by a derived class which references that field:

```cs
public class Foo {
    public Foo() {
        this.DoSomething();
    }

    public virtual void DoSomething() { }
}

public class Bar : Foo {
    public int X { get; } = 5;

    public Bar(int x) {
        this.X = x;
    }

    public override void DoSomething() {
        Console.WriteLine($"X is {X}");
    }
}
```

This would end up printing "X is 5" on instantiation of `Bar` regardless of what the constructor argument is assigned.

Granted, I'm pretty sure that doing something like this is highly not-recommended.

**Comment by svick** [comment]
I think the CLR is what should make most optimizations. And in this case, it seems it doesn't. This code:

```c#
static void Main()
{
    var c = new C(42);
    Console.WriteLine(c.x);
}
```

Generates:

```asm
sub         rsp,28h                ; function prologue
mov         rcx,7FFCCC055A78h      ; prepare for allocation (?)
call        00007FFD2B7A4C40       ; allocate c
mov         dword ptr [rax+8],5    ; c.x = 5
mov         dword ptr [rax+8],2Ah  ; c.x = 42
mov         ecx,dword ptr [rax+8]  ; tmp = c.x
call        00007FFD121DF6B0       ; Console.WriteLine(tmp)
nop  
add         rsp,28h                ; function epilogue
ret  
```

**Comment by gafter** [comment]
The compiler is producing exactly the code you asked it to. The CLR is in the best position to produce the most efficient sequence of instructions for any given source.
