### ISSUE TITLE
If we decide to correct the *case* of an identifier in VB, that should not deprioritize the Add-Import result.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#11614]
In this case, this should *not* be considered a 'spell checking' match, and the Add-Import result should have normal priority.

@davkean May have also filed this.  But i'm filing it anyways just in case it wasn't.

**Comment by Pilchie** [comment]
Don't you have a PR out for this already?

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/11668
