### ISSUE TITLE
SyntaxTree design for out var

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#11613]
The syntax trees for `out var` have gone through a couple of revisions (e.g. see #11600 which changes from one design to another), but it isn't clear we've settled on the best final design. One different alternative, for example, would be to have a node to represent a *declaration expression* that is, at present, only parsed inside an `out` argument. We are meeting at 2pm on June 1 to resolve (or at least make progress on) a consensus syntax tree design.

/cc @dotnet/compiler-api @AlekseyTs

**Comment by AlekseyTs** [comment]
The SyntaxTree design has been finalized and #11765 aligns implementation with it.
