### ISSUE TITLE
[Bug]  VS 2015 can't remove first method of dll when use IL Support extesion.

### ISSUE THREAD

**Issue by RevensofT** [dotnet/roslyn#11637]
Microsoft Visual Studio Community 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038
Installed Version: Community
Visual Basic 2015   00322-20000-00000-AA234

**Extension in use:**
- IL Support extension 2.2

**Steps to Reproduce**:
1. Create a new project of class library with IL Support.
2. Compile and you will get an error about duplicate method.
3. Create any method before first method.
4. Finally compile without an error.

<img src="http://i.imgur.com/5EjKdHk.png"></img>
**Expected Behavior**:
From above picture, Anarchy.Common should not show any method because I set method implement to FowardRef.

**Actual Behavior**:
As you see in the picture, _Dummy method didn't get rid as it should be.

**Is it error from extension ?**
I don't think so; I check regex code in vbproj, it's still the same code as I use in VS 2013.

**Comment by gafter** [comment]
Can you please attach your project to this bug report?

**Comment by RevensofT** [comment]
Hi gafter,
This is project link for example of this bug.(I can't upload zip file on github so I upload to google drive instead).
https://drive.google.com/open?id=0B_LVzxeqJvq1cy1RMVBiYkxfYkU

**Comment by gafter** [comment]
I loaded your project and I don't see any errors, so there are no errors that disappear when the dummy method is added.

Please provide a repro and reopen.
