### ISSUE TITLE
Add integer bit manipulation functions

### ISSUE THREAD

**Issue by bizon-sb** [dotnet/roslyn#1163]
There is currently no way to access the powerful bit-manipulation functions that are present on modern processors from C#. I have found these to be very useful for encryption and high performance data structures. 
These include bit rotations, finding the highest bit set, counting the number of 1 bits etc. 
My suggestion is to include these as static methods to for Int32, Int64 and others in a similar way that has been done in java (look for Integer.numberOfLeadingZeros(..) in java for an example of what I mean). 
For the platforms with the hardware that supports it these could be replaced with a single machine code instruction. Where hardware support is not available it should be easy enough to provide an optimized default implementation.
Here is a (non exhaustive) list of functions that would be useful.
- Bitwise rotation left/right
- Counting the number of leading/trailing zero bits 
- Count the number of set bits

**Comment by mkosieradzki** [comment]
I am afraid you are writing to the wrong project - because this issue is far more related to the mscorlib than to the languages/compilers - especially if you are proposing introducing static methods - not new operators, constructs etc.

I would suggest this project: https://github.com/dotnet/coreclr .

**Comment by bizon-sb** [comment]
You are right, that seems to be a better place for it. I'll close the issue and post it there instead.
