### ISSUE TITLE
Use of type initializer for optional parameters wrongfully compiles

### ISSUE THREAD

**Issue by aevitas** [dotnet/roslyn#11638]
While going over some code, I've come across an interesting piece of code that is underlined in red in Visual Studio, but does actually compile. The code is close to the following:

        public static void Test(Vector3 vector = new Vector3() { X = 1f, Y = 1f, Z = 1f})
        { }
        
        public struct Vector3
        {
            public float X;

            public float Y;

            public float Z;
        }

As expected, when hovering the line, it reads:
 > Default parameter value for 'vector' must be compile-time constant

According to the spec: 

>  The expression in a default-argument must be one of the following:
* a constant-expression 
* **an expression of the form new S() where S is a value type**
* an expression of the form default(S) where S is a value type

The above code doesn't fit any of these three, yet it does compile. When printing `vector` - the output is `0,0,0`.

Is this intentional? Surely using the type initializer here should result in a compiler error?

**Comment by lorcanmooney** [comment]
Looks like there's a missing check at [src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs#L196](https://github.com/dotnet/roslyn/blob/4bc748b1b79b6dc1ed7e1d33bed1eb157a9ce6fe/src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs#L196). `InitializerExpressionOpt` should be `null`.

**Comment by AdamSpeight2008** [comment]
Confirm that this issue is also present in VB.
![vb_issue](https://cloud.githubusercontent.com/assets/900107/15639636/41df334a-2626-11e6-8d66-713d6060a10e.jpg)

**Comment by lorcanmooney** [comment]
@AdamSpeight2008 I've opened a PR to fix the C# issue, but I'm not too familiar with VB any more. I can't spot the issue in the screenshot. Should that code compile in VS2015?

**Comment by AdamSpeight2008** [comment]
@lorcanmooney 
The potential error has the red squiggly line underneath it.

**Comment by gafter** [comment]
#11678 is a community-offered fix for this.

**Comment by AdamSpeight2008** [comment]
@gafter  Only for C#

**Comment by cston** [comment]
@AdamSpeight2008 the VB compiler reports ```error BC30059: Constant expression is required.``` as expected.
