### ISSUE TITLE
Sample of how to attach ruleset/speciic diagnostic options to a project in MSBuildWorkSpace

### ISSUE THREAD

**Issue by dasaprakashk** [dotnet/roslyn#11630]
Using Microsoft.CodeAnalysis v1.2.0.0 - When compiling the project with MS All Rules ruleset  
using Project.GetCompilationAsync().Result, or adding the SpecificDiagnosticOptions with the same IEnumerable<string, ReportDiagnostic>, the code analysis results provides only one analysis. CS8019: Unnecessary using directive.

Providing sample code I tried below:
var workspace = MSBuildWorkspace.Create();
var solution = workspace.OpenSolutionAsync(this.SolutionPath).Result;
var project = solution.GetProject(projectId);
 if (this.CurrentProject.SupportsCompilation)
 {
 //Note: I generated the specific diagnostic options in this code and set it in the project and tried both seperately               
//There are 447 total rules
var newProject = project.WithCompilationOptions(CurrentProject.CompilationOptions.WithSpecificDiagnosticOptions(options));
var comp = CurrentProject.GetCompilationAsync().Result;
var diagnostics = comp.GetDiagnostics();
}
Also tried:
using (var stream = new MemoryStream())
{
var result = comp.Emit(stream);
var d = result.Diagnostics;
}
When I try code analysis in VS, I get a comprehensive set of code analysis errors for the same project.

**Comment by srivatsn** [comment]
> var comp = CurrentProject.GetCompilationAsync().Result;

You are creating a new project with has the new compilation options but then you are using CurrentProject which doesn't have the specificDiagnostic options to get the compilation. Remember that in Roslyn everything is immutable so changing the project simply gives you a new project with the options set. You should there do `newProject.GetCompilationAsync()`
