### ISSUE TITLE
Wiki should not claim dotnet CLI supports csi

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#11641]
The wiki page [*Scripting API Samples*](https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples#getting-started) says:

> If you do not have Visual Studio installed on your machine, you can access csi.exe with the dotnet CLI tool.

But, as of dotnet CLI RC2, this is not true. I think this sentence should be removed for now.

See also https://github.com/dotnet/cli/issues/1289#issuecomment-210123326.

**Comment by tmat** [comment]
Fixed the doc.
