### ISSUE TITLE
How to implement propper reaction to C# symbol rename.

### ISSUE THREAD

**Issue by Mylan719** [dotnet/roslyn#11643]
Hi, I am developing Visual Studio 2015 update 2 extension. 
I would like to ask how should I handle event when C# symbol is renamed, so that I can change my custom markup files accordingly. 
My use case is such, that I have custom markup file format, that combines C# syntax and html markup.
Usage is following:
**Markup containing C# symbols:**

``` html
@viewmodel MyViewModel
<div>
{{value: _this.Property}}
<div>
```

**Standard C# file.**

``` csharp
using System;
namespace MyNamespace
{
    public class  MyViewModel
    {
        public string Property { get; set; }
    }
}
```

When user renames the property `Property` in the C# file, I want to rename symbol in my custom markup file.
I have been advised to use the `Microsoft.VisualStudio.Shell.Interop,IVsRefactorNotify` interface,I tried, but nothing I've tried with it worked. I have no idea how to implement/export or where to register it, so that it gets called when renamed in C# file happens. Isn't that just for C# files in the old project system?
Another thing I tried  was to implement `Microsoft.CodeAnalysis.Editor.IRefactorNotifyService`, that worked well for my needs, but since it is internal I had to use nonstandard measures that I don't want to use on prodduction enviroment.
Do you  know anbout anything else I could try? I am beginning to run out of options here. :/

**Comment by jmarolf** [comment]
@dpoeschl

**Comment by Mylan719** [comment]
Is there any hope this will be solved? It would not take much. For example you could move `IRefactorNotifyService` to namespace `Microsoft.CodeAnalysis` which is available as nuget and make it public. Problem solved I would be so happy. Is there some kind of deep reson why this can't be done? :) I mean judging by the comment it is meant as user extension point anyway. ;)

**Comment by Pilchie** [comment]
@dpoeschl is out right now, and will be back in a couple of weeks.  In the meantime, @jasonmalinowski might have thoughts.

**Comment by Pilchie** [comment]
On the Roslyn team, we've never been on the implementing side of `IVsRefactorNotify`, but I believe you need to follow the steps [here](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivshierarchyrefactornotify.aspx) and actually implement `IVsHierarchyRefactorNotify`.

Changing this to a feature request for making `IRefactorNotifyService` a publicly supported entry point instead.

**Comment by Pilchie** [comment]
Unfortunately however, we do have a backlog of other public APIs that we're interested in introducing and I'm not sure when we'll get to this one.

Tagging @mattwar @DustinCampbell @CyrusNajmabadi who have been most involved in creating those public APIs.

**Comment by Mylan719** [comment]
I have read the piece of documentation you pointed me to. Main body of the article is chain of events during reaction to refactoring event. But the it mentions I also need to implement `IVsHierarchy` and `IVsProject` along with `IVsHierarchyRefactorNotify` for it to work. So I looked on documentation on those interfaces to.
Now, It seems to me that intended use case for this interface is: When somebody wants to implement his own project system for his custom language for example. His implementation of project system should also implement those 3 interfaces in order to ba able to receive refactor events that occur in other projects. 
I may be misstaken because the documentation is really brief, but If I understand currectly how it works (which I described above) this is not what I want to archieve. I have my markup files located in standard C# web project. C# project already has it's implementation (probably in C++ exposed through DTE) that uses `IVsHierarchyRefactorNotify` I cannot touch that implementation to add functionality for my markup files. So what I would have to somehow create  my virtual project system (let's call it `VPS`) (of which I haven't found any example) Then cherry-pick my custom markup files from C# project add it to `VPS` and manage `VPS` whenever source C# project changes. Then my implementation of `VPS` would implement  `IVsHierarchyRefactorNotify` just to be able to react to simple refactoring event.
Then In the On... method I would have to get ISymbols from Roslyn project system based on On... method parameters and current file. So I would have to have some kind of map between `VPS`, `DTE` project system and Roslyn project system.
And with all this work I would basicly have equivalent of roslyn `IRefactorNotifyService` :)
Is this so? 
Also this is my reasoning why I believe `IRefactorNotifyService` is very usefull.

**Comment by Pilchie** [comment]
Sorry for ignoring this issue for so long.  I agree it would be useful, it's just not at the top of our priority list for things to make public.  @mattwar is currently driving most of our public API work, so assigning to him.

**Comment by PathogenDavid** [comment]
@Mylan719 I know this was quite some time ago, but did you ever find a workaround for this issue? I'm trying to do something similar.

**Comment by jmarolf** [comment]
`IVsRefactorNotify` is the only solution I am aware of.  You need to be a VS extension for that, but roslyn should call types that implement this interface whenever a symbol is renamed (assuming these type MEF export themselved correctly).

**Comment by PathogenDavid** [comment]
Yeah, I figured an extension was going to be involved here. It sounds like @Mylan719 didn't find success with that API. I was about to make an extension to test it anyway, but I came across this bug https://github.com/dotnet/roslyn/issues/25784. From the sound of that, it seems like that interface don't work with SDK-style projects.

**Comment by CyrusNajmabadi** [comment]
We only support IVsRefactorNotify for now.  requests for anythign else would have to go through our API proposal process.

**Comment by krisrok** [comment]
@CyrusNajmabadi could you elaborate on how to use the `IVsRefactorNotify`? Do we have to register the implementor somewhere? Does it only work for packages? Do we have to jump through all the hoops like @Mylan719 [mentioned above](https://github.com/dotnet/roslyn/issues/11643#issuecomment-229163188)? All I was able to find about _actual usage_ of the interface is in the [remarks of the documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivshierarchyrefactornotify?redirectedfrom=MSDN&view=visualstudiosdk-2022#remarks) of `IVsHierarchyRefactoryNotify`.
