### ISSUE TITLE
Compiler crash on base call in an iterator

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#11649]
Source:

```C#
using System.Collections.Generic;

class Base {
    protected virtual IEnumerable<int> M() {
        yield break;
    }

    class D : Base {
        protected override IEnumerable<int> M() {
            base.M();
            yield break;
        }
    }
}
```

This crashes the compiler in the Dev15 preview and the futures branch, but works fine on Dev14 / master.

http://tryroslyn.azurewebsites.net/#b:future/f:r/K4Zwlgdg5gBAygTxAFwKYFsB0BhA9gG31QGNkxcIRMBxVCVAJzGIG4AoN4/AQxBBgBCvVDADebGJJgAHBrjSlUAExgA3MA2TBu+GAEkAohGDpG3AEZEAPJGQA+GAFkAFAEoxEqV4RhU+FeYMqNwA1uxeAL4cXly8/AAiMABcgsIeXl6y8iRoKriqjExKIobGpgwW1rYOLu7iGQ0w5sKYteGN3r7+TUGh7Q1RkWxRbEA=

**Comment by SLaks** [comment]
Interestingly, it only crashes if both the base & derived methods are implemented as iterators (!)

**Comment by TheOpenDevProject** [comment]
@SLaks Mind showing an example that does not cause a crash?

**Comment by SLaks** [comment]
Just change either `yield break` to a normal `return` statement.
eg, http://tryroslyn.azurewebsites.net/#b:future/f:r/K4Zwlgdg5gBAygTxAFwKYFsB0BhA9gG31QGNkxcIRMBxVCVAJzGIG4AoN4/AQxBBgBCvVDADebGJJgAHBrjSlUAExgA3MA2TBu+GAEkAohGDpG3AEZEAPJGQA+GAFkAFAEoxEqV4RhU+FeYMqNwA1uxeAL5sUVy8/AAiMABcgsIeXrLyJGgquKqMTEoihsamDBbWtg4u7uJeXkFaDBAw5sKYNeFSUVFAA===

**Comment by SLaks** [comment]
The crash appears (in the debugger) to happen when generating a debug name & syntax offset for the StateMachineCachedState synthesized local for the derived method.

**Comment by tmat** [comment]
I remember filing an issue on this a while ago.

**Comment by jaredpar** [comment]
Thanks for reporting.  Will take a look at this.

**Comment by kellyelton** [comment]
Oh man this sucks.

**Comment by SLaks** [comment]
Unlike most of my bug reports, this is actually blocking compilation for one of my primary projects.
Is there any ETA for a fix?

**Comment by SLaks** [comment]
Unlike most of my bug reports, this is actually blocking compilation for one of my primary projects.
Is there any ETA for a fix?

**Comment by jaredpar** [comment]
The ETA is likely RC on this fix (preview 4 just went into Ask Mode and we're locked down on a number of high pri issues this week).  Will see if @TyOverby can get in a fix here though.

**Comment by jcouv** [comment]
Merged the fix into the dev15-preview-4 branch.

**Comment by bvkrishnna** [comment]
I migrate my vs2008 project to vs2015 getting an error.
 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.Core.targets(67,5): error MSB6006: "csc.exe" exited with code -1073741571. how to resolve this issue plz help me.

**Comment by jcouv** [comment]
@bvkrishnna Please [file a separate issue](https://github.com/dotnet/roslyn/issues/new). I don't think the issue you describe is related to OP.
When you do, I would recommend that you capture a dump of the crashing csc process (see [instructions](https://github.com/dotnet/roslyn/wiki/Troubleshooting-tips)), assuming that is compatible with your project's policies. We'll give you further instructions for transferring the dump file. From the dump file, we should be able to narrow down the problem.
Depending on the size of your project, you can also try to narrow down which file or code is causing the crash.
