### ISSUE TITLE
False errors with Roslyn

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn#11655]
I’m getting false errors from Roslyn with the attached solution. Open Rx-New.sln and build. It will compile correctly. Then go to the test project and open Tests.System.Reactive\Tests\Linq\ObservableAggregateTest.cs

![img](https://cloud.githubusercontent.com/assets/1427284/15684073/5a95bb80-2733-11e6-9445-76dfab51e3df.jpg)
[Source.zip](https://github.com/dotnet/roslyn/files/291758/Source.zip)

Severity    Code    Description Project File    Line    Suppression State
Error   CS0103  The name 'ThreadPoolScheduler' does not exist in the current context    Tests.System.Reactive..NETCoreApp,Version=v1.0  C:\dev\git\reactive-extensions-private\Rx.NET\Source\Tests.System.Reactive\Tests\Linq\ObservableAggregateTest.cs    2374    Active

The crux may be that it’s a netcoreapp1.0 project that’s referencing a project (System.Reactive.PlatformServices) that itself has netstandard 1.3 and netcoreapp1.0 outputs (among others). That type is only available in the netcoreapp1.0 output due to the dependency on Thread/ThreadPool.

**Comment by davkean** [comment]
@gafter This is likely a design-time build issue, moved it to IDE.

**Comment by Pilchie** [comment]
@jasonmalinowski Can you take a look and see what's up here?

**Comment by Pilchie** [comment]
Closing, as this would have been xproj based projects.
