### ISSUE TITLE
Visual Studio should support EnC from run mode

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/roslyn#11656]
Currently, Edit and Continue is only supported while the target process is stopped for C#/VB. If a user tries to edit they get this:

![changes-are-not-allowed-while-code-is-running](https://cloud.githubusercontent.com/assets/11078489/15684496/37ba2e00-271c-11e6-80ae-db7fcbd0337f.jpg)

There doesn't seem to be any good reason to have this restriction any longer, so at some point we should consider allowing these edits.

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/36727
