### ISSUE TITLE
CodeLens throws NullReferenceException

### ISSUE THREAD

**Issue by dekenless** [dotnet/roslyn#11653]
VS2015 Update 2

1. Open solution
2. navigate to method in code where there are references
3. Pop-up is displayed with "An exception has been encountered. This may be caused by an extension."

From the activitylog.xml:

System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.AppInsights.GettingStarted.CodeLens.ExceptionsDataPointProvider.CanCreateDataPoint(ICodeLensDescriptor descriptor)
at Microsoft.VisualStudio.Language.Intellisense.Implementation.CodeLensIndicatorService.IndicatorCollection.&lt;&gt;c__DisplayClass13_0.&lt;UpdateTemplateCollection&gt;b__0();   
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

If I disable Code Lens completely the exception does not occur.  The references do eventually populate correctly.

**Comment by Pilchie** [comment]
@olegtk This looks like the core editor indicator, right?

**Comment by olegtk** [comment]
No, it's not a core indicator. This seems to be AppInsights extension, at least according to http://stackoverflow.com/questions/25854264/visual-studio-2013-update-3-problems
Try uninstalling "Developer Analytics Tools" extension.

**Comment by dekenless** [comment]
Correct, uninstalling "Developer Analytics Tools" seemingly resolves the issue.

**Comment by danroot** [comment]
FYI, in my VS 2015 Update 2, this extension failing cause the "TEST" menu to no longer appear.  Disabling the extension caused it to reappear.  I see this more as a VS flaw (a failed add-in shouldn't kill core menu items IMO), but leaving this here in case it helps others or the VS team sees it ;)

**Comment by olegtk** [comment]
I filed internal bug to track this.

**Comment by gardnerjr** [comment]
@danroot what version of the developer analytics tools was this?  i'm not sure how we'd prevent the test menu from appearing, as we don't put anything in that menu.  

if you leave our extension enabled but just disable the "Exceptions (Application Insights)" codelens indicator from the codelens options, is your test menu still gone?  i've never seen that happen before.

**Comment by gardnerjr** [comment]
FYI: The release of VS2015 update 3 today includes a fix in the Developer Analytics Tools for the original NullReferenceException reported by @dekenless .  We still haven't seen or repro'd that being the cause of a missing test menu, though.

**Comment by danroot** [comment]
Will try U3.  Since the original report, I saw the same behavior with other extensions.  When an error occurred loading an extension, the Test menu didn't appear, even though the extensions to not directly work against that menu.  I'm guessing the VS IoC is failing to  finish loading properly after an exception loading extensions?  Don't leave this ticket open on my account though.

**Comment by Pilchie** [comment]
Thanks @gardnerjr!
