### ISSUE TITLE
Completion: Locals and parameters filter doesn't show locals

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#11667]
**Steps to Reproduce**:
```C#
class Program
{
    static void Main(string[] args)
    {
        int local = 0;
        a$$
    }
}
```

**Expected Behavior**:
`args` and `local` both show

**Actual Behavior**:
Only `args` shows

**Note**
In [CompletionItemFilter.LocalAndParameterFilter](http://source.roslyn.io/Microsoft.CodeAnalysis.Features/R/88e7332ec5ab0421.html) we only add the tag for parameter.  Also in [CompletionItemFilter.Matches](http://source.roslyn.io/Microsoft.CodeAnalysis.Features/R/43f44cc0c0f6e0c0.html) we say the item must match `All` tags.  Should that be `Any` instead?

**Comment by Pilchie** [comment]
Tag @CyrusNajmabadi @mattwar

**Comment by mattwar** [comment]
@Pilchie on All vs Any, probably. There is only one case that would currently have more than one tag in the filter set, the one you pointed out that was wrong. So we can choose for the behavior to be either way.

**Comment by Pilchie** [comment]
This was fixed by @CyrusNajmabadi in https://github.com/dotnet/roslyn/pull/11723
