### ISSUE TITLE
Add VB language version 15 flag

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#11666]

**Comment by AdamSpeight2008** [comment]
Are the available language features the same as VB14? or is there some new ones?

**Comment by TyOverby** [comment]
I've been told that tuples, consuming ref returns, and possibly await in catch / finally will be part of vb 15.

**Comment by AdamSpeight2008** [comment]
@TyOverby I was referring to these [Features](https://github.com/dotnet/roslyn/blob/dcfb3f9c83a77dad7a8a721d7b8413e0dd243d34/src/Compilers/VisualBasic/Portable/Parser/ParserFeature.vb#L52) which are set under a language version.

**Comment by TyOverby** [comment]
Closed by #11670
