### ISSUE TITLE
Reenable CA1825 for Roslyn after Roslyn picks up new analyzers

### ISSUE THREAD

**Issue by JohnHamby** [dotnet/roslyn#11665]
The analyzer for CA1825 depends on a property of IArgument that is being removed. The checkin that removes the property will need to disable the analyzer for the Roslyn solution.

After Roslyn picks up a new version of the analyzer, CA1825 can be reenabled.

**Comment by mavasani** [comment]
Seems like CA1825 is still [enabled](https://github.com/dotnet/roslyn/blob/master/build/Rulesets/Roslyn_BuildRules.ruleset#L92) for Roslyn. Presumably, the IArgument change that John was working on didn't get in. @JohnHamby I am closing this for now, kindly reopen once the rule has been disabled.
