### ISSUE TITLE
Microsoft.CodeAnalysis.BuildTask.Portable package should have the target files under contentFiles, not content

### ISSUE THREAD

**Issue by joperezr** [dotnet/roslyn#11674]
In [the nuspec file for this package](https://github.com/dotnet/roslyn/blob/master/src/NuGet/Microsoft.CodeAnalysis.BuildTask.Portable.nuspec#L38-L39) the target files are being dropped into the "content" folder in the nuget package, which doesn't follow the new nuget package conventions, and causes tools like the dotnet cli to not copy those files to the output when an app is published. Instead, this target files should be dropped to the package using [the contentfiles](http://blog.nuget.org/20160126/nuget-contentFiles-demystified.html) which is supported by the CLI.

If the issue is approved, I'm happy to make the required changes to have this working.

**Comment by tmat** [comment]
I am about to delete the package. The nuspec has more incorrect values than correct.

**Comment by tmat** [comment]
Do you need the package?

**Comment by joperezr** [comment]
Yes we do, as of now [we were still using in corefx](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json#L13) an old private built version of this package that was uploaded into buildtools some time ago. Back then I believe that Microsoft.CodeAnalysis.BuildTask.Portable package didn't even existed. There are a bunch of fixes that have been added to Microsoft.Build.Tasks.CodeAnalysis and we want to get all those, so we want to start depending on this package, but the only blocker is that the target files won't be copied unless we move them to contentFiles

**Comment by agocke** [comment]
I have other issues in the task assigned to me (like the one you filed here https://github.com/dotnet/roslyn/issues/11598 :)) so I'll take this one while i'm in the code

**Comment by tmat** [comment]
I was thinking I'd just dix the nuspec up for U3

**Comment by agocke** [comment]
@tmat If the other changes are also needed, and produce code changes to the Desktop task, it'll need to be done for 2.0 anyway.

**Comment by tmat** [comment]
OK, deleting for now.

**Comment by agocke** [comment]
Should be fixed by #13592
