### ISSUE TITLE
ObsoleteAttribute prevents correct override checks

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#11691]
Consider the following code:

``` csharp
public abstract class BaseClass<T>
{
    public abstract int Method(T input);
}

public class DerivingClass<T> : BaseClass<T>
{
    [Obsolete("Deprecated")]
    public override void Method(T input) 
    {
        throw new NotImplementedException();
    }
}
```

This code should fail to compile because `Method` is not a valid override of the base type due to the mismatch return types.  The presence of the `Obsolete` attribute though seems to allow this causing the compiler to only issue a warning here, not an error.

The compiler will eventually issue the following error:

> An error occurred while writing the output file.

**Comment by benaadams** [comment]
Shouldn't it only fail in the case where `isError == true`?
```csharp
public class DerivingClass<T> : BaseClass<T>
{
    [Obsolete("Deprecated", true)]
    public override void Method(T input) 
    {
        throw new NotImplementedException();
    }
}
```
And the compiler error is wrong?

**Comment by benaadams** [comment]
Ahhh... mismatched return types!
