### ISSUE TITLE
Add tests for completion filtering

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#11700]
See https://github.com/dotnet/roslyn/pull/11669 - We don't have any tests for the completion filtering stuff yet.

**Comment by CyrusNajmabadi** [comment]
@rchande I think you're doing htis already?

**Comment by CyrusNajmabadi** [comment]
Closing out.  we can drive test coverage based on issues that arise.  Unlikely for any work to proactively do this and close this out.
