### ISSUE TITLE
Inline Temporary Variable creates unnecessary broken cast with generics & booleans

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#11712]
**Version Used**: Dev14 Update 2

``` C#
bool M<T>(ref T x) {
    var b = M(ref x);
    return b || b;
}
```

The Inline Temporary Variable refactoring (on `b`) gives

``` C#
bool M<T>(ref T x) {
    return M(ref x) || M(ref (T)x);
}
```

**Comment by Shiney** [comment]
This seems to also happen if the code is not generic e.g.

```CSharp
    bool S(ref int x)
    {
        var b = S(ref x);
        return b || b;
    }
```

Has the same issue. Also the self reference is not necessary (but makes the sample code shorter).

What is the correct behavior in this case anyway? It won't really be a refactoring if the method with the ref parameter being called does something like increment the ref parameter.

**Comment by jasonwilliams200OK** [comment]
> What is the correct behavior in this case anyway?

`return M(ref x) || M(ref x);`?
or optimally for both `b || b` and `b && b`, it could just be `return M(ref x);`..
