### ISSUE TITLE
Implement OSS signing in the compiler when public key is specified in .snk file

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#1171]
The compiler currently OSS signs the compilation assembly when CryptoPublicKey is set to a valid public key and DelaySign is false  (i.e. sets the "signed" CorFlag bit to true without actually signing the assembly). 

We should enable OSS signing also when a public key is supplied via .snk file. Currently we report ERR_SignButNoPrivateKey error if the file doesn't contain both public and private keys. The proposal is to remove this error and OSS sign the assembly instead.

The benefit would be that without adding any command line compiler options, project system settings etc. we could add the feature of OSS signing into the compiler and get rid of FakeSign tool.

**Comment by gafter** [comment]
clearing milestone for triage

**Comment by amcasey** [comment]
It's probably worth mentioning that Concord.csproj invokes FakeSign directly on assemblies produced by ilasm.

**Comment by theoy** [comment]
Moving out of 1.0 - let's take more time to review this before adding it to the supported behavior.

**Comment by tmat** [comment]
See https://github.com/aspnet/dnx/blob/pawelka/snk/src/Microsoft.Dnx.Compilation.CSharp.Common/SnkUtils.cs for SNK file reader.

**Comment by tmat** [comment]
DNX needs this feature. 
//cc @davidfowl

**Comment by davidfowl** [comment]
https://github.com/aspnet/dnx/blob/pawelka/snk/src/Microsoft.Dnx.Compilation.CSharp.Common/SnkUtils.cs

/cc @moozzyk

**Comment by moozzyk** [comment]
Fixing link https://github.com/aspnet/dnx/blob/72b0f325959a06d7b9d92aa438df0dc889a73ec3/src/Microsoft.Dnx.Compilation.CSharp.Common/SnkUtils.cs

**Comment by davkean** [comment]
Dropping the infrastructure, this is a compiler feature.

**Comment by jaredpar** [comment]
Public signing is now a supported compiler feature.
