### ISSUE TITLE
Unexpected behavior of IOperation

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#11737]
IOperation routinely returns IInvalidExpression instance on expressions that are valid.  For example, in the following code:

``` vb
Option Strict On
Imports System.Runtime.CompilerServices

Namespace NS1
    Class C
        Sub Bar()
            Test(5)  ' Test(5) is invalid because there is no appropriate Import to bring it in.
        End Sub
    End Class
End Namespace
Namespace NS2
    Module A
        <Extension()>
        Sub Test(ByVal ec As NS1.C, ByVal n As Integer)
        End Sub
    End Module
End Namespace
```

This was unexpected to us when using the API.  While i could understand that 'Test' could not be resolved, we still expected to get an IInvocationExpression with appropriate ArgumentsInSourceOrder.  It was also expected that .TargetMethod could be null here as we could not find a suitable method.

The primary problem is that once you get an IInvalidExpression back, there's effectively nothing you can glean from it.  This means that it's harder to write features that operate on VB/C# agnostically in the presence of errors.  Instead, specific code has to be written again for each language again.

Ideally, in the presence of errors, the information reported back would still be as accurate as possible, without falling back to InvalidExpression/InvalidStatement and the like.
## 

Another example is:   "foo *= x".  If 'x' fails to bind, then we have an ICompoundAssignmentExpression (yaay,) that has a BinaryExpressionKind of Invalid (boo).  That means we have no way to tell at the IOperation level that this was even an attempt to Multiply.

Note: it's understandable that other information would be missing.  For example, it makes sense that we can't tell if this is int-multiple versus a long-multiply.  Similarly, we can't know if there was some operator that was invoked here.  However, we can still tell that this was a multiply, but that information gets lost due to the error below.

**Comment by CyrusNajmabadi** [comment]
Note: these were found by an IDE effort to move off of language specific code and instead work on the language neutral layers only.  In the absence of errors, this seems to work out ok. However, in the presence of errors, it falls over quickly.  As most IDE features need to work with errors (or exist to fix errors in the first place!) this proves problematic.

My hope is that this is not out of scope for operatoins.  IDE would really like to be able to use these to remove lots of special casing for VB/C# it has today.  It will simplify our implementations and also help vet the IOperation API more.

**Comment by AdamSpeight2008** [comment]
@CyrusNajmabadi 
Isn't it invalid because it is expecting two arguments and you're only supplying one?

**Comment by tmat** [comment]
@genlu Is this the same or similar issue as the one you're looking into?

**Comment by mavasani** [comment]
This work is now tracked with https://github.com/dotnet/roslyn/issues/18722 - adding IInvalidInvocationOperation in v2 of IOperation feature work.
