### ISSUE TITLE
IDE gives an error for 'Allow unsafe code' is not supported by one or more of the project's targets.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#11749]
PCL projects where all of the targets support unsafe code gives an error when AllowUnsafeBlocks is manually set to true. The error message is: 'Allow unsafe code' is not supported by one or more of the project's targets.

Repro:
1. Create a PCL project targeting netstandard 1.3 (Desktop and CoreCLR)
2. Manually edit the project and add <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
3. Reload the project in VS
4. Examine the Error List

**Comment by tannergooding** [comment]
This is reproducing in D14Rel 25401.00

**Comment by tannergooding** [comment]
FYI. @dotnet/roslyn-ide

**Comment by rchande** [comment]
You fixed this by adding a reference to the compat pack.

**Comment by rchande** [comment]
You fixed this by adding a reference to the compat pack.

**Comment by tannergooding** [comment]
@rchande, shouldn't this stay open so a fix where you don't have to add the compat pack goes in?

The default behavior when targeting `netstandard` is to only reference `NetStandard.Library` --or-- when upgrading from `dotnet5.x` to `netstandard1.x` (such as via the IDE) the references to `Microsoft.NETCore` and `Microsoft.NETCore.Portable.Compatibiltiy` are removed and replaced with `NetStandard.Library`.

**Comment by gcadmes** [comment]
This is closed? What am I missing? I'm using netstandard1.4, and still seeing the aforementioned error.

In my project.json, I have:
"buildOptions": {
    "allowUnsafe": true
  }
as well as having the checkbox on the projects\build tab checked.
