### ISSUE TITLE
SemanticModel.GetOperation should work when passed an ArgumentSyntax.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#11748]
This should work, and an IArgument should be returned.

**Comment by tmat** [comment]
@333fred Do you know if Cyrus fixed this?

**Comment by 333fred** [comment]
It's not merged, https://github.com/dotnet/roslyn/pull/21263.

**Comment by tmat** [comment]
@333fred Anything left to do there other than compiler team reviews?
