### ISSUE TITLE
PCL doesn't allow you to set 'Allow unsafe code'

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#11747]
PCL projects where all of the targets support unsafe code, does not allow you to set 'Allow unsafe code' in the IDE.

Repro:
1. Create a PCL project targeting netstandard 1.3 (Desktop and CoreCLR)
2. Right click the project and select 'Properties'
3. Go to 'Build'
4. Examine that 'Allow unsafe code' cannot be set

**Comment by tannergooding** [comment]
This is reproducing in D14Rel 25401.00

**Comment by tannergooding** [comment]
FYI. @dotnet/roslyn-ide

**Comment by rchande** [comment]
You fixed this by adding a reference to the compat pack.
