### ISSUE TITLE
Offer to convert method calls with string and objects to interpolated strings

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#11759]
Before:

``` C#
var name = "Your Name";
Console.WriteLine("Hello {0}", name);
```

After:

``` C#
var name = "Your Name";
Console.WriteLine($"Hello {name}");
```

**Comment by MillKaDe** [comment]
That is already available as a 3rd party extension for Visual Studio.

- [C# Essentials](https://github.com/DustinCampbell/CSharpEssentials) offers conversion from `string.Format (...)` to interpolated string.

- [Refactoring Essentials for Visual Studio](https://github.com/icsharpcode/RefactoringEssentials) offers conversion from `string.Format (...)` to interpolated string and from interpolated string back to `string.Format (...)`.

**Comment by Pilchie** [comment]
@jmarolf actually just moved the support from C# Essentials directly into Roslyn, but this is slightly different.

This is about recognizing other method signatures that take `(string formatString, params object[] args)` and call `string.Format` internally (like `Console.WriteLine` in the sample) and extending the support to them.

**Comment by CyrusNajmabadi** [comment]
This works today:

![image](https://user-images.githubusercontent.com/4564579/152590352-7dfc9d6c-c07f-4adb-b905-05b01ecd9042.png)
