### ISSUE TITLE
Introduce FormattingOptions.UseTabOnlyForIndentation with testcases

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#1176]
With the changes in PR #1166 we have removed the option `FormattingOptions.UseTabOnlyForIndentation`. 

Since we didn't have testcases backing the behavior of the option we have removed this option.

From discussion with the team, there seems to be 2 purposes:
1. In the case of,

```
<tab><tab>void MMM(int i,
<tab><tab><spaces> int j)
```

the second line is tabbed in the Indentation area and the rest of the string is filled with spaces with the help of this option
1. In the case of (Keeping Tab),

```
<Tab><Tab> var s = 0;<Many tabs> // Single or MultilineComment
```

On format, the `<Many tabs>` will be expected to  be converted to spaces because Tabs are only for indentation.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal. As it is related to formatting, it's likely something that woudl have to be considered as part of the new formatting engine effort.  Tagging @jmarolf  for visibility.
