### ISSUE TITLE
CSharpErrorLog_v1_Engine test is flaky

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#11766]
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_prtest/60/

**Comment by srivatsn** [comment]
@mavasani havent we removed the v1 test?

**Comment by mavasani** [comment]
Not yet, I will do so on Monday and also delete v1 engine product code.

**Comment by jinujoseph** [comment]
i am still seeing this http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/future-stabilization/job/windows_vsi_p2_prtest/21/

**Comment by mavasani** [comment]
That failure is on stabilization- we should just ignore it. If it fails too often, we can then port the closed side change that removed this test in master.

**Comment by mavasani** [comment]
Closing this again - we would need to port https://github.com/shyamnamboodiripad/roslyn-internal/commit/09368821809f56fa5e7649f0643c228050fde8e0 to stabilization if this test fails too often.
