### ISSUE TITLE
ArgumentException if generated SyntaxTree is not parsed WithFeatures("replace", "true")

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#11763]
To enable the generators feature requires compiling with `csc -features:replace`. However if a generator adds source using `SourceGeneratorContext.AddCompilationUnit(name, tree)` without parsing the tree with the same option (without `WithFeatures(new[] { new KeyValuePair<string, string>("replace", "true") })`), the compiler throws `System.ArgumentException: inconsistent syntax tree features`.

**Comment by gafter** [comment]
Generators should always use the underlying compilation's parse options.

**Comment by jaredpar** [comment]
Closing based on discussion.
