### ISSUE TITLE
VS crashed with OOM on relatively small project (< 20)

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11762]
This is a recent build of VS "15"

See dump: \\davkean-i7\shared\OOMProjectSystem\Devenv.dmp

Was editing a file, VS "froze" for > 20 minutes and then OOM'd.

**Comment by davkean** [comment]
tag @dotnet/roslyn-analysis

**Comment by heejaechang** [comment]
I couldn't find the dump

**Comment by heejaechang** [comment]
no dump. and old issue before all the OOM works. re-open if OOM happen again.
