### ISSUE TITLE
[Proposal] C# generic constraint (where TSelf : this) to facilitate typing members with TSelf / THISTYPE and the CRT pattern

### ISSUE THREAD

**Issue by TheOtherSamP** [dotnet/roslyn#11773]
The `where TSelf : this` generic constraint would be applicable to abstract classes and interfaces only. Type parameters with the `this` constraint would be constrained to being either the implementing/deriving type itself, or a further `where TSelf : this` constrained type parameter on the implementing/deriving type. When used outside of derivation (e.g. to type a variable) further derived children would also be allowed.
## What does this achieve?

Safe use of the (sort of) Curiously Recurring Template Pattern. Eric Lippert gives a pretty good [overview and critique of this pattern on his blog](https://blogs.msdn.microsoft.com/ericlippert/2011/02/03/curiouser-and-curiouser/). I believe this proposal addresses and solves every problem Lippert raises, with the possible exception that it may be technically challenging to implement / require a CLR change.

One of the main problems with the current use of the CRTP without the `this` constraint is that it's not safe, a consumer can fail to supply itself as the generic parameter. As such, this pattern while sometimes okay to use internally, is rarely reasonable to expose across an API interface. This constraint would fix that.

Another common issue is that the code is confusing. With this constraint in place the compiler and IntelliSense would enforce correct behaviour and remove ambiguity, mostly fixing this.

Having access to `TSelf` to constrain generic method parameters is a scenario I've wished for a few times - this can sometimes be hacked a bit with extension methods, but obvious limitations (accessibility, discoverability, etc) exist there. Public properties of `TSelf` and other general uses would also exist. Other advanced scenarios, such as constraining another type parameter to implement `IComparable<TSelf>`, would also have uses.

**Edited in note**: A side-effect of this would be that an interface could restrict the types to which it can be applied. `where TSelf : class, this, Foo` would mean an interface can only be applied to class Foo and its children, and `where TSelf : this, IBar` would mean the interface could only be applied to types that also implement IBar. While not exactly the primary intention behind this feature, I actually think this could be a nice thing to have when building strong APIs with specific consumption of interfaces in mind. 
## What would this look like?

Here I have stolen and extended the example used by Eric Lippert in his blog post do demonstrate how this suggestion would operate. Overriding included for the sake of demonstration only, not required by the feature.

```
// A class with a this constrained parameter must be abstract.
abstract class Animal<TSelf>
    where TSelf : this
{
    protected Animal(){
        // this is always TSelf or a child of TSelf.
        TSelf self = this;
    }

    // In Lippert' highly conservative scenario, animals may only make friends with their own kind.
    public virtual void MakeFriends(TSelf animal);
}

// A derived class must pass itself, or a pass-through parameter - see Fish<TSelf>.
class Cat : Animal<Cat>
{
    // Tada, Cat can now make friends with other cats, and only other cats.
    public override void MakeFriends(Cat cat) {}
}

class CatWithBell : Cat
{   
    // Back to normal inheritance behaviour here.
    public override void MakeFriends(Cat cat) {}

    // Nothing to see here, just justifying the class name.
    public readonly bool HasBell = true;
}

// Here a further type parameter constrained with this is passed through.
// Note also that a new() constraint is placed on all directly implementing types.
// A class cannot directly inherit from this without meeting the new() constraint.
abstract class Fish<TSelf> : Animal<TSelf>
    where TSelf : this, new()
{
    // Fish are extra snooty and only make friends with their exact species.
    public override void MakeFriends(TSelf fish) {}

    // But they will at least politely wave at any other fish.
    public virtual void GreetFish<TFish>(TFish fish)
        where TFish : Fish<TFish>
    {}

    // Fish are made in factories right?
    public static TSelf MakeFish()
    {
        return new TSelf();
    }
}

class Trout : Fish<Trout>
{
    // Trout only make friends with trout.
    public override void MakeFriends(Trout trout) {}

    // Can greet any other fish.
    public override void GreetFish<TFish>(TFish fish)
        where TFish : Fish<TFish>
    {}
}

// Back to normal inheritance behaviour.
class TroutWithSunglasses : Trout
{
    // Does not meet the new() constraint defined in Fish<TSelf>. This is allowed.
    public TroutWithSunglasses(bool looksCool)
    {
        if (!looksCool) throw new ArgumentOutOfRangeException();
    }
}

// DOES NOT COMPILE
// This compiles in the example on Eric Lippert's blog. Here it does not.
//class EvilDog : Animal<Cat>
//{
//  public override void MakeFriends(Cat cat) { }
//}

void UsageDemo()
{
    Cat cat = new Cat();
    CatWithBell catWithBell = new CatWithBell();
    Trout trout = new Trout();
    TroutWithSunglasses troutWithSunglasses = new TroutWithSunglasses(true);

    // Cat satisfies Animal<TSelf>'s constraints so can be used here.
    Animal<Cat> animalCat = cat;
    // This all functions as normal.
    animalCat = catWithBell;

    // While not directly derived, CatWithBell still meets the constraints.
    // EDIT: This previously said "AnimalCat<CatWithBell> ..." This was a typo
    Animal<CatWithBell> animalCatWithBell = catWithBell;

    // DOES NOT COMPILE
    // While it does still derive from Fish<TSelf>, TroutWithSunglasses does not meet the new() constraint.
    //Fish<TroutWithSunglasses> fishTroutWithSunglasses;
}
```

**Comment by orthoxerox** [comment]
Looks like it can be handled by #154

**Comment by TheOtherSamP** [comment]
I just edited in the following note to the original comment:

A side-effect of this would be that an interface could restrict the types to which it can be applied. `where TSelf : class, this, Foo` would mean an interface can only be applied to class Foo and its children, and `where TSelf : this, IBar` would mean the interface could only be applied to types that also implement IBar. While not exactly the primary intention behind this feature, I actually think this could be a nice thing to have when building strong APIs with specific consumption of interfaces in mind.

**Comment by TheOtherSamP** [comment]
@orthoxerox while #154 is definitely something I've wanted for a while, I'm not immediately convinced it offers all of the features of this proposal. Does that allow for example the case where class Animal has a non-virtual and non-callable-on-the-base-class method MakeFriends(Animal animal) and derived class Cat gets a MakeFriends(Cat animal) without having to re-implement the method?

In a slightly more complete example I'm imagining the code may look something like:

```
abstract class Animal<TSelf>
	where TSelf : this
{
	private readonly List<TSelf> friends = new List<TSelf>();

	protected void MakeFriends(TSelf other)
	{
		this.friends.Add(other);
	}

	// Retrieving, so this.friends cannot just be List<Animal>.
	public TSelf BestFriend => this.friends.First();
}
```

**Comment by sirgru** [comment]
I really like this proposal and the way it handles the solution with `this`. I came across the limitation in CRT pattern a couple of times and it has "bugged" me a few times. I think this is a separate proposal. 
However, I am not convinced `this` should apply to derived classes.

Let's take the existing code example:
```
abstract class Animal<TSelf> where TSelf : this {
    protected Animal(){
        // this is always TSelf or a child of TSelf.
        TSelf self = this;
    }

    public virtual void MakeFriends(TSelf animal);
}

// A derived class must pass itself, or a pass-through parameter
class Cat : Animal<Cat> {
    public override void MakeFriends(Cat cat) {}
}

class CatWithBell : Cat {   
    public override void MakeFriends(Cat cat) {}
    public readonly bool HasBell = true;
}
```
wouldn't it then be possible to compile this:
```
abstract class Animal<TSelf> where TSelf : this {
    protected Animal(){
        // this is always TSelf or a child of TSelf.
        TSelf self = this;
    }

    public virtual void MakeFriends(TSelf animal);
}

// A derived class must pass itself, or a pass-through parameter
class Cat : Animal<CatWithBell > {
    public override void MakeFriends(CatWithBell cat) {}  /// <- Compiles but logical error.
}

class CatWithBell : Cat {   
    public override void MakeFriends(Cat cat) {}
    public readonly bool HasBell = true;
}
```

**Comment by TheOtherSamP** [comment]
> wouldn't it then be possible to compile this:

That was absolutely not the intended meaning of the spec, no, but I believe you have highlighted an ambiguity on my part, so thanks. 

To clarify, when I say 

> A derived class must pass itself, or a pass-through parameter

 I do strictly mean **itself**. Further derived classes are not allowed, so no, your example would not compile.

Perhaps the confusion stems from the following compiling example:
```
 // While not directly derived, CatWithBell still meets the constraints.
 // EDIT: This previously said "AnimalCat<CatWithBell> ..." This was a typo
 Animal<CatWithBell> animalCatWithBell = catWithBell;
```

The relevant section from the spec is
> Type parameters with the `this` constraint would be constrained to being either the implementing/deriving type itself, or a further `where TSelf : this` constrained type parameter on the implementing/deriving type. When used outside of derivation (e.g. to type a variable) further derived children would also be allowed.

So, when defining a class that inherits from a `where TSelf : this` constrained type you must pass that type itself, and not a further derived type. Further derived types may be used in other contexts.

To use your example, `public Animal<CatWithBell> BelledUpCat { get; }` is entirely valid, but `class Cat : Animal<CatWithBell> {}` is not.

**Comment by sirgru** [comment]
> So, when defining a class that inherits from a where TSelf : this constrained type you must pass that type itself, and not a further derived type. Further derived types may be used in other contexts.
I see, this clears it up for me. Looks good.

**Comment by CodeSingularity** [comment]
Why not abbreviate the syntax even further? allow the type

**Comment by CodeSingularity** [comment]
Why not abbreviate it even further? 

This syntax is similar to the Extension method syntax. The Generic type could be automatically inferred with the following syntax:

```
abstract class Animal<this TSelf> {
    protected Animal(){
        // this is always TSelf or a child of TSelf.
        TSelf self = this;
    }

    public virtual void MakeFriends(TSelf animal);
}

// A derived class must pass itself, or a pass-through parameter
class Cat : Animal  // the 'this' generic is automatically inferred, because we use used the 'this' keyword
{
    public override void MakeFriends(Cat cat) {}
}
```

**Comment by TheOtherSamP** [comment]
@CodeSingularity I considered the possibility of allowing something along these lines to simplify usage, but if we allow this the signature of `Animal<TSelf>` would clash with `Animal`. Currently it's possible to override a type definition on the number of type arguments, interfering with that in any way seems like a no go.

**Comment by CodeSingularity** [comment]
I see your point.

Would it possible to disallow the 'this TSelf' syntax if there are conflicting definitions?
(classes with the same name and no 'this' Generic)?

```
public class Animal
{ ... } 

public class Animal<this TSelf> // not allowed since Animal exists
{ ... } 
```

Another example, with generics

```
public class Animal<TFood>
{ ... } 

public class Animal<this TSelf, TFood> // not allowed since Animal<TFood> exists with a 'this' generic
{ ... } 
```

**Comment by TheOtherSamP** [comment]
@CodeSingularity It may perhaps be possible, though I suspect it would be tricky. I'm no expert on these matters, but I think a change would have to be made to how type names are typically stored, though I'm not sure. I also don't know if this would necessarily be a backwards compatibility breaking change.

If the constraint were implicit, then addressing `Animal` where it was implicitly `Animal<TSelf>` would be an open generic. There may perhaps be some way to sensibly resolve that, but I can't think of a robust solution off the top of my head.

To be honest I don't really see the advantage of this though. Some of the useful functionality of the feature comes from the ability to specify additional constraints on `T: this`, removing the explicit syntax altogether would either remove or obscure this possibility, making it optional obscures what's going on.

If we're intent on simplifying it when specifying the child class, perhaps some shortcut keyword could be used there. 

```
class LongConvolutedMessyClass<TKey, TValue, TPizza, TMilk> : SomeBaseClassWithTSelf<LongConvolutedMessyClass<TKey, TValue, TPizza, TMilk>>
{
}
```

could perhaps be unravelled from 

```
class LongConvolutedMessyClass<TKey, TValue, TPizza, TMilk> : SomeBaseClassWithTSelf<this>
{
}
```

 where `this` passed as a generic argument is substituted for the current class definition.

The whole point of suggesting this relatively simple generic constraint rather than requesting some other THISTYPE mechanism was to make the change as small as possible. Aside from this constraint, this feature already functions in the language. The support for generics is already there, the only thing missing is the ability to enforce this specific relationship. While I'm not comfortable using it over public APIs, I've already used a hacked together version of this internally in an experimental project by combining static runtime checks and a Roslyn analyzer.

By the principle of least astonishment, and a desire for the most elegant and efficient solution, I think that keeping the changes minimal is desirable, though I do quite like the substitutable `this`.


## Side note

You are using `class SomeClass<this TSelf>` to represent the syntax, where I am using `class SomeClass<TSelf> where TSelf: this`. Both are possibilities, but I feel that the existing syntax uses the keyword modifiers to determine what you can do with type internally (`in` and `out` dictate where you can use the type) whereas the constraints dictate what can be passed in. Personally I feel the constraint syntax is more appropriate here, though that's very much a triviality.

**Comment by TheOtherSamP** [comment]
I need to think about this more before I commit to anything, but I'm not so sure that this should only be applicable to abstract classes anymore. It may also work on unsealed classes, allowing you to pass that class itself as the type. To give an example

```
class SomeBase<TSelf>
    where TSelf: this
{}
```

Ahh, I see now why I disallowed this before. I think this would be useful were it possible (if it's not a child, `TSelf` would be `SomeBase<TSelf>`, if it is a child it would behave exactly as described above) but I don't know if there's a way to handle this within the language.

The type would have to be `SomeBase<SomeBase<SomeBase<SomeBase ... >>>` which would make little sense. Perhaps a shortcut syntax could be defined for this (let's go with `SomeBase<this>` for now) but I have no idea what that could possibly compile into. This may well be an impossibility without major changes. I should trust my previous judgement more.

**Comment by TheOtherSamP** [comment]
I've reformatted, edited, and tidied this up, and moved it over into the new repo at https://github.com/dotnet/csharplang/issues/169. Any further discussion should probably take place there, so I'm closing this for now.
