### ISSUE TITLE
"Generate constructor" fix is offered instead of only "Generate method"

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#11778]
**Version Used**: VS2015 Update 2
- Create a new console app and add the code below
- Move to the `new Class1(Method1(s), 123);` line and press Ctrl+.
- "Generate constructor" is offered even though `Method1(string)` doesn't exist. The fix suggests to create a constructor that takes `void` which is invalid.

In this case, only "Generate method" should be offered.

``` C#
    class Class1
    {
        Class1(string s, int i) { }
        void Method1(int i) { }
        void Method(string s)
        {
            new Class1(Method1(s), 123);
        }
    }
```

![pic3](https://cloud.githubusercontent.com/assets/1060731/15808722/59f10f22-2b7f-11e6-8bb4-63f0499f1aee.png)

**Comment by Pilchie** [comment]
We now default to `object` instead of `void`, which is a *little* bit better

**Comment by CyrusNajmabadi** [comment]
Behavior seems correct:

![image](https://user-images.githubusercontent.com/4564579/75645300-3e190480-5bfa-11ea-93a4-5769d3b9bbf8.png)

We offer to generate either the constructors or the method.  The former is fine as we don't want to force hte user to have to get their code entirely correct before we can help them generate code that they then may continue to fixup.
