### ISSUE TITLE
"Introduce local for all occurrences" creates a new local with the same name as an existing local causing the rename to fail

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#11777]
**Version Used**: VS2015 Update 2
- Create a console app and use the code below
- Select `span.End` in `while (pos < span.End)` and press `Ctrl+.`
- Select `Introduce local for all occurrences of 'Span.End'`

The refactoring creates a new local called `end` outside of the `while` loop, and this conflicts with the local `end` inside of the `while` loop. When renaming the new `end` outside of the loop, the code doesn't rename the `end` used on the line `int spanEnd = end;` (it was `span.End`)

``` C#
namespace ConsoleApplication
{
    class Program
    {
        class MySpan { public int Start { get; } public int End { get; } }
        void Method(MySpan span)
        {
            int pos = span.Start;
            while (pos < span.End)
            {
                int spanEnd = span.End;
                int end = pos;
            }
        }

        static void Main(string[] args)
        {
        }
    }
}
```

![pic1](https://cloud.githubusercontent.com/assets/1060731/15808603/709c0be0-2b7b-11e6-8bfc-949f63f70ecb.png)
![pic2](https://cloud.githubusercontent.com/assets/1060731/15808604/709d4d52-2b7b-11e6-976b-31332513e32b.png)

**Comment by Pilchie** [comment]
Should the unique name generation code handle this case better to avoid the conflict in the first place?  Once we've introduced it, I can see how it's hard to resolve however.
