### ISSUE TITLE
Roslyn & MSBuild NodeReuse issue

### ISSUE THREAD

**Issue by TraGicCode** [dotnet/roslyn#11780]
Referencing this closed issue #8539

MSBuild uses nodereuse by default which causes the Roslyn Compilers to have their DLL being used well after your build is finished.  What this means is if you are running a full clean and rebuild with a build script you will be unable to delete the Roslyn nuget package from your packages directory until you manually kill the MSBuild.exe nodes that are idle.

Is this something that is actively being looked at or is there any valid workaround currently?  

I can set nodereuse to false in the build script but visual studio still has this problem with nodereuse

**Comment by jasonmalinowski** [comment]
I believe @jaredpar knows what our current story is here.

**Comment by jaredpar** [comment]
CC @rainersigwald who can answer the MSBuild side of things.

From our side there really isn't much we can do here.  The compiler components are loaded by MSBuild and we don't really have a lot of control in how we are loaded.  If there were an attribute, option, etc ... for us to say "please don't hold onto us after build" it's absolutely something we'd insert into our NuGet package.  But the default for `msbuild /m` is to have `/nr:true` (at least to my knowledge) and as a result our NuGet package can get pinned by the lingering processes.

**Comment by glucaci** [comment]
It's still opened?
I have this problem by using the Compiler from NuGet (V 2.1.0).

`##[error]System.UnauthorizedAccessException: Access to the path '...packages\Microsoft.Net.Compilers.2.1.0\tools\Microsoft.CodeAnalysis.CSharp.dll' is denied. ---> System.ComponentModel.Win32Exception: Access is denied`

**Comment by cyberzed** [comment]
@glucaci can't be closed since we get it quite often with our builds using 2.10.0

**Comment by TraGicCode** [comment]
Hey,

This technically goes away in .net core since packages are stored in the users home directory.

**Comment by TraGicCode** [comment]
FYI Closing this as there really isn't much the roslyn team can do for this
