### ISSUE TITLE
IDE keeps .targets files around in ".vs" folder... can't properly uninstall NuGet

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#11799]
__REPRO:__

1. File>New>C#>Console
2. ManageNugetReferences>Add "UwpDesktop" 10.0.10586.2
3. Add a line of code "var t = Windows.Storage.KnownFolders.CameraRoll.GetFilesAsync();" and build the project
4. Uninstall the NuGet package
5. Rebuild the project
6. Close the solution, then delete the .vs folder from the project, then re-open the solution

__WHAT I EXPECT:__

After step 4, the IDE should no longer colorize "KnownFolders" as a known type. It should be all black, since it's unknown.

After step 4, the IDE should give me an error that the type or namespace "Storage" is unknown.

__WHAT I GET:__

After step 4, the IDE still colorizes the type, and doesn't show any errors.

After step 5, the external compiler VBCSCompiler.exe produces an error that "Storage" is unknown, but because the error isn't recognized by the IDE, it doesn't appear in the Error List and isn't squiggled.

It's only after step 6 that the IDE will once again understand that the type is unreferenced.

__NOTES:__

This particular NuGet package uses a ".targets" file. I hypothesize that the .vs folder is caching this .targets file, and isn't being recomputed once the NuGet package has been removed.

**Comment by Pilchie** [comment]
Tag @davkean - It's true that VS doesn't re-evaluate targets files until a project is re-loaded.  We're hoping that that is something that the CPS based new project system will address.

**Comment by Pilchie** [comment]
@srivatsn / @davkean - is this something that should be moved to the project system repo?

**Comment by srivatsn** [comment]
Whether this is addressed by CPS i'm not sure but yes I've moved this to the PS repo - https://github.com/dotnet/roslyn-project-system/issues/340
