### ISSUE TITLE
[Test Failure] Build Script (+1 more) in windows_eta_open_prtest on PR #11791

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#11794]
PR: [#11791](https://github.com/dotnet/roslyn/pull/11791) *Add a project that builds a "roslyn compilers" vsix package* by @TyOverby
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/290/

**Issue 1: Build Script**
A script in the build failed to execute correctly causing a build failure.

**Issue 2: Compile Error**
error CS0122: 'AbstractOptionPage' is inaccessible due to its protection level [d:\j\workspace\windows_eta_o---d880a2eb\Open\src\VisualStudio\VisualStudioDiagnosticsToolWindow\VisualStudioDiagnosticsWindow.csproj]

**Comment by Pilchie** [comment]
You fixed, this, right?

**Comment by jmarolf** [comment]
Fixed
