### ISSUE TITLE
Request: allow analyzer to modify the intellisense completion list

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#11797]
For a lot of analyzers I write, their sole purpose is to warn the user when they're using a particular API (warn in a particular context, or based on the state of the project, or just always warn).

It seems weird that the user has to type an invocation of the API and then wait a second for the squiggle to show up.

I wish I could make my analyzer more proactive by **annotating the intellisense completion list**. Specifically, I'd like my analyzer to put warning or error icons on some members that are listed in the completion list.

@srivatsn @Pilchie

**Comment by Pilchie** [comment]
This is definitely something that we want to happen, but it may not happen for 2.0.
