### ISSUE TITLE
[Test failure] ReplacePropertyWithMethods.ReplacePropertyWithMethodsTests

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#11813]
See https://github.com/dotnet/roslyn/pull/11671
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/292/

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi, can you take a look? This is failing on lots of other PRs as well.

**Comment by CyrusNajmabadi** [comment]
Fixed with: https://github.com/dotnet/roslyn/pull/11808
