### ISSUE TITLE
Consider using type alias for nested classes

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#11811]
**Version Used**: 2.0.0.60428

**Steps to Reproduce**:

``` C#
namespace ConsoleApplication1
{
    using A = D;

    class B1<T, U>
    {
        public class N { }
    }
    class B2<T> : B1<T, int> { } // two layers just for effect

    class D : B2<string> { }

    class Program
    {
        static void Main(string[] args)
        {
            A.N n = new B1<string, int>.N();
        }
    }
}
```

**Actual Behavior**:
`B1<string, int>` is suggested by autocomplete after `new`.

**Expected Behavior**:
`A.N` to be used in the autocomplete suggestion, or, perhaps in general, the type used for declaration to be suggested for instantiation.

Maybe even quick fix to simplify `B1<string, int>` to `A`? Might be arguable what is simpler though.

**Comment by Pilchie** [comment]
We do this for non-nested types already.

**Comment by CyrusNajmabadi** [comment]
Ckosing out given lack of community feedback on this and the complexity involved.
