### ISSUE TITLE
VB ObjectCreationCompletionProvider doesn't qualify names when ( is pressed

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#11812]
**Version Used**: 14.0.25123.00 Update 2

**Steps to Reproduce**:
```
Class A
    Sub Test()
        Dim b As B.C(Of Integer) = New $$
    End Sub
End Class

Namespace B
    Class C(Of T)
    End Class
End Namespace
```
Bring up the completion list at $$, and press `(`. 

**Expected Behavior**:
The insertion text should be `B.C`

**Actual Behavior**:
The insertion text if just `C`, leading to a compile error. This is (sort of) a regression from VS2013 (it didn't special case the `(`, but it did qualify the name correctly).

[GetInsertionTextAtInsertionTime](https://github.com/dotnet/roslyn/blob/105c5403271ebb72a62143f0d90bbd0168cac7c6/src/Features/VisualBasic/Portable/Completion/CompletionProviders/CompletionUtilities.vb#L146) should get the minimal display string. Instead, it just uses the raw symbol name.

**Comment by Pilchie** [comment]
Is this the same issue in #12254?

**Comment by lorcanmooney** [comment]
No, this one is specific to the VB implementation of that provider.

#12254 seems to be an issue decoding the symbol id/key, so it falls back to inserting the display text instead. I wonder why it doesn't use the _insertion_ text?
