### ISSUE TITLE
[Test Failure] <description> in windows_eta_open_prtest on PR #11807

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#11818]
PR: [#11807](https://github.com/dotnet/roslyn/pull/11807) *Improved error recovery for lambdas in a call with extra arguments.* by @gafter
Failure: [http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/319/](http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/319/)

**Comment by jasonmalinowski** [comment]
Job results are no longer available.
