### ISSUE TITLE
New PCL project wizard in VS uses dnxcore50 when ASP.NET Core 1.0 is checked

### ISSUE THREAD

**Issue by joelverhagen** [dotnet/roslyn#11823]
**Version Used**: 

Visual Studio 2015 U3 Preview
Visual Studio Tools for Universal Windows Apps 14.0.25219.0

**Steps to Reproduce**:
1. Create a new PCL.
2. Check **.NET Framework 4.6** and **ASP.NET Core 1.0**.
3. Create the project and look at the project.json.

**Expected Behavior**:

project.json should contain a guardrail for `netcoreapp1.0`, since this is what the new ASP.NET tooling is producing:
https://github.com/aspnet/Templates/blob/77fefe61b91616a6bcb9b77355324245e46923b2/src/BaseTemplates/EmptyWeb/project.json#L19

The target framework should be some `netstandard` version.

**Actual Behavior**:

The supports guardrails contains `dnxcore50.app` and the target framework is `dotnet`. Both of these are deprecated.

**Related**:

https://github.com/dotnet/corefx/issues/9232
https://github.com/NuGet/Home/issues/2908

@rchande

**Comment by Pilchie** [comment]
Does this seem fixable without breaking existing projects in time for Update 3?

**Comment by rchande** [comment]
The obvious thing to do is to just update the field in the targeting pack. 

To not break existing projects, we would need to augment the targeting pack to list what the previous supports were for a given framework. Of course, `netcoreapp1.0` isn't going to be understood by earlier versions.

It would be great if we could get a bar check. @joelverhagen Does anything bad happen as a result of listing dnxcore50?

**Comment by joelverhagen** [comment]
Not sure what you mean by "listing". Do you mean in the `"supports"` node or in the `"frameworks"` node?

**Comment by rchande** [comment]
Yes.

**Comment by joelverhagen** [comment]
`"supports"` should be fine. Not sure how long `dnxcore50.app` will stay in the runtime.json. As of https://github.com/dotnet/corefx/issues/9232, it's still there (/cc @ericstj).

For `"frameworks"` this is not ideal since it is not equivalent to `netcoreapp1.0`. As new versions of `netstandard` are released, we will not necessarily keep `dnxcore50` up to date. Even today, `dnxcore50` does not support `netstandard1.6`, but `netcoreapp1.0` does.

**Comment by rchande** [comment]
We only use it as a `support`, so that shouldn't be a problem. WRT removing it from runtime.json, what's the plan for all the existing projects that already use it?

**Comment by joelverhagen** [comment]
That is a decision made in corefx. If NuGet sees an unrecognized `supports` entry, it warns but does not error out.

**Comment by ericstj** [comment]
We don't plan to remove it.  My impression was that would be a breaking change.  Just like NuGet hasn;t removed the dnxcore50 framework moniker, we've left behind the supports clause.

**Comment by Pilchie** [comment]
Moving to 2.0 to consider there, but we won't take this for 1.3.

**Comment by ericstj** [comment]
What milestones are you talking about here?  This is a bug on the PCL project system.

**Comment by rchande** [comment]
@rchande what needs to happen here?

**Comment by CyrusNajmabadi** [comment]
Need info on if this is an actual issue affecting users.  Given no other mentions of this in 7 years, seems unlikely.
