### ISSUE TITLE
Generate from usage is not offered in VB

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#11828]
![image](https://cloud.githubusercontent.com/assets/10522107/15875530/2bd4d760-2cbd-11e6-9ecc-499c4b86dea0.png)

**Comment by Pilchie** [comment]
@AlekseyTs Can you include what the error is in that case?

**Comment by AlekseyTs** [comment]
I think it was something like:
error BC30456: 'InstrumentExpressionStatement' is not a member of 'Instrumenter'.

**Comment by Pilchie** [comment]
Could you point us to the code you were editing and/or construct a smaller repro?  There isn't much to work with here.
