### ISSUE TITLE
CodeStyle options should include control over "SimplifyToBase"

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#11821]
There's a simplification option called SimplifyToBase ([source link](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/ExpressionSyntaxExtensions.cs,1738)]

I understand the plan is to expose a bunch of options to the user in Tools > Options > TextEditor > C#/VB > CodeStyle > General.

When that happens, I want this option to be exposed too!

Note: see also #11820

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
