### ISSUE TITLE
NullReferenceException when composing the CSharp.Features assembly

### ISSUE THREAD

**Issue by aelij** [dotnet/roslyn#11841]
**Version Used**: 2.0.0-beta1-20160603-02

**Steps to Reproduce**:

1. Create host services with the `CSharp.Features` assembly:
```csharp
MefHostServices.Create(MefHostServices.DefaultAssemblies.Concat(new[] {
    Assembly.Load("Microsoft.CodeAnalysis.Features"), 
    Assembly.Load("Microsoft.CodeAnalysis.CSharp.Features") }))
```

**Expected Behavior**:
No exception

**Actual Behavior**:
```
System.NullReferenceException Object reference not set to an instance of an object.
   at System.Composition.TypedParts.Discovery.TypeInspector.AddMetadata(IDictionary`2 metadata, String name, Object value)
   at System.Composition.TypedParts.Discovery.TypeInspector.ReadMetadataAttribute(Attribute attribute, IDictionary`2 metadata)
   at System.Composition.TypedParts.Discovery.TypeInspector.ReadLooseMetadata(Object[] appliedAttributes, IDictionary`2 metadata)
   at System.Composition.TypedParts.Discovery.TypeInspector.<DiscoverInstanceExports>d__9.MoveNext()
   at System.Composition.TypedParts.Discovery.TypeInspector.<DiscoverExports>d__0.MoveNext()
   at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart(TypeInfo type, DiscoveredPart& part)
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
```

Note that this is probably related to this PR: https://github.com/dotnet/corefx/pull/6605
For example, `GenerateMethodCodeFixProvider` has two `ExtensionOrder` attributes.

**Workaround:**
Skip `ExtensionOrder` attributes:
```csharp
var compositionContext = new System.Composition.Hosting.ContainerConfiguration()
    .WithAssemblies(MefHostServices.DefaultAssemblies.Concat(new[] { 
        Assembly.Load("Microsoft.CodeAnalysis.Features"), Assembly.Load("Microsoft.CodeAnalysis.CSharp.Features") }))
    .WithDefaultConventions(new AttributeFilterProvider())
    .CreateContainer();

var host = MefHostServices.Create(compositionContext);

private class AttributeFilterProvider : AttributedModelProvider
{
    public override IEnumerable<Attribute> GetCustomAttributes(Type reflectedType, MemberInfo member)
    {
        var customAttributes = member.GetCustomAttributes().Where(x => !(x is ExtensionOrderAttribute)).ToArray();
        return customAttributes;
    }

    public override IEnumerable<Attribute> GetCustomAttributes(Type reflectedType, ParameterInfo member)
    {
        var customAttributes = member.GetCustomAttributes().Where(x => !(x is ExtensionOrderAttribute)).ToArray();
        return customAttributes;
    }
}
```

**Comment by weltkante** [comment]
Also affects the master branch, I'm running into this when trying to consume new CompletionService API.

**Comment by DustinCampbell** [comment]
So, unless I'm missing something, this is a bug in MEF that has been fixed by @aelij (nice!) and Roslyn just needs to pick up a new System.Composition. Is that correct?

**Comment by weltkante** [comment]
Yes, thats what its looking like currently. No idea if there are new nuget packages available for MEF yet.

**Comment by DustinCampbell** [comment]
Hmmm... I'm trying to understand why I this was working for me in OmniSharp where I successful composed the Features assemblies. It looks like we're using Microsoft.Composition, 1.0.27 in Roslyn and OmniSharp is using Microsoft.Composition, 1.0.30. If you reference 1.0.30 in your app, does that address the problem?

**Comment by weltkante** [comment]
1.0.30 doesn't seem to make a difference.

**Comment by DustinCampbell** [comment]
Hmmm... OK. The other big difference is that OmniSharp is using the 1.3.0 Roslyn packages rather than 2.0.0.

@stephentoub, @dsplaisted -- this looks related to https://github.com/dotnet/corefx/pull/6605. Has that made it into any official NuGet package yet? It looks like the last Microsoft.Composition release was 1.0.30, which is a year and a half ago.

**Comment by stephentoub** [comment]
> Has that made it into any official NuGet package yet? It looks like the last Microsoft.Composition release was 1.0.30, which is a year and a half ago.

@mellinoe has a PR adding packages for System.Composition.* here:
https://github.com/dotnet/corefx/pull/9640
I'm not sure about Microsoft.Composition.

**Comment by DustinCampbell** [comment]
OK. So, this is in flux at the moment. @tmat, you're our portability guru, right? :smile: Any thoughts?

Looking at [GenerateMethodCodeFixProvider](https://github.com/dotnet/roslyn/blob/fb9324de0f17a00616a53079785f5ebaff4a75d8/src/Features/CSharp/Portable/CodeFixes/GenerateMethod/GenerateMethodCodeFixProvider.cs), it seems like having multiple `ExtensionOrder` attributes is unnecessary and they could be combined into one. I wonder if that's the case everywhere?

cc @jasonmalinowski, @Pilchie

**Comment by weltkante** [comment]
GenerateMethodCodeFixProvider seems to be the only one preventing MEF to load the assembly. Merging both attributes into one and recompiling CSharp.Features allows MEF to load it :+1:

**Comment by DustinCampbell** [comment]
I see one other but it's in the Editor Features layer. I also see others that have combined the Before and After values, so I'm confident there's not some underlying bug. Feel like submitting a PR @weltkante?

**Comment by weltkante** [comment]
I can try making one, not very fluent with github yet; I wouldn't mind if someone else does one ;)

**Comment by DustinCampbell** [comment]
@weltkante's PR has been merged, which should workaround this issue for the Features layer.

**Comment by mattwar** [comment]
we should have a test that successfully composes the features layer into an AdHocWorkspace.

**Comment by DustinCampbell** [comment]
You're right. We should. I'll do that.

**Comment by aelij** [comment]
Cool :)
@DustinCampbell maybe you should also open an issue about upgrading to System.Composition once it's out on NuGet?
