### ISSUE TITLE
VS2015: IntelliSense randomly breaks, complaining about missing references CS0246

### ISSUE THREAD

**Issue by reaction1989** [dotnet/roslyn#11847]
In VS2015 Update 3 (It also happens with Update 1 and 2) the Intellisense breaks from time to time. Then there are alot of CS0246.

The assemblies which are "forgotten" by the Intellisense are on a Network Share and get replaced multiple times a day. The problem occurs mostly when a dll gets replaced.

The only solution to solve the problem is to restart VS.

**Comment by schneidt** [comment]
I got the same Problem with VS 2015 Update 1 - Update 3.

**Comment by jasonmalinowski** [comment]
@reaction1989 When you see this happen, if you look under the References node for the project, do you see yellow exclamation points over the references on the network share that got replaced?

**Comment by reaction1989** [comment]
@jasonmalinowski  No there are no yellow exclamation marks

**Comment by jasonmalinowski** [comment]
@reaction1989 and @schneidt, I have a small tool which you can download at https://github.com/jasonmalinowski/roslyn-info-logger/releases which helps us understand what is going on here. It's an extension you have to install into Visual Studio. The next time you hit this issue, you can then run "Tools > Log Roslyn Workspace Info" which will drop a file onto your desktop which we can then look at.

**Comment by reaction1989** [comment]
[RoslynWorkspaceInfo.zip](https://github.com/dotnet/roslyn/files/339151/RoslynWorkspaceInfo.zip)

We reproduced it by Opening Solution2 on Computer1 and Solution3 on Computer2. Then we builded on Computer2 and Computer1 got the error. The RoslynWorkspaceInfo is from Computer1

**Comment by schneidt** [comment]
@jasonmalinowski, any news? 
Still got the Problem, it is very annoying. 
Some Developers of our company switched back to VS 2010, because they argue they cannot work.

**Comment by Pilchie** [comment]
I think that https://github.com/dotnet/roslyn/pull/12686 should hopefully address this issue.  We're targeting putting this fix into a hotfix shipping around the end of August.

If you could email me at kevinpi@microsoft.com, I'd be happy to share a VSIX with the fix for you to try out before then.

**Comment by Pilchie** [comment]
(Moving out of Preview 4, since this fix is already included in Preview 4).

**Comment by Pilchie** [comment]
I just wanted to point out that the update at https://msdn.microsoft.com/en-us/library/mt752379.aspx now contains this fix.
