### ISSUE TITLE
Need a means to avoid triggering formatting

### ISSUE THREAD

**Issue by DanielRosenwasser** [dotnet/roslyn#11858]
The TypeScript language service needs some means of ensuring that formatting doesn't occur in certain contexts, like pressing `Enter` during completion sessions.

As an example, the code `new Array<n` is a valid expression in JavaScript/TypeScript. It's semantically the same as `(new Array()) < n`. 

A user might want to complete `n` with `number`, and press `Enter` at its entry in a completion list, because the intent might have been to eventually write `new Array<number>()`.

However, upon pressing `Enter`, formatting is triggered and the user ends up formatting the code as `new Array < number`. This is undesirable because we are unsure of the immediate intent.

See https://github.com/Microsoft/TypeScript/issues/6123 for more details.

**Comment by Pilchie** [comment]
Is this just #8337?  cc @balajikris @rchande

**Comment by balajikris** [comment]
Yes, I would think so. If I remember correctly, the spirit of bug #8337 was to not trigger formatting at all from completion, if possible. an exception _may be_ the preprocessor case mentioned in the bug. 

@CyrusNajmabadi also had thoughts about it, his view was to completely decouple formatting from completion code.

**Comment by CyrusNajmabadi** [comment]
Yes. I would like this to be completely decoupled.  If preprocessor needs to be left aligned, then we should do that in a separate way.  That said, i think we *already* have support for this in the completion API.  A CompletionItem can just say what TextChange it wants when it is committed.  So the completion items for preprocessor directives should just return the right text change to put them at the start of the line.

**Comment by CyrusNajmabadi** [comment]
Fixed with #12275

**Comment by DanielRosenwasser** [comment]
Thanks @CyrusNajmabadi!
