### ISSUE TITLE
VS is unresponsive during a build.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#11863]

**Comment by Pilchie** [comment]
Can we get a trace and find out why VS is not handling messages?

**Comment by AdamSpeight2008** [comment]
Could related to Issue #11942 on the Priorioty level used.

**Comment by AdamSpeight2008** [comment]
@Pilchie
Does the change in the milestone, indicate that the issue is fixed?

**Comment by Pilchie** [comment]
No, if it was fixed, it would be closed.  It means that we won't hold the Preview 4 milestone for this.

**Comment by CyrusNajmabadi** [comment]
No data provided here.  Closing out.
