### ISSUE TITLE
GetOperation on a VB constructor block returns Nothing instead of an IBlock operation.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#11860]
Discovered through this customer PR: #11743

There does not appear to be a way to get an IBlock for a VB constructor like you can for a C# constructor.  Calling GetOperation on the ConstructorBlock returns nothing as does calling GetOperation on the SubNewStatement header.

**Comment by jinujoseph** [comment]
@CyrusNajmabadi  this is fixed right ?

**Comment by CyrusNajmabadi** [comment]
It is likely fixed.  I will test and add test as appropriate.

**Comment by CyrusNajmabadi** [comment]
Yes.  This has been fixed.  Tests like IBlockStatement_SubNewBlock validate that it is working properly.  Closing.
