### ISSUE TITLE
Random crash (NullReferenceException) experienced while using signature help

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#1187]
I don't have any repro, just the crash information. The dump is available on internal bug 1127440.

    > Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler) Unknown
      Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.SignatureHelp.CommonSignatureHelpUtilities.TryGetSyntax<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax>(Microsoft.CodeAnalysis.SyntaxNode root, int position, Microsoft.CodeAnalysis.LanguageServices.ISyntaxFactsService syntaxFacts, Microsoft.CodeAnalysis.Editor.SignatureHelpTriggerReason triggerReason, System.Func<Microsoft.CodeAnalysis.SyntaxToken, bool> isTriggerToken, System.Func<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax, Microsoft.CodeAnalysis.SyntaxToken, bool> isArgumentListToken, System.Threading.CancellationToken cancellationToken, out Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax expression) Unknown
      [Native to Managed Transition] 
      [Managed to Native Transition] 
      Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.SignatureHelp.CommonSignatureHelpUtilities.TryGetSyntax<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax>(Microsoft.CodeAnalysis.SyntaxNode root, int position, Microsoft.CodeAnalysis.LanguageServices.ISyntaxFactsService syntaxFacts, Microsoft.CodeAnalysis.Editor.SignatureHelpTriggerReason triggerReason, System.Func<Microsoft.CodeAnalysis.SyntaxToken, bool> isTriggerToken, System.Func<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax, Microsoft.CodeAnalysis.SyntaxToken, bool> isArgumentListToken, System.Threading.CancellationToken cancellationToken, out Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax expression) Unknown
      Microsoft.CodeAnalysis.CSharp.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.CSharp.SignatureHelp.AttributeSignatureHelpProvider.TryGetAttributeExpression(Microsoft.CodeAnalysis.SyntaxNode root, int position, Microsoft.CodeAnalysis.LanguageServices.ISyntaxFactsService syntaxFacts, Microsoft.CodeAnalysis.Editor.SignatureHelpTriggerReason triggerReason, System.Threading.CancellationToken cancellationToken, out Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax attribute) Unknown
      Microsoft.CodeAnalysis.CSharp.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.CSharp.SignatureHelp.AttributeSignatureHelpProvider.GetItemsWorkerAsync(Microsoft.CodeAnalysis.Document document, int position, Microsoft.CodeAnalysis.Editor.SignatureHelpTriggerInfo triggerInfo, System.Threading.CancellationToken cancellationToken) Unknown
      mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.CodeAnalysis.Editor.CSharp.SignatureHelp.AttributeSignatureHelpProvider.<GetItemsWorkerAsync>d__5>(ref Microsoft.CodeAnalysis.Editor.CSharp.SignatureHelp.AttributeSignatureHelpProvider.<GetItemsWorkerAsync>d__5 stateMachine) Unknown
      Microsoft.CodeAnalysis.CSharp.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.CSharp.SignatureHelp.AttributeSignatureHelpProvider.GetItemsWorkerAsync(Microsoft.CodeAnalysis.Document document, int position, Microsoft.CodeAnalysis.Editor.SignatureHelpTriggerInfo triggerInfo, System.Threading.CancellationToken cancellationToken) Unknown
      Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.AbstractSignatureHelpProvider.GetItemsAsync(Microsoft.CodeAnalysis.Document document, int position, Microsoft.CodeAnalysis.Editor.SignatureHelpTriggerInfo triggerInfo, System.Threading.CancellationToken cancellationToken) Unknown
      mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.AbstractSignatureHelpProvider.<GetItemsAsync>d__15>(ref Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.AbstractSignatureHelpProvider.<GetItemsAsync>d__15 stateMachine) Unknown
      Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.AbstractSignatureHelpProvider.GetItemsAsync(Microsoft.CodeAnalysis.Document document, int position, Microsoft.CodeAnalysis.Editor.SignatureHelpTriggerInfo triggerInfo, System.Threading.CancellationToken cancellationToken) Unknown
      Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Session.ComputeItemsAsync(System.Collections.Generic.IList<Microsoft.CodeAnalysis.Editor.ISignatureHelpProvider> providers, Microsoft.VisualStudio.Text.SnapshotPoint caretPosition, Microsoft.CodeAnalysis.Editor.SignatureHelpTriggerInfo triggerInfo, Microsoft.CodeAnalysis.Document document, System.Threading.CancellationToken cancellationToken) Unknown
      mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Session.<ComputeItemsAsync>d__10>(ref Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Session.<ComputeItemsAsync>d__10 stateMachine) Unknown
      Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Session.ComputeItemsAsync(System.Collections.Generic.IList<Microsoft.CodeAnalysis.Editor.ISignatureHelpProvider> providers, Microsoft.VisualStudio.Text.SnapshotPoint caretPosition, Microsoft.CodeAnalysis.Editor.SignatureHelpTriggerInfo triggerInfo, Microsoft.CodeAnalysis.Document document, System.Threading.CancellationToken cancellationToken) Unknown
      Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Session.ComputeModelInBackgroundAsync(Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Model currentModel, System.Collections.Generic.IList<Microsoft.CodeAnalysis.Editor.ISignatureHelpProvider> matchedProviders, System.Collections.Generic.IList<Microsoft.CodeAnalysis.Editor.ISignatureHelpProvider> unmatchedProviders, Microsoft.VisualStudio.Text.SnapshotPoint caretPosition, Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.DisconnectedBufferGraph disconnectedBufferGraph, Microsoft.CodeAnalysis.Editor.SignatureHelpTriggerInfo triggerInfo, System.Threading.CancellationToken cancellationToken) Unknown

**Comment by MattGertz** [comment]
Approved for next preview
