### ISSUE TITLE
VB Out Parameter support

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#11880]
**Version Used**: 
VS 2015 Update 2
**Steps to Reproduce**:
1. Declare Function with <Out()> attribute.

```
    Public Function Return6(<Out()> ByRef LastErrorMessage As String) As Integer
        LastErrorMessage = "None"
        Return 6
    End Function
```
1. Call Function

```
Six = Return6 (ReturnError)
```

**Expected Behavior**:
No Warnings, I don't want to have to assign a default value to an Out variable like ReturnError to make the warning disappear.
**Actual Behavior**:

```
Warning BC42030 Variable 'ReturnError' is passed by reference before it has been assigned a value. A null reference exception could result at runtime.
```

**Comment by gafter** [comment]
Issue moved to [dotnet/vblang #67](https://github.com/dotnet/vblang/issues/67) via [**ZenHub**](https://www.zenhub.com/)
