### ISSUE TITLE
[Test Failure] No identified problem in windows_debug_unit64_prtest on PR #11881

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#11883]
PR: [#11881](https://github.com/dotnet/roslyn/pull/11881) *Remove named argument3* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/406/

**Issue 1: No identified problem**
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.

21:55:02 java.lang.NullPointerException
21:55:02 	at org.jenkinsci.plugins.xunit.XUnitProcessor.performTests(XUnitProcessor.java:145)
21:55:02 	at org.jenkinsci.plugins.xunit.XUnitProcessor.performXUnit(XUnitProcessor.java:88)
21:55:02 	at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:142)
21:55:02 	at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:134)
21:55:02 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
21:55:02 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
21:55:02 	at

**Comment by Pilchie** [comment]
@dotnet/roslyn-infrastructure @jaredpar any idea on this one?

**Comment by jasonmalinowski** [comment]
Job results have gone away...
