### ISSUE TITLE
[Test Failure] Build Script (+1 more) in windows_eta_open_prtest on PR #11881

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#11893]
PR: [#11881](https://github.com/dotnet/roslyn/pull/11881) *Remove named argument3* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/406/

**Issue 1: Build Script**
A script in the build failed to execute correctly causing a build failure.

**Issue 2: MSBuild Error**
error MSB3073: The command "d:\j\workspace\windows_eta_o---d880a2eb\Open\Binaries\Debug\csi.exe ..\..\Open\build\BuildNuGets.csx d:\j\workspace\windows_eta_o---d880a2eb\Open\Binaries\Debug\ 2.0.0-beta1 d:\j\workspace\windows_eta_o---d880a2eb\Open\Binaries\Debug\NuGet\PreRelease" exited with code 1.

11:31:25   Attempting to build package from 'Microsoft.CodeAnalysis.Test.Resources.Proprietary.nuspec'.
11:31:25   Could not find a part of the path 'd:\j\workspace\windows_eta_o---d880a2eb\Open\Binaries\Debug\ProprietaryTestResources'.

**Comment by tmat** [comment]
This should fix it: https://github.com/dotnet/roslyn-internal/pull/1055
