### ISSUE TITLE
Build in master fails in src/tools/source/CompilerGeneratorTools

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#11891]
Build in master fails in src/tools/source/CompilerGeneratorTools:
...
C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(109,5): error : Your project is not referencing the "DNXCore,Version=v5.0" framework. Add a reference to "DNXCore,Version=v5.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [... src\Tools\Source\CompilerGeneratorTools\Source\VisualBasicErrorFactsGenerator\VisualBasicErrorFactsGenerator.vbproj]
...

**Comment by jasonmalinowski** [comment]
And this was fixed #11892.
