### ISSUE TITLE
[Test Failure] Build Script in windows_debug_unit32_prtest on PR #11881

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#11894]
PR: [#11881](https://github.com/dotnet/roslyn/pull/11881) *Remove named argument3* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/414/

**Issue 1: Build Script**
A script in the build failed to execute correctly causing a build failure.

**Comment by Pilchie** [comment]
That log doesn't seem to exist anymore.
