### ISSUE TITLE
Naming styles for "private fields" shouldn't apply to script locals.

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#11890]

**Comment by dpoeschl** [comment]
@Pilchie How did you see this? I can't get any Naming Styles to file in the REPL or .csx files. No lightbulbs and nothing in the error list.

**Comment by Pilchie** [comment]
I configured it as a warning and got squiggles.  Maybe something about moving it OOP made the analyzer stop running in that workspace though?

**Comment by Pilchie** [comment]
I can't repro anymore either.
