### ISSUE TITLE
Remove duplicate copies of test helper ToTestDisplayString extension method

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#11915]
Currently, there are multiple copies of extension method [ToTestDisplayString](http://source.roslyn.io/#q=ToTestDisplayString) in C# and VB compiler test layers. We should move this extension method to the core test utilities project and remove the duplicate copies and fix all the callsites by adding the necessary using.

**Comment by nbalakin** [comment]
I've found a couple more occurrences of kind of similar methods. Should those method also be moved to the same class just for consistency sake?

```static string ToTestDisplayString(this Symbol symbol)```
https://github.com/dotnet/roslyn/blob/master/src/Compilers/Test/Utilities/CSharp/Extensions.cs#L682

```static string ToTestDisplayString(this TypeWithAnnotations symbol, bool includeNonNullable = false)
static string[] ToTestDisplayStrings(this IEnumerable<TypeWithAnnotations> symbols)
static string[] ToTestDisplayStrings(this IEnumerable<ISymbol> symbols)
static string[] ToTestDisplayStrings(this IEnumerable<Symbol> symbols)
static string ToTestDisplayString(this ISymbol symbol, bool includeNonNullable)
static string ToTestDisplayString(this Symbol symbol, bool includeNonNullable)
```
https://github.com/dotnet/roslyn/blob/master/src/Compilers/Test/Utilities/CSharp/SymbolUtilities.cs#L111

**Comment by jcouv** [comment]
Fixed by @nbalakin in `master`. Thanks!
