### ISSUE TITLE
Analyzer exeption diagnostics in IDE don't show detailed exception stacks

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#11926]
See https://github.com/dotnet/roslyn-analyzers/issues/1050 for an example AD0001 - we don't seem to be emitting the line numbers for the exception call stack anymore.

**Comment by heejaechang** [comment]
copy & paste comments from different issue. 

....
heejaechang commented an hour ago
what do you expect it to show?
 @mavasani
     .NET Foundation member
mavasani commented an hour ago
Line numbers for the call stack? I remember we used to see them before
 @heejaechang
     .NET Foundation member
heejaechang commented 2 minutes ago • edited
I just checked, this code just show diagnostic reported by compiler. so this should be exactly same as v1.

so, if line number is not there, then, there is no line number before.

http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerExecutor.cs,1111

...

**Comment by srivatsn** [comment]
Isn't that supposed to come from exception.message if the pdb is available? I don't think it's anything we control. Can you check your pdb?

**Comment by heejaechang** [comment]
it shows line number with pdb.
