### ISSUE TITLE
Rename resolves NameOf conflict with erroneous "this"

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#1193]
In the following example, when "z" is renamed to "Fail", the ambiguity within the nameof is resolved by qualifying "Fail" with "this.". This is invalid, since F is static.

```C#
class C
{
    // Rename z to Fail
    static void F(int z)
    {
        string x = nameof(Fail);
    }

    int Fail;
}

**Comment by dpoeschl** [comment]
@rchande Please verify
