### ISSUE TITLE
vbcscompiler.exe should be launched at below normal priority

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#11942]
Right now when a build is invoked from VS this process is launched at normal priority and uses all the cores on the machine.  This creates a lot of contention for CPU and causes noticeable slowdown in VS and other processes (chrome, for example).  

I've set the process to be below-normal and have seen no serious impact on compilation speed.  For Roslyn.sln speeds were within 2 seconds of normal.  However, the impact on the rest of the system is enormous.  VS no longer feels sluggish during build, other processes work great.

While it is great that our compiler scales up so well to the machine, i don't think it's great that it does so in a way that so greatly impacts the rest of the user experience.  It's common to start a build and want to go do other things while that build happens.  Setting the build to be lower priority makes that possible, with little impact to the experience, and with practically no downsides.

**Comment by CyrusNajmabadi** [comment]
This would be a good, cheap, win for the perf epic.  VS not being sluggish is definitely something we want, and this is an easy way to accomplish that in one scenario.

**Comment by VSadov** [comment]
seems to be the same as https://github.com/dotnet/roslyn/issues/11863

**Comment by VSadov** [comment]
In theory Windows should automatically boost the priority of the foreground app - VS in this case. I wonder why that is not sufficient. 
Could it be something on VS side - like deprioritizing background processing and thus starving itself even with priority boost it gets form the OS?

The other thing worth mentioning is that there are certain scenarios where duration of the build initiated from VS is considered an important perf metric and tracked by RPS. For example how fast you hit a breakpoint after F5. 
Deprioritizing build process will certainly result in a regression in those metrics. Perhaps that is acceptable, just need to mention...

The other possible issue is that compiler server process could be shared by both IDE and cmd builds. Accommodating one scenario could hurt another. But that might be ok. Considering that server does not live long, actual sharing might not be a common scenario.

**Comment by CyrusNajmabadi** [comment]
It’s not just VS.  Other apps are also substantially impacted.  Chrome, Slack, Edge, Outlook, etc.

> Deprioritizing build process will certainly result in a regression in those metrics.

In my own testing, the amount of perf regression accounted for noise.  i.e. it was within the margin of error.

          -- Cyrus

**Comment by GSPP** [comment]
Deprioritizing should not cause any slowdown at all assuming that enough CPU resources are available. Priority is a tie breaker in case there is contention for the CPU. If there are no interfering foreground processes, and why would there be any in a headless scenario, there should only be a tiny statistical slowdown like 0.1% caused by the rare case that a normal-priority process needs a few microseconds of CPU.

**Comment by jaredpar** [comment]
I do not think this is the appropriate approach to the problem here.  It changes our build throughput behavior for all scenarios vs. the specific one being addressed here.  That's not an acceptable trade off for the compiler where throughput is our overriding goal.  

If VS decides this is a scenario worth addressing then it should be launching MSBuild in a different mode, perhaps at lower priority, to address the problem.

**Comment by CyrusNajmabadi** [comment]
Reactivating.  tagging @Pilchie .  This is a very poor user experience.  

Can we have our build task kick off the vbcscompiler process at low priority if invoked from VS?  As i've mentioned above, the actual build time doesn't suffer, but the user can actually reasonably use their machine while building is happening.

This would address the concern of things like "will this affect perf in a build lab".

**Comment by jaredpar** [comment]
This bug needs measurement and numbers to move forward.

**Comment by CyrusNajmabadi** [comment]
What sorts of measurements or numbers?  Compiling Roslyn.sln locally showed no observable change in the time it took to get results.  And even if it has taken longer... that's ok.  Because i can use my machine while building is occurring.  And if i'm trying to use my machine, then it's ok if other processes on the machine get the CPU resources they need to get things done :)

**Comment by jaredpar** [comment]
> And even if it has taken longer... that's ok. Because i can use my machine while building is occurring.

This is incorrectly simplifying the compiler server lifetime issues.  The compiler server is not tied to a given solution, VS instance, etc ... Instead it's a shared server amongst all ways builds are invoked.  It can't be made low priority for VS when an active command line build is occurring for instance (and there really isn't a way to differentiate between them).  

> Compiling Roslyn.sln locally showed no observable change in the time it took to get results

This is not a sufficient measurement.  In Roslyn the compiler is really not competing against anything hence making it low priority is unlikely to affect performance.  Over 70% of our build is dominated just compiling code.   In more complex build environments, where there are different languages and tools, the compiler server would be at a disadvantage.

**Comment by Pilchie** [comment]
Also tagging @AndyGerlicher, @agocke, @srivatsn, @davkean, @jasonmalinowski 

> In more complex build environments, where there are different languages and tools

This is a good point, and one I haven't considered.  Maybe this PR is too focused on Roslyn itself.  Maybe the right fix is actually for MSBuild to drop it's own priority when launched from VS (which I think is inherited by child processes) so that VS itself stays more responsive.

This used to be an option in build.exe that a lot of people used even for commandline builds, because they wanted to use outlook, etc, during the build.

Could we consider adding it to msbuild, and then having a VS option to allow setting it by default for builds launched by VS?

**Comment by Pilchie** [comment]
We might also want to consider having a different behavior if build is pressed versus start debugging, considering that in the latter case, the user is probably just waiting for the build to finish.

**Comment by jasonmalinowski** [comment]
> Maybe the right fix is actually for MSBuild to drop it's own priority when launched from VS (which I think is inherited by child processes) so that VS itself stays more responsive.

I think this is a good proposal. This means that build environments that were setting priority (either low, or heck, high!) then get the behavior they're expecting.

@jaredpar did observe that the process isn't necessarily parented by a single MSBuild instance. I guess the command line compiler could figure out what it's effective thread priority is for it's invocation and then set different thread priorities in VBCSCompiler. Or have different instances for different priorities.

**Comment by jaredpar** [comment]
> I guess the command line compiler could figure out what it's effective thread priority is for it's invocation and then set different thread priorities in VBCSCompiler

Don't think that's a good idea.  Consider the scenario where I simultaneously build from command line and build from Visual Studio.  Using thread priorities means the command line build will starve out the VS build until it completes.  

> Or have different instances for different priorities.

Would need a **lot** of evidence to have multiple VBCSCompiler instances.  It generates a lot of negative customer feedback.  Not sure that the scenario is worth the negative hit we'd take here.

> did observe that the process isn't necessarily parented by a single MSBuild instance

It's also parented by other processes than MSBuild: csc / vbc for instance are a driver in ASP.Net website scenarios. 

Overall I'm still not convinced this proposal is a good one.  It's too narrowly focused on a single problem and isn't considering the bigger picture.  Changing the priority of the compiler process means to low means that virtually anything else happening on your box will take priority over the compiler (which the user explicitly invoked): other builds, outlook, chrome, etc ...  I don't see how this wouldn't lead to loads of user feedback that "my compiles never finish when I build in VS".

**Comment by VSadov** [comment]
FWIW VS has UI to specify how many msbuild instances to spawn. Seems like it could specify priority as well. Perhaps even default to "Low"

Also - I wonder if you lower the number of parallel builds to`#physicalCores-1`, does it solve the issue with browsing/editing while building?

**Comment by VSadov** [comment]
As I see on my box the default number of parallel builds is `#logicalCores` which seems like set up intentionally to saturate the machine when building.

**Comment by davkean** [comment]
Folks, I just upgraded to Version 15.3.0-pre.1.0+26525.3003.d15prerel, and it feels like something has regressed in the past week, perhaps Cyrus is running into that as well?

Building from the command-line is fine, building from Visual Studio, however, causes Visual Studio to be unusable, not even being able to scroll the editor unusable. Capturing traces now...

**Comment by davkean** [comment]
Note, my issue was the diagnostic builds turned on, I've filed https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workItems?id=443365&fullScreen=false&_a=edit against CPS.

**Comment by informatorius** [comment]
I see this issue closed but in Visual Studio 2017 when building vbsccompiler still has normal priority?

**Comment by CyrusNajmabadi** [comment]
@informatorius the current behavior was deemed to be correct (or out of the hands of roslyn).  If a host wants to launch vbcscompiler at lower priority, it's up to the host to do so.
