### ISSUE TITLE
Clarify with LDM some details regarding Tuple Implicit/Explicit conversions

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#11941]
- Do we allow Explicit tuple conversion from Type?
- Do we allow Explicit tuple conversion from Expression?
- Do we allow Implicit/Explicit conversions from Type when tuples of the same structural signature have different underlying types.
- Do we allow actual underlying types equally with tuple types in various combinations in conversions. That is relevant only for APIs like ClassifyConversion

I assume the answer is Yes on all counts, but we need to check.

Also see: https://github.com/dotnet/roslyn/issues/11805    that is mostly about implementation details, but related.

**Comment by VSadov** [comment]
@gafter - FYI

**Comment by jcouv** [comment]
I think all those questions have been addressed in 6/17 LDM. Close the issue?

**Comment by VSadov** [comment]
Yes. All items are addressed.
