### ISSUE TITLE
How to get Diagnostics chinese message?

### ISSUE THREAD

**Issue by tylike** [dotnet/roslyn#11944]
**Version Used**: 
1.2.2
**Steps to Reproduce**:
hi,all:
I wan't use roslyn to get Diagnostics chinese message,like this:

SourceText sourceText = SourceText.From("public class t{  public void Test(){ var x =1/0; }  }");
var doc = Workspace.CurrentSolution.Projects.Single().Documents.Single(x => x.Name == 'file.cs');
doc = doc.WithText(sourceText);                
var sem = doc.GetSemanticModelAsync().Result;
var rst = sem.GetDiagnostics();
foreach (var item in rst)
{
// System.Globalization.CultureInfo.CurrentCulture is zh-CN
       richTextBox1.AppendText(item.GetType().Name + ":" + item.GetMessage(System.Globalization.CultureInfo.CurrentCulture) + "\n");
}
               
But the results I get are still English, what should I do?

**Comment by srivatsn** [comment]
From the API this should work i think. @mavasani can you take a look?

**Comment by mavasani** [comment]
We have a test that verifies this works fine: http://source.roslyn.io/#Roslyn.Compilers.UnitTests/Diagnostics/DiagnosticLocalizationTests.cs,98

@tylike - can you confirm that `System.Globalization.CultureInfo.CurrentCulture` is indeed the Chinese culture for you? Can you try to execute your test with explicitly created Chinese culture with [this](http://referencesource.microsoft.com/#mscorlib/system/globalization/cultureinfo.cs,44db57d9e190258e,references) API?

**Comment by tylike** [comment]
@mavasani 
It was my fault, I did not download the language resource file(zh-CN).
I found Roslyn 1.0 version of the language resources file from nuget , version 1.2 used and it does not apply to me.
Nuget is not available on all versions of the language resources package?
My English is poor, please forgive me.
