### ISSUE TITLE
[Test Failure] Build Script in linux_debug_prtest on PR #11838

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#11946]
PR: [#11838](https://github.com/dotnet/roslyn/pull/11838) *Share code in completion tests.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/linux_debug_prtest/455/

**Issue 1: Build Script**
A script in the build failed to execute correctly causing a build failure.

19:25:53 CSC : warning CS8032: An instance of analyzer XmlDocumentationComments.Analyzers.CSharpAvoidUsingCrefTagsWithAPrefixAnalyzer cannot be created from /home/dotnet-bot/.nuget/packages/XmlDocumentationComments.Analyzers/1.2.0-beta2/analyzers/dotnet/cs/XmlDocumentationComments.CSharp.Analyzers.dll : Could not load file or assembly 'XmlDocumentationComments.Analyzers, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified. [/mnt/j/workspace/dotnet_roslyn/master/linux_debug_prtest/src/Compilers/VisualBasic/VbcCore/VbcCore.csproj]
19:25:53   VbcCore -> /mnt/j/workspace/dotnet_roslyn/master/linux_debug_prtest/Binaries/Debug/vbccore/vbc.exe
19:25:53 cp: cannot stat ‘/home/dotnet-bot/.nuget/packages/runtime.ubuntu.14.04-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.2-rc3-24128-00/tools/crossgen’: No such file or directory
19:25:53 make: *** [bootstrap] Error 1
19:25:53

**Comment by mavasani** [comment]
@tmat has already fixed this few days back with https://github.com/dotnet/roslyn/pull/11956.
