### ISSUE TITLE
Cannot rename or get completion for using alias

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#11959]
**Version Used**: VS2015.2

**Steps to Reproduce**:
**File1**

``` csharp
namespace AliasRepro.Ns.Test
{
    class TestClass
    {
    }
}
```

**File2**

``` csharp
using System.Threading.Tasks;
using NsTest = AliasRepro.Ns.Test;

namespace AliasRepro
{
    class Program
    {
        static void Main(string[] args)
        {
        }

        static async Task Method()
        {

        }
    }
}
```
# Cannot Rename
1. Select `NsTest` in the second line of the second file and press F2 to rename it
2. NsTest will be selected and rename dialog appears but text isn't green
3. Typing any character will abort inline rename session

**Expected Behavior**:
I can rename the using alias `NsTest`

**Actual Behavior**:
![devenv_2016-06-13_11-19-58](https://cloud.githubusercontent.com/assets/7110884/16002647/0f9945e0-3159-11e6-9e20-a38cef79363f.png)
# Cannot get completion
1. Go to `static async Task Method()`
2. Change `Task` to `Task<NsTest.`

**Expected Behavior**:
I get IntelliSense for `TestClass`

**Actual Behavior**:
No IntelliSense shows up

**Comment by rchande** [comment]
Can you see if this is a compiler bug?

**Comment by ivanbasov** [comment]
Verified both scenarios with the latest VS (VS 2019 Preview 2.0). Both work fine.

**Comment by Suchiman** [comment]
@ivanbasov i tried in VS2019 Preview 1 and just updated to Preview 2 and see no difference.

**Comment by ivanbasov** [comment]
Thank you, @Suchiman !

I was able to reproduce the scenarios.
1. The rename one does not highlight with green because there are no references to the using. As soon, as there are references, it applies a normal rename highlighting.

2. The intellisense for methods under namespace under generic seems to be an issue. Reopening
