### ISSUE TITLE
ReduceExtensionMethod couldn't reduce the extension methods defined in a different assembly

### ISSUE THREAD

**Issue by ansyral** [dotnet/roslyn#11950]
**Version Used**: 
1.2.2
**Steps to Reproduce**:
```csharp
var c1 = CSharpCompilation.Create("C1",
                new[] { Parse(@"public class S { }") },
                null,
                TestOptions.ReleaseDll);

var c2 = CSharpCompilation.Create("C2",
                new[] { Parse(@"public static class SExt { public void static M(this S s) { }") },
                new[] { new CSharpCompilationReference(c1) },
                TestOptions.ReleaseDll);

var @c = c1.GlobalNamespace.GetMember<NamedTypeSymbol>("S");
var method = c2.GlobalNamespace.GetMember<NamedTypeSymbol>("SExt").GetMember<MethodSymbol>("M");

var reduced = method.ReduceExtensionMethod(@c);
```

**Expected Behavior**:
reduced != null

**Actual Behavior**:
reduced is null

i'm not sure, seems NamedTypeSymbol.Equals couldn't handle RetargetingNamedTypeSymbol? should it check its UnderlyingNamedType?

**Comment by gafter** [comment]
You looked up `S` in the wrong compilation. If you want to reduce in compilation `c2`, you need to get the symbol from `c2.

**Comment by ansyral** [comment]
Thanks, gafter. but what i want to do is to find all the extension methods of types defined in `c1`, for example `S`. is there any way I can do that?

**Comment by ansyral** [comment]
add one more comment, `c1` might not reference `c2`, so i might not be able to get the extension method from `c1`'s reference
