### ISSUE TITLE
Renaming a member to a name used within a nameof is a conflict

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#1195]
In the below example, renaming "F" to "Fail" causes rename to cause an unresolvable conflict in the nameof. If you commit the rename, there are no errors. Rename is probably confused because the nameof binds to more symbols than it used to.

```C#
class C
{
    // Rename F to Fail
    static void F(int x) { }

    [System.Obsolete(nameof(Fail))]
    static void Fail() { }
}

**Comment by dpoeschl** [comment]
@rchande Please verify.
