### ISSUE TITLE
Allow methods with generic type parameters to place further constraints on their defining types' type parameters

### ISSUE THREAD

**Issue by tuespetre** [dotnet/roslyn#11960]
*Apologies if this is covered elsewhere; I searched "constraint" on this repo and scanned each page of results and did not see anything that seemed to match.*

## Examples

```
interface A {}

interface B {}

interface C<T> where T : B 
{
    void Method(T arg0);
}

class D<T> where T : A
{
    private T fld0;

    public D(T arg0)
    {
        fld0 = arg0;
    }

    public void Method<U>(U arg0) 
        where U : B
        where T : C<U>
    {
        fld0.Method(arg0); // In the scope of this method, we know fld0 implements C<B>
    }
}
```

### Extracting and rewriting the method

When emitting IL, emit the method as a nested static class with a static method, and 'rewrite' all calls to the method similar to how calls to extension methods are handled

This would seem pretty 'severe' as @HaloFour puts it, because at runtime, reflecting on the original class would produce drastically different results than expected from just reading the authored C# code. In contrast, extension methods are implemented in a way that does not alter the type; they only sugar up static method calls within procedural portions of the IL. 

For those reasons, this option is probably a :no_entry_sign: **no-go.** :no_entry_sign: 

### Adding an additional type parameter to the method

When emitting IL, emit the method with an additional type parameter that enforces the constraint while specifying that an argument to the additional type parameter must derive from the original type parameter. Then, in the method body, emit a `castclass` opcode in the event that a field or property of the original type parameter is used. Calls to the method would also need to be 'rewritten' in the IL to add the explicit type arguments.

This offers a runtime guarantee that the method cannot even be called without the appropriate type arguments, but like the 'extraction' method detailed above, alters what is received via the reflection APIs at runtime. 

For that reason, this option is likely a :no_entry_sign: **no-go.** :no_entry_sign: 

### Emitting a `castclass` opcode in the method body

When emitting IL for the method body, emit `castclass` anywhere a field or property of the constrained type is used. Leave the written types, type signatures, and method signatures as-is. The runtime will throw an `InvalidCastException` if some attempt is made (via reflection or IL generation) to call the method where the constraint would not be met. 

This offers a mere syntactic sugar for C# that provides a compile-time guarantee of type safety for certain scenarios without slicing and dicing any expectations of the reflection API. The only thing with this is that I'm not sure how it's going to play with other CLR languages that might reference a library that was written with this sugar. 

:warning: **Needs opinions from experts.** :warning:

**Comment by HaloFour** [comment]
I don't see how that makes sense.  The method isn't declaring the generic type parameter `T1`.  Generic type constraints must be applied where they are declared and that stipulates how they are enforced at runtime.  You expect to be able to create a `D<T1>` that does not fulfill that constraint?  How should the runtime handle such a possibility?

**Comment by tuespetre** [comment]
@HaloFour

> You expect to be able to create a `D<T>` that does not fulfill that constraint?

Yes, precisely, because `D<T>` does not care about `U` beyond the context of `Method<U>`. This allows `D<T>` and its derivatives to work with any `T` (which, in the provided example, must derive from `A`) while providing additional functionality through `Method<U>` as needed only when `T` is known to implement `C<U>`.

> Generic type constraints must be applied where they are declared and that stipulates how they are enforced at runtime. [...] How should the runtime handle such a possibility?

Thanks for causing me to think this out :smile_cat: 

The constraint could be handled as any other type constraint, provided that the C# compiler effectively transforms the instance method into a static method of a nested static class which enforces the constraints, as if the following C# code had been written:

```
interface A { }

interface B { }

interface C<T> where T : B
{
    void Method(T arg0);
}

class D<T> where T : A
{
    private T fld0;

    public D(T arg0)
    {
        fld0 = arg0;
    }

    public static class Constrained<V, W>
        where V : B
        where W : T, C<V>
    {
        public static void Method(D<W> inst, V arg0)
        {
            inst.fld0.Method(arg0);
        }
    }
}
```

Calls to the 'instance method' would then be compiled as if they were written like follows:

```
class E : A, C<F>
{
    public void Method(F arg0)
    {
    }
}

class F : B { }

class G : B { }

class Program
{
    static void Main()
    {
        var test = new D<E>(new E());
        D<E>.Constrained<F, E>.Method(test, new F()); // Compiler is happy
        D<E>.Constrained<G, E>.Method(test, new G()); // Compiler is angry
    }
}
```

This is similar to how extension methods work in the sense that the author is writing what appears to be a call to an instance method even though it is actually compiled to a call to a static method on another class. In this case, the static method and its class are themselves generated by the compiler so as to be able to maintain access to private members.

**Comment by HaloFour** [comment]
That seems to be a pretty severe transformation just to mimic the behavior.  What use cases are there to actually support a syntax like this?  How frequently does this come up that it's not sufficient to write said `static` method yourself?

**Comment by tuespetre** [comment]
@HaloFour I'm afraid I won't be able to single-handedly provide the justification you are seeking. I only have my own perspective to offer. Perhaps @JonSkeet would be willing to comment, [as it seems that he has at one point desired the same feature.](http://stackoverflow.com/a/1188368/1030925)

**Comment by tuespetre** [comment]
@HaloFour I'm afraid I won't be able to single-handedly provide the justification you are seeking. I only have my own perspective to offer. Perhaps @jskeet would be willing to comment, [as it seems that he has at one point desired the same feature.](http://stackoverflow.com/a/1188368/1030925)

**Comment by jskeet** [comment]
While it's very occasionally been something I've desired, I don't think it meets the usefulness bar for me, I'm afraid.

**Comment by tuespetre** [comment]
Thanks @jskeet!

**Comment by tuespetre** [comment]
@HaloFour 

Coming back to this... the use case I have seen for this in the few related StackOverflow questions and in my own experience is the ability to neatly express a DSL using generic types. For example, `Playlist<TArtist>.Add<TSong>()` should be able to impose a constraint `where TArtist : IPlays<TSong>`, and the resulting API should be as easy to use as `boardsOfCanadaPlaylist.Add<HappyCycling>()`.

But `Playlist<BoardsOfCanada>.Constrained<BoardsOfCanada,HappyCycling>.Add(boardsOfCanadaPlaylist)`? 

Or `boardsOfCanadaPlaylist.Add<BoardsOfCanadaPlaylist,HappyCycling>(boardsOfCanadaPlaylist)`? 

:no_entry_sign:  **No way,** :no_entry_sign:  especially not when the DSL involves more components and more calls than that.

For now, with my current project, I am giving up on the compile-time guarantees because I value the DSL and the resulting API more. It would be awesome if, some day, I could come back to it and give it compile-time guarantees just by adding a handful of type parameter constraints :beers:

**Comment by tuespetre** [comment]
Hmm, is there really a need to enforce it at runtime? I mean, the runtime can enforce it, definitely, but by means of an InvalidCastException, if C# just treats the constraint as a syntactic sugar that compiles down to a castclass opcode.

**Comment by HaloFour** [comment]
You can use an extension method to wrap the call to the nested type:

```cs
public static class Method<T, U>(this D<T> d, U arg0) where T : A, C<U> where U : B {
    D<T>.Constrained.Method(d, arg0);
}
```

There's no way that this is so common of a problem to warrant redesigning parts of the language, particularly around generics.

**Comment by tuespetre** [comment]
@HaloFour thanks -- that does seem to work, although it does not play well with intellisense because type parameter constraints do not participate in type inference. It also falls short of cases where the API would want to employ the use of generics without passing in an instance for an argument (like `autechrePlaylist.Add<Rotar>()`.)

> There's no way that this is so common of a problem to warrant redesigning parts of the language, particularly around generics.

Maybe it would be more common than anyone expected once the possibility is opened up. I don't know. There's no way to tell for sure.

For reference, here is a full, copy-pastable example with an extension method for anyone who is interested:

```
interface A { }

interface B { }

interface C<T> where T : B
{
    void Method(T arg0);
}

class D<T> where T : A
{
    private T fld0;

    public D(T arg0)
    {
        fld0 = arg0;
    }

    public static class Constrained<V, W>
        where V : T, C<W>
        where W : B
    {
        public static void Method(D<V> inst, W arg0)
        {
            inst.fld0.Method(arg0);
        }
    }
}

class E : A, C<F>
{
    public void Method(F arg0)
    {
    }
}

class F : B { }

class G : B { }

static class Extensions
{
    public static void Method<T, U>(this D<T> d, U arg0) 
        where T : A, C<U> 
        where U : B
    {
        D<T>.Constrained<T, U>.Method(d, arg0);
    }
}

class Program
{
    static void Main()
    {
        var test = new D<E>(new E());
            
        test.Method(new F()); // Compiler is happy, intellisense is broken
        test.Method(new G()); // Compiler is angry
    }
}
```

**Comment by tuespetre** [comment]
@HaloFour another possibility would be to just provide a code analyzer with any library that needs this type of checking. I have not had a chance to play with Roslyn analyzers yet but I assume they could contribute warnings or errors wherever appropriate. What are your thoughts on that?

**Comment by tuespetre** [comment]
Having investigated the ability to integrate Roslyn analysis with a library, I would agree with you @HaloFour that this change would not be worth the effort, especially since all of the possible implementations fall short of something perfect without altering MSIL itself to support such constraints.
