### ISSUE TITLE
Build should clear NuGet packages and http cache

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#11969]
Build in the stabilization branch should clear NuGet packages and http cache.
See `nuget.ext locals -clear`.

**Comment by tannergooding** [comment]
@cston  I would recommend, instead, to do:
```
$env:NUGET_PACKAGES = '<EnlistmentRoot>\packages'
nuget.exe -PackagesDirectory $env:NUGET_PACKAGES -NoCache <SolutionFile>
```

This will force packages to restore to a new directory and to explicitly not use any packages which have been cached locally.

Doing such will ensure that we are only getting packages directly from the network and will also prevent us from impacting other runs, which may be dependent on the packages that are already on the machine.

**Comment by tmat** [comment]
@tannergooding @ericstj suggested doing ```nuget.ext locals -clear``` to clear HTTP caches as well.

**Comment by tannergooding** [comment]
@tmat, `-NoCache` should prevent all three caches from being used and additionally ensures we don't impact the CoreFX/CoreCLR runs by wiping the caches they use.

**Comment by ericstj** [comment]
If NoCache works then that + a local packages folder (empty) as @tannergooding suggests should be fine.

My experience with NoCache was that it hurt perf quite a bit when restoring multiple projects.  Not sure if that's still the case.

**Comment by tannergooding** [comment]
I believe it will still hurt perf (although it shouldn't be any worse than a full restore on a clean machine), but I believe (for the instances where we need to do this) it will be better to extend the execution time for our single build than it would be to impact the builds for all teams that share the machine.

**Comment by jasonmalinowski** [comment]
We now do this on MicroBuild runs so we do have the validation.
