### ISSUE TITLE
How to display a filtered list of snippets ?

### ISSUE THREAD

**Issue by omefire** [dotnet/roslyn#11962]
Hi,
I need some help dealing with snippets.

When trying to display a list of snippets, I am currently using ```IVsExpansionManager.InvokeInsertionUI(...)```, just like it's done here: https://github.com/dotnet/roslyn/blob/56f605c41915317ccdb925f66974ee52282609e7/src/VisualStudio/CSharp/Impl/Snippets/SnippetCommandHandler.cs#L95

However, what if before displaying the list of code snippets, I want to do some filtering on the VsExpansion items that I want to display ? How would I go about doing that ?
Otherwise, is there a way to display a given list of VsExpansion items ?

**Comment by Pilchie** [comment]
Tagging @dpoeschl  (who won't be in the office for a while longer) and @olegtk who might know more about the IVs* side of snippets.

**Comment by olegtk** [comment]
There is no really a support for additional filtering beyond InvokeInsertionUI() arguments (type, kind, language, prefix). A common way to display snippets is to just add them to a completion list.
