### ISSUE TITLE
Failed variation of TestCSharp_LambdaParameter_DontExpandAnonymousTypes2

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#11979]
The following slight variation of an existing IDE test fails. This shows how this test is sensitive to a bug in the C# semantic model that we will be fixing soon (see #11901).

```vb
        <Fact, Trait(Traits.Feature, Traits.Features.Expansion)>
        Public Async Function TestCSharp_LambdaParameter_DontExpandAnonymousTypes2_variation() As Task
            Dim input =
<Workspace>
    <Project Language="C#" CommonReferences="true">
        <Document>
using System;
class C
{
    static void Mumble&lt;T&gt;(T anonymousType, Action&lt;T, int, int&gt; lambda) { }
    static void Mumble() { } // added to the test

    static void M()
    {
        Mumble(new { x = 42 }, {|Expand:(a, y) => a.x|});
    }
}
        </Document>
    </Project>
</Workspace>

            Dim expected =
<code>
using System;
class C
{
    static void Mumble&lt;T&gt;(T anonymousType, Action&lt;T, int, int&gt; lambda) { }
    static void Mumble() { } // added to the test

    static void M()
    {
        Mumble(new { x = 42 }, (a, y) => a.x);
    }
}
</code>

            Await TestAsync(input, expected, expandParameter:=True)
        End Function
```

**Comment by gafter** [comment]
The test below has the same problem:

```vb
        <Fact(Skip:="https://github.com/dotnet/roslyn/issues/11979"), Trait(Traits.Feature, Traits.Features.Expansion)>
        Public Async Function TestCSharp_LambdaParameter_DontExpandAnonymousTypes1() As Task
            Dim input =
<Workspace>
    <Project Language="C#" CommonReferences="true">
        <Document>
using System;
class C
{
    static void Mumble&lt;T&gt;(T anonymousType, Action&lt;T, int&gt; lambda) { }

    static void M()
    {
        Mumble(new { x = 42 }, {|Expand:a => a.x|});
    }
}
        </Document>
    </Project>
</Workspace>

            Dim expected =
<code>
using System;
class C
{
    static void Mumble&lt;T&gt;(T anonymousType, Action&lt;T, int&gt; lambda) { }

    static void M()
    {
        Mumble(new { x = 42 }, a => a.x);
    }
}
</code>

            Await TestAsync(input, expected, expandParameter:=True)
        End Function
```

**Comment by gafter** [comment]
Hi @Pilchie @DustinCampbell @dotnet/roslyn-ide 

This issue was uncovered in the context of #11981. Please confirm whether or not you are OK with the compiler bug fix PR #11981 for issue #11901 going in while this IDE bug remains in Roslyn, or whether you'd prefer this IDE issue be addressed first.

**Comment by CyrusNajmabadi** [comment]
I'm trying to understand.  What behavior do you see in the tests when you make your compiler change?

Looking at that test, it seems to be appropriately describing the behavior we want.  Namely that in that code sample ```(a, y) => a.x``` does not get expanded.

**Comment by gafter** [comment]
The test above fails today, with or without the compiler fix. It is a variation of an existing IDE test that passes for accidental reasons.

The test that is checked in behaved correctly before the compiler fix because the compiler reports that the lambda's argument is a type parameter. Which is not correct. With the fix the compiler reports that the lambda's argument is an anonymous type, and then the refactoring expands its declaration as type `object`, which isn't correct.

You can try the test in this bug report, above, for an approximation to what the existing test does with the compiler fix. This version of test just adds two unused methods to make it fail without the compiler fix.

**Comment by CyrusNajmabadi** [comment]
@DustinCampbell knows best about expand/simplify issues.  I'd like to get his thoughts on this issue.

**Comment by CyrusNajmabadi** [comment]
@gafter I've debugged through this and can provide some insight on what's going on here.  Please contact me when you get a chance :)

**Comment by CyrusNajmabadi** [comment]
In case you can't reach me, here's the important idea:

Our Expansion system has the following logic in it: If i have parenthesized lambda, i should expand out the type names of parameters if they're not provided.  However, i can only do that if none of the parameter types contain anonymous types.  The code for this is here:

https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Simplification/CSharpSimplificationService.Expander.cs

```c#
                        if (parameters.Length > 0 && parameters.Any(p => p.Type == null))
                        {
                            var parameterSymbols = node.ParameterList.Parameters
                                .Select(p => _semanticModel.GetDeclaredSymbol(p, _cancellationToken))
                                .ToArray();

                            if (parameterSymbols.All(p => p.Type?.ContainsAnonymousType() == false))
                            {
                                var newParameters = parameterList.Parameters;

                                for (int i = 0; i < parameterSymbols.Length; i++)
```

The issue in the code sample you provided is that the semantic model is reporting all the parameter types are "ErrorType".  Because of this, we don't think there are any anonymous types, and so we think it's ok to introduce types here (namely 'object').

Ideally, in the above code examples the semantic model would tell us that the parameter types of this lambda are:  'anonymous type', 'int'.

Given that we have an ```Action<T, int, int>``` and a lambda of only two parameters, this seems very reasonable for it to provide for me.

Thanks!

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/commit/7abdbb5391935046b984c917dc7d6e54540448b0
