### ISSUE TITLE
Weird time stamp of *.LanguageServices.*.dll in VS debugger's modules window

### ISSUE THREAD

**Issue by IlyaBiryukov** [dotnet/roslyn#12007]
**Version Used**: 
Roslyn - 2.00.0.60503

**Steps to Reproduce**:
1.  Start Visual Studio "15", create a new C# Console App project
2.  Start another instance of Visual Studio, attach its debugger to the first instance
3.  Check out the loaded modules list

**Expected Behavior**:
Time stamps of *LanuageService* assemblies make sense

**Actual Behavior**:
Time stamps of *LanguageServices* assemblies are somewhere in the future, like in 2100, 2050

**Comment by ManishJayaswal** [comment]
This is likely due to deterministic build. This will be very confusing to the user.

**Comment by gafter** [comment]
The loaded modules list in the debugger should stop showing timestamps (or show them differently) when the assembly is marked as having deterministic timestamps.

**Comment by gafter** [comment]
@ManishJayaswal Where can we redirect this to get the "loaded modules list" fixed in VS?

**Comment by ManishJayaswal** [comment]
That would be the debugger team. @plnelson - should we open an Internal bug for this and assign it to debugger team?

**Comment by plnelson** [comment]
Yes, open an internal bug for this.

**Comment by ManishJayaswal** [comment]
@gafter can you do this and close this issue?

**Comment by jaredpar** [comment]
@gafter have you opened an internal bug for this yet?

**Comment by gafter** [comment]
Moving to a bug report against the module list in Visual Studio. For Microsoft employees, you can see the bug at https://devdiv.visualstudio.com/DevDiv/_workitems?id=261802&_a=edit
