### ISSUE TITLE
[Test Failure] <description> in windows_vsi_p2_open_prtest on PR #12002

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#12018]
PR: [#12002](https://github.com/dotnet/roslyn/pull/12002) *porting #11972 from stabilization to master* by @heejaechang
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/137/

**Comment by Pilchie** [comment]
The log indicates the save didn't work as expected.

**Comment by jasonmalinowski** [comment]
The logs are gone. :-(
