### ISSUE TITLE
possible VB.NET compiler bug using Null-conditional operator

### ISSUE THREAD

**Issue by stax76** [dotnet/roslyn#12027]
aaa() getting called looks like a bug.

```
Module Module1
    Sub Main()
        Dim s As String
        If s?.Contains("") AndAlso aaa() Then Console.WriteLine("bbb")
        Console.ReadKey()
    End Sub

    Function aaa() As Boolean
        Console.WriteLine("aaa")
        Return True
    End Function
End Module
```

**Comment by HaloFour** [comment]
The reason is because the null-conditional operator isn't returning `False`, it's returning `Nothing`.  VB.NET does not treat `Nothing` as `False` when it comes to short-circuiting Boolean operations.

**Comment by HaloFour** [comment]
The following MSDN page contains a table of how `Nullable(Of Boolean)` operands are compared.  When comparing a `Nullable(Of Boolean)` to a `Boolean` the VB.NET compiler implicitly converts the `Boolean` to a `Nullable(Of Boolean)`:

Under Comparing Nullable Types:
[Nullable Value Types](https://msdn.microsoft.com/en-us/library/ms235245.aspx)

Also, from the note:

> `AndAlso` and `OrElse`, which use short-circuit evaluation, must evaluate their second operands when the first evaluates to `Nothing`.

**Comment by stax76** [comment]
> VB.NET does not treat Nothing as False when it comes to short-circuiting Boolean operations.

Why does it work like this? It appears absolutely wrong to me.

**Comment by AdamSpeight2008** [comment]
@stax76 Null doesn't equal default(of T).
Think `Nullable(of Boolean)` of having 3 state.  `Do Not Know` , `False` , `True`
Also If I remember correctly VB.net has a stricter definition for `Nullable<T>` than C#.

**Comment by HaloFour** [comment]
C# doesn't permit implicit conversion from `bool?` to `bool`.  The expression `(s?.Contains("") && aaa())` would fail to compile.  You'd need to use the null-coalescing operator `??` to provide a default value, e.g. `(s?.Contains("") ?? false && aaa())`.

The VB.NET behavior does make sense if you view it in the context of a tri-state or a SQL-like `NULL`.  The lack of a value is not the same as a negative or false value, so it tests the next expression.  I can definitely see how it could be confusing, but it's been the behavior for evaluating nullable-Boolean expressions for over a decade and it would not be possible to change it even if it could be argued that it should be.

**Comment by gafter** [comment]
Issue moved to [dotnet/vblang #69](https://github.com/dotnet/vblang/issues/69) via [**ZenHub**](https://www.zenhub.com/)
