### ISSUE TITLE
Source generators design: Where does the SourceGeneratorTrigger attribute live?

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#12020]
Reflecting current ideas about source generator design, let's assume there's an attribute that you apply to your types, `SourceGeneratorTriggerAttribute`, that indicates what types should be visited by source generators.

The problem is: where does that attribute live?

Let's say it lives in Roslyn. This means that the _source generator user_ must include a reference to Roslyn, and possibly ship Roslyn DLLs with their application just to use source generators at compile time. This seems very bad.

Let's say it lives in source -- every user of source generators must define this type themselves, in source, and simultaneously reference it. This doesn't seem great either.

So where does it get defined? Do we publish a separate NuGet package to include this and only this type? Better than all of Roslyn but this is still an additional dependency that produces versioning and shipping headaches for all source generator users.

**Comment by agocke** [comment]
@cston An issue to track what we were talking about earlier

/cc @jaredpar

**Comment by agocke** [comment]
Perhaps it's possible to add source files to the project using NuGet "source" dependencies? http://docs.nuget.org/Create/Nuspec-Reference#contentfiles-with-visual-studio-2015-update-1-and-later

I don't think this is supported in CSPROJ, though, so we would have to budget in time to make that work.

**Comment by axel-habermaier** [comment]
@agocke: If it's just an attribute, the assembly does not have to be shipped if you apply the ``Conditional`` attribute. That's how ``JetBrains.Annotations`` NuGet package works, for example. Would that help? As far as I understood, the attribute is irrelevant after compilation, right?

**Comment by agocke** [comment]
@axel-habermaier Yup, perf optimization. Let's say you want live code generation, such that every change you made to your source re-ran the generator when you needed it to.

If generators could run on any file at any time, producing any result, we would have to re-run the generator for basically every keystroke. Obviously not scalable.

I don't think requiring adding an attribute to your generated types is crazy, but I'm also considering whether or not it's too expensive to use semantic analysis to trigger the generation. This would let you apply the attribute to some interface or base type, then every type that implements/overrides those types would automatically trigger generation.

**Comment by agocke** [comment]
I'm not super excited about `ConditionalAttribute` either, because I don't think it should be different between debug and release modes. I've been thinking that a new attribute, `CompilationOnlyAttribute` maybe, would be better. Any attribute with this attribute on it will just be for compile time instrumentation and be stripped from the types during emit.

**Comment by axel-habermaier** [comment]
@agocke: I understand the performance considerations, I'm just not particularly thrilled about an additional attribute. Let's assume I have two code generators in my project, one for JSON serialization and one for XML serialization. In order to know which classes which code should be generated for, I use the ``JsonSerialization`` and ``XmlSerialization`` attributes. Now I would have to do the following:

```csharp
[SourceGeneratorTrigger, JsonSerialization] // generates JSON code
class A {}

[SourceGeneratorTrigger, JsonSerialization, XmlSerialization] // generates both JSON and XML code
class B {}

[JsonSerialization] // generates nothing?
class C {}
```

Would it at least be possible to mark my own code generation attributes with ``SourceGeneratorTriggerAttribute``, or derive them from ``SourceGeneratorTriggerAttribute``? That would avoid the inconsistencies and clutter in the example above. I realize that in your JSON serialization example repository, you're using an interface to mark the classes the code should be generated for. But that just shifts the problem around, you're still specifying the same thing twice (namely: generate code serialization code for this (``JsonSerialization`` or you interface), and, yes, really, please generate code (``SourceGeneratorTrigger``)).

**Comment by axel-habermaier** [comment]
@agocke: No, there would be no difference between release and debug modes with ``ConditionalAttribute``.

> Any attribute with this attribute on it will just be for compile time instrumentation and be stripped from the types during emit.

That's exaclty what ``ConditionalAttribute`` does. Just declare ``SourceGeneratorTriggerAttribute`` as follows:

```csharp
[Conditional("ROSLYN_CODE_GENERATION")]
[AttributeUsage(/* whatever */)]
public class SourceGeneratorTriggerAttribute : Attribute
{
	// ...
}
```
Let's say this attribute lives in assembly A.dll and you're referencing it in B.dll. Unless project B defines the ``ROSLYN_CODE_GENERATION`` symbol (and there is no reason for it to do so), all usages of ``SourceGeneratorTriggerAttribute`` will be stripped out from B.dll during compilation, which in turn means that B.dll won't reference A.dll once compiled.

Note, however, that NuGet by default adds references with ``CopyLocal = true``, so the output would still contain A.dll. But it can be removed without affecting B.dll, hence it must not be shipped or versioned.

Again, that's what JetBrains does with ``JetBrains.Annotations``; they use a different symbol for ``ConditionalAttribute`` obviously.

**Comment by alrz** [comment]
Can we use a custom attribute? because it is probably always the case to mark our target classes with an attribute.

```cs
[CodeGenerator(typeof(MyAttribute), ... )] // among other things like Language
class Generator : SourceGenerator { .. }

[MyAttribute]
class TargetClass { .. }
```
Or something like that?

**Comment by agocke** [comment]
@axel-habermaier 

>Would it at least be possible to mark my own code generation attributes with SourceGeneratorTriggerAttribute, or derive them from SourceGeneratorTriggerAttribute?

That's what I was talking about when I said: 

> This would let you apply the attribute to some interface or base type, then every type that implements/overrides those types would automatically trigger generation.

You would just apply the `SourceGeneratorTrigger` attribute to your interface or your own attribute, then the attribute would be inherited through to the parent type through the iface or attr. The problem with this is that the compiler has to go through binding to figure out all of the base types and inherited attributes. This is much more expensive than just syntax, but it's possibly worth it. I'm looking into it.

>That's exaclty what ConditionalAttribute does. Just declare SourceGeneratorTriggerAttribute as follows:

You can call your modes whatever you want, but fundamentally you have different generator behavior when the symbol is defined to when it is not. If the intention is that you're *never* defining the symbol, then you're just hacking up the `ConditionalAttribute` for a new purpose. It's not even a `ConditionalAttribute` anymore, you might as well call it `NotConditionalAttribute`. If I'm going down that road, I want to use a new attribute that has exactly the semantics everyone expects.

**Comment by gafter** [comment]
This is a compiler question, not a language design question.
