### ISSUE TITLE
[Suggestion]  Improvements for Code fix action "Implement interface through 'member'"

### ISSUE THREAD

**Issue by dfkeenan** [dotnet/roslyn#12023]
Hi,

The code fix "Implement interface through 'member'" is a pretty cool. But it currently does not wrap events i.e.

``` C#
public event EventHandler<SomeEventAgs> SomeEvent
{
    add
    {
        inner.SomeEvent += value;
    }
    remove
    {
        inner.SomeEvent -= value;
    }
}
```

I think there should also be a code fix suggestion for "Implement interface explicitly through 'member'". And possibly implementing members as expression body members where applicable.  Though expression body members might also be better off as optional.

**Comment by aluanhaddad** [comment]
I like this idea. I think expression bodied members should be chosen for simple delegation like that. It reads super intuitively.
```C#
public int Length => inner.Length;
```

**Comment by keyboardDrummer** [comment]
Should this also work for VB.NET? I'm not a VB programmer but it seems delegating an event is a bit more clumsy. The best I got was the following:

```vb
Public Interface IFoo
    Event Foo()
End Interface

Class Slave
    Implements IFoo
    Public Event Foo() Implements IFoo.Foo
End Class

Class Master
    Implements IFoo

    Dim slave As Slave

    Private Custom Event Foo As IFoo.FooEventHandler Implements IFoo.Foo
        AddHandler(Value As IFoo.FooEventHandler)
            AddHandler slave.Foo, Value
        End AddHandler

        RemoveHandler(Value As IFoo.FooEventHandler)
            RemoveHandler slave.Foo, Value
        End RemoveHandler

        RaiseEvent()
            Throw New NotSupportedException("Event that is delegated can not be raised.")
        End RaiseEvent
    End Event
End Class
```

It would be nice if we could leave out the RaiseEvent part but VB enforces it.

**Comment by aluanhaddad** [comment]
@keyboardDrummer that seems like a language feature proposal. Concise event delegation Syntax for VB.

**Comment by keyboardDrummer** [comment]
@aluanhadded Well actually the only thing I'd like is if the RaiseEvent part was optional. If you don't implement it then calling RaiseEvent <customEvent> throws a compile error.

**Comment by CyrusNajmabadi** [comment]
This works now:

![image](https://user-images.githubusercontent.com/4564579/75645249-fd20f000-5bf9-11ea-9d80-afe164f6a92a.png)

Fixed with https://github.com/dotnet/roslyn/pull/14240
