### ISSUE TITLE
IOperation API does not expose BoundMethodGroup and BoundPropertyGroup specific to C#

### ISSUE THREAD

**Issue by Mylan719** [dotnet/roslyn#12036]
Hi,
I was trying to implement some walkers on C# `IOperation` trees.
I had statement something like:

``` csharp
var x = field.Property.Func#carret#tion("param")
```

`Function` has multiple overides. Now I asked for syntax node coresponding to carret position in text on 'Function' I get `IdentifierNameSyntax` because Syntax tree path for right side expression is something like:

```
methodCall>memberAccess>memberAccess>identifier
```

When I ask semantic model for `IOperation` for `IdentifierNameSyntax` node "Function"  I get instance of internal class `BoundMethodGroup`. Same thing when I ask for `IOperation` of the MemberAccessSyntax node that is directly before in the hierarchy. 
1) I would expect to get `IMethodReference`
2) BoundMethodGroupI am getting has no interface expect `IOperation` so I cannot work with it.

Is it because `IMethodReference` does not cound for overloads/methodGroups?

If I drop the invocation like this:

``` csharp
var x = field.Property.Func#carret#tion
```

I am still getting `BoundMethodGroup` which in this case is expected, but still, I cannot work with this, since there is no intrface.

**Comment by isanych** [comment]
I'm also looking into switching statement/expressions parsing to operations, but also see that not all BoundExpressions have public interfaces, some only implements IOperation with Kind None, so I can see classes with values in debug, but don't have a way to use them in code. Are there plans to fully support operations?

**Comment by jinujoseph** [comment]
dupe of https://github.com/dotnet/roslyn/issues/19965
