### ISSUE TITLE
BuildVersion will break in 2017

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#12038]
The current method of computing the last portion of our BuildVersion (major.minor.build.**revision**) will cause the build to start failing starting Jan 1st, 2017. This is because `[AssemblyFileVersion()]` only allows each version part to be in the range of `0` through `65535`.

Our current computing of the **revision** portion is done by taking the MicroBuild BuildNumber and taking the last five digits from the first part. So, the first build on June 15th, 2016 will give a BuildNumber of `20160615.1`, and from that our FileVersion will be `2.0.0.60615`. Starting 2017, we will end up producing a FileVersion of `2.0.0.70101`, which is outside the allowable range and will cause CS7035.

**Comment by tannergooding** [comment]
FYI. @jasonmalinowski, @dotnet/roslyn-infrastructure

**Comment by ManishJayaswal** [comment]
Should we be doing last 5 digits mod 65535?

**Comment by tannergooding** [comment]
@ManishJayaswal, that does give us unique/valid values for every build within a 10 year range (which is likely far greater than any major/minor revision).

However, it additionally starts giving us bad results if we don't upgrade the major/minor/build portion between years ending in 6 and 7. This is because Dec 31, xxx6 will give us 61231, where-as Jan 1, xxx7 will give 4566, which would mean (by normal version comparison) that the build with the greater version number is that from Dec 31, xxx6.
