### ISSUE TITLE
Editor Context Menu Cleanup: Remove Organize Usings

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#12031]
As part of our goal to improve developer productivity, let's condense the editor context menu. Let's remove the "Organize Usings" drop-down and replace it with the single top-level command "Remove and Sort Usings" (according to telemetry, it is the most used "Organize Usings" command by far).

**Comment by kuhlenh** [comment]
@Pilchie we're shooting for 2.0 (preview 4)

**Comment by 0xd4d** [comment]
Isn't it better to turn it into a quick action so it can fix every file in the project / solution? It seems as if it can only sort and remove unnecessary usings in the current document. I think many people would like to fix the whole project / solution.

**Comment by MgSam** [comment]
Agree with @0xd4d. Remove it from the context menu altogether. No reason it should be blessed above other quick actions and reside in the context menu.

**Comment by KirillOsenkov** [comment]
While you're here, can you please make sure it has a keyboard shortcut? If you remove it from the menu completely, how do I invoke it quickly?

**Comment by 0xd4d** [comment]
@KirillOsenkov Tools -> Options -> Keyboard and search for `Edit.RemoveAndSort`

**Comment by KirillOsenkov** [comment]
@0xd4d we need a shortcut that's by default the same for everybody.

**Comment by kuhlenh** [comment]
@KirillOsenkov what about making it part of #8928's functionality rather than give it a specific keyboard shortcut? Thoughts?

**Comment by KirillOsenkov** [comment]
@kuhlenh yeah, that'll work.

**Comment by Pilchie** [comment]
I still think we should have a keyboard shortcut for the current file.
