### ISSUE TITLE
Feature Request: Emit PDBs when executing Scripts

### ISSUE THREAD

**Issue by aelij** [dotnet/roslyn#12046]
Currently, if you run a script (e.g. running a .csx file using `csi`) and it throws, there's no way of knowing which line caused the exception, since the `ScriptBuilder` class doesn't emit a PDB for the executed assembly.

I propose adding a property to `ScriptOptions` that would determine whether to generate and load the PDB.

(I'm willing to contribute the code, should be simple enough to implement.)

**Comment by filipw** [comment]
This can also be closed following  https://github.com/dotnet/roslyn/issues/16489

**Comment by perjahn** [comment]
Probably a typo, must have meant VS17. But anyway, I assume this will be included in the future somehow? Maybe by #16489?

**Comment by aelij** [comment]
@perjahn I think it will be included in VS 2017.

**Comment by filipw** [comment]
As a public Roslyn API it missed the VS 2017 cut for 2.0.0 and will come in next release (2.1.0).
For `csi.exe` specifically there is an open PR here https://github.com/dotnet/roslyn/pull/17379
