### ISSUE TITLE
Analyzer dependencies should not be shown in the Solution Explorer

### ISSUE THREAD

**Issue by duncanpMS** [dotnet/roslyn#12047]
**Version Used**: VS2015

**Steps to Reproduce**:
1. Create a project and add a NuGet analyzer package that has an analyser assembly and additional dependency assemblies e.g. _SonarLint_
2. Expand at the _Analyzers_ node in the _Solution Explorer_

**Expected Behavior**:
Only assemblies containing analyzers are listed under the _Analyzers_ node

**Actual Behavior**:
All analyzer dependencies are shown (and if the same assembly is required by multiple NuGet packages then it will appear multiple times).

_SonarLint_ only has one extra assembly so it doesn't cause much of a problem. However, other analyzers have more and the situation gets worse the more analyzer packages you add. The additional assemblies don't provide any using information: they just add clutter, making it harder to drill down into the "real" analyzer assemblies to see the diagnostics.

**Comment by mavasani** [comment]
We now display only analyzer assemblies with non-zero diagnostic analyzers and assemblies with analyzer load failures.
