### ISSUE TITLE
Proposal Generic cast operator

### ISSUE THREAD

**Issue by NN---** [dotnet/roslyn#12043]
I would like to have this code to be allowed.

``` cs
class A
{
  public static implicit operator<T> A<T>(T t) { return new A(); }
}

A a;
a = 1;
```

It is possible to do it in other languages such as [Nemerle](http://nemerle.org)

``` nemerle
class A
{
 public static @:[T](t : T) : A { A() } // "@:" in C# is implicit operator
} 

class Program
{
 public static Main() : void 
 {
  mutable a : A; // C#: A a;
  a = 1; 
 }
}
```

**Comment by benaadams** [comment]
Wouldn't that need to be:
```csharp
class A<T>
{
  public static implicit operator A<T>(T t) { return new A<T>(); }
}
```

**Comment by dsaf** [comment]
@benaadams it's easier to see the difference with methods:

```csharp
public IEnumerable Test<T>()
{
    return new object[] {};
}

public IEnumerable<T> Test<T>()
{
    return Enumerable.Empty<T>();
}
```

**Comment by HaloFour** [comment]
The problem is that the syntax that you've described is already legal for a conversion operator.  As the generic type parameter is embedded in the type name which is reused as the operator method name syntactically you'd need another place to stick the generic type parameter in said operators.

**Comment by NN---** [comment]
@HaloFour Correct, didn't think about it.
It should be then something like:

```
public static implicit operator<T> A<T>(T t) { return new A(); }
```

**Comment by HaloFour** [comment]
@NN--- 

Or for your example:

```cs
public static implicit operator<T> A(T t) { return new A(); }
```

Which is weird looking but there probably isn't a better candidate for locating a potential place to insert another generic type parameter.

I wonder how truly generic conversion operators would work given the limitations imposed on conversion operators to not allow conversions between base and derived types.  Although I guess the compiler allows some of those shenanigans today with conversion operators on generic classes.

**Comment by alrz** [comment]
Using #11159,
```cs
extension class Extensions<T> : A {
  public static explicit operator A(T t) => new A();
}
```
Not sure about implicit conversions though.

**Comment by NN---** [comment]
@HaloFour This what happens if your syntax requires types before names;)

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #534](https://github.com/dotnet/csharplang/issues/534) via [**ZenHub**](https://www.zenhub.com/)
