### ISSUE TITLE
Bottom status bar doesn't refresh after checking for quick action from a spot with none.

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#12050]
**Version Used**: 
D14Rel 25415.00
**Steps to Reproduce**:
1. Create new C# Console App
2. Inside the main method, type string s = "foo";
3. Place the cursor inside foo, and choose 'Quick Actions and Refactorings...' from the context menu
4. The status bar at the bottom of VS says 'No quick actions available here' (Expected)
5. Select the entire line of string s = "foo"
6. Run Quick actions and Refactorings again. Choose Extract Method

**Expected Behavior**:
The bottom status bar should return to Ready.
**Actual Behavior**:
Bar still says no Quick Actions available even though, you are in the middle of the prompt. Doesn't appear to update at any point after step 3. 
![image](https://cloud.githubusercontent.com/assets/10537189/16127865/1c93840c-33b3-11e6-9e40-b288e3f936a7.png)

This isn't a regression from Update 2. Same behavior is there as well.

**Comment by Pilchie** [comment]
The normal design for the status bar is that a message stays there until some other action puts a new message there.
