### ISSUE TITLE
[Test Failure] <description> in windows_eta_open_prtest on PR #12056

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#12069]
PR: [#12056](https://github.com/dotnet/roslyn/pull/12056) *Improve parsing recovery for local functions* by @agocke
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/614/

**Comment by Pilchie** [comment]
Dupe of #12065
