### ISSUE TITLE
[Test Failure] MSBuild Error in windows_eta_open_prtest on PR #12059

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#12065]
PR: [#12059](https://github.com/dotnet/roslyn/pull/12059) *loose up a bit on what happens when build error report on us errors o…* by @heejaechang
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/617/

**Issue 1: MSBuild Error**
error MSB4057: The target "Build" does not exist in the project.

something related to Jenkins?

**Comment by Pilchie** [comment]
@brettfo You fixed this, right?

**Comment by brettfo** [comment]
Correct, this has been fixed by reverting an internal change.
