### ISSUE TITLE
Proposal: Initializer for returned objects

### ISSUE THREAD

**Issue by Haukinger** [dotnet/roslyn#12071]
It would be nice if one could use the initializer syntax to set properties not only on newly created instances created by the new operator, but also for objects created by a factory:

```
// existing
var createdByNew = new MyObject() { MyProperty = something };

// desired...
var createdByFactory = myFactory.CreateMyObject() { MyProperty = something };

// ...as shorthand for
var createdByFactory = myFactory.CreateMyObject() { MyProperty = something };
createdByFactory.MyProperty = something;

// and even shorter (like new)
var createdByFactory = myFactory.CreateMyObject { MyProperty = something };
```

**Comment by svick** [comment]
Related: #133

**Comment by aluanhaddad** [comment]
@svick I believe it's actually a duplicate except this proposal does not use `with` or any keyword.

**Comment by gafter** [comment]
Moved to https://github.com/dotnet/csharplang/issues/803
