### ISSUE TITLE
Add compiler version number to VS gui

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#12105]
![vscsharpversion](https://cloud.githubusercontent.com/assets/573215/16205045/a6ce0216-36d6-11e6-8b59-33b4251a1aae.png)

**Comment by jaredpar** [comment]
Note that we need to do this for both C# and VB.

**Comment by jasonmalinowski** [comment]
FYI to @davkean and @Pilchie too, since this might (sadly) be some work we have to do in the legacy project system as well, either because we want this for non-CPS project types, or just because of schedule sequencing.

**Comment by TyOverby** [comment]
Partially fixed by https://github.com/dotnet/roslyn-project-system/pull/749

**Comment by TyOverby** [comment]
I forgot to close this back when I was able to do testing on the change.
