### ISSUE TITLE
Project.WithProjectReferences and friends allows you to give duplicate references

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#12101]
We guard against duplicate references being created in Project.AddProjectReferences and similar APIs, but no similar guarding is done if you call WithProjectReferences. It seems the checks should be added there instead.

**Comment by KirillOsenkov** [comment]
There are incorrectly authored projects out there with duplicate project references. SourceBrowser is "finding" them in droves (by hitting the key already exists exception in CompilationTracker).

What's the best way to fix it to not break existing incorrectly authored projects? Dedup the references in WithProjectReferences/AddProjectReferences?

I've already filed a project system suggestion to issue a warning on duplicate references:
https://github.com/dotnet/roslyn-project-system/issues/311

**Comment by jasonmalinowski** [comment]
I would say AddProjectReferences/WithProjectReferences should throw (since it's bad data), and MSBuildWorkspace can do the dedup there.

**Comment by KirillOsenkov** [comment]
If it helps, this is what I wrote to work around the crash (and it seems to have helped):

```
        private Solution DeduplicateProjectReferences(Solution solution)
        {
            foreach (var projectId in solution.ProjectIds.ToArray())
            {
                var project = solution.GetProject(projectId);

                var distinctProjectReferences = project.AllProjectReferences.Distinct().ToArray();
                if (distinctProjectReferences.Length < project.AllProjectReferences.Count)
                {
                    var newProject = project.WithProjectReferences(distinctProjectReferences);
                    solution = newProject.Solution;
                }
            }

            return solution;
        }
```

@mattwar maybe Matt can look into fixing MSBuildWorkspace? I'd send a PR myself but I'm on vacation. Also it probably needs a test.

**Comment by mattwar** [comment]
Alas @KirillOsenkov I am also on vacation.

**Comment by brunotag** [comment]
@KirillOsenkov thanks for the workaround, I was getting this same "task was canceled" error mentioned here https://github.com/dotnet/roslyn/issues/12872.
So I turned on first chance exceptions and caught a System.ArgumentException in mscorlib.dll!System.Collections.Generic.Dictionary<Microsoft.CodeAnalysis.MetadataReference, Microsoft.CodeAnalysis.ProjectId>.Insert(...) and ended up here.
So, 12872 can be due to duplicate references, @pieroci

**Comment by Pilchie** [comment]
Interesting - tagging @CyrusNajmabadi too.

**Comment by jasonmalinowski** [comment]
Pulling this back in as we've realized it does actually cause problems.
