### ISSUE TITLE
Calculating diagnostics for a single file realizes all symbols in GetEntryPoint

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#12113]
Calculating the diagnostics even for a single file in a project producing an exe still realizes all of the symbols for the compilation.

In [`MethodCompiler.CompileMethodBodies`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Compiler/MethodCompiler.cs,179), we call `GetEntryPoint` regardless of the value of `filterOpt`.  This is causing performance and memory use for at least one customer who has ~4,000 source files in their main exe.

We should investigate to see if we can skip calling `GetEntryPoint` in the case where we are filtering to a single file.  If we can't, maybe we can use the declaration table to only realize methods called `Main` instead of all symbols in the compilation?

**Comment by gafter** [comment]
@Pilchie @jaredpar @MattGertz Please let me know if you'd like the (very simple) fix ported to a stabilization branch.

**Comment by MattGertz** [comment]
Yes -- we are going to port this to the next microupdate (not the current one). @jasonmalinowski is there a separate one for mu 3.2, or do we need to wait until the current mu cleans out?

**Comment by jasonmalinowski** [comment]
@MattGertz we don't have a place, but if we think we're going to have many of these I'm happy to have a branch spun up so people have a place to accumulate them, rather than us having to track them all down later.

**Comment by MattGertz** [comment]
OK, let's do that -- thanks.  The PR for this one and for #12126 will likely be part of that for starters.

**Comment by jasonmalinowski** [comment]
@jaredpar, @MattGertz: I am pleased to present our newest branch, the cleverly named `microupdate-3.2`.

**Comment by MattGertz** [comment]
Excellent, thanks @jasonmalinowski!  @gafter and @heejaechang, please create PRs against microupdate-3.2 if/when ready for approval.
