### ISSUE TITLE
Proposal: Passing a method to a delegate without specifying the name

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#12114]
It's too common to have interfaces with a single method, sometimes it make _sense_ like IDisposable but sometimes I see code like this:
```
public interface IReader<out T>
{
	T Read();
}
```
_And just for illustration, here is the implementer:_
```
public class FileReader1 : IReader<Stream>
{
	public Stream Read()
	{
		return default(Stream);
	}
}
```
And say we have the following consumer:
```
public class FileWriter1
{
	public FileWriter1(IReader<Stream> reader)
	{
	}

	public void Write()
	{
	}
}
```
And finally some client that uses it like this:
```
public class FileFactory1
{
	public void CreateFile()
	{
		new FileWriter1(new FileReader1()).Write();
	}
}
```
Now, the same thing can also be written like this, that to me makes a lot more sense:
```
public delegate T Reader<out T>();

public class FileReader2
{
	public Stream Read()
	{
		return default(Stream);
	}
}

public class FileWriter2
{
	public FileWriter2(Reader<Stream> reader)
	{
	}

	public void Write()
	{
	}
}

public class FileFactory2
{
	public void CreateFile()
	{
		new FileWriter2(new FileReader2().Read).Write();
	}
}
```
The only issue I have with it is the requirement to specify the method name, I understand the reason for it but it could have been really nice if we didn't have to do it, like this:
```
new FileWriter2(new FileReader2()).Write();
```
I mean, a delegate declaration is very similar to an interface with a single method from the perspective of the reader, now, having a method that takes multiple parameters as delegates can get quite verbose when fulfilling them whereas the interface version reads much better.

So I guess what I'm after is if there's a single method in the class that satisfies the contract then the compiler should pick it and emit what I otherwise had to write by hand.

**Comment by HaloFour** [comment]
I can't imagine that this is a situation that comes up so often as to warrant a language change that would impact the readability of the code.  The end-result appears that the consumer is accepting an instance of the class, not some selected member that happens to be wrapped in a delegate.  With any IDE you're talking two extra keystrokes, a small price to pay for improved readability.

**Comment by eyalsk** [comment]
@HaloFour It's not only about readability though or keystrokes it's completely redundant! it is common in the command pattern and obviously  in CQRS to have a single method per class and people usually use interfaces for it.

Sure It isn't common because again people use interfaces with a single method instead of delegates where in fact they should be using delegates instead but having to specify the method name isn't really _desired_.

It's not like this takes something from the language it's an addition to it, if you think you need to specify the method's name, it's still there but allowing this where it makes sense can help in term of readability and people wouldn't need to create interfaces and implement them just for a single method!

Can you clarify a bit what exactly do you mean by a language change?

**Comment by HaloFour** [comment]
@eyalsk 

Using either interfaces or delegates are both fine.  This proposal only matters if you're trying to forcibly use both.  I'd suggest that one's codebase would be cleaner and more consistent by simply sticking with a single paradigm and not trying to blend the two and expect the language to clean up after them.  It's an exceptionally narrow use case just to avoid, *at worst*, a few additional keystrokes.

It's a language change in that the compiler for the language would now have to take into account a new set of possible overload rules.  The syntax that you've describes is all currently legal syntax, potentially already successfully compiling due to overload resolution or defined implicit cast operators.

**Comment by eyalsk** [comment]
@HaloFour fair enough, thank you! :)
