### ISSUE TITLE
Remove consumption of VS binaries from SDK / installed build

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#12117]
Currently, we consume many, but not all, of our Visual Studio dependencies from the VS SDK NuGet packages. Some of these are pure accidents, some of these are because of lack of proper NuGet packages for the things we consume. We need to identify what these dependencies are, and then remove them.

**Comment by jasonmalinowski** [comment]
@mavasani This is the task you've already finished for Open.

**Comment by mavasani** [comment]
This is complete.
