### ISSUE TITLE
Create tool to unretain drops that aren't used by internal builds

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#12116]
Every time we insert a drop, we mark that drop as retained so it doesn't get expired by newer builds. However, we shouldn't keep all of those builds forever, since many of them will get "overwritten" by a newer insertion the next day; the only ones we need to keep around are ones that are being used by any active VS builds from that drop share.

We had a tool (CleanUpDrops.fsx) that would do this, but it's not been updated since the move to Git and thus is no longer useful.

**Comment by jasonmalinowski** [comment]
I guess the right way to do this now is just to unretain the build, and let VSTS expire it from there.

**Comment by brettfo** [comment]
Fixed by dotnet/roslyn-internal#1589.

It's running on an internal machine as a scheduled task, not as an Azure job, but there's a bigger work item to migrate all such tools to an Azure job.

**Comment by jasonmalinowski** [comment]
@brettfo We should move this to Azure now instead of creating more debt.

**Comment by jasonmalinowski** [comment]
Reactivating while we get this documented.

**Comment by brettfo** [comment]
Added documentation to our internal OneNote for what the tool does, how to build and test locally, how to update the scheduled job, and how to view the logs.

**Comment by jasonmalinowski** [comment]
Going to reactivate this as it seems the tool isn't working properly.
