### ISSUE TITLE
Xamarin downloading .zip files on Compiling

### ISSUE THREAD

**Issue by reader-man** [dotnet/roslyn#12128]
**Version Used**: 
Visual Studio 2015 update 2 cumulative update: vs14-kb3151378.exe

**Steps to Reproduce**:
When Opening a new Xamarin.Forms solution, and compiling it for the first time on a fresh VS 2015 installation, it will go and fetch some .zip files from the net, and that will take a long time, depending on the internet connection speed.
And Visual Studio, will look like it has hanged while compiling the solution.

**Expected Behavior**:
So, it should first Show a dialog describing what is happening in the background, and maybe some progress indication of how much downloaded, and what is left.

Plus, maybe there should be another way to download these files, and put them in the correct place, like having a setup.exe file, that can be downloaded once, and it will install the needed files, to any fresh VS 2015 installation.

**Actual Behavior**:
it will go and fetch some .zip files from the net, and that will take a long time, depending on the internet connection speed.

**Environ**:
OS: Win 10
IDE: Visual Studio 2015 update 2 cumulative update: vs14-kb3151378.exe
Xamarin: installed 4.1.0.530
Solution using Xamarin.Forms nuget 2.3.0.49
HDD: Samsung SSD 850 Pro 256GB
CPU: i7-2600 3.4GHz
RAM: 16GB
OS: win 10

this was also written here:
https://bugzilla.xamarin.com/show_bug.cgi?id=42020

as i don't know if this should be reported to Xamarin or Microsoft.

**Comment by Pilchie** [comment]
Xamarin is the right place to report this issue.
