### ISSUE TITLE
Change Signature refactoring allows to delete parameter targeted by an Out Variable Declaration, resulting in an invalid code

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#12124]
The refactoring is offered at the call-site 

Before:

```
        static void Main(string[] args)
        {
            if (M1(out var x2))
            {
                System.Console.WriteLine(x2);
            }
        }
```

After (x2 is no longer declared):

```
        static void Main(string[] args)
        {
            if (M1())
            {
                System.Console.WriteLine(x2);
            }
        }
```

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-ide Could you advise what do you think would be the desired behavior for this scenario?

**Comment by jasonmalinowski** [comment]
I'd consider that behavior to be by design here. Even if it wasn't the variable declaration, removing the out assignment could mean the variable is no longer definitely assigned, and break it regardless.

**Comment by AlekseyTs** [comment]
Thanks! Resolving "By Design" then, please "shout" if you disagree.

**Comment by CyrusNajmabadi** [comment]
agree with @jasonmalinowski 

This is acceptable behavior.  'remove parameter' has always been something that could break code.  It's more to help you update vast swaths of code.
