### ISSUE TITLE
[Test Failure] No identified problem in windows_debug_unit64_prtest on PR #12110#issuecomment-227490762

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#12135]
PR: [#12110#issuecomment-227490762](https://github.com/dotnet/roslyn/pull/12110#issuecomment-227490762) _Properly implement type inference for C# member access expressions._ by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/697/

**1 Test Failures:**
Microsoft.CodeAnalysis.CompilerServer.UnitTests.DesktopBuildClientTests+ServerTests.ConnectToPipeWithSpinWait

**Issue 1: No identified problem**
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.

**Comment by rchande** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/11819 ?

**Comment by TyOverby** [comment]
I just hit this one too:
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/805/console

**Comment by TyOverby** [comment]
Actually, I might be hitting @jaredpar's test cache

**Comment by jaredpar** [comment]
Nope.  That failure is live:

``` 
Roslyn.Compilers.CompilerServer.UnitTests.dll                               FAILED 00:02:06.4338420
```

Would have a `*` next to it if it was a cache hit.

**Comment by TyOverby** [comment]
dang

**Comment by jasonmalinowski** [comment]
@jaredpar I think this was fixed long ago?

**Comment by jaredpar** [comment]
This was fixed long ago.
