### ISSUE TITLE
Specific method is not supported exception on Workspace.TryApplyChanges(newSolution) call.

### ISSUE THREAD

**Issue by happyhebaby** [dotnet/roslyn#12136]
Roslyn version is 1.2.2 on vs2015

I tried to add a custom dll reference to every project of a solution by the following code, it throws exception even if I comment out MyFun call, which does some code modification and save back to same source file.

Anyone could tell me what's the issue?

           Solution solution = workspace.OpenSolutionAsync(solutionPath).Result;
           Solution newSolution = solution;
           string dllName = @"C:\work\NewCodeCoverage\CodeCoverageConfig\bin\Debug\CodeCoverageConfig.dll";
           Project project;
           foreach (ProjectId projectId in solution.ProjectIds)
           {
                project = newSolution.GetProject(projectId);
                project = project.AddMetadataReference(MetadataReference.CreateFromFile(dllName));
                foreach (Document document in project.Documents)
                {
                    {

                       // Same exception will throw no matter the following call is enabled or not
                       // This function makes changes to source file and save it back

                       //MyFun(document.FilePath);
                    }
                    newSolution = document.Project.Solution;
                }
            }

            bool changeApplied = workspace.TryApplyChanges(newSolution);

I expect the above code will work and each project is updated with the added reference to CodeCoverageConfig.dll.

**Comment by jmarolf** [comment]
What is the exception?

**Comment by happyhebaby** [comment]
System.NotSupportedException.
HResult:-2146233067
Callstack:
   at Microsoft.CodeAnalysis.Workspace.AddMetadataReference(ProjectId projectId, MetadataReference metadataReference)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.TryApplyChanges(Solution newSolution)
   at Docusign.CodeCoverage.CodeCoverageRun.RunCodeCoverage(String solutionPath) in C:\work\NewCodeCoverage\CodeCoverageRun\Program.cs:line 176
   at Docusign.CodeCoverage.CodeCoverageRun.Main(String[] args) in C:\work\NewCodeCoverage\CodeCoverageRun\Program.cs:line 279
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by happyhebaby** [comment]
Hi Jonathon, just wonder if you could confirm if this is a bug? If so roughly how soon a fix could be provided? One important project of our team heavily relies on this working.
Thanks a lot!

**Comment by Pilchie** [comment]
Tag @mattwar - in general however, MSBuildWorkspace has no ability to persist changes to the solution.  It's non-trivial to figure out what the correct `<Reference>` element to add to the csproj is.

**Comment by mattwar** [comment]
MSBuildWorkspace does in fact let you add metadata references.  This is not a modification to the solution file, it is a modification to the csproj file.

Not sure how that stack trace occurs though. Workspace.ApplyProjectChanges does not call Workspace.AddMetadataReference. It calls Workspace.ApplyMetadataReferenceAdded.  This call stack must be from a pre 1.0 Roslyn.

**Comment by happyhebaby** [comment]
@Pilchie @mattwar, I can see quite some example code on web using the same code pattern, include the source of roslyn itself, such as the following:
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/InlineRename/InlineRenameSession.cs,656

**Comment by mattwar** [comment]
@happyhebaby the coding pattern is not the problem.  The TryApplyChanges call at the end is throwing the exception due to the addition of the metadata references. This was not a supported feature in pre-release versions of Roslyn.  If you are actually using a released version then is should work fine. If you notice, my earlier comment pointed out that the call stack is not coming from a released version since the names of some workspace methods were changed before release.

**Comment by happyhebaby** [comment]
@mattwar, that's exactly the root cause of the issue. After I update the roslyn package it now works perfectly. Thank you for your help!

**Comment by happyhebaby** [comment]
Thanks guys.

**Comment by happyhebaby** [comment]
Hi Matt, Kevin and Jonathon,
I run into a new issue, could someone take a look? Thanks a lot.#endif statement is missing after processing a function. · Issue #12524 · dotnet/roslyn

  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
#endif statement is missing after processing a function. · Issue #12524 · d...
 Version Used: 1.2.0.0 and 1.3.1.0 Steps to Reproduce: I have specific code processing each function(static or m...  |   |

  |

  |

 


 

    On Wednesday, June 22, 2016 12:58 PM, Matt Warren <notifications@github.com> wrote:
 

 @happyhebaby the coding pattern is not the problem. The TryApplyChanges call at the end is throwing the exception due to the addition of the metadata references. This was not a supported feature in pre-release versions of Roslyn. If you are actually using a released version then is should work fine. If you notice, my earlier comment pointed out that the call stack is not coming from a released version since the names of some workspace methods were changed before release.—

**Comment by mattwar** [comment]
Your code is missing.

Not knowing what "processing a function" is referring to, I'll guess that you are attempting to make edits to a syntax tree.  You probably did something that lost the current tree node's trailing trivia that would have contained the #endif text.

**Comment by happyhebaby** [comment]
Here is my major function processing method:
        public static MethodDeclarationSyntax InsertTrace(MethodDeclarationSyntax curMethod)
        {
            if (curMethod.Body != null)
            {
                string function = curMethod.Ancestors().OfType<NamespaceDeclarationSyntax>().Single().Name + "." + curMethod.Identifier.ValueText;
                int id = 0;
                if (!functionMap.ContainsKey(function))
                {
                    id = ++currentId;
                    functionMap[function] = id;
                }
                else
                {
                    id = functionMap[function];
                }

                BlockSyntax curBody = curMethod.Body;
                SyntaxTriviaList curTrivia = curBody.GetTrailingTrivia();
                DirectiveTriviaSyntax firstDirective = curBody.GetFirstDirective();
                string statementContent = logPrefix + id + logPostfix;
                StatementSyntax traceStatement = SyntaxFactory.ParseStatement(statementContent);
                SyntaxList<StatementSyntax> newStatements = curBody.Statements.Insert(0, traceStatement);//.Insert(1, newLineTrivia);
                if (firstDirective != null)
                {
                    SyntaxKind kind = firstDirective.Kind();
                    if (kind == SyntaxKind.IfDirectiveTrivia)
                    {
//Below are a few workarounds I tried to fix the syntax tree, but so far none of them work.
                        //newStatements = newStatements.Insert(curBody.Statements.Count + 1, insertedStatement);
                        //newBody.WithTrailingTrivia(SyntaxFactory.SyntaxTrivia(SyntaxKind.EndIfDirectiveTrivia, "#endif"));
                        //newBody = newBody.WithTrailingTrivia(SyntaxFactory.SyntaxTrivia(SyntaxKind.WhitespaceTrivia, "#endif"));
                    }
                    else
                    {
                        Console.WriteLine("Need to add support for {0}", kind.ToString());
                    }
                }

                BlockSyntax newBody = curBody.Update(SyntaxFactory.Token(SyntaxKind.OpenBraceToken), newStatements,
                                                    SyntaxFactory.Token(SyntaxKind.CloseBraceToken)).WithTrailingTrivia(curTrivia);
                MethodDeclarationSyntax newMethod = curMethod.ReplaceNode(curMethod.Body, newBody);

                return newMethod;
            }
            else
            {
                return curMethod;
            }
        }

I found if the #endif is the last statement in the function, then it has this issue, otherwise, if after #endif there is at least one more statement, then #endif is successfully included in the newMethod.
