### ISSUE TITLE
cibuild is hardcoded to VS2015 (doesn't work with Dev15)

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#12137]
cibuild.cmd has this line:

```
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat" || goto :BuildFailed
```

I wish it weren't hard-coded to VS2015. My machine only has Dev15 on it.

I tried changing it to 15.0 and did cibuild and got a bunch of errors:

```
  VisualStudioInteractiveWindow -> C:\Users\ljw10\Source\Repos\roslyn\Binaries\Debug\Microsoft.VisualStudio.VsIn
  teractiveWindow.dll
  Creating intermediate PkgDef file.
C:\Users\ljw10\.nuget\packages\Microsoft.VSSDK.BuildTools\15.0.25201-dev15preview2\tools\VSSDK\Microsoft.VsSDK.t
argets(959,5): error : CreatePkgDef : error : ProvideRoslynBindingRedirectionAttribute: Common Language Runtime
detected an invalid program. [C:\Users\ljw10\Source\Repos\roslyn\src\InteractiveWindow\VisualStudio\VisualStudio
InteractiveWindow.csproj]

  ServicesVisualStudio ->
  ServicesVisualStudio -> C:\Users\ljw10\Source\Repos\roslyn\Binaries\Debug\Microsoft.VisualStudio.LanguageServi
  ces.dll
  Creating intermediate PkgDef file.
C:\Users\ljw10\.nuget\packages\Microsoft.VSSDK.BuildTools\15.0.25201-dev15preview2\tools\VSSDK\Microsoft.VsSDK.t
argets(959,5): error : CreatePkgDef : error : ReflectionTypeLoadException: Unable to load one or more of the req
uested types. Retrieve the LoaderExceptions property for more information. [C:\Users\ljw10\Source\Repos\roslyn\s
rc\VisualStudio\Core\Def\ServicesVisualStudio.csproj]
C:\Users\ljw10\.nuget\packages\Microsoft.VSSDK.BuildTools\15.0.25201-dev15preview2\tools\VSSDK\Microsoft.VsSDK.t
argets(959,5): error :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module) [C:\Users\ljw10\Sour
ce\Repos\roslyn\src\VisualStudio\Core\Def\ServicesVisualStudio.csproj]
C:\Users\ljw10\.nuget\packages\Microsoft.VSSDK.BuildTools\15.0.25201-dev15preview2\tools\VSSDK\Microsoft.VsSDK.t
argets(959,5): error :    at System.Reflection.RuntimeModule.GetTypes() [C:\Users\ljw10\Source\Repos\roslyn\src\
VisualStudio\Core\Def\ServicesVisualStudio.csproj]
C:\Users\ljw10\.nuget\packages\Microsoft.VSSDK.BuildTools\15.0.25201-dev15preview2\tools\VSSDK\Microsoft.VsSDK.t
argets(959,5): error :    at System.Reflection.Assembly.GetTypes() [C:\Users\ljw10\Source\Repos\roslyn\src\Visua
lStudio\Core\Def\ServicesVisualStudio.csproj]
C:\Users\ljw10\.nuget\packages\Microsoft.VSSDK.BuildTools\15.0.25201-dev15preview2\tools\VSSDK\Microsoft.VsSDK.t
argets(959,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.ProcessAssembly(String fileName, Hive hiv
e, PkgDefContext context, Boolean register, RegistrationMode mode) [C:\Users\ljw10\Source\Repos\roslyn\src\Visua
lStudio\Core\Def\ServicesVisualStudio.csproj]
C:\Users\ljw10\.nuget\packages\Microsoft.VSSDK.BuildTools\15.0.25201-dev15preview2\tools\VSSDK\Microsoft.VsSDK.t
argets(959,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.DoCreatePkgDef(InputArguments inputArgume
nts) [C:\Users\ljw10\Source\Repos\roslyn\src\VisualStudio\Core\Def\ServicesVisualStudio.csproj]
C:\Users\ljw10\.nuget\packages\Microsoft.VSSDK.BuildTools\15.0.25201-dev15preview2\tools\VSSDK\Microsoft.VsSDK.t
argets(959,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.Main(String[] arguments) [C:\Users\ljw10\
Source\Repos\roslyn\src\VisualStudio\Core\Def\ServicesVisualStudio.csproj]
C:\Users\ljw10\.nuget\packages\Microsoft.VSSDK.BuildTools\15.0.25201-dev15preview2\tools\VSSDK\Microsoft.VsSDK.t
argets(959,5): error : Method 'TryCreateImageContent' in type 'Microsoft.VisualStudio.LanguageServices.Implement
ation.TableDataSource.SuppressionStateColumnDefinition' from assembly 'Microsoft.VisualStudio.LanguageServices,
Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation. [C:\User
s\ljw10\Source\Repos\roslyn\src\VisualStudio\Core\Def\ServicesVisualStudio.csproj]
C:\Users\ljw10\.nuget\packages\Microsoft.VSSDK.BuildTools\15.0.25201-dev15preview2\tools\VSSDK\Microsoft.VsSDK.t
argets(959,5): error :  [C:\Users\ljw10\Source\Repos\roslyn\src\VisualStudio\Core\Def\ServicesVisualStudio.cspro
j]
```

**Comment by Pilchie** [comment]
@CyrusNajmabadi is looking at this this week I believe.

/cc @jasonmalinowski

**Comment by CyrusNajmabadi** [comment]
I think matt is looking at this now.

**Comment by 333fred** [comment]
@tannergooding doesn't the script already prefer Dev15?

**Comment by tannergooding** [comment]
This has since been updated to do `
call "%RoslynRoot%SetDevCommandPrompt.cmd" || goto :BuildFailed` which will favor `VS150COMNTOOLS`.

However, due to VS15 removing the default environment variables/etc, you have to add a couple hacks to get this working (I think running from developer command prompt also works, except for NuGet).

The repo in generally needs to be updated to properly locate a VS install that meets the requirements for build and to consume the updated NuGet bits (I don't think these are actually out yet).

**Comment by jasonmalinowski** [comment]
@tannergooding Any reason to keep this bug alive at this point? I suspect we've cleaned most of it up by now.

**Comment by tannergooding** [comment]
I believe it has all been cleaned up now. @jaredpar could probably confirm since he has done the most recent work in this area.

**Comment by jaredpar** [comment]
Keep this for now.  Let me close it out with my xcopy work.  

We still do have hard codings (deliberately) 😦

**Comment by jasonmalinowski** [comment]
@jaredpar Can you update the bug/title to reflect current problems?

**Comment by jaredpar** [comment]
@jasonmalinowski the title is accurate.  Part of our build is hard coded to VS 2015.

**Comment by jasonmalinowski** [comment]
It does work with Dev15 though (if only by luck). :smile:

**Comment by jaredpar** [comment]
@jasonmalinowski try moving our machines to Dev15 only.  It will fail guaranteed due ot the fact we hard code Dev14 uses.

**Comment by tannergooding** [comment]
@jaredpar, It won't fail (and doesn't, as is indicated by the passing open VSI tests, which build and run on machines which only contain Dev15).

**Comment by jaredpar** [comment]
@tannergooding 

> It won't fail

Please refer to this line:

https://github.com/dotnet/roslyn/blob/master/src/Tools/MicroBuild/cibuild.cmd#L9

I stand by my earlier statement

> try moving our machines to Dev15 only. It will fail guaranteed due ot the fact we hard code Dev14 uses.

**Comment by jaredpar** [comment]
Note you can also look at the description Lucian provided in the initial bug report which details exactly where we hard code our references.  

I'm really unsure what the confusion is here.  

Is it why the hard coded reference exists?  That is to prevent us from accidentally updating to Dev15 only until we resolve other infrastructure issues.

**Comment by tannergooding** [comment]
That is the `MicroBuild` script, which does not always run with each invocation of `cibuild.cmd` (the issue title is explicitly calling out the later, not the former).

The MicroBuild script will currently fail if invoked. But `cibuild` WRT to building Roslyn.sln or running the Unit Tests or open Integration tests will succeed and is currently doing so in PR.

**Comment by jaredpar** [comment]
> That is the MicroBuild script, which does not always run with each invocation of cibuild.cmd (the issue title is explicitly calling out the later, not the former).

There are two cibuild.cmd scripts checked into our repo.  I explicitly linked to one of them which is alwsay run on the Microbuild leg.  Did you read the link I posted? 

> The MicroBuild script will currently fail if invoked

So we agree.  Moving to Dev15 can't happen because we've hard code references to Dev14?

> But cibuild WRT to building Roslyn.sln or running the Unit Tests or open Integration tests will succeed and is currently doing so in PR.

That is not the topic of this bug.

**Comment by tannergooding** [comment]
Yes it is. This bug was created before the MicroBuild script existed. The bug could be used to track MicroBuild as well, but when it was created there was no secondary script.

**Comment by jaredpar** [comment]
The bug says 

> cibuild is hardcoded to VS2015

This is true.  I have demonstrated this by providing a link.  I am presently working on fixing this, and the other ramifications to our infrastructure.  

The fact that the hard coding has migrated to a new instance of cibuild.cmd I don't find that signficant.  If you do please feel free to edit the bug.

**Comment by jasonmalinowski** [comment]
@jaredpar Just checking, there's still work this bug is tracking?

**Comment by jaredpar** [comment]
This is done 

https://github.com/dotnet/roslyn/commit/28f7fed96b531ad20b763fa7fffc837e7bf7fe05#diff-0845f223c4cf3128c0835c8e7b03976b
