### ISSUE TITLE
Xamarin.Forms solution does not deploy until android setting are re-set

### ISSUE THREAD

**Issue by reader-man** [dotnet/roslyn#12132]
**Steps to Reproduce**:

I have this solution, that does not deploy in debug mode in android till I go to the .Droid project, and selecting its properties, then go to:
Android Options\Packaging Tab\
then un-tick both [Use shared Run-time] + [Use Fast Deployment (debug mode only)]
Save the changes.
then immediately tick both of them back on.
the problem, is that you need to do that every time you are going to debug and deploy the app in android emulator, or it will not deploy it.

![android settings](https://cloud.githubusercontent.com/assets/12806275/16239726/e732cc9c-37ee-11e6-8c00-ba1a6b388343.png)

**Expected Behavior**:

It should deploy the app in debug, without the need for resetting the project settings.

**Actual Behavior**:

It will not deploy, unless I reset the droid project settings as stated above.

**The sample solution here**:

https://drive.google.com/open?id=0B2xC75mde6w0UHlybk9DX2g0Z1E

**The Working Startup projects are only**:
testSyncfusion.Droid
testSyncfusion.UWP
And i am experiencing the problems with the testSyncfusion.Droid project.

**Environment**:

HDD: Samsung SSD 850 Pro 256GB
CPU: i7-2600 3.4GHz
RAM: 16GB
OS: win 10
IDE: VS 2015 update 2 + VS 2015 update 2 cumulative update: vs14-kb3151378.exe
Add-Ons: There is NO, I repeat no plug-ins like resharper or refactor installed, only plain VS, and even if they are, the loading of a solution having 55 normal class library projects, is faster than a solution having 55 PCL projects.
Xamarin: installed 4.1.0.530
Solution using Xamarin.Forms nuget 2.3.0.49

Needed installations:
* Syncfusion Essential Studio 2016 Vol 1 Xamarin u1 --> community edition: https://www.syncfusion.com/products/whatsnew
* sqlite-uwp-3130000.vsix: https://www.sqlite.org/2016/sqlite-uwp-3130000.vsix
* Visual Studio Emulator for Android 2.2: https://www.visualstudio.com/en-us/features/msft-android-emulator-vs.aspx

This was also written here:
https://bugzilla.xamarin.com/show_bug.cgi?id=42040

as i don't know if this should be reported to Xamarin or Microsoft.

**Comment by Pilchie** [comment]
Unfortunately, Roslyn has nothing to do with Android build deployment.  You should report this bug at Xamarin.com.
