### ISSUE TITLE
Property to method loses trivia from before the expression

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#12143]
**Version Used**: Roslyn 2.0.0.6061703

**Steps to Reproduce**:

1. Paste the following code into a new project:
```
class Class
{
    public int Test => /* return 42 */ 42;
}
```

2. Invoke property to method.

**Expected Behavior**: The comment is persisted.

**Actual Behavior**: It's lost for good.

**Comment by NoneGiven** [comment]
The issue title is backwards.

**Comment by jasonmalinowski** [comment]
@NoneGiven d'oh.
