### ISSUE TITLE
Move CodeLens reference computation to ServiceHub

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#12148]
Currently the reference computation for CodeLens happens out-of-proc. The diagnostic computation is moved out-of-proc as well but into a ServiceHub process. This means that there'll be duplication of workspaces. We want to consolidate out-of-proc computation in ServiceHub.

**Comment by MattGertz** [comment]
@panopticoncentral @srivatsn THis is already done right?  Moving to RC.2 at any rate to get it off the radar.

**Comment by panopticoncentral** [comment]
Done
