### ISSUE TITLE
C# code not correctly indented 

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#12155]
Reformatting the file doesn't correctly re-indent the second .Foo (); line.

using System;
namespace SwitchvoxSoftphone
{
  public class SampleClass
  {
    public SampleClass ()
    {
      this.Foo ()
                  .Foo ();
    }

    SampleClass Foo ()
    {
    }
  }
}

**Comment by Pilchie** [comment]
Is this meant to be the same issue as #12156?
