### ISSUE TITLE
CSharpFixAllOccurrences suite is flaky

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#12157]
This suite seems to fail as a group.  Either all the tests below fail or none of them do:

> CSharpFixAllOccurrences.FixAllOccurrences in Document - Apply Fix
> CSharpFixAllOccurrences.FixAllOccurrences in Document - Undo
> CSharpFixAllOccurrences.FixAllOccurrences in Solution - Apply Fix
> CSharpFixAllOccurrences.FixAllOccurrences in Solution - Verify error list after applying fix
> CSharpFixAllOccurrences.FixAllOccurrences in Solution - Verify document contents after applying fix
> CSharpFixAllOccurrences.FixAllOccurrences in Solution - Remove this qualification

This has occurred 8 times since yesterday, 28 times since last week.  It's a productivity blocker at this point.  Disabling this suite until it can be looked at:

Links to help investigator:

- Failures since [last week](http://jdash.azurewebsites.net/builds/test?name=CSharpFixAllOccurrences.FixAllOccurrences+in+Document+-+Apply+Fix&viewName=dotnet_roslyn&limit=10&pr=true&startDate=2016-06-13)
- Failure [today](http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_prtest/219/)

**Comment by jaredpar** [comment]
@Pilchie who should this issue be assigned to?

**Comment by Pilchie** [comment]
Can you take a look at this please?

**Comment by balajikris** [comment]
I think @dotnet/roslyn-analysis owns this test. @srivatsn - can you please confirm? If so, could you please have someone look at this?

**Comment by balajikris** [comment]
from a cursory look, it looks like lots of diagnostics are not showing up as expected.

Here is an example failure:
Expected Count: '4975'
Actual Count: '9807'

Similar problem applies to our style diagnostics (this.) as well, that are being tested here. looks like a test bug, initially.

**Comment by balajikris** [comment]
nevermind, @mavasani fwd-ed me a email with lots of history :disappointed: will follow up with him to understand this test.

**Comment by mavasani** [comment]
Failed again: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/303/testReport/

Re-opening :(

**Comment by balajikris** [comment]
doesn't look like the same issue.. Please file a bug if that is the case.

**Comment by mavasani** [comment]
Sure, opened https://github.com/dotnet/roslyn/issues/12651
