### ISSUE TITLE
System.Reflection.Metadata 1.4.1-beta, added by PR #12073, fails strong name verification

### ISSUE THREAD

**Issue by CaptainHayashi** [dotnet/roslyn#12154]
**Version Used**: 

`master` (commit eed3167, after pull request #12073).

Commit 9f74043, ie before #12073 was merged, works.

**Steps to Reproduce**:

1. Clone a fresh copy of the above version
2. Restore packages using `restore.cmd` 
3. Try to compile with `msbuild /v:m /m Roslyn.sln`

**Expected Behavior**:

Compilation succeeds.

**Actual Behavior**:

Compilation fails at `VisualStudioSetup` with the following error:

```
  VisualStudioSetup -> C:\roslyn-vanilla\Binaries\Debug\Roslyn.VisualStudio.Setup.dll
  Creating intermediate PkgDef file.
C:\Users\(redacted)\.nuget\packages\Microsoft.VSSDK.BuildTools\14.2.25201\tools\VSSDK\Microsoft.VsSDK.targets(913,5): error : CreatePkgDef : error : ProvideRoslynBindingRedirectionAttribute: Could not load specified assembly: 'System.Reflection.Metadata' reason: Could not load file or assembly 'System.Reflection.Metadata, Version=1.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) [C:\roslyn-vanilla\src\VisualStudio\Setup\VisualStudioSetup.csproj]
```

On closer inspection, `Binaries\Debug\System.Reflection.Metadata` is delay- or test-signed:

```
C:\roslyn-vanilla>sn /v Binaries\Debug\System.Reflection.Metadata.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Binaries\Debug\System.Reflection.Metadata.dll is a delay-signed or test-signed assembly
```

If I revert to a commit (eg 9f74043) before `System.Reflection.Metadata` was bumped from `v1.3.0-rc3-24102-00` to `v1.4.1-beta-24221-04`, restore, clean, and build, the build works, and `sn` gives

```
C:\roslyn-vanilla>sn /v Binaries\Debug\System.Reflection.Metadata.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'Binaries\Debug\System.Reflection.Metadata.dll' is valid
```

Unsure whether this is an issue with Roslyn using this package, or an upstream issue with the package not coming signed, so I'm filing the issue here to be safe.

**Comment by CaptainHayashi** [comment]
`sn /Vr Binaries\Debug\System.Reflection.Metadata.dll` works as a (rather unpleasant) workaround.

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure @jasonmalinowski @tmat Looks like multiple people are hitting this.

**Comment by tmat** [comment]
@ericstj @weshaggard Seems like CoreFX build is producing unsigned binaries :(

**Comment by weshaggard** [comment]
I'm investigating the signing for corefx binaries.

**Comment by jasonmalinowski** [comment]
This has also broken the Roslyn signed build too, since we verify the contents of our packages have signed versions of this. @tmat is there a quick rollback option available?

**Comment by tmat** [comment]
Yes, we can roll back changes https://github.com/dotnet/roslyn/pull/12073

**Comment by tmat** [comment]
Rolled back: https://github.com/dotnet/roslyn/pull/12163

**Comment by CaptainHayashi** [comment]
Just to confirm that #12184 appears to be working fine in re. this bug.  Thanks!
