### ISSUE TITLE
currently IDiagnosticService or IDiagnosticAnalyzerService is MEF service, consider moving it to WorkspaceService

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#12164]
right now, IDiagnosticService and IDiagnosticAnalyzerService is MEF service rather than IWorkspaceService.

benefit it gives is they can share some data/cache among different workspaces. but it make them to have dictionary of data per workspace which gives lifetime management issue of workspace. especially for things like preview workspace that can be created on the fly and go away.

consider moving them to workspace service which is tied to one specific workspace.

**Comment by CyrusNajmabadi** [comment]
We have not had a need to do this.  So closing out this idea.
