### ISSUE TITLE
We should have GetTextSynchronously and GetSyntaxTreeSynchronously for features that must run on the UI thread

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#12166]
This corresponds to the change we made to have GetSyntaxRootSynchronously.  We've updated some features to call this, but they still suffer if they end up calling these other functions that hten make them hit the threadpool

**Comment by mattwar** [comment]
I don't understand why this is a problem.  Why does there need to be a synchronous version, and why do we need to avoid hitting the thread pool?  Adding this API sounds like a disaster in the making.

**Comment by CyrusNajmabadi** [comment]
> why do we need to avoid hitting the thread pool? 

Because when we hit hte thread-pool the UI thread is then blocked waiting for a turn to run.  When the threadpool is saturated (which is not uncommon), then the UI thread can be essentially blocked for a long time.  Note that the threadpool will only spin up new threads if it feels that the current of threads are not making progress.  If they are making progress, but the task we have is just at the end of a major saturated queue, then the user gets a really bad experience.

The problem we essentially have is that, for better or worse, we have APIs that demand synchronous responses and are called on the UI thread.  When we implement these APIs in a manner that puts us at the mercy of the threadpool we can and do experience anywhere from minor to significant pauses in the experience. 

> Adding this API sounds like a disaster in the making.

Can you be specific about the disaster you envision.  Right now the goal would be to use this purely from synchronous features.  We could even assert in them that this code should only be called from the UI thread (just like we assert that WaitAndGetResult should only be called from teh UI thread).  That way background async work is as fine grained and non-blocking as possible, but synchronous UI work can happen as efficiently and quickly as possible so we can relinquish the UI back to the host.

The best medium/long term fix would likely be to try to press on all our partner teams to get their APIs to not be synchronous.  However, there are a massive number of these APIs (codemodel for example) so it's not something we can trivially do.

Also note: the APIs we're adding here are internal.  They're only for very special whitelisted codepaths that we've decided have to have this compromise.

**Comment by mattwar** [comment]
Okay, as long as they are only internal.

**Comment by CyrusNajmabadi** [comment]
These functions were added.  Closing this out.
