### ISSUE TITLE
Workspace.TryApplyChanges(solution) does not apply RemoveMetadataReference.

### ISSUE THREAD

**Issue by malylemire1** [dotnet/roslyn#12161]
**Version Used**: Roslyn version is 1.2.2 on vs2015

**Steps to Reproduce**: 
1. Get VisualStudioWorkspace in a Visual Studio Package :

```
IComponentModel componentModel = (IComponentModel)Package.GetGlobalService(typeof(SComponentModel));
VisualStudioWorkspace workspace = componentModel.GetService<VisualStudioWorkspace>();
```
1. Remove the metadata references : 

```
Solution solution = workspace.CurrentSolution;

foreach (ProjectId projectId in solution.ProjectIds)
{
      Project project = solution.GetProject(projectId);
      foreach (MetadataReference reference in project.MetadataReferences.Where(m => m.Display == "ReferenceFilePath").ToList())
      {
           project = project.RemoveMetadataReference(reference);
      }

      solution = project.Solution;
}

workspace.TryApplyChanges(solution);
```

**Expected Behavior**:

Changes to solution should be applied.

**Actual Behavior**:

`solution.GetChanges(workspace.CurrentSolution).GetProjectChanges().Select(x => x.GetRemovedMetadataReferences());`
Returns the actual changes before the call to TryApplyChanges.

`workspace.CanApplyChange(ApplyChangesKind.RemoveMetadataReference);`
Return true.

Changes to solution are not applied.

**Comment by malylemire1** [comment]
Just to mention that the same code with AddMetadataReference works fine.

**Comment by mattwar** [comment]
We are removing the reference using the VSProject API, but are not receiving callbacks on any of the VS/project-system hooks for watching imports being changed.  Still investigating.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
