### ISSUE TITLE
MSBuildWorkspace incorrectly sets Document.Name for wildcard includes

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#12176]
When using MSBuildWorkspace to open a .csproj with the following fragment:

```
    <Compile Include="..\ExternalFiles\*.cs">
      <Link>Subfolder</Link>
    </Compile>
```

each of the .cs files included in the project from External files will have it's document.Name == "Subfolder" instead of the actual file name.

Here's a sample solution that you can analyze:
https://github.com/KirillOsenkov/SourceBrowser/tree/master/TestCode/WildcardIncludes

**Comment by Pilchie** [comment]
If we're going to do better support for wildcards for .NET Core, this seems like something we should fix.

**Comment by mattwar** [comment]
The workspace is interpreting this correctly.  Even though you used wildcards in the include, the link provide is just a single static name.  If you try to open this in VS you will fail and get an error. 

When a link is provided, this is the name that is used to place and describe the document in the solution explorer.  In the same way the msbuild workspace uses the link to form the name of the document and folders.  So if you have a static link expression then you'll get a bunch of documents with same name.

Instead, you can use a link that computes the name from the include path.

```
    <Compile Include="..\ExternalFiles\*.cs">
      <Link>Subfolder\%(Filename)%(Extension)</Link>
    </Compile>
```

If you do this then MSBuildWorkspace will have the correct document names.

**Comment by KirillOsenkov** [comment]
Copying @controlflow - can you look over it and make sure Matt's suggestion makes sense to you? I think I agree this is by design.
