### ISSUE TITLE
Insertion tool should not assume that the assembly version of a NuGet package is the package version

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#12187]
Currently, we only rev our assembly version for Roslyn assemblies for major/minor releases. Bug fixes get new package versions per semver, but we don't rev the assembly version to avoid surprises around binding redirects. The insertion tool currently assumes otherwise, which breaks as soon as these diverge.

**Comment by jasonmalinowski** [comment]
@brettfo Once you've got the other two things off your plate, can you investigate this and see if this is still a problem? I think the best process here would be to try making your own little branch off of 2.0.0, version it 2.0.1 (but leave assembly at 2.0.0), do an insertion and see what blows up. Since we'll be doing this at some point for servicing in the net few weeks, we should front-load this and find out what breaks.

**Comment by brettfo** [comment]
Everything works correctly as per:
- [`$(RoslynFileVersionBase)`](https://github.com/dotnet/roslyn/blob/master/build/Targets/Versions.props#L13) set to 2.1.1.
- Full signed build completed.
- VS insertion tool against this build was correct (using standard values).
- Full VS validation build installed and runtime is correct (e.g., IDE features work as expected).
- Installed VS component is 2.1.1 and file properties for Microsoft.CodeAnalysis.dll report 2.1.1.
- ILSpy reports 2.1.0 as assembly version.
