### ISSUE TITLE
Allow to remove folder in solution or project.

### ISSUE THREAD

**Issue by malylemire1** [dotnet/roslyn#12183]
**Version Used**: Roslyn version is 1.2.2 on vs2015

**Expected Behavior**:

Be able to remove a folder from a project.

solution.RemoveFolder(folder.Id, recursiveRemove == true);
project.RemoveFolder(folder.Id, recursiveRemove == true);

**Actual Behavior**:

There seems to be no way of deleting a project or a solution folder.

**Comment by mattwar** [comment]
Roslyn workspace does not model project or solution folders. It does detail the folder names that each document exists within however.  So it would be possible to write a helper API to remove all documents within a folder, but you wouldn't be able to convey the concept of removing the actual folder.
