### ISSUE TITLE
We should asynchronously retry reading of metadata if the file is locked

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#12189]
If the Workspaces layer fails to read a source file, we return an empty file for that particular snapshot, and then start an asynchronous retry process. If we can successfully read the file, we then force a new Solution snapshot to be created with the new text. We should do something similar for metadata references. if we try to read a metadata reference and it's still locked for some external process, we will continue to use a cached (and broken) `VisualStudioMetadataReference` until the file gets touched again.

**Comment by jasonmalinowski** [comment]
To be clear: this proposal cannot break the snapshot model. Like files, the existing snapshot will be broken, but a new snapshot could be made later with a new Solution object.

**Comment by MattGertz** [comment]
Adding Urgency-Now, as this is related to a DTS bug.

**Comment by Pilchie** [comment]
Dropping `Urgency-Now` and moving to `Unknown`.  It isn't clear how necessary retrying and updating the snapshot is now that we're delaying reloads as in #12686.

**Comment by Pilchie** [comment]
Re-opening, since we can still consider the async retry.

**Comment by CyrusNajmabadi** [comment]
Closing out as there's no driving data indicating this is needed.  If that comes up, we should just do the work.  A tracking issue on this doesn't help us.
