### ISSUE TITLE
Generate constructor code fix is not offered when Out Variable Declarations feature is not available

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#12182]
See unit-test in https://github.com/dotnet/roslyn/pull/12159, src/EditorFeatures/CSharpTest/Diagnostics/GenerateConstructor/GenerateConstructorTests.cs:
- TestOutVariableDeclaration_ImplicitlyTyped
- TestOutVariableDeclaration_ImplicitlyTyped_NamedArgument
- TestOutVariableDeclaration_ExplicitlyTyped
- TestOutVariableDeclaration_ExplicitlyTyped_NamedArgument

They fail when parse options used make Out Variable Declarations feature unavailable.

The code fix machinery relies on semantic diagnostic to offer the fix, but it looks like the presence of parser errors about feature unavailability suppresses the diagnostics that triggers the fix.

**Comment by CyrusNajmabadi** [comment]
Interesting.  Suppression of semantic errors on syntax errors seems like a generally good idea for things like the error list/squiggles.  However, for features, it seems suboptimal.  Could we still report the diagnostics, but if they're suppressed give them a severity of "Hidden"?

**Comment by AlekseyTs** [comment]
We simply can stop suppressing that diagnostics because, apparently, the suppression doesn't happen for methods (non-constructors).

**Comment by CyrusNajmabadi** [comment]
That sounds reasonable!

On Jun 23, 2016 11:41 AM, AlekseyTs <notifications@github.com> wrote:

We simply can stop suppressing that diagnostics because, apparently, the suppression doesn't happen for methods (non-constructors).
