### ISSUE TITLE
Proposal: noreturn methods

### ISSUE THREAD

**Issue by omariom** [dotnet/roslyn#12199]
TypeScript got [`never` type](https://github.com/Microsoft/TypeScript/pull/8652) which allows to define methods that never return.
I propose similar feature for C#.

Methods "returning" `noreturn`  type must definitely throw or call other `noreturn` methods. 
They can't have `return` statements in their body nor `out` parameters. At callsites they should be threated by the compiler similarly to `throw` statements.

It will require support from CLR. and that's a good thing as CLR could take advantage of that and optimize generated code around callsites to `noreturn`s as it does now with `throw`s.

```C#
private noreturn LogAndFailFast()
{
     s_logger.Log(whatever_required);
     Environment.FailFast();
}

static class ThrowHelper
{
   public noreturn ThrowInvalidInputException(ObjectType type, long id)
   {
       throw new InvalidInputException(string.Format(InvalidInputFormatString, type, id));
   }
}
```

**Comment by omariom** [comment]
@mikedn I remember you talked about benefits of `noreturn`s  for codegen.

**Comment by HaloFour** [comment]
Dupe of #1226

**Comment by omariom** [comment]
Ouch!
