### ISSUE TITLE
Anonymous type declaration with inferred property name causes an identity crysis

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#12193]
**Version Used**: VS2015.2

**Steps to Reproduce**:
```csharp
class Program
{
    static void Main(string[] args)
    {
        var tester = new Person();

        var result = new { tester.Name$$ };
    }
}

class Person
{
    public string Name { get; set; }
}
```
1. Set cursor to `$$`
2. Try to go to definition (F12)

**Expected Behavior**:
`public string Name { get; set; }` gets selected

![devenv_2016-06-24_01-32-01](https://cloud.githubusercontent.com/assets/7110884/16323522/aae85f36-39ab-11e6-91a7-fbe5028b0b4a.png)

**Actual Behavior**:
Selection just expands to `Name` on the same line.
When the property name is inferred, visual studio treats `tester.Name` as the anonymous type property. Changing that line to `var result = new { Name = tester.Name };` allows to go to definition on `tester.Name`.

![devenv_2016-06-24_01-32-21](https://cloud.githubusercontent.com/assets/7110884/16323526/b0920ed2-39ab-11e6-874c-f1d13f4c3eed.png)

**Comment by Pilchie** [comment]
This is basically the same thing as https://github.com/dotnet/roslyn/issues/3589.
