### ISSUE TITLE
Consider introducing an overload of Solution.GetCompilationAsync that takes a Project

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#1220]
While debugging, I noticed that the following stack happens *a lot* in the diagnostic analyzer:

                Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Solution.GetProject(Microsoft.CodeAnalysis.ProjectId projectId)
                Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Solution.GetCompilationAsync(Microsoft.CodeAnalysis.ProjectId projectId, System.Threading.CancellationToken cancellationToken)
                Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Project.GetCompilationAsync(System.Threading.CancellationToken cancellationToken)

We have a project, we ask for the ID, we pass the ID as an argument, and then we immediately look up the project in order to check the “SupportsCompilation” property (which, I’m assuming, doesn’t change across versions).

**Comment by Pilchie** [comment]
Can you verify?

**Comment by amcasey** [comment]
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/Solution.cs,945c4dd600dc6fd7
