### ISSUE TITLE
Refactoring saves files

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#12209]
Just question, is it necessary for the quick fixes/refactorings (e.g. extract local) to trigger saving the file (and potentially check-out)?

**Comment by Pilchie** [comment]
Normally, we only save if the refactoring changes more than one file - are you seeing cases where that isn't true?

(Note that checkout happens at edit time, not save, so it will tend to happen regardless)

**Comment by miloush** [comment]
Yes I think I am... although it is probably always rename.

If you for example extract local, it enters the rename mode. You type the name and confirm using Enter. That triggers the save, even when it _introduces local_ which cannot be in any other file AFAIK.

(checkout can happen at save time, Source Control > Environment > Checked-in items)

**Comment by Pilchie** [comment]
I suspect that you're right and rename always saves.

**Comment by CyrusNajmabadi** [comment]
Closing out as we're unlikely to change this.
