### ISSUE TITLE
Analyze solution with WPF projects

### ISSUE THREAD

**Issue by softwaretirol** [dotnet/roslyn#12215]
**Version Used**:  2.0.0-beta1

**Steps to Reproduce**:

I just analyzed a small solution which consists of several WPF projects. The major problem for me is, that it seems that the XAML Build Task isnt getting executed. Therefore the g.cs files are not getting generated.

```
 var properties = new Dictionary<string, string>
            {
                { "DesignTimeBuild", "true" },
                { "BuildingInsideVisualStudio", "true" }
            };
            var workspace = MSBuildWorkspace.Create(properties);
            var solution = await workspace.OpenSolutionAsync(solutionPath, cancellationToken);
            var compilations = await Task.WhenAll(solution.Projects.Select(x => x.GetCompilationAsync(cancellationToken)));
```

**Expected Behavior**:
Would be a successfull compilation.
**Actual Behavior**:
Error during compilation, like "InitializeComponent()" not found.

**Comment by Pilchie** [comment]
Do you have binding redirects for the msbuild assemblies?

See https://github.com/dotnet/roslyn/issues/2779 for some more information.

**Comment by softwaretirol** [comment]
Hi @Pilchie ,

Thanks for giving me the hint, i was not aware that this is still needed.
After adding the redirects, and downgrading to the latest stable version everything worked as expected.
