### ISSUE TITLE
Completion service too hard to instantiate - need improvements to MSBuildWorkspace.Create

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#12218]
**Version Used**: Roslyn github drop as of June 20th

My code traditionally looks like this:

``` csharp
var workspace = MSBuildWorkspace.Create();
```

I want to use the completion service. But the call to `CompletionService.GetService(document)` fails, because the above `MSBuildWorkspace.Create()` apparently hasn't even loaded the necessary DLLs. As far as I can tell, if I want to be able to use the completion service, this is the new minimal startup code:

``` csharp
var assemblies = new[] {"Microsoft.CodeAnalysis", "Microsoft.CodeAnalysis.CSharp", "Microsoft.CodeAnalysis.Features",
            "Microsoft.CodeAnalysis.CSharp.Features","Microsoft.CodeAnalysis.Workspaces.Desktop"}.Select(Assembly.Load);
var types = MefHostServices.DefaultAssemblies.Concat(assemblies).Distinct().SelectMany(x => x.GetTypes());
var context = new ContainerConfiguration().WithParts(types).WithDefaultConventions(new AttributeFilterProvider()).CreateContainer();
var host = MefHostServices.Create(context);
var workspace = MSBuildWorkspace.Create(host);

public class AttributeFilterProvider : AttributedModelProvider
{
    public override IEnumerable<Attribute> GetCustomAttributes(Type reflectedType, MemberInfo member) => member.GetCustomAttributes().Where(x => !(x is ExtensionOrderAttribute));
    public override IEnumerable<Attribute> GetCustomAttributes(Type reflectedType, ParameterInfo member) => member.GetCustomAttributes().Where(x => !(x is ExtensionOrderAttribute));
}
```

That was very undiscoverable! If I merely want to use the completion service, I shouldn't be forced into learning the inner workings of MEF. I have no idea even what the `AttributeFilterProvider` is or does, but the code doesn't work if I comment it out...

I think I'd like `MSBuildWorkspace.Create()` to be reworked. There should be an overload which takes a set of flags for which Roslyn features I want (i.e. which additional DLLs it searches for).

Note: as things stand, I had to copy+paste the list of assemblies. That's because `DesktopMefServices.DefaultAssemblies` is private. It should instead be public, like `MefHostServices.DefaultAssemblies`.

**Comment by weltkante** [comment]
You can do
```csharp
MefHostServices.Create(MefHostServices.DefaultAssemblies.Concat(new[] {
    Assembly.Load("Microsoft.CodeAnalysis.Features"),
    Assembly.Load("Microsoft.CodeAnalysis.CSharp.Features"),
}))
```
and pass that to the MsBuildWorkspace

**Comment by Pilchie** [comment]
Hey @matwar - If those binaries are in the directory, should we pick them up automatically.

**Comment by mattwar** [comment]
No, the default host services only includes the workspace layer.   We could add an already composed default services in the the features dll that includes the features layer.
