### ISSUE TITLE
"Make the containing scope async" is not a suggested fix for a non-Task awaitable

### ISSUE THREAD

**Issue by matthejo** [dotnet/roslyn#12210]
**Version Used**: Visual Studio 2015 Update 2

**Steps to Reproduce**:
1. Create an awaitable class that is not derived from Task, e.g.
   
   ``` C#
   class MyAwaitable
   {
       public TaskAwaiter GetAwaiter() { return Task.CompletedTask.GetAwaiter(); }
   }
   ```
2. Start composing a method that awaits this awaitable:
   
   ``` C#
   void UseAwait()
   {
       MyAwaitable awaitable = new MyAwaitable();
       await awaitable;
   }
   ```
3. Invoke the lightbulb on the 'await awaitable' line. 

**Expected Behavior**:
Suggestion to "make containing scope async" appears since "await" can legitimately be used in this context.

**Actual Behavior**:
Suggestion to introduce a new type named "await" is given instead.

**Comment by CnSimonChan** [comment]
@Pilchie I'm investigating it. The related method is [LanguageParser.ParsePossibleDeclarationOrBadAwaitStatement()](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Parser/LanguageParser.cs#L6658).

Reading the comments, it seems that it's the intended behavior that, when it meets a valid local declaration statement, it never try to parse it as an await expression.

To improve it, maybe it needs to create a new internal statement type when local declaration and await are both valid, then try to bind it to both. There are many different situations so I'm not sure what's the best approach.

Any suggestion?

**Comment by CnSimonChan** [comment]
And this issue description is not precise. The following code await a `Task`, but it's also considered as a declaration.

```` CSharp
void UseAwait()
{
    var awaitable = Task.CompletedTask;
    await awaitable; // CS0246	The type or namespace name 'await' could not be found
}
````

**Comment by Pilchie** [comment]
Tagging @CyrusNajmabadi and @gafter who know more about the parser than I do.

**Comment by CyrusNajmabadi** [comment]
I don't feel like this is a parser issue.  I think the parser is doing the right thing here.  I think this is an issue on the code fix side where we should look for this syntactic pattern and offer the fix appropriately.

**Comment by CyrusNajmabadi** [comment]
(and i say that as someone generally very pro-changing the parser when appropriate).

HOwever, in this case, the code is syntactically correct and the idea of parsing out some new type of construct doesn't fit with how we've structured the parser and rest of the systems.

**Comment by CyrusNajmabadi** [comment]
No repro: 

![Image](https://github.com/user-attachments/assets/d44a493c-fe4f-46f4-98d8-f60ebc83732d)
