### ISSUE TITLE
Line numbers are not enabled as default

### ISSUE THREAD

**Issue by forki** [dotnet/roslyn#1222]
Please enable "line numbers" as a default for the code editor.

This is a duplicate of https://github.com/Microsoft/visualfsharp/issues/304 and https://github.com/Microsoft/TypeScript/issues/2325, but we think it should be done for all languages (see https://github.com/Microsoft/visualfsharp/issues/304#issuecomment-78557404)

**Comment by JoshVarty** [comment]
:+1:

**Comment by latkin** [comment]
Found an old UserVoice here http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/3273933-enable-line-numbers-by-default, if anyone cares to vote.

**Comment by DustinCampbell** [comment]
We've had some internal discussions (including @latkin) and it seems that there isn't an obvious solution here. The developers involved in the conversation seem to be pretty evenly split on the issue. Some say that line numbers is the first thing that they turn on after installing VS. Others say that it's the first thing they'd turn off if they were on by default.

The conclusion is that we're not going to change the default setting. With Visual Studio's roaming settings, this is less of a problem today. Assuming that you log in to VS, you can enable line numbers once, and the setting should follow you to other machines.
