### ISSUE TITLE
Make code previews "smarter"

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#12233]
Most of the time code previews are on point, but sometimes the diff they show could be cleaned up. For example,
![image](https://cloud.githubusercontent.com/assets/1402694/16393791/fcffb78e-3c66-11e6-8498-08b30dae4165.png)

would be a stronger code preview if it more obviously showed the property pieces together and then put the method pieces together (instead of having a hodgepodge of both).

**Comment by Pilchie** [comment]
Right now we rely on a line based text diffing engine - fixing this would rely on a smarter, syntax based diff.

**Comment by CyrusNajmabadi** [comment]
This is really on platform/editor if htey want to supply a new experience here.
