### ISSUE TITLE
[Code Style] Preferring framework type doesn't fade predefined types

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#12232]
When I switch my code style to prefer framework types, my framework types correctly unfade themselves. However, any place where I have a predefined type doesn't fade (see `char.IsLower`):

![image](https://cloud.githubusercontent.com/assets/1402694/16393657/789d023a-3c66-11e6-9f54-7fbdf63b8420.png)

`char` should be faded here.

**Comment by Unknown6656** [comment]
Do please forgive my ignorance, but exactly do you mean by "fade"? Which result did you expect?

_I am sorry to ask this (trivial) question, but as English is not my native language, I am not quite sure, where the issue exactly is._

**Comment by Pilchie** [comment]
@balajikris - this is the thing we talked about the other day.  This analyzer is unidirectional right now, and you can't adjust the severity.

**Comment by balajikris** [comment]
True, work to port this over to the new codestyle UI with severity options isn't done yet. I'll use this bug to track that work.

@Pilchie : can you clarify what you mean by unidirectional? I think the existing analyzer goes both ways "Framework type <-> Predefined type". No?

**Comment by Pilchie** [comment]
IIRC, the diagnostic only pushes you to Predefined typed.  If you say prefer Framework type, there is never a diagnostic or fix to help you get there.

**Comment by Pilchie** [comment]
(Similar to how the `this./Me` fading used to be before @brettfo fixed it)

**Comment by balajikris** [comment]
Thanks.

**Comment by balajikris** [comment]
WIP at https://github.com/dotnet/roslyn/pull/13132

**Comment by balajikris** [comment]
Fixed with #13132
