### ISSUE TITLE
Performance considerations for large solutions Update 3 revision?

### ISSUE THREAD

**Issue by Tmus5** [dotnet/roslyn#12246]
**Version Used**: VS Update 3

**Steps to Reproduce**:

1. Follow the instrucstions  listed to get to the regedit location (KEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\Roslyn\Internal\Performance\Cache)
2. I have not got a Rosyln directory, where should it be? see screenshot
![image](https://cloud.githubusercontent.com/assets/6599300/16415687/62df272c-3d36-11e6-8f9d-272b32ec77ee.png)

**Expected Behavior**: Be able to find the rosyln directory to add the new key

**Actual Behavior**: the directory does not exist on my machine

**Comment by Pilchie** [comment]
Sorry, you'll need to create the directories(aka `keys`)  that don't exist in the path.

**Comment by Pilchie** [comment]
(I'll update the wiki page to make that more clear - thanks!)
