### ISSUE TITLE
C# Interactive does not see System.Xml with IntelliSense

### ISSUE THREAD

**Issue by shaggygi** [dotnet/roslyn#12249]
Visual Studio 2015 Update 3

**Steps to Reproduce**:
1. Open C# Interactive
2. Type in using System.Xml

**Expected Behavior**:
Should be able to reference the namespace as it worked before updating to VS 2015 Update 3.

**Actual Behavior**:
It works after referencing the API with the following code:
# r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.6.1\System.Xml.Linq.dll"

**Comment by shaggygi** [comment]
Understanding this issue wasn't assigned to a milestone, I wanted to give an updated that I noticed this still wasn't working in VS 2017 RC.

**Comment by tmat** [comment]
You don't need to use the full path, this is sufficient:

```C#
#r "System.Xml.Linq"
```

**Comment by shaggygi** [comment]
Yep, that worked and good to know.  It used to work by adding `using System.Xml.Linq;`.  Is this coming back?

**Comment by tmat** [comment]
We have deliberately changed the set of references loaded by default to match csi.exe, so that all our interactive hosts have consistent configuration:

```
/r:System
/r:System.Core
/r:Microsoft.CSharp
/r:System.ValueTuple.dll
/u:System
/u:System.IO
/u:System.Collections.Generic
/u:System.Console
/u:System.Diagnostics
/u:System.Dynamic
/u:System.Linq
/u:System.Linq.Expressions
/u:System.Text
/u:System.Threading.Tasks
```

You can modify the configuration file:

```{vs install dir}\Common7\IDE\PrivateAssemblies\CSharpInteractive.rsp```

if you'd like to load more references or import more namespaces by default.
Unfortunately, we don't currently support this configuration to be specified on per-user bases, so you'll have to modify the settings per VS installation.

**Comment by shaggygi** [comment]
Oh, also good to know.  In that case, I will go ahead and close this issue.  Thx again for the details.

**Comment by tmat** [comment]
We have an issue tracking the per-user configuration if you are interested: https://github.com/dotnet/roslyn/issues/5976

**Comment by gridstackimmaculate** [comment]
@shaggygi https://stackdev.space/questions/exploring-xml-content-with-linq
