### ISSUE TITLE
File>New>Roslyn templates should use project.json, not packages.config

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#12248]
I wish the File>New>Roslyn templates would use project.json! I find packages.config really irritating. Most especially because it means I can't retarget my project safely, nor move the project's folder relative to its .sln file.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #61](https://github.com/dotnet/roslyn-sdk/issues/61) via [**ZenHub**](https://www.zenhub.com/)
