### ISSUE TITLE
Cannot restore nuget packages on fresh clone: access denied error

### ISSUE THREAD

**Issue by siddharth-krishna** [dotnet/roslyn#12256]
I just cloned the master branch, am on commit 0ded84474744dddf0a743829aa218ec13abd3e0a. Windows 10 machine, VS 2015 update 3, I've installed all the extensibility tools and everything.

I opened the Developer Command Prompt, navigated to the directory, and tried to run `Restore.cmd`:
```
\Source\Repos\roslyn>Restore.cmd
Deleting project.lock.json files
Deleted file - C:\Users\t-sikris\Source\Repos\roslyn\src\project.lock.json
Restoring packages: Toolsets
Access is denied.
Restore failed with ERRORLEVEL 1
```

I looked at some of the other issues and tried setting "Read and Execute" permissions on both `nuget.exe` and `Restore.cmd`. I also tried a fresh clone. Any idea what's going on?

**Comment by Pilchie** [comment]
Try editing `Restore.cmd` to add more verbosity to see what the root cause is?

**Comment by siddharth-krishna** [comment]
I'm not familiar with windows batch files - could you help me with the appropriate modifications? Thanks.

**Comment by Pilchie** [comment]
Just edit [Line 5](https://github.com/dotnet/roslyn/blob/master/Restore.cmd#L5) to not have the `-verbosity quiet` and then run again.

**Comment by siddharth-krishna** [comment]
Sorry for the delay. I tried that but got exactly the same output. I also tried to run the `nuget.exe` file myself with the arguments given in `Restore.cmd` and got an `Access is denied.` error.

I then looked at the security tab of the Properties of this file in Windows Explorer, and gave everyone, and my user read & execute permissions. It didn't seem to help. Double clicking `nuget.exe` also gives me an error ("You may not have the appropriate permissions to access the item").

**Comment by Pilchie** [comment]
@emgarten any idea about this?

**Comment by emgarten** [comment]
@siddharth-krishna running nuget.exe with no parameters fails also?

**Comment by AdamSpeight2008** [comment]
Also check to see if your anti-virus software is blocking it.

**Comment by siddharth-krishna** [comment]
Hi, it looks like this was some strange issue with permissions of the folder in which I was cloning the repo. Re-cloning to the same folder didn't help, but when I cloned into a completely different folder it somehow worked! Thanks for all your help.
