### ISSUE TITLE
Rename does not search in #region comment

### ISSUE THREAD

**Issue by epsitec** [dotnet/roslyn#12251]
**Version Used**: Visual Studio 2015, 14.0.25123.00 Update 2

**Steps to Reproduce**:

When I rename an interface, I can choose to rename _comments_ and _strings_.
But somehow `#region` has been left out.

``` c#
public interface IFoo { void Hello(); }
public class X : IFoo
{
    #region IFoo Members
    void IFoo.Hello() { }
    #endregion
}
```

When I rename `IFoo` to `IBar`, I'd love to have the code above be converted to:

```
    #region IBar Members
    void IBar.Hello() { }
    #endregion
```

With the current version of Roslyn refactoring, `#region IFoo Members` stays unchanged.

**Comment by Pilchie** [comment]
:link: also reported in https://developercommunity.visualstudio.com/content/problem/97592/rename-with-include-comments-and-includestrings-ha.html

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
