### ISSUE TITLE
[Proposal] Constructor Inheritance (aka `virtual .ctor`)

### ISSUE THREAD

**Issue by Unknown6656** [dotnet/roslyn#12263]
### Introduction:

Imagine the following situation:<br/>
I have an abstract class, with **many** constructors defined, and a few classes, which all inherit from my abstract class:

``` csharp
public abstract class AbstractParent
{
    protected int field1; // some common fields
    public abstract void method(); // an abstract or virtual method

    public AbstractParent(int a) { ... }
    public AbstractParent(int a, float b) { ... }
    public AbstractParent(double c, int i) { ... }
    // ... many more constructors ...
}

public abstract class ChildA : AbstractParent
{
    public override void method()
    {
        // code logic A;
    }
}

public abstract class ChildB : AbstractParent
{
    public override void method()
    {
        // code logic B;
    }
}

public abstract class ChildC : AbstractParent
{
    public override void method()
    {
        // code logic C;
    }
}

// you get the idea ;)
```

If I now want to use these constructors from any child class, I have to define each and everyone as follows:

``` csharp
public abstract class Child : AbstractParent
{
    public AbstractParent(int a)
        : base(a) { }
    public AbstractParent(int a, float b)
        : base(a, b) { }
    public AbstractParent(double c, int i)
        : base(c, i) { }
    // ...
}
```

which is _rather_ tedious and (a bit) pointless, as I do not really add new information/logic to the constructors.

<hr>

### Proposal:

I would therefore like to propose a syntax of an so-called `virtual` constructor:

``` csharp
public abstract class AbstractParent
{
    // ...
    public virtual AbstractParent(int a) { ... }
    // ... many more constructors ...
}
```

This constructor will be compiled as usual by compiler. If a class `Child` inherits from the abstract parent class `AbstractParent`, the compiler will automatically and implicitly add the virtual constructor to the child class as follows:

``` csharp
public abstract class Child
{
    // ...

    [DebuggerStepThrough, DebuggerNonUserCode]
    public Child(int a)
        : base(a)
    {
    }
}
```

If, however, the developer decides to 'override' the implicitly inherited virtual constructor, he uses the usual syntax:

``` csharp
public abstract class Child
{
    // ...

    public Child(int a)
    {
        // logic will be compiled as usual
        // and will not 'override' AbstractParent::.ctor(int)
    }
}
```

<hr/>

### Syntax:

As mentioned, I would use the `virtual`-keyword for this purpose, but I can also happily live any other syntax or keyword like `virtual` or some pseudo-attribute

### Why this proposal in the first place?

I have sometimes the problem, that I am writing an _convenient_ class, meaning a class with a [fluent design pattern](https://en.wikipedia.org/wiki/Fluent_interface), which contains many methods/constructors with corresponding method/constructor cascading. Implementing each and every constructor in the child classes is a real pain, which I usually solve with a small self-written script, which is reflection-based.
_(I am sure, that some tools exist out there, though ...)_

So these are my reasons why this proposal could be helpful:
- Increased readability, as code can be shortened by a significant amount
- Increased productivity, as one no more has to implement every single constructor
- Cleaner child class code and intuitive usage of `virtual` inside the parent class
- No major CLR changes required, as the constructor information has some reserved and unused flags, which could be used for the `virtual`-keyword (AFAIK)

Possible cons/alternatives:
- It is not completely obvious, which constructors a child class has, as they are only visible in the parent class code
- One could solve this by using extension constructors (IMO a very bad idea, even though I love the concept of 'extension everything')

**Comment by HaloFour** [comment]
I don't think that it's appropriate for the base class to define such a constructor.  It makes it impossible for a derived type to then hide that constructor.

I'd rather see a syntax that would allow a derived type to more easily inherit the parent constructors.  For example, Groovy has the `@InheritConstructors` annotation which instructs the compiler to automatically create constructors for each base constructor.  Actually, that very behavior can likely be accomplished via code generators.

**Comment by Unknown6656** [comment]
@HaloFour Maybe you are right in saying, that a child-side annotation/pseudo-attribute is a better idea.
My point is also, that I do not want to use external code generators, but have this functionality build into the C# language....

**Comment by TonyValenti** [comment]
This reminds me a lot of #8222

**Comment by Unknown6656** [comment]
@TonyValenti: right you are, indeed...

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
