### ISSUE TITLE
Clipboard format changed in VS2015.3

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#12260]
The clipboard format appears to have changed in VS2015.3:

Previously we expected something such as
```
"{\\rtf\\ansi{\\fonttbl{\\f0 Consolas;}}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\f0 \\fs24 \\cf1 \\cb2 \\highlight2 1 + 2}"
```

Now we are receiving:
```
"{\\rtf\\ansi{\\fonttbl{\\f0 Consolas;}}{\\colortbl;\\red0\\green0\\blue0;}\\f0 \\fs24 \\cf1 \\cb0 \\highlight0 1 + 2}"
```

See also: https://github.com/dotnet/roslyn/pull/12257

**Comment by tannergooding** [comment]
FYI. @tmat, @jasonmalinowski, @olegtk

**Comment by olegtk** [comment]
Commented in #12257 as this is by design. I can find you corresponding internal bug if you need.

**Comment by tmat** [comment]
@olegtk  It's OK. Just confirmation that the change was intentional is good.
