### ISSUE TITLE
Broken analyzer dependencies in Update3

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#12273]
**Version Used**: 
VS2015 Update3, master branch

**Steps to Reproduce**:
1. Build roslyn.sln, start VisualStudioSetup project.
2. In RoslynDev instance, create a new Console Application.
3. In package manager console, type:
```
install-package jetbrains.annotations
install-package resharpercodecontractnullability
```

**Expected Behavior**:
Analyzer runs (reports on Main method)

**Actual Behavior**:
Analyzer does not start. Instead, the next errors are displayed after build:
```
1>CSC : warning CS8032: An instance of analyzer CodeContractNullability.CodeContractItemNullabilityAnalyzer cannot be created from e:\bart\documents\visual studio 2015\Projects\ConsoleApplication3\packages\ResharperCodeContractNullability.1.0.5\analyzers\dotnet\cs\CodeContractNullability.dll : Could not load file or assembly 'System.Collections.Immutable, Version=1.1.36.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..
1>CSC : warning CS8032: An instance of analyzer CodeContractNullability.CodeContractNullabilityAnalyzer cannot be created from e:\bart\documents\visual studio 2015\Projects\ConsoleApplication3\packages\ResharperCodeContractNullability.1.0.5\analyzers\dotnet\cs\CodeContractNullability.dll : Could not load file or assembly 'System.Collections.Immutable, Version=1.1.36.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..
```

This reminds me of [a similar problem](https://github.com/dotnet/roslyn/issues/4831). Do we miss some binding redirects?

@srivatsn @tmeschter @mavasani

**Comment by srivatsn** [comment]
Yes, I believe @jasonmalinowski added the missing redirects for System.Collections.Immutable recently.

**Comment by jasonmalinowski** [comment]
Yeah, I broke this in master a few days ago but fixed it with #12231. Can you verify it's working for you again?

**Comment by bkoelman** [comment]
@jasonmalinowski I am at f8a6b35b31174eefd1da07c6e4c7dd4b78f3ce35, where it still repros.

**Comment by jasonmalinowski** [comment]
Turns out I didn't fix it. :smile: #12075 is our tracking bug for this now; I'm going to dupe this.

**Comment by bkoelman** [comment]
@jasonmalinowski Thanks for looking into this, the build warning is now fixed for me. However, diagnostics of my analyzer are not reported correctly in Update3. See https://github.com/dotnet/roslyn/issues/12325 for details. Can you take a look?

**Comment by jasonmalinowski** [comment]
Looks like @mavasani is already looking at that one, who is your expert.
