### ISSUE TITLE
Visual Studio 2015 Update 3 is not detecting that the Platform SDK is Installed

### ISSUE THREAD

**Issue by 06needhamt** [dotnet/roslyn#12276]
After installing the roslyn plugin platform SDK when i try to create an analyser project i still see the message asking to  download the SDK. See screenshot below

![roslyn 1](https://cloud.githubusercontent.com/assets/4162227/16447097/c025c10a-3de2-11e6-8103-1522c4f68336.png)

However i can see that the SDK is installed by going to tools and Extensions and updates. See screenshot below.

![roslyn 2](https://cloud.githubusercontent.com/assets/4162227/16447124/e26b3646-3de2-11e6-8527-3918c6fd3191.png)

**Comment by jmarolf** [comment]
Change the .net version to be 4.6 instead of 4.5

**Comment by 06needhamt** [comment]
Fixed this by resetting visual studio by deleting it's app data folders and registry keys nothing else worked for me will keep this issue open for anyone else

**Comment by jmarolf** [comment]
I your screen shot it says you are targeting .NET framework 4.5.  The templates are incompatible with that version.  You would need to target 4.5.2 or later. Can you see Roslyn SDK templates for .NET 4.5 after deleting app data and registry keys?

**Comment by jmarolf** [comment]
What happens if you create a 4.5 analyzer project?

**Comment by 06needhamt** [comment]
The project creates properly and also compiles and runs see link. 
https://mega.nz/#!ll5UQKSB!9DoMDaoyUbYq_mpY6249YuYXlsrZy7Jf5b4WsEY2KHs

**Comment by jmarolf** [comment]
Looking at the project files, you are targeting .NET 4.5.2, which is the minimum version.  Sorry for being unclear, I was asking if the templates showed up for regular old 4.5 (4.5.0) like we see in the screen shot,

**Comment by 06needhamt** [comment]
Closing this as it is no longer relevant
