### ISSUE TITLE
Suggestion for restore.cmd

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#12279]
Delete the binaries, so that it can build with the correct versions.

**Comment by jasonmalinowski** [comment]
Can you clarify what you mean? If you build everything should get rebuilt properly. Are you not seeing that?

**Comment by AdamSpeight2008** [comment]
For example if you are on different branch say `future` and then switch back to `master`, I generally do a `restore,cmd` and build before reopening VS. If I don't do the `restore.cmd` There is a risk that the `binaries` have incorrect versions in it.
