### ISSUE TITLE
Wiki change: Formatting error in page Performance considerations for large solutions

### ISSUE THREAD

**Issue by henriksen** [dotnet/roslyn#12278]
The wiki page "[Performance considerations for large solutions](https://github.com/dotnet/roslyn/wiki/Performance-considerations-for-large-solutions)" had a missing backtick that screwed up some formatting. 

I can't do a PR to the wiki repo, but I have [a copy of the repo with a commit with the change needed](https://github.com/henriksen/roslyn-wiki/commit/6df0e4a9b75da6155acb86145f36a019d4f0c8ef).

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #71](https://github.com/dotnet/roslyn-sdk/issues/71) via [**ZenHub**](https://www.zenhub.com/)
