### ISSUE TITLE
BasicVenus.Snippets in Nuggets: from snippet picker is flaky

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#12288]
There's been many recent failures of this:

https://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1/230/
https://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1/231/
https://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1/232/
https://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1/233/

**Comment by tannergooding** [comment]
Tagging @dpoeschl, @CyrusNajmabadi, @balajikris who were discussing the issue.

**Comment by balajikris** [comment]
Filed '236027' for the editor team to look at, since this is a bug in their code.

**Comment by Pilchie** [comment]
Can you track the results of the internal bug?

**Comment by balajikris** [comment]
Note: this scenario is now commented out in BasicVenus.xml since it will always fail. The rest of the test is enabled. Need to uncomment once we get the fix.

**Comment by balajikris** [comment]
dropping urgency-now as the scenario is disabled and the real work is being done by the Editor team. This is a tracking bug.

**Comment by Pilchie** [comment]
Can you take a look at the internal bug and see if there is something we can do now?

**Comment by Pilchie** [comment]
Fixed by #1418.
