### ISSUE TITLE
Peverify needs to be updated for new ref-locals/returns rules

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#12285]
The C# compiler has new rules for ref-locals/returns to verify that their use is safe (that no refs are captured beyond their lifetime), but the same logic is not included in peverify, so the assembly is inappropriately unverifiable in certain cases. PEVerify should be updated with the same new logic as is in the C# compiler.

**Comment by svick** [comment]
Does this mean the CLI specification (ECMA 335) should be updated too?

**Comment by jaredpar** [comment]
Note the right repo for PEVerify bugs.
