### ISSUE TITLE
HTML in a .cshtml file in a section that is marked as unnecessary, does not get faded out

### ISSUE THREAD

**Issue by Vannevelj** [dotnet/roslyn#12284]
**Version Used**: 

Visual Studio 2015 Update 3

**Steps to Reproduce**:
1. Create a new analyzer that has `WellKnownDiagnosticTags.Unnecessary` set
2. Fire the analyzer on the body of all `if` statements
3. Execute the analyzer on a razor file (`.cshtml`)
4. Include a statement like the following:

``` csharp
@if(expression)
{
    var x = 5;
    <text> Hello Roslyn </text>
    var y = 10;
}
```

**Expected Behavior**:

The entire body is marked unnecessary (aka: greyed out)

**Actual Behavior**:

Only the C# elements of the body are marked as unnecessary.

![blob](https://cloud.githubusercontent.com/assets/2777107/16461146/fc7506b2-3e22-11e6-85c0-4175216c32b6.png)

**Justification**:

We work with a lot of ABTests which are turned on/off on an external service. I'm trying to provide us with the IDE support to see whether or not something has been turned off in which case I can grey out some sections of code.

**Comment by Pilchie** [comment]
Interesting - this is definitely something we should fix when we invest more in making razor work better with refactorings/fixes/etc.

**Comment by CyrusNajmabadi** [comment]
NOt touching legacy editor.  Modern lsp razor should be ablet o handle this.  If it doesn't, that would be a bug on them though.
