### ISSUE TITLE
CSharpErrorLog fails due to an API change

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#12289]
The CSharpErrorLog Integration Test is currently creating an instance of `Microsoft.CodeAnalysis.ErrorLog` via reflection.

However, the class was changed to an abstract class in https://github.com/dotnet/roslyn/commit/ce29dfd1bfc0299ee54a24114a798e962df6c9a7 thus breaking the test.

The test needs to be updated to support the new changes.

**Comment by balajikris** [comment]
**Note**:

Please also unblock test "CSharpFixAllOccurrences.xml" from TestLocator.cs when resolving this bug. (see https://github.com/dotnet/roslyn-internal/pull/1132 if you need details)

**Comment by cston** [comment]
Fixed.
