### ISSUE TITLE
Can we replace an expression with a proxy value during document parsing?

### ISSUE THREAD

**Issue by Vannevelj** [dotnet/roslyn#12299]
**The request**:

I'd like to be able to write an analyzer that can provide a proxy value for a certain expression and trigger a re-parsing of the document. 

**The motivation**:

Our code is littered with ABTests that can be either in a deployed or active state with a control and variant group. 
Determining a test's state is done through a database lookup.
For the tests that are deployed with the control group, any statement of the following form will evaluate to false:

```csharp
if(ExperimentService.IsInVariant(ABTest.Test1))
{
}
```

I'm trying to provide tooling to make this easier to deal with at develop time by greying it out in this scenario. 
As it is, this is fairly limited and not robust because I basically have to play parser myself. 

What if the actual code is

```csharp
if(!ExperimentService.IsInVariant(ABTest.Test1))
```

or

```csharp
if(ExperimentService.IsInVariant(ABTest.Test1) || true)
```

A possible approach I could see provided is by allowing us to write analyzers that are fired once and rewrite the tree before the actual IDE parsing happens (or, well, just parse it a second time).
These should only fire once and allow us to replace a certain expression with another. This would allow me to swap all of these experiment calls for `true` and `false` literals.
As a result, these sections could benefit from all the other IDE features such as code greying for unreachable code but also more intricate ones like a variable that will never have a different value

Obviously this is just an example and I'm not sure how feasible it is. Any suggestions for a proper feature or something that already exists are more than welcome.

**Comment by srivatsn** [comment]
It sounds like what you want is the source generators feature that lets you generate a new tree and then you want to run analyzers on the tree. @cston - will it be possible to replace expressions with source generators and will analyzers run on the generated trees?

**Comment by cston** [comment]
Source generators can add syntax trees to the compilation. If the original methods are declared in a `partial class`, the added trees can include methods that `replace` the original methods. That is, callers of the method are bound to the `replace` version, although both the `replace` method and the original are included in the compilation. Analyzers run on the entire compilation, including trees generated by source generators. Replacement is only at the method level though. To replace individual expressions would require the source generator to rewrite the existing methods.

Note that the source generators feature is only available in the https://github.com/dotnet/roslyn/tree/features/source-generators branch currently.

**Comment by srivatsn** [comment]
Closing this assuming that source generators would satisfy this scenario. If it doesn't please open a specific request for source generators.
