### ISSUE TITLE
Auto properties with setter blocks

### ISSUE THREAD

**Issue by kmc059000** [dotnet/roslyn#123]
I have always wanted to be able to write a setter block with auto properties. My reasoning below with proposed implementation:

````c#
public class SomeClass
{
    //traditional auto property
   public string Prop1 { get; set; }

   //property with logic in setter. must use private field (cant use auto property)
   private string _prop2;
   public string Prop2 
   {
        get 
        {
            return _prop2;
        }
        set
        {
            //do some sort of validation (null check, length, etc)
            if(value == null || value.Length > 50)
            {
                   throw new ArgumentException();
            }
             
            _prop2 = value;
        }
    }

    public void SomeMethod()
    {
        //can modify _prop2 without going through Prop2 property setter.
        _prop2 = "I can set this to whatever and avoid the setter block";
    }
}
````

The root problems is the necessity to create a field for a property when a get or set block needs to be defined. I'd like to see that necessity removed. The following code would become valid, and a new keyword would likely need to be added. I like this because it is succinct and concise:

````c#
public class SomeClass
{
    //traditional auto property
    public string Prop1 { get; set; }

   //property with logic in setter with auto property syntax
   public string Prop2 
   {
        get;        
        set
        {
            //do something before setting the value.
            if(value == null || value.Length > 50)
            {
                   throw new ArgumentException();
            }
            //innervalue would be the new keyword which represents the behind-the-scenes field 
            innervalue = value;
            
            //or even:
            value = value;
        }
    }

    public void SomeMethod()
    {
        //cannot modify Prop2 or wrapped field without going through Prop2 property setter.
        Prop2 = "all access must go through setter";
    }
}
````

This feature could be applied to getter as well where you can provide a getter body but use auto property syntax for the setter, although I personally can't think of a good reason to do that.

````innervalue```` would be a new keyword, although it seems as that the compiler should be able to reason that if ````value```` is the target of an assignment then it would behave like ````innervalue```` behaves. Although ````value = value;```` seems strange since ``value`` means different things on opposite sides of the ````=```` and counter to how that statement would be evaluated a different context like a constructor or method body.

I would guess that the compiler would be able to reason about the above case and know that since the get uses the auto property syntax but the setter does not, then the ````innervalue```` keyword would be available and understood. 

However in a case where both the get and set have a body defined, I'm not sure how the compiler would know whether to implement innervalue or not, or whether it should implement an inaccessible field that is only accessible in the get and set blocks of the property. To solve that problem I could see another keyword (yikes!) to be added. ````auto get```` or ````autoget```` could work.

````c#
public string Prop1
{
   auto get { /*body here*/ }
   auto set { /*body here*/ }
}
````

Another way to accomplish is to put the field in the scope of the property like below. I don't like this one because you have to create the field, and give it a name which is redundant, and you have provide an implementation for the get and set. It is too verbose. 

````c#
public string Prop1
{
    string _prop1;
    get
    {
        return _prop1;
    }
   set
   {
       _prop1 = value; 
   }
}

public string Prop2
{
   //cannot access _prop1
   get {...}
   set {...}
}
````

It also feels like accessibility would not be a problem either. 
````c#
public string Prop2 
{
    get;        
    private  set
    {
        //do something before setting the value.
        if(value == null || value.Length > 50)
        {
               throw new ArgumentException();
        }
        //innervalue would be the new keyword which represents the behind-the-scenes field 
        innervalue = value;
        
        //or even:
            value = value;
        }
    }
````

**Comment by dotMorten** [comment]
Are you saying this is to reduce the property declaration by not having to add only these two lines of code ?
``` 
private string _prop1;

get { return _prop1; }
````
and `innervalue` automatically maps to the autogenerated equivalent of '_prop1'

**Comment by kmc059000** [comment]
Yes, but more importantly, prevent access to ```_prop1``` elsewhere in the class and only allow access within that property.

**Comment by RichiCoder1** [comment]
Someone mentioned the idea of:
```csharp
public string Prop1
{
    get
    {
        return field;
    }
   set
   {
       field = value; 
   }
}
```

Where `field` is the underlying autogenerated field.

**Comment by wcabus** [comment]
What if you would return the value at the end of your set {} block, and use that to update the backing field instead?

```CSharp
public string Prop2 
{
    get;        
    private set
    {
        //do something before setting the value.
        if(value == null || value.Length > 50)
        {
               throw new ArgumentException();
        }
        
        return value; //To set the value to the backing field
    }
}
```
And maybe we could use the expression format here as well, could be useful for small but custom setters?
```CSharp
public string Prop1 {
    get;
    set => value.ToUpperInvariant()
}
```

**Comment by kmc059000** [comment]
@wcabus what if you do **not** want to modify the inner field though? ```return null;```? What about struct types?

**Comment by wcabus** [comment]
break; ? Although I must admit that I find that a bit sketchy.

**Comment by RichiCoder1** [comment]
I'd agreed @kmc059000. It also would break a lot of existing code.

**Comment by migueldeicaza** [comment]
I like what Swift does in this area, and it should satisfy the requirements of this request.

They introduce "observers" which are part of a property declaration.  They augment "set" and "get" with "didSet" and "willSet",  You can use those to validate the parameters with willSet, and you can run arbitrary code after a value has been set with "didSet".

Lots of code like this can be trivially rewritten:

    public Color TextColor {
        set {
            _color = value;
            NeedsUpdate (this);
       }
    }

And just becomes:

    public Color TextColor {
        didSet { 
            NeedsUpdate (this); 
        }
    }

**Comment by RichiCoder1** [comment]
That would make both Validation and patterns like `INotifyPropertyChanged` easier to think about.

**Comment by wcabus** [comment]
Indeed, that would be a very good approach :)

**Comment by kmc059000** [comment]
Does swift allow you to manipulate value in ```willSet```? How would this map to swift:

````c#
public string Prop1
{
    get;
    set
    {
        field = value.Trim();
    }
}
````

**Comment by deoradh** [comment]
To avoid breaking code, allow return;, but keep return value; for setting the backing field.

**Comment by gafter** [comment]
@CyrusNajmabadi I think you were interested in this area, and you wanted to propose property-local fields? I don't see an issue for that.

**Comment by MadsTorgersen** [comment]
Lots of good discussion. Some of the proposals in subsequent comments now have separate issues open. So there may be more ways of abbreviating properties in the future.

For the original proposal, however, we will not pursue this. Adding another way of referencing the backing value is too big of a hammer for too little gain. Just use a named field.

**Comment by kmc059000** [comment]
While I doubt this will change the decision and I am not attempting to, I want to clarify that the reasoning for this proposal was to limit access to the backing field. By using a named field, the field is visible to the entire class and this proposal was to prevent that.

**Comment by alrz** [comment]
@kmc059000 #850.

**Comment by jnm2** [comment]
Using a backing field without naming it was considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md
