### ISSUE TITLE
[Flaky test] CSharpRazor fails intermittently

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#12320]
See  http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_prtest/272/

```
11:05:04    Executing action [7/1/2016 5:44:13 PM] VerifyCompletionList
11:05:04 --------------------------------
11:05:04 System.Exception: Completion list was not showing and it was expected to be showing
11:05:04    at Roslyn.VSHosting.Test.VerifyCompletionListAction.<>c.<Execute>b__28_0(Object[] args) in d:\j\workspace\windows_vsi_p---5e702c54\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\VerifyCompletionListAction.cs:line 57
11:05:04    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio\Services\Remote\VsUIThreadInvokerService.cs:line 87
11:05:04 ================================
```

**Comment by mavasani** [comment]
Tagging @balajikris

**Comment by balajikris** [comment]
Updating with logs and screenshot:

![image](https://cloud.githubusercontent.com/assets/4213867/16534566/8de348de-3f95-11e6-81d4-915fc055eab9.png)

~~~
11:05:04  Scenario: Verify Completion commit after fully typed item.
11:05:04 	Executing action [7/1/2016 5:44:11 PM] OpenFile
11:05:04 DEBUG: executed DTE command File.OpenFile.
11:05:04 DEBUG: start polling for code window
11:05:04 DEBUG: polling complete
11:05:04 	Executing action [7/1/2016 5:44:11 PM] PlaceCursor
11:05:04 	Executing action [7/1/2016 5:44:11 PM] SendKeys
11:05:04 	Executing action [7/1/2016 5:44:11 PM] WebUtilities
11:05:04 	Executing action [7/1/2016 5:44:12 PM] WaitForWorkspace
11:05:04 	Executing action [7/1/2016 5:44:12 PM] PlaceCursor
11:05:04 	Executing action [7/1/2016 5:44:12 PM] SendKeys
11:05:04 	Executing action [7/1/2016 5:44:13 PM] VerifyCompletionList
11:05:04 --------------------------------
11:05:04 System.Exception: Completion list was not showing and it was expected to be showing
11:05:04    at Roslyn.VSHosting.Test.VerifyCompletionListAction.<>c.<Execute>b__28_0(Object[] args) in d:\j\workspace\windows_vsi_p---5e702c54\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\VerifyCompletionListAction.cs:line 57
11:05:04    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio\Services\Remote\VsUIThreadInvokerService.cs:line 87
~~~

**Comment by natidea** [comment]
Fix is pending in https://github.com/dotnet/roslyn-internal/pull/1158

**Comment by mavasani** [comment]
Another failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p3_open_prtest/9/

**Comment by mavasani** [comment]
Another failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_prtest/475/VS_Integration_Test_Logs/

**Comment by balajikris** [comment]
@mavasani: the failing scenario for this bug has been disabled. So, it cant possibly be failing.
the last link you posted is a different scenario. Please file a new bug. Here's logs and screenshot:

Scenario: Verify Completion list in Razor syntax
    Executing action [8/2/2016 7:08:34 PM] OpenFile
DEBUG: executed DTE command File.OpenFile.
DEBUG: start polling for code window
DEBUG: polling complete
    Executing action [8/2/2016 7:08:37 PM] PlaceCursor
    Executing action [8/2/2016 7:08:37 PM] SendKeys
    Executing action [8/2/2016 7:08:42 PM] WebUtilities
    Executing action [8/2/2016 7:08:42 PM] WaitForWorkspace
    Executing action [8/2/2016 7:08:42 PM] PlaceCursor
    Executing action [8/2/2016 7:08:43 PM] SendKeys
    Executing action [8/2/2016 7:08:44 PM] VerifyCompletionList


System.Exception: The following expected item(s) not found:
DateTime

   at Roslyn.VSHosting.Test.Utilities.ThrowIfExpectedItemNotFound[TCollection](IEnumerable`1 actual, IEnumerable`1 expected) in d:\j\workspace\windows_vsi_p---5e702c54\Closed\Hosting\Test\Actions\VisualStudio\Utilities\Utilities.cs:line 39
   at Roslyn.VSHosting.Test.VerifyCompletionListAction.<>c.<Execute>b__28_0(Object[] args) in d:\j\workspace\windows_vsi_p---5e702c54\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\VerifyCompletionListAction.cs:line 121
   at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments) in f:\dd\src\omni\Apex\HostIntegration\VisualStudio\Services\Remote\VsUIThreadInvokerService.cs:line 87

![image](https://cloud.githubusercontent.com/assets/4213867/17345360/7b594d92-58ba-11e6-8c3b-12160863e45a.png)

**Comment by mavasani** [comment]
@balajikris https://github.com/dotnet/roslyn/issues/12881

**Comment by Pilchie** [comment]
Moving to 2.1 - we wouldn't take a fix here at this point without an understood customer impact.

**Comment by CyrusNajmabadi** [comment]
@mavasani can this be closed out?

**Comment by CyrusNajmabadi** [comment]
Closing out as we have no hits on this in 5+ years.
