### ISSUE TITLE
Roundtrip tuple names through metadata

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#12347]
All names in source should be propagated through metadata, similar to how dynamic is preserved.

Simple cases should be handled by PR #12344. Simple is basically anything that isn't complex, where complex includes:

- [x] "Long" tuples (tuples that require nesting in >= 8th element)
- [x] Interface implementations in type definitions
- [x] Type parameter constraints

# LDM questions
- [x] Should compilation of a tuple without names, such as  `(int, string) temp = (1, null);`, fail if the attribute type is not present in the compilation? (issue was fixed already)

**Comment by tmat** [comment]
Is there another work item tracking encoding this information to PDBs as a custom debug information blob (Windows and Portable), or should it be part of this workitem?

**Comment by agocke** [comment]
I can add that to this one.

**Comment by jaredpar** [comment]
@agocke is this list up to date?  Pretty sure long tuples are complete.

**Comment by agocke** [comment]
@jaredpar I wanted to add a few more tests for long tuples. I've added those tests so I've marked this as completed.

**Comment by jaredpar** [comment]
@agocke thanks!

**Comment by agocke** [comment]
All items are completed.

**Comment by jaredpar** [comment]
Where is the VB bug?  This is only complete for C# at the moment.

**Comment by jcouv** [comment]
There is still a TODO in the code referencing this issue:

```C#
   private static bool AddNames(TypeSymbol type, ArrayBuilder<string> namesBuilder)
            {
                if (type.IsTupleType)
                {
                    if (type.TupleElementNames.IsDefaultOrEmpty)
                    {
                        // If none of the tuple elements have names, put
                        // null placeholders in.
                        // TODO(https://github.com/dotnet/roslyn/issues/12347):
                        // A possible optimization could be to emit an empty attribute
                        // if all the names are missing, but that has to be true
                        // recursively.
                        namesBuilder.AddMany(null, type.TupleElementTypes.Length);
                    }
                    else
                    {
                        namesBuilder.AddRange(type.TupleElementNames);
                    }
                }
                // Always recur into nested types
                return false;
            }
```

**Comment by VSadov** [comment]
I think my current changes will take care of the TODO. 
We will not emit the attribute at all if we have a type that does not contain tuples with field names.
