### ISSUE TITLE
VS2015-Update3: Struct implicit conversion with binary operators

### ISSUE THREAD

**Issue by zmj** [dotnet/roslyn#12345]
**Version Used**: VS 2015 update 3

**Steps to Reproduce**:

On update 3, expressions with | or & where one operand is EnumWrapper<T> and the other is T fail to compile.

In VS2015 ugprade 2 and earlier VS, the expression resolves by converting EnumWrapper<T> to T, performing the operation, and then converting the result to EnumWrapper<T> for the assignment.

This does compile if EnumWrapper is declared as class instead of struct.

```

    class EnumRepro
    {
        public static void Repro()
        {
            EnumWrapper<FlagsEnum> wrappedEnum = FlagsEnum.Foo;
            wrappedEnum |= FlagsEnum.Bar;
        }
    }
    
    public struct EnumWrapper<T>
        where T : struct
    {
        public T? Enum { get; private set; }

        public static implicit operator T? (EnumWrapper<T> safeEnum)
        {
            return safeEnum.Enum;
        }

        public static implicit operator EnumWrapper<T>(T source)
        {
            return new EnumWrapper<T> { Enum = source };
        }
    }

    [Flags]
    public enum FlagsEnum
    {
        None = 0,
        Foo = 1,
        Bar = 2,
    }
```

**Expected Behavior**:

Code above should compile.

**Actual Behavior**:

Operator |= cannot be applied to operands of type '...'.

**Comment by jcouv** [comment]
@zmj It seems this problem no longer repros. I've tested this locally and also on TryRolsyn with latest code from `master` branch.

[Attempted repro on TryRolsyn](http://tryroslyn.azurewebsites.net/#b:master/AQ4YwGwQwZx4CiA7ArgWwEoFMAOAnAewChRgBvE00HFAIwgEsxgYAXKVp4ANwIYBNg2fAQAUASkpVyU6aGToA6nig4cWPAB4AYtADmMBWgB8wAO4q1WfkeABeYLqgGjAOm0ECAbllzzl9RtUNGAAHwcnF2DXACEoPB8/AF9ZFNkaei42PBQwVkRg5VV1LQAVY19QMwALDSxgUuAALhZWHLzZCj8MxmZSgH4C9HJgPSxWL2B8Bm4OephxybTuul7Wji4GNBxehnyCEo4CPAbB0SMiqzLTGCgAMywjST8uv1A8cZQ8JBZ7x+ijIk5Ms5D0suxOMwtjsmHtgAcNEcThcAhpNOVRI0YAQvmAsM85K83sAPqwvj8kFgzEM0JcSujTGQafYWDi8HjgEkgdIUqQQSAANoAZQAnmwsGh3PoYABddKrLhYYKOaVGTqVEAAOQIlJZAAYADQaxyeFkARiNfjiJwcACZLaAkkA==)
