### ISSUE TITLE
Generic types inference

### ISSUE THREAD

**Issue by vbcodec** [dotnet/roslyn#12359]
Now 

```
         Public Sub S1(Of T1 As SomeBase)() 
         End Sub

         S1() ' Error
```

Should not be error, but interpreted as S1(Of SomeBase)()

**Comment by HaloFour** [comment]
Why should the compiler infer the generic type argument to the be the upper bound of the generic type parameter?  What if there is no constraint?  Are you saying that the inferred generic type argument should then be `System.Object`?  What if the generic type parameter constraint is `Structure`, or if the constraint is `{ ISomeInterface, New }`?  In both cases there is no suitable upper bound.  What about if there is a non-generic overload, would that disable the inference?

**Comment by vbcodec** [comment]
@HaloFour 
Good questions :)

Design team must answer these queastions. As for me:
- no constraint, no inference
- infered type is constraint
- for structures, no inference
- for interfaces, inference exist
- for non-generic overload, no inference

What do you mean 'upper bound' ? Constraints defines limit on lowest possible type, while highest (derived) is unlimited.

**Comment by HaloFour** [comment]
> Design team must answer these queastions.

Design team doesn't have to do anything.

Your spec would only apply inference in very limited scenarios.  I can't imagine that it's common enough to justify modification to the language spec, particularly if only to avoid typing a few extra characters.

> What do you mean 'upper bound' ?

An upper bounded generic constraint is one that requires that the generic type argument be more specific than the type of the constraint.  So with `where T : SomeObject` the upper boundary of the constraint is `SomeObject` and `T` must be more specific.  This is Java/Kotlin/Scala terminology and I don't disagree that it can be confusing.  Either way, I'm referring to the least specific type allowed by the constraint.

**Comment by gafter** [comment]
Issue moved to [dotnet/vblang #149](https://github.com/dotnet/vblang/issues/149) via [**ZenHub**](https://www.zenhub.com/)
