### ISSUE TITLE
Visual Studio 15 cannot build unsafe projects from UI.

### ISSUE THREAD

**Issue by prajaybasu** [dotnet/roslyn#12358]
**Version Used**: 15.0.25302.0 (Visual Studio 15 Enterprise Preview 2)

**Project Requirements**:
  Convert PCL Project with `unsafe` blocks to .NETStandard project.

**Expected Behavior**:
- Tick "Allow unsafe code" and compile.
- Respect buildOptions in project.json

**Actual Behavior**:
- Cannot tick "Allow unsafe code" from UI and cannot compile. The tickbox/element is greyed out.
- Does not respect buildOptions in project.json.

**Solution**:
- Build with `dotnet build` after adding `"buildOptions": {"allowUnsafe": true}` to the root of your project.json
- Add  `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>` to your .csproj file below MinimumVisualStudioVersion.

**Comment by davkean** [comment]
It's by design that it doesn't respect buildOptions. The fact that "Allow unsafe code" is disabled is an indicator that our type lookup is broken cc @rchande

**Comment by Pilchie** [comment]
I believe that allow unsafe works, but only if you have a reference to the `Microsoft.NETCore.Portable.Compatibility` package.  Is that right @rchande?

**Comment by rchande** [comment]
That's right. @prajaybasu Can you share your project.json?

**Comment by rchande** [comment]
@rchande Try to repro this and close if you can't.

**Comment by prajaybasu** [comment]
I didn't know that. Sorry though, can't test anything right now since I don't have VS 15 installed right now (and my sems going on).
But the IDE message was definitely unhelpful, and I think any projects using unsafe should have that package automatically added when converting from PCL, if not already.

**Comment by rchande** [comment]
@prajaybasu In Dev15 RC we automatically add the package when you convert.
