### ISSUE TITLE
Disable EnC in presence of C# 7 switch statement

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#12380]
The compiler should provide a helper method that checks the type of the switch expression and determines whether the switch has C# 6 semantics or C# 7 semantics. In the latter case we need to report a rude edit until we have proper EnC support.

**Comment by gafter** [comment]
Specifically, when the converted switch expression isn't a C# 6 switchable type.

**Comment by gafter** [comment]
@jaredpar @AlekseyTs @agocke FYI

**Comment by jaredpar** [comment]
Do we have a bug tracking ENC work being completed here in the future?

**Comment by jcouv** [comment]
With PR https://github.com/dotnet/roslyn/pull/13754, edits are blocked in any method that contains a switch statement with C# 7 semantics (before or after the edit).
