### ISSUE TITLE
Copying custom modifiers on types loses "tupleness" during the transformation

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#12389]
CustomModifierUtils.CopyTypeCustomModifiers saves and restores the "dynamicness" of the source type, but loses the "tupleness."

**Comment by gafter** [comment]
@agocke Can you distill that into a test case?

**Comment by agocke** [comment]
@gafter I left a TODO in the code where the issue is. I talked to @jcouv about it and I think the problem is understood. If there's any confusion when someone actually starts working on the bug I'd be happy to make some kind of test case.

**Comment by jcouv** [comment]
I'm not 100% clear how to trigger this, as my understanding of custom modifiers is limited. But I think Andy had the same problem. 
This is probably the most details we can put in the bug for now.

**Comment by agocke** [comment]
@jcouv I think the test case will require custom modifiers to be constructed in IL and then passed through to the compiler as metadata. I admit I don't know how to write this offhand, though.

**Comment by jcouv** [comment]
This was fixed in https://github.com/dotnet/roslyn/commit/f8bda451c8f3c426cf62872986a2ad49f5c95acb
