### ISSUE TITLE
SyntaxGenerator adds unneeded parentheses, which the simplifier fails to remove

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#12387]
**Version Used**: 
master branch at d04f1d6a512f5586912a7badcecf486c3f955fa7

**Steps to Reproduce**:
See the test at https://github.com/dotnet/roslyn-analyzers/pull/1065/files#diff-164ec4d88a0027d1f1e7d87262201e18R163:
```csharp
(IEquatable<S>)(this)
```

Code that produces this:
```csharp
generator.CastExpression(
  equatableType.Construct(typeSymbol),
  generator.ThisExpression())
```

**Expected Behavior**:
The parentheses around `this`, which were added by the `SyntaxGenerator`, are later removed by the simplifier.

**Actual Behavior**:
The simplifier does not remove the parentheses around `this`.

**Comment by balajikris** [comment]
thanks for the fix @bkoelman :) :+1:
