### ISSUE TITLE
Language support for the decorator design pattern

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [dotnet/roslyn#124]
Not sure if this one is worthy here, or even it this one could be useful. I mostly use decorators in favor of aggregation rather than inheritance. And there are situations when most of the methods, implemented from the interface, are simply delegated methods. Such methods can be easily generated with a compiler. This is more significant when the implemented interface is heavy and has a bunch of methods. It would be nice if it's allowed to implement necessary methods only, and let the compiler generate the rest of them. Let's say:

    public interface IFoo {
        int Do1();
        int Do2();
        int Do3();
        int Do4();
        int Do5();
        int Do6();
        int Do7();
    }
    
                                // +--- whatever nice thingy to denote a decorator
                                // V    decoratee must be an instance of IFoo
    public sealed class Bar : IFoo for decoratee {
    
        // if we need a private constructor
        private Bar(IFoo decoratee) {
            this.decoratee = decoratee;
        }
    
        // ... and a factory method
        public static IFoo Bar(IFoo decoratee) {
            return new Bar(decoratee);
        }
    
        // then just decorate what's needed
        public int Do4() {
            Console.WriteLine("Do4() is decorated");
            return decoratee.Do4();
        }
    
        // the rest, Do1--Do3 and Do5--Do7 are automatically generated
    
    }

UPDATE Feb 3, 2016

Kotlin supports the same feature with slightly different syntax: https://kotlinlang.org/docs/reference/delegation.html

**Comment by MadsTorgersen** [comment]
We recognize that the scenario has some merit, and we have looked at similar proposals before.

We are concerned about a number of things, not least the amount of code the compiler would implicitly generate.

If you are comfortable generating that amount of code, source generators #5561 may emerge as a useful approach in a future release.

**Comment by lyubomyr-shaydariv** [comment]
@MadsTorgersen do I understand it right: having no such a code injector will make code uncompilable?
