### ISSUE TITLE
Formatter inserts spaces instead of tabs after incomplete if

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1240]
Source (entire document, with tabs rather than spaces):

```C#
class C {
	C() {
		if ()
	}
```

Formatting the document will replace the tab in the last line with spaces.

**Comment by SLaks** [comment]
This seems to happen on any line that follows a line missing a semicolon

**Comment by Pilchie** [comment]
This appears to be the same issue as https://connect.microsoft.com/VisualStudio/feedback/details/950651/incorrect-changed-formatting-of-spaces-tabs-for-the-next-code-row-after-pasting-coding.  Given that that report is older, let's continue to use that for tracking.

**Comment by SLaks** [comment]
I don't have access to that URL.

**Comment by Pilchie** [comment]
Okay, then we can track it twice, it's not the end of the world :smile:

**Comment by Pilchie** [comment]
@SLaks were you able to see the URL above now that you cleared your cookies?

**Comment by SLaks** [comment]
Yes

**Comment by Pilchie** [comment]
Okay, let's use the connect bug to track this then.
