### ISSUE TITLE
SyntaxTokenExtensions.IsWord is inefficient

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#12421]
The implementation of [`SyntaxTokenExtensions.IsWord`](https://github.com/dotnet/roslyn/blob/1ccc08dc3006342822f4bcd4f9cde8230c117943/src/Workspaces/CSharp/Portable/Extensions/SyntaxTokenExtensions.cs#L77) could do with some tuning around allocations:

```
private static bool IsWord(SyntaxToken token)
{
    return new CSharpSyntaxFactsService().IsWord(token);
}
```

Just typing up a simple method declaration in C# I got nearly 2500 breakpoint hits on this method, and VB has a [similar implementation](https://github.com/dotnet/roslyn/blob/1ccc08dc3006342822f4bcd4f9cde8230c117943/src/Workspaces/VisualBasic/Portable/Extensions/SyntaxTokenExtensions.vb#L242).

**Comment by AdamSpeight2008** [comment]
Think that these could be provided via a shared static readonly instance, rather than creating a new instance each time.

**Comment by AdamSpeight2008** [comment]
@lorcanmooney Do you want to do the C# implementation?

**Comment by lorcanmooney** [comment]
> Think that these could be provided via a shared static readonly instance...

That's certainly the easiest fix, though I wonder why this needs to go through _any_ instance. If you follow the calls, they all end up in the language-specific `SyntaxFacts` helpers. It should be possible to go straight to the source.

If the team approves your PR, I'll fix up the C# side similarly.
