### ISSUE TITLE
Add Option type to the BCL

### ISSUE THREAD

**Issue by bordoley** [dotnet/roslyn#1242]
C# lacks type safe semantics to express an optional value. This results in APIs which return null in order to express the lack of a result value. The negative impacts of null pointers are well documented, and an alternative already exists in F# in the form of FSharpOption. It would be useful to extend the BCL to natively support an Option type, preferably in a compatible fashion with the existing F# option type.

**Comment by ErikSchierboom** [comment]
I would love an option type. Although the base libraries would not be able to change their type signatures, new methods would be able to use it. Add-in some extension methods to convert a nullable value to an option type, and you suddenly get a lot of the benefits of option types without much trouble.

**Comment by gafter** [comment]
The Roslyn project is not the right place to make BCL requests. You should either suggest this at https://github.com/dotnet/corefx or https://github.com/dotnet/coreclr (or perhaps both).
