### ISSUE TITLE
Upgrading Analyzer Nuget packages and it doesnt work anymore

### ISSUE THREAD

**Issue by OzieGamma** [dotnet/roslyn#12425]
**Version Used**: 
- Visual Studio 2015 Update 3

```
  <package id="Microsoft.CodeAnalysis.Analyzers" version="1.1.0" targetFramework="portable45-net45+win8" />
  <package id="Microsoft.CodeAnalysis.Common" version="1.3.2" targetFramework="portable45-net45+win8" />
  <package id="Microsoft.CodeAnalysis.CSharp" version="1.3.2" targetFramework="portable45-net45+win8" />
  <package id="Microsoft.CodeAnalysis.CSharp.Workspaces" version="1.3.2" targetFramework="portable45-net45+win8" />
  <package id="Microsoft.CodeAnalysis.Workspaces.Common" version="1.3.2" targetFramework="portable45-net45+win8" />
  <package id="Microsoft.Composition" version="1.0.30" targetFramework="portable45-net45+win8" />
  <package id="NuGet.CommandLine" version="3.4.3" targetFramework="portable45-net45+win8" developmentDependency="true" />
  <package id="System.Collections" version="4.0.11" targetFramework="portable45-net45+win8" />
  <package id="System.Collections.Immutable" version="1.2.0" targetFramework="portable45-net45+win8" />
  <package id="System.Diagnostics.Debug" version="4.0.11" targetFramework="portable45-net45+win8" />
  <package id="System.Globalization" version="4.0.11" targetFramework="portable45-net45+win8" />
  <package id="System.Linq" version="4.1.0" targetFramework="portable45-net45+win8" />
  <package id="System.Reflection.Metadata" version="1.3.0" targetFramework="portable45-net45+win8" />
  <package id="System.Resources.ResourceManager" version="4.0.1" targetFramework="portable45-net45+win8" />
  <package id="System.Runtime" version="4.1.0" targetFramework="portable45-net45+win8" />
  <package id="System.Runtime.Extensions" version="4.1.0" targetFramework="portable45-net45+win8" />
  <package id="System.Threading" version="4.0.11" targetFramework="portable45-net45+win8" />
```

**Steps to Reproduce**:

1. Create a new Analyzer + CodeFix project 
2. Open Nuget
3. Update all Nuget packages

**Expected Behavior**:
It should work

**Actual Behavior**:
For some reason, when I launch the .vsix it doens't work. No idea why, don't know in what direction to look. Compilation is successful, it launches the VS dev instance. The dignostics are not detected (the default one making Program all caps) though.

**Comment by tanveerbadar** [comment]
Could you check if something like the symptoms I am encountering #12484 happened to you?

My workflow does not require me to use vsix, but it is worth a shot. If my vsix also fails, I'll update you about it.

**Comment by tanveerbadar** [comment]
Same outcome as yours. Silent failure and refactoring is not being offered. There are no exceptions raised for VSIX in either instance of VS. 

I am going to enable activity logging shortly, looks like some assembly loading failure to me. My second suspicion (since I am seeing weird failure in command line runs too) is the recently released VS 2015 Update 3 KB 3165756 Patch.

**Comment by OzieGamma** [comment]
I am going to try upgrading slowly and just use the most recent version that works.

**Comment by mavasani** [comment]
I tried your repro and get the below AD0001 diagnostic after upgrading all NuGet packages:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD1000	An instance of analyzer Analyzer1.Analyzer1Analyzer cannot be created from C:\USERS\MAVASANI\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0ROSLYN\EXTENSIONS\MAVASANI\ANALYZER1\1.0\Analyzer1.dll: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..			1	Active
```

**Workaround**: Downgrading System.Collections.Immutable to 1.1.37 (the version that latest Microsoft.CodeAnalysis packages are built against), ensures the analyzer starts working again.

Underlying issue about ths scenario not working with 1.2.0 System.Collections.Immutable is tracked by https://github.com/dotnet/roslyn/issues/12247
