### ISSUE TITLE
[vb] Check Feature Flag.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#12422]
Currently the checking of feature is just based on the language version used for the feature.
If you're are developing a new feature, it may not yet have an "official" language version.

We can pass the feature via command line argument `/feature:foo`, which put it into `ParseOptions.Features`. Yet it isn't check for in `CheckFeatureAvailability` functions.
[Source](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Parser/Parser.vb,6084)

The pull request #12277, will modify this to also check `Features`.

**Comment by gafter** [comment]
We don't usually entertain compiler-internal API requests.

**Comment by AdamSpeight2008** [comment]
Is this one being entertained?

**Comment by gafter** [comment]
I don't know anyone who is championing this issue.

**Comment by AdamSpeight2008** [comment]
coffee call for the vb posse @AnthonyDGreen @ljw1004

**Comment by ljw1004** [comment]
Honestly, I've never liked the feature flag. If you're developing a new feature in a fork of Roslyn, then I think your fork should have your feature turned on always. When a user installs your VSIX, that action is an affirmation that they want the feature, and they shouldn't have to use an additional feature flag.

**Comment by AnthonyDGreen** [comment]
Certainly for getting your feature out into people's hands to play with I agree with @ljw1004. Feature flags just add an extra burden to people testing things and we shouldn't invest much into the flags until we're going to put them in an official release of the compiler.

Think of it this way - there is only one version of the language supported by the compiler. That is the latest version. It's an _extra_ on top of your feature that the /langversion: flag reports an error if your feature is used. One doesn't opt-in to features, they opt-out. And that opt-out mechanism doesn't matter until that feature is going to be released in Visual Studio.
