### ISSUE TITLE
[Infrastructure] Push To PR should cancel in-flight Checks.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#12423]
Previously when pushing to a pull request would cancel currently in flight PR checks.
It doesn't seem to be doing that now.

**Comment by jasonmalinowski** [comment]
@tannergooding I believe we got an updated version of the Jenkins plugin that does this again?

**Comment by tannergooding** [comment]
Yes, we just need to modify the groovy script to enable it.

**Comment by jasonmalinowski** [comment]
@tannergooding Is there documentation somewhere for how to do that?

**Comment by tannergooding** [comment]
Tagging @mmitche 

There is documentation in Jenkins 2.0 if you have the right plugins installed, I'll see if I can pull it up...

**Comment by mmitche** [comment]
We have this ability already, though it is disabled (i could change this though).  It was shot down by @jaredpar as some team members use the current behavior to their advantage.

**Comment by jasonmalinowski** [comment]
@jaredpar what was the scenario to leave this as is?

**Comment by AdamSpeight2008** [comment]
Is possible to restrict it external contributors?

**Comment by jasonmalinowski** [comment]
@AdamSpeight2008 I don't see why we'd do that. If it's useful for us it's useful for you too, or vice versa.

**Comment by AdamSpeight2008** [comment]
If some team members use the current behaviour (none cancelling), for their advantage, what is it?
Or a @dotnet-bot command to cancel?

**Comment by mmitche** [comment]
It's not currently possible to restrict (or cancel, though I like that option. could be implemented).

@jasonmalinowski pushing a bunch of commits and then looking the results of each run.

**Comment by jaredpar** [comment]
@jasonmalinowski it's was emphatically requested by @CyrusNajmabadi

**Comment by mmitche** [comment]
i'll put cancellation on the backlog

**Comment by jaredpar** [comment]
My stance on the subject is that I'd prefer cancellation of previous on push as the *default*.  Perhaps I way I can state opt out on a given PR.

**Comment by CyrusNajmabadi** [comment]
>  Perhaps I way I can state opt out on a given PR.

Yes, please make sure we can opt-out.

My development model is to continually push every change to github.  it's not uncommon for me to push dozens or hundreds of commits.  I depend on Jenkins being able to tell me where things went wrong in order to track down issues that i've added.  I absolutely want each and every push to be checked.

About hte only optimization that would work for me would be that if a commit passes all checks, then any previous commits that are still running could be cancelled.  However, that's likely not going to happen much of the time.  It'll be rare that a later push will complete before previous pushes finish.

**Comment by mmitche** [comment]
@CyrusNajmabadi How do you typically find results of runs after a new commit is pushed (the details link will only point to the latest)

**Comment by CyrusNajmabadi** [comment]
i just hover over the result glyph.  Lke here: https://github.com/dotnet/roslyn/pull/13927

I can click on the glyph and see:

![image](https://cloud.githubusercontent.com/assets/4564579/18728883/28e51e26-8004-11e6-947f-06446124aa2a.png)

So i can get to the results i need.

**Comment by mmitche** [comment]
Oh nice, yeah forgot that view would show you the info.

**Comment by jasonmalinowski** [comment]
Is this configurable then (or can be it made to be) by user? I'm sympathetic to both @CyrusNajmabadi's reasonable workflow, and also the poor machines doing work they don't need to do for the rest of us. :smile:
