### ISSUE TITLE
[Proposal] Static abstract members

### ISSUE THREAD

**Issue by UnoSD** [dotnet/roslyn#12429]
Please consider adding the following language feature:

```
abstract class Base
{
    public static abstract string Something { get; }
}

class Derived1 : Base
{
    public static string Something => "Derived";
}

class Derived2 : Base { } // Compiler error.

Base.Something // Compiler error.

Derived.Something // OK.

void Something<T>() where T : Base { T.Something; // OK. }
```

A common pattern is to use Flyweight in this fashion:

```
class FlyweightFactory
{
    Dictionary<KeyType, Flyweight> _flyweights;
    public GetFlyweight(KeyType key) => _flyweights[key];
}
```

When it comes to populating the dictionary, in many cases the flyweight concrete classes have a unique key corresponding to their types. If we want to enforce the presence of the key on the sub types, we can define an abstract property/method on the base flyweight; but this means we have to create an instance only to get a constant value. On the other hand, we could use attributes (which are more fit for purpose), but there is no way to enforce an attribute.

The abstract static would solve this problem.

Or, as an alternative, an abstract attribute which must be overridden by the sub types.

**Comment by svick** [comment]
This is very similar to another proposal, static interfaces: https://github.com/dotnet/roslyn/issues/2204.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #809](https://github.com/dotnet/csharplang/issues/809) via [**ZenHub**](https://www.zenhub.com/)
