### ISSUE TITLE
Split MS.CA.Workspaces.Common nuget package into separate packages for desktop and portable

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#12444]
1. The MS.CA.Workspaces.Common nuget package depends currently identifies the target framework as net45 for both MS.CA.Workspaces.dll and MS.CA.Workspaces.Desktop.dll.

2. MS.CA.Workspaces.Desktop.dll was recently changed to target netfx 4.6. MS.CA.Workspaces.dll on the other hand still targets netfx 4.5.2.

3. This causes the following build warning to be reported whenever a reference to one of the following nuget packages is added in a project that targets netfx 4.5.2 (which is the default for projects created using VS) -

```
MS.CA
MS.CA.CSharp.Features
MS.CA.CSharp.Workspaces
MS.CA.Features
MS.CA.VisualBasic.Features
MS.CA.VB.Workspaces
MS.CA.Workspaces.Common
```
```
1>------ Rebuild All started: Project: HelloWorld, Configuration: Debug x86 ------
1>C:\Program Files (x86)\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "Microsoft.CodeAnalysis.Workspaces.Desktop, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.6" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".
1>  HelloWorld -> C:\Users\*\AppData\Local\Temp\NugetTest\475cc757-9db6-4e1d-aec1-754e652e2127\bin\Debug\HelloWorld.exe
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

The current **workaround** to avoid this warning is to bump the project's target framework version to v4.6.

4. I tried bumping up target framework requirement for MS.CA.Workspaces.dll and MS.CA.Workspaces.Desktop.dll to net46 in PR #12415. But this has the **undesirable side effect** of excluding MS.CA.Workspaces.Desktop.dll when the package is installed in a project targeting 4.5.2 (and including it for projects targeting 4.6) as I described in [this comment](https://github.com/dotnet/roslyn/pull/12415/files#r70204321)

So the options we have at this point are -

- A. Split the MS.CA.Workspaces.Common into different packages for Desktop v/s Portable as @jasonmalinowski  suggested [here](https://github.com/jasonmalinowski). I am not sure whether that will be easy to do - since that probably also means we have to split up the other packages above that depend on this package. Plus this will also impact our shipping Roslyn SDK templates. (We will need to ship new templates for 2.0 to reference the new packages + users who have existing analyzer / code refactoring projects created using the 1.0 templates that reference the old workspace package won't be able to successfully update nuget packages to target 2.0.)

- B. Revert the original change that moved MS.CA.Workspaces.Desktop.dll to netfx 4.6. 

- C. Also bump the portable MS.CA.Workspaces.dll's target framework to netfx 4.6 (`portable-net46+win8`) in MS.CA.Workspaces.Common. so that we can make this nuget package not installable on projects targeting netfx 4.5.2. This would avoid the problem described in 4 above. It is not clear whether something like `portable-net46+win8` exists yet though.

**Comment by shyamnamboodiripad** [comment]
FYI @jasonmalinowski @Pilchie I am hoping your team can drive the appropriate changes that are required for this. 

It would be great if we could fix this for Preview 4.

**Comment by tmat** [comment]
I think we should rename MS.CA.Workspaces.Destop to MS.CA.MSBuild. It seems that it mostly contains msbuild related stuff. Once Msbuild is portable this can also be portable.

**Comment by jmarolf** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/14249

**Comment by Pilchie** [comment]
Ah, we didn't split it, but we no longer have the behavior where you can install it on a lower framework and get just the portable surface area?

Tagging @jasonmalinowski and @jinujoseph as well.

**Comment by jmarolf** [comment]
@Pilchie since the move to netstandard we have no portable surface area.

**Comment by jmarolf** [comment]
That is to say if you have a netstandard1.3 libray, you get the netstandard1.3 surface area.  If you have a PCL that targets something else, there is nothing for you to target.

**Comment by Pilchie** [comment]
Sure - but the root customer issue that this was filed to address is that if you had a desktop 4.5 app and referenced the package, you would get some things, but not `MSBuildWorkspace`, but if you targeted 4.6, you would get `MSBuildWorkspace`.  This happened because the portable directory supported 4.5, so NuGet would choose assets from there, when the net46 directory didn't apply.

I presume that this no longer happens because there is no version of desktop that supports .netstandard 1.3 below 4.6?

**Comment by jmarolf** [comment]
Correct, in 2.0 you will not be able to use 4.5.2 at all.  All of our assemblies depend on 4.6
