### ISSUE TITLE
C# Interactive Window with internals

### ISSUE THREAD

**Issue by ZeBobo5** [dotnet/roslyn#12450]
How could you have access to our internal class of my assembly in C# Interactive Window ?

I tried with the following assembly attribute, but I don't know which assembly to reference:
`[assembly: InternalsVisibleTo("...")]`

Thanks

**Comment by aelij** [comment]
The interactive window (or, rather, Roslyn's Scripting API) generates a new assembly with a different name for every submission. For example, note the different suffixes `1-1` and `1-2` with these two consecutive submissions:
```
> System.Reflection.Assembly.GetExecutingAssembly().FullName
"ℛ*5c81709c-d79a-42fc-83db-6e0af081c26b#1-1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"
> System.Reflection.Assembly.GetExecutingAssembly().FullName
"ℛ*5c81709c-d79a-42fc-83db-6e0af081c26b#1-2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"
```
So currently I don't believe it's possible. For the time being, you could use [ReflectionMagic](https://blogs.msdn.microsoft.com/davidebb/2010/01/18/use-c-4-0-dynamic-to-drastically-simplify-your-private-reflection-code/) as a workaround.

**Comment by tmat** [comment]
We do have a work item on a backlog to introduce ```#r! "myassembly.dll"``` that allows you to add a reference to an assembly and skip visibility checks at all use sites accessing internal members of that assembly.

**Comment by tmat** [comment]
Related: https://github.com/dotnet/roslyn/issues/6748
