### ISSUE TITLE
Project targeting netcoreapp1.0 isn't recognized as netstandard targeting

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#12458]
**Version Used**: Visual Studio 2015 Update 3 Microupdate 3.1

**Steps to Reproduce**:
1. Open Roslyn.sln from 423afea10482f2231a30f0e50aacfdb17c37fa80
2. Look at the error list

**Expected Behavior**: I don't see any warnings.

**Actual Behavior**: I get warnings like:

> Unable to add a reference to project 'VisualBasicSyntaxGenerator'. The targets of Portable Library project 'VisualBasicSyntaxGenerator' are not the same or compatible with the targets of the current Portable Library project.

**Comment by Pilchie** [comment]
@rchande I don't see the warnings in Roslyn anymore - did we explicitly fix this?

**Comment by Pilchie** [comment]
Ping?

**Comment by rchande** [comment]
@Pilchie I don't remember fixing this and I also can't find any pull requests or commits in VSO that suggest that we did.

**Comment by jasonmalinowski** [comment]
Did we work around it, either intentionally or by accident?

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard any more reports of this.
