### ISSUE TITLE
SymbolFinder Optimizations

### ISSUE THREAD

**Issue by tanveerbadar** [dotnet/roslyn#12453]
This is more of a question rather than an issue with SymbolFinder. Consider the following simple class

class A
{
      private void f( )
      {
      }
}

When doing a FindReferencesAsync on f, is it guaranteed that SymbolFinder is intelligent enough to limit scope to the containing document only? Or to a finite set of documents in the same project if A was partial? Are similar optimizations implemented for other cases I could come up with?

Lastly, is GitHub the right place to ask these questions or should I switch to stackoverflow?

**Comment by jmarolf** [comment]
Even though f is private, we do not limit the search scope in this way.  Today if you have code like:
```C#
public class Class1
{
    static void Main(string[] args)
    {
        var a = new A();
        a.f();
    }
}

class A
{
    private void f()
    {
    }
}
```

We will still list `a.f();` as a reference.  It just happens to be a reference that is not allowed by accessibility rules.  

If you want to limit the search scope, you can pass in a set of documents and `SymbolFinder` will only look at types and metadata referenced from those files.  Finding references is quite possibly *the* most expensive call you can make in the roslyn API.  We use a [bloom filter](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Shared/Utilities/BloomFilter.cs) and [caching](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/IncrementalCaches/SymbolTreeInfoIncrementalAnalyzerProvider.cs,123) to try and speed things up, but you will still need to realize a lot of symbols and that requires compilation.  A references search at the solution scope is nearly equivalent to compiling the solution.

**Comment by tanveerbadar** [comment]
``Thanks for the quick reply. 

I am writing a bunch of automated code cleanup utilities which would greatly benefit by doing these optimizations. For now, I'll add them to my codebase.

**Comment by Pilchie** [comment]
Also tagging @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
@jmarolf is correct.  Because of error tolerance we will often search beyond what the language would normally allow.  We do, however, limit searching in some situations.  For examples, for locals we only search the containing symbol, greatly speeding up performance.   This is also because there is no way externally to reference those locals, so searching elsewhere would not ever yield additional results (even in error situations).
