### ISSUE TITLE
Ref-returning var method should be invokable with workaround

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#12468]
Although `var (x, y) = 42;` is always parsed as a deconstruction, the user could use `@var` or parenthesized expressions to disambiguate.
But in the following unittest, the parsing of those invocations still incorrectly finds deconstruction declarations...

``` C#
  public void RefReturningVarInvocation2()
        {
            string source = @"
class C
{
    static int i;

    static void Main()
    {
        int x = 0, y = 0;
        @var(x, y) = 42; // parsed as invocation
        System.Console.Write(i + "" "");
        (var(x, y)) = 43; // parsed as invocation
        System.Console.Write(i + "" "");
        (var(x, y) = 44); // parsed as invocation
        System.Console.Write(i);
    }
    static ref int var(int a, int b) { return ref i; }
}
";
            var comp = CompileAndVerify(source, expectedOutput: "42 43 44");
            comp.VerifyDiagnostics();
        }
```

**Comment by jaredpar** [comment]
Didn't we decide at LDM to not allow this?

**Comment by jcouv** [comment]
No. I filled this issue right after LDM discussion.
`var(x, y) = 1;` will always be parsed as deconstruction. But if you use `@` or parenthesize properly, you should be able to invoke a ref-returning `var` method.

**Comment by jcouv** [comment]
Following discussion with @gafter, we need to confirm with LDM whether `@var(x, y) = e;` should be seen as an invocation. He thought it should not (`@var` and `var` should mean the same thing, because var is not a keyword or contextual keyword).

We also tried the other workaround (putting parens around invocation) and it parses properly after https://github.com/dotnet/roslyn/pull/15548 (although it generates PE verification error).

**Comment by gafter** [comment]
At the LDM today we recognized that `var`, `@var`, and even versions with unicode escapes are all ways to spell the pseudo-keyword `var` and behave the same. So escaping using `@` won't work. Too bad. But parenthesizing will work.

**Comment by jcouv** [comment]
This was fixed by Neal's recent parsing work. I'll add a test.

**Comment by jcouv** [comment]
Added test to verify resolution. See https://github.com/dotnet/roslyn/pull/15922
