### ISSUE TITLE
[Test Failure] No identified problem in microbuild_prtest on PR #12464

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#12466]
PR: [#12464](https://github.com/dotnet/roslyn/pull/12464) *Run the compiler server at BelowNormal priority so it doesn't interfere with other processes when saturating the CPU.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/microbuild_prtest/111/

**Issue 1: No identified problem**
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.

**Comment by jaredpar** [comment]
Fixed with 5e6bf7d1e7a7750775a768b792f3a969ccbfd9bb
