### ISSUE TITLE
Squiggles are on the wrong span for out parameter unassigned error

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#12467]
We select the wrong span for this error: "out parameter must be assigned to before leaves the current method"...

This causes:
![image](https://cloud.githubusercontent.com/assets/1402694/16786289/8ae4a8b0-4848-11e6-9db3-974b3aa89fcb.png)

which makes it really hard to finish writing my method when I have to look through all the squiggles.

**Comment by DustinCampbell** [comment]
It's not terribly clear in @kuhlenh's example, but this is a local function.
