### ISSUE TITLE
Don't do as much work if all tests pass.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#12474]
I noticed the following extra work being done in this PR:
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/1111/console

Note that we got:
16:52:48   All tests passed

Then we spent a minute until we got here:
16:53:46 [xUnit] [INFO] - Converting 'D:\j\workspace\windows_debug---09a07fba\Binaries\Debug\xUnitResults\Roslyn.VisualStudio.Services.UnitTests.dll.2.xml' .

If everything passed, do we need to do all that XML conversion?  This would help shave off a minute (roughly 5%) from our unit test running time in success cases.

**Comment by AdamSpeight2008** [comment]
Don't the success cases contain pert data, like time taken.

**Comment by jasonmalinowski** [comment]
Is this converting to the TFS format, that we don't need anymore now that VSO speaks the xunit format natively?

**Comment by CyrusNajmabadi** [comment]
> Don't the success cases contain pert data, like time taken.

Possibly.  But then why not just capture the actual dumped data, and avoid spending a minute converting it into another form?

**Comment by tannergooding** [comment]
This is converting it to the Jenkins supported format so that Jenkins can display the data and track pass/fail/flakiness of tests

**Comment by AdamSpeight2008** [comment]
Thought Jenkins already supported xUnit?

**Comment by tannergooding** [comment]
Yes, but It still has to parse the output, which takes time for 60,000 tests

**Comment by CyrusNajmabadi** [comment]
But why parse the output when xunit already said everything passed?  We could just hardcore the data file that Jenkins needs

On Jul 13, 2016 9:22 AM, Tanner Gooding <notifications@github.com> wrote:

Yes, but It still has to parse the output, which takes time for 60,000 tests

**Comment by tannergooding** [comment]
Because Jenkins will then lose information about new tests, tests which were skipped, and tests which were removed.

**Comment by CyrusNajmabadi** [comment]
Is that important information?  Where is that even surfaced?

**Comment by tannergooding** [comment]
In the job test results: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_release_unit32/245/testReport/

And yes, it helps us track failures and when/where a test was disabled/skipped (whether due to explicit action or some flakiness in the runner/etc).
