### ISSUE TITLE
System.InvalidOperationException at Microsoft.CodeAnalysis.CSharp.CodeFixes.AddImport.CSharpAddImportCodeFixProvider.GetDescription

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#1247]
Got the below exception while trying to apply a quick fix to add using. I don't have a concrete repro or a dump as the exception was logged in the activity log.

System.InvalidOperationException: This program location is thought to be unreachable.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CSharp.CodeFixes.AddImport.CSharpAddImportCodeFixProvider.GetDescription(INamespaceOrTypeSymbol namespaceSymbol, SemanticModel semanticModel, SyntaxNode contextNode)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider.&lt;RegisterCodeFixesAsync&gt;d__16.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.&lt;&gt;c__DisplayClass12_1.&lt;&lt;AppendFixesAsync&gt;b__3&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.&lt;PerformFunctionAsync&gt;d__3`1.MoveNext()

**Comment by mavasani** [comment]
I just noticed that the file where I was applying the quick fix had static usings and after the fix was applied, the new using was added after the static usings, causing a squiggle for newly added using in the file:

using System;
using System.Globalization;
using System.IO;
using Microsoft.CodeAnalysis.CSharp.Test.Utilities;
using Microsoft.CodeAnalysis.Test.Utilities;
using Xunit;

using static Microsoft.CodeAnalysis.Test.Utilities.SharedResourceHelpers;
using static Microsoft.CodeAnalysis.DiagnosticExtensions;
`using Microsoft.CodeAnalysis.CommonDiagnosticAnalyzers; // this is the added using with error`

**Comment by srivatsn** [comment]
Looking at the [GetDescription method](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/CodeFixes/AddImport/CSharpAddImportCodeFixProvider.cs,6678aef164ef7d2e,references), it looks like we don't know why we would reach this place. @jmarolf, do you have any ideas when this could get hit. Otherwise, I'm not sure if this is actionalble without a repro or a dump.

**Comment by srivatsn** [comment]
Ah looks like our comments crossed midstream. using static is likely the missing case.

**Comment by mavasani** [comment]
Yes, and the type I did an add using for was a nested static type, i.e. CommonDiagnosticAnalyzers is actuall a static class, so the above added using should be "using static Microsoft.CodeAnalysis.CommonDiagnosticAnalyzers".

I wasn't able to repro the exception again though, even after restarting VS. The squiggle in the added using always shows up CTRL + DOT + ENTER

**Comment by jmarolf** [comment]
At the very least we should handle this case.  I suspect that the logic which determines if a using already exists does not take static into account.

**Comment by jmarolf** [comment]
Fixed with pull request #1302
