### ISSUE TITLE
PERF: CPU and allocation spike opening a large, generated file.

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#1248]
An internal user sent me a 2MB machine-generated C# file. When opening that file in VS, we see one core at full utilization for several minutes and many GB of allocations (I observed over 3GB of committed memory).

While this is undoubtedly an extreme case, we should use it to look for bottlenecks.

**Comment by pharring** [comment]
The file is at <internal FS>\public\pharring\DataContractSerializerHelper.g.cs

From an initial look at the trace, the bottleneck is in the semantic tagger.
From allocation analysis, it seems we're generating thousands of binding errors. Perhaps we should cap it at some limit and stop further semantic analysis.

**Comment by pharring** [comment]
Indeed, memory analysis of a snapshot indicates most of the memory is due to diagnostics (over a million of them). The file doesn't contain errors, but when opened stand-alone, outside the context of a project, there are missing types. It's generated code, and there are thousands of array initializers referencing missing types.

**Comment by pharring** [comment]
A quick experiment shows that we can keep a cap on the memory by limiting the maximum size of a DiagnosticBag. Semantic classification still takes several minutes to complete, but at least memory usage stays reasonable. However, @gafter points out that this would affect determinism since diagnostics are emitted in parallel. We might be able to do something special for array initializers, method bodies etc. where we know there is no parallelism.

**Comment by pharring** [comment]
For calls into GetSymbolInfo, we can use a "Null" DiagnosticBag for binding. This keeps a lid on the memory allocations for this scenario. I imagine it will also improve any analyzers that call GetSymbolInfo.

**Comment by pharring** [comment]
Given the risk analysis and the limited impact, now that I understand the bug and the potential fix, this can be moved to the 1.1 milestone.

**Comment by AdamSpeight2008** [comment]
Would I help to do a two stage approach?
Read first without diagnostics, so that the code can be quickly be displayed in the IDE
Then asynchronously rescan with diagnostics.

**Comment by pharring** [comment]
To fix this bug we don't need two stages. The diagnostics are going to be ignored anyway. The fix I have in mind doesn't improve the elapsed time much, unfortunately, but it does dramatically reduce the memory used.
To be clear, though, the file is displayed and syntactically classified. The user can interact with the file. What takes a long time is semantic classification and that's because, being a loose file, loaded outside the context of its originating project, so many types are missing. We spend most of our time trying to look for the missing symbols.

**Comment by mavasani** [comment]
Closing this out - we can address this when we get customer reports with traces/dump highlighting this issue.
