### ISSUE TITLE
Hide "Download the .NET Compiler Platform SDK" pseudo-project if SDK already installed

### ISSUE THREAD

**Issue by hickford** [dotnet/roslyn#12483]
I think Visual Studio should hide the "Download the .NET Compiler Platform SDK"  pseudo-project if you already have the SDK installed. It's confusing otherwise.

![image](https://cloud.githubusercontent.com/assets/105314/16798016/ec3c8896-48e1-11e6-8867-75aba164719f.png)

(I have version 1.3.0.60420 installed)

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #62](https://github.com/dotnet/roslyn-sdk/issues/62) via [**ZenHub**](https://www.zenhub.com/)
