### ISSUE TITLE
[Test Failure] Individual TAO Test Failure (AnalyzersNode) in windows_vsi_p0_open_prtest on PR #12096

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#12503]
PR: [#12096](https://github.com/dotnet/roslyn/pull/12096) *Completion helper work* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_open_prtest/242/

**2 Test Failures:**
AnalyzersNode.C# Analyzers Node
AnalyzersNode.VB Analyzers Node

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

AnalyzersNode.xml

**Comment by tannergooding** [comment]
I hope to have a fix for this sometime tomorrow.

**Comment by Pilchie** [comment]
Hit this again on http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/microupdate/job/windows_vsi_p0_open_prtest/31/ (for https://github.com/dotnet/roslyn/pull/12686)

**Comment by Pilchie** [comment]
Any update on this?

**Comment by ManishJayaswal** [comment]
@srivatsn does this need to be fixed in preview 4?

**Comment by Pilchie** [comment]
Hit again in http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p0_open_prtest/7/

**Comment by ManishJayaswal** [comment]
@tannergooding do you have a fix for this ( as per your comment above)?

**Comment by tannergooding** [comment]
No. I had gotten pulled off onto other work before I was able to complete this.

**Comment by ManishJayaswal** [comment]
Assigning to @srivatsn  for his team to investigate.

**Comment by mavasani** [comment]
This is failing often now, marking Urgency-Now

**Comment by mavasani** [comment]
This is fixed in master - please re-open if it fails again in master. The test is still flaky in other branches (running on Dev14), we should probably just disable it in those branches if it fails too often.
