### ISSUE TITLE
[Test Failure] Jenkins Remoting Error (+1 more) in windows_vsi_p3_open_prtest on PR #12096

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#12502]
PR: [#12096](https://github.com/dotnet/roslyn/pull/12096) *Completion helper work* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_open_prtest/248/

**Issue 1: Jenkins Remoting Error**
Java / Jenkins hit a remoting error that caused the build to fail.

**Issue 2: File operation failed**
There was an I/O error during the build. This could be caused by a hung process on the target machine, preventing it from cleaning up the workspace, or other issues, such as low disk space.

**Comment by tannergooding** [comment]
FYI. @mmitche, Jenkins IO failure when attempting to archive the xUnit artifacts for the test status page.

**Comment by mmitche** [comment]
@tannergooding Would you check out the log in C:\Jenkins on rbld-5?  I'm curious whether the Win32 socket exception keeps happening.  Don't restart the powershell/batch process.

**Comment by tannergooding** [comment]
`System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it <ipaddress>`

and then a bunch of

The remote server returned an error: (503) Server Unavailable.

**Comment by Pilchie** [comment]
What is happening here?  Is there anything actionable in this issue?
