### ISSUE TITLE
CS0165 when using null coalesce and out parameters in if statement

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#12514]
**Version Used**:  Microsoft Visual Studio Enterprise 2015 Version 14.0.25421.03 Update 3

**Steps to Reproduce**:

1. Attempt to compile the following source code:
```
using System.Collections.Generic;

namespace RoslynNullableOutReturns
{
	public static class DictionaryExtensions
	{
		static TValue GetValueOrDefault1<TKey, TValue>(this IDictionary<TKey, TValue> dictionary, TKey key)
		{
			TValue value;
			
			if (dictionary?.TryGetValue(key, out value) ?? false)
			{
				return value;
			}

			return default(TValue);
		}

		static TValue GetValueOrDefault2<TKey, TValue>(this IDictionary<TKey, TValue> dictionary, TKey key)
		{
			TValue value;

			var x = (dictionary != null) ? dictionary.TryGetValue(key, out value) : false;
			if (x)
			{
				return value;
			}

			return default(TValue);
		}

		static TValue GetValueOrDefault3<TKey, TValue>(this IDictionary<TKey, TValue> dictionary, TKey key)
		{
			TValue value;
			if (dictionary != null && dictionary.TryGetValue(key, out value))
			{
				return value;
			}

			return default(TValue);
		}
	}
}
``` 

**Expected Behavior**:
1. `GetValueOrDefault1` should have no errors.
2. `GetValueOrDefault2` could have error, could have no error. I have uncertain expectations here.
3. `GetValueOrDefault3` should have no errors.

**Actual Behavior**:
1. `GetValueOrDefault1` has error CS0165 `Use of unassigned local variable 'value'` on line 13.
2. `GetValueOrDefault2` has error CS0165 `Use of unassigned local variable 'value'` on line 26.
3. `GetValueOrDefault3` has no errors.

---

I would expect that the compiler can understand that there is no code path that gets to `return value;` where by `TryGetValue` has not been called, since it's only dealing with that and compile-time constants.

**Comment by HaloFour** [comment]
Those errors are appropriate.  In 1 and 2 you are performing conditional operations which can't guarantee that `dictionary.TryGetValue` is being called, which means that `value` is not definitely assigned.

**Comment by HaloFour** [comment]
To demonstrate in a simpler scenario which involves none of those extra operators/calls:

```cs
int i;
bool b = false;
if (b) {
    Console.WriteLine(i); // CS0165 here
}
```

**Comment by yaakov-h** [comment]
And yet I can do:

```
int i;
if (false) {
    Console.WriteLine(i); // CS0165 here
}
```

So when it's inline, the compiler understands the flow. When it's broken out into a variable, the compiler does not.

Which is why I had uncertain expectations for case 2, but I'd expect case 1 to compile.

(Yes, I know internally the compiler breaks out a null-conditional operation into a separate variable.)

**Comment by gafter** [comment]
Although you might like the compiler to do better here, the behavior is as specified for the `?.` operator and the `??` operator. The `??` operator does not specify any special behavior for _definitely-assigned-when-true_ and _definitely-assigned-when-false_ when its result happens to be of type `bool`.

**Comment by NickCraver** [comment]
For what it's worth, this trips me up every single time, and many refactoring tools as well. Would this  working as expected be considered for a future enhancement?

**Comment by gafter** [comment]
@NickCraver Good question. Language design questions are now taken at https://github.com/dotnet/csharplang

**Comment by jnm2** [comment]
Thanks @yaakov-h for pointing me here. I had opened https://github.com/dotnet/csharplang/issues/1195.
