### ISSUE TITLE
Possible Unit Test Improvements

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#12510]
Discussion of possible "improvements" to Unit Tests.

**Using InlineData**

@svick 

``` Csharp
[WorkItem(12427, "https://github.com/dotnet/roslyn/issues/12427")]
[Theory]
[InlineData("portable", DebugInformationFormat.PortablePdb)]
[InlineData("full", DebugInformationFormat.Pdb)]
[InlineData("pdbonly", DebugInformationFormat.Pdb)]
[InlineData("embedded", DebugInformationFormat.Embedded)]
public void DebugFlag(string value, DebugInformationFormat expected)
{
    VerifyQuotedValid("debug", value, expected, x => x.EmitOptions.DebugInformationFormat);
}
```

vs

``` csharp
[Fact]
public void DebugFlag()
{
    var list = new List<Tuple<string, DebugInformationFormat>>()
    {
        Tuple.Create("portable", DebugInformationFormat.PortablePdb),
        Tuple.Create("full", DebugInformationFormat.Pdb),
        Tuple.Create("pdbonly", DebugInformationFormat.Pdb),
        Tuple.Create("embedded", DebugInformationFormat.Embedded)
    };
    foreach (var tuple in list)
    {
        VerifyQuotedValid("debug", tuple.Item1, tuple.Item2, x => x.EmitOptions.DebugInformationFormat);
    }
 ]
```

---

**Feature Flags**

This provides the unit test (or tests) with a compiler with the required feature enabled.

``` csharp
[Requires.LanguageFeature( Feature.StringInterpolation )]
public void StringInterpolation_Tests(  )
{
}
```

---

**Langauge Version**

This provides the unit test (or tests) with a compiler with the required language version.

``` csharp
[Requires.LanguageVersion( CSharp7 )]
public void Foo()
{
}
```

---

**Use Multi-Line String Literals instead on XML-Literals** (#11315)

This one is VB.net specific, prior this language feature being implemented in the language.  XML Literals were often, and current are being used to provide a relatively easy alternative way to create a multi-line string, without concatenation. _Note: This will require carefully transformation due different escape sequences, and argument holes. As well as XML-Literals being white-space significance._ 

---

Are there other "improvements" you would like to see or have available for the Unit Tests?

**Comment by AdamSpeight2008** [comment]
**StringBuilder Pool**
If it is possible rather that initialising a new StringBuilder each time, to "pull" from a shared pool of instances.

**Comment by gafter** [comment]
This is a collection of independent suggestions. I think any one of them might be worth doing as a target of convenient opportunity (e.g. when it helps get something else done). I doubt we would aim to do them all at the same time.

**Comment by AdamSpeight2008** [comment]
@gafter  Add the `Up For Grabs` tag and maybe someone from the community may look at implementing some of them.

**Comment by tmat** [comment]
:-1: for using InlineData.

**Comment by AdamSpeight2008** [comment]
@tmat *"Is this just a case of who moved my cheese?"*

**Comment by tmat** [comment]
No. You haven't explained what are the benefits for the change. I only see disadvantages.

**Comment by AdamSpeight2008** [comment]
I've only just started convert a branch on mine over, and already removed a 100 lines of code.
Those `InlineData` can be testing parallel, so potential gains in total test execution time.
