### ISSUE TITLE
#endif statement is missing after processing a function.

### ISSUE THREAD

**Issue by happyhebaby** [dotnet/roslyn#12524]
**Version Used**: 1.2.0.0 and 1.3.1.0

**Steps to Reproduce**:
I have specific code processing each function(static or member) of a class using roslyn. I find a specific issue when roslyn finish the processing of the function, the last #endif statement is missing from the output, which looks to me like a bug. I suspect it also might happen with the last ending statement of a directive. Logically include some statement but missing others of a complete directive unit doesn't seem to be a correct behavior.

```
class Class2
{
    internal static string StaticFunc2(string s1)
    {
        try
        {
            Console.WriteLine("Class2.StaticFunc2");
            return "Class2.StaticFun2";
        }
```
# if DEBUG

```
        catch (Exception ex)
        {
            throw new Exception("#if debug");
        }
```
# else

```
        catch (Exception e)
        {
            throw new Exception("#else");
        }
```
# endif

```
    }
```

**Expected Behavior**:
# if DEBUG

```
        catch (Exception ex)
        {
            throw new Exception("#if debug");
        }
```
# else

```
        catch (Exception e)
        {
            throw new Exception("#else");
        }
```
# endif

```
    }
```

**Actual Behavior**:
# if DEBUG

```
        catch (Exception ex)
        {
            throw new Exception("#if debug");
        }
```
# else

```
        catch (Exception e)
        {
            throw new Exception("#else");
        }
    }
```

**Comment by svick** [comment]
In this case, the `#endif` is represented as leading trivia on the closing brace of the method. Based on https://github.com/dotnet/roslyn/issues/12136#issuecomment-232847448, your processing method creates a brand new closing brace token:

```c#
BlockSyntax newBody = curBody.Update(SyntaxFactory.Token(SyntaxKind.OpenBraceToken), newStatements,
                                     SyntaxFactory.Token(SyntaxKind.CloseBraceToken)).WithTrailingTrivia(curTrivia);
```

Instead of using `Update()` and manually having to properly copy both braces, you can use `WithStatements()`, which should fix this:

```c#
BlockSyntax newBody = curBody.WithStatements(newStatements);
```

**Comment by gafter** [comment]
@happyhebaby I suspect @svick is correct. If you want us to investigate please provide a self-contained repro.

**Comment by happyhebaby** [comment]
I confirm @svick suggestion works. However, I would like to argue that there should be multiple code pattern to result in same piece of code. As long as the syntax is correct, my code should also work. I don't have strong understanding of the roslyn engine, but it still looks like a bug to me.
It should be trivia to repro based on my provided code.
Thank you all!
