### ISSUE TITLE
Expression compiler unit tests fail when run locally

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#12539]
Running `msbuild /v:m /m BuildAndTest.proj` locally fails with errors in the VB and C# expression compiler unit tests:

```
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.VisualStudio.Debugger.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
```

**Comment by AdamSpeight2008** [comment]
Passes locally on mine, Check any folder / file permissions within your Roslyn repo folder, also check and antivirus software isn't blocking it.

**Comment by lorcanmooney** [comment]
Odd, this is still happening for me with the latest code in master after cleaning the repo and nuget packages. I'm seeing a bunch of package downgrades when running `restore`, including `Microsoft.VisualStudio.Debugger.Engine`...

```
Downloading NuGet 3.5.0-beta2
Deleting project.lock.json files
Deleted file - C:\Users\Lorcan\Documents\Projects\roslyn\src\project.lock.json
Restoring packages: Toolsets
WARNING: Detected package downgrade: Microsoft.Build.Framework from 0.0.0 to 0.1.0-preview-00005
 ToolsetPackages (>= 1.0.0) -> Roslyn.Build.Util (>= 0.9.4-portable) -> Microsoft.Build.Utilities.Core (>= 0.1.0-preview-00005) -> Microsoft.Build.Framework
 ToolsetPackages (>= 1.0.0) -> Roslyn.Build.Util (>= 0.9.4-portable) -> Microsoft.Build.Framework (>= 0.1.0-preview-00005)
Restoring packages: Toolsets (Dev14 VS SDK build tools)
Restoring packages: Toolsets (Dev15 VS SDK build tools)
Restoring packages: Roslyn SDK
Restoring packages: Samples
Restoring packages: Templates
Restoring packages: Roslyn (this may take some time)
WARNING: Detected package downgrade: Microsoft.VisualStudio.Debugger.Engine from 14.3.25421 to 14.3.25420
 BasicResultProvider.NetFX20 (>= 1.0.0) -> ResultProvider.NetFX20 (>= 1.0.0) -> Microsoft.VisualStudio.Debugger.Engine (>= 14.3.25421)
 BasicResultProvider.NetFX20 (>= 1.0.0) -> Microsoft.VisualStudio.Debugger.Engine (>= 14.3.25420)
WARNING: Detected package downgrade: Microsoft.VisualStudio.Debugger.Metadata from 14.3.25421 to 14.3.25420
 BasicResultProvider.NetFX20 (>= 1.0.0) -> ResultProvider.NetFX20 (>= 1.0.0) -> Microsoft.VisualStudio.Debugger.Metadata (>= 14.3.25421)
 BasicResultProvider.NetFX20 (>= 1.0.0) -> Microsoft.VisualStudio.Debugger.Metadata (>= 14.3.25420)
WARNING: Detected package downgrade: Microsoft.VisualStudio.Debugger.Engine from 14.3.25421 to 14.3.25420
 CSharpResultProvider.NetFX20 (>= 1.0.0) -> ResultProvider.NetFX20 (>= 1.0.0) -> Microsoft.VisualStudio.Debugger.Engine (>= 14.3.25421)
 CSharpResultProvider.NetFX20 (>= 1.0.0) -> Microsoft.VisualStudio.Debugger.Engine (>= 14.3.25420)
WARNING: Detected package downgrade: Microsoft.VisualStudio.Debugger.Metadata from 14.3.25421 to 14.3.25420
 CSharpResultProvider.NetFX20 (>= 1.0.0) -> ResultProvider.NetFX20 (>= 1.0.0) -> Microsoft.VisualStudio.Debugger.Metadata (>= 14.3.25421)
 CSharpResultProvider.NetFX20 (>= 1.0.0) -> Microsoft.VisualStudio.Debugger.Metadata (>= 14.3.25420)
WARNING: Detected package downgrade: Microsoft.Build.Framework from 0.0.0 to 0.1.0-preview-00005
 MSBuildTask (>= 1.0.0) -> Microsoft.Build.Tasks.Core (>= 0.1.0-preview-00005) -> Microsoft.Build.Framework
 MSBuildTask (>= 1.0.0) -> Microsoft.Build.Framework (>= 0.1.0-preview-00005)
WARNING: Detected package downgrade: Microsoft.Build.Framework from 0.0.0 to 0.1.0-preview-00005
 MSBuildTask (>= 1.0.0) -> Microsoft.Build.Utilities.Core (>= 0.1.0-preview-00005) -> Microsoft.Build.Framework
 MSBuildTask (>= 1.0.0) -> Microsoft.Build.Framework (>= 0.1.0-preview-00005)
```

...but I've no idea if it's relevant.

**Comment by AdamSpeight2008** [comment]
I also get those (not worried about them). Not sure but likely related to #12556

**Comment by AdamSpeight2008** [comment]
@lorcanmooney
Do still the package downgrades after doing `restore.cmd /clean`, then issue the build test command?

**Comment by lorcanmooney** [comment]
@AdamSpeight2008 Yup, still seeing this even after a `restore /clean`. I don't get as many downgrades though, so that _does_ seem unrelated.

**Comment by lorcanmooney** [comment]
```
sn -vf Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll is a delay-signed or test-signed assembly
```

`sn` also lists a bunch of Roslyn assemblies to skip verification. Maybe this should be on the list?

**Comment by Pilchie** [comment]
For Roslyn binaries that we build, we use "Public Signing", which shouldn't require running sn.  However, I'm guessing we put a delay signed version of that binary up on nuget to get unblocked.  We should replace it with a shipping (real-signed) version if there is one.

Tagging @KevinH-MS did you publish this package?

**Comment by KevinH-MS** [comment]
Shucks, it would appear that *everyone* I had test this had some sort of skip verification entry on their machines (including the VM I set up).  If I manually remove all skip verifications, I can repro on my machine.

We are referencing the *official* VSSDK package, but these aren't real implementation assemblies, so it's my guess that's why they aren't signed.

I'll see if I can come up with a short-term solution and talk to the VSSDK folks about whether they can OSS sign the reference assemblies (or something equivalent).

**Comment by AdamSpeight2008** [comment]
@KevinH-MS go get the  :squirrel:

**Comment by KevinH-MS** [comment]
This should be fixed if you fetch latest.  Thanks for your patience.

**Comment by AdamSpeight2008** [comment]
@KevinH-MS  Is this fixed on the Jenkins PR Build Servers?

**Comment by KevinH-MS** [comment]
Yes, it should be fixed everywhere (although it was never failing on the Jenkins PR servers, because those apparently have a skip verification entry).

Are you seeing a failure somewhere?

Thanks

**Comment by AdamSpeight2008** [comment]
I did, then did a second push to my PR on github, which seem to fix it.

**Comment by lorcanmooney** [comment]
That fixed it for me. Thanks @KevinH-MS!
