### ISSUE TITLE
[Test Failure] No identified problem in microbuild_prtest on PR #12529

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#12533]
PR: [#12529](https://github.com/dotnet/roslyn/pull/12529) *Always insert the insertion text, even when we can't resolve symbols.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/microbuild_prtest/243/

**Issue 1: No identified problem**
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.

**Comment by tannergooding** [comment]
@jaredpar:
```
D:\j\workspace\microbuild_pr---d013602c\src\Tools\MicroBuild\Build.proj(30,5): error MSB3073: The command "D:\j\workspace\microbuild_pr---d013602c\src\Tools\MicroBuild\..\..\..\Binaries\Release\SignRoslyn\SignRoslyn.exe -test -binariesPath "D:\j\workspace\microbuild_pr---d013602c\src\Tools\MicroBuild\..\..\..\Binaries\Release"" exited with code -532462766.
```

**Comment by jaredpar** [comment]
When PR tests fail we shoudn't just create a bug, we should actually look into the failure.  The default of creating a bug is asking me to investigate your change.
