### ISSUE TITLE
Roslyn Visual Studio Test Support vsix doesn't install/add redirects for Diagnostics binaries

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#12543]
**Version Used**: 
dev15-preview-4\release\20160713.13 on ML 25514.01
**Steps to Reproduce**:
1. Install Roslyn.VisualStudio.Test.Setup.vsix to the machine
2. If you check localappdata devenv.exe.config, redirects for Roslyn.Hosting.DIagnostics and MIcrosoft.Diagnostics.Runtime.dll should be present, and the binaries should be on the machine. They are not at the moment.

This is blocking standalone VSI tests as it impacts the WaitForWorkspace and Build actions. Workaround is to manually add redirects to the localappdata devenv.exe.config

**Comment by ManishJayaswal** [comment]
Assigning to @mavasani who is in in infrastructure swat team for next sprint.

**Comment by mavasani** [comment]
@mattscheffer Is this still an issue? We have all the VSI tests running fine on Dev15 Preview3 now. Please re-open if this is still blocking any scenario.

**Comment by mattscheffer** [comment]
I'll check in today's runs. I've automated adding the redirect for the binaries as a workaround for the tests. I'll disable that and check again.
