### ISSUE TITLE
Project system should support macros in Debug > Command Line Arguments

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#12561]
**Version Used**: 

VS2015 update 3

**Steps to Reproduce**:

1. File > New > C# > ConsoleApplication
2. Project Properties > Debug > Command line arguments `"$(SolutionDir)"`
3. Inside `Main` write the code `foreach (var arg in args) Console.WriteLine(arg);`
4. Debug > Start

**Expected Behavior**:

In step 2, there should be an "edit" button which opens up the standard VS macros+edit dialog (such as is found in Project Properties > Build Events > Edit Pre-build)

In step 4, it should have printed out the solution's directory.

**Actual Behavior**:

In step 2, there's no such edit button.

In step 4, it prints out the string `"$(SolutionDir)"` without expanding it.

See also this StackOverflow question:
http://stackoverflow.com/questions/4046575/vs2010-project-macro-variables-in-start-options-command-line-arguments?rq=1

**Comment by DustinCampbell** [comment]
Moved issue to https://github.com/dotnet/roslyn-project-system/issues/305.
