### ISSUE TITLE
Build/Rebuild doesn't generate XML documentation if DLL is up to date

### ISSUE THREAD

**Issue by MV10** [dotnet/roslyn#12560]
Can't recall whether VS has always worked this way, I've probably never tried this particular scenario, but it seems like a bug.

**Version Used**: 
VS 2015 Community edition with .NET Core 1.0 release and Tools Preview 2

**Steps to Reproduce**:

1. Create a .NET Core class project
2. Build
3. Open project properties
4. Check the "XML documentation file" option
5. Rebuild

**Expected Behavior**:
XML documentation file will be generated in the framework bin folders.

**Actual Behavior**:
No docs are generated. I have to go into the bin folders and delete the DLL (or change the source) to force a rebuild before the XML file is created.

**Comment by DustinCampbell** [comment]
Moved issue to https://github.com/dotnet/roslyn-project-system/issues/306
