### ISSUE TITLE
Project.OutputFilePath should point to bin\Debug\ConsoleApplication1.exe, not to obj\Debug\ConsoleAPplication1.exe

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#12562]
**Version Used**: 

VS2015 Update 3

**Steps to Reproduce**:

1. File > New > C# > Extensibility > Code Refactoring VSIX
2. Set a breakpoint on the method `ComputeRefactoringsAsync`, and hit F5 to launch
3. In the new experimental instance of VS, open up or create a C# project, and hit ctrl+dot to trigger the refactoring.
4. When the breakpoint is hit, go to the Immediate window and evaluate `? context.Document.Project.OutputFilePath`

**Expected Behavior**:

It should evaluate to `"...\ConsoleApplication1\bin\Debug\ConsoleApplication1.exe"`

**Actual Behavior**:

It evaluates to `"...\ConsoleApplication1\obj\Debug\ConsoleApplication1.exe"`, to the *obj* directory not the *bin* directory.

**Comments**:

I can understand that there might be internal implementation detail reasons for why the project claims to target the obj directory. But I think those reasons shouldn't surface to me, the user.

What I want is for Roslyn to offer me a model of the document+project+workspace. And the project, under its Project Properties > Build > Output Path clearly states that the output path is `bin\Debug\`. Therefore the Roslyn model of the project should reflect this.

**Comment by Pilchie** [comment]
Tagging @mattwar and @jasonmalinowski to see if they disagree with me, but my take is that Roslyn's project model represents the information passed to the compiler, not the sum of everything that happens in the build system.  In this case, msbuild tells the compiler that the output is the obj directory and then it later copies this elsewhere, but that is outside the purview of Roslyn.

**Comment by jasonmalinowski** [comment]
I agree that this is "By Design" per @Pilchie's argument. Reaching into the bin folder is a tricky process, as one might not even exist for a project. Generally "what are you really trying to do" gets asked that that point. :smile:

**Comment by ljw1004** [comment]
What I'm trying to do is build a modified version of the EXE and execute it. The only place I can reliably know that I can run it is the bin directory. (the obj directory normally doesn't contain a bunch of necessary referenced DLLs).
