### ISSUE TITLE
Incorrect "Cast is redundant" when switch on an `object`

### ISSUE THREAD

**Issue by CnSimonChan** [dotnet/roslyn#12572]
**Version Used**: 

Master branch, commit d9b6e87a1b08f2f12f5fbd5eb0b071d82b672beb (latest when submitted this issue)

**Steps to Reproduce**:

```` C#
public static void TestSwitchInt(object i)
{
    switch ((int)i)
    {
        case 0:
            Console.WriteLine("0");
            break;
        case 1:
            Console.WriteLine("1");
            break;
        case 2:
            Console.WriteLine("2");
            break;
    }
}
````

**Expected Behavior**:

No "Cast is redundant" suggestion.

**Actual Behavior**:

"Cast is redundant" on `(int)i`.

Removing it will cause the compiler to generate more complicated code (to check the type of `i`).

**Comment by gafter** [comment]
The code behaves completely differently with and without the cast, when the input is `null`.
