### ISSUE TITLE
Get rid of the old codeplex reference source

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#12571]
I find it baffling that there are two Roslyn reference sources floating around, both of them in the front page of google:

http://source.roslyn.codeplex.com/
http://source.roslyn.io/

I think that the codeplex pages should give http 301 "moved permanently" redirects to the corresponding new pages.

**Comment by jasonmalinowski** [comment]
@KirillOsenkov Any idea what it would take to get this fixed? I _think_ you were involved in the older setup?

**Comment by KirillOsenkov** [comment]
I'd start a thread internally with Arvin Gamiao and he should be able to route it.

**Comment by jasonmalinowski** [comment]
This was fixed.
