### ISSUE TITLE
Roslyn reference source - "403 you don't have permission" for some pages, not others

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#12570]
REPRO: navigate to http://source.roslyn.io/Microsoft.CodeAnalysis.Workspaces/a.html#f07f0bc37b88156c

WHAT I EXPECT: it should show a page of reference source.

WHAT I GET: 403 permission denied.

-------------------

REPRO: navigate to http://source.roslyn.io/#q=project.adddocument and click on the first "method AddDocument" link inside project Microsoft.CodeAnalysis.Workspaces

WHAT I EXPECT: it should show a page of reference source

WHAT I GET: 403 permission denied.

-------------------------

I'm looking on Roslyn reference source for the source code of Project.AddDocument. Some files within the Roslyn source code report 403 "you don't have permission". Others do let me see them.
![adddocument1](https://cloud.githubusercontent.com/assets/3316258/16901336/3fc1b584-4bf5-11e6-8faa-7fa95de3d685.png)
![adddocument2](https://cloud.githubusercontent.com/assets/3316258/16901337/3fd472e6-4bf5-11e6-944b-650c387cf6f9.png)

I did this on July 17th 8am. I'm using Chrome Version 51.0.2704.103 m (64-bit). Running Windows 10 Insider 14388.0. On a MacBookPro running Bootcamp. On my home network.

I observed the same 403 error for those pages on Internet Explorer 11 and Edge.

**Comment by KirillOsenkov** [comment]
Weird, I can't repro. Did you try another machine?

**Comment by ljw1004** [comment]
It's not repro'ing for me at the moment. I didn't try another machine at the time I filed it.

**Comment by KirillOsenkov** [comment]
It could be that you caught it at the exact same moment when the index was being updated. It's usually in the night after 1am PDT. I'm going to close this but feel free to reopen if you see weirdness again. Thanks.
