### ISSUE TITLE
Cannot mix Enum and Int with same value in one switch

### ISSUE THREAD

**Issue by CnSimonChan** [dotnet/roslyn#12573]
**Version Used**: 

Master branch, commit d9b6e87a1b08f2f12f5fbd5eb0b071d82b672beb (latest when submitted this issue)

**Steps to Reproduce**:

````C#
public enum EnumA
{
    ValueA,
    ValueB,
    ValueC
}

public static void TestSwitchEnumAndInt(object value)
{
    switch (value)
    {
        case EnumA.ValueA:
            Console.WriteLine("A");
            break;
        case 0:
            Console.WriteLine("0");
            break;
        default:
            Console.WriteLine("Default");
            break;
    }
}
````

**Expected Behavior**:

No error.

**Actual Behavior**:

`CS0152	The switch statement contains multiple cases with the label value '0'`

Since the pattern matching will check value's type first, `EnumA.ValueA` is not same as `0`.

**Comment by HaloFour** [comment]
What is written if `value` happens to be a boxed `int` with the value `0` rather than a boxed `MyEnum.ValueA`?

**Comment by gafter** [comment]
@HaloFour It is because of that possibility - those two scenarios of boxed `int` `0` and boxed `EnumA.ValueA` are distinct - that this is a bug.

**Comment by HaloFour** [comment]
@gafter Makes sense, and sounds technically correct.  I wonder if there might arise a common misconception about that fact, though, whether integral types and enums should be more implicitly convertible in a type-switch statement.
