### ISSUE TITLE
"Make the containing scope async" suggestion should not create methods with async void signature

### ISSUE THREAD

**Issue by imanushin** [dotnet/roslyn#12578]
**Version Used**: 
MSVS 2015 Update 3, .Net 4.5

**Steps to Reproduce**:

1. Create method for nunit test:
```
        [Test]
        public void MyTestMethod()
        {
            await DoAsync().ConfigureAwait(false); //DoAsync returns Task
        }
```
2. Press *Ctrl-.*, select *Make the containing scope async* suggestion
3. Preview changes

**Expected Behavior**:
```
        [Test]
        public async _Task_ MyTestMethod() // <---- see return type
        {
            await DoAsync().ConfigureAwait(false); //DoAsync returns Task
        }
```

**Actual Behavior**:
```
        [Test]
        public async void MyTestMethod() // <---- see return type
        {
            await DoAsync().ConfigureAwait(false); //DoAsync returns Task
        }
```

Why:
*async void* methods can miss exceptions, because they are not awaited (e.g. error will be suppressed). However, *async Task* methods can be awaitable (and they will be awaitable).
This suggestion should recommend create *async Task* methods or there should be two recommendations: for void and Task return values.

**Comment by CyrusNajmabadi** [comment]
I like the suggestion that we offer both changes.  There are places for async-void as well as async-task.  Providing both suggestions lets the client decide which is appropriate for their domain.

**Comment by AdamSpeight2008** [comment]
Make then warnings. In the vb case which tends towards error message being help, include the explanation in the message.
