### ISSUE TITLE
Add swixproj validation

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#12589]
Currently we dont have any kind of validation for building the swixprojs. Today, we check-in the code, build the official-build and check if everything works. This is not an ideal and sustainable way to validate the swixprojs. We should add validation for swixprojs which could be run locally rather than having to go through the official build every time we make a change

**Comment by shyamnamboodiripad** [comment]
One of the things that we need to validate is that dependencies authored for SWIX should match the underlying VSIX dependencies. This dependency authoring was missing in our swixprojs until @basoundr introduced this in #12576

**Comment by jasonmalinowski** [comment]
@jaredpar To confirm, you completed this item?

**Comment by jaredpar** [comment]
Yep.  Closed.
