### ISSUE TITLE
Put OmittedType instead of null in VariableDeclaration.Type (make it non-optional again)

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#12588]
Per compat council, we should try and avoid making a field optional that was previously mandatory.
This will decrease the chances of NullReferenceException in consuming code (such as analyzers).

**Comment by gafter** [comment]
We use the pattern of using OmittedTypeArgument where a type is grammatically permitted but may be omitted in some cases. The proposed use of an omitted type here represents places where a type is syntactically forbidden. So the solution will be to revert VariableDeclarationSyntax to its C# 6 form and represent deconstruction as a syntactically distinct node.
