### ISSUE TITLE
Implement dominant type inference for tuple types with mismatching element names

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#12585]
Not sure if we already have a more general bug for this.

This bug covers several scenarios where dominant type is computed - ternary operators, lambdas with multiple returns, method type inference.
The sitution may arise that we have multiple candidates for the dominnat type whose difference is only of tuple element names.
Note that   `ValueTuple<int, int>` and `(int, int)` are not different at all, 
while `List<ValueTuple<int, int>>` and `List<(int a, int b)>` are name-different 

- In all cases involving merging several tuple types and finding a dominant one, just drop the conflicting names. The rule is recursive and transparent through nontuple types. I.E.   (int a, int b)[] can unify with (int a, int z)[] and result in a dominant type   (int a, int)[] .

Note, this will automatically result  in "ignored name" warnings in case of tuple literals.

**Comment by jcouv** [comment]
@jaredpar @VSadov @gafter  I think this should be in RC. Makes sense?

**Comment by VSadov** [comment]
It is a strong "good to have" for RC, but it is not a breaker of existing code, so can be done in RTM if necessary.

**Comment by jcouv** [comment]
Fixed by #12834
