### ISSUE TITLE
Change syntax model of ref returns/locals/assignments.

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#12580]
For declarations, we want to:
 
1)	Put ‘ref’ in the modifiers list for declarations.  i.e. with ‘public ref int Foo()’,  ‘ref’ and ‘public’ will be in the same list.
2)	‘ref’ can be parsed in any order (for error tolerance) in the modifier list, but we will enforce that it must be the last modifier if it is there.
3)	If ‘partial’ is in the list, it can be second to last if and only if it is followed by ‘ref’.
 
For expressions, we want to:
 
1)	Introduce a new ‘RefExpression’.  It has the intuitive form:  ref <expression>
2)	We will fix up ‘ParseExpression’ in the parser to pass a value saying if ‘ref expressions’ are allowed or not.  In the cases where we allow them (like “return ref …”) we will pass true, and in all other cases we pass false.  The parser will always parse out a ref expression when possible, but will error if the flag is false.  This means we will produce a good tree for expressions like  “foo ? ref Bar() : ref Baz()”, though we will still emit errors that this form isn’t legal.
3)	We will still produce the same tree nodes for ref arguments.  i.e.  “Foo(ref a)” will have an argument node that has a ref keyword and an ‘a’ expression, it will *not* have a RefExpression of ‘ref a’.
 
For for-statements, we want to:
 
1)	Add a DeclarationModifiers list where ‘ref’ can go.  
2)	We called it ‘DeclarationModifiers’ because we were wary that ‘Modifiers’ might conflict with us adding modifiers to the actual ‘for’ statement in the future.  It also makes it clear what part of the for-statement these modifiers apply to.

**Comment by gafter** [comment]
Rather than modeling ref as a modifier, we've decided to model it as a type. So in the syntax model, there will be a "RefTypeSyntax" that includes the ref keyword and then a type. That handles all the existing contexts that we want to support ref, and it doesn't have the problem that modifiers are (mostly) unordered.
