### ISSUE TITLE
Scope changes for patterns and out var

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#12597]
The LDM is reconsidering some scope issues for pattern variables and out variables. The most likely change is that such variables declared in a declaration statement or expression statement that appear in a block are in scope throughout that block.

However, the proposed rule changes need to be settled before they are implemented.

[Addendum 2016-08-11]
The LDM has settled on a revision of the scoping rules. The principal changes from the current status are that (pattern and out) variables that are declared in the following places are in the enclosing scope (e.g. the scope that they would be in if the statement were a declaration statement that declares that variable).
- in the initializers of a local variable declaration statement
- in the expression of an expression statement
- in the condition of an `if` or `while` statement
- the expression of a `switch` statement
- in the expression of a `return`, `throw`, or `yield return` statement.

A controlled statement of a compound statement never leaks variables to an enclosing scope. Logically, you can think of a controlled statement as being surrounded by a block for the purposes of scoping.

Because of these changes, there is no longer a special treatment for the `else` clause of an `if` statement.

Here are the relevant design notes https://github.com/dotnet/roslyn/issues/12939.

[Addendum 2016-08-24]
The LDM has revised the scoping rules slightly today. Here are the changes:
- out variables and pattern variables are forbidden to be declared inside field initializers and auto-property initializers (i.e. it is an error to declare an out variable or a pattern variable). The reason for this is that we are considering having a scope that spans the declaration and includes all the initializers (separately, a scope that spans the static initializers). We expect we may do that around the time we introduce records, but unless we forbid them today it would be an incompatible change later.
- out variables and pattern variables declared inside a constructor-initializer are in scope throughout the body of the constructor. For C# 7, we may forbid them in that location unless time permits us to implement the desired scoping rules.

**Comment by HaloFour** [comment]
@gafter 

```cs
string s = "123";
bool b = int.TryParse(s, out int i);
Console.WriteLine(i); // in scope?
```

**Comment by gafter** [comment]
@HaloFour Yes.

**Comment by HaloFour** [comment]
@gafter 

Curious, particularly after all of the conversations regarding this scoping dating back to CodePlex.  It simplifies things but also complicates other things.

What about:

```cs
string s = "123";
if (int.TryParse(s, out int i)) {
    ...
}
// i in scope here?
```

or

```cs
object o = ...;
switch (o) {
    case string x: break;
    case int x: break; // can reuse x here?
}
```

**Comment by AdamSpeight2008** [comment]
I like the idea of by default is local to enclosing scope, unless the user specifies otherwise.
```c#
if( Int.TryParse( text, local out var value ) ) \\ local to enclosed scope
if( !Int.TryParse( text, guard out var value ) ) \\ not lot local to enclosed scope.
```
In pattern matching in `when clauses` it is local to enclosed scope, which would enable the out variable to be reused for different types.

**Comment by gafter** [comment]
@HaloFour These are on the table and being discussed internally. For the switch cases, we're not considering changing that.

**Comment by gafter** [comment]
The revised scoping rules have been edited into the issue description above.

**Comment by HaloFour** [comment]
@gafter 

So, to clarify:

**Fine**:
```cs
switch (obj) {
    case int x: Console.WriteLine($"obj is an int of value {x}"); break;
    case string x: Console.WriteLine($"obj is a string of value \"{x}\""); break;
}
```

**Compiler Error**:
```cs
if (obj is int x) {
    Console.WriteLine($"obj is an int of value {x}");
}
else if (obj is string x) { // ERROR CS0136
    Console.WriteLine($"obj is a string of value \"{x}\"");
}
```

**Weirdness**:
```cs
for (string line = reader.ReadLine(); line != null && int.TryParse(line, out int value); line = reader.ReadLine()) {
    // line and value in scope here
}
// value in scope here?!
```

**Comment by gafter** [comment]
@HaloFour Correct. The `for` loop does not leak anything to the enclosing scope.

**Comment by HaloFour** [comment]
@gafter 

> Correct. The `for` loop does not leak anything to the enclosing scope.

But the `out` declaration in the same construct does?

I brought up the `for` loop case specifically because that and `foreach` are the only statements that currently allow variable declaration within, and in both cases the scope of those variables is contrary to this decision.  My opinion is that having different rules for `out` declarations will be very confusing.

**Comment by gafter** [comment]
> But the `out` declaration in the same construct does?

No, the `out` declaration in the for loop does not leak anything to the enclosing scope. Neither the `for` loop nor the `foreach` loop leak their declared variables today, and that will remain true under this revision of the rules.

**Comment by HaloFour** [comment]
@gafter 

Oh ok, but if I refactored to the following then `value` would "leak" to the enclosing scope?

```cs
string line = reader.ReadLine();
while (line != null && int.TryParse(line, out value)) {
    // do something
}
// is value in scope here?
```

Sorry for pestering.  I did see Mads comment about design notes and how he intends to write up the details on this particular change in the coming weeks and I'm sure that would clarify all of the cases and ramifications.

**Comment by gafter** [comment]
Yes, if you "refactored" in that way without adding an enclosing block, both `line` and `value` would end up in the enclosing scope.

**Comment by Eyas** [comment]
@gafter 

What happens when someone references a result of a positive pattern match outside of where it is expected to be initialized? Will the compiler complain that this value might not be initialized? Or will it just compile?

e.g.

```cs
if (x is string s) {
  // do something
}
Console.WriteLine(s.Length); // s in scope according to new rule. will this compile?
```

**Comment by gafter** [comment]
@Eyas It just won't be definitely assigned there. But you could assign it yourself, for example in an else clause!

**Comment by paulomorgado** [comment]
Let me see if I got this right.

It works like this:

    if(int.TryPars(s, out var i)
    {
        // i in scope
    }
    else
    {
        // i in scope
    }

    // i not in scope

which is the same as this:

    {
        int i;
        if(int.TryPars(s, out i)
        {
            // i in scope
        }
        else
        {
            // i in scope
        }
    }

    // i not in scope

**Comment by HaloFour** [comment]
@paulomorgado 

No:

```cs
if(int.TryPars(s, out var i)
{
    // i in scope
}
else
{
    // i in scope
}

// i in scope, too!
```

**Comment by stepanbenes** [comment]
@HaloFour Will `i` be definitely assigned? I suppose that it will be...

**Comment by HaloFour** [comment]
@stepanbenes 

Yeah.  C# doesn't really know that the `out` variable and the return value of the function are related.  This isn't any different to the situation today:

```cs
int i;
int.TryParse(s, out i);
// i is definitely assigned here
```

**Comment by stepanbenes** [comment]
@HaloFour Yes, obviously. But I must say, that it is not intuitive as it differs from the case `if (x is string s)`

**Comment by paulomorgado** [comment]
@HaloFour,

That's the part I don't like.

If the variable is declared on an `if` or `while` statement, it should behave like the `for` or `foreach` statement.

The way I see it, is that the declaration always leeks into the enclosing scope. But not beyond that. And the `if` statement's scope should start at the `IfStatement` node.

The same for the ternary operator.

**Comment by HaloFour** [comment]
@stepanbenes Yes, but type-switch conditions are a different beast entirely because the compiler is aware of if/how the variable is being assigned.  Functions are otherwise a black box and the compiler can't assume what the function might do.  When pattern matching is implemented it will follow the same definite assignment rules as type-switch.

@paulomorgado I don't disagree.  There is something weird about having the scope leak out into the enclosing context in those cases.  Apart from being inconsistent internally with the behavior of `for` and `foreach` it is also inconsistent with the heritage languages C/C++ where declaration within such a construct does not leak to the enclosing scope.  My opinion is that the team wanted to go with simplicity here since it obviates the need for constructs like `guard`, but I think that it is the technically incorrect decision.

C:
```c
if (int i = read()) {
    // i in scope here
}
else {
    // i in scope here
}
// i is not in scope here

while (int i = 100) {
    i--; // i in scope here
}
// i is not in scope here
```

**Comment by HaloFour** [comment]
I know that it's probably too late but I would like to reiterate that I think that these new scope rules are a bad idea in that they introduce a number of inconsistencies in the language.  Now you'll be required to know that scoping works differently between `while` and `for` loops.  It's also inconsistent with scoping rules from C.  In my opinion if it is the intent of the developer to have the scope of the variable include the enclosing scope that they should declare the variable in the enclosing scope.

**Comment by AdamSpeight2008** [comment]
@HaloFour `while` and `for` have always had different scoping. Also `C#` not `C`

**Comment by HaloFour** [comment]
@AdamSpeight2008 

`while` has never permitted declaring a variable in the condition before and I don't think that imposed limitation is relevant to this discussion.

C# isn't C, but it borrows a lot of syntax from C and the rest of the C-family of languages.  Intentionally choosing a different behavior will be inconsistent and confusing.  C# already decided to follow C-style rules with declaration expressions in `for` statements.  Choosing different rules for `while` statements is confusing and inconsistent.

I really would love to hear more about the justification of this decision and I hope that it's something better than simply being easier to implement.

**Comment by gafter** [comment]
@HaloFour Here are the relevant design notes #12939.

**Comment by tumtumtum** [comment]
So does this mean the the equivalent of a swift guard would simply be:

    public void Foo()
    {
        if (!(let x = Bar())) { return; }

        x.ThisIsInScope();
    }

**Comment by gafter** [comment]
@tumtumtum I have no idea what your `let` thing is, but this is possible:

```cs
public void Foo(KeyType key)
{
   if (!map.TryGetValue(key, out var value)) return;
   value.OutParameterInScopeHere();
}
```

**Comment by tumtumtum** [comment]
@gafter Sorry, ignore the let and consider it a var. I was under the impression that variable declaration expressions were now allowed in an if condition -- and if that's the case, does the variable leak out to the containing scope?

**Comment by tumtumtum** [comment]
Is there a way to make sure a variable is not null and assign it to another variable in the same way as Swift's `if let` statement?

    if let x = nullableX { print(x) } else { print("x is null") }

**Comment by HaloFour** [comment]
@tumtumtum 

Assuming `nullableX` is a `string`, but could be any reference or nullable value type:

```cs
if (nullableX is string x) {
    Console.WriteLine(x);
}
else {
    // x is in scope but not definitely assigned
    Console.WriteLine("nullableX is null");
}
// x is still in scope but not definitely assigned
```

It seems much of the point of these scoping rules is to avoid the tons of extra syntax that Swift requires in order to influence the scope.

The above example is interesting, though, because `x` would leak out, but it wouldn't be definitely assigned.  And because pattern variables are `readonly` it could never be definitely assigned, so I don't know what use that identifier would have outside of the scope in which the compiler can guarantee assignment.

**Comment by gafter** [comment]
```cs
if (!(nullableX is string x)) {
    x = "value to use when nullableX is null";
}
// x is still in scope and definitely assigned
```

**Comment by HaloFour** [comment]
@gafter 

So then pattern variables are also no longer `readonly`?

**Comment by gafter** [comment]
@HaloFour Correct.

**Comment by gafter** [comment]
We have added

> - the expression of a `switch` statement

to the list of expressions that spill declared variables into the enclosing scope.

**Comment by Richiban** [comment]
> So then pattern variables are also no longer readonly?

This is sad :(

**Comment by orthoxerox** [comment]
@Richiban it looks like the design team has decided not to touch the issue of immutability in this release. Tuples are mutable, so pattern variables are mutable as well. I wonder if `let` is still there.

**Comment by Richiban** [comment]
On 16 August 2016 at 16:46, orthoxerox <notifications@github.com> wrote:

> the design team has decided not to touch the issue of immutability in this
> release


>  the design team has decided not to touch the issue of immutability in
this release

I guess I understand this, but it's a shame *because they can never go
back*... once they've introduced these features they can never turn a
variable type from mutable to immutable, or decrease a variable's scope
because this will always be a breaking change... I feel like they should
have erred on the side of smaller scope and immutability and they could
always change it in future based on feedback from the community.


-- 

- Richard Gibson -

**Comment by HaloFour** [comment]
@Richiban

Changing the pattern variable scoping would be a breaking change either way.  If they went with smaller scope and decided to expand it later they could run afoul of variable shadowing:


```cs
if (int.TryParse(s, out int i)) {
   ...
}
else {
    int i = ...
}
```

I mostly agree, though.  It feels like a short-term solution that will feel even worse when pattern matching is implemented.  I can understand not wanting to have tons of different keywords and grammars for every different situation, but I think that they could handle the majority of use cases while encouraging better practices by keeping features like this on tighter rails.

**Comment by aluanhaddad** [comment]
This is very disappointing. I do not think this is necessary at all and I do not think it integrates well into the language. The concerns that @HaloFour voiced pretty much sum up how I feel.

**Comment by gafter** [comment]
Added the following to this issue just now:

> [Addendum 2016-08-24]
The LDM has revised the scoping rules slightly today. Here are the changes:
- out variables and pattern variables are forbidden to be declared inside field initializers and auto-property initializers (i.e. it is an error to declare an out variable or a pattern variable). The reason for this is that we are considering having a scope that spans the declaration and includes all the initializers (separately, a scope that spans the static initializers). We expect we may do that around the time we introduce records, but unless we forbid them today it would be an incompatible change later.
- out variables and pattern variables declared inside a constructor-initializer are in scope throughout the body of the constructor.

**Comment by AlekseyTs** [comment]
I believe this issue has been addressed.

**Comment by SLaks** [comment]
> - out variables and pattern variables are forbidden to be declared inside field initializers and auto-property initializers (i.e. it is an error to declare an out variable or a pattern variable). The reason for this is that we are considering having a scope that spans the declaration and includes all the initializers (separately, a scope that spans the static initializers). We expect we may do that around the time we introduce records, but unless we forbid them today it would be an incompatible change later.


This is annoying; it'd be nice to be able to write

```C#
int SomeFlag { get; } = int.TryParse(SomeStatic.String, out int x) ? x : 0;
```

**Comment by gafter** [comment]
@SLaks I agree. You'll have to write a helper function.

**Comment by paulomorgado** [comment]
>@SLaks I agree. You'll have to write a helper function.

It would always have to be inside a method, right? The only thing the compiler could do is generate one. Which wouldn't be such a bad idea.

**Comment by SLaks** [comment]
@paulomorgado No; initializers are emitted as part of the (static) constructor; the compiler could generate a local there.

**Comment by paulomorgado** [comment]
Static initializers, right @SLaks?

But I think it would be less confusing if a method was generated for each initializer that needs it.

**Comment by gafter** [comment]
@paulomorgado The reason that the compiler doesn't do this for you is that it would give the wrong scope to the expression variables. We are considering having a single scope for all the expression variables of the static initializers of a class (and another scope for the expression variables of the instance initializers). But until we settle the desired scoping, and implement it, we are blocking off the area so that implementing it later will not be a breaking change.

**Comment by paulomorgado** [comment]
@gafter,

With same scope, do you mean that this will be possible?

    int SomeFlag { get; } = int.TryParse(SomeStatic.String, out int x) ? x : 0;
    int SomeOtherFlag { get; } = x;

**Comment by gafter** [comment]
Yes

**Comment by paulomorgado** [comment]
Why have you considered that? At first, I would never consider any variable leaking out of that initialization. If I wanted that, I would write a proper constructor.

Would that initialization still run before the constructor?

**Comment by gafter** [comment]
We have considered that because in the cases where it is useful, it is very awkward to work around the feature being absent.

Yes, the initialization would run before the constructor.

**Comment by paulomorgado** [comment]
I still can't think of a use case where code that looks like today's code (apart from that temporary variable usage) would benefit from that.

Is something like this expected to work with declaration expressions?

```
int x = (var I = 1; i);
int y = -i;

```

Well, if it runs before the constructor, it won't change the meaning that much.

**Comment by gafter** [comment]
There are  places where we need to compute the value of two properties at the same time and we want to expose them separately. We end up having a single underlying field that holds the pair of values. It would be a bit cleaner if we could store them separately.

Declaration expressions are still on the drawing board, so I cannot say exactly how they would work.

-Neal

On Dec 25, 2016, at 4:29 PM, Paulo Morgado <notifications@github.com<mailto:notifications@github.com>> wrote:


I still can't think of a use case where code that looks like today's code (apart from that temporary variable usage) would benefit from that.

Is something like this expected to work with declaration expressions?

int x = (var I = 1; i);
int y = -i;



Well, if it runs before the constructor, it won't change the meaning that much.

-

**Comment by paulomorgado** [comment]
> There are  places where we need to compute the value of two properties at the same time and we want to expose them separately. We end up having a single underlying field that holds the pair of values. It would be a bit cleaner if we could store them separately.

Maybe it's a "get off my lawn" attitude, but that's what constructors are for, 😄

**Comment by gafter** [comment]
Field initializers are where you compute the value of fields that occur before the constructor runs. That is much more compelling with records, where the constructor parameters are in scope in the field initializers.
