### ISSUE TITLE
Selecting the space before an expression changes the Quick Actions offered

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#12591]
If I select an expression to introduce a local variable and I happen to highlight the space before the expression, I am only offered the ability to "Extract Method".
![image](https://cloud.githubusercontent.com/assets/1402694/16933537/0f2e9a9a-4d03-11e6-9203-e3566751c3e5.png)

However, if I only select the expression, I get the correct code actions:
![image](https://cloud.githubusercontent.com/assets/1402694/16933550/27b31b04-4d03-11e6-8b9b-b3d1d9c4ef8d.png)

**Comment by Pilchie** [comment]
I suspect that we have a `Span.Intersects` and so the node we find is the entire argument list, since the start position equals the end position of the comma.

**Comment by CyrusNajmabadi** [comment]
This no longer reproes.  Will add test to demonstrate this.
