### ISSUE TITLE
Remove Unnecessary Cast adds extra parentheses in arrow method

### ISSUE THREAD

**Issue by yume-chan** [dotnet/roslyn#12600]
**Version Used**: 

Visual Studio "15" Preview 3

**Steps to Reproduce**:
1.  Add code
   
   ``` C#
   public object GetValue() => (object)new object();
   ```
2. Invoke "Remove Unnecessary Cast" on `(object)new object();`.

**Expected Behavior**:

``` C#
public object GetValue() => new object();
```

**Actual Behavior**:

``` C#
public object GetValue() => (new object());
```

Method body doesn't matter, also tried member accessing or method calling body.

**Comment by Pilchie** [comment]
You had another bug about parenthesis and expression bodied members, right?
