### ISSUE TITLE
Need [DebuggerDisplay] for Microsoft.CodeAnalysis.DocumentInfo

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#12605]
When debugging workspace code it'd be nice to see the contents of DocumentInfo instances:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/DocumentInfo.cs,51bf71c40c4e6712

Primarily the FilePath is of interest.

**Comment by KirillOsenkov** [comment]
Also FileTextLoader (http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/FileTextLoader.cs,cd86cfc0493c0539). It'd be nice to know the Path.

**Comment by AdamSpeight2008** [comment]
@KirillOsenkov 
Are there anymore you would like?

**Comment by KirillOsenkov** [comment]
@AdamSpeight2008 Thanks. If I notice anything else I'll file a separate issue.
