### ISSUE TITLE
Support discards in deconstructions, out var and patterns

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#12619]
``` C#
(int i, int j, *) = M();
var (i, j, *) = M();
```

Even if wildcards don't make it into C# 7, we need to figure out the syntax model and design, so they can be added smoothly later.

**Comment by HaloFour** [comment]
Has the wildcard syntax been settled?  My vote is definitely for `*` (rather than trying to make `_` do double duty contextually).

**Comment by jcouv** [comment]
@HaloFour The syntax is not finalized yet, but `*` has some advantages as it is not ambiguous with any identifier. We're leaning that way at the moment.

**Comment by jcouv** [comment]
@HaloFour One more thing to set expectations, it is possible that wildcards may not make it in C# 7, but only 7.1 or 8, due to time constraint. I intend to figure out the design so that it can be added later without introducing compat issues.

**Comment by jaredpar** [comment]
Moving the actual language feature out to 2.1 for now.  Issue #12664 is tracking the syntax work in RC.

**Comment by gafter** [comment]
This will be easier to address once #13270 has been done.

**Comment by jcouv** [comment]
> This will be easier to address once #13270 has been done.

@gafter I didn't understand that comment. The way I'd implement wildcards in the current design would be make a special `DeconstructionVariable` for wildcard and not produce the final assignment step to such a variable. 
We'd still produce conversion steps (since they are observable) as normal.

**Comment by gafter** [comment]
@jcouv The initial binder should not be producing any "steps" at all, as those are not part of the static semantics of the construct.

**Comment by jcouv** [comment]
This issue was superseded by the more detailed issue https://github.com/dotnet/roslyn/issues/14794
