### ISSUE TITLE
Solution Explorer Shim internal dependencies

### ISSUE THREAD

**Issue by WolfieWerewolf** [dotnet/roslyn#1261]
Hi Guys,

Just thought I would let you know that AnalyzersCommandHandler.cs has dependencies on the VS SDK that use internal modifiers.  intarnal static bool IsBuiltInRuleSet and it's dependencies.  As far as I can tell the source is not public for the SDK.  All of this needs to either be made public or moved into Roslyn.

 internal static bool IsBuiltInRuleSet(string ruleSetPath, System.IServiceProvider provider)
        {
            if (string.IsNullOrEmpty(ruleSetPath))
            {
                return false;
            }
            return (Path.Combine(GetBuiltInRuleSetDirectory(provider), Path.GetFileName(ruleSetPath)).Equals(Path.GetFullPath(ruleSetPath), StringComparison.OrdinalIgnoreCase) && ((new FileInfo(ruleSetPath).Attributes & FileAttributes.ReadOnly) == FileAttributes.ReadOnly));
        }

        private static string s_builtInRuleSetDirectory;
        internal static string GetBuiltInRuleSetDirectory(System.IServiceProvider provider)
        {
            if (s_builtInRuleSetDirectory == null)
            {
                s_builtInRuleSetDirectory = Path.Combine(GetStaticAnalysisToolsDirectory(provider), "Rule Sets");
            }
            return s_builtInRuleSetDirectory;
        }
        private static string s_staticAnalysisToolsDirectory;
        private static string GetStaticAnalysisToolsDirectory(System.IServiceProvider provider)
        {
            if (s_staticAnalysisToolsDirectory == null)
            {
                object obj2;
                string fullPath = null;
                IVsShell service = (IVsShell)provider.GetService(typeof(IVsShell));
                if ((service != null) && (service.GetProperty(-9041, out obj2) == 0))
                {
                    fullPath = obj2 as string;
                }
                if (string.IsNullOrEmpty(fullPath))
                {
                    fullPath = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), @"..\..\..\"));
                }
                s_staticAnalysisToolsDirectory = Path.Combine(fullPath, @"Team Tools\Static Analysis Tools");
            }
            return s_staticAnalysisToolsDirectory;
        }

**Comment by jaredpar** [comment]
Thanks for reporting this.  Unfortunately this is a known issue.  This, and the reason for the split between Roslyn.sln and RoslynLight.sln is covered in the [FAQ|https://github.com/dotnet/roslyn/wiki/FAQ#why-are-there-two-solution-files].  

> The VS SDK, and Roslyn's dependency on it, are constantly moving forward. Typically at a much faster pace than our CTPs. This means Roslyn is very often depending on APIs which are not yet released in a public build of Visual Studio. This makes it impossible for customers to build all of the sources on GitHub.

In this particular case it is a new API that is just not available yet in the VS SDK that comes with CTP6.  

Note: This is not a state that we are content with, it's a point in time problem.  An effect of us moving to the open where customers have different constraints than us.  We are actively working to remedy this problem.

**Comment by WolfieWerewolf** [comment]
Jared,

Thanks for that, in honesty reporting the bug was my cheeky way of making the missing source code public, as I included it in the ticket…  These things are going to happen, Roslyn is a moving target.  With enough persistence it compiles and runs as well as you could expect.

/W
