### ISSUE TITLE
Lookup of custom AsyncMethodBuilder members should check type parameter constraints

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#12616]
Lookup of custom `AsyncMethodBuilder` members should check type parameter constraints.

See `AsyncMethodBuilderMemberCollection.TryGetBuilderMember`.

**Comment by jaredpar** [comment]
After some discussion we decide to stick with the current behavior.  The compiler in general doesn't verify constraints on types that it uses during code generation.  Whether that behavior is the best approach or not, it is the general behavior of the compiler.  Changing it now holistically would be a back compat breaking change and having this feature stick out as the only one that verified the constraint feels odd.  Hence defaulting to consistency.

**Comment by jcouv** [comment]
There are some tests that are skipped because of this issue. They should be enabled to capture the decision.

**Comment by jcouv** [comment]
Re-opened, as it looks like @cston has a PR (https://github.com/dotnet/roslyn/pull/24322) fixing this.
