### ISSUE TITLE
Revert workaround to consume local Microsoft.Net.Compilers.props

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#12620]
See https://github.com/dotnet/roslyn/pull/12586/files#diff-3d047fca086c602e9edf3ed03e705e4aR31

We should do the following changes once we move to a newer toolset compiler package (Dev15 preview4 or higher) with this fix: https://github.com/dotnet/roslyn/commit/05c12ebfcdd08a02d
1. Delete the checked in copy of [build/Targets/Microsoft.Net.Compilers.props](https://github.com/dotnet/roslyn/pull/12586/files#diff-0963ae65ced7b4df9b6a694e66ddf8f1R1)
2. Set `ToolsetCompilerPropsFilePath` to `$(NuGetPackageRoot)\Microsoft.Net.Compilers\$(ToolsetCompilerPackageVersion)\build\Microsoft.Net.Compilers.props` over [here](https://github.com/dotnet/roslyn/pull/12586/files#diff-3d047fca086c602e9edf3ed03e705e4aR34)

**Comment by jasonmalinowski** [comment]
@mavasani Is this something we can do now?

**Comment by mavasani** [comment]
Have we moved to newer toolset packages that have Tanner's fix? I'd say just check the latest `$(NuGetPackageRoot)\Microsoft.Net.Compilers\$(ToolsetCompilerPackageVersion)\build\Microsoft.Net.Compilers.props` after restoring for latest sources and see if they contain https://github.com/dotnet/roslyn/commit/05c12ebfcdd08a02d

**Comment by mavasani** [comment]
Seems like we are still on Dev15 Update3 toolset compiler: https://github.com/dotnet/roslyn/blob/master/build/Targets/Settings.targets#L24

**Comment by mavasani** [comment]
I meant **Dev14** Update3 :-)

**Comment by jasonmalinowski** [comment]
This was fixed long ago.
