### ISSUE TITLE
[scriptcs] IsCompleteSubmission for VB

### ISSUE THREAD

**Issue by filipw** [dotnet/roslyn#1263]
is there an equivalent of `IsCompleteSubmission` (https://github.com/dotnet/roslyn/blob/b6484300dfafb43af0c27e542ec457a7583e1aa8/src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs#L1735) for VB?

**Comment by ManishJayaswal** [comment]
I am not sure if we have something similar for VB. @tmat would know.

**Comment by filipw** [comment]
For now I am just grabbing diagnostics and checking if everything's all right, but of course this is very naive approach.

**Comment by tmat** [comment]
@drognanar Is this now implemented?

**Comment by drognanar** [comment]
Implemented in #7302
