### ISSUE TITLE
SyntaxTrees with a null path should be explicitly disallowed

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#12638]
At present, it is possible to construct a `SyntaxTree` with a `null` path in compiler that was compiled under the `Release` configuration. However, the documentation for `SyntaxTree.FilePath` explicitly states that `the path shall not be null` (http://source.roslyn.io/#Microsoft.CodeAnalysis/Syntax/SyntaxTree.cs,e12956b59d7683ea).

* CSharpParsedSyntaxTree (http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/CSharpSyntaxTree.ParsedSyntaxTree.cs,fcc0925d5e8c089c) has a `Debug.Assert` to ensure that no null path is used for the Debug configuration
* However, there is no such check in the public API `CSharpSyntaxTree.Create` (http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/CSharpSyntaxTree.cs,d40da3b7b4e39486). As such, it is only possible to construct a syntax tree with a null path in the Release configuration
* Note that the other entry points for creating a ParsedSyntaxTree do not allow a null path
 * `CSharpSyntaxTree.CreateWithoutClone` (http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/CSharpSyntaxTree.cs,ebf9a5453787d42b) always passes an empty path (`string.empty`)
 * `CSharpSyntaxTree.ParseText` (http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/CSharpSyntaxTree.cs,f4e9b1e7862d75c8) throws an exception for null path
 * `CSharpSyntaxTree.WithChanges` (http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/CSharpSyntaxTree.cs,f93c5917f27da6d2) uses the existing path
 * `CSharpSyntaxTree.WithFilePath` (http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/CSharpSyntaxTree.ParsedSyntaxTree.cs,ae8caa7afa30b1ab) passes the value thru to the constructor (only allowing null path in Release mode)
* VisualBasic matches the CSharp behavior

We should explicitly disallow null paths at the base layer by throwing an exception (rather than just asserting).

**Comment by tannergooding** [comment]
FYI. @dotnet/roslyn-compiler, @dotnet/testimpact

**Comment by gafter** [comment]
I'm afraid adding this requirement would be a breaking change for many API clients. It would be an interesting experiment to try adding the restriction and see how many things break.

We should either embrace the requirement or drop it.
