### ISSUE TITLE
Expression Evaluator Feature Request: Fix "The type ___ exists in both foo.dll and bar.dll" error

### ISSUE THREAD

**Issue by OmerRaviv** [dotnet/roslyn#1264]
When evaluating expressions in the debugger, it is not uncommon to stumble across this error message, where there is a type with the same name in the same namespace within different loaded assemblies. Especially with MEF-powered applications, this tends to happen more and more, and I've seen many developers get very frustrated with it.

As @jaredpar [noted on stackoverflow](http://stackoverflow.com/questions/1571958/how-can-i-qualify-a-net-type-with-assembly-name-for-visual-studio-debugger-to-d) , there is currently no workaround for the issue.

I propose the following simple solution - *if the currently executing assembly directly references only one of the assemblies that contain the type, use that one.* While one might argue that this behavior is inconsistent with the usual EE semantic scoping rules, I think the trade-off of fixing a very frustrating experience in 99% of cases is well worth it.

**Comment by WolfieWerewolf** [comment]
That's a great idea.. you should fork the repo and implement it  for us :-)

**Comment by cston** [comment]
With PR #1687, the EE now retries compilation in certain ambiguous error cases, retrying with only those assemblies directly referenced by the module containing the current frame. If retry fails, the original error is reported. This will not handle all cases of CS0433 (dropping assemblies may lead to other errors for instance) but it should handle some.

**Comment by OmerRaviv** [comment]
@cston @amcasey This is wonderful news! Thank you so much, you've just solved a very big pain point that was affecting many many users.
