### ISSUE TITLE
Support method calls with ref return values in VB

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#12659]
Support the ability to consume methods / properties which have a ref return type in VB.

**Comment by AdamSpeight2008** [comment]
Out of curiosity what would they look like?
```vb
Function Foo() As ByRef BarStruct
```

**Comment by jaredpar** [comment]
@AdamSpeight2008 this feature is the ability to consume the methods, not define them.

**Comment by cston** [comment]
Fixed in #12975.
