### ISSUE TITLE
[Flaky test] CSharpFixAllOccurrences fails intermittently

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#12651]
See http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/303/testReport/

**Comment by mavasani** [comment]
Failed again: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/345/

**Comment by mavasani** [comment]
Failed again: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_prtest/465/

**Comment by mavasani** [comment]
Failed again: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_prtest/471/testReport/junit/(root)/CSharpFixAllOccurrences/FixAllOccurrences_in_Document___Cancel/

**Comment by mavasani** [comment]
Another failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p2_open_prtest/6/

I am going to skip this test for now.

**Comment by mavasani** [comment]
Anotherr failure: https://github.com/dotnet/roslyn/issues/12651

**Comment by mavasani** [comment]
Another failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/427/

**Comment by mavasani** [comment]
Okay, so I ran this test multiple times in a loop and this seems like a product issue with the v2 IDE diagnostic engine - the diagnostics triggering the fix seem to be missing intermittently, causing the fix to show up only intermittently.

I am moving this this to area-analyzers and marking it a product issue. Tagging @heejaechang @srivatsn as FYI.

**Comment by mavasani** [comment]
More specifically, I see that active document diagnostics show up first (with squiggles), then after a bit the diagnostics and squiggles disappear and then eventually when full solution diagnostics show up in error list, it is missing diagnostics for open document. See [this](http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/428/artifact/Open/Binaries/Release/Screenshots/2016-08-15_23-33-34_04%20-%20Exception%20System.Reflection.TargetInvocationException.png) for example, we have no squiggles when light bulb is invoked.

**Comment by balajikris** [comment]
/cc: @kuhlenh I think the above comment points the bug you were observing with the recent builds?

**Comment by balajikris** [comment]
@kuhlenh mentions a simple repro and I see it as well. 
1. Write code that has a codestyle squiggle.
2. Ctrl + . and bring up the fix
3. Dismiss without applying any fix
4. The squiggle goes away and the fixes are no longer offered at that position 
5. Type more code and diagnostics are properly recomputed, the squiggle appears again.

Does this sound like the same issue as this one?

**Comment by mavasani** [comment]
Actually, there might be more than one issue. Just triggering the code fix seems to clear off the squiggles for some reason, and even cancelling the code fix while its still computing it doesn't seem to bring back the squiggles.

**Comment by mavasani** [comment]
@balajikris Surely seems related, but I think there might be issues with both the analyzer engine and code fix engine/squiggles infrastructure. I have seen cases with missing diagnostics and missing squiggles when diagnostics/fixes are present (basically same repro as you mentioned above, but only with squiggles missing at step 4).

**Comment by balajikris** [comment]
squiggles are indeed missing at step 4 in my repro as well.

**Comment by mavasani** [comment]
@balajikris I am basically talking about 2 separate issues here.

1. Diagnostics (and hence squiggles) are intermittently missing, which is causing this VSI test to fail.
2. Diagnostics are present, code fixes are also offered, but as soon as code fix is invoked, the squiggles go missing. Diagnostics are still present in error list and code fixes are also offered. This is unrelated to this VSI failure, I'll file a separate issue.

**Comment by balajikris** [comment]
I see! thanks.

**Comment by mavasani** [comment]
Filed https://github.com/dotnet/roslyn/issues/13233 for issue #2 mentioned [above](https://github.com/dotnet/roslyn/issues/12651#issuecomment-240571793)

**Comment by mavasani** [comment]
@heejaechang I am unable to repro intermittently missing diagnostics issue manually, but happens very frequently when running this test (once every other time). I think it needs invoking Ctrl + dot immediately after document is opened, but before open file diagnostics finished getting computed. When I attach the debugger to running test, I see a task cancelled exception while diagnostics are computed, so seems likely we not properly handling cancellation of open file diagnostic computation in v2 engine.

I am skipping this test as it fails almost every other PR. Please unskip once fixed.

**Comment by heejaechang** [comment]
what does it call ctrl+. upon?

**Comment by mavasani** [comment]
This is the failing action in the integration test: https://github.com/dotnet/roslyn-internal/blob/master/Closed/Hosting/RoslynTaoActions/IntegrationTests/CSharpFixAllOccurrences.xml#L16. You should be able to run the tao test locally and repro the failure.

**Comment by kuhlenh** [comment]
awesome, thanks @balajikris and @mavasani for investigating this!

**Comment by mavasani** [comment]
I have skipped this VSI test

**Comment by heejaechang** [comment]
@mavasani does this only repro if I run release?

**Comment by mavasani** [comment]
No repros with debug too - you probably have to run the test 2-3 times in a loop to get it to repro.

**Comment by heejaechang** [comment]
found the bug.

actually found 2 bugs.

one in diagnostic squiggle taggers and one in AnalyzerDriver.

the issue in diagnostic squiggle tagger is that, it didnt check workspace where the diagnostic are changed. due to that, it removed diagnostics for host workspace when diagnostics in preview workspace is removed (since id for both of them are same - since documentId are same for both workspace)

I have fix for that.

the issue in AnalyzerDriver is this

http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerDriver.cs,1699
 var declarationAnalysisData = compilationData.GetOrComputeDeclarationAnalysisData(
                decl,
                allocateData => ComputeDeclarationAnalysisData(symbol, decl, semanticModel, shouldExecuteSyntaxNodeActions, analysisScope, allocateData, cancellationToken),
                cacheAnalysisData);

GetOrComputeDeclarationAnalysisData caches declarationAnalysisData only based on declaration, but the data it caches (DeclarationAnalysisData) depends on more context than declaration node. such as analysisScope. more specifically FilterSpanOpt or executeSyntaxNodeActions flag.

due to that, it now has a race where depends on what analyzer are loaded to VS first, some syntax node action works, or some other one doesn't. I made a fix but not sure whether that is correct one or not.

**Comment by heejaechang** [comment]
two fixes
https://github.com/dotnet/roslyn/pull/13241
https://github.com/dotnet/roslyn/pull/13242

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-internal/pull/1258. Thank you @heejaechang
