### ISSUE TITLE
Create CSharp .targets NuGet package for .NET Core

### ISSUE THREAD

**Issue by eerhardt** [dotnet/roslyn#12650]
**Version Used**: all

**Steps to Reproduce**:

1. Try to use the Microsoft.CSharp.Core.targets file to use MSBuild to build a project on the .NET Core CLI

**Expected Behavior**:
There should be an officially supported NuGet package containing the .targets file that can build a project invoking "Csc" on .NET Core.

**Actual Behavior**:
That package doesn't exist today.

There *is* a package on the dotnet/buildtools feed that does this, but it isn't an official Roslyn package.  See https://dotnet.myget.org/feed/dotnet-buildtools/package/nuget/Microsoft.Net.Compilers.Targets.NetCore.  Basically, the CLI team needs the functionality of this package, only in an officially supported NuGet package.

@davkean @agocke

**Comment by sfmskywalker** [comment]
Eric, am I correct in understanding that the package on the dotnet/buildtools should in principle enable Roslyn on projects targeting netcoreapp1.0?

**Comment by eerhardt** [comment]
> Eric, am I correct in understanding that the package on the dotnet/buildtools should in principle enable Roslyn on projects targeting netcoreapp1.0?

Yes, it does enable Roslyn for netcoreapp1.0, but it is not an "official" package.  So I don't think it is supported if you run into any issues.  Basically I don't recommend using this package outside of the current places it is being used (by repos that use the buildtools).

**Comment by sfmskywalker** [comment]
Got it. Thanks

**Comment by agocke** [comment]
Dup of #9640
