### ISSUE TITLE
Template analyzer test are inconsistent multiple occurrences if multiple fixes

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/roslyn#1265]
This issue arises in testing code fixes with the default template test infrastructure. 

Definitions:
"Multiple occurrences" for a test is a single string that has multiple triggering occurrences.
"Multiple fixes" is a code fix that offers more than one option

If the file is being tested for a single fix (null is passed for the codeFixIndex), then multiple occurrences are applied to the file before comparison. 

If there are multiple fixes and a specific fix is being tested (a value is passed for codeFixIndex), then only the first occurrence is applied. 

This occurs because of the conditional and break around line 92-96 of CodeFixVerifier.cs (the codeFixIndex is explicitly compared to null, and the break results in the inconsistent behavior). 

All code occurrences of the requested code fix should be tested prior to comparing the document.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #32](https://github.com/dotnet/roslyn-sdk/issues/32) via [**ZenHub**](https://www.zenhub.com/)
