### ISSUE TITLE
Testing Code Fixes does not allow alternate spacing or other formatting

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/roslyn#1266]
When documents are compared after applying code fixes during testing, obviously, every character counts :)

The default of 4 spaces in the workspace used for creating the fixed documents is arbitrary, and results in significant challenges in creating test data when the developers machine uses a different spacing. 

I suggest modifying the VerifyCSharpTestFix and VerifyBasicTestFix methods to accept workspace options that can be added to the workspace prior to applying the new document. 

Allowing workspace formatting options here is preferable to allowing the indent space value because there are other formatting options someone may wish to apply. 

I've done this in my copy if you would like to see that code.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #33](https://github.com/dotnet/roslyn-sdk/issues/33) via [**ZenHub**](https://www.zenhub.com/)
