### ISSUE TITLE
Verbatim strings in GridOptionPreviewControl.xaml

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#12669]
https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Impl/Options/GridOptionPreviewControl.xaml#L101

has verbatim strings, these should be resources bound through the viewmodel.

**Comment by rchande** [comment]
cc @balajikris

**Comment by Pilchie** [comment]
Did you fix this already?

**Comment by MattGertz** [comment]
@Pilchie @dpoeschl Looking at the file in the current version of the file in master, "header" is at least still hard-coded.

**Comment by dpoeschl** [comment]
@Pilchie @MattGertz This is *not* fixed yet.

**Comment by dpoeschl** [comment]
And it impacts Naming Styles too.

**Comment by dpoeschl** [comment]
This is now fixed by #14945
