### ISSUE TITLE
Ensure syntax model capable of handling wildcards

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#12664]
See #12619 for context.  That issue describes the ability to insert wild card place holders into deconstruction expressions.

The use of wild cards in deconstruction as a language feature is not going to be a part of the 2.0 release.  It will come later either in 2.1 or 3.0.  However this part of the syntax model is already being rev'd for the 2.0 release.  We should take the time to ensure it can handle the wildcard syntax without major changes when we do implement it.

**Comment by gafter** [comment]
In order to address this, I am working on a revised syntax model for deconstruction declarations.
