### ISSUE TITLE
Microsoft.Net.Compilers.netcore needs to be updated for netstandard

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn#12674]
The package `Microsoft.Net.Compilers.netcore` currently has support for `dotnet` and `netcoreapp1.0`. `dotnet` should be switched to `netstandard1.0` so that the latest compilers can be used more easily with CLI projects until the msbuild transition.

**Comment by agocke** [comment]
@onovotny Do you think you could give a little background on your use case for this? This package was a bit of a hack to just get things in the right place for .NET CLI so I'd be curious how other people are using it.

**Comment by onovotny** [comment]
At the time, I was trying to use it so I could use c# features in an xproj easily...so I wanted to include its toolchain to override the built-in one. Guess it's not terribly relevant at this point long as there's eventually a way to experiment with pre-release Roslyn compilers via NuGet packages ... don't want to install anything so that it "just works" on build servers and for project members that may be cloning/contributing to a code-base.

**Comment by agocke** [comment]
@onovotny Thanks, good to know. I'm not sure this package would even work in that scenario, but that's definitely a scenario we need to cover.
