### ISSUE TITLE
Microsoft.Net.Compilers with project.json-based csproj doesn't install

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn#12673]
The `Microsoft.Net.Compilers` package has its main entrypoint in `build\Microsoft.Net.Compilers.props`. The problem is that doesn't work with `project.json` based projects as it doesn't support "TFM-less" imports. 

The fix is to put/copy the props file into `build\netstandard1.0\...` and any other supported TFM like `build\sl5`, `build\net2`, etc, so it gets properly picked up. Of course the relative path to the tools directory will need an extra `..\` as well.

**Comment by jaredpar** [comment]
Closing as our expectation is this should just work given the changes to CLI to be MSBuild based.  Please push back if you disagree.  

 https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/
