### ISSUE TITLE
Inline Temp sometimes incorrectly positions the caret

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#12683]
**Version Used**: VS2015 Update 3 (14.0.25421.03)

**Steps to Reproduce**:
1. Copy/paste C#:
   
   ``` C#
   using System.Collections.Generic;
   class Program
   {
       private void Test1(List<int> line) // Inline Temp places the caret between the 'l' and first 'i' of "line"
       {
           var newLine = line;
           newLine.RemoveAt(0);
       }
   
       private void Test2() // Inline Temp places the caret at the beginning of the line (before "System")
       {
           int xyz = 7;
           System.Console.WriteLine(xyz);
       }
   }
   ```
2. Run Inline Temp on `newLine` in both `Test1` and `Test2`

**Expected Behavior**: The caret should be placed consistently. I think it should go to the start of the newly created line.

**Actual Behavior**: In `Test1`, the caret is placed between the 'l' and first 'i' of "line"

**Comment by dpoeschl** [comment]
(Updated the "Actual Behavior" -- the caret is between the 'l' and 'i' of "line", not the 'n' and 'e' of "newLine" (which no longer exists after inlining).

**Comment by CyrusNajmabadi** [comment]
Closing out for lack of feedback.
