### ISSUE TITLE
Inline Temp breaks formatting in certain cases

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#12682]
**Version Used**: VS2015 Update 3 (14.0.25421.03)

**Steps to Reproduce**:
1. Copy/paste C#:
   
   ``` C#
   using System.Collections.Generic;
   using System.Linq;
   class Program
   {
       private void Test1(List<int> line) // Inline Temp on "newLine" breaks formatting
       {
           var newLine = line.ToList();
           newLine.RemoveAt(0);
       }
   
       private void Test2(List<int> line) // Inline Temp on "newLine" works fine (only difference is missing ".ToList()")
       {
           var newLine = line;
           newLine.RemoveAt(0);
       }
   }
   ```
2. Run Inline Temp on `newLine` in both `Test1` and `Test2`

**Expected Behavior**: In both cases, the resulting line should be indented properly

**Actual Behavior**: In `Test1`, the resulting line is left aligned (at Column 1)

**Comment by CyrusNajmabadi** [comment]
I get:

![image](https://user-images.githubusercontent.com/4564579/198729431-f9b2fd80-791d-4e7d-a740-2a33de9f8fbe.png)

Which looks appropriate.  Closing out.
