### ISSUE TITLE
Re-enable integration tests that are disabled after moving to Dev15

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#12698]
PR https://github.com/dotnet/roslyn-internal/pull/1186 enables running integration tests on machines with only Dev15. This causes couple of tests to fail in Jenkins, where we currently run tests on Dev14 U3:
1. BasicIntellisense ETA test: This test passes locally for me on a Dev15 machine with the above PR. Additionally the corresponding VSI test is still passing in Jenkins, so we have coverage.
2. CodeAnalysisRulesetEditor VSI test: This test fails on Jenkins after the above change and needs to be fixed/re-enabled once we move Jenkins to Dev15.

This issue tracks enabling both the above tests once we move Jenkins to Dev15.

**Comment by mavasani** [comment]
CodeAnalysisRulesetEditor VSI test has been re-enabled. BasicIntellisense ETA test is still failing consistently, hence it is still skipped. Keeping the issue open to track BasicIntellisense ETA test

**Comment by DustinCampbell** [comment]
@mavasani: What's the status of this? We just had a regression in VB completion that would have been caught by BasicIntellisense. (It was eventually caught when VSI tests were run.)

**Comment by mavasani** [comment]
I haven't looked at it since. Someone from IDE or infraswat should investigate

**Comment by DustinCampbell** [comment]
@jasonmalinowski: Is this on our backlog?

**Comment by jasonmalinowski** [comment]
Actually we already have individual tracking bugs.
