### ISSUE TITLE
Proposal: [DoesNotReturn]

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#127]
## Background
The C# compiler does analysis to determine whether certain blocks of code are unreachable.  This is helpful in warning developers about dead code, which is not only useful for minimizing code size, but also in avoiding bugs that occur due to a developer not realizing that certain code will never be executed, often because of a simple mistake in how code was structured.

    static void Main(string[] args)
    {
        if (args == null || args.Length < 3)
            goto fail;
        if (args[0] != "arg0")
            goto fail;
        if (args[1] != "arg1")
            goto fail;
            goto fail;
        if (args[2] != "arg2") // Warning: unreachable code detected
            goto fail;
        return;
    fail:
        throw new Exception("Fail");
    }

## Problem
This kind of analysis is often hampered by method calls that never return.  Some such methods are ones that cause the process to exit, such as Environment.FailFast.  Other such methods are ones that always throws an exception, such as ExceptionDispatchInfo.Throw, or more generally helper methods for throwing exceptions.  If such methods could inform the compiler that they never return to the caller via normal control flow, the compiler could factor that information into its analysis.

## Solution
The compiler could understand a new attribute, System.Runtime.CompilerServices.DoesNotReturnAttribute, which would have two effects. First, the compiler would validate the implementation of a method annotated as [DoesNotReturn] to confirm that there’s no way in which the method could return successfully to its caller.

    [DoesNotReturn]
    static void Throw(string message) // Error: [DoesNotReturn] method may return
    {
        if (message != null) {
            throw new Exception(message);
        }
    }
    
Second, at call sites to methods annotated as [DoesNotReturn], the compiler would be free to assume that the method will never return, and can thus factor that into its unreachable code analysis.

    static void Main(string[] args)
    {
        Throw("test");
        Console.WriteLine(args[1]); // Warning: unreachable code detected
        return;
    }
    
(Because of this, methods annotated to be [DoesNotReturn] could also potentially be used in expressions where a value was expected, e.g. `string result = GetValue() ?? ThrowInvalidOperation();`.)

In order to satisfy rules on code flow that the underlying runtime imposes, and in order to deal with cases where the attribute is erroneously applied (such as manually in a method implemented in MSIL directly), the compiler would insert implicit ‘return;’ or ‘return default(TResult);” after calls to [DoesNotReturn] methods; the actual value returned doesn’t matter, because these statements will never be reached.  In some situations, though, such as in a finally block, a “return;” is invalid, so in such situations, the compiler would inject code that it can be sure will never return, e.g. “while (true);”.

**Comment by theoy** [comment]
Note, this is equivalent to Issue #59 filed by @knat, for further discussion :smile:

**Comment by VSadov** [comment]
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     is one of such methods.

It is used by C# compiler when emitting code like 
```
            try
            {
                return FooBar();
            }
            catch (Exception)
            {
                await Task.Yield();

                // helper is used here to re-throw without losing logical stack trace.
                throw;                       
            }
```
If, however, you try doing similar expansions by hand, you would get into problems with compiler still requiring you to return on all paths since formally it has not way to know that "Throw()" never returns.

**Comment by VSadov** [comment]
"throw null"   could be more appropriate piece of code to inject right after nonreturning calls. It is attractive because:
* it is very compact. Just 2 bytes.  {ldnull; throw}
* it is valid in all contexts including exception handlers
* if callee happens to violate the contract of not returning, we get an exception thrown.

**Comment by theoy** [comment]
I agree that there are benefits to "throw null", though I think users are more accustomed to relevant exception types (even if sometimes the exception hierarchies don't make as much sense). For example, ExecutionEngineException or AccessViolationException for bad things that typically aren't intended by user code.

I think if we supported decorated methods like this, then we'd probably categorize the error as similar to some sort of contract violation.

**Comment by stephentoub** [comment]
@VSadov, thanks.. I mentioned ExceptionDispatchInfo.Throw in my write-up as an example :smile:, but I wasn't aware the compiler actually generated code to use it directly.  I know we use it inside of Task and TaskAwaiter; is that what you meant, or does the compiler actually generate code to use ExceptionDispatchInfo directly?

Regarding what code we'd generate after a call to a [DoesNotReturn] method, I agree it makes sense to generate a throw instead of a return, good suggestion.  I'm less interested in the specific exception type that's generated, but then again I've never been one to put much stock in what type of exception is thrown for usage errors, and would be happy if such cases fail fasted with good diagnostics to help the developer understand what they did wrong.

**Comment by stephentoub** [comment]
@VSadov, nevermind, answered my own question, the compiler does generate code to use it directly... neat... https://github.com/dotnet/roslyn/blob/1e813498166204bded1df439a6459f8c76e6ce2c/src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs#L426

**Comment by VSadov** [comment]
@theoy , Since this exception would be thrown in "impossible" cases, I do not think it is worth producing elaborate diagnostics. However I agree, since it is not completely impossible, more strongly typed exception could be helpful here for some scenarios. Ideally we would throw some static singleton.

An interesting example of existing synthetic unreachable codegen is a case of "blocked by finally". However that case is slightly different. We _are_ 100% sure it is unreachable, therefore infinite loop is a better choice there.
```C#
        static int Test()
        {
            try
            {
            }
            finally
            {
                throw new Exception("code after try is unreachable");
            }

            // but we need to have some code here!!!
            // Since try's end is reachable, it needs to leave somwhere.
            // In addition to this, it is not allowed to fall through the 
            // end of the method without returning.
            //
            // To get out of this predicament, compiler emits 
            // infinite loop here. It is 100% unreachable anyways.
            //
            //  L1: goto L1;
        }
```

**Comment by gafter** [comment]
This is a dup of #59.

**Comment by GF-Huang** [comment]
Why can not use this for constructor? In WPF, a parameterless constructor is usually used for design time. It's need something attribute to tell analyzer do not check it.
