### ISSUE TITLE
CS0123 (no overload matches delegate) should offer 'Generate method' quick action

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#12708]
**Version Used**: 15.0.25428.1/2.0.0.60620

**Steps to Reproduce**:

``` C#
using System.Collections.Specialized;

class Program
{
    void Main(string[] args)
    {
        INotifyCollectionChanged collection = null;
        collection.CollectionChanged += OnChanged;
    }

    private void OnChanged() { }
}
```

**Expected Behavior**:
Quick action to generate `OnChanged(object, NotifyCollectionChangedEventArgs)` method to be offered.

**Actual Behavior**:
`CS0123 No overload for 'OnChanged' matches delegate 'NotifyCollectionChangedEventHandler'`
No quick actions available here.

**Comment by Pilchie** [comment]
Agreed - this would be nice to have.  Probably a pretty simple thing to contribute.
