### ISSUE TITLE
Nested types are overqualified in new operator

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#12701]
**Version Used**: 15.0.25428.1 / 2.0.0.60620

**Steps to Reproduce**:

```C#
namespace ConsoleApplication1
{
    class Program
    {
        class Nested { }
        static void Main(string[] args)
        {
            Nested n = new |
        }
    }
}
```
Use the `Nested` suggestion from autocomplete list by typing `(`.
(note that it does not repro using Enter)

**Expected Behavior**:
```C#
Nested n = new Nested(|
```
**Actual Behavior**:
```C#
Nested n = new ConsoleApplication1.Program.Nested(|
```
And quick fix is offered to get rid of the qualification. I believe this is a regression. The fact that the type is nested might not be critical.

**Comment by Pilchie** [comment]
We were unable to repro this, but I believe @CyrusNajmabadi fixed a related issue with nested types quite recently.
