### ISSUE TITLE
Allow end users to explicitly configure closed file execution of analyzers in IDE

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#12713]
IDE diagnostic engine currently decides whether or not to run analyzers on closed files based on whether or not the analyzer reports any non-hidden diagnostics. This seems like a very fragile approach, which has caused multiple performance regressions for IDE full solution analysis. Additionally, when an end user bumps up the severity of any IDE hidden diagnostic, they have absolutely no idea that they are paying a very large IDE performance cost.

We should remove this hack in the IDE diagnostic engine and allow the end-user to explicitly configure whether or not to run IDE analyzers for closed files – either per rule basis or a single workspace wide setting. We should extend the IDE tools option UI that allows changing the per-rule severity to add this closed file setting(s). I’ll file an issue to track this.

**Comment by Pilchie** [comment]
Let's settle on a design for this soon so that we can get it implemented.

**Comment by JarLob** [comment]
Is there a recommended workaround if I actually want to analyze whole solution? Should I open all files one by one? Any other way to open all files with less clicks or to analyze all solution without opening all files?

**Comment by ohadschn** [comment]
I changed all `IDEXXXX` severities to `warning` and they still aren't executed on closed files. 
My environment:

> Microsoft Visual Studio Enterprise 2017 
> Version 15.2 (26430.14) Release
> VisualStudio.15.Release/15.2.0+26430.14
> Microsoft .NET Framework
> Version 4.7.02046

**Comment by CyrusNajmabadi** [comment]
@mavasani was this done?  i thought you added options for this.

**Comment by CyrusNajmabadi** [comment]
Closing out as we have options for this.
