### ISSUE TITLE
The peculiar case of the vanishing squiggle

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#12718]
**Version Used**: VS2015 Update 3

**Steps to Reproduce**:

1. File > New Project > C# > Console
2. Add a line with a squiggle, e.g. `var s = "hello";` has a squiggle about unused variable `s`
3. Press ctrl+dot to bring up the quick action menu
4. Press Escape to close the quick action menu

**Expected Behavior**:

The squiggle should remain

**Actual Behavior**:

The squiggle vanishes.
![disappearingsquiggles](https://cloud.githubusercontent.com/assets/3316258/17111370/18a174b4-5256-11e6-9c48-1d852ef46dea.gif)

**Comment by Pilchie** [comment]
@heejaechang you fixed this, right?

**Comment by heejaechang** [comment]
yep

**Comment by balajikris** [comment]
yes this is fixed.
