### ISSUE TITLE
IDE analyzers shouldn't execute on closed files by default

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#12714]
When full solution analysis is enabled, IDE analyzers, such as simplify type name (are there more?), are currently executing on closed files as it reports descriptors with non-hidden severity. IDE diagnostic engine currently decides whether or not to run analyzers on closed files based on whether or not the analyzer reports any non-hidden diagnostics  - and this has severe performance impact as these analyzers are very expensive to run on closed files.
https://github.com/dotnet/roslyn/issues/12713 tracks adding an explicit tools option to configure closed file execution for analyzers in IDE. Until that has been implemented (which seems likely to be post preview 4), we should change IDE analyzers to only report hidden diagnostic descriptors so they don't end up running for closed files.

**Comment by Pilchie** [comment]
Note that it's not quite that trivial.  Some of these can now be configured to report other severities, in which case they do need to be run for closed files.

**Comment by mavasani** [comment]
Agreed, and we have separate issues to enable users to explicitly configure closed file analysis we should consider implementing it for RC.
However, we should at least turn off super expensive analyzers such as simplify type name for closed files. Otherwise, enabling full solution diagnostics will make IDE almost unusable - I have FSD on for Roslyn.sln and I had to suppress simplify type name to improve IDE perf.

**Comment by Pilchie** [comment]
Unfortunately, we are not going to be able to do this for Preview4, but we need to do it for Preview 5.

**Comment by mavasani** [comment]
@dpoeschl has a fix for this..
