### ISSUE TITLE
IDE style settings in tools options should be translated into a workspace level ruleset

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#12715]
IDE analyzers, whose severity can be configured at workspace level via tools options, currently take the approach of reporting multiple duplicate descriptors which differ just by severity and then switch on workspace level style setting to decide which descriptor to use for reporting diagnostics. This has couple of bad effects:
1. Multiple ways to configure severity for analyzers: We use the ruleset editor and the ruleset to configure per-project analyzer rule severities, but use the tools options UI for workspace wide settings. We have talked about unifying both these into a common editorconfig file and UI, but until that is implemented, we are stuck with 2 different ways of doing similar configuration at different analysis scopes.
2. Each IDE analyzer which is configurable at workspace level way needs to be aware about this workspace wide setting and apply the option at every place it reports diagnostics. This can cause functionality issues and has already caused performance regressions couple of times (see https://github.com/dotnet/roslyn/issues/12714). We should consider translating these Workspace level per-rule severity settings into a Workspace level ruleset and thread that as compilation options for every design time compilation.

This issue tracks addressing (2) above. It is probably jointly owned by the analyzers and IDE team.

**Comment by Pilchie** [comment]
Let's close on what we want to do here and get it done.

**Comment by Pilchie** [comment]
@dpoeschl @heejaechang @mavasani We don't need this right now, right?

**Comment by heejaechang** [comment]
we probably don't need this once this information merged into editorconfig file. but @mavasani is probably best person to answer

**Comment by kuhlenh** [comment]
@mavasani -- do we have a final plan here?

**Comment by Pilchie** [comment]
I don't think we need this right now - we are getting IDE options into the OOP workspace now.
