### ISSUE TITLE
Nuget Package problems with the .net 4.5

### ISSUE THREAD

**Issue by Kamarey** [dotnet/roslyn#12712]
**Version Used**: 
1.3.2 (https://www.nuget.org/packages/Microsoft.CodeAnalysis)

1. Despite the package marked with the 1.3.2 version, after installing it all referenced assemblies are 1.3.1.0. It's not the problem for me, just strange.
2.  This package doesn't work with the .NET 4.5 due to  the following error:

> C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary r
> eference "Microsoft.CodeAnalysis.Workspaces.Desktop, Version=1.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35,
>  processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5.2" fram
> ework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".

**Comment by Pilchie** [comment]
Tagging @shyamnamboodiripad.

**Comment by jmarolf** [comment]
@shyamnamboodiripad @Pilchie  I thought 4.5.2 was the minimum required version for our packages to run?  Isn't this by design?

**Comment by svick** [comment]
@jmarolf Then why does the package (I'm specifically looking at [Microsoft.CodeAnalysis.Workspaces.Common 1.3.2](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Workspaces.Common/1.3.2)) still claim it supports .Net 4.5 by using the `net45` directory name and by having "Supported Platforms: - .NET Framework 4.5" in its description?

**Comment by jmarolf** [comment]
@svick you're right, looks like we need to update Microsoft.CodeAnalysis.Workspaces.Common to be net452

**Comment by jasonmalinowski** [comment]
We're tracking the full work here with #12444, as we need to really split these packages apart since much of it is actually portable now.
