### ISSUE TITLE
IDE suggests to add irrelevant packages

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#12720]
**Version Used**: VS2015 Update3

The quick-fix options available to me in this .NET Core console app are misguided:

![addpackage2](https://cloud.githubusercontent.com/assets/3316258/17116447/b5e75110-526c-11e6-921b-3329e3c8a36c.png)

* Suggestion1: add "using System.Threading;"
* Suggestion2: add "using System.Threading and also add a NuGet reference to Microsoft.Bcl 1.1.9"
* Suggestion3: add "using System.Threading and also add a NuGet reference to System.Threading.Tasks 4.0.11"

In the face of Suggestion1, I think that Suggestions2+3 are *worse than useless*. Consider the possibilities of Suggestion3:
1. Maybe System.Threading.Tasks 4.0.11  will bring in a reference to the same System.Threading.CancellationToken that's already referenced by my assemblies. Therefore, Suggestion1 alone would have worked, and the only thing that Suggestion3 does is clutter up my project.json with superfluous references.
2. Maybe System.Threading.Tasks 4.0.11 will bring in a reference to a different System.Threading.CancellationToken from what's already referenced by my assemblies. Therefore, Suggestion1 alone would have worked, but Suggestion3 will deliver me an "ambiguous type" error.

Suggestion2 has the same faults. But additionally, I think that Microsoft.Bcl is just the wrong thing to put into a .NETCore app. I don't think it is able to bring any benefit there. It's sole purpose was so that PCLs could target a uniform surface area between .NET4 and .NET45.

**Comment by Pilchie** [comment]
Tagging @CyrusNajmabadi I thought we didn't show suggestions from NuGet is we already have a regular add using?

**Comment by Pilchie** [comment]
Note also that Add-NuGet is currently unaware of TFMs, but probably should be made aware (which will be easier once .NET Core projects are msbuild based).

**Comment by Pilchie** [comment]
Oh - wait.  This is in a project.json based project, right?  This is the Add-Nuget lightbulb that the Asp.NET team built before, not the one we built.

**Comment by ljw1004** [comment]
Yes it's a project.json project. File>New>C#>.NETCore>Console.

**Comment by CyrusNajmabadi** [comment]
This is not roslyn :)  Also concerning ot me is that these items show up twice in the list:

![image](https://cloud.githubusercontent.com/assets/4564579/17119394/6c422e32-527a-11e6-8552-42cea137bda2.png)

**Comment by ljw1004** [comment]
```
void f(CancellationToken cancel = default(CancellationToken))
```

I bet it showed up once on the list for the first CancellationToken, and once for the second.

I'll close this bug since I'm sure your implementation will be far better, Cyrus.

**Comment by chlowell** [comment]
The new implementation is better but including packages from the local cache can result in dubious suggestions:

![image](https://cloud.githubusercontent.com/assets/10964656/17670165/8b3ca532-62c5-11e6-8dd6-949d562e7caa.png)

I see `System.Private.*` packages are ignored; is this only an issue with prerelease packages?

**Comment by CyrusNajmabadi** [comment]
The implementation you're seeing is not the Roslyn implemention.  Ours does not start with 'Add package' :)

**Comment by chlowell** [comment]
The screenshot is from Update 3, which I thought replaced the prior implementation with Roslyn's. Do I need to install it separately?
