### ISSUE TITLE
Edit-and-continue needs to be disabled for foreach loops that contain out vars

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#12736]
See also #1503, #12688 
/cc @tmat @jaredpar 

Because out vars and patterns can introduce variables in the expression of a `foreach` loop, but the declaration of the `foreach` loop is not represented as a node, the current approach to edit-and-continue will break if a `foreach` loop contains either _out variables_ or pattern-matching in the expression. We will either need to disable edit-and-continue somehow, or begin parsing the `foreach` loop into a new node form that contains a syntax node for the variable declaration. The latter is proposed in #12688.

/cc @CyrusNajmabadi @jcouv @VSadov

**Comment by AdamSpeight2008** [comment]
Or make it an error in those cases.

**Comment by jcouv** [comment]
With PR https://github.com/dotnet/roslyn/pull/13754, edits are disallowed in an active method that has any out var.
