### ISSUE TITLE
Codelens is missing references from VB projects

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#12731]
[Build: VS2015.3]

Open SimplificationOptions.cs in Roslyn.sln and pick any member that is referenced from C# and VB projects. Say `PreferIntrinsicPredefinedTypeKeywordInDeclaration` for example.

Notice that codelens results differ from FAR results. It appears that codelens is missing results from VB. Not sure if this is a widespread issue or something in Roslyn.sln or because of whatever refactorings I locally made to Roslyn.sln. In any case this is a bug, but we need to determine how severe this is.

![image](https://cloud.githubusercontent.com/assets/4213867/17121264/54958d08-5287-11e6-8360-b1e58807f5a3.png)

**Comment by Pilchie** [comment]
Tagging @brettfo - I wonder if this is a symbol equivalence issue related to PCLs and System.Object being from System.Runtime instead of mscorlib.  We've had a few places where @brettfo had to loosen up some checks.

**Comment by brettfo** [comment]
@balajikris: look at #9056 and #9363 to see how I fixed this for FAR.

**Comment by balajikris** [comment]
Interesting point. Thanks guys, will check.

**Comment by balajikris** [comment]
another case:
![image](https://cloud.githubusercontent.com/assets/4213867/17338724/6339527e-589d-11e6-9314-eab538a4704a.png)

**Comment by Pilchie** [comment]
Is this still an issue now that @panopticoncentral has moved CodeLens to Roslyn?

**Comment by panopticoncentral** [comment]
This appears to be fixed on the current RC2 builds.
