### ISSUE TITLE
Move type to file: expose an option for cleaning up source file using directives.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#12730]
Not yet implemented.

current design automatically cleans up unused using directives in source file after moving a type to new file.
It is better to perhaps leave them behind (because the user will be offered a remove unused usings quick fix), or expose an option to set the desired behavior.

**Comment by Pilchie** [comment]
Triage thinks we should just leave them.  If/when we later add the ability to auto-apply fixes, this would be part of that.
