### ISSUE TITLE
SemanticClassificationViewTaggerProvider is tied to C#/VB Only

### ISSUE THREAD

**Issue by otawfik-ms** [dotnet/roslyn#12732]
In the [SemanticClassificationViewTaggerProvider](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/Classification/SemanticClassificationViewTaggerProvider.cs) class, the implementation is tied to C# and VB content types.
It needs to be edited to extend all Roslyn content types for F# to use it.

Special care needs to be taken to ensure this doesn't break Typescript as they have their own workaround in their compiler server.

/cc @CyrusNajmabadi

**Comment by Pilchie** [comment]
@otawfik-ms are you going to work on a PR to address this, or do you need someone else to?

**Comment by otawfik-ms** [comment]
@Pilchie I don't think I'll have capacity to work at this in the near future. It would be awesome if someone can pick it up.

**Comment by CyrusNajmabadi** [comment]
@paulvanbrenk @vladima @mgoertz-msft Do any of you have a problem if i export  https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/Classification/SemanticClassificationViewTaggerProvider.cs with the Roslyn content type?

Effectively if you do not export a "IEditorClassificationService" then this should have no effect on you.

**Comment by paulvanbrenk** [comment]
Looks like we don't export that.
