### ISSUE TITLE
Options need to be internal

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#12739]
**From API Review**

The feeling is the new options support will not be ready for public consumption at 2.0 RTM.  In particular the feature is still under development and there is a strong feeling these options may move into the compiler layer very soon.  As such for 2.0 RTM they should be made internal. 

This includes:
- `Document.Options`
- `Solution.Options`
- `Microsoft.CodeAnalysis.Options.DocumentOptionSet`

**Comment by Pilchie** [comment]
I think we're going to live with these, and will have to obsolete them if necessary.
