### ISSUE TITLE
SimplificationOptions review

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#12740]
**From API Review***

It's unclear if the type `Microsoft.CodeAnalysis.Simplification.SimplificationOptions` is ready for consumption in 2.0RTM.  The general feeling was that it needed to be delayed.  Please review and make a decision about this API.

**Comment by Pilchie** [comment]
The only new options here are 
```
Microsoft.CodeAnalysis.Simplification.SimplificationOptions.QualifyEventAccess.get
Microsoft.CodeAnalysis.Simplification.SimplificationOptions.QualifyFieldAccess.get
Microsoft.CodeAnalysis.Simplification.SimplificationOptions.QualifyMethodAccess.get
Microsoft.CodeAnalysis.Simplification.SimplificationOptions.QualifyPropertyAccess.get
```

The rest are existing public APIs.  These ones replace some [Obsolete]d options from before, so we'd be taking away functionality if we made them internal.
