### ISSUE TITLE
CompletionService.ChooseBestItems changes

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#12746]
**From API Review**

The API `CompletionServices.ChooseBestItems` needs the following changes:

- Method renamed to `FilterItems`
- Parameter `filteredItems` renamed to `items`
- Pass along the position in the document where the completion occurs.

**Comment by CyrusNajmabadi** [comment]
@jaredpar 

> Pass along the position in the document where the completion occurs.

I'm going to push back on this one.  While the 'GetCompletionsAsync' API *does* pass the caret position, the other APIs here do not.  Specifically APIs like "GetDescriptionAsync" only pass the document and completion item.  Similarly, "GetChangeAsync" does not pass the position.

Note that if a completion provider needs this data, they can store it in the completion items they produce as we have a general mechanism for passing along simple data types.  Our API pattern here is to pass along data that the provider does not have access to.

**Comment by CyrusNajmabadi** [comment]
Tagging @mattwar for his thoughts as well.

**Comment by mattwar** [comment]
As Cyrus said, if the provider/service needs this info to help react to this API it can squirrel it away in the item properties.

As for the name changes, I'd need to confer with Cyrus on the explicit task that the API is performing to know which terminology is best.

**Comment by CyrusNajmabadi** [comment]
I like the name changes a lot.  My only concern was about "Pass along the position in the document where the completion occurs."

**Comment by CyrusNajmabadi** [comment]
thanks matt!

**Comment by jaredpar** [comment]
Sounds good to me.
