### ISSUE TITLE
Review Obsolete usage in API

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#12745]
**From API Review**

During the API review it came up that the IDE made use of the `ObsoleteAttribute` to flag APIs which should no longer be used.  This did not pass the error flag though and hence these come up as warnings.  To be consistent with the compiler team these should be raised as errors.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/13006
