### ISSUE TITLE
Consider having LanguageVersion.Latest

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#12748]
**From API Review**

Presently the compiler hard codes a language version as the default for values like `CSharpParseOption.ctor`.  This means on every iteration of the language we have to change a default value.  Our consumers never get this default unless they recompile where we'd prefer them to use the latest. 

The compilers should have a value `LangaugeVersion.Latest` which is interpreted as the latest version of the langauge.  Places where we hard code `LanguageVersion.CSharp7` today should be changed to `Latest`

**Comment by AdamSpeight2008** [comment]
Shame that `LanguageVersion` is `enum` and not it's own structure.
Then we could supply a compile-time constant, as well as having support for minor releases.
```c#
struct LanguageVersion
{
  public VersionNumber Version() { get; }
  public static LanguageVersion { get; } = LanguageVersion.Supported.Latest;

 public static class Supported
 {
   public LanguageVersion CSharp7 = new LanguageVersion( Languages.CSharp, major: 7, minor: 0);
   public LanguageVersion CSharp6 = new LanguageVersion( Languages.CSharp, major: 6, minor: 0);
   public LanguageVersion Latest => CSharp7;
}
```

Could have language Feature be expressed language version.
```c#
CSharp6( inherits: CSharp5, major: 6, minor: 0,
 features: { Features.InitialisersAutoProperty,
	     Features.GetterOnlyAutoProperty,
	     Features.ExpressionBodiedMethodMembers,
	     Features.ExpressionBodiedPropertyFunctionMembers,
 	     Features.UsingStatic,
	     Features.NullConditionalOperators,
	     Features.StringInterpolation,
	     Features.NameOf,
	     Features.IndexInitialisers,
	     Features.ExceptionFilters,
	     Features.AwaitInCatchFinally
	   }
        )
```

**Comment by AdamSpeight2008** [comment]
Can i recommend.
```c#
enum LanguageVersion
{
  Latest = 0.
  CSharp5 =5,
  CSharp6= 6.
  CSharp7 = 7.
}
```
Then `latest` is the default value of the type. If you do this this you'll also need to change the FeatureCheck function to take it into account.

**Comment by AdamSpeight2008** [comment]
Whilst we're thinking about add an new language version. Could we also have `VNext` for experimental features, so it easier to change, should they get an official release version.
```
VNext = Integer.MaxValue
```

**Comment by AdamSpeight2008** [comment]
@gafter I don't agree that this should be `2147483647 (Int32.MaxValue)`, it makes more sense to be `0` the default value for the type can be use. Eg Default to the Latest Version. _Which will work with a potential new VB language feature #12629_ @AnthonyDGreen 
 `2147483647` should be for `Experimental` or `VNext` since it will always out rank any other version.

**Comment by gafter** [comment]
@AdamSpeight2008 it is not a given that the latest version will always be the default version.

**Comment by gafter** [comment]
Experimental language features should either be enabled by default (if in a separate branch) or controlled by a feature flag. Not controlled by the language version.

**Comment by AdamSpeight2008** [comment]
@gafter 
Which is `latest` or `default` ?
The Command Line flags says it is `default` , yet the language version used is `Latest`.

>  it is not a given that the latest version will always be the default version.

If that could be the case doesn't that suggest a two different enum values? And two different mappings?

**Comment by AdamSpeight2008** [comment]
> Experimental language features should either be enabled by default (if in a separate branch) 
That being the `Experimental` version, which if is `Int.MaxValue` would automatically enable them, since no other version number could be high than it.

> controlled by a feature flag. Not controlled by the language version.
But the presence of a feature flag isn't currently being checked. (See PR #12277)

**Comment by gafter** [comment]
> Which is it `latest` or `default` ?
The Command Line flags says it is `default` , yet the language version used is `Latest`.

In this version `default`, on the command line, gives you the latest version.

> >  it is not a given that the latest version will always be the default version.
> 
> If that could be the case doesn't that suggest a two different enum values? And two different mappings?

Yes, if we introduce a "default" value for the enum, it would have a different value and a potentially different mapping. It is not the purpose of this PR to propose or introduce that.

**Comment by AdamSpeight2008** [comment]
I think we should define what we mean by the terms latest and default?
 + What enum value should it have?
  + `enum Version { Latest = -1 }`
 + Negative values indicating magic version numbers.
 + Is latest the last public release (non beta)?
 + what came the last visual studio release? eg VB15 and C#6
 + available via NuGet?
+ What is meant by `default` version?
  + `enum Version { @default = 0 }` ?
+ Should there also be an experimental version number?
 + `enum Version { Experimental = Int.MaxValue }` 

How would the version indicate it was a point release?
