### ISSUE TITLE
testm Snippet doesn't automatically add a reference to Microsoft.VisualStudio.QualityTools.UnitTestFramework

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#12758]
**Version Used**: 
ML 25526.00
**Steps to Reproduce**:
1. Create a new C# console application
2. Inside Program.cs, and the namespace, type the following: class c testm
3. Hit tab twice to activate the testm snippet.
4. The snippet expands and looks like the following
![image](https://cloud.githubusercontent.com/assets/10537189/17153143/f03cf70c-532f-11e6-84be-82c70653255c.png)
5. Check the references tab in solution explorer.

**Expected Behavior**:
Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll should be in the list of references.
**Actual Behavior**:
It is missing from the list

This is causing the CSharpSnippets test to fail in standalone, and is a regression from Dev14 update 3

**Comment by Pilchie** [comment]
Can you take a look at this? I didn't think this snippet ever had support for adding references?  C# didn't even used to support that back in VS2013.

(cc @dpoeschl)

**Comment by jmarolf** [comment]
@Pilchie you won't believe this, but it actually did add the reference! Looks like this is a case of the Microsoft.VisualStudio.QualityTools.UnitTestFramework not being installed by default.  I'll make sure that if the test snippets are installed, we also install the unit test framework.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not changing these legacy extensions.
