### ISSUE TITLE
No intellisense after new in object creation expression.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#12755]
**Version Used**:  latest roslyn master [7/25] on VS2015.3

**Steps to Reproduce**:

```C#
int[] array;
Program p = new | 
array[4] = 4;
```

No intellisense after typing `new <space>`

see: https://github.com/dotnet/roslyn/issues/2836

/cc: @miloush

**Comment by miloush** [comment]
Also with array declaration:

```C#
string s = new |
int[] array;
```
