### ISSUE TITLE
(Portable) Source Link

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#12759]
To complete the E2E experience with Portable PDBs (embedded or not), the debugger needs to be able to find out the sources for documents included in the PDB. In case of Windows PDB a post-build rewriter tool injects the source document URLs into the PDB. 

Rewriting is not desirable. I propose we add a new compiler switch `/sourcelink:<file>` that tells the compiler to embed a blob into the PDB describing how to retrieve sources from a source control server. 
This technique could be used for both Windows and Portable PDBs, although we would initially only support the switch when `/debug:portable` or `/debug:embedded` is also specified.

In case of Portable PDBs the content of the source link file would be in JSON format with the following structure:

``` JSON
{
  "documents": {
     "f:/build/*" : "https://raw.githubusercontent.com/OmniSharp/omnisharp-vscode/14fbdd1897c2993c0a08e224c8eb7c36b82e8cb8/*"
  }
}
```

The content of the file would be generated by a build task preceding csc task. The build task would be specific to source control used by the project (git, TFS, etc.) and would query the source control for the current commit sha and generate the corresponding URL to the .json file.

**Implementation details**

In Portable PDB the source link data would be saved in a Custom Debug Information blob associated with the assembly.

The Portable PDB bridge would implement method already exposed on `ISymUnmanagedReader4`:

``` C#
public int GetSourceServerData(out byte* data, out int size)
```

It would read the CDI and return the raw content. The debugger would interpret the data.

**An alternative approach** 

would be to embed the source link file into the .dll itself as a managed resource (/resource:source_link.json). Although this would avoid compiler switch it would require a convention for the resource name. Unless we use some kind of GUID the resource name might collide with some resource that the project already has. Also it's odd that this information would be in the .dll and not where all other debug information is - in the .pdb (embedded or not). At the end of the day a dedicated compiler switch is imo cleaner.

**Comment by tmat** [comment]
@gregg-miskelly @noahfalk

**Comment by tmat** [comment]
@dotnet/roslyn-compiler Any objections? @jaredpar I know that adding a new compiler option is not popular, but amending output of the compiler to avoid that is much worse imo.

**Comment by tmat** [comment]
An alternative approach would be to embed the source link file into the .dll itself as a managed resource (```/resource:source_link.json```). Although this would avoid compiler switch it would require a convention for the resource name. Unless we use some kind of GUID the resource name might collide with some resource that the project already has. Also it's odd that this information would be in the .dll and not where all other debug information is - in the .PDB. At the end of the day, a dedicated compiler switch is imo cleaner.

**Comment by tmat** [comment]
@ctaggart FYI, related to https://github.com/dotnet/roslyn/issues/4119.

**Comment by ctaggart** [comment]
@tmat Thanks for adding me. I like the name of the option! :+1: This is indeed what we discussed last November. Very excited to see progress on it.

Regarding E2E experience, it is also important that private repositories, such as GitHub private repositories (https://github.com/ctaggart/SourceLink/issues/48), be indexable too. GitHub private repos do not return a HTTP 401. However, you know ahead of time that they are secure and the clients could prompt for credentials before making the request. Would it be possible to specify that it needed to be `secure` in the json document for certain documents? May be standard types of security can be supported?

**Comment by tmat** [comment]
@ctaggart Just ot be clear, the content of the file is opaque to the compiler. The interpretation is done in the debugger. I assume we're gonna support authentication in some form at some point. @gregg-miskelly ?

**Comment by gregg-miskelly** [comment]
Yes, I think we would eventually want to support authentication. At the moment though, I am not quite sure how this would work. @ctaggart do you know much about how GitHub private authentication works? Is the auth connection token part of the URL? a cookie? how could a client program integrate with them?

**Comment by noahfalk** [comment]
I'm good the proposal. I agree that there is little reason to put this file in the dll. 

Aside: Some day the debug content that might be more useful in the dll is a list of file names and hashes. This allows a debugger to quickly determine if a breakpoint that the user has bound in an open file in the IDE matches the file used to compile the debuggee. Today the debugger needs to pause the debuggee at each module load to acquire+load the symbols in order to do this check.

**Comment by ctaggart** [comment]
@gregg-miskelly GitHub private authentication is documented here https://developer.github.com/v3/auth/. The [Basic Authentication](https://developer.github.com/v3/auth/#basic-authentication) support is what I used to [SourceLink-Proxy](https://github.com/ctaggart/SourceLink-Proxy/blob/master/server.ts) to enable private repos to work with today's source indexing. Supporting their standard OAuth flow would be better.

**Comment by mjsabby** [comment]
@tmat how are you doing the embedded pdb inside the dll? Is that a well-known resource name? 
Adding a compiler switch means a precipitous drop from who will be using it.

**Comment by tmat** [comment]
@mjsabby It's a debug table entry: see spec https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PE-COFF.md#embedded-portable-pdb-debug-directory-entry-type-17

Not sure what you mean. The idea is that to use this feature one would use an msbuild task that produces the ,json file and passes it into the csc task. For git it could be something like:

```
<Target Name="GetLatestCommitHash" Condition="'$(LatestCommit)'==''">
    <Exec Command="git rev-parse HEAD" >
      <Output TaskParameter="ConsoleOutput" PropertyName="LatestCommit" />
      <Output TaskParameter="ExitCode" PropertyName="LatestCommitExitCode" />
    </Exec>
    <WriteLinesToFile File="source_link.json" Lines='{"documents": { "$(OutputDir)/*" : "$(RepoUri)/$(LatestCommit)/*" }}' />
 </Target>  
```

**Comment by mjsabby** [comment]
@tmat I was talking about your alternative where you said the one thing preventing putting this inside the dll is a well-known name. And I was pointing out that the same problem exists in embedding the PDB inside the dll, so however you solved that (if you did) would possibly apply here.

**Comment by tmat** [comment]
We didn't have a problem with well-known name since we used debug directory to embed the pdb.

**Comment by tmat** [comment]
Remaining work:
[ ] Debugger support
[ ] msbuild task/snippet to generate the .json file from GIT repo
[ ] Project System UI
[ ] E2E testing in .NET Core projects

**Comment by AArnott** [comment]
I see `$(SourceLink)` is already wired up to the Csc task. I'm interested in enhancing [PdbGit](https://github.com/aarnott/pdbgit) to set this property and skip the PDB rewrite, but I'd need to know a couple things:

1. How to detect during the build that `$(SourceLink)` is supported, since I would end up skipping PDB rewriting later when this is the case. I don't want to just set an MSBuild property and assume the customer is using the version of the .targets that support it. So what property or other clue can I check for to know it will be honored?
1. Capitalization is critical in git. GitHub, for instance, is case sensitive in its URLs. There have been multiple reports on GitLink of some source files not downloading properly that were traceable to capitalization being different in the MSBuild project file's `@(Compile)` items. Will the compiler construct the URLs from the normalized capitalization on disk (including each level of folder names)? That wouldn't guarantee it works (such as in the event of a case rename in git that doesn't update the disk). In PdbGit I solve this by querying .git at HEAD for each individual file to make certain I have the proper casing. But I don't see that as an option here, unless that .json file allows for supplying each path.

**Comment by jaredpar** [comment]
> So what property or other clue can I check for to know it will be honored?

I don't know that such a feature exists.  I definitely understand what you're asking for here as it's a problem we've run into as well.  

> Will the compiler construct the URLs from the normalized capitalization on disk (including each level of folder names)?

There are a number of items to consider here:

- MSBuild Csc task: 
    - Will attempt to normalize the provided source files based on `Path.GetFullPath` [here](http://source.roslyn.io/#Microsoft.Build.Tasks.CodeAnalysis/ManagedCompiler.cs,5c744877bd3c4aaf)
    - Will not attempt any normalization on paths passed via response files.
- csc compiler: doesn't do any normalization

**Comment by AArnott** [comment]
> Will attempt to normalize the provided source files based on Path.GetFullPath
Beware: that API only normalizes the leaf name. It does nothing for the folders that the leaf item belongs to. So you have to call GetFullPath for each path segment.

> Will not attempt any normalization on paths passed via response files.
The response files are already created by the .targets, aren't they? And they don't contain normalized paths AFAIK. So how does that solve the problem?

> csc compiler: doesn't do any normalization
That's fine, perhaps for perf reasons for everyone who doesn't care about linking a PDB to a git repo. But it means we need to solve the problem elsewhere.

**Comment by tmat** [comment]
If there is a problem with normalization I think the best place to address it is in msbuild. 

Note that /sourcelink allows you to specify a mapping from local paths as stored in the PDB to the repo URLs. The mapping also supports suffix wildcard as shown in the example above (in the description of the PR). When applied by the debugger the mappings are sorted by the key length, so if there is a more specific mapping and wildcard mapping that overlap the more specific is chosen (e.g. ```"C:\A\B\foo.cs": x``` and ```"C:\A\*": y\*``` then debugger maps ```C:\A\B\foo.cs``` to ```x``` and ```C:\A\B\bar.cs``` to ```y\B\bar.cs```).

So perhaps you can explicitly include the paths whose file name differs in the repo from the disk path.

**Comment by ctaggart** [comment]
@AArnott Any chance you would be interested in collaborating here in the original project https://github.com/ctaggart/SourceLink/issues/121 ? Now that the MSBuild tooling refactor is out, I plan on picking this back up. SourceLink 2.0 will be for this portable PDB support. Writing that json file should be simple enough. I simply don't know yet how to plug into the right spot of the MSBuild process with the updated tooling, but will have a look soon.

**Comment by AArnott** [comment]
> So perhaps you can explicitly include the paths whose file name differs in the repo from the disk path.

The compiler doesn't know or care what the disk path capitalization is, does it? The compiler just assumes it is the path passed in by MSBuild, I suspect. Which means it's the MSBuild @(Compile) item names that will determine the default capitalization if this json file doesn't override it.

@ctaggart: yes. I recently read your blog post from two years back about how GitLink took code from SourceLink. I am in conversations with GitLink about possible re-convergence of PdbGit with GitLink. But converging even further with SourceLink sounds like a very interesting discussion as well.

**Comment by tmat** [comment]
csc does some path processing and normalization:

http://source.roslyn.io/#Microsoft.CodeAnalysis/CommandLine/CommonCommandLineParser.cs,cbebf0574a6345fb,references
http://source.roslyn.io/#Microsoft.CodeAnalysis/SourceFileResolver.cs,afe7f45d8bdfc7ea,references

We also support /pathmap, which allows the user to replace prefixes of source paths with other prefixes (useful for deterministic builds).

**Comment by stffabi** [comment]
Does anybody know the progress on the visual studio debugger side of this?

VS2017 RC3 seems to have an option in the debug options window "Enable sourcelink support". Unfortunately it doesn't seem to work right now.

**Comment by gregg-miskelly** [comment]
@stffabi What issue are you seeing? RC3 should have source link support.

**Comment by stffabi** [comment]
@gregg-miskelly I'm referencing an assembly which has been build with a portable pdb and a source_link.json file from a visual studio solution. Afterwards during debugging I try to step into the code of the assembly, but VS2017 RC3 just prints out Class1.cs not found. SourceLink support is active accordingly to the debug settings dialog.

You can find the code of both solutions here.
- Repo with solution that uses the assembly: https://github.com/stffabi/sourcelink-use
- Repo with the source of the assembly with active source_link.json. The json file is generated during build as a msbuild target. https://github.com/stffabi/sourcelink-test

**Comment by AArnott** [comment]
@gregg-miskelly  and @stffabi when you refer to "source link" support in the debugger, don't you mean "source *server*" support? SourceLink is a nuget package, similar to GitLink or PdbGit, that gives PDBs source server support. It's not that the debugger has support specifically for the source link nuget package, right?

**Comment by tmat** [comment]
@AArnott https://github.com/dotnet/roslyn/issues/12759

**Comment by tmat** [comment]
@AArnott SourceLink as in reading sourcelink.json file embedded in Portable PDB.

**Comment by tmat** [comment]
@stffabi I think the problem might be that the source file path in the PDB uses ```\```:

```C:\devProjekte\Framework\00_VNext\sourcelink-test\src\ClassLibrary1\Class1.cs```

while the source link uses ```/```:

```"C:/devProjekte/Framework/00_VNext/sourcelink-test/*" : "https://raw.githubusercontent.com/stffabi/sourcelink-test/b5012a98bed12f6704cb942e92ba34ccdbd920d8/*"```

@gregg-miskelly Does the debugger attempt to replace ```\``` with ```/``` if it doesn't find an exact match first?

**Comment by tmat** [comment]
@stffabi 
Can you try to update your .csproj file like so?
```
    <WriteLinesToFile File="$(SourceLink)" Lines="{&quot;documents&quot;: { &quot;$([System.IO.Path]::GetFullPath('$(GitRootFolder)/'))*&quot; : &quot;$(RepoUri)/$(LatestCommit)/*&quot; }}" />
```

That is - adding GetFullPath call

**Comment by tmat** [comment]
BTW, you can avoid escaping double quotes like so:
```
<WriteLinesToFile File="$(SourceLink)" Lines='{"documents": { "$([System.IO.Path]::GetFullPath(`$(GitRootFolder)/`))*" : "$(RepoUri)/$(LatestCommit)/*" }}' />
```

**Comment by tmat** [comment]
@AArnott Does GitLink support Portable PDBs?

**Comment by tmat** [comment]
This task https://github.com/stffabi/sourcelink-test/blob/master/src/ClassLibrary1/ClassLibrary1.csproj#L8 is good as long as there is no mismatch between the casing of source file paths passed to the ```csc``` task and what GIT has in its storage. It might happen to Windows - if the proj file specifies ```<Compile Include="Foo.cs"/>``` but the file name is actually ```foo.cs```. I assume that GitLink deals with these cases. 

I imagine we can write a custom task that would compare all source paths passed to ```csc``` task with their corresponding paths in GIT storage and fixes them up (and perhaps reports warnings).

**Comment by jaredpar** [comment]
@tmat are you all taking into consideration the idea that the source paths listed in the PDB may not reflect the artifacts on disk?  This scenario comes into play with fully deterministic builds and the `/sourceMap` option.  This allows two developers building from different enlistment paths to create byte for byte equal DLLs / PDBs.   

The end effect though is the file paths written into the PDB may be completely invalid.  On roslyn CI for example we do builds where all source files appear to originate from `q:\`.

**Comment by gregg-miskelly** [comment]
@stffabi I will try and take a look latter today. But you can look at https://github.com/chuckries/SourceLinkTest for some example assemblies.

**Comment by ctaggart** [comment]
Using @stffabi's example  by `git clone https://github.com/stffabi/sourcelink-test` and building, I'd like to be able to extract a list of the documents & their URLs by reading the portable pdb. I am able to read the documents and their hash values, but **how to do I construct the URL**? For the old pdb format, I'd use [SrcSrvGetFile](https://github.com/ctaggart/SourceLink/blob/b3b4dbec35a0ee88a444c9c56f227c08d974f805/CorSym/SrcSrv.cs#L106) from the srvsrv.dll to [getDownloadUrl](https://github.com/ctaggart/SourceLink/blob/b3b4dbec35a0ee88a444c9c56f227c08d974f805/SymbolStore/PdbReader.fs#L28-L31). @tmat / @gregg-miskelly Do ya'll know how I may be able to come up with the download URL using a portable pdb? Is it possible to reuse the code that Visual Studio is using?

Here is the code to extract out all the documents.
``` cs
using System;
using System.IO;
using System.Reflection.Metadata; // 1.4.2
using System.Runtime.InteropServices;

class Program
{
    
    unsafe static void Main(string[] args)
    {
        // https://github.com/ctaggart/SourceLink/issues/93#issuecomment-155298236

        var f = @"C:\Users\camer\cs\sourcelink-test\src\ClassLibrary1\bin\Debug\netstandard1.4\ClassLibrary1.pdb";
        var bytes = File.ReadAllBytes(f);
        var pBytes = GCHandle.Alloc(bytes, GCHandleType.Pinned);
        var mr = new MetadataReader((byte*)pBytes.AddrOfPinnedObject(), bytes.Length);
        
        foreach(var dh in mr.Documents)
        {
            var d = mr.GetDocument(dh);
            var name = mr.GetString(d.Name);
            var language = mr.GetGuid(d.Language);
            var hashAlgorithm = mr.GetGuid(d.HashAlgorithm);
            var hash = mr.GetBlobBytes(d.Hash);
            Console.WriteLine("{0} {1} {2} {3}", toHex(hash), HashAlgorithmGuids.GetName(hashAlgorithm), LanguageGuids.GetName(language), name);
        }

        pBytes.Free();
    }

    static string toHex(byte[] bytes)
    {
        return BitConverter.ToString(bytes).Replace("-", "").ToLowerInvariant();
    }

    // https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PortablePdb-Metadata.md
    // https://github.com/jbevain/cecil/blame/master/Mono.Cecil.Cil/PortablePdb.cs

    static class HashAlgorithmGuids
    {
        static readonly Guid md5 = new Guid("406ea660-64cf-4c82-b6f0-42d48172a799");
        static readonly Guid sha1 = new Guid("ff1816ec-aa5e-4d10-87f7-6f4963833460");
        static readonly Guid sha256 = new Guid("8829d00f-11b8-4213-878b-770e8597ac16");

        public static string GetName(Guid guid)
        {
            if (guid == md5) return "md5";
            if (guid == sha1) return "sha1";
            if (guid == sha256) return "sha256";
            return guid.ToString();
        }
    }

    static class LanguageGuids
    {
        static readonly Guid csharp = new Guid("3f5162f8-07c6-11d3-9053-00c04fa302a1");
        static readonly Guid fsharp = new Guid("ab4f38c9-b6e6-43ba-be3b-58080b2ccce3");

        public static string GetName(Guid guid)
        {
            if (guid == csharp) return "csharp";
            if (guid == fsharp) return "fsharp";
            return guid.ToString();
        }
    }

}
```

It outputs:
```
5bbeb074b3011214eb475abe33a0cc3b2b264d5e sha1 csharp C:\Users\camer\cs\sourcelink-test\src\ClassLibrary1\Class1.cs
```

Indeed, the checksums matchs what PS gives:
```
PS C:\Users\camer\cs\sourcelink-test\src> Get-FileHash -Algorithm SHA1 -Path C:\Users\camer\cs\sourcelink-test\src\ClassLibrary1\Class1.cs | fl


Algorithm : SHA1
Hash      : 5BBEB074B3011214EB475ABE33A0CC3B2B264D5E
Path      : C:\Users\camer\cs\sourcelink-test\src\ClassLibrary1\Class1.cs
```

**Comment by tmat** [comment]
@ctaggart The map from document path to URL is stored in [source link custom debug info](https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PortablePdb-Metadata.md#SourceLink). 
@gregg-miskelly Do you have a spec for how the debugger interprets the file?

**Comment by tmat** [comment]
@ctaggart BTW, you can use https://source.dot.net/#System.Reflection.Metadata/System/Reflection/Metadata/MetadataReaderProvider.cs,e508e1c969554c8a to get the MetadataReader.

**Comment by gregg-miskelly** [comment]
@stffabi I took a look at the code, and I do believe the reason it wasn't working for you was that your slashes on the file path (left) side of the map entry would be going the wrong way. If you convert the git output to use backslashes on Windows I believe this will work.

@chuckreis do we have a spec for how exactly the source link content is interpreted?

@tmat: here is the basic definition --

Validation rules --
 1. The only acceptable wildcard is one and only one '*', which if present will be replaced by a relative path
2. If the file path does not contain a *, the URI cannot contain a * and if the file path contains a * the URI must contain a *
3. If the file path contains a *, it must be the final character
4. If the URI contains a *, it may be any where in the URI

Applying the map --
1. The map is sorted from most specific (longest) to least specific (shortest)
2. When we look for a match we take the path from the source entry section of the PDB, and we walk the map looking for the first match.
3. When applying a map with a wild card ('*') the '*' in the URI is replaced with the path from file path, except that '\' are replaced with '/'.

**Comment by ctaggart** [comment]
I got @stffabi's example working in Visual Studio 2017 RC3. It need backslashes and those backslashes needed escaping in json. Line endings also need to match up. I put additional comments in https://github.com/stffabi/sourcelink-test/pull/1. I/we can create tooling to make some of this easier, but I love how simple this basic case is. Great job!

**Comment by tmat** [comment]
@ctaggart We definitely need a build task that does this. Do you plan on writing one? I see your SourceLink project provides a lot of functionality, mostly to deal with Windows PDBs. Since Portable PDB support should only need the task we are talking about here, wouldn't it make sense to have a separate, minimal and cross-platform nupkg with only that functionality?

**Comment by tmat** [comment]
@ctaggart Ideally such task would become a part of https://github.com/dotnet/sdk

**Comment by tmat** [comment]
>  Ideally such task would become a part of https://github.com/dotnet/sdk

Actually, let me take this back. The taks would depend on GIT and SDK should probably not depend on GIT. So likely a separate nupkg for each source control provider would be better.

**Comment by ctaggart** [comment]
@tmat Yes, I've started a `dotnet sourcelink` tool, but I could use some assistance getting started.

It worked when I run it locally, but fails when I try to use it from another project.

working locally:
```
PS C:\Users\camer\cs\SourceLink\dotnet-sourcelink> dotnet run
SourceLink: Source Code On Demand

Usage: dotnet sourcelink [options] [command]

Options:
  -h|--help  Show help information

Commands:
  print-json  print the Source Link JSON stored in the Portable PDB file

Use "dotnet sourcelink [command] --help" for more information about a command.
```

Then when I add it to a csproj & try running `dotnet sourcelink`:

```
  <ItemGroup>
    <DotNetCliToolReference Include="dotnet-sourcelink">
      <Version>2.0.0-*</Version>
    </DotNetCliToolReference>
  </ItemGroup>
```

```
PS C:\Users\camer\cs\sourcelink-test\src\ClassLibrary1> dotnet sourcelink
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Users\camer\.nuget\packages\.tools\dotnet-sourcelink\2.0.0-b318\netc
oreapp1.0'.
PS C:\Users\camer\cs\sourcelink-test\src\ClassLibrary1> dotnet --info
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004530
```

This is with this build:
https://www.nuget.org/packages/dotnet-sourcelink/2.0.0-b318

I tried adding emitEntryPoint to the csproj, but didn't seem to help.
https://github.com/ctaggart/SourceLink/blob/build/dotnet-sourcelink/dotnet-sourcelink.csproj#L6
https://github.com/dotnet/cli/issues/2859

Any ideas how to get past this error?

**Comment by ctaggart** [comment]
I created a new issue at https://github.com/dotnet/cli/issues/5593 with steps to reproduce.

**Comment by ctaggart** [comment]
That issue has been fixed and it now works https://github.com/stffabi/sourcelink-test/pull/2:

```
dotnet build
dotnet sourcelink print-json -p .\bin\Debug\netstandard1.4\ClassLibrary1.pdb
```

`dotnet sourcelink` has been started. I think it is best to write the tests firsts, the commands that can be used to validate the the Portable PDB Source Link works. I'm currently thinking of implementing these commands:

```
dotnet sourcelink print-json -p $pdbpath
dotnet sourcelink print-documents -p $pdbpath
dotnet sourcelink print-urls -p $pdbpath
dotnet sourcelink test-urls path -p $pdbpath
```

For creating the Source Link JSON, a .NET Core version of libgit2 is needed. I'm hoping @AArnott gets that working with https://github.com/libgit2/libgit2sharp/pull/1318. I'm picturing a `dotnet sourcelink create` that is called by msbuild tasks for [each SCM provider](https://github.com/GitTools/GitLink#supported-git-providers).

## Windows PDB vs Portable PDB

For source indexing Windows PDB files, we currently have three solutions:

- SourceLink by @ctaggart
- GitLink by @GeertvanHorrik
- PdbLink by @AArnott 

It is great to see @AArnott merging back into GitLink. For source linking Portable PDB files, it would be great to have a one solution that we work together on. May be I can reach out to the .NET Foundation and see about putting together a proposal. For source linking to be a success, it really needs buy-in from several stakeholders:

- NuGet
- dotnet cli
- Visual Studio debugging
- VSCode debugging
- SCM providers like GitHub (private repositories)

**Comment by AArnott** [comment]
@tmat said:

> Does GitLink support Portable PDBs?

I don't think so. GitLink uses pdbsrv.exe IIRC to modify the pdb with a hard-coded set of data. So unless that somehow "just works" with portable PDBs, I suspect there is work to do there to add support for it.

@ctaggart mentioned "PdbLink by AArnott" but my fork is "PdbGit". And yes, the meat of it has merged back into GitLink for a v3.x release that hasn't come out yet. When it does, assuming it retains the major features that I merged into it by then, I'll shutdown PdbGit. 
Regarding SourceLink and GitLink merging, I'd be in favor, but will be very interested in an outcome that includes "it just works" when I install the nuget package.

**Comment by gregg-miskelly** [comment]
In case this feeds into the calculus - I would personally be in favor our source link support eventually coming to Windows PDBs. But the support would only be in new debuggers. So project owners would likely want to be able to choose between sourcelink vs. source server vs. both for Windows PDB projects.

**Comment by tmat** [comment]
@gregg-miskelly SourceLink for Windows PDB is certainly an option. 

I'd like to emphasize a major difference between /sourcelink and the current source linking tools -- that is while the current tools post-process the PDB, /sourcelink is a compiler option that is specifically designed to avoid the need for rewriting the PDB. The tools may be able to share a basic logic dealing with GIT but the /sourcelink tools won't need to deal with PDBs at all. Hence the same tool can be used for both PDB formats.

**Comment by ctaggart** [comment]
I hope to have the tool for creating the source link out later this week. In the spirit of writing the tests first, I just posted a prerelease of dotnet-sourcelink that can test all the checksums in a Portable PDB.

```
PS C:\Users\camer\cs\sourcelink-test\src\ClassLibrary1> dotnet sourcelink
SourceLink: Source Code On Demand

Usage: dotnet sourcelink [options] [command]

Options:
  -h|--help  Show help information

Commands:
  print-documents  print the documents stored in the Portable PDB file
  print-json       print the Source Link JSON stored in the Portable PDB file
  print-urls       print the URLs for each document based on the Source Link JSON
  test-urls        test each URL and verify that the checksums from the Portable PDB match

Use "dotnet sourcelink [command] --help" for more information about a command.

PS C:\Users\camer\cs\sourcelink-test\src\ClassLibrary1> dotnet sourcelink test-urls -p .\bin\Debug\netstandard1.4\ClassLibrary1.pdb
4dceb9b1cc934a16f10e766eab0497ef1d18fde0 sha1 csharp C:\Users\camer\cs\sourcelink-test\src\ClassLibrary1\Class1.cs
https://raw.githubusercontent.com/ctaggart/sourcelink-test/b5012a98bed12f6704cb942e92ba34ccdbd920d8/src/ClassLibrary1/Class1.cs
```

``` xml
<DotNetCliToolReference Include="dotnet-sourcelink" Version="[2.0.0-b335]" />
```

Progress.
https://github.com/ctaggart/SourceLink

**Comment by tmat** [comment]
@ctaggart Cool. dotnet tools usually pick up the project context from the .csproj in the current directory. Perhaps the PDB should be picked up from the project rather than passing on command line ```-p .\bin\Debug\netstandard1.4\ClassLibrary1.pdb```? 

/cc @srivatsn

**Comment by tmat** [comment]
@srivatsn Do we have a design guideline for dotnet tools? How dotnet tools should correspond to msbuild task, etc.

**Comment by AArnott** [comment]
This is a matter I've been discussing with @ctaggart. He is of the opinion that SourceLink should ship as a CLI tool, with a simple MSBuild wrapper. I'm advocating for just MSBuild integration so that it's totally automatic.

MSBuild doesn't (yet?) support loading MSBuild Tasks and their dependencies from restored packages the way CLI tools do though, which is what @ctaggart is focusing on. I workaround this by embedding my dependencies.

**Comment by srivatsn** [comment]
Adding @blackdwarf @piotrpmsft @livarcocc for guidance around CLI tools.

**Comment by ctaggart** [comment]
I built two dotnet tools that are wrapped by msbuild nuget packages. The combination works really well. It makes it easy to test, develop, and extend.

## SourceLink v2 is Feature Compete
I just released it to the NuGet Gallery. Please try it out! There are no known bugs, but not a ton of docs. It really isn't very hard though. Have a look at:

https://github.com/ctaggart/SourceLink

There is also an example of putting the references in a separate file here:
https://github.com/ctaggart/sourcelink-test/tree/master/src/ClassLibrary1

```
PS C:\Users\camer\cs\sourcelink-test\src\ClassLibrary1> dotnet build /p:ci=true /v:n
Microsoft (R) Build Engine version 15.1.545.13942
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/25/2017 6:07:38 PM.
     1>Project "C:\Users\camer\cs\sourcelink-test\src\ClassLibrary1\ClassLibrary1.csproj" on node 1 (Build target(s)).
     1>SourceLinkCreate:
         dotnet sourcelink-git create -u "https://raw.githubusercontent.com/stffabi/sourcelink-test/{commit}/*" -f "obj\sourcelink.json" -s "Class1.cs"
       GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
       CoreGenerateAssemblyInfo:
       Skipping target "CoreGenerateAssemblyInfo" because all output files are up-to-date with respect to the input files.
       CoreCompile:
       Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
       SourceLinkTest:
         dotnet sourcelink test "obj\Debug\netstandard1.4\ClassLibrary1.pdb"
         sourcelink test passed
       GenerateBuildDependencyFile:
       Skipping target "GenerateBuildDependencyFile" because all output files are up-to-date with respect to the input files.
       CopyFilesToOutputDirectory:
         ClassLibrary1 -> C:\Users\camer\cs\sourcelink-test\src\ClassLibrary1\bin\Debug\netstandard1.4\ClassLibrary1.dll
     1>Done Building Project "C:\Users\camer\cs\sourcelink-test\src\ClassLibrary1\ClassLibrary1.csproj" (Build target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.21
```

**Comment by ctaggart** [comment]
If ya'll would like to add source link support to Roslyn itself instead of just source server support, you will need to upgrade from project.json to the new dotnet csproj format. Then you do something similar to what I demonstrated here: cc @jaredpar 

https://github.com/aspnet/EntityFramework/pull/7726

Docs revised: https://github.com/ctaggart/SourceLink

**Comment by tmat** [comment]
@ctaggart Thanks. We can't switch Roslyn to Portable PDBs yet as we don't have symbol server support. We are working on a solution for that.
I'm gonna try source link on dotnet/symreader-converter repo though.

**Comment by ctaggart** [comment]
@tmat The plan is to allow Portable PDB files to be packaged in the nupkg files. I understand ya'll may have unique requirements. Would you mind sharing why you need a symbol server instead?

Let me know how things work out for symreader-converter. 

We now need a story for private repository support.

**Comment by tmat** [comment]
> The plan is to allow Portable PDB files to be packaged in the nupkg files. I understand ya'll may have unique requirements. Would you mind sharing why you need a symbol server instead?

@ctaggart It's not "instead" it's rather "as well". Having Portable PDBs in the nupkg is step 1, but that doesn't address all scenarios. For example, when we are debugging a VS crash dump the debugger needs to find from the PDB IDs stored in that .dmp file the PDBs somehow. For Windows PDBs it does so thru symsrv protocol. We are currently figuring out that the best approach is for Portable PDBs. In lack of this feature one would need to manually locate every single PDB when debugging a crash dump and that's very inconvenient.

**Comment by tmat** [comment]
> We now need a story for private repository support.

That's certainly an issue that needs to be addressed. One option is to add support for authentication to source link feature. @caslan @gregg-miskelly to comment on this.

Another option for the package author is to embed sources into Portable PDB instead of using source link. Source embedding is supported with VS 2017. Although the sources are compressed in the PDB it makes it bigger. 

If NuGet supported a concept similar to satellite assemblies for other content than resource assemblies, that is downloading parts of nupkg on demand, I can imaging creating a "source package" containing only sources and associating it with the main nupkg. Then the source map in source link .json file could map to relative paths. For example, 

Main package: 

```
lib\netstandard1.5\mylib.dll
lib\netstandard1.5\mylib.pdb
```

Source package:

```
src\MyLib\Lib.cs
```

When installed in nuget cache:
Main package: 

```
lib\netstandard1.5\mylib.dll
lib\netstandard1.5\mylib.pdb
src\MyLib\Lib.cs
```

Source link:
```
{
  "documents": {
     "f:/build/*" : "../../src/*"
  }
}
```

**Comment by ctaggart** [comment]
For private repository support, I was thinking of a couple of different options:

### 1. say what is support in the sourcelink.json
``` json
{  
   "auth":[  
      "basic",
      "preemptive"
   ],
   "documents":{  
      "C:\\Users\\camer\\cs\\EntityFramework\\*":"https://raw.githubusercontent.com/ctaggart/EntityFramework/f36ce80a93d9f698ff6b70207d2b83b5b11cf93b/*"
   }
}
```

### 2. register source link support auth providers
An extension in Visual Studio would register that it can provide authentication for `raw.githubusercontent.com`.

**Comment by tmat** [comment]
@ctaggart I'm not familiar with github auth but we need to be careful to only include information in the PDB that's unlikely to change. It would be unfortunate if a change in github policy broke all existing PDBs.

**Comment by gregg-miskelly** [comment]
RE: auth - our tentative plan was to handle \<not found | unauthorized | forbidden | etc> status codes and allow the user to authenticate and/or user a credential store where the user can somehow associate credentials with a URL. Though we haven't had the chance to get back and prototype this yet.

**Comment by ctaggart** [comment]
@gregg-miskelly That would be perfect! Can't wait. I need this for our repositories at work. When GitHub returns a `404 not found`, it would pop open the credentials dialog, then try again. /cc @shiftkey @haacked @kzu @cloudRoutine @ryangribble

@tmat I agree that we should put the auth info in the source link json.

**Comment by tmat** [comment]
I think at this point we can close this issue as we have and end-to-end solution with Source Link.

**Comment by ctaggart** [comment]
@tmat I welcome contributions. https://github.com/ctaggart/SourceLink/wiki/Contributing
I made `dotnet sourcelink` and `dotnet sourcelink-git` separate for a reason. Ideally, others would be created.

**Comment by tmat** [comment]
@ctaggart Cool. I was just curious. Didn't expect you'd write support for all source control systems out there.
