### ISSUE TITLE
BasicExtractInterfaceDialog and CSharpExtractInterfaceDialog are failing to open dialog due to wrong cursor placement

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#12754]
**Version Used**: 
ML 25526.00
Roslyn-Signed - Master - 20160722.2
**Steps to Reproduce**:
Run the tests via standalone context (contact me for a machine) 
For VB, the test is running the following command in scenario 1 after setting the editor text:
<PlaceCursor CharsOffset="1" Marker="Class C"/>
As you can see below, the class is selected. It is unable to open the extract interface dialog quick action here, but would be able to if C was selected. 

![image](https://cloud.githubusercontent.com/assets/10537189/17150124/10ab1396-5323-11e6-8e14-54a01432c94d.png)

**Comment by balajikris** [comment]
It is passing on PRs, i wonder what's different in standalone context?

**Comment by mattscheffer** [comment]
Realized I forgot to add the relevant part of the log for this failure. Screenshot above is directly from the test.

```
 Scenario: Verify core scenario
     Executing action [7/29/2016 12:28:20 PM] SetEditorText
     Executing action [7/29/2016 12:28:20 PM] PlaceCursor
     Executing action [7/29/2016 12:28:21 PM] ExtractInterfaceDialog
 --------------------------------
 Tao.Engine.Exceptions.UnexpectedResultException`1[Roslyn.CommonToBothHosts.Test.AbstractOkCancelDialogAction]: Extract Interface dialog is expected to be open.
    at Tao.Utilities.Extensions.ThrowUnexpectedResultException[TAction](TAction action, String message)
    at Roslyn.CommonToBothHosts.Test.AbstractOkCancelDialogAction.VerifyDialogIsOpen(Boolean isValid)
 ================================
```

**Comment by balajikris** [comment]
Per @mattscheffer 

> It's the same manual behavior between dev14 and dev15. 

> With cursor on 'Class', you can't open lightbulb to use 'Extract Interface'. However, you are able to activate Extract Interface from the Edit -> Refactor -> Extract Interface menu item or through the keyboard shortcut (Ctrl+R, Ctrl+I).

> With cursor on the class name, you can reach the extract interface dialog via lightbulb, menu item, and the keyboard shortcut.

While it's easy to fix up the test in this case, to ensure that caret is on the proper token, I wonder if this behavior is intentional or is simply an oversight?
Should lightbulb for Extract Interface be offered if caret is anywhere on the class declaration, or do we intentionally require caret be on the class name?

/cc @Pilchie

**Comment by Pilchie** [comment]
Again - why is the test passing on PRs?  I'm not sure what has changed here that would cause an issue.

**Comment by mattscheffer** [comment]
As it turns out this specific failure is my fault. Part of our changes with signed builds, means that we don't output the integration tests anymore. As a result, the integration test files used for standalone got out of sync. I believed that the latest integration test files were copied over but that was not the case here.

This test was updated 8 days ago, likely due to a similar issue. In this case, the class file actually gets renamed/reloaded from being ExtractInterfaceTest.vb to C.vb. I'm guessing it reloaded the file during the SetEditorText action, but the cursor placement was lost in the meantime. Which caused it the testrunner to fail to load ExtractInterfaceDialog.xml. At the point in the above screenshot, the cursor isn't actually there. Class is just highlighted, and using the keyboard shortcut doesn't actually work.

However, after using the new test file these two tests now pass. So the test bug can be closed there. Balaji's questioning of the behavior is still relevant though, especially as ExtractInterface works via the other two methods.

**Comment by Pilchie** [comment]
Moving to @dpoeschl for the invocation span question.  I'm okay with this being restricted to being on the class name for the lightbulb, so that it's not *always* showing up in the lightbulb menu.

**Comment by rchande** [comment]
> Should lightbulb for Extract Interface be offered if caret is anywhere on the class declaration, or do we intentionally require caret be on the class name?

@kuhlenh @dpoeschl Thoughts?

**Comment by dpoeschl** [comment]
Moving to @kuhlenh for the invocation span question. She's been thinking a lot about this lately...

**Comment by kuhlenh** [comment]
This is my proposal https://github.com/dotnet/roslyn/issues/13503 for Extract Interface caret positions. Going to mark this as dupe and close it.
