### ISSUE TITLE
Master Test Failures

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#1275]
I tried to build the latest Roslyn Master, but it fails to pass the Unit Tests.
Unfortunately there are too many to post. So I zipped the test results [Here](http://1drv.ms/18O5INA)

**Comment by jaredpar** [comment]
Thank you for reporting the issue.  In the future could you please include a bit more information about the problem.  For example:

- What build of Visual Studio are you running?
- What command did you execute that resulted in failures? 
- If the number of failures is too large, perhaps a general description or list of DLLs that had failures, etc ...

Having this information makes it much easier to triage issues and begin to investigate what went wrong.

**Comment by AdamSpeight2008** [comment]
VS2015ctp6 
Command ` msbuild /v:m /m /p:CIBuild=True BuildAndTest.proj`
