### ISSUE TITLE
rename IBuiltInAnalyzer.MustRunInProc to RunInProcess

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#12767]
rename MustRunInProc to RunInProcess

**Comment by CyrusNajmabadi** [comment]
Isn't creating an issue for this more work than just running 'Rename' in the code?

**Comment by heejaechang** [comment]
thought I will checkin this pretty quickly and move on :)

**Comment by heejaechang** [comment]
this is already done as part of OOP preview
