### ISSUE TITLE
RemoteWorkspace work left

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#12776]
- [ ] rename RemoteWorkspace to RemoteFeatures
- [ ] DiagnosticComputer - support analyzer exception filter once service hub support watson
- [x] DiagnosticComputer - figure out what to do with AnalyzerManager issue - https://github.com/dotnet/roslyn/issues/2830
- [ ] RoslynService - change it to use WorkspaceServices for all its services such as AssetService, SolutionService and etc
- [ ] add AnalyzerService that takes care of analyzer creation, lifetime, host analyzer, analyzer to analyzer id conversion and etc
- [ ] AssetService - provide a way to save (checksum, bits) to persistent storage
- [x] AssetService - support better caching mechanism than now
- [x] CompilationService - once remote workspace start supporting solution, this service is not needed
- [x] SolutionService - create its own host services such as - http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Host/Caching/IProjectCacheService.cs,24 and http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Host/SyntaxTreeFactory/ISyntaxTreeFactoryService.cs,60023215c30c1a7d and etc to better control cache.
- [x] AssetService - get asset concurrently
- [x] AssetService - provide batch channel which can get asset in batch mode (sending multiple asset through same stream)
- [x] watson support - once service hub support watson, add watson support
- [x] add unit tests
- [ ] figure out a way to track performance of this component
- [x] figure out telemetry story for this component
- [x] add Etw support

**Comment by CyrusNajmabadi** [comment]
Closing out.
