### ISSUE TITLE
work left in remote host client area

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#12773]
- [x] IRemoteHostClientService - split interface to registration service and user consumption service
- [ ] RemoteHostClient - hide Session from user completely, and rather than using raw Invoke abstraction, provide some kind of request/response abstraction
- [x] RemoteHostClientService - abstract out creation of service hub remote host client
- [x] RemoteHostClientService - make it to send over global assembly directly
- [x] RemoteHostClientService - Add batch mode asset channel in remote host client so that it can send over assets in batch mode without requiring asset channel in each service call
- [x] RemoteHostClientService - add a service to which update solution checksum on idle to latest so that we can do incremental solution checksum update.
- [x] RemoteHostClientService - send assets from primary workspace to remote host on idle before any service requesting them.
- [x] add unit test
- [x] add telemetry

**Comment by CyrusNajmabadi** [comment]
Closing out.
