### ISSUE TITLE
serialization work left that needed to be figured out before RTM for OOP

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#12770]
- [x] AbstractLanguageSpecificSerializationService - need implementation for these or/and a way to get them from host.
          // XmlReferenceResolver xmlReferenceResolver
          // SourceReferenceResolver sourceReferenceResolver
          // MetadataReferenceResolver metadataReferenceResolver
          // AssemblyIdentityComparer assemblyIdentityComparer
          // StrongNameProvider strongNameProvider
- [ ] ReferenceSerializationServiceFactory - find out a way to get actual assembly location without actually loading them. right now it is okay since we will load them anyway for open files. but would be better if we can find that out without loading them
- [x] AbstractReferenceSerializationService - find out a way to support xml doc comment for metadata reference
- [x] Asset - reduce number of asset implementations
- [ ] SourceTextAsset - find out a way to serialize it without getting text first. might require rewriting how Recoverable Text works.
- [x] ChecksumObject - see whether we can get rid of Kind
- [ ] ReferenceSerializationServiceFactory (default) - find out a way to support CoreClr (portable)
- [x] Serializer - provide a way to serialize stuff by just having only 1 method, serialize like deserialize
- [x] ChecksumObjectInfo/Workspace - provide a way to support versions
- [ ] SerializationKinds - find a way to not use enum but astraction for actual bit
- [ ] AbstractReferenceSerializationService - think about a way to send over data without allocating byte array
- [x] SnapshotStorages - special case RootStorage vs child storage
- [x] SnapshotStorages - provide a way to get checksum without walking whole tree repeatedly.
- [x] SnapshotStorages - right now, only red node we are holding is Solution. create SolutionState which doesnt hold onto any red node
- [x] ISolutionChecksumService - provide a way to walk whole hierarchical checksum tree or return multiple ChecksumObject based on given predicate
- [ ] RecoverableTextAndVersion - make recoverable text works like recoverable tree so that we can have tree/node concept
- [x] SolutionChecksumService - make creating initial solution checksum faster. currently it doesnt even use concurrency.
- [x] make serialize name to have data it is serializing as well such as SerializeChecksumObjectInfo rather than same name Serialize with overload.
- [x] move WriteArray directly down to ObjectWriter/Reader
- [x] remove reflection to get Metadata reader once @tmat makes it public
- [x] add etw logging
- [ ] add performance test for checksum creation
- [x] add telemetry
- [ ] think of a way to get rid of async GetTextAsync when creating checksum
  ...

- [x] clear up how IMetadataService and IDocumentationProviderService, 
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Host/Metadata/IMetadataService.cs,d451f864ce1d0985

- [x] http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Host/Documentation/IDocumentationProviderService.cs,cf8cf4247c6da4d7,references

works together and see whether OOP can use it.

**Comment by rynowak** [comment]
We recently ran into the issue that documentation isn't available in OOP. This would be nice to have for Razor/TagHelpers

**Comment by CyrusNajmabadi** [comment]
Closing out.
