### ISSUE TITLE
Unable to install Microsoft.CodeAnalysis.CSharp in VS 2013

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/roslyn#12780]
**Version Used**: 1.3.2

**Steps to Reproduce**:

1.  Open VS 2013 Professional
2. Create new project
3. Try to install `Microsoft.CodeAnalysis.CSharp` package from `https://www.nuget.org/api/v2/` feed

**Expected Behavior**: It got installed

**Actual Behavior**:

It fails with:
`Attempting to resolve dependency 'Microsoft.CodeAnalysis.Common (= 1.3.2)'.
Attempting to resolve dependency 'System.Collections.Immutable (≥ 1.1.37)'.
Attempting to resolve dependency 'System.Reflection.Metadata (≥ 1.2.0)'.
'System.Reflection.Metadata' already has a dependency defined for 'System.Collections.Immutable'.`

**The problem**: we are using this package in BenchmarkDotNet 0.9.8 as the default compiler. [People can't install our package now](https://github.com/PerfDotNet/BenchmarkDotNet/issues/237).

**Comment by tanveerbadar** [comment]
Are you using System.Collections.Immutable already somewhere? Remove the explicit reference and try again. You'll probably have to retest if this results in a package upgrade for immutable collections, but it seems the most likely cause to me.

**Comment by adamsitnik** [comment]
> Are you using System.Collections.Immutable already somewhere? 

@tanveerbadar No, I am not. I created new project in VS 2013 and tried to install Microsoft.CodeAnalysis.CSharp and it fails

**Comment by Pilchie** [comment]
Tagging @shyamnamboodiripad

**Comment by adamsitnik** [comment]
@shyamnamboodiripad  @Pilchie Hello! Any progress with this issue?

**Comment by tannergooding** [comment]
@adamsitnik, what version of NuGet do you have installed to VS 2013?

I am currently imaging a machine to see if I can repro the bug.

**Comment by adamsitnik** [comment]
Hi @tannergooding the version is 2.8.50313.46 (Nuget Package Manager for VS 2013)

**Comment by kasajian** [comment]
Normal computer with VS2013.  Attempting to install the Benchmark component yields the same message

Attempting to resolve dependency 'System.Collections.Immutable (≥ 1.2.0)'.
'System.Reflection.Metadata' already has a dependency defined for 'System.Collections.Immutable'.

**Comment by tannergooding** [comment]
Sorry, I got pulled off onto other work and forgot to update.

I was able to repro this bug in VS. However, I am not able to get this to repro in VS2015 or with the command line version of NuGet.

My best guess, at this point, is that the package is simply incompatible with the older version of NuGet that is available for VS2013.

I am trying to see if I can find some kind of workaround (for use within VS).

**Comment by adamsitnik** [comment]
@tannergooding Thanks for the update. Maybe it's a nuget bug? Can you try to reach the Nuget team?

**Comment by Pilchie** [comment]
Tagging @emgarten from NuGet.

**Comment by kasajian** [comment]
I'm unable to reproduce this with 2015 either. interestingly enough, after
I add the package to the solution using VS2015 and get it to wok, I can
close and reopen the same solution with VS2013 and it works.

**Comment by emgarten** [comment]
@adamsitnik you need NuGet 2.12 for Visual Studio 2013 to use *System.Reflection.Metadata*.

You can find the VSIX here: https://www.nuget.org/downloads

The error is caused by unknown target frameworks in the nuspec.

**Comment by adamsitnik** [comment]
@emgarten @kasajian Thanks for help! NuGet 2.12 solved the initial issue, but I got new one:

```
Attempting to resolve dependency 'Microsoft.CodeAnalysis.Common (= 1.3.2)'.
Attempting to resolve dependency 'System.Collections.Immutable (≥ 1.1.37)'.
Attempting to resolve dependency 'System.Runtime (≥ 4.0.0)'.
Attempting to resolve dependency 'System.Resources.ResourceManager (≥ 4.0.0)'.
The 'System.Resources.ResourceManager 4.0.0' package requires NuGet client version '3.0' or above, but the current NuGet version is '2.12.0.817'.
```

**Comment by emgarten** [comment]
@adamsitnik you will need to use Visual Studio 2015 for that package.

**Comment by Aslam-Shareef-Avalara** [comment]
Hahahahahaha
