### ISSUE TITLE
[Refactoring] Undoing 'Move Type to File' doesn't remove the file

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#12787]
If I move a class to a file with matching name and then undo the action, the file the refactoring created still exists...

**Comment by balajikris** [comment]
yeah, I didn't do anything special for undo to work here. Probably needs work :)

**Comment by kuhlenh** [comment]
@CyrusNajmabadi notes that we should also do this for Generate type, Extract Interface, etc. as well.

**Comment by Pilchie** [comment]
Didn't you add an undo here already?
