### ISSUE TITLE
VSI tests BasicProjectTemplates and CSharpProjectTemplates fail on Dev15

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#12791]
AddProjectAction has hardcoded zip file names and project names, and is failing in trying to find the project templates through DTE on Dev15 preview3 - it is likely the templates have been moved around/renamed/missing. Note that the tests currently pass on Jenkins (Dev14), but we are working towards moving Jenkins to Dev15. So please verify that the test passes locally on a standalone Dev15 install before closing this issue/unskipping the test. Following is stack track for the failures:

```
Scenario: 1) Create and build a code analysis project.
	Executing action [7/27/2016 12:14:19 PM] AddProject
Saved screenshot: C:\roslyn-internal\Open\Binaries\Debug\Screenshots\2016-07-27_12-14-20_18 - Failed AddProject Attempt 1.png
Exception caught when trying to add a project on attempt 1: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at EnvDTE80.Solution2.GetProjectTemplate(String TemplateName, String Language)
   at Roslyn.VSHosting.Test.AddProjectAction.GetProjectTemplatePath(Solution2 solution, String templateName, String language) in c:\roslyn-internal\Closed\Hosting\Test\Actions\VisualStudio\AddProjectAction.cs:line 263
   at Roslyn.VSHosting.Test.AddProjectAction.AddProject(TaoEngine engine) in c:\roslyn-internal\Closed\Hosting\Test\Actions\VisualStudio\AddProjectAction.cs:line 181
   at Roslyn.VSHosting.Test.AddProjectAction.Execute(TaoEngine engine) in c:\roslyn-internal\Closed\Hosting\Test\Actions\VisualStudio\AddProjectAction.cs:line 80
```

**Comment by Pilchie** [comment]
@jmarolf - can you take a look?

**Comment by mavasani** [comment]
Actually I am investigating this and likely reason is I don't have .NET compiler SDK installed. If I get past that and the test still fails, I'll hand it to Jon.

**Comment by mavasani** [comment]
I asked Jon to look at ProjectSystem.xml - that is failing due to a different reason. I haven't yet opened a bug for that.

**Comment by mavasani** [comment]
@jmarolf Tests are failing even after installing the SDK. Can you give this a try?

**Comment by jmarolf** [comment]
@mavasani hopefully later today.

**Comment by mavasani** [comment]
I have a fix out for ProjectSystem.xml: https://github.com/dotnet/roslyn-internal/pull/1200 - I'll spend some more time on these 2 tests to see if my setup is incorrect causing the test to fail (seems likely).

**Comment by Pilchie** [comment]
Moving to 2.0, since we won't switch to D15 for the preview 4 branch (but we still want to fix ASAP).

**Comment by mavasani** [comment]
These tests are actually passing fine on Jenkins right now, so this seems irrelevant now.
