### ISSUE TITLE
C# 7.0 tuples - Invalid code generation for expression trees

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/roslyn#12797]
Repro steps:

```
C:\Projects\roslyn\Binaries\Debug>type e.cs
using System;
using System.Linq.Expressions;

class E
{
    static void Main()
    {
        Expression<Func<(int, int)>> f = () => new (int, int)(1, 2);
    }
}
C:\Projects\roslyn\Binaries\Debug>csc e.cs ..\..\src\Compilers\Test\Resources\Core\NetFX\ValueTuple\*.cs
Microsoft (R) Visual C# Compiler version 42.42.42.42
Copyright (C) Microsoft Corporation. All rights reserved.


C:\Projects\roslyn\Binaries\Debug>e

Unhandled Exception: System.ArgumentException: Cannot resolve method Void .ctor(Int32, Int32) because the declaring type of the method handle System.ValueTuple`2[T1,T2] is generic. Explicitly provide the declaring type to GetMethodFromHandle.
   at System.Reflection.MethodBase.GetMethodFromHandle(RuntimeMethodHandle handle)
   at E.Main()

C:\Projects\roslyn\Binaries\Debug>ildasm e.exe
```

Quick inspection shows that the generated IL code has:

```
  IL_0001:  ldtoken    method instance void valuetype System.ValueTuple`2<int32,int32>::.ctor(!0,
                                                                                              !1)
  IL_0006:  call       class [mscorlib]System.Reflection.MethodBase [mscorlib]System.Reflection.MethodBase::GetMethodFromHandle(valuetype [mscorlib]System.RuntimeMethodHandle)
```

This should call the `GetMethodFromHandle` overload with a `RuntimeTypeHandle` parameter that should be set to `ldtoken valuetype System.ValueTuple`2<int32,int32>`. In contrast, the following works fine:

```
        Expression<Func<(int, int)>> f = () => (1, 2);
```

It seems the difference is noticed here:

```
NamedTypeSymbol.AllTypeArgumentCount()
SyntheticBoundNodeFactory.GetMethodFromHandleMethod(...)
SyntheticBoundNodeFactory.ConstructorInfo(...)
ExpressionLambdaRewriter.VisitObjectCreationExpressionInternal(...)
```

That method returns 2 for the use of the tuple literal `(1, 2)` but 0 for the use of `new (int, int)(1, 2)`. Looking higher up in the `LocalRewriter` it seems that `VisitObjectCreationExpression` receives the constructor of the tuple type but it never gets retargeted to the `TupleUnderlyingType` unlike what happens in the `VisitTupleLiteral` case.

**Comment by bartdesmet** [comment]
At first sight, it seems a substitution a la `node.Constructor.TupleUnderlyingMethod ?? node.Constructor` inside the `if (_inExpressionLambda)` in `VisitObjectCreationExpression` can address the issue. It'd require a change from `node.UpdateArgumentsAndInitializer` to the full-blown `node.Update` to pass in the rewritten constructor.

**Comment by bartdesmet** [comment]
I have a spot fix in my fork for expression tree futures @ https://github.com/bartdesmet/roslyn/commit/994f9642f02a9567d795f430fd9cb4b4c5519e6c. I haven't studied the code base extensively for the places where tuple types are retargeted to their underlying types, so the right fix may be in a different location. I'm planning to play around more with the intersection of expression trees and tuple types in the next few weeks.

**Comment by gafter** [comment]
The syntax `new (` is to be forbidden.

**Comment by bartdesmet** [comment]
Great, that will fix it :-). Do we have an up-to-date document on the C# 7.0 features and their language surface, reflecting latest decisions? I'm basing my investigations on the docs/features MD files right now.

**Comment by VSadov** [comment]
https://github.com/dotnet/roslyn/issues/10891   should make this problem unreachable since the code would be cause a compile error
