### ISSUE TITLE
How can Analyser and Code Fix Providers check for Language Features? 

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#12806]
How can Analyser and Code Fix Providers check for Language Features? 
How to indicate to the user that it is unavailable?
Or specify which version of the language it targets?

**Comment by bkoelman** [comment]
I did this some time ago....

https://github.com/bkoelman/ResharperCodeContractNullability/blob/staticnull/src/CodeContractNullability/CodeContractNullability/NullabilityConversionAnalyzer.cs#L143

**Comment by AdamSpeight2008** [comment]
@bkoelman Where is the function `SupportsFeature` defined?

**Comment by AdamSpeight2008** [comment]
@bkoelman  That's one way to do it.
I was thinking of suggesting making the the internal ones public, so that there is a definitive and supported way of check for features.

**Comment by srivatsn** [comment]
Tagging @jaredpar @jcouv and @gafter for comments.

**Comment by jaredpar** [comment]
The anazlyer has access to the `CSharpParseOptions` as a a part of getting the `SyntaxTree`  That has the `LanguageVersion` property which can be used to calculate available features.

**Comment by AdamSpeight2008** [comment]
@jaredpar  That requires knowledge of which version the feature is in.

If these where public then there be a simple way to check.
[GetLanguageVersion](https://github.com/dotnet/roslyn/blob/413c49e2fc11a0e01e99d87a253e81691ac541ba/src/Compilers/VisualBasic/Portable/Parser/ParserFeature.vb#L56)
[CheckFeatureAvailability](
https://github.com/dotnet/roslyn/blob/56f605c41915317ccdb925f66974ee52282609e7/src/Compilers/VisualBasic/Portable/Parser/Parser.vb#L6084)

**Comment by jaredpar** [comment]
So is your requestn to make the APIs public then?  The title of the bug is about the capability to detect which features are available.  That exists today as I noted.

**Comment by AdamSpeight2008** [comment]
@jaredpar  Nope it is also about conveying the information to the user.  Also your capability can only only detect the language version, not language features.

**Comment by gafter** [comment]
There is no public API to ask a compilation what language features are available to its source code. I'll label this an API feature request.

**Comment by gafter** [comment]
There were three questions in this issue:
1. How can Analyser and Code Fix Providers check for Language Features?
2. How to indicate to the user that it is unavailable?
3. Or specify which version of the language it targets?

I am retargeting this request to a request for a compiler API to check what language features are available.

If you are still interested in your questions 2 and 3, please create new, separate issues for them.

**Comment by jcouv** [comment]
@gafter I think we more or less dropped the language feature approach in favor of language versions. Should we close this issue?

**Comment by AdamSpeight2008** [comment]
@jcouv  The issue isn't about code internal to the Roslyn code, as it can access the internal function that check for the presence of a feature, but external user of Roslyn. 
For example say I'm writing a analyser to that converts `string.Format` to string interpolation. And the user is targeting a language version that doesn't support it. Then there is no point in the analyser being run or even loaded. The analyser should be able to ask if feature is available during initialisation to register to be run if said feature(s) are available. Akin to checking for browser feature rather the browser version.

**Comment by jcouv** [comment]
@AdamSpeight2008 can such analyzer access the language version for a compilation?
I think the answer is yes, and so that solves the problem (I agree with Jared).
There is strict equivalence between language version and feature support, unlike in the browser world. So exposing the concept of "feature" only increases complexity. 
https://github.com/dotnet/csharplang/blob/master/Language-Version-History.md

You bring up a separate concern which is optimizing which analyzers get loaded. To me that is a different and more plausible ask, something like letting analyzers declare what minimum language version they are  applicable for.  But given that "default" is the latest major version, I'm not sure whether that would optimize much.

**Comment by jcouv** [comment]
I'll go ahead and close the issue. 
Feel free to file a separate issue for the second ask you mentioned in the thread (not having analyzers load in some cases).
