### ISSUE TITLE
Interpolated String literals don't show typename quick info

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1280]
Normal & verbatim string literals show quick info for `System.String`.

Interpolated string literals don't show any quick info.

**Comment by gafter** [comment]
I'm not sure exactly what you mean. Are you saying that after typing `$"...".` you don't get a popup with the members of `string`?

**Comment by SLaks** [comment]
No; I mean that the `$"..."` token has no tooltip, unlike `"..."`, which does.

The tooltip doesn't add that much value, but the inconsistency is jarring.
