### ISSUE TITLE
Named param completion is broken

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#12808]
**Version Used**: 7/26 Roslyn.Master.Signed

Committing a named param with `colon` no longer commits the completion item. This breaks typing, as a subsequent space then removes the inserted colon, introducing errors in code.

**code:**

```C#
void TestMethod(string text, int count) { }

void TypeHere()
{
    TestMethod("", $$)
}
```

**Steps to Reproduce**:
1. At $$, fully type out `count:` followed by a `<space>`

**Expected Behavior**:
editor has text `count:` and a single space after that.

**Actual Behavior**:
editor has text `count` and a space after that. The inserted colon was removed by completion.

**Notes:** When the user types `:` completion should commit and the list should be dismissed, but that didn't happen, the list stays up and `:` is sent to editor. When i hit `<space>`, completion gets dismissed and it also removes the inserted `:`

**Comment by Pilchie** [comment]
Moving out of Preview 4, since we won't reset escrow for this.

**Comment by rchande** [comment]
Tested with latest bits, and this is fixed.
