### ISSUE TITLE
Encapsulate field offers two refactorings that do the same thing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#12800]
1. CTRL + . over _designTimeBuildRules

``` C#
    internal abstract class AbstractProvideLanguageServiceInfo 
    {
        private readonly Lazy<IImmutableSet<string>> _designTimeBuildRules
    }
```

Get offered the following:

![image](https://cloud.githubusercontent.com/assets/1103906/17222361/ba343ebc-54ac-11e6-9036-3e57f2a0763f.png)

~and~

![image](https://cloud.githubusercontent.com/assets/1103906/17222375/c45c645a-54ac-11e6-8900-603531680377.png)

I don't understand the difference

**Comment by Pilchie** [comment]
The difference is in the references to the field (if there are any).  In the first one, all existing references are updated to use the property, whereas in the second, the property is introduced, but any existing references still use the field.
