### ISSUE TITLE
Deconstruction-declaration: give better errors for bad syntax

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#12803]
The error for the first example should tell you that `int` isn't allowed in this position.
![should-use-var](https://cloud.githubusercontent.com/assets/12466233/17224586/67cdfa46-54b6-11e6-999d-7029cb9a8457.png)

The error for the second case should tell you that you're missing a type in front of `x2`.
![missing-type](https://cloud.githubusercontent.com/assets/12466233/17224609/815bc36c-54b6-11e6-8ee0-f442f248a04e.png)

**Comment by gafter** [comment]
Add myself to the assignee list, since I am revising the deconstruction syntax model and parser.

**Comment by alrz** [comment]
```cs
(1, 2) = (4, 5);
```

> The left-hand side of an assignment must be a variable, property or indexer

or a deconstruction thingy?
