### ISSUE TITLE
C# 7.0 patterns - constant pattern code generation & expression trees

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/roslyn#12813]
Consider the following code:

``` csharp
class P
{
    static void Main()
    {
        System.Func<int, bool> f = x => x is 42;
    }
}
```

Questions:
1. Do we need to emit a call to `object.Equals(object, object)` for integral types? The emitted IL code currently has two `box` instructions, one for `x` and one for `42`. Could a simple `ceq` suffice for types like these?
2. Capturing this in an expression tree seems to work and produces the lowered expression, i.e. the call to `object.Equals(object, object)`. That may be considered fine, but if the lowering changes (cf. 1 above), the consumer of the expression tree will also see a difference they may not expect.

For context, I'm looking into what it'd take to support patterns etc. in expression trees. If the constant pattern will work as-is due to lowering in the `LocalRewriter` and doesn't explicitly get rejected in an earlier phase with a "feature XYZ cannot be used in an expression tree" error, a C#-specific `IsPatternExpression` node may want to omit the constant pattern case; we wouldn't want to ship a hypothetical future version where expression trees with constant patterns start producing a C#-specific expression factory call, because the consumer would see a (reducible) extension node rather than the `Call` expression that's emitted now (and, based on 1 above, possibly an `Equals` binary expression).

**Comment by bartdesmet** [comment]
The relevant method is `CompareWithConstant` in https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs.

**Comment by gafter** [comment]
This should produce the obvious integer equality opcode.

**Comment by gafter** [comment]
Note that for `float` and `double`, we'd probably use `float.Equals(float)` and `double.Equals(double)`. See #13015.

**Comment by VSadov** [comment]
The perf part of the bug seems to be related to 
https://github.com/dotnet/roslyn/issues/16129

Expression tree scenario should be blocked by now.

**Comment by gafter** [comment]
@VSadov No, the expression-tree scenario is not blocked right now.

**Comment by gafter** [comment]
Adding the following test to verify that the first item is fixed in the pending branch for C# 8:

``` c#
        [Fact, WorkItem(12813, "https://github.com/dotnet/roslyn/issues/12813")]
        public void NoBoxingOnIntegerConstantPattern()
        {
            var source =
@"public class C
{
    static bool M1(int x)
    {
        return x is 42;
    }
}";
            var compilation = CreateCompilation(source, options: TestOptions.ReleaseDll);
            compilation.VerifyDiagnostics();
            var compVerifier = CompileAndVerify(compilation);
            compVerifier.VerifyIL("C.M1",
@"{
  // Code size        6 (0x6)
  .maxstack  2
  IL_0000:  ldc.i4.s   42
  IL_0002:  ldarg.0
  IL_0003:  ceq
  IL_0005:  ret
}");
        }
```

**Comment by gafter** [comment]
The second issue is a dup of #12900 and verified (that we now reject this kind of code) by existing test `CSharp7FeaturesInExprTrees`.

**Comment by gafter** [comment]
Test added to confirm fixed in https://github.com/dotnet/roslyn/issues/25567

**Comment by johnkellyoxford** [comment]
Bumping this because it doesn't seem to be fixed
<https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4aNYgGYmpBkIYBvGgzMNT5y2YDaAWRgYAFhAAmASXGSAFA+dvPMUkAeTE+CC5cFgBBAHNY2FxcXgUYUL58XgAvbHCuAEoAXWsmXWIUBgBxCDcRVxhYmC4AdV5nAFEARw5sSVxvXh4GCDQGWAAzBlcIDmBpMdUOSQx8kpNqc02GXknvCBYunr7vJHzVja2zdcvLxKWMBgBeBlZSbQ0Ly4BfEp/Pi3+9kcLg8Xl8wICXnSvAiUTiCVUyVS0MyOTyRRKOiYFWqtTcDSarWcoRkuWgAyGIwWk2ms3md2W5021xuOwYeyez1OJWZPJuDIez1e7z5Zj+m3FVkBfhBgR8MshQWhsJi8USSLSYX42VyMIKxX+WPKDAAQthXHUCVwKQ8qRMpjM5jAFrh7kzzCzLmyObxcC93ZdPTczAKni8WG8PsHJWKaF8gA=>

This has a very considerable effect on the generated ASM, which is why it is an issue
