### ISSUE TITLE
How to use Formatter.Format(SyntaxNode,Workspace)?

### ISSUE THREAD

**Issue by yhvicey** [dotnet/roslyn#12817]
**Version Used**: 
1.3.2

**Steps to Reproduce**:
First I tried to use these codes to format my code:

```
var workspace=MSBuildWorkspace.Create();
node=Formatter.Format(node,workspace);
```

And it throw IOException when executing MSBuildWorkspace.Create();

> Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Then I tried to install BuildTools from Nuget as SO said: http://stackoverflow.com/questions/25504951/msbuildworkspace-create-throws-exception

And I get lots of errors,so I uninstall it, but it won't throw a IOException after that. I totally don't know how that works.

Unfortunately, the SyntaxNode won't be formatted after I called Formatter.Format even if there is no exception or warning or error at all.

So what's the correct way to use that,better with out the BuildTools nuget package?

**Comment by yhvicey** [comment]
By the way, I can easily format some code in a standalone console application without buildtools or IOException. So why that's incompatible with my project?

**Comment by svick** [comment]
Do you actually need `MSBuildWorkspace`? If all you want to do is to format the node, `AdhocWorkspace` should be enough.

**Comment by yhvicey** [comment]
@svick Thanks for your help. I'll try it when I back to work.

**Comment by yhvicey** [comment]
@svick It works.Thanks alot!
