### ISSUE TITLE
Intermittent VS crash on close at FileChangeTracker.StopFileChangeListening for deleted analyzer assembly

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#12819]
See http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_prtest/469/VS_Integration_Test_Logs/ (its failed couple more times for me since yesterday)

The failure seems to happen in StartTargetAction and looks unrelated to the test, but seems to happen only for this test:
```
VS main window was brought to foreground.
Started new VS and Apex Initialized
Begin Waiting for Apex Communication
--------------------------------
System.Exception: Apex was not ready after 300 seconds.
   at Roslyn.VSHosting.Test.StartTargetAction.WaitForApex(TimeSpan timeout) in d:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\Test\Actions\VisualStudio\StartTargetAction.cs:line 281
   at Roslyn.VSHosting.Test.StartTargetAction.Execute(TaoEngine engine) in d:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\Test\Actions\VisualStudio\StartTargetAction.cs:line 109
   at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
   at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
================================
```

**Comment by mavasani** [comment]
Lot of VSI runs are failing due to this issue:

1. http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_prtest/489/ (and 3 prior failures for this PR)
2. http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_prtest/486/

This test had intermittent failures on Dev14, but seems to be failing very often now. Failure seems to be in StartTargetAction, so likely something has gone corrupt, but only CSharpEventHookup seems to be failing.

Marking this urgency now.

**Comment by mavasani** [comment]
All the failure screenshots show that the error list in focus when the test fails. CSharpErrorLog is the test prior to CSharpEventHookup, which probably doesn't close the error list at exit. I'll change the StartTargetAction to close ErrorList.

**Comment by Pilchie** [comment]
Should the errorlist test be changed to close/dismiss it instead, in case the run order changes?

**Comment by mavasani** [comment]
Yes, that seems like a cleaner fix - I also see CSharpFormatting also failed twice due to this issue, and the prior test is CSharpFixAllOccurrences, which also uses the error list.

I'll fix the error list tests.

**Comment by mavasani** [comment]
Okay, so this is actually failing due to a product issue. VS is crashing intermittently in [FileChangeTracker.StopFileChangeListening](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/FileChangeTracker.cs,95) at the end of error list/analyzer related tests with below exception/call stack:

```
Message: Error reading the C:\Users\mavasani\AppData\Local\Temp\Closed\Test\Solutions\Newtonsoft.Json\Newtonsoft.Json directory.

File Path: C:\Users\mavasani\AppData\Local\Temp\Closed\Test\Solutions\Newtonsoft.Json\Newtonsoft.Json\Analyzers\System.Runtime.CSharp.Analyzers.dll

Call stack:
 	mscorlib.dll!System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(int errorCode)	Unknown
>	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.FileChangeTracker.StopFileChangeListening() Line 95	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.FileChangeTracker.Dispose() Line 102	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.AnalyzerFileWatcherService.Tracker_UpdatedOnDisk(object sender, System.EventArgs e) Line 140	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.FileChangeTracker.Microsoft.VisualStudio.Shell.Interop.IVsFileChangeEvents.FilesChanged(uint changeCount, string[] files, uint[] changes) Line 116	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.FileChangeSubscription.NotifyAsync(Microsoft.VisualStudio.Shell.Interop._VSFILECHANGEFLAGS changes, System.Threading.CancellationToken cancellationToken)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)	Unknown
```

Close target ends up deleting the test directory, and the file change tracker crashes on trying to unadvise file change for non-existent analyzer assembly.

**Comment by mavasani** [comment]
I am going to disable the error log/fix all tests (only these use private analyzer assemblies, which lie in temp solution dir that gets deleted) and change this into a product issue.
