### ISSUE TITLE
Diagnostics roundtripped via DiagnosticData have incorrect Diagnostic.Descriptor.MessageFormat

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#1282]
Looks like we aren't round-triping MessageFormat in the descriptor correctly through DiagnosticData.

I noticed that clicking on the diagnostic id link in preview pane header sends complete diagnostic text (including names of types etc.) to bing. On debugging this seems to be the result of a bug in DiagnosticData implementation (we are not preserving message format when we call Diagnostic.Create withing DiagnosticData.ToDiagnostic()).

DiagnosticData should round trip all fields from the original diagnostic. Otherwise, this can end up causing confusion when the round tripped diagnostics are consumed (in code fix providers etc.)

We should have tests that validate that all fields in a given diagnostic (and its descriptor) are correctly roundtripped via DiagnosticData.

**Comment by heejaechang** [comment]
after this - https://github.com/dotnet/roslyn/pull/2230

this bug is no longer needed. I will close this bug.

**Comment by heejaechang** [comment]
by the way, DiagnosticData <=> Diagnostic is not currently round trip-able. so if there is any code that treat it as round-trip-able, we should stop doing it.

**Comment by heejaechang** [comment]
another case where https://github.com/dotnet/roslyn/issues/2304 could prevent this kind of issue from happening.
