### ISSUE TITLE
[Test Failure] Visual Studio Timed Out in windows_vsi_p1_open_prtest on PR #12826

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#12831]
PR: [#12826](https://github.com/dotnet/roslyn/pull/12826) *porting OOP to preview 4 branch* by @heejaechang
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p1_open_prtest/3/

**Issue 1: Visual Studio Timed Out**
Visual Studio Timed Out

...

PublicKeyToken=b03f5f7f11d50a3a due to loader exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.ReferenceManager.Providers, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

..

due to it, test got stuck and timed out.

**Comment by Pilchie** [comment]
@mavasani  - could this be related to your work to support VS "15"?

**Comment by mavasani** [comment]
This is due to the sign-in dialog popping up: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p1_open_prtest/3/artifact/Open/Binaries/Release/Screenshots/2016-07-29_22-53-58_33%20-%20Failed%20AddProject%20Attempt%201.png

@tannergooding Given that we are signed in with your account, can you take care of this?

**Comment by heejaechang** [comment]
@tannergooding @Pilchie any idea on when this can be resolved. I have one preview 4 PR blocked by this issue.

**Comment by mavasani** [comment]
Actually lot of VSI runs are now failing due to the same issue: All runs for [this PR](https://github.com/dotnet/roslyn-internal/pull/1209). Should I just merge in the netci.groovy change to move us to Dev15 machines for integration tests?

**Comment by Pilchie** [comment]
Tag @tannergooding since I saw some mail about this internally.

**Comment by mavasani** [comment]
@tannergooding Can you sign-in on the ibld machines? I have taken the rbld machines offline for migration to Dev15.

**Comment by tannergooding** [comment]
I'll resolve the ibld machines.

**Comment by tannergooding** [comment]
Machines are updated.

**Comment by mavasani** [comment]
Thanks Tanner. @heejaechang I have requested retest vsi on your PR.
