### ISSUE TITLE
Question: Any plans to implement support for transactional memory ?

### ISSUE THREAD

**Issue by vbcodec** [dotnet/roslyn#12835]
New Skylake CPU have support for transactional memory and optimistic locks. Such features can greatly ease write multithreaded apps, and improve their performance.
Best way to implement TM is probably implement it in CLR and language. But it may be possible to implement it only by language by using pinvoke, so CLR do not need to be changed.

**Comment by eyalsk** [comment]
I don't think they will ever go down with P/Invoke and workaround the CLR like this, especially when it comes to memory management.

**Comment by benaadams** [comment]
Related https://github.com/dotnet/corefx/issues/10481

**Comment by vbcodec** [comment]
@benaadams 
Not really related. Two diffrent concepts, but both used for multithreading.

**Comment by gafter** [comment]
I haven't heard about any such plans.
