### ISSUE TITLE
Operators should be exposed for `System.IntPtr` and `System.UIntPtr`

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#12836]
**Issue:**
The CLR supports a set of operators for the `System.IntPtr` and `System.UIntPtr` types (`native int`). These operators can be seen in `III.1.5` of the Command Language Infrastructure specification. However, these operators are not supported by the C#.

**Workaround:**
Either directly emit IL or write non-optimal code that does not directly translate to the appropriate IL instructions.

**Request:**
Language support should be provided for the full set of operators supported by `System.IntPtr` and `System.UIntPtr`. These operators are: `Add`, `Divide`, `Multiply`, `Remainder`, `Subtract`, `Negate`, `Equals`, `Compare`, `And`, `Not`, `Or`, `XOr`, `ShiftLeft`, `ShiftRight`.

**Other Thoughts:**
C# seems to treat both `IntPtr` and `UIntPtr` as a type only used for interop and for representing pointers in a 'safe' manner, when it is really just:

> an integer whose size is platform-specific.

It should be possible for a user to treat the `IntPtr` and `UIntPtr` types as an equivalent to the native `size_t` type. However, in order to do that, one must may have to deal with one or more of the following:
- Perform multiple levels of casting
- Use integers whose size is larger than their platform's native size
- Have branching to use integers that are platform-specific
- Work with unsafe code and do pointer arithmetic

**Comment by tannergooding** [comment]
An issue has also been filed against CoreFX for 'friendly operators' to be provided for languages that do not support the operators: https://github.com/dotnet/corefx/issues/10457

**Comment by gafter** [comment]
This sounds like a C# language request, not a compiler request. The compiler doesn't usually expose operators that are not mandated by the language specification.

**Comment by gafter** [comment]
Although adding them to the source of those types, as @tannergooding says is happening, is another way to do it.

**Comment by tannergooding** [comment]
I've added some additional thoughts on the matter in the OP.

**Comment by tannergooding** [comment]
Closing this. The issue in question was moved to the mailing list and accepted as a proposal: https://github.com/dotnet/csharplang/blob/master/proposals/intptr-operators.md
