### ISSUE TITLE
AdditionalFiles do not show up in CompilationStartAnalysisContext.Options.AdditionalFiles

### ISSUE THREAD

**Issue by torgabor** [dotnet/roslyn#12840]
**Version Used**: 
Microsoft.CodeAnalysis.Analyzers version=1.1.0
others: 1.2.1
**Steps to Reproduce**:
1. Create example analyzer project, modify it to include a CompilationStartAction
2. Add text file to project, set its type to "AdditionalFiles"
3. The CompilationStartAnalysisContext' Options.AdditionalFiles array reports as empty.
   This is consistently reproducible between two installations.

I've tried following the instructions on adding additional files:
https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Using%20Additional%20Files.md
I'm really thinking I'm missing something here, however the whole process seems pretty straightforward.
I can send an example project if it helps.
**Expected Behavior**:
Included text file appears in context.Options.AdditionalFiles
**Actual Behavior**:
context.Options.AdditionalFiles is empty

**Comment by Pilchie** [comment]
Also tagging @srivatsn - does this all seem right to you?

**Comment by srivatsn** [comment]
Ya the instructions in that doc should work. @torgabor, do you see the same behavior if you add some other item type to <AdditionalFileItemNames> as well?

**Comment by torgabor** [comment]
Hi! I'm not sure what you mean by adding other item type.
I've tried specifying Content in the AdditionalFileItemNames tag also, then setting the type of an item to Content. Same results, file does not show up.
By the way I'm using VS 2015 Update 3.

**Comment by jaybarden** [comment]
I've just encountered the same issue when running VS2017 15.7.1 for a .Net Standard project (using the https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Using%20Additional%20Files.md example) so it still seems to be an issue :-(

**Comment by Pilchie** [comment]
@jaybarden If you:

1. Start a Developer command prompt
2. Run `set PROJECTSYSTEM_PROJECTOUTPUTPANEENABLED=1`
3. Start VS from the command prompt with `devenv`
4. Open your solution

There should be an extra output window pane that logs what the project system passes to the language service.  Can you share that, and we can see if the project system is telling Roslyn about the file?

**Comment by jaybarden** [comment]
[ProjectOutputForTermsTesting.txt](https://github.com/dotnet/roslyn/files/2016098/ProjectOutputForTermsTesting.txt)

[Analyzer1.zip](https://github.com/dotnet/roslyn/files/2016101/Analyzer1.zip)
@Pilchie - I've attached both the output and a zip of the solution I was using to try this out. Please let me know if you need anything else and many thanks for the speedy response!
Jay

**Comment by Pilchie** [comment]
Note however, that from [this comment](https://github.com/dotnet/roslyn/blob/master/build/Targets/Imports.targets#L452), I see that https://github.com/dotnet/project-system/issues/2160 *is* still an issue.

**Comment by ElanHasson** [comment]
I'm seeing this in `CompilationAnalysisContext` as well.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this in 5+ years.
