### ISSUE TITLE
constraints do not count toward generic parameter "use" in analysis rules.

### ISSUE THREAD

**Issue by burtonrodman** [dotnet/roslyn#12857]
In Visual Studio 2015 with Update 3, the following code gives the warning:
Type parameter 'TKey' is never used.

Even though I don't need it for the body of the code, I do need it to properly constraint TMock.  The code will not compile without TKey.

```
    private Mock<TMock> SetupMockFor<TMock, TEntity, TKey>(string sharedReferences, string referenceFile)
        where TEntity : class
        where TMock : class, IReadOnlyRepository<TEntity, TKey>
    {
        var data = DeserializeReferenceFile<List<TEntity>>(
            Path.Combine(sharedReferences, referenceFile));

        var mock = new Mock<TMock>();
        mock.Setup(c => c.GetAll()).Returns(data);

        return mock;
    }
```

Please consider the mention of a generic parameter in constraints as "usage" of the parameter.

**Comment by gafter** [comment]
I would call this a bug.

**Comment by jcouv** [comment]
I'm not able to repro this in Visual Studio 2017 (version 15.5). 

I'll go ahead and close as Not Repro.
@burtonrodman Feel free to re-open if you can still repro this. If you do, please let me know what is the error code you're getting. Thanks
