### ISSUE TITLE
Constructors of all analysis context structs in DiagnosticAnalysisContext should be made internal

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#1285]
For example, see http://source.roslyn.io/Microsoft.CodeAnalysis/R/b6140b39b0759dd4.html

These constructors were public as they needed to be consumed explicitly by the IDE driver. Given the current implementation and future plans of merging both drivers, we can safely internalize these APIs. @JohnHamby can probably confirm this and do it as part of his prototype work?

**Comment by mavasani** [comment]
Actually, I would need to modify these constructors as part of #252 so I'll take this up myself.

**Comment by mavasani** [comment]
And I am going to hand this back to John, as I figured out we can't make this change until the drivers are merged. Even though the constructors of these context types are accessed only from within the shared AnalyzerDriver project, when the shared project is compiled into Features.csproj it needs public access to it.

**Comment by JohnHamby** [comment]
At one point in time, the design team wanted these constructors to be public to make it easier for analyzer authors to write tests. I've never been entirely comfortable with them being public.

**Comment by mavasani** [comment]
To me it seems that the right approach is to expose APIs to enable public implementations of the analyzer driver. Exposing just the barebone context object constructors might be good for tests, but that doesn't justify making an API public, especially given that one cannot write a full fledged and performant analyzer driver on top of it. Add to it all the exception handling hooks that need to be in place for the analyzer callbacks. We don't want to force public clients to do all that themselves.

My preference is once we make AnalyzerDriver public we should move the tests over to either consuming this driver or implement a custom driver on top of it, using its public APIs. They shouldn't have to explicitly deal with creating the context object or explicitly knowing about what actions to execute and how.

**Comment by srivatsn** [comment]
I think testability of an API is a very important aspect of it. Yes one would need to do a lot of work to write their own driver and yes we should expose APIs to make that easier but I see that as an orthogonal problem. These context objects are basically glorified tuples - they contain hardly any functionality and I don't think we are protecting any surface area by making them hard to construct. By keeping these public, we are enabling simple API tests or some small console app (imagine I wanted a console app that simply needed to invoke a couple of syntaxtree actions on the source- it will be fairly straightforward to write such an app if these were public - maybe that scenario doesn't require a performant engine or is a closed system and doesn't care about handling exceptions etc.) 

I see some positives and hardly any negatives in keeping these public.

**Comment by mavasani** [comment]
I do see a couple of negatives here:

1. What the tests require is a more fine grained test-only analyzer driver or rather executor, which can be asked to run a set of actions on a given code unit (symbol/node/compilation etc.). Essentially the methods provided by the currently internal AnalyzerExecutor. By providing them just the bare bone context object constructors and asking them to do all the execution is inviting trouble, even for simple test drivers. Will this test driver work if analyzer kicks of multiple threads and reports diagnostics from all of them simultaneously? Who needs to guarantee thread safety of reporting diagnostics here, probably the test driver? We are pushing this unnecessary burden onto them.
2. Having a public API to enable running custom subset of actions is exactly what we wanted to avoid when we internalized AnalyzerDriver and set of Execute***Actions method. If it was just for testability, then I don't see any harm in even making Execute***Actions methods public in test layer. I feel that an API shouldn't be public just for making it testable, it should instead have a counterpart API in the test layer to make this contract explicit.

**Comment by mavasani** [comment]
Btw, I don't see this issue as being critical or blocking for anything in particular. I am totally fine with won't fixing this for now and taking a second look at these APIs when we make the AnalyzerDriver API public in the future. We may want to double check if we really need these to be public at that point.

**Comment by srivatsn** [comment]
Let's take a look at this when we design the AnalyzerDriver API. Won't fixing now.
