### ISSUE TITLE
Workspace_RoundTrip_Test_Desktop is flaky

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#12859]
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/1832/testReport/junit/Microsoft.CodeAnalysis.UnitTests/SnapshotSerializationTests/Workspace_RoundTrip_Test_Desktop/

**Comment by tmat** [comment]
@heejaechang

**Comment by heejaechang** [comment]
this is already fixed in preivew 4 branch. I will bring the change to master.
