### ISSUE TITLE
Getting Values from Attributes applied on a class

### ISSUE THREAD

**Issue by kyewei** [dotnet/roslyn#12868]
**Version Used**: 
Roslyn CodeAnalysis 1.2.2 dll's from Nuget

**Issue**:
Concerning the following piece of code, there doesn't seem to be a way to access (semantically and not syntactically) the fields specified for the TestAttribute through the DefaultTestAttribute base call. I know that with class `A`, we can get `field1` and `field2` with something along the lines of `classATypeSymbol.GetAttributes()[0].ConstructorArguments[0].Value as int` to get the value, however, there is no way to get the same things when it is specified through a base constructor call.

I can do something along the lines of `semanticModel.GetConstantValue(classATypeSymbol.GetAttributes()[0].AttributeConstructor[0].DeclaringSyntaxReferences[0].GetSyntax().Initializer.ArgumentList.Arguments[0].Expression)`, but this is unreliable, and can't evaluate expression values the same way the above snippet can.

I haven't found a nice way to go from the attribute constructor invocation to the base call symbol nicely. Are there any nicer API calls for this type of analysis? A nice remedy for this would be if the `INamedTypeSymbol` interface, or the `AttributeData` class exposed some `::BaseCallSymbol()` method but I haven't seen an API for it either.

```c#
public class TestAttribute : Attribute 
{
    public TestAttribute(int field1, float field2) {}
}

public class DefaultTestAttribute : TestAttribute 
{
    public DefaultTestAttribute() : base(1 | 2, Math.Pow(2, 3)) {}
}

[TestAttribute(100, 1.01)]
public class A {}
[DefaultTestAttribute]
public class B {}
```

**Comment by KirillOsenkov** [comment]
I've always wanted this to pre-calculate MEF composition ([Import]/[Export] attributes) without loading an assembly and letting attribute constructors run.

**Comment by steffenloesch** [comment]
Any feedback on this? I'd be interested in an answer too.

**Comment by gafter** [comment]
The compiler's semantic model is not intended to tell you the results of computations that occur at runtime.

**Comment by steffenloesch** [comment]
I always thought that attributes that you set with the square-bracket syntax get instantiated at compile-time. I can certainly use reflection ([System.Attribute.GetCustomAttributes](https://msdn.microsoft.com/en-us/library/f2z5sd1c(v=vs.110).aspx)) on an assembly to retrieve an instance of an attribute, without ever running the assembly. 

@gafter, can you please explain why this is a runtime computation, and what Roslyn APIs are appropriate for the scenario above?

**Comment by kyewei** [comment]
If I understand correctly, `AttributeData` can provide the functionality of `::ConstructorArguments[0].Value` because attaching attributes to things (classes, parameters, etc) using `[Attr()]` enforces a constant expression requirement on the constructor arguments. However, using the base call to supply things does not. 

If the above is correct, then I can understand why in the most generic sense, base call computations "happen at runtime". But Roslyn definitely has the ability to find out if a given expression is constant or not - so I also think it's reasonable to offer an API to try to get the value, and return `null` if it is not constant: maybe a `::BaseMethodCallSymbol()` which has an Arguments field that is a list and provides some `::TryGetConstantValue()`, so that cases where things are constant the value can be found. Thoughts?

**Comment by gafter** [comment]
Roslyn does not, in general, have the code of the attribute constructor. So it doesn't know what the constructor does. But if it is available in source, a client of the Roslyn APIs can compute what it might do at runtime.
