### ISSUE TITLE
Local variable after parameter suppresses completions

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1287]
Source:

```C#
class A {
	A(int a) { a
	int a;
}
```

(a practical example of this is while typing a constructor before a field declaration)

The `a` parameter does not appear in IntelliSense in the constructor body (where I put the stray `a` token), because of the subsequent local variable.

This is a violation of the principle that text to the right of the caret should not affect IntelliSense, and is particularly annoying when simply missing a closing brace.

**Comment by rchande** [comment]
Completion is filtering out locals declared after the caret (which the second "a" is), but LookupSymbols doesn't even return the parameter "a". 

Compiler team, is there anything you could do here to prevent the parameter from getting suppresed?

**Comment by rchande** [comment]
Feel free to reassign to me and move back to IDE if not.

**Comment by gafter** [comment]
I think the answer is no, as the parameter is shadowed by a local in the code as written.

**Comment by SLaks** [comment]
But locals _cannot_ shadow parameters, so why not return both? (as errored state)

**Comment by rchande** [comment]
While it is the principle that text to the left shouldn't affect completion, in this case the missing close brace really does change the meaning of the code. We'd like to do something about this, but don't have a great solution for now. Moving out to the "1.1" milestone.

**Comment by DustinCampbell** [comment]
Shifting to 1.2. This is probably not something we'll get to for awhile.

**Comment by Pilchie** [comment]
Given that we haven't heard about this in any other forum, and don't actually know *how* to fix it, let's close this bug.
