### ISSUE TITLE
Efficient multi-document editing

### ISSUE THREAD

**Issue by Sebazzz** [dotnet/roslyn#12876]
For one of the code fixes I'm developing I have the need to walk and editing multiple documents in the solution. (It involves changing how certain methods are called, among others).

I have my code fix working, but it is not-too-fast. I'm unsure how to handle multiple edits in multiple documents in a performant way. 

My basic algorithm is as follows:
``` C#
IEnumerable<Document> documents = solution.Projects.SelectMany(x => x.Documents);

// Rewrite the other documents
foreach (Document document in documents) {
	if (!document.SupportsSyntaxTree || !document.SupportsSemanticModel) {
		continue;
	}
        // Method name changed for brevity. Accepts an Document and returns an SyntaxNode.
        // For each document I need to use its semantic model
	newRoot = await Do(document, context, cancellationToken).ConfigureAwait(false);

	if (newRoot != null) {
		solution = solution.WithDocumentSyntaxRoot(document .Id, newRoot);
	}
}
```
As I understand, once you create a new document with the new syntax root, a new solution is created and along with that (due to the backreferences between project and solution, project and document) new document and project instances.

The other way is to use `Document.WithSyntaxRoot` which is [essentially the same](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/Document.cs,6f5c972effc26722). 

Is there a better and more efficient way?

**Comment by Pilchie** [comment]
Tagging @mattwar

**Comment by mattwar** [comment]
No, there is no alternate way to bulk edit documents.

**Comment by Sebazzz** [comment]
And when it comes to replacing a document in a solution, for example, by a document returned bij `Simplifier`, is there a better way than:

``` C#
solution = solution.WithDocumentSyntaxRoot(newDocument.Id, await newDocument.GetSyntaxRootAsync(cancellationToken))
```

It seems a lot of allocations are made just for the sake of changing a document.

**Comment by mattwar** [comment]
You also probably just made a bunch of allocations changing the syntax tree.  A few more won't add measurable GC pressure.  Also, changing lots of documents is uncommon behavior, that happens only during situations like global code fixes, which is not a typing responsiveness scenario, which is the typical problem with GC pressure.

**Comment by mattwar** [comment]
For bulk edits, and alternative might look like this.

solution = solution.WithDocumentSyntaxRoots(docIdsAndRoots);

But that would encourage your 'modify all documents' code fix to hold onto all new tree roots, which would cause a memory issue in VS.  The solution itself has logic that limits the number of syntax trees (that it knows about) that are held in memory.

**Comment by Sebazzz** [comment]
No, you're right. It is about a global code fix, so responsiveness doesn't matter. Thanks for the info.
