### ISSUE TITLE
Duplicate nuget.exe with 2 versions

### ISSUE THREAD

**Issue by codespare** [dotnet/roslyn#1288]
Totally minor, but there is a nuget.exe 2.8.0 under /src and another 2.8.2 under /src/Samples in master.

**Comment by amcasey** [comment]
@tannergooding This has been fixed, right?

**Comment by tannergooding** [comment]
@amcasey, yes, we should only have one instance of `nuget.exe` in our repo now.

**Comment by amcasey** [comment]
@codespare Please let us know if you're still seeing two copies after fetching latest.

**Comment by codespare** [comment]
It is, nuget.exe 3.2.0.10516
Having issues with
``` xml
<NuGetPackageRoot Condition="'$(NuGetPackageRoot)' == '' and
     '$(OS)' == 'Windows_NT'">$(UserProfile)\.nuget\packages</NuGetPackageRoot>
```
in ```build\VSL.Settings.targets``` though, which seems to contradict
``` xml
<config>
   <add key="repositoryPath" value="../packages" />
</config>
```
in ```nuget.config```
Are those new conventions?
A side effect is the last successful build of the CoreCLR pieces I got was on October 4th. Those errors on package restore and fail to build with missing packages since.

**Comment by amcasey** [comment]
@agocke @tannergooding Can you help @codespare?

**Comment by codespare** [comment]
Also, there is a 2nd
``` xml
<PropertyGroup>
   <NuGetPackageRoot Condition="'$(NuGetPackageRoot)' == ''">$(UserProfile)\.nuget\packages</NuGetPackageRoot>
</PropertyGroup>
```
further down in ```build\VSL.Settings.targets``` line 63-65,
and
``` xml
    <NuGetCommandLineAssemblyVersion Condition="'$(NuGetCommandLineAssemblyVersion)' == ''">2.8.5</NuGetCommandLineAssemblyVersion>
```
does not reflect the version bump line 98. It is only used to define ```NuGetCommandLineVersion``` which doesn't seem to be referenced anywhere and could be removed I think.

**Comment by tannergooding** [comment]
The inconsistencies you are seeing are all related to some of our internals and should not impact your ability to build/use Roslyn.

A clean enlistment and calling `.\cibuild.cmd` (or `.\cibuild.sh` on *nix systems) should always result in a clean build if the build queues are also green.

Is this not what you are seeing?

**Comment by codespare** [comment]
Not recently, using cibuild.cmd /release, the boostrap stage goes without a glitch, but the main build warns during:
```nuget.exe restore -nocache C:\Dev\build\roslyn\master\Roslyn.sln```
with
```
...
Restoring packages for C:\Dev\build\roslyn\master\src\Scripting\VisualBasic\project.json...
WARNING: Unknown Compatibility Profile: net46.app
WARNING: Unknown Compatibility Profile: dnxcore50.app
All packages are compatible with .NETPlatform,Version=v5.0.
Restoring packages for C:\Dev\build\roslyn\master\src\Scripting\Core\project.json...
WARNING: Unknown Compatibility Profile: net46.app
WARNING: Unknown Compatibility Profile: dnxcore50.app
All packages are compatible with .NETPlatform,Version=v5.0.
Restoring packages for C:\Dev\build\roslyn\master\src\Scripting\CoreTest\project.json...
WARNING: Unknown Compatibility Profile: net46.app
WARNING: Unknown Compatibility Profile: dnxcore50.app
All packages are compatible with .NETPlatform,Version=v5.0.
Generating MSBuild file ScriptingTest.nuget.props.
Restoring packages for C:\Dev\build\roslyn\master\src\Scripting\CSharp\project.json...
WARNING: Unknown Compatibility Profile: net46.app
WARNING: Unknown Compatibility Profile: dnxcore50.app
All packages are compatible with .NETPlatform,Version=v5.0.
Restoring packages for C:\Dev\build\roslyn\master\src\Scripting\CSharpTest\project.json...
WARNING: Unknown Compatibility Profile: net46.app
WARNING: Unknown Compatibility Profile: dnxcore50.app
...
Restoring packages for C:\Dev\build\roslyn\master\src\Debugging\Microsoft.DiaSymReader.PortablePdb.Tests\project.json...
WARNING: Unknown Compatibility Profile: net46.app
WARNING: Unknown Compatibility Profile: dnxcore50.app
...
Restoring packages for C:\Dev\build\roslyn\master\src\Test\Utilities\Portable\project.json...
WARNING: Unknown Compatibility Profile: net46.app
WARNING: Unknown Compatibility Profile: dnxcore50.app
...
Restoring packages for C:\Dev\build\roslyn\master\src\Scripting\VisualBasicTest\project.json...
  NotFound https://api.nuget.org/v3-flatcontainer/runtime.unix.system.threading/index.json 1165ms
WARNING: Unknown Compatibility Profile: net46.app
WARNING: Unknown Compatibility Profile: dnxcore50.app
```
which ends with the following errors:
```
Error: DownloadPackageAsync: https://www.myget.org/F/dotnet-core/api/v2/package/runtime.ubuntu.14.04-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.1-beta-23401
  A task was canceled.
Error: DownloadPackageAsync: https://www.myget.org/F/dotnet-core/api/v2/package/runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.1-beta-23401
  A task was canceled.
Error: DownloadPackageAsync: https://www.myget.org/F/dotnet-core/api/v2/package/runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.1-beta-23401
  A task was canceled.
Error: DownloadPackageAsync: https://www.myget.org/F/dotnet-core/api/v2/package/runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.1-beta-23401
  A task was canceled.
Error: DownloadPackageAsync: https://www.myget.org/F/dotnet-core/api/v2/package/runtime.ubuntu.14.04-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.1-beta-23401
  A task was canceled.
Error: DownloadPackageAsync: https://www.myget.org/F/dotnet-core/api/v2/package/runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.1-beta-23401
  A task was canceled.
Error: DownloadPackageAsync: https://www.myget.org/F/dotnet-core/api/v2/package/runtime.ubuntu.14.04-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.1-beta-23401
  A task was canceled.
Value cannot be null.
Parameter name: stream
```

after which ```msbuild /v:m /m /p:BootstrapBuildPath=C:\Dev\build\roslyn\master\Binaries\Bootstrap BuildAndTest.proj /p:Configuration=Release /p:Test64=``` fails on:
```
C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(89,5): error :
The package Microsoft.Win32.Registry with version 4.0.0-beta-23401
could not be found in C:\Users\User\.nuget\packages.
Run a NuGet package restore to download the package.
[C:\Dev\build\roslyn\master\src\Compilers\VisualBasic\VbcCore\VbcCore.csproj]
...
C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(89,5): error :
The package Microsoft.Win32.Registry with version 4.0.0-beta-23401
could not be found in C:\Users\User\.nuget\packages.
Run a NuGet package restore to download the package.
[C:\Dev\build\roslyn\master\src\Compilers\VisualBasic\VbcCore\VbcCore.csproj]
...
C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(89,5): error :
The package Microsoft.Win32.Registry with version 4.0.0-beta-23401
could not be found in C:\Users\User\.nuget\packages.
Run a NuGet package restore to download the package. [C:\Dev\build\roslyn\master\src\Compilers\VisualBasic\VbcCore\VbcCore.csproj]
...
C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(89,5): error :
The package Microsoft.Win32.Registry with version 4.0.0-beta-23401
could not be found in C:\Users\User\.nuget\packages.
Run a NuGet package restore to download the package.
[C:\Dev\build\roslyn\master\src\Interactive\CsiCore\CsiCore.csproj]
```

I think it is somehow caused in the nuget restore stage because current ASP.NET 6 beta builds on the same host, but restores and caches its packages differently in $USERPROFILE%\.dnx\packages.

**Comment by tannergooding** [comment]
@agocke or @jasonmalinowski , could you take a closer look (or direct to someone who can).

**Comment by jasonmalinowski** [comment]
The "unknown compatibility profile" warnings are (unfortunately) expected for now. Those download errors aren't though. @tannergooding, @agocke, are those packages expected to be there?

**Comment by agocke** [comment]
```
Error: DownloadPackageAsync: 
https://www.myget.org/F/dotnet-core/api/v2/package/runtime.ubuntu.14.04-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.1-beta-23401
 
A task was canceled.
```

Looks like NuGet is failing to download some packages. Don't know why, though.

**Comment by ManishJayaswal** [comment]
@codespare can you retry this? If this issue persists then we will engage someone from the NuGet team.

**Comment by codespare** [comment]
Doing that now.

Regarding the errors when restoring packages, there could be an issue with the way nuget deals with large solutions. It is very aggressive with the connections: a snapshot in tcpview during Roslyn bootstrap stage shows 104 established connections receiving packages and 65 in fin_wait all from the same nuget.exe process.
I guess it is mostly transparent with enterprise or cloud Internet connectivity, but on an oz-grade home dsl connection, many of those timeout after a couple minutes and a few error out straight away with an exception when starting from an empty cache (or using -nocache :) and I need to restart the build a few times to fetch everything (I observe the same behaviour building AspNet 6 or Nuget itself as well).

It took me 2 goes this time, I am still getting the ```C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(89,5): error : The package Microsoft.Win32.Registry with version 4.0.0-beta-23401 could not be found``` error for
- ```.\src\Compilers\CSharp\CscCore\CscCore.csproj```
- ```.\src\Compilers\VisualBasic\VbcCore\VbcCore.csproj```
- ```.\src\Interactive\CsiCore\CsiCore.csproj```
- ```.\src\Interactive\VbiCore\VbiCore.vbproj```

(on commit 986003a074fbb093d206f79b781473f837a164c9)

**Comment by codespare** [comment]
Well in fact, adding ```-DisableParallelProcessing``` and removing ```-NoCache``` to the ```nuget.exe restore``` calls in ```cibuild.cmd``` fixes my predicament.
I assume I was consistently getting an error specifically for the ```Microsoft.Win32.Registry``` package without that option because of my sluggish connection causing timeouts while restoring the large Microsoft.Net* packages that precedes it in alphabetical order.
0 error, 0 warning and 37 unit test suites succeeded so far. Thank you again for the clarifications.
Just before I forget, there is one typo left in ```./nuget.config```:
```xml
<add key="repositoryPath" value="../packages" />
```
should be:
``` xml
<add key="repositoryPath" value="./packages" />
```

**Comment by jasonmalinowski** [comment]
@yishaigalatzer, any chance this is already a known client or server issue for NuGet?

**Comment by yishaigalatzer** [comment]
You should use NuGet 3.2.1 from https://dist.nuget.org/index.html
