### ISSUE TITLE
Warning in VB console applications - 'Could not find ruleset file "ManagedMinimumRules.ruleset"'

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#12882]
**Version Used**: 
Classic VS ML 25602.00 
**Steps to Reproduce**:
1. Create a new VB console app.
2. Open Error list

**Expected Behavior**:
No warnings or errors
**Actual Behavior**:
One error in list. See picture below. Ruleset is present at C:\Program Files (x86)\Microsoft Visual Studio 15.0\Team Tools\Static Analysis Tools\Rule Sets
![image](https://cloud.githubusercontent.com/assets/10537189/17346335/fe586756-58be-11e6-872c-72b6c9643fc9.png)

**Comment by ManishJayaswal** [comment]
@srivatsn FYI

**Comment by srivatsn** [comment]
This is now fixed in the bcb2 branch and should flow into ml with the next integration.
