### ISSUE TITLE
Proposal: Plural Attribute Targets

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#12887]
In attribute-based programming (think MEF, EF, ASP.NET MVC, xUnit, etc) it is straightforward to use attributes to add metadata to members. It would be nice to be able to apply an attribute to a group of targets at once.

``` cs
[members: Attribute] // applicable to types
[methods: Attribute] // applicable to types
[properties: Attribute] // applicable to types
[events: Attribute] // applicable to types
[fields: Attribute] // applicable to types
[typevars: Attribute] // applicable to types
[params: Attribute] // applicable to methods
[types: Attribute] // applicable to assemblies
```

As a further consideration, regions can also be a good candidate to apply an attribute on.

``` cs
class Entity
{
  #region Required Properties
  [region: Required]

  public string FirstName { get; set; }
  public string LastName { get; set; }

  #endregion
}
```

Open Issues:
- In partial class/struct declarations, should we apply the attribute only to a single part?

**Comment by dsaf** [comment]
So effectively this language feature is to work around design of first-/third- party libraries? Because it seems that the current custom attributes can already achieve the desired outcome if used properly.

For example MSTest could be "improved" (it's subjective) to reduce the excessive configuration:

```csharp
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
public sealed class AllPublicMethodsAreTestsAttribute : Attribute { }
```

Event better, it could be the default behavior of existing ```[TestClass]``` attribute with an additional ```[NotATestMethod]``` to opt-out in rare cases.

In my opinion ```#region``` is an unnecessary language element:

* language-level feature just to improve IDE support
* facilitates large code files
* could have been implemented via a simple comment convention, e.g. ```//<region> .. //</region>```

Let's not double down on it. I would personally remove it from language retroactively.

**Comment by DavidArno** [comment]
Definitely with @dsaf with regard to `#region`'s. Just stop using them already; they are an antiquated IDE fudge that should have no place in modern, small classes. I have configured CodeMaid to automatically remove them from any file I go near.

As for the proposal, this could probably be handled via source generators. Something like:

````cs
[TestFixture]
[MultiAttributeApplication(Methd|Public, IgnoreAttribute = "NotTest")]
public class SomeTests
{
    public void TestMethod1() { ... }
    public void TestMethod2() { ... }

    [NotTest]
    public void TestMethod3() { ... }

   private void SomePrivateMethod() { ... }
}
````

could then be transformed via `context.AddCompilationUnit()` calls into:
````cs
[TestFixture]
[MultiAttributeApplication("Test", Methd|Public, IgnoreAttribute = "NotTest")]
public class SomeTests
{
    [Test]
    public void TestMethod1() { ... }
    [Test]
    public void TestMethod2() { ... }

    [NotTest]
    public void TestMethod3() { ... }

   private void SomePrivateMethod() { ... }
}
````

Not sure if `SomeTests` would need to be `partial` as there's no replacement going on.

**Comment by alrz** [comment]
@dsaf Regions, I think, was introduced in the language to address the convoluted nature of C# types i.e. a class declaration can contain all kinds of members, comparing to, for example, Rust structs that only contain fields; struct members and trait implementations must be declared separately.  Anyhow, any further discussion on this matter would be pointless since that ship has sailed long time ago. I mentioned them as an existing mechanism to group class members, that's it.

@DavidArno Code generators do not "transform" code, as the name suggests, `AddCompilationUnit` adds a compilation unit, so you will need to generate a partial class and replace every member with *different attributes.* AFAIK that wouldn't be possible as currently proposed (which I think it should be). If you don't mind double invocation of replaced members, it is actually a plausible alternative option.

**Comment by svick** [comment]
As a comparison, PostSharp has something like this, calling it [attribute multicasting](http://www.postsharp.net/blog/post/multicasting-of-custom-attributes). The way it works there is that the attribute class has to inherit from `MulticastAttribute` and have `[MulticastAttributeUsage]`. When you then apply that attribute for example on a class, PostSharp understands that it should apply to all its members.

Not sure what that means for this proposal: on one hand, it shows demand for such feature, on the other, it shows that something similar can be implemented without language support.

**Comment by alrz** [comment]
@svick If you are considering assembly weaving as a viable option, a lot of other features can be implemented "without language support". I think the reason that this feature is demanding is because it doesn't always make sense for libraries to provide such attributes (like data annotations), and from consumer point of view, you can not alter such libraries to fit your needs unless they accept PRs. So at best you will need to write your own. by the way, C# supports "attribute multicasting" on fields of a common type which doesn't always come in handy because it demands a different code convention.

**Comment by svick** [comment]
@alrz `MulticastAttribute` itself does not use assembly weaving (as far as I know). What PostSharp does is that when it needs to know whether a member has an attribute applied (so that it can do assembly weaving), it also looks at its containing type for `MulticastAttribute`s, etc.

Every library that uses attribute-based programming could do that too, no weaving required. But yes, this approach means the library has to support it (by declaring its attributes with support for multicasting and then keeping multicasting in mind when reading the attributes).

**Comment by alrz** [comment]
@svick As you said, the problem with `MulticastAttribute` base class is that it must be inherited to be used i.e. it's not pluggable. In @DavidArno's example, you wouldn't be able to pass arguments to the target attribute, not at least type-safely. I think something like "nested attributes" (a la Java), among other use cases, would also help here, assuming that's possible with code generators.

```cs
[AttributeUsage(...)]
class MulticastAttribute(MulticastTargets targets, params Attribute[] attributes) : Attribute;

[Multicast(MulticastTargets.Methods, FooAttribute(1, 2, 3), BarAttribute(typeof(Baz))]
class C {}
```
This seems like a whole different proposal though. I'm not sure if it needs CLR support.

**Comment by DavidArno** [comment]
@alrz,

Ah, sounds like I'm being naive over what "compilation unit" means. I took it to mean "add a sub-thing to a thing". eg add an attribute to a method, or a method to class etc. Guess it doesn't mean that at all...

**Comment by alrz** [comment]
As mentioned, essentially a problem with specific third-party libraries and probably solvable by generators.
