### ISSUE TITLE
Committing override using parenthesis results in invalid code

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#12892]
**Version Used**: 15.0.25428.1/2.0.0.60620

**Steps to Reproduce**:

![untitled](https://cloud.githubusercontent.com/assets/10546952/17373267/599bca0a-599f-11e6-90e4-359cc4c68d0e.png)

Commit the autocomplete by pressing `(`

**Expected Behavior**:
```C#
public override string ToString()
{
    return base.ToString();|
}
```
**Actual Behavior**:
```C#
public override string ToString()
{
    return base.ToString();|
}(
```
Note the parenthesis at the end. I believe this is regression from previous preview builds.

**Comment by Pilchie** [comment]
@CyrusNajmabadi or @rchande this is likely related to the change to how we apply commits, but I thought we had tests for it to prevent this.

**Comment by CyrusNajmabadi** [comment]
We do have tests for this, and this is something i fixed during the fixes i did after the completion refactoring work.  I've verified this locally, and the above situation no longer arises.
