### ISSUE TITLE
[Master] No longer builds.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#12895]
**Version Used**: 
[Master](https://github.com/dotnet/roslyn/commit/e19244dde42d2b280e0d41ea2de857215df99153)

**Steps to Reproduce**:

1. ` msbuild /v:m /m BuildAndTest.proj`

**Expected Behavior**:
No Errors
**Actual Behavior**:
[Build Errrors](https://gist.github.com/AdamSpeight2008/e184f7930ea1d68fd07a7dcd69a02c1b)

**Comment by jmarolf** [comment]
looks like you need to run `Restore.cmd`

**Comment by AdamSpeight2008** [comment]
@jmarolf It seems a bit flaky at times, as I did do that first and it didn't build. I even used `/clean` and it still wouldn't build. Now it works.

**Comment by AdamSpeight2008** [comment]
Could be related to having some build and compiler process still being around. #12903

**Comment by jmarolf** [comment]
In general I would do the following to get back to a good state:
```
taskkill /im vbcscompiler.exe /f
taskkill /im msbuild.exe /f
git clean -xdf
restore.cmd
msbuild /m /v:m /nodereuse:false BuildAndTest.proj
```
