### ISSUE TITLE
Grey out ToString() calls in a razor render action

### ISSUE THREAD

**Issue by Vannevelj** [dotnet/roslyn#12893]
**Version Used**: 

Visual Studio 2015 Update 3

**Steps to Reproduce**:
1. Create new ASP.NET project
2. Add a Razor view
3. Add a call to `<something>.ToString()` in the form of `<h2>@Something.ToString()</h2>`

**Expected Behavior**:

`ToString()` is greyed out.

**Actual Behavior**:

`ToString()` is not greyed out.

**Justification**:
Every call like that already calls `ToString()` automatically because it is used to render output.

**Comment by miloush** [comment]
If there is an extensibility point in the compiler that would allow special project types to add/remove simplification fixes, then this should be filed at aspnet/Razor.

If there is not, I guess it won't be easy to make this for Razor only. Then the issue would either be "add such extensibility point", or add simplification fix for `string.ToString()` but that wouldn't have the effect you are looking for.

Finally, I am not sure how Razor works, but if it is boxing `Something` then including/excluding `.ToString()` would make a difference if `Something` had a `ToString()` method that hides the `object.ToString()` one  - which I agree is not a common scenario, but the greying out would kind of rely on an implementation detail.

Is your concern readability or performance? I would expect that `string.ToString()` gets optimized out.

**Comment by miloush** [comment]
Actually, Razor is probably not just appending `.ToString()`, because I expect that it renders nothing when `Something` is `null`. Including `.ToString()` in the markup throws `NullReferenceException` if `Something` is `null` and as such should not be greyed out.

**Comment by Pilchie** [comment]
Added to the backlog to think more about when we focus on razor scenarios.

**Comment by CyrusNajmabadi** [comment]
This can be done with a DiagnosticAnalzyer now.  Razor will be able to add such an analyzer if they want.  They just need to add the appropriate `WellKnownDiagnosticTags.Unnecessary` to their diagnostic and the IDE will fade this out.  Please reopen with Razor if you'd like them to do this.
