### ISSUE TITLE
Add Analyzer shouldn't be intermixed with other Runtime Reference menu items

### ISSUE THREAD

**Issue by SteveLasker** [dotnet/roslyn#1289]
When clicking on the Reference Node, the Add Analyzer... menu comes up.
From my understanding, Analyzer is a debugging, development concept, that received feedback it should be in the references folder, vs. a special folder.
However, it's currently intermixed with other Runtime scenarios, like binary, project references and the older Service References, and newer Connected Services menu items.
![analyzerinreferences](https://cloud.githubusercontent.com/assets/7647382/6670554/7eb94582-cbbc-11e4-93ad-c37fdd677cd9.png)
![analyzerinprojectmenu](https://cloud.githubusercontent.com/assets/7647382/6670556/85fe9b94-cbbc-11e4-8ff5-31d414a462e1.png)

Suggest the following.
Name the Item: Add Analyzer Reference...
Move the item below Add Connected Service in both the References and Project menu.
(Note, we have a current bug to move Add Connected Service below Add Service Reference)
http://vstfdevdiv:8080/web/wi.aspx?pcguid=22f9acc9-569a-41ff-b6ac-fac1b6370209&id=1139084
Project - Add Connected Service should be grouped with the other Service menu items

**Comment by natidea** [comment]
Menu has been relocated. Menu name is still "Add Analyzer" not "Add Analyzer Reference"
