### ISSUE TITLE
Make sure that the new language features work in Expression lambdas or give errors.

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#12900]
Most of the new language features do not align well with the set of expression tree nodes available in ET v1.0 that we are targeting.

In fact they would benefit from being represented by higher level reducible nodes as a more expressive form - I.E. instead of a bunch of lowered nested field accesses we could have tuple field accesses directly encoded in the tree as TupleFieldAccess expressions or something like that. 
The nodes would still be compilable by the ET compiler as long as they know how to reduce themselves to the ET2.0 representation, which would be regular nested field accesses.

In the short term we must ensure that new features in the context of expression trees have desirable behavior. (most likely an error for now)

**Comment by jcouv** [comment]
Moved to RC since introducing this will introduce expected compilation errors.

**Comment by gafter** [comment]
I'm working on this (for all new language features) now.
