### ISSUE TITLE
Suggestion for restore.cmd

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#12903]
**Change the verbosity**
from `-verbosity quiet` to `-verbosity normal`. So the it doesn't appear the restore has locked up.

**Kill compiler, build, test runners**
Add additional cmd to kill the compiler and test runner, as the can hang around and interfere with the restore. 

```
taskkill /IM MSBuild.exe /F
taskkill /IM VBCSCompiler.exe /F
taskkill /IM xunit.console.x86.exe /F
taskkill /IM RunTests.exe /F
```

**Comment by Pilchie** [comment]
Tagging @jaredpar

**Comment by jaredpar** [comment]
I can see the logic in adding a task kill for VBCSCompiler.  Doing so is 100% safe and it can hold onto packages by virtue of being run from them.

Killing the other processes though is decidedly not safe.  It can, and will, disrupt other operations on the machine.

**Comment by AdamSpeight2008** [comment]
>@jaredpar **wrote:** Killing the other processes though is decidedly not safe. It can, and will, disrupt other operations on the machine.

Hence I named it the `/nuke` option.

**Comment by jaredpar** [comment]
The only valid name for this option would be to explicitly convey that it is randomly breaking things on the machine.  That is functionally what it is doing.  Hence why we can't accept it.

**Comment by AdamSpeight2008** [comment]
When you've potentially have this many hanging round, during a single build and test. (of Roslyn)
![buildandtest](https://cloud.githubusercontent.com/assets/900107/17412926/2621a6a8-5a77-11e6-954d-5297ad0eee91.png)

It sometimes makes sense to kill them all, before proceeding.

**Comment by jmarolf** [comment]
@AdamSpeight2008 You shouldn't need to kill these unless test run is currently happening
```
taskkill /IM xunit.console.x86.exe /F
taskkill /IM RunTests.exe /F
```

Are these processes hanging around after test runs?

This is never safe as it will kill other builds
```
taskkill /IM MSBuild.exe /F
```

You should be using `/nodereuse:false` so msbuild instances created as part of building roslyn exit as soon as the build is complete

**Comment by AdamSpeight2008** [comment]
@jmarolf Shouldn't that be included in the build instructions?

**Comment by jmarolf** [comment]
@AdamSpeight2008 good point, done: https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md

**Comment by jasonmalinowski** [comment]
How was this breaking restore? If we have to require /nr:false for a normal operation like that, something seems really fishy.

**Comment by AdamSpeight2008** [comment]
@Pilchie 
Say if make a change to the code, and run the build command. and it uses an handle. Then causes error windows to be thrown. And abort the test run, there is likely hood that the handles are still be held on to.
So when I correct the problem and the rerun the test, I could get is being used error / warnings.
