### ISSUE TITLE
In deconstruction declaration `var (x, y, z) = e;`, we bind `var` three times.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#12905]

**Comment by gafter** [comment]
Also possibly an issue in the deconstruction variant of `foreach`.

**Comment by jcouv** [comment]
I think you've fixed this already ;-)
In [BindDeconstructionVariables](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Binder/Binder_Deconstruct.cs,2e622f48635e3de0), in the `DeclarationExpression` case, we bind the type once and use it for each designation (when the designation is a `ParenthesizedVariableDesignation`).

This same code path is also used for binding the deconstruction variant of `foreach`.
