### ISSUE TITLE
VB SemanticModel.GetEnclosingSymbol doesn't work correctly with lambda parameters/headers

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#1290]
Consider code

```VB
Imports System
Class C
    Sub F()
        Dim f1 = New Func(Of Integer, Integer, Integer)(
            Function(a1, a2)
                Return a1
            End Function)
    End Sub
End Class
```

SemanticModel.GetEnclosingSymbol(span start of ParameterSyntax "a1" )
returns Sub F. It should return the declaring lambda (C# does).

**Comment by tmat** [comment]
SemanticModel.GetEnclosingSymbol(span start of LambdaHeaderSyntax "Function(a1,a2)" ) also doesn't return the lambda.

**Comment by tmat** [comment]
Please consider this P1 - this is blocking lambda EnC for RC.

**Comment by gafter** [comment]
It is a bit scary that I find only about three tests for this API.

**Comment by tmat** [comment]
Yeah. BTW, I will need it to work for query lambdas as well. I don't have the EnC test cases yet, working on them.

**Comment by gafter** [comment]
I don't think the query lambdas will work, as there is no "enclosing symbol" in the program other than the enclosing method.

**Comment by tmat** [comment]
The bound query lambda isn't available?

**Comment by tmat** [comment]
I'll double check if I really need them.

**Comment by tmat** [comment]
I need to validate that the signatures of the bound query lambdas didn't change. I guess I could validate if all expressions in all clauses of the query have the same type and all AsClauses changed. But that's work that I'd like to avoid if possible.

**Comment by gafter** [comment]
These are not lambda expressions in the source, and are not modeled as lambda expressions in the semantic model.

**Comment by tmat** [comment]
OK. I'll special case them then.

**Comment by gafter** [comment]
@tmat This may be different between VB and C# due to differences between the languages.

**Comment by gafter** [comment]
@tmat Shouldn't SemanticModel.GetEnclosingSymbol(span start of ParameterSyntax "a1" ) return the parameter symbol, since that is the symbol it is part of the declaration of?

**Comment by tmat** [comment]
That would make sense as well.

**Comment by gafter** [comment]
Somewhat bad news.

The lambda's "begin" and "end" statements are not considered to be "inside of" the lambda for the purposes of this API. I spent the last three days trying to make it be treated as if inside, and it would require some significant reorganization of a lot of code, both within and outside the compilers, where lots of code depends on the current behavior.

I don't think it is feasible to change this in the next few weeks.

**Comment by tmat** [comment]
So if the lambda is empty 
```VB
Sub(a)
End Sub
```
then we are not able to get the symbol at all?

**Comment by gafter** [comment]
If there are any spaces between the `)` and the `End` then you can get it from those spaces.

**Comment by gafter** [comment]
You might be able to get it from the API that gives you the symbol for an expression node.

**Comment by gafter** [comment]
You should also be able to get it by asking for the "declared symbol" of the enclosing lambda syntax node.

**Comment by gafter** [comment]
@AlekseyTs Can you please "Verify" that this is the intended behavior?

**Comment by gafter** [comment]
@AnthonyDGreen Can you please "Verify" that this is the intended behavior?

**Comment by AnthonyDGreen** [comment]
The API was designed to fit the IDEs needs specifically. It was never rationalized as general purpose. We discussed it at length in the design meeting but were unable to come up with a general design that would still meet the IDE needs or even a definition for what "Enclosing" means in this context. It's unfortunate but it's a wart we'll need to live with as is.
