### ISSUE TITLE
PCL does not support targeting .NETStandard 1.6

### ISSUE THREAD

**Issue by ericstj** [dotnet/roslyn#12918]
**Version Used**: 
VS 2015 Update 3

**Steps to Reproduce**:
1. Create a new PCL
2. Target netstandard1.6
3. Build

**Expected Behavior**:
Build succeeds without error

**Actual Behavior**:
Build fails with

| Severity | Code | Description | Project | File | Line | Suppression State |
| --- | --- | --- | --- | --- | --- | --- |
| Error |  | Your project is not referencing the ".NETPlatform,Version=v5.0" framework. Add a reference to ".NETPlatform,Version=v5.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. | ClassLibrary3 | C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets | 140 |  |

As @akoeplinger pointed out here https://github.com/dotnet/corefx/issues/10213#issuecomment-235049724 this is due to missing entries in `C:\Program Files (x86)\MSBuild\Microsoft\Portable\v5.0\Microsoft.Portable.Common.targets`.

Not sure if roslyn is the right repo for PCL bugs but its the only one I'm aware of that is tracked by the folks that own this component.

**Comment by Pilchie** [comment]
We'll need to figure out what the plan is here for VS "15" PCLs versus .NET Core Class Libraries. In the meantime, there is a workaround of explicitly specifying something in your .csproj.

**Comment by prochan2** [comment]
@Pilchie, how do I "explicitly specify something" in my .csproj? Could you please explain what you mean? I'm trying to build a class library for .NET Core using MSBuild and making a PCL targeting netstandard1.6 seems a good way to me. Or is there a better way?

**Comment by Pilchie** [comment]
@prochan2 Try adding `<NuGetTargetMoniker>.NETStandard,Version=v1.6</NuGetTargetMoniker>` to the `<PropertyGroup>` at the top of your .csproj file.

**Comment by ericstj** [comment]
You need to do it after the last import statement since PCL overwrites the value of this property.

**Comment by prochan2** [comment]
It works, thanks @Pilchie  & @ericstj!

**Comment by dls314** [comment]
This seems related to https://github.com/aspnet/Tooling/issues/749 but I could be crazy.

**Comment by sickboy** [comment]
The workaround doesn't seem to work from me when running from a TFS (xaml) build. Neither does updating the the `Microsoft.Portable.Common.targets`.

**Comment by wbuchwalter** [comment]
Same thing as @sickboy . Building through VS 2015 works perfectly, but using MSBuild fails.

**Comment by Pilchie** [comment]
You added something here for RC, right?

**Comment by rchande** [comment]
Fixed in RC2.

**Comment by markmnl** [comment]
I have this issue today in VS 2015 Update 3 with a PCL targetting .NETStandard1.6

I tried the workaround but no difference, I do not understand @ericstj  "You need to do it after the last import statement since PCL overwrites the value of this property." becuase all my PropertyGroup elements are way above my one and only Import element - which is near the bottom.

**Comment by markmnl** [comment]
OK I moved my bottom Import element to above PropertyGroup, now when VS reloads project it is unavailable and I get a context menu option on right-click to install update.. doing that now..

(This versioning of .NET Core, PCL's and UWP is a really pain the arse no doubt hurting any uptake of this new tech).

**Comment by markmnl** [comment]
Installer says nothing new to install.. Screw it im just going to add common files as link instead try use library.

**Comment by ryanlederman** [comment]
I added

`<PropertyGroup>
    <NuGetTargetMoniker>.NETStandard,Version=v1.6</NuGetTargetMoniker>
  </PropertyGroup>`

at the end of my csproj, before the </Project> and after the comment about adding tasks, w/ VS2015.3 and targeting netstandard1.6. It finally compiled for me w/ VS.

**Comment by robcthegeek** [comment]
Just lost 20+ mins having this exact same issue. @ryanlederman's [comment](https://github.com/dotnet/roslyn/issues/12918#issuecomment-263938253) gave _exactly_ what was needed to resolve. Thanks!

**Comment by godrose** [comment]
The build is successful but I got lots of warnings. Should they just be ignored?
Package Microsoft.NETCore.Portable.Compatibility 1.0.1 is not compatible with dotnet (.NETPlatform,Version=v5.0). Package Microsoft.NETCore.Portable.Compatibility 1.0.1 supports:
  - net45 (.NETFramework,Version=v4.5)
  - netcore50 (.NETCore,Version=v5.0)
  - netstandard1.0 (.NETStandard,Version=v1.0)
  - win8 (Windows,Version=v8.0)
  - wp8 (WindowsPhone,Version=v8.0)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
Package NUnit 3.6.1 is not compatible with dotnet (.NETPlatform,Version=v5.0). Package NUnit 3.6.1 supports:
  - monoandroid (MonoAndroid,Version=v0.0)
  - net20 (.NETFramework,Version=v2.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - netstandard1.6 (.NETStandard,Version=v1.6)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
One or more projects are incompatible with .NETPlatform,Version=v5.0.
One or more packages are incompatible with .NETPlatform,Version=v5.0.
