### ISSUE TITLE
Checksum computation over stream wraps IOExceptions in TargetInvocationException

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn#12926]
The fact that the hashing is done via reflection light-up is leaking to callers of the API. TargetInvocationExceptions should be unwrapped.

**Version Used**: Synced to latest master

**Steps to Reproduce**:
* Pass a stream that will throw IOException on read to SourceText.From

**Expected Behavior**:
The IOException is propagated out of SourceText.From.

**Actual Behavior**:
A TargetInvocationException wraps the IOException.

**Comment by jaredpar** [comment]
@agocke please close out once we move over to Net Standard.
