### ISSUE TITLE
Missing bound node for out variable declaration

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#12940]
We have a design invariant for the bound nodes that the initial bound tree is roughly isomorphic to the shape of the syntax. We create and retain bound nodes even when they do not represent runtime operations, e.g. local variable declarations.

The out variable declaration is not retained in the initial bound trees. It should be. This would slightly simplify the handling of the diagnostic reporting it being unsupported in expression trees, for example, and would simplify the handling of some error cases in flow analysis. It is necessary for region analysis to compute the "declared inside" property.

**Comment by gafter** [comment]
Related to this, `VariableDeclaredWalker` currently checks the underlying syntax due to the absence of this bound node. That design flaw can be fixed when the bound node for the declaration is created.

**Comment by AlekseyTs** [comment]
The current design is an explicit choice and it doesn’t violate any invariants or requirements. At the moment, there are only two components in the compiler that care about declarations: SemanticModel and Region Analysis. The rest of the compiler and the entire compilation pipeline will not benefit from the introduction of a new bound node. The new node will not come for free, many places in the compiler that currently deal with fields and locals will have to be adjusted to deal with the new node and the new behavior will have to be tested as well. I am convinced that the current implementation uses the right cost/benefit balance and trade-offs, both short and long term.

**Comment by gafter** [comment]
@AlekseyTs 
> The current design is an explicit choice and it doesn’t violate any invariants or requirements.

I reviewed my understanding @mattwar, one of the original members of the Roslyn team, and he confirmed my recollection that it is, in fact, an invariant of the design of the bound trees that they are to be roughly isomorphic in shape with the syntax, and are to retain any semantically significant information. We both feel that these invariants are important and useful, so we should be consulted before committing to an approach that relaxes them.

This has been documented for years in the internal OneNote "Roslyn Team Notebook - New" section "Compiler Design" on a page entitled "Invariants of the BoundTrees". I hope to make those design notes public for the benefit of external contributors.

In any case, the pending PR #15646 restores this invariant for out variable declarations. Contrary to your assertion, I did not find that "many places in the compiler that currently deal with fields and locals will have to be adjusted to deal with the new node".

**Comment by AlekseyTs** [comment]
@gafter 

> Contrary to your assertion, I did not find that "many places in the compiler that currently deal with fields and locals will have to be adjusted to deal with the new node".

This is not a surprise. The assertion was regarding an introduction of a new kind of bound node vs. reusing existing bound nodes, PR #15646 doesn't introduce a new kind of bound nodes, it just adds a boolean flag to an existing BoundLocal node. If doing that resolves this issue to your satisfaction, I have no objections.
