### ISSUE TITLE
Implement-interface refactoring incorrectly introduces tuples attribute

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#12949]
![image](https://cloud.githubusercontent.com/assets/12466233/17445258/e2bee97a-5af8-11e6-8434-ff67e9807e24.png)

FYI for @agocke @VSadov

**Comment by agocke** [comment]
Huh. That's interesting.

**Comment by jcouv** [comment]
I have a fix and test for this scenario with a tuple with names in a method coming from metadata.

I also tested on a property, but the problem didn't exist (although `ImplementInterfaceCodeAction.GenerateProperty` has similar logic to `ImplementInterfaceCodeAction.GenerateMethod` to remove a `ComAliasName` attribute). 

@CyrusNajmabadi It seems that the implement-interface logic carries attribute from the interface implemented when they are placed on methods, but I did not observe that behavior on properties. 
Do you want to take a quick look, or should I file an issue?

**Comment by CyrusNajmabadi** [comment]
Feel free to file an issue.  I imagine it's just an oversight.

**Comment by jcouv** [comment]
Fixed with #13035
