### ISSUE TITLE
Unloading project takes very long time (minutes)

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#1294]

**Comment by tmat** [comment]
ETL trace: %internal_share%\public\tomat\Bugs\1294

**Comment by Pilchie** [comment]
Can you take a look and see if this is related to recent work?

**Comment by rchande** [comment]
Can you verify, @tmat ? Note that project unload isn't instantaneous, but shouldn't be nearly as bad as what you were seeing.

**Comment by rchande** [comment]
Reactivating pending porting to preview branch.

**Comment by MattGertz** [comment]
Approved for next preview.

**Comment by rchande** [comment]
@tmat , can you verify this now?

**Comment by Pilchie** [comment]
Since this is merged, re-closing.
