### ISSUE TITLE
VB Tuples: name match/mismatch rules similar

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#12964]
- dominant type computation among multiple candidates differing only in names (include casing?)
   not sure if all "dominant type computations" are unified. may need to happen in several places
   see ternary operators, method type inference, lambdas with multiple returns, array literals inference...
- OHI 
  when override does not match a base only in tuple names give diagnostics. Warning - in VB spirit of naming permissiveness.
  implementing methods may not need to match. Confirm with LDM
- losing tuple literal names in assignments - same warning as in C#, but case insensitive.

**Comment by jcouv** [comment]
I think this was already done. See https://github.com/dotnet/roslyn/pull/14486

**Comment by jcouv** [comment]
Add test case for array literals inference.
