### ISSUE TITLE
VB Tuples: Case Insensitivity

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#12960]
- tuple symbol equality should be case insensitive  (should be the case already, needs more testing)
- (A as integer, a As Integer)      should fail due to duplicate element names
- x.Foo and x.foo    should equally work      (do we handle the case where both are present - C# tuple)
- restictions on ItemX and disallowed member names should be case-insensitive
- OHI should be case insensitive,             (do we emit signature in same casing as in the base?)

**Comment by jcouv** [comment]
The OHI scenario will be covered in the OHI work.
