### ISSUE TITLE
[VB] De-Restricted Operators

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#12971]
## VB Proposal: De-Restricted Operators.

Proposal to remove the restriction on some operators to be defined in compliment pairs.
[Link To Proposal](https://github.com/AdamSpeight2008/Ideas/blob/master/Derestricted%20Operators.md)

**Example**

``` vb
Public Shared Operator <( x As Foo, y As Foo ) As Boolean
End Operator
'' The compliment operator =>( x As Foo, y As Foo ) As Boolean not defined.
```

**Addition**
I think that the unary complement operators `IsTrue` and `IsFalse` should remain as is.

**Comment by orthoxerox** [comment]
What would you need this for?

**Comment by AdamSpeight2008** [comment]
It frees the implementer from the shackles, that `<` `<=` `=` `<>` `>=` `>` are comparison operators. Allow them to give the other meanings. Should they actual mean comparison the their implementation then are  likely to do the compliments any ways.

**Comment by AdamSpeight2008** [comment]
Another approach could be to change the `error` into a warning.

**Comment by AdamSpeight2008** [comment]
[Ported to VBLang](https://github.com/dotnet/vblang/issues/26)
