### ISSUE TITLE
Enable integration testing on Willow installs

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#12972]
We need to update our integration test support to support the new Visual Studio "15" installer.

**Comment by panopticoncentral** [comment]
Not sure if this was completed since there was other work that needed to be done to unblock.

**Comment by jasonmalinowski** [comment]
@tmeschter: I'll leave this up to you to decide if it's OK to close or not. (This is just a tracking bug.)

**Comment by jasonmalinowski** [comment]
This is complete. yay!
