### ISSUE TITLE
Crash in method separators when opening UnboundLambda.cs

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#1297]
It appears that opening UnboundLambda.cs in the Roslyn solution crashes VS.
Disabling method separator lines makes the crash disappear.

I think the reason is NRE with stack like the following -

======================================

System.NullReferenceException occurred
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.CodeAnalysis.CSharp.EditorFeatures
  StackTrace:
       at Microsoft.CodeAnalysis.Editor.CSharp.LineSeparator.CSharpLineSeparatorService.IsBadProperty(SyntaxNode node)
  InnerException: 

>	Microsoft.CodeAnalysis.CSharp.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.CSharp.LineSeparator.CSharpLineSeparatorService.IsBadProperty(Microsoft.CodeAnalysis.SyntaxNode node) Line 152	C#
 	Microsoft.CodeAnalysis.CSharp.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.CSharp.LineSeparator.CSharpLineSeparatorService.IsBadNode(Microsoft.CodeAnalysis.SyntaxNode node) Line 279	C#
 	Microsoft.CodeAnalysis.CSharp.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.CSharp.LineSeparator.CSharpLineSeparatorService.ProcessNodeList<Microsoft.CodeAnalysis.CSharp.Syntax.MemberDeclarationSyntax>(Microsoft.CodeAnalysis.SyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.MemberDeclarationSyntax> children, System.Collections.Generic.List<Microsoft.CodeAnalysis.Text.TextSpan> spans, System.Threading.CancellationToken cancellationToken) Line 327	C#
 	Microsoft.CodeAnalysis.CSharp.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.CSharp.LineSeparator.CSharpLineSeparatorService.GetLineSeparatorsAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Threading.CancellationToken cancellationToken) Line 46	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.LineSeparators.LineSeparatorTaggerProvider.TagProducer.ProduceTagsAsync(Microsoft.CodeAnalysis.Document document, Microsoft.VisualStudio.Text.SnapshotSpan snapshotSpan, int? caretPosition, System.Threading.CancellationToken cancellationToken) Line 48	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Shared.Tagging.AbstractSingleDocumentTagProducer<Microsoft.CodeAnalysis.Editor.Implementation.LineSeparators.LineSeparatorTag>.ProduceTagsAsync(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan> snapshotSpans, Microsoft.VisualStudio.Text.SnapshotPoint? caretPosition, System.Threading.CancellationToken cancellationToken) Line 45	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource<Microsoft.CodeAnalysis.Editor.Implementation.LineSeparators.LineSeparatorTag>.RecomputeTagsAsync(Microsoft.VisualStudio.Text.SnapshotPoint? caretPosition, Microsoft.CodeAnalysis.Text.TextChangeRange? textChangeRange, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan> spansToCompute, System.Threading.CancellationToken cancellationToken) Line 573	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource<System.__Canon>.RecomputeTagsForeground.AnonymousMethod__0(System.Threading.CancellationToken ct) Line 408	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Shared.Threading.AsynchronousSerialWorkQueue.EnqueueBackgroundTask.AnonymousMethod__0(System.Threading.Tasks.Task _) Line 130	C#
 	mscorlib.dll!System.Threading.Tasks.ContinuationResultTaskFromTask<System.Threading.Tasks.Task>.InnerInvoke() Line 111	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2497	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Line 2860	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2826	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2755	C#
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() Line 2703	C#
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820	C#
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Line 1161	C#

**Comment by Pilchie** [comment]
Can you verify this?
