### ISSUE TITLE
There's no indication that Fuzzy Add Using will change the type name

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#12985]
**Version Used**: 14.0.25421.03 Update 3

![image](https://cloud.githubusercontent.com/assets/235241/17465681/8a625750-5cb3-11e6-9f86-a509dfa9c703.png)

Should there be some indication on the Add Using options that it's going to change my type name? Seems deceiving as-is.

**Comment by dpoeschl** [comment]
Also, it's unfortunate that pressing `down` doesn't switch it to the Add Using option. I hadn't even noticed the sub-menu because I'm just trying to pick the top-level thing I want, so I pressed `down enter` instinctively, which generates the type instead of adding the using.

**Comment by dpoeschl** [comment]
**Oh, it's because `FileIO` isn't a thing and it's offering `File`.** We don't show anything next to "using System.IO" to let you know that it's going to change the type name?

**Comment by miloush** [comment]
👍  
I have already been deceived by this Add Using (And Secretly Change Type)!
(And I believe I also accidentally generated types instead as @dpoeschl noted)

**Comment by CyrusNajmabadi** [comment]
Definitely not a good experience.  I'll work on improving this.

**Comment by CyrusNajmabadi** [comment]
Here's what i've come up with:

![image](https://cloud.githubusercontent.com/assets/4564579/17538373/a175a512-5e72-11e6-8b5d-bceed66ca453.png)

**Comment by miloush** [comment]
That's definitely an improvement! 👍 

I would probably prefer different wording, something more consistent with the _Encapsulate field_ for example:
```
using System.IO; (File)
using static System.Net.WebRequestMethods; (File)
using System.IO; (FileInfo)
```
likely with no parentheses if the type remains the same. Or, if you want to have the type name first, then
```
File (and add using System.IO;)
File (and add using static System.Net.WebRequestMethods;)
FileInfo (and add using Systme.IO;)
```
But I would expect the main action/verb to be first and consequences to follow, although the 'main action' could be argued both ways here I guess, and I also think that using `-` is rather uncommon at this place.

**Comment by CyrusNajmabadi** [comment]
I prefer the "File - using" vs "using - (File)" because the thing that will change that is most close to your cursor is earlier in the text.  i.e. "we're changing FileIO to File, and to make File bind, we're also adding a 'using'".  That's how i read it at least.

**Comment by miloush** [comment]
Yep, I guess it depends on what intentions you had when you brought up the quick fix.

**Comment by CyrusNajmabadi** [comment]
I also like having "File" earlier because it makes it clearer that it's something very different than just adidng a using to resolve your name.  It's *changing* your code becuase we think you mistyped something.  If that's not what you were expecting, i want you to see that right away.
