### ISSUE TITLE
VB.NET Intellisense (auto complete) broken

### ISSUE THREAD

**Issue by Chris5gd** [dotnet/roslyn#12981]
**Version Used**: VS2015 Enterprise Update 3 

**Steps to Reproduce**:

Just type code! Various autocomplete options are simply wrong, based on the type of object that must follow.

Screenshots showing the behaviour (and compared with VS2013 attached.

**Expected Behavior**: Autocomplete should show correct available options

**Actual Behavior**: Autocomplete shows completely wrong options.

The following screenshots illustrate the VS2013 (correct) and VS2015 (incorrect) behaviour:

![vs2015-autocompleteboolean](https://cloud.githubusercontent.com/assets/20885630/17461808/b0d390ac-5c90-11e6-9185-61d0d0005820.png)
![vs2013-autocompleteboolean](https://cloud.githubusercontent.com/assets/20885630/17461809/baa737be-5c90-11e6-9688-74e881dfd5e7.png)
![vs2015-autocompleteforselectedmethodoverload](https://cloud.githubusercontent.com/assets/20885630/17461810/be1ed9b0-5c90-11e6-8e4b-4c929a760ac5.png)
![vs2013-autocompleteforselectedmethodoverload](https://cloud.githubusercontent.com/assets/20885630/17461812/c33ae2cc-5c90-11e6-822d-1900537aef0e.png)

**Comment by Pilchie** [comment]
Hi,

For the first issue - we no longer support the "Common/All" tabs in completion, but you should see similar behavior when typing - if you actually type `T` or `F`, we would preselect to `True` or `False` for example.  See https://github.com/dotnet/roslyn/issues/4892 for more details.

For the second issue - we unfortunately don't tie what items should be preferred to the currently selected overload in parameter help, but we'd like to fix that at some point.  See https://github.com/dotnet/roslyn/issues/7898 for more details.
