### ISSUE TITLE
Improper IDE colorization of collection classes with Add extension methods 

### ISSUE THREAD

**Issue by TKharaishvili** [dotnet/roslyn#12983]
I'm using VS community 2015 update 3 and C# 6

With the following declaration of an `Add` extension method:

```C#
public static class ExtensionMethods
{
    public static void Add(this List<string> list, int element)
    {
        list.Add(element.ToString());
    }
}
```

and the following collection initializer:

```C#
var list = new List<string> { 1, 2, 3 };
```

The `List` part of the collection initializer doesn't get colorized properly. (It's white instead of standard greenish color for classes).
I checked for the dictionaries and got the same tiny visual glitch.

**P.S.**
This may already be fixed by now and just not shipped in the current version of VS, I'm creating an issue because I was not able to find an existing one mentioning it.

**Comment by CyrusNajmabadi** [comment]
Assigning to compiler.  Inside of https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Classification/Classifiers/NameSyntaxClassifier.cs

We call: ```var symbolInfo = semanticModel.GetSymbolInfo(name, cancellationToken);```

Passing in the node for ```List<string>```.  We get a SymbolInfo with no symbol and no candidate symbols.  

This code is valid and should return the appropriate generic symbol for this node.  Note: if no initializer arguments are present (i.e. ```new List<string> { }```) then the right symbol is returned from the compiler.  I do not believe the presence of initializer arguments should affect things here.

**Comment by Pilchie** [comment]
In my investigation it also worked if the Add method was an instance method, it just failed when it was an extension method.
