### ISSUE TITLE
Simplify Type Name on statics of derived types sometimes seems overly pedantic

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#12987]
**Version Used**: 14.0.25421.03 Update 3

![image](https://cloud.githubusercontent.com/assets/235241/17466079/8140e68e-5cbb-11e6-963a-0692a78cb15b.png)

Is this intentional? The `Ellipse.` version is arguably more readable, since I'm dealing in Ellipses in the surrounding code. And I wouldn't want to turn off Simplify Type Name in its entirety to get around this.

**Comment by Pilchie** [comment]
Related/dupe of #11820 and/or #11821

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
