### ISSUE TITLE
Improved syntax for double-checked locking

### ISSUE THREAD

**Issue by matwilko** [dotnet/roslyn#130]
# Problem
A fairly common occurrence when working with locks is to use double-checked locking to avoid acquiring the lock when it won't be necessary. However implementing this requires both a duplication of the condition and requiring statements inside the lock to be indented by three levels:

    if (condition)
    {
        lock(lockObj)
        {
            if (condition)
            {
                // statements
            }
        }
    }

Even if we eliminate the brackets on the outer if and the lock and place them on the same line to reduce indentation, it gets to be a mess very quickly except with the shortest and most trivial of conditions:

    if (condition) lock(lockObj) if (condition)
    {
        // statements
    }

# Solution
In order to alleviate this, I'd propose combining the construct in a similar way to catch filters:

    lock(lockObj) if (condition)
    {
        // statements
    }

*However*, this is already valid C#, so would impact backwards-compatibility. Instead, I'd suggest using when in place of if; It still reads off quite naturally, and is only a contextual keyword:

    lock(lockObj) when (condition)
    {
        // statements
    }

As far as I can tell, this can't compile under C# 5/6, though I'm sure someone can find a counter-example ;)

I don't see developers 'abusing' the condition in the same way they might on catch (e.g. logging taking a lock) as they can already do this just before the lock is taken, but some might disagree!

I see the main problem being if a developer unsuspectingly uses a non-pure/side-effecting condition without realising it will be evaluated twice, but I'd hope good documentation would avoid this.

It's not the most pressing of concerns and doesn't really afford us any new expressiveness, but does follow nicely the current trend of reducing boilerplate by making certain parts of the language more concise, and appears to be a relatively simple lowering transformation.

**Comment by omariom** [comment]
Double checked locking is not that complex to simplify it further.
And there are other means to do [one time initialization](https://msdn.microsoft.com/en-us/library/dd997286(v=vs.110).aspx).

**Comment by matwilko** [comment]
@omariom I'm not claiming that it's complex, this is just a way of making an otherwise quite verbose construct more succinct, much like auto-properties are not complex but reduce the verbosity of declaring a separate field and get/setters.

And it's not useful simply for one time initialization - a problem which I agree is for most cases solved by Lazy<T> or nested classes etc.

Synchronizing access to say Dictionary where you want to check if a key already exists before locking and adding the new entry is one use-case of double-locking. Another might be multiple consumers of a queue that want to avoid taking the lock if the queue is empty, or multiple consumers on a stream that doesn't have any data to read currently.

Yes, these use cases may well have already been encapsulated in concurrent collections or otherwise, but the point is that there are many use-cases of conditional locking beyond one-time initialization, and this just makes those cases a bit less indent and duplication heavy.

**Comment by sharwell** [comment]
> Synchronizing access to say Dictionary where you want to check if a key already exists before locking and adding the new entry is one use-case of double-locking.

This would not be a valid operation on `Dictionary<TKey, TValue>`. You would need to use a reader-writer lock (e.g. `ReaderWriterLockSlim`) or use a `ConcurrentDictionary<TKey, TValue>`, neither of which need double-checked locking.

**Comment by mikedn** [comment]
@matwilko "Synchronizing access to say Dictionary where you want to check if a key already exists before locking and adding the new entry is one use-case of double-locking"

As in this code?

```C#
if (!d.ContainsKey(k)) {
    lock (d) {
        if (!d.ContainsKey(k)) {
            d.Add(k...
```

If that's what you have in mind then forget about it, it's wrong. Presumably you're using a lock because some other thread may modify the dictionary and that means that calling ContainsKey without holding the lock is incorrect.

In general, I don't remember seeing double checked locking used for anything other than initialization. That's because it's not that common that the condition you're trying to check can run correctly outside the lock.

**Comment by matwilko** [comment]
@sharwell, @mikedn: The general view I'm getting from you is that this would encourage dev's to write innocuous but invalid conditions, and thus would violate the principle of making it easy to do the right thing/hard to do the wrong thing. You learn something new everyday, and I have some locks that I need to go check now! :)

I didn't think this would really go anywhere, but do you think there's anything useful or salvageable from the suggestion, or shall I just close it?

**Comment by sharwell** [comment]
@matwilko Between `Lazy<T>`, `LazyInitializer`, and a few other items, I haven't found myself in need of improved double-checked locking. Most code I write that's intended for multi-threaded environments is either not performance sensitive (and thus locking is fine), or is performance sensitive and uses lock-free algorithms.

**Comment by sharwell** [comment]
@matwilko I *do* on the other hand wish there were additional specialized concurrent types available (from time to time).

**Comment by matwilko** [comment]
> That said, I'm in no place to tell you what to do with (or the outcome of) this suggestion.

On the contrary, when you've shown why it's a poor idea and it is unlikely to actually be useful, with concrete examples of good alternatives, I think it is your/our place to at least suggest closure, if only to save the suggester's ego from the inevitable piling on later. Consensus is sometimes overrated!

> I do on the other hand wish there were additional specialized concurrent types available (from time to time), where the API hides the concurrency details from the user.

Well, the framework's open-source now, who knows what you might get if you ask (in the right place)? :+1:
