### ISSUE TITLE
4 VSI tests skipped due to ErrorListPackage load failure blocking VSI runs

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#13032]
All the windows_vsi_p1_open_prtest and windows_vsi_p3_open_prtest are currently timing out due to ErrorListPackage load failure modal dialog popping up midway during VSI runs and causes all the remaining tests to time out

Following tests have been skipped with https://github.com/dotnet/roslyn-internal/pull/1245 to unblock the VSI runs:
1. BasicSnippets
2. CSharpSnippets
3. BasicWPF
4. CSharpWPF

**You must unskip these tests and verify the VSI runs pass few times in Jenkins before closing this issue.**

![errorlistpackage](https://cloud.githubusercontent.com/assets/10605811/17524013/96230dfa-5e11-11e6-9104-f3d6e85074de.png)

**Comment by mavasani** [comment]
Tagging @dotnet/roslyn-infrastructure - we need to fix this ASAP to unblock VSI runs.

@heejaechang are you aware of any ErrorList changes that could have caused this?

**Comment by jasonmalinowski** [comment]
These often fail due to some more subtle cause like a MEF issue or something. What does the ActivityLog.xml from the machine say?

**Comment by mavasani** [comment]
```
<description>LegacySitePackage failed for package [ErrorListPackage]Source: &apos;Microsoft.VisualStudio.Composition&apos; Description: Expected 1 export(s) with contract name &quot;Microsoft.Internal.VisualStudio.Shell.TableControl.IWpfTableControlProvider&quot; but found 0 after applying applicable constraints.&#x000D;&#x000A;Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name &quot;Microsoft.Internal.VisualStudio.Shell.TableControl.IWpfTableControlProvider&quot; but found 0 after applying applicable constraints.&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()&#x000D;&#x000A;   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()&#x000D;&#x000A;   at Microsoft.VisualStudio.ErrorListPkg.Common.GetMefService[T]()&#x000D;&#x000A;   at Microsoft.VisualStudio.ErrorListPkg.ErrorListPackage.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)</description>
```

The MEF corruption seems to be happening midway during the test run (no single specific test causing it to fail) and seems to happen only for VSI test partitions p1 and p3.

**Comment by mavasani** [comment]
/updateConfiguration resolved the issue on the machine, but I wasn't able to get the issue to repro again manually on the lab machine. Should we add a workaround for this in StartTargetAction to clear the MEF cache before launching VS?

**Comment by natidea** [comment]
@jasonmalinowski @ManishJayaswal @mavasani is anyone actively looking into this, and can we get it assigned?

**Comment by heejaechang** [comment]
while I am doing some other thing which required me to sync to old roslyn code, I noticed that the error list package failure start to happen once I sync pass to new find all reference UI (which looks like internally - editor teams code - uses table control which is what error list also uses) code.

I didn't dig in to find out why, but that symptom seems consistent. if I move code back to before the new UI, the error list package failure disappears.

**Comment by mavasani** [comment]
Note that I was able to unblock the VSI runs by skipping 4 tests that were eventually causing the MEF cache corruption. The tests are fine by themselves, it seems to be bug in extension manager (I'll file one right now). We need to unskip these tests when we either have a workaround for the MEF cache corruption OR the extension manager is fixed and we move to a new base drop with the fix.

**Comment by jasonmalinowski** [comment]
Moving to IDE for further investigation, especially since @heejaechang is mentioning this started behaving differently around the new FAR UI.

**Comment by Pilchie** [comment]
Can you take a look at this as you work on updating to the latest FAR APIs?  Maybe this will go away when we update our integration test machines?

**Comment by Pilchie** [comment]
Hopefully fixed by moving to all Dev15?

**Comment by mavasani** [comment]
Yes, we should try to re-enable these tests once we move Jenkins to Preview5/RC builds for VSI tests.

**Comment by Pilchie** [comment]
Moving to RTW, but hopefully we can re-enable these ASAP now that we're on Dev15.

**Comment by tmeschter** [comment]
These are all broken for other reasons at the moment.

The *Snippets.xml tests are broken while trying to look up a (now non-existent) reg key for the location of user snippets.

The *WPF.xml tests are broken due to unexpected errors in the Error List--something about 'button1' not being declared and/or accessible.

**Comment by Pilchie** [comment]
Are there other bugs tracking those failures such that this one should be closed?

**Comment by Pilchie** [comment]
Any idea what the state of these are now?

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving out again.

**Comment by CyrusNajmabadi** [comment]
Closing out due to age and rewrite of integration tests.
