### ISSUE TITLE
Implement-interface on a property/event with attributes does not implement those attributes

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#13036]
When testing implement-interface on an interface with tuple names, I noticed that the generated code for a method implementation would print out a `TupleElementNames` attribute. See https://github.com/dotnet/roslyn/issues/12949
But when I tried the same on a property implementation (and also an event implementation), the problem did not exist. I think this means the code does not carry attributes (although it intends to, since `ImplementInterfaceCodeAction.GenerateProperty` makes sure to remove the undesired `ComAliasNameAttribute`).

```C#
        public async Task TupleWithNamesInProperty()
        {
            await TestAsync(
@"interface IInterface { [System.Runtime.CompilerServices.TupleElementNames(new[] { ""a"", ""b"" })] (int a, int b)[] Property1 { [System.Runtime.CompilerServices.TupleElementNames(new[] { ""a"", ""b"" })] get; [System.Runtime.CompilerServices.TupleElementNames(new[] { ""a"", ""b"" })] set; } } class Class : [|IInterface|] { } " + s_tupleElementNamesAttribute,
@"using System; interface IInterface { [System.Runtime.CompilerServices.TupleElementNames(new[] { ""a"", ""b"" })] (int a, int b)[] Property1 { [System.Runtime.CompilerServices.TupleElementNames(new[] { ""a"", ""b"" })] get; [System.Runtime.CompilerServices.TupleElementNames(new[] { ""a"", ""b"" })] set; } } class Class : IInterface { public (int a, int b)[] Property1 { get { throw new NotImplementedException(); } set { throw new NotImplementedException(); } } } " + s_tupleElementNamesAttribute);
        }
```

In fixing that, please make sure that `TupleElementNamesAttribute` is not generated in the implementation (it should never appear in source).

FYI for @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
@jcouv Do you just want to roll this into your other PR?

**Comment by CyrusNajmabadi** [comment]
I say that because otherwise, i'll just have to wait on yours to go through, and then just apply the same attribute filtering to those helpers in that file.  Since you're already working on it, it seems like it might be easier to just have as part of your PR.

**Comment by jcouv** [comment]
I haven't looked at the proper fix in details. It will probably need new filtering helpers for events.
I'll merge my other PR shortly.

**Comment by CyrusNajmabadi** [comment]
Sounds good.  Will do this work once yours goes through.

**Comment by CyrusNajmabadi** [comment]
The issue here is that we don't preserve attributes from the original property/event.  However, this seems extremely minor to me.  We haven't heard about this issue from anyone yet.  It's not terribly clear to me that we should be preserving attributes *ever* when implementing an interface.

**Comment by CyrusNajmabadi** [comment]
Closing this out as we've never heard of any issues around here, and the current behavior seems like a non-issue.
