### ISSUE TITLE
VB tuples: Extract Method/Local for a tuple literal treats it as Object 

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#13042]
Semantic info seems to return correct converted type. However IDE generates something like:

```VB
         Dim r1 = M2(arg:=(i:=CInt(1), d:=CDbl(1)))  
```

becomes

```VB
        Dim p As Object = (i:=CInt(1), d:=CDbl(1))
        Dim r1 = M2(Of T)(arg:=p)       
```

**Comment by jcouv** [comment]
We had the same bug in C#, which was fixed there. 
This is probably an issue with the serialization and deserialization of `SymbolKey` in IDE code for VB.

**Comment by VSadov** [comment]
@jcouv - yes, I suspected as much. I do not consider this blocking though since it is not crashing. Will be one of the first bugs to fix when in master.
