### ISSUE TITLE
Async project loading sometimes takes tens of seconds, even on single tiny console-app projects.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#13043]
Cyrus, can we please have a bug filed on this against IDE?

From: David Kean 
Sent: Wednesday, August 3, 2016 4:28 PM
To: Svetlozar Keremidarski svetkere@microsoft.com; Cyrus Najmabadi cyrusn@microsoft.com; Viktor Veis viveis@microsoft.com; Kevin Pilch-Bisson kevinpi@microsoft.com
Subject: RE: Weird async load behavior.

Okay, I’m heard two more reports of this today. 

Bill Hiebert was saying that he used to hit this in previous releases (and Svet you mentioned it might be a bug in csproj)– so it sounds like something changed this release that made it more prevalent.

Cyrus, can you least get a bug filed so that we’re tracking this? I’ll let Kevin/Viktor figure where this bug lies and who investigates.

From: Svetlozar Keremidarski 
Sent: Thursday, July 28, 2016 2:24 PM
To: David Kean David.Kean@microsoft.com; Cyrus Najmabadi cyrusn@microsoft.com; Viktor Veis viveis@microsoft.com
Subject: RE: Weird async load behavior.

With console app, I was referencing to “consoleapplication1” project system (from you picture I figure it was this) – aka classic charp project system(one you team owns for 2 years now ) . You mentioned project creation stack bellow which is very first (and usually very fast) step in ASL load and I was suggesting to look at the other (much slower) step on the same process involving the said project system and executed on the event I mentioned. 

David, I don’t know what bug is that, or whether it is a bug or just the state in Cyrus machine for example. 

Here are some possible areas that may be related on top of my head.
-   BSL loader (perhaps influenced by DPL changes?)
-   Legacy charp project system (from the picture)
-   Some extension (nugget?) that also listen to open event and participate. 
-   BSL settings (StopIDLE switch for example would create similar behavior). 

From: David Kean 
Sent: Thursday, July 28, 2016 1:40 PM
To: Cyrus Najmabadi cyrusn@microsoft.com; Svetlozar Keremidarski svetkere@microsoft.com; Viktor Veis viveis@microsoft.com
Subject: RE: Weird async load behavior.

Svet who’s bug is this? Solution load or csproj?

It’s probably better to have the owners deep dive.

From: Cyrus Najmabadi 
Sent: Thursday, July 28, 2016 1:37 PM
To: Svetlozar Keremidarski svetkere@microsoft.com; Viktor Veis viveis@microsoft.com
Cc: David Kean David.Kean@microsoft.com
Subject: RE: Weird async load behavior.

Not sure what you mean by this:

> Assuming it is not the key, then you may want to check the “[Priority]OnAfterOpenProject”  events handling in the console app

What console app are you referring to?

```
    -- Cyrus
```

From: Svetlozar Keremidarski 
Sent: Thursday, July 28, 2016 11:32 AM
To: Cyrus Najmabadi cyrusn@microsoft.com; Viktor Veis viveis@microsoft.com
Cc: David Kean David.Kean@microsoft.com
Subject: RE: Weird async load behavior.

Check if you have StopIDLE in the VS registry (although if it finishes by its own – aka before you do build and such, it is unlikely to be the reason)

Assuming it is not the key, then you may want to check the “[Priority]OnAfterOpenProject”  events handling in the console app, this is the second part that is called after the project creation and usually takes significantly more time – this is where intelisense build and LS initialization happen. (CreateProjectAsync stacks bellow is the first step and usually is very fast). 

From: Cyrus Najmabadi 
Sent: Thursday, July 28, 2016 11:24 AM
To: Svetlozar Keremidarski svetkere@microsoft.com; Viktor Veis viveis@microsoft.com
Cc: David Kean David.Kean@microsoft.com
Subject: RE: Weird async load behavior.

It eventually finishes.  Usually after a minute or so.   I’m not sure I understand your second statement.

```
         -- Cyrus
```

From: Svetlozar Keremidarski 
Sent: Thursday, July 28, 2016 11:08 AM
To: Cyrus Najmabadi cyrusn@microsoft.com; Viktor Veis viveis@microsoft.com
Cc: David Kean David.Kean@microsoft.com
Subject: RE: Weird async load behavior.

Is it eventually done? Or it never finish? 
If later it is consisted to having BSL idle working stopped (the regkey was (something like) <root>\BackgroundSolutionLoad\StopIDLE ). 

From: Cyrus Najmabadi 
Sent: Thursday, July 28, 2016 1:06 AM
To: Svetlozar Keremidarski svetkere@microsoft.com; Viktor Veis viveis@microsoft.com
Cc: David Kean David.Kean@microsoft.com
Subject: RE: Weird async load behavior.

Note: I’m getting this even for the most basic of projects.  Even a console app shows ‘loading’ for 30-60+ seconds.

```
            -- Cyrus
```

From: Cyrus Najmabadi 
Sent: Wednesday, July 27, 2016 5:48 PM
To: Svetlozar Keremidarski svetkere@microsoft.com; Viktor Veis viveis@microsoft.com
Cc: David Kean David.Kean@microsoft.com
Subject: Weird async load behavior.

Hey Guys,

I’m seeing some _very_ weird async loading behavior that reproes for me about 95% of the time.  See attached video as an example of what’s going on.  Basically, I’m loading a very small solution (four tiny csproj projects).  VS is totally responsive when I do this, but it takes ages to load the actual projects.  Any project I try to manually open will get loaded instantly, but any non-loaded projects still take forever.  After about 30-60 seconds, the projects finally load.  During this time there is practically 0% CPU and disk load.

Dave and I have tried debugging through this, but when we break it appears as if nothing is really happening.  Eventually the projects do get created with calls to:

```
           csproj.dll!CInitializeForOwnerAsync::CreateProjectInternalAsync(IVsTask * * ppTask) Line 359              C++
          csproj.dll!CCSharpProjectFactory::CreateProjectAsync(const _GUID & rguidProjectID, const wchar_t * pszFilename, const wchar_t * pszLocation, const wchar_t * pszName, unsigned long flags, IVsTask * * ppTask) Line 351      C++
          msenv.dll!CVsProjectType::HrOpenProjectAsync(const _GUID & rguidProjectID, const wchar_t * lpszCaptionTemp, const wchar_t * lpszFileTemp, const wchar_t * lpszLocationTemp, const wchar_t * lpszNameTemp, unsigned long grfCreateFlags, int * ppTask, IVsHierarchy * *) Line 2769 C++
          msenv.dll!CVsProjectTypeMgr::HrOpenProjectAsync(const _GUID & rguidProjType, const _GUID & rguidProjectID, const wchar_t * lpszCaptionTemp, const wchar_t * lpszFileTemp, const wchar_t * grfCreateFlags, const wchar_t * pfCanceled, unsigned long ppHierarchy, int * ppTask, IVsHierarchy * *) Line 918          C++
```

> ```
>         msenv.dll!CProject::DoReloadProjectAsync(IVsTask * * ppTask) Line 1731               C++
> ```

My guess is there’s some sort of _extremely_ aggressively back-off/throttling in the async solution load codepath.  That, or it’s so low priority, that it keeps getting preempted by other work.  Either way, the user experience is very bad.

Is that something that sounds like anything you guys know about?

This is on:

**Comment by CyrusNajmabadi** [comment]
![asyncload](https://cloud.githubusercontent.com/assets/4564579/17531177/ca1c69bc-5e48-11e6-962a-d11b3a24b260.gif)

**Comment by Pilchie** [comment]
@CyrusNajmabadi Do you still have a consistent repro here?  You and @jasonmalinowski might need to sit down together once you are back in town.

**Comment by CyrusNajmabadi** [comment]
ETL trace 1: "\\mlangfs1\public\cyrusn\ETL\~10SecondDelayLoadingTinyProject.zip"

I have another coming where it took more like 40+ seconds.

**Comment by CyrusNajmabadi** [comment]
\\mlangfs1\public\cyrusn\ETL

**Comment by jasonmalinowski** [comment]
Stale: we've rearchitected much of this now.
