### ISSUE TITLE
Consider renaming IsSameTypeIgnoringCustomModifiers

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#13054]
removing "PROTOTYPE" markers.

The method also ignores tuple names now.

We could just add another "ignoreXXX" to the method, but perhaps we can call the method more conceptually like IsSameTypeIgnoringDecorations or something like that.

**Comment by jcouv** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/14229
