### ISSUE TITLE
[Test Failure] <description> in windows_vsi_p3_open_prtest on PR #13018

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#13058]
PR: [#13018](https://github.com/dotnet/roslyn/pull/13018) *reduce creating default Task.FromResult tasks.* by @heejaechang
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_open_prtest/398/

**Comment by heejaechang** [comment]
error list pkg failed to load issue.

**Comment by jasonmalinowski** [comment]
Failure information isn't there anymore.
