### ISSUE TITLE
Signature Help highlights wrong parameter for attributes with params constructor argument

### ISSUE THREAD

**Issue by kayle** [dotnet/roslyn#13067]
VS 2015 Update 3

Found when consuming Thinktecture.IdentityModel.WebApi.ResourceAuthorizeAttribute. below is a simpler repro:

```
[MyAttribute(1, "abc", $$ )]
class MyAttribute : System.Attribute
{
    public MyAttribute(int x, params string[] args) { }
    public int Role { get; set; }
}
```

**Expected Behavior**:

When the cursor is at $$, it should highlight the string array argument.

**Actual Behavior**:

![image](https://cloud.githubusercontent.com/assets/1664776/17557904/eb4e4030-5ee6-11e6-8b22-d28e0a1b623e.png)

**Comment by Pilchie** [comment]
@kayle if only you knew something about that codebase :wink:

**Comment by kayle** [comment]
We'll see... My todo list keeps getting longer lately. Maybe I can get a dev environment set back up during the next gymnastics watching session.

**Comment by CyrusNajmabadi** [comment]
Closing out given lack of feedback.  The experience seems fine.  It is a place where you can supply a named property attribute argument.
