### ISSUE TITLE
Change CodeLens to use Roslyn preview APIs

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/roslyn#13069]
Currently, the CodeLens service manually gets the line before/line after to display in CodeLens tooltips. @CyrusNajmabadi commented in #13037: "In the future we should be able to make this much nicer.  For example, see the work done with the new streaming FAR system.  There we actually are able to show a real preview of the actual code of the reference, not just unclassified lines of text.  But that can wait."

**Comment by CyrusNajmabadi** [comment]
CodeLens will move to LSP entirely.
