### ISSUE TITLE
Code block outlining

### ISSUE THREAD

**Issue by scottdorman** [dotnet/roslyn#13066]
Visual Studio (through Roslyn) already supports automatically creating outlining regions for things like using directives, regions, comments, and methods. What it doesn't support (which VS Code does, see the screenshot) is the ability to automatically create outlining regions for code control structures (like `if` blocks, `for`, `foreach`, `while` and `do..while` loops, `try..catch` blocks), object initializers and collection initializers. (Probably others as well.)

<img width="393" alt="outlining" src="https://cloud.githubusercontent.com/assets/2532850/17557688/33128300-5ee6-11e6-8601-5bfaa87cd107.png">

**Comment by Pilchie** [comment]
Note that we should implement support for the editor's Indent Guide API at the same time.

**Comment by Pilchie** [comment]
How much did you get done here?

**Comment by CyrusNajmabadi** [comment]
I've done statements.  Have not done expressions (like collection initializers).

**Comment by CyrusNajmabadi** [comment]
@davidarno Could you clarify why you thumbs-downed this?

**Comment by DavidArno** [comment]
@CyrusNajmabadi,

I "thumbs-downed" it as I'm a fan of every member/type/file should be short enough to not need `#region`'s  or outlining regions. But, that's not a valid reason to block this, so I've removed that down-vote. Folk want this, so let them have it...

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/14957

**Comment by sharwell** [comment]
Reopening as the previous mentioned issue is unrelated to the feature request here.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We support all these cases:

> if blocks, for, foreach, while and do..while loops, try..catch blocks), object initializers and collection initializers.
