### ISSUE TITLE
C# EnC: investigate and handle select clauses that don't produce lambdas

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#1306]

**Comment by tmat** [comment]
"See section 7.16.2. The translation is defined recursively. See, for example, see 7.16.2.5 for a case that generates no lambda, and note the exception given in 7.16.2.3. There are a number of special cases and the effects may be subtle due to the recursive interactions of the rules."

**Comment by gafter** [comment]
See also the translation for the `join` clause, which may produce up to three lambdas.

The `orderby` clause may produce any number of lambdas.

The `groupby` clause has a special case that causes a lambda to be omitted.

**Comment by tmat** [comment]
Re ```orderby``` clause - yes, this is accounted for. Each lambda is represented by OrderingClause not OrderBy clause itself.

**Comment by tmat** [comment]
Re ```join``` - also got this right, I think. There is a lambda body for left expression, lambda body for right expression and pair lambda for creating the pair. An Into clause also produces a "pair" lambda.

**Comment by gafter** [comment]
"A query expression with a `join` clause without an `into` followed by something other than a `select` clause" also produces a "pair" lambda.

**Comment by tmat** [comment]
There is one thing that I need to double check - if a clause produces multiple pair lambdas that it might confuse the reverse mapping. We can either associate each pair lambda with a different (part of) clause if possible or we can just name them differently, so that the reverse mapping completely ignores these lambdas.  If the reverse mapping doesn't find a an existing lambda in previous generation it creates a new one. So we would just recreate all pair lambdas, which is fine since they don't contain user code/breakpoints.

**Comment by tmat** [comment]
Investigation done. #2672 is tracking the specific issues and cases that are currently broken.
