### ISSUE TITLE
Should ParenthesizedVariableComponentSyntax.Variables be named Components?

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13078]
In this syntax node

```xml
  <Node Name="ParenthesizedVariableComponentSyntax" Base="VariableComponentSyntax">
    <Kind Name="ParenthesizedVariableComponent"/>
    <Field Name="OpenParenToken" Type="SyntaxToken">
      <Kind Name="OpenParenToken"/>
    </Field>
    <Field Name="Variables" Type="SeparatedSyntaxList&lt;VariableComponentSyntax&gt;"/>
    <Field Name="CloseParenToken" Type="SyntaxToken">
      <Kind Name="CloseParenToken"/>
    </Field>
  </Node>
```

Should `Variables` be renamed `Components`?

A similar question applies to

```xml
  <Node Name="ParenthesizedVariableDesignationSyntax" Base="VariableDesignationSyntax">
    <Kind Name="ParenthesizedVariableDesignation"/>
    <Field Name="OpenParenToken" Type="SyntaxToken">
      <Kind Name="OpenParenToken"/>
    </Field>
    <Field Name="Variables" Type="SeparatedSyntaxList&lt;VariableDesignationSyntax&gt;"/>
    <Field Name="CloseParenToken" Type="SyntaxToken">
      <Kind Name="CloseParenToken"/>
    </Field>
  </Node>
```

(I'm asking because I'm not sure how much scrutiny these names received during the review)

@jaredpar @VSadov @AnthonyDGreen @jcouv Opinions?

**Comment by jcouv** [comment]
For the first one, I'd instead consider renaming `ParenthesizedVariableComponentSyntax` to `ParenthesizedVariablesSyntax`.

For the second one, I'd consider making `ParenthesizedVariableDesignationSyntax` be plural (`ParenthesizedVariableDesignationsSyntax`) or even simplify to `ParenthesizedDesignationsSyntax`,  and then rename `Variables` to be `Designations`.

**Comment by gafter** [comment]
The first rename you suggest isn't consistent with the pattern we use to name subtypes, and would introduce a confusion with existing nodes representing local variable declarations.

I was only asking about the two field names.

```xml
    <Field Name="Variables" Type="SeparatedSyntaxList&lt;VariableComponentSyntax&gt;"/>
```

and

```xml
    <Field Name="Variables" Type="SeparatedSyntaxList&lt;VariableDesignationSyntax&gt;"/>
```

**Comment by gafter** [comment]
@AndyGerlicher Please stop changing labels on our bugs.
