### ISSUE TITLE
Make CodeLens naming consistent with IDE

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/roslyn#13070]
CodeLens currently uses it's own naming scheme for showing entity names in tooltips. As @CyrusNajmabadi commented in #13037: "If you hover over a codelens reference you should see info with the same display that the IDE generally uses elsewhere.  i.e. the display we use for CodeLens should match waht we have for QuickInfo/FindReferences/NavBars etc.  It's strange that we have a totally random different way of displaying things for this scenario.  (And now that we own it ourselves, we should make things all consistent)."

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
