### ISSUE TITLE
CodeStyle -> General and Naming Styles do not support Narrator

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#13099]
Windows Narrator reads the name of the view model type if you highlight one of these combo boxes.

![image](https://cloud.githubusercontent.com/assets/3751401/17602243/a4ef8d94-5fc0-11e6-9470-3bb0560c0009.png)

**Comment by rchande** [comment]
cc @balajikris

**Comment by balajikris** [comment]
:cry: yeah, didn't get a chance to implement this originally, during preview. Will need to fix this.

**Comment by rchande** [comment]
Sure, go ahead and close this if you're tracking the work elsewhere.

**Comment by balajikris** [comment]
I don't think there is another workitem, I'll keep this. thanks.

**Comment by Pilchie** [comment]
Closing as fixed by #16380
