### ISSUE TITLE
[Proposal] Loops: improve first-item-is-special scenario

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#131]
#### Problem

I can't count the times when I had to write something like

```csharp
var first = true;
foreach (var x in xs) {
    if (!first) {
        builder.Append(",");
    }
    else {
        first = false;
    }    
    ...
}
```

Not only is this verbose, but also inefficient -- each iteration checks the variable even though it is known in advance it would be false for all but the first. 

##### A. Provide a first {} block.
Example:
```csharp
foreach (var x in xs) {
    first {} else {
        Append(",");
    }
    ...
}
```
Pros: 
1. Reduced verbosity
2. Potential for compiler optimizations by separating first item handling from the remaining loop

Cons:
1. No idea for good not-first syntax: `first {} else {}`, `!first {}`?

##### B. Provide an automatic loop index variable in loops.
Example:
```csharp
foreach (var x in xs) {
    if (index > 0) { // "index" is automatically provided here
        Append(",");
    }
    ...
}
```

Pros: 
1. Reduced verbosity
2. An index that might be useful for other things such as numbering in output

Cons:
1. Compiler optimizer would have to look for specific coding patterns (`if (index > 0)`) if it wants to make the loop more efficient.

**Comment by apskim** [comment]
If we had tuple destructing syntax from the pattern matching proposal, you solution B could be easily implemented with a Python idiom:

```cs
foreach (var (index, x) in xs.Enumerate()) {
    if (index > 0)
        Append(",");
    // ...
}

public static IEnumerable<Tuple<int, T>> Enumerate<T>(this IEnumerable<T> seq) {
    int i = 0;
    foreach (T x in seq) {
        yield return Tuple.Create(i, x);
        ++i;
    }
}
```

**Comment by ashmind** [comment]
@apskim
I like the idea functionally, but the performance would be worse, especially for primitives, given that the `Tuple` is a reference type.

Also C# currently optimizes `foreach` loops to `for` loops in some cases (e.g. arrays, see here http://tryroslyn.azurewebsites.net/#b:master/K4Zwlgdg5gBAygTxAFwKYFsDcAoADsAIwBswBjGUogQxBBgGEYBvbGNmfYsmANwHswAExgBZABQBKZq3ayAZnwBOqKqQAWMMTyqKYADxiQYEVAHcA2gF1mMAIwAaAEz2AzDAC+UlrNnuZbP3cgA=) -- this optimization would be lost if I used custom `Enumerate`.

**Comment by pdelvo** [comment]
@apskim This would be a readable solution but it would be bad in terms of performance because Tuple is a reference type you are creating a reference type for each loop iteration.

**Comment by RichiCoder1** [comment]
Another idea, which may be bad, is adding a `once` keyword or something like it.
Ex:
```csharp
foreach (var x in xs) {
    once {
        Append(":");
        continue;
    } 
    Append(",");
}
```

which might also enable something like:
```csharp
foreach (var x in xs) {
    once (x.length == 2) {
        Append(":");
        continue;
    } 
    Append(",");
}
```

**Comment by fubar-coder** [comment]
Another potential solution might be, that we have an abbreviated `foreach` body and a verbose.

```cs
// abbreviated
foreach (var x in xs) {
    // code in loop
}

// roughly translates to
foreach (var x in xs) {
    default {
        // code in loop
    }
}

// this would be the complete form
foreach (var x in xs) {
    first {
        // executed for first item
        ...
        // chaining could be done with
        goto default;
    }
    default {
        // executed for all items not matched by first (when specified) or last (when specified)
    }
}
```

Maybe there's room for a `last` block too? Should we allow a `goto first` from inside a `default` block?

**Comment by lyubomyr-shaydariv** [comment]
The Nemerle compiler provides indexed iteration: `foreach (item in sequence *with i*)`. Please see https://github.com/rsdn/nemerle/wiki/Lists-and-Indexed-Iteration

**Comment by mysticatea** [comment]
```cs
var en = xs.GetEnumerator();
if (en.MoveNext())
{
    var x = en.Current;
    // do for the first.

    while (en.MoveNext())
    {
        x = en.Current;
        // do for not first items.
    }

    // do for the last. (`x` is last item.)
}
else {
    // do when empty.
}
```

**Comment by AdamSpeight2008** [comment]
@mysticatea I was just going to suggest that.
Plus there's the `Aggregate` method.

     var x = xs.Skip(1).Aggregate( xs.First //stuff on first, (prev , curr)=>  // stuff for other ) // stuff after last.

**Comment by ashmind** [comment]
@mysticatea That's exactly what I want the compiler to generate for me, as the case seems to be pretty common. And while you implementation is efficient, it does not cover C# compiler optimization for arrays, which doesn't use enumerator at all.

@AdamSpeight2008 That would be inefficient if enumerable is not optimized for multi-iteration. E.g. for the following method you don't want to call both `First()` and `Skip()`:
```csharp
public IEnumerable<T> GetAll<T>() {
    var data = GetDataFromDB();
    foreach (var item in data) {
        yield return Convert(item);
    }
}

**Comment by RichiCoder1** [comment]
@ashmind I'm somewhat against having these conditional blocks have `else` or introducing an `always`. It seems to add a lot of unnecessary noise, as well as curly brackets and depth. I'd be much more in favor of just having `first/once` behave like a normal `if`, so you could either use `else` or just `continue` to skip the rest of the `for(each)` block.

Something like:
```csharp
//  StringBuilder sb;
var args = obj.GetArguments();
foreach(var prm in args)
{
    once {
        sb.Append("(");
    }

    var byPrm = "";
    if(prm.IsRef)
    {
        byPrm = " ref";
    }
    else if(prm.IsOut)
    {
        byPrm = " out";
    }
    sb.Append(string.Format("{0}{1} {2}", prm.Type, byPrm, prm.Name);

    last {
        sb.Append(")");
    }
}
 // .....
```
which would unfold into something like:
```csharp
IEnumerable<Argument> args = obj.GetArguments();

bool isOnceExecuted = false;
bool wasLoop = false;
var argsEnumator = args.GetEnumerator();
while(argsEnumator.MoveNext())
{		
    if(!wasLoop)
	{
		wasLoop = true;
	}
	
    var prm = argsEnumator.Current;
    if(!isOnceExecuted) {
        sb.Append("(");
		isOnceExecuted = true;
    }

    var byPrm = "";
    if(prm.IsRef)
    {
        byPrm = " ref";
    }
    else if(prm.IsOut)
    {
        byPrm = " out";
    }
    sb.Append(string.Format("{0}{1} {2}", prm.Type, byPrm, prm.Name);
}

if(wasLoop) {
	sb.Append(")");
}

// .....
```

**Comment by AdamSpeight2008** [comment]
What about these extension methods? #153

**Comment by RichiCoder1** [comment]
They'd be convenient for Linq, but this issue is specifically for `for` and `foreach` language extensions rather than BCL additions.

**Comment by thomaslevesque** [comment]
I would actually like to generalize the idea by adding the notion of "steps":

```
foreach (var x in xs)
{
    step
    {
        // handle first
    }
    step
    {
        // handle second
    }
    then
    {
        // handle others
    }
}
```

The compiler would generate something like this:

```
using (var en = xs.GetEnumerator())
{
    if (en.MoveNext())
    {
        {
            var x = en.Current;
            // handle first
        }
        if (en.MoveNext())
        {
            {
                var x = en.Current;
                // handle second
            }
            while (en.MoveNext())
            {
                var x = en.Current;
                // handle others
            }
        }
    }
}
```
(note the dummy braces: this is to follow the new semantic of the foreach loop in C# 5, where the loop variable is logically declared inside the loop, not outside. This way the loop variable isn't shared between iterations)

**Comment by RichiCoder1** [comment]
I'd argue that while `first` and `last` cases are relatively common, calls for steps beyond those are very, very rare. The step syntax would probably be fairly confusing, and reserve a common word. Not to mention I'm still against forcing the body of a foreach to be completely contained in `block-else-block` syntax, vs option specialized blocks.

**Comment by pdelvo** [comment]
I just discovered, that last is actually impossible to implement. Example:
```csharp
using System;
using System.Collections;
using System.Collections.Generic;
public class Class1
{
    static bool _isLast = false;

    class EnumTest : IEnumerable<string>
    {

        public IEnumerator<string> GetEnumerator()
        {
            throw new NotImplementedException();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            throw new NotImplementedException();
        }

        class EnumeratorTest : IEnumerator<string>
        {
            public string Current
            {
                get
                {
                    return "Foo";
                }
            }

            object IEnumerator.Current
            {
                get
                {
                    throw new NotImplementedException();
                }
            }

            public void Dispose()
            {
            }

            public bool MoveNext()
            {
                return !_isLast;
            }

            public void Reset()
            {
                throw new NotImplementedException();
            }
        }
    }

    static void Main()
    {
        var test = new EnumTest();
        foreach (var item in test)
        {
            System.Console.WriteLine(item);
            _isLast = true;

            last
            {
                _isLast = false;
            }
        }
    }
}
```

In the first iteration _isLast is set to true. So no other iteration of the loop is going to happen. So it is the last iteration. So the last block should be executed. But if it is executed the _isLast field is set to false, so another iteration of the loop is going to happen. So it was not the last iteration. Thats a contradiction.Both,running the last block and not running the last block is wrong.

You could also use Rice's theorem to argue that this is not possible.

**Comment by ashmind** [comment]
@pdelvo Originally I haven't proposed `last` — but now I think `last` can be done, by running after `foreach` has finished. And `foreach` should finish after `MoveNext` returned false.

So it's not important that iterator changes its mind later — it's just a buggy iterator, but it would not cause re-iteration.

**Comment by AdamSpeight2008** [comment]
`Last` is possible,

**Comment by pdelvo** [comment]
This would mean that for the last iteration the last part is always executed after the iterator. which would reduce the number of applications. With a first part I could put it at multiple positions in the iterator. Maybe even allow an else block

**Comment by AdamSpeight2008** [comment]
```
FirstLastRest <T,R> ( xs : IEnumerable<T>, onFirst : T-> R, onLast : T->R, onRest : T->R ) : IEnumerable<T>
{
  var en = xs.GetEnumerator()
  if( !en.MoveNext() ) return Empty<R>; 
  var first =  en.Current;
  if( !en.MoveNest() ) return Empty<R>;
  var last = en.Current;
  var state = en.MoveNext();
  if( !state ) return Empty<R>;
  yield return onFirst( first );
  do {
       yield return onRest( last );
       last = en.Current;
      } until ( en.MoveNext() );
  yield return onLast( last );
}

```

**Comment by RichiCoder1** [comment]
@pdelvo agreeing with @ashmind and @AdamSpeight2008 
I one way to do it [here](https://github.com/dotnet/roslyn/issues/131#issuecomment-72088386).

**Comment by RichiCoder1** [comment]
@pdelvo Just read you second statment. That's true, the `last` implementation I suggest is more of an `after` since it does require it's self to be executed after the iteration, and not during. There's no way to determine if something is `last` which inside a foreach without breaking the contract that `en.MoveNext` is only being called when you're explicitly interested in the next item. I'd argue that a `last` inside a loop is only valid for `foreach`s with a clear start and end.

**Comment by AdamSpeight2008** [comment]
@RichiCoder1 re-examine my last example.

**Comment by fubar-coder** [comment]
`last` should remain `last`, because you should have access to the last element of the enumeration.

Implementation:
```csharp
private static void ForEach<T>(
    IEnumerable<T> items,
    Action<T, bool> first,
    Action<T> other,
    Action<T, bool> last)
{
    var enumerator = items.GetEnumerator();
    if (!enumerator.MoveNext())
        return;
    var item = enumerator.Current;
    first(item, false);
    var hasNext = enumerator.MoveNext();
    if (hasNext)
    {
        last(item, true);
        do
        {
            item = enumerator.Current;
            hasNext = enumerator.MoveNext();
            first(item, true);
            if (hasNext)
                other(item);
            last(item, hasNext);
        } while (hasNext);
    }
    else
    {
        last(item, false);
    }
}
```

Test infrastructure:
```csharp
private enum Status
{
    FirstMatch,
    FirstElse,
    Other,
    LastMatch,
    LastElse,
}

private static void StatusEquals(IEnumerator<Status> expectedStatuses, Status status)
{
    if (!expectedStatuses.MoveNext())
        throw new InvalidOperationException(string.Format("Expected no status, got {0}", status));
    if (expectedStatuses.Current != status)
        throw new InvalidOperationException(
            string.Format(
                "Expected status {0}, got {1}",
                expectedStatuses.Current,
                status));
}

private static void TestForEach<T>(IEnumerable<T> items, IEnumerable<Status> statuses)
{
    var testItems = items.ToList();
    Console.WriteLine("ForEach with {0} items.", testItems.Count);
    var statusEnum = statuses.GetEnumerator();
    ForEach(
        testItems,
        (item, isElse) =>
        {
            StatusEquals(statusEnum, isElse ? Status.FirstElse : Status.FirstMatch);
        },
        item =>
        {
            StatusEquals(statusEnum, Status.Other);
        },
        (item, isElse) =>
        {
            StatusEquals(statusEnum, isElse ? Status.LastElse : Status.LastMatch);
        });
    if (statusEnum.MoveNext())
        throw new InvalidOperationException(string.Format("Expected status {0}, got none", statusEnum.Current));
}
```

Tests:
```csharp
private static void Main()
{
    try
    {
        TestForEach(new bool[0], new Status[0]);
        TestForEach(new bool[1], new[] { Status.FirstMatch, Status.LastMatch, });
        TestForEach(new bool[2], new[] { Status.FirstMatch, Status.LastElse, Status.FirstElse, Status.LastMatch, });
        TestForEach(
            new bool[3],
            new[]
            {
                Status.FirstMatch, Status.LastElse,
                Status.FirstElse, Status.Other, Status.LastElse,
                Status.FirstElse, Status.LastMatch,
            });
    }
    catch (InvalidOperationException ex)
    {
        Console.Error.WriteLine(ex.ToString());
    }
    Console.ReadLine();
}
```

I hope that I got this right. This implementation is easy to get wrong :grinning:

**Comment by RichiCoder1** [comment]
I'll be honest, I couldn't read read your example or parse what it was trying to say.

Re-reading it now, that is certainly possible. But it underlines the two different mentalities here. 
1. The idea that `first`, `last`, `step`, and `always`/`rest` are completely independent blocks. If you have a `first`, `last`, and `always`, you are essentially executing three different code blocks.
2. The idea that `once`/`first` and `last` are interwoven into a normal foreach block.

For 1, you'd do something like.
```csharp
IEnumerable<T> items = GetItems<T>();
foreach(var item in items)
{
	first
	{
		// Do something with the first item.
	}
	other
	{
		// Do something with everything else.
	}
	last 
	{
		// Do something with the last item.
	}
}
```
which unfolds to
```csharp
IEnumerable<object> items = GetItems<T>();
var en = items.GetEnumerator();
if(en.MoveNext())
{
	var item = en.Current;
	{
		// Do something with the first item.
	}
	if(en.MoveNext())
	{
		for(;;)
		{
			{
				// Do something with everything else.
			}
			if(!en.MoveNext()){
				{
					// Do something with the last item.
				}
				break;
			}
			item = en.Current;
		}
	}
}
```

For two, you'd have something like this instead:
```csharp
IEnumerable<object> items = GetItems<T>();
foreach(var item in items)
{
	first
	{
		// Do something with the first item.
	}
	last 
	{
		// Do something after everything else has been done.
	}
	
	// Do some other work.
	
	once (item.Property1 == 2)
	{
		// do some more things
	}
	
	last
	{
		// So some final thing.
	}
}
```
which unfolds into:
```csharp
IEnumerable<object> items;
var en = items.GetEnumerator();
if(en.MoveNext())
{
	 object item;
	 bool __hasExecutedOnce1 = false;
	 bool __isFirst = true;
	 bool __isLast = false;
	 for(;;)
	 {
	 	__isLast = en.MoveNext();
		if(__isFirst)
		{
			// Do something with the first item.
		}
		if(__isLast)
		{
			// do something after everything else has been done
		}
		
		// Do some other work.
		
		if((item.Property1 == 2) && !_hasExecutedOnce1)
		{
			// do some more things
			_hasExecutedOnce1 = true;
		}
		
		if(__isLast)
		{
			// do something after everything else has been done
		}
		if(__isLast)
		{
			break;
		}
		if(__isFirst)
			__isFirst = false;
		item = en.Current;
	 }
}
```

**Comment by pdelvo** [comment]
The problem with that is that you are changing how foreach works. If you have an enumerator which will return 1 item, then loops forever. Currently foreach will be called once, then it hangs. With your version it will not call the body once because it is calling MoveNext() twice before the body. Thas a breaking change. For making last to work you have to evaluate MoveNext() before the body is called (like you did) and you just cant do this without possibly breaking stuff. So version 2 is unfortunatly not possible. I dont think version 1 would be of much use because it can be easily implemented with the existing syntax.

**Comment by RichiCoder1** [comment]
@pdelvo  I agree with simply killing off `last`, or at least `last` with the behavior as it stands. I'm not sure what your second sentence is trying to say though.

**Comment by RichiCoder1** [comment]
@AdamSpeight2008 @fubar-coder My biggest issues with your samples is that, while they work and are very valid, they aren't at a language level which is the crux of this issue.

**Comment by pdelvo** [comment]
I was just trying to explain why it is not possible to come up with a version of foreach which does not call MoveNext() for the next iteration before the iteration. You would have to predict what MoveNext() is going to return at the end of the iteration. That is not computable. But calling it before the iteration is a breaking change. So the only last block I could think of would just be executed after the foreach is complete. And this does not look very usefull and its not really something we need a new syntax for. `first` and `once` however would be possible and usefull.first could even have some kind of else block and it could be used multiple times in the loop body.

**Comment by RichiCoder1** [comment]
The way I'm thinking about both `first` and `once` essentially boils them down to auto generated `if`s. Being able to `else` them seems perfectly valid to me. About the only bit that would need to be ironed out is `else if`, as that could possibly confuse someone.  `first` probably shouldn't accept an `else if` and I'm not sure how you'd address confusing around `else if`. I may be over thinking this though.

Now if only we could get a team member to weigh in :).

**Comment by bbarry** [comment]
What if the foreach expression was enhanced like this:


    foreach 
    (
        var item in items; 
        var index = index;
        var isFirst = once;
        var firstOfCondition = once && Condition(item) //; optional for last foreach statement declaration
        /*
        available contextual variables:
        index: auto generated index to enumerable
        once: true until after it successfully assigns true into a resulting variable per expression it is contained in
        */
    )
    ...

Any simple bool statements using `once` for conditions could be optimized by the compiler where appropriate (`if(IsFirst) {...} else {...}` for example) because the compiler can know that they will never be true a second time.

**Comment by aolszowka** [comment]
I would vote against adding such a language feature, I feel a LINQ extension method, as has been suggested here, should be written if this is a feature desired. If it should be a part of the BCL is up for debate as well in my mind. I do not see a valid use-case that an Extension method could not be used to fulfill the requirement.

As Raymond Chen states every feature starts out at -100 points, I don't see a convincing argument to get it over this initial hit.

FWIW I understand the example was probably chosen for simplicity, but in cases where you need to contact strings as the example above you should be using one of the overloads of String.Join (https://msdn.microsoft.com/en-us/library/System.String.Join%28v=vs.110%29.aspx) most have been available since .NET 4.0.

**Comment by MadsTorgersen** [comment]
Per #3912 we will probably never do this proposal. While we recognize the scenario, it is not worth adding special syntax for it.

**Comment by GSPP** [comment]
Most of the time such a loop is not required. 90% of those loops probably are string concatenations which are easily solved with string.Join. People just have to get into the habit of using LINQ-style data processing.

I can see the usefulness of indexed iteration as Nemerle has it. That said indexed iteration can be addressed with a helper method as well that converts an IE<T> to an IE<WithIndex<T>>.

**Comment by McZosch** [comment]
This should not be a language feature. The behavior can easily be applied by calling the LINQ-methods Take and Skip, or with the indexed signature of Select.

    foreach (var x in xs.Take(1)) {
        DoSomethngToFirst();
    }
    foreach (var x in xs.Skipt(1)) {
        DoSomethngToRest();
    }

**Comment by fubar-coder** [comment]
You example doesn't work as it creates two enumerators which may cause two SQL query executions, etc...

**Comment by McZosch** [comment]
... in which case you can still use the indexed signature of the Select extension, write your own extension or simply convert to a in-memory representation, which is better when handling data in multi-threaded environments anyway.

Still, there is no need for this feature, as some kind of bool evaluation has inevitably to be made and there are many ways to reduce verbosity here short of changing the language.
