### ISSUE TITLE
Separate Samples from Roslyn Repo.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#13100]
If the `sample` section of the repo was separated out into a new repo. The `restore.cmd` would a lot quicker. As it would only restore the roslyn compiler and features.
Are they actually required for compilation and unit testing?

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #63](https://github.com/dotnet/roslyn-sdk/issues/63) via [**ZenHub**](https://www.zenhub.com/)
