### ISSUE TITLE
Make "out" arguments optional while calling

### ISSUE THREAD

**Issue by pvenky** [dotnet/roslyn#13104]
Sometimes, I only care about the return value of a method that also has `out` arguments. A rather contrived example could be when I call `Double.TryParse(numberString, out value)` but only care about whether `numberString` can be parsed as a `double` but don't actually care about what the `value` is. In these cases, I have to declare a dummy variable like so
```
double dummy;
if (!Double.TryParse(numberString, out dummy))
  Console.WriteLine("Enter a number dummy!");
```
I've come across at least a few instances where I have had to choose between either creating overloaded methods that leave out the extra `out` arguments or having only one method signature (with an `out` argument) and creating dummy variables in some of the consumers. 

While `out` arguments are not constrained to be at the end of a method signature (like optional arguments are), the language spec requires the calling function to declare them as `out` when calling. So the only time a compiler will have trouble figuring out when to substitute a dummy variable will be when there are two consecutive `out` arguments of the same type and the calling function ignores one of them. For example,
```
public bool SplitRational(string rationalNumber, out int numerator, out int denominator)
{
  ....
}
public void DisplayNumerator(string rationalNumber)
{
  int n;
  if (SplitRational(rationalNumber, out n))
    Console.WriteLine($"The numerator is {n}");
  else
    Console.WriteLine("The given string is not a rational number");
}
```
In this case, you could use a syntax similar to optional arguments, where the caller can spell out the argument being matched, like `SplitRational(rationalNumber, out numerator:n);`

**Comment by HaloFour** [comment]
Implicitly treating `out` parameters as optional would likely cause issues and ambiguity with overload resolution.

With `out` variable declarations you will be able to do the following:

```cs
if (SplitRational(rationalNumber, out var n, out var d) {
    Console.WriteLine($"The numerator is {n}");
}
```

You'll still have to declare the variable for the `out` argument but it can at least be inline.

The pattern for defining such functions going forward will likely be to use tuples instead of `out` parameters anyway:

```cs
public (int numerator, int denominator)? SplitRational(string rationalNumber) {
}
```

**Comment by pvenky** [comment]
Yeah, didn't think through overload resolution. The inline `out` variable declarations do make it a little bit more convenient.
