### ISSUE TITLE
Roslyn on Windows 10 IoT Core

### ISSUE THREAD

**Issue by neaorin** [dotnet/roslyn#13135]
We would be interested in having the .NET compiler available on Windows 10 IoT Core running on ARM. (RPi and Minnowboard)

The use case revolves around a web-based IDE for IoT devices (using Blockly or similar) which would generate C# code to be passed on to the device, compiled and run.

If this is not currently possible, could we get a sense of the magnitude of effort involved?

thanks

**Comment by DavidArno** [comment]
There isn't yet a version of the .NET Core CLI that runs on Win 10 IoT with ARM. Until that happens, there's little point in trying to create a version of Roslyn that runs on that environment...
