### ISSUE TITLE
Parsing for out argument declarations needs to take deconstruction and ref returns into account

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13148]
Because we plan to support deconstruction for out arguments in the future

```cs
M(out var (x, y));
```

we need to ensure that we do not parse this as an invocation of a ref-returning method named `var` with two arguments. The syntax trees today can express the deconstruction, so we should parse it that way and emit a semantic error.

**Comment by HaloFour** [comment]
Nice!

**Comment by jcouv** [comment]
@gater, this made me wonder whether other parsing scenarios should be blocked to allow for future deconstruction. 
From the list I reviewed (see below), I think we're ok. Except for outvar, none of the punted scenarios currently allow for expressions.
Does that match your understanding?

- P0: local declaration, for statement, foreach (done in C# 7)
- P1: let clause, from clause,
- later: lambda, method declaration, using, outvar, join clause, query continuation clause, join into clause, catch.

**Comment by gafter** [comment]
@jcouv Yes, I agree we seem to be in good shape for future syntax extensions, other than out var.

**Comment by gafter** [comment]
We need to vet the implemented rule with the LDM (as it will need to be added to the language specification). I suspect the most likely rule the LDM will come up with is along the lines of "you're not allowed to have the out argument be an invocation of a method given by its simple name that is `var`."

I'm reopening this issue so that we can get an LDM decision and align it with the implementation.

**Comment by AlekseyTs** [comment]
The implemented rule is:
> you're not allowed to have the out argument be an invocation of a method given by its simple name that is "var" if all its arguments:
- are not named;
- do not have ref/out modifiers;
- are simple identifiers, or tuple literals without element names.

**Comment by gafter** [comment]
I suspect we will want to have similar rules for out arguments and deconstruction declarations. They are currently independent, unrelated implementations.

**Comment by gafter** [comment]
The LDM rule is the following:
In a syntactic position where an lvalue is expected, we parse `var (...)` as a deconstruction, no matter what `...` is. This specifically applies to
  - [ ] The left-hand-side of an assignment. The only syntactically valid form is as a deconstruction declaration statement; other forms are some kind of error. `var(1) = 2;`
  - [ ] In any expression, following `out` or `ref`. These should not bind (successfully) as an invocation.
    - [ ] In an argument position, like `M(out var (1))`
    - [ ] In a "ref expression", for example `ref int x = ref var(1);`.

As a practical matter, the language does not dictate the shape of the syntax trees, only what is legal and illegal, so we may elect to parse as an expression with some kind of syntax error.

**Comment by gafter** [comment]
@AlekseyTs Would you like to take this work, or shall I?

**Comment by AlekseyTs** [comment]
Sure, feel free to take it.

**Comment by gafter** [comment]
@AndyGerlicher Please stop

**Comment by alrz** [comment]
@gafter This doesn't apply to `(out let(a,b))` ? I thought `let` is reserved for readonly pattern variables.

**Comment by gafter** [comment]
@alrz There are no plans for anything having to do with `let` at this time.
