### ISSUE TITLE
IntelliSense does not display get-only abstract collection properties in object initializers

### ISSUE THREAD

**Issue by SolalPirelli** [dotnet/roslyn#13158]
**Version Used**: VS 2015 Update 3 (14.0.25425.01)

**Steps to Reproduce**:

1 - Write the following class:  

``` csharp
class C
{
    public IList<int> Items { get; }
}
```

2 - Instantiate it with an object initializer:  

``` csharp
var c = new C
{
};
```

3 - Move your cursor inside the initializer, and toggle IntelliSense (e.g. Ctrl+Space).

**Expected Behavior**: IntelliSense should display the `Items` property, since items can be added to it even though the property itself is read-only, e.g. `Items =  { 1, 2, 3 }`.

**Actual Behavior**: Nothing is displayed.

**Notes**:
- IntelliSense works as expected if `Items` is a `List<int>`, or if it has a `set` accessor.
- A real-life example of this is `Panel.Children` in XAML apps.

**Comment by Pilchie** [comment]
I thought you fixed this at some point in the past - did it regress?

**Comment by rchande** [comment]
This is not fixed. Here's another repro:

```C#
using System.Collections.Generic;

class C
{
    public IList<int> Items { get; }
    public int Foo;

    void M()
    {
        var c = new C
        {
            $$
        };
    }
}
```

At the `$$` `foo` shows up but Items does not.
