### ISSUE TITLE
Enable Code Analysis on Build Doesn't Work Properly

### ISSUE THREAD

**Issue by MelbourneDeveloper** [dotnet/roslyn#13152]
**Version Used**: 
Visual Studio 2015 Update 3

**Steps to Reproduce**:
1. Open up any existing project
2. Throw some code rules on and turn on 
3. Turn on "Enable code analysis on build"
4. Notice that sometimes turns on code rules, and sometimes it doesn't
5. Write some code that breaks the rules
6. Turn off "Enable code analysis on build"

**Expected Behavior**:
"Enable code analysis on build" should toggle code analysis on build on or off.

**Actual Behavior**:
The behaviour is random. Sometimes turning the checkbox off turns off code analysis on build, and sometimes it doesn't. Conversely, turning on the checkbox sometimes enables it, and sometimes it doesn't. We work predominantly in Silverlight, UWP, and .NET but it happens in all project types. This happens to us all the time. There is no consistency. So, we often resort to manually checking, or unchecking all the code rules in the code rule file.

All I am asking is that we be able to turn code analysis on build on or off. Please don't write this issue off without trying this yourself. Everyone says "oh but we've been using code rules for a long time - surely someone would have reported this by now". Well, I and my colleague get this problem all the time and it stops us from using code rules. This happens to us on several different computers.

**Comment by MelbourneDeveloper** [comment]
Haven't other people experienced this?

**Comment by MelbourneDeveloper** [comment]
This is really frustrating. I know that code rules often work, and I know that this checkbox often works so that there are times when you will not experience this problem. But, I can tell you that this is a major nightmare for me. It happens on multiple different machines, and across many different project types.

I know the immediate feeling is going to be "This can't be right because we would have noticed this by now". But, please resist that gut feeling. This is a problem.

**Comment by AceCoderLaura** [comment]
I also experience issues with code rules. Code rules will stay turned on when the checkbox is unchecked and will still be ran on generated files even when it's been told not to. Code rules need an overhaul in Visual Studio.

**Comment by MelbourneDeveloper** [comment]
This is still a problem. Even the latest versions of Visual Studio 2017. Do people even care about code rules working?

**Comment by jmarolf** [comment]
@MelbourneDeveloper  is sounds like you are running into issues with FxCop analysis.  Are you using ruleset files to configure FxCop or are you using roslyn analyzers?

**Comment by MelbourneDeveloper** [comment]
@jmarolf , I'm just using code rules inside Visual Studio. This was an issue in Visual Studio 2015, and is still an issue in Visual Studio 2017. The problems with code rules are different depending on which type of project you are trying to build for. 

It's as though nobody cares about, or tests code rules. We are attempting to bring code quality to our code base, but code rules have never worked properly. 

For example, the latest .NET Standard 2.0 projects don't even support code rules. You can't even edit them properly inside Visual Studio. With Xamarin Forms if you have XAMLC pages code rules will break the compile every second time you build. I'm not even joking. Every second time you will get a compilation error.

It's always the same story. Code rules are the last part of Visual Studio to get attention and they never work properly. Is anyone ever going to test this area of the system and fix the bugs?

**Comment by jmarolf** [comment]
@MelbourneDeveloper when you say 'code rules' you mean using this dialog?

![image](https://user-images.githubusercontent.com/9797472/37123005-80c3672c-2217-11e8-862a-fcf671dfa689.png)

Which rule sets are you using?  I assume that this is in a Xamarin app.

**Comment by MelbourneDeveloper** [comment]
@jmarolf is anybody looking at this?

**Comment by jmarolf** [comment]
@jinujoseph for triage.  

> CA0055 : Could not identify platform for 'C:\Users\chris\documents\visual studio 2017\Projects\CodeRules\CodeRules\bin\Debug\netstandard2.0\CodeRules.dll'

Haven't seen this before, perhaps this is bug with https://github.com/dotnet/project-system?

>It shouldn't build because it breaks code rules, but they are ignored anyway

@MelbourneDeveloper is running into the issue where IDE only errors won't fail a commandline build.

**Comment by MelbourneDeveloper** [comment]
@jmarolf I'm not sure if things are getting communicated properly here. The first problem is that code rules are completely broken for .NET Standard 2.0 projects in Visual Studio. There are a slew of older problems with code rules not working properly in Visual Studio, but it's hardly worth tackling them until we can at least get code rules working in .NET Standard 2.0. They were never stable enough to use in 1.6 either.

**Comment by jmarolf** [comment]
@MelbourneDeveloper can you please give a example Xamarin project demonstrating the problem?

**Comment by MelbourneDeveloper** [comment]
@jmarolf  I posted the .NET Standard 2.0 project a few posts ago.

https://www.dropbox.com/s/gqqy49qnyvux2l2/CodeRules.7z?dl=0

I don't know if you realize but .NET Standard libraries are common assembly format for all Xamarin projects. This isn't a Xamarin project specifically, but we need to use this project format for shared code. I have a Xamarin Forms project and 5 out of 8 projects are .NET Standard 2.0

**Comment by jmarolf** [comment]
@ MelbourneDeveloper alright thanks!  My assessment stands then.  There appear to be two separate bugs here that need to be looked at.
1.  CA0055 : Could not identify platform (Haven't seen this before)
2. IDE only errors won't fail a commandline build (This is actively being worked on)

**Comment by MelbourneDeveloper** [comment]
@jmarolf The original bug still stands. We still use Visual Studio 2015 Update 3, and that bug is still there. Basically, the "Enable code analysis on build" often doesn't work properly. I.e. we get compilation errors based on code rules even when "Enable code analysis on build" is turned off. We often need to physically change the list of the rules in the project drop down list to allow the project to compile.

But, **_# the most serious bug_** is that **_we have NO code rules for .NET Standard 2.0_**. This is a well known issue and has been logged elsewhere. If you want me to create a new issue, I can.

As for your point:

> 2. IDE only errors won't fail a commandline build (This is actively being worked on)

I have no idea what you are talking about.  I never said anything about building at the command line. The problems are all in Visual Studio. I've never tried building at the command line.

**Comment by MelbourneDeveloper** [comment]
@jmarolf , I should point out that the original bug was logged in August 2016, and nothing has ever been done about it. I doubt that anyone even believes me when I tell them that the "Enable code analysis on build" often doesn't work.

What's necessary here is for someone to go over the code rules inside Visual Studio with a broom, test and fix until it all works properly. **_At the moment, it's all essentially useless to us._**

**Comment by jmarolf** [comment]
@MelbourneDeveloper took a look at this today and found the following problems.  Does this match your experience?

Version Used: **Visual Studio 2017.6**
Repo steps:
1. Create .NET Standard Library 
![image](https://user-images.githubusercontent.com/9797472/37810327-b63bd812-2e10-11e8-941e-2f259f15790f.png)
**FIRST BUG**: There is no way to access the ruleset editor from a netstandard project and there is no "Code Analysis" tab in project properties
![image](https://user-images.githubusercontent.com/9797472/37810368-ec9366be-2e10-11e8-9222-df9cb01999d3.png)

1. Copy in `CodeRules.ruleset` contained in [this](https://www.dropbox.com/s/gqqy49qnyvux2l2/CodeRules.7z) zip file into the same directory as the project
1. Edit the csproj file
![image](https://user-images.githubusercontent.com/9797472/37810392-0e8aa246-2e11-11e8-9581-df14ea3d1a8f.png)
1. Change you project file to appear like the following:
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <CodeAnalysisRuleSet>CodeRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

</Project>
```
**NOTE**: I get errors in the error-list as soon as the `ruleset` file is added to the project telling me I have unnecessary using directives.
![image](https://user-images.githubusercontent.com/9797472/37810584-2751094a-2e12-11e8-87ac-4cc264931c53.png)

5.  Change the project file to disable code analysis
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RunCodeAnalysis>false</RunCodeAnalysis>
    <CodeAnalysisRuleSet>CodeRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

</Project>
```
**SECOND BUG**: Even though `RunCodeAnalysis` is set to `false` the errors will still appear in the error list.
**THIRD BUG**: As soon as you add the `RunCodeAnalysis` property to the project you will get the following errors
```
CA0055 : Could not identify platform for 'C:\Users\jmarolf\source\repos\ClassLibrary6\ClassLibrary6\bin\Debug\netstandard2.0\ClassLibrary6.dll'. 
CA0052 : No targets were selected.
```
**NOTE**: Looking at the build log this error is coming from `FxCopCmd.exe` which was not updated to understand netstandard assemblies
```ini
Target Name=RunCodeAnalysis Project=ClassLibrary6.csproj
     Building target "RunCodeAnalysis" completely.
     Output file "bin\Debug\netstandard2.0\ClassLibrary6.dll.CodeAnalysisLog.xml" does not exist.
    
        CodeAnalysisReferencePath
            C:\Users\jmarolf\.nuget\packages\netstandard.library\2.0.1\build\netstandard2.0\ref\Microsoft.Win32.Primitives.dll
            C:\Users\jmarolf\.nuget\packages\netstandard.library\2.0.1\build\netstandard2.0\ref\mscorlib.dll
            C:\Users\jmarolf\.nuget\packages\netstandard.library\2.0.1\build\netstandard2.0\ref\netstandard.dll
            ...

     Task "Copy" skipped, due to false condition; ('$(OutputType)'=='winmdobj' and '$(Language)'=='VB') was evaluated as ('Library'=='winmdobj' and 'C#'=='VB').
     Task "Copy" skipped, due to false condition; ('$(OutputType)'=='winmdobj' and '$(Language)'=='VB') was evaluated as ('Library'=='winmdobj' and 'C#'=='VB').
    CodeAnalysis
        Assembly = C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\CodeAnalysis\.\FxCopTask.dll
        CommandLineArguments = C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Team Tools\Static Analysis Tools\FxCop\FxCopCmd.exe  /outputCulture:1033 /out:"bin\Debug\netstandard2.0\ClassLibrary6.dll.CodeAnalysisLog.xml" /file:"bin\Debug\netstandard2.0\ClassLibrary6.dll" /reference:"..." /directory:"C:\Users\jmarolf\.nuget\packages\netstandard.library\2.0.1\build\netstandard2.0\ref" /ruleSet:"=C:\Users\jmarolf\source\repos\ClassLibrary6\ClassLibrary6\CodeRules.ruleset" /rulesetdirectory:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Team Tools\Static Analysis Tools\\Rule Sets" /rule:"-C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Team Tools\Static Analysis Tools\FxCop\\Rules" /searchgac /ignoreinvalidtargets /forceoutput /successfile /ignoregeneratedcode /saveMessagesToReport:Active /targetframeworkversion:v2.0 /timeout:120 /reportMissingIndirectAssemblies 
        Parameters
            AnalysisTimeout = 120
            ApplyLogFileXsl = False
            Assemblies = bin\Debug\netstandard2.0\ClassLibrary6.dll
            FailOnMissingRules = False
            FilesWritten
                bin\Debug\netstandard2.0\ClassLibrary6.dll.CodeAnalysisLog.xml
                bin\Debug\netstandard2.0\ClassLibrary6.dll.lastcodeanalysissucceeded
            ForceOutput = True
            GenerateSuccessFile = True
            IgnoreGeneratedCode = True
            IgnoreInvalidTargets = True
            IgnoreMissingIndirectReferences = False
            LogFile = bin\Debug\netstandard2.0\ClassLibrary6.dll.CodeAnalysisLog.xml
            MSBuildProjectDirectory = C:\Users\jmarolf\source\repos\ClassLibrary6\ClassLibrary6
            OutputToConsole = False
            OverrideRuleVisibilities = False
            Quiet = False
            References
                C:\Users\jmarolf\.nuget\packages\netstandard.library\2.0.1\build\netstandard2.0\ref\Microsoft.Win32.Primitives.dll
                C:\Users\jmarolf\.nuget\packages\netstandard.library\2.0.1\build\netstandard2.0\ref\mscorlib.dll
                C:\Users\jmarolf\.nuget\packages\netstandard.library\2.0.1\build\netstandard2.0\ref\netstandard.dll
                ...
            RuleDirectories = C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Team Tools\Static Analysis Tools\FxCop\\Rules
            RuleSet = CodeRules.ruleset
            RuleSetDirectories = C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Team Tools\Static Analysis Tools\\Rule Sets
            SaveMessagesToReport = Active
            SearchGlobalAssemblyCache = True
            SuccessFile = bin\Debug\netstandard2.0\ClassLibrary6.dll.lastcodeanalysissucceeded
            Summary = False
            TargetFrameworkVersion = v2.0
            ToolPath = C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Team Tools\Static Analysis Tools\FxCop\
            TreatWarningsAsErrors = False
            UpdateProject = False
            Verbose = False
         Running Code Analysis...
         Microsoft (R) FxCop Command-Line Tool, Version 15.0 (15.0.27520.0) X86
         Copyright (C) Microsoft Corporation, All Rights Reserved.
         Loaded dataflowrules.dll...
         Loaded designrules.dll...
         Loaded globalizationrules.dll...
         Loaded interoperabilityrules.dll...
         Loaded maintainabilityrules.dll...
         Loaded mobilityrules.dll...
         Loaded namingrules.dll...
         Loaded performancerules.dll...
         Loaded portabilityrules.dll...
         Loaded reliabilityrules.dll...
         Loaded securityrules.dll...
         Loaded securitytransparencyrules.dll...
         Loaded usagerules.dll...
         Could not identify platform for "C:\Users\jmarolf\source\repos\ClassLibrary6\ClassLibrary6\bin\Debug\netstandard2.0\ClassLibrary6.dll".
         * Analysis was not performed; at least one valid rules assembly and one valid
         target file must be specified.
         * 1 total analysis engine exceptions.
         Writing report to C:\Users\jmarolf\source\repos\ClassLibrary6\ClassLibrary6\bin\Debug\netstandard2.0\ClassLibrary6.dll.CodeAnalysisLog.xml...
         Done:00:00:00.4704436
        Errors
            CA0055 : Could not identify platform for "C:\Users\jmarolf\source\repos\ClassLibrary6\ClassLibrary6\bin\Debug\netstandard2.0\ClassLibrary6.dll". [C:\Users\jmarolf\source\repos\ClassLibrary6\ClassLibrary6\ClassLibrary6.csproj]
            CA0052 : No targets were selected. [C:\Users\jmarolf\source\repos\ClassLibrary6\ClassLibrary6\ClassLibrary6.csproj]
         Code Analysis Complete -- 2 error(s), 0 warning(s)
        OutputItems
            FileWrites = bin\Debug\netstandard2.0\ClassLibrary6.dll.CodeAnalysisLog.xml
    TargetOutputs
        bin\Debug\netstandard2.0\ClassLibrary6.dll.CodeAnalysisLog.xml
        bin\Debug\netstandard2.0\ClassLibrary6.dll.lastcodeanalysissucceeded
```

**Comment by MelbourneDeveloper** [comment]
@jmarolf , correct. This is the issue that .NET Standard 2.0 doesn't support code rules (or the code rules don't support .NET Standard 2.0). The steps you followed are exactly the same steps I followed to create the sample app.

But, this is only the starting point. This could be logged as a separate bug.

**Comment by MelbourneDeveloper** [comment]
@jmarolf  is anyone looking in to this?

**Comment by mavasani** [comment]
This is now resolved. Code Analysis page has been added in 16.3 and they direct users to use source based FxCopAnalyzers NuGet package rather then use legacy post-build FxCop binary analysis.
