### ISSUE TITLE
Committing a VB generic completion item includes the elipsis text

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#13161]
**Version Used**: A private build from master (f93cffec394e1bfbf1467a3c370fb286b52e3a70), running in VS2015 update 3.

**Steps to Reproduce**:

```
Interface Foo(Of T)
End Interface

Class Bar
    Implements $$
End Class
```

Bring up the completion list at $$, select `Foo(Of ...)` and press `TAB` to commit the selection. The same issue also happens if `CTRL`+`SPACE` is used to complete a partially typed identifier.

**Expected Behavior**: `Implements Foo(Of$$`

**Actual Behavior**: `Implements Foo(Of ...)$$`

**Comment by lorcanmooney** [comment]
Problem 2 is because the insertion text for generic symbols is [not valid code](https://github.com/dotnet/roslyn/blob/f93cffec394e1bfbf1467a3c370fb286b52e3a70/src/Features/VisualBasic/Portable/Completion/CompletionProviders/CompletionUtilities.vb#L106).

**Comment by lorcanmooney** [comment]
@CyrusNajmabadi: I can try and fix this if you'd like?

**Comment by CyrusNajmabadi** [comment]
Absolutely!

**Comment by Pilchie** [comment]
Thanks @lorcanmooney.  I saw this on a plane last week and found it very annoying.  I even had a todo-list entry to file the bug :smile:

**Comment by Pilchie** [comment]
@lorcanmooney feel free to continue looking at this, just assigning so we don't lose track of it.

**Comment by lorcanmooney** [comment]
@Pilchie @CyrusNajmabadi It looks like I bit off more than I could chew. The two issues have completely separate root causes (I had assumed they were related). The double `]` commit issue is compounded by some bad test code, and I'm honestly not sure what the correct product-code fix would be so I've split it off into #13412.

I have a fix for the generic ellipses issue, and I hope to submit a PR this weekend.

**Comment by rchande** [comment]
@lorcanmooney Thanks for the PR!

@rchande Review the PR and see if it fixes the issues.

**Comment by Pilchie** [comment]
Fixed!
