### ISSUE TITLE
[Idea] Object Initializers with comments

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#13167]
``` vb.net
_view = New TopLevelControl() With
          {
            .BackColor = SystemColors.Window,
            .Name = "DesignerWindowPaneBase View",
            .Text = "DesignerWindowPaneBase View"
          }
```

I propose the we should allow comments within the object initilizer.

``` vb.net
_view = New TopLevelControl() With
          {
            .BackColor = SystemColors.Window,
            ' For debugging purposes.
            .Name = "DesignerWindowPaneBase View",
            .Text = "DesignerWindowPaneBase View"
          }
```

**Comment by Joe4evr** [comment]
Should probably be noted that it works in C#
![commentininitializer](https://cloud.githubusercontent.com/assets/1058562/17661047/12b8b250-62dd-11e6-8831-2926ff5b885f.png)
Trying it in VB gives syntax errors and a fight with the formatter.

**Comment by HaloFour** [comment]
It's not limited to initializers.  VB doesn't allow comments on their own line between two parts of a statement separated by a line continuation (implied or explicit).  You can easily recreate the same behavior with LINQ statements.

**Comment by AdamSpeight2008** [comment]
It does allow comments after parametes and on the end of LINQ statements.
```vb
    Sub Main()
        Dim numbers = System.Linq.Enumerable.Range(0,1000)
        Dim odds = From number in numbers ' A Number
			        Where number Mod 2 = 0 ' Check To See if it odd
        			Select number

    End Sub
```

**Comment by Joe4evr** [comment]
Just FYI, `n % 2 == 0` gives you **even** numbers, not **odds**.

**Comment by AdamSpeight2008** [comment]
@Joe4evr  Was an intentional error. :whistle:

**Comment by HaloFour** [comment]
@AdamSpeight2008 It does at the end of the line with initializers too:

```vb
_view = New TopLevelControl() With
          {
            .BackColor = SystemColors.Window, ' For debugging purposes.
            .Name = "DesignerWindowPaneBase View",
            .Text = "DesignerWindowPaneBase View"
          }
```

So it seems like a general parsing rule when it comes to comments and line continuations.  And allowing comments after implicit line continuations was new with VS2015.

**Comment by AdamSpeight2008** [comment]
@HaloFour The comment isn't associated with '.BackColor = SystemColor.Window,` but the two entries that follow.

**Comment by AdamSpeight2008** [comment]
[Duplicate]( https://github.com/dotnet/vblang/issues/21)
