### ISSUE TITLE
Make FileBasedXmlDocumentationProvider public

### ISSUE THREAD

**Issue by aelij** [dotnet/roslyn#13169]
Currently there is no pubic API that allows constructing an XML-based `DocumentationProvider`.

I would've personally preferred a static method, e.g. `DocumentationProvider.FromXmlFile()` but seeing how the implementation classes are spread across multiple assemblies, it's probably not possible.

Another option is to make `IDocumentationProviderService` public.

cc: @jasonmalinowski

**Comment by jasonmalinowski** [comment]
This is a duplicate of #1465.

**Comment by aelij** [comment]
Oh, sorry! I did a search but the name of the class is different in that PR.  I see it's marked up for grabs.
