### ISSUE TITLE
Proposal: Multiple comparison operators in an expression

### ISSUE THREAD

**Issue by ygoe** [dotnet/roslyn#13170]
To check whether a value is within a range, one must do this now:

    if (value >= minValue && value <= maxvalue) { }

It would be easier to read if this was allowed:

    if (minValue <= value <= maxValue) { }

The compiler could take all comparison operators and combine them with an AND expression. Here's the proposed order to be generated by the compiler:

    if (minValue <= value && value <= maxValue) { }

This could be extended to an arbitrary number of comparisons:

    if (a < b < c < d < e) { }

Would result in:

    if (a < b && b < c && c < d && d < e) { }

Does that sound reasonable?

I understand that this syntax is currently invalid because `a < b` evaluates to `bool` and there is no comparison operator overload for `bool` and the type of `c` (which is normally not `bool`). It would be the compiler's task to figure this out.

This might be restricted to sequences of the same comparison operator direction, so this should be allowed:

    a <= b < c <= d < e

While this may not make sense:

    a < b > c < d >= e

**Comment by HaloFour** [comment]
Similar to #136.

**Comment by ygoe** [comment]
Didn't find that issue. It's interesting to see that Python can do this.
