### ISSUE TITLE
VSI runs timing out due to sign in dialog

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#13189]
See http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_open_prtest/399/artifact/Open/Binaries/Release/Screenshots/2016-08-15_18-09-56_29%20-%20Exception%20System.Exception.png

@jasonmalinowski We need to sign in with the 1 year license to stop this re-occurring every month?

**Comment by jasonmalinowski** [comment]
@mavasani That implies more that the profile got wiped if it went back to that point. What's the history of the machine?

**Comment by mavasani** [comment]
I am not sure, but I saw another failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_prtest/558/artifact/Open/Binaries/Release/Screenshots/2016-08-17_19-52-04_39%20-%20Exception%20System.Exception.png

Both the failures seem to be on dci-win-mbld-7

**Comment by mavasani** [comment]
I have reset the profile on that machine.
