### ISSUE TITLE
C#7 local function generated structures shouldn't be declared as static

### ISSUE THREAD

**Issue by psmacchia** [dotnet/roslyn#13191]
**Version Used**: dev15 preview 3

**Steps to Reproduce**: I compile code from [this blog post](http://druss.co/2016/04/c-7-0-local-functions/).

```
private static void Main(string[] args)
{
    int localVar = 42;
    int LocalFunction(int arg)
    {
        return localVar * arg;
    }
    Console.WriteLine(LocalFunction(1));
}
```

**Actual Behavior**: The structure generated under the wood by the compiler to handle `localVar ` **is declared as static** (and the field `localVar` is a non-static field)

**Expected Behavior**: Such generated structure shouldn't be declared as static.

As the developer of a [static analyzer](http://www.ndepend.com/) that churns IL code this matters. Unless there is a real technical reason for declaring such structure as static, it'd be cleaner to not do so.

-------------

Note: Reflector see the structure as a static class that derives from value type (it is a Reflector bug that it doesn't tell it is a structure).

![capture](https://cloud.githubusercontent.com/assets/511445/17694802/e802f998-63a5-11e6-841a-0f3d7752b16a.png)

Our static analyzer that relies on [Ceci](https://github.com/jbevain/cecil)l for IL read, shows that the generated structure is both abstract and sealed (which means static).

![capture](https://cloud.githubusercontent.com/assets/511445/17694959/adc93a70-63a6-11e6-9d77-6f75b5911a4c.png)

**Comment by svick** [comment]
As far as I can tell, the tools are confused, because the type is marked as abstract. Somehow, CLR (and peverify) doesn't mind and treats it as a normal `struct`.

I think this is a bug, so I have submitted a PR to fix it.

**Comment by gafter** [comment]
@agocke a community member has submitted a PR to fix this.

**Comment by psmacchia** [comment]
FYI I tested with VS2017 RC and the bug is indeed fixed, thanks
