### ISSUE TITLE
Roslyn is not resolving a type at design time; compiles correctly

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn#13195]
**Version Used**: 
VS 2015 Update 3

**Steps to Reproduce**:

1. Open the attached solution.
2. Go to TestExecutionSinkTests.cs in the test.xunit.runner.utility project\Visitors.
3. At the bottom, look at the TestableTestExecutionSink class

**Expected Behavior**:
All types should resolve correctly

**Actual Behavior**:
![img](https://cloud.githubusercontent.com/assets/1427284/17706420/f3d01a72-63a9-11e6-84c9-2c7ebdacba86.png)
[xUnit.zip](https://github.com/dotnet/roslyn/files/420722/xUnit.zip)

**Comment by davkean** [comment]
This is an xproj project - it's very likely an issue between xproj project system and their design-time host, I suspect https://github.com/aspnet/Tooling would be a better place to file this.

**Comment by Pilchie** [comment]
Closing based on @davkean's comment above.
