### ISSUE TITLE
Anonymous types in VB do not include the module name, so cannot be combined into netmodules

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#1319]
See C# test `MultipleNetmodulesWithAnonymousTypes`

A similar test for VB will likely reveal a problem that needs to be fixed.

**Comment by AlekseyTs** [comment]
It looks like module names are included. I added a unit-test.

**Comment by AlekseyTs** [comment]
@gafter Please verify.

**Comment by gafter** [comment]
You have already verified that the issue had been fixed previously.

**Comment by AlekseyTs** [comment]
As long as you agree that there is nothing more to fix here. :-) Thanks.
