### ISSUE TITLE
[Proposal] try-catch expressions

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#132]
#### Problem
This is one of the issues when a small change to logic significantly changes code structure.
Let's say I have the following:

```csharp
var x = Get();
Use(x);
```

Now I decide I want to handle `Get()` exceptions here (of course, separately from `Use()`).
My code becomes:

```csharp
TypeOfX x;
try {
    x = Get();
}
catch (Exception ex) {
    throw new MuchBetterException("MuchBetterMessage", ex);
}
Use(x);
```

Now the `x` is separated from its definition, I can't use `var`, etc.

#### Potential solution

Provide an expression from of `try`, for example:

```csharp
var x = try Get() catch (Exception ex) {
    throw new MuchBetterException("MuchBetterMessage", ex);
}
Use(x);
```

or maybe even
```csharp
var x = Get() catch (Exception ex) {
    throw new MuchBetterException("MuchBetterMessage", ex);
}
Use(x);
```

##### Pros:
1. Makes code structure clearer.
2. Allows `var`.

##### Cons:
1. What if exception handling isn't a single-line expression? `{}` syntax allows for it, but what if we wanted to return a value for `x`? `return` there would be super-confusing, but there is no other way in current C# to achieve something like that.

#### Other thoughts
If `Cons` are resolved somehow, I would love to see it for `switch` and other statements as well.

**Comment by omariom** [comment]
@ashmind, what do you think about this:

``` C#
var value1 = Catch(Get , 33);
var value2 = Catch(()=> Get(123) , ex => ex is TimeoutException ? 33 : 22);
var value3 = Catch(Get , ex => { throw new Exception("MuchBetterMessage", ex);});


public Func<T> Catch<T>(Func<T> value, T fallbackValue)
{
	return Catch(value, ex => fallbackValue);
}

public Func<T> Catch<T>(Func<T> value, Func<Exception, T> exHandler)
{
	return ()=>
	{
		try
		{	        
			return value();
		}
		catch (Exception ex)
		{
			return exHandler(ex);
		}
	};
}
```

**Comment by ashmind** [comment]
@omariom I think it is a fair approach, but having this kind of thing on language level would make it available and consistent for everyone -- I don't really see many people using language-construct-libs at the moment. Also as it is this does not provide a way to rethrow the exception while preserving the stack (can be done, but makes it more complex).

**Comment by XuTpuK** [comment]
I met similar problem and I think problem of this verbosity is "braces conception". Somewhere (like in "if {}" braces make REAL block, which wraps local piece of functionality. But in case of "try {}" these braces just mark portion of operators (in the same scope!) which should be "guarded". But language architectors doesn't bother with that and declare ANY braces as a "block". Probably something should be done to avoid this simplification and look at language constructs more deep.
Anyway, this or other way we should make try{}catch things more simple.

**Comment by alrz** [comment]
:+1:

This would prevent a huge `try` block or many nested ones and a level of indentation, instead you can write a specific `catch` for each function, e.g.
```
var a = F() catch {
 ..
}

var b = F() catch {
 ..
}
```
Perhaps endpoint of the embedded-statement after `catch` should not be reachable like `else` in `let` (#6400)? I wonder how this would work with the `let .. when .. else` statement altogether.

**Comment by HaloFour** [comment]
Would this be limited strictly to a single `catch` block?  Otherwise I'm not sure you'd avoid the ambiguity in associating each `catch` block to its correct `try` block if this expression were to be within a nested `try` statement.

**Comment by alrz** [comment]
@HaloFour I don't see how this can be ambiguous.
```cs
try {
  result = F() catch(E1) { ... } catch(E2) { ... }
} catch {
  result = G() catch { ... }
}
```
However, it shouldn't be a `try ... catch` *expression* I think, because it might encourage skipping exceptions everywhere, for example, 
```cs
F(try G() catch ... lasagna... )
```
Now that think about it, something like Swift's `try?` also has this problem. This probably should be integrated to a variable declaration construct, like `let`.
```cs
let result = F() catch {
  // ...
} 
```
Not sure what rules should be defined around that block to cover multiple `catch`es or the use case in my previous comment.

**Comment by MadsTorgersen** [comment]
The main problem with an example along the lines of `var x = try expr catch (...) { ... }` or (syntactical variations thereof) is that `x` wouldn't be definitely assigned after the expression, unless you require the catch block itself throws, or you give it some way to affect the outcome of the try expression.

Should a new proposal address those issues, we'd still need to consider whether this is worthwhile to spend language surface area on. I currently think it is not.
