### ISSUE TITLE
Remove project dependencies added in PR 12644.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#13207]
PR #12644 added some dependencies that bloated our VSIX packages, specifically commits e0ed02200b57918aaf8a21e5b9a4e126505297b0 and f01d7dddd0c02767e32c5ea1dd94142bca504eff.  The P2P ref added in the first commit doesn't appear to be required and can likely be removed, but the P2P ref added in the second commit looks like it was added to support the `FindAllReferencesUtilities.DefinitionDisplayFormat()` method.

These project references need to be removed, either through file linking or other refactoring to reduce the dependencies getting packaged into the VSIX during build.

**Comment by brettfo** [comment]
For reference, look at internal build `20160805.3` where `ExpressionEvaluatorPackage.vsix` is correct and build `20160808.2` where there are extra files.

**Comment by tannergooding** [comment]
@brettfo, @CyrusNajmabadi. Why not just add `<Private>False</Private>`, so that the project binary isn't included in the VSIX?
