### ISSUE TITLE
"IntroduceVariable" refactoring does not preserve empty line above local declaration

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#13218]
**Steps to Reproduce**:
Apply refactoring "Introduce local for all occurrences of 'string.Empty'

**Code Before**:

``` csharp
public class Foo
{
    public void Bar(string s)
    {
        s = null;

        Bar(string.Empty);

        s = string.Empty;
    }
}
```

**Code After**:

``` csharp
public class Foo
{
    public void Bar(string s)
    {
        s = null;
        var empty = string.Empty;
        Bar(empty);

        s = empty;
    }
}
```

**Expected Behavior**:
Empty line above local declaration should be preserved

**Actual Behavior**:
Empty line above local declaration is removed

**Comment by JosefPihrt** [comment]
I would suggest to copy leading trivia from from next statement to local declaration statement.

https://github.com/dotnet/roslyn/blob/master/src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs#L311-L312

**Comment by keyboardDrummer** [comment]
I'm wondering what the desired behavior here is. When introducing a local for a single occurrence, then the leading trivia of the 'next' statement is moved to the leading trivia of the local declaration. Is this also the desired behavior for the 'all occurrences' case, which is what @JosefPihrt suggests?

Alternatively, we could place the leading trivia of the next statement between the local declaration and the next statement. The reported issue is then resolved by adding a NewLine as trailing trivia on the local declaration.

Any comments?
