### ISSUE TITLE
Feature docs refer to a non-existant version of VS15

### ISSUE THREAD

**Issue by DavidArno** [dotnet/roslyn#13217]
According to the docs at https://github.com/dotnet/roslyn/tree/master/docs/features, they can be experimented with using "dev15 preview 4". Yet the latest preview of VS15 available is [preview 3](https://www.visualstudio.com/downloads/visual-studio-next-downloads-vs). Is this a mistake in the docs, or have they simply been updated before preview 4 has been released? If latter, when will preview 4 be available?

**Comment by miloush** [comment]
Well since you can't experiment with them using preview 3, it's probably correct. I don't think anyone would be able to tell you when will future previews become available.

**Comment by gafter** [comment]
@DavidArno We're not allowed to make promises about future events, sorry.

**Comment by DavidArno** [comment]
@gafter, completely understand. However, it seems sensible therefore to update the docs to explain that Preview 4 hasn't yet been released and that to test out the features, one needs to either wait for the release, or fork/clone/build/run that master branch here.
