### ISSUE TITLE
Design a Roslyn symbol API for virtual tuple elements

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13229]
To determine if a field is virtual, what its index is, etc.

**Comment by jcouv** [comment]
Per our latest design discussion with Vlad and Aleksey, we would give named elements an odd index (a=1, b=3, c=5) and default elements an even index (Item1=2, Item2=4, Item3=6). Other members and fields will get negative indices.

The TupleElementFields should be updated accordingly. For (int a, int, int c), it should return three fields: one for a, one for Item2 and one for c. We could consider making this API internal only.
The comments in the various tuple fields types should be reviewed and updated accordingly.

Relates to this PR: #13463

**Comment by gafter** [comment]
Encoding information into odd/even/positive/negative that way is not suitable for a public API.

**Comment by jcouv** [comment]
The following two public APIs were added in #14958.
```
Microsoft.CodeAnalysis.INamedTypeSymbol.TupleElements.get -> System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.IFieldSymbol>
Microsoft.CodeAnalysis.IFieldSymbol.CorrespondingTupleField.get -> Microsoft.CodeAnalysis.IFieldSymbol
```

The `TupleElements` array gives back elements and their position is clear.  
For `(int Alice, int)` you will get two elements back (there can be no nulls).
If you get `CorrespondingTupleField` on the first one (`Alice`), you will get a default element back (for `Item1`). 
If you get `CorrespondingTupleField` on the second (`Item2`), you will get a self-reference back (`Item2`).

FYI @VSadov to double-check. I'll close the issue now.
