### ISSUE TITLE
IDE1005 (delegate invocation can be simplified) is shown in project with C# 4

### ISSUE THREAD

**Issue by dogfuntom** [dotnet/roslyn#13226]
**Version Used**: 
Visual Studio 14.0.25425.01 Update 3

**Steps to Reproduce**:

1.  Create a C# project.
2.  Add `<LangVersion>4</LangVersion>` in a valid place inside its *.csproj file.
3. Write a method like this:
```
        private void Foo()
        {
            var callback = new System.Action(() => { });
            var handler = callback;
            if (handler != null)
                handler();
        }
```

**Expected Behavior**:
No IDE1005 message, because C# 4 doesn't support ?. operator.

**Actual Behavior**:
The IDE shows IDE1050, suggests to change to this:
```
        private void Foo()
        {
            var callback = new System.Action(() => { });
            callback?.Invoke();
        }
```

**Comment by Pilchie** [comment]
I had thought there was bug about this before, but I couldn't find it.
