### ISSUE TITLE
CodeAnalysisRulesetEditor.xml encounters VS hang sometimes.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#13225]
CodeAnalysisRulesetEditor.xml test encounters VS hang. 

See this result: 
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_prtest/573/consoleFull#-16758747638101fac1-935e-4556-95f9-7a0e25ca0b52

Logs:

```
11:08:59 Executing test 18 of 27: CodeAnalysisRulesetEditor.xml failed
11:46:21 
Build timed out (after 120 minutes). Marking the build as aborted.
```

**Comment by mavasani** [comment]
@jasonmalinowski has a PR to fix this: https://github.com/dotnet/roslyn-internal/pull/1285

**Comment by srivatsn** [comment]
@jasonmalinowski can we get that PR merged?

**Comment by jasonmalinowski** [comment]
It's not clear to me if it actually helped. :frowning:

**Comment by Pilchie** [comment]
We wouldn't fix this in Escrow without understanding the customer scenario, so moving to 2.1

**Comment by jasonmalinowski** [comment]
This test is dead.
