### ISSUE TITLE
The `ICompletionSet` interface was modified and will break VS during the next insertion

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#13222]
The `ICompletionSet` interface was modified in this commit: https://github.com/dotnet/roslyn/commit/79aaec005f82f9a7abc2519bea00c84844bbfc29.

This will break VS during the next insertion. Causing the following dialog to appear anytime completion is attempted.

![image](https://cloud.githubusercontent.com/assets/10487869/17747474/cf2d3586-6469-11e6-9295-d7fae72381aa.png)

A fix needs to be prepped and given to @dotnet/roslyn-infrastructure for inclusion with the next insertion.

**Comment by tannergooding** [comment]
This may have been a side-effect of a Willow upgrade. It seems that extensions installed in the local hive are not overriding the globally installed extensions.

**Comment by CyrusNajmabadi** [comment]
I don't understand.  What did the insertion include?  All downstream consumers of this API should have been fixed up.

**Comment by CyrusNajmabadi** [comment]
Yes, that sounds much more likely.  I don't think this has anything to do with me.

**Comment by CyrusNajmabadi** [comment]
Note: 

1. I'm on vacation.
2. This seems unlikely to be actually anything related to my work.

As such, i would advise assigning to someone else if this really is urgency-soon.

**Comment by tannergooding** [comment]
I've confirmed this was a side effect of a build-to-build upgrade in Willow. Closing the issue.
