### ISSUE TITLE
Squiggles disappear on invoking code fix

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#13233]
**Version Used**: 
Latest Roslyn bits

**Steps to Reproduce**:

1. Compile Roslyn.sln on Dev15 Preview3 to deploy latest bits to RoslynDev hive.
2. devenv /rootsuffix RoslynDev
3. Unzip `Closed\Test\Solutions\Newtonsoft.Json.zip` and open `Closed\Test\Solutions\Newtonsoft.Json\Newtonsoft.Json\Newtonsoft.Json.Portable.sln`
4. Open `Closed\Test\Solutions\Newtonsoft.Json\Newtonsoft.Json\Linq\JsonLoadSettings.cs`, go to line 27 with text `_commentHandling = value;`. You should see a green squiggle with SA1101 (prefix with this).
5. Hit Ctrl + dot and Enter to invoke the code fix, but press cancel while code fix is being computed.

**Expected Behavior**:
Squiggles still appear on the open document.

**Actual Behavior**:
Squiggles disappear as soon as code fix is invoked and don't appear again. Error list still shows the diagnostics, and the code fix for SA1101 is still offered at line 27.

**Comment by mavasani** [comment]
Another repro: At step 5 above, select all text at line 27, hit Ctrl + dot, and Escape instead of Enter. Squiggles still disappear and don't come back.

**Comment by Pilchie** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/12718?

**Comment by mavasani** [comment]
Yes, thanks.
