### ISSUE TITLE
Feature `Strict`

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#13238]
The Feature Argument [Strict](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Test/Utilities/VisualBasic/TestOptions.vb#L34) doesn't appear in the Feature enumeration list. [link](https://github.com/dotnet/roslyn/blob/7c51e593bf5dbac6e48f8b659b4bc24097339f21/src/Compilers/VisualBasic/Portable/Parser/ParserFeature.vb#L7)
Should it be?

**Comment by gafter** [comment]
No. That is a list of language features.

**Comment by AdamSpeight2008** [comment]
What is `Strict`?

**Comment by gafter** [comment]
See #13223. "strict" causes the C# compiler to obey the spec in cases where the compiler is normally permissive for compatibility with previous compiler bugs.

**Comment by AdamSpeight2008** [comment]
And in the case of VB?

**Comment by gafter** [comment]
"strict" causes the VB compiler to obey the spec in some cases where the compiler is normally permissive for compatibility with previous compiler bugs. The set of such cases is currently empty.

**Comment by AdamSpeight2008** [comment]
So `strict` defines the cause of action the compiler will take in those case. Which if I am correct in think will aid in the resultant compilation being more deterministic.

**Comment by gafter** [comment]
No, the `strict` feature has nothing to do with determinism. It has to do with following the spec more strictly than in the default mode.
