### ISSUE TITLE
[Test Failure] AV in Roslyn.Services.Editor.UnitTests2.dll

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#13243]
test failure
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/2694/

there seems an issue with metadata reader

 Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
15:26:22      at System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetExtends(TypeDefinitionHandle handle)
15:26:22      at Microsoft.CodeAnalysis.PEModule.GetBaseTypeOfTypeOrThrow(TypeDefinitionHandle typeDef) in q:\roslyn\src\Compilers\Core\Portable\MetadataReader\PEModule.cs:line 860
15:26:22      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.MakeDeclaredBaseType() in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PENamedTypeSymbol.cs:line 429
15:26:22      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.GetDeclaredBaseType(ConsList`1 basesBeingResolved) in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PENamedTypeSymbol.cs:line 406
15:26:22      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.get_TypeKind() in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PENamedTypeSymbol.cs:line 1603

**Comment by Pilchie** [comment]
I also saw this on http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/2415/console.

From @tmat:

> . Quick look at crash dump shows that the MetadataModule itself is not disposed but the underlying memory is gone. The module was created with memory pointer, so the creator (AbstractReferenceSerializationService) is responsible for keeping that memory alive. It might be a good idea to add some in-memory logging to it.

**Comment by heejaechang** [comment]
@Pilchie @tmat this test failure was not from metadata that is not from abstract reference serialization service.

but, somehow link is dead now so i can't get to actual logging information.

**Comment by Pilchie** [comment]
We don't appear to have any logs for these runs :(

**Comment by Pilchie** [comment]
Happened again in https://github.com/dotnet/roslyn/issues/13548 for PR #13545

**Comment by Pilchie** [comment]
Jenkins failure for above is http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/3244/

**Comment by Pilchie** [comment]
Is there an issue with the lifetime of metadata we give out in `TestWorkspace`?

**Comment by jasonmalinowski** [comment]
Well, we dispose TestWorkspaces, so at that point the metadata is going to be disposed. What is running beyond the lifetime there? That other link is also gone, do we at least know the _full_ stack of the failure?

**Comment by heejaechang** [comment]
I got another of these. I made to keep the build forever

http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/3433/console

**Comment by heejaechang** [comment]
here are callstack

 at System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetExtends(TypeDefinitionHandle handle)
03:27:55      at Microsoft.CodeAnalysis.PEModule.GetBaseTypeOfTypeOrThrow(TypeDefinitionHandle typeDef) in q:\roslyn\src\Compilers\Core\Portable\MetadataReader\PEModule.cs:line 860
03:27:55      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.MakeDeclaredBaseType() in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PENamedTypeSymbol.cs:line 429
03:27:55      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.GetDeclaredBaseType(ConsList`1 basesBeingResolved) in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PENamedTypeSymbol.cs:line 406
03:27:55      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.get_TypeKind() in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PENamedTypeSymbol.cs:line 1603
03:27:55      at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.Microsoft.CodeAnalysis.ITypeSymbol.get_TypeKind() in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\TypeSymbol.cs:line 694
03:27:55      at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyWriter.VisitNamedType(INamedTypeSymbol namedTypeSymbol) in q:\roslyn\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.SymbolKeyWriter.cs:line 368
03:27:55      at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Accept[TResult](SymbolVisitor`1 visitor) in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\NamedTypeSymbol.cs:line 1499
03:27:55      at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyWriter.WriteSymbolKey(ISymbol symbol, Boolean first) in q:\roslyn\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.SymbolKeyWriter.cs:line 163
03:27:55      at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyWriter.WriteFirstSymbolKey(ISymbol symbol) in q:\roslyn\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.SymbolKeyWriter.cs:line 129
03:27:55      at Microsoft.CodeAnalysis.SymbolKey.ToString(ISymbol symbol, CancellationToken cancellationToken) in q:\roslyn\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.cs:line 134
03:27:55      at Microsoft.CodeAnalysis.SymbolKey.Create(ISymbol symbol, CancellationToken cancellationToken) in q:\roslyn\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.cs:line 125
03:27:55      at Microsoft.CodeAnalysis.SymbolKeyExtensions.GetSymbolKey(ISymbol symbol) in q:\roslyn\src\Workspaces\Core\Portable\SymbolKey\SymbolKeyExtensions.cs:line 11
03:27:55      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindSourceDefinitionWorkerAsync>d__5.MoveNext() in q:\roslyn\src\Workspaces\Core\Portable\FindSymbols\SymbolFinder.cs:line 149
03:27:55      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
03:27:55      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindSourceDefinitionWorkerAsync(ISymbol symbol, Solution solution, CancellationToken cancellationToken)
03:27:55      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindSourceDefinitionAsync(ISymbol symbol, Solution solution, CancellationToken cancellationToken) in q:\roslyn\src\Workspaces\Core\Portable\FindSymbols\SymbolFinder.cs:line 98
03:27:55      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<DetermineAllSymbolsCoreAsync>d__26.MoveNext() in q:\roslyn\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine_MapCreation.cs:line 148
03:27:55      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
03:27:55      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.DetermineAllSymbolsCoreAsync(ISymbol symbol, ConcurrentSet`1 result)
03:27:55      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<DetermineAllSymbolsAsync>d__25.MoveNext() in q:\roslyn\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine_MapCreation.cs:line 136
03:27:55      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
03:27:55      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.DetermineAllSymbolsAsync(ISymbol symbol)
03:27:55      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__12.MoveNext() in q:\roslyn\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 65
03:27:55      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
03:27:55      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(ISymbol symbol)
03:27:55      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindReferencesAsync>d__50.MoveNext() in q:\roslyn\src\Workspaces\Core\Portable\FindSymbols\SymbolFinder_References.cs:line 65
03:27:55      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
03:27:55      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindReferencesAsync(ISymbol symbol, Solution solution, IFindReferencesProgress progress, IImmutableSet`1 documents, CancellationToken cancellationToken)
03:27:55      at Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences.FindReferencesTests.VB$StateMachine_483_TestAPI.MoveNext() in q:\roslyn\src\EditorFeatures\Test2\FindReferences\FindReferencesTests.vb:line 156
03:27:55      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
03:27:55      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
03:27:55      at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
03:27:55      at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__1(Object _) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\AsyncTestSyncContext.cs:line 75
03:27:55      at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
03:27:55      at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
03:27:55      at System.Windows.Threading.DispatcherOperation.InvokeImpl()
03:27:55      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
03:27:55      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
03:27:55      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
03:27:55      at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
03:27:55      at System.Windows.Threading.DispatcherOperation.Invoke()
03:27:55      at System.Windows.Threading.Dispatcher.ProcessQueue()
03:27:55      at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
03:27:55      at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
03:27:55      at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
03:27:55      at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
03:27:55      at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
03:27:55      at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
03:27:55      at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
03:27:55      at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
03:27:55      at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
03:27:55      at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
03:27:55      at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
03:27:55      at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
03:27:55      at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority)
03:27:55      at Roslyn.Test.Utilities.WaitHelper.WaitForDispatchedOperationsToComplete(DispatcherPriority priority) in q:\roslyn\src\EditorFeatures\TestUtilities\Async\WaitHelper.cs:line 19
03:27:55      at Roslyn.Test.Utilities.WpfTestCase.<>c.<RunAsync>b__2_1() in q:\roslyn\src\EditorFeatures\TestUtilities\Threading\WpfTestCase.cs:line 70
03:27:55      at System.Threading.Tasks.Task.Execute()
03:27:55      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
03:27:55      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
03:27:55      at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
03:27:55      at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
03:27:55      at Roslyn.Test.Utilities.StaTaskScheduler.<.ctor>b__7_1() in q:\roslyn\src\EditorFeatures\TestUtilities\Threading\StaTaskScheduler.cs:line 51
03:27:55      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
03:27:55      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
03:27:55      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
03:27:55      at System.Threading.ThreadHelper.ThreadStart()
03:27:55   Command: C:\Users\dotnet-bot\.nuget\packages\xunit.runner.console\2.2.0-beta1-build3239\tools\xunit.console.exe

**Comment by jaredpar** [comment]
This is a bug in the runtime.  Essentially when NGEN images + GAC + very specific return pattern in APIs are combined together there is a race condition that can lead to a crash.  That is what is happening here.  The bug tracking the desktop fix is:

https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit217724

As a temporary work around we need to delete the NGEN images for System.Reflection.Metadata on the Jenkins machines.

**Comment by genlu** [comment]
Encountered this in #14877 
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit64_prtest/1677/

**Comment by jcouv** [comment]
Encountered this too, in https://github.com/dotnet/roslyn/pull/14871
https://ci.dot.net/job/dotnet_roslyn/job/features_wildcard/job/windows_debug_unit32_prtest/1/console

The same test (`TestAPI`) that Heejae has logged in the stack trace above shows up in my stack trace (EditorFeatures\Test2\FindReferences\FindReferencesTests.vb:line 160).

**Comment by jasonmalinowski** [comment]
So I have a dump of the crash, and can observe the following things:

1. The TestWorkspace doesn't appear to have been disposed. I don't see any problems with asynchrony.
2. The metadata reader is not being loaded from the GAC and I don't see any ngen images, so I don't believe this is @jaredpar's ngen/GAC bug.

My operating assumption is we have some lifetime bug where for some reason the object pinning the memory GCed out from underneath the test. I'll dive into this more deeply in an hour or two once I'm back in the office with @tmat's help.

**Comment by jaredpar** [comment]
@jasonmalinowski can you share out the dump? Internally would be fine.

**Comment by jasonmalinowski** [comment]
@jaredpar I've dropped the Jenkins build in `\\mlangfs1\public\jasonmal\Dumps\Roslyn\13243` however @tmat and I spoke for a few minutes and we have a very plausible theory. We've identified some suspicious code in the Workspaces API.
