### ISSUE TITLE
Suboptimal code for e is null

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#13247]
Currently `e is null` translates to an `object.Equals` call on master. The question is that (1) does it meant to be a shorthand for explicit reference null check `(object)e == null`? If so, (2) shouldn't it just translate to a `ceq`?

**Comment by orthoxerox** [comment]
What if `e` is a nullable value type? But I agree, the compiler can check this at compile time and emit better code for reference types.

**Comment by alrz** [comment]
@orthoxerox It should use `HasValue` which is what it does when it compares `null` and nullables.

Anyway, my real concern is that it might be really confusing and I'm afraid to see  `e is null` AND `e == null` side by side without any clear intention. At least #8409 is explicitly for reference equality checks.

**Comment by gafter** [comment]
@alrz they should generate the same code

**Comment by alrz** [comment]
@gafter if so, I think this covers #8409 unless you have two non-constant expressions.

**Comment by jaredpar** [comment]
Moving out for now as this doesn't meet the RTM bar.

**Comment by gafter** [comment]
Did you want to move #16129 out too?

**Comment by gafter** [comment]
Also #14252

**Comment by jaredpar** [comment]
Yes and Yes.  Thanks!

**Comment by sharwell** [comment]
:bulb: See #19803 for a very descriptive breakdown of the current and expected behavior for both `Nullable<T>` and reference types.
