### ISSUE TITLE
Naming Rules should apply to more symbol kinds (locals, parameters)

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#13249]
A bunch of symbol kinds are missing because we are using RegisterSymbolAction (see its limitations at https://github.com/dotnet/roslyn/issues/8753)

We either need to fix #8753 and then test Naming Styles on the new Kinds, or we need to implement workarounds for these missing Kinds.

**Comment by Pilchie** [comment]
Didn't you fix this for parameters at least?
