### ISSUE TITLE
Refactor GetArgumentForParameterDefaultValue

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#13262]
Refactoring this function into smaller separate function will add readability and enable part of it to be reused.

[Source](https://github.com/dotnet/roslyn/blob/faf3016072e42ac20e18a6be1f48c61173c555c2/src/Compilers/VisualBasic/Portable/Binding/Binder_Invocation.vb#L3039)

[Suggested Implementation](https://gist.github.com/AdamSpeight2008/5ed6ed1b8ef134093e39499d4b265081)

**Note:** [line 21](https://gist.github.com/AdamSpeight2008/5ed6ed1b8ef134093e39499d4b265081#file-getargumentforparameterdefaultvalue-vb-L21) is for the ImplicitDefaultOptionalParameter feature.

**Comment by gafter** [comment]
We do not contemplate pull requests submitted through issues.

**Comment by AdamSpeight2008** [comment]
@gafter I wasn't suggesting that be the case.
I merely suggesting that method could do with being refactored, My suggested possible refactoring code example, just happen to be in pr.
