### ISSUE TITLE
The type 'Console' exists in both 'System.Console' and 'System.Private.CoreLib'

### ISSUE THREAD

**Issue by garrynewman** [dotnet/roslyn#13267]
**Version Used**: 1.3.0

**Steps to Reproduce**:

Compile code using CSharpCompilation with references to CoreCLR versions of
```
System.Private.CoreLib.dll
mscorlib.dll
System.Console.dll
```
**Expected Behavior**: Compiles

**Actual Behavior**: Error

```
TestScript.cs(9,9): error CS0433: The type 'Console' exists in both 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'
```

Searching though the code, this seems like the exact problem `IgnoreCorLibraryDuplicatedTypes` was added to solve - but there's no public way to enable that flag for a build.

**Comment by tmat** [comment]
Why do you include reference to ```System.Private.CoreLib.dll``` and ```mscorlib```? Couldn't you use ```System.Runtime``` instead?

**Comment by garrynewman** [comment]
I don't think so. What I'm doing is compiling scripts on the fly, loading assemblies provided here https://www.microsoft.com/net/download.

Including only these references 

```
            "System.Runtime.dll",
            "System.Runtime.Extensions.dll",

            "System.Dynamic.Runtime.dll",
          
            "System.Collections.dll",
            "System.Collections.Concurrent.dll",
            
            "System.Linq.dll",
            "System.IO.dll",
            "System.IO.Filesystem.dll",
            "System.Reflection.dll",
            "System.Xml.XmlDocument.dll",
            "System.Xml.XDocument.dll",
            "System.Net.Primitives.dll",
            "System.Net.Sockets.dll",

            "System.Threading.dll",
            "System.Threading.Tasks.dll",
            "System.Threading.Tasks.Parallel.dll",
            "System.Threading.Thread.dll",
            "System.Threading.ThreadPool.dll",
            "System.Threading.Timer.dll",
```

Creates these errors

```
Addon/Test		warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
Addon/Test		C:\GitHub\SandboxGame\Game\Addons\Test\Code\TestScript.cs(4,14): error CS0518: Predefined type 'System.Object' is not defined or imported
Addon/Test		C:\GitHub\SandboxGame\Game\Addons\Test\Code\TestScript.cs(7,19): error CS0518: Predefined type 'System.Void' is not defined or imported
Addon/Test		C:\GitHub\SandboxGame\Game\Addons\Test\Code\TestScript.cs(34,2): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Addon/Test		C:\GitHub\SandboxGame\Game\Addons\Test\Code\TestScript.cs(45,2): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Addon/Test		C:\GitHub\SandboxGame\Game\Addons\Test\Code\TestScript.cs(6,6): error CS0518: Predefined type 'System.Object' is not defined or imported
Addon/Test		C:\GitHub\SandboxGame\Game\Addons\Test\Code\TestScript.cs(45,2): error CS0518: Predefined type 'System.Object' is not defined or imported
Addon/Test		C:\GitHub\SandboxGame\Game\Addons\Test\Code\TestScript.cs(34,2): error CS0518: Predefined type 'System.Object' is not defined or imported
```

**Comment by tmat** [comment]
Could you share more details on what are you trying to achieve? Compiling against runtime assemblies is tricky.

**Comment by garrynewman** [comment]
I'm using c# as a scripting language. So I'm compiling the code at runtime and hotloading the created assemblies.

**Comment by tmat** [comment]
Are you using https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples?

**Comment by garrynewman** [comment]
No. I'm emitting an assembly from a directory of code files and loading it at runtime. I'm not sure whether the scripting system is appropriate for what we're doing.

**Comment by tmat** [comment]
In that case you'll need to add references to contract assemblies, not runtime assemblies. Contract assemblies are found in CoreFX NuGet packages. You'll need to extract them from the packages and distribute with your application.

**Comment by garrynewman** [comment]
As annoying as that is - it does kind of make sense. It seems like a huge shame that this is the case though. I guess I need to write a script to parse a bunch of stuff and copy dlls from the ref folder.

**Comment by garrynewman** [comment]
Okay, just for future generations, I have got around this (as far as I can tell) by:

Copying System.Runtime.dll and System.Runtime.Extensions.dll from:

`C:\Users\<user>\.nuget\packages\System.Runtime\4.1.0\ref\netstandard1.5`

and putting them in a References folder in my project. So then instead of referencing mscorlib.dll and System.Private.CoreLib.dll I reference these. I'm guessing I might need to add more dlls here in the future, but right now I'm referencing the corefx system dlls too and no issues yet.

I still think it'd be simpler to be able to reference the shipping dlls directly, but maybe I'm not understanding the role of the reference dlls within corefx. This works and it's not a massive change though so I'm happy.

Thanks for the help tmat.

**Comment by tmat** [comment]
@vors Mixing reference assemblies and implementation assemblies is not a good idea. Things will break.
