### ISSUE TITLE
UnusedDeclarationsAnalyzer is graying out an in-use method

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#1326]
Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EvaluationContext has a private constructor that is called from two public factory methods (in the same file).  Nevertheless, it has been grayed out and the lightbulb is offering to remove it.

**Comment by mavasani** [comment]
I have seen multiple similar cases of this during editing within Roslyn.sln today. This could be an issue with the analyzer OR the IDE analyzer driver.
