### ISSUE TITLE
clean up IDiagnosticAnalyzerService

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#13261]
2 things suggested.

first, add IDiagnosticUpdateSource in DiagnosticUpdateEventArgs or make id not object but actual type that has contains IDiagnosticUpdateSource. this is to make clear id in the DiagnosticUpdateEventArgs is only unique to the source itself. id itself is opaque handle for update sources to track a chunk of diagnostics it raised.

basically, diagnostic source creates unique id -> diagnostic source raise diagnostic changed events -> IDiagnosticService propagate it to all listener -> listener save the id it is interested in to consume it later -> when it is appropriate time, listener call back to IDiagnosticService giving in the id -> IDiagnosticService finds the owner of the id from diagnostic sources -> IDiagnosticService give the id to the update source which owns/created the id and ask it to return diagnostics chunk that belong to that id.

so id only needs to be unique in update source.

this will make some services to not work by knowing implementation details. but by only through contract.

....

another suggested change is providing a way to subscribe to events that are only associated with a particular buffer.

this should make many consumer that are working on top of particular buffer to deal with IDiagnosticService easier.

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.
