### ISSUE TITLE
EE: Implement ProjectN corlib workaround 

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#13275]
The current ProjectN corlib has AssemblyRefs and thus isn't considered a valid corlib by the compiler. We need to implement a workaround for EE to enable compilation against such corlib. Long term the CLR is working towards removing the AssemblyRefs.

**Comment by cston** [comment]
.NET Native corlib should no longer contain AssemblyRefs.

**Comment by tmat** [comment]
The workaround is to remove the requirement of no AssemblyRefs in the compiler for corlib whose strong name matches the name of .NET Native corlib. We need to test that such relaxation doesn't cause issues as we have never had the case before of corlib being involved in cyclic references.
