### ISSUE TITLE
EnC: defer active statement related work until after a document is edited

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#13276]

**Comment by tmat** [comment]
We would actually lose some functionality if we deferred active statement calculation until after the user edits a document. 
The active statement tagger that creates tracking spans for non-leaf active statements (displayed as gray spans in the editor) kicks in when projects enter break state. I believe displaying these spans adds value to debugging in general since the user has better idea about what statements are currently being executed. Visualizing these also informs the user about regions in code that shouldn’t be edited before the user even starts typing anything (otherwise a rude edit is reported).

**Comment by tommcdon** [comment]
We have one customer that is seeing a significant performance issue where 50% of the stepping time is spent related to this.  Please contact me if you are interested in the trace.

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/24428
