### ISSUE TITLE
IDE Features sometimes don't work in Conditional Compilation Code

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#13282]
eg

``` vb
#If USE_SETTING_XML_SCHEMA_VALIDATION Then
        ''' <summary>
        ''' Demand create an XML Schema instance for .settings files.
        ''' </summary>
        ''' <value></value>
        ''' <remarks></remarks>
        Private Shared ReadOnly Property Schema() As System.Xml.Schema.XmlSchema
            Get
                Static schemaInstance As System.Xml.Schema.XmlSchema
                If schemaInstance Is Nothing AndAlso Not s_SchemaLoadFailed Then
                    Dim SchemaStream As Stream
                    SchemaStream = GetType(SettingsSerializer).Assembly.GetManifestResourceStream(GetType(SettingsSerializer), "SettingsSchema")
                    schemaInstance = System.Xml.Schema.XmlSchema.Read(SchemaStream, AddressOf SchemaValidationEventHandler)
                End If
                Return schemaInstance
            End Get
        End Property
#End If
```

In the XML Comments add an additional line, should automagically insert `'''` .

**Comment by AdamSpeight2008** [comment]
**Rename**
Renaming `variable_one` to `variable1` should also rename the variable usage in the conditional compilation code.
```vb
#Const Enabled = False
Module Module1

    Sub Main()
        Dim variable_one As Integer = 0
#If Enabled Then
        Console.WriteLine(nameof(variable_one) & ":= " & variable_one )
#End If
        Console.WriteLine(NameOf(variable_one) & ":= " & variable_one)

    End Sub

End Module
```

**Comment by Pilchie** [comment]
Right now we don't parse anything in an inactive pre-processor block.  We've thought about some ways to change that, but it would be a significant undertaking, and probably not worth it given how rarely pre-processor directives are used in C# and VB.

**Comment by alrz** [comment]
@Pilchie In my opinion it is a great feature but it is not structured, ergo, it is rarely used. I'd always prefer  attribute-based pre processor directives, something like #7875.

**Comment by AdamSpeight2008** [comment]
@Pilchie  I think we should at least parse them, so that the structure of the is available to analysers and codefixes. Only do semantic analysis if the block is enabled.

**Comment by Pilchie** [comment]
@AdamSpeight2008 and who says that it even comes close to parsing correctly.  In my experience, tons of preprocessor blocks haven't been enabled in years and are full of errors to the point of being meaningless.

**Comment by AdamSpeight2008** [comment]
Hence if they were parsed they could be corrected.

**Comment by AdamSpeight2008** [comment]
@Pilchie  We could have additional `DiagnosticSeverity` for the conditional compilations.

```
DiagnosticSeverity.ConditionalCompilation_Hidden
DiagnosticSeverity.ConditionalCompilation_Info
DiagnosticSeverity.ConditionalCompilation_Error
DiagnosticSeverity.ConditionalCompilation_Warning
```

**Comment by CyrusNajmabadi** [comment]
> Hence if they were parsed they could be corrected.

This is not necessarily even desirable.  For example, i've routinely encountered (and even written) things like:

```
#if false
    This is a long paragraph of prose describing what's going on.
    ...
    Ascii diagrams galore.
    ...
    You get the idea
```

Parsing this simply will not work.  Nor is the act of 'parsing' even something we can do sensibly.  For example:

```
public
#if CORE
struct
#else
class
#endif
Foo
{
}

The work to support this sort of thing is extremely complex, with not that much benefit on the other end.
