### ISSUE TITLE
[VB LINQ] Range Query Syntax

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#13283]
**Range Query Syntax**

``` vb.net
Dim odd = From x In 1 To 100 Step 2
Dim HundredToZero = From x In 100 To 0 Step -2
```

**Comment by HaloFour** [comment]
I assume that `Step` would be optional as it is with `For` loops:

```vb
Dim numbers = From x In 1 To 100
```

How about if you omit the `To` clause and only include the `Step` clause, could that create an unbounded enumerable?

```vb
Dim allEvens = From x In 2 Step 2
```

Even if not I'd say that this would fit well with VB syntax.  My only question would be about the compiler being able to properly distinguish this feature from trying to find a `GetEnumerator` extension method defined on `System.Int32`.

That said, it'd also be very easily to emulate a language feature through extension methods:

```vb
Dim odd = From x In 1.To(100).Step(2)
```

**Comment by AdamSpeight2008** [comment]
@HaloFour  The extension methods are ok, when then range is ascending. It when is descending it get complex,
```vb
Dim xs = From x In 99 To 0 Step -2
Dim a As UInt = CUInt( 99 )
Dim b As UInt = CUInt( 1 )
Dim ys = From x In a To b Step -1 '
```

**Comment by AdamSpeight2008** [comment]
Also why can't  the compiler, compile this.
```vb
For i As UInteger = CUInt(100) To CUInt(0) Step -1 ' the -1 is a compile-time error.
```
As if it was doing
```vb
 ' Pseudo-syntax.
For  DirectCast( i , UInteger) As Integer = CInt( CUInt(100)) To CInt( CUInt(0) ) Step CInt(-1) .

```

**Comment by alrz** [comment]
This is similar to #7632 for C#. I would very appreciate it if there was also a pattern counterpart. which by the way, is available in VB already.
```vb
For index = 0 To array.Length
    ...
Next

Select Case number
    Case 1 To 5
        ...
End Select
```
```cs
foreach(var indexin 0 .. array.Length) { }

switch(number) {
  case 1 .. 5: break;
}
```

**Comment by AdamSpeight2008** [comment]
@alrz 
I hadn't consider the pattern form, but thinking about it would be useful.
` Case  0 To 100 ' Range ` eg ` 0 <= value <= 100 `
` Case 0 To 100 Step 2 ' Selection` equivalent to ` Case 0, 2, 4 ... 96, 98, 100 ` 

Should the pieces of the pattern `  _a_ To _b_ Step _c_` have the same type?
 `typeof( _a_ ) == typeof( _b_ ) == tupeof( _c_ )`
Should we restrict the feature to just the core types? If not how to determine what is a compile error.
Eg `Case "A"c To "Z" Step "A"c

```vb
Select Case obj
  Case 0 To 100 ' Range (eg 0 <= obj <= 100 )
  Case 0 To 100 Step 2 ' Selection eg ( 0, 2, 4, ... 96, 98, 100)
  Case #00:00:00# To #23;59:59# Step #00:30:00# ' Half hours.
  Case "A" To "Z" ' String
  Case "A" To "Z" Step "A" ' Error
  Case "A"c To "Z" ' Char
  Case "A"c To "Z"c ' Error
  Case 0.0 To 100.0 ' Double
```

**Comment by AdamSpeight2008** [comment]
[Ported to VBLang](https://github.com/dotnet/vblang/issues/25)
