### ISSUE TITLE
VB Tuples - need to handle generic methods in ValueTuple types

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#13298]
We do not have generic methods in ValueTuple, but in a custom ValueTuple implementation, they may exist.

We need to handle that case.

**Comment by jaredpar** [comment]
Is this specific to VB or is this a problem in C# as well?

**Comment by jcouv** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/13053
This is specific to VB. If you implement your own ValueTuple type in C#, you can include generic methods in  it.
