### ISSUE TITLE
Rebuilding Roslyn.sln in VS causes IntelliSense errors finding "*_42.42.42.42.cs"

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#13307]
The build succeeds, but I get tons of these:

![image](https://cloud.githubusercontent.com/assets/235241/17872485/1d54fd8e-6875-11e6-8ad6-518a72c727bd.png)

**Comment by jasonmalinowski** [comment]
Our plan was to aggressively hide this output window output since it's rarely useful. I can't find the bug tracking it though. Moving to IDE.

**Comment by jasonmalinowski** [comment]
Oh it's #12202.
