### ISSUE TITLE
[Go To] Enable camelCase bolding for files & symbols in GoTo

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#13309]
To meet the new design requirements. Related to work that needs to get done for https://github.com/dotnet/roslyn/issues/13221.

**Comment by CyrusNajmabadi** [comment]
Have opened: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/258606?fullScreen=false

On the editor API.  It is inconsistent with the API for Completion.

**Comment by CyrusNajmabadi** [comment]
Also, the API hasn't actually been exposed in a nuget package yet.  So we can't start using it just yet.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/14693
