### ISSUE TITLE
A way to do perf comparisions.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#13318]
Currently I'm using `msbuild /nodereuse:false /v:m /m BuildAndTest.proj` to build and test.
Is there a way to a perf comparision run. compare exist compilers, against just built compilers.

Producing a report similar to @mattwar's BenchmarkDotNet.

**Comment by bbarry** [comment]
What are you trying to measure? You could probably write BenchmarkDotNet wrapper functions over the compiler in a similar way to the unit tests. Would it be ok to depend on that library in testing projects for Roslyn?

**Comment by jaredpar** [comment]
The ability to do performance comparisons is in the works now.  @TyOverby is actively implementing this now.  

@TyOverby do we have a bug we can dupe this to?

**Comment by TyOverby** [comment]
@jaredpar We haven't had a tracking bug, so I made one https://github.com/dotnet/roslyn/issues/13336

**Comment by AdamSpeight2008** [comment]
@bbarry 
Say if someone change the code, so that it produce different IL. We should automagically produce a perf report.

**Comment by jaredpar** [comment]
Let's use that bug to track this issue.
