### ISSUE TITLE
[Go To] Implement "filter to doc scope"

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#13310]
Related to the redesign of 'Navigate To'. See also https://github.com/dotnet/roslyn/issues/13221 and https://github.com/dotnet/roslyn/issues/13309.

**Comment by CyrusNajmabadi** [comment]
This API has not been exposed by the VS side yet.  It is currently only internal.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/7fb1ba0674b675812b749d588fa0d2b07449340b
