### ISSUE TITLE
[Discussion] Language Namespace

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#13311]
From my recent experience from developing a language feature.
We could benefit from a little review around language version and Feature.

+ A common namespace, for language info.
 + eg `CodeAnalysis.VisualBasic.Language`
 + Feature Availability Checking should be coalesced into a single section of the code base.
    Currently there at least three different places.  
    + `Portable/Scanner/Scanner.vb` [link](https://github.com/dotnet/roslyn/blob/7c51e593bf5dbac6e48f8b659b4bc24097339f21/src/Compilers/VisualBasic/Portable/Scanner/Scanner.vb#L2541)
    + `Portable/Parser/Parser.vb` [link](https://github.com/dotnet/roslyn/blob/7c51e593bf5dbac6e48f8b659b4bc24097339f21/src/Compilers/VisualBasic/Portable/Parser/Parser.vb#L6103)
    + `Portable/Utilities/VisualBasic/TestOptions.vb` [link](https://github.com/dotnet/roslyn/blob/413c49e2fc11a0e01e99d87a253e81691ac541ba/src/Compilers/Test/Utilities/VisualBasic/TestOptions.vb#L31)
    + under namespace `CodeAnalysis.VisualBasic.Language.Features`
    + *So a common implementation could be used.*
    + Add informative xml comments on the methods. 
 + Also check against `Features` in parse options.
  + Move `Language Version` to be under.
    + `CodeAnalysis.VisualBasic.Language.Versions`

**Comment by jaredpar** [comment]
This type of refactoring isn't really possible.  All of our APIs are pulbic and must maintain compat.  Moving thiese items to a new namespace is a breaking change.
