### ISSUE TITLE
Additional tests for pattern matching inference interaction with other language features

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13312]
In https://github.com/dotnet/roslyn/pull/13274#discussion_r75774455 it is suggested by @AlekseyTs that the tests that demonstrate that pattern variables can be inferred lazily should be expanded substantially to test the interactions with other features more deeply.

**Comment by OmarTawfik** [comment]
@gafter @AlekseyTs can you please elaborate? I'm going through the tests in [PatternMatchingTests.cs](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs), but cannot find the original comment in #13274.
