### ISSUE TITLE
NavigateTo and FindAllReferences telemetry shows we are slightly out of goal

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#13326]
Opening this work item to track investigation into improving this scenario...

**Find All References:**
https://msit.powerbi.com/groups/c51b0605-28b2-453e-a9a8-cf03a596c794/dashboards/5f1fce4b-2d88-48c0-a519-134f57db4a2f
![far](https://cloud.githubusercontent.com/assets/6464209/17908578/de1f36a4-6935-11e6-9e95-3d0b37f3c3e3.PNG)

**Navigate To:**
https://msit.powerbi.com/groups/c51b0605-28b2-453e-a9a8-cf03a596c794/dashboards/a46bdce6-b54d-44f3-ab6e-5d3a5f726dfb
![navigateto](https://cloud.githubusercontent.com/assets/6464209/17908614/16bac744-6936-11e6-93d5-d9e04f29de6b.PNG)

**Comment by rchande** [comment]
Filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/370239

**Comment by rchande** [comment]
Also https://devdiv.visualstudio.com/DevDiv/_workitems?id=370449&fullScreen=false&_a=edit against the editor

**Comment by Pilchie** [comment]
I believe these are now in-goal. @mavasani can you confirm?

**Comment by MattGertz** [comment]
FAR is at goal; Navigate is really close.  Closing.
