### ISSUE TITLE
Want API control over the *order* of documents in a project

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#13324]
Roslyn API should expose the order of documents in a project. It should let you query the order, and specify an arbitrary order, and (maybe) let you add a new document at an arbitrary place in the order.

@CyrusNajmabadi writes: "I believe the Compiler (as part of determinism) has actually moved to guaranteeing that order of source files will be respected in terms of how partials work.  It’s a supported contract on their part. **As such, we really should push this concept outward**, even though it’s likely not good practice for people in C#.  Note that for TS (and F# I believe), order of files _is_ important.  It would be good to support and respect the ordering (including potentially exposing such facilities in the UI)."
## Examples

C# partial classes are sensitive to ordering for doc-comments:

``` cs
// file "a.cs"
/// <summary>World</summary>
partial class C { }

// file "b.cs"
/// <summary>Hello</summary>
partial class C { }

// RESULT:
// The doc-comment for "C" depends on which file was compiled first.
```

C# partial classes are sensitive to ordering for covariant interface implementations:

``` cs
// a.cs
class Program { static void Main() { I<object> c = new C(); c.f(); } }
interface I<out T> { void f(); }
partial class C : I<string>, I<System.Exception> { void I<string>.f() => System.Console.WriteLine("a"); }

// b.cs
partial class C : I<System.Exception>, I<string> { void I<System.Exception>.f() => System.Console.WriteLine("b"); }

// RESULT:
// "csc a.cs b.cs" will produce an executable that prints "a"
// "csc b.cs a.cs" will produce an executable that prints "b"
```

C# csx files are strongly sensitive to order:

``` cs
// a.csx
System.Console.WriteLine("a");

// b.csx
System.Console.WriteLine("b");

// RESULT:
// "csi a.csx b.csx" will print "a"
// "csi b.csx a.csx" will print "b"
// And once we start supporting csx files in the csc compiler as well, the problem will be there too
```

**Comment by CyrusNajmabadi** [comment]
Note: i approve of offering this functionality, even though i find every case (except for .csx) completely uncompelling. :-)

Writing code that actually depends on this ordering in C# is a "bad idea :tm:".  

For some languages (like TS) ordering of files affects core, basic, functionality (like inheritance).  It's necessary to know and use appropriately, right from the start of your project.  For C#, it really should never be relevant.  (And, personally, i think it was unfortunate that we even allowed things like doc comments on multiple partial entities)

**Comment by cH40z-Lord** [comment]
Isn't that something the folks in the F# community has been asking for way too long?

**Comment by ljw1004** [comment]
Another example...

C# partial classes are sensitive to ordering for field initialization:

```cs
// a.cs
class Program { static void Main() { System.Console.WriteLine(C.y); } }
partial class C { public static int x = 1; }

// b.cs
partial class C { public static int y = x + 1; }

// RESULT:
// "csc a.cs b.cs" will produce an executable that prints "2"
// "csc b.cs a.cs" will produce an executable that prints "1"
```

**Comment by CyrusNajmabadi** [comment]
This highlights to me not a case where we want to invest in our API, but a that we should be discouraging users from engaging in.

**Comment by Pilchie** [comment]
Agreed - I think csx is the only compelling case here, and so I think this API can wait until we start work on getting support for multiple .csx files in a project working in IDEs.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski do we still need this?  I presume that we likely have this working (so that f# can work?).

**Comment by jasonmalinowski** [comment]
Indeed, we added the following for F#:

        /// <summary>
        /// Creates a new solution instance with the project documents in the order by the specified document ids.
        /// The specified document ids must be the same as what is already in the project; no adding or removing is allowed.
        /// </summary>
        public Solution WithProjectDocumentsOrder(ProjectId projectId, ImmutableList<DocumentId> documentIds)
