### ISSUE TITLE
Make the pattern switch statement produce at most one temp per type

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13333]
Under certain conditions, like this code

``` cs
    case "hello":
    case var x when e:
    case "world":
```

The pattern switch statement produces more than one temp of a given type. Since these temps are not simultaneously alive, we can actually reuse the same temp. That would be slightly better code, and it would also make it easier for us to handle full fidelity edit-and-continue.

**Comment by alrz** [comment]
Other than that, it seems  `switch` generates so much jumps, for example,
```cs
public class Program {
  interface A { int P {get;} }
  interface B { int P {get;} } 
  static bool M1(object o) {
    if(o is A i && i.P == 0 ||
       o is B j && j.P == 0)
        return true;
    return false;
  }
  static bool M2(object o) {
    switch(o) {
      case A i when i.P == 0:
      case B j when j.P == 0:
        return true;
    }
    return false;
  }
}
```
I expect the two method generate slightly similar code but that's not the case.

I'm assuming that multiple `case p when c` could be lowered to `o is p && c  || ..` .

**Comment by gafter** [comment]
This issue is obsolete in the new recursive pattern matching implementation.
