### ISSUE TITLE
C#: await in one catch causes following catches cannot re-throw exceptions

### ISSUE THREAD

**Issue by CnSimonChan** [dotnet/roslyn#1334]
I'm using Visual Studio 2015 Preview, I have some code like the following one:

```C#
public async void TestAsync()
{
    try
    {
        throw new ArgumentOutOfRangeException();
        // The type of exception here is not important, just not be an `ArgumentNullException`.
    }
    catch (ArgumentNullException) // Catches some other type here.
    {
        await Task.Delay(500); // Do something async here, it's essential.
    }
    catch (Exception)
    {
        // Maybe do some additional processes here, doesn't affect the result.
        throw; // Just re-throw the exception.
        // throw another exception here works fine.
    }
}
```

Obviously, this method should throw an `ArgumentOutOfRangeException`, **BUT** it will throw a `NullReferenceException` instead, no matter what exception is passed into `catch (Exception)`.

**Comment by VSadov** [comment]
try statements where all catches contain awaits are handled ok, 
try statements where none of the catches contain awaits are handled ok too.

The bug affects the scenario where some catches have awaits and some do not. So if there is a need for an urgent workaround, one can change the code to use nested try's just to make sure catches with awaits and without are not mixed in same try.

Will work on a fix shortly.
Thanks for reporting!!
