### ISSUE TITLE
Typing deconstruction-declaration requires fighting with auto-completion

### ISSUE THREAD

**Issue by DavidArno** [dotnet/roslyn#13342]
**Version Used**: VS15 Preview 4

**Steps to Reproduce**:

1. Attempt to type, for example, the lines:
````cs
var (a, b) = (1, 2);
var (e, f, g, h) = (1, 2, 3, 4);
````
**Expected Behavior**:
It should be possible to type these lines without auto-completion interfering.

**Actual Behavior**:
As you type each variable, auto-completion "helpfully" completes the names for you, so the code ends up as:
````cs
var(async, bool) = (1, 2);
var (else, false, global, HashSet) = (1, 2, 3, 4);
````

**Comment by gafter** [comment]
@jaredpar I want to call this issue to your attention for 2.0.

**Comment by jcouv** [comment]
@DavidArno Thanks for reporting this. I'm looking into this issue.

**Comment by jcouv** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/13522
