### ISSUE TITLE
Naming Styles don't have a way to make prefix optional (for example) 

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#13349]
Quote from a customer: "It is much too limiting/restrictive. For example the prefix is an all or nothing deal and there's no way to make it optional."

**Comment by Pilchie** [comment]
Isn't the solution there just to not enforce a rule?  Or they want to enforce capitalization, but don't prefix?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
