### ISSUE TITLE
Get all possible exceptions of a method

### ISSUE THREAD

**Issue by markusschweitzer** [dotnet/roslyn#13341]
Hi,

would it be possible to analyze method and output the possible axceptions that CAN be thrown by this method? (in some kind of a synthax visualizer style where you would see which exceptions are handled and which arnt - I would love to write an analyzer for that)

(I have no deeper knowledge about roslyn - just wanted to ask)

Thanks in advance

**Comment by DavidArno** [comment]
Whilst it might be possible to analyse *some* methods like this, it wouldn't be possible for all. Take for example:
````cs
public void RunMethod(Action method) => method();
````
There is no way to tell at compile/analysis time all possible future uses of `RunMethod` and the methods passed to it. Each will have their own possible exceptions. So unless you label this method able being able to throw every existing aand future exception, it's exception report would be incorrect.

**Comment by markusschweitzer** [comment]
Yes, you are right. Actions, Func, Delegates... would be an exception to this, but nethertheless would it be possible to retrieve this list (currently in VS intellisense/quick info)?

![image](https://cloud.githubusercontent.com/assets/18368530/17927136/8f69a0b6-69f4-11e6-99e5-a9de45be808d.png)

Thanks for your answer

**Comment by dsaf** [comment]
That list is unfortunately generated from XML documentation, not by analyzing the code.

> ...possible axceptions that CAN be thrown by this method...

What is your expectation in the following situation?

```csharp
public void Test()
{
    if (false)
        throw new ApplicationException();
}
```

**Comment by Joe4evr** [comment]
> That list is unfortunately generated from XML documentation, not by analyzing the code.

Yes, it's the developer's responsibility to document their code and list the possible **known** exceptions that can be thrown from a given method. If third-party libraries don't list possible exceptions, you need to take that up with that lib's developer.

And before you say "But Java has checked exceptions!", you might want to read [Anders Hejlsberg's thoughts on the matter](http://www.artima.com/intv/handcuffs.html).

**Comment by markusschweitzer** [comment]
Oh ok. So its not possible.

Then, I guess this issue can be closed.

**Comment by dsaf** [comment]
@Joe4evr and why bother with automatic memory management and a static type systems - in the end it's developer's responsibility to deallocate and make sure types are used consistently

**Comment by dsaf** [comment]
@markusschweitzer I think it could be possible to make a "good enough" analyzer that will simply look for ```throw *Exception``` without any advanced analysis. Wouldn't this be useful?
