### ISSUE TITLE
Unexpected behavior of Pdb2Xml

### ISSUE THREAD

**Issue by Serenyrddraig** [dotnet/roslyn#13346]
**Version Used**: Zipped Master download 6/18/2016 06:08EDT

**Steps to Reproduce**:

1. In attached zip file, Pdb2Xml 12.0\Fujitsu.Contract.DocumentRepository.LockContract.dll /methodSpans
2. In attached zip file, Pdb2Xml 14.0\Fujitsu.Contract.DocumentRepository.LockContract.dll /methodSpans
3. Compare resulting xml files. My results are included in the zip.

**Expected Behavior**:
Files should be identical (so I thought)
**Actual Behavior**:
12.0 version is missing sequence points for all property accessors.

The two assemblies differ by the version of MSBuild/VisualStudio used to build them. Project/Solution and target framework version are identical for both MSBuild 12.0 (VS 2013) and MSBuild 14.0 (VS 2015). I've debugged the failing case and it appears that while the metadataTokens for the accessors are successfully read by the MetadataReader, the ISymUnmanagedReader3.GetMethod() returns null when processing the 12.0 pdb stream.

I have been unable to determine if this behavior was 'expected'.
[MissingSequencePoints.zip](https://github.com/dotnet/roslyn/files/435383/MissingSequencePoints.zip)

**Comment by gafter** [comment]
@tmat Can you please help triage this? Who owns Pdb2Xml?

**Comment by tmat** [comment]
There is no issue with Pdb2Xml. The difference is expected. VS 14.0 compiler (Roslyn) emits extra sequence points to auto-property accessors, so you can place a breakpoint on them.
