### ISSUE TITLE
VB Async Quick Fix Regression

### ISSUE THREAD

**Issue by AnthonyDGreen** [dotnet/roslyn#13357]
**Version Used**: Roslyn Build from 20160824.8

**Steps to Reproduce**: 

Invoke the quick fix to convert Sub Main to a function that returns a task
```VB
Module Module1
    Sub Main()
        Await Task.Run(Sub() Console.WriteLine())
    End Sub
End Module
```
**Expected Behavior**:
In Visual Studio 2013 there is only one quick fix and it adds `As Task`
![image](https://cloud.githubusercontent.com/assets/10539978/17952685/d3e6c962-6a21-11e6-8310-beeb78e38e94.png)
![image](https://cloud.githubusercontent.com/assets/10539978/17952691/e56fad70-6a21-11e6-997f-2cb12fe87db7.png)

**Actual Behavior**:
We offer two quick fixes
![image](https://cloud.githubusercontent.com/assets/10539978/17952674/afc0dd48-6a21-11e6-8316-8539d654e4e0.png)

**Comment by AnthonyDGreen** [comment]
@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
By design.  We have situations where you want to make an async-sub, and situations where you want an async-Task function.

**Comment by CyrusNajmabadi** [comment]
To be clear, it's not a regression that we support the functionality we supported before *and* we support new functionality.  :)

**Comment by AnthonyDGreen** [comment]
To be clear, @jmarolf filed this bug on my computer under my name. When we originally implemented the quick-fix in 2012 we only did the Async Function As Task version because our guidance is almost always to do that. The cases where a person should use Async Sub are pretty rare - specifically event handlers and some method overrides.

- I would be fine with it suggesting to make it an Async Sub _if_ the method had a Handles clause or was an override or interface implementation or took a parameter with a type assignable to EventArgs. Anything which suggested the commonly prescribed "proper" use cases for the "Async Sub" feature. In other scenarios it's morally reprehensible to even so much as suggest that these two options are equally valid or have some kind of peer relationship.
- At a _minimum_ the "Make method Async (return Task)" fix should always be sorted first.
- The descriptions of the quick fixes in Visual Basic should read "Make Async Sub" and "Make Async Function" not "Make method Async" and "Make method Async (return Task)". This display name is not idiomatic. In the event that the sort order of the quick-fix is just alphabetical and you can't control the sort order this would also result in sorting the fixes correctly.

**Comment by CyrusNajmabadi** [comment]
We control the ordering, so that's not a problem.  I'm amenable to sorting these to use the Task version first.  I think using the term 'method' is fine.  It's a core .net concept, and subs/functions are both ways of declaring one of those.
