### ISSUE TITLE
Code Generator doesn't handle expression bodied properties and indexers

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#1335]
`BasePropertyDeclarationSyntax` can now be null if the property or indexer is expression bodied, but the SyntaxGenerator doesn't take this into account.

**Comment by Pilchie** [comment]
Re-opening to track merging this fix to the preview branch.  @mattwar: can you prepare another pull request that cherry-picks this fix to preview?

**Comment by MattGertz** [comment]
Approved for next preview.

**Comment by Pilchie** [comment]
Closing now that #1676 is merged.
