### ISSUE TITLE
How to influence the generated files? Like syntax.Generated.vb

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#13362]
Can someone tell me if it possible influence the generated code produce into the `...Generated.vb` files.?
If so how? and where?

**Comment by HaloFour** [comment]
You mean have a generator/analyzer that can intercept and/or modify the source generated by another generator?

**Comment by AdamSpeight2008** [comment]
@HaloFour  No, if it generated, and may need change, like removing a null check so it no longer get thrown.

**Comment by HaloFour** [comment]
IIRC source generators are executed as a part of the compiler lifecycle.  The tooling will show you the results, but even if you could modify them the generator would simply overwrite your changes.  Unless you compile once and then get rid of the source generator.

**Comment by alrz** [comment]
@AdamSpeight2008 I think `CompilerTools.sln` is what you're looking for.

**Comment by gafter** [comment]
@AdamSpeight2008 Those generated files are produced as a result of processing `Syntax.xml` for the syntax trees and `BoundNodes.xml` for the bound trees. You usually want to edit the `.xml` file to cause a change to be made in the generated sources.
