### ISSUE TITLE
Improve the first time experience using tuples in dev15

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#13375]
As things stand, a new user of dev15 trying tuples will get a compiler error for missing reference to ValueTuple (in most cases).
The solution is to reference the nuget package.

Update: We’re going to go with option 2 below (offering a code fix to add the nuget reference).
- [ ] We’ll update the CodeFix to recognize the specific errors from this case.
- [ ] We are already planning on splitting the Add NuGet package into MS specific packages and 3rd parties and to enable the MS specific ones by default.
- [x] We'll update the compiler to produce a specific error code for missing ValueTuple. https://github.com/dotnet/roslyn/issues/13504
- [ ] The meta-package for dotnet core targeting netstandard 2.0 should reference the ValueTuple package (even though it is not part of that standard) https://github.com/dotnet/standard/issues/22

---

The only case where you would not have such error is when you’re targeting .Net framework 4.7 (or whatever high enough version that includes ValueTuple in mscorlib) and you have that framework installed.

Some options for addressing that:
1)  Add a reference to the nuget package in C# project templates
2)  Offer a code fix/suggestion to help the user add a nuget package
3)  Mention the nuget package in the compiler error message

Kevin solved implemented option (1) for F#. The F# templates were updated to include a nuget reference to the ValueTuple package by default.
The idea is that once an mscorlib is available with ValueTuple, the templates will have to be updated again to be conditional on the target ("if you target 4.7, then you don't need to reference the nuget package").

From discussion with Dave Kean and Cyrus, this template approach (1) may not be easy or desirable for C#.
Even having a code action to guide the user in adding this nuget reference may not be a good solution, as nuget may not be installed.

---

Some information from Kevin:
PR: files
https://github.com/Microsoft/visualfsharp/pull/1473/files

Importand bits:

Packages.config
https://github.com/KevinRansom/visualfsharp/blob/f582728ee85cc0d81c425109527aa30a5ac4410c/vsintegration/ProjectTemplates/NetCoreProject/Template/packages.config

Project file changes:  

https://github.com/Microsoft/visualfsharp/pull/1473/files#diff-359003143cb8ecbece4bf9d48dfac68bR43

**Comment by jcouv** [comment]
We’re going to go with option 2.

1.	We’ll update the CodeFix to recognize the specific errors from this case.
2.	We are already planning on splitting the Add NuGet package into MS specific packages and 3rd parties and to enable the MS specific ones by default.
3.     We'll update the compiler to produce a specific error code for missing ValueTuple.

**Comment by jcouv** [comment]
@CyrusNajmabadi Are you the right person to assign the remaining issues to (splitting and updating the code fix)?

**Comment by CyrusNajmabadi** [comment]
PR available here: https://github.com/dotnet/roslyn/pull/15014

However, there is a problem as the NuGet API we call into will not install a pre-release version of the package.  Talkgin to the nuget guys to see what we can do about that.

**Comment by CyrusNajmabadi** [comment]
Pinging @Pilchie @srivatsn for visibility on this.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/15177
