### ISSUE TITLE
Recognize task-like types by the presence of an AsyncBuilderAttribute

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#13370]
Recognize task-like types by the presence of an `AsyncBuilderAttribute` rather than a static `CreateAsyncMethodBuilder` method.

See https://github.com/dotnet/roslyn/issues/10902#issuecomment-242428870.

**Comment by stephentoub** [comment]
ValueTask changes are here:
https://github.com/dotnet/corefx/pull/11140

**Comment by ljw1004** [comment]
Finished with PR #13405
