### ISSUE TITLE
(feature request) Allow return [method name] to work with returning void

### ISSUE THREAD

**Issue by user1568891** [dotnet/roslyn#13377]
I am inspired by the planned improvements to C# that streamline code and as a fan of this idea thought it would be better as a GitHub issue than a UserVoice. Please let me know if I am in error.

**Expected Behavior**:

It would be nice if methods that return *void* could call other *void* methods in their return, just like an method that actually returns a value can.

The idea is that instead of having to do this:

```c#
	if (product == null) 
	{ 
		Log("Product not found: " + code); 
		return; 
	}
```
You could write this:
```c#
	var product = Products.Load(code); 
	if (product == null)  
		return Log("Product not found: " + code); 
```
Full context of code:
```c#
	public void SetProductDiscontinued(string code) 
	{ 
		var product = Products.Load(code); 
		if (product == null) 
		{ 
			Log("Product not found: " + code); 
			return; 
		}
	}
```
It would be another nicety that would streamline code a little more.

Original UserVoice: https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/7720836-consider-void-as-a-valid-return-value

**Comment by Joe4evr** [comment]
Dupe of #11330 (title not entirely indicative).

**Comment by user1568891** [comment]
Thanks @Joe4evr - I searched for this idea before creating this but didn't find it. It looks like this is a sort of subset of the other request though - the op on that one seems to want any type where I just want it to work with void, which was mentioned in the comments by others. Should I just add a comment on that one or keep this one as an alternative? It seems like a lot of commentators on that one are more comfortable with void - only.

**Comment by Joe4evr** [comment]
The other thread evolved into "At least allow `return voidMethod();` as a syntactic sugar statement inside other void methods", which is why I said that the title isn't indicative, so I'd say move it over there.

**Comment by user1568891** [comment]
Sounds good - thanks!

**Comment by Thaina** [comment]
@user1568891 No I'm not. What I said return anything is it can let you return anything but don't give it back out of the function

I already state that if there are code like this

```C#
void A()
{
    return 0;
}

A(); // will work fine
int a = A(); // will compile error here, that void not give you int, it just allow return int
```

Why? because sometimes we have a function that return int. But we don't really need its value

```C#
string sb;
int AppendInt(int i) // It just return current length of appended string
{
    sb += i;
    return sb.Length;
}

void AppendNumber(object anyNumber)
{
    if(anyNumber is int)
        return AppendInt((int)anyNumber);
}
```

But it just got people confuse that I want it to return number. Which is never. Just because I mention JS they got furious and press downvote without understand anything
