### ISSUE TITLE
Error combining nullable and implicit operators

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#13380]
Consider the following code

``` csharp
public class Class1
{
    public Class1()
    {
        var a = new Registration<Something>();
        var x = (a == Something.Bad);                    //this line fails in VS2015.3
    }
}

public struct Registration<T> where T : struct
{
    public static implicit operator T? (Registration<T> registration)
    {
        return null;
    }
}

public enum Something
{
    Good,
    Bad
}

```

This compiled fine in VS 2013 and VS 2015 Update 2 (not fully verified).  Need to make sure we fix this regression for the next version.

**Comment by gafter** [comment]
This appears to be broken by #9543. This PR shows why the optimization in overload resolution is not correct.

**Comment by gafter** [comment]
@theoy Please stop editing our bugs. I suspect you have some integration (e.g. Waffle) that is causing you to auto-edit our bugs.

**Comment by theoy** [comment]
> @theoy Please stop editing our bugs. I suspect you have some integration (e.g. Waffle) that is causing you to auto-edit our bugs.

🙀 

Holy smokes! I don't recall touching this bug at all, so I think you're right about it likely being related to Waffle. Not sure how much Waffle is used by the Roslyn team at the moment, but it could be they are hitting this bug (waffleio/waffle.io#1761), specifically when the Waffle board has been configured with more than one repository (in Roslyn's case, someone has added the analyzer project as a secondary source).

I hope it doesn't happen anymore, let me know if you see any other issues that appear touched "by me" (sadly, I had authorized Waffle for my other projects).

**Comment by jaredpar** [comment]
Thanks @theoy

We ended up having a lot of cases like this. Waffle did seem to be the common denominator. No one we contacted knew why this was happening. Eventually we changed permissions and it seems to hace calmed down.
