### ISSUE TITLE
CSharpFixAllOccurrences intermittent failure due FixAll preview changes modal dialog 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#13384]
**Failure:**
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/450/

**Screenshots:**
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/450/artifact/Open/Binaries/Release/Screenshots/2016-08-25_19-47-56_42%20-%20Exception%20System.Runtime.Remoting.RemotingException.png

http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/450/artifact/Open/Binaries/Release/Screenshots/2016-08-25_19-47-55_28%20-%20Modal%20Dialog.png

I am not sure if this is a test issue or a product issue (the dialog seems to hang around even after VS closed).

**Comment by rchande** [comment]
Closing because artifacts have been deleted. Please reopen if it happens again.
