### ISSUE TITLE
Implement "throw" expression

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13389]
From the [pattern-matching spec](https://github.com/dotnet/roslyn/blob/master/docs/features/patterns.md):

## Throw expression

We extend the set of expression forms to include

```antlr
throw_expression
    : 'throw' null_coalescing_expression
    ;

null_coalescing_expression
    : throw_expression
    ;
```

The type rules are as follows:

- A *throw_expression* has no type.
- A *throw_expression* is convertible to every type by an implicit conversion.

The flow-analysis rules are as follows:

- For every variable *v*, *v* is definitely assigned before the *null_coalescing_expression* of a *throw_expression* iff it is definitely assigned before the *throw_expression*.
- For every variable *v*, *v* is definitely assigned after *throw_expression*.

A *throw expression* is permitted in only the following syntactic contexts:
- As the second or third operand of a ternary conditional operator `?:`
- As the second operand of a null coalescing operator `??`
- As the body of an expression-bodied lambda or method.

**Comment by leppie** [comment]
Wow, that was fast :D

**Comment by gafter** [comment]
Well, it has already been implemented on a branch, so it's mostly a matter of pulling the implementation into master.

**Comment by leppie** [comment]
Not sure why this has to be complicated so much in term of semantics. 

Why can't it just be equivalent to the following pseudo macro/inlined-code/(even a method would work)?
```
T Throw<T>(THROW-EXPR)
{
  throw THROW-EXPR;
}
```
The only problem with this is when `Throw` is in a tail (call) position (meaning you lose some call stack info), but that is not relevant for C#.

**Comment by gafter** [comment]
@leppie What seems complicated to you? Its runtime semantics are equivalent to that. But its syntax, precedence, and static semantics have to be specified. We don't want "e1 ?? throw e2" to fail because it can't infer the type parameter of your method, for example.
