### ISSUE TITLE
Allow adding a setter when overriding an abstract read-only property

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/roslyn#13399]
Currently, this doesn't work:

```
abstract class Base
{
    public abstract string Name { get; }
}

class Derived : Base
{
    public override string Name { get; set; }
}
```

> CS0546 'MyNamespace.Derived.Name.set': cannot override because 'MyNamespace.Base.Name' does not have an overridable set accessor

This is a natural usage pattern and should be allowed. Currently the workaround is to make a non-automatic property and set the field directly, which is a bit ugly.

**Comment by Richiban** [comment]
I think that 

```
abstract class Base
{
    public abstract string Name { get; }
}

class Derived : Base
{
    public string Name { override get; set; }
}
```

might be useful if you wish to communicate the fact that the base class does not define a setter. In which case 

```
public override string Name { get; set; }
```
would actually be a kind of shorthand for:
```
public string Name { override get; override set; }
```

**Comment by alrz** [comment]
Duplicate of #9482

**Comment by thomaslevesque** [comment]
> Duplicate of #9482

Ah, thanks. I suspected it had already been suggested, but couldn't find it... I'll close this one.
