### ISSUE TITLE
Proposal: Bind to existing variables in patterns

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#13400]
### Proposal: Bind to existing variables in patterns

Ability to assign the target expression to existing variables (rel. #8990, #9005):

``` cs

public static bool Member(this Expression @this, out Expression expr, out string memberName) {
  if(@this is MemberExpression { Expression: var exprTemp, Member: { Name: var memberNameTemp } }) {
    expr = exprTemp;
    memberName = memberNameTemp
    return true;
  } else {
    expr = null;
    memberName = null;
    return false;
  }
}

```

We can rewrite this method in one line if we could assign the target expression to existing variables inside the pattern.

``` cs
public static bool Member(this Expression @this, out Expression expr, out string memberName) {
  return @this is MemberExpression { Expression: out expr, Member: { Name: out memberName } }
}
```

That's it. If the pattern-match failed, variables will be assigned to their `default` value, therefore, they are definitely assigned before leaving the method and no `CS0177` shall be raised.

This is specifically useful with #11293 and #13401.

Note: When we are matching against the static type of a property of another property it could be simplified further using the dot operator:

``` cs
public static bool Member(this Expression @this, out Expression expr, out string memberName) {
  return @this is MemberExpression { Expression: out expr, Member.Name: out memberName }
}
```

etc.

**Comment by HaloFour** [comment]
I agree.  With deconstruction following the `out` parameter route and possibly active patterns as well I think it would make for some succinct one-liners to be able to match and deconstruct directly into existing variables.  As pattern variables are no longer readonly I think that the inconsistency concerns are no longer a factor.

**Comment by alrz** [comment]
Part of
