### ISSUE TITLE
Microsoft.CodeAnalysis.VisualBasic.UnitTests.MyTemplateTests.MyWinformApp  failing.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#13404]
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/3059/testReport/junit/Microsoft.CodeAnalysis.VisualBasic.UnitTests/MyTemplateTests/MyWinformApp/

Stacktrace

MESSAGE:
Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : \r\nExecution failed for assembly 'D:\j\workspace\windows_debug---09a07fba\Binaries\Temp\'.\r\nException: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details. The error is: Font 'Microsoft Sans Serif' does not support style 'Regular'. ---> System.ArgumentException: Font 'Microsoft Sans Serif' does not support style 'Regular'.\r\n at System.Drawing.Font.CreateNativeFont()\r\n at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)\r\n at System.Drawing.Font..ctor(FontFamily family, Single emSize)\r\n at System.Drawing.SystemFonts.get_DefaultFont()\r\n at System.Windows.Forms.Control.get_DefaultFont()\r\n at System.Windows.Forms.Control.GetDefaultFontHandleWrapper()\r\n at System.Windows.Forms.Control.get_FontHandle()\r\n at System.Windows.Forms.ContainerControl.GetFontAutoScaleDimensions()\r\n at System.Windows.Forms.ContainerControl.get_CurrentAutoScaleDimensions()\r\n at System.Windows.Forms.ContainerControl.get_AutoScaleFactor()\r\n at System.Windows.Forms.ContainerControl.PerformAutoScale(Boolean includedBounds, Boolean excludedBounds)\r\n at System.Windows.Forms.ContainerControl.PerformNeededAutoScaleOnLayout()\r\n at System.Windows.Forms.ContainerControl.OnLayoutResuming(Boolean performLayout)\r\n at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)\r\n at Form1.InitializeComponent()\r\n at Form1..ctor()\r\n --- End of inner exception stack trace ---\r\n at My.MyProject.MyForms.Create__Instance__[T](T Instance)\r\n at Form1.Main()\r\n---- System.InvalidOperationException : An error occurred creating the form. See Exception.InnerException for details. The error is: Font 'Microsoft Sans Serif' does not support style 'Regular'.\r\n-------- System.ArgumentException : Font 'Microsoft Sans Serif' does not support style 'Regular'.

**Comment by CyrusNajmabadi** [comment]
I am disabling the test due to flakeyness.

**Comment by gafter** [comment]
Dup of (already fixed) #11278
