### ISSUE TITLE
No intellisense after new in object creation expression [braces case]

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#13402]
**Version Used**: 25618.00/2.0.0.60808

**Steps to Reproduce**:

``` C#
class Program
{
    static void Main(string[] args)
    {
        Program p = new |
        { }
    }
}
```

**Expected Behavior**:
`Program` preselected in autocomplete list.

**Actual Behavior**:
List not offered and nothing preselected if invoked. More evident if different type is used last, e.g.

``` C#
Dictionary<float, float> f = new |
{ }
```

This is another, like fourth or fifth case of the "no intellisense after new keyword" problem. Rather than hitting the individual things that can possible appear after `new` and exempting them, couldn't this be perhaps done from the other end?

cf. #2836 #12755
/cc @balajikris @rchande

**Comment by rchande** [comment]
This is fixed in post-dev15.
