### ISSUE TITLE
Extract Method: extracted block should intersect selection

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#13416]
I select `person` to inline it but my first quick fix is to Extract Method? And what it extracts isn't even what I selected...

![image](https://cloud.githubusercontent.com/assets/1402694/18022496/3883fdc6-6ba4-11e6-9436-a45072b9c474.png)

``` C#
    static void Main(string[] args)
    {
        Person [|person|] = new Person("ScottGu");
    }    

    public class Person
    {
        public Person(string name) { this.Name = name; }
        public string Name { get; }
    }



```

**Comment by Pilchie** [comment]
Extract method is available because we extend the selection to the nearest span that can be extracted.  However, we should order Inline Temporary above extract method when both are available.

**Comment by kuhlenh** [comment]
@jmarolf see also https://github.com/dotnet/roslyn/issues/12683 if you happen to be looking at inline temp

**Comment by ryzngard** [comment]
I'm going to mark this as resolved. In current builds extract method is lower

![image](https://user-images.githubusercontent.com/475144/210025111-4da02ecf-48cf-4ba5-b846-96bd7bc59cdd.png)
