### ISSUE TITLE
Breadcrumb for ".NET Compiler Platform SDK" should not appear in Visual C# root

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#13418]
As part of the work to clean up the templates, we're only putting the core templates (App entry points + one library) in the Visual C# root. 

The breadcrumb for the platform SDK should not appear in the root:

![image](https://cloud.githubusercontent.com/assets/1103906/18022857/7e77413c-6ba7-11e6-807d-8609ef4dfc60.png)

**Comment by Pilchie** [comment]
Agree that this should show up only under the `Extensibility` node.

**Comment by jmarolf** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/15311
