### ISSUE TITLE
Introduce alias for using directives

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#13423]
``` cs
[||]using Some.Namespace;
class C { public void M(SomeType p) { .. } }
```

->

``` cs
using {|Rename:Alias|} = Some.Namespace;
class C { public void M(Alias.SomeType p) { .. } }
```

EDIT: Alternatively we could have a fix for ambiguous types that suggest to add an alias for the corresponding namespace.

**Comment by HaloFour** [comment]
You want an F# array in the middle of your alias?

I have no idea what the syntax is attempting to accomplish (descriptions would be nice), but it could print money and I would still argue that such syntax has no place in C#.

**Comment by alrz** [comment]
@HaloFour this is the syntax used to test refactorings. It means that if you press Ctrl+. in the `[||]` position (no selection is needed) you will get the code below which is `{||}` pre selected to rename the alias.

**Comment by HaloFour** [comment]
@alrz Gotcha.  Nevermind the complaint then.  😁

**Comment by Pilchie** [comment]
Thanks for the suggestion - I can see how it would be useful.

**Comment by alrz** [comment]
Closing in favor of https://github.com/dotnet/roslyn/issues/23373
