### ISSUE TITLE
IDE terminology

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#13426]
I think it would be helpful if there was a page with the most common IDE terminology Roslyn is involved with or feeds to, as either I don't get it right or it is used inconsistently, perhaps as it evolved.

Examples of terminology I am thinking about:
- the light bulb and its entries (is it quick action? quick fix? refactorings? smart tag?) and previews
- the colored bars on the left margin of the code
- what is tooltip, quick info, intellisense vs. autocompletion, filters
- the three dropdowns on top of the editor
- squiggles that mark code
- suggestion / completion mode
- codelens and their anatomy
- collapsible blocks and the three dots
- the dimmed code (simplifications)

etc. That would be useful for reporting bugs as well as communicating new features.

**Comment by Pilchie** [comment]
@miloush Let me know what you think of #13429.

**Comment by miloush** [comment]
@Pilchie That was fast! I think it is a great start and has the most important things in it. Couple of screenshots would be nice future addition but I am sure it will evolve. Thanks!

**Comment by miloush** [comment]
Is this available somewhere other than through searching the repository? I cannot find a link in the Wiki for example...

**Comment by Pilchie** [comment]
I added a link to it from the wiki home page, and the sidebar page.
