### ISSUE TITLE
Conversion objects no longer cached.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13428]
A recent change in support of tuples unintentionally removed the cache of trivial conversion objects, so that they are now always created anew. This probably created a (space and/or time) performance regression, but we were not measuring at the time. The cache should be restored.

See https://github.com/dotnet/roslyn/commit/818ae18e7c53b5507aeff7030aa37573345951ac
and its changes to `src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversion.cs`

**Comment by VSadov** [comment]
This is ByDesign. Those trivial conversion objects are structs with trivial construction logic (just storing ConversionKind). 
The caches were likely created when conversions were classes to reduce allocations. There is no much point to cache struct instances though.
