### ISSUE TITLE
IDE should not offer to "introduce local" for a throw expression

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13435]
In code such as

``` cs
class Program
{
    public static void M3() => throw null;
}
```

If you select `throw null`, and hit control-., VS will offer to "introduce local" for `throw null`. However, it is not possible to introduce a local for a throw expression, and VS should not offer to do that.

**Comment by jcouv** [comment]
Queued a PR with a fix (https://github.com/dotnet/roslyn/pull/22666).

**Comment by jcouv** [comment]
Fixed in post-dev15.5-contrib branch
