### ISSUE TITLE
Solution lifetime tests are flaky

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#13433]
Failed in the following run:

http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_release_unit64/lastCompletedBuild/testReport/Microsoft.CodeAnalysis.UnitTests/SolutionTests/TestGetSyntaxRootDoesNotKeepRootAlive/

Assigning to @jasonmalinowski since he recently made changes in this area (feel free to reassign if this is not appropriate).

**Comment by natidea** [comment]
Another SolutionTests flaky failure. May be related:
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_release_unit64_prtest/499/
```
Stacktrace
MESSAGE:
Reference should have been released but was not.\r\nExpected: False\r\nActual: True
+++++++++++++++++++
STACK TRACE:
at Roslyn.Test.Utilities.ObjectReference`1.AssertReleased() 
in D:\j\workspace\windows_relea---0f38875e\Open\src\Test\Utilities\Desktop\ObjectReference.cs:line 61 
at Microsoft.CodeAnalysis.UnitTests.SolutionTests.TestRecoverableSyntaxTree(Solution sol, DocumentId did) 
in D:\j\workspace\windows_relea---0f38875e\Open\src\Workspaces\CoreTest\SolutionTests\SolutionTests.cs:line 1030 
at Microsoft.CodeAnalysis.UnitTests.SolutionTests.TestRecoverableSyntaxTreeCSharp() 
in D:\j\workspace\windows_relea---0f38875e\Open\src\Workspaces\CoreTest\SolutionTests\SolutionTests.cs:line 996
```

**Comment by 333fred** [comment]
Three more SolutionsTests failures:
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_debug_unit32/983/
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_release_unit64/978/
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit64/893/

**Comment by CyrusNajmabadi** [comment]
These tests were removed and we no longer have recoverable trees.  closing this out.
