### ISSUE TITLE
Publish 2.0.0-beta4 to NuGet

### ISSUE THREAD

**Issue by aelij** [dotnet/roslyn#13431]
The latest beta isn't on NuGet. Could you please publish it?

**Comment by Pilchie** [comment]
Tag @mattscheffer

**Comment by jasonmalinowski** [comment]
Since @shyamnamboodiripad is out, @natidea let's see if we can start to pick this one up.

**Comment by shyamnamboodiripad** [comment]
Tagging @jinujoseph

**Comment by jasonmalinowski** [comment]
This was done by @jinujoseph.
