### ISSUE TITLE
[Code Style] Implement a way to change style settings 

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#13439]
We are going to have a set of "style defaults" but are missing a discoverable path for users to go from a code style error in the editor to the configurable settings. 

At one point in time we had built this, so let's iterate on that:
![image](https://cloud.githubusercontent.com/assets/1402694/18065300/30f390b2-6de8-11e6-99f1-d89d510ca34d.png)

**Comment by dpoeschl** [comment]
/fyi: @balajikris as we've been chatting about this

**Comment by balajikris** [comment]
thanks @kuhlenh and @dpoeschl . I also think this we got this feedback in the UX Review, which I'm going to look, during this sprint.

**Comment by dpoeschl** [comment]
@balajikris Aside from making it appear on all of the code style fixers, was there feedback about the actual UI for it? It's pretty... developery... right now (my own fault)

**Comment by balajikris** [comment]
No, I don't think we discussed the UI for this. My review notes show the same concern that Kasey brings up in this bug's description. That going from the suggested lightbulb to the option setting that caused it, is missing.

**Comment by AdamSpeight2008** [comment]
Could be made less prominent, similar to `Preview changes`.
Is there an option not to display it as we?

**Comment by Pilchie** [comment]
Hey @kuhlenh: I think you and @dpoeschl did some thinking here yesterday.  Can you attach a mockup of your plan and pass along to him?

**Comment by kuhlenh** [comment]
![image](https://cloud.githubusercontent.com/assets/1402694/18294874/5b466cd0-7451-11e6-8495-ed35699b54e2.png)


This was what we mocked up for V1....

**Comment by Pilchie** [comment]
Did we also talk about a way to change severity (or at least disable) from under the "Suppress" menu?

**Comment by kuhlenh** [comment]
![image](https://cloud.githubusercontent.com/assets/1402694/18320577/57e1d744-74df-11e6-8706-c3b90fd3f2e5.png)

@dpoeschl and I were thinking something like this. We didn't want to use the Suppress menu because we figured it would get too long. Happy to hear other suggestions here though!

**Comment by Pilchie** [comment]
I like that UI, I just think it's odd to have a suppress menu that only includes *some* of the ways to suppress diagnostics...

**Comment by dpoeschl** [comment]
@CyrusNajmabadi suggests we change the verbiage from "Change Options" to something that sounds less generic. @kuhlenh thoughts?

**Comment by balajikris** [comment]
suggestion: `configure style` or `configure <name> style` ?

**Comment by kuhlenh** [comment]
along @balajikris's suggestion: `configure style options` or `change style options`

**Comment by CyrusNajmabadi** [comment]
Closing out as we have a UI for this now.
