### ISSUE TITLE
Remove XML Node Code Fix Bug

### ISSUE THREAD

**Issue by Hosch250** [dotnet/roslyn#13436]
**Version Used**: 

VS 15 Preview 4

**Steps to Reproduce**:

1. Enable the XML doc comment diagnostics.
2. Enter the following code (or its VB.NET equivalent):

```
/// <param name="a"></param> <param name="b"></param>
public void Foo(string b) {}
```

**Expected Behavior**:

After running the code fix to remove the `param` node for `a`,  you should get:

    /// <param name="b"></param>
    public void Foo(string b) {}

**Actual Behavior**:

You get the following broken code:

     <param name="b"></param>
    public void Foo(string b) {}

Credit to @svick for pointing this out here: http://codereview.stackexchange.com/a/139771/34073

**Comment by Hosch250** [comment]
This may be as simple as ensuring the node has a newline in the trailing trivia when deciding whether to remove the `'''` or `///`.  If this is not addressed before I have time to handle it, I will; however, I may not be able to handle this for a while.

**Comment by AdamSpeight2008** [comment]
@Hosch250   You could use the `preceedingtrivia` from the removed `<param ` and prepend it to the second.

**Comment by Hosch250** [comment]
@AdamSpeight2008 I'm pretty sure that what is currently happening is that I'm just removing both the `///` and XML node separately, and I just need to not remove the `///` node for this case.

See: https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/DocumentationComments/CodeFixes/AbstractRemoveDocCommentNodeCodeFixProvider.cs#L62

**Comment by Pilchie** [comment]
@Hosch250 are you planning on working on a fix for this?

Assigning to @CyrusNajmabadi to keep an eye on.

**Comment by Hosch250** [comment]
Yeah, eventually.  I'm busy with college just now, although I have enough free time to handle it in a couple days.

**Comment by Pilchie** [comment]
Thanks!  As far as I'm concerned there is no rush here.  Having multiple `<param>` tags on the same line is a bit of an edge case anyway.

**Comment by CyrusNajmabadi** [comment]
I'll give you a few days.  If you don't have time though, i can pick this up.

**Comment by CyrusNajmabadi** [comment]
@Hosch250 Want me to take this?

**Comment by Hosch250** [comment]
Sure.  I'm busy with school, learning F#, and getting my current PR in acceptable condition.

**Comment by CyrusNajmabadi** [comment]
@Hosch250 I did the work here.  We're shutting down on RC soon.  Thanks!

**Comment by Hosch250** [comment]
Thank you, @CyrusNajmabadi!  Sorry I was unable to get this done for you.
