### ISSUE TITLE
[Code Action] 'Convert to interpolated string' doesn't deal with trivia correctly

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#13443]
case in point: 
![image](https://cloud.githubusercontent.com/assets/1402694/18067832/73f7c88c-6df3-11e6-8dac-03ea7eeafff2.png)

**Comment by kuhlenh** [comment]
Ignore this. Turns out I didn't disable C# Essentials and our built-in version doesn't repro this

**Comment by jmarolf** [comment]
@kuhlenh thank goodness
