### ISSUE TITLE
[VB] Patterns / Additional Case Clauses

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#13440]
Is VB going to support patterns? 
What about guard clauses? eg `Case ... .... When boolEpxr`
What about type matching and value manifesting? eg `TypeIs String As str`
How will tuple clause be handled?

``` vb
Select Case obj
  Case TypeIs String As str When str IsNot Nothing
    ' do stuff
  Case ( TypeIs Boolean As valid, TypeIs Int32 As i32 ) When ( valid AndAlso ( i32 > 0 ) )
   ' manifesting into Tuple(Of Boolean, Int32 ), which has named elements ( valid:= , i32:= ) 
End Select
```

**Comment by markhurd** [comment]
BTW In VB would that `When str IsNot Nothing` clause be redundant like I believe it would be in C#'s scenario? Clearly, VB has different issues regarding `Nothing` when considering strings, but has this been confirmed (because it definitely makes some sense for other reference types to not match `Nothing`)?

**Comment by AdamSpeight2008** [comment]
@markhurd not necessarily. It makes more sense to leave the **when clause** as a general boolean expression. 

```vb
Select Case obj
  Case TypeIs String As str
   ' Manifests variable, or set value of. eg  str = DirectCast( obj, Sting )
   ' Note: str could be null ( eg default(String) )
    Select Case True

      Case Else When str IsNot Nothing
	' Handle non null string case

      Case Else When str Is Nothing
	'Handle null string case

    End Select

End Select
```    

'TypeIs obj As T` would be also applicable in if statements.

```vb
If TypeIs obj As str Then
  ' str = DirectCast( obj , String )
Else

End If
```

**Comment by AdamSpeight2008** [comment]
[(Ported to VBLang)](https://github.com/dotnet/vblang/issues/24)
