### ISSUE TITLE
Test coverage for SourceLocalSymbol binding a for statement

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13458]
In https://github.com/dotnet/roslyn/pull/13274#discussion_r76849261 @AlekseyTs questioned whether we have tests covering the binding of type-inferred deconstruction variables in a for statement. If we do not have such tests, we should.

Similarly, in https://github.com/dotnet/roslyn/pull/13274#discussion_r76849303 we have a similar question for foreach loops.

**Comment by jcouv** [comment]
I confirmed that the branch of `DeconstructionLocalSymbol.InferTypeOfVarVariable` in question (which relates to ForEachVariableStatement) is indeed covered already.

For example by `ForEachStringDeclarationWithImplicitVarType`, `ForEachIEnumerableDeclarationWithImplicitVarType`, and several other tests.

The branch that relates to `ForStatement` no longer exists.

```C#
            protected override TypeSymbol InferTypeOfVarVariable(DiagnosticBag diagnostics)
            {
                // Try binding enclosing deconstruction-declaration (the top-level VariableDeclaration), this should force the inference.
                switch (_deconstruction.Kind())
                {
                    case SyntaxKind.SimpleAssignmentExpression:
                        [...]
                        break;

                    case SyntaxKind.ForEachVariableStatement:
                        throw new Exception();
                        Debug.Assert(this.ScopeBinder.GetBinder((ForEachVariableStatementSyntax)_deconstruction) == _nodeBinder);
                        _nodeBinder.BindForEachDeconstruction(diagnostics, _nodeBinder);
                        break;

                    default:
                        throw ExceptionUtilities.UnexpectedValue(_deconstruction.Kind());
                }

                Debug.Assert((object)this._type != null);
                return this._type;
            }
```
