### ISSUE TITLE
'Add missing cases' quick fix should introduce balanced braces only

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#13455]
**Version Used**:  25618.00/2.0.0.60808

**Steps to Reproduce**:
```C#
using System;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            ConsoleModifiers m;
            switch (m) // quick fix offered here
        }
    }
}
```
Invoke the quick fix to add missing cases.
(I have automatic brace completion disabled if that changes anything)

**Expected Behavior**:
```C#
namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            ConsoleModifiers m;
            switch (m)
            {
                case ConsoleModifiers.Alt:
                    break;
                case ConsoleModifiers.Shift:
                    break;
                case ConsoleModifiers.Control:
                    break;
            }
        }
    }
}
```
**Actual Behavior**:
```C#
namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            ConsoleModifiers m;
            switch (m)
            {
                case ConsoleModifiers.Alt:
                    break;
                case ConsoleModifiers.Shift:
                    break;
                case ConsoleModifiers.Control:
                    break;
            } // stolen brace
        } // stolen brace
    // missing brace
}
```
If the quick fix inserts `{`, it should also come up with corresponding `}`. Current quick fix solution does not compile and breaks all code following.

**Comment by Pilchie** [comment]
Tagging @Hosch250 - do you want to take a look at this?

**Comment by CyrusNajmabadi** [comment]
IIRC, we looked at this when the feature was created.  One of the problems is that from the parser's perspective, it has no idea what ```}```s belong to what.  So, in the original code, the ```}``` following the empty switch *does* get parsed as the close curly of the switch.  As such, it's not 'missing' and does not get filled in by refactoring.  Now, one thing we could try to do would be to walk the containers and see if any of them are missing their close curly.  If they are, then we could consider something like rewriting the entire spine, reattaching each curly to teh construct higher than it.  Akward, but doable.

**Comment by Hosch250** [comment]
@Pilchie I would, except I'm busy with college just now.  If it is still around when I'm available, I'll do it.

**Comment by miloush** [comment]
@CyrusNajmabadi Does it need to be that complex? If the rule was "if inserting opening one, insert closing one too", than this would break the following scenario:

```C#
using System;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            ConsoleModifiers m;
            switch (m) // quick fix offered here
             } // switch one
        }
    }
}
```
but somehow this looks like not eligible for reporting. Also, the number of errors before and after the quick fix would stay the same.
