### ISSUE TITLE
Tests needed for out variables in declarators in for loop.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13459]
In https://github.com/dotnet/roslyn/pull/13274#discussion_r76849977 @AlekseyTs asked about test coverage for the error case of out variables and pattern variables (illegally) declared in declarators in a for loop. We should ensure we have such tests to ensure the compiler behavior is sane.

See also https://github.com/dotnet/roslyn/pull/13274#discussion_r76852787

**Comment by AlekseyTs** [comment]
I think there is actually a bug in this scenario.
