### ISSUE TITLE
Issue binding (erroneous) variables in a declarator argument list.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13460]
In https://github.com/dotnet/roslyn/pull/13274#discussion_r76852091 @AlekseyTs noted that the error situation of variables being declared inside a declarator argument list can have more precise binding behavior, so that some (erroneous) variables declared in that context will bind to a valid type, while others will be assigned an error type. This change would likely simplify the code.

**Comment by AlekseyTs** [comment]
This issue has been addressed

**Comment by gafter** [comment]
As noted in #13660, tests are missing for this bug fix.

**Comment by AlekseyTs** [comment]
Additional testing for Patterns is tracked by #13660.
