### ISSUE TITLE
Wrong number of overloads in QuickInfo

### ISSUE THREAD

**Issue by antonssonj** [dotnet/roslyn#13462]
**Version Used**: 
VS2015, Update 3
**Steps to Reproduce**:

```
public class Program
 { 
    static void Main(string[] args) 
    {
        new T().M$$();
    }
}
public class T
{
    public void M() { }
    public static void M(int i) { }
}
```

When I hoover over the M in the main method a quickinfo with + 1 overload is shown.

**Expected Behavior**:
![image](https://cloud.githubusercontent.com/assets/12250134/18104126/e5616468-6ef9-11e6-9626-d01286ea8f96.png)
**Actual Behavior**:
![image](https://cloud.githubusercontent.com/assets/12250134/18104136/f42a8e02-6ef9-11e6-8c73-a18174e57530.png)

**Comment by CyrusNajmabadi** [comment]
Need info if this is actually an issue for the ecosystem.

**Comment by sharwell** [comment]
Removing Need More Info label as this is already reproducible and actionable.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.  We mention that there are many overloads here.  Doesn't seem like an issue.
