### ISSUE TITLE
Surrogate pairs not recognized in identifiers.

### ISSUE THREAD

**Issue by mishra14** [dotnet/roslyn#13474]
I am working on [GB18030](https://microsoft.sharepoint.com/teams/DD_Tenets/World%20Ready/Releases/SitePages/Dev15GB18030.aspx) certification prep for NuGet Visual Studio UI. 

It seems that symbols/characters from [CJK Unified Ideographs Extension B](http://jrgraphix.net/r/Unicode/20000-2A6DF) are not accepted as/in valid C# namespace in Visual Studio.

But according to the specs [here](https://msdn.microsoft.com/en-us/library/aa664670.aspx), they should be since CJK Extension B falls into the [Lo class of unicode](http://www.fileformat.info/info/unicode/category/Lo/list.htm).

Repro -
1. Create new console app in VS.
2. Change the namespace or class name to a combo of CJK ex B characters - 𠀀𠀁𠀂𠀃 (using the first 4 here)
3. Observe that VS throws an error.

More ref - [SO Question](http://stackoverflow.com/questions/950616/what-characters-are-allowed-in-c-sharp-class-name)

//cc : @rrelyea

**Comment by ufcpp** [comment]
@mishra14 The roslyn compiler doesn't accept surrogate pairs. As long as the compiler uses `string` - UTF-16 based string implementation, cost of accepting them is too high.

**Comment by gafter** [comment]
Treating surrogates properly in identifiers is nontrivial, but it doesn't have to be much of a performance hit. Only when surrogates are actually used would any surrogate-related code path be taken.

**Comment by miloush** [comment]
@mishra14 I am all for supporting surrogate pairs and would have been myself pointing the specification out, except that it explicitly refers to Unicode 3.0 where there were no such surrogates...

**Comment by gafter** [comment]
@miloush More recent versions of the language specifications will refer to more recent versions of the Unicode specs. Sorry the C# 6 spec isn't out yet.

**Comment by gafter** [comment]
Actually, the older versions of the spec appear to say we should support surrogates. For example, see https://msdn.microsoft.com/en-us/library/aa664669(v=vs.71).aspx which implies that the following program should compile without error. Roslyn rejects it.

```cs
using System;
using System.Collections.Generic;
using System.Linq;

class Program
{
    public static void Main(string[] args)
    {
        int \U00020000 = 10; // http://www.fileformat.info/info/unicode/char/20000/index.htm
        Console.WriteLine(\U00020000);
    }
}
```

**Comment by gafter** [comment]
This is also reported as #9371

**Comment by jaredpar** [comment]
duping to #9731 which is the primary issue for this.
