### ISSUE TITLE
Fetch VS integration testing framework (Apex, Tao, Omni) assemblies from nuget

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#13475]
Currently we have a snapshot checked into internal repo. The snapshot however is only guaranteed to work in one specific VS version. Since we need to move to the latest build often we need to consume these from nuget packages that get automatically published by the VS build.

**Comment by gafter** [comment]
@tmat Is this referring to Roslyn (the open-source project)?

**Comment by tmat** [comment]
Yes, it's concerning our internal repo infrastructure.
