### ISSUE TITLE
Integration test AddMissingReference.xml requires FX 4.0 Targeting pack

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#13476]
The targeting pack is not present in Willow by default. FX 4.0 is also not supported anymore. Perhaps we could update the test for use a supported FX, such as 4.6. Alternatively we need to make sure our integration test machines have it installed.

**Comment by gafter** [comment]
Roslyn (the open-source project) does not have anything called `AddMissingReference.xml`

**Comment by Pilchie** [comment]
Can you look at updating the test (I assume it is just because it uses a canned project that needs it's TFM updated?)

**Comment by Pilchie** [comment]
@tmeschter do you know the current state of this test?

**Comment by Pilchie** [comment]
This is currently still marked as disabled.  Let's see if it's easy to re-enable with a project update in RTW.

**Comment by jmarolf** [comment]
Ported in https://github.com/dotnet/roslyn/pull/17515
