### ISSUE TITLE
[Feature Request] Pipeline operator in c#

### ISSUE THREAD

**Issue by jjaskulowski** [dotnet/roslyn#13479]
I suggest such syntax.

```
var y = new object();
var x1 = new {num = 1, str = "foo", y} -> $"{*.num} {*.str} " + *.y.ToString();
var x2 = new [] {1,2,3} -> Array.Sort;
var x3 = new object [] {1,2,3} -> Cast<int> -> $.Sum;
```

I don't suggest => because new tuple syntax would be interpreted as lambda declaration.

**Comment by dsaf** [comment]
It's a duplicate: https://github.com/dotnet/roslyn/issues?q=pipe%20operator

**Comment by dsaf** [comment]
Also: https://github.com/dotnet/roslyn/issues/11590#issuecomment-222162975 . Literally took 5 minutes to find.
