### ISSUE TITLE
VB Signature help shows both static and instance overloads when invoked off type name.

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#13485]
``` VB
Class C
    Public Sub M()
    End Sub

    Public Shared Sub M(x As Integer)
    End Sub
End Class

Module Module1

    Sub Main()
        C.M($$)
    End Sub

End Module
```

Invoke Signature Help at `$$`.

**Expected Behavior**:
Only the static method is shown.

**Actual Behavior**:
Both methods are shown.

From https://connect.microsoft.com/VisualStudio/feedback/details/1090905/vs-2015-shows-non-static-overloads-for-static-regex-replace-method

**Comment by antonssonj** [comment]
A similar problem in c# #13462

**Comment by CyrusNajmabadi** [comment]
Closing out as we're not chaning these vb experiences.
