### ISSUE TITLE
[caret placement] Convert method to property 

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#13492]
This is part of our effort to make our quick actions more discoverable by having them triggered where expected.

![image](https://cloud.githubusercontent.com/assets/1402694/18140831/13f7bba2-6f6c-11e6-837c-66c7ba72abcd.png)

Today, only (1-3) trigger this quick action. However, it seems very strange that we do not offer the fix in (6-8). (1-3) will let you change both the Get and Set methods, but these options are not given in (6-8).

@CyrusNajmabadi has strong opinions for why (4) and (9) should continue to offer no quick fixes. I think in general, we are in agreement on this case.

Lastly, if I highlight the method as shown in (5) and (10), I get no quick fix. Let's offer a quick fix in this case.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We should drive these from reported issues of people having problems.   Right now we've driven things based on the diagnsotic (Which makes sense) or the the refactoring helper service (to get uniform behavior).  We don't really need general issue tracking all of these.
