### ISSUE TITLE
[caret placement] Implement Interface

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#13491]
This is part of our effort to make our quick actions more discoverable by having them triggered where expected.

![image](https://cloud.githubusercontent.com/assets/1402694/18140469/7d51fd80-6f6a-11e6-8cc2-e01e14446eac.png)

Today we offer this quick action in positions (1-4). However, if I am writing a new class (as in the example above) I want to have the quick fix triggered when I am in position (5), i.e., as I am "moving forward". Note, this should only be offered if I am in an "empty" class.

For discoverability purposes, it might be kind of cool to investigate if we can have faded gray text in (5) that says 'press Ctrl+. to implement interface'.

**Comment by CyrusNajmabadi** [comment]
Note: there may be many interfaces to implement.  Keep that in mind with how you 'fix' this issue.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We should drive these from reported issues of people having problems.   Right now we've driven things based on the diagnsotic (Which makes sense) or the the refactoring helper service (to get uniform behavior).  We don't really need general issue tracking all of these.
