### ISSUE TITLE
[caret placement] Add Braces

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#13490]
This is part of our effort to make our quick actions more discoverable by having them triggered where expected.

![image](https://cloud.githubusercontent.com/assets/1402694/18098811/a57c472a-6e98-11e6-9eae-31d84d35d795.png)

Today we offer a quick action for (1), (2), and (3). However, I often will be in placement (4-6) when I realize I need to make my if-statement multi-line. As such, it would be more conducive to this "forward typing" workflow to also trigger the Add Braces quick action in (4), (5), and (6). It would also be awesome if we could tell if you completed the inner statement or not (i.e., if you haven't completed a valid statement in (4-6) when you add braces, we will leave your caret where it was when you triggered the action so that you can complete the statement; otherwise, we'll move your caret to after the last brace). 

Last thing: today, if you select the if-statement and its following line, you only trigger the quick action if your caret is in the first line (1-3). If your caret lands in (4-6) you won't get the suggestion, so let's try to make sure when you select the snippet that it doesn't matter where your cursor ends up.

**Comment by Pilchie** [comment]
I don't think it will be intuitive to users to have the valid spans change when you have completed a valid statement.  We should just show the fix throughout 4, 5, and 6.

Also - we should explore the behavior when you have `else` and `else if` blocks.  Currently you can only fix one at a time and have to move your cursor between them.  Should there be a second fix that adds braces to all of them at once?

**Comment by DustinCampbell** [comment]
How do we determine where to put the braces if I invoke the refactoring in (1-3) but I'm adding the if-statement in front of existing code? For example, I start with this.

```C#
void M(bool condition)
{
    var theNumber = 0;
    theNumber = 19 + 23;
    Console.WriteLine($"Print {theNumber}");
}
```

Now, I type an if-statement in front of the variable declaration.

``` C#
void M(bool condition)
{
    var theNumber = 0;
    if (condition)$$
    theNumber = 19 + 23;
    Console.WriteLine($"Print {theNumber}");
}
```

With the caret position at $$, where should the braces go? Obviously, wrapping the now embedded statement changes the program.

A few thoughts (which @CyrusNajmabadi and I both thought of :smile:). I suspect a mix of these would greatly improve the refactoring.

1. We could have a heuristic that look at the indentation of the next line and, if the next line is indented, wrap it in braces. E.g. it *would* wrap in this case:

``` C#
void M(bool condition)
{
    var theNumber = 0;
    if (condition)$$
        theNumber = 19 + 23;
    Console.WriteLine($"Print {theNumber}");
}
```

2. We could have heuristic that never wraps the embedded statement if the next line is blank. E.g. it *wouldn't* wrap in this case:

``` C#
void M(bool condition)
{
    var theNumber = 0;
    if (condition)$$

    theNumber = 19 + 23;
    Console.WriteLine($"Print {theNumber}");
}
```

3. We could change the behavior depending on what position the refactoring is invoked from. For example, if invoked from (1-3), it would insert braces if front of the embedded statement; if invoked from (4-5), it would wrap the embedded statement.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
