### ISSUE TITLE
Update tuple element indices and TupleElementFields API

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#13502]
Per our latest design discussion, we would give named elements an odd index (a=1, b=3, c=5) and default elements an even index (Item1=2, Item2=4, Item3=6). Other members and fields will get negative indices.

The `TupleElementFields` should be updated accordingly. For `(int a, int, int c)`, it should return three fields: one for `a`, one for `Item2` and one for `c`. We could consider making this API internal only.
The comments in the various tuple fields types should be reviewed and updated accordingly.

Relates to this PR: https://github.com/dotnet/roslyn/pull/13463

**Comment by jcouv** [comment]
This is a duplicate of https://github.com/dotnet/roslyn/issues/13229

**Comment by jcouv** [comment]
Neal clarified that just coming up with an indexing strategy would not meet the public API needs for #13229. 
So this here issue is for the indexing strategy, which is internal only.

**Comment by VSadov** [comment]
I have a fix for this as a part of https://github.com/dotnet/roslyn/pull/13713

**Comment by jcouv** [comment]
Closing. Was fixed with #13713
