### ISSUE TITLE
A unique error code should be used for missing ValueTuple type

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#13504]
This will greatly simplify the logic for the code fix that will suggest to add a nuget reference.

Relates to https://github.com/dotnet/roslyn/issues/13375 (improving the first time experience for tuple users)

**Comment by jcouv** [comment]
@CyrusNajmabadi I introduced a new error code for missing ValueTuple type in C#.

For VB, the error seems to have all the information. Let me know if I should also change it.
```
BC31091: Import of type 'ValueTuple(Of ,)' from assembly or module 'NoTuples.dll' failed.
        Dim x As (Integer, String) = (1, "hello")
                                     ~~~~~~~~~~~~
```
FYI for @AlekseyTs

**Comment by CyrusNajmabadi** [comment]
> For VB, the error seems to have all the information. Let me know if I should also change it.

You should also change it.  We will not look at things like the text of the error.  All we will look at is the error code.  The rest is considered to be a opaque piece of data that we will not try to interpret.

**Comment by jcouv** [comment]
Fixed in VB too, with https://github.com/dotnet/roslyn/pull/13571

**Comment by agocke** [comment]
@jcouv This error message doesn't seem better than the existing one for missing well known types. For instance, these are the errors I see without `System.ValueTuple`:

```
CS8179	Predefined type 'System.ValueTuple`2' is not defined or imported
CS8137	Cannot define a class or member that utilizes tuples because the compiler required type 'System.Runtime.CompilerServices.TupleElementNamesAttribute' cannot be found. Are you missing a reference?
```

The error about TupleElementNamesAttribute seems more readable to me.

**Comment by jcouv** [comment]
@agocke 
Yes, the new error is a clone of `ERR_PredefinedTypeNotFound`, but with its own error code.
The main requirement is to have a unique code, here `CS8179`. This error code will be consumed by the IDE (code fix for suggesting nuget package) without having to parse the error message itself.
