### ISSUE TITLE
[caret placement] Encapsulate field does not use refactoring helper service

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#13505]
This is part of our effort to make our quick actions more discoverable by having them triggered where expected.

![image](https://cloud.githubusercontent.com/assets/1402694/18146731/21ac537e-6f86-11e6-9320-d53076533fe9.png)

Currently, we offer this quick fix at (2-5). If you are 1 space before, e.g. (1), you will not get the fix. I think this should be a bug, but it seems like it's up for debate.

**If we select an entire file and press `Ctrl+.`, we offer up this quick fix. This seems very, very strange so let's remove this.** See below:

![image](https://cloud.githubusercontent.com/assets/1402694/18146823/a4b0735e-6f86-11e6-968c-e21a7de29f19.png)

**Comment by Pilchie** [comment]
Not showing this at 1 has been reported a few times (it used to work in VS2013).  I agree with not showing this if the user selects the whole class - we should only show it if the selection contains just fields.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We should drive these from reported issues of people having problems.   Right now we've driven things based on the diagnsotic (Which makes sense) or the the refactoring helper service (to get uniform behavior).  We don't really need general issue tracking all of these.

**Comment by sharwell** [comment]
Reopening this issue. Currently `CSharpEncapsulateFieldService.GetFieldsAsync` is not using our refactoring helper service, and is therefore not providing a consistent experience with our other field-based refactorings.

**Comment by CyrusNajmabadi** [comment]
Clossing out as speculative.
