### ISSUE TITLE
[caret placement] Extract Interface

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#13503]
This is part of our effort to make our quick actions more discoverable by having them triggered where expected. 

![image](https://cloud.githubusercontent.com/assets/1402694/18145808/97960c4c-6f81-11e6-8f72-2de00b2ab2da.png)
- We currently only offer this quick fix at (3). **At a minimum, let's offer the fix anywhere in the declaration of the class (1-4).** 
- We can also offer these "class-wide" quick fixes at any empty line in the class, e.g., (5). We may need a larger design discussion here...
- If a user selects the entire class, let's offer this quick fix (currently triggers only "Move" refactorings).
- If a user selects 2+ members and presses `Ctrl+.`, it would be awesome if we would offer to extract interface with these selected members (@dpoeschl  suggestion).

**Comment by CyrusNajmabadi** [comment]
Closing out.  We should drive these from reported issues of people having problems.   Right now we've driven things based on the diagnsotic (Which makes sense) or the the refactoring helper service (to get uniform behavior).  We don't really need general issue tracking all of these.

**Comment by sharwell** [comment]
Reopening as this feature is not currently using the refactoring helper service.
