### ISSUE TITLE
[Q] More information about a TODO - Bug 889301.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#13507]
I could do with more information about this bug 889301, is there a unit test. **Edit** [Is this it?](https://github.com/dotnet/roslyn/blob/56f605c41915317ccdb925f66974ee52282609e7/src/Compilers/VisualBasic/Test/Syntax/Parser/ParseDeclarationTests.vb#L651)
What source code did produce the "bug"
```vb
                    Dim paramSpecifiers As ParameterSpecifiers = 0
                    Dim modifiers = ParseParameterSpecifiers(paramSpecifiers)
                    Dim param = ParseParameter(attributes, modifiers)

                    ' TODO - Bug 889301 - Dev10 does a resync here when there is an error.  That prevents ERRID_InvalidParameterSyntax below from
                    ' being reported. For now keep backwards compatibility.
                    If param.ContainsDiagnostics Then
                        param = param.AddTrailingSyntax(ResyncAt({SyntaxKind.CommaToken, SyntaxKind.CloseParenToken}))
                    End If
```
[link](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Parser/Parser.vb#L4492)

**Comment by jmarolf** [comment]
This is the original bug

# Bug 889301:Parser-more error:''

**Description**
```VB
Friend Class cTest
   Sub Sub1 (0 To 10)
   End Sub
End Class
```
**Expected**
error 30203: Identifier expected.

**Actual** 
[32..39) : error 30213: Comma or ')' expected.
[32..32) : error 30203: Identifier expected.

And I do believe that [this](https://github.com/dotnet/roslyn/blob/56f605c41915317ccdb925f66974ee52282609e7/src/Compilers/VisualBasic/Test/Syntax/Parser/ParseDeclarationTests.vb#L651) is the regression test for this.
