### ISSUE TITLE
QuickInfo should let you know if a local is a 'ref' local or not.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#13514]
Ran into this while using some ref local stuff.  Hovering over the value gives you no indication it's byref.  That's annoying because you don't realize what the semantics are of assigning to it or any of its fields.

**Comment by Pilchie** [comment]
This comes from `SymbolDisplay`.

**Comment by jaredpar** [comment]
Related to https://github.com/dotnet/roslyn/issues/11356

**Comment by cston** [comment]
@CyrusNajmabadi, does #11356 provide what is needed from the compiler layer?

**Comment by CyrusNajmabadi** [comment]
Most likely.  Thank you!  If you want, i can do hte quick info work now that the API is available.

**Comment by cston** [comment]
@CyrusNajmabadi, please feel free to update quick info. Thanks.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/issues/16397
