### ISSUE TITLE
windows_eta_open_prtest failure "error CS1061: 'ITextBuffer' does not contain a definition for 'GetFeatureOnOffOption'"

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#13513]
windows_eta_open_prtest failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/3216/
```
UI\Documents\Margins\NavigationBar\NavigationBarMarginProvider.cs(42,38): error CS1061: 'ITextBuffer' does not contain a definition for 'GetFeatureOnOffOption' and no extension method 'GetFeatureOnOffOption' accepting a first argument of type 'ITextBuffer' could be found (are you missing a using directive or an assembly reference?) [d:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\RoslynETAHost\jnggxbbi.tmp_proj]
```

**Comment by dpoeschl** [comment]
Hmm, seems to only happen on jobs from my PR. Investigating.

**Comment by dpoeschl** [comment]
Related to dotnet/roslyn-internal@7186175, but it's only happening on my PR

Closed/reopened the PR to try to get it to target the latest open master.

**Comment by Pilchie** [comment]
Is this still an issue?  I think @jasonmalinowski thought maybe your run got kicked off in the middle of a cross-cutting change between Open and Closed?

**Comment by dpoeschl** [comment]
The timing explanation makes the most sense. Closed.
