### ISSUE TITLE
XML doc comments don't work for System.String

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#13529]
Willow uses "doc redirect" for XML doc comments of Desktop FX reference assemblies. For example, mscorlib.xml in FX 4.5 reference assemblies only contains a single line:

```
<doc redirect="%PROGRAMFILESDIR%Reference Assemblies\Microsoft\Framework\.NETFramework\v4.X\mscorlib.xml" />
```

The actual documentation is in the specified file. When showing Quick Info on ```string``` type the doc comment doesn't show up on Willow build  25626.00 from ml branch.

Also the integration test ```CSharpQuickInfo``` needs to be updated to account for a change in the actual doc comment:

Old:
> Represents text as a series of Unicode characters.To browse the .NET Framework source code for this type, see the Reference Source.

New:
> Represents text as a sequence of UTF-16 code units.To browse the .NET Framework source code for this type, see the Reference Source.

**Comment by terrajobst** [comment]
AFAIK we discovered this during PCL days. @davkean, any more context or contact?

Otherwise, @rpetrusha & @mairaw: do you guys have any idea where the docs for this feature might be?

**Comment by jasonmalinowski** [comment]
This is trivial to implement, it's mostly a question of "how do I interpret that string"? The `%%`s would have made me think environment variables, but `%PROGRAMFILESDIR%` isn't a normal environment variable.

**Comment by jasonmalinowski** [comment]
Oh, wait, if we're in Visual Studio we don't read those XML files, we let the core VS service do them. (We'll still have to update our non-VS code.) So does the core VS service support this?

**Comment by terrajobst** [comment]
For the record, PCLs are using this feature. Take a look at: "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.6\Profile\Profile32\Microsoft.VisualBasic.xml"

**Comment by jasonmalinowski** [comment]
So looking at the VS implementation, there are three magic values allowed. `%CORSYSDIR%`, which maps to some "runtime directory path", `%VSPATHDIR%` which maps to the Common7\IDE path, and `%PROGRAMFILESDIR%` which maps to SHGetSpecialFolderPath(..., CSIDL_PROGRAM_FILES, ...)

**Comment by terrajobst** [comment]
@jasonmalinowski 

> So does the core VS service support this?

Don't know. But I know where to look :smile:

https://devdiv.visualstudio.com/DevDiv/_search?type=Code&lp=search-project&text=CXMLMemberIndexService&result=DefaultCollection%2FDevDiv%2FVS%2FGBmaster%2F%2Fsrc%2Fenv%2Fmsenv%2Fcore%2Fxmlindex.cpp&preview=0&filters=ProjectFilters%7BDevDiv%7D&_a=contents

**Comment by mairaw** [comment]
Which feature are you referring to @terrajobst? @rpetrusha has changed the summary of the String class for the 4.6.2 release.

**Comment by terrajobst** [comment]
@mairaw the feature in our infrastructure to redirect XML IntelliSense files to another location using the `redirect` attribute.

**Comment by mairaw** [comment]
I know very little about that. Not sure if @rpetrusha has more details.

**Comment by rpetrusha** [comment]
@mairaw @terrajobst I think I know even less about it.

**Comment by terrajobst** [comment]
Thanks @mairaw and @rpetrusha. I think that means @tmat and @jasonmalinowski will have to save the day then ;-)

**Comment by jasonmalinowski** [comment]
Looking at this in yesterday's internal master build, it seems things are generally working. Except somehow System.String itself which doesn't get do comments. Other primitive types get it, and the doc comment is there in the file...but it doesn't work.

**Comment by jasonmalinowski** [comment]
And this appears to be an issue with the VS IVsXMLMemberIndexService service. The code is bailing saying this isn't represented even though it most clearly is. I've filed an [internal bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/283204) to track this from here.

**Comment by jasonmalinowski** [comment]
And closing the loop: yes, there was a bug where some queries to the IVsXMLMemberIndexService in redirected cases wouldn't return correct results. The internal bug is tracking from there.
