### ISSUE TITLE
CodeLens count is inconsistent across partial declarations and linked file

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/roslyn#13530]
Currently CodeLens has the behavior of:
- The references WON'T include the current declaration.
- The references WILL include other partial declarations.
- The references WON'T include the current declaration in linked files.
- The references WILL include other partial declarations in linked files.

It's not clear why we do point 3 because it's a declaration that's not the one I'm looking at right now.

See #13500.

**Comment by CyrusNajmabadi** [comment]
Clsoing out due to lack of broad feedback on this.
