### ISSUE TITLE
Should QuickInfo show the declared accessibility or the effective accessibility of symbols?

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#13544]
```C#
internal class C
{
    public void M() {} // QuickInfo on M
}
```
Should it show as public or internal?

**Comment by dpoeschl** [comment]
/cc: @CyrusNajmabadi because we briefly chatted about this offline

**Comment by Pilchie** [comment]
Personally I think is should show the *declared* accessibility - `public` in this case.

**Comment by Pilchie** [comment]
@DustinCampbell do you have an opinion?

**Comment by DustinCampbell** [comment]
I think it should be declared. Making it effective without some other indication of what's happening will just serve to confuse.
