### ISSUE TITLE
After choosing ASP.NET 1.0, it does not show up in your list of targets

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#13567]
1. Create a new portable project, choose ASP.NET 1.0 + NET 4.6
2. Choose Project -> Properties

Expected: ASP.NET 1.0 and .NET 4.6 to be listed
Actual: Only .NET 4.6 is listed

Clicking change, I see:

_The selection cannot be targeted by this project type. Create a new non-portable project to target it._

**Comment by rchande** [comment]
@davkean Was this fixed when you reverted the change I made in the microupdate?
