### ISSUE TITLE
Creating a new .NET Framework 4.6/UWP/ASP.NET 1.0 asks me retarget to .NET Standard even though I'm already targeting it

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#13568]
**Version Used**: 

**Steps to Reproduce**:

1. Create a new .NET Framework 4.6/UWP/ASP.NET 1.0 portable project
2. Look in project.json, see that my TFM is "netstandard1.3"
3. Click Project -> Properties

Expected: No button to retarget me to .NET Standard:
Actual:

![image](https://cloud.githubusercontent.com/assets/1103906/18216689/36932b7c-710d-11e6-91c1-1257ab30369d.png)

**Comment by rchande** [comment]
@davkean Was this fixed when you reverted the change I made in the microupdate?
