### ISSUE TITLE
CodeFixes that alter AdditionalFiles do not save the changes

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#13561]
**Version Used**: VS 15 Preview 4

**Steps to Reproduce**:
1. Enlist in Roslyn, under source control
2. Change something from `internal` to `public`
3. Use the Public API analyzer/fixer to add the newly public thing to the `PublicAPI.Unshipped.txt` file

**Expected Behavior**: `PublicAPI.Unshipped.txt` should be saved, and show as changed under source control

**Actual Behavior**: `PublicAPI.Unshipped.txt` is not saved until you Save All in VS.

**Comment by dpoeschl** [comment]
Some potential psychic debugging from @pilchie elsewhere: "Sounds like we're missing a dispose on an invisible editor somewhere"

**Comment by dpoeschl** [comment]
Also /cc: @tmeschter

**Comment by jasonmalinowski** [comment]
Oh, hey, turns out it's dotnet/project-system#2160 that I filed after investigating. :smile:
