### ISSUE TITLE
Checking two of ASP.NET Core 1.0, UWP or .NET Framework 4.6 in portable checks all of them

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#13566]
1. File -> New Portable Project
2. Check .NET Framework 4.6 + UWP
3. Click OK
4. Project -> Properties

Expected: Only ASP.NET Core 1.0 and .NET Framework 4.6 to be selected
Actual: All 3 are selected

**Comment by davkean** [comment]
This in Dev15 recently install.

**Comment by rchande** [comment]
@davkean Was this fixed when you reverted the change I made in the microupdate?

**Comment by rchande** [comment]
Looks like this was fixed by your revert.
