### ISSUE TITLE
A way to get recommendations without a Workspace

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#13572]
I might be very wrong about this, but here is my reasoning.

### Goals

I have a web application that allows people to write C#. Currently it is using a classic request/response model, and I don't maintain a session — I create `ParseTree` and `Compilation` for each request instead.

Looking at the `Recommender` I see that it requires me to create a `Workspace` as well, which would introduce overhead and complexity that I believe is not warranted for this scenario.

### Details

`Recommender.GetRecommendedSymbolsAtPositionAsync` requires a `workspace`, but I see that it could have worked without one (and with some reflection I have proven underlying services _can_ work without one). It uses `workspace` for three things:

1. Getting an `IRecommendationService` from `workspace.Services`
2. `CSharpSyntaxContext` used by `CSharpRecommendationService`
3. Getting an `OptionSet` from `workspace.Options` if another one was not provided

It seems none of these are essential.

First one can be handled by providing `HostLanguageServices` for a given language, or `Func<string, HostLanguageServices>` — which I can then implement, potentially without MEF. But given it's only for service resolution, it could also be some kind of `IServiceResolver.GetService<>`.

Second one (`CSharpSyntaxContext`) stores the `workspace`, but nothing seems to use it in this call tree. It does not validate `workspace` for `null`, so I assume it is optional. I can see `CreateContext_Test` which explicitly passes `null` there — so maybe splitting the context into a base one and context-with-workspace would make it more explicit and remove the need for the `Test` method. In any case, if some recommendation services need the `workspace` later on, they can always do it conditionally.

Third one (`OptionSet`) would not be needed if I could pass in one. There is nothing workspace-specific about those options, but since it is abstract and has internal members, I can't instantiate or subclass it.

### Summary

Here are the API changes I suggest here.
Current API:
```
Task<IEnumerable<ISymbol>> Recommender.GetRecommendedSymbolsAtPositionAsync(
    SemanticModel semanticModel,
    int position,
    Workspace workspace,
    OptionSet options = null,
    CancellationToken cancellationToken = null
)
```

Simplest suggested API:
```
Task<IEnumerable<ISymbol>> Recommender.GetRecommendedSymbolsAtPositionAsync(
    SemanticModel semanticModel,
    int position,
    Func<string, HostLanguageServices> languageServiceResolver,
    OptionSet options = null,
    CancellationToken cancellationToken = null
)

public class SimpleOptionSet : OptionSet {
    public SimpleOptionSet(ImmutableDictionary<OptionKey, object> values) { ... }
}
```

I'm not fully happy with `HostLanguageServices` requirement here, as it could be something like
```
public interface IServiceResolver<TServiceBase> {
    TService GetService<TService>() where TService : TServiceBase;
}
```
but this wouldn't be something worth introducing in a single place.

In this model:

  1. Everything but the `SemanticModel` is immutable and can be reused between requests
  2. The API is simpler for the case when a workspace isn't needed for other reasons

**Comment by mattwar** [comment]
All the API's are designed with the assumption that the caller has a workspace available.  Sometimes, some of the API's have overloads where you can specify the SemanticModel or SyntaxTree up front, because this saves some overhead when you don't have to make an async call.  In other cases, the workspace might only be used to find the underlying language service via the host services API.  However, it is not simpler to have the API use the host services instead of the workspace as an argument.  Host services is only an access point to workspace and language services that are tied to an instance of a workspace anyway.  

The Recommender API uses mostly the SemanticModel to return symbols.  Given the amount of work in allocations and processing you had to go through to even get the SemanticModel let alone force it to find and realize symbols, the overhead of constructing a Workspace is not going to be noticeable.

**Comment by ashmind** [comment]
@mattwar Thanks for the detailed reply. I've given it a bit more thought, and while I'm not a fan of this model, I do understand your reasoning and benefits of a consistent approach. And I decided I'll need some services above `Recommender` anyway and so `Workspace` is unavoidable.

Thanks again — I'll close this now.
