### ISSUE TITLE
[PR Test Failure] Fail to restore SRM and find XUnitResults

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#13570]
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/linux_debug_prtest/3246/

1. error: Unable to resolve 'System.Reflection.Metadata (>= 1.4.1-beta-24430-01)' for '.NETPortable,Version=v4.5,Profile=Profile7'.
2. [xUnit] [ERROR] - No test reports found for the metric 'xUnit.Net' with the resolved pattern '**/xUnitResults/*.xml'. Configuration error?.

**Comment by dpoeschl** [comment]
@tmat Any idea what might be going wrong with SRM?

**Comment by dpoeschl** [comment]
Also cc: @agocke

**Comment by dpoeschl** [comment]
Rerunning the suite passed.

**Comment by AdamSpeight2008** [comment]
This doesn't look right `*/xUnitResults/.xml` shouldn't it be `*/xUnitResults/*.xml`

**Comment by tmat** [comment]
@dpoeschl Is it intermittent? If so I suspect entwork error or myget server error.

**Comment by dpoeschl** [comment]
Intermittent. That was also @agocke's guess.

**Comment by agocke** [comment]
Yup, I'm going to close this as likely network issue for now.
