### ISSUE TITLE
CodeStyle Tools Options window : improve keyboard navigation

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#13579]
1. Have to tab twice to select severity/preference
2. should show drop down on some key (space ?)

**Comment by Pilchie** [comment]
Does the dropdown not show on Alt+Down (the standard keybinding?)

**Comment by balajikris** [comment]
Yeah, Alt + Down seems to work (once you tab twice to get to the drop down and select the list itself).

**Comment by rchande** [comment]
As long as it's fully keyboard navigable we can live with the double-tab issue.

**Comment by dpoeschl** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/16380
