### ISSUE TITLE
Simplification APIs should return the reasons for simplifying a node 

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#13587]
SimplifyTypeName Analyzer uses Simplification API to determine whether a name can be reduced. However, the API does not indicate why or what reductions happened. 

Simplify to predefined types is one of the reductions handled by the API, but this is configurable by a user option (tools -> option -> codestyle). 

To determine whether this particular reduction happened to a node, we attach a Annotation with custom meta-data. The analyzer looks for that annotation and then issues a diagnostic per the configured setting.

We need a better way to get this information from the simplifier than tacking annotations, especially as we expose more simplification options.

**Comment by balajikris** [comment]
See: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/Diagnostics/Analyzers/CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs,143
```C#
                // set proper diagnostic ids.
                if (replacementSyntax.HasAnnotations(nameof(CodeStyleOptions.PreferIntrinsicPredefinedTypeKeywordInDeclaration)))
                {
                    diagnosticId = IDEDiagnosticIds.PreferIntrinsicPredefinedTypeInDeclarationsDiagnosticId;
                }
                else if (replacementSyntax.HasAnnotations(nameof(CodeStyleOptions.PreferIntrinsicPredefinedTypeKeywordInMemberAccess)))
                {
                    diagnosticId = IDEDiagnosticIds.PreferIntrinsicPredefinedTypeInMemberAccessDiagnosticId;
                }
                else if (expression.Kind() == SyntaxKind.SimpleMemberAccessExpression)
                {
                    var memberAccess = (MemberAccessExpressionSyntax)expression;
                    diagnosticId = memberAccess.Expression.Kind() == SyntaxKind.ThisExpression ?
                        IDEDiagnosticIds.RemoveQualificationDiagnosticId :
                        IDEDiagnosticIds.SimplifyMemberAccessDiagnosticId;
                }
```

**Comment by Pilchie** [comment]
This is something we should take a look at, to see if we can improve the performance of the simplify analyzer.  It's currently *quite* expensive.

**Comment by CyrusNajmabadi** [comment]
These systems were rewritten (Especially having them not overlap for different simplificaion tasks).  Closing out.
