### ISSUE TITLE
Move type to file refactoring : detect conflicts ahead of time for Rename type to match file.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#13584]
Today rename type to match file just calls `RenameSymbolAsync` and does not worry about conflicts. An improvement here would be to detect conflicts ahead of time and display it?

At the least we should add some tests for this case.

**Comment by Pilchie** [comment]
@dpoeschl has long been thinking about exposing conflict information for Rename Tracking as well.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
