### ISSUE TITLE
RoslynInsertionTool: better way to discover Willow components

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#13593]
Currently RIT fetches a TFS log file zip from the target build, finds a log file containing "Upload VSTS Drop" name (corresponding to Microbuild task called "Upload VSTS Drop"), parses the file for `https://.*vsman` pattern and then uses the URLs found this way.  This is very fragile and full of assumptions that need to be true across all repos we insert from. Also, if the URL is not found NRE is thrown. 

We should have a more robust way of doing this.

**Comment by jasonmalinowski** [comment]
It's worked fine for two years....(famous last words)
