### ISSUE TITLE
Workspace should be more resilient when it can't read a generated file

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#1360]
See also DevDiv.979836 — we need a mechanism to re-try failed file load cases

It is quite common for generated files to be included in the project. When the workspace is trying to read this file, it might get access denied. This results in discrepancy between Error List and actual build output and bogus build errors. This is a bad experience, and a regression from the old language service. We haven't seen this many issues of this nature before Roslyn.

We could try retrying 10 times spaced out by 200 ms. Or use FileShare.ReadWrite or FileShare.Delete, which are more forgiving than FileShare.Read. Or both.

From @Pilchie:
In the native C# language service, we used to have a single retry after 1 second which alleviated many of these sort of issues.

From @heejaechang:

currently, when a workspace try to read a file content, for whatever reason if it fails, it raise workspace failed event and move on. and remains that way until something happens to that file again.

this is a problem since this could cause a lot of errors to show up in IDE. since those file either contains empty content or staled content from whatever it used to have, this will make some errors to show up for that project, but if there is p2p reference to this project, especially skeleton assembly, then, this could cause even more errors to show up in all those project that transitively depends on this project.

what I am observing is when we build or tf sync or even when we load project, if we happen to be out of luck, we gets a lot of this failures and hence a lot of errors in IDE. (I included what I have in my VS right now below)

I think this make IDE experience quite bad. since there is no easy way to fix this once it happens. close solution and re-loading might not fix it sometimes, you need to do that several times sometimes.

so, I think we need a way to mitigate this issue. I think we need some mechanism that listen to this workspace failure events and re-load them.
...

[Failure] The process cannot access the file 'C:\dd\Roslyn2\Main\Open\Compilers\CSharp\Portable\obj\Debug\BoundNodes.xml.Generated.cs' because it is being used by another process.

[Failure] The process cannot access the file 'C:\dd\Roslyn2\Main\Open\Compilers\VisualBasic\Portable\obj\Debug\Syntax.xml.Generated.vb' because it is being used by another process.

**Comment by weltkante** [comment]
Getting this consistently in VS 2015 RC in a large WinForms project containing WPF UserControls (the project is also on a network share making file access slower than locally). The generated file connecting the CodeBehind with the XAML always generates these errors during builds.

[Failure] The process cannot access the file 'U:\...\MyUserControl.g.i.cs' because it is being used by another process.

**Comment by mattwar** [comment]
#2539 fixes the problem trying to read generated files that are temporarily inaccessible.

**Comment by heejaechang** [comment]
:+1: ah, finally!
