### ISSUE TITLE
Prototype: target typed "default"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#13602]
Work items:
- [x] Parsing
- [x] Target typing
- [x] Overload resolution
  - [x] Report error if failed inference
  - [x] Only non-nullable types should be considered as candidates
- [x] Verify semantic model (GetConstantValue, GetConversion, GetOperation)
- [ ] IDE refactoring to simplify (when possible) or expand
- [x] Write spec ([issue](https://github.com/dotnet/roslyn/issues/17111), [proposal](https://github.com/dotnet/csharplang/blob/master/proposals/target-typed-default.md))
- [x] Validate [IDE scenarios](https://github.com/dotnet/roslyn/blob/master/docs/contributing/IDE%20Test%20Plan.md)
- [x] Update prototype with latest LDM decisions
    - [x] Use literal syntax node
    - [x] Update `as` and `is` scenarios.

Test ideas:
- [x] `dynamic x = default;` // error
- [x] `const int x = default;` // ok
- [x] `var x = default;` // error
- [x] `(int, int) t = (default, default);` // ok
- [x] `int[] t = new[] { default };` // ok
- [x] `ITest i = default;` // error
- [x] `@default`
- [x] `default.ToString();`
- [x] `M(default);` where `void M<T>(T x) { ... }` // error
- [x] `flag ? default : 1;`
- [ ] `default` in enum?
- [ ] more test on overload resolution: `M(default, 1)`, `M(default, (1, 2))`
- [ ] test `const object x = default(S);`
- [ ] test `C[] x = new[] { default };`
- [ ] test `null == default`

LDM questions:
- [x] Is "default" a literal?
- [x] Can you apply a cast on "default"? `var x = (int)default;` (I think the answer is yes).
- [x] Can "default" be used as default parameters? (current behavior is yes)
- [x] Can "default" appear in constant expressions? (current behavior is yes)
- [x] Can type-targeted default be applied anywhere the traditional "default" was used (including reference types)? (current answer is yes, including reference types)
- [x] `throw default;`? (current behavior is no)
- [x] `default` has a type (which is inferred) and also a constant value (if appropriate)
- [x] Should `case default:` give a warning (LDM 3/7)

Relates to language proposals https://github.com/dotnet/roslyn/issues/7737 and https://github.com/dotnet/roslyn/issues/13255

Overload resolution might re-use some techniques from https://github.com/dotnet/roslyn/pull/11493

**Comment by AdamSpeight2008** [comment]
What happens if `default` already exists in scope as parameterless method / property

>Can "default" be used as default parameters?

Yes because it save the author having to write the type again.
eg ` SomethingClass<T0,T1,T2> thisparameter = default,  `

**Comment by jcouv** [comment]
@AdamSpeight2008 

> What happens if default already exists in scope as parameterless method / property or a constant?

`default` is a reserved keyword, so method, properties or constants couldn't use it as name ([example](http://tryroslyn.azurewebsites.net/#K4Zwlgdg5gBAygTxAFwKYFsDcAoADsAIwBswBjGUogQxBBgGEYBvbGNmfYsmANwHswAExiDUAMyrAiyABQBKZq3YBfJW04lykZCPGTpOZUA=)).

**Comment by AdamSpeight2008** [comment]
@jcouv `@default` is though.

**Comment by alrz** [comment]
> `ITest i = default`

Why? Shouldn't it be equivalent to `default(ITest)`?

**Comment by HaloFour** [comment]
@AdamSpeight2008 

The compiler requires that any reference of a keyword as an identifier be prefixed with `@`.  But I can see where the following could be considered ambiguous:

```cs
int x = 2;
int @default = 3;
int result = x + default; // oops, sets result to 2
```

**Comment by svick** [comment]
@HaloFour I don't see how is that different from the following, currently valid code:

```c#
int? x = null;
int @null = 0;
int? result = x ?? null; // oops, sets result to null
int? correct = x ?? @null;
```

**Comment by HaloFour** [comment]
@svick 

I agree.  It's not a big enough of a concern to reconsider the feature.  Anyone who explicitly decides to use keywords as identifiers via `@` accepts the responsibility of ensuring that they don't mix them up.

**Comment by jcouv** [comment]
> ITest i = default; // error. Why? 

@alrz There was no LDM discussion or decision on this, but my thinking is that `default` does not overlap with `null` (you can use one or the other, but not both). So `default` would be for structs and non-nullables only.
I agree with you this is not obvious, as you could say `default` is a simplification of `default(ITest)` and today C# allows `ITest i = default(ITest);`. I'll add to the list of open questions.

**Comment by AdamSpeight2008** [comment]
@HaloFour 
```c#
int @default = 3;
int result = default; // oops, sets result to ??
```
Is that result 3 or 0.

**Comment by HaloFour** [comment]
@AdamSpeight2008 

Indeed, I already pointed that out.  But as @svick noted that's already the case with `null` and `@null` and, frankly, the developer that takes it upon themselves to use keywords as identifiers accepts the responsibility of not mixing them up.

**Comment by alrz** [comment]
@jcou That doesn't seem to be a big win. I expect the following work
```
void M(int x = default, object o = default) {}
```
which requires the default to be allowed in optional params and with reference types.

**Comment by AdamSpeight2008** [comment]
It think the following syntax is more in keeping with C#.
```c#
F( int x?, string s?, int? n, bool b? )
```
equivalent to 
```c#
F( int    x = default(int),
   string s = default(string),
   int?   n = default(nullable<int>),
   bool   b = default(bool) )
```

**Comment by jcouv** [comment]
@AdamSpeight2008 
> Is that result 3 or 0.
`default` is always a keyword. `@default` is always an identifier. 
`int result = default;` // result is set to zero (regardless of any locals called `@default` declared in scope).

**Comment by CyrusNajmabadi** [comment]
> There was no LDM discussion or decision on this, but my thinking is that default does not overlap with null (you can use one or the other, but not both)

That seems unfortunate.  It would be nice to have a single literal you could use for everything.

**Comment by CyrusNajmabadi** [comment]
> Is "default" a literal?

Out of curiosity, is there any reason why we wouldn't want to make 'default' as close to 'null' as possible, except that it would also be allowed for non-reference types?

**Comment by AdamSpeight2008** [comment]
Make it behave similarly to VB's `Nothing` when it used in assignment.

**Comment by CyrusNajmabadi** [comment]
@AdamSpeight2008 does that bring any interesting additional semantics you care about?

**Comment by HaloFour** [comment]
@AdamSpeight2008 

> Make it behave similarly to VB's `Nothing` when it used in assignment.

To quote @AnthonyDGreen when responding to a complaint about `Nothing` equating to `0` in VB.NET:

> One of my great regrets 🙁

In short, that's an absolutely awful idea.

@jcouv

In my opinion, `default` should be nothing more than shorthand for `default(T)` where `T` can be inferred by the compiler.  No more.  No less.  That means that it should absolutely mean `null` where `T` is a reference type or interface.  I believe that is going to be the expected behavior, anything else will be surprising in a bad way.

**Comment by AdamSpeight2008** [comment]
If the target type is a class, it assigns it of zero (null). if it target is a structure it assign it the zero value (0).
eg
```c#
string s = nothing; //  (s == null) == true  or the default value of the type.
Int i = nothing; // ( s == 0 ) = true or the default value of the type.
```

I think that comment is about the expression ` Nothing = 0 `. Akin to C's `define NULL = 0;`

**Comment by CyrusNajmabadi** [comment]
Is there any difference between those semantics and the semantics of "default(T)" where T is whatever type is present?

**Comment by CyrusNajmabadi** [comment]
In other words, i see 'default' as just being shorthand for "default(T)".  Are there additional VB semantics you see on top of that.

**Comment by AdamSpeight2008** [comment]
@CyrusNajmabadi  That's how I also see it, shorthand for `default( T )`. It save the developer writing the type explicitly again. It like the dual of `var`

**Comment by HaloFour** [comment]
@AdamSpeight2008 

Ok, yes, I agree.  I makes sense for `default` to behave like `Nothing` in VB.NET, which is like `default(T)` in C# today.  What doesn't really make sense is the fact that `Nothing` in VB.NET behaves like that.  😄

**Comment by AdamSpeight2008** [comment]
I hope that's because Erik Meijer had something to do with the implementation.

**Comment by CyrusNajmabadi** [comment]
@AdamSpeight2008 Ah ok.  I would not want it to be like VB's Nothing then.  I would prefer it be like C#'s default(T).

**Comment by DavidArno** [comment]
Definitely agree with others here re `ITest i = default;` being treated as an error. The LDM seem to have misunderstood/ignored the ideas in the linked issues, namely that `default` just be shorthand for `default(T)`, where `T` is known. So the following should apply:
````csharp
dynamic x = default; // error - type isn't known
var x = default; // error - type isn't known
ITest i = default; // OK: default same as default(ITest)
````

**Comment by DavidArno** [comment]
I agree with others here who have questioned why `ITest  i = default;` is viewed as an error. The LDM seem to have misunderstood/ignored the contents of the linked issues, which is that `default` would be the equivalent of `default(T)`, for situations where `T` is known. So the following should apply:
````csharp
dynamic x = default; // error, type isn't specified
var x = default; // error, type isn't specified
ITest i = default; // OK: default is shorthand for default(ITest)
````

**Comment by jcouv** [comment]
@DavidArno There was no LDM discussion of this feature yet.
I got the feedback from you and others in the thread that there is strong interest to allow the `default` literal anywhere the `default` operator could. Thanks :-)

**Comment by jcouv** [comment]
Per your feedback, I have changed the prototype to allow `default` on reference types. I'll keep the LDM question open to confirm.

**Comment by jcouv** [comment]
This is feature complete, as far as I can tell. No known work left. Completed a manual test pass in IDE.
Ready to merge back to master. I'll close this list now.
