### ISSUE TITLE
Contextual keywords aren't escaped in symbol display strings.

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#13610]
Contextual keywords such as `await` aren't escaped by `To[Minimal]SymbolDisplayString`, even if the specified options request escaping. This affects completion providers which use the minimizing process to create insertion text.

**Comment by Pilchie** [comment]
Moving to compiler since the API is defined there.

**Comment by CyrusNajmabadi** [comment]
I think this behavior is correct.  These are not keywords, and the display is fine to show them as their actual words.  The issue appears to be with: 

> This affects completion providers which use the minimizing process to create insertion text.
