### ISSUE TITLE
"Predefined type is not defined or imported" error not shown in Error List

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#13649]
**Version Used**: VS 2015 U3, master (a7637024)

**Steps to Reproduce**:
1. Create a .Net 4.5 (not .Net 4.6 or newer) Console application in normal VS 2015 (or in VS 2015 started from the Roslyn project in the Roslyn solution).
2. Write the following code into its `Main`: `IFormattable f = $"";`.
3. Build.

**Expected Behavior**:

The following error shows in the Error List, in the Build + IntelliSense mode:

> CS0518    Predefined type 'System.Runtime.CompilerServices.FormattableStringFactory' is not defined or imported

**Actual Behavior**:

The error shows in the Output window (with Show output from Build set) and it shows in the Error List in the Build Only mode, but it does not show there in the Build + IntelliSense mode.

---

This sounds similar to https://github.com/dotnet/roslyn/issues/11462, except that it's not related to analyzers and that it happens with latest Roslyn code from master.

**Comment by gafter** [comment]
The behavior is per spec, though not particularly helpful in this case. The program does not have any errors, but cannot be compiled without the required reference. That makes the error an "emit-only" build error (i.e. not an intellisense error).
