### ISSUE TITLE
find a way to send options to OOP or build efficiently.

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#13643]
after editor config work is done, we need a way to efficiently sync that options between different host such as VS, build, OOP.

**Comment by heejaechang** [comment]
@Pilchie @srivatsn @jasonmalinowski @JohnHamby will we need design meeting? didn't put milestone since I think it is after dev15 work.

**Comment by heejaechang** [comment]
for dev15, we will cherry-pick options we know we need and explicitly serialize those over OOP.

**Comment by heejaechang** [comment]
some reasons why we need to sync options between different host are

for build, OOP. we need build and ide to report same diagnostics to do de-duplication. otherwise, build and IDE will report different diagnostics since option is different and IDE will always win.

also, we need to do this efficiently so that we don't realize all options exists in VS.

**Comment by Pilchie** [comment]
Moving to 2.1 for now.

**Comment by jasonmalinowski** [comment]
Closing this as it's tracked by items in the .editorconfig project now.
