### ISSUE TITLE
Go to Implementation doesn't deal with types that have type forwards

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#13646]
**Version Used**: daily build from Roslyn master 60906.06

**Steps to Reproduce**:
1. Create a new portable project that's System.Runtime based.
2. Define an interface that uses System.Object in a method parameter.
3. Create a desktop-targeting project, and implement the interface.
4. Go to Implementation on the method from the original interface created in step 2.

**Expected Behavior**: It should take me to the implementation of the method.

**Actual Behavior**: It doesn't. It says there are no implementations.

**Analysis:** This is happening because we use the [regular symbol comparer](https://github.com/dotnet/roslyn/blob/a76370241899a0dcdfb522730cdfdcd9fb662551/src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs#L167) in our implementation of finding interface methods, which considers the signatures to be different because object is coming from different assemblies. We could switch that to the comparer that doesn't care, but that seems incorrect. Find References has a different "are these two types the same" codepath that is smarter and deals with type forwarding; it's not clear to me why that's not always active if you use the default comparer.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi this is the reason we saw that issue last week. I've long been suspicious about our symbol comparers and now I'm more suspicious. We have the standard one that does care about assembly identity (and screws up all type forwarding), and one that doesn't care. Find References has it's own custom logic that uses both of these to compare. It seems like this is a landmine for bugs like this.

**Comment by Pilchie** [comment]
Tagging @brettfo who has been fixing issues related to this all over the place (solution explorer pivots, FAR, etc...)

**Comment by jasonmalinowski** [comment]
If we're having to fix this up everywhere, then I'm further convinced our abstractions here aren't right. :smile:

**Comment by CyrusNajmabadi** [comment]
THey're almost certainly not right.  I welcome anyone providing a common set of helpers that we can use everywhere.  Note that an important part of this is that this code work across symbols in both VB and C#.  I have no idea what the logic is for type forwarding.  But if anyone does, feel free to submit a fix for this issue.

**Comment by CyrusNajmabadi** [comment]
>  This is happening because we use the regular symbol comparer in our implementation of finding interface methods, 
> Find References has a different "are these two types the same" codepath that is smarter and deals with type forwarding; 

Why do we have multiple different comparers?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi: I _suspect_ the answer is history. Originally, we had the regular and assembly-ignoring comparer. It's quite possible that the assembly-ignoring comparer existed primarily in places where we should have been looking at type forwarding, but we might have not had the requisite compiler APIs at the point to actually implement it. Then when the bug was fixed for Find References not dealing with facades correctly, the fix was done via changing how we called our existing comparers rather than unifying all of this.

I had a thought this morning on the drive in that perhaps the comparers like we have them are a bit redundant too -- we already have the SymbolKey code that provides another way to deal with symbols from different compilations that "in theory" has to match up with the equality comparer stuff. I'd assume that symbol equality is true if and only if SymbolKey could also map those symbols, or else I really can't expect features to work reliabily. I'm wondering why we even need an equality comparer being called for _every_ FAR "is this the same" when instead for cross-project we could just map the symbol to the right compilation, cache that, and potentially .Equals() the symbols which might just be a reference equality check.

**Comment by CyrusNajmabadi** [comment]
> "is this the same" when instead for cross-project we could just map the symbol to the right compilation, cache that, and potentially .Equals() the symbols which might just be a reference equality check.

That's certainly something we could consider doing.  There are likely two major places where we do equality checks:

1. When we're doing the inheritance walking to see what types to cascade to.  This is tricky as we look at metadata with the assumption that the metadata will mean the same thing regardless of what project it is in.  To do things correctly, we may have to look at the same metadata in the context of every project as that may change our results.
2. When actually binding a potential textual reference.  In this case, we're always in the context of some project.  And, as such, it would likely be fine to take the approach you mentioned and compare the reference symbol to the proper def symbol that was mapped into that project.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi The assumption you're mentioning in 1 was weakened with the type forwarding work. It's already completely "normal" to have a type from metadata be in two different assemblies (say mscorlib and System.Runtime) and those are still the same because in some cases there's a façade between them.

**Comment by Pilchie** [comment]
Let's us this to track a simple fix to Go to implementation.  @jasonmalinowski or @CyrusNajmabadi can one of you file a second issue describing the larger issue and the proposed solution?

**Comment by CyrusNajmabadi** [comment]
I dont' repro this, and we did a bunch of work to get these symbols to work properly across lots of scnearios.  so closing out as we haven't heard abotu this being a problem presently.
