### ISSUE TITLE
[Test] Many test failures due to "Error List Package did not load"

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#13659]
An example screenshot: Error List Package did not load: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_open_prtest/461/artifact/Open/Binaries/Release/Screenshots/2016-09-07_00-05-55_82%20-%20Modal%20Dialog.png

**Comment by dpoeschl** [comment]
Not sure if flaky yet. Re-running...

**Comment by dpoeschl** [comment]
/cc: @agocke This seems very unrelated to my changes.

**Comment by jasonmalinowski** [comment]
Duplicate of #13032.
