### ISSUE TITLE
[Test] Integration test failure due to focus being stolen by new(?) popup

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#13658]
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/483/artifact/Open/Binaries/Release/Screenshots/2016-09-06_23-45-50_30%20-%20Exception%20System.Reflection.TargetInvocationException.png

**Comment by jasonmalinowski** [comment]
Unfortunately the screenshot went away to confirm, but @dpoeschl was this the same / similar popup mentioned in internal bug 262491? That was the underlying fix for the issue. Assuming you can confirm that we'll close this as external.

**Comment by jasonmalinowski** [comment]
(assigning to myself to track closing nothing more)

**Comment by jasonmalinowski** [comment]
The external underlying bug has been fixed. We'll get it once we move to some newer builds.
