### ISSUE TITLE
Comparing a value type to null discards the branch with no warning

### ISSUE THREAD

**Issue by gulbanana** [dotnet/roslyn#13654]
**Version Used**: 
csc.exe 1.3.1.60616

**Steps to Reproduce**:
1. clone https://github.com/gulbanana/repro-csc-timespanequals
2. build and run

**Expected Behavior**:
The check in DidIGetTheTime is intended to throw an exception if the optional TimeSpan argument was not passed. However, null was accidentally used instead of default(T); if this check can't ever pass, I expect a compiler error.

**Actual Behavior**:
The if() is silently discarded and the emitted IL contains no branch. The exception is never thrown.

**Comment by benaadams** [comment]
This is often used as an optimisation in generics that accepts both classes and structs

**Comment by 0xd4d** [comment]
```
1>Program.cs(17,17,17,26): warning CS8073: The result of the expression is always 'false' since a value of type 'TimeSpan' is never equal to 'null' of type 'TimeSpan?'
```

The trick is to enable `strict` mode. Add it to your csproj file:

```
    <Features>strict</Features>
```

**Comment by gulbanana** [comment]
Thank you, I'll add that flag. I could've sworn that an earlier c# version successfully warned about this using the default settings...

**Comment by gulbanana** [comment]
@benaadams, the difference in this case is that it's statically known to be a value type and hence always false.
