### ISSUE TITLE
Auto type casting in condition experssion assignment and etc.

### ISSUE THREAD

**Issue by mojtabakaviani** [dotnet/roslyn#13653]
by default number is integer, so when assignment to smaller types need casting.
for example:

```
int a = 5, b = 6;
byte c = (byte)(a > b ? 1 : 0);
```

but 0,1 in byte range, Roslyn is intelligent and can auto casting.

```
byte c = a > b ? 1 : 0;
```

**Comment by dsaf** [comment]
Related to #1419

**Comment by gafter** [comment]
If I understand this request, you are asking for "target typing" to see through "?:" expressions.

**Comment by mojtabakaviani** [comment]
Yes,  "?:" expressions is very good example.

**Comment by gafter** [comment]
I believe this would be a breaking language change, as the current specification for finding a common type among the operands of `?:` and the proposed treatment using target typing could get different results. Since we don't want breaking changes, closing.
