### ISSUE TITLE
'is' and 'as' operators can guarantee each other's result

### ISSUE THREAD

**Issue by SherifRefaat** [dotnet/roslyn#13655]
Can you confirm that if a statement that use `is` and returns `true`, substituting the '`is`' operator with '`as`' operator will result in not null result in all circumstances.

**Example:**
```
var result = instance is FooObject;
var result2 = instance as FooObject;
```

so if '`result`' variable is '`true`' it will guarantee that '`result2`' will always be not null in all cases?

**Comment by fuszenecker** [comment]
Hi,

An is expression evaluates to true if the provided expression is non-null, and the provided object can be cast to the provided type without causing an exception to be thrown.

See also: https://msdn.microsoft.com/en-us/library/scekt9xw.aspx

**Comment by dodyg** [comment]
```
if (instance is FooObject){
   var x = instance as FooObject
}
```

Will `x` guaranteed to be a valid casting and not return null in above case?

**Comment by 0xd4d** [comment]
Yes, `is` and `as` use the same IL instruction, `isinst`.

**Comment by orthoxerox** [comment]
Yes, and that's why we're getting the new `value is Type variableofType` construct in C#7.
