### ISSUE TITLE
Get Error CS0220 in C# Interactive when multiplying

### ISSUE THREAD

**Issue by shaggygi** [dotnet/roslyn#13657]
**Version Used**: 
VS 2015 Update 3

**Steps to Reproduce**:
1. Open C# Interactive
2. Enter 60466176 * 36

**Expected Behavior**:
Should return: 2176782336

It appears you can assign the value like this: uint value = 2176782336;

**Actual Behavior**:
I get the following response: (1,1): error CS0220: The operation overflows at compile time in checked mode.

**Comment by svick** [comment]
Why do you think this is a bug? For example, the code `uint value = 60466176 * 36;` fails with the same error in normal C#. So why should it work in C# interactive?

**Comment by AdamSpeight2008** [comment]
`Integer.Max = 2147483647` which is greater than the expected `2176782336`. So should not produce the error, even if the literals where unsigned integers.

**Comment by shaggygi** [comment]
@svick  Oops.  You are correct.  I was not casting correctly.

60466176 * 36
(1,1): error CS0220: The operation overflows at compile time in checked mode

(uint)60466176 * 36
2176782336

uint value = (uint)(60466176 * 36);
(1,21): error CS0220: The operation overflows at compile time in checked mode

 uint value = ((uint)60466176 * 36);
> value
2176782336
