### ISSUE TITLE
Untested code in parsing tuples.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13667]
The following code appears in `LanguageParser.cs`:

```cs
                if (!result.ContainsDiagnostics && list.Count < 2)
                {
                    result = this.AddError(result, ErrorCode.ERR_TupleTooFewElements);
                }
```

but the condition `result.ContainsDiagnostics` doesn't make a difference in any compiler tests. It should probably be removed or tested.

(Note that `ContainsDiagnostics` does not test for errors in the node, or even errors anywhere beneath the node)

**Comment by jaredpar** [comment]
Test.  Please ignore.

**Comment by jaredpar** [comment]
Test. Please ignore.

**Comment by jaredpar** [comment]
Test. please ignore.

**Comment by jaredpar** [comment]
Test. please ignore.

**Comment by jaredpar** [comment]
Test. please ignore.

**Comment by jaredpar** [comment]
Test. please ignore.

**Comment by jaredpar** [comment]
Test. please ignore.

**Comment by jaredpar** [comment]
test. please ignore.

**Comment by jaredpar** [comment]
test. please ignoreu.

**Comment by jaredpar** [comment]
test. please ignore.

**Comment by gafter** [comment]
@jaredpar Did you want to team up in tackling this issue? ;)

**Comment by jaredpar** [comment]
Sorry.  Been using this issue as a test for an application I'm working on.  I'll stop using it now that I fixed the main bugs. :)
