### ISSUE TITLE
Duplicate enum key values do not emit neither error, nor warning

### ISSUE THREAD

**Issue by DovydasNavickas** [dotnet/roslyn#13664]
**Version Used**: 
One with .NET CLI 1.0.0-preview2-003121

**Steps to Reproduce**:
1. Create enum
2. Define two keys with duplicate values

**Expected Behavior**:
At least a warning that two enum keys have the same value.

**Actual Behavior**:
No error, no warning :cry:

**Comment by svick** [comment]
Sometimes, `enum`s intentionally have more than one field with the same value. For example, [out of the ~200 public `enum`s in mscorlib, 13 have values with multiple names](http://ideone.com/d0GKxz).

So this definitely shouldn't be an error, and even a warning is questionable.

**Comment by DovydasNavickas** [comment]
Ok, I didn't think about this case. I'm closing the issue as it seems reasonable now. Thanks, for explanation @svick!
