### ISSUE TITLE
The Visual Studio workspace should consume the new file watching APIs

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#13679]
A new file watching API was introduced into Visual Studio to let us watch a single directory, and consume those notifications on a background thread. This can prevent us from needing to subscribe to each file separately which should significantly help solution load.

**Comment by mavasani** [comment]
@jasonmalinowski @Pilchie Do we want to keep this in RC or move out to RTM?

**Comment by Pilchie** [comment]
This won't happen for RC at this point.  Let's put it in RC.2 though.

**Comment by Pilchie** [comment]
Moving to 2.1 - while I really want this, I think the risk of adopting it this late is too high.

**Comment by jasonmalinowski** [comment]
We've half moved to the new APIs: this is now using the background thread variant, but we haven't switched to the directory watch yet.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi @jinujoseph FYI that this is the original tracking bug for #42095. I'll let you dedup as you want.

**Comment by CyrusNajmabadi** [comment]
Duple of https://github.com/dotnet/roslyn/issues/42095
