### ISSUE TITLE
Code Styles: Should we change the "Suggestion" glyph in the Severity pickers to not confuse Info/Suggestion

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#13673]
![image](https://cloud.githubusercontent.com/assets/235241/18332610/e757bcbc-751c-11e6-9a9e-67022eb51fe4.png)

Note how it says "Suggestion" but shows the recognizable "Info" glyph. Or are we purposely trying to tie those brands of things together? We're stuck with them being called "Infos" in the Error List, so maybe it's okay to mix the concepts here? It feels wrong, though...

**Comment by dpoeschl** [comment]
@Pilchie @kuhlenh @DustinCampbell

**Comment by DustinCampbell** [comment]
We should have a new icon. What is the going into the Error List?

**Comment by Pilchie** [comment]
@kuhlenh: Can you follow up with the editor and UX and figure out what we're going to do here?

**Comment by Pilchie** [comment]
The decision from Ux was not to change this, because a suggestion is a subset of information.
