### ISSUE TITLE
Overload resolution uses quadratic algorithm to find the best candidate.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13685]
Overload resolution (unary operators, binary operators, and methods) uses a quadratic algorithm to select the best candidate, because it compares every candidate to every other candidate.

There is a simple linear algorithm that gives the same result: scan once to find a possibly best method, and then scan a second time to ensure that it is better than every other candidate.

**Comment by gafter** [comment]
@bbarry Good questions.

The same (as existing) result can be produced with a linear algorithm. Just not the one you provided.

**Comment by bbarry** [comment]
I've created this console app tool to attempt to validate the algorithm to be used against the existing one (which in its current form demonstrates the above code is not a valid replacement):

https://gist.github.com/bbarry/e78dbfec6a9f71d428e92fc37f567572

**Comment by cston** [comment]
Fixed in #15839.
