### ISSUE TITLE
pool stream used in emit

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#1368]
one of trace from user (http://stackoverflow.com/questions/28607217/compiletimes-with-roslyn-suddenly-drop) shows this is one of top 3 allocations caused by roslyn when emitting.

we should pool the stream.

Name                                                                                                                                                	Inc %	          Inc	Inc Ct	Exc %
 microsoft.codeanalysis!MemoryStream.Grow                                                                                                           	  6.2	   20,880,500	    24	  0.0
+ microsoft.codeanalysis!MemoryStream.Write                                                                                                         	  3.9	   13,110,624	    11	  0.0
|+ microsoft.codeanalysis!MetadataWriter.SerializeMethodBody                                                                                        	  2.4	    8,172,220	     6	  0.0
||+ microsoft.codeanalysis!MetadataWriter.SerializeMethodBodies                                                                                     	  2.4	    8,172,220	     6	  0.0
|| + microsoft.codeanalysis!MetadataWriter.SerializeMetadataAndIL                                                                                   	  2.4	    8,172,220	     6	  0.0
||  + microsoft.codeanalysis!PeWriter.WritePeToStream                                                                                               	  2.4	    8,172,220	     6	  0.0
||   + microsoft.codeanalysis!PeWriter.WritePeToStream                                                                                              	  2.4	    8,172,220	     6	  0.0
||    + microsoft.codeanalysis!Compilation.SerializeToPeStream                                                                                      	  2.4	    8,172,220	     6	  0.0
||     + microsoft.codeanalysis!Compilation.Emit                                                                                                    	  2.4	    8,172,220	     6	  0.0
||      + microsoft.codeanalysis!Compilation.Emit                                                                                                   	  2.4	    8,172,220	     6	  0.0
||       + microsoft.codeanalysis.desktop!FileSystemExtensions.Emit                                                                                 	  2.4	    8,172,220	     6	  0.0
||        + afas.runtimegenerator!Generator.TryCompile                                                                                              	  2.4	    8,172,220	     6	  0.0
||         + afas.runtimegenerator!Afas.RuntimeGenerator.Generator+<>c__DisplayClass13.<TryCompile>b__d(class Afas.RuntimeGenerator.CSDom.CSProject)	  2.4	    8,172,220	     6	  0.0

**Comment by theoy** [comment]
Moving out to 1.2 because we're meeting end to end performance goals for multiproject solution builds, but we should continue to look into this area. Sending to @pharring opportunistically if he wants to take a look earlier.

**Comment by mattwarren** [comment]
Maybe you could make use of [Microsoft.IO.RecycableMemoryStream](http://www.philosophicalgeek.com/2015/02/06/announcing-microsoft-io-recycablememorystream/) that just got open-sourced?

**Comment by heejaechang** [comment]
@mattwarren I just opened an issue - #1689

**Comment by pharring** [comment]
Note that the MemoryStream in PEWriter is NOT the familiar System.IO.MemoryStream. It could probably benefit from pooling buffers, but we can't use the off-the-shelf RecyclableMemoryStream.

**Comment by tmat** [comment]
Before we start adding dependencies to random libraries, we should step back and look at the design of the writer. The entire thing can be improved in many ways. We also want to factor the writer out of Roslyn post-Dev14. So let's not start doing ad hoc changes right now.

**Comment by pharring** [comment]
@tmat We're not going to take a dependency on the RecyclableMemoryStream library nor do I intend to make ad hoc changes. I do intend to make targeted fixes for customer-reported performance issues. HeeJae has supplied me with the traces for the stackoverflow issue and I will study them today.

**Comment by tmat** [comment]
@pharring Sounds good.

**Comment by pharring** [comment]
I've looked a little closer and the pooling we already do in MemoryStream is pretty efficient. The huge majority of allocations are satisfied from our existing pooled allocator. Most instances are very small (96.25% are less than 64 bytes, measured on our 'Picasso' C# solution). Today, we do not keep allocations larger than 1,024 bytes around. This could be tweaked, but it seems reasonable right now. The pool size is 32 entries, so that's a maximum of 32KB of pooled reserve. Doubling that 1,024 to 2,048 would save another 0.08% of allocations.

The stackoverflow request that sparked this issue likely has an unusually high number of large allocations. Unfortunately, I can't tell just from the ETW trace whether bumping the threshold to 2,048 would help that case.

It's possible to have a two (or many) tiered pooling strategy (at the byte[] level), but we still have to be mindful of the total allocation size.

**Comment by heejaechang** [comment]
@pharring do you mean .NET MemoryStream?

**Comment by pharring** [comment]
@heejaechang no. This is our [Cci.MemoryStream](http://source.roslyn.io/#Microsoft.CodeAnalysis/PEWriter/MemoryStream.cs,7a5b594cb98c59ec).

**Comment by pharring** [comment]
I don't think there's enough supporting data to go forward with this.
