### ISSUE TITLE
VB Compiler outputs to a different binary than the one passed through outputpath in certain cases.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#13681]
**Version Used**: 

**Steps to Reproduce**:
1. Invoke vbc with `vbc foo.vb /t:exe /o:foo.dll`

**Expected Behavior**: Since the output path is specified as foo.dll, the expectation is that there's a foo.dll on disk.

**Actual Behavior**: It outputs a foo.dll.exe because the target is a exe. 

.NET Core executables are output as dlls by default because they are run by a different host. Supporting that will require a post-process step which is brittle.

**Comment by gafter** [comment]
I suspect this is by design.

**Comment by srivatsn** [comment]
In an offline thread @AlekseyTs confirmed that this has always been the behavior and suggested a targeted break in behavior i.e., if the output name already has an extension that we recognize (dll/exe/netmodule), don’t add another one. Chances of a break will be quite limited.

@gafter @jaredpar @AlekseyTs - this is blocking .NET Core VB projects. Can we prioritize fixing this?
