### ISSUE TITLE
AdditionalFileItemNames property group breaks CodeModel rename

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#13697]
**Version Used**: Visual Studio 2015 Update 3

**Steps to Reproduce**:
1. Create a new console application.
2. Add the following into the project file:

```
  <PropertyGroup>
    <AdditionalFileItemNames>$(AdditionalFileItemNames);None</AdditionalFileItemNames>
  </PropertyGroup>
```
1. Attempt to rename Program.cs to something else. Click "Yes" when asked to rename the type.

**Expected Behavior**: The type gets renamed.

**Actual Behavior**: The type isn't renamed.

**Comment by CyrusNajmabadi** [comment]
Closing.  We are not changing codemodel experiences.
