### ISSUE TITLE
Add embedded source support for Windows PDBs

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn#13707]
The design tracked by #12625 already accounts for Windows PDBs, but an issue where diasymreader can write but not read back embedded sources for documents with no sequence points.

This is to track getting the diasymreader issue resolved and #13138 unblocked.

Tracking it separately to mark the most pressing need (in portable PDBs) done for 2.0 Preview 5.

**Comment by nguerrera** [comment]
Moving to 2.1 since there's too much project system work going on to get this in for RC. cc @srivatsn

**Comment by nguerrera** [comment]
Close stale WIP PR #13138, but it is the starting point for when this ultimately gets picked back up.

**Comment by tmat** [comment]
@nguerrera I'm gonna finish this. Are "documents with no sequence points" the only issue you know of?

**Comment by nguerrera** [comment]
@tmat Yes. That was the only known issue.
