### ISSUE TITLE
FileBasedXmlDocumentationProvider processes DTDs

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1371]
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Utilities/Documentation/FileBasedXmlDocumentationProvider.cs needs to consume http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Utilities/Documentation/XmlDocumentationProvider.cs,59.

This is a security hole.

While you're at it, please also fix https://roslyn.codeplex.com/workitem/406; you can see my fixed version at https://github.com/SLaks/VSEmbed/blob/master/VSEmbed.Roslyn/XmlDocumentationProvider.cs

**Comment by jasonmalinowski** [comment]
:+1:

The performance improvements would be nice to make, but we can track that as a separate bug and separate commit.

**Comment by basoundr** [comment]
Reopening this issue so this could be tracked for RC

**Comment by MattGertz** [comment]
Approved for next preview.

**Comment by Pilchie** [comment]
Closing, since this is now merged into preview.
