### ISSUE TITLE
Inspecting ValueTuple in VB immediate mode raises Assertion Failed dialog.

### ISSUE THREAD

**Issue by craigajohnson** [dotnet/roslyn#13715]
**Version Used**: 
VS 2015 Update 3 (14.0.25425.01)

**Steps to Reproduce**:
1. Create a VB console app with any line of code in Main, set a break point on that line and run.
2. When reaching the breakpoint, go to Immediate Mode.
3. Type ?(0,1) [Enter]

**Expected Behavior**:
Show:
(0, 1)
  Item1: 0
  Item2: 1

**Actual Behavior**:
Displays an Assertion Failed dialog. (It will display the Tuple value after dismissing the dialog with Ignore). 

![roslyn tuple assertion](https://cloud.githubusercontent.com/assets/5340203/18400572/bad9b28a-7693-11e6-8783-99d32580b77e.png)

**Comment by jaredpar** [comment]
Thanks for reporting this issue.  VB tuples support in the EE is planned for preview 5.  This should be fixed by then.

**Comment by craigajohnson** [comment]
Do you know when this fix will be in the master branch?

**Comment by craigajohnson** [comment]
Never mind - it looks like it was merged today! Nice job.

**Comment by jaredpar** [comment]
@craigajohnson WRT the merge.  We have a script that auto-merges between our dev15-preview-5 branch and master.  It runs a couple of times a day.
