### ISSUE TITLE
Allow nested types in interfaces

### ISSUE THREAD

**Issue by int19h** [dotnet/roslyn#13725]
C# (and presumably VB?) does not allow an interface declaration to contain a nested type. There doesn't seem to be any clear reason for this limitation - nested types are useful in interfaces for the same scenarios they're useful for classes; e.g. to define a type that is strongly associated with that particular interface and its methods. One scenario that doesn't apply to interfaces is giving special access to private members of the outer type, since in interfaces, all such members are public - but it's not the only reason to use nesting.

So far as I can see, there's no IL-level restriction on this, at least not according to Ecma-335 spec - `nested` is permitted on any type record, including interfaces. Semantics is otherwise identical, too. So it's strictly a language syntax limitation.

**Comment by HaloFour** [comment]
Actually VB.NET does allow this:

```vb
Public Interface IFoo
    Class Bar
    End Class
End Interface
```

I want to say that this was already proposed and that there was a brief discussion regarding why the C# spec chose to not allow such nested types but I can't find the issue either here or on CodePlex.

**Comment by DavidArno** [comment]
As everything inside an interface must be public, this "feature" would promote the use of public nested types.

**Comment by int19h** [comment]
Not promote, allow. And they're already allowed in classes and structs, so it wouldn't be anything new.

I understand that there are style guides that prohibit this, but I don't think the language should be the arbiter here. Pros and cons of nested classes are wrt readability - they don't enable any unsafe practices.

**Comment by DavidArno** [comment]
C# is a mature language, thus anything new added to it should be a "good thing" as such new features are implicitly being promoted as a good way of working.

[Inner classes should only be implementation details and so shouldn't be public](https://github.com/DavidArno/SuccincT/issues/10). Your porposal would not only encourage public inner classes, it would mandate that any class implementing such an interface implement that inner class (whether it needed to or not) and make the inner class public. This is not a "good thing".

**Comment by int19h** [comment]
In this case, what is a "good thing" is very subjective.

For example, public inner classes are quite useful when defining families of "case classes" (to borrow Scala terminology). Having them nested inside their parent abstract class makes them syntactically more like enums, in that the type provides a namespace for the cases. It also makes it possible to ensure that the whole assemblage is fully encapsulated, by making the constructor of the base private, so that only inner classes can reference it. There's no other way provided by the language to define such a construct, since only nested classes have special visibility rules that allow access to private members of the outer class.

**Comment by gafter** [comment]
This is being done in C# 8 as part of "[default interface methods](https://github.com/dotnet/csharplang/issues/52)".  For any further discussion, please take it to the `csharplang` repo.
