### ISSUE TITLE
Inline Temp Sometimes Removes Comment

### ISSUE THREAD

**Issue by zanqi** [dotnet/roslyn#13730]
**Version Used**: 14.0.25425.01 update 3

**Steps to Reproduce**:

1. Copy and paste the following code 
```
using System.Collections.Generic;

class Class1
{
    private void Test1(List<int> line)
    {
        var newLine = line;
        // abc
        newLine.RemoveAt(0);
    }
}
```
2. Run inline temp on variable newLine

**Expected Behavior**: Comment abc should remain

**Actual Behavior**: Comment is removed

**Comment by Pilchie** [comment]
Is this a dupe of a trivia bug that you already have?

**Comment by brettfo** [comment]
Yes, this is a case covered by #1017.
