### ISSUE TITLE
Generate Constructor doesn't support readonly autoproperties

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#13749]
``` C#
class C
{
    public int Prop { get; }
}

class Program
{
    static void Main()
    {
        var prop = 42;
        var c = new C(prop);
    }
}
```

Invoke Generate Constructor on C.

**RESULT**
A new field named `prop` is created.

**EXPECTED**
To just initialize `Prop` instead.

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/roslyn/pull/14827
