### ISSUE TITLE
InteractiveWindow / VisualStudioInteractiveWindow - ContentTypeMetaData.cs

### ISSUE THREAD

**Issue by WolfieWerewolf** [dotnet/roslyn#1375]
This is a small one but I thought I would mention it.  The above is duplicated in both projects except the instance in Interactive Window includes only the internal class ContentTypeMetaData whereas the VisualStudioInteractiveWindow project has an additional static class ContentTypeMetaDataHelpers which is necessary to implement the VSInteractiveWindow.

I'm sure both projects will be eventually re-factored and merged into one assembly (Which is what I'm doing and how I noticed it), but I thought it was worth mentioning.

Kind Regards
/W

**Comment by ManishJayaswal** [comment]
@WolfieWerewolf We do not have any plans to merge VisualStudioInteractiveWindow and InteractiveWindow into one assembly. They are different components in different layers.

**Comment by WolfieWerewolf** [comment]
Six months or so later.... I came to that realization some time ago :-)  
Thanks for the answer though.

/W
