### ISSUE TITLE
Roslyn fails to enforce definite assignment rule for a variable assigned in a local iterator function or local async function

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#13762]
Roslyn fails to enforce definite assignment rules for variables which are assigned in local iterator functions or local async functions which are called before the variables in question are used.

Since these types of local functions don't execute all statements at the first call it can't be proven that assignment was executed.

here are some examples:

1) Since I don't iterate the result of Local function it's body won't execute at all and I will end up using unassigned local variable i;
```cs
using System;
using System.Collections.Generic;

public class C
{
  static void Main()
  {
    int i;

    Local();

    Console.WriteLine(i);

    IEnumerable<int> Local()
    {
      yield return 0;

      i = 10;
    }
  }
}
```

2) This case even marks statement 'i = 10;' as unreachable but still allows to use the variable in the enclosing method.
```cs
using System;
using System.Collections.Generic;

public class C
{
  static void Main()
  {
    int i;

    Local();

    Console.WriteLine(i);

    IEnumerable<int> Local()
    {
      yield break;

      i = 10;
    }
  }
}
```

3) It's almost guaranteed that local variable i won't be assigned by the time it's used.
```cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

public class C
{
  static void Main()
  {
    int i;

    Local();

    Console.WriteLine(i);

    async Task Local()
    {
      await Task.Delay(1000*60*60);
      i = 10;
    }
  }
}
```

**Comment by agocke** [comment]
Hmm that would indicate that `yield` and `await` do not generate branches out of the method, which is large bug. Thanks for the report.

**Comment by controlflow** [comment]
Branches out of the method from `await` expression? Seriously? :)
What about whole local iterator function body, delayed until `.GetEnumerator()` + `.MoveNext()`?

The problem here is not the missing exit edge in control flow graph from `await` expression (unlike `yield return`, there is no exit edge there). The core problem here is the delayed/suspendable nature of both iterator and async functions, preventing to use other stuff like `out`/`ref` parameters/returns.

The use-site definite assignment checking for such local functions can't be implemented sound. I think you should simply do not replay writes of iterator/async local functions (like you do for delegate creation from local function symbol) during definite assignment processing of local function calls.

**Comment by agocke** [comment]
@controlflow I disagree that it can't be implemented soundly, but not propagating writes for iterator/async functions is attractive -- the semantics are complex and it's probably not clear to users where the data flow branches are.

**Comment by TessenR** [comment]
@agocke Is there any decision how this should be implemented? I will appreciate any clarification about expected behavior.

I personally think that compiler should not propagate writes from iterator/async local functions at all.

However if you are planning to propagate writes from iterator/async local functions I'd like to know expected results for some other cases which also don't have compiler errors currently.

1) enumerating local iterator via foreach:
```cs
    void M()
    {
        int x;
        
        foreach(var y in Local()) { }
        
        System.Console.WriteLine(x);
        
        System.Collections.Generic.IEnumerable<int> Local()
        {
            yield return 5;
            x = 5;
        }
    }
```

2) enumerating local iterator via foreach with breaks in the loop body:
```cs
    void M()
    {
        int x, y;
        
        foreach(var z in Local()) { break; }
        
        System.Console.WriteLine(x);
        System.Console.WriteLine(y);
        
        System.Collections.Generic.IEnumerable<int> Local()
        {
            x = 5; // executed 
            yield return 5;
            y = 10; // not executed
        }
    }
```

3) Enumerating part of the collection e.g. with linq Take method
```cs
using System.Linq;
class C
{
    void M()
    {
        int x,y;
        
        foreach(var z in Local().Take(2)) { }
        
        System.Console.WriteLine(x);
        System.Console.WriteLine(y);
        
        System.Collections.Generic.IEnumerable<int> Local()
        {
            yield return 5;
            x = 5;
            yield return 5;
            y = 5;
        }
    }
}
```

4) Enumerating part of the collection when it has unknown number of elements before assignment
```cs
    void M()
    {
        int x;
        
        foreach(var z in Local().Take(int.MaxValue)) { } // is int.MaxValue enough? 
        
        System.Console.WriteLine(x);
        
        System.Collections.Generic.IEnumerable<int> Local()
        {
            var random = new System.Random();
            int counter = 0;
            while(counter++ < random.Next())
                yield return 5;
            x = 5;
        }
    }
```

5) assignment before/after first await in local async function with non-awaited call
```cs
    void M()
    {
        int x, y;
        
        Local();
        
        System.Console.WriteLine(x);
        System.Console.WriteLine(y);
        
        async System.Threading.Tasks.Task Local()
        {
            x = 5;
            await System.Threading.Tasks.Task.Delay(1000*60*60*24);
            y = 5;
        }
    }
```

6) assignment if method is awaited:
```cs
    async void M()
    {
        int x;
        
        await Local();
        
        System.Console.WriteLine(x);
        
        async System.Threading.Tasks.Task Local()
        {
            await System.Threading.Tasks.Task.Delay(1000*60*60*24);
            x = 5;
        }
    }
```

**Comment by agocke** [comment]
I'm going to disallow and iterator functions from definitely assigning variables. The behavior is just too subtle.

Compiler data flow will be fixed to recognize these branches, though.


________________________________

**Comment by agocke** [comment]
(And by that I mean, every time control flow is returned to the caller, that counts as a branch out of the method. And yes, that means there's an implicit branch before the first statement of an iterator).

**Comment by xieguigang** [comment]
![81761b83014db0e6b95031e35c2bda65c0167ee1](https://cloud.githubusercontent.com/assets/9410171/20383803/33c2432c-acec-11e6-8692-d793ddcbdc30.png)

Probably the LINQ operator in VisualBasic combine with lambda can be more simplify
