### ISSUE TITLE
Expose TopSyntaxComparer publicly 

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#13776]
Related issue: #8962
Related to: #13772 

I'm breaking this apart from the above issue/PR based on a discussion with @CyrusNajmabadi 

I'm after [`ComputeMatch`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Differencing/TreeComparer.cs,1f3b5152c6594079,references) on an instance of [`TopSyntaxComparer`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/EditAndContinue/TopSyntaxComparer.cs,df715b0df7c9aaaa).

Bits and pieces have already been made public but this particular SyntaxComparer implementation has not. One thing I noticed is that `TopSyntaxComparer` belongs to `Microsoft.CodeAnalysis.CSharp.Features` which isn't currently exposing any public API.

**Comment by Przemyslaw-W** [comment]
I am also interested in EnC API - see #1617
I think this will be suitable for my use case as well. Will this be included into update 4?

**Comment by CyrusNajmabadi** [comment]
Closing for now.  @JoshVarty if you ever get back around to needing this, let us know.
