### ISSUE TITLE
Test TestRecoverableSyntaxTreeCSharp is flaky

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13788]
The test `Microsoft.CodeAnalysis.UnitTests.SolutionTests.TestRecoverableSyntaxTreeCSharp` depends on GC behavior that is not guaranteed. I've seen it fail nondeterministically, for example

http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/3542/

**Comment by AdamSpeight2008** [comment]
@gafter I've seen the Visual Basic also fail flaky (see #13600). Which involved `TypeKind` so may narrow down the issue.

**Comment by gafter** [comment]
The issue is that GC is not deterministic.

**Comment by natidea** [comment]
Disabled test with #13857

**Comment by AdamSpeight2008** [comment]
What about the VB test?

**Comment by CyrusNajmabadi** [comment]
The VB test was also disabled. @jasonmalinowski introduced thsi and will take a look at it.

**Comment by jasonmalinowski** [comment]
Dupe of #13433.
