### ISSUE TITLE
[Proposal] Disallow public abstract constructors

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#1378]
As far as I understand there is no reason for public abstract constructors to exist, so why not remove the ambiguity? Unless there is something I don't know.

*"CA1012: Abstract types should not have constructors"*
https://msdn.microsoft.com/en-us/library/ms182126.aspx

**Comment by svick** [comment]
Are you suggesting to make this a compile error? That would break backwards compatibility and for that, there should be a very good reason. I don't see removing ambiguity as a good reason here, since it's not really that confusing.

**Comment by dsaf** [comment]
@svick If there ever going to be a 'strict mode' C# compilation, it would fall into that category. Or it could be a compile warning (it's not a static analysis-level problem really).

**Comment by alanfo** [comment]
I'd support a compiler warning for public constructors in abstract classes but I wouldn't support disallowing them altogether as this would break backwards compatibility as @svick said.

The time to have disallowed them would have been C# 1.0 but there's been a heck of a lot of water under the bridge since then :)

**Comment by gafter** [comment]
We cannot do this as it wold be a breaking change.

**Comment by sharwell** [comment]
To add to what @gafter said, the way to implement this would be a Roslyn-based analyzer which implements the CA1012 diagnostic.

1. If you set the severity of a diagnostic to error, your build will fail if that diagnostic is reported.
2. If you provide a code fix for the diagnostic, you can automatically fix all violations of this rule.

The result is an efficient, positive, opt-in experience that provides all of the desired functionality you requested without breaking other users.
