### ISSUE TITLE
Diagnostic Analyzer Error Kept Green (not Red) Squigglie

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/roslyn#138]
I enabled CA1012 with code existing that broke the rule. I saw a green squigglie as expected. 

I then changed this to be an error, and saved the ruleset.

The break correctly appeared in the Error pane as an error and as an error in the Solution Explorer list of active analyzers. 

However, the squiggly did not change from green to red until I closed and reopened the file. 

It would be nice if this "just worked," but at the least, I think there should be mitigation messages somewhere.

**Comment by KathleenDollard** [comment]
BTW, This is especially annoying because I usually keep a set of files open, and it is actually less disruptive to close and reopen VS (which is obviously a pane). 

It would be nice if there was a "rerun analyzers on all open files" button/menu item for this scenario.

**Comment by srivatsn** [comment]
Analyzers are getting rerun when the ruleset changes and that's why the error list is updated. The squiggle not being updated just sounds like a bug.

Any edit\change should rerun analyzers to catch the error list up live.

**Comment by heejaechang** [comment]
probably a bug where tagger when diff doesn't consider error kind as a difference.

**Comment by heejaechang** [comment]
this should have been fixed.

**Comment by heejaechang** [comment]
commit SHA: de6406023b41cd481bcc9297ef887e3ddf8aaba3
