### ISSUE TITLE
Cross-project errors using reference assemblies

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13815]
A persistent pain point has been poor IDE experience for errors in cross-language scenarios. The problems arise both in the error list window and in the squiggles in the editor.

For the error list, we currently offer a drop-down so that the user can select “build only”, “intellisense only” or “both” in the error list. Unfortunately these options are largely meaningless to our end users. To benefit from these options the user must have an understanding of the architecture of the IDE that they rarely possess.

For the “squiggles”, we simply do not have a good solution. If one project does not compile (perhaps due to a small syntax error), any project that references its types may have many errors. These errors can hide (like a needle in a haystack) any useful information that the IDE might provide.

It has been proposed that the compilers be capable of producing reference assembles for cross-language builds, and that the compilers be tolerant of errors when producing these reference assemblies. This would allow the IDE to use a generated reference assembly of an erroneous project when compiling projects that depend on it.

See also #2184.

**Comment by KirillOsenkov** [comment]
See also #2162

**Comment by Pilchie** [comment]
Since this isn't happening immediately, I'm putting this into a milestone so it doesn't show up in triage queries.

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/issues/7482 (tolerate errors option when emitting metadata-only)

**Comment by CyrusNajmabadi** [comment]
We do gnerate skeletons for cross project assemblies already, allowing errors, and feature like goto def to work.  Closing out.
