### ISSUE TITLE
Syntactic disambiguation: patterns and tuples

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13822]
The syntax starting with `A<` below cannot parse as a type, and therefore should be parsed as an expression. Roslyn currently does not handle it correctly, and produces a syntax error.

``` cs
            M(x is A < B, (C > D));
```

**Comment by gafter** [comment]
This is unlikely to occur "in the wild".

**Comment by jcouv** [comment]
@gafter Wasn't this addressed by your change https://github.com/dotnet/roslyn/pull/16834 already?

**Comment by gafter** [comment]
Yes, I see it was! Thanks.
