### ISSUE TITLE
Regression: Roslyn shouldn't require references for all overloads when an overload matches exactly

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#13824]
Here is a test that demonstrates the problem. It is expected that this test passes.

``` csharp
        [Fact]
        public void ExtraReferencesNeeded()
        {
            var comp1 = CreateCompilationWithMscorlib(@"
using System.Xml.Linq;

public static class C
{
    public static void M(string s) { }

    // A referencing compilation passing a string shouldn't need
    // a reference to System.Xml.Linq here
    public static void M(XDocument d) { }
}", references: new[] { SystemXmlLinqRef });

            comp1.VerifyDiagnostics();

            var comp2 = CreateCompilationWithMscorlib(@"
public class D
{
    public void M()
    {
        C.M(""test string"");
    }
}", references: new[] { comp1.ToMetadataReference() });

            comp2.VerifyDiagnostics();
}
```

**Comment by davkean** [comment]
Would this be that MSBuild regression: https://github.com/dotnet/roslyn/issues/9370?

**Comment by agocke** [comment]
@davkean I suspect the same root cause.

I also agree with Neal on the spec's statement of applicability. This is purely whether we want to be noncompliant for backwards compatibility.

**Comment by gafter** [comment]
This was a decision we made some years ago (that Roslyn would require references to types mentioned in the methods of a method group) for VS2015. We were fully aware of the consequences and documented the decision. There may be performance implications for changing it.

**Comment by gafter** [comment]
This is a regression in the sense that we no longer compile code we used to. It is not a regression (rather, the current behavior could be characterized as a bug fix) in the sense that we now follow the language spec.

**Comment by jaredpar** [comment]
> This is a regression in the sense that we no longer compile code we used to.

That's a pretty bad regression.  At the moment it's preventing us from correctly building Visual Studio without modification of sources.  The 1.0 RTM compiler was able to build Visual Studio without change hence this is a regression since then.

**Comment by gafter** [comment]
@jaredpar I suspect there have been changes to some APIs used in visual studio since 1.0 RTM that added methods to a method group that mention unreferenced assemblies.

**Comment by gafter** [comment]
@agocke Did this test pass in Roslyn 1.0 RTM?

**Comment by agocke** [comment]
My mistake, I actually trimmed this repro too much -- the actual repro requires `params`:

```
        public static void M(string s, params string[] rest) { }
        public static void M(XDocument d, params string[] rest) { }
```

That will compile successfully in Roslyn 1.0 RTM.

**Comment by gafter** [comment]
Also #9370 and #15588.

**Comment by AlekseyTs** [comment]
It would be easier to reason about the issue is exact error messages were included.

**Comment by jaredpar** [comment]
This behavior is currently as spec'd and a part of the shipping 7.0 compiler.  I agree it could cause upgrade problems for customers.  But until we see a few motivating samples this won't meet the bar.
