### ISSUE TITLE
Get remaining IDE analyzers to run Out-of-process

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#13838]
We enabled certain IDE analyzers to run out of process for the `2.0 (Preview 5)` milestone, but we need to do the rest, and fill out OpenFilesOnly appropriately.

**Comment by Pilchie** [comment]
Can you add a list of which ones they are to the issue description?

**Comment by Pilchie** [comment]
@CyrusNajmabadi https://github.com/dotnet/roslyn/pull/15103 still isn't merged?!?!

**Comment by Pilchie** [comment]
Given that there was some performance concern about the PR to do this, we won't do it in RTW, but it will be a focus after that.

**Comment by Pilchie** [comment]
Still pending - we need to get this done early in 15.6, but I think with the simplify type names fix @sharwell did we are in much better shape.

**Comment by CyrusNajmabadi** [comment]
@mavasani do we have any analyzers now that don't run OOP?

**Comment by mavasani** [comment]
> @mavasani do we have any analyzers now that don't run OOP?

Only remaining ones are from internal partners which are the special DocumentDiagnosticAnalyzer and ProjectDiagnosticAnalyzer subtypes. All the regular analyzers run OOP, so we can close this one out.
