### ISSUE TITLE
Linq used in DataFlowPass.cs

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13834]
A recent change to DataFlowPass.cs added this assertion:

```cs
            Debug.Assert(localsOpt.Where(l => l.DeclarationKind == LocalDeclarationKind.UsingVariable).All(_usedVariables.Contains));
```

Even though it is executed only in debug mode, we avoid Linq on hot paths in the compiler. Please rewrite this or remove it.

(The simplest fix would be to fuse with the immediately preceding loop. Or delete the assertion, as it tests a condition obviously established by the previous loop).

**Comment by AlekseyTs** [comment]
In my opinion, it is acceptable to use Linq in asserts.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/commit/645f5add37ccd31f1f85cc5e4f8fa6c0e9c1baf1
