### ISSUE TITLE
Please support yield collection from IEnumerable 

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#13852]
In addition to `yield return` from IEnumerable function. C# should be able to yield any other IEnumerable from inside

``` C#
IEnumerable<int> GetInt()
{
    yield return 0;
    yield return 1;
    yield return 2;
    yield [3,4,5];
    yield return 6;
    yield return 7;
    yield return 8;
    yield Enumerable.Range(9,99);
}
```

Like yield\* in js

**Comment by dsaf** [comment]
F# has this, it enables proper recursion as well: http://theburningmonk.com/2011/09/fsharp-yield-vs-yield

**Comment by alrz** [comment]
#15

**Comment by gafter** [comment]
Language design discussion now takes place at https://github.com/dotnet/csharplang .  Please reopen there if you want to continue this.  I am closing this as the discussion appears to be stale.  See also https://github.com/dotnet/csharplang/issues/378
