### ISSUE TITLE
Proposal: better editor support for commented code

### ISSUE THREAD

**Issue by vbcodec** [dotnet/roslyn#13896]
Commented code is text without any intelisense support, just text without any meanings. 
There is need for some intelisense support for commented code like hover tips, Go To Definition and other what's possible

**Comment by HaloFour** [comment]
So you're asking that the compiler start to parse into comments just in case they might contain code?  The vast, vast majority of comments won't contain any code so it sounds like an expensive way to waste time.

I'd recommend source control.  Then commenting out blocks of code becomes unnecessary.

**Comment by vbcodec** [comment]
@HaloFour 

It won't be high cost to discard all non-code from comments, and source control is defitelly much less usefull. I just want to quickly get some informations about types / function without un-commenting,, read information, then recommenting. Don't think it is difficult to understand.

**Comment by Pilchie** [comment]
This is not likely something that we will do.
