### ISSUE TITLE
Proposal: multiple variables declared in a 'let' query clause

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13919]
I propose to allow multiple variables in a query expression's `let` clause.

The specification would be changed to support this as follows:

> A query expression with a `let` clause
> 
> ``` cs
> from x in e
> let y = f, z = g, …
> …
> ```
> 
> is translated into
> 
> ``` cs
> from * in ( e ) . Select ( x => new { x , y = f, z = g, … } )
> ```

this would facilitate the use of `out var` arguments in query expressions with no additional machinery:

``` cs
from x in e
select y = M(out var z0), z = z0
```

It may also have some synergy with tuples and pattern-matching.

/cc @jcouv @VSadov @AlekseyTs @MadsTorgersen

**Comment by HaloFour** [comment]
Please also consider the select+filter scenario of using pattern matching with LINQ which I think will become and incredibly common use case.

**Comment by AlekseyTs** [comment]
I would like to point out that the proposed translation looks inconsistent with VB translation. In VB, comma inside Let clause is causes an extra Select call and all range variables declared in the Let clause prior to the comma are in scope after the comma. I.e. ```Let a = <expr1>, b = <expr2>``` is equivalent to ```Let a = <expr1> Let b = <expr2>``` and ```a``` is in scope in ```expr2```.

**Comment by gafter** [comment]
We considered this yesterday in the LDM and we believe we are more likely to support

> A query expression with a let clause
> ```cs
> from x in e
> let (y, z) = e2
> …
> ```
> is translated into
> ```cs
> from * in ( e ) . Select ( x => new { x , y = (var (y, z) = e2).Item1, z = z } )
> ```

/cc @dotnet/ldm

**Comment by gafter** [comment]
Dup of https://github.com/dotnet/roslyn/issues/13964
