### ISSUE TITLE
[Test Failures on windows_eta_open_prtest] Connectivity Issue: Possible issue connecting to GitHub or cloning the repository.

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#13929]
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/3832/

<details>
   <summary> Failures </summary>
Connectivity Issue

Possible issue connecting to GitHub or cloning the repository. This could be caused by a lack of network connectivity or a lack of disk space. Please email netciadmin. Error cloning remote repo 'origin'
Indication 1 

Could not find a revision to build

Unable to find the appropriate revision to build. Merge conflicts? If so, resolve them and update PR. If this is a ROSLYN branch: Feature branch? If yes, then this failure is expected - we do not currently support running internal jobs against feature branches. Future, master or stabilization? If yes, then its likely the commit pump between Roslyn to Roslyn internal is not running. Contact mlinfraswat@microsoft.com. 
Indication 2 

GitHub Timeout

Timeout cloning repo from GitHub. Retry the job.
Indication 3 

There are errors when processing test results

There was an error processing the xunit test results: [xUnit] [ERROR] - No test reports found for the metric 'xUnit.Net' with the resolved pattern '**/xUnitResults/*.xml'. Configuration error?.
Indication 4 
</summary>

**Comment by dpoeschl** [comment]
@jasonmalinowski I think @mattwar is the person responsible for investigating these, but correct me if I'm wrong.

**Comment by jmarolf** [comment]
love the fancy
```XML
<details>
   <summary> Failures </summary>
</details>
```

**Comment by mattwar** [comment]
Apparently the machine was 'wedged'.  Now it is rebooted.
