### ISSUE TITLE
Port AttributeTests_Tuples.cs tests to VB

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#13942]
The tests provide additional coverage of various corner cases of tuple element name emit to metadata.

While not blocking for initial implementation of the feature, we should port the tests for the purpose of code coverage and perhaps to find bugs.

**Comment by cston** [comment]
Fixed in https://github.com/dotnet/roslyn/commit/81ad15cca0176968a4b817ef51e2fe801cd456f3
