### ISSUE TITLE
Cannot generate constructor from getter only props

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#13944]
``` csharp
abstract class Contribution
    {
        public string Title { get; }
        public DateTimeOffset DateCreated { get; }
        public User User { get; }
        public int Number { get; }
        public Milestone Milestone { get; }
    }
```

If I select all of this and press `Ctrl+.` then I don't get the option to generate the constructor. However, if I add back all my setters, I get this option.

**Comment by Pilchie** [comment]
Similar to https://github.com/dotnet/roslyn/issues/13749

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/roslyn/pull/14827
