### ISSUE TITLE
[Clash] ErrorID

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#13949]
Just making us aware that there a potential clash of `ERRID` numbers when merging.

#13918 `ERR_DocFileGen = 37258`
#13799 `ERR_TupleExplicitNamesOnAllMembersOrNone = 37258`

My suggestion is to renumber the first one, so that the errIDs used by Tuples are grouped together.

**Comment by gafter** [comment]
`ERR_TupleExplicitNamesOnAllMembersOrNone` doesn't exist any longer.
