### ISSUE TITLE
Proposal: Allow source code generators to run on custom project data files

### ISSUE THREAD

**Issue by Opiumtm** [dotnet/roslyn#13954]
[Source code generators feature](https://github.com/dotnet/roslyn/blob/future/docs/features/generators.md)

Similar to code generation for XAML files in Visual Studio 2015 for Universal Windows Platform (compiled bindings code generation, for example).

File of any type could be passed to compiler (as command-line parameter or as reference to file containing files list) and be accessible in source generators as full file path so source generator could plainly read file content and generate appropriate source code if needed.

It would be a fine generalization of VS tools and make XAML code generation (i.e. compiled {x:Bind ...} bindings) special case of this generic feature. And it wouldn't require updates to Visual Studio as source code generators would be distributable and updateable from nuget.

**Comment by gafter** [comment]
We do not have any such feature in Roslyn.  If you're talking about the language feature, please reopen your issue in `csharplang`.
