### ISSUE TITLE
Unit test failed locally: Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.BinaryOperators.Test1

### ISSUE THREAD

**Issue by zanqi** [dotnet/roslyn#13968]
**Version Used**: Accepted changes up until 20-Sep-2016

**Steps to Reproduce**:
1. Run msbuild /v:m /m BuildAndTest.proj locally

**Expected Behavior**: No error

**Actual Behavior**: Have the following error message,
Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.BinaryOperators.Test1
      Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : 
      Execution failed for assembly 'C:\Users\Key\AppData\Local\Temp\'.

Expected (left) vs Actual (Right)

![image](https://cloud.githubusercontent.com/assets/2538192/18732987/db684132-8099-11e6-9b83-624b0fa93d3e.png)

**Comment by gafter** [comment]
This is over a year old and I have not seen it appearing again. So closing. Please let me know if this recurs.
