### ISSUE TITLE
NRE in build task

### ISSUE THREAD

**Issue by livarcocc** [dotnet/roslyn#13966]
"E:\git\temp\temp.csproj" (default target) (1) ->
(CoreCompile target) ->
  E:\git\cli-1\artifacts\win10-x64\stage2\sdk\1.0.0-preview3-003633\Microsoft.CSharp.Core.targets(71,5): error MSB3883: Unexpected exception:  [E:\git\temp\temp.csproj]
  E:\git\cli-1\artifacts\win10-x64\stage2\sdk\1.0.0-preview3-003633\Microsoft.CSharp.Core.targets(71,5): error : System.NullReferenceException: Object reference not set to an instance of an object. [E:\git\temp\temp.csproj]
  E:\git\cli-1\artifacts\win10-x64\stage2\sdk\1.0.0-preview3-003633\Microsoft.CSharp.Core.targets(71,5): error : at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.GetUserName() [E:\git\temp\temp.csproj]
  E:\git\cli-1\artifacts\win10-x64\stage2\sdk\1.0.0-preview3-003633\Microsoft.CSharp.Core.targets(71,5): error : at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.GetPipeNameForPath(String compilerExeDirectory) [E:\git\temp\temp.csproj]
  E:\git\cli-1\artifacts\win10-x64\stage2\sdk\1.0.0-preview3-003633\Microsoft.CSharp.Core.targets(71,5): error : at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.RunServerCompilation(RequestLanguage language, List`1 arguments, BuildPaths buildPaths, String keepAlive, String libEnvVariable, CancellationToken cancellationToken) [E:\git\temp\temp.csproj]
  E:\git\cli-1\artifacts\win10-x64\stage2\sdk\1.0.0-preview3-003633\Microsoft.CSharp.Core.targets(71,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [E:\git\temp\temp.csproj]

**Comment by jaredpar** [comment]
Repro steps, context, etc ... ?

**Comment by livarcocc** [comment]
Talked to @agocke, he said that's all he needed. Can you chat with him?

**Comment by jaredpar** [comment]
@livarcocc even if you talked with @agocke need more info on this bug.

**Comment by livarcocc** [comment]
This only happens on windows. At least, I could not repro it on OSX. Have not tried on a Linux box.

Here are the repro steps:

1. Clone https://github.com/livarcocc/cli-1/tree/remove_unofficial_csc. The folder where you cloned the CLI will be known for these repro steps as <clireporoot>
2. Run build.cmd /t:Compile from root.
3. After it is done, create a temporary folder
4. Then invoke <clireporoot>/artifacts/win10-x64/stage2/dotnet new -t msbuild to create an msbuild project that the CLI can build and run.
5. Copy NuGet.Config from <clireporoot> to this temp folder.
6. Run <clireporoot>/artifacts/win10-x64/stage2/dotnet restore
7. Run <clireporoot>/artifacts/win10-x64/stage2/dotnet build3

Actual:
You will hit the NRE above. 

Expected:
Build should succeed.
