### ISSUE TITLE
'Make sync' doesn't remove my 'await'

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#13961]
When I make an async method that can actually be synchronous, the quick fix 'Make Sync' does not remove my 'await' where I called my synchronous async method:

![image](https://cloud.githubusercontent.com/assets/1402694/18723624/2d556cf6-7fee-11e6-844d-2f057fc6a981.png)

**Comment by dpoeschl** [comment]
@CyrusNajmabadi Is this by design?
