### ISSUE TITLE
What do the .Next Projects do?

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#13974]
Could we add an explanation to the wiki?

**Comment by jmarolf** [comment]
We can... They are a temporary artifact so that people can debug using both Visual Studio 2015 and Visual Studio "15" Preview.

Setup -> Set as startup project to debug roslyn on Visual Studio 2015
Setup.Next -> Set as startup project to debug roslyn on Visual Studio "15" Preview

**Comment by Pilchie** [comment]
Slight clarification - they probably aren't temporary, but once we depend on VS "15" as a minimum, the code from .Next will be moved to Setup, and Setup.Next will be for stuff that is only in the VS *after* 15.  That's why we didn't call it "Setup.15" in the first place...
