### ISSUE TITLE
Adding an analyzer using the roslyn sdk project template shouldn't change existing startup project in solution

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#1397]
I noticed that if I add one of the roslyn sdk template projects to a solution (right click solution node in solution explorer and add new project), the newly added project becomes the startup project unsetting the startup project that I already had. This seems like a bug. This does not happen when I add other projects (like simple console apps) to my solution.

**Comment by jmarolf** [comment]
We do this so the VSIX is debugged on F5.  We can check for other existing projects and bail in that case.

**Comment by jmarolf** [comment]
This has been fixed internally (Templates are not open source yet).  @shyamnamboodiripad can you verify this?
