### ISSUE TITLE
Syntax Visualizer for VSCode / Xamarin

### ISSUE THREAD

**Issue by sschmid** [dotnet/roslyn#13973]
The Syntax Visualizer helps a lot and is a great tool.

It would be nice to have a Syntax Visualizer also for VS Code or / and Xamarin to be able to use it on a Mac.

Thanks!

**Comment by jcouv** [comment]
If that helps, there is some visualization for syntax trees built into [sharplab.io](https://sharplab.io/).

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #64](https://github.com/dotnet/roslyn-sdk/issues/64) via [**ZenHub**](https://www.zenhub.com/)
