### ISSUE TITLE
No way to get elements of a tuple conversion

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13976]
The compiler's APIs provide no way to get the elementwise conversions of a tuple conversion, or of a deconstruction. Both should be easily available.

For example, there is no way in an analyzer to know that a user-defined conversion is used within the conversion underlying a tuple passed as a parameter.

**Comment by VSadov** [comment]
request for a new API.

**Comment by jcouv** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/11803
