### ISSUE TITLE
Proposal: switching on/off certain language features in source code

### ISSUE THREAD

**Issue by Opiumtm** [dotnet/roslyn#13986]
In a hypothetical situation when new language features could potentially break backward compatibility or introduce uncertainty in source code, it would be good to turn off some language features.
Language features should be configurable globally via compiler command-line option and locally in source code. Introduce `#region`-like syntax to switch language features locally.

``` C#
// switch off "tuples" language feature
#switch_off Tuples
...
// switch on "tuples" language feature again
#switch_on Tuples
```

Also it would be easier to introduce experimental language features, as they would be turned off by default and developer can turn it on in source code or via command-line option.

**Comment by svick** [comment]
> In a hypothetical situation when new language features could potentially break backward compatibility or introduce uncertainty in source code, it would be good to turn off some language features.

But we're not in that hypothetical situation. So why introduce this now?

> Also it would be easier to introduce experimental language features, as they would be turned off by default and developer can turn it on in source code or via command-line option.

As far as I know, that's mostly already how features of C# 7.0 were initially implemented: you had to add `<Features>` to your csproj or `/features:` on the command line. It's somewhat clunky, but I think it works for the use case of experimental/unfinished features.

**Comment by paulomorgado** [comment]
Why would you want to switch of tuples and keep the source code? What tuple code would compile if tuples were switched off?

And, if this were ever to be implement, I would favor something like:

```C#
#pragma feature disable tuples
// ....
#pragma feature restore tuples
````

But, really, so much work has been done over the years to assure backward compatibility that this feature would be useless.

**Comment by DavidArno** [comment]
`pragma feature disable inheritance`
`pragma feature disable null`
`pragma feature disable goto`

I can dream... :grinning:

**Comment by dsaf** [comment]
@DavidArno also no default mutability!

**Comment by vbcodec** [comment]
#praqgma feature diable pragma feature disable

**Comment by Opiumtm** [comment]
>But we're not in that hypothetical situation. So why introduce this now?

I have been somewhat scared with "extension everything" and "pattern matching" upcoming features.
These features are indeed great, but I think they would break backward compatibility for some code.

**Comment by HaloFour** [comment]
> but I think they would break backward compatibility for some code.

Please cite evidence as to why you think either feature would affect any existing code.

**Comment by Opiumtm** [comment]
@HaloFour "extension everything" effectively introduce uncertainty in code.
For example, if you extend class and introduce parameterless constructor it would conflict with class own constructor having one parameter with default value.
If you extend class to introduce extension operators it could also conflict.
Yes, it require namespace when extension is referenced to be listed in `using`.

Class and interfaces extensions certainly could introduce backward compatibility issues. Sometimes it is desirable to switch off already existing extension methods locally using proposed `pragma` keyword.

**Comment by HaloFour** [comment]
Extension methods have already proven that this is not the case.  The compiler is perfectly fine at determining where there would be ambiguities and not permitting the extension.

Having to support a Cartesian product of dialects within every source file handled by the compiler would be a supportability nightmare.  If you don't like a particular feature, don't use it.  Set the language level to the version prior.

**Comment by Opiumtm** [comment]
>The compiler is perfectly fine at determining where there would be ambiguities and not permitting the extension.

Could you surely say "extension everything" would do so?

>Cartesian product of dialects 
No dialects, but ability to switch off certain C# analyzer paths.

**Comment by HaloFour** [comment]
> Could you surely say "extension everything" would do so?

I can say with a lot of confidence that the C# team will go to lengths to ensure that the changes that they implement will not break existing syntax or affect existing code bases in a negative manner.  They have a fantastic track record of this.

**Comment by DavidArno** [comment]
> Could you surely say "extension everything" would do so?

The C# language team are frustratingly extreme in their insistence on only allowing features that are fully backward-compatible. So "extension everything" will be backward-compatible, or it won't be permitted into the language.

**Comment by MgSam** [comment]
When I read a C# source file I don't want to go hunting around to figure out what features someone may have turned on or off. Though other languages are moving in this direction, I think it's a mistake as it effectively makes lots of incompatible source branches from a single language. 

It's also no doubt a significant investment for the compiler team that they could instead be spending on other tasks.

**Comment by Opiumtm** [comment]
@HaloFour @DavidArno 
Well... But I'm still scared of upcoming "extension everything" feature. It looks indeed extremely powerful and dangerous!

**Comment by axel-habermaier** [comment]
@Opiumtm: If you don't like a feature, you could also write an analyzer that forbids its use in your projects. So what you're suggesting is basically already supported with Roslyn.

**Comment by Opiumtm** [comment]
@axel-habermaier I would like this feature, but I'm scared about backward compatibility.

**Comment by axel-habermaier** [comment]
@Opiumtm: Ah, I see. In that case, you'll just have to trust the C# team. As the others have already pointed out, they usually know what they're doing! :)

**Comment by DavidArno** [comment]
@axel-habermaier 

> Same goes to @DavidArno; just forbid null, inheritance, and goto via analyzers if you think that would be a good idea. 

Yep, [Arnolyzer](http://davidarno.github.io/Arnolyzer/) exists for that very reason. In fact, I'm coding the the analyzer that reports reassignment of a variable as an error at this very moment :smile:

**Comment by gafter** [comment]
We're not eager to have 2^n different languages.  Having said that, if you still want to pursue this please continue discussion at `csharplang`.
