### ISSUE TITLE
Build race condition

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#13980]
There is a race condition in our build that is causing it to fail with MSB3277 errors. 

``` txt
error MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved. These reference conflicts are listed in the build log when log verbosity is set to detailed. [D:\j\workspace\windows_relea---78ad37e5\src\VisualStudio\Core\SolutionExplorerShim\SolutionExplorerShim.csproj] 
```

 In the last 24 hours we've had three failures:

> http://jdash.azurewebsites.net/builds/kind?name=Build&startDate=2016-09-20&viewName=dotnet_roslyn

The actual error from the diagnostic log is the following:

``` txt
There was a conflict between "Microsoft.VisualStudio.Text.Logic, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "Microsoft.VisualStudio.Text.Logic, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". (TaskId:1581)
                        "Microsoft.VisualStudio.Text.Logic, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "Microsoft.VisualStudio.Text.Logic, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not. (TaskId:1581)
```

The problem appears to be that MSBuild is considering `Binaries\$(Configuration)` when attempting te resolve the `Microsoft.VisualStudio.Text.Logic` reference.  An earlier build component is placing the binary in that directory.  Hence it becomes a race between the component copying it to the output directory and when SolutionExplorerShim builds.

I've labeled this as `urgency-now` because it affects the correctness of the produced DLLs.

**Comment by agocke** [comment]
Another instance: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/3870/

**Comment by jasonmalinowski** [comment]
@mattwar could you look at this? If you can figure out it's a particular area of the codebase owned by a certain team feel free to move it on.
