### ISSUE TITLE
[Proposal] Allow null conditional operators to work with struct pointers 

### ISSUE THREAD

**Issue by jbruening** [dotnet/roslyn#13990]
As comparison of a pointer to null is valid syntax, just add ?-> to the null conditional operators.

example use:

```
struct foo
{
    public int a;
    public int b;
}

unsafe int AOr2()
{
    foo* val = SomePInvokeMethod();
    return val?->a ?? 2;
}
```

**Comment by Unknown6656** [comment]
@jbruening : Maybe I am missing something, but structs are normally not allowed to be null, so a null conditional operator does not make much sense on struct type.
So in a idealistic world, the proposal does not make sense.
Of course, one could have a `nullptr` or an invalid pointer .... but do we need a null conditional operator?
Won't the "invalid" pointer or null-pointer be interpreted bitwise as the struct type in question?
I mean, I would never expect, that the value of `*val` or `val` itself being null, would I?

Do please correct me, If I am wrong, I am eager to know whether I have some big misunderstanding :)

**Comment by axel-habermaier** [comment]
@Unknown6656: While a variable of a struct type never can be ``null``, a pointer to a struct-typed value certainly can be. I've occasionally also missed a ``?->`` operator.

**Comment by Unknown6656** [comment]
Thank you very much for the explanation, Sir.

I think, that this could be categorised as a rather "rare case". But it would be nice to let the community implement it --- as you suggest. In the worst case one would have to branch the current roslyn repo.....

**Comment by gafter** [comment]
This is now championed at https://github.com/dotnet/csharplang/issues/418 and https://github.com/dotnet/csharplang/issues/398.  Please continue any discussion there.
