### ISSUE TITLE
[Proposal] (Minor) Method groups for constructors

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#140]
#### Problem

This is a very small thing, but a small inconsistency still might be worth resolving.

Consider the following:

``` csharp
var ys = xs.Select(New.Y);
```

Now I want to create `Y` using constructor:

``` csharp
var ys = xs.Select(x => new Y(x));
```

Inconsistent, not as convenient (especially if that's not just a single parameter).
#### Proposed solution

Generate method groups from constructors.
I am not sure what the syntax would be, but here is an option:

``` csharp
var ys = xs.Select(new Y);
```

**Comment by lyubomyr-shaydariv** [comment]
What about `var ys = xs.Select(Y.new);` with a more "plain" syntax similar to method groups? Java has method references with siimilar syntax `acceptLambda(Foo::method)` for methods and `acceptLambda(Foo::new)` for constructors respectively. Just curious: there is no way to have a constructor delegate in .NET?

**Comment by ashmind** [comment]
@lyubomyr-shaydariv 
`var ys = xs.Select(Y.new);` sounds great as well. The main reason why I haven't proposed it was because it can clash with static method named `new` on `Y`.

> Just curious: there is no way to have a constructor delegate in .NET?
Hmmm, that's actually a great question. I thought `Delegate.CreateDelegate` accepted `MethodBase`, but it takes `MethodInfo`. That means that the feature I proposed would need a method generated to wrap the constructor. This is still OK on the language side, but complex in IL -- so probably wouldn't be implemented.

**Comment by mikedn** [comment]
You can't have a delegate to a constructor because the constructor itself only initializes the object, some other code needs to actually allocate the object.

I think it's a reasonable proposal. The IL is not any more complex than the one generated by x => new Y(x), actually it's identical.

**Comment by paulomorgado** [comment]
That code translates to something like:

    Func<X, Y> f = new Func<X, Y>(New.Y);
    var ys = Enumerable.Select(xs, f);

And, like @mikedn said, creating a new object is a bit more that just calling a constructor.

Calling the constructor involves another method:

    Y <>call_ctor(X x)
    {
        return new Y(x);
    }
    ...
    Func<Y> f = new Func<Y>(<>call_ctor);
    var ys = Enumerable.Select(xs, f);

Is that method the problem here, or the extra characters you have to type?

**Comment by aluanhaddad** [comment]
I have frequently encountered situations where I want to map a constructor as described by this request, and I have usually ended up creating a static factory method. 

The drawback with static factory methods however, is that there is no way to abstract over them.

This is issue is actually closely related to a request that has been voiced many times, namely to be able to express that a type has an operator as part of that type's 'interface'.

So while constructor references would be useful, I would rather see something more general, that would make factories, and many other patterns more maintainable.

**Comment by alrz** [comment]
@ashmind What about Java syntax for this: `Y::new`? also it is consistent with #5444.

**Comment by HaloFour** [comment]
IIRC you couldn't create a direct delegate to a constructor regardless of syntax.  Something like `Func<Y> f = Y::new;` would probably have to be converted to `Func<Y> f = () => new Y();`

**Comment by alrz** [comment]
@HaloFour yeah but it will be very helpful e.g. in `items.Select(Foo::new);` you won't even need to worry about constructor overloads since it will be inferred from usage.

**Comment by MadsTorgersen** [comment]
This is a good idea and has been frequently requested.

**Comment by aluanhaddad** [comment]
I've wanted this feature for a long time.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #1218](https://github.com/dotnet/csharplang/issues/1218) via [**ZenHub**](https://www.zenhub.com/)
