### ISSUE TITLE
categorize errors from compiler that can be produced live and ones that can't

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#1400]
in IDE we need to figure out and merge build and live error. without this info, it is so easy to have either duplicated errors (one from build and one from live) or staled errors.

duplicated errors can happen if a user changed location of an error while build is going on. since we can't track text changes for out-of-proc compiler (which we also has no idea what version of text file it picked up for compilation), we can't find out whether reported error is something we also have from live errors. so we will end up have 2 same errors with 2 slightly different locations reported. this also becomes stale error since the build error will not go away until next build.

another case where stale error can happen is user fixing an issue while build is going on. in that case, build error doesnt even have matching live error. so it will left out there reporting wrong thing until next build.

we need a way to see what compiler error can be produced by live and what not. user diagnostic doesnt have this problem since there is no distinction between live and build. it is compiler diagnostics unique problem.

...

found another case. if build reported errors that IDE think they can also be reported by live analysis (compiler errors), IDE will throw those errors from build away and user ends up have missing errors.

**Comment by heejaechang** [comment]
@srivatsn @AnthonyDGreen @gafter adding some people who can push this API

**Comment by shyamnamboodiripad** [comment]
This probably doesn't need new API. I think we just want well-known tag that compiler can attach to errors indicating whether or not it is live...

**Comment by heejaechang** [comment]
Either way, but I would prefer map if we can figure that out by just ID. If same ID is shared between multiple cases where one can produced by Live and one can’t. then in property since that is where info per diagnostic instance is stored.


-          Heejae

**Comment by gafter** [comment]
The compiler does not have a concept of "live". What does this mean?

**Comment by heejaechang** [comment]
@gafter here by live, I meant diagnostics that can be produced by compilation.GetDiagnostics(), and by build means all diagnostics csc or vbc can produce that are not produced by compilation.GetDiagnostics()

**Comment by gafter** [comment]
I thought we already had (or plan to have) a tag that indicated what compilation phase/API the diagnostic was produced from.

**Comment by heejaechang** [comment]
@gafter if csc/vbc can provide that info through to IDE, that would work as well.

**Comment by mavasani** [comment]
Is this a correct claim: The only category of diagnostics that csc/vbc command line builds can generate which are never part of compilation.GetDiagnostics() are diagnostics without location (e.g. parse command line argument errors, some fatal exception diagnostics, emit diagnostics)?

If so, probably for live editing scenarios in IDE, only diagnostics with locations in documents (especially the active document) are of primarily interest to user. i.e. if I have a state no-location diagnostic, it probably won't freak me out if it stays in the error list till next build.

If these two assumptions are correct, we can probably just make this as design: Live analysis is only supported for compiler diagnostics with a location. User can do a build to get up-to-date no location diagnostics.

**Comment by mavasani** [comment]
@gafter I think what HeeJae is requesting is that compiler layer maintain a set of what possible diagnostic IDs can be returned by compilation.GetDiagnostics vs full fledged command line build. This way, the compiler analyzer, which is used by the IDE to show live errors, will return only the subset of descriptors/IDs in its SupportedDiagnostics property that can be reported through compilation.GetDiagnostics.

@heejaechang is this correct analysis of what you are requesting?

**Comment by heejaechang** [comment]
@mavasani I think current implementation of CompilerAnalyzer.SupportedDiagnostics are wrong. it treats compiler and compileranalyzer same and return all diagnostics compiler can produce as supported diagnostics for compileranalyzer. and that is not true, compiler is superset of compileranalyzer, so, compileranalyzer should return those diagnostics that it actually can produce as supported diagnostics rather than return ones for compiler.

I can see why it is implemented that way, since currently there is no api to filter those one out. so it does easy way which is returning all diagnostic for compiler not compileranalyzer as supported diagnostics. due to this, all engine after this needs to deal with this special behavior.

I am asking an api to filter those out so that compiler analyzer can return right set of supported diagnostic at the beginning so that we don't need special code all around IDE to treat compiler analyzer special.

**Comment by mavasani** [comment]
@heejaechang Again I won't say analyzer is wrong, its just conservative, and we can't force any analyzer to return us exact set of descriptors it can report diagnostics, it can always return a superset of what it actually ever reports. 

I don't think we need any API here for this analyzer to return the exact set though, as the analyzer is within the compiler layer itself. We will just need the compiler team to maintain a table of what subset of diagnostics from ErrorCode.cs (and .vb) can possibly never be reported via compilation.GetDiagnostics, but could be during command line builds, and compiler analyzer can use it to return the exact set of supported descrptors. It will be a bit of maintenance overhead for compiler team though, but if they are ready to support it I have no issues with fixing the analyzer.

**Comment by heejaechang** [comment]
Returning more is not the issue issue is it returning diagnostic ids for compiler not compiler analyzer is issue since we don't run compiler analyzer from command line but compiler.

Sent from my Windows Phone
________________________________

**Comment by mavasani** [comment]
Well its easy to store this information in a table within compiler layer with current source snapshot, but I think it will be a maintenance nightmare, likely to get out-of-date soon, and cause duplicate or missing diagnostics in error list.

Below are the maintenance overheads in approach of maintaining this table:

1. For every new diagnostic added, developer has to make a conscious decision of what bucket it falls into. We can write a test to catch if new diagnostic is not mentioned in this table, but still the developer has burden of making this explicit choice.
2. If any existing diagnostic which falls under one of these buckets, is now reported at a new place in source code OR an existing report of diagnostic is deleted, such that it will change the bucket under which it falls, developer needs to know to change the table.

I personally don't feel this is a maintainable approach + I don't like IDE diagnostic de-duplication relying on what supported descriptor IDs an internal compiler analyzer reports. 
If it is possible to make a broader choice "for compiler analyzer, we always report no location diagnostics from an explicit build, and live/build de-duplication is only done for diagnostics with source location", then I think that's a more reliable approach.

**Comment by heejaechang** [comment]
Why we have compiler analyzer then? If we are need to special case in the system here and there case by case?

Sent from my Windows Phone
________________________________

**Comment by mavasani** [comment]
I thought the only reason to have it was to keep our IDE diagnostic service code cleaner. I am not sure we can ever treat compiler analyzer same as any other analyzer, due to performance requirements anyways (should execute before other analyzers, shouldn't execute SupportedDiagnostics, etc.)

This analyzer doesn't do anything special, except just invoke compiler Get*Diagnostics public APIs in its registered actions. So I think the only question here is whether compiler team wants to support the table or not and whether we are fine with missing/duplicate diagnostics showing up if this table goes out of date.

**Comment by gafter** [comment]
@mavasani 
> Is this a correct claim: The only category of diagnostics that csc/vbc command line builds can generate which are never part of compilation.GetDiagnostics() are diagnostics without location (e.g. parse command line argument errors, some fatal exception diagnostics, emit diagnostics)?

No. For example, the lowering phases can report errors pointing to source constructs when required runtime support methods cannot be found.

**Comment by gafter** [comment]
See https://github.com/dotnet/roslyn/issues/3675#issuecomment-163436367 for one possible approach to this.

**Comment by davkean** [comment]
Here's another example of this https://github.com/dotnet/roslyn/issues/26326 - CS8107 is produced at various layers in the compiler, some of which don't come through GetDiagnostics().

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We have this API with ErrorFacts.IsBuildOnlyDiagnostic.  We also intend to use this as part of upcoming work with LSP pull diagnostics documented here https://github.com/dotnet/roslyn/issues/63861.
