### ISSUE TITLE
Please add API to get parameter corresponding to an argument

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#14003]
I propose we add an API to get the parameter (symbol) corresponding to an argument (syntax) in an invocation.

``` cs
public ParameterSymbol SemanticModel.CorrespondingParameter(ArgumentSyntax argument);
```

This is related to #8805, but proposed to be available in the SemanticModel.

**Comment by gafter** [comment]
See https://github.com/Pilchie/RoslynCancellationTokenAnalyzers/blob/master/CancellationAnalyzer/CancellationAnalyzer/CancellationTokenMustBePassedExplicitlyAnalyzer.cs for an example of the pain analyzer authors go through to get it almost-but-not-really right.

/cc @Pilchie

**Comment by AlekseyTs** [comment]
IArgumentOperation already exposes corresponding parameter symbol.
