### ISSUE TITLE
Please allow overload function with generic constraints class and struct

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#14009]
Simply put, now we can't do thing like this

```C#
class A
{
    public static T Work<T>(string s) where T : class
    {
    }

    public static Nullable<T> Work<T>(string s) where T : struct
    {
    }
}
```

While generic constraint class and struct will never ambiguous. So I want to use it like overload function. Internally where T is class or struct it would implement differently

And if in the future we have `ref this` extension method I would like to do it like this

```C#
static class A
{
    public static T Work<T>(this T obj) where T : class
    {
    }

    public static ref T Work<T>(ref this T obj) where T : struct
    {
    }
}
```

**Comment by orthoxerox** [comment]
Dupe of #7459

**Comment by Thaina** [comment]
as duplicated
