### ISSUE TITLE
Retargeting causes PCL to show wrong property pages

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#14019]
Ported from DevDiv 109535
Affected Branch: D14OOB 
Affected Build: 23121.00
Affected Product Language: 

Steps to reproduce:
1. Create a new PCL targeting .NET 4.5 and Windows 8
2. Double-click on Properties to open Property Designer
3. Click Change...
4. Change targets to .NET 4.0, SL5, Windows 8

@Expected: For project to be reloaded and property designer to open with:

![image](https://cloud.githubusercontent.com/assets/3751401/18795651/6277d7b0-817a-11e6-9ef5-7483452489e1.png)

@Actual:

![image](https://cloud.githubusercontent.com/assets/3751401/18795652/6908f410-817a-11e6-88bb-043279e2f0c5.png)

**Comment by Pilchie** [comment]
Tagging @srivatsn

**Comment by srivatsn** [comment]
This issue was moved to dotnet/roslyn-project-system#1894
