### ISSUE TITLE
Cancelling a check-out prompt when retargeting portable shows 3 errors

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#14022]
Ported from DevDiv 129698

Affected Branch: 
Affected Build: 
Affected Product Language: 

Steps to reproduce:
1. Create a new portable project
2. On disk, mark the project as read-only (to simulate source control)
3. Double-click Properties, change the targets and click OK
4. When prompted with:

Affected Branch: 
Affected Build: 
Affected Product Language: 

Steps to reproduce:
1. Create a new portable project
2. On disk, mark the project as read-only (to simulate source control)
3. Double-click Properties, change the targets and click OK
4. When prompted with:

Click Cancel

@Expected: Just the first error

@Actual: 3 errors in a row:

Click Cancel

@Expected: Just the first error

@Actual: 3 errors in a row:

Affected Branch: 
Affected Build: 
Affected Product Language: 

Steps to reproduce:
1. Create a new portable project
2. On disk, mark the project as read-only (to simulate source control)
3. Double-click Properties, change the targets and click OK
4. When prompted with:

Click Cancel

@Expected: Just the first error

@Actual: 3 errors in a row:

![image](https://cloud.githubusercontent.com/assets/3751401/18795958/f1b64a3c-817b-11e6-914d-f44711b9e1a2.png)

![image](https://cloud.githubusercontent.com/assets/3751401/18795961/f4b1e5de-817b-11e6-8c1c-c674c35027ba.png)

![image](https://cloud.githubusercontent.com/assets/3751401/18795962/f7840788-817b-11e6-8abf-9fd8d3ad9a8f.png)

**Comment by CyrusNajmabadi** [comment]
Closing out as this platform.
