### ISSUE TITLE
Update current library-manager features to use new StreamingFar presenter.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14026]
Currently this is Goto-def and goto-implementation. This also includes the existing FAR work inside TypeScript to move over to our new API.  

Once we do this, we can remove the library manager code entirely.

**Comment by CyrusNajmabadi** [comment]
Tagging @vladima @paulvanbrenk .  When you guys are able to move to the new Streaming-Far stuff, let me know.  It will make it possible for us to remove a whole lot of crufty code in the VS15 timeframe.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Note: You can find the IStreamingFindReferences interface here: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/FindReferences/IFindReferencesService.cs

**Comment by Pilchie** [comment]
Is this done know?

**Comment by CyrusNajmabadi** [comment]
No.  TypeScript is still working on their end Vlad started the work and @minestarks is looking into the current state of it.

**Comment by CyrusNajmabadi** [comment]
Closing in favor of https://github.com/Microsoft/TypeScript/issues/15281
