### ISSUE TITLE
Improve Perf by calling XmlReader.ReadInnerXml rather than constructing the whole tree

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#1403]
Quoting @jasonmalinowski "We're using an XML reader to create a full tree, only to immediately get stuff back from it. And you could call XmlReader.ReadInnerXml which would just give you the string you want directly and avoid creating a huge pile of garbage."

https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Utilities/Documentation/XmlDocumentationProvider.cs#L43

[Discussion](https://github.com/dotnet/roslyn/pull/1399#discussion_r26805432)

**Comment by smerrell** [comment]
I was digging through help wanted tags to find something to work on and this looks to have been completed by 1bf6bfc2b23d2934f3a124b9180f703cd3a72fe6

**Comment by Therzok** [comment]
Yeah, I think that this can be closed ?

The sample I wss trying on (Xamari.Android)  has huge dml comments files

So if it"s about of that specific target part, it used to allocate /4 gin in swooo, llp
