### ISSUE TITLE
ETA tests failing due to missing libraries

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#14041]
Multiple separate PR's are failing ETA tests due to missing libraries..  Look like it might have something to do with runtime version.

http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/3978/console

10:19:21 C:\Program Files (x86)\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(140,5): error : Your project is not referencing the ".NETPortable,Version=v4.5,Profile=Profile7" framework. Add a reference to ".NETPortable,Version=v4.5,Profile=Profile7" in the "frameworks" section of your project.json, and then re-run NuGet restore. [d:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\RoslynTestAnalyzers\RoslynTestAnalyzers.csproj]
10:19:21 
d:\j\workspace\windows_eta_o---d880a2eb\Open\Binaries\Obj\Immutable\Debug\GeneratedAssemblyInfo_42.42.42.42.cs(6,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [d:\j\workspace\windows_eta_o---d880a2eb\Open\src\Dependencies\Immutable\Immutable.csproj]
10:19:21 d:\j\workspace\windows_eta_o---d880a2eb\Open\Binaries\Obj\Immutable\Debug\GeneratedAssemblyInfo_42.42.42.42.cs(7,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [d:\j\workspace\windows_eta_o---d880a2eb\Open\src\Dependencies\Immutable\Immutable.csproj]
10:19:21 d:\j\workspace\windows_eta_o---d880a2eb\Open\Binaries\Obj\Immutable\Debug\GeneratedAssemblyInfo_42.42.42.42.cs(8,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [d:\j\workspace\windows_eta_o---d880a2eb\Open\src\Dependencies\Immutable\Immutable.csproj]

**Comment by tannergooding** [comment]
Tagging @agocke

**Comment by jasonmalinowski** [comment]
@agocke fixed this a few days ago.
