### ISSUE TITLE
Preselect is always selecting 'ContinueWith' on a task, interfering with tring to call 'ConfigureAwait'.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14056]
See gif below.  Essentially, no matter what, completion always selects .ContinueWith after a task.  This broke muscle memory for me because i normally type ```<dot>Con<tab>(false)``` to get ```.ConfigureAwait(false)```.  However, *every* time, no matter what completion matches against .ContinueWith.

1. I have no idea why it would match ContinueWith.  'Con' is an exact prefix match against ConfigureAwait.
2. I have no idea why the MRU list isn't working.  

![preselect](https://cloud.githubusercontent.com/assets/4564579/18811868/ed526cd8-8274-11e6-9f15-b5ac38e9d526.gif)

**Comment by CyrusNajmabadi** [comment]
@rchande do you know what's happened here?  Is this something related to target typing?

**Comment by AdamSpeight2008** [comment]
Does C A Tab work any better?

**Comment by CyrusNajmabadi** [comment]
CA is not what i'm tying.  I'm typing ```Con<tab>```.  That needs to both preselect and commit to ConfigureAwait

**Comment by CyrusNajmabadi** [comment]
This is not about workarounds.  This is about having the correct behavior for these characters.

**Comment by AdamSpeight2008** [comment]
Wouldn't `ContinueWith` be the more common usage?

**Comment by CyrusNajmabadi** [comment]
As i already mentioned, this is happening despite me actually using and committing ConfigureAwait, thus breaking the actual MRU we have.    'Common' isn't relevant here.

**Comment by Pilchie** [comment]
My guess is that this is target typing somehow.  The fact that `ContinueWith` returns a task directly, unlike `ConfigureAwait` is confusing it.

**Comment by miloush** [comment]
Not entirely dissimilar to #14064

**Comment by CyrusNajmabadi** [comment]
> My guess is that this is target typing somehow

Yup.  I debugged through and htat's exactly what's happening.  Specifically, I've written the code ```await x.```

The type inferrer correctly says "hey... 'Task' is legal here".  i.e. if you had "await task x.y()" and did 'generate method' on 'y()' we'd give it the Task type.  However, completion then says "ContinueWith is better than all the others because it returns a Task".

We may be able to address this by having the typeinferrer also return ConfiguredTaskAwaitable as something that can be inferred in this context.  Note that we'll want that type at the end of the list of types it returns so that features like GenerateMethod and whatnot will pick the more sensible "Task" type.

**Comment by rchande** [comment]
@CyrusNajmabadi Looks like we now consider MRU against any matches returned by filtering. Target typing makes us conclude that there's exactly one "best match" of `ContinueWith` if you've only typed `con`. Even if `ConfigureAwait` is in the MRU list, MRU will never pick it with `con` typed since its not returned by filtering.

It's sort of unfortunate that target typing totally breaks MRU...

**Comment by rchande** [comment]
I suppose we could first put the "best match" item in the array returned by FilterItems followed by items that got kicked out by the ultimate best match and let MRU deal with it (by either picking the first item because there was nothing applicable in the MRU or by choosing an item that actually appeared in the MRU)

**Comment by CyrusNajmabadi** [comment]
I think my problem is that target typing is too aggressive.  Especially since we only have a weak heuristic based system for determining what the target type is.  Given that, i think target-type selection should be the *last* thing that system kicks in when everything else has resulted in multiple possibilities.  i.e. if you have an exact match, then target typing shouldn't be able to override.  if the MRU wants us to preselect something, then target typing should likely take a back seat.

However, if all of the above result in multiple possible items to select, *then* we could fall back to target typing.  What do you think?

**Comment by rchande** [comment]
Yeah, I think I agree--I'll start working on that and hopefully fix all of these issues simultaneously.

**Comment by CyrusNajmabadi** [comment]
Sounds good!

**Comment by rchande** [comment]
Please verify.
