### ISSUE TITLE
Files in "Packages" folder are ignored by VS/compiler

### ISSUE THREAD

**Issue by pebezo** [dotnet/roslyn#14053]
**Version Used**: VS2015 Update 3 (14.0.25431.01)

**Steps to Reproduce**:
1. Create a blank console project. The name doesn't matter, but let's use PkTest for this example.
2. Create a folder called "Packages" in the root of PkTest project.
3. Create a simple class in the this folder, for example Foo.cs. Type something in this file make it invalid. For example type "abcdef" in the body of the class.
4. Build/Rebuild the solution.

**Expected Behavior**:

VS should show an error message where we typed "abcdef".

**Actual Behavior**:

VS says that everything compiled and that nothing's wrong.

There's something about name the folder "Packages". If the name of the folder is anything else it works fine. (I hope this is the right repo).

**Comment by mavasani** [comment]
I am unable to repro this on VS2017 RC. Not sure why this was tagged with Area-Analyzers as the issue was reported for building the solution.
