### ISSUE TITLE
[IDE Feature Request?] Differ language parts in IDE Editor by using different color

### ISSUE THREAD

**Issue by OlivChu** [dotnet/roslyn#14065]
Hi Roslyn Team, 

Last several month,I've been using **Supercharger** extension tool for daily job [](http://supercharger.tools/) ,I'm rely on one of its feature called "Name Emphasis", it can differ your code from types,constructors,methods,properties by different format using different color.

Examples from Supercharger tools extension:
![image](https://cloud.githubusercontent.com/assets/12636161/18826046/fd19e850-83fd-11e6-8a35-f14656180803.png)

So my question is that can we add a native support for this kind of feature in IDE editor rather than using such an extension? Or has the IDE has supported that already (through some hiding options)?

**Comment by 0xd4d** [comment]
See #3976

**Comment by jasonmalinowski** [comment]
No, @OlivChu there isn't built in support at this point. #3976 is tracking adding such a feature.

**Comment by OlivChu** [comment]
@jasonmalinowski OK, Thanks a lot.
