### ISSUE TITLE
Support configuring multiple diagnostics at a time in Solution Explorer

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#1406]
Currently, you can only Right Click a diagnostic in Solution Explorer and set the severity if you select one diagnostic at a time. It would be very helpful if you could select multiple diagnostics at a time for this operation.

Solution Explorer presents diagnostics with a very different organizational structure than the rule editor. If a user wants to configure all rules provided by a particular analyzer library, regardless of the category or ID, Solution Explorer is the most straightforward approach.

**Note:** I just realized that the rule set editor allows you to group by **Analyzer ID**, which actually groups the diagnostics by *assembly*. It would still be nice to edit the selection in Solution Explorer.

**Comment by srivatsn** [comment]
I believe @tmeschter has already implemented this.

**Comment by tmeschter** [comment]
@sharwell @srivatsn Yes, you can select multiple diagnostics and set them to the same severity all at once.

**Comment by srivatsn** [comment]
Closing since this has now been implemented.
