### ISSUE TITLE
Allow implicitly typed variable(var) in methods optional paramters

### ISSUE THREAD

**Issue by imranbaloch** [dotnet/roslyn#14066]
Let's say we have this method,

```
public void SomeMethod(string str = "", int id = -1)
{
}
```

It will be great if we have something like,

```
public void SomeMethod(var str = "", var id = -1)
{
}
```

Due to optional parameter, compiler can easily determines the type. Just a suggestion.

**Comment by DavidArno** [comment]
Um, how do you propose that the compiler work out that `var str = null` is  `string`, as opposed to any other reference type?

**Comment by dsaf** [comment]
> It will be great if we have something like...

Why? It's not likely to be something like ```Dictionary<Dictionary<string, Tuple<string, decimal>>>``` due to type limitation. The type names are likely to be quite short. Even your example only saves 3 characters.

**Comment by alrz** [comment]
As @DavidArno said, for all default values (null, zero and other structs) you will require to specify the type anyways. I'd prefer #7737 as it helps with consistency, conciseness and DRY.
```cs
public void SomeMethod(string str = default, int id = default)
```
As for non-default values like `-1` I don't think that it need to be different as it doesn't even save a single keystroke.

**Comment by imranbaloch** [comment]
@DavidArno oh sorry I mean, 

`string str = ""`. 

What I mean is that when we can do

`var s = "";`

why not this,

`someMethod(var s = "")`

**Comment by DavidArno** [comment]
> why not this,
`someMethod(var s = "")`

You are asking the wrong person, as I'm no fan of default/optional parameters and would always go for the following instead:
````cs
someMethod() => ...
someMethodWithString(string s) => ...
````

**Comment by gafter** [comment]
Closing as this doesn't appear to have much support.  Having said that, if you want to continue to pursue this discussion, please open a new thread in `csharplang`.
