### ISSUE TITLE
Error CS1703 Multiple assemblies with equivalent identity have been imported

### ISSUE THREAD

**Issue by routbiplab** [dotnet/roslyn#14060]
**Version Used**:  MS Visual Studio CE 2015 with XAMARIN

**Steps to Reproduce**:
1. When I am trying to build any project I get this error.

> Error CS1703 Multiple assemblies with equivalent identity have been imported: 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\mscorlib.dll' and 'C:\windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll'. Remove one of the duplicate references. DemoMvvm.Droid c:\users\biplab rout\documents\visual studio 2015\Projects\DemoMvvm\DemoMvvm\DemoMvvm.Droid\CSC

**Comment by jasonmalinowski** [comment]
@routbiplab: can you share the version of the Xamarin tools and the full version of Visual Studio you are using? Also, does this happen on literally _any_ project, including things like regular console applications?

**Comment by jasonmalinowski** [comment]
@routbiplab Any chance you could get some additional information for us?
