### ISSUE TITLE
FuncEval error with immutable collections

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1407]
Steps:

 1. Clone https://github.com/SLaks/DroidMaster/tree/39493a090c0e422b54ad2cf28068750078c1f94f at that commit
 2. Set Break on errors (except File Not Found0)
 2. Run
 3. Click Open Script Editor
 3. When it breaks on the composition failure, opne any ExportProvider frame, then expand non-empty immutable collection within `this`.

Error:

    Error	Evaluation of method System.Collections.Immutable.ImmutableHashSetDebuggerProxy`1[Microsoft.VisualStudio.Composition.RuntimeComposition+RuntimePart].get_Contents() requires use of the static field System.Collections.Immutable.AllocFreeConcurrentStack`1[System.Collections.Immutable.SecurePooledObject`1[System.Collections.Generic.Stack`1[System.Collections.Immutable.RefAsValueType`1[System.Collections.Immutable.SortedInt32KeyNode`1[System.Collections.Immutable.ImmutableHashSet`1+HashBucket[Microsoft.VisualStudio.Composition.RuntimeComposition+RuntimePart]]]]]].stack, which is not available in this context.	

This happens on one of my machines, but not a different one.
I have a memory dump on OneDrive.

**Comment by SLaks** [comment]
For those who are curious, the type involved is

```C#
System.Collections.Immutable.AllocFreeConcurrentStack<
	System.Collections.Immutable.SecurePooledObject<
		System.Collections.Generic.Stack<
			System.Collections.Immutable.RefAsValueType<
				System.Collections.Immutable.SortedInt32KeyNode<
					System.Collections.Immutable.ImmutableHashSet+HashBucket<
						Microsoft.VisualStudio.Composition.RuntimeComposition+RuntimePart
					>
				>
			>
		>
	>
>
```

**Comment by KevinH-MS** [comment]
@SLaks I'm having some trouble reproducing this issue.  I get a:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Services.AsyncQueryService.AsyncServiceProvider..ctor(IServiceProvider serviceProvider, IServiceProvider oleServiceProvider)
```

calling VSServiceProvider.Initialize()...

I'll keep trying some things, but let me know if you have any ideas on how to get past this.

Thanks

**Comment by KevinH-MS** [comment]
@SLaks I was able to get to the composition failure by commenting out that line...

Next question--can you clarify what you mean by an "ExportProvider frame"?  (what method in the CallStack Window, specifically)

Also, can you provide the exact expression ("this...") that you're trying to evaluate?  (these types have **a lot** of members :wink:)

Thanks!

**Comment by SLaks** [comment]
I don't get any errors form `Initialize()` on 14.0.22609.0.
However, you're right; that shouldn't affect composition at all.

I mean any method on `ExportProvider`; since I'm inspecting `this`, it doesn't matter which.
I just repro'd on the top frame, `Microsoft.VisualStudio.Composition.ExportProvider.GetExports(Microsoft.VisualStudio.Composition.ImportDefinition importDefinition)`.  It happens for literally every immutable collection or hashset.

**Comment by KevinH-MS** [comment]
I see.  I'll try to get that build installed on a VM and stop in that method (on my build of VS, the Exception is thrown in an entirely different method).

In the meantime, if you could send a link to the dump on OneDrive, that might be quicker.  My e-mail is kevinh@microsoft.com.

**Comment by SLaks** [comment]
Shared.
Which method the exception is thrown from ought to not matter; the issue happened (on that machine) in any call frame on `ExportProvider`.

PS: Why is your Live account's displayname `.`?

**Comment by KevinH-MS** [comment]
Thanks!  I spun up a VM with your build of VS, and I was able to get into that method, but here's what I'm seeing:
![capture](https://cloud.githubusercontent.com/assets/6464209/7357051/13bd1c18-ece1-11e4-844e-4f7d1462aed0.PNG)
Could you try to "Debug > Save Dump As..." inside the instance of VS that's having the problem (capture dump of the "debuggee" process)?  It seems to be something related to the machine state (hopefully, I might be able to piece it together between the two dumps).

**Comment by KevinH-MS** [comment]
Thanks for sharing the dump of the debuggee.  I was able to repro the issue with that.  The error appears to be generated by Microsoft.VisualStudio.VIL.Host.dll.  I've notified the team that owns that library, and I'll post back here when I get a resolution.

**Comment by pnelsonmsft** [comment]
@SLaks, I improved ability to inspect these Immutable collections.  You should see improvements in the next release of Visual Studio 2015.  However, there will always be cases where we can't read the value of a static field.  I'm open to suggestions for improving the error message in this case.

**Comment by KevinH-MS** [comment]
I believe the original issue should be mostly addressed with VS 2015 RTM.  If things still don't look *good*, please re-activate with updated details.
