### ISSUE TITLE
OOP Workspace throws a `ObjectDisposedException` when attempting to call `ServiceHubRemoteHostClient.CreateAsync` if OOP is disabled

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#14074]
```
System.ObjectDisposedException: The semaphore has been disposed.
   at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
   at StreamJsonRpc.DelimitedMessageHandler.<WriteAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__56`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.Remote.ServiceHubRemoteHostClient.<CreateAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at FQN.<EmitAsync>d__0.MoveNext()
```

**Comment by tannergooding** [comment]
FYI. @ManishJayaswal, @KevinH-MS, @heejaechang

**Comment by heejaechang** [comment]
@tannergooding how did you get IServiceHubRemoteHostClient when OOP is disabled? did you cache it?

**Comment by heejaechang** [comment]
I am not sure how you got RemoteHostClient since if OOP is disabled, you won't be able to get one from IRemostHostClientService

**Comment by tannergooding** [comment]
@KevinH-MS to answer the question

**Comment by KevinH-MS** [comment]
We call:
```
var remoteHostClientFactory = _workspace.Services.GetService<IRemoteHostClientFactory>();
if (remoteHostClientFactory != null)
{
    remoteHostClient = await remoteHostClientFactory.CreateAsync(_workspace, cancellationToken).ConfigureAwait(false);
}
```

It appears that the IRemoteHostClientFactory is non-null, but CreateService throws an Exception.  If we should be calling a different service, let us know.

**Comment by heejaechang** [comment]
IRemoteHostClientFactory is not something user is supposed to use.

IRemoteHostClientService is one should use.

http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Remote/IRemoteHostClientService.cs,c636e67ba354a34c,references

**Comment by KevinH-MS** [comment]
I tried to change to use IRemoteHostClientService, but GetRemoteHostClientAsync is always returning `null`.  I'm using the Roslyn bits from the dev15-rc branch.  Is there something explicit that needs to be done to turn on OOP if we're calling through IRemoteHostClientService?

**Comment by heejaechang** [comment]
@KevinH-MS only thing you need should be remotehost option.

**Comment by KevinH-MS** [comment]
Isn't that supposed to get set automatically if our package is installed?

**Comment by heejaechang** [comment]
I believe it should. but can you check?

**Comment by KevinH-MS** [comment]
Where do the options get set?  I just see this in RemoteHostClientService.cs:
```
public void Enable()
            {
                lock (_gate)
                {
                    if (_instanceTask != null)
                    {
                        // already enabled
                        return;
                    }

                    // We enable the remote host if either RemoteHostTest or RemoteHost are on.
                    if (!_workspace.Options.GetOption(RemoteHostOptions.RemoteHostTest) &&
                        !_workspace.Options.GetOption(RemoteHostOptions.RemoteHost))
                    {
                        // not turned on
                        return;
                    }
```

**Comment by heejaechang** [comment]
it is option serializer that gets initial value. option serializer has changed between preview 5 and master. which branch are you using? in master, old method might not work. and since in master we are turning on remote host by default (I just checked in change), you don't need regkey set on package installation.

**Comment by KevinH-MS** [comment]
I'm using the dev15-rc branch.

**Comment by heejaechang** [comment]
ya, reg key won't work for rc since option serialization has changed.

**Comment by heejaechang** [comment]
@KevinH-MS probably we need to debug it together to see why you can't just use GetRemoteHostClient service

**Comment by heejaechang** [comment]
I believe this is fixed.
