### ISSUE TITLE
[Bug] Mixing collection Initializer and indexer Initializer

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/roslyn#14071]
**Version Used**: 

Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

**Steps to Reproduce**:

Create a default console application and try to compile a next code

```cs
using System.Collections.Generic;

class Program
{
  static void Main() {
    var d1 = new Dictionary<string, int> {
      { "one", 1 }, // OK
    };

    var d2 = new Dictionary<string, int> {
      ["two"] = 2,  // OK
    };

    var d3 = new Dictionary<string, int> {
      { "one", 1 }, // <-- Program.cs(15,7,15,19): error CS0747: Invalid initializer member declarator
      ["two"] = 2,
    };
  }
}
```

**Expected Behavior**:

Code should be compiled without errors or warnings.

**Actual Behavior**:

The compiler error occured: CS0747: Invalid initializer member declarator

**Comment by gafter** [comment]
Looking at [the language specification](https://github.com/ljw1004/csharpspec/blob/gh-pages/expressions.md#object-creation-expressions), I can see that `d1` is being initialized with a *collection-initializer*, `d2` is being initialized with an *object-initializer*, but I can't figure out which language construct you think `d3` is initialized with.

**Comment by ViIvanov** [comment]
@gafter Thanks for link to the lang spec, now I see that it is not a bug.
I was thinking, I can mix a collection initializer and indexer initializer. Issue can be closed.
