### ISSUE TITLE
Type preselection takes priority over exact case matches in C#

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#14085]
**Version Used**: 20160926.07

**Steps to Reproduce**:

1. Create a new console application.
2. Add `using System.IO;` to the top to pull in the namespace
3. Start typing `string path = Path` as if you were going to write something like `Path.Combine`

**Expected Behavior**: The Path class is selected since that's exactly what I typed.

**Actual Behavior**: The path variable is selected. Short of up/down arrow or dismissing completion, there's no way to get it select Path.

**Comment by miloush** [comment]
That looks like much easier repro of #14064.
Also #14056 might be relevant.

**Comment by rchande** [comment]
Please verify.
