### ISSUE TITLE
Indent Guides tracking spans become incorrect after edits

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#14087]
**Version Used**: Preview 25725.00

![outliningtrackingspans](https://cloud.githubusercontent.com/assets/235241/18854207/b758b91c-83fe-11e6-8119-81adc219babc.gif)

**Comment by dpoeschl** [comment]
FYI @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Thanks!
