### ISSUE TITLE
@dotnet-bot test perf_correctness_prtest please triggers Performance Test Run

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#14092]
In a PR, if I comment

```none
@dotnet-bot test perf_correctness_prtest please
```

then **Performance Test Run** is triggered in addition to the requested test.

**Comment by gafter** [comment]
See, for example, #13955 where this most recently occurred.

**Comment by jasonmalinowski** [comment]
@TyOverby, any idea what is going on here?
