### ISSUE TITLE
Jenkins failing to build

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14090]
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/4027/

CreatePkgDef : error : ProvideCodeBaseAttribute: Could not load specified assembly: '' reason: Could not load file or assembly 'file:///D:\j\workspace\windows_debug---09a07fba\Binaries\Debug\System.AppContext.dll' or one of its dependencies. The system cannot find the file specified. [D:\j\workspace\windows_debug---09a07fba\src\VisualStudio\Setup\VisualStudioSetup.csproj]
Indication 2

**Comment by jasonmalinowski** [comment]
@mattwar Can you get out the targeted fix for this ASAP?

**Comment by natidea** [comment]
@mattwar Can we close this issue now?

**Comment by mattwar** [comment]
Not certain that this fix alone fixes the problem.  If we don't see this kind of error pop up this week, then I think we can close it.

**Comment by jaredpar** [comment]
I've verified this is a dupe of the primary build race condition #13980
