### ISSUE TITLE
Indent Guides don't scale with the editor

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14099]
**Version Used**:  VS Preview 5 2575.00

**Steps to Reproduce**: 

1. Zoom Editor to 200%
2. Hover over any brace

**Expected Behavior**:
Indent guides scale with editor

**Actual Behavior**:
![hover](https://cloud.githubusercontent.com/assets/9797472/18881764/75951212-8491-11e6-9834-60e4d92e9c46.png)

**Comment by jasonmalinowski** [comment]
@jmarolf Should this be filed against the core editor?

**Comment by jmarolf** [comment]
Opened https://devdiv.visualstudio.com/DevDiv/_workitems?id=271431
