### ISSUE TITLE
Analyzer for analyzer references missing when creating projects with roslyn sdk project templates

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#1409]
When I create analyzer with code fix projects using roslyn sdk project templates, I am seeing that the 'analyzer for analyzer' references are missing under References -> Analyzers. 

![capture](https://cloud.githubusercontent.com/assets/10579684/6745779/96d3ff94-ce79-11e4-802e-f2f31f55fe82.PNG)

I can see that that the dlls are present on disk under packages folder - but the references seem to be missing in the project...

![capture2](https://cloud.githubusercontent.com/assets/10579684/6745824/7283f7a6-ce7a-11e4-8a3f-da4df15e4307.PNG)

**Comment by srivatsn** [comment]
I think this is the issue I fixed yesterday where the install ps1 script had a -Include instead of -Filter. Can you try the latest package?

**Comment by shyamnamboodiripad** [comment]
This could be it. I haven't checked in a new build yet - but manually changing -Filter to -Include seemed to fix the issue for analyzers that I created (i.e. I changed what the template spit out). I wonder if there are 2 separate issues here - 1 fix the templates to use -Filter and 2 fix the shipping analyzers (such as above analyzers for analyzers, the System.Runtime analyzers etc.)

**Comment by shyamnamboodiripad** [comment]
Verified this does not repro in newer builds.
