### ISSUE TITLE
"Tuple must contain at least two elements" error appears twice

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#14091]
**Version Used**: preview 25725

![image](https://cloud.githubusercontent.com/assets/235241/18855146/621b139e-8405-11e6-8ad8-3cc86e00ff60.png)

Why does the error message appear twice?

**Comment by dpoeschl** [comment]
The error shows twice in the error list as well.

**Comment by jcouv** [comment]
Fixed by #15969
