### ISSUE TITLE
Proposal: Extension method support in scripting

### ISSUE THREAD

**Issue by glennblock** [dotnet/roslyn#141]
## Problem
Developers using C# scripting are unable to define extension methods in script. I believe this is due to the fact that the script code is wrapped in the submission, and you cannot have extensions on nested static classes. Also Roslyn does not allow using "this"

For example, a developer cannot do this within a script.

```csharp
public static class StringExtensions() {
  public static string DoSomething(this string text ) {
    ...
  }   
}
```

Now extension methods can be defined on dlls and loaded into the scripting context, however this requires a developer to create a full blown C# project / dll. It would offer a smoother scripting experience if these extension methods could be defined within a top-level script, or a child script that is loaded with `#load`.

## Proposed solutions
Both solutions would require allowing usage of the `this` pointer in script, OR some equivalent. If `this` is enabled, it could be scoped to only work for extension methods if there is concern about its usage elsewhere.

### A. Support extension methods on nested classes.
If extension methods are enabled on nested static classes, then one could define a static class in script with extensions and they would be picked up. This would make the above example work, though I imagine it will be more work to allow this at the compiler level.

### B. Lift the class at compile time
Provide a new `#extensions` directive which can be put on a class to indicate that this class has extension methods. At compile time the class is lifted out of the submission so that the extension methods can be resolved. 

Here is an example of how this would look from an authoring perspective

```csharp
#extensions
public static class StringExtensions() {
  public static string DoSomething(this string text ) {
    ...
  }   
}
```

**Comment by glennblock** [comment]
Looking at this more `#extensions` is probably not required, as if you detect a static class with methods that have a this modifier, you could automatically life out the class in B.

**Comment by tmat** [comment]
My opinion is that we should allow to define extension methods in any class in C# proper.

**Comment by glennblock** [comment]
@tmat sounds good to me!

**Comment by dfkeenan** [comment]
@tmat That would be great.  A number of times I wished I could have done something like:

```c#
public abstract SomeClass
{
    //.....
   protected static void SomeExtension(this object obj)
   {
       //.....
   }
    //.....
}
```

**Comment by daveaglick** [comment]
Has there been any movement on this in the nightlies? Not the suggestion to change the language (though that would be awesome too), just interested in getting extension method support in scripts for now... Has it been discussed how this will implemented within the team yet?

I'm not particularly fond of introducing magic directives that are specific to the scripting compiler. Lifting any class that contains extensions seems like a more general approach to me.

Another thought I had was to create overloads and/or fluent extensions to the scripting APIs that allow passing in additional script code that goes outside the submission class. Then you could put whatever you needed in there, including static classes with extension methods. In cases like ScriptCS where you want the whole thing to be captured in a single text file or string, the Roslyn scripting consumers would be responsible for implementing the functionality however it's appropriate for them (with the `#extensions` directive, using a delimiter between global and nested code, etc.).

```
string globalCode = @"
    public static class MyExtensions
    {
        //...
    }
";

string scriptCode = @"
    //...
";

ScriptOptions options = new ScriptOptions()
    .WithReferences(assemblies)
    .WithNamespaces(namespaces)
    .WithGlobalCode(globalCode);
CSharpScript.Eval(scriptCode, options);
```

**Comment by cston** [comment]
In the master branch, top-level extension methods are now supported in C# scripts. See https://github.com/dotnet/roslyn/pull/3472

**Comment by daveaglick** [comment]
Great, thanks. What timing.

So if I'm reading the PR and tests correctly, this works if you define your static extension methods "inline" with the rest of the script code. Putting them in a static class within the script still would not work, correct?

**Comment by cston** [comment]
That is correct, that PR adds support for top-level extension methods only, it does not allow extension methods within nested classes.

**Comment by glennblock** [comment]
Cool, I did not know this (or must not have seen that it was closed). Great news!

**Comment by glennblock** [comment]
:+1:
