### ISSUE TITLE
Missing bound node for tuple decomposition declaration

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#14106]
We are missing a bound node for a decomposition declaration. Consequently, it cannot be distinguished (in the bound nodes) from a decomposition assignment statement.

This is related to #13270 and #14072.

**Comment by gafter** [comment]
@jcouv I believe this is either fixed or on the way to being fixed. If so, please close. If not please re-assign to me.

**Comment by jcouv** [comment]
Yes, this is now fixed. Deconstructions get bound into a bound deconstruction assignment operator with a bound tuple expression (for the left) and a bound expression (for the right).
The bound tuple expression will have bound nodes that are either some bound LValue (something that can be assigned to) or bound local (marked as a declaration).
