### ISSUE TITLE
Implement command line switch that prints the git sha of the built version of roslyn

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#14109]
Especially for nightly builds, having a git commit that roslyn team members can easily check out and repro without hassle would aid in debugging.

**Comment by TyOverby** [comment]
cc @gafter

**Comment by gafter** [comment]
@TyOverby If this is intended to also impact the MSBuild task, please specify how.

**Comment by gafter** [comment]
Adding to milestone 2.1 to be considered and triaged for a future release.

**Comment by jcouv** [comment]
@jaredpar asked what is the `gcc` behavior for comparison:
```
> gcc --version
gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by TyOverby** [comment]
rustc behavior

```
> rustc -V
rustc 1.17.0-nightly (0f34b532a 2017-02-21)
```

**Comment by tmat** [comment]
The sha is stored in AssemblyInformationVersion so we can print out that version string with ```csc /version```.

**Comment by jaredpar** [comment]
The rust model seems pretty reasonable here by attaching it as a part of the version number scheme.

**Comment by jcouv** [comment]
Here's what I get on an official build with FileVersionInfo.GetVersionInfo(filePath): 

![image](https://cloud.githubusercontent.com/assets/12466233/23540131/5b3ed096-ff94-11e6-81fd-96fea55590c5.png)


The first part of the `ProductVersion` seems to come from `$(NuGetPerBuildPreReleaseVersion)` in `GenerateAssemblyInfo.targets`. One solution is to parse out the portion after "Commit Hash:".

**Comment by jcouv** [comment]
Logo and version were updated to include a shortened SHA:
```
Microsoft (R) Visual C# Compiler version 2.0.0.61427 (8ecba4f6)
Microsoft (R) Visual C# Compiler version 42.42.42.42424 (<developer build>)

Microsoft (R) Visual Basic Compiler version 2.0.0.61427 (8ecba4f6)
Microsoft (R) Visual Basic Compiler version 42.42.42.42424 (<developer build>)
```
