### ISSUE TITLE
Have CodeLens Referenes Window Use FAR instead

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14102]
Now that we have the new FAR window it seems redundant to have to maintain a codelens window when they show the same information
![codelens](https://cloud.githubusercontent.com/assets/9797472/18883475/3168aaa2-8498-11e6-9699-0ce983004601.png)

![far](https://cloud.githubusercontent.com/assets/9797472/18883474/2e8b3f5c-8498-11e6-9b37-3bf90361f5d4.png)

**Comment by TobiasSekan** [comment]
Can you not easy show the FAR window instead of the (minimal) CodeLens window?

**Comment by CyrusNajmabadi** [comment]
@jmarolf can you move this to platform? we don't own the CodeLens UI.

**Comment by jmarolf** [comment]
moved to https://developercommunity.visualstudio.com/t/Have-CodeLens-References-Window-Use-Find/10188408
