### ISSUE TITLE
No api to get project errors.

### ISSUE THREAD

**Issue by marler8997** [dotnet/roslyn#14103]
There's no API to get errors/warnings with project files (I believe this is also the case with solution files).

The SyntaxTree and SemanticModel have a GetDiagnostics method that allows an application to retrieve errors/warnings with the syntax/semantics respectively.  I suggest the same "GetDiagnostics" api be used for getting errors/warnings about solutions and projects.

Original Question About This Issue Here:
http://stackoverflow.com/questions/39644051/roslyn-ignores-missing-assembly-references-when-loading-project?noredirect=1#comment66688804_39644051

**Comment by CyrusNajmabadi** [comment]
Needs to go through API proposal on this.

**Comment by sharwell** [comment]
@CyrusNajmabadi The issue is requesting a `GetDiagnostics` method for `Project` and/or `Solution`.

**Comment by CyrusNajmabadi** [comment]
@sharwell Understood.  Still needs to go through API process for that to happen.

**Comment by CyrusNajmabadi** [comment]
Clsoing out.  Needs to go through API review process.
