### ISSUE TITLE
White over blue is not as obvious as black on white in intellisense filtering

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14100]
**Version Used**: VS Preview 5 2575.00

**Steps to Reproduce**:

1. Bring up intellisense

**Expected Behavior**:
Selected text to be easy to see why it was chosen

**Actual Behavior**:
Looks like `inter` should be more bolded on selection.  White over blue is not as obvious as black on white
![hover](https://cloud.githubusercontent.com/assets/9797472/18882016/63295240-8492-11e6-9bf9-cd864e956fb6.png)

**Comment by 0xd4d** [comment]
Background color could be changed (see Ctrl+F in editor for a color you're already using)

Or foreground color could be changed instead of bolding the text.

It's easier to see an added color instead of just bolding the text (IMHO).

**Comment by jasonmalinowski** [comment]
@jmarolf I believe this is feedback for the core editor team. Can you move the bug to them?

**Comment by jmarolf** [comment]
Opened https://devdiv.visualstudio.com/DevDiv/_workitems?id=271430
