### ISSUE TITLE
Local functions do not respect newline formatting options

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14119]
**Steps to Reproduce**:
1. Go to Options -> Text Editor -> C# -> Code Style -> Formatting -> New Lines
2.  Uncheck all "New line options for braces"

![image](https://cloud.githubusercontent.com/assets/9797472/18894505/22b663b6-84c8-11e6-8f44-034369577c0e.png)
3. Write a local function
4. Format the document (default shortcut is Ctrl +K, D )

**Expected Behavior**:

``` C#
class A {
    static void M() {
        void Local() {
        }
    }
}
```

**Actual Behavior**:

``` C#
class A {
    static void M() {
        void Local() 
        {
        }
    }
}
```

**Comment by jcouv** [comment]
This doesn't seem to meet the current RTW bar. Moving out.

**Comment by SLaks** [comment]
Why not?

This makes local functions look very jarring in codebases that put braces on the same line.
I'm avoiding this feature myself because of this.

**Comment by alrz** [comment]
@jcouv I'd be nice if we could know how these issues are prioritized across milestones.

**Comment by jcouv** [comment]
@SLaks @alrz We only have couple of weeks until the compiler is locked for RTM and about 80 bugs for the compiler alone (plus many relative to IDE which may involve us too), so hard prioritization will be applied at this point. Rough guideline for prioritization: crashes, perf issues, major feature issue, now-or-never language decisions.

This formatting issue ranks lower than those. I understand that's painful. If we end up having bandwidth, I'll try to bring this back in (I took a quick look and `NewLineForOpenBracesNonDefault` seems to be a good test to mimic or update).

**Comment by jcouv** [comment]
Thanks @SLaks for the PR. After the PR is reviewed and approved, I'll try to push it though shiproom, which enforces the RTM bar and evaluates risks/benefits trade-offs.

**Comment by jcouv** [comment]
@Pilchie Assigned to you since this is an IDE-only change. I'll let you drive through shiproom. Thanks

**Comment by Pilchie** [comment]
Moving to 2.1 as this didn't meet the bar this morning.

**Comment by 0xCA** [comment]
Just updated VisualStudio.
Still not fixed.

**Comment by Pilchie** [comment]
@0xCA unfortunately, this fix won't be in a release for a little while, as the frequent updates like the one that went out yesterday only contain fixes for the most significant issues (crashes/hangs/dataloss/etc).
