### ISSUE TITLE
Out Variable tests for Script should cover statements that currently aren't covered by GlobalCode_* unit-tests 

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#14113]
Basically GlobalCode_\* unit-tests should cover all the different statements that are covered by Scope_\* unit-tests

**Comment by gafter** [comment]
This is a special case of the more general issue #14146 for expression variables.

**Comment by AlekseyTs** [comment]
This issue is for Out Variable declarations.
