### ISSUE TITLE
Is it possible to provide formatting options with the project configuration?

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#1411]
I was looking into the possibility of providing formatting options as part of a project configuration. The [`IOptionSerializer`](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Options/Providers/IOptionSerializer.cs) interface stood out, but it doesn't seem like it'd be usable for the purpose of overriding options that come down from the environment (e.g. settings within the IDE).

Is there any mechanism in place that allows control of options like the [`FormattingOptions`](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Formatting/FormattingOptions.cs) that would override values specified in the IDE?

**Comment by Pilchie** [comment]
There isn't at the moment, but it's something that we'd like to support as well.  (At least in the API, if not in VS).

**Comment by SLaks** [comment]
In the meantime, you can use my [Rebracer](https://visualstudiogallery.msdn.microsoft.com/410e9b9f-65f3-4495-b68e-15567e543c58) (solution-level only).
But native support for this would be much nicer.

**Comment by Pilchie** [comment]
Just happened to see this, but this is now possible in VS 2017 through our .editorconfig support.

**Comment by SLaks** [comment]
Is there any documentation for that, other than http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/CodeStyle/CSharpCodeStyleOptions.cs?

**Comment by Pilchie** [comment]
Yes!  See https://blogs.msdn.microsoft.com/dotnet/2016/12/15/code-style-configuration-in-the-vs2017-rc-update/ for an introductory blog post, and https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options for the docs.

**Comment by SLaks** [comment]
But none of those mention formatting options.
The closest is https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference

http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Formatting/CSharpFormattingOptions.cs is completely undocumented.

**Comment by Pilchie** [comment]
Tagging @kuhlenh and @jmarolf who worked on these docs.
