### ISSUE TITLE
No option to collapse local function

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14120]
**Steps to Reproduce**:
1. Write a local function

**Expected Behavior**:
Margin allows me to collapse local function, the same as a method.

**Actual Behavior**:
margin offers to collapse methods and lambdas but not local functions
![image](https://cloud.githubusercontent.com/assets/9797472/18894727/73502e64-84c9-11e6-872e-489c391c6a51.png)

**Comment by dpoeschl** [comment]
@CyrusNajmabadi @Pilchie @DustinCampbell Are we planning to make all scopes collapsible (if blocks, etc)? Or should we just do this for local functions?

**Comment by DustinCampbell** [comment]
Collapsing local functions is consistent with our behavior of collapsing multi-line lambdas and anonymous methods. I think we should just do those. The question of collapsing statements is a bit orthogonal.

**Comment by jcouv** [comment]
@DustinCampbell Would you have any pointer where this logic and corresponding tests reside? Thanks

**Comment by jcouv** [comment]
Never mind, it was fixed already (in https://github.com/dotnet/roslyn/pull/14269).

![image](https://user-images.githubusercontent.com/12466233/29992556-18db24e4-8f53-11e7-9e54-4f284a147dca.png)
