### ISSUE TITLE
Tuples have no way to control the spacing around the parentheses

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#14129]
**Version Used**: preview/25725

**Comment by dpoeschl** [comment]
@DustinCampbell @Pilchie  Do you remember if this is by design?

**Comment by DustinCampbell** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/10587.

I think we decided to wait and see what people ask for. I suspect there's a possibility for multiple options. For example, users might want to control spacing around parentheses when used in parameter lists or return types, but maybe not as locals.

**Comment by dpoeschl** [comment]
Closing as dupe.
