### ISSUE TITLE
Change signature not offered on local functions

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14122]
**Steps to Reproduce**:
1. Write a local function
2.  Invoke the light bulb (Ctrl+.) while the cursor is on one its parameters

**Expected Behavior**:
![image](https://cloud.githubusercontent.com/assets/9797472/18894920/c3995728-84ca-11e6-8b69-7f0e152afc42.png)

**Actual Behavior**:
No Change signature offered

**Comment by jcouv** [comment]
I have a PR out for this.

**Comment by jcouv** [comment]
Fix went in for 15.7 preview 3.
