### ISSUE TITLE
New icons for rules are too small and very hard to see

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#1412]
I have to squint to tell the difference between error and disabled.

(For some reason when I attach the below screenshot to the issue it seems to get magnified a little. But the real icons I see on the screen (and in my local copy of this screenshot) are even smaller. I wonder if this is because of high DPI or some such.)

![capture](https://cloud.githubusercontent.com/assets/10579684/6746601/791271e8-ce88-11e4-931e-28c8e5134718.PNG)

**Comment by shyamnamboodiripad** [comment]
I have contacted the folks in VS who created these icons for us requesting to make these larger.

**Comment by shyamnamboodiripad** [comment]
We now have new better looking icons for this that we need to check in internally. @tmeschter could you please handle the updating of the icons?

**Comment by tmeschter** [comment]
We have the `ImageMonikers` already, we just need to update the files associated with those monikers.

**Comment by tmeschter** [comment]
The fix for this was checked in today (April 30th, 2015) and should be in tomorrow's build. Bumping back to @shyamnamboodiripad for verification.
