### ISSUE TITLE
indent guides do not appear on local functions

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14126]
**Steps to Reproduce**:

1. write local function

**Expected Behavior**:
indent guides for local functions
**Actual Behavior**:
indent guides not offered on local functions, but are offered for methods and lambdas
![image](https://cloud.githubusercontent.com/assets/9797472/18894727/73502e64-84c9-11e6-872e-489c391c6a51.png)

**Comment by dpoeschl** [comment]
We know there's still an open question about where all indent guides should show up. What do we want the experience to be here?

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/14269
