### ISSUE TITLE
Generate Method should create tuple-returning methods

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#14136]
**Version Used**: preview/25725

```C#
class C
{
    public void M1()
    {
        (int x, int y) = Method();
    }
}
```

Generate Method on `Method` creates an object-returning method instead of a tuple-returning method.

**Comment by dpoeschl** [comment]
TypeInferrer bug?

**Comment by CyrusNajmabadi** [comment]
I wouldn't say it's a 'bug'.  This is more of a feature request on the type inferrer to at least pick something deconstructable (like a tuple) when used in a deconstruction context.
