### ISSUE TITLE
Question: Is the difference in presence/absence of the completion list after ( on invocation between C# and VB intentional?

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#14137]
**Version Used**: preview/25725

In a method, type "String.Format(". In C#, you just get Signature Help and can arrow through it. In VB you get Signature Help and Completion, and arrowing goes through Completion. Is this difference intentional?

**Comment by dpoeschl** [comment]
@Pilchie @rchande ?

**Comment by Pilchie** [comment]
Yes, for consistency with VB in 2013.
