### ISSUE TITLE
Better SigHelp experience around tuple arguments

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#14138]
**Version Used**: preview/25725

```C#
class C
{
    public void M1()
    {
        int x = 0, y = 0;
        M2$$
    }

    public void M2((int, int) t1, (int, int t2) t2) { }
}
```

At the $$, type `(`. SigHelp shows up. Begin typing the tuple with another `(` -- sig help disappears until you're done with the tuple. It'd be cool if it just stayed up while typing the tuple argument, and even cooler if it could highlight which tuple argument you are in the middle of typing.

**Comment by dpoeschl** [comment]
@rchande How hard would it be to do the "even cooler" bit discussed above?

**Comment by rchande** [comment]
Fixed, please verify @dpoeschl (fix is in master and rc)
