### ISSUE TITLE
Finalize the set of situations where not having TupleElementNamesAttribute is an error

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#14147]
We currently require the attribute when tuple type syntax is used in source.

The rule can be strengthened to:
- tuple literals with names as well
- any expression that returns a tuple type with nondefault element names

or relaxed:
- only require the attribute when it needs to be emitted.

Related to https://github.com/dotnet/roslyn/pull/14023

**Comment by jcouv** [comment]
@VSadov I thought this was answered and implemented already. Can you confirm whether any work is left for this?

**Comment by VSadov** [comment]
Because of how all current ValueTuple implementations are packaged, it is unlikely the situation will arise when ValueTuple types are present while TupleElementNames is not. 
Unless someone intentionally does such thing - but to what purpose? To get an error?

The implementation is actually a bit stronger than needed since not all type declarations will result in emitting the attribute, but we will report an error anyways.
The important part is that situations where tuple types with names used in signatures will require the attribute.
