### ISSUE TITLE
Squiggle does not go away after fixing type reference issue

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14145]
**Steps to Reproduce**:
1.  Create Project A that references Microsoft.CodeAnalysis.CSharp 1.3.1 nuget package
2.  Create Project B that references Microsoft.CodeAnalysis.CSharp 1.3.2 nuget package
3.  Have Project B reference Project A and call a public method from project B that references a Microsoft.CodeAnalysis.CSharp symbol
4.  Downgrade Project B to reference Microsoft.CodeAnalysis.CSharp 1.3.1 nuget package

**Expected Behavior**:
Error is removed

**Actual Behavior**:
Project now builds and no errors are in the error list but the squiggle is still there
![error](https://cloud.githubusercontent.com/assets/9797472/18922330/fe4dd33e-855c-11e6-92db-e0ea3d3d50ae.png)

**Comment by heejaechang** [comment]
@jmarolf did you restore?

**Comment by heejaechang** [comment]
@jmarolf I just tried to repro and the squiggle is not showing up at the first place.

**Comment by heejaechang** [comment]
@jmarolf ping?

**Comment by heejaechang** [comment]
@jmarolf please re-activate the bug if it still repro.
