### ISSUE TITLE
Pattern variable tests for Script should cover statements that currently aren't covered by GlobalCode_* unit-tests

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#14146]
Basically GlobalCode_\* unit-tests should cover all the different statements that are covered by Scope_\* unit-tests for all kinds of expression variables.

**Comment by AlekseyTs** [comment]
This issue for pattern variables.

**Comment by AlekseyTs** [comment]
@gafter If you disagree with assignment based on the feature ownership, bring it to @jaredpar.

**Comment by gafter** [comment]
I am following your lead in #13417 and #13569. As far as I can tell, you prefer a blanket issue that covers more when the underlying issue is not specific, for example, to one kind of expression variable. Issues can be partially completed if a new issue is opened for the remainder.

This issue is for all kinds of expression variables. Please do not exit this issue again.
