### ISSUE TITLE
Question: Is there a way to abort a running CSharpScript?

### ISSUE THREAD

**Issue by TzeWey** [dotnet/roslyn#14144]
If the running script contains an infinite loop, is there a way to stop it?

I am leaning towards finding a way to load the assembly into its own AppDomain and unload the domain to stop it from running and would like to know if there is a better way?

**Comment by tenor** [comment]
This question is a general non Roslyn-related .NET question, and can be rephrased as: is there a way to forcibly terminate a running thread?

**Long Answer:** Yes, there is, but it requires an elaborate setup that cannot be succinctly explained here.
**Better Answer:** Run your script in another process and terminate that process when you're done.
