### ISSUE TITLE
Instrumentation behavior for a switch "when clause" needs to be decided and implemented

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#14156]

**Comment by AdamSpeight2008** [comment]
I think we should be able to set a breakpoint on that `when clause`, so that it only breaks when the `clause argument` before is true. But before the `when clause` as executed.

**Comment by gafter** [comment]
A rough spec appears in https://github.com/dotnet/roslyn/issues/14337#issuecomment-254338630
