### ISSUE TITLE
Incremental parse hang when typing a tuple before a function call

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#14167]
**Version Used**: VisualStudio/preview/25727.00

**Steps to Reproduce**:

1. Create a new console app.
2. Add the following code into Main:
    ```
            (int a, int b) Inner()
            {
                return (0, 0);
            }

            Inner();
    ```
3. Before the invocation of inner, start to type `(int a, int b)` as if you were going to decompose it.

**Expected Behavior**: You can type.
**Actual Behavior**: The IDE hangs.

**Comment by jcouv** [comment]
Fixed by #14456
