### ISSUE TITLE
Project templates: Rename "Diagnostic.nuspec" file in templates and make it easier to create nuget packages that install correctly

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#1416]
I created a solution with multiple analyzer + code fix projects created using the Roslyn project templates. I then set output folders for all projects to the same directory expecting to see VSIXes and nugets for both analyzers in the output directory. But when I built the solution, looks like the Diagnostics.nuspec files from the two projects that have "copy to output directory" set to "copy if newer" just ended up clobbering each other.

It would be nice to base the name of this .nuspec file on the user name of the analyzer project (similar to how we change the name of the analyzer and code fix provider types to match) so that all .nuspec files are available in the output folder.

**Comment by shyamnamboodiripad** [comment]
Looks like nuget package creation for these projects just packages all dlls in the output folder into a single nuget package. So in the above scenario, I end up with multiple identical nuget packages...

**Comment by shyamnamboodiripad** [comment]
Not only are all dlls in the output folder packaged into a single nuget package. Looks like we also add each of these dlls as analyzer references when I consume these nuget packages.

This is quite problematic since I have to then go and remove the analyzer references that don't contain any analyzers to avoid the following annoying warnings.

Warning	CS8033	The assembly *\Documents\Visual Studio 2015\Projects\Apps\packages\CSAnalyzer.1.0.0.0\tools\analyzers\Common.dll does not contain any analyzers.

**Comment by jmarolf** [comment]
fixed when we moved to analyzer projects using the sdk-style project format
