### ISSUE TITLE
Local functions are missing descriptions in completion

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#14163]
Type the following code:

![image](https://cloud.githubusercontent.com/assets/201340/18936361/92bd4ed0-859b-11e6-99e6-d8abb2256368.png)

_Expected:_ there's a tooltip describing localFunction
_Actual:_ you get a cute little empty box

**Comment by Pilchie** [comment]
I wonder if the fixes @CyrusNajmabadi made to SymbolKey for OOP FAR fixed this?

**Comment by CyrusNajmabadi** [comment]
No clue.  But we shoudl add a test case for this.

**Comment by agocke** [comment]
The root cause of this bug seems to be that the symbol key serialization does not work for local functions.
