### ISSUE TITLE
CSharpSyntaxVisitor not visiting child nodes of VariableDeclarationSyntax

### ISSUE THREAD

**Issue by conniey** [dotnet/roslyn#1417]
I am writing a Roslyn diagnostic analyzer that checks the types that a List is initialized with.  But, the CSharpSyntaxVisitor is not visiting the nodes beneath the VariableDeclarationSyntaxNode.  In my concrete visitor, I have overrides for child nodes that should be there but none of the breakpoints are getting hit.  Also, if I do `analysis.Node.ChildNodes().ToArray()` in the Immediate Window, I can see the child nodes that my visitor should be hitting.

The code I am analysing is:
`var types = new System.Collections.Generic.List<Type> { typeof(String), typeof(System.Console) };`

The NuGet package of Roslyn is: https://www.nuget.org/packages/Microsoft.CodeAnalysis (1.0.0-rc1)

Analyzer Code:
```csharp
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public class Analyzer1Analyzer : DiagnosticAnalyzer
{
...
        public override void Initialize(AnalysisContext context)
        {
            context.RegisterSyntaxNodeAction((analysis) =>
            {
                ConcreteCSharpVisitor visitor = new ConcreteCSharpVisitor();
                visitor.Visit(analysis.Node);
            }, SyntaxKind.VariableDeclaration);
        }
}

class ConcreteCSharpVisitor : CSharpSyntaxVisitor
{
    public ConcreteCSharpVisitor() : base() { }

    public override void VisitEqualsValueClause(EqualsValueClauseSyntax node)
    {
        base.VisitEqualsValueClause(node);
    }

    public override void VisitVariableDeclarator(VariableDeclaratorSyntax node)
    {
        base.VisitVariableDeclarator(node);
    }

    public override void VisitObjectCreationExpression(ObjectCreationExpressionSyntax node)
    {
        base.VisitObjectCreationExpression(node);
    }

    public override void VisitTypeOfExpression(TypeOfExpressionSyntax node)
    {
        base.VisitTypeOfExpression(node);
    }

    public override void VisitInvocationExpression(InvocationExpressionSyntax node)
    {
        base.VisitInvocationExpression(node);
    }
}
```

**Comment by pdelvo** [comment]
I reported that and it is already fixed (but there is not an updated nuget package yet): #565

At least I think it is the same thing. Have you tried a Nightly Build?

**Comment by conniey** [comment]
I tried the latest nightly build on myget, but the same behaviour happens... it's not visiting those nodes. :(

**Comment by gafter** [comment]
A visitor does is not supposed to *recurse* down to visit children. It only dispatches for the single syntax node you call `Visit` on. So the behavior is by design.

**Comment by CyrusNajmabadi** [comment]
@conniey You'll want to use a SyntaxWalker instead.  A walker actually recurses down.

**Comment by mattwar** [comment]
You can also use the CSharpSyntaxRewriter, it is a CSharpSyntaxVisitor that does call recursively down the tree.

**Comment by conniey** [comment]
I see thanks for the clarification. I assumed that the nodes would pass around the Visitor to their children.

Are there any plans on adding samples or a wiki? I tried looking at the https://github.com/dotnet/roslyn/tree/master/docs/samples briefly but its impossible to just view it in browser and Ctrl+F specific things.
