### ISSUE TITLE
Minor code issue in PE meta data generation

### ISSUE THREAD

**Issue by ahowroyd** [dotnet/roslyn#14188]
**Version Used**: 
Current source code as of end Sep 2016.

File: Src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs
Line 2589: if (sizeWithOnlyFields > 0 && sizeWithOnlyFields < this.constantTable.Count)
in PopulateConstantTableRows()

Steps to fix

Change to: if (sizeWithOnlyFields < this.constantTable.Count)
Rationale: It is possible for sizeWithOnlyFields to be zero, but both other kinds of initialisation to exist and hence be unsorted.

Bug likely introduced with addition of property initalizers. (previously there was only the possibility of 2 kinds of initialisation)

**Steps to Reproduce**

1.  Create a module with both multiple property initializations and parameter initializations but no field initializations.
2. Examine PE for correct sortedness of constant initializations.

**Expected Behavior**:
Conant table rows should be sorted in all cases.

**Actual Behavior**:
Constant definitions will not be ouput into pe meta data in sorted order.

**Comment by svick** [comment]
Since you seem to know exactly what code should be changed, why don't you submit a pull request for this? Don't forget to add a unit test, if that makes sense.

**Comment by ahowroyd** [comment]
(I probably shouldn't even reply to that).
I'm not involved with the project, and at this time, am not willing to go there. (I may not even have the skills). At the same time this is a compiler, so the code makes interesting reading even for casuals - this is a case of many eyes can spot minor mistakes.

I also am not familiar enough with the code base to even fully compile it let alone build a unit test or find where that stuff goes. (again it doesn't make sense for me to start asking beginners questions if I'm not going to be putting the effort back into the project.)

Since I'm clearly not qualified to be making bug fixes, someone more familiar with that code is going to have to review (carefully) my input - I was more hoping that person would just say 'ah yes, thanks for spotting that'. Someone more familiar with the code might also make the call to just remove the 'if' statement completely (the optimisation of not always sorting seems rather dubious - in a big module the condition will almost certainly be true; when small optimisation is not important and sorting will be fast).

Sorry, if I'm being unhelpful - this is my last word on the subject - take my suggested fix or leave it.

**Comment by gafter** [comment]
Sounds like this may be the source of a determinism bug in the compilers.

**Comment by gafter** [comment]
I don't see anything like the code you quote in https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs
Am I looking at the wrong file?

**Comment by ahowroyd** [comment]
Right file, but it is has been substantially re-written compared with the copy I have. (and issue fixed). Although I only downloaded a couple of days ago, I seem to have gotten an 'old' version/branch. I'll investigate and probably re-download. I'll get back to you if there is anything to this. (just cancel for now)

**Comment by gafter** [comment]
This appears to have been fixed in https://github.com/dotnet/roslyn/commit/e9488f355f1cbf2049f0f94ce668efd51e8da5e0 .

**Comment by gafter** [comment]
You may have an old version on your disk. The `Src` directory no longer exists. The directory `src` is now used in its place.
