### ISSUE TITLE
Could we have documentation of what's planned for pattern matching in C# 7, please?

### ISSUE THREAD

**Issue by DavidArno** [dotnet/roslyn#14187]
Currently, [ roslyn/docs/features/patterns.md](https://github.com/dotnet/roslyn/blob/master/docs/features/patterns.md) on the master branch still documents lots of pattern matching features that are unlikely to make it into C# 7 (with just a basic type switch statement being planned for that release). In addition, the "patterns.work.md" doc mentioned therein results in a `404`. On the [Language Feature Status page](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md) links back to the full-blown pattern matching doc.

So there appears to be no documentation on what is currently likely to appear in C# 7. Could a new doc be created please that describes this, or the links updated so the master branch docs point to it?

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/csharplang/issues/1778
