### ISSUE TITLE
Doc comments don't show on local functions

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14182]
**Version Used**: 

**Steps to Reproduce**:

1.  Create a local function with doc comments
```C#
static Gen<SyntaxList<UsingDirectiveSyntax>> GenerateUsings() {
    /// <summary>
    /// method summary
    /// </summary>
    /// <returns></returns>
    Gen<UsingDirectiveSyntax> GenerateUsing()
    {
        var strings = GenerateIdentifierStrings();
        return Gen.Choose(1, 100).SelectMany(i => strings.ArrayOf(i))
            .Where(i => i.Length > 1)
            .Select(x => UsingDirective(CreateNameSyntax(x)));
    }

    var usings = GenerateUsing();
    return Gen.Choose(1, 100).SelectMany(i => usings.ArrayOf(i))
        .Select(array => List(array));
}
``` 
2. Hover over `var usings = GenerateUsing();

**Expected Behavior**:
Doc comments show up
![actual](https://cloud.githubusercontent.com/assets/9797472/18943424/5cba623a-85d4-11e6-8b8d-72a610719849.png)

**Actual Behavior**:
![actual](https://cloud.githubusercontent.com/assets/9797472/18943382/24e74774-85d4-11e6-8b76-fe4310200cf6.png)

**Comment by gafter** [comment]
It isn't clear that they are *supposed* to be supported on local functions. We need to decide, and then do whatever we decided.

**Comment by agocke** [comment]
Doc comments are for members, in my opinion. I do not think this should work.

**Comment by gafter** [comment]
@agocke I'm OK with doc comments not being supported for local functions.

@dotnet/ldm @dotnet/roslyn-compiler Does anyone want to push back on this?

**Comment by terrajobst** [comment]
> Doc comments are for members, in my opinion. I do not think this should work.

Agreed. Also, if were to support this, we'd also have to come up with how represent local functions in documentation IDs and decide how to persist them in the resulting XML. Which seems like a bad idea...

**Comment by CyrusNajmabadi** [comment]
👍 on not supporting doc comments.  It's similar to how we do nto support them for local lambdas either.

**Comment by gafter** [comment]
@CyrusNajmabadi Or local variables.

**Comment by AnthonyDGreen** [comment]
I don't think we need full doc-comment support because these are likely pretty lightweight but it would be nice if quick info showed the text from a comment immediately preceding the local function declaration. It seems to me the most likely and natural place for someone to write a brief summary of what that function does and we should plumb that through as we would a doc comment. I think this is also a fair experience for local variables now that I mention it.

**Comment by agocke** [comment]
Consensus reached! 😄
