### ISSUE TITLE
"Shared Project" appears twice in the New Project Dialog

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#14194]
**Version Used**: 25725

![image](https://cloud.githubusercontent.com/assets/235241/18972639/de9d7b14-864e-11e6-9a39-db4009b683e0.png)

**Comment by dpoeschl** [comment]
@jmarolf Any ideas?

**Comment by dpoeschl** [comment]
Are they identical (i.e., is this harmless), or is there some underlying difference?

**Comment by jmarolf** [comment]
dupe of https://github.com/dotnet/roslyn-project-system/issues/375 Fixed in bcb2
