### ISSUE TITLE
Peek (Alt+F12) does not work on Local Functions

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#14193]
**Version Used**: 25725

``` C#
class C
{
    public void M()
    {
        $$Foo();

        void Foo() { }
    }
}
```

Invoke Peek from the $$ location. 

![image](https://cloud.githubusercontent.com/assets/235241/18972593/a81b4832-864e-11e6-87f8-c8b1f66fda92.png)

**Comment by agocke** [comment]
Dup of #8644
