### ISSUE TITLE
Breakpoints on .

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#14198]
We should be able to place a breakpoint on the member invocation eg the dot `.`
Which would facilitate the debugging of chained methods, with breaking into separated invocations.

**Comment by AdamSpeight2008** [comment]
Since this could be a performance hit, I'd be ok if it an user option to enable or disable.
**UI-wise** we could implement an "horizontal margin" into the IDE
```
*  Represents a breakpoint (enabled)


* 42 || var en = GetTheEnumerable
     + \----------------------------------------------------------------------
     | |            *           *                         *         *
     + /----------------------------------------------------------------------    
  43 || var res = en.Where((e,i)=> i.IsPrime && e != null).Select( e=> e)
```

**Comment by timopomer** [comment]
truth, anyone who debugged linq extension methods knows exactly the pain of cutting a line of code into different temporary variables for debugging purpuses

**Comment by tmat** [comment]
Since similar feature request have been made previously I have filed a more general issue to track feature of placing breakpoint on an arbitrary expression: https://github.com/dotnet/roslyn/issues/22016. I would not hold my breath though expecting this feature to be implemented any time soon.
