### ISSUE TITLE
"View Class Diagram" fails with only .net desktop workload

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#14200]
**Version Used**: 25725

![image](https://cloud.githubusercontent.com/assets/235241/18976157/a0d6b712-8664-11e6-9e2e-f4336ec987e7.png)

![image](https://cloud.githubusercontent.com/assets/235241/18976160/a7bdcbce-8664-11e6-9527-472bbdea16f5.png)

**Comment by dpoeschl** [comment]
@jmarolf Is this a setup issue with the new installer?

**Comment by dpoeschl** [comment]
Jason mentions that @Pilchie might have fixed this.

**Comment by Pilchie** [comment]
Yes, fixed in latest internal builds.

**Comment by dpoeschl** [comment]
Closing and assigning myself to (theoretically) verify the fix.
