### ISSUE TITLE
SolutionTests.TestSyntaxRootNotKeptAlive failing again

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#14211]
SolutionTests.TestSyntaxRootNotKeptAlive has failed twice in the last two days.

https://github.com/dotnet/roslyn/pull/14204
https://github.com/dotnet/roslyn/pull/14162

It is known for rare intermittent flakiness because it relies on GC occurring within a time limit that cannot be guaranteed.  However, to not have the test leaves us vulnerable to easily accidentally breaking the weak-reference caching mechanism for syntax trees.

A failure could indicate that GC was not completed in time, or there was an actual change that affects this behavior.

**Comment by tmat** [comment]
More failures: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/4414/
