### ISSUE TITLE
Predefined type keywords should be recommended after case.

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#14218]
**Version Used**: 
25722.02

**Steps to Reproduce**:

``` C#
object o = null;
switch (o)
{
    case $$
};
```

type `int` at `$$`

**Expected Behavior**:
`int` is in the completion list and inserted.

**Actual Behavior**:
It isn't and something else gets inserted instead.

Now that type patterns can be used in switch cases, we need to recommend the predefined type keywords in this context.

**Comment by OmarTawfik** [comment]
@Pilchie no repro on `post-dev15`. Predefined types such as `int`, `string`, and `byte` are there.
Can you please confirm?

**Comment by OmarTawfik** [comment]
@Pilchie can you please check the following?

**Comment by Pilchie** [comment]
@CyrusNajmabadi can you take a quick look here?

**Comment by OmarTawfik** [comment]
@CyrusNajmabadi can you please take a look? should this be closed now?

**Comment by gafter** [comment]
@OmarTawfik A good way of disposing of this issue is to add a new (or identify an existing) test for it.
