### ISSUE TITLE
CSharpSyntaxGenerator.WithGetAccessorStatements assumes property has accessors

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#1423]
This method assumes that PropertyDeclaration.AccessorList is not null. However, it may be null in the case of expression-bodied properties:

``` C#
class Foo
{
    string Message => string.Empty;
}
```

Right now you can't use `SyntaxGenerator` to modify `Message` without hitting a `NullReferenceException`.

**Comment by Pilchie** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/1335

**Comment by tmeschter** [comment]
Reactivating.

With the fix for #1335 we no longer run into the `NullReferenceException`.

However, `SyntaxGenerator` now silently does nothing. If you take an expression-bodied property declaration and try to add a `get` accessor using `WithGetAccessorStatements` I expect it to remove the expression body and add the accessor. Instead, you just get the original declaration back.

**Comment by mattwar** [comment]
This is consistent with much of the behavior of SyntaxGenerator.  If you try to modify a property for a node that doesn't have that property it will just do nothing and give you back the original node.
