### ISSUE TITLE
Naming Styles: Indexer names should not be flagged

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#14234]
**Version Used**: 
25722.02

**Steps to Reproduce**:
1. Create a rule that non-private members need to be PascalCased.
2. Add an indexer

**Expected Behavior**:
No report, since indexer names are fixed

**Actual Behavior**:
We report an diagnostic on the indexer.

**Comment by Pilchie** [comment]
Didn't you fix this?

**Comment by dpoeschl** [comment]
This was fixed with along with the new UI changes.
