### ISSUE TITLE
Auto try block with presence of catch keyword

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#14231]
It so normal when we write some block of code and want to wrap it whole with try function

So I think maybe we could have some syntactic sugar for try-catch block. Simply put, if we have `catch` keyword after any `}` it will assume that those whole code was wrapped with `try`

```C#
public void A()
{
    // some lines of code
}
catch(Exception e)
{
   // normal catch
}

public void B()
{
    while(isTrue)
    {
        // Loop things
    }
    catch(Exception e)
    {
       // normal catch
    }
}
```

It would just transpile to

```C#
public void A()
{
    try
    {
        // some lines of code
    }
    catch(Exception e)
    {
        // normal catch
    }
}

public void B()
{
    while(isTrue)
    {
        try
        {
            // Loop things
        }
        catch(Exception e)
        {
            // normal catch
        }
    }
}
```

**Comment by svick** [comment]
This is quite similar to https://github.com/dotnet/roslyn/issues/13367.

**Comment by Thaina** [comment]
@svick Thanks. That issue also has some mention catch for if and using so this seem duplicated
