### ISSUE TITLE
Discussion - Deconstruction of Collections/Enumerables

### ISSUE THREAD

**Issue by Velocirobtor** [dotnet/roslyn#14235]
Since Deconstruction is probably going to make it into C#, I think it would be awesome to allow Deconstruction of Collections/Enumerables:

``` C#
var arr = new[]{1, 2, 3, 4};

var (a, b, c, d) = arr;
var (x, y) = arr.Take(2);
// or if Slices make it into C# (Which would be awesome!)
var (v, w) = arr[1:-1];
```

Python for example already has a similar feature and I think it's quite useful.
As for a possible Implementation:
Since Deconstruction will probably be via a Deconstruction Method with out parameters, allowing out params could do the trick:

``` C#
public static void Deconstruct<T>(this IEnumerable<T> collection, out params T[] values) {
    var enumerator = collection.GetEnumerator();
    for (int i = 0; i < values.Length; ++i) {
        if(!enumerator.MoveNext()) throw new DeconstructionException("Not enough values in collection");
        values[i] = enumerator.Current;
    }
    //and optional
    if(enumerator.MoveNext()) throw new DeconstructionException("Too many values in collection");
}
```

This way all Enumerables could be deconstructed.

**Comment by svick** [comment]
Related: https://github.com/dotnet/roslyn/issues/10631

**Comment by jcouv** [comment]
Discussion of language features are being moved over to csharplang. I'll move this issue over.

**Comment by jcouv** [comment]
Issue moved to [dotnet/csharplang #874](https://github.com/dotnet/csharplang/issues/874) via [**ZenHub**](https://www.zenhub.com/)
