### ISSUE TITLE
Designer file deleted from project when target framework is invalid

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#14244]
The issue we repro'ed last week.

Edit the project file, then add an entry to the RESX and save all. The design file gets removed from the project.
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    ...
    <TargetFrameworkIdentifier>FooBar</TargetFrameworkIdentifier>
    ...
  </PropertyGroup>

```

**Comment by Pilchie** [comment]
This issue does not contain enough description to be able to repro this bug.  Also, we're not likely to fix it for csproj.  If it's still an issue for CPS based projects, it should be filed in the project sytem repository.

**Comment by jcouv** [comment]
@Pilchie Dave was able to repro the issue in 2 minutes on my box. I filled the issue mostly to track it,  since he understood the repro better than me. 
@davkean can you confirm this should be closed?
