### ISSUE TITLE
VB tuples: inference for method type args differs between flat parameters and parameters as tuple

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#14255]
See tests below. If you invoke `Test(Function() 7, Function() 8)` (flat parameters) or `Test((Function() 7, Function() 8))` (tuple of 2 lambdas), the overload resolution between the flat vs tuple versions of `Test` method is different.
The difference stems from `OverloadResolution.EliminateNotApplicableToArguments`. 

For the flat case (no tuple), it updates the second candidate to have a max relaxation level of `DelegateRelaxationLevelWideningToNonLambda`, which causes that candidate to be rejected by `ShadowBasedOnDelegateRelaxation`. This relaxation level is determined by looking at the conversion from lambda to object, which has `ConversionKind.DelegateRelaxationLevelWideningToNonLambda`.

For the tuple case, the conversion is `WideningTuple` which leaves the maximum relaxation level to `None` and so the second candidate isn't rejected.

```VB

        <Fact>
        Public Sub Inference02()

            Dim comp = CreateCompilationWithMscorlibAndVBRuntime(
<compilation name="Tuples">
    <file name="a.vb">
Public Class C
    Shared Sub Main()
        Test((Function() 7, Function() 8))
    End Sub

    Shared Sub Test(Of T)(x As (T, T))
        System.Console.WriteLine("first")
    End Sub

    Shared Sub Test(x As (Object, Object))
        System.Console.WriteLine("second")
    End Sub

    Shared Sub Test(Of T)(x As (System.Func(Of T), System.Func(Of T)))
        System.Console.WriteLine("third")
        System.Console.WriteLine(x.Item1().ToString())
    End Sub
End Class
    </file>
</compilation>,
options:=TestOptions.ReleaseExe, additionalRefs:=s_valueTupleRefs)

            CompileAndVerify(comp, expectedOutput:="
second
")

        End Sub

        <Fact>
        Public Sub Inference02_WithoutTuple()

            Dim comp = CreateCompilationWithMscorlibAndVBRuntime(
<compilation name="Tuples">
    <file name="a.vb">
Public Class C
    Shared Sub Main()
        Test(Function() 7, Function() 8)
    End Sub

    Shared Sub Test(Of T)(x As T, y As T)
        System.Console.WriteLine("first")
    End Sub

    Shared Sub Test(x As Object, y As Object)
        System.Console.WriteLine("second")
    End Sub

    Shared Sub Test(Of T)(x As System.Func(Of T), y As System.Func(Of T))
        System.Console.WriteLine("third")
        System.Console.WriteLine(x.ToString())
    End Sub
End Class
    </file>
</compilation>,
options:=TestOptions.ReleaseExe, additionalRefs:=s_valueTupleRefs)

            CompileAndVerify(comp, expectedOutput:="
first
")

        End Sub
```

FYI @VSadov @AlekseyTs

**Comment by jcouv** [comment]
Do we have the same problem in C#?

**Comment by gafter** [comment]
The direction of comparison in the VB language spec have lower relaxation levels being worse and higher ones being better. It is reversed in the compiler. But the point of the rule should be that the worst relaxation level among the tuple element conversions is the relaxation level of the while tuple conversion for a widening tuple conversion.

**Comment by jcouv** [comment]
If we make any fixes for this, it will be good to add `Inference02_WithoutTuple` to the C# test suite too.

**Comment by gafter** [comment]
I've just started experimenting with what might be needed to address this in [https://github.com/gafter/roslyn/tree/master-14255](https://github.com/gafter/roslyn/tree/master-14255). My impression is that some of the rules regarding overload resolution with arguments and parameters would have to be extended to handle corresponding tuple cases (tuple type and literal); many of them are not reflected as conversion flags.

Handing off to @AlekseyTs .

**Comment by gafter** [comment]
@AnthonyDGreen @AlekseyTs @VSadov @jcouv @dotnet/ldm Can we please meet to discuss the approach we'd like the VB language specification to take on this issue before we commit to an implementation?

**Comment by AlekseyTs** [comment]
We discussed the approach and settled on aggregating (Max) delegate relaxation level across all tuple element conversions.
