### ISSUE TITLE
Error? In DirectCast.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#14266]
```
        Dim a = DirectCast(-1, SByte)
        Dim b As SByte = -1
        Dim c = CSByte(-1)
        Dim d = CType(-1, SByte)
```

Error message `Value of type 'Integer' can not be converted to 'SByte'.`
Located on the '-1`of the`DirectCast`, all of the other compile.

We should special case the usage of a literal, that is with the ranges of the target type of the cast as being a valid conversion.

**Comment by gafter** [comment]
`-1` is not a literal, but your point is well taken.

**Comment by gafter** [comment]
The VB language specification doesn't actually say what `DirectCast` is supposed to mean, statically or dynamically (hint, hint @AnthonyDGreen), but VS's pop-up help is relevant

![image](https://cloud.githubusercontent.com/assets/3804346/19172852/e7537ac6-8bd8-11e6-9072-3eaf54670719.png)

In short, `DirectCast` is supposed to look at the *type* of the expression, but not its value. The error is, I believe, by design.

@AnthonyDGreen Can you please confirm?

**Comment by AnthonyDGreen** [comment]
Per the current specification:

> 11.11 Cast Expressions
>
> A cast expression coerces an expression to a given type. Specific cast keywords coerce expressions into the primitive types. Three general cast keywords, CType, TryCast and DirectCast, coerce an expression into a type.
> 
> DirectCast and TryCast have special behaviors. Because of this, they only support native conversions. Additionally, the target type in a TryCast expression cannot be a value type. User-defined conversion operators are not considered when DirectCast or TryCast is used.
>
>> Annotation
>> The conversion set that DirectCast and TryCast support are restricted because they implement “native CLR” conversions. The purpose of DirectCast is to provide the functionality of the “unbox” instruction, while the purpose of TryCast is to provide the functionality of the “isinst” instruction. Since they map onto CLR instructions, supporting conversions not directly supported by the CLR would defeat the intended purpose.

Though the spec should probably amended to say that DirectCast is equivalent to the castclass instruction otherwise. It is correct to say that the _purpose_ of having DirectCast in the language is to support 'unbox', even if it supports more than that.

**Comment by AdamSpeight2008** [comment]
@gafter True, sometimes it's easy to forget that the `-` is an operator and not part of the literal representation.

**Comment by AnthonyDGreen** [comment]
@AdamSpeight2008 happens to literally everybody at least once.

**Comment by AdamSpeight2008** [comment]
Am I right in think that `-1` should reduced down to a constant during compilation, rather than evaluated at runtime. Where if the operator was followed by a variable identifier, has to be a runtime evaluation.

**Comment by AnthonyDGreen** [comment]
@AdamSpeight2008, that's intuitive though it might have some impact on overload resolution. Incidentally the fact that negative literals aren't compile-time constants is related to why Int32.MinValue isn't expressable as a decimal literal in code.
