### ISSUE TITLE
[Proposal] Case fall through should be allowed

### ISSUE THREAD

**Issue by dotnetchris** [dotnet/roslyn#1426]
C# should really allow proper case fall through. There is no reason it needs to derivate from C with how switch behaves. 

Perhaps an alternative would be similar to 

`switch unchecked(foo)` and this would allow proper case fall through without changing anything existing.

Having located https://github.com/dotnet/roslyn/issues/168 it already seems like this is supported and that something just specifically bars us from using it normally. Whatever disallows us to use case fall through should be turned off or have an opt-out.

**Comment by bbarry** [comment]
I use fall through switches already. It looks like this:

    public int DoSwitch(int i)
    {
        var j = 0;
        switch (i) 
        {
        case 0:
            j++;
            goto case 1;
        case 1:
            j++;
            goto default;
        default:
            j++;
            break;
        }
        return j;
    }

You simply have to be explicit about it (the gotos here are optimized out in release mode in VS). I would prefer seeing `break;` become optional since in the current syntax it could always be implied inside any case block containing at least one statement.

**Comment by dotnetchris** [comment]
That's not case fall through. Maybe the compiler turns it into case fall through but that's just explicit jump to labels what we're forced to type.

**Comment by CyrusNajmabadi** [comment]
@dotnetchris This is an extremely strong statement to make: "There is no reason it needs to derivate from C with how switch behaves."

For example, i can think of a very simple reason to deviate from C: It helps avoid accidental fallthrough errors.

C#'s behavior has saved me on several occasions.  I was bitten by this recently in JavaScript where i wrote this:

```js
case x:
    if (...) {
        // lots o code
        return;
    }
```

Where i intended to write:

```js
case x:
    if (...) {
        // lots o code
    }
    return;
```

Here, C#'s behavior would have caught this issue up front and saved me a lot of annoying debugging time to determine the issue.   As mentioned, if i truly want one case to fall through to the next (which is rare, but does happen), i'm simply explicit about it.  This means i have no loss of functionality *and* my code is self describing to anyone who needs to read it in the future.

**Comment by HaloFour** [comment]
> For example, i can think of a very simple reason to deviate from C: It helps avoid accidental fallthrough errors.

This is the entire reason that C# behaves the way it does.  `switch` fall-through has been identified as a common source of bugs in C.  I don't see how anything has changed, and if someone wants the behavior they can use `goto case`.

**Comment by firda-cze** [comment]
I am glad when compiler at least warns me and am fine with errors, but there is one exception:

```C#
switch(something)
{
case 0:
case 2:
    common();
    break;
case 1:
case 3:
   different();
   break;
}
```
but not to mess with current syntax, what about
```C#
switch(something)
{
   case 0, 2: doit(); break;
   case 1, 3: other(); break;
}
```
??

**Comment by paulomorgado** [comment]
@firda-cze, that syntax makes more sense than the one in the spec. The one in the speck feels like it's missing a `goto`.

But, is it really worth the change?

**Comment by HaloFour** [comment]
If pattern matching adopts the standard `switch` syntax it would likely be possible to write a generic helper class to evaluate multiple cases using a similar syntax, something like:

```cs
switch (something)
{
    case of(0, 2):
        doit();
        break;
    case of(1, 3):
        other();
        break;
}
```

**Comment by einsteinsci** [comment]
Perhaps a new definition of the `continue` keyword would work, using `continue` to explicitly fall-through, without the cringe-worthy feeling of reading and/or writing a `goto`:

```csharp
switch (foo.Bar)
{
case 1:
    // do stuff
    continue; // fall through to case 2
case 2:
    // do more stuff
    break; // still required
default:
    break;
}
```

**Comment by HaloFour** [comment]
@einsteinsci The `continue` keyword already means something if the `switch` statement occurs within a `for`, `while` or `do` loop.

**Comment by einsteinsci** [comment]
@HaloFour Ah. I knew it already had a meaning, but did not realize it would break existing code, by jumping to the next `case`, instead of the beginning of the loop. I guess the whole `unsafe switch` syntax will probably be the best option here then.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
