### ISSUE TITLE
Type inferrer doesn't infer nested tuple tupes

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#14277]
``` C#
(int, (string, bool)) x = (1, ("", $$))
```

The type inferrer does not infer the nested tuple of (string, bool) from a position inside the outer tuple.

**Comment by jcouv** [comment]
It will help for repro and verification to have a specific scenario that is impacted. Could you provide one?

**Comment by jaredpar** [comment]
@rchande can you add the information requested?

**Comment by CyrusNajmabadi** [comment]
@rchande isn't this entirely on the IDE side?  Is there something on the compiler side that is causing an issue here?

**Comment by CyrusNajmabadi** [comment]
not repro.  will add test indicating this.

**Comment by jasonmalinowski** [comment]
Reactivating this bug, because as discovered in https://github.com/dotnet/roslyn/pull/43521/commits/c492a3d010aa124b34aaae87a20bcd2b8f90cf22 the tests added weren't actually asserting anything. Once I fixed that the tests are failing sometimes.

**Comment by CyrusNajmabadi** [comment]
The fixed up tests seem to have the expected behavior.
