### ISSUE TITLE
C# compiler encodes module name into anonymous type, but does not distinguish "." and "_"

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#1428]
The C# compiler adds the module name to the encoding of an anonymous type name when generating a netmodule, but the mapping is not 1-to-1. In particular it maps "." to "_", which can cause a conflict when netmodules are combined that map to the same name under this mapping.

The VB compiler does not do this mapping, which means combining netmodules may fail due to anonymous types.

/cc @agocke @cston

**Comment by gafter** [comment]
I suggest the following 1-to-1 mapping for turning a module name to an identifier for embedding in the name of the generated anonymous type. The mapping can also be used for producing the name of the PrivateImplementationDetails class. This mapping need only be used when we are generating a netmodule. In other cases we do not need to include the module name in the generated name.

1. Any character that can appear in an identifier maps to itself, except `Q` and `_`.
2. `Q` maps to `QQ`
3. `_` maps to `Q_`
4. `.` maps to `_`
5. any other character maps to `Q` followed by four hex digits for its unicode value.

**Comment by gafter** [comment]
@VSadov I believe you might be looking at this.

**Comment by agocke** [comment]
I don't have a problem with the proposed solution for escaping, but FWIW I think the main issue here will be solved by not including the module name except when combining netmodules. Since very few people use netmodules the impact of the module name change should be fairly low.

**Comment by tmat** [comment]
I agree with @agocke - nobody really uses netmodules, so let's keep this as simple as possible. Just replace '.' with '/' e.g., which won't be contained in real world netmodule name since it is not a valid file name character.

**Comment by gafter** [comment]
It sounds like the two of you agree with my proposal "This mapping need only be used when we are generating a netmodule. In other cases we do not need to include the module name in the generated name."

However, I still think we should avoid using a mapping that is not 1-to-1. We should avoid making assumptions about the file system, so I still recommend the mapping described above.

**Comment by VSadov** [comment]
I think replacing . with / is sufficient. We could even go as far as making module names containing "/" an error to ensure that for the set of valid module names the mapping is 1-1.

**Comment by tmat** [comment]
See MetadataHelpers:

/// <summary>
        /// Checks that the specified name is a valid metadata String and a file name.
        /// The specification isn't entirely consistent and complete but it mentiones:
        /// 
        /// 22.19.2: "Name shall index a non-empty string in the String heap. It shall be in the format {filename}.{extension} (e.g., 'foo.dll', but not 'c:\utils\foo.dll')."
        /// 22.30.2: "The format of Name is {file name}.{file extension} with no path or drive letter; on POSIX-compliant systems Name contains no colon, no forward-slash, no backslash."
        ///          As Microsoft specific constraint.
        /// 
        /// A reasonable restriction seems to be a valid UTF8 non-empty string that doesn't contain '\0', '\', '/', ':' characters.
        /// </summary>
        internal static bool IsValidMetadataFileName(string name)
        {
            return FileNameUtilities.IsFileName(name) && IsValidMetadataIdentifier(name);
        }

**Comment by gafter** [comment]
We're talking about the module name, which is sometimes but not always related to the metadata file name.

**Comment by tmat** [comment]
We can require the module name specified via CompilationOptions to also be a valid file name (IsValidMetadataFileName true).

**Comment by gafter** [comment]
@tmat Why would we want to do that?

**Comment by tmat** [comment]
Why would we not do that? We define that '\0', '\', '/', ':' are not allowed in module name on all platforms. Nobody has ever complained and will not complain (cause nobody really cares about the module name).

**Comment by tmat** [comment]
The ECMA spec says that on Microsoft and Posix platforms these characters are disallowed. If anybody wanted to create such a module (or assembly) name the resulting binary won't work cross platform. So i think it's reasonable limitation.

**Comment by gafter** [comment]
There are other characters that may be used in a module name or a file name but may not appear in a type name (e.g. comma, asterisk, etc). I don't think we need to wait for incremental complaints from customers before providing a complete solution. Let us please just solve the problem once and for all.

**Comment by tmat** [comment]
I don't think changing this is worth the effort.

**Comment by gafter** [comment]
Then perhaps when I come to address this in milestone 1.2 I'll just close it as will not fix.
