### ISSUE TITLE
"vbCrLf is not declared" in EE when VB is called from C#

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#1429]
Create a C# Console Application with code:
```C#
class Program
{
    static void Main(string[] args)
    {
        ClassLibrary1.Class1.M();
    }
}
```

Create a VB class library with code:
```VB
Public Class Class1
    Shared Sub M()
    End Sub
End Class
```

Set a breakpoint on the definition of M() and start debugging. When the breakpoint is hit, try to evaluate "vbCrLf" in the Watch window.

**Expected**: It evaluates without error
**Actual**: (1) : error BC30451: 'vbCrLf' is not declared. It may be inaccessible due to its protection level.

**Comment by dpoeschl** [comment]
@amcasey FYI

**Comment by ManishJayaswal** [comment]
This repros in VS2013

**Comment by amcasey** [comment]
When it _does_ work (VB calling VB), it comes through an import of namespace ```Microsoft.VisualBasic``` in a ```TypesOfImportedNamespacesMembersBinder```.

**Comment by amcasey** [comment]
When it doesn't work (C# calling VB), there's still a ```TypesOfImportedNamespacesMembersBinder``` importing namespace ```Microsoft.VisualBasic```, but the namespace returns an empty collection from ```GetModuleMembers()```.

**Comment by amcasey** [comment]
Oh, _that's_ why this isn't a regression - in the C# calling VB case, Microsoft.VisualBasic.dll is not loaded.  That would certainly affect the namespace contents.

**Comment by amcasey** [comment]
I don't believe this can be fixed in the EE.
