### ISSUE TITLE
Do we allow explicit typing in tuple literals?

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#14293]
This applies to both C# and VB, but VB also has type characters

``` cs
var tuple = (int X = 1, int B = 2)
```

``` VB
Dim tuple = (X as Integer := 1, Y As String := "2")

Dim tuple = (X% := 1, Y$ := "2")
```

Current implementations do not allow explicit typing. Need to confirm with LDM(s)

**Comment by AnthonyDGreen** [comment]
I also thought about this for the first time this week. Should modified identifiers be extended to support tuples?

`Dim point(x As Integer, y As Integer) = GetOffset()`

It's one of those 'feels VB' things but I think I need to noodle on it for a bit.

**Comment by VSadov** [comment]
Another thing to consider is modified identifiers in tuple types -

```VB
Dim a As  (x?() as Integer, y() As Integer?, z As Integer?())
```

Not sure if there is a C# analog for this.

For now I assume that modified identifiers are not allowed in tuple types.

**Comment by VSadov** [comment]
And another, smaller, thing to consider whether under Strict Off

```VB
Dim x as (Ident1, Ident2())    ' is this   (Ident As Object, Ident2 As Object())  when Strict Off ??
``` 

This one seems to be VB only.

**Comment by tmat** [comment]
Can we avoid doing this? It feels like adding unnecessary complexity to new concepts. If VB customers are really keen on using type characters then it make sense. If the type characters are just something of a legacy feature I'd rather avoid them in new syntax forms.

**Comment by VSadov** [comment]
@tmat - Type chars are hard to avoid. They are supported pretty deep in the lexer and are parts of VB identifier tokens. Some support for type chars is needed even if just giving an error that they are not expected.
Being a lexer feature, type chars do not impact parsing much, so it seems easier to just support them.

The rest of the things mentioned here do bring a lot of complexity to the grammar/parser/binder, with none of additional expressiveness or convenience. 
How many different ways to say ```z As Integer?()``` are too many?
But there could be other opinions.

**Comment by tmat** [comment]
@VSadov If the complexity is limited to the lexer that's fine. I'm more worried about all IDE features and 3rd party analyzers that will need to handle complexity that can be avoided.

**Comment by xieguigang** [comment]
![no-title](https://cloud.githubusercontent.com/assets/9410171/19169863/b792402c-8c48-11e6-8d66-91ad61540f40.png)

Hi, how can I enable this tuple language syntax? tuple is still not working on Preview 5 for VisualBasic

```
BC37267 Visual Basic AND  VB.NET Predefined type is not defined or imported.
```

**Comment by VSadov** [comment]
You need to install nuget package for ValueTuple into your project.
ValueTuple types are required for tuples to work and are not available (yet) by default

**Comment by xieguigang** [comment]
Great, it works!

**Comment by xieguigang** [comment]
Hi, Can we adding a new language syntax of VisualBasic type char as type cast operation for the VB Primitive types, example as:

```vbnet
Dim x As Double = 3.0
Dim y As Integer = x%
```

``x%`` just working as the inline type cast operator ``CInt(x)`` if the primitive type can be casting, and I think this will makes the code more brevity

**Comment by AnthonyDGreen** [comment]
@xieguigang today the compiler insists that a reference to x uses the correct type character, if any, for the variable being referenced. So this would be a new meaning for that syntax that also turns off some type checking. It also would only apply to primitive types and to expressions that end in identifiers. I'm wary of adding another casting syntax for so narrow a scenario.

**Comment by xieguigang** [comment]
@AnthonyDGreen Hi, because of the gdi+ graphics drawing, mathematics calculation related framework development in the VisualBasic may required of a lot of usage of the primitive type, and some implicit type casting may exists. Due to the reason of Option explicit is OFF and Option strict is ON to following the company team coding rule,  implicit type casting can not be compiled, so that a lot of inline type casting ``CStr``, ``CInt`` may be used, and these will makes the code style not so nice-looking. And I think using the type char as the inline type casting would be good.

But still thanks a lot for reply my request. :-)

**Comment by AnthonyDGreen** [comment]
Option Explicit OFF or Option _Infer_ Of? Option Explicit just means you can use variables without explicitly declaring them.

**Comment by xieguigang** [comment]
![2016-10-18](https://cloud.githubusercontent.com/assets/9410171/19465089/ebf77532-9533-11e6-9687-c02f2fb5a528.png)
![2016-10-18 3](https://cloud.githubusercontent.com/assets/9410171/19465094/f0ad8e36-9533-11e6-92ac-8255e165c4b2.png)

@AnthonyDGreen  NoNONONO, I means when Option explicit is OFF and Option strict is ON, the implicit type casting will be an error....... not Option Infer Off

**Comment by xieguigang** [comment]
![old](https://cloud.githubusercontent.com/assets/9410171/19466560/6650eb7e-953e-11e6-82ce-e6e4f9757482.png)

This new inline type casting syntax looks better than the old style:

![new](https://cloud.githubusercontent.com/assets/9410171/19466568/6d6a356e-953e-11e6-9933-b97f9f742f26.png)

**Comment by VSadov** [comment]
I think we decided that this would unnecessary complicate the feature.

**Comment by toddpmain** [comment]
Too bad this was closed and not implemented. @xieguigang had the right suggestion for VB programmers for variable casting with type characters. In tuples too would be a bonus.
