### ISSUE TITLE
C# PrivateImplementationDetails class can contain module name with '.', confusing tools which expect to parse into namespaces

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#1430]
Commit 38aa68de adds the module name to the PrivateImplementationDetails class to prevent #1228. If that module name contains '.', tools which consume metadata and attempt to reverse engineer C# namespaces can become confused and believe that the dots represent namespace separators. For example, this is the result in refasmgen:

```
.namespace '<PrivateImplementationDetails><Maui.Core'
{
	.class private sealed 'dll>'
		extends [mscorlib]System.Object
	{
		.custom instance void [mscorlib]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = { }
		.method assembly static 
			uint32 ComputeStringHash(string s)
		{
			ret
		}
		.field static assembly initonly int64 '7E50BDC673C53A3E19E50BC237337FA9902ABB30'
	}
}
```

**Comment by gafter** [comment]
See #1428 for a proposed solution.

**Comment by gafter** [comment]
@VSadov I believe you might be looking at this.
