### ISSUE TITLE
Inconsistent localization patterns around creating Anonymous and Tuple types.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14302]
Some exceptions throw localized messages.  Some just have hardcoded english.  For example:

                throw new ArgumentException($"{nameof(elementLocations)} must either be 'default' or have the same length as {nameof(elementTypes)}.");

                    throw new ArgumentException(CodeAnalysisResources.TupleElementNameCountMismatch, nameof(elementNames));

**Comment by jcouv** [comment]
Fixed by #14464
