### ISSUE TITLE
Unlocalized exception messages in Compilation.cs

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#14313]
Most of our exception messages are localized, like

```cs
                throw new ArgumentException(CodeAnalysisResources.StreamMustSupportWrite, nameof(peStream));
```

but there are a number that are not. For example, in `Compilation.cs`, we find

```cs
                    throw new ArgumentException(String.Format("Reference of type '{0}' is not valid for this compilation.", reference.GetType()), "references[" + i + "]");
```

**Comment by OmarTawfik** [comment]
@gafter I did a scan and it looks like it was fixed in #14464. Let me know if there is anything else you found during the initial search.
