### ISSUE TITLE
MsBuildWorkspace.OpenSolutionAsync() takes a very long time

### ISSUE THREAD

**Issue by ap0llo** [dotnet/roslyn#14325]
**Version tested 1.3.2**: 

I'm trying to analyze a fairly large codebase using Roslyn. On of the first steps in my program is calling MsBuildWorkspace.OpenSolutionAsync() and awaiting the result. 
I encountered one solution containing about 300 projects that takes a very long time to open. (3-4 hours). Opening up the same solution in Visual Studio is much faster (about 5 minutes)

Is there some kind of debug log I can enable to determine where all the time is spent?

**Comment by Pilchie** [comment]
I'm not sure if you can do it without building your own Roslyn, but you might be able to hook up an msbuild diagnostic logger by passing properties to the `MSBuildWorkspace` constructor that would include timing information for each task/target.

Maybe @mattwar has other ideas?

**Comment by mattwar** [comment]
There was a fix made a few days ago that may be related.

**Comment by mattwar** [comment]
https://github.com/dotnet/roslyn/pull/14245

**Comment by ap0llo** [comment]
Yes, this seems to have fixed my problem as well. In my small test program that does nothing but to load the solution, the load time is down to 3 minutes with binaries built from the current master branch.

Thanks!

**Comment by Pilchie** [comment]
Closing as fixed by #14245
