### ISSUE TITLE
Create ProjectContext for each deferred project using the overloaded IWorkspaceProjectContextFactory.CreateProjectContext that takes a ProjectExternalErrorReport parameter

### ISSUE THREAD

**Issue by huizhonglong** [dotnet/roslyn#14331]
**Version Used**: latest preview5

This is related to issue 14329

Please create ProjectContext for each deferred project using the overloaded IWorkspaceProjectContextFactory.CreateProjectContext that explicitly takes an ProjectExternalErrorReport parameter
https://github.com/dotnet/roslyn/blob/65cc61578e9646cf76a297d8a9e0005afa57378a/src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker_IVsSolutionLoadEvents.cs

@Pilchie

**Comment by Pilchie** [comment]
Given that #14329 is fixed, and a new `ProjectExternalErrorReporter` will be created when it is accessed, we don't think this is required any more.
