### ISSUE TITLE
Add ValueTuple as default reference for interactive window

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#14347]
Both for C# and VB, it would be good if `ValueTuple` was referenced by default so that you can use the latest language features.

```
Loading context from 'CSharpInteractive.rsp'.
Type "#help" for more information.
> var t = (1, 2);
(1,9): error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported
```

FYI @VSadov

**Comment by jcouv** [comment]
Also, the default language version should be updated to avoid squiggles. 

![image](https://cloud.githubusercontent.com/assets/12466233/19174175/cf6b7374-8be1-11e6-93ef-3f8ae29dc736.png)

Strangely, as you can see, the code is run despite the squiggles.

**Comment by Pilchie** [comment]
I suspect this is because the IDE code explictly set the language version to 6 back when the compiler's default was 5, and that got removed from the interactive host process (that does the compile), but not the IDE (which does the squiggles).

**Comment by Pilchie** [comment]
I don't know if this can be reliably fixed though, as I don't believe we plan require 4.6.2 to be installed on the developer's machine.

**Comment by tmat** [comment]
It can be fixed. We ship ValueTuple in VS Private Assemblies and add it to interactive .rsp file.

**Comment by vbcodec** [comment]
Dou you plan VB Interactive to be ready for RTM ? Here #12974 VB PM says that it is mostly unfinished.

**Comment by jcouv** [comment]
@vbcodec, I don't know the answer, but #12974 is a better place to ask that. 
This here issue tracks that new language features should work in supported interactive scenarios.

**Comment by jcouv** [comment]
@tmat Do you want to file an issue to track the problem with extra brackets when a tuple is printed output?
If this is a problem with the ValueTuple library itself, I'd want to fix that soon.
