### ISSUE TITLE
Prefer throw-expression doesn't respect Severity setting in Tools options.

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#14356]
**Version Used**: 

**Steps to Reproduce**:
```C#
class Customer
{
    private string name;

    public Customer(string name)
    {
        if (name == null)
        {
            throw new ArgumentNullException(nameof(name));
        }
        this.name = name;
    }
```
1. Go to Tools\Options\Text Editor\C#\Code Style\ and change "Prefer throw expression" to be a suggestion/error/warning.

**Expected Behavior**:
Something to show in the error list and the editor.

**Actual Behavior**:
Nothing except the faded text.

**Comment by Pilchie** [comment]
Pretty sure I saw a PR out for this over the weekend anyway.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/3b9c80ad887064b9fda4299b924cdafb1914a087
