### ISSUE TITLE
CA1309 violation is observed when using == between strings with .NET 4.5.1

### ISSUE THREAD

**Issue by wargamer** [dotnet/roslyn#14355]
**Version Used**: 1.1.0

**Steps to Reproduce**:

1. Create a Console Application
2. Write code like 
`string a = "a";
string b = "b";
if(a == b) { }`
3. Observe a CA1309 violation

**Expected Behavior**:
I expect a CA1309 violation when I compare strings with something other than StringComparison.Ordinal
**Actual Behavior**:
A CA1309 violation pops up when I use `==` which, according to the reference source, does a comparison with StringComparison.Ordinal. And that should not generate a CA1309

It might also be worth to note that I'm building against .NET 4.5.1 and [I also made a StackOverflow post regarding this issue](http://stackoverflow.com/questions/39246924/is-ca1309-still-valid-for-source-compiled-against-net-4-5-1).

**Comment by srivatsn** [comment]
Moved to https://github.com/dotnet/roslyn-analyzers/issues/1081
