### ISSUE TITLE
Error symbols are not fully roundtrippable

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14365]
Currently, it is possible to get error NamedTypeSymbols that we cannot fully roundtrip with the IDE's OOP process.  Specifically, error types may point to error namespaces as their containing symbol.  However, there is currently no way to specify that namespace when we try to re-realize the error type.  i.e. we have this:

```
        public abstract INamedTypeSymbol CreateErrorTypeSymbol(INamespaceOrTypeSymbol container, string name, int arity);
```

But we do not have a way to Create the container in the case of something like an error namespace.

**Comment by CyrusNajmabadi** [comment]
tagging @gafter @AlekseyTs

**Comment by Pilchie** [comment]
@CyrusNajmabadi what work is left on the IDE, and what scenario is it about?

**Comment by CyrusNajmabadi** [comment]
there is some SymbolKey work left.  That said, i think this could be pushed out to post-dev15.

**Comment by DustinCampbell** [comment]
@CyrusNajmabadi : Is this still needed?

**Comment by DustinCampbell** [comment]
I mean, is this issue still needed? Or, does the work still need to happen? I'm looking at #27527 and I'm wondering if I should do this as part of that.

**Comment by CyrusNajmabadi** [comment]
Yes, i think this work is still needed.  @jnm2 just ran into this.  @jnm2 can you point at a commit where you're seeing htis.

**Comment by jnm2** [comment]
@CyrusNajmabadi https://github.com/jnm2/roslyn/commit/roslyn_14365

**Comment by jnm2** [comment]
The test was `TestCSharp_SetterReferences` in`FindReferencesTests.PropertySymbols.vb`:
https://github.com/jnm2/roslyn/commit/e2156684718d2ac0a4065470e9592f7e7d518166#diff-cf436af41a63a3fa8133dfaf1da9f56fR921

**Comment by CyrusNajmabadi** [comment]
@DustinCampbell The test jnm2 reference will fail due to an inability to roundtrip an error-type-symbol for 'System.Int32'.  While this specific codepath is unlikely to be hit by a user in practice (it basically occurs when you don't have a reference to mscorlib), it does demonstrate the problem.  

The primary problem is in ErrorTypeSymbolKey.Create/Resolve.
