### ISSUE TITLE
TypeScript and JavaScript are read-only when debugging

### ISSUE THREAD

**Issue by billti** [dotnet/roslyn#14360]
Note: I already discussed this with @tmat and he asked me to log the issue here for tracking.

**Version Used**: Git commit e74d9fa (Oct 3rd)

**Steps to Reproduce**:

1. File / New Project / ASP.NET / Choose a template that has some content
2. Set a breakpoint in a JavaScript file that will run on launch.
3. Press F5 and wait for the breakpoint to be hit

**Expected Behavior**:
4. The file is still editable in the editor.

**Actual Behavior**:
5. The file is marked as readonly (same goes for TypeScript files)

## Investigations so far

It seems to me the root cause is that TypeScript/JavaScript documents belong to a different project than the project being debugged, but the EditAndContinue code only tracks one project launched by the debugger, and thus doesn’t find the documents project to answer certain questions.

The whole class "VsENCRebuildableProjectImpl" is initialized with one AbstractProject (the project being debugged):

```c#
        internal VsENCRebuildableProjectImpl(AbstractProject project)
        {
            _vsProject = project;
// etc…
```
In this class, in EnterBreakStateOnPE, it creates the edit session with that one project:

```c#
                    s_breakStateEnteredProjects.Add(KeyValuePair.Create(_vsProject.Id, state));
                    s_breakStateProjectCount++;

                    // EnC service is global, but the debugger calls this for each project.
                    // Avoid starting the edit session until all projects enter break state.
                    if (s_breakStateEnteredProjects.Count == s_debugStateProjectCount)
                    {
                        Debug.Assert(_encService.EditSession == null);
                        Debug.Assert(s_pendingActiveStatements.TrueForAll(s => s.Owner._activeStatementIds.Count == 0));

                        var byDocument = new Dictionary<DocumentId, ImmutableArray<ActiveStatementSpan>>();

                        // note: fills in activeStatementIds of projects that own the active statements:
                        GroupActiveStatements(s_pendingActiveStatements, byDocument);

                        // When stopped at exception: All documents are read-only, but the files might be changed outside of VS.
                        // So we start an edit session as usual and report a rude edit for all changes we see.
                        bool stoppedAtException = encBreakReason == ENC_BREAKSTATE_REASON.ENC_BREAK_EXCEPTION;

                        var projectStates = ImmutableDictionary.CreateRange(s_breakStateEnteredProjects);

                        _encService.StartEditSession(s_breakStateEntrySolution, byDocument, projectStates, stoppedAtException);
```

So when VSReadOnlyDocumentTracker::SetReadOnly asks:

```c#
_encService.IsProjectReadOnly(document.Project.Id ...
```

When it runs:

```c#
            // normal break mode - if the document belongs to a project that hasn't entered the edit session it shall be read-only:
            if (editSession.Projects.TryGetValue(id, out projectReason))
            {
                sessionReason = SessionReadOnlyReason.None;
                return projectReason != ProjectReadOnlyReason.None;
            }
```

The editSession.Projects doesn't contain the TypeScript project, and falls through to the MetadataNotAvailable code path.

This simple hack in `VsReadOnlyDocumentTracker::SetReadOnly` to skip all those checks for documents belonging to the TypeScript project type...

```c#
        private void SetReadOnly(Document document)
        {
            // Only set documents read-only if they're part of a project that supports Enc.
            var workspace = document.Project.Solution.Workspace as VisualStudioWorkspaceImpl;
            var project = workspace?.ProjectTracker?.GetProject(document.Project.Id);

            if (project?.Language.Equals("TypeScript") == true)
            {
                return;
            }
```

..worked around the issue (as shown below). Maybe this is an OK temporary workaround if a proper fix is too invasive at this point.

**Comment by ManishJayaswal** [comment]
@tmat what are your thoughts on the workaround?

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/14572/commits/ab5d0db6980aec2502e7cb733a85708b6524a2b1

**Comment by tmat** [comment]
@billti Could you validate with the latest d15prerel build please?

**Comment by billti** [comment]
Works great. Thanks!
