### ISSUE TITLE
Microsoft.VisualStudio.LanguageServices should embed Shell.Interop 10 and 11 IAs

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#1436]
### Problem
If you build a VS component which references both Microsoft.VisualStudio.LanguageServices and Microsoft.VisualStudio.Shell.Interop.10 (or 11) you will get a build warning if you try to embed the interop assembly (NoPIA). That's because MS.VS.LanguageServices does NOT embed these two interops.
### Background
We do not currently embed these two interops in MS.VS.LS because by doing so creates its own build warning due to references in Microsoft.VisualStudio.Progression.CodeSchema
### Fix
Track down the authors of Microsoft.VisualStudio.Progression.CodeSchema and ask them to embed these two interops.

**Comment by sharwell** [comment]
Why do you need to embed them? They are always available (provided by the IDE installation) and immutable. Embedding them in every assembly that references them also has the unwanted side effect of increasing the size of all the assemblies that get loaded.

**Comment by sharwell** [comment]
As an additional note, we (extension developers) do actually need to embed Shell.Interop.11 in certain cases - but this is to enable support for a single extension targeting Visual Studio 2010+ that "opts-in" to a Visual Studio 2012+ feature when run in an environment that supports it. One example is Git Diff Margin, which uses the `IVsDifferenceService` when provided by the IDE:

https://github.com/laurentkempe/GitDiffMargin/blob/master/GitDiffMargin/Git/GitCommands.cs

**Comment by pharring** [comment]
I think you answered your own question: Embedding makes "light up" easier/possible.Embedding will include only the types that you actually use and it knows how to leave "vtable gaps" for unused methods too.

This particular issue is more of a "build quirk" than a policy that will help Roslyn. We have an existing VS component that supports light up from version 10 onwards and has all the shell interops embedded. If that component takes a dependency on MS.VS.LS, then they get a build warning. The reason MS.VS.LS doesn't embed today is because of that Progression.CodeSchema assembly.

**Comment by pharring** [comment]
Looks like this should be an easy fix. I'll make the change on the Progression side.

**Comment by Pilchie** [comment]
@pharring  want to finish this up if the Progression changes are in?

**Comment by pharring** [comment]
The Progression change was made, but we're blocked waiting for a new (internal) base drop. Once it's there, we can update.

**Comment by Pilchie** [comment]
Great - I know people are currently evaluating a new base drop, so hopefully this can be wrapped up in the next couple of days.

**Comment by amcasey** [comment]
Adding label so it shows up in the to-verify query.
