### ISSUE TITLE
Reenable Interactive Window Integration Tests

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#14369]
Interactive Window integration tests don't work anymore on pre-Willow VS and have been disabled. Enable them once we only run on Willow.

**Comment by tmat** [comment]
See ```Closed\Hosting\Test\Execution\TestLocator.cs```

**Comment by ivanbasov** [comment]
Fixed with 
https://github.com/dotnet/roslyn/pull/18137
https://github.com/dotnet/roslyn/pull/18297
https://github.com/dotnet/roslyn-internal/pull/1726
