### ISSUE TITLE
Source files for a project sometimes open in the miscellaneous project 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#14361]
This is happening with 25806.00 WPT, but also hit it with a few builds before it. I also saw @srivatsn hit this.

I'm hitting it occasionally opening the ProjectSystem repo in the old project system, but I've also hit it with Console and WinForms projects.

1. Create a new WinForms project
2. Notice that Designer fails to load, if you look at Form1.cs it opens in Misc Files.

It is inconsistent so its probably some sort of race, one time I also hit this, and unsure if its related:
```
system\src\Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj : error  : Project 'Microsoft.VisualStudio.ProjectSystem.Managed' could not be opened because the Visual C# 15 Preview 5 compiler could not be created. ValueFactory attempted to access the Value property of this **instance.**
```

**Comment by davkean** [comment]
Note, I attempted to debug this but lost the repro.

**Comment by Pilchie** [comment]
@srivatsn @nguerrera @mavasani - anyone else hitting this? Unfortunately, without a repro we'll have a hard time investigating :(

**Comment by Pilchie** [comment]
Tagging @jasonmalinowski in case he's seen any reports of anything like this too.

**Comment by jasonmalinowski** [comment]
Nope.

**Comment by Antaris** [comment]
I've just encountered this in using VS2017 `VisualStudio/public.d15rel/15.0.26009.0` with the Preview5 bits:

![snip_20170106110515](https://cloud.githubusercontent.com/assets/255906/21716121/6526b57a-d400-11e6-92ce-42e3f875979e.png)

Here is my MSBuild file:

```xml
<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\..\SharedProperties.props" />
  <PropertyGroup Label="Fx">
    <UseSqlServer>true</UseSqlServer>
  </PropertyGroup>
  <PropertyGroup>
    <Description>Data library</Description>
    <Copyright>Fresh Egg Limited</Copyright>
    <AssemblyTitle>FX: Data</AssemblyTitle>
    <TargetFramework>netstandard1.6</TargetFramework>
    <AssemblyName>Fx.Data</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
    <EmbeddedResource Include="_Content\**\*.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Fx.Common\Fx.Common.csproj" />
    <ProjectReference Include="..\Fx.Core.Abstractions\Fx.Core.Abstractions.csproj" />
    <ProjectReference Include="..\Fx.Core\Fx.Core.csproj" />
    <ProjectReference Include="..\Fx.Data.Abstractions\Fx.Data.Abstractions.csproj" />
  </ItemGroup>
</Project>
```

If I close and re-open Visual Studio, or close the file and re-open from the Solution Explorer, it still appears as misc and won't provide Intellisense.

Still build fines though.

**Comment by Antaris** [comment]
I disabled lightweight solution load on the Solution property window (F4) and restarted VS, it now loads as part of the project again.

**Comment by davkean** [comment]
@jasonmalinowski @Pilchie  I've found a repro for this: https://github.com/dotnet/roslyn-project-system/issues/1350. It looks like we're putting you in some sort of bad state - need to debug it.
