### ISSUE TITLE
Proposal: Overridable is operator

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#14372]
Disclaimer: This is not related to the previously proposed `is` operator for deconstruction.

Swift has introduced a "match" operator to override matching logic for types. I think it is useful to have something similar to [the `~=` operator in Swift](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Patterns.html) (via the `is` operator).

The overridable `is` operator will accept precisely two operands.

Using #11159:
```cs
[Flags]
enum State { None, A = 1, B = 2, C = 4 }

extension class StateExtensions : State {
  public static bool operator is(State a, State b) => a.HasFlag(b);
}

State s = State.A | State.B;
Console.WriteLine(s is State.A); // prints true
// translates to
Console.WriteLine(StateExtensions.op_Match(s, State.A));

```
Clearly, the logic is different compared to `==` so we need to define it as the `is` operator.

With help of #262 and #2944 we *might* be able to generalize the above example.
```cs
public extension class FlagsEnumExtensions<T> : T where T : enum, [Flags] {
  public static bool operator is(T a, T b) => a.HasFlag(b);
}
```
The advantage of this approach is that you can have custom matching logic also in `switch` statements.

**Comment by svick** [comment]
What are the use cases for this? Normal `[Flags]` `enum`s already have `HasFlag()`, so what is an example of a type that would benefit from the "custom matching logic"?
