### ISSUE TITLE
Open Source Enhanced source view

### ISSUE THREAD

**Issue by slang25** [dotnet/roslyn#14394]
For large organisations, the [Enhanced source view](http://source.roslyn.codeplex.com/) would be really useful for quick cross-repo analysis and code browsing/discovery.

Is this on your roadmap? I am in the process of building something very similar right now, would love to not have to and just extend your work!

**Comment by alrz** [comment]
https://github.com/KirillOsenkov/SourceBrowser

**Comment by slang25** [comment]
@alrz Awesome 😃 Thanks!
