### ISSUE TITLE
Implement Units of Measure or a broader class of similar contracts

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#144]
F# is the inspiration:

https://msdn.microsoft.com/en-us/library/dd233243.aspx

This could be user-configurable, however:

"Units of measure are used for compile-time unit checking but are not persisted in the run-time environment. Therefore, they do not affect performance."

"Units of measure are used for static type checking. When floating point values are compiled, the units of measure are eliminated, so the units are lost at run time. Therefore, any attempt to implement functionality that depends on checking the units at run time is not possible. For example, implementing a ToString function to print out the units is not possible."

Perhaps it could be an additional feature to the ones already requested such as method pre- and post- conditions etc.

**Comment by lyubomyr-shaydariv** [comment]
I'm not familiar with this concept, but is the following assumption true: if I declare one float as "weight" and another one as "length", then I can't perform any arithmetic operations over them until I cast them back to floats (just strip the units)?

**Comment by manish** [comment]
@lyubomyr-shaydariv 
I think you should be able to do

e.g. if your first variable is a weight say 16kg or more scientifically a force 16N `Newton` and your second variable is length, say 5 meters, then when you multiply them, you get 80 `Nm`. A `Nm` is torque.

A variable distance say 20 miles divided by another variable 5 hours would yield speed, 4 miles/hour.

**Comment by AdamSpeight2008** [comment]
`10`  is just value, it has no implicit meaning. 10 what?
`10 metres` is a better, as you know it that it is a different to say `10N`
*I think it also is aware that metres is unit of measure for distance and newtons is a unit of measure for mass*

It prevents you doing silly things like adding `metres` to `newtons` , but you could be allow to multipy them for `Nm` (Torque).

Unit of Measure add an additional "compile-time" type safety to numeric values.
At the moment to sort of get the same functionality you have to implement a system yourself.

[Example 0](http://www.dreamincode.net/forums/topic/297808-why-separation-of-concerns-matters/)
[Example 1](http://www.dreamincode.net/forums/topic/344882-a-unit-system/)

**Comment by dsaf** [comment]
Yes, otherwise you will need to apply the 'pure OOP' approach and create a struct per type of unit (or some type of generic wrapper) and then create all the operator overloads and then consuming code will have to deal with that type hierarchy and its performance implications. Basic value types are kind of a gap in the type system.

**Comment by dsaf** [comment]
From #2209:

> I don't see why not. It would nice to have user-defined literals as in C++11, so you can do something like:

> ```csharp
public primitive Radian
{
   …
   public static Radian operator _rad;

>    public static implicit operator Radian(int value)
   {
       return new Radian((value % 360) * Math.PI / 180f);
   }

>    public static implicit operator Radian(float f)
   {
       // do the corresponding calculation here ...
   }
   ...
}
```
> So when you use it like var myRadian = 45_rad; or var myRadian = 45.23f_rad;, the literal will pick the corresponding implicit operator to get the Radian;

**Comment by dsaf** [comment]
A way of declaring unsigned floats would also be beneficial.

**Comment by omidkrad** [comment]
I really like what @JohanLarsson has done in [Gu.Units](https://github.com/JohanLarsson/Gu.Units). It's probably the closest thing to F# we can do in C# at this time. I think this could be extended to support currencies as well (you don't want to add up USD and EUR, for example, before some conversion).

**Comment by MadsTorgersen** [comment]
Units of measure in F# are immensely cool. However, I think a similar thing in C# would be a major effort, that would benefit only a small portion of its developers. This is not the language's sweet spot.
