### ISSUE TITLE
MSBuild support for /version ?

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#14411]
There is a [new command-line only flag](https://github.com/dotnet/roslyn/issues/7588), `/version`, for asking the compiler to report its version (and exit).

Like `/help` and `/logo`, this is not currently supported through MSBuild. Should it be?

Is this something that should be exposed in the IDE?

@mattwar @Pilchie @AnthonyDGreen @jaredpar

**Comment by Pilchie** [comment]
I don't see any reason to expose this in the IDE.

**Comment by AdamSpeight2008** [comment]
@Pilchie I disagree, having it in (at least) the `About Visual Studio` could help narrow the search space of reported issues / bugs.

**Comment by AnthonyDGreen** [comment]
@MattGertz for MSBuild coordination.

**Comment by MattGertz** [comment]
This does not make the bar currently, given all of the other critical work we've loaded onto the MSBuild team.  Perhaps in a future version.

**Comment by gafter** [comment]
I've changed the milestone to 2.1. We are now talking about possible *future* support.

So for a future version, is this something we want to expose in the IDE? If so, what would that look like? Would it make more sense for there to be a way of seeing what modules (and their versions) are loaded into VS?

Is it something we want to add MSBuild support for? If so, what would that look like?

**Comment by gafter** [comment]
@jasonmalinowski @mattwar @AlekseyTs Please chime in whether or not you'd like this exposed in MSBuild, and if so what the form of that support would be.

**Comment by mattwar** [comment]
I don't understand what it means to have msbuild support for this?  

Are you imagining someone using msbuild on the command line and issuing a build request to get back the compiler version instead of actually building?

Are you imaging that the IDE is issuing an request via the project system's use of msbuild to determine the compiler version and somehow relay that information to the user some way?

Something else?

**Comment by AlekseyTs** [comment]
> I don't understand what it means to have msbuild support for this? 

Be able to invoke the compiler task in msbuild so that it would output the compiler version.

**Comment by AlekseyTs** [comment]
I think we should support this switch in msbuild.

**Comment by gafter** [comment]
@AlekseyTs
Do you have a proposal for what form that support would take, or are you hoping someone else will make a proposal?

**Comment by jasonmalinowski** [comment]
@AdamSpeight2008's suggestion of exposing it under Help > About or maybe a property page for a project seems useful (remember: the answer can technically vary per project due to NuGet packages.)

I'm not sure what it would mean for the build task to have support. I guess you could always just have the task have another output property with it. Having it invoke csc /version directly (with no way to parse the output) seems unnecessary.

**Comment by AlekseyTs** [comment]
@gafter 
> Do you have a proposal for what form that support would take

See how other command line arguments are supported by VB and C# compiler tasks. I don't think /version switch should be any different.

**Comment by gafter** [comment]
@AlekseyTs As a design approach, that sounds fine, but nobody has performed that design exercise. I also don't have a proposal for how it should behave. I'll keep this open for a while in case someone else does.

**Comment by mattwar** [comment]
I agree with @AlekseyTs that the flag should pass into the msbuild task. It is not entirely different than the NoLogo flag that gets passed, or other cosmetic flags..

However, we should separate that from if & how this information is exposed in the IDE.

**Comment by gafter** [comment]
@mattwar The purpose of `/version` command-line flag is to cause the compiler to produce the version information in its output *and do nothing else*, so that the consumer can parse the complete compiler output as a version number. In that sense it is not merely a cosmetic flag, and extending that behavior to MSBuild is probably counterproductive. If we just want the version information to appear in the msbuild log, the logo line is sufficient and no support for anything like `/version` would be needed.

**Comment by tmat** [comment]
Why don't we just do nothing and wait till someone actually asks for this? Personally I don't think there is any scenario when this would be useful.

**Comment by jaredpar** [comment]
Agree with @tmat for now.
