### ISSUE TITLE
GetMetadataReader throws when reading metadata of versions different than the running process

### ISSUE THREAD

**Issue by raffaeler** [dotnet/roslyn#14425]
**Version Used**: 
Microsoft.CodeAnalysis.* version 1.3.2
The hosting process is an asp.net core application
The assembly that I am trying to read the metadata from, is a .NET Framework 4.5.2 DLL

**Steps to Reproduce**:
The following code runs in the .NET Core application:
```
var filename = @"C:\dev\SomeDotNetFramework.dll";  // .NET Framework 4.5.2 DLL
var raw = System.Collections.Immutable.ImmutableArray.Create<byte>(System.IO.File.ReadAllBytes(filename));
var provider = System.Reflection.Metadata.MetadataReaderProvider.FromMetadataImage(raw);

// *** the following will throw ***
var reader = provider.GetMetadataReader(System.Reflection.Metadata.MetadataReaderOptions.None);
...
```

**Expected Behavior**:
I expect to be able to read any metadata compatible with the ecma-335 specifications.
For example I expect a .NET desktop can read the metadata coming from a winmd file or a .net core dll.
Likewise, as for this example, I expect a .net core process can read the metadata of any other kind of assembly/winmd.
I also want the analyzed metadata being **unloaded** from memory once the read is over. In other words, I don't want the dll is loaded as a normal assembly would be.

The expected behavior would be similar to what happens in the Microsoft ecma-335 C++ API which I use in other projects. The C++ API can read any metadata coming from any ecma-335 file, regardless the clr-flavor/version.

**Actual Behavior**:
From the following exception, I understand the metadata API complains the dll being analyzed is built with a different .net flavor than the current process.

Exception thrown: 'System.BadImageFormatException' in System.Reflection.Metadata.dll
Additional information: Invalid COR20 header signature.

**Comment by 0xd4d** [comment]
Is this Roslyn related?

AFAIK, that method expects pure .NET metadata as input and you pass in a PE file. [CODE](https://github.com/dotnet/corefx/blob/ba9bd56a79764086a916c95b372279a7e01cee93/src/System.Reflection.Metadata/src/System/Reflection/Metadata/MetadataReader.cs#L188)

**Comment by raffaeler** [comment]
Thank you, I didn't know the metadata stuff was moved into corefx.
As for the BadImageFormatException, I will retry by just feeding the metadata instead of the whole assembly. I didn't expect this.

**Comment by tmat** [comment]
@raffaeler Try this:
```C#
using (var peReader = new PEReader(File.OpenRead(filename)))
{
   var reader = peReader.GetMetadataReader();
}
```

**Comment by raffaeler** [comment]
Thank you, you brought me on the right way.
This code does not throw ...
```
using (var peReader = new System.Reflection.PortableExecutable.PEReader(File.OpenRead(filename)))
{
    var raw = peReader.GetMetadata().GetContent();
    var provider = System.Reflection.Metadata.MetadataReaderProvider.FromMetadataImage(raw);
    var reader = provider.GetMetadataReader(System.Reflection.Metadata.MetadataReaderOptions.None);
    foreach (var typedef in reader.TypeDefinitions)
    {
        var definition = reader.GetTypeDefinition(typedef);
        // ...
    }
}
```

**Comment by tmat** [comment]
@raffaeler You don't need to use MetadataReaderProvider to get the metadata reader. [PEReader.GetMetadataReader](https://source.dot.net/#System.Reflection.Metadata/System/Reflection/Metadata/PEReaderExtensions.cs,8653910fa2bff691)  extension method returns MetadataReader.
