### ISSUE TITLE
Event parameter cascading stopped working after changes to SemnaticModel around event parameters

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#14428]
Related to work for https://github.com/dotnet/roslyn/issues/14364.

Test Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences.FindReferencesTests.TestEventParameterCascading has been disabled.

**Comment by AlekseyTs** [comment]
See https://github.com/dotnet/roslyn/pull/14434.

**Comment by AlekseyTs** [comment]
Reassigning based on offline conversation.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/issues/14477
