### ISSUE TITLE
With Lightweight Solution Load, a deferred project fails to build for dynamic analysis

### ISSUE THREAD

**Issue by JohnHamby** [dotnet/roslyn#14433]
With Lightweight Solution Load enabled for a solution that includes a VB class library project and a C# project that refers to the VB project, opening a file in the C# project in a way that triggers dynamic analysis to build the C# project also requires dynamic analysis to build the VB project. The VB project build fails as if the fundamental .Net types (System.Object, System.String, etc.) were not available.

@Pilchie @ManishJayaswal @KevinH-MS might find this to be of interest.

**Comment by Pilchie** [comment]
Can you provide a repro solution somewhere?

**Comment by Pilchie** [comment]
Moving to RC.2 as this was rejected by shiproom.
