### ISSUE TITLE
C# Interactive package load failure in latest ML

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#14430]
**Version Used**: 
25810.01
**Steps to Reproduce**:
1. Open VS and attempt to open C# interactive window 

You currently get a package load failure. Exception info below is taken from the activity log:

LegacySitePackage failed for package [CSharpVsInteractiveWindowPackage]Source: 'System.ComponentModel.Composition' Description: No exports were found that match the constraint: ContractName Microsoft.VisualStudio.LanguageServices.CSharp.Interactive.CSharpVsInteractiveWindowProvider RequiredTypeIdentity Microsoft.VisualStudio.LanguageServices.CSharp.Interactive.CSharpVsInteractiveWindowProvider

**Comment by tmat** [comment]
Fixed yesterday: https://github.com/dotnet/roslyn/pull/14406
