### ISSUE TITLE
Expose the ProjectExternalErrorReporter from IWorkspaceProjectContext

### ISSUE THREAD

**Issue by huizhonglong** [dotnet/roslyn#14432]
This is related to issue # 14375.
Now CPSProjectFactory. GetExternalErrorReporter() will not return an existing reporter for a projectId, but rather create a new one.
As we discussed, please expose the ProjectExternalErrorReporter from IWorkspaceProjectContext

@mavasani

**Comment by Pilchie** [comment]
@mavasani are you going to take care of this?

**Comment by mavasani** [comment]
Actually, I am wondering if we actually need to fix this - AbstractProject already implements the error reporter specific VS interfaces: http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/AbstractProject_IVsReportExternalErrors.cs,10 and you can just cast the `IWorkspaceProjectContext` to `IVsReportExternalErrors` or `IVsLanguageServiceBuildErrorReporter2` and it will use the project external error reporter to report errors. CPS also does this explicit cast to report errors: https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs#L51

**Comment by mavasani** [comment]
Confirmed with @huizhonglong that she is now unblocked and doesn't really need this change.
