### ISSUE TITLE
Audit all asynchronous operations to ensure a waiter is present.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#14442]
Ensure all operations defined [here](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/Shared/TestHooks/FeatureAttribute_Names.cs) have an appropriate waiter [here](https://github.com/dotnet/roslyn/tree/master/src/Test/Diagnostics/Waiters).

**Comment by AdamSpeight2008** [comment]
Could do with an analyser to do the checking. Akin to the Public Api analyser.

**Comment by jasonmalinowski** [comment]
We could probably just change the API and have one single thing rather than requiring an export for each individual type. There's no good reason why the shape of this API is what it is.

**Comment by jasonmalinowski** [comment]
Hey look @heejaechang did this. Closing!

**Comment by AdamSpeight2008** [comment]
@jasonmalinowski In which PR?

**Comment by jasonmalinowski** [comment]
@AdamSpeight2008 #24120.
