### ISSUE TITLE
Display exception stack trace in expanding section in error list for the errors that are reported for analyzer / fixer crashes

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#1444]
This is how errors for crashing analyzers look currently -
![1](https://cloud.githubusercontent.com/assets/10579684/6762325/503cdd10-cf1b-11e4-803f-7d432a501c75.PNG)

The exception stack trace is missing in the error. I feel this information is required so that analyzer authors can know where the exception is being thrown from. End users won't care about stack trace and so it should only be displayed in an expanding section.

Ideally we need a long description field on the diagnostic to store the stack trace. However, until we have one, we could repurpose diagnostic.Descriptor.Description for this. Per recent conversation with @mavasani, we already create unique descriptors for each instance of these diagnostics - so it shouldn't be too difficult to populate the above field in the descriptor with the stack trace.

We should also serialize stack trace for any inner exceptions.

**Comment by mavasani** [comment]
Well I think this is a bug: "we already create unique descriptors for each instance of these diagnostics"
but its fine as its not an analyzer descriptor.
I agree this seems very useful to fix.
