### ISSUE TITLE
Casting should not switch to suggestion mode

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14449]
**Version Used**: 25807 / 2.0.0.60925

**Steps to Reproduce**:

``` C#
namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            int a = (in|
        }
    }
}
```

**Expected Behavior**: The autocomplete list to be in completion mode, like in previous builds.

**Actual Behavior**: The autocomplete list is in suggestion mode instead. I blame tuples.

**Comment by miloush** [comment]
This has biggest impact when you want to use capital letters only to select the type to cast to, as this do not work in suggestion mode:
```C#
DependencyObject d = (DO|
```

**Comment by Pilchie** [comment]
@CyrusNajmabadi @rchande @jcouv - any ideas here?

**Comment by CyrusNajmabadi** [comment]
Assigning to Julien.

Julien, we're probably being too conservative.  If we can infer a known real type, then we probably don't want to switch to suggestion mode.

**Comment by jcouv** [comment]
Thanks for reporting this. Just got back from vacation. I'll look into it shortly.

**Comment by jcouv** [comment]
I tried typing the code below and tried typing a few triggers at the `$$` mark (return, tab, comma and close-paren). They all behaved as I expected (completing the word "DependencyObject").
The colon trigger also behaved as I expected (not completing the word).

@CyrusNajmabadi I'll stop by to confirm with you.

```C#

class DependencyObject
{
    static void Main(string[] args)
    {
        DependencyObject d = (DOb$$
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Perhaps your fixes didn't make it into the right branch.  If this is fixed, and we have tests for this experience, then this can be closed out (ideally with the corresponding PR of yours where you did this work).

**Comment by miloush** [comment]
I confirm I cannot reproduce this on latest builds.

**Comment by jcouv** [comment]
Thanks.
I'll keep this issue open for now to check that we have test coverage.

**Comment by jcouv** [comment]
I think this is covered by `TupleExpressionInVarDeclaration` and `TupleExpressionInVarDeclaration2` tests in `SuggestionModeCompletionProviderTests`.
