### ISSUE TITLE
Test failure on clean up-to-date Roslyn: UnitTests.CompilerServerUnitTests.SimpleMSBuild

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#1445]
Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.SimpleMSBuild : Assert.Equal() Failure Position: First difference is at position 0 Expected: Actual: Microsoft (R) Build Engine version 14.0.22705.0 Copyright (C) Microsoft Corporation. All rights reserved. Build started 3/20/2015 4:03:16 PM. 1>Project "C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloSolution.sln" on node 1 (Rebuild target(s)). 1>ValidateSolutionConfiguration: Building solution configuration "Debug|Mixed Platforms". The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft.NetNative\Microsoft.NetNative.targets (60,11)" does not exist in the project, and will be ignored. The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft.NetNative\Microsoft.NetNative.targets (108,11)" does not exist in the project, and will be ignored. 1>Project "C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloSolution.sln" (1) is building "C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloProj.csproj" (2) on node 1 (Rebuild target(s)). 2>CoreClean: Creating directory "obj\x86\Debug\". The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft.NetNative\Microsoft.NetNative.targets (60,11)" does not exist in the project, and will be ignored. The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft.NetNative\Microsoft.NetNative.targets (108,11)" does not exist in the project, and will be ignored. 1>Project "C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloSolution.sln" (1) is building "C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloLib.csproj" (3) on node 2 (Rebuild target(s)). 3>CoreClean: Creating directory "obj\Debug\". PrepareForBuild: Creating directory "bin\Debug\". The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft.NetNative\Microsoft.NetNative.targets (60,11)" does not exist in the project, and will be ignored. The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft.NetNative\Microsoft.NetNative.targets (108,11)" does not exist in the project, and will be ignored. GenerateTargetFrameworkMonikerAttribute: Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files. 3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(405,15): error MSB4064: The "ErrorLog" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property. [C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloLib.csproj] 3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(386,9): error MSB4063: The "Csc" task could not be initialized with its input parameters. [C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloLib.csproj] 3>Done Building Project "C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloLib.csproj" (Rebuild target(s)) -- FAILED. 1>Project "C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloSolution.sln" (1) is building "C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\VBLib.vbproj" (4) on node 3 (Rebuild target(s)). 4>GenerateTargetFrameworkMonikerAttribute: Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files. 4>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.VisualBasic.CurrentVersion.targets(386,15): error MSB4064: The "ErrorLog" parameter is not supported by the "Vbc" task. Verify the parameter exists on the task, and it is a settable public instance property. [C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\VBLib.vbproj] 4>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.VisualBasic.CurrentVersion.targets(371,9): error MSB4063: The "Vbc" task could not be initialized with its input parameters. [C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\VBLib.vbproj] 4>Done Building Project "C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\VBLib.vbproj" (Rebuild target(s)) -- FAILED. 2>Done Building Project "C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloProj.csproj" (Rebuild target(s)) -- FAILED. 1>Done Building Project "C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloSolution.sln" (Rebuild target(s)) -- FAILED. Build FAILED. "C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloSolution.sln" (Rebuild target) (1) -> "C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloLib.csproj" (Rebuild target) (3) -> (CoreCompile target) -> C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(405,15): error MSB4064: The "ErrorLog" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property. [C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloLib.csproj] C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(386,9): error MSB4063: The "Csc" task could not be initialized with its input parameters. [C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloLib.csproj] "C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\HelloSolution.sln" (Rebuild target) (1) -> "C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\VBLib.vbproj" (Rebuild target) (4) -> C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.VisualBasic.CurrentVersion.targets(386,15): error MSB4064: The "ErrorLog" parameter is not supported by the "Vbc" task. Verify the parameter exists on the task, and it is a settable public instance property. [C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\VBLib.vbproj] C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.VisualBasic.CurrentVersion.targets(371,9): error MSB4063: The "Vbc" task could not be initialized with its input parameters. [C:\Users\ngafter\AppData\Local\Temp\RoslynTests\311748a0-c5c7-4207-85ee-9141969fe12d\VBLib.vbproj] 0 Warning(s) 4 Error(s) Time Elapsed 00:00:01.56

**Comment by agocke** [comment]
This was a break caused by the diagnostics team due to the added "ErrorLog" parameter.

**Comment by jcouv** [comment]
Test related to this issue is still skipped and failing. Re-opening issue.
```C#
  [Fact(Skip = "https://github.com/dotnet/roslyn/issues/1445")]
        public void SimpleMSBuild()
```

**Comment by jaredpar** [comment]
These tests have been disabled for 1.5 years now. Lets take a look at this in 15.6. If it's easy to fix then lets do so. Otherwise lets delete the tests.
