### ISSUE TITLE
Move bootstrap build back to MSBuild 15.0

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#14451]
Our bootstrap build temporarily needs to go back to MSBuild 14.0.  There is a bug in MSBuild 15.0 which prevents us from fully loading our bootstrap components and hence invalidates our build.  

https://github.com/Microsoft/msbuild/issues/1183

This bug tracks the removal of work arounds on our end.

**Comment by tannergooding** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/14892
