### ISSUE TITLE
Code Style for usings

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14450]
With the new code style feature I would suggest having some coverage for usings, namely
- whether usings should be inside namespaces or at the top level
- whether usings should be fully qualified (cf #3716)
- whether 'System' directives should be sorted first (currently an editor option)

**Comment by DavidArno** [comment]
Could you add highlighting unused usings to that list?

**Comment by Pilchie** [comment]
Agreed, though unfortunately, we're not going to have time to get to it in the 2.0 release.

**Comment by jinujoseph** [comment]
closing this  
"whether usings should be inside namespaces or at the top level" is done via [link](https://github.com/dotnet/roslyn/pull/35009)
