### ISSUE TITLE
"Hide base name" code fix does the wrong thing for const fields

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#14455]
_Ported from Visual Studio Feedback_

``` C#
class A { internal const int i = 0; }
class B : A { internal const int i = 1; }
```

Apply "Hide base name" from the light bulb.

![image](https://cloud.githubusercontent.com/assets/116161/19323713/f126c8fc-9072-11e6-97cb-bca47196e7ef.png)

Note that there are two problems. First, there's a formatting issue, and second, that's an illegal position for "new" to appear in the language.

**Comment by sharwell** [comment]
Marking as a duplicate of #18391 (could have been the other way around, but the work was done on that issue)
