### ISSUE TITLE
Object Browser/Class View do not show base types or members of types in projects contained in solution folders during search

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#14462]
![image](https://cloud.githubusercontent.com/assets/116161/19326842/fd5caaca-9080-11e6-9d51-b0b91b422959.png)

vs. 

![image](https://cloud.githubusercontent.com/assets/116161/19326854/0b53bf6a-9081-11e6-9118-5352509a8783.png)

**Comment by JoshVarty** [comment]
There is a related issue when dragging items from the ClassView onto things like UML panes. In VS2015 RTM when you dragged an item the clipboard would have contained "Test\\ClassLibrary5". As of VS2015 Update 1 the clipboard now appears to contain just "ClassLibrary5".
