### ISSUE TITLE
Proposal: Better code generation

### ISSUE THREAD

**Issue by MarkPflug** [dotnet/roslyn#14468]
There currently exist two approaches to code generation (that I'm aware of):

One, is to use SingleFileGenerator (CustomTool) in Visual Studio. This is a "design time" feature of Visual Studio that creates source .cs files that are included in the project, and thus also included in source control. This is currently used for generating the code behind .resx and .tt files, for example.

A second approach is to use a custom MSBuild task to generate code at compile time. I believe this approach is used for generating code for xaml files.

There are pros and cons to both approaches:

**SingleFileGenerator**

Pros
- You get Intellisense for generated code in Visual Studio, since the code is part of the project.
- You can view the generated source file, if you like.

Cons
- Requires Visual Studio. Can't generate the source without VS to drive the custom tool.
- Generated code gets added to source control. I list this as a con, because I don't consider generated code to be "source code".

**MSBuild Task**

Pros
- Works from a command line build, and on a build system without needing VS.
- Generated code doesn't get included in source control.

Cons
- No intellisense for generated code in VS. (This can be a very big con)

In both scenarios, the source C# code has been generated before the compiler is invoked, so the compiler simply deals with the .cs files it is provided. 

The proposed [Generators](https://github.com/dotnet/roslyn/blob/master/docs/features/generators.md) feature appears to be potential third approach to this problem, though it appears to be addressing AOP concerns more than simple code generation. My proposal is to extend the generators feature to allow a generator to be associated with input files that are not C# source. So, for example a "resx generator" could be explicitly provided the list of .resx source files that it should generate code for.

Analyzers have similar support through the /additionalfiles parameter to csc. Potentially, these additional files could be made available to generators, but there might need to be some mechanism to indicate to the generator _which_ additional files it should be generating code for, beyond simply using the file extension (or maybe the file extension is enough).

This seems like it would be the best of both worlds: generated code doesn't get added to source control, you could get intellisense in VS for the generated code, and it would work from a command line build.

I'm assuming that for generators there would be a significant amount of AST caching that would happen when working in VS. Such caching would need to be aware that a change to the input file (resx) would require that the AST be regenerated. I would expect that the AST would only be updated "upon save" of the input file, not during "live edit".

Perhaps this is already a scenario that the generators feature is intended to support, but in reading the description it sounds like it is only currently intended to generate code based on attributes in the input source files; meaning it wouldn't have access to the _additional files_ collection.

**Comment by MarkPflug** [comment]
Also, the generated code for SingleFileGenerators is "editable", which can be problematic since any modifications would be overwritten the next time the file is generated. Ideally, it would be possible to "navigate to" a symbol in the generated code and see source file representation of the AST, but the source would be presented in a readonly view, in much the same way a "from metadata" readonly view is presented when you navigate to a symbol in an external assembly.

@mattwar Does this proposal mesh at all with the generators feature that you proposed in #5561?

**Comment by gafter** [comment]
@cston I assigned this to you to investigate whether it makes sense in the context of generators.

**Comment by MarkPflug** [comment]
I recently came across a project that already accomplishes what I've proposed here: (not surprisingly by a member of the Visual Studio team)
https://github.com/AArnott/CodeGeneration.Roslyn 

I was able to apply a similar pattern to the one he used in a test project. It works as I was hoping: I have a custom file format (file extension) that when saved will generate C# code that is then immediately visible via Intellisense to the rest of my code, and the generated code won't be included in source control. This is nice, because by updating a nuget package I can change the content of the generated code, but won't have to have a huge changeset, just an update to the package version. This is superior to a SingleFileGenerator where I would have to regenerate all the files in my project, and then check in a massive changeset with uninteresting changes. And of course, it also works from a command line MSBuild. The key to this is the MSBuild <Generator> metadata that Visual Studio IDE will use to trigger a MSBuild target when the input file is saved. I cannot find this <Generator> metadata documented anywhere.

This mostly works, but there are couple things that could be improved.

First, the <Generator> metadata doesn't seem to be honored when it is applied to custom Item types. In my example targets file I defined an ItemGroup as `<StringList Include="**\*.str"/>`. I applied the Generator using an ItemDefinitionGroup:

```
  <ItemDefinitionGroup>
    <StringList>
      <Generator>MSBuild:GenerateCodeExample</Generator>
    </StringList>
```

This didn't work, and I tried a few variations to no avail. The _hack_ that finally got things to work was to apply my generator to both the `Compile` item type as well and include `<Compile Include="**\*.str"/>`. Obviously, I don't want to compile the .str files, but seemingly the `Compile` item type was required to get the `Generator` to be honored. In my generator target I then `<Compile Remove="@(StringList)"/>` so that the .str files aren't passed to csc. This works, but definitely feels like a hack. Why would the Generator metadata not apply to custom Item types? (I acknowledge this is no longer a question for the Roslyn team)

The second thing that could be better, was what I mentioned in my previous comment, a readonly view of the generated code. My code generator writes the generated code files to the "obj" folder (IntermediateOutputPath). In Visual Studio, when I navigate to definition on a symbol defined by the  generated code, it takes me to the source file in the obj folder. This generated file has  a "g.cs" extension to indicate it is generated, and a comment indicating not to edit it. However, it would be nice if there was a way to tell Visual Studio to display the source code in a read-only way; perhaps by applying a GeneratedCode metadata to the item. I'm worried that the team who would be using this tool will end up getting confused and editing the generated code, only to have it overwritten the next time the code is generated. If the IDE could prevent that, it would be ideal.

So great news, I think this feature request can be dropped from the Roslyn repo.

I would like to forward the above suggestions to the appropriate Visual Studio team though. Do you guys know if there is a git repo where it would be appropriate to open an issue with this?

**Comment by jnm2** [comment]
I would say https://github.com/dotnet/project-system but half the things I've opened there got moved 😆
