### ISSUE TITLE
No Quick Info when hovering over methods or property during debugging

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#1446]
Ported from TFS WorkItem: <b>1114405</b>

---

<p><b>Repro Steps:</b></p>

<P><B>Affected Branch:</B> <BR><B>Affected Build:</B> <BR><B>Affected Product Language:</B> <BR><BR><B>Steps to reproduce:</B><BR><BR>1. Paste the following code over boilerplate code on a VB console application</P>

<P>&nbsp;</P><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>
<P>Module</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT color=#000000 size=2 face=Consolas> </FONT></FONT><FONT color=#2b91af size=2 face=Consolas><FONT color=#2b91af size=2 face=Consolas><FONT color=#2b91af size=2 face=Consolas>Module1</P></FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>
<P></FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>&nbsp; Dim</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> _count </FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>As</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> </FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>Integer</P></FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>
<P></FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>&nbsp; Sub</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> Main()</P>

<P></FONT></FONT><FONT color=#2b91af size=2 face=Consolas><FONT color=#2b91af size=2 face=Consolas><FONT color=#2b91af size=2 face=Consolas>&nbsp;&nbsp;&nbsp; Console</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>.WriteLine(</FONT></FONT><FONT color=#a31515 size=2 face=Consolas><FONT color=#a31515 size=2 face=Consolas><FONT color=#a31515 size=2 face=Consolas>"debuggin"</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>)</P>

<P></FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>&nbsp; End</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> </FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>Sub</FONT></FONT></FONT></P>

<P><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>&nbsp;</P></FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>
<P></FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>&nbsp; Public</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> </FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>Function</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> Foo() </FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>As</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> </FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>Integer</P></FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>
<P>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MsgBox(</FONT></FONT><FONT color=#a31515 size=2 face=Consolas><FONT color=#a31515 size=2 face=Consolas><FONT color=#a31515 size=2 face=Consolas>"hello"</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>)</P>

<P></FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>&nbsp; End</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> </FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>Function</FONT></FONT></FONT></P>

<P><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>&nbsp;</P></FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>
<P></FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>End</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT color=#000000 size=2 face=Consolas> </FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>Module</FONT></FONT></FONT></P>

<P><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas></FONT></FONT></FONT>&nbsp;</P>

<P>&nbsp;</P>

<P>2. Put a BP on Console.WriteLine line and hit F5</P>

<P>3. When the BP is hit, hover your mouse over the function name "Foo" ( if you are on a build that does not have a fix for 1112400 then you would see the function getting evaluated however this bug is about a different issue).</P>

<P>&nbsp;</P>

<P>&nbsp;</P>

<P>Expected: &nbsp;there is hover tip for function Foo</P>

<P>&nbsp;</P>

<P>Actual:&nbsp;&nbsp;there is no hover tip for function Foo</P>

<P>&nbsp;</P>

<P>This is a regression from Dev12</P>

<P><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>&nbsp;</P></FONT></FONT></FONT>

------------------------------

<p><b>Revisions:</b></p>

1) Created By Manish Jayaswal (1/23/2015 5:52:10 PM)

---

2) Edited By Andrew Casey (ROSLYN) (1/26/2015 1:08:55 PM)

Manish clarified that he expected to see Quick Info, rather than a data tip.

---

3) Edited By Manish Jayaswal (2/3/2015 2:17:07 PM)

Not a regression from Dev12 so making it pri 3.

---

**Comment by CyrusNajmabadi** [comment]
@jinujoseph we haven't heard anything about this in 7 years.  I'm ok closing this out.
