### ISSUE TITLE
Perf test escaping sometimes fails

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#14480]
The string escaping in perf tests sometimes fails, resulting in broken builds that shouldn't have failed. Some examples include:

* https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit64_prtest/1080/console
* https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/4807/console

**Comment by 333fred** [comment]
This is because the Pull Title isn't properly escaped here: https://github.com/dotnet/roslyn/blob/master/cibuild.cmd#L98

**Comment by 333fred** [comment]
The root cause is coming from here: https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java#L360. The pull title needs to be escaped.

**Comment by 333fred** [comment]
@mmitche @TyOverby @jaredpar I've submitted https://github.com/jenkinsci/ghprb-plugin/pull/430 to ghprb.

**Comment by mmitche** [comment]
@333fred Okay this will get merged in when the next plugin update happens.
