### ISSUE TITLE
EE: No error reported for unrecognized (perhaps missing) pseudo-variable type

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#1449]
Ported from TFS WorkItem: <b>1102923</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P>See Microsoft.CodeAnalysis.VisualBasic.UnitTests.PseudoVariableTests.UnrecognizedAssembly unit test.</P>
<P><BR>F5 the following:</P>
<P>Class C<BR>&nbsp;&nbsp;&nbsp; Shared Sub Main()<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; System.Diagnostics.Debugger.Break()<BR>&nbsp;&nbsp;&nbsp; End Sub<BR>End Class"</P>
<P><BR>In the Immediate Window enter:</P>
<P>o = New With { .P = 1 }<BR>?o</P>
<P>&nbsp;</P>
<P><U>Expected</U>: Error unrecognized type</P>
<P>&nbsp;</P>
<P><U>Actual</U>: Debug.Assert() failure</P>
<P>&nbsp;&nbsp; at System.Diagnostics.TraceListener.Fail(String message)<BR>&nbsp;&nbsp; at System.Diagnostics.TraceInternal.Fail(String message)<BR>&nbsp;&nbsp; at System.Diagnostics.Debug.Assert(Boolean condition)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.EEMethodSymbol.GetBoundMethodBody(DiagnosticBag diagnostics, Binder&amp; methodBodyBinder) in C:\Roslyn\Main\Closed\ExpressionEvaluator\VisualBasic\Source\ExpressionCompiler\Symbols\EEMethodSymbol.vb:line 457<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileSynthesizedMethods(ImmutableArray`1 additionalTypes) in C:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Compilation\MethodCompiler.vb:line 809<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileMethodBodies(VisualBasicCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean generateDebugInfo, Boolean hasDeclarationErrors, Predicate`1 filter, DiagnosticBag diagnostics, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Compilation\MethodCompiler.vb:line 228<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean generateDebugInfo, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Compilation\VisualBasicCompilation.vb:line 2250<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean generateDebugInfo, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1246<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.CompilationContext.Compile(InspectionContext inspectionContext, String typeName, String methodName, CompilationTestData testData, DiagnosticBag diagnostics, ResultProperties&amp; resultProperties) in C:\Roslyn\Main\Closed\ExpressionEvaluator\VisualBasic\Source\ExpressionCompiler\CompilationContext.vb:line 150<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.EvaluationContext.CompileExpression(InspectionContext inspectionContext, String expr, DkmEvaluationFlags compilationFlags, DiagnosticFormatter formatter, ResultProperties&amp; resultProperties, String&amp; errorMessage, CultureInfo preferredUICulture, CompilationTestData testData) in C:\Roslyn\Main\Closed\ExpressionEvaluator\VisualBasic\Source\ExpressionCompiler\EvaluationContext.vb:line 328<BR>...</P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By Chuck Stoner (1/6/2015 5:52:07 PM)

------------------------------

2) Edited By Manish Jayaswal (2/20/2015 2:04:15 PM)

<p>We get a not so user friendly error message in the retail bits. Ideally we should give a better error message but this does not make the RC bar.</p>
<p>&nbsp;</p><font color="#1e1e1e" size=1 face=Consolas><font color="#1e1e1e" size=1 face=Consolas><font color="#1e1e1e" size=1 face=Consolas>
<p>(1) : error BC30657: '&lt;&gt;m0' has a return type that is not supported or parameter types that are not supported.</p></font></font></font>

------------------------------

**Comment by cston** [comment]
Does not repro with VS 2015 Update 1, and the unit test does not reflect the actual behavior where the type from the previous evaluation is available.
