### ISSUE TITLE
Bring back Go to Definition Navigation Stack

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#14496]
_[Issue on Microsoft Connect](http://connect.microsoft.com/VisualStudio/feedback/details/2011983/view-popbrowsecontext-command-and-others-doesnt-work)_

We cut the Go to Definition Navigation Stack as part of Roslyn in favor of the standard VS navigation stack that was made more prominent in VS 2012. There are a few requests to bring it back.

**Comment by rclabo** [comment]
I'm so glad to see this opened as a issue here. I'm limping along with View.NavigateBackward (Ctrl +-) but it's not nearly as efficient as View.PopBrowseContext.  When I use F12 to go to a definition I often have to use View.NavigateBackward (Ctrl +-) three or four times before I'm back to the place I hit F12.  

With View.PopBroweContext (Ctl + shift + 8) in prior versions of Visual Studio I only had to hit the keyboard combination ONCE and I was back to the place I used the F12. I sure how this gets fixed soon in Visual Studio 2015. It's a real productivity drain to not have View.PopBroweContext (Ctl + shift + 8) working.

**Comment by clambert** [comment]
View.PopBroweContext and Edit.GoToDefinition is used like a mental call stack when looking through source code. I will F12 to go to definition and then poke around then do another F12 so forth and so on and I use View.PopBrowseContext to get back to where I was originally. View.NavigateBackword could easily be over 30 operations before I need to get back to where I started. Also I may be switching between some sql statements I'm looking at and the source code while doing all of the above which using View.NavigateBackwords makes unbearable when I try to get back to where I was as well.

A better interim solution would be the ability to mark a line and then a hot key to jump back to that line later.

**Comment by Pilchie** [comment]
@clambert You can add bookmarks and cycle through them already - check out the Edit -> Bookmarks menu.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement in 8 years.
