### ISSUE TITLE
EncapsulateField integration tests failing on Dev15 due to changed keyboard shortcuts

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/roslyn#14499]
Both BasicEncapsulateField and CSharpEncapsulateField tests fail on Dev15 preview 5 due to the keyboard shortcut Ctrl+R, Ctrl+E not being bound to a command. This hangs the test.

**Comment by tmeschter** [comment]
These seem to run and succeed without modification now.

**Comment by Pilchie** [comment]
Moving to RTM, given the PR is against Master.
