### ISSUE TITLE
Fully-qualified path for Type defined in different Solution (cross solution project reference)

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#14493]
We are using Roslyn Compiler for generating a Dependency Graph for a given application code. The **application code can span across multiple solutions and can have references between the solutions** (ex. Service code in one solution, common business logic in another solution etc.)

For the purpose of generating the Dependency Graph, we would require fully-qualified name and exact path of all the custom types refereed (ones which we have created as our application code).

Roslyn happens to give this information using the SemanticModel's Symbol Information.

**Scenario which works**:
SemanticModel's Symbol Information gives the Location (path) and ContainingSymbol information for any Type if the type is declared in the same Solution (under some project) in which it is getting used.

**Scenario which does not work**:
If the refereed Type is not part of the current solution but is part of some other solution which is getting refereed in the existing solution, then the SemanticModel does not give any Symbol Information which can give the Path and Fully Qualified Name.

**Note**:
We have already tried using the variants of GetSpeculativeSymbolInfo and GetSpeculativeTypeInfo. But it does not give any information. It just mentions that its a part of MetaData (as if we are using a Type from .NET Class Lib).

//Sample Code for Testing

```
public class TestClass
{
    Student student = new Student();
    Person person = new Person();
}

public class Student
{
    public string Name { get; set; }
}
```

Notes:

TestClass is part of project Project_1 which is in Solution_1.
TestClass has two members: Class Student is part of project Project_2 which is in Solution_1 and Project_1 has a Project Reference to Project_2.
Class Person is part of project Project_XYZ which is in Solution_XYZ and Project1 from Solution_1 has a dll Reference to Project_XYZ from Solution Solution_XYZ.
The .dll of Project_XYZ is getting created at location "..\Projects\SourceCode\AllBinaries" and "Project_1" from Solution_1 refers the .dll of Project_XYZ from this location "..\Projects\SourceCode\AllBinaries"

Code for getting Symbol Information of the Type:

```
private void GetSymbolDetails(TypeSyntax typeSyntax)
{
    ISymbol symbol = semanticModel.GetSymbolInfo(typeSyntax).Symbol; 
   //HERE semanticModel = document.GetSemanticModelAsync().Result;
}
```

**Scenario which works**:
When the above code is called with input parameter as "IdentifierNameSyntax IdentifierName Student", the "symbol" gives all the required symbol details of "Student" (including fully-qualified name and exact path).

**Scenario which does not work**:
When the above code is called with input parameter as "IdentifierNameSyntax IdentifierName Person", the "symbol" value is null.

Looking forward to some pointers from the Experts.

**Comment by Pilchie** [comment]
How are you getting a document in the first place? In general, I would look at your `Compilation` object and see if it has any diagnostics.

**Comment by abhijitparkhi1983** [comment]
Hello @Pilchie, Thanks for your response. As of now, I dont directly deal with the Compilation.
As far as the Document is concerned, this is how we get to the document:

```
var workspace = MSBuildWorkspace.Create();
solution = workspace.OpenSolutionAsync(solutionPath).Result;

foreach (var project in solution.Projects)
{
     project.Documents.ToList().ForEach(ReadDocument);
}
```
Once we get a document from the above code, we do the following:
```
var decendendNodes = document.GetSyntaxRootAsync().Result;
var semantecModel = document.GetSemanticModelAsync().Result;
```
We pass the semantecModel to instance of **CSharpSyntaxWalker** class and finally we call **CSharpSyntaxWalker**'s `Visit(decendendNodes)`.

Hope I was able to give you required information. 
FYI: Instead of loading a document as text data, we directly use the Document object. So i am not sure how would a Compilation help here.

Looking forward to your valuable input.

**Comment by Pilchie** [comment]
Does `(await project.GetCompilationAsync()).GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error)` return anything?

**Comment by abhijitparkhi1983** [comment]
Hel

**Comment by abhijitparkhi1983** [comment]
Hello @Pilchie, sorry for coming late on this thread.

The above code gives 0 Diagnostic. 
Is there any thing else I need to check?

Looking forward to further help from the forum. I am clueless and stuck completely

**Comment by Pilchie** [comment]
At this point it's getting harder to psychic debug - any way you can share the projects involved?

**Comment by abhijitparkhi1983** [comment]
Hello @Pilchie, I am not sure what do mean by "getting harder to psychic debug".  Should I be giving some more information? 

The crux of the question is simple. In case where the application contains multiple solutions (which is a very regular case. Roslyn source code also has three solutions under it namely **Compilers.sln**, **CrossPlatform.sln** and **Roslyn.sln**), and when there are cross solution references (I am sure there are cross solution references in the above 3 solutions as well), how do we get the details of a Type refereed in one solution but defined in another. 

How do i share the project involved? Have never done it here on github? Is there any facility to share the project against this question?

**Comment by abhijitparkhi1983** [comment]
@Pilchie , looking forward to some insight from the @roslyn team on the above concern

**Comment by jcouv** [comment]
@abhijitparkhi1983 For sharing a repro, you could create a github repo for your project or make a zip file (host it on OneDrive, Google Drive or Dropbox), then copy the link here. The smaller the repro the better.

**Comment by thirstycreative** [comment]
@Pilchie Hello,
I my name is  Roslyn from Australian but I am not in the @roslyn team.
Wow I wish I could understand what you are working on.
Kindest,
Roslyn

**Comment by gafter** [comment]
@abhijitparkhi1983 I suspect that the compilation that contains the reference does not have a metadata reference to the compilation or assembly where the type is defined. Please provide is with a small, complete, self-contained program that uses Roslyn and illustrates the issue.
