### ISSUE TITLE
Type parameter should not switch to suggestion mode

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14492]
**Version Used**: 25807

**Steps to Reproduce**:

``` C#
namespace ConsoleApplication1
{
    class Program
    {
        class N { }
        static void Main(string[] args)
        {
            Program.N n = Load<Program.|
        }

        static T Load<T>() => default(T);
    }
}
```

**Expected Behavior**:
Completion mode for typing `Program.N` type parameter.

**Actual Behavior**:
Suggestion mode expecting lambda expression. I don't see how lambda would be appropriate at this place anyway.

![untitled](https://cloud.githubusercontent.com/assets/10546952/19349156/8e9201b6-9149-11e6-9df0-4bd6d59fd957.png)

I believe this is a regression.

**Comment by rchande** [comment]
The partially typed generic parses as a binary operator expression. The type inferrer tries to figure out what the expression on the right should return and returns the type of the left side which in this case happens to be System.Func`1 because of the `Load` method.
