### ISSUE TITLE
Allow inheriting existing structures to annotate them with custom attributes

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#145]
Consider this structure:

https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.vector2.aspx

How do I annotate it or its members with additional custom attributes of my choice?

This is a cross-language suggestion: I also want to be able to do this in F# (units of measure on third-party types) unless C# implements units of measure (which would be great).

**Comment by MadsTorgersen** [comment]
We'll consider proposals on this topic. Maybe reference assemblies play a role.
