### ISSUE TITLE
FindReferences and MiscellaneousFiles integrations test fail due to missing command Window.ActivateDocumentWindow

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/roslyn#14503]
The following integration tests fail on Dev15 preview 5:
- BasicFindReferences
- BasicMiscellaneousFiles
- CSharpFindReferences
- CSharpMiscellaneousFiles

with:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Command "Window.ActivateDocumentWindow" is not available.
   at EnvDTE._DTE.ExecuteCommand(String CommandName, String CommandArgs)
   at Roslyn.VSHosting.Test.RoslynInProcessAPI.<>c__DisplayClass111_0.<GetFindSymbolResults>b__0() in C:\Users\paulv\Documents\GitHub\roslyn-internal\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\Utilities\RoslynInProcessAPI.cs:line 859
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeByAction(Object[] values) in f:\dd\src\omni\Apex\Framework\Hosts\Services\UIThreadInvoker\UIThreadInvokerHelper.cs:line 118
   at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments) in f:\dd\src\omni\Apex\HostIntegration\VisualStudio\Services\Remote\VsUIThreadInvokerService.cs:line 87
```

**Comment by tmeschter** [comment]
Find References is now asynchronous, so the test as-written may try to switch to the results window before it has even shown up, or before any results have populated. This leaves us in some weird indeterminate state where subsequent commands don't work the way we expect.

I don't think we'll be able to get Find References working until we can merge https://github.com/dotnet/roslyn-internal/pull/1417. Since that references new functionality in Dev15, it in turn will need to wait until we're building against Dev15 binaries.

**Comment by sharwell** [comment]
@tmeschter Can this be closed now?

**Comment by tmeschter** [comment]
@sharwell If the tests pass, sure.

**Comment by tmeschter** [comment]
Or alternatively, if we don't expect any integration tests to be working right now.

**Comment by sharwell** [comment]
@tmeschter you sent a PR shown above to delete the tests. It was never merged so I was asking you to confirm the intent. :)

**Comment by CyrusNajmabadi** [comment]
These tests exist and are not skipped.  closing this out.
