### ISSUE TITLE
EE: Assert failure evaluating With statement

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#1450]
Ported from TFS WorkItem: <b>1105859</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P>F5 the following:</P>
<P>&nbsp;</P>
<P>Structure S<BR>&nbsp;&nbsp;&nbsp; Friend F As T<BR>End Structure<BR>Structure T<BR>End Structure<BR>Class C<BR>&nbsp;&nbsp;&nbsp; Shared Sub F(o As System.Action)<BR>&nbsp;&nbsp;&nbsp; End Sub<BR>&nbsp;&nbsp;&nbsp; Shared Sub Main()<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; System.Diagnostics.Debugger.Break()<BR>&nbsp;&nbsp;&nbsp; End Sub<BR>End Class</P>
<P><BR>Evaluate:</P>
<P>&nbsp;</P>
<P>F(Sub()<BR>&nbsp;&nbsp;&nbsp; Dim o = New S()<BR>&nbsp;&nbsp;&nbsp; With o<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .F = New T()<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; With .F<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End With<BR>&nbsp;&nbsp;&nbsp; End With<BR>End Sub)</P>
<P>&nbsp;</P>
<P><U>Result</U>: Assert failure:</P>
<P>&nbsp;&nbsp;System.Diagnostics.Debug.Assert(false) Line 100&nbsp;C#<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.CodeGen.StackScheduler.Rewriter.VisitReferenceAssignment({Microsoft.CodeAnalysis.VisualBasic.BoundReferenceAssignment}) Line 100&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundReferenceAssignment.Accept({Microsoft.CodeAnalysis.VisualBasic.CodeGen.StackScheduler.Rewriter}) Line 1653&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit({Microsoft.CodeAnalysis.VisualBasic.BoundReferenceAssignment}) Line 126&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.CodeGen.StackScheduler.Rewriter.Visit({Microsoft.CodeAnalysis.VisualBasic.BoundReferenceAssignment}) Line 48&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriter.VisitExpressionStatement({Microsoft.CodeAnalysis.VisualBasic.BoundExpressionStatement}) Line 12052&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundExpressionStatement.Accept({Microsoft.CodeAnalysis.VisualBasic.CodeGen.StackScheduler.Rewriter}) Line 4460&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit({Microsoft.CodeAnalysis.VisualBasic.BoundExpressionStatement}) Line 126&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.CodeGen.StackScheduler.Rewriter.Visit({Microsoft.CodeAnalysis.VisualBasic.BoundExpressionStatement}) Line 48&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriter.VisitList(Of Microsoft.CodeAnalysis.VisualBasic.BoundStatement)(Length = 4) Line 25&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriter.VisitBlock({Microsoft.CodeAnalysis.VisualBasic.BoundBlock}) Line 12003&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundBlock.Accept({Microsoft.CodeAnalysis.VisualBasic.CodeGen.StackScheduler.Rewriter}) Line 4039&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit({Microsoft.CodeAnalysis.VisualBasic.BoundBlock}) Line 126&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.CodeGen.StackScheduler.Rewriter.Visit({Microsoft.CodeAnalysis.VisualBasic.BoundBlock}) Line 48&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriter.VisitList(Of Microsoft.CodeAnalysis.VisualBasic.BoundStatement)(Length = 2) Line 25&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriter.VisitBlock({Microsoft.CodeAnalysis.VisualBasic.BoundBlock}) Line 12003&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundBlock.Accept({Microsoft.CodeAnalysis.VisualBasic.CodeGen.StackScheduler.Rewriter}) Line 4039&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit({Microsoft.CodeAnalysis.VisualBasic.BoundBlock}) Line 126&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.CodeGen.StackScheduler.Rewriter.Visit({Microsoft.CodeAnalysis.VisualBasic.BoundBlock}) Line 48&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriter.VisitList(Of Microsoft.CodeAnalysis.VisualBasic.BoundStatement)(Length = 3) Line 25&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriter.VisitBlock({Microsoft.CodeAnalysis.VisualBasic.BoundBlock}) Line 12003&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundBlock.Accept({Microsoft.CodeAnalysis.VisualBasic.CodeGen.StackScheduler.Rewriter}) Line 4039&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit({Microsoft.CodeAnalysis.VisualBasic.BoundBlock}) Line 126&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.CodeGen.StackScheduler.Rewriter.Visit({Microsoft.CodeAnalysis.VisualBasic.BoundBlock}) Line 48&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriter.VisitList(Of Microsoft.CodeAnalysis.VisualBasic.BoundStatement)(Length = 5) Line 25&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriter.VisitBlock({Microsoft.CodeAnalysis.VisualBasic.BoundBlock}) Line 12003&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundBlock.Accept({Microsoft.CodeAnalysis.VisualBasic.CodeGen.StackScheduler.Rewriter}) Line 4039&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit({Microsoft.CodeAnalysis.VisualBasic.BoundBlock}) Line 126&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.CodeGen.StackScheduler.Rewriter.Visit({Microsoft.CodeAnalysis.VisualBasic.BoundBlock}) Line 48&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.CodeGen.StackScheduler.Rewriter.Rewrite({Microsoft.CodeAnalysis.VisualBasic.BoundBlock}, Count = 1) Line 35&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.CodeGen.StackScheduler.OptimizeLocalsOut(Method Sub &lt;&gt;x._Closure$__._Lambda$__0-1(), {Microsoft.CodeAnalysis.VisualBasic.BoundBlock}, Count = 1) Line 24&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.CodeGen.Optimizer.Optimize(Method Sub &lt;&gt;x._Closure$__._Lambda$__0-1(), {Microsoft.CodeAnalysis.VisualBasic.BoundBlock}, Count = 1) Line 23&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.New(Method Sub &lt;&gt;x._Closure$__._Lambda$__0-1(), {Microsoft.CodeAnalysis.VisualBasic.BoundBlock}, An internal error has occurred while evaluating method Microsoft.CodeAnalysis.CodeGen.ILBuilder.GetDebuggerDisplay()., {Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.EEAssemblyBuilder}, Count = 0, OptimizationLevel.Release, False) Line 76&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.GenerateMethodBody({Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.EEAssemblyBuilder}, Method Sub &lt;&gt;x._Closure$__._Lambda$__0-1(), {Microsoft.CodeAnalysis.VisualBasic.BoundBlock}, Nothing, Nothing, Nothing, Count = 0, Uninitialized) Line 1479&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileSynthesizedMethods({Microsoft.CodeAnalysis.VisualBasic.TypeCompilationState}) Line 949&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileSynthesizedMethods(Length = 1) Line 931&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileMethodBodies({Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation}, {Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.EEAssemblyBuilder}, False, False, Nothing, Count = 0, IsCancellationRequested = False) Line 228&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.CompileImpl({Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.EEAssemblyBuilder}, Nothing, Nothing, False, Count = 0, Nothing, IsCancellationRequested = False) Line 2250&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.Compilation.Compile({Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.EEAssemblyBuilder}, null, null, false, Count = 0, null, IsCancellationRequested = false) Line 1246&nbsp;C#<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.CompilationContext.Compile("&lt;&gt;x", "&lt;&gt;m0", {Microsoft.CodeAnalysis.CodeGen.CompilationTestData}, Count = 0, {Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProperties}, {Microsoft.CodeAnalysis.ExpressionEvaluator.InspectionContextFactory.InspectionContextImpl}) Line 150&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.EvaluationContext.CompileExpression({Microsoft.CodeAnalysis.ExpressionEvaluator.InspectionContextFactory.InspectionContextImpl}, "F(Sub()" &amp; vbCrLf &amp; "Dim o = New S()" &amp; vbCrLf &amp; "&nbsp;&nbsp;&nbsp; With o" &amp; vbCrLf &amp; "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .F = New T()" &amp; vbCrLf &amp; "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; With .F" &amp; vbCrLf &amp; "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End With" &amp; vbCrLf &amp; "&nbsp;&nbsp;&nbsp; End With" &amp; vbCrLf &amp; "End Sub)", DkmEvaluationFlags.None, {Microsoft.CodeAnalysis.DiagnosticFormatter}, {Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProperties}, Nothing, Nothing, {Microsoft.CodeAnalysis.CodeGen.CompilationTestData}) Line 328&nbsp;Basic<BR>...</P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By Chuck Stoner (1/9/2015 4:26:04 PM)

------------------------------

2) Edited By Manish Jayaswal (3/20/2015 12:54:14 PM)

Is this a user scenario? Can we type multi line lambdas in watch or immediate window?

------------------------------

**Comment by cston** [comment]
Multi-line lambdas are not supported currently, but this will repro with the following:
F(Sub() If True Then Dim o = New S() : With o : .F = New T() : With .F : End With : End With)

**Comment by cston** [comment]
No longer repros. Enabled test in #9871.
