### ISSUE TITLE
StandardTextDocument constructor shouldn't force UI thread 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#14527]
https://github.com/dotnet/roslyn/commit/273c54e06afea14d9fe196aae7032bfa60bc0ef0#diff-051ec54efa102ae7059eb64118683be8R68 added invocation of GetItemId to the constructor of StandardTextDocument, which needs foreground thread access. This is invoked during AddSourceFile. For CPS, we plan to invoke this from background thread.

**Comment by Pilchie** [comment]
Do you have an alternate proposal?

**Comment by mavasani** [comment]
Can we pass in an optional itemId (or getItemId delegate) to AddFile? AbstractLegacyProject can invoke the current implementation and CPS project can pass default ItemId

**Comment by Pilchie** [comment]
@mavasani Just to be clear is this an issue for RC?

**Comment by mavasani** [comment]
@Pilchie Nope, right now we are still invoking all IWorkspaceProjectContext APIs from the UI thread in CPS. I caught this because I added one invocation from background thread and caught this assert.

**Comment by Pilchie** [comment]
Thanks - moving to RTM for now then.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We don't seem to have any of this code anymore.  Reopen if you feel differently @mavasani
