### ISSUE TITLE
Completion item filtering missing filters for snippets and keywords

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14528]
**Version Used**: 25807

**Steps to Reproduce**: Turn _Show completion item filters_ on and invoke the autocomplete dropdown.

**Expected Behavior**: The ability to view snippets only (or use the filters to hide them).

**Actual Behavior**: No such filter even when snippets are present in the list.

**Comment by Pilchie** [comment]
Tagging @CyrusNajmabadi @kuhlenh @markw-t @DustinCampbell 

We also don't have a filter for keywords.  I can't remember the thinking here though...

**Comment by CyrusNajmabadi** [comment]
Seems like a reasonably request.
