### ISSUE TITLE
NonFatalWatsons don't seem to be uploaded.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14534]
@jmarolf run into this on his box.  He got a NFW but his event viewer showed no watson bucket actually filed.

**Comment by Pilchie** [comment]
Tagging @heejaechang - are you familiar with the non-fatal watson code?

Also @tmeschter as reliability champ.

**Comment by heejaechang** [comment]
the one we currently have is port of old debugger watson code which rely on certain dll to be in VS that debugger team deploy.

we have now official API from performance team. 

we should do this issue.
https://github.com/dotnet/roslyn/issues/9368

**Comment by Pilchie** [comment]
I see that #9368 is assigned to @heejaechang for RC - @srivatsn @heejaechang is that likely to be done?  We really need to get this data to fix issues before RTM.
