### ISSUE TITLE
Splitting string literals in HTML uses wrong white space character

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14548]
**Version Used**: 25807

I am not sure whether this is a Roslyn issue or ASP.NET issue, but the split string literals option is under C# so I am filing it here. Let me know if I should file it over there, or if this is an unsupported scenario.

My white space settings are spaces for C# and tabs for HTML, both sized 4. This is the result as I was just typing the SQL command and hitting enter at each line before the quotes:

``` C#
 ➔  @{
 ➔   ➔  SqlCommand command = new SqlCommand("SELECT bla bla " +
 ➔   ➔   ➔  "INNER JOIN bla" +
•••"LEFT OUTER JOIN bla" +
•••"GROUP BY bla|");

 ➔   ➔  SqlDataReader ...
 ➔  }
```

I don't want to argue whether C# inside HTML should use C# settings or HTML settings (I was expecting tabs here, or perhaps whatever is used on the line being split), but 3 spaces (rather than 4) look wrong either way, like it was supposed to be 3 tabs.

**Comment by Pilchie** [comment]
@CyrusNajmabadi @jasonmalinowski is this an issue with the fix getting the options from the wrong place, or the new per-document options not  respecting projections properly?

**Comment by jasonmalinowski** [comment]
Perhaps both. The existing formatting system had the special backdoor interfaces for getting HTML-editor-specific formatting options which we haven't replaced with the new API yet.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/38832 .
