### ISSUE TITLE
IntelliSense preselects what I want 

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14542]
```C#
    class Program
    {
        class C
        {
            public int I;
            public bool B;
        }
        static void Main(string[] args)
        {
            int localI;
            bool localB;
            C c;

            c.| localI = 4; // aiming for c.I = localI = 4;
            localB = true;  //    and for c.B = localB = true;
        }
    }
```
And the thing indeed preselects `c.I` and `c.B` respectively. That's some serious _IntelliSense_, well played!

**Comment by Pilchie** [comment]
This is "target typing" implemented in https://github.com/dotnet/roslyn/issues/11729.  

Glad you like it - I'm pretty excited about it too.

Tagging @rchande @CyrusNajmabadi @DustinCampbell @kuhlenh @markw-t so they see this too.
