### ISSUE TITLE
Formatting invalid tuples + local function hangs 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#14559]
Consider the following code:

``` csharp
namespace ConsoleApplication
{
class Program
{
static void Main(string[] args)
{
(int a, i Test()
{

}
}
}
}
```

When pasted into the IDE this will cause a hang during formatting.  The formatting operation is cancelable and once canceled the IDE becomes usable again.

**Comment by agocke** [comment]
No longer repros in 2.0 RTM
