### ISSUE TITLE
[XAML] Explicitly opt into Roslyn functionality

### ISSUE THREAD

**Issue by mgoertz-msft** [dotnet/roslyn#14565]
XAML documents participated in too many incompatible language features. This caused many commands to be handled by Roslyn that should have been handled by Visual Studio. The fix is to opt out of RoslynContentType and explicitly opt into the features supported by XAML.

**Comment by Pilchie** [comment]
Should this be resolved now?

**Comment by Pilchie** [comment]
Closing based on #14566.
