### ISSUE TITLE
MSBuildWorkspace.OpenSolutionAsync(solutionPath).Result Exception while opening SignalR solution

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#14581]
**Version**: Latest Roslyn Version 1.3.2

**Steps to Reproduce**:
1. Run code : MSBuildWorkspace.OpenSolutionAsync(solutionPath).Result
2. Here **solutionPath** is the path to the "Microsoft.AspNet.SignalR.Mono.Mobile.sln" solution which in itself is part of the SignalR source code repository from Git.
3. Note: This is a mobile version of SignalR and the machine on which I am trying to run the above code has no prerequisites installed required for running a mobile/XAMRIN applications.

**Actual Behavior**:
When we execute about code the application throws following exception:
**{"The imported project \"C:\Program Files (x86)\MSBuild\Microsoft\WindowsPhone\v8.0\Microsoft.WindowsPhone.v8.0.Overrides.targets\" 
was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. 
C:\\SignalR\samples\Microsoft.AspNet.SignalR.Client.WP8.Samples\Microsoft.AspNet.SignalR.Client.WP8.Samples.csproj"}**

**Expected Behavior**:
I understand that this error is because the requires prerequisites is not installed but still the Expected Begavior should be such that instead of throwing the exception, the API OpenSolutionAsync should have some overloaded option which can suppress this error and still continue with loading other solution projects which are not dependent on these prerequisites.

**Scenario I am working on**:
I am trying to work with "CSharpSyntaxWalker" and using its Visitor's to visit each type of Visitor to create a Dependency Graph in the application.

**Note**: 
This utility in a long run will be sitting on some centralized server machine and will be generating Dependency Graph for all the C# applications organization wide. 
So technically installing all the prerequisite for every other application on that centralized server wont be possible. 

Is there any existing solution to this problem ?
Looking forward to hear from the experts.

**Comment by Pilchie** [comment]
@mattwar what do you think here?

**Comment by mattwar** [comment]
It is possible that we could log the exception instead of letting it flow out.

**Comment by abhijitparkhi1983** [comment]
@Pilchie and @mattwar 
Thanks for adding your responses on this thread. It would certainly be helpful if the exception is logged and the code still continues ahead.

**Comment by mattwar** [comment]
This has been fixed. These types of errors will no longer cause exceptions to be thrown. They are now logged via the Workspace.WorkspaceFailed event and are available via a new MSBuildWorkspace.Diagnostics property.
