### ISSUE TITLE
No default selection enter key behavior radio buttons on IntelliSense pages

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#14597]
**Steps to Reproduce**:
1. Go to Tools\Options\Text Editor\C#\IntelliSense (or VB).
2. Look at the "Enter key behavior" section

**Expected Behavior**:
One of the radio buttons should be selected.

**Actual Behavior**:
Nothing is selected

**Comment by CyrusNajmabadi** [comment]
Closing out as not repro.
