### ISSUE TITLE
Flaky unit test Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.ProjectCacheHostServiceFactoryTests.TestImplicitCacheMonitoring

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#14592]
See https://ci.dot.net/job/dotnet_roslyn/job/dev15-rc/job/windows_debug_unit32_prtest/63/

**Comment by dpoeschl** [comment]
FYI @333fred

**Comment by jaredpar** [comment]
Another instance https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/5176/

**Comment by Pilchie** [comment]
Hasn't failed in the last 1000 non-PR runs.  @jasonmalinowski is this another weakref test to look at?

**Comment by jasonmalinowski** [comment]
Probably. 😦

**Comment by tmat** [comment]
another case: https://ci.dot.net/job/dotnet_roslyn/job/dev15.4.x/job/windows_release_unit64_prtest/49/

**Comment by mavasani** [comment]
Another failure: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/9748/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces/ProjectCacheHostServiceFactoryTests/TestImplicitCacheMonitoring/

**Comment by gafter** [comment]
Removing "Urgency-Soon" as the test has been skipped in #23526.

**Comment by CyrusNajmabadi** [comment]
This test is gone.
