### ISSUE TITLE
Microsoft.Net.Compilers 2.0.0 package is no longer available on NuGet.org

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#14591]
The Microsoft.Net.Compilers 2.0.0 package was mistakenly pushed instead of 2.0.0-beta5.  The package was immediately unlisted.  However there are clearly still references to it in the wild which are being actively downloaded.  As such we’re taking the more extreme measure of deleting the package altogether.  If you’re one of the customers who ended up with this package please switch to 2.0.0-beta5.

https://www.nuget.org/packages/Microsoft.Net.Compilers/2.0.0-beta5

**Comment by 0xd4d** [comment]
Seems like `Microsoft.CodeAnalysis.VisualBasic` 2.0.0-beta5 hasn't been published: https://www.nuget.org/packages/Microsoft.CodeAnalysis.VisualBasic/

```
Error		NuGet Package restore failed for project ConsoleApplication44 for 'Microsoft.CodeAnalysis.VisualBasic (= 2.0.0-beta5)'.			0	
Error		Unable to resolve 'Microsoft.CodeAnalysis.VisualBasic (= 2.0.0-beta5)' for '.NETFramework,Version=v4.6'.			0	
```

- Create a C# project (.NET Framework 4.6)
- Add project.json below
- Restart Visual Studio
- Compile

```json
{
	"dependencies": {
		"Microsoft.CodeAnalysis.VisualBasic.Features": "2.0.0-beta5"
	},
	"frameworks": {
		"net46": {}
	},
	"runtimes": {
		"win": {}
	}
}
```
