### ISSUE TITLE
EnvDTE.CodeParameter.StartPoint and EndPoint causes exception for “ByVal ParamArray” parameters

### ISSUE THREAD

**Issue by carlos-j-quintero** [dotnet/roslyn#146]
See MS Connect Bug:
https://connect.microsoft.com/VisualStudio/feedback/details/1066180/envdte-codeparameter-startpoint-and-endpoint-causes-exception-for-byval-paramarray-parameters

**Comment by DustinCampbell** [comment]
Fixed with PR #488.
