### ISSUE TITLE
Insertion tool no longer producing "NO CHANGES" messages if there are no changes

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#14603]
This support was added in dotnet/roslyn-internal@46b00bfe2fd33daa0c2c9f9faab94dfa4ddbc747 to do "NO CHANGES" instead of an error if there are no changes to insert. It looks like that was recently broken, or isn't working in reasonable scenarios.

**Comment by VSadov** [comment]
looks like it works fine now. 
Could be caused by file sharing problem.

**Comment by jasonmalinowski** [comment]
@OmarTawfik Here's a tracking bug for what we observed earlier. It's working for some insertions but not others...

**Comment by OmarTawfik** [comment]
Happens on Roslyn, but not LUT. Debugging why.

**Comment by OmarTawfik** [comment]
@jasonmalinowski it is because of the tool set change. The tool fails because there isn't a newer build to insert, but still there is "a" change which is updating the tool set. It should be fixed when we update the tool set. Closing for now.

**Comment by jasonmalinowski** [comment]
@OmarTawfik But if/when we have to hold toolset insertions, we have the problem again, right?

**Comment by OmarTawfik** [comment]
Yes. If it is something frequent, then I'll fix it now.
