### ISSUE TITLE
GetDeclaredSymbol is not working for tuple names in tuple literals

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#14600]
GTD for   "greeting"  in IDE goes nowhere

``` cs
var tuple = (number: 5, greeting: "Hello");
```

When I debugged, I noticed that  `CSharpSemanticModel::GetDeclaredSymbolCore` just returns `null` - it does not have a case for the element name in a tuple literal. 

I think the expected behavior is to return the symbol for the tuple element defined by the literal.

As a result of this, many other scenarios like FAR, rename, etc may get confused. They seem to be able to trace element references to the declaration syntax, but declaration syntax itself refuses to bind to what it declares.

== Crash repro:

```cs
    class Program
    {
        static void Main(string[] args)
        {
            var x = (Program: 1, Bob: 2);

            var Alice = x.Program;                
        }

    }
```

Try renaming “Program” in the tuple literal to be “Main”   (Also notice clearly wrong colorization)

**Comment by VSadov** [comment]
My be causing bad behavior in https://github.com/dotnet/roslyn/issues/14116

**Comment by jasonmalinowski** [comment]
I hit this while testing highlight references as well as clicking references highlights the definition, but the definition itself doesn't highlight.

**Comment by jcouv** [comment]
Vlad found out there are crashes associated with this problem. Moving back to RTM.
