### ISSUE TITLE
[Proposal] Concurrent Block

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#14604]
# Concurrent Block

I'm thinking this along the lines of abstracting away the underlying machinery, so that the programmer can express that this section can be run concurrently. This proposal is for introduction of a new block construct in the C# and VB language, which permits code with the block to be run concurrently. 

``` C#
  T0 a;
  T1 b;

  concurrent
  {
    a = await PartA();
    b = await PartB();
  }
```

``` vb
  Dim a As T0
  Dim b As T1

  concurrent
    a = await PartA()
    b = await PartB()
  end concurrent
```

There will be some form of flow analysis to check the "lines" can be run concurrently. eg there have no interdependencies with each other. The result will be the same as if it was run consecutively. 

**Join Patterns**
Express the join pattern.

``` c#
winner = concurrent { a , b } when any;
results = concurrent { a , b } when all;
```

**target**
Have the ability to specify where the concurrent code should be executed, eg GPUCPU.

``` c#
winner = concurrent gpu { a , b } when any;
results = concurrent gpu { a , b } when all;
```

---

 The `ConcurrentBlock` is a indicating a pattern. How that pattern is implemented is handled by another component, let's call it a `PatternMaker`. The **PatternMaker** takes the code in the block _translates_ it into form that can be processed by the `Concurrency Target`, which is similar to how `async` blocks work.

``` c#
concurrent Task {} /* Transforms uses Task (possible Default) */
concurrent Thread {} /*  Transform uses Threads */
concurrent Process { } /* Transform uses Processes */
concurrent Fibres {} /* Transform uses Fibres */
concurrent GPU { } /* Transform use GPU concurrency */
```

**Comment by benaadams** [comment]
What would be the outcome of this?

Equivalent Result A
```csharp
var t1 = PartAAsync();
var t2 = PartBAsync();

a = await t1;
b = await t2;
```

Equivalent Result B
```csharp
var t1 = Task.Run(() => PartA());
var t2 = Task.Run(() => PartB());

a = await t1;
b = await t2;
```

Result A would start running `PartBAsync` when an await in `PartAAsync` was hit (and it's result was not completed) or when it completed if there were no awaits.
Result B would start running `PartA` & `PartB` simultaneously, though the `PartA` would have a slight latency on starting vs Result A.

**Comment by AdamSpeight2008** [comment]
@benaadams  They would run simultaneously as it in a concurrent block.

**Comment by benaadams** [comment]
So be the same as?
```csharp
T0 a;
T1 b;

Task<T0> t1 = Task.Run(() => PartA());
Task<T1> t2 = Task.Run(() => PartB());

a = await t1;
b = await t2;
```

**Comment by AdamSpeight2008** [comment]
yep
```vb
    Sub Main()
        Dim a As Double
        Dim b As String
        Dim q = Task.Run(Async Function()
                             Dim T0 = Task.Run(
                               Async Function()
                                   Await Task.Delay(2000)
                                   Return Math.PI
                               End Function
                                     )
                             Dim T1 = Task.Run(
                               Async Function()
                                   Await Task.Delay(2400)
                                   Return "Hello World!"
                               End Function
                                     )
                             a = Await T0
                             b = Await T1
                         End Function)
        q.Wait()
    End Sub
```

**Comment by HaloFour** [comment]
The `concurrent` block itself would block until all of the asynchronous operations have completed?

As for concurrent join patterns I think that extension methods on `ValueTuple<...>` would suffice:

```cs
public static class ValueTupleAsyncExtensions {
    public static TaskAwaiter<(T1, T2)> GetAwaiter<T1, T2>(this (Task<T1>, Task<T2>) tasks) {
        // join on the two tasks here
    }
}

var (a, b) = await (PartAAsync(), PartBAsync());
```

**Comment by AdamSpeight2008** [comment]
@HaloFour The `concurrent` would block until completion of all concurrent operations.

I do like the extension method idea. `await ( PartAAsync(), PartBAsync ).WhenAny()`

We would have to compare it against the array base approach.

**Comment by HaloFour** [comment]
@AdamSpeight2008 

> The `concurrent` would block until completion of all concurrent operations.

That would violate the principle of "async all the way".  How do you propose to avoid issues of deadlocking when one of those async methods might expect to be able to dispatch back to the now blocked thread?

**Comment by vbcodec** [comment]
Task.WaitAll

**Comment by AdamSpeight2008** [comment]
@HaloFour I don't see how this proposal *violates the principle of async all the way*. It currently to have an async function contain aspects which are executed concurrently (eg Parallel )

**Comment by HaloFour** [comment]
@AdamSpeight2008 

So you mean to use a `concurrent` block only within an `async` function?  And by "blocking" you mean that the coroutine would not resume until all of the `await`ed tasks have completed?  That wouldn't violate said principle, but that was not apparent from your example expanded code above.

However, I don't think such a `concurrent` block would be necessary.  It's pretty simple to start and `await` multiple tasks concurrently right now.  As illustrated above I think some simple extension methods could be used to expand on that to make for some nice syntax candy around joins.

**Comment by AdamSpeight2008** [comment]
[(Ported to VBLang)](https://github.com/dotnet/vblang/issues/22)
