### ISSUE TITLE
[Proposal] Deligation class

### ISSUE THREAD

**Issue by momijin** [dotnet/roslyn#1461]
### Problem

To use the delegation on various design patterns, we must write a lot of tedious code.
### Proposal

To introduce the delegation class in c#.
### Example

Class Z use a delegation to class A.

``` C#
class A
{
    public int Method1() { return 0; }
    public void Method2(int p) {}
    public void Method3(int p) {}
}

class Z : delegate A
{
    public void Set(A a) { base<A> = a; }
}
```

The delegation syntax is written like the inheritance syntax;
Above is expanded to:

``` C#
class Z
{
    private A _a;
    public int Method1() { return _a.Method1(); }
    public void Method2(int p) { _a.Method2(p); }
    public void Method3(int p) { _a.Method3(p); }

    public void Set(A a) { _a = a; }
}
```

Three methods are automatically generated by the compiler.

Next example is using with readonly and override keyword. You must set a delegation in constructor and you can change a method behavior.

``` C#
class Y : delegate readonly A
{
    public Y(A a) { base<A> = a; }
    public override int Method1() { return base<A>.Method1() + 1; }
}
```

Above is expanded to:

``` C#
class Y
{
    private readonly A _a;
    void Method2(int p) { _a.Method2(p); }
    public void Method3(int p) { _a.Method3(p); }

    public Y(A a) { _a = a; }
    public int Method1() { return _a.Method1() + 1; }
}
```

Next example is using two delegation classes. Class B has two conflict method names, so one is given an alias name, other is excluded.

``` C#
class B
{
    public int Method1() { return 10; }
    public void Method2(int p) {}
    public void Method3(string q) {}
}

class W : delegate A, delegate B
{
    uses
    {
        B { alias B_Method1 = Method1; exclude Method2; }   
    }
    public void Set(A a) { base<A> = a; }
    public void Set(B b) { base<B> = b; }
}
```

Above is expanded to:

``` C#
class W
{
    private A _a;
    public int Method1() { return _a.Method1(); }
    public void Method2(int p) { _a.Method2(p); }
    public void Method3(int p) { _a.Method3(p); }

    private B _b;
    public int B_Method1() { return _b.Method1(); }
    public void Method3(string q) { _b.Method3(q); }

    public void Set(A a) { _a = a; }
    public void Set(B b) { _b = b; }
}
```

Next example is using with inheritance. It is similar to the previous example.

``` C#
class U : A, delegate B
{
    uses
    {
        B { alias B_Method1 = Method1; exclude Method2; }   
    }
    public void Set(B b) { base<B> = b; }
}
```

Above is expanded to:

``` C#
class U : A
{
    private B _b;
    public int B_Method1() { return _b.Method1(); }
    public void Method3(string q) { _b.Method3(q); }

    public void Set(B b) { _b = b; }
}
```

I wish that this proposal makes C# better and it is useful for the people using C#.

**Comment by zgxnet** [comment]
This is actually a mixin.
See #60

**Comment by momijin** [comment]
@zgxnet

I read #60 interestingly very much. I wish that C# 7 will be added a mixin or a trait that has better supports of delegation.

Thank you for your kind comment.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

Traits, which are proposed at https://github.com/dotnet/csharplang/issues/52, can provide some of the requestion functionality but in a syntactically different form.
