### ISSUE TITLE
[Dicussion] String vs Tuple(Of Char+)

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#14620]
# String vs Tuple(of Char+)

Is there any performance benefits / deficits?

`( "P"c , "u"c , "b"c , "l"c , "i"c , "c"c )` vs `"Public"`

**Comment by svick** [comment]
I don't understand the question. In what situations could it make sense to use such tuple instead of `string`?

**Comment by AdamSpeight2008** [comment]
@svick 
Which uses less space? Are there situations where having a `ValueTypeString` eg below certain length?

**Comment by dsaf** [comment]
https://en.wikipedia.org/wiki/String_interning#Motivation

**Comment by gafter** [comment]
@AdamSpeight2008 There exist performance measurement tools that can help you to answer that question in the context of your particular application.
