### ISSUE TITLE
Where are dark theme color definitions?

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#1462]
I found the following class white defines classification colors for the Light theme.

https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/Classification/ClassificationTypeDefinitions.cs

How and/or where are the colors for the Dark theme defined?

**Comment by dpoeschl** [comment]
@sharwell The colors for other themes are not defined in or editable via Roslyn.sln. They defined along with the themed colors from some other VS features and then installed together as one pkgdef, so the code is in a more central location that is not open source.

Let us know if you've found a problem with one of the existing themed colors, or if there's something else you're trying to accomplish that's blocked by this.
