### ISSUE TITLE
Ensure all code style analyzers do not run on generated code

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#14638]
This bit us on Naming Styles and will probably hit again on other code styles unless we ensure they aren't running on generated code.

**Comment by dpoeschl** [comment]
See https://github.com/dotnet/roslyn/pull/14634/commits/21c20ac9944fc7100fac7d65f347abc2553733a5 for an example of how to fix this.

**Comment by CyrusNajmabadi** [comment]
Fixed with 5c9e97e54fa165b54220193ca47eb504f447d60f
