### ISSUE TITLE
debug assert in C# parser

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#14649]
**Version Used**: 
rc drop with current ml master built (roslyndev hive)

**Steps to Reproduce**:
1. open roslyn-internal in roslyndev with debug bit
2. turn on full solution analysis
3. wait for the assert to show up.

**Expected Behavior**:
no assert

**Actual Behavior**:
assert.

assert is this code
http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Parser/SyntaxParser.cs,1090

code that make assert to happen is this file
roslyn-internal\Open\src\Compilers\Server\VBCSCompilerTests\ClientConnectionTests.cs
http://source.roslyn.io/#Roslyn.Compilers.CompilerServer.UnitTests/ClientConnectionTests.cs,17

here are callstack

Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxParser.IsMakingProgress(ref int lastTokenOffset) Line 1090    C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseLambdaParameterList() Line 11186           C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseLambdaExpression() Line 11123           C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCastOrParenExpressionOrLambdaOrTuple(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.Precedence precedence) Line 10251 C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTerm(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.Precedence precedence) Line 9588   C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseSubExpressionCore(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.Precedence precedence) Line 9363   C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseSubExpression(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.Precedence precedence) Line 9291   C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseArgumentExpression(bool isIndexer) Line 9939        C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseArgumentList(out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken openToken, out Microsoft.CodeAnalysis.Syntax.InternalSyntax.SeparatedSyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ArgumentSyntax> arguments, out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken closeToken, Microsoft.CodeAnalysis.CSharp.SyntaxKind openKind, Microsoft.CodeAnalysis.CSharp.SyntaxKind closeKind) Line 9814                C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseParenthesizedArgumentList() Line 9769             C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParsePostFixExpression(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExpressionSyntax expr) Line 9652  C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTerm(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.Precedence precedence) Line 9624   C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseSubExpressionCore(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.Precedence precedence) Line 9363   C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseSubExpression(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.Precedence precedence) Line 9291   C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseExpressionCore() Line 9028             C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseExpressionStatement() Line 8999             C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatementNoDeclaration(bool allowAnyExpression) Line 6909   C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatementCore() Line 6728             C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatements(ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CSharpSyntaxNode previousNode, Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.StatementSyntax> statements, bool stopOnSwitchSections) Line 7384           C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseBlock(bool isMethodBody, bool isAccessorBody) Line 7324  C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseBlockAndExpressionBodiesWithSemicolon(out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BlockSyntax blockBody, out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ArrowExpressionClauseSyntax expressionBody, out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken semicolon, bool parseSemicolonAfterBlock, Microsoft.CodeAnalysis.CSharp.MessageID requestedExpressionBodyFeature) Line 2825 C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMethodDeclaration(Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.AttributeListSyntax> attributes, Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder modifiers, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.TypeSyntax type, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExplicitInterfaceSpecifierSyntax explicitInterfaceOpt, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken identifier, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.TypeParameterListSyntax typeParameterList) Line 3000      C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatement(Microsoft.CodeAnalysis.CSharp.SyntaxKind parentKind, string typeName) Line 2540 C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseClassOrStructOrInterfaceDeclaration(Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.AttributeListSyntax> attributes, Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder modifiers) Line 1645  C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTypeDeclaration(Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.AttributeListSyntax> attributes, Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder modifiers) Line 1575  C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatement(Microsoft.CodeAnalysis.CSharp.SyntaxKind parentKind, string typeName) Line 2388 C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken openBrace, ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.NamespaceBodyBuilder body, ref Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder initialBadNodes, Microsoft.CodeAnalysis.CSharp.SyntaxKind parentKind) Line 717 C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceDeclaration() Line 454                C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken openBrace, ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.NamespaceBodyBuilder body, ref Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder initialBadNodes, Microsoft.CodeAnalysis.CSharp.SyntaxKind parentKind) Line 600 C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnitCore() Line 359                C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseWithStackGuard<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax>(System.Func<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax> parseFunc, System.Func<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax> createEmptyNodeFunc) Line 387               C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnit() Line 342                C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(Microsoft.CodeAnalysis.Text.SourceText text, Microsoft.CodeAnalysis.CSharp.CSharpParseOptions options, string path, System.Threading.CancellationToken cancellationToken) Line 392         C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ParseSyntaxTree(Microsoft.CodeAnalysis.Text.SourceText text, Microsoft.CodeAnalysis.ParseOptions options, string path, System.Threading.CancellationToken cancellationToken) Line 1635       C#
Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CSharpSyntaxTreeFactoryService.ParseSyntaxTree(string fileName, Microsoft.CodeAnalysis.ParseOptions options, Microsoft.CodeAnalysis.Text.SourceText text, System.Threading.CancellationToken cancellationToken) Line 43 C#
Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.CreateTreeAndVersion(Roslyn.Utilities.ValueSource<Microsoft.CodeAnalysis.TextAndVersion> newTextSource, Microsoft.CodeAnalysis.ProjectId cacheKey, string filePath, Microsoft.CodeAnalysis.ParseOptions options, Microsoft.CodeAnalysis.Host.HostLanguageServices languageServices, Microsoft.CodeAnalysis.PreservationMode mode, Microsoft.CodeAnalysis.TextAndVersion textAndVersion, System.Threading.CancellationToken cancellationToken) Line 164              C#
Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.FullyParseTreeAsync(Roslyn.Utilities.ValueSource<Microsoft.CodeAnalysis.TextAndVersion> newTextSource, Microsoft.CodeAnalysis.ProjectId cacheKey, string filePath, Microsoft.CodeAnalysis.ParseOptions options, Microsoft.CodeAnalysis.Host.HostLanguageServices languageServices, Microsoft.CodeAnalysis.SolutionServices solutionServices, Microsoft.CodeAnalysis.PreservationMode mode, System.Threading.CancellationToken cancellationToken) Line 132              C#

**Comment by gafter** [comment]
@jcouv I think this is the assertion you added recently to track down this issue.

**Comment by 333fred** [comment]
Another repro of this bug in the Project System repo. Relevant lines:

* https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Build/LanguageServiceErrorListProviderTests.cs#L169
* https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Build/LanguageServiceErrorListProviderTests.cs#L183

#14852 fixes it when applied locally.

**Comment by jcouv** [comment]
Thanks @333fred for confirming. The fix (#14852) just went into master branch.
