### ISSUE TITLE
Roslyn in Dev15 should use MS.VS.Shell.Framework, not MS.VS.Shell.Immutable.*

### ISSUE THREAD

**Issue by IlyaBiryukov** [dotnet/roslyn#14652]
Version: _2.0.0-beta6-61010-02_,  commit 4cdc3d8b75cfc4a22d722338c9dafeccb80dc574.

**Steps to Reproduce**:
1. Start Visual Studio Dev15 Preview 5
2. Create a new C# or VB project

**Expected Behavior**:
VS does not load any _Microsoft.VisualStudio.Shell.Immutable.*_ modules. Roslyn assemblies for Dev15 reference _Microsoft.VisualStudio.Shell.Framework.dll_.

**Actual Behavior**:
VS loads _Microsoft.VisualStudio.Shell.Immutable.*.dll_ because Roslyn still references it.

**User Impact:**
Nothing is broken functionally.
However, loading MS.VS.Shell.Immutable.\* in VS is an unnecessary perf overhead. In Dev15 Preview5+ all types from _MS.VS.Shell.Immutable.*_ where moved to _Microsoft.VisualStudio.Shell.Framework_.  _TypeForwardedToAttribute_ were added to Immutables for run-time compatibility.

**Comment by tmat** [comment]
I think this is due to the fact that Roslyn depends on VS SDK v15.0.25604-preview4 which has Immutable.11 and 10 in its nuget dependencies. Seems like 15.0.25726-preview5 doesn have it anymore, so updating to the newer version should fix this.

@jasonmalinowski FYI

**Comment by jasonmalinowski** [comment]
@IlyaBiryukov: but that's a Dev15 thing, right? Code still targeting Dev14 has to use the older versions? FYI to @Pilchie and @tmeschter who are updating some of those references anyways.

**Comment by IlyaBiryukov** [comment]
Yep, it's Dev15 Preview5 and beyond. Dev14 still uses the older versions.

**Comment by IlyaBiryukov** [comment]
Yep, VSSDK 15.0.25726-Preview5 has the chanages. Please note that the latest _Microsoft.VSSDK.BuildTools_ package is version _15.0.25728-Preview5_.

**Comment by tmat** [comment]
@jasonmalinowski I have generated and publish the internal VS SDK packages with Preview5 bits (need them for interactive window). Not gonna update Roslyn though to make Jared's life easier. @tmeschter will follow up.

**Comment by tmat** [comment]
@IlyaBiryukov Why is Microsoft.VisualStudio.Settings.15 versioned differently than the rest of the SDK? ```15.0.25123-Dev15Preview```

**Comment by IlyaBiryukov** [comment]
@tmat, a good question for VS extensibility team. I'll ask them why it is so.

**Comment by tmeschter** [comment]
We're no longer loading these assemblies. I noticed, however, that the NuGet.SolutionRestoreManager assembly is.
