### ISSUE TITLE
Please make XmlDocumentationProvider public

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1465]
And the derived FileBased & Content versions, or factories thereof.

Without making these public, it's rather hard to create references that include documentation.

Or at least make [`IDocumentationProviderService`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Host/Documentation/IDocumentationProviderService.cs) public.

**Comment by sharwell** [comment]
I'm not quite sure what you're trying to do. Does [`ISymbol.GetDocumentationCommentXml`](https://github.com/dotnet/roslyn/blob/fa5f370ae8c3403bb1506ac334cb0369e0f6a666/src/Compilers/Core/Portable/Symbols/ISymbol.cs#L195) not work for your scenario?

**Comment by SLaks** [comment]
`ISymbol.GetDocumentationCommentXml` uses the MetadataReference's `DocumentationProvider`.

I'm asking to create a reference that has one.

**Comment by aelij** [comment]
I see this is marked up for grabs with a stale PR. Would anyone mind if I take this?

The PR deals with `XmlDocumentationProvider`. Is it okay if we also make `IDocumentationProviderService` public?
