### ISSUE TITLE
CPS capability check fails for dotnet core projects

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/roslyn#14673]
**Version Used**: d15prerel\25821.00, wpt\25818.00, d15prerel\25819.00
Workloads : dotnetcorepreview, visualstudioextensibility, nativedesktop, netweb

**Steps to Reproduce**:

1. Create a dotnet-core project
2. Try to detect whether project is CPS using the method described at https://github.com/Microsoft/VSProjectSystem/blob/master/doc/automation/detect_whether_a_project_is_a_CPS_project.md
3. 

**Expected Behavior**: The method should return true when project is cps based

**Actual Behavior**: Returns false

Same behavior happens when checking for "PackageReference" capability.

@srivatsn @basoundr @rrelyea

This will be a blocker for NuGet as we won't be able to add/remove/update references on a project correctly or even restore it correctly if we can't detect the kind of project is.

**Comment by rrelyea** [comment]
@rohit21agrawal worked with Lifeng and got unblocked.
can be closed now.
