### ISSUE TITLE
completion after new<SPACE> inserts unnecessary namespace when commit using '('

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn#14676]
**Version Used**: VS 2015 update 3

**Steps to Reproduce**:
1. paste the following code into a C# code file

``` csharp

namespace A
{
    class ClassA { }
}

namespace Test
{
    using A;
    void M()
    {
        ClassA a = new
    }
}
```
1. put caret after "new" then type <SPACE>
2. after completion list comes up, type '('

**Expected Behavior**:
`ClassA()` inserted

**Actual Behavior**:
sometimes `A.ClassA()` is inserted. then quick fix offers to simplify the namespace part.

If it does not repro, try delete A then retype A in `using A`, then try again.

**Comment by rchande** [comment]
Unable to repro on VS 15 RC. Can you let me know if it repros for you?

**Comment by jeremymeng** [comment]
Does not repro on VS 15 RC. Closing.
