### ISSUE TITLE
Quick fix for CS0650 (bad array declarator)

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14687]
Would be nice if CS0650 had a quick fix available, changing

``` C#
string paths[] = Directory.GetFiles(...);
int myarray[2];
```

into

``` C#
string[] paths = Directory.GetFiles(...);
int[] myarray = new int[2];
```

**Comment by CyrusNajmabadi** [comment]
We welcome PRs :)

**Comment by Neme12** [comment]
This is such an unusual thing to type if you know you're not writing C. I didn't expect there to be a specialized error message for this.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
