### ISSUE TITLE
"Inline temporary variable" does not replace all references

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#14681]
**Steps to Reproduce**:

``` csharp
var items = new List<string>(); 
string first = items[0]; // Inline temporary variable 'first'
first = first.ToUpper();
```

**Result**

``` csharp
var items = new List<string>();
string first = items[0]; // "Inline temporary variable" is available for 'first', but nothing changes when the refactoring is invoked
first = items[0].ToUpper();
```

**Expected Behavior**:
All references should be replaced.
**Actual Behavior**:
Only second reference is replaced.

**Comment by Pilchie** [comment]
In this case, we chose not to make the change, since it would already introduce an error.  Instead we just highlight the conflict in the preview window.

Can you elaborate on why you think this would be a better experience?

**Comment by JosefPihrt** [comment]
Expected result should look like this:
```csharp
var items = new List<string>();
items[0] = items[0].ToUpper();
```
This code contains no error.

**Comment by JosefPihrt** [comment]
When I apply refactoring "Introduce local for all occurrences of 'items[0]'" on this code:
```csharp
var items = new List<string>();
items[0] = items[0].ToUpper();
```
This is the result:
```csharp
var items = new List<string>();
var v = items[0];
v = v.ToUpper();
```
I would expect that "Inline temporary variable" will reverse "Introduce local for all occurrences of ...".

**Comment by Pilchie** [comment]
Thanks for poking again.  You are right that this should work.  I was thinking this was a conflict case, but it's not.  It's likely that the conflict detection code is what's going wrong though.
