### ISSUE TITLE
Out var scope vs extension methods

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#14694]
1. Case: user-defined literals requested. Answer: use extension methods #4971.
2. Case: inconsistent scoping suggested for `if-else` #12597, #12939. Answer: why not extension methods?

``` csharp
public void Before(string arg)
{
    if (!int.TryParse(arg, out int number))
        throw new ArgumentException();

    Console.WriteLine($"It's a number: {number}");
}
```

``` csharp
public void After(string arg)
{
    Guard.IsNumber(arg, out int number);

    Console.WriteLine($"It's a number: {number}");
}

public static class Guard
{
    public static void IsNumber(string arg, out int parsed)
    {
        if (!int.TryParse(arg, out int secondParsed))
            throw new ArgumentException();

        parsed = secondParsed;//Otherwise: "error CS0136: A local or parameter named 'parsed' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter."
    }
}
```

**Comment by svick** [comment]
BTW, you can simplify `Guard.IsNumber` to:

```c#
public static void IsNumber(string arg, out int parsed)
{
    if (!int.TryParse(arg, out parsed)) // not "out int parsed"
        throw new ArgumentException();
}
```

**Comment by svick** [comment]
I'm not sure this would be a good replacement:

1. Your `Guard.IsNumber` is not actually an extension method, so without Extension Everything (https://github.com/dotnet/roslyn/issues/11159), there might be lots of various `Guard` classes (though I guess `using static` could help with that?).
2. You have to write a method for each combination of method and exception or figure out a generic way of specifying them.
3. The only thing you can do is to throw an exception, not `return` or `break`, or do something else.

**Comment by dsaf** [comment]
@svick 
>BTW, you can simplify Guard.IsNumber to:

Ah, that's it - thanks!

> Your Guard.IsNumber is not actually an extension method, so without Extension Everything (#11159), there might be lots of various Guard classes (though I guess using static could help with that?).

I meant "helper" method.

> You have to write a method for each combination of method and exception or figure out a generic way of specifying them.

How likely is this to be a problem in practice? Besides I have a feeling that it's a good practice anyway.

> The only thing you can do is to throw an exception, not return or break, or do something else.

This is a good point.

**Comment by DavidArno** [comment]
I don't follow what you are proposing here as `Guard.IsNumber(arg, out int number);` still relies on the scope of `number` leaking out into the enclosing block.

**Comment by dsaf** [comment]
@DavidArno you are right, I should've used C# 6 for implementing the ```Guard.IsNumber```. My general point still stands though.

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
