### ISSUE TITLE
Nuget packages - Assemblies dependent on packages not listed inside .nuspec file

### ISSUE THREAD

**Issue by fengari** [dotnet/roslyn#1469]
Perhaps I'm missing something obvious here...

Checking the Microsoft.CodeAnalysis.dll assembly from the NuGet package with ildasm, it shows a lot of dependencies on assemblies like System.Runtime, System.IO, System.Reflection, System.Collections, etc. A lot of them.

This refers to the Microsoft.CodeAnalysis.dll found under lib/net45 in the installed package.

These dependencies will not be found on the machine, because the packages are not installed by NuGet, because they are not listed as dependencies in the Microsoft.CodeAnalysis.Common.nuspec file.

The nuspec file only lists Collections.Immutable and Reflection.Metadata as dependencies.

How is this supposed to work?

**Comment by Pilchie** [comment]
Historically, things like System.Runtime and the other references you mention are provided by the .NET framework. They are the contract assemblies that define Portable Class Libraries, and are also implemented as type forwarding facade assemblies in the full framework.  These dependencies are implicitly satisfied by the .NET framework you are targeting.
