### ISSUE TITLE
Proposal: Derived types in arguments of polymorphic functions

### ISSUE THREAD

**Issue by vbcodec** [dotnet/roslyn#14691]
```
Public Class Animal
    Public Name As String

    Public Overridable Sub CopyFrom(OtherAnimal As Animal)
    End Sub
End Class

Public Class Cat
    Inherits Animal

    Public Length As Integer

    Public Overrides Sub CopyFrom(OtherAnimal As Animal)
        Name = OtherAnimal.Name
        Length = CType(OtherAnimal, Cat).Length
    End Sub
End Class
```

Casting to Cat is bit uncomfortable, so better is to write

```
Public Class Cat
    Inherits Animal

    Public Length As Integer

    Public Overrides Sub CopyFrom(OtherAnimal As Cat)
        Name = OtherAnimal.Name
        Length = OtherAnimal.Length
    End Sub
End Class
```

Probably CLR won't allow to use different type as arguments, and such function must be compiled to

```
    Public Overrides Sub CopyFrom(OtherAnimal As Animal)
        If TypeOf OtherAnimal IsNot Cat Then Throw New Exception("Type error")
        Dim x As Cat = OtherAnimal
        Name = x.Name
        Length = x.Length
    End Sub
```

**Comment by svick** [comment]
I don't think it's a good idea to silently make a method call throw an exception. Also, such methods would violate Liskov substitution principle (the L in SOLID), I don't think a language feature should help you with that.

**Comment by HaloFour** [comment]
I agree with @svick, I think that having the derived type narrow the contract would lead to unexpected errors.

Now if you wanted to inverse the relationship and allow for contravariance of the arguments then I think that does make sense and would be supportable in the sam manner as covariant return types.  But I don't think that this would be a particularly common use case nor does it require a lot of code to accomplish today.

**Comment by orthoxerox** [comment]
Did you pick the class name [on purpose](https://archive.eiffel.com/doc/manuals/technology/typing/cat.html)? It's the biggest headache in Eiffel's type system.

**Comment by gafter** [comment]
Closing for lack of community support.  For any continuing discussion, please move to `vblang`.
