### ISSUE TITLE
EnvDTE.CodeFunction.FunctionKind causes exception for methods of classes with explicit interface implementation

### ISSUE THREAD

**Issue by carlos-j-quintero** [dotnet/roslyn#147]
See MS Connect issue:
https://connect.microsoft.com/VisualStudio/feedback/details/1066145/envdte-codefunction-functionkind-causes-exception-for-methods-of-classes-with-explicit-interface-implementation

**Comment by DustinCampbell** [comment]
Fixed with PR #488.
