### ISSUE TITLE
Indent Guides Appearing over Usings

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#14701]
On WPT/25818.00, I'm seeing the indent guides appear over the using statements, as shown below:

![image](https://cloud.githubusercontent.com/assets/2371880/19657498/4f83e8de-99d9-11e6-8e18-1de9c5f97312.png)

Tagging @dotnet/roslyn-ide.

**Comment by Pilchie** [comment]
Ugh.  @CyrusNajmabadi is this known?

**Comment by CyrusNajmabadi** [comment]
Have poked the editor team about this.  I believe POR is to have indent guides never draw in a column where there non-whitespace.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://devdiv.visualstudio.com/DevDiv/_git/a290117c-5a8a-40f7-bc2c-f14dbe3acf6d/commit/8cd3e2429224a785cd1e35dd70e23ae21a209893
