### ISSUE TITLE
Target typing on character deletion preselects wrong entry

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14704]
**Version Used**: 2.0.0.61020

**Steps to Reproduce**:
1.  Enable _Show completion list after a character is deleted_
   2.

``` C#
using System;
class Program
{
    static void Main(string[] args)
    {
        if (Environment|
    }
}
```
1. Backspace to `Environmen`

**Expected Behavior**:
`Environment` to be preselected.

**Actual Behavior**:
`Equals` is preselected

**Comment by miloush** [comment]
Forgot references: #14085 #14056 #14668
/cc @rchande

**Comment by rchande** [comment]
This is fixed in master. Thanks @miloush!
