### ISSUE TITLE
C# compiler is not working properly when called from root folder

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#14725]
**Version Used**: Microsoft (R) Visual C# Compiler version 2.0.0.60925

**Steps to Reproduce**:
1. Go to root folder (e.g. c:\ or /)
2. Compile any C# code with syntax error using full path to the file

C:>csc c:\temp\p.cs
Microsoft (R) Visual C# Compiler version 2.0.0.60925
Copyright (C) Microsoft Corporation. All rights reserved.

emp\p.cs(6,24): error CS1003: Syntax error, ',' expected

**Observe missing c:\t**

**Comment by jaredpar** [comment]
> and obviously it expects the directory structure to exist rather than creating it, not sure whether that's by design

That is by design.  The compiler doesn't do any folder management.  It simply writes output where it's instructed to write output.  It's the job of MSBuild to create the necessary folder structure.

**Comment by marek-safar** [comment]
I am removing the second issue as that's my typo and leaving only the original issue
