### ISSUE TITLE
Option to enforce code style automatically

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14749]
Not sure if this is part of #7071 but it would be great if either as another severity level or a different option I could set the IDE to enforce code styles during formatting and autoformatting, i.e. when `}` is typed or the format document/selection command is invoked.

So that for example all vars I type would turn into explicit types or all framework types would turn into built-in types etc. on the go.

**Comment by Pilchie** [comment]
This is what is intended by #7068.
