### ISSUE TITLE
Regression in delegate conversion

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#14744]
**Version Used**:  2.0.0.60925

**Steps to Reproduce**:

1. Compile following code

```
using System;

class Program
{
    static void Main(string[] args)
    {
    }

    public static void ProcessInApplicationTrust<TResult>(Func<TResult> func)
    {
        ProcessInApplicationTrust(delegate
        {           
        });
    }

    public static void ProcessInApplicationTrust(Action action)
    {
    }
}
```

**Expected Behavior**:

No error

**Actual Behavior**:

Program.cs(11,35,13,10): error CS0648: '' is a type not supported by the language

**Comment by gafter** [comment]
This appears to be a duplicate (i.e. a different symptom) of https://github.com/dotnet/roslyn/issues/14722, which is now fixed.
