### ISSUE TITLE
Enable parameter modifier on extension methods

### ISSUE THREAD

**Issue by zspitz** [dotnet/roslyn#14747]
**Version Used**: 
C# 6.0

**Steps to Reproduce**:
```
public static class StringExtensions1 {
    //Doesn't compile -- "The parameter modifier cannot be used with 'this'"
    public static void Fill(this ref string s) {
        if (s == null) {s="";}
    }
}
public static class StringExtensions2 {
    //Doesn't compile -- "Do not use 'System.Runtime.CompilerServices.ExtensionAttribute'. Use 'this' keyword instead"
    [Extension] public static void Fill(ref string s, int count) {
        if (s == null) {s="";}
    }
}
```

[Additional example with auto-initializing dictionary](http://stackoverflow.com/q/40264788/111794).

**Expected Behavior**:
Either syntax should compile and run.

**Actual Behavior**:
Neither syntax compiles.

**Comment by svick** [comment]
This is a duplicate of https://github.com/dotnet/roslyn/issues/165.

**Comment by zspitz** [comment]
@svick I don't know how I missed that.
