### ISSUE TITLE
Include actual prerequisites in our vsixmanifests

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#14768]
In #14741, I added `<Prerequisites>` sections to all of our vsixmanifests, but I only included the "Core Editor" piece.  We should think about the rest.

**Comment by Pilchie** [comment]
@jmarolf What do you think - are there any additional `<Prerequisites>` that we should add?

**Comment by jmarolf** [comment]
@Pilchie I would argue that for some component "Core Editor" is too much.  The expression elevator doesn't need it, for example, it just needs the VSIXInstaller.  In general everything depends on us.  I will take a pass at all of our dependencies and make sure they still make sense

**Comment by jmarolf** [comment]
@Pilchie Expression Evaluator technically has no dependencies that it doesn't deploy itself, like the compiler, so we could refactor this to have the closest to “no dependencies” possible.  There is no case where this refactoring benefits anyone today and it’s not a breaking change to change package dependencies later.

**Comment by Pilchie** [comment]
Looks like there is nothing to do here.
