### ISSUE TITLE
PropertyDeclarationSyntax.WithSemicolon should use consistent naming conventions

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#1476]
MethodDeclarationSyntax.WithSemicolonToken
vs.
PropertyDeclarationSyntax.WithSemicolon

Both methods should have the same name IMO.

**Comment by Pilchie** [comment]
Same as http://roslyn.codeplex.com/workitem/448

**Comment by VSadov** [comment]
@AnthonyDGreen , you might want to take a look at this.

**Comment by MattGertz** [comment]
Approved for next preview.
