### ISSUE TITLE
Alternative approach to introduction of variables into scope.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#14777]
There have a been a few raised voices that the current and suggested approach to how the new language features introduce variable into scope.  He is my considered approach.

---

**Default to nearest outer scope**

The variable being introduce should be to **nearest outer scope** by default.

``` c#
if( !(o is int i) )
{
 /* i is in scope and definitely not assigned */
 throw new ArgumentException("Not an int", nameof(o));
}
/* i is in scope and definitely assigned. */
```

It simplifies one of the initial use cases, and I think the most likely usage.

``` c#
int value;
if( int.TryParse( text , out value )
```

into 

``` c#
if( int.TryParse( text, out int value )
```

---

It is the more eccentric usage of localizing to the nearest inner scope (of this particular code block). eg the `then` and `else` blocks. That is cause of tension for the community. especially around where it is introduce in "patterns". I propose that in these cases the change from the default (nearest outer) should made explicit and require the coder to specify a change to the **nearest inner scope**.

For example a lightweight approach to this is by prefixing `~` on the variable identifier.

``` c#
if (o is int ~i)
{
  /* i is scope and definitely assigned */
}
/* i is not in scope. /*
```

``` c#
if( !(o is int ~i) )
{
  /* i is scope finitely not assigned */
}
else
{
 /* I is scope and definitely assigned */
}
/* i is not in scope. /*
```

---

Then there are the case where the coder would like the variable introduced in one of nearest blocks and not the other. Use case: Guards.

``` c#
if( !int.TryParst( text, value ) )
{
 /* value not in scope. */
}
else
{
 /* value is in scope and assigned */
}
```

In pattern I propose we borrow from VB.net and use `IsNot` to indicate the negation of the pattern.

``` c#
if (o isnot int ~i)
{
  /* i is scope  not assigned a new value*/
 /* also is an error as i is being reused for a variable declaration */
}
else
{
 /* i is scope and definitely assigned a value.*/
 /* also is an error as i is being reused for a variable declaration */
}
/* i is in scope. /*
```

This should be easier to read ( ie not missing the easily missed `!` at the start. ), and allow us to know that the usage of variable introduction could be different.

---

**When the variable identifier prior exists**

What about the case where the variable already exist prior the usage? 
With the default ( nearest outer scope) the variable is reused.

``` c#
int i;
...
if( !(o is int i) )
{
 /* i is in scope and definitely maybe assigned */
 throw new ArgumentException("Not an int", nameof(o));
}
/* i is in scope and definitely assigned. */
```

And in the nearest inner scope the variable can not reused and thus produces an compile-time error.
Forcing the coder to make a explicit choice, and either make scope outer or use a different variable identifier.

``` c#
int i;
...
if (o is int ~i)
{
  /* i is scope and definitely assigned */
 /*  also is and error as i is be reused for a variable declaration */
}
/* i is in scope. /*
```

``` c#
int i;
...
if (o isnot int ~i)
{
  /* i is scope  not assigned a new value*/
 /* also is an error as i is being reused for a variable declaration */
}
else
{
 /* i is scope and definitely assigned a value.*/
 /* also is an error as i is being reused for a variable declaration */
}
/* i is in scope. /*
```

if the type of `i` is incompatible with the one in the pattern, it is an error in all cases.

**Comment by miloush** [comment]
Interesting, I was under the impression that the two groups disagree on whether the variable should be in the outer scope in the first place.

Anyway, I am not a big fan of the `~i` syntax as `~` is already an operator for bitwise negation and sticking it in front of things that are not numbers looks strange and in front of numbers without that meaning confusing.

I agree that `(!(o is int))` is not the most beautiful construct, but you can also do `(o is int == false)`  which looks fine enough to me to not justify the addition of a new keyword, although I am probably not that opinionated on that one.

Overall I think it is not a good idea to have a syntax for directly changing scoping rules. It increases complexity of the language and makes it more difficult to read. Better to stick to one and get used to it. You might not even see the line that determines the scope in a part of the code you are looking at!

**Comment by AdamSpeight2008** [comment]
The use of the prefix (whatever it is), restricted to very specific cases.
That of "patterns" which could potential introduce a new variable. eg `out` 
It those specific case where the desired intent of scope should be explicitly declared. 

The use of '~' was merely a suggestion of prefix. Making the default nearest outer simplifies the use of  `out var`s in `TryParse` for example. Thus shouldn't change the meaning of existing code, a user / codefix could easily simplify those use case.

It is the constrained introduction of variable that is cause the headaches, as there are existing language patterns that do constrain scoping to nearest inner.
eg
```c#
using(var obj = new DisposableObject)
{
  /* obj is in scope */
}
/* obj is in scope */
```
partly because some also what to extend it to previously out scopeing constructs to allow constrained variable introduction. eg `switch` and `if .. else ...`

```c#
if( myobj is uint64 ~value ){ /* value is locally scoped and definitly assigned and of type UInt64 */   }
if( myobj is  int64 ~value ){ /* value is locally scoped and definitly assigned and of type  Int64 */   }
if( myobj is uint32 ~value ){ /* value is locally scoped and definitly assigned and of type UInt32 */   }
if( myobj is  int32 ~value ){ /* value is locally scoped and definitly assigned and of type  Int32 */   } 
if( myobj is uint16 ~value ){ /* value is locally scoped and definitly assigned and of type UInt16 */   }
if( myobj is  int16 ~value ){ /* value is locally scoped and definitly assigned and of type  Int16 */   } 
```
without the prefix ('~') it would be a compile-time error as value is not defined. If it was it still be an compile-time error, as the variable ('value') is targeted to have multiple possible types.

**Comment by miloush** [comment]
> (You probably meant `/* obj is NOT in scope */` outside of `using`)

I understand the problem you are trying to solve, and I personally tend to prefer strict scoping rules, i.e. no leakage to outer scope, so I can't disagree with you. You can also use extra pair of brackets in your example:
```C#
{ if( myobj is uint64 ~value ){ /* value is locally scoped and definitely assigned and of type UInt64 */   } }
{ if( myobj is  int64 ~value ){ /* value is locally scoped and definitely assigned and of type  Int64 */   } }
{ if( myobj is uint32 ~value ){ /* value is locally scoped and definitely assigned and of type UInt32 */   } }
{ if( myobj is  int32 ~value ){ /* value is locally scoped and definitely assigned and of type  Int32 */   } }
{ if( myobj is uint16 ~value ){ /* value is locally scoped and definitely assigned and of type UInt16 */   } }
{ if( myobj is  int16 ~value ){ /* value is locally scoped and definitely assigned and of type  Int16 */   } }
```

I just think that making scoping adjustable would bring more problems than it solves.

**Comment by DavidArno** [comment]
@miloush,
> Interesting, I was under the impression that the two groups disagree on whether the variable should be in the outer scope in the first place.

That is the key flaw to this proposal. I read "*The variable being introduce should be to nearest outer scope by default.*" and completely disagreed. I feel if such a feature were introduced, then any `out/is var`'s should not leak at all by default and should require explicit leaking via a keyword or symbol if that's what's wanted.

So, reluctantly, I think you are right that "*Overall I think it is not a good idea to have a syntax for directly changing scoping rules ... Better to stick to one and get used to it*". I don't like the new scope leakage rules and think them a massive mistake for many many reasons, but the language team have picked them as their preferred solution and won't back down, so we all need to now move on and live with them.

**Comment by AdamSpeight2008** [comment]
@DavidArno _"The variable being introduce should be to nearest outer scope by default."_
Would allow existing patterns to be simplified and still maintain semantics.

eg **Guards**
```C#
T M( String text )  
{
  if( !Decimal.TryParse( text, value ) throw new someexecption();
  /* value is in scope and assigned */
  ...
}
```

The following code 
```c#
/* preface code */
if(o is int ~i){  /* i is in scope and maybe assigned */ }
else {   /* i is in scope and not assigned */  }
/* i is not in scope */
/* postscript code */
```
would translate into
```c#
/* preface code */
  {
    int i;
    if( o is int i ) { /* i is in scope and assigned */ }
    else { /* i is in scope and not assigned
  }
 /* i is not in scope */
/* postscript code*/
```
And the following
```c#
/* preface code */
if(o is int i){  /* i is in scope and assigned  }
else { /* i is in scope and not assigned }
/* i is in scope and maybe assigned */
/* postscript code */
```
into
```c#
/* preface code */
  int i;
  if( o is int i ) { /* i is in scope and assigned */ }
  else { /* i is in scope and not assigned
 /* i is in scope and maybe assigned */
/* postscript code*/
```

**Comment by DavidArno** [comment]
@AdamSpeight2008,
> This proposal is only for the places in code where variable have the potential to be introduced into scope. Specifically out parameters and patterns and not a proposal to change variable declarations.

Yep, I get that. The bit I disagree with is that `out/is var`'s should leak out into the outer scope by default, ie I'd go for the total opposite of your proposal, requiring explicit request for leakage into the outer scope, with non-leakage the default.

But I agree with @miloush that having the two systems, regardless of which is the default, will likely lead to even more confusion and bugs than the scope leakage solution itself will. So we are better off just accepting that `out/is var` scope leakage is here to stay.

**Comment by AdamSpeight2008** [comment]
Think that this is partially due to the use of `enclosing` and `enclosed` in respect to the scope. 
To me `enclosing -> nearest outer scope` and `enclosed -> nearest inner scope`.
