### ISSUE TITLE
SemanticModel.GetTypeInfo does not work with ExpressionStatements

### ISSUE THREAD

**Issue by Inspyro** [dotnet/roslyn#1477]
Hi, I'm trying to get the type info from an expression in a method body, specifically the c# code  looks like this:

```csharp
namespace NamespaceA
{
   class ClassA 
   { 
      void MethodA(NamespaceB.ClassB classB) 
      {
        new NamespaceB.ClassB(); 
      }
   }
}

namespace NamespaceB
{
  class ClassB {}
}
```

When calling **SemanticModel.GetTypeInfo** for the **first QualifiedNameSyntax** (the MethodA *parameter NamespaceB.ClassB*) the **correct type info** is returned

When calling **SemanticModel.GetTypeInfo** for the **second QualifiedNameSyntax** (the MethodA body statement *new NamespaceB.ClassB*) a type info with **type = null** is returned.

Is this behaviour expected? I would guess this is a bug. 

In order to reproduce the issue you can use the following c# code:
```csharp
internal class Program
  {
    private static Document ToDocument(string sourceCode)
    {
      var workspace = new AdhocWorkspace();
      var project = workspace.AddProject ("TestProject", LanguageNames.CSharp);
      return project.AddDocument ("SomeFile", sourceCode);
    }


    private static IEnumerable<TypeInfo> ExtractQualifiedName(Document document)
    {
      var syntaxTree = document.GetSyntaxTreeAsync().Result;
      var semanticModel = document.GetSemanticModelAsync().Result;

      var nodes=syntaxTree.GetRoot().DescendantNodes().OfType<QualifiedNameSyntax>();
      return nodes.Select(node=>semanticModel.GetTypeInfo (node));
    }

    private static void Main ()
    {
       var qualifiedNames= ExtractQualifiedName(ToDocument(@"
namespace NamespaceA
{
   class ClassA 
   { 
      void MethodA(NamespaceB.ClassB classB) 
      {
        new NamespaceB.ClassB(); 
      }
   }
}

namespace NamespaceB
{
  class ClassB {}
}"));

      //NOTE: Result NamespaceB.ClassB;null -- why is the second typeinfo.type=null?
      Console.WriteLine ("Result:" + ToViewableString(qualifiedNames));
      Console.ReadKey();
    }

    private static string ToViewableString(IEnumerable<TypeInfo> typeInfos)
    {
      return string.Join (";", typeInfos.Select (r => r.Type==null?"null":r.Type.ToString()));
    }
  }
```

**Comment by erik-kallen** [comment]
I think the method is to be called on the embedded expression instead; statements don't have a type.

**Comment by fschmied** [comment]
@erik-kallen Actually, the method is already being called for QualifiedNameSyntax nodes (i.e., the "NamespaceB.ClassB" part) in the sample, not for the surrounding statement. Shouldn't it work the same way in both cases?

**Comment by theoy** [comment]
@AnthonyDGreen - do you want to take first look at this API usage?

**Comment by AnthonyDGreen** [comment]
The bug is actually that's it's not returning null for the first qualified name. GetSymbolInfo is what should be used there. GetTypeInfo is specifically for getting the type of an _expression_ classified as a value. Type expressions like NamespaceB.ClassB aren't values and don't have types. Likewise statements should not return any TypeInfo.
