### ISSUE TITLE
We need to rewrite the Lambda Rewriter

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#14796]
It's just become too difficult to work in -- there are too many dictionaries with many possibly overlapping keys and values.

There are a few concrete changes I want to make:

1.  Remove LambdaRewriter.Analysis.RemoveUnneededReferences. This function loops over the capture analysis that was just completed and filters out things that are considered "unneeded" for closure creation. Then, the analysis is rewritten with these things removed. This has created situations where important information was dropped because it was considered unneeded for that particular analysis, but a subsequent analysis wanted the full information.
2. Stop using dictionaries for everything. All capture analysis is implicitly a consideration of scopes. Scopes form a tree. Our data structure for scope analysis should also be a tree. If we simply walked the tree of scopes and created a frame containing the captured variables for each scope we could have a much more readable rewriting pass. In addition, it would be much easier to perform invariant checking and optimizations on this structure than on our dictionaries.
3. Split out frame allocation from lowering. Right now we only create frames right before we lower the code, which is why local function call rewriting must happen in a second pass, since we may see a forward call to a local function that hasn't been lowered yet, so we don't know it's lowered target. If we allocated frames ahead of time based on scopes and captured variables we could do all body rewriting in a single visitation.

**Comment by tmat** [comment]
I'd add that it would be nice if we could unify C# and VB a bit.

**Comment by VSadov** [comment]
@tmat  - C# and VB are fairly unified here, although there are necessary differences due to locals having different lifetimes.
We should definitely not let this code diverge without need though. Completely agree with that.
