### ISSUE TITLE
EnvDTE.CodeClass.Members collection doesn’t include code elements for “Declare” methods of VB.NET class

### ISSUE THREAD

**Issue by carlos-j-quintero** [dotnet/roslyn#148]
See MS Connect bug:
https://connect.microsoft.com/VisualStudio/feedback/details/1071220/envdte-codeclass-members-collection-doesnt-include-code-elements-for-declare-methods-of-vb-net-class

**Comment by DustinCampbell** [comment]
Fixed with PR #488.
