### ISSUE TITLE
Autocomplete does not preselect enums in overloads

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14813]
**Version Used**: 2.0.0.61025

**Steps to Reproduce**:

``` C#
DateTime.Parse(null, CultureInfo.GetCultureInfo("ta"), |
```

**Expected Behavior**: `DateTimeStyles` to be preselected, so that dot can be pressed to commit.

**Actual Behavior**:
Last committed item is suggested, i.e. 
when `using System.Globalization;` is already present: `CultureInfo` is suggested
when the using is added using quick fix during typing, `null` is suggested

**Comment by Pilchie** [comment]
Pulling back into RC2.  Also - this looks more common than just being about overloads.

**Comment by rchande** [comment]
This is resolved in RC2.
