### ISSUE TITLE
Autocomplete filters Alt+ shortcuts interference

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14811]
Wanted to point out (sice I have run into this twice already) that the Alt+ keyboard shortcuts for filters in autocompletion list interfere with shortcuts for menus, i.e. you cannot open top level menus when the list is open. In English, that's E (enums vs Edit), V (events vs View), P (properties vs Project), D (delegates vs Debug), N (namespaces vs Analyze), and T (snippets vs Tools).

I see there is no easy solution, but wondered whether there were any other ideas on the table?

**Comment by CyrusNajmabadi** [comment]
This was discussed and was considered an acceptable tradeoff.  The thought was that the amount of times people would be wanting to open top level menus *while* intellisense was open would be suitably low.  We wanted very easy keystrokes for the completion filters, and that led us to this design.

**Comment by miloush** [comment]
Thanks. If I remember correctly the only menu item I ever wanted to open while intellisense was open was Tools to go to options, because something with the intellisense wasn't the way I wanted. Unfortunately no other letter from 'snippets' is free and one of the reasons to go to Tools was because I haven't seen the snippets I was looking for in the first place. However, I agree that all these are one-time problems and do not interfere once you are set up.
