### ISSUE TITLE
[Proposal] Color for User Types - Structures within the Dark theme

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#1482]
Much of the recent work on Microsoft projects related to performance involves considering the use of value types for their performance advantage when it makes sense. However, value types have substantially different semantics than classes. I believe it makes sense to alter the color for value types to distinguish them from reference types, provided it can be done without interfering with developers.

Without altering any of the other colors in the default Dark theme for C# code, I found the color 9ECEDC particularly usable on the following fronts:
1. It is distinguished from other colors used for types within this theme.
2. It is not easily mistaken with the color used for keywords.

I recommend making this the default value for this setting for new installations. The following image shows what this color looks like in some code for a Roslyn diagnostic analyzer:

![image](https://cloud.githubusercontent.com/assets/1408396/6785799/e9f083e4-d155-11e4-81b1-dc8e23fa68b7.png)

**Comment by Pilchie** [comment]
What do you think?  If we are going to change the default, we should probably do both the light and dark theme.

**Comment by DustinCampbell** [comment]
This is something I wanted when the original dark theme was created. After all, I had my own dark theme that colored value types and interfaces differently.

**Comment by sharwell** [comment]
@Pilchie While I am not opposed to that, I did not include a recommendation for other themes for the following reasons:

1. The light theme does not currently distinguish between type kinds. The dark theme already distinguishes interfaces, enums, and type parameters from the others.
2. The choice of color needs to be evaluated for its potential to be confused with other standard colors. Since I do not spend a large amount of time in any theme but the Dark theme, I could not be sure the recommendation would have the intended result.

**Comment by DustinCampbell** [comment]
I think it's probably unlikely that we'll do this for RTM.

**Comment by JoeRobich** [comment]
Closing as Structures were given a unique Dark theme color starting in VS 2019.
