### ISSUE TITLE
Cannot find API detailed documentation

### ISSUE THREAD

**Issue by mrolle45** [dotnet/roslyn#14820]
**Version Used**: N/A

**Steps to Reproduce**:
1. 
2. 
3. 

**Expected Behavior**:I want to find documents about how to use this project or the programs built from it.
In particular, I want to use the Microsoft.DiaSymReader.Native package on NuGet.
In fact, I'd like to be able make general inquiries such as this to the appropriate place.  It doesn't seem that this is an issue with the product itself.

**Actual Behavior**:

**Comment by gafter** [comment]
@tmat Can you please field this question? Where are docs and/or samples for `DiaSymReader.Native`?

**Comment by tmat** [comment]
The best place to start is https://github.com/dotnet/symreader. 

(We should update the link on nuget to point to that repo.)
