### ISSUE TITLE
MetadataReader: How to retrieve property or method return type?

### ISSUE THREAD

**Issue by raffaeler** [dotnet/roslyn#14823]
**Version Used**:  1.3.2
**Steps to Reproduce**: N/A

I can successfully obtain the PropertyDefinition or the MethodDefinition but yet don't know how to obtain the return type (TypeDefinition or TypeReference).

Can someone point me to the right direction? (I need to use the Metadata API only)
Thank you

**Comment by gafter** [comment]
@tmat Can you please field this question about the metadata reader API?

**Comment by raffaeler** [comment]
BTW I just retrieved the return type by *manually* decoding the BlobHandle of the signature with the help of the ECMA-335 specs.

I can see the MetadataDecoder already exists in the source code, but I can't see a public entry point.
Manual decoding is risky since there could be multiple use-cases where the stream length can change and cause a fault in my code.

TIA

**Comment by tmat** [comment]
You can use ```MethodDefinition.DecodeSignature``` and ```PropertyDefinition.DecodeSignature```: https://source.dot.net/#System.Reflection.Metadata/System/Reflection/Metadata/TypeSystem/MethodDefinition.cs,67.

Note that these methods are only available since version 1.4.1.

**Comment by raffaeler** [comment]
This explains why I couldn't see in the most obvious place :)

I can't see any packaged stable version post 1.3.2.
Am I missing something?
Should I wait for the final 2.0 which is currently in beta?

Thanks

**Comment by tmat** [comment]
System.Reflection.Metadata is a separate package - the library is included in Roslyn distro but also available as a separate nuget. Pre-release versions are available on myget: https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Reflection.Metadata.

**Comment by raffaeler** [comment]
Got it, but unfortunately I will have to wait for the release bits due to internal customer requirements.
Thanks!

**Comment by BillHenning** [comment]
Hello, sorry to reopen this but I'm attempting to use System.Reflection.Metadata to learn about the public API surface of an assembly and I am hitting stumbling blocks trying to determine method return types.  I am able to get to the MethodDefinition of methods for a TypeDefinition fine.  

While MethodDefinition does have methods like GetParameters(), I don't see anything for GetReturnType().  I'm curious why there is no get return type method.  

Anyhow, I have been searching the web but the only thing I find are references like this to having to possibly use DecodeSignature().  That being said, I haven't yet found a real world example of how to use it.  Can someone provide some guidance of how that method should be called, before it takes certain arguments and I'm not sure what to provide for them.

The main goal here is to just get an EntityHandle to the return type of the method as easily as possible.  I'd really appreciate any help I can get such as from @tmat since I'm stuck here.  Thanks!

**Comment by tmat** [comment]
@BillHenning GetParameters() returns parameter metadata (such as names), but not their types -- that's how the underlying metadata is structured. The return type as well as types of all parameters are encoded in the method signature blob. 

You can find an example of signature decoding code here:
https://github.com/dotnet/metadata-tools/blob/master/src/Microsoft.Metadata.Visualizer/MetadataVisualizer.cs#L419
and
https://github.com/dotnet/metadata-tools/blob/master/src/Microsoft.Metadata.Visualizer/MetadataVisualizer.SignatureVisualizer.cs

**Comment by tmat** [comment]
@BillHenning BTW, You won't be able to get a simple EntityHandle. The type signature can be much more complex than a simple handle. What are you trying to do on high level?

**Comment by BillHenning** [comment]
@tmat - My company has a syntax highlighting editor control named SyntaxEditor that we produce for various MS platforms like WPF, UWP, etc.  We have a syntax language add-on that supports advanced C#/VB editing with automated Intellisense.  It basically allows anyone making an app to drop our control in and instantly have a code editor like the VS one right in their app.

Our add-on currently uses .NET reflection to load up and store/cache metadata information about assemblies.  While that works fine in general, one problem is that it then locks the assembly that was read.  Or other times, dependent assemblies aren't found properly, etc.  My goal here is to have another optional way using Roslyn's assembly metadata reading functionality to be able to load up .NET assemblies and basically do "reflection" on them to gather all the info we need to support automated Intellisense in our code editor. 

I currently have a reader implementation gathering TypeDefinition data pretty well and am just getting into type members.  That's where I'm running into the issue of needing to know how to decode signatures.  So like for methods, I need to know what the return type is (even in special cases where it might be a constructed generic type, array, etc.) and same for parameter types.

I'll try to check out the links you sent tomorrow.  If you have any other suggestions that might help, please send them over.  Thanks!
