### ISSUE TITLE
Suggestion - Editor - Auto-complete of overridden properties

### ISSUE THREAD

**Issue by ahowroyd** [dotnet/roslyn#14838]
Love the new one line property getter syntax....  

public override int Test => 7;

It would by super nice if the 'override' autocomplete had a way to know that the user wants to use the short syntax rather than the full form.  (otherwise the user is left deleting several lines after each use).

One suggestion might be for '=' key or space bar to be intercepted as an alternative to enter during auto-complete - that would just autocomplete the name and signature, but not create the block. 

Problems with the suggestion to used an alternate key include (needs more thought)
 - This would probably be a little quirky (hard to discover feature)
-  Using the space bar as the auto complete char would have the secondary issue that after typing 'override T' + space, the editor can't know that T wasn't the name of a type and the user still intends to put the property name next.

In any case, just a suggestion....

**Comment by Pilchie** [comment]
@CyrusNajmabadi This is handled by your PR for expression bodied member support, right?

**Comment by CyrusNajmabadi** [comment]
Yes.  We will now honor the user choice here.

**Comment by Pilchie** [comment]
@ahowroyd see https://github.com/dotnet/roslyn/pull/14399 - it was just too late to catch the next release of VS "15", but it will be in the one after that.
