### ISSUE TITLE
Unify roslyn-bot and vslsnap accounts and upgrade security

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#14842]
Right now roslyn-bot and vslsnap both exist, and we only need one. We also should look at moving them over to deploy keys or something a bit newer.

**Comment by nguerrera** [comment]
We're going to retire both accounts and use dotnet-bot.

**Comment by nguerrera** [comment]
Status: roslyn-bot is eliminated. The account hasn't been deleted, but it's been removed from the dotnet org and has no priviliges higher than any external account. It can probably be deleted.

vslsnap has not yet been replaced by dotnet-bot,
