### ISSUE TITLE
Microsoft.Net.Compilers.nuspec authoring may be incorrect for RC

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#14857]
The authoring here: https://github.com/dotnet/roslyn/blob/dev15-rc/src/NuGet/Microsoft.Net.Compilers.nuspec

Seems to have most facades included, but it is missing System.ValueTuple.dll, which may be necessary for csi.exe.

**Comment by jaredpar** [comment]
@tmat it looks like the NuSpec wasn't updated when you took a depnedency on ValueTuple.

**Comment by tmat** [comment]
Is it not gonna be fixed by https://github.com/dotnet/roslyn/pull/14859?

**Comment by jaredpar** [comment]
That is for master only.  Change is too destructive for RC.  

Should be possible to grab the resulting nuspec though and port it directly to RC

**Comment by MattGertz** [comment]
Leave a comment
