### ISSUE TITLE
Roslyn fails to load analyzer dependency assemblies

### ISSUE THREAD

**Issue by alexperovich** [dotnet/roslyn#14866]
**Version Used**: 2.0.0-beta3

**Steps to Reproduce**:

1. sync to dotnet/corefx master
2. Replace BuildToolsVersion.txt with the following:

> 1.0.27-prerelease-01001-03	

3. run init-tools.cmd
4. touch foo.cs
5. run csc using `Tools/dotnetcli/dotnet.exe Tools/csc.exe` with the following commands:

> /target:library
/out:foo.dll
/analyzer:Tools/analyzers/Desktop.CSharp.Analyzers.dll
foo.cs

**Expected Behavior**:
binary foo.dll is produced with no warnings

**Actual Behavior**:
The analyzer fails to load due to missing dependencies. The specific dependency is Desktop.Analyzers.dll

**Comment by srivatsn** [comment]
You'll have to pass in all dependencies of an analyzer as input to the compiler. In this case there should be another /analyzer:Tools/analyzers/Desktop.Analyzers.dll

**Comment by alexperovich** [comment]
The same thing happens with both assemblies passed into the compiler.

**Comment by srivatsn** [comment]
@mavasani can you take a look at why it fails if the full set of dependencies?

**Comment by mavasani** [comment]
I am able to repro this issue with the above repro steps. Analyzers with dependencies fail to load with dotnetcore csc but work fine with netfx csc. This is the same issue as summarized in https://github.com/dotnet/roslyn-analyzers/issues/1028#issuecomment-227599906. As summarized by @srivatsn in https://github.com/dotnet/roslyn-analyzers/issues/1028#issuecomment-231145991, you will need .NetCore 1.1 and VS2017 RC compiler toolset to get the relevant fixes for this to work.
