### ISSUE TITLE
Need roslyn test snapshot

### ISSUE THREAD

**Issue by asecchia** [dotnet/roslyn#14864]
#1 – I agree, we can use the dev15-rc snapshot for the Roslyn once we enter Escrow. I can take up this work. 

Snapshot for memory test

@mavasani

**Comment by gafter** [comment]
@mavasani I have no idea what this is about. Can you please engage the user to clarify and assign an area?

**Comment by mavasani** [comment]
@gafter This is for a change to our RPS performance tests.

**Comment by mavasani** [comment]
This is fixed.
