### ISSUE TITLE
Tuple deconstruction into locals with nested tuple gives an error

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#14876]
**Version Used**: 15.0.25802.0

**Steps to Reproduce**:
```
static class Program
{
    static void Main()
    {
        (int x, (string, long) y) = Foo();
    }

    static (int, (string, long)) Foo()
    {
        return (5, ("Foo", 34983490));
    }
}
``` 

**Expected Behavior**: Compiles successfully.

**Actual Behavior**: "Identifier expected" error, on the assignment operator.

Replacing the type of `y` with `var` seems to work fine. Turning it into a single local variable declaration - `(int x, (string, long) y) local = Foo();`  - also works as expected. It seems odd that the above would be disallowed.

**Comment by jcouv** [comment]
Thanks @lorcanmooney for reporting this. 
I expect to investigate this in the next 2 weeks or so (some parsing changes are planned for this week and they may fix this problem as a side-effect).

**Comment by lorcanmooney** [comment]
I should probably add that when I encountered this, the nested tuple was nullable. It didn't seem to make any difference to the behaviour, but simply flattening the tuples wasn't a viable workaround.

**Comment by jcouv** [comment]
Added test to verify resolution (this no longer repros after the recent parsing changes). See https://github.com/dotnet/roslyn/pull/15922
