### ISSUE TITLE
Consider caching "this" locally in async methods

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#14873]
Re:  https://github.com/dotnet/coreclr/issues/7914

It is fairly common for async methods to reach for instance members and that needs to go through an inconvenient indirection that is not always optimizable by JIT since JIT does not have knowledge that "this" is semantically readonly and cannot change from one statement to another.
Compiler has that knowledge and can cache captured "this" into a local. 

NOTE: need to reestablish the cache after every resume.
most likely we can just rehydrate the cache on every resume and rely on the optimizer to kill the dead write, if the "this" value goes unused.

**Comment by VSadov** [comment]
Putting this into 2.1, but we may do this earlier if cheap.

**Comment by tmat** [comment]
Note that if implemented this new variable will have to be tracked by EnC.

**Comment by VSadov** [comment]
@tmat  - would likely make sense only under /o+

**Comment by jamesqo** [comment]
Am by no means an expert a compilers, but I wonder if it would be possible to eliminate the this field entirely if it isn't used... [TryRoslyn](http://tryroslyn.azurewebsites.net/#b:features-tuples/K4Zwlgdg5gBAygTxAFwKYFsDcAoUlaIoYB0AKgBYBOqAhgCb5k0gDWIO2ADsAEYA2YAMYxIaSgDMag1DACS2AN7YYKmKWYsAPKIB8MAGIB7QwEEQCCIIAUAShwBfbF14DhgvsxAwAwjABccorKqtz8QjDMFsLqrNoQyHpGpuaWtsEqSqowAJDUyMCUEDAAzDhZjvZAA=) shows that `<>4__this` is being emitted even though no fields are being accessed.

**Comment by VSadov** [comment]
@jamesqo - that is in Debug. We store "this" so that you could watch/use it in debugger. In optimized build there should be no <>4__this if it is not used.
