### ISSUE TITLE
Microsoft.CSharp.Core.targets and Microsoft.VisualBasic.Core.targets should add themselves to the MSBuildAllProjects property

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/roslyn#14870]
These targets files should have the following (or similar) in them:

```xml
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
```

See also https://github.com/Microsoft/msbuild/issues/1298

**Comment by jaredpar** [comment]
@dsplaisted can you explain why we should be doing this and what the effects are? The information in the bugs don't provide much context here.

**Comment by jeffkl** [comment]
In MSBuild 16.0, this won't be necessary any more. 

https://github.com/Microsoft/msbuild/pull/3605

**Comment by nguerrera** [comment]
This should NOT be done. It is obsolete to add to msbuildallprojects.
