### ISSUE TITLE
Tuple member highlighting and find refs gets confused if there's a local with same name

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#14881]
**Version Used**: 

**Steps to Reproduce**:

```
using System;

static class Program
{
    static void Main()
    {
        (int foo, int bar) tuple;
        int bar;

        tuple = (5, 6);
        tuple.bar = 23;
        bar = 10;

        Console.WriteLine(tuple.bar);
        Console.WriteLine(bar);
    }
}
```

Put you cursor on the various `bar`s. See what gets highlighted, and what's shown if Find References is invoked.

**Expected Behavior**: The highlighter and find references logic should always be able to select the right `bar`s.

**Actual Behavior**: In most cases, the highlighting and find refs logic gets very confused and highlights both `bar` declarations. It only seems to be correct when the cursor is on `tuple.b$$ar` expressions.

Possibly related to #10576.

**Comment by gafter** [comment]
Assigning to compiler team for initial investigation.

**Comment by gafter** [comment]
I suspect the semantic model is treating the `bar` inside the tuple type as a reference to the local.
