### ISSUE TITLE
Consider lowering method group conversions into delegate creation

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#14882]
Currently we have a conflated bound node that can represent both high-level method group conversion and low-level delegate creation. Semantically these are slightly different actions and there are many places that need to adjust for this.
I think initially we reused the node, hoping to minimize rewriting, but as a result we still need to rewrite most method group conversions while the code dealing with unified node needs to deal with its peculiarities.

see for example comments like:
```cs
                // This can occur in a delegate creation expression because the method group
                // in the argument can have a "this" receiver even when "this"
                // is not captured because a static method is selected.  But we do preserve
                // the method group and its receiver in the bound tree, so the "this"
                // receiver must be rewritten.

                //TODO: It seems we may capture more than needed here.

                // TODO: Why don't we drop "this" while lowering if method is static? 
                //       Actually, considering that method group expression does not evaluate to a particular value 
                //       why do we have it in the lowered tree at all?
```

Note that VB already uses separate nodes for this and separation of responsibilities makes corresponding code simpler since certain scenarios (like fake "capturing" of "this" by a static method group in the example above)  simply cannot happen.

**Comment by gafter** [comment]
I am treating these three issues together: #14882, #13840, #13915
