### ISSUE TITLE
Seemingly needless error CS0121: The call is ambiguous between the following methods or properties: 'x(Action)' and 'x(Func<Task>)'

### ISSUE THREAD

**Issue by sandersaares** [dotnet/roslyn#14885]
**Version Used**: 
VS 2015 Update 3

**Steps to Reproduce**:

Attempt to compile the following code:

```cs
private void x()
{
}

private void yyyyyyyyyyyyyyy(Action a)
{
}

private void yyyyyyyyyyyyyyy(Func<Task> a)
{
}

private void z()
{
	yyyyyyyyyyyyyyy(x);
}
```

**Expected Behavior**:

Code compiles and the `Action` overload is used in `z()`.

**Actual Behavior**:

CS0121: The call is ambiguous between the following methods or properties: 'foo.yyyyyyyyyyyyyyy(Action)' and 'foo.yyyyyyyyyyyyyyy(Func<Task>)'

**Further notes**:

Explicitly casting it as `yyyyyyyyyyyyyyy((Action)x);` works fine.

Casting as `yyyyyyyyyyyyyyy((Func<Task>)x);` is a compile error.

**Comment by gafter** [comment]
This is bullet 3 in #250
