### ISSUE TITLE
Microsoft.CodeAnalysis.FxCopAnalyzers references packages containing unsigned files

### ISSUE THREAD

**Issue by ericstj** [dotnet/roslyn#14899]
1.1.0 references 1.0.0 versions of System.Runtime.Analyzers and System.Runtime.InteropServices.Analyzers which are unsigned.

see https://github.com/dotnet/buildtools/issues/1187

**Comment by mavasani** [comment]
This was fixed subsequently. Can you try https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/1.2.0-beta2?
