### ISSUE TITLE
EnvDTE.CodeFunction.FunctionKind doesn’t return vsCMFunction.vsCMFunctionDestructor for Protected Overrides Sub Finalize()

### ISSUE THREAD

**Issue by carlos-j-quintero** [dotnet/roslyn#149]
See MS Connect bug:
https://connect.microsoft.com/VisualStudio/feedback/details/1070903/envdte-codefunction-functionkind-doesnt-return-vscmfunction-vscmfunctiondestructor-for-protected-overrides-sub-finalize

**Comment by DustinCampbell** [comment]
Fixed with PR #488.
