### ISSUE TITLE
Replace with property overrides change signature

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14909]
**Version Used**:  d15prerel/15.0.25831.2

**Steps to Reproduce**:

1. Bring up code actions on GetTuple (Ctrl + .)
```C#
using System;

public class Program {
    public static void Main(string[] args) {
        var a = GetTuple();
    }

    private static (int a, int b) [|GetTuple|]() {
        return (5, 6);
    }
}
```

**Expected Behavior**:
change signature is offered
![image](https://cloud.githubusercontent.com/assets/9797472/19947499/a353cb54-a105-11e6-8abe-dcc0d9134cca.png)

**Actual Behavior**:
only replace with property is offered
![image](https://cloud.githubusercontent.com/assets/9797472/19947512/b3575fca-a105-11e6-873a-40550c8d7306.png)

**Comment by CyrusNajmabadi** [comment]
By design.  No parameters in signature.
