### ISSUE TITLE
Local functions should have different error for missing a body

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#14900]
The one for methods says that the method must have a body because it is not abstract, extern, or partial. Local functions can be none of those. The message should just read that local functions must always have a body.

**Comment by alrz** [comment]
Why not `extern`? I think that would be useful with `DllImport` etc.

**Comment by agocke** [comment]
@alrz We don't currently support attributes on local functions. That's something we're considering adding, but probably not in time for 2.0.

**Comment by agocke** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/18901
