### ISSUE TITLE
Toggling bracket options does not show any change in preview

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14903]
**Version Used**: d15prerel/15.0.25831.2

**Steps to Reproduce**:  Modify spacing options for brackets

![image](https://cloud.githubusercontent.com/assets/9797472/19946457/748577ea-a101-11e6-8dd5-84cd707a8b2b.png)

![image](https://cloud.githubusercontent.com/assets/9797472/19946473/7e0d7fce-a101-11e6-92b4-164c77566db6.png)

**Comment by CyrusNajmabadi** [comment]
No repro:

![Image](https://github.com/user-attachments/assets/48ed4954-5f7c-4a3e-9e40-6e0a73f7502a)
