### ISSUE TITLE
CodeStyle: We should have a rule for whether to qualify static access with typename or not.

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#14910]
```C#
class Program
{
    static int field;
    static void Main(string[] args)
    {
        field = 42;
    }
}
```

Should have a way to require qualification of `field` with `Program.`.

**Comment by DavidArno** [comment]
> Should have a way to require qualification of `field` with `Program`

Seriously, every time someone does that, a kitten dies and the noise drowns it out...

**Comment by Pilchie** [comment]
I didn't say _I_ would turn it on :)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback asking for this.
