### ISSUE TITLE
WPF FAR does not show project in "Project then definition" Group by

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14929]
**Version Used**: d15prerel/15.0.25831.2

**Steps to Reproduce**:

1. Use find all references for element defined in xaml file such as a button
2. Group by "Project then definition"

**Expected Behavior**:
xaml file shows up in results

**Actual Behavior**:
External reference found is shown, but there is no way to navigate to it
![image](https://cloud.githubusercontent.com/assets/9797472/19977174/fbb6d606-a1af-11e6-8bf0-cfcda8ad4101.png)

**Note**: 
If you change the grouping to be "Definition Only" then you can see the file but still not the location
![image](https://cloud.githubusercontent.com/assets/9797472/19977321/767187ce-a1b0-11e6-9a2e-3ce2ba88aeee.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
