### ISSUE TITLE
Task<SemaphoreDisposer> taking lots of memory

### ISSUE THREAD

**Issue by asecchia** [dotnet/roslyn#14934]
@mavasani @CyrusNajmabadi 

Is there a way we can do this without allocating for a disposable/using pattern?

D:\projects\roslyn\roslyn\src\Workspaces\Core\Portable\FindSymbols\SymbolTree\SymbolTreeInfo_Metadata.cs

        public static async Task<SymbolTreeInfo> TryGetInfoForMetadataReferenceAsync(

            // Find the lock associated with this piece of metadata.  This way only one thread is
            // computing a symbol tree info for a particular piece of metadata at a time.
            var gate = s_metadataIdToGate.GetValue(metadata.Id, s_metadataIdToGateCallback);
            using (await gate.DisposableWaitAsync(cancellationToken).ConfigureAwait(false))

D:\projects\roslyn\roslyn\src\Compilers\Core\Portable\InternalUtilities\SemaphoreSlimExtensions.cs
        public async static Task<SemaphoreDisposer> DisposableWaitAsync(this SemaphoreSlim semaphore, CancellationToken cancellationToken = default(CancellationToken))
        {
            await semaphore.WaitAsync(cancellationToken).ConfigureAwait(false);
            return new SemaphoreDisposer(semaphore);
        }

It is currently allocating over half a GB of memory.

Name                                                                                                                                                       Inc %             Inc
Type System.Threading.Tasks.Task`1[Roslyn.Utilities.SemaphoreSlimExtensions+SemaphoreDisposer]                                                              2.7     543,110,656
+ mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[Roslyn.Utilities.SemaphoreSlimExtensions+SemaphoreDisposer].GetTaskForResult(!0)         2.7     534,304,064
|+ mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[Roslyn.Utilities.SemaphoreSlimExtensions+SemaphoreDisposer].SetResult(!0)               2.7     534,304,064
| + Microsoft.CodeAnalysis.Workspaces!Roslyn.Utilities.SemaphoreSlimExtensions+<DisposableWaitAsync>d__1.MoveNext()                                          2.7     534,304,064
|  + mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[Roslyn.Utilities.SemaphoreSlimExtensions+SemaphoreDisposer].Start(!!0&)               2.7    534,304,064
|   + Microsoft.CodeAnalysis.Workspaces!SemaphoreSlimExtensions.DisposableWaitAsync                                                                          2.7     534,304,064
|    + Microsoft.CodeAnalysis.Workspaces!Microsoft.CodeAnalysis.FindSymbols.SymbolTreeInfo+<TryGetInfoForMetadataReferenceAsync>d__4.MoveNext()              2.7     533,767,168
|    |+ mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].Start(!!0&)                                                        2.7     533,767,168
|    | + Microsoft.CodeAnalysis.Workspaces!SymbolTreeInfo.TryGetInfoForMetadataReferenceAsync                                                                2.7     533,767,168

**Comment by Pilchie** [comment]
You already fixed this, right?

**Comment by asecchia** [comment]
Cyrus checked in the fix already

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/14923
