### ISSUE TITLE
DPL needs to participate in NavigateTo "partial results"

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#14935]

**Comment by Pilchie** [comment]
Unfortunately, this won't happen for 15.3.

**Comment by CyrusNajmabadi** [comment]
@rchande @Pilchie what is "DPL"?  Thanks!

**Comment by jmarolf** [comment]
delayed-project-load. This feature was removed from VS so I believe this can be closed

**Comment by CyrusNajmabadi** [comment]
Cool.  Closing out :)
