### ISSUE TITLE
Clicking on link for error id in light bulb preview pane opens external browser while clicking on the same in error list opens a browser tab inside VS

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#1493]
Repro Steps:

1. In a C# console app type code *abc x;*
2. With cursor on above line, press "Ctrl + ." to trigger light bulb
3. Click on the link for CS0246 in the preview pane - the link is opened in an external browser
4. Click on similar link for CS0246 in error list - the link is opened in a new browser tab inside VS

Expected: Behavior should be consistent between 3 and 4 above

**Comment by srivatsn** [comment]
Also ensure consistency with solution explorer as well
