### ISSUE TITLE
After build g.i.cs files show up in FAR window

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14930]
**Version Used**:  d15prerel/15.0.25831.2

**Steps to Reproduce**:

1.  Create a WPF App with a Button  defined
2.  Search for that button in FAR
3.  Build project

**Expected Behavior**:
No change in FAR results

**Actual Behavior**:
Button definition in g.i.cs file is shown
![image](https://cloud.githubusercontent.com/assets/9797472/19977582/4a532840-a1b1-11e6-9ce1-b0020ff4e200.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
