### ISSUE TITLE
g.i.cs elements show up under solution explorer

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14931]
**Version Used**:  d15prerel/15.0.25831.2

**Steps to Reproduce**:

1.  Create a new WPF app
2.  Build the app
3.  Examine the class elements under MainWindow.xaml
![image](https://cloud.githubusercontent.com/assets/9797472/19977730/dd523bc2-a1b1-11e6-9e1f-45051a55eea1.png)

**Expected Behavior**:
All elements either navigate the user to MainWindow.xaml or MainWindow.xaml.cs

**Actual Behavior**:
`_contentLoaded`, `InitializeComponent()`, and `IComponentConector.Connect(int, objcet)` all navigate you to MainWindow.g.i.cs

**Comment by Pilchie** [comment]
Is this a regression from VS2015?

**Comment by CyrusNajmabadi** [comment]
Unlikely to change any behaviors here given lack of customer feedback.
