### ISSUE TITLE
Cannot create PCL targeting net46.app, uwp.10.0.app, and dnxcore50.app

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14932]
**Version Used**: d15prerel/15.0.25831.2

**Steps to Reproduce**:

1. Create a new PCL that targets the following
![image](https://cloud.githubusercontent.com/assets/9797472/19977864/5789259a-a1b2-11e6-8b64-365bb430326a.png)

**Expected Behavior**:
Project is created sucessfully

**Actual Behavior**:
Package restore fails on project creation
![image](https://cloud.githubusercontent.com/assets/9797472/19977891/6753c46c-a1b2-11e6-8e58-13bbdfb1687b.png)

**Comment by bbarry** [comment]
ASP.NET Core 1.0?

Is that label wrong (expecting ".NET Core 1.x")...

ASP.NET Core 1.0 is a set of libraries that target .NET Standard.

**Comment by Pilchie** [comment]
@jinujoseph - this is the fix you took yesterday, right?

Tag @rchande too

**Comment by jinujoseph** [comment]
yes , this was checked to d15rel.
