### ISSUE TITLE
500MB allocations from AssemblyMetadata.Copy

### ISSUE THREAD

**Issue by asecchia** [dotnet/roslyn#14946]
SymbolTreeInfo.TryGetInfoForMetadataReferenceAsync calls GetMetadataNoThrow in order to use the metadata.Id
Internally GetMetadataNoThrow copies the entire metadata

From PortableExecutableReference:
        public Metadata GetMetadata()
        {
            return GetMetadataNoCopy().Copy();
        }

Name                                                                                                                                                                               Inc %             Inc
Type Microsoft.CodeAnalysis.AssemblyMetadata                                                                                                                                        2.6     513,011,520
+ Microsoft.CodeAnalysis!AssemblyMetadata.CommonCopy                                                                                                                                 2.6     512,905,184
|+ Microsoft.CodeAnalysis.Workspaces!SymbolTreeInfo.GetMetadataNoThrow                                                                                                               2.6     512,905,184
| + Microsoft.CodeAnalysis.Workspaces!Microsoft.CodeAnalysis.FindSymbols.SymbolTreeInfo+<TryGetInfoForMetadataReferenceAsync>d__4.MoveNext()                                         2.6     512,905,184
|  + mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].Start(!!0&)                                                                                   2.6     512,905,184
|   + Microsoft.CodeAnalysis.Workspaces!SymbolTreeInfo.TryGetInfoForMetadataReferenceAsync                                                                                           2.6     512,905,184
|    + Microsoft.CodeAnalysis.Workspaces!Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder+<FindImmediateMatchingMetadataTypesInMetadataReferenceAsync>d__20.MoveNext()         2.6     512,905,184
|     + mscorlib!AsyncTaskMethodBuilder.Start                                                                                                                                        2.6     512,905,184
|      + Microsoft.CodeAnalysis.Workspaces!DependentTypeFinder.FindImmediateMatchingMetadataTypesInMetadataReferenceAsync                                                            2.6     512,905,184
|       + Microsoft.CodeAnalysis.Workspaces!Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder+<FindAllMatchingMetadataTypesInProjectAsync>d__19.MoveNext()                      2.6     512,905,184

**Comment by heejaechang** [comment]
public Metadata GetMetadata()
{
return GetMetadataNoCopy().Copy();
}

the copied version is set as no owner. so Metadata could cache no owner version (shallow copied metadata which should be cheap to hold onto) if it ever created and hand out same instance after that.

**Comment by Pilchie** [comment]
You checked in a fix for this already, right?
