### ISSUE TITLE
Properties are colorized as types

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14941]
**Version Used**:  d15prerel/15.0.25831.2

**Steps to Reproduce**:

Consider the code below:
```C#
public abstract class A {
    protected C C => new C();
}

public class B : A {
    void M() {
        C.Value = 1;
    }
}

public class C {
    public int Value { get; set; }
}
```

`C.Value = 1` will be colorized as 
![image](https://cloud.githubusercontent.com/assets/9797472/19984598/5aa9f050-a1cc-11e6-8b62-2bbf9ff366f3.png)
where `C` is colorized as a type.

If I add `this` it is now correctly colorized as a property
![image](https://cloud.githubusercontent.com/assets/9797472/19984636/818d7d90-a1cc-11e6-8d4e-62b4d9bf7bfc.png)

**Comment by Pilchie** [comment]
I'm unable to repro this with d15rel.25908.00.  Are you sure this isn't fading triggered by the "prefer" `this.` analyzer, which @CyrusNajmabadi fixed in https://github.com/dotnet/roslyn/pull/14960?

**Comment by jmarolf** [comment]
Agree can't reproduce on d15rel/150.25913.0
