### ISSUE TITLE
6GB allocations of Type Variant

### ISSUE THREAD

**Issue by asecchia** [dotnet/roslyn#14950]
Name                                                                                                            	Inc %	             Inc
 Type Variant                                                                                                   	 24.9	6,148,014,592.000
+ mscorlib.ni!System.Array.GetValue(Int32)                                                                      	 24.9	6,147,917,824.000
|+ mscorlib.ni![COLD] System.Array.Reverse(System.Array, Int32, Int32)                                          	 24.9	6,147,917,824.000
| + mscorlib!System.Collections.Generic.List`1[Roslyn.Utilities.StreamObjectWriter+Variant].Reverse(int32,int32)	 24.9	6,147,917,824.000
|  + Microsoft.CodeAnalysis!StreamObjectReader.ConstructObject                                                  	 24.9	6,147,917,824.000
|   + Microsoft.CodeAnalysis!StreamObjectReader.ConstructFromValues                                             	 24.9	6,147,917,824.000
|    + Microsoft.CodeAnalysis!StreamObjectReader.ReadValue                                                      	 24.9	6,147,917,824.000
|     + Microsoft.CodeAnalysis.CSharp!CSharpSyntaxNode.DeserializeFrom                                          	 15.5	3,840,257,024.000
|     + Microsoft.CodeAnalysis.VisualBasic!VisualBasicSyntaxNode.DeserializeFrom                                	  9.3	2,307,659,264.000

**Comment by Pilchie** [comment]
You checked in a fix for this already, right?

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/14952
