### ISSUE TITLE
SyntaxGenerator.AsPublicInterfaceImplementation is misleading

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#1495]
Based on the comments, I expected `AsPublicInterfaceImplementation` and `AsPrivateInterfaceImplementation` to take a *type* declaration and an interface name, and add members to the type to stub out the interface. Instead, it's meant to take existing *member* declarations, and fix them up so they can implement a member of the given interface. There are a few specific issues here:

1. There's no doc comment for the `declaration` parameter specifying that it must be a method, property, or indexer.
2. The implementation accepts a type declaration for `declaration`, even though it shouldn't. No exceptions are thrown and the code modifies the access modifiers.
3. The doc comment made me think this would do the same thing as the "Implement Interface" feature in VS, though it only does a small part of that.

**Comment by mattwar** [comment]
This is already documented to accept only method, property and indexer declarations.
