### ISSUE TITLE
When compile assembly and its satellite resource assemblies in memory and set current culture - ResuorceManager to be able to load correct resource.

### ISSUE THREAD

**Issue by luboid** [dotnet/roslyn#14968]
**Version Used**: 1.3.2

**Steps to Reproduce**:

I'm apply repo with test code:
https://github.com/luboid/roslyn-test-case

**Expected Behavior**:
When compile assembly and its satellite resource assemblies in memory and set current culture - ResuorceManager to be able to load correct resource. 

**Actual Behavior**:
ResuorceManager can't load correct resource.

All working fine when assemblies are written down to the file system.  I suspect in memory can't work out because assemblies don't have Location.

**Comment by tmat** [comment]
I see you're using ```Assembly.Load``` API to load the in-memory assemblies, including their satellite assemblies. I'm not familiar with how ResourceManager locates the satellite assemblies for in-memory assemblies, or if it's even a supported scenario. @weshaggard @ericstj could you help?

**Comment by weshaggard** [comment]
cc @gkhanna79 @ramarag for resource manager questions.

**Comment by luboid** [comment]
Here is fusion log for in memory case:

*** Assembly Binder Log Entry  (4.11.2016 г. @ 20:24:53) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  E:\pub\roslyn-test-case\src\CSRunner\bin\Debug\CSRunner.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Documents.Queue2.resources, Version=1.0.0.0, Culture=en, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///E:/pub/roslyn-test-case/src/CSRunner/bin/Debug/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = CSRunner.exe
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: E:\pub\roslyn-test-case\src\CSRunner\bin\Debug\CSRunner.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///E:/pub/roslyn-test-case/src/CSRunner/bin/Debug/en/Documents.Queue2.resources.DLL.
LOG: Attempting download of new URL file:///E:/pub/roslyn-test-case/src/CSRunner/bin/Debug/en/Documents.Queue2.resources/Documents.Queue2.resources.DLL.
LOG: Attempting download of new URL file:///E:/pub/roslyn-test-case/src/CSRunner/bin/Debug/en/Documents.Queue2.resources.EXE.
LOG: Attempting download of new URL file:///E:/pub/roslyn-test-case/src/CSRunner/bin/Debug/en/Documents.Queue2.resources/Documents.Queue2.resources.EXE.
LOG: All probing URLs attempted and failed.

*** Assembly Binder Log Entry  (4.11.2016 г. @ 20:24:54) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  E:\pub\roslyn-test-case\src\CSRunner\bin\Debug\CSRunner.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Documents.Queue2.resources, Version=1.0.0.0, Culture=en, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///E:/pub/roslyn-test-case/src/CSRunner/bin/Debug/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = CSRunner.exe
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: E:\pub\roslyn-test-case\src\CSRunner\bin\Debug\CSRunner.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///E:/pub/roslyn-test-case/src/CSRunner/bin/Debug/en/Documents.Queue2.resources.DLL.
LOG: Attempting download of new URL file:///E:/pub/roslyn-test-case/src/CSRunner/bin/Debug/en/Documents.Queue2.resources/Documents.Queue2.resources.DLL.
LOG: Attempting download of new URL file:///E:/pub/roslyn-test-case/src/CSRunner/bin/Debug/en/Documents.Queue2.resources.EXE.
LOG: Attempting download of new URL file:///E:/pub/roslyn-test-case/src/CSRunner/bin/Debug/en/Documents.Queue2.resources/Documents.Queue2.resources.EXE.
LOG: All probing URLs attempted and failed.

**Comment by ramarag** [comment]
Yes you are right, resource manager needs resources on disk to function. As far as i know you have 2 options to get streams working

1. Use the streamresourcemanager code from https://gist.github.com/ramarag/6e6f58a210dd00745582 .
2.  Use the [AppDomain.AssemblyResolve] (https://msdn.microsoft.com/en-us/library/system.appdomain.resourceresolve(v=vs.110).aspx) being added as part of netstandard2.0 work https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/tests/System/AppDomainTests.cs#L461

**Comment by luboid** [comment]
Ok, thank for help
