### ISSUE TITLE
Throwing expressions which can be converted to Exception

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#14965]
The current specification has this in 8.9.5:

> A throw statement with an expression throws the value produced by evaluating the expression. The expression must denote a value of the class type System.Exception, of a class type that derives from System.Exception or of a type parameter type that has System.Exception (or a subclass thereof) as its effective base class. If evaluation of the expression produces null, a System.NullReferenceException is thrown instead.

As part of the ECMA standardization process, we noted that this is a bit unfriendly for `dynamic`, and is unusual in terms of not taking implicit conversions to `Exception` into account. `mcs` does both of these, and the ECMA group has decided to permit this, including the following wording in the upcoming standard:

> A throw statement with an expression throws an exception produced by evaluating the expression. The expression shall be implicitly convertible to `System.Exception`, and the result of evaluating the expression is converted to `System.Exception` before being thrown. If the result of the conversion is null, a `System.NullReferenceException` is thrown instead.

We would like Roslyn to implement our retroactive change to the Standard, with appropriate levels of grovelling apology (from us). Note that this potentially affects an error message as well:

> error CS0155: The type caught or thrown must be derived from System.Exception

**Comment by gafter** [comment]
However, the compiler does not implement the specification for user-defined conversion as well:

``` c#
class Foo
{
    public static implicit operator Exception(Foo foo) => null;

    void M()
    {
        // Error CS0155: The type caught or thrown must be derived from System.Exception
        throw this;
    }
}
```

**Comment by gafter** [comment]
I am including this in C# 8 so that the throw statement and/or expression will interact properly with the switch expression.  I believe it would be a breaking change to do it later due to this interaction.  The implementation is about 10 lines of code.  It would be a negative number of lines of code if we didn't also want to support the old binding method for previous language versions.

/cc @jcouv @agocke @jaredpar @MadsTorgersen
