### ISSUE TITLE
Warning CS0109 is slightly inaccurately worded

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#14966]
Consider this code:

```csharp
class Base
{
    private void F() {}
}
class Derived: Base
{
    new public void F() {}
}
```

Roslyn emits a warning - which it should:

>Test.cs(9,21): warning CS0109: The member 'Derived.F()' does not hide an inherited member. The new keyword is not required.

`Derived.F()` *does* hide an inherited member, it's just not an "available" (in ECMA standardese) member. In the C# 5 spec section 3.7.1.2 the reverse (when you *can* use `new`) is worded as "Contrary to hiding a name from an outer scope, hiding an accessible name from an inherited scope causes a warning to be reported".

**Comment by gafter** [comment]
The word "inherited" should be "accessible" in the diagnostic.
