### ISSUE TITLE
C# advanced options appearance issue

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#14979]
![image](https://cloud.githubusercontent.com/assets/3751401/20017088/5a0ee00c-a27f-11e6-8c1b-9f5c7012eca8.png)

With the options dialog at its default size, note how the gray borders are touching the scrollbar.

**Comment by reaction1989** [comment]
@Pilchie this can be closed or?

**Comment by Pilchie** [comment]
Tag @jinujoseph - @reaction1989 I could imagine someone specifying a margin on the control to make this look a little nicer someday.

**Comment by reaction1989** [comment]
@Pilchie There is a margin 
![image](https://user-images.githubusercontent.com/873751/33039062-02b6b49e-ce37-11e7-9ddd-ce00a6b82b4f.png)

Or do you mean another one?

**Comment by Pilchie** [comment]
I'll defer to @dpoeschl on this.

**Comment by dpoeschl** [comment]
The code specifies a margin of `0,0,3,0` (https://github.com/dotnet/roslyn/commit/d668ede61a377c1e8692ff3dd3372432dc6ab74c#diff-6641b061f04581b881c351f58c563872) and I see the margin the same way @reaction1989 does. Looks good to me, but we can reopen if someone can point to a current build where it looks bad. Thanks again for your work on this @reaction1989!
