### ISSUE TITLE
Need a Code Fix to install System.ValueTuple package

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#14970]
**Version Used**: 
Latest Dev15 RC bits.

**Steps to Reproduce**:

1. Create a new *desktop* Console Application 
2. Add the following to the body of `Main`: `(int, string) y = (5, "Hello");`
3. Note the error squiggles under both `(int, string)` and `(5, "Hello")` stating ``Predefined type 'System.ValueTuple`2' is not defined or imported``.
4. Press `Ctrl+.` to bring up the list of code fixes.

**Expected Behavior**:

There should be a quick fix offering to install the [System.ValueTuple package](https://www.nuget.org/packages/System.ValueTuple/).

**Actual Behavior**:

No code fix is provided. Unless you already know about the System.ValueTuple package, the fix here is not obvious. Anyone trying to use tuples in an existing project is likely to run into this problem, and we should make it easy for them to get back on the right path.

**Comment by AdamSpeight2008** [comment]
Do you really want a Code Fix for an issue that will be a mute point, when package is integrated into the core framework?

**Comment by tmeschter** [comment]
That's only helpful for new projects targeting a framework with `ValueTuple`, or projects that can be upgraded to a new framework. Everyone else will need to use the System.ValueTuple package.

**Comment by alrz** [comment]
AFAIK there exist a code fix that suggests to add nuget packages for unresolvable types that are known to be in top 1000 packages. perhaps it could cover this one.

**Comment by tmeschter** [comment]
Yes, this could be viewed as a special case of that general code fix. However, in my brief testing, it does not offer to fix this particular issue.

**Comment by AdamSpeight2008** [comment]
Is the package in the top 1000? If not we could have a list of special cased packages eg `System.ValueTuple`

**Comment by alrz** [comment]
I think the issue here is that tuple literal doesn't produce a "missing type" error and has its own error, whereas the code fix just diagnose missing type errors. Perhaps if you explicitly use `ValueTuple` type name it suggests to add the package. I've not tested any of these though.

**Comment by AdamSpeight2008** [comment]
@alrz In that case we get the following error.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'ValueTuple<,>' does not exist in the namespace 'System' (are you missing an assembly reference?)	
```

**Comment by AdamSpeight2008** [comment]
Related PR #13571

**Comment by AdamSpeight2008** [comment]
Think if we add the error id to the following list [link](https://github.com/dotnet/roslyn/blob/8df386bbf5a4af063ab94dfc7ea0a779562eb235/src/Features/CSharp/Portable/CodeFixes/AddImport/CSharpAddImportCodeFixProvider.cs#L130) I believe that we'll get the suggestion to appear.

**Comment by jcouv** [comment]
There is an existing work item to track this code fix work: https://github.com/dotnet/roslyn/issues/13375
You could resolve a duplicate.

Two parts are left at this point: the code fix should run out-of-proc and it should trigger on the new error code for missing ValueTuple reference.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/15177
