### ISSUE TITLE
DPL: Inline Rename "gives up" on SyntaxNode

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#14977]
Open Roslyn.sln with DPL active
Navigate To SyntaxNode.cs
Put the caret on `SyntaxNode`
F2
Type a new name, hit enter
Rename shows the "computing rename information" wait indicator for a few seconds
The wait indicator eventually disappears and nothing is renamed

**Comment by Pilchie** [comment]
I bet this is because we tell VS to load the files, and that ends up changing the `Solution` in a way we don't expect.

**Comment by CyrusNajmabadi** [comment]
this doesn't repro for me.
