### ISSUE TITLE
Error list messages for several coding-styles need to be improved.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14986]
![image](https://cloud.githubusercontent.com/assets/4564579/20019213/61d991e8-a288-11e6-90e9-39c356f4e188.png)

The text here isn't great.  I need persons gooder with speeking to help me here.

Halp me obi-wan- @kuhlenh , you're my only hope.

**Comment by CyrusNajmabadi** [comment]
(This bug is for the overall bucket of getting the right text for the error list and the light bulb).

**Comment by Pilchie** [comment]
You sent out a PR for this already, right?

**Comment by CyrusNajmabadi** [comment]
Strings were updated for these.
