### ISSUE TITLE
"Use object initializer" breaks code

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14988]
Example:

```c#
var v = new Whatever();
v.Blah = v.Blah.WithSomething();
```

Use-object-initializer should not be offered here as the variable it is initializing is used in the statement it would rewrite.  i.e. it converts the above to this illegal code:

```c#
var v = new Whatever()
{
     Blah = v.Blah.WithSomething()    // v not available here.
}
```

**Comment by Pilchie** [comment]
Not an RC issue.
