### ISSUE TITLE
[RC2] Unable to specify values to /keepalive for compiler server

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#1499]
This issue represents porting the fix for the /keepalive switch in 752d7ccb9703e667c3d62784a8b517bd4941ca83 to the preview branch.

## Importance
Without this fix, every valid use of the /keepalive switch results in

    error CS2007: Unrecognized option: '/keepalive:10'

and keepalive is completely unusable. This switch is mandatory for Roslyn use in ASP.NET classic.

## Fix Description
The proposed fix for RC2 is represented a pull request #1518.

## Validation
There are already a variety of unit tests for this feature, but this change also adds an end-to-end test that verifies the complete scenario.

## Risk
This is a targeted fix to the keepalive switch and should not effect any other compiler scenarios.

**Comment by agocke** [comment]
@theoy FYI

**Comment by theoy** [comment]
@agocke - let's tee up a PR before we get approval for this as well.

**Comment by agocke** [comment]
@theoy PR created at #1518.

**Comment by MattGertz** [comment]
Approved for next preview.

**Comment by agocke** [comment]
Merged #1518
