### ISSUE TITLE
Design question: If a method overrides/implements a method from metadata, should we suppress "convert to property"?

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14991]
For example:

![image](https://cloud.githubusercontent.com/assets/4564579/20020797/438c60a0-a290-11e6-85b0-cf0685ca9a26.png)

Upside, this will rarely end up working well for the customer.
Downside, perhaps they know what they're doing, and they'd find the lack of the refactoring annoying/confusing.

**Comment by miloush** [comment]
I remember hitting Ctrl+. and seeing "No quick actions available here" on several occasions and it is indeed a bit disappointing.

However, I believe that quick fixes should not introduce compile errors in the first place and I view any such as a candidate for bug report. Would that be just by design?

**Comment by CyrusNajmabadi** [comment]
it's not a quick-fix, it's a refactoring.  And refactorings should generally allow you do do what you want, but let you *know* there will be a potential issue.  

For example, a rename *may* cause issues.  So we tell you what they are.  but we don't stop you, because that may be super annoying for you to have to adjust your code first just to satisfy us.  We think tools should still work, even if you may need to do additional work once we make the change.

**Comment by miloush** [comment]
Good point, my mistake.

**Comment by Pilchie** [comment]
I think we should allow this, given that the preview squiggles the property with the error.  This matches with our philosophy of allowing the user to perform the operation anyway in case they are on the way to doing something else (like making it not an override).

Tagging @kuhlenh and @DustinCampbell for any dissenting opinions.
