### ISSUE TITLE
Proposal: Exception.Rethrow()

### ISSUE THREAD

**Issue by jreumuth** [dotnet/roslyn#14999]
Rerowing an exception in .NET has two shortcomings. One is you lose some call stack info. In the following code:
```
public void Method2() {
    if (new Random().Next(2) == 0)
        throw new Exception();
}

public void Method1() {
    try {
        Method2();
        Method2();
        Method2();
    } catch (Exception ex) {
        throw;
    }
}
```
In the stack trace, the only line from Method1 is the throw line. The call to Method2 that threw the exception in not in the stack trace and there's no good way to known which Method2 call it was.

The second shortcoming of rethrowing an exception is you cannot do it outside of the catch block. There's at least two use cases for rethrowing an exception later outside of the catch block:
1. You capture an exception and need to rethrow it much later after doing a lot of other stuff if that other stuff doesn't fail. The other stuff done cannot possibly be within the catch block. I have run into 3 such situations within the past couple years (once making an auto test framework, once with an exception from another thread, and once with an exception in a hook proc).
2. Writing a function to deal with an an exception that occurs in a finally (to avoid having to duplicate the same logic in a bunch of places). By default an exception in a finally would overwrite an already existing exception (if there is one) which would virtually never be desirable (arguably this design is a flaw in .NET but due to backwards compatibility we're stuck with it).

I'll mention you can use the following hack to overcome these problems:
```
public static void PreserveStackTrace(Exception exception) {
	MethodInfo preserveStackTrace = typeof(Exception).GetMethod("InternalPreserveStackTrace", BindingFlags.Instance | BindingFlags.NonPublic);
	preserveStackTrace.Invoke(exception, null);
}
```
But you shouldn't have to rely on a hack to solve these issues. It should be a first class feature. To fix this in a first class way, there needs to be a way of rethrowing an exception without these shortcomings. It could be a new rethrow keyword (i.e. rethrow ex) or a Exception.Rethrow() method.

**Comment by HaloFour** [comment]
The C# compiler doesn't deal with the particulars of how `Exception` behaves or any of the methods that it might surface.  You might want to take this up with the [CoreCLR](https://github.com/dotnet/coreclr) repository.

**Comment by jreumuth** [comment]
@HaloFour 

Thanks. I posted it as #https://github.com/dotnet/coreclr/issues/8005.
