### ISSUE TITLE
EnvDTE.CodeFunction.FunctionKind doesn’t return correct value for EnvDTE80.CodeEvent.Adder, Remover or Thrower

### ISSUE THREAD

**Issue by carlos-j-quintero** [dotnet/roslyn#150]
See MS Connect bug:
https://connect.microsoft.com/VisualStudio/feedback/details/1070919/envdte-codefunction-functionkind-doesnt-return-correct-value-for-envdte80-codeevent-adder-remover-or-thrower

**Comment by DustinCampbell** [comment]
Sigh... it's a little disheartening when I'm investigating a bug and happen upon a TODO comment that I wrote wrote which reveals the problem:

https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Impl/CodeModel/InternalElements/CodeAccessorFunction.cs#L157

**Comment by DustinCampbell** [comment]
Fixed with PR #488.
