### ISSUE TITLE
Tabbing to complete from an empty intellisense list causes a nullref popup

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#15006]
**Version Used**: d15rel/15.0.25903.2

**Steps to Reproduce**:

1. C# code
```C#
using System;
class Program
{
    static void Main(string[] args)
    {
        InvProExc$$
    }
}
```
2. Ctrl+J to bring up intellisense at the $$
3. Filter down to only interfaces such that there is nothing in the list
4. Press tab

**Expected Behavior**: Not sure.

**Actual Behavior**: 
![image](https://cloud.githubusercontent.com/assets/235241/20024009/c867b242-a2a0-11e6-9d85-8b8684ec9a85.png)

**Comment by dpoeschl** [comment]
FYI @rchande @CyrusNajmabadi

**Comment by rchande** [comment]
Please verify @dpoeschl
