### ISSUE TITLE
Missing "assigned but its value is never used" warning on (some) tuples

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#15002]
**Version Used**: d15rel/15.0.25903.2

```C#
using System;
class Program
{
    static void Main(string[] args)
    {
        (int, int) tuple1 = (3, 4);
        (int, int) tuple2 = default(ValueTuple<int, int>);
    }
}
```

`tuple2` gets `The variable 'tuple2' is assigned but its value is never used` warning, but `tuple1` does not get the warning.

I would expect them both to get the warning.

**Comment by jcouv** [comment]
FYI @VSadov

**Comment by gordanr** [comment]
Something similar in VS 2015.

```
private void Test()
{
    bool b1 = true;                     
    bool b2 = DateTime.Now.Ticks > 1234L;
}
```

The variable 'b1' is assigned but its value is never used
b2 - no warning

Both variables are assigned but never used? I would expect them both to get the warning.

**Comment by jcouv** [comment]
@gordanr I was confused too, but gafter clarified in this comment: https://github.com/dotnet/roslyn/pull/15026#discussion_r86669132
