### ISSUE TITLE
Lightbulb doesn't work immediately after Rename Tracking is dismissed

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#15007]
**Version Used**: d15rel/15.0.25903.2

![lightbulbrenametracking](https://cloud.githubusercontent.com/assets/235241/20024157/1a0e772e-a2a2-11e6-99d3-710bbfc3301d.gif)

**Comment by CyrusNajmabadi** [comment]
Closing out as i cannot repro this and this was heavily rewritten.
