### ISSUE TITLE
Noticable delay opening options pages

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#15001]
Open the code style (or any other C# option page implemented by Roslyn). There's a noticable delay between the tab switch and the WPF UI showing up, even if you open and close the tools options dialog multiple times in one session.

**Comment by dpoeschl** [comment]
I don't notice a problem switching multiple times in one session, but it is bad the first time for me too. Still, I don't think this meets the bar for `2.0`, and Kevin agreed. FYI @mavasani

**Comment by jinujoseph** [comment]
Closing old issue,
revert back if you still seeing this in current build
