### ISSUE TITLE
Indent Guides BlockContextProvider starts to cut off text as you indent deeper

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#15004]
**Version Used**: d15rel/25903.2

![indentguides](https://cloud.githubusercontent.com/assets/235241/20023813/a50e4992-a29f-11e6-863b-ef5aece2d9f6.gif)

**Comment by dpoeschl** [comment]
FYI @CyrusNajmabadi 

The weird background-less popups are a result of screen2gif, I think. That didn't actually happen when I did the recording.

**Comment by Pilchie** [comment]
@CyrusNajmabadi - do you know where this might be happening?

**Comment by CyrusNajmabadi** [comment]
No clue!  Totally crazy.

**Comment by CyrusNajmabadi** [comment]
Doesn't repro for me now.
