### ISSUE TITLE
Convert to object initializer generates bad code if code is within a With block

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#15012]
1. Paste the following code into a new VB console app.

```
        With New String("c"c, 42)
            Dim x As ProcessStartInfo = New ProcessStartInfo()
            x.Arguments = .Length.ToString()
        End With
```

*Expected:* the code action isn't recommended to convert this to an object initializer, since then it breaks the .Length reference.
*Actual:* we do.

**Comment by Pilchie** [comment]
@CyrusNajmabadi you fixed a similar issue on the C# side already - did that handle this too?
