### ISSUE TITLE
ProcessStartInfo listed twice in completion in initializer

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#15011]
Create a new console app, and type what you see below:

![image](https://cloud.githubusercontent.com/assets/201340/20025384/0ef5a0fc-a2ab-11e6-8352-b618fa03e696.png)

Observe ProcessStartInfo is listed twice.

**Comment by Pilchie** [comment]
Presumably these are the item from the new preselection and from the symbol provider not unifying?

**Comment by rchande** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/15426
Please verify @jasonmalinowski
