### ISSUE TITLE
Proposal: Lambda Wildcards

### ISSUE THREAD

**Issue by HaloFour** [dotnet/roslyn#15027]
This is an extension to #14862 and #14794.

I propose that when a lambda is declared using multiple `_` identifiers for parameter names that all of those identifiers are then considered wildcards and attempting to reference those parameters in the lambda body is a compiler error.  However, if there is only a single parameter with that name then it may be referenced in the lambda body to retain backwards compatibility.

```cs
Func<int, int, bool> func1 = (_, _) => true; // legal
Func<int, int, bool> func2 = (_, _) => _ + 4; // CS0103: The name '_' does not exist in the current context
```

**Comment by vbcodec** [comment]
It is alerady included in #14794, seel end of 'Wildcards (revisited)' section

**Comment by HaloFour** [comment]
@vbcodec 

I believe that #14862 would supersede that behavior and that wildcards wouldn't just result by attempting to declare multiple variables of the name `_` in scope.

However, if those proposals combined (and implemented) still results in wildcards for lambda declarations then I will close this proposal.

**Comment by HaloFour** [comment]
Rereading #14794 it does appear to cover this.
