### ISSUE TITLE
Using out var quickfix uses var even if options are off

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#15021]
1. Set "use explicit type" for all style options in C#.
2. Add this code:

```
IPAddress foo;
IPAddress.TryParse("1.2.3.4", out foo);
```

3. Invoke the refactoring.

*Expected:* no var
*Actual:* the dreaded evil var!

(obviously yes I'm pro-var, but it seems if people don't want it we're doing it anyways)

**Comment by NoneGiven** [comment]
There are two reciprocal issues here: With a type name (IPAddress), it always uses var even if the "elsewhere" var preference is set to "prefer explicit type." And with a type keyword (int), it always uses the keyword even if "elsewhere" preference is set to "prefer var."

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/15306

We now respect the user's 'var' preferences for both extract-method and inline-declaration.
