### ISSUE TITLE
Microsoft.Reflection offered over System.Reflection

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15025]
![image](https://cloud.githubusercontent.com/assets/4564579/20026852/a92917e8-a2c0-11e6-8536-4dfd6483208f.png)

Likely that System matches should beat out other matches.

**Comment by miloush** [comment]
There is also the _Place 'System' directives first when sorting usings_ setting which could be used. Although I always turn it on, so I am fine with having System matches first.

**Comment by Pilchie** [comment]
What *is* `Microsoft.Reflection`?  I've never heard of that.

**Comment by Pilchie** [comment]
I'm not inclined to fix this without more reports of it being an issue.

**Comment by Pilchie** [comment]
@DustinCampbell @kuhlenh for dissenting opinions.

**Comment by CyrusNajmabadi** [comment]
Another case:
![image](https://cloud.githubusercontent.com/assets/4564579/20415839/d74c97ba-acef-11e6-8507-184fce15f862.png)

**Comment by Pilchie** [comment]
Still this has been the same in Add Using since VS 2005, and I've never heard of a request to change it before now.  I still don't find it all that compelling.

**Comment by Pilchie** [comment]
Talked this over with @kuhlenh, and we are okay with just sorting System to the top in the lightbulb.
