### ISSUE TITLE
Preselect for enums seems to have regressed

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15024]
Typing:

![image](https://cloud.githubusercontent.com/assets/4564579/20026835/46e31f3e-a2c0-11e6-822e-e791a1e68fe2.png)

Expected that BindingFlags woudl not be preselected.  It wasn't.

**Comment by miloush** [comment]
Might be related to #14813.

**Comment by Pilchie** [comment]
Yes, looks like a dupe.
