### ISSUE TITLE
Allow parsing deconstruction-declaration as expression

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#15049]
For instance, `var x = ((var y, var z) = e).Item1;`

**Comment by jcouv** [comment]
Within 2.0, we need to at least do some disambiguation in the parser. The rest of the feature can be post-2.0.

**Comment by jcouv** [comment]
In particular, this means that deconstruction declaration can be used in embedded statement.
For instance:
```C#
if (flag)
    var (x, y) = e;
```

**Comment by gafter** [comment]
A proposed plan of attack, from the language design POV, is here: https://gist.github.com/gafter/36265536f98b7dfd58fdc1d86ec5aecb

**Comment by gafter** [comment]
@MadsTorgersen and I came up with a way to prevent this from being a breaking change. I’ll revise the proposal shortly.

**Comment by gafter** [comment]
The compiler implementation is mostly done in #15548; the next step would be to delete the 30 lines that produce the diagnostic and add testing. When we schedule this work is to be decided by @jaredpar.

**Comment by jcouv** [comment]
Moved to 2.1.
Relates to support for deconstructions mixing assignments and declarations (https://github.com/dotnet/roslyn/issues/15050).

**Comment by jaredpar** [comment]
@gafter is this important for 15.3 or can we push off to 15.6?

**Comment by gafter** [comment]
This is the implementation side of a language feature (https://github.com/dotnet/csharplang/issues/125) that is not in 7.1. So it should be pushed off, or even closed until we start work on the feature.
