### ISSUE TITLE
Null-ref in service hub process.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15041]
Got a null ref here in SnapshotService.cs:

```
        protected override void OnDisconnected(JsonRpcDisconnectedEventArgs e)
        {
            _source.Done();
        }
```

_source was null.

Stack was: 

```
>	Microsoft.CodeAnalysis.Remote.ServiceHub.dll!Microsoft.CodeAnalysis.Remote.SnapshotService.OnDisconnected(StreamJsonRpc.JsonRpcDisconnectedEventArgs e) Line 32	C#
 	Microsoft.CodeAnalysis.Remote.ServiceHub.dll!Microsoft.CodeAnalysis.Remote.ServiceHubServiceBase.OnRpcDisconnected(object sender, StreamJsonRpc.JsonRpcDisconnectedEventArgs e) Line 108	C#
 	[External Code]	
```

Dump is here:  https://drive.google.com/file/d/0ByISdSEZ09PBX21Zbkw1WmVQOW8/view?usp=sharing

**Comment by CyrusNajmabadi** [comment]
Tagging @srivatsn @heejaechang @panopticoncentral

**Comment by heejaechang** [comment]
this and this probably related - https://github.com/dotnet/roslyn/issues/15040#issuecomment-258716222

**Comment by heejaechang** [comment]
talking with service hub team where they run multiple service hub process hosts for our service which causing shared state not exist. seems related to that.. but not 100% sure.

**Comment by heejaechang** [comment]
can repro this with this. - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/288961

**Comment by heejaechang** [comment]
looks like a race in service hub where it fails to initialize some COM object which cause us to create 2 service hub processes.

**Comment by heejaechang** [comment]
talked to service hub guys. root cause is not fixed yet. decided to do retry on our side until root cause is fixed.

https://github.com/dotnet/roslyn/pull/15110

**Comment by heejaechang** [comment]
opened tracking bug - https://github.com/dotnet/roslyn/issues/15562
