### ISSUE TITLE
.NET 2.0 ResultProvider DLLs should be in NetFX20 root directory in ExternalAPIs nupkg 

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#15058]
ResultProvider DLLs were previously in a NetFX20 root directory in the ExternalAPIs nupkg. As of a recent change, the DLLs are in Dlls/*ResultProvider.NetFX20.

**Comment by cston** [comment]
cc @jaredpar, @mavasani

**Comment by tmat** [comment]
👍

**Comment by jasonmalinowski** [comment]
@cston: what's the problem with the current setup?

**Comment by cston** [comment]
@jasonmalinowski The current setup is perhaps good enough. Feel free to close this issue.
