### ISSUE TITLE
VB: Typing a variable triggers snippet completion

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#15051]
When typing `Dim t$$`, I get a completion list with a number of snippets, including `tbArray` which is hard-selected. 
Pressing space triggers the completion, which makes me angry ;-)

FYI @CyrusNajmabadi @rchande 

Repro version: 
Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.25831.1 D15REL
Microsoft .NET Framework
Version 4.6.01586

**Comment by jcouv** [comment]
Never mind, I had selected the option to "always include" snippets. In that scenario, I think that is the expected behavior.

**Comment by CyrusNajmabadi** [comment]
No.  This is an issue.  Snippets should not interfere with typing variable names.

**Comment by jcouv** [comment]
This problem also appears when typing comments. With the "always show snippets" option, I get annoying completing in this scenario too:
![image](https://cloud.githubusercontent.com/assets/12466233/21324253/d02160f2-c5d5-11e6-81cc-0d722f9eba64.png)

**Comment by jcouv** [comment]
This is a pre-existing problem. I'll let the IDE team prioritize.

**Comment by CyrusNajmabadi** [comment]
Closing out as we're not investing in these scenarios.
