### ISSUE TITLE
Go to line requires all projects be loaded

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#15061]
**Steps to Reproduce**:

1.  Open Roslyn.sln (with DPL off)
2. Press Ctrl+G (Go to line)

**Expected Behavior**:
Go to line immediately pops up

**Actual Behavior**:
All projects need to load before go to line appears
![image](https://cloud.githubusercontent.com/assets/9797472/20077467/670a79d2-a4f1-11e6-912b-7efc2caacf8c.png)

**Comment by Pilchie** [comment]
Tagging @CyrusNajmabadi - I think we've already been talking to the platform team about enabling this.

**Comment by CyrusNajmabadi** [comment]
Yes.  The platform team is fixing this.  I believe the work is being done by James Williams. Will ping him to comment on this.

**Comment by CyrusNajmabadi** [comment]
According to james this is fixed in RC2.  So let's validate when we get an updated build
