### ISSUE TITLE
deconstructing witin LINQ comprehensions

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#15074]
It has [been suggested that](https://github.com/dotnet/roslyn/issues/347#issuecomment-258845034) we support

```cs
from (a, b) in Pairs select a * b

from t in Pairs let (a, b) = t select a * b
```

**Comment by HaloFour** [comment]
Feels like a good first step towards #6877, starting with compiler-verified guaranteed to succeed tuple patterns.

**Comment by jamesqo** [comment]
Definitely seems like a good idea. +1

**Comment by nmarcel** [comment]
Ufff! for a moment I believed the asterisk (in the second example) represented an F-Sharpesque tuple style.

**Comment by atifaziz** [comment]
While we anxiously wait for this to appear in a future version of C#, one could deconstruct via a folding function for tuples, like this:

```c#
static class TupleExtensions
{
    public static TResult Fold<T1, T2, TResult>(this (T1, T2) tuple, Func<T1, T2, TResult> folder) =>
        folder(tuple.Item1, tuple.Item2);
}
```

and then use it in LINQ as follows:

```c#
from t in Pairs select t.Fold((a, b) => a * b);
```

**Comment by jcouv** [comment]
This language feature requests is tracked by https://github.com/dotnet/csharplang/issues/189
I'll go ahead and close this Roslyn issue. Thanks
