### ISSUE TITLE
Tuple types in using directives

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#15072]
It has [been requested that](https://github.com/dotnet/roslyn/issues/347#issuecomment-258845034) we support

```cs
using Subject = (bool Gender, double Age);
```

**Comment by HaloFour** [comment]
🍝   Generic version when combined with #3993?

```cs
using Subject<T> = (T Gender, double Age);
```

**Comment by eyalsk** [comment]
That's pretty cool!

**Comment by DavidArno** [comment]
At first glance, this seems an excellent idea. But then it takes on the texture of that "aerosol cream", that looks like rich, thick, real cream but turns out to be 90% air. Yes, it would be useful, but the scope would then just be within that file. Some means of giving it a wider scope would really make this useful, eg:

**Subject.cs**
````cs
public global Subject = (bool Gender, double Age);
````
**OtherFile.cs**
````cs
bool getGender(Subject subject) => subject.gender; 
        
var gender = getGender((false, 10));
````

**Comment by dsaf** [comment]
@DavidArno this was previously rejected for some reason #7451.

**Comment by DavidArno** [comment]
@dsaf,
That's a shame, but thanks for the link.

**Comment by MgSam** [comment]
I'm happy with the proposal as @gafter specified. I think generics and global scope are both orthogonal to this feature and should be considered separately.

**Comment by DavidArno** [comment]
Generics and global scope are enhancements to the basic proposal. So you appear to be misusing the term "orthogonal" :stuck_out_tongue:

**Comment by MgSam** [comment]
@DavidArno They are completely separable proposals that do not impact the merits of this feature as proposed. I'd call that orthogonal. Scope creep is the death of feature requests.

**Comment by qrli** [comment]
I don't see this necessary. It is at best low priority.

If you want a type, define a type.

**Comment by alrz** [comment]
Once we have records, it'll be a piece of cake.
```cs
struct Subject(bool Gender, double Age);
```
 I'd personally prefer to have generic and global type aliases over this.

**Comment by DavidArno** [comment]
@alrz,

I'm confused by your comment. First you appear to argue that records will handle this requirement just fine, but then appear to argue that aliases would be better than records. Am I misunderstanding you?

**Comment by orthoxerox** [comment]
@DavidArno records do not cover all the use cases you might need aliases for. See my example in #7453, there's no way a record can replace a long-winded generic interface type declaration.

**Comment by DavidArno** [comment]
@orthoxerox,

Apologies, my comment wasn't clear. I was referring to this specific feature request: tuple aliases, not type aliases in general.

**Comment by alrz** [comment]
@DavidArno I'm saying that when you want a named tuple you'd better to define a struct record. But generic and global type aliases are also useful for other scenarios.

**Comment by AdamSpeight2008** [comment]
Will the diposable form of using also be supported.
```c#
using ( ( MyDisposable0, MyDisposable1 ) )
[
  ...
}
```

**Comment by alrz** [comment]
@AdamSpeight2008 This is already supported:
```cs
using(IDisposable d1 = e1, d2 = e2) {}
```
Also see #9882 and #11420.

**Comment by AdamSpeight2008** [comment]
@alrz That's not what I'm asking. 
Let's we have this function.
```
Function Foo(Of T As IDisposable(Of T), U As IDisposable(Of U)) () As ( T, U )
End Function
```
And it is call within the header of a using block.
```
using( Foo() ) { ... }
 // Will both part of the Tuple<T,U> be disposed?
```
Do the `Tuple<T,U>` dispose correctly the disposable items within the tuple? eg `.Item1` , `.Item2`

**Comment by HaloFour** [comment]
@AdamSpeight2008 

#9882

**Comment by AdamSpeight2008** [comment]
@HaloFour  If the tuple is decomposed into separate variables, we risk the chance of disposing of a copy.

**Comment by HaloFour** [comment]
@AdamSpeight2008 

That proposal goes over several potential implementations.  Either way, this proposal is about `using` for aliases, not `using` for disposables.  #9882 is about `using` for disposables and how that might relate to tuples, if at all.

**Comment by jcouv** [comment]
@gafter Should this be moved to csharplang?

**Comment by gafter** [comment]
@jcouv yes, I'll move it.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #423](https://github.com/dotnet/csharplang/issues/423) via [**ZenHub**](https://www.zenhub.com/)
