### ISSUE TITLE
Info diagnostics are never reported on command line builds

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#1508]
Any analyzer diagnostic which is reported with severity Info isn't displayed on command line builds or in output window when building within VS, but shows up in the IDE error list as part of live analysis.
Not displaying info diagnostics has been the behavior of command line builds since ever, but we may want to change it now.
Another side effect of this is that none of the analyzer exception diagnostics (which are info diagnostics) show up on command line builds.

**Comment by mavasani** [comment]
NOTE: The reasoning behind analyzer exception diagnostics being Info rather than a Warning by default was to avoid build breaks when analyzer throws and warnaserror is set to true.

**Comment by shyamnamboodiripad** [comment]
:+1: We need this. For build lab scenario, I would imagine that someone would want to know if analyzers fail to run in the build lab as part of CI builds for some reason.

**Comment by shyamnamboodiripad** [comment]
A hunch: It may be that compiler is correctly reporting these but MSBuild won't report them under 'Minimal' verbosity which is the default for VS.

**Comment by shyamnamboodiripad** [comment]
Yes looks like the compiler is producing info diagnostics correctly - but MSBuild does not include this in the build output by default. If I set the build output verbosity in VS to 'Detailed', then I can see the info diagnostics in the build output -

![capture2](https://cloud.githubusercontent.com/assets/10579684/6973336/efe20a2a-d93e-11e4-8232-be11543d540a.PNG)

![capture](https://cloud.githubusercontent.com/assets/10579684/6973228/249eed1a-d93e-11e4-8183-c26ee1e3a50a.PNG)

The default verbosity is 'Minimal' and looks like MSBuild does not display the info messages in its output for either 'Minimal' or 'Normal'.

**Comment by shyamnamboodiripad** [comment]
Could you please verify this @mavasani?

**Comment by mavasani** [comment]
Verified.
