### ISSUE TITLE
Indent Guides BlockContextProvider does not show relevant lines

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#15083]
![untitled](https://cloud.githubusercontent.com/assets/10546952/20105027/08db24ec-a5c8-11e6-832d-7e5e50f701be.png)

Showing the last line is probably not going to make it for multiline statements, but neither does the first line as shown in the case of attributes above.

Expected: class names instead of [Serializable]...

**Comment by Pilchie** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/14985
