### ISSUE TITLE
C# should have something akin to My.Resources.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#15082]
`nameof( ... )` reduces the number of magic strings that can easily be missed when renaming the member.
Looking through the framework reference source, I see another source of "magic strings",
That of resource keys / strings, which leads to potential issues when resources are renamed or removed.
Code that references them could be forgotten about,
In this area VB.net has some syntactic sugar around resource strings, that of `My.Resources.`. 
I think C# should also have some of this form of syntactic sugar also.

Possible solutions.
1. Leave as is
2. Use a Code Analyzer,
 *I'm current unsure if resource keys are available to them.*
3. Language Support. eg `my.resources.`

**Comment by DavidArno** [comment]
For those of us who are unfamiliar with VB.NET, would you mind providing my details of `My.Resources` and how it works, please?

**Comment by HaloFour** [comment]
Resource file project items already generate type-safe classes in C#.

**Comment by AdamSpeight2008** [comment]
@HaloFour 
It's not about making them but accessing them, in VB make is easier to access them and, use them.
```VB.net
Module Module1

  Sub Main()
    ' Resource exists
    Dim A As String = My.Resources.ResourceManager.GetString("HelpText")
    Dim B As String = My.Resources.HelpText
    ' Let's say we mis-type the key.
    Dim C As String = My.Resources.ResourceManager.GetString("HelpTxt")
    Dim D As String = My.Resources.HelpTxt
  End Sub

End Module
```
As well has compile-time support for checking it the resource key exists.

Error Reported as compile-time
```
   Severity: Error
       Code: BC30456
Description: 'HelpText' is not a member of 'ConsoleApplication3.My.Resources'.
    Project: ConsoleApplication3
       File: ...\ConsoleApplication3\Module1.vb
       Line: 9
Suppression: Active
```
The previous line `Dim C As String = My.Resources.ResourceManager,GetString("HelpTxt")` is a valid compile.

**Comment by HaloFour** [comment]
@AdamSpeight

I know.  I'm saying that Visual Studio already provides that same functionality for C# projects.
