### ISSUE TITLE
Enum preselection broken.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15090]
![image](https://cloud.githubusercontent.com/assets/4564579/20112166/1ac325d8-a5a0-11e6-822e-5f582c80cbca.png)

After hitting space after the ```==``` 'WaitIndicatorResult' should be selected.  Instead, we've preferred a local parameter.  Specifically teh local parameter i'm already checking :(

**Comment by CyrusNajmabadi** [comment]
tagging @rchande

**Comment by Pilchie** [comment]
Another duplicate of https://github.com/dotnet/roslyn/issues/14813?
