### ISSUE TITLE
EnvDTE.CodeDelegate.Attributes and EnvDTE80.CodeEvent.Attributes returns 0 elements always

### ISSUE THREAD

**Issue by carlos-j-quintero** [dotnet/roslyn#151]
See MS Connect bug:
https://connect.microsoft.com/VisualStudio/feedback/details/1066166/envdte-codedelegate-attributes-and-envdte80-codeevent-attributes-returns-0-elements-always

**Comment by DustinCampbell** [comment]
Fixed with PR #488.
