### ISSUE TITLE
Remove InternalImplementationOnlyAttribute and constrain the analyzer to directly to ISymbol

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#1510]
When we specified `InternalImplementationOnlyAttribute`, it was to be implemented in its own nuget package and imported by the compilers for `ISymbol` and friends. We never implemented that. Instead the implementation we have is tied intimately to the compilers.

The constraints for `ISymbol` and friends can be implemented much more efficiently than the general mechanism currently implemented.

Since we do not appear to be doing the general mechanism, please remove `InternalImplementationOnlyAttribute` and implement the desired constraints directly for the type `ISymbol` and friends.

**Comment by gafter** [comment]
@srivatsn @JohnHamby @mavasani @jaredpar 

Removing my self-assignment, as I won't have time for this in the 1.0 timeframe.

I suspect this is an opportunity for performance improvement in our analyzers.

**Comment by srivatsn** [comment]
While this would be nice, it's not critical for 1.0. Moving to unknown.

**Comment by Youssef1313** [comment]
@mavasani As this issue related to RS1009, I think it should be moved to roslyn-analyzers repository.

**Comment by mavasani** [comment]
I don't think we really want to make this change, there is no net user or code maintenance value add here, and potential perf gain mentioned is likely not significant. I am going to close this out.
