### ISSUE TITLE
Some MSBuildWorkspaceTests fail after updating to Dev15 Preview5

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#15102]
After updating our build to target Dev15 Preview5, and updating the `MSBuildWorkspace` to find the MSBuild 15.0 binaries based on the VS location, the following tests still fail:

* Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestCompilationOptions_VisualBasic_OptionStrict_On
* Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_MetadataReferenceHasDocComments
* Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_CSharp_WithoutPrefer32BitAndConsoleApplication
* Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_CSharp_WithPrefer32BitAndConsoleApplication
* Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_VisualBasic_WithoutPrefer32BitAndConsoleApplication
* Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_VisualBasic_WithPrefer32BitAndConsoleApplication
* Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_WithXaml

During at least some of these test runs we're getting an `InvalidProjectFileException` stating that "The "Csc" task could not be initialized with its input parameters". I'm not sure if that is relevant or not.

**Comment by Pilchie** [comment]
Yes, that seems *very* likely related.  @agocke - any ideas?

**Comment by agocke** [comment]
@Pilchie @tmeschter I'd need more info, like the full exception message + stack, to get a better idea.

**Comment by tmeschter** [comment]
@Pilchie @agocke I'll see what I can do about that.
