### ISSUE TITLE
PopulateSwitch refactorings should be lower priority than other selection based refactorings.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15117]
I selected some code to introduce-local.  I got this:

![image](https://cloud.githubusercontent.com/assets/4564579/20153632/8b3aef02-a678-11e6-8071-22fc16cf5f86.png)

The PopulateSwitch options should not be above the items that are relevant to my selection.

**Comment by CyrusNajmabadi** [comment]
Hrmm... this is hard.  Looks like we compute these guys seperately, then merge them in.  By that time, we've lost information about before/after ordering.  Darn.

**Comment by Pilchie** [comment]
Right - we were originally of the belief that *fixing* something was always of higher priority than refactoring, but that may not be the case always...

**Comment by CyrusNajmabadi** [comment]
This is no longer necessary thanks to https://github.com/dotnet/roslyn/issues/16388
