### ISSUE TITLE
"Set Rule Severity" has no checked items for current effective severity

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#1512]
![nonechecked_effectiveseverity](https://cloud.githubusercontent.com/assets/10605811/6796004/8fd23338-d1a7-11e4-955e-17c44ef2d971.jpg)

I am seeing no severity checked for the default rule. Changing the effective severity to something else causes the new severity to show with a check mark and from then on it always shows the correct effective severity checked.

**Comment by srivatsn** [comment]
I believe the design is that the menu item shows the current severity set in the ruleset file. The effective severity is shown by the icon. See #619 for a discussion of why the distinction matters. Having said that, we should probably have another entry here like "Clear" or "Default" that is simply an action that clears the checkmark and remove the entry from the rulset effective returning the rule to Default status. That would likely help with the confusion here as well.

**Comment by shyamnamboodiripad** [comment]
@tmeschter have we changed the behavior per what @srivatsn suggested above (i.e. add a 'Default' entry?). If you assigned this to me to verify, I think @mavasani  should do that since the bug was logged by him :)

**Comment by shyamnamboodiripad** [comment]
@mavasani Could you please verify this?
