### ISSUE TITLE
Microsoft.DiaSymReader.Native.x86.dll ends up in nuget package

### ISSUE THREAD

**Issue by joperezr** [dotnet/roslyn#15137]
@natemcmaster commented on [Fri Oct 21 2016](https://github.com/dotnet/corefx/issues/12913)

Microsoft.DiaSymReader.Native 1.4.0 includes a .props file as included below. This includes a condition `!Exists('project.json') AND !Exists('$(MSBuildProjectName).project.json')`. The deprecation of project.json means that when users upgrade from a project.json build system to a MSBuild system (and thus deletes project.json), this .props file will include Microsoft.DiaSymReader.Native.{arch}.dll as 'content' in all projects using the .NET Core SDK.

Example: 
dotnet build3 on a netcoreapp will copy the file to the output directory

```
_CopyOutOfDateSourceItemsToOutputDirectory:
  Copying file from "C:\Users\namc\.nuget\packages\microsoft.diasymreader.native\1.4.0\runtimes\win\native\Microsoft.DiaSymReader.Native.x86.dll" to "bin\Debug\netcoreapp1.0\Microsoft.DiaSymReader.Native.x86.dll".
  Copying file from "C:\Users\namc\.nuget\packages\microsoft.diasymreader.native\1.4.0\runtimes\win\native\Microsoft.DiaSymReader.Native.amd64.dll" to "bin\Debug\netcoreapp1.0\Microsoft.DiaSymReader.Native.amd64.dll".
```

The extra file in the output directory may be harmless for "dotnet run", but it's still wrong for .NET Core projects which resolve native assets from the nuget cache.

**The worse problem is "dotnet pack3"**, which includes all 'content' items. This means Microsoft.DiaSymReader.Native.x86.dll and Microsoft.DiaSymReader.Native.amd64.dll will end up in the nuget package of anyone performing "dotnet pack3" on a csproj that uses Microsoft.NETCore.App.  

The offending props file, from .nuget\packages\microsoft.diasymreader.native\1.4.0\build\microsoft.diasymreader.native.props

``` xml
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Condition="!Exists('project.json') AND !Exists('$(MSBuildProjectName).project.json')">
    <Content Include="$(MSBuildThisFileDirectory)\..\runtimes\win\native\Microsoft.DiaSymReader.Native.x86.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)\..\runtimes\win\native\Microsoft.DiaSymReader.Native.amd64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>
</Project>
```

cc @emgarten @piotrpMSFT 

---

@ericstj commented on [Thu Nov 10 2016](https://github.com/dotnet/corefx/issues/12913#issuecomment-259744542)

This isn't a CoreFx package, please open in https://github.com/dotnet/roslyn/issues

---

@joperezr commented on [Thu Nov 10 2016](https://github.com/dotnet/corefx/issues/12913#issuecomment-259744662)

thanks @ericstj I'll move this issue over to roslyn repo.

**Comment by tmat** [comment]
@ericstj I believe the condition is there to detect older versions of nuget that use packages.config. Perhaps we should check for presence of packages.config?

**Comment by ericstj** [comment]
Potentially.  We should ask the NuGet folks for a best practice recommendation for folks who are trying to write packages that work in both a packages.config project, project.json project, and packagereference project.  /cc @rrelyea @emgarten

**Comment by emgarten** [comment]
Checking for ``packages.config`` or ``packages.projectName.config`` is a better option. Project.json and PackageReference type projects will behave the same.

We could potentially improve this by setting a property in the targets/props files auto generated for project.json/packagereference to declare the mode NuGet brought the package in under.  https://github.com/NuGet/Home/issues/3928

For NETCore apps the problem is just that this target is used at all since the dlls come from runtimes, right? Fixing this targets file to work PackageReference would solve that.

I've opened https://github.com/NuGet/Home/issues/3927 to track excluding content items coming from packages, the pack3 behavior you are seeing seems wrong.

**Comment by tmat** [comment]
I have changed the .props file liks so:

```
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Condition="Exists('packages.config') OR Exists('$(MSBuildProjectName).packages.config')">
    <Content Include="$(MSBuildThisFileDirectory)\..\runtimes\win\native\Microsoft.DiaSymReader.Native.x86.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
      <Link>Microsoft.DiaSymReader.Native.x86.dll</Link>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)\..\runtimes\win\native\Microsoft.DiaSymReader.Native.amd64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
      <Link>Microsoft.DiaSymReader.Native.amd64.dll</Link>
    </Content>
  </ItemGroup>
</Project>
```

**Comment by natemcmaster** [comment]
`packages.$(MSBuildProjectName).config` is also a valid name for NuGet 2 config file. (cref https://github.com/NuGet/NuGet2/blob/e89c4b2fc6dc2fc752d2fceecd2a2175b0f4ab69/src/Build/NuGet.targets#L40)

**Comment by tmat** [comment]
OK, I'll add that. Thanks for pointing it out.

**Comment by tmat** [comment]
@natemcmaster Could you confirm that the above snippet is correct and complete now? Thanks.

**Comment by natemcmaster** [comment]
@tmat LGTM

**Comment by jasonmalinowski** [comment]
@tmat good to close now?

**Comment by tmat** [comment]
Yup.

**Comment by rohit21agrawal** [comment]
this is happening with projects that are targeting netcoreapp1.1 as the dependency microsoft.diasymreader.native of Microsoft.netcore.app is bringing in a prop files which adds DLLs into the content item.

This can be prevented by adding ```<Pack>false</Pack>``` on these items
