### ISSUE TITLE
Update Quick Info for string literals to show the length of the string

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#1513]
When hovering over a string literal in the C# editor, the Quick Info only shows "class System.String". It would be helpful if a second line were included which showed the length of the string.

**Comment by Pilchie** [comment]
We should take some care that Quick Info doesn't become so big that it is intrusive by adding a ton of info there.

**Comment by CyrusNajmabadi** [comment]
Having heard no more feedback on this, i think we shoudl close this out as not being worth it.
