### ISSUE TITLE
Update Quick Info for integer literals to show value in multiple bases

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#1514]
Currently the Quick Info for an integer literal in the editor simply shows "struct System.Int32" (or another integer type), along with the summary documentation for that type. It would be helpful if the next 4 lines provided the following:
1. The decimal representation of the number
2. The hexadecimal representation of the number
3. The octal representation of the number
4. The binary representation of the number

In addition, it may be worthwhile to consider including the `char` value for any integer inside that range, though I have not needed this information nearly as many times.

**Comment by Pilchie** [comment]
We should take some care that Quick Info doesn't become so big that it is intrusive by adding a ton of info there.

**Comment by CyrusNajmabadi** [comment]
Unlikely to do this given lack of feedback on this issue.
