### ISSUE TITLE
Refactor non-Roslyn document buffer/view listener hookup 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#15153]
Address concerns from @CyrusNajmabadi in https://github.com/dotnet/roslyn/pull/15106 and move the non-Roslyn document buffer/view listener hookup to appropriate place.

**Comment by Pilchie** [comment]
You've already got a PR out for this, right?

**Comment by mavasani** [comment]
Yes: https://github.com/dotnet/roslyn/pull/15189

**Comment by Pilchie** [comment]
Fixed by #15189
