### ISSUE TITLE
Howto debug VBCSCompiler

### ISSUE THREAD

**Issue by BartNetJS** [dotnet/roslyn#15164]
vbcscompiler.exe is consuming a lot of cpu on a specific solution at the moment the unittest projects are build.
 It is not Always at the same unittest project

For that I like to debug the vbcscompiler

I can start the vbcscompiler project via vs2015, but when building my solution the vbcscompiler.exe from the C:\Program Files (x86)\MSBuild\14.0\Bin folder is started and used.

How can I debug vbcscompiler?

tx

**Comment by gafter** [comment]
Cause vbcscompiler to be started by compiling a small program.

Then attach to that process using the debugger.

Then run the compiles that you wish to debug the behavior of.

**Comment by BartNetJS** [comment]
This is what I tried so far:

* Opened the roslyn.sln in VS2015
* Started the CompilerExtension project in debug mode via VS2015
 * An experimental VS2015 instance is started
 * I open my custom solution in the experimental vs2015
 * initiated a full rebuild
 * after a while I can see VBCSCompiler is launched and eating all the cpu resources
 * but it is the VBCSCompiler from "C:\Program Files (x86)\MSBuild\14.0\Bin" and not from the running instance that is found under "C:\Users\bauweraert\AppData\Local\Microsoft\VisualStudio\14.0RoslynDev\Extensions\Microsoft\Roslyn Compilers\42.42.42.42424"

I also tried to overwrite all the file in the bin folder with the files from the folder above, but then VS2015 complains on compile time about versions

Any help welcome
Tx
