### ISSUE TITLE
Fix double writes in build output

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#15163]
The following projects still have a set of double writes to their build output:

- VisualStudioSetup.Next
- VisualStudioTest.Next

Once addressed the temporary ignore logic needs to be deleted from BuildBoss.

**Comment by jasonmalinowski** [comment]
@jaredpar is this something you're taking care of or we should have the owners of those projects take a look at?

**Comment by jaredpar** [comment]
This is work I'm doing.  I just needed a bug so I could reference it in the code I checked in.  I forgot to assign the bug to myself after filing.
