### ISSUE TITLE
Better generic type inference based on type parameter constraints.

### ISSUE THREAD

**Issue by orthoxerox** [dotnet/roslyn#15166]
**Steps to Reproduce**:
```C#
public static void Foo<T, U>(T value)
    where T: IEnumerable<U>
{
	Console.WriteLine(value.FirstOrDefault().ToString());
}

public static void Main(string[] args)
{
	IEnumerable<int> x = new [] { 1, 2 };
	
	Foo(x);
	
	Console.ReadKey();
}
```
**Expected Behavior**:

The program compiles and runs. The type of `U` is inferred to be `int`, because of `T: IEnumerable<U>`.

**Actual Behavior**:

> The type arguments for method 'Scratchpad.Program.Foo<T,U>(T)' cannot be inferred from the usage. Try specifying the type arguments explicitly. (CS0411)

**Comment by HaloFour** [comment]
I want to say that I've seen this come up before but maybe it was in the comments of a different proposal.  I'm a fan of better generic inference in cases like this, although I have some minor concerns about how recursive such inference might be.  The above case is relatively straightforward

**Comment by TonyValenti** [comment]
I think you might be referencing this issue:
#https://github.com/dotnet/roslyn/issues/5023

**Comment by orthoxerox** [comment]
Covered by https://github.com/dotnet/csharplang/issues/110
