### ISSUE TITLE
Suppress ReplaceMethodWithProperty for overriden method declared outside solution

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#15165]
I would propose to suppress ReplaceMethodWithProperty refactoring for overriden method that are declared outside solution.

An attempt to replace that kind of method with property will always produce invalid code.

#### Code Sample:

```csharp
public class Foo
{
    public override string ToString() // Replace 'ToString' with property
    {
        return base.ToString();
    }
}
```

**Comment by svick** [comment]
Is this a duplicate of https://github.com/dotnet/roslyn/issues/14991?
