### ISSUE TITLE
Quick Info does not render language-specific keywords

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#1516]
Most references to language-specific keywords, such as `null`, are written in the following form in my documentation:

```
<see langword="null"/>
```

In the C# editor in Visual Studio 2013, the tag above is rendered as simply "null" (no quotes, no formatting). In Visual Studio 2015 CTP 6, the word is omitted altogether. This results in very strange documentation in many cases. It would be helpful if, at minimum, the Quick Info in Visual Studio 2015 were updated to include the keyword from this tag.

**Comment by rchande** [comment]
Specifically, the IDE should always include the content of the attribute inside the <see> element. We especially need to not drop href.
