### ISSUE TITLE
Roslyn falls back to use VB glyphs if the language is not C# in GoToDefinitionService results

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#15178]
Found in F# language service:
https://github.com/Microsoft/visualfsharp/issues/1698

![image](https://cloud.githubusercontent.com/assets/15987992/20229730/ec26ae88-a80c-11e6-9894-48200956976b.png)

**Comment by CyrusNajmabadi** [comment]
@OmarTawfik is this still an  issue for you?
