### ISSUE TITLE
Completion for enums doesn't work anymore

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#15186]
In the following code typing a space after typing ```=``` or ```case``` in locations indicated by ```$``` should preselect ```Foo``` but it doesn't.

```C#
    enum Foo { A,B,C }

    class Program
    {
        static void Main(string[] args)
        {
            Foo f =$
            switch (f)
            {
                case$
            }

        }
    }
```

VS build d15rel/15.0.25909.2

**Comment by Pilchie** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/14813
