### ISSUE TITLE
"csc.exe" exited with code -2146232797.

### ISSUE THREAD

**Issue by OlegSkripnyak** [dotnet/roslyn#15194]
**Version Used**:   VS 2015, 14.0.25431.01 Update 3, Android library project 

**Steps to Reproduce**:
Compile the following code:
```
public static class CommonExtensions
{
        public static Func<object, float> ToFloat = o =>
        {
            var o1 = o as dynamic;
            return o1 != null
                ? 0f
                : (float)o;
        };
}
```
**Expected Behavior**: Compiled
**Actual Behavior**: "csc.exe" exited with code -2146232797.

**Comment by jaredpar** [comment]
Thanks for reporting.  We'll take a look at that.

**Comment by OmarTawfik** [comment]
@OlegSkripnyak the following code compiles fine on my side:

```
public static class CommonExtensions
{
        public static System.Func<object, float> To1Float = o =>
        {
            var o1 = o as dynamic;
            return o1 != null
                ? 0f
                : (float)o;
        };
}
```
With the command line on latest from master:
`Binaries\Debug\Exes\csc\csc.exe /t:library repro.cs`

Can you please tell me if you still see it in VS 2017, or in the latest Roslyn builds?

**Comment by OmarTawfik** [comment]
Update: Looking into a VS 2017 RC build, we're actually producing the error:
`Error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'`
Seems to be a missing runtime binder functionality in the Android implementation.

**Comment by OmarTawfik** [comment]
@OlegSkripnyak In VS 2017, it should be fixed by adding a reference to the C# runtime (Microsoft.CSharp.dll) to the project. I'll keep this bug open to track that.

**Comment by OmarTawfik** [comment]
@jaredpar moving to RTM. Following up with template owners.

**Comment by OmarTawfik** [comment]
Filed the following bug on Xamarin team:
https://bugzilla.xamarin.com/show_bug.cgi?id=52454

Closing this one.
