### ISSUE TITLE
No info diagnostics in error list for VB analyzer with LocalizableString message format that throws

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#1519]
1. Create a VB analyzer project using the Roslyn SDK template
2. Create a custom localizable string implementation in this project that throws (i.e. inherit LocalizableString and throw NotImplementedException from all overridden methods).
3. Set the message format for the analyzer (i.e. the const in the analyzer class) to new instance of above LocalizableString
4. Build the analyzer
5. Consume the NuGet package for the analyzer from a new VB console app.

Expected: 
Should see an info diagnostic in the VB console app for NotImplementedException from above localizable string

Observed:
No exception. Instead I see the warnings produced by the analyzer with empty messages (indicating that the exception is being gobbled somewhere)

NOTE: If I create a C# analyzer instead of a VB one above, then the info diagnostic shows up correctly. See below screenshot for what the error list looks like in this case (I have both C# and VB analyzers above referenced in a solution that contains C# and VB console app)

![capture](https://cloud.githubusercontent.com/assets/10579684/6798017/526ac856-d1c6-11e4-958e-677535f88615.PNG)

**Comment by mavasani** [comment]
This might be a dupe of #1521 
In the screenshot you seems to have a C# project in the solution as well, which has the exception diagnostic in error list. Does this issue repro if you just had a VB project in the solution?

**Comment by shyamnamboodiripad** [comment]
@mavasani, you are right this was a dupe. Removing the C# project causes the error to be reported correctly. If I then add back the C# project, I can see all the diagnostics that should have been present.
![capture](https://cloud.githubusercontent.com/assets/10579684/6974874/2e09331c-d94b-11e4-81dd-e95eb18f5d7e.PNG)

I was confused because the repro for this issue was consistent (behaves the same way every time) whereas #1521 was inconsistent. Also #1521 has to do with purely-VSIX scenario whereas this one has to do with the purely-nuget case.

I'll close this issue.
