### ISSUE TITLE
SuppressMessageAttribute not working with namespaces

### ISSUE THREAD

**Issue by giggio** [dotnet/roslyn#152]
I am trying to uses the GlobalSuppressions file to suppress a specific rule on a specific namespace on my test project, like so:

````csharp
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0061", Scope = "namespace", Target = "CodeCracker.Test.Design", Justification = "No need for tests to have async sufix.")]
````

But it does not work. The diagnostic keeps being generated. The method specific works:

````csharp
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0061:TaskNameAsyncAnalyzer", Justification = "No need for tests to have async sufix.", Scope = "member", Target = "~M:CodeCracker.Test.Design.CopyEventToVariableBeforeFireTests.IgnoreMemberAccess")]
````

I guess this is a bug, right?

**Comment by mavasani** [comment]
@giggio This is as per the design of FxCop source level suppressions, and we have retained that design in Roslyn. Please see the note in section "Global-Level Suppressions" in here: https://msdn.microsoft.com/en-us/library/ms244717.aspx

"When you suppress a warning with namespace scope, it suppresses the warning against the namespace itself. It does not suppress the warning against types within the namespace."

@srivatsn By Design?

**Comment by mavasani** [comment]
@shyamnamboodiripad Can you double check if we are fine with the current design for suppress message attribute applied with namespace target? Seems reasonable to me..

**Comment by srivatsn** [comment]
Let's stick to the FxCop convention for the suppressmessage attribute otherwise we will end up breaking a bunch of suppressions in existing code.

**Comment by shyamnamboodiripad** [comment]
I agree it makes sense to stick with the FxCop convention in this case.

**Comment by giggio** [comment]
Ok, it makes sense not to break everyone. But how would then I suppress diagnostics against types inside the namespace? Is that at all possible? Or will I have to add each one individually? This would be really annoying.

**Comment by mavasani** [comment]
You can suppress a diagnostic on the entire type in one of the following ways: 
1) using Scope = "type" and Target = "~T:<FullyQualifiedTypeName>" in the assembly attribute in GlobalSuppressions file OR 
2) By explicitly applying the attribute on the type node without any scope or target.

If either approach doesn't work, its a bug that must be fixed.

**Comment by mavasani** [comment]
But yes, you would have to do it on individual type. Alternatively you can suppress it on the entire assembly by having as assembly attribute with no scope and target.

**Comment by giggio** [comment]
Ok, this is insufficient. The ability to suppress a diagnostic on a specific namespace, including all its types, is really important. I am seeing that there is no way to do this today? May I suggest that feature? :)

**Comment by giggio** [comment]
Just as a follow up, I posted the idea to uservoice: https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/7091554-allow-suppressmessageattribute-to-work-types-withi

**Comment by srivatsn** [comment]
We could just add a new scope called "TypesInNamespace" and specifying a namespace there should suppress in all types in that namespace.

**Comment by srivatsn** [comment]
Created #486 to track this request.

**Comment by mavasani** [comment]
Yes, I don't think implementing this is tough for us in Roslyn. However, it would be good to know the original thinking behind the current design. Probably Nate remembers, let me follow up with him.

**Comment by giggio** [comment]
I will tell you why I need it, and maybe it helps. You can see on my original post above that I am asking for it on the namespace `CodeCracker.Test.Design`. This is a test assembly, `CodeCracker.Test.dll`, and the specific diagnostic we want to suppress is the one that requires the `Async` suffix for async methods. We don't want to have to add `Async` to the end of every test method, it looks ugly, and it is unnecessary. And I want the diagnostic reported on all other methods that are not direct test methods, like test helpers, etc, as I want to know if they are async or not.
Right now we suppressed the diagnostic on the whole assembly, but it is not ideal. Ideally we would suppress only the test namespaces and that would be it.
Thanks for following up on this on #486. :)

**Comment by NickCraver** [comment]
Is there any hope of this being added? I also want this for various Roslyn analyzers, disabling it for all types within a namespace.
