### ISSUE TITLE
IntelliSense should provide completions from the base class for the new keyword

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#15207]
If I type `new ` in a class-level declaration, can you please show every accessible member from the base class?

Like `override`, `new` is only valid as a modifier when hiding a base member.
You should offer completions for hidable (all) base members just like you do for `override`.

**Comment by Pilchie** [comment]
Great idea.

**Comment by CyrusNajmabadi** [comment]
Unlikely to change anything here given lack of customer feedback on these scenarios.
