### ISSUE TITLE
IntelliSense doesn't show read-only class properties in object initializers

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#15205]
**Version Used**: 2015, 15

```C#
class C {
	int x;
	C P { get; } = new C {  };
}
```

Inside the last pair of braces, IntelliSense should show `P`, to allow `new C { P = { x = 2 } }` (which is completely legal).

It currently only shows writable properties and concrete collection properties.

**Comment by SLaks** [comment]
See also https://github.com/dotnet/roslyn/issues/13158

**Comment by SLaks** [comment]
For maximal corner-casey goodness, you should perform a DFS on the type of each property, and only show the property if its type has any reachable properties that are writable or collections (as opposed to https://twitter.com/Schabse/status/797645857881518081, which is useless).

**Comment by diryboy** [comment]
Out of curiosity, why is it legal? You don't have a `set` for `P`.

**Comment by Pilchie** [comment]
This is "Getter-only auto-properties" - They generate a readonly backing field that can be assigned from the constructor.

**Comment by SLaks** [comment]
No; these are nested property initializers.

`P` happens to be a getter-only autoprop, but that's irrelevant, because the `P = {}` isn't happening in that instance's constructor.  @Pilchie, you mean `P = new C {}`, which is illegal.

Inside an initializer, you can write `P = { ... }` (which is illegal elsewhere) to set properties on the _existing value_ of `P`.

`new C { P = { x = 2 } }` compiles to

```C#
C tmp = new C();
tmp.P.x = 2;
```

**Comment by diryboy** [comment]
Oh thank you very much! This syntax is new to me, it was actually [documented in the spec](http://stackoverflow.com/a/16795073/71312) but was not present in [MSDN](https://msdn.microsoft.com/en-us/library/bb384062.aspx) [docs](https://msdn.microsoft.com/en-us/library/bb397680.aspx) by simple google search.

**Comment by zaytsev-victor** [comment]
Can't repro on VS2017 15.2
![15205](https://user-images.githubusercontent.com/23630781/27988247-3d9afcb2-6426-11e7-8d96-3bea519626b7.png)

**Comment by Pilchie** [comment]
@zaytsev-victor your screenshot shows it reproing.  `P` should also be in the list.

**Comment by zaytsev-victor** [comment]
is there any reason why ```IPropertySymbol``` doesn't contain ```IsAutoProperty``` property?

**Comment by CyrusNajmabadi** [comment]
> is there any reason why IPropertySymbol doesn't contain IsAutoProperty property?

It would need cracking of IL to make that determination.  We don't want to have to look at hte implementation of a property to make such a determination.  In a similar vein, we wouldn't even be able to answer the question for something like a reference assembly (since private members are stripped and you don't have access to the IL).

**Comment by zaytsev-victor** [comment]
```csharp
class Foo
{
}

class Bar
{
    public Foo Foo { get; } = new Foo();

    void M()
    {
        var b = new Bar { $$ };
    }
}
```
Should be ```Foo``` shown here?

**Comment by SLaks** [comment]
@zaytsev-victor You're misunderstanding this syntax.

This issue has nothing to do with auto-implemented properties; it's only about collections.  `Foo` should be shown if it is a collection (if its type implements `IEnumberable` and has an `Add()` method), regardless of how the property itself is implemented.

Auto-properties are _purely_ an implementation detail and are completely irrelevant when consuming the symbol, which is why there is no way to check for them.

**Comment by zaytsev-victor** [comment]
> ```Foo``` should be shown if its type has properties that can be be set in initializers

but 
```csharp
class Foo
{
}

class Bar
{
    public Foo Foo { get; } = new Foo();

    void M()
    {
        var b = new Bar { Foo = { } };
    }
}
```
is legal syntax.
So, I think ```Foo``` should be shown.
