### ISSUE TITLE
<see cref> doesn't accept unqualified member names from base types

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#15208]
```C#
class C  {
	///<summary><see cref="ToString"/></summary>
	int x;
}
```

This gives (on both Roslyn and native compilers)

> CS1574: XML comment has cref attribute 'ToString' that could not be resolved

Changing it to `Object.ToString`, or to `x`, works fine.

Why does this name lookup ignore base types?

**Comment by SLaks** [comment]
The spec doesn't say anything about this.

**Comment by gafter** [comment]
Agreed, the spec doesn't say anything about this. The Roslyn binder tries to duplicate, approximately, the previous behavior of the native compiler for compatibility. What you see the compiler doing is what you get.

**Comment by christothes** [comment]
It appears to work if the member reference is fully qualified: 

[Sharplab](D4AQTAjAsAUCAMACAQgQwF4G5axAZkXEQGFEBvWRKxAejsQB4BnAVwFs3UAnATwD5K1OjUQAVABYBLJoi4BTJgHsANgDcFjJnLmIAxvIBmAXgBEyAHQAxRYpM0BMarXoBlRYgAmijQBcpM5m09Q1M0LnMAESsbOz5zQSphFBYfRD9pT28ZADtFVMCdfTljEyjrW3sE5xEGGlYObn4q)

```c#
using System;
using Baz;

public class C {
    /// <summary>
    /// This resolves <see cref="B.Foo"/>
    /// So does this <see cref="Bar.D.Foo"/>.
    /// But this does not <see cref="D.Foo"/>
    /// </summary>
    public void M() {
    }
}

namespace Bar {
    public class D : B
    {
        public override void Foo()
        {
            throw new NotImplementedException();
        }
    }
}

namespace Baz {
    public abstract class B
    {
        public abstract void Foo();
    }
}
```
