### ISSUE TITLE
Naming Styles usability feedback (required) [PR Available]

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#15217]
1. Explanatory text
2. Change "Style" header to "Required Style" or something similar. People were thinking that the chosen style should cause the warning/error/etc., when the enforcement works the other way.

**Comment by dpoeschl** [comment]
@Pilchie @kuhlenh

**Comment by kuhlenh** [comment]
@dpoeschl : #1 refers to explaining the rule hierarchy, correct?

**Comment by dpoeschl** [comment]
@kuhlenh There's not so much a hierarchy as much as an ordering, but yes, that's the idea. It could also explain part of point 2 by saying that the rules are to ensure symbols have the specified naming styles.

**Comment by kuhlenh** [comment]
I think the most confusing part was that only one rule applies--the rules do not cascade.

**Comment by dpoeschl** [comment]
@kuhlenh Gotcha. Will mention that in the explanatory text.

**Comment by dpoeschl** [comment]
`The Required Style of the first rule with a matching Specification will be enforced at the chosen Severity level.`

@kuhlenh @Pilchie any thoughts? Anyone else who was involved in the user study (I'm not sure who those people were)?

**Comment by dpoeschl** [comment]
Nevermind, let's move the discussion to the PR: https://github.com/dotnet/roslyn/pull/15262
