### ISSUE TITLE
Delete our custom config files

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#15229]
This concerns the production of our csc.exe.config, vbc.exe.config and VBCSCompiler.config file.  Today these files are produced through two different processes:

1. Generated in the [GenerateCompilerExecutableBindingRedirects.targets](https://github.com/dotnet/roslyn/blob/master/build/Targets/GenerateCompilerExecutableBindingRedirects.targets) file.
2. Checked into [build/bootstrap](https://github.com/dotnet/roslyn/tree/master/build/bootstrap). 

Having two methods here is an artifact of history, not an explicit design.  It's also a problem because it opens up a significant test gap in our code.

The bootstrap phase of our CI system is the primary way we test our shipping bits.  Essentially build the compiler, copy the shipping bits into a separate directory, and then use those bits to compile the entire repo.

Today instead of using the config files generated in option 1, we explicitly copy the config files from option 2.  Hence this doesn't test the live shipping bits, but instead some unshipping configuration.  Need to remove option 2 and let the bootstrap phase fully use the shipping config files.

**Comment by tmat** [comment]
See also https://github.com/dotnet/roslyn/pull/14879.

**Comment by jaredpar** [comment]
Closed with https://github.com/dotnet/roslyn/commit/4f4907eec0dd95fbbdd7ba2fd9092ded5bf8fe25
