### ISSUE TITLE
Doing a 'restore' from the command line completely hangs VS while Roslyn.sln is open.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15227]
It seems like we're doing a ton of work on the UI thread in a blocking fashion.

**Comment by Pilchie** [comment]
This is fallout from the fact that the project system schedules a synchronous design time build whenever a project.lock.json file changes.  This isn't something that we'll fix in the legacy project system, but should be better in the new CPS based project system.  Tagging @srivatsn and @davkean  for that.

**Comment by CyrusNajmabadi** [comment]
I'd really like this bug to be left open.  That we know what the issue is doesn't mean the issue is not there.  This bug can help us track ensuring that this scenario works well in the new CPS world, whnever it comes online.

**Comment by Pilchie** [comment]
CPS issues are tracked in the dotnet/Roslyn-project-system repo, not here.
