### ISSUE TITLE
Investigate failing tests

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#15223]
Tests:

- Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.ExtractMethod.ExtractMethodTests+SelectionValidator.TestSelectReturnButNotAllCodePathsContainAReturn
- Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.ExtractMethod.ExtractMethodTests+FlowAnalysis.BugFix6313_1
- Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.ExtractMethod.ExtractMethodTests+FlowAnalysis.BugFix6313_6

**Comment by Pilchie** [comment]
@jaredpar Are you going to do this?

**Comment by jaredpar** [comment]
@AlekseyTs can you take a look at this
