### ISSUE TITLE
Error list is slow.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15231]
![image](https://cloud.githubusercontent.com/assets/4564579/20285026/9bfb8176-aa74-11e6-9dd8-9f8d2e3a297b.png)

This is a pretty embarrassing experience.

**Comment by miloush** [comment]
I thought I just have a slow computer, glad to see others are hitting it too for built-in windows.

**Comment by heejaechang** [comment]
curious what cause the infobar to show up. is it UI thread input delay exceeding certain threshold?

**Comment by srivatsn** [comment]
This is the error list itself that pops this up and Roslyn is not involved. Closing as external since this being tracked in the Error list issue database.

**Comment by CyrusNajmabadi** [comment]
@srivatsn can you link me to the error list bug? That way i can actually track this getting fixed?
