### ISSUE TITLE
Make ChangeSignature more flexible.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15230]
After talking with @dpoeschl, i think i want two new capabilities from ChangeSignature:

1. The ability to change names of signature items, and have those renames happen
2. The ability to use ChangeSignature on a tuple.  Both for reordering tuple elements, and for potentially adding/removing names for tuple elements (and having references fixed up).

@dpoeschl Thinks this should be doable.

**Comment by Pilchie** [comment]
Can you collect this in #4510 instead?
