### ISSUE TITLE
Propose that functions have implicit function pointers

### ISSUE THREAD

**Issue by codecore** [dotnet/roslyn#15237]
While writing code that uses recursion, one must explicitly use the function name. If that name changes, one must update that everywhere, including in the function. In the same spirit that every object has a 'this' object pointer, I propose that every function have a 'recurse' function pointer.

`private static Func<int,bool> isEven = (x) => 0 == x % 2;
`
```
    public static int countOdd(IEnumerable<int> numbers, int count)
    {
        if (numbers.Count() == 0) return count;
        return countOdd(numbers.Skip(1), (isEven(numbers.First()) ? count : count + 1));
    }
```        
becomes:

```
    public static int countOdd(IEnumerable<int> numbers, int count)
    {
        if (numbers.Count() == 0) return count;
        return recurse(numbers.Skip(1), (isEven(numbers.First()) ? count : count + 1));
    }
```

**Comment by HaloFour** [comment]
Seems like a very limited benefit to justify adding a new contextual keyword to the language.  Why would `recurse` be any clearer than the actual function name?  And in the use case of issues self-referencing delegate instances within lambda bodies that issue is resolved through local functions which offer hoisting.

**Comment by eyalsk** [comment]
@codecore 

> If that name changes, one must update that everywhere, including in the function.

It's not like people are doing it manually, we have refactoring tools exactly for this reason and if we make a mistake, we probably would get an error so what's the issue? :)

**Comment by codecore** [comment]
@eyalsk I know this. This proposal would mean there is one less place for that code to change.
@HaloFour  For the same reason that 'this' is more convenient than passing in a pointer to your object as the first argument, which is really what is going on. This proposal eliminates the need for some hoisting hack.

**Comment by HaloFour** [comment]
@codecore 

> For the same reason that 'this' is more convenient than passing in a pointer to your object as the first argument, which is really what is going on.

And virtual dispatch.  But passing the current object in a transparent manner has significantly more use cases than having some keyword to represent the current function.  The latter only has the benefit during recursion, which is a relatively uncommon pattern in C#.  I'm not aware of any functional languages that offer a specific keyword for referencing the current function for recursion.  Even there you use the function's name.

**Comment by codecore** [comment]
Fine. Just trying to save some keystrokes, and offer a standard name for the current name for those folks that do recursion. Small effort, small rewards.

**Comment by benknoble** [comment]
@codecore what happens if there is already a function named `recurse` with the same signature? Which one gets called, or is it a compile-time error due to unambiguity? To me that seems problematic and counter-intuitive, especially because because it might break backwards-compatibility as `recurse` could not (as proposed) be made a contextual keyword.

**Comment by eyalsk** [comment]
@codecore 

> I know this. This proposal would mean there is one less place for that code to change.

You make it sound like it's a _huge_ benefit, somehow. 😄 

> For the same reason that 'this' is more convenient than passing in a pointer to your object as the first argument, which is really what is going on. This proposal eliminates the need for some hoisting hack.

Convenience you say? It's more like mandatory in some cases.
```
class Foo
{
	public string foo;
	
	public Foo(string foo)
	{
		this.foo = foo;
		
		FooBar bar = new FooBar(this);
	}

	public Foo() : this("")
	{
	}

	public int this[int i] => i;

	public Foo Chaining() => this;

	class FooBar
	{
		public FooBar(Foo foo)
		{
		}
	}
}
```

> Fine. Just trying to save some keystrokes, and offer a standard name for the current name for those folks that do recursion. Small effort, small rewards.

Are you sure? sometimes typing the function name would be shorter than the keyword `recurse` just as an example `fib`, `sqrt`, `pow`.

**Comment by codecore** [comment]
@benknoble This proposal would make 'recurse' a key word that can only be used in a function. All those projects that currently have a function or variable or type called 'recurse' would learn of this change at compile time.
@eyalsk I did not intend to imply that this would be some huge benefit. In the future I will explicitly indicate that my proposals are trivial and will only benefit me. True, there are as some functions with names shorter that 'recurse'. This does not prevent one from explicitly using the function name, it just provides the option of a standard name for the current function. Thank you for educating me on the extensive required uses for the 'this' keyword. Fortunately, the proposed keyword 'recurse' has no such burden and it's use is optional.

**Comment by HaloFour** [comment]
> This proposal would make 'recurse' a key word that can only be used in a function. All those projects that currently have a function or variable or type called 'recurse' would learn of this change at compile time.

Breaking changes require an exceptionally high bar.  You'll notice that no new keywords introduced to the language after 1.0 resulted in breaking changes.  The keyword could only be used in syntax that was previously illegal (like `yield`) or only considered a keyword when no identifier of that name was in scope (like `var`).

**Comment by eyalsk** [comment]
@codecore I'm sorry if I 'm blunt and maybe a little harsh with my replies, this isn't my intention at all I'm just being honest and my point wasn't to educate you but to show you why I think it isn't as useful as `this`.

Just to clarify I'm not against this feature and I wouldn't mind it but at the same time I really do think that it's _redundant_.

**Comment by codecore** [comment]
@eyalsk No problem. Your points are good.

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
