### ISSUE TITLE
RoslynTaoActions.csproj uses a build task from $(OutDir)

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#15239]
RoslynTaoActions.csproj pulls in a build task from tao.exe, which really irritating since once you do a build MSBuild will then lock the assembly and prevent further builds.

The XInclude support should either be moved to a separate build task, or should be invoked as a process which prevents locking.

(This is incidentally why we also have to have strong name disabled on our build machines which I think @PIlchie has been wondering about.)

**Comment by jasonmalinowski** [comment]
@mavasani can you help out here? It looks like this support was added for project system tests.

**Comment by Pilchie** [comment]
See https://github.com/dotnet/roslyn/issues/13304 for the strong name signing piece

**Comment by mavasani** [comment]
@jasonmalinowski What is the priority of this work? As in, is this blocking our move to Dev15 RC for dogfooding or is it fine to look at this after I am done with my Dev15 perf gap bugs?

**Comment by jasonmalinowski** [comment]
@mavasani Well, right now it means I can't reliably build the closed repro. :-(
