### ISSUE TITLE
Cannot build on macOS Sierra (10.12)

### ISSUE THREAD

**Issue by praeclarum** [dotnet/roslyn#15238]
**Version Used**: master

**Steps to Reproduce**:

1. Run `make` on macOS 10.12

**Expected Behavior**: Compile succeeds

**Actual Behavior**: Error saying the runtime is not supported:

```
$ make
export HOME=/Users/fak ; \
	pushd /Users/fak/Projects/roslyn/build/MSBuildToolset ; \
	/Users/fak/Projects/roslyn/Binaries/dotnet-cli/dotnet restore && \
	/Users/fak/Projects/roslyn/Binaries/dotnet-cli/dotnet publish -o /Users/fak/Projects/roslyn/Binaries/toolset && \
	sed -i -e 's/Microsoft.CSharp.Targets/Microsoft.CSharp.targets/g' /Users/fak/Projects/roslyn/Binaries/toolset/Extensions/Microsoft/Portable/v5.0/Microsoft.Portable.CSharp.targets
~/Projects/roslyn/build/MSBuildToolset ~/Projects/roslyn
log  : Restoring packages for /Users/fak/Projects/roslyn/build/MSBuildToolset/project.json...
log  : Lock file has not changed. Skipping lock file write. Path: /Users/fak/Projects/roslyn/build/MSBuildToolset/project.lock.json
log  : /Users/fak/Projects/roslyn/build/MSBuildToolset/project.json
log  : Restore completed in 1819ms.
Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'osx.10.12-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'osx.10.12-x64' in the 'runtimes' section.
make: *** [/Users/fak/Projects/roslyn/Binaries/toolset] Error 1
```

Some earlier log statements said:

```
log  : Installing runtime.osx.10.10-x64.Microsoft.NETCore.DotNetHost 1.0.1.
log  : Installing runtime.osx.10.10-x64.Microsoft.NETCore.DotNetHostResolver 1.0.1.
log  : Installing runtime.osx.10.10-x64.Microsoft.NETCore.Jit 1.0.4.
```

Is this repo somehow hard coding OS versions (10.10)?

**Comment by Pilchie** [comment]
Tag @jaredpar @agocke

**Comment by Pilchie** [comment]
I feel like @DustinCampbell dealt with some of this for omnisharp at some point...

**Comment by praeclarum** [comment]
Is there a way to go back to using the mono build? This is quite a blocker for me - macOS 10.10 is over two years old...

**Comment by DustinCampbell** [comment]
I spent a far too much time getting OmniSharp fixed to build on macOS Sierra. I actually did have to hard code 10.11-x64 in a call to `dotnet publish`. However, the newer .NET CLI should address this. cc @piotrpMSFT in case he has some insight.

Here's the PR where I fixed this in omnisharp-roslyn: https://github.com/OmniSharp/omnisharp-roslyn/pull/644. The key issue is that we were passing `--infer-runtimes` to `dotnet restore`.

**Comment by praeclarum** [comment]
@DustinCampbell wow that's a lot of infrastructure hacking I'm not comfortable with. Nice hack, but I don't understand any of those changes.

What is the root issue here? Is .NET Core broken on Sierra (I don't think so since I use it every day)? Is Roslyn using an old broken version (must be)? Why doesn't Roslyn bump their .NET Core?

Why was the mono support removed? Is there a switch to use it instead of Core?

**Comment by jaredpar** [comment]
> Why doesn't Roslyn bump their .NET Core?

The short answer is: it's really difficult for us.  😦 

The biggest problem we have is around NuGet restoration.  The last time @agocke and I redid the cross platform build the only official xplat NuGet restore solution was dotnet cli based which implied xproj.  That didn't work for Roslyn as we are largely msbuild / csproj based.  

In order to do the restore it takes a significant amount of bootstrapping on our end.  Bumping the CoreCLR version is expensive because we have to revisit all of that bootstrapping.  Hence we generally don't do it unless we have a need.  

Clearly this is a need, it's just one we weren't aware of until we hit this issue. 

> Why was the mono support removed?

The dotnet tooling in general, and NuGet specifically, was standardizing on CoreCLR for the runtime. As such when they moved we moved too.

**Comment by agocke** [comment]
This may end up being a simple fix -- I'll try adding mocking this up.

However, I like to sit on Apple's old OSes for a while until the new ones have the kinks worked out, so I don't have a Sierra machine ready. I'll finally take the plunge though so that I can test this :)

**Comment by praeclarum** [comment]
Ha, it always comes down to nuget!

@agocke I would be happy to test also.

(It's so weird that we have a compiler sensitive to OS versions :-/)

**Comment by jaredpar** [comment]
> It's so weird that we have a compiler sensitive to OS version

In this case it's more the runtime.  The compiler itself doesn't care what OS it is on except in pretty odd corner cases.  The CoreCLR in this case though is sensitive 😦

**Comment by praeclarum** [comment]
> The CoreCLR in this case though is sensitive

Understood. But if the compiler was just a normal sln + csprojs then I could just build it with mono. Oh well. :-)

**Comment by jaredpar** [comment]
> . But if the compiler was just a normal sln + csprojs then I could just build it with mono. Oh well. :-)

Oh it is.  At the end of the day we just compile CrossPlatform.sln.  The problem is whether or not Mono can restore it 😄
