### ISSUE TITLE
Please publish debug symbols for Release builds

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1524]
Can you please publish PDBs for Roslyn assemblies in NuGet release & VS previews on a symbol server? (or even just as a download somewhere)

I'd be able to give much more detailed bug reports if I could load symbols and see what's actually going on inside a debugger.

**Comment by JoshVarty** [comment]
+1

**Comment by mattwarren** [comment]
+1

**Comment by davkean** [comment]
@ManishJayaswal In this on track for the 1.1 milestone?

**Comment by ManishJayaswal** [comment]
@amcasey likley a dupe of #3

**Comment by amcasey** [comment]
@agocke probably subsumed by #3.

**Comment by agocke** [comment]
Dup of #3
