### ISSUE TITLE
Code shown as miscellaneous file even after NuGet restore completed

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#15241]
Repro step:
1. download `\\mlangfs1\public\gel\UnitTestProject1.zip` and unzip it
2. open solution and restore NuGet packages

Expected behavior: all assemblies referenced though NuGet package should be loaded successfully and code files in projects can be opened as C# file

Actual behavior: warnings say packages not restored; code file still open as misc file; no NuGet reference loaded successfully (see screenshot below) 
Not shown in the picture: Roslyn workspace has the same representation of those projects in memory. 

Explicitly build the solution or click on missing assembly in solution explorer would somehow fix this issue.

@dotnet/roslyn-ide @KevinH-MS @ManishJayaswal

![misc](https://cloud.githubusercontent.com/assets/788783/20288746/7183b998-aa8a-11e6-9b53-45a88122e93c.png)

**Comment by Pilchie** [comment]
@jasonmalinowski @emgarten - Is this a project system issue or a NuGet issue?

**Comment by emgarten** [comment]
It shouldn't be possible for NuGet to influence the project like this for packages.config projects.

**Comment by Pilchie** [comment]
But warnings in the error-list are from NuGet, right?

**Comment by emgarten** [comment]
The highlighted warning in the screen shot is written into the project file. I tried this locally, restore completes but the project system doesn't appear to reload. After closing and reopening the solution manually everything is fine. 

The failed to resolve all project references is a known issue, this can happen when NuGet is unable to determine if an unresolved reference is a project or not and can be ignored here. There is a fix in progress for this that would remove the extra checks for solutions like this.

**Comment by jasonmalinowski** [comment]
Hmm, this should have been moved to project-system, but at this point going to just close. It's too old.
