### ISSUE TITLE
TargetType preselection overrides case-sensitive exact match

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#15246]
**Version Used**: 15 Preview 5

```C#
void M(Task task) => M(Task
```

Opening IntelliSense at the end of this line will preselect lowercase `task`, even though I explicitly typed exactly `Task`.

This is particularly annoying when trying to `await Task.WhenAll()`.

This regression is caused by #11729

**Comment by SLaks** [comment]
Similarly, if I type `M(T`, please preselect `Task` (prefer exact-case prefix matching over target-type matching)

**Comment by Pilchie** [comment]
I think https://github.com/dotnet/roslyn/pull/14210 is intended to fix this, right @rchande?

**Comment by rchande** [comment]
Yep, this is fixed.
