### ISSUE TITLE
Weird IntelliSense Failure

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#15252]
**Version Used**: 15 Preview 5, on Surface Pro 4

I created a Class Library, targeting .Net 4.5.2 or 4.6.1, with the following source:

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

class C {
    void M(int a) { }
}
```

When I press Ctrl+Space with the cursor inside `int`, VS hangs for ~10 seconds, an IntelliSense window wider than the screen briefly appears, then IntelliSense stops working entirely anywhere in that file until I close and reopen it.

This happens consistently in a (literally) brand new Experimental Instance.

No exceptions are thrown (not even cancellation exceptions).

**Comment by Pilchie** [comment]
Tagging @olegtk and @rchande.  @SLaks if you disable completion filtering at Tools\Options\Text Editor\C#\IntelliSense does that prevent the issue?

**Comment by Pilchie** [comment]
Additionally can you try leaving completion filtering on, and turning WPF hardware acceleration off at Tools\Options\Environment\General?

**Comment by SLaks** [comment]
Disabling completion filtering prevents the initial bug (but if you disable it after triggering the bug, IntelliSense still won't work until you reopen the file).
Re-enabling it makes the bug trigger again immediately (even without reopening the file, which is not very surprising).  Interestingly, when I triggered it right after re-enabling, the bug happened more slowly, and I saw the completion list increase in width by one full base width every second or so until it fell off the screen and vanished.

Disabling hardware acceleration has no effect.

**Comment by Pilchie** [comment]
Did you disable the "Enable rich client visual experience" too?  I.e. all 3 of these?  If not, can you try that?

![image](https://cloud.githubusercontent.com/assets/312835/20319587/99a83946-ab23-11e6-9805-bbb680503596.png)

**Comment by SLaks** [comment]
No, I hadn't.
I tried that, and it still had no effect.

**Comment by rchande** [comment]
@olegtk is fixing this in the editor.
