### ISSUE TITLE
Syntax sugar for lazy object

### ISSUE THREAD

**Issue by szguoxz** [dotnet/roslyn#15251]
I have a piece of code for lazy object (The built-in one is not practical to use):
Account _a;
Account Acct => _a ?? (_a=GetAccount(xxx));
-------------
It's the shortest version I can get, but it seems a waste for me to declare Account _a;

Can we have a syntax sugar say:
1. acct ?= GetAccount(xxx); will evaluate GetAccount and assign only when Acct is null? This could be a declaration of field initialization,

2. Account Acct ?=> GetAccount(xxx); Will simply auto generate code for the above? This will be a declaration of a readonly property lazy initialization.

**Comment by MgSam** [comment]
There are many existing proposals for this sort of thing- I suggest you do a search and add your voice to one of those.

**Comment by jnm2** [comment]
https://github.com/dotnet/roslyn/issues/13737

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
