### ISSUE TITLE
Add <EmbedSources>true</EmbedSources> in CSharp/VB.core.targets

### ISSUE THREAD

**Issue by mjsabby** [dotnet/roslyn#15250]
Microsoft (R) Visual C# Compiler version 2.0.0.61104

1. Create a CSProj in VS 2017 RC
2. Try the embedding source feature, via ``<Embed>true</Embed>`` in csproj
3. Looks like the MSBuild wire up doesn't work for this compiler option

**Workaround or another approach**:
``
    <EmbeddedFiles Include="@(Compile);@(AdditionalFiles)" />
``

I'd prefer an option that stays true to the /embed compiler option mainly because it figures out the ``#line`` directive based other files that need inclusion.

This is likely fixable in the Core.targets and the build task. But I'd also like this to work in .NET CLI, I'm assuming that CLI will be using these targets?

**Comment by mjsabby** [comment]
cc @nguerrera

**Comment by nguerrera** [comment]
CLI will be using the same targets so we only need the feature in core targets.

The #line discovery is not supposed to be limited to /embed with no args. The latter is purely shorthand for /embed: repeating all source files. So I would expect the "workaround" to be semantically perfect. 

You might need to put it in a target that runs just before compile if you want to embed anything dynamically added to @(Compile) such as the target framework attribute.

**Comment by mjsabby** [comment]
@nguerrera Ok. I still think we should expose the <Embed>true</Embed> so people don't have to use the Include syntax to get it to work.

**Comment by jcouv** [comment]
@nguerrera I assume this is part of the embed source feature (https://github.com/dotnet/roslyn/issues/12625) and you're the right person to own this. Can you triage into a milestone?

**Comment by tmat** [comment]
I think we should finish embedded source support in 15.6

**Comment by nguerrera** [comment]
Let's track this with #19127. There's bit more detail there.
