### ISSUE TITLE
AnalyzerDependencyCheckerTests have hardcoded dependency on msbuild 14

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#15255]
https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/VisualStudio/Core/Test/AnalyzerSupport/AnalyzerDependencyCheckerTests.vb#L22

**Comment by mavasani** [comment]
This is tracked by https://github.com/dotnet/roslyn/issues/16301.
