### ISSUE TITLE
Upgrade to xunit 2.0 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#1525]
xunit 2.0 has been officially released. We should update BuildAndTest.proj to target this instead of the current alpha version.

**Comment by tannergooding** [comment]
Joining as a 'participant' so I can ensure the standalone tests are updated to use the xUnit 2.0 binaries at the same time.

**Comment by xperiandri** [comment]
Any progress?
Any tasks to do?

**Comment by KevinH-MS** [comment]
@tannergooding where are we at with the xunit 2.1 upgrade?

**Comment by tannergooding** [comment]
We are waiting on @Pilchie and his team to finish upgrading the IDE unit tests.

**Comment by amcasey** [comment]
@tannergooding Done now?

**Comment by jaredpar** [comment]
@amcasey it is done and there was much rejoicing.
