### ISSUE TITLE
TryStatementSyntax's Catches property should return all catch blocks regardless of directives.

### ISSUE THREAD

**Issue by happyhebaby** [dotnet/roslyn#15266]
**Version Used**: version 1.3.2

**Steps to Reproduce**:

For the following sample try catch block:

```c#
            try
            {
                //load the account
                //check for access to method
                int i = 0;
                return;
            }
#if DEBUG
            catch (ApplicationException ex)
            {
                throw new ApplicationException("The internal exception message was: " + ex.Message + ".  The stack trace is: " + ex.StackTrace + ".");
            }
#else
            catch (Exception e)
            {
                string str = e.Message;
                throw new ApplicationException(str);
            }
#endif
```

The TryStatementSyntax object's Catches property only returns only one block depends the value of "DEBUG". In my scenario, I need all the catch blocks returned so I could instrument the complete code. 
After talking with Cyrus of Roslyn team, this is the current behavior and there is no work around. I have to parse the file myself with the different values for the preprocessor directive set, then stich together the disparate edits together.

I would like to argue that this is very undesired behavior, as my guess is many applications around Roslyn could like to instrument the complete source code regardless surrounding symbol values, let user write complex inelegant code to stich them back is way from optimal. Roslyn team should consider to support this in future version to make the scenario much easier to use.

**Comment by CyrusNajmabadi** [comment]
This is orthgonal to try/catches.  This is asking for the Roslyn system to have some way to provide information about code that the language defines as having no meaning. It's similar in ask to having Roslyn tell you what the following code means:

```c#
try 
{
}
// catch (IOException e) { ... }
catch (Exception e)
{
}
```

This is something that is a major 'ask' due to there being near infinite possibilities for what might appear within that #if block.  For example, the #if bug might open a string or comment that then changes the meaning of the other parts of the block (including making the remainder of the preprocessor directives *parse* differently).  

These themselves can have massive downstream effects.  For example, consider just basic preprocessor stuff like:

```c#
#if DEBUG
class 
#else
struct
#endif
MyClass {

}
```

Not only is syntax affected here, but there would be massive semantic fallout from this.

As such, the recommendation for cases like this is: parse your code depending on the sets of options you care about, figure out the changes you would make for the different parse possibilities, and then merge those changes in together to get the final result.

You could wait for us to try to provide a generalized solution for this.  But it's going to be super low on our list, and likely would not be available for years :-/

**Comment by svick** [comment]
As I understand it, the issue is that Roslyn does not parse contents of the `#if` branch that was not taken at all. In your case, if Roslyn did parse it, it would still produce a nice syntax tree, but it's not guaranteed to. For example, consider code like this:

```c#
try
{
    // whatever
}
#if DEBUG
catch (ApplicationException ex)
#else
catch (Exception ex)
#endif
{
    throw new ApplicationException(ex.Message);
}
```

Or even:

```c#
try
{
    // whatever
}
catch (
#if DEBUG
ApplicationException
#else
Exception
#endif
ex)
{
    throw new ApplicationException(ex.Message);
}
```

What would you expect to get in those cases? How is the tree supposed to look like?

One approach to solving your case that I can see would be to remove (or comment out) the directives, perform your instrumentation and then add the directives back.

Another approach would be to perform the instrumentation once with `DEBUG` set and then once with it unset, taking care not to add instrumentation twice to `catch` blocks that are not inside `#if`s.

**Comment by happyhebaby** [comment]
IMHO, for the examples you give, the api could return a single catch block which contains the whole code: I guess for most of the scenarios users only care about getting the complete code for instrumentation, user could further parse it if needed. This output is much more preferred as it returns a value that doesn't break original code integrity. I already have a workaround solution which I am working on. It is relatively ugly, as I have to pre-process and maintain such special case list, as my program requires several SyntaxRewriters processing the code, every SyntaxRewriter will need to implement such logic to stitch result together, which is not efficient, so I chose to maintain the list to stitch back in the last stage.
This is purely a discussion how Roslyn api should return a optimal result. 

    On Tuesday, November 15, 2016 4:05 PM, Petr Onderka <notifications@github.com> wrote:
 

 As I understand it, the issue is that Roslyn does not parse contents of the #if branch that was not taken at all. In your case, if Roslyn did parse it, it would still produce a nice syntax tree, but it's not guaranteed to. For example, consider code like this:try
{
    // whatever
}
#if DEBUG
catch (ApplicationException ex)
#else
catch (Exception ex)
#endif
{
    throw new ApplicationException(ex.Message);
}Or even:try
{
    // whatever
}
catch (
#if DEBUG
ApplicationException
#else
Exception
#endif
ex)
{
    throw new ApplicationException(ex.Message);
}What would you expect to get in those cases? How is the tree supposed to look like?One approach to solving your case that I can see would be to remove (or comment out) the directives, perform your instrumentation and then add the directives back.Another approach would be to perform the instrumentation once with DEBUG set and then once with it unset, taking care not to add instrumentation twice to catch blocks that are not inside #ifs.—

**Comment by happyhebaby** [comment]
My workaround seems to work, although it's a lot of hassle:-) Need to test it on a much larger code base.

**Comment by CyrusNajmabadi** [comment]
We would need a specific proposal about what you're asking for.  Asking for "try-statements" to somehow figure this out would not be a scalable solution as we'd need something for *every* location where you might have #ifdef'ed out code that could enter any sort of construct.

For example, how would you represent the following:

```c#
if (
     a ||
#if debug
     somecondition
#else
    othercondition
#endif
    || b)
{
}
```

What if either of those branches are the complete works of shakespeare? :)

**Comment by CyrusNajmabadi** [comment]
Right now, the try+catch scenario seems totally in your domain.  As such, we are recommending a domain specific solution to the issue you're running into.

**Comment by happyhebaby** [comment]
A quick thought: how about for any object internally contains directive-enclosing code, return a List<SyntaxTrivia, string> property, the first element is the starting directive, the second is the code following the directive until the next directive. Give user a way to query and get back the complete code block is much elegant than return partial incorrect code block, IMHO.
For example, in your first example, the IfStatementSyntax's Condition should be ExpressionSyntax of "     a ||
#if debug
     somecondition
#else
    othercondition
#endif
    || b", then this condition object could have another property which represents directive parts.

**Comment by CyrusNajmabadi** [comment]
You can write such a function already :)

Just walk the tree, and examine it for trivia-directives.  A simple SyntaxWalker can do that job for you.

**Comment by CyrusNajmabadi** [comment]
You can see how we did somethign similar with this helper function: https://github.com/dotnet/roslyn/search?utf8=%E2%9C%93&q=ContainsInterleavedDirective

**Comment by happyhebaby** [comment]
I already did:-) I used SyntaxFactory.ParseStatement instead. However, my point remains the same, return partial code as code content feels like a bug no matter what angel you look at it. 

    On Tuesday, November 15, 2016 6:23 PM, CyrusNajmabadi <notifications@github.com> wrote:
 

 You can see how we did somethign similar with this helper function: https://github.com/dotnet/roslyn/search?utf8=%E2%9C%93&q=ContainsInterleavedDirective—

**Comment by CyrusNajmabadi** [comment]
> However, my point remains the same, return partial code as code content feels like a bug no matter what angel you look at it.

I'm not sure why that is.  As mentioned already, there might be *anything* in #if block.  If you look at my second example, depending on the different ways we go down the block, vastly different items may be returned.  Depending on the interpretation, we may open a string or comment which then causes later preprocessor directives to disappear, etc. etc.

There is no concept of 'partial code' here.  There is the region that is active, and the regions that are inactive.  Those inactive regions could contain *anything*.  All we can do is tell you where they are, and leave it to you *in your domain* to figure out the best way to handle it.  

Remember, people an use these regions for any purpose.  Some people use it for adding prose.  Some use it for conditionally enabling/disabling code.  Some use it to add their own DSLs that other tools use.  

it's like askign us to to understand c# code if it appears in a comment, without recognizing that people use comments for all sorts of things beyond c# code.  As this understanding woudl have to be domain specific, the best way to handle htis is with domain specific code in your tool.

**Comment by DavidArno** [comment]
@happyhebaby,

> I would like to argue that this is very undesired behavior, as my guess is many applications around Roslyn could like to instrument the complete source code regardless surrounding symbol values...

No. Really, really no. What you are requesting might make sense for extreme edge-cases, such as what you are involved with, but I really cannot imagine why I'd ever want some sort of syntax tree with all the variations that get filtered out by preprocessor directives. 

I completely disagree that Roslyn's current behaviour is a bug. There might be legitimate use-cases for what you are asking for, but it would be non-trivial to implement and surely is very low priority compared with 100's of more worthwhile activities that the compiler team could be working on.

**Comment by gafter** [comment]
This request looks attractive in your particular example, as you happen to use the conditional directives in a particularly neat way in that example. The compiler's API has no reason to assume that would be the general case, and I can't see us ever extending the APIs for such as narrow, specific use case.

**Comment by happyhebaby** [comment]
I truly don't think our scenario is extreme edge cases like some claimed: We want to instrumented the whole product code in certain way, then we want to have the whole instrumented code compiled so we can run it to collect analytical data we look for. In order to work around the issue, I have to spend a lot of time implemented a customized language parser, which doesn't seem a desirable way when Roslyn exists.

Just my 2 cents.

**Comment by CyrusNajmabadi** [comment]
@happyhebaby It's not even clear how Roslyn would provide support for this in the first place.  Do you have an actual proposal for how we would do this?  Note that we certainly would not do a single one-off just for try/catches.  As such, your proposal should have a recommendation on how we can deal with this with all cases where #ifdefs exists.  For exampe, how would you deal with something like:

```c#
class C
#if some_platform
    : ISomeInterface
{
      void ISomeInterface.SomeMethod() { }
#elif some_other_platform
    : BaseClass1, IInterface2
{
      public C() : base(...) { }
#else
{
    interface INested { 
#endif

    void Method1() {
#if some_platform
        SomeStatement(); }
#else
        try {
#endif
     SomeInnerStatement();

#if !some_platform
       } catch { }
#endif
    }

#if !some_platform && !some_other_platform
   }
#endif
}
```

**Comment by happyhebaby** [comment]
We are engineers, if there is a need then there should be a way:-) Roslyn should have much richer internal state info than implementing a raw solution from scratch to make this happen. I wrote a 1600 line parser to fulfill my goal. With the rich state info Roslyn collect, it should be much few lines of code to achieve this.

I respect your team have priority on new features and idea way the api should be used, but still our requirement is not weird scenario. I don't have deep understanding of the api yet, I am just trying to help to make a suggestion to make the api more useful to a largest possible set of user scenarios.

**Comment by CyrusNajmabadi** [comment]
> With the rich state info Roslyn collect, it should be much few lines of code to achieve this.

We welcome PRs. :)

> I am just trying to help to make a suggestion to make the api more useful to a largest possible set of user scenarios.

I understand your desire for something to help you out here.  I'm simply pointing out that what you're asking for is not at all trivial to provide.  If you feel otherwise, then we would be happy to integrate in a good solution if you can present one.  Thanks!

**Comment by happyhebaby** [comment]
I can describe in general how I did it: I wrote a customized parser to parse a program into desired format, in the process it also records directive location information; In the same processing step I generate an equivalent program without any directives; This instrumented version gets passed to other parts of the system for further processing; At the last step I stitch the directives back based on earlier location info I collected.

**Comment by CyrusNajmabadi** [comment]
If i were to try that approach with the above code, i would get a completely unparseable syntax tree.  For example, just the starting bit of code would be:

```c#
class C
    : ISomeInterface
{
      void ISomeInterface.SomeMethod() { }

    : BaseClass1, IInterface2
{
      public C() : base(...) { }

{
    interface INested { 
```

**Comment by happyhebaby** [comment]
We have a huge product code base, so far the above methodology works fine. I understand your point, I guess it depends on whether the following processing steps require a complete valid syntax tree. If not, since later the directives are correctly added back, then it's still a valid instrumented version. If does, still there should be some technical way to deal with it. We are good engineers we can invent any wheel for our project:-)

**Comment by CyrusNajmabadi** [comment]
We welcome PRs. 

> We have a huge product code base, so far the above methodology works fine

Roslyn is a set of libraries that have to work properly for all consumers, not just ones who have the precise set of requires as you do though :)    

> If does, still there should be some technical way to deal with it.

It sounds like you came up with a technical way to deal with it already :)

**Comment by happyhebaby** [comment]
I propose the engineer who can elegantly solve this problem be awarded one Turing award. Just joking:-)
