### ISSUE TITLE
Suggestion - Make Intellisense show "almost valid" members

### ISSUE THREAD

**Issue by mirhagk** [dotnet/roslyn#1526]
Intellisense is the feature for me that makes coding flow nicely. If I ever need to jump somewhere else just to remember which name something was, it's break the flow for me, and I lose the context of where I am.

Intellisense with roslyn/visual studio is fantastic, but there are still times when it doesn't work for me. This occurs mostly at the start of a project, and happens when I do something like forget to mark an inner class as public somewhere else.

It would be nice if roslyn/visual studio was able to provide suggestions for things that would be valid if accessibility rules were different, or even if a namespace was being included in the usings. These would obviously need to be distinct from the regular list, and would involve inserting them as well as running a code fix to change something else (change visibility, import namespace etc). I think this feature would solve a lot of the scenarios where you need to switch somewhere else to make a trivial change before getting back to the code you actually want to write.

**Comment by Pilchie** [comment]
This is definitely something that we want to think more about and offer something for.  It won't happen as part of VS 2015, but we will do more thinking.

**Comment by CyrusNajmabadi** [comment]
Not planning on doing this.  Perhaps a space for where intellicode can help with suggestions, even if invalid, and user can go fixup after the fact.
