### ISSUE TITLE
Diagnostic error line numbers for ContainedLanguage documents are not updated when editing outside of Razor & JS script block

### ISSUE THREAD

**Issue by jramsay** [dotnet/roslyn#15278]
Version: D15Rel25831
Filed under RC.2

This issue repros for both JS script blocks & Razor blocks (screenshots below) in contained language documents (.html, .cshtml, etc).  

I noticed that the DocumentDiagnosticAnalyzer methods (AnalyzeSemanticsAsync /AnalyzeSyntaxAsync) are not getting called for the contained language buffer (ex: TypeScript) when the primary buffer (HTML) is edited.  

It feels like these should also be triggered for edits outside of the script blocks.

**Steps to Reproduce**:

1.  In VS, create a new ASP.NET stand-alone app 
2. . Open \Views\Manage\Index.cshtml
2.  Add an error to a the Razor block (ex: @if (Model**..**HasPassword))
3.  Insert a few lines to the HTML above the Razor block

**Expected Behavior**:
Error line numbers for Razor blocks and JavaScript blocks in the Error list are updated

**Actual Behavior**:
Error line numbers are not updated.

![razorcsharp](https://cloud.githubusercontent.com/assets/8161247/20333170/ae3072c4-ab65-11e6-812e-08dea76fd538.png)

![htmlrepro](https://cloud.githubusercontent.com/assets/8161247/20333171/b1da1b8c-ab65-11e6-87ee-70ef3873d2b5.png)

**Comment by heejaechang** [comment]
@jramsay when user types other part of razor file will it update generated cs file? otherwise, we won't know that we need to update line numbers.

**Comment by heejaechang** [comment]
confirmed that razor won't update generated files when outside of script section is changed. so we have no idea whether we need to re-analyze the file or not. someone need to ask us to reanalyze

**Comment by jramsay** [comment]
@heejaechang : Typescript passes in a IVsTextBufferCoordinator when it instantiates Roslyn's ContainedLanguage (AbstractContainedLanguage).  This contains the Primary (RazorCSharp or htmlx) and Secondary (TypeScript) ITextBuffers.  Can you listen for the primary buffers OnChange event to know when to reanalyze?  I'll start a thread with the WTE folks that links to this issue as the above is just a guess and they'll probably be able to point you in the right direction.

**Comment by heejaechang** [comment]
@jramsay thank seems easiest way. let me do that.
