### ISSUE TITLE
TextDocumentState should provide a way to get a text synchronously

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#15279]
See http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/TextDocumentState.cs,105.

We should provide a synchronous implementation, so that if the synchronous method is called on `AsyncLazy` we don't waste a thread.

The tricky bit will be the delays and retries we do in `LoadTextAsync`

**Comment by mattwar** [comment]
Fixed by #15369
