### ISSUE TITLE
"Visual C#" branded as Preview 5 in Help -> About

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15281]
![image](https://cloud.githubusercontent.com/assets/1103906/20336976/44ebee66-ac22-11e6-9ebe-02f0db473c9c.png)

**Comment by Pilchie** [comment]
Interesting.  "Preview 5" doesn't appear anywhere in the Roslyn source code.  I'm not sure where this might be coming from.

**Comment by Pilchie** [comment]
Can you try to track down where this is coming from?

**Comment by davkean** [comment]
I don't trust my install - I installed the latest build on a fresh machine, and it says RC.
