### ISSUE TITLE
[Local Functions] Return from "parent" method

### ISSUE THREAD

**Issue by Unknown6656** [dotnet/roslyn#15288]
_Please do excuse me, if I am not up-to-date concerning the_ `local functions`-_feature, but I have the following question/proposal:_

Should it be possible, to allow a local function to return from the "parent" function?
I mean something along these lines:
```csharp
public void Process( ... )
{
	SomeType obj1 = ...;
	SomeType obj2 = ...; // some resource-intensive objects

	void cleanup()
	{
		// do some object clean up
		obj1.Close();
		obj2.CleanUp();
		obj2.Dispose();

		return return; // return from "parent"
	}


	// main logic begins here
	...

	if (!some_condition_1)
		cleanup();
	...

	if (!some_condition_2)
		cleanup();
	...
}
```
which would be identical to:
```csharp
public void Process( ... )
{
	SomeType obj1 = ...;
	SomeType obj2 = ...; // some resource-intensive objects

	void cleanup()
	{
		// do some object clean up
		obj1.Close();
		obj2.CleanUp();
		obj2.Dispose();
	}


	// main logic begins here
	...

	if (!some_condition_1)
	{
		cleanup();

		return;
	}
	...

	if (!some_condition_2)
	{
		cleanup();

		return;
	}
	...
}
```

As you can see, the statement `return return;` would not only return from the local function, but also from the parent one. _(the syntax or keyword does not really matter to me --- it is more about the point of being able to emit control-statements to the parent function)_

**Comment by HaloFour** [comment]
This has come up before:

https://github.com/dotnet/roslyn/issues/259#issuecomment-156554559

**Comment by agocke** [comment]
Yup, Neal's comment is still relevant: local functions are lowered into their own methods, so they can't interact with the parent method except for through the standard inter-method control flow (e.g., returning to the caller, yielding to the caller, etc.).

Since we're closing down for language features now I'm going to say that even if we liked this feature we wouldn't have time to put it into C# 7.

However, if you really want this feature and want it in a future version of C#, you could make a proposal for language design. For now I'll close this issue, though.

**Comment by CodingOctocat** [comment]
Exception catching can be used:

```CS
private void IPConfigListCvs_Filter(object sender, FilterEventArgs e)
{
    var item = (IPConfigModel)e.Item;
    string keyword = SearchKeyword.ToLower();

    void Contains(Func<IPConfigModel, string> property)
    {
        if (property(item).ToLower().Contains(keyword))
        {
            e.Accepted = true;

            throw new Exception("return");
        }
    }

    try
    {
        Contains(x => x.Title);
        Contains(x => x.IPv4Config.IP);
        Contains(x => x.IPv4Config.Mask);
        Contains(x => x.IPv4Config.Gateway);
        Contains(x => x.IPv4Config.Dns1);
        Contains(x => x.IPv4Config.Dns2);
        Contains(x => x.Remark);
    }
    catch (Exception ex) when (ex.Message == "return")
    {
        return;
    }
}
```
