### ISSUE TITLE
Async state machine fields should be reused where possible for user-defined locals/parameters

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#15290]
Example:
```C#
using System;
using System.Threading.Tasks;

class Test
{
    public static void Main(string[] args) => MainAsync(args).GetAwaiter().GetResult();
    private static async Task MainAsync(string[] args)
    {
        if (args.Length > 0)
        {
            int a = 1;
            await Task.Yield();
            Console.WriteLine(a);
        }
        else
        {
            int b = 2;
            await Task.Yield();
            Console.WriteLine(b);
        }
    }
}
```
In a release build, this generates a state machine with these fields:
```C#
public int <>1__state;
public AsyncTaskMethodBuilder <>t__builder;
private YieldAwaitable.YieldAwaiter <>u__1;
private int <a>5__1;
private int <b>5__2;
public string[] args;
```
Note that that even though the two variables ```a``` and ```b``` are both int and have non-overlapping scopes/lifetimes, the state machine still contains a field for each rather than reusing the same field for both.

Related, consider:
```C#
using System;
using System.Threading.Tasks;

class Test
{
    public static void Main(string[] args) => MainAsync(args).GetAwaiter().GetResult();
    private static async Task MainAsync(string[] args)
    {
        if (args.Length > 0)
        {
            await Task.Yield();
            Console.WriteLine(args.Length);
        }
        else
        {
            string[] data = new string[1];
            await Task.Yield();
            Console.WriteLine(data.Length);
        }
    }
}
```
Even though ```args``` and ```data``` don't have overlapping lifetimes, the compiler still outputs in release a field for each:
```C#
public int <>1__state;
public AsyncTaskMethodBuilder <>t__builder;
private YieldAwaitable.YieldAwaiter <>u__1;
private string[] <data>5__1;
public string[] args;
```

**Comment by VSadov** [comment]
The case of "a" and "b" is doable. We actually intentionally force them into separate fields for debugging reasons. - That does not need to happen with /o+ /debug:pdbonly

**Comment by VSadov** [comment]
The case with "args" and "data" is much harder since the static scopes do intersect. We would need more complete liveness analysis, than we currently do for awaits to prove that actual dynamic lifetimes of "arg" and "data" do not intersect.  
- I.E. if there is a reachable goto at the end of the method going to the beginning, we no longer can clobber "args" hoist by using it for "data". . .

**Comment by bbarry** [comment]
It isn't just the async SM generation that does this, I'd say there is room for this "liveness analysis" before applying the async lowering at all. For example the yield machine would benefit as well:

    public IEnumerable<int> Foo()
    {   
        var c = 1;
        yield return c;
        var d = c+1; 
        yield return d;
        yield return d;
    }

generates a machine with:

    private int <>1__state;
    private int <>2__current;
    private int <>l__initialThreadId;
    private int <c>5__1;
    private int <d>5__2;

[tryroslyn](http://tryroslyn.azurewebsites.net/#b:master/f:r/K4Zwlgdg5gBAygTxAFwKYFsDcAoUlaIoYB0AwgPYA2lqAxsmORCMQOKoSoBOYtOADsABGlXjFqUAhiBAxS2AN7YYKmIJFiAbuTAATGAFkAFAEplqpaqswAZuS6pJtABZHNkrjDBp0XiDAAxcnJTM2sLc3CrCmYqVGIAdR40ABlIVCNvDBMcKJgAX0iCoqL1UVoYAEkAUQhgdG5JEVQAHkhkAD5A4NMiyyj3TwqAXhgARlyohDBUSn0HZGAufz4iq0GYfVHaAGoJmDXVadn51EXlzcnw47mYBaX/XSvi/KA==)

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/22985

**Comment by stephentoub** [comment]
Thanks!
