### ISSUE TITLE
Call to local function referencing then-undeclared variable incorrectly allowed

### ISSUE THREAD

**Issue by khyperia** [dotnet/roslyn#15298]
**Version Used**: 2.0.0.61104 - which is in the recent VS2017RC release.

(Don't have a dev build set up, so I apologize if this has been fixed already - scanned through local function issues and couldn't find any related items, and didn't quickly see any tests with this specific case)

**Repro code**:

```csharp
class Program
{
    static void Main(string[] args)
    {
        Foo();
        int x = 2;
        void Foo() => System.Console.WriteLine(x); // prints "0"
    }
}
```

**Expected Behavior**:

Something similar to the following example:

```csharp
class Program
{
    static void Main(string[] args)
    {
        int x;
        Foo(); // CS0165: Use of unassigned local variable 'x'
        x = 2;
        void Foo() => System.Console.WriteLine(x);
    }
}
```

Ping @dotnet/roslyn-compiler - probably @agocke in particular?

**Comment by jaredpar** [comment]
Thanks for reporting.  Definitely looks like a bug 😄

**Comment by agocke** [comment]
Huh, yeah. I'm not sure what's going on here...
