### ISSUE TITLE
(Idea) LINQ methods

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#153]
LINQ extension methods that also return the **Enumerator**, so that the rest of the sequence can further processed. I think that the `enumerator` be required to be lifted into a capture so it lifetime can persist across multiple methods.
**Example: OnFirst**

    Tuple<IEnumerator<T>,R> OnFirst<T,R>( this IEnumerable<T> xs , initial R, Func<R,T, R> fn )
    {
      var en = xs.GetEnumerator();
      var res = initial;
      if( en.MoveNext() ) 
      {
        res = fn(res, en.Current )
        return Tuple.Create(res, en );
      }
      return res;
    }

**Comment by svick** [comment]
So your proposal is just to add such methods? Could you give an example of how would they be used?

**Comment by AdamSpeight2008** [comment]
This would produce a string with comma delimited values..

`var res = xs.OnFirst("", (p,c)=> p + c ).ForRest( (p,c)=> p+ ", "+c);`

**Comment by jwooley** [comment]
@AdamSpeight2008 For the specific case of generating CSV (or other cases where you add a delimiter before subsequent items), this could be done just with

var res = String.Join(", ", xs)

Many other cases may be handled using the LINQ Aggregate extension without resorting to .ForFirst/ForRest semantics.

**Comment by AdamSpeight2008** [comment]
@jwooley I'm not say that comma separated delimitation is the "definitive" usage case. There could be cases where the enumerator is "expensive", for example databases. #131
did you see the database query case on the other topic. Aggregate also includes the first item when being proceeded. 

Implementations

    public static class exts
    {
      static public Tuple<R,IEnumerator<T>> OnFirst<T,R>
        (this IEnumerable<T> xs, Func<R,T,R> dothis, R initial) 
	    {
	      R output = initial;
	      var en = xs.GetEnumerator();
	      if( en.MoveNext() )
	      {
	        output = dothis( output, en.Current );
	      }
	      return new Tuple<R,IEnumerator<T>>( output, en);
	    }
    
    static public R WithRest<T,R> 
      (this Tuple<R,IEnumerator<T>> tu, Func<R,T,R> dothis )
      {
        var en = tu.Item2;
        R output = tu.Item1;
        while( en.MoveNext() )
       {
          output = dothis( output, en.Current);
       }
       return output;
      }
    }

**Comment by gafter** [comment]
"this is not a proposal I'm just put it out there to see if would be useful."

After more than six months, no others seem to see the utility of the idea, so I'm closing this discussion.
