### ISSUE TITLE
Need .editor_config option for PreferExplicitTupleName.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15307]
Related pr: https://github.com/dotnet/roslyn/pull/15202

@jmarolf

**Comment by CyrusNajmabadi** [comment]
Note: this shoudl likely be done for all our new CodeStyle features.

**Comment by DustinCampbell** [comment]
Also, `PreferObjectInitializer_FadeOutCode` and `PreferCollectionInitializer_FadeOutCode` need editorconfig options as well.

**Comment by Pilchie** [comment]
Hmm - those seem more like presentation things.  I'm not sure I would force them on an entire team through editorconfig.
