### ISSUE TITLE
Completion Ask: Allow completion providers results to be shown immediately, instead of waiting for all providers to complete.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15301]
Ask from MonoDevelop: They have completion providers that might take a *long* time (i.e. due to making actual network http requests).  Right now, this means that displaying results are gated on the longest of these requests completing.  That's problematic in two ways:

1. Completion doesn't appear until all the providers are done.  Making things as slow as the slowest provider.
2. Our 'blocking' model means that users who invoke completion, then hit a commit character, could be blocked for a long time.

If MonoDevelop cannot do something like cache the results on their side, then we'll need something on our side.  Potentially even calling out specific slow providers that we would not wait to present, and which would not cause blocking on things like 'commit'.

**Comment by CyrusNajmabadi** [comment]
@toddgrun @Pilchie @mattwar

**Comment by Pilchie** [comment]
For 1, the problem is how to add things to an existing, sorted list in a way that isn't aggravating to the user.

**Comment by CyrusNajmabadi** [comment]
Correct.  It's already seriously annoying when you get thsi behavior in NavigateTo.  But at least there it's not too bad to just wait till things settle down.  Such behavior though goes entirely against a core goal of intellisense (to be fast and non-intrusive).

**Comment by CyrusNajmabadi** [comment]
this was done, and we have things like import-completion appear later on.  closing out.
