### ISSUE TITLE
"Download .NET Compiler Platform SDK" should not be in root node

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15311]
As per previous discussions should should be removed from the root node:

![image](https://cloud.githubusercontent.com/assets/1103906/20374123/7b16a0aa-acca-11e6-8393-c0ae91e9e94e.png)

**Comment by davkean** [comment]
tag @jmarolf

**Comment by davkean** [comment]
Don't forget Visual Basic as well.

**Comment by davkean** [comment]
Looks like the VB one has the wrong priority too, it sorts above the VSIX templates, whereas C# sorts below them:

![image](https://cloud.githubusercontent.com/assets/1103906/20374401/74e8e29a-accc-11e6-887e-d61d43e45d3d.png)

**Comment by davkean** [comment]
Putting this in IDE, so it gets triaged, hint hint... :)

**Comment by Pilchie** [comment]
I think @jmarolf was going to take a look at this this week.

**Comment by jmarolf** [comment]
fixed with https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/50349
