### ISSUE TITLE
GenerateMethod should generate a bool return type if it can't figure out a type, and the method starts with "Is"

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15315]

**Comment by orthoxerox** [comment]
Or 'Has' or 'Can'?

**Comment by bkoelman** [comment]
"Supports", "Contains"

**Comment by DavidArno** [comment]
Hmm, so `IssueReportGenerator` will be created as a `bool` method, but `ProblemReportGenerator` won't.

😛

**Comment by Pilchie** [comment]
@DavidArno generally we would also check for the next letter being capitalized to avoid issues like that.
