### ISSUE TITLE
Change in method overload resolution?

### ISSUE THREAD

**Issue by andrew-vandenbrink** [dotnet/roslyn#15318]
**Version Used**: 
4.6.1
**Steps to Reproduce**:

1. Create 2 methods
```
Info(string message); //1st
Info(string message, params object[] args); //2nd
```
2. Call the method
 ```
Info("XXXXXXXXXXXXXXXXXXXXXXXXX " + this.A +
", xxxxxxxxxxx: " + this.B);
```

**Expected Behavior**:
Method overload resolution should choose the first method as in previous version

**Actual Behavior**:
Method overload resolution choose 2nd method

This causing a bug just by recompiling to the latest .net framework.
as the 2nd method contains logic like this.
```
string x=string.Format(message,args);//throw exception when message contains something like "aa{4}"
```

**Comment by svick** [comment]
I can't reproduce this in a trivial .Net 4.6.1 console application in VS 2015 Update 3.

How exactly are you compiling your code? From VS? Which version (including update number)? (4.6.1 is not a version of the compiler, it's a version of .Net, which is not relevant.)

Could you share complete code that demonstrates the issue?

**Comment by andrew-vandenbrink** [comment]
From VS, 
![image](https://cloud.githubusercontent.com/assets/12871379/20392355/bd12506e-acd7-11e6-9e32-6e7bddeffe0f.png)

![image](https://cloud.githubusercontent.com/assets/12871379/20392910/26f17558-acda-11e6-8bc1-2ade16e0e2eb.png)


I can't share full code,

I can write something similar, don't ask why the code like that, its old application that I need to maintain..

Just copy paste to Program.cs
```
using System;
using System.Collections.Generic;

using System.Text;


namespace ConsoleApplication2
{
    public class BaseMonitor
    {

        protected virtual void Info(string message)
        {
        }
    }

    public class Monitor : BaseMonitor
    {

        public void Info(string message, params object[] args)
        {
            string x = string.Format(message, args);

        }

        protected override void Info(string message)
        {

        }
    }


    public class Business : Monitor
    {

        public void Test()
        {
            base.Info("Test{4}");//throw exception
        }

    }

    class Program
    {
        static void Main(string[] args)
        {
            Business b = new Business();
            b.Test();
        }
    }
}

```

Confirmed changing .net framework/visual studio got nothing to do with this

the old version doesn't have this signature, that's why the old one working fine....
```
Info(string message, params object[] args)
```

so looks like expected behavior I guess?

**Comment by svick** [comment]
Yeah, as far as I can tell, this is the excepted behavior according to the C# spec:

From [Overload resolution](https://github.com/ljw1004/csharpspec/blob/gh-pages/expressions.md#overload-resolution):

> the set of candidates for a method invocation does not include methods marked `override`, and methods in a base class are not candidates if any method in a derived class is applicable.

This means that `Monitor.Info(string)` is not a candidate and since `Monitor.Info(string, params object[])` is applicable, `BaseMonitor.Info(string)` is also not a candidate.

I wonder if being able to declare a method as `new override` (i. e. `override` the base method, but also consider the method to be declared here for the purpose of overload resolution) would make sense in cases like this (it's not something the compiler would currently allow ).

**Comment by andrew-vandenbrink** [comment]
Thanks I will close the issue as its expected behavior.
