### ISSUE TITLE
References to CoreLib private assemblies

### ISSUE THREAD

**Issue by praeclarum** [dotnet/roslyn#15321]
**Version Used**: 2.0.0-beta5

**Steps to Reproduce**:

1. Create a Xamarin.Mac project
2. Reference CodeAnalysis.CSharp
3. Build

**Expected Behavior**: Successful build

**Actual Behavior**:

Build fails with:

    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets: 
      error :   Bundle Resource 'Facades/System.Private.CoreLib.InteropServices.dll' not found on disk (should be at '/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/Facades/System.Private.CoreLib.InteropServices.dll')
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets: 
      error :   Bundle Resource 'Facades/System.Private.CoreLib.Threading.dll' not found on disk (should be at '/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/Facades/System.Private.CoreLib.Threading.dll')

For some reason Roslyn references CoreCLR assemblies. This is totally not cool when trying to build with mono.

This was discovered after I filed a Xamarin.Mac bug: https://bugzilla.xamarin.com/show_bug.cgi?id=46956

This is a pretty big roadblock for me. Can these references be removed?

**Comment by praeclarum** [comment]
Hello. My iOS app Continuous makes use of Roslyn but I can't update until this bug is fixed. It's a big regression for me. 

I wonder if someone would look at this and assign a milestone so that I can plan the next releases of my app accordingly.

**Comment by praeclarum** [comment]
I cannot find any direct references to the assemblies but the project lock file (whatever that is) seems to contain direct references.

I would love to fix this for you an submit a PR but I don't understand Roslyn's dependence on the Core CLR enough. I could really use some guidance here.

```
$ grep -r "System.Private.CoreLib" .
Binary file ./Binaries/dotnet-cli/shared/Microsoft.NETCore.App/1.0.0-rc3-004338/libcoreclr.dylib matches
Binary file ./Binaries/dotnet-cli/shared/Microsoft.NETCore.App/1.0.0-rc3-004338/Microsoft.CSharp.dll matches
./Binaries/dotnet-cli/shared/Microsoft.NETCore.App/1.0.0-rc3-004338/Microsoft.NETCore.App.deps.json:          "runtimes/osx.10.10-x64/lib/netstandard1.0/System.Private.CoreLib.dll": {},
./Binaries/dotnet-cli/shared/Microsoft.NETCore.App/1.0.0-rc3-004338/Microsoft.NETCore.App.deps.json:          "runtimes/osx.10.10-x64/native/System.Private.CoreLib.ni.dll": {},
Binary file ./Binaries/dotnet-cli/shared/Microsoft.NETCore.App/1.0.0-rc3-004338/mscorlib.dll matches
Binary file ./Binaries/dotnet-cli/shared/Microsoft.NETCore.App/1.0.0-rc3-004338/System.Private.CoreLib.dll matches
Binary file ./Binaries/dotnet-cli/shared/Microsoft.NETCore.App/1.0.0-rc3-004338/System.Private.CoreLib.ni.dll matches
./build/MSBuildToolset/project.lock.json:          "runtimes/osx.10.10-x64/lib/netstandard1.0/System.Private.CoreLib.dll": {},
./build/MSBuildToolset/project.lock.json:          "runtimes/osx.10.10-x64/native/System.Private.CoreLib.ni.dll": {},
./build/MSBuildToolset/project.lock.json:          "runtimes/ubuntu.14.04-x64/lib/netstandard1.0/System.Private.CoreLib.dll": {},
./build/MSBuildToolset/project.lock.json:          "runtimes/ubuntu.14.04-x64/native/System.Private.CoreLib.ni.dll": {},
./build/MSBuildToolset/project.lock.json:        "runtimes/osx.10.10-x64/lib/netstandard1.0/System.Private.CoreLib.dll",
./build/MSBuildToolset/project.lock.json:        "runtimes/osx.10.10-x64/native/System.Private.CoreLib.ni.dll",
./build/MSBuildToolset/project.lock.json:        "runtimes/ubuntu.14.04-x64/lib/netstandard1.0/System.Private.CoreLib.dll",
./build/MSBuildToolset/project.lock.json:        "runtimes/ubuntu.14.04-x64/native/System.Private.CoreLib.ni.dll",
```

**Comment by jaredpar** [comment]
Sorry for the delay.  I heard about this issue in a xamarin slack chat and had been discussing it there.  Didn't realize we had a public facing bug on it.

> For some reason Roslyn references CoreCLR assemblies. 

To be clear Roslyn does not reference CoreCLR private assemblies.  I double checked this when I first saw the bug and even dug through our compiled assemblies to make sure it wasn't sneaking in the back door somewhere.  Was able to verify this for the binaries produced from our Windows build.  

> Reference CodeAnalysis.CSharp
> I cannot find any direct references to the assemblies but the project lock file (whatever that is) seems to contain direct references.

I'm not seeing the same behavior even on my MacBook.  The CodeAnalysis.CSharp project in source is located at `src/Compilers/CSharp/Portable`.  The lock file in that directory doesn't contain any private assemblies references on my machine.  

> ./build/MSBuildToolset/project.lock.json

I also see a lot of references to private CoreCLR assemblies here but that is expected.  This project is part of our compiler bootstrapping process.  Essentially it builds some NuGet components we need so that we can actually run a restore on CrossPlatform.sln.  This isn't a part of our shipping toolset.  It's a (very hacky) tool for enabling NuGet restore on Mac / Linux. 

I'm curious why this is a blocker to your scenario.  It's not a tool we distribute or would even recommend others using.  We hope to delete it as soon as cross plat MSBuild based NuGet restore is a viable solution.

**Comment by praeclarum** [comment]
Thanks for taking a look!

It's a blocker because I can't compile a Xamarin.Mac app that references the CodeAnalysis.CSharp nuget (see original post errors). I used to be able to do this, but 2.0.0-beta5 has these Private references. (Please see the Xamarin bug.)

To be clear, I am not using a custom build or anything - just a nuget reference from Xamarin.Mac.

**Comment by jaredpar** [comment]
>  I used to be able to do this, but 2.0.0-beta5 has these Private references. (Please see the Xamarin bug.)

As I stated in my comment though we don't see these references anywhere.  We've looked in the lock file, the assembly, the NuSpec file and none have these references.

**Comment by praeclarum** [comment]
OK, something fishy is happening then. I will close this while I figure out where the heck those references are coming from...

Thank you for your attention.

**Comment by jaredpar** [comment]
Please do let us know.  It's very possible we're doing this in some indirect way that we don't realize.  If so would be happy to fix.

**Comment by itsho** [comment]
although very old issue, I like to know if there are more details.

I've bumped into this bug via another bug - https://github.com/obfuscar/obfuscar/issues/205.

So I did a test:
* I've used a SDK csproj (_Microsoft.NET.Sdk.WindowsDesktop_) targeted for **net461**
* Compiled with **msbuild** (directly in _Visual Studio_) and got these references:
![viaMSBUILD](https://user-images.githubusercontent.com/1774797/99667068-80c68980-2a74-11eb-8d30-b1168c3cae5f.png)
* Compiled with **dotnet.exe** CLI and got these references (**added** _System.IO.Compression_ and _System.Private.CoreLib_)!
![viaDOTNET](https://user-images.githubusercontent.com/1774797/99667022-6f7d7d00-2a74-11eb-8af3-208adac24743.png)

Thanks.
