### ISSUE TITLE
Without a ref to System.ValueTuple, the VB compiler reports diagnostics that are not helpful

### ISSUE THREAD

**Issue by AlessandroDelSole** [dotnet/roslyn#15328]
**2017 RC**: 

**Steps to Reproduce**:

1. Create a Visual Basic application
2. Write some code based on tuples (e.g. Dim foo As (Integer, Integer) )

**Expected Behavior**:
The IDE should automatically include a reference to System.ValueTuple or the compiler should report a meaningful diagnostic saying that a reference to that library is required, possibly with a quick action. Folks who have never used tuples before might be confused by the current messages.

**Actual Behavior**:
Red squiggles and the compiler reports the following:

Cannot define a class or member that utilizes tuples because the compiler required type 'System.Runtime.CompilerServices.TupleElementNamesAttribute' cannot be found. Are you missing a reference?

Predefined type 'ValueTuple(Of ,)' is not defined or imported.

**Comment by AdamSpeight2008** [comment]
#15177

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/15177
