### ISSUE TITLE
Naming style "require uppercase" doesn't allow numerics or non-Latin characters

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#15326]
From: https://developercommunity.visualstudio.com/content/problem/2440/uppercase-naming-with-number.html

```C#
internal enum ButtonState : uint
{
    FROM_LEFT_1ST_BUTTON_PRESSED = 0x01,
    RIGHTMOST_BUTTON_PRESSED = 0x02,
    FROM_LEFT_2ND_BUTTON_PRESSED = 0x04,
    FROM_LEFT_3RD_BUTTON_PRESSED = 0x08,
    FROM_LEFT_4TH_BUTTON_PRESSED = 0x10
}
```

All of the enums that contain a number 1,2,3,4 fail the naming convention of uppercase.  Is there anyway to configure naming to force uppercase and allow numbers?

**Comment by davkean** [comment]
Make sure the character you are checking actually has a concept of case before checking if its upper case.

**Comment by Pilchie** [comment]
Is there a handy API for that?

**Comment by davkean** [comment]
Char.GetUnicodeCategory will return a enum describing the char - or just try upper case it, and see if the character changes.

**Comment by QuickC** [comment]
Also note that Kinds of type "Local variable" & "parameter" are needed

**Comment by Pilchie** [comment]
Note also non-latin languages like in #15486

**Comment by dpoeschl** [comment]
Actually a globalization issue for non-Latin languages.
