### ISSUE TITLE
Formatter doesn't clean up whitespace within :=

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#1534]
Invoke a method with a named argument.  Put a space between the colon and the equals sign.  Invoke the formatter (e.g. newline after call).

e.g. M(x : = 1)

Expected: M(x:=1)
Actual: M(x: =1)

Note that space _around_ the operator is formatted.

**Comment by amcasey** [comment]
FYI @heejaechang

**Comment by amcasey** [comment]
This is a regression from dev12.

**Comment by heejaechang** [comment]
@basoundr adding Balaji since he is fixing formatting bugs nowadays.
