### ISSUE TITLE
Suggestion ellipses look bad on single-character spans

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#15350]
![image](https://cloud.githubusercontent.com/assets/235241/20420962/dacf75c6-ad15-11e6-98eb-078405046974.png)

Maybe this is by design? @CyrusNajmabadi @kuhlenh

**Comment by CyrusNajmabadi** [comment]
That looks pretty bad :)

we should probably make the minimum tag-span 2 chars so that you always get 3 dots.

**Comment by Pilchie** [comment]
Note that it also depends on DPI and font sizes.
