### ISSUE TITLE
Add Nuget Package fails when "Save new projects when created" is not enabled.

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#15355]
1. Go to Tools\Options\Projects and Solutions and uncheck "Save new projects when created".
2. Go to Tools\Options\Text Editor\C#\Advanced and enable "Suggest usings for types in NuGet packages"
3. Create  new Console Application
3. Type `JToken`
4. Invoke "Add NuGet package".

**RESULT**
```
---------------------------
Microsoft Visual Studio
---------------------------
Installing 'Newtonsoft.Json' failed.



Additional information: Exception has been thrown by the target of an invocation.
---------------------------
OK   
---------------------------
```

**EXPECTED** 
At least a better error message

**Comment by Pilchie** [comment]
With the change to invoke via reflection, we need to unwrap `TargetInvocationException`, unless you can get rid of that reflection soon.

**Comment by CyrusNajmabadi** [comment]
With my change you now get: 

![image](https://cloud.githubusercontent.com/assets/4564579/20692839/5b119d46-b58f-11e6-9d30-709a2fc5d1fe.png)

Which is better...
