### ISSUE TITLE
750MB Task allocations

### ISSUE THREAD

**Issue by asecchia** [dotnet/roslyn#15363]
@CyrusNajmabadi 

```
Type System.Threading.Tasks.Task`1[Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeDeclarationInfo]                           2.2   216,892,224
Type System.Threading.Tasks.Task`1[System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.FindSymbols.Symbo  2.2   215,644,096
Type System.Threading.Tasks.Task`1[Microsoft.CodeAnalysis.FindSymbols.IDeclarationInfo]                                    2.1   204,420,560
Type System.Threading.Tasks.Task`1[Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeIdentifierInfo]                            1.2   118,173,792
```

These 4 Task allocations are contributing to 750MB of allocation activity happening in ServiceHub. They should be pretty easy to remove.

**Comment by asecchia** [comment]
Name                                                                                                                                                                                                                 	Inc %	           Inc
 Type System.Threading.Tasks.Task`1[Microsoft.CodeAnalysis.FindSymbols.IDeclarationInfo]                                                                                                                             	  2.0	   208,883,968
+ mscorlib.ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].GetTaskForResult(System.__Canon)                                                                                              	  2.0	   208,777,440
|+ mscorlib.ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].SetResult(System.__Canon)                                                                                                    	  2.0	   208,777,440
| + microsoft.codeanalysis.workspaces!Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions+<GetDeclarationInfoAsync>d__7.MoveNext()                                                                           	  2.0	   208,777,440
|  + mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].Start(!!0&)                                                                                                                   	  2.0	   208,777,440
|   + microsoft.codeanalysis.workspaces!DocumentExtensions.GetDeclarationInfoAsync                                                                                                                                   	  2.0	   208,777,440
|    + microsoft.codeanalysis.workspaces!Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder+<FindImmediatelyInheritingTypesInDocumentAsync>d__25.MoveNext()                                                      	  2.0	   208,777,440
|     + mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.FindSymbols.SymbolAndProjectId`1[System.__Canon]]].Start(!!0&)        	  2.0	   208,777,440
|      + microsoft.codeanalysis.workspaces!DependentTypeFinder.FindImmediatelyInheritingTypesInDocumentAsync                                                                                                         	  2.0	   208,777,440
|       + microsoft.codeanalysis.workspaces!Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder+<>c__DisplayClass23_0.<FindSourceTypesInProjectAsync>b__1(class Microsoft.CodeAnalysis.Document)                  	  2.0	   208,777,440
|        + system.core!System.Linq.Enumerable+<>c__DisplayClass7_0`3[System.__Canon,System.__Canon,System.__Canon].<CombineSelectors>b__0(!0)                                                                        	  2.0	   208,777,440
|         + system.core!System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.__Canon,System.__Canon].MoveNext()                                                                                             	  2.0	   208,777,440
|          + system.core!System.Linq.Buffer`1[System.__Canon]..ctor(class System.Collections.Generic.IEnumerable`1)                                                                                                  	  2.0	   208,777,440
|           + system.core!Enumerable.ToArray                                                                                                                                                                         	  2.0	   208,777,440
|            + microsoft.codeanalysis.workspaces!Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder+<FindSourceTypesInProjectAsync>d__23.MoveNext()                                                              	  2.0	   208,777,440
|             + mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.FindSymbols.SymbolAndProjectId`1[System.__Canon]]].Start(!!0&)	  2.0	   208,777,440
|              + microsoft.codeanalysis.workspaces!DependentTypeFinder.FindSourceTypesInProjectAsync                                                                                                                 	  2.0	   208,777,440
|               + microsoft.codeanalysis.workspaces!Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder+<FindTypesInProjectAsync>d__13.MoveNext()                                                                 	  2.0	   208,777,440


Name                                                                                                                                                                                                            	Inc %	           Inc
 Type System.Threading.Tasks.Task`1[System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.FindSymbols.SymbolAndProjectId`1[Microsoft.CodeAnalysis.INamedTypeSymbol]]]                            	  2.0	   207,128,512
+ mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.FindSymbols.SymbolAndProjectId`1[System.__Canon]]].GetTaskForResult(!0)	  2.0	   206,918,016
|+ mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.FindSymbols.SymbolAndProjectId`1[System.__Canon]]].SetResult(!0)      	  2.0	   206,918,016
| + microsoft.codeanalysis.workspaces!Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder+<FindImmediatelyInheritingTypesInDocumentAsync>d__25.MoveNext()                                                    	  2.0	   203,435,552
| |+ mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.FindSymbols.SymbolAndProjectId`1[System.__Canon]]].Start(!!0&)      	  2.0	   203,435,552
| | + microsoft.codeanalysis.workspaces!DependentTypeFinder.FindImmediatelyInheritingTypesInDocumentAsync                                                                                                       	  2.0	   203,435,552


Name                                                                                                                                                              	Inc %	           Inc
 Type System.Threading.Tasks.Task`1[Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeDeclarationInfo]                                                                 	  1.9	   201,569,072
+ mscorlib.ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].GetTaskForResult(System.__Canon)                                           	  1.9	   201,356,464
|+ mscorlib.ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].SetResult(System.__Canon)                                                 	  1.9	   201,356,464
| + microsoft.codeanalysis.workspaces!Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeInfo+<GetInfoAsync>d__6`1[System.__Canon].MoveNext()                           	  1.9	   201,356,464
|  + mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].Start(!!0&)                                                                	  1.9	   201,356,464
|   + microsoft.codeanalysis.workspaces!SyntaxTreeInfo.GetInfoAsync                                                                                               	  1.9	   201,356,464
|    + microsoft.codeanalysis.workspaces!Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions+<GetDeclarationInfoAsync>d__7.MoveNext()                     	  1.9	   201,356,464
|     + mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].Start(!!0&)                                                             	  1.9	   201,356,464
|      + microsoft.codeanalysis.workspaces!DocumentExtensions.GetDeclarationInfoAsync                                                                             	  1.9	   201,356,464
|       + microsoft.codeanalysis.workspaces!Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder+<FindImmediatelyInheritingTypesInDocumentAsync>d__25.MoveNext()	  1.9	   201,356,464


Name                                                                                                                                                                    	Inc %	           Inc
 Type System.Threading.Tasks.Task`1[Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeIdentifierInfo]                                                                        	  1.1	   118,711,696
+ mscorlib.ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].GetTaskForResult(System.__Canon)                                                 	  1.1	   118,711,696
 + mscorlib.ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].SetResult(System.__Canon)                                                       	  1.1	   118,711,696
  + microsoft.codeanalysis.workspaces!Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeInfo+<GetInfoAsync>d__6`1[System.__Canon].MoveNext()                                 	  1.1	   118,391,104
  |+ mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].Start(!!0&)                                                                      	  1.1	   118,391,104
  | + microsoft.codeanalysis.workspaces!SyntaxTreeInfo.GetInfoAsync                                                                                                     	  1.1	   118,391,104
  |  + microsoft.codeanalysis.workspaces!SyntaxTreeInfo.GetIdentifierInfoAsync                                                                                          	  1.1	   118,391,104
  |   + microsoft.codeanalysis.workspaces!Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractReferenceFinder+<>c__DisplayClass6_0+<<FindDocumentsAsync>b__0>d.MoveNext()	  1.1	   110,351,184


more detailed stacks

**Comment by CyrusNajmabadi** [comment]
Can you update this with the current allocatins?

**Comment by asecchia** [comment]
this is what remains after the above merge:
Name                                                                                                                                                                                	Exc %	        Exc
Type System.Threading.Tasks.Task`1[System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.FindSymbols.SymbolAndProjectId`1[Microsoft.CodeAnalysis.INamedTypeSymbol]]] 	  1.1	 73,806,144
Type System.Threading.Tasks.Task`1[Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeDeclarationInfo]                                                                                    	  1.0	 72,839,848
Type System.Threading.Tasks.Task`1[System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.FindSymbols.SymbolAndProjectId`1[Microsoft.CodeAnalysis.INamedTypeSymbol]]][] 	  0.4	 30,335,564


approximately 170MB (down from 750)

**Comment by Pilchie** [comment]
@CyrusNajmabadi  - note the question on #15364 about whether it's worth taking that to the `dev15-rc2` branch.

**Comment by CyrusNajmabadi** [comment]
I dunno :)  What's the bar for RC2?

**Comment by CyrusNajmabadi** [comment]
Have tried to reduce the 170MB of allocs here https://github.com/dotnet/roslyn/pull/15541

Let me know if you run into more egregious outliers!
