### ISSUE TITLE
C# Language Suggestion: Concise nested class definitions

### ISSUE THREAD

**Issue by ryantrem** [dotnet/roslyn#1537]
I can define a namespace as:

``` C#
namespace Foo
{
    namespace Bar
    {
    }
}
```

or as

``` C#
namespace Foo.Bar
{
}
```

Either way, I refer to that namespace as "Foo.Bar".

I'd love the same flexibility for nested classes. That is, today I can write:

``` C#
partial class Outer
{
    private class Inner
    {
    }
}
```

but I'd really like to be able to write:

``` C#
private class Outer.Inner
{
}
```

Where "partial" is implied by the concise class definition syntax.

The scenario where I would find this particularly useful is when a set of classes implement a set of interfaces, but the implementation of certain interfaces is an implementation detail of the implementation of a higher level interface (and therefore a nested class as it does not need to be publicly exposed but may need private access to the parent class). For example:

``` C#
public interface IDocumentRepository
{
    IDocumentCollection Documents { get; }
}

public interface IDocumentCollection : IEnumerable<IDocument>, INotifyCollectionChanged { }

public interface IDocument
{
   string Text { get; }
   IAuthor Author { get; }
}

public interface IAuthor
{
    string Name { get; }
}
```

``` C#
public partial class DocumentRepository : IDocumentRepository
{
    private readonly DocumentCollection documents = ...

    public IDocumentCollection Documents { get { return this.documents; } }
}

private class DocumentRepository.DocumentCollection : IDocumentCollection
{
    ...
}

private partial class DocumentRepository.Document : IDocument
{
    ...
}

private class DocumentRepository.Document.Author : IAuthor
{
    ...
}
```

This level of nested classes is a perfectly reasonable design for this type of situation, and results in the right level of encapsulation, but today is **syntactically awkward as it ends up producing overly indented code**.

**Comment by KalitaAlexey** [comment]
I'd prefer syntax like this
```
public class MyOuterClass
{
    private partial class MyInnerClass;
}

private class MyOuterClass.MyInnerClass
{
}
```

And it keeps one question is open - should the compiler allows to implement nested class in another file to refer rule "One file - one class", or should it enforces to implement nested class in same file to encapsulate private classes in one file.
I'd prefer implement public classes in another file and private classes in same file

**Comment by jnm2** [comment]
Oh man, I would use this a lot. It's always hard to decide between keeping classes private and nested and indented and cluttering up the containing class, and making them internal just for the sake of working with them in separate files.

The syntax reminds me of the syntax in #595.

**Comment by HaloFour** [comment]
What I've typically done is separate the nested classes into their own files by defining the parent class as a `partial` class:

Bar.cs:
```cs
public partial class Bar : Foo {
    // can use Baz here
}
```

Baz.cs:
```cs
public partial class Bar {
    private class Baz {
        // Baz definition here
    }
}
```

Sure, you have to repeat the parent class name, but it makes it pretty easy to separate non-trivial nested classes into their own files.

**Comment by ryantrem** [comment]
Right, partial classes were implied in my example above. The issue is not about separating the code into different files, it's about avoiding overly indented code. The example I gave above today would translate to:

```C#
partial class DocumentRepository
{
    partial class Document
    {
        private class Author
        {
            ...
        }
    }
}
```

To avoid this type of issue with namespaces, you can define them concisely:

```C#
namespace System.Threading.Tasks
{
   ...
}
```

instead of

```C#
namespace System
{
    namespace Threading
    {
        namespace Tasks
        {
            ...
        }
    }
}
```

The point is, the same indenting issues happen with (deeply) nested classes, which discourages using them, even though nested classes are actually desirable in examples like the one I gave above.

**Comment by mirhagk** [comment]
In #595 it was suggested by @paulomorgado to have this same syntax but instead refer to namespaces. So

~~~
public class System.Threading.Tasks.Task{}
~~~

would be

~~~
namespace System.Threading.Tasks
{
    public class Task{}
}
~~~

Rather than

~~~
public class System
{
    public class Threading
    {
        public class Tasks
        {
            public class Task{}
        }
    }
}
~~~

In the context of that proposal I much prefer using this syntax to remove the namespace nesting from every single file, but that would make this proposal not work. Perhaps this is a way to make them work together? But it'd be very confusing whether it was nested in classes or namespaces.

**Comment by paulomorgado** [comment]
The big difference here is that namespaces don't have inner namespaces (namespace declarations can have inner namespace declarations) and don't have accessibility modifiers.

Unless you are creating the `Outer` class just for the purpose of having an inner `Inner` class, `class Namespace.Outer.Inner` (why stop at just the type) would have to stand for:

    namespace Namespace
    {
        partial class Outer
        {
            partial class Inner
            {
                ...
            }
        }
     }
 
 But how would the access modifiers be applied? Just to the most inner type? That would require the types to be writte like this:
 
    public partial class Namespace.Outer
    {
        ...
    }
    
    private partial class Namespace.Outer.Inner
    {
        ...
    }
 
 And how would this this collision be resolved?

    namespace Namespace
    {
        partial class Outer
        {
            partial class Inner
            {
                ...
            }
        }
     }

    namespace Namespace
    {
        namespace Outer
        {
            partial class Inner
            {
                ...
            }
        }
     }

What is the real world case where you would want something that is inside another thing to be written in a way that hides it?

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

**Comment by ryantrem** [comment]
@gafter - was this migrated to csharplang, or do I have to do that manually?

**Comment by HaloFour** [comment]
You'll need to reopen the issue there if you want to continue to pursue it.
