### ISSUE TITLE
No cross platform nuget package of Roslyn is available

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#15378]
**Version Used**: Microsoft.Net.Compilers 2.0.0-rc

Only following packages are available

Microsoft.Net.Compilers.netcore - which is clear netcore specific version
Microsoft.Net.Compilers - nowhere mentioned but it's windows desktop only version due to following reasons

RC release of 2.0 started bundling netstandard version of platform dependant assemblies.

Following assemblies are not forwarding assemblies but have netcore specific implementation which causes various issue when running e.g. on Mono

System.Runtime.InteropServices.RuntimeInformation.dll
System.Text.Encoding.CodePages.dll

**Expected Behavior**:

Properly target netstandard 1.6

**Comment by jaredpar** [comment]
Can you give some more context into how you are looking to use this package?  

This particular NuGet package is deliberately platform specific at this point.  It delivers the standalone compiler toolset (csc, vbc, msbuild tasks, targets, etc ...) for the desktop runtime environment. 

We've had a couple of requests for a more general, non-platform specific toolset.  Our initial attempt was the Microsoft.Net.Compilers.netcore package.  That ended up being very tied to how dotnet CLI needs NuGet packages because it was our only scenario + customer.  If there is a scenario here we'd love to hear it because we don't have a good one to shape this type of NuGet package.

**Comment by marek-safar** [comment]
The scenario is quite simple, because this is just ordinary nuget any project can reference it and many do already. When you open/build this project using Mono runtime (e.g. Visual Studio for Mac, xbuild, xplatform msbuild, etc.) it'll fail because the nuget is restored and used as any other nuget.

An error example from simple console app referencing the nuget

```
Task "Csc"
        Using task Csc from Microsoft.Build.Tasks.Csc, Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
        Tool /Users/ankit/Projects/Console004/packages/Microsoft.Net.Compilers.2.0.0-rc/build/../tools/csc.exe execution started with arguments: /noconfig /debug:full /debug+ /optimize- /out:obj/x86/Debug/Console004.exe Program.cs Properties/AssemblyInfo.cs foo/EmptyClass.cs obj/x86/Debug/.NETFramework,Version=v4.5.AssemblyAttribute.cs /target:exe /define:DEBUG /nostdlib /platform:x86 /reference:/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/4.5-api/System.dll /reference:/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/4.5-api/System.Core.dll /reference:/Users/ankit/Projects/Console004/Lib02/bin/Debug//Lib02.dll /reference:/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/4.5-api//mscorlib.dll /warn:4
        Environment variables being passed to the tool:
        Microsoft (R) Visual C# Compiler version 2.0.0.61104
        Copyright (C) Microsoft Corporation. All rights reserved.
        
CSC: error CS2001: Source file '/Users/ankit/Projects/Console004/Console004\Program.cs' could not be found.
CSC: error CS2001: Source file '/Users/ankit/Projects/Console004/Console004\obj/x86/Debug/.NETFramework,Version=v4.5.AssemblyAttribute.cs' could not be found.
CSC: error CS2001: Source file '/Users/ankit/Projects/Console004/Console004\foo/EmptyClass.cs' could not be found.
CSC: error CS2001: Source file '/Users/ankit/Projects/Console004/Console004\Properties/AssemblyInfo.cs' could not be found.
        Tool /Users/ankit/Projects/Console004/packages/Microsoft.Net.Compilers.2.0.0-rc/build/../tools/csc.exe execution finished.
```

**Comment by jcouv** [comment]
From chat with @marek-safar, it sounds like for Mono and VS for Mac to refresh their version of the compiler package requires some work beyond updating a version number (the desktop packages are used and massaged, and MVIDs for specific binaries get baked in the product to workaround some problems).

It sounds like there is an ask to fix our existing packages, or maybe a new for a new one (I'm not very familiar with our package strategy and identified gaps). We can discuss next week.
I'll take a note in my effort to facilitate adoption (https://github.com/dotnet/roslyn/issues/18783)

**Comment by marek-safar** [comment]
The underlying problem is that roslyn tools nuget (which distributes csc) is specific to .net 4.6. I don't know if it's possible to make tools inside nuget multi-platform but probably not right now.

**Comment by jcouv** [comment]
Adding @agocke who is currently working on a [NETCore-targeted Compilers NuGet package](https://github.com/dotnet/roslyn/pull/19190) (it would be a separate package, not merged with desktop one). 
@marek-safar Would that meet the needs of your scenario?

**Comment by marek-safar** [comment]
I don't think so as that package will be again netcore specific and won't run on Mono out of box.

**Comment by jcouv** [comment]
Assigning to Jared since he's driving this discussion.

**Comment by jcouv** [comment]
I'm not clear where we left this off and a number of things probably have changed (Andy mentioned we removed our dependency on `System.Runtime.InteropServices.RuntimeInformation.dll`, and mono probably added support `System.Text.Encoding.CodePages.dll`?).

Is there still an issue, or can we close?

**Comment by marek-safar** [comment]
There is still an issue as Roslyn does not provide netstandard compatible tools version. Jared mentioned this is nuget limitation in some way but that was some time ago

**Comment by agocke** [comment]
@marek-safar, @jcouv, and I talked about this offline. Some takeaways:

1. Our package currently contains a lot of dependent assemblies that are built for .NET 4.6 on Windows Desktop CLR and are incompatible with Mono. By bundling these assemblies in the `tools` directory of `Microsoft.NET.Compilers` we're creating work for Mono users to delete these harmful assemblies.

2. This package isn't currently usable to override the compiler on Mono installations, largely because of (1).

The proposed solution is to

1. Multitarget the Roslyn compilers to also compile against .NET 4.7. That should eliminate the dependencies that break when run on Mono.

2. Create a new layout for the Microsoft.NET.Compilers package by adding a .NET 4.7 folder (perhaps called net47 under the tools/ directory?) where we ship these assemblies.

3. Change the `Microsoft.NET.Compilers.props` file to detect whether or not MSBuild is running on Mono and, if so, choose to use the .NET 4.7 binaries instead of the .NET 4.6 binaries.

cc @jaredpar for these plans.

**Comment by jaredpar** [comment]
> Multitarget the Roslyn compilers to also compile against .NET 4.7. That should eliminate the dependencies that break when run on Mono

Just the exes or the dll projects as well? Hoping it's just the exes ... 

> Create a new layout for the Microsoft.NET.Compilers package by adding a .NET 4.7 folder (perhaps called net47 under the tools/ directory?) where we ship these assemblies.

Why did we land on this vs. just creating a separate Mono package? The manner in which we build the Microsoft.Net.Compilers package today is meant to be an exact replica of how our bits work in an MSBuild layout. This helps give us confidence that the product we're building today will run when we insert it into MSBuild (testing what we are shipping). Adding new bits here change that somewhat. 

> Change the Microsoft.NET.Compilers.props file to detect whether or not MSBuild is running on Mono and, if so, choose to use the .NET 4.7 binaries instead of the .NET 4.6 binaries

This seems like another reason why we should be shipping a separate package here. At least in the short term.

**Comment by agocke** [comment]
@jaredpar I'm fine with the separate package approach as well. I was most persuaded by the argument that this makes it confusing for users who are trying to find the package and accidentally pick the non-Mono compatible one.

**Comment by marek-safar** [comment]
The argument for a single package was the easy way to ship C# compiler prototypes as a single package

**Comment by jcouv** [comment]
If we choose to go with single package, let's document the package (on our wiki, https://aka.ms/roslyn-packages).

**Comment by jaredpar** [comment]
The compiler already ships multiple packages today: desktop and coreclr. Hence there is already no single package for compiler prototypes. Adding a different package for mono is the more consistent approach here.

Again, one of the direct goals of the Microsoft.Net.Compilers package is to have a method of shipping our exact MSBuild layout as a single package. This ensures that we can safely ship patches to our customers without potential for upsetting their builds. Adding new bits here goes against that goal.

**Comment by agocke** [comment]
Having just done a quick test, it looks like we would need to add a `net47` target to *every* assembly, not just `csc`.

**Comment by jcouv** [comment]
My understanding is that the `Microsoft.Net.Compilers`  package now solves this problem. @agocke @marek-safar Is there an issue or work left for this? If not, let's close the issue.

**Comment by marek-safar** [comment]
You can close this now
