### ISSUE TITLE
Roslyn launching two copies of RoslynCodeAnalysisService32

### ISSUE THREAD

**Issue by asecchia** [dotnet/roslyn#15373]
@heejaechang 

![image](https://cloud.githubusercontent.com/assets/2646338/20448493/1f464efe-ad99-11e6-8a24-76dac805bcdb.png)

Open Roslyn.sln in VS
Note: two copies of ServiceHub.RoslynCodeAnalysisService32 are launched - one lasts for 17s and the other stays alive for the entire duration of the process. The short lived one is launched second.

**Comment by heejaechang** [comment]
dup of this.
https://github.com/dotnet/roslyn/issues/15041
