### ISSUE TITLE
Full solution analysis does not respect Code Style settings

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#15386]
**Version Used**: 25909

**Steps to Reproduce**:

1. Enable full solution analysis
2. Change the default Code Style settings, 
3. Open some files that will trigger Code Style

**Expected Behavior**: Settings (i.e. preference and severity) to apply for the whole solution

**Actual Behavior**: Settings applied for opened files only. Rest of the solution is analysed with default settings.

**Comment by Pilchie** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/9712 I believe
