### ISSUE TITLE
Tuples not working in .NET Core Console App

### ISSUE THREAD

**Issue by shaggygi** [dotnet/roslyn#15388]
**Version Used**: 
Visual Studio 2017 RC

**Steps to Reproduce**:
1. Create new .NET Core Console App
2. Add the following (or similar Method)

```cs
static (int sum, int count) Tally(int[] values)
{
    var r = (s: 0, c: 0);

    foreach (var v in values)
    {
        r.s += v; r.c++;
    }

    return r;
}
```

3. Add Nuget package System.ValueTuple

**Expected Behavior**:
Should not have any errors.

**Actual Behavior**:
Get red squiggles on code:

```cs
(int sum, int count)
```

Get the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8137	Cannot define a class or member that utilizes tuples because the compiler required type 'System.Runtime.CompilerServices.TupleElementNamesAttribute' cannot be found. Are you missing a reference?

I tried the same steps with a .NET Core Class project and WPF project and appears to work.  Did I do something wrong or is this currently a limitation on .NET Core preview tooling?

Thx

**Comment by Belorus** [comment]
Probably nuget System.ValueTuple should be referenced ?

**Comment by shaggygi** [comment]
"3. Add Nuget package System.ValueTuple"

**Comment by leoniDEV** [comment]
I had the same issue, after closing and reopening the solution, the tuple works as expected

**Comment by shaggygi** [comment]
@Belours It also appears to work after restarting VS on my side.  Thanks for noticing this.

**Comment by srivatsn** [comment]
Likely related to https://github.com/dotnet/roslyn-project-system/issues/784

**Comment by jcouv** [comment]
I tried this on RC.2 (VS "Version 15.0.26006.2 D15REL") and did not encounter the problem.
Smells like a project system issue as Sri hinted. 
Assigned to Dave, since he already has the related issue..

**Comment by shaggygi** [comment]
@jcouv @davkean  I also just tried my project with issue from stated above and appears to now work with VS15R2.  Thanks.
