### ISSUE TITLE
Optimize FormattableString.Invariant to not allocate FormattableString instance

### ISSUE THREAD

**Issue by JamesNK** [dotnet/roslyn#15395]
Invariant formatting an interpolated string allocates a FormattableString object.

```
FormattableString.Invariant($"count: {count}")
```

Please optimize this code to call `FormattableString.Format(CultureInfo.InvariantCulture)` directly without allocating an unnecessary FormattableString object.

**Comment by CyrusNajmabadi** [comment]
Wouldn't that imply knowledge from the compiler about how FormattableString.Invariant was implemented?  What if it's implemented by some other host in a different manner?

**Comment by JamesNK** [comment]
It would.

If it is a problem then maybe there could be a different method that could wrap the FormattableString that translated to that code.

**Comment by gafter** [comment]
> Please optimize this code to call `FormattableString.Format(CultureInfo.InvariantCulture)` directly without allocating an unnecessary FormattableString object.

We cannot do that, because `FormattableString.Format` is an instance method, and if we perform the optimization you request there would be no instance to call it upon.

We prefer not to intrinsify ordinary methods in the C# compiler. That is more appropriately the job of the runtime.
