### ISSUE TITLE
Internal error in the expression evaluator on simple variable expression

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#15400]
**Version Used**: VS15 preview

**Steps to Reproduce**:

```
using System;
using System.Reflection;
using System.Reflection.Emit;

class C
{
    static void Main()
    {
        AssemblyName aName = new AssemblyName("DynamicAssemblyExample");
        AssemblyBuilder ab = AppDomain.CurrentDomain.DefineDynamicAssembly(aName, AssemblyBuilderAccess.RunAndSave);
        var x = ab.Evidence;

        Console.WriteLine(x); // Set a breakpoint here and add "x" to watch window
        return;
    }
}
```

**Expected Behavior**:

No internal error

**Actual Behavior**:

Internal error in the expression evaluator.

**Comment by jcouv** [comment]
FYI @cston for triage

**Comment by jcouv** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/12466233/28082863-7cd6e00e-6628-11e7-99bd-fd040dc148b7.png)

**Comment by cston** [comment]
@marek-safar, I'm not able to repro this with a more recent build either. Please let us know if you still hit this with a more recent build. Thanks.

**Comment by marek-safar** [comment]
Seems to work for me with recent build too

**Comment by cston** [comment]
@marek-safar thanks for verifying.
