### ISSUE TITLE
proposed [Area-Language Design] Anonymous types in a generic declaration

### ISSUE THREAD

**Issue by timopomer** [dotnet/roslyn#15417]
I would like to propose a way to use anonymous types in a generic setting.

I do **not** know if our latest build lets us create collections of named tuples for example, but on multiple occurances I have needed to create helper classes to enable me to imitate the anonymous types i actually wanted to use.

If generic functions can handle anonymous types, why cant they be made non generic where the declaration is necessary (generic classes like collections for example)

This is particularly useful to the creation of conversion tables and such.

Nowadays i have to use dynamic or object or a new class that only imitates the anonymous idea i originally had planned.

If var can contain anonymous types, why couldn't they be used as a generic type?

So we have to somehow statically declare what anonymous type will be used and this is my idea:

This is a proposed look, it seems a bit dirty to me so suggestions and ideas are very welcome

Generic class declaration
```
var dict = new Dictionary<string, { name = string, age = int }>()
{
	{"person1",new { name = "tim", age = 22 }}
};
```

Non generic function
```
{ name = string, age = int } func() => new { name = "tim", age = 22 };
```

Thank you for reading/considering my request. It means alot to me to feel apart of this incredible community

**Comment by dsaf** [comment]
Tuples seem to work. Best way to try is here: http://tryroslyn.azurewebsites.net

**Comment by paulomorgado** [comment]
@timopomer, are you aware that anonymous types have little or no use outside the assembly they are defined on?

But if you really, really, really need it:

```C#
var dict =
    Enumerable
        .Repeat(new { name = "tim", age = 22 }, 1)
        .ToDictionary(i => "person1", i => i);
```

**Comment by timopomer** [comment]
@dsaf can you post an example? i couldnt get it working

also incase that works, why are we keeping anon types if you can generate tuples instead?

**Comment by dsaf** [comment]
@timopomer due to compilation and mental backwards compatibility. C# syntax gets set in stone, that's why any potential design mistakes face a backlash from community e.g. #14697 .

**Comment by timopomer** [comment]
@dsaf great, thank you. resolved. looking forward to c#7!
