### ISSUE TITLE
'Use expression body': Should we have an option like "Prefer expression body if on single line"?

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15414]
I'm finding myself not a huge fan of the "Use expression body" code fix.  The problem seems to be that I want expression-bodied properties for very simple properties, but i'm getting them for all possible properties.  This includes properties with large complex bodies (i.e. a ternary with multiple nested invocations).  Yes, this can become an autoprop... but it ends up being very overweight :)

I could imagine a few potential options here.  Like "use expression body for simple dotted expressions", or "use expression body if on single line".  The latter would then only offer the refactoring if your code was just a simple return statement with an expression on a single line.  Anything more complex would not be offered.

What do you think?

**Comment by DavidArno** [comment]
How would you determine "...with an expression on a single line". Do you mean offer it eg for:
````cs
private bool SomeFunction()
{
    return the result of some really long complex expression that just keeps going on and on and on and on and on and on and on and on and on and on;
}
````
But not offer it for a nicely formatted version that spans multiple lines?
````cs
private bool SomeFunction()
{
    return the result of some really long complex expression that just keeps going on and 
           on and on and on and on and on and on and on and on and on;
}
````

**Comment by CyrusNajmabadi** [comment]
Yes.  "On a single line" would mean "an expression that doesn't span multiple lines".

> But not offer it for a nicely formatted version that spans multiple lines?

You'd use the existing preference for that.  This is about adding a new style for those (like myself) who like expression bodied expressions to not span multiple lines.

**Comment by DavidArno** [comment]
OK, that makes sense. In that case I've nothing useful to add as I'm happy with the fix as is.

**Comment by miloush** [comment]
I have to agree that the type of block (method/property/accessor/etc.) does not determine whether I prefer block body or expression body, It's the content, and single line-ness seems to be a good metric for that.

**Comment by Pilchie** [comment]
@kuhlenh and I talked about this - we think that the right way to expose this is as another possible value for the `Preference` column for these rules, so instead of "True/False", they would be "Always/Never/If on single line".

**Comment by dpoeschl** [comment]
Also consider the case where the expression has a leading comment. Should this count as multiple lines (my preference), or should the comment be moved above the member, or...?
