### ISSUE TITLE
Question : How can I update wiki page

### ISSUE THREAD

**Issue by codingonHP** [dotnet/roslyn#15419]
There is a typo in code on this page :  https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Syntax-Transformation and some of the API are now obsolete.
Is it possible to update it in anyway ?

Thanks.

**Comment by DavidArno** [comment]
On any page on the wiki, scroll down and on the right hand side is the clone link: https://github.com/dotnet/roslyn.wiki.git. Clone it, pull to your desktop and edit it. Then push to your cloned repo and finally create a pull request.

Easy 😃

**Comment by Pilchie** [comment]
Yeah, I wish this was easier for externals :(

**Comment by hickford** [comment]
You could change the permissions so users can contribute documentation? https://help.github.com/articles/changing-access-permissions-for-wikis/
