### ISSUE TITLE
Manage specifications window is doing odd things with multiple desktops

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#15429]
Using d15rel/25920.00. There seems to be some weird interactions with the specifications window and multiple desktops. Here is the scenario:

1. Open the manage specifications window under naming styles.
![image](https://cloud.githubusercontent.com/assets/2371880/20500411/2b0fce92-afea-11e6-8269-49a2f4020b2e.png)
2. Click any edit button.
3. Switch desktops. The manage specifications window is now visible on all virtual desktops.
4. Close the edit window.
5. Switch desktop. The manage specifications window follows you to the next desktop you switch to and stays there, not following any more.

**Comment by Pilchie** [comment]
Hmm - are we currently creating a VS Dialog instance?  If so, is this a platform issue?
