### ISSUE TITLE
Allow custom "using ..... ;" sorting order + grouping

### ISSUE THREAD

**Issue by Unknown6656** [dotnet/roslyn#15422]
I may be one of few people, but I do not like how the default using-statement sorting works.
I would therefore like to propose an IDE setting, to allow custom using-statement grouping and sorting, e.g. by length, reverse alphabet, or whatever...

The problem is, however, how to define the sorting rule to the IDE....
_(ideal would be submitting a LINQ sorting query to the IDE inside the settings ^^)_

**Comment by Pilchie** [comment]
This is the only time I've ever heard of a request like this.  At present, I can't imagine the complexity is worth it for the number of people who would use it.

**Comment by Unknown6656** [comment]
OK  (.__.)
