### ISSUE TITLE
Project load error in DPL mode

### ISSUE THREAD

**Issue by jainaashish** [dotnet/roslyn#15427]
I'm getting a project load error when solution is opened under DPL and then load a project. It throw below error:

`A project with that name is already opened in the solution.`

Steps:
- First you need to get the test NuGet vsix with my restore changes. Do below steps:
  o Uninstall existing NuGet vsix. Execute “Vsixinstaller /u:NuGet.72c5d240-f742-48d4-a0f1-7016671e405b” from developer command prompt as Admin
  o Install NuGet vsix from \\scratch2\scratch\asja\DPLRestore simply by double clicking it.
- Open VS in DPL mode. And open solution from \\scratch2\scratch\asja\PCWithUAP By default all the projects of this solution will be deferred.
- Build solution
- Load project1 and you will see the error.

**Comment by Pilchie** [comment]
Took a look this morning, and this is happening in the old project system code because NuGet is loading the project through DTE.  NuGet is going to switch to using the right VS service to do this.
