### ISSUE TITLE
[scriptcs] Emitting and loading PDB symbols for script code

### ISSUE THREAD

**Issue by filipw** [dotnet/roslyn#1543]
Is there currently a supported/user-friendly way of emitting PDB for script code in order to allow debugger to be attached?

I managed to get it to work using a hardly elegant method of emitting the compilation with PDB to `MemoryStream`, loading it all into `AppDomain` and then reflecting to find `Submission#0` and `<Factory>` method - [see here](https://github.com/scriptcs/scriptcs-engines/blob/master/src/ScriptCs.CSharp/CSharpScriptCompilerEngine.cs#L47). 

It would be nice if we could do it in some better way.

**Comment by ManishJayaswal** [comment]
unfortunately we currently do not have supported way to do this. We will likely need this in order to support scripts as first class concept in VS.

**Comment by filipw** [comment]
Can be closed following the merge of https://github.com/dotnet/roslyn/issues/16489
