### ISSUE TITLE
Review AnalyzerFileReference

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#1544]
I think we need to review the public surface area for this type.  The contract for it is unclear ...

- When will the load func be called?
- How many times will it be called?  Does this change in the face of error?  
- Why is the load logic in AnalyzerFileReference vs. the caller for other types?

**Comment by jaredpar** [comment]
CC @tmat

**Comment by tmeschter** [comment]
Fixed by be5b71f24ef710d0c6321dc3e108f19aee1847f7, where `AnalyzerFileReference` was updated to take an `IAnalyzerAssemblyLoader` instead of a `Func<string, Assembly>`.

**Comment by tmeschter** [comment]
Moving to @jaredpar  for verification.
