### ISSUE TITLE
DataFlowAnalysis.Captured should be separated into CapturedInside and CapturedOutside

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#1545]
The type `DataFlowAnalysis`, which results from `SemanticModel.AnalyzeDataFlow`, currently ignores the region and computes the capture set for the entire enclosing method. It should be region-sensitive like the other methods in `DataFlowAnalysis`, and be separated into `CapturedInside` and `CapturedOutside`.

/cc @heejaechang @AnthonyDGreen @tmat @VSadov @AlekseyTs

**Comment by gafter** [comment]
Please comment now if you object to this API change. I plan on doing it in the next day.

For compatibility I'll preserve the existing API, but mark it [Obsolete]. Please let me know if you think I should remove it.

**Comment by heejaechang** [comment]
@gafter no objection, but will require some change in ExtractMethod. @balajikris

**Comment by gafter** [comment]
@heejaechang I don't think it should *require* changes in ExtractMethod, as all of the existing APIs will continue to exist and behave as they do today. But I think you will want to make changes to take advantage of the new APIs.

**Comment by jcouv** [comment]
@heejaechang FYI We're about to merge a community PR to fix this, in case you want to take a look too.
https://github.com/dotnet/roslyn/pull/23428

**Comment by heejaechang** [comment]
@jcouv looks fine.! thank you!

**Comment by jcouv** [comment]
@alrz fixed this in 15.7. Closing
