### ISSUE TITLE
Allow fixes to provide menu icons

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/roslyn#15456]
It would be very helpful to users if fixes were allowed to display icons on the fixes menu, like other tools do:

![image001](https://cloud.githubusercontent.com/assets/470455/20513471/f261f2f2-b07d-11e6-8d4a-7674b442d0d6.png)

**Comment by CyrusNajmabadi** [comment]
Implementation concept:

1. Add an ```ImmutableArray<string> Tags``` to CodeAction.
2. Add a mef extensibility point to translate from Tags to VS' ImageMoniker.

Optional/Desirable:
3. Move our existing system to using the above.  Remove usage of Glyph enum entirely.
