### ISSUE TITLE
Introduce Constant refactoring fails

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#15453]
**Version Used**: d15prerel 25918.2

**Steps to Reproduce**:

Place the caret on the "16" in the code snippet below and press Ctrl+. and start the "Introduce constant" refactoring. Try to give it a name.

```csharp
    internal static class PdbExtensions
    {
        internal static IEnumerable<string> FindMissingOrChangedSourceFiles(this PdbFile pdbFile)
        {
            Argument.IsNotNull(() => pdbFile);

            foreach (var checksumInfo in pdbFile.GetFilesAndChecksums())
            {
                string file = checksumInfo.Key;
                byte[] expectedChecksum = checksumInfo.Value;
                HashAlgorithm hasher = expectedChecksum.Length == 16 ? (HashAlgorithm)MD5.Create() : SHA1.Create();
                byte[] actualChecksum = File.Exists(file) ? HashFile(hasher, file) : null;

                if (!AreEqualBuffers(expectedChecksum, actualChecksum))
                {
                    yield return file;
                }
            }
        }
    }
```

The refactoring fails with an error that exposes this callstack:

```
System.ArgumentException : textContainer is not a SourceTextContainer that was created from an ITextBuffer.
Parameter name: textContainer
   at Microsoft.CodeAnalysis.Text.Extensions.GetTextBuffer(SourceTextContainer textContainer)
   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.TryNavigateToSpan(Workspace workspace,DocumentId documentId,TextSpan textSpan,OptionSet options)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.TryStartRenameSession(Workspace workspace,Solution oldSolution,Solution newSolution,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorkerAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass19_0.<InvokeCoreAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by CyrusNajmabadi** [comment]
@heejaechang @jasonmalinowski @mattwar 

Is this another case where we broke being able to map from an open document's SourceText to an ITextBuffer?

**Comment by CyrusNajmabadi** [comment]
The code inside VisualStudioDocumentNavigationService is:

```c#
            var text = document.GetTextAsync(CancellationToken.None).WaitAndGetResult(CancellationToken.None);
            var textBuffer = text.Container.GetTextBuffer();
```

@heejaechang you mentioned the this was broken by Kayle to deal with an uncommon typing scenario (i.e. when text versions are reiterated).  Can we reinstate the original invariant?  This definitely concerns me as it seems like we've broken an invariant that has affected at least two pieces of code.  I'm worried there may be other locations that we don't know about that will affect customres.

**Comment by heejaechang** [comment]
I thought that issue is already fixed (I think we removed the optimization Kayle has put in). the above exception can happen if ITextSnapshot we created sourcetext from is already release. if one checks cancellation token, is cancellation token raised?

**Comment by heejaechang** [comment]
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Text/Extensions.SnapshotSourceText.cs,88

actually, looks like it is not fixed...

**Comment by Pilchie** [comment]
In this case we're going through the Container/TextBuffer, not the snapshot?  Shouldn't that work regardless as long as the file is open?

**Comment by CyrusNajmabadi** [comment]
Yes.  Something is *super strange* here.  An open document should always be able to from its SourceText to the ITextBuffer.  If it can't, then we've broken something badly.

**Comment by jasonmalinowski** [comment]
I don't think we've ever had enough clue of what this bug is to have fixed it. We've gotten reports like this but they've been sporadic enough to make it hard to measure if we've got it or not...

**Comment by heejaechang** [comment]
what is text container type by the way? are we sure the source text we have is for open file?

**Comment by CyrusNajmabadi** [comment]
> what is text container type by the way? are we sure the source text we have is for open file?

Yes.  We're navigating to the document.  The very first thing we do is ask the workspace to ensure that document is opened.

**Comment by Pilchie** [comment]
@AArnott are you able to repro this consistently?

**Comment by AArnott** [comment]
I guess not. This morning when I tried it, it didn't repro. But while it was reproing it happened several times in a row.

**Comment by Pilchie** [comment]
Closing as Not repro for now.  Let us know if you hit it again.
