### ISSUE TITLE
Multiple VSI tests failing since 11/17

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#15463]
11/22: https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_open_prtest/25/#showFailuresLink
11/18: https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_open_prtest/19/#showFailuresLink
11/18: https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_open_prtest/18/#showFailuresLink
11/17: https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_open_prtest/15/#showFailuresLink

The same several scenarios are failing in BasicRazor, BasicSignatureHelp, BasicVenus, BasicWebApp, BasicWinForms, and CSharpAutomaticBraceCompletion. Since they all seem to have started failing at once, I suspect they have the same root cause.

**Comment by Pilchie** [comment]
From the first link, the first failure was:

>17:32:24  Dumping log file d:\j\workspace\windows_vsi_p---9a06aa34\Open\Binaries\Release\Exes\EditorTestApp\VSIntegrationTestLogs\BasicRazor.txt
17:32:24 Test: BasicRazor started: 11/22/2016 4:11:44 PM
17:32:24 	Executing action [11/22/2016 4:11:44 PM] StartTarget
17:32:24 Begin Waiting for Apex Communication
17:32:24 	Executing action [11/22/2016 4:11:45 PM] SetToolsOption
17:32:24 Previous option value: TextEditor > HTMLX > InsertTabs = False
17:32:24 Setting option: TextEditor > HTMLX > InsertTabs = false
17:32:24 	Executing action [11/22/2016 4:11:45 PM] AddMvcProject
17:32:24 	Executing action [11/22/2016 4:11:53 PM] AddItem
17:32:24  Scenario: Verify Completion list in Razor syntax
17:32:24 	Executing action [11/22/2016 4:11:54 PM] OpenFile
17:32:24 DEBUG: executed DTE command File.OpenFile.
17:32:24 DEBUG: start polling for code window
17:32:24 DEBUG: polling complete
17:32:24 	Executing action [11/22/2016 4:11:54 PM] PlaceCursor
17:32:24 	Executing action [11/22/2016 4:11:54 PM] InsertText
17:32:24 	Executing action [11/22/2016 4:11:54 PM] WebUtilities
17:32:24 	Executing action [11/22/2016 4:11:55 PM] WaitForWorkspace
17:32:24 	Executing action [11/22/2016 4:11:55 PM] PlaceCursor
17:32:24 	Executing action [11/22/2016 4:11:55 PM] SendKeys
17:32:24 --------------------------------
17:32:24 System.Exception: Tao action timed out at 11/22/2016 4:51:55 PM. Timeout limit was: 00:40:00
17:32:24 ================================
17:32:24 
17:32:24 
17:32:24 Saved screenshot: d:\j\workspace\windows_vsi_p---9a06aa34\Open\Binaries\Release\Exes\EditorTestApp\Screenshots\2016-11-22_16-51-55_54 - Exception System.Exception.png
17:32:24 Killing VS procid: 1772

Did something change about the canned project it opens such that it can't find the text it is looking for?

From the next screenshot, it looks like our completion code is using an API that doesn't exist in the base VS :(
<img width="498" alt="screen shot 2016-11-23 at 2 12 56 pm" src="https://cloud.githubusercontent.com/assets/312835/20580402/fad60338-b186-11e6-9693-9a41f09ccac0.png">


@tmeschter can you take a look as you're getting things going on RC.

Should we just disable these on the existing machines?

**Comment by tmeschter** [comment]
@DustinCampbell I'm closing this issue. BasicVenus and BasicWinForms still fail, but it seems to be for different reasons at this point (tracked by  https://github.com/dotnet/roslyn/issues/15744, https://github.com/dotnet/roslyn/issues/15747, https://github.com/dotnet/roslyn/issues/15844, and https://github.com/dotnet/roslyn/issues/15845).

The other tests are passing.
