### ISSUE TITLE
New Find All References opens WinForms designer

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#15478]
**Version Used**: 2017 RC

**Steps to Reproduce**:

1. Open a WinForms designer for a class that uses a member.
2. Close its codebehind file.
3. Click Find All References on that member.

**Expected Behavior**:
The codebehind should open.

**Actual Behavior**:
The designer opens.

**Comment by Pilchie** [comment]
Do we handle navigation, or does it come from the editor once we report results?  Someone probably needs to specify the "editor" they want when the file is opened.

**Comment by CyrusNajmabadi** [comment]
This is working as expected.
