### ISSUE TITLE
MSBuildWorkspace doesn't correctly open some solutions, projects have 0 references

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#15479]
1. Create a new C# console app
2. Add NuGet references to Microsoft.CodeAnalysis.Workspaces.CSharp 2.0.0-rc.
3. Use MSBuildWorkspace to open  https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/System.Collections.Immutable.sln 
4. Iterate over all projects of the solution, for each project GetCompilation, and then GetDiagnostics().

Verify there are no diagnostics.

Currently I'm seeing multiple issues:
1. Need to manually add references to ManagedEsent and Elfie
2. Need to make sure to reference System.Reflection.Metadata version https://www.nuget.org/packages/System.Reflection.Metadata/1.4.1-beta-24430-01 because the latest one doesn't work
3. The compilations I see have 0 references, I'm not sure why
4. I saw a spurious ArgumentNullException deep in DecisionTreeBuilder.CheckSubsumed(), but I'm suspecting it is due to the compiler being not tolerant to System.Object missing

Until all of these are fixed, http://source.roslyn.io will have all sorts of bugs in it that I can't do anything about.

**Comment by KirillOsenkov** [comment]
The stack for the ArgumentNullException in case anyone's interested:

 	System.Collections.Generic.Dictionary<object, Microsoft.CodeAnalysis.CSharp.DecisionTree>.FindEntry Line 299	C#
 	System.Collections.Generic.Dictionary<object, Microsoft.CodeAnalysis.CSharp.DecisionTree>.TryGetValue Line 500	C#
>	Microsoft.CodeAnalysis.CSharp.DecisionTreeComputer.CheckSubsumed Line 311	C#
 	Microsoft.CodeAnalysis.CSharp.DecisionTreeComputer.CheckSubsumed Line 349	C#
 	Microsoft.CodeAnalysis.CSharp.DecisionTreeComputer.ComputeDecisionTree Line 190	C#
 	Microsoft.CodeAnalysis.CSharp.BoundPatternSwitchStatement.ComputeDecisionTree Line 128	C#
 	Microsoft.CodeAnalysis.CSharp.BoundPatternSwitchStatement.EnsureDecisionTree Line 118	C#
 	Microsoft.CodeAnalysis.CSharp.BoundPatternSwitchStatement.DecisionTreeDiagnostics.get Line 29	C#
 	Microsoft.CodeAnalysis.CSharp.ControlFlowPass.VisitPatternSwitchStatement Line 335	C#
 	Microsoft.CodeAnalysis.CSharp.BoundPatternSwitchStatement.Accept Line 3005	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.VisitWithStackGuard Line 298	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.VisitAlways Line 283	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.Visit Line 265	C#
 	Microsoft.CodeAnalysis.CSharp.ControlFlowPass.Visit Line 107	C#
 	Microsoft.CodeAnalysis.CSharp.ControlFlowPass.VisitStatement Line 232	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.VisitBlock Line 1143	C#
 	Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept Line 2391	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.VisitWithStackGuard Line 298	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.VisitAlways Line 283	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.Visit Line 265	C#
 	Microsoft.CodeAnalysis.CSharp.ControlFlowPass.Visit Line 107	C#
 	Microsoft.CodeAnalysis.CSharp.ControlFlowPass.VisitStatement Line 223	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.VisitForEachStatement Line 2129	C#
 	Microsoft.CodeAnalysis.CSharp.BoundForEachStatement.Accept Line 3323	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.VisitWithStackGuard Line 298	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.VisitAlways Line 283	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.Visit Line 265	C#
 	Microsoft.CodeAnalysis.CSharp.ControlFlowPass.Visit Line 107	C#
 	Microsoft.CodeAnalysis.CSharp.ControlFlowPass.VisitStatement Line 232	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.VisitBlock Line 1143	C#
 	Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept Line 2391	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.VisitWithStackGuard Line 298	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.VisitAlways Line 283	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.Visit Line 265	C#
 	Microsoft.CodeAnalysis.CSharp.ControlFlowPass.Visit Line 107	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.Scan Line 362	C#
 	Microsoft.CodeAnalysis.CSharp.ControlFlowPass.Scan Line 116	C#
 	Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass<Microsoft.CodeAnalysis.CSharp.ControlFlowPass.LocalState>.Analyze Line 382	C#
 	Microsoft.CodeAnalysis.CSharp.ControlFlowPass.Analyze Line 171	C#
 	Microsoft.CodeAnalysis.CSharp.ControlFlowPass.Analyze Line 144	C#
 	Microsoft.CodeAnalysis.CSharp.FlowAnalysisPass.Analyze Line 129	C#
 	Microsoft.CodeAnalysis.CSharp.FlowAnalysisPass.Rewrite Line 41	C#
 	Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod Line 941	C#
 	Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType Line 436	C#
 	Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedTypeAsTask.AnonymousMethod__0 Line 324	C#

**Comment by tmat** [comment]
Re 2: https://github.com/dotnet/roslyn/pull/14879

**Comment by Pilchie** [comment]
MSBuildWorkspace currently has big problems in the 2.0 branch, because it doesn't know how to find MSBuild.  I'm surprised you're getting as far as you are. Are you binding redirecting it back to the 14.0 version? 

Tagging @tmeschter and @mattwar

**Comment by KirillOsenkov** [comment]
Good to know, I'll just hold off until it's all working again.

Maybe 2.0.0-rc was snapped before the breaking changes you're talking about? And yes, I might be redirecting it to 14.0. I don't have Willow on my box if that matters.

**Comment by Pilchie** [comment]
If you still have the 14.0 build tools installed and you redirect our references *down* from 15.1 to 14.0 you might be avoiding all of the "fun" of finding msbuild on a willow based machine.

For step 3 - are there any WorkspaceFailed dignostics?  What about compilation diagnostics?

**Comment by KirillOsenkov** [comment]
I haven't noticed any WorkspaceFailed invocations. There were 18 thousand compilation diagnostics.

**Comment by mattwar** [comment]
I was able to repro the 18 thousand diagnostics.  However, msbuild is also failing to build the project on the command line too.  The workspace reports that msbuild API reported a failure when processing the project file.  So I end up with a project with no references, which leads to the 18 thousand diagnostic messages from roslyn.

**Comment by mattwar** [comment]
The command line failure was occurring when building the solution, failing on the package project.  If I just built the dll project then it worked fine.  Msbuild was failing via the workspace because I didn't have the redirects in my app config.  Once I added the msbuild redirects, then the project opened without error and I was able to get compilation and diagnostics..  It ends up with 10 diagnostics, that are all "hidden" unnecessary using directive diagnostics.

**Comment by mattwar** [comment]
I tried both using dev14 and dev15 (on same machine with dev14 installed).  I was able to succeed at opening the project & solution for System.Collections.Immutable.  I was able to get all the metadata references and no diagnostics (except for the hidden ones.)

**Comment by mattwar** [comment]
Note: I did also have to do a nuget restore on the project (it has project.json for references)

**Comment by devdutt91** [comment]
@mattwar  Could you please tell me what are the redirects you added?
I added the MSBuild redirects, but still sln load has lot of diagnostic errors.
