### ISSUE TITLE
Refactoring - Use 'throw' expression should be smarter

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#15471]
Currently, when clicking on the quick action Use 'throw' expression in Visual Studio 15 RC, the following code:
```
class Thing
{
	public Thing(string name)
	{
		if (name == null) throw new ArgumentNullException(nameof(name));
		if (name.Length == 0) throw new ArgumentEmptyException(nameof(name));

		Name = name;
	}

	public string Name { get; }
}
```
Is replaced with the following:
```
class Thing
{
	public Thing(string name)
	{
		if (name.Length == 0) throw new ArgumentEmptyException(nameof(name));

		Name = name ?? throw new ArgumentNullException(nameof(name));
	}

	public string Name { get; }
}
```
And so now, when null is passed it will throw NRE instead of the expected exception.

This will probably get caught by tests (given that they exist) but still refactoring shouldn't introduce _bugs_ or change the behaviour of the code and so I think that this case should be taken into account.

**Comment by Pilchie** [comment]
I thought you took a look at this already - did it just not make the fork for RC?

**Comment by CyrusNajmabadi** [comment]
Thanks @eyalsk This was fixed in : https://github.com/dotnet/roslyn/pull/15023

**Comment by CyrusNajmabadi** [comment]
Confirmed this no longer reproes.  Thanks @eyalsk

**Comment by eyalsk** [comment]
@CyrusNajmabadi Thanks!
