### ISSUE TITLE
The naming rule violation is inadequate for non-Latin languages

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#15486]
**Version Used**: 

Visual Studio 2017 RC

**Steps to Reproduce**:

1. Use Japanese characters for identifiers

**Expected Behavior**:

There is no message.

**Actual Behavior**:

The code analyzer says "Naming rule violation: These words must begin with upper case characters".

![image](https://cloud.githubusercontent.com/assets/3760955/20550074/54470168-b175-11e6-9e91-c85d06d6ccce.png)

However, Japanese characters don't have such a classification. There is no upper case in Japanese characters. This message may be inadequate for many non-Latin languages.

You should not simply use `char.IsLower`/`IsUpper` methods for this purpose.
https://github.com/dotnet/roslyn/blob/7a105a46a735d8c3b21a9c1990cecbe6ac4dde8c/src/Features/Core/Portable/Diagnostics/Analyzers/NamingStyles/Serialization/NamingStyle.cs#L136

**Comment by VR-Architect** [comment]
I have same issue with 2017 RC1. To reproduce, create a new AspNet CORE website. Upgrade all modules in NuGet (not the the pre's) and you get these two notifications. The project builds, runs, but shuts down immediately with no error message. Runing on Windows 10 with all updates.

Severity	Code	Description	Project	File	Line	Suppression State
Message	IDE1006	Naming rule violation: These words must begin with upper case characters: _Page_Views_Home_About_cshtml	fcs_GenTao	d:\Users\Brian\Documents\Visual Studio 2017\Projects\fcs_GenTao\src\fcs_GenTao\Views\Home\About.cshtml	1	Active

Severity	Code	Description	Project	File	Line	Suppression State
Message	IDE1006	Naming rule violation: These words must begin with upper case characters: __RazorDesignTimeHelpers__	fcs_GenTao	d:\Users\Brian\Documents\Visual Studio 2017\Projects\fcs_GenTao\src\fcs_GenTao\Views\Home\About.cshtml	1	Active

**Comment by ufcpp** [comment]
Related to: https://github.com/dotnet/roslyn/issues/15326

**Comment by Pilchie** [comment]
We'll track this with https://github.com/dotnet/roslyn/issues/15326.
