### ISSUE TITLE
Multiple Constructor dependencies

### ISSUE THREAD

**Issue by fredrikhr** [dotnet/roslyn#15484]
# Problem
This is a proposal for making it easier to derive base classes with multiple constructors.

The problem occurs when the derived class wants to extend or replace the argument list of multiple base constructors while still doing the exact same initialization internally. Consider the following code

```csharp
namespace Ctor
{
    class NumberSuffix
    {
        private readonly string text;
        public NumberSuffix(byte b) { text = b.ToString(); }
        public NumberSuffix(sbyte sb) { text = sb.ToString(); }
        public NumberSuffix(short s) { text = s.ToString(); }
        public NumberSuffix(ushort us) { text = us.ToString(); }
        // And so on...
    }
    class PrefixText : NumberSuffix
    {
        private readonly string preText;
        public PrefixText(string prefixText, byte b) : base(b) { preText = prefixText; }
        public PrefixText(string prefixText, sbyte sb) : base(sb) { preText = prefixText; }
        public PrefixText(string prefixText, ushort us) : base(us) { preText = prefixText; }
        public PrefixText(string prefixText, short s) : base(s) { preText = prefixText; }
        // And so on...
    }
}
```

As we can see, the derived class `PrefixText` performs the same initialization in all its constructors, but calls a **different** base constructor each time.

This is a pretty silly and very simplified example which in this case could be solved using generics. However, consider the case where a class has constructors with argument lists of different lengths (and different types at one or more common positions).

# Proposal
Code duplication for the example implementation of the derived class `PrefixText` could be avoided using the following syntax:
```csharp
class PrefixText : NumberText
{
    private readonly string preText;
    private PrefixText(string preText) { this.preText = preText; }
    public PrefixText(string preText, byte b) : base(b), this(preText) { }
    public PrefixText(string preText, byte sb) : base(sb), this(preText) { }
    public PrefixText(string preText, byte s) : base(s), this(preText) { }
    public PrefixText(string preText, byte us) : base(us), this(preText) { }
}
```

This suggests a comma-separated constructor call list. This would have to have the following restrictions:
- Multiple constructors are called in the order they are specified.
- If a base constructor is specified, the first constructor must be the base constructor. This must also be the only base-constructor, as there would not be an easy way to check for circular dependencies in the base constructor implementation which might be located in a different assembly.

# Gain
In the shown example the gain of such a language feature is minimal. The feature above could for example easily be implemented using Generics. However, this does prevent the derivation from duplicating possibly complex initialization code. Complex initializations could be put into a common method, but that would still require the developer to write identical bodies for a potentially large number of constructors (which would introduce a potential bug-source). A common initialization method would also not be able to set readonly field and properties (as shown in the example above).

# Implementation
In theory the compiler could be made to check the constructor call graph to avoid circular dependencies or calling one constructor multiple times. This might be difficult for the base class constructors, as they might be implemented in different assemblies where the call graphs might not easily be available.

As a simplification one could start with only accepting two constructors where the second (this) constructor may not have an additional constructor call dependency.

**Comment by jnm2** [comment]
I can say I've wanted this for the last six years.

**Comment by HaloFour** [comment]
I can see a couple of issues here that might impede implementation of something like this:

1. The "shared" private constructor couldn't have the implicit call to `base()`, which would be a deviation from normal behavior for that syntax.  This would result in the assembly being unverifiable.
1. The "shared" private constructor couldn't be invoked directly from within the class due to it's lack of constructor chaining, which would be another deviation from normal behavior for that syntax.

Due to these reasons I'd think that it would be better to look into syntax for "initializer methods", a way to describe a method that is used for common initialization that can be called from only within a constructor of that class.  The compiler could then do some chicanery to either inline the contents of that method into the calling constructors or could emit a private method with `ref` arguments for the `readonly` fields that might be initialized.

🍝 

```cs
class PrefixText : NumberText
{
    private readonly string preText;

    // called as a method
    public PrefixText(string preText, byte b) : base(b) {
        // some special initialization here
        init(preText);
    }

    // called using constructor chaining syntax
    public PrefixText(string preText, byte sb) : base(sb), init(preText) {
        // some other initialization here
    }

    init(string preText) {
        this.preText = preText;
    }
}
```

This would be equivalent to the following:

```cs
class PrefixText : NumberText
{
    private readonly string preText;

    public PrefixText(string preText, byte b) : base(b) {
        // some special initialization here
        this.init(preText, ref this.preText);
    }

    public PrefixText(string preText, byte sb) : base(sb) {
        this.init(preText, ref this.preText);
        // some other initialization here
    }

    // use some inutterable name here
    private void init(string preText, ref $field_preText) {
        $field_preText = preText;
    }
}
```

Relevant:  #3200

**Comment by eyalsk** [comment]
I understand that the example is very simplistic and I also understand the idea but it's extremely bad example beyond the fact that you can solve this with generics as you mentioned yourself but I'm confused by the inheritance relationship.

Why subclasses need to have their own state? if you inherit from fruit would you expect an apple to have its own state? if the answer is yes then I'd argue that it's not an apple, not to mention a fruit and it shouldn't be inherited from fruit.

**Comment by jnm2** [comment]
> Why subclasses need to have their own state?

Where should I start? I have hundreds of classes like this, mostly abstract, with state in both the abstract and the subclass. Every one I've just looked at seems perfectly encapsulated to me, and in every case composition is not an option.

**Comment by jnm2** [comment]
I'm not understanding the generics argument. Take Exception, for example, where you have four base ctors and you need to set a field or two in the subclass.

**Comment by eyalsk** [comment]
@jnm2 I'll answer you soon! 😉

**Comment by jnm2** [comment]
@eyalsk No worries, I've been making an effort not to do the same =)

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
