### ISSUE TITLE
"Searching..." text in rename dashboard is not localized.

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#1548]
See http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/InlineRename/Dashboard/DashboardViewModel.cs,37

**Comment by dpoeschl** [comment]
Noticed this with @rchande recently.

**Comment by MattGertz** [comment]
Approved for next preview.

**Comment by rchande** [comment]
Ported to Preview branch.

**Comment by rchande** [comment]
Please verify, @dpoeschl.
