### ISSUE TITLE
"Attempted to access an unloaded AppDomain" during Roslyn.Services.Editor2.UnitTests.dll

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#15497]
At the end of the xunit log:

  Finished:    Roslyn.Services.Editor2.UnitTests
System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.

Unfortunately no additional output or crash dump was produced.

**Comment by Pilchie** [comment]
This doesn't seem actionable without more info.  Let's wait a bit to see if it starts to happen more.

**Comment by jasonmalinowski** [comment]
@Pilchie This is the second time it's happened in recent (last week or two) memory.

**Comment by Pilchie** [comment]
So - what do you propose doing about it?

**Comment by jasonmalinowski** [comment]
Figure out why we didn't get a crash dump or something?

**Comment by jasonmalinowski** [comment]
We saw this in https://devdiv.visualstudio.com/DevDiv/_build/explorer?_a=summary&tab=ms.vss-test-web.test-result-details&buildId=471116.

**Comment by Pilchie** [comment]
Can you think of what additional logging we could add to track this down?

**Comment by jasonmalinowski** [comment]
My main thought is xunit put that error message in the log....they must have caught the exception somewhere. It might have a stack trace that can be printed too.

**Comment by Pilchie** [comment]
Hit this again in https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/5245/artifact/Binaries/Release/UnitTests/VisualStudioIntegrationTests/xUnitResults/Roslyn.VisualStudio.IntegrationTests.dll.out.log

**Comment by CyrusNajmabadi** [comment]
Hit again here: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/5960/artifact/Binaries/Debug/UnitTests/VisualStudioIntegrationTests/xUnitResults/Roslyn.VisualStudio.IntegrationTests.dll.out.log

**Comment by jasonmalinowski** [comment]
Moving to 15.3, since we're now seeing this very, very reliabily.

**Comment by mavasani** [comment]
Another failure: https://ci.dot.net/job/dotnet_roslyn/job/features_ioperation/job/windows_release_vs-integration_prtest/263/

**Comment by rchande** [comment]
Another failure: https://ci.dot.net/job/dotnet_roslyn/job/dev15.4.x/job/windows_debug_vs-integration_prtest/24/artifact/Binaries/Debug/UnitTests/VisualStudioIntegrationTests/xUnitResults/

**Comment by tmat** [comment]
Another one: https://ci.dot.net/job/dotnet_roslyn/job/features_compiler/job/windows_release_vs-integration_prtest/2/artifact/Binaries/Release/UnitTests/VisualStudioIntegrationTests/xUnitResults/Roslyn.VisualStudio.IntegrationTests.dll.out.log

**Comment by 333fred** [comment]
Also happened in the integration tests, https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/8738/artifact/Binaries/Debug/UnitTests/VisualStudioIntegrationTests/xUnitResults/Roslyn.VisualStudio.IntegrationTests.dll.out.log.

**Comment by 333fred** [comment]
Again: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.6.x-vs-deps/job/windows_release_unit64/41/artifact/Binaries/
