### ISSUE TITLE
Proposal idea: Fluent methods

### ISSUE THREAD

**Issue by jvlppm** [dotnet/roslyn#155]
# Scenario

Today, to create a fluent API method, you have to:
* set the return type to the current class
* return this

But when you add inheritance to the mixture, it get not so fluent anymore.

# What you do today:
```
class FluentBase
{
    string _name;
    public FluentBase WithName(string name) { _name = name; return this; }
}

class FluentSomething : FluentBase
{
}

FluentSomething a = ...;
FluentSomething b = a.WithName("Test"); // Build error
FluentSomething b = (FluentSomething)a.WithName("Test"); // Ok
```
There is nothing that ensures that your method will return the current instance (looking at the method signature), and the returned type is always the base class, not the instance type.

# Proposal idea
To have something like
```
class FluentBase
{
    string _name;
    public this WithName(string name) { _name = name; }
}
```
The "this" return type would mean that the method returns the current instance type.
With that:
```
FluentSomething a = ...;
FluentSomething b = a.WithName("Test"); // Success
```
would compile, and no casts would be necessary.

Overriding the method would still work, and is would always return the current instance.

# Advantages
* Simpler to write fluent methods (No return this necessary).
* Clearer API (no guessing about whether the method return a new instance, or itself).
* Better tooling (Intelissense would know more specifically the method return type).

This is the raw idea, not a formal proposition, in a new thread, to keep things organized.

**Comment by SolalPirelli** [comment]
Your first concern can be fixed using the [curiously recurring template pattern](http://en.wikipedia.org/wiki/Curiously_recurring_template_pattern), e.g. `IFluent<T> where T : IFluent<T>`, but an equivalent to Scala's `this.type` would indeed be nice since C# has no generic wildcards, which means (to continue the example) a method can't take "any IFluent".

**Comment by lyubomyr-shaydariv** [comment]
I think that allowing `void` methods to be chained would be another, but confusing or ambiguous, solution. First, `void`-returning methods cannot be chained today, returning a non-`void` can be considered a call of an instance of the returned type. But what if you do several invocations of `void`-methods over the same instance in a row? Second, there are legacy libraries that cannot declare the suggested fluent interface methods. Suppose something like `obj.Void1(); obj.Void2(); obj.Void3()`. I think that invoking methods is more of a style of a programming language, and, probably, it might look something like `obj.Void1().Void2().Void3()`.

**Comment by HaloFour** [comment]
It requires more boilerplate but it could be something solved nicely with covariant overrides.  This is something that the Java language supports as well as the CLR itself.

```cs
public class FluentBase {
    private string _name;
    public virtual FluentBase WithName(string value) {
        this._name = value;
        return this;
    }
}

public class FluentSomething : FluentBase {
    // override WithName with a covariant override
    public override FluentSomething WithName(string value) {
        return (FluentSomething)base.WithName(value);
    }
}

FluentSomething f1 = new FluentSomething();
FluentSomething f2 = f1.WithName(name);
```

That doesn't solve the problem if FluentBase might return a new instance of some other type.  Usually when I'm working with fluent API it is through a series of interfaces and the underlying implementations are private and this also doesn't help there.  It would be nice to have something that simplifies all of that but since it usually involves members spanning multiple interfaces that could be tricky.

**Comment by ashmind** [comment]
Btw there is a concept of `This` type variable in [JavaGI](http://www.stefanwehr.de/publications/Wehr_JavaGI_generalized_interfaces_for_Java.pdf), which is similar to what you propose.

**Comment by sharwell** [comment]
You can also combine a generic extension method with an internal implementation method. For an example, see the changes to **StorageMetadata.cs** and **StorageMetadataExtensions.cs** in the following commit.

https://github.com/sharwell/openstack.net/commit/a09fc524ac19cf946c8cb16af030b730f439cf1d

**Comment by jvlppm** [comment]
This proposal targets mutable objects.
With immutable objects in mind it makes sense to always return another instance (and return itself only when the object is the same).
With my proposal it is not possible to return a cloned object (intentionally, making it clear that the return is always the same object, after modification).

So Immutable classes are not covered by this proposal, since you cannot ensure the other object's type.

This proposal would help immutable object builders, like StringBuilder.

**Comment by sharwell** [comment]
@jvlppm This is what I meant:

```csharp
class FluentBase
{
    public string Name { get; set; }
}

static class FluentBaseExtensions
{
    public static T WithName<T>(this T fluent, string name)
        where T : FluentBase
    {
        fluent.Name = name;
        return fluent;
    }
}
```

**Comment by Richiban** [comment]
Wouldn't it be better if C# supported the `..` method chaining syntax? That way you could achieve fluent-like functionality with any object at the call site. E.g.

```
public class FluentThing
{
    public void WithA(A a)
    {
    	this._a = a;
	}

	public void WithB(B b)
	{
		this._b = b;
	}
}
```

which you could use like this:
```
var fluent = new FluentThing()
	..WithA(new A())
	..WithB(new B())
```

**Comment by lyubomyr-shaydariv** [comment]
@Richiban 
yeah, that's a nice idea, because it seems to be a purely call-site issue. Usually, there's a need of chaining the `void` methods, and fluent builder chain methods (the way they exist so far) are a just a syntactic workaround. I had a similar idea above but I was not sure about the syntax. `..` looks nice and it seems to support any methods no matter what return types they have. :)

**Comment by HaloFour** [comment]
The problem with a syntax like that is that when applied to a class representing an immutable builder if you're chaining against the original reference you're basically throwing away all of the intermediate calls.

**Comment by jvlppm** [comment]
@HaloFour . My proposal does not work for immutable objects, I don't know how it could be updated to benefit immutable classes.

@Richiban The only downside of chaining void methods is that:
This change would affect only methods that were not designed to be used that way, whether you want it or not.
And the methods that were already implemented with this pattern in mind, won't get any benefit (unless they are updated to return void).
I don't know if that is really a problem.

@sharwell Using extension methods does solve the problem, but extension methods won't have access to private/protected fields, making it very limited, so it cannot be used everywhere.

@SolalPirelli The curiously recurring template pattern does work, but it does not solve the issues that this proposal targets.

> Simpler to write fluent methods (No return this necessary).

The curiously recurring template pattern is not as simple as using ```this``` as return type.

> Clearer API (no guessing about whether the method return a new instance, or itself).

With the curiously recurring template pattern you know the return type, but not whether the returned object is the same or not.

> Better tooling (Intelissense would know more specifically the method return type).

When you inherit from an existing class you lose the specific return type information.

```csharp
    interface IBase<T> where T : IBase<T>
    {
        T Test();
    }

    class Other : IBase<Other>
    {
        public Other Test()
        {
            throw new NotImplementedException();
        }
    }

    class SomeOther : Other { ... }

SomeOther a = (SomeOther) new SomeOther().Test(); // Cast is still needed
```

Unless you do something like:

```csharp
    class Test2 : Other, IBase<Test2>
    {
        public new Test2 Test()
        {
            base.Test();
            return this;
        }
    }
```

For every base class method...

My proposal is valid, but it can help only mutable object methods, where ```return this``` is the only possible return.
I don't know if this pattern is common enough to be worth investing (maybe it is).

**Comment by biqas** [comment]
@jvlppm I think it is worth and i also posted some threads in the previous discussion on Codeplex.
http://roslyn.codeplex.com/discussions/562656 and also here on GitHub. https://github.com/dotnet/roslyn/issues/311.

Currently the language is not providing anything which is type safe to achieve this. The curiously recurring template pattern and co-variant overrides are not solving the problem.

**Comment by dharmatech** [comment]
@Richiban There's a User Voice [entry for adding method cascades C#](https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/5182443-add-method-cascades-to-c).

**Comment by firda-cze** [comment]
Hi, I have recently made the same proposal (as #2322) because I was not searching for 'fluent' but for 'this as return type'. So...

Extension method can solve the problem, but it requires to always have two versions of the same method. One being the implementation (which can access all it needs) and being either `public` or `internal`, the other being generic extension that simply calls the implementation and returns the object.

```C#
public class One
{
    internal void Impl() { ... }
}
public class Second: One
{
    internal void Impl2() { ... }
}
public static class FluentExtensions
{
    public static T TheMethod(this T me) where T: One { me.Impl(); return me; }
    public static T SecondMethod(this T me) where T: Second { me.Impl2(); return me; }
}

new Two().TheMethod().SecondMethod();
```
...but it is ugly and a lot of unnecessary coding. Replacing `void` with `this` and emit one attribute to tell the compiler that it can be chained would solve it nicely.

```C#
public class One
{
    public this TheMethod() { ... }
}
```

shall be seen as

```C#
public class One
{
    [ReturnThis]
    public void TheMethod() { ... }
}
```

and the chain
```C#
new Two().TheMethod().SecondMethod();
```

as
```C#
var it = new Two();
it.TheMethod();
it.SecondMethod();
```

Immutables won't be touched (as they will not use `this` as return type), but usage will look the same.

**Comment by firda-cze** [comment]
BTW: I am currently working on my own language (have working VSPackage with scanner and single-file-generator to C#) and added this feature, while not using 'void' as return type, but the enclosing class, changing all `return` statements to `return this` (while creating extended CodeDom in my parser) + add one `return this` as last statement (if it is not there... and is reachable, but that is TODO). The method will be marked with the attribute as described and code generator will look for the attribute and emit extra cast if needed (another TODO as I still have no reference-checking... but I can at least start using it).

This:
```C#
new Two().TheMethod().SecondMethod();
```
will be converted to
```C#
((Two)(new Two().TheMethod()).SecondMethod();
```

**Comment by firda-cze** [comment]
Another solution exists for `this.type`: shadowing the true virtual method (creating a bit different name for it) and add one callable, that calls the virtual and returns the object. But you have to update it in every derived class :(

I was experimenting with it a bit and this code snippet (in *my* language)
```
	next this override
	^ parse next word, literal, operator or character on this line
		base.next() //<<< this needs extra caution
		if word != null
			var code opcode
			_words.tryGetValue word, out code
			opcode = code
			return
        //...
```
will produce this:
```C#
        /// <summary>
        /// parse next word, literal, operator or character on this line
        /// </summary>
        public Lexer Next(  )
        {
            this.Next_();
            return this;
        }//Next
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Next_(  )
        {
            base.Next_(); //<<< here, needs to be detected to call the proper version
            if( Word != null )
            {
                Opcode code;
                _words.TryGetValue( Word, out code );
                Opcode = code;
                return;
            }
            //...
```

but there is tricky part: calling the base implementation - it needs to be detected and fixed to call the proper version. Still, it is doable in the compiler.

**Comment by gafter** [comment]
We do not expect to do what this requests, but we are considering covariant return types #357.

**Comment by Thaina** [comment]
@gafter I would like to have this than covariant return type

**Comment by copernicus365** [comment]
@gafter I'm sorry to see you say "We do not expect to do what this requests," but then you say "but we are considering covariant return types #357."

But as @sharwell [wrote](https://github.com/dotnet/roslyn/issues/357#issuecomment-173091915): "I also notice that it appears that you are confusing this issue with #155. However, covariant return types are a completely different proposal from the special case described there."

I'm really glad co-variant return types are being worked, but if co-variant return types don't fully solve the need for language support of Fluent APIs, I would strongly encourage that this or other proposed solutions that enable Fluent APIs typing not be tabled. It's a huge issue. Fluent typing is only becoming more and more important. Entire languages do nothing but fluent typing, like for instance jQuery. It's entire existence would be impossible without Fluent API typing. I have a fluent API library that generates ASP.NET MVC code that runs entirely on patterns like those [described above](https://github.com/dotnet/roslyn/issues/155#issuecomment-72044049), but there are real limitations you run into with this, and it could be so simplified with language support like this. Simply being able to return 'this' as a type, or some other ideas that would address fluent needs, I hope will still be seriously considered. Thanks guys.

**Comment by HaloFour** [comment]
@copernicus365 

How don't covariant returns solve the issue described in this proposal?  You would be permitted to override and return the current type as well as returning `this`.  All this proposal gives you in addition is a much more narrow scope, particularly since it doesn't account for fluent APIs over immutable types, which is a pattern that the team has expressed interest in encouraging.

JQuery is fluent specifically because the designers went to extra lengths to make it fluent.  JavaScript offers no special language features that exist specifically to enable fluent APIs.

**Comment by Thaina** [comment]
@HaloFour The main issue that covariant need to overridden unlike fluent

We only need to have all class return itself after doing some logic. But then we need to tell every child class to override one by one just to return itself. That's more junk code

I don't see why covariant return is better than fluent. Fluent is far more compact to solve what we really need. One problem is we may not want it to change any logic. But covariant let you do that and there are no way to make sure overriding will call it base

**Comment by HaloFour** [comment]
@Thaina 

This proposal is much too limited, even for fluent APIs.  It limits the API to a single verb and encourages mutability.  How many fluent APIs actually follow that model?  Few in my experience.  JQuery doesn't, it returns new instances containing the new state of the operation or selection.  LINQ doesn't, it always returns a new `IEnumerable<T>` wrapping the target with the new operation.

Covariant returns solves multiple problems and enables more fluent API forms, including single-verb immutable builders, which is a better pattern to enable and encourage.

**Comment by copernicus365** [comment]
@HaloFour, thanks for the response. 

How is this going to work in the case of a ButtonBase class which has a number of Button classes that inherit from it, or a TooltipBase class which has a few or more Tooltip classes that implement it? Even worse a HtmlWidget class which ButtonBase and TooltipBase and all of their Buttons and Tooltip controls inherit from (this is true for my scenario, lots of base fluent method types are on the base HtmlWidget class)? I'm guessing this is going to be no good. We would want the base methods they have in common (like SetSize, or SetColor, etc) to be specified on the base class which is able to simply return the final implemented class back.

`public class HtmlWidget { 

   SizeEnum _size;
   public this SetSize(SizeEnum size) { _size = size; return this; }

   // or would 'self' work better? I don't really care, I just want the functionality! Other threads had the attribute route
   // public self SetSize...
}

public class ButtonBase : HtmlWidget { /*...*/ }

public class SubmitButton : ButtonBase {
   // SetSize already works! returns SubmitButton 
}

class SubmitButtonAjax : ButtonBase {
   // SetSize already works! returns SubmitButtonAjax 
}
`
It's impractical and hugely inefficient to say we have to override every single one of these methods on every single end-of-the-line in inheritance classes when one of the base classes inherited from could be the one that simply returns the actual implementing type as it's return type. It defeats the purpose in my view. I would continue to use the basically hack of putting the functionality in a separate static class with generic extension methods that relies on generic constraints. But as someone else said in one of these related threads, there should be no need to have generics involved in this implementation (as he said, Java had some such functionality without that).

Or does covariant returns actually do this? Great if it does, not great if it doesn't. If it doesn't, then please let's not table this kind of fluent functionality as a separate ticket. And by the way, on this mutable / immutability business, I could care less about having that restriction, just so long as the same expected type gets returned. But if you know technical reasons where it would be easier to require having to return the same exact instance, fine. What matters most is having the ability to return the final implemented class instance from a base class. 

Thanks mates

**Comment by copernicus365** [comment]
> JQuery doesn't, it returns new instances containing the new state of the operation or selection. LINQ doesn't...

Just a quick note, both LINQ and JQuery are all about sequences. Fluent APIs are by no means just about sequences, as indeed never the case in my fluent library. Sure, it could be for other fluent libraries, but I hope we can think first of all about single instances. The functionality is to be able to keep acting on a type, like for instance (StringBuilder): `sb.AppendLine("Hello").AppendLine("World").AppendLine("!");` 

Of course, in that case it is a single type so just returns itself (StringBuilder), but we need that functionality for cases where a base class has functionality used by the derived class, without loosing then in the returns the derived type.

**Comment by HaloFour** [comment]
@copernicus365

You'd be required to re-override the methods.  There's nothing about the CLR or C# type systems which would allow for methods to be automagickally covariant in the way that you describe.  At *best* the C# compiler could put an attribute on the method to note that it *should* return the same type (or instance) as the instance on which it is called, but nothing could enforce that and like any type erasure it could be defeated very easily resulting in runtime exceptions.  The synthetic bridge method approach to covariant returns at least prevents this.

Yes, fluent APIs take all kinds of shapes.  jQuery's is often about sequences but not exclusively.  LINQ is definitely about sequences.  But the sequence aspect is irrelevant, what is important is that they build a context through a series of consecutive verbs where state is retained but only in the result of each individual verb.  Such immutable patterns for fluent APIs are preferred and should be encouraged.  They often have contextual verbs based on previous calls, which this proposal doesn't address given that you're forced to return the same instance.

If metaprogramming/code-generation comes to pass you should be able to relatively easily have the covariant overrides automatically generated for you, though.  An analyzer could probably help to do this now.

**Comment by copernicus365** [comment]
> There's nothing about the CLR or C# type systems which would allow for methods to be automagickally covariant in the way that you describe.

Ahem, these are _feature requests_, so the point is, what if this _can _be done? I never said it's already possible, of course not. I do appreciate your expertise, and I do appreciate if some of you low-level, compiler building experts (which I am not) say it's _simply impossible to find a way for this to be done_. If that turns out to be the case, then I'm sorry to have wasted your time. 

But in the other related threads, I heard others say _both Java and Scala_ have this kind of feature. So paint me skeptical. Maybe it's more _the will to do it_ and _the recognition of it's importance_ that is missing? It seems surprising that there would not be a way to return 'this,' the most derived type in an inheritance, like proposed here: https://github.com/dotnet/roslyn/issues/311. It seems like what matters in the end is that the system, the type system, knows and enforces what type is being returned at a given time. Well well, the system *does* know when it's working on a given type and why can't that type just be returned then? I can't believe that can't be rigorously enforced, and thus made possible. 

Anyways, thanks for the discussion, but count me in as voting this as a majorly helpful feature if it indeed can be done.

**Comment by HaloFour** [comment]
Java'so return value covariance functions the exact same way that the C# team is implementing it for C# 7.0, through bridge methods.  There is no automatic covariance in Java.  The JVM doesn't support an *automatic* way of transforming the return type any more than the CLR does, it requires the compiler to emit the different signature and to bridge the overridden method.

Either way, the C# team appears to have decided that covariant returns are sufficient for implementing this pattern and they decided to close this proposal.

**Comment by copernicus365** [comment]
Okay (bummer), but thanks for the information on Java. Maybe sometime in the future something or other can make this feature a possibility.

**Comment by Thaina** [comment]
> There is no automatic covariance in Java

More the reason C# should have anything better than Java
