### ISSUE TITLE
"Use null propogation" code fix introduces a compiler error

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#15505]
**Version Used**: 
VS2017 RC

**Steps to Reproduce**:

1. Enable Full solution analysis for C#
2. Open Roslyn.sln and source file `src\Compilers\CSharp\Portable\CSharpCompilationOptions.cs`
3. Observe below suggestion in the error list:
```
Severity	Code	Description	Project	File	Line	Suppression State
Message	IDE0030	Null check can be simplified	CSharpCodeAnalysis	C:\roslyn-internal\Open\src\Compilers\CSharp\Portable\CSharpCompilationOptions.cs	618	Active
```
4. Press Ctrl + dot to invoke code fix

**Expected Behavior**: 
Code fix is applied without introducing any errors.

**Actual Behavior**:
Code fix introduces the following error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0023	Operator '?' cannot be applied to operand of type 'ImmutableArray<string>'	CSharpCodeAnalysis	C:\roslyn-internal\Open\src\Compilers\CSharp\Portable\CSharpCompilationOptions.cs	618	Active
```
![image](https://cloud.githubusercontent.com/assets/10605811/20580684/abf5122a-b188-11e6-91ad-6995bd7bfb96.png)

**Comment by Pilchie** [comment]
Darn struct comparisons with null...

**Comment by jwooley** [comment]
This issue would arise as well if you follow the recommendation inside of an IQueryable (Entity Framework) LINQ query. It would not raise a compile time exception, but would fail at runtime when parsing the query from the provider. Found with VS 2017 RC build 15.0.26009.0.
