### ISSUE TITLE
IOperation reports 'Instance' for static method access in delegate creation xpression.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15513]
From https://github.com/dotnet/roslyn/issues/15325

Given the code:

```c#
using System;

class A
{
    static int Function(int x) => x + x;
    static void Error()
    {
        var func = new Func<int,int>(Function); // <- IDE0009	Member access should be qualified. Lightbulb says to change this to "this.Function", but its compile error.
        func(1);
    }
}
```

For the reference to "Function" (inside ```new Func<int, int>(Function)```), we get an IMemberReferenceExpression that has a non-null ```.Instance``` value.  The kind of this is "InstanceReferenceExpression".  This doesn't make sense as "Function" is a reference to a static method.

**Comment by mavasani** [comment]
@333fred Is this done with your recent changes?

**Comment by 333fred** [comment]
Doesn't look like it, just tested. We still have a non-null Instance here. The reason appears to be that we actually do have a `BoundThisReference` as the `InstanceOpt` of the method group we create the `IMethodReference` from.
