### ISSUE TITLE
System.Runtime.InteropServices.RuntimeInformation package should be included as a dependency for MSBuildWorkspace

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#15510]
NuGet package 2.0.0-rc for the workspace doesn't seem to work if you don't additionally install https://www.nuget.org/packages/System.Runtime.InteropServices.RuntimeInformation

**Comment by tmat** [comment]
Related: https://github.com/dotnet/roslyn/issues/15518
