### ISSUE TITLE
Incorrect completion, navigate to not working in AppDomainUtils.cs

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#15524]
Open AppDomainUtils.cs in Roslyn.sln. 

Go To Definition doesn't work on AppDomain.CreateDomain.

The list of available overloads is also off:
![image](https://cloud.githubusercontent.com/assets/41759/20611048/1520a51e-b258-11e6-89c8-694c2b4a9591.png)

https://msdn.microsoft.com/en-us/library/system.appdomain.createdomain(v=vs.110).aspx

Repros on D15Rel 25920 with latest Roslyn VSIX from master installed.

**Comment by CyrusNajmabadi** [comment]
You have named parameters.  So i believe we've filtered the list down to only those that would be applicable with those named parameters.

I cannot repro goto-def not working.

**Comment by tmat** [comment]
I actually wanted to change some of the parameters and call another overload. The filtering is not useful in that scenario.

**Comment by tmat** [comment]
Re GTD: I can repro 100% in multiple clones of Roslyn repo on my machine. Perhaps it's something in the .vs cache that's corrupted? I have uploaded zipped repo to %internal_share%\public\tomat\Bugs\15524 as is (including .git and .vs folders). You just need to have all nuget restored from another repo on your machine to avoid calling restore.

**Comment by tmat** [comment]
I think it would be better if instead of filtering the non-matching overloads out we moved them to the end of the list. Perhaps also fade them out.

**Comment by CyrusNajmabadi** [comment]
GTD shouldn't be impacts by any caches at all.  Will try to debug it on your machine next week.  

Interesting suggestions about SigHelp improvements.  We can def look into that in the future.

**Comment by tmat** [comment]
I suggest removing the filtering for now until we implement something better. As it is currently it's a regression from the previous behavior. Users will be surprised they don't see APIs they think they should see. I definitely was.

**Comment by CyrusNajmabadi** [comment]
I think we've had the filtering for a while now.  But i do like the idea of just using the names to prioritize the items, versus using them to filter the items out.

**Comment by tmat** [comment]
You are right - it's filtering out the overloads in Dev14 as well. I haven't realized that. Not a regression then.

**Comment by Pilchie** [comment]
@CyrusNajmabadi can you take a look at the Go to Definition failures when you get a chance?

@tmat can you file a separate issue for the sig-help suggestions?

**Comment by CyrusNajmabadi** [comment]
@tmat Are you still repro'ing goto-def not working?

**Comment by CyrusNajmabadi** [comment]
I fixed issues with gotodef not working properly with https://github.com/dotnet/roslyn/pull/17725

If you see this again, let us know.
