### ISSUE TITLE
'Call hierarchy' window is unable to expand local functions ('searching...' takes forever)

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#15522]
Expanding local functions' call nodes never ends in VS 2017 RC.

```cs
    class Program
    {
        static void Main(string[] args)
        {
            Local();
            void Local() => Bar();
        }
        static void Bar() { }
    }
```

![callhierarchy](https://cloud.githubusercontent.com/assets/5566206/20608444/1f9813a2-b293-11e6-99fc-2a76b600be59.gif)

**Comment by agocke** [comment]
Looks like this was fixed by #15820
