### ISSUE TITLE
"Variable declaration can be inlined" sometimes does not respect "var" settings

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15526]
The variable declaration can be inlined sometimes does not always respect my "var" settings

![image](https://cloud.githubusercontent.com/assets/1103906/20614052/12b999f4-b31e-11e6-82ff-0d430be7d28b.png)

I can't get a standalone repro because when I try to isolate it does respect it, but to see examples, run this fixer across the project system repro.

Example (https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/NuGetDependenciesSubTreeProvider.cs#L177):

![image](https://cloud.githubusercontent.com/assets/1103906/20614039/dec21478-b31d-11e6-8003-7cf097491576.png)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/15306
