### ISSUE TITLE
Now it's time to discuss which new language features would be in C# 8.0

### ISSUE THREAD

**Issue by ygc369** [dotnet/roslyn#15537]
As C# 7.0 will be released soon, there's no time to add more features. But there are still many good ideas that has not come true in C# 7.0, so I wonder which of them would be in the roadmap of C# 8.0, such as escape analysis and reference count as alternative GC.

**Comment by HaloFour** [comment]
I believe that both of those suggestions would belong under [CoreCLR](https://github.com/dotnet/coreclr).  The C# compiler has no ability to replace the garbage collector nor to allocate reference types onto the stack.

I think that you'd likely find C# 8.0 to be initially comprised of those items that slipped from the original C# 7.0 work list.  This would likely include further enhancements to pattern matching, asynchronous sequences (`IAsyncEnumerable`), `readonly` parameters/locals, non-nullable references and probably a few others that I'm forgetting, plus whatever other proposals here are in a ready state and championed by an LDM member.

**Comment by svick** [comment]
There is already [a list of features currently planned for C# 8.0](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md#c-70-and-vb-15--1).
