### ISSUE TITLE
Inline Temporary Variable omits parentheses when calling extension methods

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#15530]
**Version Used**: 2017 RC

```C#
async Task M() {
	var t = await Task.FromResult("");
	t.Any();
}
```

The Inline Temporary Variable refactoring produces `await Task.FromResult("").Any();`, which does not compile.

It looks like you need to move the parenthesis check before unreducing extension methods.

**Comment by CyrusNajmabadi** [comment]
Nice catch!
