### ISSUE TITLE
Renaming a local function breaks code by renaming usages of unrelated elements

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#15533]
The refactoring tries to rename all symbols with the same name even if they are referencing another function

```cs
    class Program
    {
        static void Main(string[] args)
        {
            if ("".Length > 0)
            {
                Action a = Local;
                void Local()
                {
                    Console.WriteLine("Hello from Local");
                } // Local
            }
            else
            {
                Action a = Local;
                void Local() // <-- invoke the refactoring here
                {
                }
            }
        }
    }
```

Obviously changes should be limited to the 'else' block, otherwise my code will be completely broken by the refactoring.

![roslynrename](https://cloud.githubusercontent.com/assets/5566206/20631007/88c99334-b345-11e6-877d-90324f385c98.png)

**Comment by agocke** [comment]
Looks like this was fixed by #15820
