### ISSUE TITLE
Duplicate items in Errors List if the analyzer message contains a newline

### ISSUE THREAD

**Issue by alinapopa** [dotnet/roslyn#1554]
Related to issue #1455 (message is truncated in the output window).
After building the project, the Error List contains two items for each error or warning, one with the full message and the other with the truncated message.
Example: 
The analyzer message is:
MessageFormat = "First line of message. " + System.Environment.NewLine + "Second line of message. ";
Error list shows:
![error2](https://cloud.githubusercontent.com/assets/8061142/6815999/8a65487e-d24a-11e4-9741-47c51d7d48a5.png)
The tooltip also shows two messages
![error3](https://cloud.githubusercontent.com/assets/8061142/6816011/b7b298ae-d24a-11e4-97d7-6a91d99fdb59.png)

**Comment by heejaechang** [comment]
#1402 should fix this issue once checked in.
