### ISSUE TITLE
IEnumerable<T> runs constructor any access(even inspection)

### ISSUE THREAD

**Issue by timopomer** [dotnet/roslyn#15547]
**Version Used**: 
mono 4.8.0 
.NET framework 4.6.1
**Steps to Reproduce**:

1. Create a class, preferably with a static integer you can increment to count individual constructor calls
2. Create IEnumerable of the class by selecting an arbitrary array of items
3. Use breakpoints to Inspect with debugger / Try to print or count the elements to cause the constructor to run again

**Expected Behavior**:
Constructor runs once for each element and objects are stored inside IEnumerable 
**Actual Behavior**:
Constructor runs every time elements are accessed in any way

You can avoid the bug by casting the IEnumerable to a List<> or array to cause all constructors to be ran once and the objects be saved properly

Code to reproduce:

```
	public class SomeClass
	{
		public static int index = 0;
		public int localIndex;
		public string type;

		public SomeClass(string type)
		{
			this.type = type;
			this.localIndex = SomeClass.index;
			SomeClass.index++;
			Console.WriteLine($"Node created: {this}");
		}
		public override string ToString()
		{
			return $"[{this.type} and my index is {this.localIndex}]";
		}
	}

	static class MainClass
	{
		public static void Main(string[] args)
		{

			IEnumerable<SomeClass> allClasses = new string[] { "1", "2", "3" }.Select(n => new SomeClass($"I hold {n}"));

			Console.WriteLine(allClasses.Count());
			foreach (SomeClass g in allClasses)
			{
				Console.WriteLine("Print after: " + g);
			}
		}
	}
```

Putting a breakpoint on line `Console.WriteLine(allClasses.Count());` and inspecting allClasses causes the values inside to change every time you inspect them

![First inspection](http://image.prntscr.com/image/69977e567b1140b6b4e4d893da74330e.png)
![Second inspection](http://image.prntscr.com/image/a7d264a31ebc4b508bdc94ed3a65b200.png)

**Comment by gafter** [comment]
This is the way that lazy iterators work: `Select` computes the result on demand, and doesn't cache the result. It only caches the lambda so it can compute the result every time. If you want the result cached, you should use your own implementation of `Select` that does that, or call `ToArray` early on.

I'm not sure why this is posted on the Roslyn repo. Do you think there is a compiler bug?

**Comment by timopomer** [comment]
I thought this has to do with the IDE being broken, if this is intentional im sorry. just my code completely breaking from inspecting it in the debugger called an alarm bell and made me try to reproduce this "bug" for a good while

Thank you
Nonetheless as a suggestion I think the debugger should warn you inspecting the IEnumerable will make the constructors run or some other warning of that kind

**Comment by svick** [comment]
Visual Studio debugger in the same situation says "Expanding the Results View will enumerate the IEnumerable". Maybe VS Code could say something similar.

@timopomer You might consider requesting that at [VS Code's repo](https://github.com/Microsoft/vscode).

**Comment by timopomer** [comment]
@svick but im using visual studio for mac (the reskinned xamarin studio) does it have a repo?
