### ISSUE TITLE
Debugger doesn't recognize catch variable in async method

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1555]
Source:

```C#
using System;
using System.Threading.Tasks;

class A {
	static void Main(string[] args) {
		Run().Wait();
	}
	static async Task Run() {
		try {
			throw new InsufficientExecutionStackException();
		} catch (InsufficientExecutionStackException ex) {
		}  // Breakpoint here
	}
}
```

At the breakpoint, `ex` errors (CS0103) in Watch and does not appear in Locals.
Removing `async Task` makes it work fine.

`$exception` does work.

**Comment by ManishJayaswal** [comment]
This seems to work in the latest builds. I see ex in locals window and when I evaluate it in watch then I get the following:

+		ex	{"Insufficient stack to continue executing the program safely. This can happen from having too many functions on the call stack or function on the stack using too much stack space."}	System.InsufficientExecutionStackException
