### ISSUE TITLE
System.Collections.Immutable > 1.1.37 is evil

### ISSUE THREAD

**Issue by philippe-lavoie** [dotnet/roslyn#15559]
For whatever reason, each time I upgrade a nugetpackage somehow related to nuget, things start to fail. This time, I'm getting the following error when running a VSIX custom editor.

Method not found: 'System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.INamedTypeSymbol> Microsoft.CodeAnalysis.INamespaceOrTypeSymbol.GetTypeMembers()'.

Turns out that reverting System.Collections.Immutable to 1.1.37 fixes it. 

Can you please... pretty please... tell your nuget packages that if you update immutable collections everything will stop working?  That would prevent me (and others) from loosing a day trying to understand the above cryptic error. 

The evilness of that library is not to be taken lightly. The debugger even decided to inline everything and wouldn't allow me to step into the method that throws the above error. Revert that library and magic happens, you can debug normally and roslyn works properly. 

1.2.0 or 1.3.0 of that library both cause Roslyn to act weird.  Maybe it's because I'm calling it within a VSIX addon. Maybe not... in all cases, it shouldn't break everything.

**Comment by bkoelman** [comment]
Yes, I've run into that too in the past. Unfortunately it is nowhere documented that updating packages is tricky when using roslyn. 

The problem is that the roslyn assemblies (and dependencies) are already loaded in VS before your vsix is loaded. Whatever your vsix then references is ignored due to binding redirects; your vsix will run against the assemblies that ship with VS. Note this varies per Visual Studio version. 

To be safe, you should reference the 1.0.0 version of roslyn assemblies in your vsix project, which works in all versions of VS 2015 (Default/Update1/2/3).

**Comment by tmat** [comment]
@philippe-lavoie Can you be more specific about the scenario? What version of Visual Studio are you using. What version of Roslyn package does your package reference? What other dependencies does your package have?

**Comment by philippe-lavoie** [comment]
I'm authoring a VSIX extension in Visual Studio 2015. The full packages.config is shown below. Please note, that this is the working version, change 1.1.37 to 1.2.0 or 1.3.0 for that System.Collections.Immutable package and everything breaks.

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.CodeAnalysis" version="1.2.2" targetFramework="net462" />
  <package id="Microsoft.CodeAnalysis.Analyzers" version="1.1.0" targetFramework="net462" />
  <package id="Microsoft.CodeAnalysis.Common" version="1.2.2" targetFramework="net462" />
  <package id="Microsoft.CodeAnalysis.CSharp" version="1.2.2" targetFramework="net462" />
  <package id="Microsoft.CodeAnalysis.CSharp.Workspaces" version="1.2.2" targetFramework="net462" />
  <package id="Microsoft.CodeAnalysis.VisualBasic" version="1.2.2" targetFramework="net462" />
  <package id="Microsoft.CodeAnalysis.VisualBasic.Workspaces" version="1.2.2" targetFramework="net462" />
  <package id="Microsoft.CodeAnalysis.Workspaces.Common" version="1.2.2" targetFramework="net462" />
  <package id="Microsoft.Composition" version="1.0.30" targetFramework="net462" />
  <package id="Microsoft.VisualStudio.Imaging" version="14.3.25407" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.LanguageServices" version="1.2.2" targetFramework="net462" />
  <package id="Microsoft.VisualStudio.OLE.Interop" version="7.10.6070" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.Shell.14.0" version="14.3.25407" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.Shell.Immutable.10.0" version="10.0.30319" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.Shell.Immutable.11.0" version="11.0.50727" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.Shell.Immutable.12.0" version="12.0.21003" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.Shell.Immutable.14.0" version="14.3.25407" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.Shell.Interop" version="7.10.6071" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.Shell.Interop.10.0" version="10.0.30319" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.Shell.Interop.11.0" version="11.0.61030" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.Shell.Interop.12.0" version="12.0.30110" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.Shell.Interop.8.0" version="8.0.50727" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.Shell.Interop.9.0" version="9.0.30729" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.TextManager.Interop" version="7.10.6070" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.TextManager.Interop.8.0" version="8.0.50727" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.Threading" version="14.1.131" targetFramework="net462" />
  <package id="Microsoft.VisualStudio.Utilities" version="14.3.25407" targetFramework="net452" />
  <package id="Microsoft.VisualStudio.Validation" version="14.1.111" targetFramework="net452" />
  <package id="Microsoft.VSSDK.BuildTools" version="14.3.25420" targetFramework="net462" developmentDependency="true" />
  <package id="Microsoft.Web.Xdt" version="2.1.1" targetFramework="net462" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net462" />
  <package id="NuGet.Common" version="3.4.3" targetFramework="net462" />
  <package id="NuGet.Configuration" version="3.4.3" targetFramework="net462" />
  <package id="NuGet.Core" version="2.12.0" targetFramework="net462" />
  <package id="NuGet.DependencyResolver" version="3.4.3" targetFramework="net462" />
  <package id="NuGet.DependencyResolver.Core" version="3.4.3" targetFramework="net462" />
  <package id="NuGet.Frameworks" version="3.4.3" targetFramework="net462" />
  <package id="NuGet.LibraryModel" version="3.4.3" targetFramework="net462" />
  <package id="NuGet.Logging" version="3.4.3" targetFramework="net462" />
  <package id="NuGet.Packaging" version="3.4.3" targetFramework="net462" />
  <package id="NuGet.Packaging.Core" version="3.4.3" targetFramework="net462" />
  <package id="NuGet.Packaging.Core.Types" version="3.4.3" targetFramework="net462" />
  <package id="NuGet.Protocol.Core.Types" version="3.4.3" targetFramework="net462" />
  <package id="NuGet.Protocol.Core.v2" version="3.4.3" targetFramework="net462" />
  <package id="NuGet.Protocol.Core.v3" version="3.4.3" targetFramework="net462" />
  <package id="NuGet.Repositories" version="3.4.3" targetFramework="net462" />
  <package id="NuGet.RuntimeModel" version="3.4.3" targetFramework="net462" />
  <package id="NuGet.Versioning" version="3.4.3" targetFramework="net462" />
  <package id="System.AppContext" version="4.3.0" targetFramework="net462" />
  <package id="System.Collections" version="4.3.0" targetFramework="net462" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="net462" />
  <package id="System.Collections.Immutable" version="1.1.37" targetFramework="net462" />
  <package id="System.Console" version="4.3.0" targetFramework="net462" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net462" />
  <package id="System.Diagnostics.FileVersionInfo" version="4.3.0" targetFramework="net462" />
  <package id="System.Diagnostics.StackTrace" version="4.3.0" targetFramework="net462" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="net462" />
  <package id="System.Dynamic.Runtime" version="4.3.0" targetFramework="net462" />
  <package id="System.Globalization" version="4.3.0" targetFramework="net462" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="net462" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net462" />
  <package id="System.Linq" version="4.3.0" targetFramework="net462" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="net462" />
  <package id="System.Reflection" version="4.3.0" targetFramework="net462" />
  <package id="System.Reflection.Metadata" version="1.2.0" targetFramework="net462" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="net462" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net462" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net462" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net462" />
  <package id="System.Runtime.Handles" version="4.3.0" targetFramework="net462" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="net462" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="net462" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net462" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net462" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net462" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net462" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="net462" />
  <package id="System.Text.Encoding.CodePages" version="4.3.0" targetFramework="net462" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="net462" />
  <package id="System.Threading" version="4.3.0" targetFramework="net462" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="net462" />
  <package id="System.Threading.Tasks.Parallel" version="4.3.0" targetFramework="net462" />
  <package id="System.Threading.Thread" version="4.3.0" targetFramework="net462" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="net462" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="net462" />
  <package id="System.Xml.XmlDocument" version="4.3.0" targetFramework="net462" />
  <package id="System.Xml.XPath" version="4.3.0" targetFramework="net462" />
  <package id="System.Xml.XPath.XDocument" version="4.3.0" targetFramework="net462" />
</packages>

**Comment by jasonmalinowski** [comment]
Taking this bug as I'll be bringing up with the SDK team.

**Comment by philippe-lavoie** [comment]
Thanks, glad it's being looked at. It's always unsettling when you need to accrue technological debt and can't leverage the latest supported version of a library. Roslyn and VSIX should easily worked together as VSIX is a perfect candidate for Roslyn. I think the same thing for Analaysis and CodeFix packages.

**Comment by jasonmalinowski** [comment]
It is possible to do use a higher version, the challenge is Visual Studio has some complicated rules about how it finds assemblies. In your VSIX you could add a few extra lines and tell it "find this newer System.Collections.Immutable over here" and it'll work, but how to do that isn't obvious unless you know how to do that.

**Comment by onetruejones** [comment]
jasonmalinowski - where you say "that isn't obvious unless you know how to do that" - is there any chance you could let me know how to do that? I have encountered this issue and I am completely stumped.

**Comment by sharwell** [comment]
@onetruejones You have to use `ProvideCodeBase`.

```csharp
[assembly: ProvideCodeBase(
    AssemblyName = "System.Collections.Immutable",
    Version = "1.2.0.0",
    CodeBase = "$PackageFolder$\\System.Collections.Immutable.dll")]
```

You also need to have your extension included as a VsPackage asset with pkgdef generation enabled.

**Comment by tannergooding** [comment]
Note: Providing code base redirects for some of these core assemblies comes with the risk of breaking a various functionality in VS.

Generally, with any of the files in `Common7\IDE\PublicAssemblies` and `Common7\IDE\PrivateAssemblies`, VS stabilizes on a single version at release and any number of installed components (or 3rd party extensions) could be dependent on that functionality or behavior. If `S.C.Immutable`, as an example, took any runtime breaking changes between version A (which shipped with VS) and version B (which you are upgrading to) you may end up in an indeterminate state (at least until you uninstall your extension).

**Comment by GeorgeAlexandria** [comment]
I also have a couple issues with Method not found exception, and  `System.Collections.Immutable.1.1.37` when I work under Vsix for VS 2015 update 3. 

I was try to use `Microsoft.CodeAnalysis.Common.1.3.1` nuget package to fix these issues and I was surprised that the `Microsoft.CodeAnalysis.Common.1.3.1` depends on the  `System.Collections.Immutable.1.2.0` nuget package under `.netstandard13`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Microsoft.CodeAnalysis.Common</id>
    <version>1.3.1</version>
    ...
    <dependencies>
      <group targetFramework=".NETPortable0.0-Profile7">
        <dependency id="System.Collections.Immutable" version="1.1.37" />
        <dependency id="System.Reflection.Metadata" version="1.2.0" />
        <dependency id="Microsoft.CodeAnalysis.Analyzers" version="1.1.0" />
      </group>
      <group targetFramework=".NETStandard1.3">
        <dependency id="Microsoft.CodeAnalysis.Analyzers" version="1.1.0" />
        <dependency id="System.AppContext" version="4.1.0" />
        <dependency id="System.Collections" version="4.0.11" />
        <dependency id="System.Collections.Concurrent" version="4.0.12" />
        <dependency id="System.Collections.Immutable" version="1.2.0" />
        ...
      </group>
    </dependencies>
  </metadata>
</package>
```
the package `System.Collections.Immutable.1.2.0` contains the ***v1.2.0*** of relevant assembly, but the assembly `Microsoft.CodeAnalysis.dll` from the package `Microsoft.CodeAnalysis.Common.1.3.1` references the `System.Collections.Immutable.1.1.37` (as is shown in [dnspy](https://github.com/0xd4d/dnSpy))
![image](https://user-images.githubusercontent.com/13402478/45919516-2125c100-be9f-11e8-94fb-0f00bc050513.png)
I didn't check the all other Roslyn nuget packages of v1.3.1 but assume that they have the same incompatibility with `System.Collections.Immutable`. Did I misunderstand something?!

So to "use" `Microsoft.CodeAnalysis.*v1.3.1` we need to reference `System.Collections.Immutable.1.2.0` nuget packages and keep separately a `System.Collections.Immutable.dll` v1.3.7 that will substitute the v1.2.0 after a buid or just use [ProvideBindingRedirection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.providebindingredirectionattribute?redirectedfrom=MSDN&view=visualstudiosdk-2017) and [ProvideCodeBase](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.providecodebaseattribute?view=visualstudiosdk-2017), but as @tannergooding, pointed out, usages of this attributes comes with a couple of risks for VS

**Comment by codehunter13** [comment]
?

**Comment by sharwell** [comment]
The version(s) of Roslyn, System.Collections.Immutable, and a few other libraries (e.g. Newtonsoft.Json) are dictated by the range of Visual Studio a Visual Studio extension targets. I would need to know this range and the dependencies in question before being able to answer this question.
