### ISSUE TITLE
Fluent API formatting suggestion 

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#15554]
Currently, Visual Studio doesn't know how to format the following code:
```
var host = new WebHostBuilder()
            .UseKestrel()
							.UseContentRoot(Directory.GetCurrentDirectory())
							.UseIISIntegration()
							.UseStartup<Startup>()
							.Build();
```
What I expect to happen is for all subsequent calls to be vertically aligned with the first dot operator.

So the above code would be formatted like this:
```
var host = new WebHostBuilder()
            .UseKestrel()
            .UseContentRoot(Directory.GetCurrentDirectory())
            .UseIISIntegration()
            .UseStartup<Startup>()
            .Build();
```
Alternatively:
```
var host = new WebHostBuilder().UseKestrel()
                               .UseContentRoot(Directory.GetCurrentDirectory())
                               .UseIISIntegration()
                               .UseStartup<Startup>()
                               .Build();
```
I use R# quite heavily for formatting and it does know how to do it but I think that it would be nice if VS could handle it out of the box too.

**Comment by Pilchie** [comment]
Yes, this would be nice to do - it's a little finicky requiring some options for how wrapping should behave though.

Note that smart indent should work after the first continued line though for the initial typing case.

**Comment by banshee** [comment]
FYI, I think it's surprising that anyone thinks this is a feature request. It's not; it's a terrible bug.  Makes editing C# a completely miserable experience.

**Comment by CyrusNajmabadi** [comment]
The IDE now has support through this through the lightbulb.  Using hte above:

![image](https://user-images.githubusercontent.com/4564579/76693490-188cf180-6623-11ea-8f0a-34937f552b98.png)

![image](https://user-images.githubusercontent.com/4564579/76693492-22aef000-6623-11ea-814e-6fcfd761a67b.png)

You end with:

![image](https://user-images.githubusercontent.com/4564579/76693495-2b072b00-6623-11ea-9d0e-f83f98d7620b.png)

You also get:

![image](https://user-images.githubusercontent.com/4564579/76693498-3bb7a100-6623-11ea-82a0-d9bd12f9f9ef.png)

**Comment by CyrusNajmabadi** [comment]
Closing out as being addressed with the existing wrapping system.  If there are additional issues, we should drive them through specific requests.

**Comment by twsouthwick** [comment]
@CyrusNajmabadi is there a way to apply this while generating code with Roslyn? I see it available via VS, but I've got some code generation projects that generates some fluent call chains, and, since they are fairly long, I'd prefer to have it automatically invoke the wrapping system before the output is generated and added to a project.

**Comment by CyrusNajmabadi** [comment]
You could take the code we have in roslyn and apply it yourself.  But it's not available as a general purpose API.  Sorry!
