### ISSUE TITLE
remove retry once root issue is fixed.

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15562]
we have retry to workaround root issue owned by other team
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/288961

remove those retry code once root issue is fixed.
http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.Next/Remote/ServiceHubRemoteHostClient.cs

**Comment by jinujoseph** [comment]
We can verify this only after 15.3 ships

**Comment by CyrusNajmabadi** [comment]
I do not see any retries in this code anymore.  Closing this out.
