### ISSUE TITLE
Cannot load debug symbols for Roslyn DLLs

### ISSUE THREAD

**Issue by CnSimonChan** [dotnet/roslyn#15571]
**Version Used**: 

Visual Studio 2015 Update 3

**Steps to Reproduce**:

1.  Clone this repo.
2.  Run `Restore.cmd` and `msbuild /v:m /m Roslyn.sln`
3.  Run `devenv /rootsuffix RoslynDev`
4. Start another Visual Studio, Attach to previous `devenv.exe`
5. Open `Modules` window, try load symbols for `Microsoft.CodeAnalysis.*.dll` by selecting from `Binaries\Debug\Dlls\*\Microsoft.CodeAnalysis.*.pdb`

**Actual Behavior**:

Visual Studio says "A matching symbol file was not found in this folder".

And the timestamps in the `Modules` window seem randomly.

![default](https://cloud.githubusercontent.com/assets/1330321/20698042/f970f87a-b638-11e6-8b28-1a8b42ecbdee.PNG)

**Comment by Pilchie** [comment]
The random timestamps are an expected side effect of the determinism compiler option, since we know write a hash to the timestamp field of the dll.

I believe that in step 2 we are not deploying the newly built extensions because our build process now assumes VS 2017 RC.  

Tagging @jaredpar for confirmation.

**Comment by CnSimonChan** [comment]
@Pilchie I did a recompilation and yes it didn't deploy them to the experimental instance.

But I can not deploy them with the .vsix package either, VS reports that the XML is not correctly formatted.

Does it mean `master` branch only supports VS 2017 now?

**Comment by Pilchie** [comment]
It's currently still possible to build and run tests with VS 2015, but yes, running the bits in VS requires VS 2017 RC now.  

Unfortunately, it became too difficult to maintain support for both.

**Comment by CnSimonChan** [comment]
I know, thank you.
