### ISSUE TITLE
msbuild issue

### ISSUE THREAD

**Issue by siddytopcoder** [dotnet/roslyn#15574]
Error MSB4019: The imported project "C:\Users\gautams\Downloads\MSBuild.Community.Tasks.v1.5.0.214\MSBuild.Community.Tasks.Targets" was not found.

**Comment by gafter** [comment]
What does this have to do with Roslyn?

**Comment by jcouv** [comment]
@siddytopcoder We didn't have enough information to investigate and didn't hear back from you. I'll go ahead and close the issue.
