### ISSUE TITLE
CSharpScript.RunAsync() fails when providing a Globals object

### ISSUE THREAD

**Issue by khionu** [dotnet/roslyn#15587]
**Version Used**: `Microsoft.CodeAnalysis.Scripting 1.3.2 and 2.0.0 RC (Issue occurs with .NET Core 1.1.0 but not 1.0.1)

**Steps to Reproduce**:

1. Use `CSharpScript.RunAsync()`, providing Globals 

**Expected Behavior**:
Script is compiled and executed.

**Actual Behavior**:
[InvalidCastException](https://gist.github.com/khionu/a69ab39950035e9533a0484d7627671d)

**Additional Notes**:
I am unsure if this is my environment or Roslyn, but given this broke after using .NET Core 1.1.0 and with how little information I could find on troubleshooting this issue, I felt it was best to report it.

I can confirm that the runtimes being used by Roslyn and my Project are the same, and that I only have one instance of the Entry Assembly (where the class `ReplGlobals` is) loaded.

**Comment by tmat** [comment]
C# Scripting is currently only supported on .NET Framework 4.6+, not on .NET Core. We'll look into issues on .NET Core at some point but unfortunately I can't give any estimates on time frame.

See https://github.com/dotnet/roslyn/issues/15352 for details.
