### ISSUE TITLE
Allow disabling warnings/errors to do with strong naming and binding redirects

### ISSUE THREAD

**Issue by davidfowl** [dotnet/roslyn#1558]
See https://github.com/aspnet/Home/issues/407. The dnx runtime automatically unifies to the versions specified in project.json using AssemblyResolve on full CLR. We need a way to tell the compiler to shut up since it'll be running on a runtime that doesn't require binding redirects.

**Comment by theoy** [comment]
@tmat - do you want to take a look at this?

**Comment by tmat** [comment]
@davidfowl Why don't you just suppress the warning?

**Comment by davidfowl** [comment]
I tried https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.Runtime.Roslyn.Common/CompilerOptionsExtensions.cs#L25. Unless i'm missing something...

**Comment by davidfowl** [comment]
Was disabling the wrong one it seems. Works!
