### ISSUE TITLE
Warning waves

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/roslyn#1559]
Has the "warning waves" feature been discussed in the open yet? There have been multiple references to it in this repo, but I can't find any official information on it. Has the community had the opportunity to offer feedback on the proposed design?

**Comment by WolfieWerewolf** [comment]
Hi Guys,

I’ve been following this thread with enthusiasm; the work you guys do amazes me.  I have a question though and hoped one of you kind people could shed some light.  I’m running the latest CTP and working with a standard C# console app project; no special build tools, the standard template.  I’m using Roslyn to dynamically compile an assembly as follows:

//Roslyn Test
            SyntaxTree tree1 = CSharpSyntaxTree.ParseText(swSciTeas[0]);
            SyntaxTree tree2 = CSharpSyntaxTree.ParseText(swSciTeas[1]);
            var compilation = CSharpCompilation.Create("SkyNetBars",
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary),
                     syntaxTrees: new[] { tree1, tree2 },
                     references: new[] {
                            MetadataReference.CreateFromAssembly(typeof(object).Assembly),
                            MetadataReference.CreateFromAssembly(typeof(TeaTime.Time).Assembly),
                            MetadataReference.CreateFromAssembly(typeof(System.Linq.Enumerable).Assembly),
                            MetadataReference.CreateFromAssembly(typeof(TeaFile).Assembly),
                            MetadataReference.CreateFromAssembly(typeof(PriceSeries).Assembly),
                            MetadataReference.CreateFromAssembly(typeof(PriceBar).Assembly)
                            });

            using (var memStream = new MemoryStream())
            {
                using (var pdbStream = new MemoryStream())
                {
                    var emitresult = compilation.Emit(peStream: memStream, pdbStream: pdbStream);
                    string compilationDiagnostics = string.Join(Environment.NewLine, from diagnostic in emitresult.Diagnostics
                                                                                     select diagnostic.GetMessage());
                    compilationStopWatch.Stop();
                    Console.WriteLine("Stage 2: Compilation in: " + compilationStopWatch.Elapsed.ToString() + Environment.NewLine);
                    Console.WriteLine("Stage 2: Compilation Diagnostics:" + Environment.NewLine);
                    Console.WriteLine("--------------------------------------------------------" + Environment.NewLine);
                    Console.WriteLine(compilationDiagnostics);
                    Console.WriteLine("--------------------------------------------------------" + Environment.NewLine);

                    Assembly SkyNetBars = Assembly.Load(memStream.GetBuffer(), pdbStream.GetBuffer());
                    //Original Working & Tested
                    Type sciTeaType = SkyNetBars.GetType("SkyNet.Bars.SciTea");
                    object sciTeaInstance = Activator.CreateInstance(sciTeaType, new object[] { _TicksProperty, _TrendProperty, _PullbackProperty, _ReversalProperty });
                    tickPriceSeries = (PriceSeries)sciTeaType.InvokeMember("Evaluate", BindingFlags.InvokeMethod | BindingFlags.Instance | BindingFlags.Public, null, sciTeaInstance, new object[] { });
                    //Original Working & Tested

                }


            }

When I attach the debugger to the running instance of the console app I can see the new in-memory assembly and that the symbols are loaded (dynamically) but when I attempt to step through the code VS reports that the “Source Code Files” cannot be located.  My assumption is that this has something to do with workspaces and that I need to hook up a workspace to my compilation somehow (I haven’t quiet figured that out yet)…. any advice would be very much appreciated.

Kind Regards

/W

**Comment by gafter** [comment]
@eatdrinksleepcode No public issue yet. There were a handful of designs floated internally before Roslyn went open-source. I'll dredge up a recent one and post it as a proposal/issue.

@WolfieWerewolf I don't think you meant to post your question here. It doesn't appear to have anything to do with warning waves.

**Comment by gafter** [comment]
See #1580
