### ISSUE TITLE
VS 2015 CTP 6 compile error

### ISSUE THREAD

**Issue by ellismg** [dotnet/roslyn#1560]
Per @talebi in dotnet/corefx#1238

I've already added a comment to this thread:
https://github.com/dotnet/corefx/issues/1001#issuecomment-84494151

Simply cannot compile a project having a reference to Revit API 2013. It says:
Metadata file 'E:\dev\cadtools_revit\Source\Lib\RevitAPI\RevitAPI_x64_2013.dll' could not be opened -- Row ID or heap offset is too large. The same project compiles in previous VS versions.

Can you guys take a first look and see if this is actually a metadata reader issue or something else?

**Comment by AlekseyTs** [comment]
It looks like this message is coming out of metadata reader:
src\System.Reflection.Metadata\src\Resources\MetadataResources.resx(271):    <value>Row ID or heap offset is too large.</value>

**Comment by VSadov** [comment]
@ellismg - it does look like metadata reader issue. Can you assign appropriately?
