### ISSUE TITLE
Suggestion: provide better SemanticModel/IDE experience inside broken foreach declaration

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#15601]
[In a code review it was suggested](https://github.com/dotnet/roslyn/pull/15548#discussion_r90164938) that we should bind and give good SemanticModel (and therefore IDE) experience inside an expression in this context:

`foreach (AnyExpression in e) {}`

where `AnyExpression` is some expression form not legally supported in this context.

**Comment by 333fred** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/19996
