### ISSUE TITLE
Re-enable skipped unit tests in CSharpEditorServicesTest broken by #1442

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#1561]
Re-enable skipped unit tests in CSharpEditorServicesTest broken by #1442 

Roslyn.Services.Editor.CSharp.UnitTests.dll, 10969 of 10973 test(s) passed
showing 4 of 4 failure(s)

TestGeneratePropertyInPropertyInitializers failed.
Assert.Equal() Failure
Position: First difference is at position 0
Expected: int
Actual:   static

TestGenerateFieldInPropertyInitializers failed.
Assert.Equal() Failure
Position: First difference is at position 0
Expected: readonly
Actual:   static

TestGenerateReadonlyFieldInPropertyInitializers failed.
Assert.Equal() Failure
Position: First difference is at position 0
Expected: int
Actual:   static

TestGenerateMethodInPropertyInitializer failed.
Assert.Equal() Failure
Position: First difference is at position 0
Expected: int
Actual:   static

**Comment by rchande** [comment]
Hm, Jenkins said the merged build was green. Thanks, will take a look.

**Comment by dpoeschl** [comment]
@rchande CSharpEditorServicesTests aren't run on Jenkins, unfortunately. :frowning: You can see the test assemblies that were run toward the bottom of the [build log](http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_windows_prtest/1320/console), and Roslyn.Services.Editor.CSharp.UnitTests is not included. (/cc: @jaredpar)

**Comment by rchande** [comment]
@jaredpar Didn't we talk at lunch about how Roslyn.Services.Editor.*.UnitTests assemblies took far to long? Or was that something else.

Either way, could we get Jenkins to run those assemblies? They hold the bulk of the IDE tests...
