### ISSUE TITLE
The .NET framework version dropdown on the New Project dialog is really out of place

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#15621]
_Disclaimer: Sorry if this is the wrong place to write it but I've reported this before on uservoice and other places such as msft blogs and nothing was done with it._

This is relevant to all versions of Visual Studio but maybe it can be changed for Visual Studio 15 RTM.

So when we create a new project today in Visual Studio and open the New Project dialog the .NET framework version dropdown appears at the top regardless to the selected template!

Even if I select a C++  project I still see this dropdown, I'm using Visual Studio for many, many years to me it's an annoyance but to new comers it can be totally confusing.

I feel like from a user experience perspective this dropdown needs to be shown only when you select a .NET project template, when you select a .NET Core project I feel it should list all the relevant versions for .NET Core as opposed to all the versions of the full .NET framework that has nothing to do with it.

**Comment by Pilchie** [comment]
@srivatsn @davkean This is definitely something we should think about after VS 2017.  Should we track it on the project system repo?

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#925
