### ISSUE TITLE
Changing the hyperlink in Error List

### ISSUE THREAD

**Issue by alinapopa** [dotnet/roslyn#1562]
I have created a code analyzer and when I use it, in the Error List the error or warning has a hyperlink on it that goes to search for Code + Description.
For a custom diagnostic analyzer this default hyperlink is not useful. Is there a way I can change this hyperlink? I would like to be able to remove it or set it to something else.

**Comment by heejaechang** [comment]
http://source.roslyn.io/#Microsoft.CodeAnalysis/Diagnostic/DiagnosticDescriptor.cs,4a0a00cc5df1dbb4,references

Descriptor that you return from SupportedDiagnostics (http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/DiagnosticAnalyzer.cs,5c085870139ed902) has a HelpLink. if you set it, click will go to that url.
