### ISSUE TITLE
Unused variable warning should not be reported if variable name is underscore

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#15631]
This came up in LDM 11/30/2016.
The compiler won't report unused variable warnings for new kinds of variables (out vars, deconstruction vars, pattern vars) and obviously should not report warnings for discards. The question came up whether the warning should be relaxed for C#6-style variables. That question will need follow-up, but for the case of a local declaration where the local is named underscore, we can remove the warning now to be consistent with discard behavior.

**Comment by jcouv** [comment]
FYI @gafter

**Comment by jcouv** [comment]
@gafter I'm thinking of closing this. 
The warning for un-used variable already has logic to determine if the right-hand-side expression could have side-effects. 
This leaves us with trivial scenarios such as `var _ = 1;` which are not useful as a discard either.

I think it's ok to leave the warning for such cases. Or at least treat the priority as low enough that it can wait til we revisit this kind of warning more generally...

**Comment by gafter** [comment]
@jcouv I have no objection.
