### ISSUE TITLE
Possible change to location of "Type and identifier are both required in a foreach statement"

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#15632]
The parser usually places an error for missing syntax following the preceding syntax (e.g. on the following token). This includes the error

`Type and identifier are both required in a foreach statement`

which is given when you write

`foreach (Something in expr) { }`

This particular error message is currently placed on the `in` token. It has been suggested that this error might be better placed on `Something` rather than `in`.

**Comment by gafter** [comment]
Personally I believe the suggestion would reduce the quality of the diagnostic, but I've filed this issue to track the discussion.

**Comment by gafter** [comment]
I'm planning to close this as "By Design" in a couple of weeks unless I hear some compelling argument for making the proposed change.

**Comment by alrz** [comment]
A similar example would be `int = 1`. Again, the diagnostics is on the `=` token. In that sense, these are consistent with each other. But in case of a `foreach` statement the compiler produces a different diagnostic in addition to the one that says it's expected to see an identifier before `=`. So I think it would make sense if squiggles were on different tokens and do not overlap.

**Comment by gafter** [comment]
> ...in case of a `foreach` statement the compiler produces a different diagnostic in addition to the one that says it's expected to see an identifier before `in`.

Not so. See

https://github.com/dotnet/roslyn/blob/ca5aba04971e99414639ee4aac698cc273975d1b/src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationExpressionTests.cs#L666
https://github.com/dotnet/roslyn/blob/ca5aba04971e99414639ee4aac698cc273975d1b/src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationExpressionTests.cs#L723

**Comment by alrz** [comment]
Well, I was wrong about "in addition to" part. But it's a different diagnostic, right? It's not a lexer error i.e. an unexpected token. It is the `foreach` statement that requires both type and the identifier in *iteration variable location*. So, there is that.
```cs
// Identifier expected; on `=`
int = 1;
// 'C' is a type but is used like a variable; on `C`
C = 1; 
// Identifier expected and CS0230; both on `in`
foreach(int in list) 
// Identifier expected and CS0230; both on `in`
// Also, CS0030 on `foreach`!
foreach(C in list)
```
The last example is interesting. Even `foreach` seems appropriate for `CS0230`, because it is directly related to the loop itself.

**Comment by gafter** [comment]
@alrz We like to keep *syntax* errors local, which is why it is on the `is`.

**Comment by gafter** [comment]
Closing as `By Design`, though this is not intended to close down any future effort at improving these diagnostics.
