### ISSUE TITLE
EE: Calculate members lazily

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#15647]
Calculating the set of type member (fields and properties) for a value in the Locals or Watch window is fairly expensive. But the set is calculated early currently to determine whether to mark the value row as Expandable. Consider delaying calculating the members until the value is expanded, perhaps marking the value Expandable in all cases.

**Comment by cston** [comment]
See https://github.com/dotnet/roslyn/issues/15647.

**Comment by tmat** [comment]
Dup of https://github.com/dotnet/roslyn/issues/32800
