### ISSUE TITLE
CSharpScript.Create does not allow to specify a Previous script

### ISSUE THREAD

**Issue by fuzzycactus** [dotnet/roslyn#15645]
The CSharpScript compiler checks for the `Previous` script submission to compile first; however, the setting of Previous is not exposed - it appears to be only available in the abstract Script constructor.

How does one set it?

**Comment by aelij** [comment]
The previous script is set when you chain scripts using the [`ContinueWith`](http://source.roslyn.io/Microsoft.CodeAnalysis.Scripting/R/28760f869988b06b.html) method. See examples [here](https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples#chain).

**Comment by fuzzycactus** [comment]
ah ok, it's a passive fetch, not active set ... ie "run script B before running this one".  Got it.
