### ISSUE TITLE
Language Feature Status should be updated

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#15654]
The page [Language Feature Status](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md) seems to be out of date, specifically when it comes to branches listed for features:

1. It says that Throw Expr is in its own feature branch, when it was merged into master in https://github.com/dotnet/roslyn/pull/13750.
2. Likewise, it says that Expression-Bodied Everything has its feature branch, but it was merged in https://github.com/dotnet/roslyn/pull/13970.
3. For Source Generation, the link goes to [features/generators](https://github.com/dotnet/roslyn/tree/features/generators), which does not exist, while the text says it's in master, which I'm not sure is correct.

Considering that Throw Expr and Expression-Bodied Everything are merged into master, it's also probably incorrect to say they are both in the Prototyping state.

**Comment by alrz** [comment]
Perhaps, wildcard and deconstruction should be added. Because they are standalone features and do not depend on type switch or tuples.

**Comment by jcouv** [comment]
The Language Feature Status page recently with current information about 7.1 and later plans. We're are going to better keep it up-to-date as prototyping work begins.
