### ISSUE TITLE
Proposal: Allow otherwise unresolvable instant methods to resolve to a static method in the same type

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#15652]
```cs
str.IsNullOrEmpty();
array.Sort();
```
->
```cs
string.IsNullOrEmpty(str);
Array.Sort(array);
```

**Comment by orthoxerox** [comment]
I think you should ask the coreclr team to add these as extension methods instead. I don't think this is a constantly recurring problem that requires a general solution.

**Comment by alrz** [comment]
@orthoxerox 

That would be a breaking change, because currently `using static` doesn't support extension methods. That'd be corefx though.

**Comment by jnm2** [comment]
Part of me likes this but mostly it seems this would lead to confusion. Usually an API should have a single way of doing things.

**Comment by aluanhaddad** [comment]
Extension methods are the right way to take care of this. As much as it would be nice to have certain methods, like `String.IsNullOrWhiteSpace`, available, I would really not want all of them.
```C#
var abc = "abc";
// very nice
if (abc.IsNullOrWhiteSpace())
{
    return;
}
```
```C#
var abc = "abc";
// terrible!
abc.Format("{0}{1}", "def");```
