### ISSUE TITLE
RenamedSpansTracker location

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/roslyn#15664]
In what NuGet package `RenamedSpansTracker` is located? https://github.com/dotnet/roslyn/blob/84bc7eea2e05e9d9d7e1b53c2a107c0ac9857a72/src/Workspaces/Core/Portable/Rename/ConflictEngine/RenamedSpansTracker.cs I'm trying to implement Inline Rename service for F# and I think I should use this class.

**Comment by Pilchie** [comment]
It should be in `Microsoft.CodeAnalysis.Workspaces.Common`.
