### ISSUE TITLE
Debug symbol not loaded when debugging VisualStudioSetup

### ISSUE THREAD

**Issue by zanqi** [dotnet/roslyn#15668]
**Version Used**: Last pulled on Dec 3rd master branch. 

**Steps to Reproduce**:

1. Select VisualStudioSetup as startup project and press F5
2. Set a breakpoint in Roslyn's code

**Expected Behavior**:
Breakpoint can be created and hit.

**Actual Behavior**:
Symbol not loaded:

![image](https://cloud.githubusercontent.com/assets/2538192/20870538/24b34408-bac5-11e6-9269-1d0ee1af2fae.png)

Error when adding the pdb manually:

![image](https://cloud.githubusercontent.com/assets/2538192/20870566/97f003c0-bac5-11e6-98a9-c705d649dbad.png)

**Comment by jasonmalinowski** [comment]
@zanqi: are you still able to reproduce this?

**Comment by zanqi** [comment]
Tested ok in VS2017. Closing this
