### ISSUE TITLE
Add methods for getting fields, properties, methods and events to the ITypeSymbol interface

### ISSUE THREAD

**Issue by denis-tsv** [dotnet/roslyn#1566]
Please, add methods for getting fields, properties, methods and events to the ITypeSymbol interface.

ImmutableArray<IFieldSymbol> GetFields();
ImmutableArray<IPropertySymbol> GetProperties();
ImmutableArray<IEventSymbol> GetEvents();
ImmutableArray<IMethodSymbol> GetMethods();

These methods are more useful than single GetMembers method.
For example, it is easier to call GetProperties() method, then get all members and after that find properties. Without GetProperties() method I need to write something like this to get all properties:
ITypeSymbol typeSymbol = ...;
var properties = typeSymbol.GetMembers()
.Where(m => m.Kind == SymbolKind.Property).Cast<IPropertySymbol>();

**Comment by gafter** [comment]
These would be one-line extension members.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal. 

In general though, helpers which really are nothing more than a thin wrapper over existing functionality are not likely to be done.
