### ISSUE TITLE
Null propagation operator returns "null" for default value of non-nullable generic type

### ISSUE THREAD

**Issue by KaychTech** [dotnet/roslyn#15670]
.NET version:  4.6.01586

Chaining the null propagation operator on a default value for a non-nullable type returns null instead of the expected value.  For instance, when 'T' represents an int, null is returned in the following instead of "0".

```
public class Test<T>
{ 
    public string Run()
    {
        return default(T)?.ToString();
    }
}

var t = new Test<int>();

Console.WriteLine(t.Run());    // value is null
```

However, when first assigning the default value to a variable and then using the null propagation operator, the expected result is returned.

```
public class Test2<T>
{
    public string Run()
    {
        var value = default(T);

        return value?.ToString();
    }
}

var t2 = new Test2<int>();

Console.WriteLine(t2.Run());    // value is "0"
```

**Comment by CyrusNajmabadi** [comment]
IL produced for:

```c#
    public string Run()
    {
        return default(T)?.ToString();
    }
```

is:

```
        IL_0000: nop
	IL_0001: ldnull
	IL_0002: stloc.0
	IL_0003: br.s IL_0005

	IL_0005: ldloc.0
	IL_0006: ret
```

Or, essentially "return null".  Looks like the compiler 'optimized' away 'default(T)?...." directly into 'null'.  That optimization seems like it should only be done if T is known to be a reference type.

**Comment by CyrusNajmabadi** [comment]
Bug may be here:

https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ConditionalAccess.cs#L34

```c#
        internal BoundExpression RewriteConditionalAccess(BoundConditionalAccess node, bool used)
        {
            Debug.Assert(!_inExpressionLambda);

            var loweredReceiver = this.VisitExpression(node.Receiver);
            var receiverType = loweredReceiver.Type;

            // Check trivial case
            if (loweredReceiver.IsDefaultValue())
            {
                return _factory.Default(node.Type);
            }
```

**Comment by gafter** [comment]
I thought it was supposed to be an error to use the `?. operator on  a value not known to be nullable.

**Comment by CyrusNajmabadi** [comment]
@gafter who is the best to handle such questions?  I assume there are interesting back compat concerns here.

**Comment by gafter** [comment]
@MadsTorgersen Is the best person to clarify the intended specified behavior.

**Comment by KaychTech** [comment]
I believe it is (and should be) valid to check unconstrained generic types for null; otherwise, how would you handle the above test case of calling '.ToString()' without catching a NullReferenceException?  With or without the '?.' operator, you'd be checking for null against a potentially non-nullable type (which is normally not a valid operation/statement).

i.e. Something like the following would need to be used, instead:

```
var value = default(T);

return value == null ? null : value.ToString();
```

**Comment by CyrusNajmabadi** [comment]
@gafter Can i give this to a compiler dev to take on?  I don't really have the spare cycles to do this fully.  I just wanted to see if i could figure out how to address bugs in the emitter.  Thanks!

**Comment by gafter** [comment]
@CyrusNajmabadi I'm guessing you've touched base with @jaredpar to hand this off.
