### ISSUE TITLE
Preview pane for code style options should be resizable.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#15685]
In the screenshot below, the preview pane on the bottom cannot be resized and always takes up 50% of the window.  This behavior is probably fine for the initial showing of the window, but I'd like to be able to resize it (e.g., insert a grid size grip between the top and bottom panels).

![image](https://cloud.githubusercontent.com/assets/926281/20903235/67a8943c-baef-11e6-9394-7a7f8d28641c.png)

**Comment by Pilchie** [comment]
Re-opening to track the formatting pages.

**Comment by reaction1989** [comment]
@Pilchie Is here something left i can help with?

**Comment by Pilchie** [comment]
@reaction1989 Sure!  The pages under CodeStyle/Formatting have a similar split, but still aren't separately resizable:

They start at http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.Implementation/Options/OptionPreviewControl.xaml,fabe6f0788435e69 I think.

**Comment by alrz** [comment]
I can already do this though

![resize](https://user-images.githubusercontent.com/3105979/33169161-d4556202-d058-11e7-8e9b-91fede257511.png)

**Comment by Pilchie** [comment]
That's the CodeStyle\General page, not the formatting pages underneath there (Spacing, Wrapping, etc).

**Comment by CyrusNajmabadi** [comment]
THe entire tools|option pane can be enlarged if someone wants to see more.  i think that's sufficient here.
