### ISSUE TITLE
Change type of AttributeData.NamedArguments property

### ISSUE THREAD

**Issue by denis-tsv** [dotnet/roslyn#1568]
Now type of AttributeData.NamedArguments property is ImmutableArray<KeyValuePair<string, TypedConstant>> so it is not useful to find argument by name.
For example, I need to write something like this to find argument:
AttributeData attribute = ...;
var argument = attribute.NamedArguments.FirstOrDefault(item => item.Key == "ArgumentName");
if (!argument.Equals(default(KeyValuePair<string, TypedConstant>)))
{
    // do something
}

But I'd like to write something like this:
if (attribute.NamedArguments.Contains("ArgumentName"))
{
    var argument = attribute.NamedArguments["ArgumentName"];
}
or
var argument = attribute.NamedArguments.GetValueOrDefault("ArgumentName");

Maybe it is better to replace ImmutableArray by ImmutableDictionary or some custom collection?
And replace KeyValuePair by some reference type to ckeck founded item on null, but not compare with default(KeyValuePair<>).

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  As this could be done trivially with an extension it is probably not likely to be added though.
