### ISSUE TITLE
RC insider VSIX can dramatically increase build times?

### ISSUE THREAD

**Issue by qwertie** [dotnet/roslyn#15696]
**Version Used**: Visual Studio 2015 Update 3 + RC insider VSIX

**Steps to Reproduce**:

While trying to build Roslyn, I installed VS 2015 Preview 4 and RC insider VSIX as the [installation instructions](https://github.com/dotnet/roslyn/wiki/Building-Testing-and-Debugging) suggested. After that I was [not able to build Roslyn](https://github.com/dotnet/roslyn/issues/15667), but that's a separate issue. Around the same time, I noticed [my projects were building very slowly](http://stackoverflow.com/questions/40953934/vs-2015-suddenly-builds-very-slowly/40993332#40993332). With help online I eventually noticed that my compiler was running from inside the Extensions\14.0 folder, making me think "RC Insider" was the cause. I think that's true because [uninstalling RC insider fixed the problem](http://stackoverflow.com/a/40993332/22820).

**Expected Behavior**: Normal speed build.

**Actual Behavior**: 8x slower build than normal.

How could RC insider cause this issue?

I would request that the Roslyn build instructions be updated to inform users that they are **globally** replacing the C# compiler used by Visual Studio, so that when all their builds start acting up, they have some hint what the cause might be.

Also, the build instructions say that following the RC insider uninstall instructions will also delete any other VS extensions that the user might have - which is horrible. Is there a more precise way to uninstall it? (On the plus side, Visual Studio reports that some of my extensions are still installed.)

**Comment by jmarolf** [comment]
@qwertie I assume the slowdown is because the VSIX binaries are not ngen'd so you are seeing a lot of extra jit time.  I wouldn't have expected 8x slowdown though

**Comment by jasonmalinowski** [comment]
@agocke I think you might have investigated an issue like this before?

**Comment by agocke** [comment]
@qwertie As you mentioned in your post, the compiler server is not enabled for the VSIX (that's what "Using shared compilation" indicates). Without either NGEN or the compiler server builds can be very slow.

@jaredpar We recently enabled the compiler server for the NuGet package by default -- perhaps we should consider the same for the VSIX compiler extension?

@jasonmalinowski I'll let you handle the rest of the notes on VSIX installation, or changing the guide to recommend 2017 RC if you prefer that.

**Comment by jaredpar** [comment]
@agocke my expectation is that it would be on by default.  Are we specifically doing the opposite?
