### ISSUE TITLE
Question:  Local Functions and Capturing Scope

### ISSUE THREAD

**Issue by HaloFour** [dotnet/roslyn#15699]
**Version Used**: 

[http://tryroslyn.azurewebsites.net/](http://tryroslyn.azurewebsites.net/)
0694d5ccc05b7e1cc37c82a1c15c8f9fc23e3775 at 29 Oct 2016

Admittedly a little old but I doubt that the implementation has changed.

**Steps to Reproduce**:

```cs
public void M() {
    int x = 2;
    int y = 3;
    int z = 4;

    int local() => x + y;
    Func<int> del = () => z;

    int result1 = local();
    int result2 = del();
}
```

**Actual Behavior**:

I noticed that if a local function captures any of the locals of its parent method and that parent method also declares a delegate which captures any locals that the code generated uses an allocated display class rather than the more efficient display struct.  This is true even if none of the captured locals overlap.

Is this expected behavior?  If so it's probably worth noting somewhere so that people using local functions for performance purposes don't accidentally cause the compiler to convert to the less efficient implementation.

**Comment by svick** [comment]
Something similar has been asked for in https://github.com/dotnet/roslyn/issues/7224, except for the case where both functions are lambdas.

That proposal has been rejected, since it would mean allocating more objects. That does not apply here, since struct closures do not cause allocations.

So, I don't see anything that would prevent this optimization.

**Comment by HaloFour** [comment]
@svick 

I guess you can argue that once a display class needs to be allocated that there is little point in bothering with the display struct since the cost has already been sunk into the allocation.  The difference between calling the instance method on the display class vs. calling the static method with the display struct ref is probably negligible.

**Comment by svick** [comment]
Yeah, it would not decrease the number of allocations. But it would decrease the size of allocations, which I believe is more important. And it would potentially decrease the lifetime of some variables (e.g. if the delegate was returned from the function, but the local function wasn't), which is important for reference type variables.

So I still think this would be a useful optimization.

**Comment by agocke** [comment]
This is by-design for now. On my backlog is a bug to rewrite the lowering pass for closures entirely: #14796.

There are a bunch of things on the table for the rewrite, including some discussion on incorporating escape analysis to do even smarter capturing.

**Comment by agocke** [comment]
I'm going to close this as a dup.
