### ISSUE TITLE
RenameSymbolAsync misses indirectly accessed private fields 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#157]
Consider the following code:

``` csharp
class B
{
  internal C Owner { get {... } }
}

class C
{
   private int id;

   void M(B b) 
   {
      Console.WriteLine(b.Owner.id);
   }
}
```

If `Renamer.RenameSymbol` is run on the field`C.id` the rename operation will not update the reference in the expression `b.Owner.id`.

**Comment by dpoeschl** [comment]
@jaredpar Rename Tracking works in this scenario for me, and Rename Tracking [uses the RenameSymbolAsync API](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.RenameTrackingCommitter.cs#L106
) directly, so I'm confused about why this would fail. 
Are you seeing this in Rename Tracking / Inline Rename, or just through the API? Can you confirm that you see this failure on this simple case, or was this reduced from a larger failing case?

**Comment by jaredpar** [comment]
@dpoeschl it was reduced from a larger case.  Essentially the code formatter was failing to rename this pattern when run against the Roslyn sources.

**Comment by jaredpar** [comment]
@dpoeschl another case I just found: rename doesn't appear to update symbols that appear as a part of an interpolated string.

**Comment by dpoeschl** [comment]
As discussed offline, rename now works correctly on interpolated strings. 

Let me know if you're able to find a repro for the indirectly accessed private field case.

**Comment by jaredpar** [comment]
Going to close the issue for now.  As we discussed the most likely cause of these problems is the older bits I am using.  When I upgrade to a newer drop I'll reopen if these issues still exist.
