### ISSUE TITLE
Multiple "...Provider encountered an error and has been disabled." errors

### ISSUE THREAD

**Issue by kakins** [dotnet/roslyn#15705]
**Version Used**: 
VS 2015, latest update as of 12/6/2016.

**Steps to Reproduce**:

1.  This seems to happen randomly, however I notice whenever I try to use refactoring shortcuts (CTRL + .) or highlight some code where refactoring may be available.  

**Expected Behavior**:
No errors, refactoring context menus should appear.

**Actual Behavior**:
Various refactoring providers are throwing a "...Provider encountered an error and has been disabled."

Do we know if this fix has been pushed to a recent update? I'm experiencing this issue, but with multiple "provider" errors, such as SimplifyTypeNamesCodeFixProvider. I have tried everything from disabling ReSharper to reverting to VS settings from a month ago where everything was working fine.

**Comment by kakins** [comment]
One scenario where I see this problem occurring:  selecting some text inside a method produces the 'ExtractMethodCodeRefactoringProvider' error.  Clicking the 'Enable' button on the error popup, with the text still selected causes the error to constantly reappear.  If I deselect the text and click enable, the error does not appear, however will do so if I select the text again.

![image](https://cloud.githubusercontent.com/assets/14915247/21195057/bca78830-c1f7-11e6-8c54-10287f480d92.png)

**Comment by Pilchie** [comment]
Can you run devenv with the /log argument, and then send us `%AppData%\Microsoft\VisualStudio\14.0\ActivityLog.xml`?

**Comment by kakins** [comment]
Ahh, I didn't realize that ActivityLog.xml logged these types of errors.  Great.  Here is the log, it looks like there's a common "Specified cast is not valid" exception being thrown for, at least so far, both ExtractMethodCodeRefactoringProvider & InlineTemporaryCodeRefactoringProvider (see errors 798, 852).

I attached the log as a .txt file, unless you'd rather me paste it in the comment here.
[ActivityLog.txt](https://github.com/dotnet/roslyn/files/652743/ActivityLog.txt)

**Comment by Pilchie** [comment]
@kakins  - are you signed in to VS and roaming your settings?

It looks like you have a bad option persisted somewhere.  We fixed the code to be more resilient here in VS 2017.

In the meantime, you could try going to:  Tools\Options\Text Editor\C#\Code Style and changing the value of the options for use of predefined type names versus framework type names.

Alternatively, going to Tools\Import and Export Settings and resetting all your settings might fix this.

**Comment by kakins** [comment]
Very interesting.  So trying to select that Code Style item in the Options dialog crashes Visual Studio.  I hate to lose any settings, but it looks like I just need to reset everything.

**Comment by Pilchie** [comment]
If you wanted to be more selective you could try copying `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Profiles\CSharp.vssettings` and then editing it to include only the `CSharp-Specific` settings and then import that file.

**Comment by kakins** [comment]
I went ahead and reset all settings, wasn't too big of a problem just have to reset some key bindings.  Haven't seen the error since but will report back if I do.  Thanks!

**Comment by Pilchie** [comment]
Thanks for the confirmation!

**Comment by KrisVandermotten** [comment]
It seems I had the same problem (or very similar) problem. Resetting the settings solved it.

In my case it was probably caused by the fact that I had just installed Visual Studio 2017 RC on another box, and changed some code style settings there. I suppose those might have roamed into my Visual Studio 2015 installation, and corrupted it.

**Comment by Pilchie** [comment]
Thanks - we're tracking this in #13556 - I think we need to change the name of some options that have different types.
