### ISSUE TITLE
BaseMethodDeclarationSyntax abstraction should be extended

### ISSUE THREAD

**Issue by JamesFaix** [dotnet/roslyn#15700]
The abstract class `Microsoft.CodeAnalysis.CSharp.Syntax.BaseMethodDeclarationSyntax` serves as the base class for all "method-like" syntax constructs: 
 - `MethodDeclarationSyntax`
 - `ConstructorDeclarationSyntax`
 - `DestructorDeclarationSyntax`
 - `OperatorDeclarationSyntax`
 - `ConversionOperatorDeclarationSyntax`

This base class is highly useful, but there are also many non-virtual members of the derived classes that are shared.  Many of these have the derived type as their return type, and so they would need to be abstracted by a generic interface or abstract class.

This is the common interface implemented by all the derived types, excluding abstract members from `BaseMethodDeclarationSyntax`.
```
interface IBaseMethodDeclarationSyntax<TNode> 
    where TNode: BaseMethodDeclarationSyntax 
{
    TNode AddAttributeLists(params AttributeListSyntax[] items);
    TNode AddBodyStatements(params StatementSyntax[] items);
    TNode AddModifiers(params SyntaxToken[] items);
    TNode AddParameterListParameters(params ParameterSyntax[] items);
    TNode WithAttributeLists(SyntaxList<AttributeListSyntax> attributeLists);
    TNode WithBody(BlockSyntax body);
    TNode WithParameterList(ParameterListSyntax parameterList);
    TNode WithSemicolonToken(SyntaxToken semicolonToken);
}
```
If expression-bodied constructors and destructors make the final cut for C#7, these members can also be added to the list:
```
ArrowExpressionClauseSyntax ExpressionBody { get; }
TNode WithExpressionBody(ArrowExpressionClauseSyntax expressionBody);
```
-------
There are also several members that are common to some of the derived types, or have close analogs between the derived types.  These may be convenient to conform to a single abstraction, but it may also be semantically muddy.

Examples:
```
TypeSyntax ReturnType { get; }
TNode WithReturnType(TypeSyntax returnType);
```
The `ReturnType` property and corresponding `With` method are found on `MethodDeclarationSyntax`, and `OperatorDeclarationSyntax`, and the `Type` property of `ConversionOperatorDeclarationSyntax` and its corresponding 'With' method are very much analogous.  These members could possibly be implemented on the base class or interface, with constructors and destructors returning `null` for the property, and throwing `NotSupportedException` for the `With` method.

Another stretch might be to make some of these properties more unified:
```
MethodDeclarationSyntax.Identifier
ConstructorDeclarationSyntax.Identifier
DestructorDeclarationSyntax.Identifier
OperatorDeclarationSyntax.OperatorToken
DestructorDeclarationSyntax.TildeToken
```

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
