### ISSUE TITLE
Deadlock: SaveEventsService performs COM service queries during MEF composition

### ISSUE THREAD

**Issue by jviau** [dotnet/roslyn#15713]
[SaveEventsService](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/SaveEventsService.cs) performs COM service queries in its constructor. This results in a deadlock when the main thread waits on a background task that eventually causes this class to be composed via MEF.

This hang can occur in DotNet Core projects when the property pages are being created.

**Comment by jasonmalinowski** [comment]
This is currently being fixed by #14354.

**Comment by jviau** [comment]
Awesome, thanks!
