### ISSUE TITLE
Simplify smart indentation implementation.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15711]
Right now our indentation implementation is quite complex.  We support both listening to ISmartIndent as well as listening directly to ```<enter>```.  The latter is so that we can control what happens when the user hits enter in the middle of code and if there's whitespace to the right of the cursor.   In that event we want to indent *and* delete the whitespace after the cursor.

However, the editor is changing the default behavior of ISmartIndent to do that automatically.  When enter is hit, they'll remove all whitespace after the cursor and place any subsequent text at the indent column we provide.

Once this goes in, we can remove our indent ```<enter>``` handler entirely, and we can just use ISmartIndent.  This will clean up a lot of code (especially as those two types know about each other and channel data to and from each other).

**Comment by AmadeusW** [comment]
New editor behavior will be available in 26014.04

**Comment by CyrusNajmabadi** [comment]
@jinujoseph This should not be assigned to me.  Thanks!

**Comment by CyrusNajmabadi** [comment]
This was done in https://github.com/dotnet/roslyn/pull/33989 and https://github.com/dotnet/roslyn/pull/33983 and https://github.com/dotnet/roslyn/pull/33978
