### ISSUE TITLE
Convert between nullable and non-nullable types

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [dotnet/roslyn#15724]
I'd like to easily and concisely convert an `int` to an `int?` with the following syntax:

```
var value = 1;
var nullableValue = value?;
```

Conversely, I'd like to be able to convert a nullable `int` to a non-nullable `int` with the following syntax:

```
var value = 1?;
var nonNullableValue = value!;
```

This would be very handy in handling nullable DateTimes, where the expressions can get hairy - having lots of extra `.Value`s only helps to lessen clarity. And not using Nullable `DateTime`s makes me have to handle `DateTime.MinValue`, wow.

```
var myEvent = ... // something I got from DB, or a form

// some model validation

var myString = $"{myEvent.Start!.ToString("d MMMM yyyy")} {myEvent.Start!.ToString("HH:mm")} - {myEvent.End!.ToString("HH:mm")}
```

This would translate to just casting (`((DateTime?)x)`) and accessing `x.Value`, ie not so complex and somewhat in the lines of what steps C# is taking otherwise.

**Comment by svick** [comment]
In your specific case, one workaround would be to use `?.`. Since it seems you already know that the values are not `null`, there should be no difference between `.Value.` and `?.`:

```c#
var myString = $"{myEvent.Start?.ToString("d MMMM yyyy")} {myEvent.Start?.ToString("HH:mm")} - {myEvent.End?.ToString("HH:mm")}";
```

You can also shorten your code and avoid all nullable issues by specifying the format strings directly in the string interpolation, instead of using `ToString()`:

```c#
var myString = $"{myEvent.Start:d MMMM yyyy} {myEvent.Start:HH:mm} - {myEvent.End:HH:mm}";
```

**Comment by bjorn-ali-goransson** [comment]
That's a new one for me. Nice!

Then, my suggestion would be a breaking change as it would repurpose `?` to the opposite.

I guess I'll close this one.

**Comment by IEvangelist** [comment]
Breaking change and repurpose... two very scary terms, let's avoid this one for now.
