### ISSUE TITLE
Access to document in DiagnosticAnalyzer

### ISSUE THREAD

**Issue by doubret** [dotnet/roslyn#15730]
I'm writing a diagnostic analyzer / code fix provider and i would like to know the document when my analyzer in invoked.
Is this possible to know the document concerned by the analysis ?

Thanks

**Comment by srivatsn** [comment]
From the analyzer, if you register a syntax action, you can look at the tree and get the file path from the SyntaxTree. From a CodeFix, the context object will give you the document.
