### ISSUE TITLE
Incorrect suggestion to use 'var'.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15736]
![image](https://cloud.githubusercontent.com/assets/4564579/20989874/37cff744-bc8b-11e6-82f6-edc557f8ff53.png)

In this case, I'm foreaching over an InlineCollection, but i'm stating that the values will be of type "Run".  This is effectively doing a ```.Cast<Run>()``` on the expression i'm foreaching over.  If this gets changes to 'var', then the type will be 'Inline', not 'Run'.  And if that happens, i won't be able to call "run.Text" below (as .Text is not defined on 'Inline').

**Comment by CyrusNajmabadi** [comment]
tagging @dpoeschl

**Comment by dpoeschl** [comment]
Good find!

**Comment by Pilchie** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/14052.
