### ISSUE TITLE
"Use null propagation" code fix is incorrect

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#15737]
**Version Used**: 

Dev15 RC2 26006

**Steps to Reproduce**:

```C#
class C
{
    public C Next;
}

class Program
{
    static void Main(string[] args)
    {
        C c = new C();
        C d = new C();
        var x = c != null ? c.Next : d;
    }
}
```

**Expected Behavior**:

No suggestion is offered since the code can't be simplified using ```?.``` operator

**Actual Behavior**:
![image](https://cloud.githubusercontent.com/assets/41759/20990200/7f0ff482-bc8c-11e6-9f67-326446656c11.png)

Note that even if the code fix offered 

```C#
var x = c?.Next ?? d;
```

it's not correct as the value of ```Next``` may be ```null```.

**Comment by CyrusNajmabadi** [comment]
This has been fixed.  Will find the PR when i get a chance.

**Comment by controlflow** [comment]
Well, `c?.Next ?? d` is not correct transformation either. The original code can evaluate to `null` when `c.Next` is `null`.

**Comment by CyrusNajmabadi** [comment]
Yes.  As stated, this has been fixed.  We no longer offer the fix here.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/15511
