### ISSUE TITLE
Spell-check should never spell-check 'var'.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15733]
![image](https://cloud.githubusercontent.com/assets/4564579/20989720/9cacaeba-bc8a-11e6-95ff-adc0c5819a44.png)

**Comment by Pilchie** [comment]
Does this affect only `var`, or other keywords too?

**Comment by CyrusNajmabadi** [comment]
Probably 'dynamic' as well.
