### ISSUE TITLE
Incorrect precedence of `is` operator

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#15734]
```C#
class Program
{
    static void Main(string[] args)
    {
        if (args is string[] || args.Length > 0) // ok
        {
        }

        if (args is null || args.Length > 0) // error
        {
        }
    }
}
```

**Actual result**

```Operator '||' cannot be applied to operands of type '<null>' and 'bool'```

**Expected result**

No error.

**Comment by gafter** [comment]
A prototype fix for this is at https://github.com/gafter/roslyn/tree/pattern-precedence (last commit only). I'll shepherd it through the PR process when I'm back near the office.
