### ISSUE TITLE
[Flaky Test] CSharpWinForms.xml

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15743]
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_prtest/122/console

..

 Waiting for Roslyn features SolutionCrawler: 12/9/2016 11:57:17 PM
16:02:30 Waiting for Roslyn features ErrorList: 12/9/2016 11:57:22 PM
16:02:30 Finished waiting for Roslyn features SolutionCrawler and ErrorList: 12/9/2016 11:57:22 PM
16:02:30 Waiting for error list: 12/9/2016 11:57:24 PM
16:02:30 Finished waiting for error list: 12/9/2016 11:57:26 PM
16:02:30 	Executing action [12/9/2016 11:57:28 PM] OpenFile
16:02:30 DEBUG: executed DTE command File.OpenFile.
16:02:30 DEBUG: start polling for code window
16:02:30 DEBUG: polling complete
16:02:30 	Executing action [12/9/2016 11:57:28 PM] VerifyEditorContainsText
16:02:30 	Executing action [12/9/2016 11:57:28 PM] OpenFile
16:02:30 DEBUG: executed DTE command File.OpenFile.
16:02:30 DEBUG: start polling for code window
16:02:30 DEBUG: polling complete
16:02:30 	Executing action [12/9/2016 11:57:28 PM] VerifyEditorContainsText
16:02:30 --------------------------------
16:02:30 System.Exception: Actual and expected items don't match:
16:02:30 Expected: public partial class Form1 : Form
16:02:30     {
16:02:30         public Form1()
16:02:30         {
16:02:30             InitializeComponent();
16:02:30         }
16:02:30 
16:02:30         private void ExecuteWhenButtonClicked(object sender, EventArgs e)
16:02:30         {
16:02:30 
16:02:30         }
16:02:30     }
16:02:30 Actual: using System;
16:02:30 using System.Collections.Generic;
16:02:30 using System.ComponentModel;
16:02:30 using System.Data;
16:02:30 using System.Drawing;
16:02:30 using System.Linq;
16:02:30 using System.Text;
16:02:30 using System.Threading.Tasks;
16:02:30 using System.Windows.Forms;
16:02:30 
16:02:30 namespace TestProj
16:02:30 {
16:02:30     public partial class Form1: Form
16:02:30     {
16:02:30         public Form1()
16:02:30         {
16:02:30             InitializeComponent();
16:02:30         }
16:02:30 
16:02:30         private void ExecuteWhenButtonClicked(object sender, EventArgs e)
16:02:30         {
16:02:30 
16:02:30         }
16:02:30     }
16:02:30 }
16:02:30 
16:02:30 
16:02:30    at Roslyn.VSHosting.Test.Utilities.CompareAndThrowIfNotEqual[TItem](TItem expected, TItem actual) in d:\j\workspace\windows_vsi_p---5e702c54\Closed\Hosting\Test\Actions\VisualStudio\Utilities\Utilities.cs:line 15
16:02:30    at Roslyn.VSHosting.Test.VerifyEditorContainsTextAction.<>c.<Execute>b__4_0(Object[] args) in d:\j\workspace\windows_vsi_p---5e702c54\Closed\Hosting\Test\Actions\VisualStudio\VerifyEditorContainsTextAction.cs:line 23
16:02:30    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments)

**Comment by jmarolf** [comment]
duping against https://github.com/dotnet/roslyn/issues/15848
