### ISSUE TITLE
[Failing Test] BasicVenus.xml

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15744]
when manually ran, all run failed

..

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1/289/console

..

  Dumping log file d:\j\workspace\windows_vsi_p13cea124f\Open\Binaries\Release\Exes\EditorTestApp\VSIntegrationTestLogs\BasicVenus.txt
22:23:22 Test: BasicVenus started: 12/7/2016 10:15:26 PM
22:23:22 	Executing action [12/7/2016 10:15:26 PM] StartTarget
22:23:22 Begin Waiting for Apex Communication
22:23:22 	Executing action [12/7/2016 10:15:26 PM] SetToolsOption
22:23:22 Previous option value: TextEditor > HTML > InsertTabs = False
22:23:22 Setting option: TextEditor > HTML > InsertTabs = false
22:23:22 	Executing action [12/7/2016 10:15:26 PM] SetFeatureOption
22:23:22 	Executing action [12/7/2016 10:15:26 PM] AddProject
22:23:22 	Executing action [12/7/2016 10:15:27 PM] AddItem
22:23:22  Scenario: Tab completing an event inserts Event Handler
22:23:22 	Executing action [12/7/2016 10:15:28 PM] OpenFile
22:23:22 DEBUG: executed DTE command File.OpenFile.
22:23:22 DEBUG: start polling for code window
22:23:22 DEBUG: polling complete
22:23:22 	Executing action [12/7/2016 10:15:28 PM] PlaceCursor
22:23:22 	Executing action [12/7/2016 10:15:28 PM] InsertText
22:23:22 	Executing action [12/7/2016 10:15:28 PM] PlaceCursor
22:23:22 	Executing action [12/7/2016 10:15:28 PM] Venus
22:23:22 	Executing action [12/7/2016 10:15:32 PM] WaitForWorkspace
22:23:22 	Executing action [12/7/2016 10:15:32 PM] SendKeys
22:23:22 	Executing action [12/7/2016 10:15:34 PM] OpenFile
22:23:22 DEBUG: executed DTE command File.OpenFile.
22:23:22 DEBUG: start polling for code window
22:23:22 DEBUG: polling complete
22:23:22 	Executing action [12/7/2016 10:15:34 PM] VerifyEditorContainsText
22:23:22 --------------------------------
22:23:22 System.Exception: Actual and expected items don't match:
22:23:22 Expected:     Protected Sub Button1_Click(sender As Object, e As EventArgs)
22:23:22 
22:23:22     End Sub
22:23:22 Actual: 
22:23:22 Partial Class _Default
22:23:22     Inherits System.Web.UI.Page
22:23:22 
22:23:22 End Class

**Comment by Pilchie** [comment]
Tracked by #15844.
