### ISSUE TITLE
[Failing Test] BasicWinForms.xml

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15747]
when manually ran, all runs failed.

...

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1/289/console

...

 Dumping log file d:\j\workspace\windows_vsi_p13cea124f\Open\Binaries\Release\Exes\EditorTestApp\VSIntegrationTestLogs\BasicWinForms.txt
22:23:22 Test: BasicWinForms started: 12/7/2016 10:19:47 PM
22:23:22 	Executing action [12/7/2016 10:19:47 PM] StartTarget
22:23:22 Begin Waiting for Apex Communication
22:23:22  Scenario: Test My IntelliSense
22:23:22 	Executing action [12/7/2016 10:19:48 PM] AddProject
22:23:22 	Executing action [12/7/2016 10:19:49 PM] OpenFile
22:23:22 DEBUG: executed DTE command File.OpenFile.
22:23:22 DEBUG: start polling for code window
22:23:22 DEBUG: polling complete
22:23:22 	Executing action [12/7/2016 10:19:49 PM] SetEditorText
22:23:22 	Executing action [12/7/2016 10:19:50 PM] PlaceCursor
22:23:22 	Executing action [12/7/2016 10:19:50 PM] SendKeys
22:23:22 	Executing action [12/7/2016 10:19:52 PM] VerifyCompletionList
22:23:22 --------------------------------
22:23:22 System.Exception: The following expected item(s) not found:
22:23:22 Application
22:23:22 Computer
22:23:22 Forms
22:23:22 MySettings
22:23:22 Resources
22:23:22 Settings
22:23:22 User
22:23:22 WebServices
22:23:22 
22:23:22    at Roslyn.VSHosting.Test.Utilities.ThrowIfExpectedItemNotFound[TCollection](IEnumerable`1 actual, IEnumerable`1 expected) in d:\j\workspace\windows_vsi_p13cea124f\Closed\Hosting\Test\Actions\VisualStudio\Utilities\Utilities.cs:line 39
22:23:22    at Roslyn.VSHosting.Test.VerifyCompletionListAction.<>c.<Execute>b__28_0(Object[] args) in d:\j\workspace\windows_vsi_p13cea124f\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\VerifyCompletionListAction.cs:line 121
22:23:22    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments)
22:23:22 ================================

**Comment by jmarolf** [comment]
duping against https://github.com/dotnet/roslyn/issues/15848
