### ISSUE TITLE
Expression bodied lambda body is not instrumented

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#15749]
**Version Used**: 

Dev15 RC2 26006.2

**Steps to Reproduce**:

Create a unit test project like so:

```C#
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;

public class C
{
    public void M1()
    {
        L1();
        void L1()
        {
            var f = new Func<int>(
                () => 1
            );

            f();
        }
    }
}

[TestClass]
public class UnitTest1
{
    [TestMethod]
    public void TestMethod1()
    {
        new C().M1();
    }
}
```

**Expected Behavior**:

The line with break point is marked as covered.

**Actual Behavior**:

![image](https://cloud.githubusercontent.com/assets/41759/20992457/eb9ee570-bc98-11e6-9bd3-151b820eac6c.png)

**Comment by JohnHamby** [comment]
Resolved by #15815 .
