### ISSUE TITLE
Convert to interpolated string refactoring should "fail" on bad string.format

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#15758]
**Originally filed [here](https://developercommunity.visualstudio.com/content/problem/1876/convert-to-interpolated-string-refactoring-should.html)**

**Steps to Reproduce**:

Given 
```C#
String.Format("asdf {1} asdf", x.y);
```
Invoke refactoring to convert to interpolated string

**Expected Behavior**:

This creates a silent fail at runtime, about the worst. 
Either 
- don't offer the refactoring (which returns to the problem that refactorings that almost work can't say why they don't) or 
- just don't do the refactoring, or do it in such a way that 
- do it in a way that is so stupid someone might see it `$"asdf {string.format("this was going to blowup at runtime")}"` (don't really do that)
- if you must do it, insert a comment
```C#
// The code used for the interpolated string refactor was flawed, this probably doesn't do what you want("[give previous code")
$"asdf {1} asdf"
```
Refactorings shouldn't change the run time performance in a fundamental way - even fixing a runtime exception

**Actual Behavior**:
```C#
$"asdf {1} asdf"
```

**Comment by Pilchie** [comment]
We should put a conflict marker around the `x.y` and some explanatory text in the preview, the same way we do for inline temporary variable, in examples like:
```C#
int x = 3;
x = 4;
```

**Comment by AdamSpeight2008** [comment]
@Pilchie @jmarolf @kuhlenh I've already analyser that can do most of this, but it needs to be update to support the newer version of VS. `String.Format Diagnostics` I've been slowly working on new implementation.

**Comment by CyrusNajmabadi** [comment]
Unlikely to do anything here given lack of customer feedback.  Finding and reporting issues with code is the space of analyzers.
