### ISSUE TITLE
Breakpoints do not get hit after building Roslyn.sln and hitting F5

### ISSUE THREAD

**Issue by tonkymm** [dotnet/roslyn#15752]
Hi,
I'm trying to debug Roslyn.sln, but I can't seem to hit any break points. I get the message below after setting Roslyn as startup project and hitting F5 . Visual Studio gets launched but cannot hit any breakpoints. 

I followed the instructions from https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md .
 
![image](https://cloud.githubusercontent.com/assets/19374925/20997076/2757386a-bcb7-11e6-9415-34683c5c60a6.png)

**Version Used**: 
Latest versions. 
1. Cloned from https://github.com/dotnet/roslyn.git
2. Microsoft Visual Studio Community 2015 with Update 3

**Steps to Reproduce**:

1. Open "Developer Command Prompt for VS2015"
2. cd roslyn 
3. git clone https://github.com/dotnet/roslyn.git
4. Restore.cmd
5. msbuild /v:m /m Roslyn.sln
6. Open roslyn.sln with Visual Studio 2015
7. Set Roslyn.sln as start up project
8. Hit F5
9. Get "You are debugging a Release build of Microsoft.VisualStudio.LanguageServices.dll".

**Comment by Pilchie** [comment]
We need to update https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md.

Unfortunately, while you can edit and build with VS 2015, the binaries are only deployed for debugging in VS if you are running VS 2017 RC.

cc @jaredpar @agocke @jasonmalinowski.

**Comment by jasonmalinowski** [comment]
We're using #16016 to track the updating of that document.
