### ISSUE TITLE
Lightbulb doesn't consistently show

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15753]
1. Clone this repo to this commit: https://github.com/dotnet/roslyn-project-system/commit/e8f444a1ebe3d78b6b494d5dc355e95b7da19086
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (build 26005.0 D15PreRel)
4. Open  src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\Tree\Dependencies\DependencyNodeId.cs
5. Navigate and place cursor on line 155

Expected: Light bulb to show
Actual: Light bulb doesn't show, unless I explicitly get it to via CTRL+.

![image](https://cloud.githubusercontent.com/assets/1103906/21001360/f05a3796-bd73-11e6-97b5-f823d377caa2.png)

**Comment by Pilchie** [comment]
Does the lightbulb show in the margin in this case, just not as part of the quick info hover text?  If so, that is because suggestions aren't true `IErrorTag`s that are handled by the editor yet.

Tagging @markw-t and @dpugh.

**Comment by davkean** [comment]
As called on thread, the lightbulb does not show on the margin - unfortunately, I cut the screen shot too short.

**Comment by davkean** [comment]
I've installed the latest build and still regularly hitting this, here's an example for unused usings:

![image](https://cloud.githubusercontent.com/assets/1103906/21206421/f563de94-c2b5-11e6-8cdf-8b3ebf414866.png)

There's something interesting about this case - I just used the [Fix All to fix all instances of Unused Usings](https://github.com/dotnet/roslyn-project-system/pull/952), this one was missed by the Fix All - so something tells me this is something to do with Roslyn. In fact, see this follow up commit (https://github.com/dotnet/roslyn-project-system/pull/952/commits/81fa4550387bc01fc1eb0c6e9740f77c5b6ee06e) that fixes all the ones missed by the first time I ran it.

**Comment by davkean** [comment]
As a heads up, I'm still seeing this in the latest build. I've noticed something in some of the cases I've run into, I double-click a message, it navigates to it, I see the ... under the instance in the editor. Then, it disappears for a while and then eventually comes back, so looks like some of these instances are perf related. Though make note that above the ... never disappeared and still the light bulb didn't show.

**Comment by Pilchie** [comment]
Tagging @heejaechang too.  Something to do with re-analysing the file when it is opened by the navigation possibly?

**Comment by heejaechang** [comment]
@mavasani what would be the case where fix all won't fix something? is fix all heuristic not fix at all if there is case where fix can't be applied? or just skip the one that is not fixable for whatever reason?

@davkean so LB never show up? or if it does show up later, then it is timing issue. otherwise, something seems went wrong. suggested action provider should have refresh logic when re-analysis happens. but hard to know exactly what went wrong. LB itself also cache result so, not sure which part in the pipe line went wrong.

by the way, if it is right after running fix all which touched a lot of files, diagnostic engine will be busy re-analyzing those changed files (changed in RC3 as IDE requested to make error list to respond faster to fix all changes) which might make active file processing a bit slower since diagnostic engine is designed not to cancel current task unless file current task is processing is changed.

**Comment by mavasani** [comment]
@heejaechang Fix all might skip some diagnostics if they have conflicting fixes. However, for Dave's repro, he is doing a FixAll on unused usings, which shouldn't have any conflicts - this should work unless some diagnostics were mixed by FixAll computation or there is some race in the fix all computation.

**Comment by davkean** [comment]
Just to make it clear on the issues as they might be unrelated, I've ran into two issues:

1) The ... showing/namespace faded, but the light bulb never appearing, no matter how long I wait.
2) The ... disappearing when I navigate to it, and then eventually comes back at which point I can use light bulb.

2) might be only a perf issue - but 1) is a functional issue.

**Comment by Pilchie** [comment]
Sadly, I don't think we will have time to take a look here.

**Comment by CyrusNajmabadi** [comment]
Another case where we seem to not be finding everything during fix-all.

**Comment by davkean** [comment]
Still running into this, light bulb only shows on this line if I press CTRL+.
![image](https://cloud.githubusercontent.com/assets/1103906/24742821/2fac6d8c-1aef-11e7-83b9-34e1b5f1105f.png)

**Comment by sharwell** [comment]
@davkean I'm looking at the same behavior happening for me in a file right now. So there's that. 😕

**Comment by gundermanc** [comment]
Hitting this as well occasionally. I think @sharwell hit the nail on the head. It seems things get into a bad state and stay that way until the document is closed and reopened. I find I can still bring up the bulb via Ctrl+., though, so it's probably something particular to the GetSuggestedActionCategoriesAsync() code path

**Comment by CyrusNajmabadi** [comment]
haven't heard reports on this in 5+ years.  closing out.
