### ISSUE TITLE
"Name can be simplified" cannot be suppressed from the Error List

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15766]
1. Clone this repo to this commit: https://github.com/dotnet/roslyn-project-system/commit/e8f444a1ebe3d78b6b494d5dc355e95b7da19086
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (build 26005.0 D15PreRel)
4. Open src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\Debug\LaunchProfileData.cs at line 105
5. In the Error List (not the light-bulb), right-click on the "Name can be simplified" and choose Suppress -> In Source

Expected: For the message to be suppressed
Actual: The message is not suppressed

Note, If you go via the light-bulb it is supressed.

**Comment by Pilchie** [comment]
Moving to Analyzers for the Error-List integration.

**Comment by heejaechang** [comment]
@mavasani is suppression on error list work differently than LB suppression except entry point?

@davkean I can't repro this from lastest master.  but @jmarolf @CyrusNajmabadi sometimes, after preview windows, code fix gets stuck with wait dialog box.

**Comment by davkean** [comment]
That last issue looks like something I called out here: https://github.com/dotnet/roslyn/issues/16086#issuecomment-269575595.

**Comment by heejaechang** [comment]
the reason it got stuck was due to debug only validation which took long time.

**Comment by davkean** [comment]
Hmm - I may have been running with debug bits also.

**Comment by heejaechang** [comment]
so this one seems not repro. I will resolve it as won't repro with latest master.

except master OOP is currently broken due to this - https://github.com/dotnet/roslyn/pull/16226

looks like IDE added new requirement in RegisterWorkspaceHost which caused OOP to broke.

**Comment by davkean** [comment]
@heejaechang Did you try with my actual project (ie the project system repro)?

**Comment by heejaechang** [comment]
yep.
