### ISSUE TITLE
"Object initialization can be simplified" continues to hang around even after you've fixed it

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15764]
1. Clone this repo to this commit: https://github.com/dotnet/roslyn-project-system/commit/e8f444a1ebe3d78b6b494d5dc355e95b7da19086
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (build 26005.0 D15PreRel)
4. Open src\microsoft.visualstudio.editors\attributeeditor\permissionsetservice.vb at line 87
5. Open Lightbulb, choose Object Initialization Can Be Simplified -> Fill all occurrences in Solution
6. Click OK when the dialog opens
7. Wait for ... to removed from Error List

Expected: No Object initialization can be simplified in Error List
Actual: Still 10s of occurrences in the Error List pointing to locations that have been fixed

**Comment by davkean** [comment]
The same occurs if I right-click on the Messages and choose Suppress -> In Suppression File - they all remain.

**Comment by Pilchie** [comment]
This seems like an issue with the analyzer driver.

**Comment by srivatsn** [comment]
Reanalysis is not happening? Or not clearning fast enough?

**Comment by davkean** [comment]
Given the ... went away, I assume that analysis was done, right?

**Comment by srivatsn** [comment]
Yes it should mean that. Need to take a look.

**Comment by heejaechang** [comment]
@mavasani will fix all issued by VB will fix one in cs as well?

@davkean it seems I can't repro this. fix all from vb fixes all vb occurrences and fix all from cs fixes all cs occurrences.

**Comment by heejaechang** [comment]
this is same as other bug. require this fix https://github.com/dotnet/roslyn/pull/16226 to test against latest master.

also, one needs to remove this to use DEBUG bit to test.
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/CodeActions/CodeActionEditHandlerService.cs,120

**Comment by mavasani** [comment]
@heejaechang - FixAll right now operates only on the language on which it was invoked, so it will fix all VB OR C# but not both simultaneously. There is a design restriction that leads to this behavior.

**Comment by heejaechang** [comment]
found cancellation issue in solution crawler. looks like introduced when project analysis got moved out to its own processor.

**Comment by heejaechang** [comment]
with the above fix, it looks like diagnostics left out won't happen anymore.

...

I sometime see fix all stuck and mess up everything including diagnostic engines. looking into that issue now.
