### ISSUE TITLE
Make RemoveUnnecessaryImportsService a public API

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#1576]
We have a fantastic facility to remove and sort usings, however sadly it's internal and we can't use it in cleanup tools such as codeformatter.

Please make the API public to remove and sort usings and imports:

http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/RemoveUnnecessaryImports/RemoveUnnecessaryImportsService.cs,4f75e1eeef1dda98

**Comment by srivatsn** [comment]
This will not solve all the problems but @mattwar made the simplifier also remove unused usings. So if you annotate your usings with a Simplifier annotation, and simplify it, then it will be removed. It will not sort the usings though.

**Comment by KirillOsenkov** [comment]
Ah, thanks for reminding me!

This also needs to be public, of course:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/OrganizeImports/OrganizeImportsService.cs,1944cfd453abc8b1

**Comment by mavasani** [comment]
Alternative: Once FixAllContext constructors become public, Sri is going to work on it, you should be able to trigger FixAll across scope of interest with diagnostic ID for unnecessary usings. That way if you are only interested in removing unnecessary usings, but not everything that can be simplified (casts, type names), it should work.

**Comment by KirillOsenkov** [comment]
This is a good workaround however we do need to make the two above APIs public regardless.

**Comment by mynkow** [comment]
Is it possible to have this service public?

**Comment by CyrusNajmabadi** [comment]
closing out.  would need to go through actual API process.
