### ISSUE TITLE
VSProjectTracker throws which cause second solution load to always fail

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15768]
basically this throws
http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/VisualStudioProjectTracker_IVsSolutionEvents.cs,97

repro is simple. just create console app and close and reopen.

at close, the above throws, after that all solution is opened in misc project.

**Comment by heejaechang** [comment]
I think this is urgent bug. since second solution open never works.

**Comment by heejaechang** [comment]
@mavasani @jasonmalinowski @Pilchie @mattwar so who should I give this bug to? I think this bug is urgent.

related commit - https://github.com/dotnet/roslyn/commit/d8c76666da3eee317028f1c34e0eab28b33ccb6d

**Comment by jasonmalinowski** [comment]
@mattwar Can you take a look?

**Comment by mattwar** [comment]
I'm OOF until Monday.

**Comment by mavasani** [comment]
@heejaechang Can you try reverting the commit and see if it resolves the VSI test issues? Please re-open the resolved VSO bug when you merge in the revert.

**Comment by mattwar** [comment]
This was fixed by #15800
