### ISSUE TITLE
NamingStyle violation doesn't show up in console app

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15763]
Repro step

1, create new console app
2. add this code

...

using System.Threading.Tasks;

public class Program
{
    static void Main(string[] args)
    {
    }

    public Task Foo()
    {
        return null;
    }
}

..

expected
Message	IDE1006	Naming rule violation: Missing suffix: 'Async'	to show u p

actual
nothing happens.

...

does this rule require some special flag in project file?

**Comment by heejaechang** [comment]
https://github.com/dotnet/roslyn/issues/15760#issuecomment-265690136

**Comment by davkean** [comment]
This looks like this is due the design of the Async name checker - it only fires if the method is marked as "async" - not whether it's a task returning async method or not. That seems limiting.

tag @dpoeschl

**Comment by CyrusNajmabadi** [comment]
We don't currently ahve a way to have arbitrary ways to designate symbols of interest.  You're limited to basic things (like type of symbol, accessibility of symbols, modifiers of the symbol).  In the future we want to expose this as a extensibility point.  That way users can provide pieces of code that designate if their symbol is a match or not.  i.e. "Equals(taskOfTType, (symbol as IMethodSymbol)?.ReturnType.OriginalDefinition)"

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
