### ISSUE TITLE
Expand IVsHierarchy mocks to support solution folders and parented projects

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#15778]
This will enable writing a unit test for https://github.com/dotnet/roslyn/pull/15741.

**Comment by CyrusNajmabadi** [comment]
We can drive this if someone actually goes and tries to flesh out tests in this area.  DOn't really need a tracking bug here.

**Comment by sharwell** [comment]
Fixed the label to be Test-Gap (tracking issue).

**Comment by CyrusNajmabadi** [comment]
Clsoing out as speculative.
