### ISSUE TITLE
Go to All shows no results if projects aren't finished loading

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#15777]
**Version Used**: RC.2

**Steps to Reproduce**:

1. Open Roslyn.sln
2. Immediately invoke Go to All (Ctrl + T)
3. Search for a type

**Expected Behavior**:
Got to All doesn't say "no results found." until all the projects have loaded

**Actual Behavior**:
The user is shown "no results found." and the user needs to dismiss and reinvoke Go to All after the projects have been loaded to actually get results.

**Note:** the only indication that the projects are not done loading is the subtly progress bar at the top of Solution Explorer.

**Comment by Pilchie** [comment]
Can you follow-up with the editor team here about the experience?  I thought it was supposed to indicate partial results directly in the Go To UI?

@jmarolf  did you have Lightweight solution load enabled?

**Comment by jmarolf** [comment]
I updated to the latest RC.2 build today and it does tell you that projects aren't loaded.
