### ISSUE TITLE
Issues with non-blocking FixAll computation experience

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#15775]
**Version Used**: 
D15prerel 26007.1 (yesterday's build)

**Steps to Reproduce**:

1. git clone https://github.com/dotnet/roslyn-project-system
2. From a devenv admin command prompt, execute build.cmd from the root of the repo.
3. Open `src\ProjectSystem.sln`
4. Open source file `src\Microsoft.VisualStudio.Editors\Common\Utils.vb` in project Microsoft.VisualStudio.Editors.vbproj
5. Invoke FixAll for document scope for IDE0017 on line 217

**Expected Behavior**:
Cancellable wait dialog shows up, preventing further edits to solution snapshot OR further invocations of code fixes/FixAll operations

**Actual Behavior**:
There are multiple issues in the new behavior:
1. We seem to be kicking off a background FixAll operation, and there is no indication given to the user that FixAll is being computed in the background - it feels as if the FixAll operation was a no-op.
2. After a considerable amount of time (depending on size of the solution/performance of analyzer fix all), the FixAll preview dialog pops up all of a sudden. A dialog popping up for an operation invoked few seconds in the past, doesn't seem to be a good experience.
3. If in the meantime (i.e. before the FixAll preview dialog comes up). I edit the code on line 217 to remove the `New` keyword in the object initialization statement, we end up in a bad state. FixAll preview dialog operated on a solution snapshot prior to my edit and hence ignores my edit. Trying to apply the fix bails out, without any indication that FixAll apply did not work.
4. Instead of editing code as in 3. above, I kick off another FixAll in document on the same line while the first FixAll is still computing in the background, then 2 FixAll preview dialogs come up one after another. I can dismiss/apply the fix all from the first dialog, but second dialog hangs around forever and I can neither dismiss/apply/close it. I am forced kill VS to get back to editing code. In fact, VS crashed if I click the `?` at top of the second fix all preview dialog.

![image](https://cloud.githubusercontent.com/assets/10605811/21023291/b6270570-bd34-11e6-92ae-518edd4c7ab9.png)

Above issues were all considered when we made FixAll a blocking operation with a cancellable dialog, especially given it is a user invoked operation that changes the solution snapshot. I feel we should bring back the old experience to get consistent behavior and user experience.

**Comment by mavasani** [comment]
Tagging @CyrusNajmabadi - I am not sure if the cancellable wait dialog not showing up for FixAll is a bug OR a design/experience change.

**Comment by CyrusNajmabadi** [comment]
It's a bug.  @jmarolf is working on it with this tracking bug: https://github.com/dotnet/roslyn/issues/15411

**Comment by davkean** [comment]
https://github.com/dotnet/roslyn/issues/15761 and https://github.com/dotnet/roslyn/issues/15762 are related and probably dups.

**Comment by Pilchie** [comment]
Is this a better bug to track this with than #15411?

**Comment by jmarolf** [comment]
@Pilchie yeah, lets close @CyrusNajmabadi 's bug in favor of this one.

**Comment by CyrusNajmabadi** [comment]
@jmarolf Can we follow the pattern we use with other ThreadedWaitDialog situations?  Namely, we create the TWD and do a blocking Wait on the async work we need to do?  I'd like to see how well that works out.

**Comment by CyrusNajmabadi** [comment]
Note: we'll still need to address the Preview-Changes dialog.  When we decide we need to show PreviewChanges, we immediately relinquish the thread we're on (so that the TWD goes away), and then on the next pump we show the dialog.

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/roslyn/pull/15767
