### ISSUE TITLE
NamingStyleCodeFixProvider crashes on const readonly

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#15788]
Obviously not a normal scenario, but for the moment that I had `const readonly`, the naming style code fix provider crashed. Possibly related rules (in precedence order):
(Private|Protected) Static Readonly (Property|Field) -> PascalCase
(Internal|Private|Protected|Protected Internal) Static Field -> s_ prefix.

Tested on d15rel/26008.00.

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at async Microsoft.CodeAnalysis.CodeFixes.NamingStyles.NamingStyleCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by dpoeschl** [comment]
@jmarolf - The fact that this crashes is weird. Don't we have exception handlers to pop up the infobar?

**Comment by dpoeschl** [comment]
@jmarolf - Filed a separate bug for the crash at #16428

**Comment by 333fred** [comment]
@dpoeschl, it didn't crash vs, at least when I filed the bug. It popped up in the infobar.

**Comment by dpoeschl** [comment]
Ahh, @jmarolf is this because it was debug bits?

**Comment by jmarolf** [comment]
@dpoeschl yep

**Comment by rchande** [comment]
I also encountered this infobar while editing `CSharpDebuggerIntelliSenseTests.vb` in Roslyn.sln.

**Comment by dpoeschl** [comment]
Filed #16588 to fix the problem completely. For this bug, I hope to just eliminate the failure/infobar by providing no codefix when the symbol cannot be found.
