### ISSUE TITLE
Closing/reopening a solution is crashing VS.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15781]
Crash occurs here:

```c#
        int IVsSolutionEvents.OnAfterCloseSolution(object pUnkReserved)
        {
            AssertIsForeground();

            if (IsDeferredSolutionLoadEnabled())
            {
                // Copy to avoid modifying the collection while enumerating
                var loadedProjects = ImmutableProjects.ToList();
                foreach (var p in loadedProjects)
                {
                    p.Disconnect();
                }
            }

            lock (_gate)
            {
                Contract.ThrowIfFalse(_projectMap.Count == 0);
            }
```

In ```Contract.ThrowIfFalse(_projectMap.Count == 0);```

@mattwar Is this due to the project-unload-queuing work you did?

**Comment by mattwar** [comment]
@CyrusNajmabadi Yes.. the change was to make it always postpone the removal of the project so it is properly sequenced with other operations in the queue.  Unfortunately, the queue even existing means all the project tracker operations are fundementally async.

**Comment by CyrusNajmabadi** [comment]
that's unfortunate.  Any ideas on what we should do here?

**Comment by mattwar** [comment]
obviously, we can revert the change, but that will just bring the race condition back.  As you can see with this problem, any event coming in from VS potentially has the same race condition with respect to the background queue.

**Comment by CyrusNajmabadi** [comment]
Did your chnage go into RC2 or RC3?  Thanks!

**Comment by mattwar** [comment]
It just went into master yesterday

**Comment by mattwar** [comment]
The change I made was reverted..  This issue no longer applies
