### ISSUE TITLE
Crash in serialization.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15780]
![image](https://cloud.githubusercontent.com/assets/4564579/21028189/dddc5f02-bd48-11e6-9901-8aabe6cbb159.png)

Tagging @heejaechang @mattwar This looks like a combination of wrk that both of you have done.  

1. "IsRecursive".  That's your work, right Matt?
2. 'EncodingKind'.  That's your work, right Heejae?

**Comment by mattwar** [comment]
Heejae found this a couple of days ago.  It is crashing because its deserializing from persisted state and the serialization format has changed.  You can kill your VS cache and start up again.

**Comment by heejaechang** [comment]
tagging @mattwar 

I send email to matt about this before. basically what is happening is that, format of stream is now changed due to objectreader/writer change.

any data saved by earlier version of objectreader/wrtier will now throw when read by new version of object reader.

all consumer of such stream (such as stream saved in persistent storage) now needed to be guard from that exception or change data format version of that stream.

**Comment by heejaechang** [comment]
and yes, like matt said, workaround is deleting .vs folder. but I am not sure whether that is enough for consumer since it will crash their VS and they won't know what is going on.

**Comment by davkean** [comment]
Like this: https://github.com/dotnet/roslyn/issues/15765?

**Comment by CyrusNajmabadi** [comment]
We need to store a persistence version and change this whenever this happens.  Can one of you fix this?

Any data we persist must be resilient to being read in a future version of VS.

**Comment by mattwar** [comment]
I was unaware there was any persistence going on.  There is no versioning story for this persistence.  The serializer was not meant to be used this way.  It was designed for in-process (and possibly inter-process) serialization, not across time or version of VS/roslyn.

**Comment by mattwar** [comment]
@CyrusNajmabadi  it is not enough to simply add version information into serialization stream.  That would simply lead to an exception when you try to read the wrong version and would be the same experience.  In order to have cross version support each object would need its own versioning story and the ability to either fail and recover when deserializing or maintain backward compatibility across time.

**Comment by heejaechang** [comment]
@davkean #15765 is different issue. fix is scheduled for RC3. added comment on the issue.

...

right now, object reader/writer itself doesn't have versioning. the one who uses that such as SyntaxTreeIndex or SymbolTreeInfo has serialization version.

all those that save stream to persistent service using object reader/ writer needs to update their version.

**Comment by CyrusNajmabadi** [comment]
> That would simply lead to an exception when you try to read the wrong version

I don't see how that's the case.  We changed the persistence format.  The persistence reading mechanism needs to be resilient to data being read in from a previous version.  If the previous persisted data *lacks* a version, then the data should be considered unreadable.  

--

All our features do this already.  But this time the issue is happening at the core persistence layer itself, before the feature can even get involved.

**Comment by heejaechang** [comment]
I don't think object reader itself can know whether issue is due to stream format change or not. also there is no place to put such information in since object reader/writer can be used in the middle of stream. version must be owned by the data itself such as syntax tree index or diagnostic state and etc.

**Comment by CyrusNajmabadi** [comment]
> all those that save stream to persistent service using object reader/ writer needs to update their version.

@heejaechang That will not help.  The crash is happening *before* we can even get around to reading the version.  The crash happens in "new StreamObjectReader(stream)" *itself*.  StreamObjectReader assumes that hte stream it reads will have a certain format.  It cannot presume that as it may be created over data persisted from a previous version of VS.

**Comment by heejaechang** [comment]
that will be an issue actually then.

**Comment by CyrusNajmabadi** [comment]
> also there is no place to put such information in since object reader/writer can be used in the middle of stream. 

StreamObjectReader/Writer is fully capable of adding/checking for any data it needs.  If StreamObjectReader/Writer changes it's internal representation, then it must be able to check if that has happened and deal with it appropriately.

**Comment by CyrusNajmabadi** [comment]
Note: all our features do persist a version ID that they check whenever *they* change their representation.  The problem here is that the underlying stream persistence API changed it's own in-stream representation, and it's not resilient to reading in old data.

Changing versions at hte feature level will not help as we're not even making it to the point where we can read the feature-version.  The crash is happening at a lower level than that.  

--

@mattwar We've been using StreamObjectReader/Writer to persist feature index data for several Roslyn releases now.  We cannot release in the current state.  This will break 100% of customers who upgrade.  Has this change made it into RC2, or is it in RC3?  If the former, we need to immediately address this.  Otherwise, we need to make this a high priority for addressing so we can get something into ask mode before RC3 ships.

**Comment by heejaechang** [comment]
my mental model for object reader/writer was like binary writer/reader with some added functionality and should be able to be used when binary writer/reader is used.

if there is some header to the stream for reader/writer need to work, it now no longer straight stream reader/writer.

**Comment by CyrusNajmabadi** [comment]
@Pilchie For visibility.

**Comment by heejaechang** [comment]
I think this only happen for find symbol, other ones that uses persistent service actually doesn't crash VS. is it because they don't expect stream reader to throw exception?

**Comment by CyrusNajmabadi** [comment]
StreamObjectReader could never throw an exception before in its constructor.  It is not documented to throw... it's very exceptional that we would throw an exception reading a stream that we successfully persisted before.

**Comment by mattwar** [comment]
Stream reader/writer always had assumption that stream was never persisted across sessions.

**Comment by CyrusNajmabadi** [comment]
Ok.  But that assumption is clearly incorrect.  We've been persisting using StreamReader/Writer for *years*.  It's literally the underpinning behind all of the persistence we do.  We persist diagnostics using this.  We persist every IDE index using this.  We persist things like todo-comments and designer-attributes with this.

If we don't use this for persistence, then we just need to reinvent the wheel, creating another persistence service that basically serves the exact same purpose (except is resilient to format changes).

**Comment by mattwar** [comment]
Being resilient to format changes makes the serialization slower, and this one was meant for making tree serialization as fast as possible.  We are probably better off to have two different implementations.

**Comment by CyrusNajmabadi** [comment]
Can you have a new layer built on top of this.  One that validates versioning info, and one that doesn't.  Then we can document that the one that doesn't should only be used for in-memory situations?
