### ISSUE TITLE
Turn naming rules and style rules off by default

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#15786]
Because we do not currently support one-click code style cleanup, having code style and naming rules on by default creates a cluttered and frustrating experience for developers.

Let's turn these off by default until we have a solution for this clutter and quickly resolving your code style/naming violations. 

FYI @davkean, @pilchie

**Comment by CyrusNajmabadi** [comment]
@kuhlenh Editor team is turning off the column by default, as per the internal thread you are on.  Is that not sufficient here?  You will not get any items showing in your error list, and you'll get the effective 'advertisement' by seeing '0 of XXX messages' shown.

**Comment by kuhlenh** [comment]
Code style we can keep on with the Messages off because you can fix each 'type' of error in mass. However, I still think we should turn naming rules off by default as there is no way to fix them (e.g., what happens when you want to fix your code style issues and you turn Messages on and are littered with naming rule violations? How do you even know where to turn these naming rules off?).

Make sense?

**Comment by CyrusNajmabadi** [comment]
Possibly.  I'd much rather us just invest in a way to turn these off from the lightbulb.

**Comment by davkean** [comment]
You can change them via the lightbulb:

![image](https://cloud.githubusercontent.com/assets/1103906/21032794/0e932fc4-be00-11e6-8da0-7510b975b947.png)

**Comment by CyrusNajmabadi** [comment]
I meant actually being able to turn off.  We have some designs that Kasey/David are working on that would allow for that.

**Comment by Pilchie** [comment]
I'm generally in favor of having these on by default just for the advertising aspect of it.  We'll continue to monitor VS feedback reports to see how people seem to feel about these in RC and RC.2 though.

**Comment by davkean** [comment]
I'm not a fan on having them on by default - they are currently firing on every single unit test.

**Comment by CyrusNajmabadi** [comment]
They will be analyzed by default, but won't show up in the error list by default.  The user will see the advertisement "0 of XXX Messages".  They can click on the item and then see the items and choose to address them if they want.  But they're not getting spammed with messages by default.

**Comment by davkean** [comment]
Yes, but if I want to see the other useful things I now need to see a bunch of noise intermixed with it. 

There's already been feedback on this, Brad pointed this out and I've pointed this out - working on Code Analysis for many years, I'm absolutely convinced that you need to have better defaults.

**Comment by CyrusNajmabadi** [comment]
What useful things do you want to see?  From our telemetry the 'messages' window is practically not used at all.

The default will be that people will not see things, except a small advertisement that there are potentially messages they can see if they want to.  I would lke to try out that experience to see how well it works for people first.

**Comment by davkean** [comment]
I mean "useful stuff from Roslyn" not "useful stuff from other components".

For example, the pattern matching simplification is all goodness https://twitter.com/davkean/status/806760939420676097 (and the community agrees given the number of retweets/likes). 

You can't argue that a naming rule that fires on every single async test is in the same bucket as the above fix.

**Comment by Pilchie** [comment]
Maybe we should keep the other naming rules, but turn the Async Method rule off?
