### ISSUE TITLE
Parameters of unreferenced type break many IDE features

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#15799]
**Version Used**: 2017 RC

Create 2 projects:

In project 1, with reference to System.Windows.Forms.dll:
```C#
public class C {
	public static void M(System.Windows.Forms.Control c) { }
}
```

In a second project, with a reference to the first project but not to WinForms, type `C.M`.

 - In the Members completions after typing `C.`, the `M` entry has a completely empty tooltip.
 - Peek Definition on `M` shows a generic error.

Quick Info and Go To Definition work fine (Quick Info doesn't highlight the parameter type as a class, which makes sense).  No exceptions are thrown.

I assume the issue here is that overload resolution fails too fatally.

**Comment by Pilchie** [comment]
@gafter - do you want to look at this from the compiler side first?

**Comment by jcouv** [comment]
@SLaks I tried to repro this, but was unable to (in VS 2017 version 15.6 preview 1). 
I'll go ahead and close. Feel free to re-open if you're still seeing this in a recent version. Thanks

Created a solution with 3 projects: 
(1) a library with type `LibClass`, 
(2) another library with type `AnotherLibraryClass` and method `void M(LibClass)` and a reference to the assembly produced by the first project, and 
(3) a client (shown below).

The tooltip on completing the method looks fine:
![image](https://user-images.githubusercontent.com/12466233/33789250-1a9f160c-dc2c-11e7-8c3d-d5b48a9d22bb.png)

Peek Definition worked:
![image](https://user-images.githubusercontent.com/12466233/33789344-b81e7c06-dc2c-11e7-888a-af78d8a55fc6.png)

The client project does not reference the assembly from first project, as shown here:
![image](https://user-images.githubusercontent.com/12466233/33789320-9193fd54-dc2c-11e7-964e-fc499ab2e4ee.png)
