### ISSUE TITLE
Type generalization refactorings

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#15796]
- [x] Push member Up 
- [ ] Push member down
- [x]  Make abstract member in base
- [ ] Make virtual member in base

Particularly useful in writing cross-language analyzers. :)

**Comment by Pilchie** [comment]
Definitely care about these.  I'm surprised we didn't have them on our backlog already.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
