### ISSUE TITLE
Visual Studio does not provide any feedback when options are changed

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#15803]
When changing options in Visual Studio there's no feedback that tells the person what changed or at least a message at the bottom that tells the person how many things changed or even that things changed at all.

Now, In Visual Studio the UX experience is such that changes are immediate, e.g., you click on a label and you can uncheck/check a checkbox so sometimes a person might change options either because he/she _misclicked_ or because they played with the options and thought they changed it back to the default but didn't, some people will forget or mistakenly click the Okay button and not the Cancel button.

So I think that in addition to counting the amount of changes and put a message at the bottom of the window about it, it would be great if the style of the text for controls/widgets would change into bold when changes are made.

**Comment by Pilchie** [comment]
Can you follow-up with the platform team to suggest this?

**Comment by kuhlenh** [comment]
Brought this to the attention of the IDE Platform team.
