### ISSUE TITLE
Suggestion: Ability to compile from stdin (without file)

### ISSUE THREAD

**Issue by am11** [dotnet/roslyn#15802]
It would be a nice improvement to command line interface of roslyn compilers, if the ability to pipe the code to the compiler (or read from stdin) is introduced. This would:

* come handy when making short, self-contained examples
* make the compilers consistent with similar utilities of era
* allow the downstream utilities to expose a similar option and they will simply pipe the stdin to csc/vbc (e.g. stdin->dotnet->msbuild->csc)

Consider the following GCC example:

```sh
echo 'int main(){return 0;}' | g++ -x c++ -O -Wall -o myapp.exe /dev/stdin

# or

g++ -x c++ -O -Wall -o myapp.exe - << EOF
int main() {
  return 0;
}
EOF
```

and another one using node.js (interprets and executes; meant for `csi.exe`):

```sh
node -e console.log(process.arch) # evaluation mode

# or

node -p console.log(process.arch) # printing mode
```

Having an option similar to GCC in CSC and VBC would enable us to do:

```sh
echo 'using System;class A{static void Main(){Console.WriteLine(321);}}' | csc /out:myapp.exe

# or

csc /out:myapp.exe - << EOF
using System;
class A {
  static void Main() {
    Console.WriteLine(321);
  }
}
EOF
```

and for the one similar to node.js in CSI:

```sh
csi /e Console.WriteLine(321)
```

Having the code to a temp file and compile is an ok alternative, but on-the-file option without filesystem I/O intervention has its significance as well. :)

**Comment by saitolabs** [comment]
+1
