### ISSUE TITLE
Analysis errors with some sequences of Expression<> declarations and assignments and uses

### ISSUE THREAD

**Issue by tskarman** [dotnet/roslyn#15805]
I observed this behavior in a project of mine. I then went ahead and succeeded in reproducing it with a fresh project.

A workaround appears to be to shuffle the assignments around so that no "similar" signatures appear in sequence.
The issue described can also be reproduced in a different way: Move the assignments directly to the field declarations. The same phenomenon takes place.

**Version Used**: Microsoft Visual Studio Community 2017 RC15.0.25920.0 D15REL - see 
[vsinfo.txt](https://github.com/dotnet/roslyn/files/642203/vsinfo.txt)

**Steps to Reproduce**:

1. Download and extract [ConsoleApp1.zip](https://github.com/dotnet/roslyn/files/642176/ConsoleApp1.zip)
2. Open ConsoleApp1.sln with VS 2017 RC
3. Open "Error Window" and include IntelliSense errors in list.
4. Open source file Program.cs
5. Observe error indication by IntelliSense
6. Add empty line to file. Save. Observe IntelliSense errors disappear.
7. Close solution.
8. Open solution.
9. Observe that IntelliSense error indications return.

**Expected Behavior**:

No error indications via IntelliSense.

**Actual Behavior**:

Error indications via IntelliSense. See attached ![image1](https://cloud.githubusercontent.com/assets/2319548/21049934/ec0a780a-be17-11e6-9faa-47e9342d0290.png).

**Comment by tskarman** [comment]
Also, these issues report similar issues:
- #14981
- #15545

**Comment by OmarTawfik** [comment]
Thanks for reporting.
I believe this is a repro of #14649. The fix #14852 went into master.
