### ISSUE TITLE
Find All References should provide incremental results

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15829]
On the project system repro (http://github.com/dotnet/roslyn-project-system), I'm finding that it takes at least ~20 seconds to find results of the average type within the Microsoft.VisualStudio.ProjectSystem.Managed project.

Is there a way to see progressive results so I get results sooner?

**Comment by Pilchie** [comment]
I thought we did get results streamed in now?

**Comment by CyrusNajmabadi** [comment]
We definitely do (and i can observe results streaming in on my own box).  My guess is that this is related to the editor's issue with updating the progress bar.  Their UI thread is completely hogged doing nothing but updating the progress bar.  So all the actual entries in the list end up not showing until the progress bar completes.  Daofa is working on a fix.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/51610?_a=overview
