### ISSUE TITLE
Find All References progress bar doesn't always make progressive progress

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15828]
The progress bar on the new Find All References doesn't always make forward progress, which makes for a frustrating progress bar. 

If you can't get accurate progress, can you "fake it" similar to browsers to always make forward progress?

See: https://vid.me/H7rY

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/15549

**Comment by CyrusNajmabadi** [comment]
We should now always have accurate progress.  We initially have no progress. Then we figure out the set of documents to search.  We use the count of that to get our progress 'step' and then we increment the progress bar as we process each document.

**Comment by davkean** [comment]
I realize this might not be your bug - but this is still is occurring in recent builds out of mastr. The progress bar still goes backwards in some cases.

**Comment by Pilchie** [comment]
Can you take a look?

**Comment by CyrusNajmabadi** [comment]
Fixed with https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/51610?_a=overview
