### ISSUE TITLE
foreach shouldn't emit finally blocks for empty dispose methods

### ISSUE THREAD

**Issue by benaadams** [dotnet/roslyn#15824]
Foreach loops with concrete enumerators shouldn't emit a finally block to call Dispose if the Dispose method is empty.

The finally block blocks any function from using `foreach` from being an inline candidate.

So for example this function is not inlinable
```csharp
public static void ValidateHeaderCharacters(StringValues headerValues)
{
    foreach (var value in headerValues)
    {
        ValidateHeaderCharacters(value);
    }
}
```
with reason
`[FAILED: has exception handling] FrameHeaders:ValidateHeaderCharacters(struct)`

Because post C# compile it is actually more like this
```csharp
var e = headerValues.GetEnumerator();
try
{
    while (e.MoveNext())
    {
        ValidateHeaderCharacters(e.Current);
    }
}
finally
{
    e.Dispose();
}
```
The full il for the function is
```cil
  .method public hidebysig static void 
    ValidateHeaderCharacters(
      valuetype [Microsoft.Extensions.Primitives]Microsoft.Extensions.Primitives.StringValues headerValues
    ) cil managed 
  {
    .maxstack 1
    .locals init (
      [0] valuetype [Microsoft.Extensions.Primitives]Microsoft.Extensions.Primitives.StringValues/Enumerator V_0
    )

    // [247 38 - 247 50]
    IL_0000: ldarga.s     headerValues
    IL_0002: call         instance valuetype [Microsoft.Extensions.Primitives]Microsoft.Extensions.Primitives.StringValues/Enumerator [Microsoft.Extensions.Primitives]Microsoft.Extensions.Primitives.StringValues::GetEnumerator()
    IL_0007: stloc.0      // V_0
    .try
    {

      IL_0008: br.s         IL_0016
      // start of loop, entry point: IL_0016
        IL_000a: ldloca.s     V_0
        IL_000c: call         instance string [Microsoft.Extensions.Primitives]Microsoft.Extensions.Primitives.StringValues/Enumerator::get_Current()
        IL_0011: call         void Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameHeaders::ValidateHeaderCharacters(string)
        IL_0016: ldloca.s     V_0
        IL_0018: call         instance bool [Microsoft.Extensions.Primitives]Microsoft.Extensions.Primitives.StringValues/Enumerator::MoveNext()
        IL_001d: brtrue.s     IL_000a
      // end of loop
      IL_001f: leave.s      IL_002f
    } // end of .try
    finally
    {
      IL_0021: ldloca.s     V_0
      IL_0029: call     instance void Microsoft.Extensions.Primitives]Microsoft.Extensions.Primitives.StringValues/Enumerator::Dispose()
      IL_002e: endfinally   
    } // end of finally
    IL_002f: ret          

  } // end of method FrameHeaders::ValidateHeaderCharacters
```

Would like need to be when the enumerator is in the same assembly? To avoid compat breaks?

**Comment by mikedn** [comment]
> Foreach loops with concrete enumerators shouldn't emit a finally block to call Dispose if the Dispose method is empty.

How is Roslyn supposed to know that the `Dispose` method is empty? Is the code in your example all in the same assembly?

**Comment by benaadams** [comment]
> How is Roslyn supposed to know that the Dispose method is empty? Is the code in your example all in the same assembly?

I added that as a point to the bottom; but you are right in my example its not so it wouldn't work... 😒

**Comment by mikedn** [comment]
And it's not only about compatibility, when reference assemblies are used the compiler doesn't even see the actual IL.

**Comment by gafter** [comment]
"optimizations" such as this are the job of the runtime compiller, not the front end. In that way the optimization can work across assemblies as well as it does within the same assembly.
