### ISSUE TITLE
Compiler Option /nostdlib is Ignored

### ISSUE THREAD

**Issue by ThePademelon** [dotnet/roslyn#15827]
**Steps to Reproduce**:

1. Instantiate a CSharpCodeProvider.
2. Add reference to https://puu.sh/sMwNp/9bd6204e80.dll.
3. Create a CompilerParameters object and use CompilerOptions = "/nowarn:1659;1699;1701;612;618 /nostdlib+ /noconfig /define:SILVERLIGHT;".
4. Call CompileAssemblyFromSource(CompilerParameters, params string[]).

**Expected Behavior**:
Successful build.

**Actual Behavior**:
Build fails with error CS1703.

**Comment by gafter** [comment]
This issue does not appear to be about the Roslyn compiler. The Roslyn compiler does not have those APIs.

**Comment by ThePademelon** [comment]
Well this is utilised via CodeDom. So it's either a Roslyn issue or a CodeDom issue. If you could direct me to the CodeDom issue tracking system that would also be helpful.

**Comment by ThePademelon** [comment]
Okay, I went into the repo and discovered that an SDK has to be specified in a special parameter in order for /nostdlib to take effect. There really should be a warning or at the very least some documentation around around /nostdlib command regarding this behaviour.

If I get time I'll make the fix myself via PR.
