### ISSUE TITLE
Compile-time inlining Expression Methods

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/roslyn#15825]
Right now as a developer I can put `[MethodImpl(MethodImplOptions.AggressiveInlining)]` on a method and it **might** be implemented and only at runtime. I can think of dozens of reasons for these limitations BUT I think in a limited use case they can be over come.

If a method has `[MethodImpl(MethodImplOptions.AggressiveInlining)]`, is not virtual, has no other attributes on it, no attributes on its parameters, no attributes on its return, and is an expression method the complier can inline the method. It would still need to be emitted for reflection and delegate usage.

**Comment by gafter** [comment]
@SamuelEnglard This issue properly belongs on the [runtime compiler](https://github.com/dotnet/coreclr), which is where the inlining occurs. We do not perform optimizations in the C# and VB front ends, as only the runtime compiler has enough information to apply them consistently (e.g. across assembly boundaries).

**Comment by SamuelEnglard** [comment]
@gafter But that is the very point of my issue. I realize that they cannot be inlined across assembly boundaries and the like which is why I said they would still have to be emitted. (though that could be solved by saying the method must be internal to the assembly)

The point of this is that there are (though limited) cases where the compiler CAN inline.

**Comment by gafter** [comment]
@SamuelEnglard Indeed... and there are far fewer limitations where the runtime compiler can or does inline.

**Comment by SamuelEnglard** [comment]
@gafter but as a developer if I know for sure (which only the compiler can really do) that a method will be inlined I can use it differently. *coughc++macroscough*
