### ISSUE TITLE
Performing more than one Find All References at a time causes the windows to not display results until all searches have finished

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15833]
1. Clone this repo to this commit: https://github.com/dotnet/roslyn-project-system/commit/e8f444a1ebe3d78b6b494d5dc355e95b7da19086
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (build 26005.0 D15PreRel)
4. Open src\Microsoft.VisualStudio.ProjectSystem.Managed\Threading\Tasks\TaskResult.cs
5. Right-click on TaskResult and choose Find All References
6. Click Keep Results
7. Repeat steps 5 and 6, 4 times

Expected: Results to appear as they are done
Actual: Windows only show results when all are done

See video: https://vid.me/aYyP.

**Comment by davkean** [comment]
Note, if you notice carefully, 6 searches are performed even though I've only kicked off 4 invocations, I've filed a separate bug to track that: https://github.com/dotnet/roslyn/issues/15834

**Comment by CyrusNajmabadi** [comment]
Fixed with https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/51610?_a=overview
