### ISSUE TITLE
Choosing "current project" filter in Find All References, results in zero results

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15830]
1. Clone this repo to this commit: https://github.com/dotnet/roslyn-project-system/commit/e8f444a1ebe3d78b6b494d5dc355e95b7da19086
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (build 26005.0 D15PreRel)
4. Open src\Microsoft.VisualStudio.ProjectSystem.Managed\Threading\Tasks\TaskResult.cs
5. Right-click on TaskResult and choose Find All References
6. From the Find All References, choose Current Project

Expected: For three results to be listed

![image](https://cloud.githubusercontent.com/assets/1103906/21089129/a994b462-c089-11e6-82e1-8934a23668bf.png)

Actual:

![image](https://cloud.githubusercontent.com/assets/1103906/21089132/afd34cc6-c089-11e6-9297-1d5a84b22bb2.png)

I played around with a few types, and seems like the "Current Project" filter is broken.

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Can you file a bug on this against the editor?  Roslyn is not responsible for project filtering, it happens on the VS side.  Thanks!

**Comment by davkean** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems?id=359445&fullScreen=false&_a=edit

**Comment by olegtk** [comment]
Ooops, @CyrusNajmabadi, looks like we misinformed you in PR #14751, this feature does depend on the project guid that you removed :( Sorry about that. Will route the bug to you.

**Comment by davkean** [comment]
Reopening, based on that. I'll close the VS one.

**Comment by CyrusNajmabadi** [comment]
Ok.  If we add this back in though this will break 'anycode'.  Will try to find the original bug to let them know about that.
