### ISSUE TITLE
Performing more than one Find All References at a time, causes more searches than invocations

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15834]
1. Clone this repo to this commit: https://github.com/dotnet/roslyn-project-system/commit/e8f444a1ebe3d78b6b494d5dc355e95b7da19086
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (build 26005.0 D15PreRel)
4. Open src\Microsoft.VisualStudio.ProjectSystem.Managed\Threading\Tasks\TaskResult.cs
5. Right-click on TaskResult and choose Find All References
6. Click Keep Results
7. Repeat steps 5 and 6, 4 times

Expected: Only 4 searches to be performed
Actual: 6 total searches are performed

See video: https://vid.me/aYyP.

**Comment by CyrusNajmabadi** [comment]
VS hard caps the number of windows they want to create.  That cap is here: http://index/?leftProject=Microsoft.VisualStudio.ErrorListPkg&leftSymbol=h9anve8akzcw

Can you file a bug against the editor team if you'd like this experience or behavior improved?  Roslyn has no control over this.

**Comment by davkean** [comment]
Having looked at the source code, I think you're misinterpreting the bug - the bug is that I've kicked off _4_ Find All References invocations, but _6_ searches are occurring. The number of windows I expect is only 4.

**Comment by CyrusNajmabadi** [comment]
I'm not certain what's going on then.  Roslyn does not control any of the windowing here.  We just get called in to produce results, and we just supply the data.

**Comment by Pilchie** [comment]
Can you follow-up with the platform team on whether we need to do something here?

**Comment by CyrusNajmabadi** [comment]
Not certain about this issue.  I need to investigate (ideally with the editor's fixes and our fixes applied).

**Comment by CyrusNajmabadi** [comment]
@davkean Can you still repro this?  I tried this in Roslyn and didn't see anything go wrong.

**Comment by davkean** [comment]
It's now too fast (!) in the above solution to repro this. :(

**Comment by CyrusNajmabadi** [comment]
>It's now too fast 

That's what i like to hear!

**Comment by davkean** [comment]
Yeah, it finds the usage instantly.

**Comment by CyrusNajmabadi** [comment]
Yeah, i can't repro this.  I did the same experiment with "SyntaxNode" in roslyn (a symbol with thousands of results).  I got the right number of searches happening and the expected results in all the tabs that were opened.  I'm thinking this is fixed at this point :)
