### ISSUE TITLE
BasicQuickInfo/CSharpQuickInfo integration tests failing on Dev15 RC.2

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#15841]
**Version Used**: 

Dev15 RC.2

**Steps to Reproduce**:

Run the BasicQuickInfo or CSharpQuickInfo integration tests.

**Expected Behavior**:

Test passes.

**Actual Behavior**:

The test fails due to a change in the Quick Info for the `System.String` type. It used to start with:

> Represents text as a series of Unicode characters.

It now starts with:

> Represents text as a sequence of UTF-16 code units.

**Comment by Pilchie** [comment]
These tests have been replaced.
