### ISSUE TITLE
BasicVenus/CSharpVenus/CSharpVenusRename integration tests fail on Dev15 RC.2

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#15844]
**Version Used**: 

Dev15 RC.2

**Steps to Reproduce**:

Run the BasicVenus, CSharpVenus, or CSharpVenusRename integration tests in Visual Studio

**Expected Behavior**:

Test passes

**Actual Behavior**:

Test fails early on while trying to add a file to a web site (take from a run of BasicRename):

> VS main window was brought to foreground.
> Started new VS and Apex Initialized
> Begin Waiting for Apex Communication
>     Executing action [12/12/2016 11:40:05 AM] SetToolsOption
> Previous option value: TextEditor > HTML > InsertTabs = False
> Setting option: TextEditor > HTML > InsertTabs = false
>     Executing action [12/12/2016 11:40:06 AM] SetFeatureOption
>     Executing action [12/12/2016 11:40:06 AM] AddProject
>     Executing action [12/12/2016 11:40:09 AM] AddItem

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.VisualStudio.Web.Application.WATemplateWizard.MakeChild(ProjectItem parent, ProjectItem child)
>    at Microsoft.VisualStudio.Web.Application.WATemplateWizard.Microsoft.VisualStudio.TemplateWizard.IWizard.ProjectItemFinishedGenerating(ProjectItem projectItem)
>    at Microsoft.VisualStudio.TemplateWizard.Wizard.EnumContentsAddItem(ProjectItems projectItems, XmlNode contentNode, String projectName, String currentFolder, String currentTargetFolder, String rootName, String templateFolderPath, String destinationRootFolderPath, String userSpecifiedDestItemPath, String projectTypeString, List`1 wizardExtensions, String rootExtension)
>    at Microsoft.VisualStudio.TemplateWizard.Wizard.Execute(Object application, Int32 hwndOwner, Object[]& ContextParams, Object[]& CustomParams, wizardResult& retval)
>    at EnvDTE.ProjectItems.AddFromTemplate(String FileName, String Name)
>    at Roslyn.VSHosting.Test.AddItemAction.Execute(TaoEngine engine) in D:\Projects\Roslyn\Closed\Hosting\Test\Actions\VisualStudio\AddItemAction.cs:line 129
>    at Tao.Engine.DebuggableActionExecutor.Execute()
>    at Tao.Engine.DefaultActionExecutor.Execute()

**Comment by CyrusNajmabadi** [comment]
These tests don't seem to exist anymore.
