### ISSUE TITLE
Unable to reference Micosoft.CodeAnalysis from .Net Core console app

### ISSUE THREAD

**Issue by vad710** [dotnet/roslyn#15843]
**Version Used**: 
I've tried both 2.0rc and 1.3.2 using vs2017

**Steps to Reproduce**:

1. Open Visual Studio 2017 RC
2. Create a new Console App (.NET Core)
3. Right-Click "Dependencies" in solution explorer, select "Manage NuGet Packages"
4. Search for "Microsoft.CodeAnalysis" v1.3.2 (or 2.0.0-rc with prerelease checked)
5. Click Install
6. Observe that the installation fails

**Expected Behavior**:
Microsoft.CodeAnalysis should be installed and referenced properly. 

**Actual Behavior**:
Microsoft.CodeAnalysis package fails to be referenced. In the output, an error representing Microsoft.Composition is displayed:

`Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)`

This error prevents Analyzers to be run on different platforms.

**Comment by Pilchie** [comment]
I believe you will need an `imports` tag to get the Microsoft.Composition package to be restored.

Tagging @ericstj - do you know if there are plans to make a version of this package that supports .NET Standard directly?

**Comment by vad710** [comment]
@Pilchie  Where would I add the `imports` tag to get this to work?

**Comment by Pilchie** [comment]
See the Imports section of https://docs.nuget.org/ndocs/schema/project.json.

**Comment by Pilchie** [comment]
Oh, interesting - with the csproj based tooling, I'm not sure how it works.  @emgarten @srivatsn Do you know?

**Comment by srivatsn** [comment]
You need to add a `<PackageTargetFallback>` property to your project. See https://github.com/NuGet/Home/wiki/PackageTargetFallback-(new-design-for-Imports)

**Comment by twsouthwick** [comment]
I believe [System.Composition](https://www.nuget.org/packages/System.Composition/) is the replacement. @weshaggard @terrajobst

**Comment by shaggygi** [comment]
I'm seeing this issue while using a .NET Core Console app and VS 2017 RC3.

**Comment by jmarolf** [comment]
This has been fixed in the new project system

**Comment by vad710** [comment]
@jmarolf where can we get info on the new project system?
