### ISSUE TITLE
CSharpWinForms integration test fails on Dev15 RC.2

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#15848]
**Version Used**: 

Dev15 RC.2

**Steps to Reproduce**:

Run the CSharpWinForms integration test on VS.

**Expected Behavior**:

Test passes.

**Actual Behavior**:

Test fails:

> VS main window was brought to foreground.
> Started new VS and Apex Initialized
> Begin Waiting for Apex Communication
>  Scenario: Add a control
>     Executing action [12/12/2016 12:37:09 PM] AddProject
>     Executing action [12/12/2016 12:37:23 PM] OpenFile
> DEBUG: found and activated window.
> DEBUG: start polling for code window
> DEBUG: polling complete
>     Executing action [12/12/2016 12:37:24 PM] WinFormsAddControl
>         Control 'SomeButton' added successfully.
>     Executing action [12/12/2016 12:37:25 PM] Build
> Waiting for Roslyn features SolutionCrawler: 12/12/2016 12:37:33 PM
> Waiting for Roslyn features ErrorList: 12/12/2016 12:37:37 PM
> Finished waiting for Roslyn features SolutionCrawler and ErrorList: 12/12/2016 12:37:37 PM
> Waiting for error list: 12/12/2016 12:37:39 PM
> Finished waiting for error list: 12/12/2016 12:37:41 PM
>     Executing action [12/12/2016 12:37:44 PM] OpenFile
> DEBUG: executed DTE command File.OpenFile.
> DEBUG: start polling for code window
> DEBUG: polling complete
>     Executing action [12/12/2016 12:37:45 PM] VerifyEditorContainsText
>     Executing action [12/12/2016 12:37:45 PM] VerifyEditorContainsText
>     Executing action [12/12/2016 12:37:45 PM] CloseSolution
>  Scenario: Add a Click() Handler
>     Executing action [12/12/2016 12:37:45 PM] AddProject
>     Executing action [12/12/2016 12:37:47 PM] OpenFile
> DEBUG: found and activated window.
> DEBUG: start polling for code window
> DEBUG: polling complete
>     Executing action [12/12/2016 12:37:49 PM] WinFormsAddControl
> 
> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index
>    at System.Collections.ArrayList.get_Item(Int32 index)
>    at Microsoft.VisualStudio.Design.Serialization.CodeDom.MergedCodeDomGenerator.get_PrimaryCodeGenerator()
>    at Microsoft.VisualStudio.Design.Serialization.CodeDom.MergedCodeDomGenerator.ValidateIdentifier(String value)
>    at System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.System.ComponentModel.Design.Serialization.INameCreationService.ValidateName(String name)
>    at System.ComponentModel.Design.DesignerHost.CreateSite(IComponent component, String name)
>    at System.ComponentModel.Container.Add(IComponent component, String name)
>    at System.ComponentModel.Design.DesignerHost.PerformAdd(IComponent component, String name)
>    at System.ComponentModel.Design.DesignerHost.System.ComponentModel.Design.IDesignerHost.CreateComponent(Type componentType, String name)
>    at Roslyn.VSHosting.Test.WinFormsAddControlAction.Runner.Run(InProcessAPI inProcessAPI) in D:\Projects\Roslyn\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\WinForms\WinFormsAddControlAction.cs:line 65
>    at Roslyn.VSHosting.Test.WinFormsDesignerAction`1.Run(Object[] args) in D:\Projects\Roslyn\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\WinForms\WinFormsDesignerAction.cs:line 61
>    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments)

**Comment by jmarolf** [comment]
Ported in https://github.com/dotnet/roslyn/pull/17226
