### ISSUE TITLE
BasicWinForms integration test fails on Dev15 RC.2

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#15845]
**Version Used**: 

Dev15 RC.2

**Steps to Reproduce**:

Run the BasicWinForms integration test on Visual Studio.

**Expected Behavior**:

Test passes.

**Actual Behavior**:

A "Go to Definition" action seems to fail:

> VS main window was brought to foreground.
> Started new VS and Apex Initialized
> Begin Waiting for Apex Communication
>  Scenario: Test My IntelliSense
>     Executing action [12/12/2016 11:52:28 AM] AddProject
>     Executing action [12/12/2016 11:53:16 AM] OpenFile
> DEBUG: executed DTE command File.OpenFile.
> DEBUG: start polling for code window
> DEBUG: polling complete
>     Executing action [12/12/2016 11:53:21 AM] SetEditorText
>     Executing action [12/12/2016 11:53:30 AM] PlaceCursor
>     Executing action [12/12/2016 11:53:32 AM] SendKeys
>     Executing action [12/12/2016 11:53:40 AM] VerifyCompletionList
>     Executing action [12/12/2016 11:53:42 AM] SendKeys
>     Executing action [12/12/2016 11:53:45 AM] VerifyCompletionList
>     Executing action [12/12/2016 11:53:45 AM] CloseSolution
>  Scenario: Bug 586849 - GTD on My.Forms.FormName
>     Executing action [12/12/2016 11:53:46 AM] AddProject
>     Executing action [12/12/2016 11:53:55 AM] OpenFile
> DEBUG: executed DTE command File.OpenFile.
> DEBUG: start polling for code window
> DEBUG: polling complete
>     Executing action [12/12/2016 11:53:55 AM] SetEditorText
>     Executing action [12/12/2016 11:53:56 AM] PlaceCursor
>     Executing action [12/12/2016 11:53:56 AM] GoToDefinition
> Unexpected VS notification text: a VS dump should be available
>  - - - - - -
> Tao.Engine.Exceptions.UnexpectedResultException: Expected notification text: []
> Actual notification text: [Cannot navigate to the symbol under the caret.]
>    at Roslyn.VSHosting.Test.RoslynActions.RoslynVisualStudioAction.AfterExecute(TaoEngine engine) in D:\Projects\Roslyn\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\RoslynVisualStudioAction.cs:line 161
>    at Tao.Engine.DebuggableActionExecutor.AfterExecute()
>    at Tao.Engine.DefaultActionExecutor.AfterExecute()
> = = = = = =

**Comment by jmarolf** [comment]
Ported in https://github.com/dotnet/roslyn/pull/17431
