### ISSUE TITLE
Microsoft.DiaSymReader.Native folder ends up in project using new CSPROJ after upgrading to Microsoft.NETCore.App/1.1.0

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/roslyn#15859]
**Version Used**:
Visual Studio 2017 RC (d15rel/15.0.26009.0)

**Steps to Reproduce**: 

1. Create a new .NET Core Console application or ASP.NET Core (.NET Core) application
2. Change the project to target `netcoreapp1.1` using the property pages
3. Upgrade the package reference for `Microsoft.NETCore.App` to `1.1.0`

**Expected Behavior**:
No strange folder appears in Solution Explorer.

**Actual Behavior**:
![image](https://cloud.githubusercontent.com/assets/249088/21130920/622be3e8-c0c0-11e6-9e3b-63fb8aa76799.png)

**Comment by tmat** [comment]
We need to update to a newer version of the package: https://www.nuget.org/packages/Microsoft.DiaSymReader.Native/1.5.0-beta2-24728

**Comment by tmat** [comment]
(the problem is in the package, no in the project system)

**Comment by Pilchie** [comment]
@tmat who is "we"?  Where should this bug go?

**Comment by tmat** [comment]
dotnet SDK.

**Comment by Pilchie** [comment]
@DamianEdwards - can you file on the SDK then?

**Comment by Pilchie** [comment]
Also tagging @piotrpMSFT

**Comment by piotrpMSFT** [comment]
@tmat who will be updating the dependency version in https://github.com/dotnet/sdk?

**Comment by DamianEdwards** [comment]
Can I assume this is tracked now?

**Comment by tmat** [comment]
@srivatsn

**Comment by tmat** [comment]
I was mistaken. The package doesn't come from SDK, it actually comes from https://www.nuget.org/packages/Microsoft.NETCore.App/1.1.0. Since that package shipped already we can't change it.

**Comment by DamianEdwards** [comment]
@tmat so, how are we going to fix this issue then?

**Comment by tmat** [comment]
@DamianEdwards The project system behaves correctly. The package is incorrect, but can't be changed now. So I don't think we can fix this without shipping a new version of Microsoft.NETCore.App (1.1.1).

**Comment by Petermarcu** [comment]
@DamianEdwards , I just followed these steps in 2017 RC4 and the solution explorer issue didn't repro. Do we still need to update NetCoreApp? Can you still repro?

**Comment by Petermarcu** [comment]
ah, I see that it isn't just the solution explorer problem but the size.
