### ISSUE TITLE
Why don't you have an overload of SyntaxFactory.InterpolatedStringExpression with just contents as paramete?

### ISSUE THREAD

**Issue by MatthieuMEZIL** [dotnet/roslyn#15854]
In SyntaxFactory.IncoationExpression for example, the opening and closing parentheses are optional. 
Why stringStartToken is not in SyntaxFactory.InterpolatedStringExpression? 
Isn't it always $"?

**Comment by CyrusNajmabadi** [comment]
Couldn't it also be: "@$"?

**Comment by MatthieuMEZIL** [comment]
Correct.
However, it can still be optional IMHO

**Comment by CyrusNajmabadi** [comment]
We don't make things optional if there are multiple values it could be.

**Comment by CyrusNajmabadi** [comment]
in the case of ParenthesizedLists the OpenParen and CloseParen can be optional since we know what tokens would need to go there.

**Comment by MatthieuMEZIL** [comment]
Ok. Makes sense. Thanks
