### ISSUE TITLE
Switch "preselection" is not helpful

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15858]
IntelliSense is pre-selecting the variable that I'm switching over, which is not helpful nor allowed. What I'd rather see is the enum itself (TaskSchedulerPriority) selected.

![image](https://cloud.githubusercontent.com/assets/1103906/21129093/baf2e524-c153-11e6-8a1b-9a98cfc9def6.png)

**Comment by CyrusNajmabadi** [comment]
@rchande You fixed this right?

**Comment by rchande** [comment]
@davkean What build are you on? This should be fixed in RC2.

**Comment by davkean** [comment]
Yes it has been fixed in recent builds.
