### ISSUE TITLE
nameof expression with local context + semantic checks

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#1585]
```c#
using System;

public class Foo {
    public Foo SetOnly { set { } }
    public string S => nameof(this.SetOnly.SetOnly);
}
```
Produces compiler error:
> CS0154: The property or indexer 'Foo.SetOnly' cannot be used in this context because it lacks the get accessor

But there is no actual read usage here. Can you please clarify how `nameof` should work in cases like this?

**Comment by gafter** [comment]
We require the expression to be semantically valid, only suppressing the instance/static check on the last dot.
