### ISSUE TITLE
Diagnostic for invalid String.Format expressions

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#15856]
Make an analyzer to identify invalid `String.Format` expressions, e.g.:
```C#
String.Format("asdf {1} asdf", x.y);
```

This could help with #15758 in the future...(@pilchie and I were talking about this earlier today)

**Comment by AdamSpeight2008** [comment]
I've already implemented this @kuhlenh, have a look at [StringFormatDiagnostic](https://marketplace.visualstudio.com/items?itemName=AdamSpeight2008.StringFormatDiagnosticRoslyn). 
It does needs updating to work with the latest release of VS, any help would be appreciated. As it does (yet) provide code fixes for the issues.

**Comment by CyrusNajmabadi** [comment]
Closing as this should be handled by the runtime as they own this API and the format string rules.
