### ISSUE TITLE
Property gets unindented after pasting text

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#15865]
**Version Used**: VS2017RC

**Steps to Reproduce**:

1. Use code below
2. Copy class name (`S`)
3. Add ` : IEquatable<` between `S` and `{` (note that after typing `<`, the closing `>` isn't added by VS, this could actually be the real bug)
4. Paste `S`

**Expected Behavior**:

The `S` is pasted and nothing else changes

**Actual Behavior**:

The property is unindented.

```C#
using System;

namespace ConsoleApp {
    struct S {
        /// <summary>
        /// 
        /// </summary>
        public int P { get; set; }
    }
}
```

Before paste:
```C#
using System;

namespace ConsoleApp {
    struct S : IEquatable< {
        /// <summary>
        /// 
        /// </summary>
        public int P { get; set; }
    }
}
```

After paste:
```C#
using System;

namespace ConsoleApp {
    struct S : IEquatable<S {
        /// <summary>
        /// 
        /// </summary>
    public int P { get; set; }
    }
}
```

**Comment by Pilchie** [comment]
Note that the `>` is not inserted automatically, because that only happens if there are no more tokens on the line (unless the tokens were also automatically inserted to close previous constructs).

**Comment by CyrusNajmabadi** [comment]
Does nto repro for me.  I get:

![image](https://user-images.githubusercontent.com/4564579/217333572-00897341-069b-4960-8f63-fbc56438938e.png)
