### ISSUE TITLE
CS1574 fix doesn't try to use a namespace alias

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#15864]
**Version Used**: VS2017RC

**Steps to Reproduce**:

- Create a console app
- Enable 'XML documentation file' in the project settings
- Paste the code below
- Press Ctrl+. inside `MemoryStream`

**Expected Behavior**:

It should suggest to add `SIO.MemoryStream`

**Actual Behavior**:

It suggests to add `using System.IO;`

```C#
using SIO = System.IO;

namespace ConsoleApp
{
    class Program
    {
        /// <summary>
        /// <see cref="MemoryStream"/>
        /// </summary>
        /// <param name="args"></param>
        static void Main(string[] args)
        {
        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Closing out given lack of feedback.
