### ISSUE TITLE
[Failing Test]  CSharpSignatureHelp.xml

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15863]
System.ArgumentNullException: Value cannot be null.

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_prtest/134/console

....

System.ArgumentNullException: Value cannot be null.
20:15:18 Parameter name: source
20:15:18    at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
20:15:18    at Roslyn.Hosting.Test.Signature..ctor(ISignature actual) in d:\j\workspace\windows_vsi_p---5e702c54\Closed\Hosting\Test\Actions\Library\Signature.cs:line 20
20:15:18    at Roslyn.VSHosting.Test.VerifySignatureHelpAction.<>c.<Execute>b__12_0(Object[] args) in d:\j\workspace\windows_vsi_p---5e702c54\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\VerifySignatureHelpAction.cs:line 50
20:15:18    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments)

**Comment by Pilchie** [comment]
@tmeschter - did you see this test failing in your work to get Jenkins using RC.2?

**Comment by tmeschter** [comment]
@Pilchie I saw some failures, but it wasn't consistent. It consistently passed on my local RC.2 system, so I chalked the failures up to flakiness.

**Comment by heejaechang** [comment]
fixed by https://github.com/dotnet/roslyn/pull/15874
