### ISSUE TITLE
Context tooltip for indent guides should say more than just "else".

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15872]
Originally filed at: https://vsfeedback/comment/718711

> I like the context tooltip that shows up when I hover over an indent guide, which shows me the code context for that particular indent level.  However, when I hover over an "else" block, all it shows is "else".  It should also show the if expression that the else corresponds to.

Seems like a reasonable suggestion!

**Comment by davkean** [comment]
Clearly the milestone - @Pilchie doesn't triage bugs/features with a milestone, so this will never get assigned to anyone.

**Comment by Pilchie** [comment]
2.1 seems reasonable for when to make this change - I'll go back through all unassigned issues when we start working on 2.1.

**Comment by CyrusNajmabadi** [comment]
Closing out as this has been done.
