### ISSUE TITLE
DiagnosticIncrementalAnalyzer is not resilient to exceptional derived types of Location

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#1587]
Location is a public abstract type that anyone can implement a derived class for.  Consider what happens if the below class is written.

```C#
class ErrorLocation : Location
{
    public override LocationKind Kind
    {
        get
        {
            throw new Exception("");
        }
    }

    public override bool Equals(object obj)
    {
        throw new Exception("");
    }

    public override int GetHashCode()
    {
        throw new Exception("");
    }

    public override SyntaxTree SourceTree
    {
        get
        {
            throw new Exception("");
        }
    }

    public override TextSpan SourceSpan
    {
        get
        {
            throw new Exception("");
        }
    }

    public override IModuleSymbol MetadataModule
    {
        get
        {
            throw new Exception("");
        }
    }

    public override FileLinePositionSpan GetLineSpan()
    {
        throw new Exception("");
    }

    public override FileLinePositionSpan GetMappedLineSpan()
    {
        throw new Exception("");
    }
}
```

We do not currently guard against Location throwing an exception.  If this location is returned in something like.
```C#
context.ReportDiagnostic(Diagnostic.Create(Rule, new ErrorLocation(), namedTypeSymbol.Name));
```

An unhandled exception will be generated in [GetDiagnosticData](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer.cs,701) that will bring down the Visual Studio process.

**Comment by shyamnamboodiripad** [comment]
Good catch!

**Comment by shyamnamboodiripad** [comment]
Investigate restricting inheritance on Location (such that we can have derived types for well known location types such as SourceLocation and MetadataLocation - but no external implementations).

**Comment by shyamnamboodiripad** [comment]
@jmarolf Could you please verify?
