### ISSUE TITLE
Remove CodeBase attributes before dev15 RTM

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15875]
we have bunch of code base attributes for facades dlls which won't be needed in latest ML or RTM drop.
http://source.roslyn.io/#Roslyn.VisualStudio.Setup/AssemblyRedirects.cs,40

but needed for jenkins and old drops. we added them for now to make roslyn vsix to work with old drops. but before RTM, we should clean them up.

see related PR - https://github.com/dotnet/roslyn/pull/15874

**Comment by jasonmalinowski** [comment]
These are gone now.
