### ISSUE TITLE
Introduce local quick fix by declaring the local first

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#15879]
A minor idea for quick fix - I often want to turn a method parameter into a local variable, but I tend to always type the variable name first. It would be great if the "introduce local" quick fix could pick that up.

E.g.:
```C#
static void Main(params string[] args)
{
    Main(args[0]);
}
```
This allows you to _Introduce local for 'args[0]'_.

My usual workflow, however, is like this:
```C#
static void Main(params string[] args)
{
    string firstArg = |
    Main(args[0]);
}
```
and now I have to either switch to mouse and drag and drop the value and type `firstArg` there instead, or hit tens of keys to cut it, go back, paste it, go back and type `firstArg`. What I would find really helpful would be if the introduce local quick fix would have an option to use the unfinished `firstArg` for the selected value.

I am aware that this is a legal code if Main returned string, but that shouldn't be a problem as the quick fix is only offered when there is an argument selected.

**Comment by CyrusNajmabadi** [comment]
Not likely to ever do this.
