### ISSUE TITLE
[Failing Test] CSharpFixAllOccurrences.xml

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15883]
preview windows is not opening.

might be related to https://github.com/dotnet/roslyn/issues/15775

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_prtest/140/console

...

================================================================================
16:27:27 Dumping logs of all failed TAO tests.
16:27:27 ================================================================================
16:27:27 ================================================================================
16:27:27  Dumping log file D:\j\workspace\windows_vsi_p---ad02e19d\Open\Binaries\Release\Exes\EditorTestApp\VSIntegrationTestLogs\CSharpFixAllOccurrences.txt
16:27:27 Test: CSharpFixAllOccurrences started: 12/13/2016 4:17:58 PM
16:27:27 	Executing action [12/13/2016 4:17:58 PM] StartTarget
16:27:27 Begin Waiting for Apex Communication
16:27:27 	Executing action [12/13/2016 4:17:58 PM] SetFeatureOption
16:27:27 	Executing action [12/13/2016 4:17:58 PM] ExecuteCommand
16:27:27 	Executing action [12/13/2016 4:17:59 PM] VerifyErrorList
16:27:27 	Executing action [12/13/2016 4:18:06 PM] UnzipFile
16:27:27 	Executing action [12/13/2016 4:18:06 PM] OpenProject
16:27:27  Scenario: FixAllOccurrences in Document - Cancel
16:27:27 	Executing action [12/13/2016 4:18:07 PM] OpenFile
16:27:27 DEBUG: executed DTE command File.OpenFile.
16:27:27 DEBUG: start polling for code window
16:27:27 DEBUG: polling complete
16:27:27 	Executing action [12/13/2016 4:18:07 PM] WaitForWorkspace
16:27:27 	Executing action [12/13/2016 4:18:08 PM] PlaceCursor
16:27:27 	Executing action [12/13/2016 4:18:08 PM] VerifyCodeActions
16:27:27 	Executing action [12/13/2016 4:18:19 PM] PreviewChangesDialog
16:27:27 Button 2 clicked
16:27:27     'Cancel' button.
16:27:27 	Executing action [12/13/2016 4:18:19 PM] VerifyEditorContainsText
16:27:27  Scenario: FixAllOccurrences in Document - Apply Fix
16:27:27 	Executing action [12/13/2016 4:18:19 PM] OpenFile
16:27:27 DEBUG: executed DTE command File.OpenFile.
16:27:27 DEBUG: start polling for code window
16:27:27 DEBUG: polling complete
16:27:27 	Executing action [12/13/2016 4:18:19 PM] WaitForWorkspace
16:27:27 	Executing action [12/13/2016 4:18:19 PM] PlaceCursor
16:27:27 	Executing action [12/13/2016 4:18:19 PM] VerifyCodeActions
16:27:27 	Executing action [12/13/2016 4:18:20 PM] PreviewChangesDialog
16:27:27 Button 1 clicked
16:27:27     'Apply' button.
16:27:27 	Executing action [12/13/2016 4:18:20 PM] WaitForWorkspace
16:27:27 	Executing action [12/13/2016 4:18:20 PM] VerifyEditorContainsText
16:27:27  Scenario: FixAllOccurrences in Document - Undo
16:27:27 	Executing action [12/13/2016 4:18:20 PM] ExecuteCommand
16:27:27 	Executing action [12/13/2016 4:18:20 PM] WaitForWorkspace
16:27:27 	Executing action [12/13/2016 4:18:20 PM] OpenFile
16:27:27 DEBUG: executed DTE command File.OpenFile.
16:27:27 DEBUG: start polling for code window
16:27:27 DEBUG: polling complete
16:27:27 	Executing action [12/13/2016 4:18:21 PM] WaitForWorkspace
16:27:27 	Executing action [12/13/2016 4:18:21 PM] VerifyEditorContainsText
16:27:27  Scenario: FixAllOccurrences in Solution - Apply Fix
16:27:27 	Executing action [12/13/2016 4:18:21 PM] OpenFile
16:27:27 DEBUG: executed DTE command File.OpenFile.
16:27:27 DEBUG: start polling for code window
16:27:27 DEBUG: polling complete
16:27:27 	Executing action [12/13/2016 4:18:21 PM] WaitForWorkspace
16:27:27 	Executing action [12/13/2016 4:18:21 PM] PlaceCursor
16:27:27 	Executing action [12/13/2016 4:18:21 PM] VerifyCodeActions
16:27:27 	Executing action [12/13/2016 4:18:30 PM] PreviewChangesDialog
16:27:27 Button 1 clicked
16:27:27     'Apply' button.
16:27:27  Scenario: FixAllOccurrences in Solution - Verify error list after applying fix
16:27:27 	Executing action [12/13/2016 4:18:34 PM] ExecuteCommand
16:27:27 	Executing action [12/13/2016 4:18:34 PM] VerifyErrorList
16:27:27 Verifying error list content against the baseline: Closed\Test\Solutions\Newtonsoft.Json\Newtonsoft.Json\ErrorLog_After_FixAll_PrefixWithThis.json
16:27:27  Scenario: FixAllOccurrences in Solution - Verify document contents after applying fix
16:27:27 	Executing action [12/13/2016 4:18:53 PM] OpenFile
16:27:27 DEBUG: executed DTE command File.OpenFile.
16:27:27 DEBUG: start polling for code window
16:27:27 DEBUG: polling complete
16:27:27 	Executing action [12/13/2016 4:18:53 PM] WaitForWorkspace
16:27:27 	Executing action [12/13/2016 4:18:53 PM] VerifyEditorContainsText
16:27:27 	Executing action [12/13/2016 4:18:53 PM] OpenFile
16:27:27 DEBUG: executed DTE command File.OpenFile.
16:27:27 DEBUG: start polling for code window
16:27:27 DEBUG: polling complete
16:27:27 	Executing action [12/13/2016 4:18:53 PM] WaitForWorkspace
16:27:27 	Executing action [12/13/2016 4:18:53 PM] VerifyEditorContainsText
16:27:27 	Executing action [12/13/2016 4:18:53 PM] OpenFile
16:27:27 DEBUG: executed DTE command File.OpenFile.
16:27:27 DEBUG: start polling for code window
16:27:27 DEBUG: polling complete
16:27:27 	Executing action [12/13/2016 4:18:53 PM] WaitForWorkspace
16:27:27 	Executing action [12/13/2016 4:18:53 PM] VerifyEditorContainsText
16:27:27  Scenario: FixAllOccurrences in Solution - Remove this qualification
16:27:27 	Executing action [12/13/2016 4:18:54 PM] OpenFile
16:27:27 DEBUG: executed DTE command File.OpenFile.
16:27:27 DEBUG: start polling for code window
16:27:27 DEBUG: polling complete
16:27:27 	Executing action [12/13/2016 4:18:54 PM] WaitForWorkspace
16:27:27 	Executing action [12/13/2016 4:18:54 PM] PlaceCursor
16:27:27 	Executing action [12/13/2016 4:18:54 PM] VerifyCodeActions
16:27:27 	Executing action [12/13/2016 4:19:03 PM] PreviewChangesDialog
16:27:27 --------------------------------
16:27:27 Tao.Engine.Exceptions.UnexpectedResultException`1[Roslyn.CommonToBothHosts.Test.AbstractOkCancelDialogAction]: Preview Changes dialog is expected to be open.
16:27:27    at Tao.Utilities.Extensions.ThrowUnexpectedResultException[TAction](TAction action, String message)
16:27:27    at Roslyn.CommonToBothHosts.Test.AbstractOkCancelDialogAction.VerifyDialogIsOpen(Boolean isValid) in D:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\RoslynTaoActions\Actions\Common\AbstractOkCancelDialogAction.cs:line 100
16:27:27 ================================
16:27:27 
16:27:27 
16:27:27 Saved screenshot: D:\j\workspace\windows_vsi_p---ad02e19d\Open\Binaries\Release\Exes\EditorTestApp\Screenshots\2016-12-13_16-24-04_11 - Exception System.Reflection.TargetInvocationException.png
16:27:27 --------------------------------
16:27:27 Tao.Engine.Exceptions.UnexpectedResultException`1[Roslyn.CommonToBothHosts.Test.AbstractOkCancelDialogAction]: Preview Changes dialog is expected to be open.
16:27:27    at Tao.Utilities.Extensions.ThrowUnexpectedResultException[TAction](TAction action, String message)
16:27:27    at Roslyn.CommonToBothHosts.Test.AbstractOkCancelDialogAction.VerifyDialogIsOpen(Boolean isValid) in D:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\RoslynTaoActions\Actions\Common\AbstractOkCancelDialogAction.cs:line 100
16:27:27 ================================
16:27:27 
16:27:27 
16:27:27 Saved screenshot: D:\j\workspace\windows_vsi_p---ad02e19d\Open\Binaries\Release\Exes\EditorTestApp\Screenshots\2016-12-13_16-24-04_28 - Exception System.Reflection.TargetInvocationException.png
16:27:27 	Executing action [12/13/2016 4:24:04 PM] SetFeatureOption
16:27:27 	Executing action [12/13/2016 4:24:04 PM] CloseTarget
16:27:27 Test finished: 12/13/2016 4:24:08 PM
16:27:27 	Executing action [12/13/2016 4:24:08 PM] CloseTarget
16:27:27 Closing VS. force Close = True, closeVsToFreeHandles = False
16:27:27 	  Cleared VS MEF Component Cache.
16:27:27 
16:27:27 ================================================================================
16:27:27  Dumping log file D:\j\workspace\windows_vsi_p---ad02e19d\Open\Binaries\Release\Exes\EditorTestApp\VSIntegrationTestLogs\TaoStartup.txt
16:27:27 Created screenshots folder: D:\j\workspace\windows_vsi_p---ad02e19d\Open\Binaries\Release\Exes\EditorTestApp\Screenshots
16:27:27 Saved screenshot: D:\j\workspace\windows_vsi_p---ad02e19d\Open\Binaries\Release\Exes\EditorTestApp\Screenshots\2016-12-13_16-06-07_47 - Verifying Screenshot Reliability.png
16:27:27 
16:27:27 BUILD WARNINGS for D:\j\workspace\windows_vsi_p---ad02e19d\Roslyn.sln
16:27:27 16:03:32.919   146>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(2490,5): warning MSB3305: Processing COM reference "" from path "C:\Windows\SysWOW64\stdole2.tlb". The type library importer could not convert the signature for the member 'DISPPARAMS.rgvarg'. [D:\j\workspace\windows_vsi_p---ad02e19d\Closed\Test\CompilerPerfTest\CompilerPerfTest.vbproj]
16:27:27 16:03:32.920   146>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(2490,5): warning MSB3305: Processing COM reference "" from path "C:\Windows\SysWOW64\stdole2.tlb". The type library importer could not convert the signature for the member 'DISPPARAMS.rgdispidNamedArgs'. [D:\j\workspace\windows_vsi_p---ad02e19d\Closed\Test\CompilerPerfTest\CompilerPerfTest.vbproj]
16:27:27 16:03:54.989   155>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1909,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [D:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\RoslynTaoActions\RoslynTaoActions.csproj]

**Comment by Pilchie** [comment]
Can you look at re-enabling, since #15775 is fixed now.

**Comment by heejaechang** [comment]
@Pilchie when you say "you", who are you refering to? @to

**Comment by heejaechang** [comment]
wrong button sorry. saw that @Pilchie assigned the bug to @tmeschter

**Comment by Pilchie** [comment]
Has this been ported?

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving out.

**Comment by CyrusNajmabadi** [comment]
This test doesn't exist anymore.
