### ISSUE TITLE
compiler does not register code pages provider 

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn#15888]
See dotnet/corefx#10054. Once we get roslyn satellites in CLI, we'll get bad output for text outside the ASCII range unless the user has set their console code page to 65001, which is not common and may cause them other problems.

I've asked the corefx team to reconsider putting the burden on every localized command line tool for this in dotnet/corefx#14496, but we'll not likely get that in a CoreCLR that the CLI can depend upon in VS 2017.

Related: dotnet/cli#5007

**Version Used**: VS 2017  RC2

**Steps to Reproduce**:

* Use machine where CultureInfo.CurrentUICulture would pick up resources from fr/ folder, also verify that `chcp` gives 850
* Install recent VS 2017 Enterprise RC2 with .NET Core and Docker (preview) workload
* Copy C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\fr to C:\Program Files\dotnet\sdk\1.0.0-preview4-[build]\fr to mimic what a future localized CLI installation would do
* Launch developer command prompt
* `mkdir tmp`
* `cd tmp`
* `dotnet new`
* Edit Program.cs to have an error, ([space]+s) after Program 
```
using System;

class Program s
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello World!");
    }
}
```
* `dotnet restore`
* `dotnet build`

## Expected result
`dotnet build` formats errors as well as `msbuild`:

```
Program.cs(3,15): error CS1514: { attendue [D:\Temp\tmp\tmp.csproj]
Program.cs(3,15): error CS1513: } attendue [D:\Temp\tmp\tmp.csproj]
Program.cs(3,15): error CS0116: Un espace de noms ne peut pas contenir directement des membres tels que des champs ou des méthodes [D:\Temp\tmp\tmp.csproj]
Program.cs(4,1): error CS1022: Définition de type ou d'espace de noms, ou fin de fichier attendue [D:\Temp\tmp\tmp.csproj]
Program.cs(9,1): error CS1022: Définition de type ou d'espace de noms, ou fin de fichier attendue [D:\Temp\tmp\tmp.csproj]
```

## Actual result
* `dotnet build` csc error output does not handle diacritics correctly

```
Program.cs(3,15): error CS1514: { attendue [D:\Temp\tmp\tmp.csproj]
Program.cs(3,15): error CS1513: } attendue [D:\Temp\tmp\tmp.csproj]
Program.cs(3,15): error CS0116: Un espace de noms ne peut pas contenir directement des membres tels que des champs ou des m├®thodes [D:\Temp\tmp\tmp.csproj]
Program.cs(4,1): error CS1022: D├®finition de type ou d'espace de noms, ou fin de fichier attendue [D:\Temp\tmp\tmp.csproj]
Program.cs(9,1): error CS1022: D├®finition de type ou d'espace de noms, ou fin de fichier attendue [D:\Temp\tmp\tmp.csproj]
```

@jaredpar

Related: https://github.com/dotnet/cli/issues/5007

**Comment by akoeplinger** [comment]
Possibly related: https://github.com/dotnet/roslyn/issues/10785

**Comment by nguerrera** [comment]
@akoeplinger Thanks. Same root cause, same fix and easier repro. Closing as duplicate.
