### ISSUE TITLE
[Flaky Test] BasicGenerateTypeDialog.xml

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15898]
hard to find vsi runs this test not failed. almost always fail.

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_prtest/190/console

...

20:36:52 ComboBox 'AccessList' value set to 'Public'
20:36:52 --------------------------------
20:36:52 System.Windows.Automation.ElementNotAvailableException: Unrecognized error.
20:36:52    at MS.Internal.Automation.UiaCoreApi.CheckError(Int32 hr)
20:36:52    at MS.Internal.Automation.UiaCoreApi.UiaGetUpdatedCache(SafeNodeHandle hnode, UiaCacheRequest request, NormalizeState normalize, Condition customCondition)
20:36:52    at System.Windows.Automation.AutomationElement.FromHandle(IntPtr hwnd)
20:36:52    at Roslyn.VSHosting.Test.GenerateTypeDialogAction.FindDialog(Boolean retryIfNotFound) in D:\j\workspace\windows_vsi_p---cafb754d\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\GenerateTypeDialogAction.cs:line 54
20:36:52    at Roslyn.CommonToBothHosts.Test.AbstractOkCancelDialogAction.FindElementByAutomationId(String automationId, TreeScope searchScope) in D:\j\workspace\windows_vsi_p---cafb754d\Closed\Hosting\RoslynTaoActions\Actions\Common\AbstractOkCancelDialogAction.cs:line 166
20:36:52    at Roslyn.CommonToBothHosts.Test.AbstractOkCancelDialogAction.SelectComboBoxItem(String automationId, Func`2 selector, TreeScope searchScope) in D:\j\workspace\windows_vsi_p---cafb754d\Closed\Hosting\RoslynTaoActions\Actions\Common\AbstractOkCancelDialogAction.cs:line 0
20:36:52    at Roslyn.CommonToBothHosts.Test.AbstractOkCancelDialogAction.SelectComboBoxItem(String automationId, String text) in D:\j\workspace\windows_vsi_p---cafb754d\Closed\Hosting\RoslynTaoActions\Actions\Common\AbstractOkCancelDialogAction.cs:line 276
20:36:52    at Roslyn.CommonToBothHosts.Test.AbstractGenerateTypeDialogAction.SelectKind(String kind) in D:\j\workspace\windows_vsi_p---cafb754d\Closed\Hosting\RoslynTaoActions\Actions\Common\AbstractGenerateTypeDialogAction.cs:line 29

**Comment by dpoeschl** [comment]
Checked the last 20 or so builds, and this hasn't failed in any of them. Optimistically closing. Feel free to reopen if the problem shows up again.
