### ISSUE TITLE
[Flaky Test] CSharpExtractInterfaceDialog.xml

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15897]
it looks like it fails 3 of 5 runs.

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_prtest/143/console

...

19:06:58 --------------------------------
19:06:58 System.Windows.Automation.ElementNotAvailableException: Unrecognized error.
19:06:58    at MS.Internal.Automation.UiaCoreApi.CheckError(Int32 hr)
19:06:58    at MS.Internal.Automation.UiaCoreApi.UiaGetUpdatedCache(SafeNodeHandle hnode, UiaCacheRequest request, NormalizeState normalize, Condition customCondition)
19:06:58    at System.Windows.Automation.AutomationElement.FromHandle(IntPtr hwnd)
19:06:58    at Roslyn.VSHosting.Test.ExtractInterfaceDialogAction.FindDialog(Boolean retryIfNotFound) in D:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\ExtractInterfaceDialogAction.cs:line 57
19:06:58    at Roslyn.CommonToBothHosts.Test.AbstractOkCancelDialogAction.<IsDialogClosed>b__8_0() in D:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\RoslynTaoActions\Actions\Common\AbstractOkCancelDialogAction.cs:line 32
19:06:58    at Tao.Utilities.Helper.Retry[T](Func`1 action, TimeSpan delay, TimeSpan timeout) in D:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\Test\Execution\Helper.cs:line 57
19:06:58    at Roslyn.CommonToBothHosts.Test.AbstractOkCancelDialogAction.IsDialogClosed() in D:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\RoslynTaoActions\Actions\Common\AbstractOkCancelDialogAction.cs:line 32
19:06:58    at Roslyn.CommonToBothHosts.Test.AbstractOkCancelDialogAction.VerifyDialogIsOpen(Boolean isValid) in D:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\RoslynTaoActions\Actions\Common\AbstractOkCancelDialogAction.cs:line 110

**Comment by dpoeschl** [comment]
Checked the last 20 or so builds, and this hasn't happened in any of them. Optimistically closing. Feel free to reopen if the issue shows up again.
