### ISSUE TITLE
Compiler crash on simplest 1-param deconstruct statement

### ISSUE THREAD

**Issue by hi-octane** [dotnet/roslyn#15893]
**Version Used**: 
Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.26009.0 D15REL
Microsoft .NET Framework
Version 4.6.01055

**Steps to Reproduce**:
Create following console app:
```
using System;

namespace ConsoleApp
{
    class Program
    {
        class A
        {
            public int a;
            public void Deconstruct(out int b)
            {
                b = a;
            }
        }

        static void Main()
        {
            var p = new A() { a = 10 };
            var (p2) = p;//<- crashes here
        }
    }
}
```

**Expected Behavior**:
Application works.

**Actual Behavior**:
csc.exe crashes during compilation, IDE crashes if file opened.

**Comment by jcouv** [comment]
The crash is in `TupleTypeSymbol.Create` (invoked by `MakeDeconstructionConstructionStep`). 
```C#
            if (numElements <= 1)
            {
                throw ExceptionUtilities.Unreachable;
            }
```

**Comment by jcouv** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/15922. 
An error is now reported, as we do not allow 1-deconstruction at this point (why deconstruct into parts if there is only one part?).
