### ISSUE TITLE
Change how pre-processor symbols are verified

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#15900]
Today the `CSharpParseOptions` type is inconsistent with how it verifies pre-processor symbols:

- The constructor will verify all symbols are valid identifiers and throw an exception when they are not. 
- The `WithPreProcessorSymbols` method does no verification. 

This inconsistency is bad for bot the compiler and consumers of the compiler API.  After some discussion the compiler team decided to change the API in the following way:

- The `CSharpParseOptions` type will never throw on pre-processor symbols that are invalid identifiers.
- Diagnostics will be produced for invalid identifiers in the pre-processor symbols

As a part of fixing this we should examine uses like in the following PR to see if they need to be cleaned up after the change.  

https://github.com/dotnet/roslyn/pull/15798

**Comment by jaredpar** [comment]
Doesn't meet the bar now.  Will handle in next release.

**Comment by OmarTawfik** [comment]
@jaredpar filed #16913 while reading through this as well.

**Comment by OmarTawfik** [comment]
Filed #16917 as it is related to this as well.
