### ISSUE TITLE
Pattern matching spec for "switch" uses undefined non-terminal "complex_pattern"

### ISSUE THREAD

**Issue by bondsbw** [dotnet/roslyn#15904]
The non-terminal `complex_pattern` is used within the [pattern matching specification for switch statement](https://github.com/dotnet/roslyn/blob/features/patterns/docs/features/patterns.md#switch-statement), but `complex_pattern` is not defined inside the document.

Note:  this document also specifies [patterns.work.md](https://github.com/dotnet/roslyn/blob/features/patterns/docs/features/patterns.work.md) as the location of related design and implementation issues, but that document does not exist.

**Comment by gafter** [comment]
Complex patterns were cut from C# 7.
