### ISSUE TITLE
Unable to build C#/VB applications due to typo in path of ruleset

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#15902]
**Version Used**: 
ML 26013.6
**Steps to Reproduce**:
1.  Install VS with Managed Desktop Workload
2. Create a new C# Console Application.
3. Attempt to build

**Expected Behavior**:
The project builds
**Actual Behavior**:
The project fails to build due to the following error. Note the extra slash between Static Analysis Tools and Rule Sets
CSC : error CS8035: Error reading ruleset file C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Static Analysis Tools\\\Rule Sets\MinimumRecommendedRules.ruleset - File not found.

**Comment by Pilchie** [comment]
Moving to analyzers.  @srivatsn to triage.

**Comment by mavasani** [comment]
This was failing due to missing System.xml.ReaderWriter not deployed with compiler swr. Omar fixed it yesterday.

**Comment by itzshan** [comment]
Hi Mavasani,

Could you please explain a bit more about what was done exactly and how? I am also stuck in a similar problem. Appreciate your help!

Thanks.
