### ISSUE TITLE
Code behind file saved when generating event handler in web form

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#15907]
On the latest Roslyn/master:

1. Create a new Asp.NET Empty Web Site
2. Add a "Web Form" to the website
3. Start editing the web form. Within the <div> element, add a new `asp:button`. You should have typed something like:
`<asp:Button`
4. Add an event handler using intellisense. You should have typed:
'asp:Button OnClick=""` Commit the "Add New Event Handler" item. (See screenshot for example):
![image](https://cloud.githubusercontent.com/assets/3751401/21200734/2fe5e58a-c1fd-11e6-83b7-3ed062f56448.png)

After committing, note that that the code behind file for the Web Form has opened in another tab, but is already saved (no asterisk in the tab). It should be unsaved.

**Comment by rchande** [comment]
I believe this was introduced by https://github.com/dotnet/roslyn/pull/15357

**Comment by mattwar** [comment]
It was.  This is actual the exact scenario (albeit not related to web code behind that we wanted to make the change for.  It was actually the case where you have one file open, do a code fix/refactoring that creates a change in a different file that is closed.  There is no way to know that the change has not been saved unless you open the file.  In this case, the change is made in a closed file, which is then automatically opened after the change and after the save has occurred.

**Comment by mattwar** [comment]
From talking to other folks, it looks like we should change the assumption that the test has.  It is okay in this case that the document was already saved.

**Comment by Pilchie** [comment]
Urgency now since this is blocking our RI.  Please sync up with @rchande on a path forward here.

**Comment by rchande** [comment]
We've decided to update the test.
