### ISSUE TITLE
Generic type expansion + overload resolution can pick a version that causes a type error where an explicit choice exists

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/roslyn#15911]
**Version Used**: 

.NET 4 compiler through .NET Core 1.0 compiler

**Steps to Reproduce**:

Try to compile this:

    public static void program {
        void Main()
        {
            //IX((p) => p.Count, new List<string>());
            IX((x, p) => { return p.Count; }, new List<string>());
            //IX<List<string>, int>((x, p) => { return p.Count; }, new List<string>());
        }

        public delegate void IXD<T>(IXD<T> first, T second);
        public delegate U IXD<T, U>(IXD<T, U> first, T second);
        public void IX<T>(IXD<T> first, T second) {}
        public U IX<T, U>(IXD<T, U> first, T second) { return default(U);}
    }

**Expected Behavior**:

Compiles

**Actual Behavior**:

Since 'program.IXD<System.Collections.Generic.List<string>>' returns void, a return keyword must not be followed by an object expression

Cannot convert lambda expression to delegate type 'program.IXD<System.Collections.Generic.List<string>>' because some of the return types in the block are not implicitly convertible to the delegate return type

Single expression lamba does not help.

The explicit expansion of IX compiles however.

In reducing this to its minimal form the code now appears really meaningless.

The equivalent VB code builds just fine in Roslyn's VB .NET compiler.

**Comment by gafter** [comment]
This appears to be an annoying feature of C#'s overload resolution specification. It can probably be fixed in the context of #250.

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
