### ISSUE TITLE
Error with Auto-Capitalization on KeyWords after Multi-Line String in VB.NET

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15913]
Ported from https://devdiv.visualstudio.com/DevDiv/_workitems?fullScreen=true&id=216010&triage=true&_a=edit

Description: We have found that if you pause in the middle of typing a string, Visual Studio will capitalize all keywords that were previously in a string 

Repro Steps:1. Create and save a new VB.NET class file 
2. Add the following content to the file: 
Imports Microsoft.VisualBasic 

Public Class Class1 

Public Sub New() 
Dim a As String = "I have a signle line string here" 
Dim b As String = "Now I have a keyword that is lowercased in this string return false ' TEST TEST TEST" ' TEST TEST TEST 
End Sub 

End Class 

3. Delete the closing double quotes for string a 
4. Save 
5. Notice that all of the previously lower-cased keywords are changed to upper-case 
6. Close the quote 
7. Save again 
8. The keywords are still capitalized

**Comment by CyrusNajmabadi** [comment]
A primary issue here is saving while in this state.  This is because saving causes commit to happen.  

Note: in the case the customer has there is no 'unterminated' string in the file.  That's because hte comment contains a quote character.

**Comment by Pilchie** [comment]
Hmm - I'm not sure what to do about this.  I wonder if we could employ a heuristic based on the number of syntax errors in the file?

**Comment by CyrusNajmabadi** [comment]
In the example given there are no syntax errors.  That's because the string ends up consuming code without any issues, and the a quote in the comment later on ends the string.  

I'm tempted to "won't fix" this kevin.  it seems like a reasonable workaround is simply "don't hit save" while you're in the middle of these types of operations".  What do you think?

**Comment by CyrusNajmabadi** [comment]
@Pilchie Are you ok with tihs being 'by design'.  Note that there are no incomplete strings in the tree.

**Comment by CyrusNajmabadi** [comment]
@Pilchie Are you ok with this being 'by design'?

**Comment by CyrusNajmabadi** [comment]
Closing this out as by design.  @Pilchie Let me know if you think that's a problem.  Note that the workaround does not seem onerous here.  Just don't hit 'save' while in the middle of writing a *complete* string that happens to be terminated by a quote that is inside a comment.

**Comment by Pilchie** [comment]
It's true that the workaround isn't *difficult*.  The problem is that it is *highly* unlikely that the user would recognize that it is a workaround, or that they are in the sort of situation where they need to remember not to save.  Many people save unconsciously without even being aware of it.

**Comment by CyrusNajmabadi** [comment]
Ok.  Do you have any suggestions on what can be done here?  Note that in the problem description there is no unterminated string.   In order to get into this situation you need a comment which has a single quote in it, and which contains another comment marker.  That way when one comment is opened up, it immediately closes again, without generating bad code due to the remainder of hte comment being converted into a comment.

**Comment by Pilchie** [comment]
No, I don't have a solution in mind, but that doesn't mean that I think we should pretend that this isn't a problem.
