### ISSUE TITLE
Rename via a file that only differs causes an error and results in your changes being reverted

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15918]
1. File -> New -> C# Console Application (.NET Framework)
2. In Solution Explorer, rename Program.cs -> program.cs 
3. Click Yes when prompted to rename the class

Expected: 

``` C#
    class program
    {
        static void Main(string[] args)
        {
        }
    }
```

Actual: It briefly changes to above, but then something writes to the file outside of the IDE and you get:

![image](https://cloud.githubusercontent.com/assets/1103906/21211500/22e32966-c2d8-11e6-9bca-56ffd016a593.png)

Followed by:

``` C#
    class Program
    {
        static void Main(string[] args)
        {
        }
    }
```

Sometimes when I did the reverse I got a dialog about something not being in the correct state (maybe the rename state screwed up?)

**Comment by CyrusNajmabadi** [comment]
I do not repro this now.
