### ISSUE TITLE
[Flaky Test] CSharpChangeSignatureDialog.xml

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15925]
same issue as other VSI tests that require dialogbox UI manipulation.

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_prtest/166/console

...

21:19:48 System.Windows.Automation.ElementNotAvailableException: The target element cannot receive focus.
21:19:48    at MS.Internal.Automation.ElementUtil.Invoke(AutomationPeer peer, DispatcherOperationCallback work, Object arg)
21:19:48    at MS.Internal.Automation.ElementProxy.SetFocus()
21:19:48    at MS.Internal.Automation.UiaCoreApi.CheckError(Int32 hr)
21:19:48    at MS.Internal.Automation.UiaCoreApi.UiaGetUpdatedCache(SafeNodeHandle hnode, UiaCacheRequest request, NormalizeState normalize, Condition customCondition)
21:19:48    at System.Windows.Automation.AutomationElement.FromHandle(IntPtr hwnd)
21:19:48    at Roslyn.VSHosting.Test.ChangeSignatureDialogAction.FindDialog(Boolean retryIfNotFound) in D:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\ChangeSignatureDialogAction.cs:line 48
21:19:48    at Roslyn.CommonToBothHosts.Test.AbstractOkCancelDialogAction.<IsDialogClosed>b__8_0() in D:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\RoslynTaoActions\Actions\Common\AbstractOkCancelDialogAction.cs:line 32
21:19:48    at Tao.Utilities.Helper.Retry[T](Func`1 action, TimeSpan delay, TimeSpan timeout) in D:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\Test\Execution\Helper.cs:line 57
21:19:48    at Roslyn.CommonToBothHosts.Test.AbstractOkCancelDialogAction.IsDialogClosed() in D:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\RoslynTaoActions\Actions\Common\AbstractOkCancelDialogAction.cs:line 32
21:19:48    at Roslyn.CommonToBothHosts.Test.AbstractOkCancelDialogAction.AfterExecute(TaoEngine engine) in D:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\RoslynTaoActions\Actions\Common\AbstractOkCancelDialogAction.cs:line 23
21:19:48    at Tao.Engine.DebuggableActionExecutor.AfterExecute()
21:19:48    at Tao.Engine.DefaultActionExecutor.AfterExecute()
21:19:48 ================================
21:19:48

**Comment by heejaechang** [comment]
@dpoeschl David. All VSI tests that use this AutomationElement stuff are failing quite frequently. most of them saying ElementNoAvailble or found and etc.

when you fix this bug, can you make sure all other VSI tests that use these action are also fixed?

**Comment by dpoeschl** [comment]
I checked the last 20 or so runs and this didn't fail in any of them. Optimistically closing, but feel free to reopen if it crops up again. I'm going to blame ghosts in the Jenkins system.
