### ISSUE TITLE
Overload operator "*" for string and integer in C#

### ISSUE THREAD

**Issue by ygc369** [dotnet/roslyn#15923]
Please provide this overload, just like overload operator "+" for string.
if s is string, n is integer, then s*n should be a string that repeat s n times.
for example:
string s="abc"*3;  // s="abcabcabc"

**Comment by ocoster** [comment]
Is this really common enough that it requires an built in operator overload?

**Comment by mburbea** [comment]
Why not just write yourself an extension method that does that?
```csharp
public static StringExtensions{
       public static string Repeat(this string str, int times)=>
               string.Join("", Enumerable.Range(0, times).Select(x => str))
}
```

**Comment by timopomer** [comment]
C# is not a scripting-esque language. string addition is probably the most syntactic sugar we will get in that regard. everything else needs to be created by the programmer.

**Comment by gafter** [comment]
This is a request for the core libraries, not for the language compilers. See https://github.com/dotnet/coreclr for a more likely place for this feature request.

**Comment by miloush** [comment]
It's more likely you would succeed with `new string(string s, int count)` request.

@mburbea StringBuilder with fixed capacity would be a better suggestion.
