### ISSUE TITLE
Class Alias

### ISSUE THREAD

**Issue by szguoxz** [dotnet/roslyn#15928]
Really like to have a Class alias feature.

i.e.: Alias xx = cc.vv.rrr;

This is different than the using statement. The problem of using statement is: It's only effective inside the file that defines it.

What it should do is: define it in an assembly, then whatever project refer to that assembly, should automatically have that alias.

I think the price to pay for this feature is minimum.

on reflection, the type name can go back to the original class name, or make it really fancy, add a alias property to Type class. Though I think it's unnecessary.

**Comment by HaloFour** [comment]
#7451

**Comment by gafter** [comment]
Yes, this is a dup of #7451
