### ISSUE TITLE
EditorConfig and projection buffers

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#15930]
Do we correctly respect .cshtml/.vbhtml/.aspx extensions, or do we look at the secondary buffer type?  What *should* we do?

**Comment by jmarolf** [comment]
@Pilchie this is a good question.  I'll investigate

**Comment by jmarolf** [comment]
We will show an error or warning in the projection buffer if that level of severity is set, but we do not allow them to be fixed.

![image](https://cloud.githubusercontent.com/assets/9797472/21302500/434a5de6-c56c-11e6-87b4-d4a1360cf505.png)

**Comment by jmarolf** [comment]
This only happens if the user sets the severity in tools-> options.  Even if the option is set in editorconfig for `cshtml` it will not show errors or warning in the projection buffer

**Comment by jmarolf** [comment]
The question here is what do we want to happen for codestyles in general for projection buffers?

**Comment by jmarolf** [comment]
Considering we correctly apply editorconfig options to .cshtml/.vbhtml/.aspx when the analysis engine lets them through, https://github.com/dotnet/roslyn/issues/15903 should handle this case for us.
