### ISSUE TITLE
!= double.NaN should be a warning, and suggestion to fix

### ISSUE THREAD

**Issue by JPWilli** [dotnet/roslyn#15936]
**Version Used**: 
Roslyn Language Services
2.0.0.6112806

**Steps to Reproduce**:
Write code:
double a = Foo();
if (a != double.NaN)
{
Thing();
[Program.txt](https://github.com/dotnet/roslyn/files/655721/Program.txt)
}
else
{
OtherThing();
}

**Expected Behavior**:
Should see a warning on != double.NaN saying "This expression is always true, consider !IsNaN(a)", perhaps a code refactoring to actually make that change, and a warning on OtherThing(); complaining about unreachable code.

**Actual Behavior**:
None of the above occur, and the code builds without warnings.
[Program.zip](https://github.com/dotnet/roslyn/files/655724/Program.zip)

**Comment by CyrusNajmabadi** [comment]
Tagging @gafter Do we do constant analysis for doubles?  If so, ```x != <Constant-NaN>``` should always be ```true```.  And if that is equal to the constant true, then the ```else``` branch should be unreachable right?

If we don't do this, could we?

**Comment by gafter** [comment]
No, an expression that uses a variable is never a constant expression. However, we can detect this comparison and warn about it (and also `== double.NaN`) in a warning wave.

**Comment by 333fred** [comment]
There is an existing FxCop code that covers this case: CA2242. As these analyzers are shipped with .NET 5 and turned on by default, we think that effectively addresses the need here.
