### ISSUE TITLE
Using a pointer type in a deconstruction crashes the compiler

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#15934]
**Version Used**: https://github.com/dotnet/roslyn/commit/a2df65047264ed08fb3a985056085dbcee821253

**Steps to Reproduce**:
```cs
class C {
    unsafe void M() {
    	(int* x, int y) = M2();
    }
}
```
**Expected Behavior**: The compiler should not crash.

**Actual Behavior**: The compiler crashes with an invalid cast exception. See the [repro and call stack](http://tryroslyn.azurewebsites.net/#b:master/K4OwzghgZgpgBAYwDYTGOBhAUAby3AuANwHsBLAEzgFkAKASn0L0LgEhayQAXAKjgAeAGjhducAJ704AXhoAmBgG4mBAL6q4mzj14ix06osZs8bDWqA=).

**Comment by HaloFour** [comment]
What is the signature of `M2`?  Does it have a custom deconstruct method?  IIRC you can't use pointers with tuples given generic type arguments can't be pointers.

**Comment by alrz** [comment]
@HaloFour Yes, that's another issue. Here `int*` is not even parsed as a type. It is parsed as a multiplication expression. I'm looking into constraint checking (#15641) but this is new as I didn't see this before merge.

**Comment by alrz** [comment]
I ran a bisect and based on that, https://github.com/dotnet/roslyn/commit/3806ef8e37758582a2810d3bab7f316c5a71d28e is the commit causing this. Unfortunately, that's a gigantic diff.

@gafter Can you please verify? I can't continue #15641 as long as this is failing.

**Comment by gafter** [comment]
I wonder if this is fixed in https://github.com/dotnet/roslyn/pull/15641

**Comment by gafter** [comment]
@jcouv Thanks for calling this to my attention. I'll work on it.

**Comment by AlekseyTs** [comment]
LGTM
