### ISSUE TITLE
VS2017 RC "forgets" code folding/collapsing inside a solution

### ISSUE THREAD

**Issue by Unknown6656** [dotnet/roslyn#15947]
**Version Used**: 
Visual Studio Enterprise 2017 RC Build 15.0.26009.0 on Windows 10, 64Bit

**Steps to Reproduce**:

1.  Create a C#/VB/F#/C++/....-Solution (basically any language which supports the built-in CodeFolding-feature)
2.  Add some code files with "foldable code", e.g. some classes, functions etc.
3.  Fold some code segments, save the solution and close the file/solution/IDE
4.  Reopen the file(s) in question

**Expected Behavior**:
The code folding should be "remembered" by the IDE

**Actual Behavior**:
Any previous code folding is "forgotten" (except for `#region`-tags, which are always in their collapsed state)

**Comment by Pilchie** [comment]
Is this related to the structure guide stuff?  Can you take a look?

**Comment by Unknown6656** [comment]
@Pilchie : Do please excuse me, Sir, but what exactly do you mean with _"the structure guide stuff"_?

**Comment by CyrusNajmabadi** [comment]
hey @Unknown6656 "Structure guides" are these new lines that we draw in the IDE:

![image](https://cloud.githubusercontent.com/assets/4564579/21289273/8017a0fa-c44d-11e6-8a78-116500ce8649.png)

Internally we have a common infrastructure for outlining-regions as well as these new guides.

**Comment by CyrusNajmabadi** [comment]
@Unknown6656 Are you reproing this for C++ as well?  The reason i ask is that C# and C++ have totally different implementations for computing hte spans.  Whereas, we all share a common infrastructure for persisting and restoring the spans.  So if you see this in C++, it sounds like the issue is in the core layer and not in the platform layer.

**Comment by Unknown6656** [comment]
@CyrusNajmabadi @Pilchie : Yes I do see the indentation lines / structure guides.
What I have noticed, however, is that the structure guides load after ~300ms in a larger code file (>1000 Lines), and that the collapsing icons (meaning the little `+` and `-` on the side load after another ~500ms or so. After loading, however, the code remains completely unfolded, so I guess there is some kind of exception thrown during the loading process, which takes a bit of time to process and which the IDE ignores (I get no message/error/etc. and no entry inside the ActivityLog).

@CyrusNajmabadi: Concerning your question about C++: Yes, it affects all languages including C++.

**Comment by Unknown6656** [comment]
**Update:** I cannot reproduce this behaviour in the build `15.0.26014.0` .... only in `15.0.26009.0`

**Comment by CyrusNajmabadi** [comment]
I can't repro this either.  Perhaps just an interim bug that got fixed?  Let us know if you see this again.  Thanks!
