### ISSUE TITLE
Completion List incorrectly invoked on Space between 'new' and Type in ObjectCreationExpression

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#1594]
Paste the below code
```
class Program
{
    static void Main(string[] args)
    {
        var s = new A[] {
           new A  (   new $$B()),
                };
    }
}

public class A
{
    public A(B b)
    {

    }
}

public class B
{
}
```

Now keep pressing spaces at `$$`, the completion list shows up and B gets inserted inspite of B being present already. The resultant looks something like this
```
class Program
{
    static void Main(string[] args)
    {
        var s = new A[] {
           new A  (   new   B        B()),
                };
    }
}

public class A
{
    public A(B b)
    {

    }
}

public class B
{
}
```

 This is a regression from Dev12.

**Comment by rchande** [comment]
This isn't actually a regression from Dev12. Something like ```Program p = new $$Program``` will preselect Program when you type space. Dev12 has seem to have a different preselection bug where object creation preselection doesn't work within array initializers.

@Pilchie @DustinCampbell Any reason Dev12 had this behavior?

**Comment by DustinCampbell** [comment]
I thought 'new' preselection was restricted to only work when there is a specific type to the left (i.e. in a variable declarator). Am I remembering it wrong?

**Comment by rchande** [comment]
Can you verify this, @basoundr ?

**Comment by Pilchie** [comment]
This should still be closed, right?

**Comment by Pilchie** [comment]
For reference new preselection attempted to use target typing.  It handled more cases than just the right hand side of an equals, but never did array initializers.  IIRC, the places where it would infer a target type were: assignment, return, and method argument (tied to signature help overload).
