### ISSUE TITLE
Editor support for Common Intermediate Language

### ISSUE THREAD

**Issue by am11** [dotnet/roslyn#15940]
*(I am not entirely sure which team this request may belong to, I intend to move it to the appropriate repo in case this is the wrong one)*

It would be handy if OOTB `.il` support is considered in the on-going editor improvements efforts. 

MonoDevelop provides editor support for IL and it is unfortunate that VS is missing this.

`ILSupport` (https://github.com/ins0mniaque/ILSupport) extension for VS provides editor support in terms of syntax highlighting, but lacks the intellisense feature.

---

On related note, `ILSupport` is using `code` as `BaseDefinition` for IL content-type ([ref](https://github.com/ins0mniaque/ILSupport/tree/c414695/IL%20Support/Definitions.cs#L12)), is there a better choice available; some language which could roughly offset IL AST (perhaps C# or C)?

copy @spadapet (in a hope to get some insights) :)

**Comment by Pilchie** [comment]
This is probably the best place for this, but it's not something that we currently have on our radar to do.

`code` seems like a fine base definition.  It's what Roslyn [uses](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/ContentTypes/ContentTypeDefinitions.cs,96c729808caaec58).

**Comment by CyrusNajmabadi** [comment]
Definitely not doing this in roslyn.  If Runtime wants to invest here, they're welcome to with a custom LSP.
