### ISSUE TITLE
BasicMetadataAsSource/CSharpMetadataAsSource 

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#15950]
**Version Used**: 

Dev15 RC.2

**Steps to Reproduce**:

Run BasicMetadataAsSource or CSharpMetadataAsSource integration tests in ETA.

Note that you probably won't be able to run ETA on a Dev15 RC.2 system at all until it has been updated. Check with @tmeschter.

**Expected Behavior**:

Test passes.

**Actual Behavior**:

Test fails because the text of the metadata-as-source file is not what we're expecting. It looks like we're not picking up the doc comments properly. From the test results:

>  Scenario: GotoDef on int from source
>     Executing action [12/16/2016 8:22:22 AM] SetEditorText
>     Executing action [12/16/2016 8:22:23 AM] PlaceCursor
>     Executing action [12/16/2016 8:22:23 AM] GoToDefinition
> Note: ActiveTextView has lost Keyboard focus.
>     Executing action [12/16/2016 8:22:25 AM] VerifyEditorContainsText
>     Executing action [12/16/2016 8:22:25 AM] VerifyEditorContainsText
> 
> Tao.Engine.Exceptions.UnexpectedResultException`1[Roslyn.Hosting.Test.VerifyEditorContainsTextAction]: Expected substring: '\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll
> #endregion
> 
> using System.Globalization;
> using System.Runtime;
> using System.Runtime.InteropServices;
> using System.Security;
> 
> namespace System
> {
>     //
>     // Summary:
>     //     Represents a 32-bit signed integer.To browse the .NET Framework source code for
>     //     this type, see the Reference Source.
>     [ComVisible(true)]
>     public struct Int32 : IComparable, IFormattable, IConvertible, IComparable<Int32>, IEquatable<Int32>' 
> Actual text: '#region Assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> // C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll
> #endregion
> 
> using System.Globalization;
> using System.Runtime;
> using System.Runtime.InteropServices;
> using System.Security;
> 
> namespace System
> {
>     [ComVisible(true)]
>     public struct Int32 : IComparable, IFormattable, IConvertible, IComparable<Int32>, IEquatable<Int32>
>     {
>         public const Int32 MaxValue = 2147483647;
>         public const Int32 MinValue = -2147483648;

**Comment by Pilchie** [comment]
@heejaechang did you sort out the missing xml doc comments issue?

**Comment by Pilchie** [comment]
Is this still broken?  I thought we fixed the doc comment issue?

**Comment by heejaechang** [comment]
@Pilchie yes, I fixed the missing xml doc comment issue. last time I checked it passed but not sure whether it now does or not.

**Comment by tmeschter** [comment]
@Pilchie These won't actually be disabled until I merge https://github.com/dotnet/roslyn-internal/pull/1443, which should happen today.

**Comment by tmeschter** [comment]
@Pilchie And then I can see about re-enabling them.

**Comment by heejaechang** [comment]
with missing xml doc comment?

**Comment by tmeschter** [comment]
Yes.
