### ISSUE TITLE
Contents of hover lightbulb menu depend on caret position

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#1595]
I had an error in a field declaration like ```int x = T.NonExistent.GetHashCode()```.  When I mouse over ```Nonexistent``` the lightbulb offers to generate it, as expected.  However, the lightbulb may also offer to encapsulate the field in a property, depending on the caret location.  If the caret is within the field declaration, the actions are present; otherwise, they are not.  Since I triggered the menu with the mouse, depending on the caret position surprised me.

**Comment by amcasey** [comment]
FYI @shyamnamboodiripad

**Comment by shyamnamboodiripad** [comment]
The root cause here is probably #1030. We should not be returning refactorings during hover because I believe light bulb only asks us for code fixes in this case.

**Comment by srivatsn** [comment]
Fixed by #1824

**Comment by shyamnamboodiripad** [comment]
Could you please verify that this is fixed @amcasey?

**Comment by amcasey** [comment]
Seems to be based solely on the squiggle now.
