### ISSUE TITLE
[Request for help] PDB info: may valid c# method sequence points span over multiple documents?

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/roslyn#15953]
I'm doing a hobby project that uses `Microsoft.DiaSymReader` to obtain source lines for a given method.

The API for PDB assumes that sequence points of a method may span multiple files. [As example](https://github.com/dotnet/symreader/blob/84ba625453d76d2a592091ff1c947f774a79ef8e/src/Microsoft.DiaSymReader/Shared/Extensions/SymUnmanagedExtensions.Method.cs#L12):
```
        public static ISymUnmanagedDocument[] GetDocumentsForMethod(this ISymUnmanagedMethod method)
        {
            if (method == null)
            {
                throw new ArgumentNullException(nameof(method));
            }

            return NullToEmpty(GetItems((ISymEncUnmanagedMethod)method,
                (ISymEncUnmanagedMethod a, out int b) => a.GetDocumentsForMethodCount(out b),
                (ISymEncUnmanagedMethod a, int b, out int c, ISymUnmanagedDocument[] d) => a.GetDocumentsForMethod(b, out c, d)));
        }
```

Just for curiosity: is there any valid c# syntax that will result in method spanning multiple files?

As so far I can remember only
* `#line filename` directive
* code emitted via `Reflection.Emit` using the `ISymbolDocumentWriter` API
* Future code generators with `superseded();`

Partial methods have sequence points only for file with implementation, checked that.

Thanks and sorry if the question is offtopic.

**Comment by tmat** [comment]
Yes, there is:

File1.cs:
```C#
partial class C { int X = 1; }
```

File2.cs:
```C#
partial class C { int Y = 2; }
```

File3.cs:
```C#
partial class C { C(int z) { z = 3; } }
```

The constructor body spans all these files.

**Comment by ig-sinicyn** [comment]
@tmat 
Wow, forgot about this one. Good catch!

It's interesting that Roslyn emits three sequence points (or four, for debug builds), but all of them refers to same line with `C(int z) { z = 3; }`
However, it's just an implementation detail and can be changed anytime in the future.

Will add a proofcode, need time to make it less ugly:)
