### ISSUE TITLE
Add an option to disable Go To Implementation feature in Roslyn API

### ISSUE THREAD

**Issue by dungpa** [dotnet/roslyn#15958]
**Version Used**: 
Microsoft.CodeAnalysis.EditorFeatures 2.0.0-rc2

**Steps to Reproduce**:
F# language service in Visual Studio 2017 starts using Roslyn for editor features:

1. Open an F# file in Visual Studio
2. Right click and choose Go To Implementation
3. Nothing happens

**Expected Behavior**:
One should be able to opt-out and disable Go To Implementation if F# language service doesn't know how to implement Go To Implementation yet.

**Actual Behavior**:
There is no API in order to hide Go To Implementation feature.

See https://github.com/Microsoft/visualfsharp/issues/1800#issuecomment-265613399 for more details.

**Comment by CyrusNajmabadi** [comment]
Anything other than GoToImpl?

**Comment by dungpa** [comment]
Probably also 'Quick Actions and Refactoring (`Ctrl + .`)) feature if there is not a way to disable that yet.

**Comment by CyrusNajmabadi** [comment]
> Probably also 'Quick Actions and Refactoring (Ctrl + .)' feature

Hrmm... intersting.  will have to look into that.  That feature isn't controlled by us.

**Comment by CyrusNajmabadi** [comment]
Ok, i have a fix out for the 'quick actions' menu item.  Anything else?

**Comment by dungpa** [comment]
After checking other menu items, I think that's all for now. Thanks for the quick turn around.

**Comment by CyrusNajmabadi** [comment]
Ok, you should no longer see "Quick Actions and Refactorings".  If/when F# adds support for that, we can make it work by exporting the right set of Languages on SuggestedActionSourceProvider.

**Comment by dungpa** [comment]
Great, thanks.

**Comment by saul** [comment]
@dungpa, @CyrusNajmabadi - not sure "Quick Actions and Refactorings" has been disabled? We now have a few code fixes that use this feature I think.

**Comment by cartermp** [comment]
Yep, we're now using that with some code fixes.
