### ISSUE TITLE
Visual Studio 15 Updates

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#15965]
Just a minor issue but when there's a new Visual Studio update you need to go through _hoops_ and I feel like the experience can be slightly better, maybe some steps can be removed or maybe the process can be simplified completely, currently you have to follow these steps:

1. Visual Studio notifies you that an update is available, you click to update.

2. Then the the extensions window opens, you click to update yet again.

3. Then the installer window is showing up and when you finally need to really update you have to do yet another two steps.

4. You must close Visual Studio and in order to do it you have to close the extension window first because it's a modal window and then close the main window.

5. Finally, you can really update Visual Studio.

Now, instead of going through all these steps it would be nicer if we could just jump from the notification directly to the installer, I hope it make sense.

**Comment by Pilchie** [comment]
Thanks - I've forwarded a link to this to the internal team that handles the installer/update stuff.  You might consider submitting though the submit feedback link so that others can find it on Developer Community.
