### ISSUE TITLE
PreviewPane CalculateSize() crash if global WordWrap is true

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#15973]
**Version Used**: 
Any Roslyn version

**Steps to Reproduce**:
1. In a Roslyn host other than VS set global WordWrap to true: editorOptionsFactoryService.GlobalOptions.SetOptionValue(DefaultTextViewOptions.WordWrapStyleId, WordWrapStyles.WordWrap);
2. Try to show Preview Pane e.g. by triggering Remove Unused Usings

**Expected Behavior**:
Shouldn't crash

**Actual Behavior**:

Crashes the process with ArgumentOutOfRange in PresentationCore.dll:
The parameter value must be between '0' and '3579139.40666667'.

```
 	Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLineSource.Format Line 268	C#
 	Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLineSource.FormatLineInVisualBuffer Line 164	C#
 	Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.FormatSnapshotLine Line 3246	C#
 	Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.DoAnchorLayout Line 3028	C#
 	Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.DoCompleteLayout Line 3010	C#
 	Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.InnerPerformLayout Line 2847	C#
 	Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PerformLayout Line 2764	C#
 	Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.DisplayTextLineContainingBufferPosition Line 571	C#
>	Microsoft.CodeAnalysis.Editor.Shared.Extensions.IWpfDifferenceViewerExtensions.SizeToFitHelper.CalculateSize Line 124	C#
 	Microsoft.CodeAnalysis.Editor.Shared.Extensions.IWpfDifferenceViewerExtensions.SizeToFitHelper.SnapshotDifferenceChanged Line 78	C#
 	Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent<Microsoft.VisualStudio.Text.Differencing.SnapshotDifferenceChangeEventArgs> Line 444	C#
 	Microsoft.VisualStudio.Text.Differencing.Implementation.DifferenceBuffer.PerformUpdatesOnUIThread.AnonymousMethod__0 Line 594	C#
```

The good news is that the bug only reproes if the VS Editor's global WordWrap option is set to true. This is never true in VS, but may be true in other Roslyn hosts.

The bad news is that when this bug reproes, it's really hard to figure out.

The problem is that this code here is passing double.MaxValue:
https://github.com/dotnet/roslyn/blob/273955e0736451e506366ab1bfe746150ec11435/src/EditorFeatures/Core.Wpf/IWpfDifferenceViewerExtensions.cs#L117

This is not correct (WPF text renderer won't accept widths larger than 3500000 pixels). I suggest just passing null, the editor will deal with this correctly.

If WordWrap is off, these values are never consumed. So we've basically been getting lucky all the time (and we'll stay lucky in VS where global WordWrap is unlikely to be changed). 

So the recommended fix is to just change the int.MaxValue, int.MaxValue to null, null. Because these values are always ignored anyway.

**Comment by CyrusNajmabadi** [comment]
Wow.  Nice to know :)

**Comment by CyrusNajmabadi** [comment]
@KirillOsenkov is this still an issue?  I'm amenable to just closign it out if not.  If it is still an issue, i'd rather the affected party just supply a PR here since i doubt this will rise to us fixing this.
