### ISSUE TITLE
Question: How to get package references from within analyzer

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#15977]
**Version Used**: 
Visual Studio 2017 RC, v15.0.26014.0 with NuGet version of Microsoft.CodeAnalysis 2.0.0-rc2

Is there an API to get the list of referenced packages (presumably from the compilation) from within an analyzer? The [package reference I am looking for](https://www.nuget.org/packages/JetBrains.ExternalAnnotations/) does not contain assemblies, only xml files. I would like to find the full path to its package folder, if installed.

From within my analyzer, I would like to take an optional dependency on this package. If the user added both mine and that other package to the project, my analyzer should detect that and parse the xml files from the package instead of from a system-wide folder (that may not exist for some developers working on a shared project that utilizes my analyzer).

**Comment by bkoelman** [comment]
Ideally this would work for both .NET projects (using packages.json) and csproj-based .NET Core projects (using PackageReference elements in the project file).

**Comment by Pilchie** [comment]
Tagging @srivatsn.

**Comment by srivatsn** [comment]
No package references are a project-level concept. They get resolved to dlls from within the package when they get to the compiler. The compilation has no knowledge of packages at all and so there isn't any API at the compilation level.

The only way I can think of doing this is if your analyzer marked that xml file as an additional file then it would get passed in to your analyzer and you can read it directly if it's present.

**Comment by bkoelman** [comment]
The set of xml files I want to parse is about 500, which varies over package versions. So requiring users put them in the project file is not a usable solution for me. Thanks for answering, though.
