### ISSUE TITLE
Incorrect check mark status when selecting multiple rules in solution explorer

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#1597]
I have two projects (one VB and one C#) in my solution. I added nuget references to one analyzer each in the two projects (I just created a simple 'Type name contains lowercase letters' analyzer using the Roslyn SDK templates for each language and added them as nuget references to the two projects).

For the C# project, I introduced a rule set file and changed the severity of the C# rule to error (by right clicking on the rule in solution explorer and using the 'Set Rule Set Severity' fly out menu). For the VB project, I have no rule set file.

I then selected the two rules from the two projects as shown below and opened the Set Rule Set Severity fly out menu

**Observed**:
![capture](https://cloud.githubusercontent.com/assets/10579684/6838291/ec3492c0-d313-11e4-90ba-92f1d54abe3c.PNG)

**Expected**:
Per current design, in multi-select scenarios, a check mark should be present in the menu only if all the selected rules have the same severity.

However in the above case, we display a check mark on 'Error' even though one of the selected rules is a warning and the other is an error. 

Note: I think this will also repro for a single project with two rules - one with an explicit rule set entry and another without. I *think* we have a bug where if some rule does not have an explicit entry in a rule set file, then we ignore its (default) severity when calculating the check marks.

**Comment by tmeschter** [comment]
Yes, we ignore rules that do not have an explicit setting in the rule set file.

**Comment by tmeschter** [comment]
Moving to @shyamnamboodiripad for verification.
