### ISSUE TITLE
C# Code Style Options apply to generated files

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#15971]
Currently, C# Code Style Options are applying to generated files.

For example, we have a XAML control, `GeneralOptionPageControl.xaml`. This has a generated code behind file, `GeneralOptionPageControl.g.i.cs`. If we have the options set to not use `this.`, then we get a warning for `IDE0003 - Name can be simplified` on the following code line `this.Timeout.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.OnPreviewTextInputTimeout);`.

We may need a discussion around what to do for the `.editorconfig` file, where it could be argued that `GeneralOptionPageControl.g.i.cs` should be included, as the option was specified to apply to `[*.cs]`, and not some string that excludes `*.g.i.cs` files. If we decide to have `[*.cs]` ignore generated files, then I imagine we would want to explicitly document this behavior (perhaps having another option here would be the proper route... something like `dotnet_style_applies_to_generated_files = false`)

**Comment by tannergooding** [comment]
FYI. @Pilchie, @jmarolf, @dotnet/roslyn-ide

**Comment by jasonmalinowski** [comment]
Analyzers can opt-out of what we identify as generated files. This might just be a really simple fix.

**Comment by Pilchie** [comment]
Tagging @CyrusNajmabadi and @dpoeschl - I thought this was done as part of https://github.com/dotnet/roslyn/issues/14638?

**Comment by CyrusNajmabadi** [comment]
@mavasani @heejaechang We set "context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);" for this analyzer ("AbstractQualifyMemberAccessDiagnosticAnalyzer").  Do you know why we'd be getting called back for ".g.i.cs" files?  These should be filtered out by the analysis engine, right?

**Comment by mavasani** [comment]
Interesting - these should have been filtered out by [this](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerDriver.GeneratedCodeUtilities.cs,75) code. I'll take a look.

**Comment by mavasani** [comment]
Seems like something is weird is going on with IDE analyzers here. They appear to be showing diagnostics for all the generated files (.generated.cs, .g.i.cs, etc.), however when I install FXCop analyzers, which also configure generated code analysis with flags None, they don't show up diagnostics in these generated files - identical code in non-generated files is flagged.

**Comment by mavasani** [comment]
Ah, seems like SimplifyTypeNames diagnostic analyzer doesn't configure generated code analysis: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/Diagnostics/Analyzers/CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs,31

**Comment by mavasani** [comment]
In fact, I just did a search of all references for DiagnosticAnalyzer.Initialize method in source.roslyn.io and seems like lot of IDE analyzers don't configure generated code analysis: http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/DiagnosticAnalyzer.cs,af18e1ac63bf01ca,references

We should probably write an analyzer for Roslyn.sln that flags this.

**Comment by Pilchie** [comment]
Specifically:

1. `CSharpSimplifyTypeNamesDiagnosticAnalyzer`
2. `PreferFrameworkTypeDiagnosticAnalyzerBase`
3. `VisualBasicSimplifyTypeNamesDiagnosticAnalyzer`

Are the only 3 that can show up in the error list I think.

**Comment by Pilchie** [comment]
Pulling back into RTM - we'd like to fix along with #15903.
