### ISSUE TITLE
Explicit Interface Implementation Completions should change return type

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#15989]
**Version Used**: 2017 RC Refresh

```C#
class C :IComparable{
	void IComparable.
}
```

If I select `CompareTo` from IntelliSense after the `.`, it should change `void` to `int` to match the declared return type of the interface method.

**Comment by Pilchie** [comment]
I like this suggestion, but it's not something we normally do, since it might be jarring if the cursor shifts around if the type name is long.

OTOH - maybe the right thing to do is make this completion like override completion and just insert the whole signature...

**Comment by SLaks** [comment]
@Pilchie That doesn't work, because, unlike the `override` keyword, the trigger here can only appear after the return type.

You could offer completions for explicit implementations after typing `IComparable.` with no return type, but that wouldn't be very discoverable (since there is no reason to type that).

**Comment by CyrusNajmabadi** [comment]
Unlikely to do anything here given lack of feedback.
