### ISSUE TITLE
Change Scoping on Do...While condition

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#15986]
Hi C# Team,
I wanted to propose that the scoping on the do...while condition be changed.  Plainly put, it should be able to access anything inside of the loop body.  Specifically, something like this should work:

````
            var EndDate = DateTime.Now.AddMinutes(1);

            do {
                var Today = DateTime.Now;

            } while (Today < EndDate);
````

**Comment by bbarry** [comment]
This is a breaking change:
```csharp
using System;
public class C
{
    static readonly DateTime Today = DateTime.Now;
    
    public void M()
    {
        var EndDate = DateTime.Now.AddMinutes(1);
        do
        {
            var Today = DateTime.Now;
        } while (Today < EndDate);
    }
}
```

**Comment by DavidArno** [comment]
Whilst this is indeed a breaking change, the fact that variables defined in the `do` block aren't accessible in the `while` expression is a definite design flaw of the language. But as fixing it would be a breaking change, we are stuck with it.

**Comment by jnm2** [comment]
Wait a minute- aren't you a proponent of conservative scoping anyway? Harkening back to the conversation on declaring variables in `if` conditions?

**Comment by DavidArno** [comment]
Orthogonal!

(always wanted to use that word)

Or am I a hypocrite? Not sure... 😁

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
