### ISSUE TITLE
Directives ignored by quick actions

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#15980]
**Version Used**: 2.0.0.61205

**Steps to Reproduce**:

```C#
...
    |
    #endregion

    #region MyRegion

    class MyClass { }
...
```

**Expected Behavior**: No quick actions available at the current location.

**Actual Behavior**: Move `MyClass` to file quick action available. Even if `MyRegion` is collapsed.

**Comment by Pilchie** [comment]
@kuhlenh do you wan to take a look a this along with your other caret positioning issues?

**Comment by CyrusNajmabadi** [comment]
I'll fix this.
