### ISSUE TITLE
Encapsulate field consecutive capital letters

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#15987]
(minor inconvenience)

**Version Used**: 2.0.0.61205

**Steps to Reproduce**:

```C#
public int ID;
```

**Actual Behavior**: After encapsulate field and use property:
```C#
private int iD;
public int ID { get => iD; set => iD = value; }
```

**Expected Behavior**: Depends on the code style settings, but definitely not `iD`. If a quick fix is lowering case, it should lower group of capital letters except the last one if small letters follow, i.e. _IPAddress_ should become _ipAddress_, _UI12_ should become _ui12_ etc.

(For the record, ID is not an acronym so it [shouldn't](https://msdn.microsoft.com/en-us/library/ms229043(v=vs.110).aspx#Anchor_1) be all capital.)

**Comment by jnm2** [comment]
> (For the record, ID is not an acronym so it shouldn't be all capital.)

Thank you.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
