### ISSUE TITLE
IntelliSense: Incomplete parenthetical followed by statement is treated as cast

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#15982]
**Version Used**: 2017 RC Refresh

```C#
int v = 0;
(v.T)
v.ToString();
```

Pressing Ctrl+Space on `.T` in the parentheses shows no completions, because it's parsed as a cast and `v.` does not contain any types.

This only happens if `.T` was typed before opening IntelliSense.

This violates the rule that IntelliSense should not be affected by code after the cursor, and makes it surprisingly annoying to insert code before a statement.

**Comment by gafter** [comment]
@CyrusNajmabadi FYI

**Comment by gafter** [comment]
It must be parsed as a cast because it is, syntactically speaking, a valid cast. Assigning to IDE team for investigation.

**Comment by CyrusNajmabadi** [comment]
Yup. It's valid code, so parsing as a cast is correct. It's on the IDE to do the right thing here

**Comment by Pilchie** [comment]
IIRC, we have had this issue for several releases.

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard about this from other people.  `v.` does work and shows the right list.  it's only if you have `v.T` and you explicitly try to bring up completion there.
