### ISSUE TITLE
Explicit Interface Implementation Completions show Object methods

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#15988]
**Version Used**: 2017 RC Refresh

```C#
class C : IComparable {
	int IComparable.
}
```

Pressing Ctrl+Space after the `.` will show the four methods from `object`, even though they cannot be implemented with this syntax.

**Comment by SeanFarrow** [comment]
Hi,

I'd like to get involved and fix this, but have a few questions:

I'm assuming this is in the language service. where is the best place to start in terms of looking at tests/where this sort of thing would be implemented.
@slaks Where are you pressing the "." character so I can duplicate this, sorry, I'm visually impaired and would just like to clarify.

Thanks
Sean.

**Comment by CyrusNajmabadi** [comment]
hi @SeanFarrow I believe the code in question is here: https://github.com/dotnet/roslyn/blob/master/src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceCompletionProvider.cs#L42

**Comment by SeanFarrow** [comment]
Ok, thanks.

I’ll have a look at this over the next few days, but need to sign a cla first.
Cheers
Sean.

**Comment by dpoeschl** [comment]
Hey @SeanFarrow,

In regards to your question:

> Where are you pressing the "." character so I can duplicate this, sorry, I'm visually impaired and would just like to clarify.

There's a class `C` implementing `IComparable`, and in the class the user types `int IComparable` followed by the period/dot (because they are starting to implement the interface explicitly).

Hope that helps.

**Comment by SeanFarrow** [comment]
Hi,

Ok, I’ve duplicated this and will investigate the fix, can somebody assign me please?
Cheers
Sean.

**Comment by Pilchie** [comment]
GitHub doesn't allow assigning issues to people who aren't part of the repo, so I can't assign it to you, but I've given it to @rchande to help answer questions you might have, and so someone else doesn't start on it.

**Comment by SeanFarrow** [comment]
Hi,

Do we have tests for the completion providers, I can’t seem to find them.
Cheers
Sean.

**Comment by rchande** [comment]
@SeanFarrow The tests for the Explicit Interface Completion provider are here: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExplicitInterfaceCompletionProviderTests.cs. Most C# completion providers have their corresponding tests in the same directory.

**Comment by SeanFarrow** [comment]
Hi, Thanks, I’ll take a look once I’ve upgraded resharper!

**Comment by SeanFarrow** [comment]
Hi,

What is the best way of creating a document from c# source code, I need a document to write unit tests for this feature.

**Comment by CyrusNajmabadi** [comment]
Hi Sean,

Could you clarify your question?  You shouldn't have to do much to add a new test.  If you take a look at: 
https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExplicitInterfaceCompletionProviderTests.cs  you'll see how the existing tests work. 

 You'll just need to add a new test that uses VerifyItemIsAbsentAsync to ensure that a member of 'object' is not shown.

**Comment by SeanFarrow** [comment]
Hi,

Thanks, guess I was trying to complicate things.
Cheers
Sean.

**Comment by SeanFarrow** [comment]
Hi,

After adding a unit test for this and running the test command, it appears this test is not being picked up.
Any pointers as to why?
I’ve added the XUnit Fact attribute.

**Comment by CyrusNajmabadi** [comment]
Hi Sean, can you link me to your PR?  I can pull it down and see what's up.

**Comment by SeanFarrow** [comment]
Hi Cyrus,

See:
https://github.com/dotnet/roslyn/pull/18574
I am blocked with this until we work out what’s going on—I’m sure it’s trivial!
Thanks for any help.
Cheers
Sean.

**Comment by CyrusNajmabadi** [comment]
Hey Sean,

You're missing "using System;" in your test.  As such, "IComparable" doesn't bind, and no completion is shown at all :)

**Comment by SeanFarrow** [comment]
Hi,

Ok, I don’t know how I missed that, but when you can’t see those are the sorts of things that can happen.
I’ll look at this over the weekend!
Cheers

**Comment by CyrusNajmabadi** [comment]
> but when you can’t see those are the sorts of things that can happen.

@SeanFarrow I'm sorry for the hassle!  Are there things we could do to make this easier/more understandable/less error prone?

I'm also tagging @dpoeschl who's doing a lot of work on the parts of the IDE experience to make them more accessible and who is passionate about improving things here.  We'd love to get your insight and experience to help us out here.

**Comment by SeanFarrow** [comment]
Hi,

It depends how deep your influence goes, there are definitely things that could be improved.
It’s as much about how UI automation is implemented, as much as it is the IdE, I’m happy to have a chat wit hthe relevant people/do any testing if you think that will help.

**Comment by CyrusNajmabadi** [comment]
I'll let @dpoeschl Take the reigns here. 

Specifically though, when it came to the tests was there something that made this particularly difficult to track down?   One thing we've tried to do is to make tests declarative in many cases.  so, in an example like yours, the test says "here's the code representing the user scenario, and here's what i expect (i.e. 'no GetHashCode')".  I'd def like to understand what might make it better so that it isn't hard to track down what was going wrong.

**Comment by SeanFarrow** [comment]
In this case, you can’t really do much, it’s probably as declarative as possible. Because strings are used, mainly for the method we don’t want to be available, then the excluding of namespaces won’t show up, therefore the only thing I could think of is to replace the string with a reference to GetHashCode on a type, but then that would mean type introspection to see if the GetHashCode method exists on the type, so probably more work than is worth while.
