### ISSUE TITLE
Background solution analysis does nothing on recent builds

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15993]
1. Clone at this commit:
https://github.com/davkean/roslyn-project-system/commit/f19967712d698a1a56ef1c61d31c09e556d4f63f
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (I picked yesterday's build of Roslyn - 12/18 - installed via https://dotnet.myget.org/F/roslyn/vsix/0b48e25b-9903-4d8b-ad39-d4cca196e3c7-2.1.0.6121801.vsix)
4. Turn on both C# and VB Full Solution Analysis
5. Wait for ... to disappear from Error List

Expected: Many issues to show up in Error List under messages
Actual: Nothing - the error list is empty

6. Open src\Microsoft.VisualStudio.ProjectSystem.Managed\Collections\DictionaryEqualityComparer.cs

-Notice that the following issue shows up-

```
Severity	Code	Description	Project	File	Line	Suppression State
Message	IDE0018	Variable declaration can be inlined	Microsoft.VisualStudio.ProjectSystem.Managed	C:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\Collections\DictionaryEqualityComparer.cs	110	Active
```

This worked in previous builds.

**Comment by davkean** [comment]
Manish, you are looking at this right? @srivatsn is this going to be fixed for RC3?

**Comment by mavasani** [comment]
I'll take a look now.. I was working on Package property page fixes, but this seems more urgent..

**Comment by mavasani** [comment]
@heejaechang Is this related to the other error list/diagnostics issues you are investigating?

**Comment by heejaechang** [comment]
@mavasani this seems related to this https://github.com/dotnet/roslyn/pull/16226

but not 100% sure. but right now OOP is busted due to the bug above.

**Comment by mavasani** [comment]
Verified this doesn't repro after syncing to Heejae's branch https://github.com/dotnet/roslyn/pull/16416 and opening the solution in dev hive.
