### ISSUE TITLE
Explicit Interface Implementation should show completions for interface type parameterizations

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#15990]
**Version Used**: 2017 RC Refresh

```C#
interface IBase<T> {
	int M();
}

class C : IBase<string>, IBase<double> {
	int IBase<
}

```

After the (final) `<`, you should show IntelliSense completions for every parameterization of this interface implemented by the class (which may include nested type parameters).

**Comment by CyrusNajmabadi** [comment]
Unlikely to do anything here given lack of feedback.
