### ISSUE TITLE
Live Unit Tests adds a menu item *above* Open in Solution Explorer

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15995]
Can we move this menu item:

![image](https://cloud.githubusercontent.com/assets/1103906/21297693/523cf874-c5d8-11e6-8289-76844f45db8a.png)

There's no way this is more important/or used more than Open/Open With/View Code and View Designer.

**Comment by ManishJayaswal** [comment]
@KevinH-MS @shyamnamboodiripad @genlu - not sure what change caused this in 15.6. We should definitely fix this. I have created a clone of this issue in LUT repo. 
(https://github.com/dotnet/testimpact/issues/2573)

**Comment by ManishJayaswal** [comment]
Apparently this has always been like this. We should still fix this.
