### ISSUE TITLE
Cannot navigate to certain symbols within Microsoft.VisualBasic.dll

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16002]
Tried to isolate this repro, but couldn't. However, I can repro consistently in our solution.

1. Clone at this commit:
https://github.com/davkean/roslyn-project-system/commit/f19967712d698a1a56ef1c61d31c09e556d4f63f
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (I picked yesterday's build of Roslyn - 12/18)
4. Open src\Microsoft.VisualStudio.AppDesigner\Common\switches.vb
5. Navigate to line [420 in src\Microsoft.VisualStudio.AppDesigner\Common\switches.vb](https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.AppDesigner/Common/switches.vb#L420):
```
Dim ts As TimeSpan = Microsoft.VisualBasic.Now.Subtract(s_timeCodeStart)
```
6. Right-click on Now and choose **Go To Definition**

Expected: To go to the definition
Actual:
```
---------------------------
Microsoft Visual Studio
---------------------------
Cannot navigate to the symbol under the caret.
---------------------------
OK   
---------------------------
```

**Comment by Pilchie** [comment]
I suspect this is because we embed the runtime, and the symbol doesn't actually come from MS.VB.dll in this case?

**Comment by davkean** [comment]
No, embed runtime is turned off:

```
.assembly extern Microsoft.VisualBasic
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 10:0:0:0
}
```

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in these VB scenarios.
