### ISSUE TITLE
"Apply" on "Rename" window is cut-off on certain DPIs

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16004]
This is 2560 x 1600 at 125%:

![image](https://cloud.githubusercontent.com/assets/1103906/21299958/6089aafa-c5f4-11e6-9ab3-09f4d12413ee.png)

**Comment by CyrusNajmabadi** [comment]
Not repro:

![image](https://user-images.githubusercontent.com/4564579/76693535-11b2ae80-6624-11ea-8f1b-b5439f88204f.png)

I've tried a bunch of resolutions/dpis.  LMK if you still see this in any of them.  Thanks!
