### ISSUE TITLE
"Simplify type names" doesn't always appear in the Error List

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16000]
1. Clone at this commit:
https://github.com/davkean/roslyn-project-system/commit/f19967712d698a1a56ef1c61d31c09e556d4f63f
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (I picked yesterday's build of Roslyn - 12/18)
4. Open src\Microsoft.VisualStudio.AppDesigner\Common\switches.vb
5. Wait for the ... from the Error List to disappear

**Expected:** At least 10 instances of "Simplify type name" to appear in Error List, for example:

https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.AppDesigner/Common/switches.vb#L484
https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.AppDesigner/Common/switches.vb#L471
https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.AppDesigner/Common/switches.vb#L448

**Actual:** Only one instance appears:

```
IDE0003	Name can be simplified.	Microsoft.VisualStudio.AppDesigner	C:\project-system2\src\Microsoft.VisualStudio.AppDesigner\Common\switches.vb	459	Active
```

NOTE: If I move the cursor to the line, I'm offered to fix the "simplify type name".

**Comment by davkean** [comment]
May or may not be related to: https://github.com/dotnet/roslyn/issues/15993

**Comment by davkean** [comment]
Okay, may be this is me confusing how the feature works.

It appears that the case it is firing on is to remove "Me.", whereas I was expecting it to show "System.Windows.Forms.Control" examples in the Error List. I can't figure how to get these to show in the Error List, there appears to be nothing that controls this.

**Comment by davkean** [comment]
No maybe I'm wrong - some of these instances do show up in the ErrorList under IDE00012.

**Comment by Pilchie** [comment]
`this./Me` and Framework/Predefined type names analyzers are controllable in Tools\Options and should show up in the error list.  Fully qualified names, Attribute suffixes, converting static access to base type, etc, are still just "Hidden" diagnostics - the cause fading in open files, but don't appear in closed files or the error list.

**Comment by davkean** [comment]
Maybe I don't understand the by design resolution here?

**Comment by Pilchie** [comment]
Some are, yes.  For example, all IDE0012's should be, but none of the IDE0001's (like at L448 of switches.vb) should ever be in the errorlist.  Not all of the simplifications that we had in VS2015 were promoted to fully configurable code style diagnostics.  Some are still just faded text and a fix in the open file, but never show in the error list.
