### ISSUE TITLE
Can't see previous name of symbol you are renaming if its too long

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16003]
Was renaming a member, can't remember the exact wording of the previous symbol, so expected to be able to hover it to get a tooltip with the full name. However, there is no tooltip - can we add one? Or reduce the font size of this to reduce occurrence?

![image](https://cloud.githubusercontent.com/assets/1103906/21299888/df9171bc-c5f3-11e6-81fc-7cebfa7ef6c9.png)

**Comment by Pilchie** [comment]
Tooltip is a good idea.

**Comment by dpen2000** [comment]
@davkean This should be closed now as #16212 fixed

**Comment by AbhitejJohn** [comment]
Looks like this can be closed.
 /cc: @jinujoseph
