### ISSUE TITLE
Visual Studio's undo and redo button don't work for ruleset files

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#1600]
I noticed that the undo / redo buttons in VS don't work inside rule set editor. 
![capture](https://cloud.githubusercontent.com/assets/10579684/6838490/80ab8b4a-d317-11e4-8ded-3079a0284ba1.PNG)

In the above case, I have made an edit in the rule set file (as confirmed by the \* next to the file name). However, the undo button stays disabled.

If I hit ctrl + z, I am able to undo recent changes (so seems like there is an undo stack). But looks like its just not hooked up to the undo and redo buttons somehow.

**Comment by Youssef1313** [comment]
Rulesets are now deprecated. Probably there is nothing needed here now.
