### ISSUE TITLE
Our 'Building, Debugging, and Testing on Windows' documentation needs updating

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#16016]
The following doc needs to be updated to list the current requirements of the repo and should list the instructions for building the repo using Dev15 RC2.

https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md

**Comment by tannergooding** [comment]
FYI. @davkean, @jasonmalinowski, @dotnet/roslyn-infrastructure

**Comment by jcouv** [comment]
@tannergooding The instructions seem reasonably up-to-date at this point. Can we close this issue?
