### ISSUE TITLE
"Enable full solution analysis" does not persist its ON state

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#16015]
**Version Used**: d15prerel 26017.0

**Steps to Reproduce**:

1. Open the C# -> Advanced page under Tools Options
2. Check the "Enable full solution analysis" option
3. Click OK.
4. Close VS.
5. Re-open VS.
6. Open the C# -> Advanced page under Tools Options

**Expected Behavior**:
The option is still on.

**Actual Behavior**:
It's always OFF after starting VS.

**Comment by AArnott** [comment]
What makes this particularly bothersome is that #16014 makes it hard to get to this option to turn it back on every time I use VS.

**Comment by davkean** [comment]
Ah, this might explain: https://github.com/dotnet/roslyn/issues/15993.

**Comment by miloush** [comment]
There is also this "we have turned advanced features off to improve performance" notification I have seen couple of times, which apparently turns FSA off. It also suggests this setting is saved per solution, which might explain some of these issue. That's just such an unpredictable experience...

**Comment by srivatsn** [comment]
@mavasani can you take a look here since @heejaechang is out?

**Comment by heejaechang** [comment]
probably due to how option work has changed.

**Comment by heejaechang** [comment]
@jasonmalinowski so this is due to RoamingVisualStudioProfileOptionPersister always fail for nullable type.

looks like settingManager.GetValueOrDefault return actual type of nullable type so, type checking always fail

**Comment by heejaechang** [comment]
@jasonmalinowski what actually happening is implicit conversion between nullable type and object where object will point directly the type nullable type is wrapping.
