### ISSUE TITLE
Renaming / deleting a linked active rule set file doesn't update CodeAnalysisRuleSet property for project

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#1601]
1. Create a project and add some analyzer references to this project.
2. Create a rule set file in the solution folder and add it as a linked file to the project. Alternately, create shared project with the rule set file and reference shared project from the above project. 
3. Set the linked ruleset file as the active rule set for the project (by editing the project file to add &lt;CodeAnalysisRuleSet&gt;..Shared\Shared.ruleset&lt;/&gt;). 
3. Now change severity of rules for the project by using the Set Rule Set Severity fly out menu under solution explorer - this works like a charm (i.e. linked rule set file is updated correctly).
4. Now rename the rule set file in VS.

**Observed**: Project file remains unchanged when I rename the file which means, all errors go back to their default severity as opposed to severities specified in the rule set file. Also if I try to open the active ruleset for the project via the Open Active Ruleset context menu item, I get the following error -

![capture2](https://cloud.githubusercontent.com/assets/10579684/7422745/11845438-ef44-11e4-8e4f-d1f75c397f79.PNG)

**Expected**: I would expect that when a rule set file is renamed in VS, we would go through all projects in VS that may be using that file (either directly or via linked file) as their active rule set and update them projects.

We have great support for the *each project has its own rule set* scenario. I think *sharing a rule set file between multiple projects* will be a common scenario and we should have better support for this scenario in VS.

**Comment by srivatsn** [comment]
We should probably ensure that there is telemetry for detecting how many projects set rulesets and how many of them are shared

**Comment by tmeschter** [comment]
@shyamnamboodiripad I can't repro this using the steps above--VS won't let me rename the file in step 5. Can you provide a couple more details?

1. In step 2, how exactly did you create the file in the solution folder? Did you right-click on the solution in Solution Explorer and select "Add | New Item...", or did you do something else?
2. In step 3, did you add the `<CodeAnalysisRuleSet>` property to a global property group, or to a configuration-specific property group? VS only properly understands this element when it is in a configuration-specific property group.

Please assign this back to me when you've had a chance to review it.

**Comment by shyamnamboodiripad** [comment]
@tmeschter In step 2, I created a folder on Disk and copied a ruleset file to it. I then created a solution folder with the same name (matching the location on Disk - although this is probably not required) and added the ruleset file via right-click->Add->Existing Item...

In step 3, I added the property to configuration-specific property groups for Debug and Release.

Below screenshot may help clarify -
![capture](https://cloud.githubusercontent.com/assets/10579684/7422665/65060a76-ef43-11e4-90c2-da0e2f6161f0.PNG)

I can still repro this. Let me know if you need more details.

**Comment by shyamnamboodiripad** [comment]
Ah looks like VS disallows renaming any file in a solution folder if it is being used as a linked file in some project in the solution. That explains the error you were running into above @tmeschter. I think this error may have been introduced be some recent platform change (not sure - I don't recall running into this when I tried this before).

In any case adding the ruleset as a 'linked' file is not necessary for the issue reported in the bug to repro. If you skip adding ruleset file as a linked file in step 2 above, the bug will repro.

**Comment by tmeschter** [comment]
Ah, I see. We may not be informed when renaming files that are part of the solution but not part of a project. And when we are informed, we only update the projects where the .ruleset was included as an item.

**Comment by tmeschter** [comment]
Here's what should happen:

* If a project- or solution-level .ruleset is renamed, we need to update every `CodeAnalysisRuleSet` property containing the old name in every C# and VB project--even if the .ruleset isn't a file in the project.
* If a project- or solution-level .ruleset is deleted, we need to clear every `CodeAnalysisRuleSet` property containing the name in every C# and VB project--again, even if the .ruleset isn't a file in the project.
* If a project-level .ruleset is removed, we only clear the `CodeAnalysisRuleSet` properties for that project.
* If a solution-level .ruleset is removed, we do nothing.

**Comment by tmeschter** [comment]
Note that a couple of the scenarios aren't allowed by VS to being with:

* A solution-level file can't be deleted, only removed.
* A project-level file can't be renamed if it is a linked file.

**Comment by tmeschter** [comment]
Bumping back to @shyamnamboodiripad for verification.

**Comment by shyamnamboodiripad** [comment]
@srivatsn Could you please verify this / assign to someone who can verify? I need a new build for this which won't be available until next week.
