### ISSUE TITLE
Get offered to inline a variable within an Expression tree resulting in a build error

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16028]
1. CTRL+. on `int result`

``` C#
using System;
using System.Linq.Expressions;

class Program
{
    static void Main(string[] args)
    {
        int result;
        Method(() => GetValue(out result));
    }

    public static void GetValue(out int result)
    {
        result = 0;
    }

    public static void Method(Expression<Action> expression)
    {

    }
}
```

After inlining, it results in the following build error:

```
Error	CS8198	An expression tree may not contain an out argument variable declaration.	ConsoleApp31	c:\users\davkean\documents\visual studio 2017\Projects\ConsoleApp31\ConsoleApp31\Program.cs	8	Active
```

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by davkean** [comment]
Got this assert - but this is probably because I have debug bits installed:

![image](https://cloud.githubusercontent.com/assets/1103906/21600669/442c1eba-d1d4-11e6-9d72-5c3a18265423.png)

**Comment by CyrusNajmabadi** [comment]
The assert is only saying: the refactoring introduced an error.   We use it in debug bits to help us identify areas where we want to improve the refactoring.
