### ISSUE TITLE
Get a code fix to install NuGet package/generate variable for every invalid usage on a line

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16024]
1. CTRL+. on the following line:

``` C#
    class Program
    {
        static void Main(string[] args)
        {
            value = value != null ? null : value.ToLower();
        }
     }
````

![image](https://cloud.githubusercontent.com/assets/1103906/21335450/21e02daa-c6b3-11e6-9ce3-1f6073eea218.png)

Not sure what you want to do here, so i'll won't propose anything, but the majority of those items on the menu all do the same thing.

**Comment by Pilchie** [comment]
@CyrusNajmabadi any ideas here?

**Comment by Pilchie** [comment]
Or @kuhlenh @DustinCampbell

**Comment by CyrusNajmabadi** [comment]
Sure.  Isn't this what EquivalenceKeys are for?

**Comment by CyrusNajmabadi** [comment]
@kuhlenh As i've mentioned before, i hate the design of litebulbs that they show all the fixes on a line.  I really think we should change things so that they show the fixes for the fix-spans the caret is on *or* the closest fix-spans if the caret isn't on any of them.

**Comment by kuhlenh** [comment]
I believe @CyrusNajmabadi has a fix for this.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/16617
