### ISSUE TITLE
AddImport diagnostic doesn't offer to add a reference if namespace is present

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#16022]
**Version Used**: 2017 RC Refresh

**Steps to Reproduce**:

1. Create a Class Library with public type `A.B`
2. Create a second project that does not reference it.
3. Add a source file to the second project with `using A;` and `B`.

**Expected Behavior**:
Quick fix to add a reference to the Class Library project.

**Actual Behavior**:
You only show quick fixes to create `B`.
Deleting `using A;` will show the expected quick fix.

**Comment by Pilchie** [comment]
The reverse half of https://github.com/dotnet/roslyn/issues/8730
