### ISSUE TITLE
Migrate Roslyn packages to use System.Composition instead of Microsoft.Composition

### ISSUE THREAD

**Issue by prafullbhosale** [dotnet/roslyn#16040]
Having a dependency on `Microsoft.Composition` requires the project to have 
```xml
<PackageTargetFallback>portable-net45+win8</PackageTargetFallback>
```
(`imports` in the project.json world)

`System.Composition` is the new package for MEF2 and is a replacement for `Microsoft.Composition`
https://www.nuget.org/packages/System.Composition

cc @srivatsn @davidfowl

**Comment by Pilchie** [comment]
Can we do this soon so that there is time to react in other parts of the stack?

**Comment by pranavkm** [comment]
Any idea when this would be addressed?

**Comment by jmarolf** [comment]
@pranavkm there is a surprising amount of work that needs to be changed on the VS side, but I hope to get this done this week.

**Comment by JunTaoLuo** [comment]
👀

**Comment by JunTaoLuo** [comment]
Any updates on this?

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/roslyn/pull/19754

**Comment by prafullbhosale** [comment]
@jmarolf any ideas on when this planned for release and with what version? 

cc @mlorbetske

**Comment by jmarolf** [comment]
@prafullbhosale I believe the first nuget packages to have this change will be `2.3-beta3` .  You can try out the packages from [myget](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis/2.3.0-dev-61716-04) today to verify.
