### ISSUE TITLE
Lots of false errors in IDE

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn#16042]
**Version Used**: 
VS 2017 RC2

**Steps to Reproduce**:

1. Check out the following commit from Rx.NET: https://github.com/Reactive-Extensions/Rx.NET/tree/618817a75b466734f100b27f1ee74d5e2a54c46a
2. Load Rx.NET/Source/System.Reactive.sln
3. Compile and see it succeed
4. Open up ObservableQuery.cs and see lots of false errors.

**Expected Behavior**:
No false errors.

**Actual Behavior**:

Lots of errors like these:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'ObservableQuery<TSource>.ObservableRewriter.FindObservableMethod(MethodInfo, IList<Expression>)' and 'ObservableQuery<TSource>.ObservableRewriter.FindObservableMethod(MethodInfo, IList<Expression>)'	System.Reactive(net45), System.Reactive(net46), System.Reactive(netstandard1.3), System.Reactive(uap10.0)	C:\dev\RxNET\Rx.NET\Source\System.Reactive.Providers\Reactive\ObservableQuery.cs	294	Active

Note this is all in a single project that's multi-targeting. There is no ambiguity.

**Comment by onovotny** [comment]
It appears to be parsing things multiple times.

![](https://pbs.twimg.com/media/C0KwalRUUAAxkhO.jpg:large)

**Comment by davkean** [comment]
This looks like: https://github.com/dotnet/roslyn-project-system/issues/986

**Comment by onovotny** [comment]
@davkean could be...wasn't sure since I saw the drop down duplicates too.

**Comment by davkean** [comment]
Going to dup this in lieu of the one over in project system.

**Comment by davkean** [comment]
We've submitted a fix for this - should be in the next public preview.
