### ISSUE TITLE
Predefined type preference for XML documentation

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#16059]
**Version Used**: 2.0.0.61213

By which predefined type preference setting is `<see cref="UInt32" />` judged? Either way, I think there should be a separate setting for usage in XML comments.

**Comment by gafter** [comment]
I don't understand the question.

**Comment by miloush** [comment]
Sorry. The Text Editor > C# > Code Style > General has two options for _predefined type preferences_:

- for locals, parameters and members
- for member access expressions

I am getting IDE0013 _Name can be simplified_ on `<see cref="UInt32" />`. The question is which of the two settings above influence the IDE0013 in this case.

**Comment by Pilchie** [comment]
I remember @balajikris debating this, but I don't remember what we came up with as the answer.

**Comment by balajikris** [comment]
It's judged by the latter option "for member access expressions". There are detailed notes in the source code as to why that's the case. I vaguely recall filing an IDE issue for this, so it's possible there's a dupe bug for this.
