### ISSUE TITLE
Should Inner Classes show up in the BaseList?

### ISSUE THREAD

**Issue by janvanderhaegen** [dotnet/roslyn#16051]
Should a nested class (inner class) show up in the outer class' ClassDeclaration's BaseList?

**Version Used**:  Nuget 1.2.0.0, DLL 1.2.1

**Steps to Reproduce**:
Suppose I have this Outer class with a nested Inner class
```
public class Outer : SomeBaseClass, ISomeInterface{
    public class Inner { }
}
```
Then, I loop to find all ClassDeclarations: 
```
            foreach (var project in projects)
            {
                foreach (var doc in project.Documents)
                {
                    if (!doc.SupportsSyntaxTree)
                        continue; 
                    var tree = await doc.GetSyntaxTreeAsync();
                    var root = tree.GetRoot();
                    var classNodes = root
                        .DescendentNodes()
                        .OfType<ClassDeclarationSyntax>();
                    }
               }
```

**Expected Behavior**:

Outer 's BaseList contains SomeBaseClass and ISomeInterface

**Actual Behavior**:
Outer 's BaseList contains SomeBaseClass, ISomeInterface and Inner

**Comment by gafter** [comment]
Since you told it not to dive into class declarations with
```cs
                        .DescendantNodes(p => !(p is ClassDeclarationSyntax))
```
why would you expect it to find the inner class declaration?

**Comment by CyrusNajmabadi** [comment]
@gafter I think the problem is this bit:

> Outer 's BaseList contains SomeBaseClass, ISomeInterface and Inner

**Comment by janvanderhaegen** [comment]
@gafter Hmm, sorry I updated the sample. There were two issues but the first one had to do with that line of code which I missed...
The real oddity though is that the inner class shows up in the BaseList of the outer class. Isn't BaseList meant to list the inheritance (super classes & interfaces) solely?

**Comment by gafter** [comment]
I tried creating the following test case for this issue, but it passes today. Please modify this test to demonstrate your issue.

``` c#
        [Fact, WorkItem(16051, "https://github.com/dotnet/roslyn/issues/16051")]
        public void ExtraBase()
        {
            var text =
@"public class Outer : SomeBaseClass, ISomeInterface{
    public class Inner { }
}
class SomeBaseClass {}
interface ISomeInterface {}";
            var comp = CreateStandardCompilation(text);
            var tree = comp.SyntaxTrees[0];
            var outer = tree.GetCompilationUnitRoot().DescendantNodes().OfType<ClassDeclarationSyntax>().First();
            Assert.Equal(2, outer.BaseList.Types.Count);
            Assert.Equal("SomeBaseClass", outer.BaseList.Types[0].ToString());
            Assert.Equal("ISomeInterface", outer.BaseList.Types[1].ToString());
            var model = comp.GetSemanticModel(tree);
            var outerType = model.GetDeclaredSymbol(outer) as INamedTypeSymbol;
            Assert.Equal("SomeBaseClass", outerType.BaseType.Name);
            Assert.Equal(1, outerType.Interfaces.Length);
            Assert.Equal("ISomeInterface", outerType.Interfaces[0].Name);
        }
```

**Comment by janvanderhaegen** [comment]
Hey @gafter ! 

I reviewed your test and it should expose the issue exactly as is. If this test passes indeed in the latest version, it's very likely the issue has now been fixed by another code checkin.  Closing issue and thank you for your help!
