### ISSUE TITLE
Visual Studio 15 Community Edition

### ISSUE THREAD

**Issue by dhusemann** [dotnet/roslyn#1606]
I know normally during the build up to a next version that the pre-releases are typically the Big Daddy of Visual Studio and not broken down by sku.  

With the open sourcing of Corefx, coreclr, Roslyn, msbuild and perhaps more, is there a chance of releasing a community edition pre release, on par with the 2013 community edition. 

Especially as yall get closer to builds working in visual studio 2015.

**Comment by Pilchie** [comment]
The decision about what SKUs get released when is bigger than the Roslyn project :smile:  Unfortunately, we can't comment about plans here, but we'll pass along the feedback about it.

Out of curiosity, what is the problem with using the Ultimate SKUs from the public CTPs?

**Comment by dhusemann** [comment]
@Pilchie For me currently, it is Size of the package,  I recently moved and currently only option for high speed is Satellite. only get 15 gig a month,  at a relatively slow 10mbs. then it drops to around 150kbs. So the smaller the package is the better.
