### ISSUE TITLE
Pattern matching crashes if lambda captures pattern variable

### ISSUE THREAD

**Issue by hi-octane** [dotnet/roslyn#16066]
**Version Used**: 
Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.26014.0 D15REL
Microsoft .NET Framework
Version 4.6.01055

**Steps to Reproduce**:
Run the following app:

```
using System.Collections.Generic;
using System.Linq;

namespace ConsoleApp2017
{
    class Program
    {
        class A
        {
        }
        
        static void Main(string[] args)
        {                           
            var dummy = new List<int>();

            switch((object)new A())
            {
                case A a:
                    {
                        dummy.Any(x => a != null);
                    }
                    break;
            }
        }
    }
}
```
**Expected Behavior**:
App just runs, no output.

**Actual Behavior**:
Null-reference on the switch statement, when trying to initialize not created instance of a hidden class <>c__DisplayClass27_0 CS$<>8__locals0;

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ConsoleApp2017.Program.Main(String[] args) in D:\Temp\ConsoleApp2017\ConsoleApp2017\Program.cs:line 16

**Comment by paulomorgado** [comment]
@gafter, why are these display classes even being used. I wasn't expecting any extra allocations when using pattern matching.

**Comment by CyrusNajmabadi** [comment]
There's a lambda that captures the pattern variable.

**Comment by paulomorgado** [comment]
Doh!

But it seems related to that.

In [my case](16180 "Switch on pattern throws NullReferenceException") I was able to [work around](16180#issuecomment-270242465) the problem by extracting the code in the `case`s to other methods.

**Comment by YaakovDavis** [comment]
Another workaround is simply assigning the pattern variable to another temp one. Change this:
```
 class C { public int A; }

    class Program
    {
        static void Main(string[] args)
        {
            switch (new C())
            {
                case C c:
                    Func<bool> f = () => c.A > 10;
                    break;
                default:
                    break;
            }
        }
    }
```

to this:

```
 class C { public int A; }

    class Program
    {
        static void Main(string[] args)
        {
            switch (new C())
            {
                case C c:
                    var rcWorkwround = c;
                    Func<bool> f = () => rcWorkwround .A > 10;
                    break;
                default:
                    break;
            }
        }
    }
```

**Comment by gafter** [comment]
@AlekseyTs Is working on making an LDM-approved change so that the extent of a case-block scoped expression variable will be the switch block. That should fix this issue as a side-effect. Leaving it open until we can verify that.

**Comment by paulomorgado** [comment]
> @AlekseyTs Is working on making an LDM-approved change so that the extent of a case-block scoped expression variable will be the switch block. That should fix this issue as a side-effect. Leaving it open until we can verify that.

Say what?

**Comment by CyrusNajmabadi** [comment]
The extent.  Not the scope.  It gives the variable a place to live that doesn't have lifetime concerns as switch cases get entered/exited.

**Comment by jcouv** [comment]
Tracked by VSO https://devdiv.visualstudio.com/DevDiv/_workitems/edit/369823
