### ISSUE TITLE
XML documentation does not offer framework types in autocomplete list

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#16060]
**Version Used**: 2.0.0.61213

**Steps to Reproduce**:

In a XML comment, type `<see cref="UInt32`

**Expected Behavior**: `UInt32` to be in the autocomplete list.

**Actual Behavior**: Only `uint` in the list.

**Comment by gafter** [comment]
Do you have a `using` for `System`?

**Comment by miloush** [comment]
Yep. And it resolves the UInt32 type, it's just not in the autocomplete list.

**Comment by rchande** [comment]
This is fixed.
