### ISSUE TITLE
XML crefs don't impact usings

### ISSUE THREAD

**Issue by RobinHood70** [dotnet/roslyn#16067]
**Version Used**: 
4.6.1 on VS 2015 (Update 3)

**Steps to Reproduce**:

1. Add unqualified cref in XML documentation not used elsewhere in the class.
2. Add a using for the cref.

```
using System;
...
/// <summary>Does the thing.</summary>
/// <exception cref="ArgumentNullException">The parameter was null.</exception>
public void MyPassthrough(string param) => Static.DoTheThing(param)
```

**Expected Behavior**:
The "using System" should be flagged as used, since ArgumentNullException references it.

**Actual Behavior**:
The "using System" is greyed out and will be removed in a Remove and Sort Usings operation.

**Comment by 0xd4d** [comment]
Have you enabled "XML documentation file" option?

**Comment by RobinHood70** [comment]
Apparently, I hadn't. I didn't realize that it would case that effect. Thanks for the tip.

**Comment by jnm2** [comment]
> Have you enabled "XML documentation file" option?

I should not have to enable that. We rely on XML documentation comments across projects in the same solution. If removing the `using` causes an error, it should not be suggested. Please fix.
