### ISSUE TITLE
Rich text/ASCII art/images in IntelliSense XML comments

### ISSUE THREAD

**Issue by chucker** [dotnet/roslyn#1607]
As previously described [over at StackOverflow](http://stackoverflow.com/questions/10294228/is-there-an-intellisense-add-in-that-allows-icons-graphics-in-xml-comments), I'd love to provide richer API documentation for our internal tools, such as mockups for what a control might look like, custom icons, etc. A Color class could show show a little swatch for predefined values; a Font class could show a sample rendering; a Control class could show a sample screenshot.

ASCII art would be a lesser, but in some cases sufficient alternative.

**Comment by CyrusNajmabadi** [comment]
Closing out as ascii art should be possible today with `<c>` and `<code>` tags.  We will respect it and render it in a monospaced font.

**Comment by ricardoboss** [comment]
Flutter does this amazingly by just interpreting the text as markdown and shows embedded images and such:
![](https://i.stack.imgur.com/DQ2XX.png)
