### ISSUE TITLE
Please allow non-public members to implicitly implement non-public interfaces

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#16089]
```cs
internal interface I
{
  void M();
}

public class C : I
{
  protected internal virtual void M() {}
}
```
In other words, `M` must not be less accessible than `I` rather than required to be public.

Currently the workaround is to explicitly implement `I ` to delegate corresponding non-public members.

Q: Should the accessibility of `C` also be taken into account?

**Comment by bondsbw** [comment]
Related: #3599

**Comment by alrz** [comment]
@bondsbw "Allow implicit implementation of internal interfaces" This is currently possible and the example suggests to add internal modifier on interface members which doesn't add up. I think it that's a little misleading.

**Comment by bondsbw** [comment]
Agreed, the issue name is misleading.

But unless I'm misunderstanding one of the proposals, they are substantially the same.  Though I believe yours goes a bit further in allowing `protected internal` instead of just `internal`.

**Comment by alrz** [comment]
@gafter I'd appreciate it if you could clarify if there is anything wrong with the suggestion. Thanks.

**Comment by gafter** [comment]
@alrz I don't think this would be a bad idea necessarily, but it has marginal value compared to many other things we could do. If you think of any proposal as starting with -100 or -1000 points, it is hard to see how the value added rises above that.

**Comment by alrz** [comment]
CLR is actually capable of implementing interface methods via even private members,

I think a syntax similar to constructor initializer would be helpful.


```cs
public class C : I
{
    protected internal virtual void M() : I.M {}
}
```

This feature does exist in VB.
