### ISSUE TITLE
extern local functions make the parser prematurely leave method scope

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#16098]
**Version Used**: a2df65047264ed08fb3a985056085dbcee821253

```C#
class C {
    public int M() {
        extern void L();
        return 2;
    }
}
```

**Expected**: 
(currently-non-existent) error "Local functions cannot be 'extern'".

**Actual**:
A whole bunch of syntax & semantic errors from the rest of the file, because the parser assumes a missing `}` before the `extern` keyword:

> 
> (1,20,1,20): error CS1513: } expected
> (3,8,3,14): error CS1519: Invalid token 'return' in class, struct, or interface member declaration
> (5,0,5,1): error CS1022: Type or namespace definition, or end-of-file expected
> (1,15,1,16): error CS0161: 'C.M()': not all code paths return a value

http://tryroslyn.azurewebsites.net/#b:master/f:r/MYGwhgzhAEDC0G8BQ1XQA4FcBGICWw0eAdgC7QCyAFAJSIpqMCmAHqUwE7HQBuA9ngAm0ADK0A3A0aoOTUpi7QATJMYBfJGqA===

**Comment by agocke** [comment]
@SLaks This is another parser trade-off. This is invalid code, so no matter what parse tree is chosen it will be invalid. There are two reasonable invalid parse trees here. First, you can choose to parse the `extern` as an invalid modifier to a local function. Second, you can choose to treat `extern` as the start of a member declaration where the user forgot a closing brace.

I'm not sure one is necessarily better than the other here, but I'm inclined to keep the current parse tree. I don't think `extern` is a common mistake users will make while defining local functions, but I think forgetting the closing brace of a method or, perhaps more importantly, writing a new incomplete method above a member with an extern declaration, is significantly more common.

I'm encouraged in my interpretation by noting that you found this by explicitly attempting to find weird parsing edge cases in C# and no one else has yet to report this issue, while a very similar issue with accessibility modifiers was reported almost immediately when people were testing simple local function cases.

**Comment by SLaks** [comment]
Yep; good point.

The only counter-argument is to help people who (incorrectly) try to write `extern` P/Invoke functions (as per #11731).

**Comment by agocke** [comment]
@SLaks If this only makes the lives of the people in that thread (including me 😄 ) a little harder, I'm OK with that.

I'm also still open to enabling the feature for real later.
