### ISSUE TITLE
SelectionValidator tests can't handle C# 7.0 code

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#16116]
Specifically the catch all test [DontCrash](https://github.com/dotnet/roslyn/blob/a73beac38d1563b2133108dab664a08d14981fa2/src/EditorFeatures/CSharpTest/ExtractMethod/SelectionValidatorTests.cs#L1333) can't handle the TestResource.AllInOneCSharpCode resource string

``` csharp
        public async Task DontCrash()
        {
            await IterateAllAsync(TestResource.AllInOneCSharpCodeVersion6);
        }
```

This was missed originally because there were two versions of TestResource.AllInOneCSharpCode:

- TestUtilities Portable: never updated, had only C# 6.0 code
- TestUtilities Desktop: updated to have C# 7.0 code

This suite was referencing the Portable version hence it was missed when we added the new code.  Once I found the duplicate strings and merged them the issue popped up.

The failure seems to be around local functions hence assigning out to @agocke.

@Pilchie for an FYI

**Comment by agocke** [comment]
Fixed by #16021
