### ISSUE TITLE
Proposal: Add attributes which run custom functions to and throw compiler errors on fail.

### ISSUE THREAD

**Issue by henrikklarup** [dotnet/roslyn#16110]
Add some way of putting attributes on different classes/enums and run custom functions for validation on compile time.
E.g.

A custom NoDublicatesAttribute could be added to enums to prevent multiple in the enum.
A custom NoImplicitValuesAttribute could be added to enums to only allow explicit value assignment the enum.

**Comment by eyalsk** [comment]
@henrikklarup Do you mean something like this #13553?

**Comment by alrz** [comment]
These are prefect use cases for analyzers.
