### ISSUE TITLE
How to use Roslyn in .Net Core, I can't reference Microsoft.Analysis via NuGet

### ISSUE THREAD

**Issue by mykge** [dotnet/roslyn#16118]
**Version Used**:  .Net Standard 1.6

**Steps to Reproduce**:

1.  Reference Microsoft.Analysis via NuGet
2.  Visual Studio 2015 Nuget Package console throw a exception

**Comment by Pilchie** [comment]
Please include the error message details, and what package and version you are using.  Microsoft.Analysis isn't a package.

**Comment by Pilchie** [comment]
Unfortunately, without more information we can't say what's happening here.
