### ISSUE TITLE
Question: Boxing on stack for function calls

### ISSUE THREAD

**Issue by edward-a** [dotnet/roslyn#16112]
According to C# documentation boxing is done on heap. What i am wondering about is whether it's a good idea in theory to allocate box on stack in case boxing is done for a function argument. And move that box to heap later only if that box gets referenced from heap. I think it would be a significant optimization for function calls with object-type arguments and the ones with variable number of arguments. Please enlighten me on this matter.

**Comment by svick** [comment]
The C# compiler does not decide how are reference types (including boxed value types) allocated, that's up to the CLR. So I think this issue belongs to the coreclr repo, not here. And that repo already has a fairly similar proposal: https://github.com/dotnet/coreclr/issues/1784.

**Comment by edward-a** [comment]
My bad, should have asked this question at coreclr. Thanks for the link to a similar proposal, will look into it.
