### ISSUE TITLE
Extra * added on the line after a block comment ends.

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#16128]
```C#
/*
class C {}
*/
```
Place the cursor at the end of the comment and press Enter.

**Expected Behavior**:
A newline.

**Actual Behavior**:
A newline plus another `*`.

Originally reported at https://developercommunity.visualstudio.com/content/problem/8316/c-multiline-comment-bug-adds-a-out-of-multiline-ar.html

**Comment by jnm2** [comment]
I always thought this was by design but yes, it's annoying. 😆

**Comment by Pilchie** [comment]
Doing it inside the comment is by design (controlled by the option at Tools\Options\Text Editor\C#\Advanced:
![image](https://cloud.githubusercontent.com/assets/312835/21534341/5361ebee-cd1a-11e6-9a08-fe5e4e1c3451.png)

but doing it after the comment is a bug.

IIRC @diryboy implemented this?

**Comment by diryboy** [comment]
Wow, I thought I fixed similar bug before, but this one is real. Looks it only happens if the caret is right next to the `*/` and also at the end of the file. I'll check what went wrong, but may take some time as I need to catch up with the changes in the repo. Thank you!

**Comment by reaction1989** [comment]
I tried to reproduce it.  It is working like a charm in VS2017RC as well as in VS2015. Or is it in a newer version of Roslyn?

**Comment by diryboy** [comment]
@reaction1989 Try delete everything in the file and type `/**/` then hit Enter

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  I get:

![image](https://github.com/dotnet/roslyn/assets/4564579/f6929ef1-f185-4e7b-a53e-dcb14597144f)
