### ISSUE TITLE
Make the IWaitIndicator service accessible to F# project system

### ISSUE THREAD

**Issue by saul** [dotnet/roslyn#16121]
**Version Used**: master

Microsoft.CodeAnalysis.Editor.Host.IWaitIndicator should be public, and not just visible to projects that can see internals of EditorFeatures.

Alternatively, please add Microsoft.VisualStudio.FSharp.ProjectSystem to the InternalsVisibleTo for this project (FSharp.Editor is already there).

**Comment by Pilchie** [comment]
Note that Roslyn's IWaitIndicator is just a pretty thin wrapper around VS's existing mechanism - see [VisualStudioWaitIndicator](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Utilities/VisualStudioWaitIndicator.cs,a5c29fef3e1bd10b).  The F# project system could probably just copy this code if it needs to.

**Comment by saul** [comment]
That's true - but if the code already exists in Roslyn and other parts of F# are using the internals of this project, it makes sense to use the code that already exists considering it's a one line change.

**Comment by Pilchie** [comment]
I'd really rather not yet another IVT for the sake of 75 lines of boiler-plate code.  They are outrageously hard to get rid of later.

**Comment by Pilchie** [comment]
And I don't want to make it public, because the Visual Studio SDK already advertises a public way to do it - which is what the implementation above does.  There is no need to add a second concept here.

**Comment by saul** [comment]
It's nearly 300 in total for WaitContext, WaitIndicator and WaitContext.Callback. Regardless, if you're against making it public or opening the internals to FSharp.ProjectSystem then no need to keep this issue open.

**Comment by Pilchie** [comment]
I'm against adding IVT on principle.  I reluctantly consent to it when the value is significant, but I don't see that here.  This is just a small bit of relatively stable utility code though.

If something significant from Roslyn is needed, then I'm happy to discuss it more in the context of the value it provides.

**Comment by saul** [comment]
For anyone looking at this (and for future reference) - [ThreadedWaitDialogHelper](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.threadedwaitdialoghelper.aspx) exists in Microsoft.VisualStudio.Shell.14.0 👍
