### ISSUE TITLE
Make IQuickInfoProvider public

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#16136]
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Extensibility/QuickInfo/IQuickInfoProvider.cs

This would be quite helpful for developers writing IDE-like scenarios (https://github.com/ashmind/mirrorsharp/issues/10).

It would also make it much easier to write extensions that provide Roslyn-aware items in Quick Info

For example:

 - Show coverage information
 - Show recorded values from last test run
 - Show `git blame` for the target symbol
 - Show NuGet info for the target symbol
 - Show platform support or internal corporate compliance rules

**Comment by CyrusNajmabadi** [comment]
tagging @mattwar

**Comment by CyrusNajmabadi** [comment]
Covered under https://github.com/dotnet/roslyn/issues/42427
