### ISSUE TITLE
warning CS0429 - not detected by csc.exe

### ISSUE THREAD

**Issue by davidjamartin** [dotnet/roslyn#16147]
**Version Used**: 
csc.exe
I have tested with these versions, the non Roslyn compilers work as expected:
Microsoft (R) Visual C# 2005 Compiler version 8.00.50727.5483
Microsoft (R) Visual C# Compiler version 4.6.1087.0

The following do not emit the warning:
Microsoft (R) Visual C# Compiler version 1.3.1.60616
Microsoft (R) Visual C# Compiler version 1.3.1.60621
Microsoft (R) Visual C# Compiler version 2.0.0.61205

**Steps to Reproduce**:
1. Create a file to produce the issue (https://msdn.microsoft.com/en-us/library/2ch1a3w5.aspx):
// CS0429.cs  
public class cs0429   
{  
    public static void Main()   
    {  
        if (false && myTest())  // CS0429  
        // Try the following line instead:  
        // if (true && myTest())  
        {  
        }  
        else  
        {  
            int i = 0;  
            i++;  
        }  
    }  
  
    static bool myTest() { return true; }  
}  

2. Build using CSC.exe
csc.exe CS0429.cs

**Expected Behavior**:
I would expect to see the following warning as per previous versions:

CS0429.cs(6,22): warning CS0429: Unreachable expression code detected

**Actual Behavior**:
The warning does not get emitted.

**Comment by SLaks** [comment]
Demo: http://tryroslyn.azurewebsites.net/#b:master/f:>ilr/A4VwRgNglgxgBDCBDAzihKAMAWATATjgG8AoOcuUSWOFAFyTpoDcB7KAEzgFkkoA7ABQBKYmQoSoAMziCpSCCgCmcAGSq4AWwCeAFSX0RogPTG4AYQDKOAuInlTcXQCdtcOgAsVU1hAisAdwEAczhofhUBeiUkDgAuO3tTaVk6ZxAVdS09AzojRIlSewoAXzglRRUi4vsBOjgoOABeOEwAbgKaqABqbo6auBLEocT6RhowVl9s/UNRIjhnJToQZ353dKU2wZIRkiA===

**Comment by gafter** [comment]
The language concept of reachability applies to statements. There is no language-defined concept of reachable expresions. It was an error that previous compilers produced this diagnostic.
