### ISSUE TITLE
Please allow ref on foreach variable in case of an array

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#16155]
```cs
foreach(ref var item in array)
{
}
```
->
```cs
for(int i = 0; i < array.Length; ++i)
{
  ref var item = ref array[i];
}
```

**Comment by jnm2** [comment]
This is genius.

**Comment by HaloFour** [comment]
I assume that `item` would be readonly?

**Comment by DavidArno** [comment]
@HaloFour,

That seems extremely unlikely, given the team's resistance to making anything read-only by default.

**Comment by alrz** [comment]
@HaloFour Since this would be only allowed for arrays, it is totally safe to be assigned. I think that's the case for `readonly ref` which doesn't exists yet.

@DavidArno It is currently readonly for non-ref case, which is a good thing. But in this case we explicitly declared it as `ref` so I don't think that would come as a surprise. Also, when it's `ref` it is already guarded against closure capture etc.

**Comment by HaloFour** [comment]
@DavidArno

> That seems extremely unlikely, given the team's resistance to making anything read-only by default.

Except for `foreach` iterator variables, which have always been readonly.  That's explicitly why I mentioned it.

**Comment by jaredpar** [comment]
In order to make that readonly we'd need to support the notion of `readonly ref`.  That is actually something we're looking into seriously for the next version of C#.

**Comment by eyalsk** [comment]
@jaredpar You mean like the next major release?

**Comment by jaredpar** [comment]
@eyalsk it will not be a part of C# 7.0.  But it is a candidate for coming out in a point release / VS update.

**Comment by eyalsk** [comment]
@jaredpar Thank you very much.

**Comment by aluanhaddad** [comment]
@alrz
> @jnm2 It is actually C++. :)

😆 😆 
It won't be until we have
```C#
foreach(ref ref var item in array) { ... }
```
[pure gold](https://channel9.msdn.com/Shows/Going+Deep/Cpp-and-Beyond-2012-Scott-Meyers-Universal-References-in-Cpp11/player#time=13m20s)

**Comment by alrz** [comment]
Moved to https://github.com/dotnet/csharplang/issues/461
