### ISSUE TITLE
Bug: Lambda parameters are incorrectly associated with tuple elements of the same name

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#16168]
**Version Used**: VS 2017 RC, 2.0.0.61104 (obtained via `csc /?` from the command line)

**Steps to Reproduce**:

1.

```cs
class RoslynBug
{
    public static void Foo()
    {
        IEnumerable<int> ints = null;

        ints.Select(x[|] => (x: x, y: x));
    }
}
```

2. Hit backspace and rename the lambda argument `x` to `z`.
3. Press Ctrl + . and select "rename 'x' to 'z'".

**Expected Behavior**: The naming of the tuple element `x` should not be affected.

```cs
class RoslynBug
{
    public static void Foo()
    {
        IEnumerable<int> ints = null;

        ints.Select(z => (x: z, y: z));
    }
}
```

**Actual Behavior**: The tuple element `x` is renamed to `z`.

```cs
class RoslynBug
{
    public static void Foo()
    {
        IEnumerable<int> ints = null;

        ints.Select(z => (z: z, y: z));
    }
}
```

**Other Notes:** I also noticed that when I place my cursor next to the first `x`, both the tuple name and the actual argument `x` are highlighted.

![roslynbug](https://cloud.githubusercontent.com/assets/9159214/21579696/78f6d654-cf8a-11e6-8724-df8c1b34c1f8.PNG)

**Comment by jamesqo** [comment]
It seems like it can happen with variables outside the lambda too. Renaming the tuple element `ints` -> `intss` in the following snippet

```
        public static void Foo()
        {
            IEnumerable<int> ints = null;

            new[] { ints }.Select(ins => (ints[|]: ins, x: 0));
        }
```

yields

```cs
        public static void Foo()
        {
            IEnumerable<int> intss = null;

            new[] { intss }.Select(ins => (intss: ins, x: 0));
        }
```

**Comment by jcouv** [comment]
@CyrusNajmabadi I'm looking around for test automation on rename refactoring. I couldn't find such a category of tests in `CSharpEditorServicesTest`. Are there such tests?

**Comment by jcouv** [comment]
@VSadov This sounds like the issue you described with tuple literal (their element location is not properly tracked, so the IDE falls back on some name matching heuristic) in https://github.com/dotnet/roslyn/issues/14600
