### ISSUE TITLE
Visual Studio 15 RC - Lost Windows

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#16172]
_Disclaimer: This is one example, I guess that there are more scenarios where this happens._

**Version Used**:  Visual Studio 15 RC

**Steps to Reproduce**:

1. Open Visual Studio.
2. Go to Options\Text Editor\C#\Code Style\Naming\Manage Specifications.
3. Alt+Tab to another application.
4. Alt+Tab back to Visual Studio.
5. The Options window will show but Manage Specifications will _disappear_ and to some users it may seems like Visual Studio is hanged because the Options window is a modal window and you can't do anything unless you close the Manage Specifications window first.

Now, I'm pretty sure that intuitively most users will try to use Alt+Tab to bring the window only to find out that it's not in list because Alt+Tab is used to switch between applications or to show top level windows whereas in practice they need to use Win+Tab to bring this window.

I don't know if it's a bug or whether you know about it but anyway, I thought to report this.

**Expected Behavior**:

Manage Specifications should appear again when the user press Alt+Tab to get back to Visual Studio.

**Actual Behavior**:

Manage Specifications doesn't appear.

**Comment by dpoeschl** [comment]
I think this is specific to the Naming Styles modal dialogs (or any modal dialogs shown from options pages, of which this is the only one for C#/VB). It's probably related to https://github.com/dotnet/roslyn/issues/15429, as well as internal bug 276905.
