### ISSUE TITLE
Solution does not open in VS 2K15 update 3

### ISSUE THREAD

**Issue by eliassal** [dotnet/roslyn#16179]
**Version Used**: 
VS 2K15 update 3
After cloning the repository, I went to VS 2k15, Updte 3, I got a prompt to install SP1, I skipped. No single project in the solution was able to load, all 86 projects display (load failurr or Unavailable)
**Steps to Reproduce**:

1. cloned the repositiory
2. Opened solution in VS
3. When prompted to install VS 2K15 SP1, I skipped

**Expected Behavior**:

**Actual Behavior**:

**Comment by eyalsk** [comment]
@eliassal What's wrong with 2015? same length just crystal clear. 😉

**Comment by jmarolf** [comment]
@eliassal do you have the VS SDK installed?

**Comment by eliassal** [comment]
Yes, I have the following SDKs
![sdks](https://cloud.githubusercontent.com/assets/8447864/21588603/ce84312a-d0e8-11e6-8c53-59bf047c8773.jpg)

**Comment by eliassal** [comment]
I googles a litle bit, and understood that the VS SDK is in the setup of VS which I have done as you can notice in the following snapshot
![vssdks](https://cloud.githubusercontent.com/assets/8447864/21589133/fc85d618-d0ee-11e6-92ed-8bca7dc193f2.jpg)

**Comment by jmarolf** [comment]
@eliassal sorry for being obtuse.  Normally when someone get that error it is because the VSSDK in not installed.  Do you get the same errors now that the VSSDK is installed?

**Comment by eliassal** [comment]
It is already installed if I am not mistaken, I did not add anything today, just checked my setup

**Comment by jmarolf** [comment]
@eliassal  Did you also run Restore.cmd as per the instructions [here](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md)?

**Comment by eliassal** [comment]
jmarolf, can you please tell me what this cmd file do? It corrupted my web access on 2 machines. I tried on the 1st one, right away I started not to be able to browse anything. I rebooted, I then was able to browase but once I relaunched the cmd, again same symptoms and now even after reboot, whenever I browse a any page, get "Page can not be diplayed...", click on Fix connection problem, I get a message indicating "problems found .......ypur computer appears to be correctly configured but the device detected wpad.mynetwork.net is not responding, same thing for channel9.msdn.co....
I tried on a 2nd machine, same behavior no web connection to any web site, all ping works fine

**Comment by jmarolf** [comment]
Restore.cmd should have restored the nuget packages necessary to build.  I have not heard of it changing internet connection settings.  Perhaps someone over at https://github.com/NuGet/NuGet.Client has heard of this?

**Comment by eliassal** [comment]
I really dont know what went wrong, rstore.cmd just get frozen on the 1st step "Restoring Toolsets" then I get this strange behavior. I retried just now again on the 2nd machine, getting the exact same behavior

**Comment by Pilchie** [comment]
@eliassal `Restore.cmd` can end up downloading several hundred MB of NuGet packages if you haven't run it before.  Perhaps something about using that much bandwidth is affecting your connection if it is throttled or something?

**Comment by jasonmalinowski** [comment]
@eliassal Let us know if you still are running into issues.
