### ISSUE TITLE
Implement customizable type/member sorting using Symbol Specifications

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#16173]
Currently, we can add Symbols Specification and then control the style for each specification and that's great but there's no way to to sort these Symbols Specification inside the Manage Specifications window and I think that it would be awesome if we could control the order and then make the formatting mechanism use these specifications to sort the _code_.

In R# there's a feature called File Layout where you can plan how you want to structure the code and you can have some complex rules there, however, for people that don't use R# for whatever reason they may find this feature attractive and as useful as having naming styles.

Any plans for something like this?

**Comment by jmarolf** [comment]
@eyalsk sounds like a completely different feature that naming styles.  If we did this I think we would not conflate it with the naming styles UI.

**Comment by eyalsk** [comment]
@jmarolf Yeah, it is a different feature but the knowledge to do both is there in the Manage Specifications, wouldn't you agree?

**Comment by Pilchie** [comment]
Tagging @CyrusNajmabadi and @dpoeschl.  We *would* like to extend the concept of symbol specifications for more things including this and classification/syntax highlighting.

**Comment by dpoeschl** [comment]
Thanks for the great idea! We've been talking about reusing the Symbol Specifications concept for other features but hadn't filed an issue to track it. I've filed https://github.com/dotnet/roslyn/issues/16259 to track reusing this concept for classification as well.

**Comment by Pilchie** [comment]
Actually - we're already tracking this in #4778.  I'll make a comment about using Symbol Specifications there.
