### ISSUE TITLE
Parsing Diagnostics Relocation Work.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#16178]
@CyrusNajmabadi  and @jcouv 

Would you mind looking at the parsing of parameter arguments, soon. As I'm thinking of having another look at implementing my previous proposal for a VB language feature (Implicit Default Optional Parameters). As it maybe possible to implement in the binder rather than the parser. 
```vb
Sub Method( <CallerLineNumber> Optional LineNo As Int32 = 0 ) '  Pre-feature
Sub Method( <CallerLineNumber> Optional LineNo As Int32 ) ' Post-Feature
```
The `= 0` or `= Nothing` (`Initialiser` I think) to be optional in the presence of the parameter modifier `optional`.
IRCC one cause for concern (for said ole implementation) was a change to the code involved in overload resolution, to correctly handle `<CallerInfoAttributes>` in the presence of the feature.
If you move the diagnostic(s) involved I could re-prototype the feature, to hopefully get it into a future version of the language.

**Comment by gafter** [comment]
Now that you've created this issue, @CyrusNajmabadi and @jcouv have seen your request.

Closing, as opening an issue is not a good way to facilitate private communication.
