### ISSUE TITLE
Preview window shows implementation detail instead of friendly name of fixer

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16196]
![image](https://cloud.githubusercontent.com/assets/1103906/21600394/a09cee22-d1cf-11e6-8a9f-45cd969bb23b.png)

Shouldn't this be a user friendly string?

**Comment by jmarolf** [comment]
@Pilchie If this is assigned to be I assume that it is not up-for-grabs?

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in the preview-changes experience.
