### ISSUE TITLE
Crash opening a solution

### ISSUE THREAD

**Issue by IlyaB** [dotnet/roslyn#1619]
My VS crashes when I open my solution. It doesn't crash if I delete .vs folder, but then it crashes the next time. It started happening after I signed in with some user name in CTP6 build. Then I uninstalled CTP6 and installed RC, still the same crash. 
Resetting VS settings via Tools -> Import and Export Settings -> Reset Settings doesn't help

VS Build: D14Rel 22726.00
Roslyn version: 1.0.0.50317

Exception:
System.InvalidOperationException "This program location is thought to be unreachable."

Exception call stack:
   at Microsoft.VisualStudio.LanguageServices.VisualBasic.ProjectSystemShim.ConvertedVisualBasicProjectOptions.ConvertWarningLevel(WarningLevel level)
   at Microsoft.VisualStudio.LanguageServices.VisualBasic.ProjectSystemShim.ConvertedVisualBasicProjectOptions.DetermineGeneralDiagnosticOption(WarningLevel level, Nullable`1 ruleSetGeneralDiagnosticOption)
   at Microsoft.VisualStudio.LanguageServices.VisualBasic.ProjectSystemShim.ConvertedVisualBasicProjectOptions..ctor(VBCompilerOptions options, IVbCompilerHost compilerHost, IEnumerable`1 globalImports, ImmutableArray`1 strongNameKeyPaths, String projectDirectoryOpt, IRuleSetFile ruleSetOpt)
   at Microsoft.VisualStudio.LanguageServices.VisualBasic.ProjectSystemShim.VisualBasicProject.UpdateOptions()
   at Microsoft.VisualStudio.LanguageServices.VisualBasic.ProjectSystemShim.VisualBasicProject.SetCompilerOptions(VBCompilerOptions& pCompilerOptions)

Crash Call stack:
 	Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(exception, handler) Line 155	C#
>	Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.FilterException(e) Line 1320	C#
 	Microsoft.VisualStudio.LanguageServices.VisualBasic.ProjectSystemShim.VisualBasicProject.SetCompilerOptions(pCompilerOptions) Line 379	Basic
 	[Native to Managed Transition]	
 	Microsoft.VisualStudio.LanguageServices.VisualBasic.ProjectSystemShim.ConvertedVisualBasicProjectOptions.ConvertWarningLevel(level) Line 271	Basic
 	Microsoft.VisualStudio.LanguageServices.VisualBasic.ProjectSystemShim.ConvertedVisualBasicProjectOptions.DetermineGeneralDiagnosticOption(level, ruleSetGeneralDiagnosticOption) Line 212	Basic
 	Microsoft.VisualStudio.LanguageServices.VisualBasic.ProjectSystemShim.ConvertedVisualBasicProjectOptions.New(options, compilerHost, globalImports, strongNameKeyPaths, projectDirectoryOpt, ruleSetOpt) Line 146	Basic
 	Microsoft.VisualStudio.LanguageServices.VisualBasic.ProjectSystemShim.VisualBasicProject.UpdateOptions() Line 385	Basic
 	Microsoft.VisualStudio.LanguageServices.VisualBasic.ProjectSystemShim.VisualBasicProject.SetCompilerOptions(pCompilerOptions) Line 378	Basic
 	[Native to Managed Transition]	
 	CVbcMSBuildHostObject::SetState(options, sources, references, imports, analyzers, additionalFiles, ruleSetFile) Line 1786	C++
 	CVbBldCompiler::InitializeFromCache(pCache) Line 2727	C++
 	CLangCompiler::InitializeFromCache() Line 919	C++
 	CLangCompiler::RunIntellisenseBuild(fCanUseCache, pfCacheUsed) Line 1240	C++
 	CLangCompiler::InternalCallMSBuildToInitializeAllCompilerSettings(fCanUseCache, pfCacheUsed) Line 1401	C++
 	CLangBuildMgr::EnsureCompilerInitialized() Line 3445	C++
 	CLangBuildMgr::OnAfterOpenProject(fSCCOpenedAsynchronous) Line 3417	C++
 	CVbBuildMgr::OnAfterOpenProject(fOpenedAsynchronous) Line 504	C++
 	CLangProject::OnAfterOpenProject(fAdded) Line 881	C++
 	CVsProject::OnAfterOpenProject(fAdded) Line 1022	C++
 	CVbProj::OnAfterOpenProject(fAdded) Line 277	C++
 	CLangHierarchy::PrioritizedOnAfterOpenProject(pHierarchy, fAdded) Line 3957	C++
 	CSolution::FirePrioritizedOnAfterOpenProject(solnEvents, pHierarchy, fProjAdded) Line 17996	C++

**Comment by mavasani** [comment]
@basoundr probably has context.

**Comment by basoundr** [comment]
I had an issue in this area and had it fixed. @jasonmalinowski had a fix in the same area. Without the call stack it is tough to identify the issue here. @jasonmalinowski, has your fix made into D14Rel?

**Comment by basoundr** [comment]
Got dumps from @IlyaB and the issue did not repro. I am going to close this bug as 'not repro'. If this bug happens again we can reopen this issue.
