### ISSUE TITLE
Tuple extension method vs foreach

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#16194]
It was [reported on discussion on another issue](https://github.com/dotnet/roslyn/issues/16159#issuecomment-269876416) that an extension method such as

```cs
public static IEnumerator<(T, U)> GetEnumerator<T, U>(
  this (T[] xs, U[] ys) source)
  => source.xs.Zip(source.ys, (x, y) => (x, y)).GetEnumerator();
```

does not permit the following code to compile

```cs
foreach(var (x, y) in (new int[1], new byte[2])) // ERROR
```

**Comment by alrz** [comment]
I'm not sure I understand this. It won't work for non-tuples either,
```cs
public static class C
{
    public static IEnumerator<int> GetEnumerator(this int @this) => throw null;
    
    static void M()
    {
        foreach(var x in 5) {} // ERROR  
    }
}
```

**Comment by gafter** [comment]
Checking the C# language spec, I see that extension methods are not specified to work for foreach loops.

**Comment by jnm2** [comment]
I predict a feature request.
