### ISSUE TITLE
Inline variable declaration removed whitespace

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16198]
This is based on what is in master as of #0461ffc60aa57e9862ba721a0681352ce443896b.

I cannot repro this standalone nor if I manually run the code fix over the same code. But hopefully this contains enough information to understand the problem. Basically, in [this commit](https://github.com/dotnet/roslyn-project-system/pull/1064/files#diff-e0beb0c586e3ff8a4df6f5c4dc9d101fL403) it changed:

``` C#
var itemType = GetUnresolvedReferenceItemType(originalItemSpec,
                                              updatedUnresolvedSnapshots,
                                              catalogs,
                                              out unresolvedReferenceSnapshot);
```

into:

``` C#
var itemType = GetUnresolvedReferenceItemType(originalItemSpec,
                          updatedUnresolvedSnapshots,
                          catalogs,
                          out IProjectRuleSnapshot unresolvedReferenceSnapshot);
```

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/17016
