### ISSUE TITLE
Rationalize our dependency on Microsoft.VisualStudio.Repository

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#16206]
Roslyn has a transitive dependency on the Microsoft.VisualStudio.Repository.  This is not included in our reference set.  Hence Roslyn is depneding on it without realizing it. This causes our test output to be incomplete and our depnedency graph to have missing entries.

**Comment by jasonmalinowski** [comment]
Whatever this was, it's gone now.
