### ISSUE TITLE
Rationalize our GraphModel dependency

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#16201]
Roslyn has a dependency on the GraphModel APis via the NuGet package RoslynDependencies.Microsoft.VisualStudio.GraphModel.  This package doesn't fit the standard naming convention for packages and lacks Dev15 versions.  This needs to be updated so we can remove the work around in our RunTests project and our project.json entries.

**Comment by jasonmalinowski** [comment]
These no longer exist.
