### ISSUE TITLE
Refactoring "Move type to ..." removes modifier

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#16205]
**Version Used**: Visual Studio 2017 RC 15.0.26014.0

**Code to Reproduce**:
```csharp
public abstract class Foo
{
    private class Bar // Move type to Bar.cs
    {
    }
}
```

**Actual Behavior**:
```csharp
public partial class Foo
{
}
```

**Comment by Pilchie** [comment]
@CyrusNajmabadi didn't you fix this?

**Comment by CyrusNajmabadi** [comment]
I'll check.  I fixed at least one case of this.  But there may be others.

**Comment by miloush** [comment]
I actually prefer to keep all modifiers at one place so that I do not have to go through each file when refactoring, so my expected would be `partial class Foo` here.

**Comment by CyrusNajmabadi** [comment]
This has been fixed.  THe original file will look like this:

```c#
public abstract partial class Foo
{
}
```

And the new file will look like this:

```c#
public abstract partial class Foo
{
    private class Bar // Move type to Bar.cs
    {
    }
}
```
