### ISSUE TITLE
Should analyzers be disabled while compiling XAML MarkupCompilePass1?

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#1622]
WPF (and other XAML flavors) has special magic to invoke the compiler twice (in two passes) – once for the .tmp_proj to produce an assembly that it can reflect upon, and the second is the real compiler invocation that receives the input that was calculated after pass1.

This is where it generates a temporary project to build:
http://referencesource.microsoft.com/#XamlBuildTask/Microsoft/Build/Tasks/Xaml/GenerateTemporaryAssemblyTask.cs,87

We should probably be disabling the analyzers for .tmp_proj compilation. This will likely require changes to MSBuild targets/tasks.

**Comment by KirillOsenkov** [comment]
In fact, longer term we should avoid invoking the compiler during pass1 in the first place, we should retrieve whatever information is needed by XAML resource generation from the sources by using a lighter-weight Roslyn-based tool (I'm guessing even parsing should be sufficient). However this requires non-trivial changes to XAML targets and tasks.

**Comment by mavasani** [comment]
A fix for this change has been checked into MSBuild C# and VB targets files to skip analyzer execution for XamlPrecompile target.

**Comment by KirillOsenkov** [comment]
@mavasani what's the associated commit or checkin that fixes this?

**Comment by mavasani** [comment]
You want internal changesets: 1460411 and 1461374
