### ISSUE TITLE
Intellisense eats "=" while typing attribute parameter without committing completion

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn#16236]
**Version Used**: 

VS 2017 RC public.d15rel/15.0.26014.0

**Steps to Reproduce**:

1. paste the following code into a C# code file

```csharp

[A()]
class AAttribute: Attribute
{
    public string Skip { get; set; }
}
```

2. type "Skip = " in "()" of "A[()]"

**Expected Behavior**:
"Skip " inserted in the editor

**Actual Behavior**:
"Skip = " inserted in the editor

**Comment by rchande** [comment]
Can you verify @jeremymeng ?
