### ISSUE TITLE
Migrate key storage to Azure

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#16237]
Currently, we're using a Microsoft-internal key management system that is being deprecated. We should move this to Azure storage before it's shut down, but also because moving to Azure means we can move dependent infrastructure to Azure too.

**Comment by jaredpar** [comment]
Which infrastructure is a candidate to move to Azure here?

**Comment by brettfo** [comment]
I've moved our build retainer tool to use Azure KeyVault for secrets management.  Other tools still need to be converted.

**Comment by jasonmalinowski** [comment]
This is all completed.
