### ISSUE TITLE
Roslyn Insertion Tool doesn't send notifications on script failure

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#16235]
The Roslyn Insertion Tool doe not currently send notifications if the insertion script itself fails (such as if building the tool fails).

We should wrap the script in a `try/catch` block and use the `Send-MailMessage` function to ensure that script execution failures are sent to @dotnet/roslyn-infrastructure as well.

We should additionally be validating the MSBuild exit code so we can send the appropriate error notification.

**Comment by jasonmalinowski** [comment]
We got rid of the things that can fail.
