### ISSUE TITLE
"Place 'System' directives first when sorting usings" doesn't roam

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16247]
1. Log into VS
2. Choose Tools -> Options -> C# -> Advanced
3. Check "Place 'System' directives first when sorting usings"
4. Click OK
5. On another machine, Log into VS

Expected: For the setting to have roamed and it be checked
Actual: It does not roam and its unchecked

**Comment by davkean** [comment]
it's more than just this setting too, I noticed these don't roam:

![image](https://cloud.githubusercontent.com/assets/1103906/21794530/23be2936-d74f-11e6-8f90-c298606806c4.png)

Maybe this bug is really "roam all the things"

**Comment by Pilchie** [comment]
@jmarolf Can you verify that everything roams as expected now that the binding redirect issue is fixed?

**Comment by Pilchie** [comment]
Note - I was hitting this on Sort System first again today, even though the Add Using for NuGet had roamed.

**Comment by Pilchie** [comment]
See #16392, which looks like a report of this for another option.

**Comment by Pilchie** [comment]
And https://github.com/dotnet/roslyn/issues/16393

**Comment by jmarolf** [comment]
Looks like this is not fixed.  Attempts to save this setting result in the following exception.  Closing this as this is a VS issue not Roslyn.

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException occurred
  HResult=0x80131500
  Message='Newtonsoft.Json.Linq.JObject' does not contain a definition for 'clientId'
  Source=Microsoft.CSharp
  StackTrace:
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinderController.SubmitError(CError pError) in f:\dd\ndp\fx\src\CSharp\Microsoft\CSharp\RuntimeBinderController.cs:line 19

```

**Comment by davkean** [comment]
Where is the internal bug filed for this? I'm still seeing it.

**Comment by jmarolf** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems?id=371401 Looks like it was closed while I wasn't looking.
