### ISSUE TITLE
Undo history, breakpoints, diff marks and cursor position is lost after using code fix to rename file to match type

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16253]
1. Create a new project
2. Make changes in Class1.cs
3. Rename Class1 => Class2
4. Drop light bulb
5. Choose Rename file to match type
6. Attempt to undo the changes you made in 2

Expected: Changes to be undone in the file
Actual: All undo history is lost - unlike if I manually renamed the type

**Comment by davkean** [comment]
It's more than undo history - it looks like this is being treated as a completely new file instead of the running document seeing this as just a rename of an existing file. I also lose:

- the Edit markers (ie green/yellow/red bars)
- Cursor position
- probably other things that are being tracked by VS

**Comment by davkean** [comment]
If I manually rename the file using Solution Explorer - then everything works as expected.

**Comment by Pilchie** [comment]
This is a consequence of https://github.com/dotnet/roslyn/issues/6261.  The Roslyn workspace doesn't have the concept of renaming a document, so we lower that to a remove/add pair when committing to VisualStudio in `TryApplyChanges`.

**Comment by Pilchie** [comment]
We should consider solving #6261 and this bug for Update 1.
