### ISSUE TITLE
TupleTypeSymbols are not always round-trippable (error type)

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#16252]
This came about from a discussion in https://github.com/dotnet/roslyn/pull/16232

If the Compilation does not have a definition for the Sytem.ValueTuple`X types, then creating a tuple (like ```(x, y, z)```) will produce a TupleTypeSymbol whose 'UnderlyingTupleType' is an 'Error' NamedTypeSymbol.  This is reasonable and produces good results for higher layers.

Unfortunately, these symbols are problematic as they are not easily round-tripped.  If you try to call ```Compilation.CreateTupleType(yeOldUnderlyingErrorType, ...)``` then the compiler will throw an exception stating that the underlying type is not valid.

While i think it's good that the API is picky, i think it should at least accept the same underlying types that it itself hands out.  More generally, it should accept an Error-NamedTypeSymbol if the containing namespace is called System, which is in the global namespace, and the type name is ValueTuple.

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv

**Comment by gafter** [comment]
@CyrusNajmabadi Would this issue have symptoms in the IDE in the upcoming release if not fixed?

**Comment by jcouv** [comment]
@gafter My understanding is that the issue was already solved (at the IDE level) by https://github.com/dotnet/roslyn/pull/16232, so we can push out this API work if needed.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/16232
