### ISSUE TITLE
Convert to Interpolated String leaves newlines in parenthesized expressions

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#16251]
**Version Used**: 2017 RC Refresh

```C#
			string s = "A" + (
				2);
```

`Convert to Interpolated String` produces

```C#
			string s = $"A{(
				2)}";
```

This produces

>CS8076	Missing close delimiter '}' for interpolated expression started with '{'.

**Comment by SLaks** [comment]
Removing the parentheses fixes.

**Comment by CyrusNajmabadi** [comment]
No repro, i get:

![Image](https://github.com/user-attachments/assets/c08d94a4-b4c3-4f96-8d69-eba7c2990e13)
