### ISSUE TITLE
Expose some way to initialize ForegroundThreadAffinitizedObject

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#16260]
I'm building some tests to compare the performance of the editor with various language services. I'm using a [fork](https://github.com/AmadeusW/VSEmbed) of [VSEmbed](https://github.com/SLaks/VSEmbed) to do so. VSEmbed hosts the editor with Roslyn's language services outside of Visual Studio and in a WPF Application.

When I create the editor from a Console Application I receive a number of errors complaining that the `ForegroundNotificationService` can't be created by MEF and is failing here: http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/ForegroundNotification/ForegroundNotificationService.cs,37

It looks like I have to initialize the `ForegroundThreadAffinitizedObject` as shown here: http://source.roslyn.io/#Roslyn.Services.Test.Utilities/Threading/WpfTestCase.cs,41

Currently I'm doing this via reflection as you can see here: https://github.com/AmadeusW/VSEmbed/blob/f0e8c97949bce770c7cf0564edebfb8a81df6717/PerformanceTests/BasicTypingTest.cs#L25-L38

This works, but it's obviously fragile. Is there any chance we might be able to expose some way of initializing `ForegroundThreadAffinitizedObject`?

**Comment by CyrusNajmabadi** [comment]
@JoshVarty is this still a need you have?

**Comment by JoshVarty** [comment]
No it's not. Feel free to close if you'd like.
