### ISSUE TITLE
"Rename file to match type" doesn't work for nested types

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16284]
1. In file DesignTimeAssemblyResolution.ReferenceItem.cs:

``` C#
// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

using System;

namespace Microsoft.VisualStudio.ProjectSystem.VS.References
{
    internal partial class DesignTimeAssemblyResolution
    {
        private struct ResolvedReference
        {
            public ResolvedReference(string resolvedPath, Version version)
            {
                ResolvedPath = resolvedPath;
                Version = version;
            }

            public string ResolvedPath
            {
                get;

            }

            public Version Version
            {
                get;
            }
        }
    }
}
```

2. On ResolvedReference, drop the light bulb

Expected: To be able to rename the file to match type or vice versa ("Move type to file" created the file)
Actual: Only get offered to "move type to file"

**Comment by davkean** [comment]
It looks like "Move type to file" and "Rename file to match type" are in sync on their logic. My reasoning if that "Move type to file" can move to a nested structure "Foo.Bar.cs" then "Rename file to match type" should respect that same structure.

**Comment by balajikris** [comment]
>My reasoning if that "Move type to file" can move to a nested structure "Foo.Bar.cs" then "Rename file to match type" should respect that same structure

I'm not sure if that is always correct. Suppose there was one outer type in the file (your example case), sure, the synchrony makes sense. In the case where there are more than one outer types in the file and the file name already matches one of those type names,  I'm not sure if "rename file" option on the other types is useful. Sure, it could still be useful, but didn't take that approach in the initial implementation. Just noting that here, in case it helps. 

```C#
A.cs

$$class Outer
{
   class Inner { }
}

class A { }
```

**Comment by davkean** [comment]
Sorry the repro was wrong, I changed from DesignTimeAssemblyResolution -> ResolvedReference

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/16456
