### ISSUE TITLE
Use Null Propagation diagnostic incorrect for method groups

### ISSUE THREAD

**Issue by aelij** [dotnet/roslyn#16287]
**Version Used**: VS 2017 Build 26020

**Steps to Reproduce**:
```csharp
var c = new C();
Action<string> a = $$c != null ? c.M : (Action<string>)null;
class C { public void M(string s) { } }
```

IDE0030 appears at $$, and the fix produces non-compilable code:

```csharp
Action<string> a = c?.M;  //CS0023 Operator '?' cannot be applied to operand of type 'method group'
```

**Expected Behavior**:

Diagnostic should not show up in this case.

**Comment by Pilchie** [comment]
Is this a dupe?  You fixed value types - did that apply to method groups too?

**Comment by CyrusNajmabadi** [comment]
Yup.  This has been fixed.  I'll add a test to this effect.

**Comment by CyrusNajmabadi** [comment]
Confirmed with https://github.com/dotnet/roslyn/pull/16297
