### ISSUE TITLE
"Move type to file" duplicates interface implementations in partial class

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16282]
1. On ReferenceItem, choose "Move type to DesignTimeAssemblyResolution.ReferencePathItem"

``` C#
// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

namespace Microsoft.VisualStudio.ProjectSystem.VS.References
{
    internal class DesignTimeAssemblyResolution : IVsDesignTimeAssemblyResolution
    {
 [...]
        private struct ReferenceItem
        {
            public ReferenceItem(string resolvedPath, Version version)
            {
                ResolvedPath = resolvedPath;
                Version = version;
            }

            public string ResolvedPath
            {
                get;

            }

            public Version Version
            {
                get;
            }
        }
  }
}
```

Expected: 

```
    internal partial class DesignTimeAssemblyResolution
    {

        private struct ReferenceItem
        {
            public ReferenceItem(string resolvedPath, Version version)
            {
                ResolvedPath = resolvedPath;
                Version = version;
            }

            public string ResolvedPath
            {
                get;

            }

            public Version Version
            {
                get;
            }
        }
    }
```

Actual:
```
  internal partial class DesignTimeAssemblyResolution : IVsDesignTimeAssemblyResolution
  {
        private struct ReferenceItem
        {
            public ReferenceItem(string resolvedPath, Version version)
            {
                ResolvedPath = resolvedPath;
                Version = version;
            }

            public string ResolvedPath
            {
                get;

            }

            public Version Version
            {
                get;
            }
        }
    }
```

**Comment by Pilchie** [comment]
Why do you expect that?  Both are legal.

**Comment by CyrusNajmabadi** [comment]
Yeah.  This is also a case where people definitely follow both styles.  Some people only want the base-list on one part.  Some people duplicate the base-list on all parts.  Some people put the specific base-type on the part where the impls exist for that type.

**Comment by davkean** [comment]
The way I see it, is that inner class only specifies "just enough" to indicate that it's a inner class of its parent. The more it duplicates (such as modifiers and interfaces) the more I have to change when that changes in the original parent file. You don't keep them in sync automatically for me, so I'm going to have to fix them up when they change.

**Comment by CyrusNajmabadi** [comment]
As this is legal, i would move this out to 2.1.  What do you think @Pilchie ?  I'm worried about changin this and negatively affecting people who might prefer this style.

**Comment by miloush** [comment]
#16205 also related. I agree with @davkean preference here, and I fall into 'some people put the specific base-type on the part where the impls exist for that type' group.

Would be nice to see an option for this, but I agree it isn't critical. You immediately spot it and can fix it as part of verifying the generated code that it looks as it should.
