### ISSUE TITLE
Switch over type throws null ref exception

### ISSUE THREAD

**Issue by rogeralsing** [dotnet/roslyn#16293]
Reporting the unexpected behavior seen in this question: http://stackoverflow.com/questions/41504414/c-sharp-7-pattern-matching-semantics

**Version Used**: 
Microsoft Visual Studio Professional 2017 RC
Version 15.0.26014.0 D15REL
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Professional
Visual C# 2017 RC   00369-50000-00000-AA365
Microsoft Visual C# 2017 RC

**Steps to Reproduce**:

1. I have not been able to reproduce this outside of my library code:
I have this block of code:
https://github.com/AsynkronIT/protoactor-dotnet/blob/master/src/Proto.Remoting/EndpointManager.cs#L21
```c#
var msg = context.Message;
//TODO: convert to switch later, currently doesnt work, switching on type throws null ref error
if (msg is Started)
{
    Console.WriteLine("[REMOTING] Started EndpointManager");
    return Actor.Done;
}
if (msg is MessageEnvelope)
{
    var env = (MessageEnvelope)msg;
    PID pid;
    if (!_connections.TryGetValue(env.Target.Host, out pid))
    {
        Console.WriteLine("Resolving EndpointWriter for {0}", env.Target.Host);
        var props =
            Actor.FromProducer(() => new EndpointWriter(env.Target.Host))
                .WithMailbox(() => new EndpointWriterMailbox());
        pid = context.Spawn(props);
        _connections.Add(env.Target.Host, pid);
    }
    pid.Tell(msg);
    return Actor.Done;
}
return Actor.Done;
```

Which works as expected.

This block however, https://github.com/AsynkronIT/protoactor-dotnet/blob/master/src/Proto.Remoting/EndpointManager.cs#L45
```c#
switch (context.Message)
{
    case Started _:
        Console.WriteLine("[REMOTING] Started EndpointManager");
        return Actor.Done;
    case MessageEnvelope env:
        PID pid;
        if (!_connections.TryGetValue(env.Target.Host, out pid))
        {
            Console.WriteLine("Resolving EndpointWriter for {0}", env.Target.Host);
            var props =
                Actor.FromProducer(() => new EndpointWriter(env.Target.Host))
                    .WithMailbox(() => new EndpointWriterMailbox());
            pid = context.Spawn(props);
            _connections.Add(env.Target.Host, pid);
        }
        pid.Tell(env);
        return Actor.Done;
    default:
        return Actor.Done;
}
```
Throws Null reference exception.

I have narrowed it down to the `case MessageEnvelope env:` line.
Replacing that with:
```c#
case MessageEnvelope _:
     var env = context.Message as MessageEnvelope;
```
Fixes the issue.

**Expected Behavior**:
I would expect the above to work just like the original if based code.

**Actual Behavior**:
Null reference exception on the `case MessageEnvelope env:` line.
Or rather it throws null reference exception directly on the `switch(context.Message)` before I am able to step into any of the case blocks.  but the above mentioned fix removes the issue.

**Comment by gafter** [comment]
This is a dup of #16066
