### ISSUE TITLE
CA1021 (Avoid out parameters) complains about Deconstruct methods

### ISSUE THREAD

**Issue by DavidArno** [dotnet/roslyn#16291]
**Version Used**: VS2017 RC2

**Steps to Reproduce**:

1. Create a class and add a `Deconstruct()` method to it. 
2. Enable rule CA1021
3. Build

**Expected Behavior**:
`Deconstruct()` is a special case and has to have `out` parameters to work properly. Therefore this analyser should ignore `Deconstruct()` methods.

**Actual Behavior**:
The message "`Consider a design that does not require that <parameter> be an out parameter.`" is reported for each `out` parameter in the `Deconstruct`.

**Comment by airbreather** [comment]
The `dotnet/roslyn-analyzers` implementation of CA1021 doesn't have this problem.

Does that mean that this can be closed?

**Comment by DavidArno** [comment]
It does indeed. Thanks.
