### ISSUE TITLE
zero- and one-element tuples

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#16313]
To best align positional pattern-matching (which won't restrict the number of values being deconstructed) with tuples, please support zero-element and one-element tuple types and tuple expressions.

**Comment by AdamSpeight2008** [comment]
Doesn't the current tuple parser require a minimum of 2 values?

**Comment by alrz** [comment]
@AdamSpeight2008 Yes.

**Comment by bbarry** [comment]
Why not align the other way, don't recognize deconstruction syntax with fewer than 2 elements?

**Comment by HaloFour** [comment]
@gafter 

I assume that this will be a post-C# 7.0 consideration?

@bbarry 

Without support for conditional deconstruction of zero/one values then patterns like `None()` and `Some(T)` would be impossible.

**Comment by orthoxerox** [comment]
@bbarry Single-value tuples are necessary for primitive wrapper types.

**Comment by dsaf** [comment]
Would leveraging it for naming primitive return values be considered an abuse?

```csharp
(int id) SaveSomethingToDb(Something smth);
```

instead of

```csharp
int SaveSomethingToDbAndReturnId(Something smth);
```

**Comment by HaloFour** [comment]
I like how Swift handles "womples", they're effectively just the scalar value itself.  So an `Int32` is an `(Int32)` is an `((Int32))`.  This makes sense as `1`, `(1)` and `((1))` are all the same value.  Swift does not allow for naming the element of a "womple", though, which kind of makes sense.

**Comment by Richiban** [comment]
Will the zero-tuple be explicitly referred to as unit anywhere?

I'd love to see some support for this in the future, such as being able to use `Func<int, ()>` instead of `Action<int>`, for example.

**Comment by alrz** [comment]
I think the type (and literal) for unit could be `()` if it wasn't ambigious, but using it in place of void probably requires language support so you dont need to explicitly return `()`.

**Comment by jcouv** [comment]
@gafter Is this tracking a compiler/API change or a language feature? If the latter, could you close or move to csharplang?

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #883](https://github.com/dotnet/csharplang/issues/883) via [**ZenHub**](https://www.zenhub.com/)
