### ISSUE TITLE
VS 2017 RC Debugging Message

### ISSUE THREAD

**Issue by reaction1989** [dotnet/roslyn#16322]
I am trying to debug with VS2017RC and i am always getting this error when i try to start:

![image](https://cloud.githubusercontent.com/assets/873751/21742702/bbff7f46-d4f3-11e6-9a1b-442161c2ce00.png)

My startproject ist VisualStudioSetup.Next

Any suggestions?

**Comment by jasonmalinowski** [comment]
@reaction1989 Hmm, sorry this particular bug got missed. That should have worked. Are you still seeing this?
