### ISSUE TITLE
Razor: Goto definition navigates to subject buffer contents in generated files

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#1633]
Will add detailed steps - 
the crucial steps are 
1. add a helper page to app_code
2. call one of the helper methods in an aspx page
3. goto definition on the class or method (ensure that the helper page is not open in the editor)

![image](https://cloud.githubusercontent.com/assets/4213867/6862066/2603ad24-d3ff-11e4-96d8-17e26f5fd0f8.png)

**Comment by Pilchie** [comment]
Fixing this will require coordination with the web project system.

**Comment by CyrusNajmabadi** [comment]
Razor has been redone to be LSP based.  We are not touching legacy razor.
