### ISSUE TITLE
Evaluating type switch in quick watch permanently introduces variable

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#16336]
**Version Used**: VS 2017 RC (15.0.26020.0)

**Steps to Reproduce**:
```csharp
class Program
{
    static void Main(string[] args)
    {
        object value = 0;
    }$$
}
```
1. Set breakpoint at `$$`
2. Open quick watch and evaluate `(value is int a && a == 0)`
3. Evaluate it again

**Expected Behavior**:
Returns `true` everytime.

**Actual Behavior**:
Returns `true` on the first evaluation and `error CS0136: A local or parameter named 'a' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter` on every further evaluation.

**Comment by tmat** [comment]
Dup of https://github.com/dotnet/roslyn/issues/16062
