### ISSUE TITLE
Assembly-level attributes & AllowMultiple = true 

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/roslyn#16337]
**Version Used**: master (15 dec 2016)

**Steps to Reproduce**:

Run the following code:
```cs
using System;
using ConsoleApp;

[assembly: My, My, My]

namespace ConsoleApp
{
	[AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
	public class MyAttribute : Attribute
	{
	}

	[My, My, My]
	public class Program
	{
		public static void Main(string[] args)
		{
			var t = typeof(Program);
			Console.WriteLine(
				"Type-level: {0} attributes",
				Attribute.GetCustomAttributes(t, typeof(MyAttribute)).Length);
			Console.WriteLine(
				"Assembly-level: {0} attributes",
				Attribute.GetCustomAttributes(t.Assembly, typeof(MyAttribute)).Length);

		}
	}
}
```
[TryRoslyn results](http://tryroslyn.azurewebsites.net/#b:master/K4Zwlgdg5gBAygTxAFwKYFsDcAoUlYDCA9hCEQDaoCCADjTtgNoCGIIGARuQgFwwCyCADQDhogLrZsEZulQgazAMaoYxUhWp1sAb2wBIRlWTIATmA7A0AVRDMoqABTGzFq6gAqzUw+QgAdFTk5CJB5EQA7vzA5MhgNJQwALwwZsCoAJSS+jTAXGBKMErkrCCiLuaWaDB8FW5oBnr6AL5ShoIiHRIGufmFxaUwAAqmRFCmso0GOXnkBTAozHGFAG5EYAAmAsyQjijm0IziMN5QIBnTTfr6K96pyakINKhEAGaOI2MT6Bk41/rqMiUfwAdXMaAAMpAnNNrgAiDxPVAAWkoK1Q5D4OgADM0TiZKu4QHChLD9HUqqh/ABxVDIAigZBEdAUomOZAiZBIt6OQSstAZDL+CGoaDIAAWv1hgM0oPBqChEBh/30cKobE43FRqHRmJgOLxS1clOJpJV/KptPpjOZFpA7MCGvQXDEXOePL5BPqmSFIrFkoY11aLWwzSAA==)

**Expected Behavior**:
Shouldn't be there three `MyAttribute` attributes for the assembly? Expected output:
```
Type-level: 3 attributes
Assembly-level: 3 attributes
```

**Actual Behavior**:
It prints
```
Type-level: 3 attributes
Assembly-level: 1 attributes
```

The current behavior reproduces on с# 3 compiler and on [c# 5 compiler](https://dotnetfiddle.net/T5TuDd) but mono 4.2.2 compiler (here's [online version](https://www.jdoodle.com/compile-c-sharp-online)) works as expected.

**Comment by ig-sinicyn** [comment]
Oookay, it's now even weirder 😕

Check the
```cs
using System;
using ConsoleApp;

[assembly: My("A"), My("A"), My("B")]

namespace ConsoleApp
{
	[AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
	public class MyAttribute : Attribute
	{
		public MyAttribute(string origin)
		{
			Origin = origin;
		}

		public string Origin { get; }
	}

	[My("A"), My("A"), My("B")]
	class Program
	{
		static void Main(string[] args)
		{
			var t = typeof(Program);
			Console.WriteLine(
				"Type-level: {0} attributes",
				Attribute.GetCustomAttributes(t, typeof(MyAttribute)).Length);
			Console.WriteLine(
				"Assembly-level: {0} attributes",
				Attribute.GetCustomAttributes(t.Assembly, typeof(MyAttribute)).Length);

			Console.ReadKey();
		}
	}
}
```

**Comment by AlekseyTs** [comment]
If I remember correctly, assembly level attributes are de-duped based on the target attribute and values as part of attribute merging across all modules. It would be interesting to see if native compiler behaves in the same manner.

**Comment by ig-sinicyn** [comment]
@AlekseyTs 

> It would be interesting to see if native compiler behaves in the same manner.

It does. Same behavior on с# 3 compiler (VS 2008).

**Comment by jaredpar** [comment]
This behavior is By design.

**Comment by ig-sinicyn** [comment]
@jaredpar 

Well, just out of curiosity, what's the reasons behind this decision? 

It's not documented anywhere as far as I can see. Also, some compilers (mono's one, as example) do not merge assembly-level attributes, so it does not look as like something fundamental or CLS-related 😕

**Comment by gafter** [comment]
@ig-sinicyn This is very longstanding behavior of the C# compiler, and to change it today might break some users of the compiler. I don't know the original reasons for the "decision" that things should behave this way, but given that they do, it would be too much of a risk to change it.
