### ISSUE TITLE
Minor clarification for the wiki

### ISSUE THREAD

**Issue by StingyJack** [dotnet/roslyn#16331]
On the [wiki page for creating new analyzers](https://github.com/dotnet/roslyn/wiki/How-To-Write-a-C%23-Analyzer-and-Code-Fix), there is an instruction that needs a bit more text. It currently says...

> Press F5 to run the newly created Analyzer project in a second instance of Visual Studio. 

Which is correct if you have an empty solution, but if you are adding a new analyzer project to an existing solution, it doesnt work. Something like the following may reduce that confusion.

> Press F5 to run the newly created Analyzer projects in a second instance of Visual Studio (the project template actually creates three projects, and the <project name>.VISX is the one the debugger will start).

**Comment by Pilchie** [comment]
Applied, with a tiny bit of editorial license.
