### ISSUE TITLE
Expression-bodies accessors don't show completion for base

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#16335]
**Version Used**: 15.0.26020

```C#
class B {
	public virtual int T { get => bas }
}
```

Pressing Ctrl+Space on `bas` offers no completions.  

This works on TryRoslyn-Edge, so it may have been fixed.  http://tryroslyn-edge.azurewebsites.net/#b:master/f:>ilr/MYGwhgzhAEBC0G8CwAoAkABwK4CMQEthoA3fAJwBcswRp8A7C6AFUWgHMBTJgXgD5oOSNAC+qEUA

I'm filing anyway for verification.

**Comment by Pilchie** [comment]
Nope - base is not in the list in context in current bits.

**Comment by Pilchie** [comment]
Should be a quick fix to the [`BaseKeywordRecommender`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/Completion/KeywordRecommenders/BaseKeywordRecommender.cs,ddad28bc6c3f0c25)
