### ISSUE TITLE
Rosyln CAExcludePath: non-operational for Native C++ Project

### ISSUE THREAD

**Issue by mancoast** [dotnet/roslyn#16333]
Greetings!

This issue exists to discuss the exact requirements to exclude Library and SDK folders from Code Analysis.
We are trying to implement Continuous Integration with Analysis Builds to check the output from EnableExperimentalCppCoreCheck.

**Version Used**: 
Windows Server 2016 - Clean Install
Visual Studio 2015 Update 3
Native C++ Solution

https://github.com/buddhi1980/mandelbulber2/issues/198 REFERENCE https://github.com/buddhi1980/mandelbulber2/commit/1fa29dad9ab901cd1eabadb4396ff0fe115885d5
**Steps to Reproduce**:
1.  git clone ...
2.  Open/Build *.sln
3.  8000+ Warnings

**Expected Behavior**:
Ignore directories specified by CAExcludePath from analysis results.
**Actual Behavior**:
Directories specified by CAExcludePath - non-operation - Analysis has thousands of warnings from QT library and windows SDK source files.

**Comment by mancoast** [comment]
@Pilchie  Are we experiencing unexpected behavior with proper use of CAExcludePath [bug], or is the implementation within commit 1fa29da incorrect? [user error]

Thanks!

**Comment by Pilchie** [comment]
I'm the wrong person to ask - I'm just trying to get the bug to the right people.

**Comment by mancoast** [comment]
Ok, thanks!

**Comment by mancoast** [comment]
Reference Appveyor Logs:
https://ci.appveyor.com/project/buddhi1980/mandelbulber2/build/1.0.1.0.0.7.5-master/job/9nkh6emamplrqgf2/messages

**Comment by jmarolf** [comment]
@mancoast see https://msdn.microsoft.com/en-us/library/zyhb0b82(v=vs.100).aspx

**Comment by mancoast** [comment]
Greetings @jmarolf,

Thanks for the hint, but #pragma is not an acceptable solution for the unresponsive Rosyln CAExcludePath variable.  I need to exclude the "./packages/" folders from analysis.  Also require exclusion of all code-generated headers and source files that are part of QT MOC/UI/RES in folder "./build-win".

Thanks,
coast

**Comment by jmarolf** [comment]
@AndrewPardoe would you be able to help @mancoast figure out why setting CAExcludePath like this does not work?

```XML
<CAExcludePath>$(SolutionDir)\build-win\;$(SolutionDir)packages\;$(WindowsSDK_IncludePath);$(CAExcludePath)</CAExcludePath>
```

**Comment by AndrewPardoe** [comment]
Let me find our MSBuild expert for you.

**Comment by sunnychatterjee** [comment]
Here are a few steps for debugging these issues for a future reference:

1. Go to Tools->Options->Project and Solutions->Build and Run->MSBuild Project Build Output Verbosity and change it to Diagnostic (default should be Minimal).
2. Run code analysis on solution.

From the build output window, you should see what CAExcludePath expands to. For example, for a simple console project, I see something like -

1>                   CAExcludePath = C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include;C:\Program Files (x86)\Windows Kits\8.1\Include\um;C:\Program Files (x86)\Windows Kits\8.1\Include\shared;C:\Program Files (x86)\Windows Kits\8.1\Include\winrt;;

Once you see what this output contains, you can tell whether the string consists of well-formed paths as you intend them to be.

For this particular issue, note that <CAExcludePath> is set inside Microsoft.CodeAnalysis.Targets file. I was able to successfully override it for my local project by sticking in the following after importing the targets file.

  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
  </ImportGroup>
  <PropertyGroup Condition="'$(Language)'=='C++'">
    
    <CAExcludePath>$(SolutionDir);$(CAExcludePath)</CAExcludePath>
  </PropertyGroup>

This suppresses all warnings from my solution directory.

Hope this helps!

**Comment by mancoast** [comment]
Greetings @sunnychatterjee 

The changes suggested are in this commit:
https://github.com/buddhi1980/mandelbulber2/commit/219432e22c9e3f3c8c789d478beb115fa46ec495

1.) Move PropertyGroup composed of CAExcludePath after all Targets.
2.) Set Build Verbosity to Diagnostic 

The new Build Logs are available here.
https://ci.appveyor.com/project/buddhi1980/mandelbulber2/build/1.0.1.0.0.7.6-master

It appears that the Code Analysis still outputs many warnings from SDK and Library files from:
```
# still non-operational
<CAExcludePath>..</CAExcludePath> 

# MSVC14 C++ Projects require Curated Code Analysis
# 1. Exclude Autogen code headers/source
$(SolutionDir)\build-win\
# 2. Exclude Nuget packages
$(SolutionDir)packages\ 
# 3. Exclude SDK files
$(WindowsSDK_IncludePath)
```

Do you have any additional suggestions?

Thanks,
coast

**Comment by sergiyor** [comment]
Hello @mancoast,
The targets file for CppCoreCheck contains the following:
        <BuildMacro Include="CAExcludePath">
            <EnvironmentVariable>true</EnvironmentVariable>
            <Value>$(IncludePath)</Value>
        </BuildMacro>

So it takes into account current include paths but not the CAExcludePath property.
You can try changing IncludePath to include additional folders. Make sure you do this before importing CppCoreCheck targets.

Also, in the last build log I'm seeing warnings only from c:\projects\mandelbulber2\. Apparently, SDK headers are actually excluded as expected by the use of $(IncludePath).

Anyway, I'll file a bug to correct CppCoreCheck targets for the next VS update.

Thanks.
-Sergiy

**Comment by mancoast** [comment]
Greetings @sergiyor 

The use of IncludePath instead CAExcludePath resolved the confusion.
Also needed to juxtapose IncludePath to Microsoft.Cpp.targets.
Lastly, required a quick comment suppression CAExcludePath PropertyGroup.
see:
https://github.com/buddhi1980/mandelbulber2/commit/e411150b04f620cac5a0d0150d6febce5199348d

Now our Continuous Integration with Analysis Builds includes relevant EnableExperimentalCppCoreCheck:
https://ci.appveyor.com/project/buddhi1980/mandelbulber2/build/job/vr14wufr8dtetgj3/messages


Thanks for the hints, everyone!

**Comment by jmarolf** [comment]
alright @mancoast I'm closing this issue
