### ISSUE TITLE
Improve editorconfig IDE formatting options

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#16343]
Original discussion [here](https://groups.google.com/forum/#!topic/editorconfig/Ftaui8OlLYc)
1. csharp_new_line_before_open_brace, That looks a little bit cumbersome. IMHO, something like this would be better:
csharp_new_line_before_open_brace = true
csharp_new_line_before_open_brace_lambdas = false
csharp_new_line_before_open_brace_anonymous_methods = false
2. csharp_space_within_parentheses (currently rather inconsistent, as there are separate options for space_between_method_call_parameter_list_parentheses and space_between_method_declaration_parameter_list_parentheses, typeof(...), default(...) and sizeof(...) are treated as method calls without any mention in documentation, and there is no way to change spacing of checked(...))
3. csharp_indent_braces and csharp_indent_block_contents - should be possibly to specify a value for each brace type, like with csharp_new_line_before_open_brace. For example, I have a user request where user doesn't want to have namespace contents indented.

**Comment by Pilchie** [comment]
We don't think this is enough of a benefit to change at this point.

**Comment by kevygreen** [comment]
Having them all on one line (without an error level) prevents people from enforcing a standard. If you want to bring it to people's attention that they aren't following the standard, there is currently no way to do that.

**Comment by dsoronda** [comment]
Why is this closed ?
What if I want to completely disable csharp_new_line_before_open_brace ?
What if I want K & R style and want to set csharp_new_line_before_open_brace = false for all ?

It would be nice to be able to let user decide how to handle new line.

My code looks like this: 
void MyMethod() {

**Comment by jmarolf** [comment]
@dsoronda

> Why is this closed ?

see @Pilchie 's comment above

> What if I want to completely disable csharp_new_line_before_open_brace ?

Can you clarify what you mean here? Do you want to turn the formatter off?

> What if I want K & R style and want to set csharp_new_line_before_open_brace = false for all ?`

`csharp_new_line_before_open_brace = none`


> What is option for csharp_new_line_before_open_brace to support code like this ?

You editorconfig file has incorrect syntax, the below should set the options correctly
```
csharp_new_line_before_catch = false
csharp_new_line_before_else = false
csharp_new_line_before_finally = false
csharp_new_line_before_members_in_anonymous_types = false
csharp_new_line_before_members_in_object_initializers = false
```

**Comment by dsoronda** [comment]
Thank you @jmarolf .

I finally make it to work. I had to restart VS 2017, after I make changes to .editorconfig, to make it work.
Sadly, this still doesn't work in VS Code :(

This is how my .editorconfig look now :

~~~ini
# http://EditorConfig.org

# This file is the top-most EditorConfig file
root = true

# All Files
[*]
charset = utf-8
end_of_line = crlf
indent_style = tab
indent_size = 4
insert_final_newline = false
trim_trailing_whitespace = true

# Dotnet Code Style Settings
# See https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference
# See http://kent-boogaart.com/blog/editorconfig-reference-for-c-developers
[*.{cs,csx,cake,vb}]


# New Line Options
# BUG: Warning level cannot be set https://github.com/dotnet/roslyn/issues/18010
# https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#newline_before_else
# none, accessors, types, methods, properties, indexers, events, anonymous_methods, control_blocks, anonymous_types, object_collection_array_initalizers, lambdas, local_functions
# csharp_new_line_before_open_brace = all

csharp_new_line_before_open_brace = none
csharp_new_line_before_catch = false
csharp_new_line_before_else = false
csharp_new_line_before_finally = false
csharp_new_line_before_members_in_anonymous_types = false
csharp_new_line_before_members_in_object_initializers = false

~~~

**Comment by jmarolf** [comment]
@dsoronda

> Sadly, this still doesn't work in VS Code :(

Yep, VSCode does not support these yet could you file an issue on https://github.com/OmniSharp/omnisharp-roslyn/issues?

**Comment by DustinCampbell** [comment]
@jmarolf: Just FYI, that's sort of the wrong place for C# for VS Code issues. That's the repo for the OmniSharp server used by VS Code. The appropriate place to start for C# for VS Code issues is https://github.com/OmniSharp/omnisharp-vscode/issues.
