### ISSUE TITLE
Find Refs needs better output formatting or grouping for partial classes

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#1634]
Find Refs on Partial classes creates 2 separate entries for the class, one with 0 references and other with ref count of actual references - 1.

See how the class Index has 2 entries with 0 and 3 references in FindRefs versus 4 references in codelens.

![image](https://cloud.githubusercontent.com/assets/4213867/6862096/0a6ae220-d400-11e4-8a9c-f6db477ad371.png)

**Comment by rchande** [comment]
@CyrusNajmabadi Can this be closed?
