### ISSUE TITLE
Insertion tool should clean up old pull request branches

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#16356]
It's not uncommon we forget to delete merged insertion branches, or forget to merge them entirely. The insertion tool should probably clean up old branches after a few weeks.

**Comment by agocke** [comment]
I've written a Python script for this. Currently finding a place to put it. :)

**Comment by jasonmalinowski** [comment]
@agocke Didn't this end up somewhere? I forget.

**Comment by agocke** [comment]
I looked around and can't find my script :/

**Comment by jasonmalinowski** [comment]
Reactivating because we still need this, but it's not @agocke's problem anymore. :smile:

**Comment by jasonmalinowski** [comment]
Closing in favor of https://github.com/dotnet/roslyn-tools/issues/221.
