### ISSUE TITLE
Add tests for default parameter values for local functions

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#16352]
We do not appear to have tests for default values on parameters of local functions. Please add such tests. From a [related code review](https://github.com/dotnet/roslyn/pull/16315#discussion_r95046806):

> we probably do not have any tests that verify that default parameter values are handled properly for local functions. Please add some of the success tests that verify that it is possible to take advantage of the default values. Should also check if values make it to metadata.

**Comment by gafter** [comment]
See See https://github.com/dotnet/roslyn/pull/16315/files#r95429886 for a conversation that may be related to this.

**Comment by gafter** [comment]
See also https://github.com/dotnet/roslyn/pull/16315/files#r95427001

**Comment by gafter** [comment]
There are new test cases related to expression variables in https://github.com/dotnet/roslyn/pull/16467 . I'm leaving the rest for @agocke per @jaredpar .

**Comment by AdamSpeight2008** [comment]
Are there test for CallerInfoAttributes? `local([CallerLineNumber] int x = 0)`
