### ISSUE TITLE
Calculating Diagnostics from analyzers sometime crashes VS

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#16363]
sometimes VS crashes seemingly randomly while using VS with full solution analysis on.

with this call stack.

looks like VS is hitting a condition which previously thought to be can't happen.
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler) Line 152	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.Executor.ComputeDiagnosticsAsync(Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers analyzerDriverOpt, Microsoft.CodeAnalysis.Project project, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.StateSet> stateSets, System.Collections.Immutable.ImmutableDictionary<Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer, Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult> existing, System.Threading.CancellationToken cancellationToken) Line 195	C#
 	[Resuming Async Method]	
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	**Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.Contract.ThrowIfTrue(bool condition, string message) Line 99	C#**
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.Executor.TryReduceAnalyzersToRun(Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers analyzerDriverOpt, Microsoft.CodeAnalysis.VersionStamp version, System.Collections.Immutable.ImmutableDictionary<Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer, Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult> existing, out System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer> analyzers) Line 240	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.Executor.ComputeDiagnosticsAsync(Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers analyzerDriverOpt, Microsoft.CodeAnalysis.Project project, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.StateSet> stateSets, System.Collections.Immutable.ImmutableDictionary<Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer, Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult> existing, System.Threading.CancellationToken cancellationToken) Line 184	C#
>	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.Executor.GetProjectAnalysisDataAsync(Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers analyzerDriverOpt, Microsoft.CodeAnalysis.Project project, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.StateSet> stateSets, bool ignoreFullAnalysisOptions, System.Threading.CancellationToken cancellationToken) Line 111	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.AnalyzeProjectAsync(Microsoft.CodeAnalysis.Project project, bool semanticsChanged, Microsoft.CodeAnalysis.SolutionCrawler.InvocationReasons reasons, System.Threading.CancellationToken cancellationToken) Line 88	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.LowPriorityProcessor.ProcessProjectAsync.AnonymousMethod__0(Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer a, Microsoft.CodeAnalysis.Project p, System.Threading.CancellationToken c) Line 143	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.RunAnalyzersAsync.AnonymousMethod__0(Microsoft.CodeAnalysis.Project v, System.Threading.CancellationToken c) Line 185	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.GetOrDefaultAsync<Microsoft.CodeAnalysis.Project, object>(Microsoft.CodeAnalysis.Project value, System.Func<Microsoft.CodeAnalysis.Project, System.Threading.CancellationToken, System.Threading.Tasks.Task<object>> funcAsync, System.Threading.CancellationToken cancellationToken)	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.RunAnalyzersAsync<Microsoft.CodeAnalysis.Project>(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer> analyzers, Microsoft.CodeAnalysis.Project value, System.Func<Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer, Microsoft.CodeAnalysis.Project, System.Threading.CancellationToken, System.Threading.Tasks.Task> runnerAsync, System.Threading.CancellationToken cancellationToken) Line 183	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.LowPriorityProcessor.ProcessProjectAsync(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer> analyzers, Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.WorkItem workItem, System.Threading.CancellationTokenSource source) Line 143	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.LowPriorityProcessor.ExecuteAsync() Line 56	C#
 	[Resuming Async Method]	
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine) Line 1090	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#

**Comment by srivatsn** [comment]
Fixed by #16371
