### ISSUE TITLE
[Proposal][Optimization] Optimize Autogenerated Property getter/setter to directly access to field

### ISSUE THREAD

**Issue by KalitaAlexey** [dotnet/roslyn#1636]
Let we have a class
```
class A
{
	public int Property
	{
		get;
		set;
	}

	int propertyWithSimpleAssignmentField;

	public int PropertyWithSimpleAssignment
	{
		get
		{
			return propertyWithSimpleAssignmentField;
		}
		set
		{
			propertyWithSimpleAssignmentField = value;
		}
	}

	int propertyWithCustomLogicField;

	public int PropertyWithCustomLogic
	{
		get
		{
			return propertyWithCustomLogicField / 2;
		}
		set
		{
			propertyWithCustomLogicField = value * 2;
		}
	}

	public int field;
}
```

IL code for
```
field = 1;
```
in RELEASE build is 
```
IL_0007:  ldc.i4.1
IL_0008:  stfld      int32 ConsoleApplication1.A::'field'
```

IL code for
```
Property = 2;
```
is
```
IL_000e:  ldc.i4.2
IL_000f:  call       instance void ConsoleApplication1.A::set_Property(int32)
```
but compiler sees property is not virtual so compiler should be sure property getter and setter will not be changed. Compiler may replace calling of virtual function with direct access to field.
It allow us give up of using fields at all.
Sometimes I want to set a breakpoint to a property getter/setter to know where it is referenced, but in RELEASE it may create performance tidbit.

**Comment by GeirGrusom** [comment]
It is inlined by the JIT compiler.

**Comment by KalitaAlexey** [comment]
Are there people who can confirm words of @GeirGrusom ? If it is true, then I am not going to use fields any more

**Comment by GeirGrusom** [comment]
```csharp
public class Foo
{
  public int Bar { get; set; }
}

var foo = new Foo();

foo.Bar = 100;
```

For this code the JIT did the following:

``` asm
lea         rcx,[7FE8D1A4158h]; I'm not *quite* sure why it loads this address into RCX. I assume it's the address of foo.
call        000007FEEC912400; I assume this calls the constructor.
mov         dword ptr [rax+14h],64h; The address of the newly created object is located in rax.
``` 

Looks like the field is inlined to me at least, but I'm no master of either the JIT compiler or AMD64.

**Comment by KalitaAlexey** [comment]
@GeirGrusom If so then it is great. I will use Property more often.

**Comment by mattwarren** [comment]
There's some information on this [MSDN page](https://msdn.microsoft.com/en-us/library/ms973852.aspx#code-snippet-18) about this, it states:

> Table 6 shows the time needed to fetch (and add), and to store, a set of integer instance fields and properties. **The cost of getting or setting a property is indeed identical to direct access to the underlying field, unless the property is declared virtual,** in which case the cost is approximately that of a virtual method call. No surprise there.

**Comment by gafter** [comment]
Unless I hear a reason to do otherwise, I'm going to close this as the need is met by the jit's behavior.

**Comment by Sebazzz** [comment]
Perhaps for access to an inherited abstract property that has been marked in the current class as sealed? That would cause a viable lookup otherwise which is unnecessary if the property or class is marked sealed.
