### ISSUE TITLE
Figure out why features are requesting navigation to out-of-bounds locations

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#16365]
This problem has been patched over twice:
- PR https://github.com/dotnet/roslyn/pull/16357
    - Issue #7660
    - Issue https://devdiv.visualstudio.com/DevDiv/_workitems?id=112211
    - Issue https://devdiv.visualstudio.com/DevDiv/_workitems?id=136895
    - Issue https://devdiv.visualstudio.com/DevDiv/_workitems?id=224318
    - Issue https://devdiv.visualstudio.com/DevDiv/_workitems?id=235409
- PR https://github.com/dotnet/roslyn/pull/5329
    - Issue https://github.com/dotnet/roslyn/issues/4348

**Comment by CyrusNajmabadi** [comment]
Have looked in prism and don't see issues here.  Closing out.
