### ISSUE TITLE
In-place initialization of structs optimization could be observable when ctor has byref args

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#16364]
The following should print ` 1 1 ` :

```C#
    class Program
    {
        public struct Boo
        {
            public int I1;

            public Boo(ref Boo b1)
            {
                this.I1 = 1;
                this.I1 += b1.I1;
            }
        }

        public static Boo v1;

        public static void Main()
        {
            Boo a1 = default(Boo);

            a1 = new Boo(ref a1);
            System.Console.WriteLine(a1.I1);

            v1 = new Boo(ref v1);
            System.Console.WriteLine(v1.I1);
        }
    }
```

It however prints ` 2 1 `

The case with local `a1` is in-place optimized and as such sees its own partially updated state.
That is incorrect.

We had this bug since the times of the native compiler. It is a relatively contrived case, but with addition of `ref` locals and members it would be eventually easier and easier to hit.

I think we should fix this.
The fix could be as simple as disallowing the in-place optimization if struct ctor takes anything by ref. 

These cases are not common and it would be better to be conservative. - I mean it is not worth further analysis to prove that some cases are safe.

**Comment by VSadov** [comment]
not specifically a bug in ref locals, but related to ref-ness

**Comment by jaredpar** [comment]
Why did we add the ref locals language feature tag?  There is nothing involving ref locals here.  

Given this behavior has been around for a long time I'm not sure that we could fix it.  It would be a subtle breaking change.  Especially at this point in the cycle I'm a bit nervous about any changes here.  Very little time for customers to absorb.

**Comment by HaloFour** [comment]
Same as #15715, no?

**Comment by VSadov** [comment]
I have added a "ref" tag because it is easier to reach through a ref local -

```C#
            // make a ref somewhere in the code
            ref var r = ref a1;
. . . 
. . . 
            // the result would vary here 
            // for example it would matter whether we are in a try block or not
            a1 = new Boo(ref r);
```

Then I discovered that ref locals are not really required. There is a repro without ref locals.

As we allow more ref-related features, the problem could get more observable.

**Comment by VSadov** [comment]
Yes it is the same as #15715

**Comment by VSadov** [comment]
I guess this is a dupe then.

**Comment by VSadov** [comment]
@jaredpar    2.1   as in the dupe seems appropriate. 
Especially considering this is so old.

**Comment by VSadov** [comment]
There was another report on this.

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/20087
