### ISSUE TITLE
IForEachLoopStatement needs to be adjusted for multiple iteration variables

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#16372]
Due to deconstruction, it is possible for a foreach loop to have multiple iteration variables

IForEachLoopStatement  needs somehow adjusted to support that. Currently only a single-variable foreach is supported.

**Comment by AdamSpeight2008** [comment]
@VSadov
Could you provide a code example? as I am struggle to picture it.

**Comment by alrz** [comment]
@AdamSpeight2008 `foreach(var (x ,y) in listOfTuples)`

**Comment by AdamSpeight2008** [comment]
So it just save you writing the following?
```C#
foreach(var t in listOfTuples)
  var (x,y) = t;
```

**Comment by alrz** [comment]
@AdamSpeight2008 Yes. Though this issue is not about the syntax -- deconstructions are already implemented), it's about the API exposing it.

**Comment by AdamSpeight2008** [comment]
To me, it throws out my thinking on iterators / IEnumerator that of there being a single yield type. 
especially with the proposed syntax in `foreach` specifically.  It makes more sense to write the following in the case.
`foreach( (var x, var y) in listOfTuples )`

**Comment by alrz** [comment]
@AdamSpeight2008 That's also possible, I believe. It's basically the deconstruction syntax, though you must declare each variable as it is required by foreach i.e. deconstructing to existing variables is not possible.

**Comment by jinujoseph** [comment]
@CyrusNajmabadi  need this for V1 ?

**Comment by CyrusNajmabadi** [comment]
Yes.  We would need this for V1 as this is a standard C# construct.  We can either add ```ImmutableArray<IVariableDeclaration> Declarations { get; }``` to it (to be the most future proof), or just add ```ImmutableArray<ILocalSymbol> Variables { get; }```

I think we would just need the latter.
