### ISSUE TITLE
Proposal: abstract extension class

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#16379]
Currently, when we need a bunch of extension-like methods to be provided by derived classes, we'll have:
```cs
protected abstract Bar ToBar(Foo foo);
// ...
var something = ToBar(foo);
```
While instance extension methods (a variation of #16271) could be used here,
```cs
protected abstract Bar ToBar(this Foo foo);
// ...
var something = foo.ToBar();
```
It is not on par with #11159, e.g. you could not have extension properties etc.
```cs
protected abstract Bar GetProperty(this Foo foo);
// ...
var something = foo.GetProperty(); // could be a property
```
I want to propose that extension declarations be able to be `abstract` in other classes.
```cs
abstract class X {
  protected abstract extension class E : Foo {
    public abstract Bar Property { get; }
  }
}
```
A derived class must provide an implementation for abstract extensions.
```cs
sealed class Y : X {
  protected override extension class E : Foo {
    public override Bar Property => new Bar();
  }
}
```
It might be helpful if extension methods could be also `virtual`, (not to be confused with #258).

**Comment by orthoxerox** [comment]
> It might be helpful if extension methods could be also virtual, (not to be confused with #258).

As in #11211?

**Comment by alrz** [comment]
@orthoxerox Both #258 and #11211 do virtual dispatch on "extended type" i.e. the first paramerter. but in instance extension methods (second example above), virtual applies to the containing type (`this`), not the first parameter.

**Comment by bondsbw** [comment]
I think I like this proposal better than
```c#
protected abstract Bar ToBar(this Foo foo);
```
because the keyword `this` in such a situation could be confusing.

**Comment by alrz** [comment]
The use case will be addressed by shapes (https://github.com/dotnet/csharplang/issues/164).
