### ISSUE TITLE
IDE0030 (Null check can be simplified): Non-equivalent refactoring suggested

### ISSUE THREAD

**Issue by NickCraver** [dotnet/roslyn#16387]
**Version Used**: VS 2017 RC 15.0.26020.0

**Steps to Reproduce**:

1. Start with this a sample method:
```c#
    public string Foo(int? a)
    {
        return a == null ? string.Empty : a.ToString();
    }
```
2. `Ctrl+.` on the body
3. Select "Use null propagation"
4. Observe incorrect suggestion to correct to:
```c#
    public string Foo(int? a)
    {
        return a?.ToString();
    };
```

Screenshot: 
<img width="671" alt="screen shot 2017-01-10 at 09 03 12" src="https://cloud.githubusercontent.com/assets/454813/21809033/f654be50-d713-11e6-99cf-b54de6e16393.png">

**Expected Behavior**: Suggestion should not be made.

**Actual Behavior**: Suggestion is present.

The two pieces of code are not equal. The suggestion will return `null` in the case of `a` being null, not the `String.Empty` it was before.

**Comment by Pilchie** [comment]
@CyrusNajmabadi You already fixed this - can you link the PR and close?

**Comment by CyrusNajmabadi** [comment]
fixed with https://github.com/dotnet/roslyn/pull/15511
