### ISSUE TITLE
[Proposal] When statement

### ISSUE THREAD

**Issue by momijin** [dotnet/roslyn#1638]
### Problem

The switch statement is not modern. But it is very hard to change it. (See #959)
### Proposal

To introduce the when statement in C#. The when statement has follwing feature.
・No case fall through
・Pattern-matching (See #1572) expanded
・Multiple expression
・At when all, executing statements of all matched patterns

The switch statement is made a condition of the current state.
### Syntax

``` C#
when any | all (expression[, expression ..])
{
    case (pattern[, pattern ..]) { statements }
    case (pattern[, pattern ..]) { statements }
    ..
    else { statements }
}
```

The any keyword means to execute statements of a first matched pattern. 
The all keyword means to execute statements of all matched patterns. 
If the expression is appeared more than one times, the pattern in a case is needed same time.
### Example

The following is an example of matching by values.

``` C#
int a = 2;

when any (a)
{
    case(1) {}  // no execute
    case(2) {}  // execute
    case(3) {}  // no execute
    else {}     // no execute
}
```

The following is an example of matching by values with relational operators and logical operators.

``` C#
int a = 2;

when any (a)
{
    case(<= 0) {}         // (a <= 0) == false,          no execute
    case(1 || 2) {}       // (a == 1 || a== 2) == true,  execute
    case(>= 3 && <= 5) {} // (a >= 3 && a<= 5) == false, no execute
}
```

The following is an example of matching by types.

``` C#
object o = new string();

when any (o)
{
    case (is int n) {}     // no execute
    case (is string s) {}  // execute
    else {}                // no execute
}
```

The following is an example of matching by two patterns.

``` C#
bool b1 = true;
bool b2 = false;

when any (b1, b2)
{
    case (true, true) {}   // no execute
    case (true, false) {}  // execute
    case (false, true) {}  // no execute
    case (false, false) {} // no execute
}
```

The following is an example of matching by methods and executing statements of all matched patterns. 

``` C#
string s = "ab";

when all (s)
{
    case (.Contains("a")) {} // s.Contains("a") == true,  execute
    case (.Contains("b")) {} // s.Contains("b") == true,  execute
    case (.Contains("c")) {} // s.Contains("c") == false, no execute
    else {}                  // no execute
}
```

**Comment by dsaf** [comment]
But isn't extending / re-purposing the switch statement exactly something they want to do based on the original proposal?

Imho the biggest problem with the team's original proposal is the imperative nature, but it seems they are aware of it suggesting the following:

```csharp
return match(e)
{
        3 => x,
        string s => s.foo,
        Point(3, int y) => y,
        * => null
};
```

Also, it's not a strong criticism, but I think they don't generally like two keywords directly next to each other.

**Comment by AdamSpeight2008** [comment]
This very similar to the Pattern-Matching proposal(s).

**Comment by dsaf** [comment]
@AdamSpeight2008 you mean the proposal he directly referenced right at the top :)?

**Comment by svick** [comment]
The way I see it, the most distinguishing and also the most problematic feature of this proposal is the special "missing part is the match expression" syntax.

I think that it would require significant work to specify precisely and even then, it would still be confusing and probably wouldn't allow you to do everything. Some questions that would need to be answered (in the following `e` is the matched expression):

1. `e.Contains("a")` is written as `case(.Contains("a"))`. How do you write `"abc".Contains(e)`? The obvious choice (`case("abc".Contains())`) would be ambiguous and confusing.
2. Would `case(-1)` mean `e == -1` or `e == e-1`? (Such condition could make sense for floating point numbers.) How do you write the other one?
3. Can you `await`, invoke or cast the match expression? E.g. `case(await)`, `case(())`, `case((int))`?  
How would you disambiguate cast, invocation and parenthesized expression? E.g. would `case((Color))` mean `(Color)e`, `e(Color)` or `e == (Color)`?

Even if all such problems could be solved, I don't think all this complexity is worth it. Pattern matching and `else if` chains are probably a better choice for these kinds of conditions.

**Comment by momijin** [comment]
@dsaf

> Also, it's not a strong criticism, but I think they don't generally like two keywords directly next to each other.
I Think so too, To use them appropriately is bad. I will close this issue when I think my proposal is covered with `match expression` in this issue.

Thank you for your kind comment.

**Comment by momijin** [comment]
@AdamSpeight2008

> This very similar to the Pattern-Matching proposal(s).
Matching is based on  the Pattern-Matching proposal(#1572).

Thank you for your kind comment.

**Comment by HaloFour** [comment]
The pattern joining aspect of this is quite interesting and I think would fit in with the proposed `switch` enhancements as well as whatever an expression version of that would be:

```cs
switch (shape1, shape2)
{
    case (Rectangle(width, length), Circle(radius)):
    ...
}
```

I don't agree with the implicit use of the variable, though.  I don't know how general condition logic is expected to fit in with pattern matching, if it is at all, but I would rather see a better way to directly refer to the matching type.

There was a proposal somewhere to simplify single argument lambdas using a token like `@` to signify the argument, that could potentially work here.  And they could perhaps be indexed in the case of pattern joining:

```cs
// shorthand for employees.Where(e => e.IsManager);
var managers = employees.Where(@.IsManager);

int x, y;
switch (x, y)
{
    case (@ % 2 == 0, @ % 2 == 1):
        Console.WriteLine("x is even and y is odd!");
        break;
    case (@0 < @1):
        Console.WriteLine("x is less than y!");
        break;
}
```

Although at that point I tend to agree that nested `if`/`else` statements is probably better.

**Comment by paulomorgado** [comment]
Couldn't this be achieved with tuples?

**Comment by momijin** [comment]
@svick

> 1.  e.Contains("a")  is written as  case(.Contains("a")) . How do you write  "abc".Contains(e) ? The obvious choice ( case("abc".Contains()) ) would be ambiguous and confusing.

Your suggestion makes it clear that it is useless in the expresson which does not started with a dot. I think that to solve it the matched expression should bo placed explicitly by place-holder. (Temporarily use @, inspirated @HaloFour proposal)

Case of `"abc".Contains(e)` it is written `case("abc".Contains(@)) `.


>2.Would  case(-1)  mean  e == -1  or  e == e-1 ? (Such condition could make sense for floating point numbers.) How do you write the other one?

Let me confirm whether I don't misunderstand, is `e-1` 0.1 used the real literal ?
If it is so, `case(-1)` means `e == -1`, case of `e == e-1` is written `case(1e-1)`.


>3.Can you  await , invoke or cast the match expression? E.g.  case(await) ,  case(()) ,  case((int)) ?
 How would you disambiguate cast, invocation and parenthesized expression? E.g. would  case((Color))  mean  (Color)e ,  e(Color)  or  e == (Color) ?

Only value, `is` operator, relational operators and expression started with a dot are allowed implicit using matched expression, others are need to use place-holder indicated in item 1. I think that it resolves those ambiguities.


Would the above be an answer? I am afraid whether I misunderstand your intention.

Thank you for your kind comment.

**Comment by momijin** [comment]
@HaloFour

> There was a proposal somewhere to simplify single argument lambdas using a token like  @  to signify the argument, that could potentially work here.

I think so too. It is also necesarry to resolve ambiguities of my proposal. I am grad that this issue including two proposals and many suggestions is useful even a little to make better C# 7.

**Comment by alrz** [comment]
While this can be done with tuples and patterns and `is operator` I think extending the existing `switch` syntax would be better approach, e.g.
```cs
// optional target
switch {
// optional case
when a.Contains("A"): break;
// no break
when (expression) embedded-statement
case (pattern) when (expression)  embedded-statement
}
```
Although, I think the probability of considering this approaches to zero.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
