### ISSUE TITLE
Can reflection consume generic and return ref for field?

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#16383]
Since we have a plan for return ref. Is it would possible to return ref from reflection?

Something like

```C#
FieldInfo fi = typeof(obj).GetField("Transform");
ref Matrix4x4 m = fi.GetValueRef<Matrix4x4>(ref obj);
m.41 = 0;
m.42 = 0;
m.43 = 1;
```

**Comment by HaloFour** [comment]
That would fall under the BCL.  You could suggest that here:  https://github.com/dotnet/coreclr/issues

**Comment by jaredpar** [comment]
There is no way to utilize ref via reflection at this time.  All of the reflection APIs operate in terms of object which can't represent a ref value.  As @HaloFour mentioned this is a dicussion better suited for coreclr though as they control this behavior / API.
