### ISSUE TITLE
IDE0024 (Use expression body for properties): Removing extra whitespace

### ISSUE THREAD

**Issue by NickCraver** [dotnet/roslyn#16386]
**Version Used**: VS 2017 RC 15.0.26020.0

**Steps to Reproduce**:

1. Start with this a sample program:
```c#
class Program
{
    static void Main(string[] args) { }

    private string _prop = "HELLO THERE!";
    public string Prop { get { return _prop; } }

    public string OtherThing => "Pickles";
}
```
2. `Ctrl+.` on `public string Prop { get { return _prop; } }`
3. Select "Use expression body for properties"
4. Observe the line below the `Prop` property being removed, result:
```c#
    public string Prop => _prop;
    public string OtherThing => "Pickles";
```

Screenshot: 
<img width="688" alt="screen shot 2017-01-10 at 08 26 44" src="https://cloud.githubusercontent.com/assets/454813/21807838/8f16cd3c-d70e-11e6-9659-fc798a514c90.png">

**Expected Behavior**: Suggestion should not remove the unrelated line below the property.

**Actual Behavior**: Line below the property is removed.

**Comment by NickCraver** [comment]
A more severe instance of this is when there was no extra line to remove, causing multiple properties to appear on a single line. Here's an example:
<img width="1036" alt="screen shot 2017-01-10 at 08 54 43" src="https://cloud.githubusercontent.com/assets/454813/21808727/89affb62-d712-11e6-8b7d-894115cc6b93.png">

Before:
```c#
public NameValueCollection Form
{
    get { return formVariables; }
}
private NameValueCollection formVariables = new NameValueCollection();
```

After:
```c#
public NameValueCollection Form => formVariables; private NameValueCollection formVariables = new NameValueCollection();
```

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/16987
