### ISSUE TITLE
IDE0027 (Collection initialization can be simplified): Incorrect suggestion with a ternary

### ISSUE THREAD

**Issue by NickCraver** [dotnet/roslyn#16385]
**Version Used**: VS 2017 RC 15.0.26020.0

**Steps to Reproduce**:

1. Start with this a sample program:
```c#
using System.Collections.Generic;
class Program
{
    static void Main(string[] args)
    {
        var condition = args.Length > 0;
        var a = new List<int>();

        var ids = condition ? a : new List<int>();
        ids.Add(4);
    }
}
```
2. `Ctrl+.` on `new List<int>();`
3. Select "Collection initialization can be simplified"
4. Observe incorrect suggestion to correct to:
```c#
        var ids = condition ? a : new List<int>
        {
            4
        };
```

Screenshot: 
<img width="725" alt="screen shot 2017-01-10 at 08 07 08" src="https://cloud.githubusercontent.com/assets/454813/21807251/da4c8222-d70b-11e6-866d-d5c8d2a38ced.png">

**Expected Behavior**: Suggestion should not be made.

**Actual Behavior**: Suggestion is present.

The two pieces of code are not equal. The suggestion only adds in one case of the ternary, rather than always to the result of whichever the ternary chooses.

**Comment by CyrusNajmabadi** [comment]
Thanks for the bug!  Will take a look asap!

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/15504
