### ISSUE TITLE
Setting not persisted: Collapse #regions

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#16392]
**Version Used**: 2.0.0.61308

_Text Editor > C# > Advanced > Collapse #regions when collapsing to definitions_ setting does not seem to be preserved.

1. Export settings
2. Enable the setting above
3. Import the exported settings

**Expected:** The setting to be cleared as it was at the time of export
**Actual:** Stays enabled

**Comment by Pilchie** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/16247 for another option.

**Comment by Pilchie** [comment]
Oops, actually a duplicate of https://github.com/dotnet/roslyn/issues/14810.
