### ISSUE TITLE
Support new VSHPROPID_ActiveIntellisenseProjectContext for context switching in kproj projects

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#164]
From the Web Tools team:

1.       I’ll add a new IVSHierarchy property called VSHPROPID_ActiveIntellisenseProjectContext which will gets or sets the project name of the active intellisense project. This  string will match the value returned from ICSharpProjectRoot::GetFullProjectName.
2.       IVsHierarchy events will be generated when this property is changed just like when VSHPROPID_SharedItemContextHierarchy is changed

We need to consume that new property.

**Comment by pharring** [comment]
Is a string the best currency for this? Would the project's GUID be better?

**Comment by Pilchie** [comment]
In practice project GUID's are not actually unique (even within a solution).  Too many people copy and modify project files without updating the GUID.

**Comment by jasonmalinowski** [comment]
For kproj scenarios, the projects we see are fake projects and not even 1:1 to project files. So I guess the kproj system could cook up their own GUIDs for us, but they're already a project name that's historically used for IntelliSense purposes and supported by other interfaces like IVsContainedLanguageProjectNameProvider.

**Comment by AArnott** [comment]
@Pilchie While I agree people copy projects, their GUIDs *must* be unique in a solution. As soon as VS loads a project with a GUID that collides with an existing project, VS forcibly changes a GUID on a project to force it to be unique again and the new GUID gets written to the project file.

I'm not arguing for names vs. GUIDs. I just wanted to clarify that project GUIDs *are* unique when loaded.

**Comment by DustinCampbell** [comment]
@AArnott They're only unique when loaded in VS though. In MSBuild, aren't the GUIDs the same?

**Comment by AArnott** [comment]
MSBuild doesn't recognize this property or care. No one cares outside VS.
No one will query for this VSHPROPID_ActiveIntellisenseProjectContext
property outside VS as it's a VS-specific property.
