### ISSUE TITLE
Roslyn's editorconfig contains invalid file list

### ISSUE THREAD

**Issue by olegtk** [dotnet/roslyn#16406]
[*.cs,*.csx,*.vb,*.vbx] is invalid syntax for file glob list, you need [{*.cs,*.csx,*.vb,*.vbx}]
No big deal, but apparently users are routinely copying Roslyn's editorconfig: https://developercommunity.visualstudio.com/content/problem/9560/editorconfig-not-working-correctly.html

**Comment by Pilchie** [comment]
Let's just fix this in master ASAP.
