### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests.InteractiveSessionTests.CompilationChain_SubmissionSlotResize [FAIL] on linux debug

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#16402]
https://ci.dot.net/job/dotnet_roslyn/job/dev15-rc3/job/linux_debug_prtest/15/

this is actual error message 

Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests.InteractiveSessionTests.CompilationChain_SubmissionSlotResize [FAIL]
12:46:50       System.FormatException : Input string was not in a correct format.
12:46:50       Stack Trace:
12:46:50             at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
12:46:50             at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
12:46:50          /mnt/j/workspace/dotnet_roslyn/dev15-rc3/linux_debug_prtest/src/Scripting/CSharpTest/InteractiveSessionTests.cs(490,0): at Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests.InteractiveSessionTests.CompilationChain_SubmissionSlotResize()

**Comment by heejaechang** [comment]
added both compiler and interactive since I wasn't sure which team this bug belong to

**Comment by gafter** [comment]
This issue is over a year old, and the test in question appears to be working. Closing. Please reopen if this is still an issue.
