### ISSUE TITLE
Preview warning-highlights look terrible in the dark theme.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#16404]
![image](https://cloud.githubusercontent.com/assets/4564579/21825744/d1ad9a92-d739-11e6-9e02-2a7747f41c1c.png)

**Comment by CyrusNajmabadi** [comment]
Conflicts look fine: 

![image](https://cloud.githubusercontent.com/assets/4564579/21825855/3e34a174-d73a-11e6-9522-fbfe0a80160f.png)

Checking to see why these are so different.

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Looks like we want to tweak the display here for the dark theme.  @Pilchie Says you know how we'd do this.  Right now we have this definition:

```c#
        public PreviewWarningTagDefinition()
        {
            this.BackgroundColor = Colors.Yellow;
            this.DisplayName = EditorFeaturesResources.Preview_Warning;
            this.ZOrder = 10;
        }
```

In the dark theme we'd like:

```c#
        public PreviewWarningTagDefinition()
        {
            this.Border = new Pen(Brushes.Yellow, thickness: 1.5);
            this.DisplayName = EditorFeaturesResources.Preview_Warning;
            this.ZOrder = 10;
        }
```

**Comment by dpoeschl** [comment]
@CyrusNajmabadi Can I convince you that you should just have a different color background in the dark theme, rather than giving it a completely different treatment?

**Comment by CyrusNajmabadi** [comment]
Sure!  What's a good color we should use?  And how would we implement that?

**Comment by miloush** [comment]
I am not sure how the error highlight looks in the light theme, but in the dark one I have to say that the yellow border would be more consistent...

**Comment by dpoeschl** [comment]
Investigating to see if this needs to stay in 15.3

**Comment by CyrusNajmabadi** [comment]
This looks fine now:  

![image](https://user-images.githubusercontent.com/4564579/76693576-b92fe100-6624-11ea-97d8-109fbf73860b.png)
