### ISSUE TITLE
Error list contains spurious errors from much earlier build

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#16411]
As you can see, I've asked for `Build Only` diagnostics in the Error List. And as you can see, there is only one error on build. Yet the error list shows many errors from a previous (now obsolete) version of the source file.

![image](https://cloud.githubusercontent.com/assets/3804346/21831024/b150c4ba-d755-11e6-9317-bd27d62fb0d6.png)

**Comment by heejaechang** [comment]
@gafter is solution reloaded or something between build?

**Comment by heejaechang** [comment]
hmm.. I can't repro this. @gafter do you have some idea on how this happened? otherwise, I don't think this bug is actionable.

**Comment by heejaechang** [comment]
I am going to close this, without repro step, not much i can do. please re-open if it happens again.
