### ISSUE TITLE
All IDE Analyzer should implements IBuiltInAnalyzer

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#16415]
All IDE analyzer should implement IBuiltInAnalyzer for its special treatment in IDE.

**Comment by CyrusNajmabadi** [comment]
Can we document IBuiltInAnalyzer to specify what it is for, and why you would need to implement it?

**Comment by heejaechang** [comment]
added comment on IBuiltInAnalyzer file

**Comment by Pilchie** [comment]
Done
