### ISSUE TITLE
Block comment breaks when caret in /**/ and between */ and hit Enter

### ISSUE THREAD

**Issue by pawchen** [dotnet/roslyn#16417]
This bug is found during code review https://github.com/dotnet/roslyn/pull/16189#discussion_r95245715

**Version Used**: 
VS2015 Update 3

**Steps to Reproduce**:

1.  `/**$$/` // $$ stands for the caret
2.  Hit <kbd>Enter</kbd>

**Actual Behavior**:
```
/**
 * $$/
```

**Expected Behavior**:
Not sure. At least the block comment should be closed. Either insert another `*` or not insert spaces before `/` at all.

**Comment by miloush** [comment]
Or do not insert anything, just break it:
```
/**
$$/
```
Typing anything but `*` at that position would break the comment, so it should be fine for <kbd>Enter</kbd> too. Neither is the actual behavior too unexpected to me, and it is easy spot and fix.

**Comment by diryboy** [comment]
Maybe, but we have existing tests like
```
/**
 *$$/
```
Those cases does not break the block comments, so I think this case should not.

**Comment by miloush** [comment]
I see. I can see arguments both ways, "it should behave the same" vs. "this test is for a comment that is multi-line already". I don't have a preference here, just wanted to point out another option to consider and that what is expected might differ for people familiar and unfamiliar with the feature.

**Comment by diryboy** [comment]
Yes, thanks. I wonder why would people put the caret at that place and hit <kbd>Enter</kbd> in the first place. If that was simply accident, then probably they would not blame the weird result.

PS. VS2013 had similar behavior, so this is not a regression.

**Comment by CyrusNajmabadi** [comment]
I'm clsoing this out.  I genuinely don't see an issue with the current behavior.  the `/**` indicates you're in a string, so this is just hte 'enter' behavior before any following content in the string.  Seems fine to me.
