### ISSUE TITLE
CodeFixes can crash VS

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#16428]
See https://github.com/dotnet/roslyn/issues/15788

**Comment by dpoeschl** [comment]
FYI @jmarolf

**Comment by dpoeschl** [comment]
Might be because it was debug bits. @jmarolf please confirm

**Comment by jmarolf** [comment]
Ah, that is why it crashed on your machine.  But was @333fred also using debug bits?

**Comment by jmarolf** [comment]
Saw @333fred 's comment on https://github.com/dotnet/roslyn/issues/15788 closing
