### ISSUE TITLE
Implement abstract class generates TupleElementNamesAttribute

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#16434]
**Version Used**: VS2015 Update 3

**Steps to Reproduce**:

Lib1:
```cs
public abstract class X
{
  protected abstract void M((int a, int b) p);
}
```

Lib2:
```cs
public class [||]Y : X 
{
  
}
```
Run "implement abstract class" on `[||]`.

**Expected Behavior**:
```cs
public class Y : X
{
  protected override void M((int a, int b) p)
  {
    throw new NotImplementedException();
  }
}
```
**Actual Behavior**:
```cs
public class Y : X
{
  protected override void M([TupleElementNames(...)] (int a, int b) p)
  {
    throw new NotImplementedException();
  }
}
```
My actual scenario is that I created an abstract class in Features project, and implement it in BasicFeatures.

**Comment by Pilchie** [comment]
Why is the compiler not omitting the attributes when it raises things back to source level.  This seems like an issue in the APIs used by the IDE, not the IDE itself.

**Comment by jcouv** [comment]
Reminds me of https://github.com/dotnet/roslyn/issues/12949 (Implement Interface refactoring was outputting the TupleElementNames attribute too) and was fixed.

**Comment by jcouv** [comment]
Added test in https://github.com/dotnet/roslyn/pull/16663 (this issue didn't repro with latest bits).

I'm a little puzzled how VS 2015 update 3 could have refactored tuple syntax (as opposed to outputting `ValueTuple`), since C#7.0 is only supported in VS 2017.

**Comment by jcouv** [comment]
Verified by #16663
