### ISSUE TITLE
Track active item in solution explorer doesn't

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#16446]
In VS2017 Preview 2, "track active item in solution explorer" doesn't do so.

![image](https://cloud.githubusercontent.com/assets/3804346/21865925/ebcd5354-d7fc-11e6-84b8-20bb604b2fad.png)

**Comment by davkean** [comment]
We don't own this, file it against VS.

**Comment by gafter** [comment]
Filed as https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=366859
