### ISSUE TITLE
New caret position when formatting source with Formatter class

### ISSUE THREAD

**Issue by raffaeler** [dotnet/roslyn#16457]
**Version Used**: 1.3.2
I am creating a simple WPF control to edit small snippets. 

With regards to the Formatter class, how can I preserve the correct position of the **caret** after the Formatter returns the new text for the source document?

Thank you

**Comment by Pilchie** [comment]
Inside Visual Studio we use the editor's `ITrackingPoint` support to do that.  Outside Visual Studio, we provide no explicit support.  My recommendation would be to use `Formatter.GetFormattedChanges()` and then apply the changes yourself, tracking adjustments to the caret position as you see fit.
