### ISSUE TITLE
Move System.Text.Encoding.CodePages to PrivateAssemblies

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#16455]
It's currently deployed with Roslyn but it would be better if it was included with minshell. Ideally Roslyn wouldn't deploy any CoreFX assemblies, only assemblies that are specific to Roslyn, to avoid potential duplicate files across VS.

**Comment by jasonmalinowski** [comment]
@tmat You fixed this a few days ago, if I recall?

**Comment by tmat** [comment]
Yes.
