### ISSUE TITLE
Remove NullReferenceExeption handling in our ETA tests

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#16465]
The Dev15 version of MS.VS.Implementation.SimpleTextViewWindow has a bug around CloseView.  It will throw an NRE when hosted outside of Visual Studio.  There doesn't appear to be any way to avoid this NRE and instead the following mitigations were added:

1. Handle the NRE when calling CloseView
2. Ignore NRE in the first chance exception logger

Once this bug is fixed we need to remove these changes.

**Comment by KirillOsenkov** [comment]
Can you e-mail me the details? I've worked around a bunch of nullrefs there so I may have a fix.

**Comment by jaredpar** [comment]
@KirillOsenkov I'll send you details but editor already agreed to fix for RTW so prob easiest to wait a few days.

**Comment by KirillOsenkov** [comment]
I knew it'd be something I've ran into already ;) Sent you a simpler fix using `FormatterServices.GetUninitializedObject()`.

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving out.
