### ISSUE TITLE
Simplify CSharpParseOption constructors

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#16475]
right now, CSharpParseOption constructors are a bit hard to reason what is called when for what.
http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/CSharpParseOptions.cs,46

we should clean those up and remove ones that are not necessary.

see these for more info.
https://github.com/dotnet/roslyn/issues/15797
https://github.com/dotnet/roslyn/pull/16421
https://github.com/dotnet/roslyn/pull/15798

**Comment by AdamSpeight2008** [comment]
We should have more doc-comments on parts of roslyn.

**Comment by heejaechang** [comment]
@AdamSpeight2008 Hi Adam. I am not sure which one are you talking about?

**Comment by OmarTawfik** [comment]
@heejaechang can you take a look at #17113? it is fixing the inconsistencies in parse options reported in #15900.

**Comment by OmarTawfik** [comment]
Addressed in #17113.
