### ISSUE TITLE
Regression around order in which convertibility of arguments is evaluated

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/roslyn#16478]
As found [here](https://github.com/aspnet/Common/issues/181).

**Version Used**: 
2.0.0.61213

**Steps to Reproduce**:

1. Compile and run this:
```c#
using System;
using System.Collections.Generic;

public class Test
{
    public static void Assert<T>(T a, T b)
    {
        Console.WriteLine("Non collection");
    }

    public static void Assert<T>(IEnumerable<T> a, IEnumerable<T> b)
    {
        Console.WriteLine("Collection");
    }
    
    public static void Main()
    {
        string[] a = new[] { "A" };
        StringValues b = new StringValues();

        Assert(a, b);
    }
    
    private class StringValues : List<string>
    {
        public static implicit operator StringValues(string[] values)
        {
            return new StringValues();
        }
        
        public static implicit operator string[] (StringValues value)
        {
            return new string[0];
        }
    }
}
```
using version 2.0.0.61213. Note that the result is "Non collection".

2. Compile it using version 1.3.1.60616 and note that the result is "Collection".

**Expected Behavior**:
We expect the same implicit conversion (and thus Assert overload) to be performed.

**Actual Behavior**:
The other implicit conversion is used instead.

CC @pranavkm

**Comment by Eilon** [comment]
FYI, this was found while updating ASP.NET's codebase to use C# 7. The specific failure case was in an ASP.NET test where it was calling xUnit's Assert methods, which have many overloads, and passing in ASP.NET types that have implicit operator conversions.

**Comment by AlekseyTs** [comment]
It looks like behavior is changed due to type inference change. It used to be impossible to infer type arguments for method 'Test.Assert<T>(T, T)' in the given scenario. Right now compiler infers ```string[]```, the candidate becomes applicable and is considered the best according to the "betterness" rules.

**Comment by pranavkm** [comment]
@AlekseyTs any idea why it compiles and runs with the old compiler if it was impossible to infer the type arguments? There is certainly one case where the compiler does a better job now - from the original work item (https://github.com/aspnet/Common/issues/181)

Added note: looks like the new compiler fixes the overload resolution in the scenario StringValues does not implement IEnumerable<T>. Commenting out the : List<string> portion of the StringValues type declaration successfully compiles with the new compiler. The old compiler fails with an error:

1.cs(21,19): error CS1503: Argument 2: cannot convert from 'Test.StringValues' to 'System.Collections.Generic.IEnumerable<string>'

**Comment by jcouv** [comment]
Tracked by VSO https://devdiv.visualstudio.com/DevDiv/_workitems/edit/369821
