### ISSUE TITLE
Feature Request: Add IntelliSense pre-selection for default, like new

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1647]
When I type `CancellationToken cancellationToken = default(`, can you please pre-select `CancellationToken`, just like the `new` operator?

**Comment by sharwell** [comment]
I think this is the least `Pedantic ;)` issue I've ever seen from you. Love the idea.

**Comment by SLaks** [comment]
Nah; I've filed some other non-pendantic issues too.
Recently, #1524, #1382, #1373, #1276, #534

**Comment by Pilchie** [comment]
Yes, this is definitely a good suggestion (though I'm surprised MRU pre-selection doesn't help you in that specific case).

**Comment by SLaks** [comment]
MRU doesn't help if I just added `System.Threading` via quick fix from the type name.  (which is common, since that namespace isn't in the template)

Actually, on further thought, can you preselect `default(T)` after `=` in non-primitive argument declaration? (since no other expression is valid)

**Comment by sharwell** [comment]
> Actually, on further thought, can you preselect `default(T)` after = in a non-primitive argument declaration? (since no other expression is valid)

Arguably beneficial for all such types, but only required for non-nullable, non-primitive value types.

**Comment by Pilchie** [comment]
Fixed by #6907

**Comment by dpoeschl** [comment]
@slaks said:

> Actually, on further thought, can you preselect default(T) after = in a non-primitive argument declaration? (since no other expression is valid)

Splitting out this part into #7113
