### ISSUE TITLE
Tab formatting inconsistent when splitting string literals on enter

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#16483]
**Version Used**: VisualStudio/public.d15rel/15.026014.00

**Steps to Reproduce**:

1. Create a string literal.
2. Place character at end of string literal.
3. Press enter a few times.

**Expected Behavior**:

I'd expect all the new string literals to have the same alignment.

**Actual Behavior**:

On each enter they align increasingly to the left margin. See:

![image](http://i.imgur.com/ce1eABW.gif)

**Comment by Pilchie** [comment]
I can't repro with d15rel.26117.0.  Are you using tabs or anything?
