### ISSUE TITLE
Suggestion mode when declaring array

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#16481]
**Version Used**: 2.0.0.61308

**Steps to Reproduce**:

```C#
double[] d = new |
```

**Expected Behavior**: Autocomplete list in completion mode, so that you can type `d[`

**Actual Behavior**: Autocomplete list in suggestion mode, saying `<implicit array declaration>`. Implicit array declaration cannot follow `new` as far as I know.

**Comment by Pilchie** [comment]
This is by design, otherwise typing implicit array creation expressions is very difficult.

**Comment by miloush** [comment]
I see, I have mistaken `<implicit array declaration>` for 
```C#
double[] d = { ... }
```
rather than 
```C#
double[] d = new [] { ... }
```
