### ISSUE TITLE
The C# compiler fails when run on Mono

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#16487]
**Version Used**: 2.0.0-rc3-61110-06

**Steps to Reproduce**:

1. Download the Microsoft.Net.Compilers package on macOS/Linux.
2. Run csc.exe from the package using mono with a simple program:

```
$ mono csc.exe HelloWorld.cs
```

**Expected Behavior**:
Build succeeds

**Actual Behavior**:
```
error CS2001: Source file '/Users/joebob/helloworld\HelloWorld.cs' could not be found.
```

**Comment by jcouv** [comment]
Fixed by #16486
