### ISSUE TITLE
Compiler crashes with StackOverflowException when using out var

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/roslyn#16507]
**Version Used**: 
csc.dll, 2.0.0-beta6-60922-08 for .NET Core

**Steps to Reproduce**:

1. Install dotnet-cli 1.0.0-preview4-004233
2. Download this repo:  [roslyn-overflow.zip](https://github.com/dotnet/roslyn/files/705672/roslyn-overflow.zip)
3. Run `dotnet restore` and `dotnet build` on this project: test\Microsoft.DotNet.Watcher.Tools.Tests\Microsoft.DotNet.Watcher.Tools.Tests.csproj

**Expected Behavior**:
Compiles.

**Actual Behavior**:
> error MSB6006: "C:\Users\namc\AppData\Local\Microsoft\dotnet\sdk\1.0.0-preview4-004233\RunCsc.cmd" exited with code -1073741571.
Process is terminated due to StackOverflowException.

The compiler failed by making this change:
```diff
--- MsBuildFileSetFactoryTest.cs	2017-01-13 17:34:06.494445500 -0800
+++ MsBuildFileSetFactoryTest1.cs	2017-01-13 17:28:00.606618500 -0800
@@ -29,19 +29,17 @@
         [Fact]
         public async Task ProjectReferences_OneLevel()
         {
-            TemporaryCSharpProject proj2;
-            TemporaryCSharpProject target;
             _tempDir
                 .SubDir("src")
                     .SubDir("Project2")
-                        .WithCSharpProject("Project2", out proj2)
+                        .WithCSharpProject("Project2", out var proj2)
                         .WithTargetFrameworks("netstandard1.1")
                         .WithDefaultGlobs()
                         .Dir()
                         .WithFile("Class2.cs")
                     .Up()
                     .SubDir("Project1")
-                        .WithCSharpProject("Project1", out target)
+                        .WithCSharpProject("Project1", out var target)
                         .WithTargetFrameworks("netcoreapp1.0", "net451")
                         .WithProjectReference(proj2)
                         .WithDefaultGlobs()
```
See code in its original context: https://github.com/aspnet/DotNetTools/blob/7ee45afed40e85652545f037cd9c3e04dd385493/test/Microsoft.DotNet.Watcher.Tools.Tests/MsBuildFileSetFactoryTest.cs#L147-L182

**Comment by jcouv** [comment]
Thanks for reporting this.
I was able to repro on Windows too. After that I grabbed all the parameters from the detailed log (from `dotnet build /v:d`) and copied them into an rsp file. Then I can repro with a more direct invocation of `csc.exe`:

```
Microsoft.DotNet.Watcher.Tools.Tests> dotnet \repos\roslyn\Binaries\Debug\Exes\csc\csc.exe /noconfig @test.rsp
Process is terminated due to StackOverflowException.
```
As a side-note, this `csc.exe` is version 2.0.0.60922 (Commit Hash: 6dccf33b6...).

After that I tried to repro with a more recent version of `csc.exe` by running: 
```
Microsoft.DotNet.Watcher.Tools.Tests> dotnet \repos\roslyn\Binaries\Debug\Exes\csc\csc.exe /noconfig @test.rsp
```

That one worked (no stackoverflow crash) and produced a `Microsoft.DotNet.Watcher.Tools.Tests.dll`. So I suspect the issue has already been fixed.

However, to be completely confident, I would like to either:
1. run the new `csc.exe` within the dotnet cli.
2. look at the managed stack of the overflow and find the commit/fix that corrected this problem.

I've not been able to do either of those yet. For (1), I tried invoking my own `csc.exe` from dotnet cli, but even with some hacking and file copying I didn't manage to. For (2), I got a dump from the stackoverflow crash but opening it only offers to debug in native mode (so no managed stack). I'll ask for some assistance back in the office.

**Comment by natemcmaster** [comment]
FYI we upgraded to a new CLI (RC4) and it seems [my particular code](https://github.com/aspnet/DotNetTools/commit/5a444fa75ccbd3eba1df2df50362bf048d761e64#diff-4c12f0525b7126c796ff0690c5f36b61R141) now compiles now w/o the SO exception.

**Comment by jcouv** [comment]
Great, that's what I expected. Thanks for the verification.
I'll go ahead and close the issue.
