### ISSUE TITLE
Microsoft.VisualStudio.Shell.15.0 used in Roslyn build requires strong name skipping

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#16506]
It's currently not signed properly.

**Comment by agocke** [comment]
Too work around this, type the following into an elevated Dev command prompt:

`sn -Vr Microsoft.VisualStudio.Shell.15.0,b03f5f7f11d50a3a`

**Comment by jaredpar** [comment]
Fixed now in post-dev15
