### ISSUE TITLE
"Go to definition" not working between F# and C#

### ISSUE THREAD

**Issue by forki** [dotnet/roslyn#16511]
Since F# moved over to Roslyn in the Visual Studio 2017 RC we thought one of the benefits would be to have easier navigation between F# and C#. Unfortunately this is not implemented yet.

@vasily-kirichenko and myself are interested in helping to make that work. Any pointers on where would have to look? 

/cc @KevinRansom @cartermp @dsyme

**Comment by forki** [comment]
I think @nosami implemented it for xamarin Studio, so it must be possible somehow ;-)

**Comment by smoothdeveloper** [comment]
Find usages and rename would also be pretty important once go to definition is working, I assume it relies on similar machinery.

**Comment by nosami** [comment]
@forki Pretty hacky though. I match Roslyn's EntityId with F#'s XmlDocSig. Maybe there are better options for VS now that F# has the Roslyn workspace layer.

**Comment by forki** [comment]
Tbh I'm fine with hacky as long as we get rid of this major complain point

Am 14.01.2017 14:05 schrieb "Jason Imison" <notifications@github.com>:

**Comment by CyrusNajmabadi** [comment]
Which direction do you want to go in? Are you starting in C# and trying to find results in F#, or vice-versa?

**Comment by cartermp** [comment]
@CyrusNajmabadi Bidirectional - in mixed projects I'd say they're equally important.  I'm curious if it's worth doing some temporary work now to enable this or hold off until we get on the roslyn project system.

**Comment by CyrusNajmabadi** [comment]
Right now F# does not use or interoperate with the Roslyn Symbol system.  I also imagine trying to make it do so would be a lot of work.  As such, we'll have to use other means.  To go from C#->F# the following is possible with existing VS apis:

https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivssymbolicnavigationnotify.aspx

https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivsrefactornotify.aspx

These are old crufty APIs that existed pre-roslyn.  But which allowed other languages (like Xaml) to participate in C# operations.

--

Going from F# to C# would be simpler.  In F# if you found a symbol that came from metadata, you could then go access the VSWorkspace and look for a project producing that dll.  You could then find C#/VB symbol in that project using the exposed Roslyn symbolic APIs, and you could then ask Roslyn to navigate to that symbol for you.

**Comment by Pilchie** [comment]
This is #8105.
