### ISSUE TITLE
Support retrieving  iteration index during a for-each without the need for a variable

### ISSUE THREAD

**Issue by tumtumtum** [dotnet/roslyn#1651]
C# is moving more and more towards declarative programming without the need for state/variables unless absolutely necessary. I propose a language feature whereb foreach statements can give you access to the current iteration index without the use of a variable.

The following code:

```
var i = 0;

foreach  (var obj in collection)
{
    Console.WriteLine("Object {0}: {1}', i++, obj);
}
```

Could be replaced with:

```
foreach (var obj in collection)
{
    Console.WriteLine("Object {0}:{1}", foreach.i, obj);
}
```

Nested use-cases use foreach.foreach.i etc.

I'm happy to submit a pull request :-)

**Comment by AdamSpeight2008** [comment]
You could use the overload of Enumerable.Select, that includes the iteration index.
```vb
For Each x In collection.Select( Function(obj, i ) New With {.i = i, .obj = obj} )
  Console.WriteLine("Object {0}:{1}", x.i, x.obj)
Next
```

**Comment by MgSam** [comment]
Is this really a big pain point? The syntax you propose is a little wonky, and doesn't really add much clarity, IMO. 

Also, the way you phrase the request you make it sound like there is a counter that the compiler is currently hiding from you when you write a `foreach`. This is not the case. To implement this the compiler would have to create a counter variable in addition to the iterator variable.

**Comment by tumtumtum** [comment]
Yes the compiler would have to add a counter (I'm not implying otherwise). And no it's not a big pain point and I'm making a suggestion not a demand. I don't think the syntax is wonky but that's just me.

**Comment by aluanhaddad** [comment]
I also think this would be useful, but if tuple support is added to the language #347, this feature request would be implementable with a simple extension method. 
Given the proposed syntax for tuples, consider the following:
```C#
public static IEnumerable<(T element, int index)> WithIndex<T>(this IEnumerable<T> source) =>
    source.Select((element, index) => (element, index));

// consuming code
foreach ((var customer, var index) in customers)
{
    Console.WriteLine(index);
    Console.WriteLine(customer.Name);
}
```

**Comment by reghrafa** [comment]
I like the idea. It is not a pain-point at all but a nice feature :)
But I would prefer something like this:
```C#
foreach (var x in items; int i = 0; i++)
{
    WriteLine(i);
}
```

It could then be used in any kind of loop.
