### ISSUE TITLE
Go To Definition should go to Deconstruct() in deconstructing assignments

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#16529]
When I press F12 on the `=` token in `(a, b) = blah` (where `blah` has a `Deconstruct()`), can you open the `Deconstruct()` method?

Just like F12 already opens operator overloads.

This would help people understand how tuples work in general, and would be quite helpful when navigating an unfamiliar codebase that uses custom deconstructable types.

**Comment by CyrusNajmabadi** [comment]
I might broaden this to include any sort of explicit conversion.  It's a nice idea.

**Comment by SLaks** [comment]
Conversions are less obvious, because they aren't associated with the `=` token (they can also happen at any other conversion site, such as passing a parameter.

**Comment by gafter** [comment]
@SLaks Deconstruction doesn't always happen at the `=`.

```cs
foreach (var (x, y) in e) // deconstruct on each element
var (x, (y, z)) = e; // nested deconstruction
```

**Comment by SLaks** [comment]
Good point.
For nested deconstructions, pressing F12 on `=` could show a `FindSymbolResults` window with every `Deconstruct` method being called (which may include duplicates).  The TODO in my PR will solve that.

For `foreach`, I'm not sure; maybe link to the `in`?

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/issues/18963 (Find All References on Deconstruct method).
