### ISSUE TITLE
Quick Fix: Null Check can be simplified ignores second branch of ternary

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#16520]
**Version Used**: 15.0.26020.0

```C#
var s = "";
var a = s != null ? s.Length : 42;
```

Quick fix produces
```C#
var s = "";
var a = s?.Length;
```

This silently changes the type of `a` to from `int` to `int?` and drops the `42`.

It should be
```C#
var a = s?.Length ?? 42;
```

**Comment by SLaks** [comment]
Note that you technically should not offer this at all if the member returns a nullable type.

For example:
```C#
var e = new Exception();
var s = e != null ? e.Source : "A";
```

This would reduce to 
```C#
var s = e?.Source ?? "A";
```

But that returns a different value if `e` is not null but `e.Source` is.

**Comment by Pilchie** [comment]
Another dupe - can you find the primary and resolve (this is already fixed).

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/15511
