### ISSUE TITLE
VS Error List doesn't show errors from build failure

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#16545]
Ported from https://github.com/dotnet/roslyn-project-system/issues/1185

Build output lists a couple of errors:
![image](https://cloud.githubusercontent.com/assets/782127/21996565/dccb7caa-dbf8-11e6-8133-f62fc98fe85b.png)

Error List doesn't show these errors (just other unrelated warnings):
![image](https://cloud.githubusercontent.com/assets/782127/21996611/1d569d72-dbf9-11e6-8466-6b1eb5cf931c.png)

Restarting Visual Studio to see if it's helpful... fixes the problem.
![image](https://cloud.githubusercontent.com/assets/782127/21996679/6c9b64b2-dbf9-11e6-9ac9-febb0a4dd58a.png)

**NOTE:** Full solution analysis is turned off and this doesn't repro consistently, so very likely a race condition in computing open file intellisense diagnostics.

**Comment by mavasani** [comment]
Tagging @heejaechang and ardalis.

**Comment by mavasani** [comment]
Tagging @ardalis.

**Comment by ardalis** [comment]
FYI, repro'd this today with a different error in another file that was not open at the time. Opening the file where the error is located and then rebuilding does populate the Error List, which was completely empty (no errors, no warnings). After opening the file with the error and rebuilding, the Error List dialog displays the error as well as several warnings (all of which were in the Output window for each build).

Version info: 
![image](https://cloud.githubusercontent.com/assets/782127/22034425/40539764-dcba-11e6-941d-add5ec424e01.png)

Thanks!

**Comment by ardalis** [comment]
You can clone [this repro](https://github.com/ardalis/CleanArchitecture) and open it in VS2017. It had the behavior both yesterday and today (two different VS builds).

**Comment by srivatsn** [comment]
Was this the partial class issue?

**Comment by heejaechang** [comment]
could be.

**Comment by heejaechang** [comment]
@ardalis is this still repro after this fix? (https://github.com/dotnet/roslyn/pull/17071) which should be in the lastest dev15 build? can you try the latest?

**Comment by heejaechang** [comment]
if this doesn't repro any more, I will close it as not repro.

**Comment by ardalis** [comment]
I haven't seen it since January. I think you can probably close the issue and if I encounter it again I will reopen it or file a new issue.
