### ISSUE TITLE
IntelliSense: Lambda types not identified in some generic methods

### ISSUE THREAD

**Issue by CarlLeth** [dotnet/roslyn#16548]
I've looked through all existing issues with "IntelliSense" and "Lambda" and I think this is a similar but so far unreported variant of the issue.

**Version Used**: 
Visual Studio Enterprise 2015
14.0.25425.01 Update 3 (and in all earlier updates)
**Steps to Reproduce**:

The issue is demonstrated twice below: once with LINQ on IEnumerables, and once with a custom class with no overloading (I thought it was an overload resolution problem at first, but the second example implies it's not).

```C#
public static class NoIntellisenseExamples
{
    public static void NoIntellisenseInEnumerableJoin()
    {
        IEnumerable<Book> books = null;
        IEnumerable<Author> authors = null;

        //Intellisense fails on both 'book => book.AuthorId' and 'author => author.Id'
        var test = books.Join(authors, book => book.AuthorId, author => author.Id, (book, author) => new { book, author });
    }

    public static void NoIntellisenseInSimplerCase()
    {
        var books = new Wrapper<Book>();
        var authors = new Wrapper<Author>();

        //Intellisense fails on 'author => author.Id' but works for the book lambda.
        books.Combine(authors, book => book.AuthorId, author => author.Id);

        new Wrapper<Book>().Combine<Author, int>(authors, book => book.AuthorId, author => author.Id);

        //Intellisense fails on both 'book => book.AuthorId' and 'author => author.Id' in both of the following:
        books.CombineExt(authors, book => book.AuthorId, author => author.Id);
        WrapperExtensions.CombineExt(books, authors, book => book.AuthorId, author => author.Id);

        //Intellisense works perfectly here.
        books.ThisWorks(authors, book => book.AuthorId, author => author.Id);

        //Intellisense fails on 'book => book.AuthorId' but works for 'author => author.Id'
        books.ThisAlmostWorks(authors, book => book.AuthorId, author => author.Id);
    }
}

public class Book
{
    public int AuthorId { get; set; }
    public string Title { get; set; }
}

public class Author
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class Wrapper<TInner>
{
    public void Combine<TOuter, TKey>(Wrapper<TOuter> outer, Func<TInner, TKey> innerKey, Func<TOuter, TKey> outerKey)
    { }

    public void ThisWorks<TOuter>(Wrapper<TOuter> outer, Func<TInner, int> innerKey, Func<TOuter, int> outerKey)
    { }
}

public static class WrapperExtensions
{
    public static void CombineExt<TInner, TOuter, TKey>(this Wrapper<TInner> inner, Wrapper<TOuter> outer,
        Func<TInner, TKey> innerKey, Func<TOuter, TKey> outerKey)
    { }

    public static void ThisAlmostWorks<TInner, TOuter>(this Wrapper<TInner> inner, Wrapper<TOuter> outer,
        Func<TInner, int> innerKey, Func<TOuter, int> outerKey)
    { }
}
```
**Expected Behavior**:

Intellisense recognizes types of all lambda arguments.  This was the behavior in all previous versions tested (2010, 2012, and 2013).

![vs2013 intellisense](https://cloud.githubusercontent.com/assets/6820205/22006029/1b00c85a-dc25-11e6-9658-b401efec6ade.png)

**Actual Behavior**:

Intellisense does not recognize types of some of the arguments, as marked in code comments

![vs2015 intellisense](https://cloud.githubusercontent.com/assets/6820205/22006058/51fc764c-dc25-11e6-9a1e-0a77f74643b6.png)
.

**Comment by gafter** [comment]
I am not able to reproduce this in the current VS2017 preview. @CarlLeth can you please confirm that this is fixed?

**Comment by jaredpar** [comment]
Have not heard back from user, closing for now.  Please ping us if you can provide the requested information.

**Comment by CarlLeth** [comment]
Sorry for delay; was not able to get VS2017 to test until today.  All my previously-failing tests now pass, even without automatic brace completion.  Exact confirmed working version is Enterprise 2017 / 15.0.0-RTW+26228.4 with .NET Framework version 4.6.01055.  Thanks and well done!
