### ISSUE TITLE
Please support 'edit and continue' in 'is-expressions with patterns'

### ISSUE THREAD

**Issue by dudikeleti** [dotnet/roslyn#16549]
**Version Used**: 
Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.26020.0 D15REL
Microsoft .NET Framework
Version 4.6.01055
Installed Version: Enterprise

**Steps to Reproduce**:

1. Write an 'is expression' with declaration pattern, e.g. if (item is int i)
2. Put a break point in the 'if' block and  run the program
3. When break, edit something within the 'if' body (block)

**Expected Behavior**:
If the change is something that allowed (see [here](https://github.com/dotnet/roslyn/wiki/EnC-Supported-Edits)), the program should continue to run 

**Actual Behavior**:
EnC not supported

**Comment by gafter** [comment]
This is a dup of #12379 #12435 #12438 and #13333
