### ISSUE TITLE
File Rename has NullReferenceException

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16546]
_From @ardalis on January 16, 2017 23:21_

Trying to rename a file and getting a failure with stack trace shown:

![image](https://cloud.githubusercontent.com/assets/782127/22002270/932d23d0-dc18-11e6-9e3d-ec1d3de0487a.png)

Stack trace:
System.AggregateException : One or more errors occurred. ---> Object reference not set to an instance of an object.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---> (Inner Exception #0) System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.RemoveDocumentCore(DocumentId documentId,Boolean isAdditionalDocument)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentRemoved(DocumentId documentId)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.RenameDocumentOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)<---

_Copied from original issue: dotnet/roslyn-project-system#1202_

**Comment by CyrusNajmabadi** [comment]
Isn't this the same as: https://devdiv.visualstudio.com/DevDiv/_workitems?_a=edit&id=293456&triage=true

I emailed you and @jasonmalinowski  about this.  I'm not sure what is going on here (and i'm not sure how the workspace talks to project systems).  My guess is that it's this code though:

```c#
                var project = hostDocument.Project.Hierarchy as IVsProject3;
                ...
                project.RemoveItem(0, itemId, out var result);
```

Perhaps this is a case when the underlying hierarchy is not an IVsProject3?  But i have no idea when that happens, or what the appropriate thing would be to do in this case.

Can you advise given your expertise on project systems?

**Comment by Pilchie** [comment]
You need to create a .NET Core class library or application to use the new project system.

**Comment by davkean** [comment]
You emailed, but you never sent the bug nor replied to Jason's request for it. :)

I suspect there's some weird interaction here due to the way that CPS works, here's some things you can rely on:

1. If you only interact with the project system via IVsXXX APIs, then the state should be consistent. ie Adding a file, and then immediately querying for that file via the same IVsXXX interface should find it.

2. Adding a file via IVsXXX, I don't think, given the current design, guarantees that we've told Roslyn about it by the time we return./

Perhaps 2 might be the issue? We should talk offline, we have the same issue with our renamer - and I think perhaps we should give that guarantee.

**Comment by davkean** [comment]
To test this, you need to install the .NET Core workload, and create a Console App (.NET Core).

**Comment by CyrusNajmabadi** [comment]
I hate outlook. I literally only have this mail in the thread:

![image](https://cloud.githubusercontent.com/assets/4564579/22007678/8268da42-dc29-11e6-941e-0bf7e1044363.png)

**Comment by CyrusNajmabadi** [comment]
oh.  It's in a folder called "Clutter".  WTF.   What on earth is that folder for??

**Comment by davkean** [comment]
It puts mail in that folder that it thinks your not going to read. For most people that's probably mailing lists, promotional emails, etc, but I'm not surprised that it puts email from real people in there for you. :)

**Comment by CyrusNajmabadi** [comment]
Ok.  installing now.

**Comment by CyrusNajmabadi** [comment]
So the hierarchy here is a [ConfiguredProjectHostObject](https://github.com/dotnet/roslyn-project-system/blob/3f6c9b9995dde7adffa2044b6a5f97403d6852c7/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ConfiguredProjectHostObject.cs)

Not sure the right way to remove documents from those.  Any ideas?

**Comment by CyrusNajmabadi** [comment]
From looking here: https://github.com/dotnet/roslyn-project-system/blob/3f6c9b9995dde7adffa2044b6a5f97403d6852c7/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/AbstractHostObject.cs

It seems like we could likely make this guy implement IVsProject3 (by deferring to the underlying InnerVsProject).  Should hopefully unblock this scenario.

**Comment by davkean** [comment]
Thanks -I'm implementing this now.

**Comment by davkean** [comment]
Okay, I've done that (and this also fixed: https://github.com/dotnet/roslyn-project-system/issues/1216) Cyrus, and I've got further now we get:

```
System.AggregateException : One or more errors occurred. ---> Could not find file 'C:\Users\davkean\Documents\Visual Studio 2017\Projects\ConsoleApp62\ConsoleApp62\Foo.cs'.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---> (Inner Exception #0) System.IO.FileNotFoundException : Could not find file 'C:\Users\davkean\Documents\Visual Studio 2017\Projects\ConsoleApp62\ConsoleApp62\Foo.cs'.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode,IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.InvisibleEditor..ctor(IServiceProvider serviceProvider,String filePath,Boolean needsSave,Boolean needsUndoDisabled)
   at Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace.OpenInvisibleEditor(IVisualStudioHostDocument hostDocument)
   at Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace.OpenInvisibleEditor(DocumentId documentId)
   at Microsoft.VisualStudio.LanguageServices.Implementation.GlobalUndoServiceFactory.WorkspaceUndoTransaction.AddDocument(DocumentId id)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)<---

```

**Comment by CyrusNajmabadi** [comment]
Joy.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski Do you know anything about this code?  I'm curious why this works at all in non-.netcore situations.

**Comment by Pilchie** [comment]
`InvisibleEditor` expects the file to already exist on disk to read from (http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/InvisibleEditor.cs,39),

but looking at `CodeActionEditHandlerService.ApplyAsync` it looks like this might be happening because the *source* document's filepath doesn't exist at http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/CodeActions/CodeActionEditHandlerService.cs,174.

Is there something funky about the source document in the .NET Core project?

**Comment by jasonmalinowski** [comment]
The repro here is unclear to me. Are we renaming the file from solution explorer, or invoking a code action, or...? They start in very different codepaths which is why I'm hesitant to guess and guess wrong.

**Comment by ardalis** [comment]
Starting state is class name and file name of IFoo2 (IFoo2.cs).
Change class name to IFoo in editor. Light bulb appears.
Hit ctrl+. and choose Rename file to match class name (or whatever it says for this operation).
Error shown in screenshot appears. This was in Monday's build.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi, how are we renaming the file? I could imagine that in the old project system, the rename is pushed back to the workspace immediately, but with .NET Core / CPS there is some sort of asynchronous delay.

**Comment by CyrusNajmabadi** [comment]
Rename is accomplished with a File-delete + File-add.  We explicitly accomplush the delete by calling:

```c#
                var project = hostDocument.Project.Hierarchy as IVsProject3;

                var itemId = hostDocument.GetItemId();
                if (itemId == (uint)VSConstants.VSITEMID.Nil)
                {
                    // it is no longer part of the solution
                    return;
                }

                project.RemoveItem(0, itemId, out var result);
```

To add the document, we call EnvDTE.ProjectItems.AddFromFile.

in both cases, everything is Synchronous on the Workspace side.

**Comment by CyrusNajmabadi** [comment]
if things are actually async under the covers, then we need that exposed in the API so that we can appropriately block or await the completion of these operations.

**Comment by Pilchie** [comment]
@davkean sounds like `EnvDTE.ProjectItems.AddFromFile` this part might not be reflected back in the Roslyn workspace by the end of the call?

**Comment by davkean** [comment]
It's not async on when it's added/reflected to the tree. It is async when we tell Roslyn about it, which was my comment above.

I need to figure out how we would get CPS to block on that - the problem is that we're being called back on a non-blocking event on a background thread, and CPS only waits for the tree to be published, nothing else.

Firing up a thread.

**Comment by Pilchie** [comment]
@davkean your PR auto-closed this.  I assume it should remain open?

**Comment by jasonmalinowski** [comment]
@davkean Makes sense. We could update the Roslyn code that is calling AddFromFile to have some abstraction that calls back to CPS to do the appropriate wait, but I could definitely imagine there are other third party callers that would also call AddFromFile and then assume the workspace has been updated. Something to think about.

**Comment by davkean** [comment]
Yeah I think it would be pretty common for people to assume that AddFromFile makes Roslyn aware of it, for example, they might immediately touch the CodeModel.

There are no CPS APIs that you can wait on that will tell you that we've updated the workspace, we ran into a similar problem for rename, and as a workaround we waited on the workspace.

**Comment by jasonmalinowski** [comment]
Incorrectly closed again, @basoundr?

**Comment by basoundr** [comment]
That's bizzare. I did not close this issue. I fetched the changes from upstream and pushed it my fork to keep my master up to date. Guess, that push closed this!

**Comment by davkean** [comment]
Okay, CPS doesn't have anything we can do here right now. We'll need a new extension point, even then there are performance concerns about blocking the language service (however, I don't that's big a deal and we're telling you during evaluation for these and not requiring a design-time build).

Is there a easy way for you to await on the workspace in this case until we can add something here (post RTM)?

**Comment by CyrusNajmabadi** [comment]
I'm a little concerned here.  We're calling a synchronous API that used to have some reasonable beahvior.  i.e. we add a file, and once the call is done, the file has been added.  Now that behavior isn't there :-/

Can we add a new async api that we can call, and then we can at least block on that going through and the workspace being updated?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Unfortunately I don't think so. If @davkean was able to, he'd just be able to fix it entirely on his side with no work from us. 😦

**Comment by CyrusNajmabadi** [comment]
Ok.  Understood.  From talking with @Pilchie We're leaning toward simply disabling this feature for .net core projects.

**Comment by ardalis** [comment]
That (disabling/removing feature) would be too bad; I use this feature all the time via Resharper since it's infinitely faster than using Solution Explorer to perform a rename (and of course when you change a type name, you want the file name to change to match, 99.99999% of the time)...

**Comment by CyrusNajmabadi** [comment]
@ardalis It would only be until we could get in an appropriate fix so that you don't get a crash.  THe feature would still be enabled for other projects.  We'd only be disabling it for the cases where it simply doesn't work today.

**Comment by ardalis** [comment]
That's certainly better than a crash, I agree. :) But as someone working mainly in Core I think it would affect me quite a bit until there's fix / it can be implemented. I understand, though.

**Comment by CyrusNajmabadi** [comment]
@davkean @jasonmalinowski How can i tell if we're in a .net core project?

**Comment by davkean** [comment]
Call `IVsHierarchy.IsCapabilityMatch("CPS")` where IsCapabilityMatch is from this extension: http://index/?leftProject=Microsoft.VisualStudio.Shell.15.0&leftSymbol=dpymnb6wkfpe&file=Utilities.cs&rightSymbol=xcoyv1eszeyw.

**Comment by CyrusNajmabadi** [comment]
Ok.  Trying this out now.

**Comment by CyrusNajmabadi** [comment]
Ok.  I've opened https://github.com/dotnet/roslyn/pull/16683 for that change.
