### ISSUE TITLE
No intellisense (due to unknown type) for delegate arguments

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#16555]
**Version Used**: 2.0.0.61313

**Steps to Reproduce**:

```C#
static void Main(string[] args)
{
    int[] a;

    Array.Sort(a, (x, y) => x.|
    Console.WriteLine();
}
```

**Expected Behavior**: `x` to be resolved of type `int` and autocomplete list shown.

**Actual Behavior**: `x` is treated as of unknown type, hence no intellisense. Repros with single argument delegates too.

**Comment by gafter** [comment]
This appears to work as desired in VS2017 Release Candidate (assuming you have `using System;`). See also #11619.

**Comment by gafter** [comment]
I take that back. Without the closing paren (which the IDE inserts for you) I do not get any intellisense.

**Comment by miloush** [comment]
Yes, I have automatic brace completion disabled, and I confirm that if you put a semicolon or closing parenthesis there it fixes it.

**Comment by CyrusNajmabadi** [comment]
I get:

![image](https://user-images.githubusercontent.com/4564579/198736518-e3943a19-1b5e-40ff-86d3-7cd2df6412b9.png)

which looks correct to me.
