### ISSUE TITLE
Show some kind of diagnostic for invalid EditorConfig values

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#16556]
**Version Used**: 2017 RC

If a Roslyn `.editorconfig` property has an invalid value, the property is silently ignored.
This, combined with the complete lack of documentation for formatting options, and lack of any UI whatsoever, makes it very difficult to use this awesome feature.

Can you make http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Next/Options/EditorConfigDocumentOptionsProvider.DocumentOptions.cs,39 show an `Info` diagnostic in the error list with the exception message (linked to the source line in `.editorconfig`)?
And make the various custom parsers throw detailed localized exceptions instead of failing silently?
 - http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeStyle/CodeStyleHelpers.cs
 - http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Formatting/CSharpFormattingOptions.Parsers.cs

It would also be nice to warn on any property that starts with `csharp_` or `dotnet_` but is not recognized by Roslyn (to catch name typos).

**Comment by SLaks** [comment]
+@Pilchie @kuhlenh @jmarolf

**Comment by SLaks** [comment]
On the flip side, a `.editorconfig` from a newer version of VS that adds more values or properties (especially new languages features for newline options) should ideally not spam the error list.

I'm not sure what the best solution to that is (without compromising on current warnings).
Perhaps add a list of known-but-unsupported names/values that can be updated in service packs (or VSIXes) for existing VS versions?

Also, some of this should perhaps go in the core Editor editorconfig APIs instead of Roslyn.

**Comment by jmarolf** [comment]
@SLaks I agree we need to have a better experience here, thanks for starting the discussion.  @madskristensen [wrote](https://github.com/madskristensen/EditorConfigLanguage) an [extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.EditorConfig) that provides intellisense for editorconfig files.  My current thinking is that we want an experience like this.

**Comment by madskristensen** [comment]
@jmarolf @SLaks That extension also validates Roslyn specific properties in .editorconfig files

**Comment by SLaks** [comment]
Except that it doesn't recognize the (undocumented) formatting options in http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Formatting/CSharpFormattingOptions.cs

**Comment by madskristensen** [comment]
@kuhlenh I didn't now about the undocumented formatting options. What should I do about those? Right now they are flagged as invalid properties in the error list. Would it make sense to add them to Intellisense like the rest?

**Comment by kuhlenh** [comment]
@madskristensen @SLaks we're waiting on telemetry to see if we need *all* the formatting options or not. We hypothesize that some of the formatting options never get changed from the defaults. Once we "finalize" the set of formatting options, their status will go to "documented". Hope that makes sense!

**Comment by madskristensen** [comment]
I'm releasing an update to the extension shortly that doesn't invalidate the undocumented properties. It will be version 1.10.133 or higher

**Comment by Pilchie** [comment]
Thanks @madskristensen!  This seems to be resolved for now - we'll circle back when we know what options we want to document from there.
