### ISSUE TITLE
Multiple condition of one variable, new semantics for C#

### ISSUE THREAD

**Issue by KaptenJon** [dotnet/roslyn#16553]
Instead of:

if((someint > 100 && someint < 100) || someint==0)
{...}

What about:

if((someint > 100 && <100) || ==0)
{...}

**Comment by eyalsk** [comment]
Inequalities is important topic.

**Comment by jcouv** [comment]
I'll go ahead and close this discussion. Please open a new one on csharplang and continue there, if you still feel this is valuable.
Thanks
