### ISSUE TITLE
"Change signature" does not preserve evaluation order of arguments

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#1656]
### Description

The order in which arguments appear in a call determines the evaluation order. When the **Change signature...** refactoring operation is used to reorder parameters of a method, the call sites should be updated in a manner that preserves the original evaluation order.

### Steps to reproduce

First, define the following method.

```csharp
[TestMethod]
public void TestEvaluationOrder()
{
  int x = 3;
  int result = Calc(x++, x++);
  Assert.AreEqual(-1, result);
  Assert.AreEqual(5, x);
}

private static int Calc(int left, int right)
{
  return left - right;
}
```

Second, use the **Change signature...** refactoring operation to reverse the order of the `left` and `right` parameters.

### Expected result

The test continues to pass.

### Actual result

The test fails.

**Comment by Pilchie** [comment]
We've never preserved side effect order in any of our refactorings (introduce local/inline temp, extract method, etc).

**Comment by sharwell** [comment]
@Pilchie For this one, you could by changing the call site to use named parameters in the same order for any call site that involves potentially side-effecting evaluation. :thought_balloon:

**Comment by Pilchie** [comment]
The trouble is the detection of potentially side-effecting evaluation.
