### ISSUE TITLE
Code completion for tuples

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#16565]
IDE should help complete this code `(int word, int) t = (wo$` to `word:$`.

**Comment by kuhlenh** [comment]
cc @CyrusNajmabadi @jcouv @Pilchie

**Comment by DavidArno** [comment]
I'm a little concerned by this idea. If I have a variable `word2` in scope, I really would not want the IDE to autocomplete to `word:` at the point I've typed `(int word, int) t = (wo$`.

**Comment by CyrusNajmabadi** [comment]
intellisense doesn't mean that it will autocomplete.  THis will be a declaration/reference point.  Meaning we show you the options, but we don't auto-select/complete anything.  You can explicitly try to select and complete something though.

**Comment by DavidArno** [comment]
Great. Thanks for the clarification, @CyrusNajmabadi.

**Comment by jcouv** [comment]
It looks like this was fixed for C#, but not VB. Can you confirm?

**Comment by CyrusNajmabadi** [comment]
This is how it works:

![image](https://github.com/dotnet/roslyn/assets/4564579/cdaa4197-f33f-4af1-8f77-6df4684a959f)
