### ISSUE TITLE
Disable resolving conflicts during rename

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#16560]
It looks like conflicts during renaming refactoring are resolved automatically. Is there a way to disable that? For example, I want to rename a method parameter to a name that is already declared in the class scope and this feature is blocking me.

**Comment by Pilchie** [comment]
We do not have a way to do this when there is an automatic resolution to the conflict.

**Comment by miloush** [comment]
I thought I have seen  "developers know what they are doing" somewhere but never mind, thanks for confirmation. :-)

**Comment by Pilchie** [comment]
We do allow you to commit even if you have unresolvable conflicts, but we don't currently have a way to prevent the resolution of the ones we know how to commit.  It's an interesting idea.
