### ISSUE TITLE
Inline Rename: Renaming a method to "Finalize" in C# crashes VS

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#16567]
Copied from [VSO](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems?id=365693&projectId=0bdbc590-a062-4c3f-b0f6-9383f67865ee&src=alerts&src-action=cta&fullScreen=true&_a=edit), also on Connect at https://connect.microsoft.com/VisualStudio/feedback/details/3118377/unknown-hard-error-and-application-crash-using-vs15-enterprise.

**Version Used**: VS 2017 RC

```C#
class C
{
    ~C() { }
    void M() { }
}
```

Rename `M` to `Finalize`  Note that you have to have an existing destructor to crash.

**Comment by CyrusNajmabadi** [comment]
What is actually causing the crash?
