### ISSUE TITLE
SyntaxGenerator does not support type constraints

### ISSUE THREAD

**Issue by kentcb** [dotnet/roslyn#1658]
Type constraint support is conspicuously missing from several methods in `SyntaxGenerator`. In such cases in which type constraints are relevant, `default(SyntaxList<TypeParameterConstraintClauseSyntax>)` is passed through to the `SyntaxFactory`.

Is there a reason for this? Should the relevant APIs be extended? An example would be:

```C#
public abstract SyntaxNode MethodDeclaration(
    string name,
    IEnumerable<SyntaxNode> parameters = null,
    IEnumerable<string> typeParameters = null,
    IEnumerable<SyntaxNode> typeConstraints = null,
    SyntaxNode returnType = null,
    Accessibility accessibility = Accessibility.NotApplicable,
    DeclarationModifiers modifiers = default(DeclarationModifiers),
    IEnumerable<SyntaxNode> statements = null);
```

Here, I've added the `typeConstraints` parameter. I've added it after `typeParameters` because that seems most natural and correct, despite it being a breaking change.

**Comment by mattwar** [comment]
SyntaxGenerator has the WithTypeParameter and WithTypeConstraint API's for adding type parameters and constraints.

**Comment by kentcb** [comment]
@mattwar yes, this is what I used to get around this problem. However, it makes no sense to me why `SyntaxGenerator. MethodDeclaration ` has support for everything else - even for the type parameter names! Surely if you can specify the type parameter names you should also be able to specify their constraints. It's inconsistent.

**Comment by mattwar** [comment]
There is currently no common abstraction for constraints in the SyntaxGenerator model. VB & C# manage them different within type and method declarations. They also need to correspond to a specific type parameter.  This is why I went with a design that requires you to add the constraints on after the method is first declarated.
