### ISSUE TITLE
update default vssettings to include new code style settings

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#16599]

**Comment by jasonmalinowski** [comment]
@jmarolf What does this bug mean today? If I do reset settings, it won't actually reset codestyle because it won't reapply the defaults?

**Comment by jmarolf** [comment]
@jasonmalinowski correct there is a xml file that get deployed with VS that contains all the default settings.  We will want to update this to contain all of the new rules that we've added in the past year.

**Comment by jasonmalinowski** [comment]
@jmarolf Any idea if this still matters over a year later? Clearly we haven't been updating it and nobody has noticed?

**Comment by jmarolf** [comment]
That is up to y'all to decide.  Basically there will be hard-to-repro bugs around setting round-tripping and syncing settings for the for-seeable future until this is fixed.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of clarity.
