### ISSUE TITLE
[Failing test] CSharpExtractInterfaceDialog.xml & CSharpGenerateTypeDialog.xml & BasicExtractInterfaceDialog.xml

### ISSUE THREAD

**Issue by drognanar** [dotnet/roslyn#16602]
The CSharpExtractInterfaceDialog test fails sporadically:

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2/322/

**Comment by drognanar** [comment]
cc @Pilchie

**Comment by dpoeschl** [comment]
The wrong file is open after ExtractInterface

Actual and expected items don't match:
Expected:
```C#
class C : ITest
{
    public void M() { }
}
```

Actual: 
```C#
interface ITest
{
    void M();
}

This does not repro locally for me.

**Comment by dpoeschl** [comment]
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_prtest/318/ for a similar failure but in GenerateType

**Comment by dpoeschl** [comment]
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_prtest/354/console for BasicExtractInterfaceDialog
