### ISSUE TITLE
[Failing test] BasicChangeSignatureDialog.xml

### ISSUE THREAD

**Issue by drognanar** [dotnet/roslyn#16601]
The BasicChangeSignatureDialog fails sporadically:

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0/385/

**Comment by drognanar** [comment]
cc @Pilchie

**Comment by dpoeschl** [comment]
Null reference on Change Signature invocation (it seems).

![image](https://cloud.githubusercontent.com/assets/235241/22167699/ff0e971c-df1c-11e6-83ae-ec37ff017f27.png)

This does not repro for me locally.

**Comment by dpoeschl** [comment]
Ported to new test framework, appears fixed in https://github.com/dotnet/roslyn/pull/17505
