### ISSUE TITLE
Cannot create a portable library targeting previous versions

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16607]
_From @davkean on January 19, 2017 1:33_

Build: 26114.2

This is with the desktop workload installed.

![image](https://cloud.githubusercontent.com/assets/1103906/22090064/6c2c0242-de43-11e6-92c3-24c3a88339e1.png)

_Copied from original issue: dotnet/roslyn-project-system#1240_

**Comment by davkean** [comment]
@Pilchie This is a pretty big regression - can you please triage this?

**Comment by Pilchie** [comment]
This is by design - there is no longer support for creating PCLs targeting older platforms, though you can still Open them.

**Comment by davkean** [comment]
If I change .NET Framework to 4.0, then I can continue to target old platforms. You've just made it harder - and more confusing.
