### ISSUE TITLE
[Failing test] CSharpRename.xml

### ISSUE THREAD

**Issue by drognanar** [dotnet/roslyn#16603]
The CSharpRename test fails:

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3/394/

**Comment by drognanar** [comment]
cc @Pilchie

**Comment by dpoeschl** [comment]
Marker 'Program' not found in text: 
class SomeOtherClass
{
    void M()
    {
        Program p = new Program();
    }
}

**Comment by dpoeschl** [comment]
This has been ported to the new test framework.
