### ISSUE TITLE
Dictionary Initializers or Index Initializers: What is the correct term to use?

### ISSUE THREAD

**Issue by rmaclean** [dotnet/roslyn#1660]
There is some confusion, at least I have, around the name of he new C# 6 feature. Is it called `Dictionary Initializers` or if it is called `Index Initializers`? Both here & on various websites the two different terms are used almost interchangeably. 

For example on the [roadmap](https://github.com/dotnet/roslyn/wiki/Languages-features-in-C%23-6-and-VB-14) it is dictionary, but in the [feature description document](http://www.codeplex.com/Download?ProjectName=roslyn&DownloadId=930852) it is index. 

Personally I hoping for Index, since this has more potential use beyond dictionaries and internally it is using indexers.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
