### ISSUE TITLE
Please store nuget.exe in a global directory so that restore.cmd doesn't need to download it for every working tree

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#16619]

**Comment by jasonmalinowski** [comment]
@alrz: we generally would want to avoid editing global paths to keep your environment fairly isolated. I wouldn't imagine this would be much of a problem, in any case. How is it impacting you?

(cc @jaredpar who would be curious to know at least)

**Comment by jaredpar** [comment]
I'm unclear what this issue is asking.  Can you elaborate?

**Comment by alrz** [comment]
I use multiple worktrees on ramdisk and hdd and restore.cmd downloads nuget.exe for each one. In contrast, all other dependencies are global (as it seems so). The bottom line is that my internet connection isn't so fast and I'm impatient to wait to download nuget.exe every time I create a worktree, alternatively I could copy/past nuget.exe. I'm asking if it's possible restore.cmd download nuget.exe in a global directory (or even temp) so it's shared between all working trees.

**Comment by jaredpar** [comment]
I'm surprised that NuGet.exe stands out as a problem in a slow internet environment as compared to the large amount of packages that we restore.  My package folder usually measures in the gigs and changes very frequently while the NuGet.exe binary is small and changes very rarely.  On average it changes maybe 3-4 times a year and hence should never be a frequent source of downloads.
