### ISSUE TITLE
Unexpected code path is taken in the Binder while binding a pattern

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#16616]
According to the comments in several places, the following method is not supposed to be called during normal binding process.
```  
private BoundExpression BindQualifiedName(QualifiedNameSyntax node, DiagnosticBag diagnostics)
```
However, it appears that binding of a pattern violates that (see https://github.com/dotnet/roslyn/pull/16525).

**Comment by AlekseyTs** [comment]
@gafter FYI

**Comment by gafter** [comment]
A comment is *documentation*, not executable code.

**Comment by gafter** [comment]
Doc comments have been updated in https://github.com/dotnet/roslyn/issues/25567
