### ISSUE TITLE
Intellisense doesnt suggest <param> tags for indexers

### ISSUE THREAD

**Issue by pdelvo** [dotnet/roslyn#1661]
```csharp
public class Foo
{
    /// <summary>
    /// A indexer.
    /// </summary>
    /// <#
    /// <returns> foo. </returns>
    public string this [string foo]
    {
        get { return foo; }
    }
}
```

If the cursor is at # and intellisense is up "param name="foo"" doesnt show up. It should work for indexers the same way it works for methods. I can create a PR for that.

**Comment by Pilchie** [comment]
@rchande  can you take a look at the PR and merge once reviewed?
