### ISSUE TITLE
Transitive dependencies that are not referenced cause type loading issues.

### ISSUE THREAD

**Issue by saquibmian** [dotnet/roslyn#16627]
I'm running into a strange scenario, and I'm not sure if it's a bug or if it's intended behaviour. 

**Version Used**: 
Microsoft.CodeAnalysis.CSharp @ 1.3.2

**Steps to Reproduce**:
I have three projects:
- Project A defines a type called `Serializer` and references Newtonsoft.Json. 
- Project B defines a type call `Program` that has a public field of type `A.Serializer` (and references A). 
- Project C doesn't reference any project, but runs a program that loads B in an `MSBuildWorkspace`, and iteratates through `Programs` fields, and their type's fields, etc. 

The scenario I'm seeing is that because `B` doesn't reference a transitive dependency (Newtonsoft.Json), the msbuild workspace is not able to resolve the type and returns an error type. Here's some code:

## Project A, Serializer.cs (references Newtonsoft.Json only)

```csharp
public class Serializer {
	public JsonSerializer _serializer = new JsonSerializer();
}
```

## Project B, Program.cs (references A only)
```csharp
class Program {
	private Serializer _serializer = new Serializer();
}
```

## Project C, Main.cs (references no one)
```csharp
class Program {
	static void Main( string[] args ) {
		Task.Run( async () => await AsyncMain() )
			.ConfigureAwait( false )
			.GetAwaiter()
			.GetResult();
	}

	static async Task AsyncMain() {
		using( var workspace = MSBuildWorkspace.Create() ) {
			var proj = await workspace.OpenProjectAsync(
				@"..\B\B.csproj"
			);

			var compilation = await proj.GetCompilationAsync();
			var type = compilation.GetSymbolsWithName(
				predicate: n => true,
				filter: SymbolFilter.Type
			).OfType<ITypeSymbol>().FirstOrDefault();

			var members = type.GetMembers();
			LogErrorTypeFields( type );
		}

		Console.ReadLine();
	}

	static void LogErrorTypeFields( ITypeSymbol type ) {
		var members = type.GetMembers();
		foreach( var member in members ) {
			var field = ( member as IFieldSymbol );
			if( field == null ) {
				continue;
			}

			if( field.Type is IErrorTypeSymbol ) {
				Console.WriteLine( $"in {type.Name}, {field.Name} is errortype ({field.Type})" );
			} else {
				LogErrorTypeFields( field.Type );
			}
		}
	}
}
```

**Expected Behavior**:
I don't know. I believe this may be expected, because `A._serializer` is marked public, and is therefore an exported type (if I mark it private, I can't see it in `GetMembers()` at all). At runtime there won't be any problem, because the transitive dependency will be loaded into the appdomain. But the compiler seems to require it when I'm doing analysis.  

**Actual Behavior**:
The output is:
```
in Serializer, _serializer is errortype (Newtonsoft.Json.JsonSerializer)
```

Is this a bug? I discovered this when some analyzers we have that inspect the object graph would fail if (unused) transitive dependencies weren't referenced.

**Comment by Pilchie** [comment]
This is by design - the compiler only considers types that it is given explicit references to.

**Comment by saquibmian** [comment]
Thanks for confirming, that makes sense for a lot of reasons (conflict resolution among transitives being one). Feel free to close this issue!
