### ISSUE TITLE
Code Style: Suggest to use identical parameter names across method overrides

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#16622]
It is allowed to use different names but it is most likely not desirable.

**Comment by alrz** [comment]
@Pilchie Is this part of FxCop analyzers? I'd like to know that what analyzers are more likely to be part of Roslyn. I suppose where we suggest to use other language features it'll go to Roslyn, otherwise it belongs to FxCop (or whatever). This feels like to be of the latter category. However, I like these to be built-in in the IDE since installing a nuget for these is awkward and possibly undesirable. For instance, If I want to run #16621 on `CSharpSyntaxGenerator` I shouldn't really need to install FxCop on Roslyn!

**Comment by alrz** [comment]
I suppose this also belongs to FxCop analyzers.

**Comment by CyrusNajmabadi** [comment]
@pilchie should we move to this to Roslyn-analyzers?

**Comment by Youssef1313** [comment]
@CyrusNajmabadi There is already [CA1725](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1725) for this purpose. I think this can be closed?

**Comment by CyrusNajmabadi** [comment]
Indeed.  Clsoing out.
