### ISSUE TITLE
Quick Fix for inconsistent accessibility diagnostics

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#16632]
This should be recursively applied to CS0050 through CS0061 diagnostics.

Could be generalized as "Change accessibility" refactorings.

**Comment by Pilchie** [comment]
Actually, this is a duplicate of #10337.

**Comment by Pilchie** [comment]
Actually, no this is slightly different

**Comment by CyrusNajmabadi** [comment]
Closing as we have decided this is not something we want to invest in.
