### ISSUE TITLE
Internal exceptions in CSharpNamingStyleDiagnosticAnalyzer and CSharpRemoveUnnecessaryImportsDiagnosticAnalyzer when using compilation.WithAnalyzers().GetAllDiagnosticsAsync() in 2.0.0-rc2

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#16644]
**Version Used**: 
2.0.0-rc2 (same code works perfectly in 1.3.2)

**Steps to Reproduce**:
[RoslynAnalyzerIssue.zip](https://github.com/dotnet/roslyn/files/718737/RoslynAnalyzerIssue.zip)

```csharp
var featuresAssembly = Assembly.Load("Microsoft.CodeAnalysis.Features");
var csharpFeaturesAssembly = Assembly.Load("Microsoft.CodeAnalysis.CSharp.Features");
var hostServices = MefHostServices.Create(new[] {
    Assembly.Load("Microsoft.CodeAnalysis.Workspaces"),
    Assembly.Load("Microsoft.CodeAnalysis.CSharp.Workspaces"),
    featuresAssembly,
    csharpFeaturesAssembly
});
var projectInfo = ProjectInfo.Create(
    ProjectId.CreateNewId(), VersionStamp.Create(), "_", "_", LanguageNames.CSharp,
    metadataReferences: new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) }
);
var workspace = new AdhocWorkspace(hostServices);
var sourceText = SourceText.From("class Program { static void Main() {} }");
var documentId = DocumentId.CreateNewId(projectInfo.Id);
var solution = workspace.CurrentSolution
    .AddProject(projectInfo)
    .AddDocument(documentId, "_", sourceText);
workspace.TryApplyChanges(solution);

var analyzers = new[] {
    new AnalyzerFileReference(featuresAssembly.Location, new AssemblyLoader(featuresAssembly)),
    new AnalyzerFileReference(csharpFeaturesAssembly.Location, new AssemblyLoader(csharpFeaturesAssembly)),
}.Select(r => r.GetAnalyzers(LanguageNames.CSharp)).Aggregate((a, b) => a.AddRange(b));

var compilation = await solution.GetProject(projectInfo.Id).GetCompilationAsync();
var diagnostics = await compilation.WithAnalyzers(analyzers).GetAllDiagnosticsAsync().ConfigureAwait(false);

// look at diagnostics here

private class AssemblyLoader : IAnalyzerAssemblyLoader {
    private readonly Assembly _assembly;

    public AssemblyLoader(Assembly assembly) {
        _assembly = assembly;
    }

    public Assembly LoadFromPath(string fullPath) => _assembly;
    public void AddDependencyLocation(string fullPath) {}
}
```

**Expected Behavior**:
Variable `diagnostics` is empty -- `SourceText` has no issues.

**Actual Behavior**:
Variable `diagnostics` contains two items:

warning AD0001: Analyzer 'Microsoft.CodeAnalysis.CSharp.Diagnostics.NamingStyles.CSharpNamingStyleDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

warning AD0001: Analyzer 'Microsoft.CodeAnalysis.CSharp.RemoveUnnecessaryImports.CSharpRemoveUnnecessaryImportsDiagnosticAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Diagnostics.AnalyzerOptions' to type 'Microsoft.CodeAnalysis.Diagnostics.WorkspaceAnalyzerOptions'.'

**Comment by ashmind** [comment]
@dpoeschl In my understanding the fix suppresses those analyzers -- but how should I change my code to make those work? I can't create `WorkspaceAnalyzerOptions` directly since it's `internal`.

**Comment by sharwell** [comment]
@ashmind These analyzers are not currently usable outside of the IDE. We have a couple of projects for tracking issues related to resolving this:
https://github.com/dotnet/roslyn/projects/4
https://github.com/dotnet/roslyn/projects/18

**Comment by ashmind** [comment]
@sharwell For style I understand, but `CSharpRemoveUnnecessaryImportsDiagnosticAnalyzer` uses workspace just to get an `IUnnecessaryImportsService` -- why wouldn't that work in `AdHocWorkspace` ?
