### ISSUE TITLE
Member access in nameof in instance field initializer fails to compile

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1664]
Source:

``` C#
class C {
    string x = nameof(x.ToString);
} 
```

Error CS0236: A field initializer cannot reference the non-static field, method, or property 'C.x'

Removing the member access (`nameof(x)`) makes it compile fine.

**Comment by theoy** [comment]
Ping @MadsTorgersen - but I'd be happy to chalk this as By Design.

/cc @AnthonyDGreen

**Comment by SLaks** [comment]
Why would this be by design?
How is `x.Member` worse than `x`, given that `x` is not evaluated in either case?

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
