### ISSUE TITLE
Please have the ternary operator work as a unary operator as well

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/roslyn#1665]
Hi,

I very often come across scenarios where I want to assign a value if a condition is satisfied.
Sometimes a `if` statement is too verbose, so is the ternary.

So my suggestion is to please make the 2nd argument of the ternary operator optional so we can substitute `x = flag ? 10 : 0` or more common `x = flag ? "selected" : null` with `x = flag ? 10`;`and`x = flag ? "selected"`.

This could be very helpful in associated technologies such as in ASP.NET MVC Razor syntax, XAML, and others.

Here's how it can be used in razor: `<div class='container @(active ? "active")'/>`

**Comment by KalitaAlexey** [comment]
It is a bit confusing. And your wrote with error
You suggest
```
int x = 5;
x = flag ? 10;
```
But your example with razor equal to
```
string class = "container " + (active ? "active");
```
You think must be available something like this?

**Comment by markusjohnsson** [comment]
What would this mean then:

```
var x = 3;
x = (flag1 ? 5) + (flag2 ? 10);
```

**Comment by weitzhandler** [comment]
So I'm not sure what the `false` part should be, I believe it shouldn't return a nullable but rather a default value, so in your above example `x` will be assigned to `0` if both flags are `false`.
As per the Razor result, it will be default(string), which will be `null`.

**Comment by markusjohnsson** [comment]
Yeah, but then `x = flag ? 10` would result in `x = 0` for `flag = false`, not the same as in your first example (i.e. not the same as `if (flag) x = 10`).

**Comment by weitzhandler** [comment]
You're right I've updated my 1st post.

**Comment by gafter** [comment]
@weitzhandler How would the precedence work in
`(a ? b ? c : d)`
? Is this the same as
`(a ? (b ? c) : d)`
or
`((a ? b) ? c : d)`
?

**Comment by weitzhandler** [comment]
I guess it should be same or after the full ternary operator

**Comment by dsaf** [comment]
Compare this:

```csharp
if ((2 > 3 ? 4) > 5) {}
```
...to this:
```csharp
if ((2 > 3 ? 4 : 0) > 5) {}
```
In the first case I need to remember that the default value is ```0``` and spend few seconds figuring that out. The problem exists, but I am not sure this syntax is a solution.

**Comment by weitzhandler** [comment]
When extension methods were introduced people were also paranoid about it
but we got used to it and now ex properties is baking.
In not saying caution should not be taken but I do think it's still worth
consideration. I don't think it's something hard to get used to after all.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
