### ISSUE TITLE
Idea: encapsulating mutable property operator?

### ISSUE THREAD

**Issue by ziriax** [dotnet/roslyn#16665]
I love the C# expression body syntax, that allows me to write simple getonly properties like

`public string FullName => $"{FirstName} {LastName};`

However, I often need to encapsulate mutable properties, and that still requires writing set/get accessors.

```
public IController Controller 
{
   get { return nestedChild.Controller; }
   set { nestedChild.Controller = value; }
}
```

I guess it can't be hard to support some kind of "binding" operator, that let's one write instead of the verbose code above:

`public IController Controller <=> nestedChild.Controller;`

But surely a good reason must exist that such a simple feature is part of C#?

Thanks,
Peter

**Comment by jnm2** [comment]
I think this could be cool if

**Comment by jnm2** [comment]
I think this could be cool we gained this ability via a mechanism to delegate any member definition to a member of some other object.

**Comment by alrz** [comment]
```cs
public ref IController Controller => ref nestedChild.Controller;
```

**Comment by alrz** [comment]
Note: the above won't work if the target Controller is a property, in that case you couls use a generators.

**Comment by eyalsk** [comment]
You can also use the new C# 7.0 syntax:
```
public IController Controller 
{
   get => nestedChild.Controller;
   set => nestedChild.Controller = value;
}
```
Not as short as what is proposed but still something I guess. :)

**Comment by Ziriax** [comment]
The syntax I suggested also makes some mathematical sense: `A.prop <=> B.prop` means that the value of `A.prop` is x if and only if the value of `B.prop` is also x ;-)

**Comment by Ziriax** [comment]
One could even imagine a very simple mixin system being implemented like this:

```
public class Pegasus : Animal, IBird <=> m_Bird, IMamal <=> implicit m_Mamal
{
       IBird m_Bird;
       IMamal m_Mamal;
}
```

The compiler would then just delegate all methods of the `IBird` and `IMamal` to the nested fields. If members are added or removed from the interfaces, everything automagically compiles, no refactoring is needed.

Although in this case, the `<=>` operator seems redundant syntax...

But I'm getting carried away here, mixins are really another issue ;-)

**Comment by eyalsk** [comment]
@Ziriax It might worth writing a separated proposal about mixins even though there are quite a few proposals about it. :)

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
