### ISSUE TITLE
Discard incorrectly displayed in IDE

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#16667]
This is with some early RTM bits.

- [x] Colorization (fixed by https://github.com/dotnet/roslyn/pull/20561)
- [ ] Quick Info
- [x] Triggered completion (started a [change](https://github.com/jcouv/roslyn/tree/complete-discard) for this, but I actually think this doesn't repro)
- [ ] Go To Definition
- [ ] Generate Method

The "long" discard is **colorized** wrong (it is blue but should be white). Hovering over the discard should show QuickInfo with "int _" at least, but currently shows nothing.
![image](https://cloud.githubusercontent.com/assets/12466233/22171897/c3bb9f30-df4d-11e6-82a9-0be0bf69d62d.png)

![image](https://cloud.githubusercontent.com/assets/12466233/22171916/43a499b8-df4e-11e6-8f8b-a3cc136c683f.png)

![image](https://cloud.githubusercontent.com/assets/12466233/22171922/80480184-df4e-11e6-85ae-fffdacdcd7cc.png)

![image](https://cloud.githubusercontent.com/assets/12466233/22178037/1203a528-dfe1-11e6-8501-cd584a4224ab.png)

![image](https://cloud.githubusercontent.com/assets/12466233/22178009/4529b9c0-dfe0-11e6-84d3-9135d496ac9b.png)

Also, the **quick info** for short discard could be improved. It should probably have an additional description "(discard variable)", in the same way that locals show "(local variable)".
![image](https://cloud.githubusercontent.com/assets/12466233/22171932/b7593828-df4e-11e6-9a71-e7e0a159662d.png)

**Triggered completion** on a short discard is wrong if there is a variable that starts with an underscore.
In the following example, typing `ctrl+space` completes the underscore to "_something".
```C#
int _something = 4;
M(out _$$);
```

**Goto definition** on a discard (short or declaration expression) gives a pop-up. I'm not sure if that is what we want.
![image](https://cloud.githubusercontent.com/assets/12466233/22178029/b527f0ca-dfe0-11e6-9374-3e95ef305314.png)

The **red squiggles** on short discard are barely visible (this is not a new problem though).
![image](https://cloud.githubusercontent.com/assets/12466233/22178060/d3ecfaa4-dfe1-11e6-9d7e-46a93332c526.png)

The **generate method** refactoring on a short discard uses an underscore as the variable name, but when using a `var _` the variable will be called "var" and when using `int _` the variable will be called "v".
![image](https://cloud.githubusercontent.com/assets/12466233/22178076/3a2c5242-dfe2-11e6-951b-3897cfe328b0.png)

**Comment by CyrusNajmabadi** [comment]
Closing out.  I don't think there's remaining work we intend to do for discards.

**Comment by sharwell** [comment]
@CyrusNajmabadi I think it would make sense to create a new issue for the Generate Method portion of this issue.
