### ISSUE TITLE
clicking "About .NET Compiler Platform" in "Download the .NET Compiler Platform SDK" shows warning from github

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#1666]
this might or might not an issue. but I am opening just to make sure.

basically, if I click the link, first thing I see is this.

![image](https://cloud.githubusercontent.com/assets/1333179/6894829/4918c970-d68e-11e4-9dbf-850ed60302d5.png)

it might be a time to update IE version in VS or we open an external browser.

**Comment by srivatsn** [comment]
Please file a TFS bug on the shell team for this.

**Comment by sharwell** [comment]
I created an [Open in External Browser](https://visualstudiogallery.msdn.microsoft.com/46c0c49e-f825-454b-9f6a-48b216797eb5) extension, but it doesn't support Visual Studio 2015 right now. But it's [open source](https://github.com/tunnelvisionlabs/OpenInExternalBrowser) too.

**Comment by heejaechang** [comment]
@srivatsn is the template that has the link "About .Net ... " ours? if so, can we make the link < a href  ... > thing to open browser in external window?
