### ISSUE TITLE
creating new project with "Download the .NET Compiler Platform SDK" create a project that asking me to download vsix again

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#1667]
is this by design?

![image](https://cloud.githubusercontent.com/assets/1333179/6894879/d836c2ba-d68e-11e4-80a9-263e39542581.png)

not sure why it is creating a project just to let me know to download another vsix.

**Comment by jmarolf** [comment]
This is the design used by both the Azure SDK and Xamarin.  There is no way to uninstall the templates in the VSSDK and we cannot programatically install a template from the new project dialog.
