### ISSUE TITLE
FindAllReferences should provide containing member names

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#16675]
(feature request)

When finding all references, it would be useful if all the usage results also mentioned the name of the  outer scope that contains the result (like a qualified name of a namespace, type or member).

Scenario: I have a field defined class and want to see in which methods it is used. I FAR to the field and end up with pages of results, but I have to double-click on all of them to get the information about where the reference is.

**Comment by CyrusNajmabadi** [comment]
I think this is a good idea.  BUt one thing i don't like is that we have no way to just provide the fully qualified containing type, without also providing full types for things like parameters.  This makes the display names for symbols extremely large and unwieldy.

**Comment by miloush** [comment]
Perhaps just the member name would do, as you already have the file name?
Another option would be grouping. I guess you can always come up with super large name that will make the results suboptimal to present...

**Comment by CyrusNajmabadi** [comment]
This was done:

![image](https://user-images.githubusercontent.com/4564579/75650552-0d8d9680-5c0b-11ea-9c35-12cb06afa053.png)

I believe @mavasani did hte work, but i can't find the PR.
