### ISSUE TITLE
TrustFailure in downloading the nuget

### ISSUE THREAD

**Issue by FonixAgileSolutions** [dotnet/roslyn#16684]
**Version Used**: 
6
**Steps to Reproduce**:

1. In my Windows 10 machine, I run this command `nuget install Microsoft.Net.Compilers` to get the latest compiler 

**Expected Behavior**:
installing C# 6 compiler
 
**Actual Behavior**:

WARNING: Error: TrustFailure (The authentication or decryption has failed.)
WARNING: An error occurred while loading packages from 'https://www.nuget.org/api/v2/': Error: TrustFailure (The authentication or decryption has failed.)
Unable to find package 'Microsoft.Net.Compilers'.

![image](https://cloud.githubusercontent.com/assets/22116996/22193250/17f867fa-e14b-11e6-9e0a-5b17413f30bf.png)

**Comment by grzegorz-ogrodowski** [comment]
Have you found an solution for this issue?

**Comment by jasonmalinowski** [comment]
I've reached out to the NuGet team to help out here.

**Comment by emgarten** [comment]
@FonixAgileSolutions would try using the latest version of nuget.exe here: https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe

From the error message here it looks like this is coming from an older version of nuget.exe

**Comment by jasonmalinowski** [comment]
@FonixAgileSolutions Let me know if @emgarten's change didn't work for you.
