### ISSUE TITLE
Annotated C# Language Specification 

### ISSUE THREAD

**Issue by gordanr** [dotnet/roslyn#16687]
There are two excellent books about C#:
'C# Annotated Standard' by Jon Jagger, Nigel Perry, Peter Sestoft.
'The C# Programming Language' by Anders Hejlsberg, Mads Torgersen, Scott Wiltamuth, Peter Golde.

What makes these books outstanding is that some very smart people have contributed with annotations. Annotators have written historical notes, explanations, clarifications, funny comments, language design dilammas and other comments about some sentences and paragraphs in the main text of the book.

Many blog authors (e.g. Eric Lippert) comment selected topics (sentences) from C# Language Specification. Those blog entries, although very useful, are scattered all over the internet. It would be nice to have standardized way of annotating C# Language Specification. It is possible to make online system that offers annotating of selected text or linking selected text from specifiction with external resource. 
 
Consumers would simply click on the word in the online C# Language Specification and get all annotations related with clicked word/sentence/paragraph. 

Best way to get a good insight into what annotating system has to offer you can find here. (It takes less than 2 minutes).
https://hypothes.is/blog/elife-partners-with-hypothes-is-to-advance-open-scholarly-annotation/

The main problem could be the fact that specification changes in times.

cc @MadsTorgersen @jskeet

**Comment by CyrusNajmabadi** [comment]
@BillWagner is there something you'd like to do with this?
