### ISSUE TITLE
quickinfo LB got confused when there are multiple issues

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#1668]
I am not sure whether the issue is in LB engine or us. or it could be by design.

        public Exception Test()
        {
            return (int)1 + (int)2;
        }

this will show error squiggles under (int)1 + (int)2 also unnecessary tags for both "int".

if I hover over any one of them, it will show code fixes for both "int"

I can understand why this is happening (since quick info will ask LB for the error squiggle span and we will happily say there are two fixes for the span). not sure whether it is desirable or not. since it took me sometimes to figure out why this is happening.

user might not care since fix is valid though.

**Comment by heejaechang** [comment]
probably just not worth or nick picking.
(Exception)(Exception)new Exception(...)

shows 2 code fixes which has same end result. what actually got deleted is different, but end result is same. should we merge those two? (this will require getting fixes for all codefixes though. which break our lazy model)

**Comment by srivatsn** [comment]
Looks like this has been fixed and we can now see the fixes for both issues.
