### ISSUE TITLE
[Failing test] BasicEditAndContinue.xml

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#16689]
I've seen this fail a number of times

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_prtest/354/console

**Comment by ivanbasov** [comment]
Fixed by https://github.com/dotnet/roslyn-internal/pull/1838 and https://github.com/dotnet/roslyn/pull/19381
