### ISSUE TITLE
Fix All doesn't work for IDE0008 (Use explicit type instead of 'var')

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#16692]
**Version Used**: 
D15PreRel 26120.4

**Steps to Reproduce**:

1. Enable full solution analysis for C#
2. `git clone https://github.com/dotnet/roslyn-analyzers`
3. `msbuild BuildAndTest.proj /t:RestorePackages` - Verify restore succeeds.
4. `msbuild BuildAndTest.proj /m` - Verify build succeeds.
5. Open `src\Analyzers.sln`
6. Verify a bunch of IDE0008 diagnostics in error list. Click on any one.
7. Ctrl + Dot and verify "Use explicit type instead of 'var'" code fix is provided and works.
8. Ctrl + Z to undo the code fix and attempt to Fix All occurrences in any scope (Document/Project/Solution)

**Expected Behavior**:
Fix All works OR is not offered at all

**Actual Behavior**:

![image](https://cloud.githubusercontent.com/assets/10605811/22218352/3839380e-e15b-11e6-8635-9734764e08ea.png)

**Comment by mavasani** [comment]
I verified Fix All does work fine for other IDE suggestions (such as IDE0019) in the same solution.

**Comment by Pilchie** [comment]
Can you try this again?  I believe it may have been due to https://github.com/dotnet/roslyn/issues/16415.

**Comment by mavasani** [comment]
Yes, verified on latest d15rel build.
