### ISSUE TITLE
Undo doesn't work after suppressing a diagnostic in a newly created GlobalSuppression.cs

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#16691]
**Version Used**: 
D15PreRel 26120.4

**Steps to Reproduce**:

1. Create a C# class lib project
2. Type any code to generate an IDE analyzer suggestion. For e.g. IDE0008 (use explicit type instead of var)
3. Ctrl + Dot, and select suppress in suppression file.
4. Suppression gets added, new file GlobalSuppressions.cs is added to the project and diagnostic gets suppressed.
5. Ctrl + Z

**Expected Behavior**:
Step 4 gets reverted and diagnostic shows up again.

**Actual Behavior**:
No changes.

**Comment by Pilchie** [comment]
This seems like another place we need to have a custom undo around adding a file.
