### ISSUE TITLE
All IDE "Suggestion" diagnostics are shown as "Hidden" in the ruleset editor

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#16695]
**Version Used**: 
D15PreRel 26120.4

**Steps to Reproduce**:

1. Create new C# project
2. In solution explorer, right click on Analyzers node under `Project -> References -> Analyzers` and click "Open active ruleset"
3. Search "IDE000" in the ruleset editor

**Expected Behavior**:
Action for all IDE diagnostics is "Suggestion" or "Info".

**Actual Behavior**:
Action for all IDE diagnostics is "Hidden" and none of the available actions in the dropdown have "Suggestion". Seems like we didn't fix the CodeAnalysis Ruleset editor integration when adding the concept of "Suggestions".

![image](https://cloud.githubusercontent.com/assets/10605811/22219742/dc424e0e-e160-11e6-9178-56c656fa908d.png)

![image](https://cloud.githubusercontent.com/assets/10605811/22219760/ed442b78-e160-11e6-954a-1b61a095eaf2.png)

**Comment by Pilchie** [comment]
@kuhlenh Not sure what do do here?  This is something we should sort out as we think more about .editorconfig vs .ruleset.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is not an experience we are investing in.
