### ISSUE TITLE
Redundant check for namespace accessibility

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#167]
http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.Features/CodeFixes/FullyQualify/AbstractFullyQualifyCodeFixProvider.cs,164 checks whether a namespace is accessible.

But that always returns true; 
http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.Workspaces/Shared/Extensions/ISymbolExtensions_Accessibility.cs,116

(or is this just future-proofing?)

**Comment by srivatsn** [comment]
Sounds like oversight. Let's clean that up
