### ISSUE TITLE
[Test failure] CrossLanguage.xml

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#16704]
Been failing basically every time.

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/post-dev15/job/windows_vsi_p1_prtest/80/

**Comment by tmeschter** [comment]
Unfortunately it consistently passes on my local system. :-(

**Comment by Pilchie** [comment]
This has been ported to the new test harness, right?

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving out.

**Comment by CyrusNajmabadi** [comment]
This test doesn't exist anymore.
