### ISSUE TITLE
C# command line parser doesn't resolve relative paths for references/source files, given a valid base directory

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#16705]
**Version Used**: 
D15PreRel 26120.4

**Steps to Reproduce**:

1. Create a C# DotNet core application
2. Add the following itemgroup to the project file:
```
<ItemGroup>
  <COMReference Include="Accessibility">
      <Guid>{1EA4DBF0-3C3B-11CF-810C-00AA00389B71}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>1</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
</ItemGroup>
```

**Expected Behavior**:
Intellisense from the new COM reference in the project (e.g. Accessiblitiy namespace should be shown).

**Actual Behavior**:
No intellisense because the added link reference has relative path and command line parser doesn't resolve a relative reference path to an absolute path based on the given base directory.

**Comment by jaredpar** [comment]
This bug mentions the command line compiler but provides an MSBulid entry as a repro.  Can you provide a command line repo?

**Comment by jcouv** [comment]
@mavasani Do you still have a repro?

**Comment by mavasani** [comment]
@davkean @srivatsn - can you provide a repro here?

**Comment by mavasani** [comment]
I recall we added a workaround in the project system due to this bug.

**Comment by davkean** [comment]
This isn't referring to Csc, this is referring to the CommandLineParser type. We should separate source files from references. As I found out later, [References are treated and resolved completely](https://github.com/dotnet/project-system/issues/1872) different - the command-line parse itself doesn't resolve them during a parse..

The bug I recall was when you had a compile item that had a path outside of the base directory that we passed to the command-line parser, this is what fixed it: https://github.com/dotnet/project-system/pull/1032.

```
Base Directory: C:\Foo\Bar
Source File: ..\Foo\Baz\Compile.cs
```

Let me fire up a repro.

**Comment by davkean** [comment]
Once I've fired up a repro I can clearly see that this isn't a bug in the parser:

``` C# 
            var results = CSharpCommandLineParser.Default.Parse(new string[] { @"..\Foo\Source.cs" }, @"C:\Projects\Bar", null, null);

            Console.WriteLine(results.SourceFiles.First().Path);
```

Outputs:

```
           C:\Projects\Bar\..\Foo\Source.cs
```

The parser doesn't normalize (which is a reasonable behavior) - which was tripping up our logic that was expecting a normalized path.

We can close this one out.
