### ISSUE TITLE
Need to create a MSBuild layout NuGet for CLI

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#16717]
Today the CLI deploys Roslyn as an MSBulid component by patching together a number of our components.  This is a fragile solution because it means there needs to be a high degree of communication between ourselves an CLI when we make changes to this layout.  Such changes are not uncommon during a release and elements like the compiler server depend on them existing. 

Need to take an approach similar to how we deploy to MSBulid here.  Have a NuGet package which contains the layout we expect and CLI can consume this by simply laying down the package contents into the appropriate directory.

**Comment by jaredpar** [comment]
FYI @piotrpMSFT

**Comment by agocke** [comment]
Some notes on this issue: I've created the `Microsoft.NETCore.Compilers` package to serve as the forward-looking shared-framework-compatible compiler package. I'd like to use this package both as the installation package for official CLI builds and also as a third-party installable package that can upgrade the "in-box" compilers.

This package is currently being published on MyGet but I won't regard this issue as completed until the official .NET CLI build is using this package for build and layout.

**Comment by jcouv** [comment]
Is there still work to do for this?

**Comment by jcouv** [comment]
@khyperia @agocke Is there still work to do for this?

**Comment by jaredpar** [comment]
This work is done. We can close.
