### ISSUE TITLE
Figure out why the Rename Tracking unit tests for named tuples were passing

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#16712]
Prior to https://github.com/dotnet/roslyn/pull/16711, there were unit tests that appeared to assert that renaming named elements of tuples via Rename Tracking would work correctly, but trying those exact tests out in the IDE caused crashes. There's a disconnect between what the tests claim to be doing and what happens in the IDE, and we need to figure out that gap.

**Comment by CyrusNajmabadi** [comment]
Unlikely to do anything here.
