### ISSUE TITLE
[Proposal]Allow event forwarding

### ISSUE THREAD

**Issue by KalitaAlexey** [dotnet/roslyn#1671]
For code

```
public class MyClass
{
    public event EventHandler EventOccurred {
        add {
            AnotherClassInstance.EventOccurred += value;
        }
        remove {
            AnotherClassInstance.EventOccurred -= value;
        }
    }

    public event EventHandler<SomeEventArgs> EventOccurred2 {
        add {
            AnotherClassInstance.EventOccurred2 += value;
        }
        remove {
            AnotherClassInstance.EventOccurred2 -= value;
        }
    }

    public AnotherClass AnotherClassInstance { get; }
}
```

I'd like to write something like

```
public class MyClass
{
    public event EventHandler EventOccurred => AnotherClassInstance.EventOccurred;

    public event EventHandler<SomeEventArgs> EventOccurred2 => AnotherClassInstance.EventOccurred2;

    public AnotherClass AnotherClassInstance { get; }
}
```

Or If this approach is wrong, then explain me why?

**Comment by HaloFour** [comment]
Doesn't sound a common problem at all, and you have a functioning solution even if it is a little verbose.

**Comment by KalitaAlexey** [comment]
@HaloFour Yes C# goes on way of cutting extra verbosity.

**Comment by vladd** [comment]
My feeling is that the language core is not a proper place for such a feature (the scenario seems to be pretty rare), but a good case for a decent metaprogramming facility (which is not currently discussed by the dev team, but definitely needs to be introduced into the language).

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
