### ISSUE TITLE
All VSI queues failing with CreatePkgDef error in VisualStudioSetup.Dependencies.csproj

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#16728]
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_open_prtest/54/
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_open_prtest/58/
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/56/
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_open_prtest/65/

```
CreatePkgDef : error : ArgumentException: No Visual Studio registration attribute found in this assembly. [D:\j\workspace\windows_vsi_p---2168b4b2\Open\src\VisualStudio\Setup.Dependencies\VisualStudioSetup.Dependencies.csproj]
```

**Comment by dpoeschl** [comment]
FYI @JohnHamby (/cc: @jasonmalinowski @tmeschter)

**Comment by JohnHamby** [comment]
I have no idea what might cause this.

**Comment by dpoeschl** [comment]
Fixed.

**Comment by haypxx** [comment]
don't just say fixed tell us how!!
