### ISSUE TITLE
Reflection - Lexical Ordering

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#16733]
Hi,

There's no official way to reflect on a type and get (say) public properties in their lexical (declared) order. Many articles and utilities rely on ordering by MetadataToken and although this seems to work, is sometimes regarded as risky and potentially breaking in a future release.

However lexical ordering is extremely useful and quite natural for many applications so providing a way to do this that has official support would be superb.

(For example we have Dapper utility code that formats SQL queries with `{0}` and `{1}` etc where parameters are expected and then use reflection to replace these with `@<some_property_name>` ensuring the SQL text always contains a parameter name that **exactly** matches the anonymous object's property name, 0 being the first property, 1 the second etc.).

I guess you could either flatly commit to honoring the MetadataToken and say that this will always be the same as the lexical order or perhaps introduce a new property on the Type class LexicalPosition where 0 indicates the first declared property, 1 the second and so on.

If this integer was assigned increasingly based on lexical order of members (whether they be fields, properties, public private etc) then this would work - getting all public properties ordered by LexicalPosition would always order correctly.

I'm posting this here because it is the compiler that will know this lexical order as it processes the token stream.

One could argue that writing code which depends on lexical order is risky but it would be no more risky than writing code that depends on a the spelling of a property.

Thanks.

**Comment by HaloFour** [comment]
I'd certainly argue that depending on lexical order is more risky and fragile as the entire class structure can be refactored but as long as the accessible names and signatures remain unchanged the consuming code will compile just fine.

To my understanding there is no real facility in the CLR or the reflection API to obtain a deterministic order of members, nor is there a component to the CLI spec which dictates this meaning that you can expect very different experiences under different runtimes.  I'd imagine that for a proposal to get off of the ground that it would have to start there.

**Comment by dsaf** [comment]
1. Isn't this beyond just C# and thus a CLR question?

2. You could probably harness https://github.com/dotnet/roslyn/blob/master/docs/features/generators.md somehow. Annotate properties with OrderAttribute automatically?

**Comment by Korporal** [comment]
I opened a new issue here:
https://github.com/dotnet/core/issues/469

**Comment by Korporal** [comment]
So current suggestion is to take steps to ensure that ordering by MetadataToken becomes guaranteed to equate to lexical (declaration) order. Many believe this to be true today and so if it is in fact true, take steps to ensure it remains true going forward.

This may be a simpler change than adding support for ordering,

**Comment by Korporal** [comment]
Can anyone tell me - which repo should I discuss this in, its been closed in two places:
https://github.com/dotnet/core/issues/469

Is this Roslyn repo - the ideal and best place??

**Comment by tmat** [comment]
Roslyn repo is fine.

**Comment by gafter** [comment]
I believe metadata tokens are not fully in lexical order of members. I believe it is in lexical order if you are only considering fields, or only considering methods, but I do not think there is a way to get the lexical order from metadata.
