### ISSUE TITLE
Switch Roslyn to BasicUndo that targets Dev15 VS SDK

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#16737]
Update BasicUndo.dll to Dev15 VS SDK, publish nupkg and switch Roslyn to the updated package. 
Clean up binding redirects in ```build\Defaults\Desktop\App.config```.

**Comment by Pilchie** [comment]
@jaredpar Is this still needed?

**Comment by Pilchie** [comment]
Moving back to infrastructure, since this is test infrastructure.

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving out.
