### ISSUE TITLE
windows_vsi_p3_prtest timing out

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#16741]
Following error is given in the dump taken when execution times out
```
Tag count mismatch: 
Expected: 1
Actual: 0
Current editor text:
class C
{
}
```

**Comment by jmarolf** [comment]
found in https://github.com/dotnet/roslyn-internal/pull/1527

**Comment by tmeschter** [comment]
What have I done to deserve all the integration test failures?

**Comment by Pilchie** [comment]
You *currently* have the most context, but we should farm them out to multiple people for separate root causes.

**Comment by tmeschter** [comment]
We no longer have logs. I see no further failures of this sort. Closing this as "Not Repro".
