### ISSUE TITLE
SemanticModel.GetDeclaredSymbol(ParameterSyntax) doesn't work for parameters of a Local Function

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#16757]
This is going to affect IDE experience. I noticed that IDE doesn't show tooltips on the parameters and "Find All References" finds nothing when invoked on the parameters. This issue is the likely reason for the behavior.

**Comment by AlekseyTs** [comment]
CC @agocke, @jaredpar

**Comment by agocke** [comment]
Dup of https://github.com/dotnet/roslyn/issues/16209

**Comment by bkoelman** [comment]
Should VS2017-RC4 contain this fix? I'm asking because #16209 still fails there.

**Comment by AlekseyTs** [comment]
@bkoelman 

> Should VS2017-RC4 contain this fix? I'm asking because #16209 still fails there.

No. Unfortunately, the fix didn't make it into VS2017.
