### ISSUE TITLE
Generic type inference for value tuples seems ... odd

### ISSUE THREAD

**Issue by DavidArno** [dotnet/roslyn#16756]
**Version Used**: 
VS 2017 RC (15.0.26020.0)
C# 2017 RC (00369-50000-00000-AA898)

**Steps to Reproduce**:

Compile the following code:
```csharp
using System;

namespace TupleGenericsTests
{
    public static class Extensions
    {
        public static TR F1<T1, TR>(this T1 value, Func<T1, TR> func) => func(value);
        public static TR F2<T1, T2, TR>(this (T1, T2) value, Func<T1, T2, TR> func) => 
            func(value.Item1, value.Item2);
    }

    public class Tests
    {
        public int TimesTwo(int value) => value * 2;
        public int AddTwoInts(int value1, int value2) => value1 + value2;
        public float AddIntAndFloat(int value1, float value2) => value1 + value2;

        public int TestF1() => 1.F1(TimesTwo);

        public int TestF2WithTwoInts() => (1, 1).F2(AddTwoInts);

        public int TestF2WithIntAndFloat() => (1, 1.0).F2(AddIntAndFloat);
    }
}
```

**Expected Behaviour**:
All compiles fine.

**Actual Behaviour**:
`TestF1` - compiles fine.
`TestF2WithTwoInts` - compiles fine.
`TestF2WithIntAndFloat` - fails to compile, with the error:
`The type arguments for method 'Extensions.F2<T1, T2, TR>((T1, T2), Func<T1, T2, TR>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.`

It seems odd that if `T1`, `T2` and `TR` are all the same type, then their types can be inferred; but if they differ, then they can't be inferred.

**Comment by jcouv** [comment]
FYI @VSadov I'll stop by to discuss.

**Comment by VSadov** [comment]
`1.0` is a `double` literal. Should work with `1.0f`

**Comment by jcouv** [comment]
Vlad figured out the puzzle. The 1.0 literal is a double (not a float).

Here's an updated example without cruft (not tuples and no extension methods) to demonstrate:

```C#
using System;
public class Tests
{
    public static TR F2<T1, T2, TR>(T1 v1, T2 v2, Func<T1, T2, TR> func) => func(v1, v2);

    public float AddIntAndFloat(int value1, float value2) => value1 + value2;
        
    public int TestF2WithIntAndDouble() => F2(1, 1.0, AddIntAndFloat); // cannot infer types
    public float TestF2WithIntAndFloat() => F2(1, 1.0f, AddIntAndFloat); // ok
}
```

**Comment by DavidArno** [comment]
Ha, @VSadov deserves that wizard hat he wears! Apologies for wasting your time over a simple typo like that 😊
