### ISSUE TITLE
Create MetadataReference throws an exception on Xamarin project

### ISSUE THREAD

**Issue by jotab123** [dotnet/roslyn#16768]
Version:
Visual Studio 2015
Tested with Microsoft.Codeanalysis 1.3.1.0 and 2.0.0.0

Code:
`var metadataReference = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);`

Exception:

> System.IO.FileNotFoundException: Could not find file "/mscorlib.dll".

**Comment by tmat** [comment]
What's the value of ```typeof(object).Assembly.Location```?

**Comment by jotab123** [comment]
The value of `typeof(object).Assembly.Location` is `"mscorlib.dll"`. If I check another object like `ContentPage` it returns the correct path:

`typeof(ContentPage).Assembly.Location` returns `"/storage/emulated/0/Android/data/com.excompany.project1/files/.__override__/Xamarin.Forms.Core.dll"`

**Comment by tmat** [comment]
I assume you run on Mono -- if that's the case it looks like a bug in Mono. The location should be a full path.

**Comment by jotab123** [comment]
Ok, I'm gonna report it. 

Thanks!
