### ISSUE TITLE
Override completion issue when committing with parenthesis

### ISSUE THREAD

**Issue by jbevain** [dotnet/roslyn#16770]
**Version Used**:  2.0.0.61313

No difference if Automatic Brace Completion is on or off.

**Steps to Reproduce**:

1. Declare a class Foo
2. Input:

```csharp
override ToString()
```

**Actual Behavior**:

Inserted text:

```csharp
public override string ToString()
{
    return base.ToString();)
}
```

1. Typing the opening parenthesis commits the completion.
2. Typing the closing parenthesis adds it where the caret is moved inside the committed completion.

**Expected Behavior**:

That is very much debatable, but I don't think the opening parenthesis should commit this completion.

**Side note**:

We have the exact same issue in the VS Tools for Unity where we're providing completion for Unity specific methods. It's aggravated by the fact that they are normal (not overriden) methods, and a lot of our users are typing them through muscle memory, so they would type:

```csharp
void FixedUpdate()
```

and end up with:

```csharp
public void FixedUpdate()
{
    )
}
```

If you do not think that override completion needs fixing, we would still welcome a discussion on how to control what triggers the completion to be committed through the completion API.

**Comment by CyrusNajmabadi** [comment]
Closing out given lack of feedback.
