### ISSUE TITLE
Declared variables confused with tuple arguments in VS tooltips

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#16778]
```vb.net
Module Module1
    Sub Main()
        Dim a = 0
        Dim tuple = (a:=0, b:=0)
    End Sub
End Module
```

Hovering over `b` (the tuple argument) produces nothing, but hovering over 'a' (the other tuple argument) produces a tooltip about `a` (the declared variable).

![image](https://cloud.githubusercontent.com/assets/15987992/22351743/347d3bbe-e3ce-11e6-9a8d-dab487cdd3e5.png)

**Comment by jcouv** [comment]
If I understood correctly, this is the VB counterpart to this C# change https://github.com/dotnet/roslyn/pull/16659

**Comment by jcouv** [comment]
The VB work on semantic model of named tuple elements is tracked by https://github.com/dotnet/roslyn/issues/16697
I'll close OP as duplicate.
