### ISSUE TITLE
[?] Extension Methods Use?

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#1678]
Is there any guidance as to if extension methods can be used within the Roslyn code-base?

**Comment by theoy** [comment]
I doubt people would object to extension method use themselves as much as potentially some of the other side effects if the extension methods were generalized/less performant and hence potentially inappropriate for hotpaths.

/cc @gafter, @pilchie, @JohnHamby @ManishJayaswal @srivatsn @pharring @jaredpar

**Comment by Pilchie** [comment]
Right - it's generally fine to use extension methods in the implementation of Roslyn.  We did have some principles about where they should (and shouldn't) appear as part of the public API though.

cc @AnthonyDGreen

**Comment by AdamSpeight2008** [comment]
Would their usage be ok? Say if a PR from [branch: Try Peek](https://github.com/AdamSpeight2008/roslyn-AdamSpeight2008/tree/TryPeek_4) was submitted?

**Comment by gafter** [comment]
@AdamSpeight2008 I cannot see the diffs on that branch without a PR being submitted. Rather than submitting a hypothetical question about whether a PR would be accepted, why don't you try submitting the PR and initiate the discussion there?

**Comment by gafter** [comment]
Generally speaking we use extension methods when the use feels like a natural extension of the API and where there are likely to be other clients elsewhere. If there is only one client or used only within one source file, we generally don't use extension methods.
