### ISSUE TITLE
Retrieving Symbol from DocumentationCommentId

### ISSUE THREAD

**Issue by Andrew-Hanlon** [dotnet/roslyn#16786]
I am currently using roslyn to parse xml doc comments.

The `ISymbol.GetDocumentationCommentId()` method works great to get an id that identifies an xml doc comment member. However, when parsing the xml doc comments themselves, it does not appear possible to (cleanly) get back to the Symbol from the id.

For example, I use `Symbol.GetDocumentationCommentXml()` to extract the following doc xml:

```xml
<summary>
  Lorum ipsum <see cref="M:Namespace.Type`1.Method``1(System.String,``0)">...
</summary>
```
From here I can easily use a visitor to parse the xml and extract the id, but there is no way to cleanly retrieve its corresponding `IMethodSymbol`.

Currently, I am using a separate visitor to find the Symbol by crudely parsing the cref and walking the dot-delineated tokens, then comparing the full cref id to the results of another `GetDocumentationCommentId()` call. I am caching the results, but it is still a lot of overhead considering you have to include references in the lookup.

A big improvement would be if roslyn could cache the results from `GetDocumentationCommentId` calls and expose a reverse-lookup. Since this method is called internally from the `DocumentationCommentCompiler`, the cache would be filled automatically as you query the documentation xml.

I also thought about overloading the `GetDocumentationCommentXml` method itself to include an out parameter that returns an individual lookup for any Ids that were bound -- but this approach appears to have a much larger surface area given the number of individual overloads and the call depth for this method.

If the cache idea is acceptable, I would be happy to work on an initial pull request after some discussion.

Is this something that would be desirable to the community? And what would be your thoughts on implementation? Is there something I am missing that makes this unnecessary?

Thanks!

**Comment by daveaglick** [comment]
Have you seen the [DocumentationCommentId](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/DocumentationCommentId.cs) class? Specifically, `DocumentationCommentId.GetFirstSymbolForDeclarationId(...)` may be what you're looking for.

**Comment by Andrew-Hanlon** [comment]
Thank you kindly @daveaglick - I obviously didn't look hard enough!

**Comment by daveaglick** [comment]
No problem, happy to help :smile:
