### ISSUE TITLE
CSharpLineSeparators is failing in master

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#16791]
**History**: https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3/

**Comment by Pilchie** [comment]
What was the failure here?  A missing tag?

**Comment by Pilchie** [comment]
Could be https://github.com/dotnet/roslyn/issues/10916?

**Comment by dpoeschl** [comment]
These tests are going away and will be replaced with tests against the new framework. It's not worth doing a separate investigation into the old behavior.
