### ISSUE TITLE
Flaky EnC & CodeGen tests

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#16790]
**Examples**
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/dev15-rc3/job/windows_release_unit32/15/#showFailuresLink
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/dev15-rc3/job/windows_release_unit32/16/#showFailuresLink

**History**
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/dev15-rc3/job/windows_release_unit32/

**Comment by dpoeschl** [comment]
@jasonmalinowski Do we need to investigate these failures in `dev15-rc3`? They aren't failing in `master`.

**Comment by jasonmalinowski** [comment]
That branch is now shipped, so no changes will be taken. :smile:

**Comment by dpoeschl** [comment]
This has failed twice in a row now in the windows_debug_unit64 queue:

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_debug_unit64/326/
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_debug_unit64/327/

**Comment by dpoeschl** [comment]
Okay, four times in a row. https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_debug_unit64/

@jaredpar @tmat Can someone look into these very soon?

**Comment by dpoeschl** [comment]
@jaredpar informs me that the repeated failures might be due to caching. Still, we should get this looked at.

**Comment by dpoeschl** [comment]
It's green now. But it does keep cropping up.

**Comment by dpoeschl** [comment]
Cropped up again for real this time. https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_release_unit32/331/#showFailuresLink
