### ISSUE TITLE
Control falls through switch statement case labels

### ISSUE THREAD

**Issue by tenor** [dotnet/roslyn#168]
This issue was previously reported in the [old Roslyn forums.](https://social.msdn.microsoft.com/Forums/en-US/51d3278b-d7b6-4ec6-8c94-371603e06a92/falling-through-switch-case-labels?forum=roslyn)

```C#
var i = 0;

switch (i)
{
    case 0:
        Console.WriteLine('0');
    case 1:
        Console.WriteLine('1');
    case 2:
        break;
}
```

The code above will compile in both scripting and interactive mode.

In interactive mode, the code will compile even if the break statement is omitted.

*Edited Code for clarity*

**Comment by redknightlois** [comment]
Fall through switch is insanely useful for high performance code.

**Comment by sharwell** [comment]
@redknightlois You can still fall through in C#, you just have to do it explicitly. The syntax looks like this:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/80f056045605ef6f8e6b17c96c8267997d025f12/StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1000CodeFixProvider.cs#L85

**Comment by redknightlois** [comment]
Nice, didn't know that. 
Would that issue a jump statement if the behavior would be fall through? Or better would the JIT find out and do not emit the jump it at all?

**Comment by sharwell** [comment]
@redknightlois If I'm not mistaken, the C# compiler will remove unnecessary branch instructions between cases when optimization is enabled (but not when optimization is disabled because it would negatively impact the debugging experience).
