### ISSUE TITLE
Extend Syntax Tree Visualizer to work on SyntaxNodes while debugging

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#1680]
Right now when debugging rewritten syntax trees I had been using `.ToFullString()` to see if my rewriter had worked correctly. 

I recently ran into an issue where I was creating an invalid syntax tree, but `.ToFullString()` printed it such that it appeared valid. (I was creating an `InvocationExpression` with the `Identifier` "Namespace.Type.MethodName" instead of a chain of `SimpleMemberAccessExpressions` with the identifiers "Namespace", "Type" and "MethodName").

Ultimately the only arbiter of truth when it comes to syntax trees is the Syntax Visualizer. When debugging it would be very useful to analyze the nodes I'm interested in so I can determine correctness.

@KirillOsenkov mentioned that there may have been a debugger visualizer at some point and mentioned I should ask @shyamnamboodiripad about this.

**Comment by shyamnamboodiripad** [comment]
There used to be a debugger visualizer in early versions of Roslyn CTP when Syntax trees and nodes were serializable. Since debugger visualizers require to run in a separate app domain, we would need the nodes to be serializable to make this work correctly.

**Comment by JoshVarty** [comment]
Do you remember why serialization of nodes was removed? I recall seeing an explanation on StackOverflow (Perhaps by @Pilchie) but I can't seem to find it.

I suspect there's a good reason for the removal and it's unlikely things have changed. If that's the case, I'll go ahead and close this issue.

**Comment by Pilchie** [comment]
The main reason was to make the core APIs part of the portable profile, which doesn't support Serialization.

**Comment by JoshVarty** [comment]
Makes sense, I doubt that's going to change so I'll close this.

**Comment by svick** [comment]
Would it be possible to use some other serialization that is supported in PCL (say, JSON.NET) for this, instead of binary serialization?
