### ISSUE TITLE
Unit tests are using the 'foreground thread' state between tests

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#16811]
While working on the VisualStudioWorkspace thread affinity fix, I "discovered" that we have some shared components, notably the ForegroundNotificationService, that use the STA thread in the tests between tests. This is terrifying. Our WpfFact clears the foreground thread between tests, which meant that when feature asked for the foreground thread it got the "fallback foreground thread" which was really some random thread pool thread and everything broke from there. This was very difficult to debug.

We should try to clean this up. I can think of a few tasks that are small (I hope) and would have made this easier to debug:

- [ ] Investigate why we have the 'fallback foreground thread' behavior and delete it if possible
- [ ] If the above cannot be deleted, update the foreground thread class in unit tests to fail (hard) if somebody asks for it
- [ ] Fail tests if somebody tries to schedule work to the STA scheduler when a WpfFact isn't running

And possibly more, of course.

**Comment by jasonmalinowski** [comment]
I think @sharwell either fixed this, or changed enough of this that this bug isn't useful anymore.

**Comment by sharwell** [comment]
I missed the date when reading this notification. You scared me good. :laughing:
