### ISSUE TITLE
Inline Temporary Variable adds duplicate cast

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#16819]
**Version Used**: 15.0.0-RC.3+26127.0

```C#
var o = (Exception)null;
Console.Write(o == new Exception());
```

The Inline Temporary Variable refactoring produces

```C#
Console.Write((Exception)(Exception)null == new Exception());
```

**Comment by Pilchie** [comment]
Interesting - the expansion code should probably not add a cast if there already was one.

**Comment by reaction1989** [comment]
The implementation can be found here [InlineTemporaryCodeRefactoringProvider.cs](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.cs)
