### ISSUE TITLE
Add feature to disable or grey-out obsolete/deprecated C# methods, attributes, etc on autocomplete

### ISSUE THREAD

**Issue by CanisLupus** [dotnet/roslyn#16817]
[@DustinCampbell recommended, a few weeks ago, that I post the request here also. Originally in [https://github.com/OmniSharp/omnisharp-vscode/issues/1109](https://github.com/OmniSharp/omnisharp-vscode/issues/1109)]

I couldn't find a setting for this, nor find results about it on Google. It would be really helpful to avoid auto-completing obsolete stuff when using an API that has legacy methods and attributes. In VSCode, greying out things marked Obsolete (and showing them last in the autocomplete list) - or maybe even being able to disable them - would be great.

Thanks,
Daniel

**Comment by Pilchie** [comment]
I thought we used to do this in the native language service...

**Comment by DustinCampbell** [comment]
Not that I'm aware of. We did it in VB for IntelliSense in Zone, but never did anything for C#.

**Comment by sharwell** [comment]
Consolidating multiple requests in this area to design issue #26488
