### ISSUE TITLE
MetadataAsSource uses Visual Basic code instead of C# code

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#16818]
**Version Used**:  VS2017RC 15.0.26127.0

**Steps to Reproduce**:

- Create a C# Console App (.NET Framework 4.6)
- Add a VB Class Library (.NET Framework 4.6)
- Add a reference to the VB library from the C# Console App
- Restart VS
- Click on eg. 'string' in the C# code and press F12

**Expected Behavior**:

C# code is shown since current project is a C# project.

**Actual Behavior**:

Visual Basic code is shown

I couldn't repro this with VS2015.3.

**Comment by jasonmalinowski** [comment]
Stealing this one since I hit it myself and was too curious to see what was going on.
