### ISSUE TITLE
Convert to Interpolated String inserts an extra space in the string from newlines

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#16820]
**Version Used**: 15.0.0-RC.3+26127.0

```C#
var s = "A" + 1 + "B"
      + "C";

```

The Convert to Interpolated String refactoring produces

```C#
var s = $"A{1}B C";
```

The space between `B` and `C` should not be there.
This a subtle and easily-overlooked change in runtime behavior; this is quite bad.

**Comment by jmarolf** [comment]
Inital investigation points to the formatter.  When we format for elastic trivia [here](http://index/?query=CleanupDocumentAsync&rightProject=Microsoft.CodeAnalysis.Workspaces&file=CodeActions%5CCodeAction.cs&line=275) we add the spaces
