### ISSUE TITLE
Type argument inference with unambiguous method group

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#16824]
Apologies if this is a dupe; I don't see another issue like this.

Please allow the following. I see no possible ambiguity in this scenario. The`IsEven` and `Test` method groups have only one overload which fits the delegate signature.

```c#
class Program
{
    public static void Main()
    {
        Test(IsEven);
    }

    public static bool IsEven(int x) => x % 2 == 0;

    public static void Test<T>(Func<T, bool> predicate)
    {
    }
}
```

**Expected Behavior**:
Infers `Test<int>(IsEven)` and compiles

**Actual Behavior**:
CS0411 The type arguments for method 'Program.Test<T>(Func<T, bool>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

**Comment by jaredpar** [comment]
Believe this is by design but will let @gafter comment on exactly how.

**Comment by gafter** [comment]
Type inference [doesn't infer based on an argument that is a method group](https://github.com/ljw1004/csharpspec/blob/gh-pages/expressions.md#the-first-phase), no matter how many or few members the method group has. The conversion from a method group to a delegate (of some particular type) occurs *after* type inference has completed to determine what that delegate type is.

Having said that, I imagine it might be possible to modify (the specification for) type inference to get the behavior @jnm2 would like. Who would like to take a crack at it?

**Comment by jnm2** [comment]
@gafter Should I move this to csharplang?

**Comment by gafter** [comment]
@jnm2 Sure, if you'd like to discuss it further. But without a suggestion as to *how* it would work, I don't see how it can move past the discussion phase. Perhaps that discussion will trigger an idea in someone's head?

**Comment by jnm2** [comment]
Issue moved to [dotnet/csharplang #129](https://github.com/dotnet/csharplang/issues/129) via [**ZenHub**](https://www.zenhub.com/)
