### ISSUE TITLE
References from .NET framework project to .NET standard library project are not found

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#16827]
Ported from https://github.com/dotnet/roslyn-project-system/issues/1323

**Version Used**: 
d15prerel 26130

**Steps to Reproduce**:

*Repro 1:*
1. Open the attached [ClassLibrary4.zip](https://github.com/dotnet/roslyn/files/740038/ClassLibrary4.zip) solution and see references for Class1 or Class1.M or Class1.M2 via CodeLens indicators or Find All References.

*Repro 2:*
1. Create a framework console app (FrameworkConsoleApp3_2:   4.6.1);
2. Add a new standard class library project (StandardCL3_2: [netstandard1.4]), write the method to the class;
3. Add the reference from FrameworkConsoleApp3_2 to StandardCL3_2 successfully;
4. Call the class library method from FrameworkConsoleApp3_2 and save the program.cs;
5. Build the solution succeeded;
6. See references for Class1 or Class1.M or Class1.M2 via CodeLens indicators or Find All References.

**Expected Behavior**:
Non-zero references.

**Actual Behavior**:
Zero references.

**Comment by Pilchie** [comment]
Does this still repro?  Is this the facade problem again?

**Comment by jasonmalinowski** [comment]
@Pilchie possibly.

**Comment by MattGertz** [comment]
Mondo escrow triage: keeping this for now.

**Comment by dpoeschl** [comment]
It appears to work for me. @mavasani Can you reopen if this still repros for you?

![image](https://user-images.githubusercontent.com/235241/30884227-a8f75c0e-a2c3-11e7-9f17-76a4376aeef1.png)
