### ISSUE TITLE
2 helper types that do similar thing

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#16836]
looks like there are 2 helper types that does similar thing

http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/InternalUtilities/FileUtilities.cs,65051d4343632c16

http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Shared/Utilities/IOUtilities.cs,10

2 probably need to be merged to one.

**Comment by CyrusNajmabadi** [comment]
These types seem to serve different purposes.  FileUtilities seems to do operations, while wrapping nearly all exceptions as IOExceptions.  IOUtilities allows you to perform operations while swallowing known exceptions that can occur when doing IO operations.
