### ISSUE TITLE
ExceptionDispatchInfo and CA1031 warning

### ISSUE THREAD

**Issue by saxenark** [dotnet/roslyn#16848]
VS2015

Compile the code snippet below (partial code)

            catch (Exception e)
            {
               // some processing
                exceptionDispatchInfo = ExceptionDispatchInfo.Capture(e);
            }

            // some more processing
            exceptionDispatchInfo?.Throw();

This code compiles but Code Analysis throws up CA1031
Warning	CA1031	Modify 'FeatureController.Initialize()' to catch a more specific exception than 'Exception' or rethrow the exception.

This warning should probably be suppressed by the analyzer if possible.

**Comment by jaredpar** [comment]
@srivatsn where are we tracking FxCop issues?

**Comment by srivatsn** [comment]
In VSO. However, we are rarely fixing anything in FxCop and will instead spend our energies on making sure that the roslyn re-implementation of these rules address these issues. So please file this in https://github.com/dotnet/roslyn-analyzers/issues
