### ISSUE TITLE
Feature Request: Quick action to generate struct/class from tuple declarations / parameter lists

### ISSUE THREAD

**Issue by YaakovDavis** [dotnet/roslyn#16851]
When selecting the following:

```(int x, int y, int z)```

and pressing Ctrl + ., it would be nice to be offered to generate the following struct/class:

```
struct <Name>
{
  public int X;
  public int Y;
  public int Z;
}
```
\<Name> is a place holder of course.
When the tuple elements aren't named, place holders should appear for the field names as well.

Edit: would be nice to have the above implemented for an arbitrary selection of consecutive parameters in a method signature as well.

**Comment by CyrusNajmabadi** [comment]
This was added with https://github.com/dotnet/roslyn/pull/28257

![image](https://user-images.githubusercontent.com/4564579/75650474-c901fb00-5c0a-11ea-9d54-bf444e6ec43d.png)
