### ISSUE TITLE
Completion doesn't re-use last chosen member if two or more characters is typed

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#16854]
**Version Used**: VS2017RC 15.0.26127.0

**Steps to Reproduce**:

1. Console.writel();
2. Console.wr();

**Expected Behavior**:

WriteLine gets picked

**Actual Behavior**:

Write gets picked

This worked in VS2015.3.

It works if you only type w (one letter)

**Comment by CyrusNajmabadi** [comment]
Does not repro for me:

![image](https://user-images.githubusercontent.com/4564579/217336643-c1fa4c38-629a-450b-9a32-087bd2b8afed.png)
