### ISSUE TITLE
Does the nameof operator work outside the method scope

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/roslyn#1685]
Hi,

The `nameof`, is indeed a pretty neat feature that will eliminate those nasty hard-coded param names.

But will it work at the namespace scope level? Because in all tutorials I've bben looking at, it didn't involve working with attributes or other non-method-scope `nameof` calls.

Here's an example usage:

    [CustomValidation(typeof(Person), nameof(Person.Validate)]
    public class Person
    {
         public static ValidationResult Validate(/***/)
         {
             /***/
         }
    }

**Comment by HaloFour** [comment]
`nameof()` produces a `string` constant so it is permitted in attributes.  I don't know all of the accessibility rules off-hand but your example above works just fine.

**Comment by weitzhandler** [comment]
Great, awesome!
C# rawwkz!

**Comment by theoy** [comment]
> Great, awesome!
> C# rawwkz!
-- @weitzhandler 

:+1::100:

I :heart::heart::heart: C# as well :grinning:

**Comment by weitzhandler** [comment]
Does the `nameof` operator also work on instance fields, for example:

    [Display(ResourceType = typeof(Resx), Name = nameof(IsEmpty))]
    public bool IsEmpty

**Comment by JoshVarty** [comment]
Yes it does. Just tested in VS2015 CTP6: 

![image](https://cloud.githubusercontent.com/assets/1249087/7289810/2ffbd79e-e943-11e4-97a5-e735d2dd09c6.png)

**Comment by weitzhandler** [comment]
Thanks!
That's awwwwesome finally.
I hate hardcoding!
