### ISSUE TITLE
Where do vssdk targets files get installed with VS2017 RC?

### ISSUE THREAD

**Issue by bbarry** [dotnet/roslyn#16863]
**Version Used**: 

Visual Studio Community 2017 RC (15.0.26127.0)

**Steps to Reproduce**:

1. uninstall all VS and any products installed with previous VS installation
2. run installer for VS2017 RC, check every workload (haven't attempted to reduce this)
3. switch to individual components tab, ensure Visual Studio SDK is checked
4. Set install location to E:\ drive instead of C:\ drive (haven't tested otherwise, limited on space, I install everything possible this way)
5. run installer, come back next day (download size prohibits me from doing this faster thanks to lovely dsl connection)
6. open 2017 developer command prompt
7. cd to roslyn git repository
8. ensure roslyn up to date with current master (`git pull`; `git checkout master`; `git reset --hard` just to be sure)
9. run restore.cmd

**Expected Behavior**:

restore.cmd runs successfully, can move forward towards other things

**Actual Behavior**:

essentially #15991  

`C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\` does not contain a `VSSDK\` directory.

**Comment by jasonmalinowski** [comment]
@bbarry Can you share log here from what Restore outputted before it failed?

**Comment by bbarry** [comment]
Aside from the path differences, it was exactly #15991

My `\Git\roslyn\.git\config` file had the wrong value in the origin url.  I'm closing this.
