### ISSUE TITLE
[Wiki] Getting-Started-C%23-Syntax-Transformation contains errors

### ISSUE THREAD

**Issue by mrlacey** [dotnet/roslyn#16880]
**Version Used**: 
wiki doc version 4 (latest)

**Steps to Reproduce**:

The documentation at https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Syntax-Transformation
contains examples that use `MetadataReference.CreateFromAssembly` but this is now obsolete.
Instead, should use `MetadataReference.CreateFromFile`

The lines

            MetadataReference mscorlib =
                    MetadataReference.CreateFromAssembly(typeof(object).Assembly);
            MetadataReference codeAnalysis =
                    MetadataReference.CreateFromAssembly(typeof(SyntaxTree).Assembly);
            MetadataReference csharpCodeAnalysis =
                    MetadataReference.CreateFromAssembly(typeof(CSharpSyntaxTree).Assembly)

should be

            MetadataReference mscorlib =
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location);
            MetadataReference codeAnalysis =
                    MetadataReference.CreateFromFile(typeof(SyntaxTree).Assembly.Location);
            MetadataReference csharpCodeAnalysis =
                    MetadataReference.CreateFromFile(typeof(CSharpSyntaxTree).Assembly.Location);

Note that this code also includes another error (again twice on the page)

The line 

            var rewriterText = File.ReadAllText(rewriterText);

should be 

            var rewriterText = File.ReadAllText(rewriterPath);

I would submit a PR for the fixes but it's in the wiki :/

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #72](https://github.com/dotnet/roslyn-sdk/issues/72) via [**ZenHub**](https://www.zenhub.com/)
