### ISSUE TITLE
MSBuildWorkspace.OpenSolutionAsync fails on vs 2017rc3 csproj files

### ISSUE THREAD

**Issue by GrantErickson** [dotnet/roslyn#16886]
Roslyn: 2.0.0-rc3
VS 2017 RC (15.0.0-RC.3+26127.0) and .NET Core SDK 1.0 RC3 build 004530

Two solutions:
SimpleConsole is a Hello World .NetCore net46 console app. 
RoslynConsoleApp is a .NetCore net46 app that attempts to load SimpleConsole via MSBuildWorkspace.OpenSolutionAsync

When run, workspace.OpenSolutionAsync produces the following diagnostic:
"Msbuild failed when processing the file 'C:\\git\\RoslynCompileFails\\SimpleConsole\\SimpleConsole\\SimpleConsole.csproj' with message: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format."

Repo at: https://github.com/GrantErickson/RoslynCompileFails.git

@MarkMichaelis
@ascott18

**Comment by Pilchie** [comment]
Hmm - my guess is that MSBuildWorkspace is using a VS2015 version of MSBuild that happens to be on the same machine, and it doesn't know about the new schema...

**Comment by mattwar** [comment]
RC3 predates the 'fix' that lets MsbuildWorkspace work against VS2017 msbuild.

**Comment by mattwar** [comment]
I can get this to succeed if I access a more recent version of the roslyn package from the myget feed, and have the new msbuild.exe.config runtime redirects in my App.Config _AND_ manually include the latest Microsoft.Build and Microsoft.Build.Tasks.Core prerelease packages from nuget since they are not being recursively added automatically.

**Comment by GrantErickson** [comment]
Thanks for the quick feedback. Will these packages be available via Nuget before RTM or do we need to use myget. We can also try with a new build of VS. Do you think the existing complexity will be resolved by RTM?

**Comment by mattwar** [comment]
I don't believe there will be another pre-release of these packages.  You'll have to try the Roslyn myget feed to try it before release.

You'll need a Nuget.config in your project directory that looks something like this:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="dotnet.myget.org roslyn" value="https://dotnet.myget.org/F/roslyn/api/v3/index.json" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```
And you'll have to not believe VS/Nuget about what is the most recent version.  You'll want one that is more recent in time (not number) and claims to be a 'RC4' build.

As for the msbuild packages, the most recent prerelease on nuget is sufficient.

None of the complexity will go away by release, though.  So you'll still need to have the correct msbuild packages and the correct App.config msbuild binding redirects.  It is possible that a post release roslyn package could fix the need for you to manually add the msbuild package references.  As for the binding redirects, many have tried and failed trying to find a solution for that one. The removal of msbuild dlls from the GAC has made it more difficult.
