### ISSUE TITLE
Enum-completion contains Enum type itself if some amount of word has been typed.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#16888]
![image](https://cloud.githubusercontent.com/assets/4564579/22532238/d3c9f06a-e89a-11e6-8ef8-cf9eaa1d567d.png)

**Comment by CyrusNajmabadi** [comment]
"CompletionTriggerKind" should not be in the list.  Paging @rchande

**Comment by rchande** [comment]
Seriously? I thought I fixed this.

**Comment by Pilchie** [comment]
I can't repro today.
