### ISSUE TITLE
Support the instrumented clause, for standard and simple code instrumentation

### ISSUE THREAD

**Issue by msfcolombo** [dotnet/roslyn#16896]
# Background

It's common in the implementation of logging, retry handlers and other helpers, to have a method that observes and manages execution of a code block. This is usually performed with lambdas:
```
Instrument("MyAction", () =>
{
    // action code
} );
```
Lambdas imply the following:

- Lambdas cannot interact with parent control flow, such as breaking or continuing a `for` statement, or immediately return a value for the declaring method. They force the developer to return a flag or temporary object to the observer method, which is then returned to the caller, which then must be evaluated and processed. That's a lot of boilerplate just to add instrumentation.
- The observer interface and implementation typically require multiple versions: one for sync and other for async code, one for void and other for returned values. Providers can forget to implement one version.
- The stacktrace contains two additional entries: the Observe call and an internally generated method for the lambda.
- Lambdas often require an additional heap object to provide access to variables outside the lambda body.

Some people suggest the `using` keyword as way of avoiding lambda issues, but `using` doesn't notify the `IDisposable` object about exceptions. This prevents observation of certain outcomes. Also, the `IDisposable` interface is designed for release of unmanaged resources. There is a general assumption that an object cannot be reused after it's disposed, and this assumption doesn't hold for observers. And finally, `using` cannot transparently issue a retry attempt.

# Proposal

The proposal is to make C# support a clear form of instrumentation:
```
instrumented (object-Expr)
{
    // action code
}
```
The object-Expr must return an instance of `IInstrument`. The action code is free to return a value for the declaring method, or to interact with parent flow statements (ie, it can have `break` and `continue`). This makes instrumentation much cleaner and less invasive and disruptive than a lambda. There are clear benefits in readability and editability, not to mention simpler stacktraces and mildly improved performance.

The above code is compiled roughly as if the developer had written:
```
var _temp = object-Expr;
for (var _i = 0; ; ++_i) {
    _temp.NotifyAttempt(_i);
    try
    {
        // action code
    }
    catch (Exception ex)
    {
        if (_temp.NotifyException(_i, ex))
            throw; // Instrumenter wants rethrow.
        continue; // Instrumenter wants retry.
    }
    _temp.NotifySuccess(_i);
    break;
}
```
With this feature, a provider of `IInstrument` implementation can:

- Determine the time when the action started and finished, regardless of outcome.
- Decide if an exception is abortive or if a retry should be attempted.
- Retry as many times as wanted, knowing the number of each iteration.
- Cache and reuse the object especified by object-Expr.
- Throw an exception if the action took longer than expected, at the `NotifySuccess` call.

The provider can also back off (for instance, sleep) during execution of `NotifyAttempt`. In order to support async code, the `IInstrument` interface should also declare the async version `NotifyAttemptAsync`. The compiler decides which method to call from the style of parent method. This brings the additional benefits:

- The provider of an observer cannot forget to support asynchronous code.
- The user will have a single syntax for both sync and async code: `instrument (foo) { ... }`.

**Comment by gafter** [comment]
This appears to be a C# language design proposal. Language design proposals should be opened for discussion on the [csharplang mailing list](https://lists.dot.net/mailman/listinfo/csharplang), and if sufficient support is given, it should be submitted as a pull request to add a [proposal in markdown](https://github.com/dotnet/csharplang/tree/master/proposals) at the [csharplang repository](https://github.com/dotnet/csharplang).

**Comment by jnm2** [comment]
I love everything about this proposal. This is one of those things that would dramatically affect my daily coding.

**Comment by YaakovDavis** [comment]
I suggest the `with` keyword:
```with (logger) {...}```  
`with (benchmarker) {...}`
`with (reattmeptor) {...}`

I also suggest calling the object insider the parenthesis (e.g. `logger`) "executor".
Multiple executors can be used as well:
```
with (benchmarker)
with (reattmeptor)
{
  ...
}
```

**Comment by msfcolombo** [comment]
@YaakovDavis What about:
```
with (benchmarker, reattmeptor, ...)
{
    ...
}
```
?

**Comment by YaakovDavis** [comment]
> @YaakovDavis What about:
> 
> with (benchmarker, reattmeptor, ...)
> {
>     ...
> }
> ?

I personally think that the order of execution/control is less clear with such commas.  
The syntactical structure is very similar to `using` blocks`; with a separate clause, it's clear that the outer clause wraps the inner, and extends it in scope.  

If C# happens to introduce support for commas in `using`s, then users will become familiar with such  pluralities. In that scenario, it'll make sense to support them with this feature as well.

**Comment by jnm2** [comment]
@msfcolombo Can you move this to dotnet/csharplang please?

**Comment by msfcolombo** [comment]
Thanks. Created [csharplang issue 85](https://github.com/dotnet/csharplang/issues/85).
