### ISSUE TITLE
Trying to add two dll references into all projects under a solution, some will fail while others will work.

### ISSUE THREAD

**Issue by happyhebaby** [dotnet/roslyn#16891]
**Version Used**: version 1.3.2

**Steps to Reproduce**:

Repro code snippet:
```C#
                        containRef1 = false;
                        containRef2 = false;
                        foreach (MetadataReference reference in project.MetadataReferences)
                        {
                            if (!containRef1 && reference.Display.EndsWith(codeCoverageConfigDll))
                            {
                                containRef1 = true;
                            }
                            else if (!containRef2 && reference.Display.EndsWith(monitoringSystemDll))
                            {
                                containRef2 = true;
                            }

                            if (containRef1 && containRef2)
                            {
                                break;
                            }
                        }
                        if (!containRef1)
                        {
                            project = project.AddMetadataReference(MetadataReference.CreateFromFile(dllPath1));
                        }
                        if (!containRef2)
                        {
                            project = project.AddMetadataReference(MetadataReference.CreateFromFile(dllPath2));
                        }

                        if (!(containRef1 && containRef2))
                        {
                            changeApplied = workspace.TryApplyChanges(project.Solution);
                            if (!changeApplied)
                            {
                                Console.WriteLine("TryApplyChanges on reference failed on {0}", name);
                            }
                        }
```
**Expected Behavior**:Expect both dll references get added successfully into the new project.

**Actual Behavior**: The dlls get added in some projects, but won't get added for the rest, so for those failed, the workspace.TryApplyChanges(project.Solution) call will return false.
This issue looks similar to bug 13802, which also failed for a small number of product projects, also the large majority projects will pass.
Unfortunately, like bug 13802, our company couldn't share production code, so not sure what other info your team needs in order to debug the issue.

**Comment by mattwar** [comment]
Do you do this code snippet for each project in the solution?  Applying changes for each project separately?  You may be having problems with how you are iterating the projects and applying the changes.

Instead, you might try changing all the  projects in solution at once, like this:

```cs
var solution = workspace.CurrentSolution;
foreach (var id in solution.ProjectIds)
{
    // get the project instance to work on
    project = solution.GetProject(id);

    // change project here ...
    ChangeProject();

   // get solution from changed project before getting next project
   solution = project.Solution;
}

workspace.TryApplyChanges(solution);
```

Or, if you really want to apply each project change one at a time, then at least iterate the project ids, not the projects, and fetch the project each time from the new current solution.

```cs
foreach (var id in workspace.CurrentSolution.ProjectIds)
{
    project = workspace.CurrentSolution.GetProject(id);

    ChangeProject();

   workspace.TryApplyChanges(project.Solution);
}
```

Also, don't recreate the MetadataReference each time you add it to a project.  Create it once so all projects refer to the same instance.  Each MetadataReference actually loads and holds onto a separate copy of the metadata bytes from the file.

**Comment by happyhebaby** [comment]
Hi Matt, the reason I try to save solution change on each project is because of bug 13802. If I save just once after all project get processed, the final save will fail. Other than that, I basically have exact the same code pattern to iterate each project id as you pointed out, but it keeps on failing on a set of projects while pass on the rest of them.
I have found a work around code on bug 13802, so that I can just save the solution once out of the ProjectIds loop, it worked. Still this save within the loop pattern should be a valid usage pattern and should work, but it doesn't.
