### ISSUE TITLE
building project that is converted to .net standard project shows build error

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#16912]
_From @heejaechang on February 2, 2017 21:10_

it is related to https://github.com/dotnet/roslyn-project-system/issues/1450

once project has converted, trying to build the project shows this error

2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1556,5): error MSB5016: The name ".NETStandard,Version" contains an invalid character ".".  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets

_Copied from original issue: dotnet/roslyn-project-system#1451_

**Comment by davkean** [comment]
This is portable.

**Comment by heejaechang** [comment]
@davkean sorry I dont know what that means. I converted project to .net standard through property page and built.

**Comment by davkean** [comment]
This is the portable project system, and not the CPS-based project system, and hence moved the bug to the Roslyn repo as the IDE team owns this.

**Comment by Pilchie** [comment]
@rchande Can you take a look?

**Comment by Pilchie** [comment]
From an internal email thread, this is an issue with a targets change that @nguerrera is fixing.  Closing as external.  @nguerrera is there a pointer to the other issue/PR?
