### ISSUE TITLE
Roslyn unit tests cannot run in VS2015 U3 CE

### ISSUE THREAD

**Issue by orthoxerox** [dotnet/roslyn#16914]
**Version Used**: 
tip of post-dev15

**Steps to Reproduce**:

1. Start with a fresh Win 10 x64 Pro
2. Install VS2015 U3 CE
3. Install the .vsix required by Roslyn
4. Clone, restore, build
5. Open Roslyn.sln in VS, go to Test Explorer

**Expected Behavior**:

All tests are discovered and can be run

**Actual Behavior**:

VS keeps discovering them forever and doesn't allow to run the tests.

I have an earlier branch in my fork where there's no VS integration for xUnit tests, but CodeRush Test Runner works perfectly (neither Test Runner nor Test Explorer work in post-dev15 for me). (https://github.com/orthoxerox/roslyn/compare/features/functors...dotnet:post-dev15). I rolled back the xUnit-related changes in `build/Targets/Dependencies.props` and `build/ToolsetPackages/project.json`, but that didn't help at all.

**Comment by jaredpar** [comment]
Using our repo in VS 2015 is no longer supported in master or post-dev15.  We've taken a number of changes that break the experience.  Even with the new VSIX changes it's unlikely for every scenario to continue working.  

The last branch of the code which should function in VS 2015 is the VS 2017 RC branch.  

https://github.com/dotnet/roslyn/releases/tag/Visual-Studio-2017-RC
