### ISSUE TITLE
Formatting on close brace doesn't work for some items

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#16927]
**Version Used**: 15.0.0-RC.3+26127.0

**Steps to Reproduce**:

1. Paste following code in VS.
```CSharp
class Program
{
    public static void SomeOtherMethod(bool param = false)
    {
                if (true)
                {
                }

                ((string)"").AsEnumerable();
    }
}
```

2. Delete closing brace
3. Type closing brace to trigger formatting
4. The If-Statement is formatted correctly, but the invocation is not.

![image](https://i.gyazo.com/c805d8af369fb0000e4fed93fe785239.gif)

**Comment by YaakovDavis** [comment]
It also doesn't work for some initializers, like:
```
var x = new[]
{
   new Foo { X = ..., Y= ...},
new Foo { X = ..., Y= ...}
}
```

Closing the last brace (or using the Format Document command) doesn't format the code the way you expect.

**Comment by miloush** [comment]
Not sure if the same issue, but property getters don't seem to be formatted the way they used to either:
```C#
    public static bool Test
    {
get
        {
            return true;
        } // retyping this bracket used to indent 'get' correctly and it still does for 'if'
    }
```

**Comment by CyrusNajmabadi** [comment]
Tagging @heejaechang

**Comment by miloush** [comment]
@YaakovDavis if I remember correctly the formatter does not touch these, see also #9702

**Comment by Pilchie** [comment]
1. The original issue is a dupe of https://github.com/dotnet/roslyn/issues/13163
2. Array initializers are never formatted if on multiple lines (though as noted in #9702, we may want to change that)
3. Looks like a bug in what span is chosen to reformat for accessors, as re-typing the property's brace does format it.  @miloush Care to file a separate issue for that?
