### ISSUE TITLE
Support C#7 tuples as default values for optional parameters

### ISSUE THREAD

**Issue by fitdev** [dotnet/roslyn#16921]
**Version Used**: 
C#7 in VS2017RC3

**Steps to Reproduce**:
Right now the following code gives a compilation error:

    void Foo((int, bool) bar = (3, false))
    {    }

**Expected Behavior**:
It should work as if the type of `bar` was the primitive type, since both of its constituent parts are clearly compile-time constant: `3` and `false`

**Actual Behavior**:
> Error CS1736 Default parameter value for 'bar' must be a compile-time constant

**Comment by Unknown6656** [comment]
AFAIK the tuple `(int, bool)` is internally compiled as `struct System::ValueTuple<int, bool>`, meaning that it is not a "primitive" in C#-terms. For this feature to work, one would need a CLI language change to allow "primitive structs" (meaning structures, which are entirely composed of other "primitive structures", pointers and/or primitive fields).
<hr/>
Maybe one should consider the implementation of constant or native structure values being allowed to be used as optional parameters. Take a look at the following <b>only mildly related</b> issues:<br/>
#16095 <br/>
#15079 <br/>
#4982 <br/>
#5474 <br/>

**Comment by AdamSpeight2008** [comment]
Optional Parameter require the default value to be a compile-time constant, as it stored in the metadata.

**Comment by gafter** [comment]
This appears to be a C# language design proposal. Language design proposals should be opened for discussion on the [csharplang mailing list](https://lists.dot.net/mailman/listinfo/csharplang), and if sufficient support is given, it should be submitted as a pull request to add a [proposal in markdown](https://github.com/dotnet/csharplang/tree/master/proposals) at the [csharplang repository](https://github.com/dotnet/csharplang).

**Comment by Unknown6656** [comment]
_Oh jesus christ, not that mailing list again...
I am sorry, but the migration to the mailing list is one huge back-step in my opinion.
I know nobody will miss me, but I will not be further contributing to the C# language design, if it means writing and receiving tons of emails......_

**Comment by Joe4evr** [comment]
@Unknown6656 Sound your voice in #16916

**Comment by Unknown6656** [comment]
@Joe4evr : I will -- I just hoped, that @gafter would also see it, if I write it here .....

**Comment by jcouv** [comment]
I'll go ahead and close this language issue. The current compiler behavior is by-design (tuples don't have a constant value, therefore cannot be used a default values for optional parameters). 
Feel free to open a language issue for discussion on the csharplang repo. Thanks
