### ISSUE TITLE
Incorrect System.Reflection.*Attributes checks in some parts of the code

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#16929]
**Version Used**: Current master branch

Eg. `TypeAttributes` is a mix of flags and enums. To check if a type is eg. non-nested public, one has to first use `VisibilityMask` and then compare the result with eg. `Public`, but some of the code treat `Public` as a flag and use code like `(f & TypeAttributes.Public) == TypeAttributes.Public`.

The following attributes and sub-enums are sometimes used incorrectly:

```
TypeAttributes
	VisibilityMask (NotPublic, Public, NestedPublic, ...)
	ClassSemanticsMask (Class, Interface)

MethodImplAttributes
	CodeTypeMask (IL, ...)
	ManagedMask (Managed, Unmanaged)

MethodAttributes
	MemberAccessMask (PrivateScope, Private, ...)

ManifestResourceAttributes
	VisibilityMask (Public, Private)

FieldAttributes
	FieldAccessMask (PrivateScope, Private, ...)
```

**Comment by akoeplinger** [comment]
In https://github.com/dotnet/roslyn/pull/75081 it was decided to not replace the ManifestResourceAttributes/MethodImplAttributes/TypeAttributes instances since they are not a real issue.

The rest should be good now.
