### ISSUE TITLE
[FUN] Support DestructableAttribution

### ISSUE THREAD

**Issue by cia48621793** [dotnet/roslyn#16923]
**NOTICE: THIS IS A TROLL PROPOSAL, AND THEREFORE THIS PROPOSAL IS MEANINGLESS. DON'T BE SERIOUS ABOUT IT.**

Just because I cannot accept the `Deconstruction` going out of nowhere, I therefore propose the `DestructableAttribution`

```
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
class DestructableAttribute : Attribute {} // Yep, simple as that
```

Before adding the `Destructable`
```
class Point {
    public int X { get; }
    public int Y { get; }

    public Point(int x, int y) { X = x; Y = y; }
    public void Deconstruct(out int x, out int y) { x = X; y = Y; } // What's it gonna do? Can I call this method?
}
var (x, y) = new Point(1, 2);
```
After adding the `Destructable`
```
[Destructable]
class Point {
    public int X { get; }
    public int Y { get; }

    public Point(int x, int y) { X = x; Y = y; }
    public Deconstruct(out int x, out int y) { x = X; y = Y; } // notice how the 'void is removed
    // now the 'Deconstruct' is a reserved word
}
var (x, y) = new Point(1, 2);
```
If a `Deconstruct` was added without attaching `Destructable` attribute, a compiler error will occur:
```
class Point {
    public int X { get; }
    public int Y { get; }

    public Point(int x, int y) { X = x; Y = y; }
    public Deconstruct(out int x, out int y) { x = X; y = Y; }
}
var (x, y) = new Point(1, 2);
```
```
error CSXXXX: Class 'Foo' is not allowed to deconstruct
```

Syntax:
```
<deconstruct> ::= "Deconstruct"
<deconstruct-decl> ::= <method-accessor> <deconstruct> <parameter> <method-stmt>
<class-decl> ::= ... 
               | <deconstruct-decl>*
```
I'm sorry. I don't know much about computer science/EBNF/blah blah blah, I'm still a student tho, so don't make it serious man, I was trying to act funny. (and stupid as well)

Why did I 'propose' this? **Have you considered that older libraries, older classes may contain the `Deconstruct` method as well? Should they be `Deconstructable` at all?** Even though the chance with the exact 'current' syntax is extremely rare, I don't think we should neglect this chance. By adding a `Destructable` attribute this kind of situation can easily, be avoided. 

In addition it can make the code more intuitive by hinting the developer and the IDE/compile which class supports tuple destruction, instead of looking around for the `Deconstruct` method, which can be anywhere inside the class, it can be time-costing finding it.

Since the C# 7.0 is not forming its shapes yet, and we can still change the mechanics of 'Valued tuples' before it was cooked, before the VS2017 final came out.

_#longlivethecsharp
#csharpsuperiority
#fuckjava_

**Comment by gafter** [comment]
This appears to be a C# language design proposal. Language design proposals should be opened for discussion on the [csharplang mailing list](https://lists.dot.net/mailman/listinfo/csharplang), and if sufficient support is given, it should be submitted as a pull request to add a [proposal in markdown](https://github.com/dotnet/csharplang/tree/master/proposals) at the [csharplang repository](https://github.com/dotnet/csharplang).

**Comment by cia48621793** [comment]
@gafter but because of this is not intended for seriousness, let's leave it here somehow.

I have found another point: Just like `async` and `await`,  we should also denote a special identifier to mark the new features, rather than available for nothing.

**Comment by cia48621793** [comment]
@gafter fine, I will pack my 'belongings', but mailing list is really hateful.
