### ISSUE TITLE
SyntaxGenerator has no LockStatement method

### ISSUE THREAD

**Issue by bpierson** [dotnet/roslyn#16934]
SyntaxGenerator has methods like `UsingStatement`, but no way to generate a `lock` block (that I could see). Am I missing something obvious? Shouldn't there be a `LockStatement` method?

**Comment by CyrusNajmabadi** [comment]
PRs welcome :)

**Comment by bpierson** [comment]
Ok, thanks! I don't really know how to contribute, so I'll just do it here. Looks like it would be as simple as this:

(In `SyntaxGenerator`):
```
/// <summary>
/// Creates a statement that represents a lock-block pattern.
/// </summary>
public abstract SyntaxNode LockStatement( SyntaxNode expression, IEnumerable<SyntaxNode> statements );
```

(In `CSharpSyntaxGenerator`):
```
public override SyntaxNode LockStatement( SyntaxNode expression, IEnumerable<SyntaxNode> statements )
{
	return SyntaxFactory.LockStatement(
		expression: (ExpressionSyntax)expression,
		statement: CreateBlock( statements ) );
}
```

I suppose it would be nearly identical in VBSyntaxGenerator, but I didn't look at that code.

**Comment by CyrusNajmabadi** [comment]
Hey @bpierson You can contribute by just Forking this repo, making a branch with these changes, and then opening a PR against Roslyn against your new branch :)

**Comment by CyrusNajmabadi** [comment]
Note: Please make your branch off of our "post-dev15" branch, and not off of our 'master' branch.  'master' is very locked down right now as we try to ship VS2017.  post-dev15 is for where future changes would go, and will likely be released in our Update1 release.

**Comment by bpierson** [comment]
Ok Cyrus - I guess now is as good a time as any... I need to learn how to be a good citizen and contribute to these open source projects. :)

**Comment by CyrusNajmabadi** [comment]
Good luck, have fun!

**Comment by Pilchie** [comment]
@CyrusNajmabadi assigning to you since we can't assign to people outside the org.  Can you help @bpierson get this in shape?

**Comment by CyrusNajmabadi** [comment]
@bpierson Are you going to be able to get to this?  If not, i'll take it.  Thanks!

**Comment by bpierson** [comment]
Hi Cyrus, I would appreciate if you did. I'm going to work on my git skills
on a few lower profile projects first. :) Thanks.

On Feb 20, 2017 7:21 PM, "CyrusNajmabadi" <notifications@github.com> wrote:

@bpierson <https://github.com/bpierson> Are you going to be able to get to
this? If not, i'll take it. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dotnet/roslyn/issues/16934#issuecomment-281226966>, or mute
the thread

**Comment by viceroypenguin** [comment]
@CyrusNajmabadi - I've completed this here: https://github.com/viceroypenguin/roslyn/commit/87a335c0b7b6e4edf168fac45ab1a04f3a535a31

I branched off master because I couldn't find the branch `post-dev15`.  I'll be happy to rebase before submitting a PR.

**Comment by CyrusNajmabadi** [comment]
Looks good.  Just submit a PR and we'll review and merge it in.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/17387
