### ISSUE TITLE
Proposal: Auto-Implemented Property Changes

### ISSUE THREAD

**Issue by Jijjy** [dotnet/roslyn#16948]
Apologies if this has already been discussed, I couldn't seem to find anything here.

If you've ever worked with xamarin you would have came across something like this:
```
private string _foo;
public string Foo
{
    get { return _foo; }
    set
    {
        _foo = value;
        OnPropertyChanged("Foo");
    }
}
```
Which, frankly, looks absolutely horrific when you have a bunch of these together. Can we not have something like this?
```
public string Foo { get; set; notify; }
```
Or
```
public string Foo { get; set; } => FooChanged("Bar");
```

Having moved into the ASP.NET MVC world i'm a little out of practise with these things, but it does seem like they could be made much more elegant.

**Comment by Joe4evr** [comment]
Yeah, it's been asked before. This is one of the examples given for Code Generators.

**Comment by Jijjy** [comment]
Having looked more, seems like a common request and Code Generators look like they'll make this fairly redundant
