### ISSUE TITLE
Feature Request: Include 'ifnull' and 'ifnotnull' conditions

### ISSUE THREAD

**Issue by kunal-chowdhury** [dotnet/roslyn#16946]
We already have 'if', 'elseif', 'else' blocks for condition checking. What if we can add few more conditions like 'ifnull' and 'ifnotnull'? This will improve the code which maximum developers use.

**For example,**
ifnull (person) { ... }       // equivalent to => if (person == null) { ... }
ifnotnull (person) { ... }       // equivalent to => if (person != null) { ... }

**Comment by svick** [comment]
How does this improve the code? By saving a few characters (or in the negative case, a single character)? That does not seem worth it to me.

An alternative is to change the editor behavior to make this code easier to write. ReSharper already does this: if you type `person.null` and press <kbd>Enter</kbd>, it generates the whole `null` check `if` statement.

**Comment by miloush** [comment]
Could also be easily solved with snippets...

**Comment by Thaina** [comment]
`==null` is already shorter than
`notnull`

**Comment by jcouv** [comment]
I'll go ahead and close this. Continue the discussion on csharplang if still active.
Here's one issue that seems related: https://github.com/dotnet/csharplang/issues/882. There may be others.
