### ISSUE TITLE
Local functions extension method

### ISSUE THREAD

**Issue by UnoSD** [dotnet/roslyn#16959]
Will local functions support being used as extension methods?

It could be useful to make code more readable and not clutter the type.

**Comment by svick** [comment]
[It seems they currently can't.](http://tryroslyn.azurewebsites.net/#b:master/f:r/M4FwhiCWDGAE0BszGLAwgKAN4dn2oEMsAbgPaQAmsAsgBQCUu+O+bpF1AonSABaRUZAEYArAKbQQsMg1hYAvszxKFQA=) This code:

```c#
static class C
{
    static void M()
    {
        void E(this object o) {}
    }
}
```

Produces this not quite clear error message:

> error CS1106: Extension method must be defined in a non-generic static class

Though maybe this can be reconsidered as part of https://github.com/dotnet/roslyn/issues/16271.

**Comment by jcouv** [comment]
I'll move this discussion to csharplang, as it is not currently actionable as a compiler bug (current behavior is by design).

**Comment by jcouv** [comment]
Issue moved to [dotnet/csharplang #1024](https://github.com/dotnet/csharplang/issues/1024) via [**ZenHub**](https://www.zenhub.com/)
