### ISSUE TITLE
Target typing for return

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#16952]
(edited)

**Version Used**: 2.0.0.61401

```C#
static void Test(List<int> i) { }
static void Test(Func<List<int>> f) { }
static void Main(string[] args)
{
    Test(() => new |
}
```

Am I wrong to have expected `List<int>` in the autocompletion list, if not preselected?

**Comment by CyrusNajmabadi** [comment]
You're not wrong to expect this.  But it's just not something we've done yet.  If you want this, you'll have to fix up https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs to properly handle this case.

PRs welcome.

**Comment by CyrusNajmabadi** [comment]
Oh, my bad.  this is by design.  ```Action<List<int>>``` means that this is a delegate which *takes* a List as it's argument.  Not that it *returns* a List.  If you change this into a Func, then everything works properly:

![image](https://cloud.githubusercontent.com/assets/4564579/22621859/8ceb91b8-eae2-11e6-995c-503268a1a402.png)

**Comment by miloush** [comment]
OK that was meant to be `Func` of course, sorry. The problem is though I oversimplified the repro. See the edited version now (added overload).

**Comment by CyrusNajmabadi** [comment]
Reopening.

**Comment by CyrusNajmabadi** [comment]
With this repro, i'll now repeat:

> You're not wrong to expect this. But it's just not something we've done yet. If you want this, you'll have to fix up https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs to properly handle this case.

> PRs welcome.

:)

Basically, the likely issue is that we don't apply any heuristics when trying to figure out which overload this corresponds to.  We'll need that to get this scenario working.

**Comment by miloush** [comment]
Hm I see, this goes together with the problem that autocompletion is no longer connected to the overload selection in IDE. There is more obvious set-up that will hit the same problem:

```C#
class A { }
class B { }

void Test(A a) { }
void Test(B b) { }

Test(new |  // what to preselect here?
```

**Comment by CyrusNajmabadi** [comment]
This works for me: 

![image](https://user-images.githubusercontent.com/4564579/152591215-48513f5a-fc40-4d87-b3f2-7c8e56f00788.png)
