### ISSUE TITLE
[idea] return using to enforce using on upper stack

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#16958]
For a long time we have using and IDisposable but we need to rely on api consumer to proper use `using` or calling `Dispose`

So, by the same idea of `async`/`await`. I think we could treat `using` in the same manner. We should be able to mark a function to return using on any `IDisposable` object. And the consumer must try to explicitly use Dispose or using, or continue return using, else it cause error

```C#
// any better keyword?
public using HttpWebResponse Request(this HttpMethod method,string url)
{
    var req = HttpWebRequest.CreateHttp(url);
    req.Method = method.ToString();
    return using req.GetResponse();
}

////

void DoSomething()
{
    var resp = HttpMethod.Get.Request("url"); // ERROR
}

void DoSomethingInUsing()
{
    using(var resp = HttpMethod.Get.Request("url"))
    {
        // do anything
    }
}

void DoSomethingDispose()
{
    var resp = HttpMethod.Get.Request("url");

    resp.Dispose(); // Should be ok?
}

using HttpWebResponse DoSomethingReturn()
{
    var resp = HttpMethod.Get.Request("url");
     // do something
    return using resp;
}
```

Also, I'm not sure if it possible but, I want this feature possible to write cleanup logic after return using

```C#
public using HttpWebResponse Request(this HttpMethod method,string url)
{
    var req = HttpWebRequest.CreateHttp(url);
    req.Method = method.ToString();
    var resp = req.GetResponse();
    return using resp; // Act like async or yield
    // split code after this line into defer state
    resp.Close();
}

void DoSomethingInUsing()
{
    using(var resp = HttpMethod.Get.Request("url"))
    {
        // do anything

        // before the end of the block it will inject
        // resp.Close()
        // That was deferred there to here
    }
}
```

ps.

In the class and constructor scope, I'm not sure how to handle. One way is to allow this feature only local function. Another way might also enforce the class to implement `IDisposable` and call `Dispose` of that field

**Comment by svick** [comment]
I think that adding something like this would be much more complicated, because there are lots of you things you can do with objects C# and where you have to track that the object is correctly disposed. For example, how do you handle passing the object to other functions, which can then store it in fields etc.?

And if you forbid all those complicated cases, it makes the feature much less useful.

There is already a proposal that tries to solve all those issues: Destructible Types https://github.com/dotnet/roslyn/issues/161 (though it didn't seem to gain much traction with the language design team).

**Comment by jnm2** [comment]
@Thaina I would not like the method that returns an IDisposable telling me how to use it. There is a very good reason for this. Sometimes I have no option but to set the function's return value to a class field and only dispose it when the containing class, which is itself disposable, is disposed.

**Comment by Thaina** [comment]
@svick Well I really cannot consider

One way is just let it be. If you temp that object in any field then it just pass. It satisfied that already out of scope

It's like error when declare variable in one line `if` block. Compiler just know that it not possible to use that variable anywhere so it throw error

In this case, compiler just know that if you don't temp it in any field, it not possible to dispose that object anywhere so it throw error for those condition

Another way might also have `using` on field that would ask you to generate Dispose function

```C#
class A
{
    using HttpWebRequest tmpRequest;
    public void DoSomething()
    {
        tmpRequest = HttpMethod.Get.Request("url"); // Can set it on field with using
    }

    // ERROR : need to implement Dispose and dispose that field
}
```

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
