### ISSUE TITLE
Edit and Continue for out variable declarations

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#16960]
I haven't found an issue tracking this very annoying problem, i.e. that EnC is disabled when there is out variable declaration wherever inside the member.

This makes using the feature not justified when just declaring the variable on a separate row gives me EnC.

Related issues: #12736 #13754

**Comment by HaloFour** [comment]
Sounds like an issue of the tooling just not having caught up yet?  To my knowledge out declarations always transform into equivalent C# constructs that support E&C today.
