### ISSUE TITLE
SyntaxGenerator generates illegal event declaration for interfaces in C#

### ISSUE THREAD

**Issue by ali-hk** [dotnet/roslyn#16964]
**Version Used**: 
Latest VS 2015 Update 3 release

**Steps to Reproduce**:

1. Get a SyntaxGenerator from a document
2. `var eventSyntax = _generator.EventDeclaration("SomeEvent", _generator.IdentifierName("EventHandler");`
       (or instead a syntax node generated from an IEventSymbol for the second parameter)
3. Add eventSyntax to an **InterfaceDeclaration**.

**Expected Behavior**:
`event EventHandler SomeEvent;`

**Actual Behavior**:
`event EventHandler SomEvent
{
     add;
     remove;
}`

**Comment by ali-hk** [comment]
Easy repro:

            AdhocWorkspace workspace = new AdhocWorkspace();
            SyntaxGenerator generator = SyntaxGenerator.GetGenerator(workspace, LanguageNames.CSharp);
            var eventNode = generator.EventDeclaration("ReproEvent", generator.IdentifierName("EventHandler"));
            var ifaceNode = generator.InterfaceDeclaration("IReproInterface", members: new[] { eventNode });
            var classNode = generator.ClassDeclaration("ReproClass", members: new[] { eventNode });
            Console.WriteLine(ifaceNode.NormalizeWhitespace().ToFullString());
            Console.WriteLine(classNode.NormalizeWhitespace().ToFullString());

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/issues/16986
