### ISSUE TITLE
'Better conversion from expression' isn't preserved by tuple literals

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#16967]
Given an expression E<sub>1</sub> which matches exactly a type T<sub>1</sub> and an expression E<sub>2</sub> for which some type T<sub>21</sub> is a better conversion target than some other type T<sub>22</sub>, the tuple type (T<sub>1</sub>, T<sub>21</sub>) should be a better conversion target than the tuple type (T<sub>1</sub>, T<sub>22</sub>) for a tuple literal (E<sub>1</sub>, E<sub>2</sub>). 

Currently the statement above doesn't hold. Consequently, valid function calls become compilation errors if their arguments are 'tuplified'.

```cs
using System;
public class C
{
  void M1(object x, short y)
  {
      M1(x, 5);  // compiles
  }

  void M1(object x, ushort y)
  {
  }
    
  void M2((object x, short y) x)
  {
      M2((x.x, 5));  // error CS0121: The call is ambiguous between the following methods or properties: 'C.M4((object x, short y))' and 'C.M4((object x, ushort y))'
  }

  void M2((object x, ushort y) x)
  {
  }
    
  void M3(object x, Action y)
  {
      M3(x, () => throw null);  // compiles
  }

  void M3(object x, Func<int> y)
  {
  }
    
  void M4((object x, Action y) x)
  {
    M4((x.x, () => throw null));  // error CS0121: The call is ambiguous between the following methods or properties: 'C.M2((object x, Action y))' and 'C.M2((object x, Func<int> y))'
  }
   
  void M4((object x, Func<int> y) x)
  {
  }
}
```

**Comment by gafter** [comment]
@jcouv @MadsTorgersen @VSadov You may want to look to see if the current behavior is as intended.

**Comment by jcouv** [comment]
From discussion with @VSadov, this is by design. A very similar example was discussed before, in https://github.com/dotnet/roslyn/issues/10801, and LDM decided the complexity was not worth it.

**Comment by jcouv** [comment]
Thanks @TessenR for reporting this issue. 
We looked back at LDM notes and this has been considered already, but the conclusion was not to support it.
