### ISSUE TITLE
.editorconfig changes not picked up until document reload

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#16978]
**Version Used**: d15rel 26205.0

Create a ConsoleApp with an .editorconfig file next to the .csproj.
Update the .editorconfig file to contain:
```
root = true

[*]
indent_size = 13
```

The indent_size of 13 won't be applied until you close and reopen Program.cs (or whatever your file is called). Close & reopen to observe the crazy indent_size.

Now, change the indent_size to 4 and notice that the new setting is not applied again until the file is reloaded

**Comment by dpoeschl** [comment]
@jmarolf I'm not sure which layer of caching is to blame here.

**Comment by Pilchie** [comment]
Project reload, or file reload?  I believe this is a dupe.

**Comment by dpoeschl** [comment]
@Pilchie project reload. Closing/opening the .editorconfig does nothing in this case.

**Comment by dpoeschl** [comment]
@Pilchie Scratch that. Document reload does it.

**Comment by dpoeschl** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/15003
