### ISSUE TITLE
Outlining preview gets more and more truncated as lines are added

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#16976]
**Version Used**: d15rel 26205.0

![image](https://cloud.githubusercontent.com/assets/235241/22662170/f2167dd4-ec5c-11e6-96fd-dd8dc004492a.png)

![image](https://cloud.githubusercontent.com/assets/235241/22662215/14d1b668-ec5d-11e6-9058-9da5aa798f09.png)

**Comment by dpoeschl** [comment]
Reminiscent of https://github.com/dotnet/roslyn/issues/15004

**Comment by Pilchie** [comment]
We do some scaling to make those previews smaller - maybe it's not accurate with how much we shrink the tooltip itself?

**Comment by reaction1989** [comment]
Where does that scaling happen? If you point me to that i would try looking into that.

**Comment by Pilchie** [comment]
It starts [here](http://source.roslyn.io/Microsoft.CodeAnalysis.EditorFeatures/R/09c2dc8bf5eac04b.html) I think.

**Comment by reaction1989** [comment]
@dpoeschl  I can not reproduce this issue on the current master. 
I am running a 13" Full HD Display.

![image](https://cloud.githubusercontent.com/assets/873751/23093634/003d0032-f5e9-11e6-8427-7ffa41d9afde.png)

**Comment by CyrusNajmabadi** [comment]
I can't repro this either.  Closing out.
