### ISSUE TITLE
Vote for your favorite discussions platform

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#16971]
Vote your choices [here](https://www.surveymonkey.com/r/FX2PFF9)

1. Discourse. 

2. Maling list. 

3. GitHub. 

4. Other. 

[Link to the results](https://www.surveymonkey.com/results/SM-BW7727W3/)

**If you choose the `Other` option feel free to elaborate on it here.**

**Comment by eyalsk** [comment]
1. GitHub

2. Discourse

**Comment by DavidArno** [comment]
1. Discourse
2. Other (subject to another good suggestion by the language team).

**Comment by HaloFour** [comment]
1. Discourse
2. Github

Just an aside (not to start any conversations here) but maybe a SurveyMonkey survey (or similar) would be a better tool?

**Comment by eyalsk** [comment]
@HaloFour on it.

**Comment by eyalsk** [comment]
@DavidArno, @HaloFour updated, thanks. 😉

**Comment by DavidArno** [comment]
The poll is letting me select multiple items for each column. Didn't click submit yet, so not sure if it then reports an error. But it would be good to make them radio buttons, rather than checkboxes, if you can.

**Comment by eyalsk** [comment]
@DavidArno Odd, it is two columns of radio buttons, I'll check it out.

**Comment by alrz** [comment]
This's probably a [*ranking question*](https://help.surveymonkey.com/articles/en_US/kb/How-do-I-create-a-Ranking-type-question), but it's alright. :)

**Comment by eyalsk** [comment]
@alrz Yeah I noticed it only after I created it.. can't change it now, the only thing I can change is the weight but the type of the survey. :D

**Comment by MadsTorgersen** [comment]
The C# and VB design teams have a recommendation for where and how to conduct language design discussion: #17054. It aligns well with the votes in the survey. 

Please comment there by Friday Feb 10!

Thanks,

Mads
