### ISSUE TITLE
Formatting with "Indent block contents" set to true sometimes doesn't undo formatting with "Indent block contents" set to false.

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#16977]
**Version Used**: d15rel 26205.0

**Steps to Reproduce**:

1. Start with "Indent block contents" set to true
    ```C#
    class Program
    {
        static void Main()
        {
            System.Console.WriteLine("Hello");
        }
    }
    ```
2. Set "Indent block contents" to false, and format document. You get:
    ```C#
    class Program
    {
        static void Main()
        {
        System.Console.WriteLine("Hello");
        }
    }
    ```

3. Set "Indent block contents" to true, and format document.

**Expected Behavior**: The block contents go back to looking like the code in step 1 above
**Actual Behavior**: Nothing changes.

**Note**: This only repros sometimes. When it repros, you can change some code and then try format document again and it works as expected. I can make it repro fairly easily, so I'm happy to help if you can't repro it.

**Comment by Pilchie** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/16161?

**Comment by Pilchie** [comment]
Giving to @jasonmalinowski as potential dupe of #16161

**Comment by jasonmalinowski** [comment]
Old issue, and probably a dupe of that one.
