### ISSUE TITLE
Refactoring "Generate method" not suggested.

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#16975]
**Version Used**: Visual Studio 2017 RC 15.0.0-RC3+26127.0

**Code to Reproduce**:
```csharp
using Microsoft.CodeAnalysis;

namespace My
{
    public static class Foo
    {
        public static void Bar(SyntaxNode node)
        {
            ReportDiagnostic(node); // "Generate method" not suggested here

            ReportDiagnostic2(node); // "Generate method" suggested here
        }
    }
}
```

It seems that this error occurs when there is a type with same name as method that would be generated. In this case there is enum "Microsoft.CodeAnalysis.ReportDiagnostic".

**Comment by Pilchie** [comment]
Good catch, we likely just don't listen to the right diagnostic id for this case (CS1955).
