### ISSUE TITLE
Rename with CTRL-V

### ISSUE THREAD

**Issue by Hosch250** [dotnet/roslyn#16988]
**Version Used**: VS Community 2015

**Steps to Reproduce**:
1. Create an identifier (variable, class...).
2. Copy something into the clipboard.
3. Start renaming the identifier, and at some point press "CTRL-V" to paste the clipboard contents into the identifier name.

**Expected Behavior**:
I would expect other identifiers to update with the new contents and continue updating as new characters are deleted/typed.

**Actual Behavior**:
The identifier being edited continues to update correctly, but references are not updated after this point.

**Comment by Pilchie** [comment]
We were unable to reproduce this with VS 2017 RC.4 - can you give that a try and let us know if it still happens.

**Comment by Hosch250** [comment]
Verified as fixed in VS 2017.
