### ISSUE TITLE
Improve the error message for compiler error CS0191

### ISSUE THREAD

**Issue by Worthaboutapig** [dotnet/roslyn#16982]
**Version Used**: 
VS 2015 Community 14.0.25431.01 Update 3, .NET 4.6.01586

**Steps to Reproduce**:
1. Create a class 'A' with a readonly field 'foo'.
2. Create a class 'B' which derives from class 'A'.
3. Attempt to assign a value to 'foo' in the constructor of 'B'.

**Expected Behavior**:
"A readonly field cannot be assigned to (except in the constructor of the class in which the field is defined or a variable initializer)"

**Actual Behavior**:
"A readonly field cannot be assigned to (except in a constructor or a variable initializer)"

The error message as it stands is wrong/ incomplete, which is confusing.

**Comment by 06needhamt** [comment]
PR is Out #22874

**Comment by Evangelink** [comment]
Is there anything left to do on this?

**Comment by trivalik** [comment]
Variable initializer are not allowed to assign readonly fields in 4.8.

`
    public class A
    {
        public readonly bool b;
    }
`

Use which lead to CS0191
`
            var a = new A()
            {
                b = chkBox.Checked
            };
`
