### ISSUE TITLE
Is T expressions result in CS8121 error if sealed class, implementing a generic interface, is used for T

### ISSUE THREAD

**Issue by DavidArno** [dotnet/roslyn#16993]
Visual C# 2017 RC 00369-50000-00000-AA146
Visual Studio/15.0.0-RC.3+26127.3: 

**Steps to Reproduce**:

Attempt to compile the following code:

````cs
namespace NS1
{
    public interface ITest<T> {}

    internal class Test1 : ITest<int> { }
    internal sealed class Test2 : ITest<int> { }

    internal class C<T>
    {
        public void F(ITest<T> x)
        {
            if (x is Test1 z) { }
            if (x is Test2 y) { }
        }
    }
}
````

**Expected Behavior**:
All compiles OK.

**Actual Behavior**:
The `if (x is Test2 y) { }` line results in the error:
`CS8121 An expression of type ITest<T> cannot be handled by a pattern of type Test2`

**Comment by controlflow** [comment]
Hm, ordinary `x is Test2` compiles fine

**Comment by DavidArno** [comment]
@controlflow,

Indeed, it's only when the new `x is T y` pattern match is used that the problem occurs and only when the base type is generic and the type in the pattern is sealed.

(It took quite some time to distil down the error I had in my code to this specific set of conditions! 😁 )

**Comment by DavidArno** [comment]
@Pilchie,

I notice you have only tagged this as "Area-Language-Design", rather than as a bug. Does this mean that the `x is T y` pattern deliberately doesn't support sealed classes? Is there anything documented on why this is the case, if so?

**Comment by Pilchie** [comment]
Just trying to get it closer to the right people looking at it :)

**Comment by DavidArno** [comment]
@Pilchie, OK, thanks for the clarification. I'll be quiet now 😀

**Comment by aelij** [comment]
Also note that the "use pattern matching" analyzer produces an incorrect code fix (IDE0019) that results in non-compilable code in these cases.

**Comment by CyrusNajmabadi** [comment]
tagging @gafter

**Comment by gafter** [comment]
The simple way to demonstrate that this is the same issue is to see if you get an error when the body of F is rewritten this way:

``` c#
            //if (x is Test1 z) { }
            var z = (Test1)x;

            //if (x is Test2 y) { }
            var y = (Test2)x;
```

Indeed, the second cast results in an error.

So this is a dup of https://github.com/dotnet/csharplang/issues/154
