### ISSUE TITLE
Is it possible to sort suggestion base on type hierarchy?

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#16996]
_From @Thaina on May 18, 2016 4:14_

I would like vscode in C# could have this feature from monodevelop. To sort members of an object by the class it defined

![image](https://cloud.githubusercontent.com/assets/1042507/15347193/65abbb7c-1ce9-11e6-8f69-68e4ec247936.png)

It quite useful for class with a load of member from hierarchy. Such as monobehaviour in unity

_Copied from original issue: OmniSharp/omnisharp-vscode#337_

**Comment by alrz** [comment]
Grouping members like that would be annoying in the completion list, perhaps just mention the type on the right of the row in the list (and optionally sort by it)?

**Comment by Thaina** [comment]
I have already request #16685

And I also thinking that we should made it in omnisharp

**Comment by DustinCampbell** [comment]
I didn't release https://github.com/dotnet/roslyn/issues/16685 was already there. I'll resolve this in favor of that.

Remember that OmniSharp has deep ties to Roslyn. If we did it in Roslyn, I'd want in OmniSharp, and thus VS Code.
