### ISSUE TITLE
Class diagram doesn't show the refness of ref returns

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#17005]
**Version Used**: d15rel 26206.00

**Steps to Reproduce**:

1. Create a C# new project.
2. Add a method like `static ref int MethodWithRefReturn() { }`
3. View the method in class diagram.

**Expected Behavior**: The refness is shown in class diagram.

**Actual Behavior**: It's not. If you change it, refness is blown away.

![image](https://cloud.githubusercontent.com/assets/201340/22715933/2edaa056-ed48-11e6-8371-fc7239f7848e.png)

**Comment by CyrusNajmabadi** [comment]
Class diagram is legacy and is not being updated.
