### ISSUE TITLE
Completion lists in workflow expression editors doesn't show help

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#17009]
**Version Used**: d15rel 26206.00

**Steps to Reproduce**:

1. Type DateTime.Now in an workflow expression editor.

**Expected Behavior**: I see help in the tooltip.

**Actual Behavior**: itty bitty tooltip.

![image](https://cloud.githubusercontent.com/assets/201340/22716521/41b7ad88-ed4b-11e6-8566-130166bd2654.png)

**Comment by eriawan** [comment]
@jasonmalinowski could I know where (the code/file location) to look for this?

I'll try to fix this 🙂

**Comment by jasonmalinowski** [comment]
@eriawan It looks like the place to start would be the GetDescriptionAsync function [here](https://github.com/dotnet/roslyn/blob/1168c4cf7e498fa11c43522c80b6cdc1d16985a5/src/EditorFeatures/Core/Implementation/IntelliSense/Completion/Presentation/CustomCommitCompletion.cs#L57-L62). I will warn though it's quite possible this is a Workspace setup issue where we're not setting up something right so the references aren't getting documentation, and the code that sets _that_ up is internal to the workflow editor itself which isn't open source.

**Comment by eriawan** [comment]
@jasonmalinowski thanks! I have tested the code, and you're right that the GetDescriptionAsync is the right starting place. Is there any kinds of documentation to set up the Workspace so the references can be correctly linked? I'd like to try that too.

Thank you in advance 🙂

**Comment by jasonmalinowski** [comment]
@eriawan I guess if I were you I'd trace for the expression editor case and the regular "typing in a regular C# file" case, and see where things start differing. At some point there's some difference _somewhere_ and I'm not sure where it would be. My understanding of the code is this bug shouldn't exist, which is why it's hard to guess where the problem is.

**Comment by eriawan** [comment]
@jasonmalinowski many thanks! I'll trace that too.

**Comment by eriawan** [comment]
Hmm... strange. On VS 2015 U3, works fine.

I'll try to dive deeper on VS 2017 Workflow. I'm using VS 2017.2.

**Comment by eriawan** [comment]
@jasonmalinowski , the branch that you described doesn't exist anymore.

> @eriawan It looks like the place to start would be the GetDescriptionAsync function [here](https://github.com/dotnet/roslyn/blob/1168c4cf7e498fa11c43522c80b6cdc1d16985a5/src/EditorFeatures/Core/Implementation/IntelliSense/Completion/Presentation/CustomCommitCompletion.cs#L57-L62). 

Could you help me to give more info on which branch that has this link (quoted above) that you have provided?

**Comment by eriawan** [comment]
Hi @jasonmalinowski ,

In VS 2015 Update 3, the workflow works:

![image](https://cloud.githubusercontent.com/assets/8773147/26195119/eab49364-3be4-11e7-81ea-f817d0ecfc4f.png)

Unfortunately, if I use microsite branch, VS 2015 is broken. I got this exception:

![image](https://cloud.githubusercontent.com/assets/8773147/26201562/d2036e94-3bfd-11e7-8684-d11c16b56e02.png)

This is the stack trace:

```
System.ArgumentException occurred
  HResult=0x80070057
  Message=currentPosition  TextBuffer does not match with current TextBuffer
  Source=Microsoft.VisualStudio.Platform.VSEditor
  StackTrace:
   at Microsoft.VisualStudio.Text.Operations.Implementation.NaturalLanguageNavigator.GetExtentOfWord(SnapshotPoint currentPosition)
   at Microsoft.CodeAnalysis.Editor.Implementation.TextStructureNavigation.AbstractTextStructureNavigatorProvider.TextStructureNavigator.GetExtentOfWordWorker(SnapshotPoint position, CancellationToken cancellationToken) in D:\GITHUB_REPO\roslyn\src\EditorFeatures\Core\Implementation\TextStructureNavigation\AbstractTextStructureNavigatorProvider.TextStructureNavigator.cs:line 113
   at Microsoft.CodeAnalysis.Editor.Implementation.TextStructureNavigation.AbstractTextStructureNavigatorProvider.TextStructureNavigator.<>c__DisplayClass7_0.<GetExtentOfWord>b__0(IWaitContext waitContext) in D:\GITHUB_REPO\roslyn\src\EditorFeatures\Core\Implementation\TextStructureNavigation\AbstractTextStructureNavigatorProvider.TextStructureNavigator.cs:line 54
   at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.VisualStudioWaitIndicator.Wait(String title, String message, Boolean allowCancel, Boolean showProgress, Action`1 action) in D:\GITHUB_REPO\roslyn\src\VisualStudio\Core\Def\Implementation\Utilities\VisualStudioWaitIndicator.cs:line 43
   at Microsoft.CodeAnalysis.Editor.Host.IWaitIndicatorExtensions.Wait(IWaitIndicator waitIndicator, String title, String message, Boolean allowCancel, Action`1 action) in D:\GITHUB_REPO\roslyn\src\EditorFeatures\Core\Host\IWaitIndicator.cs:line 21
   at Microsoft.CodeAnalysis.Editor.Implementation.TextStructureNavigation.AbstractTextStructureNavigatorProvider.TextStructureNavigator.GetExtentOfWord(SnapshotPoint currentPosition) in D:\GITHUB_REPO\roslyn\src\EditorFeatures\Core\Implementation\TextStructureNavigation\AbstractTextStructureNavigatorProvider.TextStructureNavigator.cs:line 48
   at Microsoft.AppInsights.GettingStarted.Editor.LightBulb.SuggestedActionSource.TryGetWordUnderCaret(Boolean force, SnapshotSpan range, TextExtent& wordExtent)
   at Microsoft.AppInsights.GettingStarted.Editor.LightBulb.SuggestedActionSource.<>c__DisplayClass13_0.<HasSuggestedActionsAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```
The document always returns `null` when calling `var document = GetDocument(position, cancellationToken)` in line 85, in method `TextStructureNavigator.GetExtentOfWordWorker(SnapshotPoint position, CancellationToken cancellationToken)`.
I think there are some changes in the code between microsite and the Roslyn used in VS 2015 Update 3.

Which branch that's used by VS 2015 Update 3 that could I use? Because in the VS 2015 Update 3 RTM, the tooltip help works well.
I'll try to compare the deltas of change between microsite and release 1.3.2 for now.

**Comment by eriawan** [comment]
@jasonmalinowski after further debugging, I found these facts:

- The document object above (in my previous post) will always be null because the workspace (screenshot below) will always returns null.
- the object that return the workspaceregistration fails to get the workspace, although looking at the key value of `s_bufferToWorkspaceRegistrationMap` has this list of key-value pair, and only one of the element returns a key-value pair that has value of workspace object not null 

This is my current debug screenshot:

![image](https://cloud.githubusercontent.com/assets/8773147/26202497/db3d2e4c-3c01-11e7-892d-6cbcac347b1a.png)

My questions are:

- Is this the correct behavior?
- Also looking at the code, the `s_bufferToWorkspaceRegistrationMap` is readonly but somehow it has values in it. When does the value get inserted/added?

**Comment by eriawan** [comment]
@jasonmalinowski 
just quick inquiry, I need to know some aspects about getting the workspace. 
My questions are:

- Is this the correct behavior?
- Also looking at the code, the s_bufferToWorkspaceRegistrationMap is readonly but somehow it has values in it. When does the value get inserted/added?

**Comment by jasonmalinowski** [comment]
Oops sorry my inbox has been overflowing the past few days. :frowning:

Which text buffer is being passed in for the lookup for the workspace registration? Is that a different text buffer than the one where we triggered completion from the start?

The exception you're seeing with NaturalLanguageNavigator is a known bug with the editor, but the exception should be getting caught and ignored. I'd suggest you ignore it for the purposes of this debugging. (FYI to @olegtk this is another form of the suggested actions projection bug.)

> Also looking at the code, the s_bufferToWorkspaceRegistrationMap is readonly but somehow it has values in it. When does the value get inserted/added?

The field itself is readonly, but ConditionalWeakTable isn't an immutable type -- it can still get things added and removed.

> I think there are some changes in the code between microsite and the Roslyn used in VS 2015 Update 3.

If you meant the microupdate branch, there were a few changes but not many. We have tags for all the various releases you can look at and compare: https://github.com/dotnet/roslyn/compare/Visual-Studio-2015-Update-3...microupdate

**Comment by eriawan** [comment]
@jasonmalinowski 

> Which text buffer is being passed in for the lookup for the workspace registration? Is that a different text buffer than the one where we triggered completion from the start?

To be honest, I don't know which text buffer is being passed, because it is an array/collection that has 4 elements, and one element is full of comments, the rest 3 elements contain text buffer.

**Comment by jasonmalinowski** [comment]
@eriawan Do you mean the buffer being passed was a "projection buffer" of other buffers?

**Comment by eriawan** [comment]
@jasonmalinowski 

sorry, I was busy on my day job for the last 4 days.
Could you elaborate on "projection buffers"? what kind of buffers for TextBuffer implementations?

**Comment by jasonmalinowski** [comment]
@eriawan: https://msdn.microsoft.com/en-us/library/dd885240.aspx#projection

The workflow editor takes a buffer that is a full bit of source (basically, surrounding the expression with a method and a return statement), and then uses projection to display a buffer that is just the expression itself. Roslyn is analyzing the full buffer (because we need a valid file), but you only see the projection buffer.
