### ISSUE TITLE
Class diagram doesn't show tuple types

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#17003]
**Version Used**: d15rel 26206.00

**Steps to Reproduce**:

1. Create a new project, and add System.ValueTuple.
2. Add a new method that consumes a tuple.
3. View the class diagram of the containing type, and look at the method.

**Expected Behavior**: The tuple type is shown as the type of the argument.

**Actual Behavior**:

![image](https://cloud.githubusercontent.com/assets/201340/22715873/e779d178-ed47-11e6-9e67-e0a03a234cb9.png)

**Comment by jcouv** [comment]
Consider adding this to the [IDE test plan](https://github.com/dotnet/roslyn/blob/master/docs/contributing/IDE%20Test%20Plan.md) template.

**Comment by CyrusNajmabadi** [comment]
Class diagram is legacy and is not being updated.
