### ISSUE TITLE
Invoking the light bulb in a workflow expression editor crashes

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#17008]
**Version Used**: d15rel 26206.00

**Steps to Reproduce**:

1. Create a new workflow console application.
2. Add an If block in the workflow.
3. Type Console.WriteLine() in the if block.
4. Select the expression.
5. Ctrl+.

**Expected Behavior**: nothing happens

**Actual Behavior**: it crashes.

**Comment by CyrusNajmabadi** [comment]
Workflow is not a support scenario anymore.  CLosing out as we are not going to do any work here without a divisional shift.
