### ISSUE TITLE
Add method brackets when selecting it with the intellisense

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#17010]
_From @CarlosTorrecillas on July 26, 2016 16:6_

## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
VS Code version: 1.3.1
C# Extension version: 1.3.0
## Steps to reproduce

Create a private method
Start typing the name of the new method created in a different method of the same class (or where the scope of the method applies).
Select the method from the list displayed in the intellisense help
## Expected  behavior

It would be nice to get the method brackets because it would come up the parameter description straight away and would save some typing.
## Actual behavior

The method name autocompletes without the brackets

_Copied from original issue: OmniSharp/omnisharp-vscode#623_

**Comment by DustinCampbell** [comment]
We'll keep this on our backlog. Note that we'd likely only do this if we also made the same behavior change in Visual Studio and Xamarin Studio.

**Comment by CyrusNajmabadi** [comment]
I believe Sam added a feature for this you can choose to use: 
![image](https://user-images.githubusercontent.com/4564579/217337123-4a1d08cb-bfd6-4315-b79c-d6f902d0703c.png)

**Comment by sharwell** [comment]
Duplicate of #35187
