### ISSUE TITLE
Rename tracking border shown in .cshtml files even though you can't trigger the light bulb

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#17017]
**Version Used**: d15rel 26206.00

**Steps to Reproduce**:

1. Create a new project with .cshtml files, and add `@foreach (var x in Enumerable.Range(0, 1)) { }
`
2.  Type over the variable x.

**Expected Behavior**: You don't see rename tracking active.

**Actual Behavior**: Rename tracking is active, but you just can't trigger the light bulb

This can be fixed either by disabling the tracking or enabling the light bulb.

**Comment by CyrusNajmabadi** [comment]
Closing out as this would be owned by razor.
