### ISSUE TITLE
Give feedback that we're downloading from NuGet when users enable "Suggest usings for types in NuGet"

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#17013]
There should be some visual indication that there is a delay between the time you enable this feature to when you can actually use it. Perhaps take advantage of a task center?

People try to use this feature immediately after turning it on and then they think it doesn't work. If we don't use a task center, we could try having some sort of pop-up when people trigger Quick Actions in this instance to say "still downloading from NuGet"...

**Comment by CyrusNajmabadi** [comment]
We can potentially use the [BackgroundTaskManager](https://devdiv.visualstudio.com/DevDiv/_git/BackgroundTaskManager) here.

**Comment by CyrusNajmabadi** [comment]
Note.  BTM isn't available in the product yet.  So i can't target it.
