### ISSUE TITLE
 warning CS7035: The specified version string does not conform to the recommended format - major.minor.build.revision

### ISSUE THREAD

**Issue by JBaltika** [dotnet/roslyn#17024]
Hi,
Can anybody explain why AssemblyFileVersion must be four digits for build and revision? Why 
major.minor.yyyyMM.ddHHmm  format is invalid? I am not talking about AssemblyVersion. Why? In academia world or imaginary world, maybe  two four meanness digits  is just fine. However, in complex agile enterprise world when organization has 400+ VS projects building on daily bases almost, some kind of the datetime format is only choice for sanity and keep track. More over, its the only choice to build on VSTS & local machine complex solutions and have compatible upgrades . Just food for thought ...

[assembly: AssemblyVersion("4.0.0.0")]
[assembly: AssemblyFileVersion("4.3.201702.80525")]

4 - is product version, 3 is agile sprint version and date format

**Comment by tmat** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/aa381058(v=vs.85).aspx

**Comment by Ekus** [comment]
I believe @tmat is referring to the "four 16-bit integers" bit: "The version consists of two 32-bit integers, defined by four 16-bit integers" which is a lower-level Windows file format limitation it seems. I'm surprised  that while it supports the 1.0.19365.1 format today (2019, day 365), it does not allow 1.0.**66001**.1 so we are going to have a minor Y2K66 problem in the future. More comments: https://blogs.msdn.microsoft.com/msbuild/2007/01/03/fixing-invalid-version-number-problems-with-the-assemblyinfotask/  (I'm gonna try the Major.Minor.YYMM.DDBuildNumber approach)

**Comment by CollinAlpert** [comment]
Azure DevOps' Artifacts can somehow work around this limitation. I created a NuGet package with the version 202208.23.1 yesterday and I'd really like to know why the hell this works.

**Comment by LosManos** [comment]
I stumbled upon
```
warning CS7035: The specified version string '1.0.65536.0' does not conform to the recommended format
```
today.
65536 does not fit in 16 bits.
