### ISSUE TITLE
Collection initializer should use return value of the Add method

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#17030]
**Version Used**: VS2015U3

**Steps to Reproduce**:

```cs
class X : IEnumerable
{
  public X Add(int item) => new X { 1, 2, 3 };
  // ...
}
```
**Expected Behavior**:
```cs
public X Add(int item) => new X().Add(1).Add(2).Add(3);
```
**Actual Behavior**:
```cs
public X Add(int item) { var t = new X(); t.Add(1); t.Add(2); t.Add(3); return t; }
```

**Comment by svick** [comment]
While I understand how this would be useful for types like immutable collections, it would also be a breaking change. For example, consider `HashSet<T>`, whose `Add()` returns a `bool`:

With the proposed change, code like `new HashSet<int> { 1, 2 }`, which works as expected now, would fail to compile.

**Comment by alrz** [comment]
@svick I should have mentioned that "if the return type has an applicable `Add` method".

**Comment by HaloFour** [comment]
Even in that case it would change the semantics of existing code, thus it's pretty much a non-starter.

**Comment by alrz** [comment]
That was my "expected behavior" though :smile: I suppose those down votes are saying "don't break C#".
