### ISSUE TITLE
.editorconfig settings being ignored in some refactorings

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#17042]
The following places look like they're touching solution options when they should be using document options:

- src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
- src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider
- src/Features/CSharp/Portable/UseExpressionBody/AbstractUseExpressionBodyCodeFixProvider.cs

FYI to @kuhlenh and @Pilchie

Also reported in https://developercommunity.visualstudio.com/content/problem/24588/useexpressionbodyformethodscodefixprovider-faillin.html

**Comment by Pilchie** [comment]
The ones in `src/Features/CSharp/Portable/UseExpressionBody/AbstractUseExpressionBodyCodeFixProvider.cs` are fixed by https://github.com/dotnet/roslyn/pull/17046

**Comment by Pilchie** [comment]
I'm working on the other two now.

**Comment by jasonmalinowski** [comment]
Reactivating as I'm guessing @Pilchie wants to use this to track a 15.1 port.

**Comment by Pilchie** [comment]
Sadly, I don't think this will meet a 15.1 bar.
