### ISSUE TITLE
Is it possible to configure a project in MSBUILD or VS to treat messages like IDE0028 as compile time errors?

### ISSUE THREAD

**Issue by digeff** [dotnet/roslyn#17051]
Is it possible to configure a project in MSBUILD or VS to treat messages like IDE0028 as compile time errors?

**Comment by Pilchie** [comment]
You can configure VS to do so, either in Tools\Options\Text Editor\C#\Code Style\General, or through a `.editorconfig` file for your project.

This currently doesn't apply to command-line/CI builds, but that's on our roadmap to support.

@kuhlenh or @jmarolf do you have a pointer to the editorconfig documentation handy?

**Comment by kuhlenh** [comment]
Yes, here is the [editorconfig documentation](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference).

**Comment by nphmuller** [comment]
@Pilchie Is there a link so we can track when the CLI/CI support is implemented?
