### ISSUE TITLE
Strange debugger stepping in code that has pattern matching.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#17076]

**Comment by CyrusNajmabadi** [comment]
![repro](https://cloud.githubusercontent.com/assets/4564579/22809746/4036c9cc-eee9-11e6-81b6-1816bd3d12ed.gif)

**Comment by CyrusNajmabadi** [comment]
Note that stepping over the second 'is TInvocation invocation'  Instead of jumping to the 'node = node.parent' statement, it sets the IP at teh 'return' statement (incorrectly).

**Comment by CyrusNajmabadi** [comment]
Tagging @gafter @jcouv

**Comment by jcouv** [comment]
This looks much like the issue I recently fixed: https://github.com/dotnet/roslyn/pull/16803
That issue was with 'if' statements in async methods, and the symptom was that even when the condition is false, the statement inside the body of the condition gets apparently stepped into (although never actually executed).
Your repro above seems to match.

Would you mind trying again with a post-dev15 build?

**Comment by jcouv** [comment]
@CyrusNajmabadi If you let me know the test and method to repro, I can verify. But I'm pretty confident this is fixed in master branch. 
I'll close.

**Comment by CyrusNajmabadi** [comment]
This is in AbstractAddParameterCodeFixProvider.  The code runs when you do something like"

"new MyType(too, many, arguments, supplied)".

**Comment by CyrusNajmabadi** [comment]
You'd be able to try this out by running the AddParameterTests tests.

**Comment by jcouv** [comment]
The problem still repro'es. I'll test again with PR #18844.

**Comment by jcouv** [comment]
The issue still repros in recent preview bits :-(
```
Version 15.3.0 Preview 1.0 [26526.1.d15rel]
VisualStudio.15.IntPreview/15.3.0-pre.1.0+26526.1.d15rel
```

**Comment by jcouv** [comment]
The IL generated and sequence points seem correct. See https://github.com/jcouv/roslyn/commit/9dae4b2a26d1e9c80bbd73139397f48ea32e5bc4

I'll talk to Tomas to confirm if he thinks this is a JIT/debugger issue.

**Comment by jcouv** [comment]
Pushing to 15.6 due to bug bar.

**Comment by jcouv** [comment]
My simplified repro (https://github.com/jcouv/roslyn/commit/9dae4b2a26d1e9c80bbd73139397f48ea32e5bc4) no longer seems to show the issue in VS, but the test Cyrus pointed out still repros. Not sure what happened.
I'll have to resume search for a simple repro.

**Comment by jcouv** [comment]
I think it would be good for a fresh pair of eyes to take a look at this.

**Comment by gafter** [comment]
@CyrusNajmabadi I don't have a repro for this issue.  The offending code no longer exists in `AbstractAddParameterCodeFixProvider`.  I tried a reduced repro from the code appearing in your pic, but the bug does not repro (see below).  Can you please either put together a repro or close this?

```csharp
using System.Threading.Tasks;

internal class Program
{
    private static void Main(string[] args)
    {
        M(new Node()).GetAwaiter().GetResult();
    }

    static async Task M(Node node)
    {
        while (node != null)
        {
            if (node is A a)
            {
                await Task.Yield();
                return;
            }
            else if (node is B b)
            {
                await Task.Yield();
                return;
            }

            node = node.Parent;
        }
    }
}

class Node
{
    public Node Parent = null;
}
class A : Node { }
class B : Node { }
```

**Comment by CyrusNajmabadi** [comment]
Closing out as i haven't seen this again.  Likely been fixed by now.  Thanks for looking!

**Comment by gafter** [comment]
A test to prevent regression was added in https://github.com/dotnet/roslyn/pull/42824
