### ISSUE TITLE
Pressing tab on navigation window should auto-complete

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#17075]
If user presses `ctrl+,` and starts typing an item name to navigate to, a list is populated as the user types with all possible entries. User can scroll up/down with up/down keys.
Similar to how other controls possibly behave (example: browser address bar), it would be great if while navigating up/down, the main text box is changed with the entry item.

**Example use case:**

1. I want to navigate to `CSharpCompilationOptions` in the code base.
2. I start typing `csharpcom` and presented with the hundreds of types in the Roslyn code base that map to that.
3. I press down to hover over `CSharpCompilation` type that appears in the list.
4. The value `CSharpCompilation` is now available in the text box.
5. I type `o` to have the value `CSharpCompilationo` in the text box.
6. Now the list contains `CSharpCompilationOptions` as the first suggestion.
7. I press enter to navigate to that type/file.

**Result:**

User reaches the navigation item with fewer key strokes.

![image](https://cloud.githubusercontent.com/assets/15987992/22806957/7ae270d6-eed9-11e6-9be5-10765209d078.png)

**Comment by Pilchie** [comment]
Please file on VSPlatform.

**Comment by OmarTawfik** [comment]
@Pilchie can you please mention the repo?

**Comment by Pilchie** [comment]
Devdiv.visualstudio.com
