### ISSUE TITLE
Generate Constructor defaults to fields and not auto-props

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#17087]
I have this constructor already: 

```C#
public class User
    {
        public string Username { get; set; }
        public int Age { get; set; }
        public double Weight { get; set; }
        public double Height { get; set; }
        public int MHR { get; }
        public double BMR { get; }
        public Gender Gender { get; set; }
        public List<Workout> Workouts { get; set; }

        public User(string username, int age, double weight, double height, Gender gender)
        {
            Username = username;
            Age = age;
            Weight = weight;
            Height = height;
            MHR = 220 - age;
            BMR = BasalMetabolicRate();
            Gender = gender;
        }
}
```

I add a new property `public int Id { get; set; }` and **Ctrl+.** to generate a new constructor to include this new prop `_user = new User(1, "kaseyu", 25, 150, 71, Gender.Female);`:

![image](https://cloud.githubusercontent.com/assets/1402694/22836290/9f0ca002-ef70-11e6-81e3-16be234ab681.png)

Why is it making a new constructor with a bunch of new fields, when I have a bunch of properties already?

**Comment by CyrusNajmabadi** [comment]
How would we know what properties to hook up your parameters to?  There are no names or anything else to figure it out.

**Comment by kuhlenh** [comment]
@CyrusNajmabadi you are brilliant! I am sure you will come up with something 😄

**Comment by CyrusNajmabadi** [comment]
Seriously though. I'm not sure what you're asking for.  Can you explain how you think this should be working?  Thanks :-)

**Comment by kuhlenh** [comment]
All I did was add a parameter to an object instance that already existed. I wanted the IDE to know that all I did was add a parameter and to then generate a constructor using the new parameter and my existing properties...not just make a whole new set of fields.

**Comment by jmarolf** [comment]
I would just match based on indentifier and type.  In C#, if there is a property name `Age` of type `int` and I pass in `int age`  to the constructor it would make send to do `this.Age = age`.  Obviously once this pattern is violated we would cease offering the more specific refactoring

**Comment by CyrusNajmabadi** [comment]
Kasey, how did you want us to map those random parameters (like 71) to a property?

Are you saying you just want an add-parameter feature?  Or that you want a smarter constructor generated?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of customer feedback on this.
