### ISSUE TITLE
[C# feature request] define operator **

### ISSUE THREAD

**Issue by chaitanyapotti** [dotnet/roslyn#17098]
Hello all,
I would like to propose the functionality to add an extra operator ** 

Usage : x**y = Math.Pow(x,y)

This usage is common with other languages (Python) and is unambiguous.

Why: While typing formulae in our applications, using Math.Pow() multiple times, makes the expression long and less readable. This implementation solves that problem.

Note: Also, I've read other posts where people had qualms about operator overloading. But, I feel this can be taken up.

Thanks 
Chaitanya

**Comment by alrz** [comment]
#4594

**Comment by gafter** [comment]
Roslyn is the repo for the implementation. The language is now designed over at https://github.com/dotnet/csharplang
