### ISSUE TITLE
Sprint 111-113 Summary

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#17096]
# Note:
These last 3 sprints have essentially been: 
![image](https://cloud.githubusercontent.com/assets/9797472/21243307/21ac5cc6-c2cd-11e6-828a-c6e1d51ae68c.png)
But we've recently had time to come up for air so I will attempt to summarize the work of the last 1.5 months.

# Sprint 111-113 Stats

|  Repository | Bugs Closed| Pull Requests Merged |
|:-------------:|:-------------:|:-------------:|
| [Roslyn](https://github.com/dotnet/roslyn) | [608](https://github.com/dotnet/roslyn/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20closed%3A%222016-12-11%20..%202017-02-10%22%20) | [545](https://github.com/dotnet/roslyn/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20closed%3A%222016-12-11%20..%202017-02-10%22%20)
| [F#](https://github.com/microsoft/visualfsharp)| [199](https://github.com/microsoft/visualfsharp/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20closed%3A%222016-12-11%20..%202017-02-10%22%20) | [228](https://github.com/microsoft/visualfsharp/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20closed%3A%222016-12-11%20..%202017-02-10%22%20)
| [Project System](https://github.com/dotnet/roslyn-project-system) | [348](https://github.com/dotnet/roslyn-project-system/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20closed%3A%222016-12-11%20..%202017-02-10%22%20) | [198](https://github.com/dotnet/roslyn-project-system/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20closed%3A%222016-12-11%20..%202017-02-10%22%20)
| [.NET CLI](https://github.com/dotnet/cli) | [553](https://github.com/dotnet/cli/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20closed%3A%222016-12-11%20..%202017-02-10%22%20) | [228](https://github.com/microsoft/visualfsharp/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20closed%3A%222016-12-11%20..%202017-02-10%22%20) |
| [.NET SDK](https://github.com/dotnet/sdk) | [187](https://github.com/dotnet/sdk/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20closed%3A%222016-12-11%20..%202017-02-10%22%20) | [144](https://github.com/dotnet/sdk/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20closed%3A%222016-12-11%20..%202017-02-10%22%20) |
| [Omnisharp](https://github.com/OmniSharp/omnisharp-roslyn) | [14](https://github.com/OmniSharp/omnisharp-roslyn/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20closed%3A%222016-12-11%20..%202017-02-10%22%20) | [35](https://github.com/OmniSharp/omnisharp-roslyn/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20closed%3A%222016-12-11%20..%202017-02-10%22%20) |
| **Total** | **1909** | **1378** |
 
# VB/C# Compiler Team Accomplishments
- Implemented 
	- RTM bug fixes
	- discards
	- while-loop out-var scope changes
- Testing 
- Dogfooding 
   - Compiler features
   - VS 2017 in general 
   - Found a number of bugs we’ll address post Release-to-Web
- Triaging incoming Visual Studio feedback and reported crashes
- Post RTM design work
  - Readonly ref proposal on csharplang
  - Infrastructure and planning for point releases 

# F# Team Accomplishments
![image](https://cloud.githubusercontent.com/assets/9797472/22848381/d4afcd28-efa8-11e6-9b7a-84bd1fc99684.png)
- Shipped the bits to VS 2017 RC4
- Improvements to internal builds infrastructure
- Announced our immediate 2017 roadmap

# Interactive Execution Team Accomplishments
- New Live-Unit-Testing functionality
	- Pause/Resume
	- Exclude single tests
- Testing
- Dogfooding, ourselves (any repo and solution we can get our hands on) and helping partner teams dogfood ( VSO repo, VS repo, Windows and Office)
- Fixing RTM issues 

# Project & Analysis Team Accomplishments
- New Project System Features
	- Transitive P2Ps
	- Package page
	- Publish page
- Bug fixes
- More bug fixes
- Dogfooding

# .NET CLI Team
- CLI 1.0 Features
	- Migrate xproj/project.json to msbuild with `dotnet migrate`!!!!
		- Works even on large complex projects
	- Project creation with new templates `dotnet new console`
		- New templating engine 
	- Create a new solution file `dotnet new sln`
	- Add projects to a solution `dotnet sln add`
	- Add new nuget package dependency with `dotnet add package`
	- Add new project reference with `dotnet add reference`

# IDE Team Accomplishments

- Releases
	- .editorconfig support for naming styles
	- Bug fixing and testing
		- A bunch of long-standing Watsons and important fixes to new features
	- Delivered a Dev14 hotfix for some customer impacting issues

- Post-RTW
	- Refactoring: Convert if to switch ([contributed](https://github.com/dotnet/roslyn/pull/16277) by @alrz)
	- Refactoring: Change base or add digit separators to numeric literals ([contributed](https://github.com/dotnet/roslyn/pull/16664) by @alrz)
	- ~20 other bug fixes
# Omnisharp
- Shipped 1.7 release!
	- New TextMate grammar for syntax highlighting
	- Support for latest .NET Core .csproj projects
	- NuGet package restore for .csproj projects
	- Several improvements to Code Actions

**Comment by vbcodec** [comment]
will VS RTM be available to download before ship / release date ?

**Comment by vbcodec** [comment]
what reall means "Infrastructure and planning for point releases" ?
Releasing of compilers independent from VS ? (similar to Typescript)

**Comment by jmarolf** [comment]
@vbcodec every feature checked into the master branch made it into the latest public RC.  Features checked into post-dev15 will likely not be in the initial version of Visual Studio 2017.  Regarding point releases, its unclear exactly what we are going to do (we are still planning after all), but I believe that the LDM wants release independence like typescript.  Frankly, this is something we will want feedback on regarding the right release cadence.

**Comment by alrz** [comment]
#6543 and #16664 are not tbe same thing though. :)

**Comment by chrisaut** [comment]
@alrz wrong thread?

**Comment by alrz** [comment]
No, linked PR for the second refactoring in post-rtw doesn't seem to be correct.

**Comment by jmarolf** [comment]
@alrz whoops sorry, I updated the summary (though I appreciate @Giftednewt 's contribution as well 😄  )

**Comment by Giftednewt** [comment]
@jmarolf Always glad to contribute 😄
