### ISSUE TITLE
Array constructor currently falls under the csharp_style_var_elsewhere category.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#17109]
If you have an  `.editorconfig` file configured with the following:
```ini
[*.cs]
csharp_style_var_for_built_in_types = true:error
csharp_style_var_when_type_is_apparent = true:error
csharp_style_var_elsewhere = false:error
```

Then, the following statement causes `IDE0008: Use explicit type instead of 'var'`:
```C#
var a = new int[3];
```

Repro Solution: [ClassLibrary.zip](https://github.com/dotnet/roslyn/files/772064/ClassLibrary.zip)

**Comment by tannergooding** [comment]
FYI. @jmarolf

**Comment by tannergooding** [comment]
Also FYI. @dotnet/roslyn-ide

**Comment by balajikris** [comment]
I think you want to start looking here: [IsTypeApparentInDeclaration](https://github.com/dotnet/roslyn/blob/a0a0ca19d7c941cd46d0ce72b60efb63bd076e88/src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.State.cs#L75)

**Comment by sharwell** [comment]
There are two cases of particular interest to me:

### Array of built-in type

```csharp
var array = new int[3];
```

💭 It seems like users would consider this a built-in type.

### Array of other type

```csharp
var array = new Exception[3];
```

💭 It seems like users would consider this an *apparent* type.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  And our code explicitly checks for:

![Image](https://github.com/user-attachments/assets/b58208bf-d8a1-4bca-9d45-6424c9ea60b5)
