### ISSUE TITLE
`is constant` pattern-matching operation fails to convert constant to type of left-hand-side

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#17103]
I know it's way too late, but maybe somebody can explain why this `is` constant pattern:
```c#
bool Is42(byte b) => b is 42;
```
Works not the same way as similar `switch` statement:
```c#
bool Is42(byte b) {
    switch (b) {
        case 42: return true;
        default: return false;
    }
}
```

`switch` statement performs implicit conversion of literal expressions under `case` labels to *"govering-type"* (`byte` in the example above), while `is` expression just uses "nominal"/"default" type of literal expression and in fact first method never returns `true`.

cc @gafter

**Comment by gafter** [comment]
That question would better be asked in https://github.com/dotnet/csharplang .

**Comment by controlflow** [comment]
@gafter so you're confirming this is not a Roslyn bug, right?

**Comment by gafter** [comment]
This appears to be per spec.

**Comment by gafter** [comment]
Actually, [the spec](https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md) has a special accommodation for integral types that is not implemented. But that accommodation wouldn't work for a floating-point type.

**Comment by gafter** [comment]
@controlflow I could not reproduce this issue in the latest code base. This test passes:

``` c#
        [Fact]
        public void IsConstantPatternConversion_Positive()
        {
            var source =
@"using System;
public class Program
{
    public static void Main()
    {
        {
            byte b = 12;
            Console.WriteLine(b is 12); // True
            Console.WriteLine(b is 13); // False
        }
        bool Is42(byte b) => b is 42;
        Console.WriteLine(Is42(42));
        Console.WriteLine(Is42(43));
    }
}";
            var expectedOutput =
@"True
False
True
False";
            var compilation = CreateCompilationWithMscorlib45(source, options: TestOptions.DebugExe);
            compilation.VerifyDiagnostics(
                );
            var comp = CompileAndVerify(compilation, expectedOutput: expectedOutput);
        }
```

And similarly a new project in Visual Studio with that code behaves properly. I suspect you're using an older version of Visual Studio or Roslyn. Can you please verify?

**Comment by controlflow** [comment]
Argh, looks like I got confused by ILSpy's [decompiled C# code](http://tryroslyn.azurewebsites.net/#b:master/f:r/K4Zwlgdg5gBAygTxAFwKYFsDcAobAHYAIwBswBjGM4gQxBBgAUAnAeyievWwG9sZ+YBEuRgpqyEQDcWYACYwAstUgAKAJR8BvATpjbdBwgjQxCMALwwAjACYcBgwGEWEEC2KoAdAHUmYNAAykKgqZmD0tmqYMAD0MTAAKkzAqJoOAs6u7l6+/qhBECFhEQDMUbHxAGLUxCCp6QC+abrNOpluHj5+gcEqAJIgACw2KsNqUa0ZLh053fm9A8OjZRM6TTrNYhIUhCzuMIsjRiaEahYAfKYw4TDDOA1AA===) (cast to `byte` is missing before boxing the value) and wrote incorrect test in VS afterwards :|

Sorry for disturbance, everything works like expected.

**Comment by gafter** [comment]
I'll keep this issue open for the addition of a couple of tests in this area.
