### ISSUE TITLE
Supported nested yield sequences

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#17114]
Support automatic enumeration of sequences that appear after a "yield return" statement.

The following code is not valid C#

    class Program
    {
        static void Main(string[] args)
        {
        }

        private IEnumerable<int> Values
        {
            get
            {
                yield return 1;
                yield return 2;
                yield return 3;

                yield return Others;
            }
        }

        private IEnumerable<int> Others
        {
            get
            {
                yield return 4;
                yield return 5;
                yield return 6;
            }
        }
    }

To get the desired effect (the effect intended by the above) we must write the property 'Values'  like this:

        private IEnumerable<int> Values
        {
            get
            {
                yield return 1;
                yield return 2;
                yield return 3;

                foreach (var e in Others)
                    yield return e;
            }
        }

Allowing us to code it as in the first example above would seem to be a natural way of expressing this.

The basic rule could be that if the expression following yield return is of the same type as the return type of the enclosing property/method then translate this to an automatic enumeration of the expression's elements.

This is supported in F# using yield! as opposed to yield (in a sequence expression) and would be a very welcome improvement to C#.

**Comment by YaakovDavis** [comment]
What about the following case?

```
class C<T> : IEnumerable<T>, IEnumerable<IEnumerable<T>>
{
   ...
}

class D
{
   C c = new C();
   IEnumerable<C> Values => yield return c;
}
```

Should `Values` return `c`, or iterate it?
In F# it's unambiguous due to the special `yield!` syntax. If C# is to support such "digging", it should have a special syntax as well. 

Suggestion:
```yield enumerate c;```

**Comment by Korporal** [comment]
That did vaguely cross my mind, but in this case the property (Values) specifies a return type IEnumerable<int> not IEnumerable<IEnumerable<int>>.

So I guess in the general case if the expression following yield return is a T return the T as is done today, else enumerate (so far as necessary) and return the individual Ts.

So if e is IEnumerable<T> enumerate these with a compiler generated foreach loop, but if e is IEnumerable<IEnumerable<T>> then enumerate these with two compiler generated foreach loops.

The method/property return type dictates what is to be returned.

**Comment by YaakovDavis** [comment]
I noticed that I had an error in the code (forgot the generic arg); fixed.
See the updated example.

**Comment by Korporal** [comment]
Let me show this to better make my case:

        private IEnumerable<int> Values
        {
            get
            {
                yield return 1;
                yield return 2;
                yield return 3;

                foreach (var e in Others)
                    yield return e;

                return Others;
            }
        }

This is illegal C# currently despite the fact that we're trying to return from Values something with identical type as Values' return type.

However, if there were no "yield return" statements then the (ordinary) return is legal.

**Comment by YaakovDavis** [comment]
I forgot the generic arg in my example above, please check the updated example.
It's not about a standalone `return` (which isn't allowed even today IIRC, once you use `yield`). The `yield return` itself is ambiguous in my case.

**Comment by Korporal** [comment]
I'm not seeing the ambiguity (not saying there isn't one - just not seeing it). Can you post more representative C#?

**Comment by HaloFour** [comment]
Proposals and discussions regarding the C# language are moving to the following repo:

https://github.com/dotnet/csharplang
