### ISSUE TITLE
[Proposal] Convert VB Unit Tests to Multiline String Literals.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#17124]
Now the VB.net supports multi-line string literals, the usage of XML Literals can be lessened.
The conversion will have to be carefully done as the XML-Literal are white case sensitive as well as indentation aware, they also include escaped characters. 
There is a potential gain in test performance and memory usage.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler I'm not marking this as up-for-grabs as I'm not confident we would want to take the time to review a submission without evidence of real gains.

**Comment by AdamSpeight2008** [comment]
Could we at put it on a separate branch to attract `Up-For-Grabs` contributors? as it is big task.
Once it done, and there is evidence of gains merge back into the main repo?

**Comment by gafter** [comment]
@AdamSpeight2008 You can make as many forks of the Roslyn repo as you want, and makes branches in there all you want. Evidence of real gains would not prompt us to merge it into the main repo. It would raise the issue to the level of us being willing to consider whether or not we would want to review it. And if we were willing to review it, then the outcome of that review would determine whether or not we'd merge it back into the main repo.
