### ISSUE TITLE
Inlining ref returns scenario needs to be enabled through IDE

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#17132]
Inlining Code Action need to be implemented for ref returns.
See below code, #12838, and #17053.
The test `WithRefInitializer1` was implemented in https://github.com/dotnet/roslyn/commit/c7349324e98e5a9dbc38b9c8a89f09b41d3c2012 to make sure a fixer doesn't appear for ref returns until the feature is properly implemented/tested.

```csharp
class C
{
    ref int M()
    {
        int[] arr = new[] { 1, 2, 3 };
        ref int x = ref arr[2];
        return ref x;
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Closing out given lack of feedback on this.
