### ISSUE TITLE
"Find All References" misses results

### ISSUE THREAD

**Issue by jods4** [dotnet/roslyn#17139]
On VS 2017 RC, Feb 7th update.

I have the following `public const string DealGroupValidated` in a partial class. As you can see in the screen shot, it _is_ used in one place.

![image](https://cloud.githubusercontent.com/assets/3832820/22931906/b949d08a-f2c6-11e6-8aee-d3875098e80e.png)

Yet, when I perform a _Find All References_ on this field, it comes up empty.
![image](https://cloud.githubusercontent.com/assets/3832820/22931941/db9d2d6c-f2c6-11e6-8a14-a31fe82baaa9.png)

This is an ASP.NET Core project migrated to `.csproj`, if it makes any difference. Lightweight solution loading is turned off.

**Comment by CyrusNajmabadi** [comment]
Can you provide a repro project?

**Comment by jods4** [comment]
@CyrusNajmabadi not easily. It's a large private solution :(

I don't know what triggers the bug but this is as well as I can describe it:
- ASP.NET Core project (csproj);
- Lightweight solution loading disabled;
- A `public static partial class` that spans many files, each with...
- one large `public const string` verbatim string (`@"...."`).
- It's used from other classes in the same project, by simple reference `MailTemplates.Xyz`.
- Class references do list all the sites where it's used.
- But _Find all references_ on the const itself brings up no result.

**Comment by CyrusNajmabadi** [comment]
Sorry, i can't repro this with that sort of approach.  Were you able to follow those instructions and get a repro for this?  If so, can you link to that project?

**Comment by jods4** [comment]
@CyrusNajmabadi I just spent 15 minutes trying to create a repro with no success.
Worse, I tried it today in my solution and it works.

As you can see on the screenshots, it did not work 3 days ago. 
But I have no idea what triggered this situation.

Any idea?

**Comment by CyrusNajmabadi** [comment]
No.  I'm not sure what would be going on here.  If you're able to provide a repro project, please let me know!
