### ISSUE TITLE
Code fix for CS0428 does not fix the error.

### ISSUE THREAD

**Issue by josefpihrt** [dotnet/roslyn#17141]
**Version Used**: Visual Studio 2017 RC 15.0.0-RC3+26127.0

**Code to Reproduce**:
```csharp
using System.Linq;

namespace My
{
    public static class Foo
    {
        public static void Bar()
        {
            var arr = new object[] { null };

            int i = arr.Count; // "Change 'Count' to 'LongCount'."
        }
    }
}
```

* The code fix is erroneous so it should not be suggested.
* Or it should suggest "Change 'Count' to 'Length'".

**Comment by Pilchie** [comment]
This is the "Spell check" fix which just looks for similar identifiers.  However, we should consider a specific fix for CS0428 to add the parentheses.  And we should also consider a specific analyzer/fixer that suggests moving from `Count()` to `Length` if it exists.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
