### ISSUE TITLE
Type system HOLE: ref returns are not considered as invariant during variance checking

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#17140]
**Version Used**: 

Master branch @ February 14

**Steps to Reproduce**:

Compile the following code:
```c#
delegate ref T RefFunc<out T>();
interface I<out T> { ref T RefMethod(); }

class C : I<string> {
  string _field;
  public ref string RefMethod() => ref _field;
    
  public void M() {
    I<string> ofString = new C();
    I<object> ofObject = ofString;
    ofObject.RefMethod() = new object(); // BOOM!
      
    RefFunc<object> func = new RefFunc<string>(this.RefMethod);
    func() = new object(); // BOOM!
  }
}
```

**Expected Behavior**:

Compiler error, similar to CS1961 in the example below:
```c#
interface I<in T> {
  // error CS1961: Invalid variance: The type parameter 'T' must be invariantly
  // valid on 'I<T>.RefMethod(ref T)'. 'T' is contravariant.
  void RefMethod(ref T refParameter);
}
```

**Actual Behavior**:

Code compiles without a single error, program crashes at runtime:
> System.TypeLoadException: 'Could not load type 'I`1' from assembly 'ConsoleApp13, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because a covariant or contravariant type parameter was used illegally in the signature for the result type in method 'RefMethod'.'

**Comment by gafter** [comment]
This kind of bug makes me even more fearful of the bugs we're not detecting because we're not testing using a verifier on the results of compiling programs that contain ref returns.

**Comment by VSadov** [comment]
Good catch!! 
It appears we are missing tests for variance with ref returns.

```C#
// should be an error
delegate ref T RefFunc<out T>();

// should be an error
interface I<out T> { ref T RefMethod(); }
```

**Comment by controlflow** [comment]
"Using verifier"? `PEVerify` was updated to allow more managed reference manipulations/returns to handle C# ref-returns usage patterns?

**Comment by gafter** [comment]
@controlflow No, that is part of the problem.
