### ISSUE TITLE
C# Interactive doesn't work with tuple syntax.

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/roslyn#17157]
**Version Used**: 
Microsoft Visual Studio Enterprise 2017 RC 15.9.9-RC4+26206.0
Microsoft (R) Visual C# Interactive Compiler version 2.0.0.61404

**Steps to Reproduce**:

* Microsoft Visual Studio Enterprise 2017 RC 15.9.9-RC4+26206.0
1. Open the **C# Interactive** window.
2. Enter `(1,2)`

* Microsoft (R) Visual C# Interactive Compiler version 2.0.0.61404
1. Run `csi.exe`
2. Enter `(1,2)`

**Expected Behavior**:
Outputs `[(1, 2)]`

**Actual Behavior**:

* Microsoft Visual Studio Enterprise 2017 RC 15.9.9-RC4+26206.0
    (1,13): error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported

* Microsoft (R) Visual C# Interactive Compiler version 2.0.0.61404
    (1,1): error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported
    (1,1): error CS0029: Cannot implicitly convert type '(string, int)' to 'object'

**Workaround**

* Microsoft Visual Studio Enterprise 2017 RC 15.9.9-RC4+26206.0

Remove

    /r:System.ValueTuple.dll

From

    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\InteractiveComponents\CSharpInteractive.rsp

* Microsoft (R) Visual C# Interactive Compiler version 2.0.0.61404

Remove

    /r:System.ValueTuple.dll

From

    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\csi.rsp

**Comment by tmat** [comment]
The important piece of information here is that the machine has a pre-release version of .NET Framework 4.7

**Comment by paulomorgado** [comment]
Or, if you think as a customer, the customer installed VS2017 and tuples don't work on interactive environments.

Isn't .NET Framework 4.7 a requirement of VS2017? I sure didn't explicitly install it.

**Comment by tmat** [comment]
It is not. Windows Insider update would install it.

**Comment by paulomorgado** [comment]
OK!

I've noticed that, although the interactive uses the mscorlib ValueTuple, in projects (.NET Framework or .NET Core), the System.ValueTuple package is required.

**Comment by jcouv** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/17192 (this let the EE and Interactive handle the duplicate ValueTuple type and pick the one from the app instead of the one from mscorlib).
I expect the fix to make it into 15.3 (summer timeframe, based on my understanding).

There will also be a follow-up to have GAC type unification, so the compiler workaround isn't needed (targeting desktop 4.7.1 framework).

**Comment by jcouv** [comment]
Yes. At this point RTM has a very high bar for accepting fixes (crashes and such). So this fix didn't make it into RTM. Sorry about that.

**Comment by paulomorgado** [comment]
At least, make that noticeable in the release notes and release a script to fix .rsp files.

**Comment by thomaslevesque** [comment]
I just hit the same issue. @paulomorgado's fix doesn't seem to work for me, I still get the same error.

**Comment by paulomorgado** [comment]
Run this:

    Get-ChildItem -LiteralPath 'C:\Program Files (x86)\Microsoft Visual Studio\' -Filter '*.rsp' -Recurse | Select-String -SimpleMatch '/r:System.ValueTuple.dll'

You'll see which rsp files have the reference.

**Comment by thomaslevesque** [comment]
Thanks @paulomorgado, that was it. I had a csi.rsp in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\csi.rsp`

**Comment by paulomorgado** [comment]
Beware of any VS updates. I think it will "repair" that.
