### ISSUE TITLE
Unresolvable conflict not indicated when renaming identifier.

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#17177]
**Version Used**: Visual Studio 2017 RC 15.0.0-RC4+26206.0

**Code to Reproduce**:

![rename](https://cloud.githubusercontent.com/assets/11931318/23029827/0f633c94-f46c-11e6-8d97-62c90c85f141.png)

**Comment by sharwell** [comment]
@sys27 I found some additional cases where this occurs. I'm not sure if you want to fix them now or have me file separate issues.

**Pattern matching switch case:**

```csharp
switch (3)
{
case int a:
  int b = a; // rename b to a
  break;
}
```

**Pattern matching `if`:**

```csharp
if (3 is int a)
{
    int b; // rename b to a
}
```

**Exception filters:**

```csharp
try
{
}
catch (Exception e) when (e is InvalidCastException f) // rename e to f
{
}
```

**Out variables:**

```csharp
if (int.TryParse("", out int result))
{
    int x; // rename x to result
}
```

**Pattern matching inside interpolated string:**

```csharp
string value = $"{3 is int x}";
int y = x; // rename y to x
```

**Parameters of a local function:**

```csharp
void Method()
{
  void LocalFunction(int x)
  {
  }

  int y; // rename y to x
}
```

**Comment by Pilchie** [comment]
@sharwell can you help @sys27 get through the Jenkins issues with #18740?

**Comment by sharwell** [comment]
@Pilchie @sys27 Done and merged!
