### ISSUE TITLE
Ellipsis is showing even if a diagnostic is suppressed with #pragma

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#17181]
**Version Used**: Visual Studio 2017 RC 15.0.0-RC4+26206.0

**Code to Reproduce**:

![ellipsis](https://cloud.githubusercontent.com/assets/11931318/23032740/c6976738-f475-11e6-82f9-740f1bf1d19f.png)

**Comment by Pilchie** [comment]
I think this is the same as https://github.com/dotnet/roslyn/issues/12213 (but with a different type of tag)
