### ISSUE TITLE
IDE0016 is suggested in places where it changes the semantics of the code

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#17185]
Example:
```C#
using System;

public class Class1
{
    private string _x;
    private string _y;

    public Class1(string x, string y)
    {
        if (x == null)
        {
            throw new ArgumentNullException(nameof(x));
        }

        if (y == null)
        {
            throw new ArgumentNullException(nameof(y));
        }

        _x = x;
        _y = y;
    }
}
```

In the above code, IDE0016 (Null check can be simplified) is suggested for both throw statements.

This would transform the code into the following:

```C#
using System;

public class Class1
{
    private string _x;
    private string _y;

    public Class1(string x, string y)
    {
        _x = x ?? throw new ArgumentNullException(nameof(x));
        _y = y ?? throw new ArgumentNullException(nameof(y));
    }
}
```

In the case where `x` is not null, but `y` is, the semantics of the code has changed, because now `_x` will be assigned before the `ArgumentNullException` has been thrown for `_y`.

**Comment by Pilchie** [comment]
Why does that matter?  The constructor still throws, so there is no resulting object.

**Comment by tannergooding** [comment]
@Pilchie, this also repros for methods.

**Comment by CyrusNajmabadi** [comment]
Many of our code-actions may change semantics.  That's why it's a suggestion.  It's saying "hey... i notice you could do this.  Do it if you think it makes sense for you".

**Comment by tannergooding** [comment]
@CyrusNajmabadi, I understand that, but I think we could also make this better by not breaking semantics where possible 😄 (especially in cases where we let the user turn errors on for some of these suggestions).

**Comment by CyrusNajmabadi** [comment]
The problem with that is that then makes things so restricted that we basically are hugely limited in terms of how and when we offer this sort of feature.  Effectively anything in the language that could change state (which is a LOT of things) would cause the feature to be disabled.  I'd much rather just say that this was a feature that we would not allow you to change into a warning/error.  

It's really just a style-suggestion.  Not really something where you'd tell someone you must use this pattern, or else your code is in error.

**Comment by tannergooding** [comment]
The following is a valid transformation and is still pretty common.

```C#
if (x == null)
{
    throw new ArgumentNullException(nameof(x));
}

_x = x;
```

While the following is also common and is distinctly known to change the semantics and therefore should not be supported.

```C#
if (x == null)
{
    throw new ArgumentNullException(nameof(x));
}

// Some code before the assignment where x is not accessed or used

_x = x;
```

I don't think the restricting the second scenario from being suggested will make this transformation uncommon or unusable at all.

**Comment by CyrusNajmabadi** [comment]
It will make it much more restricted.  For example, if you have:

```c#
if (x == null)
{
    throw new ArgumentNullException(nameof(x));
}

if (y == null)
{
    throw new ArgumentNullException(nameof(y));
}

_x = x;
_y = y;
```

Now the feature can't even be offered.  Even if it's something that the user would want.  And it's definitely the case that there's lots of code that looks like that.

Again, the feature is simply a suggestion, stating that we can transform this code if *you* want it transformed.  It's up to you to decide if this is what you want or not.

**Comment by Pilchie** [comment]
Yeah, I'm not inclined to stop offering this in this case.

**Comment by jlennox** [comment]
An example of how IDE0016 can introduce a breaking change:

```
public class ReturnedClass
{
    public IDisposable Disposable { get; set; }
    public object AnotherValue { get; set; }
}

private static ReturnedClass Ide0016Issues(object someOtherValue)
{
    var retunedclass = new ReturnedClass();

    if (someOtherValue == null)
    {
        throw new ArgumentNullException();
    }

    retunedclass.Disposable = File.OpenWrite("hello");
    retunedclass.AnotherValue = someOtherValue;

    return retunedclass;
}
```

IDE0016 suggests changing it to:
```
private static ReturnedClass Ide0016Issues(object someOtherValue)
{
    var retunedclass = new ReturnedClass();

    retunedclass.Disposable = File.OpenWrite("hello");
    retunedclass.AnotherValue = someOtherValue ?? throw new ArgumentNullException();

    return retunedclass;
}
```

Which now causes the FileStream to be created but not disposed.

**Comment by seiffs** [comment]
> It will make it much more restricted. For example, if you have:
> 
> ```cs
> if (x == null)
> {
>     throw new ArgumentNullException(nameof(x));
> }
> 
> if (y == null)
> {
>     throw new ArgumentNullException(nameof(y));
> }
> 
> _x = x;
> _y = y;
> ```
> 
> Now the feature can't even be offered. Even if it's something that the user would want. And it's definitely the case that there's lots of code that looks like that.
> 
> Again, the feature is simply a suggestion, stating that we can transform this code if _you_ want it transformed. It's up to you to decide if this is what you want or not.

IMHO such suggestion should be offered only in constructor, not in methods. In a method the value of x changes the state of the object and then if y is null exception is thrown. I think people believe that the suggested quick actions are safe (I just rejected such breaking change in a code review). And because the code in this case seems old and could be automatically modernized they apply quick action without thinking so the yellow bulb would stops anoying them - and in this case it clearly changes the functionality of the code. I'd definitelly vote for more restrictions for IDE0016.
