### ISSUE TITLE
Light bulb no longer works in Interactive Window

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#17189]
Repro:
1) Open C# Interactive Window
2) Type

```C#
> #r "System.Xml.Linq"
> XElement
```

3) Press ```Ctrl+.```. 

Expected result:
Light bulb suggesting to add ```using System.Xml.Linq```.

Actual result:
Nothing happens.

**Comment by tmat** [comment]
This is a regression.

**Comment by Pilchie** [comment]
The lightbulb has only worked in the first submission forever.

**Comment by tmat** [comment]
You are right. I forgot. I need to fix that.

**Comment by nawfalhasan** [comment]
Is this fixed? Can I use it in VS 2015?

**Comment by tmat** [comment]
Seems fixed in 16.5.
