### ISSUE TITLE
IErrorReportingService needs to be cleaned up

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#17203]
in this PR - https://github.com/dotnet/roslyn/pull/17174

I added ability to show infobar in VS main window. and some people believe IDE should always use that which is different behavior than what we have now.

looks like we have some clean up to do on the service.

options are

1. leave things as it is.
2. make everyone to use VS main window
3. make service to accept view to show the infobar explicitly.

**Comment by heejaechang** [comment]
tagging @jmarolf for FYI

**Comment by Pilchie** [comment]
@jasonmalinowski - you had thoughts about how you wanted this cleaned up.

**Comment by jasonmalinowski** [comment]
I don't remember what this was.
