### ISSUE TITLE
IDE0032 should not be specified for classes or structs with an explicit `StructLayout` attribute

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#17201]
**Repro**
1. Create a new C# Class Library
2. Set the contents of Class1.cs to the following
```C#
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 8)]
public struct MyStruct
{
    private int _x;
    private int _y;

    public int X
    {
        get
        {
            return _x;
        }

        set
        {
            _x = value;
        }
    }

    public int Y
    {
        get
        {
            return _y;
        }

        set
        {
            _y = value;
        }
    }
}
```
3. Note that IDE0032 (Use auto property) is suggested for both `_x` and `_y`.

**Expected Behavior**
IDE0032 should not be suggested for structs or classes that have the `StructLayout` attribute.

**Comment by CyrusNajmabadi** [comment]
Again, it's a suggestion :)   For example, it would be perfectly reasonable to write: 

```c#
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 8)]
public struct MyStruct
{
    public int X { get; set; }

    public int Y { get; set; }
}
```

This would have the same IL/semantics.  The purpose of many IDE features is to help you efficiently transform your code so that you don't have to do all the work yourself.

**Comment by tannergooding** [comment]
Again, I realize these are suggestions :). I am just indicating ways that I think the diagnostics could be improved.

And yes, converting both is reasonable (assuming that the compiler emits the backing fields in the order the properties are listed in the type). Converting only some of them is not, as it changes the layout of the struct.

Some of the suggestions users will want to enforce as code styles (and some of them are currently possible to enforce as code styles), so places where the suggestion is incorrect should probably get fixed at some point (even if those go 'Up for grabs').

**Comment by 0xd4d** [comment]
I agree that this should be fixed. Some users would want to use this fix on the whole project or solution. Most people don't check the diff before pressing OK, they assume it works. Applying this fix to the above code could break the code, something that will perhaps only be detected at runtime. This is similar to #15018 (fixed by #15023) , it breaks code, and it was fixed.

**Comment by stephenmartindale** [comment]
This is related, but I'm really not sure where to ask. Is there some way to disable `IDE0032`? It's a preference of code style and there seems to be no option in Visual Studio to turn this one off - it isn't in the code-style property pages.

**Comment by Pilchie** [comment]
Unfortunately, no, that one isn't configurable right now, though I agree that it should be.

**Comment by Pilchie** [comment]
I think the right thing here would be to add a warning annotation when we detect a `StructLayout`.

**Comment by logiclrd** [comment]
When a type is involved in serialization, the names of the fields are important, and changing fields to auto properties will break serialization. It in an anti-pattern to use auto properties with a serialized class, as there is no documented guarantee that the underlying fields will have the same names from one version of the dev tools to another, and the exact names are an internal implementation detail. I second requests for this setting to be configurable, and it would also be nice if it could be disabled regionally with a `#pragma`, in the same manner as `#pragma warning disable/restore 12345`.

**Comment by logiclrd** [comment]
One possible work-around if you have a project with many developers, some of whom might not recognize the implications of blindly applying these suggestions: Create a dummy `Attribute` and apply it to the fields. A field with an attribute is no longer eligible for the IDE0032 suggestion.
```
class ExplicitAttribute : Attribute { }

[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 8)]
public struct MyStruct
{
    [Explicit] private int _x;
    [Explicit] private int _y;

    public int X
    {
        get
        {
            return _x;
        }

        set
        {
            _x = value;
        }
    }

    public int Y
    {
        get
        {
            return _y;
        }

        set
        {
            _y = value;
        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Not repro.
