### ISSUE TITLE
VisualStudioSetup or VisualStudioSetup.Next don't deploy ExpressionEvaluator or Interactive

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#17214]
Repro
1. Set VisualStudioSetup.Next as startup project
2. Hit F5
3. In the new instance of VS start debugging something (to load EE)
4. In the new instance of VS, open the interactive window
5. In the initial instance of VS check the loaded modules

You will notice that all the CodeAnalysis modules were loaded from the RoslynDev hive folder (ie. correctly), except for the ExpressionEvaluator and Interactive modules (those were still loaded from the non-hive folder).

For EE, the workaround indicated by Chuck was to build the "ExpressionEvaluatorPackage" project (under ExpressionEvaluator/Setup) before F5. That indeed fixed the problem.
So I suspect there is a missing dependency between Setup or Setup.Next and ExpressionEvaluatorPackage project.

I suspect something similar is missing for Interactive.

Modules loaded when exercising the EE:
![image](https://cloud.githubusercontent.com/assets/12466233/23078739/ca92b318-f4fe-11e6-8d87-65d68715a3f1.png)

Modules loaded when exercising Interactive:
![image](https://cloud.githubusercontent.com/assets/12466233/23089118/0794ba06-f539-11e6-8675-f9e9d198b503.png)

FYI @tmat

**Comment by jcouv** [comment]
FYI @cston

**Comment by tmat** [comment]
We should merge all Roslyn VSIXes except for .Next into a single one. No reason to have multiple of them.

**Comment by jcouv** [comment]
I agree they should be merged. Tanner did mention this is a subtle change though. The best as I understood: VSIX projects also produce a binary which have a name or identity and RPS detects when those change.

**Comment by Neme12** [comment]
@jcouv It looks like they are all merged now into the `RoslynDeployment` project which is now also set as the startup project by default. Do you think this issue can be closed?

**Comment by jcouv** [comment]
Yup. Let's close. Thanks
