### ISSUE TITLE
The setting for Enter key behavior does not show a default selection

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#17236]
This is the case both in C# and VB.
Once the user makes a selection, it behaves as intended, from what I can tell.

![image](https://cloud.githubusercontent.com/assets/12466233/23090040/fd241a20-f548-11e6-9a34-6a5ee5f7337c.png)

FYI @CyrusNajmabadi

**Comment by Pilchie** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/14597
