### ISSUE TITLE
Returning results from functions could be made easier

### ISSUE THREAD

**Issue by michaelcheers** [dotnet/roslyn#17238]
I find myself writing
```csharp
return result;
```
a lot. So, I think there should be a new feature which lets a variable be a result.
```csharp
static auto Fibonacci (int upTo) //auto is a tuple of all "returning" values, so (int result).
{
    returning int result = 1;
    int lastNum = 0;
    for (int n = 0; n < upTo; n++)
    {
         int oldResult = result;
         result += lastNum;
         lastNum = oldResult;
    }
} 
```
So, because we put returning, it returns it at the end of the function. Also, so if you have to return something somewhere else: you could use
```csharp
return;
```
So, `return;` would return the "returning" values.

**Comment by eyalsk** [comment]
@michaelcheers You may want to post this at the new C# language design [repo](https://github.com/dotnet/csharplang) and close/delete this one.

**Comment by michaelcheers** [comment]
@eyalsk, OK.
