### ISSUE TITLE
Completion listbox isn't shown after typing `?? throw new `

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#17256]
**Version Used**: VS2017RC.4

**Steps to Reproduce**:

1. Add code

```C#
using System;
namespace N {
	class Program {
		static void Main(string[] args) {
			var a = args ?? throw 
		}
	}
}
```

2. Add `new ` (space after new) after `throw`

**Expected Behavior**:

Completion listbox pops up

**Actual Behavior**:

Nothing happens.

**Comment by jcouv** [comment]
Thanks @0xd4d for reporting this issue. Fixed with #19828.
The fix will ship in Visual Studio 2017 version 15.3. I'm not completely sure about various previews, but my guess is this will first show up in preview 3.
