### ISSUE TITLE
Expression bodied constructor line doesn't get auto formatted on semicolon

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#17257]
**Version Used**: VS2017RC.4

**Steps to Reproduce**:

1. Add code

```C#
namespace N {
	class Program {
		int field;
		public Program()=>field=1
		static void Main(string[] args) {
		}
	}
}
```

2. Add a semicolon after `public Program()=>field=1`

**Expected Behavior**:

The line gets formatted

**Actual Behavior**:

The line doesn't get formatted.

**Comment by gafter** [comment]
Operators, constructors, and destructors don't work properly.
