### ISSUE TITLE
Extension methods named as properties kill intellisense

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#17258]
**Version Used**: 2.0.0.61413

**Steps to Reproduce**:
```C#
class Test
{
    public List<int> List;
}

static void Main(string[] args)
{
    List<Test> list = new List<Test>();

    for (int i = 0; i < 4; i++)
        list.RemoveAll(t => t.List.Count < |);
}
```

**Expected Behavior**: `i` to be offered for autocompletion

**Actual Behavior**: `i` is missing in the list. The parameters info tooltip shows `IEnumerable<int>.Count()`.

**Comment by gafter** [comment]
Because you've typed `<`, you are now entering type parameters for the generic extension method `Count`.

**Comment by miloush** [comment]
Hmm I see... that's a bit ambiguous indeed. In that case the list should contain items from both options I guess?

**Comment by Pilchie** [comment]
VB does some merging of lists in similar cases, but we don't in C# that I know of. Perhaps we should consider it.

**Comment by CyrusNajmabadi** [comment]
It's in the list for me:

![image](https://user-images.githubusercontent.com/4564579/217338379-2701e92b-d4bb-4b19-a871-0b024bcbb522.png)

**Comment by miloush** [comment]
@sharwell just out of curiosity, why are the years old issues that have been apparently fixed being closed as not planned?

**Comment by sharwell** [comment]
![image](https://user-images.githubusercontent.com/1408396/217387110-6c8f2d5d-5554-499a-a478-d48a9017fe6e.png)
