### ISSUE TITLE
Integration Test Failure

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#17255]
A recent commit has introduced a failing unittest.
[Failure](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/162/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpInteractive/ForStatement/)
which is causing unrelated Pull Requests to fail.

**Comment by jcouv** [comment]
This is fairly old. I assume it was fixed already. Please re-open if that's not the case.
