### ISSUE TITLE
Source server links in PDBs don't work due to line ending difference

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#17268]
The links in Roslyn PDBs point to https://raw.githubusercontent.com, which serves source files as they are stored in git. The build server checks out files with Windows line endings however. 
As a result the compiler calculated SHAs differ from what debugger calculates for the content dowloaded from https://raw.githubusercontent.com.

**Comment by jasonmalinowski** [comment]
The debugger is going to support updating line endings when resolving, so we won't have to do anything here.
