### ISSUE TITLE
Analyzer (SyntaxNodeAction) not being called for all parts of partial method

### ISSUE THREAD

**Issue by siegfriedpammer** [dotnet/roslyn#17273]
**Version Used**:
Visual Studio: `15.0.0-RC.4+26206.0 (Community)`
.NET: `4.6.01586`
Roslyn: `2.0.0-rc4` nugets

**Steps to Reproduce**:

1. Create the following analyzer:

		[DiagnosticAnalyzer(LanguageNames.CSharp)]
		public class MyAnalyzer: DiagnosticAnalyzer
		{
			static readonly DiagnosticDescriptor descriptor = ...;

			public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(descriptor);

			public override void Initialize(AnalysisContext context)
			{
				context.EnableConcurrentExecution();
				context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
				context.RegisterSyntaxNodeAction(
					AnalyzeMethod,
					new SyntaxKind[] { SyntaxKind.MethodDeclaration }
				);
			}

			static void AnalyzeMethod(SyntaxNodeAnalysisContext nodeContext)
			{
				// should be called for all MethodDeclarations
			}
		}

2. Use the following code to test:

        partial class Test
        {
            partial void FooBar(int bar); // gets called for this, OK!
        }

        partial class Test
        {
            partial void FooBar(int foo) // never gets called for this!
            {
            }
        }

**Expected Behavior**:

`AnalyzeMethod` should be called for both occurrences of `FooBar`.

**Actual Behavior**:

Only the first occurrence is reported to the analyzer.

**Comment by mavasani** [comment]
Assigning to @heejaechang, who is already working on a fix.

**Comment by jinujoseph** [comment]
@heejaechang is this done ?

**Comment by heejaechang** [comment]
yep. done long time ago.
