### ISSUE TITLE
Relax unicode constraints

### ISSUE THREAD

**Issue by generateui** [dotnet/roslyn#17279]
Obviously, copying APL like
```
Table.Posn←TABL{⍺∘+¨0,⍨¨(⊃SEPN)×i0⍴⍵}¨Table
```
may not be exactly an improvement over the current situation. However, I can see value in using unicode characters as variable names `var Δ = value1 - something` or `var ∑ = prices.Sum()`. 

Currently, some symbols are valid C#, such as `ε`. 

Proposal: identify usefull unicode symbols and allow them to be used in C# symbol names such as class names, variable names and method names.

**Comment by svick** [comment]
[The C# spec says](https://github.com/dotnet/csharplang/blob/6027ad5a4ab013f4fb42f5edd2d667d649fe1bd8/spec/lexical-structure.md#identifiers):

> The rules for identifiers given in this section correspond exactly to those recommended by the Unicode Standard Annex 31, except that underscore is allowed as an initial character (as is traditional in the C programming language), Unicode escape sequences are permitted in identifiers, and the "@" character is allowed as a prefix to enable keywords to be used as identifiers.

I think that (mostly) following the Unicode standard is the right approach.

The actual rules are that any Unicode characters that are letters are allowed in identifiers. This means that this code is valid C#:

```c#
var Δ = value1 - something;
var Σ = prices.Sum();
```

Notice that I used U+03A3 GREEK CAPITAL LETTER SIGMA. Your snippet used the similar looking U+2211 N-ARY SUMMATION, which is not a letter (it's a math symbol, just like `+`), so using that is not valid.

**Comment by miloush** [comment]
@generateui could you give couple of "useful Unicode symbols" you would like to use as symbol names?

While I am all for Unicode support the current rules seem quite reasonable to me (at least in the context you are discussing). I would definitely keep the math operators unavailable for the case if custom operators would be introduced in the future.

Also note that fixing #13474 will extend the valid identifier names to the math letter ranges (1D400-1D7CB).

**Comment by gafter** [comment]
The definition of what an identifier is in C# is mostly taken from the recommendations of the Unicode specification (with the exception of the handling of `_`). We do not want to duplicate the work of that group, and result in something that varies from their intent.
