### ISSUE TITLE
Question: Is there a way to override isEnabledByDefault: false in Unit Tests?

### ISSUE THREAD

**Issue by siegfriedpammer** [dotnet/roslyn#17271]
In our unit testing base classes we use the following to initalize the environment:

            var syntaxTree = parseTextFunc(text.ToString());

            Compilation compilation = createCompilationFunc(new[] { syntaxTree });
            var diagnostics = new List<Diagnostic>();

            var compilationWithAnalyzers = compilation.WithAnalyzers(ImmutableArray<DiagnosticAnalyzer>.Empty.Add(new T()));
            var result = compilationWithAnalyzers.GetAnalyzerDiagnosticsAsync().GetAwaiter().GetResult();
            diagnostics.AddRange(result);

But we are forced to declare all our analyzers `isEnabledByDefault: true` as they're not executed if declared `isEnabledByDefault: false`. Of course `#pragma warning disable ID` should still work inside the unit test.

**Question: Is there a way to override isEnabledByDefault: false in unit tests?**

**Comment by jnm2** [comment]
This question should have had some response from someone.

**Comment by sharwell** [comment]
The analyzer test library does this by default. If you can't use that library for your test purposes, you can use the same approach:

https://github.com/dotnet/roslyn-sdk/blob/2e8b8ef8a8133528f89010800d575a2f0403be74/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest%601.cs#L1164-L1171

**Comment by jnm2** [comment]
Cool, thank you! I looked through http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp/CSharpCompilationOptions.cs,8ccf5a200c09bbb7,references and couldn't find where Roslyn was doing it, but I missed [this overload](http://sourceroslyn.io/#Microsoft.CodeAnalysis/Compilation/CompilationOptions.cs,94821cf4d51c954c,references) of the base method.

**Comment by JohanLarsson** [comment]
This fix does not work in 4.5.0 https://github.com/dotnet/roslyn/issues/67204
