### ISSUE TITLE
Intellisense + Capital Letters

### ISSUE THREAD

**Issue by josefpihrt** [dotnet/roslyn#17275]
**Version Used**: Visual Studio 2017 RC 15.0.0-RC4+26206.0

![intellisense](https://cloud.githubusercontent.com/assets/11931318/23174998/5d6a29a2-f85e-11e6-9184-2a6f6d3b3ed5.png)

* Currently, when I type **CR**, a method with name **C...R...** is selected only if there is no method with name **Cr...**

* I would propose that if I type **CR** and there is a method with name **C...R...**, it should take precedence over a method with name **Cr...**

**Comment by Pilchie** [comment]
Tag @kuhlenh @CyrusNajmabadi @rchande @DustinCampbell 

How do people feel about changing match preferences in cases like this?

**Comment by CyrusNajmabadi** [comment]
Basically, an exact case-sensitive, CamelCase match would beat out case-insensitive other matches.  I think that's ok.  If the filter text contains capital letters, that's a strong signal this is what the usre wants.  I think we could safely take this.

**Comment by kuhlenh** [comment]
:+1: ran into this today...wanted to do ```DateTime.Now.AD``` to filter to ```AddDays()``` but it kept just preselecting ```Add()```. As long as we make it case-sensitive, this should be fine.

**Comment by DustinCampbell** [comment]
I"m also in favor of this. Sounds like a good tweak to me.

**Comment by JosefPihrt** [comment]
I realized that name can also start with two upper-case letters (interface name). So I would say that priority should go like this:

1. **AB...**
2. **A...B...**
3. **Ab...**

**Comment by miloush** [comment]
Also see #16053 for discussion and the current behavior. 

This is the same issue as `tn` case mentioned there. Not the `MF` case though.

**Comment by JosefPihrt** [comment]
I would propose to take camel-cased identifiers into consideration. This could improve developer
productivity when typing local variable name (or parameter name).

A simple rule could be applied:

1. **aB...**
2. **a...B...**

Current behavior:

![camelcase](https://cloud.githubusercontent.com/assets/11931318/23384824/c2dbf430-fd4c-11e6-83c9-634b1a12808d.png)

**Comment by 0xd4d** [comment]
How about this one, happens if you have added `using System.ComponentModel;` :

![completion](https://cloud.githubusercontent.com/assets/1060731/23488429/d6d9d08c-feec-11e6-8e95-27b8b677cba9.png)

`ArgumentNullException` is a better match, and also happens to be exactly what I wanted.

**Comment by bboyle1234** [comment]
PLEASE make intellisense case-aware. 
When I type `myV` it should select `myValue` instead of `MyValue`.
When I type `Myv` it should select `MyValue` instead of `myValue`. 

Here's the kicker: When a user bothers to use the shift key to capitalize a letter, they want the variable or member that HAS that letter capitalized.
I'd die of joy if you guys can make this happen. PLEASE.

**Comment by bboyle1234** [comment]
@rchande , I have no idea how I managed "unassign" you above ... hopefully you can fix that, sorry.
