### ISSUE TITLE
Symbols used to represent Local Function can spill their diagnostics into global declaration error bag

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#17293]
LocalFunctionAttributeOnTypeParameter test started failing due to this after order of binding of nodes by SemanticModel got changed. I commented the failing assert out, the test is not skipped.

**Comment by AlekseyTs** [comment]
I think https://github.com/dotnet/roslyn/pull/17014 is going to address this.

**Comment by agocke** [comment]
Fixed by #17014
