### ISSUE TITLE
Unexpected conflicts in renaming.

### ISSUE THREAD

**Issue by thorgeirk11** [dotnet/roslyn#1729]
When I rename any of the callbacks all the others get reported as an unresolvable conflict.
This only happens to variables/parameters of type Action/Func.

See the code below:
```csharp
void Foo(Action callback)
{
    callback();
}

void SomeFoo(Func<bool> callback)
{
    callback();
}

void OtherFoo()
{
    Action callback = () => { };
    callback();
}
```
![image](https://cloud.githubusercontent.com/assets/2693474/6940189/cc2ed472-d863-11e4-900f-e84e77e5a6f0.png)

I am using Visual Studio 2015 CTP 6

**Comment by dpoeschl** [comment]
[LocalVariableConflict](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Rename/CSharpRenameRewriterLanguageService.cs,b6e4e87d81321873) assumed that any unqualified invocation expression that matches the name of a local/parameter is a conflict, but this is not true in the case of locals/parameters of delegate types.

**Comment by dpoeschl** [comment]
@amcasey As the filer of one of the dupes of this, can you verify the fix?

**Comment by amcasey** [comment]
Checked that this repro now behaves correctly in both C# and VB.
