### ISSUE TITLE
[Proposal] Allow extension methods affect choice of type in method groups and formattable strings

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#173]
#### Problem
Let's say I have the following extension method:
```csharp
public Func<T2, TResult> Curry<T1, T2, TResult>(this Action<T1, T2, TResult> action, T1 arg) {}
```
and the following class method:
```csharp
public static int Add(int x1, int x2);
```

If I call this extension method as a normal method, it looks like this:
```csharp
Curry(Add, 5);
```

However as an extension method, it would look like this:
```csharp
((Action<int, int>)Add).Curry(5);
```

Another related problem is with interpolated strings -- since extension methods do not affect type choice, it is not possible to call `IFormattable` extension methods on `$""`.

#### Potential solution
I suggest allowing extension methods to influence the type choice for the method group.
Example:
```csharp
Add.Curry(5);
```

Similar logic should apply to `$""`.

##### Pros
1. Consistency between different call types
2. Reduced verbosity in functional scenarios (e.g. Select(Add.Curry(5)))
3. Allows extension methods on `FormattableString`

##### Cons
1. Resolution is pretty complex as it is, not sure if there are any edge cases that would complicate this further

**Comment by thomaslevesque** [comment]
I agree that it would be nice, but it would make it much harder to find candidate extension methods: since the expression doesn't have a type, it means that suddenly *all* extension methods in scope are candidates, and the compiler has to check all of them to find a compatible one.

---

On an unrelated note: your `Curry` method doesn't do currying, but partial application ;). A `Curry` would be more like this:
```
static Func<T1, Func<T2, TResult>> Curry<T1, T2, TResult>(Func<T1, T2, TResult> func)
{
    return x => y => func(x, y);
}
```
And could be used like this:

    var curriedAdd = Curry<int, int, int>(Add);
    var add1 = curriedAdd(1);
    int result = add1(2);

**Comment by ashmind** [comment]
> I agree that it would be nice, but it would make it much harder to find candidate extension methods: since the expression doesn't have a type, it means that suddenly all extension methods in scope are candidates, and the compiler has to check all of them to find a compatible one.

Why? Let's say you write `X(() => y)`, and you have a set of static imports. Wouldn't the resolution here be just as complex as in `(() => x).X()`?

**Comment by gafter** [comment]
W do not believe that this kind of change can be made without breaking compatibility - i.e. sometimes selecting a different overload under the revised rules or causing an ambiguity.
