### ISSUE TITLE
Proposal: Make brackets optional on empty bodied constructor overloads.

### ISSUE THREAD

**Issue by doktrova** [dotnet/roslyn#17306]
As the title states is it possible to make the brackets optional on constructors with no body.

For example

```
class Person {

string _name, _gender;
int _age;

public Person(string name, int age, string gender) {
_name = name;
_age = age;
_gender = gender;
}

//Instead of this
public Person(string name) : this(name, 0, "unknown") 
{
}

//Just this
public Person(string name) : this(name, 0, "unknown"); 
}
```

**Comment by AdamSpeight2008** [comment]
Proposals for C# language features are now being issued in [dotnet/csharplang](https://github.com/dotnet/csharplang)

**Comment by kingces95** [comment]
@doktrova Opened the same issue over at https://github.com/dotnet/csharplang/issues/860.

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
