### ISSUE TITLE
Always true conditions in SyntaxPath.cs

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#17300]
**Version Used**: master
**Steps to Reproduce**: 

1. [L73](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Utilities/SyntaxPath.cs#L73)
2. [L102](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Utilities/SyntaxPath.cs#L102)
3. [L116](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Utilities/SyntaxPath.cs#L116)

**What's always true**:
When the right side of the expression is evaluated, the left part is false, so `!_trackKinds` is false leading to `_trackKinds` being true. Thus, the right expression doesn't need the `_trackKinds && XXX` check but only the second part of it.

**Comment by Pilchie** [comment]
Want to take a look and clean this up some?

**Comment by Joe4evr** [comment]
Couldn't the whole expression for all those cases just be `if (_trackKinds && /*other condition*/)`?

**Comment by Evangelink** [comment]
Current:
`if (!_trackKinds || (_trackKinds && child.RawKind == kind))`

So I would say:
`if (!_trackKinds || child.RawKind == kind)`

So for all cases:
`if (!_trackKinds || /* other condition */)`

**Comment by CyrusNajmabadi** [comment]
@Evangelink Would like you to just submit a PR to fix this up?

**Comment by Evangelink** [comment]
Yep will do!

**Comment by Pilchie** [comment]
Fixed by #17323.
