### ISSUE TITLE
IDE won't load check-in policy, creates new registry node

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#17313]
Forgive me if this is the wrong place for this issue, but I'm really not sure where to file this one.

After creating a custom TFS Check-In Policy (referencing `Microsoft.TeamFoundationServer.ExtendedClient` from Nuget and implementing a subclass of `PolicyBase`) and adding the assembly location to the Windows Registry, Visual Studio doesn't read it's own configuration registry and creates a new one.

**Version Used**: 

Microsoft Visual Studio Enterprise 2015 Version 14.0.25431.01 Update 3

**Steps to Reproduce**:

1. Create a custom check-in policy
2. Add a new registry item: `HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0_Config\TeamFoundation\SourceControl\Checkin Policies\MyCheckinPolicy` with a `REG_SZ` value of `C:\Path\To\The\CheckinPolicy.dll` (edit name and path as appropriate).
3. Launch Visual Studio

**Expected Behavior**:

The new check-in policy shows up in the list at Team Explorer -> Settings -> Team Project -> Source Control -> Check-in Policy -> Add...

**Actual Behavior**:

The new check-in policy does not appear in that list.

When launching Visual Studio, it creates a new node `14.0_Config_27896`. The number at the end is seemingly random, does not correspond to a process ID, and is always evenly divisible by four so it's [probably a reference to some kind of Windows kernel handle](https://blogs.msdn.microsoft.com/oldnewthing/20050121-00/?p=36633/) such as a process ID.

![image](https://cloud.githubusercontent.com/assets/426009/23239977/a30f8aea-f9be-11e6-99a0-2a929d691342.png)

I don't know if this behaviour is related, however the new `14.0_Config_<num>` node does not contain my new check-in policy under `TeamFoundation\SourceControl\Checkin Policies`.

**Comment by Pilchie** [comment]
Please file on https://connect.microsoft.com.  Checkin Policies are unrelated to the Roslyn project.
