### ISSUE TITLE
Readonly Structs vs Classes have dangerous inconsistency - failed spin lock

### ISSUE THREAD

**Issue by Drawaes** [dotnet/roslyn#17310]
**Version Used**: Any

**Steps to Reproduce**:

1. Create private readonly Spinlock _lock;
2. take a lock

**Expected Behavior**:
That the code is protected by the lock... or the compiler throws an error

**Actual Behavior**:
struct is copied and lock is taken on the copy no compiler warning

This seems like it should either not compile or should work. Because the readonly struct is copied the lock never actually works

will do nothing, apparently this is a known issue, that is defended against only by comments?

https://github.com/dotnet/coreclr/search?l=C%23&q=mutable+readonly&type=Code&utf8=%E2%9C%93

**Comment by Drawaes** [comment]
Got caught by this again today, readonly GCHandles never show as deallocated when free is called for the same reason

**Comment by Drawaes** [comment]
https://gist.github.com/Drawaes/84704a1a8ce8eb9e3bca6ef364d8beb2

Simple example to repo the behavior

**Comment by CyrusNajmabadi** [comment]
Seems like an appropriate place for warning waves.

**Comment by Korporal** [comment]
The example you refer to does not use any kind of lock, am I missing something?

**Comment by benaadams** [comment]
@Korporal here's an example https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Buffers/ConfigurableArrayPool.cs#L169

**Comment by benaadams** [comment]
@Korporal here's an example https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Buffers/ConfigurableArrayPool.cs#L169

It won't give you a compile error or runtime error if you make it readonly; it just won't lock

**Comment by jcouv** [comment]
Notes from LDM https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-11-06.md#roslyn-17310

**Comment by jcouv** [comment]
Moving to IDE as suggestion for analyzer, since LDM concluded this should not be a compiler error.

**Comment by Drawaes** [comment]
Any news on this? I think @grabyourpitchforks had some ideas around this as well

**Comment by CyrusNajmabadi** [comment]
@mavasani Can this be moved to Roslyn-Analyzers?

**Comment by mavasani** [comment]
Tagging @stephentoub - I believe this is tracked by https://github.com/dotnet/roslyn-analyzers/issues/2811 and there is already a WIP PR for it: https://github.com/dotnet/roslyn-analyzers/pull/2831

**Comment by CyrusNajmabadi** [comment]
Great.  Closing out then.
