### ISSUE TITLE
TypeHelpers.IsMscorlib should also check for object type

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#17338]
From discussion https://github.com/dotnet/roslyn/pull/17192#pullrequestreview-23606064, two conditions are required to identify mscorlib: it should not reference other assemblies and it should contain the type `object`.

```C#
        private static bool IsMscorlib(this Assembly assembly)
        {
            return assembly.GetReferencedAssemblies().Length == 0;
        }
```

FYI @cston

**Comment by cston** [comment]
`IsMscorlib()` is not used and can be removed. The one reference in `IsMscorlibType()` is commented out and the comment to re-enable the check is probably unnecessary as well.

**Comment by jcouv** [comment]
The method was removed. Closing the issue.
