### ISSUE TITLE
Assertion fails in GetDiagnostics() on CodeAnalysis.Desktop.csproj 

### ISSUE THREAD

**Issue by scottcarr** [dotnet/roslyn#1733]
Hello,

I have a Roslyn-based tool I'd like to try running on Roslyn itself.  I'm trying to open the projects and get diagnostics like:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.MSBuild;


namespace MyCompiledRoslyn
{
  class Program
  {
    static void Main(string[] args)
    {
      var msbw = MSBuildWorkspace.Create();
      var sln = msbw.OpenSolutionAsync(@"C:\Users\carr27\Documents\GitHub\roslyn\src\RoslynLight.sln").Result;
      var proj = sln.Projects.First(p => p.Name == "CodeAnalysis.Desktop");
      Console.WriteLine(proj.FilePath);
      var cu = proj.GetCompilationAsync().Result;
      Console.WriteLine("got compilation");
      var d = cu.GetDiagnostics();
      Console.WriteLine("got diagnostics");
    }
  }
}
```

My issue is the above code works for me with rc1 (that I installed with NuGet) but not when I compile rosyln myself from the github master branch.  With the Roslyn I compiled,  I get this assertion failure:

![assert_fail](https://cloud.githubusercontent.com/assets/472477/6945264/7de01cce-d866-11e4-831b-5f6e7bef2172.PNG)

Could someone please check if this is reproducible?  There might be some problem with my build.  Thanks.

**Comment by scottcarr** [comment]
I guess the difference is the assertion is removed from the release build.  I verfied this by changing to my build of master to release.  The question is if that assert failing matters?

**Comment by AlekseyTs** [comment]
@VSadov Please verify.
