### ISSUE TITLE
Is it possible to build Roslyn  with VS 2017 RC?

### ISSUE THREAD

**Issue by npolyak** [dotnet/roslyn#17348]
This is not an issue, just a question.  

You do not provide instructions for building Roslyn under VS 2017 RC.

**Comment by eyalsk** [comment]
@npolyak The following [instructions](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md#getting-the-code) should cover this.

Did you try to build it? are you getting any errors?

**Comment by AdamSpeight2008** [comment]
@npolyak Yes, I'm currently using VS 2017 RC. 
An issue sometime occurs we changing branches, so sometime I delete the build folder and nuget folder. Then `restore.cmd`, `build` and then `build and test`. before opening in VS

**Comment by npolyak** [comment]
Answering eyalsk - I have not tried building it in VS2017 - the only reason I am not switching to it is because I was not sure if one can build Roslyn in it.

Thanks Adam. I assume I do not have to install Roslyn Insider extension for VS2017, right?

**Comment by eyalsk** [comment]
@npolyak Ahh.. okay, well, you should because you can build Roslyn on it.

No you don't need to install the extension.

**Comment by npolyak** [comment]
I would add a note on your GITHUB page about building with VS 2017 RC before closing this issue.
