### ISSUE TITLE
`this` keyword is not shown in intellisense in expression-bodied get/set

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#17341]
**Version Used**: d15rel/26220.01

**Steps to Reproduce**:

1. Create a simple class:
```C#
public class Test 
{
    private bool testField;
}
```
2. Create a property:
```C#
public bool TestProperty
{
    get => // type this.testField here
}
```

**Expected Behavior**: Intellisense shows the `this` keyword when in the getter expression body.

**Actual Behavior**: `this` keyword is not shown. It is shown correctly if you have a fully expression-bodied property, such as `public bool TestProperty => this.testField;`.

**Comment by 333fred** [comment]
@Pilchie.

**Comment by Pilchie** [comment]
`base` is also missing.  Should probably do a pass through the keyword recommenders and see what makes sense to offer there that might be missing.

**Comment by Pilchie** [comment]
Can't repro anymore.
