### ISSUE TITLE
IDE: incorrect renaming behavior for parameter of local function

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#17355]
**Version Used**: 
VS 2017 RC4 26206.0
**Steps to Reproduce**:

1. Example code:
```C#
public class A
{
    void M()
    {
        int M2(int x) => x + 1;
    }
}
```
2. Press Ctrl+R, Ctrl+R on the 2 positions of `x`.

**Expected Behavior**:
`x` can be renamed.
**Actual Behavior**:
`x` in parameter: alert "Can't rename this item."
`x` in expression body: can rename, but claiming conflict.

**Comment by CyrusNajmabadi** [comment]
Tagging @agocke

**Comment by CyrusNajmabadi** [comment]
Note: this fails even with a normal block-body for local functions.  
Note: FindRefs fails on the local-function parameter, but succeeds on a reference within the local function parameter.  
Note: the same issue occurs for type parameters of the local function.

This is surprising that this was missed.  Rename/FAR are part of the test matrix for IDE features.

Tagigng @dotnet/roslyn-ide

**Comment by Pilchie** [comment]
Can you see if the FAR failure is a semantic model API issue and move to the compiler if so?

**Comment by AlekseyTs** [comment]
Could be fixed by https://github.com/dotnet/roslyn/pull/16789.

**Comment by CyrusNajmabadi** [comment]
THe issue with parameters no longer reproes.  However, this still reproes for local-function type parameters.  Looking.

**Comment by CyrusNajmabadi** [comment]
The type parameters are an issue with teh compiler.  SemanticModel.GetDeclaredSymbol on a local-function's TypeParameters returns null.  

Tagging @agocke

**Comment by Pilchie** [comment]
Also reported here: https://developercommunity.visualstudio.com/content/problem/69397/error-while-trying-to-renema-variable-in-method-ne.html for parameters.

**Comment by huoyaoyuan** [comment]
Seems already fixed now. Closing.
