### ISSUE TITLE
Committing autocomplete for directives does not trigger indenting

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#17367]
**Version Used**: 2.0.0.61413

**Actual Behavior**:
1. At the very beginning of line, type `#region`. Note that as soon as you type `n` the directive is indented.
2. Now try again, but hit enter on the `#region` entry in the autocomplete list. Note that formatting is not triggered this time. Similar with `#endregion`.

**Expected Behavior**:
The two methods to be equivalent - both should indent.

**Comment by Pilchie** [comment]
I thought this was a dupe, but I couldn't find it with some looking.  @CyrusNajmabadi @rchande does it look familiar to you guys?

**Comment by CyrusNajmabadi** [comment]
I swear there was one assigned to me.  But i can't find it at all.

**Comment by Pilchie** [comment]
Also reported as https://developercommunity.visualstudio.com/content/problem/44032/intellisense-region-auto-indentation-not-working.html

**Comment by austinv900** [comment]
Same issue

**Comment by CyrusNajmabadi** [comment]
This is because the indent system looks for the actual key to be typed to be "n".  This is clearly broken and hte indent system should likely listen for tab/enter/completion-commands, shoudl call through to completion so that completion commits, and then should indent accordingly.

**Comment by CyrusNajmabadi** [comment]
PRs welcome.

**Comment by ggirard07** [comment]
I see that the milestone on this bug is for 16.0. Does this means it will not be fixed until Visual Studio vnext? This is really frustrating since VS 2017 when you have dozens of those to do per days!

**Comment by programatix** [comment]
Wow, version 2.0.0.61413 till 2.3.2.6201901 and it is still not fixed.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/21820

**Comment by CyrusNajmabadi** [comment]
@programatix PRs are always welcome/encouraged for issues that are "up for grabs".
