### ISSUE TITLE
'is' and 'as' keywords improperly recommended after decimal.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#1736]
### Repro

'$$' indicates cursor position.

``` C#
var x = $$0;
```

Type a period "."

### Result
`is` and `as` appear as recommended keywords.

### Expected
No recommended keywords.

**Comment by Pilchie** [comment]
Similar to internal TFS bug 863345.

**Comment by rchande** [comment]
There are similar issues in VB that we should fix at the same time.

**Comment by rchande** [comment]
Can you verify, @brettfo?
