### ISSUE TITLE
VS very slow when working in CodeAnalysis proj in Roslyn.sln

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#17373]
Version: build 26209.1 d15rel

Perf trace:

%internal_share%\mlangfs1\public\tomat\Bugs\17373

**Comment by Pilchie** [comment]
Can you take a look at the trace and see if you can identify what is up?

**Comment by rchande** [comment]
@tmat Were you using NavigateTo? This looks like another instance of the "bad typing lag in NavigateTo" bug that I've been investigating.

**Comment by rchande** [comment]
@tmat You also have something allocating lots of 
` Type Entry[Microsoft.Cci.ISignature,System.Collections.Generic.KeyValuePair`2[System.Reflection.Metadata.BlobHandle,System.Collections.Immutable.ImmutableArray`1[System.Byte]]][]
`
PerfView says those stacks are broken--do you know if you have any extensions installed that could have caused that?

**Comment by Pilchie** [comment]
Ping @tmat ?
