### ISSUE TITLE
Proposal: Default-or-Empty Coalesce operator "???"

### ISSUE THREAD

**Issue by richardtallent** [dotnet/roslyn#17378]
Rather than having to write this:

```C#
var bar = string.IsNullOrEmpty(foo) ? "baz" : foo;
```

It might be nice to do this instead:
```C#
var bar = foo ??? "baz";
```

The same idea could be used to coalesce value types if their default value is an invalid value:

```C#
// old and busted
var startDate = (oldSubscriptionEnd==DateTime.MinValue) ? DateTime.Today : oldSubscriptionEnd;
// new hotness
var startDate = oldSubscriptionEnd ??? DateTime.Today;
```

Coalescing a numeric type's default 0 value would also be possible, though there may be fewer use cases where a 0 value is invalid and should be overridden. But for strings especially, I think there's a strong case for streamlining replacing null and empty values.

**Comment by gafter** [comment]
Language feature proposals are now discussed in [dotnet/csharplang](https://github.com/dotnet/csharplang).
