### ISSUE TITLE
Autocompletion list misses params for indexers

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#17384]
**Version Used**: 2.0.0.61413

**Steps to Reproduce**:
```C#
class Program
{
    public int this[params|
}
```
**Expected Behavior**: `params` to be in the autocompletion list

**Actual Behavior**: Not there.

**Comment by CyrusNajmabadi** [comment]
If this is legal C# code, then PRs welcome.

**Comment by miloush** [comment]
Compiles and runs just fine.

**Comment by skosterin88** [comment]
Is "params" keyword allowed in the indexer definition? I thought that it is not.

**Comment by miloush** [comment]
I don't see a reason why it shouldn't, it's just a syntactic sugar for regular method. And I run into this in a real scenario.

By the way, C# 5.0 specification, 10.9 Indexers
> _indexer-declarator_:
>    _type_   this   [   _formal-parameter-list_   ]
> The _formal-parameter-list_ specifies the parameters of the indexer. The formal parameter list of an indexer corresponds to that of a method (§10.6.1), except that at least one parameter must be specified, and that the ref and out parameter modifiers are not permitted.

And §10.6.1 of course allows them

> _formal-parameter-list_:
> _fixed-parameters_
> _fixed-parameters_   ,   _parameter-array_
> _parameter-array_

Sounds explicitly allowed to me and could be breaking to forbid it at this moment.

**Comment by CyrusNajmabadi** [comment]
It should def be allowed.  PRs welcome.
