### ISSUE TITLE
VSSDK1081 occurs on ConvertToConditional sample

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#17399]
Occured in [this](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/436) run:

```
C:\Users\dotnet-bot\.nuget\packages\Microsoft.VSSDK.BuildTools\15.0.26124-RC3\tools\VSSDK\Microsoft.VsSDK.targets(680,5): error VSSDK1081: Problem occurred while extracting the vsix to the experimental extensions path. [D:\j\workspace\windows_relea---8a39a417\src\Samples\CSharp\ConvertToConditional\Impl\ConvertToConditionalCS.csproj]
```

**Comment by Pilchie** [comment]
@AlexEyler Looks like another case of the build targets running into problems in our CI runs.

**Comment by Pilchie** [comment]
Tagging @jaredpar, @jasonmalinowski, @tannergooding too.

**Comment by jaredpar** [comment]
Is there a need to deploy samples as a part of the CI runs?

**Comment by Pilchie** [comment]
Good point, and no, I don't think they should ever be deployed in CI runs.

**Comment by AlexEyler** [comment]
I have a bug on my plate to improve this error message (so it includes the exception message at least) - usually it comes as a result of a file being in use while we're trying to overwrite it via the Unzip method, but I'm not sure in this case.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #66](https://github.com/dotnet/roslyn-sdk/issues/66) via [**ZenHub**](https://www.zenhub.com/)
