### ISSUE TITLE
Analyzer 'System.Runtime.Analyzers.CSharpTestForEmptyStringsUsingStringLengthAnalyzer' threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by wdolek** [dotnet/roslyn#17418]
Getting Warning when building solution in Visual Studio (see below). 

No such warning listed when running:
`msbuild /p:RunCodeAnalysis=true`

I couldn't figure out how to grab whole stack trace, error message points only to project and not to exact file where analyzer fails.

**Version Used**: 
- `System.Runtime.Analyzers` `1.1.0`
- Visual Studio 2015, Update 3

**Steps to Reproduce**:

0. <having bigger C# solution, some quite oldish technologies, such as WCF etc.>
1. Install NuGet package `System.Runtime.Analyzers` `1.1.0` to all projects
2. Enable code analysis in project settings
3. Build solution

**Expected Behavior**:
1. Zero or more warnings/errors (depends on settings)
2. No exception thrown within analyzer

**Actual Behavior**:
1. Zero or more warnings/errors (depends on settings)
2. Warning AD0001 `Analyzer 'System.Runtime.Analyzers.CSharpTestForEmptyStringsUsingStringLengthAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. <Project name>  <Project dir path>\CSC`  1

**Comment by Pilchie** [comment]
I think this should probably be over at https://github.com/dotnet/roslyn-analyzers.
