### ISSUE TITLE
c# conditional operator without else

### ISSUE THREAD

**Issue by NiklasRaab** [dotnet/roslyn#17416]
Please provide support for conditional operator without an else. For example:

`string returnValue = someBool ? "this is a return value"`

At the moment you have to write: 
`string returnValue = someBool ? "this is a return value" : string.Empty`

It would be small but nice 👍

**Comment by eyalsk** [comment]
@NiklasRaab You should propose language features at the [CSharpLang](https://github.com/dotnet/csharplang/issues) repo.

**Comment by NiklasRaab** [comment]
Sorry, i will close this. Thank you!
