### ISSUE TITLE
Workspaces should never parse command line options, but call into Compiler API

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#17423]
Example: [CompilationOptionsConversion](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Utilities/CompilationOptionsConversion.cs)
Used in: [CSharpProjectShim](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.cs#L259)

All such uses in the project shim should be replaced by calling into the compiler API.
The compiler API should also expose these to the IDE/Workspaces.

/cc @jaredpar @jasonmalinowski

**Comment by jasonmalinowski** [comment]
@OmarTawfik You implied you're already working on this as a part of some other work you're working on?

**Comment by OmarTawfik** [comment]
I'm doing a small fix there in `features/readonly-ref` branch.
I believe this issue for tracking the larger work item, which might require API changes, as the compiler command line parser might not expose the appropriate methods yet.

**Comment by jasonmalinowski** [comment]
Closing as we're revisiting much of this as part of a larger piece of work being tracked. This bug doesn't really add much to the value.
