### ISSUE TITLE
Annoying auto-completion when typing local function with generic return

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#17426]
Try typing `IEnumerable<T> Local<T>() { }`.
You will end up with `IEnumerable<TaiwanCalendar>` instead.

FYI @agocke @CyrusNajmabadi

**Comment by jcouv** [comment]
Related scenario. After declaring the local function, try typing some code before the local function. For example:
```C#
            AssertEx.SetEqual(); // when you type this, AssertEx.S$$ will not complete properly
            
            IEnumerable<LanguageVersion> Versions()
            {
                foreach (LanguageVersion version in Enum.GetValues(typeof(LanguageVersion)))
                {
                    yield return version;
                }
            }
```

**Comment by gafter** [comment]
I'm not sure how this can be fixed, since there is no way to know it is a local function when `T` is being typed. @CyrusNajmabadi what do you think we should do about this?
/cc @agocke

**Comment by CyrusNajmabadi** [comment]
We solved this for regular methods by just putting "T" in the completion list when it could be the return type of a method.  We'll likely have to do the same for local functions.

**Comment by Pilchie** [comment]
I think the problem here is that with no modifiers, we don't know that this is a local function, so this would mean showing it in any statement context?

**Comment by CyrusNajmabadi** [comment]
i think it's not really a problem.  We can just see if this is a location where we could be in the return type of a local function, and we add "T", just like we add T when typing in a location that looks like it could be the return type of a method.

It's a heuristic, but it's served us well so far.

**Comment by Pilchie** [comment]
Agreed. I was just pointing out that "location where we could be in the return type of a local function" is basically all statement contexts.

**Comment by CyrusNajmabadi** [comment]
Yup.  Long live "T"! May its reign be everlasting!

**Comment by CyrusNajmabadi** [comment]
This works now:

![image](https://user-images.githubusercontent.com/4564579/198739494-49eae844-c65b-468e-bc53-7a4ed1627f91.png)
