### ISSUE TITLE
Code Structure - Extend behavior to other structure components like paranthesis

### ISSUE THREAD

**Issue by sujaysarma** [dotnet/roslyn#17441]
I love the way VS automatically draws lines between the open and close { curly braces } in the c# editor. Can you get it to do exactly the same thing for ( parenthesis ) as well ? When function calls have a number of parameters or you are anonymizing and nesting calls, things start to get really messy even 2 levels deep. The dotted line thing that the IDE does would be great to have.

@CyrusNajmabadi -- Filing this as per our email discussion.

/cc: @CyrusNajmabadi, @Pilchie, @jaredpar

**Comment by AdamSpeight2008** [comment]
I think there a couple of extensions on the VSGallery that do rainbow braces.

**Comment by sujaysarma** [comment]
@AdamSpeight2008 The idea is that the IDE does this natively. Also, see my note above. The item was filed after discussion with the team.

**Comment by CyrusNajmabadi** [comment]
Closing out as rainbow braces was added for this use case.
