### ISSUE TITLE
Compiler crash when compiling element access to by-reference local array

### ISSUE THREAD

**Issue by akarpov89** [dotnet/roslyn#17453]
**Version Used**: 
Master branch @ February 14

**Steps to Reproduce**:
Compile the following code:

```csharp
using System;

public class C 
{            
    public void F()
    {
        ref int[] a = ref {1,2,3};
        Console.WriteLine(a[0]);
    }        
}
```

**Expected Behavior**:
Compiler successfully compiles the code or emits a syntax error that array initializer expression isn't allowed in ref expression. I lean towards the latter because such construct looks weird, most probably won't be used and doesn't give much value.

**Actual Behavior**:
Compiler crash.

**Comment by VSadov** [comment]
Should not compile.    `{1,2,3}` is not a variable.

**Comment by akarpov89** [comment]
I've just found that changing 
```csharp
ref int[] a = ref {1, 2, 3};
```
to
```csharp
ref var a = ref {1, 2, 3};
```
causes another crash:
```csharp
Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.DataFlowPass.MarkFieldsUsed(TypeSymbol type)
   at Microsoft.CodeAnalysis.CSharp.DataFlowPass.WriteArgument(BoundExpression arg, RefKind refKind, MethodSymbol method)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitLocalDeclaration(BoundLocalDeclaration node)
```

**Comment by VSadov** [comment]
Added the other scenario as well.

Thanks for reporting these!!!
