### ISSUE TITLE
[Question] MinValue and MaxValue.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#17457]
This is going to read like a dumb question, but I need confirmation.
Are the `MinValue` and `MaxValue` of the types that specify there bit width. eg `Int32` going to change?
If never then I / we, can in same test cases use the text `2147483647`, rather than `Int32.MaxValue.ToString`

**Comment by gafter** [comment]
Those APIs are not part of Roslyn.

**Comment by AdamSpeight2008** [comment]
Yes I know there not part of Roslyn, but we use those constants in unit-tests.

**Comment by jmarolf** [comment]
This would be a question for the https://github.com/dotnet/corefx repo.
