### ISSUE TITLE
[wiki] Building Testing and Debugging

### ISSUE THREAD

**Issue by mihailik** [dotnet/roslyn#17452]
# [Building Testing and Debugging](https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging)
^^^ 

that wiki page has dead references for VS2015 build instructions

![roslyn-issue-wiki](https://cloud.githubusercontent.com/assets/4041967/23412960/3297c236-fdcf-11e6-93c9-1894dbd45f90.png)

For VS2015 the branch name is `microupdate`, but the links to "Instructions to build on...(Win/Linux)" refer to `future` branch.

Here's the right reference:

https://github.com/dotnet/roslyn/tree/microupdate/docs/contributing

**Comment by jasonmalinowski** [comment]
Oh goodness that page was out of date. It's less bad now. :smile:
