### ISSUE TITLE
We might want to revisit SemanticModel behavior around type syntax for a DeclarationExpression based on ParenthesizedVariableDesignation

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#17462]
Today if the type syntax is ```var``` (like in ```var (x1, (x2, x3))```), we don't return anything from GetSymbolInfo\GetTypeInfo for that syntax. @gafter argues that this is somewhat inconsistent by comparison with other forms of type syntax. Also, in incorrect programs, we do lookup var and bind it to a type in the enclosing scope. The semantic model behavior here does not agree with the binding behavior.  

@jcouv FYI

**Comment by jcouv** [comment]
What should the type of "var" be, in `var (x, (y, z)) = (1, (2, 3));`? Aside from nothing, the only other option I can see would be a tuple type (`(int, (int, int))` in this example).
@gafter Is that what you are proposing?
