### ISSUE TITLE
VSSDK "There was a problem checking to see if the profile was setup"

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#17460]
On latest RTM build I get the following error
```
C:\Users\jmarolf\.nuget\packages\Microsoft.VSSDK.BuildTools\15.0.26124-RC3\tools\VSSDK\Microsoft.VsSDK.targets(683,5): error VSSDK1042: There was a problem checking to see if the profile was setup. ExternalSettingsManager::GetScopePaths failed to initialize PkgDefManager for C:\Program Files (x86)\Microsoft Visual S tudio\2017\Enterprise\Common7\IDE\devenv.exe [C:\source\roslyn\Open\src\VisualStudio\VisualStudioInteractiveComponents\VisualStudioInteractiveComponents.csproj]
```

**Comment by Pilchie** [comment]
Tag @AlexEyler

**Comment by AlexEyler** [comment]
That's a new one - setting up a repro now. I'm assuming this was during build of Roslyn.sln?

**Comment by AlexEyler** [comment]
@jmarolf hmm, I couldn't repro. Here are the steps I took:
1. Install latest build of RTM on Win10.
1. Clone Roslyn repo.
1. Open Visual Studio and close it (this sets up the profile for the non-root suffixed instance - I don't think it matters but I want to be explicit).
1. From developer command prompt, run `Restore.cmd`
1. From developer command prompt, run `msbuild /v:m /m Roslyn.sln`

Is there something you've done differently? For instance:
1. Do you have multiple versions of Visual Studio installed? Multiple instances of VS 2017?
1. Is this a first time build or after multiple builds?
1. Are you building from within VS?
1. Does this consistently repro?
1. Do you have a different OS?
1. Is the RoslynDev instance closed when you build the solution?

**Comment by jmarolf** [comment]
@AlexEyler sorry, I cleaned my nuget cache and that fixed the issue.

**Comment by SolderedMushroom** [comment]
But one issue remains: "setup" is a noun; in this error message it ought to be "set up."
