### ISSUE TITLE
Add VB project settings and DTE API to control Language Version

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#17495]
C# projects include a settings drop-down for Language Version (pictured below). But VB projects don't have a corresponding drop-down with the list of VB versions.

From the compiler usage information, the current list looks like this:
```
/langversion:<number>             Specify language version:
                                  9|9.0|10|10.0|11|11.0|12|12.0|14|14.0
```

In particular, the VB Language Version drop-down should expose two options: "default" and "latest" (with friendly labels).

![image](https://cloud.githubusercontent.com/assets/12466233/23474200/c502699e-fe67-11e6-9354-fbb7c79d8d54.png)

Relates to https://github.com/dotnet/roslyn/pull/17435 (UpgradeProject code fixer, which cannot support the scenario for VB because of lack of LanguageVersion DTE API).

FYI @jaredpar @Pilchie @davkean

**Comment by jcouv** [comment]
From discussion with the team, we don't need to do this now, as the coming quarterly release will only have a point release for C#, but not VB.

**Comment by jcouv** [comment]
Indeed, thanks. There may be a duplicate, but I'll reopen this one for now to be safe.

**Comment by CyrusNajmabadi** [comment]
Unlikely to make any change to these VB scenarios.
