### ISSUE TITLE
More Tags

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#175]
One of the issues from the move to github is discussions and actual issues are mixed together.
Could we have some additional tag so we filter just them.
`Issue`
`Topic` A discussion thread.
`Idea / Concept` used to gain a general consensus of a topic, would addition research and design. aka a feasibility study.
`Proposal` more fleshed out idea, more details, etc. getting to the stage we it suitable to be "Pull" topic.

**Comment by theoy** [comment]
Hrm, we have a less utilized Discussion tag.

**Comment by MgSam** [comment]
Could you guys tag "official" language proposals that the team is seriously considering as such? It's hard to tell at a glance what issues are feature requests by the community vs what issues are formal proposals the C# team is actively considering.

**Comment by gafter** [comment]
@MsSam: We're going to use the tag "1 - Planning" for issues under consideration by the language design groups.

https://github.com/dotnet/roslyn/issues?q=is%3Aopen+label%3A%22Area-Language+Design%22+label%3A%221+-+Planning%22+
