### ISSUE TITLE
RIT.exe outputs a list directly instead of its contents

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#17506]
Was running an insertion and saw this in the output:

```
   Ended : Wednesday, March 1, 2017 6:11:10 PM

System.Collections.Generic.List`1[System.String]
Updating assembly versions
```

Note the `System.Collections.Generic.List`1[System.String]`, which is probably intended to be the contents.

**Comment by jasonmalinowski** [comment]
@brettfo some low hanging fruit.
