### ISSUE TITLE
SemanticModel: GetSymbolInfo/GetDeclaredSymbol returns null for System.Drawing.Font

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#17507]
**Version Used**: 1.3.1 

**Steps to Reproduce**:
** Code **: 
`var semanticModel = document.GetSemanticModelAsync().Result //Where document is Microsoft.CodeAnalysis.Document`

Using the above **semanticModel**, we are trying to find the **full qualified path** of the **Font** type declared: `private Font font;`

The way we use **semanticModel** to get the **full qualified path** is like below:
```
ISymbol symbolInformation = semanticModel.GetSymbolInfo(node).Symbol
                                        ?? semanticModel.GetDeclaredSymbol(node);

ITypeSymbolInfo typeInformation = semanticModel.GetTypeInfo(node).Type;

``` 
**Expected Behavior**: 
1. For **symbolInformation**,  **symbolInformation** should not be null; it should suggest the required full qualified path which is *System.Drawing.Font*
2. For **typeInformation**,  **typeInformation** should suggest the required full qualified path which is *System.Drawing.Font*

**Actual Behavior**:
1. **symbolInformation** returns null.
2. **typeInformation** gives **ErrorType** as data and does not give any information on the fully qualified path for **Font**.

**Note**:
We have been using symbolInformation way  for getting the full qualified path of the System defined types and in most cases, we do get the required FQP for those types like say **int's** **System.Int32** etc.

**Comment by Pilchie** [comment]
Can you check your `Compilation` for Diagnostics?  I suspect that references are not configured properly on it.

**Comment by abhijitparkhi1983** [comment]
Hello Pilchie,

Wanted to know if this is what you are suggesting: 
```
var sementicModel = document.GetSemanticModelAsync().Result
var diagnosticDetails = sementicModel.Compilation.GetDeclarationDiagnostics(CancellationToken.None);
```
Do you want me to check out on the **diagnosticDetails** data?

**Comment by Pilchie** [comment]
Yes, but I would look at all diagnostics, not just DeclarationDiagnotics.

**Comment by abhijitparkhi1983** [comment]
I tried to infer the data from all the possible Diagnostics option available like below:

```
var declarationDiagnistics = sementicModel.Compilation.GetDeclarationDiagnostics(CancellationToken.None);
var parseDiagnostics = sementicModel.Compilation.GetParseDiagnostics(CancellationToken.None);
var allDiagnostics = sementicModel.Compilation.GetDiagnostics(CancellationToken.None);
var methodBodyDiagnostics = sementicModel.Compilation.GetMethodBodyDiagnostics(CancellationToken.None);
```
But none of the above gives me any insight to the references. 
So I tried to check for all the referenced assemblies using following code:

`sementicModel.Compilation.References`

The references along with other references shows a reference to System.Drawing dll:

**Assembly Path='Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Drawing.dll'	Microsoft.CodeAnalysis.MetadataReference {Microsoft.CodeAnalysis.MetadataImageReference}**

But still **Font** type is not getting resolved.  Please let me know what else can i look out for

**Comment by abhijitparkhi1983** [comment]
Yes, in one of the projects where i am using **Font** type, I dont see any assembly included in the **sementicModel.Compilation.References**. 

Infact the **sementicModel.Compilation.References** collection is empty which is very strange because the corresponding project in which the current Document is present has assembly reference to many assemblies including **System.Drawing**.

In such cases where the references are missing from **sementicModel.Compilation.References**, what could be a possible reason?

**Comment by gafter** [comment]
Since there are no references, the compiler is doing the right thing.
