### ISSUE TITLE
Cannot type '²' in a method, or in the documentation comment for a method

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#1750]
This is a regression from the behavior in Visual Studio 2013.

### Steps to reproduce

1. Open a document which is located in a project using Git for source control, and which contains a method.
2. Insert the caret inside the body of a method.
3. Wait for Code Lens to show the number of changes which have been made to the method. For example, it might say "3 changes".
4. Type <kbd>Alt</kbd>+<kbd>0178</kbd> (*must* use the number pad for the digits)

### Expected results

The character `²` is typed.

### Actual results

The Code Lens details for the change history appears.

**Comment by balajikris** [comment]
The bug seems to be in the VSEditor. I'll create an internal TFS workitem for them and keep this open as a tracking bug to provide updates.

**Comment by balajikris** [comment]
_Update_:  This was fixed by the editor team today. I will resolve the bug once I am able to verify it in our internal drops.

**Comment by dpoeschl** [comment]
Verified resolved.

**Comment by sharwell** [comment]
@balajikris @dpoeschl Can you check that this is resolved in the XAML text editor as well (which added CodeLens as a margin)? I recently noticed this bug affecting those files.

**Comment by dpoeschl** [comment]
Removing Verified label until this can be confirmed in xaml.

**Comment by dpoeschl** [comment]
(The internal work item mentioned above is 1154849.)

**Comment by balajikris** [comment]
@sharwell I couldn't find how to enable codelens margin in xaml files (i have all options related to codelens checked) . I did however verify that pressing ALT down and typing from number key pad, inserts symbols in xaml and xml files. Do let me know if I need to verify something more, or in case you know what i'm missing.
