### ISSUE TITLE
NavigateToItemProvider.CacheFileNames consumes 100% of a CPU core in background thread

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/roslyn#17511]
After editing (F#) code for some time, switching branches, etc., VS starts to consume ~25% CPU:

![image](https://cloud.githubusercontent.com/assets/873919/23502156/d66711d6-ff47-11e6-82fa-692675cac7cb.png)

It can do it forever (I was watching VS in this state for about 20 minutes, then restarted it).

dotTrace shows this (~1 minute snapshot):

![image](https://cloud.githubusercontent.com/assets/873919/23502345/9ed878e4-ff48-11e6-883d-c63ceefbab5a.png)

**Comment by Pilchie** [comment]
The FileNameProvider is a core VS component.  Tagging @olegtk - can you help us route this?

**Comment by olegtk** [comment]
Please file an internal bug for the editor team. @vasily-kirichenko, any repro steps? If you can still repro it, please grab a memory dump and etl traces. Thanks!

**Comment by Pilchie** [comment]
Created "Bug 390244:NavigateToItemProvider.CacheFileNames consumes 100% of a CPU core in background thread"
