### ISSUE TITLE
NuGet packages need to be updated for Net Standard / App 2.0

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#17517]
The collection of base Roslyn NuGet packages need to be updated for Net Standard / App 2.0.  

Today they contain entries for only Net Standard 1.3.  That means during a build operation for Roslyn in a Net Standard 2.0 enviroment the following will occur:

- Net Standard 1.3 packages will be resolved and downloaded by NuGet 
- The build process will see the duplicate libraries and choose the Net Standard 2.0 versions

Hence these packages will be downloaded for no reason.  This has practical implications for any Net Core 2.0 application that uses Roslyn: ASP.NET, CLI, etc ...  

Will likely be part of the Net Standard 2.0 Tooling story.

**Comment by agocke** [comment]
@jaredpar Is this still something we want to do?

**Comment by jaredpar** [comment]
Yes ... close the issue ;)
