### ISSUE TITLE
[Proposal] Expansion of foreach statement

### ISSUE THREAD

**Issue by momijin** [dotnet/roslyn#1752]
### Proposal

Expansion of foreach statement

1. Composite foreach statement
2. Automatic generated variable
3. Finally block

#### Composite foreach statement

The composite foreach statement is follow to:

```C#
foreach (var item1 in items1, var item2 in items2)
{
    DoSomething(item1, item2);
}
```

It is similar to nested foreach statements.

```C#
foreach (var item1 in items1)
{
    foreach (var item2 in items2)
    {
        DoSomething(item1, item2);
    }
}
```

But their behaviors are different when `break` statement is used. In the former it breaks and finishes a foreach loop, in the latter it breaks only an inner loop and continues by an outer loop. Also their behaviors are different in the following the automatic generated variable and the finally block.

#### Automatic generated index variable

An automatic generated index variable is an automatically generating variable as a current iteration index. This gets inspiration in #1651. Also using an automatic generated index variable realizes like `first` of #131. (They are not little simpler than originals.）
The following is that use example.

```C#
[index]foreach (var item in items)
{
    if (index != 0) {
        builder.Append(",");    // do if it is not first time.
    }
    Console.WriteLine("Item {0}:{1}", index, item);
}
```

Above is expanded to:

```C#
private int index = 0;
foreach (var item in items)
{
    try
    {
        if (index != 0) {
           builder.Append(",");    // do if it is not first time.
        }
        Console.WriteLine("Item {0}:{1}", index, item);
    }
    finally
    {
        index++;
    }
}
```

#### Finally block

When a loop is end or `items` is empty, statements in a finally block are executed. The finally block has a conditional expression of zero or one. Using a finally block and an automatic generated index variable realizes like `else` of #134. (It is not simpler than the original too.）

```C#
[index]foreach (var item in items) 
{
    // do something if items is not empty.
}
finally (index == 0)
{
    // do something if items is empty.
}
```

#### Automatic generated breaked flag variable

An automatic generated breaked flag variable is an automatically generating variable before break statement. Using a finally block and it realizes like `else` of Python.

```C#
[breaked]foreach (var item in items)
{
    if (condition) { break; }
}
finally 
{
    if (!breaked) { } // do something if a break statement did not use.
}
```

Above is expanded to:

```C#
private bool breaked = false;
try
{
    foreach (var item in items)
    {
        if (condition) { breaked = true; break; }
    }
}
finally
{
    if (!breaked) { } // do something if a break statement did not use.
}
```

#### About the automatic generated variable

When using two automatic generated variables, it is described as follows.

```C#
[index, breaked]
```

The scope of automatic generated variables is in a foreach satement. If it is used nested foreach statments, a variable name has to be different. The following is a changed example.

```C#
[outerIndex : index]
```

**Comment by paulomorgado** [comment]
Feels like too much work for too little benefit.

For example, if you want to break out of an onion of loops, just refactor that o a method and `return`. It works with `for`, `foreach`, `while`, etc.

**Comment by momijin** [comment]
@paulomorgado  

Thank you for your kind comment.
