### ISSUE TITLE
Insufficient intellisense assistance on some generic methods

### ISSUE THREAD

**Issue by TKharaishvili** [dotnet/roslyn#17525]
I'm using VS community 2015 update 3 and C# 6

Let's discuss the following method signature:

```C#
void GenericMethod<T1, T2, T3>(T1 item, Func<T1, T2> selector1, Func<T1, T3> selector2)
```

During the invocation, at the time of typing the second parameter

```C#
GenericMethod(new { a = 5, b = "test" }, x => x.
```

intellisense has trouble figuring out what the type of `x` is and doesn't display it's members. Only by the time the programmer gets to the 3rd parameter the type information becomes available.

This only takes place for more than two type arguments. If the method is kept with two generic types only everything works smoothly.

P.S. This may have already been reported or even fixed by now. I'm pointing it out in case it wasn't...

**Comment by Pilchie** [comment]
@jaredpar @gafter is this one of the already seen/fixed type inference in lambda scenarios?

**Comment by gafter** [comment]
Yes, this works like a champ in VS2017.
