### ISSUE TITLE
Attempting to create a SyntaxToken of kind VisualBasic.SyntaxKind.IdentifierToken throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by alinapopa** [dotnet/roslyn#17526]
Is there a way to create a SyntaxToken of type VisualBasic.SyntaxKind.IdentifierToken?

**Version Used**: 
Microsoft.CodeAnalysis 2.0.0-rc3
**Steps to Reproduce**:
using Microsoft.CodeAnalysis.VisualBasic;
var token = SyntaxFactory.Token(SyntaxKind.IdentifierToken, text);
**Expected Behavior**:
Returns a SyntaxToken
**Actual Behavior**:
Throws ArgumentOutOfRangeException

In src\Compilers\VisualBasic\Portable\Syntax\SyntaxFactory.vb
`Friend Shared Sub VerifySyntaxKindOfToken(kind As SyntaxKind)`

**Comment by alinapopa** [comment]
@gafter That looks like a bug not just a question. Is there a reason for SyntaxKind.IdentifierToken to be out of range when creating a token?

**Comment by gafter** [comment]
@alinapopa I don't know what text was passed to that API. Was it the text of a valid identifier name?

**Comment by gafter** [comment]
This appears to be due to the following implementing code:

``` vb
        Friend Shared Sub VerifySyntaxKindOfToken(kind As SyntaxKind)
            Select Case kind
                Case SyntaxKind.AddHandlerKeyword To SyntaxKind.EndOfXmlToken,
                     SyntaxKind.NameOfKeyword,
                     SyntaxKind.DollarSignDoubleQuoteToken,
                     SyntaxKind.InterpolatedStringTextToken,
                     SyntaxKind.EndOfInterpolatedStringToken

                Case Else
                    Throw New ArgumentOutOfRangeException(NameOf(kind))
            End Select
        End Sub

        Public Shared Function Token(kind As SyntaxKind, Optional text As String = Nothing) As SyntaxToken
            VerifySyntaxKindOfToken(kind)
            Return CType(InternalSyntax.SyntaxFactory.Token(ElasticMarker.UnderlyingNode, kind, ElasticMarker.UnderlyingNode, text), SyntaxToken)
        End Function
```

**Comment by alinapopa** [comment]
Yes, exactly. The exception is thrown no matter what text is passed in.

**Comment by AdamSpeight2008** [comment]
That's because you're passing in as the first argument `SyntaxKind.IdentifierToken`, which isn't on the list of valid kinds inside of `VerifySyntaxKindOfToken`. Hence defaults to the  `Case Else` and thus throws the exception.

**Comment by AdamSpeight2008** [comment]
@alinapopa  Have you tried using `[this function](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Syntax/SyntaxNodeFactories.vb#L301)`?

**Comment by alinapopa** [comment]
@AdamSpeight2008 you don't have to explain the code, my point is why `SyntaxKind.IdentifierToken` is not on the list of valid kinds when creating a SyntaxToken.
Using Identifier() works, thanks!

**Comment by TyOverby** [comment]
@gafter: what is the point of VerifySyntaxKindOfToken?

**Comment by TyOverby** [comment]
ping @dotnet/roslyn-compiler

**Comment by AlekseyTs** [comment]
> what is the point of VerifySyntaxKindOfToken?

It looks like its purpose is to restrict what kind of tokens can be created by SyntaxFactory.Token APIs. See if there is a good reason to exclude IdentifierToken from the set.

**Comment by TyOverby** [comment]
It appears that the `SyntaxFactory.Token` method is only wired up to work with language keywords and punctuation.  

The change to make this accept more `SyntaxKind`s would be non-trivial, and we already have dedicated APIs for those syntax kinds.
