### ISSUE TITLE
Breakpoints do not work correctly in portable PDB EnC in unchanged methods

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/roslyn#17539]
**Version Used**: d15rel 26221.0

**Summary**
When using portable PDBs + EnC, if breakpoints are set in unedited methods, the line deltas aren't being applied. So the symbol reader seems to return the old line numbers causing breakpoints to be set on the wrong line (or not bind at all if the is no associated code with this bogus line number). This issue doesn't repo if using Windows PDBs.

**Steps to Reproduce**:
1.  Create a .NET Core project with the below code
2.  Set a breakpoint on the two `Console.WriteLine` calls
3. Start debugging
4. Your first breakpoint will be hit
5. Add a blank line before the call to another method so that the lines in `AnotherMethod` move down by 1 line.
6. Hit F5

**Expected Behavior**:
The breakpoint should hit on the Console.WriteLine line

**Actual Behavior**:
The breakpoint hits, but it was actually bound to the next line (`Debugger.Break`)

**Debuggee**
```csharp
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!"); // set breakpoint here
            AnotherMethod();
        }

        static void AnotherMethod()
        {
            Console.WriteLine("Another method to stop in"); // and here
            System.Diagnostics.Debugger.Break();
        }
    }
```

**Comment by tmat** [comment]
The bug is in Microsoft.DiaSymReader.PortablePdb.
