### ISSUE TITLE
Fix usage of Experimental/InstalledByMSI flags in *.vsixmanifest files.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#17538]
**TRACKIING**

To prevent the Roslyn components from appear in Tools -> Extensions and Updates and to prevent them from being marked as Experimental, the [`Experimental="true"`](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Setup/source.extension.vsixmanifest#L9) flag (as well as `InstalledByMSI="true"`) need to be figured out.

**Comment by Pilchie** [comment]
SDK support is still not there for this.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
