### ISSUE TITLE
Add Ubuntu 16.* to CI infrastructure

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#17533]
From https://github.com/dotnet/roslyn/pull/17386

**Comment by TyOverby** [comment]
Looks like we already have 16.4 machines: https://ci.dot.net/label/ubuntu1604-20170216/search/?q=ubuntu16

**Comment by TyOverby** [comment]
cc @mmitche @jaredpar @dotnet/roslyn-infrastructure

**Comment by mmitche** [comment]
Yep should be quite easy to add 16* runs
