### ISSUE TITLE
Locals declared in the Immediate Window should be included in the Locals Window

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#1754]
1. F5:
class C
{
    static void Main()
    {
        System.Diagnostics.Debugger.Break();
    }
}

2. In the Immediate Window:
var o = new C();

Expected: Locals Window should contain "o"
Actual: Locals is empty

**Comment by amcasey** [comment]
Fixed by 81665e4dedc4d6

**Comment by amcasey** [comment]
I've been using this regularly - just forgot to add the label.
