### ISSUE TITLE
It looks like an interesting code path in MakeIsDeclarationPattern has absolutely no test coverage.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#17548]
https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs#L182

in ```BoundExpression MakeIsDeclarationPattern(SyntaxNode syntax, BoundExpression loweredInput, BoundExpression loweredTarget, bool requiresNullTest)```
```
            else if (type.IsNullableType())
            {
                // While `(o is int?)` is statically an error in the binder, we can get here
                // through generic substitution. Note that (null is int?) is false.

                // bool Is<T>(object e, out T? t) where T : struct
                // {
                //     t = e as T?;
                //     return t.HasValue;
                // }
                return _factory.Call(
                    _factory.AssignmentExpression(loweredTarget, _factory.As(loweredInput, type)),
                    GetNullableMethod(syntax, type, SpecialMember.System_Nullable_T_get_HasValue));
            }
```

I think we should have a unit-test covering the body of the ```if```, including a scenario when SpecialMember.System_Nullable_T_get_HasValue method is not available.

**Comment by gafter** [comment]
Most likely dead code given the restricted pattern forms we support. Will check and remove if so.
