### ISSUE TITLE
Add Oct 21, 2013 design notes to GitHub

### ISSUE THREAD

**Issue by richlander** [dotnet/roslyn#17567]
Add a link for this comment or delete

https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Compiler/Compiler.cs#L769

/cc @gafter

**Comment by gafter** [comment]
@MadsTorgersen Where are the 2013-10-21 design notes?

**Comment by gafter** [comment]
Oh, I have them in my mailbox.

**Comment by gafter** [comment]
We should fill out 2013 and any 2014 that are missing.

**Comment by gafter** [comment]
Done.

**Comment by gafter** [comment]
Oh, that isn't the one I just uploaded.
