### ISSUE TITLE
Create a build queue that runs our tests on Windows 7

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#17566]
We've ran into a few cases where we are running our builds on Windows 7 has failed because we accidentally use newer PowerShell features. Having a queue would catch these sorts of things.

Right now this would be a bit of a pain because we'd have to maintain special images with Visual Studio builds, but once we move to a standard image we might get this more or less for free.

**Comment by tmat** [comment]
We might also want to consider including a machine with the latest .NET Framework build before it releases.

**Comment by jasonmalinowski** [comment]
Going to close this one: it'd be nice, but not really worth the effort.
