### ISSUE TITLE
SemanticModel.Compilation.References returns empty list on Deployment Server

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#17569]
**Version Used**: 1.3.1

**Steps to Reproduce**:

1. Environment in which the code works: 
      - Developers Machine with 
      - Microsoft Visual Studios 2015 Community Version installed 
      - NET Framework 4.6.1 
      - Roslyn Version 1.3.1 
      - Code which works and returns required list of Referenced assemblies:
```
var semanticModel = document.GetSemanticModelAsync().Result //Where document is Microsoft.CodeAnalysis.Document;

ISymbol symbolInformation = semanticModel.GetSymbolInfo(node).Symbol
                                        ?? semanticModel.GetDeclaredSymbol(node);

var allReferences = sementicModel.Compilation.References;
```
2. Environment/Server machine where the above code does not work:
      - Server Machine Windows 2008.
      - .NET Framework 4.6.1 
      - Release folder of the application code where along with the application .dll, we do have Roslyn related .dll's as well. **Roslyn is not installed separately as such on the Server Machine**. 
      - Code which does not work:

```
var semanticModel = document.GetSemanticModelAsync().Result //Where document is Microsoft.CodeAnalysis.Document;

ISymbol symbolInformation = semanticModel.GetSymbolInfo(node).Symbol
                                        ?? semanticModel.GetDeclaredSymbol(node);

var allReferences = sementicModel.Compilation.References;
```

Please let me know what am i missing on the Server Machine?

**Comment by Pilchie** [comment]
Likely you are missing the Reference assemblies, which are installed by various things that VS depends on, including: The build tools, the Portable Class Library references, other SDKs.

Compile time references are generally different than runtime references, so you need to ensure that the compile-time dependencies are installed.

Also, you haven't specified where you are getting a `document` from - is it `MSBuildWorkspace`?

**Comment by abhijitparkhi1983** [comment]
Thanks for a quick reply @Pilchie .

Yes I am getting the **Document** using **MSBuildWorkspace**. I am opening the **Solution** using **OpenSolutionAsync** and then iterating through all the **Projects** from Solution and then  through all the **Documents** of a Project.

I missed to mention that we have also installed the **Microsoft Build Tools 2015**  on the server machine.

I belived that with .NET Framework 4.6.1 version installed on the server, it should take care of installing the required Portable Class Library references as well as all the required **Compile-Time dependencies**.
The installer which I have used for installing the above .NET version is **NDP461-DevPack-KB3105179-ENU.exe**

Do I have to install any specific SDK/installer for Roslyn to work? 
Do I have to install **.NET Compiler Platform SDK** on the server machine?

Looking forward to hear from the Roslyn Team.

**Comment by Pilchie** [comment]
Just to clarify - installing .NE 4.6.1 provides *no* reference assemblies, it only provides runtime implementation assemblies.  To get portable library reference assemblies, you should install something like: https://www.microsoft.com/en-us/download/details.aspx?id=40727

> Do I have to install any specific SDK/installer for Roslyn to work?

Yes.  You need to install whatever SDK/installer the solution you are trying to analyze depends on. However, that is specific to the solution you are trying to analyze.
