### ISSUE TITLE
Allow comparison of type parameteres

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/roslyn#17571]
**Version Used**: 
C# 7

I'm sorry if this has been discussed before, I was unable to find it.
Anyway, I'd love to be able to compare type parameters like so:

    var isPerson = T is Person;

or in `switch` statements:

    public IEnumerable<T> GetCollection<T>()
    {
      switch (T)
      {
        case Manager:
          return Context.Managers;
        case Person:
          return Context.Persons;
        default:
          throw new NotSupportedException("The specified type is not supported.");
      }
    }

Currently this isn't supported either:

    public IEnumerable<T> GetCollection<T>()
    {
      switch (typeof(T))
      {
        case typeof(Manager): //A constant value is expected
          return Context.Managers;
        case typeof(Person):
          return Context.Persons;
        default:
          throw new NotSupportedException("The specified type is not supported.");
      }
    }

**Comment by alrz** [comment]
#8194

**Comment by weitzhandler** [comment]
I wouldn't say my suggestion equals to yours, but I'll close this one since I'm happy with the other one too.
Mine was that you can treat a type declaration (i.e. `T` from type parameter directly without having to get its type.

**Comment by alrz** [comment]
That wouldn't be possible because `switch` accepts an expression not a type. #8114 does not propose any syntax changes as the parser is already capable of parsing typeof in case clauses.
