### ISSUE TITLE
[Proposal] "Default values" for out parameters

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#1757]
In methods with `out`-parameters it is very common to see first statements like:

``` c#
string DoSomething(string key, out string value, out int id)
{
  value = null;
  id = 0;

  var a = F(key);
  if (a == null) return null;

  var b = G(a);
  if (b == null) return null;

  value = H(b, out id);
  return J(b);
}
```

While definite assignment rules are definitely good thing to have in C#, statements like this (to satisfy definite assignment rules) looks pretty silly in methods with "early" returns. It may be convenient to allow out parameter "initialization" with some constant default value in-place, using optional parameter syntax:

``` c#
string DoSomething(string key, out string value = null, out int id = 0)
{
  var a = F(key);
  if (a == null) return null; // ok, 'value' and 'id' are assigned

  var b = G(a);
  if (b == null) return null;

  value = H(b, out id);
  return J(b);
}
```

**Comment by ViIvanov** [comment]
Can I call this method like that:
```cs
var smth = DoSomething("key");
```
? Is this side effect?

**Comment by controlflow** [comment]
@ViIvanov this is declaration-site feature, just to satisfy definite assignment rules. "Default" value has nothing to do with invocations, it's should not be stored in metadata with `[DefaultValue]` attribute.

**Comment by svick** [comment]
I don't understand, why does the current syntax look silly?

Also, I think that using the same syntax as optional parameters without actually making the parameters optional would be confusing.

**Comment by MgSam** [comment]
Agree with @svick. The risk of confusion with this syntax is pretty great, as seen by @ViIvanov's question. 

I don't think syntax making it easier to add new methods that use out parameters should really be a priority, as the proposed tuples feature will be much nicer for the caller to interact with and serve the same purpose (returning multiple values).

**Comment by alrz** [comment]
@gafter I think "caller-receiver parameters" from [record spec draft](https://github.com/dotnet/roslyn/blob/features/records/docs/features/records.md) can be applied here for a straightforward `Deconstruct` implementation.

```cs
public void Deconstruct(out string name = this.Name, out int age = this.Age) {}
```

However, as currently specified, this needs the method to be not static. So you could not use this in a extension Deconstruct method. However, with "extention everything" it wouldn't be much of an issue.

```cs
extension class PersonExtensions : Person
{
  public void Deconstruct(out string name = this.Name, out int age = this.Age) {}
}
```
etc.

**Comment by jcouv** [comment]
Moving language design discussion over to csharplang. Thanks

**Comment by jcouv** [comment]
Issue moved to [dotnet/csharplang #1033](https://github.com/dotnet/csharplang/issues/1033) via [**ZenHub**](https://www.zenhub.com/)
