### ISSUE TITLE
"var" infers the left side, why not use "new()" to infer the right?

### ISSUE THREAD

**Issue by playsomethingsaxman** [dotnet/roslyn#17582]
In a code scope we could infer type from the left side and use:

`var x = new ConcurrentDictionary<int, Queue<int>>();`

But inside a class the same thing would likely be stretched out to:

`private ConcurrentDictionary<int, Queue<int>> _x = new ConcurrentDictionary<int, Queue<int>>();`

Is there anything stopping us from inferring from the right side? For instance if I use a type-less constructor on the right side, can't it know to use the empty constructor for the type specified on the left?

`private ConcurrentDictionary<int, Queue<int>> _x = new();`

Look how much quicker that could be to type, or cleaner to read.

**Comment by gafter** [comment]
Language proposals go in the https://github.com/dotnet/csharplang repository, where you will already find [a feature request that is being tracked by the language design group](https://github.com/dotnet/csharplang/issues/100) for this feature.
