### ISSUE TITLE
Codelens does not work well in Websites

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#1758]
Codelens doesn't play well in web scenarios, I'm compiling issues here.
1. The adornment is not enabled for web files like .aspx or .cshtml etc.
2. Location info is incorrect for references in .cshtml files for functions defined in App_Code for which we do show references. See screenshot below.
3. Add a .cs file to App_code folder and consume the code in a Helper1.cshtml file under the same App_code folder. Close the Helper1.cshtml from the editor. Codelens now picks up the generated temp files, it should instead show 0 references. See screenshot below.
4. References from closed .aspx pages won't show up due to how the web project system works. [issue: https://github.com/dotnet/roslyn/issues/9194]

screenshot for issue 2:
![image](https://cloud.githubusercontent.com/assets/4213867/6974088/8037ec7a-d944-11e4-9a37-58271d750f0f.png)

screenshot for issue 3:
![image](https://cloud.githubusercontent.com/assets/4213867/6974141/fdb93244-d944-11e4-8ae2-172916dbf0f9.png)

**Comment by Pilchie** [comment]
I believe that the design was to not show any references that come from .cshtml files since they are transient depending on whether the file is open or not.  @DustinCampbell @tmeschter Can one of you confirm?

**Comment by tmeschter** [comment]
I don't recall if we or the CodeLens team explicitly designed for any of these scenarios.

I'm not a web developer, but my understanding is that you would not generally define types and members in .cshtml/.vbhtml files to begin with. If that is true, there may not be much value in enabling the adornment.

References are calculated in the CodeLens process, and I don't think that process has any way of knowing that a reference is in a .cshtml file or a generated file and thus should be excluded. Potentially those references could be filtered out on the VS side, though.

**Comment by balajikris** [comment]
Observation: Dev12 seems to filter out references from .cshtml files.

**Comment by Pilchie** [comment]
Moving to 1.1 based on current bar.

**Comment by balajikris** [comment]
More related issues and work items at https://github.com/dotnet/roslyn/issues/9194

**Comment by jinujoseph** [comment]
This is believed to be fixed in 16.0.Preview1 
If you notice more issue here ,requesting to file a new issue (as this contains old context)
