### ISSUE TITLE
[IExpression] IOperation unit tests for invocation arguments

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#17587]
- [x] IArgument
- [x] IOmmittedArgumentExpression

Arguments can be present in 3 different binding contexts, all of which need unit tests. See implementation for [IHasArgumentExpression.ArgumentsInParameterOrder](http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/IExpression.cs,98f791614f6140c3,references)
   1. BoundCall
   2. BoundIndexerAccess
   3. BoundObjectCreationExpression

Refer to the [OverloadResolutionTests](http://source.roslyn.io/#q=OverloadResolutionTests)

**Comment by genlu** [comment]
@AlekseyTs Will `BoundOmittedArgument` ever exposed to IOperation? From what I see in the binder code, it seems the invocation will always contain actual argument expressions rewritten from those `BoundOmittedArgument`.

http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Binding/Binder_Invocation.vb,f86ac8cb64a210f3

**Comment by AlekseyTs** [comment]
It looks like BoundOmittedArgument nodes can escape initial binding, we even have special lowering for them.

**Comment by genlu** [comment]
@AlekseyTs Ah, yes. I see them in erroneous code like below (when resolution failed), seems it is for error reporting purpose. Form top of your head, will valid code results in `BoundOmittedArgument` after initial binding?

```vb
Class P
    Sub M1()
        M2(1, , 2)
    End Sub

    Sub M2(Optional a As Integer = 0, Optional b As Integer = 0)
    End Sub
End Class
```

**Comment by AlekseyTs** [comment]
Yes.

> we even have special lowering for them

**Comment by genlu** [comment]
Related https://github.com/dotnet/roslyn/issues/8794

**Comment by mavasani** [comment]
@genlu - is this test item done? Can we close it if so?
