### ISSUE TITLE
[IExpression] IOperation unit tests for element reference expressions

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#17589]
- [ ] IArrayElementReferenceExpression
- [ ] IPointerIndirectionReferenceExpression
- [x] ILocalReferenceExpression
- [x] IParameterReferenceExpression
- [x] IInstanceReferenceExpression
- [x] IMemberReferenceExpression
- [x] IFieldReferenceExpression
- [x] IPropertyReferenceExpression
- [x] IEventReferenceExpression
- [x] ILateBoundMemberReferenceExpression 

We should probably break these into separate issues.

**Comment by jinujoseph** [comment]
seperate bugs to track the unfinished ones
