### ISSUE TITLE
Consider yes/no as a additional aliases for true/false

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#17586]
This is a suggestion.

The convention "true" and "false" to represent boolean true and boolean false are simply conventions and not always the most expressive terms.

Consider the readability here:

    if (DoesParentNodeMatch(a,b,) == true)

    if (DoesParentNodeMatch(a,b,) == yes)

The fact is that in ordinary language we rarely resort to using "true" or "false" but rather "yes" and "no".

Tony:  "Did you catch up with mike last week Ed?"

Ed:      "true" 

See what I mean? pretty much everyone would reply "yes" here. Questions with boolean results usually have answers "yes" or "no".

If adding two new aliases for "true" and "false" does not cause a breaking change, then please consider this.

**Comment by dman2306** [comment]
It can cause many breaking changes. What if I have variables called `yes` and `no`? Even worse, imagine this contrite example, what if I already have:
`bool yes = false, no = true;`

Your addition would completely reverse the logic of my code. C# is not English. I don't think we need to try to turn it into English.

**Comment by 0xd4d** [comment]
I don't like this idea, but if you really need it today, you can do it today:

```C#
using System;
using static ConsoleApp.BooleanExtensions;

namespace ConsoleApp {
	static class BooleanExtensions {
		public const bool yes = true;
		public const bool no = false;
	}

	class Program {
		static void Main(string[] args) {
			Console.WriteLine($"yes = {yes}");
			Console.WriteLine($"no = {no}");
		}
	}
}
```

**Comment by Korporal** [comment]
Yes, I guess its too late to consider this now - would have been neat though!
Thanks
