### ISSUE TITLE
[IExpression] IOperation unit tests for unary operators

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#17591]
- [x] IUnaryOperatorExpression 
- [x] IAddressOfExpression
- [x] IAwaitExpression

Need to write tests to verify all [UnaryOperatorKind](http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/IExpression.cs,ca10f7d1b0fa7a99,references) values.

**Comment by jinujoseph** [comment]
@heejaechang can you verify this https://github.com/dotnet/roslyn/issues/8834 as well

**Comment by mavasani** [comment]
@heejaechang were you able to checkin the unary operator tests?

**Comment by heejaechang** [comment]
yes. I did, but just IUnaryOperatorExpression but the other 2
