### ISSUE TITLE
[IExpression] IOperation unit tests for binary operators

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#17592]
- [x] IBinaryOperatorExpression
- [x] IAssignmentExpression
- [x] ICompoundAssignmentExpression
- [x] IEventAssignmentExpression
- [x] IConditionalAccessExpression
- [x] IConditionalAccessInstanceExpression
- [x] INullCoalescingExpression
- [x] IIsTypeExpression
- [x] ISizeOfExpression
- [x] ITypeOfExpression

Need to write tests to verify all [BinaryOperatorKind](http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/IExpression.cs,e5b345c6bd506816) values.

We should probably break these into separate issues.

**Comment by jinujoseph** [comment]
make sure to verify https://github.com/dotnet/roslyn/issues/8913

**Comment by jinujoseph** [comment]
and also https://github.com/dotnet/roslyn/issues/8846

**Comment by jinujoseph** [comment]
also https://github.com/dotnet/roslyn/issues/9174
