### ISSUE TITLE
Bug - remove unused usings

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#17609]
Try this,

Write some simple code that compiles but use Int rather than int etc. Then hover mouse over the usings and you'll see it is happy to remove "System" (if there are no other uses of it).

However doing that and committing the code can cause build errors because Int, etc are defined in System and it should not consider System safe to remove if the code contains any of these type aliases.

This caused a build to break recently because developer assumed it is always safe to remove unused usings.

**Comment by dman2306** [comment]
Well there is no `Int`, I assume you mean `Int32` or some other version of it? It is working fine for me. As soon as I add an `Int32` in VS2017, `using System` is no longer flagged as unused. Please provide code the reproduces the issue?

**Comment by Korporal** [comment]
Maybe its VS 2015 - Id need to check

**Comment by CyrusNajmabadi** [comment]
@Korporal Can you please provide a simple repro for this?

**Comment by dman2306** [comment]
@Korporal Decimal works correctly in 2015 and 2017. Please provide code that reproduces the problem.

**Comment by Korporal** [comment]
Folks sorry for confusion, let me dig out the pull request in our system that dealt with this and get a repro sample, dont want to waste your time. (If I recall the type was a appearing as a method return type).

**Comment by Korporal** [comment]
I'm closing this, I must have misdiagnosed this a few weeks ago when I stumbled upon something, you guys are quite right and I can't repro, I'm closing.
