### ISSUE TITLE
Suggestion: find all references for constants/literals

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#17608]
I'd like to see Visual Studio's "Find all references" include support for literals/constants.

Currently we can't do this easily and must do a brute force text search (Find in files).

So if we have some code:

    string srchLabel = "AllCategories";

We could select the string constant and find all other references to that string in the solution.

I did post this suggestion recently but can't recall which repo, but this seems to be the correct place for this.

This feature would be very handy for seeing if developers have hard coded such things and is especally useful when refactoring large apps that have abused hard coding and have umpteen copies of the string literal scattered across code.

**Comment by jmarolf** [comment]
@Korporal you are in luck: https://github.com/dotnet/roslyn/pull/17048 @CyrusNajmabadi already this feature 3 weeks ago

**Comment by CyrusNajmabadi** [comment]
As @jmarolf mentioned, this was done with https://github.com/dotnet/roslyn/pull/17048.  Cheers!
