### ISSUE TITLE
[IStatement] IOperation unit tests for miscellaneous statements

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#17606]
- [x] IBlockStatement
- [x] IExpressionStatement
- [x] IEmptyStatement
- [x] IThrowStatement
- [x] ILockStatement
- [ ] IUsingStatement

**Comment by 333fred** [comment]
IUsingStatement at least has no tests in C#, and barely any in VB. We need to verify each of these to make sure they're actually complete.

**Comment by jinujoseph** [comment]
verify IUserStatement test

**Comment by 333fred** [comment]
With the tests for using statements in the flow analysis feature, I'm confident we have enough tests at this point.
