### ISSUE TITLE
SkipCompilerExecution and ProvideCommandLineArgs should be set before calling the CompileDesignTime target	

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#17613]
**Version Used**: 

VS 2017 RTW (dev15rtwsvc 26228.04)

**Steps to Reproduce**:

```
git clone https://github.com/aarnott/pinvoke
cd pinvoke
git checkout c5642c29ddd
src\pinvoke.sln
```

**Expected Behavior**:

No errors in error list

**Actual Behavior**:

3 errors in error list:

SkipCompilerExecution and ProvideCommandLineArgs should be set before calling the CompileDesignTime target	
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\Managed\Microsoft.Managed.DesignTime.targets:243

![image](https://cloud.githubusercontent.com/assets/3548/23681917/ec5e1370-0345-11e7-8403-2c4c9b6cdc64.png)

**Comment by AArnott** [comment]
This doesn't always repro. But it's one of many issues I've run into when converting the PInvoke.sln to the new .NET SDK project type.

**Comment by Pilchie** [comment]
@davkean / @natidea - should this be migrated to project system?

**Comment by natidea** [comment]
This issue was moved to dotnet/roslyn-project-system#1707

**Comment by vamsisridhara** [comment]
this issue resolved when I disable the solution light weight load option.

**Comment by Habikki** [comment]
@vamsisridhara, just ran into this issue today and I had the inverse work for me.  Enabling light weight load seemed to address my build error.  Strange.
