### ISSUE TITLE
IDE0018: Variable Declaration can be mistakenly inlined on do while loop

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/roslyn#17624]
**Version Used**: 
Visual Studio 2017 RTM (Visual Studio/15-RTW+26228.4)
**Steps to Reproduce**:

1. Have a do while loop with a method with an out parameter and using the out parameter after the do while
2. Use the suggested IDE0018 fix to inline variable (available on mouseover over string token)

**Expected Behavior**:
IDE0018 is not suggested

**Actual Behavior**:
IDE0018 is suggested and application results in compilation error
CS0103	The name 'token' does not exist in the current context

Repro source:
Note: This is a heavily shortened version of a unit test, the debug assert is usually an Assert.Equal and more other asserts exist.
```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IDE0018Repro
{
    class Program
    {
        static void Main(string[] args)
        {
            string activateEmail;
            string token;
            do
            {
                activateEmail = GetEmail();
            } while (!TryExtractTokenFromEmail(activateEmail, "activate-user", out token));
            Debug.Assert(token == "Test"); // works
            /*
             do
             {
               activateEmail = GetEmail();
             } while (!TryExtractTokenFromEmail(activateEmail, "activate-user", out string token));
             Debug.Assert(token == "Test"); // compile error token not valid in this context
           */

        }

        private static string GetEmail()
        {
            return "Hello World";
        }

        private static bool TryExtractTokenFromEmail(string activateEmail, string key, out string token)
        {
            token = "Test";
            return true;
        }
    }
}

```

**Comment by Pilchie** [comment]
I think this same issue was just reported on the Developer Community forum too?
