### ISSUE TITLE
Can't generate field/property when left hand-side matches the name of another name in scope

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#17621]
1. Code:

``` C#
    using System;

    public class Foo
    {
        public Foo(String foo)
        {
            String = foo;
        }
    }
```

2. Drop lightbulb on the left hand side of the assignment

**Expected:** To be able to generate field/property
**Actual:** Cannot generate field/property

![image](https://cloud.githubusercontent.com/assets/1103906/23696446/c95a8f00-0437-11e7-9360-83588c9a558e.png)

If I change the property to be something else such as Stringed, then I get:

![image](https://cloud.githubusercontent.com/assets/1103906/23696295/2f771444-0437-11e7-856b-99fdc9f41732.png)

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by davkean** [comment]
raised by https://twitter.com/khellang/status/839241370015518720. @khellang

**Comment by khellang** [comment]
Also, semi-related; generate a getter-only auto prop. Is that on the table? Couldn't find an issue.

**Comment by davkean** [comment]
Yeah, I'd probably expect an option for that. File another bug.

**Comment by CyrusNajmabadi** [comment]
Yup.  Standard problem of us moving onto compiler diagnostics.  Should be not that difficult to fix.  Ideally IOperation will make this better.
