### ISSUE TITLE
Option to generate a getter-only auto property

### ISSUE THREAD

**Issue by khellang** [dotnet/roslyn#17622]
**Steps to Reproduce**:

1. Code:

```csharp
public class Foo
{
    public Foo(string bar)
    {
        Bar = bar;
    }
}
```
 
2. Drop lightbulb on the left hand side of the assignment

**Expected Behavior**:

Provide an option to generate a getter-only auto property. Preferably as the first option.

**Actual Behavior**:

Options to generate:

1. Auto property
2. Field
3. Readonly field
4. Local

![image](https://cloud.githubusercontent.com/assets/582487/23697195/1adabb1c-03e7-11e7-98f4-650c8e8cc2af.png)

**Comment by khellang** [comment]
Raised by request in #17621

**Comment by alrz** [comment]
Also it would be nice to put "generate" code actions into separate sub menus for fields and properties.

**Comment by CyrusNajmabadi** [comment]
> Also it would be nice to put "generate" code actions into separate sub menus for fields and properties.

Generate code actions will be placed into separate sub menus if we have too many items to show.  They actually are generated as sub-items by the fixer.  we just actually elevate the nested items to tp-level items if there are not that many items to show.

**Comment by CyrusNajmabadi** [comment]
@DustinCampbell @Pilchie . I'm leaning toward *always* generating an auto-prop if you're in the constructor.  Do you have any issue with the default just becoming that?  I think i'd prefer that over having "generate property" and "generate auto-property" in the same list.  

What do you think?

**Comment by Pilchie** [comment]
My ideal would be that generate always generates an autoproperty (if on a langver high enough to support it), and that we offer a refactoring on auto-properties to convert to a full property and introduce a backing field.

**Comment by miloush** [comment]
Perhaps worth a code style option?

**Comment by khellang** [comment]
I think it's reasonable to lean towards immutability by default and make it easy to switch to mutable fields/properties if needed :+1:

**Comment by miloush** [comment]
@CyrusNajmabadi @Pilchie I don't think this issue is about generating autoproperty, that is already the case as shown in the screenshot (and the one I suggested code style option for). I think this issue is about missing the property equivalent of "read-only field".

**Comment by CyrusNajmabadi** [comment]
This has been fixed, and is now the default:

![image](https://cloud.githubusercontent.com/assets/4564579/26086536/1b1c93a4-39a0-11e7-9809-53eadfc41648.png)

**Comment by khellang** [comment]
Thanks, @CyrusNajmabadi! :heart:
