### ISSUE TITLE
Parser Bug

### ISSUE THREAD

**Issue by Yassseeen** [dotnet/roslyn#17626]
**Version Used**: 

**Steps to Reproduce**:

After upgrading to VS 2017 I got the following error from this code (which has always been working perfectly)

byte[] HexStringToByteArray(string hex)
    {
        if (hex.Length % 2 == 1)
            throw new Exception("The binary key cannot have an odd number of digits");

        byte[] arr = new byte[hex.Length >> 1];

        for (int i = 0; i < hex.Length >> 1; ++i) // Error in this line
        {
            arr[i] = (byte)((GetHexVal(hex[i << 1]) << 4) + (GetHexVal(hex[(i << 1) + 1])));
        }

        return arr;
    }
Exception:

Error 1: The variable 'i' cannot be used with type arguments
Error 2: 'hex' is a variable but is used like a type    
the solution was to surround the expression by parentheses.

for (int i = 0; i < (hex.Length >> 1); ++i)

**Expected Behavior**:

**Actual Behavior**:

**Comment by DavidArno** [comment]
Pasting that code into VS2017 gives a clue as to what's going on. It reformats the "error" line to:
```cs
for (int i = 0; i<hex.Length> > 1; ++i)
```
in other words, Roslyn v2 is parsing `i<hex.Length>>1` as a generic type being tested as greater than 1.

**Comment by SLaks** [comment]
This works on `master`: http://tryroslyn.azurewebsites.net/#b:master/K4Zwlgdg5gBAygTxAFwKYFsDcBYAUAB2ACMAbMAYxnJIEMQQYBhGAbzxg5gDcB7MAExgBZABSRkAbQC6MABaoAHgEpWedpwBmPAE4wxEZDDAwAvDAAMmIzAA8cxQDoAMqmjJZMAHyeYARisA1AFgKgD0oTAAotraOkYQMO5gDGQQqOocbLicMAC+MBl5ari5QA==

**Comment by 0xd4d** [comment]
This was probably fixed by #16834

**Comment by jasonmalinowski** [comment]
(for those following along at home, this originated from a [StackOverflow question](http://stackoverflow.com/questions/42669193/vs-2017-bug-or-new-features))

**Comment by gafter** [comment]
This is fixed by #16834.

**Comment by gafter** [comment]
See also #17135, #17296
