### ISSUE TITLE
Intellisense doesn't show local variables when < smaller than is used with List Count property

### ISSUE THREAD

**Issue by wanton7** [dotnet/roslyn#17625]
**Version Used**: 
Visual Studio 2017 

**Steps to Reproduce**:

1. Open Visual Studio 2017
2. Create C# console project
3. Try to do following
var bar = 1;
var foo = new List<int>();
if (foo.Count < bar)

**Expected Behavior**:
When you do press < then b from keyboard you would expect bar to show up in intellisense.

**Actual Behavior**:
Local variables are not shown by intellisense.
If you change foo to array and use .Length instead, intellisense works.

**Comment by 0xd4d** [comment]
Same as #17258 ?

**Comment by Pilchie** [comment]
Yes, this is a dupe.
