### ISSUE TITLE
Runtime BindingFailure for .NET Framework 4.6.1 project referencing .NET Standard 1.4

### ISSUE THREAD

**Issue by UnoSD** [dotnet/roslyn#17639]
**Version Used**:

- Project A: .NET 4.6.1
- Project B: .NET Standard 1.4 csproj
- VS2017

**Steps to Reproduce**:

1. Add some dependencies to .NET Standard project (E.G. System.IO.Filesystem.Primitives, System.Security.Crypyography.Primitives and others).
2. Reference .NET Standard project from .NET Framework project.
3. Build and run.

The result is a `Managed Debugging Assistant 'BindingFailure'` as it cannot resolve the .NET Framework implementation of the .NET Standard dependency. Indeed none of the dependencies' `.dll` is copied to the output folder.

**Expected Behavior**: The compiler should copy the correct dependency's `.dll` from the package\GAC to the output folder. Or at least (and probably better), it should automatically add the dependent NuGet packages to the referring project.

**Actual Behavior**: Runtime exceptions.

The only workaround is to copy or reference the missing libraries manually.

Thank you.

**Comment by nguerrera** [comment]
This is tracked by https://github.com/NuGet/Home/issues/4488. Currently, the referencing project has to use PackageReference for transitive dependencies to flow. See discussion for workaround involving a dummy package reference.
