### ISSUE TITLE
RemotingException : Requested Service not found in Integration tests

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#17634]
Tests fail randomly because of that:

1. https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/932/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/CSharpChangeSignatureDialog/VerifyReorderParameters/
2. https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/934/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/CSharpChangeSignatureDialog/VerifyReorderParameters/
3. https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/953/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicChangeSignatureDialog/VerifyRefactoringCancelled/
4. https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/955/testReport/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicFindReferences/FindReferencesToSharedField/

Found in #17617

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-infrastructure

**Comment by OmarTawfik** [comment]
@heejaechang might this be related to OOP? trying to run them locally sometimes succeed.

**Comment by jasonmalinowski** [comment]
@tannergooding, @tmeschter, @dotnet/roslyn-ide, any ideas?

**Comment by heejaechang** [comment]
@jasonmalinowski I think this is new VSI test issue (new VSI remoting to out of proc VS instance issue)

**Comment by OmarTawfik** [comment]
@heejaechang is someone looking into it? this is blocking all? PRs to master.

**Comment by heejaechang** [comment]
@OmarTawfik @Pilchie I dont think this is OOP thing. it is new VSI remoting. I dont know anything about it.

**Comment by Pilchie** [comment]
@dpoeschl: Do you have another bug tracking this already?

**Comment by dpoeschl** [comment]
All of the tests listed are disabled with their own tracking bugs.

**Comment by OmarTawfik** [comment]
@dpoeschl still failing :(
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/1037/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpFindReferences/FindReferencesToCtor/

**Comment by OmarTawfik** [comment]
another one: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/1041/testReport/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicGenerateTypeDialog/CheckFoldersPopulateComboBox/

**Comment by dpoeschl** [comment]
3/4 days and the builds are already gone. This is ridiculous. @dotnet/roslyn-infrastructure

**Comment by tannergooding** [comment]
Tagging @mmitche, build logs and the like are disappearing particularly quickly.

**Comment by mmitche** [comment]
@dpoeschl I upped it a bit, but the amount of space used is pretty crazy so I can't bump it that high.

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving out.

**Comment by jinujoseph** [comment]
Closed via [Link](https://github.com/dotnet/roslyn/pull/25151)
