### ISSUE TITLE
"Pick Members" dialog should have a search/filter box.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#17649]
Recommended by @terrajobst 

I think this would be a good idea.  Esp. as we use this dialog for more purposes.  i.e. https://github.com/dotnet/roslyn/issues/17648

**Comment by Pilchie** [comment]
I agree though I think it's less important than some other work.

**Comment by TobiasSekan** [comment]
It is already in -> I think this Issue can close.

![2021-12-03 17_57_00-AXP enERPplus - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/17874713/144642035-37031242-a8fb-4aea-9372-e3fd78573079.png)

**Comment by CyrusNajmabadi** [comment]
Yup.  Can close out.
