### ISSUE TITLE
`Generate Both` is confusing

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#17644]
We have the option to `Generate Both` for both a `GetHashCode` and `Equals`, but it's confusing what "both" refers to if you have no selection and other things in the list (particularly since it comes before the items it refers to).

**Comment by CyrusNajmabadi** [comment]
> particularly since it comes before the items it refers to

Can you give a picture?  It should be:

```
Generate Equals(object)
Generate GetHashCode()
Generate both
```

**Comment by Pilchie** [comment]
I can't repro now, but I thought I saw that on Friday when I was playing with it :-/

**Comment by CyrusNajmabadi** [comment]
yeah... that would be pretty crazy.  Given that it's a single provider just generating a list of 3 items.

Also, there's need for just "GetHashCode".  i.e. you have a type that already had .Equals in it.  In this case we can just offer to generate just 'GetHashCode' for you.

So, i think the experience should likely be.

1. Empty file.  Offer: Generate-Equals and Generate-Equals-and-GetHashCode
2. You already have an Equals(object) method.  We only offer 'Generate GetHashCode'.

**Comment by CyrusNajmabadi** [comment]
'Generate both' removed with https://github.com/dotnet/roslyn/pull/17689
