### ISSUE TITLE
Design questions for Generate Equals/GetHashCode

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#17645]
- [ ] Should we support generating only one - it's not a good practice to encourage.
- [x] Should we also generate `operator ==`/`operator !=`?
- [x] Should we add IEquatable<T> support for people?

@kuhlenh / @DustinCampbell / @CyrusNajmabadi - thoughts?

**Comment by CyrusNajmabadi** [comment]
> Should we support generating only one - it's not a good practice to encourage

Good point.  Given that we warn if you have Equals but not GetHashCode.  We probably only want to offer both if you have none.

**Comment by CyrusNajmabadi** [comment]
> Should we also generate operator ==/operator !=?

Yes.  This work was done in: https://github.com/dotnet/roslyn/pull/17976

**Comment by CyrusNajmabadi** [comment]
> Should we add IEquatable support for people?  

Yes.  I think that should be done as well.

**Comment by CyrusNajmabadi** [comment]
All of this has been done.
