### ISSUE TITLE
Generate Equals/GetHashCode should use framework helpers if available

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#17646]
@jcouv and @MadsTorgersen tell me that we added helpers to testing equality and calculating/combining hash codes for members to the framework to support the compiler doing it.

We should test the framework and use them instead of hardcoding strange constants and stuff into the user's code if they invoke Generate Equals/GetHashCode.

**Comment by CyrusNajmabadi** [comment]
Unfortunately, the framework helpers are internal.

**Comment by Pilchie** [comment]
I thought the compiler generated code to call them?  How does it do that if they are internal?

**Comment by CyrusNajmabadi** [comment]
THey're called directly inside ValueTuple.  Which lives in a layer that has access to them.

Anonymous types do not call the helpers (as they're in your own assembly).  As such they emit the same code directly that i'm emitting.

**Comment by Pilchie** [comment]
😿 @terrajobst - can we think about making those helpers accessible in some mythical future framework?

**Comment by CyrusNajmabadi** [comment]
Specifically, this would be about exposing: https://github.com/dotnet/corefx/blob/8f824ba00f5656436f7063da49fb0ac94eff8566/src/Common/src/System/Numerics/Hashing/HashHelpers.cs

**Comment by terrajobst** [comment]
We have a proposal for it here:

https://github.com/dotnet/corefx/issues/14354

**Comment by Pilchie** [comment]
Moving to Unknown to consume these when the Fx supports it.

**Comment by morganbr** [comment]
The .NET Core ```HashCode.Combine``` API has been merged in https://github.com/dotnet/corefx/pull/25013. It should be a much higher quality hash than Roslyn generates right now and hash nearly as quickly (as well as making cleaner generated code).

For projects targeting .NET Core 2.1, you should be able to start using it. Hopefully it'll show up in other frameworks soon.

**Comment by CyrusNajmabadi** [comment]
Thanks @morganbr .  Should be easy for Roslyn to incorporate support for this in projects that are targetting these libraries.  If not, the code can then fallback to how it currently works.

Cheers!
