### ISSUE TITLE
Would be useful to have a feature that implements IEquatable<T> and/or ==/!= for a type.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#17650]
This likely should play along with the existing Generate-Equals feature.

**Comment by AdamSpeight2008** [comment]
Related Topic #2149

**Comment by CyrusNajmabadi** [comment]
@AdamSpeight2008 how are these related?  thanks!

**Comment by AdamSpeight2008** [comment]
@CyrusNajmabadi 
In the linked issue I proposed `==` and `!=` (in VB `=` and `<>`) for type, to enable using `Select Case` matching over types. But because that aspect of Roslyn is PCL it wasn't supported. 

> (Remember, PCL just reflects the underlying platforms, so if something is missing from PCL it's because it's missing from one of the platforms you are targeting)
>
> @nguerrera did some investigation around this, and we weren't happy with the semantics of the equality operations. Nick can provide more details.

**Comment by weltkante** [comment]
Clarifying: the linked issue is about adding ==/!= to the `System.Type` class (the ==/!= operators aren't defined on `System.Type` for PCL projects). Can't tell if that is related to this issue at all.

**Comment by bkoelman** [comment]
Actually I implemented such bits some time ago in the roslyn-analyzers repo. Never got reviewed, though....

https://github.com/dotnet/roslyn-analyzers/pull/1065

**Comment by CyrusNajmabadi** [comment]
Yeah, this is unrelated.  This is about making it easy to generate ==/!= in your own type.  Not anything to do with System.Type.
