### ISSUE TITLE
Should DocumentId, ProjectId and SolutionId be sealed?

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#1765]
Right now DocumentId, ProjectId and SolutionId are not sealed. Should they be?
@mattwar ?

**Comment by jaredpar** [comment]
:+1: 

Looking around there are a number of `public` types that seem like they would be a good fit for `sealed`.  Have we done a review of these types recently?

**Comment by mattwar** [comment]
Yes, the should be sealed.

**Comment by Pilchie** [comment]
Keeping in rc2 since this is a API breaking change, so it's better to take earlier.

**Comment by Pilchie** [comment]
Re-opening to track port to preview branch.

**Comment by Pilchie** [comment]
Ported to preview in #1783.
