### ISSUE TITLE
IDE0006	Error encountered while loading the project

### ISSUE THREAD

**Issue by FlavioSCardoso** [dotnet/roslyn#17667]
**Version Used**: VS Pro 14.0.25431.01

**Steps to Reproduce**:

1. File, New Project, Cross-Platform, Blank Xml App (Xamarin.Forms.Portable)

**Expected Behavior**:
Can't get error information as described on inner instructions or in https://github.com/dotnet/roslyn/wiki/Diagnosing-Project-System-Build-Errors 

**Actual Behavior**:
Get the folowing Warning:	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	App2.Droid		1	Active
After executing instructions to get error information the log file isn't created.

**Comment by Pilchie** [comment]
Can you zip up and attach the log files that did get created?

**Comment by FlavioSCardoso** [comment]
[Monitoramentos.zip](https://github.com/dotnet/roslyn/files/848668/Monitoramentos.zip)
Brand new just created project...

**Comment by Pilchie** [comment]
Wow - I totally missed this :-/.

I just took a look and I see these errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	Monitoramentos		1	Active
Warning		The "XamlCTask" task could not be instantiated from "D:\KevinPi\Downloads\Monitoramentos\Monitoramentos\packages\Xamarin.Forms.2.3.3.193\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20\Xamarin.Forms.Build.Tasks.dll". Could not load file or assembly 'Xamarin.Forms.Build.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)	Monitoramentos			
Warning		The "XamlCTask" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.	Monitoramentos			
```

After I deleted the `packages\Xamarin.Forms.2.3.3.193\` and did a new restore from NuGet, things worked as expected.  I suspect a file in the packages directory is corrupt somehow.

**Comment by Pilchie** [comment]
@nwudoebuka take a look at https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md for information about design time builds and how to capture logs that should give more detail about why they are failing.
