### ISSUE TITLE
Extension Methods for Tuple Type?

### ISSUE THREAD

**Issue by RandyBuchholz** [dotnet/roslyn#17663]
VS2017/C#7
### Description
You can write an extension method on a specific tuple, but what about on all tuples?
```
public static string TupleExtension( this (int One, int Two) tup) { ... }
```
`var ans = (1, 1).TupleExtension();`  Seems to work fine for all cases of (int, int). The use may be limited, and it gets messy to use many of these.

What about extensions on all tuples?
```
var a = (1, 1).Method();
var b = ("Hello", 6).Method();
```
This would be helpful for writing things like conversions - `.ToSomething()`.

`public static string TT(this Tuple t) {...}` is invalid for Tuple. Is there a way write an extension that applies to all tuple instances? I wanted to ask here before putting in a feature item in the language repo.

**Comment by DavidArno** [comment]
You just have to make it a generic extension method:
```cs
public static string TupleExtension<T1, T2>(this (T1 p1, T2 p2) tuple) => ...
```

**Comment by RandyBuchholz** [comment]
I'm trying to go the other way, and avoid the "Of course, you'll need one per each type of tuple".

Making an extension on a specific/generic signature works fine (and it doesn't seem necessary to make it a generic). What I am looking for is a way to write an extension that shows up on all tuples. Something like
`public static string TupleExtension( this (()) tuple) => ...` which would then be available anytime the tuple syntax was encountered.

```
var a = (1, 5, 7).TupleExtension();

// Same extension, written once, different signature
var b = ("One", Two").TupleExtension();
```

**Comment by DavidArno** [comment]
The nearest you could get to that would be to have the extension method extend `ITupleInternal`, which all `ValueTuple<...>` types implement ... but you can't as `ITupleInternal` (as its name suggests) is marked as `internal`. 

So unfortunately, "Of course, you'll need one per each type of tuple" remains a contraint on what you want to achieve.

**Comment by RandyBuchholz** [comment]
That's for the thorough explanation, David!
