### ISSUE TITLE
typeof((tuple)) Incomplete

### ISSUE THREAD

**Issue by RandyBuchholz** [dotnet/roslyn#17662]
### Description
Getting the type of a tuple using typeof() does not function completely. (VS2017/C#7)
`Type tupletype = typeof(int One, int Two);` does not bring One, and Two into the DeclaredFields collection. They come over as Item1, Item2. This is limiting in some scenarios.

### Example
Currently, you can create a limited "Pseudo Type" using tuples. You can't "new" a tuple, but you can create one from a "template" by declaring a type instance and using Activator. 
```
class Program {
	public static Type OhmsTriangle =  typeof(( int Voltage, int Current, int Resistance ));
	static void Main(string[] args) {
		var ot = Activator.CreateInstance(OhmsTriangle);
	}
}
```
The problem is that you lose the naming information from the tuple. The information is lost in the typeof() step.
Expected ot -> ( int Voltage, int Current, int Resistance). 
Actual ot -> (int, int, int).
This prevents things like comparisons.

I can't test the Activator step, so I don't know if it will work correctly. But, because I get (int, int int) and not (Item1, Item 2, Item3) it doesn't seem so. Unless the name is suppressed if it is "Item".

### Related
If this was working, it would be nice to have an extension on tuple instances to shorthand it. 
``` var ot = OhmsTriangle.New();```

**Comment by DavidArno** [comment]
It's unclear what you are trying to achieve here. Firstly, 
```cs
typeof(( int Voltage, int Current, int Resistance ));
```
is the same as saying:
```cs
typeof(ValueTuple<int, int, int>);
```
The `(x, y)` syntax, and the names `x` and `y` are just compiler sugar placed over those `ValueTuple` types.
```cs
var ot = Activator.CreateInstance(OhmsTriangle);
```
is the same as saying:
```cs
var ot = new ValueTuple<int,int,int>();
```

But it's unclear why you are doing this anyway. You can "new" tuples, with names other than `Item1` etc, just use the `()` syntax:
```cs
class Program 
{
    static void Main(string[] args) 
    {
        var ot = (Voltage:0, Current:0, Resistance:0);
    }
}
```

**Comment by RandyBuchholz** [comment]
Sorry if I wasn't clear. I added a use case about the issue/item that may have confused this.

What I see as a "defect" is that typeof(tuple) doesn't retain the names of the elements. Your explanation helps understand why. I see that it is the de-sugaring of the tuple syntax that looses the name info, and that is why it doesn't work. But shouldn't it work?

As you said, we are doing `var t = typeof(ValueTuple<int, int, int>)`. If I look at t, I see the array - `DeclaredFields` has the names of the generic parameters as fields. The names of these fields are in `DeclaredFields[I].Name`. The names created are item-based - Item1, Item2. These get populated somehow. If the names can be made available, shouldn't it use them?

 This doesn't work, but conceptually, it could de-sugar to something like 
``` 
( "Voltage", "Current", "Resistance")typeof(ValueTuple<int, int, int>)
```
This could be implemented with a overload of typeof (though the docs say it can't be overloaded)
```
// overload
typeof(object target, string[] genericNames)

// de-sugared 
typeof(ValueTuple<int, int, int>, new string[]{ "Voltage", "Current", "Resistance" } )
```
The typeof overload would then populate the `DeclaredFields[I].Name` with the appropriate name.

#### Why
I'm just exploring some things with tuples right now. This is design-side driven. I'll provide a little background, but some of this is more suited for the csharplang repo I think.

I do a lot of modeling, and I create Data Domains to represent types. In a simple form the are like if you could do ` class Name : string { }`, but usually much more, like constraints. In my tool, I can assign a Domain to a attribute, and when I preview the code, the domain is replaced with the type I give it. With tuples, my domains can be more complex, similar to `class OhmsTriangle : ( int Voltage, int Current, int Resistance)`.  What I experimenting with is creating something like this in C#. It's a small step towards local types, and almost just templating right now.

As part of this I'm exploring is Type Pointers - they are not actual Types, but they point to and resolve to a type. A use for this is decoupling classes. If I don't use any of the behavior of a class, there is usually no reason to pass it as an object - it is very constraining, and creates unnecessary dependencies. If I only need the data, I can just pass a tuple. In some cases I may want a "Tuple Map" so I can cast what I receive into a contextual or Domain. The ` public static Type OhmsTriangle =  typeof(( int Voltage, int Current, int Resistance ));` serves as a map. Currently I can do `var self = (Name: "Me", Age:15)` and then I can do `var futureSelf = self with (Age = received.Age)` when "with" is implemented.  I don't need a "global" definition of self - each class (sending and receiving) can contain its own.

The type-pointer part comes in for things like return values. I can't do, ` OhmsTriangle = Class.Method();` because OhmsTriangle isn't a true type. With a Type Pointer I might be able to do a form of type substitution. A class could return a Domain or TypePointer.
```
public

**Comment by gafter** [comment]
Two issues here.

First, the syntax `typeof(int x, int y)` isn't valid, because `int x, int y` isn't a type. The type here would be the same thing with parens around it, so with one pair of parens part of the `typeof` syntax, and one pair part of the tuple type, you should be writing `typeof((int x, int y))`.

Second, the purpose of `typeof` is to give you access to the `System.Type` object corresponding to a compile-time type. The names of tuple elements are not part of the `System.Type` object, and so it is intentional that they are lost through this operation.

The code

``` c#
        Console.WriteLine(typeof((int x, int y)));
```

should output

``` none
System.ValueTuple`2[System.Int32,System.Int32]
```
