### ISSUE TITLE
No scrollbar in Code Style preview pane

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#17679]
We should have a scrollbar in this editor, at least if we need it:

![image](https://cloud.githubusercontent.com/assets/312835/23777302/7b9378ca-04e8-11e7-95a4-788aebcdff75.png)

**Comment by reaction1989** [comment]
@Pilchie I have looked into that. It seems that the source which needs to be touched is not in the Roslyn Source.
We have a Content Control here which is located in the GridOptionsPreviewControl.xaml This gets filled with a IWpfTextViewHost.

The Implementation of this is in `Assembly Microsoft.VisualStudio.Text.UI.Wpf, Version=15.0.0.0`

**Comment by Pilchie** [comment]
I'm pretty sure there is an option you can set on an IWpfTextViewost somewhere to get it to display scroll bars.  @KirillOsenkov @olegtk do you remember where off-hand?

**Comment by KirillOsenkov** [comment]
Is the text view missing the Interactive role? Without the interactive role, scroll bar margins won't get picked up:

```
    [Export(typeof(IWpfTextViewMarginProvider))]
    [Name(PredefinedMarginNames.VerticalScrollBarContainer)]
    [MarginContainer(PredefinedMarginNames.RightControl)]
    [ContentType("text")]
    [TextViewRole(PredefinedTextViewRoles.Interactive)]
    [GridUnitType(GridUnitType.Star)]
```
