### ISSUE TITLE
Proposal: PHP-style alternative syntax for all block structures and control statements

### ISSUE THREAD

**Issue by Jehoel** [dotnet/roslyn#17673]
### Problem:

When using C# in a text-templating environment (`.aspx`, Razor/`.cshtml`, T4 `.tt`, _et cetera_) the succinctness of its syntax hinders readability, especially when using C# to template another curly-braces document, such as JSON or JavaScript (and especially in the case of using T4 to generate C#).

When ASP.NET first launched with `.aspx` files in 2001 VB.NET was the modal language (owing to most Classic ASP developers using VBScript) so it was easy to match control block starts with their endings because VB.NET's syntax is very verbose (`If... Then... ElseIf... Else... End If`). As developers move to C# it becomes harder to "eyeball" code, for example:

    <% If someCondition Then %>
    <p><%= "hello, world" %></p>
    <% Else %>
    <%    For i As Integer = 0 To 5 %>
    <p><%= "goodbye, cruel world" %></p>
    <%    Next %>
    <% End If %>

But in C# it's harder to follow if you read in bottom-to-top order as the braces don't identify or at least classify what control block they refer to:

    <% if( someCondition ) { %>
    <p><%= "hello, world" %></p>
    <% } else { %>
    <%    for(int i = 0; i < 5; i++) { %>
    <p><%= "goodbye, cruel world" %></p>
    <%    } %>
    <% } %>

PHP suffered the same problem initially, made all the worse by its longer block-start syntax `<?php ?>`. A solution was introduced in PHP4 with Alternative Syntax for Control Structures: http://php.net/manual/en/control-structures.alternative-syntax.php

In short, since PHP you can specify any block statement using the form:

    <keyword>:
      (block-body)
    end<keyword>;

For example:

    <?php if( $foo ): ?>
    <p><?= "hello, world" ?></p>
    <?php else: ?>
    <?php    for( $i = 0; $i < 5; $i++): ?>
    <p><?= "goodbye, cruel world" ?></p>
    <?php    endfor; ?>
    <?php endif; ?>

### Proposal:

I'm proposing the C# parser accept this alternative form for all C# block and control statement keywords: `if`, `for`, `do`, `while`, `try`, `using`, `checked`, and so on. I see no reason why it wouldn't also be applied to other constructs, such as `namespace` and `class`/`struct`/`interface` as well. It could also work with anonymous functions by reusing the `delegate` keyword (e.g. `delegate(String x): enddelegate;`) though lambda functions, given their inherent brevity, will have no need for this more verbose syntax.

While unrelated to this project, the Razor parser would need to be updated to allow the use of the `end<keyword>;` construct - though perhaps with an explicit `@` signifier to avoid false-positive detection of keywords, for example:

     @if( $foo ):
     <p>@( "hello, world" )</p>
    @else:
        @for( $i = 0; $i < 5; $i++):
    <p>@( "goodbye, cruel world" )</p>
        @endfor;
    @endif;
    
In this contrived short example the proposed alternative syntax has little utility as the entire statement is readable without assistance, but when dealing with many "real-world" examples, like page template render functions stretching into the thousands (or tens of thousands) of lines this syntax would greatly aid readability.

### Negative consequences:

The main risk is keyword/identifier collision, though I imagine very few identifiers are named `endfor` or `endusing` - but this can be mitigated by using context-sensitive keywords (_a la_ Linq's `from`/`where` keywords) such that `endif` is only recognized if it follows a preceding `if():` statement at the same block-depth, for example.

### Addendum Proposal: combine with control-statement-labels:

It has been frequently requested that C# support something like Java's "labelled statements" to allow for the problem of breaking out of nested loops without using `goto`. Java's solution is to prefix the statement with a label, however the syntax is ambiguous between a generic label and a label exclusively for the control statement. I'd like to propose that in C# the label could be embedded within the statement, like so:

    // in curly-brace:
    for labelName( int i = 0; i < 5; i++ ) {
        if( foo ) {
            break labelName;
        }
        bar();
    }

    // in alternative syntax:
    for labelName( int i = 0; i < 5; i++ ):
        if( foo ):
            break labelName;
        endif;
        bar();
    endfor;

    // in inline syntax:
    for labelName( int i = 0; i < 5; i++ ) if( foo ) break labelName; else bar();

The use of at least one whitespace character between the `for` means it won't conflict with `foreach`, for example.

This can be applied to other non-loop statements to allow for a "break anywhere" feature which help eliminate the excess syntax required for the "break from if` problem: http://stackoverflow.com/questions/17727655/how-to-break-out-of-an-if-statement-from-a-boolean-inside-the-if-statement

    if( foo ) {
        doSomething1();
        if( bar ) {
            doSomething2();
            if( baz ) {
                doSomething3();
            }
        }
    }

Becomes:

    if outer( foo ):
        doSomething1();
        if( !bar ) break outer;
        doSomething2();
        if( baz ) break outer;
        doSomething3() break outer;
    endif;

...which is more readable to those who prefer the "many `return`" style, and helps eliminate excessive helper functions.

**Comment by gafter** [comment]
Language design discussions now take place at https://github.com/dotnet/csharplang
