### ISSUE TITLE
Many dialog-based integration tests are failing

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#17680]
https://github.com/dotnet/roslyn/pull/17655#issuecomment-285482257
https://github.com/dotnet/roslyn/pull/17654#issuecomment-285496301
https://github.com/dotnet/roslyn/issues/17640

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving out.  But we need to nevertheless move forward on fixing dialog tests.
