### ISSUE TITLE
Need tests to ensure edit-and-continue works with expression-bodied methods

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#17681]
Specifically
- [ ] expression-bodied property accessors
- [ ] expression-bodied event accessors
- [ ] expression-bodied constructors
- [ ] expression-bodied destructors
- [ ] expression-bodied operators

**Comment by ivanbasov** [comment]
Decided that we will not support EnC conversion from/to blocks/expression bodies for constructors, destructors and events.
