### ISSUE TITLE
Suggestion: Find-Refs on a setter should only find write-references to that property.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#17684]
Ported from https://developercommunity.visualstudio.com/content/problem/23315/find-references-for-a-setter-also-lists-results-fo.html

**Comment by kentcb** [comment]
Looking forward to this!

**Comment by jcouv** [comment]
I'm taking a stab at this (PR https://github.com/dotnet/roslyn/pull/23276, WIP)

**Comment by IanKemp** [comment]
Looks like this is addressed by #25561, which is set to ship in 15.8!

**Comment by CyrusNajmabadi** [comment]
This has been done.  If you do find-refs from an accessor we filter down to only usages of that accessor.

**Comment by CyrusNajmabadi** [comment]
PR is here: https://github.com/dotnet/roslyn/pull/28231
and went into the 16.0 milestone.  So i would imagine it will be in an upcoming 16.0 release.  Cheers!

**Comment by jcouv** [comment]
My understanding is this change will first be visible in dev16 preview 2.

**Comment by jnm2** [comment]
😱 Is Preview 1 out and about yet?

**Comment by jinujoseph** [comment]
yes it will be part of 16.0.Preview2
