### ISSUE TITLE
Visual Studio Crashes while editing C#

### ISSUE THREAD

**Issue by a-jaeger** [dotnet/roslyn#17696]
Visual Studio 2015 Enterprise, Version 14.0.25431.01 Update 3 crashes periodically on unspecific actions in the C# editor. It seems to be while refreshing intelli sense information.

The following information is taken from the event log (german):
```
Name der fehlerhaften Anwendung: devenv.exe, Version: 14.0.25420.1, Zeitstempel: 0x57685d85
Name des fehlerhaften Moduls: unknown, Version: 0.0.0.0, Zeitstempel: 0x00000000
Ausnahmecode: 0xc00000fd
Fehleroffset: 0x06770e7a
ID des fehlerhaften Prozesses: 0x2eb0
Startzeit der fehlerhaften Anwendung: 0x01d298e743fc36da
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Pfad des fehlerhaften Moduls: unknown
Berichtskennung: bebd178c-a2b7-4887-a35f-eea303382645
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:
```

**Comment by jasonmalinowski** [comment]
@tmeschter, can we get some information out of that report?

**Comment by tmeschter** [comment]
@jasonmalinowski Sorry, I'm unable to find any crash information from those details.

**Comment by jasonmalinowski** [comment]
@a-jaeger If you're still seeing the issue, can you report the issue through Help > Send Feedback > Report an Issue? That'll capture some extra logs that we can better use to figure this out. Feel free to put my GitHub username in the report so that way I can more easily find it.

**Comment by a-jaeger** [comment]
I have gotten the issue once more. I sent a report as mentioned by @jasonmalinowski. I additionally found a corresponding Report.wer. Maybe this is useful for you.
[Report.wer.txt](https://github.com/dotnet/roslyn/files/850137/Report.wer.txt)

**Comment by a-jaeger** [comment]
I got the error once more and was able to gather more information out of th event log. I want to provide this information to you.

```
Name der fehlerhaften Anwendung: devenv.exe, Version: 14.0.25420.1, Zeitstempel: 0x57685d85
Name des fehlerhaften Moduls: unknown, Version: 0.0.0.0, Zeitstempel: 0x00000000
Ausnahmecode: 0xc00000fd
Fehleroffset: 0x319480db
ID des fehlerhaften Prozesses: 0x2060
Startzeit der fehlerhaften Anwendung: 0x01d2ba66f9377a50
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Pfad des fehlerhaften Moduls: unknown
Berichtskennung: 44303b7c-ab3a-42e4-91c4-7b928952e56a
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```
Additional Information from the event log:
```
Fehlerbucket 108253151518, Typ 1
Ereignisname: APPCRASH
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: devenv.exe
P2: 14.0.25420.1
P3: 57685d85
P4: StackHash_199c
P5: 0.0.0.0
P6: 00000000
P7: c00000fd
P8: PCH_D3
P9: 
P10: 

Angefügte Dateien:
\\?\C:\Users\developer\AppData\Local\Microsoft\VSCommon\14.0\SQM\sqmdata.cvr
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER227A.tmp.WERInternalMetadata.xml

Diese Dateien befinden sich möglicherweise hier:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_devenv.exe_783ca57d3f5f0e771c3ac3da08d6b919b2859a9_12aa736e_1e7551e6

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: 44303b7c-ab3a-42e4-91c4-7b928952e56a
Berichtstatus: 0
Bucket mit Hash: d0a069ee5a439060c11bbfa01400e005
```
By now i was able to find two of the mentioned files: sqmdata.cvr and Report.wer. I have added them to the pos
[additional_files.zip](https://github.com/dotnet/roslyn/files/946189/additional_files.zip)

t.

**Comment by MattGertz** [comment]
@tmeschter Would this repro in Dev15 also (does it match any known stacks)?

**Comment by tmeschter** [comment]
@MattGertz Impossible to say at this time as we don't have a stack trace. I've requested further information from Watson so that if the Dev14 crash happens again we'll be able to capture a call stack, and then see if it is happening in Dev15.

**Comment by a-jaeger** [comment]
I got the error once more. This time I could reproduce it for some steps to do. So I recorded the steps to reproduce and sent it via the vs reporting system. Maybe there is now more information for you @jasonmalinowski.

**Comment by jasonmalinowski** [comment]
Closing; the report data is too old now to be actionable, unfortunately.
