### ISSUE TITLE
Code completion appears for lambda parameter name

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/roslyn#17697]
**Version Used**: 
VS2017
**Steps to Reproduce**:

1. 
```
using System;

class Foo
{
	public static void Main (string[] args)
	{
		new Action<int> (($
	}
}
```
2. Remove $ and start typing name of lambda parameter

**Expected Behavior**:
No code completion should be shown
**Actual Behavior**:
Code completion shows up:
![image](https://cloud.githubusercontent.com/assets/774791/23788887/d4ece8bc-0578-11e7-881d-b5ed4119543e.png)

**Comment by miloush** [comment]
First, that's not true. For example, you can reference a method:
```C#
public void Method(int i) { }

public void Test() { var a = new Action<int>((Method)); }
```
The method can be qualified with namespace/type if it is a static one.

Second, the completion is in suggestion mode, so you can freely type whatever you need and it won't be overtaken with anything from the list.

**Comment by DavidKarlas** [comment]
```
using System;

class Foo
{
	public static void Main (string[] args)
	{
		new Action<int,int> ((x,$
	}
}
```
Maybe in this case? But ye since it's in suggestion mode you can close this.

**Comment by jasonmalinowski** [comment]
You need to trigger completion there because you could be typing the type of a lambda parameter. For example:

            var x = new Action<int>((int y) => { });

We pop that completion because you might be typing "int".

**Comment by jasonmalinowski** [comment]
@DavidKarlas That is by design then, was this getting in your way or it just seemed like a curiosity?

**Comment by DavidKarlas** [comment]
I just didn't see use for it... Didn't consider to use (int y) for lambda...
