### ISSUE TITLE
Code completion appears for namespace name

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/roslyn#17699]
**Version Used**: 
VS2017
**Steps to Reproduce**:

1. 
```
using System;

namespace $
```
2. Remove $ and start typing name of namespace

**Expected Behavior**:
No code completion should be shown
**Actual Behavior**:
Code completion shows up:
![image](https://cloud.githubusercontent.com/assets/774791/23789008/53cf9896-0579-11e7-871d-3ea6215f1008.png)

**Comment by CyrusNajmabadi** [comment]
This is by design.  We now actually help you write the namespace since you may be repeating an existing namespace that you've written elsewhere.

**Comment by DavidKarlas** [comment]
Actually it probably makes sense to show existing namespaces in project but not #if, #region...

**Comment by CyrusNajmabadi** [comment]
These are snippets.  They always show up as long as completion is shown.

**Comment by DavidKarlas** [comment]
Ok, closing as invalid
