### ISSUE TITLE
Proposal: use interface keyword to automatically wrap concrete classes

### ISSUE THREAD

**Issue by mmkal** [dotnet/roslyn#17690]
Interfaces are fine when they represent a contract that could be implemented in many ways. But very often, they will be used to wrap a single concrete class, simply because interfaces work better with Dependency Injection and mocking frameworks.

You'll often see code like this:
```C#
// GreetingPrinter.cs
public class GreetingPrinter
{
  public void Greet(string person) => Console.WriteLine("Hello " + person);
}
// IGreetingPrinter.cs
public interface IGreetingPrinter
{
  public void Greet(string person);
}
// MyClass.cs
public class MyClass
{
  private readonly IGreetingPrinter _greetingPrinter;
  public MyClass(IGreetingPrinter greetingPrinter)
  {
    _greetingPrinter = greetingPrinter;
  }
  public void DoStuff()
  {
    Console.WriteLine("doing stuff");
    _greetingPrinter.Greet("Bob");
  }
}
// MyClassTests.cs
public class MyClassTests
{
  private readonly MyClass _myClass = new MyClass(Mock<IGreetingPrinter>());
  [Test]
  public void DoStuff_Greets()
  {
    _myClass.DoStuff();
    Mock<IGreetingPrinter>().Verify(gp => gp.Greet("Bob"));
  }
}
```

This works, but having to create the `IGreetingPrinter` interface is an unnecessary overhead. People rely on their IDE to do it (extract interface), and it's not always simple to change the signature of a public method without tools like Resharper. Sometimes parameter names can get out of sync, or methods are added to the class but not the interface. In cases like this, it would be preferable to bypass the `IGreetingPrinter` definition completely, and use the `interface` keyword to ask the compiler to *generate* us an interface with the concrete class's public properties and methods:

```C#
// GreetingPrinter.cs
public class GreetingPrinter
{
  public void Greet(string person) => Console.WriteLine("Hello " + person);
}
// MyClass.cs
public class MyClass
{
  private readonly interface<GreetingPrinter> _greetingPrinter;
  public MyClass(interface<GreetingPrinter> greetingPrinter)
  {
    _greetingPrinter = greetingPrinter;
  }
  public void DoStuff()
  {
    Console.WriteLine("doing stuff");
    _greetingPrinter.Greet("Bob");
  }
}
// MyClassTests.cs
public class MyClassTests
{
  private readonly MyClass _myClass = new MyClass(Mock<interface<GreetingPrinter>>());
  [Test]
  public void DoStuff_Greets()
  {
    _myClass.DoStuff();
    Mock<interface<GreetingPrinter>>().Verify(gp => gp.Greet("Bob"));
  }
}
```

The compiler does the boring, easily automate-able work for us of creating the interface. It doesn't clutter up our file system or the class definition file. It could even be used to define new classes implementing the same contract:
```C#
public class EnthusiasticGreetingPrinter : interface<GreetingPrinter>
{
  public void Greet(string person) => Console.WriteLine("HELLO " + person.ToUpper());
}
```
 The `interface` keyword is already reserved, so this addition should be backwards compatible.

Thoughts? Could this work?

**Comment by DavidArno** [comment]
Hi, language feature requests like this should now be posted to the [csharplang repo](https://github.com/dotnet/csharplang).

**Comment by mmkal** [comment]
My bad, have copied this [there](https://github.com/dotnet/csharplang/issues/245).
