### ISSUE TITLE
Different colors for parameters, locals and captures

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#17703]

**Comment by miloush** [comment]
Capturing variables is a non-obvious concept and visually distinguishing them sounds like a great idea to me. Not sure how to make it fit well with current black resp. white color though.

**Comment by alrz** [comment]
Different shades of gray works for me.

**Comment by miloush** [comment]
Shades of gray would likely interfere with "this can be simplified" shading.

**Comment by 0xd4d** [comment]
Dupe of #3976

**Comment by alrz** [comment]
@0xd4d Thanks, so it was not a deja vu as I thought it to be.
