### ISSUE TITLE
Allow Generic Attributes

### ISSUE THREAD

**Issue by Mafii** [dotnet/roslyn#17701]
As explained in [this ]( http://stackoverflow.com/a/294259/5962841) answer by Jon Skeet (also paraphrasing Eric Lippert) it is mentioned, that implementing Generic Attributes should be available in terms of IL - they just aren't used in C#-  or actually actively blocked (the compiler doesn't allow them).

Some time has passed since then - from my view it makes sense to bring this idea up again.

The feature of generic attributes adds value because it makes the langue more generic and more flexible.

As an example, this could be:

    [AttributeUsage(AttributeTargets.Field)]
    private class TypeAssociationAttribute : Attribute
    {
      public Type AssociatedType { get; set; }
    }

But with generic attributes it could be like this:

    [AttributeUsage(AttributeTargets.Field)]
    class TypeAssociationAttribute<TType> : Attribute
    {
    }

Also, the generic argument would allow me to put constraints onto the type.

I think it's fair to say it would improve the language,
Wheter it's effort is worth it, is obviously desicion of the design team. I think it is.

**Comment by DavidArno** [comment]
Hi, language feature requests like this should now be posted to the [csharplang repo](https://github.com/dotnet/csharplang).

**Comment by gafter** [comment]
This idea is being tracked at https://github.com/dotnet/csharplang/issues/124 where you are welcome to repeat this and start more discussion.

**Comment by Mafii** [comment]
@gafter thank you so much for your work. Sorry for the inconvenience.
