### ISSUE TITLE
(Named) value tuples and Linq

### ISSUE THREAD

**Issue by myblindy** [dotnet/roslyn#17713]
**Steps to Reproduce**:
```
var list = new(int value, string name)[] { (1, "a"), (2, "b"), (3, "c") };
var item = list.FirstOrDefault(w => w.value > 5);
```

**Expected Behavior**:
I would expect `item` to be `(int, string)?` so I can use `??` or test of failure in a meaningful way.

**Actual Behavior**:
What I actually get is an actual value type with default values inside. This may or may not be useful (and indeed it is not in my case), since 0/null values inside the tuple can easily be valid entries.

This is worsened by functions such as this:
```
        internal static TValue SafeTryGet<TKey, TValue>(this IDictionary<TKey, TValue> list, TKey key) =>
            key != null && list.TryGetValue(key, out TValue ret) ? ret : default(TValue);
```
 There's no (obvious) way of overloading this function to return a nullable type for value types and a plain `default` for classes. The closest I've gotten is with a second helper function, but this isn't anywhere as clean as it could be:
```
        internal static TValue? SafeTryGetValue<TKey, TValue>(this IDictionary<TKey, TValue> list, TKey key) where TValue : struct =>
            key != null && list.TryGetValue(key, out TValue ret) ? ret : new TValue?();
```

**Comment by alrz** [comment]
That's not how `FirstOrDefault` works, it literally returns `default(T)` where `T` is `(int, string)`.

You could use this instead:
```cs
var list = new(int value, string name)?[] { (1, "a"), (2, "b"), (3, "c") };
var item = list.FirstOrDefault(w => w.value > 5);
```

**Comment by gafter** [comment]
This appears to be a question about the way the `FirstOrDefault` API works. I think @alrz has answered it.

**Comment by myblindy** [comment]
It's more about the limitation of the API to work with the new named tuples. I know it returns `default(T)`, I'm just saying that's not good enough when working with value types. It wasn't really an issue until now mostly because we (at least I) used classes, but named tuples are values and all these `*OrDefault()` functions don't return useful information for them.
