### ISSUE TITLE
Intellisense suggests full type name when it is not necessary

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#17729]
**Version Used**: Visual Studio 2017 15.0.0-RTW+26228.4

**Code to Reproduce**:
```csharp
using System.Collections.Generic;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace N
{
    public class C
    {
        public static void M()
        {
            List();
            List<string> items = new $$
        }
    }
}

namespace Microsoft.CodeAnalysis.CSharp
{
    public static class SyntaxFactory
    {
        public static List<T> List<T>() { return null; }
    }
}
```
**Expected Behavior**:
```csharp
List<string> items = new List<string>();
```
**Actual Behavior**:
```csharp
List<string> items = new System.Collections.Generic.List<string>();
```

**Comment by Pilchie** [comment]
Hmm - I'm unable to reproduce this with recent bits. @JosefPihrt can you still reproduce it?

**Comment by JosefPihrt** [comment]
@Pilchie I can still reproduce it with latest version (15.1.0+26403.3).

It could be caused by the fact that SyntaxFactory contains method **List**. So intellisense thinks that it cannot use **new List** and instead it uses **new System.Collections.Generic.List**.

**Comment by Pilchie** [comment]
Yes, you need to have a generic method with the same name.  Updated description with standalone repro.

**Comment by Pilchie** [comment]
Given the limited nature of the problem, I'm okay with this.

**Comment by CyrusNajmabadi** [comment]
Not repro on latest main:

![image](https://user-images.githubusercontent.com/4564579/152592020-3da041a5-a55b-4120-b88c-f01c78637c12.png)
