### ISSUE TITLE
I can not find all references for the symbol

### ISSUE THREAD

**Issue by yeaicc** [dotnet/roslyn#1772]
(Sorry, my English is very poor....)
When i want to find all refs for a symbol like this:
```C#
var refs = SymbolFinder.FindReferencesAsync(symbol, solution).Result;
```
I found 8 refs.In fact,i found 9 refs in Visual Studio.
Is it ? bug?

**Comment by yeaicc** [comment]
In fact,all refs in a .cs file

**Comment by pharring** [comment]
@yeaicc Thanks for the bug report. Please can you give a more complete repro? Note that Visual Studio lists the definition as well as any references which may be why you're seeing 9 total 'references'.

**Comment by yeaicc** [comment]
Yes,I got it.Visual Studio lists the definition .....

Thank you so much
