### ISSUE TITLE
We should provide refactorings that convert to patterns *and* suggest appropriate names.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#17727]
It would be great if we could offer a refactoring in a place like this:

```c#
            if (symbol is IMethodSymbol)
            {
                symbol = ((IMethodSymbol)symbol).PartialImplementationPart ?? symbol;
            }
```

It would offer to convert this to something like:

```c#
            if (symbol is IMethodSymbol method)
            {
                symbol = method.PartialImplementationPart ?? symbol;
            }
```

The challenge here is offering a good name to the user.  @rchande If we can take all the name generation logic and make an API for it that would be super helpful.  We could then:

1. pick a good initial name suggestion.
2. have this start an inline rename session.
3. pop up the completion list with alternative names we thought of.

**Comment by Pilchie** [comment]
Agreed.  We should have the pieces necessary for 1 and 2 already based on how introduce local works, right?

**Comment by CyrusNajmabadi** [comment]
I think i'd like all our 'introduction' tools to go through the same API (that i hope @rchande can build).  That way we can pick a good default name, but also offer a set of good options for people that want to use a different name.
