### ISSUE TITLE
VB auto-completion on parameter names introduces duplicate :=

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#17730]
Seems to me like the auto-completion should be smart and not produce the `:=` where there is already one at the insertion point.

![image](https://cloud.githubusercontent.com/assets/12466233/23818738/0c400832-05b3-11e7-83d2-a0690e9a173f.png)

![image](https://cloud.githubusercontent.com/assets/12466233/23818744/1cfa608c-05b3-11e7-9118-5b8771603060.png)

![image](https://cloud.githubusercontent.com/assets/12466233/23818748/292c9fb4-05b3-11e7-9137-fef01df16843.png)

**Comment by jasonmalinowski** [comment]
@rchande is there a reasonable fix here?

**Comment by CyrusNajmabadi** [comment]
Would take a small community fix on this.

**Comment by paul1956** [comment]
@CyrusNajmabadi if the code is in VB that needs to be fixed, and you can point out the file, and I can start in December I would take it and add tests as well. 

Of all the stuff you closed this is the only one I have ever seen.

**Comment by CyrusNajmabadi** [comment]
@paul1956 it would be in one of our vb completion providers.

**Comment by genlu** [comment]
No longer repro. Now we only show the item w/o `:=` in this context
