### ISSUE TITLE
 Bug: C#. Find all references doesn't work with "static bool operator =="

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#1773]
If you have a class with an explicit "operator ==", then "Find All References" doesn't work (it returns no results).

It looks like VS 2013 behaved the same way, so it's not a regression, but it is surprising.

Note that CodeLens finds the references OK.

**Comment by Pilchie** [comment]
There are a variety of "implicit references" that we would like to be able to find but don't currently.

**Comment by jasonmalinowski** [comment]
The engine supports this, there's just a bug in invoking it on an operator's definition where we don't correctly find the symbol to search for.

**Comment by jasonmalinowski** [comment]
Fixed by #2491.
