### ISSUE TITLE
Move Roslyn over to .xlf for localization

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#17731]
Right now we still using some legacy localization tools for building our localization for Roslyn that has a few bad impacts:

1. The localizations themselves are held elsewhere.
2. We can't build our localized setup packages in our current build.
3. Insertions can potentially get flaky because of the previous item.

We should move to the newer .xlf-based system, once the remaining concerns are understood there.

**Comment by tmat** [comment]
Once this is done, delete LOC files from Razzle and remove compiler files from Roslyn CoreXT package.

**Comment by nguerrera** [comment]
The remaining concern was that the xlf process had manual steps that I did not want to spread to more repos, but the automation tooling for this is now implemented: https://github.com/dotnet/xliff-tasks :)

I'm in the process of rolling out the automation to the 5 repos that already use xlf starting with dotnet/sdk#1291. Once that's done, I'd like to give it a bit of time to bake, and then we can move roslyn over.

**Comment by jasonmalinowski** [comment]
Going to close this since xlf was done. Will create a more detailed set of items for the remaining cleanup.
