### ISSUE TITLE
LanguageVersion enum should specify a type.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#17747]
Shouldn't we have a type specifier on the `Language Version` [enum](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Compilers/VisualBasic/Portable/LanguageVersion.vb#L9)? eg
 ```vbnet
   Public Enum LanguageVersion As Integer
        [Default] = 0
        VisualBasic9 = 9
        VisualBasic10 = 10
        VisualBasic11 = 11
        VisualBasic12 = 12
        VisualBasic14 = 14
        VisualBasic15 = 15
        Latest = Integer.MaxValue
    End Enum
```

**Comment by gafter** [comment]
The short answer is "no". The VB language defines the type as `Integer`, and there is no reason to specify it unless a different underlying type is wanted.
