### ISSUE TITLE
Is there any plan for 64bit VisualStudio?

### ISSUE THREAD

**Issue by xieguigang** [dotnet/roslyn#17757]
**Version Used**: 

The latest Vs2017 release 

**Steps to Reproduce**:

Coding a large VisualBasic project may takes more than 2GB memory, and vs crashed.....

![qq 20170312183900](https://cloud.githubusercontent.com/assets/9410171/23831044/d83d2b3a-0753-11e7-998a-3661222fe215.png)

**Comment by shaggygi** [comment]
@xieguigang Saw this the other day if it helps.

https://www.reddit.com/r/programming/comments/5ye9oa/why_visual_studio_isnt_64bit/

**Comment by jasonmalinowski** [comment]
@xieguigang If you are seeing crashes, please use Help > Send Feedback > Report a Problem. That will help us collect some information so we can see why you're running out of memory. There isn't a 64-bit version of Visual Studio 2017, so we'll want to see why you're having issues here.

**Comment by whoisj** [comment]
@xieguigang VS can consume up to 3 GiB of RAM (Windows is "cool" like that) even if > 2 GiB doesn't make much sense on 32-bit pointers. 😏 Therefore you're only half way to OOM.

**Comment by jasonmalinowski** [comment]
Given @xieguigang is on a 64-bit machine, we can theoretically go up to 4 GB (we are marked as LARGEADDRESSAWARE). If it's crashing around 2 GB that might mean something is churning memory so badly in the GC that it's giving up, and it really wouldn't matter how much memory you had...

**Comment by Pilchie** [comment]
This is not a Roslyn question - https://visualstudio.uservoice.com or https://developercommunity.visualstudio.com are better places for this.
