### ISSUE TITLE
WithStatements not working with VB

### ISSUE THREAD

**Issue by kentcb** [dotnet/roslyn#17753]
NOTE: completely open to this being something I'm doing wrong. I am not at all 💯 sure this is a Roslyn issue. However, the code _does_ work for C#, just not VB.

**Version Used**: 1.3.2

**Steps to Reproduce**:

See exact code [here](https://github.com/kentcb/PCLMock/blob/master/Src/PCLMock.CodeGeneration/Generator.cs#L605). If you grab the entire project and run [this specific test](https://github.com/kentcb/PCLMock/blob/master/Src/PCLMock.UnitTests/CodeGeneration/GeneratorFixture.cs#L29), you'll see that it fails. The output does not include _any_ code in the generated method.

**Expected Behavior**:

Calling `WithStatements` against `SyntaxGenerator` should work with VB as it does with C#.

**Actual Behavior**:

Calling `WithStatements` against VB's `SyntaxGenerator` does not appear to append the statements in any way.

**Comment by gafter** [comment]
Moving to IDE, as `SyntaxGenerator` is in the Workspaces layer.

**Comment by CyrusNajmabadi** [comment]
Hi @kentcb Can you provide a minimal repro that demonstrates the issue?  Thanks!

**Comment by kentcb** [comment]
@CyrusNajmabadi Afraid not. I submitted this issue nearly a year ago. I've linked to relevant code though.

**Comment by CyrusNajmabadi** [comment]
The issue here is that we only have a VB FunctinStatement.  We will need to convert these to their block forms in order to add statements here.

**Comment by CyrusNajmabadi** [comment]
Making as help-wanted.  We would take a PR here to help with this scenario.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
