### ISSUE TITLE
Compiler error when combines throw expression together with generic types and null-coalescing operator

### ISSUE THREAD

**Issue by sgjsakura** [dotnet/roslyn#17754]
**Version Used**: 
Visual Studio 2017
**Steps to Reproduce**:
The following code can reproduce the error:
```C#
public void Test<T>(T value)
{
  var x = value ?? throw new ArgumentNullException(nameof(value));
}
```
**Expected Behavior**:
The above code should be compiled correctly.
**Actual Behavior**:
CS0019: The '??' operator cannot be apply between type `T` and `<throw expression> `

**Comment by 0xd4d** [comment]
Try `public void Test<T>(T value) where T : class`

**Comment by gafter** [comment]
The interaction with the throw expression is a red herring. This also fails, as it should:

``` c#
        var y = value ?? default(T);
```

The problem is that `value` isn't a nullable type or a reference type. Try the suggestion made by @0xd4d .

**Comment by sgjsakura** [comment]
While the C# language sepcification says comparison between an unrestricted genertic value and null is accepable,  and it will returns false if the actual type is non-nullable, it simply returns false. the following code can pass the compilation check:
```C#
var x = (value != null) ? value : default(T);
```

So does it possible to enhance the compiler to accept nul-coalescing for unrestricted genertic value?

Thanks~

**Comment by gafter** [comment]
@sgjsakura Yes, the language specification can be changed to make the compiler support that. Language feature requests are taken at https://github.com/dotnet/csharplang
