### ISSUE TITLE
Generate Type not appearing the First time Ctrl+. in the Attribute List Context

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#1776]
Paste the below code

```
Class C
    <System.CLSCompliant(False), Foo>
    Dim foo As Integer
End Class
```

Note that the `Foo` in the `AttributeList` Context is with the Capital 'F'. Now press 'ctrl + dot', to Generate Type `Foo`. Instead of getting the codefix to generate type, we see that 'Foo' gets modified to 'foo'. Issuing 'ctrl + dot' again shows the codefix to generate type 'foo'.

Expected: Generate Type for `Foo` when 'ctrl + dot' was issued the first time

**Comment by srivatsn** [comment]
Presumably adding the error that shows up for tis case to generate type should fix this issue.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  Closing out as so much of these systems has been modified in the last 7 years that it likely is just fixed now.
