### ISSUE TITLE
WinForms Designer Bug

### ISSUE THREAD

**Issue by Hosch250** [dotnet/roslyn#17765]
**Version Used**: VS 2017

**Steps to Reproduce**:

1. Open a solution with a WinForms control.
2. Open a WinForms control in the designer.
3. Select any control.

**Expected Behavior**:
Ideally, VS would populate the Properties window with the information, do whatever else it does, and continue working.

**Actual Behavior**:
VS locks up so hard I have to force-close it with the Task Manager after giving it a couple minutes to unlock.

**Comment by Pilchie** [comment]
Can you please start a second instance of VS while it is hung and use the send-feedback link in the title bar to report this? For one thing, this is likely not a roslyn issue, but additionally, doing that will capture a memory dump that will help us investigate the hang.
