### ISSUE TITLE
Custom tuple variable names are not specified in API response

### ISSUE THREAD

**Issue by ChuckkNorris** [dotnet/roslyn#17777]
**Version Used**: 
.NET Core 1.1.1

**Steps to Reproduce**:

1. Create HTTP Get method in Controller returning a Tuple
```
[HttpGet]
public (string firstName, string lastName) Get() {
   return ("Tom", "Hanks");
}
```

2. Call Endpoint and view Result
`{ item1: "Tom", item2: "Hanks" }`

**Expected Behavior**:
Should return a json object with the keys named according to what was specified in the method.
`{ firstName: "Tom", lastName: "Hanks" }`

**Actual Behavior**:
`{ item1: "Tom", item2: "Hanks" }`

**Comment by bbarry** [comment]
I think this would need to be an asp.net issue, not a compiler issue. Or maybe a JSon.NET issue?

**Comment by ChuckkNorris** [comment]
Ok - I wasn't entirely sure where it should go.

**Comment by ChuckkNorris** [comment]
Moved to here: https://github.com/aspnet/Home/issues/1967
