### ISSUE TITLE
Async and while(true) loop: can't properly step to top of while loop

### ISSUE THREAD

**Issue by xen2** [dotnet/roslyn#17773]
**Version Used**: 
VS2015 RTM Update3 and VS2017 RTM

**Steps to Reproduce**:

1. Create a console project
2. Paste this code:
```
using System.Threading.Tasks;

namespace PdbTest1
{
    class Program
    {
        static void Main(string[] args)
        {
            TestAsync().Wait();
        }

        public static async Task TestAsync()
        {
            while (true)
            {
                Console.WriteLine();
            } // stepping from here to beginning of loop doesn't work
        }
    }
}
```
3.  Try to step TestAsync

**Expected Behavior**:

Can step from brace closing loop `}` to `while (true)`

**Actual Behavior**:

Program doesn't resume stepping until I add again a breakpoint.
Note: this doesn't happen if `TestAsync` is a void function.

I fill it here rather than VS Connect because I suspect it might be related to improper PDB generation.

**Comment by Steedalion** [comment]
@xen2 , I'm not sure what you were trying to do but this should probably be closed now that you better understand async programming.

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  Closing out.
