### ISSUE TITLE
Cannot create list of tuples in assemblies marked as partial trust

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/roslyn#17783]
@jbogard commented on [Sat Mar 11 2017](https://github.com/dotnet/coreclr/issues/10123)

In a .NET 4.5.2 application (console in this case), trying to create a list of tuples results in a method access exception, if the assembly is marked for allowing partial trusted callers:

```csharp
using System;
using System.Collections.Generic;
using System.Security;

[assembly: AllowPartiallyTrustedCallers]

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var t = (i: 5, j: 6);

            var foo = new List<(int i, int j)>
            {
                t,
                (i: 7, j: 8)
            };
            Console.WriteLine(foo[0].i);
        }
    }
}
```

Exception returned:
```
Unhandled Exception: System.MethodAccessException: Attempt by method 'ConsoleApp2.Program.Main(System.String[])' to access method 'System.Collections.Generic.List`1<System.ValueTuple`2<ConsoleApp2.Foo,System.__Canon>>..ctor()' failed.
   at ConsoleApp2.Program.Main(String[] args) in c:\ConsoleApp2\Program.cs:line 17
```

I only see this in .NET 4.5.x applications, not in .NET Core.

---

@stephentoub commented on [Sat Mar 11 2017](https://github.com/dotnet/coreclr/issues/10123#issuecomment-285907844)

cc: @jcouv 

---

@jcouv commented on [Sat Mar 11 2017](https://github.com/dotnet/coreclr/issues/10123#issuecomment-285908163)

Thanks @jbogard for reporting this.
I'm able to repro (copied exception details below). I'll investigate.

```
System.MethodAccessException occurred
  HResult=0x80131510
  Message=Attempt by security transparent method 'ConsoleApp1.Program.Main(System.String[])' to access security critical method 'System.ValueTuple`2<System.Int32,System.Int32>..ctor(Int32, Int32)' failed.

Assembly 'CsPartialTrust, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is marked with the AllowPartiallyTrustedCallersAttribute, and uses the level 2 security transparency model.  Level 2 transparency causes all methods in AllowPartiallyTrustedCallers assemblies to become security transparent by default, which may be the cause of this exception.
  Source=CsPartialTrust
  StackTrace:
   at ConsoleApp1.Program.Main(String[] args) in d:\issues\PartialTrust\CsPartialTrust\Program.cs:line 13
```

**Comment by jcouv** [comment]
I think the APTCA attribute should be set on the ValueTuple assembly (for both targets that include an implementation in the ValueTuple package). Filed corex issue https://github.com/dotnet/corefx/issues/17144

**Comment by jcouv** [comment]
I added the APTCA attribute to System.ValueTuple.dll in the nuget package, for target group netstandard1.0. I expect the package will be re-published to nuget in the .Net Core 2.0 timeframe, but I'm not sure the ETA for that. 
I'll keep the issue open until I find out.

**Comment by jbogard** [comment]
Thanks! Almost sounds like an acronym of a US healthcare bill...

**Comment by jcouv** [comment]
As far as I can tell, .Net Core 2.0 is slated for [Q3 2017](https://github.com/dotnet/core/blob/master/roadmap.md).
I'll go ahead and close the issue now.
