### ISSUE TITLE
VS2017 RTM hangs on "Install Missing Features" dialog

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#17792]
**Version Used**: 
VS2017 RTM

**Steps to Reproduce**:
1. Install Community Edition; during feature selection, do **not** select support for UWP
2. Download sources as zip from https://github.com/bkoelman/fluentassertions
3. Open `FluentAssertions.sln`
4. Accept upgrade dialog
5. Wait for "loading projects" dialog to close
6. Popup "Install Missing Features" shows, but buttons are not clickable (VS hangs)

![image](https://cloud.githubusercontent.com/assets/10324372/23876077/17abfb8c-083c-11e7-9448-9c6d90372906.png)

**Expected Behavior**:
Solution can be loaded successfully.

**Actual Behavior**:
VS hangs. Because it may indicate a deadlock, I attached debugger. On break, it shows the next call stacks:

![image](https://cloud.githubusercontent.com/assets/10324372/23876150/5b6e98e8-083c-11e7-97fd-53dae783125e.png)

Hope this helps!

**Comment by Pilchie** [comment]
Can you choose `Debug->Save Dump As` when it's in this state and make the dump available somewhere?

@brettfo @jmarolf is this anything either of you have heard of?

**Comment by brettfo** [comment]
I haven't seen this one before.  The Install Missing Features dialog is supposed to launch the VS installer with the appropriate options preselected.  Maybe there was an issue with admin/non-admin mode?

**Comment by Pilchie** [comment]
@brettfo - can you set up a VM and try to repro?

**Comment by brettfo** [comment]
I wasn't able to repro this locally.

@bkoelman, can you repro this again and take a dump as per @Pilchie's comment above?  Once you have a dump file, send me an email at brettfo@microsoft.com and I can setup an online location for you to copy the dump since it's probably too big for GitHub.

**Comment by brettfo** [comment]
FYI for anybody following along at home, @bkoelman collected a dump file for me that I'm now looking through.

**Comment by brettfo** [comment]
To finish the follow-up here, the issue has been tracked down to another VS component waiting for something on the UI thread.  I've created an internal bug (398424) and assigned it to the appropriate team.

Thanks to @bkoelman for finding this and taking a dump.
