### ISSUE TITLE
Flaky build: CS7027 happening during builds

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#17812]
We're seeing some random issues in our builds producing

    CSC : error CS7027: Error signing output with public key from file 'D:\j\workspace\windows_debug---b386130b\build\Targets\..\Strong Name Keys\RoslynInternalKey.Private.snk' -- The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020) [D:\j\workspace\windows_debug---b386130b\src\Tools\Source\CompilerGeneratorTools\DeployCompilerGeneratorToolsRuntime\DeployCompilerGeneratorToolsRuntime.csproj]

For example: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit64_prtest/3478/

**Comment by jasonmalinowski** [comment]
This we saw in a PR against dev15.0.x which doesn't have the toolset update so it must be a machine issue somehow.

**Comment by JohanLarsson** [comment]
I started getting this yesterday on one machine.
Using [this minimal repro](https://github.com/JohanLarsson/SignRepro) I get failure every time when I rebuild.

If I delete the bin & obj folder the first build fails and the next is successful.

**Comment by jasonmalinowski** [comment]
@jaredpar or @agocke want to take a look at @JohanLarsson's bug? Marking this as a compiler bug now since it seems to be not exclusive to us.

**Comment by agocke** [comment]
I'll look. I've seen reports of this, but never a reliable repro.

**Comment by agocke** [comment]
Oh, this repro is for Win 7... I'll see if I can find a Win7 machine

**Comment by JohanLarsson** [comment]
It started happening on one Win 7 box the day after updating VS to latest. I updated another Win 7 box with same antivirus but don't have the same problem on that machine. Only seen it once in 50 builds on that machine. The machine that is now having problems has been my primary dev machine for a year and I can't remember seeing this bug once before this week.

**Comment by agocke** [comment]
Could you use something like ProcessExplorer (https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to see if anyone has an open handle to that file the next time you see this?

**Comment by agocke** [comment]
As of right now, the only place I can find us actually reading the key file is http://source.roslyn.io/#Microsoft.CodeAnalysis/StrongName/StrongNameProvider.cs,50, which is a simple `File.ReadAllBytes`. Moreover, this code is basically unchanged for years, as far as I can tell.

**Comment by JohanLarsson** [comment]
Already did, many times, nothing has been locking the file. Renaming the file works also.

**Comment by agocke** [comment]
Hmm. If you totally disable your antivirus, does the problem still reproduce? File.ReadAllBytes seems about as simple as it gets.

**Comment by JohanLarsson** [comment]
It is my work computer and it is a bit locked down not sure how to disable McAfee. The other win 7 box I tried on has the same antivirus and should be updated to the same version so not sure av is the issue. I'll add a console app that reads the sdk to the sln tomorrow. Maybe one that reads in a loop and see if it fails when I build. At home now so can't do it right now. Thanks for the ideas, would be nice to resolve this, keep 'em coming.

**Comment by JohanLarsson** [comment]
Also the repro is just the bare minimum for a signed project to build.

**Comment by jaredpar** [comment]
Ah anti-virus is in play? That is almost certainly the cause then. That is exactly the type of build errors we see when anti-virus programs are executing on the machine.

**Comment by JohanLarsson** [comment]
I have used this machine the last 6000 commits and don't remember seeing the issue before. Could be a weird coincidence that the antivirus was updated at the same time as I updated VS but unlikely as the other machine should have the same update if so. Also if it is an issue with antivirus it would be nice to find a way because at work I can't really opt out of av. I'll google if there is a way to disable temporarily tomorrow.

**Comment by agocke** [comment]
I'm betting it's actually just a race condition that VS updating somehow managed to make more common. It's possible the antivirus and the compiler were always racing and some unrelated change caused them to race faster/closer.

**Comment by JohanLarsson** [comment]
If I change the repro project to new csproj the issue goes away. That indicates that it may not be due to antivirus.

**Comment by agocke** [comment]
Ah, this may be MSBuild! Could you use Process Monitor to trace file system access to this file? I wonder if MSBuild also access this file.

**Comment by JohanLarsson** [comment]
About the race condition: yes it is likely. The machine that is having the issues is a powerhouse desktop. The other machines I have tried on are slower.

**Comment by JohanLarsson** [comment]
Do you have a link for how to trace access to the file?

**Comment by agocke** [comment]
https://docs.microsoft.com/en-us/sysinternals/downloads/procmon to download. I'm not a procmon expert at all, but here's what I usually do:

1. Configure the filer to only trace system calls that include the given file path.
2. Turn on the setting to drop all the messages filtered out.
3. Start system-wide collection.
4. Run the build.
5. Stop system wide collection.

You should now have a list of all Windows calls made that include that file path. There should also be a list of the processes that accessed the file. That's the list I'm interested in 😄

**Comment by JohanLarsson** [comment]
Console app can do `File.ReadAllBytes(snk);` without problems.

```cs
class Program
{
    static void Main()
    {
        var snk = Path.Combine(Directory.GetCurrentDirectory(), "..\\..\\..\\SignRepro\\SignRepro.snk");
        Console.WriteLine(snk);
        File.ReadAllBytes(snk);
        Console.WriteLine("Success!");
        Console.WriteLine("Press any key to exit.");
        Console.ReadKey();
    }
}
```

**Comment by JohanLarsson** [comment]
Here is the procmon dump for a rebuild that failed:
```
"Time of Day","Process Name","PID","Operation","Path","Result","Detail"
"09:00:10,0707773","VBCSCompiler.exe","23292","CreateFile","C:\Git\Kasta\SignRepro\SignRepro\SignRepro.snk","SUCCESS","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened"
"09:00:10,0708289","VBCSCompiler.exe","23292","QueryNetworkOpenInformationFile","C:\Git\Kasta\SignRepro\SignRepro\SignRepro.snk","SUCCESS","CreationTime: 2018-07-18 16:03:19, LastAccessTime: 2018-07-18 16:03:19, LastWriteTime: 2018-07-18 16:03:19, ChangeTime: 2018-07-18 16:03:19, AllocationSize: 1601-01-01 02:00:00, EndOfFile: 1601-01-01 02:00:00, FileAttributes: A"
"09:00:10,0708483","VBCSCompiler.exe","23292","CloseFile","C:\Git\Kasta\SignRepro\SignRepro\SignRepro.snk","SUCCESS",""
"09:00:10,0709503","VBCSCompiler.exe","23292","CreateFile","C:\Git\Kasta\SignRepro\SignRepro\SignRepro.snk","SUCCESS","Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Open No Recall, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened"
"09:00:10,0710685","VBCSCompiler.exe","23292","QueryStandardInformationFile","C:\Git\Kasta\SignRepro\SignRepro\SignRepro.snk","SUCCESS","AllocationSize: 600, EndOfFile: 596, NumberOfLinks: 1, DeletePending: False, Directory: False"
"09:00:10,0710934","VBCSCompiler.exe","23292","ReadFile","C:\Git\Kasta\SignRepro\SignRepro\SignRepro.snk","SUCCESS","Offset: 0, Length: 596, Priority: Normal"
"09:00:10,0711360","VBCSCompiler.exe","23292","CloseFile","C:\Git\Kasta\SignRepro\SignRepro\SignRepro.snk","SUCCESS",""
```

Screenie:
![image](https://user-images.githubusercontent.com/1640096/42988200-0b673e32-8bfc-11e8-9038-907002da1ebc.png)

Weird thing about the dump is that it shows success on all rows.
![image](https://user-images.githubusercontent.com/1640096/42988277-431916ac-8bfc-11e8-90af-6f65f18be602.png)

**Comment by JohanLarsson** [comment]
I ran a new trace with filter 'ends with' 'SignRepro.snk' with the same result. Thinking maybe it was copied to some temp location.

**Comment by JohanLarsson** [comment]
Here is a trace from a rebuild filtered on 'begins with' $(SolutionDir)
[SignRepro_rebuild.zip](https://github.com/dotnet/roslyn/files/2212884/SignRepro_rebuild.zip)

**Comment by JohanLarsson** [comment]
I did a search but did not find a way to disable mcafee. Not going to do any hacks such as registry edits on this machine. It seems I'm running in some locked down mode as google results do not match what I see locally.

**Comment by JohanLarsson** [comment]
I wiped my computer, hopefully I don't have a repro any more.

**Comment by JohanLarsson** [comment]
Still have the issue. Fresh install of Win 10. Contacted IT about disabling antivirus. Will report when I find the culprit.

**Comment by JohanLarsson** [comment]
Finally some progress, looks like IT has scripted a new antivirus software, Cylane and that it is the culprit. I'm not sure what settings have been messed with as it is an admin updating some policy remotely.

**Comment by jaredpar** [comment]
Closing as this seems to be resolved now. Will re-open if we see any future events that aren't virus scanner related.

**Comment by martincostello** [comment]
Just had this randomly happen in a CI build in GitHub Actions: [logs](https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/28929069399/job/85823540436?pr=7496#step:6:337)

```text
CSC : error CS7027: Error signing output with public key from file 'C:\a\opentelemetry-dotnet\opentelemetry-dotnet\artifacts\obj\OpenTelemetry.Api.ProviderBuilderExtensions\OpenTelemetry.snk' -- The process cannot access the file 'C:\a\opentelemetry-dotnet\opentelemetry-dotnet\artifacts\obj\OpenTelemetry.Api.ProviderBuilderExtensions\OpenTelemetry.snk' because it is being used by another process. [C:\a\opentelemetry-dotnet\opentelemetry-dotnet\src\OpenTelemetry.Api.ProviderBuilderExtensions\OpenTelemetry.Api.ProviderBuilderExtensions.csproj::TargetFramework=net8.0]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:03:21.72
```

.NET SDK version is 10.0.301.
