### ISSUE TITLE
C#7 pattern matching: if (obj is string s == false) does not work as expected.

### ISSUE THREAD

**Issue by sumtec** [dotnet/roslyn#17828]
**Version Used**: 
C#7 with VS2017

**Steps to Reproduce**:

1. Create a new C#7 project and add the following function to any ".cs" file:
``` csharp 
void Test(object obj)
{
  if (obj is string s == false) return;
  Debug.WriteLine(s);
}
```

2. Observe the IntelliSense or Build output. 

**Expected Behavior**:
No error; Or,
Showing an error saying something like "Pattern matching in the if statement is not allow to test with false" on the line of the "if" statement.

**Actual Behavior**:
Showing an error saying "Use of unassigned local variable 's'" on the line of the statement "Debug.WriteLine(s)".

**Reason for thinking this is a bug**:
The following code can be compiled without issue:
``` csharp
void TestOK(object obj)
{
  if (!(obj is string s)) return;
  Debug.WriteLine(s);
}
```

The `!x` is equivalent to 'x == false'.  And '!' is sometimes easy to be skipped by human eyes. 

And I understand that in the example of `if (obj is string s == nonConstantValue) ...`, we don't know if obj is a string or not if the "if-block". So, the "s" is meaningless. However, I think:
1. It's ease to know if it is comparing to a constant false or not.
2. We should, in this example, tell the user that the s here is meaningless and not allow them to write such an "if" statement, instead of showing "unassigned s" when the user attempt to use it.

And yes, if we are allowing user to compare with false, there would be some weird cases like `if (obj is string s != true)` or  `if (!(obj is string) == false)`. However, this is the users' problem.

P.S.:
The following code cannot be compiled as well:

``` csharp
void TestTrue(object obj)
{
   if ((obj is string s) == true) Debug.WriteLine(s);
}
```

**Comment by AdamSpeight2008** [comment]
`s` is definitely unassigned if the pattern doesn't match, hence the error.

**Comment by gafter** [comment]
The unary negation operator `!` inverts "definitely assigned when true" and "definitely assigned when false". The binary relational operators never produce results in these states. Therefore `!` and `== false` are not equivalent operations. This issue demonstrates that fact.

It is by design.

**Comment by sumtec** [comment]
Hi @gafter,

Correct me if I am wrong:

``` csharp
        static void TestANot(bool a)
        {
            bool b;
            if (!a) return; else b = a;
            Console.WriteLine(b);
        }

        static void TestAFalse(bool a)
        {
            bool b;
            if (a == false) return; else b = a;
            Console.WriteLine(b);
        }
```

They both can be compiled. With my limited knowledge, I haven't heard of the inverse of the definitely assigned state. Do you mean by the true(e)/false(e) described [here](https://en.wikipedia.org/wiki/Definite_assignment_analysis#The_analysis)? I thought both `?` and `== false` behaves the same. Or, would you mind give me an example showing how they behave differently without the pattern matching syntax?

Regards,
Frank

**Comment by gafter** [comment]
If you have an expression for which a variable is "definitely assigned when true", then using `== true` on that expression will destroy the "partial" definitely assigned state; the variable will not be definitely assigned afterwards. Here is an example without pattern-matching:

``` c#
    static void Main()
    {
        bool b = true;
        int x;
        if (b && M(out x)) Console.WriteLine(x); // ok
        if ((b && M(out x)) == true) Console.WriteLine(x); // error
    }
    private static bool M(out int x)
    {
        x = 1;
        return true;
    }
```
