### ISSUE TITLE
Using Go to Definition twice, causes a previewed "source as metadata" document to be promoted as an open document

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#17833]
1. File -> New Console App (.NET Framework)
2. In Program.cs, choose Go to Definition on `string`
3. Tab back to Program.cs
4. In Program.cs, choose Go to Definition on `string`

Expected: For String.cs to remain in the preview tab
![image](https://cloud.githubusercontent.com/assets/1103906/23894710/478cce88-08f7-11e7-99b6-29722dd57b47.png)

Actual: String.cs gets promoted as a open document:
![image](https://cloud.githubusercontent.com/assets/1103906/23894700/3bffdf6a-08f7-11e7-84bf-b0e1dcb623b9.png)

**Comment by CyrusNajmabadi** [comment]
I don't repro this.
