### ISSUE TITLE
VS2017 Roslyn suggets using var on foreach with MatchCollection 

### ISSUE THREAD

**Issue by henkmollema** [dotnet/roslyn#17836]
I'm not sure if this is the right repository and this issue is might have been opened before, but I could not find it.

**Version Used**: 
Visual Studio 2017

**Steps to Reproduce**:
Iterate through a match collection using a `foreach` like:
```cs
foreach (Match match in MyRegex.Matches("some input"))
{
    // ...
}
```

**Expected Behavior**:
Roslyn does not suggest anything.

**Actual Behavior**:
Roslyn will suggest "use 'var' instead of explicit type". However, `Matches()` returns `MatchCollection` instance which is a non-generic `ICollection`. This results in `match` being an `object` rather than a `Match` instance.

![image](https://cloud.githubusercontent.com/assets/1521207/23902300/f26f7170-08c0-11e7-893e-6a71b1afc182.png)

Please note that I use an EditorConfig file to specify my code rules:
```ini
csharp_style_var_for_built_in_types = true:suggestion
csharp_style_var_when_type_is_apparent = true:suggestion
csharp_style_var_elsewhere = true:suggestion
```

**Comment by Pilchie** [comment]
This is the same issue as https://github.com/dotnet/roslyn/issues/14052, and should be fixed in a future release of VS 2017.

**Comment by henkmollema** [comment]
Thanks! 👍
