### ISSUE TITLE
Please add links to the sample source code in the FAQ

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn#17843]
There are a lot of helpful how-to information at https://github.com/dotnet/roslyn/wiki/FAQ#getting-information-questions.  However it is not easy to jump directly to the sample code from a particular answer.

**Expected Behavior**:
Link to C#/VB sample code file

**Actual Behavior**:
Had to manually navigate the repro to find the file, then search for FAQ number

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #68](https://github.com/dotnet/roslyn-sdk/issues/68) via [**ZenHub**](https://www.zenhub.com/)
