### ISSUE TITLE
IDE0017 (Initialization can be simplified) incorrect for dynamic object initialization

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [dotnet/roslyn#17853]
**Version Used**: 
Visual Studio 15.0.0-RTW+26228.4
**Steps to Reproduce**:

```c#
dynamic body = new ExpandoObject(); //<--- IDE recommends IDE0017
body.content= new ExpandoObject();
```
IDE then simplifies to 
```c#
dynamic body = new ExpandoObject() {
    content = new ExpandoObject() //CS0117, ExpandoObject does not contain definition for 'content'
};
```

**Expected Behavior**:
No recommendation to be made for IDE0017

**Actual Behavior**:
IDE0017 is recommended

**Comment by CyrusNajmabadi** [comment]
Interesting.  It's arguable that we should never offer this if the types of the variable and type being initialized are different.  After all, accessing the member off of hte variable's type might produce different results than accessing off of the type being constructed.  

However, that's likely pretty unlikely, so i think it will suffice to just suppress in the dynamic case.
