### ISSUE TITLE
Feature request: SQL IN statement style comparison for C#

### ISSUE THREAD

**Issue by girishAnar** [dotnet/roslyn#17877]
It would be lot easier if we can have sql IN statement style to C# to compare a set of unrelated variables against a value or a set of values.

Eg: 
```
string var_a="", var_b="", var=c, compare_val=""; 
... 
if((var_a, var_b, var_c)==compare_val) 
{ 
}
```

**Comment by FredyFerrari** [comment]
Ambiguous syntax to https://github.com/dotnet/csharplang/issues/190

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
