### ISSUE TITLE
Opening a rule set file from a solution folder does not open it in the <All> context

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#1787]
Split from #1579.

1. Create a new project.
2. Add a new rule set file by right-clicking on the solution item in Solution Explorer and selecting "Add | New Item...". Save the file next to the solution.
3. Add the rule set file as a linked file to a project.
4. Right click the rule set file and click 'Set Active Rule Set' - the operation succeeds and there are no errors.
5. Double-click on the rule set icon in the solution-level folder to open the rule set.

**Expected:** Rule set editor opens in the <All> context.

**Observed**: Rule set editor opens in the project context.

Note that we may not be able to fix this. Since the rule set is an item in a project, VS may be telling us to use that project as our context. In that case, there's no good way for us to know that the user double-clicked the item in the solution folder.

**Comment by srivatsn** [comment]
This seems like a very minor issue and might even  be expected based on the current design which is that the selected project will be the one showing up as the context. Won't fixing this issue.
