### ISSUE TITLE
<typeparamref isn't in the completion list for members of generic types

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#17872]
I get it for the type itself:

![image](https://cloud.githubusercontent.com/assets/1103906/23932381/b685aaa0-098b-11e7-8eef-efe08c7fe892.png)

But not members of the type:

![image](https://cloud.githubusercontent.com/assets/1103906/23932373/a7f546da-098b-11e7-9121-a7d63318fb9b.png)

**Comment by lorcanmooney** [comment]
I've added a fix for this to #17970.
