### ISSUE TITLE
VB: Move Type to File carries over wrong XML Comments when code file starts with a Delegate.

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/roslyn#17879]
1. In Visual Studio 2017 RTM, create a new VB Project (CommandLine, WinForms).
2. Define a Delegate with an XML Comment at the top of a Code File.
3. Define a class.
4. Define another second class.
5. From Refactorings, pick 'Move type to Class'.

Expected Result:
Second class should have moved to a new file, with no XML comment on top.

Actual Result:
Second class has moved to new file, and got the XML comment of the Delegate.

**Comment by CyrusNajmabadi** [comment]
This appears to be an issue with the SyntaxEditor.  Reaching out to @mattwar about this.

**Comment by CyrusNajmabadi** [comment]
Unlikely to change anything here due to lack of feedback.
