### ISSUE TITLE
VB intellisense offered inside string literal.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#17888]
Ported from https://developercommunity.visualstudio.com/content/problem/28269/intellisense-ignoring-quote-character-at-start-of.html

See video repro here: https://www.youtube.com/watch?v=jnDBoMUZ3Cg

User opens a string literal and starts typing in it.  VB intellisense comes up even though it shouldn't.

**Comment by Pilchie** [comment]
Note that the string is also not classified as a string in this case.  Makes me wonder if there is a (incremental?) parse issue.

**Comment by CyrusNajmabadi** [comment]
Unable to repro this.  Have asked customer if they can provide the code where they hit this.

**Comment by CyrusNajmabadi** [comment]
Unable to repro this.  No response from customer.  Closing out.
