### ISSUE TITLE
Formatting: Web Forms Indent Settings not Honored

### ISSUE THREAD

**Issue by JoelDKraft** [dotnet/roslyn#17883]
**Version Used**: 2.0.0.61501

**Steps to Reproduce**:
I am using an .aspx page with embedded code with master pages. The formatter does not honor the settings that I have configured in the editor preferences for tags.

Let's say this is my sample.

```
<%@ Page Language="c#" %>
<script runat="server">

private void Page_Load()
{
}

</script>
<asp:Content runat="server" ContentPlaceholderId="MainContent">

<h3>Hello, world!</h3>

</asp:Content>
```
I have gone to Tools > Options > Text Editor > HTML WebForms > Formatting > Tag Specific Options. I selected "script" from the Client HTML Tags list and unchecked "Indent Comments". The preview shows correctly. I also added the asp:Content tag to the ASP.NET Controls section and also ensured that "Indent Comments" was not checked to override the default setting.

The problem then occurs when you format the document, either manually or automatically.

**Expected Behavior**:
The document above retains its existing formatting, as it already matches the specified formatting.

**Actual Behavior**:
```
<%@ Page Language="c#" %>

<script runat="server">

	private void Page_Load()
	{
	}

</script>
<asp:content runat="server" contentplaceholderid="MainContent">

	<h3>Hello, world!</h3>

</asp:content>
```

Notice that the contents of both tags were indented, even though I have them both of them set to not indent.  Also notice that it treated <asp:Content> as a client tag instead of a WebForms control and lower-cased it all.

**Additional Comments**:
I've also noticed that if I write code in the content area that should be block formatted, it is not. For example this appears when I add a script tag:
```
<script></script>
```

When the preferences show that it should be this:
```
...before tag
<script>
contents
</script>
after tag...
```

**Comment by Pilchie** [comment]
@toddgrun - do you know how those settings are supposed to translate into Roslyn API calls?

**Comment by ToddGrun** [comment]
Regarding asp:Content, I see it respecting the indent rules and capitalization rules.

Regarding script block indent: Looks like we don't honor those settings for contained languages (script/style blocks). Will point our PM to this to determine whether this is worth pursuing.

**Comment by Pilchie** [comment]
@toddgrun - what is the right place to report this, as it's not a Roslyn issue at this point?

**Comment by madskristensen** [comment]
The correct place to report this is Connect or VS Feedback
