### ISSUE TITLE
Shortcut for syntactically growing the selection

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn#17897]
**Version Used**: Visual Studio 2017 Enterprise (RTM)

**Steps to Reproduce**:

When I want to refactor statements and expressions, especially when using extract method, I first need to select the part that I need to affect. This usually involves a bunch of keyboard gymnastics to perform this. Sometimes I even end up using the mouse. 🤢 

**Expected Behavior**:

I can use a keyboard shortcut to grow the selection. It should grow outwards. First time, it selects the token, then the enclosing node, then the next enclosing node and so on. Nodes that don't change the selection should be skipped so it always grows. It would be useful to support the reverse shortcut, which would simply undo the last extension (as shrinking wouldn't be well defined in the general case).

**Actual Behavior**:

The Visual Studio web browser opens. I kid you not. As a Resharper user, I'm used to <kbd>Ctrl+W</kbd> as the mechanism to grow the selection, so I often hit <kbd>Ctrl+W</kbd> only to find that nothing happens. Confused, I hit <kbd>Ctrl+W</kbd> again, only to find that the integrated web browser opens. Needless to say, that's not really helpful. Although in this instance, it turned out OK:

![image](https://cloud.githubusercontent.com/assets/5169960/23973961/ed4d3c10-0995-11e7-8135-fc66b2beddab.png)

**Comment by CyrusNajmabadi** [comment]
How do i thumbs-down this?

**Comment by terrajobst** [comment]
By implementing it 😄

**Comment by Pilchie** [comment]
While I'm not sure I want this hooked up to Ctrl+W, I do want the feature.  We've talked about it for years, but I don't think it made it onto our github backlog before now.

**Comment by terrajobst** [comment]
I care much less about the shortcut as I'll be able to tweak that. I can see why you might now want to use <kbd>Ctrl+W</kbd> as it's used as a prefix for many other shortcuts. But please don't make it something obscene like <kbd>Ctrl+Shift+Alt+→</kbd> 😄

**Comment by GerjanOnline** [comment]
Do you mean the same as this? https://code.visualstudio.com/docs/editor/codebasics#_shrinkexpand-selection

There seems an extension that does this: https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.HotCommandsforVisualStudio

But for sure it would be nice to have it OOTB

**Comment by gundermanc** [comment]
Hi all, the VS Editor team has committed to a platformized implementation of this feature. We're experimenting with wiring up the ITextStructureNavigator.GetSpanOfEnclosing() to an editor command.

This work is being tracked by: https://devdiv.visualstudio.com/DevDiv/Editor/_queries?id=457694&_a=edit&triage=true

**Comment by cH40z-Lord** [comment]
> This work is being tracked by: https://devdiv.visualstudio.com/DevDiv/Editor/_queries?id=457694&_a=edit&triage=true

Sometimes I wish these kind of tickets are open/public :<

**Comment by tiesmaster** [comment]
"platformized implementation" -- What does that actually means?

**Comment by terrajobst** [comment]
I think this means "part of the VS platform" (as opposed to be an extension)

**Comment by terrajobst** [comment]
VS 2019 has the feature now. On my machine, the shortcut is <kbd>CTRL</kbd><kbd>SHIFT</kbd><kbd>=</kbd>.
