### ISSUE TITLE
Local functions / csc.exe exits with -2146232797

### ISSUE THREAD

**Issue by benpetermorris** [dotnet/roslyn#17890]
**Version Used**: VS2017 RTW 26628.09

**Steps to Reproduce**: In a .NET class library, compile:

```
using System;
using System.Collections.Generic;
using System.Linq;

public class Class
{
   public class Item
   {
      public int Id { get; set; }
   }

   public class ItemsContainer : IDisposable
   {
      public List<Item> Items { get; set; }

      public void Dispose()
      {
      }
   }

   public static void CompilerError()
   {
      using (var itemsContainer = new ItemsContainer())
      {
         Item item = null;

         itemsContainer.Items.Where(x => x.Id == item.Id);

         void Local1()
         {
            itemsContainer.Items = null;
         }

         void Local2()
         {
            Local1();
         }
      }
   }
}
```

Produces the error:

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(71,5): error MSB6006: "csc.exe" exited with code -2146232797.`

The code is AFAIK the minimum required to reproduce the bug. Changing pretty much any single part will prevent the failure.

The failure first appeared when I refactored several Func<...>-style local functions to use the new local functions syntax.

**Comment by agocke** [comment]
Thanks for reporting! 

I believe this is the same as #16895 and it looks like this no longer repros with #16908, so I'm going to close it as a duplicate.
