### ISSUE TITLE
Faulting csc.exe (2.0.0.61501) on Windows Server 2012 without latest .Net Framework 4.6.2

### ISSUE THREAD

**Issue by valse** [dotnet/roslyn#17908]
Hi,
  I recently upgraded our ASP.Net MVC 4.5.2 project with the latest 2.0.1 roslyn compiler version but, after publishing on our production servers, the app crashes with the error:
```
Faulting application name: csc.exe, version: 2.0.0.61501, time stamp: 0xa16928ca
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18340, time stamp: 0x57366075
Exception code: 0xe0434352
Fault offset: 0x0000000000008a5c
Faulting process id: 0x1550
Faulting application start time: 0x01d29e2fc5c1f876
Faulting application path: C:\www\****\bin\roslyn\csc.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 037cd29d-0a23-11e7-80d6-bc764e093275
Faulting package full name: 
Faulting package-relative application ID: 
```
```
Application: csc.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingMethodException
Stack:
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(System.String[])
```
Our servers had already installed the 4.5.2 framework but I needed to upgrade it to the latest one.

Thanks
Marco

**Comment by vgnelica** [comment]
Hi i caught same error. I was helped by downgrade packages
Microsoft.Net.Compilers -> 1.3.2
Microsoft.CodeDom.Providers.DotNetCompilerPlatform -> 1.0.0

**Comment by jcouv** [comment]
@valse @vgnelica Might one of you be able to capture a crash dump?

Below is the registry key that I use to get full crash dumps to the folder `c:\shared-dumps`. You can find the [documentation here](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx).
If you are not familiar, note that dump files will have a snapshot of the process when it died, so I leave it up to your judgement (if there is proprietary or sensitive information, then please decline).

If you can do that, then contact me at jcouv@microsoft.com referencing this github issue, then I'll reply privately with information to send the dump file.

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps]
"DumpFolder"="c:\\shared-dumps"
"DumpCount"=dword:00000001
"DumpType"=dword:00000002
```

**Comment by valse** [comment]
Hi @jcouv,
   thanks for your help but I already solved the issue upgrading the .net framework so I can't reproduce the problem again... maybe @vgnelica can do it for us...?

**Comment by Desmont** [comment]
I'm having the same issue on Windows Server 2008 SP2, with the 4.5.2 .NET Framework. 
My company policy forbids me from sharing any sensitive information. 

```
  <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-03-21T11:33:13.000Z" /> 
  <EventRecordID>121271</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>{REMOVED}</Computer> 
  <Security /> 
  </System>
  <EventData>
  <Data>csc.exe</Data> 
  <Data>2.0.0.61501</Data> 
  <Data>a16928ca</Data> 
  <Data>KERNEL32.dll</Data> 
  <Data>6.0.6002.19623</Data> 
  <Data>56ec4631</Data> 
  <Data>e0434352</Data> 
  <Data>00000000000166cd</Data> 
  </EventData>
  </Event>
```

```
  <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-03-21T11:33:25.000Z" /> 
  <EventRecordID>121272</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>{REMOVED}</Computer> 
  <Security /> 
  </System>
  <EventData>
  <Data>Application: csc.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.MissingMethodException Stack: at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(System.String[])</Data> 
  </EventData>
  </Event>
```

**Comment by jcouv** [comment]
Thanks @Desmont and @valse. Although the information is not as complete as a crash dump, they both have csc.exe crashing first thing when entering the `Main` method, with a `MissingMethodException`.
The next question is what method is missing. I would expect the `MissingMethodException` to have that information in its message.

Ping @jaredpar @VSadov in case they recognize the root cause.

**Comment by jaredpar** [comment]
> I'm having the same issue on Windows Server 2008 SP2, with the 4.5.2 .NET Framework.

The C# 7.0 compiler requires the 4.6 .NET Framework to execute.  Running on 4.5.2 is not supported and is very likely the source of this particular error.

@agocke did we update the config files to have the minimum runtime explicitly listed here?

**Comment by jaredpar** [comment]
@valse 

> Faulting application path: C:\www\****\bin\roslyn\csc.exe

Can you take a look that directory and post a list of all of the files that are present?  Interested in the overall list but in particular interested in whether csc.exe.config is present.

**Comment by KMjkantonen** [comment]
Hi,
We've just experienced the exact same issue.  Upgraded to 2.01 and pushed to our Windows Server 2012 R2 environment which is restricted to .NET 4.5.2.  Applications crashed; rolled back to 1.3.2 and everything works again.  Same errors as described above.  Checked and the bin\roslyn path does have csc.exe.config.  I do have a currently faulting development environment if you need more information.  Thanks,
Jake

**Comment by jaredpar** [comment]
@KMjkantonen 

> Upgraded to 2.01 and pushed to our Windows Server 2012 R2 environment which is restricted to .NET 4.5.2.

The C# 7.0 compiler (2.0 and higher) requires .NET 4.6 to run hence that particular failure is expected.  We're working on making the error better by setting the minimum runtime correctly.  

CC @Jinhuafei for reference as this affects the DotNetCompilerPlatform NuGet as well.

**Comment by agocke** [comment]
@jaredpar No, I forgot we could do that. I'll make the change.

**Comment by jcouv** [comment]
I'll let @agocke close as by design (C# 7.0 compiler requires .Net 4.6) and update the minimum required runtime configuration. Thanks

**Comment by valse** [comment]
Do you suggest to downgrade to the previous version for the 4.5.x projects?
I think that I'll can't upgrade the NuGet package after this new minimum requirement upgrade right?

**Comment by jaredpar** [comment]
@valse 

> Do you suggest to downgrade to the previous version for the 4.5.x projects?

Correct.  The 1.X packages are capable of running on 4.5.2 and will continue to work there. 

> I think that I'll can't upgrade the NuGet package after this new minimum requirement upgrade right?

Correct.  Unless the machines can be moved to have 4.6 installed you'll need to remain on the 1.X Roslyn packages.

Is your core scenario here running ASP.Net applications?

**Comment by valse** [comment]
Hi @jaredpar 
all clear thanks!

> Is your core scenario here running ASP.Net applications?

Yep, MVC web sites.
