### ISSUE TITLE
Synthetic tuple fields aren't supported by dynamic

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#17911]
**Version Used**: 

2.0.0.61501

**Steps to Reproduce**:

```csharp
using System;
class Test
{
    static void Main(string[] args)
    {
        var tuple2 = (x: 0, y: 0);
        Console.WriteLine(tuple2.x);
        Console.WriteLine(tuple2.y);
        dynamic d = tuple2;
        Console.WriteLine(d.x); // Bang
        Console.WriteLine(d.y); // Bang
        
        var tuple8 = (0, 0, 0, 0, 0, 0, 0, 0);
        Console.WriteLine(tuple8.Item8);
        d = tuple8;
        Console.WriteLine(d.Item8); // Bang
    }
}
```

**Expected Behavior**:

The "fake" fields supported by the C# compiler (both due to named tuple elements and ItemN where N > 7) should behave the same way when accessed via a dynamic value.

**Actual Behavior**:

A `RuntimeBinderException` is thrown.

(Apologies if this is a duplicate... I couldn't find one.)

**Comment by jskeet** [comment]
Thinking about this further:

- The `x` and `y` probably can't be maintained in any sensible fashion. Propagating it for a single assignment would be feasible, but could get tricky really quicky:

    var tuple = (x: 0, y: 0);
    dynamic d1 = tuple;
    dynamic d2 = d1;
    Console.WriteLine(d2.x);

- The `Item8`, `Item9` etc fields would probably be "accidentally" available for code that really used the CLR names, never using C# tuple syntax... but that would probably be better, nevertheless.

**Comment by mgravell** [comment]
An awkward thing about this is that if it was fixed, it would work differently locally yo if the dynamic was passed to another method and *then* accessed, because the name information **isn't preserved** at that point.

For that reason, with the current implementation I think it would be dangerous and confusing to fix this. I would love for the fix to exist  though. I just don't think it possibly can (reliably) today. 

FWIW I have similar issues where I'd like synthetic tuples to work with dapper as parameter names, but all dapper can see is Item1 etc.

**Comment by mgravell** [comment]
(Dammit, can't edit on mobile; yo=to; name pseudo-metadata is only preserved outwards, not onwards/inwards)

**Comment by mattnischan** [comment]
Seems like this could have been handled more like lambda closures: with the creation of a ValueTuple_abcd class specific to the case at hand, complete with the correct field names. Of course, that very quickly may become complicated in other ways (up/downcasting, is Dictionary<ValueTuple<int, int>, string> the same as Dictionary<(int, int), string>)

**Comment by mgravell** [comment]
I put some thought into how I would have implemented synthetic tuples if it was me. I'm not sure why the answer chosen wasn't "compilers generated struct" - after all, the compiler generates classes all the time. I guess it comes down to the public API and anonymous vs discoverable. But yeah, the fact that it is just ValueTuple-* with attributes makes it very brittle.

**Comment by gafter** [comment]
Synthetic tuple fields are not part of the runtime object, by design. So it is not expected that this would work.

Tagging @MadsTorgersen @jcouv @VSadov in case they want to comment further.

**Comment by mgravell** [comment]
alternative fix: "generics plus attributes" - somehow pass the psuedo metadata attributes alongside the (ValueType-*) "T"

**Comment by jcouv** [comment]
Yes, this is expected.

From [design notes](https://github.com/dotnet/roslyn/blob/master/docs/features/tuples.md):

## Name erasure at runtime

Importantly, the tuple field names aren't part of the runtime representation of tuples, but are tracked only by the compiler.

As a result, the field names will not be available to a 3rd party observer of a tuple instance - such as **reflection or dynamic code**.

**Comment by mgravell** [comment]
Obviously I'm not Jon, but I suspect the problem there is that the expectation is that `dynamic` - along with the compiler-specific resolver  - is intended (conceptually, at least) to behave *kinda like* the compiler. This is an explicit break from that.

**Comment by VSadov** [comment]
We could, in theory, teach the dynamic binder to know about `Item8`, `Item9`, ...  since those can be inferred from the `ValueType` instantiation having a canonical tuple shape.   

That would need to be done in https://github.com/dotnet/corefx/tree/master/src/Microsoft.CSharp
I think it is worth logging an issue about that, so it could be triaged.  

Support for "friendly" names like `Alice`, `Bob` is IMO hopeless. 
Dynamic works by introspecting boxed instances and an instance of a tuple does not carry any information about the "friendly" element names.

**Comment by jskeet** [comment]
Righto - will create a new issue just for the Item8... part so that can be discussed separately (and in the right repo).

For what it's worth, Marc's comment is spot on in terms of an ideal world - using `dynamic` is meant (IMO) to *feel* like normal C#, with normal C# features applied. However, I completely understand that sometimes features simply don't gel well with that. So long as users aren't surprised, it's not much of a problem. (I'll do my little bit on that front.)

Will close this issue now, but I'm still glad it exists, as a reference point.

**Comment by mgravell** [comment]
Random after-the-fact shower-thought - there is at least good precedent for this: it is very comparable to extension methods, which also don't work for `dynamic`.

**Comment by danielcrabtree** [comment]
Also, you can access `Item8` via `dynamic`. You just do it using `tuple8.Rest.Item1`

**Comment by jskeet** [comment]
@danielcrabtree: The point is that you shouldn't have to. Using Item8 should work - especially as it works for `ValueTuple<...>` regardless of other tuple syntax.
