### ISSUE TITLE
roslyn / .editorConfig [*.cs] causes crash

### ISSUE THREAD

**Issue by MoSkinny** [dotnet/roslyn#17914]
roslyn / .editorConfig with Visual Studio 2015 editorconfig extension

**Steps to Reproduce**:

1. Install the EditorConfig extension for VS 2015
2. Place the .editorconfig file in the solution folder
3. Open the solution in VS 2015

**Expected Behavior**: 
Visual studio doesn't crash due to the missing curly braces in the `[*.cs]` file type filter under the _CSharp code style settings:_  section.  The file filter `[*.cs]` should be `[*.{cs}]`

**Actual Behavior**:
Microsoft Visual Studio 2015 has stopped working

![image](https://cloud.githubusercontent.com/assets/5541870/24019696/b1a93a8c-0a5e-11e7-9e3b-986fc01d5589.png)

**Comment by tannergooding** [comment]
`[*.cs]` is perfectly valid, as can be seen on the official editorconfig website: http://editorconfig.org/

This sounds like a bug in the VS2015 Extension: https://github.com/editorconfig/editorconfig-visualstudio#readme

**Comment by Pilchie** [comment]
Can you file on the extension - we didn't have support for editorconfig in VS2015.

**Comment by MoSkinny** [comment]
Thanks for the information... I'll open an issue in the extension forum
