### ISSUE TITLE
ServiceHub.RoslynCodeAnalysisService32.exe stays running after VS has been closed

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#17920]
_From @NTaylorMullen on March 16, 2017 23:10_

I haven't been able to reproduce this issue but after closing VS gracefully the ServiceHub.RoslynCodeAnalysisService32 process stayed running and kept a handle on several DLLs.

Wasn't sure what information was needed to properly diagnose the issue so I took a dump of the process: `\\NTaylorMullen\SHARED\Dumps\ServiceHub.RoslynCodeAnalysisService32.DMP`

_Copied from original issue: dotnet/roslyn-project-system#1770_

**Comment by IlyaBiryukov** [comment]
This is most likely a Service Hub issue.
Tracked by https://devdiv.visualstudio.com/DevDiv/Connected%20Experience/_workitems?id=396489&_a=edit&triage=true

**Comment by NTaylorMullen** [comment]
Captured a better dump: `\\NTaylorMullen\SHARED\Dumps\ServiceHub.dmp`

**Comment by davkean** [comment]
tag @heejaechang

**Comment by heejaechang** [comment]
@davkean thank you. already talked about this with @NTaylorMullen and @IlyaBiryukov . servicehub team is looking.

**Comment by Ronmenator** [comment]
Further information that hopefully could help.

I had this issue this morning on a single WPF project (VS 2017 15.3.3) solution.

The task ServiceHub.RoslynCodeAnalysisService32.exe stayed running after I closed and trying to kill it through task manager only showed 'Access denied' message.

I solved it through an elevated command prompt running taskkill. But it would not completely kill the process:

`C:\WINDOWS\system32>taskkill.exe /F /T /PID 12732
ERROR: The process with PID 12732 (child process of PID 12528) could not be terminated.
Reason: There is no running instance of the task.

C:\WINDOWS\system32>taskkill.exe /F /T /PID 12528
ERROR: The process "12528" not found.

C:\WINDOWS\system32>taskkill.exe /F /T /PID 12152
SUCCESS: The process with PID 9684 (child process of PID 12152) has been terminated.
ERROR: The process with PID 12152 (child process of PID 1360) could not be terminated.
Reason: There is no running instance of the task.

C:\WINDOWS\system32>taskkill.exe /F /T /PID 12152
ERROR: The process with PID 12152 (child process of PID 1360) could not be terminated.
Reason: There is no running instance of the task.

C:\WINDOWS\system32>taskkill.exe /F /T /PID 12732
ERROR: The process with PID 12732 (child process of PID 12528) could not be terminated.
Reason: There is no running instance of the task.

C:\WINDOWS\system32>taskkill.exe /F /T /PID 12528
ERROR: The process "12528" not found.`

The interesting thing to note, and what finally allowed me to close this task, was Process ID: 1360, which was Windows Explorer (not file explorer) but windows itself. After killing the windows process, I was able to end both Roslyn and Devenv without further issues. Restarting explorer through Task manager brought windows back.

I hope this could help, let me know if you need anything else. I get this issue a lot.

Regards

Ronnie

**Comment by heejaechang** [comment]
@AArnott @IlyaBiryukov is this a known issue?

**Comment by AArnott** [comment]
I see such a permission issue with killing processes randomly, but I haven't ever noticed a tendency toward certain processes. In my estimation it's been a bug in Windows.

**Comment by Ronmenator** [comment]
The important thing to note is that it is not random processes, but following the path of dependencies. By trying to stop the process that holds the previous, you find the one that would allow the source process to be removed. In this case, the ServiceHub.RoslynCodeAnalysisService32 code was being blocked by windows itself. 

I wish I could say that it was a once off, but unfortunately, this happens every time, and the only way to get your system back is to hard boot by power, and every time, it is caused by ServiceHub.RoslynCodeAnalysisService32 hanging. Subsequently, I was not able to reproduce the process to stop windows - that I agree seem to be random, but whatever ServiceHub.RoslynCodeAnalysisService32 does, it does not allow windows to restart at all.

I do not agree that it is a windows bug because it only started when code analysis was introduced.

**Comment by AArnott** [comment]
> I do not agree that it is a windows bug because it only started when code analysis was introduced.

It may be unique to this process, and you may be right that this process does something it shouldn't. But IMO it is the Windows kernel's job to guard against unruly processes, and a non-elevated shouldn't be allowed to prevent Windows from rebooting.

**Comment by CyrusNajmabadi** [comment]
Have not seen any further indications this is still happening.  Most likely a servicehub issue that was fixed at some point.

**Comment by AArnott** [comment]
@CyrusNajmabadi this bug was 5 years old. :) I don't think we need more info, do we?

**Comment by CyrusNajmabadi** [comment]
Yup yup. Will close it.
