### ISSUE TITLE
The entry point Main method should not be allowed to return int by-ref because it is not supported by CLR

### ISSUE THREAD

**Issue by VladimirReshetnikov** [dotnet/roslyn#17923]
**Version Used**: 

Microsoft Visual Studio Enterprise 2017
Version 15.0.26228.9 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01586

**Steps to Reproduce**:

Compile as a console application and run:
```
using System;

class C
{
    static ref int Main()
    {
        throw new Exception();
    }
}
```

**Expected Behavior**: A compile-time error: error CS5001: Program does not contain a static 'Main' method suitable for an entry point.

**Actual Behavior**: No compile-time errors. Unhandled exception at runtime: System.MethodAccessException: Entry point must have a return type of void, integer, or unsigned integer.

**Comment by jcouv** [comment]
FYI @VSadov
