### ISSUE TITLE
ref var not colorized correctly

### ISSUE THREAD

**Issue by diryboy** [dotnet/roslyn#17933]
**Version Used**: 
VS2017

**Steps to Reproduce**:
1. New Console App
1.
```C#
        static void Main( string[] args )
        {
            int i = 0;
            ref var a = ref F(ref i);

            ref int F( ref int b )
            {
                return ref b;
            }
        }
```

**Expected Behavior**:
`var` be colorized

**Actual Behavior**:
![image](https://cloud.githubusercontent.com/assets/159110/24037870/3263a5a0-0b3a-11e7-933e-b807a243e62b.png)

**Comment by Pilchie** [comment]
Oops.  That's embarassing.  @diryboy - want to PR a fix?

**Comment by diryboy** [comment]
Why not?

**Comment by diryboy** [comment]
Not sure what happened, but this bug was actually fixed in #16342 in master. https://github.com/dotnet/roslyn/pull/16342/files#diff-3b7e3b07f692c9c87b4047362cc670c8R182

**Comment by CyrusNajmabadi** [comment]
The fix was checked into "dotnet:post-dev15".  So you'll see it in update1 but not RTM.

**Comment by diryboy** [comment]
Just found that, good, thanks!
