### ISSUE TITLE
Omittable "class" constraint on child type of a class

### ISSUE THREAD

**Issue by hozuki** [dotnet/roslyn#17959]
**Version Used**: 
VS2017 (with ReSharper)

**Steps to Reproduce**:

Here's a piece of code that show currently how it is written now:

```csharp
public static TChild ExpectToBe<TChild, TParent>(this TParent obj)
    where TParent : class
    where TChild : class, TParent {
    var child = obj as TChild;
    if (child == null) {
        // throw ...
    }
    return child;
}
```

**Expected Behavior**:

Since `TParent` already has a `class` constraint (so the type itself is not an interface) and `TChild` is a subtype of `TParent`, `TChild` should also be a class. Therefore, the `class` constraint of `TChild` can be omitted.

**Actual Behavior**:

If you omit the `class` constraint on `TChild`, Roslyn prompts an error on `as` conversion. It can't assure `TChild` is nullable.

**Comment by alrz** [comment]
>so the type itself is not an interface

It can be. `class` means it must be a reference type.

**Comment by hozuki** [comment]
OK I get it. Sorry I forgot boxing. But still, it means `TParent` must be a reference type. So `TChild` must also be a reference type, which is nullable.

**Comment by alrz** [comment]
A struct can inherit from an interface so you will need a class constraint on TChild as well.

**Comment by hozuki** [comment]
`class` constraint is also applicable to interfaces... it's a trap! 😆 
So it's real meaning is:
1. that type could be a class or (boxed and cast to / simply cast to) an interface;
2. that argument is passed in byref (classes), or boxed and byval (structs), in caller's view;
And so are its children, unless other constraints are applied.
Tricky, but noted. Thank you for the explanation. :)
