### ISSUE TITLE
Wrong matches highlighting in completion list if CompletionItem.FilterText is set

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/roslyn#17969]
If I create a `CompletionItem` with the following code:
```fsharp
CommonCompletionItem.Create(name, ..., filterText = filterText)
```
and `filterText` is different from `name`, then matches in completion list are wrong:

![pasted image at 2017_03_19 18_41](https://cloud.githubusercontent.com/assets/873919/24082721/37b2e4c4-0cdb-11e7-96bf-173d21972a18.png)

(here `filterText` for items are `bind`, `bind`, `BindIPEndPoint`, `bind2`, `bind` and so on).

However, the filtering itself works OK.

I expect "bind" to be highlighted (shown in bold font) in all items. Currently it highlights the first four characters of each item.

**Comment by CyrusNajmabadi** [comment]
What is your filter text in hte above examples?

**Comment by vasily-kirichenko** [comment]
> (here filterText for items are bind, bind, BindIPEndPoint, bind2, bind and so on).

In short, the last part of long (dot delemited) identifier. I'll recheck in debugger, but i'm pretty sure about that.

**Comment by CyrusNajmabadi** [comment]
@vasily-kirichenko I have a potential fix.  Can you try it out and see if it takes care of things for you?

**Comment by vasily-kirichenko** [comment]
@CyrusNajmabadi sure, but how I can test it?

**Comment by CyrusNajmabadi** [comment]
Just pull down my branch, and build Roslyn with it.

**Comment by CyrusNajmabadi** [comment]
Ok, highlighting result with my change:

![image](https://cloud.githubusercontent.com/assets/4564579/24340101/974c6318-1264-11e7-8bdc-eb8431820f02.png)

**Comment by vasily-kirichenko** [comment]
This is great, thanks. How can I know that it's in NuGet?

**Comment by CyrusNajmabadi** [comment]
This will be in our 15.3 release.  If your work targets that same release, then things will work out.  I'm not sure how/when this flows through nuget.  @jasonmalinowski might know.

**Comment by jasonmalinowski** [comment]
We will have packages uploaded https://dotnet.myget.org/gallery/roslyn that would contain the fix if you need it in NuGet package form. The packages would be versioned 2.3.0-beta1-*.
