### ISSUE TITLE
Omittable generic type parameter

### ISSUE THREAD

**Issue by hozuki** [dotnet/roslyn#17960]
**Version Used**: 

VS2017 (with ReSharper)

**Steps to Reproduce**:

Here's how this function is invoked now (the function is in #17959):

```csharp
class Parent {}
class Child : Parent {}

// Parent parent = ...
var child = parent.ExpectToBe<Child, Parent>();
```

**Expected Behavior**:

Since this generic type parameter `TParent` is assured to be `Parent` class (see appendix), this type parameter can also be omitted, unless explicitly appointed.
Currently, if both `TChild` and `TParent` is appeared in the argument list, their types can be resolved, like those functions in Linq. However if only a part of the types appears in the argument list, a full generic type argument must be given. Why not something like partial template specialization?

**Actual Behavior**:

The best practice could be something like this:

```csharp
// TParent is recognized as the type of `parent`.
var child = parent.ExpectedToBe<Child>();
```

Unfortunately, it is not supported yet.

---

A test of how runtime type of generic typed parameter is recognized:

```csharp
class GenericTest {
    
    class Parent { }

    class Child : Parent { }

    static void A<T>(T t) where T : Parent {
        Console.WriteLine($"The type of param object is : {typeof(T).Name}");
    }

    public static void Test() {
        var parent = new Parent();
        var child = new Child();
        Parent childAsParent = child;
        A(parent);
        A(child);
        A(childAsParent);
    }

}
```

Result:

```plain
The type of param object is : Parent
The type of param object is : Child
The type of param object is : Parent
```

So the type is always the argument's declared type, not runtime type.

**Comment by gafter** [comment]
The Roslyn repository tracks the compiler implementations (among other things). We no longer track language feature requests here. Such proposals are now discussed in https://github.com/dotnet/csharplang/
