### ISSUE TITLE
Readonly Auto-properties Issue

### ISSUE THREAD

**Issue by hishamco** [dotnet/roslyn#1797]
I used readonly auto-properties in the following code
```
Public ReadOnly Property Host As String = "127.0.0.1"
Public ReadOnly Property Port As Integer = 6379
Public Sub New()
       Me.New(Host, Port)
End Sub
Public Sub New(host As String, port As Integer)
        Me.Host = host
        Me.Port = port
        'Code omitted for brevity
End Sub
```
instead of duplicate the code in both constructors, I called the parametrized constructor inside the the default one, but I got "Implicit reference to object under construction is not valid when calling another constructor".
So is this a bug?!!

**Comment by Joe4evr** [comment]
It's not the ReadOnly that's the problem, but the fact that you can't call a constructor from another one of the same type (AFAIK). Instead, you can just omit the `Me.New(Host, Port)`, since the compiler will already insert the given values for those properties into the constructor, anyway.

**Comment by hishamco** [comment]
@Joe4evr I'm agree with you but I want to call the parametrized constructor to execute the rest of the code instead of the duplication

**Comment by gafter** [comment]
@hishamco The initialization of `Host` and `Port` occur in the any final constructor (i.e. one that does not chain to another constructor of the current class). Since your first constructor is not a final constructor, it does not initialize `Host` and `Port`. Since you attempt to read `Host` and `Port` before chaining, you would be reading the default values of those fields (`Nothing` and `Nothing`). Since this is obviously not what you want, the compiler is doing you a favor by preventing you from doing it.

You're welcome ;)

**Comment by gafter** [comment]
@ljw1004 Can you please label this issue "Verified" if you agree with the resolution?

**Comment by ljw1004** [comment]
The line in the spec is $9.3.1 Instance Constructors: "Because Me is not considered to be constructed until after the call to a base class constructor, the parameters to a constructor invocation statement cannot reference Me, MyClass, or MyBase implicitly or explicitly"

**Comment by hishamco** [comment]
@gafter I never heard that the initialization will happen in the final constructor, thanks for clarification
@ljw1004 I already seen such chain call in ```StreamWriter```  but when I used the readonly auto properties the issue occurs

Anyhow, I modify the code using optional paramters
```
Public ReadOnly Property Host As String
Public ReadOnly Property Port As Integer
Public Sub New(optional host As String="127.0.0.1", port As Integer=6379)
        Me.Host = host
        Me.Port = port
        'Code omitted for brevity
End Sub
```
please let me know if there's improvement can I do in the previous snippet ..

**Comment by gafter** [comment]
@hishamco The problem still occurs here:

```vb
Public Sub New()
       Me.New(Host, Port)
End Sub
```

**Comment by ljw1004** [comment]
I can't see any improvement. I guess it's impossible to combine autoprop-initializers with a common constructor that uses those initializers. Your workaround looks decent.
