### ISSUE TITLE
Replacement for Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace?

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#17974]
_From @MarkMichaelis on January 20, 2017 23:38_

In migrating from VS2015 to VS2017, is Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace the intended replacement for Microsoft.DotNet.ProjectModel.Workspaces.ProjectJsonWorkspace? Or is there some other implementation of Microsoft.CodeAnalysis.Workspace that we should be using?

/cc @granterickson, @morrisjoe, @breaman, @ascott18

_Copied from original issue: dotnet/roslyn-project-system#1285_

**Comment by davkean** [comment]
_From @srivatsn on January 30, 2017 17:28_

Yes MSBuildWorkspace should work for these projects. Now I know @mattwar was looking into MSBuildWorkspace being broken due to MSBuild moving elsewhere. Matt, does MSBuildWorkspace work with MSBuild 15 (which is needed for it to understand .NET core projects).

**Comment by davkean** [comment]
_From @mattwar on January 30, 2017 19:0_

Msbuild should work in RC3.  Though you'll need to upgrade the app's redirects to include the newest msbuild's redirects found in msbuild.exe.config.

**Comment by davkean** [comment]
_From @JosephWoodward on February 23, 2017 0:27_

Does MSBuildWorkspace support the .NET Standard? IE, can it be used for loading .NET Core projects on Mac and Linux?

**Comment by davkean** [comment]
_From @mattwar on February 23, 2017 0:30_

MSBuildWorkspace only supports desktop clr currently.

**Comment by davkean** [comment]
_From @JosephWoodward on February 23, 2017 1:21_

Ok, thank you for the prompt reply!

**Comment by davkean** [comment]
_From @JosephWoodward on February 23, 2017 2:51_

@mattwar Do you have any suggestions as where to look or what to do for anyone that wants to load the new MsBuild .csproj proj format on Mac and Linux?

**Comment by JosephWoodward** [comment]
Would love to see .NET Standard support for MSBuildWorkspace so it will be usable on a Mac or Linux.

**Comment by per-samuelsson** [comment]
@JosephWoodward 

Regarding

> @mattwar Do you have any suggestions as where to look or what to do for anyone that wants to load the new MsBuild .csproj proj format on Mac and Linux?

you might find some info in #14206, and more explicitly, by starting from this https://github.com/dotnet/roslyn/issues/14206#issuecomment-254271050. In the end, it turned out that proposal was not really x-plat either though, but could be worth looking up again.

**Comment by Pilchie** [comment]
I think the ideal would be to make `MSBuildWorkspace` just work in 15.3 - I'm going to take a look and see if this is feasible.

**Comment by per-samuelsson** [comment]
> I think the ideal would be to make MSBuildWorkspace just work in 15.3

And what about x-plat story? 15.x and x-plat is two separate concerns, yes?

**Comment by stuartleeks** [comment]
Any update on the x-plat story for loading csproj workspaces?

**Comment by JosephWoodward** [comment]
> Any update on the x-plat story for loading csproj workspaces?

Really interested to know this too! Is it still on the road map?

**Comment by ltcmelo** [comment]
Me too, could anyone please shared an update on this issue?

In addition, I'd like to ask how people have "replaced" the absence of MSBuildWorkspace so far - I've tried https://github.com/daveaglick/Buildalyzer, but I can't use it due to package incompatibilities (downgrade with Microsoft.Win32.Primitives and similar). Any comments are appreciated

**Comment by daveaglick** [comment]
@ltcmelo Feel free to open an issue in Buildalyzer if the package incompatibilities are something that could be potentially resolved upstream.

**Comment by ltcmelo** [comment]
@davkean Thanks for the hint. I'll give it a try compiling it locally and, if I don't see a reason for the incompatibility, I'll fill a report.

**Comment by IanKemp** [comment]
Any progress on this? Seems it's not in 15.7 which makes me a sad panda 😢

**Comment by IanKemp** [comment]
See also: #17968

**Comment by DustinCampbell** [comment]
@IanKemp: The new MSBuildWorkspace is in the Roslyn 2.9.0 which are not yet on NuGet.

**Comment by stuartleeks** [comment]
@dustincampbell - is 2.9.0 available via a preview feed to give it a try? :-)

**Comment by stuartleeks** [comment]
You are correct (I'm looking for xplat). Was quickly scanning the notification and got my hopes up!

**Comment by IanKemp** [comment]
For anyone looking for the preview bits including `MSBuildWorkspace`: add `https://dotnet.myget.org/F/roslyn/api/v3/index.json` as a package source in VS, then open the Package Manager for your project, ensure "Include prerelease" is ticked and that your "Package source" is on "All", and then install `Microsoft.CodeAnalysis.Workspaces.Common`.

Note that, because the MSBuild bits are still not available in .NET Standard/Core, **your project has to target .NET Framework 4.6 or higher**.

**Comment by JosephWoodward** [comment]
Bah, saw this had been updated and got all excited thinking cross-platform support was finally added :(

**Comment by tomakita** [comment]
It's not clear from reading through this issue (or maybe I missed it) -- is .NET Standard support for MSBuildWorkspace something that's planned?

**Comment by beeuhtricks** [comment]
Definitely still interested in cross-platform support for this. I'm writing a static analysis and code exploration tool and not having this API on macOS and Linux is pretty unfortunate. Willing to help implement as well.

**Comment by jmarolf** [comment]
It is my understanding that this should "just work" now if you use MSBuildLocator with a .NET Core SDK installed

**Comment by beeuhtricks** [comment]
Oh perfect! Thanks for the clarification.

**Comment by EamonNerbonne** [comment]
Thanks for the link to the locator, solved my issues too!

In case sometime finds this after some googling, to use MSBuildWorkspace on .net core you can follow these instructions: https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application - essentially adding a reference to `Microsoft.Build.Locator`; adding `ExcludeAssets="runtime"` to other `Microsoft.Build.???`  `<PackageReferences>`, and calling `MSBuildLocator.RegisterDefaults();` at the start of your program.
