### ISSUE TITLE
CodeAnalysis.Elfie unlisted on Nuget

### ISSUE THREAD

**Issue by OliverHallam** [dotnet/roslyn#17984]
It looks like the Elfie package is unlisted on Nuget, and there are no listed versions:

https://www.nuget.org/packages/Microsoft.CodeAnalysis.Elfie/

**Comment by jasonmalinowski** [comment]
@jinujoseph is this expected?

**Comment by jinujoseph** [comment]
This is currently by design, to reduce any direct dependency on the package.

**Comment by OliverHallam** [comment]
This has caused us some trouble, since we rely on an internal (Proget) mirror of Nuget.org which was unaware of the unlisted package.  We've worked around it for now by manually uploading the package.

Dogmatically thoguh It doesn't seem right for a public package to rely on an unlisted package.

**Comment by jinujoseph** [comment]
Completely agree Oliver, we will work towards getting this fixed.
cc/ @Pilchie

**Comment by conniey** [comment]
Is there an ETA on getting this fixed? I was trying to consume the stable release Microsoft.CodeAnalysis  2.2.0 but it depends on Microsoft.CodeAnalysis.Elfie.

**Comment by jasonmalinowski** [comment]
@conniey Although the package is unlisted (i.e. "hidden") it's otherwise there. What problem are you seeing?

**Comment by conniey** [comment]
@jasonmalinowski Thanks for following up. :) The warning from paket was throwing me off but it appears to be working.

**Comment by teo-tsirpanis** [comment]
@jinujoseph can we reopen this? The package is still unlisted.
