### ISSUE TITLE
Use RHS info to suggest replacement names for `var`

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#17988]
cc @Pilchie

**Comment by Pilchie** [comment]
Technically, I think this should happen for non-var as well if the RHS exists.  Sometimes the expression will have a more meaningful name than just the type.

**Comment by Pilchie** [comment]
I don't this needs to happen now though.

**Comment by CyrusNajmabadi** [comment]
Not sure what this is asking for.
