### ISSUE TITLE
Unable to Get "Analyzer with Code Fix (NuGet + VSIX) template" option in the VS even after installing >net SDk Vsix package

### ISSUE THREAD

**Issue by abhisheksharma0994** [dotnet/roslyn#17981]
Unable to Get "Analyzer with Code Fix (NuGet + VSIX) template" option in the VS> New Project > Extensibility,  even after installing >net SDk Vsix package.

 My VS version : Microsoft Visual Studio Enterprise 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA745
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Microsoft Visual Studio Tools for Applications 2015   00322-80000-00000-AA745
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-80000-00000-AA745
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA745
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA745
Microsoft Visual C++ 2015

ASP.NET and Web Tools 2015.1   14.1.20907.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9.5   14.0.20810.0
Azure App Service Tools v2.9.5

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.1.0000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

CRMDeveloperTools   1.0
Information about my package

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2015.2   Build 103.0.20150818.200216
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

Microsoft .NET Core Tools (Preview 2)   14.1.20907.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Hive Query Language Service   2.1.0000.0
Language service for Hive query

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.41025.2

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.40623.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.40623.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.40623.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.60629.0
Microsoft SQL Server Data Tools

StyleCop   4.7
Provides source code style and consistency tools. See https://github.com/Visual-Stylecop/Visual-StyleCop for more details.

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

Visual Studio Tools for Universal Windows Apps   14.0.25527.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   4.1.1.1 (ee3cfcd)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.1.1.0 (ffca580)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.iOS   9.8.1.3 (422d7d4)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by jmarolf** [comment]
@abhisheksharma0994 is the dotnet framework version set to 4.6?

**Comment by abhisheksharma0994** [comment]
I just changed it 4.6 and the issue got fixed. Thanks a lot :)

**Comment by mwpowellhtx** [comment]
I cannot find it either. I have .NET Framework 4.7 indicated in my registry. Running against VS2015 latest updates. Do I need to install the actual .NET Framework SDK(s)?

**Comment by mwpowellhtx** [comment]
I see... Apparently answered on [SO](http://stackoverflow.com/questions/41808140/analyzer-with-code-fix-template#answer-41808184).
