### ISSUE TITLE
[IOperation] Differing variable declaration in Blocks loops between C# and VB

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#17998]
C# Code:
```C#
for (int i = 0; i < 5; i++)
{
}
```
Resulting IOp Tree:
```
IForLoopStatement (LoopKind.For) (OperationKind.LoopStatement)
  Condition: IBinaryOperatorExpression (BinaryOperationKind.IntegerLessThan) (OperationKind.BinaryOperatorExpression, Type: System.Boolean)
      Left: ILocalReferenceExpression: i (OperationKind.LocalReferenceExpression, Type: System.Int32)
      Right: ILiteralExpression (Text: 5) (OperationKind.LiteralExpression, Type: System.Int32, Constant: 5)
  Local_1: System.Int32 i
  Before: IVariableDeclarationStatement (1 variables) (OperationKind.VariableDeclarationStatement)
      IVariableDeclaration: System.Int32 i (OperationKind.VariableDeclaration)
        Initializer: ILiteralExpression (Text: 0) (OperationKind.LiteralExpression, Type: System.Int32, Constant: 0)
  AtLoopBottom: IExpressionStatement (OperationKind.ExpressionStatement)
      IIncrementExpression (UnaryOperandKind.IntegerPostfixIncrement) (BinaryOperationKind.IntegerAdd) (OperationKind.IncrementExpression, Type: System.Int32)
        Left: ILocalReferenceExpression: i (OperationKind.LocalReferenceExpression, Type: System.Int32)
        Right: ILiteralExpression (OperationKind.LiteralExpression, Type: System.Int32, Constant: 1)
  IBlockStatement (0 statements) (OperationKind.BlockStatement)
```

Visual Basic code:
```VB.NET
For i As Integer = 1 To 5
Next
````

Resulting IOp Tree:
```
IForLoopStatement (LoopKind.For) (OperationKind.LoopStatement)
  Condition: IBinaryOperatorExpression (BinaryOperationKind.IntegerLessThanOrEqual) (OperationKind.BinaryOperatorExpression, Type: System.Boolean)
      Left: ILocalReferenceExpression: i (OperationKind.LocalReferenceExpression, Type: System.Int32)
      Right: ILiteralExpression (Text: 5) (OperationKind.LiteralExpression, Type: System.Int32, Constant: 5)
  Before: IExpressionStatement (OperationKind.ExpressionStatement)
      IAssignmentExpression (OperationKind.AssignmentExpression, Type: System.Int32)
        Left: ILocalReferenceExpression: i (OperationKind.LocalReferenceExpression, Type: System.Int32)
        Right: ILiteralExpression (Text: 1) (OperationKind.LiteralExpression, Type: System.Int32, Constant: 1)
  AtLoopBottom: IExpressionStatement (OperationKind.ExpressionStatement)
      ICompoundAssignmentExpression (BinaryOperationKind.IntegerAdd) (OperationKind.CompoundAssignmentExpression, Type: System.Int32)
        Left: ILocalReferenceExpression: i (OperationKind.LocalReferenceExpression, Type: System.Int32)
        Right: IConversionExpression (ConversionKind.Basic, Explicit) (OperationKind.ConversionExpression, Type: System.Int32, Constant: 1)
            ILiteralExpression (OperationKind.LiteralExpression, Type: System.Int32, Constant: 1)
  IBlockStatement (0 statements) (OperationKind.BlockStatement)
```

There are a few differences here.
1. There's no `IVariableDeclaration(Statement)` in VB. In fact, there doesn't appear to be any variable declarations in the accessible `IOperation` statements for VB.
2. There's some inconsistency with getting access to the `IForLoopStatement`. Both languages have, syntax-wise, a `ForStatement` construct. In C#, this refers to the entire block. In VB, this refers just to the `For i As Integer = 1 To 5` section, and is enclosed by a `ForBlock` construct. You can't get access to the `IForLoopStatement` from the `ForStatement`, only the `ForBlock`. While I can understand the difference between the languages here, perhaps we should allow getting the `IForLoopStatement` from the `ForStatement` in VB.

**Comment by 333fred** [comment]
@dotnet/analyzer-ioperation

**Comment by 333fred** [comment]
This issue also affects If Then Else loops as well. FYI @jinujoseph

**Comment by CyrusNajmabadi** [comment]
> While I can understand the difference between the languages here, perhaps we should allow getting the IForLoopStatement from the ForStatement in VB.

VB statement/block handling has always been a bit baroque.  We'll likely want to make an decision here across all VB statements.  I view that as orthogonal to any other issues we find with individual elements.

**Comment by jinujoseph** [comment]
> While I can understand the difference between the languages here, perhaps we should allow getting the IForLoopStatement from the ForStatement in VB.

Design Decision:
We will not allow for this.  It means you have a situation where two syntax nodes in a language will point to the same IOPeration.  Then the IOperation's '.Syntax' will not poitn back at one of these.  That violates a previous design decision.

For now, let's keep things similar between the languages.  We'll only support getting the Operation on the VB block, and not on hte header statement.

**Comment by jinujoseph** [comment]
> There's no IVariableDeclaration(Statement) in VB. In fact, there doesn't appear to be any variable declarations in the accessible IOperation statements for VB.

This should be fixed by whoever works on these constructs.  Any declared variables should show up in the operation tree somehow.

**Comment by jinujoseph** [comment]
this should be fixed as per our new design forloops
