### ISSUE TITLE
VS is deadlocking when attempting to open ProjectSystem.sln

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#17997]
**Version Used**: 
VS 2017 RTW - 15.0.0+26228.9

**Steps to Reproduce**:

1. Enlist in the dotnet/roslyn-project-system repo
2. Clean your nuget cache
3. Run `.\build.cmd`
4. Open `src\ProjecySystem.sln`

**Expected Behavior**:
It works

**Actual Behavior**:
VS Deadlocks

**Dump**
[internal-mlang-share]\public\tagoo\Dumps\devenv_PackageInstallerServiceFactory_EnableService.dmp

![image](https://cloud.githubusercontent.com/assets/10487869/24118361/bcceb93c-0d6a-11e7-83a8-900be59fae82.png)

![image](https://cloud.githubusercontent.com/assets/10487869/24118369/c13f15d4-0d6a-11e7-864d-a1d5779b8f6f.png)

**Comment by davkean** [comment]
Shouldn't be calling _serviceProvider.GetService on a background thread.

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by davkean** [comment]
As a side note, the project system repo has started to move away from IServiceProvider to our own [IVsService<T>](https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/IVsService%601.cs) implementation so that we can import it - we assert if you pull on it on a non-UI thread to catch these sorts of issues.

**Comment by CyrusNajmabadi** [comment]
Roslyn is not safe to call SetSite on on a BG thread.   AFAIK, we've never supported such a thing.  Tagging @jasonmalinowski

**Comment by davkean** [comment]
Oh, ignore me - didn't see that on the stack, that might be the UI thread.

**Comment by davkean** [comment]
I can see the problem, the UI thread is blocked and ExtensibleSourceRepository is trying to access UI thread in MEF creation, doesn't look like a Rolsyn bug.

**Comment by Pilchie** [comment]
Resolving per @davkean's comments.

**Comment by tannergooding** [comment]
@davkean, who owns this bug then? I can't seem to find `ExtensibleSourceRepository` or who owns it.
