### ISSUE TITLE
[IOperation] No top-level block access in VB

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#17999]
In C#, we can access all `IOperation`s in a method by getting the operation on the top-level syntax `Block` for a method. There is no equivalent way to go from a syntax node to all `IOperation`s in VB (that I can find).

Related: perhaps we should also be able to move from a `MethodDeclaration` (C#) or `SubBlock` (VB) to this top-level block in both languages. When I first tried out `IOperation`, that's certainly one of the first things that threw me for a loop.

@dotnet/analyzer-ioperation

**Comment by mavasani** [comment]
I think @CyrusNajmabadi opened an issue for this.. let me try to find it

**Comment by mavasani** [comment]
Related to https://github.com/dotnet/roslyn/issues/11860

**Comment by 333fred** [comment]
This is actually a dup of #8919, linked from that bug. I'll update our uber-tracking bug to track that one instead.
