### ISSUE TITLE
Question: ScriptEngine

### ISSUE THREAD

**Issue by KamyarNazeri** [dotnet/roslyn#18]
Is there going to be any signs of `ScriptEngine` in the final release of Roslyn as we saw in previous CTP?

**Comment by DustinCampbell** [comment]
We haven't abandoned scripting, but needed to stop working on it a couple of years ago to focus on finishing the compilers. Hopefully, we'll have some news to share soon.

**Comment by KamyarNazeri** [comment]
:+1:

**Comment by mattwar** [comment]
The ScriptEngine type specifically?  No. I changed the API. :innocent:

**Comment by DustinCampbell** [comment]
Oh yes, @mattwar did change the API. It'll be way better than it was when it finally sees the light of day. :smiley:

**Comment by mysticatea** [comment]
I'm looking forward to the news.

**Comment by MattGertz** [comment]
As Dustin says, we'll have more to say on all of this Real Soon Now.  Lotsa other stuff has been taking all of our cycles, keeping us from writing out a cogent plan here, but we're starting to get some breathing room now for that.  Apologies for the delay!

**Comment by dfkeenan** [comment]
Really looking forward to news about what's happening in this space.  Hopefully I will be able to pick-up the project I dropped when you shelved the feature.

P.S.  I am almost as excited about it as I am about HoloLens.

**Comment by ManishJayaswal** [comment]
You should be able to see them now!!

**Comment by jaredpar** [comment]
https://github.com/dotnet/roslyn/tree/master/src/Scripting

**Comment by DustinCampbell** [comment]
Yup -- this is now done with commit ef547b73e65129809e01392585406815c904d021.
