### ISSUE TITLE
Signed builds are taking longer than they should

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#18008]
Right now our signed build takes about 40 minutes to actually build and run tests, and then over an hour to actually publish bits, index them, and other silly tasks. It should be a lot faster than it is.

**Comment by CyrusNajmabadi** [comment]
@dibarbet is this still an issue with all the work we've done?  can we close this out?

**Comment by dibarbet** [comment]
I think we can close it.  Signed builds still can take a while, but the majority of that is due to signing which takes an intentionally random long amount of time.  Nothing we control.
