### ISSUE TITLE
[IOperation] Multiple Variable declaration inconsistency

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18000]
Take the following sample code:
```C#
void Test() {
    int i1 = 1, i2 = 2;
}
```
This produces the following syntax tree:
![image](https://cloud.githubusercontent.com/assets/2371880/24120834/33fc684e-0d73-11e7-87ea-27b1ce4dc719.png)

If you get the `IOperation` tree for the `VariableDeclaration`, you get the following:
```
IVariableDeclarationStatement (2 variables) (OperationKind.VariableDeclarationStatement)
  IVariableDeclaration: System.Int32 test (OperationKind.VariableDeclaration)
    Initializer: ILiteralExpression (Text: 1) (OperationKind.LiteralExpression, Type: System.Int32, Constant: 1)
  IVariableDeclaration: System.Int32 test2 (OperationKind.VariableDeclaration)
    Initializer: ILiteralExpression (Text: 2) (OperationKind.LiteralExpression, Type: System.Int32, Constant: 2)
```

If you get the `IOperation` tree for either of the `VariableDeclarator`s, you get this tree:
```
IVariableDeclarationStatement (1 variables) (OperationKind.VariableDeclarationStatement)
  IVariableDeclaration: System.Int32 test (OperationKind.VariableDeclaration)
    Initializer: ILiteralExpression (Text: 1) (OperationKind.LiteralExpression, Type: System.Int32, Constant: 1)
```

Seems like we're unnecessarily synthesizing an `IVariableDeclarationStatement` here, I'd expect to just get back the `IVariableDeclaration` for that variable.

@dotnet/analyzer-ioperation

**Comment by mavasani** [comment]
+1, completely agree. We should stop synthesizing nodes here and be consistent in what we return.

**Comment by 333fred** [comment]
There's also a VB difference here, which we should fix whenever we do this C# work as well: getting the `IOperation` tree on either `VariableDeclarator` in the equivalent VB code returns null. It should be returning the individual `IVariableDeclaration` as well.

**Comment by jinujoseph** [comment]
@333fred is this being addressed with your recent changes

**Comment by 333fred** [comment]
No, this is entirely separate from IVariableDeclaration refactor PR. This will need to be a change in the code that gets IOperations when given a syntax node.

**Comment by 333fred** [comment]
Tracking with https://github.com/dotnet/roslyn/issues/18068.
