### ISSUE TITLE
[IOperation] Getting IOperation of VariableDeclarator returns null or throws

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18019]
When you call `GetOperation` on a `VariableDeclarator` in VB, you get either a null return, or an assert, depending on the context. If it's a single variable, you get a null return. If it's a multi-variable statement, such as `Dim i1, i2 As New Integer`, you get the following assert:
![image](https://cloud.githubusercontent.com/assets/2371880/24162885/27fb1276-0e26-11e7-91a2-8de2330abd1d.png)

Getting the `IOperation` for `VariableDeclarator` works as expected in C#.

**Comment by 333fred** [comment]
FYI @dotnet/analyzer-ioperation

**Comment by jinujoseph** [comment]
@heejaechang this should be fixed right ?

**Comment by 333fred** [comment]
The crash is fixed, but we have a new issue tracked here: https://github.com/dotnet/roslyn/issues/22362.
