### ISSUE TITLE
[IOperation] Stop synthesizing ISwitchStatement when given a CaseSwitchLabel

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18042]
Given the following method:
```C#
static void Main(string[] args)
{
    int i = 1;
    switch(i)
    {
        case 1: break;
        case 2: break;
        default: break;
    }
}
```
the following syntax tree is produced:
![image](https://cloud.githubusercontent.com/assets/2371880/24177304/d46142aa-0e5e-11e7-8754-d1d3480c3c3a.png)
Attempting to get the `IOperation` for the `SwitchSection` and `CaseSwitchLabel`/`DefaultSwitchLabel` nodes returns an `ISwitchStatement` for the entire switch statement. It should be returning the `ISwitchCase` or `ISingleValueClause` (or other clause, as appropriate), respectively. This is highly annoying, as you can't get the individual `IOperation` from a `SyntaxNode`.

**Comment by 333fred** [comment]
VB has the opposite problem. Given the following VB code:
```VB.NET
Module Program
    Sub Main(args As String())
        Dim number As Integer = 8
        Select Case number
            Case 1 To 5
                Console.WriteLine("Between 1 and 5")
            Case 6, 7, 8
                Console.WriteLine("Between 6 and 8")
            Case 9 To 10
                Console.WriteLine("Equal to 9 or 10")
            Case Else
                Console.WriteLine("Not between 1 and 10")
        End Select
    End Sub
End Module
```
the following syntax tree is produced:
![image](https://cloud.githubusercontent.com/assets/2371880/24177513/4e0c28c6-0e60-11e7-9a88-57b7d7406f3e.png)

Getting the `IOperation` for `CaseBlock` returns the `IBlockStatement` of the case body, not an `ISwitchCase`. Getting the `IOperation` for the `CaseStatement` causes the following assert:

![image](https://cloud.githubusercontent.com/assets/2371880/24177556/8e680c14-0e60-11e7-999a-6f3ed00fdaec.png)

**Comment by 333fred** [comment]
@dotnet/analyzer-ioperation

**Comment by CyrusNajmabadi** [comment]
great  catches.

**Comment by jinujoseph** [comment]
@heejaechang good to close this ? we have tests for this ?

**Comment by heejaechang** [comment]
@jinujoseph this should be fixed now, but not sure whether there is a test or not.

**Comment by jinujoseph** [comment]
test tracked separately
