### ISSUE TITLE
Remove IUnboundLambda

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#18057]
1. Paste the following code in ETA:
```
using System;

class Program
{
    static void Main(string[] args)
    {
        var x = () => F();
    }

    static void F()
    {
    }
}
```
2. Display IOperation tree for the EqualsValueClauseSyntax. Note that we have **no IOperations** for code inside the lambda body.
```
IOperation tree for "= () => F()"

IVariableDeclarationStatement (1 variables) (OperationKind.VariableDeclarationStatement, IsInvalid)
  IVariableDeclaration: var x (OperationKind.VariableDeclaration)
    Initializer: IUnboundLambdaExpression (OperationKind.UnboundLambdaExpression, Type: null)
```
3. Display IOperation tree for the ParenthesizedLambdaExpressionSyntax.
```
IOperation tree for "() => F()"

ILambdaExpression (Signature: lambda expression) (OperationKind.LambdaExpression, Type: null)
  IBlockStatement (1 statements) (OperationKind.BlockStatement)
    IExpressionStatement (OperationKind.ExpressionStatement)
      IInvocationExpression (static void Program.F()) (OperationKind.InvocationExpression, Type: System.Void)
```

I expected the IOperation tree in 3. to be a sub-tree of IOperation tree of 2.

**Comment by mavasani** [comment]
Tagging @dotnet/analyzer-ioperation

**Comment by mavasani** [comment]
This might actually be a missing API issue. UnboundLambda generally has a BoundLambda for error recovery, we should probably expose it. @AlekseyTs your thoughts?

**Comment by AlekseyTs** [comment]
> This might actually be a missing API issue. UnboundLambda generally contains a BoundLambda node within it for error recovery, we should probably expose it.

I think the IUnboundLambdaExpression should not be a part of the API.

**Comment by mavasani** [comment]
@jinujoseph @CyrusNajmabadi can we add this issue to the list of API discussions for next week?

**Comment by jinujoseph** [comment]
**Design Team Decision**

We are in agreement that IUnboundLambdaExpression  should not be part of our API, it's not correct and appropriate. It would be great if we expose ILamda where we give the best effort to get the  
Method symbol and the body.
