### ISSUE TITLE
IIncrementExpression exposes both UnaryOperatorKind and BinaryOperatorKind

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#18056]
[IIncrementExpression](http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/IExpression.cs,1290) exposes UnaryOperatorKind but it's base type [ICompoundAssignmentExpression](http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/IExpression.cs,1280) expose BinaryOperatorKind.

Tagging @dotnet/analyzer-ioperation and @heejaechang who is working on unary operator tests.

**Comment by jinujoseph** [comment]
Refer https://github.com/dotnet/roslyn/issues/8834 while fixing as well.

**Comment by jinujoseph** [comment]
**Design Team Notes**

We need to simplify the hierarchy, The intend here is we are not going to have the complex inheritance hierarchy where in the same hierarchy there is  lot of base.  We should try to make it more flat and narrow. IExpression might have Iincrementexpression, IcompondAssignment , IAssignementExpression and those themselves can implement side hierarchy, which can be technically called as infos which are not Ioperation Kind , Say IAssignmentInfos

Also look at #8834,#8835 while fixing this as well.

**Comment by mavasani** [comment]
@heejaechang Did we check in unit tests for unary operations?

**Comment by jinujoseph** [comment]
Nope, it's still pending https://github.com/dotnet/roslyn/pull/18136

**Comment by heejaechang** [comment]
@mavasani ha ha not yet!

**Comment by jinujoseph** [comment]
@heejaechang , you can close this issue onces the test is checked in.
