### ISSUE TITLE
Wrong or misleading behavior of DataFlowAnalysis.WritterInside

### ISSUE THREAD

**Issue by aka-STInG** [dotnet/roslyn#18051]
**Version Used**: 
2.0.0
**Steps to Reproduce**:

I'm writing translation tool to other language and need to detect if structs are modified inside method to mimic this behavior in another language.
Input:
```
public struct Foo
{
    public int Boom;
    public void Bar()
    {
    }
}
public class MyClass
{
    public void Test(Foo foo)
    {
        foo.Bar();
    }
}
```

**Expected Behavior**:

DataFlowAnalysis.WrittenInside does not contain "foo" parameter as documentation says "The set of local variables that are written inside a region.".

**Actual Behavior**:
DataFlowAnalysis.WrittenInside does contain "foo".

**Comment by bkoelman** [comment]
Sounds like a duplicate of https://github.com/dotnet/roslyn/issues/14886.

**Comment by gafter** [comment]
Yes, it is a duplicate.
