### ISSUE TITLE
Brace matching does not support two-chars braces

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/roslyn#18050]
In F# we have braces that contain two and more characters: `[| |]`, `{| |}`, `<@ @>`, `<@@ @@`>.

For the following code:

```fsharp
module File2

let foo = [|  |]
```
our `IBraceMatcher` implementation returns right spans:

![image](https://cloud.githubusercontent.com/assets/873919/24188166/661298ba-0ef1-11e7-94da-d7d19b923661.png)

![image](https://cloud.githubusercontent.com/assets/873919/24188199/82ee2eae-0ef1-11e7-997c-76f477bb4594.png)

but as a result, the braces are not highlighted:

![image](https://cloud.githubusercontent.com/assets/873919/24188226/97e3698c-0ef1-11e7-981b-e5943cf60458.png)

/cc @Pilchie @cloudRoutine

**Comment by vasily-kirichenko** [comment]
(`leftSpan` and `rightSpan` order are wrong on the screenshots, but fixing that does not help).

![image](https://cloud.githubusercontent.com/assets/873919/24193286/dab2088e-0f02-11e7-9d15-edfcaa99d949.png)
![image](https://cloud.githubusercontent.com/assets/873919/24193305/e647aeba-0f02-11e7-82bb-7ce9cb87b88d.png)
![image](https://cloud.githubusercontent.com/assets/873919/24193310/eee1c088-0f02-11e7-9d60-c2a93da100f2.png)
![image](https://cloud.githubusercontent.com/assets/873919/24193330/f97ec13a-0f02-11e7-9cab-2e94ad0cd76d.png)
![image](https://cloud.githubusercontent.com/assets/873919/24193341/0192cbd2-0f03-11e7-986b-6b6273d662fe.png)
![image](https://cloud.githubusercontent.com/assets/873919/24193351/09ed838a-0f03-11e7-809d-494e02c278ac.png)
![image](https://cloud.githubusercontent.com/assets/873919/24193360/10d7cc8c-0f03-11e7-8a98-f4e20c9b4868.png)
![image](https://cloud.githubusercontent.com/assets/873919/24193368/16e0f5a4-0f03-11e7-9bd4-00b9549f4e12.png)

The problem is here http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/BraceMatching/BraceHighlightingViewTaggerProvider.cs,76

You check that the cursor at the start or either span:
```csharp
if ((!rightBrace && braces.Value.LeftSpan.Start == position) ||
    (rightBrace && braces.Value.RightSpan.Start == position))
{ ...
```
So a possible fix would be:
```csharp
if ((!rightBrace && braces.Value.LeftSpan.IntersectsWith(position)) ||
    (rightBrace && braces.Value.RightSpan.IntersectsWith(position)))
{ ...
```
Does it make sense?

**Comment by CyrusNajmabadi** [comment]
I dont' know why we have that if-condition at all...

**Comment by CyrusNajmabadi** [comment]
Ok.  I've update the code for the roslyn brace highlighter.   We will give you the position of the character we want to get matching braces for. 

Thanks!

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/issues/18118
