### ISSUE TITLE
IConversionExpression must expose IsChecked boolean

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#18055]
BoundConversion nodes in both compilers have this flag. We should expose this flag on [IConversionExpression](http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/IExpression.cs,925).

**Comment by mavasani** [comment]
Tag @dotnet/analyzer-ioperation

**Comment by CyrusNajmabadi** [comment]
We will do this.

**Comment by 333fred** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/21040.
