### ISSUE TITLE
[IOperation] `GetOperation` returns a superset of IOperations for given syntax nodes

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18064]
Uber-tracking issue for all instances of this. We seem to have a pattern of returning an `IOperation` that contains the expected operation for a given syntax node, rather than returning just the operation for that syntax node.

* [ ] https://github.com/dotnet/roslyn/issues/18042 `switch` Statements
* [ ] https://github.com/dotnet/roslyn/issues/18061 `fixed` Statements 
* [ ] https://github.com/dotnet/roslyn/issues/18062 `using` Statements
* [ ] https://github.com/dotnet/roslyn/issues/18068 Variable declarations
* [ ] https://github.com/dotnet/roslyn/issues/18405 Argument expressions

**Comment by jinujoseph** [comment]
We dont' need the uber bug.  All these are legitimate issues that just need to be fixed.  Our design is that if you ask for a sub-syntax-node you should get the operation whose syntax points to that node.  So all this existing behavior is definitely broken.
