### ISSUE TITLE
SemanticModel.GetOperation returns Nothing for EqualsValueSyntax in local declarations in VB

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#18070]
SemanticModel.GetOperation returns a valid IOperation tree for EqualsValueClauseSyntax (C#), but returns null for EqualsValueSyntax (VB).

**Comment by mavasani** [comment]
This seems to be the case in VB only for EqualsValueSyntax within local initializers. It returns non-null IOperation in field and parameter initializers, so this just looks like a VB bug.

**Comment by jinujoseph** [comment]
dupe https://github.com/dotnet/roslyn/issues/22429
