### ISSUE TITLE
IDE0018 suggested incorrectly withing usings

### ISSUE THREAD

**Issue by twcclegg** [dotnet/roslyn#18076]
**Version Used**: 
VisualStudio/15.0.0+26228.9

**Steps to Reproduce**:
```c#
class Example
{
    static void Main()
    {
        var fileDescriptors = GetFileDescriptors();
        string fileType;
        using (var f = GetFile(fileDescriptors, out fileType))
        {
            /* Do things */
        }
        Console.WriteLine(fileType);
    }
}
```

**Expected Behavior**:
IDE0018 is not suggested

**Actual Behavior**:
IDE0018 suggests:
```c#
class Example
{
    static void Main()
    {
        var fileDescriptors = GetFileDescriptors();
        using (var f = GetFile(fileDescriptors, out string fileType))
        {
            /* Do things */
        }
        Console.WriteLine(fileType);
    }
}
```
This causes error CS0103 `The name 'fileType' does not exist in the current context`

**Comment by NSentinel** [comment]
I got similar behaviour, posted [here](https://developercommunity.visualstudio.com/content/problem/34307/ide0018-variable-declaration-can-be-inlined-shown-1.html#): 

A variable declaration inside `while` can't be used outside of cycle (seems variable scope is exactly one above method call) but IDE still suggests to inline. Result source after transformation can't be compiled.

Example:

```csharp
         SocketProtocolPair socketProtocolPair;

         while (!_socketProtocolPairPool.TryDequeue(out socketProtocolPair))
         {
             PreAllocSocketProtocolPairs((int)(_runtimeConfiguration.MemoryBackedConnectionsCount * PoolAutoGrowCoeff));
         }

         socketProtocolPair.Protocol = protocol;
```

Transformed to:

```csharp
         while (!_socketProtocolPairPool.TryDequeue(out SocketProtocolPair socketProtocolPair))
         {
             PreAllocSocketProtocolPairs((int)(_runtimeConfiguration.MemoryBackedConnectionsCount * PoolAutoGrowCoeff));
         }

         socketProtocolPair.Protocol = protocol;
```

Compilation result:

Error `CS0103 The name 'socketProtocolPair' does not exist in the current context`

**Comment by NSentinel** [comment]
#17624

**Comment by sharwell** [comment]
:memo: This issue also occurs in the following cases:

### The `when` clause of an exception handler:

```csharp
int x;
try
{
}
catch when (GetValue(out x))
{
}

Console.Write(x);
```

### Expressions which may or may not be evaluated

```csharp
int x
bool value = false && GetValue(out x);
Console.Write(x);
```

### Fixed statements

```csharp
int x;
fixed (int* p = GetValue(out x))
{
}

Console.Write(x);
```
