### ISSUE TITLE
Add documentation for pathmap command-line flag

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#18071]
Please add documentation for the /pathMap command-line flag.

**Comment by gafter** [comment]
I see there is already a one-line description in https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/CommandLine.md

We have online docs for the compiler flags maintained by... is it still @billchi-ms ?

**Comment by jcouv** [comment]
A doc issue has been opened to track this: https://github.com/dotnet/docs/issues/1800
@gafter, ok to close OP issue?
