### ISSUE TITLE
Add using should try looking at the fully qualfiied name to pick which of multiple options to add

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#18072]
Consider this invocation on the second error in the Roslyn codebase:

![image](https://cloud.githubusercontent.com/assets/201340/24215904/8735e924-0ef7-11e7-8ae8-546c129c5ce5.png)

Two suggestions are given because we (unfortunately) have two separate types named "Traits". But in the second case, we know that only one of them has a member called Features.Build, so we could distinguish.

**Comment by Pilchie** [comment]
We might have a dupe of this somewhere...

**Comment by CyrusNajmabadi** [comment]
Havne't heard any feedback on this.  Closing out.
