### ISSUE TITLE
Remove language dependency on compiler server

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#18083]
The compiler server has a hard dependency on both the C# and VB compiler libraries.  This means in order to ship on language with server support we must essentially ship both languages.  It doesn't fully require csc / vbc be shipped but those binaries are small compared the the underlying libraries. 

There are customers who want to ship only one language.  Need to change the dependencies here to make that possible.

**Comment by jcouv** [comment]
This feels like a new feature. Should it be moved out of 15.3 at this point?

**Comment by jaredpar** [comment]
Yes.  It's also possible this may not be relevant anymore.  I thought I had moved out all of our remaining CLI work but missed this one.

**Comment by jaredpar** [comment]
This is no longer relevant as the VB language ships by default in CLI now.
