### ISSUE TITLE
Duplicate setting in .editorconfig causes whole file to be ignored silently

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#18087]
**Version Used**: 
Visual Studio Professional 2017 RTM (15.0.0+26228.9)

**Steps to Reproduce**:
1. Create an .editorconfig on the .sln level.
2. Add any valid settings to it.
3. Add a duplicate setting, e.g.
```
csharp_style_conditional_delegate_call = true:suggestion
csharp_style_conditional_delegate_call = true:suggestion
```
4. Open solution in Visual Studio

**Expected Behavior**:
One of the following:
1. Valid settings are picked up and the duplicate setting is either ignored or first/last value wins
2. There is clear error or warning visible somewhere within VS 2017 that explains the problem

**Actual Behavior**:
Settings in .editorconfig are silently ignored (I had to debug VS to diagnose).

**Comment by sharwell** [comment]
According to the following text from editorconfig.org (emphasis mine), I believe that the correct behavior is the last one wins.

> EditorConfig files **are read top to bottom** and the closest EditorConfig files are read last. Properties from matching EditorConfig sections are **applied in the order they were read**, so properties in closer files take precedence.

**Comment by Pilchie** [comment]
Tagging @olegtk to chime in here too.

**Comment by olegtk** [comment]
It sounds like a bug to me, please file an internal bug.

**Comment by jasonmalinowski** [comment]
Isn't this what @sharwell was looking at?

**Comment by sharwell** [comment]
@jasonmalinowski @olegtk Yes, this is what I was looking at. I plan to file the internal bug on Monday.

**Comment by sharwell** [comment]
@ashmind The code responsible for this issue isn't part of an open source project. I've filed an internal bug to get it resolved.
