### ISSUE TITLE
VS2017 crashes when opening VBproj created with VS2015

### ISSUE THREAD

**Issue by rahulpaw** [dotnet/roslyn#18098]
**Version Used**: 2.0.0.61501

**Steps to Reproduce**:

1.  Install VS 2017 RTM
2.  Open the attached project
[Catalog.UnitTests.zip](https://github.com/dotnet/roslyn/files/863799/Catalog.UnitTests.zip)
[devenvopenvdev14vbproj.txt](https://github.com/dotnet/roslyn/files/863805/devenvopenvdev14vbproj.txt)

**Expected Behavior**: The project should open properly. This particular project is a VB unit testing project that was created from VS 2013. 

**Actual Behavior**: The VS crashes. The call stack shows Microsoft.VisualStudio.LanguageServices.VisualBasic.dll entries at the top.
The issue was raised at https://developercommunity.visualstudio.com/content/problem/25532/cannot-open-vs-2013-unit-test-solution.html

**Comment by jcouv** [comment]
Based on the linked stack trace, it looks like a project system issue.
@srivatsn Can you take a look and route/assign?

```
>	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler)	Unknown
 	Microsoft.VisualStudio.LanguageServices.VisualBasic.dll!Microsoft.VisualStudio.LanguageServices.VisualBasic.ProjectSystemShim.VisualBasicProject.SetCompilerOptions(ref Microsoft.VisualStudio.LanguageServices.VisualBasic.ProjectSystemShim.Interop.VBCompilerOptions pCompilerOptions)	Unknown
 	[Native to Managed Transition]	
 	mscorlib.dll!System.IO.Path.Combine(string path1, string path2)	Unknown
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.Legacy.AbstractLegacyProject.TryGetOutputPathFromHierarchy
```

**Comment by srivatsn** [comment]
This issue was moved to dotnet/project-system#1936

**Comment by Pilchie** [comment]
I'm pretty sure I've seen this before from Watson.  I think it might be when you have a Web project that targets a .NET Framework version that you don't have the targeting pack installed.
