### ISSUE TITLE
Microsoft.CodeAnalysis.Location.Create: System.ArgumentNullException

### ISSUE THREAD

**Issue by zezba9000** [dotnet/roslyn#18095]
**Version Used**: 
Microsoft Visual Studio Community 2017
Version 15.0.26228.9 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01586
Installed Version: Community
Visual C# 2017   00369-60000-00001-AA757
Microsoft Visual C# 2017

**Steps to Reproduce**:
I think It started to happen after I added the "System.ValueTuple" to my classic .NET Framework dll project.

Here is the stack trace:

> System.ArgumentNullException : Value cannot be null.
> Parameter name: syntaxTree
>    at Microsoft.CodeAnalysis.Location.Create(SyntaxTree syntaxTree,TextSpan textSpan)
>    at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.CreateSourceLocation(String filePath,Int32 start,Int32 length)
>    at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadLocation()
>    at Microsoft.CodeAnalysis.SymbolKey.Reader`1.ReadArray[T](Func`1 readFunction)
>    at Microsoft.CodeAnalysis.SymbolKey.TupleTypeSymbolKey.Resolve(SymbolKeyReader reader)
>    at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadWorker(SymbolKeyType type)
>    at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadSymbolKeyWorker(Boolean first)
>    at Microsoft.CodeAnalysis.SymbolKey.Resolve(String symbolKey,Compilation compilation,Boolean ignoreAssemblyKey,CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.ExtractMethod.Extensions.ResolveType[T](SemanticModel semanticModel,T symbol)
>    at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.AnalyzerResult..ctor(SemanticDocument document,IEnumerable`1 typeParametersInDeclaration,IEnumerable`1 typeParametersInConstraintList,IList`1 variables,VariableInfo variableToUseAsReturnValue,ITypeSymbol returnType,Boolean awaitTaskReturn,Boolean instanceMemberIsUsed,Boolean endOfSelectionReachable,OperationStatus status)
>    at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
>    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by gafter** [comment]
This appears to be related to the issue that newly constructed nodes don't have a tree. I believe there is another issue tracking this.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/17863
