### ISSUE TITLE
Adding Analyzers Via a Project Reference

### ISSUE THREAD

**Issue by JasonBock** [dotnet/roslyn#18093]
**Version Used**: 

Visual Studio 2017 (though this applies to 2015 as well)

**Steps to Reproduce**:

I'd like to be able to add analyzers to a project via a project reference. For example, let's say I have this solution setup:

* Solution
  * ProjectA
  * ProjectB

ProjectB contains analyzers that are only used for code in ProjectA. I can only add analyzers from an assembly reference, not a project reference. I can do this now by referencing the DLL created by building ProjectA (e.g. bin\Debug\ProjectA.dll) but then I run into weird rebuilding and locking issues from Visual Studio. I could get around this by using this approach to version the assembly (https://stackoverflow.com/questions/826777/how-to-have-an-auto-incrementing-version-number-visual-studio#826850) but then I can't really control its version number. It would be far simpler to have the ability to right-click on "Analyzers", select "Add Analyzers" and have the ability to reference a project.

**Expected Behavior**:

Being able to add analyzers via a project reference.

**Actual Behavior**:

That option doesn't exist.

(Note, this is more of a feature request than a bug, but I tried to conform to the given format)

**Comment by sharwell** [comment]
Getting this to work on the command line probably wouldn't be too difficult. The UI for adding the reference is almost complete as well - it's just that "Projects" section you see in the Add&rarr;Reference... dialog is not visible on the Add&rarr;Analyzer... dialog.

With that said, the implementation is *very* hard. In theory, typing a change in one file of your solution can affect the way the IntelliSense compiler behaves for other files in your solution. I don't have any specific proposal for the way it should behave at this time; I just wanted to point out which part of this feature request makes it particularly challenging.

But I have to admit. This would be one of the coolest features ever, so for that :+1:

**Comment by Pilchie** [comment]
I'm pretty sure @heejaechang has thought about using the second process for this in the long term, but it's unfortunately not likely to happen anytime soon.

**Comment by heejaechang** [comment]
great idea but that kind of dynamic analyzer change would be hard to track... my idea was little bit simpler version which make writing new analyzer easier. this idea if scoped down to special context of writing new analyzer then, could be done... actually.

**Comment by heejaechang** [comment]
@mavasani @jinujoseph how do you think? this seems good idea on our analyzer pad idea we had before.

**Comment by MartinJohns** [comment]
I would absolutely love this feature. Would make integrating custom analyzer much nicer without having the hassle of integrating a custom private NuGet feed first.

@heejaechang @Pilchie Did you make any progress or had any more discussions on this by chance?

**Comment by Pilchie** [comment]
Not yet I'm afraid :(

**Comment by heejaechang** [comment]
tagging @jinujoseph

**Comment by jinujoseph** [comment]
Very valuable , not sure we can fit this for 15.5 , lets target for dev16

**Comment by kierenj** [comment]
This would be awesome.  Currently we use "sanity check" unit tests, which use reflection and NCrunch to give feedback about certain classes not being serialisable, missing unit test classes, and hope to extend this to look at architecture rules.

I don't think many would mind if it's realtime or not (per-keypress on the analyser project): using the last-built version should be fine

**Comment by ericstj** [comment]
Have you tried doing:
```
    <ProjectReference Include="..\ProjectB\ProjectB.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <OutputItemType>Analyzer</OutputItemType>
    </ProjectReference>
```

**Comment by trigger-death** [comment]
```xml
    <ProjectReference Include="..\ProjectB\ProjectB.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <OutputItemType>Analyzer</OutputItemType>
    </ProjectReference>
```

This works, but when it seems to produce an unsightly warning on the Dependencies item due to it internally having some issue with the referenced project. The analyzer does work correctly though.

**Comment by ProductiveRage** [comment]
Does the 16.0 milestone mean that hopefully it will land in a release of Visual Studio 2019 one day?

I've used the suggested "ProjectReference" approach above and I don't get any "unsightly warning" (which I'm very happy about!). When I rebuild the Analyzer project, I have to unload any target project and then rebuild it but that's not too bad. It would be amazing if this _was_ built into VS, though!

**Comment by alrz** [comment]
>With that said, the implementation for the overall experience is very hard. In theory, typing a change in one file of your solution can affect the way the IntelliSense compiler behaves for other files in your solution

@sharwall Can this be reconsidered along with generators? since implementation challenges are somewhat similar.

**Comment by prashantchoudhary** [comment]
Adding  `OutputItemType=Analyzer` causes the build to fail with `Could not load file or assembly 'Microsoft.CodeAnalysis'` . It works without it though.  

I am building by doing `dotnet build`. I am on a Mac and I use Rider.

**Comment by fjmorel** [comment]
@prashantchoudhary I had a similar issue (but it was a compiler warning for me) that went away after I updated to the latest .NET SDK.

**Comment by prashantchoudhary** [comment]
Yes upgrading to .Net SDK 5 fixed this issue. But still don't understand why it wouldn't work with framework version 3.1

**Comment by jnm2** [comment]
SDK is dev tools, and SDK 5 may bring fixes to dev tools both when you are targeting framework version 5.0 and when you are targeting 3.1 and earlier.

**Comment by terrajobst** [comment]
Does this cover generators as well? Or should this be a separate issue? FWIW, I have this need much more for generators than for analyzers.

**Comment by RikkiGibson** [comment]
It should cover both analyzers and generators.

**Comment by sharwell** [comment]
Here's the form to use without any warnings in the dependencies node:

```xml
<ProjectReference Include="..\ProjectB\ProjectB.csproj"
                  OutputItemType="Analyzer"
                  ReferenceOutputAssembly="false"
                  SetTargetFramework="TargetFramework=netstandard2.0" />
```

**Comment by alrz** [comment]
Is it possible to have this built-in?
```xml
<ProjectReference Include="@(GeneratorProjectReference)"
                  OutputItemType="Analyzer"
                  ReferenceOutputAssembly="false"
                  SetTargetFramework="TargetFramework=netstandard2.0" />
```
```xml
<GeneratorProjectReference Include="..\ProjectB\ProjectB.csproj" />
```

**Comment by sharwell** [comment]
@dotnet/project-system @dotnet/msbuild-admins what do you think about `GeneratorProjectReference` (or perhaps `AnalyzerProjectReference`)?

**Comment by tmeschter** [comment]
`AnalyzerProjectReference` would be more consistent with existing naming--since analyzers came first and generators built on those, we effectively treat generators as a subset of analyzers.

More interesting than the name, however, is what features we build around this to make it truly useful:
  - Almost certainly we want to update the Add Reference Dialog to support creating `AnalyzerProjectReference` items.
  - Do we want a different representation of these `ProjectReference`s in the Dependencies node?
  - Do we need to pass additional information from the project system to the language service so it is aware that a particular analyzer/generator comes from a particular project?
  - When the user makes changes to the analyzer project, does VS automatically build the analyzer project, pick up the updated binary, and re-analyzer the dependent projects?

**Comment by drewnoakes** [comment]
> Do we want a different representation of these ProjectReferences in the Dependencies node?

The analyzers themselves should appear within the _Analyzers_ node. Perhaps we would also add an _Analyzers_ node as a child of specific project reference nodes, which would be consistent with how we display other kinds of items brought in by references (package content items, package build files, etc).

**Comment by terrajobst** [comment]
> 1. Almost certainly we want to update the Add Reference Dialog to support creating `AnalyzerProjectReference` items.
> 2. Do we want a different representation of these `ProjectReference`s in the Dependencies node?

(1) is the most impactful UX update IMHO. (2) would be neat, but much less valuable to me. Yes, I could see how it's useful for configuring the analzyer, but given that it's project reference I'm typically not interested and instead use the definition's default to adjust severity.

**Comment by davkean** [comment]
In the original design of .NET Core, `<PackageReference>` and `<ProjectReference>` were to be equivalent long term (so I could swap a PackageReference for a ProjectReference and everything would `just work`). I propose that we maintain this goal, and plumb this through as ProjectReference as an asset instead of introducing a new reference type. I suspect this will be significantly easier to represent too, as you won't need to teach every single consumer about a new reference concept.

**Comment by mavasani** [comment]
@sharwell The workaround you mentioned in https://github.com/dotnet/roslyn/issues/18093#issuecomment-1039415533 works fine, but analyzer does not flow transitively. For `ClassLibrary1.csproj -> Analyzer.csproj` and `ClassLibrary2.csproj -> ClassLibrary1.csproj`, analyzer lights up for ClassLibrary1 but not for ClassLibrary2. Do we know of any workaround to enable transitive flow?

**Comment by alrz** [comment]
>what features we build around this to make it truly useful:

Thanks for the response. I think the shortcut alone could be a huge help already as this is the first thing people will likely try when starting to write an analyzer so to me this seems like a barrier to adoption unless you know this issue exists and have it bookmarked. Also it's nice that the maintenance could be done internally in case the workaround is changed or removed entirely.

**Comment by sharwell** [comment]
> Do we know of any workaround to enable transitive flow?

I'm not aware of a way, but this would also likely not be desirable. Transitive flow for source generators (which behave the same as analyzers for packaging) tends to cause problems.

**Comment by davkean** [comment]
@mavasani Transitive flow of analyzers I would expect in the same way they are transitive for packages. This would just work if we went down the PackageReference route - the assets would just contain it.

**Comment by Bosch-Eli-Black** [comment]
> @sharwell The workaround you mentioned in [#18093 (comment)](https://github.com/dotnet/roslyn/issues/18093#issuecomment-1039415533) works fine, but analyzer does not flow transitively. For `ClassLibrary1.csproj -> Analyzer.csproj` and `ClassLibrary2.csproj -> ClassLibrary1.csproj`, analyzer lights up for ClassLibrary1 but not for ClassLibrary2. Do we know of any workaround to enable transitive flow?

@mavasani I can't comment on analyzers, but for our team's use case, we'd want our source generators to **not** be transitive 🙂

I suppose maybe this depends on what the purpose of the source generator is. In our case, we're taking in `.json` files and transforming them into C# code, which we'd like to happen only on specific projects.

**Comment by Nirmal4G** [comment]
@davkean

> In the original design of .NET Core, `<PackageReference>` and `<ProjectReference>` were to be equivalent long term (so I could swap a `PackageReference` for a `ProjectReference` and everything would "just work").

Currently `ProjectReference` requires a full path to the project file instead of a canonical name. In cases where the project, package and assembly names are different, how are we going to identify projects based on given package name? What about assets other than assembly references? How is `ProjectReference` going to expose the NuGet concepts?

**Comment by zivkan** [comment]
NuGet looks at the `PackageId` property, if it exists, when determining the restore inputs, and therefore the restore graph: https://github.com/NuGet/NuGet.Client/blob/c7c47b337eb399adc43cecc07b68f6a7cd838608/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L762

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not planning on changing how analyzers are referenced.

**Comment by terrajobst** [comment]
Sadness as this is the core reason I don't use them more.

**Comment by ChristophHornung** [comment]
So sad to see such a useful feature request that is also in the top20 of upvoted request being rejected.
