### ISSUE TITLE
Do not offer Change signature refactoring when not applicable

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/roslyn#18103]
**Version Used**: 
Visual Studio/15.0.0-RTW+26228.4

**Steps to Reproduce**:
See code example under Actual behavior.

**Expected Behavior**:
Not offered when there is no point to change the signature.

**Actual Behavior**:
In these examples:
 - you can't reorder (because there is only one),
 - remove any parameters (because it would break the code),
 - the lambda function is an anonymous method (so it is not called anywhere else), 
 - renaming a parameter is supported inline.

![image](https://cloud.githubusercontent.com/assets/9047283/24251280/e9fb622c-0fd9-11e7-9d1d-f7a76bcd153d.png)
![image](https://cloud.githubusercontent.com/assets/9047283/24251353/320a8a66-0fda-11e7-9923-6126eb3384a3.png)

![image](https://cloud.githubusercontent.com/assets/9047283/24251503/a7ab97c4-0fda-11e7-9c42-9ea39f80e46f.png)

**Comment by miloush** [comment]
It has been said elsewhere that breaking code is allowed, and that consistency of the quick fix being available is valued over users worrying why they can't invoke it...

**Comment by CyrusNajmabadi** [comment]
> remove any parameters (because it would break the code),

Meta-point:
All of change-signature may break things.  For example, reordering parameters on a method that is passed to some delegate-accepting function with some signature.

The point of the feature isn't to take you from correct-state-to-correct-state.  It's to help automate operations, especially those that would be quite tedious to do at scale.

--

That said, for lambdas i'm somewhat skeptical that this feature provides that much value (unless we cascade from the lambda to corresponding delegates and other callsites).  Will have to see how this is actually implemented to see if there are valuable cases i'm unaware of.

**Comment by Peter-Juhasz** [comment]
I can accept both points, but please consider my feedback:
One of the things I dislike Resharper (I don't even use it) is that "refactorings" are too intrusive, like "change private to public". There is always something you can change, but most of them has no value. In this case, when the light bulb appears, it triggers my mind that "hey, there is a refactoring available here", but when I expand it then I see that "oh, it's only Change signature..., which has no point here". So my point is, refactorings should be offered only if they provide value, in any other case, they only pollute the editor. For example, "organize usings" is not offered when usings are well organized.

**Comment by CyrusNajmabadi** [comment]
> So my point is, refactorings should be offered only if they provide value

Value is in the eye of the beholder :)

But your point is taken, and is not alone.  We are evaluating some potential options here we hope can help out.

**Comment by AdamSpeight2008** [comment]
@CyrusNajmabadi Only offer the change signature if the target method is the "user's code".

**Comment by CyrusNajmabadi** [comment]
Lambdas are the user's code :)

Also, if you look here: https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs#L94

you'll see that we should only ever offer this for symbols from source, and not metadata.

**Comment by AdamSpeight2008** [comment]
@CyrusNajmabadi  My mistake I thought it was on the `Parallel.For` not an argument to it. 👓

**Comment by Pilchie** [comment]
@kuhlenh Take a look at this thread.  @Peter-Juhasz how would you feel if a *differnt* icon appeared instead of the lightbulb if only refactorings were available, as opposed to suggestions/fixes?

**Comment by Peter-Juhasz** [comment]
@Pilchie I think the lightbulb is simple enough, if there are fixes then you also see squiggles in the editor, so I would keep simplicity and would not introduce a new icon. But even if there would be a different icon for refactoring, in this case I would not show it, because this refactoring has no value here.

What about showing it always in the context menu next to Organize usings, but showing only when it has value in the editor?

**Comment by Pilchie** [comment]
Okay - we made this much less intrusive (Change signature is only available at the definition, not the reference). We're still experimenting with the idea of a new icon, but I don't think we need this issue for it.

**Comment by CyrusNajmabadi** [comment]
PR was https://github.com/dotnet/roslyn/pull/17316.
