### ISSUE TITLE
CSharpEventHookup legacy integration test is timing out

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#18108]
The test is currently timing out and causing the jobs to fail.

**Comment by jasonmalinowski** [comment]
It's not juts timing out, it's outright crashing I think. I had some truly terrifying dumps I was looking at yesterday.

**Comment by Pilchie** [comment]
Please take a look ASAP

**Comment by Pilchie** [comment]
Deleted yet?

**Comment by rchande** [comment]
These have been deleted.
