### ISSUE TITLE
Cannot use nameof(variable) in the variable declaration

### ISSUE THREAD

**Issue by yallie** [dotnet/roslyn#18102]
**Version Used**: Microsoft (R) Visual C# version 1.3.1.60616

**Steps to Reproduce**:

```c#
struct Program
{
	static void Main()
	{
		// CS0841: cannot use variable 'local' before it is declared.
		var local = nameof(local);
	}
}
```

**Expected Behavior**:

The code should compile without errors. The name of the variable is already declared and it cannot change, so using the variable name is guaranteed to be safe.

**Actual Behavior**:

The compiler reports CS0841: cannot use variable 'local' before it is declared.

**Comment by alrz** [comment]
`string local = nameof(local);`.

**Comment by yallie** [comment]
Yes, I currently use it as a workaround.  
The point is, the type of `local` variable is irrelevant for the `nameof` expression.

**Comment by alrz** [comment]
For reference: https://github.com/dotnet/roslyn/blob/master/docs/designNotes/2015-03-04%20C%23%20Design%20Meeting.md

**Comment by yallie** [comment]
Thanks @alrz, I've overlooked #766.
