### ISSUE TITLE
2 potential perf improvement around code lens 

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#18101]
1. do cancellation more eagerly than what it is doing now. this should reduce numbers of unnecessary FAR from code lens.

2. reduce number of GetFullyQualifiedName calls. right now, when this file (http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax.xml.Syntax.Generated.cs#1) is opened, we get thousands of GetFullyQualifiedName calls. and that seems cause flashing on code lens taggers. this call doesn't look like either cancelled or scoped to the view making CPU to be 100% for a while.

**Comment by heejaechang** [comment]
@panopticoncentral opened a bug but not sure who I should assign it to or which label I should put.

**Comment by CyrusNajmabadi** [comment]
CLosing out as stale.
