### ISSUE TITLE
Assert fired at VisualStudioWorkspaceImpl.GetDocumentIdInCurrentContext for a document in shared project

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#1811]
1. Build Roslyn.sln from the main hive
2. Start devenv from the RoslynDev hive with the locally built bits, and open \Open\src\Roslyn.sln
3. Open source file VisualBasicDeclarationComputer.vb
4. Click on its base type `DeclarationComputer` in the inherits clause and hit F12

Got: Below assert fires with the given call stack. 
The host document here is `DeclarationComputer.cs`, which isfrom a shared project but the _"sharedHierarchy"_ is null.

`Contract.Requires(sharedHierarchy == LinkedFileUtilities.GetSharedHierarchyForItem(hostDocument.Project.Hierarchy, itemId));`

>	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.GetDocumentIdInCurrentContext(Microsoft.CodeAnalysis.DocumentId documentId) Line 901	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.CanNavigateToSpan(Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.DocumentId documentId, Microsoft.CodeAnalysis.Text.TextSpan textSpan) Line 42	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.GoToDefinition.GoToDefinitionHelpers.TryGoToDefinition(Microsoft.CodeAnalysis.ISymbol symbol, Microsoft.CodeAnalysis.Project project, System.Collections.Generic.IEnumerable<System.Lazy<Microsoft.CodeAnalysis.Editor.Host.INavigableItemsPresenter>> presenters, Microsoft.CodeAnalysis.ITypeSymbol containingTypeSymbol, bool throwOnHiddenDefinition, System.Threading.CancellationToken cancellationToken) Line 83	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.GoToDefinition.AbstractGoToDefinitionService.TryGoToDefinition(Microsoft.CodeAnalysis.Document document, int position, System.Threading.CancellationToken cancellationToken) Line 56	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.GoToDefinition.GoToDefinitionCommandHandler.TryExecuteCommand.AnonymousMethod__0(Microsoft.CodeAnalysis.Editor.Host.IWaitContext waitContext) Line 74	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.VisualStudioWaitIndicator.Wait(string title, string message, bool allowCancel, System.Action<Microsoft.CodeAnalysis.Editor.Host.IWaitContext> action) Line 38	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.GoToDefinition.GoToDefinitionCommandHandler.TryExecuteCommand(Microsoft.CodeAnalysis.Document document, int caretPosition, Microsoft.CodeAnalysis.Editor.IGoToDefinitionService goToDefinitionService) Line 68	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.GoToDefinition.GoToDefinitionCommandHandler.TryExecuteCommand(Microsoft.VisualStudio.Text.ITextSnapshot snapshot, int caretPosition) Line 54	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.GoToDefinition.GoToDefinitionCommandHandler.ExecuteCommand(Microsoft.CodeAnalysis.Editor.Commands.GoToDefinitionCommandArgs args, System.Action nextHandler) Line 40	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.ExecuteHandlers<Microsoft.CodeAnalysis.Editor.Commands.GoToDefinitionCommandArgs>(System.Collections.Generic.IList<Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.GoToDefinitionCommandArgs>> commandHandlers, Microsoft.CodeAnalysis.Editor.Commands.GoToDefinitionCommandArgs args, System.Action lastHandler) Line 97	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.Execute<Microsoft.CodeAnalysis.Editor.Commands.GoToDefinitionCommandArgs>(Microsoft.VisualStudio.Utilities.IContentType contentType, Microsoft.CodeAnalysis.Editor.Commands.GoToDefinitionCommandArgs args, System.Action lastHandler) Line 71	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.ExecuteGotoDefinition(Microsoft.VisualStudio.Text.ITextBuffer subjectBuffer, Microsoft.VisualStudio.Utilities.IContentType contentType, System.Action executeNextCommandTarget) Line 829	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.ExecuteVisualStudio97(ref System.Guid pguidCmdGroup, uint commandId, uint executeInformation, System.IntPtr pvaIn, System.IntPtr pvaOut, Microsoft.VisualStudio.Text.ITextBuffer subjectBuffer, Microsoft.VisualStudio.Utilities.IContentType contentType) Line 140	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.Exec(ref System.Guid pguidCmdGroup, uint commandId, uint executeInformation, System.IntPtr pvaIn, System.IntPtr pvaOut) Line 53	C#
 	Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(ref System.Guid pguidCmdGroup, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut)	Unknown
 	Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(ref System.Guid pguidCmdGroup, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut)	Unknown
 	Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.Exec(ref System.Guid pguidCmdGroup, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut)	Unknown
 	Microsoft.VisualStudio.Platform.WindowManagement.dll!Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.Exec(ref System.Guid pguidCmdGroup, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut)	Unknown
 	Microsoft.VisualStudio.Platform.WindowManagement.dll!Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Exec(ref System.Guid pguidCmdGroup, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut)	Unknown

**Comment by Pilchie** [comment]
@heejaechang can you take a look?

**Comment by heejaechang** [comment]
should be fixed with #1861
