### ISSUE TITLE
Language proposal for C# vNext (8?)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/roslyn#18126]
@jterry75 commented on [Thu Mar 23 2017](https://github.com/dotnet/corefx/issues/17449)

I find myself always writing code like:

```C#
enum States
{
    On,
    Off,
    InBetween
}

class Example
{
    public States State { get; }
}

class Program
{
    public static void Main(string[] args)
    {
        var t = new Example();
        // ...
        if (t.State == States.On || t.State == States.InBetween) // <- Interested here.
        {
             // Do something.
        }
    }
}
```

What if C# had an addition specifically for enum types to match as a language feature.
```C#
var t = new Example()
// ...
if (t.State.Is(On, InBetween)
{
    // Do Something
}
```

I can imagine that this has a few helpful optimizations. For 1 we only need to actually call `.State` once which means that we know the multiple calls are side-effect-free but for 2 we can actually infer the enum type exactly so we dont need its qualifiers.

```C#
enum WowWeWriteExtreemlyDescriptiveEnumNames
{
    A,
    B,
    C
}

var z = WowWeWriteExtremelyDescriptiveEnumNames.A;
// ...
if (z == WowWeWriteExtremelyDescriptiveEnumNames.A || 
    z == WowWeWriteExtremelyDescriptiveEnumNames.B)
{
    // Do Work
}
```
Goes to
```C#
if (z.Is(A, B))
{
    // Do Work
}
```

You could imagine for `[Flags]` enums we could match based on logical operation:
```C#
[Flags]
enum Test
{
    None = 0x0,
    A = 0x1,
    B = 0x2,
    C = 0x4
}

if (z.Is(A, B || C))
{
    // Do work
}
```

Ideas?

---

@danmosemsft commented on [Thu Mar 23 2017](https://github.com/dotnet/corefx/issues/17449#issuecomment-288870779)

@jterry75 thanks for the contribution. I'll move to what I think is the right repo
https://github.com/dotnet/roslyn

**Comment by Korporal** [comment]
This can kind of be achieved now with a little fiddling around:


    using System;
    using System.Linq;

    namespace Junk
    {
        public enum Sample
        {
            First,
            Second,
            Third
        }
        class Program
        {
            static void Main(string[] args)
            {
                Sample a = Sample.First;
                Sample b = Sample.Second;
                Sample c = Sample.Third;

                if (b.IsAny(Sample.Third, Sample.Second))
                {
                    ;
                }
            }
        }

        public static class EnumExtensions
        {
            public static bool IsAny<T>(this T Enum, params T[] Args) where T : struct, IComparable
            {
                return Args.Where(a => Enum.Equals(a)).Any();
            }
        }

**Comment by benknoble** [comment]
Note that the solution proposed by @Korporal isn't _completely_ type-safe: it can receive arguments conforming to the `where` clause (and should still operate as expected), not just `enums`. We could consider this a feature of the method rather than a bug, but it is notable that the method cannot guarantee `T` is an `enum`.

**Comment by jcouv** [comment]
The C# language design has moved to a separate repo: https://github.com/dotnet/csharplang
Please move this discussion over there.

**Comment by jterry75** [comment]
@Korporal - I do that roughly today but as @benknoble pointed out its kinda a hack. With `where T : enum` this would certainly be possible but I find it odd that given that constraint we would then require every project to implement the extension method which will just be exactly what you wrote. Seems like the language could just provide this in the `System` namespace or something.

@jcouv - I dont know how to 'move' an issue but I appreciate the tip on the new repo. Can you assist with the move?

**Comment by jcouv** [comment]
Issue moved to [dotnet/csharplang #330](https://github.com/dotnet/csharplang/issues/330) via [**ZenHub**](https://www.zenhub.com/)
