### ISSUE TITLE
Cannot create naming rules for type parameters and local variables

### ISSUE THREAD

**Issue by jonathanmarston** [dotnet/roslyn#18121]
In trying to configure naming rules in an .editorconfig, I've found that the current implementation of naming rules lacks the ability to target certain symbol kinds. In my scenario I need the ability to target type parameters and local variables.

Type parameters and variables should be supported symbol kinds both through the options UI in VS and through .editorconfig files.

**Comment by Pilchie** [comment]
@dpoeschl Is this something that we're already tracking elsewhere?  If so can you resolve as a dupe? If not, can you add to the Code style project?

**Comment by dpoeschl** [comment]
I don't think we're tracking it elsewhere. Let's use this one to track it.

**Comment by jnm2** [comment]
I'm going to go ahead and start using `applicable_kinds = local` so that I'm already there when you light this up.

**Comment by jnm2** [comment]
Though perhaps locals will be `csharp_`-specific rather than `dotnet_`-specific.
