### ISSUE TITLE
There is no way to get UnaryOperationKind.OperatorMethodFalse and no node to map to IUnaryOperatorExpression in IIfStatement

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#18135]
see this test.

http://source.roslyn.io/#Roslyn.Compilers.CSharp.Semantic.UnitTests/Diagnostics/OperationAnalyzerTests.cs,1854

same for vb

**Comment by jinujoseph** [comment]
**Design Team Descision** 

Shortcircuiting && and || operators are special and need a way to expose some more information about if a ‘user defined true/false operator’ was called.  We will either expose that information on IBinaryExpression, or we will introduce a new IShortcircuitingLogicalExpression that has that info.

**Comment by tmat** [comment]
New API - moving to 15.later

**Comment by heejaechang** [comment]
it is all gone now.
