### ISSUE TITLE
Completion not working with missing leading underscore (in some cases)

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#18131]
**Version Used**: VS2017

I can't come up with a standalone repro, but if you open Roslyn.sln and go to Editor_OutOfProc and pick any method and type `inp`, the `_inProc` field is not in the list.

**Comment by sharwell** [comment]
I can reproduce this with the following:

```csharp
class Program2
{
    static int _myProgram;

    static void Main2(string[] args)
    {
        myp|
    }
}
```

**Comment by sharwell** [comment]
Assigning @CyrusNajmabadi since this is likely related to the ongoing work in #18138.

**Comment by CyrusNajmabadi** [comment]
I haven't looked closely enough.  But i'm thinking that _ should not be treated as a word character and should be a word separate from the perspective of the pattern matcher.

**Comment by CyrusNajmabadi** [comment]
Tagging @grabalon as well.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/18540
