### ISSUE TITLE
Suggestion for C# exception throw syntactical sugar

### ISSUE THREAD

**Issue by mschwa** [dotnet/roslyn#18132]
This thought just struck me. Not entirely sure where to suggest it so I'm doing it here. If this is the wrong place I'm totally sorry, just let me know and I will never do it again ;-) 

Anyway. It would be super nice not to have to type "new" every time a throw an exception. Is there a case where you are not creating an object reference for an exception? 

**Version Used**: 

C# <= 7

**Steps to Reproduce**:

1.  throw an exception

`throw new InvalidOperationException("Email must be present.");`

**Suggested Behavior**:

`throw InvalidOperationException("Email must be present.");`

**Comment by JasonBock** [comment]
Not grooving on this idea. Using `new` is standard for any object creation. If this is added for exceptions, then why not do that everywhere?
```
var person = Person();
```
How would you be able to tell if this is calling a constructor or a method?
