### ISSUE TITLE
Visual Studio 2017 "Stand-Alone Code Analysis Tool" missing Microsoft.Build, Version=14.0.0.

### ISSUE THREAD

**Issue by aodendaal** [dotnet/roslyn#18140]
**Version Used**: 

**Steps to Reproduce**:

1. Install Visual Studio Enterprise 2017 and include Visual Studio extension development workload with optional VC++ 2017 v141 toolset (x86,x64)
2. Run VS and go to Tools -> Extensions and Updates
3. Find .NET Compiler Platform SDK and click Download
4. Restart VS
5. Create a new Stand-Alone Code Analysis Tool project found under Templates -> Visual C# -> Extensibility (.NET Framework 4.6 or greater)
6. In the Main function write
```var workspace = Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.Create();```
7. Run Debug

**Expected Behavior**:
Code executes without exceptions

**Actual Behavior**:
System.Reflection.ReflectionTypeLoadException raised with multiple of the same LoaderExceptions:
```Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.```
```Could not load file or assembly 'Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.```

I tried adding a reference to ```Microsoft.Build``` and ```Microsoft.Build.Tasks.Core``` but I only have versions 4.0.0.0 and 15.1.0.0

How do I get the correct references because either the template is using old references or I'm missing the older versions

**Comment by jmarolf** [comment]
@aodendaal a workaround here would be:
1. Add an App.config file to your console project with the following contents
```XML
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build"
                          publicKeyToken="b03f5f7f11d50a3a"
                          culture="neutral" />
        <bindingRedirect oldVersion="14.0.0.0"
                         newVersion="15.1.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Framework"
                          publicKeyToken="b03f5f7f11d50a3a"
                          culture="neutral" />
        <bindingRedirect oldVersion="14.0.0.0"
                         newVersion="15.1.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Tasks.Core"
                          publicKeyToken="b03f5f7f11d50a3a"
                          culture="neutral" />
        <bindingRedirect oldVersion="14.0.0.0"
                         newVersion="15.1.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
2. Add 15.1 references to `Microsoft.Build`, `Microsoft.Build.Framework`, and `Microsoft.Build.Tasks.Core`

**Comment by jmarolf** [comment]
@asecchia I think the fix here is to have the templates add the redirects and msbuild references automatically for you.  Thanks for reporting this bug.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #69](https://github.com/dotnet/roslyn-sdk/issues/69) via [**ZenHub**](https://www.zenhub.com/)
