### ISSUE TITLE
Refactoring: Sync namespace and folder structure

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#18147]
Many customers have stated they like "sync type and file name" but another refactoring they need is "sync namespace and folder" (aka "adjust namespaces"). 

This should work to rename all namespaces throughout the entire folder structure for the solution.

**Comment by monoman** [comment]
👍 In my experience, this is a very common need, when iterating the start (alpha stage) of a library project, or when the APIs are nominally public but are used only internally like inside a console/web app. 

**It would be nice to have some gate-keeping dialog warning the user that the results of this refactoring can possibly mean breaking changes on public APIs, and giving he/she the option to bail out.**

🥇 **Even better if the refactoring assesses that no public classes with public members will be changed and then skips the warning but possibly not the confirmation dialog.**

**Comment by kuhlenh** [comment]
Oops, looks like I made a dupe! https://github.com/dotnet/roslyn/issues/14341.
