### ISSUE TITLE
Improve the IDE0019 message / "Variable declaration can be inlined" shown twice in IDE with different semantics

### ISSUE THREAD

**Issue by NSentinel** [dotnet/roslyn#18148]
**Version Used**: 
Visual Studio 2017 RTM / 15.0.0 + 26228.9

**Code to Reproduce**:

```csharp
var ex = e.ExceptionObject as Exception;
if (ex != null) 
{
}
```

**Actual Behavior**:

Invoke refactor quick actions (`Ctrl +.`) on `ex` in `var ex = e.ExceptionObject as Exception;`

Two variants are shown:

1. IDE0019:
![image](https://cloud.githubusercontent.com/assets/2722498/24303282/81be61bc-10c6-11e7-91ae-3ac8e005bb79.png)

2. Regular variable inlining:
![image](https://cloud.githubusercontent.com/assets/2722498/24303412/f16795ec-10c6-11e7-8c3a-c465762ffc4d.png)

I think the IDE0019 message can be improved to give more understanding about action would be taken without pointing to each menu option.

**Comment by sharwell** [comment]
💭 What if instead of saying "Inline temporary variable", the first option read "Use pattern matching"?

**Comment by NSentinel** [comment]
Pretty good for me: the refactoring action and the message will match each other

**Comment by Pilchie** [comment]
@CyrusNajmabadi @kuhlenh what do you think about changing the text of the diagnostic form here?

**Comment by Pilchie** [comment]
Giving to @CyrusNajmabadi for his opinion, but totally okay with @sharwell fixing too :)

**Comment by CyrusNajmabadi** [comment]
THe feature, internally, is called "UsePatternMatching".  Looks like an incorrect loc string was used.
