### ISSUE TITLE
IArrayCreationExpression.Dimensions for explicit versus implicit case

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#18155]
An IArrayCreationExpression might have explicitly specified or implicitly generated dimensions. Currently, we expose all the Dimension IOperations, regardless of whether they are explicit in source or implicitly computed by the compiler: http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/IExpression.cs,1227

Open questions:
1. Should the `Dimensions` exposed on `IArrayCreationExpression` filter out implicitly computed dimension?
  1. If yes, should we have a separate helper (extension) method on IArrayCreation to get implicitly computed dimensions and rename the current `Dimensions` property to something like `ExplicitDimensions`?
  2. If no, what is the expectation from an analyzer analyzing and reporting diagnostics on numerical literals? We can't expect all such analyzers to check for generated IOperations...

**Comment by jinujoseph** [comment]
**Design Team Decision**

It was decided that when we have compiler generated or Implicitly computed by compiler , we will set IsImplicit flag to true. It was also decided not to expose the option for Analyzer authors to specify if they want explicit or not. We can add that in future based on ask and scenarios.

**Comment by jinujoseph** [comment]
@bkoelman i have updated the comments to clarify.

**Comment by bkoelman** [comment]
Thanks

**Comment by tmat** [comment]
Resolved by 21363
