### ISSUE TITLE
Warning CS8123 is misleading if there is no element name in the target type

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#18169]
**Version Used**:  2.0.0.61501

**Steps to Reproduce**:

Compile this code:

```csharp
(int, int) t = (pointless: 10, 20);
```

**Expected Behavior**:

A warning along the lines of:

> The tuple element name 'pointless' is ignored because no name is specified by the corresponding element in the target type '(int, int)'

**Actual Behavior**:

> The tuple element name 'pointless' is ignored because a different name is specified by the target type '(int, int)'

The actual error message is misleading because a different name *isn't* specified - instead, *no* name is specified.

It's fine for this to be a warning, but it would be nice if the message were clearer. Unfortunately my *guess* is that in order to have a different message between this and the situation where there really *is* a different name, they have to be different warning numbers - and that may count as a breaking change. (I'm not sure what the C# team policy is there.) In that case, we might need a single warning message that covers both situations. For example:

> The tuple element name 'pointless' is ignored because the corresponding element in the target type '(int, int)' does not specify the same name.

That's definitely not as nice as having two different warnings though, IMO.

**Comment by jcouv** [comment]
I didn't want to introduce two different diagnostics, but updated message. Hopefully that should minimize the confusion.
`warning CS8123: The tuple element name 'b' is ignored because a different name or no name is specified by the target type '(int a, int)'.`

**Comment by jcouv** [comment]
Closed by #18454
