### ISSUE TITLE
The term 'Get-FileHash' is not recognized

### ISSUE THREAD

**Issue by abubakarm** [dotnet/roslyn#18170]
**Version Used**: 
master branch
**Steps to Reproduce**:

1. download latest source, on Windows 7 64bits (with latest powershell for windows 7), 
2. open VS 2017 command prompt
3. run restore.cmd

**Expected Behavior**:
Everything should download fine and Build.cmd should be ready to run
**Actual Behavior**:
it throws an exception:
System.Management.Automation.CommandNotFoundException: The term 'Get-FileHash' is not recognized as the name of
 a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was include
d, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exce
ption exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

Error executing command:  & (Join-Path $PSScriptRoot "download-nuget.ps1")

**Comment by jasonmalinowski** [comment]
@jaredpar Any guess if this is another instance of "Windows 7 powershell is different"?

**Comment by abubakarm** [comment]
it may be, i think Get-FileHash is not in the powershell 3 which I have on my system. Trying to install a new one ... or I am mistaken.

**Comment by abubakarm** [comment]
after installing Windows Management Framework 4.0 on windows 7 64 bits and restarting the machine, this error is fixed.

**Comment by hickford** [comment]
Same problem with `restore.cmd` 

> System.Management.Automation.CommandNotFoundException: The term 'Get-FileHash' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

I'm using Windows 7.

**Comment by abubakarm** [comment]
@hickford did you install Windows Management Framework 4.0, google for it, install and restart machine and try again, this should work.
