### ISSUE TITLE
Test generic type inference with "ref readonly" parameters

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#18172]
Once we are able to make calls with "ref readonly" parameters, generic type inference involving "ref readonly" will be testable.

The feature may not require any additional changes and work similarly to regular byval parameters, but will need to be tested.
Make sure to test:

ref readonly/out/ref differences
indexers
operators
tuples
lambdas
betterness

**Comment by OmarTawfik** [comment]
Merged from #22283
