### ISSUE TITLE
String intepolation format using constant

### ISSUE THREAD

**Issue by zaiboot** [dotnet/roslyn#18177]
I am creating a string with some dates/ integers formatted in a specific way. I know this could be worked around with string builder and some other ways. Just doing the test on interpolated strings and found this is not working as I expected. Not sure if my assumptions are correct. Look at this dotnetfiddle: https://dotnetfiddle.net/33nBt2 for more information.

**Version Used**: 
netcore1.1

**Steps to Reproduce**:

1. Created a datetime object .
2. Create a string constant with the desired format. E.g.: "yy-MM hh";
2. Using string interpolation use that predefined constant for the format of such datetime.
3. String interpolation being printed in a console.writeline line.

**Expected Behavior**:
'Hello World 17-03-26 08:07'
**Actual Behavior**:
Hello World DATE_OR3AT
code for demo:
```csharp
using System;
					
public class Program
{
	public static void Main()
	{
		var fecha = DateTime.UtcNow;
		const string DATE_FORMAT = "yy-MM-dd hh:mm";
		Console.WriteLine($"Hello World {fecha:DATE_FORMAT}");
	}
}
```
Thank you everyone for your time.

**Comment by AdamSpeight2008** [comment]
@zaiboot You'd get the same behaviour if you did the following 
The warning message 'The variable 'DATE_FORMAT` is assigned but never used.` would be a indication that the Interpolated String, isn't go behave as you think.
```c#
using System;
					
public class Program
{
	public static void Main()
	{
		var fecha = DateTime.UtcNow;
		const string DATE_FORMAT = "yy-MM-dd hh:mm";
   		Console.WriteLine(String.Format("Hello World {0:DATE_FORMAT}",fecha));
	}
}
```

**Comment by zaiboot** [comment]
Yup. I noticed that.  So any links or documentation on how it works? The inner of interpolated strings on .netcore1.1? I've been digging in the code but no idea how is that parsed or set. 
Thanks

**Comment by AdamSpeight2008** [comment]
It is the same as `String.Format`.

**Comment by gafter** [comment]
The format string is a sequence of literal characters. It isn't an expression.
