### ISSUE TITLE
Proposal: improve `is` operator

### ISSUE THREAD

**Issue by XaveScor** [dotnet/roslyn#18173]
```c#
var b = a as Clazz;
if (b != null) {
  doSmth(b);
}
```
is most frequent use pattern of `as` operator. This usage causes some problems. For example:
```c#
var b = a as Clazz;
if (a != null) {
  doSmth(b);
}
```
The PVS-Studio static analyzer finds this problem in its every article.
We may solve this one:
```c#
class A {}
class B: A {
public void doSmth() {}
}

A a = new B();
if (a is B) {
  a.doSmth();//We can use this method because we know `a` is instance of B class. 
}
```

**Comment by Muchiachio** [comment]
It's already possible in a form of
```C#
A a = new B();
if (a is B b) {
  b.doSmth();
}
```

**Comment by gafter** [comment]
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

As has been pointed out by @Muchiachio, C# 7 already supports something so remarkably close to what you suggest that we would not take your request. Also, it would be a breaking change in the type rules of the language, changing the behavior of existing programs.
