### ISSUE TITLE
Code Style option to preserve, insert or remove empty lines

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#18186]

**Comment by Pilchie** [comment]
Agree that we want this, but I think it needs to be more nuanced - people often have different preferences for the spacing between different constructs.

**Comment by alrz** [comment]
this could have separate options for different places just like "new line".

**Comment by dpoeschl** [comment]
Also consider the case of https://github.com/dotnet/roslyn/issues/23280 when designing this.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi @alrz Did https://github.com/dotnet/roslyn/pull/50358 addresses this?

**Comment by OsvaldasRubavicius** [comment]
Any progress/news on this issue?

**Comment by Rasmus715** [comment]
Rooting for this one!

**Comment by CyrusNajmabadi** [comment]
THere's an option for this now: 

![image](https://github.com/dotnet/roslyn/assets/4564579/409bb26b-eb3f-45e3-8adb-f2e7bc6209c0)
