### ISSUE TITLE
C# 7.0 Multiple values for a case bug

### ISSUE THREAD

**Issue by brunovisck** [dotnet/roslyn#18188]
**Version Used**:  2.0.0.61501

**Steps to Reproduce**:

1. Create a switch that uses Byte or Ushort  

```
byte testByte = 130;

switch (testByte)
{
    case 127: // 0111 1111
    case 128: // 1000 0000
        Console.WriteLine(@"BUGGGGGGGGGGGGGGGGG");
        break;
    default:
        Console.WriteLine(@"OK :D");
        break;
}

ushort testUshort = 32769;

switch (testUshort)
{
    case 32767: // 0111 1111 1111 1111
    case 32768: // 1000 0000 0000 0000
        Console.WriteLine(@"BUGGGGGGGGGGGGGGGGG");
        break;
    default:
        Console.WriteLine(@"OK :D");
        break;
}
```

**Expected Behavior**:

The expected behavior was the switch goes to default statement

**Actual Behavior**:

The switch goes to the case statement.

The compiler converts the 'switch' to 'if', but the conversion occurs in the wrong way.

**Comment by jcouv** [comment]
FYI @gafter
