### ISSUE TITLE
[C# Feature Request]  Abstract Classes inherit from interfaces passing implementation responsility

### ISSUE THREAD

**Issue by GrantHoffman** [dotnet/roslyn#18192]
Abstract classes should allow the responsibility of implementations to be passed to child class. Here is an example of how it can be useful

        public interface IFoo
        {
             int Id { get; set; }
        }

        public abstract class FooAdapter : IFoo
        {
              public Bar ToDTO()
              {
                   return Mapper.Map<Bar, IFoo>(this)
              }     
        }

        public class FooImplementationAdapter : FooAdapter
        {
             public int Id {get; set; }
        }

**Comment by benknoble** [comment]
C# is now tracking at [dotnet/csharplang](https://github.com/dotnet/csharplang)

**Comment by GrantHoffman** [comment]
Noted, Issue moved https://github.com/dotnet/csharplang/issues/360 this can be closed
