### ISSUE TITLE
IOperation API for attributes

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#18198]
We have no API for representing attributes, and hence get no IOperations for any syntax node within an attribute.

**Comment by mavasani** [comment]
Source:

```
class Attr : System.Attribute { public Attr(int i) { } }

[Attr(0)]
class C
{
    public void F()
    {
        var a = new string[1];
    }
}
```

IOperation:
```
IOperation tree for "Attr(0)"

IOperation:  (OperationKind.None)
```

**Comment by mavasani** [comment]
Tag @dotnet/analyzer-ioperation

**Comment by genlu** [comment]
Should it be treated as an IInvocationExpression?

**Comment by CyrusNajmabadi** [comment]
The attribute likely doesn't need IOperations.  But the code that is provided as arguments to the attribute likely does.

**Comment by genlu** [comment]
@CyrusNajmabadi Considering that runtime retrieval of attribute instance involves code execution, which is treated as same as object creation expression, I'd argue otherwise (although I don't think it warrants a separate interface).

**Comment by AlekseyTs** [comment]
An attribute application is different from invocation. For example, it can include initializers for fields/properties.

**Comment by genlu** [comment]
My bad, I meant to say `IObjectCreationExpression`.

**Comment by jinujoseph** [comment]
**Design Team Decision**.

The approach of IObjectCreation sounds reasonable with the addition of a kind to differentiate if this is kind Attribute. we need to see if there is a way to expose IAttributeCreation for better clarity.

**Comment by jinujoseph** [comment]
group all attributes one

**Comment by Youssef1313** [comment]
NOTE if this is worked on later:

```
public class MyAttribute : Attribute
{
    public MyAttribute([CallerLineNumber] int line = 0)
    {
    }
}
```

Applying `[My]` without arguments should have "IsImplicit = true" for the IArgumentOperation.

**Comment by RikkiGibson** [comment]
Closing in favor of #53618
