### ISSUE TITLE
Proposal:  Allow covariance on return types

### ISSUE THREAD

**Issue by HaloFour** [dotnet/roslyn#182]
# Problem

Currently when overriding a virtual method the overriding method is required to match the signature including the return value.  This prevents the overriding method from returning a more specific type which could be useful to the caller which would then not have to cast.  This is a limitation imposed by the C# compiler and not a limitation of the CLR.

The closest solution to this today is to shadow the method in the derived class and have that method return the more specific type.  However, the derived class cannot both shadow the method and override the method.

# Proposal

Remove the limitation on the compiler and allow the overriding of methods with a covariant return type.

```cs
public class Foo {
    public virtual Foo MyMethod() {
        return this;
    }
}

public class Bar : Foo {
    // override the method, the return type can be Foo or any type deriving from Foo
    public override Bar MyMethod() {
        // do stuff here
        return (Bar)base.MyMethod(); // calling the base method still returns Foo
    }
}

...

Bar bar1 = new Bar();
Foo foo1 = bar1;
Bar bar2 = bar1.MyMethod(); // since Bar::MyMethod returns Bar no cast is required
Foo foo2 = foo1.MyMethod(); // virtually dispatches to Bar::MyMethod and returns a Bar but the apparent return type is still Foo and must be cast
```

**Comment by HaloFour** [comment]
To note it appears that covariant return types are supported by the CLR when it comes to interface implementations, but given explicit implementation this can be easily worked around:

```cs
public interface IFoo {
    IFoo MyMethod();
}

public class Bar : IFoo {
    IFoo IFoo.MyMethod() {
        return this.MyMethod();
    }

    public Bar MyMethod() {
        // do stuff here
        return this;
    }
}
```

**Comment by mikedn** [comment]
"This is a limitation imposed by the C# compiler and not a limitation of the CLR."

Actually it is a limitation of the CLR, the method signature must match for a method to override another. And the method signature includes the return type

**Comment by HaloFour** [comment]
IL supports covariant return types and PEVerify has no issue with it.

**Comment by mikedn** [comment]
Have you actually checked that it calls the method that is supposed to call? :smile:

**Comment by HaloFour** [comment]
You're right, it appeared that it was working as MSIL does allow for overloading based on the return type.  The derived method wasn't actually overriding and this was apparent when attempting to call the method on the base class.

Given that such a feature would involve changes to the runtime and spec I'll withdraw it.  It's a nice to have (I've appreciated it in Java) but it's not a big deal.

**Comment by gafter** [comment]
We are tracking this proposal as #357. It does not require CLR/IL support. We would do what Java does (emit bridge methods).
