### ISSUE TITLE
Create build task to discover .editorconfig files

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#18208]
In order for MSBuild determinism and dependency validation to work, we need to find the .editorconfig files _before_ we invoke the CoreCompile target (since is doing up-to-date checking) and also before the Csc/Vbc task runs, because we want that to be reasonably deterministic. Therefore, we need a build task to take the compiler inputs and walk around the file system locating the .editorconfig files that will apply so they can be passed.

### Open questions

- Which binary does this build task live in? The task itself has no dependency on Roslyn at all, so it could live anywhere. Should it live in MSBuild core build tasks or in our CodeAnalysis build tasks? I'm leaning towards the latter, as it has some affinity with our scenarios and will likely rev with it. @jaredpar, thoughts? This reminds me of the new task that you're creating for the reference assembly copying. It's another ancillary task that supports Csc/Vbc but might be consumed in other places.
- Where does the target that invokes the task live in? @jaredpar and @agocke do you have guidance/rules for what should and shouldn't go within our .targets that we bundle in the toolset packages vs. the core projects?
- Is there any code this can share from the core .editorconfig support? @olegtk is there any source that might be usable here from your implementation? This is just file discovery, so we don't need the full logic.

### Implementation notes

The order of the output must be stable to support determinism builds. The actual sort criteria won't matter, but must be stable.

**Comment by jasonmalinowski** [comment]
#17121 is also filed to track some other questions about whether the compiler is currently deterministic in other situations like this.

**Comment by Pilchie** [comment]
Sadly, this editorconfig work isn't going to fit for 15.3, but we're going to continue targeting the next foundation update.

**Comment by dpoeschl** [comment]
Moving .editorconfig work to 15.later

**Comment by agocke** [comment]
Done in https://github.com/dotnet/roslyn/pull/27398
