### ISSUE TITLE
Integrate 'private protected' implementation into a product version

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#18201]
Tasks:
- [ ] Link the feature to a supported language level
- [ ] Identify (and implement) required testing to be done

Implementation work is occurring in https://github.com/dotnet/roslyn/tree/features/privateProtected

**Comment by jcouv** [comment]
Seems like this can be closed, no?

**Comment by gafter** [comment]
Integrated into C# 7.2 and VB 15.5.
