### ISSUE TITLE
Create API for consuming .editorconfig options at the analyzer layer

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#18217]
Once we have the .editorconfig files parsed, we need to get the values to analyzers. We'll hash this out in a face-to-face meeting, but possible proposals are:

### Proposal 1

The pattern we have in the IDE is any given document can get an OptionSet type which represents an immutable set of options. From there you can call .GetOption() and pass it an option key which is just a type you define, and you get the value back. In this proposal, we'd just move these APIs down to the compiler layer, and then have some API to get the OptionSet for a syntax tree. We'd probably add this on the analyzer context objects given (especially for tree analyzers since we could provide the OptionSet immediately).

This API is "lazy" so until an analyzer were to actually ask for .editorconfig information it won't actually have to do any evaluation for that given file. 

### Proposal 2

Something new. This is fuzzier, and I'm not sure if there's any clear benefit over the API we already have above. We could imagine analyzers having to declare their options they consume up front and that's read via some specialty API. It's perhaps simpler, but won't bring any new expressivity that we don't already have.

**Comment by jasonmalinowski** [comment]
Proposal 1 is the current plan of record.

**Comment by Pilchie** [comment]
Sadly, this editorconfig work isn't going to fit for 15.3, but we're going to continue targeting the next foundation update.

**Comment by dpoeschl** [comment]
Moving .editorconfig work to 15.later.

**Comment by jasonmalinowski** [comment]
Not sure why this was still assigned to me; moving to @agocke (who might just go and close it.)

**Comment by jasonmalinowski** [comment]
We ultimately added a new API at the compiler layer, and then updated OptionSet to consume it.
