### ISSUE TITLE
Flow the list of .editorconfig files through the compiler front end

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#18210]
Once we have [the list of .editorconfig files](https://github.com/dotnet/roslyn/issues/18208) determined, we need to get them through the compiler APIs. The expectation is these are expressed in the same form roughly as source files:

1. They go into another input into the Csc/Vbc tasks.
1. We convert those to /editorconfig switches, which are a list of file names after that. Same as any other switched input.
1. We parse those through and still represent as files in the parsed command line options, again same as everything else.

**Comment by Pilchie** [comment]
Sadly, this editorconfig work isn't going to fit for 15.3, but we're going to continue targeting the next foundation update.

**Comment by dpoeschl** [comment]
Moving .editorconfig work to 15.later.

**Comment by agocke** [comment]
Done in https://github.com/dotnet/roslyn/issues/27232

**Comment by smitpatel** [comment]
@agocke - Which milestone (or VS version) did this go in? Milestone here is 16.0 but in PR it is 15.8

**Comment by agocke** [comment]
16.0 is right. I've removed the milestone from the PR.
