### ISSUE TITLE
Implement .editorconfig parsing in the compiler

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#18219]

**Comment by Pilchie** [comment]
Sadly, this editorconfig work isn't going to fit for 15.3, but we're going to continue targeting the next foundation update.

**Comment by dpoeschl** [comment]
Moving .editorconfig work to 15.later.

**Comment by guidobouman** [comment]
#18210 is on milestone 15.8, should this not be there as well?

**Comment by agocke** [comment]
Fixed in #26105

**Comment by agocke** [comment]
Thanks, meant #26253
