### ISSUE TITLE
Modify WouldBeAssignableIfUsedAsMethodReceiver to know about lvalue ternary

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#18220]
When the fix for https://github.com/dotnet/roslyn/pull/18166 is merged into `readonly-ref` branch, make sure it is adjusted to also consider lvalue ternary.

**Comment by jcouv** [comment]
@VSadov If this wasn't done already, do you want to take care of this in your PR merging to master, or after you merge to master?
