### ISSUE TITLE
Suggestion: When calling a non-existent method, don't autocomplete on colon

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#18229]
I'm calling a non-existent method
```C#
MethodThatWillBeGenerated($$)
```

I type `firstParameter:` at the $$, and completion commits whatever happens to be selected and I get some type/namespace/method name inserted when I'm trying to use named arguments.

**Comment by dpoeschl** [comment]
The only case I can come up with where I wouldn't want this is when I used a named argument to pass a non-obvious literal value (`true` for example), but *after* that I want to name my named arg the same thing as a local variable or something. Maybe that's enough to shoot this down.

**Comment by Pilchie** [comment]
I think this suggestion is reasonable - note that it's not to prevent completion from working there, it's just to adjust the set of commit characters to remove `:` in this case.

**Comment by reaction1989** [comment]
@dpoeschl i tried to reproduce it with the latest vs2017 release and also with the current master. I could not reproduce it. I could write 

`MethodThatWillBeGenerated(nameParameter:)` without inserting an "randomn" Type

**Comment by dpoeschl** [comment]
@reaction1989 is right. My named argument must have been a substring of an existing identifier.

An example:
```C#
using System.Threading;

public class Class
{
    void Method(CancellationToken cancellationToken)
    {
        Test($$)
    }
}
```
Type `token:` at the $$, and it completes to "cancellationToken:"

Given this, I care very little about this being changed. @Pilchie should we just close this?

**Comment by Pilchie** [comment]
Yep.
