### ISSUE TITLE
dynamic interface wrapping

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#18232]
Alternative to #15974 to grant intellisense to dynamic

Whenever we convert dynamic to interface it should be like this

```C#
public interface A
{
    public string _id { get; set; }
    public string Name { get; set; }
}

dynamic d = ParseJSON(text);
var a = (A)d;
```

Compiler should transpile it tobe

```C#
public interface A
{
    public string _id { get; set; }
    public string Name { get; set; }
}

public class __dynamicA : A
{
    public dynamic __d;
    public string _id { get => __d._id; set => __d._id = value }
    public string Name { get => __d.Name; set => __d.Name = value }
}

dynamic d = ParseJSON(text);
var a = (d as A) ?? new __dynamicA() { __d = d };
```

Also if we drop `CS1612` on setting struct property as in #17207 then `__dynamicXXX` should be struct

**Comment by Thaina** [comment]
@Pilchie Should this be in roslyn or csharplang ?

**Comment by Pilchie** [comment]
If it involves changing the language specification (which this does, because it changes what happens when dynamic is converted to an interface type), it should be on csharplang.

**Comment by Pilchie** [comment]
Tagging @gafter

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
