### ISSUE TITLE
The 'C# 7' language version is missing from csc.exe /? printhelp

### ISSUE THREAD

**Issue by dzeitlin** [dotnet/roslyn#18237]
The 'C# 7' language version is missing from csc.exe /? printhelp.
See: http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp/LanguageVersion.cs,41ddf4073ec089aa

**Version Used**: 
`csc.exe 2.0.0.61501`

**Steps to Reproduce**:
`csc.exe /?`

**Expected Behavior**:
`/langversion:<string>         Specify language version mode: ISO-1, ISO-2, 3, 5, 6, 7, Default, or Latest`

**Actual Behavior**:
`/langversion:<string>         Specify language version mode: ISO-1, ISO-2, 3, 5, 6, Default, or Latest`

**Comment by jcouv** [comment]
Yes. I realized this problem as well. The [fix ](https://github.com/dotnet/roslyn/pull/17894/files) will ship in dev15.3 along with C# 7.1. I've also added a checklist so that we don't forget for next time.

**Comment by jcouv** [comment]
Thanks @dzeitlin for reporting the problem.
