### ISSUE TITLE
Resolve usings won't resolve for internalsvisible interfaces

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#18233]
In the project system, we use the [IWorkspaceProjectContext interface](http://index/?leftProject=Microsoft.VisualStudio.LanguageServices&leftSymbol=o5dvtamcvniy&file=Implementation%5CProjectSystem%5CCPS%5CIWorkspaceProjectContext.cs&line=12) from Microsoft.VisualStudio.LangaugeServices.dll, in which we have InternalsVisibleTo access.

Resolve usings and the spell checker both don't offer code actions to resolve this type when I use it.

1. Clone github.com/dotnet/roslyn-project-system
2. From command prompt, run build.cmd
3. Open src\ProjectSystem.sln
4. Open SourceItemHandler.cs
5. Delete the `using Microsoft.VisualStudio.LanguageServices.ProjectSystem;`
6. Navigate to IWorkspaceProjectContext usage, and try and get a code action to add a using.

Expected: To get prompted to add a using
Actual: Nothing

![image](https://cloud.githubusercontent.com/assets/1103906/24386777/33bfa576-13bd-11e7-90f9-c3a8e01d7fb6.png)

**Comment by davkean** [comment]
I should clarify, this is not all InternalsVisibleTo types - just this particular one. Maybe something to do with the namespace clash (the namespaces are reversed, `ProjectSystem.LanguageServices` and `LanguageServices.ProjectSystem`) and internalsvisibleto.

**Comment by Pilchie** [comment]
This might be *just* about the namespaces.  I don't think IVT matters at all here.

**Comment by davkean** [comment]
That what I suspected but I couldn't repro it outside of IVT.

**Comment by CyrusNajmabadi** [comment]
Ugh.  Can't open that project with my current VS :(

![image](https://cloud.githubusercontent.com/assets/4564579/24438980/1f9f6bc4-1400-11e7-8984-e6edc9f88a9f.png)

**Comment by davkean** [comment]
How do you not have desktop workload installed?

**Comment by CyrusNajmabadi** [comment]
I installed only the minimum to develop roslyn :)

**Comment by davkean** [comment]
TBH, I don't know you can open Roslyn without the .NET desktop worldload...

**Comment by CyrusNajmabadi** [comment]
Seems to work fine :)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
