### ISSUE TITLE
Strange implementation of Optional<T>

### ISSUE THREAD

**Issue by SergeyTeplyakov** [dotnet/roslyn#1823]
Roslyn code base contains public struct called [Optional<T>](https://github.com/dotnet/roslyn/blob/8771786e5a80e9d27ffb40702f5cca558ca6fabb/src/Compilers/Core/Portable/Optional.cs). This type is similar to [Optional type](http://en.wikipedia.org/wiki/Option_type) but the implementation is looks weird to me.

From my perspective, any optional type should hold following invariant: if the `HasValue` property returns true `Value` property should provide a valid value. It is very debatable what the "valid value" is, but for optional reference types it means that the `Value` is not null.

Current `Optional<T>` does not have a class constracts, so it is possible to use it with value types. But in this case what should be the logic for this case: `Optional<int?>`? or what the difference from the API consumer or API provider between `Optional<int>` and `Nullable<int>`? Why to introduce yet another type that competes with an existing and widely used type?

Another question is related to using `Optional<T>` with reference types. Because of implicit conversion from `T` to `Optional<T>` following code runs successfully:

```c#
public Optional<string> Foo(object o)
{
  if (o == null)
    return null; // resulting object would have HasValue == true, but Value == null!
 return o as string; // the same is true here!
}
```

I'm working on few analyzers in in one of them I started using this type and found out that I hardly can use this type properly.

So the questions are: 

1. Why this struct does not have a class constraint with appropriate implementation of `HasValue` property.
2. And if this implementation is correct what the expected semantic difference between `Optional.HasValue == false` and `Optional.HasValue == true && Optional.Value == null`.

*UPDATE*
It seems that original semantic of this struct was to model optional arguments in the same way that @vladima mentioned in his post [Copy-And-Update in C#](http://v2matveev.blogspot.com/2010/05/copy-and-update-in-c.html) to model an optional arguments in builder pattern. See [Scripting.cs](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.Scripting/Script.cs,202). 

The original intend was not to model Maybe type that is so popular in functional language. But unfortunately, the concept is too similar to Maybe monad that even Roslyn team members started using this struct in a wrong way. Now this struct is already in public (and widely used) class like [SemanticModel](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/Compilation/SemanticModel.cs,704) and there it was used like a maybe monad there.

Thanks,
Sergey

**Comment by SolalPirelli** [comment]
Regardless of which contract this thing should satisfy, `HasValue` is always true, there's clearly something odd here. GitHub's search says the constructor is never called outside of the class itself, so maybe it's just unused code?

**Comment by SergeyTeplyakov** [comment]
@SolalPirelli This is a struct, so default constructor was used indirectly via calling `default(Optional<object>)`. The easiest way to find all references is to use [source.roslyn.codeplex.com](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/Optional.cs,86bbd87a0ffc79bf,references).

**Comment by jasonmalinowski** [comment]
`Optional.HasValue == false` and `Optional.HasValue == true && Optional.Value == null` do have two distinct meanings. One example is the Optional type being used in the function GetConstantValue:

- `Optional.HasValue == false` means "a constant value could not be determined for this expression"
- `Optional.HasValue == true && Optional.Value == null` means "a constant value was determined for this expression, and that value was null."

The other example is when we use it for methods like .With(...) where we're returning a new instance of an immutable type with some values changed. In those cases, we need to distinguish between "I do not want a change to this field" (`Optional.HasValue == false`) and "I want to change this field to null" (`Optional.HasValue == true && Optional.Value == null`).

This type is not a Maybe monad. Any resemblance to real Maybe monads, living or dead, is purely coincidental.

**Comment by SergeyTeplyakov** [comment]
Thanks, Jason.

>This type is not a Maybe monad. Any resemblance to real Maybe monads, living or dead, is purely coincidental.

This should be clearly stated in the documentation for this type. It is too easy to reinterpret the meaning of this type in a wrong way.

**Comment by SergeyTeplyakov** [comment]
Closing this issue as by design.

**Comment by jasonmalinowski** [comment]
Actually I take back what I said about "purely coincidental" -- the doc comment is actually terribly misleading since it mentions a specific constraint to "value type". If you want to write a doc comment and send the pull request feel free to do so, otherwise we can try writing something better. (I'm often a fan of the person who was confused fixing the comment, because if we write it we might make something else equally confusing.)
