### ISSUE TITLE
Proposal: Explicitly typed "var" declarations in C#

### ISSUE THREAD

**Issue by jonathanmarston** [dotnet/roslyn#18247]
## Problem
You can currently define variables in 3 ways using explicit types or an implicit type using the ```var``` keyword:
```
// Explicitly typed
Dictionary<string, string> variable;

// Explicitly typed with initializer
Dictionary<string, string> variable = "hello";

// Implicitly typed with initializer
var variable = new Dictionary<string, string>();
```

This is fine when either all variable declarations are explicit, or when all of them are implicit. However, because there is no way to specify a type using the ```var``` keyword, the type and the variable are flip-flopped when writing code where some variables are initialized, and others aren't initialized, or are initialized to ```null```.

### Example:
```
var singleString = "hello";
Dictionary<string, string> dictionaryOfStrings;
var listofStrings = new List<string> { "hi", "howdy" };
Func<string, IEnumerable<char>> getCharacters = null;
```

This creates an inconsistent flow in the code, requiring the reader to switch sides of the declaration when looking for the type.

There is, in fact, a workaround of sorts, where you cast ```null``` to the desired type:
```
// Implicitly typed with null initializer
var variable = (Dictionary<string, string>)null;
```

However, this changes the meaning of the code by disabling the compiler check for reading a reference variable before assigning to it.

## Proposed Solution
It would be helpful to increase consistency and readability of code if you could supply an explicit type when using the ```var``` keyword, without needing to initialize the variable.

With this proposal, the previous example would become:
```
var singleString = "hello";
var dictionaryOfStrings: Dictionary<string, string>;
var listofStrings = new List<string> { "hi", "howdy" };
var getCharacters: Func<string, IEnumerable<char>> = null;
```

The syntax here is borrowed from TypeScript, and makes variable declarations in C# read more closely to VB, where the ```var``` keyword can be consistently used, and the type consistently appears on the right-hand side of the declaration.

It would also be valid to specify a type and an initializer concurrently using the ```var``` keyword:
```
var enumerable: IEnumerable<string> = new List<string>();
```

## Potential Issues
The main issue I see with this proposal is that some could view it as over-complicating the language by adding another way to say the same thing, but I'd argue that the ```var``` keyword has already done that. This proposal is simply allowing developers that have embraced ```var``` to use a more consistent syntax throughout their code.

**Comment by bbarry** [comment]
Language requests should be entered in https://github.com/dotnet/csharplang

**Comment by jonathanmarston** [comment]
Thanks. Moved to dotnet/csharplang#376
