### ISSUE TITLE
Refactor & Decide on interface versus abstract type

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#18246]
Tagging @heejaechang, who would like to discuss this in the API design meeting.

**Comment by jinujoseph** [comment]
**Design Meeting Notes**

This depends on how we implement Laziness, if laziness is implemented by lamda which can be left completely pure datatype without having any strong reference to C#/VB or no strong reference to roslyn then we can take the abstract type route.
But if we do laziness needs location which needs a strong reference to language specific operation type, then other languages will need interfaces to be available to them.

We need to revisit this after we investigate lazy scenarios and their implementation.

**Comment by jinujoseph** [comment]
VB factory checked in via https://github.com/dotnet/roslyn/pull/19073
