### ISSUE TITLE
IDE0028 (Collection initialization can be simplified) - invalid code fix

### ISSUE THREAD

**Issue by kindermannhubert** [dotnet/roslyn#18242]
Hi, IDE0028 proposes invalid code fix for following code (using VS2017 15.0.26228.9):
```C#
int lastItem;
var list = new List<int>();
list.Add(lastItem = 5);
```
The fix looks like this:
![ide0028](https://cloud.githubusercontent.com/assets/11704036/24397895/e612cec6-13a7-11e7-8d8c-d58ec77e10cc.png)

which does not compile.

Diagnostic should not be displayed in these cases or fix has to be smarter.

**Comment by jmcpherson10** [comment]
What is wrong with providing the fully qualified type name? 
Lazy programmers, that's what's wrong.
You should ALWAYS know what types you are dealing with.

**Comment by CyrusNajmabadi** [comment]
@jmcpherson10 I'm not sure what you're referring to at all.
