### ISSUE TITLE
Do not suggest replacing property with separate methods

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/roslyn#18241]
**Version Used**:
Visual Studio/15.0.0-RTW+26228.4

**Steps to Reproduce**:
See Actual behavior.

**Expected Behavior**:
Introduce private field and implement getter/setter to use that field instead of introducing separate methods which break the concept (or unit) of property. At least have this refactoring with higher priority.

**Actual Behavior**:
C# is the only language which has a clear concept of Properties, instead of having only methods which are separate and independent of each other. Why do you suggest this anti-pattern instead of implementing getters/setters?

![image](https://cloud.githubusercontent.com/assets/9047283/24395155/f8332c6c-139e-11e7-89ff-be27e9079b5a.png)

**Comment by Pilchie** [comment]
This refactoring is valuable when you plan to do something like add arguments (maybe a `CancellationToken`), or you want the API to make it clear that the operation is expensive.

However, it's a good point that we are *missing* a different refactoring to convert an auto-property to "full" property. I've filed https://github.com/dotnet/roslyn/issues/18267 to track that.
