### ISSUE TITLE
Possible concurrency problem with XmlDocumentationProvider

### ISSUE THREAD

**Issue by daveaglick** [dotnet/roslyn#18244]
**Version Used**: 2.0.0 (NuGet)

**Steps to Reproduce**:

1. Load an assembly into a compilation using a `MetadataReference`, specifying an `XmlDocumentationProvider`
2. Concurrently call `ISymbol.GetDocumentationCommentXml()`

**Expected Behavior**: Correct XML from the XML file.

**Actual Behavior**: Occasional missing XML elements that are present in the XML file.

I've noticed this happening in big documentation generations where I concurrently iterate lots of symbols and repeatedly attempt to get the XML comments for them. Most of the time it works fine, but every so often one of the symbols will end up with missing comments.

It's been difficult to track down a root cause due to inconsistency, but wrapping the entire `ISymbol.GetDocumentationCommentXml()` call in a lock appears to resolve the issue leading me to suspect some kind of concurrency problem. It could be in the `GetDocumentationCommentXml()` implementation, but I suspect it's in `XmlDocumentationProvider.GetDocumentationForSymbol()`. 

Specifically, there's a check outside the lock if the dictionary cache has been initialized. If not we lock and read the XML file, but if the dictionary has been initialized we go straight to checking for the symbol. If a thread starts generating the dictionary and then another gets to the method and does the check for initialization before the first is done it may get incomplete or inconsistent information.

This *might* be related to #18191 since symptoms sound similar (cc @rynowak)

**Comment by cston** [comment]
@daveaglick, thanks for reporting this issue and for identifying the race condition in `XmlDocumentationProvider.GetDocumentationForSymbol`. 

cc @jinujoseph
