### ISSUE TITLE
IDE0028 - Collection Initializer Can Be Simplified: Invalid Code

### ISSUE THREAD

**Issue by AlexanderMorou** [dotnet/roslyn#18260]
**Version Used**: 
Visual Studio/15.0.0+26228.9

**Steps to Reproduce**:

1. Define a dictionary initializer
2. Specify some values via assignment (`dict[key] = value`)
3. Specify some values that refer to the dictionary (same value for different keys: `dict[key2] = dict[key1]`)

**Expected Behavior**:

Stop specifying the values in the collection initializer if the value expression contains a reference to an unassigned variable.

**What You Can Not Do**
You can't necessarily rewrite the expressions to cherry pick the values you want:
```
dict[key] = value;
dict[key2] = dict[key];
dict[key3] = value2;
``` 

Cannot be rewritten into:
```
dict = new DictionaryType() { [key] = value, [key3] = value2 }
dict[key2] = dict[key];
```
Precisely because you don't know if the order is important (if key and key3 are the same, the assigned value for key2 would be incorrect.)

**What You Could Do (if the language supported it)**
```
dict = new DictionaryType() { [key] = value, [key2] = [key], [key3] = value2 };
```

**Actual Behavior**:
The following code is generated with the simple three-key example above:
```
dict = new DictionaryType() { [key] = value, [key2] = dict[key], [key3] = value2 };
```

**Comment by CyrusNajmabadi** [comment]
Can you provide your original piece of code that you encountered the issue with?  Your example seems to have issues in it that don't make sense to me.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Ah, i figured out your case.  Thanks!

**Comment by AlexanderMorou** [comment]
Sorry for not noticing this.

Glad you figured it out easily enough.
