### ISSUE TITLE
Move Naming Styles analyzer from Features layer to Code Style layer

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#18279]
The naming styles analyzers should be moved from the Features layer (which only runs in the IDE) to the new Code Style layer (which runs during the compilation process). This includes `NamingStyleDiagnosticAnalyzerBase` and `AbstractNamingStyleCodeFixProvider` along with their derived types.

:memo: Depends on #18278

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to do this, we should just have a work item tracking it with a real milestone that we're doing it in.
