### ISSUE TITLE
XML documentation file is malformed when method has C# 7 tuples as parameters

### ISSUE THREAD

**Issue by VictorGavrish** [dotnet/roslyn#18274]
I was referred here from an [msbuild Github issue](https://github.com/Microsoft/msbuild/issues/1917).

**Version Used**: 
2.0.0.61325

**Steps to Reproduce**:
1. Clone [this](https://github.com/VictorGavrish/TupleExtensions) repo.
2. Open command prompt at src\TupleExtensions
3. Run `dotnet restore`
4. Run `dotnet build`

**Expected Behavior**:
A NuGet package with correct documentation is generated.

**Actual Behavior**:
The documentation doesn't work for most methods.

The documentation file (that can be found under `bin\Debug\netstandard1.0\TupleExtensions.xml`) contains entries like

```xml
<member name="M:TupleExtensions.TupleLinqExtension.ToDictionary``2(System.Collections.Generic.IEnumerable{System.})">
...
</member>
```

The important part is `System.Collections.Generic.IEnumerable{System.}`, which is what it generates for a parameter of type `IEnumerable<(TKey key, TValue value)>`. This means that Visual Studio can't find the documentation when the NuGet package is installed.

**Comment by jaredpar** [comment]
CC @jcouv

**Comment by jcouv** [comment]
Fixed by #18380. The documentation printer will output `System.ValueTuple{...}` (which is similar to `Tuple` and any other generic type). 
This fix is scheduled to ship in the first quarterly release of VS2017 (dev15.3).

Thanks @VictorGavrish for reporting this.

**Comment by VictorGavrish** [comment]
Wow, thanks for fixing it so quickly. I didn't expect this to be prioritised so highly.

**Comment by jcouv** [comment]
Also fixed in VB (which I forgot in the first PR), by https://github.com/dotnet/roslyn/pull/18435
