### ISSUE TITLE
 Operand of the IUnaryOperatorExpression doesn't implement any specific IOperation

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#18289]
http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/IExpression.cs,444 

also refer https://github.com/dotnet/roslyn/issues/8825

**Comment by mavasani** [comment]
I am not sure I understand this issue. @jinujoseph what needs to be changed here? The API looks fine as is to me.

**Comment by mavasani** [comment]
I am not sure I understand this issue. @jinujoseph what needs to be changed here? The API looks fine as is to me.

**Comment by jinujoseph** [comment]
hmm, don't remember now, closing this out.
