### ISSUE TITLE
nameof(System.Void) doesn't work

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#18284]
The compiler reports an error when ```nameof(System.Void)``` is used:

```
error CS0673: System.Void cannot be used from C# -- use typeof(void) to get the void type object
```

Expected: 
The result of the expression should be "Void".

**Comment by alrz** [comment]
Actually, none of primitives are allowed in `nameof`.

**Comment by tmat** [comment]
Ah, I see. Updated.

**Comment by jaredpar** [comment]
This is "By Design". The expression inside `nameof` must be a legal simple name or member access . If the expression is in error then it's illegal in `nameof`. The one exception is referencing an instance member from a type reference.
