### ISSUE TITLE
Move "Type Style" analyzers from Features layer to Code Style layer

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#18281]
The type style analyzers should be moved from the Features layer (which only runs in the IDE) to the new Code Style layer (which runs during the compilation process). This includes `CSharpTypeStyleDiagnosticAnalyzerBase` along with its derived types, and the associated code fixes.

:memo: For those not aware, this is the Use/Don't Use `var` analyzer (IDE0007, IDE0008).

📝 Depends on #18278

**Comment by Youssef1313** [comment]
This was fixed in https://github.com/dotnet/roslyn/pull/42209. @sharwell Should this get closed?
