### ISSUE TITLE
[Flaky Test] Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.GenerateMethodInClosedFile

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18295]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration/633/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpCodeActions/GenerateMethodInClosedFile/

```
Assert.Equal() Failure
 ↓ (pos 2)
Expected: \\r\\nusing System;\\r\\n\\r\\npublic class Foo\\r\\n{\\r\\n ···
Actual:     \\r\\npublic class Foo\\r\\n{\\r\\n}\\r\\n
 ↑ (pos 2)
```

**Comment by 333fred** [comment]
@Pilchie, can you assign this to someone please?

**Comment by 333fred** [comment]
@jmarolf, could your changes from https://github.com/dotnet/roslyn/commit/f4f341ec3987d8326657c6ebc1f252edf524e698#diff-d3e832a0d28d7d40123b9188e262c271 be related?

**Comment by Pilchie** [comment]
Starting with @jmarolf, but also heads up @rchande

**Comment by 333fred** [comment]
@jmarolf, any progress?

**Comment by 333fred** [comment]
Jenkins Logs:

```
 Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.GenerateMethodInClosedFile
      Assert.Equal() Failure
                     (pos 2)
      Expected: \r\nusing System;\r\n\r\npublic class Foo\r\n{\r\n   Â·Â·Â·
      Actual:   \r\npublic class Foo\r\n{\r\n}\r\n
                     (pos 2)
      Stack Trace:
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\Extensions\SolutionExplorerExtensions.Verifiers.cs(27,0): at Roslyn.VisualStudio.IntegrationTests.Extensions.SolutionExplorer.SolutionExplorerExtensions.VerifyFileContents(AbstractIntegrationTest test, Project project, String fileName, String expectedContents)
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpCodeActions.cs(48,0): at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.GenerateMethodInClosedFile()
```

![image](https://cloud.githubusercontent.com/assets/2371880/24670673/cfcc49e0-1923-11e7-9ef0-5d1129beaceb.png)

**Comment by Pilchie** [comment]
Hit this for VB in https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/5207/, https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/5191/.

**Comment by jmarolf** [comment]
This test is flaky because we expect this code to be generated:
```C#
using System;

public class Foo
{
    internal void Bar() => throw new NotImplementedException();
}
```

And sometimes this code is generated instead:
```C#
using System;

public class Foo
{
    internal void Bar() 
    {
        throw new NotImplementedException();
    }
}
```

We need a way to get/set the member generation options from the integration test.  @CyrusNajmabadi I believe you changed a lot in the options code recently?

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving out.

**Comment by sharwell** [comment]
> This test is flaky because we expect this code to be generated:

This was corrected in 0f854a325e50a604774941884ece63ff14376272 but the test is now being unskipped with an updated assertion in #25151.

**Comment by jinujoseph** [comment]
Closed via [Link](https://github.com/dotnet/roslyn/pull/25151)

**Comment by 333fred** [comment]
Doesn't look like this fixed it @sharwell, https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_vs-integration/1996/

**Comment by sharwell** [comment]
Superseded by #26204
