### ISSUE TITLE
Provably correct code fails to compile in VS 2017

### ISSUE THREAD

**Issue by smmalis37** [dotnet/roslyn#18299]
**Version Used**: Microsoft Visual Studio Enterprise 2017
Version 15.0.26228.10 D15RTWSVC
Microsoft .NET Framework
Version 4.7.02046

Visual C# 2017   00369-60000-00001-AA113
Microsoft Visual C# 2017

**Steps to Reproduce**:

1. Attempt to compile the following function:
```
private bool TryFoo(string[] manyThings, out Exception exception)
{
    bool succeeded = true;

    foreach (string thing in manyThings)
    {
        if (!TryDoThing(thing, out exception))
        {
            succeeded = false;
        }
    }

    if (succeeded)
    {
        exception = null;
    }

    return succeeded;
}
```

**Expected Behavior**:
The function should compile.

**Actual Behavior**:
The function does not compile with the error that exception is not assigned a value on all code paths.

**Rationale**
The fact that exception is assigned a value on all code paths is provable at compile time. There are 2 code paths here: either manyThings has 1 or more values, or it has none. If it has at least 1 value, we will call TryDoThing which will assign a value. If it has none, the if condition will always be true, and exception will be assigned a value.

**Easy workaround**
Set `exception = null` as the first line in the function, and everything's fine. In my case this was functionally equivalent.

**Comment by jaredpar** [comment]
This behavior is by design.  The compiler definite assignment rules do not take into account this type of flow analysis.
