### ISSUE TITLE
Design Question : Should we have a special node for Out Var Declaration

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#18303]
Example here : https://github.com/dotnet/roslyn/issues/18300

**Comment by jinujoseph** [comment]
we need a way to represent this

**Comment by jinujoseph** [comment]
@333fred , can you come up with the API proposal here

**Comment by 333fred** [comment]
Some example code for context:
```C#
class C1
{
    public void M1()
    {
        M2(out var i);
    }
    public void M2(out int i)
    {
        i = 1;
    }
}
```

**Comment by 333fred** [comment]
In this scenario, the underlying BoundNode for `out var i` is actually just a BoundLocal, which we already map to ILocalReferenceExpression. The underlying BoundLocal has a field on it, `IsDeclaration`, that is true here and false when not in an out var declaration or in a deconstruction statement. The simple solution here would be to just add a new field to ILocalReferenceExpression:
```
/// <summary>
/// True if this reference is also the declaration site of this variable. This is true in out variable declarations
/// and in deconstruction operations where a new variable is being declared.
/// </summary>
public bool IsDeclaration { get; }
```

The BoundLocal node for these declarations doesn't have anything else interesting in it that isn't already captured by the ILocalReferenceExpression.

Alternatively, we could create a new class `ILocalDeclarationAndReferenceExpression` that is exactly the same as ILocalReferenceExpression. We would then modify the CSharpOperationFactory's handling of BoundLocal to return the correct type.

**Comment by CyrusNajmabadi** [comment]
Design decision: We will do things as @333fred outlined.  Note that we may also need to add .IsDeclaration to "IFieldReferenceExpression".

We should also test and validate that this all works for "out var" as well as deconstructions like "(var x, var y) = ..."

**Comment by 333fred** [comment]
The underlying `BoundFieldReference` has no concept of whether or not the field was declared here, so I don't think that there's a good way of getting that information.

**Comment by CyrusNajmabadi** [comment]
> The underlying BoundFieldReference has no concept of whether or not the field was declared here

We can either go back to syntax (as an implementation detail, not for the client to have to do).  Or we can add this info to BoundFieldReference.
