### ISSUE TITLE
IOperation doesn't support string interpolations

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#18300]
**Example Code** 
using System;
class P
{
    private void M()
    {
        var s = "";
        if (int.TryParse(s, out var i))
            Console.WriteLine($"i ={ i}, s ={ s}");
        else
          Console.WriteLine($"i ={ i}, s ={ s}");
    }
}

Try generating Ioperation tree for Ifstatement
**Generated Tree**

IOperation tree for "if (int.TryParse(s, out var i))
            Console.WriteLine($"i ={ i}, s ={ s}");
        else
          Console.WriteLine($"i ={ i}, s ={ s}");"

IIfStatement (OperationKind.IfStatement)
  Condition: IInvocationExpression (static System.Boolean System.Int32.TryParse(System.String s, out System.Int32 result)) (OperationKind.InvocationExpression, Type: System.Boolean)
      IArgument (Matching Parameter: s) (OperationKind.Argument)
        ILocalReferenceExpression: s (OperationKind.LocalReferenceExpression, Type: System.String)
      IArgument (Matching Parameter: result) (OperationKind.Argument)
        ILocalReferenceExpression: i (OperationKind.LocalReferenceExpression, Type: System.Int32)
  IExpressionStatement (OperationKind.ExpressionStatement)
    IInvocationExpression (static void System.Console.WriteLine(System.String value)) (OperationKind.InvocationExpression, Type: System.Void)
      IArgument (Matching Parameter: value) (OperationKind.Argument)
        IOperation:  (OperationKind.None)
  IExpressionStatement (OperationKind.ExpressionStatement)
    IInvocationExpression (static void System.Console.WriteLine(System.String value)) (OperationKind.InvocationExpression, Type: System.Void)
      IArgument (Matching Parameter: value) (OperationKind.Argument)
        IOperation:  (OperationKind.None)

**Comment by mavasani** [comment]
My proposed API:

```
public interface IInterpolatedStringExpression : IOperation
{
    /// <summary>
    /// Contents of interpolated string.
    /// </summary>
    ImmutableArray<IInterpolatedStringContent> Contents { get; }
}

public interface IInterpolatedStringContent : IOperation
{
}

public interface IInterpolatedStringText : IInterpolatedStringContent
{
    /// <summary>
    /// Text content
    /// </summary>
    IOperation Text { get; }
}

public interface IInterpolation : IInterpolatedStringContent
{
    /// <summary>
    /// Expression
    /// </summary>
    IOperation Expression { get; }

    /// <summary>
    /// Optional alignment
    /// </summary>
    IOperation Alighment { get; }

    /// <summary>
    /// Optional format string.
    /// </summary>
    IOperation FormatString { get; }
}
```

**Comment by mavasani** [comment]
Point to discuss: BoundInterpolation is a BoundNode in VB but BoundExpression in C#.

**Comment by jinujoseph** [comment]
**Design Team Decision**

Design Teams proposal was to go with proposal 2 (Complex shape but richer hierarchy)

**Comment by jinujoseph** [comment]
This is done via #19590
