### ISSUE TITLE
Compiler Happily Emits Task<void>

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1830]
Source:

```C#
var t = Task.Run(() => {
	return Console.Beep();
});
```

**This should [not compile!](http://tryroslyn.azurewebsites.net/#b:master/f:sr/K4Zwlgdg5gBAygTxAFwKYFsDcAoUlaIoYB0AKgBYBOqAhgCb5k0gDWIOAbjZTMjALwxSzFsQBKwCAAopASgEA+GAG9sASGrJglCDADCAewggDAG1TEAQqlQAHOTgC+snEAA=)**

The IDE also happily reports that `t` is a `Task<void>`.
Running it throws a TypeLoadException: `The generic type 'System.Func`1' was used with an invalid instantiation in assembly mscorlib`

**Comment by AlgorithmsAreCool** [comment]
Despite this being an obvious bug, i wish it was legal to use void as a generic parameter.

**Comment by SLaks** [comment]
@AlgorithmsAreCool Feel free to file a feature request in dotnet/coreclr.

**Comment by lawrencejohnston** [comment]
@SLaks @AlgorithmsAreCool This is suggested in #234.

**Comment by theoy** [comment]
Nice catch! :)

**Comment by AdamSpeight2008** [comment]
@SLaks 

Let's say the CLR allowed `Func<Void>` how would it work with `Action<>`, especially overload resolution?

**Comment by SLaks** [comment]
@AdamSpeight2008 `Action` would take precendence, just like `Func<int>` vs `delegate int MyDelegate();`.

**Comment by gafter** [comment]
@AlekseyTs Can you "Verify" this please?
