### ISSUE TITLE
Calling context.ReportDiagnostic() from RegisterCompilationEndAction() callback produces warnings without squiggles or code fixes

### ISSUE THREAD

**Issue by bartkoelman** [dotnet/roslyn#1831]
In CTP6, my Analyzer provides a callback for RegisterCompilationEndAction(). Using a custom visitor, it acts on method/field/property symbols. It then produces warnings in the Errors list as expected, but double-clicking on them does not jump to the source code (line numbers are displayed). Also there are no squiggles on the affected symbols and the FixProvider is not invoked when hovering over the affected source code. 

When I change my analyzer back to respond on RegisterSymbolAction directly, all works fine. However then my Analyzer cannot search all symbols in the solution for existence of a special attribute reliably. 

In VS settings, I have "Show diagnostics for closed files" checked (default).

I would expect squiggles and invocation of the code fix provider when reporting a diagnostic on a symbol, whether from RegisterCompilationEndAction() or RegisterSymbolAction().

**Comment by mavasani** [comment]
All these issues have been fixed post-CTP6 by @heejaechang 

However, I am not sure I understand this: _"When I change my analyzer back to respond on RegisterSymbolAction directly, all works fine. However then my Analyzer cannot search all symbols in the solution for existence of a special attribute reliably"_

The attribute symbol should be defined in the compilation. You should be using a RegisterCompilationStartAction/SymbolAction pattern like here: http://source.roslyn.io/#Microsoft.CodeAnalysis.FxCopAnalyzers/Design/CA1003DiagnosticAnalyzer.cs,65
Look for your attribute type of interest in the compilation start action using this API: http://source.roslyn.io/Microsoft.CodeAnalysis/R/b69619b653a39389.html, and cache it in the per-compilation analyzer instance and reference it from the registered symbol action callback on this instance.

**Comment by bartkoelman** [comment]
Hi mavasani, thanks for your suggestions. 

Good to know about analyzer instance lifetime, I was wondering about that. I have now switched to using the RegisterCompilationStartAction/SymbolAction pattern, which exactly fits my needs and solves my issues.

I am aware of Compilation.GetTypeByMetadataName(), but in my scenario I search for a named type that is not fully qualified. It may occur in any namespace and even in referenced projects or assemblies. To achieve this, I use compilation.GetSymbolsWithName(), followed by looping over compilation.References, passing each of them to a custom symbol visitor that starts at compilation.GetAssemblyOrModuleSymbol(reference).GlobalNamespace. 

I am a bit worried about performance for resolving the attribute in large solutions. I will play a bit with that later. Would it be possible to somehow pass my cached results onto the associated fix provider instance? Or maybe is there an API using which I can check that the cached symbols still exist in the FixProvider compilation instance?

**Comment by heejaechang** [comment]
@bartkoelman diagnostic has properties that you can store string.

by the way, even though GetSymbolsWithName is not as expensive as walking whole symbols in the compilation, it is still quite expensive operation. if you really need to do it, you should use CompilationEndAction or do it only once and cache metadataname string of the symbol you found so that next run you can just use GetTypeByMetadataName.

**Comment by bartkoelman** [comment]
@heejaechang thanks for helping out. 

Diagnostic's CustomTags is what I used to pass Analyzer results to the FixProvider, must have looked over it before.

Also I implemented caching as you suggested. To get the full metadata name I used the code at http://stackoverflow.com/questions/27105909/get-fully-qualified-metadata-name-in-roslyn.

Very nice!

**Comment by mavasani** [comment]
@bartkoelman Diagnostic.Properties (http://source.roslyn.io/#Microsoft.CodeAnalysis/Diagnostic/Diagnostic.cs,47) was added very recently to allow storing a custom property bag per-diagnostic instance. Descriptor's CustomTags allows storing tags per-descriptor which cannot be configured per-diagnostic instance created through the descriptor.

**Comment by bartkoelman** [comment]
@mavasani In CTP6 it's not yet available. Currently I clone the initial descriptor, adding in the custom tags, each time a diagnostic is reported. This seems to work fine. Was the .Properties added for convenience only or am I missing something?

**Comment by mavasani** [comment]
@bartkoelman Nope, it was added because cloning descriptors is not the correct way to add per-diagnostic properties. A descriptor is supposed to represent metadata for all diagnostics with a given ID, and you should create just a single instance of descriptor per ID. Custom tags on diagnostic descriptor should represent custom properties about all diagnostics with an ID. Property bag on the diagnostic should be used to store custom information which is specific to each diagnostic instance. Once you move to a newer Roslyn drop, you should change your code to use the property bag.

**Comment by mavasani** [comment]
@srivatsn @heejaechang We should probably add verification code to Diagnostic.Create to verify that the passed in descriptor is reference equals one of the descriptors returned from DiagnosticAnalyzer.SupportDiagnostics, and if not throw?

**Comment by heejaechang** [comment]
@srivatsn @mavasani ya, we should enforce that.

**Comment by bartkoelman** [comment]
@mavasani Thanks for your clarification. I will add a TODO for it in my code and update when the next drop becomes available.

**Comment by mavasani** [comment]
@bartkoelman I am closing this issue as the underlying issues have all been fixed.

**Comment by bartkoelman** [comment]
I agree, thanks
