### ISSUE TITLE
Insert `}`, `)` and `]` at the end of selected span

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#18319]
As an alternative to https://github.com/dotnet/roslyn/issues/16949, I suggest we insert `}`, `)` and `]` at the end of the selected span.

```cs
if (expr) [|return;|]
```
Typing open curly brace <kbd>{</kbd> should also insert the close curly brace.
```cs
if (expr) {[|return;|]} // remains selected
```
And hitting <kbd>Enter</kbd> should format the whole statement (https://github.com/dotnet/roslyn/issues/17164),
```cs
if (expr)
{
    return;
}
```
This is basically what sublime text does.

**Comment by sharwell** [comment]
I believe VS Code behaves the way you describe as well.

**Comment by Pilchie** [comment]
I like this suggestion - @DustinCampbell @kuhlenh what do you think about it?

**Comment by DustinCampbell** [comment]
Yup -- I think it should be a core editor feature though.

**Comment by miloush** [comment]
Not free though, it breaks the current behavior of replacing the selection. Definitely sounds something I would want to turn off.

(And it might need to respect the disable automatic brace completion setting.)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback asking for this.  This would also go through the editor and their brace matching system.  So is better served as a request to developercommunity.
