### ISSUE TITLE
report which document FAR is initiated in FAR telemetry

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#18327]
we want this to distinguish Roslyn FAR from one from type script and others.

this issue address this work item

"15.3, I want additional information on project types involved, so that we can tease out (for example) TypeScript-related FAR issues from ours."

**Comment by Pilchie** [comment]
This should probably apply to the other things we report as well (Format Document/Rename/GoTo)?

**Comment by heejaechang** [comment]
good point.

**Comment by CyrusNajmabadi** [comment]
Closing out as there are no requests for this, and we want to resrtat with telemetry to get proper hygiene with it.
