### ISSUE TITLE
VS 2015 Update 3 hangs

### ISSUE THREAD

**Issue by udlose** [dotnet/roslyn#18329]
**I have a memory dump that is 1.7GB in size.  Please let me know how I can get this to you!**

**Strange observations:**
1. I read about a hang with Update 3 (https://github.com/dotnet/roslyn/issues/12317) and pulled the cumulative update - KB3165756 (https://msdn.microsoft.com/library/mt752379). It says it successfully installed and shows up in my list of Windows installed updates - as well as the About dialog in VS.  However, my executable and the error message in Application Event Viewer (message below) list the version as 14.25420.1 instead of 14.0. 25431.01 (the cumulative update) so I'm not positive it is actually updated.

2. this seems to be project specific. I deleted the .suo thinking it was corrupt but it didn't change anything. I have also disabled Solution-wide Analysis - again didn't work.

**Version Used**: VS2015 14.0.254.20.1 (Update 3)

**Steps to Reproduce**:

1.  Open VS as administrator
2. Open a solution (seems to be solution-specific)
3. VS completes loading solution
4. within 10-20 seconds, VS just hangs and is non-responsive

**Expected Behavior**:
VS does not hang

**Actual Behavior**:
VS hangs and I have to kill the process

**Error Message from Application Event Viewer after I kill the process:**
The program devenv.exe version 14.0.25420.1 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 49d0
 Start Time: 01d2a971b6255985
 Termination Time: 4294967295
 Application Path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
 Report Id: 04cd0394-1566-11e7-b28b-34f39a954916
 Faulting package full name: 
 Faulting package-relative application ID:

**Comment by Pilchie** [comment]
Can you email me at kevinpi@microsoft.com and I will set up a OneDrive for Business folder you can upload to.

**Comment by udlose** [comment]
I was able to find another dev in my group who had the same problem.  It turned out somehow his GIT repo info that VS must read was jacked up?  He suggested running the GIT cmd below which so far has solved the problem.  In any case, VS should certainly not hang :)

git clean -dfx

**Comment by Pilchie** [comment]
That command deletes all the files in the tree that aren't explicitly added to git.  I'll take a look at the dump to see if I can find out what was hanging VS in there.

**Comment by Pilchie** [comment]
We've been following up on this offline, and have determined that the issue is in NuGet.  @jainaashish has been following up there.
