### ISSUE TITLE
Inline temp variable into an extension method invocation causes leading "this." to be parenthesized

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#18322]
**Version Used**: VS2017

**Steps to Reproduce**:

1. Copy/Paste C# code:
```C#
public class Class1
{
    void M()
    {
        var c = 8;
        this.DoStuff(c);
    }
}

public static class Class1Extensions { public static void DoStuff(this Class1 c, int x) { } }
```
2. Run Inline Temp on `c`

**Expected Behavior**: `this.DoStuff(8);`

**Actual Behavior**: `(this).DoStuff(8);`

**Comment by Pilchie** [comment]
I'm sort of surprised that we didn't have tests for this, but I guess extension methods on `this` aren't *that* common.
