### ISSUE TITLE
InvalidCastException at VisualBasicSyntaxFactsService.TryGetDeclaredSymbolInfo

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#1834]
Ported from internal work items 1152014 and 1153151.

-----

### Repro
Create a new VB console application then paste this directly below the `Module` definition:

``` VB
Public Sub New()
End Sub
```

### Result
System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.Syntax,TypeBlockSyntax' at VisualBasicSyntaxFactsService.TryGetDeclaredSymbolInfo line 742.

**Comment by Pilchie** [comment]
Re-opening to track porting to preview.

**Comment by Pilchie** [comment]
Fixed by 3dd55d8
