### ISSUE TITLE
Naming styles options show up in the wrong language if you have multiple languages installed

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#18340]
I have Japanese and English installed, English is selected:

![image](https://cloud.githubusercontent.com/assets/1103906/24537242/9b3a98ac-162c-11e7-8820-9be719523521.png)

Everything in options is in English, except naming styles:

![image](https://cloud.githubusercontent.com/assets/1103906/24537270/c1ad33a0-162c-11e7-97e2-bbb34c2fbc31.png)

**Comment by dpoeschl** [comment]
@davkean These strings are not dynamic in that way. You can change the names of them through the UI, or create your own with special names. The first time naming styles starts up, it grabs a [localized XML blob](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/NamingStyles/Serialization/NamingStylePreferences.cs,f020dbc473670cce) and then stores that as your user setting for that option. From then on, you'll see them in whatever language it was initialized in.

We don't try to back-infer that the name you gave a rule matches a known loc string and then localize the display. In your settings, the specification/style has a name populated from that default xml blob, and that's it. I don't consider this a loc bug, as it's just reading from your settings, and it happens that the setting is initially created in some language. Closing preemptively, but tagging @nguerrera in case he has an objection to the current behavior.

**Comment by nguerrera** [comment]
Is there at least an option to reset to defaults for someone getting stuck in this state?

**Comment by dpoeschl** [comment]
@nguerrera Not directly in the feature itself. I *think* resetting your C# settings through "Import and Export Settings" would do it, but that's a bit of a heavy hammer. Also I haven't tested this.

Technically, nobody ever gets "stuck" in this state. You can always go through and rename all of the things. It's annoying, but not "stuck". I'm not arguing that it's a good experience, just that there exists *some* workaround.

**Comment by davkean** [comment]
I disagree with this resolution, my machine is now in state that's not clear how I reset just these settings without throwing always all my settings:

![image](https://cloud.githubusercontent.com/assets/1103906/24986516/0ed68382-203e-11e7-91c6-24af52d1c0f4.png)

Because I happened to open the settings page once while I had Japanese selected, it means that these are forever in Japanese? I don't even have it installed anymore. This feels like an implementation detail bleeding through...

**Comment by CyrusNajmabadi** [comment]
@dpoeschl 

> The first time naming styles starts up, it grabs a localized XML blob and then stores that as your user setting for that option.

I'm not sure that's a good idea.  With settings we should only be storing things the user explicitly has set.  If the user hasn't changed the setting, then we probably shouldn't be persisting anything.

If we followed that approach, then the we would always get the fresh set of options for the user, and that should show up properly for the user.  Of course, once they change anything, then we should persist it.  And then i think it would be acceptable that whatever default title we picked for that locale would then be what you would always see.

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Another thing to consider is the idea that *under the covers* the title for these is 'null', And we map the well known initial settings to localized strings on demand.   That way, when a user provides their own title, we absolutely store and migrate it properly.  However, the well-known rules will have titles that always show up properly until the user changes is away from the default (null).

That said, this is likely very low priority. I would do this work if/when we make more investments in this area.

**Comment by CyrusNajmabadi** [comment]
Closing out as we have not heard more reports on this.
