### ISSUE TITLE
.editorconfig namespace catches type parameters

### ISSUE THREAD

**Issue by angelsix** [dotnet/roslyn#18345]
dotnet_naming_rule.namespace_pascal_case.severity = error
dotnet_naming_rule.namespace_pascal_case.symbols  = namespace_pascal_case_symbols
dotnet_naming_rule.namespace_pascal_case.style    = namespace_pascal_case_style

dotnet_naming_symbols.namespace_pascal_case_symbols.applicable_kinds   = namespace

dotnet_naming_style.namespace_pascal_case_style.capitalization  = pascal_case

This causes names of parameters passed into methods to be caught by this rule

`public void Test(int myParam) {}` 

So I cannot style namespaces to be Pascal, with type_parameters as camelCase

**Comment by dpoeschl** [comment]
@angelsix Thanks for the bug report! I'm not able to repro the problem you're seeing where this .editorconfig is squiggling "myParam". Is that your entire "naming" section of your .editorconfig? Do you have any additional Naming Rules set in the VS Tools | Options | Text Editor | C# | Code Style | General UI? Can you provide any more detail on that?

Regardless, "namespace" isn't currently a supported symbol kind to apply naming rules to, [see the code](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/Analyzers/NamingStyleDiagnosticAnalyzerBase.cs,28), so this rule won't work.

**Comment by dpoeschl** [comment]
Closing for now. Let me know if you have more information about that first part in my previous comment.
