### ISSUE TITLE
Datetime keyword missing on SyntaxKind

### ISSUE THREAD

**Issue by Nassiel** [dotnet/roslyn#18346]
**Version Used**: Latest master (commit: 940f119)

**Steps to Reproduce**:

1. Read visual basic syntax tree for translate it into c# code
2. Find a date keyword
3. Try to translate to datetime c# keyword and try to find it in SyntaxKind enum

So, ¿what keyword I should write/use? And I miss some other keywords like, dynamic.

Thanks.

**Comment by sharwell** [comment]
There is no `Date` keyword in C#. You'll need to use the underlying type `DateTime` instead.

Here's one way you can create a syntax node for this type:

```csharp
TypeSyntax dateTimeTypeSyntax = SyntaxFactory.ParseTypeName(typeof(DateTime).FullName)
    .WithAdditionalAnnotations(Simplifier.Annotation)
```

**Comment by Nassiel** [comment]
Hi, thanks! 

In the end I needed another function: `SyntaxFactory.IdentifierName(typeof(DateTime).FullName)` But you raise the right event in my mind.

So, solved. 👍
