### ISSUE TITLE
[IOperation] Hidden sub nodes

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18351]
When you get an IOperation node, there are scenarios where, due to things like invalid syntax, there are child syntax nodes with valid IOperations that you cannot get to from the parent node. As an example, take this (invalid) C# code:

```C#
class Program
{
    static void Main(string[] args)
    {
        int[1, 2] x;
    }
}
```

This produces the following syntax tree:

![image](https://cloud.githubusercontent.com/assets/2371880/24562967/a89f16d8-1601-11e7-9f93-fffb31543d39.png)

In syntax, we're able to get to the invalid `ArrayRankSpecifier`, even though such a construct shouldn't exist. If we get the `IOperation for the `VariableDeclaration`, we get the following tree:

```
IOperation tree for "int[1, 2] x"

IVariableDeclarationStatement (1 variables) (OperationKind.VariableDeclarationStatement)
  IVariableDeclaration: System.Int32[,] x (OperationKind.VariableDeclaration)
```

Here, there is no indication that there are other nodes below the `IVariableDeclaration`'s type. We can retrieve those IOperations, however, by getting the IOperation for the `NumericLiteral`s that make up the array rank specifier. To deal with this, we'll likely have to expose some kind of general Children attribute, where we can put all of these invalid nodes that otherwise don't have a place to be exposed. Related to #17802.

**Comment by jinujoseph** [comment]
**Design Team Meeting**

This is a very corner case scenario. Unless we see more instances of this kind, the decision was that we should not be able to get to the Ioperations of this. We should essentially hide them and return null.

**Comment by jinujoseph** [comment]
This should be fixed now.
pls verify and close

**Comment by 333fred** [comment]
With the changes to the way that GetOperation works, it's no longer possible to retrieve those individual IOperations, as per design decision.
