### ISSUE TITLE
Intellisense offers wrong suggestion after dismissal and re-opening in context of switch-case

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#18359]
**Version Used**: 15.0.0.+26228.9

**Steps to Reproduce**:

```CSharp
public sealed class VSConstants
{
    public enum VSStd2KCmdID
    {
        TYPECHAR = 1,
    }

    public enum VSStd97CmdID
    {
        Expand = 187,
    }
}

class Program
{
    static void Main(string[] args)
    {
        switch((VSConstants.VSStd97CmdID)5)
        {
             //Begin typing here vvvv
            case VSConstants.
        }
    }
}
```

1. Type `vss`
2. Observe completion list is correct.
3. Dismiss completion. (`Esc`)
4. Open completion (`Ctr-space`)
5. Observe that incorrect item has been inserted and selected in list.

![image](http://i.imgur.com/byicTEz.gif)

**Comment by CyrusNajmabadi** [comment]
@rchande didn't you fix something where we were offering the full enum preselect when a person was typing after a dot?

**Comment by rchande** [comment]
@CyrusNajmabadi This case is interesting. We correctly type infer that `VSConstants.VSStd97CmdID` is required and call ToMinimalDisplayString on it. However, ToMinimalDisplayString doesn't account for any qualification that might appear before the position we pass in. It produces the most sensible minimal display string, which is, in fact, `VSConstants.VSstd97CmdID. We'll need to do some work to trim off any qualification that's already present. Do you know if we have any helpers that can already do that?

**Comment by JoshVarty** [comment]
I'm not sure if this is related, but some options aren't showing up in Intellisense.

For example:

`VSStd2K` is not being offered to be as a suggestion in the following code:

```CSharp
var guid = VSConstants.VSStd //<-Cursor here with Intellisense up
```

![image](http://i.imgur.com/oUExd3k.gif)

**Comment by JoshVarty** [comment]
I'm not sure if this is related, but in the following code, the suggestion `VSStd2K` is missing from the list. 

**Note: I cannot get this to repro with the above code, but it repros if you add a reference to `Microsoft.VisualStudio.Shell.15.0`**

```
var guid = VSConstants.VSStd; //<-Bring up Intellisense here
```

![image](http://i.imgur.com/oUExd3k.gif)
