### ISSUE TITLE
Why "Constraint cannot be special class 'Enum'"? It is possible in F# and MSIL

### ISSUE THREAD

**Issue by lostmsu** [dotnet/roslyn#18369]
**Version Used**: 
C# 7
**Steps to Reproduce**:
```c#
void Func<T>() where T: System.Enum {}
```

**Expected Behavior**:
Should compile
**Actual Behavior**:
`error CS0702: Constraint cannot be special class 'Enum'`

I'm guessing it is "by design", but what is the reason for this design? F# and MSIL both appear to handle that constraint. Also, according to https://stackoverflow.com/questions/79126/create-generic-method-constraining-t-to-an-enum/8086788#8086788, C# itself can then consume such a method no problem.

**Comment by jaredpar** [comment]
You are correct that this is "By Design".  Indeed it is supported at the MSIL level and C# can consume such definition.  Adding support though is work and it's something the language team has discussed a few times, it's just never had enough priority compared to other feature work we've done.

**Comment by lostmsu** [comment]
I don't quite understand why close the issue? If Microsoft is not going to work on this, someone else could.
