### ISSUE TITLE
FAR results in Web Application projects could use improvement

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#18382]
A couple of problems here:

1. Each aspx/.cshtml file is it's own "project" in Roslyn, so the grouping by project is messy.  We should try to unify by the `IVsHierarchy`.
2. The code preview is showing the secondary buffer/C# content, but we should be mapping to the surface buffer.
3. Because of (2), the line/column info is wrong and navigation doesn't behave as expected (when it works).

Here is an example result set: 

![image](https://cloud.githubusercontent.com/assets/312835/24591732/2665219a-17bd-11e7-8735-701180f69841.png)

**Comment by CyrusNajmabadi** [comment]
WAP is no longer supported.  Razor FAR is owned by them now.
