### ISSUE TITLE
EnvDTE.CodeFunction.StartPoint, EndPoint, GetStartPoint, etc. cause exception for VB.NET "Declare Sub"/"Declare Function" methods

### ISSUE THREAD

**Issue by carlos-j-quintero** [dotnet/roslyn#1839]
See MS Connect bug:

https://connect.microsoft.com/VisualStudio/feedback/details/1232254/envdte-codefunction-startpoint-endpoint-getstartpoint-etc-cause-exception-for-vb-net-declare-sub-declare-function-methods

I didn't detect this bug before because there was a previous bug #148.

**Comment by Pilchie** [comment]
Let's see if this is simple enough to pull into preview.

**Comment by basoundr** [comment]
Ported from TFS WorkItem: **1153282**

------------------------------



**Repro Steps:**

When you use the code model (EnvDTE) to get if the start / end edit points of a VB.NET method that is a &quot;Declare Sub&quot; or &quot;Declare Function&quot; method, you get NotImplementedException or NotSupportedException. In VS 2013 this worked fine.
  


  

Steps to reproduce:
  


  

1) Create a package in VB.NET with a command and this command event handler (also attached):
  


  

   Public Sub New()
  

   End Sub
  


  

   Protected Overrides Sub Initialize()
  

      MyBase.Initialize()
  


  

      &#39; Add our command handlers for menu (commands must exist in the .vsct file)
  

      Dim mcs As OleMenuCommandService = TryCast(GetService(GetType(IMenuCommandService)), OleMenuCommandService)
  

      If Not mcs Is Nothing Then
  

         &#39; Create the command for the menu item.
  

         Dim menuCommandID As New CommandID(GuidList.guidVSPackage1CmdSet, CInt(PkgCmdIDList.cmdidMyCommand))
  

         Dim menuItem As New MenuCommand(New EventHandler(AddressOf MenuItemCallback), menuCommandID)
  

         mcs.AddCommand(menuItem)
  

      End If
  

   End Sub
  


  

   Private Sub MenuItemCallback(ByVal sender As Object, ByVal e As EventArgs)
  


  

      Dim dte As EnvDTE.DTE
  


  


  

      dte = CType(MyBase.GetService(GetType(EnvDTE.DTE)), EnvDTE.DTE)
  


  

      ShowCodeElements(dte.ActiveDocument.ProjectItem.FileCodeModel.CodeElements)
  


  

   End Sub
  


  

   Sub ShowCodeElements(codeElements As EnvDTE.CodeElements)
  


  

      Dim codeClass As EnvDTE.CodeClass
  

      Dim codeFunction As EnvDTE.CodeFunction
  

      Dim textPoint As EnvDTE.TextPoint
  


  

      For Each codeElement As EnvDTE.CodeElement In codeElements
  


  

         Select Case codeElement.Kind
  


  

            Case EnvDTE.vsCMElement.vsCMElementClass
  


  

               codeClass = CType(codeElement, EnvDTE.CodeClass)
  

               ShowCodeElements(codeClass.Members)
  


  

            Case EnvDTE.vsCMElement.vsCMElementFunction
  


  

               codeFunction = CType(codeElement, EnvDTE.CodeFunction)
  

               Try
  

                  textPoint = codeFunction.StartPoint
  

               Catch ex As Exception
  

                  System.Windows.Forms.MessageBox.Show(ex.ToString())
  

               End Try
  


  

               Try
  

                  textPoint = codeFunction.EndPoint
  

               Catch ex As Exception
  

                  System.Windows.Forms.MessageBox.Show(ex.ToString())
  

               End Try
  


  

               Try
  

                  textPoint = codeFunction.GetStartPoint(EnvDTE.vsCMPart.vsCMPartWhole)
  

               Catch ex As Exception
  

                  System.Windows.Forms.MessageBox.Show(ex.ToString())
  

               End Try
  


  

               Try
  

                  textPoint = codeFunction.GetStartPoint(EnvDTE.vsCMPart.vsCMPartHeader)
  

               Catch ex As Exception
  

                  System.Windows.Forms.MessageBox.Show(ex.ToString())
  

               End Try
  


  

               Try
  

                  textPoint = codeFunction.GetStartPoint(EnvDTE.vsCMPart.vsCMPartName)
  

               Catch ex As Exception
  

                  System.Windows.Forms.MessageBox.Show(ex.ToString())
  

               End Try
  


  

         End Select
  


  

      Next
  


  

   End Sub
  


  

2) Run the package and create a VB.NET class library with this code:
  


  

Public Class C1
  

   Public Sub MethodA()
  

   End Sub
  


  

   &lt;System.Runtime.InteropServices.DllImport(&quot;MyDll.dll&quot;)&gt;
  

   Public Sub MethodB()
  

   End Sub
  


  

   Public Declare Sub MethodC Lib &quot;MyDll.dll&quot; ()
  


  

End Class
  


  

3) Click the package command.
  


  

4) Actual results: methods A and B don&#39;t cause exceptions. Method C causes exceptions
  


  

5) Expected results: actual points without exceptions

------------------------------




**Revisions:**



1) Created By Microsoft Connect (4/7/2015 12:53:32 PM)

------------------------</br>
Customer Information</br>
------------------------</br>
User ID: 3130757</br>
Handle: Carlos J. Quintero</br>
</br>
---------------------------</br>
Connect Site Information</br>
---------------------------</br>
Site Name: Visual Studio and .NET Framework</br>
Site ID: 210</br>
Feedback ID: 1232254</br>
Feedback Form: 6111</br>
</br>
----------------------</br>
Problem Description</br>
-----------------------</br>
When you use the code model (EnvDTE) to get if the start / end edit points of a VB.NET method that is a &quot;Declare Sub&quot; or &quot;Declare Function&quot; method, you get NotImplementedException or NotSupportedException. In VS 2013 this worked fine.

Steps to reproduce:

1) Create a package in VB.NET with a command and this command event handler (also attached):

   Public Sub New()
   End Sub

   Protected Overrides Sub Initialize()
      MyBase.Initialize()

      ' Add our command handlers for menu (commands must exist in the .vsct file)
      Dim mcs As OleMenuCommandService = TryCast(GetService(GetType(IMenuCommandService)), OleMenuCommandService)
      If Not mcs Is Nothing Then
         ' Create the command for the menu item.
         Dim menuCommandID As New CommandID(GuidList.guidVSPackage1CmdSet, CInt(PkgCmdIDList.cmdidMyCommand))
         Dim menuItem As New MenuCommand(New EventHandler(AddressOf MenuItemCallback), menuCommandID)
         mcs.AddCommand(menuItem)
      End If
   End Sub

   Private Sub MenuItemCallback(ByVal sender As Object, ByVal e As EventArgs)

      Dim dte As EnvDTE.DTE


      dte = CType(MyBase.GetService(GetType(EnvDTE.DTE)), EnvDTE.DTE)

      ShowCodeElements(dte.ActiveDocument.ProjectItem.FileCodeModel.CodeElements)

   End Sub

   Sub ShowCodeElements(codeElements As EnvDTE.CodeElements)

      Dim codeClass As EnvDTE.CodeClass
      Dim codeFunction As EnvDTE.CodeFunction
      Dim textPoint As EnvDTE.TextPoint

      For Each codeElement As EnvDTE.CodeElement In codeElements

         Select Case codeElement.Kind

            Case EnvDTE.vsCMElement.vsCMElementClass

               codeClass = CType(codeElement, EnvDTE.CodeClass)
               ShowCodeElements(codeClass.Members)

            Case EnvDTE.vsCMElement.vsCMElementFunction

               codeFunction = CType(codeElement, EnvDTE.CodeFunction)
               Try
                  textPoint = codeFunction.StartPoint
               Catch ex As Exception
                  System.Windows.Forms.MessageBox.Show(ex.ToString())
               End Try

               Try
                  textPoint = codeFunction.EndPoint
               Catch ex As Exception
                  System.Windows.Forms.MessageBox.Show(ex.ToString())
               End Try

               Try
                  textPoint = codeFunction.GetStartPoint(EnvDTE.vsCMPart.vsCMPartWhole)
               Catch ex As Exception
                  System.Windows.Forms.MessageBox.Show(ex.ToString())
               End Try

               Try
                  textPoint = codeFunction.GetStartPoint(EnvDTE.vsCMPart.vsCMPartHeader)
               Catch ex As Exception
                  System.Windows.Forms.MessageBox.Show(ex.ToString())
               End Try

               Try
                  textPoint = codeFunction.GetStartPoint(EnvDTE.vsCMPart.vsCMPartName)
               Catch ex As Exception
                  System.Windows.Forms.MessageBox.Show(ex.ToString())
               End Try

         End Select

      Next

   End Sub

2) Run the package and create a VB.NET class library with this code:

Public Class C1
   Public Sub MethodA()
   End Sub

   
   Public Sub MethodB()
   End Sub

   Public Declare Sub MethodC Lib &quot;MyDll.dll&quot; ()

End Class

3) Click the package command.

4) Actual results: methods A and B don't cause exceptions. Method C causes exceptions

5) Expected results: actual points without exceptions

------------------------------

2) Edited By Macy Qu (Shang Hai Wei Chuang Ruan Jian) (4/7/2015 9:51:09 PM)

repro on Win8.1 with VS2015 Pre-RC CTP

------------------------------

3) Edited By Kevin Pilch-Bisson (4/8/2015 9:35:49 AM)

Please copy the info from this to the GitHub but, and then resolve this in favor of that one.

------------------------------

**Comment by basoundr** [comment]
Opening the bug to track for preview

**Comment by Pilchie** [comment]
Re-closing now that this is merged to RC.
