### ISSUE TITLE
Extended file properties are missing from compiled assembly file.

### ISSUE THREAD

**Issue by r3db** [dotnet/roslyn#18427]
**Version Used**: 
VS2015

**Steps to Reproduce**:

```csharp
private static async Task CompileSolution(Solution solution)
{
    foreach (var id in solution.GetProjectDependencyGraph().GetTopologicallySortedProjects())
    {
        var compilation = await solution.GetProject(id).GetCompilationAsync();

        using (var exeStream = new FileStream($"{id.Id}.dll", FileMode.OpenOrCreate))
        {
            compilation.Emit(exeStream);
            await exeStream.FlushAsync();
         }
    }
}
```

Running the above code will generate an assembly **without** extended file properties like:
Copyright, Product Version, etc...

But compiling the same solution with Visual Studio sets the correct properties in the generated file.

**Expected Behavior**:
![image](https://cloud.githubusercontent.com/assets/9978724/24670246/991cd992-196d-11e7-9249-c3fc83b80d5c.png)

**Actual Behavior**:
![image](https://cloud.githubusercontent.com/assets/9978724/24669905/5f3da810-196c-11e7-810a-c490cbc6e356.png)

**Comment by gafter** [comment]
I'm not sure why this is filed as a Roslyn issue. You created a file and, though you asked Roslyn to put some bits in it, you (and not Roslyn) have control over how you create, open, and close the file.

**Comment by r3db** [comment]
@gafter I was hoping Roslyn would put all the necessary bits on it.
Including the appropriate extended file properties.
It seems not to the case.

**Comment by r3db** [comment]
**Solution**

```csharp
private static async Task CompileSolution(Solution solution)
{
    foreach (var id in solution.GetProjectDependencyGraph().GetTopologicallySortedProjects())
    {
        var compilation = await solution.GetProject(id).GetCompilationAsync();

        using (var exeStream = new FileStream($"{id.Id}.dll", FileMode.OpenOrCreate))
        using (var resStream = compilation.CreateDefaultWin32Resources(true, false, null, null))
        {
            compilation.Emit(exeStream, resStream);
            await exeStream.FlushAsync();
         }
    }
}
```
