### ISSUE TITLE
Is there a way to disable the option offered by the IDE to disable an analyzer?

### ISSUE THREAD

**Issue by taori** [dotnet/roslyn#18423]
As i have pointed out here:

http://stackoverflow.com/questions/43123127/how-can-i-disable-analyzer-suppression-for-custom-analyzers-in-visualstudio

i am genuinely wondering whether there is any way to prevent this behavior of offering to suppress analyzers which work in the scope of an Error.

Is there currently a way to do this? If not - would this be a feature which could be added?

Note that i think supression on non errors is perfectly fine. But on an error level it should be impossible in my opinion.

**Comment by sharwell** [comment]
:memo: For additional context, there are two cases where suppressing an error could be valuable:

1. When using the "Treat Warnings as Errors" compiler option
2. For analyzers which are capable of producing false positives, and the use of Error severity is intended as a "Must be dealt with" setting - either by correcting the issue or by suppressing it for the specific case

**Comment by taori** [comment]
Yes, supression certainly has a good reason for being in there. But there should also be ways to enforce an analyzer to execute no matter what. In my case it's an analyzer which detects AwaitExpressions where there is no ConfigureAwait specified.

At one stage my analyzer was faulty and rendered valid c# as false, because my analyzer false positive flagged an expression - This is where suppression would be handy to maintain build capability despite error. Positive feature in general.

But in general -> I want a library which references this analyzer to be forced to implement it like this - no matter what. I don't want that analyzer to be ignored with a mere key stroke. 

If there is any option to influence whether or not an analyzer can be mandatory or not i would be perfectly happy the way it is (I assume there is one, since it doesnt offer me to suppress default VS analyzers with a quick fix)

During research time i

**Comment by sharwell** [comment]
@taori You could create a second diagnostic that gets reported on a `#pragma warning disable` or `[SuppressMessage]` usage that targets your first diagnostic, forcing users to double-disable the item in order to suppress it.

**Comment by taori** [comment]
@sharwell I agree that would be a double nudge to point out to someone, that he absolutely should not be doing, what he is doing. But that would just add another case of "he should not be able to suppress this analyzer".

I just think it would be very useful if there was at least some option to make an analyzer mandatory - given that there should be a way which indicates to the analyzer developer not to be all that generous with making an analyzer unsuppressable.

**Comment by sharwell** [comment]
💭 Given the plethora of options available to development teams when it comes to code review processes, at this point I'm not convinced that the feature described in this proposal would provide any specific benefit which teams do not already have. Developers and leads are generally intelligent individuals quite capable of identifying and avoiding unwanted workarounds for project safeguards. As a specific example, if the authors of a library do not want anyone to suppress a warning related to the use of `ConfigureAwait`, then I fully believe that the library is not at risk of ever including such code.

:memo: This is by no means a deciding comment on the issue, but rather my personal opinion based on experiences with diagnostic reporting tools created by various companies.

**Comment by jmarolf** [comment]
@taori an explicit design decision with analyzers was that the developer always has control over their environment.  If they want some analysis to be an error then they can increase the severity of that diagnostic.  If they find some analysis to be giving false positives they can turn them off entirely.  It sounds like you are suggesting that analyzer authors be given the ability to set a default severity that cannot be overridden.  If a developer wants to disable or ignore a warning, that would show up in a code review, and presumably the developer would need to justify why they disabled analysis.  Could you explain to me what the use case is where we want the analyzer author to override settings on a developers machine that cannot be modified?

**Comment by taori** [comment]
I agree that probably every potential use case i could come up with could be resolved by doing code review. However not every company is big enough to do code reviews, because of reasons like management being too stubborn and not seeing the necessity in it. 

This leaves companies, which are focused on project based development, who potentially barely plan on any budget towards QA, with holes in the code, which could be easily fixed by a strictly enforced analyzer error.

Another potential idea to fix this is having the feature of unsuppressable analyzer errors in the IDE itself. Let's imagine that there is a file which tracks analyzers which cannot be suppressed at all. If that would be the case, i could just make sure to regularly check that file for changes - to see if someone made changes against my will.

At this point i am sure you will probably say "You could add analyzer checks on your build environment" - Yeah. Stubborn Management. I see your reasoning for not seing the need in this feature, but it would solve issues like this without any manpower/organization/build environment changes involved.

**Comment by jmarolf** [comment]
@taori There is nothing that we can do to stop developers from doing things on their machines.  A developer could uninstall an analyzer from their project.  I guess we could try and block that, but its a losing battle.  Fundamentally, we don't have anything that can lock a developers machine down like that.  Personally I prefer to trust devs to follow team rules and do whatever validation they can before checkin.

**Comment by jmarolf** [comment]
@taori I do think there is something here though.  Perhaps an easy way to push a set of settings across a team and manage them.  Would you find that useful?

**Comment by taori** [comment]
Yes, very. A team shared setting to manage analyzer settings would already be a big help, since it would centralize where those settings are and thus allowing to keep track of how they are being set. I think it's resharper which has a similar feature for code style settings, which can also be put into specific locations, which will lock in code styles and prevent overrides. [Resharper - EditorConfig](https://www.youtube.com/watch?v=wGa0W6Te00s&t=0s)

A similar feature for analyzers would be really useful

**Comment by jmarolf** [comment]
@taori editofconfig support was added to Visual Studio 2017.  R# made sure that they respected them, but you can specify code and naming styles in editorconfig without R#.  Today you can use a ruleset file to configure what severity analyzers are set at across your team. Roslyn does that [here](https://github.com/dotnet/roslyn/blob/master/build/Rulesets) though our setup is admittedly more complex that most people would care to implement.  

The plan for the next release is to have editorconfig be the place where you can do analyzer configuration. @kuhlenh has been thinking about this and other features.

**Comment by taori** [comment]
@jmarolf Yeah, i thought the first time i heared about editorconfig was in some connect video i've watched. I am very glad to hear that. Looks like there will only be feature layering to be done in order for analyzer rulesets to be set up in an intuitive way. At least i was not aware that they existed until now.

In that case i guess this issue can be closed, since it sounds like this feature may be in the next release. It'll sure be a useful addition to other people as well.

Thanks for your time. @kuhlenh nice feature idea. I sure hope this feature will happen 👍

**Comment by sharwell** [comment]
@taori For a quick audit, you could create a search for all files in a project which contain your analyzer ID. If anyone tried to use `#pragma warning disable` or `[SuppressMessage]`, it will show up in the search query.

**Comment by sharwell** [comment]
@taori You can remove the UI related to configuring analyzer severity by specifying [`WellKnownDiagnosticTags.NotConfigurable`](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Compilers/Core/Portable/Diagnostic/WellKnownDiagnosticTags.cs#L37) in the descriptor. Normally this is used for "helper" hidden diagnostics [like this](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/000b45d99e2a6973db9e5fb9717822dca1404499/StyleCop.Analyzers/StyleCop.Analyzers/MaintainabilityRules/SA1119StatementMustNotUseUnnecessaryParenthesis.cs#L65-L66), but it doesn't seem to be limited to that use.

**Comment by taori** [comment]
Thanks for letting me know about this! I will keep in mind the suggestion not to use it in a manner where a user may want to be able to configure it.
