### ISSUE TITLE
EnvDTE.CodeFunction.FunctionKind causes COMException for Sub New() in VB.NET instead of returning vsCMFunction.vsCMFunctionConstructor

### ISSUE THREAD

**Issue by carlos-j-quintero** [dotnet/roslyn#1843]
See MS Connect bug:

https://connect.microsoft.com/VisualStudio/feedback/details/1232304/envdte-codefunction-functionkind-causes-comexception-for-sub-new-in-vb-net-instead-of-returning-vscmfunction-vscmfunctionconstructor

I didn't report this before because there were another bugs #149 and #150 that were breaking my tests earlier.

**Comment by Pilchie** [comment]
Let's see if this is simple enough to pull into preview.

**Comment by basoundr** [comment]
Ported from TFS WorkItem: **1153305**

------------------------------



**Repro Steps:**

When you use the EnvDTE.ProjectItem.FileCodeModel to get the function kind of a method, EnvDTE.CodeFunction.FunctionKind doesn&#39;t return vsCMFunction.vsCMFunctionConstructor for a VB.NET method &quot;Public Sub New()&quot;. Instead, it causes COMException.
  


  

Steps to reproduce the problem:
  


  

1) Create a VB.NET package with a menu command such as the attached .zip file, which uses this code:
  


  

   Protected Overrides Sub Initialize()
  

      MyBase.Initialize()
  


  

      &#39; Add our command handlers for menu (commands must exist in the .vsct file)
  

      Dim mcs As OleMenuCommandService = TryCast(GetService(GetType(IMenuCommandService)), OleMenuCommandService)
  

      If Not mcs Is Nothing Then
  

         &#39; Create the command for the menu item.
  

         Dim menuCommandID As New CommandID(GuidList.guidVSPackage1CmdSet, CInt(PkgCmdIDList.cmdidMyCommand))
  

         Dim menuItem As New MenuCommand(New EventHandler(AddressOf MenuItemCallback), menuCommandID)
  

         mcs.AddCommand(menuItem)
  

      End If
  

   End Sub
  


  

   Private Sub MenuItemCallback(ByVal sender As Object, ByVal e As EventArgs)
  


  

      Dim dte As EnvDTE.DTE
  


  


  

      dte = CType(MyBase.GetService(GetType(EnvDTE.DTE)), EnvDTE.DTE)
  


  

      ShowCodeElements(dte.ActiveDocument.ProjectItem.FileCodeModel.CodeElements)
  


  

   End Sub
  


  

   Sub ShowCodeElements(codeElements As EnvDTE.CodeElements)
  


  

      Dim codeClass As EnvDTE.CodeClass
  

      Dim codeFunction As EnvDTE.CodeFunction
  

      Dim functionKind As EnvDTE.vsCMFunction
  


  

      For Each codeElement As EnvDTE.CodeElement In codeElements
  


  

         Select Case codeElement.Kind
  


  

            Case EnvDTE.vsCMElement.vsCMElementClass
  


  

               codeClass = CType(codeElement, EnvDTE.CodeClass)
  

               ShowCodeElements(codeClass.Members)
  


  

            Case EnvDTE.vsCMElement.vsCMElementFunction
  


  

               codeFunction = CType(codeElement, EnvDTE.CodeFunction)
  


  

               Try
  


  

                  functionKind = codeFunction.FunctionKind
  


  

                  System.Windows.Forms.MessageBox.Show(functionKind.ToString())
  


  

               Catch ex As Exception
  

                  System.Windows.Forms.MessageBox.Show(ex.ToString())
  

               End Try
  


  

         End Select
  


  

      Next
  


  

   End Sub
  


  

2) Run the package and in the second VS instance, create a VB.NET Class Library with this code in Class1.vb:
  


  

Public Class C1
  


  

   Public Sub New()
  


  

   End Sub
  


  

   Public Sub MethodA()
  

   End Sub
  


  

End Class
  


  

3) Click the Tools &gt; My Command Name menu.
  


  

The expected result is vsCMFunction.vsCMFunctionConstructor (like in VS 2013). The actual result is COMException Catastrophic failure.

------------------------------




**Revisions:**



1) Created By Microsoft Connect (4/7/2015 1:31:26 PM)

------------------------</br>
Customer Information</br>
------------------------</br>
User ID: 3130757</br>
Handle: Carlos J. Quintero</br>
</br>
---------------------------</br>
Connect Site Information</br>
---------------------------</br>
Site Name: Visual Studio and .NET Framework</br>
Site ID: 210</br>
Feedback ID: 1232304</br>
Feedback Form: 6111</br>
</br>
----------------------</br>
Problem Description</br>
-----------------------</br>
When you use the EnvDTE.ProjectItem.FileCodeModel to get the function kind of a method, EnvDTE.CodeFunction.FunctionKind doesn't return vsCMFunction.vsCMFunctionConstructor for a VB.NET method &quot;Public Sub New()&quot;. Instead, it causes COMException.

Steps to reproduce the problem:

1) Create a VB.NET package with a menu command such as the attached .zip file, which uses this code:

   Protected Overrides Sub Initialize()
      MyBase.Initialize()

      ' Add our command handlers for menu (commands must exist in the .vsct file)
      Dim mcs As OleMenuCommandService = TryCast(GetService(GetType(IMenuCommandService)), OleMenuCommandService)
      If Not mcs Is Nothing Then
         ' Create the command for the menu item.
         Dim menuCommandID As New CommandID(GuidList.guidVSPackage1CmdSet, CInt(PkgCmdIDList.cmdidMyCommand))
         Dim menuItem As New MenuCommand(New EventHandler(AddressOf MenuItemCallback), menuCommandID)
         mcs.AddCommand(menuItem)
      End If
   End Sub

   Private Sub MenuItemCallback(ByVal sender As Object, ByVal e As EventArgs)

      Dim dte As EnvDTE.DTE


      dte = CType(MyBase.GetService(GetType(EnvDTE.DTE)), EnvDTE.DTE)

      ShowCodeElements(dte.ActiveDocument.ProjectItem.FileCodeModel.CodeElements)

   End Sub

   Sub ShowCodeElements(codeElements As EnvDTE.CodeElements)

      Dim codeClass As EnvDTE.CodeClass
      Dim codeFunction As EnvDTE.CodeFunction
      Dim functionKind As EnvDTE.vsCMFunction

      For Each codeElement As EnvDTE.CodeElement In codeElements

         Select Case codeElement.Kind

            Case EnvDTE.vsCMElement.vsCMElementClass

               codeClass = CType(codeElement, EnvDTE.CodeClass)
               ShowCodeElements(codeClass.Members)

            Case EnvDTE.vsCMElement.vsCMElementFunction

               codeFunction = CType(codeElement, EnvDTE.CodeFunction)

               Try

                  functionKind = codeFunction.FunctionKind

                  System.Windows.Forms.MessageBox.Show(functionKind.ToString())

               Catch ex As Exception
                  System.Windows.Forms.MessageBox.Show(ex.ToString())
               End Try

         End Select

      Next

   End Sub

2) Run the package and in the second VS instance, create a VB.NET Class Library with this code in Class1.vb:

Public Class C1

   Public Sub New()

   End Sub

   Public Sub MethodA()
   End Sub

End Class

3) Click the Tools &gt; My Command Name menu.

The expected result is vsCMFunction.vsCMFunctionConstructor (like in VS 2013). The actual result is COMException Catastrophic failure.

------------------------------

2) Edited By Macy Qu (Shang Hai Wei Chuang Ruan Jian) (4/7/2015 9:54:12 PM)

Repro on Win8.1 with VS2015 Pre-RC CTP

------------------------------

3) Edited By Kevin Pilch-Bisson (4/8/2015 9:36:15 AM)

Please copy the info from this to the GitHub bug and then resolve this in favor of that one.

------------------------------

**Comment by basoundr** [comment]
Reopening to track for preview

**Comment by Pilchie** [comment]
Closing, as this was merged into preview last night.
