### ISSUE TITLE
Extract method offers to extract out a "return null"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#18449]
Given that I cannot repro this on any other return null block (including the one it originally showed), I suspect the following isn't expected?

![image](https://cloud.githubusercontent.com/assets/1103906/24687791/1578cafa-19ff-11e7-9d4d-f9504874e284.png)

**Comment by AdamSpeight2008** [comment]
It is perfectly valid extraction, just not a very sane one.

**Comment by Pilchie** [comment]
@davkean - what was your selection in this case?

I would expect extract method to be available in that statement.  It's true that it might not be immediately useful, but it may also be the case that you want to extract it because you're about to change it to do something complicated.
