### ISSUE TITLE
Issue when compilig Visual Basic Project With Microsoft.CodeAnalysis.Emit

### ISSUE THREAD

**Issue by ranuka2** [dotnet/roslyn#18458]
**Version Used**: 1.3.1

Please help to resolve this,

http://stackoverflow.com/questions/43227185/compiler-issue-in-visual-basic-project-with-microsoft-codeanalysis-emit

Thanks.

**Comment by jcouv** [comment]
I see that @svick [already answered ](http://stackoverflow.com/a/43237319/172315) on stackoverflow.
Closing this question.
