### ISSUE TITLE
VSSDK.BuildTools dep version breaks sln

### ISSUE THREAD

**Issue by Nassiel** [dotnet/roslyn#18460]
**Version Used**: Latest Master f937819

**Steps to Reproduce**:

1. Download latest version from scratch
2. Uninstall/remove NuGet package Microsoft.Net.Compilers 2.0.1
3. Uninstall/remove NuGet package Microsoft.VSSDK.BuildTools 15.0.26124-RC3
3. Try to open de Roslyn project with vs15

**Expected Behavior**: Everything loads fine

**Actual Behavior**: 90% of the projects breaks and the solution it's unable to self-recover. Offering you to install the visual studio 2015 update 1 in a loop. While for example I already have the update 3.

I solved the behavior by installing the latest NuGet build for both package from other project*. After change on the file to the 15.0.26201 and download the package from other project* everything get solved.

I think it breaks because the version of the VSSDK 15.0.26124-RC3 it's not available to download (by default, it's a pre release) and in the Dependencies.props it's the desired version. 

How can I upload my branch with that change to this project and then ask to merge it?
Thanks you.

*You need to download from other functional project because while the solution it's broken, the NuGet it's unable to find the "default project".

**Comment by Pilchie** [comment]
Why do you expect things to work after uninstalling the packages in 2 and 3?  Also, how did you remove it?

The dialog is a known issue because the projects fail to load.

I expect that the packages you couldn't find come from a different NuGet feed, which you can find in our https://github.com/dotnet/roslyn/blob/master/NuGet.Config

**Comment by Nassiel** [comment]
Aha, well, obviously I told you how to reproduce the steps means how to break the solution to the same status than mine was. The "remove option" is going to the appdata/.nuget folder and remove the version of those packages.

The situation for me was completely different, I updated the project from a really far way commit and I found that the restore command found errors from the nuget package manager, visual studio solution also founds problems to restore the packages and the nuget console was also unable to install or check anything.

But your solution doesn't work too. The problem I see that is not with downloading an specific version, is while download any package. So for the moment the only solution I found is open another project, manually download the missing packages to fill the appdata/.nuget folder and then re-open the Roslyn project.

**Comment by Pilchie** [comment]
What were the restore errors?

**Comment by jasonmalinowski** [comment]
@Nassiel What were the restore errors you saw?

**Comment by jasonmalinowski** [comment]
@Nassiel We're happy to investigate the restore errors you saw, so feel free to share them. Until then I'm going to close this bug as there's not much we can do until then, but feel free to reply and we'll reactivate it.
