### ISSUE TITLE
Additional .editorconfig Settings

### ISSUE THREAD

**Issue by Rabadash8820** [dotnet/roslyn#18466]
I had some ideas for additional .editorconfig settings for .NET languages.  If there is a preferred site/forum for proposing this type of thing, then I will happily take this discussion over there.  Here are the ideas:

1. **dotnet_style_properties_over_fields**:  would prefer public properties over public fields.  For example,  `public int Value { get; set; }` would be preferred to `public int Value;`.  According to [this article](https://blog.codinghorror.com/properties-vs-public-variables/), this seems to be a coding style with valid pros and cons on both sides.

2. **csharp_style_auto_implemented_properties**:  would prefer auto-implemented properties to properties with a superfluous backing field.  This would help trim out some boilerplate code.  For example:
```
// Prefer
public int Property { get; set; }
// Over
private int _property;
public int Property {
    get { return _property; }
    set { _property = value; }
}
```

3. **csharp_style_custom_event_accessors**: would prefer custom add/remove accessors for events.  This would be useful for environments like Unity scripting, where custom accessors offer some performance gains and should be preferred.  For example:
```
// Prefer
private EventHandler _invoker;
public event EventHandler SomethingHappened {
    add { _invoker += value; }
    remove { _invoker -= value; }
}
// Over
public event EventHandler SomethingHappened;
```

**Comment by Pilchie** [comment]
For 1, I don't think we would ever do it.  The article you mention was written before the convenience of auto-props existed.  At this point I can see a good reason to prefer public fields.

For 2, We have an analyzer and fix that suggests simplifying to an auto-prop if possible, but it (currently) only runs if Tools\Options\Text Editor\C#\Advanced\Enable Full solution analysis is enabled.  There is currently no way to disable this analyzer, but https://github.com/dotnet/roslyn/pull/17857 adds one.  Also, https://github.com/dotnet/roslyn/pull/18362 provides a specific option about how they should be generated.

For 3, I agree this is something that could be done - adding it to our backlog.

**Comment by Rabadash8820** [comment]
@Pilchie  I didn't know about that "Enable full solution analysis" option, I will definitely need to read up on that.  Regarding 1, did you mean that at this point you can _not_ see a good reason to prefer public fields?  If that's the case, then wouldn't an .editorconfig setting for preferring auto-props be desirable?

**Comment by Pilchie** [comment]
@Rabadash8820 I did mean that (and edited inline to avoid future confusion).

You're right though that we could add an editorconfig setting and diagnostic to push people to properties when they have public fields.  I would expect that to come from the roslyn-analyzers project once we get it backed by editorconfig and more integrated into product.  See [`NonConstantFieldsShouldNotBeVisible`](https://github.com/dotnet/roslyn-analyzers/blob/569bd373a4831d3035597197e02980b57602a7f2/src/Microsoft.ApiDesignGuidelines.Analyzers/Core/NonConstantFieldsShouldNotBeVisible.cs#L15) for an existing implementation here.

**Comment by Pilchie** [comment]
@jinujoseph - FYI, another diagnostic that already exists in roslyn-analyzers that we should probably just have on by default as a suggestion in VS...

**Comment by Rabadash8820** [comment]
Cool, I appreciate your considering these suggestions!

**Comment by tamlin-mike** [comment]
@Pilchie " At this point I can not see a good reason to prefer public fields.": I can see value in this. Imagine a vec3f { float x,y,z; }. Using properties for these would make something already slow even worse. If you have a directory "LowLevelMath" in a folder in a project, I can definitely see value in being able to prefer direct field access over properties _for that directory_ (and subdirs).

**Comment by Rabadash8820** [comment]
@tamlin-mike  Good point; gaming and multi-media APIs like Unity3D and SFML are riddled with public float fields.  This reinforces the potential benefit of a `dotnet_style_properties_over_fields` .editorconfig setting, because again, either convention might be appropriate in a given environment.  Don't let the "properties over fields" order throw you; the setting could just as easily be called `dotnet_style_fields_over_properties`.  The point is, I think there should be an .editorconfig setting that allows devs to prefer one convention over the other.

**Comment by Pilchie** [comment]
@tamlin-mike What JIT doesn't inline simple property accessors anyway?

**Comment by tamlin-mike** [comment]
@Pilchie Really? Instead of addressing the issue at hand, namely _source code_, you try to make this a discussion about how a JIT may or may not optimize (while consuming more CPU) unwanted IL (which by its very definition creates bloat)?

I'm sorry, I won't bite. I just wanted to make you aware you're busted, and since it's bad form to feed the trolls, I end this discussion here.

**Comment by CyrusNajmabadi** [comment]
Clsoing out given lack of customer feedback warranting these requests.
