### ISSUE TITLE
Analyzer packages appear to be missing developmentDependency=true

### ISSUE THREAD

**Issue by flcdrg** [dotnet/roslyn#18463]
**Steps to Reproduce**:

1. Create .NET 4.5 Class Library project
2. Add Microsoft.CodeAnalysis.CSharp 2.0.0 NuGet package to project

**Expected Behavior**:

Analyzer package should be added

**Actual Behavior**:

Errors displayed:

Package Microsoft.CodeAnalysis.CSharp.Workspaces 2.0.0 is not compatible with net45 (.NETFramework,Version=v4.5). Package Microsoft.CodeAnalysis.CSharp.Workspaces 2.0.0 supports: netstandard1.3 (.NETStandard,Version=v1.3)
Package Microsoft.CodeAnalysis.Workspaces.Common 2.0.0 is not compatible with net45 (.NETFramework,Version=v4.5). Package Microsoft.CodeAnalysis.Workspaces.Common 2.0.0 supports:
  - net46 (.NETFramework,Version=v4.6)
  - netstandard1.3 (.NETStandard,Version=v1.3)

Shouldn't analyzer packages be marked with developmentDependency=true so it shouldn't matter what the target framework of the project is, as the analyzer is used by Roslyn, not the project?

**Comment by jmarolf** [comment]
@flcdrg [Microsoft.CodeAnalysis.CSharp](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/) is a nuget package that contains libraries that only run on .NET 4.6 or higher.  It does not contain any analyzers.  Does the same thing happen when trying to add [Microsoft.CodeAnalysis.Analyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Analyzers) which does have analyzers?

**Comment by flcdrg** [comment]
Ok.. I see why I'm confused. I was seeing 'CodeAnalysis' and assuming they were all analysers (probably a hang over from using FxCop) - but actually now I understand that those are all Roslyn things, and it's really just the .Analyzers packages (as you say) that are analyzers.
