### ISSUE TITLE
Improperly formatted/tabbed XML Doc Comment is moved on Caret Position Changed in VB

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#18473]
**Version Used**: 15.0.0.26228.9

**Steps to Reproduce**:

1. Using following code

```VB
Module Module1

    '''
    '
    ''' 
    Sub Main()
        Dim x As Integer
        x = 4


    End Sub

End Module
```
2. Highlight XML Doc Comment
3. Shift+Tab
4. Move caret
5. Observe that XML Doc Comment is repositioned.

**Expected Behavior**: XML Doc Comment is not moved by changes in caret position.

![image](https://i.gyazo.com/b35431ff586df8b20a956d20481ad437.gif)

I don't know VB well enough to be familiar with the intended behavior, but I believe it's only supposed to change on edits.

**Comment by Pilchie** [comment]
But Shift+Tab *is* an edit :)
