### ISSUE TITLE
Getting absolute path to CompilationOption.CryptoKeyFile

### ISSUE THREAD

**Issue by vedun-z** [dotnet/roslyn#18470]
I have a `Project` which `CompilationOption.CryptoKeyFile` is a relative path. I want to get access to `CryptoKeyFile`, so I need an absolute path to `CryptoKeyFile`. As far as I understand `CompilationOption.StrongNameProvider` should resolve relative paths to key files, however It does not have public API. I suggest to add a way to get an absolute path of `CryptoKeyFile` without using internal Roslyn API.

**Comment by gafter** [comment]
The compiler has to resolve many different paths (e.g. source files) but it does not provide APIs to get those in absolute form either. It would seem odd to have an API for just this one. Unless there is a widespread need demonstrated for this, I don't see it happening.
