### ISSUE TITLE
Strange behaviour with Dictionary and List initializers in C# 6

### ISSUE THREAD

**Issue by ksmigiel** [dotnet/roslyn#18475]
**Version Used**: 
Roslyn 2.0.0-rc2 (C# 6)

**Steps to Reproduce**:

Run below code
``` cs
var dictionary = new Dictionary<int, List<int>>
{
	[0] = new List<int>{ 1 },
	[0] = { 2 }
};
		
Console.WriteLine(dictionary[0].Count);
```

**Expected Behavior**:
Compiler or static code analysis should raise an error, since it looks like not supported syntax.

**Actual Behavior**:
Dictionary will contain List with two elements {1, 2}

What's more case below is also compiled without problems, but during execution `KeyNotFoundException` exception will be thrown:
``` cs
var dictionary = new Dictionary<int, List<int>>
{
	[0] = { 1 }
};
```

I found it by mistake and then by analyzing generated *IL code*

**Comment by jaredpar** [comment]
Thanks for taking the time to report this issue. This is fairly similar to #19739 and you may want to read that discussion.

But essentially what is happening here is you're mixing member and collection initializers. The behavior there is covered by this section of the spec:

> A member initializer that specifies a collection initializer after the equals sign is an initialization of an embedded collection. Instead of assigning a new collection to the target field, property or indexer, the elements given in the initializer are added to the collection referenced by the target. The target must be of a collection type that satisfies the requirements specified in §7.6.11.3.
