### ISSUE TITLE
Arrows don't navigate Edit.Find box as expected

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#18492]
## Repro
1. Press Ctrl-F (for Edit.Find)
2. Type something in the search box
![image](https://cloud.githubusercontent.com/assets/12466233/24738377/2226ae7a-1a4a-11e7-8fa5-b5fbb2776a85.png)
3. Press tab once, then use arrow keys (right then down) to go to "Find Next", "Find Previous", "Find All". This works as expected.
![image](https://cloud.githubusercontent.com/assets/12466233/24738405/6239d7c6-1a4a-11e7-85ed-5d1a2c88ae47.png)
4. set the focus back in the search box
5. press tab 6 times, bringing the focus on "Entire Solution"
6. Try to use arrow keys to expand the choices, but the dropdown doesn't open as expected

## Expected
![image](https://cloud.githubusercontent.com/assets/12466233/24738436/aa065c50-1a4a-11e7-84e1-3dab51438329.png)

## Actual
![image](https://cloud.githubusercontent.com/assets/12466233/24738448/b726131c-1a4a-11e7-8a68-88aa94e505fb.png)

**Comment by Pilchie** [comment]
The VS Platform editor team owns find. Please file on VSTS or through send feedback.

**Comment by jcouv** [comment]
Filed https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/405056
