### ISSUE TITLE
Merge bot keeps pushing empty branches to origin

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#18493]
I'm constantly deleting merge branches on project system that have no changes. I speculate based on the naming of them (in that they have consecutive dates) that the merge bot is pushing branches to origin even when they have no changes. This might be okay when it used to have a fork, but given it now pushes directly to the repo - it would be great if it didn't do that as these become visible to visitors of the main repo.

**Comment by davkean** [comment]
@jasonmalinowski What's the trick to get this on a infrastructure backlog?

**Comment by jasonmalinowski** [comment]
@davkean: there's "Infrastructure" projects you can add if you click to the right.
