### ISSUE TITLE
Window chrome ignoring mouse clicks when using TransparencyKey

### ISSUE THREAD

**Issue by Nickesm** [dotnet/roslyn#185]
Read this thread: http://stackoverflow.com/questions/20596163/bug-using-transparentkey-and-resizing-form

And perform the steps to get this bug.

**Comment by svick** [comment]
How is this a Roslyn (i.e. the compiler) bug?

**Comment by Nickesm** [comment]
Wrong place ¬¬

**Comment by Nickesm** [comment]
Wrong place ¬¬
