### ISSUE TITLE
IOperation API entries should stay in PublicAPI.Unshipped.txt

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#18506]
https://github.com/dotnet/roslyn/pull/18434

Seems like this PR incorrectly moved unshipped IOperation APIs to PublicAPI.Shipped.txt. 

Anything that touches the IOperation API surface should be unshipped:
  1. OperationKind
  2. IOperation API surface in MS.CA.Semantics namespace (which includes the IOperation interfaces, OperationWalker, OperationVisitor, etc.) 
  3. SemanticModel.GetOperation API.
  4. RegisterOperationAction
  5. OperationAnalysisContext

**Comment by sharwell** [comment]
💭 It's my understanding that PublicAPI.Shipped.txt is intended to reflect the APIs which were accessible in a release which was declared stable. It's primary purpose is to increase awareness regarding changes to what a consumer could have been accessing without the use of reflection. By this approach, the IOperation APIs should be included in PublicAPI.Shipped.txt, even if the API review process treats them in a relaxed manner when considering changes to the API surface area.

**Comment by mavasani** [comment]
I am fine with either approach: keeping only shipped, supported APIs in shipped.txt versus keeping only publically accessible APIs in a stable release. However, my understanding is that these APIs were publically accessible even in VS2015 Update3 (1.3.0 release) and the design time explicitly requested us to keep them in the unshipped file to avoid continuous churn of shipped.txt.

Tagging the relevant folks to decide on the preferred approach: @Pilchie @Srivatsn @jaredpar @jinujoseph @ManishJayaswal @CyrusNajmabadi

**Comment by jaredpar** [comment]
> However, my understanding is that these APIs were publically accessible even in VS2015 Update3 

Yes.  They are public but not supported.  There isn't really a good way to classify them because there really isn't any other API like it.  

> the design time explicitly requested us to keep them in the unshipped file to avoid continuous churn of shipped.txt.

Correct.  The churn of IOperation in shipped was making it hard to differentiate actual breaking changes from normal IOperation churn.  IIRC caused us to miss one compat issue hence we added this rule.

**Comment by sharwell** [comment]
One interesting solution would be incorporation of a "Preliminary" status which the Public API analyzer is aware of. See the **Preliminary Features** section at the bottom of the following page for one case where I used this designation:
http://tunnelvisionlabs.github.io/dotnet-threading/docs-latest/html/e02b9881-f06b-4420-aace-71b176d635db.htm

**Comment by Pilchie** [comment]
Such a concept could also help with F#/TypeScript internal dependencies.
