### ISSUE TITLE
Missing FieldReferenceExpression operations in collection initializers

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#18509]
Ported from https://github.com/dotnet/roslyn-analyzers/issues/933

=================================

#### Repro steps
1. Open Analyzers.sln
2. Change Dependencies\CodeAnalysis\project.json to include: `"Microsoft.CodeAnalysis.FxCopAnalyzers": "1.2.0-beta1"`
3. Restore NuGet packages for solution
4. Open BasicInvokeTheCorrectPropertyToEnsureCorrectUseSiteDiagnostics.vb

![falsereportca1823](https://cloud.githubusercontent.com/assets/10605811/14577461/39de7054-0329-11e6-8a9c-6ae884e644e3.png)

Seems like an IOperation bug (analyzer is just looking for all FieldReferenceExpressions), but someone should confirm before porting it to Roslyn repo.

=============

It's either an straightforward IOperation bug or a more subtle issue. If the compiler is replacing uses of a named constant with its value in the bound trees, then we will have to get clever to retain the knowledge that the constant came from a symbol.
This is almost certainly not fixed.

**Comment by jinujoseph** [comment]
Tracked at #18781
