### ISSUE TITLE
Audit usage of CType() and DirectCast() to TypeBlockSyntax

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#1850]
As discovered in item #1834, the parent of a VB constructor block isn't necessarily a TypeBlockSyntax.  In searching the code base for explicit casts to this type, I found 6 instances in VisualBasicEditAndContinueAnalyzer.vb where a node's parent is assumed to be a TypeBlockSyntax, but that's not necessarily the case and the incorrect cast could crash VS.

### TODO
Audit the 6 instances I found to determine if `CType(..., TypeBlockSyntax)` or `DirectCast(..., TypeBlockSyntax)` should be prefaced with a type check or replaced with TryCast().

Note, that while EnC might not support scenarios where a node's parent isn't a TypeBlockSyntax, it should be considered a possibility that the user could be in some broken intermediate state when the VB EnC analyzer is running.

### To review:

In VisualBasicEditAndContinueAnalyzer.vb:

1.  Line 2328 (`Dim typeDeclaration = DirectCast(oldNode.Parent.Parent, TypeBlockSyntax)` in ClassifyUpdate(VariableDeclaratorSyntax,VariableDeclaratorSyntax))
2.  Line 2366 (`Dim typeDeclaration = DirectCast(oldNode.Parent, TypeBlockSyntax)` in ClassifyUpdate(PropertyStatementSyntax, PropertyStatementSyntax))
3.  Line 2437 (`containingType:=DirectCast(newNode.Parent, TypeBlockSyntax)` in ClassifyUpdate(MethodBlockSyntax, MethodBlockSyntax))
4.  Line 2524 (`containingType:=DirectCast(newNode.Parent, TypeBlockSyntax)` in ClassifyUpdate(OperatorBlockSyntax, OperatorBlockSyntax))
5.  Line 2545 (`containingType:=DirectCast(newNode.Parent.Parent, TypeBlockSyntax)` in ClassifyUpdate(AccessorBlockSyntax, AccessorBlockSyntax))
6.  Line 2575 (`containingType:=DirectCast(newNode.Parent, TypeBlockSyntax)` in ClassifyUpdate(ConstructorBlockSyntax, ConstructorBlockSyntax))

**Comment by brettfo** [comment]
FYI @tmat

**Comment by wschae** [comment]
We don't analyze doc with broken trees. I.e., we return when there is any syntax errors before EnC analysis. Therefore, I don't think we need any TryCast.

@tmat What do you think?

**Comment by tmat** [comment]
Correct. We bail is there are semantic errors.

**Comment by wschae** [comment]
@brettfo Thanks for pointing out this issue. We don't think we need any change here at this point, though.
