### ISSUE TITLE
VisualStudioSetup and /rootsuffix RoslynDev crash in current master branch

### ISSUE THREAD

**Issue by lachbaer** [dotnet/roslyn#18512]
I tried it several times to clean, restore and recompile, always the same problem as stated in the title.
Until now my previous compilations all worked.
I'm trying C# features.

**Comment by Pilchie** [comment]
Can you post the callstack of the crash? Also, can you confirm that you're on VS2017, and that you have VisualStudioSetup.*Next* as the startup project?

**Comment by lachbaer** [comment]
@Pilchie 
I am on VS2017, my startup project is "VisualStudioSetup" - without .Next - and compiling according to the Wiki.

**Comment by lachbaer** [comment]
@Pilchie 
VisualStudioSetup*.Next* is working 😄 
What's the point of keeping the ordinary "VisualStudioSetup" still in master branch then and mentioning it in the Wiki?

**Comment by Pilchie** [comment]
@lachbaer We keep it around because we plan to re-purpose it for Dev16 at some point.

I've updated the wiki though - sorry for that!

**Comment by lachbaer** [comment]
@Pilchie Thank you very much for the immediate help! Much appreciated :-)

I keep this issue open for a while in case others currently have the same problem.

**Comment by lachbaer** [comment]
@Pilchie 
The Wiki link to "Building testing and debugging" on Windows is broken now.

**Comment by Pilchie** [comment]
Thanks - I've fixed up some Wiki issues.  Looks like GitHub's change of Markdown parser broke some stuff, and I've put out https://github.com/dotnet/roslyn/pull/18529 to update the docs about contributing.

**Comment by Pilchie** [comment]
Fixed in #18529.
