### ISSUE TITLE
C# Specifications are not up to date

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#18515]
We are shipping an out-of-date specification for C# with Visual Studio. We should stop doing that and link to the online specifications.

This is also [tracked internally at 405168](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems?id=405168&_a=edit). and [428131](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems?id=428131&_a=edit).

**Comment by miloush** [comment]
How about shipping up-to-date specification, or making it part of some workload/component?
I value having an offline reference.

**Comment by gafter** [comment]
We do not yet have an up-to-date specification.

**Comment by miloush** [comment]
So what do you propose linking to?

**Comment by gafter** [comment]
@miloush I propose linking to the site where the specs are being developed (and where feature specs will be placed).

**Comment by BillWagner** [comment]
You could also link to the version we publish on docs.microsoft.com: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/  It's directly imported from https://github.com/dotnet/csharplang/blob/master/spec/README.md and child documents. We are currently publishing the master branch.

**Comment by gafter** [comment]
Yes, [you](https://github.com/dotnet/docs/issues/3381) could do it that way too.

**Comment by gafter** [comment]
This has been resolved. Recent VS releases do not include a copy of the (out-of-date) C# language specification.
