### ISSUE TITLE
Inconsistent CS0019 behaviour with nullable enum types

### ISSUE THREAD

**Issue by NSentinel** [dotnet/roslyn#18527]
**Version Used**: 
Microsoft Visual Studio Enterprise 2017
Version 15.1 (26403.0) Release
VisualStudio.15.Release/15.1.0+26403.0
Microsoft .NET Framework
Version 4.7.02046

**Code to Reproduce**:

```csharp
enum E : byte
{
      A = 1
}
```

**1. Compilable version**:

```csharp
static void Main(string[] args)
{
      E? e = E.A;
      byte b = (byte) (e ?? 0);
}
```

**2. CS0019 version** (`0` changed to `1`):

```csharp
static void Main(string[] args)
{
      E? e = E.A;
      byte b = (byte) (e ?? 1);
}
```

**3. "Fixed" CS0019 version**:

```csharp
static void Main(string[] args)
{
      E? e = E.A;
      byte b = (byte) (e ?? (E)1); // or (e ?? E.A) but not (e ?? (byte)1)
}
```

**4. Simplified version** (somewhat optimized code transformation for future compiler improvement):

```csharp
static void Main(string[] args)
{
      E? e = E.A;
      byte b = (byte) e.GetValueOrDefault((E) 1); // or e.GetValueOrDefault(E.A)
}
```

---

As far as I can see here is the following (in square brackets reference to code example):

- [1] compiler output code as:

```csharp
    E? e = new E?(E.A);
    byte b = e.HasValue ? ((byte) e.GetValueOrDefault()) : ((byte) 0);
```

- [2] compiler can't "understand" `1` constant in code although it just worked with `0` (probably since `default(E) == 0` ?) with `CS0019` (main reason why I fill this issue as `inconsistent behaviour`)

- [3] compilable variants

- [4] just optional suggestion for future improvements of nullable type handling

Hopefully, fix will be for [2] (make it compilable) and not for [1] (make it `CS0019`).

**Comment by sharwell** [comment]
The literal 0 is implicitly convertible to any enum type, per [the following](https://github.com/dotnet/csharplang/blob/master/spec/conversions.md#implicit-enumeration-conversions) in the C# Language Specification. No such provision is made for other values.

> An implicit enumeration conversion permits the *decimal_integer_literal* `0` to be converted to any *enum_type* and to any *nullable_type* whose underlying type is an *enum_type*. In the latter case the conversion is evaluated by converting to the underlying *enum_type* and wrapping the result (Nullable types).

**Comment by NSentinel** [comment]
@sharwell Thanks for quick but detailed answer, so `won't fix` ?

**Comment by sharwell** [comment]
@NSentinel No problem. 👍
