### ISSUE TITLE
Inconsistent typing of multidimensional arrays in VB.NET

### ISSUE THREAD

**Issue by michalhosala** [dotnet/roslyn#18535]
**Version Used**: VS: 14.0.25123.00 Update 2

**Steps to Reproduce**:
1. Have the following code
```
    Dim a = {"a"}
    Dim o1 = {{"a"}}
    Dim o2 = {a}
```
2. Put cursor over o1 and o2 and observe their types

**Expected Behavior**:
`o1` and `o2` should be of same type

**Actual Behavior**:
`o1` is of type `String(,)` and `o2` is of type `String()()`

My expectations for consistency are driven not only by common sense but also by the fact that `o1` and `o2` are typed the same in similar c# code:
```
    var a = new[] { "a" };
    var o1 = new[] { new[] { "a" } };
    var o2 = new[] { a };
```

**Comment by AdamSpeight2008** [comment]
The type inference is correct, you're put an array in a jagged array. Not into a 2D array.
```vb
Dim a As String() = { "a" }
Dim o1 As String(,) = {{ "a" }}
Dim o2 As String()() = { a }
```

**Comment by michalhosala** [comment]
@AdamSpeight2008 not sure I follow, can't really see the difference comparing against c# code.

**Comment by michalhosala** [comment]
@AdamSpeight2008 so is there actually any way to initialize jagged array as I am doing it for `o1` array in c# code?

**Comment by AdamSpeight2008** [comment]
@michalhosala The follow VB and C# are equivalent.
```vbnet
        Dim D1() As Int32 = {(0), (1)}

        Dim D2(,) As (Int32, Int32) = {
                                        {(0, 0), (0, 1)},
                                        {(1, 0), (1, 1)}
                                      }
        Dim JA As (Int32, Int32)()() = {
                                        ({(0, 0)}),
                                        ({(1, 0), (1, 1)}),
                                        ({(2, 0), (2, 1), (2, 2)})
                                       }
```
```c#
var D1 = new[]  { (0) }};
var D2 = new[,] {  {(0,0), (0,1) },
                   {(1,0), (1,1) } }
var JA = new[]  { new[]  { (0,0)},
                  new[]  { (1,0), (1,1) },
                  new[]  { (2,0), (2,1) , (2,2) }
                };
```

**Comment by michalhosala** [comment]
@AdamSpeight2008 neither your VB.NET nor C# code compiles, compiler is complaining about parentheses., I guess, in case of VB.NET, you intended to write something like:
```
    Dim JA As Integer()() = {
        ({0, 0}),
        ({1, 0, 1, 1}),
        ({2, 0, 2, 1, 2, 2})
    }
```

It works, thanks for pointing me in the right direction, forgot about the parenthesized expressions, closing... To achieve both `o1` and `o2` from original report to be of same type, change the code to:
```
        Dim a = {"a"}
        Dim o1 = {({"a"})}
        Dim o2 = {a}
```

**Comment by AdamSpeight2008** [comment]
@michalhosala Nope, look at the types I used. `Tuple(of Int32, Int32)` , so I am using tuple literals, the value are the positions in the colloctions.
