### ISSUE TITLE
Incorrect syntax mapping for IOperation corresponding to an invalid invocation expression 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#18537]
See comment https://github.com/dotnet/roslyn/pull/17938/files/22a068341adc54abad38fa99ec5688f0da852443#r110458305

It seems more logical for the syntax of the receiver to have just Console instead of Console.WriteLine2

**Comment by jinujoseph** [comment]
Is this fixed @genlu ?

**Comment by genlu** [comment]
Not fixed, as this is not related to deriving arguments.

**Comment by jinujoseph** [comment]
verify and close

**Comment by mavasani** [comment]
We do not generate an `IInvocationOperation` for this case now. The actual operation tree is:

```
IInvalidOperation (OperationKind.Invalid, Type: ?, IsInvalid) (Syntax: 'Console.WriteLine2()')
  Children(1):
      IInvalidOperation (OperationKind.Invalid, Type: ?, IsInvalid) (Syntax: 'Console.WriteLine2')
        Children(1):
            IOperation:  (OperationKind.None, Type: null) (Syntax: 'Console')
```

This seems reasonable (note that the OperationKind.None node is for BoundMethodGroup).
