### ISSUE TITLE
MSBuildWorkspace.OpenProjectAsync().Result is null under load

### ISSUE THREAD

**Issue by NSuriyan** [dotnet/roslyn#18544]
**Version Used**: 
Visual Studio 2015
Microsoft.CodeAnalysis.Workspaces.Desktop.dll 1.0.0.50618
In package Microsoft.CodeAnalysis.Workspaces.Common.1.0.1.nupkg
**Steps to Reproduce**:
I am analyzing over 1000 projects for some pattern of code. I am using MSBuildWorkspace in a standalone analyzer to load these projects using the OpenProjectAsync method.  
The MSBuildWorkspace is static and is shared, while the projects are loaded and analyzed in parallel through multiple tasks.  
Occasionally, OpenProjectAsync().Result is null and there is no other exception thrown.  It seems random and there does not seem to be a pattern for these projects.  I could open the failed project the next time around with no issues.
If I create a separate workspace every time, per project, then all the projects get opened correctly and there is no issue, but it is *significantly* slower.  Creating the workspace is both time and memory intensive, as I find.

Any idea why OpenProjectAsync().Result returns null occasionally?  Can the MSBuildWorkspace instance be shared like how I am doing?

**Expected Behavior**:
Either the project should open or there should be some error thrown.
**Actual Behavior**:
No error thrown and instead the project is null.

**Comment by Pilchie** [comment]
@mattwar didn't you look at this at some point?

@NSuriyan can you hook something up to the `WorkspaceFailed` event and see if something is reported?

**Comment by Pilchie** [comment]
@NSuriyan also - it would be good to try newer packages than those.  In particular, @mattwar added additional logging to `WorkspaceFailed` recently, but you'd need to get the latest packages from our myget source to have those changes.

**Comment by mattwar** [comment]
Loading of projects into MSBuildWorkspace is not thread safe.  Accessing them once loaded, is thread safe though.  It might work as a shared workspace if you control access to loading through a lock or async queue.

**Comment by NSuriyan** [comment]
Thanks. let me try this.
