### ISSUE TITLE
InConversion and OutConversion of VB ByRef argument exposes placeholder nodes as IOperations

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#18548]
When passing a modifiable element as argument for a VB `ByRef` parameter, the `In/OutConversion`  properties of  the `IArgument` operation would expose placeholder nodes as `Operand` (as those properties themselves are of type `IConversionExpression`). 

```vb
Class Program
    Sub M1()
        Dim x = 1.0
        M2(x)
    End Sub

    Sub M2(ByRef a As Integer)
    End Sub
End Class
```

```
IOperation tree for "M2(x)"

IInvocationExpression ( Sub Program.M2(ByRef a As System.Int32)) (OperationKind.InvocationExpression, Type: System.Void) (Syntax: 'M2(x)')
  Instance Receiver: IInstanceReferenceExpression (InstanceReferenceKind.Implicit) (OperationKind.InstanceReferenceExpression, Type: Program) (Syntax: 'M2')
  Arguments(1): IArgument (ArgumentKind.Explicit Matching Parameter: a) (OperationKind.Argument) (Syntax: 'x')
      ILocalReferenceExpression: x (OperationKind.LocalReferenceExpression, Type: System.Double) (Syntax: 'x')
      InConversion: IConversionExpression (ConversionKind.Basic, Implicit) (OperationKind.ConversionExpression, Type: System.Int32) (Syntax: 'x')
          IOperation:  (OperationKind.None) (Syntax: 'x')
      OutConversion: IConversionExpression (ConversionKind.Basic, Implicit) (OperationKind.ConversionExpression, Type: System.Double) (Syntax: 'x')
          IPlaceholderExpression (OperationKind.PlaceholderExpression, Type: System.Int32) (Syntax: 'x')
```

Related: #8905

**Comment by jinujoseph** [comment]
**Design Team Decision**

Instead of specifically saying IArgument points to two ioperations for in and out, it should point to two sort of conversions from in and out, It could just be conversion info sort of thing that contains the kind.A special node by direction in-out conversion in a struct that contains two literal conversion structs on it and we don't say whats the operand is as its explicit.   

From @CyrusNajmabadi 
This will be shared by other ioperations , We will need to design conversions that are reusable across other operations , for example IConversionExpression would likely want to point at that conversion Type.
cc @333fred

**Comment by genlu** [comment]
@CyrusNajmabadi Based on your comment above, seems I should re-purpose the  newly added `CommonConversion` for this?

**Comment by CyrusNajmabadi** [comment]
Yes.

**Comment by CyrusNajmabadi** [comment]
Tagging @333fred where did we land vis-a-vis an interface for conversions.  If @genlu uses CommonConversion for "in/out" it seems like he won't be able to get back to the actual language conversions the user may want.  This seems unfortunate and it seems like we may need extensions here to give you back the specific language conversions if they want them.

**Comment by 333fred** [comment]
I believe we wanted to do a similar thing to what we did for IConversionExpression, where we have the CommonConversion property and extension methods for C# and VB for getting the language-specific Conversion structs.

**Comment by genlu** [comment]
@AlekseyTs made a comment on the usage of `Optional` in the new interface.

```cs
    public interface IArgument : IOperation
    {
        /// <summary>
        /// Kind of argument.
        /// </summary>
        ArgumentKind ArgumentKind { get; }
        /// <summary>
        /// Parameter the argument matches.
        /// </summary>
        IParameterSymbol Parameter { get; }
        /// <summary>
        /// Value supplied for the argument.
        /// </summary>
        IOperation Value { get; }
        /// <summary>
        /// Information of the conversion applied to the argument value passing it into the target method. Applicable only to VB Reference arguments.
        /// </summary>
        Optional<CommonConversion> InConversion { get; }
        /// <summary>
        /// Information of the conversion applied to the argument value after the invocation. Applicable only to VB Reference arguments.
        /// </summary>
        Optional<CommonConversion> OutConversion { get; }
    }
```

**Comment by CyrusNajmabadi** [comment]
Design decision (tentative) - Dependent on https://github.com/dotnet/roslyn/issues/21728

Ideally we could only get IARguments for correct method resolution cases.  In that case,  we feel like we can always give a relevant value for InConversion and OutConversion.  Namely it can either be the actual conversion if there was one, or 'Identitity' to indicate 'no conversion happened'.

**Comment by genlu** [comment]
@CyrusNajmabadi So the proposal here is to make In/OutConversion not `Optional<>` and always provide identity conversion in case there's no actual conversion for both C# and VB?

**Comment by CyrusNajmabadi** [comment]
Yes.
