### ISSUE TITLE
Move line up/down triggers line commit and thus can generate code

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#18541]
1. Type the following code in a new VB file:
```
        If True Then
        End If
        If Blah
```

Make sure you don't have a "Then" after the second If.

2. Do Alt+Up

*Expected:* the lines are interchanged but we don't put a Then there
*Actual:* we spit a Then.

**Comment by jasonmalinowski** [comment]
I've filed this on behalf of https://developercommunity.visualstudio.com/content/problem/38328/editor-vbnet-move-line-up-with-altup-arrow-breaks.html.

**Comment by Pilchie** [comment]
@jasonmalinowski any idea if this has ever worked?

**Comment by jasonmalinowski** [comment]
@Pilchie No idea. I didn't look.

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard about this from anyone.
