### ISSUE TITLE
Invalid code generated when implementing interface through explicitly implemented property

### ISSUE THREAD

**Issue by kcnygaard** [dotnet/roslyn#18556]
**Version Used**: 
VS 2017 Update 1 and master 85ca862c20fd1cb4192f3a42521eeadcba6828cb

**Steps to Reproduce**:

1. Create a new project with the following:
```
interface IA
{
    IB B { get; }
}
interface IB
{
    int M();
}
class AB : IA, IB
{
    IB IA.B => null;
}
```
2. Put caret in `class AB : IA, IB` line and invoke `Implement interface through 'IA.B'`

**Expected Behavior**:
```
public int M()
{
    return ((IA)this).B.M();
}
```

**Actual Behavior**:
Invalid code (CS0120):
```
public int M()
{
    return IA.B.M();
}
```

**Comment by kcnygaard** [comment]
I went ahead and submitted a pull request #18557 for review that fixes this bug and am signing the CLA now.

**Comment by Pilchie** [comment]
@CyrusNajmabadi can you take a look at the PR?

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/18557
