### ISSUE TITLE
Deconstruction assigning to write-only indexer causes compiler crash

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#18554]
**Version Used**: 2.1.0.61520

**Steps to Reproduce**: Compile the code below

using System;

```csharp
class Test
{
    int this[int index]
    {
        set => Console.WriteLine($"{index}={value}");
//        get => throw new Exception("Shouldn't be called");
    }
    
    void BreakCompiler()
    {
        var tuple = (1, 2);
        (this[0], this[1]) = tuple;
    }

    static void Main()
    {
        new Test().BreakCompiler();
    }    
}
```

**Expected Behavior**: Indexer is called twice

**Actual Behavior**: Compiler crashes with code -2146232797

Note that uncommenting the getter for the indexer - even though it's not called anywhere - fixes the breakage.

**Comment by jcouv** [comment]
Fixed by @alrz in #18586.
The fix will ship in Visual Studio 2017 version 15.3.
Thanks @jskeet for reporting the issue.
