### ISSUE TITLE
`WasCompilerGenerated` property on bound node is not a robust way to determine `ArgumentKind` in VB

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#18550]
The implementation in VB bound tree provides a fully populated list of arguments, including arguments with default value and array that is generated by compiler as argument for `ParamArray` parameter for invocation of expanded form. However, we currently don't have definitive information on the bound node that tells us if 

1. it is a default value argument, or 
2. it is an array created by compiler because or it is an array provided explicitly by caller for the normal form of invocation. 

At the moment, we rely on checking `WasCompilerGenerated` property on the argument bound nodes, which might break in many cases. @AlekseyTs proposed a more robust approach, basically to create additional wrapper nodes, and during binding we wrap up argument nodes of default value and paramarray argument generated by compiler.

**Comment by 333fred** [comment]
Tackling this as part of https://github.com/dotnet/roslyn/pull/26781.

For default args, we're storing the information about which params are using a default value in a BitVector in the respective BoundCall/ObjectCreation/Parameter
For param array, ArrayCreationExpression already has `IsParamArrayArgument` as a property.

**Comment by jinujoseph** [comment]
@333fred can you verify and close

**Comment by 333fred** [comment]
This was fixed with #26781
