### ISSUE TITLE
Casting null to call custom ==/!= operators is incorrectly identified as redundant

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#18565]
**Version Used**: VS 2017 RC

![](http://i.imgur.com/QpKxZgv.png)

The cast above is incorrectly identified as redundant; removing the cast would change the behavior by calling `object.ReferenceEquals` instead. This only happens with ==/!= and not other operators like *.

**Comment by CyrusNajmabadi** [comment]
>  removing the cast would change the behavior by calling object.ReferenceEquals

I don't believe this is true.  If I write:

```c#
Console.WriteLine(null == (Polynomial)null);
```

Then this compiles down to:

```
        IL_0008: ldnull
	IL_0009: ldnull
	IL_000a: call bool Polynomial::op_Equality(class Polynomial, class Polynomial)
	IL_000f: call void [mscorlib]System.Console::WriteLine(bool)
```

So each cast is independently redundant.  Note that if you remove either of the casts, then the other becomes necessary.  And also note that if you try to "remove all" it will only remove one of the casts as it can tell that removing both *would* then be a problem.

**Comment by jamesqo** [comment]
@CyrusNajmabadi Nice! I thought the compiler was saying that both casts were redundant, I didn't realize it would update its suggestions when one of them was removed. Just a thought-- perhaps it could darken only one of the casts in such a case, to make it less confusing to the reader? Other than that, I'm closing this issue.

**Comment by CyrusNajmabadi** [comment]
It's an interesting case.  Since you really could remove either of the casts, I think it's honest to show both as redundant within the existing code.  If we didn't fade one, it would somewhat imply that that cast could not be removed (which is not true).  Of course, your point is spot on that this can be construed as meaning that both can be removed safely.

I have no solution I like, so for now I think keeping things as is is acceptable :)

**Comment by miloush** [comment]
Just want to point out that there is a precedence here with casts like `float f = (float)3 / (float)2`.

I would swear this has been discussed before cannot find it.
I personally prefer symmetry here, but I don't have a better solution either.
