### ISSUE TITLE
Conflict is not indicated when renaming a parameter from partial method definition

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#18566]
**Version Used**: Visual Studio 2017 15.0.0+26228.10

**Code to Reproduce**:
```csharp
public partial class Foo
{
    partial void Bar(Foo value)
    {
        Foo foo = null;
    }
}

public partial class Foo
{
    partial void Bar(Foo value); // Rename 'value' to 'foo' from here
}
```
**Actual Behavior**:
Conflict is not indicated in the IDE.`

**Comment by tuespetre** [comment]
@Pilchie can I grab this one?

**Comment by Pilchie** [comment]
Sure thing - I just assigned it to @dpoeschl since only contributors can be assigned, but he might be able to give you some pointers about where to look when he gets back from vacation.
