### ISSUE TITLE
Roslyn EE regression with F# debug type proxies

### ISSUE THREAD

**Issue by saul** [dotnet/roslyn#18581]
**Version Used**: VS 2017

**Steps to Reproduce**:

Code to reproduce:

```f#
let someMap = ["Hi", 15; "There", 10] |> Map.ofList
```

1. Set a breakpoint after this line of code
2. Look at the "Locals" window to inspect `someMap`. Note how there are no members beneath this object, only "Raw View".

This regression is due to [TypeHelpers.cs@192](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/TypeHelpers.cs#L192-L194). An assumption was made by the author of this code that is invalid with F#. In F#, it is impossible to have public members on internal classes. Therefore any debug type proxy that is an internal type does not work with F# and the Roslyn EE. Note that this is a *regression* compared to the behaviour of the native EE (as noted in the comments of TypeHelpers.cs).

**Expected Behavior**:

This is the behaviour with VS 2015 or by enabling the "Legacy C#/VB.NET expression evaluator" in VS 2017:

![image](https://cloud.githubusercontent.com/assets/64654/24877842/a907e6c0-1e28-11e7-8d96-a34610e6b210.png)

**Actual Behavior**:

![image](https://cloud.githubusercontent.com/assets/64654/24877897/d3a7eb28-1e28-11e7-8dfe-d9f0b05f49e8.png)

**Comment by saul** [comment]
For more information, see: https://github.com/Microsoft/visualfsharp/issues/2184#issuecomment-292645097

**Comment by saul** [comment]
Thanks @tmat - am I right in thinking that we should expect this to be public in 15.3 as the milestone for this issue suggests?

**Comment by jinujoseph** [comment]
Thats right @saul , This will be available in 15.3. Thanks for taking care of it.
