### ISSUE TITLE
Quick info constantly flashing/refreshing in recent builds

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#18596]
Build: VisualStudio.15.int.vsuwpt/15.2.0-Preview+26410.1.vsuwpt

Quick Info is constantly flashing like so for errors in my build, not sure if this is Editor or Roslyn:

![quickinfoflashing](https://cloud.githubusercontent.com/assets/1103906/24894823/1d374728-1ed0-11e7-80df-4e53a64ec612.gif)

**Comment by Pilchie** [comment]
@olegtk Looks like an editor issue to me - We don't generally control error tooltips.

**Comment by olegtk** [comment]
nasty. I can repro it on vsuvscore too. Investigating...

**Comment by olegtk** [comment]
looks like Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Presentation.QuickInfoPresenter.QuickInfoPresenterSession.PresentItem keeps calling IQuickInfoSession.Recalculate in a loop.

**Comment by rchande** [comment]
Looks like this was introduced by https://github.com/dotnet/roslyn/commit/3ef5891043f89145b1e1c1a7de8c0e02acd15c6e

**Comment by davkean** [comment]
Hey folks, is this going to be fixed for the 15.3 Preview?

**Comment by rchande** [comment]
@davkean I've been investigating. In the worst case we can revert the change that regressed this.
