### ISSUE TITLE
Test plan for "Infer tuple names" aka "tuple projection initializers" (7.1)

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#18606]
Test plan for "Infer tuple names" aka "tuple projection initializers"
=================

This is a checklist for testing the implementation of https://github.com/dotnet/csharplang/issues/415. I (@gafter) will check items off as I see they are tested.
Items that are checked off but marked with the name of a test have been updated by Julien.

- [ ] We need a specish proposal that clearly describes the decision for key decision points. Once that is done I'll add additional bullets to this test plan.

There should be a positive test for each of the "golden" C# scenarios in https://github.com/dotnet/csharplang/issues/370:
- [x] `(int, int) t = (x, y); // (int x, int y) on the right` (`TupleCreationWithInferredNames`)
- [x] `(int a, int b) t = (x, y); // (int x, int y) on the right` (`TupleCreationWithInferredNames`)
- [x] `var t = (x, y); // (int x, int y)`
- [x] `var t = (x, x); // (int, int)`
- [x] `var t = (n: x, x); // (int n, int x)`
- [x] `var t = (x, 5); // (int x, int)`
- [x] `var t = (x, x, y); // (int, int, int y)`

There should be a positive test for corresponding "golden" VB scenarios:  (`TupleCreationWithInferredNames`, `TupleCreationWithInferredNames2`)
- [x] `Dim t As (Integer, Integer) = (x, y) ' (x As Integer, y As Integer) on the right`
- [x] `Dim t As (a As Integer, b As Integer) = (x, y) ' (x As Integer, y As Integer) on the right`
- [x] `Dim t = (x, y) ' (x As Integer, y As Integer)`
- [x] `Dim t = (x, x) ' (Integer, Integer)`
- [x] `Dim t = (n := x, x) ' (n As Integer, x As Integer)`
- [x] `Dim t = (x, 5) ' (x As Integer, Integer)`
- [x] `Dim t = (x, x, y) ' (Integer, Integer, y As Integer)`

Test language version:
- [x] We should not infer tuple names in C# 7.0
  - [x] or VB 15.0. (`MissingMemberAccessWithVB15`)
- [x] We should infer tuple names in C# 7.1
  - [x] and VB 15.3. (`TupleCreationWithInferredNames`, `TupleCreationWithInferredNames2`)
- [x] We identified a breaking change for this feature. Write a program that displays different behavior depending on language version.
- [x] Add a note to the compiler breaking changes document for the language change's effect on existing programs.
- [x] Ensure the "default" language version is C# 7.0, and the "latest" is C# 7.1. These tests may already exist in `master`. (`LanguageVersion_MapSpecifiedToEffectiveVersion`)
- [x] Similarly ensure "default" and "latest" versions for VB. (`LanguageVersion_MapSpecifiedToEffectiveVersion`)

Tests specific to this feature:
- [ ] Test to ensure correct (per spec) behavior when an inferred name would be of the form
  - [x] `Item1` (both in the correct and incorrect position) (tested on `Item4` and `Rest` in `TupleCreationWithInferredNamesWithCSharp7`)
  - [ ] `Item10` (both in the correct and incorrect position)
  - [ ] `GetHashCode`, `Equals`, `ReferenceEquals`
  - [ ] These same names are case-insensitive in VB.
- [ ] Test to ensure no name inferred for a user-defined operator invocation
- [ ] Test to ensure a name is inferred even if a user-defined conversion is applied after the expression
- [x] Test the interaction of "common type" with inferred names.
- [ ] Test each of the syntactic constructs that cause a name to be inferred:
  - [x] `Identifer` (local, parameter, field, property, event, enumeration constant)
  - [x] `expr.Identifier` including `this.Identifier` and `base.Identifier`
  - [x] `expr?.Identifier`
  - [ ] `value` in a property setter
  - [x] A declaration expression with a simple designator (see below)
  - [ ] `@_` as a plain identifier
  - [ ] `@_` as a designator
  - [ ] Some other VB-specific contexts
- [ ] Test that other syntactic constructs to not cause a name to be inferred:
  - [x] tuple literal
  - [x] `expr.M()` (except in VB)
  - [x] `( Identifier )`
  - [x] `checked ( Identifier )` and `unchecked ( Identifier )`
  - [ ] `default(Type)`
  - [x] A `_` discard expression in deconstruction.
  - [ ] A `_` discard designator in deconstruction

- [ ] Test that inferred names can come from the left-hand-side of a deconstruction
  - [x] For a deconstruction-declaration like `var (x, y) = (1, 2)`
  - [x] For a deconstruction-declaration like `(var x, var y) = (1, 2)`
  - [x] For a deconstruction-declaration like `(int x, int y) = (1, 2)`
  - [x] In nested scenarios (`ValueTupleReturnWithInferredNamesWithCSharp7_1`)
  - [x] For a deconstruction assignment like `(x, y) = (1, 2)` (`ValueTupleReturnIsEmittedIfUsed`, `ValueTupleReturnWithInferredNamesWithCSharp7_1`)

Where names are inferred, test the behavior of APIs
- [ ] `GetDeclaredSymbol` on the argument expression (probably should not declare the tuple element name)
- [x] `GetTypeInfo`
- [ ] `GetSpeculativeTypeInfo`
- [ ] Test the interaction of typeless tuples with inferred names is per spec. In this case inferred names are never used (there is no type to contain the inferred names).
- [ ] Though it would be an error to use an inaccessible member in a tuple expression, the APIs should still show the name as being inferred based on the syntax.
- [ ] Using a named constant (`const` declared member or local) should infer the name.
- [ ] If the tuple is typeless, e.g. contains a method group, there should be no inferred names (because there is no type into which it could be inferred).

IDE tests (see also the [IDE test plan](https://github.com/dotnet/roslyn/blob/master/docs/contributing/IDE%20Test%20Plan.md)); each for both languages
- [ ] Is the inferred name colored appropriately at its use site?
- [ ] Does completion after dotting off a tuple literal include inferred names?
- [ ] Do inferred names show quick info when hovering on completion list items and uses?
- [ ] Does selecting an inferred identifier also highlight other references to it?
- [x] Does extract method of a tuple literal include inferred names in the return type? (`TestTupleWithInferredNames`)
- [ ] When using extract-method on an expression like `x.y` or `y` in a tuple literal, is it replaced by `y: GeneratedMethod()` to preserve the inferred element name?
- [x] Same as previous two questions for introduce-variable (or is it generate-local?) and/or generate-field instead of extract-method. (`TupleWithInferredName_InferredNameBecomesExplicit`)
- [x] Does inline-temporary-variable introduce a tuple element name lost by the inlining? E.g. changing `(temp, 2)` to `(temp: expression, 2)`? (`ExplicitTupleNameAdded` in C# and VB)
- [ ] Does go-to-definition from a use of an inferred element name navigate to the element of the tuple literal? (manually verified)
- [ ] Does find-all-references find other uses of the same inferred name?

Miscellaneous
- [ ] Complete this test plan (work in progress); The following references may be useful:
  - https://github.com/dotnet/roslyn/blob/master/docs/contributing/Compiler%20Test%20Plan.md
  - https://github.com/dotnet/csharplang/issues/415 (champion issue)
  - https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md
  - The [IDE test plan](https://github.com/dotnet/roslyn/blob/master/docs/contributing/IDE%20Test%20Plan.md).
  - PR for merging the feature to master https://github.com/dotnet/roslyn/pull/19069

**Comment by ufcpp** [comment]
Is this expected behavior?

```cs
using System;

static class Extensions
{
    public static void y(this (int, Action) t) => Console.WriteLine("extension y");
}

class Program
{
    static void Main()
    {
        int x = 1;
        Action y = () => Console.WriteLine("variable y");

        var t = (x, y);

        // "extension y" in VS 15.2
        // "variable y" with <LangVersion>7.1</LangVersion> in VS 15.3 (I know this is an expected breaking change)
        // error CS8306 with <LangVersion>7.0</LangVersion> in VS 15.3 (including 15.3.2. Is this expected?)
        t.y();
    }
}
```

**Comment by jcouv** [comment]
@ufcpp Yes, this is expected. When you upgrade the compiler, you get the new semantics, regardless of LangVersion. We don't try to emulate the old semantics when you set an old LangVersion.
Thanks

**Comment by gafter** [comment]
I'm closing this. @jcouv, do you want issues for additional possible tests?
