### ISSUE TITLE
figure out a way to support project k scenario in persistent service

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#1860]
our persistent service assumes (project.filepath, document.filepath) tuple is unique in a solution. that was true until project k. in project k, new concept of context is introduced where (project.filepath, document.filepath) is no longer unique. 

we need to figure out a way to properly support project k in persistent service.

**Comment by Pilchie** [comment]
Tag @dpoeschl 

There is an IntelliSense project name that we use to distinguish between the contexts.  We could make the tuple include that and just use null for most projects.

**Comment by heejaechang** [comment]
@Pilchie  ya, probably that is what we need to do. but before that, I want to make sure that there is just other unique key I can use rather than file path.
