### ISSUE TITLE
Make fixed pointer local always backed by a pointer.

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#18615]
Currently, in some cases the fixed variable is backed by the actual pinned managed reference, which is converted to a pointer at use sites inside the fixed block.

While, by itself a correct implementation, it is not the most obvious or efficient for the JIT, since it looks like the managed reference is repeatedly accessed and pinned managed references have more loaded semantics than pointers.

A simple solution would be to pin the managed reference, but back the pointer by a real pointer local that is initialized based on the value of the reference.

We are already employing this strategy when pinning strings, we should do the same with arrays and other cases.

===
This came from the analysis of codegen inefficiencies in the Kesterel http server code.

**Comment by jkotas** [comment]
> managed references have more loaded semantics than pointers.

*Pinned* locals containing managed references. Regular non-pinned managed reference locals are fine.

**Comment by VSadov** [comment]
@jkotas - fixed to mention "pinned". 
That clarifies the reason, but the proposed solution is basically the same.
