### ISSUE TITLE
Test plan for "ref assemblies" (7.1)

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#18612]
This is the test plan for "ref assemblies".

See also
- [Language Feature Status](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md)
- [The `refout` feature branch](https://github.com/dotnet/roslyn/tree/features/refout)
- [PR comparing the refout feature branch to master](https://github.com/dotnet/roslyn/pull/19345)
- [[Work items] Refining ref assemblies](https://github.com/dotnet/roslyn/issues/17612)
- [Specification](https://github.com/dotnet/roslyn/blob/features/refout/docs/features/refout.md)
- [Produce ref assemblies from command-line and msbuild](https://github.com/dotnet/roslyn/pull/17558) (initial implementation)
- [Make the command-line compilers able to generate reference assemblies](https://github.com/dotnet/roslyn/issues/2184) (old specification)

-----------------------------

Golden Path Tests
- Unless otherwise specified, the following tests should exist for both VB and C#
- [X] Should produce both an output assembly and a ref assembly using both `/out` and `/refout`
- [X] Should produce only a ref assembly using `/refonly`
- [X] The ref assembly produced should be deterministic when `*` not used in `AssemblyVersionAttribute`
- [X] When `/refonly` is used, we should not be sensitive to semantic error in [see `RefAssembly_InvariantToSomeChanges`]
  - [x] Method bodies (including operators)
  - [x] Properties
  - [x] Field initializers
  - [x] Constructor bodies including initializers
  - [x] Property Accessor bodies
  - [x] Event Accessor bodies
  - [ ] Similarly, all these cases when there is an `InternalVisibleToAttribute`
- [X] When `/refout` and not `/refonly`, we should not produce a ref assembly if there are any errors [see `RefOutWithError`]
- [x] Tuple names in APIs are visible through the ref assembly. (See `RefAssemblyClient_EmitTupleNames`)
- [x] Dynamic in APIs is visible through the ref assembly (C# only). (See RefAssemblyClient_EmitDynamic)
- [x] `out` parameters in APIs are visible through the ref assembly (C# only). (See RefAssemblyClient_EmitOut)
- [ ] Modules are visible through the ref assembly (VB only)
- [x] Variance is visible through the ref assembly (See RefAssemblyClient_EmitVariance)
- [x] Constant and enum values visible through the ref assembly (See RefAssemblyClient_EmitConst and RefAssemblyClient_EmitEnum)
- [x] Parameter default values visible through the ref assembly (See RefAssemblyClient_EmitOptionalArguments. But no way to verify the default value of parameter)
- [x] Parameter names used in overrides visible through the ref assembly. (See RefAssemblyClient_EmitArgumentNames)
- [x] Params parameters visible through the ref assembly. (See RefAssemblyClient_EmitParams)
- [x] Extension methods accessed through a ref assembly act as extension methods. (See RefAssemblyClient_EmitExtension)
- [x] When `/refonly` and `/doc` are used, XML docs produced for included APIs (See `RefOnly` And RefOut in commandline tests)
- [ ] When `/refonly` and `/doc` are used, XML docs not produced for excluded APIs (out of scope for 7.1)
- [ ] When `/refout` used and resource are specified, they are not in the ref assembly
- [ ] When `/refonly` used and resource are specified, they are included in the ref assembly
- [x] When method bodies, comments, and spacing are changed, the ref assembly is invariant.
- [x] The order of members appearing in a ref assembly is the same as in the main assembly (See RefAssembly_VerifyTypesAndMembers)
- [ ] Changing the order of methods in a class causes the order to be changed in the ref assembly
- [x] The generated assembly excludes compiler-generated "implementation details" type (See RefAssembly_VerifyTypesAndMembers, which has anonymous type)

Inclusion and Exclusion
- Most private members of *classes* should be excluded from the ref assembly
  - [x] Fields excluded when `private` (and included otherwise)
- Most private members of *structs* should be excluded from the ref assembly
  - [x] Fields should be included (until we refine this policy)
- For both classes and structs
  - [x] Nested types should be included no matter the access (See RefAssemblyClient_EmitNestedTypes)
  - [ ] Explicit interface implementations should be included (not sure how to verify)
  - [x] Methods, properties, events, operators, indexers, constructors excluded only when `private` (I don't think I have a test for operators or indexers though)
  - [x] Private accessors of properties should be excluded (See RefAssembly_VerifyTypesAndMembers)
  - [ ] Attributes in all locations included (until we refine this policy)
- [ ] In the future, we can change `private` to `internal` and exclude more if there are no `InternalsVisibleTo`.
- [ ] Generic type parameter constraints on included API elements are included.

Miscellaneous
- [ ] It is an error to use `/addmodule` with either `/refout` or `/refonly`.
- [x] Produce `ReferenceAssemblyAttribute` in the ref assembly with either `/refout` or `/refonly`.
- [ ] `/refonly` and `/debug` together are an error (There is a test for this, but the test asserts that it is NOT an error. Perhaps change spec? See #19708)
- [x] Ensure error scenarios around structs are preserved when used from a ref assembly
  - [x] A struct with any non-empty field is not empty for DA purposes (See RefAssemblyClient_StructWithPrivateIntField)
  - [x] A generic struct with a generic private field may cause circularity errors at a use site, e.g. `struct S1<T> { private T t }` in the ref assembly used this way `struct S2 { S1<S2> x; }`   (See RefAssemblyClient_StructWithPrivateGenericField)
- [ ] Are there winmd-specific scenarios?
- [ ] Can F# compile against ref assemblies?
- [ ] Can C++ compile against ref assemblies?
- [ ] There should be an error if the main assembly and ref assembly have different names.
- [ ] Test F5 scenario in IDE

Build Scenarios
- The implementation includes MSBuild support not covered by this test plan. However, here are some basics:
  - [ ] Test build and rebuild scenarios.
  - [ ] An up-to-date ref assembly should cause the build of a dependent assembly to be skipped
  - [ ] An up-to-date ref assembly should not prevent deployment of a dependent project when the associated DLL has changed.
- [ ] Does C# scripting run against the proper assembly when ref assemblies are used in the build?

**Comment by jasonmalinowski** [comment]
Some things to think about for the test plan:

1. Testing build, and rebuild scenarios, and making sure the binaries are correctly deployed in all projects. The fast-up-to-date check could interfere with things.
2. Testing references between C# and VB project references, and ensuring the IDE is working correctly across those. (Do refactorings work, for example?)
3. Testing references to and from C++ projects, both regular DLL kinds and also .winmd producing kinds.
4. Testing across the .NET Core / legacy project system boundary.
5. Object browser?
6. XAML designer.
7. WinForms designer with controls being consumed across-projects.
8. Live Unit Testing.

**Comment by tmat** [comment]
Also references that use ```AssemblyVersion(*)```

**Comment by rainersigwald** [comment]
@jcouv's initial testing has revealed a couple of interesting project set-up scenarios:

* Legacy csproj that references System.Runtime facades
* New-SDK csproj that references System.Runtime facades through NuGet packages

(I tested the latter during development but broke the former.)

**Comment by jcouv** [comment]
Another scenario from Jason:
>I’m not sure exactly when the legacy project system reevaluates that item group, so you’ll probably want to test that it does it right after adding a new project reference and also does it if you rename the output name of a project you’re depending on or change it’s output path.

**Comment by jcouv** [comment]
Here are [my notes](https://gist.github.com/jcouv/4c05a3917a8e5a2c5f7e196374fa7036) for the test plan's checklist.

**Comment by gafter** [comment]
Went over the test plan today with @jcouv and checked off all we could.

**Comment by jcouv** [comment]
Issues so far:
- [ ] Go To Definition goes to metadata view, instead of source
- [ ] If I add an API to a library, I need to re-build the library and the client before the API is visible to the client
- [ ] Live Unit Testing gives "Build completed (failed)."

**Comment by gafter** [comment]
I'm closing this. @jcouv, do you want issues for additional proposed tests?
