### ISSUE TITLE
Get offered a smart tag that I cannot drop down for an incomplete method

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#18621]
``` C#
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ConsoleApp282
{
    class Program
    {
        public async Task<IReadOnlyCollection<ProjectConfiguration>>
    }
}

```

1. Place cursor in ProjectConfiguration
2. Hover mouse over ProjectConfiguration so that a smart tag appears
3. Click Smart tag

Expected: For smart tag to be opened
Actual: Smart tag disappears

**Comment by davkean** [comment]
Why do we offer the smart tag in that case only for you not to be able to select it?

**Comment by CyrusNajmabadi** [comment]
No clue.  I haven't debugged through this yet to see.

**Comment by CyrusNajmabadi** [comment]
I'm just adding notes for the person who takes a look at this as to probable issue.  It's likely that the detection part of the system thought it was ok.  But the fix portion got thrown off by the wonky tree.

**Comment by CyrusNajmabadi** [comment]
I don't repro this problem myself:

![image](https://cloud.githubusercontent.com/assets/4564579/24977819/45ffeec2-1f83-11e7-97ae-f26c7966b78b.png)

**Comment by CyrusNajmabadi** [comment]
Note: i tried caret locations all through that type (including right before/after the ```<``` and ```>``` tokens.  All locations works properly.

**Comment by CyrusNajmabadi** [comment]
Tagging @olegtk

**Comment by olegtk** [comment]
Yep, can repro that. File an internal bug please.

**Comment by CyrusNajmabadi** [comment]
Done: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/407331
