### ISSUE TITLE
Get nonsensical code fixes when you've typed a generic type without any type arguments 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#18623]
I've probably filed this before but I'm filing it again as I can't find it. This annoys me especially with types that are you aren't aware if there are non-generic versions or not (`IReadOnlyCollection<T>` is a perfect example of this - we have `ICollection` and `ICollection<T>`, but there's no non-generic version of `IReadOnlyCollection`)

Here's the behavior:

![resolvenamespace](https://cloud.githubusercontent.com/assets/1103906/24943270/1158ddf8-1f99-11e7-8048-3da7583aeaf8.gif)

**Comment by davkean** [comment]
Sorry for the quick video, GitHub has a limit on file size.

**Comment by CyrusNajmabadi** [comment]
I recommend screentogif.  File sizes will not be a problem then :)

**Comment by CyrusNajmabadi** [comment]
This might be tricky to fix.  We do need to offer 'fully qualify' in many cases, even when there's an equivalent using in scope.  

I'm thinking the appropriate fix is:

1. if no type args are present, get the list of candidate namespaces.  Allow for hits for types with/without generics.
2. For each possible namespace, we then:
3. Walk inside out, seeing what namespaces are imported at each level.  If we hit an import layer that imports this namespace, then don't consider this a viable match.  If we do hit an import layer that pulls in another type with the same name, then *do* consider this namespace as match (as it could be used for disambiguation).
