### ISSUE TITLE
Question: Recommended way to get method signatures

### ISSUE THREAD

**Issue by andrew-vandenbrink** [dotnet/roslyn#18630]
The FAQ in this link, refer to **old** pattern to get completion list
https://github.com/dotnet/roslyn/wiki/FAQ 

Now that completion service is public api, there is new pattern to get completion list

The question is,
What is the recommend way to get method signatures?

Logic in 
https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.Roslyn.CSharp/Services/Signatures/SignatureHelpService.cs#L176
seems using the **old** pattern to get method signatures

**Comment by Pilchie** [comment]
Tagging @DustinCampbell, but this is basically https://github.com/dotnet/roslyn/issues/3540.
