### ISSUE TITLE
[Suggestion] Default Grouping Collapse/Expand Behavior in FAR with interfaces

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#18643]
Version Used: 2.0.0.6150105 (VS 2017 RTW 26228.4)

Steps to Reproduce:
far
1. Create a C# project
2. Add several classes that implement the IDisposable interface.
3. Right click an implementation of the Dispose method and invoke "Find all references"

Expected Behavior:
One of the following:
- Group for the concrete implementation of Dispose on the class on which we invoked FAR is the only group that is expanded. All other tree nodes are collapsed until an explicit user action is performed.
- Group for the concrete implementation of Dispose on the class on which we invoked FAR is the top-most group (before user applies column-based sorting).

Actual Behavior:
Every implementation of `IDisposable.Dispose()` shows up. The group containing references to the desired concrete implementation is buried deep within the results, requiring scrolling to find it.

**Comment by CyrusNajmabadi** [comment]
This work has been done.  We will only show results in FAR that could actually call into the implementation method in question.
