### ISSUE TITLE
Provide extensibility system to map custom completion tags to completion images+filters

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#18649]
Razor would like this as they have some items they want to put in the completion list that do not map to any of our well known completion tags.  i.e. they want completion for something like "@import" and they'd like a glyph+filter representing "@-directives".  

This should not be too difficult to provide, though it would likely be custom to every layer that has a way to present images.  For example, our Editor layer would likely provide a model that goes from Tags-to-ImageMonikers (if that's the lowest layer where ImageMonikers are available).  

Note: if the editor moves to a new completion API, we'll likely want this to track nicely with that work.

**Comment by CyrusNajmabadi** [comment]
Tagging @Pilchie @toddgrun

**Comment by madskristensen** [comment]
We would like this for 15.4. The change is important so Razor can provide Intellisense for Razor directives which is a highly requested feature. The lack of the feature makes the Razor editor seem broken and incomplete and we've received many many bugs on it from users
