### ISSUE TITLE
Incorrect error for await in local function inside lock

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#18644]
See https://github.com/dotnet/csharplang/issues/392 for details.

The compiler improperly produces an error when `await` is used inside a local function whose declaration happens to be inside a `lock` statement.

**Comment by jcouv** [comment]
Moving to 15.later. Yell if it should stay in 15.5.

**Comment by jcouv** [comment]
Closing the issue on behalf of @t-camaia 
The fix was merged to `features/compiler` which will likely ship in 15.7.
