### ISSUE TITLE
[Suggestion] Find all references filter and/or grouping for XML comments

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#18641]
**Version Used**: 2.0.0.6150105 (VS 2017 RTW 26228.4)

**Steps to Reproduce**:
![far](https://cloud.githubusercontent.com/assets/5387680/24974496/3204aac2-1f77-11e7-9a37-ae1edc480910.png)

1. Create a C# project
2. Add an interface or class with XML doc comments referencing that class via `<see cref=..>`
3. Right click class name, invoke "Find all references"

**Expected Behavior**:
Some form of filtering of grouping of references from doc comments in FAR.

Typically, I use FAR for one of two purposes:

1. Tracing through callers of code to assess the impact of a code change.
2. Checking for all references for the purposes of sweeping refactors.

For case 1., which in my workflow is the common case, it'd be useful to be able to either group FAR results by usage type (e.g.: comment, call, reference, etc.), or to be able to filter out usage type (e.g.: exclude all references from DOC comments) since these references have no impact on program behavior.

**Actual Behavior**:
Observe that doc comment references fill up much of the FAR visual real estate, making it cumbersome to navigate actual usages. This problem grows significantly if you perform an FAR on commonly used types that are referenced in XML comments such as `string`.

**Comment by Pilchie** [comment]
Somewhat related to #17684 - and the desire to support filtering FAR by type of access in general.

**Comment by CyrusNajmabadi** [comment]
closing out given lack of customer feedback on this.
