### ISSUE TITLE
Null Reference when attempting to navigate to a constructor from Find All References

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#18666]
I double-clicked the highlighted constructor in Find All References, and VS opened a dialog and said that an extension failed and to look at ActivityLog. 

![image](https://cloud.githubusercontent.com/assets/1103906/24994012/542a5016-206c-11e7-842d-5adeb4f01558.png)

Looking at the log I see:

```
System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.GetDocumentIdInCurrentContext(DocumentId documentId) at
Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.TryNavigateToSpan(Workspace workspace, DocumentId documentId, TextSpan textSpan, OptionSet options) at Microsoft.CodeAnalysis.DocumentSpanExtensions.TryNavigateTo(DocumentSpan documentSpan) at
Microsoft.CodeAnalysis.FindUsages.DefinitionItem.DocumentLocationDefinitionItem.TryNavigateTo() at Microsoft.VisualStudio.LanguageServices.FindUsages.StreamingFindUsagesPresenter.RoslynDefinitionBucket.TryNavigateTo() at
Microsoft.VisualStudio.LanguageServices.FindUsages.FindUsagesTableControlEventProcessorProvider.TableControlEventProcessor.PreprocessNavigate(ITableEntryHandle entry, TableEntryNavigateEventArgs e) at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.<>c__DisplayClass40_0.<OnEntryElementNavigate>b__2(ITableControlEventProcessor p, ITableEntryHandle entry) at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.<>c__DisplayClass59_1`1.<EventProcessorHandler>b__0() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
```

Double-clicking again does not provide an error. In between Finding the results, and double-clicking the constructor I had changed code a lot by reverting a bunch of changes, including to the file in question.

Cannot repro this again,

**Comment by davkean** [comment]
Oh I I think I renamed this file and then undid that rename - which may have reloaded a project in between, or maybe a solution. I'm not sure. Perhaps the document doesn't exist any more?

**Comment by CyrusNajmabadi** [comment]
@dpoeschl This looks like a linked file issue.  Basically, this codepath is intended to be able to fail (hence the "Try" part). however, there has been an added call to:

```c#
            documentId = workspace.GetDocumentIdInCurrentContext(documentId);
```

The default impl of that basically cannot fail, however, it looks like the impl can fail in VIsualStudioWorkspaceImpl here:

```c#
            var hostDocument = GetHostDocument(documentId);
            var itemId = hostDocument.GetItemId();
```

if this codepath is intended to be called from codepaths that can fail (for example, because the document-id being referred to is no longer around), then it needs to be resilient here as well.

**Comment by CyrusNajmabadi** [comment]
Havne't gotten any reports on this, and we redid how navigation and linked files works.  Closing out.
