### ISSUE TITLE
Visual studio 2017 keeps collapsing pinned windows

### ISSUE THREAD

**Issue by mcosmin222** [dotnet/roslyn#18669]
**Version Used**: 2017.1

**Steps to Reproduce**:

1. Create a new solution
2. Pin the solution explorer, to keep it open
3. start and then stop debugging
4. Solution explorer is now collapsed

**Expected Behavior**:
Solution explorer (pinned window) should stay opened because it was opened when I started debugging

**Actual Behavior**:
Solution explorer (pinned window) gets collapsed after I stopped debugging

**Comment by Pilchie** [comment]
Roslyn doesn't control the window management - can you please file through VS Send Feedback instead?

In general though there are different (independent) window layouts for while debugging and while not debugging, so that you don't have to manage callstack/locals/etc while not debugging, so I expect this is by design from the VS platform team's viewpoint.

**Comment by winifix** [comment]
Same issue ETA on Fix?

**Comment by whoisj** [comment]
https://developercommunity.visualstudio.com/content/problem/51581/solution-explorer-does-not-remain-pinned-after-clo.html

**Comment by winifix** [comment]
Found the correct solution, and although this is not really related to this git, its the only thing that returns results in google so everyone will see this

In visual studio click
Help -> "Manage Visual Studio Performance"
under "Tools Windows" -> "Startup" make sure "Use Default Behavior" is selected for both
1. Team Explorer
2. Object Browser
Now when you build your solution pinned windows will actually remain pinned.

**Comment by mcosmin222** [comment]
I looked for that setting everywhere (kind of unintuitive for it to be under HELP). I knew it was somewhat related to it, since the issue only started appearing after VS offered to "optimize" performance. I lost more time uninstalling it and then reinstalling because I could not find how to turn it off.

**Comment by kthayer424** [comment]
The "Manage Visual Studio Performance" solution worked, but to be clear, you need to "Use Default Behavior" for every window in the panel of pinned windows. In my case it was the Error List window minimizing all the other windows in the same panel.

**Comment by craiggeil** [comment]
Little disappointed that Microsoft hid this setting under Help of all places. It belongs in Options.

**Comment by CyrusNajmabadi** [comment]
@craiggeil Please file feedback as per https://github.com/dotnet/roslyn/issues/18669#issuecomment-293959272

That way the platform team will see this and can consider doing something about it.  This is the repo for C#/VB and has no relation to the platform's windowing code.  Thanks!
