### ISSUE TITLE
Have compiler return semantic errors in lambdas even in the presence of syntax errors

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#1867]
Today, the compiler does not return semantic errors inside lambdas in the IDE if there are syntax errors.   This causes several quick fix scenarios to fail inside lambdas (for example #1239, #1241, and #1744 are all caused by this problem).  

Consider the code sample below from issue #1239:
```C#
using System.Threading.Tasks;

class C {
    C() {
        Task.Run(() => {
            new C(0)
        });
    }
}
```

_new C(0)_ will never be squiggled by the IDE because of the lack of a semicolon.  This makes quick-fixes that could generate a constructor unable to run because there is no error to trigger them.  

By having the compiler return semantic errors in lambdas even in the presence of syntax errors, many more IDE scenarios will "Just Work"

**Comment by CyrusNajmabadi** [comment]
Note: whenever this is fixed we need to remove the UnboundIdentifiersDiagnosticAnalyzerBase type and ensure all AddUsing tests (and other tests that depend on this type) still continue passing.  Right now, this type is a hack at the IDE layer to get and display reasonable semantic errors to the user and to drive our normal features.  This should not be something the IDE is responsible for doing.  Users should be getting these errors, even in the presence of a syntax error in a lambda, and our features should not have to list for syntax errors to drive semantic features.

**Comment by CyrusNajmabadi** [comment]
Reactivating.  Here are cases where we still don't get errors from the compiler:

```c#
using System.Linq;
class C { C() { "".Select(() => { new Byte  //<-- no error on Byte
class D { D() { "".Select(() => { new Byte  ( ) }   //<-- no error on Byte

class Program
{
    static void Main(string[] args)
    {
        args[0].Any(x => IBindCtx  // <-- no error on IBindCtx
        string a;
    }
}
```

**Comment by gafter** [comment]
For the first two cases, the compiler certainly *does* produce a semantic error about `Byte` not found. But I'll be sure to add a test case for them.

Working on the third case.

**Comment by gafter** [comment]
OK, in the third case we have a lambda of the form

```cs
e.Any(x => identifier string identifier; // and more broken syntax
```

and you're complaining that we don't give an error that we can't bind the first identifier? What are you imagining the compiler would be trying to bind it *for*? It simply doesn't line up with any recognizable expression form.

**Comment by gafter** [comment]
Here is a better repro for the third case:

```cs
        args[0].Any(x => IBindCtx, foo foo);
```

Here we should give an error that we can't bind IBindCtx.

**Comment by gafter** [comment]
OK, PR #7555 addresses all the new cases.

**Comment by gafter** [comment]
@CyrusNajmabadi OK, all fixed. I'm eager to catch as many of these cases as possible. You're welcome to open *new issues* for any new cases you discover.

**Comment by CyrusNajmabadi** [comment]
@gafter Will do.  Thanks!
