### ISSUE TITLE
Invalid expression binds to valid TypeSymbol.

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#18675]
**Version Used**: Visual Studio 2017 15.1.0+26403.3

**Code to Reproduce**:
```csharp
using Microsoft.CodeAnalysis.CSharp;

namespace N
{
    public class C
    {
        public void M()
        {
            var kind = x.Kind();
        }
    }
}
```
If we try to obtain TypeSymbol for `x.Kind()` we get `Microsoft.CodeAnalysis.CSharp.SyntaxKind` which does not make sense to me.

**Comment by gafter** [comment]
It is the only extension method in your solution. You are also getting an error message for it.

**Comment by JosefPihrt** [comment]
I assumed that invalid expression cannot have valid TypeSymbol, which does not seem to be the case.

Interesting is that I get can TypeSymbol (method's return type) but I am unable to get MethodSymbol of the expression `x.Kind()`.
