### ISSUE TITLE
Use Throw Expression code action discards contents of else-clause

### ISSUE THREAD

**Issue by magnusbakken** [dotnet/roslyn#18670]
**Version Used**:
Visual Studio 2017 (build 26403.3)

**Steps to Reproduce**:
Apply the "Use throw expression" code action on a piece of code that performs a null check and throws ArgumentNullException for some variable if it's null, or assigns the variable to a member field if the value isn't null, but which also has an else or else-if clause for the if-statement.

    int? _x;

    public C(int? x)
    {
        if (x == null)
        {
            throw new ArgumentNullException(nameof(x));
        }
        else
        {
            Console.WriteLine("x is not null");
        }

        _x = x;
    }

**Expected Behavior**:
Either the code action should preserve the else clause, or it shouldn't offer an action at all. To retain the original behavior, the resulting code would have to be:

    int? _x;

    public C(int? x)
    {
        if (x != null)
        {
            Console.WriteLine("x is not null");
        }

        _x = x ?? throw new ArgumentNullException(nameof(x));
    }

But now it's doing the null check on x twice.

**Actual Behavior**:
In actuality the code action simply discards the else clause, yielding this:

    int? _x;

    public C(int? x)
    {
        _x = x ?? throw new ArgumentNullException(nameof(x));
    }

If you use an else-if clause instead of a simple else clause it's the same story. The following code has the same exact output as the first example:

        if (x == null)
        {
            throw new ArgumentNullException(nameof(x));
        }
        else if (x == 0)
        {
            throw new ArgumentException("Cannot be zero", nameof(x));
        }

**Demonstration**:
![throwexpressionproblem](https://cloud.githubusercontent.com/assets/284189/25001727/1c86e09a-2047-11e7-9d5a-615d13ba7015.gif)

**Comment by CyrusNajmabadi** [comment]
Ack!
