### ISSUE TITLE
"Convert if to switch" should only fire if there's at least two checks

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#18686]
**Version Used**: Current as of this bug filing.

![image](https://cloud.githubusercontent.com/assets/235241/25022499/f03b5eae-204a-11e7-9c68-66e87d2238e5.png)

**Comment by alrz** [comment]
For reference, this was mentioned in the PR,


>>It might help if you don't want or forget to write the switch itself and you've just started typing. But I'll consider it if you want

>Yes. I see your point. If we only offer this on the 'if' keyword, then i think that will keep down noisiness and so we can still allow it even for these simple cases.

**Comment by Pilchie** [comment]
@alrz now that we're showing the lightbulb automatically whenever there is a refactoring, this feels like a little too much when we're using it for day to day development.

**Comment by alrz** [comment]
I think there should be a way to  specify "likelihood" of a refactoring to be preferable, then we show the lightbulb to indicate that there is something than can be done here that is likely to be preferable. In other cases, we still show it in the action menu, I don't really see any reason to make this depend on the number of comparisons since the refactoring clearly says "convert if to switch" and that's exactly what it's going to do.

**Comment by dpoeschl** [comment]
Even if some other fix/refactoring that's more likely to be preferable causes the lightbulb to be shown, I don't want to be hit by a crazy long list things, especially when some of them don't provide value, so we have to be *somewhat* conservative about what we show. I *really* think converting a null check to a switch on `case null:` doesn't provide value. Maybe we don't need multiple comparisons (I don't know, that was @CyrusNajmabadi's suggestion), but I at least think the null-check case should be special-cased out.

**Comment by CyrusNajmabadi** [comment]
There are two cases here that i can identify.

1. The user who says "i need to add another check, let me convert this simple-if to a switch, and then add them in."  
2. The user who comes to something complex, and says "i would lke help converting this large entity to a switch".

While '1' is valid, it seems less likely and less important than '2'.  The real value here is the ability to take a large chunk of code and convert it over.  Offering the feature on all "ifs" on the off chance someone may want this seems inappropriately excessive.

**Comment by MattGertz** [comment]
@CyrusNajmabadi Nevertheless, this _is_ a take-back, and I'm sure we'll get at least one customer stating that, in their case, they've simply changed their mind after starting something as an "if" that they realized really should be a "switch," but the command doesn't exist.  I'm not sure it hurts to have this stay in.  Can you check with Kasey first?  Then tag me again if PM agrees.

**Comment by Pilchie** [comment]
@MattGertz Note that we haven't shipped this feature yet.  It was added after 15.0.

**Comment by MattGertz** [comment]
Thanks -- I withdraw my objection and approve.

**Comment by CyrusNajmabadi** [comment]
You approved the bug, not the PR :)  That's ok, i make lamb.

**Comment by alrz** [comment]
@CyrusNajmabadi Would it make sense to not suggest this only if the constant is `null`? The use case is that when you want to add an `else if` to an existing `if` statement, with this change you won't get the fix until you fully write the second condition.

**Comment by CyrusNajmabadi** [comment]
To me, it would still be an issue if you had "if (x == 0)" etc.

**Comment by alrz** [comment]
Yeah, just read the comment in the code. thanks.
