### ISSUE TITLE
Can Deconstruct instance methods never be generic?

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#18682]
**Version Used**: 2.1.0.61520

**Steps to Reproduce**:

```csharp
using System;

class Test
{
    object x, y;
    
    public void Deconstruct<T>(out T x, out T y)
    {
        x = (T) this.x;
        y = (T) this.y;
    }
    
    static void Main()
    {
        var test = new Test { x = 1, y = 2 };
        // Doesn't compile
        //(int a, int b) = test;
        
        // This is fine: int is inferred
        int a, b;
        test.Deconstruct(out a, out b);
    }
}
```

The commented out code produces error messages of:

> Test.cs(16,26): error CS0411: The type arguments for method 'Test.Deconstruct<T>(out T, out T)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
> Test.cs(16,26): error CS8129: No Deconstruct instance or extension method was found for type 'Test', with 2 out parameters and a void return type.

Now I'd start by arguing that the second message is incorrect: it clearly *did* find a Deconstruct instance method with 2 out parameters and a void return type... but it wasn't deemed appropriate due to the first message.

I'm trying to write (for C# in Depth) the rules of `Deconstruct` methods. Would it be fair to say that:

- Instance `Deconstruct` methods can't be generic
- Extension `Deconstruct` methods can be generic, but all type arguments must be inferred via just the first (`this`) parameter

? That second statement is *very* woolly to start with, given the complexities of type inference, but if we can start with something in the right direction, that would be good.

**Comment by jaredpar** [comment]
CC @jcouv

**Comment by jskeet** [comment]
Now that I've looked at `Deconstruct` overloading a bit more carefully, it feels like only the arity of the "target" is used in order to find a candidate method, which would certainly make sense of this restriction. Is finding the method to deconstruct effectively a matter of trying to transform:

```csharp
(int x, string y) = target;
```

into something like:

```csharp
target.Deconstruct(out var tmp1, out var tmp2);
int x = tmp1;
string y = tmp2;
```

... and then checking that would work? That would explain a lot of what I'm seeing. If it's a good way of thinking about deconstruction, I'll use it in the book...

**Comment by jcouv** [comment]
@jskeet Yes, deconstruction translates to something that is very similar to `out var`. Once a method is found by this mechanism, we apply further restrictions (return type, etc).

See https://github.com/dotnet/roslyn/blob/master/docs/features/deconstruction.md

## Resolution of the Deconstruct method

The resolution is equivalent to typing `rhs.Deconstruct(out var x1, out var x2, ...);` with the appropriate number of parameters to deconstruct into. It is based on normal overload resolution. This implies that `rhs` cannot be dynamic and that none of the parameters of the `Deconstruct` method can be type arguments. A `Deconstruct<T>(out T x1, out T x2)` method will not be found. Also, the `Deconstruct` method must be an instance method or an extension (but not a static method). It also must return void.

**Comment by jskeet** [comment]
Fantastic - thanks very much :)
