### ISSUE TITLE
Make UpgradeProject work for VB

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#18694]
The driving scenario is tuple inferred names (https://github.com/dotnet/roslyn/pull/18374) (VB 15.3).

Update: also VB 15.5 features.

**Comment by jcouv** [comment]
FYI @Pilchie @kuhlenh I moved this to IDE category, as there is currently no UI for setting LangVersion in VB projects and DTE APIs are lacking for setting it programmatically as well. 
I'm happy to help with the UpgradeProject code fixer itself, if we decide to go ahead with the above two first. 
Thanks

**Comment by AdamSpeight2008** [comment]
@jcouv Could we add a UI Setting for the Language Version?

**Comment by AnthonyDGreen** [comment]
@jinujoseph This is the work item I was talking about. We need this to expose the point release versions of VB in the UI.

**Comment by jcouv** [comment]
@jinujoseph One more thought on this, the work to add the UI drop-down and underlying API for VB LangVersion is likely very similar to the work to add WarnVersion (C# and VB). https://github.com/dotnet/roslyn/issues/1580
Let's do WarnVersion at the same time.

**Comment by jinujoseph** [comment]
moved to project system [link](https://github.com/dotnet/project-system/issues/3141)
