### ISSUE TITLE
Make SemanticModel's Analyze*Flow methods public. Remove corresponding extension methods.

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#187]
Both [AnalyzeControlFlow](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/Compilation/SemanticModel.cs,7630aa539f5fc234,references) and [AnalyzeDataFlow](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/Compilation/SemanticModel.cs,c9303de5c28c5a3c,references) are marked internal within SemanticModel.

They're exposed via extension methods in [ModelExtensions.AnalyzeControlFlow](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/Compilation/Extensions.cs,b982b6ec87a8fbbd,references) and [ModelExtension.AnalyzeDataFlow](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/Compilation/Extensions.cs,1ffe843748276870,references)

I don't think accessing these methods through extension methods provides any value. I propose the extension methods be removed (for the above methods, and their other overload) and we simply mark the corresponding methods within SemanticModel as public. 

If the team agrees, I can go ahead and submit a PR for this.

**Comment by jmarolf** [comment]
This looks like a mistake from when we unified the interface ISemanticModel to the abstract class SemanticModel.  Go ahead and submit a PR.

**Comment by gafter** [comment]
If I recall, the language-specific extension methods are type safe (e.g. Taking language-specific StatementSyntax)

**Comment by JoshVarty** [comment]
There are language-specific extension methods and they should be left alone. 

But I don't think that the language-agnostic extension methods serve a purpose that wouldn't be achieved by making the following methods public instead of internal.

```CSharp
SemanticModel.AnalyzeControlFlow(SyntaxNode)
SemanticModel.AnalyzeControlFlow(SyntaxNode, SyntaxNode)
SemanticModel.AnalyzeDataFlow(SyntaxNode)
SemanticModel.AnalyzeDataFlow(SyntaxNode, SyntaxNode)
```

**Comment by DustinCampbell** [comment]
That seems fair to me.

**Comment by JoshVarty** [comment]
As discussed in #190 this is by design.
