### ISSUE TITLE
AssemblySymbol.GetWellKnownType API should be removed

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#18700]
```
        internal NamedTypeSymbol GetWellKnownType(WellKnownType type)
        {
            return this.GetTypeByMetadataName(WellKnownTypes.GetMetadataName(type));
        }
```

This method is not used by the compiler in any meaningful way, moreover its implementation is incorrect because it doesn't follow the lookup rules for well-known types. We should remove it before someone uses it by mistake, assuming it does the right thing.

**Comment by BattleRush** [comment]
Created pullrequest: https://github.com/dotnet/roslyn/pull/18731

First time commiting to roslyn, let me know if done correctly.
