### ISSUE TITLE
Workspace options API behaves very stangely

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#18707]
From #13430:

> These tests share a workspace via a class fixture. Some of the tests validate behaviour with non-default options. The goal of my changes was to apply these non-default values, then restore the options to the original state once the test is complete.

> The  OptionSet  is presented as what looks like a standard immutable API, so my plan was to read  Workspace.Options  and store it for later. In the meantime I would use that snapshot to create a new instance with the non-default values needed for the test, and apply them to the workspace (this part worked fine). Once the test was done, my attempts to apply the original  OptionSet  to the workspace never seemed to have any effect - the non-default options would stay in effect and cause subsequent tests to fail. The reason I found was that  WorkspaceOptionSet  is not actually a snapshot, but a cache only of "observed" values. Before the test, no options had been observed, so restoring the original instance just restored an empty cache - reads still went through to the underlying  IOptionService  which still contained the non-default values.

> My workaround for this was to "observe" all the options before I changed them. That way, I could get an  OptionSet  primed with the default values, so applying it afterwards would actually change something. This was frustrated by always getting an empty  WorkspaceOptionSet  from  Workspace.Options , which was effectively throwing away any of the default values I'd previously observed.

In summary:

1. `OptionSet` looks like an immutable snapshot, but the workspace implementation isn't.
2. Reading workspace options always returns [an empty WorkspaceOptionSet](https://github.com/dotnet/roslyn/blob/c723ac13c874b7dd867cca79324535e42fcd5a45/src/Workspaces/Core/Portable/Options/OptionServiceFactory.cs#L118), losing any cached values.

cc @jasonmalinowski

**Comment by CyrusNajmabadi** [comment]
> The reason I found was that WorkspaceOptionSet is not actually a snapshot, but a cache only of "observed" values. Before the test, no options had been observed, so restoring the original instance just restored an empty cache - reads still went through to the underlying IOptionService which still contained the non-default values.

The right way to read options now is to get them through Solution.Options (https://github.com/dotnet/roslyn/blob/c8eb69d84c1ca2fb344c741992e1bac4f7e75928/src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs#L1482). **not** Workspace.Options.  This is a true snapshot that is safe to read in a multi-threaded/changing environment.
