### ISSUE TITLE
VS Integration tests should install an AssertListener in the VS process

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#18704]
We install an AssertListener for unit tests that logs the assert and fails the test.  We should do the same for the VS process when running VS integration tests, so that they don't just hang the test run.

See https://github.com/dotnet/roslyn/issues/18676 for an example of where we didn't.

**Comment by rchande** [comment]
See https://github.com/dotnet/roslyn/blob/3dff8b3c78945aeae449da2ecd59082696eb2f36/build/Defaults/Desktop/app.config#L10-L17 for example

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative and given that we rewrote integration tests.
