### ISSUE TITLE
random CPU spikes in idle VS

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#18703]
_From @abpiskunov on April 14, 2017 0:17_

I was looking at VS at some moment in Task Manager and noticed that CPU started to grow to 50-60%  randomly without any action in VS (it was opened for a while already).  It was going on for sometime, then I decided to catch a trace and took etl: \\vwdbuild01\Temp\antonpis\dump\RandomCPU.etl  and it showed some code analysis going on, not sure if it is roslyn or Code Lense ..  

See if you want to investigate that…

_Copied from original issue: dotnet/project-system#1993_

**Comment by Pilchie** [comment]
@mavasani can you take a look?

**Comment by jinujoseph** [comment]
we have done a lot of perf improvement after this. 
If you still continue the see the same issue , pls reopen with new traces
