### ISSUE TITLE
XML Doc Comment handles Enter incorrectly when there is whitespace before caret

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#18713]
**Version Used**: 15.1.26405.1

**Steps to Reproduce**:

```Csharp
/// <summary>
/// 
/// </summary>
class C
{

}
```
1. Place cursor on middle line of doc comment. (Ensure that there is space before cursor)
2. Press enter

**Expected Behavior**:
```CSharp
/// <summary>
///
/// 
/// </summary>
class C
{

}
```

**Actual Behavior**:

```CSharp
/// <summary>
///

/// </summary>
class C
{

}
```

![image](http://i.imgur.com/5Hku5UV.gif)

**Comment by Pilchie** [comment]
Pretty sure this is a dupe.

**Comment by Pilchie** [comment]
But I can't find it - @DustinCampbell does it look familiar to you?

**Comment by DustinCampbell** [comment]
Nope. I fixed a ton of these long ago. I'd guess this is a regression.

**Comment by DustinCampbell** [comment]
Here's the unit test that tests this precise scenario:

https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/CSharpTest/DocumentationComments/DocumentationCommentTests.cs#L848-L869

**Comment by JoshVarty** [comment]
I can't repro this outside of two of my solutions. (Platform and Editor)

Are there `.editorconfig` or similar solution options that might interact with XML Doc comments in such a way to cause this? Maybe trailing or leading whitespace options?

**Comment by JoshVarty** [comment]
Yes I think it's the presence of `trim_trailing_whitespace = true`
