### ISSUE TITLE
More detail around requirements for integer comparisons in constant patterns

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#18728]
**Version Used**: 2.1.0.61520

**Steps to Reproduce**:

```csharp
using System;

class Test
{
    static void Main()
    {
        int x = 10;
        if (x is 10L)
        {
            Console.WriteLine("Yes");
        }
    }
}
```

**Expected Behavior**:

Compiles with no error, executes and prints "Yes".

**Actual Behavior**:

> error CS0266: Cannot implicitly convert type 'long' to 'int'. An explicit conversion exists (are you missing a cast?)

From the [patterns](https://github.com/dotnet/roslyn/blob/master/docs/features/patterns.md) feature spec:

> If both `e` and `c` are of integral types, the pattern is considered matched if the result of the expression `e == c` is true.

The expression `x == 10L` is perfectly valid, so why isn't this pattern valid? I'm not suggesting that there should be a change to the behavior, but it would be nice to have a little more description in the feature doc, in lieu of a C# 7 full specification.

**Comment by AdamSpeight2008** [comment]
@jskeet Is the conversion being reported also wrong. Shouldn't it be `Int` to `Long` rather that `Long` to `Int`.

**Comment by jskeet** [comment]
I assume it's trying to convert the constant to the input type, but we'll find out more later, I expect :)

**Comment by jcouv** [comment]
FYI @gafter

**Comment by gafter** [comment]
The feature specification is at https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md and it says

> A constant pattern tests the value of an expression against a constant value. The constant may be any constant expression, such as a literal, the name of a declared const variable, or an enumeration constant, or a typeof expression. The expression is implicitly converted to the type of the matched expression. If no suitable implicit conversion exists, or the result is not a constant, the pattern-matching operation is an error. Otherwise the pattern c is considered matching the expression e if object.Equals(c, e) would return true.

While the compiler may indeed generate better code, such as a direct integral comparison, an error is required for this case.

**Comment by jskeet** [comment]
Great, thanks for the link. Will read that in more detail :)
