### ISSUE TITLE
Confusing error message when using a var pattern in switch/case with pointer input

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#18727]
**Version Used**:  2.1.0.61520

**Steps to Reproduce**:

```csharp
using System;

class Test
{
    unsafe static void Main()
    {
        fixed (char *x = "hello")
        {
            switch (x)
            {
                case var y: break;
            }
        }
    }
}
```

**Expected Behavior**:

An error message that helps the user understand what's wrong.

**Actual Behavior**:

> Test.cs(11,22): error CS0244: Neither 'is' nor 'as' is valid on pointer types

This is confusing (if you don't happen to be thinking about patterns in general) as the code doesn't contain an `is` or `as` operator.

I can't immediately think of any pattern match that would be valid for pointer types, so perhaps it would be clearer to make that the error message, even for `is` / `as` operators? ("Pattern matching is not valid on pointer types".) Of course, it's possible that I've misunderstood and there *are* patterns that match pointers, or will be in the future...

**Comment by jcouv** [comment]
FYI @gafter
