### ISSUE TITLE
TODO: move test code out of compilation object

### ISSUE THREAD

**Issue by QwertyZW** [dotnet/roslyn#18736]
https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Compilation/Compilation.cs#L45

https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Compilation/Compilation.cs#L50

**Comment by gafter** [comment]
We don't have any plans to do this.  This code in the product to assist with testing is useful.
