### ISSUE TITLE
Some VisualBasicCodeModelService APIs not handling Declare Function and Sub

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#1873]
`VisualBasicCodeModelService` does not handle Declare Function and Sub in the following APIs
1. `SetType`
2. `InsertParameterIntoContainer`
3. `GetFunctionExtender`

@DustinCampbell @carlos-j-quintero Are these scenarios that we should handle?

**Comment by Pilchie** [comment]
I suspect that at least the first two should work.  Can you look at the VS2013 implementation and see what it did?
