### ISSUE TITLE
Incorrect namespace generated for new files when the project contains special characters

### ISSUE THREAD

**Issue by BattleRush** [dotnet/roslyn#18758]
**Version Used**: 
15.3 (master)
VisualStudio.15.Release/15.1.0+26403.7

**Steps to Reproduce**:

![image](https://cloud.githubusercontent.com/assets/11750584/25103221/fe1e8392-23bb-11e7-9088-11aa851df963.png)

1. Create a project with special characters like " ", -, +, =, (, ), !, .,
2. Add a new .cs file

**Expected Behavior**:
```
using System;
using System.Collections.Generic;
using System.Text;

namespace Debug____Test_2__.net_core________
{
    class Class1
    {
    }
}
```

**Actual Behavior**:
```
using System;
using System.Collections.Generic;
using System.Text;

namespace Debug == Test 2 (.net core) ! -+-+
{
    class Class1
    {
    }
}
```

The initial Program.cs receives the correct namespace, but all new files being added are being generated incorrectly.

Couldn't quite find the event that is creating those files.
I looked into `Microsoft.CodeAnalysis.FileTextLoader` but at that point the file was already written to disk and it's already too late. Could someone point out where I should look to find the correct entry point to debug this issue?

**Comment by Pilchie** [comment]
Tagging @srivatsn @davkean looks like a `roslyn-project-system` issue?

**Comment by BattleRush** [comment]
I was able to reproduce the issue with .Net Core and .Net Standard Projects (Tested with: Console, Lib, Web projects).
.Net Framework projects worked as expected.

Other issue I found is when you add in .Net Core/Standard a new resouce file, the *.Designer.cs file is not being generated, which has a bigger impact than just the namespace name. I assume its strongly linked with the namespace issue.

**Comment by davkean** [comment]
@BattleRush I'll move this over to the project system. The second issue is https://github.com/dotnet/project-system/issues/1521.

**Comment by davkean** [comment]
This issue was moved to dotnet/project-system#2016
