### ISSUE TITLE
Report error rather than warning if [Deprecated] attributes with both Remove and Deprecate

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#18755]
The following reports `warning CS0618: 'C.F()' is obsolete` based on the first `[Deprecated]` attribute rather than `error CS0618: 'C.F()' is obsolete` from the second attribute.
```
using Windows.Foundation.Metadata;
class C
{
    [Deprecated("Removed", DeprecationType.Remove, 0)]
    [Deprecated("Deprecated", DeprecationType.Deprecate, 0)]
    static void F() { }
    static void Main()
    {
        F();
    }
}
```

**Comment by AlekseyTs** [comment]
I believe this is by design, we decided to go with the simple implementation when the support for this attribute was added.
