### ISSUE TITLE
[IOperation] Print lists on newlines

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18752]
See https://github.com/dotnet/roslyn/pull/18698#discussion_r111781374. 

```
IVariableDeclarationStatement (1 declarations) (OperationKind.VariableDeclarationStatement) (Syntax: 'Dim i1 As Integer')
  IVariableDeclaration (1 variables) (OperationKind.VariableDeclaration) (Syntax: 'i1')
    Variables: Local_1: i1 As System.Int32
```
> This doesn't have to fixed right away, but the output would be more readable if the first item was printed on the new line. This applies to all lists.

**Comment by jinujoseph** [comment]
closed via #20716
