### ISSUE TITLE
[IOperation] Should we throw when given a default/empty list for IVariableDeclaration

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18767]
Currently, we check ImmutableArray.IsDefaultOrEmpty when determining isInvalid in the constructor of IVariableDeclaration. Is this the correct behavior? As the compiler is currently implemented, it's theoretically impossible to be passed either a default or empty array, but nothing says that empty might not become valid (especially for otherwise invalid syntax) in the future. Should we be ensuring that default values are swapped for an empty array in the constructor? Should we throw when encountering either of these issues?

**Comment by jinujoseph** [comment]
Is this relevant anymore now that we don't expose IsInvalid through our API?

**Comment by 333fred** [comment]
Nope.
