### ISSUE TITLE
Migrate our internal signed build share to newer storage

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#18764]
Right now we're on the "small and expensive" option for storage, and we should move to the newer storage that's been provisioned.

**Comment by jaredpar** [comment]
What all does this entail?  Curious to understand more.

**Comment by jasonmalinowski** [comment]
@jaredpar Our space today is allocated for us by DevDiv IT, which has different options available for storage which makes tradeoffs of size vs. cost vs. reliability. As Roslyn drops get bigger getting more space on our existing option (which is a "small and highly fast and reliable" option) is proving to be expensive.

This is mostly a process of DevDiv IT allocating a new storage share, moving the files over, and the updating the DFS paths behind the scenes accordingly.

**Comment by jaredpar** [comment]
Do we know if they've enabled file system de-duping on the storage server?  Given the way our drops are structured I imagine that would be a huge savings.

**Comment by johnbeisner** [comment]
The Azure tiered storage wasn't a 'fit' as most of the content is newer; less than a year old. This tiered storage leverages 'archive' type files that are rarely accessed - which doesn't seem to be the case here. .5 TB were added to the current share: \\cpvsbuild\drops\roslyn
