### ISSUE TITLE
Type inference bug?

### ISSUE THREAD

**Issue by sunnycase** [dotnet/roslyn#18770]
**Version Used**:  Visual Studio 2017

**Steps to Reproduce**:

```c#
    public static class NullExt
    {
        public static T? Some<T>(this T? value, Action<T> func) where T : struct
        {
            if (value != null)
                func(value.Value);
            return value;
        }

        public static T Some<T>(this T value, Action<T> func) where T : class
        {
            if (value != null)
                func(value);
            return value;
        }
    }

    class Program
    {
        public static void Main()
        {
            string s = "s";
            s.Some(_ => Console.Write("some"));

            int? i = 1;
            i.Some(_ => Console.Write("some"));
        }
    }
```

**Expected Behavior**:
This code snippet compiles.

**Actual Behavior**:
This code snippet doesn't compiles.
error CS0121: The call is ambiguous between the following methods or properties: “NullExt.Some<T>(T?, Action<T>)” and “NullExt.Some<T>(T, Action<T>)”

Change
```c#
            i.Some(_ => Console.Write("some"));
```
to
```c#
            i.Some<int>(_ => Console.Write("some"));
```
it compiles, So i think it's a type inference bug. What do you think of this?

**Comment by shikimoon** [comment]
It's very helpful to me

**Comment by gafter** [comment]
This is probably not a bug, but a case where https://github.com/dotnet/csharplang/issues/98 would help.
