### ISSUE TITLE
CSharpInteractiveCommands.VerifyPreviousAndNextHistory failed a VSI run

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#18779]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/2722/

```
MESSAGE:
Assert.Equal() Failure\r\n ↓ (pos 1)\r\nExpected: 1 + 2\r\nActual: 1.ToString()\r\n ↑ (pos 1)
+++++++++++++++++++
STACK TRACE:
at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractiveCommands.VerifyPreviousAndNextHistory() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpInteractiveCommands.cs:line 30
```

**Comment by tmat** [comment]
@ivanbasov

**Comment by ivanbasov** [comment]
This method was implemented long ago and still relies on Wait(seconds: 1); between commands. We should not use this and replace with WaitFor (some event).

@tannergooding or I can help with porting it.

**Comment by JoeRobich** [comment]
Saw this again: [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=125084&view=ms.vss-test-web.build-test-results-tab)

**Comment by JoeRobich** [comment]
Saw this again: [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=128138&view=ms.vss-test-web.build-test-results-tab)

```
Assert.Equal() Failure\r\n ↓ (pos 1)\r\nExpected: 1 + 2\r\nActual: 1.ToString()\r\n ↑ (pos 1)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.InteractiveWindow_OutOfProc.Verifier.LastReplInput(String expectedReplInput) in /_/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/InteractiveWindow_OutOfProc.Verifier.cs:line 25
   at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractiveCommands.VerifyPreviousAndNextHistory() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpInteractiveCommands.cs:line 32
```

![03 03 43-CSharpInteractiveCommands VerifyPreviousAndNextHistory-EqualException](https://user-images.githubusercontent.com/611219/54660929-8ac10980-4a95-11e9-85a0-5814a6229530.png)

**Comment by ryzngard** [comment]
Saw again: [test logs](https://dev.azure.com/dnceng/public/_build/results?buildId=265993&view=ms.vss-test-web.build-test-results-tab&runId=7239306&resultId=100026&paneView=debug)

**Comment by ryzngard** [comment]
Saw again: [test logs](https://dev.azure.com/dnceng/public/_build/results?buildId=288052&view=ms.vss-test-web.build-test-results-tab&runId=8096226&resultId=100014&paneView=debug)

**Comment by ryzngard** [comment]
Saw again: [test logs](https://dev.azure.com/dnceng/public/_build/results?buildId=289677&view=ms.vss-test-web.build-test-results-tab&runId=8158224&resultId=100026&paneView=debug)

**Comment by JoeRobich** [comment]
Adding Skip for this test until it can be made to be more reliable - https://github.com/dotnet/roslyn/pull/37774
