### ISSUE TITLE
Intellisense hard selection when backspacing needs to be conditioned on match quality

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#18785]
New VB project:
``` VB
Dim x = new List(Of String)()
x.$$Add("")
```

Type backspace and then `.`. `x` replaces `xAdd` because we do a hard selection. We should soft select because the new filtertext is not a prefix match of anything.

**Comment by Pilchie** [comment]
@rchande can you link the Developer Community issue that inspired this?
