### ISSUE TITLE
Optimization: Passing static method as Action parameter should no allocate

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#18780]
In the code below, compare the two methods of passing `StaticMethod` to `F`.
Calling with a lambda generates a lazy singleton `Action`, but calling with the method creates a new `Action` on every call. 
It seems the former would be more efficient, but to get that behavior, users have to type extra glue code. 
That is even more pronounced for the scenario where the static method takes parameters (passing into a method that accepts `Func<...>`).

```C#
class C
{
    static void StaticMethod() { }
    void F(System.Action a) { }
    void M()
    {
        // compare the following two methods of passing StaticMethod to F
        // F(() => StaticMethod());
        // F(StaticMethod);
    }
}
```

```C#
// decompiled code for F(() => StaticMethod());
internal class C
{
    [CompilerGenerated]
    [Serializable]
    private sealed class <>c
    {
        public static readonly C.<>c <>9;
        public static Action <>9__2_0;
        static <>c()
        {
            // Note: this type is marked as 'beforefieldinit'.
            C.<>c.<>9 = new C.<>c();
        }
        internal void <M>b__2_0()
        {
            C.StaticMethod();
        }
    }
    private static void StaticMethod()
    {
    }
    private void F(Action a)
    {
    }
    private void M()
    {
        Action arg_21_1;
        if (arg_21_1 = C.<>c.<>9__2_0 == null)
        {
            arg_21_1 = C.<>c.<>9__2_0 = new Action(C.<>c.<>9.<M>b__2_0);
        }
        this.F(arg_21_1);
    }
}
```

```C#
// decompiled code for F(StaticMethod);
internal class C
{
    private static void StaticMethod()
    {
    }
    private void F(Action a)
    {
    }
    private void M()
    {
        this.F(new Action(C.StaticMethod));
    }
}
```

FYI @CyrusNajmabadi @cston

**Comment by CyrusNajmabadi** [comment]
I would love to have this. I think we even have a PR on this.  I think what's holding it back are open questions about security contexts and how they are captured.

**Comment by jcouv** [comment]
You're right. Found https://github.com/dotnet/roslyn/pull/6642 which points to existing issue https://github.com/dotnet/roslyn/issues/5835 (opened by @gafter).

I'll resolve OP as duplicate then.
