### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorList [FAIL]

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#18789]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/2802/

**Comment by Pilchie** [comment]
@srivatsn @jinujoseph Which area is the right one for this issue?

**Comment by srivatsn** [comment]
Project System. I\ll move it.

**Comment by srivatsn** [comment]
This issue was moved to dotnet/project-system#2023
