### ISSUE TITLE
CS0306ERR_BadTypeArgument01 is failing on 32bit jenkins runs.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#18800]
On 32bit it reports this error:

EXEC : // error CS1685: The predefined type 'ExtensionAttribute' is defined in multiple assemblies in the global alias; using definition from 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' 

But on 64bit it does not.

**Comment by CyrusNajmabadi** [comment]
This was fixed with @agocke 's change.

**Comment by CyrusNajmabadi** [comment]
Opening because we do need to unskip the test.

**Comment by sharwell** [comment]
@CyrusNajmabadi AFAICT the change to skip the test was never merged. Can this be closed?

**Comment by jaredpar** [comment]
Closing as there doesn't appear to be a skipped test here. At least I couldn't find one with the tracking ID 18800.
