### ISSUE TITLE
Define expected behavior for simultaneous install of NuGet and VSIX analyzers

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#18818]
## Scenario

This issue involves defining the expected behavior when all of the following conditions are met:

* The IDE has an analyzer installed as a VSIX which reports diagnostic *D*
* A project has an analyzer installed via NuGet (or more generally, as an `<Analyzer>` reference) which reports diagnostic *D*

### Analyzers

Diagnostics reported by analyzers are evaluated according to their diagnostic ID, as obtained through the `SupportedDiagnostics` property. If a project has a NuGet-installed analyzer which reports diagnostic *D*, then results filtering will be applied such that diagnostic *D* is never reported for this project by a VSIX-installed analyzer.

:memo: The comparison is performed on individual diagnostic IDs in order to support several scenarios expected to arise over time:

* A VSIX-installed analyzer supports diagnostics *A*, *B*, and *C*. Diagnostic *B* is later provided through NuGet to allow its use during command-line builds. Both packages should be used, where results of *B* are displayed only from the NuGet-installed analyzer while *A* and *C* continue to be displayed from the VSIX-installed analyzer.
* The assembly identity is generally irrelevant for determining the source of a diagnostic. Analyzer assemblies may be freely renamed, split, merged, etc., and/or change any other identity property without changing the expected behavior for the scenario described in this issue.

⚠️ The filtering does not necessarily mean that the VSIX-installed analyzer which reports diagnostic *D* will not run. If one VSIX-installed analyzer instance reports *A* and *B*, while the NuGet-installed analyzer instance only reports *B*, the VSIX-installed analyzer which reports *B* will still run (so diagnostic *A* is gathered), but all reports of *B* from the VSIX-installed analyzer will be filtered from the result before displaying it to users.

### Code Fixes

For each reported (non-filtered per the previous step) instance of diagnostic *D*, code fixes from both NuGet-installed analyzers and VSIX-installed analyzers are gathered in this scenario. Code actions are compared by their equivalence key. In the event one or more code actions with equivalence key *E* are provided by the NuGet-installed analyzers, all code actions provided by VSIX-installed analyzers with equivalence key *E* will be ignored.

:memo: It's important to consider code actions provided by both NuGet- and VSIX-installed analyzers even in scenarios where the diagnostic is reported by a NuGet-installed analyzer. It is possible that a user installs a VSIX-installed code fix specifically to improve their IDE experience (e.g. by adding new options to the fixes provided by the NuGet-installed analyzers). Use of a NuGet-installed analyzer should not preclude this scenario.

:warning: Note that the specific omission of code actions provided by VSIX-installed analyzers is important when an equivalence key duplication is identified. Since it is possible for the NuGet-installed and VSIX-installed analyzers to be different versions of the same analyzer assembly, we cannot expect code actions from a VSIX-installed analyzer to understand the diagnostic details provided by a NuGet-installed analyzer. We favor the code actions provided by the NuGet-installed analyzer with the assumption that the analyzer and fixer provided through NuGet understand each other.

**Comment by Pilchie** [comment]
Tagging @jasonmalinowski @kuhlenh @jinujoseph @mavasani.

**Comment by Pilchie** [comment]
Note that this wasn't the original intended use of `EquivalenceKey`.  It isn't immediately clear to me that overloading it in this way is sufficient.

**Comment by sharwell** [comment]
@Pilchie It fits in line with the interpretation of equivalence key that we thought was correct when creating StyleCop Analyzers. We treated it as a value that indicates whether two arbitrary code fixes provided to the system represent "doing the same thing" or "not doing the same thing". Thus, if two code actions were "doing the same thing" and one was provided by NuGet-installed analyzer while the other was provided by a VSIX-installed analyzer, we use the one provided by the NuGet-installed analyzer.

**Comment by heejaechang** [comment]
analyzer and code fix are originally designed to be not coupled. so I think we can think those cases separately.

also, for analyzers, our original design was multiple analyzers can report same diagnostic ID which might not overstepping each other. which even ourselves do to cover cases where compiler won't report diagnostics for code fix such as missing type or member for invalid code.

due to that, we introduced a concept of analyzer identity. basically, we said if we have 2 analyzers (whatever  diagnostics they are producing), if 2 has same identity, we consider 2 are same. at the time, it was used to do de-duplication (same analyzer being installed by vsix and nuget package) but we didn't though about versioning.

I thought what @Pilchie suggested was what we were going to do.

if 2 analyzers have same identity (one from vsix and nuget), we always choose one from nuget packages since it was the explicit one from users (part of project)

and that goes same for code fixer.

**Comment by heejaechang** [comment]
oh. forgot to add. current default analyzer identity implementation include version, but suggestion was taking that out. so if 2 analyzer return same identity (might be 2 different versions of same logical analyzers), we always take one from nuget packages (same for both analyzers and code fixer)

**Comment by sharwell** [comment]
@heejaechang I'm not sure what specifically it means for two analyzers to have the same identity. I am assuming that it contains some number of the following:

1. The fully-qualified name of the analyzer type
2. The containing assembly name
3. Some subset of other properties that make up the assembly identity (publickeytoken, culture, version, etc.)

In any combination, the above place requirements on analyzer authors which produce an unnecessarily poor development/migration experience. For example:

1. They do not allow an analyzer type to *ever* be renamed, or in mismatched version scenarios a NuGet- and VSIX-installed analyzer could start producing duplicate results
2. They do not allow an analyzer to be partially migrated to NuGet (some IDs produced by the analyzer now supported by NuGet, but others not)
3. They do not allow an analyzer which reports multiple IDs to be easily split into one analyzer for each ID
4. In some configurations, it allows both a NuGet-installed analyzer and a VSIX-installed analyzer to report the same diagnostic ID while working in the IDE. When some of these items are missing during a build, users will naturally assume that the missing items represent a bug in the analyzer implementation - while this may be the case depending on scenario, it could prove very difficult to track down the reason for this behavior in real-world scenarios.

I believe the original concept of analyzer identity, even if modified to relax its requirements, will prove insufficient to address the needs of NuGet and VSIX distribution, which is why I've proposed a new de-duplication strategy that I believe substantially reduces the likelihood users will see unexpected results.

**Comment by heejaechang** [comment]
I believe identity is actually defined in AnalyzerReference not not DiagnosticAnalyzer itself. we can make author to define some assembly attribute that our AnalyzerFileReference will pick up and report as identity.

anyway, the identity is created so that author can define what are logically same analyzers (file). the scenario we were thinking was

same analyzers (file) installed for both vsix and nuget. 

but also, wanted to use for a case such as author updating same analyzers (file) to newer version.

the identity is not on each analyzers since actual thing author give users is a file. sure that has its own limitation, but didn't want to make things too complex for 1% cases.

...

for your particular question, having duplicated diagnostics because one installed vsix analyzer package A that will produce diagnostic A from analyzer A from a file A and nuget analyzer package B that will produce diagnostic A from analyzer A from a file B

I think this is a corner case and we should not try to fix this issue. user can see where the diagnostics comes from error list with source column. and remove one of them. I believe the author is the one who need to fix this.

the supported case I think should be vsix analyzer package A producing diagnostic A from analyzer A from a file A. and nuget analyzer package B producing diagnostic A from analyzer A from a file A (or modified version of A)

I think we should try to provide best practice for scenario and add support for such scenario rather than trying to support all difference variations and make code too complex.

**Comment by sharwell** [comment]
@heejaechang Aside from the fact that it would take more work to implement, are there any tenet-impacting technological barriers to adopting the approach I described (e.g. inability to meet compatibility, performance, or usability goals)?

I'm trying to separate the various items mentioned in this topic into items which are mostly self-impacting (e.g. amount of work it takes to implement) and those that are user-impacting (e.g. are users encountering scenarios they can't explain). So far I have interpreted most of your items to be self-impacting, where you are focused on providing a sufficient experience without over-complicating the development work in ways that extend timelines and/or increase the likelihood of bugs getting released. And with that view, the approach currently in place is much closer to behaving in the manner you described while it would take substantial work to change to the approach I was proposing.

**Comment by heejaechang** [comment]
the very  first issue will be 2 analyzers are currently allowed to report same diagnostic ID I believe.

**Comment by jasonmalinowski** [comment]
> A VSIX-installed analyzer supports diagnostics A, B, and C. Diagnostic B is later provided through NuGet to allow its use during command-line builds. Both packages should be used, where results of B are displayed only from the NuGet-installed analyzer while A and C continue to be displayed from the VSIX-installed analyzer.

Your proposal does fix the assembly flakiness you're worried about, at the cost of different flakiness:

1. Version 1.0 of a package reports a bunch of issues as A.
2. Users of this package complain that having A as the code for everything is annoying.
3. Version 2.0 of the package reports some of those issues as B or C, with no change to the logic of when/where it reports.

If the team has 1.0 installed, and somebody on the team wants to try out 2.0, with this algorithm won't they get a bunch of duplicates with A being reported from 1.0 and also B and C being reported from 2.0? I suspect that'll be really confusing. I agree people would expect that assembly identity changing shouldn't break scenarios like this, but I'm not sure my proposed scenario is any less 'expected' to work.

It's probably a good heuristic in absence of anything else, but I suspect we're going to have to look at expressing some NuGet identity concepts or some other metadata at some point. In the past we've discussed this we also wanted to have some sort of button for "I have this VSIX installed, now I want an install NuGet package" button which _definitely_ had to know package metadata. I don't know where that thought leads us.

**Comment by heejaechang** [comment]
I just want it to be not too complex and only expert can understand what eventually gets picked up as analyzers/fixers just to cover all corner cases.

my suggestion was when vsix and nuget provide same file or updated version of the file (that has analyzers/fixers) then, one from nuget package always win (one that explicitly added as analyzer reference in project file)

simple and straight forward.

...

implementation wise, we make engine to prefer one from nuget package rather than vsix. and remove versions from analyzer file identity.

**Comment by sharwell** [comment]
@jasonmalinowski NuGet currently does not allow you to install two different versions of the same package in a project at the same time. In your scenario, upgrading to 2.0 would eliminate the reports from 1.0 at minimum in the specific project. The only time it would be a problem would be if the analyzer authors create multiple package IDs and a user installs more than one of them - but this issue is already a problem for all kinds of NuGet packages so there's nothing unique about analyzers to care about specifically.

**Comment by sharwell** [comment]
@heejaechang The approach is "simple and straightforward", but it blocks all of our proposed migration strategies for getting code style analyzers into the build. Most, if not all, of the limitations with the strategy which I mentioned earlier are concrete examples of problems that I suspect will appear during this work.

> the very first issue will be 2 analyzers are currently allowed to report same diagnostic ID I believe.

Under the new plan, multiple analyzers will still be allowed to report the same diagnostic ID. The only limitation will be all such analyzers for a particular ID must either be specified in the project (analyzer references added e.g. through NuGet) or in the environment (e.g. analyzers installed via VSIX). You would not be allowed to mix installation strategies *for a single diagnostic*, which is a necessary design both to eliminate confusion and to provide flexibility for teams trying to move analyzers from VSIX to NuGet.

> I think these are cases where author need to fix the issue.

I'm trying to avoid all these cases where users report a problem and then the author has to take some action to fix some subtle detail relating to some new notion of "analyzer identity". At best it will be a frustration, and at worst we'll hit cases where we don't have time to address the identity issues and have to delay a feature release over it. The proposal I gave is more likely to result in user behavior independently of the specific long-term development strategies various analyzer authors choose to work under. In other words, it is intentionally robust to varied decisions made by analyzer developers *naive to the way the diagnostic driver works*.

**Comment by heejaechang** [comment]
@sharwell how users would know what is going on? allowing 2 different analyzers to report same diagnostic ID except vsix one is just confusing.

when moving vsix analyzers to nuget analyzer, asking users to update vsix and install nuget is I am not sure why so bad and needed to be avoided. it is one time thing and users need to update vsix at one point anyway. and this is intermediate issue. 

anyway, I expressed my preference. let's see how other think.

**Comment by jasonmalinowski** [comment]
@sharwell I missed one clarification in my example: 1.0 was coming from NuGet, 2.0 was coming from VSIX.

**Comment by Pilchie** [comment]
Assigning to @kuhlenh to drive to a decision here, and so that it's out of my triage query.

**Comment by sharwell** [comment]
@jasonmalinowski My proposal is agnostic to the version numbers.

1. If the version numbers (`[AssemblyVersion]`) are the same and the content of the assemblies is the same, then it doesn't matter which one loads because they both behave the same.
2. If the version numbers are the same and the contents of the assemblies differ, then even if we request a particular one the CLR might give us the other one. In this case the in-IDE experience may end up using the VSIX-installed analyzer behavior even in a project that has the analyzer installed through NuGet, but this is a runtime limitation.
3. If the version numbers differ, then the NuGet-installed analyzer is used regardless of which one has the higher version number.

**Comment by jasonmalinowski** [comment]
@sharwell Exactly. :smile: My point is that if I have a different version (higher, lower, sideways, whatever) that uses different diagnostic IDs for the same issues I believe your proposal runs into issues. I used versions as a motivating example why people might change.

**Comment by Pilchie** [comment]
Sadly, this editorconfig work isn't going to fit for 15.3, but we're going to continue targeting the next foundation update.

**Comment by dpoeschl** [comment]
Unfortunately, we need to move this editorconfig work to the next foundation update.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/41687
