### ISSUE TITLE
Define expectations for non-EditorConfig option storage

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#18817]
While **.editorconfig** is being developed as a flexible source of options for analyzer authors, there are other options sources currently in use that will need to be preserved if we don't want users to face breaking changes. Since independently-implemented options sources (e.g. stylecop.json used by StyleCop Analyzers) are not affected by any of the proposed .editorconfig changes, they do not need to be considered. Two main sources of options which are currently provided to analyzers are:

* `LocalUserProfileStorageLocation`
* `RoamingProfileStorageLocation`
* MSBuild storage location (doesn't exist, but could be implemented to support #18326)
* Rule set files (in the event we unify the API experience for setting diagnostic severities)

If #18392 is accepted, presumably an analyzer assembly simultaneously distributed as a NuGet package and a VSIX would be able to define options which reference these storage locations.

### Expectations

To ensure the build experience matches the IDE experience, it's important that analyzers enabled at build time (i.e. analyzers installed into projects via NuGet) behave as though IDE settings are not provided, even when running inside the IDE. 

#### Example

In this example, assume **My.Analyzers.dll** is installed in Visual Studio as a VSIX, and a solution with the following projects is opened.

* Project A
  * My.Analyzers.dll installed via NuGet
* Project B
  * No analyzers installed via NuGet

When analyzing Project B, the options observed by analyzers in My.Analyzers.dll will see all available options, including options defined in the `LocalUserProfileStorageLocation` and `RoamingProfileStorageLocation` storage locations provided by the IDE. However, when analyzing Project A, the options observed by analyzers in My.Analyzers.dll will only see options which are available for command line builds. This includes .editorconfig options as well as MSBuild properties (if supported) and rule set files (if supported), but explicitly and intentionally omits the storage locations which are provided by the IDE.

**Comment by Pilchie** [comment]
Tagging @jasonmalinowski @kuhlenh @jinujoseph @mavasani.

**Comment by jasonmalinowski** [comment]
What is our plan to mitigate confusion here? Is a message in Tools > Options saying "settings are being overridden in these projects by .editorconfig" or something sufficient?

**Comment by kuhlenh** [comment]
@jasonmalinowski I think that would work.

**Comment by jasonmalinowski** [comment]
And as far as what to do with `RoamingProfileStorageLocation`, I believe the appropriate thought experiment to do is "what would roaming settings between Visual Studio and Visual Studio Code look like?" The type intentionally didn't have "Visual Studio" anywhere in the name, namespace, or comments to imply this might be the intent. There's still host-specific behavior to actually provide a UI _for_ that option, but you could imagine (or not imagine) settings roaming to VS Code even if there wasn't UI to set it if I installed a newer package.

@sharwell: does anything we'd ever consider moving to nuget use `LocalUserProfileStorageLocation`? Much of those were largely for internal switches for perf testing, or giving customers workarounds/kill switches for things, etc. Not something that analyzers should be consuming in the first place.

**Comment by Pilchie** [comment]
Sadly, this editorconfig work isn't going to fit for 15.3, but we're going to continue targeting the next foundation update.

**Comment by dpoeschl** [comment]
Unfortunately, we need to move this editorconfig work to the next foundation update.

**Comment by CyrusNajmabadi** [comment]
This work should just be done.  A tracking issue untouched for 7 years doesn't help us.
