### ISSUE TITLE
IOperation API shape for DelegateCreationExpression

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#18839]
```
using System;

public class NeatCode
{
    // Used parameter methods
    public void UsedParameterMethod1(Action a)
    {
        Action a2 = new Action(() =>
        {
            a(); // No parameter reference expression operation generated for this access
        });
    }
}
```

```
IOperation tree for "new Action(() =>
        {
            a(); // No parameter reference expression operation generated for this access
        })"

IMethodBindingExpression: null (Static) (OperationKind.MethodBindingExpression, Type: System.Action) (Syntax: '() => ... }')
```

BoundDelegateCreationExpression implements IMemberBindingExpression, but there is no API that exposes it's argument. Hence we receive no IOperation callbacks for anything inside a delegate creation expression.

**Comment by jinujoseph** [comment]
workaround https://github.com/dotnet/roslyn/pull/19307

**Comment by 333fred** [comment]
See https://github.com/dotnet/roslyn/pull/20026#discussion_r120241416 for some C#/VB parity considerations.

**Comment by 333fred** [comment]
This is another point of inconsistency between VB and C#. In the above example, the lambda expression has a type of null, and a converted type of Action. However, in the VB equivalent code
```VB
Sub M1()
    Dim a = New Action(Sub()
                                      End Sub)
End Sub
```
the multiline lambda expression has a type of Nothing and a converted type of Nothing.

**Comment by 333fred** [comment]
Related to https://github.com/dotnet/roslyn/issues/20095.

**Comment by 333fred** [comment]
The discussion and proposed API have been happening in https://github.com/dotnet/roslyn/issues/20095, so I'm going close this and track with that issue.
