### ISSUE TITLE
Get offered refactorings for a lambda argument  within the body of the lambda itself

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#18848]
I've got a compiler error because GetActiveConfiguredProjectsMapAsync is obsolete, dropping the light bulb shows a fix that has nothing even to do with the line I'm on:

![image](https://cloud.githubusercontent.com/assets/1103906/25213342/6aefcfe4-25d3-11e7-8ccb-bdb3860eea38.png)

Is it deliberate that the refactoring that applies only to the line where the lambda is passed as an argument, applies to the entire lambda body?

**Comment by davkean** [comment]
here's an example:

``` C#
using System;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Lamda(async () =>
            {
























                Console.WriteLine("Foo"); // <-- Why am I getting offered a bunch of unrelated refactorings here?
                
            });
        }

        public static void Lamda(Func<Task> asyncMethod)
        {

        }
    }
}
````

![image](https://cloud.githubusercontent.com/assets/1103906/25213648/5cdd3afc-25d5-11e7-93b5-04706479e0b1.png)

**Comment by CyrusNajmabadi** [comment]
> Is it deliberate that the refactoring that applies only to the line where the lambda is passed as an argument, applies to the entire lambda body?

No.

**Comment by davkean** [comment]
@CyrusNajmabadi I see you fixed named parameter one, but not the others (see the other examples in the last image).

**Comment by CyrusNajmabadi** [comment]
Filed https://github.com/dotnet/roslyn/issues/19007 about being offered the 'make async' fix.  

The issue with use-expression-body is known and was something we were going to fix a part of work we're doing with the editor team.  However, i can't find a specific issue for this, so i also filed https://github.com/dotnet/roslyn/issues/19008 to track it explicitly.
