### ISSUE TITLE
Missing hidden sequence point emitted an embedded statement of using statement

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#18844]
VSO bug [390881](https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems?_a=edit&id=390881)

```C#
class C
{
    bool F()
    {
        bool x = true;
        bool value = false;
        using (var stream = new System.IO.MemoryStream())
            if (x)
            {
                value = true;
            }
            else
                value = false;

        return value;
    }
}
```

```IL
.try
  {
    // sequence point: if (x)
    IL_000b:  ldloc.0
    IL_000c:  stloc.3
    // sequence point: <hidden>
    IL_000d:  ldloc.3
    IL_000e:  brfalse.s  IL_0016
    // sequence point: {
    IL_0010:  nop
    // sequence point: value = true;
    IL_0011:  ldc.i4.1
    IL_0012:  stloc.1
    // sequence point: }
    IL_0013:  nop
    IL_0014:  br.s       IL_0018
    // sequence point: value = false;
    IL_0016:  ldc.i4.0
    IL_0017:  stloc.1
    // sequence point: <hidden>                         // not emitted
    IL_0018:  leave.s    IL_0025
  }
  finally
  {
   ...
  }
```

Debugger steps onto the else branch even though it's not executed:

![image](https://cloud.githubusercontent.com/assets/41759/25209772/f6d34588-2531-11e7-8e65-e35e542236ec.png)

See skipped test ```PDBTests.UsingStatement_Embedded```

**Comment by tmat** [comment]
@jcouv Similar to the bug you fixed recently. Wanna take it?

**Comment by jcouv** [comment]
Sure.
For reference, the previous fix for sequence point in `if` is https://github.com/dotnet/roslyn/pull/16803
This new case looks so similar, I don't understand how it wasn't covered by that fix. Mysterious.

**Comment by tmat** [comment]
Thanks. Assigned the VSO bug to you as well, to let the customer know when fixed.

**Comment by sharwell** [comment]
Sometimes I don't know what's worse, the bug, or the fact that someone wrote code that exhibited the bug. 😆

**Comment by jcouv** [comment]
While I'm in there, I'll add a test for Cyrus's similar scenario (which is likely fixed already): https://github.com/dotnet/roslyn/issues/17076
