### ISSUE TITLE
NullReferenceException when switching on enum with type pattern match

### ISSUE THREAD

**Issue by madelson** [dotnet/roslyn#18859]
**Version Used**: 

C# 7 (VS2017 install from 2017-04-20)

**Steps to Reproduce**:

```
switch (StringSplitOptions.RemoveEmptyEntries)
{
	case object o:
		Console.WriteLine(o);
		break;
}
```

**Expected Behavior**: Prints "RemoveEmptyEntries"

**Actual Behavior**: Throws NullReferenceException

Stack Trace:
>    at System.IO.TextWriter.SyncTextWriter.WriteLine(Object value)
   at System.Console.WriteLine(Object value)

NOTE: I found [this issue](https://github.com/dotnet/roslyn/issues/9131) which seems similar, but the example code there runs fine for me.

**Comment by 0xd4d** [comment]
It's because the value isn't boxed by the compiler, i.e., a non-boxed `1` is passed to `WriteLine(object)`

**Comment by madelson** [comment]
@0xd4d yeah I got different things with slight tweaks in different contexts. LinqPad consistently gave me NRE, but NUnit would crash on the code above and change to NRE if I switched it to:

```
Console.WriteLine(o.GetHashCode());
```

**Comment by gafter** [comment]
@madelson Can you please provide a more complete repro, including a Main?

**Comment by madelson** [comment]
@gafter do you mean uploading a full solution? The repro I gave runs standalone in LinqPad.

Here's a version for a console app:

```
namespace Repro
{
public class Program
{
	public static void Main()
	{
		switch (System.StringSplitOptions.RemoveEmptyEntries)
		{
			case object o:
				System.Console.WriteLine(o);
				break;
		}
	}
}
}
```

**Comment by gafter** [comment]
This may be a dup of the already fixed https://github.com/dotnet/roslyn/issues/17281.

**Comment by gafter** [comment]
No, I see that this is a runtime failure of the compiled program.

**Comment by gafter** [comment]
The generated code is missing a `box` operation.
