### ISSUE TITLE
Productivity: IntelliSense should provide values in configuration files (app.config/appsettings.json)

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/roslyn#18866]
In projects that have an app.config file (web.config too) or appsettings.json, those values should be available in API's that use those values (ConfigurationManger), GetSection, etc. Much easier to prevent typos when reading configuration data in code.

/cc @Pilchie

**Comment by Pilchie** [comment]
@onovotny - good thing our completion API is extensible so that people who provide those values can write providers :)

**Comment by CyrusNajmabadi** [comment]
Closing out.  Roslyn doesn't own the experience for these files.  The respective teams that do control this could consider adding lsp servers to improve their experience there.
