### ISSUE TITLE
C# produces wrong IL when adding int and pointer

### ISSUE THREAD

**Issue by tarekgh** [dotnet/roslyn#18871]
@tarekgh commented on [Tue Feb 14 2017](https://github.com/dotnet/coreclr/issues/9591)

When enabling the overflow/underflow compiler flag, there is a case when JIT generate wrong code. basically we have a method 

```C#
        internal unsafe void AdjustBytes(int count)
        {
            _bytes += count;
        }
```

in the file 
https://github.com/dotnet/corefx/blob/10733b7bb84d6132f4ac6fd83f3405f3ebd689a6/src/System.Text.Encoding.CodePages/src/System/Text/EncodingCharBuffer.cs#L91

When compiling with overflow flag on, the jit will produce the following 

```
00007FFF46E67D50  push        rbp  
00007FFF46E67D51  push        rdi  
00007FFF46E67D52  push        rsi  
00007FFF46E67D53  sub         rsp,30h  
00007FFF46E67D57  mov         rbp,rsp  
00007FFF46E67D5A  xor         eax,eax  
00007FFF46E67D5C  mov         qword ptr [rbp+28h],rax  
00007FFF46E67D60  mov         qword ptr [rbp+50h],rcx  
00007FFF46E67D64  mov         dword ptr [rbp+58h],edx  
00007FFF46E67D67  cmp         dword ptr [7FFF46DFB728h],0  
00007FFF46E67D6E  je          00007FFF46E67D75  
00007FFF46E67D70  call        00007FFFA65B0EB0  
00007FFF46E67D75  nop  
            _bytes += count;
00007FFF46E67D76  mov         rax,qword ptr [rbp+50h]  
00007FFF46E67D7A  mov         edx,dword ptr [rbp+58h]  
00007FFF46E67D7D  mov         edx,edx  
00007FFF46E67D7F  add         rdx,qword ptr [rax+48h]  
00007FFF46E67D83  jae         00007FFF46E67D8A  
00007FFF46E67D85  call        00007FFFA65AFBD0  
00007FFF46E67D8A  mov         rax,qword ptr [rbp+50h]  
00007FFF46E67D8E  mov         qword ptr [rax+48h],rdx  
        }
00007FFF46E67D92  nop  
00007FFF46E67D93  lea         rsp,[rbp+30h]  
00007FFF46E67D97  pop         rsi  
00007FFF46E67D98  pop         rdi  
00007FFF46E67D99  pop         rbp  
00007FFF46E67D9A  ret  
````

you can notice the operations neglect the sign. so if someone pass negative number to the method we'll end up with wrong result. if we compile with overflow flag off, JIT produce the following right code:

```

00007FFF46E877B0  push        rbp  
00007FFF46E877B1  push        rdi  
00007FFF46E877B2  push        rsi  
00007FFF46E877B3  sub         rsp,30h  
00007FFF46E877B7  mov         rbp,rsp  
00007FFF46E877BA  xor         eax,eax  
00007FFF46E877BC  mov         qword ptr [rbp+28h],rax  
00007FFF46E877C0  mov         qword ptr [rbp+50h],rcx  
00007FFF46E877C4  mov         dword ptr [rbp+58h],edx  
00007FFF46E877C7  cmp         dword ptr [7FFF46E1B728h],0  
00007FFF46E877CE  je          00007FFF46E877D5  
00007FFF46E877D0  call        00007FFFA65B0EB0  
00007FFF46E877D5  nop  
            _bytes += count;
00007FFF46E877D6  mov         eax,dword ptr [rbp+58h]  
00007FFF46E877D9  movsxd      rax,eax  
00007FFF46E877DC  mov         rdx,qword ptr [rbp+50h]  
00007FFF46E877E0  add         qword ptr [rdx+48h],rax  
        }
00007FFF46E877E4  nop  
00007FFF46E877E5  lea         rsp,[rbp+30h]  
00007FFF46E877E9  pop         rsi  
00007FFF46E877EA  pop         rdi  
00007FFF46E877EB  pop         rbp  
00007FFF46E877EC  ret  
```

to repro the issue, on corefx repo do the following:

- enable compiling with overflow flag by doing the change mentioned in the following line https://github.com/dennisdietrich/corefx/blob/private/Unchecked/dir.props#L169
- remove the uncheck from the line https://github.com/dotnet/corefx/blob/10733b7bb84d6132f4ac6fd83f3405f3ebd689a6/src/System.Text.Encoding.CodePages/src/System/Text/EncodingCharBuffer.cs#L91
- build the repo (from the root folder run build.cmd)
- go to the folder src\System.Text.Encoding.CodePages\tests then build and run using the command msbuild /t:rebuildandtest

you'll get one test failed because of the wrong code generated for the AdjustBytes method in the library System.Text.Encoding.CodePages

https://github.com/dotnet/corefx/pull/16160

---

@tarekgh commented on [Tue Feb 14 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-279870624)

CC @russellhadley 

---

@mikedn commented on [Tue Feb 14 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-279930716)

Is this really a JIT bug? Or is it a C# compiler bug and/or messed up CIL spec?

The IL code looks like:
```
IL_0001:  ldarg.0
IL_0002:  ldfld      uint8* Program/Bar::p
IL_0007:  ldarg.1
IL_0008:  add.ovf.un
```
On 64 bit this means that the addition operation has mismatched operand types - `long` and `int`. For better or worse the CIL spec allows this but it's not very clear how the smaller operand should be widened.

The description of `add.ovf.un` says 
>Add unsigned integer values with overflow check.

so it seems that the smaller operand should be zero extended and that's exactly what the JIT does.

But it can be argued that the `.un` part of `add.ovf.un` affects only the overflow check and that the JIT should always sign extend the `int32` value that's on the stack. And what happens if you want to add an `uint` to a pointer? Well, you have to insert a `conv.u` and that's exactly what the C# compiler does.

So the C# compiler and the JIT compiler seem interpret the spec differently. Conclusion: the spec is flawed :)

---

@stephentoub commented on [Wed Feb 15 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-280029419)

cc: @jaredpar

---

@jaredpar commented on [Wed Feb 15 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-280051567)

CC @VSadov, @jcouv 

---

@VSadov commented on [Wed Feb 15 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-280075467)

![image](https://cloud.githubusercontent.com/assets/8218165/22986690/37a01634-f361-11e6-8d39-f1851d90bd7b.png)

---

@mikedn commented on [Wed Feb 15 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-280076128)

@VSadov It's not a native int/native int case, it's an int32/native int case.

---

@VSadov commented on [Wed Feb 15 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-280079464)

@mikedn - yes, that is correct.    `checked( nint + int32 )`  is a valid operation

---

@mikedn commented on [Wed Feb 15 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-280080800)

@VSadov Ah, you highlighted the results. But this is about the operands. `checked(nint + int32)` is a valid operation but it's not clear how that `int32` is to be widened to `nint`. The JIT assumes it is unsigned and zero extends while the C# compiler assumes that it is signed and so it will be sign extended.

---

@tannergooding commented on [Wed Feb 15 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-280086140)

I agree, I think the spec is flawed here. Currently it indicates that all unmanaged pointers are `unsigned native int` and that `int32` is zero extended to become `unsigned native int`.

However, when dealing with `native int op int32`, this means that addition and subtraction will be incorrect on 64-bit platforms.

What should be happening here is that `int32` is coerced into `native int` of the same sign and then the operation should be executed (so `int32` would be sign extended and `unsigned int32` would be zero extended).

---

@VSadov commented on [Wed Feb 15 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-280104210)

implicit conversion from `int32` to `nint` should always sign-extend.
CLI, itself, does not track unsigned types, it knows only `int32, int64, nint, F, & and O`

Obviously, `int32` must become a `nint` before `add.ovf.un` or any kind of `add` can be performed.

`un` in `ovf.un` suffix does not specify the operand types of `add`, has nothing to do with operands really, it just specifies how overflow is determined in two's-complement math - CF vs. OF.

Basically we start with _signed_ `int32` and `nint` and the result of the operation is `nint` with a guarantee that the carry flag was not set while adding.
I do not see how 0-extending would be involved.

The spec is not vague about this, but is admittedly terse and relevant pieces are scattered around.

---

@mikedn commented on [Wed Feb 15 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-280112080)

> The spec is not vague about this, but is admittedly terse and relevant pieces are scattered around.

Is there any text in the spec that is actually relevant in this case? Because the only obvious piece right now is the description of `add.ovf.un` and that one is interpretable.

Also, this isn't the only case where an `int32` on the stack ends up being zero extended. See III.1.6 "Implicit argument coercion" for another case.

That said, it may be that sign extension makes more sense. Probably the only reason why such mixed type operations are valid is to avoid a bunch of casts in unsafe code. And since in .NET signed integer types are far more common than unsigned types it makes sense to sign extend by default and require a `conv.u` only when unsigned types are involved.

And considering that just a week ago I run into a real JIT bug related to `add.ovf.un` it may be that the JIT is wrong on this too. But it's far from obvious.

---

@tannergooding commented on [Wed Feb 15 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-280117815)

> Basically we start with signed int32 and nint

@VSadov, it is true that we start with a `signed int32`, but we do not start with a `signed native int`. The spec explicitly states that unmanaged pointers are `unsigned native int` and the result of that is a `unsigned native int` (the stack does not itself track whether the type is signed/unsigned, so it is up to the IL emitted to indicate the appropriate types by using the appropriate instructions).

---

@BruceForstall commented on [Fri Mar 24 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-289155002)

@VSadov as @mikedn wrote, the spec for add.ovf.un says:

> Add unsigned integer values with overflow check.

It seems pretty clear that this says the values being added should be treated as unsigned. So, when you write:

> un in ovf.un suffix does not specify the operand types of add, has nothing to do with operands really, it just specifies how overflow is determined in two's-complement math - CF vs. OF.

I would disagree.

It looks like JIT64 and RyuJIT agree on this interpretation. What about earlier, pre-Roslyn C# compilers?

---

@tannergooding commented on [Fri Mar 24 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-289158662)

I think we can all agree that, regardless of what the spec says right now, the behavior here is wrong (with regards to how pointer arithmetic is meant to work).

That is, for `pointer + int32`, the int32 should be sign extended and then added to the pointer so that negative int32 results in a subtraction.

---

@VSadov commented on [Fri Mar 24 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-289174596)

From the C# compiler's point of view there is, among many others, a built-in operator with a signature: `Add(pointer, int) -> pointer`.  
 
Compiler will see no reasons to apply any conversions to the operands since they match the types expected by the operator. That will not be affected by checked/unchecked context. The context has no effect on how operators are resolved.
The only thing that is affected is that numeric `Add` will be marked as `checked` according to the context and as a result will be emitted with `ovf.un` suffix.

Native compiler emits the same IL. 

---

@BruceForstall commented on [Sun Mar 26 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-289328800)

cc @CarolEidt 

---

@BruceForstall commented on [Tue Mar 28 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-289835732)

@VSadov I don't have much experience with the C# spec, but I have a question: should the "checked" context apply to pointer arithmetic at all in C#?

[Here](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#the-checked-and-unchecked-operators) it says overflow checking applies to (for binary operators):
```
The predefined +, -, *, and / binary operators (Arithmetic operators), when both operands are of integral types.
```
But it seems a pointer type is NOT an integral type. [Here](https://github.com/dotnet/csharplang/blob/master/spec/unsafe-code.md#pointer-types) it specifically says:
```
Pointer types are a separate category of types.
```

And [here](https://github.com/dotnet/csharplang/blob/master/spec/unsafe-code.md#pointer-conversions) it says pointers can be _converted_ to an integral type, but that conversion is explicit, not implicit.

Pointer arithmetic with one pointer and one integral type is specifically defined [here](https://github.com/dotnet/csharplang/blob/master/spec/unsafe-code.md#pointer-arithmetic), but I don't read anything there that implies the pointer is an "integral type", thus it seems overflow checking still shouldn't be applied.

Comments?

---

@mikedn commented on [Tue Mar 28 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-289843875)

I'm not sure what the C# spec has to do with this. The spec dictates how this particular piece of code is supposed to behave. It doesn't dictate how the code is to be translated to IL or to be precise it doesn't say that the C# built-in operator `+(pointer, int) -> pointer` directly maps to the `add.ovf.un` IL instruction. If an additional cast is required then so be it, the C# compiler has to insert that cast. But nobody seems to know for sure if the cast is required or not... 

Perhaps the fact that a cast would be required in the common case of `+(pointer, int)` and not required in the much less common case of `+(pointer, uint)` should push us towards fixing the JIT and clarifying the IL spec rather than fixing the C# compiler.

> but I have a question: should the "checked" context apply to pointer arithmetic at all in C#?

That's a very interesting question! The C# spec says this:

> If a pointer arithmetic operation overflows the domain of the pointer type, the result is truncated in an implementation-defined fashion, but no exceptions are produced.

---

@BruceForstall commented on [Mon Apr 03 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-291178360)

@VSadov Any comments on this?

---

@VSadov commented on [Mon Apr 03 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-291369902)

I think C# spec just tries to explain that `checked` only has effect on types that can overflow - i.e. integral vs. floating point types or some random type with undefined range and user-defined operators.

"Integral" is probably slightly misused here, but integer arithmetic is clearly applicable to pointers and pointers have a range of permitted values, so add/sub operations can be checked.

```c#
            checked
            {
                // this overflows
                void* m2 = (byte*)(-1);

                // this overflows
                void* m1 = (byte*)0 - 1;
            }
```

The point here is not what C# spec says, but how the behavior is implemented in IL.

The idea that `ovf.un` not only checks the result, but also zero extends operands would make pointer math trickier to emit.

Currently we convert `uint` operands to native int if added to a pointer, always - checked or unchecked context, while `int` operands are not converted. 
With the suggested change/refinement of the IL semantic, we would need to reverse that behavior in checked context (i.e. `int` would be converted, but `uint` would not be), but keep existing behavior in unchecked context, - since regular add/sub opcodes are all sign-extending. 

Anyways, this change will mostly result in a bunch of additional conversions in IL, since adding`int` is more common than adding `uint`. It seems that the whole point of allowing add between a native int and a regular int was to avoid these conversions. Otherwise it would make more sense to just require both operands be of the same size.

---

@CarolEidt commented on [Wed Apr 19 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-295415022)

I think that the fundamental problem here is that the signedness of integral types on the evaluation stack is not tracked, but is instead specified by the operations that are performed upon them. This is a fundamental property of the IL. Thus, as @BruceForstall points out, `add.ovf.un` is specified as taking unsigned operands. If the desired behavior is to sign-extend the 32-bit operand, that must be done explicitly.

This statement:
> I think we can all agree that, regardless of what the spec says right now, the behavior here is wrong (with regards to how pointer arithmetic is meant to work).

is irrelevant to the CLR/JIT, because the operand here is unsigned, and I think we can all agree on how an unsigned value should be added to a pointer. The C# compiler is where the knowledge of the operand types is available, and that is presumably where the explicit cast should be added.

Note further that, as this is the long-standing behavior of the JIT, it is unlikely that this could be changed without causing possible compatibility issues with existing code.

---

@RussKeldorph commented on [Thu Apr 20 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-295987745)

The conclusion is that JIT behavior is by design.  If a fix is made, it should be made to the C# compiler, both because of the ECMA language and because it would be a "less breaking" change.  Looks like this may have come up before in dotnet/roslyn#5671.

---

@tarekgh commented on [Thu Apr 20 2017](https://github.com/dotnet/coreclr/issues/9591#issuecomment-295989537)

@RussKeldorph it looks to me we didn't reach agreement if the issue has to be fixed in Roslyn. I am seeing dotnet/roslyn#5671 is closed as won't fix. this is really bad bug we need to fix it somewhere. 

@VSadov I am going to move this issue to Roslyn repo to decide what to do.

**Comment by VSadov** [comment]
I think it is pointless to argue with JIT team about interpretation of the spec that they own :-)

Besides, it is easier to service compiler than various JITs, so practically, updating compiler is the easier way to get the desired behavior.

Now we need to decide whether we want to fix this. It could be breaking, but that is the point of the fix.

Considering that this bug is reported once in two years, it may not be very breaking though.

**Comment by tannergooding** [comment]
@VSadov, I do think it could become more breaking, with the implementation of `nint/nuint`, since that will make `native integer` and `pointer` arithmetic more prevelant.

**Comment by VSadov** [comment]
@tannergooding - good point, although backend distinguishes pointers and native ints and we can have different emit for 'byte*' + 'int' and 'nuint' + 'int'. Not sure if we want that distinction though.

**Comment by jaredpar** [comment]
> Considering that this bug is reported once in two years, it may not be very breaking though.

I don't think that relates to whether or not it's likely to affect customers.  It could just as easily be argued that customers aren't reporting it because it's working for them in the current form and they've simply never noticed. 

We should bring this up in compat council to see how we feel about potentially taking a break here.

**Comment by VSadov** [comment]
@jaredpar - the reason that customers are complaining is that they enable "checked" and still have overflowing behavior on 64bit. (the behavior is 64bit specific)
The absence of expected crash prompts them to report a bug.

This is definitely a material for the @dotnet/roslyn-compat-council

**Comment by VSadov** [comment]
Actually it is worth than "no exception in checked", it may also turn 

```c#
checked
{
     _bytes += (-1);
}
```
into 

```c#  
checked
{
     _bytes += (very big number);
}
```

when running on 64bit.

- Just adding more info to consider the likelihood anyone is dependent on this behavior.

**Comment by JosephTremoulet** [comment]
See also https://github.com/dotnet/coreclr/issues/13501

**Comment by gafter** [comment]
The Compat Coincil discussed this (in May 2017) and decided that we are good with the proposed change in generated code.

**Comment by VSadov** [comment]
Considering inconsistencies between JITs and bugs like https://github.com/dotnet/coreclr/issues/13501, it seems sensible to always cast and stop relying on add.ovf.un support for mixed arguments altogether.  

That would be the most reliable way of fixing this scenario with prejudice.

It may seem a bit heavy-handed, but since we will have to force sign extending for int operands, the cast is needed in nearly 100% cases anyways, so we could as well emit cast unconditionally and not rely on unstable behaviors.
