### ISSUE TITLE
Bit-shift and comparison operator is parsed as generic type argument syntax in VS2017

### ISSUE THREAD

**Issue by mjcheetham** [dotnet/roslyn#18878]
**Version Used**: 15.1 (26403.7)

In VS2017 the expression `i < j >> 1` is being parsed as  `(i<j>) > 1` whereas in VS2015 it was parsed as `(i<j) >> 1`.

**Steps to Reproduce**:

```cs
int i = 0, j = 0;
bool b = i < j >> 1;
```

**Expected Behaviour**:

No errors (as in VS2015):

![image](https://cloud.githubusercontent.com/assets/5658207/25282675/20e79c84-26a9-11e7-84ce-a208a2c18d01.png)

**Actual Behaviour**:

![image](https://cloud.githubusercontent.com/assets/5658207/25282665/17cdd42e-26a9-11e7-978c-e5222e481a8b.png)

**Comment by gafter** [comment]
This was fixed in https://github.com/dotnet/roslyn/pull/16834 .
