### ISSUE TITLE
NavigateTo tests are broken/flakey

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#18870]
It looks like they are more likely to fail than to pass, so I will consider them broken.

This affects both VB and C# tests.

**Comment by VSadov** [comment]
Both VB and C# tests are still failing. Failed 4 times in the last 24 hours

**Comment by sharwell** [comment]
:memo: The previous line was a false alarm (filters for viewing failed tests were not excluding other branches where my fix wasn't merged). Also #19530 is tracking the current state.
