### ISSUE TITLE
csc /O changes program behavior wrt floats

### ISSUE THREAD

**Issue by vargaz** [dotnet/roslyn#18891]
**Version Used**: 

csc 2.0.0.61404 running on Mono 5.0

**Steps to Reproduce**:

Compile the following c# code with/without csc /O flag:
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```
using System;
using System.Runtime;
using System.Runtime.ExceptionServices;

public class Tests
{
	public static void Main (String[] args) {
		Console.WriteLine (bar ());
	}

	public static int bar () {
		float f1 = 3.40282346638528859E+38f;
		float f2 = 3.40282346638528859E+38f;		
		float PositiveInfinity =  1.0f / 0.0f;
		float f = f1 + f2;

		return f == PositiveInfinity ? 0 : 1;
	}
}
```
When ran on mono, the version compiled without the /O flag prints 0, and the version compiled
with the /O flag prints 1. The reason is that the csc /O generates the following IL code:
```
    IL_0000:  ldc.r4     3.40282347E+38
    IL_0005:  ldc.r4     3.40282347E+38
    IL_000a:  stloc.0
    IL_000b:  ldc.r4     (00 00 80 7F)
    IL_0010:  stloc.1
    IL_0011:  ldloc.0
    IL_0012:  add
    IL_0013:  dup
    IL_0014:  ldloc.1
    IL_0015:  beq.s      IL_001a
```
........
So the result of the addition stays on the IL stack, without undergoing any r32<->r64 conversion, since in Mono, operations on floats are done in double precision. Without the /O flag, csc generates the following IL:
```
    IL_0015:  add
    IL_0016:  stloc.3
    IL_0017:  ldloc.3
```
So the result of the addition is converted to r32 when written to local 3.

I think csc shouldn't optimize away loads/stores to locals of type float, since it eliminates conversions, changing program behavior.

**Comment by gafter** [comment]
The [spec says](https://github.com/dotnet/csharplang/blob/6027ad5a4ab013f4fb42f5edd2d667d649fe1bd8/spec/types.md#floating-point-types)

> Floating-point operations may be performed with higher precision than the result type of the operation. For example, some hardware architectures support an “extended” or “long double” floating-point type with greater range and precision than the double type, and implicitly perform all floating-point operations using this higher precision type. Only at excessive cost in performance can such hardware architectures be made to perform floating-point operations with less precision, and rather than require an implementation to forfeit both performance and precision, C# allows a higher precision type to be used for all floating-point operations. Other than delivering more precise results, this rarely has any measurable effects. However, in expressions of the form x \* y / z, where the multiplication produces a result that is outside the double range, but the subsequent division brings the temporary result back into the double range, the fact that the expression is evaluated in a higher range format may cause a finite result to be produced instead of an infinity. **To force a value of a floating point type to the exact precision of its type, an explicit cast can be used.**

My emphasis. Also, in 6.1.1 (might not be in the latest version of the spec):

> In most cases an identity conversion has no effect at runtime. However, since floating point operations may be performed at higher precision than prescribed by their type (§4.1.6), assignment of their results may result in a loss of precision, and **explicit casts are guaranteed to reduce precision to what is prescribed by the type.**

If you want a result truncated to the type `float`, it is not sufficient merely to store it in a local variable of that type, as the compiler may use the stack to store locals, and the CLR may use extended precision to represent them. You must cast the value to the type `float` to force the truncation.

**Comment by vargaz** [comment]
Makes sense, thanks.
