### ISSUE TITLE
Can't build latest version of master. Missing ISuggestedActionWithFlavors

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#189]
I'm getting an error on: 
https://github.com/dotnet/roslyn/blob/4754991da6685dfe4d7fcb967e8163490d12df8a/src/EditorFeatures/Core/Implementation/Suggestions/SuggestedActionWithFlavors.cs#L15

Roslyn Ref Source can't find it either: http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Suggestions/SuggestedActionWithFlavors.cs,15

I'm guessing `ISuggestedActionWithFlavors` likely exists in a closed source component of the codebase.

**Comment by mikedn** [comment]
That interface is in Microsoft.VisualStudio.Language.Intellisense.dll which is part of the VS SDK. You probably need to install the latest 2015 CTP to get it, I have it here.

Or try using the Roslyn2013.sln which doesn't include all the VS stuff.

**Comment by JoshVarty** [comment]
Geez, that's embarasssing. :)

Thanks @mikedn
