### ISSUE TITLE
quickwatch fails on valid expression

### ISSUE THREAD

**Issue by Spongman** [dotnet/roslyn#18908]
run the following program, stop at the breakpoint, quickwatch "t.Id".
````
error CS1061: 'T' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'T' could be found (are you missing a using directive or an assembly reference?)
````
however, the code executes fine.

	public interface IFoo<T>
	{
		T Id { get; }
	}

	public class Foo<T, TKey>
		where T : class, IFoo<TKey>
	{
		public void Method(T t)
		{
			var q = t.Id;        // <<<<<<------ breakpoint here
		}
	}

	public class Goo : IFoo<string>
	{
		public string Id => "asd";
	}

	public static void Main()
	{
		new Foo<Goo, string>().Method(new Goo ());
	}

**Comment by CyrusNajmabadi** [comment]
Works fine in latest builds:

![image](https://user-images.githubusercontent.com/4564579/198742884-8e64ce73-1d79-4597-8830-27616cf99369.png)
