### ISSUE TITLE
expose "SymbolDisplayCompilerInternalOptions" to public

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#1891]
http://stackoverflow.com/questions/27105909/get-fully-qualified-metadata-name-in-roslyn

user should have easy way to contruct metadata type name that can be used with Compilation.GetTypeByMetadataName.

https://github.com/dotnet/roslyn/issues/1831#issuecomment-91318801

**Comment by mavasani** [comment]
+1

**Comment by JoshVarty** [comment]
:+1: I needed this one again today.

**Comment by Aethon** [comment]
+1 srsly.

**Comment by michaelcfanning** [comment]
+1

**Comment by bkoelman** [comment]
+1

**Comment by nicebug** [comment]
+1

**Comment by panopticoncentral** [comment]
+1

**Comment by AnthonyDGreen** [comment]
I approve of making it public. I'm assuming the name won't be CompilerInternal.

**Comment by steffenloesch** [comment]
+1

**Comment by nonbob** [comment]
+1

**Comment by suprak** [comment]
+1

**Comment by ascott18** [comment]
+1

**Comment by ReubenBond** [comment]
Any help here would be appreciated: is there a way we can construct the corresponding metadata name for an `INamedTypeSymbol` in a `Compilation`?

**Comment by ReubenBond** [comment]
@AnthonyDGreen it says above that I unassigned you. That was not my intention, many apologies.
![image](https://user-images.githubusercontent.com/203839/42539802-9381a998-84df-11e8-945d-fa10b8460115.png)
I don't know how that happened, since I do not appear to have the ability to assign or unassign people on dotnet/roslyn:
![image](https://user-images.githubusercontent.com/203839/42539822-9cb4e606-84df-11e8-8a1a-a080307c9277.png)
Versus on a repository I do have permissions on:
![image](https://user-images.githubusercontent.com/203839/42539861-b2d41574-84df-11e8-843a-8026ebd6cdfb.png)

**Comment by ceztko** [comment]
Any update on this? Another use case for the requested feature, if I understand correctly, could be to allow trying to construct a `Type` from a `ITypeSymbol`. This can be used from example to construct a concrete attribute starting from `AttributeData` at runtime with reflection. If the constructor arguments and parameters in the compilation are correct this is guaranteed to be safe.

**Comment by CyrusNajmabadi** [comment]
Can you expand on that (with an example) @ceztko ?  I'm not really getting what you're asking for.

**Comment by ceztko** [comment]
> Can you expand on that (with an example) @ceztko ? I'm not really getting what you're asking for

I'm assuming the the canonical CLR metadata name described in [Compilation.GetTypeByMetadataName](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.compilation.gettypebymetadataname?view=roslyn-dotnet) is basically the same as [Type.AssemblyQualifiedName](https://docs.microsoft.com/en-us/dotnet/api/system.type.assemblyqualifiedname?view=netframework-4.8) that can be used with [Type.GetType(name)](https://docs.microsoft.com/en-us/dotnet/api/system.type.gettype?view=netframework-4.8#System_Type_GetType_System_String_). If not I misread the issue. Anyway, it would be cool if roslyn provided as a supported way to compute a compliant `AssemblyQualifiedName` from an `ITypeSymbol`.

The uses case I provided, which actually it's an easy one and I coded it for simple cases (doesn't work for arrays, for example), it's about constructing an actual attribute instance from `AttributeData`:

```
        /// <summary>
        /// Construct an attribute from AttributeData
        /// </summary>
        public static TAttrib Construct<TAttrib>(this AttributeData data)
            where TAttrib : Attribute
        {
            Type[] types = new Type[data.ConstructorArguments.Length];
            object[] objects = new object[data.ConstructorArguments.Length];
            for (int i = 0; i < data.ConstructorArguments.Length; i++)
            {
                var arg = data.ConstructorArguments[i];
                types[i] = Type.GetType(arg.Type.GetAssemblyQualifiedName());
                objects[i] = arg.Value;
            }

            var attrib = (TAttrib)typeof(TAttrib).GetConstructor(types).Invoke(objects);
            for (int i = 0; i < data.NamedArguments.Length; i++)
            {
                var arg = data.NamedArguments[i];
                var property = typeof(TAttrib).GetProperty(arg.Key);
                if (property == null)
                {
                    var field = typeof(TAttrib).GetField(arg.Key);
                    if (field == null)
                        throw new Exception($"Missing property or field with name {arg.Key}");

                    field.SetValue(attrib, arg.Value.Value);
                }
                else
                {
                    property.SetValue(attrib, arg.Value.Value);
                }
            }

            return attrib;
        }

        /// <summary>
        /// Get CLR Metadata type name that can be used with Type.GetType(name)
        /// </summary>
        public static string GetAssemblyQualifiedName(this ITypeSymbol symbol)
        {
            return symbol.ContainingNamespace + "." + symbol.Name + ", " + symbol.ContainingAssembly;
        }
```

**Comment by sbergen** [comment]
Looks to me like making `SymbolDisplayFormat.QualifiedNameArityFormat` public (perhaps with a different name) would fulfil the needs for most use cases, including OP's use case. I would think using `Compilation.GetTypeByMetadataName` would be a pretty common use case, and It's currently really confusing that there seems to be no easy way to get the string required by `Compilation.GetTypeByMetadataName` from e.g. a `INamedTypeSymbol`.

**Comment by sbergen** [comment]
> Looks to me like making `SymbolDisplayFormat.QualifiedNameArityFormat` public (perhaps with a different name) would fulfil the needs for most use cases, including OP's use case.

Didn't take me too long to figure out I'm wrong :) Nested types don't seem to work with this.

In any case, I would prefer if there was a SymbolDisplayFormat directly for this, instead of having to construct one yourself.

**Comment by rodion-m** [comment]
What is this issue waiting for? Please make `SymbolDisplayCompilerInternalOptions` public.

Btw, here is a reflection-based hacky solution that allows to create `SymbolDisplayFormat` using an internal constructor: https://gist.github.com/rodion-m/f116db6b7f745c0f535b1ed615c4b8f0

Usage example:
```cs
SymbolDisplayFormat symbolDisplayFormat = SymbolDisplayFormatFactory.CreateSymbolDisplayFormat(SymbolDisplayFormatFactory.SymbolDisplayCompilerInternalOptions.IncludeCustomModifiers);
```

**Comment by CyrusNajmabadi** [comment]
> What is this issue waiting for?

We would need a proper proposal, including which items to make public and the best way to expose them.

**Comment by CyrusNajmabadi** [comment]
Closing out as this was filed prior to our current API proposal process.  If someone is interested in this, can you open a new issue that follows that process.

**Comment by aradalvand** [comment]
Given that the `SymbolDisplayCompilerInternalOptions` and by extension its `UseArityForGenericTypes` item are still internal (which makes no sense, this issue is still as relevant as ever and should not have been closed), we could nonetheless implement a reliable workaround rather easily:
```cs
static class TypeSymbolExtensions
{
	extension(SymbolDisplayFormat)
	{
		// NOTE: Inspired by the internal `QualifiedNameArityFormat` — see https://github.com/dotnet/roslyn/blob/c2a993bf925f60e328823fbe0057cd5cbcff219e/src/Compilers/Core/Portable/SymbolDisplay/SymbolDisplayFormat.cs#L226-L231
		public static SymbolDisplayFormat FullyQualifiedMetadataNameWithoutGenericArity => new(
			globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
			typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
			// compilerInternalOptions: SymbolDisplayCompilerInternalOptions.UseArityForGenericTypes, // NOTE: This could've been uncommented and the special logic in `FullMetadataName` would no longer be necessary. See 
			miscellaneousOptions: SymbolDisplayMiscellaneousOptions.ExpandValueTuple
		);
	}
	extension(INamedTypeSymbol type)
	{
		public string FullMetadataName
		{
			get
			{
				var withoutArity = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedMetadataNameWithoutGenericArity);
				if (type.IsGenericType)
					return $"{withoutArity}`{type.TypeParameters.Length}";
				return withoutArity;
			}
		}
	}
}
```

**Comment by CyrusNajmabadi** [comment]
@aradalvand 

> and should not have been closed

The issue does not follow our publicapi request process.

--

Note: you may want to to double check your extension for nested generics.
