### ISSUE TITLE
EnC: improve editing experience when stopped on exception

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#18917]
Currently [we make editor buffers read-only](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/EditAndContinue/VsENCRebuildableProjectImpl.cs,141), which is not ideal [370341](https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=370341)

Proposal for new experience:

-	We don’t use read-only buffers at all in this scenario, let the user type in the buffer as normal.
-	We detect the edit and send event to the debugger. 
-	If the unwind fails instead of showing a modal dialog and taking focus away from the editor we just squiggle the change and report rude edit with error message “Exception couldn’t be unwound”.
-	Before continue we wait for the result of the event and we block continue if unwind failed (the rude edit will do that).

**Comment by miloush** [comment]
Is this the reason why when you now hit an exception, place the cursor somewhere and start typing, the insertion point is reset and you type somewhere else, potentially in different file? That is absolutely annoying regression indeed!

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/36727
