### ISSUE TITLE
error MSB6006: access outer variables from local function

### ISSUE THREAD

**Issue by robisrob** [dotnet/roslyn#18918]
**Version Used**: .Net Core SDK 1.0.1

**Steps to Reproduce**:

- Possibility 1: Try to compile https://github.com/robisrob/BugRoslyn/blob/broken/Test.cs
- Possibility 2: Go to https://travis-ci.org/robisrob/BugRoslyn/branches

**Expected Behavior**:
Class can be compiled

**Actual Behavior**:
I get the following error: MSB6006. 

By putting certain lines in comment the build will pass. See https://github.com/robisrob/BugRoslyn/blob/notbroken/Test.cs

**Comment by gafter** [comment]
@agocke Has this compiler crash in local functions been fixed?

**Comment by agocke** [comment]
No. I think this may be the same bug as in https://github.com/dotnet/roslyn/issues/18918

**Comment by robisrob** [comment]
@agocke #18918 is the reference to this issue...

**Comment by agocke** [comment]
@robisrob Woops, thanks! I meant https://github.com/dotnet/roslyn/issues/18814 😝

**Comment by robisrob** [comment]
@agocke you're welcome :)

**Comment by agocke** [comment]
Fixed by https://github.com/dotnet/roslyn/issues/20198
