### ISSUE TITLE
Poor naming suggestions when creating an async method

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#18926]
![image](https://cloud.githubusercontent.com/assets/4564579/25309320/c2a7ffde-277e-11e7-881d-c71af639945b.png)

Tagging @rchande

**Comment by sharwell** [comment]
@rchande I would treat the case of returning `Task` the same way you would treat a variable with the type `var` - simply don't suggest names in this case.

**Comment by Pilchie** [comment]
In this case, isn't the problem that the parser is treating `async` as the return type still?

@CyrusNajmabadi didn't you just change the parser to do better here?  Or is this after that change?

**Comment by CyrusNajmabadi** [comment]
This is probably aided by my change.  Still filing it so we can verify.

**Comment by rchande** [comment]
I think `Task` is already excluded from producing naming suggestions. Easy enough to exclude `async` too--unless we think there are users trying to return types called `async`.

**Comment by CyrusNajmabadi** [comment]
This no longer repros.
