### ISSUE TITLE
Apply insert_final_newline consistently to our code base

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#18934]
Currently the **.editorconfig** files used by this project do not specify a value for `insert_final_newline`. In combination with various settings on individual developer machines, this is causing a fair amount of unnecessary code churn in pull requests.

I propose adding this value to **.editorconfig** in a manner consistent with the existing configurations of [dotnet/corefx](https://github.com/dotnet/corefx/blob/master/.editorconfig#L10) and [dotnet/coreclr](https://github.com/dotnet/coreclr/blob/a2e04c1f7f798ccf3e573a95cc5ec66e1ba86490/.editorconfig#L12).

Currently the value is not enforced by Roslyn or the IDE, but both the commonly-used EditorConfig and certain other source editors do recognize it already. Tighter integration between Roslyn and EditorConfig is planned, but it doesn't seem necessary to wait for that to make this change.

**Comment by MisinformedDNA** [comment]
Should this be closed?

**Comment by sharwell** [comment]
Thank you @MisinformedDNA !
