### ISSUE TITLE
Proposal to update colors for certain blocking and non-blocking labels

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#18949]
I'm finding that some of my pages of pull requests are challenging to get a quick overview, and I believe that changing the colors of a few targeted labels may assist in this. The labels of particular interest to me appear commonly and have special implications for the review process:

### Non-blocking labels

These labels are procedural/automated and do not block the review merge process. I propose they be colored to match the background (`#FFFFFF`) so they are less distracting.

* **cla-already-signed**
* **cla-not-required**
* **cla-signed**

### Blocking labels

These labels, when applied, necessarily block forward progress of a review/merge. I propose they be inverted (`#000000`) for maximum contrast against other labels and the background.

* **cla-required**
* **PR For Personal Review Only**

**Comment by jasonmalinowski** [comment]
My feedback: blocking should be red. That is what red means. Black actually doesn't stand out in black/white text.

**Comment by sharwell** [comment]
Implemented this morning. While @jasonmalinowski's comment was more agreed to than not, we went with the original proposal for its simplicity (didn't have to come up with colors for all the other items which are red or red-like).
