### ISSUE TITLE
Suppress roslyn messages causes strange behavior.

### ISSUE THREAD

**Issue by Portikus** [dotnet/roslyn#18942]
**Version Used**: VisualStudio 2017 / 15.1 (26403.7) Release

**Steps to Reproduce**:
In the attached repo solution : [SuppressRoslynWarningsBug.zip](https://github.com/dotnet/roslyn/files/950915/SuppressRoslynWarningsBug.zip) I configured a project to use a shared.props file . In this file there is a variable specified which contains all warnings I want to suppress (in this case IDE0019). 
Furthermore there is a `Class1` which code causes a IDE0019 warning:

````csharp
var str = obj as string;
if (str != null)
{
}
````
So the warning will be suppressed but:
1. Open the shared.props file
2. Remove the IDE0019
3. Close and reload the solution

**Expected Behavior**:
Now I expected that the warning wont be supressed anymore but it is still suppressed.

This is not the only Issue I get with a shared property file in combination with the suppression of warnings. In my Solution (45 netstandard and UWP projects) I added recently 3.Party analyser and I wanted to supress some of their warnings. So I added these warnings to my shared.props file. But some of these warnings are not suppressed. I tried to reproduce this in a small environment but then I got the issue descriped above. Maybe there is a general problem with suppression of warnings using a shared.props file?

I hope you can help me.

**Comment by sharwell** [comment]
@Portikus (A workaround, not a solution) When I encountered this in an experiment, I found that I could close VS and delete the **.vs** folder next to my solution. When I reopened the solution, it was now operating with the updated shared configuration.

**Comment by Pilchie** [comment]
Tagging @davkean and @srivatsn - are we tracking the msbuild caching of imported targets not being updated on file change?

**Comment by davkean** [comment]
Yes, we're tracking this as part of: https://github.com/dotnet/project-system/issues/268.

**Comment by Portikus** [comment]
@Pilchie  @davkean unfortunately the latest Visual Studio update (15.3.1) didn't fix this problem. The only way Visual Studio recognizes the changes is with the workaround from @sharwell.

**Comment by Portikus** [comment]
@davkean may you reopen this issue?

**Comment by davkean** [comment]
@Portikus I missed that you were referring to the old project system and not the new one. I can move this bug and we can leave it open but to set expectations - we have do not have intentions of reloading targets in the legacy project system. It's a non-trivial amount of work that we're rather spend on adding features to the new project system so that we can phase out the legacy project system.

**Comment by davkean** [comment]
This issue was moved to dotnet/project-system#2734

**Comment by Portikus** [comment]
> @Portikus I missed that you were referring to the old project system and not the new one. I can move this bug and we can leave it open but to set expectations - we have do not have intentions of reloading targets in the legacy project system. It's a non-trivial amount of work that we're rather spend on adding features to the new project system so that we can phase out the legacy project system.

@davkean thank you for the info. Ok then I have to wait until UWP is supported in the new project system I guess.

**Comment by davkean** [comment]
UWP will be one of the first existing project types that will move.
