### ISSUE TITLE
Can't install .NET Compiler Platform SDK

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#18954]
**Version Used**: VS 15.1 (26403.7) Release, Community Edition

**Steps to Reproduce**:

1. I did a google search that took me to this page https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.NETCompilerPlatformSDK

I installed the VSIX from it. Installation appeared to go okay. I searched for Analyzer in the File>New dialog, and the only C# result I got was "Download the .NET Compiler Platform SDK". So I guess installation hadn't worked.

2. I tried clicking on that FileNew>C#>Extensibility>Download Compiler Platform SDK. It took me to a local page C:\Users\ljw1004\Documents\Visual Studio 2017\Projects\CSharpCompilerPlatformSDKDownload1\index.html with a fwlink to https://go.microsoft.com/fwlink/?LinkID=526901, which points to the exact same download page as I tried in Step1 (if you open it in an external window) or which downloads Roslyn_SDK.vsix directly (if you click on the link inside VS). Regardless, it says "This product is already installed to all applicable products".

3. I tried going to Tools>Extensions and uninstalled the .NET Compiler Platform SDK. Then I launched the VS2017 installer, clicked on Modify, and turned on the "Visual Studio extension development" workload. This claims it lets you create code analyzers. (However, the "individual components" tab doesn't list any component that looks like it's at all related to .NET Compiler Platform SDK so I don't know if this really worked).

I then launched VS2017. Once again, the File>New dialog only had an option for "Download .NET Compiler Platform SDK". It let me install it okay (hence, the VS Installer checkbox apparently hadn't installed it!). But even after installing it, the File>New dialog continues to only have an option for "Download .NET Compiler Platform SDK".

**Expected Behavior**:

Please let me write an analyzer! I don't know how to get started!

**Actual Behavior**:

I can't even get started writing an analyzer.

**Comment by ljw1004** [comment]
Edit: I next tried to create a File>New>C#>ClassLibrary (i.e. a standard desktop framework class library) and install a NuGet reference to Microsoft.CodeAnalysis. The NuGet installation failed because it said it couldn't find anything compatible with this target. I tried a few different target frameworks (40, 45, 452, 46) and got the same error on all of them.

Next I tried to do File>New>.NET Standard Library. I guess by default this targets .NETStandard1.4? -- is a pain to find out with the "Properties" node absent from SolutionExplorer. Again NuGet failed saying it couldn't find anything compatible. I tried targeting .NETStandard 1.3 and got another error message:

```
Package Microsoft.Composition 1.0.27 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETStandard,Version=v1.3.
Package restore failed. Rolling back package changes for 'ProbabilisticAnalyzer'.
```

Oh boy this is a challenge!

**Comment by jmarolf** [comment]
Analyzers only work on .NET Framework 4.6 and newer
![image](https://cloud.githubusercontent.com/assets/9797472/25354559/33679c9c-28e8-11e7-88f4-1ea6971e9a65.png)
 If you change this dropdown the template will show up

**Comment by ljw1004** [comment]
Hmm... I guess I was mislead by a few things:

(1) Leaving the default .NET4.5 target, it shows an option "Download .NET SDK" which isn't relevant to my current setup nor does it guide me in the right direction

(2) The Installer workload seems to promise more than it actually delivers?

**Comment by jmarolf** [comment]
@ljw1004 I am not saying anything you've reported is not a bug,  just trying to unblock you.

1. I need to remove that "Download Roslyn SDK" project.  It should just be a checkbox on the VS installer
2. I need to move all the templates (on VS 2017) to be netstandard based. 
3. I need to update roslyn dependencies to no longer include `Microsoft.Composition`

With these changes I think most if not all of your pain points should be addressed

**Comment by ljw1004** [comment]
Sure, understood, thanks!

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #70](https://github.com/dotnet/roslyn-sdk/issues/70) via [**ZenHub**](https://www.zenhub.com/)
