### ISSUE TITLE
Warning that Interactive is too slow

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#18961]
![image](https://cloud.githubusercontent.com/assets/4564579/25356156/21fcb982-28ee-11e7-987b-8774c9e1eccd.png)

**Comment by tmat** [comment]
There is nothing to improve on our side that I know of. We just create a tool window.

**Comment by CyrusNajmabadi** [comment]
Haven't seen this in ages.  Closing out.
