### ISSUE TITLE
Sometimes the type identity seems to fail on CoreCLR

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#18985]
We see this only in tests and very rarely, it is likely to be an artifact of assembly loading races in tests or something like that.

We need to investigate this and fix. Even if rare, it happens often enough to cause failed builds and other grief.

A typical failure would be a random test failing with something like:

Assert.Same() Failure 
Expected: Pia1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null 
Actual: Pia1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null

or 

12:17:10         Assert.Equal() Failure
12:17:10         Expected: System.IComparable
12:17:10         Actual:   System.IComparable

I.E. Seemingly same types compare as not equal where they are expected to be equal.

**Comment by agocke** [comment]
The tests seem solid after the SDK change. I'm going to assume that this was related to the deployment, which is now being done using `publish`, which should be more reliable than the system I was using before. Closing for now.
