### ISSUE TITLE
Generate field should consider `readonly` modifier when generating fields

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#18988]
Case in point: https://github.com/dotnet/roslyn/pull/18966/files/85e26374b69e836165cc3f6824ad56ac12652907#r113299906.

I used generate field to generate the readonly _waitIndicator field and it was inserted after the mutable _disposed field. It would be nice if we could have automatically grouped it with the other readonly fields.

**Comment by rchande** [comment]
cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
interestingly... it's supposed to do that.  I wonder if it broke when we did the work to stop trying to keep things alphabetized.

**Comment by CyrusNajmabadi** [comment]
ah no.  we consider const-ness.  but not readonly-ness.

**Comment by CyrusNajmabadi** [comment]
Note to self: when doing this work, also update generate-field to smartly place field using information from surrounding assignment-statements and the parameter list.
