### ISSUE TITLE
CSharpErrorListDesktop.ErrorLevelWarning test and related are flakey

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#18996]
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorList
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorLevelWarning
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListDesktop.ErrorList
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListDesktop.ErrorLevelWarning

**Comment by sharwell** [comment]
I'm a bit concerned that these tests are telling us about a real race condition bug in our product.

**Comment by Pilchie** [comment]
@srivatsn @jmarolf these are the ones you just disabled and entered a bug on project-system for, right?

**Comment by jmarolf** [comment]
This is actually a different set of tests than the one I set a PR out for, but if you asking if this should also be in the project system repo, I would say yes as the intent is the same

**Comment by srivatsn** [comment]
This issue was moved to dotnet/project-system#2125

**Comment by sharwell** [comment]
@srivatsn Reopening this because the tests still exist in Roslyn, and are un-skipped as part of the work in #25151. Please review the approach and let me know if this is good or we need to do something else.
