### ISSUE TITLE
Using 'tab' to commit a tuple-parameter name should not insert the colon.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#18994]
This is not how it works for named parameters to methods.  Hitting tag on a named-parameter completoin item does not insert the colon.  The change in behavior is seriously affecting my muscle memory and typing here :)

Tagging @jcouv

**Comment by jcouv** [comment]
Maybe hitting tab should insert the colon in both cases? ;-)

**Comment by CyrusNajmabadi** [comment]
:)   IIRC, it was very explicit that we didn't insert colon.  Some people (like myself) just hit tab-colon, expecting to just get the name.  Similar to how tab on ```List<>``` doesn't insert the ```<>```

**Comment by Pilchie** [comment]
I would love to change that, as long as we had great overtype support.

Similar to inserting parens on method calls, etc.

**Comment by Pilchie** [comment]
However, for right now, @CyrusNajmabadi is right - this is not how our experience currently works.

**Comment by jcouv** [comment]
Notes to self:
Relates to https://github.com/dotnet/roslyn/pull/16861.
For reference, the tests I'll need to add probably look like those: https://github.com/dotnet/roslyn/pull/13638.

**Comment by jcouv** [comment]
Fixed by #19335
