### ISSUE TITLE
use block/expression-body 'reverse' fix should be a CodeRefactoring, not a CodeFix.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#19008]
We should have code-fixes for user code that violates their current preference for use-block/expression-body.  However, for code that doesn't violate their preference, but which can be switched to the reverse, we should offer things as a CodeRefactoring (not a fix).

This way even if a user prefers expression-bodies, they can switch a member to use an block if they feel it is more appropriate in that context.

This will then present the option to the user using the new "Code Refactoring" glyph, instead of the "light-bulb-fix" glyph.  i.e. we'll prompt with the lightbulb (plus suggestion/warning/error tag) when the code violates the preference.  But we we'll only show the code-refactoring glyph for code that doesn't violate the preference.

**Comment by davkean** [comment]
@CyrusNajmabadi Are we making refactorings a different icon? Awesome - my complaints with always showing them will go away.

**Comment by CyrusNajmabadi** [comment]
> Are we making refactorings a different icon?

Yup.  :)   @kuhlenh Can provide you with more details if you're interested.

**Comment by Pilchie** [comment]
didn't I see that you already have a PR for this?
