### ISSUE TITLE
Smart Tag shouldn't be offered for 'AddressOf' expression

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#1900]
Ported from TFS WorkItem: **529510**

---

**Repro Steps:**

<FONT size=3>

Step1. Open New VB file.&nbsp;

Step2: Copy and paste the following code:

&nbsp;

<PRE style="FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink; FONT-SIZE: 16px"><SPAN style="COLOR: blue">Module</SPAN> <SPAN style="COLOR: #2b91af">Module1</SPAN>
    <SPAN style="COLOR: blue">Public</SPAN> <SPAN style="COLOR: blue">Sub</SPAN> <SPAN style="COLOR: black">Foo</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">ByVal</SPAN> <SPAN style="COLOR: black">a1</SPAN> <SPAN style="COLOR: blue">As</SPAN> <SPAN style="COLOR: #2b91af">Exception</SPAN><SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Sub</SPAN>
    <SPAN style="COLOR: blue">Public</SPAN> <SPAN style="COLOR: blue">Sub</SPAN> <SPAN style="COLOR: black">foo</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">ByVal</SPAN> <SPAN style="COLOR: black">a1</SPAN> <SPAN style="COLOR: blue">As</SPAN> <SPAN style="COLOR: #2b91af">Action</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">Of</SPAN> <SPAN style="COLOR: #2b91af">ArgumentException</SPAN><SPAN style="COLOR: black">))</SPAN>
    <SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Sub</SPAN>
    <SPAN style="COLOR: blue">Sub</SPAN> <SPAN style="COLOR: black">Main</SPAN><SPAN style="COLOR: black">()</SPAN>
        <SPAN style="COLOR: black">foo</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">New</SPAN> <SPAN style="COLOR: #2b91af">Action</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">Of</SPAN> <SPAN style="COLOR: #2b91af">Exception</SPAN><SPAN style="COLOR: black">)(</SPAN><FONT style="BACKGROUND-COLOR: #ffff00"><SPAN style="COLOR: blue">AddressOf</SPAN> <SPAN style="COLOR: black">Foo</SPAN></FONT><SPAN style="COLOR: black">))</SPAN>
    <SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Sub</SPAN>
<SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Module</SPAN></PRE>

&nbsp;

**ACTUAL RESULT**

Smart Tag under <FONT style="BACKGROUND-COLOR: #ffff00"><FONT size=+0><SPAN style="COLOR: blue"><FONT size=+0>AddressOf</FONT></SPAN> </FONT><SPAN style="COLOR: black">Foo</SPAN></FONT>

<FONT style="BACKGROUND-COLOR: #ffff00"><SPAN style="COLOR: black"></SPAN></FONT>&nbsp;

**EXPECTED RESULT**

Shouldn't be offered at all, because Action(of T) requires an 'AddressOf' expression or lambda expression as the only argument to its constructor.
</FONT>

---

**Revisions:**

1) Created By Binyam Kelile (11/28/2012 6:57:09 PM)

---

2) Edited By Binyam Kelile (11/28/2012 6:57:12 PM)

Unit test:

...\Services\VisualBasic\Test\CodeActions\IntroduceVariable\IntroduceVariableTests.vb
<font size=2 face=Consolas><font size=2 face=Consolas>

&lt;</font></font><font color="#2b91af" size=2 face=Consolas><font color="#2b91af" size=2 face=Consolas><font color="#2b91af" size=2 face=Consolas>WorkItem</font></font></font><font size=2 face=Consolas><font size=2 face=Consolas>(13283)&gt;

&lt;</font></font><font color="#2b91af" size=2 face=Consolas><font color="#2b91af" size=2 face=Consolas><font color="#2b91af" size=2 face=Consolas>Fact</font></font></font><font size=2 face=Consolas><font size=2 face=Consolas>(Skip:=</font></font><font color="#800000" size=2 face=Consolas><font color="#800000" size=2 face=Consolas><font color="#800000" size=2 face=Consolas>&quot;13283&quot;</font></font></font><font size=2 face=Consolas><font size=2 face=Consolas>), </font></font><font color="#2b91af" size=2 face=Consolas><font color="#2b91af" size=2 face=Consolas><font color="#2b91af" size=2 face=Consolas>Trait</font></font></font><font size=2 face=Consolas><font size=2 face=Consolas>(</font></font><font color="#2b91af" size=2 face=Consolas><font color="#2b91af" size=2 face=Consolas><font color="#2b91af" size=2 face=Consolas>Traits</font></font></font><font size=2 face=Consolas><font size=2 face=Consolas>.Feature, </font></font><font color="#2b91af" size=2 face=Consolas><font color="#2b91af" size=2 face=Consolas><font color="#2b91af" size=2 face=Consolas>Traits</font></font></font><font size=2 face=Consolas><font size=2 face=Consolas>.</font></font><font color="#2b91af" size=2 face=Consolas><font color="#2b91af" size=2 face=Consolas><font color="#2b91af" size=2 face=Consolas>Features</font></font></font><font size=2 face=Consolas><font size=2 face=Consolas>.CodeActionsIntroduceVariable)&gt;

</font></font><font color="#0000ff" size=2 face=Consolas><font color="#0000ff" size=2 face=Consolas><font color="#0000ff" size=2 face=Consolas>Public</font></font></font><font size=2 face=Consolas><font size=2 face=Consolas> </font></font><font color="#0000ff" size=2 face=Consolas><font color="#0000ff" size=2 face=Consolas><font color="#0000ff" size=2 face=Consolas>Sub</font></font></font><font size=2 face=Consolas><font size=2 face=Consolas> TestNoRefactoringOnAddressOfExpression()

</font></font><font color="#0000ff" size=2 face=Consolas><font color="#0000ff" size=2 face=Consolas><font color="#0000ff" size=2 face=Consolas>Dim</font></font></font><font size=2 face=Consolas><font size=2 face=Consolas> source = NewLines(</font></font><font color="#800000" size=2 face=Consolas><font color="#800000" size=2 face=Consolas><font color="#800000" size=2 face=Consolas>&quot;Imports System \n Module Module1 \n Public Sub Foo(ByVal a1 As Exception) \n End Sub \n Public Sub foo(ByVal a1 As Action(Of ArgumentException)) \n End Sub \n Sub Main() \n Foo(New Action(Of Exception)([|AddressOf Foo|])) \n End Sub \n End Module&quot;</font></font></font><font size=2 face=Consolas><font size=2 face=Consolas>)

TestMissing(source)

</font></font><font color="#0000ff" size=2 face=Consolas><font color="#0000ff" size=2 face=Consolas><font color="#0000ff" size=2 face=Consolas>End</font></font></font><font size=2 face=Consolas><font size=2 face=Consolas> </font></font><font color="#0000ff" size=2 face=Consolas><font color="#0000ff" size=2 face=Consolas><font color="#0000ff" size=2 face=Consolas>Sub
</font></font></font>

---

3) Edited By Cyrus Najmabadi (11/28/2012 6:57:13 PM)

---

4) Edited By Cyrus Najmabadi (11/28/2012 6:57:14 PM)

Resolved with changeset 24755: Don't provide introduce var on 'addressof' in a delegate constructor.

---

5) Edited By Binyam Kelile (11/28/2012 6:57:15 PM)

Verified as fixed and closed.

---

6) Edited By Jeremy Meng (11/28/2012 6:57:17 PM)

This still repros.&#160; Light bulb offers three options after selecting &quot;AddressOf Foo&quot;:

&#160;

extract method

introduce ...

introduce ... for all ...

---

7) Edited By Jeremy Meng (11/28/2012 6:57:17 PM)

introduce variable will generate code with error:

&#160;

SourceCode.vb(10) : error BC32008: Delegate 'System.Action(Of System.Exception)' requires an 'AddressOf' expression or lambda expression as the only argument to its constructor.

---

8) Edited By Dustin Campbell (11/28/2012 6:57:18 PM)

This probably regressed when Cyrus made&#160;EM and IEV use a white list.

---

9) Edited By Kevin Pilch-Bisson (7/1/2013 8:41:05 AM)

There is no smart tag anymore, but if you select the highlighted chunk, this still repros.

---

10) Edited By Prakash Balasubramanian (4/1/2014 4:58:17 PM)

We still offer refactorings for this case which results in compilation errors when applied.

---

11) Edited By Dustin Campbell (4/14/2014 9:39:49 AM)

Extract Method should expand in this case.

---

12) Edited By Balaji Krishnan (7/10/2014 12:04:11 PM)

Yep, Ctrl R,M (Extract method command) also produces the same incorrect result. If selection expansion handles this correctly, then both workflows will be fixed.

---

16) Edited By Kevin Pilch-Bisson (2/15/2015 9:15:36 PM)

We can port this as up for grabs.&nbsp; 

---

**Comment by CyrusNajmabadi** [comment]
I'm ok with this behavior.  User may want to be making a set of steps.  it's ok for intermediary steps to be in error to still help them make the changes they may expect to be able to make.

**Comment by sharwell** [comment]
Reopening; the original issue remains up for grabs. There are two acceptable approaches for fixing this:

1. Continue offering the **Extract Local** functionality for `New Action`, and omit it entirely for `AddressOf Foo`.
2. Offer the **Extract Local** functionality in both locations, but automatically treat both locations as extracting the entire `New Action` expression to a local.

**Comment by CyrusNajmabadi** [comment]
Closing out as this doesn't repro for me at all.
