### ISSUE TITLE
It looks like there is no way to satisfy requirements of warning CS0626 while declaring an extern event

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#19003]
```
class Test
{
    extern event System.Action E1 ;
    extern event System.Action E2 {add; remove;}
    extern event System.Action E3 {add{} remove{}}
}
```

Result:
(3,32): warning CS0626: Method, operator, or accessor 'Test.E1.add' is marked external and has no attributes on it. Consider adding a DllImport attribute to specify the
        external implementation.
(3,32): warning CS0626: Method, operator, or accessor 'Test.E1.remove' is marked external and has no attributes on it. Consider adding a DllImport attribute to specify the
        external implementation.
(4,39): error CS0073: An add or remove accessor must have a body
(4,47): error CS0073: An add or remove accessor must have a body
(5,36): error CS0179: 'Test.E3.add' cannot be extern and declare a body
(5,42): error CS0179: 'Test.E3.remove' cannot be extern and declare a body

Note that an attempt to declare accessors explicitly results in an error, which makes it impossible to apply the DllImport attribute to them.

**Comment by AlekseyTs** [comment]
Perhaps we should support special attribute targets (add/remove) on events.

**Comment by gafter** [comment]
I understand the dilemma, and agree it is unfortunate. However, it appears to be a consequence of the language specification. The compiler is doing nothing wrong. Any change to the compiler (e.g. permitting an accessor without a body) would need to be supported by a language feature change, and a change to the `DllImport` to permit it to be used on an event would need to be supported by a library change.

If you would like to see a change, please open an issue in either the language repo or the core library repo.
