### ISSUE TITLE
Wrong IntelliSense for ParameterExpressions after dynamic variable in same method, if expression is using the dynamic variable as name

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/roslyn#19010]
**Version Used**: 
Microsoft Visual Studio Enterprise 2017
Version 15.1 (26403.7) Release
VisualStudio.15.Release/15.1.0+26403.7
Microsoft .NET Framework
Version 4.6.01586

**Steps to Reproduce**:

1.  define dynamic variable (e.g. ExpandoObject)
2.  define expression variable (e.g. ParameterExpression) using var and use the dynamic variable as name
3. look at IntelliSense tooltip of expression variable

**Expected Behavior**:
The tooltip should show the expression type e.g. ParameterExpression

**Actual Behavior**:
The tooltip shows dynamic as the type.
Apparently it happens to all later expression variables.
It apparently only happens to expressions, the methodinfo in the repro is correct.
The code itself is obviously broken, as the name of the parameterExpression should not be ``input`` but instead be ``"input"``.
That's how I stumbled upon it, if i change it to be ``"input"`` it works.

Screenshot:
![dynamicrepro](https://cloud.githubusercontent.com/assets/7989549/25422882/cc76a5f6-2a62-11e7-8155-cd9147c4635b.png)

Repro:
```csharp
dynamic input = new ExpandoObject();
input.Id = "1234567890";
var paramExpression = Expression.Parameter(typeof(object), input); // shows up as dynamic in tooltip
var genMi = typeof(Program).GetMethod("Test", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static); // shows up correctly as MethodInfo in tooltip
var functor = Expression.Lambda<Action<object>>(Expression.Call(null, genMi, paramExpression), paramExpression); // shows up as dynamic in tooltip
```

**Comment by Pilchie** [comment]
This is correct.  The resultant type *is* dynamic.  Any method call where one of the parameter types is dynamic is treated as a dynamic call and the result is dynamic.
