### ISSUE TITLE
Autocomplete inserts unnecessary qualified name of type when member is of the same name

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#19011]
**Version Used**:  2.2.0.61618

**Steps to Reproduce**:
```C#
enum Test { }
class Program
{
    static Test[] Test;
    static void Main()
    {
        Test = new |
    }
}
```

**Actual Behavior**:

At this point, autocomplete inserts `global::Test` (or `ConsoleApp1.Test`) upon pressing <kbd>[</kbd> which is immediately marked as unnecessary and offered to be removed. (Same for instance members.)

**Expected Behavior**:

Do not insert what is to be removed.

**Comment by Pilchie** [comment]
I thought this was a dupe, but I can't see it right now. @rchande Does it look familiar to you?

**Comment by rchande** [comment]
Looks similar to https://github.com/dotnet/roslyn/issues/9763

**Comment by Pilchie** [comment]
Ah yes, though that's about the type instead of another member, so leaving this open for now.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback on this issue.
