### ISSUE TITLE
Autocomplete prefers case insensitive match 

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#19012]
**Version Used**: 2.2.0.61618

**Steps to Reproduce**:
Case 1:
```C#
enum Test { }
class Program
{
    Test Test;
    public Program(Test test)
    {
        Test = t|
    }
}
```
Case 2 adding:
```C#
public Program(int test) : this((Test)te|
```

**Actual Behavior**: Autocomplete preselects `Test` rather than `test` - even when you spell out `test` completely, so pressing <kbd>;</kbd> changes it to `Test = Test;` (<kbd>)</kbd> to `this((Test)Test)` respectively).

**Expected Behavior**: case matching results to be preferred over case insensitive matches, and especially full case sensitive match to win any time.

**Comment by Pilchie** [comment]
I suspect the enum pre-selection code is what is making the upper-case one win.

**Comment by CyrusNajmabadi** [comment]
Closing out, this is working as expected:

![image](https://user-images.githubusercontent.com/4564579/198742019-ff265edc-f632-487a-a04d-adc5d36e4b69.png)

![image](https://user-images.githubusercontent.com/4564579/198742061-d5b53c54-f8d0-4809-9709-a301b699aea6.png)
