### ISSUE TITLE
Determine upgrade plan for compiler-diagnostics-controlling options looks like

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#19026]
The current plan for .editorconfig is to remove the ability to control core compiler diagnostics via .editorconfig in by default 15.3, moving consumption to either a major version (where we can potentially make a breaking change) or under some sort of other /langver or equivalent opt-in switch. This bug will track designing that piece.

**Comment by sharwell** [comment]
It is my understanding that the ability to control core diagnostic severity was never added to the current .editorconfig implementation, making this a planning item only. Is that correct?

**Comment by jasonmalinowski** [comment]
@sharwell: yes. I want to at least have us think through future problems there so we know what the upgrade plan looks like, especially in light of backcompat concerns, before we ship 15.3 and discover we painted ourselves into a corner. I don't think we have issues but want to have at least a strawman.

**Comment by sharwell** [comment]
We should reserve the properties in the documentation at the same time (and in the same way) we provide the ability to set the severity of diagnostics reported by analyzers, but just not hook them up to the compiler. Aside from that, we just have to define the relative priority of **.editorconfig** next to rule set files and the project file's built-in way to disable warnings or set specific warnings as errors.

**Comment by jasonmalinowski** [comment]
We ultimately landed with `dotnet_diagnostic.<code>.severity` being a settable property, using the values as mentioned in https://github.com/dotnet/roslyn/pull/36566. And it overrides per @sharwell's old comment.
