### ISSUE TITLE
introduce variable generates Let clause in wrong location in aggregate context

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#1902]
Ported from TFS WorkItem: **531203**

---

Select `Math.Abs(x) > 1` and introduce variable

**Repro Steps:**

``` VB
Module Program
    Sub Main()
        Dim q = Aggregate x In {0, 1, 2} Into Count(Math.Abs(x) > 1) ' Introduce variable
    End Sub
End Module
```

_Actual_:

``` VB
Module Program
    Sub Main()
        Dim q = Let v = Math.Abs(x) > 1 Aggregate x In {0, 1, 2} Into Count(v) ' Introduce variable
    End Sub
End Module
```

_Expected_:

``` VB
Module Program
    Sub Main()
        Dim q = Aggregate x In {0, 1, 2} Let v = Math.Abs(x) > 1 Into Count(v) ' Introduce variable
    End Sub
End Module
```

---

**Revisions:**

1) Created By HeeJae Chang (11/28/2012 9:23:37 PM)

---

2) Edited By HeeJae Chang (11/28/2012 9:23:38 PM)

Associated with changeset 29671: let argument in aggregate function be extractable

---

3) Edited By Kevin Pilch-Bisson (2/15/2015 9:10:23 PM)

Port to GitHub

---

**Comment by CyrusNajmabadi** [comment]
Unlikely to do anything special here absent enough customer complaints about this behavior.
