### ISSUE TITLE
Update the project systems to include .editorconfig files in the fast up-to-date check

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#19029]
The legacy project system will need to have it's up-to-date checks updated to recognize that .editorconfigs are a new input into the system.

**Comment by Pilchie** [comment]
Sadly, this editorconfig work isn't going to fit for 15.3, but we're going to continue targeting the next foundation update.

**Comment by jasonmalinowski** [comment]
This was done by @tmeschter.
