### ISSUE TITLE
Add a notification in Tools > Options if an .editorconfig is overriding your project settings

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#19030]
If you go into Tools > Options and have an .editorconfig overriding something somewhere, we should show that fact there, and give you a way to view the list of files actually impacting it.

**Comment by Pilchie** [comment]
Sadly, this editorconfig work isn't going to fit for 15.3, but we're going to continue targeting the next foundation update.

**Comment by dpoeschl** [comment]
Unfortunately not getting to this editorconfig work in 15.5, but we will target the next foundation update.

**Comment by sharwell** [comment]
Also reported here:

🔗 https://developercommunity.visualstudio.com/content/problem/549315/visual-studio-1602-c-code-style-formatting-spacing.html
🔗 https://developercommunity.visualstudio.com/content/problem/549337/visual-studio-1602-editor-keep-tabs-option-inserts.html
