### ISSUE TITLE
Type inference should infer enumerable item type inside a lambda

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#1903]
Ported from TFS WorkItem: **726766**

------------------------------

**Repro Steps:**

1. Paste this code

```C#
using System.Collections.Generic;
using System.Linq;
 
class A { }
class B { }
class C
{
    IEnumerable<B> GetB(IEnumerable<A> a)
    {
        return a.Select(i => Foo(i));
    }
}
```

2. Invoke Generate Method on Foo

&nbsp;

*Expected*:
```C#
private B Foo(A i)
```

*Actual*:
```C#
private object Foo(A i)
```
------------------------------

**Revisions:**

1) Created By Kirill Osenkov (6/28/2013 1:30:35 PM)

------------------------------

2) Edited By Kirill Osenkov (6/28/2013 1:32:05 PM)

Dev12 generates this, which is equally useless:

&#160;
<font face=Consolas>

</font><font color="#0000ff" face=Consolas><font color="#0000ff" face=Consolas>private</font></font><font face=Consolas> <font style="BACKGROUND-COLOR:#ffff00;">TResult</font> Foo(</font><font color="#2b91af" face=Consolas><font color="#2b91af" face=Consolas>A</font></font><font face=Consolas> i)

{

</font><font color="#0000ff" face=Consolas><font color="#0000ff" face=Consolas>&#160;&#160;&#160; throw</font></font><font face=Consolas> </font><font color="#0000ff" face=Consolas><font color="#0000ff" face=Consolas>new</font></font><font face=Consolas> </font><font color="#2b91af" face=Consolas><font color="#2b91af" face=Consolas>NotImplementedException</font></font><font face=Consolas>();

}
</font>

------------------------------

3) Edited By Kevin Pilch-Bisson (7/1/2013 9:20:58 AM)

Yes, this would be a nice improvement.

------------------------------

**Comment by bmay2** [comment]
I believe I've got a fix for this one.

**Comment by balajikris** [comment]
@bmay2 : Thanks for the submission!
