### ISSUE TITLE
[Suggestion] Add not null attribute flags to parameters

### ISSUE THREAD

**Issue by henrikklarup** [dotnet/roslyn#19040]
Add some kind of attribute flags for parameters to defined that null is not a valid value. Something like this.

`public int returnX ([NotNull] Point firstParam) 
{
    // Here we don't need to null-check because the parameters is marked.
    return firstParam.X;
}`

**Comment by miloush** [comment]
Language proposals are now in the `csharplang` repo. See https://github.com/dotnet/csharplang/issues/403

(Not sure if your example was meant to be illustrational only, but I would expect `Point` to be a struct and therefore non-nullable.)

**Comment by jcouv** [comment]
As pointed out above, there is a proposal on csharplang. The "non-nullable reference types" feature is being worked on in a C# 8.0 prototype. Mads recently gave an [overview](https://channel9.msdn.com/Blogs/Seth-Juarez/A-Preview-of-C-8-with-Mads-Torgersen) of the current thinking. 
Stay tuned :-)
