### ISSUE TITLE
Revert workaround for AsyncSemaphore disposal problems

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#19042]
After we update Roslyn to a version of vs-threading which includes the change in Microsoft/vs-threading#105, the workaround in pull request #19043 should be reverted.

**Comment by Pilchie** [comment]
When do we expect to update to a new version?  Probably not before 15.3?

**Comment by sharwell** [comment]
@Pilchie There is no expected update time frame yet. The upstream fix was closed as a tentative wontfix, so we'll see where things go.

**Comment by CyrusNajmabadi** [comment]
@sharwell still anything to do here?  can we close this out if not?

**Comment by sharwell** [comment]
@CyrusNajmabadi The workaround can likely be removed now.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this needs to be done, assign to a person/milestone so it is done.
