### ISSUE TITLE
Compiling scripts targetting .Net 3.5 not possible due to how script entry point is generated

### ISSUE THREAD

**Issue by fabianoliver** [dotnet/roslyn#19048]
**Version Used**: Roslyn 2.0.0

**Steps to Reproduce**:

Set up a project, adding net 3.5 reference assemblies (mscorlib, System) as well as the TPL for .Net 3.5  (https://www.nuget.org/packages/TaskParallelLibrary), and to AsyncBridge (https://www.nuget.org/packages/AsyncBridge.Net35/).

Add a document with SourceCodeKind.Script, and compile project.

**Expected Behavior**:

Project should compile

**Actual Behavior**:

Compilation fails with ErrorCode.ERR_MissingPredefinedMember as Roslyn cannot find the .GetAwaiter() method for the Task-type.

--

As far as I see it, the issue is caused by

CSharpCodeAnalysis\Symbols\Synthesized\SynthesizedEntyrPointSymbol
line 45: GetRequiredMethod(taskType, WellKnownMemberNames.GetAwaiter, diagnostics);

When targetting .Net v3.5 with the two libraries from above, the Task type doesn't contain a GetAwaiter() method; rather, this is provided only as an extension method by AsyncBridge.

From what I see, this might be the only thing preventing scripts from targetting net 3.5, so hopefully this might be worth addressing?

You'll most likely have better potential solutions in mind; but some ideas,

1. Look for the extension method specifically if Task-type doesn't contain a GetAwaiter method (probably not a great approach)

2. Allow us to take care of creating the entry points ourselves, maybe by defining custom SynthesizedEntryPointSymbol-derived types and e.g. specify as an option to use these for compilation

3. Give us an option to disable creating an entry point for scripts altogether. Would be best for my personal use case - I'm using script-.documents as the way Roslyn transforms their syntax etc. is very useful, but I'm invoking the factory method myself via Reflection & don't need an entry point. I've read a few posts by people doing something similar, so there might be some demand for this

**Comment by tmat** [comment]
Why is this important? We do not support NET 3.5.

**Comment by fabianoliver** [comment]
Just to make sure we'on the same page - I'm refering to the target framework version of the output assembly that Roslyn produces upon compilation, not of the application that actually uses Roslyn to compile it.

Correct me if wrong; my impression was that Roslyn is pretty agnostic towards framework versions (i.e. could even compile an assembly targetting .Net 2.0, if you wanted to/took care of the references) -
of course there may be some necessary limitations when syntax rewriting takes place, like in the scripting case. It'd certainly be very useful to have a broad range of supported project setups though.


"Why is this important?" -
for the same reason Visual Studio still supports .Net 2.0 projects I assume; to be able to target a wide range of machine setups that may use the compiled assembly one way or the other.

I think Roslyn's scripting features can be used for much more than what they were probably originally intended for.

Very specific, but in my case, I'm working on a C# editor for Excel; 
Users can write code with global functions (similar to VBA) into Documents with SourceCodeKind.Script, saving me a *lot* of hassle with syntax transformation/projection etc. - this is compiled into an Assembly. Later on, an XLL AddIn is created which hosts the CLR, loads that generated assembly, instantiates the script class (= calls the factory method), and exposes its functions as UDFs/Macros to Excel. It'd be useful if that AddIn could target older framework versions too for maximum compatibility; while the editor itself needs .Net 4.6, the generated addin does not and might be shared with users on outdated .Net versions.

**Comment by tmat** [comment]
@fabianoliver Thanks for providing details of your scenario. Having a concrete scenario helps prioritizing. I still think it's kind of lower priority compared with other scripting work items, but feel free to submit a PR.

**Comment by tmat** [comment]
@agocke @AlekseyTs "Async Main" feature is likely using similar pattern as scripting, so this might be an issue for Async Main as well. Can we unify some code and fix both if so?

**Comment by tmat** [comment]
//cc @TyOverby

**Comment by TyOverby** [comment]
This is actually one of the issues that I've solved already for Async-Main.  I should be able to port the fix over to the scripting fairly easily.

**Comment by tmat** [comment]
@TyOverby Cool!

**Comment by MattGertz** [comment]
This needs to be in by Thursday 6/1, or deferred to 15.6.

**Comment by TyOverby** [comment]
@fabianoliver: Can you share a csproj file with the referenced script that causes this behavior?  I have a PR that I believe solves the issue, but I can't get your original failure to reproduce.

Here's my attempt to repro: https://github.com/TyOverby/script-35-repro

**Comment by TyOverby** [comment]
@fabianoliver 

Using the code in #19623, the following code works now:

```c#
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis;

namespace Scripttest
{
    class Program
    {
        static int Main(string[] args)
        {
            // Obviously change this to point to your own dlls.
            MetadataReference corlib = MetadataReference.CreateFromFile(@"C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll");
            MetadataReference asyncBridge = MetadataReference.CreateFromFile(@"C:\Users\tyoverby.REDMOND\Documents\Visual Studio 2017\Projects\Script 35 Repro\Script 35 Repro\bin\Debug\AsyncBridge.Net35.dll");
            MetadataReference threading = MetadataReference.CreateFromFile(@"C:\Users\tyoverby.REDMOND\Documents\Visual Studio 2017\Projects\Script 35 Repro\Script 35 Repro\bin\Debug\System.Threading.dll");

            var syntax = CSharpSyntaxTree.ParseText(
                text: "var x = 1;", 
                options: CSharpParseOptions.Default.WithKind(SourceCodeKind.Script));

            var compilation = CSharpCompilation.Create(
                assemblyName: "my_assembly", 
                options: new CSharpCompilationOptions(OutputKind.ConsoleApplication).WithUsings("AsyncCompatLibExtensions"),
                syntaxTrees: new[] { syntax }, 
                references: new[] { corlib, asyncBridge, threading});

            var result = compilation.Emit("./out.exe");

            return result.Success ? 0 : 1;
        }
    }
}
```

**Comment by fabianoliver** [comment]
@TyOverby 

Great!! Pretty much exactly the same example code I was testing with / that was failing in the previous version. So agree, if above succeeds now the issue is fixed.

Thanks a lot for looking into/fixing this,
Fabian

**Comment by TyOverby** [comment]
@fabianoliver Good to hear!  Just remember to include the `WithUsings("AsyncCompatLibExtensions")` call!
