### ISSUE TITLE
Initialize Interactive with Project Context doesn't appear for .NET Core projects

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#19050]
Right-clicked on a project in .NET Core solution and this capability didn't show up at all...

**Comment by shaggygi** [comment]
@kuhlenh check this issue out... https://github.com/dotnet/project-system/issues/223

I originally added to Roslyn repo, but @srivatsn moved to project-system repo.

**Comment by kuhlenh** [comment]
Thanks @shaggygi ! Resolving as dupe.
