### ISSUE TITLE
ReferenceHighlighting tests are flaky

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#19059]
The following tests have been failing sporadically recently.

CSharpReferenceHighlighting.WrittenReference
BasicReferenceHighlighting.Highlighting

One example where they both failed is:
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/3340/

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving out.

**Comment by CyrusNajmabadi** [comment]
Closing out.  These tets are running and passing without issues.
