### ISSUE TITLE
Brace highlighting shouldn't have a tagger delay when you type )

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#1906]
Ported from TFS WorkItem: **929503**

------------------------------

**Repro Steps:**

Right now, when you type ) or ] or any closing brace, we don't highlight the brace you just closed and it's matching open brace until a half second or so. This breaks a core scenario: where you're closing lots of parentheses and you are trying to figure out if you got them all. Instead of immediately seeing which pair you matched, you have to wait a half second, see you missed a few, type another few parentheses, wait again etc.

&nbsp;

We should tweak the tagger to have a tagger delay of zero when you typed a close brace. It can still be asynchronous.

------------------------------

**Revisions:**

1) Created By Jason Malinowski (4/19/2014 11:29:09 AM)

------------------------------

2) Edited By Kevin Pilch-Bisson (2/15/2015 8:51:53 PM)

Port to GitHub as Up For Grabs in the &quot;Unknown&quot; milestone.

------------------------------

**Comment by AdamSpeight2008** [comment]
:+1: Yes please.

**Comment by thorgeirk11** [comment]
:+1: Indeed

**Comment by CyrusNajmabadi** [comment]
Using TaggerDelay.NearImmediate is probably more appropriate than 0.

**Comment by balajikris** [comment]
It is currently using NearImmediate, which has a delay of 50 milliseconds (haven't checked source for accuracy). Either the bug is now out of date, or Jason meant that we do better than NearImmediate

**Comment by jasonmalinowski** [comment]
Yes, NearImmediate is too slow. If you're trying to play "match a brace" visually it's horrible.

**Comment by Pilchie** [comment]
See also internal bug 1213278

**Comment by cremor** [comment]
Is this related to the problem that for some users the brace highlighting of existing braces isn't immediate any more in VS2015? Some background here: http://stackoverflow.com/questions/31724771/how-do-i-get-visual-studio-2015-to-highlight-brackets-braces-and-references-ins

**Comment by Pilchie** [comment]
For C# and VB this is almost certainly the same issue.  Roslyn is not involved in css which is mentioned in the StackOverflow post however.

**Comment by CyrusNajmabadi** [comment]
Going to see if this reproes.  One thing that I changed when I did the tagger rewrite was the enormous amount of batching/throttling/transition-delays that could occur as we bounced around our threads.  i.e. we'd first throttle incoming events, causing a delay.  Then we'd wait a certain amount of time based on the feature.  Then we'd compute the results.  Then we'd delay reporting the UI thread.  Then we'd batch and throttle again.  Then we'd report the results.

Now pretty much it's just "event happened?  kick off background work on the delay the feature requested".    Results computed and collected and batched and reported with no more than a 50ms time window.  So for something 'near immediate', the total delay introduced should only be 50ms+50ms, whereas previously it could be several hundred (there were parts where we even hardcoded in a full 250ms pause) ick.

**Comment by CyrusNajmabadi** [comment]
Ok.  So I think the experience is now totally acceptable (and i'm including a a gif to show what it's like).  Highlighting is so fast that it's very easy to tell what the matching brace is.  Highlighting keeps up with almost no perceptible delay when typing or moving the caret.  As such, i'm going to close this as I think the current behavior is fine.

![bracematching](https://cloud.githubusercontent.com/assets/4564579/10290072/d24821b6-6b56-11e5-9146-6aa44b33157e.gif)

**Comment by cremor** [comment]
This looks indeed fine. But it's certainly not as fast for everyone:
![brace highlight lag](https://cloud.githubusercontent.com/assets/116314/10301031/884c2ae6-6bfe-11e5-846c-e7bd1ec8ff35.gif)

As you can see, I have a very noticeable delay. If I move the cursor as fast as you did, nothing other than the first and last pair of braces will be highlighted. Interestingly, the highlighting of in-between braces isn't cancelled if I type the closing braces. But it lags so far behind that I always type one brace to many when I stop as soon as I see the first opening brace highlighted.

This is on a quite fresh Windows 7 SP1 x64 VM (using Oracle VirtualBox) with Visual Studio 2015 RTM. Everything is up to date and Visual Studio was even started in Safe Mode. The machine is fast enough and the VM has access to enough resouces of it (Core i5, all 4 cores available for VM, 6 GB RAM for VM). VS2013 didn't have that problem.

**Comment by CyrusNajmabadi** [comment]
@cremor My gif was not from RTM.  It was from a recent build that includes my "tagger rewrite" changes.  These changes included many tweaks to address the overall latency problem involved with the old system.  You should be able to get these fixes once the next update to VS goes out.

**Comment by cremor** [comment]
Ok, great. Thanks!
