### ISSUE TITLE
What's new in Roslyn NuGet package 2.1?

### ISSUE THREAD

**Issue by myblindy** [dotnet/roslyn#19076]
I can't find any change logs, is it safe to use? I've been having the VS2017 C# compiler crash every other compilation (and/or return -2146232797) and I'd love to try a newer version, but installing the package does nothing different. What version of the compiler did I have before? I can't even tell that.

**Comment by agocke** [comment]
@myblindy The difference between 2.0.0 and 2.1.0 is very small -- just a change to the .exe.config for the compilers to mandate running on frameworks >= .NET 4.6 and a change to an error message for tuples.

Did you file a bug for your compiler crash?

**Comment by myblindy** [comment]
I wish I could, but I can't release the code since it's proprietary and I'm fairly certain it's because of the size of the codebase/class and the number of compiler-generated items (inner functions, nested lambda functions, etc). 

It really is annoying though, 2 out of 3 compilation attempts fail and the 3rd succeeds most of the time, except if I make some very specific code changes then it refuses to compile at all (despite it being legal code).

**Comment by jasonmalinowski** [comment]
@myblindy Please file a bug so we can track it. Even if you can't share code (don't worry, that's the common case) there's still logging and other information we can work with you to collect which can help us understand what is going on.

**Comment by myblindy** [comment]
@jasonmalinowski Very well, I'll set up an issue for it. You can mark this closed by the way, @agocke answered my initial question.
