### ISSUE TITLE
Roslyn supplies TargetFrameworkMoniker (and other params) incorrectly in help query

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#1907]
Ported from TFS WorkItem: **937176**

------------------------------

**Repro Steps:**

1. New C# console app

2. Type DateTime.Now.ToString() inside the Main method

3. Press F1 (cursor being on ToString or adjacent&nbsp;parentheses)

&nbsp;

**Expected:**

a DateTime.ToString page for .NET 4.5(.1) should open<BR>

****&nbsp;

**Actual**:

the following MSDN page opens:

[http://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&amp;l=EN-US&amp;k=k(System.DateTime.ToString);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.5);k(DevLang-csharp)&amp;rd=true](http://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&amp;l=EN-US&amp;k=k(System.DateTime.ToString);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.5);k(DevLang-csharp)&amp;rd=true)

which is related to .NET Micro Framework version 2.0, 2.5 (though the DateTime.ToString keyword is correct).

&nbsp;

**Note** that additional parameters in help query (TargetFrameworkMoniker and&nbsp;DevLang) are separated from their values with hyphens (-), not equal signs (=). Changing them to equal signs fixes the query:<BR>[http://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&amp;l=EN-US&amp;k=k(System.DateTime.ToString);k(TargetFrameworkMoniker=.NETFramework,Version%3Dv4.5);k(DevLang=csharp)&amp;rd=true](http://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&amp;l=EN-US&amp;k=k(System.DateTime.ToString);k(TargetFrameworkMoniker=.NETFramework,Version%3Dv4.5);k(DevLang=csharp)&amp;rd=true)&nbsp;- this is indeed a&nbsp;.NET 4.5 page

Could it be the case that Roslyn (or someone else) has a typo in help query&nbsp;generation code?<BR>

------------------------------

**Revisions:**

1) Created By Andrew Stasyuk (4/30/2014 2:34:24 PM)

------------------------------

2) Edited By Kevin Pilch-Bisson (2/15/2015 9:14:33 PM)

Port to github and mark as up for grabs.

------------------------------

**Comment by balajikris** [comment]
The help query is still the same as of today [query](https://msdn.microsoft.com/query/dev14.query?appId=Dev14IDEF1&l=EN-US&k=k(System.DateTime.ToString);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6);k(DevLang-csharp)&rd=true) but it does navigate to the correct documentation today. 

Query: https://msdn.microsoft.com/query/dev14.query?appId=Dev14IDEF1&l=EN-US&k=k(System.DateTime.ToString);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6);k(DevLang-csharp)&rd=true

Help page: DateTime.ToString() for .NET Framework 4.6 and 4.5.

**Comment by balajikris** [comment]
Implementation wise, I think Roslyn does not get generate the whole query string. We implement [IVsLanguageContextProvider.UpdateLanguageContext](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/LanguageService/AbstractLanguageService%25602.IVsLanguageContextProvider.cs,0e5e624735979891) and set the `devlang` attribute appropriately. So, some other Visual studio component is generating the whole string.

**Comment by balajikris** [comment]
On closer inspection, it does navigate to the incorrect page, but only if the target framework is set to ".Net Framework 4.5". It works correctly for every other framework version from 2 to 4.6.

**Comment by Pilchie** [comment]
Does our code set the TFM, or should this bug be moved elsewhere?

**Comment by balajikris** [comment]
so far i didn't find a place in roslyn source that sets it. But I also don't yet know who sets it, I'm looking through to find which component would set it.

**Comment by balajikris** [comment]
Not entirely sure what's the issue here, but its something to do with determining online vs offline help string. 

GetHelpUrl() in env\msenv\vsbrowse\hlpextsrvc.cpp

```C++
if ( key.CompareNoCase(L"TargetFrameworkMoniker") == 0)
{
	// targetmoniker  format = framework,version[,profile]
	int c = value.Find(L",");
	if (c > 0)
	{
		c = value.Find(L",", c + 1);
	}
	if ( c > 0 )
	{
		url.AppendFormat(L";k(TargetFrameworkMoniker-%s)", UrlEncode(value.Left(c)));
	}
	else
	{
		url.AppendFormat(L";k(TargetFrameworkMoniker-%s)", UrlEncode(value));
	}
}
```

**Comment by balajikris** [comment]
@Pilchie - any idea which team i should file a bug for?

**Comment by balajikris** [comment]
Filed internal bug 1181750 for the Shell team. Closing this bug as External.
