### ISSUE TITLE
Solution.WithDocumentSourceCodeKind - Changes aren't applied properly

### ISSUE THREAD

**Issue by fabianoliver** [dotnet/roslyn#19079]
**Version Used**: 2.1.0

**Steps to Reproduce**:

See attached code file for a full example:

[UpdateSourceCodeKindExample.cs.txt](https://github.com/dotnet/roslyn/files/965067/UpdateSourceCodeKindExample.cs.txt)

**Expected Behavior**:

Code should run through without errors when instantiating the example class, meaning the solution should correctly have been updated and contain a document with an updated SourceCodeKind

**Actual Behavior**:

Exception is being thrown at "3 - SourceCodeKind not synchronized", meaning the Workspace's active solution's document still has the original SourceCodeKind

----------

Quick description:

I create a solution with 1 project that contains 1 document with some given SourceCodeKind.
I then call Solution.WithDocumentSourceCodeKind to change this document's SourceCodeKind (e.g. from Script to Regular).
The solution returned by this operation looks correct - the new/updated solution contains 1 project with 1 document that has the updated SourceCodeKind.
I then call Workspace.TryApplyChanges with this updated solution;  that returns true as well.
Oddly though, afterwards, Workspace.Solution does *not* seem to updated - it still contains the Document with its original, non-updated SourceCodeKind.

**Comment by Pilchie** [comment]
@fabianoliver if you want to take a look yourself, this should eventually get updated [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Workspace.cs,816), via [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Workspace.cs,1307)

**Comment by fabianoliver** [comment]
That's a bit strange. Above code runs fine for me when I'm creating & linking a project against the respective Roslyn projects directly and compile from scratch. Both for my original github Roslyn clone, which was a few weeks out of date, as well as a live resync; and both in debug as well as release builds.

Yet it fails with the behavior described above when I'm using the Roslyn assemblies from Nuget; both for v.2.1.0 as well as v2.0.0.

**Comment by Pilchie** [comment]
Check the history, maybe we fixed it :)

--
Kevin Pilch
https://twitter.com/Pilchie
________________________________

**Comment by fabianoliver** [comment]
I think you're right..!

v2.1.0 was released on Nuget on April 21, I assumed this was in line with the Github-version of around the same date.

But ILSpy tells me the v2.1.0-Workspace type doesn't have a "OnDocumentInfoChanged" method, which was added with a Commit on Feb 17 ( https://github.com/dotnet/roslyn/commit/a7a9dcbe79e23fe09242f0e0a05fe527e5be0e69 ), so must be some earlier version - and I think that commit fixed the issue too.

**Comment by Pilchie** [comment]
That's quite likely - most of our focus has been on the 2.3 branch, with only a couple of very impactful fixes going to the 2.1 and 2.2 branches.

Sounds like this can be closed as fixed in 2.3.
