### ISSUE TITLE
VB: language version flag 15.3 not properly passed to project system

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#19075]
Repro:
- Create a VB proj and set language version to 15.3 (in the proj file)
- Type a tuple with inferred names and use the inferred names
- If you build the project, it will build properly
- But the IDE will show red squiggles (it is using language version Default)

**Comment by AdamSpeight2008** [comment]
Default is tied to latest major release, `15.0`.

**Comment by jcouv** [comment]
From discussion with @srivatsn, only the new project system has a generic way of passing the whole command-line through. 
The old project system has to go through the un-managed API (`CVbcMSBuildHostObject::SetLanguageVersion`). That method needs to convert from language version as a string ("15.3") to an enum value (`VisualBasic15_3 = 1503` in this case).
Note: the corresponding method for Csc (`CCscMSBuildHostObject::SetLangVersion`) doesn't have that problem (it is just a pass-through).

@srivatsn It would be great if someone from your team could help with that. Thanks

FYI @jasonmalinowski

**Comment by jcouv** [comment]
One more thing: while making this change, let's also make sure that language version "Latest" is passed properly (`Latest = Integer.MaxValue`, but it's probably better to pass the specific version, `1503`).

**Comment by srivatsn** [comment]
Can you file a bug in the project-system repo for this?

**Comment by jcouv** [comment]
Issue moved to [dotnet/project-system #2088](https://github.com/dotnet/project-system/issues/2088) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jcouv** [comment]
Looks like we can fix this without project system change. Re-opening compiler issue.

**Comment by jcouv** [comment]
Fixed by #19112

**Comment by AdamSpeight2008** [comment]
@jcouv Are you sure this is fixed as i am using `15.8.0 Preview 1.1` and it doesn't seem to be passing the language version.

**Comment by jcouv** [comment]
@AdamSpeight2008 I tried it just now (`Version 15.8.0 Preview 2.0 [27715.0.d15.8]`) by creating a VB class library with .NET Framework, then using a VB 15.5 feature (non-trailing named arguments), manually setting the `<LangVersion>15.5</LangVersion>` in the project file, and it worked as expected.

If there is an issue that you can repro, please file it with details in the project-systems repo (consider linking to https://github.com/dotnet/project-system/issues/3411 which was the most recently fixed issue regarding VB and LangVersion).
Thanks
