### ISSUE TITLE
AutomaticEndConstructCorrector has unlocalized UI strings

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#19087]
Here: https://github.com/dotnet/roslyn/blob/9745b0fa5c6d451d7eaffb4bdbd903f0a39d25d0/src/EditorFeatures/VisualBasic/AutomaticEndConstructCorrection/AutomaticEndConstructCorrector.vb#L69

**Comment by Pilchie** [comment]
This isn't a regression, and IntelliSense is a trademark that doesn't get localized anyway...
