### ISSUE TITLE
investigate flaky netcore tests

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#19090]

**Comment by Pilchie** [comment]
@jmarolf should this go on `dotnet/project-system`?

**Comment by jmarolf** [comment]
@Pilchie the tests live in this repo.  I don't know the strategy, perhaps?

**Comment by Pilchie** [comment]
Fair point, but there is no appropriate Area label to classify this.  @srivatsn where would you like to track it?

**Comment by srivatsn** [comment]
Let's just move to the project-system repo so that there's place to look at all project system bugs.

**Comment by srivatsn** [comment]
This issue was moved to dotnet/project-system#2092

**Comment by sharwell** [comment]
@srivatsn Reopening this because the tests still exist in Roslyn, and are un-skipped as part of the work in #25151. Please review the approach and let me know if this is good or we need to do something else.

**Comment by Neme12** [comment]
@sharwell Is this fixed with #25151?
