### ISSUE TITLE
Field missing from completion list

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#19101]
**Version Used**: 15.0.0+26228.12

First noted: https://github.com/dotnet/roslyn/issues/18359#issuecomment-293069534

I don't believe this is directly related though because this has nothing to do with `switch` and the missing entry is a field.

**Steps to Reproduce**:

1. File > New Solution > C# Console App
2. Add reference to Microsoft.VisualStudio.Shell.15.0 
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.Shell.15.0.dll`
3. Use following code:

```CSharp
using Microsoft.VisualStudio;

namespace IntellisenseBug
{
    class Program
    {
        static void Main(string[] args)
        {
            var x = VSConstants.VsStd14;
        }
    }
}
```

4. Try to get completion for the field `VSConstants.VsStd14`.

**Expected Behavior**:

`VSConstants.VsStd14` shows up in completion

**Actual Behavior**:

`VSConstants.VsStd14` never shows up, despite appearing to correctly bind to a symbol (QuickInfo and GoToDefinition work on it).

![image](http://i.imgur.com/WEOgHjf.gif)

**Comment by Pilchie** [comment]
This field has `EditorBrowsable(EditorBrowsableState.Never)`
