### ISSUE TITLE
Prohibit to use double quoted title with wiki

### ISSUE THREAD

**Issue by urasandesu** [dotnet/roslyn#19130]
**Version Used**: 
n/a

**Steps to Reproduce**:

1. Clone https://github.com/dotnet/roslyn.wiki.git on Windows

**Expected Behavior**:
All operations should be succeeded.

**Actual Behavior**:
Clone is succeeded but checkout is failed. Because [the title of this page -- it is used as file name -- contains double quote](https://github.com/dotnet/roslyn/wiki/How-to-support-new-C%23-language-features-by-"Edit-And-Continue"-(ENC)).

**Comment by Pilchie** [comment]
I just renamed the page.

**Comment by urasandesu** [comment]
Thank you for the quick response!!
