### ISSUE TITLE
Redundant box in pattern-match

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#19153]
**Version Used**: 

15.3 (master)

**Steps to Reproduce**:

1. Compile the following and examine the IL
``` c#
    public static void M<T, U>(U x) where T : U
    {
        // when T is not known to be a reference type, there is an unboxing conversion from
        // a type parameter U to T, provided T depends on U.
        switch (x)
        {
            case T i:
                Console.Write(i);
                break;
        }
    }
```

**Expected Behavior**:

x is boxed once.

**Actual Behavior**:

x is boxed three times.

**Comment by alrz** [comment]
I think all three boxes here are sensible,

1. first we box to null check (true only for the switch, not is)
2. then we box back to pattern variable type `T`
3. finally we box again to pass it over to `Write` which accept an `object`.

We might be able to skip the first step for single-case switches.

**Comment by alrz** [comment]
One case that I find that it is actually redundant is when you use `is` where `==` suffices.
```cs
if (o is null is false)
```
This boxes a boolean.

**Comment by gafter** [comment]
I am adding the following test to verify the behavior:

``` c#
        [Fact, WorkItem(19153, "https://github.com/dotnet/roslyn/issues/19153")]
        public void RedundantBox()
        {
            var source = @"using System;
public class C
{
    public static void M<T, U>(U x) where T : U
    {
        // when T is not known to be a reference type, there is an unboxing conversion from
        // a type parameter U to T, provided T depends on U.
        switch (x)
        {
            case T i:
                Console.Write(i);
                break;
        }
    }
}";
            var compilation = CreateCompilation(source, options: TestOptions.ReleaseDll);
            compilation.VerifyDiagnostics();
            var compVerifier = CompileAndVerify(compilation);
            compVerifier.VerifyIL("C.M<T, U>(U)",
@"{
  // Code size       37 (0x25)
  .maxstack  1
  .locals init (U V_0)
  IL_0000:  ldarg.0
  IL_0001:  stloc.0
  IL_0002:  ldloc.0
  IL_0003:  box        ""U""
  IL_0008:  isinst     ""T""
  IL_000d:  brfalse.s  IL_0024
  IL_000f:  ldloc.0
  IL_0010:  box        ""U""
  IL_0015:  unbox.any  ""T""
  IL_001a:  box        ""T""
  IL_001f:  call       ""void System.Console.Write(object)""
  IL_0024:  ret
}");
        }
```

There are only two `box` instructions on the input value - one for the `is` test and one for the conversion. It is possible to eliminate one of them, as they produce the same result, but the runtime compiler is optimized to produce good machine code for this pattern of code because it occurs when people write `if (x is int) { var i = (int)x; ...`. So we are going to keep it this way.

The last `box` instruction is to box the user variable `i` for the call to `Write`. That is correct.
