### ISSUE TITLE
Find all references where a collection is modified

### ISSUE THREAD

**Issue by alexschneider-ms** [dotnet/roslyn#19152]
I'd like to propose the following feature request:

* Find all references to a collection where it is assigned to or modified. When I say modified, I mean like when the operations `List<T>.Add()`, `List<T>.Insert()`, `List<T>.Remove/RemoveAt/RemoveAll`, `List<T>.Reverse()`, etc and so on for Dictionaries, Sets, anything under System.Collections. I'm looking to find any method that actually changes the order or number of items in the collection. LINQ/other operations that don't modify the list shouldn't pop up here.

I'm working on a project now where I'm trying to debug why a collection (list) contains the objects that it does. In order to do that, I selected the variable and right clicked/selected "Find All References". However, there are hundreds of references and perhaps only 5 or so references where the collection is actually modified. Most of the references are LINQ/iterations over the list which don't modify the list.

That took me some time to sort through to find the right ones and it seems like something that Visual Studio should be capable of doing.

Currently there is a "Show Only Read Usages" and "Show Only Write Usages" in the "Find Usages" view, but methods that modify a collection only show up under "Read Usages" (for good reason - I'm not suggesting changing this behavior).

**Comment by Pilchie** [comment]
1. Note that Find Usages is actually a ReSharper feature, not a VS one :)
2. I agree that what you propose would be very *useful*, but it's also very hard in general.  There is no metadata that specifies what operations modify a collection, so there is no way to know short of a bunch of heuristics what to find.

**Comment by 333fred** [comment]
@Pilchie, @alexschneider-ms means the rewritten find all references view, not find usages.

I had one thought here: allow me to filter what references show up by method calls, if the symbol is a valid receiver. So for example, I could use find all references on a variable, then filter the references that show up by method invoked. Or, if I was finding all references to a type, filter by all the methods defined on that type (including extension methods). Then, this request would be as simple as filtering down to all the variations of `Add`.

**Comment by Pilchie** [comment]
For the second, if they appear in the preview (as the method calls do), there is already the "Search" filter which can limit stuff.

**Comment by CyrusNajmabadi** [comment]
Unlikely to do this.  Someone could write this as a custom tool if desired.
