### ISSUE TITLE
Matching an expression of type `byte?` with a pattern of type `int` should not be allowed

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#19151]
**Version Used**: 

15.3 (master)

**Steps to Reproduce**:

1. Compile the following
``` c#
    public static void M(byte? x)
    {
        switch (x)
        {
            case int i:
                Console.Write(i);
                break;
        }
    }
```

**Expected Behavior**:

Compile-time error "a value of type `byte?` can never be handled by a pattern of type `int`".

**Actual Behavior**:

Compiles with no error. Pattern never matches.

**Comment by alrz** [comment]
"Compiles with no error." and no warnings? I think it'd be nice to inform the user if a pattern will never match.

**Comment by gafter** [comment]
@alrz A pattern that will never match (based on its type) is intended to be an error. That's why I opened this issue.

**Comment by gafter** [comment]
Note to self: See
``` c#
        internal static ConstantValue GetIsOperatorConstantResult(TypeSymbol operandType, TypeSymbol targetType, ConversionKind conversionKind, ConstantValue operandConstantValue)
```
for many cases of interest.
