### ISSUE TITLE
Update new project system to support watching for appearing/disappearing .editorconfig files

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#19161]
Just like #19029 for the legacy project systems, we also need an update for the new project systems too. The appropriate file watching needs to be updated to make sure that works.

**Comment by Pilchie** [comment]
Sadly, this editorconfig work isn't going to fit for 15.3, but we're going to continue targeting the next foundation update.

**Comment by dpoeschl** [comment]
Unfortunately not getting to this editorconfig work in 15.5, but we will target the next foundation update.

**Comment by jasonmalinowski** [comment]
@tmeschter did this work.
