### ISSUE TITLE
"Add null check" is continuously offered if the parameter is of a type that hasn't been resolved

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19173]
1. CTRL+. on `args`

``` C#
    class Program
    {
        static void Main(String args)
        {
            if (args == null)
            {
                throw new System.ArgumentNullException(nameof(args));
            }

            Console.WriteLine("Hello World!");
        }
    }
```

**Expected:** Not to be offered to "Add null check"
**Actual:** Continuously offered to "Add null check" until "String" is been resolved

**Comment by davkean** [comment]
Interestingly, this doesn't occur if you change `String` -> `String[]`

**Comment by CyrusNajmabadi** [comment]
What do you mean by "Resolved" in this context?

**Comment by davkean** [comment]
I mean if the namespace that contains the type isn't in scope.
