### ISSUE TITLE
"Add argument name" requires you to be on exactly the argument

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19175]
1. CTRL+. at $

``` C#
using System;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine(args$);        
    }
}
```

**Expected:** To be offered to "Add argument name"
**Actual:** Not offered to "Add argument name"

Note, for highlighting usage and goto definition purposes that character position is considered part of the argument.

**Comment by Pilchie** [comment]
@alrz want to take a look?  @CyrusNajmabadi do you know if we have  better for refactorings to use here?

**Comment by CyrusNajmabadi** [comment]
We have a helper called "GetTouchingWordAsync" which may be helpful here.  But, since the last token may not be a keyword/idntifier, we probably just need to check if the current token is ```)``` or ```,```, and we're at the start of it, then just move back one token.
