### ISSUE TITLE
Confusing error span/error message if you forgot a starting brace in async statement lambda

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19178]
I have the follow code, and I've forgotten a brace where indicated:

```
                _projectThreadingService.Fork(async () =>
                    <-- Missing brace
                    // Extremely naive implementation of a Windows Pane logger - the assumption here
                    // is that text is rarely written so transitions to the UI thread are rare. If 
                    // this changes, then we'll need to implement a better queueing mechanism.
                    IVsOutputWindowPane pane = await _outputWindowProvider.GetOutputWindowPaneAsync();

                }, options: ForkOptions.HideLocks | ForkOptions.StartOnMainThread);
            }
```

Hovering over this shows the following:

![image](https://cloud.githubusercontent.com/assets/1103906/25607217/e8d55f26-2f58-11e7-86ce-9a3dcdf78fff.png)

This is really confusing - CS1998 fires stating that the method is missing an await, but the span of the error message for CS1998 knows to include the statements that have an await. ie Hovering over the statement that contains an `await`, tells me that the method is missing an `await`. Make up your mind, as part of the error reporting purposes these statements should either be included as part of the method or not.

**Comment by RikkiGibson** [comment]
I don't seem to be able to repro this. Has this possibly changed in the meantime?

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWACg9CiBWciy7AZkICZ8AhSgb0vwGFWxAGyEALPgCyACmy0APNhEA+fADMAdknwBLTTHwB7AA4xdRzVACU/QXwqCn+OwIC+lD4yrCOAYV5XIQlpGVtHeyCnTgA6WWwADnww/ABeFSjnAQB6bPwoXTATABs4TKzsAE5CERi/IyLS+BRlBiz3HQ50fDZrNsEvNyA

```cs
using System;
using System.Threading.Tasks;

public class B
{
    public static void M(Func<Task> fn, int options)
    {
        
    }
}

public class C
{
    public void M()
    {
        B.M(async () =>
            // simple
            await Task.CompletedTask;
        }, 2 + 2);
    }
}
```

Diagnostics:
```
CS7036	There is no argument given that corresponds to the required formal parameter 'options' of 'B.M(Func<Task>, int)' Line 16
CS1026	) expected Line 18
CS1519	Invalid token ',' in class, struct, or interface member declaration Line 19
CS1022	Type or namespace definition, or end-of-file expected Line 21
```

**Comment by RikkiGibson** [comment]
Please reopen if this is still an issue

**Comment by davkean** [comment]
Yeah agreed cannot repro.
