### ISSUE TITLE
Code Style: enforce named arguments for literals

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#19186]
Note: there is already a refactoring for adding named arguments.

**Comment by jcouv** [comment]
:memo: I expect we'll add support for [non-trailing named parameters](https://github.com/dotnet/csharplang/issues/570) in 15.6. Then enforcing that literals be named will make more sense (be less annoying).

**Comment by jcouv** [comment]
The non-trailing named arguments feature is merged to master, so this can go ahead.

**Comment by dpoeschl** [comment]
@jcouv What's the status of this one? I thought you had it almost working.

**Comment by jcouv** [comment]
One issue remains in the PR (how the new codefix interacts with the existing refactoring). I should be able to merge by next week (in time for 15.5 preview 2).

**Comment by jcouv** [comment]
Quick update: from discussions following the issue I mentioned above, that PR is snowballed. The existing refactoring would need to be removed and the code migrated into the new codefix.

**Comment by jcouv** [comment]
I've dropped my PR with some rationale. If anyone is interested, feel free to pick up this issue.

**Comment by alrz** [comment]
>running such a fixer on the Roslyn codebase was actually rather annoying (consider all the Assert methods, with literals for the expected values).

probably it's best to limit this to invocations with >2 arguments.

**Comment by CyrusNajmabadi** [comment]
Unlikely to do this given lack of feedback.
