### ISSUE TITLE
"Register designer attribute" plays badly with new "SDK" projects, leading to tons of UI hangs

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#19187]
The infrastructure we have for determining if a file is 'designable' ends up sending a firehose of notifications to the UI thread giving the state of *each* document (and whether it it designable or not).  It needs to do this so that it can also clear the designable state for a file as well as mark files as designable.

This is not only bad on its own (thousands of UI notifications), but it also plays *super* bad with the new projects we have in roslyn which are CPS based.  These projects then need to do all sorts of blocking/pumping waits to try to get the results, and the entire UI just becomes a mess around responsiveness:

Here's an example of the types of callstacks this is causing:

```
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.Threading.NoMessagePumpSyncContext.Wait(waitHandles, waitAll, millisecondsTimeout)	Unknown
 	System.Threading.SynchronizationContext.InvokeWaitMethodHelper(syncContext, waitHandles, waitAll, millisecondsTimeout)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.Threading.Monitor.Wait(obj, millisecondsTimeout, exitContext)	Unknown
 	System.Threading.Monitor.Wait(obj, millisecondsTimeout)	Unknown
 	System.Threading.ManualResetEventSlim.Wait(millisecondsTimeout, cancellationToken)	Unknown
 	System.Threading.Tasks.Task.SpinThenBlockingWait(millisecondsTimeout, cancellationToken)	Unknown
 	System.Threading.Tasks.Task.InternalWait(millisecondsTimeout, cancellationToken)	Unknown
 	System.Threading.Tasks.Task.Wait(millisecondsTimeout, cancellationToken)	Unknown
 	System.Threading.Tasks.Task.Wait(timeout)	Unknown
 	Microsoft.VisualStudio.Threading.JoinableTaskFactory.WaitSynchronouslyCore(task)	Unknown
 	Microsoft.VisualStudio.Threading.JoinableTaskFactory.WaitSynchronously(task)	Unknown
 	Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()	Unknown
 	Microsoft.VisualStudio.Threading.JoinableTask<Microsoft.VisualStudio.ProjectSystem.VS.HResult>.CompleteOnCurrentThread()	Unknown
 	Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<Microsoft.VisualStudio.ProjectSystem.VS.HResult>(asyncMethod, creationOptions)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously<Microsoft.VisualStudio.ProjectSystem.VS.HResult>(asyncAction)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrInvoke.AnonymousMethod__0()	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(action, vsShellServiceProvider, projectFaultHandlerService, project)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrInvoke(asyncAction, registerProjectFaultHandlerService)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.GetProperty(itemId, propId, propValParam)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNodeWrapper.GetProperty(itemid, propid, pvar)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.UnconfiguredProjectHostObject.GetProperty(itemid, propid, pvar)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.ConfiguredProjectHostObject.GetProperty(itemid, propid, pvar)	Unknown
>	Microsoft.VisualStudio.LanguageServices.Implementation.DesignerAttribute.DesignerAttributeIncrementalAnalyzer.RegisterDesignerAttribute.AnonymousMethod__0()	C#
```

We need to do something about this as just dogfooding is very painful.  Having this escape to customers would be very bad.

**Comment by CyrusNajmabadi** [comment]
Tagging @Pilchie @jasonmalinowski @davkean @heejaechang

**Comment by CyrusNajmabadi** [comment]
Note: this appears to be far worse after Jared's change.  Possibly because we have far more projects that use CPS now.

**Comment by CyrusNajmabadi** [comment]
Potential things we can do:

1. Provide an entirely BG thread mechanism for roslyn to notify the system about these files.  Do nothing on the UI thread.
2. Have the notification batch up.  With the hope that doing a bunch of stuff on the UI thread at once will be helpful.  Note: i don't know if this will actually help.  If each call into CPS ends up being bad, then this will still be a problem.  But at least we won't have 20k UI notiications, we'll only have a small handful.

**Comment by heejaechang** [comment]
can CPS provide an API one can call from background thread? @srivatsn @davkean

**Comment by srivatsn** [comment]
Yes we can definitely work on a bg API. This also causes more problems like this - https://github.com/dotnet/project-system/issues/2001 @tmeschter can you work with HeeJae on fixing this?

**Comment by Pilchie** [comment]
Note - would this also let us update a project a time?  The current impl of this also checks project file readonly state for every file, etc.

**Comment by CyrusNajmabadi** [comment]
That would be nice.  It would also be nice to move all the computation entirely OOP.  Right now it's very chatty oop.

**Comment by CyrusNajmabadi** [comment]
I'm going to look at two changes that can be made right now (since this perf issue is *really* impacting me badly).

1. Batching UI work so that we don't notify the UI thread once per document in your solution.
2. Avoiding the work entirely for CPS projects (since they don't support this capability anyways) (according to @Pilchie).  We already check "hierarchy.IsCapabilityMatch("CPS")" in some cases.  We'd just do no work for these projects in this case.

**Comment by davkean** [comment]
I think we need to design this a little before we do 2). It's not entirely clear to me what happens when we start bringing up WinForms, etc - https://github.com/dotnet/project-system/issues/2100

**Comment by davkean** [comment]
What I mean by that is I don't know all the usages of this metadata before I say "we don't need to mark these objects with it". It's going to be entirely based on compat.

**Comment by Pilchie** [comment]
Yep.  The thought with 2 is definitely around a short term thing to unblock things.

The other use case I know of is the webforms designer and third party "Component" designers.

**Comment by Pilchie** [comment]
You've already been looking at this.
