### ISSUE TITLE
Refactoring out an unnecessary cast

### ISSUE THREAD

**Issue by thorgeirk11** [dotnet/roslyn#1919]
There is a different result of running a code fix on a single line versus a whole document. Refactoring out an unnecessary cast for the following code:

```CSharp
float temp1 = (float)(1 / 2);
float temp2 = (float)(1 / 2);
float temp3 = (float)(1 / 2);
```
Refactoring one cast at a time results in the following code:
```CSharp
float temp1 = 1 / 2;
float temp2 = 1 / 2;
float temp3 = 1 / 2;
```
However when the same refactoring is run on the document, by clicking on "Fix all occurrences in: Document" inside the light bulb, the following happens:
```CSharp
float temp1 = (1 / 2);
float temp2 = (1 / 2);
float temp3 = (1 / 2);
```

Here is a screenshot of the issue.
![image](https://cloud.githubusercontent.com/assets/2693474/7092283/e6bf475c-df9f-11e4-85ad-c94d3f4e8d1d.png)

Is this expected behaviour ?

**Comment by srivatsn** [comment]
This was fixed by @mavasani some time ago. I just verified that this works fine now. The fix should show up in the next preview.
