### ISSUE TITLE
Want summary for the object in the tooltip when hover over its constructor call

### ISSUE THREAD

**Issue by pawchen** [dotnet/roslyn#19199]
Currently when you hover over the `Something` of `new Something()`, typically you get `Initialize a new instance of Something (with its parameter)`, which is not helpful because I knew it's a constructor call.

It would be great that the tooltip includes the summary of that `Something`. I mean the info from the summary tag below
```C#
/// <summary>This something can do blah, blah</summary>
class Something { ... }
```

**Comment by Pilchie** [comment]
In some places in the past, we've distinguished between the constructor and the type by offering constructor info on the `new` keyword, and type information on the type name.

Another approach would be to merge them.

**Comment by diryboy** [comment]
I would prefer the merging approach, having to hover over the `new` keyword to see the constructor info is kinda surprising.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack fo feedback on this.
