### ISSUE TITLE
Specifying the checksum when creating SourceText

### ISSUE THREAD

**Issue by pranavkm** [dotnet/roslyn#1920]
We use the Roslyn compiler to generate Razor views in Mvc. This involves converting the original cshtml file and transforming it into a string that represents the C# code to compile. This boils down to 

```C#
var sourceText = SourceText.From(generatedCSharpCode, Encoding.Utf8);
var syntaxTree = SyntaxTreeGenerator.Generate(sourceText, absolutePathToView);
```

Looking at the generated PDB (using PdbToXml, great tool!), it seems like

1. Roslyn calculates the SHA1 checksum using `generatedCSharpCode`
2. Sets the file path to `absolutePathToView`

The VS debugger uses the contents of the file at `abolutePathToView` to calculate the checksum and thinks it's a mismatch. Consequently unless we have “Allow Source Location to be different”, the breakpoint doesn’t hit. 

Is there another way to create the `SourceText` so we can have it use the checksum of the `absolutePathToView`?

**Comment by pharring** [comment]
I suppose we could add a public overload of SourceText.From that takes a checksum argument.

As a workaround for now, you'll have to write your SourceText implementation. You could clone [StringText](http://source.roslyn.io/#Microsoft.CodeAnalysis/Text/StringText.cs,79749899b53d5846) into your project, for example.

**Comment by tmat** [comment]
@mattwar

**Comment by tmat** [comment]
I'm not sure I understand the problem. The SyntaxTreeGenerator should return a syntax tree backed by source text with the corresponding checksum. Maybe it doesn't?

**Comment by tmat** [comment]
The value of ```absolutePathToView``` should be the path to the generated file. It should not be the cshtml file. Use #line to map to the cshtml file.

**Comment by mattwar** [comment]
What is SyntaxTreeGenerator?

**Comment by pranavkm** [comment]
@pharring - thanks. I'll look into that.

@tmat, `absolutePathToView` is the `'cshtml` file and we don't write the generated contents to disk. Specifying a random path gets the debugger to work - we do this today by specifying relative paths when generating line pragmas and absolute path when generating the pdb. However I just wasn't certain if that's what we should be doing.

@mattwar Oops - that's a two line utility code we use (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/Compilation/SyntaxTreeGenerator.cs#L19-L22)

**Comment by tmat** [comment]
@pranavkm Assuming that "random path" is the path to the generated file, then yes, that's what you should be doing.

**Comment by davkean** [comment]
@gafter You marked this as an infrastructure bug, but this looks like request for a compiler API. Marked it as such, feel free to move it I've marked it incorrectly.

**Comment by gafter** [comment]
I think the bug is in your code, here: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/Compilation/SyntaxTreeGenerator.cs#L36-L38

You are specifying a source path whose contents do not match the text given to the parser. The VS debugger finds the file at that path and rightfully complains that it isn't the right source.

**Comment by pranavkm** [comment]
@gafter what would be the right thing for us to in this case? Not specify the source path?

**Comment by gafter** [comment]
Give the name of a file that does not exist.
