### ISSUE TITLE
Naming suggestions have an empty useless tool tip

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19200]
![image](https://cloud.githubusercontent.com/assets/1103906/25648077/44e3b0e4-300b-11e7-9613-28a13b3ad48c.png)

**Comment by sharwell** [comment]
This should at least say that it's a suggested name, or something.

**Comment by rchande** [comment]
Confirmed with @dpoeschl that this bug does not affect the user-friendly tenet.

**Comment by davkean** [comment]
@sharwell Yeah agreed - TBH I had no idea what these names were when I first encountered them. Took me a few looks to understand what was going on.
