### ISSUE TITLE
Nothing happens when run Test.cmd

### ISSUE THREAD

**Issue by diryboy** [dotnet/roslyn#19210]
It appears that the `Test` target of BuildAndTest.proj has a `Condition="'$(TestDesktop)' == 'true' or '$(TestCoreClr)' == 'true' or '$(TestVsi)' == 'true'"`, but `Run-Test()` from build.ps1 only specify `/p:ManualTest=true`

**Comment by Pilchie** [comment]
@jaredpar I heard you were looking at this?

**Comment by jaredpar** [comment]
Yep.  https://github.com/dotnet/roslyn/pull/19206

**Comment by diryboy** [comment]
#19220 fixed this issue, closing.
