### ISSUE TITLE
Running compiler tests on latest desktop bits

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#19215]
This was suggested by @preetikr
I need to think more about this. On the surface, I'm not sure that the compiler tests will add much value, as they exercise fewer paths than the desktop unittests. 
Taking the example of ValueTuple, the compiler C# tuple unittests  will only exercise the constructors and the fields. They don't typically invoke the comparison or equality logic, which is most of the ValueTuple code.

**Comment by jaredpar** [comment]
Can you clarify this?  When speaking about running the compiler tests there are two axis to consider:

1. The runtime on which the xunit process executes
1. The runtime on which the result of CompileAndVerify execute

Wasn't sure which you meant by this issue.

Note: today these two are linked together so.  But hopefully in the future we can separate this out hence it may become a bit more interesting.

**Comment by jcouv** [comment]
@jaredpar The proposal was to either have the compiler team join the windows insiders program, or find a way to run our tests on windows insider bits (preview of the latest desktop framework).
From recent thread with you and MeiChin, I'm not convinced this is valuable (do we expect this to help catch relevant issues).
