### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspacesNetCore.ProjectReference [FAIL]

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#19223]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/3638/

Seems to be failing very consistently.

**Comment by dpoeschl** [comment]
@dotnet/roslyn-infrastructure

**Comment by Pilchie** [comment]
@srivatsn / @jmarolf want to move this to the project system repo?

**Comment by srivatsn** [comment]
This issue was moved to dotnet/project-system#2124
