### ISSUE TITLE
XML Cref IntelliSense has started showing private types from the framework

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19227]
I understand it is legal to point to a non-accessible type in cref, I do not, however, think that these should be shown in IntelliSense - I don't remember seeing this until I installed this build, so this feels like a regression:

![image](https://cloud.githubusercontent.com/assets/1103906/25684371/681033f0-30a4-11e7-8017-57cca8bec225.png)

**Comment by Pilchie** [comment]
Nothing has changed in this completion provider.  @jaredpar know of any changes to the compiler that could affect `LookupSymbols` results here?

**Comment by jaredpar** [comment]
No.  CC @AlekseyTs, @jcouv in case they are aware of anything here.

**Comment by rchande** [comment]
@jcouv I don't have a machine with 15.0 but I do see this on 15.1. There haven't been any IDE changes in this area. It's not happening in VB or in C# with other framework versions.,, so it doesn't seem like a BCL issue.
@jaredpar Can I move this to the compiler so you guys can take a look?

**Comment by jaredpar** [comment]
Moving back to compiler.  Warning: this is **very** low on the priority list ATM.

**Comment by davkean** [comment]
This has become really annoying, because internal types that are in the global scope are showing up always such as BidArgumentTypeAttribute from System.Data. I could have sworn this is a regression, anyone got an earlier build to check?

**Comment by jcouv** [comment]
Neal tried this on VS2015 update 3 and found the same behavior. His machine has .NET Framework 4.6.2 installed (but not 4.7).

Also, the code used to figure out which symbols should be returned from LookupSymbols in the context of a CREF is pretty explicit: all types that are in your assembly and all types that are not private.

```C#

        /// <summary>
        /// A symbol is accessible for referencing in a cref if it is in the same assembly as the reference
        /// or the symbols's effective visibility is not private.
        /// </summary>
        private bool IsCrefAccessible(Symbol symbol)
        {
            return !IsEffectivelyPrivate(symbol) || symbol.ContainingAssembly == this.Compilation.Assembly;
        }
```

For the record, here's a repro test case:
```C#
        [Fact]
        public void CrefLookup2()
        {
            var lib = @"internal class InternalDictionary { }";

            var source = @"
/// <summary>
/// See <see cref=""HERE""/>.
/// </summary>
class C
{

}
";
            var libComp = CreateCompilation(lib);

            var compilation = CreateCompilation(
                new[] { Parse(source, options: TestOptions.RegularWithDocumentationComments) },
                references: new[] { libComp.ToMetadataReference() },
                options: TestOptions.ReleaseDll.WithXmlReferenceResolver(XmlFileResolver.Default));

            var model = compilation.GetSemanticModel(compilation.SyntaxTrees.Single());
            int position = source.IndexOf("HERE", StringComparison.Ordinal);
            AssertEx.SetEqual(model.LookupSymbols(position).Select(SymbolUtilities.ToTestDisplayString),
                "InternalDictionary", "C");
        }
```

**Comment by CyrusNajmabadi** [comment]
I don't repro this now:

![image](https://user-images.githubusercontent.com/4564579/217344437-c496b41b-4b36-4c7d-a1ee-ed4b3268280b.png)
