### ISSUE TITLE
Attempting to display the light bulb immediately after applying a code fix, causes it be to be immediately dimissed 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19244]
I'm unsure if this because Roslyn is causing a focus change that's causing it be dismissed, but I can repro this pretty consistently, see attached video:

![lightbulbdimiss](https://cloud.githubusercontent.com/assets/1103906/25689443/6cc76afe-30cb-11e7-9f6b-4396974e93ea.gif)

Here I'm

1. CTRL+.
2. ENTER
3. CTRL+.

**Expected:** For the lightbulb to remain open
**Actual:** Lightbulb is dismissed

Will move the bug if you don't think this is Roslyn causing the focus change.

**Comment by davkean** [comment]
@CyrusNajmabadi @olegtk What are you thoughts on this? Roslyn or the editor?

**Comment by olegtk** [comment]
I think this is something that we already fixed for 15.3, currently the fix is only in lab/vsuvscore though. Send the bug to the editor, we will verify that.

**Comment by Pilchie** [comment]
@davkean can you file internally?

**Comment by davkean** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems?id=430197&fullScreen=false&_a=edit

**Comment by olegtk** [comment]
thanks! I can repro on Preview, but can't on vsuvscore so I think this is fixed, but we will verify it more thoroughly.
