### ISSUE TITLE
C# command line tests fail in development build

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#19245]
I get this failure

``` none
Test 'Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.CommandLineTests.ParsePlatform' failed: System.TypeInitializationException : The type initializer for 'Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.CommandLineTests' threw an exception.
---- System.NullReferenceException : Object reference not set to an instance of an object.
	at Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.CommandLineTests..ctor()
	----- Inner Stack Trace -----
	CommandLineTests.cs(42,0): at Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.CommandLineTests..cctor()
```

which appears to be due to this line

``` c#
        private static readonly string s_compilerShortCommitHash =
            CommonCompiler.ExtractShortCommitHash(typeof(CSharpCompiler).GetTypeInfo().Assembly.GetCustomAttribute<CommitHashAttribute>().Hash);
```

Not sure how this code is supposed to behave if the `CommitHashAttribute` is missing.

**Comment by jcouv** [comment]
I'll stop by tomorrow.
The project file for CodeAnalaysis.CSharp project, which has CSharpCompiler, does include the CommitHashAttribute. So I don't see how it could be missing.

https://github.com/dotnet/roslyn/blob/bab9408961d15d910c3ee48216a586cda58f8265/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj#L27

**Comment by jcouv** [comment]
I'm running into the problem occasionally as well.
Building from the command-line seems to do the right thing (include the CommitHash attribute) and fix the situation.
When this problem occurs, the CSharp and VB CodeAnalysis assemblies has other attributes I expect (like AssemblyFileVersion), but is missing the commit hash one.

**Comment by jcouv** [comment]
Ty suggested this may be related to building from detached HEAD branch. I'm not convinced, but I'll keep an eye out.

**Comment by jcouv** [comment]
I investigated this further and it does seem related to building a detached HEAD branch.

**Comment by AdamSpeight2008** [comment]
See #19556 also

**Comment by jaredpar** [comment]
Sholud be fixed by this PR

https://github.com/dotnet/roslyn/pull/19593
