### ISSUE TITLE
InlineTemporary into a invocation of local function produces bad code

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#19247]
In the example below, inlining `V` leads to bad code

![image](https://cloud.githubusercontent.com/assets/12466233/25690382/93a8a66e-3045-11e7-858d-df01eb0ceed7.png)

![image](https://cloud.githubusercontent.com/assets/12466233/25690387/a55013de-3045-11e7-8ace-2e4bd7f39f53.png)

FYI @agocke

**Comment by Pilchie** [comment]
Presumably, we should just not be expanding the name of the local function.
