### ISSUE TITLE
Proposal: Make 'YouCannotRenameThisElement' also display where/why it failed.

### ISSUE THREAD

**Issue by tamlin-mike** [dotnet/roslyn#19252]
**Version Used**: VS 15.1 (26403.7)

**Steps to Reproduce**:

1. Rename a lot of symbols using Inline renaming.

**Expected Behavior**:
It should always work to rename a valid identifier.

**Actual Behavior**:
Sometimes, seemingly stochastic, the rename fails somewhere within `Microsoft.CodeAnalysis.Editor.Implementation.InlineRename`, displaying the `EditorFeaturesResources.YouCannotRenameThisElement` string in a dialog.

The problem is, this error string is returned from nine different places in that class, making it practically impossible to know where and more importantly _why_ it failed (short of creating a debug build yourself and so on).

While I'd personally prefer a more descriptive error message added, even if English-only, a far from optimal but easier to implement solution would be to append an LF and the line number it failed on, since it would require no l10n.

I know Microsoft hates giving its customers information - especially when it comes to telling them what has failed as that would give them the ability to actually research the actual problem, but with Roslyn being open source, I have hopes this deeply rooted customer disdain might not apply in this case.

**Comment by 0xd4d** [comment]
> While I'd personally prefer a more descriptive error message added, even if English-only, a far from optimal but easier to implement solution would be to append an LF and the line number it failed on, since it would require no l10n.

MS already uses a special number when something goes wrong, it's -2146232797 [1], aka the "Stack Trace Hidden" error. I think it can also be used when a rename fails.

[1] https://github.com/dotnet/roslyn/issues?utf8=%E2%9C%93&q=is%3Aissue%20-2146232797

**Comment by tamlin-mike** [comment]
@0xd4d ROFL!

**Comment by Pilchie** [comment]
I think this a great idea, and I would love to see detailed reasons in the dialog.  Unfortunately, we're not likely to have time to address it any time soon, but we'd happily welcome a PR.

**Comment by tamlin-mike** [comment]
Having given this some more thought now, an idea popped up that could both sidestep the "l10n required" while providing the extra info many would like. It would apply to a great number of scenarios, not only this, so I wanted to bounce this and perhaps let the concerned parties chime in.

What if instead of a single string and only a simple dialog box (as it is today), extra info could be provided that would display an "Advanced info" (or whatever) button that would reveal that extra info?

That extra info would be non-localized, and display something more akin to developer-to-developer communication. In its simplest form, think of it as an assert error message.

The idea is that if something doesn't provide extra info, everything both looks and behaves like it does today. It would not affect existing source code one bit, while allowing this extra detail info to be added when and where it feels prudent to do so.
If an error _source_ do implement this extra info interface (let's preliminary call it ITechnicalDetailsErrorInfo, an abstract base class having a single method returning a string, and the base class default impl. returns null), the code displaying the dialog could then - provided the extra info contains something - switch to use the "enhanced" dialog, allowing the user to look at the inherently technical and not localized information.

@Pilchie Feel free to bounce this to other team members to let them get a feel for the idea.

Comments?

**Comment by CyrusNajmabadi** [comment]
We did add a lot more descriptions to the cases where we can't rename.  if you're still seeing a case, let us know :)
