### ISSUE TITLE
Smart variable naming should escape keywords

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#19260]
**Version Used**: 2.3.0.61627

**Steps to Reproduce**:
```c#
class For
{
    For |
}
```
Commit `for`.

**Expected Behavior**: `@for` inserted;

**Actual Behavior**: `for` inserted and CS1519.

**Comment by kuhlenh** [comment]
Ran into this same problem with ```StringBuilder```:

![image](https://user-images.githubusercontent.com/1402694/26851928-529dea8a-4ac1-11e7-9cc9-7120c8d903b8.png)

**Comment by Pilchie** [comment]
Yeah, I didn't consider keywords that were parts of other type names I guess.  Let's pull this back into 15.6
