### ISSUE TITLE
Smart variable naming creating conflicts

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#19261]
**Version Used**: 2.3.0.61627

**Steps to Reproduce**:
```C#
class Program
{
    Program |
    Program GetProgram;
}
```

**Actual Behavior**: 
Committing `Program` results in in CS0542 (same name as enclosing type). 
Committing `GetProgram` results in CS0101 (conflicting name).

**Expected Behavior**:
Either conflicting names should not be offered, or they should use the same red cross icon like conflicting types do.

**Comment by CyrusNajmabadi** [comment]
closing out for lack of feedback.
