### ISSUE TITLE
LightBulb dropdown attached to bottom of info pane 

### ISSUE THREAD

**Issue by vsccarl** [dotnet/roslyn#19265]
**Version Used**: 
d15rel\26503.01

**Steps to Reproduce**:

1. Code in an error. (adding an extra return statement to a method works)
2. Click on the code with the error.
3. Hover over with the pointer to bring up the error/warning popup and lightbulb dropdown

**Expected Behavior**:
LightBulb dropdown attached to the top of the error/warning info popup

**Actual Behavior**:
![image](https://cloud.githubusercontent.com/assets/12900364/25721638/06fb8246-30c6-11e7-9da6-01e1f1c78e6a.png)

**Comment by Pilchie** [comment]
@olegtk FYI

@vsccarl is this behavior different?  I thought the lightbulb was always aligned with the blue `Show potential fixes` link.

**Comment by olegtk** [comment]
it's actually bug #361918, the LightBulb is supposed to be on the upper side indeed, close to the mouse cursor.

**Comment by Pilchie** [comment]
Huh.  Shows what I know, but then again I'm not much of a mouse user.

**Comment by vsccarl** [comment]
@Pilchie I always remember it being attached to the top as shown [here](https://msdn.microsoft.com/en-us/library/dn872466.aspx).

vsuml looks like this:
![image](https://cloud.githubusercontent.com/assets/12900364/25723602/8ad8d5da-30cd-11e7-9fc1-471da6028880.png)
