### ISSUE TITLE
FullyQualifiedName issue with CodeLens

### ISSUE THREAD

**Issue by singhsarab** [dotnet/roslyn#19263]
**Steps to Reproduce**:

1. Create a class library project and write a method inside a nested class, for example:

```
namespace FooBarNamespace
{
    public class OuterClass
    {
        public class NestedClass
        {
            public void Method1()
            {
            }
        }
    }
}
```
2. Use CodeLensReferencesService.GetFullyQualifiedName to get the FQN for the method.

**Expected Behavior**:
FooBarNamespace.OuterClass+NestedClass.Method1

**Actual Behavior**:
FooBarNamespace.OuterClass.NestedClass.Method1

**Comment by Pilchie** [comment]
@panopticoncentral any thoughts here?

**Comment by panopticoncentral** [comment]
@Pilchie It doesn't look like there's a SymbolDisplay option to get plus between nested types, am I reading the code correctly?

**Comment by Pilchie** [comment]
I'm not aware of a way - Roslyn normally models the source concept of symbols, not how they happen to be encoded in metadata.

**Comment by Pilchie** [comment]
@singhsarab Can you elaborate on what the customer impact of this issue is?  Doe it mean that CodeLens doesn't work for nested types?  All indicators, or just some?

**Comment by singhsarab** [comment]
@Pilchie Indicators won't work for types whose FQN does not match.
For simple types, since the FQN matches, it works fine.
For nested types, FQN does not match, hence it does not work.

**Comment by Pilchie** [comment]
What indicators?  All of them?

**Comment by singhsarab** [comment]
TestIndicators.

**Comment by panopticoncentral** [comment]
Is it possible for the test indicator code to construct its internal FQN with "." instead of "+" to match what's coming back from Roslyn? I'm on a slow connection at the moment, so I can't check it myself, I can also look when I get into the office in about 1.5 hours.

**Comment by singhsarab** [comment]
@panopticoncentral 
Yes, mapping “+” to “.” in the test indicator code would work, but I am not sure if that is the right thing to do.

String values for C# fully qualified names use “+” between classes. Even while getting the type by string, we need to pass the name appropriately Type.GetType("Namespace.OuterClass+NestedClass").
[MSDN Reference](https://msdn.microsoft.com/en-us/library/yfsftwz6(v=vs.110).aspx)
