### ISSUE TITLE
CastExpression should add parenthesis around expression when necessary

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn#19262]
**Version Used**: 
2.1.0

**Steps to Reproduce**:

```csharp
var binaryExpression = BinaryExpression(SyntaxKind.AddExpression,
    IdentifierName("x"),
    IdentifierName("y"));
var castExpression = CastExpression(PredefinedType(Token(SyntaxKind.IntKeyword)), binaryExpression);
Console.WriteLine(castExpression.ToFullString());
```

**Expected Behavior**:

(int)(x+y)

**Actual Behavior**:

(int)x+y

**Comment by Pilchie** [comment]
That is not the purpose of the `SyntaxFactory`.  It is there to construct *exactly* the syntax you ask it to.

**Comment by jeremymeng** [comment]
ah that's right.

**Comment by CyrusNajmabadi** [comment]
You can use SyntaxGenerator.  Which will attempt these sort of niceties. :)

**Comment by jeremymeng** [comment]
Thanks for the tip @CyrusNajmabadi! Yes we use SyntaxGenerator too. In this case I don't have a document/project but should be able to get it easily.
