### ISSUE TITLE
Calling TryGoToDefinition from a callout causes VS to become a top most window

### ISSUE THREAD

**Issue by drognanar** [dotnet/roslyn#19271]
**Version Used**: 
d15prerel-26423.1 + Roslyn ddef785
also repros in latest vsuml, d15rel, d15prerel

The issue repros after the following change has been merged:
https://github.com/dotnet/roslyn/commit/2f11213119804e665f7e876fa3e372639be4604a#diff-e6e9ed18929cbe35dcd0c4131ab4d6f6R281

**Steps to Reproduce**:

1. Create a callout menu that calls `TryGoToDefinition`.
2. If the callout is focused as the method is executing VS remains the topmost window until restarted.

**Expected Behavior**:

VS should not become the topmost window.

**Comment by Pilchie** [comment]
Per off-line conversation we determined that this was related to calling the API while a WPF popup was active.  Not sure if there is anything we can do different, but conversations are ongoing.

**Comment by Pilchie** [comment]
Giving to @CyrusNajmabadi to track the possible need to change our use of VS Platform APIs here, or close if no action is necessary.

**Comment by CyrusNajmabadi** [comment]
Our usage is correct AFAICT.  We are calling the platform API exactly as it is documented.  We have no knowledge if we're being called from within a 'on top' flyout.  If VS/WPF have this issue, then it seems like something for the platform to 'fix'.  If it can't be fixed, then it seems like it will simply have to be the case that flyouts do not call this API without dismissing themselves first.

Or, in other words, this problem exists entirely in the absense of Roslyn.  If this flyout called into the platform directly, they'd have the same issue.  So, to me, it's up to those parties to work out what the appropriate resolution is here.
