### ISSUE TITLE
MSBuildWorkspace Projects Sometimes Falsely Reports "HasDocuments"

### ISSUE THREAD

**Issue by scottlurowist** [dotnet/roslyn#19288]
**Version Used**: 2.1.0

**Steps to Reproduce**:

1. Use MSBuildWorkspace to load a solution in a Roslyn command-line app generated by a Roslyn template.
2. Load the solution asynchrously.
3. Load projects that have C# documents.
4. Run the program on Windows Server 2012 R2.

**Expected Behavior**:
 I expect that each project with documents reports that"HasDocuments" is true. The project will also have a collection of documents.

**Actual Behavior**:
When I run on Windows 10, I never see this issue. I see this issue on Windows Server 2012 R2. I run Windows Server 2012 R2 in an Oracle VirtualBox VM. This also occurs on Hyper-V VMs.

The problem occurs regardless of whether I compile with Visual Studio 2015 or Visual Studio 2017.

I have some solutions where I work where there is no problem. Yet, one solution falsely reports HasDocuments as false, and the collection of documents is empty. Yet, there are probably more than 100 C# files!

I cannot post any of the solutions, for obvious reasons. 

I am at a loss as to what is happening.

Scott Lurowist

**Comment by Pilchie** [comment]
Can you try installing the 2.3 packages from our (MyGet Feed)[], and hook something up to the `WorkspaceFailed` event.

I suspect that the proble here is either:

1. The Windows Server machine doesn't have the required targeting packs installed, so the design time build fails to create the command line arguments.
2. Binding redirects for the MSBuild assemblies.

**Comment by scottlurowist** [comment]
I do not have access to our build server where this needs to work, but I can test this in a 2012 VM.

Thanks,
Scott

**Comment by scottlurowist** [comment]
I am sorry, but I don't know what (MyGet Feed)[] is. I'll be happy to do this.

I do have an update.

On my work laptop's Windows Server 2012 R2 VirtualBox image, my tool works with one of our products, but not another product.

I installed Visual Studio 2017 on this same VirtualBox image. I compiled my tool, and now the tool works with the BOTH PRUDUCTS. This is good.

My tool is a command line tool. It is a command line tool so that it can run as a Team City build step. I copied the Visual Studio 2017 compiled code to the build agent that our build guy is allowing me to use.  It is a single build agent, but the original problem persists on the build agent. 

Here is some more information.

The build agent is running the 4.6 runtime of .NET. The source code for both products is pulled to the same build agent.

I checked the solution files. Both products have the same version of the solution file:
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 14
VisualStudioVersion = 14.0.25123.0
MinimumVisualStudioVersion = 10.0.40219.1

Here is the first few lines of the project file in question that works with my tool:
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />

Here is the first few lines of the project file in question for the product that does not work with my tool:
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />

Does the "ToolsVersion" make a difference?

**Comment by Pilchie** [comment]
Sorry - MyGet feed was intended to be a link, I've edited it inline.  You need to add a NuGet.config file that adds the (feed url)[https://dotnet.myget.org/F/roslyn/api/v3/index.json], similar to the one in Roslyn's repo [here](https://github.com/dotnet/roslyn/blob/master/NuGet.Config).

I expect that the problem is that your server doesn't have the SDK's your project depends on installed (Visual Studio installs them as prerequisites).

**Comment by scottlurowist** [comment]
_I expect that the problem is that your server doesn't have the SDK's your project depends on installed (Visual Studio installs them as prerequisites)._

This does not explain why the tool runs successfully on the same build agent for one solution, but not another. It seems to me that BOTH solutions for different products would not work.

I can't look at this until the weekend. I have deadlines at my job. I do thank you for looking into this.

Scott

**Comment by Pilchie** [comment]
Do the two solutions have different dependencies?

**Comment by scottlurowist** [comment]
I don't know to which dependencies you refer.

All I know is that the EXACT SAME MSBuildWorkspace code works reliably with one product / solution, and another product / solution does not work reliably. MSBuildWorkspace does not reliably  find the  documents / files for projects that are part of the solution that does not work.

Since I am trying to analyze code for a product at my job, I cannot post that code here. 

Is there a dependency on the project file versions for MSBuildWorkspace? I have seen no mention of such a depdendency.

**Comment by Pilchie** [comment]
The issue is the project type (WPF, PCL, WEB, etc), plus exactly what version of the .net framework things target.  MSBuild needs to import specific target files for specific project types/sdks.  Some of those are installed by Visual Studio, and my guess is that your VM and build server are missing the ones you need.

**Comment by scottlurowist** [comment]
I am writing an analyzer for unit tests. These are simple DLL project types. 

I shall investigate the project files for the unit test project that fails. I do know it was not created with VS 2015. It may have been created with VS 2012. But, I do not work on that product.

Thanks!
Scott

**Comment by Pilchie** [comment]
@scottlurowist it might have to do with what the Target Framework version is on the tests.  You might have targeting packs for some version installed, but not others.

**Comment by scottlurowist** [comment]
I have been on vacation. I'll look at this.
