### ISSUE TITLE
Suggestion: "Build and Run" options should expose MSBuild binary logging

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#19287]
The new [MSBuild binary log](https://github.com/Microsoft/msbuild/wiki/Binary-Log) option (introduced in MSBuild 15.3) is really handy. It is streamlining the usage of Kirill's structured file logger.
From the command-line, you'd pass `/bl` to `msbuild`.
When using this option, logging to a text file is redundant, since the binary log has more information. So maybe this could be exposed as a new entry in the "MSBuild project build log file verbosity" drop-down.

@Pilchie I'm not sure if this is managed by the Roslyn IDE layer or VS. Can you help route?

![image](https://cloud.githubusercontent.com/assets/12466233/25732439/69a088e0-3104-11e7-9d42-9bc87e163ff4.png)

**Comment by Pilchie** [comment]
It's *certainly* not IDE :)

It's either Project System (tagging @srivatsn), or the core Solution build team in VS Platform...

**Comment by jcouv** [comment]
Created a VSO issue for this (430822). Closing on github.
