### ISSUE TITLE
Diagnostics should be able to pass info to code fix providers.

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#1929]
ATM it's not possible to pass Information from diagnostics to code fix providers.
There is no real reason the code fix providers need to run a second diagnostic.

**Comment by mavasani** [comment]
You can pass custom information through the "properties" bag parameter taken by Diagnostic.Create method. Its a string -> string map.

**Comment by mkrueger** [comment]
Seems to be my roslyn is too old - I don't have that overload. But if it exists it would be helpful.

I was just translating NRefactory5 diagnostics and was missing that ability.
