### ISSUE TITLE
Why are there two solutions checked in? 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#193]
Several customers have noticed there are two solutions checked into the repo and wonder which one they should be using: Roslyn.sln or Roslyn2013.sln?

### Short answer

At the moment customers should be focusing on Roslyn2013.sln.  This solution is guaranteed to build on a machine with only VS 2013 installed.  Our Jenkins system is setup to ensure we don't silently break that guarantee.  

Of course that solution won't be editable in VS 2013 due to our consumption of new language features.  I would expect that it is editable in VS 2015 CTP5 but nothing is setup to verify this works at the moment.  

### Longer answer

The code available on GitHub now includes our Visual Studio components.  These components necessarily depend on the VS SDK and building the code requires having a compatible version installed on the build machine.  

The VS SDK though is tied to a particular version of VS and cannot be installed without it.  The VS SDK and our dependency on it evolves at a fairly pace.  Fast enough that it quickly includes components not available in even the latest CTP and instead requires a build which is only available internally. 

In the past this hasn't been a problem because both the code and builds were internal.   Now though our code is open to the world and we need a solution which doesn't depend on internal builds to succeed.  

Once we complete the move to GitHub, I will quickly make getting Roslyn.sln into a externally consumable state a priority.  That will include some manner of verification to ensure we don't break it as we evolve our code.  At the moment though I'm still focussed on that critical first step: completing the move to GitHub.  Hopefully that will be wrapping up in the next week or so.  

How we keep it buildable is an item that is still being discussed.  Our *very rough* thoughts are to: 

- Keep master buildable on a released version of Visual Studio.  Preferably an RTM build but will likely start off with CTPs given our current state.  
- Create a branch where we can move forward with dependencies on internal build features. 

This is a new world for us and we're still working to find the right processes.  :smile:

**Comment by giggio** [comment]
@jaredpar Ok, I want to pick up something from the `Up for grabs` list, and I don't work at Microsoft. Does this mean I will be able to use `Roslyn2013.sln` to work? I have been doing my work lately on VS 2015 CTP 5. Should I use `Roslyn2013.sln` or `Roslyn.sln`?
Regarding components not available on the latest CTP, can you work around somehow on the future, maybe deploy temporary versions on Nuget/Myget, maybe mock dependencies, etc?

**Comment by jaredpar** [comment]
@giggio I would stick with Roslyn2013.sln for the moment.  

We're working with the VS SDK owners to figure out the future solutions.  NuGet is definitely an item that is being discussed.  It would certainly solve the "how to build" part of the equation.  

That is only part of the problem though.  There are other issues with our dogfood story which are significantly harder to solve because it ends up requiring changes to Visual Studio.  It's all being discussed and considered but just one of those items that will take time to happen.  

One step at a time ...

**Comment by giggio** [comment]
@jaredpar Ok, I just tried building the HEAD of Roslyn, and Roslyn.sln does not build on VS 2015 CTP 5, but Roslyn.2013.sln does build.
I also noticed you are using xUnit 1, and not using [Xunit.Runner.VisualStudio](https://www.nuget.org/packages/xunit.runner.visualstudio) so I will need to reinstall the Runner Addin into VS.

**Comment by jwooley** [comment]
I'm wondering what the reasoning was to use xunit instead of mstest where the packaged project templates continue to use mstest.

**Comment by giggio** [comment]
My understanding: Xunit is open source, part of .NET Foundation, just like Roslyn. MSTest is not.
