### ISSUE TITLE
Update use of HashAlgorithm to reduce allocations

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#19309]
**Version Used**: 15.1

PerfView is showing substantial overhead for the creation of a temporary array in `HashAlgorithm.ComputeHash(Stream)`, originating from Microsoft.CodeAnalysis and Microsoft.CodeAnalysis.Workspaces. On my machine, this accounted for more than 3 seconds of time while Roslyn.sln was opening. Code using this method should be updated to use an alternative that allows the use of a caller-specified buffer from a pool.

**Comment by CyrusNajmabadi** [comment]
tagging @heejaechang 

From talking to heejae earlier, we're nto certain if anything can be helped here.  The issue is that we're not computing the hash and throwing away the value.  We hold onto the value.  So pooling isn't helpful.

**Comment by sharwell** [comment]
@CyrusNajmabadi The time spent is in ` clr!JIT_NewArr1`. It's literally the buffer allocation using for reading from the stream that's taking time.

**Comment by CyrusNajmabadi** [comment]
Related: https://github.com/dotnet/corefx/issues/16622

**Comment by CyrusNajmabadi** [comment]
Can you be more specific sam?  I can imagine a lot of different buffers at play here.
