### ISSUE TITLE
C# IntelliSense is confused for await in non-async methods

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1931]
In a non-async method, the `await` keyword is offered as a keyword completion.
However, once entering it, it's treated as a (non-existent) type, and there is no IntelliSense whatsoever after the space (because it thinks you're declaring a variable).

Entering an almost-complete `await` expression (eg, `await Task.Yield()`) doesn't change anything (offering a quick fix to generate an `await` class, even though that isn't a valid declaration); it's only parsed as an `await` expression after adding a semicolon or wrapping in parentheses (which then offers an add await quick fix).

See also #1884

**Comment by Pilchie** [comment]
I don't think there is actually anything unique from #1884 here - fixing the fault tolerance there should make things just work here.

**Comment by SLaks** [comment]
The appearance of `await` in IntelliSense, and how `await` is classified, is a bit different from what is mentioned there.

**Comment by gafter** [comment]
@Pilchie The symptoms in both bugs talk about intellisense, not compiler behavior. If there is an underlying compiler issue can you please write it up?

**Comment by gafter** [comment]
Closing as a dup of #1884.

**Comment by Pilchie** [comment]
What is unique here is the context.  In a statement context like this, the parser doesn't fall into the `AwaitExpressionSyntax` that it does in #1884 until you add the semi-colon.  Before that it parses as a `LocalDeclarationStatement`, and then as two expression statements.

Perhaps the parser could fall into this case as soon as the `.` is entered instead?

**Comment by jaredpar** [comment]
Going to let #1884 track this bug.
