### ISSUE TITLE
None of these syntax factory types or extension methods seem to line up for adding a base interface

### ISSUE THREAD

**Issue by StingyJack** [dotnet/roslyn#19316]
All versions. 

Just trying to take an existing interface, create a new one from it with slightly altered methods (rename, change return type) and then base the new interface on the old one `INewInterface : IOldInterface` has been a 3 hour exercise in flailing. Its still not compiling (or it does, and breaks at runtime), and I'm about to go back to string parsing.

Can these Add and With methods (they mean the same thing in idiomatic english) just take what the SyntaxFactory offers, instead of requiring enormous chains of eventually unmaintainable functions?

Is there a "Plain" API available for this? Something non-fluent? (I dont mind fluent, but its not "fluent" when a statement is 40 lines long - that's just textual diarrhea). And something that works with intellisense, because I roslyn is useful to me but only if I dont have to scale an enormous rock wall of overly specific notation with types that do not seem to jive.

```
var oldInterfaceDecl = (InterfaceDeclarationSyntax)interfaceDeclaration;
var newInterfaceDecl = SyntaxFactory.InterfaceDecl($"{oldInterfaceDecl.Identifier.Text}Part2");

// or should that be 

var newInterfaceDecl = SyntaxFactory.InterfaceDecl($"{oldInterfaceDecl.Identifier.Text}Part2");
   .WithBaseList(SyntaxFactory.BaseList(SyntaxFactory.Token(SyntaxKind.ColonToken),   SyntaxFactory.SeparatedList<????>(????How far does this have to go???)))

// it probably has to go this far, not that I can tell what it even means. I just want to add ": OldInterfaceName" to an interface declaration.

var newInterfaceDecl = SyntaxFactory.InterfaceDecl($"{oldInterfaceDecl.Identifier.Text}Part2");
.WithBaseList(SyntaxFactory.BaseList(SyntaxFactory.Token(SyntaxKind.ColonToken), new SeparatedSyntaxList<BaseTypeSyntax>().Add(SyntaxFactory.SimpleBaseType(SyntaxFactory.TypeSyntax("NOPE")))));
```

VS wants to help, but it offers things that just dont work, or that compile and fail at runtime.

**Comment by CyrusNajmabadi** [comment]
@StingyJack You can just call:

```c#
var newDecl = oldDecl.AddBaseListTypes(SyntaxFactory.SimpleBaseType(YourType));
```

**Comment by StingyJack** [comment]
Thanks but I ended up with the bits at the bottom. I know its more wordy and fragile, but 
![image](https://cloud.githubusercontent.com/assets/15381181/25776398/1a7ce1fe-328b-11e7-965b-df4be0d5e84e.png)

^ `TypeSyntax` just does not click. I know what _types_ are, but these Roslyn extension methods burn me all the time by allowing something in the code and compiling only to fail with messages like this at runtime....
 
![image](https://cloud.githubusercontent.com/assets/15381181/25776435/128568f8-328c-11e7-83d9-637c8f316fe1.png)

... Yep... that is just "ArgumentException" "keyword". It wouldn't kill the developers who wrote this stuff to at least emit a message more descriptive than "keyword". nameof(thing) is not a suitable replacement.

code that works.
```
    var oldInterfaceDecl = (InterfaceDeclarationSyntax) interfaceDeclaration;
                        var newInterfaceIdentifier = SyntaxFactory.Identifier(idef.ServiceContractAsyncName).WithoutTrivia();
                        var newInterfaceDecl = oldInterfaceDecl.WithIdentifier(newInterfaceIdentifier)
                            .WithoutTrivia()
                            .WithMembers(new SyntaxList<MemberDeclarationSyntax>())
                            .WithBaseList(SyntaxFactory.BaseList(SyntaxFactory.Token(SyntaxKind.ColonToken),
                                    SyntaxFactory.SeparatedList<BaseTypeSyntax>()
                                        .Add(SyntaxFactory.SimpleBaseType(SyntaxFactory.ParseTypeName(oldInterfaceName)))))
                            .WithOpenBraceToken(SyntaxFactory.Token(SyntaxKind.OpenBraceToken))
                            .WithCloseBraceToken(SyntaxFactory.Token(SyntaxKind.CloseBraceToken));

                        result.Debug.Add($"new interface: {newInterfaceDecl.GetText()}");

```

**Comment by CyrusNajmabadi** [comment]
> TypeSyntax just does not click

I don't know how to help with that.  :)  

> Yep... that is just "ArgumentException" "keyword". It wouldn't kill the developers who wrote this stuff

All our syntax factories are autogenerated (so that they're 100% consistent).

Feel free to submit a PR to make the error message better.  I'd have no problem with such a change going through. :)

Note: you could make your code simpler by doing the following:

```c#
var newInterfaceIdentifier = SyntaxFactory.Identifier(idef.ServiceContractAsyncName).WithoutTrivia();
                        var newInterfaceDecl = oldInterfaceDecl.WithIdentifier(newInterfaceIdentifier)
                            .WithoutTrivia()
                            .WithMembers(new SyntaxList<MemberDeclarationSyntax>())
                            .WithBaseList(SyntaxFactory.SeparatedList<BaseTypeSyntax>(SyntaxFactory.SimpleBaseType(SyntaxFactory.ParseTypeName(oldInterfaceName)));
```

Note: i'm not sure why you were created new open/close curlies.  I can't tell if you want to make your new interface hte same as your old interface (except with the addition of a base list), or if you want to make a fresh interface decl that shares nothing in common.

If you want to make it the same as the old decl, then start with oldInterfaceDecl and only replace what you want (you'll inherit all the stuff you didn't replace).  If you want a fresh decl (i.e. with all new pieces), then just do SyntaxFactory.InterfaceDecl(...) and pass in anything you don't want the default value for.

**Comment by CyrusNajmabadi** [comment]
Closing as there's no actual bug here.  

@StingyJack Feel free to submit PRs that address any issues you have with this API (i.e. with error messages) if you'd like!

**Comment by CyrusNajmabadi** [comment]
> Is there a "Plain" API available for this? Something non-fluent?

You don't need to use anything 'fluent' at all.  The fluent API is to take an existing immutable object and produce new ones from it.  You can always just call all the direct factory methods on SyntaxFactory to do whatever you want.  For example, you can directly call SyntaxFactory.InterfaceDeclaration(...) and provide everything in a non-fluent fashion.

**Comment by CyrusNajmabadi** [comment]
> but these Roslyn extension methods burn me all the time by allowing something in the code and compiling only to fail with messages like this at runtime....

First, these aren't extension methods :)

Second, what would be your approach to avoid the runtime checks?  A core part of the roslyn syntax API is performance.  That means having a struct for a token so that each token doesn't incur an allocation cost.  That means that from a type system perspective, we can't have a distinct type here.  Which means we need a runtime check ot make sure the 'kind' you're passing in is valid.  

This is an understood, but necessary tradeoff so that we can scale roslyn to massive projects and massive trees.

**Comment by StingyJack** [comment]
No problem with closing this. It was ranty anyway.

I have several years worth of Wcf service contracts that are used by ChannelFactory, and I want to add Task or Begin/End Async but have no interest in regenerating everything with svcutil. 

I tried for a few hours to build new items from scratch instead of copying the existing trees, and just could not get the program to run. After trying to do an identifier replacement on the old items, it was dragging some things along (or not) and I was ending up with stuff like this (#endregion was attached as leading trivia to the closing brace)...
```
    [ServiceContract]
    public interface IWcfServiceAsync
    {
#endregion
    }
``` 

or sometimes this where the endregion would be omitted, and a partial `Task<,` kind of interjected.
````
[ServiceContract]
    public interface IWcfServiceAsync
    {
#region "gets"
      Task<SomeResult> GetMethod1Async(SomeType param, SomeOtherType otherParam)
      Task<SomeResult> GetMethod2Async(SomeType param, SomeOtherType otherParam)
      Task<
#endregion //#region "gets"
#region "saves"
      Task<SomeResult> SaveMethod1Async(SomeType param, SomeOtherType otherParam)
      Task<SomeResult> SaveMethod2Async(SomeType param, SomeOtherType otherParam)
    }

````
At that point I went back to hand constructing them.  And then back. And then took a break and went to go find my brain and started replacing one piece at a time of the old item and found it was the closing curly.

I don't want to disable the runtime checks, but there is a notable gap where intellisense would normally be. "`TypeSyntax` does not click"  is just one of the examples of this. _Something_ needs to be passed as a parameter, but the API is intentionally/unintentionally vague as to _what_.  The IDE says "TypeSyntax", but SyntaxFactory doesnt make those. There is a TypeDeclaration, but that cant be correct. The method is called BaseList*() but wants something that's _not_ (or maybe it is).  =/

**Comment by CyrusNajmabadi** [comment]
> but there is a notable gap where intellisense would normally be. "TypeSyntax does not click" is just one of the examples of this. Something needs to be passed as a parameter, but the API is intentionally/unintentionally vague as to what. The IDE says "TypeSyntax", but SyntaxFactory doesnt make those.

TypeSyntax is an abstract type.  It's the root of all potential Type-Syntaxes.  For example, there are types that are:

1. types that are just keywords.  i.e. "int".
2. types that are just an identifier.  i.e. "String"
3. Dotted names: "System.String"
4. Array Types: int[]
5. Pointer types: int*
6. Generic types: ```List<int>```
7. Tuple types: (int, string)
8. Aliased names: X::System.String

And so on and so forth.  

You have to decide what you want to make in a given context.  

> The method is called BaseList*() but wants something that's not (or maybe it is).

Roslyn has a concrete syntax tree.  That means it represents everything down to the single character level.  in the case of Interface/Class/StructDeclarations you can provide a "BaseListSyntax" which represents the *colon* and the following list of types that follows.  i.e. ```: System.IDisposable```.

However, the API recognizes that often it's pretty onerous to have people have to supply tokens in so many places when it can be inferred from the grammar.  i.e. a "BaseList" will always need a colon, so we make it optional to provide one.  We also know that lots of times a node will have  subnode with a list of nodes in it.  i.e. "BaseListSyntax" itself has a "List of TypeSyntaxes".  So we provide convenience 'Add' methods that 'drill through' that parent/child relationship for you.  i.e., on the InterfaceDeclaration you can just say "AddBaseListTypes".  This is saying "Add the following *Types* to the list-of-Types in my 'BaseList', and make the BaseList if i don't already have one".

The intent is to actually get you to write a lot less, by allowing you to eschew tokens and to talk to child nodes without having to go explicitly make them.

**Comment by CyrusNajmabadi** [comment]
>and I was ending up with stuff like this (#endregion was attached as leading trivia to the closing brace)...

Yes.  If you're making new nodes out of existing nodes, then that's what will happen.  I question *why* you're doing that though.  Why not just make new nodes from scratch.  You don't need to provide unambiguous tokens.  i.e. you don't need to provide the curlies for  a new type-declaration.  Roslyn will add them automatically through the helper factory methods if you leave them out.

**Comment by CyrusNajmabadi** [comment]
I recommend this page: https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Syntax-Analysis

Using the syntax visualizer can also be super helpful.

**Comment by CyrusNajmabadi** [comment]
Note: i would also recommend you look into SyntaxGenerator/SyntaxEditor, which are APIs that try to make some of this work simpelr and easier.  You're directly talking to the low level API whose purpose is to be completely explicit and fully representative of all hte intracacies you have to care about in C# for every single construct.
