### ISSUE TITLE
Unable to use roslyn as a library to create a custom language

### ISSUE THREAD

**Issue by alexanderuv** [dotnet/roslyn#19323]
**Version Used**: 2.1

**Steps to Reproduce**:

1. Try to inherit Compilation
2. Boom! internal constructor

**Expected Behavior**:
A true open framework should allow for extension. Why keep everything internal?

**Actual Behavior**:
No chance of proper extension (unless forking roslyn itself, which seems like overkill)

**Comment by Pilchie** [comment]
Roslyn is not intended to be a framework for creating custom languages.  It is intended to be a C# and a VB compiler.
