### ISSUE TITLE
VB: Intellisense for members of delegates created as lambda expressions in With-statement.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#19337]
**Version Used**: 
Visual Studio Community 2015

**Steps to Reproduce**:
Type the following code:

```vb
With Function() New ArgumentException
  .Invoke()
End With
```

**Expected Behavior**:
Pressing the dot character before typing ```Invoke()``` should pop-up the intellisense completion list with members from the delegate type implied by the lambda expression ```Function() ...```

**Actual Behavior**:
The pop-up completion list does not show. However adding another dot after ```Invoke()``` does bring up the list (in the above code case you see members of the ```ArgumentException``` type as expected). The problem seems to be related to inferring that the With-statement expression creates a delegate type, because if you remove the lambda and just create a plain object as follows, the dot brings up the completion list immediately so you can auto-complete the ```ToString()``` member:

```vb
With New ArgumentException
  .ToString()
End With
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
