### ISSUE TITLE
Clone objects

### ISSUE THREAD

**Issue by juanpaexpedite** [dotnet/roslyn#1933]
I understand the implementation of ICloneable and the base of MemberwiseClone, but when I try to use in the real world (XAML) I cannot use it due to many problems, like it is protected, casting to object, COM issues, sealed classes. 
 Always the alternatives are a 'deep' for each of the properties, serializations. But for instance Storyboard is really hard to clone, it has Arrays and it is imposible to clone in a generalized way. So I do not understand why the option to clone is so complicated if the object and it's objects are in somepart of the memory and it could be replicated without all this issues. Just a MemoryClone.

**Comment by sharwell** [comment]
There is no one definition for "Clone". In fact, you can't even break this operation into "deep" and "shallow" cloning, because you also have objects like `string` which is clone-by-reference. You'll need to very specific about what you are trying to do before we can talk about what a "clone" is in your case.

**Comment by gafter** [comment]
@juanpaexpedite what Roslyn component is this reported against?

**Comment by juanpaexpedite** [comment]
I am not an expert in the deeps of everything, I will try to be more specific:

1.- MemberwiseClone is protected so I can only use in my classes and only for the Fields.
2.- The usual way to use it is by implementing in my classes
class MyClass: ICloneable {
    //...
    public MyClass Clone() { return (MyClass )this.MemberwiseClone(); }
    object ICloneable.Clone() { return Clone(); }
}
3.- MemberwiseClone only clones fields.

So in the last case I try to clone more generic is the 
 Assembly Windows.Foundation.UniversalApiContract
 Windows.UI.Xaml.Media.Animation
 public sealed class Storyboard

It does not have Clone method, so the only way to implement that is this link
http://www.moonmile.net/blog/archives/4087

I was able to generalize it a bit,but Is it acceptable this effort? 

And I do not consider serialize and deserialize is the optimum way because you lost bindings.

I hope with this example the issue is more clear to have another kind of clone at the roslyn capabilities.

**Comment by gafter** [comment]
@juanpaexpedite Where in the Roslyn APIs do you find the `MemberwiseClone` that you are referring to?

**Comment by gafter** [comment]
Closing this issue as it does not appear related to the Roslyn APIs. Please let me know if that's wrong.
