### ISSUE TITLE
Want the `interface` `class` `virtual` `override` keywords clickable

### ISSUE THREAD

**Issue by pawchen** [dotnet/roslyn#19332]
When ctrl + clicked, show something listing all related definitions and allow the items to click and Peek, so one can easily go "up" and "down"?

**Comment by miloush** [comment]
So many times I wanted to go to the overridden member indeed!

**Comment by Pilchie** [comment]
I love this idea, and it relates to the work in https://github.com/dotnet/roslyn/pull/18966.

Tagging @kuhlenh and @DustinCampbell too for thoughts.

**Comment by alrz** [comment]
Also F12 on the decl itself should go to usages.

**Comment by pawchen** [comment]
Closing as the up/down button is available in VS2022.
