### ISSUE TITLE
.editorconfig discovery isn't correctly ordered in some cases

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#19355]
Right now the build task isn't returning the correct ordering if you had a directory structure roughly like:

.editorconfig
a\\.editorconfig
b\\.editorconfig

**Comment by Pilchie** [comment]
Sadly, this editorconfig work isn't going to fit for 15.3, but we're going to continue targeting the next foundation update.

**Comment by dpoeschl** [comment]
Unfortunately not getting to this editorconfig work in 15.5, but we will target the next foundation update.

**Comment by agocke** [comment]
This is no longer necessary, as the compiler structure has been refactored to handle this, instead of the build task.
