### ISSUE TITLE
Handle special edge case in simplification

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#19368]
**Version Used**: Master with #19258 merged

A test already exists for this case, but was disabled as part of #19258. This behavior impacts both automatic simplification scenarios (running the simplifier as part of code formatting) as well as the simplication cases detected through an analyzer.

⚠️ When working on a correction to this, be careful not to regress on the performance benefits provided by #19258.

**Steps to Reproduce**:

1. Defined a nested type `B` which contains a nested type of the same name as a static method of the containing type `A`
2. Within a method of `B`, invoke the static member of `A` through a qualified reference
3. Attempt to use the IDE diagnostics to simplify the reference to no longer be qualified

Example:

```csharp
using System;
class A
{
  static void Del() { }
  class B
  {
    delegate void Del();
    void Boo()
    {
      Del d = new Del(A.Del); 
      A.Del(); // Attempt to simplify this
    }
  }
}
```

**Expected Behavior**:

The invocation should be simplified to just `Del()`.

**Actual Behavior**:

The invocation remains as `A.Del()`.

**Comment by CyrusNajmabadi** [comment]
Closing out.  If we wnat to fix this we should just fix it. Having a tracking bug for 7 years doesn't help us.
