### ISSUE TITLE
Convert base / Insert digit separators refactorings are not available when the caret is at the end of a numeric literal

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#19369]
**Version Used**: Latest magma-hot bits

**Steps to Reproduce**:

```C#
class C
{
    int x = 42;
}
```

1. Place editor caret between `2` and `;`
2. Press <kbd>Ctrl</kbd>+<kbd>.</kbd>

**Expected Behavior**: 'Convert base' and 'Insert digit separators' refactorings should be available.

**Actual Behavior**: They're not.

**Comment by Pilchie** [comment]
@alrz - interested in another one?
