### ISSUE TITLE
API replacement for named arguments in IOperation

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#19371]
**Version Used**: 
master branch

As discussed in https://github.com/dotnet/roslyn/issues/8813:

> It is not obvious what value do we get from distinguishing between Positional and Named arguments. I believe Analyzers will be more interested in the order, in which arguments are evaluated (ArgumentsInEvaluationOrder solves that). Knowing whether the argument was named doesn't look that important and can always be discovered from syntax.

Because I have an [existing analyzer](https://github.com/bkoelman/CSharpGuidelinesAnalyzer/blob/master/src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Rules/Maintainability/AvoidUsingNamedArgumentsAnalyzer.cs) that depends on `ArgumentKind.Named`, I tried to use syntax instead. However I failed to get that working.

Please consider the next program:
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Semantics;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            const string source = @"
                class C
                {
                    void M(int i, string s = null)
                    {
                    }

                    void N()
                    {
                        M(3, s: string.Empty);
                    }
                }";

            Document document = new AdhocWorkspace()
                .AddProject("TestProject", LanguageNames.CSharp)
                .AddMetadataReferences(new[]
                {
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(ValueTuple).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(System.IO.FileSystemInfo).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(System.Reflection.Metadata.ArrayShape).Assembly.Location)
                })
                .WithCompilationOptions(new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
                .AddDocument("Source.cs", source)
                .Project
                .WithParseOptions(new CSharpParseOptions().WithFeatures(new[]
                {
                    new KeyValuePair<string, string>("IOperation", "true")
                }))
                .Documents.First();

            SemanticModel model = document.GetSemanticModelAsync().Result;

            if (model.Compilation.GetDiagnostics().Any())
            {
                throw new Exception(string.Join(Environment.NewLine, model.Compilation.GetDiagnostics()));
            }

            var typeSymbol = model.Compilation.GetTypeByMetadataName("C");
            var methodSymbol = typeSymbol.GetMembers("N").OfType<IMethodSymbol>().Single();
            var methodSyntax = (MethodDeclarationSyntax) methodSymbol.DeclaringSyntaxReferences.First().GetSyntax();

            var bodyOperation = (IBlockStatement) model.GetOperation(methodSyntax.Body);
            var statement = (IExpressionStatement) bodyOperation.Statements.First();
            var invocation = (IInvocationExpression) statement.Expression;
            var arg0 = (IArgument) invocation.ArgumentsInEvaluationOrder.First();
            var arg1 = (IArgument) invocation.ArgumentsInEvaluationOrder.Skip(1).First();

            var syn0 = (LiteralExpressionSyntax) arg0.Syntax;
            var syn1 = (MemberAccessExpressionSyntax) arg1.Syntax;

            Console.WriteLine("0: " + syn0.ToFullString());
            Console.WriteLine("1: " + syn1.ToFullString());
        }
    }
}
```

which prints:
```
0: 3
1: string.Empty
```

What would be the correct way to determine if an argument is named? If non-trivial, it would be helpful to me when I would use a boolean property `IArgument.IsNamed`.

**Comment by bkoelman** [comment]
tagging @AlekseyTs @genlu @mavasani @CyrusNajmabadi @jinujoseph

**Comment by genlu** [comment]
`IArgument.Syntax` returning the syntax for the expression instead of the entire argument is a known bug, which should be fixed soon. The goal is you would be able to get the corresponding `ArgumentSyntax` for explicit arguments (for default values and empty param array, `Syntax` will give you entire invocation I believe).

**Comment by bkoelman** [comment]
Thanks for your explanation.

Will this fix and the API changes be in the next VS update? I know that `IOperation` is still experimental, though I would like to try and keep my analyzers working as good as possible.

The changes in the features/IOperation branch will ship somewhere after that, right?

I'm very happy to see lots of efforts to make `IOperation` better! Keep up the good work ;)

**Comment by genlu** [comment]
Yes, the changes in IOperation branch will ship after next VS update, and this fix will be part of that.

**Comment by jinujoseph** [comment]
@genlu , can you confirm this is done ?
