### ISSUE TITLE
Renaming an open file causes it end up in the MiscProject

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#19389]
_From @davkean on May 2, 2017 4:5_

Dev15 Preview 1:

1. File -> New -> Console App (.NET Core)
2. In Solution Explorer, rename Program.cs -> Program1.cs
3. Notice that it ends up in Misc:

![image](https://cloud.githubusercontent.com/assets/1103906/25603591/65528600-2f40-11e7-87fd-34fc106903f9.png)

_Copied from original issue: dotnet/project-system#2102_

**Comment by srivatsn** [comment]
_From @davkean on May 2, 2017 4:9_

Note, this appears to be have been caused by: https://github.com/dotnet/project-system/pull/1841. It looks like Roslyn expects that the file has been renaming in the running document table by the time we tell them about the file. This isn't case anymore, it looks like publishing the tree used to do that.

**Comment by srivatsn** [comment]
_From @CyrusNajmabadi on May 8, 2017 19:17_

This is definitely super annoying (and a pretty bad regression).

**Comment by srivatsn** [comment]
@jasonmalinowski said in an email:

If that’s “expected” by the current code this is just a bug and nothing more. Honestly it might mean there’s a legitimate bug outside CPS scenarios too we need to look at.

My half-seriously-named Fundamental Rule of Project System Interaction is whenever we’re being told about a project/document/event that is ordered relative to some other event (in this case, a file being opened) that we have to subscribe to both the event and also see if we “missed” the event by checking the state of the system. So when we’re told about a document we check if it’s already opened (consider: a file is already opened that’s not in a project, then right click in the tree and say include in project), but still the document provider is also subscribing to IVsRunningDocumentTableEvents and should respond if we were told about the closed file and then we get the rename and respond there.

For misc files (just take a look at MiscellaneousFilesWorkspace.cs), it’s also subscribing to the IVsRunningDocumentTableEvents and implementing a “bottom feeder” approach: it’s watching the events too and attaching its own workspace to files that are open that aren’t attached to anything else. The intent of the code is to be deocupled in that it’s doing its own little thing, but bugs have creeped in because we have two components both watching IVsRunningDocumentTableEvents and are changing workspace system state in response to those events.

Unfortunately since the system we have today very much assumes those are all happening on the UI thread the ordering is fairly sane. This is why I know we have to do a good audit/formalization of some of this to get you fully onto background thread initialization. Adding documents on the background thread is OK, but at some point we do need to check the RDT and make sure that any RDT eventing is handled safe. Clean room code this is Threading 101, it’s just a bit icky if we try to shoehorn it in.

**Comment by davkean** [comment]
Do we plan on making progress on this week?

**Comment by 333fred** [comment]
This also affects when moving files from one folder to another.
