### ISSUE TITLE
Shared project model

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#19387]
I got this bug report:

----

Added a second class in same .cs file.

namespace stuff
{
class1 { }
class2 { }
}

When adding additional class in same .cs file, VS4Mac suggested moving class2 it’s own file. Instead of creating new class2.cs in existing file’s project (in this case the shared code project of the Xamarin Forms project), it moved to iOS specific project.
----

Basicaly the MoveTypeToFile refactoring moves the class to the project the shared project is associated with. Roslyn has no representation for shared projects ATM and I don't see any way to fix that - and it may affect more refactorings like generate type and so on.

Would be nice if that could be fixed in future versions.

**Comment by zspitz** [comment]
[This](https://developercommunity.visualstudio.com/content/problem/583044/rename-refactoring-does-not-work-in-files-included.html) is probably the same probem. (IIRC there's a corresponding issue here on GitHub, but I can't seem to find it now.)

**Comment by DemetrisLeptos** [comment]
the problem with sharedprojects movetype refactoring still persists - it actually crashes now - not even moving to a concrete project

**Comment by FANAU-Softwareentwicklung** [comment]
Still not working.
![image](https://user-images.githubusercontent.com/102870604/188154519-c4ee500c-736e-4f23-abdf-d0725e895a1e.png)
VS-Version 2022 - 17.3.0 Preview 6.0
.NET Framework 4.8

**Comment by CyrusNajmabadi** [comment]
Closing as this sis a vs4mac scenario, whcih is now gone.
