### ISSUE TITLE
How to check if a Class or a Method is a Partial Class or Partial Method

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#19386]
**Version Used**: 
2.0.1

**Steps to Reproduce**:

1. For any Partial Class/Method, the corresponding **ClassDeclarationSyntax** node or **MethodDeclarationSyntax** node data does not give any information if the given class is Partial class/method. 
2. We dont get this information even from any property of **INamedTypeSymbol** for Class or **IMethodSymbol** for Method.
3. We can get this information only using **node.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword))**.

**Expected Behavior**:
There has to be some property in **ClassDeclarationSyntax** node or **MethodDeclarationSyntax** node or in **INamedTypeSymbol** for Class or **IMethodSymbol** for Method which gives us the information that the node is a partial type. 

**Actual Behavior**:
There isnt any property currently  in **ClassDeclarationSyntax** node or **MethodDeclarationSyntax** node or in **INamedTypeSymbol** for Class or **IMethodSymbol** for Method which gives us the information that the node is a partial type.

**Comment by alrz** [comment]
>We can get this information only using node.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)).

True. you could define an extension method on `ClassDeclarationSyntax` for it. Also I think this information is not available for symbols since partial-ness compiles away once the parts are merged and turned to a single symbol.

**Comment by CyrusNajmabadi** [comment]
Do you care if hte symbol was *declared* partial?  Or actually has multiple partial types.  For example, you might have:

```c#
partial class C { }

partial class D { }
partial class D { }
```

Do you want C and D to report that they're partial?  Or just D?

If the former, then you can do this just by checking the modifiers of these class declarations.
If you only care about the latter, then just get the ```INamedTypeSymbol``` for the type, and check. ```ISymbol.Locations.Length``` or ```INamedTypeSymbol.DeclaringSyntaxReferences.Length``` to see if hey are ```> 1```.
