### ISSUE TITLE
Automatic referencing of mscorlib on coreclr

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#1939]
Unless the [/nostdlib](https://msdn.microsoft.com/en-us/library/fa13yay7.aspx) option is passed the C# compiler will automatically add a reference to mscorlib for the compilation.  The compiler assumes that mscorlib exist inside [GetCORSystemDirectory](https://msdn.microsoft.com/en-us/library/k0588yw5%28v=vs.110%29.aspx) / [RuntimeEnvironment::GetRuntimeDirectory](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.runtimeenvironment.getruntimedirectory%28v=vs.90%29.aspx).  No checking is performed on this, it simply assumes the file exists in that location. 

This process doesn't make sense when the compiler is run under coreclr for a couple of reasons:

- There is no mscorlib in coreclr scenarios.  Instead there are a set of contract assemblies to be referenced. 
- There is no SDK directory to search for.  The CoreCLR deployments for the compiler will include the runtime assemblies, not the contract assemblies.  

Note that relying to the desktop APIs even when running under coreclr is not really an option.  They won't exist on xcopy installs or cross platform.  

We need to come up with a suitable cross plat / coreclr strategy for this scenario.

**Comment by tmat** [comment]
I think we might need to replicate the CLR loader logic in mscoree.

**Comment by jaredpar** [comment]
@tmat but what would be the end goal?  There is no mscorlib to reference.  Which DLL would we pick instead?

**Comment by tmat** [comment]
When a manged exe is being loaded by Windows mscoree finds the CLR (and mscorlib) installed on the box and loads it. Presumably it looks up some registry/environment values. GetRuntimeDirectory imo just returns the location the executing runtime is initialized from. So I guess we need to check the same registry values mscoree does. Of course, that code would be Windows specific.

**Comment by jaredpar** [comment]
@tmat right but what DLL should we eventually implicitly add a reference to?  There is no mscorlib in a coreclr scenario on say Linux.  Adding a reference to the corelib we sym ship with the compiler is wrong because it's a DLL that is never meant to be referenced by the user.

**Comment by tmat** [comment]
Correct, I don't think we can make it work on Linux. We can make it work for csc running CoreCLR on Windows. On linux that feature would just not be available. The user has to specify the path to mscorlib.

**Comment by tmat** [comment]
Or perhaps if you have Mono installed it sets some env variable that we can use (equivalent of the registry entry).

**Comment by VSadov** [comment]
One does not seem to contradict another. We could fetch the SDK location from several source
1) command line args
2) environment variable (only if  # 1 fails)
3) from some global registry/GetRuntimeDirectory source (only if # 2 fails)

This way it would be possible to control the default behavior with appropriate granularity and still override it locally if needed.

**Comment by agocke** [comment]
Answer: no default referencing, mscorlib is dead, long live System.Runtime
