### ISSUE TITLE
Naming suggestions after out var

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#19409]
![image](https://cloud.githubusercontent.com/assets/3751401/25922844/9466918e-358f-11e7-95dc-4f9d41255217.png)

**Comment by rchande** [comment]
cc @CyrusNajmabadi

**Comment by sharwell** [comment]
I marked this as **Bug** instead of **Feature Request** since it's so clear what the expected behavior needs to be and was just a minor oversight when implementing the feature originally.

**Comment by rchande** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/20792
