### ISSUE TITLE
Set next statement crashes Visual Studio

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#1941]
Repro:

- Open Roslyn.sln
- Set vbc2 as the startup project
- Set a breakpoint on line 64 of BuildClient.cs (https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/BuildClient.cs#L64) 
- F5
- When the breakpoint hits that line right click and select "Set Next Statement"
- Seletct `return fallbackCompiler(...)`

At this point the IDE will crash.

Stack trace not provided because attaching with windbg before invoking the "Set Next Statement" command causes the crash to not occur.

**Comment by ManishJayaswal** [comment]
Looks like it is the diasymreader version mismatch issue.

**Comment by ManishJayaswal** [comment]
This should be fixed after Kevin updated the debugger bits.
