### ISSUE TITLE
15.3 Preview breaks build with System.Runtime version mismatches

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#19425]
_From @AArnott on May 10, 2017 20:18_

Building in a 15.2 VS Developer Prompt works fine, but when building in a 15.3 Preview prompt, I get lots of errors like this:

```
CSC : error CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.IO' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [F:\git\DevCore\src\clr\tests\TestService\TestService.csproj]
CSC : error CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'StreamJsonRpc' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [F:\git\DevCore\src\clr\tests\TestService\TestService.csproj]
CSC : error CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Diagnostics.TraceSource' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [F:\git\DevCore\src\clr\tests\TestService\TestService.csproj]
```

### Repro steps

```
git clone https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/DevCore
cd devcore
cd src\clr
msbuild /t:restore
msbuild
```

If you get other errors, you might run the "init" script in the root of the repo and try to build again.

MSBuild that is broken: 15.3.118.39484
MSBuild that works: 15.1.1012.6693

_Copied from original issue: Microsoft/msbuild#2088_

**Comment by AArnott** [comment]
_From @AndyGerlicher on May 10, 2017 23:4_

Is this a compiler error? Or is the input somehow changing after you upgrade to 15.3?

**Comment by AArnott** [comment]
The input is not changing. I have one enlistment and two VS command windows open. One works, one doesn't.

**Comment by AArnott** [comment]
Good point about it being a compiler error. The differences between the compiler command line are essentially this:

```diff
- /nowarn:1701,1702,1705,CS1591,1701,1702
+ /nowarn:CS1591,1701,1702
```

So CS1701 is an error in the build output, even though both switches include nowarn for 1701. although interestingly, 15.2 specifies it twice whereas 15.3 only specifies it once. 
So I guess this looks like a compiler bug rather than an msbuild one. I'll move it.

**Comment by jaredpar** [comment]
This is not an issue in the compiler.  The warning behavior here is unchanged as are our targets.  It appears to either be a core MSBuild targets issue or related to the new SDK targets.
