### ISSUE TITLE
Cache delegate for non-capturing local functions when caching delegates for static methods

### ISSUE THREAD

**Issue by pawchen** [dotnet/roslyn#19431]
This issue is created in respond to https://github.com/dotnet/roslyn/pull/6642#issuecomment-300571520

Currently #6642 avoids local functions completely, as local functions all appears `IsStatic` but they could capture things. When it makes into a feature branch, consider support them like non-capturing lambda.

Also need to consider what to do when the delegate type involves generic parameters from any local functions.

**Comment by jcouv** [comment]
FYI @agocke (relates to local functions)

**Comment by pawchen** [comment]
Closing as this is done in #58288. Just mark the targeting local function as `static`.
