### ISSUE TITLE
Save & Paste format VB documents when Pretty Listing disabled

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#1944]
Forking this issue from #1156.

This is a regression from VS2013.

1. Disable VB pretty listing.

2. Copy/paste VB:
    ```VB
    Module Module1
        Dim z    = 7
        Dim zzzz = 8
        Sub M()
            Dim a     = 7
            Dim bbbbb = 7
        End Sub
    End Module
    ```

**Expected**: Pasted code has the same formatting as above (with lots of spaces after ```z``` and ```a```).
**Actual**: Pasted code is formatted

**Note**: The same problem occurs with the save command. There may be other commands too, but these are the two I'm aware of.

**Comment by Pilchie** [comment]
I wonder if the save that is part of the global undo is the trigger for #1945.  Can you take a look?
