### ISSUE TITLE
Use dev15.3 compiler as toolset and change Roslyn projects to use "latest" language version

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#19443]
FYI @CyrusNajmabadi

**Comment by sharwell** [comment]
This will break external contributor scenarios prior to 15.3 shipping. I may not hurt to update the toolset, but we can't change the language version yet.

**Comment by jcouv** [comment]
If we don't dogfood new languages features before release, nobody else will. So I'd favor ironing out problems so that we can go ahead with dogfood.

What kind of break(s) do you expect from updating the language version and using the new language features?

**Comment by jcouv** [comment]
@sharwell Discussed this with Jared. He agrees we should move forward.

There are two options (both for internal and external contributors):
- do nothing: then some contributors may notice red squiggles on new syntax (in the few places they will be introduced) that won't actually block their build.
- contributors can install Roslyn nightlies (I have posted Kevin's [nightlies instructions](https://github.com/dotnet/roslyn/issues/18783#issuecomment-299064434) for reference)
