### ISSUE TITLE
Any profiler command line argument?

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#19453]
I don't know it exist or not but I have seen mono have `--profile=log` command line argument. Did the roslyn have any easy profiling log?

I wish I could log at least all the method call instead of going in every method and put `Console.WriteLine(stackTrace)` manually

**Comment by jcouv** [comment]
@Thaina
Could you clarify what the problem you're trying to solve?

Although I have not used a profiler in a while, I can see a number of them when searching for ".NET profiler". The kind of instrumentation you describe can be done at runtime (when assemblies are loaded), without help from the compiler.

**Comment by Thaina** [comment]
@jcouv What I have found is ANT and Resharper. It overkill and overprice for me who just want to log all method call (I can analyze it myself). So I think common profiler like that should just supported in `dotnet` cli itself

At I said. mono support it

**Comment by mikedn** [comment]
> At I said. mono support it

Apparently you're confusing mono with mcs and Roslyn.

> I wish I could log at least all the method call instead of going in every method and put Console.WriteLine(stackTrace) manually

That would have horrible performance and will provide skewed numbers. Use a real profiler, VS Community Edition has one built in that supports both sampling and instrumentation modes.

**Comment by Thaina** [comment]
@mikedn I'm not sure but isn't the ability to make logs out all method call in the program would be dome by compiler configuration? At least `dotnet` support `dotnet test` so wasn't `--profile` should be in the same place?

I use visual studio for mac in macso. No profiler command in that place. If you have a way to profile dotnet core on macos please tell me

If I don't forced to use macos in my workplace I would already did what you suggest

**Comment by mikedn** [comment]
> I'm not sure but isn't the ability to make logs out all method call in the program would be dome by compiler configuration?

In .NET (and likely any other similar runtime/JIT based technology - JVM, Node.JS etc.) providing profiling support is the job of the runtime, not the job of managed compilers.

> At least dotnet support dotnet test so wasn't --profile should be in the same place?

Maybe. But I don't see any pieces of `dotnet` in this repository. Pretty much the same way you won't find any pieces of test runner used by `dotnet test` in this repository.

>  use visual studio for mac in macso. No profiler command in that place. If you have a way to profile dotnet core on macos please tell me

That's unfortunate but that doesn't mean that it's the job of C# compiler to solve this.

**Comment by Thaina** [comment]
@mikedn `dotnet` is just a cli wrapping around `roslyn` isn't it?

**Comment by mikedn** [comment]
Roslyn, the C# compiler, happens to be one tool the dotnet cli invokes but I wouldn't call dotnet a wrapper around Roslyn because of that. AFAIK it doesn't even call the C# compiler directly, it uses MSBuild. And it does other things that have nothing to do with Roslyn - restoring/creating packages, running tests, running the assembly produced by Roslyn etc.

Having a `dotnet profile` command might be interesting/useful/desirable but that's something to be discussed with the cli and runtime teams.

**Comment by Thaina** [comment]
Thank you for your explanation
