### ISSUE TITLE
Can't resolve namespace on generic type within assignment

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19456]
1. Attempt to resolve the type between the $ -> $

``` C#

        private struct EvaluationProjectChange
        {
            public readonly IComparable Version;
            public readonly IImmutableDictionary<string, IImmutableDictionary<string, string>> Added;
            public readonly IImmutableDictionary<string, IImmutableDictionary<string, string>> Removed;

            public EvaluationProjectChange(IComparable version, IProjectChangeDescription projectChange)
            {
                Version = version;

                var added = ImmutableDictionary<string, $IImmutableDictionary$<string, string>>

                 ProjectChange = projectChange;
            }
        }
```

Expected: To resolve to a System.Collections.Immutable
Actual:

![image](https://cloud.githubusercontent.com/assets/1103906/25995633/a2423394-3756-11e7-93ff-047a4e736720.png)

**Comment by Pilchie** [comment]
Seems strange that there is no compiler diagnostic there. In your screenshot, `ImmutableDictionary` is colored, but `IIMutableDictionary` isn't.  what namespaces are each in, since it isn't in your sample.  I expect the  the problem is that until you put a `(` or a `.` after the last `>`, the compiler is parsing this as a set of comparisons :/

**Comment by CyrusNajmabadi** [comment]
I'm cure the compiler is parsing 

```c#

var added = ImmutableDictionary<string, IImmutableDictionary<string, string>>

ProjectChange
```

As the following:

"var added = ImmutableDictionary < string"

then, the comma separates out another *local variable*.  i.e. it's as if you wrote:

"var x = x < y, z = 0"

So "IImmutableDictionary" now becomes the name of the second variable.  And then the parser goes completely off the rails at that point.

I think i may be able to help things out here.  But the general problem of ambiguity and concervatism around incomplete generics will almost always be a problem for the IDE.

**Comment by CyrusNajmabadi** [comment]
@Pilchie Fixing this requires a change in the parser.  Given that this is just a diminished experience, and a not a crash or anything like that, I'm not sure we could get it in with the compiler's bar for 15.3.  What do you and @jaredpar think?

**Comment by Pilchie** [comment]
@CyrusNajmabadi did you notice that I put it in the 1`5.later` milestone already? 😄

**Comment by CyrusNajmabadi** [comment]
Nope.  I only say "Pilchie added this to the 15.3 milestone 4 hours ago"  :)
