### ISSUE TITLE
Question: where to highlight new keywords?

### ISSUE THREAD

**Issue by lachbaer** [dotnet/roslyn#19460]
I'm currently prototyping an `isnot` operator. Intellisense and code completion work, but where can I make that keyword being highlighted like the other keywords?

**Comment by Pilchie** [comment]
See: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Classification/ClassificationHelpers.cs,24.

**Comment by lachbaer** [comment]
Thank you! That helped. 😃
