### ISSUE TITLE
ExtractMethod refactoring doesn't work properly when selection includes a local function

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#19461]
In the code below, select everything inside method `M`, except the local declaration for `y`, and trigger the refactoring.
![image](https://cloud.githubusercontent.com/assets/12466233/26010240/ff1f9f76-3700-11e7-9fce-0a0d1f053773.png)
The result is incorrect code:
![image](https://cloud.githubusercontent.com/assets/12466233/26010281/25692c10-3701-11e7-9ba5-d7ba2ba52647.png)

Reported via https://developercommunity.visualstudio.com/content/problem/55004/local-inline-function-c-7-issues.html

**Comment by jcouv** [comment]
FYI @agocke @Pilchie

**Comment by jcouv** [comment]
It looks like the behavior was improved since this issue was filed, and a warning is produced in the preview:
![image](https://user-images.githubusercontent.com/12466233/38155564-433efe98-342d-11e8-96e5-ace06a45e7cf.png)

**Comment by CyrusNajmabadi** [comment]
This works now (without any warning).  Adding test to demonstrate.
