### ISSUE TITLE
Quick Fix does not work for some CS0229 "Ambiguity between xxx and xxx"

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#19463]
**Version Used**: 15.3 (26508.5-Preview)

**Steps to Reproduce**:

1. New C# Solution
2. Use following code:
```CSharp

interface IList
{
    int Count
    {
        get;
        set;
    }

    void Counter();
}

interface Icounter
{
    double Count
    {
        get;
        set;
    }
}

interface IListCounter : IList, Icounter { }

class MyClass
{
    void Test(IListCounter x)
    {
        var xx = x.Count;  // <-try quick fix here
    }

    public static void Main() { }
}
```

3. Hover over `x.Count` with the mouse and choose "Show Potential Fixes"

**Expected Behavior**:

Either:
- Quick fixes are shown
or 
- If a quick fix is not possible, the option is not shown.

**Actual Behavior**:
- Clicking the "Show Potential Fixes" action link does nothing.

![image](http://i.imgur.com/HHyYSl6.gif)

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me locally.  I only see:

**Comment by CyrusNajmabadi** [comment]
Not repro.  please reopen if you see this in vsuml.
