### ISSUE TITLE
Hot path method is not checking CancellationToken

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#19464]
This method shows up on top of profile traces for us:
http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalysisState.cs,7a73fd2caadcfc67

We notice it doesn't check its cancellation token. It'd be nice to insert a few checks inside the loop so that it bails fast when the work is cancelled.

**Comment by sharwell** [comment]
@KirillOsenkov Can you describe an activity that I can do to measure this? For example, were the profile traces taken during project load, or during typing, or perhaps something else?

**Comment by KirillOsenkov** [comment]
CC @Therzok

**Comment by Therzok** [comment]
This is while typing (in VS for Mac), which queries diagnosers using engine v1.

**Comment by CyrusNajmabadi** [comment]
The link doesn't work.  Can you let us know what you wanted annotated.  Given no movement on this, i'm going to assume this hasn't been a problem.

**Comment by Therzok** [comment]
https://sourceroslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalysisState.cs,7a73fd2caadcfc67

This should work.

**Comment by CyrusNajmabadi** [comment]
That doesn't take me to any particular line.  Is there an issue here still?

**Comment by Therzok** [comment]
This is the [only method](https://sourceroslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalysisState.cs,518) in there that doesn't use the cancellationToken, there was another method, but that one has a comment as to why it's not passed.

**Comment by Therzok** [comment]
No clue if this is still an issue though. I have no context on what the problem was.
