### ISSUE TITLE
Formatting adds unexpected extra line break

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#1947]
In the code below, the resulting string contains two blank lines above "example comment" after formatting. I would expect that the single blank line is preserved. Repro for CTP6.

    using System.Linq;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp.Syntax;
    using Microsoft.CodeAnalysis.Editing;
    using Microsoft.CodeAnalysis.Formatting;
    using Microsoft.CodeAnalysis.Text;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    namespace RoslynTestCtp6
    {
        [TestClass]
        public class RoslynFormattingBug
        {
            [TestMethod]
            public void Formatter_inserts_additional_line_break()
            {
                const string source = @"

                        public class C
                        {
                            public string f1;
                    
                            // example comment
                            public string f2;
                        }

                        public class SomeAttribute : System.Attribute { }
                    ";

                var projectId = ProjectId.CreateNewId();
                var solution =
                    new AdhocWorkspace().CurrentSolution.AddProject(projectId, "test", "test", LanguageNames.CSharp)
                        .AddMetadataReference(projectId, MetadataReference.CreateFromAssembly(typeof (object).Assembly));

                var documentId = DocumentId.CreateNewId(projectId, "repro");
                solution = solution.AddDocument(documentId, "repro", SourceText.From(source));

                var document = solution.Projects.First().Documents.First();
                var compilation = solution.Projects.First().GetCompilationAsync().Result;

                var typeSymbol = compilation.GetTypeByMetadataName("C");
                var fieldSymbol = typeSymbol.GetMembers("f2").First();

                var fieldSyntax = fieldSymbol.DeclaringSyntaxReferences.First().GetSyntax();
                var varSyntax = (VariableDeclarationSyntax) fieldSyntax.Parent;

                var attribute = compilation.GetTypeByMetadataName("SomeAttribute");

                var editor = DocumentEditor.CreateAsync(document).Result;
                SyntaxNode attributeSyntax =
                    editor.Generator.Attribute(editor.Generator.TypeExpression(attribute))
                        .WithAdditionalAnnotations(Formatter.Annotation);
                editor.AddAttribute(varSyntax, attributeSyntax);

                var newRoot = editor.GetChangedRoot();
                var newDocument = editor.GetChangedDocument();

                SyntaxNode rootFormatted = Formatter.Format(newRoot, newDocument.Project.Solution.Workspace);
                string result = rootFormatted.ToString();

                // result now contains:
                /*
                public class C
                {
                    public string f1;

                    // example comment
                    [global::SomeAttribute]
                    public string f2;
                }

                public class SomeAttribute : System.Attribute { }
                */
            }
        }
    }

**Comment by mattwar** [comment]
This seems to be related to formatter directly, and not with DocumentEditor.  What happens here is that the attribute when constructed has elastic marker trivia, so there ends up being elastic trivia between the comment and the first token of the attribute that the formatter sees, convincing it to reformat the leading trivia of this token. The formatter is adding the extra line when it does this formatting.

**Comment by bkoelman** [comment]
Same problem with multi-line comment style.
