### ISSUE TITLE
Proposal: generate XML doc comments with "Create and initialize property" Quick Action

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#19479]
**Version Used**: 

Visual Studio 2017 Update 3 (26510.0-Preview)

**Steps to Reproduce**:

1. Set "XML documentation file" option on
2. Apply "Create and initialize property" Quick Action

**Expected Behavior**:

I'd like the C# compiler to generate XML doc comments on the constructor:

```cs
public struct Point
{
    /// <summary>
    /// </summary>
    /// <param name="x"><see cref="X"/></param>
    public Point(int x)
    {
        X = x;
    }

    /// <summary>
    /// 
    /// </summary>
    public int X { get; }
}
```

especially a line `<param name="x"><see cref="X"/></param>`.

**Actual Behavior**:

![image](https://cloud.githubusercontent.com/assets/3760955/26024332/4be8d502-380a-11e7-8072-2b68d6331957.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback.
