### ISSUE TITLE
'IsReservedKeyword' does not allow newly added keywords

### ISSUE THREAD

**Issue by lachbaer** [dotnet/roslyn#19471]
```cs
// Path: src\Compilers\CSharp\Portable\Syntax\SyntaxKindFacts.cs

        public static bool IsReservedKeyword(SyntaxKind kind)
        {
            return kind >= SyntaxKind.BoolKeyword && kind <= SyntaxKind.ImplicitKeyword;
        }

// Path: src\compilers\csharp\portable\syntax\syntaxkind.cs

        ImplicitKeyword = 8384,
        IsnotKeyword = 8389,

        // contextual keywords
        YieldKeyword = 8405,

```
I have added the `IsnotKeyword` (with some space to `ImplicitKeyword`) and it wasn't highlighted in the IDE, because `IsReservedKeyword` stopps the validation at `ImplicitKeyword`.

If all keywords up to `YieldKeyword` are standard keywords, shouldn't the method rather be
```cs
            return kind >= SyntaxKind.BoolKeyword && kind < SyntaxKind.YieldKeyword;
```

For now I have adapted it to end at `SyntaxKind.IsnotKeyword`, but with the next keyword being introduced a further change is due.

**Comment by lachbaer** [comment]
Just saw, same for
```cs
        public static IEnumerable<SyntaxKind> GetReservedKeywordKinds()
        {
            for (int i = (int)SyntaxKind.BoolKeyword; i <= (int)SyntaxKind.ImplicitKeyword; i++)
            {
                yield return (SyntaxKind)i;
            }
        }
```

**Comment by davkean** [comment]
I don't work on the compiler, but `Yield` is a context keyword, ie it only gets parsed a keyword based on the context, ie `yield return`, `yield break`. `IsReservedKeyword` is likely indicating keywords that always get parsed as a keyword regardless of the context, putting Yield that in that would be incorrect.

**Comment by lachbaer** [comment]
@davkean `yield`'s not in it. The condition is 'less than' not 'less or equal than'.

**Comment by davkean** [comment]
Ah, I understand your issue - you are saying "make the comparison against Yield" to avoid needing to update the next time there's a new keyword. Understood, I'll let the compiler team answer this, but there hasn't been a new non-contextual keyword for a long while (maybe v1)....

**Comment by lachbaer** [comment]
>  there hasn't been a new non-contextual keyword for a long while (maybe v1)....

At least not since Roslyn started.

**Comment by sharwell** [comment]
@lachbaer For each of the many keywords added in recent versions of the language, extreme care was taken to ensure people using that name as an identifier would not be broken during an upgrade scenario. Reserved keywords are keywords which are not allowed be be used for any other purpose in the language unless they are escaped. If, for example, you added `isnot` to the list of reserved keywords, anyone with a local variable named `isnot` would get a compilation error after the change.

To answer the specific concerns addressed by the issue:

1. `yield` is not a reserved keyword. It is only a contextual keyword, specifically an identifier which is treated as a keyword if and only if the next token is `return` or `break`.
2. No new reserved keywords are being added to C#, so the `IsReservedKeyword` does not need to be flexible in its implementation.

Other examples of contextual keywords:

* `get`
* `set`
* `add`
* `remove`
* `async`
* `await`
* `nameof`

**Comment by lachbaer** [comment]
@sharwell Thanks, I have updated the keyword to be contextual. Nevertheless the same problem occurs in the method `GetContextualKeywordKinds`:
```cs
for (int i = (int)SyntaxKind.YieldKeyword; i <= (int)SyntaxKind.WhenKeyword; i++)
{
    yield return (SyntaxKind)i;
}
```
I have updated `WhenKeyword` to `IsnotKeyword` .

If this is not by design then feel free to reopen 😄

**Comment by sharwell** [comment]
@lachbaer I don't have enough familiarity to answer that last question. I could reopen but you'll probably get a faster answer if you open a new issue specifically for `GetContextualKeywordKinds` since your new question would be more specific than this long thread.
