### ISSUE TITLE
How to generate Operations.xml.Generated.cs?

### ISSUE THREAD

**Issue by lachbaer** [dotnet/roslyn#19484]
I need to alter Operations.xml.Generated.cs, but I don't find a corresponding XML file and generator in the repo. Can I do the changes manually?

**Comment by lachbaer** [comment]
Does anyone has a preliminary answer?

**Comment by CyrusNajmabadi** [comment]
IOPeration is currently being developed.  If you want to make any changes, just edit the file directly.  However, it's likely that that work may just be blown away as @heejaechang and others continue work in this area. 

What are you trying to do?

**Comment by lachbaer** [comment]
@CyrusNajmabadi 
```cs
    /// <summary>
    /// Represents an expression that tests if a value is not of a specific type.
    /// </summary>
    /// <remarks>
    /// This interface is reserved for implementation by its associated APIs. We reserve the right to
    /// change it in the future.
    /// </remarks>
    internal sealed partial class IsnotTypeExpression : Operation, IIsnotTypeExpression
    {
        public IsnotTypeExpression(IOperation operand, ITypeSymbol isnotType, bool isInvalid, SyntaxNode syntax, ITypeSymbol type, Optional<object> constantValue) :
            base(OperationKind.IsnotTypeExpression, isInvalid, syntax, type, constantValue)
        {
            Operand = operand;
            IsnotType = isnotType;
        }
        /// <summary>
        /// Value to test.
        /// </summary>
        public IOperation Operand { get; }
        /// <summary>
        /// Type for which to test.
        /// </summary>
        public ITypeSymbol IsnotType { get; }
        public override void Accept(OperationVisitor visitor)
        {
            visitor.VisitIsnotTypeExpression(this);
        }
        public override TResult Accept<TArgument, TResult>(OperationVisitor<TArgument, TResult> visitor, TArgument argument)
        {
            return visitor.VisitIsnotTypeExpression(this, argument);
        }
    }
```

**Comment by lachbaer** [comment]
Little side node: I added `IIsnotTypeExpression.cs` to the project, without errors(!), but the project does not include the type, so that the interface inheritance above does not resolve. I had this resolved by closing IDE, cleaning and rebuilding, but nevertheless it keeps occuring from time to time. Can this be a bug?

**Comment by heejaechang** [comment]
sorry. the generator is not in yet. for now, if you want, you can add one manually along with the interfaces.

I am wondering whether what you are seeing is just timing issue or actual functional issue. when it happens again next time, can you close all opened documents, and only open the file that shows the error? and see whether it gets removed?

**Comment by jinujoseph** [comment]
Closing this as this is tracked [here](https://github.com/dotnet/roslyn/issues/20204)
