### ISSUE TITLE
We should have an analyzer that sees "(x: x, y: y)" offers to simplify to "(x, y)".

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#19485]
It will need to only be on for C# 7.1 and above.

**Comment by AdamSpeight2008** [comment]
Would it affect subsequent usages of the named items of the tuple? Ie the `x:` and `y:` parts.

**Comment by CyrusNajmabadi** [comment]
I'm not sure what you mean :)

**Comment by AdamSpeight2008** [comment]
@CyrusNajmabadi 
For example.
```
var t (x: x, y: y) = foo;
t.x
t.y
```

**Comment by sharwell** [comment]
@AdamSpeight2008 No. This is a new feature (C# 7.1) allowing the names to be inferred from the initialization:
https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.1/infer-tuple-names.md

**Comment by jcouv** [comment]
@CyrusNajmabadi If you have not started on this I could take a stab. Let me know.
I'm assuming I can follow what you did for the "default" literal in https://github.com/dotnet/roslyn/pull/19499.

**Comment by CyrusNajmabadi** [comment]
I haven't started.  So feel free.  Your assumption on how to do this is correct.   Thanks!

**Comment by jcouv** [comment]
@CyrusNajmabadi Should there be two separate preferences for "prefer inferred member name": one for tuples and one for anonymous types? Or should they share a single preference?

**Comment by CyrusNajmabadi** [comment]
Let's go with two preferences.  It doesn't really hurt anyone to have both, and it prevents a case where someone happens to prefer opposing forms and has no way to specify that.

**Comment by jcouv** [comment]
Fixed by #20649 (also includes same treatment for anonymous types).
