### ISSUE TITLE
'GetContextualKeywordKinds' does not allow newly added keywords

### ISSUE THREAD

**Issue by lachbaer** [dotnet/roslyn#19491]
I have added a new contextual keyword `isnot`. The method `GetContextualKeywordKinds` at `WhenKeyword`.

```cs
        WhenKeyword = 8437,
        IsnotKeyword = 8447,

        // additional preprocessor keywords
        ElifKeyword = 8467,

// Path: src\Compilers\CSharp\Portable\Syntax\SyntaxKindFacts.cs

public static IEnumerable<SyntaxKind> GetContextualKeywordKinds()
{
    for (int i = (int)SyntaxKind.YieldKeyword; i <= (int)SyntaxKind.IsnotKeyword; i++)
    {
        yield return (SyntaxKind)i;
    }
}

```

I have updated `WhenKeyword` to `IsnotKeyword` and put it to the end of the contextual keyword list with an appropriate new ID.

Shouldn't it be rather `i < ElifKeyword` so that it must not be adapted every time a new keyword is added?

**Comment by CyrusNajmabadi** [comment]
Feel free to make that change and submit it as a PR.  :)
