### ISSUE TITLE
Pretty lister changes case of unresolvable types

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#1949]
Consider the following code snippet:

``` vb
Dim outputKind as OutputKind = OutputKind.ConsoleApplication
```

In the case where `OutputKind` is unresolvable (has a squiggle) any pretty listing of that line will change the output to:

``` vb
Dim outputKind as outputKind = outputKind.ConsoleApplication
```

This makes editing code not feasible with the build is in a broken state.

**Comment by Pilchie** [comment]
It seems like the check at http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic.Workspaces/CaseCorrection/VisualBasicCaseCorrectionService.Rewriter.vb,135 should prevent at least the first of these - not sure about the second.

Maybe we shouldn't be using `GetAnySymbol` for case correction, but only symbols that don't have errors?
