### ISSUE TITLE
DataFlowAnalysis fails on local functions

### ISSUE THREAD

**Issue by torgabor** [dotnet/roslyn#19504]
**Version Used**: 
2.1.0.0
**Steps to Reproduce**:

Using the following code:

```cs
	class Program
	{
		static void Main(string[] args)
		{
			var tree = CSharpSyntaxTree.ParseText(@"
public class Program
{
	public static void Main()
	{
		int y = 3;
		int val(int z) => y += z;
	}
}");

			var mscorlib = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);

			var compilation = CSharpCompilation.Create("MyCompilation",new[] { tree }, references: new[] { mscorlib });
			var model = compilation.GetSemanticModel(tree);
			var local = tree.GetRoot().DescendantNodes().OfType<LocalFunctionStatementSyntax>().Single();
		
			DataFlowAnalysis localResult = model.AnalyzeDataFlow(local);
		}
	}
```
localResult.Succeeded will be false.
Replacing the local function with a lambda expression yields correct analysis.
Compilation finished without errors
Calling the val() or consuming its result makes no difference.

**Comment by alrz** [comment]
https://github.com/dotnet/roslyn/issues/14214

**Comment by torgabor** [comment]
Sorry, for creating a duplicate, I didn't notice the previous issue.  Should I close this now, or should this remain open till the original is resolved?

**Comment by alrz** [comment]
This is a dup of #14214 as the issue is being tracked there, so you can close this one.
