### ISSUE TITLE
By default, cannot hit breakpoints in UTF-8 files with no BOM...

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#19514]
**Steps to Reproduce**:

1.  Create a new C# Console Appliction
2.  Open Program.cs in a hex editor and remove the BOM
3.  Place a breakpoint in void Main
4.  F5

**Expected Behavior**:
Breakpoint is hit

**Actual Behavior**:
Breakpoint is not hit unless you select the option to allow source to differ from original version

**Comment by KevinH-MS** [comment]
I'm not sure if this is an issue in Roslyn, but opening here, because I heard from @tannergooding that we may have made some changes here to allow debugging files that had "insignificant" whitespace changes.

**Comment by tannergooding** [comment]
Tagging @tmat. I believe the changes were going to be around newline, so I don't think that should be impacting this.

**Comment by tmat** [comment]
It doesn't seem to repor on the latest build: 26510.0-Preview d15rel (dogfood channel), Roslyn 2.3.0.6171503

**Comment by KevinH-MS** [comment]
I checked out d15prerel 26515.1, and you're right, it doesn't seem to repro any more.  Closing...

**Comment by KevinH-MS** [comment]
FYI @genlu, since I know you were hitting this too.  If you upgrade to the latest VS, the issue should go away.
