### ISSUE TITLE
Microsoft.CodeAnalysis.UnitTests.LoggingTests.TestAllocationPooling failed in CI

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#19512]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit64_prtest/6298/testReport/junit/Microsoft.CodeAnalysis.UnitTests/LoggingTests/TestAllocationPooling/

```
MESSAGE:
Assert.Same() Failure\r\nExpected: RoslynLogBlock { }\r\nActual: RoslynLogBlock { }
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.UnitTests.LoggingTests.TestAllocationPooling() in q:\roslyn\src\Workspaces\CoreTest\UtilityTest\EtwLoggingTests.cs:line 16
```

**Comment by tmat** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/14612/testReport/junit/Microsoft.CodeAnalysis.UnitTests/LoggingTests/TestAllocationPooling/

**Comment by sharwell** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/14677/testReport/junit/Microsoft.CodeAnalysis.UnitTests/LoggingTests/TestAllocationPooling/

**Comment by jaredpar** [comment]
Closing as this hasn't shown up in a while. Will reopen as necessary.

**Comment by 333fred** [comment]
Reopening: https://dnceng.visualstudio.com/public/_build/results?buildId=57111

**Comment by JoeRobich** [comment]
Hit this in #31782 [Build](https://dnceng.visualstudio.com/public/_build/results?buildId=58162)

**Comment by jaredpar** [comment]
@JoeRobich do you have a link to the failure? The second link you posted seems to go to a new build.

**Comment by JoeRobich** [comment]
Follow that link and use the "Attempt" dropdown and choose Attempt 1.

**Comment by jaredpar** [comment]
Oh nice. Haven't seen that before.

**Comment by JoeRobich** [comment]
Hit this in #32455 - [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=72780&view=ms.vss-test-web.test-result-details) Attempt 1

**Comment by JoeRobich** [comment]
Hit this again [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=73055&view=ms.vss-test-web.test-result-details) Attempt 1

**Comment by jaredpar** [comment]
@JoeRobich that test looks broken. It assumes that using an ObjectPool if you free then allocate the allocate will return the freed value. I'm not sure we guarantee that semantic.

**Comment by jaredpar** [comment]
Consider the case where there is a background thread going from a previous test. It could be manipulating the pool in the background in which case the identity won't be preserved.

**Comment by mavasani** [comment]
Failed again: https://dev.azure.com/dnceng/public/_build/results?buildId=79650&view=ms.vss-test-web.test-result-details

**Comment by JoeRobich** [comment]
Hit this in #33058 - [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=85804&view=ms.vss-test-web.build-test-results-tab) - Attempt 1

**Comment by jaredpar** [comment]
This looks like it's more on the IDE side of workspaces than compiler. As my previous analysis stated this testing is flawed and should probably just be deleted. Rather than comment again I'd suggest the commentor send a PR to delete the suite.
