### ISSUE TITLE
VS uses CPU while user is not actively working on VS

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#19515]
while user is idle, Roslyn is spinning CPU. we should reduce as much as possible on VS side and do that on OOP side.

**Comment by CyrusNajmabadi** [comment]
Do you have a trace that shows where the CPU time is spent?

**Comment by heejaechang** [comment]
I opened this bug because I needed a bug for PR. this is about what andrew said about making too much connection to service hub.

**Comment by sharwell** [comment]
Closing per #19516.
