### ISSUE TITLE
VB SyncLock error ?

### ISSUE THREAD

**Issue by vbcodec** [dotnet/roslyn#19524]
```
Public Class DBConnectionLink
    Shared Errors As New List(Of AppError)

    Public Shared Sub WriteErrors()
        SyncLock Errors
            For Each E In Errors
                Try
                    MonitoringError(E)
                Catch ex As Exception
                End Try
             Next
             Errors.Clear()
        End SyncLock
    End Sub

    Friend Shared Sub AddError(Err As AppError)
        SyncLock Errors
            Errors.Add(Err)
        End SyncLock
    End Sub

End Class
```

Function WriteError is called by single background thread, while AddError by other working thread(s)
Calling WriteErrors throw (sometimes) exception:
 
```
Message: Collection was modified; enumeration operation may not execute. 
Stack: 
in System.ThrowHelper.ThrowInvalidOperationException
in System.Collections.Generic.List`1+Enumerator.MoveNextRare
in System.Collections.Generic.List`1+Enumerator.MoveNext
in Tools.DBConnectionLink.WriteErrors 
```

**Comment by jaredpar** [comment]
This is very unlikely to be a VB compiler issue. The code here is very straight forward and compiles down to the expected `Monitor.Enter` / `Monitor.Exit` calls. If you see an issue with the compiled IL where it's not doing this correctly please send us that. 

I think what is more likely here is a single threaded reentrancy problem. Essentially that the call to MonitoringError is inadvertently triggering a call to AddError.
