### ISSUE TITLE
CSharpNavigateTo.NavigateTo is flakey.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#19530]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/4219/consoleFull#9716893042d31e50d-1517-49fc-92b3-2ca637122019

      Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpNavigateTo.NavigateTo [FAIL]

VB test has also been disabled.

**Comment by Pilchie** [comment]
Can you take a look?  You're probably the most familiar with Navigate To right now.

**Comment by CyrusNajmabadi** [comment]
Assigning to Ravi.  The port from the previous test seems to have made this flakey.

**Comment by CyrusNajmabadi** [comment]
Looking at the code, it's definitely a race condition in the test.  The test invokes:

            VisualStudio.Editor.InvokeNavigateTo("FirstMethod");

This calls to invoke 'go to', and then types, and then waits for the async tasks of Roslyn's navto implementation to complete.  However, there's nothing htat ensures that the async tasks of Roslyn's navto implementation have even started.  i.e. the editor will call into NavigateToItemProvider.StartSearch.  But they do do on a BG thread.  So it's completely possible for the test to say "wait for roslyn nav to" to which roslyn's nav to says "i'm not doing anything".  The test then tries to validate the editor, and fails because nothing has actually happened.

**Comment by rchande** [comment]
@CyrusNajmabadi The test also sends an "Enter" to the Go To dialog. If you send enter to Go To before the search is completed, what is supposed to happen?

The tao-based test as an enormous (http://index/?query=navigatetoaction&rightProject=Microsoft.VisualStudio.Shell.UI.Internal&file=Packages%5CNavigateTo%5CNavigateToSession.cs&line=21) amount of infrastructure for testing GoTo so I'm hoping we can do something more lightweight.

**Comment by CyrusNajmabadi** [comment]
> The test also sends an "Enter" to the Go To dialog. If you send enter to Go To before the search is completed, what is supposed to happen?

No clue.  I imagine it might just dismiss the dialog.

--

We might have to work with the editor to provide a way to say: we've typed code, please kick off the actual call to the providers.  Otherwise, we're fundamentally racey here.  We're communicating with another component and assuming that once they return, that it's safe to proceed.  But it really isn't  in this case.

**Comment by CyrusNajmabadi** [comment]
tagging @olegtk

**Comment by MattGertz** [comment]
Leaving in 15.3 for the moment , but if this involves a lot of plumbing anywhere, we'll need to move it.

**Comment by CyrusNajmabadi** [comment]
VB test has also been disabled.

**Comment by olegtk** [comment]
Can you first wait till your provider's StartSearch() is called? Unfortunately I don't see any waitable entities in NavigateTo core.
Also, just to confirm - you cannot use Apex test framework because it's not public, right? Apex has pretty good support for testing NavigateTo.

**Comment by CyrusNajmabadi** [comment]
> Can you first wait till your provider's StartSearch() is called

We could.  However, it violates the spirit of our Integration Tests being blackbox tests.  We just send normal events and we then validate the state of VS.  We don't like having to hook up special code that has intimate knowledge of the internals of something like NavigateTo.  

> Also, just to confirm - you cannot use Apex test framework because it's not public, right? Apex has pretty good support for testing NavigateTo.

I personally don't know.  But if Apex isn't public then that would be a no-go because then customers could not properly work with it.

**Comment by olegtk** [comment]
This asynchrony is pretty fundamental part of any search that is based on the VS shell's common search control. I'm not even sure this can be solved without any feature-specific test plumbing. Creating synchronous code path that is only used by tests also sounds like a violation of the black box sprit to me.
Please file a bug and let's discuss it, this needs some design.

**Comment by CyrusNajmabadi** [comment]
>  I'm not even sure this can be solved without any feature-specific test plumbing

Yes/no.  As mentioned in our email thread about ITextBuffer.ChangedAsync, there can be a generalized mechanism for features to indicate that they are currently performing work, and that same mechanism can be used by tests to appropriately wait for the right moments to move forward or validate things.

So yes, it would need test plumbing.  But i don't think it's feature-specific.  It's just a generalized mechanism that each feature can use.

**Comment by MattGertz** [comment]
Mondo escrow triage:  moving out.
