### ISSUE TITLE
ProjectExternalErrorReporter can't be used by F# 

### ISSUE THREAD

**Issue by dsyme** [dotnet/roslyn#19547]
#### ProjectExternalErrorReporter can't be used by F# because it requires a CompilerDiagnosticsAnalyzer (and we don't have one of those)

In the Visual F# IDE Tools, we are trying to use Roslyn to report both document (intellisense) and compiler (build) error messages.    We already do the former.  If we use Roslyn for both, we expect we will solve our [error message unification regressions](https://github.com/Microsoft/visualfsharp/issues/3047).

For the document errors we already use a [DocumentDiagnosticAnalyzer](https://github.com/Microsoft/visualfsharp/blob/ce473ddab307c1bbbf027207badf086e71a238ff/vsintegration/src/FSharp.Editor/Diagnostics/DocumentDiagnosticAnalyzer.fs#L26).  For the build-time error messages, our plan was to use the instance of [ProjectExternalErrorReporter we create](https://github.com/Microsoft/visualfsharp/blob/722a64a98735c6c7e9c988f7b43fada0cf4940ba/vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs#L415) and [pass to CreateProjectContext](https://github.com/Microsoft/visualfsharp/blob/722a64a98735c6c7e9c988f7b43fada0cf4940ba/vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs#L427).  This seems like a reasonable expectation of how things should work.

However,  AFAICS using this ``ProjectExternalErrorReporter`` ends up trigggering code that goes down [this path which does a FailFast.OnFatalException in DiagnosticIncrementalAnalyzern](https://github.com/dotnet/roslyn/blob/175c1605927859bc3cfcd4a84b720b27c4054ba9/src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateManager.cs#L139).  because the Visual F# Tools don't implement a CompilerDiagnosticsAnalyzer object. 

Possible solutions are

1. Visual F# Tools just don't try to use ``ProjectExternalErrorReporter`` for this purpose

2. Roslyn's DiagnosticIncrementalAnalyzer is adjusted so it doesn't require the language to have a CompilerDiagnosticsAnalyzer 

3. Someone says the magic recipe to create/register/access an appropriate CompilerDiagnosticsAnalyzer and pass it into roslyn

4. Roslyn makes a change to make it possible for F# to implement a CompilerDiagnosticsAnalyzer, just like C# and VB do

**Version Used**: See https://github.com/Microsoft/visualfsharp/blob/master/packages.config

**Steps to Reproduce**: See  

1.  Build the Visual F# Tools branch mentioned in https://github.com/Microsoft/visualfsharp/issues/3047#issuecomment-301645070. 
1. open VisualFSharp.sln 
1. set VisualFsharpOpernSource as the startup project
1. Launch devenv.exe using F5
2.  In the experimental instance of VS, open a sample F# project like the ones under tests\projects\misc
3.  Make sure the project has an error in it, e.g. a syntax error
4. Compiler the project in the experimental instance

**Expected Behavior**:

Doesn't hit a ``FailFast.OnFatalException`` in Roslyn

**Actual Behavior**:

Hits  a ``FailFast.OnFatalException`` in Roslyn https://github.com/dotnet/roslyn/blob/175c1605927859bc3cfcd4a84b720b27c4054ba9/src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateManager.cs#L139

**Comment by dsyme** [comment]
Separately, while poking around, I found this code which looks unfriendly to F# and multi-language use of Roslyn in general: https://github.com/dotnet/roslyn/blob/0d6f96aa4bd85f4c616c616e0a79e41adf2283c2/src/Features/Core/Portable/Diagnostics/AnalyzerHelper.cs#L92

        public static bool IsCompilerAnalyzer(this DiagnosticAnalyzer analyzer)
        {
            // TODO: find better way.
            var typeString = analyzer.GetType().ToString();
            if (typeString == CSharpCompilerAnalyzerTypeName)
            {
                return true;
            }

            if (typeString == VisualBasicCompilerAnalyzerTypeName)
            {
                return true;
            }

            return false;
        }

**Comment by AdamSpeight2008** [comment]
@dsyme That looks like a good candidate to be overridable method on a base class maybe `DiagnosicAnalyzer` or lower.

**Comment by Pilchie** [comment]
@heejaechang can you help out here?

**Comment by heejaechang** [comment]
ya. it was never designed to be used in this way. let me look around and get back.

does F# support third party DiagnosticAnalyzer? no right?

**Comment by heejaechang** [comment]
@dsyme can you try this? https://github.com/dotnet/roslyn/pull/19561 to see whether this fix your issue?

**Comment by dsyme** [comment]
> does F# support third party DiagnosticAnalyzer? no right?

Yes it does, see https://github.com/Microsoft/visualfsharp/blob/ce473ddab307c1bbbf027207badf086e71a238ff/vsintegration/src/FSharp.Editor/Diagnostics/DocumentDiagnosticAnalyzer.fs#L25

**Comment by heejaechang** [comment]
@dsyme I didn't mean that as third party analyzer. for me, that is still 1st party analyzer.

**Comment by dsyme** [comment]
> @dsyme I didn't mean that as third party analyzer. for me, that is still 1st party analyzer.

Ah I see.  Then correct - no 3rd party.

**Comment by srivatsn** [comment]
As part of this can we also fix https://github.com/dotnet/roslyn/blob/38afa69825db300e58aa6416dbb2c14ab340da7f/src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProjectFactory.cs#L76

We seem to have hacked in an extra overload for F# instead of the original one working for F# as well.

**Comment by srivatsn** [comment]
Because of this the F# CPS projectsystem passes in null for the ProjectExternalErrorReporter today - https://github.com/dotnet/project-system/blob/360a009390105ad50695ae595ddb62dbd56b87b3/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs#L278

**Comment by heejaechang** [comment]
@srivatsn which one are you talking to? and can you be more specific on what you want?

**Comment by heejaechang** [comment]
@dsyme I need some kind of confirmation the fix I made is what you want. otherwise, can't checkin.

**Comment by srivatsn** [comment]
I'll track my comment using https://github.com/dotnet/project-system/issues/1853 instead of muddying this issue.

**Comment by dsyme** [comment]
@heejaechang Confirmation here, thanks https://github.com/dotnet/roslyn/pull/19561#issuecomment-303460245 :)
