### ISSUE TITLE
IDE adds @ to my new keyword

### ISSUE THREAD

**Issue by lachbaer** [dotnet/roslyn#19552]
I have added `isnot` keyword and made changes to the classification. But when typing this code:
```cs
object isnot;
if (isnot isnot string) ...
```
after the opening paren' IntelliSense suggest to write `@isnot`, though identifier `isnot` without the `@` is fine. I cannot the heck find out where this comes from. Can anybody give me a hint?

**Comment by alrz** [comment]
I think this kind of questions are better to be asked in [the Roslyn's gitter channel](https://gitter.im/dotnet/roslyn), no?

**Comment by lachbaer** [comment]
@alrz Good idea, didn't know that place. I have asked that question over there, too, and will close here as soon as I got a resolving answer.

**Comment by lachbaer** [comment]
@CyrusNajmabadi wrote on https://gitter.im/dotnet/roslyn:

I think it's StringExtensions.EscapeIdentifier
Which is called from CompletionUtilities.GetInsertionText

@CyrusNajmabadi Thank you very much! ❤️ Found it :-) My issue has been resolved, `isnot` residue from the times where it put it to the reserved keywords.
