### ISSUE TITLE
Tuple deconstruction crashes VS 2017 ide

### ISSUE THREAD

**Issue by ILAgent** [dotnet/roslyn#19554]
**Version Used**: 
VS 2017 (15.2 , 26430.6)

```
{
  "dependencies": {
 ...
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
    "System.ValueTuple": "4.3.0",  
},
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

**Steps to Reproduce**:

```
                (DrivingGuideProgressSection[], DrivingGuideProgressSection) reducedTuple = sections.Skip(1)
                    .Aggregate((new DrivingGuideProgressSection[0], sections[0]),
                        (tuple, section) =>
                        {
                            (var firstSecs, var lastSec) = tuple;
                            return lastSec.JamType == section.JamType
                                ? (firstSecs, lastSec.AddLength(section.Length))
                                : (firstSecs.Concat(new[] { lastSec }).ToArray(), section);
                        });
```
When I'm wrinting
` (var firstSecs, var lastSec) = tuple;`
IDE crashes

**Expected Behavior**:

Don't crash obiviously

**Actual Behavior**:

Crash !

**Comment by Pilchie** [comment]
Hi @ILAgent.  I'm not able to reproduce this with the latest builds.  It's possible that we've fixed it, but to confirm, can you can a look in your Event viewer for any events from ".NET Runtime" that would include the callstack of the crash?

**Comment by ILAgent** [comment]
Hi ! Unfortunatelly, I've not found appropriate events.  But it looks like https://github.com/dotnet/roslyn/issues/18674 and https://github.com/dotnet/roslyn/issues/17572 which were fixed in 15.3. 
Waiting for update...

**Comment by sharwell** [comment]
@ILAgent Thank you for taking a look. 😄

**Comment by Pilchie** [comment]
Tagging @jcouv too - does this look like a dupe?

Also @ILAgent The first 15.3 build is in the preview channel now, which you can install side-by-side with the released version to give it a try and see.  Check out https://www.visualstudio.com/vs/preview/ for details.
