### ISSUE TITLE
Type inference issue?

### ISSUE THREAD

**Issue by louthy** [dotnet/roslyn#19557]
.NET Compiler Platform: 2.0.0.6140902

I have been running into this issue for a while now, and I am wondering whether this is just a bug that nobody has noticed, or a missing feature of Roslyn (to which I need to raise a proposal in csharplang).

First if I create a function that does partial application
```c#
    static Func<B, C> Partial<A, B, C>(Func<A, B, C> f, A a) => b => f(a, b);
```
And a simple function to add two ints.
```c#
    static int Add(int x, int y) => x + y;
```
And then try to partially apply by passing `Add` and `1` to `Partial`.  
```c#
    Func<int, int> Add1 = Partial(Add, 1);
```
I get:
```
    The type arguments for method 'Partial<A, B, C>(Func<A, B, C>, A)' cannot be inferred from 
    the usage. Try specifying the type arguments explicitly.
````
This is odd to me, because the types for `Add` are known, the type for the constant `int` is known, the expected return type is known.  Why can't the `A`, `B`, and `C` of `Partial` be inferred?

If I add type arguments it works as expected:
```c#
    Func<int, int> Add1 = Partial<int, int, int>(Add, 1);
```

I _feel_ like this used to work, because I wrote a ton of overrloads for doing [currying](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Prelude/Prelude_Curry.cs) and [partial-application](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Prelude/Prelude_PartialApplication.cs) in my [functional programming library](https://github.com/louthy/language-ext); perhaps I am mistaken, but I don't remember it being so awkward to use.

**Comment by alrz** [comment]
https://github.com/dotnet/roslyn/issues/16824#issuecomment-276177025

> Type inference [doesn't infer based on an argument that is a method group](https://github.com/ljw1004/csharpspec/blob/gh-pages/expressions.md#the-first-phase), no matter how many or few members the method group has. The conversion from a method group to a delegate (of some particular type) occurs _after_ type inference has completed to determine what that delegate type is.
