### ISSUE TITLE
Convert string to Func?

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#19569]
This is more of a question than an issue, and is similar to these questions:

http://stackoverflow.com/questions/10655761/convert-string-into-func

How could one approach this today, with the current capabilities of roslyn?

**Comment by svick** [comment]
You can use Roslyn scripting. For example, using the code from the SO question:

```c#
var str = "f => f.Substring(0, f.IndexOf(' '))";
var func = await CSharpScript.EvaluateAsync<Func<string, string>>(str);
var firstWord = func("Hello World");
```

This requires the `Microsoft.CodeAnalysis.CSharp.Scripting` package.
