### ISSUE TITLE
Guidelines annoyingly "move" with the caret modifying a type declaration

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19572]
Guidelines are moving with the caret when modifying a type declaration, which is a little annoying:

![lines](https://cloud.githubusercontent.com/assets/1103906/26131940/47e36106-3ae0-11e7-85c0-79cd621e179b.gif)

**Comment by Pilchie** [comment]
@CyrusNajmabadi Is this an issue on the Roslyn side, or the platform?  Tracking spans have the wrong trackingmode?

**Comment by CyrusNajmabadi** [comment]
Tagging @gundermanc

**Comment by gundermanc** [comment]
This looks like it might be an editor side issue. I'll take a look.

**Comment by CyrusNajmabadi** [comment]
Thanks!   I don't think Roslyn has anything involved here.  We just give the raw spans.  We don't do anything with tracking spans ourselves afaict.

**Comment by davkean** [comment]
@gundermanc Do we want a VS bug on this?

**Comment by gundermanc** [comment]
Hi all, sorry for the delay, I have filed DEVDIV WI 440099 to track this issue. It is worth noting that this is not a new visual artifact, Code Lens uses positive point tracking too as pictured in the GIF.

We can probably get the desired behavior by switching to negative point tracking for both adornments.

**Comment by CyrusNajmabadi** [comment]
Closing in favor of the devdiv workitem here:  https://devdiv.visualstudio.com/DevDiv/_workitems/edit/440099
