### ISSUE TITLE
SyntaxGenerator: support generating tuples

### ISSUE THREAD

**Issue by tmds** [dotnet/roslyn#19586]
I haven't found how to generate tuples using the SyntaxGenerator. Is this supported?

**Comment by Pilchie** [comment]
@CyrusNajmabadi is this possible already?

**Comment by CyrusNajmabadi** [comment]
A tuple type, or a tuple expression?  The former may be possible with SyntaxGenerator.TypeExpression.  The latter is likely not possible. 

PRs welcome.

**Comment by tmds** [comment]
@CyrusNajmabadi How can a tuple type be generated using TypeExpression?

**Comment by CyrusNajmabadi** [comment]
Probably can't be.  Feel free to submit a PR to make this possible.  If you do, please include VB as well.  Thanks!

in the meantime, you can just use SyntaxFactory.XXX instead.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/19748
