### ISSUE TITLE
Building during project load seems to wait until the entire project loads before building.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#19597]
A common pattern for me is to open VS, go to a project, right-click, and say "build".  Previously, this would start the build for that project immediately.  Now it waits for my entire project to load.  As loading projects now takes minutes, this slows me down enormously.

This is a regression from RTM.

**Comment by davkean** [comment]
Should you file this against project-system? By wait for the entire project to load, do you mean "wait for the entire solution to load?"

**Comment by CyrusNajmabadi** [comment]
> By wait for the entire project to load, do you mean "wait for the entire solution to load?"

Yes.  

> Should you file this against project-system?

Who owns building? Is it the project system?

**Comment by davkean** [comment]
Yes, we own it. I'll move it.

**Comment by davkean** [comment]
This issue was moved to dotnet/project-system#2210
