### ISSUE TITLE
Status of /features:deterministic=true

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/roslyn#196]
It seems to me that this feature is not finished yet.

Can someone confirm it's not finished?(maybe I'm using it wrong or I misunderstood what it means)
If it's not finished yet... Is there plan to finish it any time soon?

**Comment by gafter** [comment]
It will not be finished for VS2015. I will be working on it.

**Comment by DavidKarlas** [comment]
words can't express my feelings... :heart:
