### ISSUE TITLE
Clean up bound nodes modified for IOperation purpose

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#19603]
We have modified C# `BoundCall`,  `BoundObjectCreationExpression` and `BoundIndexerAccess` to provide necessary data for deriving argument operations. We should try to clean this up once moved to @heejaechang's operation factory model.

**Comment by jinujoseph** [comment]
we should also handle  BoundObjectInitializerMember

**Comment by jinujoseph** [comment]
old issue closing it , if still an issue pls reopen with current information
