### ISSUE TITLE
Insert platform type CallerArgumentExpressionAttribute

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#19605]
Please work with the BCL teams to proactively insert `CallerArgumentExpressionAttribute` into the appropriate libraries so that we can have the *[caller argument expression](https://github.com/dotnet/csharplang/issues/287)* feature light up as soon as we are able to implement it.

**Comment by jamesqo** [comment]
@gafter It seems like the BCL team wants the compiler team to finalize the feature proposal before the type is added. https://github.com/dotnet/corefx/issues/21809

**Comment by DarkChowder** [comment]
Can you check if this is still stuck? Right now the attribute is [documented](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callerargumentexpressionattribute?view=net-5.0), and it is in the [runtime](https://github.com/dotnet/corefx/pull/30469), but it doesn't do anything when you compile it, which is confusing.

**Comment by jcouv** [comment]
The attribute was added in .NET 6 (https://github.com/dotnet/runtime/issues/22596). The compiler feature was implemented in .NET 6 (C# 10) (https://github.com/dotnet/roslyn/issues/52745).
Closing this tracking issue
