### ISSUE TITLE
Suggestion: analyzer for catching parameter name changes in overrides

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#19600]
```C#
public class Base
{
    public virtual void M(int a) { }
}
public class Derived : Base
{
    public override void M(int b) { } // changing the name is technically allowed but not recommended
}
```

As we discussed today in LDM, the language allows it, but except for some rare cases (names which cannot be spoken in C#, from PE produced by other languages), users generally expect the names to match. 
Sounds like the job for an analyzer.

@CyrusNajmabadi FYI

**Comment by sharwell** [comment]
Related issues:

* DotNetAnalyzers/StyleCopAnalyzers#2015
* dotnet/roslyn-analyzers#911
* DotNetAnalyzers/StyleCopAnalyzers#1949

**tl;dr:** This was proposed (@sharwell) and implemented (@pdelvo) for StyleCop Analyzers, and then one of our other developers (@vweijsters) implemented the equivalent rule CA1725 for roslyn-analyzers and it's already merged.

**Comment by jcouv** [comment]
Thanks 👍
