### ISSUE TITLE
We should have a CodeStyle setting that recommends "is null" instead of "ReferenceEquals(..., null)"

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#19601]

**Comment by sharwell** [comment]
:question: Should it apply to `x == null` as well?

**Comment by CyrusNajmabadi** [comment]
Don't think so.  That seems nice and succint.

**Comment by sharwell** [comment]
Some people may prefer `x is null` over `x == null` since it's a teeny bit faster in the case where the static type of `x` provides a custom `operator ==`.

**Comment by CyrusNajmabadi** [comment]
But if you have a custom ```operator==``` we do not want to change your code.  Because that would be changing semantics :)     This would definitely be important for types that return 'true' for ```==null``` in their operator, but which would return false if you used ```is null```

**Comment by Joe4evr** [comment]
> And as a bonus it doesn't allow an accidental value type to slip by.

But it wouldn't work for nullable value types because `Nullable<T>` is itself a struct.

**Comment by sharwell** [comment]
@Joe4evr The `x is null` pattern does work for nullable value types. It only isn't allowed for non-nullable value types.

**Comment by CyrusNajmabadi** [comment]
This feature exists now.
