### ISSUE TITLE
Proposal: Select parameter in "Change signature" dialog based on cursor position.

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#19612]
I would propose to preselect parameter in "Change signature" dialog based on cursor position in text editor. This would allow to faster remove/reorder parameters.

**Comment by Pilchie** [comment]
That sounds like a nice little tweak.  Care to submit a PR for it?

**Comment by JosefPihrt** [comment]
I noticed that this feature has been implemented in VS2019 so I guess this issue can be closed now.
