### ISSUE TITLE
Refactoring "Move type to ..." breaks preprocessor directives

### ISSUE THREAD

**Issue by josefpihrt** [dotnet/roslyn#19613]
**Version Used**: Visual Studio 2017 15.2.0+26430.6

**Code to Reproduce**:
```csharp
public class Foo
{
    #region Region
    public class Bar // Move type to 'Bar.cs'
    {
    }
    #endregion
}
```
**Actual Behavior**:
```csharp
public partial class Foo
{
    #endregion
}
```

**Comment by sharwell** [comment]
:memo: We had to deal with this for StyleCop Analyzers, and believe we found a rather clever solution in the end.

**Comment by Pilchie** [comment]
This was fixed already for 15.3 (I think by https://github.com/dotnet/roslyn/pull/16300 - @CyrusNajmabadi does that look right), though it leaves the `#region` and removes it's indentation, which could be better.

**Comment by Pilchie** [comment]
@sharwell That's actually how this is implemented as well :)

**Comment by CyrusNajmabadi** [comment]
Yeah.  This was fixed.  But clearly the fix could use some work.  If anyone wants to fix up the formatting, that would be totally great.

**Comment by YVEF** [comment]
Hi, Actually, I can tackle the issue, but I need to know/confirm the strategy. to resolve it. I already, mentioned it here #57077 
Thanks.

**Comment by CyrusNajmabadi** [comment]
@YVEF I would not over complicate things. We can just detect some very common cases that go awry today and improve on them. :-)

**Comment by Rekkonnect** [comment]
This still applies (17.9.2) and also carries over `#endregion` directives that are not bound to any `#region` ones. Example:

We have this file:
```csharp
public class Foo
{
    #region Region1
    public class NotBar
    {
    }
    #endregion

    #region Region2
    public class Bar // Move type to 'Bar.cs'
    {
    }
    #endregion
}
```

After moving Foo.Bar to Bar.cs, we have (indentation is preserved as-is):
```csharp
// Foo.cs
public partial class Foo
{
    #region Region1
    public class NotBar
    {
    }

#endregion
#region Region2
    #endregion
}

// Bar.cs
```csharp
public partial class Foo
{
    #endregion

    #region Region2
    public class Bar // Move type to 'Bar.cs'
    {
    }
    #endregion
}
```
