### ISSUE TITLE
Generate Constructor code fix copies attributes, even those inaccessible in the derived class

### ISSUE THREAD

**Issue by analogrelay** [dotnet/roslyn#19611]
**Version Used**:
```
Microsoft Visual Studio Community 2017 Preview
Version 15.3 (26510.0-Preview) Preview
VisualStudio.15.Preview/15.3.0-Preview+26510.0
Microsoft .NET Framework
Version 4.7.02046
```

**Steps to Reproduce**:

1. Create a new C# project (any kind)
2. Add a new class
3. Insert the following code

```csharp
using System;

namespace TestApp.Data
{
    public class Base
    {
        public Base([Bar] string foo)
        {

        }

        [AttributeUsage(AttributeTargets.Parameter)]
        private class BarAttribute : Attribute
        {

        }
    }

    public class Derived : Base
    {

    }
}
```

4. Ctrl-. on the `Base` symbol in the line containing `public class Derived : Base`
5. Select `Generate constructor 'Dervied(foo)'.`

**Expected Behavior**: The constructor is generated successfully, without the `[Bar]` attribute and no errors are introduced

**Actual Behavior**: The `TestApp.Data.Base+BarAttribute` attribute is copied to the new constructor because it is defined on the base class constructor, resulting in a syntax error because it is inaccessible. See the below animation.

![generate-constructor-copies-attributes](https://cloud.githubusercontent.com/assets/7574/26185562/a0060842-3b40-11e7-9002-636125db5c97.gif)

This comes up when working with EntityFramework, as you commonly derive from `Microsoft.EntityFrameworkCore.DbContext` and add a constructor to pass through the `DbContextOptions` parameter. However, that [base class constructor has an internal attribute defined on it](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore/DbContext.cs#L85), which is used in static-analysis tools in the EF build.

I'm not sure if copying the attributes from the base class constructor is the correct behavior. In the case above, the attribute is only relevant to the developers of the assembly defining the base class (it's part of static analysis tools used in the development of EntityFramework), and having it injected into my code is unexpected. I do recognize though that there could be cases where the attributes **should** be copied, but I'm not sure what they are... not copying them actually seems clearer to me here. Or perhaps only copying attributes which are accessible from the derived type in question.

(On a side note, the attribute is copied with the `Attribute` suffix in the type name present, which is not common C# style)

**Comment by sharwell** [comment]
💭 Interesting. The biggest place where I've found copying attributes valuable is things like `[Nullable]` or `[NotNull]`. Accessibility does seem to be a reasonable limiting item for this functionality.

> On a side note, the attribute is copied with the Attribute suffix in the type name present, which is not common C# style

We've been treating cases like this as bugs and working to fix them (small things matter too 🙂). If you file a separate issue, it's likely this will get resolved in a shorter amount of time 👍

**Comment by Pilchie** [comment]
I believe we have the same issue with Implement interface/Abstract base class too.

**Comment by Pilchie** [comment]
Also, I think the presence of `Attribute` is because simplification fails because we fail to bind with no errors.  In other words, I'm not sure it's an issue for attributes that *are* accessible.

**Comment by anurse** [comment]
If we agree that suppressing attributes that aren't accessible in the derived class is sufficient, I think I'm willing to send a PR. I've spiked it out and it's not too deep in the system :).

**Comment by anurse** [comment]
My initial (tested manually but no automated tests) inexperienced attempt at fixing the problem: https://github.com/dotnet/roslyn/compare/master...anurse:anurse/19611-inaccessible-attribute-in-constructor-param

**Comment by Pilchie** [comment]
Looks reasonable to me - care toturn it into a PR and add a test?

**Comment by CyrusNajmabadi** [comment]
Note: we don't generally do this sort of filtering because it's not clear what your end intent is.  For example, you may be generating into a location where the type does not exist, or where the type is nto accessible.  But perhaps when that happens your preference will be to then reference the type in some way, or make it accessible enough in the destination location.  

I've done this myself many times.  I generate code into some layer where things are not accessible, but i end up refactoring the code because i do want the code i generated to be what i will be using.

**Comment by Pilchie** [comment]
@CyrusNajmabadi that's fair if the original type is from source, but if it's a metadata reference, I think it's safe to assume that the user doesn't have the ability to access it.

**Comment by CyrusNajmabadi** [comment]
Well, the example was from source :)

If this was metadata then i think i woudl be ok with the filtering.  Note (for @anurse) a VB type used from C# will appear as metadata by defualt (and vice versa).  But we have helpers to determine if the type is actually from source or not.  You can use SymbolFinder.FindSourceDefinitionAsync

**Comment by CyrusNajmabadi** [comment]
We would take a targeted community fix here.
