### ISSUE TITLE
Update LangVersion for Roslyn VB projects to 15.3 or 15.5

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#19610]
When I tried, the Ubuntu CI builds failed with: `error BC2014: the value '15.3' is invalid for option 'langversion' `
This suggests that the .NET Core build may not be using the package specified by `MicrosoftNetCompilersnetcoreVersion`.

FYI @agocke

**Comment by jasonmalinowski** [comment]
@jcouv Trying to understand this bug a bit, why is it only impacting VB and not C#? Why is this an infrastructure issue vs. the compiler package itself being perhaps busted for actual products?

**Comment by jcouv** [comment]
When I updated the .NET Core compiler package in Roslyn and updated the LangVersion to 15.3 in VB projects, I am no longer able to build Roslyn. This worked fined for updating LangVersion in C# projects.

Jared thinks we may be using the wrong compiler when building VB projects, but I have not been able to confirm yet. I will chat with Andy (who is back in office).

**Comment by jcouv** [comment]
From discussion with Andy, we think this likely will be fixed after switching to the new Core-compatible package that he's working on.

**Comment by agocke** [comment]
Looks like this was verified as fixed in #22812
