### ISSUE TITLE
Reflection - Lexical Ordering

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#19628]
Hi

I'd like to reopen this issue please:

https://github.com/dotnet/roslyn/issues/16733

It became closed I think over growing confusion as to whether this was a compiler or CLR issue.

Thx

**Comment by alrz** [comment]
It's not closed? and you literally opened an issue to open another issue? so meta.

**Comment by gafter** [comment]
Closing as dup of #16733
