### ISSUE TITLE
IOperation tree shape for empty string interpolation

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#19630]
See https://github.com/dotnet/roslyn/pull/19590#pullrequestreview-39039200

Test `InterpolatedStringExpression_Empty` generates an Interpolation String Expression Operation with no parts. It should probably have one part.

**Comment by jinujoseph** [comment]
**Design Team Decision**
It should have one part for empty string

**Comment by mavasani** [comment]
Resolving this as Won't Fix based on the justification from Chuck in this comment: https://github.com/dotnet/roslyn/pull/20928#discussion_r128045655.
