### ISSUE TITLE
Completion shows snippets after using

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#19639]
**Version Used**: 
ba0cefe70bad6c0094a148b033386773243323fa

**Steps to Reproduce**:

At the top of a C# file, type `using T = System.Threading.Tasks.Task;` to declare an alias

**Expected Behavior**:
I get that.

**Actual Behavior**:
snippets are in completion after `using `, and commit on space to `testc` 😦

**Comment by CyrusNajmabadi** [comment]
Not there currently:

![image](https://user-images.githubusercontent.com/4564579/198745727-199b700c-6800-48b8-8a53-0086bb03766a.png)
