### ISSUE TITLE
[Suggestion]Create a new assignment operator to have many assignments in one statement

### ISSUE THREAD

**Issue by MatthieuMEZIL** [dotnet/roslyn#19641]
Today, there are many pieces of code like this:
```
instance.P1 = ...; 
instance.P2 = ...;
instance.P3 = ...;
instance.Foo();
```

To avoid to repeat the instance. and to avoid to use many statements, we can create some fluent api methods.
e.g. 
```
public T SetP1<T>(this T instance, TheTypeOfP1 p1) where T : TheTypeDefiningP1
{
    instance.P1 = p1;
    return instance;
}
```

I think this would be nice to have an operator (.= for example) that allows us to use something like object initializer outside the constructor.
e.g.
```
instance.=
{
    P1 = p1,
    P2 = p2,
    P3 = p3
}.Foo()
```

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
