### ISSUE TITLE
Deterministic property in msbuild is ignored in loaded project options

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#19651]
**Version Used**:  See csproj file

**Steps to Reproduce**:

Ros.csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" Version="15.1.1012" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="15.1.1012" />
    <PackageReference Include="Microsoft.CodeAnalysis.Build.Tasks" Version="2.3.0-beta2-61709-08" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="2.3.0-beta2-61709-08" />
  </ItemGroup>

</Project>
```

Program.cs:
```
using Microsoft.CodeAnalysis.MSBuild;
using System;

class Program
{
    static void Main(string[] args)
    {
        var workspace = MSBuildWorkspace.Create();
        var project = workspace.OpenProjectAsync("Ros.csproj").Result;
        Console.WriteLine(project.CompilationOptions.Deterministic);        
    }
}
```

Create these two files, run `dotnet restore` then `dotnet run` (with nuget configured to include the Roslyn myget feed).

**Expected Behavior**:

Prints True

**Actual Behavior**:

Prints False

**Comment by Pilchie** [comment]
This is one of a few new properties (also publicsign), that don't flow through in `MSBuildWorkspace`.  I took a look at fixing it, but it's actually quite tricky (COMImport interfaces and type identity problems :-/)

**Comment by jskeet** [comment]
So I shouldn't worry that it's not actually having the desired effect on my normal build? (I've seen unexpectedly-changed files, but only in passing, so have never investigated further.) I don't need this for the work I'm doing within the Roslyn API, but I was somewhat worried that the impact might be greater...

**Comment by Pilchie** [comment]
No, it's fine in the actual build, and VS gets it right. It's just `MSBuildWorkspace` that has the bug - (the public-sign one can be more significant if it changes assembly identity and there are `InternalsVisibleTo`s in play :(

**Comment by jskeet** [comment]
Righto, thanks for the reassurance. I'll leave it to you to decide whether to leave this open, or whether to close it as you've already got it tracked somewhere else and this just becomes noise...

**Comment by Pilchie** [comment]
(Basically [`CSharpCompilerInputs`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/MSBuild/CSharp/CSharpProjectFileLoader.CSharpProjectFile.cs,daf35e419410fb82) needs to implement `ICscHostObject4` and `ICscHostObject5`, but can't from managed code, because the PIA type doesn't exist anywhere that can be shared...

**Comment by CyrusNajmabadi** [comment]
Clo9sing out due to lack of feedback on this issue.
