### ISSUE TITLE
Unable to build in Visual Studio 2013 (update documentation for compiler packages)

### ISSUE THREAD

**Issue by llewelynrex** [dotnet/roslyn#19659]
Version 2.1.0: 

I've already resolved the problem in itself. The Microsoft Build Tools 2015 are required for the build to succeed once the Microsoft.Net.Compilers NuGet package has been added to the project. I just didn't find any documentation on it anywhere on this repository. It would be nice to have this documented as a dependency somewhere (where it's easy to find).

Kind regards
Llewelyn

**Comment by Pilchie** [comment]
Our build instructions are on https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building%2C%20Debugging%2C%20and%20Testing%20on%20Windows.md.

In general, we no longer officially support building with anything less than Visual Studio 2017.

**Comment by Pilchie** [comment]
Ah, I misunderstood. This isn't for building *Roslyn*, it's for building other projects once the compiler package is installed.  Moving to compilers then.

**Comment by llewelynrex** [comment]
Yeah. That's right. Sorry I wrote it a little ambiguously!

**Comment by jcouv** [comment]
It seems possible to have documentation on a nuget package, and it gets displayed on the [nuget page](https://www.nuget.org/packages/Microsoft.Net.Compilers/) for each specific version.
I think this description comes from `src\NuGet\Microsoft.Net.Compilers.nuspec`.

**Comment by jcouv** [comment]
While we're in there, we should consider adding some versioning information in the package description:
- Versions 1.x mean C# 6.0 (Visual Studio 2015 and updates). For instance, 1.3.2 corresponds to the most recent update (update 3) of Visual Studio 2015.
- Version 2.0 means C# 7.0 (Visual Studio 2017 version 15.0).
- Version 2.1 is still C# 7.0, but with a couple fixes (Visual Studio 2017 version 15.1).
- Version 2.2 is still C# 7.0, but with a couple more fixes (Visual Studio 2017 version 15.2).
- Version 2.3 means C# 7.1 (Visual Studio 2017 version 15.3).

**Comment by jcouv** [comment]
I started a wiki page for collecting useful information about our NuGet packages:
https://github.com/dotnet/roslyn/wiki/NuGet-packages

**Comment by jcouv** [comment]
Added a link to documentation to the package description and added a note about build tools.
