### ISSUE TITLE
Need a proper representation for __arglist argument for IOperation

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#19673]
Take the following example,
```cs
        Console.Write("{0} {1} {2} {3} {4}", 1, 2, 3, 4, __arglist(5));
```
The __arglist is currently returned as:
```
    IArgument (ArgumentKind.Explicit, Matching Parameter: null) (OperationKind.Argument, IsInvalid) (Syntax: '__arglist(5)')
      IOperation:  (OperationKind.None) (Syntax: '__arglist(5)')
        Children(1): ILiteralExpression (Text: 5) (OperationKind.LiteralExpression, Type: System.Int32, Constant: 5) (Syntax: '5')
```

I believe this can be solved by simply adding `ArgumentKind.ArgList`, and create such an `IArgument` based on underlying `BoundArgListOperator`.

**Comment by genlu** [comment]
FYI @heejaechang @jinujoseph

**Comment by nguerrera** [comment]
#8394

**Comment by genlu** [comment]
Do we want to discuss this today? @jinujoseph

**Comment by jinujoseph** [comment]
sure , we should actually discuss #8394 in general

**Comment by CyrusNajmabadi** [comment]
We tink we should have:

```c#
    public interface IArgList : IOperation
    {
        List<IOperation> Values;
    }
```

If user uses __arglist(1, 2, 3), then they will have an IArgument with a VAlue that is this IArgList.  The IArgList will point at 1, 2, 3.  The Kind of the ArgumentKind of the IArgument will be a new value called ... ArgList

**Comment by mavasani** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/8394
