### ISSUE TITLE
editorconfig does not affect code generation if rules are set to "none"

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#19675]
**Version Used**: 15.3 Preview1

**Steps to Reproduce**:

_(Ensure you have global code style settings in VS for 'var' set to "use explicit type")_

1. Create a new Console App (.NET Framework) project
2. Right-click on the solution node and select Add->New Item...
3. In the "Add New Item" dialog, select "Text File" and type ".editorconfig" for the name.
4. In .editorconfig, add the following and save the file:
    ```
    [*.cs]
    csharp_style_var_for_built_in_types = true:suggestion
    ```
5. Close and re-open Program.cs to work around bug where editorconfig settings are not loaded unless file is closed and re-opened _(grumble)_.
6. In Program.cs, type `Console.WriteLine(args.Length);` as the body Main.
7. Select `args.Length` and press <kbd>Ctrl+.</kbd> to display the light bulb.
8. Select "Introduce local for 'args.Length'" from the light bulb and your code should look like this:
    ```
    var length = args.Length;
    Console.WriteLine(length);
    ```
9. Undo get back to `Console.WriteLine(args.Length);`
10. In .editorconfig, change "suggestion" to "none" and save.
11. Close and re-open Program.cs _(grumble again)_ and try to introduce a local for `args.Length` again. 

**Expected Behavior**:
```
var length = args.Length;
Console.WriteLine(length);
```

**Actual Behavior**:
```
int length = args.Length;
Console.WriteLine(length);
```

**Comment by sharwell** [comment]
`none` is not a valid value for these settings. It will fail to parse and fall back to the default value for the option, which is `false:silent`. If you meant to affect code generation but not have a suggestion, you need to have the true version of a valid setting, which would be `true:silent`.

**Comment by sharwell** [comment]
➡️ We need to make `none` and `silent` the same. Everyone is currently using `none` and doesn't realize it's not working as expected.

**Comment by DustinCampbell** [comment]
Why in the world does it work this way? How are users supposed to do the right thing? Here's with the EditorConfig Language Service shows:

![image](https://cloud.githubusercontent.com/assets/116161/26278754/f7bc15dc-3d56-11e7-9426-8a773cff6d02.png)

**Comment by sharwell** [comment]
@DustinCampbell `false:none` worked as expected, and the behavior of `true:silent` is so subtle no one noticed.

**Comment by DustinCampbell** [comment]
I'm not sure it's that subtle. The "var" rules are a perfect example of wanting to not bother users (e.g. none) but still wanting code generation to default to the right style for a code base (true).

Anyway, thanks for the clarification @sharwell. We really need to fast track some of these problems that are stumbling blocks for anybody using editorconfig with code style. The fact that I still have to close and reopen a files after changing options/editorconfig is pretty frustrating.

**Comment by DustinCampbell** [comment]
And of course, the fact that the EditorConfig Language Service squiggles "silent" as a warning does't put users in a pit of success.
