### ISSUE TITLE
Simpel code with bit shift doesn't compile anymore

### ISSUE THREAD

**Issue by kekekeks** [dotnet/roslyn#19680]
**Version Used**: VS2017 

**Steps to Reproduce**:
```csharp
var c = 10
for (int i = 0; i < c >> 1; ++i)
{
}
```
**Expected Behavior**: Code compiles like it did with previous versions

**Actual Behavior**:
> error CS0118: 'c' is a variable but is used like a type 
> error CS0307: The variable 'i' cannot be used with type arguments

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/16834

Tagging @gafter for confirmation.

**Comment by gafter** [comment]
Correct
