### ISSUE TITLE
Variables can't be accessed when debugging a local function

### ISSUE THREAD

**Issue by jltjohanlindqvist** [dotnet/roslyn#19692]
**Version Used**: 15.2 (26430.6)

**Steps to Reproduce**:

1.  Create a console app project
2. Add the following class: 
```
using System;
using System.Collections.Generic;

namespace ConsoleApp
{
    public class Test
    {
        private List<int> _ints = new List<int>();

        public Test()
        {
            _ints.Add(1);
            Method(2);
        }

        public void Method(object t)
        {
            localFunction();

            void localFunction()
            {
                // adding this line makes the variables disappear in debug mode
                Console.WriteLine(t);

                _ints.Add(2);
            }
        }
    }
}
```
3. Call the constructor of class `Test` in `Program.cs` main method.
4. Set a break point at the line `_ints.Add(2);`
5. Run the program in debug mode
6. Check either Locals or mouse over `_ints` to try to see contents of the list.

**Expected Behavior**:
Being able to see the contents of the list.

**Actual Behavior**:
Can't see any variables at all.

----

Removing the line where I access the variable `t` makes it possible to see the contents of the list. So I'm assuming it has something to do with trying to access the parameter of the method `Method`.

Going into the call stack and switching focus to the call to `localFunction();` makes it possible to access the list.

**Comment by jltjohanlindqvist** [comment]
[ConsoleApp.zip](https://github.com/dotnet/roslyn/files/1018139/ConsoleApp.zip)

Added project zip file.

**Comment by ivanbasov** [comment]
Tried to reproduce this with Visual Studio Version 15.3 (26430.0-Preview). Everything seems to work fine.
When I'm on the following line:
`    _ints.Add(2);`

I'm able to see the content of _ints both within the Locals window under 'this' and when hovering over it. @jltjohanlindqvist, could you please try with the latest Visual Studio?

**Comment by jltjohanlindqvist** [comment]
Just tested in both 15.2 and 15.3 with new installations and you're right. I can see the content of _ints using 15.3 but not when using 15.2.

**Comment by ivanbasov** [comment]
Great! Thank you very much for the confirmation!
