### ISSUE TITLE
Allow emitting portable PDBs for CSI on Windows

### ISSUE THREAD

**Issue by filipw** [dotnet/roslyn#19691]
**Version Used**: 

CSI from `master`

**Steps to Reproduce**:

1. On Windows, start the latest version `csi.exe` against a CSX script. That version of CSI emits PDBs (see https://github.com/dotnet/roslyn/pull/17379)
2. Attempt to attach the CLR debugger that ships with **C# extension for VS Code**

**Expected Behavior**:

Debugger attaches.

**Actual Behavior**:

Debugger does not attach. 
The root cause is that the CLR debugger that ships with C# extension for VS Code only supports portable PDBs, while in scripting we only have full PDBs on Windows https://github.com/dotnet/roslyn/blob/master/src/Scripting/Core/Utilities/PdbHelpers.cs#L10. This behavior doesn't affect attaching VS debugger, as that one obviously can consume full PDBs.

The current workaround is to use Mono for Windows to run `csi.exe`, as that would result in portable PDB format.

@tmat would it make sense to add an extra option to `csi.exe` arguments where we could pass the PDB format? This would facilitate attaching the CLR debugger that ships with C# extension for VS Code

**Comment by tmat** [comment]
I think we would want to use Portable PDB by default, except when the runtime doesn't support it. The runtime support is displaying line numbers and file names in stack traces (exception.ToStirng) -- see https://github.com/dotnet/corefx/issues/19788). Desktop FX 4.7.1 supports Portable PDBs in stack traces.

I guess we could provide an option to override this so that you can debug on pre-4.7.1

**Comment by ivanko2000** [comment]
I stumbled on this thread while looking for a way to debug CSX scripts in VS Code (where editing/IntelliSense/etc is already supported), and it appears this discussion is further along than anything else I could locate... Any progress on this by any chance?

**Comment by filipw** [comment]
@ivanko2000 you can use dotnet-script for CoreCLR CSX debugging in VS Code https://github.com/filipw/dotnet-script
For CSI/scriptcs debugging on Windows you can use https://github.com/Microsoft/vscode-mono-debug extension as it works with full PDB format

**Comment by ivanko2000** [comment]
Thank you @filipw - looks promising, I'll definitely give it a shot.

Still, the approach proposed in this issue report appears to be the most 'natural' option for full .NET on Windows. :)

**Comment by tmat** [comment]
I believe this is now resolved - we use Portable PDBs on Mono and Core CLR: http://source.roslyn.io/#Microsoft.CodeAnalysis.Scripting/Utilities/PdbHelpers.cs,10
