### ISSUE TITLE
Inconsistent Output: using derived class to access base class properties set in derived class constructor

### ISSUE THREAD

**Issue by atameet** [dotnet/roslyn#19698]
[coreclr#11771](https://github.com/dotnet/coreclr/issues/11771)

**Version Used**: 
dotnet --version
1.0.0-preview2-1-003177

**Steps to Reproduce**:

Hello,

I have the following test code. While, I know the _order_ of the initializations for static properties with/without static constructor(beforefieldinit) present and the calling of the static constructor timing is based on different things . In my understanding, at least when we access the (static)property then it is understood that the (static)constructor would have been called for sure. Please correct me if I am wrong or I am missing something completely obvious :)

```
using System;
namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var v1 = D1.val;
            Console.WriteLine("Hello World:" + v1 + ":");
            new D1();
            var v2 = D1.val;
            Console.WriteLine("Hello World:" + v2 + ":");
            Console.WriteLine(v1==v2);
            Console.Read();
        }
    }
    public class B{   
        //static B(){}
        public static string val{get;set;}
    }
    public class D1:B{
        static D1(){
            val="d1";
        }
    }
}
```

Thanks
**Expected Behavior**:
Output:
```
Hello World:d1:
Hello World:d1:
True
```

**Actual Behavior**:
Output:
```
Hello World::
Hello World:d1:
False
```

**Comment by jaredpar** [comment]
This behavior is "By Design". Even though in the code you used `D1.val` the actual executed code is `B.val`. Hence `D1` is not accessed and its static constructor is not run.
