### ISSUE TITLE
Support context-aware commenting behavior

### ISSUE THREAD

**Issue by RyanCavanaugh** [dotnet/roslyn#19702]
**Version Used**: master

**Steps to Reproduce**:

In a TypeScript .tsx file, execute the "Comment Code" action in this block:
```ts
const el = <div>
|( <- caret here) Hello, world! 
</div>;
```

**Expected Behavior**:
```ts
const el = <div>
<!-- Hello, world! -->
</div>;
```

**Actual Behavior**:
```ts
const el = <div>
// Hello, world! 
</div>;
```

We need https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/CommentSelection/ICommentUncommentService.cs (or something like it) to support providing a custom comment edit based on location, since we both need to detect that we're in a JSX element, and put content at the start and end of the line (rather than just the start, since there is no single-line comment sequence in JSX)

/cc @CyrusNajmabadi since we spoke about this

**Comment by CyrusNajmabadi** [comment]
Shouldn't be too hard to do.  We'll likely produce a new API that actually tells you where the user is.  And we'll likely make this async as well.

**Comment by Pilchie** [comment]
Tagging @DustinCampbell as well, so he's aware of the API request here.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/20459
