### ISSUE TITLE
`Go To Implementation` doesn't work correctly if there's an `abstract override` method

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#19700]
**Version Used**: VS2017 15.2

**Steps to Reproduce**:

Press `Ctrl+F12` (`Go To Implementation`) on `A.M()`, see comment in code:

```C#
using System;

namespace Example {
	class Program {
		static void Main(string[] args) {
		}
	}
	abstract class A {
		// Press Ctrl+F12 on M (Go To Implementation)
		public virtual void M() { }
	}
	abstract class B : A {
		public abstract override void M();
	}
	sealed class C1 : B {
		public override void M() { }
	}
	sealed class C2 : A {
		public override void M() => base.M();
	}
}
```

**Expected Behavior**:

It shows `A.M()`, `C1.M()` and `C2.M()` in the FAR toolwindow

**Actual Behavior**:

It shows `A.M()` and `C2.M()` in the FAR toolwindow. `C1.M()` is missing.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski Why would you do this :'(
