### ISSUE TITLE
Move type to file duplicates assembly level attributes

### ISSUE THREAD

**Issue by xt0rted** [dotnet/roslyn#19707]
**Version Used**: 15.2 (26430.6)

**Steps to Reproduce**:

1. Create a file with 2 classes in it
2. Add `[assembly: Microsoft.Owin.OwinStartup(typeof(Class1))]` to the top of the file
3. Run the `Move type to...` refactoring

**Expected Behavior**:
`Class2` should be moved to a new file and the assembly level attribute should remain in the file for `Class1`.

**Actual Behavior**:
The assembly level attribute is now duplicated between both files.

This was first reported with the VS Feedback tool until I realized the code was also on GitHub. https://developercommunity.visualstudio.com/content/problem/55251/move-class-to-file-refactoring-duplicates-assembly.html

**Comment by Pilchie** [comment]
@CyrusNajmabadi is this one of the cases you fixed for 15.3?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedbakc on this issue.
