### ISSUE TITLE
Jitting in InlineRenameSession.ApplyReplacements and InitializeOpenBuffers

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#19704]
Jitting during inline rename leads to a UI delay in http://watsonservice/watsoncab/uri?p=https://uswewatcab01.blob.core.windows.net/global-201705/1d3a9f9f-ad9f-4286-b76c-50b09a926a85.zip. Do we have optprof scenarios that cover inline rename?

cc @KevinH-MS

**Comment by Pilchie** [comment]
Do we really have close to 1second of jitting?

**Comment by KevinH-MS** [comment]
I don't *think* we have optprof scenarios for this, but 1 second does seem like a terrible lot.  To me, this screams "we're allocating too much leading up to this scenario".  Is the reason for the long delay in JIT possibly due to GCs or attempts to allocate new blocks of memory?

**Comment by genlu** [comment]
Closing old OptProf issues.
