### ISSUE TITLE
/refout and /debug together should be an error

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#19708]
But we have a test that asserts it is OK:

``` c#
            var outWriter = new StringWriter(CultureInfo.InvariantCulture);
            var csc = new MockCSharpCompiler(null, dir.Path,
                new[] { "/nologo", "/out:a.dll", "/refonly", "/debug", "/deterministic", "/doc:doc.xml", "a.cs" });
            int exitCode = csc.Run(outWriter);
            Assert.Equal("", outWriter.ToString());
            Assert.Equal(0, exitCode);
```

**Comment by gafter** [comment]
We might consider changing (or confirming, if it has already been changed) the spec to allow the combination.

**Comment by jcouv** [comment]
Confirmed the current behavior is documented. Let me know if ok to close.

> Also, the /refonly parameter silently disables outputting PDBs, as ref assemblies cannot be executed. 

https://github.com/dotnet/roslyn/blob/master/docs/features/refout.md

**Comment by sharwell** [comment]
I am in favor of the current behavior for two reasons:

1. Allowing mutually-exclusive options where possible makes it less likely that tooling which calls the compiler will fail unexpectedly. For example, the tool no longer needs to know about the relation between these two options and can pass through items as indicated by the user.
2. In a world where this specific pair of mutually-exclusive options is allowed, I believe the current behavior is what the user would expect: What kind of output? Reference assembly. Output available debug information? Yes. The fact that no debug information is available has little bearing on what we're expecting to see.

**Comment by jcouv** [comment]
In this case, Neal was not pushing back. Just needed to update the doc (which it is).

**Comment by jcouv** [comment]
Neal, please close if ok. Re-assign to me if not.

**Comment by sharwell** [comment]
> In this case, Neal was not pushing back.

This is how I interpreted the situation. 👍

**Comment by gafter** [comment]
ok, I'm fine with it.
