### ISSUE TITLE
Implement Interface adds uneeded members when implementing interface with new methods

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#19721]
With the following hierarchy:
```C#
interface ImmutableView
{
    int Prop1 { get; }
}
interface MutableView : ImmutableView
{
    new int Prop1 { get; set; }
}
class Implementation : MutableView {}
```
Using the "Implement Interface" quick action will implement both interfaces, `ImmutableView` explicitly, resulting the following generated code:
```C#
class Implementation : MutableView
{
    public int Prop1 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }

    int ImmutableView.Prop1 => throw new NotImplementedException();
}
```
"Implement Interface" should be smart enough here to know that it doesn't need to implement Prop1 twice, unless the "Implement Interface Explicitly" option is selected. 
I'm assuming that this @CyrusNajmabadi?

**Comment by CyrusNajmabadi** [comment]
We would take a PR for this.
