### ISSUE TITLE
OperationFactory/Operations.Generated.cs refactoring

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#19720]
We need to address the following suggestions when we implement the operation node generator:

1. https://github.com/dotnet/roslyn/pull/19636#pullrequestreview-39800375
2. https://github.com/dotnet/roslyn/pull/19636#discussion_r118044195
3. https://github.com/dotnet/roslyn/pull/19636#pullrequestreview-39801178
4. https://github.com/dotnet/roslyn/pull/19636#discussion_r118045725
5. https://github.com/dotnet/roslyn/pull/20177#discussion_r121588312
6. https://github.com/dotnet/roslyn/pull/20177#discussion_r121588474
7. https://github.com/dotnet/roslyn/pull/20177#discussion_r121589002

**Comment by mavasani** [comment]
There are some more comments on the PR, please look at them when working on this.

**Comment by jinujoseph** [comment]
closing this as this is tracked [here](https://github.com/dotnet/roslyn/issues/20204)
