### ISSUE TITLE
Build.cmd and Test.cmd don't handle space in path.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#19726]
**Version Used**: 
Commit: [4a78582](https://github.com/dotnet/roslyn/commit/4a785825c725cb1a41edbaf47de9018a3c7e5c89)
```
C:\Users\Adam Speight\Documents\Repos\ROSLYN>Build
Using existing NuGet.exe at version 4.1.0
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1008: Only one project can be specified.
Switch: Speight\Documents\Repos\ROSLYN\Roslyn.sln
```

**Steps to Reproduce**:

1. Requires a path contain a space.
2. Run `Build.cmd` or `Test.cmd`

**Expected Behavior**:
No Errors
**Actual Behavior**:
`MSBuild` thinks it is two projects, not one.

**Comment by AdamSpeight2008** [comment]
@Pilchie I think this can be solved by put the argument in quotes.

**Comment by AdamSpeight2008** [comment]
Fortunately I'm in the position to add another user (with space) to the system. Though this could be an untenable solution to others.

**Comment by jmarolf** [comment]
Looks like we just need to wrap the results of the `Join-Path` commands [here](https://github.com/dotnet/roslyn/blob/master/build/scripts/build.ps1#L35) and [here](https://github.com/dotnet/roslyn/blob/master/build/scripts/build.ps1#L42) in parenthesis

**Comment by AdamSpeight2008** [comment]
@jmarolf  ` $proj = Join-Path $($repoDir) "BuildAndTest.proj"` ?

**Comment by jmarolf** [comment]
@AdamSpeight2008 can you build successfully if you make that change locally?

**Comment by AdamSpeight2008** [comment]
When I do I get the following.
```
C:\Users\Adam Speight\Documents\Repos\ROSLYN>build
Using existing NuGet.exe at version 4.1.0
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1008: Only one project can be specified.
Switch: Speight\Documents\Repos\ROSLYN\Roslyn.sln

For switch syntax, type "MSBuild /help"
Command failed to execute: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin\msbuild.exe /v:m /m C:\Users\Adam Speight\Documents\Repos\ROSLYN\Roslyn.sln
```
Looks like we need quotation marks around it. *PowerShell is a mystery to me*

**Comment by AdamSpeight2008** [comment]
I'm trying the following and it seems to work.
```
    $target = if ($project -ne "") { $project } else { Join-Path $($repoDir) "Roslyn.sln" }
    $buildArgs = "$buildArgs ""$target"""
```
I'll look at the `Test` part after it finishing building.

**Comment by AdamSpeight2008** [comment]
@jmarolf 
`Test` isn't so easy. Currently using the following `build.ps1` [gist](https://gist.github.com/AdamSpeight2008/1a44935d8e20e1ad77677edcdb71e8ca)
[Output](https://gist.github.com/AdamSpeight2008/c5021e2d369febd39589afe834aaa85f)

**Comment by jmarolf** [comment]
@AdamSpeight2008 looks like we'll need some way to add quotes around the nuget cache path [here](https://github.com/dotnet/roslyn/blob/dc7e9b48bd78b9e92a3342247588ce04b1cc6859/build/Targets/Versions.props#L49)

**Comment by jmarolf** [comment]
@AdamSpeight2008 of place quotes around the call site [here](https://github.com/dotnet/roslyn/blob/03f53b4cc1f1a7a97829e6bc0d43eed4588cd32f/BuildAndTest.proj#L102)

**Comment by AdamSpeight2008** [comment]
@jmarolf We need some way of placing quotes around each of the arguments in `TestAssemblies`
```
    <PropertyGroup>
      <CoreRunExe>$(CoreClrTestDirectory)\CoreRun.exe</CoreRunExe>
      <CoreRunArgs>$(CoreClrTestDirectory)\xunit.console.netcore.exe @(CoreTestAssemblies, ' ') -parallel all -xml $(CoreClrTestDirectory)\xUnitResults\TestResults.xml</CoreRunArgs>
      <RunTestsExe>&quot;Binaries\$(Configuration)\Exes\RunTests\RunTests.exe&quot;</RunTestsExe>
      <RunTestsArgs>&quot;$(NuGetPackageRoot)\xunit.runner.console\$(xunitrunnerconsoleVersion)\tools&quot; $(RunTestArgs) @(TestAssemblies, ' ')</RunTestsArgs>
      <VsixExpInstallerExe>$(NuGetPackageRoot)\roslyntools.microsoft.vsixexpinstaller\$(RoslynToolsMicrosoftVSIXExpInstallerVersion)\tools\VsixExpInstaller.exe</VsixExpInstallerExe>
      <VsixExpInstallerArgs>-rootSuffix:RoslynDev -vsInstallDir:"$([System.IO.Path]::GetFullPath('$(MSBuildBinPath)\..\..\..'))"</VsixExpInstallerArgs>
    </PropertyGroup>

```

**Comment by AdamSpeight2008** [comment]
This works.
```     <RunTestsArgs>&quot;$(NuGetPackageRoot)\xunit.runner.console\$(xunitrunnerconsoleVersion)\tools&quot; $(RunTestArgs) @(TestAssemblies -> '&quot;%(Identity)&quot; ',' ')</RunTestsArgs>
```

I'll do a Pull Request later.

**Comment by AdamSpeight2008** [comment]
Another PR #17524
