### ISSUE TITLE
Nesting collection initializer inside dictionary initializer results in code that throws at runtime

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/roslyn#19739]
**Version Used**: VS 2017 Update 3 Preview 1

**Steps to Reproduce**:

Compile and run the following code:

```c#
using System.Collections.Generic;

class Program
{
    static void Main(string[] args)
    {
        var expectedItems = new Dictionary<string, List<string>>()
        {
            ["Compile"] = { "Class1.cs", "Class2.cs" },
        };
    }
}
```

**Expected Behavior**:
Program runs successfully (or fails to compile, if this is not valid syntax).

**Actual Behavior**:
A `KeyNotFoundException` is thrown.

**Comments**
The compiler is generating code equivalent to the following:

```c#
var expectedItems = new Dictionary<string, List<string>>();
expectedItems["Compile"].Add("Class1.cs");
expectedItems["Compile"].Add("Class2.cs");
```

The IL looks like this:

```
.method private hidebysig static void  Main(string[] args) cil managed
{
  .entrypoint
  // Code size       52 (0x34)
  .maxstack  3
  .locals init (class [mscorlib]System.Collections.Generic.Dictionary`2<string,class [mscorlib]System.Collections.Generic.List`1<string>> V_0)
  IL_0000:  nop
  IL_0001:  newobj     instance void class [mscorlib]System.Collections.Generic.Dictionary`2<string,class [mscorlib]System.Collections.Generic.List`1<string>>::.ctor()
  IL_0006:  dup
  IL_0007:  ldstr      "Compile"
  IL_000c:  callvirt   instance !1 class [mscorlib]System.Collections.Generic.Dictionary`2<string,class [mscorlib]System.Collections.Generic.List`1<string>>::get_Item(!0)
  IL_0011:  ldstr      "Class1.cs"
  IL_0016:  callvirt   instance void class [mscorlib]System.Collections.Generic.List`1<string>::Add(!0)
  IL_001b:  nop
  IL_001c:  dup
  IL_001d:  ldstr      "Compile"
  IL_0022:  callvirt   instance !1 class [mscorlib]System.Collections.Generic.Dictionary`2<string,class [mscorlib]System.Collections.Generic.List`1<string>>::get_Item(!0)
  IL_0027:  ldstr      "Class2.cs"
  IL_002c:  callvirt   instance void class [mscorlib]System.Collections.Generic.List`1<string>::Add(!0)
  IL_0031:  nop
  IL_0032:  stloc.0
  IL_0033:  ret
} // end of method Program::Main
```

Explicitly calling the `List` constructor fixes the issue, but is a lot more verbose:

```c#
var expectedItems = new Dictionary<string, List<string>>()
{
    ["Compile"] = new List<string>() { "Class1.cs", "Class2.cs" },
};
```

**Comment by CyrusNajmabadi** [comment]
This is by design:

> A member initializer that specifies a collection initializer after the equals sign is an initialization of an embedded collection. Instead of assigning a new collection to the target field, property or indexer, the elements given in the initializer are added to the collection referenced by the target. The target must be of a collection type that satisfies the requirements specified in §7.6.11.3.

You are referencing teh collection you get by accessing the indexer on the dictionary you just created.  But you didn't put anything into the dictionary, so you're getting a KeyNotFound exception.

**Comment by SolderedMushroom** [comment]
@CyrusNajmabadi I want to hop over to csharplang and file an issue against that nonsense, but I know it would be a breaking change. Why on Earth do we have "Y *equals* Z" syntax which *adds* Z's contents to Y?

**Comment by SolderedMushroom** [comment]
Also, in what scenarios is that syntax actually useful? In order to be inside a collection initializer, and have a key already exist so you can add to it, all I can think of is this:

```csharp
var expectedItems = new Dictionary<string, List<string>>()
{
    ["Compile"] = new List<string>() { "Class1.cs", "Class2.cs" },
    ["Compile"] = { "Class3.cs" }
};
```

Which is absurd.

**Comment by CyrusNajmabadi** [comment]
It's useful for lots of types which expose collections that are already instantiated. For example WPF
