### ISSUE TITLE
Cannot delete .vs directory after closing solution

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#19768]
**Version Used**: 15.3 preview 1 with 732a69f10ea9a9a55414da3f4e4f2d23646230b7 installed in experimental instance

**Steps to Reproduce**:

1. Create a .NET Class Library project
2. Close the solution
3. Attempt to delete the **.vs** directory

**Expected Behavior**:

The **.vs** directory is deleted.

**Actual Behavior**:

The **.vs** directory cannot be deleted, because the file **.vs/[SolutionName]/v15/sqlite3** is locked.

**Notes**:

This behavior is a regression against 15.2, introduced after 15.3 Preview 1.

**Comment by Pilchie** [comment]
@sharwell do you know what's it's locked by?  I presume the OOP process?  @heejaechang could this be because OOP isn't closed yet?

**Comment by heejaechang** [comment]
could be. db might not released lock yet.

**Comment by CyrusNajmabadi** [comment]
That's exactly what is it.  I see handles open to the DB on both the OOP side *and* on the VS side.  I'm trying to figure out the latter first.  We should be releasing the DB fully, so i need to see what handle is being kept open over there.

**Comment by CyrusNajmabadi** [comment]
actually, i may have misspoke.  It looks like it's all just handles held by hte OOP side.  I need to fix things up over there to release stuff.
