### ISSUE TITLE
Compilation failure for inner function + value tuple + ternary operator case

### ISSUE THREAD

**Issue by myblindy** [dotnet/roslyn#19781]
**Version Used**: 

NuGet package `Microsoft.Net.Compilers` version 2.1.0, latest at the time of writing. Also fails with the base VS2017 compiler.

**Code to Reproduce**:

```
        static void Main(string[] args)
        {
            void GetValName(string text)
            {
                int? idx = null;
                var v = (0, idx.HasValue? text + "" : "");
            }
        }
```

**Behavior**:

Something about this statement confuses both the compiler and the VS IDE itself. If you try formatting it, it seems to think the `?` acts as a sort of function close statement, and arranges the braces accordingly.

Similarly, the compiler outputs this:
```
1>Program.cs(16,48,16,49): error CS1026: ) expected
1>Program.cs(16,66,16,67): error CS1002: ; expected
1>Program.cs(16,66,16,67): error CS1513: } expected
1>Program.cs(16,72,16,73): error CS1002: ; expected
1>Program.cs(16,72,16,73): error CS1513: } expected
1>Program.cs(20,1,20,2): error CS1022: Type or namespace definition, or end-of-file expected
```

Note that enclosing the true branch in parenthesis fixes all problems. I'm using this workaround for now, but the code as posted is obviously valid C# code and is rejected by the compiler.

**Comment by gafter** [comment]
This bug is fixed in the pending VS2017 Update 3.
