### ISSUE TITLE
Interpolated string in attribute is not colorized properly and GoToDefinition doesn't work

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#19780]
I expect "GetDebuggerDisplay()" to be colored differently, and `GoToDefinition` on that method should take me to that method.

![image](https://cloud.githubusercontent.com/assets/12466233/26461609/9962479c-4132-11e7-81f1-6be28d4efcd3.png)

In contrast, "GetDebuggerDisplay()" is colored properly in an interpolated string local (although the "nq" causes errors):
![image](https://cloud.githubusercontent.com/assets/12466233/26461745/11a2c416-4133-11e7-9e6b-23c81217b7a7.png)

**Comment by Pilchie** [comment]
`nq` causes errors because it's not a valid `string.Format` specifier.  The debugger has it's own language of course :)

**Comment by CyrusNajmabadi** [comment]
Not planning any support here.
