### ISSUE TITLE
Tuple name refactoring doesn't work with switch statements with patterns

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#19794]
Given the following code:
```C#
public class Class1 {
    public void Test() 
    {
        (int x, int y) t = (1, 2);
        switch (t.Item1)
            case var x where x > 0:
                break;
        }
    }
}
```

We should be offering a refactoring to rename `Item1` to `x`. However, an IOperation bug probably means that with pattern matching, we're not returning an `ISwitchStatement` for the switch in this case. FYI @CyrusNajmabadi. Whoever takes https://github.com/dotnet/roslyn/issues/17600 should investigate this as well.

**Comment by jinujoseph** [comment]
we just need to add test to confirm this along with #17600

**Comment by mavasani** [comment]
We already have bunch of tests around this: http://source.roslyn.io/#Roslyn.Compilers.CSharp.Semantic.UnitTests/IOperation/IOperationTests_IPatternSwitchCase.cs,0524c8a574e2bf95
