### ISSUE TITLE
Change default for "Place 'System' first when sorting usings" to true?

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#19797]
Can we look at telemetry, and see if it makes sense to change the default value of this to true?

**Comment by AArnott** [comment]
I wonder if telemetry is the best source, given we've already stacked the deck against this change by changing the default.
Rather, what if we crawled github to get data around which sort is actually used for the majority of code people work with?

**Comment by sharwell** [comment]
@Pilchie this would be a good candidate for moving to a "when in Rome" default, falling back to the current default.

**Comment by Pilchie** [comment]
@kuhlenh can you take a look at what makes sense here?

**Comment by alrz** [comment]
VS doesn't sync settings like this? In that case I think the default value is less of an issue.

**Comment by CyrusNajmabadi** [comment]
This is defaulted to true:

![image](https://github.com/dotnet/roslyn/assets/4564579/eec8ed2f-fdeb-408d-b662-70df760643aa)
