### ISSUE TITLE
Should referencing [IsReadOnly] signatures without an [InAttribute] modreq be allowed?

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#19792]
If a reference exists that has a virtual method with a ref-readonly parameter and [IsReadOnly] attribute, but no [IsConst] required modifier: Per feature design this is not possible, but it can be created by external tools/compilers. Should it be imported and used in the compilation? or should we mark it as a bad symbol and generate a use site error for it?

This issue should track design decisions taken around this issue, and how to fix it.
Issue was raised in #19658, where the PR for now allows it and added tests to verify the behavior.

cc @AlekseyTs @VSadov

**Comment by jcouv** [comment]
From LDM today, this is a design decision for the compiler to make.

**Comment by jcouv** [comment]
From discussion with Omar and Vlad, we'll load metadata strictly: require modreq in metadata, where the compiler would emit it.

**Comment by OmarTawfik** [comment]
@jcouv are we ok with having this in `15.later`? should it be done in `15.5`?

**Comment by jcouv** [comment]
Same for this one. From our discussion, let's keep this in 15.later for now, and go through un-assigned 15.5 ref readonly issues first.

**Comment by OmarTawfik** [comment]
FYI @jcouv moved to `15.later` as you mentioned above.
