### ISSUE TITLE
Add usings should check for both sorts

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#19796]
Currently in Add Using, we check if the usings are already sorted, and if so, insert in sorted order.

However, in the check if the usings are sorted, we base that on the value of the "Place 'System' namespaces first" option.  However, instead of just giving up if they aren't sorted according to the option, we should try again with the option the other way, so that add using works better even if the option is wrong.

**Comment by Pilchie** [comment]
@CyrusNajmabadi what do you think?

**Comment by CyrusNajmabadi** [comment]
Makes total sense to me.  I'm also makign this up-for-grabs in case anyone else wants to take it.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/20469
