### ISSUE TITLE
[Scripting] Disable suport for csx compilation in csc for RTM, make scripting specific API internal

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#1979]

**Comment by ManishJayaswal** [comment]
@cston @tmat @mattwar Matt mentioned that he has already made everything he could find internal but we should do another review. We still need to disable support for compiling csx files though.

**Comment by BobStrogg** [comment]
I've been using SourceCodeKind.Interactive to parse simple expressions into an AST (later visiting them & building a System.Linq.Expressions AST)...  Since RC3 it won't let me do that (throws NotSupportedException for Interactive); is there an alternative?

**Comment by cston** [comment]
Would SyntaxFactory.ParseExpression() work as an alternative?

**Comment by BobStrogg** [comment]
It works beautifully, thank you so much.  This'll teach me to RTFM :)
