### ISSUE TITLE
Inconsistent names EnumKeyword and DelegateKeyword

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#198]
Consider the following properties:

* `ClassDeclarationSyntax.Keyword`
* `InterfaceDeclarationSyntax.Keyword`
* `StructDeclarationSyntax.Keyword`
* `EnumDeclarationSyntax.EnumKeyword`
* `DelegateDeclarationSyntax.DelegateKeyword`

I believe that one of the following should occur for consistency:

1. Rename `EnumKeyword` &rarr; `Keyword`, and rename `DelegateKeyword` &rarr; `Keyword`
2. Rename `Keyword` &rarr; `ClassKeyword`, `InterfaceKeyword`, and `StructKeyword` as appropriate

Considering the fact that the first three are actually implementing an abstract property defined in `TypeDeclarationSyntax`, it would be easier to use `Keyword` as the name of the property for all of the above cases. I also believe it would be easier for users overall if this were the case.

**Comment by gafter** [comment]
These are all named "Keyword" because they override the "Keyword" property of TypeDeclarationSyntax. In that case we cannot give them different names. Unless we are doing that, we prefer to name the property by the keyword it contains.

**Comment by theoy** [comment]
Interesting that HuBoard removes the "Done" label when archiving. Need to try out this workflow some more :smile:
