### ISSUE TITLE
Consider combining "Value" and "Frozen" flags for the generated attributes

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#19809]
It may be more robust to use some kind of  struct that wraps a byte and has all the required states and transitions between them.
But we need to agree on what transitions are valid - I.E.: is it ok to go from true to false when not frozen? What if anyone has already seen the value?

This is related to the emerging pattern of using two bool variables like the following:

```C#
        private bool _needsGeneratedIsReadOnlyAttribute_Value;
        private bool _needsGeneratedIsByRefLikeAttribute_Value;

        private bool _needsGeneratedIsReadOnlyAttribute_IsFrozen;
        private bool _needsGeneratedIsByRefLikeAttribute_IsFrozen;
```

The _IsFrozen part is used in Debug.Assert to validate that when _Value transitions in certain ways the corresponding _Frozen is not set.  
It seems somewhat fragile (who is checking the Frozen itself is Frozen and not reset back?). It also seems to invite 2x as many fields than needed.

**Comment by gafter** [comment]
I have no idea what this is about.

**Comment by VSadov** [comment]
@gafter  Added more info.

**Comment by cston** [comment]
The multiple pairs of fields have been replaced by a single pair of fields and helper methods to limit access to those fields:
```C#
        private int _needsGeneratedAttributes;
        private bool _needsGeneratedAttributes_IsFrozen;

        internal EmbeddableAttributes GetNeedsGeneratedAttributes()
        {
            _needsGeneratedAttributes_IsFrozen = true;
            return (EmbeddableAttributes)_needsGeneratedAttributes;
        }

        private void SetNeedsGeneratedAttributes(EmbeddableAttributes attributes)
        {
            Debug.Assert(!_needsGeneratedAttributes_IsFrozen);
            ThreadSafeFlagOperations.Set(ref _needsGeneratedAttributes, (int)attributes);
        }
```

**Comment by cston** [comment]
Closing. Please reactivate if there's more that should be considered here.
