### ISSUE TITLE
Should we require "ref" and "readonly" modifiers to match on partial struct parts?

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#19808]
The precedent with "static", "sealed", "abstract" etc   shows that we allow flags that enable something via their presence to be present only on one or any of the parts. - We basically just compute the union of these bits.

There must be a reason for such behavior, but I am not sure if it applies to "ref" and "readonly". 
We need to decide whether these also have optional behavior or must match

**Comment by jcouv** [comment]
LDM answered "no".
@VSadov @OmarTawfik I'll close this issue, as this is the behavior that is implemented.

There is also a follow-up to allow modifiers in any order (https://github.com/dotnet/roslyn/issues/22322).
