### ISSUE TITLE
Manage NuGet Packages fails...

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#19813]
**Version Used**: 

15.3 (dogfood)

**Steps to Reproduce**:

1. Create new Windows Classic Desktop -> Console App (.NET Framework) 
2. Solution Explorer -> References -> Manage NuGet Packages...

**Expected Behavior**:

Dialog box pops up for managing NuGet packages

**Actual Behavior**:

![image](https://cloud.githubusercontent.com/assets/3804346/26512197/5b303c3e-421a-11e7-94af-00e06d00fb1e.png)

**Note**:

This makes it very difficult to use tuples, which require adding a nuget package.

**Comment by Pilchie** [comment]
Please file on https://github.com/nuget/home.
