### ISSUE TITLE
CSharpEncapsulateField.EncapsulateThroughCommand integration test failure

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#19816]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/4673/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpEncapsulateField/EncapsulateThroughCommand/

```
MESSAGE:
Assert.Contains() Failure\r\nNot found: public static int? Param { get => param; set => param = value; }\r\nIn value: \r\nnamespace myNamespace\r\n{\r\n class Program\r\n {\r\n private static int? param = 0;\r\n static void Main(string[] args)\r\n {\r\n param = 80;\r\n }\r\n }\r\n}
+++++++++++++++++++
STACK TRACE:
at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.Editor_OutOfProc.Verifier.TextContains(String expectedText, Boolean assertCaretPosition) at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpEncapsulateField.EncapsulateThroughCommand() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpEncapsulateField.cs:line 47
```

**Comment by MattGertz** [comment]
Mondo escrow triage:  test-only, moving out to get this off the radar.

**Comment by dpoeschl** [comment]
@rchande Another instance in https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/6192/

**Comment by dpoeschl** [comment]
Still failing. https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_vs-integration_prtest/6485/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpEncapsulateField/EncapsulateThroughCommand/

**Comment by dpoeschl** [comment]
Again: https://ci.dot.net/job/dotnet_roslyn/job/dev15.3.x/job/windows_release_vs-integration_prtest/73/

**Comment by sharwell** [comment]
@dotnet/roslyn-infrastructure The two `EncapsulateThroughCommand` tests are flaky, and my belief for the reason is the keystroke we send isn't getting registered due to a focus or timing problem. Here is the latest failure:
https://ci.dot.net/job/dotnet_roslyn/job/dev15.7.x/job/windows_debug_vs-integration_prtest/200
