### ISSUE TITLE
Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Classification.SyntacticTaggerTests.TestTagsChangedForEntireFile is hanging

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#19822]
It seems the root of some of the recent hangs is Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Classification.SyntacticTaggerTests.TestTagsChangedForEntireFile. From a dump file we see it's waiting on [this line](https://github.com/dotnet/roslyn/blob/8637503c0ef73033450e384802ea486efae6fcda/src/EditorFeatures/CSharpTest/Classification/SyntacticTaggerTests.cs#L52) which means the initial tags changed never got through. If I look at the tag computer, it seems it did tell the notification service to queue something, but the StaTaskScheduler is not doing work.

Looking for exceptions, there is this exception in the heap:

```Exception type:   Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException
Message:          should be on latest snapshot

InnerException:   <none>
StackTrace (generated):
    SP       IP       Function
    1938E524 1A66B269 Roslyn_Test_Utilities_Desktop!Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(System.String, System.String)+0x69
    1938E548 1A66B1ED System!System.Diagnostics.TraceListener.Fail(System.String)+0xd
    1938E550 1A6665A5 System!System.Diagnostics.TraceInternal.Fail(System.String)+0xad
    1938E590 09AC8BB8 System!System.Diagnostics.Debug.Assert(Boolean, System.String)+0x10
    1938E594 1A1DE5BA Microsoft_CodeAnalysis_EditorFeatures!Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService+<ProcessAsync>d__12.MoveNext()+0x39a
```
Which is coming from:

    src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs:330:                    Contract.Assert(snapshot.Version.Next == null, "should be on latest snapshot");

**Comment by CyrusNajmabadi** [comment]
It this happening at all in 15.3?  or only in 15.6?   I just tweaked tagging in 15.6 so it's possible i regressed something.  But if this is occurring in 15.3 then it would not be my change.

**Comment by CyrusNajmabadi** [comment]
That exeption is also terrifying.

**Comment by CyrusNajmabadi** [comment]
That exceptoin is also interesting in that it's for a component that is not being tested in the test that hangs.   i.e. the test is TestTagsChangedForEntireFile which is really testing SyntacticClassificationTaggerProvider.TagComputer.  But the assert  is in "AbstractAsynchronousTaggerProvider". But SyntacticClasificationTaggerProvider is a very specialized tagger provider.  it does nto have any relation to AbstractAsynchronousTaggerProvider.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi This was on 15.3. And yes, it's terrifying.

**Comment by MattGertz** [comment]
Mondo escrow triage:  not enough info yet, but I agree that it's something we'd want to consider for Escrow depending on what we find.

**Comment by Pilchie** [comment]
@jasonmalinowski what are your thoughts on whether this is likely a test issue or a product issue?

**Comment by jasonmalinowski** [comment]
@Pilchie I suspect test issue. If it was a product issue that met our current bar, it's probably something we're seeing in other telemetry/feedback streams.

**Comment by CyrusNajmabadi** [comment]
I can't find any skipped tests here.
