### ISSUE TITLE
Deconstruct type parameters cannot be inferred from explicit types in deconstruction

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#19825]
**Version Used**: 7.1

**Steps to Reproduce**:
```cs
class X 
{
  void Deconstruct<T, U>(out T t, out U u) => (t, u) = this; 
  void M() { (int i, object j) = this; }
}
```
**Expected Behavior**: Should call `X.Deconstruct<T, U>` and `X.Deconstruct<int, object>` respectively.

**Actual Behavior**: `The type arguments for method 'X.Deconstruct<T, U>(out T, out U)' cannot be inferred from the usage. Try specifying the type arguments explicitly.`

**Comment by jcouv** [comment]
If this worked, wouldn't it create a circularity problem in this example?

Anyways, the [feature spec](https://github.com/dotnet/roslyn/blob/master/docs/features/deconstruction.md#resolution-of-the-deconstruct-method) explains how the `Deconstruct` method is invoked:

> The resolution is equivalent to typing `rhs.Deconstruct(out var x1, out var x2, ...);` with the appropriate number of parameters to deconstruct into.
[...]

FYI @gafter @VSadov in case I'm missing something.

**Comment by alrz** [comment]
@jcouv 

>wouldn't it create a circularity problem in this example?

Yes, the example is not meant to "run", but I think it should compile.

>The resolution is equivalent to typing rhs.Deconstruct(out var x1, out var x2, ...); with the appropriate number of parameters to deconstruct into.

I'm proposing to add explicit types to that invocation:
```
this.Deconstruct(out T t, out U u);
this.Deconstruct(out int i, out object j);
```

**Comment by jcouv** [comment]
I see. Thanks for the clarification.
Could you provide some motivating examples where this is useful? If you do, maybe let's start a new discussion on csharplang repo instead, as this is not a bug in implementation.

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/issues/18682
