### ISSUE TITLE
SymbolFinder methods FindOverridesAsync and FindImplementationsAsync are much slower than they were in 2.0.0-beta1

### ISSUE THREAD

**Issue by maca88** [dotnet/roslyn#19827]
**Version Used**: `2.1.0` and `2.0.0-beta1`

The performance of `FindOverridesAsync` and `FindImplementationsAsync` methods dropped with the version `2.0.0-beta3`, all higher versions have similar performance.

**Steps to Reproduce**:

In order to reproduce the issue I've created two branches for each version on my repository where I encountered the problem:

[Fixture](https://github.com/maca88/AsyncGenerator/blob/performance/roslyn-2.1.0/Source/AsyncGenerator.Tests/ExternalProjects/NHibernate/Fixture.cs#L27) for version `2.1.0`
[Fixture](https://github.com/maca88/AsyncGenerator/blob/performance/roslyn-2.0.0-beta1/Source/AsyncGenerator.Tests/ExternalProjects/NHibernate/Fixture.cs#L27) for version `2.0.0-beta1`

**Expected Behavior**:
The performance of both methods should be similar in both versions.

**Actual Behavior**:
Performance of `FindOverridesAsync`:
- Version `2.1.0`:
![findoverrides-2_1_0](https://cloud.githubusercontent.com/assets/5311349/26523904/62a8a6a4-4323-11e7-8f79-914287acd88a.png)
- Version `2.0.0-beta1`:
![findoverrides-2_0_0-beta1](https://cloud.githubusercontent.com/assets/5311349/26523918/ce154d3e-4323-11e7-833f-2564bbb6f875.png)

Performance of `FindImplementationsAsync`:
- Version `2.1.0`:
![findimpl-2_1_0](https://cloud.githubusercontent.com/assets/5311349/26523911/94e91004-4323-11e7-82ac-977b6b31a799.png)
- Version `2.0.0-beta1`:
![findimpl-2_0_0-beta1](https://cloud.githubusercontent.com/assets/5311349/26523925/18f455f2-4324-11e7-8445-c4b7c11aa847.png)

**Comment by CyrusNajmabadi** [comment]
I'm looking at your fixture, but i can't see the calls to FindOverridesAsync  or   FindImplementationsAsync .  Can you clarify how i can test your scenario out?

**Comment by maca88** [comment]
I've simplifed the fixtures in order to have everything in one method.
When I ran the fixtures on my computer (Intel i7 860) I got the following results:

- Version `2.0.0-beta1`
```
Start calling sequentially FindImplementationsAsync for 1929 interface methods
Total elapsed time 2026ms
Start calling concurrently FindImplementationsAsync for 1929 interface methods
Total elapsed time 834ms
Start calling sequentially FindOverridesAsync for 1034 abstract/virtual methods
Total elapsed time 586ms
Start calling concurrently FindOverridesAsync for 1034 abstract/virtual methods
Total elapsed time 259ms
```

- Version `2.1.0`
```
Start calling sequentially FindImplementationsAsync for 1929 interface methods
Total elapsed time 55520ms
Start calling concurrently FindImplementationsAsync for 1929 interface methods
Total elapsed time 52819ms
Start calling sequentially FindOverridesAsync for 1034 abstract/virtual methods
Total elapsed time 23781ms
Start calling concurrently FindOverridesAsync for 1034 abstract/virtual methods
Total elapsed time 23706ms
```

**Comment by CyrusNajmabadi** [comment]
Can you clarify this step: Fetch the NHibernate Submodule

**Comment by maca88** [comment]
> Fetch the NHibernate Submodule

In this step the NHibernate git submodule should be initialized and updated by running the following commands:
```
git submodule init 
git submodule update
```

**Comment by CyrusNajmabadi** [comment]
> Run "Source/ShowBuildMenu.bat" script with the option "A" to generate the SharedAssembly.cs

Do you mean the ShowBuildMenu.bat that is in "Source\AsyncGenerator.Tests\ExternalProjects\NHibernate\Source"  ?

**Comment by maca88** [comment]
Yes.

**Comment by CyrusNajmabadi** [comment]
Ok.  I got things running.  Investigating now.
