### ISSUE TITLE
C# Async/Await optimization cause NRE on local variables access (maybe try/finally related)

### ISSUE THREAD

**Issue by deniszykov** [dotnet/roslyn#19831]
Version Used: Roslyn shipped with VS2015, VS2017

Steps to Reproduce:
1.  Create console application project
2.  Use following code https://gist.github.com/deniszykov/9a9dcd4f6fb5ea7905b8a15e5bc7d0c0
3.  Run in debug mode and see 10000 in output
4.  Run in release mode (make sure optimization flag is on) and get NullReferenceException.

Expected Behavior:
Same behavior as in non-optimized code.

Actual Behavior:
NRE when accessing local variable in optimized code.

**Comment by VSadov** [comment]
there is a bug. 
readStream is not captured in /o+ , bu tit should since its value lives across awaits. 
Possibly an issue with the data flow analysis.

**Comment by VSadov** [comment]
simpler repro:

```C#
    public class Program
    {
        static void Main(string[] args)
        {
            Test().Wait();
        }

        public static async Task Test()
        {
            // declaring variable before try/finally and nulling it in finally cause NRE in try's body
            var obj = new Object();

            try
            {
                for(int i = 0; i < 3; i++)
                {
                    // NRE on second iteration
                    obj.ToString();
                    await Task.Yield();
                }
            }
            finally
            {
                obj = null;
            }
        }
    }
```

crashes with NRE in /o+

Seems like a bug in async capture analysis.   `obj` must be captured here and it is not.

**Comment by VSadov** [comment]
Even simpler repro without async. Clearly a hole in definite assignment analysis.

```C#
    public class Program
    {
        static void Main(string[] args)
        {
            Test();
        }

        public static void Test()
        {
            object obj; 

            try
            {
                goto l3;

                l1:
                goto l2;

                l3:
                goto l1;


                l2:

                // Should be compile error
                // 'obj' is uninitialized
                obj.ToString();
            }
            finally
            {
                obj = 1;
            }
        }
    }
```
