### ISSUE TITLE
MethodBase.GetCurrentMethod().DeclaringType returns wrong type when used in Lambda

### ISSUE THREAD

**Issue by jabbera** [dotnet/roslyn#1983]
The following code returns ConsoleApplication6.Program in VS 2013 and ConsoleApplication6.Program+<>c__DisplayClass0 in VS 2015 CTP 

```
    class Program
	{
		static Lazy<string> typeName = new Lazy<string>(() => MethodBase.GetCurrentMethod().DeclaringType.FullName);
		static void Main(string[] args)
		{
			Console.WriteLine(typeName.Value);
		}
	}
```

**Comment by gafter** [comment]
Anonymous methods such as a lambda do not have a declaring type according to the C# language specification. The fact that there is a declaring type when viewed through reflection is an artifact of the translation process ; any value it returns is 'wrong' from a language point of view.

**Comment by gafter** [comment]
@AnthonyDGreen @DustinCampbell @ljw1004 @MadsTorgersen @gafter @srivatsn @theoy Paging the compat council to consider the proposed outcome. Please speak up if you'd like to consider this be changed.

**Comment by jabbera** [comment]
I've only found a small handful of places in our code where this happens. Most of the time it's around logging, and it's fairly trivial to resolve by just moving the lambda into a method. I'd suggest a compiler warning if this change sticks. It's a very subtle change in behavior that could really screw with someone who is using it for anything more complicated then logging.

**Comment by AnthonyDGreen** [comment]
Presumably this is an artifact of the optimization we made around codegening these as instance methods on a singleton? Given that the exact declaring type of the method could change depending on whether you captured local state anyway it wasn't entirely reliable to begin with. The risk seems small enough to compared to the performance benefit that I'm willing to risk this break.

**Comment by tmat** [comment]
@jabbera When using reflection on compiler generated members all bets are off.

**Comment by jabbera** [comment]
@tmat I'm not disagreeing and in retrospect it's a totally bizarre thing to do. However it's a change in behavior since .net 2.0 as far as I can tell.

**Comment by tmat** [comment]
@jabbera Sure, it is a change. A guarantee that it will stay the same forever was never given though.

**Comment by jabbera** [comment]
@tmat, agreed. Although since it is a change in a longstanding behavior a compiler warning, if possible, would be nice.

**Comment by tmat** [comment]
@jabbera Agree that a diagnostic would be useful - perhaps not in the compiler but an FxCop style warning. Static analysis can only identify some of the issues though. Perhaps the rule could be "Avoid using GetCurrentMethod" because that's generally broken API anyways.

**Comment by AnthonyDGreen** [comment]
Well, I know GetCurrentMethod results can be corrupted by JIT I lining. The x64 JIT as I recall was notorious for aggressively inlining things. We actually found places where code access security boundaries would be optimized away like this so no it's not reliable. That said, it is a change worth documenting and we can certainly create some kind of upgrade advisor diagnostic pack to help here.

Regards,

-ADG

Sent from my Windows Phone
________________________________

**Comment by gafter** [comment]
Reopening and assigning to @AnthonyDGreen to be added to the compiler specs.

**Comment by AnthonyDGreen** [comment]
I've added a link to this issue to our index in the compiler spec to be ported into markdown with the other known breaking changes.

**-ADG**
