### ISSUE TITLE
It looks like there is no way to explicitly implement an event and use extern modifier because parser requires accessors.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#19838]

**Comment by gafter** [comment]
This isn't a compiler bug. This is required by the language specification. See https://github.com/dotnet/csharplang/blob/master/spec/classes.md#events

Perhaps you meant to add this issue to the csharplang repo?

**Comment by AlekseyTs** [comment]
@gafter I am not sure what particular portion of the spec you refer to. Could you please quote the relevant portions here?

**Comment by gafter** [comment]
Sure. The relevant part is this grammar excerpt:

```antlr
add_accessor_declaration
    : attributes? 'add' block
    ;

remove_accessor_declaration
    : attributes? 'remove' block
    ;
```

**Comment by AlekseyTs** [comment]
> Sure. The relevant part is this grammar excerpt:

That is just a grammar for accessors when accessors are provided. You didn't quote the part that requires accessors' declarations to be present.

**Comment by alrz** [comment]
```
event_declaration
    : attributes? event_modifier* 'event' type variable_declarators ';'
    | attributes? event_modifier* 'event' type member_name '{' event_accessor_declarations '}'
```
I think the second rule matches an explicit implementation which requires assessors.

**Comment by gafter** [comment]
Dup of #19003
