### ISSUE TITLE
Don't underline the entire lambda for missing return statement

### ISSUE THREAD

**Issue by hughbe** [dotnet/roslyn#19840]
**Version Used**: 
Microsoft (R) Visual C# Compiler version 2.1.0.61520

**Steps to Reproduce**:

Compile this code:

```cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main()
        {
            return new int[0].Select<int, int>(rawData =>
            {
                for (int i = 0; i < 100; i++)
                {
                    Console.WriteLine(i);
                }
            });
        }
    }
}
```

**Expected Behavior**:

Only part of the lambda is highlighted with red squigglies. This helps focus the error from the IDE side

**Actual Behavior**:

All of the lambda is underlined with red squigglies. This is very distracting, especially in large lambdas such as those used for Elasticsearch/NEST.

![untitled](https://cloud.githubusercontent.com/assets/1275900/26535486/1a7579f8-4458-11e7-9464-281e15b03ccf.png)

**Comment by jcouv** [comment]
I think @CyrusNajmabadi fixed this already. Trying this code sample on [TryRoslyn](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDZICYgNQA+AAgAwAERAjANwCwAUKRZQCx2PlUB0AMmgHYBHdg34QwcKAAcIAYzhkAwgHt+UZRjgBBKVMoMA3gzImKAZgoAmMgAUEygOYJxx00fqnP5srAgw0shQsZACyEAIAFACUrl5k7nFxRADsZPxwAO5kAjAA2iQAulwAynCasjAAPDlI2fwwAHwRzhkAIn4QZAC8DbGJJgn9iQBmyghkETnZ3WQk1NOVZJQkc9l4eDEeQ3GD2/0qahpwXADqCGjwfOmTUex7XgC+ff0Pt8+mT1smnw9AA=) only underlines the arrow of the lambda.
I'll go ahead and close.

**Comment by jcouv** [comment]
Just for clarification, I expect the fix will ship with Visual Studio 2017 version 15.3.
