### ISSUE TITLE
Strange naming suggestion when you return a Task<string>

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19859]
Getting naming suggestions "Get**V**Async" - not sure why the "V"?

![image](https://cloud.githubusercontent.com/assets/1103906/26569747/eb5ac684-454f-11e7-860f-f08d29d2da24.png)

**Comment by Pilchie** [comment]
Because our name suggester suggests `v` for values when there is not better name.  We should probably just not offer a suggestion here.

**Comment by CyrusNajmabadi** [comment]
we offer:

![image](https://user-images.githubusercontent.com/4564579/198746461-d30692f3-d0f2-47fd-8173-77ec7cb858ce.png)


Which, while not great, doesn't seem awful.  It's a suggestion after all... so can be ignored.
