### ISSUE TITLE
Change the IOperation unit test dump format for child nodes

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#19866]
Currently, the dump prints the first child on the same line as the children header, which makes reviewing the dump very tedious. @AlekseyTs and @jcouv have both requested to change this format to dump the first child node on a new line.

It is a single line change in the dumper: we just need to append Environment.NewLine to the string argument passed to this LogString call: http://source.roslyn.io/#Roslyn.Test.Utilities/Compilation/OperationTreeVerifier.cs,245

However, this will need to update the expected output for almost all of the existing IOperation unit tests. We should do this sooner rather than later though.

@jinujoseph Can we get the vendors do this task as soon as possible?

**Comment by jinujoseph** [comment]
also look into https://github.com/dotnet/roslyn/pull/20276#discussion_r122770695

**Comment by jinujoseph** [comment]
closed via https://github.com/dotnet/roslyn/pull/20716
