### ISSUE TITLE
[Proposal] FileSystem absraction in MSBuildWorkspace

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#19891]
It would be great if I could plug in a virtual filesystem into an MSBuildWorkspace.
One example that I'm considering right now would be providing analysis over a git commit without actually checking it out (e.g. libgit2sharp allows me to get streams for any blob).

**Comment by Pilchie** [comment]
Our initial thoughts were that you would derive your own type from `Workspace` for this sort of scenario, but I can see how re-using `MSBuildWorkspace` for the solution population would be useful there.

@DustinCampbell - thoughts?

**Comment by DustinCampbell** [comment]
Perhaps I'm missing something, but I'm not sure this is actually possible from MSBuildWorkspace. After all, MSBuildWorkspace calls into MSBuild, which directly uses the file system. So, solution and project files would absolutely need to be on disk and paths to source files and references would also be on the file system. After that, it would be possible to substitute different files and references as part of populating the workspace, but I'm not sure there's much value.

I'd recommend using the [`MSBuildProjectLoader`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/MSBuild/MSBuildProjectLoader.cs,25b131ba5b71dc06) to do the heavy lifting of processing solution and project files. Once you've got that, populating a custom workspace from your own virtual file system isn't that much work.

**Comment by CyrusNajmabadi** [comment]
Closing out as this doesn't seem actionable.  If you still want this, i'd create a new issue going through the api proposal process.  Thanks!
