### ISSUE TITLE
No async test case for a try/finally with an uncaught exception

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/roslyn#19905]
Looking at the async test cases in https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs, there does not appear to be any case in which an exception is thrown inside a `try/finally` block and not caught, causing the `finally` to be entered from exceptional control flow rather than ordinary control flow.

Note: The `AnonType32` and `Await43` tests do throw exceptions inside a `try/finally` block, but then they both catch them before entering `finally`.

Filing this as an issue per @jmarolf.

**Comment by drcjt** [comment]
I'd like to use this as a first contribution/patch to Roslyn.

If my understanding is right the core of this test would be like this:

`try
{
	var tmp = await (new { task = Task.Run<string>(async () => { await Task.Delay(1); return ""; }) }).task; 
	throw new Exception(tmp);
}
finally
{
	// If reached here then test is successful
}`

**Comment by masonwheeler** [comment]
@drcjt Yeah, basically.  But whatever's calling `TestCase.Run()` has to catch and handle the exception.
