### ISSUE TITLE
Operation tree contains no nodes for local functions

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#19902]
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp2
{
    class Program
    {
        static IEnumerable<T> F<T>(IEnumerable<T> source, Func<T, bool> predicate)
        {
            IEnumerable<T> Iterator()
            {
                foreach (var element in source)
                    if (predicate(element))
                        yield return element;
            }

            return Iterator();
        }
    }
}
```

Operation tree for BoundLocalFunctionStatement has no child nodes.

We seemed to have added an OperationKind.LocalFunctionStatement, but added no IOperation interface for it, causing us to miss this bug when we added IOperationWithChildren.

**Comment by mavasani** [comment]
Tagging @dotnet/analyzer-ioperation - I believe we should fix this for 15.3

**Comment by mavasani** [comment]
To be clear on the example above, remove unused parameters analyzer will report both source and predicate as unused parameters.

**Comment by 333fred** [comment]
@jinujoseph, should we bring this to the meeting today?

**Comment by jinujoseph** [comment]
This is just a bug which needs to be fixed,and manish already knows what needs to be done here. @mavasani do you have any concern from design perspective ?

**Comment by mavasani** [comment]
I presume Fred meant discuss the new IOperation API that must be introduced in 15.later, correct? I will work on the workaround for 15.3 meanwhile.

**Comment by jinujoseph** [comment]
Ah sure , can you put the proposed API shape for discussion today

**Comment by 333fred** [comment]
I was assuming that you had an API shape. If not, it doesn't matter for now.

**Comment by mavasani** [comment]
I am assuming we want to expose the body and the local function symbol, so the API should be pretty trivial:

```
    public interface ILocalFunctionStatement : IOperation
    {
        IBlockStatement Body { get; }

        IMethodSymbol LocalFunctionSymbol { get; }
    }
```

**Comment by mavasani** [comment]
We probably want to share a common sub-type with ILambdaExpression though: http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/ILambdaExpression.cs,14

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/20177
