### ISSUE TITLE
AbstractCompletionProviderTests.CreateWorkspace is confusing

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#19901]
It's a base method on the abstract test harness and the naming implies that it gives implementors a chance to create their own workspace. It's only called in the methods that verify trigger or commit characters. We should consider renaming it, at least.

**Comment by rchande** [comment]
Observed in https://github.com/dotnet/roslyn/pull/19805/files

**Comment by CyrusNajmabadi** [comment]
This method seems fine to me.  It's the abstract base that allows the C# and VB impls to create the appropriate workspace they want.  Closing out as not something we need a tracking issue for.
