### ISSUE TITLE
Toggle between multi-line and single-line initialization

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#19904]
Filed on behalf of a customer.

The customer would like a way to easily toggle to make initializations single/multiple lines, e.g.,

```csharp
var foo = new Bar 
{
    Prop1 = "my prop",
    Prop2 = "my other prop"
}
```

After `Ctrl+.` is pressed:

```csharp

var foo = new Bar { Prop1 = "my prop", Prop2 = "my other prop" }
```

**Comment by thomasthiry** [comment]
I think that for code readability the single line / multiple lines has a big impact and that too often code is left the way it is just because it's too painful to switch. 
Also, this allows you to quickly see the content of the whole line (formatted) and put it back into one line after you've read it.

**Comment by CyrusNajmabadi** [comment]
PRs welcome.

**Comment by thomasthiry** [comment]
I think I'll need some time to get used to that... :-) 
But that's awesome, thanks.

**Comment by Neme12** [comment]
Should we really have code fixes that only change whitespace formatting? If so, what should this apply to? Just object/array initializers? Parameters as well? How would this interact with code style settings?

**Comment by CyrusNajmabadi** [comment]
> Should we really have code fixes that only change whitespace formatting? If so, what should this apply to? Just object/array initializers? Parameters as well?

I would think: constructs that people commonly put on multiple or single lines.

> Parameters as well? 

Definitely.  Wrapping of parameters is one of the most common stylistic things people do in a codebase.  

> How would this interact with code style settings?

Presumably the code style setting tells you when something is wrong.  The feature allows you to then quickly get the code 'right'.  For people who don't use codestyles here, the feature just allows you to rapidly tweak the formatting.

**Comment by CyrusNajmabadi** [comment]
Note: this would be a good location to use the new 'wrapping' code refactoring system.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
