### ISSUE TITLE
BoundDelegateCreationExpression does not implement IMethodBindingExpression

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#19917]
Given the following VB code;

```vb
Public Class C1
    Private _handler As Action(Of Object)

    Public Sub Handler(o As Object)
    End Sub

    Public Sub SetupHandler()
        _handler = AddressOf Handler
    End Sub
End Class
```

We get the following Operation tree for `AddressOf Handler`;
```
IOperation tree for "AddressOf Handler"

IOperation:  (OperationKind.None) (Syntax: 'AddressOf Handler')
  Children(1): IInstanceReferenceExpression (InstanceReferenceKind.Implicit) (OperationKind.InstanceReferenceExpression, Type: C1) (Syntax: 'Handler')
```

This is because that `AddressOf` results in a `BoundDelegateCreationExpression`, which does not implement `IMethodBindingExpression`. I think the fix here is just to make it implement the interface. @AlekseyTs, does that sound correct to you?

**Comment by 333fred** [comment]
FYI @dotnet/analyzer-ioperation

**Comment by mavasani** [comment]
BoundDelegateCreationExpression also takes an argument for C#. It does not seem right for it to implement just IMethodBindingExpression. We already have a tracking bug for designing the correct API for exposing this bound node.

**Comment by mavasani** [comment]
See https://github.com/dotnet/roslyn/issues/18839

**Comment by mavasani** [comment]
And also https://github.com/dotnet/roslyn/issues/8897

**Comment by 333fred** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/20095.
