### ISSUE TITLE
IOperation API for anonymous object creation expressions

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#19926]
Two possible approaches:

1. Expose two separate arrays for declared property symbols and arguments:
```
    public interface IAnonymousObjectCreationExpression : IHasArgumentsExpression
    {
        ImmutableArray<IPropertySymbol> DeclaredProperties { get; }
    }
```

2. Expose a single array of property initializers, each with declared symbol and initializer:

```
    public interface IAnonymousObjectCreationExpression : IOperation
    {
        ImmutableArray<IAnonymousPropertyInitializer> Initializers { get; }
    }

    public interface IAnonymousPropertyInitializer : IOperation
    {
        IPropertySymbol DeclaredProperty { get; }
        IOperation Initializer { get; }
    }

```

**Comment by CyrusNajmabadi** [comment]
```c#
public interface IAnonymousObjectCreationExpression : IOperation
    {
        ImmutableArray<IAssignmentExpression> Initializers { get; }  // or
        ImmutableArray<IOperation> Initializers { get; }
    }
```

---

If we use AssignmentExpression we need to have a IOperation for the left side.  This will be a PropertyReferenceExpression.  HOwever, because we don't have an appropriate 'receiver' (since we're inside creating the anonymous expression), we'll just use 'null' as the receiver and doc this.
