### ISSUE TITLE
IOperation API for BoundDeconstructionAssignmentOperator

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#19924]
Two possible approaches:

1. Expose it as an IAssignmentExpression, where left and right are IOperations.
2. Introduce a new type with more strongly typed left and right child nodes:

```
    public interface IDeconstructionAssignmentExpression : IOperation
    {
        ITupleExpression Left { get; }
        IConversionExpression Right { get; }
    }
```

**Comment by CyrusNajmabadi** [comment]
Pull @jcouv in for this next week @jinujoseph

**Comment by jinujoseph** [comment]
**Design Team Decision**

_From @jcouv_ 

The proposal is to represent deconstruction-assignments (`(a, b) = e;`) and deconstruction-declarations (`(var a, var b) = e;`) with IAssignment nodes, containing a left, a right, and a deconstruction conversion.
One follow-up was to check with LDM if the language should say that deconstructions are conversions.

From discussion with @gafter , he think that the language will probably not treat deconstructions as conversions, but that should not matter to IOperation design.
We can go forward with the proposed design regardless of what LDM decides.

**Comment by mavasani** [comment]
@333fred Does your PR https://github.com/dotnet/roslyn/pull/21643/files address this?

**Comment by 333fred** [comment]
No, it does not.
