### ISSUE TITLE
[ComImport] broken when using .net native

### ISSUE THREAD

**Issue by albertofustinoni** [dotnet/roslyn#19942]
Looks like the latest version of the .net native compiler has broken `[ComImport]` functionality when dealing with WinRT components.

I have followed the documentation detailing how to [play audio using Audio graphs](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/audio-graphs) in UWP and, since I am generating the samples procedurally, I need to use the following:

```
[ComImport]
[Guid("5B0D3235-4DBA-4D44-865E-8F1D0E4FD04D")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
unsafe interface IMemoryBufferByteAccess
{
    void GetBuffer(out byte* buffer, out uint capacity);
}
```

I have put my audio generating code into its own WinRT component and link to it from other assemblies as needed.

My app works correctly when compiled in debug mode but can't even build in release since that uses .net native. What I get is the following error

```
C:\Users\Alberto\.nuget\packages\microsoft.net.native.compiler\1.6.2\tools\Microsoft.NetNative.targets(691,5): error : ILT0021: Could not resolve method 'System.Void LibretroRT.AudioGraphPlayer.AudioPlayer.IMemoryBufferByteAccess__LibretroRT_AudioGraphPlayer__Impl.Stubs.GetBuffer(System.__ComObject, ref System.Byte*, ref System.UInt32)'
```

Interestingly, if I copy and paste the exact same code into the app project itself it does work.

You can reproduce the issue for yourself: the app is open source on [this GitHub repo](https://github.com/Aftnet/LibretroRT)

I'm using the latest version (5.3.3) of the `Microsoft.NETCore.UniversalWindowsPlatform` nuget package as well.

Any way to work around this?

**Comment by jcouv** [comment]
@MichalStrehovsky for confirmation and triage.

**Comment by MichalStrehovsky** [comment]
From looking at the test coverage, `[ComImport]`/`[Guid]`/`[InterfaceType]` should work with .NET Native, but maybe there's a bug somewhere. As a blind attempt to work around you could try:

* make the the `IMemoryBufferByteAccess` interface non-nested
* make the `out byte* buffer` into `out IntPtr buffer`

I'm not sure if either would help to work around the possible bug, but it's worth a try.

We're better equipped to help with .NET Native issues by email: `dotnetnative at microsoft com` - we should probably move this issue over there (whether the workaround helps or not), as it's unlikely to be Roslyn related.

Cc @yizhang82

**Comment by yizhang82** [comment]
@albertofustinoni My guess would be that ref byte * might be what's triggering the bug. It would be good if you can send mail to the mail mentioned by @MichalStrehovsky so that we can better help you there. I'll take a look either way. Thanks for reporting the issue!

**Comment by jcouv** [comment]
Thanks for the assistance Michal and Yi. 
I'll close the issue as External and let @albertofustinoni follow-up with you as recommended.

**Comment by albertofustinoni** [comment]
@MichalStrehovsky Making `IMemoryBufferByteAccess` not nested (maybe also moving it into its own file) seems to have done the trick: I have been able to compile in release.

I have sent an email to the address you mentioned about the issue, in any case.

P.S. I know this is not the place to ask, but do you know where to report issues with the C++ compiler? I'm getting "internal error" when compiling one of the native projects for ARM in release mode now...

**Comment by yizhang82** [comment]
@xiangfan-ms Can you let @albertofustinoni how to report the C++ compiler issue?

**Comment by xiangfan-ms** [comment]
For external customer, the official report channel is from VS menu 'Help' -> 'Send Feedback'.
Or you can go to https://vsfeedback/ directly.
