### ISSUE TITLE
Initialize field and property from parameter should be available even if the constructor does not have braces

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#19956]
**Steps to Reproduce**:

1. Create a class and try to type a new constructor like so:

```C#
class C
{
    public C(string text)
}
```

2. With the caret within `text`, press <kbd>Ctrl+.</kbd>

**Expected Behavior**: The "initialize field and property refactorings" should be available. Invoking them should generate braces for the constructor body.

**Actual Behavior**: Only "change signature" is available.

**Comment by CyrusNajmabadi** [comment]
Done!
