### ISSUE TITLE
Investigate behavior of "orphan" files during a code fix

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#19952]
As a follow-up to #19919, it would be helpful to know the precise behavior in an edge case currently believed to be hypothetical. This is an **investigation** issue that anyone with a small amount of free time should be able to work through.

Estimated time to complete investigation: 3 hours.

### Experimental setup

1. Define a class which implements `IVsHierarchy` and `IVsProject`. Everything can throw `NotImplementedException` except for [`IVsProject.IsDocumentInProject`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivsproject.isdocumentinproject.aspx), which needs to set `pfFound=0; pitemid=0; return VSConstants.S_OK;`.
3. Modify the `InvisibleEditor` constructor to ignore the `projectOpt` argument and instead use an instance of the previously defined special class as the `vsProject` variable.

### Experiment

Make sure Fix All operations work for documents which are not open in the editor. This should include experimenting with the legacy project system as well as the new CPS-based projects. Roslyn.sln includes projects of both forms, and the Use Default Literal code style fixer has proven useful in earlier evaluations.

1. Make sure Undo operation works after applying a Fix All (should undo changes made to files which were not open).
2. Make sure if you open a changed file after applying a code fix, that the Project dropdown at the top left of the editor shows the correct project name(s) and features like Quick Info and navigation work. In particular, make sure the project is *not* listed as "Miscellaneous Files".

### Results

1. Push a branch to your fork containing the modified code so the experimental setup can be peer reviewed for accuracy.
2. Modify the comments in `InvisibleEditor` to describe the impact of this forced edge case on the ability of Fix All operations to apply to files which are not open in the editor.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
