### ISSUE TITLE
Visual C++ does not block as expected on Modreq(IsConst)

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#19950]
Visual C++ compiler understands Modreq(IsConst) and accepts it (on return types and parameters), but doesn't enforce read-only semantics on the signature.
We might need to re-consider using another type for the modifier.
Found in #19658

**Comment by tannergooding** [comment]
It's probably worth noting this section from the C++/CLI [spec](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-372.pdf):

![image](https://cloud.githubusercontent.com/assets/10487869/26736442/e14b01e0-477a-11e7-8462-ef59ef6d5082.png)

**Comment by OmarTawfik** [comment]
After merging #20254, this is now fixed. The C++ compiler produces:

```
warning C4679: 'T1::M1': could not import member
note: This diagnostic occurred while importing type 'T1 ' from assembly 'temp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
```
