### ISSUE TITLE
Having an item that is both a source file and an additional item breaks DPL and CPS

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#19968]
See https://github.com/dotnet/project-system/issues/1350, and the PR https://github.com/dotnet/roslyn/pull/19889 where we avoid duplicates.

Having a project file with:

``` XML
<ItemGroup>
   <Compile Include="Foo.cs"/>
   <AdditionalFiles Include="Foo.cs"/>
</ItemGroup>
```

And then enabling Lightweight solution load repros this (files end up in misc files due to an `ArgumentException`).

**Comment by Pilchie** [comment]
It looks like we end up creating the same `IVisualStudioHostDocument` for both files.

**Comment by Pilchie** [comment]
Hmm - I tried just refcounting in the `_documentMonikers` collection, but the workspace is also unhappy with this.

Turns out that the native project system also gets this exception and swallows it and doesn't set any more properties from the Design Time Build :-/

**Comment by KevinH-MS** [comment]
Curiosity:  Can you elaborate on the end-to-end scenario where having this in a project would be meaningful?  (we're trying to figure out if this is something we need to worry about for LUT or not, but I can't tell when or why someone would write it).

Would we get workspace events for the additional file? 

/CC @shyamnamboodiripad @drognanar

**Comment by Pilchie** [comment]
@KevinH-MS I don't think it's a common scenario, and in fact has never worked properly in the legacy project system, it just swallowed the exception during project creation.

@davkean mentioned that there are some cases in CPS where this happens, but I think they are transient, due to the async nature of CPS populating the language service.

**Comment by MattGertz** [comment]
Mondo escrow triage:  doesn't seem like a common scenario, let's fix post-escrow.

**Comment by Pilchie** [comment]
@MattGertz : The PR for this (#20558) is currently `Pending Director Approval` - should we withdraw it from that list?

**Comment by MattGertz** [comment]
No, let's leave it.

**Comment by Pilchie** [comment]
Fixed in #20558

**Comment by Pilchie** [comment]
This fix was reverted because it broke typescript.  Re-activating.

**Comment by dpoeschl** [comment]
@Pilchie What happened with the PR here?

**Comment by Pilchie** [comment]
It's only partially complete.  More work still needs to happen :-/

**Comment by CyrusNajmabadi** [comment]
AFAIK dpl is not a thing anymore. And we have no more feedback on this.  Closing out.
