### ISSUE TITLE
Add a code fix/format to fix modifier ordering

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19971]
Unlike VB, C# doesn't fix up the ordering of a modifier:

``` C#
    internal partial static class ProjectLoggerExtensions
    {
        public static ILifetime<IProjectLogger> BeginLoggingContext(this IProjectLogger logger)
        {
            Requires.NotNull(logger, nameof(logger));

            return new ProjectLoggingContext(logger);
        }
    }

```

Above partial needs to go before class. I never remember the ordering, so we can we auto-fix this or give me a code fix so that I can just CTRL+. then ENTER to fix it immediately.

**Comment by Pilchie** [comment]
modifier analyzer is https://github.com/dotnet/roslyn/issues/7066, and the ability to auto-fix any analyzer with a fix is https://github.com/dotnet/roslyn/issues/7068.
