### ISSUE TITLE
Tooltip for XML comment elements are empty

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19974]
![image](https://cloud.githubusercontent.com/assets/1103906/26707892/5bee1382-478b-11e7-988e-8b3379fd9693.png)

**Comment by gundermanc** [comment]
@AmadeusW @dpoeschl is this fixed with the 15.next completion work?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback about this issue.
