### ISSUE TITLE
Create a way to check if FixProvider is being called from Preview Window Vs Committed

### ISSUE THREAD

**Issue by GrantHoffman** [dotnet/roslyn#19989]
**Feature Request**:
    Create a way to tell if the FixProvider is being Called for preview or for comitting.

I've created a Code Fix Provider to Add resources to a file, however these changes should only be applied via final commit.   There is no good way of finding if fix was for preview or for comit  Currently, I am using the call stack as a work around:

        public static bool IsCallFinal()
        {
            var currentStack = new StackTrace();
            return false == currentStack.GetFrames().Any(x => x.GetMethod().Name == "<GetPreviewOperationsAsync>b__0");
        }

**Comment by Pilchie** [comment]
You can do this by overriding [`ComputePreviewOperationsAsync`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeActions/CodeAction.cs,4a60a4dc2ea63ba0) and returning something different. The default impl just calls `ComputeOperationsAsync` though.

**Comment by Pilchie** [comment]
l
