### ISSUE TITLE
Binding for ForEachVariableStatement doesn't bind Variable expression unless it is a deconstruction left

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#19996]
For example, see scenario in unit-test GetEnclosingBinderInternalRecovery_11 added in https://github.com/dotnet/roslyn/pull/19995.

This creates problems for SemanticModel because it cannot find information about that expression in a normal way. The approach we have been taking is that expressions like that should still be bound (perhaps ignoring any diagnostics from that) and preserved in the bound tree for the semantic model to find. See, how we handle declarator arguments (BindDeclaratorArguments), which are disallowed by the grammar.

**Comment by AlekseyTs** [comment]
This issue will likely have negative effect on IOperation as bound tree will be missing bound information for some portions of code.

**Comment by gafter** [comment]
This issue is among a set of duplicates that includes the following issues: https://github.com/dotnet/roslyn/issues/15601, https://github.com/dotnet/roslyn/issues/15759, https://github.com/dotnet/roslyn/issues/23007.

**Comment by 333fred** [comment]
Fixed in #25848.
