### ISSUE TITLE
OverriddenOrHiddenMembers property from MethodSymbol is internal

### ISSUE THREAD

**Issue by macpak** [dotnet/roslyn#200]
Just a question: why did you decide to make this property internal ? Why can't it be public ?

**Comment by jmarolf** [comment]
No one tested this api for general use or found the time to rationalize its performance characteristics.  This is a very expensive method to call.  We can carefully control how we use it internally on the roslyn team, but once we make it public we need to be ok with people calling it from anywhere.  We'll likely make this public at some point, but someone will need to spend the time to look at it and decide if this is really the best way to do things.  For what scenario did you need this information?

**Comment by macpak** [comment]
I am working on a [StyleCop implementation using Roslyn ](https://github.com/DotNetAnalyzers/StyleCopAnalyzers). We have a rule that is violated if: **A call to a member from an inherited class begins with ‘base.’, and the local class does not contain an override or implementation of the member.** . In order to make it work, we need to know if the override/hidden member exists in the child class.

**Comment by amcasey** [comment]
There are some nuances to consuming the data structure returned by OverriddenOrHiddenMembers.  I would have thought you'd be able to get what you wanted from IMethodSymbol.OverriddenMethod and ITypeSymbol.FindImplementationForInterfaceMember.  As for hidden members, yes there should probably be a public API.  I believe there's an existing bug, but I can't seem to find a number.

**Comment by amcasey** [comment]
Found it.  This is tracked internally as 998952.

**Comment by sharwell** [comment]
For reference, the rule is actually implemented as:

> Replace `base.` with `this.` in any case where it does not change the meaning of the code.

**Comment by amcasey** [comment]
I would be surprised to learn we don't have that functionality in the language services.  We certainly remove redundant "this." qualification, so tidying up "base." seems like a natural progression.

**Comment by amcasey** [comment]
I think this is it: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/ExpressionSyntaxExtensions.cs,1667

This might be a simpler way to go.  Basically, you just replace "base." with "this." then re-bind and check for differences.  I'm not sure what the perf implications are, but it seems to work in the IDE.

**Comment by heejaechang** [comment]
you can use SpeculativeSemanticModel from SemanticModel to see whether base.X and this.X bound to same thing. doing this using SpeculativeSemanticModel should be really cheap.

**Comment by theoy** [comment]
Stealing this b/c I think there is a private discussion related to this as well.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
