### ISSUE TITLE
CSharpLanguageInstructionDecoder implementation of IDkmLanguageInstructionDecoder is slow

### ISSUE THREAD

**Issue by tommcdon** [dotnet/roslyn#20017]
The implementation of IDkmLanguageFrameDecoder.GetFrameName in Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CSharpLanguageInstructionDecoder is causing slow stepping performance if the callstack or threads windows are open in Visual Studio.  In ETL traces that we have looked it, we see that about half of the time stepping can be spent in this function.

**Comment by sharwell** [comment]
@tommcdon Is there a trace we can take a look at to help narrow things down?

**Comment by tommcdon** [comment]
\\vsdbgqa\tommcdon\Traces\ML Cyrus Traces\ReproTrace3.etl.zip
