### ISSUE TITLE
Smart variable naming keep suggesting names after a name is applied

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#20016]
Type: 
```csharp
 Dictionary<string, string> 
```

* Press `Space`. 
* Apply the suggestion ```dictionary```. 
* Press`Space`.  ```dictionary``` will be suggested again. I expected nothing to be suggested (or maybe an ```=```).

![image](https://cloud.githubusercontent.com/assets/1402694/26792019/e707c87a-49cd-11e7-8ed7-7de6f59c5c8f.png)

**Comment by rchande** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/20792
