### ISSUE TITLE
Unclear message when compiler cannot find System.ValueTuple types when NuGet package < 4.4.0

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/roslyn#20018]
**Version Used**: 

15.3 Preview 2 (26602.0.d15rel)

**Steps to Reproduce**:

```csharp
namespace ConsoleApp13
{
    class Program
    {
        static void Main(string[] args)
        {
            var (a,b,c) = (1, 2, 3);
        }
    }
}
```

**Expected Behavior**:

Targeting .NET 4.6, I add the `System.ValueTuple` 4.3.1 package and it works.
Targeting .NET 4.7, I add the `System.ValueTuple` 4.3.1 package and it works.

**Actual Behavior**:

Targeting .NET 4.6, I add the `System.ValueTuple` 4.3.1 package and it works.
Targeting .NET 4.7, I add the `System.ValueTuple` 4.3.1 package and it fails:

```
error CS8179: Predefined type 'System.ValueTuple`3' is not defined or imported
```

/cc @jcouv

**Comment by sharwell** [comment]
❓ What version of the System.ValueTuple NuGet package do you have installed? Prior to 4.4.0-preview1-25305-02 I believe it would be confusing to the compiler (type defined in both mscorlib and in System.ValueTuple).

**Comment by twsouthwick** [comment]
Ah - I have 4.3.1 installed. I'll give 4.4.0 a shot.

**Comment by twsouthwick** [comment]
Ok - installing 4.4.0-preview1-25305-02 seems to fix the issue. Is there already a bug tracking adding better warnings or fixing the ambiguity?

**Comment by jcouv** [comment]
@twsouthwick Go ahead and file an issue. Thanks
I agree the message should say something about ambiguity between two types that were found, rather than saying it's missing.

**Comment by sharwell** [comment]
@jcouv Does this issue not suffice?

Also, it'd be good to special case the warning if the ambiguity occurs due to System.ValueTuple.dll and either .NET Standard or mscorlib, due to the likelihood of this particular upgrade path.

**Comment by jcouv** [comment]
Sure. Fixed issue title.

**Comment by twsouthwick** [comment]
I see we both changed the title at the same time - I'll stop touching it :)

**Comment by jcouv** [comment]
Improved the message with #20077
