### ISSUE TITLE
we should log non-fatal watson when extension throws an exception

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#2002]
we need at least to do that for our own ones such as code fixer, code refactoring and etc.

**Comment by jmarolf** [comment]
@heejaechang can you verify this please?

**Comment by heejaechang** [comment]
@jmarolf re-opened the issue. VS shows if exception is thrown from RegisterCodeFixesAsync, but other public APIs such as FixableDiagnosticIds, GetFixAllProvider doesn't show it.

**Comment by jmarolf** [comment]
We already guard against these cases:
- FixableDiagnosticIds is guarded against [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/CodeFixes/CodeFixService.cs,409)
- GetFixAllProvider is guarded against [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/CodeFixes/CodeFixService.cs,274) 

However, we do not guard against improperly initialized ImmutableArrays for FixableDiagnosticIds like we do for [SupportedDiagnostics](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerManager.cs,166)

I'll fix this case and then close this issue

**Comment by jmarolf** [comment]
@heejaechang can you verify this please?
