### ISSUE TITLE
Possible deadlock/hang in BindNamedAttributeArgument

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#20036]
See dump and repro at \mlangfs1\public\kirillo\cschang

Sample stack:
```
>	Microsoft.CodeAnalysis.CSharp.Binder.BindNamedAttributeArgument Line 358	C#
 	Microsoft.CodeAnalysis.CSharp.Binder.BindAttributeArguments Line 320	C#
 	Microsoft.CodeAnalysis.CSharp.Binder.BindAttributeCore Line 148	C#
 	Microsoft.CodeAnalysis.CSharp.Binder.GetAttributes Line 73	C#
 	Microsoft.CodeAnalysis.CSharp.Symbol.LoadAndValidateAttributes Line 323	C#
 	Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.GetAttributesBag Line 460	C#
 	Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.GetAttributes Line 469	C#
 	Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.ForceComplete Line 406	C#
 	Microsoft.CodeAnalysis.CSharp.Symbol.ForceCompleteMemberByLocation Line 712	C#
```

5 threads are sitting in this exact call stack and nothing else is happening.

This was reported by the SQL team as it periodically hangs their builds. I'm not sure this is a hang in csc.exe but the csc.exe process is stuck with the dump and nothing is moving along.

Internal contact: Grant Culbertson.

**Comment by jcouv** [comment]
@VSadov Could you take a look and advise for 15.3 course of action?

**Comment by VSadov** [comment]
looking

**Comment by VSadov** [comment]
The repro that is provided actually works for me. 
What I noticed is that current compiler compiles the sample much faster than the one packaged with the repro. - both still succeed and produce a binary.

Perhaps the sample hits some particularly expensive codepath that was fixed since the last release (there were several) and it is just slow?

@jcouv  - Considering the difficulties with repro, I have doubts this would meet the bar for 15.3

**Comment by KirillOsenkov** [comment]
@VSadov thanks for looking! By just looking at the callstacks in the dump, can you make an educated guess if a deadlock is possible in that codepath? Is there a rare race condition under which the 5 threads will all deadlock? When I've grabbed the dump the csc.exe definitely didn't seem to be progressing. I even took another dump a few minutes later and it was still in the exact same state. 

If Grant's builds freeze again with csc.exe in these same frames we'll know it's a non-deterministic deadlock.

Another idea: maybe by inspecting the dump with WinDbg we can figure out what the threads are all waiting for?

**Comment by VSadov** [comment]
Looked in WinDbg - it appears to be a deadlock in the JIT/typeloader. 

No threads are making progress. 
In particular:

=== one thread:
ntdll!ZwWaitForSingleObject(void)+0xa
ntdll!RtlpWaitOnCriticalSection(struct _RTL_CRITICAL_SECTION * CriticalSection = 0x000000b8`ca760e30 Locked with contention, long Increment = <Value unavailable error>)+0xe1
ntdll!RtlpEnterCriticalSectionContended(struct _RTL_CRITICAL_SECTION * CriticalSection = 0x000000b8`ca760e30 Locked with contention)+0xa4
clr!UnsafeEnterCriticalSection+0x9
clr!CrstBase::SpinEnter(void)+0xa2
clr!CrstBase::Enter(void)+0x11c
clr!CrstBase::AcquireLock+0x8
clr!CrstBase::CrstHolder::CrstHolder(class CrstBase * pCrst = <Value unavailable error>)+0x14
clr!ClassLoader::LoadTypeHandleForTypeKey_Body(class TypeKey * pTypeKey = 0x000000b3`c5d29bf0, class TypeHandle typeHnd = class TypeHandle, ClassLoadLevel targetLevel = CLASS_LOAD_EXACTPARENTS (0n4))+0x2ac
clr!ClassLoader::LoadTypeHandleForTypeKey(class TypeKey * pTypeKey = 0x000000b3`c5d29bf0, class TypeHandle typeHnd = class TypeHandle, ClassLoadLevel targetLevel = CLASS_LOADED (0n6), class InstantiationContext * pInstContext = 0x00000000`00000000)+0xee
clr!ClassLoader::LoadTypeDefThrowing(class Module * pModule = 0x00007ff8`ed399cf8, unsigned int typeDef = 0x200051d, ClassLoader::NotFoundAction fNotFoundAction = ThrowIfNotFound (0n0), ClassLoader::PermitUninstantiatedFlag fUninstantiated = FailIfUninstDefOrRef (0n0), unsigned int tokenNotToLoad = 0, ClassLoadLevel level = CLASS_LOADED (0n6), class Instantiation * pTargetInstantiation = 0x00000000`00000000)+0x207
clr!ClassLoader::LoadTypeDefOrRefThrowing(class Module * pModule = 0x00007ff8`ed399cf8, unsigned int typeDefOrRef = 0x200051d, ClassLoader::NotFoundAction fNotFoundAction = ThrowIfNotFound (0n0), ClassLoader::PermitUninstantiatedFlag fUninstantiated = FailIfUninstDefOrRef (0n0), unsigned int tokenNotToLoad = 0, ClassLoadLevel level = CLASS_LOADED (0n6))+0x242
clr!SigPointer::GetTypeHandleThrowing(class Module * pModule = 0x00007ff8`ed399cf8, class SigTypeContext * pTypeContext = 0x000000b3`c5d2a120, ClassLoader::LoadTypesFlag fLoadTypes = LoadTypes (0n0), ClassLoadLevel level = CLASS_LOADED (0n6), int dropGenericArgumentLevel = 0n0, class Substitution * pSubst = 0x00000000`00000000, struct ZapSig::Context * pZapSigContext = 0x00000000`00000000)+0x5ed
clr!CEEInfo::getFieldTypeInternal+0x194887
clr!CEEInfo::getFieldType(struct CORINFO_FIELD_STRUCT_ * fieldHnd = 0x00007ff8`eddcdc30, struct CORINFO_CLASS_STRUCT_ ** pTypeHnd = 0x000000b3`c5d2a2e8, struct CORINFO_CLASS_STRUCT_ * owner = 0x00000000`00000000)+0x255
clrjit!Compiler::lvaCanPromoteStructType(struct CORINFO_CLASS_STRUCT_ * typeHnd = 0x00007ff8`eddce218, struct Compiler::lvaStructPromotionInfo * StructPromotionInfo = 0x000000b3`c5d2a2b0, bool sortFields = true)+0x16c
clrjit!Compiler::lvaCanPromoteStructVar(unsigned int lclNum = <Value unavailable error>, struct Compiler::lvaStructPromotionInfo * StructPromotionInfo = 0x000000b3`c5d2a2b0)+0x4a
clrjit!Compiler::fgPromoteStructs(void)+0xce
clrjit!Compiler::fgMorph(void)+0x84
clrjit!Compiler::compCompile(void ** methodCodePtr = 0x000000b3`c5d2a7e0, unsigned long * methodCodeSize = 0x000000b3`c5d2ab80, unsigned int compileFlags = 0x102e10)+0x188


=== bunch of other threads:
ntdll!ZwWaitForSingleObject(void)+0xa
ntdll!RtlpWaitOnCriticalSection(struct _RTL_CRITICAL_SECTION * CriticalSection = 0x000000b8`ca74e5d0 Locked with contention, long Increment = <Value unavailable error>)+0xe1
ntdll!RtlpEnterCriticalSectionContended(struct _RTL_CRITICAL_SECTION * CriticalSection = 0x000000b8`ca74e5d0 Locked with contention)+0xa4
clr!UnsafeEnterCriticalSection+0x9
clr!CrstBase::SpinEnter(void)+0xa2
clr!CrstBase::Enter(void)+0x11c
clr!ListLockEntry::FinishDeadlockAwareEnter+0x15
clr!ListLockEntry::LockHolder::DeadlockAwareAcquire+0x87
clr!MethodDesc::MakeJitWorker(class COR_ILMETHOD_DECODER * ILHeader = 0x000000b8`ca76e350, unsigned long flags = 0)+0x283
clr!MethodDesc::DoPrestub(class MethodTable * pDispatchingMT = 0x00000000`00000000)+0x150b
clr!PreStubWorker(struct TransitionBlock * pTransitionBlock = 0x00000000`00000295, class MethodDesc * pMD = 0x00007ff8`eda39360)+0x3cc
clr!ThePreStub(void)+0x55
Microsoft_CodeAnalysis_CSharp!Microsoft.CodeAnalysis.CSharp.Binder.BindNamedAttributeArgument(<HRESULT 0x80004001>)+0x1d6
Microsoft_CodeAnalysis_CSharp!Microsoft.CodeAnalysis.CSharp.Binder.BindAttributeArguments(<HRESULT 0x80004001>)+0x394
Microsoft_CodeAnalysis_CSharp!Microsoft.CodeAnalysis.CSharp.Binder.BindAttributeCore(<HRESULT 0x80004001>)+0x19d
Microsoft_CodeAnalysis_CSharp!Microsoft.CodeAnalysis.CSharp.Binder.GetAttributes(<HRESULT 0x80004001>)+0x18c
Microsoft_CodeAnalysis_CSharp!Microsoft.CodeAnalysis.CSharp.Symbol.LoadAndValidateAttributes(<HRESULT 0x80004001>)+0x1be
Microsoft_CodeAnalysis_CSharp!Microsoft.CodeAnalysis.CSharp.Symbols.SourceFieldSymbol.GetAttributesBag(<HRESULT 0x80004001>)+0xd6
Microsoft_CodeAnalysis_CSharp!Microsoft.CodeAnalysis.CSharp.Symbols.SourceFieldSymbol.GetAttributes(<HRESULT 0x80004001>)+0x9
Microsoft_CodeAnalysis_CSharp!Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberFieldSymbol.ForceComplete(<HRESULT 0x80004001>)+0x96

**Comment by KirillOsenkov** [comment]
Very interesting! So it's a bug in the .NET runtime?

**Comment by VSadov** [comment]
Yes, i think CLR guys should take a look at the dump/repro

**Comment by KirillOsenkov** [comment]
@karelz do you know who would be the best person to investigate a potential deadlock in the desktop CLR Jit?

**Comment by karelz** [comment]
Looks like type loader - @gkhanna79 should be able to help.
Moving it to CoreCLR is probably best - all Runtime is there, incl. TypeSystem & JIT.

**Comment by gkhanna79** [comment]
Please assign to @kouvel who can help take a look after moving the issue to coreCLR.

**Comment by KirillOsenkov** [comment]
Filed https://github.com/dotnet/coreclr/issues/12174 and closing this one.
