### ISSUE TITLE
Branch with pipe causing issues with clones on Windows

### ISSUE THREAD

**Issue by morgoth1145** [dotnet/roslyn#20044]
**Version Used**:
Current git repo

**Steps to Reproduce**:

1. Clone roslyn repo on Windows
2. Remove "merges/master-to-features/ioperation-20170605-070016|" from ".git/packed-refs" file
3. Run "git fetch"

**Expected Behavior**:
Successful fetch

**Actual Behavior**:
error: cannot lock ref 'refs/remotes/origin/merges/master-to-features/ioperation-20170605-070016|': Unable to create 'F:/open-source-stuff/dotnet.roslyn/.git/refs/remotes/origin/merges/master-to-features/ioperation-20170605-070016|.lock': Invalid argument
From https://github.com/dotnet/roslyn
 ! [new branch]            merges/master-to-features/ioperation-20170605-070016| -> origin/merges/master-to-features/ioperation-20170605-070016|  (unable to update local ref)

**Comment by sharwell** [comment]
I deleted the offending branch.

/cc @agocke

**Comment by morgoth1145** [comment]
Fetch works fine now.  Thanks!
