### ISSUE TITLE
Allow public use of CodeActionWithNestedActions

### ISSUE THREAD

**Issue by RyanCavanaugh** [dotnet/roslyn#20049]
**Version Used**: Current master

**Steps to Reproduce**:

1. Try to instantiate `CodeActionWithNestedActions`
2. Nope, `internal`
3. 😢 

**Expected Behavior**: Should be able to create `CodeActionWithNestedActions` through either some other overload to `Create` or with `new`

**Actual Behavior**: Can't create "grouped" refactorings because there's no public way to create an instance of that class

/cc @CyrusNajmabadi

**Comment by Pilchie** [comment]
I'm okay with opening this up for 15.6.  @CyrusNajmabadi @DustinCampbell @kuhlenh any objections?

**Comment by Pilchie** [comment]
@RyanCavanaugh PS - we take PRs 😉

**Comment by DustinCampbell** [comment]
No objections from me since I had to resort to reflection in OmniSharp to proper support code actions. Without exposing this, Roslyn API consumers and code fix authors are at a disadvantage.

**Comment by CyrusNajmabadi** [comment]
We shoudl def make this available.  Though i think teh correct way to do this is to just allow CodeAction to have nested children (that's actually how the property is exposed).  I dont' think there's a need for a distinct subtype.

Also, we have to decide how we want to expose the "can my children be flattened directly into the lightbulb if there aren't that many items?" flexibility that we currently have.

**Comment by CyrusNajmabadi** [comment]
Solution: Just give IVT to ryan.  (note: not typescript.  just ryan).

**Comment by DustinCampbell** [comment]
:smile:

**Comment by sharwell** [comment]
Prioritizing this on the grounds that IDE analyzers shall not have special privileges. We either need to expose this functionality, or remove uses of this functionality within dotnet/roslyn.

**Comment by CyrusNajmabadi** [comment]
It's less of an objection and more like: the API here is really ugly.  We shouldn't expose `CodeActionWithNestedActions`.  it should just be that any CodeACtion can have nested children :)

**Comment by sharwell** [comment]
I'm thinking a new overload of `CodeAction.Create`:

```csharp
public static CodeAction Create(string title, ImmutableArray<CodeAction> nestedActions, bool isInlinable)
```

**Comment by CyrusNajmabadi** [comment]
I think that's reasonable.

**Comment by RyanCavanaugh** [comment]
🎉
