### ISSUE TITLE
ClassDeclarationSyntax.ConstraintClauses should return null if not specified.

### ISSUE THREAD

**Issue by happyhebaby** [dotnet/roslyn#20045]
**Version Used**: 1.3.2

**Steps to Reproduce**: ClassDeclarationSyntax.TypeParameterList returns null when a class doesn't have it, while ClassDeclarationSyntax.ConstraintClauses returns an empty list when it doesn't have it.

**Expected Behavior**: To make the api uniformly interfaced to meet developer's expectation. Keep the uniformity is important for api design as developers don't need to check everything from documentation and most of the time they don't. Found this out while testing my code. The latter should also return null. If this suggestion is agreed, the whole code base should be scrubbed for similar pattern. I guess it's hard to fix at this stage as it will be a breaking change. But filed it anyway just in case.

**Actual Behavior**: n/a

**Comment by jcouv** [comment]
The latter API returns a `SyntaxList` which is a struct, so it cannot be `null`. It could be default or empty, and empty seems reasonable/usable. 
On the other hand, the first API returns a `TypeParameterListSyntax` which is a class, so `null` makes sense there.

Aside from documentation, I'm not sure how to smooth those edges to make the API more friendly. Also, as you mentioned we are constrained by API compat.

**Comment by happyhebaby** [comment]
Thanks for the clarification.

On Tuesday, June 6, 2017, 9:53:29 PM PDT, Julien Couvreur <notifications@github.com> wrote:


The latter API returns a SyntaxList which is a struct, so it cannot be null. It could be default or empty, and empty seems reasonable/usable.
On the other hand, the first API returns a TypeParameterListSyntax which is a class, so null makes sense there.

Aside from documentation, I'm not sure how to smooth those edges to make the API more friendly. Also, as you mentioned we are constrained by API compat.
