### ISSUE TITLE
Expose ExpressionGenerator.GenerateExpression()

### ISSUE THREAD

**Issue by ulrichb** [dotnet/roslyn#2005]
This is a feature request to make [`ExpressionGenerator.GenerateExpression()`](https://github.com/dotnet/roslyn/blob/c8e8ad3682cd04b4159abdb9197b70bb06d4e82e/src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs#L22) public.

Our use case: We build a code transformation utility where where want to copy attribute values from an `AttributeData` instance into a syntax tree. For this we utilize `ExpressionGenerator.GenerateExpression()` using a reflection call, because it does exactly what we want (converting an attribute value into an expression syntax), and an own implementation would be quite expensive.

**Comment by Pilchie** [comment]
@mattwar does this seem like something that fits into the SyntaxGenerator?

**Comment by mattwar** [comment]
Yes, there should be something that exposes that, and the SyntaxGenerator.Attribute factory method  should be using it.

**Comment by mattwar** [comment]
You can now call SyntaxGenerator.Attribute() with the attribute data from a symbol and the correct ExpressionGenerator  API will be called.  You can also call SyntaxGenerator.TypeConstantExpression() directly, but since you only get TypeConstants from AttributeData, you probably have no need to.
