### ISSUE TITLE
MethodDeclarationSyntax.WithReturnType returns an object with Parent set

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#20064]
Per discussion in #20040, 

```csharp
MethodDeclarationSyntax method;
            method = method
                .WithReturnType(returnType) // this returns with Parent!=null
                .WithBody(updatedBody) // this returns with Parent==null
                .AddModifiers(SyntaxFactory.Token(SyntaxKind.AsyncKeyword)) // this also returns with Parent==null
```

@Pilchie suggests that `WithReturnType` divergent behavior is a bug.

**Comment by AArnott** [comment]
Actually though, what if `returnType===method.ReturnType` before the call to `WithReturnType`, such that the `WithReturnType` method can return `this`. In that case, is it legal to return an object where `Parent!=null`?

**Comment by jcouv** [comment]
FYI @gafter for triage.

**Comment by gafter** [comment]
That is the intended behavior of these With APIs - if you With a part with the value that it already has, you don't get back a new object.

@AArnott is that your scenario?

**Comment by AArnott** [comment]
I didn't test whether the returnType was actually different. I don't mind assuming so.
