### ISSUE TITLE
Roslyn doesn't select all matching identifiers when in a tuple deconstruction

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#20066]
**Version Used**: d15rel 26602.0

When the caret is on the local variable within a ValueTuple deconstruction, only that identifier instance is highlighted:
![image](https://user-images.githubusercontent.com/3548/26860668-022da1c0-4af4-11e7-8b77-e7ef5a135207.png)

But when I select the same local variable in another context, all references to that identifier (including the one in the tuple deconstruction) are highlighted:
![image](https://user-images.githubusercontent.com/3548/26860673-0b81b9a0-4af4-11e7-9371-7059574299d3.png)

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/issues/18371

**Comment by jcouv** [comment]
Filed two related issues with full details and also a similar problem with anonymous types:
https://github.com/dotnet/roslyn/issues/20115
https://github.com/dotnet/roslyn/issues/20116

I'll close this in favor of those. Thanks for reporting this @AArnott !
