### ISSUE TITLE
Tuple Bug

### ISSUE THREAD

**Issue by carloscds** [dotnet/roslyn#20071]
I'm using Visual Stdudio 17 (15.2) and when I have create a Tuple with named variables, VS shows Item1, Item2 and not correct name of variable.

I have this code:
```csharp
public class Foo
    {
        public (int ID, string Name) People() => (1, "Carlos");

        public void test()
        {
            var p = People();
        }
    } 
     
```
After Run code and stop at "var p = People()", VS shows Item1 and Item2 as variable, but correct is "ID and Name".
![vs1](https://user-images.githubusercontent.com/1697221/26875968-8592513a-4b5a-11e7-8844-5d4d2c2dc238.jpg)

Correct is show variable names, like when I put comma:
![vs2](https://user-images.githubusercontent.com/1697221/26875995-a043f3bc-4b5a-11e7-919d-7a605a00b930.jpg)

**Comment by tmat** [comment]
Could you please try with 15.3 Preview? Seems to work now:
![image](https://user-images.githubusercontent.com/41759/26894916-ae4868a2-4b74-11e7-9df5-f2ce93bcf087.png)

**Comment by carloscds** [comment]
@tmat Works fine with 15.3.

**Comment by tmat** [comment]
@carloscds Thanks for checking.
