### ISSUE TITLE
Is it possible to precompile a web application with Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace?

### ISSUE THREAD

**Issue by ranuka2** [dotnet/roslyn#20070]
I'm developing a Visual Studio 2015 extension which need to to pre compile a selected web application project and emit the output to a target location. The compiled binary will be submitted to a service for analysis. Is it possible to use Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace to achieve this? Any Rolslyn based alternatives for this?

**Comment by Pilchie** [comment]
@ranuka2 I don't know of anyone who has done this.  Generally `MSBuildWorkspace` won't know about any of the embedded code in aspx/cshtml files though, because MSBuild never processes them, so depending on your requirements it may not work.

**Comment by ranuka2** [comment]
@Pilchie Is there any Roslyn based alternative approach for this (other than using MSBuildWorkspace)?

**Comment by Pilchie** [comment]
I don't know.  Maybe somebody over at https://github.com/aspnet/Home would know?

**Comment by standerby** [comment]
Does MSBuildWorkspace still not support project-less web applications? I opened a solution today and couldn't find web applications.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of activity.
