### ISSUE TITLE
Intellisense doesn't work for "Inferred tuple names"

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/roslyn#20072]
It's possible that I'm not understanding this new feature correctly but it compiles usage of `t.a` just fine.

**Version Used**: 
VS 2017 Version 15.3 (26510.0-Preview) Preview
But I'm seeing same thing in VS for Mac after updating to Roslyn 2.3.0-beta1 nuget from nuget.org.

**Steps to Reproduce**:
Enter code below
```csharp
using System;

class MainClass
{
    public static void Main(string[] args)
    {
        var a = 1;
        var b = 2;
        var t = (a, b);
        Console.Write(t.a);
        Console.Write(t.);
    }
}
```

**Expected Behavior**:
Not show error and offer code completion.

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/774791/26876601-4caf7992-4b87-11e7-95b2-f970d1b4037a.png)

**Comment by jcouv** [comment]
Something else is going on. What do the red squiggles say? I suspect they say you need to use Language Version 7.1.

An easy way to verify that is to type `#error version` and look at the error that produces. If you are using C# 7.1, then it will look like this:
![image](https://user-images.githubusercontent.com/12466233/26890696-4ae2c0a8-4b67-11e7-8cff-ea60d9e6f41a.png)

:memo: I get proper completion:
![image](https://user-images.githubusercontent.com/12466233/26890651-25686594-4b67-11e7-98c6-992b57215944.png)

**Comment by DavidKarlas** [comment]
![image](https://user-images.githubusercontent.com/774791/26890800-28a496c8-4bb3-11e7-9445-0b502ec34d3e.png)

![image](https://user-images.githubusercontent.com/774791/26890823-3c355632-4bb3-11e7-81be-198f90972050.png)

Is it possible this was fixed in newer version?

**Comment by jcouv** [comment]
Thanks for the snapshots. Yes, the whole feature was added in a newer version than what you are using.
 
Looking at the compiler version and looking at the [source tree](https://github.com/dotnet/roslyn/blob/8f02e04893c4b53cf6ca11b064848888365914d3/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs) for that version, I can see that the inferred tuple names feature was not there yet.
I think you are using preview 1, which only includes the "default" literal feature. I think you can confirm by look at the version information in "About Visual Studio" menu.
The inferred tuple names, async Main, and reference assemblies features didn't make it to preview 1 (they are in preview 2 instead).
