### ISSUE TITLE
Adjust tests once https://github.com/dotnet/coreclr/issues/12147 is addressed

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#20083]

**Comment by AlekseyTs** [comment]
Related to https://github.com/dotnet/coreclr/issues/12147

**Comment by jcouv** [comment]
As a side note, I noticed that the CoreCLR issues are in Milestone "Future". It may be good to agree on a more specific timeline for the end-to-end feature.

**Comment by jcouv** [comment]
The linked issue https://github.com/dotnet/coreclr/issues/12147 was fixed. Removing the Blocked tag.
