### ISSUE TITLE
Feature Improve Code Actions should have states.

### ISSUE THREAD

**Issue by GrantHoffman** [dotnet/roslyn#20086]
Code action should should have a way to tell if the changes are Final.  Preferable to support multiple states.

1. Final Actions (action that should occur after a fix is applied completely)

Overriding ComputePreviewOperationsAsync is not sufficient, because ComputePreviewOperationsAsync is Called prior to make all of you changes when using FixAll for Document, Projects, or Solutions.

Additionally,  the default FixAllProvider (BatchFixAllProvider) does not work well when merging change sets.

Related StackOverflow issues: 

https://stackoverflow.com/questions/44243781/roslyn-code-action-how-to-check-if-preview-or-real-execution    

2. Function Overload for Batch states to improve caching and efficency

Code action should include overloads for handling FixAll for Document, Projects, or Solutions, this will improve caching, and improve efficiency on multidocument fixes or fixes who are dependent on other Documents.

Related StackOverflow issues: 

https://stackoverflow.com/questions/44420677/roslyn-document-changes-doesnt-fully-update-document

3. Default BatchFixProvider should have a way of telling if the changes merge appropiately, instead of showing partial changes, there is no indication that change sets could not be merged, which allow the Fix provider to apply partial or incomplete fixes, there should be some indication or even an event to manually hanndle merging

**Comment by GrantHoffman** [comment]
@Pilchie How can I get a callback after the Visual studio Suggested Action occurs.

I see there is a class:  
Microsoft.VisualStudio.LanguageServices.Implementation.Experimentation.AnalyzerVsixSuggestedActionCallback

My Issue: I'm adding resources to a Resx File but I only want to add them after the user decides the changes are final.

Do you know how I can do this?

**Comment by CyrusNajmabadi** [comment]
> My Issue: I'm adding resources to a Resx File but I only want to add them after the user decides the changes are final.

What do you mean by "the changes are final"?   It's unclear to me why you can't make the change in GetOperationsAsync and have that just work.

**Comment by CyrusNajmabadi** [comment]
> Default BatchFixProvider should have a way of telling if the changes merge appropiately, instead of showing partial changes, there is no indication that change sets could not be merged, which allow the Fix provider to apply partial or incomplete fixes, there should be some indication or even an event to manually hanndle merging

The default BatchFixProvider is a singleton.  So there would be no way to have it provide customized behavior.  The recommendation is that you provide your own FixProvider if you have complex behavior (like edits that will overlap each other).

**Comment by CyrusNajmabadi** [comment]
> How can I get a callback after the Visual studio Suggested Action occurs.

Create your own CodeActoinOperation.  We will call "Apply" on it when the action occurs.  So, at the end of Apply, it will be after the suggested action occurs.

**Comment by CyrusNajmabadi** [comment]
> The recommendation is that you provide your own FixProvider 

Note: we could consider exposing some sort of helper subclass of FixProvider that does all the parallelizing, but otherwise makes you responsible for all the editing.  But doing that parallel application isn't that hard to do, so i don't thnk we'd be providing a huge amount of value there.

**Comment by GrantHoffman** [comment]
> What do you mean by "the changes are final"? It's unclear to me why you can't make the change in GetOperationsAsync and have that just work.

How can I make a change in GetOperationsAsync it is not a virtual method? 
If you're referring to ComputeOperationsAsync/ComputePreviewOperationsAsync? 
When you are using a FixAllScope,  other than instance (Document, Project, Solution).
 Both of these methods are called before the changes are actually final,  Since I am writing to a resource file,  Roslyn does not roll back the changes, because they're not made to the current document.

**Comment by GrantHoffman** [comment]
As for the Batch Fix Provider,  When I'm using the document editor, and I add a member, the Batch Fix Provider seems to not be able to merge the changes, because the diagnostic spans are overlapping.  Even though they shouldn't be.  Perhaps the events should be on the code action overloaded for how it handle FixAllScope.    

The Batch Fix provider can check if the Code Action Implements an interface for these events before calling it's default merging strategy.   If it does you can avoid calling the default merging strategy because the user has overload a way for handling multiple diagonistic in the code action.

**Comment by GrantHoffman** [comment]
How do I use a code action operation? to be more specific what consumes the code action operation? a code action/ fix provider?

**Comment by GrantHoffman** [comment]
I tried your suggestion and created a CodeActionOperation, however my apply function is never called.

    public class DelayedApplyChangesOperation : CodeActionOperation
    {
        public override void Apply(Workspace workspace, CancellationToken cancellationToken)
        {
            using (var file = new System.IO.StreamWriter("c:\\temp\\test.txt"))
            {
                file.WriteLine("Lines and Stuff");
            }

            Debug.WriteLine("Test Execution");
        }
    }

        protected override async Task<IEnumerable<CodeActionOperation>> ComputePreviewOperationsAsync(CancellationToken cancellationToken)
        {
            const bool isPreview = true;
            // Content copied from http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeActions/CodeAction.cs,81b0a0866b894b0e,references
            var changedSolution = await this.GetChangedSolutionWithPreviewAsync(cancellationToken, isPreview).ConfigureAwait(false);
            if (changedSolution == null)
            {
                return null;
            }

            return new CodeActionOperation[] { new ApplyChangesOperation(changedSolution), new DelayedApplyChangesOperation() };
        }

**Comment by CyrusNajmabadi** [comment]
> Since I am writing to a resource file, Roslyn does not roll back the changes

I don't think you'll be able to preview in this case.  Your preview will just have to be something like a string that just says that you're going to be updating the file.  Roslyn has no general facility for allowing application/rollback of arbitrary actions.

Actually, roslyn has no facility for rollback at all.  All we do is apply changes, and allow VS's undo mechanism to undo things.  if you want undo to work, you'll have to register your own undo actions as well.  I can help you out with that.

**Comment by CyrusNajmabadi** [comment]
> As for the Batch Fix Provider, When I'm using the document editor, and I add a member, the Batch Fix Provider seems to not be able to merge the changes, because the diagnostic spans are overlapping

Hrmm.. do you have an example of that?

**Comment by CyrusNajmabadi** [comment]
> The Batch Fix provider can check if the Code Action Implements an interface for these events before calling it's default merging strategy. If it does you can avoid calling the default merging strategy because the user has overload a way for handling multiple diagonistic in the code action.

I'm not sure how that would actually work.  There will be many CodeActions being applied, it's not clear which one we ask.  We could potentially as the CodeFixProvider if it wants to resolve the issue though.

**Comment by CyrusNajmabadi** [comment]
> I tried your suggestion and created a CodeActionOperation, however my apply function is never called.

Yes.  We don't call into this during Preview.  Only during final application.

**Comment by GrantHoffman** [comment]
@CyrusNajmabadi,  It seems I need a call back to occur when the changes are final, is there a way I can create an event or callback for when   if there isn't a way to tell when the changes are finalized,  Is there a way I can create a callback for when the undo action is called

**Comment by CyrusNajmabadi** [comment]
> It seems I need a call back to occur when the changes are final,

Can you clairfy what you mean by "are final"?  It sounds like what you're asking for is a way to know then changes are actually being applied o the workspace.  And that is already available through "CodeActionOperation.TryApply".

> Is there a way I can create a callback for when the undo action is called.

To do this, you will have to register an undo operation with VS.  Roslyn does not have a generalized undo/redo engine to plug into.

> Also, shouldn't these events be built in can we get a feature request for this?

Could you be specific.  What exactly are you asking for?

**Comment by GrantHoffman** [comment]
@CyrusNajmabadi,  what I am looking for is an event that occurs, when the user decided the changes are final.

When you click the Solution Button under code action the changes are precalcuated and technically applied, but in a sense the changes are not final, because if you were to hit the cancel button all of the undo actions would be called.

However, if you decide to hit apply then, the changes would be final and nothing would happen.
There should be an even when a user hit apply, because that's when things are actually truly final.  

Registering a undo action is a current work around, but Ideally if there was an event for when these changes occured, I just beable to do my changes then, Perhaps control Z wouldn't revert all of my changes but atleast I would have a relyable event to use,  instead of having to code for the edge case. 

What if this is a preview? What they are calling the code from the solution now I have to register an undo action.  All of this would be solved with an event that occurs when the user actually is done.

If this is not clear I can post pictures

**Comment by CyrusNajmabadi** [comment]
Why is CodeActionOperatoin.TryApplyChanges not suitable for this?  Thanks!

**Comment by CyrusNajmabadi** [comment]
@GrantHoffman Can you please help out here?  Thanks!

**Comment by GrantHoffman** [comment]
TryApplyChanges will not help anything.  

I'm modifying a Resx File to add a const as a key in a resx File.
As you said before
When Clicking Calculate Changes for the Solution this PreCalculates the Changes for the entire solution.  Meaning that All of my Consts will now be added as keys to the RESX File.
When I click Cancel, the solution rolls back the changes.
Yet it ignores the changes that were written to the resx file.  

We need an event which signals the finalization of Changes.

**Comment by CyrusNajmabadi** [comment]
I think the appropriate way to handle this would be to just have a few fixes "add to resx" and "add to resx and update solution".  You have different codeactions (or code action operations) for each.  You only actually make the cahnge in TryApplyChanges.  For the preview you don't do anything.

Would that work?

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of information.
