### ISSUE TITLE
IDE stop responding completely while a big C# file was edited.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#20094]
I edited a big C# file. IDE got slower and slower to respond. Eventually it stopped responding at all, I had to kill the process. I captured a dump before killing the process, it is available upon request.

CC @Pilchie

**Comment by Pilchie** [comment]
@sharwell Can you take a look?

**Comment by sharwell** [comment]
@AlekseyTs Do you have the Roslyn Syntax Visualizer window open?

**Comment by AlekseyTs** [comment]
> Do you have the Roslyn Syntax Visualizer window open?

I didn't open it explicitly.

**Comment by sharwell** [comment]
@AlekseyTs Was this the same process as the one you filed for #20093, or different? From my investigation of #20093, it was only a matter of time before that process crashed, so I'm hoping to avoid the long separate analysis of this heap dump.

**Comment by AlekseyTs** [comment]
It is possible that it was the same process, but later in time. I do not remember for sure. This wasn't a crash, however, it looked like a dead-lock in IDE. Might be a different issue.

**Comment by sharwell** [comment]
It appears to at minimum have been impacted by the other issue. For now I'm going to close this as a duplicate. If it reappears, the other changes we've made will reduce the "noise" in the crash dump and hopefully allow us to track down whatever remaining issue could cause it.
