### ISSUE TITLE
Plz make C# Scratch version

### ISSUE THREAD

**Issue by KorenX** [dotnet/roslyn#20104]
**Version Used**: 
Idk rly

**Steps to Reproduce**:
1.  Make
2.  C#
3.  Scratch version

**Expected Behavior**:
Program C#, but without coding. Maybe an interactive software make online.

**Actual Behavior**:
Program C#. But with coding.

**Comment by KorenX** [comment]
☺

**Comment by miloush** [comment]
http://baltie.cz/en/whatisbaltie.asp

**Comment by Pilchie** [comment]
This isn't something that we'll tackle as part of this repo, but people are welcome to use the code here to try something on their own.
