### ISSUE TITLE
The given expression is never of the provided type when pattern matching is used

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#20103]
**Version Used**: 2.3.0.61719 (5fbdd5c5)

**Steps to Reproduce**:

```csharp
class C
{
	static object Test ()
	{
		const object o = null;
		return o is object res; // Removing unused res shows the warning
	}

	static void Main ()
	{
	}
}
```

**Expected Behavior**:

`warning CS0184: The given expression is never of the provided ('object') type` is issued or even CS8121 error to be consistent with other pattern matching checks.

**Actual Behavior**:

No warning CS0184

**Comment by jaredpar** [comment]
FYI @gafter

**Comment by gafter** [comment]
This is somewhat intentional, though I agree it is odd. I would treat it as a feature request.

**Comment by jaredpar** [comment]
Why is it intentional?

**Comment by gafter** [comment]
The rule is that we use the expression's *type* (not its value) to determine if a pattern-matching operation is "impossible", and we give an error on those instead of a warning.  Having said that, a warning here is reasonable and worth adding.

**Comment by gafter** [comment]
I will note that in a `switch`, the value of the switch expression, if constant, affects reachability (i.e. warnings).

**Comment by gafter** [comment]
This is now fixed in master. The warning now appears with or without the identifier after the type.
