### ISSUE TITLE
Short-hand "object-literal" syntax for anonymous objects

### ISSUE THREAD

**Issue by MrMatthewLayton** [dotnet/roslyn#20102]
Currently when we want to declare an anonymous type we do:

```
var foo = new { bar = 123 };
```

What I would like to see (just the omission of `new`):

```
var foo = { bar = 123; }
```

Or, bring anonymous object / "object-literal" syntax in line with Javascript:

```
var foo = { bar: 123 };
```

Rationale

- It looks cleaner
- It would improve readability of objects being serialized/deserialized to JSON
- Code formatting would look cleaner too; for example:
```
return Ok({
    foo: "Hello World",
    bar: 123
});
```

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
