### ISSUE TITLE
Utilise NameOf 

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#2011]
I currently manually going through the VB code of Roslyn to find the locations where we can utilise the `NameOf' operator, rather than explicitly writing them inside of a string literal. 

[Branch: NameOf](https://github.com/AdamSpeight2008/roslyn-AdamSpeight2008/tree/NameOf)

So of these utilises may/ may not have been with commits of #1879.

I you find any location that could no with updating let me know and I'll include it.
Currently I'm upto the `\BoundTree` folder.

**Comment by gafter** [comment]
I'm going to close this issue as it does not track any work we are planning to do.
