### ISSUE TITLE
Adding items to a Getter Only List Property should throw an exception

### ISSUE THREAD

**Issue by cullen-tsering** [dotnet/roslyn#20113]
**Version Used**:  .NET Framework 4.6.01590

**Steps to Reproduce**:

1. Given the following code
```c#
void Main()
{
	try
	{
		var someObjectB = new SomeClassB();
		someObjectB.SomeClassAIds.Add(10);
		Console.WriteLine("List count is {0}", someObjectB.SomeClassAIds.Count);
	}
	catch (Exception ex)
	{
		Console.WriteLine(ex);
	}
	
}

public class SomeClassA
{
   public int Id { get; set; }
   public string Name { get; set; }
}

public class SomeClassB
{
   public List<SomeClassA> SomeClassAList { get; set; } = new List<SomeClassA>();
   public List<int> SomeClassAIds => SomeClassAList?.Select(m=>m.Id).ToList();
}
```
**Expected Behavior**:
I was expecting the following line to throw an exeption:
		someObjectA.SomeClassAIds.Add(10);

**Actual Behavior**: 
The code executed without error while nothing was added to the list.

**Proposed Change**: 
In this case, knowing SomeClassAIds is a getter only property, have it throw an exception

**Comment by cullen-tsering** [comment]
The primary motivations is for code maintainability: 
First, the result is totally contrary to what the method is expected to do;  the method Add should add it or throw an exception when it cannot add it to the list;
Secondly, devs who are not familiar with the existing codebase can introduce changes and believe it works;  In worst case scenario, this leaks to production and wreak havoc.

**Comment by Pilchie** [comment]
This isn't a request for a change to either  the language, the compiler, or the tooling.  The only way for something like this to happen would be for List to somehow know that it's a temporary and throw, but it has no way to know that. 

Instead, I would structure your code differently:

```C#
public class SomeClassB
{
   public List<SomeClassA> SomeClassAList { get; set; } = new List<SomeClassA>();
   public IList<int> SomeClassAIds => SomeClassAList?.Select(m=>m.Id).ToList().AsReadOnly();
}
```

Or look into using some immutable collections directly, from the System.Collections.Immutable nuget package.

**Comment by cullen-tsering** [comment]
@Pilchie First of all, thanks for comments and the solution that can be used to get out of this situation! 
 The point of this issue is not that I lack solution to handle this kind of situation but to point out a problem which is the compiler does not issue an error or even a warning in this context.  List.Add internally does array coping when it has to increase its capacity, which is expansive, that is if it indeed goes through the motion of adding.  

And agree the list doesn't have that knowledge.  However the compiler possesses the knowledge from the code context, which in this case is how SomeClassB defines a getter only property.  Does this not sound like a responsibility that lies with the compiler, no?  

May be this is better handled by external tools like ReSharper?

**Comment by Pilchie** [comment]
The compiler can't (in general), tell that the returned collection is a temporary and not a field.  If it was a field, you could add to it with no problem.  It could (maybe) warn in the subset of cases where it can tell that it's a temporary, but that would be pretty rare.

(Even in your example, there is no guarantee that the implementation of `ToList()` that gets called doesn't stash the list in a static somewhere that other people rely on.  Just because people *shouldn't* write code like that, doesn't mean that they don't)

**Comment by Pilchie** [comment]
Tagging @jaredpar for the compiler perspective too.
