### ISSUE TITLE
IOperation API support for BoundDynamicObjectCreationExpression

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#20119]
This has similar design aspect as https://github.com/dotnet/roslyn/issues/20114#issue-234640941. BoundDynamicObjectCreationExpression is very similar to BoundObjectCreationExpression, except that we do not have a single bound constructor, but instead a method group of applicable constructors. We can either reuse IObjectCreationExpression with null Constructor and expose a MethodGroup of applicable methods or introduce a new IDynamicObjectCreationExpression as follows:

```
    public interface IDynamicObjectCreationExpression : IHasArgumentsExpression
    {
        /// <summary>
        /// Applicable methods.
        /// </summary>
        ImmutableArray<IMethodSymbol> ApplicableMethods { get; }
        /// <summary>
        /// List of member or collection initializer expressions in the object initializer, if any.
        /// </summary>
        ImmutableArray<IOperation> Initializers { get; }
    }
```

**Comment by mavasani** [comment]
@jinujoseph Another API to discuss today. We should try to cover all DynamicXXX related expressions.

**Comment by jinujoseph** [comment]
**Design Team Decision**

Decision was to create a common IDynamicHasArgumentsExpression.. and then each of the dynamic invocation, object creation and indexer access will derive from it.  Which should have list of applicable symbols, the name as string (in case we find no applicable symbols) and other props.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/20962
