### ISSUE TITLE
LSL: P2P references from legacy project to CPS projects are dropped in ASL

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#20128]
**Version Used**: 
Dev15.3 Preview 

**Steps to Reproduce**:

1. Enable Lightweight solution load.
2. Open Roslyn and wait for the solution to index and load fully.
3. Close and re-open.
4. Open a file from a legacy project system project (like VisualStudioProjectTracker.cs).

**Expected Behavior**:
P2P refs to CPS projects (like CodeAnalysis) work.

**Actual Behavior**:
They don't, leading to a poor IntelliSense experience.

**Notes**:
This is happening because the Roslyn LSL code subscribes to OnAfterOpenSolution, but in the second load, the CPS projects are created during ASL, which means that they don't exist, and so LSL never hooks them up.  A potential fix would be to move Roslyn LSL code to OnAfterBackgroundSolutionLoadComplete.

**Comment by MattGertz** [comment]
Mondo escrow triage:  meets the bar.

**Comment by Pilchie** [comment]
This turns out to be a non-issue after all.  The two cases that I could think of are deferred projects that reference non-deferred projects, either:
1. During solution load, when one will never be deferred (like a CPS project).  This ends up working because when the deferred project is created, it fails to find the project to add a P2P for, and adds a metadata ref instead.  Then, when the CPS project is created, `TryProjectConversionForIntroducedOutputPath` is called, which finds the projects that have metadata references and promotes them to P2P refs.
2. If a P2P ref is created between two deferred projects, and later the lower level one is loaded for real, it works because we never remove the P2P ref from the still deferred project, and the newly created non-deferred project will have the same projectid, so the connection is maintained.

Nothing to do here after all.
