### ISSUE TITLE
IOperation API shape for BoundDynamicIndexerAccess

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#20122]
Same design issue as other BoundDynamicXXX nodes. We can either reuse IIndexedPropertyReferenceExpression or define a new IDynamicIndexedPropertyReferenceExpression with a set of applicable indexers.

```
    public interface IDynamicPropertyReferenceExpression : IMemberReferenceExpression
    {
        ImmutableArray<IPropertySymbol> ApplicableProperties { get; }
    }

    public interface IDynamicIndexedPropertyReferenceExpression : IDynamicPropertyReferenceExpression, IHasArgumentsExpression
    {
    }
```

**Comment by mavasani** [comment]
@jinujoseph another issue to discuss today

**Comment by jinujoseph** [comment]
**Design Team Decision**

We should first look at API design for IIndexer first , then transition to dynamic indexer.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/21711
