### ISSUE TITLE
Feature request: allow anonymous types to be used as return types and generic arguments

### ISSUE THREAD

**Issue by madelson** [dotnet/roslyn#20136]
With C# 7, we can now use named tuples as method return types and generic arguments, which is great. However, these limitations are still imposed for anonymous types. 

I propose that we should allow for "naming" anonymous types in these contexts. For example:

```
// anonymous types are still internal; so they wouldn't
// be able to appear in public signatures of public classes
internal { int A, string B } Foo()
{
    var list = new List<{ int A, string B }>();
     // do stuff
    return list.First();
}
```

Why should this be added when we can already do this via tuples? I see two main reasons:

* Reflection-based APIs: because tuple property names aren't accessible via reflection, we can't do:
```
JsonConvert.DeserializeObject<(int A, string B)>("{ A: 2, B: 'a' }");
```
This is frustrating because this kind of syntax would be ideal for many cases (deserialization, mapping SQL queries back to ad-hoc objects). We have a workaround today of using type inference:
```
JsonConvert.DeserializeAnonymousType("{A: 2, B: 'a' }", new { A = default(int), B = default(string) })
```
My experience, however, has been that many developers find this confusing.

* Consistency: anonymous types are very similar to tuples: being able to use them in similar ways seems like it rounds out a jagged edge in the language rather than bloating it with yet another thing to learn.

**Comment by ufcpp** [comment]
dup of https://github.com/dotnet/roslyn/issues/8404, https://github.com/dotnet/csharplang/issues/668
And language feature proposals are moved to dotnet/csharplang.

**Comment by jcouv** [comment]
I'll go ahead and close this issue as dupe (@ufcpp pointed out the existing discussions for this in csharplang repo).
Thanks
