### ISSUE TITLE
Inconsistent CS0433 and CS8179

### ISSUE THREAD

**Issue by m0sa** [dotnet/roslyn#20135]
**Version Used**:  2.2.0

**Steps to Reproduce**:

If you somehow end up with a `net47` `mscorlib` and a `System.ValueTuple` dll from the nuget package in a compilation, the results are very confusing, and not clear what's wrong. Here's a minimal repro case  as a LinqPad script:

```
<Query Kind="Program">
  <NuGetReference>Microsoft.CodeAnalysis.CSharp</NuGetReference>
  <NuGetReference>System.ValueTuple</NuGetReference>
  <Namespace>Microsoft.CodeAnalysis</Namespace>
  <Namespace>Microsoft.CodeAnalysis.CSharp</Namespace>
</Query>

void Main()
{
	CSharpCompilation
		.Create("Test")
		.AddReferences(
			new[]
			{
				typeof(object).Assembly.Location,
				Util.GetFullPath("System.ValueTuple.dll"),
			}.Select(x => MetadataReference.CreateFromFile(x)).ToArray())
		.WithOptions(new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
		.AddSyntaxTrees(
			SyntaxFactory.ParseSyntaxTree(@"
				using System;
				public class Lib
				{
					(string str, int x) Test1() => throw new Exception();
					
					ValueTuple<string, int> Test2() => throw new Exception();
				}
			"))
		.GetDiagnostics()
		.Dump();
}
```

**Actual Behavior**:
```
(5,6): error CS8137: Cannot define a class or member that utilizes tuples because the compiler required type 'System.Runtime.CompilerServices.TupleElementNamesAttribute' cannot be found. Are you missing a reference? 
(5,6): error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported 
(7,6): error CS0433: The type 'ValueTuple<T1, T2>' exists in both 'System.ValueTuple, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' 
```

**Expected Behavior**:
I'd like to see one of the following two options for the lines with Test1 and Test2;
- both should get the same `Diagnostic`, `CS0433` seems more appropriate
- compilation defaults to the `mscorlib` version of the `System.ValueTuple` and succeeds

**Background**
I've hit this while writing a roslyn view engine for mvc 5 (it's actually more a bug of the `BuildManager.GetReferencedAssemblies()`, because it doesn't respect the target framework). So even thought the target framework was `net462`, one can end up running on the `net47` runtime, with the `System.ValueTuple` dll from the package picked up by `BuildManager` from `/bin` due to the default `<system.web><compilation><assemblies><add name="*">` directive. More details [here](https://github.com/StackExchange/StackExchange.Precompilation/blob/45739289eeee248aca64cdc27c3d2105a947fabe/StackExchange.Precompilation/Hacks.cs#L28) and here: https://github.com/StackExchange/StackExchange.Precompilation/issues/28

**Comment by jcouv** [comment]
@m0sa Thanks for the detailed repro.
Unfortunately, constraints in the implementation will make it quite hard to unify those error messages.
FYI I just made a [change](https://github.com/dotnet/roslyn/pull/20112) to the 8179 error message, since it could occur when the ValueTuple type is ambiguous (imported twice).


As for the specific issue you mention about targeting net46 then running on a machine with net47 is known and unfortunately will only be fixed in the next version of desktop framework. 
There is a [workaround](https://github.com/dotnet/roslyn/pull/17192) when trying to use compiler APIs in such a situation, but I don't think ASP.NET took that fix. You could file an issue with that team/repo.

**Comment by m0sa** [comment]
Thanks for the links. The changed error message makes sense now for the case I've hit. Unfortunately the APIs you pointed me to are internal, though. Are there any plans to make them public?

**Comment by jnm2** [comment]
Just ran into this while using LINQPad with the NuGet package BenchmarkDotNet.

**Comment by jnm2** [comment]
Just ran into this while using LINQPad with the NuGet package BenchmarkDotNet.

Tuple syntax is highlighted with:

> CS8179 Predefined type 'System.ValueTuple`2' is not defined or imported

On a hunch I typed `ValueTuple` and it is highlighted with:

> CS0433 The type 'ValueTuple' exists in both 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by jnm2** [comment]
Slightly off topic- is excluding the System.ValueTuple assembly from the BenchmarkDotNet NuGet package something LINQPad has the information do to automatically when running queries on net47?

In other words, I expect this to be automatically resolved in tools other than VS. Is that a correct expectation?

**Comment by jnm2** [comment]
Never mind, it appears that VS doesn't handle this situation either. In fact it's worse because at lease LINQPad lets me exclude a single assembly from being referenced in the NuGet package.

**Comment by jcouv** [comment]
@m0sa Regarding the internal API: after re-reading the issue, the problem you run into is actually simpler than the one I had in mind. We do not recommend you use the internal API for this case, you should only reference ValueTuple once.
The latest ValueTuple package (4.4 currently in pre-release) is aware of `net47` and handles type-forwarding.
Let me know if that makes sense.

**Comment by jcouv** [comment]
@m0sa 
This should be fixed by updating to latest ValueTuple package.
Since I didn't hear a confirmation from you for a while, I will close this issue. Please re-open if that did not solve the problem.
