### ISSUE TITLE
Interlocked.Increment on volatile field does not produce warning as in VS2013

### ISSUE THREAD

**Issue by Vlad5Maxed** [dotnet/roslyn#2013]
This code produces warning in VS2013 but not in VS2015. Not sure is this is bug.
public static class Something
    {
        private static volatile int currentValue;

        public static int GetUniqueValue()
        {
            return Interlocked.Increment(ref currentValue);
        }
}
VS2013 message:
a reference to a volatile field will not be treated as volatile

**Comment by mikedn** [comment]
It looks like the warning is generated for methods other than Interlocked.X. In this case this isn't a bug, it's a fix as the warning isn't necessary in the case of Interlocked, volatile is implied by those methods.

**Comment by Vlad5Maxed** [comment]
Do you mean that for Interlocked it is no longer generates this warning but for other methods it still generates warning? Sorry I don't have access to VS2015 to check.

**Comment by mikedn** [comment]
Yes, for other methods the warning is still generated. Interlocked was special cased:

https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs#L39

**Comment by VSadov** [comment]
The change was done on purpose. The point of the warning is to remind that references do not track whether the referent is volatile. Accessing the field through the reference will not have same memory ordering guarantees. 
On the other hand Interlocked methods have ordering guarantees which are same or stronger than provided by volatile, so warning is unnecessary. Using volatile fields through interlocked methods is common enough that compiler makes it a special case.

**Comment by Vlad5Maxed** [comment]
Thank you guys.
