### ISSUE TITLE
Redundant work in data flow analysis

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#20143]
PR https://github.com/dotnet/roslyn/pull/20004 contains redundant work around checking whether we're in a local function and whether or not we've captured a variable within that local function:

https://github.com/dotnet/roslyn/pull/20004/files#diff-cbdf5016ee7e0a00f12e386f9a3bc188R916

This could be cleaned up to prevent checking if we're in a local function twice.

**Comment by jaredpar** [comment]
Is this a bug, feature request, etc ...?  Please add the appropriate label to classify this issue.

**Comment by agocke** [comment]
This bug is no longer valid. Closing
