### ISSUE TITLE
Inconsistent error messages with nullable types in a type pattern with identifier

### ISSUE THREAD

**Issue by Blue0500** [dotnet/roslyn#20156]
**Steps to Reproduce**:
```
object obj = 4;

bool correct = obj is Nullable<int> num1;
// CS8116 : It is not legal to use nullable type 'int?' int a pattern; use the underlying type 'int' instead.

bool incorrect = obj is int? num2;
// CS1003 : Syntax error, ':' expected
// CS1525 : Invalid expression term ';' 
// CS0103 : The name 'num2' does not exist in the current context.
```

**Expected Behavior**:
Trying to use either `Nullable<int>` or `int?` in a type pattern with an identifier should result in CS8116 explaining that nullable types can't be used.

**Actual Behavior**:
Instead, using `int?` results in CS1003, CS1525, and CS0103, while using `Nullable<int>` correctly results in CS8116

**Comment by jcouv** [comment]
@Blue0500 Thanks for reporting this. 

I believe the behavior you observe is by-design. It results from precedence rules in parsing to disambiguate the language.
When you are typing `obj is int? num2`, you might be trying to type `(obj is int) ? num2 : num3`.
The compiler prefers the latter parsing interpretation ([more details](https://github.com/dotnet/roslyn/issues/10492)).

FYI @gafter in case anything to add.

**Comment by gafter** [comment]
The nullable type is not permitted in a type pattern, which is why the parser disambiguates this way.
