### ISSUE TITLE
NuGet packages should use open source licenses

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#20169]
Currently, NuGet packages like [`Microsoft.Net.Compilers`](https://www.nuget.org/packages/Microsoft.Net.Compilers/) or [`Microsoft.CodeAnalysis.CSharp`](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/) are licensed under licenses like "MICROSOFT .NET LIBRARY (INSTALL AND USE)" or "MICROSOFT .NET LIBRARY", where the former even prohibits redistribution. I think this is contrary to the spirit of open source, and that the NuGet packages should use the same license as their source code (in this case, the Apache License).

A similar issue has been recently resolved for .Net Core packages at https://github.com/dotnet/corefx/issues/12190.

This issue was created in response to [this SO question](https://stackoverflow.com/q/44498084/41071).

**Comment by jasonmalinowski** [comment]
Assigning to me while I chat with @richlander and @terrajobst. There's already a conversation with the lawyers we can piggy back on I think.

**Comment by tmat** [comment]
tagging myself @tmat

**Comment by gafter** [comment]
@agocke suggested

> The portable license we use for our libraries (Microsoft.CodeAnalysis*.dll) is here: https://www.microsoft.com/net/dotnet_library_license.htm
> 
> And we define the redist and non-redist licenses in NuGet pack here: 
> 
> https://github.com/dotnet/roslyn/blob/da60463e987dd0263e5d4584be7ea61e3da428df/src/NuGet/NuGetProjectPackUtil.csproj#L29
> 
> In theory the only work would be changing the lines in the Microsoft.NET.Compilers.nuspec and Microsoft.NETCore.Compilers.nuspec files from nonRedist to redist here:
> 
> https://github.com/dotnet/roslyn/blob/da60463e987dd0263e5d4584be7ea61e3da428df/src/NuGet/Microsoft.Net.Compilers.nuspec#L22

**Comment by svick** [comment]
@gafter Making sure all packages use the redistributable version of the "MICROSOFT .NET LIBRARY" license would be an improvement. But I still think it would be best if the packages used an open source license (presumably Apache, just like the source code).

Is that not an option, at least for some Roslyn packages?

**Comment by gafter** [comment]
I found the following non-redistributable packages in Roslyn/src/NuGet:

``` none
./Microsoft.CodeAnalysis.Compilers.nuspec:26:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
./Microsoft.CodeAnalysis.EditorFeatures.Wpf.nuspec:26:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
./Microsoft.CodeAnalysis.Remote.Razor.ServiceHub.nuspec:26:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
./Microsoft.Net.Compilers.nuspec:22:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
./Microsoft.Net.CSharp.Interactive.netcore.nuspec:22:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
./Microsoft.NETCore.Compilers.nuspec:19:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
./Microsoft.VisualStudio.IntegrationTest.Utilities.nuspec:19:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
./Microsoft.VisualStudio.LanguageServices.nuspec:26:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
./Microsoft.VisualStudio.LanguageServices.Razor.RemoteClient.nuspec:26:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
```

**Comment by gafter** [comment]
The following the ones I am changing to a redistributable license for now:

``` none
./Microsoft.CodeAnalysis.Compilers.nuspec:26:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
./Microsoft.Net.Compilers.nuspec:22:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
./Microsoft.NETCore.Compilers.nuspec:19:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
```

The following remain open issues and I will need to consult with others to determine if we should be changing the license:

``` none
./Microsoft.CodeAnalysis.EditorFeatures.Wpf.nuspec:26:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
./Microsoft.CodeAnalysis.Remote.Razor.ServiceHub.nuspec:26:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
./Microsoft.Net.CSharp.Interactive.netcore.nuspec:22:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
./Microsoft.VisualStudio.IntegrationTest.Utilities.nuspec:19:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
./Microsoft.VisualStudio.LanguageServices.nuspec:26:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
./Microsoft.VisualStudio.LanguageServices.Razor.RemoteClient.nuspec:26:    <licenseUrl>$licenseUrlNonRedist$</licenseUrl>
```

**Comment by gafter** [comment]
@DustinCampbell had confirmed that the licenses on the other six packages are correct.
