### ISSUE TITLE
Regions Text mishandles newlines.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#20163]
**Version Used**: 
`VS2017 Preview`
`Visual Basic 2017 - 00369-60000-00001-AA005`

```vbnet
Module Module1
#Region ""
    Sub Main()

    End Sub
#End Region

End Module
```
**Steps to Reproduce**:

1.  Place caret inbetween quotation marks.
2.  Press Enter / Return.
3. Code should look this

```vbnet
Module Module1
#Region "
"
    Sub Main()

    End Sub
#End Region

End Module
```
**Actual Behavior**:
![vs2017preview_issue01](https://user-images.githubusercontent.com/900107/27011672-9c0b816e-4eb8-11e7-8d0d-ac7d938e7d7a.png)

It also results in 4 errors being reported.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	BC30681	'#Region' statement must end with a matching '#End Region'.	\ConsoleApp1\Module1.vb	2	Active
Error	BC30625	'Module' statement must end with a matching 'End Module'.	\ConsoleApp1\Module1.vb	1	Active
Error	BC30648	String constants must end with a double quote.	\ConsoleApp1\Module1.vb	2	Active
Error	BC30648	String constants must end with a double quote.	\ConsoleApp1\Module1.vb	3	Active

```

**Expected Behavior**:

Parse the string within the region text just like the other string literals in source, by allowing newlines to be parsed. Then report error during binding. This should prevent the cascaded errors. 
Notice if you remove the second quotation mark the subsequent code is parse and coloured correctly, producing only the single error.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	BC30648	String constants must end with a double quote.	\ConsoleApp1\Module1.vb	2	Active

```

**Comment by Pilchie** [comment]
This is actually a question about parsing of strings in `#Region`, and whether multi-line strings should be allowed there.

**Comment by AdamSpeight2008** [comment]
@Pilchie  More of parsing them as if multi-line strings are allowed. (Even if there not.)
