### ISSUE TITLE
New Refactoring Request: auto-property to property with backing field

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#20160]
It would be really nice if I could right-click on an auto-property and select:
Quick Actions & Refactorings > Convert to Standard Property

This would convert a line of code FROM:
public long TemplateId {get; set;} = 0;

TO:

private long __TemplateId = 0;
public long TemplateId {
get {
return __TemplateId;
}
set {
__TemplateId = value;
}
}

**Comment by Pilchie** [comment]
Hmm - we've been talking about implementing this, and I believe @chborl was planning on doing it soon, but I can't find an issue where we were tracking it, so thanks for filing.

**Comment by Pilchie** [comment]
Found it - #18267
