### ISSUE TITLE
Conversion Expressions for Invalid Nodes

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#20175]
Consider the following _invalid_ C# code:
```C#
using System;

class Program
{
    static void Main(string[] args)
    {
        int i1 = ;
    }
}
```
We currently get the following operation tree for `i1 = ;`:
```
IVariableDeclarationStatement (1 declarations) (OperationKind.VariableDeclarationStatement, IsInvalid) (Syntax: 'int /*<bind ... *</bind>*/;')
  IVariableDeclaration (1 variables) (OperationKind.VariableDeclaration, IsInvalid) (Syntax: 'int /*<bind ... *</bind>*/;')
    Variables: Local_1: System.Int32 i1
    Initializer: IConversionExpression (ConversionKind.Invalid, Implicit) (OperationKind.ConversionExpression, Type: System.Int32, IsInvalid) (Syntax: '')
        IInvalidExpression (OperationKind.InvalidExpression, Type: ?, IsInvalid) (Syntax: '')
```

There is an empty IdentifierNodeSyntax there, and the semantic model exposes a Type and ConvertedType of `null` there. Should we be removing the conversion expression here to match the semantic model, or should we be leaving it in? Thoughts, @dotnet/analyzer-ioperation @AlekseyTs?

**Comment by CyrusNajmabadi** [comment]
Seems surprising and unhelpful to have this conversion there (IMO).

**Comment by AlekseyTs** [comment]
Seems fine to me, given that this is an error scenario.

**Comment by 333fred** [comment]
I can certainly see why the conversion expression is introduced, but I'm not sure that we should be exposing it globally. It disagrees with what the semantic model says about that node, which we've tried to match in other places. It also seems to me like this is an implementation detail of roslyn, that it needs to introduce a conversion for an invalid expression.

**Comment by 333fred** [comment]
*Design-Team*:
We'd like to see how the semantic model handles these situations. Does it special case this in particular, or does it also manage to special case something like this:
```C#
class Program
{
    static void Main(string[] args)
    {
        int i1 = a + b;
    }
}
```
Where `a` and `b` are undefined.

**Comment by 333fred** [comment]
After looking at the semantic model, it appears that is just special-cases the scenario where `IsMissing` is true on the syntax node requested. Otherwise, it will return ErrorType as the type.

**Comment by 333fred** [comment]
Given that, I'd suggest that we do the same special case. In the given example in the original post, the Syntax of the BoundConversion has `IsMissing==true`. I'd suggest that in that case, and that case only, we omit the IConversionExpression, and return the underlying operand (which should be a BoundBadExpression). Retagging @dotnet/analyzer-ioperation @CyrusNajmabadi @AlekseyTs for more discussion.

**Comment by 333fred** [comment]
I can see the argument for keeping it though, as the underlying expression will have a Type of `ErrorType`.

**Comment by CyrusNajmabadi** [comment]
Design decision: Yes.  Try to do the missing checks and remove the conversion and make the type null if so.
