### ISSUE TITLE
take another look on what to cache on arguments

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#20193]
see this for more detail 
https://github.com/dotnet/roslyn/pull/20137#pullrequestreview-43830203

basically, right now for argument what we cache and what we put in the argument array are not 100% same. in between we put fake ioperation node that doesnt have corresponding bound node. we need to figure out what exactly we will cache on argument.

**Comment by tmat** [comment]
@heejaechang Is this important to fix for 15.5 or is it just a perf optimization?

**Comment by heejaechang** [comment]
after this - https://github.com/dotnet/roslyn/pull/21857, it is no longer relevant.

**Comment by tmat** [comment]
@heejaechang So we can close this issue?
