### ISSUE TITLE
Formatter ignores NewLine option

### ISSUE THREAD

**Issue by jrieken** [dotnet/roslyn#202]
Run the code below and notice that neither \r\n is removed, nor that \n is being used.

```c#
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.MSBuild;

namespace Formatting
{
    class Program
    {
        static void Main(string[] args)
        {

            var unformattedCode = @"using System\r\n; namespace HelloWorld{class Program{static void Main(string[]args){Console.WriteLine(""Hello,World!"");}}}";

            var cu = CSharpSyntaxTree.ParseText(unformattedCode);

            var normalizedNode = cu.GetRoot().NormalizeWhitespace("    ");
            var value = normalizedNode.GetText().ToString();
            if (value.IndexOf("\r\n") >= 0)
            {
                Console.WriteLine("normalized? nope");
            }

            var cw = MSBuildWorkspace.Create();
            var options = cw.Options
                .WithChangedOption(FormattingOptions.NewLine, LanguageNames.CSharp, "\n")
                .WithChangedOption(FormattingOptions.UseTabs, LanguageNames.CSharp, false)
                .WithChangedOption(FormattingOptions.TabSize, LanguageNames.CSharp, 8);

            var formattedNode = Formatter.Format(cu.GetRoot(), cw, options);
            value = formattedNode.GetText().ToString();
            if (value.IndexOf("\r\n") >= 0)
            {
                Console.WriteLine("formatted? nope");
            }

            Console.ReadLine();

        }
    }
}
```

**Comment by dpoeschl** [comment]
+Compiler team to comment on the expected behavior of the [NormalizeWhitespace method](http://source.roslyn.io/#Microsoft.CodeAnalysis/Syntax/SyntaxNodeExtensions.cs,389e160f1943f0c2), which I think exists to insert newlines/spaces in certain places based on [its tests](http://source.roslyn.io/#Roslyn.Compilers.CSharp.Syntax.UnitTests/Syntax/SyntaxFormatterTests.cs). 

@basoundr for the Formatter.Format part

**Comment by basoundr** [comment]
[FormattingOptions.NewLine](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Formatting/FormattingOptions.cs,23) is not used by Roslyn for the purpose of the formatting C# and VB and the value is always the default value.

It is an option that is used by TypeScript's Internal usage.

**Comment by dpoeschl** [comment]
Note: you can click the NewLine field in source.roslyn.io to see that there are no references within the Roslyn code (and compare with how the other options are used).

Do we intend to support this option? These options all need to documentation, too.

Regardless, is there currently a good way of switching all newlines to '\n'?

**Comment by rchande** [comment]
You could use a [SyntaxRewriter](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/CSharpSyntaxRewriter.cs,72741c962906b744,references) and in "VisitTrivia", replace NewLineTrivia with new NewLineTrivia containing your preferred line ending. I believe you'll need to descend into structured trivia in order to replace newlines within doc comments, etc.

**Comment by jmarolf** [comment]
Its just the newline option that is not respected.

```C#
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.MSBuild;

namespace Formatting
{
	class Program
	{
		static void Main(string[] args)
		{
			var unformattedCode = @"using System;

namespace HelloWorld
	{
		class Program
		{
			static void Main(string[] args)
			{
				Console.WriteLine(""Hello,World!"");
			}
		}
	}";

			var cu = CSharpSyntaxTree.ParseText(unformattedCode);

			var normalizedNode = cu.GetRoot().NormalizeWhitespace("    ");
			var oldValue = normalizedNode.GetText().ToString();
			Console.WriteLine(oldValue);

			var cw = MSBuildWorkspace.Create();
			var options = cw.Options
				.WithChangedOption(FormattingOptions.UseTabs, LanguageNames.CSharp, true);

			var formattedNode = Formatter.Format(cu.GetRoot(), cw, options);
			var newValue = formattedNode.GetText().ToString();
			Console.WriteLine(newValue);
		}
	}
}
```

the formatter changes spaces to tabs etc.  

Name| Value
------------ | -------------
oldValue	| "using System;\r\n\r\nnamespace HelloWorld\r\n{\r\n    class Program\r\n    {\r\n        static void Main(string[] args)\r\n        {\r\n            Console.WriteLine(\"Hello,World!\");\r\n        }\r\n    }\r\n}"	string
newValue | 	"using System;\r\n\r\nnamespace HelloWorld\r\n{\r\n\tclass Program\r\n\t{\r\n\t\tstatic void Main(string[] args)\r\n\t\t{\r\n\t\t\tConsole.WriteLine(\"Hello,World!\");\r\n\t\t}\r\n\t}\r\n}"	string

**Comment by rchande** [comment]
As @basoundr mentions, the C#/VB formatting engines don't currently respect the option, which is only used by TypeScript. Until we add that functionality, anyone who wants to switch the linebreaks will need to use string.Replace or rewrite the tree. string.Replace will replace linebreaks within string literals, so it's better to use a rewriter to only rewrite NewLineTrivia.

**Comment by basoundr** [comment]
There is no easy way to replace the newlines. The easiest way is to write a SyntaxWriter like [SyntaxFormatter](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/SyntaxFormatter.cs,54cb2e4288b05906) suggested by @rchande

**Comment by rchande** [comment]
@basoundr  SyntaxFormatter is internal :frowning:.

**Comment by mattwar** [comment]
SyntaxFormatter is the same thing as NormalizeWhitespace.

**Comment by nosami** [comment]
So, we simply need to write a 700 line class to support \n. I see.

**Comment by mattwar** [comment]
or you could do this:

var newRoot = root.ReplaceTrivia(
    root.DescendantTrivia().Where(t => t.IsKind(SyntaxKind.EndOfLineTrivia), 
    (t, _) => SyntaxFactory.LineFeed);

That should get most of them, except possibly inside multi-line comments.

**Comment by Mpdreamz** [comment]
`Formatter.Format` should support it, the fact we can write a custom syntaxrewriter is **not** a valid cop out IMO.

**Comment by Pilchie** [comment]
We should make Formatter.Format support this option as well as TypeScript.

**Comment by mkrueger** [comment]
That's a blocker for the mono team as well. At least for inserting new lines the formatter should take the new line option.
I don't care much about changing existing new lines according to that option that much. 
Would be nice if they would be corrected as well. But it's more important when inserting new lines.

**Comment by basoundr** [comment]
[`FormattingOptions.NewLine`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Formatting/FormattingOptions.cs,21) is currently not serialized. To serialize it, change the 'FeatureName' of the option to something unique and have the FeatureName exported through [`VisualBasicSettingsManagerOptionSerializer `](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.VisualBasic/Options/VisualBasicSettingsManagerOptionSerializer.vb,29) and [`CSharpSettingsManagerOptionSerializer`](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.CSharp/Options/CSharpSettingsManagerOptionSerializer.cs,48)

**Comment by jrieken** [comment]
thanks!

**Comment by sonawane-yogesh** [comment]
> or you could do this:
> 
> ```cs
> var newRoot = root.ReplaceTrivia(
>     root.DescendantTrivia().Where(t => t.IsKind(SyntaxKind.EndOfLineTrivia)), 
>     (t, _) => SyntaxFactory.LineFeed);
> ```
> 
> That should get most of them, except possibly inside multi-line comments.

Another way from above example.

```public static string ReplaceFieldsAndProperties(string programText)
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(programText);
            var compilationRoot = syntaxTree.GetCompilationUnitRoot();
            var propertyNodes = (from field in compilationRoot.DescendantNodes().OfType<PropertyDeclarationSyntax>() select field).ToList();
            if (!propertyNodes.Any()) return programText;
            var syntaxTriviaList = SyntaxFactory.TriviaList(SyntaxFactory.Tab, SyntaxFactory.ElasticTab);
            var withoutProperty = compilationRoot.ReplaceNodes(propertyNodes, (syntax, declarationSyntax) =>
                declarationSyntax.ReplaceTrivia(declarationSyntax.DescendantTrivia()
                        .Where(t => t.IsKind(SyntaxKind.EndOfLineTrivia)
                                    || t.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia)
                                    || t.IsKind(SyntaxKind.SingleLineCommentTrivia)), (t, _) => SyntaxFactory.Space)
                    .WithoutLeadingTrivia()
                    .WithLeadingTrivia(syntaxTriviaList)
                    // .WithLeadingTrivia(SyntaxTriviaList.Create(SyntaxFactory.ElasticTab))
                    .WithTrailingTrivia(SyntaxTriviaList.Create(SyntaxFactory.CarriageReturnLineFeed)));
            var formattedPropertyText = withoutProperty.GetText().ToString();
            return formattedPropertyText;
        }
