### ISSUE TITLE
Create Generator similar to bound node generator that creates basic IOperation types

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#20204]
we want to create IOperation generator similar to boundnode generator that create basic types from xml files.

the generator should create IOperation interfaces and Operations concrete types.

**Suggestions on generators** (We need to address the following suggestions when we implement the operation node generator)
https://github.com/dotnet/roslyn/pull/20177#pullrequestreview-43626611 
https://github.com/dotnet/roslyn/pull/19636#pullrequestreview-39800375
https://github.com/dotnet/roslyn/pull/19636#discussion_r118044195
https://github.com/dotnet/roslyn/pull/19636#pullrequestreview-39801178
https://github.com/dotnet/roslyn/pull/19636#discussion_r118045725
https://github.com/dotnet/roslyn/pull/20177#discussion_r121588312
https://github.com/dotnet/roslyn/pull/20177#discussion_r121588474
https://github.com/dotnet/roslyn/pull/20177#discussion_r121589002
https://github.com/dotnet/roslyn/pull/20364#discussion_r124862730
https://github.com/dotnet/roslyn/pull/20364#discussion_r123421564
https://github.com/dotnet/roslyn/pull/20689#discussion_r126509127
https://github.com/dotnet/roslyn/pull/20689#discussion_r126516915
https://github.com/dotnet/roslyn/pull/21407#discussion_r133309220
https://github.com/dotnet/roslyn/pull/21711#discussion_r137319982

**Comment by heejaechang** [comment]
suggestion on generators - https://github.com/dotnet/roslyn/issues/19720

**Comment by 333fred** [comment]
Moving this out to 15.8, as I feel that it's less important than CFG work. @AlekseyTs or @jinujoseph, push back if you feel this should be targeted sooner.

**Comment by jinujoseph** [comment]
@333fred any chance of getting this done ? or rename the file pls or close it

**Comment by 333fred** [comment]
I'd like to get this done in the 16.0 timeframe, but it's definitely low on the priority list.

**Comment by 333fred** [comment]
With #38056, this is now implemented.
