### ISSUE TITLE
No warning for unused local tuple variable

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#20208]
**Version Used**: 2.3.0.61719 (5fbdd5c5)

**Steps to Reproduce**:

```csharp
class C
{
	public static void Main ()
	{
		(int, int) t1 = (-1, 2); // warning CS0219
		var t2 = (-1, 2);  // NO warning CS0219
	}
}
```

**Expected Behavior**:

Consistent behaviour

**Actual Behavior**:

The warning is issued for t1 variable only

**Comment by alrz** [comment]
Tracked by #15695.

>A local variable that is written to is considered to also be read, unless the written value is always a constant.

**Comment by alrz** [comment]
It's interesting that tuples are an exception to that rule since tuple literals cannot be `const`.

**Comment by alrz** [comment]
I see that's not the actual cause since the two locals are different only by `var`.

**Comment by jcouv** [comment]
Thanks for reporting this.
FYI @VSadov

**Comment by jcouv** [comment]
I've made a PR for 15.3 and started discussion with compat council.

**Comment by jcouv** [comment]
Won't meet the bug bar for 15.3. Discussion still ongoing for 15.6.
If not, it'll be a good candidate for warning waves https://github.com/dotnet/roslyn/issues/1580

**Comment by jcouv** [comment]
LDM approved the compat break. The change (#20231) will ship in 15.5 (C# 7.2).
Thanks for reporting this.
