### ISSUE TITLE
"Go To Definition" command places cursor at end of method name.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#2021]
Ported from TFS WorkItem: **883644**

---

**Repro Steps:**

<BR>**Steps to reproduce:**<BR>
1. Create a new C# Console application.
2. Set the editor text of Program.cs to the following:

<BLOCKQUOTE style="MARGIN-RIGHT: 0px" dir=ltr><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>

<FONT face=Consolas>namespace</FONT></FONT></FONT></FONT><FONT size=2><FONT size=2><FONT color=#000000 face=Consolas> ConsoleApplication1</FONT>

<FONT face=Consolas>{</FONT>

</FONT></FONT><FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;&nbsp;&nbsp; class</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT><FONT color=#2b91af size=2><FONT color=#2b91af size=2><FONT color=#2b91af size=2>Program
</FONT></FONT></FONT></FONT><FONT size=2><FONT size=2>

<FONT face=Consolas><FONT color=#0000ff>&nbsp;&nbsp;&nbsp; </FONT>{</FONT>

</FONT></FONT><FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; static</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>void</FONT></FONT></FONT><FONT size=2><FONT size=2> Main(</FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>string</FONT></FONT></FONT></FONT><FONT size=2><FONT size=2><FONT face=Consolas>[] args)</FONT>

<FONT face=Consolas><FONT color=#0000ff>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </FONT>{</FONT>

<FONT face=Consolas><FONT color=#0000ff>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </FONT>myFunction();</FONT>

<FONT face=Consolas><FONT color=#0000ff>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </FONT>}</FONT>

<FONT face=Consolas></FONT>&nbsp;

</FONT></FONT><FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; static</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>void</FONT></FONT></FONT></FONT><FONT size=2><FONT size=2><FONT face=Consolas> myFunction()</FONT>

<FONT face=Consolas><FONT color=#0000ff>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </FONT>{</FONT>

<FONT face=Consolas><FONT color=#0000ff>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </FONT>}</FONT>

<FONT face=Consolas><FONT color=#0000ff>&nbsp;&nbsp;&nbsp; </FONT>}</FONT>

<FONT face=Consolas>}</FONT>
</FONT></FONT>
1. Right click on the call to myFunction() inside the Main() fuinction and click "Go To Definition".
2. Right click on the call to myFunction() again, and click on "Peek Definition".

<BR>**Actual Results:**<BR>Both "Go To Definition" and "Peek Definition" successfully find the definition of the function (or variable). However, "Go To Definition" places the cursor at the end of the function or variable&nbsp;name, while "Peek Definition" puts the cursor at the end of the beginning of the function or variable&nbsp;name.

<BR>**Expected Results:**<BR>(This is also the Dev12 behavior)

Both "Go To Definition" and "Peek Definition" place the cursor at the beginning of the function or variable&nbsp;name.

---

**Revisions:**

1) Created By Collin Deel (Chinasoft) (2/14/2014 4:23:50 PM)

---

2) Edited By Dustin Campbell (2/18/2014 9:38:53 AM)

We like the design that the caret is at the end with a selection. We should do the same for Peek.

---

3) Edited By Collin Deel (Chinasoft) (5/1/2014 11:34:32 AM)

I just noticed that double-clicking on&nbsp;a class/function/variable/etc&nbsp;name&nbsp;in the solution explorer also places the caret at the beginning of the definition name.

---

4) Edited By Kevin Pilch-Bisson (2/18/2015 4:50:58 PM)

Let's port this to GitHub in Unknown and Mark Up for Grabs.&nbsp; 

---

**Comment by CyrusNajmabadi** [comment]
This is not roslyn.  We create the peek item calling into `IPeekResultFactory.Create(IPeekResultDisplayInfo displayInfo, string filePath, int startLine, int startIndex, int endLine, int endIndex, int idLine, int idIndex, bool isReadOnly);`  We pass the appropriate start/end positions, but the platform places the caret at the start.

@jinujoseph  can we move to azdo?  Note: i'm also fine just closing this as this just seems so niche and we haven't heard a single thin on this.

**Comment by jinujoseph** [comment]
thanks Cyrus, old issue so closing this out. if this comes up ..we can move to platform
