### ISSUE TITLE
VBCompiler.CompileAssemblyFromFileBatch() is modifying the passed in CompilerOptions

### ISSUE THREAD

**Issue by niemyjski** [dotnet/roslyn#20214]
I was using the legacy VB CodeDom provider to generate VB Code and compile it on the fly for our app. It was working great but we wanted to support newer language features so we brought in the latest Roslyn Code Dom provider via nuget... The change was simple and our c# implementation works flawlessly but I can't even compile the simplest sample due to the VBCompiler is injecting unwanted/invalid compiler options

Lets say I pass in the compiler options of `/optionInfer+ /define:CodeSmith40 /define:CodeSmith50 /define:CodeSmith60 /define:CodeSmith70 /define:CodeSmith80 /define:TRACE` they are modified once I call CompileAssemblyFromFileBatch to `/nowarn:41008,40000,40008 /define:_MYTYPE=\\\"Web\\\" /imports:Microsoft.VisualBasic  /optionInfer+ /define:CodeSmith40 /define:CodeSmith50 /define:CodeSmith60 /define:CodeSmith70 /define:CodeSmith80 /define:TRACE`

Once it defines `_MYTYPE` (unwanted), I believe it's calling the following code (https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Compilers/VisualBasic/Portable/Symbols/EmbeddedSymbols/VbMyTemplateText.vb#L287) which causes my compile to fail with:

```
vbc : (1,1): error BC30002: Type 'Global.System.Web.HttpRequest' is not defined.
vbc : (1,1): error BC30002: Type 'Global.System.Web.HttpResponse' is not defined.
```

```
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.5" targetFramework="net462" />
  <package id="Microsoft.Net.Compilers" version="2.2.0" targetFramework="net462" developmentDependency="true" />
```

**Comment by jaredpar** [comment]
@niemyjski the CodeDom package is owned by ASP.Net, no Roslyn.  Could you please file the bug here?

https://github.com/aspnet/RoslynCodeDomProvider

**Comment by Jinhuafei** [comment]
@jaredpar /define:_MYTYPE="Web" has been there for years, and it's been working with the legacy vbc.exe without any issue. Can you check why the new vbc.exe causes compilation error with this option?

**Comment by jaredpar** [comment]
@Jinhuafei 

Here are the errors being reported:

```
vbc : (1,1): error BC30002: Type 'Global.System.Web.HttpRequest' is not defined.
vbc : (1,1): error BC30002: Type 'Global.System.Web.HttpResponse' is not defined.
```

That would suggest the compiler is missing a reference. Is everything beeing properly passed to the compiler here?
