### ISSUE TITLE
ref structs should not implement interfaces

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#20226]
Considering that ref structs cannot be boxed or passed as a generic type argument, implementing interfaces is pointless.

**Comment by sharwell** [comment]
What about `IDisposable`? A `using` statement requires the type to be `IDisposable` even if it dispatches the `Dispose` call to the method on a particular type.

**Comment by VSadov** [comment]
Ref struct is not convertible to an interface, even if it claims to be implementing one. In particilar that would not satisfy the requirememts of `using`.

**Comment by KrisVandermotten** [comment]
Well, we could change the requirements of `using`, as in #11420.

**Comment by VSadov** [comment]
fixed in https://github.com/dotnet/roslyn/pull/20293

**Comment by nietras** [comment]
It is definitely not pointless, it can used with generics without boxing! Please remove this restriction. I have a specific need that is blocked by this, namely for my work with Span.Sort?

**Comment by nietras** [comment]
I guess it is because there is currently no way to constrain a generic type parameter to avoid possibly boxing it. Why not consider a constraint for this then? Not sure what would be good but:

```csharp
internal interface ISwapper
{
    void Swap(int i, int j);
}
internal ref struct Swapper<T> : ISwapper // ref structs can't inherit interfaces :( Nor be generic type parameter
{
    Span<T> _items;

    public Swapper(Span<T> items)
    {
        _items = items;
    }

    public void Swap(int i, int j)
    {
        ref T start = ref _items.DangerousGetPinnableReference();
        SpanSortHelper.Swap(ref Unsafe.Add(ref start, i),
                            ref Unsafe.Add(ref start, j));
    }
}

public void SomeMethod<TSwapper>(TSwapper swapper)
    where TSwapper : ref struct 
    // Although it should still work for normal structs, just restrict the availability of boxing etc. 
    // "unboxable" :|
{
     // Swapper can then be used to inject zero, one or more extra items...
}
```

**Comment by jtheisen** [comment]
I second @nietras. This limitation prevents the creation of a lot of very useful building blocks.

**Comment by jtheisen** [comment]
As a motivation consider this building block:

```
	public interface IAction<T>
	{
		void Do(ref T value);
	}

	public static unsafe void ForEach<A, T>(this Memory<T> memory, A action)
		where T : unmanaged
		where A : struct, IAction<T>
	{
		fixed (T *ptr = &memory.Span.GetPinnableReference())
		{
			var p = ptr;
			var e = ptr + memory.Span.Length;
			
			for (; p < e; ++p)
			{
				action.Do(ref *ptr);
			}
		}
	}
```

And then using this with some implementation:

```
	public struct PointlesSumAction : IAction<Char>
	{
		public Char sum;

		public void Do(ref Char value)
		{
			sum += value;
		}
	}

...

        {
            var a = new PointlesSumAction();
	    myMemory.ForEach(ref a);
	}

```

With optimizations turned on, this compiles to a loop with `Do` inlined, and the range checks being done only once for the `ForEach` call.

This can be done with `Memory` now, but it really belongs to `Span`.

**Comment by miyu** [comment]
Please reconsider this. @jtheisen gives a great example that can benefit heavily from inlining. My specific use-case involves traversing a BST with a custom comparer that'd have a ref to a few larger structs (do not want to make class for variety of reasons). My only alternative is to copy-paste my tree search function so that I can benefit from inlining and avoid big struct copies.

**Comment by miyu** [comment]
See also https://github.com/dotnet/csharplang/issues/1148

**Comment by redknightlois** [comment]
Sorry for reviving a zombie thread but currently hitting the exact same issue. We deal with unmanaged memory A LOT. And the ability to enclose the memory boundaries inside `Span<byte>` has simplified, and even made our code of complex data structures way faster. If we wouldn't have hit this issue we wouldn't have to rethink the approach. We use struct interface metaprogramming sparingly with excellent results in performance, code readability, and maintainability (we cannot ask for more); the ability to have `ref struct` implementing interfaces is beyond cosmetic, it allows us to be able to produce very high-performance code without having to jump several hops in coding abstractions to package those `Span<byte>` into a method (which is also inefficient in comparison). 

It is certainly not pointless, the more you use `Span<byte>` the more important it becomes to have interfaces for `ref struct` .

**Comment by CyrusNajmabadi** [comment]
hi @redknightlois discussions abotu the language go at dotnet/csharplang.  See teh linked threads in the post above yours :)   this is the repo for the compiler impl.

**Comment by jtheisen** [comment]
@CyrusNajmabadi Yes, but it would really help a lot if the language implementors could tell them what they need to hear.

Using unboxed structs as interfaces through generics is possible in C# (and probably VB) since the days of Silverlight, yet the OP's statement proves this isn't common knowledge, even among the experts.

And these things are why .NET is so much better than Java, the static language where everything is boxed except ints and floats. 

You guys know you need to embrace that advantage, and you did of course, with the introduction of Span&Co - but this right here is an oversight that really needs fixing.

And it's likely easy to fix, so maybe the language implementors should do that first and then just have it sanctioned by the language people, right?

**Comment by CyrusNajmabadi** [comment]
> And it's likely easy to fix, so maybe the language implementors should do that first and then just have it sanctioned by the language people, right?

No. We don't purposefully deviate in that manner.

>  Yes, but it would really help a lot if the language implementors could tell them what they need to hear.

It's the same group of people. We just make language changes over at dotnet/csharplang. Then once that is done, the compiler is updated to support the new language version.
