### ISSUE TITLE
Create an analyzer + fixer for missing OSS copyright comment

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#2022]
We often forget to add the OSS copyright comments when creating new files. Based on recent code reviews this seems like a common problem. We have also had cases where the problem slipped past code reviewers unnoticed until someone happened to notice and fix up the issue a few weeks later.

Adding an analyzer + fixer for this would be nice. The analyzer would also be very cheap (purely syntax based and only needs to be invoked once per file).

**Comment by srivatsn** [comment]
@dpoeschl - weren't you working on this?

**Comment by dpoeschl** [comment]
Yeah, I have an old analyzer/fixer for this that I could update. It was difficult to integrate into our internal dogfooding experience at the time for various reasons, which is why it was not checked in then.

**Comment by sharwell** [comment]
Duplicate of #33012
