### ISSUE TITLE
P2P references do not respect [TypeForwardedTo] attributes

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#20227]
**Version Used**: 
Visual Studio 2017 Update 2

**Steps to Reproduce**:

1. Create a new C# class library ProjectA and reference some binary, such as `Microsoft.VisualStudio.Text.UI.Wpf.dll`
2. Add another class library to the solution: ProjectB and make a P2P reference to ProjectA
3. Paste this code in ProjectA:
```
using System.Runtime.CompilerServices;
using Microsoft.VisualStudio.Text.Editor;
[assembly:TypeForwardedTo(typeof(IWpfTextView))]
```
4. In ProjectB, use the type:
```
class C : IWpfTextView {} 
```

**Expected Behavior**:
Should build fine and IntelliSense should work

**Actual Behavior**:
Doesn't build because in ProjectB it can't find where IWpfTextView is defined.

Important: this works fine if you switch to a metadata reference (i.e. if you reference ProjectA.dll instead of a project reference, it will work fine)

**Comment by jasonmalinowski** [comment]
@KirillOsenkov: by your repro steps, even building is broken:

> C:\Users\jasonmal\documents\visual studio 2017\Projects\ClassLibrary2\ConsoleApp1\Program.cs(14,48,14,60): error CS1069: The type name 'IWpfTextView' could not be found in the namespace 'Microsoft.VisualStudio.Text.Editor'. This type has been forwarded to assembly 'Microsoft.VisualStudio.Text.UI.Wpf, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.

Did you miss a step?

**Comment by jasonmalinowski** [comment]
I also see no change in behavior replacing with a file reference.

**Comment by KirillOsenkov** [comment]
OK, now I'm not convinced that it should work at all. I wonder if the compiler should resolve a type from ProjectA that's been type-forwarded away to some other assembly.

Or are type-forwarders only respected by the runtime, and not the compiler?

I should add that the IDE behavior is correct, i.e. consistent with the compiler. @jasonmalinowski is correct, there doesn't seem to be a difference whether you're referencing ProjectA as a P2P or a .dll reference.

CC @gafter @agocke @jaredpar - should the compiler be able to bind against a type that was forwarded?

**Comment by jasonmalinowski** [comment]
The compiler chases type forwards.

**Comment by agocke** [comment]
Looks like Project B needs a reference to `Microsoft.VisualStudio.Text.UI.Wpf.dll`. At least, that wasn't mentioned in your repro steps.

**Comment by KirillOsenkov** [comment]
I see, is this required? You need to have the reference to a project where the type is forwarded from AND the binary where the type is forwarded to?

**Comment by KirillOsenkov** [comment]
I guess so, because how it would otherwise know about types members...

**Comment by jasonmalinowski** [comment]
@KirillOsenkov Correct.

**Comment by jasonmalinowski** [comment]
At this point I'm going to close this since as far as I can tell, there is no product bug here...
