### ISSUE TITLE
Unable to suppress CS2002

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#20229]
**Version Used**: 2.2.0.61624

**Steps to Reproduce**: Create a new .NET Standard project, add `<NoWarn>2002</NoWarn>` and include some files twice.

**Expected Behavior**: No CS2002

**Actual Behavior**: `Source file ... specified multiple times`

I'm not sure whether this is intentional since not many people want to include duplicate files anyway. However, I need to include duplicate files to work around a bug where Visual Studio doesn't pick up on some auto-generated code files, so it would be really useful to suppress these warnings.

**Comment by jcouv** [comment]
@jamesqo Could you describe the repro steps in more details? In particular, how do you add the same file twice in a .NET Standard project?

I tried adding the same file via the IDE (didn't do anything). I tried editing the csproj file (but that gave me the msbuild error below, not CS2002).

`Duplicate 'Compile' items were included. The .NET SDK includes 'Compile' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultCompileItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'Class1.cs'	NETStandard	C:\Program Files\dotnet\sdk\2.0.2-vspre-006949\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.DefaultItems.targets	263	`

**Comment by jcouv** [comment]
@jamesqo Could you assist with repro details? Thanks

**Comment by jcouv** [comment]
@jamesqo I wasn't able to repro. Please try again on recent setup and re-open the issue with details if the problem still exists. Thanks
