### ISSUE TITLE
Feature Request: Assign property value without additional private member boilerplate. And simplify get/set.

### ISSUE THREAD

**Issue by justindyer** [dotnet/roslyn#20239]
As of C# 7.0, if logic is necessary in a property, then an additional member is necessary to store the value. 

The simplest form of property looks like this:
`public string MyProperty { get; set; }`

If logic is necessary, then the addition of a member is necessary and usually is boilerplate code that is just more work to write and have like so:

```
private string _myProperty = "default";
public string MyProperty
{
    get
    {
        return _myProperty;
    }
    set
    {
        if(value != "")
        {
            _myProperty = value;
        }
    }
}
```

Ideally, this could be simplified by referring to the property using a keyword. In this example I choose to use a keyword named `self`:
```
public string MyProperty
{
    get
    {
        return self;
    }
    set
    {
        if(value != "")
        {
            self = value;
        }
    }
}
```

It could be furthermore simplified by allowing this syntax so that explicitly defining a get or set is optional:
```
public string MyProperty
{
    get; //Simplified syntax for defining a get.
    set
    {
        if(value != "")
        {
            self = value;
        }
    }
}
```

**Comment by KrisVandermotten** [comment]
> Ideally, this could be simplified by referring to the property using a keyword.

I believe you meant "Ideally, this could be simplified by referring to the _backing field_ using a keyword" ?

**Comment by justindyer** [comment]
Yes, that is a more accurate description.

**Comment by jcouv** [comment]
@justindyer Please move this discussion to the csharplang repo. There may already be a suggestion for this (here's a related one: https://github.com/dotnet/csharplang/issues/318).
I'll close this Roslyn issue as it is not a compiler bug. Thanks

**Comment by jnm2** [comment]
Using a backing field without naming it was considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md
