### ISSUE TITLE
IDE quick info tooltip missing xml doc comment if the doc includes "&"

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#2023]
Ported from TFS WorkItem: **547298**

---

**Repro Steps:**
1. paste the following code into VS<div><br></div><div><div>class C</div><div>{</div><div>&nbsp; &nbsp; static void Foo()</div><div>&nbsp; &nbsp; {</div><div>&nbsp; &nbsp; &nbsp; &nbsp; CompileAndInvoke();</div><div>&nbsp; &nbsp; }</div><div>&nbsp; &nbsp; /// &lt;summary&gt;</div><div>&nbsp; &nbsp; /// Compile &amp; Invoke</div><div>&nbsp; &nbsp; /// &lt;/summary&gt;</div><div>&nbsp; &nbsp; static void CompileAndInvoke()</div><div>&nbsp; &nbsp; { }</div><div>}</div></div><div><br></div><div>2. hover cursor over either one of "CompileAndInvoke()</div><div><br></div><div>**Actual**:</div><div>No xml doc comments in the tool tip.</div><div><br></div><div>**Expected**:</div><div>doc comments in the tool tip.</div><div><br></div><div>the exception log shows two exceptions</div><div><br></div><div><div>System.Xml.XmlException: Name cannot begin with the ' ' character, hexadecimal value 0x20. Line 3, position 14.</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.Throw(Exception e)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32&amp; colonPos)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32&amp; charRefEndPos)</div><div>12/4/2012 12:21:38 PM</div><div>Source: First chance exception: System.Xml</div><div>StackTrace: &nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.Throw(Exception e)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32&amp; colonPos)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32&amp; charRefEndPos)</div><div><br></div></div><div><br></div><div>and&nbsp;</div><div><br></div><div><br></div><div><div>System.Xml.XmlException: Name cannot begin with the ' ' character, hexadecimal value 0x20. Line 3, position 14.</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.Throw(Exception e)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32&amp; colonPos)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32&amp; charRefEndPos)</div><div>12/4/2012 12:21:38 PM</div><div>Source: First chance exception: System.Xml</div><div>StackTrace: &nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.Throw(Exception e)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32&amp; colonPos)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32&amp; charRefEndPos)</div><div><br></div><div>System.Xml.XmlException: An error occurred while parsing EntityName. Line 3, position 14.</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.Throw(Exception e)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32&amp; charRefEndPos)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.ParseText(Int32&amp; startPos, Int32&amp; endPos, Int32&amp; outOrChars)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.FinishPartialValue()</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.get_Value()</div><div>&nbsp; &nbsp;at System.Xml.XmlReader.WriteNode(XmlWriter xtw, Boolean defattr)</div><div>&nbsp; &nbsp;at System.Xml.XmlReader.ReadInnerXml()</div><div>&nbsp; &nbsp;at Roslyn.Services.DocumentationComment.FromXmlFragment(String xml) in e:\Roslyn\Main\Source\Services\Core\DocumentationComment.cs:line 102</div><div>12/4/2012 12:21:38 PM</div><div>Source: First chance exception: System.Xml</div><div>StackTrace: &nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.Throw(Exception e)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32&amp; charRefEndPos)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.ParseText(Int32&amp; startPos, Int32&amp; endPos, Int32&amp; outOrChars)</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.FinishPartialValue()</div><div>&nbsp; &nbsp;at System.Xml.XmlTextReaderImpl.get_Value()</div><div>&nbsp; &nbsp;at System.Xml.XmlReader.WriteNode(XmlWriter xtw, Boolean defattr)</div><div>&nbsp; &nbsp;at System.Xml.XmlReader.ReadInnerXml()</div><div>&nbsp; &nbsp;at Roslyn.Services.DocumentationComment.FromXmlFragment(String xml) in e:\Roslyn\Main\Source\Services\Core\DocumentationComment.cs:line 102</div><div><br></div></div><div><br></div><div><br></div>

---

**Revisions:**

1) Created By Jeremy Meng (12/7/2012 10:36:26 PM)

---

2) Edited By Dustin Campbell (12/7/2012 10:36:27 PM)

Actually, the Expected should be to show the XML error in the tooltip. See, the attached screenshot.

---

3) Edited By Dustin Campbell (12/7/2012 10:36:27 PM)

Kevin's preference would be to try and show the actually text of the doc comment, regardless of parse errors.

---

4) Edited By Kayle Hinkle (5/14/2014 9:39:42 PM)

The compiler currently returns the following:

&nbsp;

&lt;!-- Badly formed XML comment ignored for member &quot;M:C.CompileAndInvoke&quot; --&gt;

&nbsp;

The IDE currently only displays the &lt;summary&gt; contents, which is null here.

&nbsp;

3 options:
1. won't fix
2. Display what the compiler currently returns (Badly formed XML comment ignored for member &quot;M:C.CompileAndInvoke&quot;)
3. Ask the compiler team to provide the text anyway despite the errors.

---

5) Edited By Kevin Pilch-Bisson (6/13/2014 1:16:51 PM)

We should show the message below in these cases.

---

6) Edited By Kevin Pilch-Bisson (2/15/2015 9:25:45 PM)

Let's put this in unknown/up for grabs.

---

**Comment by sharwell** [comment]
Hovering over `CompileAndInvoke` should show the following:

> Compile & Invoke

The XML error will be reported separately at the location where it actually occurs. There is no need to remove useful information from Quick Info for all the references over this.

**Comment by Pilchie** [comment]
It's not that we deliberately try to remove info, it's just that we parse the xml, and if there is a parse error, we don't get a summary tag to get the contents of.

**Comment by sharwell** [comment]
I know that. :smile:  I just wanted to clarify the intended (optimal) outcome since it's labeled Up for Grabs.

**Comment by CyrusNajmabadi** [comment]
Behavior seems acceptable.  user is already informed (through several mechanisms) that there's a problem with their doc comment.

**Comment by sharwell** [comment]
Reopening. This statement is not correct:

> user is already informed ... that there's a problem with their doc comment.

Under default project configurations, Quick Info does not work and there is no indication at all regarding the cause.

**Comment by CyrusNajmabadi** [comment]
Closing as by design and lack of feedback.  If we want to make any changes here, then we should attach this to a milestone and fix it.
