### ISSUE TITLE
PublicAPI code fixer doesn't update Unshipped file

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#20230]
The fixer triggers (lightbulb appears), but the action doesn’t seem to work (no file is changed).
Also, I noticed that the shipped/unshipped files no longer come up in GoTo (Ctrl+,). I suspect they were removed from the project and that may have something to do with the problem.

**Comment by Pilchie** [comment]
This is a bug in the project system.  @jasonmalinowski just checked in a workaround, but you might not have it in the branch you were working in yet.

**Comment by jcouv** [comment]
Thanks @Pilchie and @jasonmalinowski :-)
I'll close the issue and wait for workaround to propagate.

**Comment by jasonmalinowski** [comment]
I would have expected it to be anywhere @jcouv is working by now. @jcouv where was this?

**Comment by jcouv** [comment]
The code fixer worked when I tried it, just now, on dev15.6 branch.
