### ISSUE TITLE
FindReferencesAsync returns nothing for extension in static class

### ISSUE THREAD

**Issue by majatu** [dotnet/roslyn#20243]
**Version Used**: 1.3.0.0

**Steps to Reproduce**:

Main project uses extension from another project. With Roslyn i try to find all references of this extension, but it's return nothing, but inside one project works well.

**1.csproj**

```
public async Task Find()
{
    const string solutionPath = @"....sln";
    const string methodName = "My";
    const string fileName = "MyExtensions.cs";

    var workspace = MSBuildWorkspace.Create();
    var solution = await workspace.OpenSolutionAsync(solutionPath);

    ISymbol methodSymbolType = null;

    foreach (var project in solution.Projects)
    {
        var compilation = await project.GetCompilationAsync();

        if (methodSymbolType != null)
            continue;

        var commonSyntaxTrees = compilation.SyntaxTrees;

        foreach (var commonSyntaxTree in commonSyntaxTrees)
        {
            if (!commonSyntaxTree.FilePath.EndsWith(fileName))
                continue;

            var semanticModel = compilation.GetSemanticModel(commonSyntaxTree);

            try
            {
                var nodes = semanticModel.SyntaxTree.GetRoot().DescendantNodes().OfType<MethodDeclarationSyntax>();

                foreach (var dr in nodes)
                {
                    var isMethodSymbolType = dr.Identifier.Text == methodName;
                    if (isMethodSymbolType)
                    {
                        methodSymbolType = semanticModel.GetDeclaredSymbol(dr);

                        break;
                    }
                }
            }
            catch (Exception ex)
            {
                continue;
            }

            if (methodSymbolType == null)
                continue;

            break;
        }
    }

    var referencesType1 = await SymbolFinder.FindReferencesAsync(methodSymbolType, solution);
```

extension sample **2.csproj**

```
public static class MyExtensions
{
    public static string My(this string value, ...)
    {
        ...
    }
}
```

usage sample **3.csproj**

`"....".My(...);`

**Expected Behavior**:

all references locations are found

**Actual Behavior**:

here in referencesType1 is no location, any ideas why?

**Comment by Pilchie** [comment]
Can you try:

1. Subscribing to `WorkspaceFailed` and seeing if you get an issues reported?
2. Verifying that there are no diagnostics on either of your compilations?

My suspicion is that something has gone wrong in the population of your `Solution`.

**Comment by majatu** [comment]
Seems very strange, that usual method between multiple projects or static extension in one project is found ok, but not such case, like i need. After upgrading to Microsoft.CodeAnalysis 2.2.0 projects not found in solution at all.

**Comment by Pilchie** [comment]
> After upgrading to Microsoft.CodeAnalysis 2.2.0 projects not found in solution at all with same code. I'll try soon downgrade and subcribe to WorkspaceFailed

Likely because you'll need the MSBuild 15 binaries installed and binding redirects to it in your application.

Can you attach a zip that includes all 3 projects where this repros?

**Comment by majatu** [comment]
Unfortunately no, this is a commercial projects. I also tried with msbuild 15 with no luck again. Build is ok in cmd, but event WorkspaceFailed writes me "Msbuild failed when processing the file 3.csproj"

Path var C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin
How i run build msbuild /tv:15.0 from directory with 3-d project

**Comment by Pilchie** [comment]
> Unfortunately no, this is a commercial projects. 

Can you construct a small example where this repros that doesn't involve the commercial code?

>  Build is ok in cmd, but event WorkspaceFailed writes me "Msbuild failed when processing the file 3.csproj"

Can you try the 2.3 preview packages?  They should write more detail.

ToolsVersion is a red-herring.  MSBuild hasn't looked at it in many years now.

**Comment by CyrusNajmabadi** [comment]
This works for me.  My guess is that something is wrong with this project loading.  We would need more information or a repro to figure out what's going wrong.  This is not an issue at the FAR level.
