### ISSUE TITLE
Add way to export Tools>Options settings to .editorconfig

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#20253]
Perhaps add a button on the Tools>Options page? Does this include Tabs/Formatting?

**Comment by jasonmalinowski** [comment]
@allisonchou @kuhlenh can I dupe this against something now?

**Comment by Therzok** [comment]
https://github.com/dotnet/roslyn/pull/28472 ?

**Comment by mavasani** [comment]
This is complete.
