### ISSUE TITLE
Simplify Find All References for one reference

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#20256]
If I invoke FAR and there is only a single reference available, navigate me directly to that reference rather than dumping me in the Results window to see one result.

**Comment by AtsushiKan** [comment]
I would find that more annoying than helpful. A lot of the time, the one-liner tells me what I needed to know and I don't need the additional chore of finding my way back to where I was.

**Comment by CyrusNajmabadi** [comment]
I looked into doing this and it's surprisingly difficult.  The problem is one of "how do you know there's only a single reference?"  i.e. say the FindRefs calls takes 30 seconds to search a huge project.  We find the first reference very quickly.  What do we do then?  We're still doing the search and there might be a second result.  So do we just not show any results until we get a second result?  This means that we could be delaying showing you that first result for a long time.

**Comment by SolderedMushroom** [comment]
I'm a customer and I would also find this annoying.

**Comment by CyrusNajmabadi** [comment]
I'd be happy to expose this as a user facing option.  However, there's still the open question of "what happens if it just takes a long time to actually do the search?"

**Comment by alrz** [comment]
"Go To All" immediately goes to the first result and when you hit Esc it goes back where you started typing. Something like that could be applied to FAR, also when the user is still "in the context" a shortcut key would be useful for going to the "next result" (if any)

**Comment by CyrusNajmabadi** [comment]
go-to is a blocking operation currently.  FindRefs is non-blocking.

**Comment by miloush** [comment]
I agree with both sides and I am adding another option - you might want to go to the single result and also store it in the FAR window for later reference.

It's not very clear what counts as a single reference, though. If the reference is shared among several projects through a linked file, it gets multiple entries in the FAR window, would you treat it as a single one?

**Comment by alrz** [comment]
R# does that with tabs and I found it quite useful. I think the issue with linked files is irrelevant since every reference points to either of those files.

**Comment by miloush** [comment]
@alrz Sorry by irrelevant you mean it should be treated as single reference?

The FAR results are not just a physical location, they also have context. Even if it is the same linked file, when you open it from the results it opens it in the context of the respective project.

Speaking of which, if the only thing you cared about was _were_ the result is, it is much more difficult to figure that out when the file is opened as opposed to reading it out of the FAR window

**Comment by alrz** [comment]
I don't know how FAR works today, but the compiler has no information about linked files and it treats them as standalone compilation units.

**Comment by CyrusNajmabadi** [comment]
Giving to @kuhlenh for more design input.

**Comment by CyrusNajmabadi** [comment]
Not planning on doing this.
