### ISSUE TITLE
Why do ConditionalMemberAccess and SimpleMemberAccess have different associativity in a syntax tree?

### ISSUE THREAD

**Issue by vedun-z** [dotnet/roslyn#20257]
SimpleMemberAccess is right-associative. If you have an expression like `o.A.B.C.D` it would be parsed as `(((o.A).B).C).D`.

A syntax tree for the expression is:

![image](https://user-images.githubusercontent.com/1244051/27203146-2502ed50-522d-11e7-9994-58c2a8526304.png)

We can notice that a value of each expression depends only on values of child. This fact is true for most of expressions and it's extremely useful for implementation of visitors . However the fact is not true for ConditionalMemberAccess. Lets consider the same example in case of conditional access `o?.A?.B?.C?.D`.

Surprisingly, it has following syntax tree:

![image](https://user-images.githubusercontent.com/1244051/27203546-0a45cd28-522f-11e7-859e-ae8bc379a70b.png)

A value of each conditional member access expression depends on a parent value, not on the values of child. Moreover, you can mix simple member accesses and conditional member access. For example 
`o?.A.B` and  `(o?.A).B` has pretty different syntax trees because, in the first case, conditional access is root and, in the second case, simple member access is root. 

Can you guys explain me the reason why simple member access and conditional access have different associativity in a syntax tree? Because of that reason, correct interpretation of expressions like `o?.A.B?.C.D` becomes much more harder. For example, the syntax tree for expression `o?.A.B?.C.D` looks like:
![image](https://user-images.githubusercontent.com/1244051/27204002-3f31dfd4-5231-11e7-934c-fc9b0061da7c.png)

**Comment by CyrusNajmabadi** [comment]
It makes the system much simpler overall.  If you have  a?.B.C.D.E   you don't want to say "evaluate a?.B.C.D and then get the E member off of it... except if you also saw ?. down the left side, in which case you get a appropriate null-lifted value of hte type of the E member".  

Instead, you want to say "just evaluate 'a'.  If it's non null, evaluate the right side appropriately like you always would.  If it's null, then handle things in the following manner"

The benefit of the syntax approach is taht ConditionalAccessExpression points at an expression on the left and an expression on the right.  That allows the *right* side of the ? operator to be the normal MemberAccessExpression for something like ".B.C.D.E".  Except that now we only need to evaluate that as appropriate based on what the value before the ? evaluated to.

**Comment by CyrusNajmabadi** [comment]
> For example
o?.A.B and (o?.A).B has pretty different syntax trees because, in the first case, conditional access is root and, in the second case, simple member access is root.

This is *good*.  These constructs have totally different semantics for the language.  For example, in the first, if 'o' is null, then you get a 'null' value of whatever type 'B' is.  In the second example, if 'o' is null, you will get a null-ref exception.  that's because ".B" in the second expression is a normal member acesss that will null ref at runtime if the left side is null.  In the first expression you have the conditional access and ".A.B" is specially handled if you have null.

**Comment by CyrusNajmabadi** [comment]
> Can you guys explain me the reason why simple member access and conditional access have different associativity in a syntax tree?

The simple reason is because they have different associativity at the language level. And the associativity they have follows the style of semantics each language construct presents.

**Comment by vedun-z** [comment]
Thank you for your clarification, I've got the point.
