### ISSUE TITLE
Enable "Add Using for NuGet/reference assembly" by default

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#20255]

**Comment by jcouv** [comment]
Is this still planned for 15.5?

**Comment by dpoeschl** [comment]
I hope so. @Pilchie?

**Comment by Pilchie** [comment]
I think it's too late for the change now, but we should make as early as possible in 15.6.  Note that a part of this was tied to enabling navigation features in OOP by default to trade some VM

**Comment by kuhlenh** [comment]
@pilchie @dpoeschl I didn't think the OOP work was verified as successful yet, was it? I have lots of CPU issues running it on my machine...

**Comment by CyrusNajmabadi** [comment]
@kuhlenh That's the first i've heard of any issues here.  What CPU problems do you have running it on your machine?
