### ISSUE TITLE
FAR: Group headers should not count no results as a result

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#20259]
**Steps to Reproduce**:

1. Create a console application.
2. FAR on Main

**Expected Behavior**:
FAR says there are no results

**Actual Behavior**:
It has a node that says no results, but the rollup says one result.  I know the definition *might* count, but I don't want it too, especially if the definition is from a differnt project or from metadata.

![far](https://user-images.githubusercontent.com/312835/27206401-2e8ea210-51ec-11e7-8447-8c951d2e280c.png)

**Comment by lineralpha** [comment]
IEntryBucket2.ShowCount to control whether to show the count or not

**Comment by CyrusNajmabadi** [comment]
Ok.  That sorta works:

![image](https://user-images.githubusercontent.com/4564579/27554605-c9590dce-5a63-11e7-84e0-564cc07b2930.png)

However, it's still a bit wonky in cases like so:

![image](https://user-images.githubusercontent.com/4564579/27554615-d4e8fa14-5a63-11e7-91b8-04a6262ae7cc.png)

**Comment by CyrusNajmabadi** [comment]
@lineralpha is there a good way i could programatically examine these buckets and disable the count in cases like this?

**Comment by CyrusNajmabadi** [comment]
Ideal would be a way to mark a row as 'not counting' for purposes of this aggregated value.  Or, alternatively, providing a dummy 'row' that you guys would show when there are no actual rows to show.  Right now we're faking that concept by making this special row.  But the fakery definitely leaks out a bit.  it would be nice if the table had the idea of a bucket+zero-real-rows as a first class concept here.  Thoughts @lineralpha ?

**Comment by lineralpha** [comment]
The ShowCount doesn't really work great in this cascaded grouping case. 

I checked all the column contents for the definition entry in this case
![image](https://user-images.githubusercontent.com/5386041/27566854-af122160-5a9c-11e7-8e1f-673c212f1325.png)

Does it make sense if the definition does not have references, the File/Path/Project columns should not have values? 

The table creates buckets based on entries. The idea of "not counting" dummy entry might work. If we have some way to allow you to specify that this dummy entry should not be counted in any buckets, that might solve the problem. Make sense?

**Comment by lineralpha** [comment]
Seems things are a bit complicated. Assuming the count number were fixed on the definition bucket, What count number should we show for the project bucket in below two grouping scenarios:

![image](https://user-images.githubusercontent.com/5386041/27567156-d9ebdf28-5a9e-11e7-9bc7-b4f3ab7d3fff.png)

![image](https://user-images.githubusercontent.com/5386041/27567165-ed8aa122-5a9e-11e7-9490-c909716be4b6.png)

**Comment by CyrusNajmabadi** [comment]
> The table creates buckets based on entries. The idea of "not counting" dummy entry might work. If we have some way to allow you to specify that this dummy entry should not be counted in any buckets, that might solve the problem. Make sense?

Yes.  Would you be able to provide this?

**Comment by CyrusNajmabadi** [comment]
> Assuming the count number were fixed on the definition bucket, What count number should we show for the project bucket in below two grouping scenarios:

I would expect in:

![image](https://user-images.githubusercontent.com/4564579/27596626-f546db62-5b14-11e7-8cbe-56c4341f1b6c.png)

to see (0), (0)

and in:

![image](https://user-images.githubusercontent.com/4564579/27596637-ff8a7926-5b14-11e7-833e-bddecc1bdf01.png)

to see (1)

**Comment by CyrusNajmabadi** [comment]
basically, the numbers would be the aggregate count of non-dummy rows in all children of a bucket

**Comment by lineralpha** [comment]
> Yes. Would you be able to provide this?

Can you open a bug for us?

**Comment by CyrusNajmabadi** [comment]
Sure.  here you go!   https://devdiv.visualstudio.com/DevDiv/_workitems/edit/457565  Thanks @lineralpha

**Comment by CyrusNajmabadi** [comment]
Note: the bug covers some sort of system whereby we can mark a row as not being a real reference.  Such rows would not be counted in the bucket counts, and would not need things like filepaths/lines/columns.

THanks!

**Comment by dpoeschl** [comment]
The platform fix isn't scheduled until a future release.

**Comment by CyrusNajmabadi** [comment]
@jinujoseph Platform team closed this out.  What's the right thing to do on our end when that happens?

**Comment by jinujoseph** [comment]
@CyrusNajmabadi two options, Close this issue as external or request editor to open(with justification on priority)  and keep this open till that gets resolved.

**Comment by CyrusNajmabadi** [comment]
Given teh small amount of feedback over this amount of time, i'm fine with closing as external :-)

**Comment by CyrusNajmabadi** [comment]
Closing as external.
