### ISSUE TITLE
'as' and 'is' should not be recommended after typing a decimal in a number.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#2025]
Ported from TFS WorkItem: **531128**

---

**Repro Steps:**

REPRO:

1.&nbsp; Paste the following C# code:

class C<BR>{<BR>&nbsp;&nbsp;&nbsp; void M()<BR>&nbsp;&nbsp;&nbsp; {<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; var x = 1$$2;<BR>&nbsp;&nbsp;&nbsp; }<BR>}

2.&nbsp; At the '$$' type a period.

&nbsp;

RESULT:

The completion list is shown with 'as' and 'is' present.

&nbsp;

EXPECTED:

No completion list.

---

**Revisions:**

1) Created By Brett Forsgren (11/28/2012 9:16:09 PM)

---

2) Edited By Kevin Pilch-Bisson (2/15/2015 9:18:18 PM)

Port to Unknown and mark &quot;Up for grabs&quot;

---

**Comment by balajikris** [comment]
I couldn't repro this locally when i was testing something similar, please see if this reproes before starting on a fix. /cc: @kuhlenh

**Comment by CyrusNajmabadi** [comment]
No repro.
