### ISSUE TITLE
Usefulness of Classification APIs without a SemanticModel

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#20261]
Hi, I'm trying to use the C# Classification APIs to implement syntax highlighting for my app. After I saw the [ConsoleClassifier](https://github.com/dotnet/roslyn/blob/master/src/Samples/CSharp/ConsoleClassifier/Program.cs) sample I thought they would be the perfect tool for the job, but things didn't turn out as expected. One reason for this is that my app (in its current stage) is just a single-file code viewer, and can't really bring in other files to build the semantic model/form a compilation with. In other words, this is how I've created the `Document` for each code file to pass to `Classifier`:

```cs
private static Document CreateDocument(string sourceText)
{
    var workspace = new AdhocWorkspace();
    var solution = workspace.CurrentSolution;
    var project = solution.AddProject(string.Empty, string.Empty, LanguageNames.CSharp);
    return project.AddDocument(string.Empty, sourceText);
}
```

Of course, I can't expect to have perfect highlighting because Roslyn has no idea about anything besides the current `.cs` file. So code highlighting looks like this:

![149758617230929](https://user-images.githubusercontent.com/9159214/27211300-570b4826-5226-11e7-84e1-395feb43eeae.png)

I was not surprised that things like `SyntaxReplacement.Create` didn't highlight, since the compiler can't tell whether it's a class or a field/property just by looking at the expression. However, I was surprised to see the return types of properties/methods (i.e. `SyntaxReplacement`) and types surrounded by `typeof()` were not highlighted, since the context they're used in implies they have to be types. I traced this down to the fact return types, `typeof()` types, and parameter types were being classified as plain identifiers with the following console app:

```cs
using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Classification;
using Microsoft.CodeAnalysis.Text;

namespace ClassLibrary1
{
    public class Class1
    {
        public void Foo()
        {
            var source = SourceText.From(@"
class C
{
    Type1 M(Type2 param)
    {
        var t = typeof(Type3);
    }
}");
            var ws = new AdhocWorkspace();
            var doc = ws.AddProject("", LanguageNames.CSharp).AddDocument("", source);
            var spans = Classifier.GetClassifiedSpansAsync(doc, new TextSpan(0, source.Length)).Result;

            var span1 = spans.First(s => source.GetSubText(s.TextSpan).ToString() == "Type1");
            Console.WriteLine($"Type1: {span1.ClassificationType}"); // Outputs 'Type1: identifier'

            var span2 = spans.First(s => source.GetSubText(s.TextSpan).ToString() == "Type2");
            Console.WriteLine($"Type2: {span1.ClassificationType}"); // Outputs 'Type2: identifier'

            var span3 = spans.First(s => source.GetSubText(s.TextSpan).ToString() == "Type3");
            Console.WriteLine($"Type3: {span1.ClassificationType}"); // Outputs 'Type3: identifier'
        }
    }
}
```

Is there anyway to circumvent this and get return/parameter/`typeof()` types treated specially so I can highlight them green, or are the Classification APIs not the right tool for this job without a semantic model? Thanks.

**Comment by CyrusNajmabadi** [comment]
> Is there anyway to circumvent this and get return/parameter/typeof() types treated specially so I can highlight them green, or are the Classification APIs not the right tool for this job without a semantic model? Thanks.

It sounds like you're not actually doing semantic analysis.  Semantic analysis means that we actually go in and figure out what htings mean, and then classify appropriately.  For example we could classify "Int32" as a struct-type, and "Object" as a class-type.  

Here, what you're doing is *syntactic* analysis.  You're not actually figuring out what things mean, you're just using where they exist syntactically to make a decision.  If that's the case, just get a syntax tree for this stuff and do your own analysis.  For example, you could use SyntaxFacts.IsTypeOnlyContext to say "this node is in a place where only types are allowed... so i shall classify it as a type" (even if it really isn't a type at the end of the day.

**Comment by jamesqo** [comment]
@CyrusNajmabadi Hm, I see. Interesting response because I hadn't really thought about that distinction before; thanks for the nice and clear explanation. I suppose I'll return to these APIs when I add more advanced support for C# in my app.
