### ISSUE TITLE
Name suggestions don't use alias-names properly

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#20273]
i.e.:

![image](https://user-images.githubusercontent.com/4564579/27234461-ff8ceb9e-5271-11e7-9ee9-af3cf0fc740d.png)

I would expect to be offered "stringTable" and "table" as potential names here.

**Comment by CyrusNajmabadi** [comment]
Tagging @rchande

**Comment by rchande** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/20792
