### ISSUE TITLE
Documentation for discards is contradictory

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#20274]
I'm trying to understand https://github.com/dotnet/roslyn/blob/master/docs/features/discards.md

It has:

> In C#7.0, they can appear in the following contexts:

> - ...
> - is patterns, such as `x is int _`
> - switch/case patterns, such as `case int _:`

But then (emphasis mine):

> The second representation of discards is using the expression `_` as a short-hand for `var _`, when no variable named _ is in scope. It is allowed in out vars, deconstruction assignments and declarations, and plain assignments (`_ = IgnoredReturn();`). **It is, however, not allowed in C#7.0 patterns.**

So is it allowed in C# 7.0 patterns or not? It looks like it's fine to use it with a type pattern:

```csharp
object x = 5;
// This is fine
if (x is int _ || x is string _)
{
}
```

Is the note trying to indicate that it can't be used as a shorthand for a `var` pattern, i.e. this is not allowed?

```csharp
object x = 5;
if (x is _) // Invalid, not equivalent to if (x is var _)
```

? Some clarification would be much appreciated :)

**Comment by gafter** [comment]
"It" in this sentence refers to the same noun phrase that "it" refers to in the previous sentence, which is the "second representation" (using the expression `_` as a short-hand for `var _`, when no variable named `_` is in scope) that is not allowed in C# 7.0 patterns. Your examples, which *do* work, are not using `_` as an expression.

**Comment by jskeet** [comment]
Okay, I see. If this becomes part of more widely-read documentation, I think it would be worth making that clearer (with examples), but while it's only in the Roslyn github repo it's fine.

Thanks!
