### ISSUE TITLE
Extract local misses occurrence with implicit receiver

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#2027]
Ported from TFS WorkItem: **996944**

---

**Repro Steps:**

Extract all occurrences of `**P**`.

``` C#
class Program
{

      public virtual int P { get; set; }

       public string M()
        {
        var p1 = **this.P**.ToString();
        return p1 + **P**;
        }
}

```

Expected: Both `**this.P**` and `**P**` are extracted.

Actual: Only `**this.P**` is extracted.

---

**Revisions:**

1) Created By Andrew Casey (ROSLYN) (7/30/2014 10:15:20 AM)

---

2) Edited By Kevin Pilch-Bisson (2/15/2015 9:05:32 PM)

Yes, we should do this eventually.&nbsp; Put on GitHub in Unknown/Up for Grabs.

---

**Comment by CyrusNajmabadi** [comment]
Clsoing out due to age and lack of broader feedback.
