### ISSUE TITLE
Generate Equals should use pattern declaration if available

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#20296]
Currently, we generate the following for a sample struct:
```C#
struct S1
{
    int field;

    public override bool Equals(object obj)
    {
        if (!(obj is S1))
        {
            return false;
        }

        var s = (S1)obj;
        return field == s.field;
    }
}
```

We should use a pattern declaration there if available:
```C#
struct S1
{
    int field;

    public override bool Equals(object obj)
    {
        if (!(obj is S1 s))
        {
            return false;
        }

        return field == s.field;
    }
}
```

**Comment by 333fred** [comment]
We could actually simplify it further:
```C#
struct S1
{
    int field;

    public override bool Equals(object obj) =>
        obj is S1 s && field == s1.field;
}

**Comment by CyrusNajmabadi** [comment]
I agree.  The only reason we didn't do this was because this feature is currently defined at a language neutral layer, and VB doesn't have patterns.  We'd have to do some more complex refactorings to make it possible to do this sort of thing.

**Comment by CyrusNajmabadi** [comment]
This works now (and we have tests for this like `TestEqualsSingleField_Patterns`).
