### ISSUE TITLE
Incorrect inline temporary variable result

### ISSUE THREAD

**Issue by hughbe** [dotnet/roslyn#20298]
**Version Used**: 
2.2.0.61624

**Steps to Reproduce**:

Use the "Inline Temporary Variable" refactoring on the `clonePath

```cs
using System;
using System.Runtime.InteropServices;

namespace Test
{
    public class SafeNativeMethods
    {
        public class Gdip
        {
            internal static int GdipClonePath(HandleRef path, out IntPtr clonepath) { clonepath = (IntPtr)10; return 1; }
        }
    }

    public class GraphicsPath
    {
        public GraphicsPath(IntPtr path, int x) { }

        public object Clone()
        {
            IntPtr clonePath = IntPtr.Zero; // ACTION: Inline this temporary variable using the lightbulb menu

            int status = SafeNativeMethods.Gdip.GdipClonePath(new HandleRef(), out clonePath);

            if (status != 0)
                throw new Exception();

            return new GraphicsPath(clonePath, 0);
        }
    }
}
```

## Expected

```cs
using System;
using System.Runtime.InteropServices;

namespace Test
{
    public class SafeNativeMethods
    {
        public class Gdip
        {
            internal static int GdipClonePath(HandleRef path, out IntPtr clonepath) { clonepath = (IntPtr)10; return 1; }
        }
    }

    public class GraphicsPath
    {
        public GraphicsPath(IntPtr path, int x) { }

        public object Clone()
        {
            int status = SafeNativeMethods.Gdip.GdipClonePath(new HandleRef(), out IntPtr clonePath); // EXPECTED: inlined

            if (status != 0)
                throw new Exception();

            return new GraphicsPath(clonePath, 0);
        }
    }
}
```

## Actual

```cs
using System;
using System.Runtime.InteropServices;

namespace Test
{
    public class SafeNativeMethods
    {
        public class Gdip
        {
            internal static int GdipClonePath(HandleRef path, out IntPtr clonepath) { clonepath = (IntPtr)10; return 1; }
        }
    }

    public class GraphicsPath
    {
        public GraphicsPath(IntPtr path, int x) { }

        public object Clone()
        {
            IntPtr clonePath = IntPtr.Zero; // DIFFERENCE: this hasn't been inlined!

            int status = SafeNativeMethods.Gdip.GdipClonePath(new HandleRef(), out clonePath);

            if (status != 0)
                throw new Exception();

            return new GraphicsPath(IntPtr.Zero, 0); // DIFFERENCE: this now always returns IntPtr.Zero
        }
    }
}
```

Gif:
![uodnqlwkm0](https://user-images.githubusercontent.com/1275900/27257924-0daefafc-5414-11e7-8e2c-5b8917cd9b53.gif)

**Comment by hughbe** [comment]
Expected:

```cs
IntPtr clonePath = IntPtr.Zero;

int status = SafeNativeMethods.Gdip.GdipClonePath(new HandleRef(), out clonePath);

if (status != 0)
    throw new Exception();

return new GraphicsPath(IntPtr.Zero, 0);
```

Actual:
```
int status = SafeNativeMethods.Gdip.GdipClonePath(new HandleRef(), out IntPtr clonePath);

if (status != 0)
    throw new Exception();

return new GraphicsPath(clonePath, 0);
```

**Comment by miloush** [comment]
Your expected code is not equivalent to your source code. 

Looks like your expected code is based on the knowledge of the GdipClonePath flow and if that's the case, you could have just said that the expected code is simply
```C#
throw new Exception();
```

The actual generated code is equivalent to your original code which is the aim of these light bulb suggestions.

**Comment by hughbe** [comment]
Oh derp, I'm super sorry. I just realised that I got the actual result wrong - if you look at the video you can see. 
I've edited my comment but for reference this is the result!

```
int status = SafeNativeMethods.Gdip.GdipClonePath(new HandleRef(), out IntPtr clonePath);

if (status != 0)
    throw new Exception();

return new GraphicsPath(IntPtr.Zero, 0);

```

**Comment by hughbe** [comment]
Here's a gif
![uodnqlwkm0](https://user-images.githubusercontent.com/1275900/27257891-16809542-5413-11e7-81f1-913c137a1bea.gif)

**Comment by CyrusNajmabadi** [comment]
Sorry, i'm getting very confused.  Can you please be clear what your original source code was, what variable you performed the refactoring operation on, what result you got, and what result you expected to get.  Thanks!

**Comment by hughbe** [comment]
@CyrusNajmabadi sorry, I confused myself. I took a step back and updated the error with proper results for expected and actual.

I've also highlighted the difference in caps :)

**Comment by CyrusNajmabadi** [comment]
This is working as intended.  As the preview shows, there is an error here.  (that's why we say 'conflicts detected').

Specifically, we cannot 'inline' an expression into an 'out' location.  After all "out IntPtr.Zero" doesn't make any sense.  As the code cannot be inlined properly, we also don't remove the declaration, as per:

https://github.com/dotnet/roslyn/blob/master/src/Features/CSharp/Portable/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.cs#L231

--

This is an example of a case where don't want to suppress this refactoring, even though it doesn't fully work in all scenarios.  After all, you may want to inline IntPtr.Zero to dozens of locatoins, and this will help you do this.  But you'll still have to go fix up a few locations that we tell you about that we can't necessarily inline ourselves.

**Comment by CyrusNajmabadi** [comment]
Also, your expected code does not match what the intent of the feature actually is.  Your expected code says:

```c#
            return new GraphicsPath(clonePath, 0);
```

But the point of 'inline temporary variable' is that it gets rid of the temporary variable, takes the value it was initialized with, and inserts it at all the reference sites.  

--

We do also have a feature called "inline variable decalration" that will do what you want.  However, it only works if the variable doesn't have an initializer.  So if you had:

```c#
 public object Clone()
        {
            IntPtr clonePath;

            int status = SafeNativeMethods.Gdip.GdipClonePath(new HandleRef(), out clonePath);
```

Then it would offer to convert that to the code you want.  We can't convert the code if it has an initializer as that might affect semantics.
