### ISSUE TITLE
Completion for Task-like missing values

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#20297]
When awaiting task-like objects, some elements are missing from the completion list, such as `ConfigureAwait`.

**Comment by Pilchie** [comment]
We just display the result of LookupSymbols...

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler

**Comment by jcouv** [comment]
FYI @cston

**Comment by TyOverby** [comment]
@333fred: do you have an example task-like that exhibits this behavior?

**Comment by 333fred** [comment]
@TyOverby I was using the AsyncLazy class from AsyncEx: https://github.com/StephenCleary/AsyncEx

**Comment by TyOverby** [comment]
@333fred AsyncLazy has EditorBrowsableState.Never set.  https://github.com/StephenCleary/AsyncEx/blob/master/src/Nito.AsyncEx.Coordination/AsyncLazy.cs#L158
