### ISSUE TITLE
Add unit test to ensure that VSDiagnosticAnalyzerProviderService returns paths with $RootFolder$ strings expanded

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#2029]
We recently ran into an issue fixed by PR #2001 that caused the VS build to be broken (no diagnostics, squiggles and light bulb).

We should add a unit test to ensure this particular issue never surfaces again.

**Comment by heejaechang** [comment]
I already have pull request out for this bug. Can you code review the PR?


-          heejae
