### ISSUE TITLE
Lambda method with no capture in static class generates instance method

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#20315]
**Version Used**: 
```
➜  ~ csc
Microsoft (R) Visual C# Compiler version 2.3.0.61719 (5fbdd5c5)
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Steps to Reproduce**:

1. See this sample: https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAGAAhwEYBuAWACh8jiA6AJQFcA7GNMOC6wkxuAGYY4AY3YB7Ft1gR2IogCYCAWQhoWAYQzQoVAN5UCRAMwEZcogBYValgAoAlIYIHKASBIKAPOOAArURgkAl8AsWDQwIj/QIA+Am0wYAATCAIAXgI7SLECCGiwmAJgAsCCEVLc5IcM+L0NSShxYToAdQQ0eAAZdTg7ACI9PABfPWJRhVHjYf7g/OLgioJq0gJh7iNhqmGgA=

**Expected Behavior**:
I expect the method the lambda generates to be a static one, not an instance method. Although the lambda cache is static, it seems weird to have an _instance method_ on a _static class_. It has no performance impacts, but it leads to weird (but apparently valid) IL inside a static class
```
.method assembly hidebysig 
            instance void '<Main>b__0_0' (
```

**Actual Behavior**:
The generated method in the lambda closure is generated as an instance method

**Comment by Pilchie** [comment]
Tag @jaredpar and @VSadov

**Comment by Therzok** [comment]
I misread the IL, there is a nested class being generated with the instance method. Still would like to know the reason behind the method not being static.

**Comment by jaredpar** [comment]
> Still would like to know the reason behind the method not being static.

Performance. There is a measurable difference in invoking the delegate as an instance method vs. a static one. @VSadov has the details but IIRC it has to do with how the JIT handles arguments on the execution stack. They line up better for instance methods than static ones.

**Comment by Therzok** [comment]
👍 I have no qualms about closing this issue then, just wanted to find out why this was the case.
