### ISSUE TITLE
IOperation represenation of default switch case label

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#20312]
See discussion here: https://github.com/dotnet/roslyn/pull/20276#discussion_r122769104

Three possible design approaches:
1. Add a new IOperation node for default case label.
2. Re-use ISingleCaseValueClause with case kind Default for default label in both normal and pattern case clauses.
3. Re-use ISingleCaseValueClause with case kind Default for default label in normal switch statement and re-use IPatternCaseClause with case kind Default in pattern switch statement.

**Comment by jinujoseph** [comment]
**Design Team Decision**

Go with the first approach " Add a new IOperation node for default case label" 
Note: We already have seperate casekind for defaults

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/20707
