### ISSUE TITLE
Add ExpressionBody to BaseMethodDeclarationSyntax.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#2032]
I recommend changing the syntax tree API by adding `ExpressionBody` to `BaseMethodDeclarationSyntax`. It looks like an oversight that it wasn't that way to start with.

@AlekseyTs @AnthonyDGreen

**Comment by gafter** [comment]
Recommend Milestone 1.0 (stable).

**Comment by AnthonyDGreen** [comment]
Does it apply equally well to all derivatives? Constructors?

Regards,

-ADG

Sent from my Windows Phone
________________________________

**Comment by AlekseyTs** [comment]
It is not applicable to constrcutors/destructors for example.

**Comment by gafter** [comment]
There are a couple of

**Comment by AnthonyDGreen** [comment]
Given that it doesn't apply to all derivatives of BaseMethodDeclarationSyntax adding this would seem inappropriate.
