### ISSUE TITLE
[Suggestion] Cursor insertion mode

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#20328]
In Xamarin Studio we had a feature 'cursor insertion mode'. When methods/fields etc. are created the user was able to see where it's created and could've changed that.

Roslyn just inserts newly created code somewhere in the text - would be nice to be able on IDE side to change that. That would require that the IDE can get control of where something is inserted in the tree.

**Comment by Pilchie** [comment]
Tagging @kuhlenh and @DustinCampbell.  This is something we've talked about as well that might be nice to do.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
