### ISSUE TITLE
Audit EditorFeatures to figure out what splitting the WPF dependency would look like

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#20322]
@KirillOsenkov and @ToddGrun want to use some parts of EditorFeatures in Visual Studio for Mac. Some parts of the EditorFeatures layer will depend on editor components that we can ship there, and some depend on WPF (think inline rename's dashboard) that won't have any chance of an easy port. We should audit our features to figure out how things generally land to inform next steps.

I can imagine a few methods of auditing:

1. See what uses IWpfTextView vs. ITextView correctly and incorrectly.
2. Remove the WPF references and see what breaks.

or others.

**Comment by sharwell** [comment]
Sounds like a cool task 👍

**Comment by Pilchie** [comment]
@KirillOsenkov @toddgrun out of curiosity, does mono have the same loader resiliency for allowing types that never end up being jitted that the .NET Framework runtime has?

Not saying we don't want to do this, just wanting to understand the importance of doing all and getting it all right, right now.

**Comment by KirillOsenkov** [comment]
We're not sure about the runtime, but even when we add EditorFeatures to the MEF composition it asks for CallHierarchy, UI.Internal and UI.Wpf. If we had the "lower half" of EditorFeatures that doesn't bring these dependencies that'd be awesome.

**Comment by Pilchie** [comment]
Isn't that a bug in MEF (and/or the configuration of the composition) then?  Anything that does a reflection load of every type in an assembly should be resilient to some of those types failing to load (IMO at least)

**Comment by KirillOsenkov** [comment]
We can't risk shipping a product where we're an inch away from a crash due to a missing dependency and uncertain runtime-specific behavior. The MEF behavior I've mentioned is just one example, I'm pretty sure we've seen other things broken as well.

**Comment by KirillOsenkov** [comment]
I was thinking about how to do this in principle: Create a new WpfEditorFeatures project and move the WPF-and-friends-dependent types there? Like CallHierarchy and stuff?

Or create a new CoreEditorFeatures project and move everything that's not WPF-dependent there?

What should the name of the new assembly be? Microsoft.CodeAnalysis.EditorFeatures.Wpf.dll? Microsoft.CodeAnalysis.WpfEditorFeatures.dll? Microsoft.CodeAnalysis.CoreEditorFeatures.dll? Microsoft.CodeAnalysis.EditorFeatures.Core.dll?

**Comment by Pilchie** [comment]
@KirillOsenkov depending on how much there is, it might be simpler to just push the WPF stuff up to the VisualStudio layer.

**Comment by jasonmalinowski** [comment]
@KirillOsenkov That's why this work item exists. Audit what it is and figure out the best plan as a result.

**Comment by jasonmalinowski** [comment]
OK, so auditing through EditorFeatures I've came to a few conclusions.

1. As things often started there and then moved to Workspaces/Features, it's kinda a wasteland of random leftovers.
2. A lot of the WPF dependencies fall into a few common categories, and we could light up a lot of IDE features as long as we had answers to those. (More later.)
3. Making EditorFeatures.Wpf.dll (or just pushing over to the VS layer) is probably the way to go, as otherwise we have to do type forwarding (yes, EditorFeatures has a public surface area.) "CoreEditorFeatures" seems poorly defined, and I hesitate to figure out how we'd refactor that a second time. (ReallyCoreEditorFeatures?)
4. While starting this work, I suspect creating an EditorFeatures.Wpf layer is probably the best approach. Just creating another layer and moving types around we could very quickly create an EditorFeatures without the dependencies for @KirillOsenkov and @ToddGrun. We'd end up with an assembly that contains the stuff still dependent, and then could refactor to remove those dependencies as the editor lights up ways to avoid some of those things. As we near the end of this effort, we could fold the remaining bits into the VS layer if we determine we don't have a long-term plan for that, or leave the bits there if we're still planning on moving these. I think that question largely comes down to specifying exactly what is end goal here and how much we want in VS for Mac running atop EditorFeatures-based stuff.

**Comment by jasonmalinowski** [comment]
Going through stuff that depends on WPF directly (not the WPF portion of the editor, but directly against WPF assemblies):

- Call Hierarchy
    - API uses System.Windows.Media.ImageSource
- Classification
    - Any of the definitions in ClassificationTypeDefinitions.cs, as they use the WPF color types
- Code Action Preview Generation
    - Entire feature creates WPF views
- Edit and Continue
    - Error type definitions, active statement highlighting tag definitions
- EditorNotificationServiceFactory
    - Implementation launches dialogs to ask user things. Abstraction that would be reimplemented.
- Inline Rename
    - Dashboard (custom WPF UI)
    - Tag definitions involve Pen/Brushes
- Line Separators
    - Entire feature is built with a custom adornment
- Navigate To
    - Hacks for converting semi-transparent images to Icons (NavigateToIconFactory.cs, ConvertBitmapSourceToIcon)
- Quick Info
    - All the content we create is WPF based in many ways
- Reference Highlighting
    - Tag definitions involve Pen/Brushes
- (utilities)
    - HighContrastChecker.cs is copied/pasted hackery from the editor and can probably be deleted
ForegroundThreadAffinitizedObject.cs is a dumpster fire

As far as things that depend on IWpfTextView, there is very little. The primary cause is IWpfTextViewCreationListener. The remaining uses are mostly around us creating views for preview windows.

**Comment by KirillOsenkov** [comment]
@mhutch @mkrueger FYI

**Comment by mhutch** [comment]
@jasonmalinowski most all of these sound useful, and it doesn't sound like it would be that difficult to abstract some of them out :)

**Comment by jasonmalinowski** [comment]
The majority of this is complete and resulted in #22105.
