### ISSUE TITLE
Assertion when opening Build settings page on CSharpCompilerSymbolTest project

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#20331]
I'm using `VisualStudio.15.IntPreview/15.3.0-pre.3.0+26615.0.d15rel` with a custom project-system from PR https://github.com/dotnet/project-system/issues/2414

![image](https://user-images.githubusercontent.com/12466233/27347750-84d205fa-55a6-11e7-8ac8-95c9fd7c2612.png)

FYI @srivatsn for triage

**Comment by srivatsn** [comment]
Is this a cps project or an old one?

**Comment by jcouv** [comment]
I think it uses the new SDK. It has "dependencies".

**Comment by srivatsn** [comment]
Ok, then this is somewhat expected - CPS doesn't implement connectionpointcontainer yet and that's what this assert looks like it's saying. However I've never seen this for normal netcore projects.. so interesting. Either way i'll move this to the project system repo.

**Comment by srivatsn** [comment]
This issue was moved to dotnet/project-system#2471
