### ISSUE TITLE
Context tooltip for indent guides should be clickable

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#20347]
It should move the caret to the clicked position.

**Comment by alrz** [comment]
Does the other tooltip (the one that appears once you are on `}` if `{` is not on the screen), also belongs to Roslyn? I think that should be clickable too  (currently it's not hit visible even though it's still onscreen when you hover).

**Comment by Pilchie** [comment]
What do you mean by "context tooltip"

**Comment by alrz** [comment]
@Pilchie Same as https://github.com/dotnet/roslyn/issues/15872

**Comment by Pilchie** [comment]
Okay - that's what I thought.  In that case, tagging @markw-t, since we'd probably want to put this in the platform.

**Comment by markw-t** [comment]
Interesting idea. Is your main scenario for this to move the caret to a location that is currently scrolled offscreen (like the top of a method or loop)?

**Comment by alrz** [comment]
>Is your main scenario for this to move the caret to a location that is currently scrolled offscreen (like the top of a method or loop)?

Yes -- both xaml and cs. This is a lot more useful than any shortcut key like "goto containing method" etc.

**Comment by Pilchie** [comment]
@alrz I suggest filing with send feedback so that this can get on the platform team's radar.
