### ISSUE TITLE
Code analyser does not trigger unless code file is opened

### ISSUE THREAD

**Issue by realekhor** [dotnet/roslyn#20354]
**Version Used**: 2.0.0.6140902

We are currently building a series of code analyzers within my team and when we test it with single files console apps, it works like a charm. However, when we test it with large code bases, the analyzers don't seem to trigger unless each file is opened. And even at that, the analysis only seems to process opened files.

Any help will be appreciated.

**Comment by sharwell** [comment]
![image](https://user-images.githubusercontent.com/1408396/27385200-646cd40a-5657-11e7-89c7-cd90c77e4941.png)

**Comment by realekhor** [comment]
Hi @sharwell thanks a million! that resolved it. Thank you :)
