### ISSUE TITLE
Roslyn and project properties don't agree on what C# 6/7 are called

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#20353]
Properties:
![image](https://user-images.githubusercontent.com/1103906/27374976-125a95da-56b1-11e7-9ebe-64680bcfacdf.png)

Code fix:
![image](https://user-images.githubusercontent.com/1103906/27374954-05262cf8-56b1-11e7-83c7-e592f874d55b.png)

Is it 6.0 or 6?

**Comment by davkean** [comment]
tag @jcouv

**Comment by jcouv** [comment]
For 7, we're aligning on "7.0".
For 6, I'm not sure. I thought we preferred "6" over "6.0".

**Comment by jcouv** [comment]
@jaredpar @gafter Can you confirm that C# 6 (and older) should use single digit version ("6" instead of "6.0")?

For reference, we've made a change to align 7 to use "7.0" (https://github.com/dotnet/roslyn/pull/19802).

**Comment by jaredpar** [comment]
> For 6, I'm not sure. I thought we preferred "6" over "6.0".

There may have been a preference in theory, but in practice we seem to use both with equal frequency. 😦 

The preference should be single digit 6 and before (2, 3, 6, etc ...) and two digits 7 and after (7.0, 7.1, 8,0, etc ...).
