### ISSUE TITLE
Support for .editorconfig insert_final_newline and trim_trailing_whitespace

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#20356]
These are not are mentioned in the [documentation](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options).

I tested `trim_trailing_whitespace` for a while and came to the conclusion that it has no effect. 
Also, these do not appear in the Roslyn 2.2.0 source code.

Please support them and document the behavior of the editor when the settings are active.

`trim_trailing_whitespace` is particularly important because, depending on the codebase you're working in, you either *really* want this forced on or *really* want this forced off. It probably should not interfere with verbatim strings, but that should be discussed.
`insert_final_newline` is very similar.

**Comment by jnm2** [comment]
Found https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options, updated issue.

**Comment by sharwell** [comment]
I *strongly* recommend not using the `trim_trailing_whitespace` option. Even if Visual Studio provides special handling for verbatim string literals, it is a near-certainty that other editors will not. Implementation of the same feature via an analyzer that ensures language semantics are accounted for is the best approach, and is the one used by StyleCop Analyzers for its rule [SA1028](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1028.md).

**Comment by Pilchie** [comment]
Tagging @olegtk and @jasonmalinowski have we talked about whether these would be platform supported or Roslyn supported?

**Comment by olegtk** [comment]
It's supported by the core editor since 15.3 (only applied to new edits though). I realize it can break some C# code, but it's a universal property we have to support. Users might choose not to enable it in their .editorconfig.

**Comment by jnm2** [comment]
That makes sense. Can you please provide a C#-safe `csharp_trim_trailing_whitespace` option?

**Comment by Pilchie** [comment]
@olegtk All 3 are supported?

**Comment by olegtk** [comment]
@Pilchie you mean insert_final_newline and trim_trailing_whitespace? Yes, they are supported since Preview1 or Preview2.

**Comment by Pilchie** [comment]
Yeah, the third I was thinking of was charset, but I see that that is now supported.

**Comment by Pilchie** [comment]
I'm going to close this issue as external, but if you want, it might make sense to file a new feature request issue for the idea of `csharp_trim_trailing_whitespace`

**Comment by jnm2** [comment]
Thanks. https://github.com/dotnet/roslyn/issues/20398
