### ISSUE TITLE
"Use expression body for property" isn't available when targeting 6.0

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#20352]
1. Project Properties -> Build -> Advanced -> Language Version -> C# 6.0
2. With the caret on Foo, CTRL+.

``` C#
    class Program
    {
        public string Foo
        {
            get { return null; }
            set { }
        }
    }
```

**Expected Behavior**:
For "Use expression body for accessors" to be available

**Actual Behavior**:
"Use expression body for accessors" is not available

Is this because this method might contain a throw expression? If so, might the new language code fix help with that?

![image](https://user-images.githubusercontent.com/1103906/27374910-d3fd5aac-56b0-11e7-9a55-3f3280b43df2.png)

**Comment by sharwell** [comment]
Most expression-bodied members are available in C# 6. However, there are three exceptions:

1. Property and event accessors (this is the `get`/`set` or `add`/`remove`)
2. Constructors
3. Destructors

**Comment by Pilchie** [comment]
Use expression body for a get only property should be supported, but as @sharwell notes, C# 6 didn't support it for accessors, but that doesn't seem to be the case.

**Comment by CyrusNajmabadi** [comment]
Sorry, i'm a bit confused by this.  Isn't this by design.  Expression bodied accessors are not avialable in C# 6.  If you try to use them, you get:

![image](https://user-images.githubusercontent.com/4564579/27553916-9ec5c52c-5a61-11e7-9fc0-7f5b95f28262.png)

So why would we wnat to offer this to the user?

**Comment by Pilchie** [comment]
Not even expression bodied properties/methods worked when I tried it.

**Comment by CyrusNajmabadi** [comment]
Oh.  THis bug is about also offering the feature for getter-only properties.  ok.  we can add support for that.  it is somewhat of a PITA as we now need to track precisely what we're being called on to validate the right version.

**Comment by sharwell** [comment]
@CyrusNajmabadi Seems like this should be easy. Just run treat the "Use expression-bodied accessors" property as false when the language version is 6 and everything will just work.
