### ISSUE TITLE
Typo in editorconfig storage location for csharp_space_around_binary_operators

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#20355]
I think I found a typo which looks like it will cause a bug.
Looks like it should be `"csharp_space_around_binary_operators"`, not `"csharp_space_around_binary_operators "` with the extra space.

It's in master as well as in the current release version. Introduced in c0cd2911052fc153b39ad0264d3c8bdb65c788c8.

https://github.com/dotnet/roslyn/blob/version-2.2.0/src/Workspaces/CSharp/Portable/Formatting/CSharpFormattingOptions.cs#L126

**Comment by Pilchie** [comment]
Thanks for finding!
