### ISSUE TITLE
Code fix for going directly from expression body -> block body

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#20351]
We have a code fix for going directly from:

``` C#
        public IProjectTree Parent
        {
            get
            {
                throw new NotImplementedException();
            }
        }
```

to:

``` C#
        public IProjectTree Parent => throw new NotImplementedException();
```

But to go the reverse, you need to invoke two code fixes:

One to go to ("Use body block for properties"):

``` C#
        public IProjectTree Parent { get => throw new NotImplementedException(); }
```

And another to go to ("Use body block for accessors"):

``` C#
        public IProjectTree Parent
        {
            get
            {
                throw new NotImplementedException();
            }
        }
```

This is quite annoying as you have to move the cursor to invoke the second one. This bit me today, when I tried to remove C# 7.0'isms ("throw expressions") from the code base (because build service is using 6.0) and assuming that after the code fix the code was all good (in a hurry, not paying much attention). It was not.

**Comment by sharwell** [comment]
:bulb: I believe this feature is controlled by the "Use expression-bodied accessors" option. When set to "Prefer", the conversion to a block-bodied property will use an expression-bodied accessor. Otherwise, it goes all the way to a full property.

**Comment by sharwell** [comment]
I filed #20360 for a special case here.

**Comment by sharwell** [comment]
I'm closing this broader issue as by-design, though it was instrumental in revealing several closely related bugs. Thanks for filing this!

**Comment by sharwell** [comment]
I also filed #20363 to fix the round-trip behavior anomaly.
