### ISSUE TITLE
[IOperation] Should out of range enum conversion be invalid?

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#20365]
Ran across this scenario in my C# explicit conversion testing:
```C#
class C1
{
    public void M1()
    {
        E2 e2 = (E2)E1.Thousand;
    }
}

enum E1
{
    One = 1, Thousand = 1000
}

enum E2 : byte
{
    Two
}
```
We get the following conversion:
```
IOperation tree for "(E2)E1.Thousand"

IConversionExpression (ConversionKind.CSharp, Explicit) (OperationKind.ConversionExpression, Type: E2, Constant: null) (Syntax: '(E2)E1.Thousand')
  IFieldReferenceExpression: E1.Thousand (Static) (OperationKind.FieldReferenceExpression, Type: E1, Constant: 1000) (Syntax: 'E1.Thousand')
```
The constant value for the underlying BoundConversion is `bad`, and the underlying BoundConversion does not have any errors for this element (`HasErrors` and `HasAnyErrors` are both false). However, the statement is clearly invalid, and I feel like our invalid flag should probably be set. Opinions, @dotnet/analyzer-ioperation @AlekseyTs?

**Comment by mavasani** [comment]
Didn't we decide to get rid of the invalid flag on IOperation @heejaechang?

**Comment by jinujoseph** [comment]
yes we did https://github.com/dotnet/roslyn/issues/18089

**Comment by 333fred** [comment]
Ah, ok. Closing this then.
