### ISSUE TITLE
Expression-bodied accessors option should be secondary to expression-bodied properties

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#20363]
**Version Used**: 15.3 Preview 3

Currently the available options are **When possible** and **When on single line**. However, as observed by myself and reported by @davkean in #20351, the current settings are not intuitive with respect to the option for using expression-bodied properties. I believe the behavior of these options should be tuned, ~~or a new option provided,~~ such that the setting becomes:

1. When the form of a property allows both expression-bodied property and expression-bodied accessor, always prefer expression-bodied property.
2. Otherwise, fall back to the behavior currently used for expression-bodied accessors.

**Comment by sharwell** [comment]
Tagging @dotnet/roslyn-ide: we need to decide if this should modify the current option behavior, or be a new option. I would be in favor of modifying the current options, since it's what at least two users were expecting it to do already and that approach avoids versioning headaches.

**Comment by Pilchie** [comment]
I don't understand the proposed changes.

**Comment by Pilchie** [comment]
Nevermind - I read it again now, and I do understand, and agree.

**Comment by Pilchie** [comment]
To clarify - I agree with modifying the current option.

**Comment by Pilchie** [comment]
@kuhlenh @DustinCampbell would love to hear your thoughts here too.

**Comment by kuhlenh** [comment]
I would also prefer to modify the existing option to do the "right" thing than add a new option. This is a new feature so I'm happy about us being proactive about defining its style.

**Comment by sharwell** [comment]
I modified the title to reflect the direction we all agree on.

**Comment by CyrusNajmabadi** [comment]
How does this manifest?  Is there an example of things going 'wrong' that we would see a difference in behavior in?

**Comment by sharwell** [comment]
@CyrusNajmabadi yes I linked another issue in the original post above. That issue would not have occurred.

**Comment by CyrusNajmabadi** [comment]
I'm a bit confused.  What does someone do if they don't want expression bodied properties, but they do want expression bodied accessors?  It sounds like we wouldn't ever respect the option being in that form.  Or is there some way for the user to specify that they like that.  For dave's case, could he not get what he wants by saying "i don't want expression bodied accessors"?

**Comment by sharwell** [comment]
@CyrusNajmabadi That would fall into the category of "form not allowing expression-bodied properties", though in that case it would be per policy instead of per language restriction.

**Comment by CyrusNajmabadi** [comment]
Sorry, i still don't get what is being asked for.  There is a linked bug that doesn't seem to be behaving incorrectly.  Can someone just simply give the actual code example that isn't working 'properly' and what behavior you'd like to see?   That would help avoid an incorrect assumption on my part about what the actual issue is.

**Comment by sharwell** [comment]
@CyrusNajmabadi The behavior change affects two operations:

### Condition for showing *Use expression-bodied accessor*

All of the following are true:

1. Code uses C# 7+
2. Code is not currently an expression-bodied accessor
3. Code can be written as a property with expression-bodied accessors
4. Either of the following is true:
  1. The property is not a getter-only property
  2. "Use expression-bodied properties" is false

### Behavior of *Convert to block-body*

Never uses expression-bodied accessors.

**Comment by CyrusNajmabadi** [comment]
I'm still not sure i understand the top bit.  I think i can manage the bottom bit.

**Comment by sharwell** [comment]
I believe that by implementing the bottom part, the top part will be implemented. The correction to the bottom part represents the difference between the current and desired behaviors.

**Comment by CyrusNajmabadi** [comment]
FWIW, i'd find it much easier to just say, if you have:

```c#
class C
{
    int Prop => 0;
}
```

And you pick "Convert to block body" then you should get:

```c#
class C
{
    int Prop { get { return 0; } }
}
```

i.e. what we started with, and what we want to get out of it.
