### ISSUE TITLE
A Fix All should be available for CS8059 (expression-bodied accessors not available)

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#20361]
**Version Used**: 15.3 Preview 2

**Steps to Reproduce**:

1. Set the language version to C# 6

1. Define two properties with expression-bodied accessors (not supported by C# 6)

    ```csharp
    public int X { get => 0; }
    public int Y { get => 0; }
    ```

1. Use the light bulb on either line to convert the property to a full property or an expression-bodied property (both supported by C# 6)

**Expected Behavior**:

The light bulb to convert to full or expression-bodied property should include Fix All options.

**Actual Behavior**:

No fix all is available, so each property must be converted separately.

**Comment by Pilchie** [comment]
Interesting - this should be relatively easy to support, just adding the new diangostic id.

**Comment by sharwell** [comment]
@Pilchie This diagnostic ID is used for all cases of language version mismatch, so it will be necessary to be more specific somehow so we don't e.g. mix this up with #20362.
