### ISSUE TITLE
[Test failure] BasicCodeActions.GenerateMethodInClosedFile

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#20371]
windows_release_vs-integration_prtest failed on #19490 Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicCodeActions.GenerateMethodInClosedFile ([details](https://ci.dot.net/job/dotnet_roslyn/job/dev15.6/job/windows_release_vs-integration_prtest/380/))
```
MESSAGE:
Assert.Equal() Failure
↓ (pos 13)\r\n
Expected:
Class Foo
 Friend Sub Bar()
 Throw New N···
Actual:
Class Foo
End Class
↑ (pos 13)
+++++++++++++++++++
STACK TRACE:
at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicCodeActions.GenerateMethodInClosedFile() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicCodeActions.cs:line 42
```

**Comment by Pilchie** [comment]
@VSadov is this the same thing you saw in another branch?

**Comment by MattGertz** [comment]
Mondo escrow triage:  keeping while we determine if this is a product issue.

**Comment by Pilchie** [comment]
I don't think this is a product issue.

**Comment by CyrusNajmabadi** [comment]
Hit again: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/5758/testReport/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicCodeActions/GenerateMethodInClosedFile/

**Comment by CyrusNajmabadi** [comment]
Have manually validated that this works.  Skipping tests to unblock PRs.

**Comment by cston** [comment]
Hit [again](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/5812).

**Comment by 333fred** [comment]
Hit again in features/ioperation https://github.com/dotnet/roslyn/pull/20524

**Comment by dpoeschl** [comment]
Again: https://ci.dot.net/job/dotnet_roslyn/job/dev15.3.x/job/windows_debug_vs-integration_prtest/87/

**Comment by dpoeschl** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/dev15.3.x/job/windows_debug_vs-integration_prtest/98/

**Comment by CyrusNajmabadi** [comment]
Fantastic!
