### ISSUE TITLE
[Suggestion] Auto insert brackets in completion

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#20385]
In XS we had a feature bracket auto insertion in comletion list.

Assume that you've a method Foo and complete it with tab or return you end up with:

Foo|

Now in XS with the feature you end up with Foo(|) or Foo()| depending of Foo takes parameters or not. I had some logic to guess where delegates could be so that evnt += Foo| didn't insert the brackets as well as some other places where delegates could be expected.

But usually that was very nice for typing.

**Comment by Pilchie** [comment]
Same idea as https://github.com/dotnet/roslyn/issues/12363.  We've avoided this in the past because we want people to have good "type forward" muscle memory, but something we can consider with decent overtype like brace completion.
