### ISSUE TITLE
CSharpExtractMethod.ExtractViaCodeActionWithMoveLocal is flaky in readonly-ref branch

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#20382]
need to investigate if it is related to the changes in the branch or came with integration

**Comment by Pilchie** [comment]
Tagging with the compiler for now so it's not in triage queries, but please let me know if it looks like an inherited issue.

**Comment by OmarTawfik** [comment]
Bringing to 15.5 for making a decision. @VSadov is this something we should worry about now?

**Comment by VSadov** [comment]
The test is no longer flakey. It consistently fails. Probably just needs updating, but I am not 100% confident in what the right behavior is. So passing to IDE.
