### ISSUE TITLE
Bad performance in inline rename

### ISSUE THREAD

**Issue by rynowak** [dotnet/roslyn#20384]
**Version Used**: 

Using d15prerel 26618.0

**Steps to Reproduce**:

1.  Clone https://github.com/aspnet/Razor
2.  build.cmd /t:restore
3.  Open Razor.sln
4. Open [AttributeStructure.cs](https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Language/AttributeStructure.cs)
5. Do an inline rename on the type name (ctrl+R ctrl+R)

**Expected Behavior**:

Completes in a reasonable amount of time, VS stays reponsive

**Actual Behavior**:

Takes minutes, hangs VS.

I have a perfview trace of this that I can share on corpnet, it's too big to upload on github. Please shoot me a mail or IM if you want me to provide it.

Looking into the trace, the hot path I'm hitting is here:

![image](https://user-images.githubusercontent.com/1430011/27417379-c4ec08de-56c8-11e7-8911-2f654e538a55.png)

The rest of the CPU time is being spent in GC
![image](https://user-images.githubusercontent.com/1430011/27417409-011181b8-56c9-11e7-8d75-3e71628d6001.png)

----- 

It looks like the proximal cause here is dealing with repeated resizes happening during `Combine`. The `Stack<>` type is kind crummy for the usage here, and using `List<>` but treating it as a stack could optimize this by avoiding the intermediate array and using `AddRange` to do a single resize operation.

That said, I don't know really know how/why this got so hot. These are mostly simple .cs files, why we have a syntax tree depth that could cause these kinds of issues is anyone's guess.

**Comment by sharwell** [comment]
:memo: I'm not observing this behavior in 15.3 Preview 2.1, though I did see a gold bar saying 'Roslyn Language Service' is slowing typing performance.

**Comment by Pilchie** [comment]
Seems like @sharwell has an idea of where this issue is, but it may end up in the editor.

**Comment by sharwell** [comment]
@rynowak I brought it down to the ~1 second range with #20425. 😎

**Comment by rynowak** [comment]
Thanks!
