### ISSUE TITLE
MS.CA.Workspaces.Desktop v2.0.0 depends on MSBuild v15.1

### ISSUE THREAD

**Issue by thr0ttles** [dotnet/roslyn#20391]
**Version Used**: 
MS.CA.Workspaces.Common v2.0.0 nuget package
MS.CA.Workspaces.Desktop.dll v2.0

**Steps to Reproduce**:

1. Download MS.CA.Workspaces.Common v2.0.0 nuget package
2. Inspect MS.CA.Workspaces.Desktop.dll using ILDASM and notice it depends on MS.Build 15.1, MS.Build.Framework v15.1, and MS.Build.Tasks.Core v15.1
3. When executing the following line of code in a project that is using MS.Build v14, a LoaderException will occur. The LoaderException is complaining that it can't find MS.Build v15.1. The project with this code is using MS.Build v14.0.

var workspace = Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.Create();

**Expected Behavior**:
MS.CA.Workspaces.Common and MS.CA.Workspaces.Desktop v2.0.0 should depend on MS.Build v14

**Actual Behavior**:
MS.CA.Workspaces.Common and MS.CA.Workspaces.Desktop v2.0.0 depend on MS.Build v15.1

**Comment by Pilchie** [comment]
Yes.  We deliberately updated the dependency as part of the 2.0 packages.

**Comment by thr0ttles** [comment]
@Pilchie thanks. is there a discussion thread somewhere regarding why the 2.0 packages depend on MSBuild v15?

**Comment by Pilchie** [comment]
The 2.0 packages are what ship with VS 2017, which has a dependency on MSBuild 15.

**Comment by thr0ttles** [comment]
@Pilchie noted. thank you.
