### ISSUE TITLE
Consolidate tests for #1702

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#2039]
In code review https://github.com/dotnet/roslyn/pull/1992#discussion_r28466288 it was recommended that the tests be consolidated for performance reasons. This issue tracks that work.

**Comment by AlekseyTs** [comment]
The test are exactly the way I'd like them to be.

**Comment by AlekseyTs** [comment]
Closing as team decided to not enforce any specific style around consolidating unit-tests.
