### ISSUE TITLE
ref extension methods should require 7.2

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#20395]
It appears that ref extension methods work on 7.0

NOTE: `ref readonly this` requires 7.2 because `ref readonly` requires that, but `ref this` is ok with 7.0.

Repro:
Try recent build -

https://dotnet.myget.org/feed/roslyn/package/vsix/0b48e25b-9903-4d8b-ad39-d4cca196e3c7/2.6.0.6182203

direct link:
https://dotnet.myget.org/feed/roslyn/package/vsix/0b48e25b-9903-4d8b-ad39-d4cca196e3c7/2.6.0.6182203

The following works in a default console app (7.0), but it should demand 7.2

```C#
    public static class C1
    {
        public static void Ext(ref this Guid self, int arg)
        {

        }
    }
```

**Comment by VSadov** [comment]
FYI  @OmarTawfik

**Comment by OmarTawfik** [comment]
@VSadov  Will submit a PR for that shortly
