### ISSUE TITLE
SemanticModel's Compilation.References returns empty collection

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#20396]
**Version Used**: 
1.3.2 / 2.0.0/2.2.0

**Steps to Reproduce**:

1. Get a **Vanilla Windows 2012 server machine 64 bit**.
2. Install **.NET Framework 4.6.1**
3. Install **.NET Framework 4.6.1 Runtime**
4. Install **.NET Framework 4.6.1 Targeting Framework.**
5. Install **Visual Studios Microsoft Build Tools 2015**
6. Using following code, try to get values for SemanticModel's **Compilation.References**

```
var workspace = MSBuildWorkspace.Create();
Solution solution= workspace.OpenSolutionAsync(file Path).Result;

foreach(var project in solution.Projects)
{
    foreach(var document in project.Documents)
    {
           SemanticModel sementicModel = document.GetSemanticModelAsync().Result;
           Console.Write(document.Name + " :  " + sementicModel.Compilation.References.Count());
     }
}
```

**Expected Behavior**:
SemanticModel's Compilation.References should return a collection of Compilation References.

**Actual Behavior**:
sementicModel.Compilation.References.Count() retrurns **0**.
Further because the returned value is **0**, below code returns **Null Symbol Information**

`semanticModel.GetSymbolInfo(node).Symbol ?? semanticModel.GetDeclaredSymbol(node)`.

**Comment by Pilchie** [comment]
This looks like another case where `MSBuildWorkspace` wasn't able to process the projects.  We'll need either the project you ran that against, or you'll need to hook up WorkspaceFailed events with 2.3 packages to identify what's going wrong.

Does the project you're trying to analyze compile successfully on that machine if you just run msbuild on the command line?

**Comment by abhijitparkhi1983** [comment]
@Pilchie , 
Yes it does run successfully on the machine if i run msbuild on the command line.
I have uploaded the sample code at the following location: 
https://www.dropbox.com/s/hil35z7zh8ioirn/Roslyn_Version_3_0_0_EmptyReferences.zip?dl=0

**NOTE**: This same code works on the developer machine where Visual Studios 2015 Community version is installed.

**FYI**: Sorry for adding this here. I had added an issue  #20309 which you had closed. I have given a link for the code which reproduces that issue. I am not sure if you get notifications for closed issue on git. It will be really very helpful if you can guide me on  #20309.

**Comment by Pilchie** [comment]
I'm aware of #20309, and investigating further is one of the (very many) things on my todo list.  I will get back to it, but it might be until next week.

**Comment by abhijitparkhi1983** [comment]
@Pilchie ,

In the same code, I am trying to print the Compilation References for each Project using following code :

```
var firstOrDefault = originalSolution.Projects.FirstOrDefault();

                if (firstOrDefault != null)
                {
                    Compilation compilation = firstOrDefault.GetCompilationAsync().Result;

                    Console.WriteLine(compilation.References.Count());
                }
```
It prints 0.

**Comment by abhijitparkhi1983** [comment]
Also using following code, I hooked-up the WorkspaceFailed event:

```
var workspace = MSBuildWorkspace.Create();
Solution originalSolution = workspace.OpenSolutionAsync(currentFile).Result;
workspace.WorkspaceFailed += WorkSpaceFailedException;
......

private static void WorkSpaceFailedException(object sender, WorkspaceDiagnosticEventArgs e)
{
        Console.WriteLine(e.Diagnostic.Message);
}
```
But The event is never fired.

**Comment by Pilchie** [comment]
I took at look at this today, and after making the same changes that @sharwell mentioned in #20309, I found that this worked as expected on my Server 2012 machine.

**Comment by abhijitparkhi1983** [comment]
Thanks @Pilchie  for all the help. I think most of it is working now. I shall further test few more cases which are still failing.
