### ISSUE TITLE
How to do multiple replacements in a SyntaxTree correctly?

### ISSUE THREAD

**Issue by rikimaru0345** [dotnet/roslyn#20392]
I'm writing a code-fix provider that just wraps a InvocationExpression around a string.
And it also adds a `using static ...;` if its not already present.

Somehow I cannot get the code fix to apply both changes.
On the first run it adds the using, on the second run (when it detects that it doesn't have to add the using again) it wraps the expression.
But it never does both at the same time.
I think that's because one change modifies the original tree and thus the second source node cannot be found anymore.

I read on stackoverflow that using "ReplaceNodes" with a dictionary would work, but it doesn't work for me.

I could reorder my replacements maybe, but that seems to be extremely brittle because I want to add maybe one or two more minor things to the rewriter and I can foresee that it might even become impossible to solve this by only doing my replacement calls in the right order :(

Here's what I have

```csharp

async Task<Document> WrapInCallAsync(Document document, ExpressionSyntax syntax, CancellationToken c, string functionName, string usingStatic)
{
	// Keep track of all replaced nodes
	Dictionary<SyntaxNode, SyntaxNode> dict = new Dictionary<SyntaxNode, SyntaxNode>();

	// If the caller provides us with a using to add, we do that here
	if(usingStatic != null)
	{
		// Looking upwards, take the first namespace declaration we can see
		var ns = syntax.Ancestors().OfType<NamespaceDeclarationSyntax>().FirstOrDefault();
		if(ns != null)
			if(ns.Usings.All(u => u.StaticKeyword == null || (u.Name as IdentifierNameSyntax)?.Identifier.ValueText != usingStatic))
			{
				// Create our "using static ...;"
				var u = SyntaxFactory
					.UsingDirective(SyntaxFactory.IdentifierName(usingStatic))
					.WithStaticKeyword(SyntaxFactory.Token(SyntaxKind.StaticKeyword));

				// Change the namespace to include that using
				var changedNs = ns.WithUsings(ns.Usings.Add(u));
				dict.Add(ns, changedNs);
			}
	}


	// Step 2: We want to wrap our call around the given expression, first create the call
	var memberAccess = SyntaxFactory.ParseExpression(functionName);
	var args = SyntaxFactory.SeparatedList(new[] { SyntaxFactory.Argument(syntax) });
	var call = SyntaxFactory.InvocationExpression(memberAccess, SyntaxFactory.ArgumentList(args));

	// Then replace the original expression with that call
	// "text" --> Method("text")
	dict.Add(syntax, call);


	// Finally get the root, apply all our changes, and return the changed root.
	var root = await document.GetSyntaxRootAsync(c);
	root = root.ReplaceNodes(dict.Keys, (original, rewritten) => dict[original]);
	return document.WithSyntaxRoot(root);
}
```

I feel like my code just doesn't have the right structure, surely there is some way to maybe find `syntax` again in the newly modified tree, or maybe some other way to avoid this problem altogether?

**Comment by Pilchie** [comment]
At purely the compiler layer, you can use `SyntaxAnnotations` to mark nodes to be able to find them again.

If you move up to the workspaces layer, the `SyntaxEditor` class exists to help make this easier.

**Comment by rikimaru0345** [comment]
I see, that is good to know. After adding SyntaxAnnotations everything works. Thank you.
