### ISSUE TITLE
Tests that use StopTheThreadPoolContext need to be re-enabled and updated

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#204]
Unshelve Xunit2Parallel;angocke and:

1. Run `.nuget\NuGetRestore.ps1`
2. Build the Roslyn solution.
3. Run `.\packages\xunit.runners.2.0.0-rc1-build2826\tools\xunit.console.exe .\Binaries\Debug\Roslyn.Services.UnitTests.dll -parallel assemblies -noshadow`

This should deadlock (you can investigate by attaching to the xunit process). I suspect the problem is StopTheThreadPoolContext.

**Comment by jasonmalinowski** [comment]
Updating the bug: the current state is the tests that use StopTheThreadPoolContext are disabled, but should be re-enabled when this is removed.

**Comment by jasonmalinowski** [comment]
This is now fixed.
