### ISSUE TITLE
CS0128 local function overloading

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#20408]
**Version**: 15.3.0 Preview 2.1

```C#
static void Main(string[] args)
{
    int Foo(int a) => a;
    int Foo(int a, int b) => a + b;
}
```

gives _CS0128: A local variable or function named 'Foo' is already defined in this scope_

Is there a reason why overloading is not allowed on local functions?

**Comment by Supermaxman** [comment]
Discussion about local functions which may answer your question: 
https://github.com/dotnet/roslyn/issues/2930

> Scoping Rules
Exactly same as for local variables (therefore no overloading)
They may be declared only directly within a block

**Comment by miloush** [comment]
Must have had overlooked that when searching, thanks! (although it doesn't really say why)
