### ISSUE TITLE
Patch up project output paths from ref assemblies when inserting P2P references

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#20412]
P2P references are broken when ref assemblies are turned on (with ~~`<CompileUsingReferenceAssemblies>true</CompileUsingReferenceAssemblies>`~~ `<ProduceReferenceAssembly>true</ProduceReferenceAssembly>`). 
Rolsyn tracks paths to identify project outputs, but in some cases it receives the implementation assembly path (`bin/a.dll`) from the project system, and the ref assembly path (`bin/ref/a.dll` by default) in other cases. 

The proposal (option (4) discussed in https://github.com/dotnet/project-system/issues/2478) is for Roslyn to recognize this pattern and strip the "ref/" when establishing P2P references.
@jasonmalinowski Feel free to write more details from the discussion today, as you understand it best.

The goal for this short-term workaround is to enable dogfooding of ref assemblies in 15.3. We will document the scenarios that are known to still be broken (LSL, LUT, etc) and continue the discussion to fix them with a proper design in 15.5.

FYI @srivatsn @Pilchie @jaredpar @davkean

**Comment by MattGertz** [comment]
Mondo escrow triage:  keeping in 15.3 because related to new feature.  However, we don't want this area to go late into Escrow.

**Comment by jcouv** [comment]
@jasonmalinowski Is there a chance this will still make it for 15.3? Thanks

**Comment by jasonmalinowski** [comment]
@jcouv That's where we still want it to be. How likely we are to succeed is unclear. @Pilchie was looking at rebalancing this.

**Comment by jaredpar** [comment]
Can we help?

**Comment by Pilchie** [comment]
@jaredpar Sure - PRs welcome :)  [This code](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/AbstractProject.cs,b885435b5bb6e17e) is likely where you'd want to start looking.

**Comment by jcouv** [comment]
@Pilchie Could you also point out a test in the right area?

**Comment by Pilchie** [comment]
Try looking in `Test\ProjectSystemShim` under `src\VisualStudio\[Core|CSharp|VisualBasic]`

**Comment by jcouv** [comment]
Jason said this was handed off to Sam. Thanks

**Comment by Pilchie** [comment]
This was fixed by #20833.
