### ISSUE TITLE
EditorConfig: How to eliminate multiple consecutive blank lines?

### ISSUE THREAD

**Issue by danrozenberg** [dotnet/roslyn#20426]
If I have the following:

```
int Foo(int a, int b)
{
  

    return a + b;
}
```

Is there any rule that will either warn me or automatically format it to:

```
int Foo(int a, int b)
{
    return a + b;
}
```
?

Thanks!

**Comment by Pilchie** [comment]
We don't currently have an analyzer for this built in to Roslyn.  (There is a request for it at https://github.com/dotnet/roslyn/issues/18186 though).  

In the meantime, you could try using the StyleCop.Analyzers packages.

**Comment by jez9999** [comment]
@Pilchie Is there actually a rule for multiple blank lines in StyleCop.Analyzers?  I can't see one.

**Comment by Pilchie** [comment]
Original Stylecop *did* have one. @sharwell - do you know if it is part of StyleCop.Analyzers too?

**Comment by sharwell** [comment]
It's [SA1507](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1507.md)

**Comment by jez9999** [comment]
Thanks
