### ISSUE TITLE
How do I customize the entries in the "fix all" preview window?

### ISSUE THREAD

**Issue by rikimaru0345** [dotnet/roslyn#20423]
When my code analyzer suggests a fix I can do a "fix all in this document" action, which will then show the preview window.

Is it possible to change the strings that are displayed in this list?
My code fix wraps string literals and string interpolations in a function call and I would like to display only the string that gets wrapped in the list, not the "full" line and how it will look like after the change.

If its unclear what I'm talking about, I mean the entries in this window:
![](http://i.imgur.com/QgEpTbG.png)

**Comment by Pilchie** [comment]
Unfortunately, there isn't a way to do this today.

**Comment by Pilchie** [comment]
I'm going to treat this as part of https://github.com/dotnet/roslyn/issues/5222.
