### ISSUE TITLE
out var ignores explicit type preference

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#20437]
**Version Used**: 2.3.0.61814

**Steps to Reproduce**:
```C#
int.TryParse("0", out var i);
```

![untitled](https://user-images.githubusercontent.com/10546952/27511653-d788cada-5921-11e7-89ab-d9d433eac9b9.png)

**Expected Behavior**: IDE0008: Use explicit type instead of 'var'

**Actual Behavior**: Nothing.

**Comment by Pilchie** [comment]
Just to confirm - you do have the severity set to something, right?

**Comment by miloush** [comment]
Just to confirm - yes, Suggestion for all of them.
