### ISSUE TITLE
TemporaryStorageServiceFactory makes OS X run out of handles

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#20439]
**Version Used**: 
Microsoft.CodeAnalysis.2.3.0-beta2-61823-06 from myget which includes https://github.com/dotnet/roslyn/pull/19624

**Steps to Reproduce**:
1. You need to build a special MonoDevelop setup for this
2. Open MonoDevelop's solution
3. Wait for the typesystem to finish loading

**Expected Behavior**:
It doesn't run out of file handles

**Actual Behavior**:
It runs out of file handles

What happens?

OS X has a really low hard limit on file handles, thus, we need to avoid this keeping a lot of handles alive. By modifying the MonoDevelop code to use a `Host` kind workspace (to be able to use `SolutionSizeTracker` and other `IIncrementalAnalyzerProvider`s), we are not forced to use Roslyn's stock `TemporaryStorageServiceFactory`. Under OS X, this depletes file handles limit pretty quickly.

I see a few ways forward to fix this:
a) Make the `TemporaryStorageServiceFactory` service layer a lower one - i.e. Default, so we can override it at `Host` level
b) Modify `IIncrementalAnalyzerProvider`s to allow `MonoDevelop` workspaces so they get enabled
c) Import the FileStream-based `TemporaryStorageServiceFactory` from [MonoDevelop](https://github.com/mono/monodevelop/blob/ed863026d64f9a9a843f72f7c4f19eac903c6727/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopTemporaryStorageServiceFactory.cs#L51-L186) into Roslyn and use it when the platform is OS X

**Comment by sharwell** [comment]
Depending on how memory mapped files are implemented on OSX, the work in #19624 (which did not appear in the latest beta packages) may have improved this situation substantially.

**Comment by Therzok** [comment]
It would be great if the myget feed attached the commit sha which contained the published nuget, but:

[This package] (https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis/2.3.0-beta2-61823-06) is from 23 June, which should contain #19624.

From my understanding, the 2.3.0-beta2 and beta3 packages follow the master branch.

**Comment by sharwell** [comment]
@Therzok I downloaded the package from NuGet and opened it in ILSpy to verify that it does not contain the change. The situation of making determinations like this should improve substantially in the future with #20283.

**Comment by Therzok** [comment]
Oh, that is great to hear! I'll retest with a newer package when available!

**Comment by Therzok** [comment]
Okay, it seems like 2.3.0-beta3-61826-04 has the fix. From my testing, we no longer run out of file handles on the MonoDevelop solution. This is marvelous @sharwell .

Consider this issue fixed, we can just use stock roslyn provider now! We're down to 114 handles from 12000+.
