### ISSUE TITLE
[FeatureRequest] Markdown support for completion items

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#20442]
In VS4Mac we display completion items sometimes differently:

* Obsolete members are strikethrough
* Members show their return type at the right side with a smaller font
* More advanced use cases like the formatting completion show a small description

We're using pango markup for these features - would be really nice if we could get either markdown support or some properties.

ATM we have only these 3 use cases: strikethrough, right side description and small description beside the element. That could be covered with properties alone.

**Comment by mkrueger** [comment]
Video: https://screencast.com/t/24IKfvePxm

That's how it looks like.

**Comment by Pilchie** [comment]
Like https://github.com/dotnet/roslyn/issues/16817, but with more scope. Tagging @markw-t, and @olegtk

**Comment by sharwell** [comment]
* Obsolete members are strikethrough: Moved to #26488 
* Members show their return type at the right side with a smaller font: Moved to #26489 

I wasn't sure how to handle the other items above. If I've missed something important, please feel free to open a new issue targeting the specific single feature so we can discuss it. 😄
