### ISSUE TITLE
Minor Bug: Icons in "fix all" window randomly change

### ISSUE THREAD

**Issue by rikimaru0345** [dotnet/roslyn#20440]
**Version Used**: 
Vs Community 2017, 15.2, (26430.14)

**Steps to Reproduce**:
**Expected Behavior**:
**Actual Behavior**:

A minor bug, but maybe it has something to do with the various other random problems I'm experiencing.

Open "fix all" in the "all in project" mode.
Enable and disable some files while you have windows forms windows present in your project.

**Comment by CyrusNajmabadi** [comment]
I don't repro anything here, and the link to the video is gone now.  need more info on what's going on here.
