### ISSUE TITLE
Enable EnC support for C#7.1 features

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#20455]
- [x] async Main (from @jcouv : This doesn't seem relevant to ENC) 
- [x] “default” literal
- [x] inferred tuple names
- [x] pattern-matching with generics (EnC is not supported in generic types/methods)

**Comment by vsccarl** [comment]
Pattern-matching with generics is not allowing EnC currently as expected, but I am not seeing it noted in the Error List.

**Comment by jinujoseph** [comment]
Thanks @vsccarl  for verifying this.
