### ISSUE TITLE
VB new preselection should not include the current error type

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#20461]
`Dim helper = new CompletionHelperaaa$$`

New preselection includes "CompletionHelperaaa" and selects it which makes it really hard to type backspace 3 times and insert an open paren.

![image](https://user-images.githubusercontent.com/3751401/27560046-95e932e8-5a77-11e7-9dba-7f85bd712dcc.png)

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
