### ISSUE TITLE
Make method synchronous sorts above add using

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#20460]
**Version Used**: 
15.3 Preview

**Steps to Reproduce**:

Something like:
```C#
async Task SomethingAsync() { }
```

**Expected Behavior**:
Add using should be first.

**Actual Behavior**:
`Make method synchronous.` is first.
Also - `Make method synchronous.` shouldn't end with a period.

(Filed on behalf of @DustinCampbell)

**Comment by Pilchie** [comment]
This is a regression in 15.3, right?  Let's fix

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/20470

**Comment by DustinCampbell** [comment]
Thanks!
