### ISSUE TITLE
UI delay during solution load from analyzer dependency checker

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#20476]
A customer reported a very large UI delay on solution load, whose underlying cause was attempting to report analyzer dependency conflict diagnostic IDE1002 on UI thread during analyzer reference initialization. This is done on the UI thread by both legacy and new project systems. The root cause is that diagnostic reporting involves checking if diagnostic was suppressed or not, which requires binding and decoding all the global assembly level attributes. We can push the analyzer dependency conflict diagnostic reporting on background thread to avoid this UI delay.

**Comment by sharwell** [comment]
:memo: I hit this last night and was working on it this morning not realizing someone else hit it too.

**Comment by mavasani** [comment]
Thanks Sam. Short term fix would be to just push analyzer dependency conflict diagnostic reporting onto a task. Long term, we should move our new project system to do all language service initialization in a free threaded manner.

@jinujoseph @MattGertz I think we should consider the short term fix for 15.3, or atleast 15.4.

**Comment by sharwell** [comment]
@mavasani In my PerfView run, the dominant issue related to this was the call to `DiagnosticData.TryCreate` (a synchronous method that blocks on the result of `GetCompilationAsync`) from inside `AnalyzerDependencyCheckingService.CheckForConflictsAsync` (an `async void` method that ended up getting inlined on the UI thread by the scheduler). Two ways to avoid the block appeared to be:

1. Make `DiagnosticData.TryCreate` asynchronous
2. Wrap the offending call to `DiagnosticData.TryCreate` in a task that forces its execution to occur on a different thread, unblocking the UI thread

**Comment by mavasani** [comment]
Yes, I am going to implement 2.

**Comment by sharwell** [comment]
I measured the impact of this improvement at a bit over 2% on solution load time for Roslyn.sln. It might be hard to justify for 15.3 on *this* measurement, but if we can show a more substantial improvement in other scenarios I would be very much in favor of the change.

**Comment by MattGertz** [comment]
Sam's right; current bar is 20%.  Now, of course, I recall that Sam's machine isn't exactly typical, though. :-)

**Comment by Sumo-MBryant** [comment]
In my solution (the reporter of the issue), the UI will typically hang for 20 seconds to 1 minute 15 seconds with over 200 IDE1002 warnings reported. With the below rule set applied, the hang lasted 10 seconds or less. With all IDE1002 warnings fixed, there was no apparent UI hang.

```xml
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="Rules" Description="Code analysis rules" ToolsVersion="15.0">
  <Rules AnalyzerId="Roslyn_HostError" RuleNamespace="Roslyn_HostError">
    <Rule Id="IDE1001" Action="None" />
    <Rule Id="IDE1002" Action="None" />
    <Rule Id="IDE1003" Action="None" />
  </Rules>
</RuleSet>
```

**Comment by mavasani** [comment]
The performance impact here is directly proportional to the number of projects that have this analyzer dependency conflict diagnostic. For further context, root cause for this diagnostic is different projects in solution are referring to different version of the analyzer package or dependencies. I presume very few projects are affected in Roslyn.sln, but a large number of them were affected in Mark's solution.

**Comment by sharwell** [comment]
@Sumo-MBryant That's great info. Is your project open source by any chance? Also, how long is the total solution load time?

**Comment by jinujoseph** [comment]
@mavasani lets create a PR against master, we can move to the release branches based on bar check

**Comment by Sumo-MBryant** [comment]
Unfortunately it isn't open source. The breakdown of solution load time for me was:

|Phase|Duration|Notes|
|---|---|---|
|Initial Load|3 – 8 seconds|UI is unusable either due to hanging or the solution load dialog.|
|Solution Completed Initialising and Loading (all projects marked as loaded)|45 seconds – 1 minute 20 seconds|There were only a couple of hangs during this period, otherwise UI is usable.|
|Post Solution Load Hang|20 seconds - 1 minute 15 seconds without Nuget Restore|UI hangs completely or has massive stalls, UI is not usable during this time period.|

**Comment by sharwell** [comment]
@mavasani I just measured `DiagnosticData.TryCreate` as a 9.3 second UI thread block after initial solution load in 15.3 Preview 6.

**Comment by mavasani** [comment]
Dupe of #23775
