### ISSUE TITLE
Tokenize a C# source file.

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#20480]
Hi, does the Roslyn "library" provide a means to simply open and tokenize arbitrary C# source files?

I'm not interested in compiling or translating to IL or creating assemblies or resolving references to symbols or anything, just obtain a "token" stream (i.e. IEnumerable<Token> ??) so that I can enumerate tokens.

Thanks

**Comment by Therzok** [comment]
https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Syntax-Analysis

**Comment by Korporal** [comment]
@Therzok - Hi, yes I have read that (briefly) before, but that seems to be concerned with how to traverse the parse tree, I'm (initially) just seeking to open a .cs file and tokenize it - just get the tokens with no regard to syntax or anything, and outside of the context of a project and without looking at other .cs files that might be involved in a true compilation.

**Comment by Pilchie** [comment]
Take a look at [`SyntaxFactory.ParseTokens()`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/SyntaxFactory.cs,3297b9dba0e37aa1)

**Comment by shaggygi** [comment]
@Korporal  this is an old, old file, but does this help?

https://www.filipekberg.se/2011/10/20/using-roslyn-to-parse-c-code-files/

```csharp
string code = System.IO.File.ReadAllText(@"YourFile.cs");
var syntaxTree = Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(code);
```

**Comment by Korporal** [comment]
@Pilchie - Yes, thanks. I'm seeing a class Lexer and SourceText etc (which looks like it can be created from a TextReader), I'm gonna play with this!

**Comment by Korporal** [comment]
I've started putting together a lexical analyzer class for C#, but before I go too far I wanted to ask if anyone has any knowledge of this:

CSharpTokenizer Class

as it may save me the effort. Having said that the analyzer I'm designing includes comments as distinct tokens and I don't think either Roslyn or the above do anything like that.

**Comment by CyrusNajmabadi** [comment]
>Having said that the analyzer I'm designing includes comments as distinct tokens and I don't think either Roslyn or the above do anything like that.

You could simply accomplish that by getting each token from ParseTokens and processing .LeadingTrivia and .TrailingTrivia

**Comment by Korporal** [comment]
@CyrusNajmabadi - So does SyntaxFactory.ParseTokens() already do what I want? I want to simply open a .cs file (without any reference to other files, projects or solutions - just a text file) and convert that to an IEnumerable of "tokens". The ParseTokens() method returns SyntaxToken instances which may be fine.

I may have misunderstood and thought that ParseTokens was performing syntax analysis and so on - what I want is JUST a raw sequence of lexical tokens create from raw input text.

**Comment by CyrusNajmabadi** [comment]
Yes.  Just use ParseTokens.  No analysis is done.  It's just straight tokens.

**Comment by CyrusNajmabadi** [comment]
> I may have misunderstood and thought that ParseTokens was performing syntax analysis and so on

Note: i'm curious why you don't at least want syntax analysis.  For example, if you just use lexical analysis, nothing will tell you if a contextual keyword is an actual keyword or not.  So things like 'await' will always appear as identifiers to you, even if they are keywords in that particular context.

Similarly, you'll get strange results around  ```>>``` from ParseTokens as there will be no syntactic analysis to tell you if that's actually a ```>>``` token, or two ```>``` tokens.

Note that syntactic analysis is not actually testing if your code is meaningful (i.e. semantically correct), it's just validating that the tokens would form a valid syntax tree.  Normally that's what most people want to start with.  ParseTokens is for some *very* low level type operations where one can accept nonsensical results (normally because they'll override their usage of those results once a tree is available).

**Comment by Korporal** [comment]
@CyrusNajmabadi - Hi, all I'm aiming to do is finish a source scanning tool, for searching repos (for example) for occurrences of certain types of data. For example find all occurrences of source code that has any comments with the text "legislated" or all code that has a class name containing "LTI" and so on.

So this is a source code search utility that can do this kind of thing, being able to restrict the text searches to specific kinds of tokens is core to this kind of tool. Of course recognizing a class name as a true class name does (in reality) require parsing of the token stream, but since (in almost every conceivable case) all .cs files are clean and compilable, the tool can do some rudimentary parsing of class declarations because illegal syntax is pretty much ruled out.

I'd expect (I could be wrong) that having the Roslyn code parse these files might be problematic because that requires metadata from external assembly references and so on and for partial classes requires multiple files to be combined etc.

**Comment by CyrusNajmabadi** [comment]
> I'd expect (I could be wrong) that having the Roslyn code parse these files might be problematic because that requires metadata from external assembly references and so on and for partial classes requires multiple files to be combined etc. whereas I want to treat each .cs file we find in the folder tree as a distinct unit, I don't want to open projects, solutions etc.

Nope.  That's *semantic analysis*.  You can trivially parse syntax trees from a string, without any external dependencies at all.  It's a pure syntactic analysis.   I would recommend doing this instead of lexical.  But either are available to you if you want.

**Comment by Korporal** [comment]
@CyrusNajmabadi - OK thanks, that makes sense now that you explain it, you're quite right syntax validation doesn't involve resolving names etc. I'm just trying to play with Roslyn, after reading around the web it seems I must install Microsoft.CodeAnalysis from nuget. I tried but it refused saying that the package has nothing that's compatible with .Net 4.5 (which is what I used to create my test scan app). I visited the Nuget page for the package and it says NOTHING about what framework versions are required/supported.

**Comment by CyrusNajmabadi** [comment]
tagging @Pilchie   Sorry, i have no idea about that sort of thing :D    But i can help with teh APIs *once* you get things up and running.

**Comment by Pilchie** [comment]
What version of the package are you installing?  Roslyn depends on .NET 4.6.

**Comment by Korporal** [comment]
@Pilchie - I just updated my console app to .Net 4.6 and it installed (I was installing the version suggested by the package manager in VS 2017 2.2.0).

**Comment by Korporal** [comment]
@CyrusNajmabadi - Hi, this looks very good, and you're right the syntax tree it generates is far more useful than analyzing the token stream!

**Comment by Korporal** [comment]
@CyrusNajmabadi - Although the "trivia" is a bit confusing. When I generate simply tokens I can see comments as leading trivia (when HasLeadingTrivia is true) but when I examine the parse tree, I can see a property HasLeadingTrivia is true but cannot see the actual trivia (a comment).

**Comment by Korporal** [comment]
@CyrusNajmabadi 

> Nope. That's semantic analysis. You can trivially parse syntax trees from a string, without any external dependencies at all. It's a pure syntactic analysis. I would recommend doing this instead of lexical. But either are available to you if you want.

So the parse tree one gets does not have references resolved? If one wanted to do that is there another operation? is there a subsequent processing step into which one passes the tree that's returned from ParseCompilationUnit?

**Comment by Korporal** [comment]
@CyrusNajmabadi - I wonder why "KindText" (on the various parse tree nodes) is not a public property?

**Comment by Korporal** [comment]
@CyrusNajmabadi - OK I can just access Kind().ToString().

**Comment by CyrusNajmabadi** [comment]
@Korporal the data for trivia is owned purely by tokens.  i.e. trivia (whitespace + comments) is only present between tokens.  

There are aggregating helpers that can tell you for a node (which eventually is comprised of tokens) if it has trivia on its first or last tokens.  in this case use SyntaxNode.GetLeadingTrivia.

Please see https://github.com/dotnet/roslyn/wiki/Roslyn%20Overview#working-with-syntax for more information.

**Comment by CyrusNajmabadi** [comment]
> So the parse tree one gets does not have references resolved? If one wanted to do that is there another operation? is there a subsequent processing step into which one passes the tree that's returned from ParseCompilationUnit?

Yes.  See https://github.com/dotnet/roslyn/wiki/Roslyn%20Overview#working-with-semantics for more information.

You'll create a Compilation object that understands sets of syntax trees and sets of references and can appropriately answer semantic questions about it.  SemanticModel is the type you'll use to answer semantic questions about nodes in your SyntaxTrees.

**Comment by Korporal** [comment]
@CyrusNajmabadi 

> the data for trivia is owned purely by tokens. i.e. trivia (whitespace + comments) is only present between tokens.

There are aggregating helpers that can tell you for a node (which eventually is comprised of tokens) if it has trivia on its first or last tokens. in this case use SyntaxNode.GetLeadingTrivia.

Please see https://github.com/dotnet/roslyn/wiki/Roslyn%20Overview#working-with-syntax for more information.

Much appreciated, I can see and enumerate these trivia objects now from parse tree nodes, probably enough for me to do what I need.

**Comment by CyrusNajmabadi** [comment]
Awesome.  Also, FYI, there's https://gitter.im/dotnet/roslyn to ask general Roslyn questions.  Probably better than opening issues for this sort of thing.  Cheers!
