### ISSUE TITLE
Unexpected ordering of Add Using and Remove Unused Variable

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#20487]
**Version Used**: Latest sources

3 scenarios to illustrate:

1. Invoke Ctrl+. at the $$ (spaces matter)
```C#
  class C
  {
      void M()
      {
          List<int>   $$           x;
      }
  }
```

**Expected Behavior**: Add Using is the first thing in the lightbulb
**Actual Behavior**: Add Using is the first thing in the lightbulb 👍 

2. Invoke Ctrl+. at the $$ (spaces matter)
```C#
  class C
  {
      void M()
      {
          List<int>           $$   x;
      }
  }
```

**Expected Behavior**: Not sure. Is it based on proximity to caret, or on severity? It just feels like Add Using should win regardless.
**Actual Behavior**: Remove Unused Variable is the first thing in the lightbulb

3. Invoke Ctrl+. at the $$ (spaces matter)
```C#
  class C
  {
      void M()
      {
          List<int>              x;$$
      }
  }
```

**Expected Behavior**: I'm past the end of the statement, so I don't immediately think proximity should matter. I'd expect Add Using to be the first thing in the lightbulb.
**Actual Behavior**: Remove Unused Variable is the first thing in the lightbulb

**Comment by dpoeschl** [comment]
FYI @Pilchie @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Right now it's based on proximity to the span the diagnostic is for.

**Comment by CyrusNajmabadi** [comment]
Logic is in here: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/Suggestions/SuggestedActionSetComparer.cs

**Comment by Pilchie** [comment]
Tagging @kuhlenh.  I know why we did the proximity thing, but I think this experience is terrible.

1. Add using fixes an *error* not a warning.
2. This means that the default fix right after typing a line of code is to delete that line of code ☹️

**Comment by Pilchie** [comment]
@kuhlenh - let's figure out something better here.

**Comment by CyrusNajmabadi** [comment]
This works properly now.  The error gets higher priority than removing the unnecessary variable no matter where you are.
