### ISSUE TITLE
AsyncCompletionService shouldn't depend on VS Editor's ICompletionSession

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#20525]
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Intellisense/Completion/AsyncCompletionService.cs,28

```
private readonly IIntelliSensePresenter<ICompletionPresenterSession, ICompletionSession> _completionPresenter;
```

We have an IIntelliSensePresenter that depends on ICompletionSession which is an Editor concept. We need to find a way to remove this since it's only used by the Quick Info implementation. This prevents the Visual Studio for Mac team from implementing our own IIntelliSensePresenter.

cc @toddgrun

**Comment by KirillOsenkov** [comment]
cc @rchande @jasonmalinowski

**Comment by jasonmalinowski** [comment]
To give some additional background here: right now AsyncCompletionService can (somewhat reasonably) be used in Visual Studio for Mac without needing the WPF editor there, as they can provide their own IIntellSensePresenter that talks to the VS for Mac completion APIs. But we still leak the session type from the VS APIs there whichi we really don't need. Deleting the second type parameter from IIntelliSensePresenter and doing something else there is all we need.

**Comment by KirillOsenkov** [comment]
Yeah I think with the move to the new Completion and QuickInfo (in the next couple months) this will become no longer relevant. 

Feel free to close and if we ever need this again I will reopen.

**Comment by jinujoseph** [comment]
thanks @KirillOsenkov
