### ISSUE TITLE
Runtime Type validation. (Could be a stupid idea)

### ISSUE THREAD

**Issue by vaualbus** [dotnet/roslyn#2053]
I would start saying that this is the first time I write here!
Any way, Recently I have something in my mind. 
Let's said that we could have an attribute that can be applied to variables (I know that right now it is impossible If the variable is inside a method) that tell the runtime how to menage that variable value.
This would be runtime idea of the current contracts research project (this If I get right should work at compile time)
Let's make an example.

// The value is between -10 and 10. -10 <= x <= 10
[InRange(-10,10)]
punt int Test { get; set; }

public void TestStupidFeaure(int someValue)
{
     // If durin excution test have a value greater equals than 100, the runtime will produce an exception;
     [MaxValue(100)]
     var test = 10;

```
 //And suipport also min value
 //There an exception will be throw id some value is <= 1.
 [MinValue(1)]
 var test2 = someValue;
```

}

I know this feature seem very trick and unecessary but could be a way to prevent bugs.
Don't even know if it is possible to implement this feature, but anyway I like the idea.
Thanks, Best regards, Alberto

**Comment by AdamSpeight2008** [comment]
@vaualbus 
Why not define a custom class of structure? [Unit System](http://www.dreamincode.net/forums/topic/344882-a-unit-system/)

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
