### ISSUE TITLE
Devenv.exe and servicehub.XXX.exe are taking up 100% cpu for minutes.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#20559]
This is happening even though i only have a single file open in VS and i stopped editing it *minutes* ago.  Seriously, these processes are using my CPU non-stop and never seem to stop.  I have full-solution-analysis and codelens OFF.

**Comment by CyrusNajmabadi** [comment]
Have collected a trace.  Will link when it is uploaded.

**Comment by CyrusNajmabadi** [comment]
tagging @heejaechang

**Comment by CyrusNajmabadi** [comment]
It looks like a ton of time is spent in searching for todo comments https://drive.google.com/file/d/0ByISdSEZ09PBMWhOczFwWnJGc00/view?usp=sharing

Shouldn't this all be syntactic (and cached)?  Is there some reason this is taking so much time?

**Comment by heejaechang** [comment]
I can take a look. one question. is it new solution or already have persisted data? looks like vs is not loading from persisted data if todo info is already done once. otherwise, service hub won't process any todo work.

**Comment by heejaechang** [comment]
if it is first time solution opened, then sure solution crawler will visit ever files in the solution to get todo comments and that will take some times.

**Comment by sharwell** [comment]
@CyrusNajmabadi 7 seconds of thread-time in that trace is addressed by #20478.

**Comment by CyrusNajmabadi** [comment]
This is just me working with Roslyn.sln.  Definitely not new.

**Comment by heejaechang** [comment]
I just took a look at the etl. OOP is busy running solution crawler for symbol tree index and others (FAR and GOTO indexes)

VS side is busy creating service hub connection for todo comments which should got improved in master now.

**Comment by heejaechang** [comment]
according to trace, CPU is not actually busy, VS only used 4 second of CPU time among 40 seconds of trace. so it is perceived as 100% but in between many idle time. this I believe is due to todo comment creating new connection for each file which should be fixed in master now. it now create 1 connection and keep it alive for entire todo service. it should make work to be done in more dense way. making its perf same as beofer we moved todo comment OOP.

**Comment by CyrusNajmabadi** [comment]
This has gotten better in the last few years.  closing out.
