### ISSUE TITLE
Reloading Roslyn.sln solution takes 5+ minutes.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#20553]
Did a git fetch, then had VS prompt me to reload solution.  I did so and it took 5+ minutes.  I collected a trace of around 2 minutes of it and will upload for investigation.

**Comment by CyrusNajmabadi** [comment]
Tagging @srivatsn @Pilchie

**Comment by sharwell** [comment]
@CyrusNajmabadi Was one of the branches (from or to) using Jared's fix-cps change, and the other one not? (i.e. did one or more projects involved in the switch go from legacy to CPS or vice-versa?)

**Comment by CyrusNajmabadi** [comment]
Trace is here: https://drive.google.com/file/d/0ByISdSEZ09PBSUhmRWR3RHM3ZXc/view?usp=sharing

**Comment by CyrusNajmabadi** [comment]
@sharwell These are all master/master changes (so they should have Jared's changes).

**Comment by sharwell** [comment]
@CyrusNajmabadi I just reproduced it to a lesser extent

**Comment by CyrusNajmabadi** [comment]
Another trace: https://drive.google.com/file/d/0ByISdSEZ09PBTnY5Y1JYLXZ4dGM/view?usp=sharing

**Comment by Pilchie** [comment]
Should this be moved to `dotnet/project-system`?

**Comment by CyrusNajmabadi** [comment]
This has gotten much better in teh last few years.  closing out.
