### ISSUE TITLE
DeclarationFinder APIs should be more explicit about languages that don't support compilations

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#20573]
See https://github.com/dotnet/roslyn/pull/20435, and internal bug 455588.

Basically the internal APIs on DeclarationFinder, and the public APIs that rely on them never return any results for languages don't support compilations, only because of the check in [`SolutionState.ContainsSymbolsWithNameAsync`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/SolutionState.cs,face05e75659106d).

We should be more explicit in the documentation about API and think about whether this leads to bad results for languages like TypeScript.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  partner teams not asking for anything here.
