### ISSUE TITLE
ISyntaxFactsService.IsEntirelyWithinStringOrCharOrNumericLiteral returns false for numeric literals in C#

### ISSUE THREAD

**Issue by MaStr11** [dotnet/roslyn#20594]
**Version Used**: 
VS 2017 15.1
**Steps to Reproduce**:

Code to analyze (Cursor positon marked with $$ )
```CSharp
a.methodCall(12$$3)
```
**Expected Behavior**:
`ISyntaxFactsService.IsEntirelyWithinStringOrCharOrNumericLiteral` returns `true` for VB  and C#.

**Actual Behavior**:
The VB version of `ISyntaxFactsService` returns true. The C# version does not.

Reason:
`CSharpSyntaxFactsService.IsEntirelyWithinStringOrCharOrNumericLiteral` only checks for `IsEntirelyWithinStringOrCharLiteral` [here](
https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/LanguageServices/CSharpSyntaxFactsService.cs#L134).

**Comment by CyrusNajmabadi** [comment]
Closing out.  If this causes a problem somewhere we should track that somehow.  Otherwise, this is effectively just an issue that should be a 'todo' in teh code.
