### ISSUE TITLE
Generate Constructor refactoring generates a public constructor in an abstract class

### ISSUE THREAD

**Issue by sonnemaf** [dotnet/roslyn#20595]
**Version Used**: 
Visual Studio 2017 (Roslyn 2)

**Steps to Reproduce**:
1. Create the following class

```
abstract class Shape {
    public string Color { get; set; }
}
```
2.  Select the text 'public string Color { get; set; }' and hit Ctrl+.
3. From the Context menu select the option "Generate constructor 'Shape(string)'"

**Expected Behavior**:
A protected constructor, because the class is abstract

```
abstract class Shape {
    protected Shape(string color) {
        this.Color = color;
    }
    public string Color { get; set; }
}
```

**Actual Behavior**:
A public constructor

```
abstract class Shape {
    public Shape(string color) {
        this.Color = color;
    }

    public string Color { get; set; }
}
```

**Comment by HaloFour** [comment]
I don't think that there is anything wrong with the current behavior.  It's legal syntax and behaves effectively identically to using the `protected` accessibility given you can't instantiate the class directly.  I think it's primarily a question of style and preference.

**Comment by sharwell** [comment]
Definitely a bug. This is an unintentional deviation in the generated code from [CA1012](https://msdn.microsoft.com/en-us/library/ms182126.aspx), with no real reason why a `public` constructor would ever be generated in this case.

**Comment by zaytsev-victor** [comment]
And what about VB.NET? It also should be protected constructor in this case?

**Comment by CyrusNajmabadi** [comment]
@zaytsev-victor Yes.  we would do the same thing for VB here.  These code-fixes are shared between C# and VB and almost always do the same thing for both languages.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/20632
