### ISSUE TITLE
Is there a way to dump symbol assertion code?

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#20593]
For example if you call `DumpSymbol(node)` in a test, it fails with the following output:
```
 var symbolInfo = model.GetSymbolInfo(node, default(CancellationToken));
 Assert.Equal(CandidateReason.None, symbolInfo.CandidateReason);
 Assert.NotNull(symbolInfo.Symbol);
 Assert.Equal(0, symbolInfo.CandidateSymbols.Length);
```
This could be a detailed output, uninteresting assertions can be removed afterwards.

**Comment by alrz** [comment]
Alternatively we have define something like `VerifyDiagnostics`,
```cs
model.VerifySymbol(node, s => {
  // assertions
});
```
If any of assertions fails the actual assertions will be printed to the output.

**Comment by jcouv** [comment]
I didn't understand how `VerifySymbols` would improve test code.

For the first idea (helper to generate test code), that's an interesting suggestion. I may give it a shot next time I have to write repetitive test code on symbols. I assume this generator would have to be symbol-specific (different kinds of symbols should produce different test code).

**Comment by alrz** [comment]
>I didn't understand how VerifySymbols would improve test code.

It would help to actually run the test *and* dump passing assertions if it fails, otherwise you'd need to add DumpSymbol call everytime to see what's going on.

**Comment by gafter** [comment]
This is a good idea, but we have no such plans.
