### ISSUE TITLE
SymbolFilter parameter to AbstractNavigateToSearchService methods

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#20591]
**Version Used**: 
0f658a492302a11277348d1fd1ef2e1d0a0e4130

**Expected Behavior**:
Being able to pass in a SymbolFilter parameter to pre-filter results before passing them to the caller

**Actual Behavior**:
All symbol kinds are passed in

In VS4Mac, we have the ability of tagging the kind of symbols to match (i.e. `type:`, `event:`, `method:`, `member:`)

Providing ways to pre-filter results at this API level would mean that `type:` requests would become way faster instead of post-filtering many possible matches.

**Comment by CyrusNajmabadi** [comment]
The issue here is that INavigateToSearchService is a cross language service.  SymbolFilter is not a cross-language concept (it is C#/VB specific).  Do you have data showing that this would be a subtantial improvement over post-result filtering?

**Comment by Therzok** [comment]
Just filtering offering a subset of SymbolFilter (i.e. Type, not TypeAndMember), would offer way faster searching in a project than getting everything.

http://source.roslyn.io/i.txt

Specific case: 250k symbols in roslyn solution, 50k types. This increases search responsiveness if the Roslyn SymbolFilter definition can be passed as a parameter.

Really useful for the cases with short search patterns, like `a`

**Comment by CyrusNajmabadi** [comment]
> would offer way faster searching in a project than getting everything.

My point is this: you shouldn't be getting everything.  You should just be getting the things that match the search string.  it's unclear to me if filtering the results of that list will be substantially slower than filtering the results before you get them.

Note: i've tested locally, and on my laptop i can do about 850k name tests per second.  So, in the case you've mentioned I would expect to be able to search all those 250k symbols in 1/3rd of a second.  Only searching 50k types would decrease that by 5x.  However, it's not clear to me that such a saving is that valuable to the user.  i.e. 1/3rd of a second to 1/15th of a second doesn't feel like it's going to be that substantial.

**Comment by Therzok** [comment]
What I'm worried about is not throughput, but actually the memory pressure coming in from allocations (symbol result and result array). If the user types really fast, the GC can kick in a lot and make the operation clunky. Especially since VSMac does these in process. It might be theoretical, but I'd really want to err on the safe side here. 

On the other hand, there's more stuff done in VSMac. Currently, we filter by kind before marshalling to the UI layer, but given lower level APIs of the search service implement symbolfilter as a parameter, I don't see why it shouldn't be exposed.

**Comment by Neme12** [comment]
Why is this specific to vs4mac? I use this in VS as well with `m` (member) and `t` (type) prefixes. How is this different?

**Comment by Therzok** [comment]
@Neme12 the interface in VS did not expose filters like this before.
