### ISSUE TITLE
Do not reference non readonly fields on 'GetHashCode' methods

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#20598]
**Version Used**: 
Latest master

**Expected Behavior**:
GetHashCode should use only readonly fields in order to return a consistent value.

**Actual Behavior**:

List of impacted classes where field can easily be marked as readonly:
- [CodeModelEvent.cs](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Impl/CodeModel/CodeModelEvent.cs#L24)
- [SymbolInfo.cs](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Compilation/SymbolInfo.cs#L104)
- [SyntaxTriviaList.Reversed.cs](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Syntax/SyntaxTriviaList.Reversed.cs#L51)
- [SyntaxTokenList.Reversed.cs](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Syntax/SyntaxTokenList.Reversed.cs#L61)

Others:
- [BitVector.cs](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Collections/BitVector.cs#L51)

**Comment by sharwell** [comment]
This is interesting. The only real impact of this is it makes it difficult to use instances of the affected types as keys in a hash-based lookup set/map. But if the type is mutable, then it is arguably not incorrect to include mutable data in the hash code, subject to the aforementioned limitation.

**Comment by Evangelink** [comment]
Hi @sharwell,

Thanks for the quick feedback on this. I was suggesting this change based on the special notes of this [msdn page](https://msdn.microsoft.com/en-us/library/system.object.gethashcode%28v=vs.110%29.aspx):

> In general, for mutable reference types, you should override GetHashCode only if:
> - You can compute the hash code from fields that are not mutable; or
> - You can ensure that the hash code of a mutable object does not change while the object is contained in a collection that relies on its hash code.

**Comment by Pilchie** [comment]
Note that `CodeModelEvent.Type` *is* mutable.  Multiple events can get merged together [here](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.Implementation/CodeModel/CodeModelEventQueue.cs,42).  Adding Compiler tag for now, since the other examples are all there.

**Comment by jaredpar** [comment]
Chatted with @VSadov and once our C# 7.2 features are in place we should be able to make all of the SyntaxList types `readonly` and hence not have this problem.

**Comment by Evangelink** [comment]
Out of curiosity, do you guys think that referencing mutable fields in the `GetHashCode` method is not so much of an issue if not used as part of a hash-based collection? What I mean is except if you are in total control of the class (private class) don't you think you should always make sure to design the class as if it could be used in hash-based collection?

**Comment by sharwell** [comment]
@Evangelink I don't currently take a hard-line approach on the issue. The thing that interests me most is strategies to avoid bugs related to the subject matter, e.g. antlr/antlr4#1955 that I found last week.

**Comment by VSadov** [comment]
actionable only when we use C#7.2

**Comment by alrz** [comment]
Probably a good candidate for an analyzer to flag those cases.

**Comment by Evangelink** [comment]
@jaredpar Feel free to close this ticket as it is pretty old and the code did change a lot so it might no longer be accurate/valid.
