### ISSUE TITLE
Consider expanding concurrent execution of analyzer actions

### ISSUE THREAD

**Issue by JohnHamby** [dotnet/roslyn#2059]
The current policy of not running any actions of a given analyzer concurrently is safe, but is perhaps more restrictive than necessary. A set of safe rules that allow for more concurrency is probably possible, and would improve analysis throughput. Here is a set of proposed rules for consideration:

1.    The Initialize methods of two or more different analyzers can run concurrently. We make no guarantees about state shared between analyzers, or about static state.
2.    The actions of two or more different analyzers can run concurrently. We make no guarantees about state shared between analyzers.
3.    Any number of actions that were registered directly by a single analyzer’s Initialize method can run concurrently. We make no guarantees about static state, or about cross-compilation state.
4.    An action A is an ancestor of action B if B was registered either by A or by another action that has A as an ancestor. Two actions X and Y are related if any of these hold:
    a.    X is an ancestor of Y.
    b.    Y is an ancestor of X.
    c.    X and Y have a common ancestor.
    d.    X and Y are the same action, and that action has an ancestor.
5.    Any number of actions of a single analyzer can run concurrently so long as no two of those actions are related.

**Comment by mavasani** [comment]
Thanks a lot @JohnHamby

**Comment by mavasani** [comment]
I think we want 3. and 5. to be non-default. i.e. by default single analyzer's actions won't run concurrently, but if marked explicitly by the author to be multithreaded (we should add this support soon), then they might run concurrently.

**Comment by JohnHamby** [comment]
@mavasani makes an interesting point. Marking an analyzer as "concurrent" does not necessarily have to imply that all actions can run concurrently--the restrictions introduced by 4/5 above could still hold.

The question of requiring opting in vs. defaulting to concurrency is deep. It's not straightforward to write an analyzer that is correct with respect to the action execution order rules and not correct with respect to these concurrency rules, but it may be more possible to write an analyzer that appears to execute correctly given the behavior of the analysis engine but fails with more concurrency.

Sorry that my nested labeled list was corrupted in formatting. This markdown business is apparently too subtle for me.

**Comment by mavasani** [comment]
Agreed. Related actions should not be run concurrently. 

1. All the start actions are primarily for registering nested actions, and hence need to always run first to get the nested actions and can never run concurrently with them. 
2. An end action should always be the final one to run and cannot run concurrently with any nested actions registered by its enclosing start action.

The flag would just indicate that analyzer host is free to invoke all the unrelated actions of the analyzer concurrently.

**Comment by mavasani** [comment]
Closing this out as we have no near term plans for improving core analyzer driver performance or making it's action callbacks more concurrent. We can re-open this when we do so in future. @JohnHamby let me know if you disagree.
