### ISSUE TITLE
AbstractNavigateToSearchService.SearchDocumentAsync iterates project documents

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#20590]
**Version Used**: 
0f658a492302a11277348d1fd1ef2e1d0a0e4130

**Expected Behavior**:
The service should only query the passed in document

**Actual Behavior**:
The services iterates all documents until it matches the one sent in via the parameter

**Comment by sharwell** [comment]
@CyrusNajmabadi Is this one that you've already corrected in one of your Navigate To perf branches?

**Comment by CyrusNajmabadi** [comment]
No.  Have talked to @Therzok about it as well.  This isn't really much of an issue.  The document iteration time is effectively no impact.  So i'll probably keep as is.

**Comment by CyrusNajmabadi** [comment]
Not going to fix as this is an internal impl detail that shouldn't actually impact anything.  Enumerating the documents of a project is essentially free.  And this approach allows us to centralize our code, instead of having to duplicate things unnecessarily.
