### ISSUE TITLE
using static prefers the method group over enum members in an ambigious call

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#20605]
This is more of a question rather than a bug, since "fixing" this is obviously a breaking change.

**Steps to Reproduce**:

```cs
using System;
using static E;
using static X;
class C {
    void M(Action a) {}
    void M(E a) {}
    void Test()
    {
        M(Foo); // binds to the method
    }
}
enum E { Foo }
static class X {
    public static void Foo() {}
}
```
**Expected Behavior**: The call is ambigious

**Actual Behavior**: Compiles fine with `Foo` bound to the method.

Is this the intended behavior and if so why?

**Comment by alrz** [comment]
Is this mentioned in the spec?

**Comment by gafter** [comment]
Similarly, using DIM features

``` c#
using System;
public class C {
    public void M1()
    {
        M2(I3.X); // binds to the method X, not the constant
    }
    static void M2(int X) { }
    static void M2(Action X) { }
}

interface I1
{
    const int X = 1;
}
interface I2
{
	static void X() { }
}
interface I3 : I1, I2
{
}
```

**Comment by alrz** [comment]
So the behavior is at least consistent. I'm wondering how method groups take precedence while, to my understanding, *name lookup* doesn't look into the kind of members.

**Comment by gafter** [comment]
Name lookup in https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#member-lookup certainly does look into the kind of members.

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We're doing all language design now at dotnet/csharplang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!
