### ISSUE TITLE
Async state machine 'Start' called on a copy of the state machine

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#20606]
**Version Used**: 15.3 Preview 3

**Steps to Reproduce**:

1. Create a custom task-like type with the method builder implemented as a `struct`
2. In the `Start<TStateMachine>` method, set the value of a field of the method builder
3. In the `SetResult` method, read the value of the field

**Expected Behavior**:

The value read in `SetResult` will match the value written to the field in `Start<TStateMachine>`.

**Actual Behavior**:

The value read in `SetResult` is the value of the field at the point `Create()` returned.

**Cause**:

The `Start<TStateMachine>` method is called on a copy of the builder on the stack instead of calling it on the instance returned from `Create()`.

**Workaround**:

Set the state in `Create()` instead of `Start<TStateMachine>`.

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler I marked this as a bug, though the [spec for this feature](https://github.com/dotnet/roslyn/blob/master/docs/features/task-types.md) was not clear enough to determine whether this was an intentional design for some reason.

**Comment by jcouv** [comment]
FYI, moved out of C# 8 RTM

**Comment by madelson** [comment]
> Workaround:
> Set the state in Create() instead of Start<TStateMachine>.

This is not a complete workaround since at the point when Create() is called we don't have access to TStateMachine yet.

> jcouv modified the milestones: 16.3, Compiler.Next on Jul 8, 2019

Curious what this means in terms of timeline. Are we waiting for the next minor version of C# itself or will this be fixed in a compiler patch?

**Comment by jcouv** [comment]
A community member is working on a [fix](https://github.com/dotnet/roslyn/pull/41253) as we speak. If it goes well, it would be available in in VS 16.6 and corresponding minor release of .NET Core.
