### ISSUE TITLE
Handle OOM in TemporaryStorageServiceFactory without crashing 

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#20621]
**Version Used**: 15.3 Preview 3

:link: This will provide a long-term solution to [Bug 459031](https://devdiv.visualstudio.com/DevDiv/_workitems?id=459031) (this is just an automatic crash report that is sent when the situation occurs).

**Steps to Reproduce**:

Encounter a situation in which TemporaryStorageServiceFactory fails to provide requested storage due to *two* IOException instances getting thrown due to lack of available memory.

**Expected Behavior**:

Code analysis engine shuts down so the IDE provides the ability for users to save their work and restart.

**Actual Behavior**:

The IDE crashes.

**Comment by CyrusNajmabadi** [comment]
Seems unlikely we'd ever do anything here.  Esp. in the 64bit world.
