### ISSUE TITLE
Roslyn ships (parts) of System.Composition

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#20620]
We have these two hacks:

1. https://github.com/dotnet/roslyn/blob/6baa2b770f01b01c9c3db2443d08768d2daee4ab/src/VisualStudio/Setup.Next/VisualStudioSetup.Next.csproj#L92-L93
2. https://github.com/dotnet/roslyn/blob/6baa2b770f01b01c9c3db2443d08768d2daee4ab/src/VisualStudio/Setup/VisualStudioSetup.csproj#L212-L215

which was working around a problem that VS shipped some but not all the parts of MEF that we depended on. That was really terrible, and should be cleaned up now. This was particularly confusing to @jaredpar who incorrectly assumed we did sane things.

**Comment by AdamSpeight2008** [comment]
Being *"sane"* was in the job description?
