### ISSUE TITLE
Renaming the default namespace should update the RootNamespace property of the project

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#2062]
**Repro Steps:**
1. Create a C# console application.
2. In Program.cs, invoke Rename on the namespace declaration. Change it to something else and press ENTER to commit the change.

**Expected Result:**

Dialog appears to allow user to change the default namespace, updating the project file.

![image](https://cloud.githubusercontent.com/assets/116161/7192569/af55cff6-e44b-11e4-959a-f23726987c38.png)

**Actual Result:**

No dialog. :frowning: 

_This is a regression from Visual Studio 2013_

**Comment by Pilchie** [comment]
See also internal TFS Bug 1208184.

**Comment by CyrusNajmabadi** [comment]
Unlikely to do this.
