### ISSUE TITLE
Base call constructor: Parameterless versus optional parameters

### ISSUE THREAD

**Issue by Logerfo** [dotnet/roslyn#20633]
### Steps to reproduce
Compile the following class in what we are going to call as "Assembly 1" (a library):
```c#
public class B
{
   public B() { }
}
```
Compile the following class in what we are going to call as "Assembly 2" (an application):
```c#
public class C : B
{
   public C() { }
}

internal class Program
{
   private static void Main()
   {
      new C();      
   }
}
```
Recompile Assembly 1 with class B now looking like this:
```c#
public class B
{
   public B(object p = null) { }
}
```

### Expected behavior (by me, actually)
Assembly 2 will run normally.

### Actual behavior
Assembly 2 will throw a `MissingMethodException`, looking for a parameterless constructor in `B`, unless you recompile it (which happens normally).

### Reason:
Assembly 2 IL looks like this before recompilation:
```asm
IL_000a: call instance void [Assembly1]Assembly1.B::.ctor()
```
And like this after recompilation:
```asm
IL_000a: call instance void [Assembly1]Assembly1.B::.ctor(object)
```
_is there a markup for CIL in GitHub?_

### Question:
Would it be possible for the runtime to workaround this, looking for a constructor that would match the parameters and calling it, instead of throwing the exception? That would be great, because adding a optional parameter to the constructor would stop being a breaking change if you only update the corresponding library.
Also: am I asking this in the right place? Should I be doing it in a runtime repository or something like that? Please refer me to the right place if I'm not.
Thank you very much.

**Comment by gafter** [comment]
This is a request for a change to the behavior of the runtime (i.e. a change to the CLR specification). I recommend making the request in https://github.com/dotnet/coreclr .
