### ISSUE TITLE
IDE0006 Error

### ISSUE THREAD

**Issue by rhaverty** [dotnet/roslyn#20640]
**Version Used**:

* Surface Book
* Windows 10
* Visual Studio 2017

(Edited by @sharwell to expand the document contents inline)

:link: [Original issue](https://github.com/dotnet/roslyn/files/1124672/VS.2017.Issue.docx) (Word format)

**Steps to Reproduce**:

| Severity | Code | Description | Project | File | Line | Suppression State |
| --- | --- | --- | --- | --- | --- | --- |
| Warning | | Cannot find wrapper assembly for type library "EnvDTE80". Verify that (1) the COM component is registered correctly and (2) your target platform is the same as the bitness of the COM component. For example, if the COM component is 32-bit, your target platform must not be 64-bit. | PCO to iSolved Convesion | | | |
| Warning | IDE0006 | Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled. | PCO to iSolved Convesion | | 1 | Active |
| Warning | | The referenced component 'EnvDTE80' could not be found. | PCO to iSolved Convesion | | | |

When I attempt the solution found on the Web I get:

![image](https://user-images.githubusercontent.com/1408396/27874905-eb302062-6176-11e7-9767-41c6c579775a.png)

The Web solution:

![image](https://user-images.githubusercontent.com/1408396/27874931-022297aa-6177-11e7-88e4-8c628f02e127.png)

**Comment by gafter** [comment]
@rhaverty This issue does not contain sufficient detail to act on. Please add more detail and reopen.

**Comment by gafter** [comment]
The warning shown in the attachment is

Cannot find wrapper assembly for type library "EnvDTE80". Verify that (1) the COM component is registered correctly and (2) your target platform is the same as the bitness of the COM component. For example, if the COM component is 32-bit, your target platform must not be 64-bit.

**Comment by sharwell** [comment]
@rhaverty This sounds like the kinds of issues seen when a project uses `<COMReference>` instead of `<Reference>` for the interop assemblies. One example of where this was fixed in a Visual Studio extension can be seen here: https://github.com/gitextensions/gitextensions/pull/3439/commits/965dc9ec13721ea8b673016b5a9a7f17200ebb17

**Comment by Pilchie** [comment]
@rhaverty Note that in the instructions it says to type `set TRACEDESIGNTIME=true`, but in your screenshot `set` is missing.

**Comment by Pilchie** [comment]
I wonder if this is because of VS 2017's move to not be in the GAC, etc.

**Comment by Pilchie** [comment]
Starting with @sharwell since you've seen issues like this before.

**Comment by CyrusNajmabadi** [comment]
@sharwell is there anything we need to do here?
