### ISSUE TITLE
Broken IntelliSense and syntax coloring if you have two files that have file names that culturally equal

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#20659]
**Version Used**: 

**Steps to Reproduce**:

1. Create a new project .NET Console App (.NET Framework)
2. Add Encyclopaedia.cs
3. Add Encyclopædia.cs
4 Reload project (unsure if this is needed)
5. Open both files

**Expected Behavior**:
Both to have syntax coloring/intellisense

**Actual Behavior**:
1 or both of them is missing syntax coloring/intellisense 
![image](https://user-images.githubusercontent.com/1103906/27891208-cacb4872-623b-11e7-985a-cbc926a9f472.png)

Attempting to open intellisense pops up:

![image](https://user-images.githubusercontent.com/1103906/27891214-db2d2c1c-623b-11e7-924b-bee2d09913a2.png)

Is someone is doing a cultural-aware comparison here on the file names?

**Comment by davkean** [comment]
If you look at the Editor type drop down - looks like the wrong type is displayed in that too.

**Comment by jasonmalinowski** [comment]
Hah, we're sure not intentionally doing a cultural compare anywhere. I suspect this bug won't make me happy once we find the root cause.

**Comment by jasonmalinowski** [comment]
So this looks like a shell bug, at least to start: if I simply create Encyclopædia.txt and Encyclopaedia.txt on my desktop (note: not C# and not even in a project), and try to open both of them with VS, the second open doesn't open a second file tab. In one case, it refreshed the file contents, but didn't refresh the file name.

**Comment by jasonmalinowski** [comment]
Migrated to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/491141 against the editor team. It might have to go even further down to the core shell.
