### ISSUE TITLE
[Loc] Rename in editor causing exception

### ISSUE THREAD

**Issue by vsccarl** [dotnet/roslyn#20653]
**Version Used**: 
2.3.0.6183003
Windows 8.1 Chinese (Traditional)

**Steps to Reproduce**:

1. Right click in editor window
2. Select rename

**Expected Behavior**:
Should be able to rename methods, declarations, etc.

**Actual Behavior**:

![](https://user-images.githubusercontent.com/12900364/27804718-5473475e-5fe5-11e7-869f-c07edfbfaa0f.png)

Originally thought to be Live Unit Testing related but is reproducible without LUT running. [testimpact/2003](https://github.com/dotnet/testimpact/issues/2003)

**Comment by Pilchie** [comment]
Tag @dpoeschl and @nguerrera 

@vsccarl what VS build and branch is this?

**Comment by dpoeschl** [comment]
RenameErrorTextBrushKey was removed in https://github.com/dotnet/roslyn/commit/86e29d7dd096b4b8ddd5324f6da48c127b8a2d87 -- I wonder if this is the loc'd xaml getting out of date thing. @nguerrera

**Comment by dpoeschl** [comment]
I thought we had fixed that a while ago, but I don't understand the version # in this bug (2.3.0.6183003) -- @vsccarl What VS branch/build were you using?

**Comment by Pilchie** [comment]
@vsccarl - can you double check that this is not an issue with the current 15.3 builds?

**Comment by vsccarl** [comment]
Sorry I missed the notifications for these mentions, (had an old rule that was filtering out mail from Roslyn). This was in d15rel, likely build would be 26704.00. 

Verifying now that it isn't still in d15rel.

**Comment by vsccarl** [comment]
I was not able to repro in 15.3 RTM. Appears to be fixed.
