### ISSUE TITLE
NamedParameterCompletionProvider could mandate named arguments after an out-of-position argument

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#20657]
After the change to relax this completion provider to accommodate non-trailing named arguments (https://github.com/dotnet/roslyn/pull/20601), the completion will never be exclusive if LanguageVersion >= 7.2.
We should consider a more refined approach, where the completion is marked as exclusive if the current position follows an argument with a name that is used out-of-position (this requires looking at the various candidate overloads).

For instance, if you have a method `void M(int a, int b)` and start typing an invocation `M(b: 1, $$`, we can determine that you must type an argument name (`a:` in this case) and make that the exclusive completion. There are some more complicated cases when multiple overload are available.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
