### ISSUE TITLE
Roslyn is double-parsing command-line options when we AbstractProject.SetOptions

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#20665]
0.3% of allocations opening ProjectSystem.sln is caused by Roslyn double-parsing command-line arguments:

![image](https://user-images.githubusercontent.com/1103906/27898004-0874d352-6267-11e7-9dde-923d9ae052a8.png)

We're calling IWorkspaceProjectContext.SetOptions and you are parsing it twice; once in SetArgumentsAndUpdateOptions and once in SetRuleSet.

http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.Implementation/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs,122

**Comment by Pilchie** [comment]
A (likely incorrect) fix is in https://github.com/dotnet/roslyn/pull/20152.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski did we ever get around to fixing this?  or is this still a core problem?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi It's been pretty heavily refactored but honestly it'd be good to give an extra check since some of the legacy code menetioned is still around. @Pilchie I'll reassign this to me since I don't think you'll be getting to this soon.

**Comment by Pilchie** [comment]
> I don't think you'll be getting to this soon

:rofl: Yeah, probably not.  Thanks @jasonmalinowski

**Comment by jasonmalinowski** [comment]
Looks like I did fix this when I rewrote all this, a minute or two with the debugger doesn't see any duplicate parsing, even if ruleset files change.
