### ISSUE TITLE
AbstractProject.AddAnalyzerReference allocates 2.5% of opening ProjectSystem.sln

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#20663]
AbstractProject.AddAnalyzerReference is allocating 2.5% (56 MB) of allocations, just opening ProjectSystem.sln:

![image](https://user-images.githubusercontent.com/1103906/27895669-a40b32bc-6257-11e7-98d5-17dc47c21395.png)

This is a lot, and looking at it - looks to be just a bunch of infrastructure related allocation for scheduling tasks, Func<T> allocations, etc.

**Comment by davkean** [comment]
Trace is: \\mlangfs1\public\davkean\Roslyn\20663.

**Comment by sharwell** [comment]
@davkean Can you merge/zip that ETL? In its current form I don't have symbols to work with.

**Comment by Pilchie** [comment]
Also, is this after @jasonmalinowski's change for file-system-watchers here or not?

**Comment by CyrusNajmabadi** [comment]
@davkean i'm guessing this isn't an issue anymore, or else you'd be banging down our door?   Can you let us know if this still needs addressing, or can be closed out?
