### ISSUE TITLE
VisualStudioSetup.Next instance throws Could not load type 'Microsoft.VisualStudio.Text.ITextImage in ServicesVisualStudio project

### ISSUE THREAD

**Issue by zein-makki** [dotnet/roslyn#20670]
**Version Used**: 
Latest Master
And
Microsoft Visual Studio Community 2017
Version 15.0.26228.9 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01038

**Steps to Reproduce**:

1. Set VisualStudioSetup.Next as startup project
2. Hit F5
3. In the experimental instance opened, click open / project solution
4. Choose any existing console application project with one class only

**Expected Behavior**:
Project loaded

**Actual Behavior**:
Exception thrown and experimental VS instance exits

**Details**:

Exception thrown at `TextBufferContainer` method `CreateContainer`:

> System.TypeLoadException: 'Could not load type 'Microsoft.VisualStudio.Text.ITextImage' from assembly 'Microsoft.VisualStudio.Text.Data, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.    at Microsoft.CodeAnalysis.Text.Extensions.TextBufferContainer..ctor(ITextBuffer editorBuffer, Encoding encoding)
>    at Microsoft.CodeAnalysis.Text.Extensions.TextBufferContainer.CreateContainer(ITextBuffer editorBuffer)
>    at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
>    at Microsoft.CodeAnalysis.Text.Extensions.TextBufferContainer.From(ITextBuffer buffer)
>    at Microsoft.CodeAnalysis.Text.Extensions.AsTextContainer(ITextBuffer buffer)
>    at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.MiscellaneousFilesWorkspace.TrackOpenedDocument(UInt32 docCookie, String moniker)
>    at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.MiscellaneousFilesWorkspace.OnAfterAttributeChangeEx(UInt32 docCookie, UInt32 grfAttribs, IVsHierarchy pHierOld, UInt32 itemidOld, String pszMkDocumentOld, IVsHierarchy pHierNew, UInt32 itemidNew, String pszMkDocumentNew)

**Comment by Pilchie** [comment]
@zein-makki In order to use the roslyn, you need to be using the Preview channel of VS from https://www.visualstudio.com/vs/preview/.

**Comment by LYP951018** [comment]
Sorry, but I don't understand the "design". Does that mean we must use VS Preview if we want to use Roslyn?
