### ISSUE TITLE
INavigateToSearchResult is not sufficient for displaying information

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#20676]
**Version Used**: 
5d080fe9b153d2849aab7d1e81f5e7c0632d7e98

**Steps to Reproduce**:

1. Query AbstractNavigateToService
2. Display the data in the UI in VSMac through available fields 
3. Observe that there is presentation layer information loss

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/109974/27922894-38be9aca-6285-11e7-9a93-b0c7a8ffe5ed.png)

Enough data is present in through the interface definitions that we can show this kind of informational tooltip

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/109974/27922922-45b51b46-6285-11e7-947a-de71a9884fd7.png)

There is no return type, modifiers on the symbol, the parameters are not prettied (one per line instead of all in the same line), no extension method information. Working around this by querying the symbol at a given span.

**Comment by Therzok** [comment]
There is a subtle difference which is more or less not important, INavigateToSearchResult shows the `this` inline in the parameters, while VSMac used to discard it and show it on its own line for clarity, I have no strong preference on this.

**Comment by CyrusNajmabadi** [comment]
I'm not sure i agree with this assessment.  Can VS4Mac not use the data provided to go reacquire the symbol and get more information to display?

**Comment by sharwell** [comment]
@CyrusNajmabadi I requested @Therzok file this issue in the expectation that VS4Mac is expected to realize the same gains VS did in #18725.

**Comment by Therzok** [comment]
One other thing is that in our presentation layer we don't have a glyph determining accessibility. We have only the kind glyph, and we append the symbol's accessibility via the tooltip information.

Yes, we _can_ query the symbol information we want from the document's source span. Would just be nice to have this information by default from Roslyn. (Something we can format via TaggedText chunks)

**Comment by CyrusNajmabadi** [comment]
I actually don't think we can do any better here.  Here's why:  say we wanted to include more information in the INavigateToSearchResult.  What information would that be?

First, We obviously can't include the ISymbol as that has no meaning to F#/TS/JS/etc.

We could consider having a PropertyBag on result with information that might be useful.  For example, we could include the symbol key.  However, computing symbol keys is expensive and can't be done syntactically.  That means that either we need semantics for building the index (which would be very problematic), or we'd need semantics when reporting the results (which we know is far too slow).

The benefit of the current system is that it's extraordinarily lightweight.  We can compute the indices on a file by file basis without needing semantics.  Searching can be done in another process easily with all results marshalled over from the OOP server to the host.  

Including additional data just isn't feasible in an efficient manner.  Right now, i would recommend you do the approach whereby as the user goes through the items you asynchronously use the document/location information to go determine what symbol that is so you can supply the information you care about to them.
