### ISSUE TITLE
Edit and Continue is blocking F5 saying edits were made, but none were

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#20680]
My scenario here was I was setting a breakpoint in Roslyn, F5ing VisualStudioSetup.Next, hit the breakpoint, and wanted to continue. Edit and Continue was blocking me doing anything further saying I already had made edits.

**Comment by jasonmalinowski** [comment]
Dump file at `\\mlangfs1\public\jasonmal\Dumps\Roslyn\20680\EncSaysThereAreEditsButNoEdits.dmp`.

**Comment by jasonmalinowski** [comment]
Tagging @jinujoseph and @tmat -- I'm unable to debug right now because of this. 😦

**Comment by CyrusNajmabadi** [comment]
I'm hitting this with the latest builds as well.  However, i was able to get past this by just disabling EnC.  I'm using:

![image](https://user-images.githubusercontent.com/4564579/27941828-895e87b8-6287-11e7-9506-05952e7f99c7.png)

**Comment by jasonmalinowski** [comment]
Current theory is this is related to the move to the new project system in Roslyn.sln: since the language service isn't getting 100% correct project system data, some of those aren't able to build which is blocking things.

**Comment by tmat** [comment]
Should be fixed now: https://github.com/dotnet/roslyn/pull/38905, except for UWP projects. Please reopen if it repros again.
