### ISSUE TITLE
Proposal: (Minor) Unkeyword built-in types (e.g. int)

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#207]
#### Problem
Currently built-in types (`int`, `string`, `etc`) in C# are full keywords.
However, some of those names might be useful variable/parameter names depending on the situation.

For example:
```csharp
foreach (var @byte in hash) ...
foreach (var @char in name) ...
var @object = json.ToObject();
```

At the moment, these names require `@`-escaping -- which is not well-known to most people and rather inconvenient.

#### Proposed solution
Change grammar so that those type keywords are well-known type names instead of full keywords.
This would be similar to how `var` is handled at the moment.

##### Pros:
1. Less special names in the language -- more choice for identifier names
2. More consistent type identifier handling -- both `var`/`dynamic` and `int` will be same for the parser

##### Cons:
1. Colorizers will have to be smarter (but then they already have to, due to `var`/`dynamic`)

**Comment by lyubomyr-shaydariv** [comment]
I think this would make readability even more harder in comparison with the @-escape. I would be greatly confused with:

    public static readonly double int = 2;

or:

    object var = ...;x
    var enum = from ... select ...;
    ...
    foreach ( var in enum ) {
    }

I guess (not a compiler expert) this would make the grammar more complicated and really bound to context. Also I would use good old short names for "trivial" values like `var b in hash` and `var ch in name`.

**Comment by ashmind** [comment]
>  I would be greatly confused with:
```csharp
public static readonly double int = 2;
```

Well you can do `var var = var.var;` right now -- while this is confusing, I don't think anyone does that.
And you can do:
```csharp
public static readonly DateTime DateTime = ...;
```

So I don't see banning `int` from identifiers as a primary solution for terrible naming -- it is a pretty limited special case.

> I guess (not a compiler expert) this would make the grammar more complicated and really bound to context.

Only if you want to highlight those differently from all other types, and even then there is already `var`, so it should make grammar simpler by removing one special case. If you don't care about highlighting it should make grammar simpler as you can just parse a `Type` nonterminal, then resolve `int` to something else at a much later stage.

> Also I would use good old short names for "trivial" values like var b in hash and var ch in name.

Yes you can, and yet I don't see why we need this rather arbitrary naming limitation -- also one-letter names only work well in a very small scope.

**Comment by mirhagk** [comment]
The given example of:

```
foreach (var char in word) 
{
}
```

Is something I find myself writing all the time, and then realizing that `char` is a keyword, and switching to another variable name. It's a small thing but it does break my workflow as I usually finish the loop before I realize that that name is invalid syntax. It's even worse since I can't use rename tools since it's syntactically incorrect rather than semantically. The `@` keyword is not very well known, and so I usually rename the variable to `letter`, `let` or `c`.

It is a major change to the language though so I'm happy putting up with the inconvenience.

**Comment by Miista** [comment]
It's bad practice to name your variables that way. The name of primitives are a set of constant names and as such they can be disallowed at compile time. If you were to disallow anything that might match a class name you would basically disallow any combination of letters.

**Comment by ashmind** [comment]
@mirhagk
> It is a major change to the language though so I'm happy putting up with the inconvenience.

It does not seem to be a large change from the language perspective. As for implementation, it shouldn't be too complex either, but I don't think that work/benefit should discourage this -- in OSS I could try to write a pull request myself if Roslyn team agreed with the idea.

@Miista
> It's bad practice to name your variables that way

I don't think blocking bad naming is a goal in C# language design -- as you mention only a narrow set of keywords is blocked anyway. And I don't find `foreach (var char ...` bad naming -- it is literally each character.

**Comment by RichiCoder1** [comment]
I'm somewhat in agreement with @ashmind here. I agree that the work/benefit means that the language team should probably not consider doing the coding work themselves, but I'd still love to see a review and OSS pull request from a community member on this.

For the issue itself, I also agree that I run into situations where I'm using a type name as a variable name, because I'm breaking down a collection of that type and it, by definition, is the most sensible name for that time. I've also done the same with `param`. 
On the flipside, I agree this could lead to confusion outside of a foreach context.

**Comment by Miista** [comment]
And you can do so. Just add @ in front of the variable name. 

______________
Søren Palmund

**Comment by mirhagk** [comment]
@Miista As mentioned it's a very easy workaround, but the problem is the inconvience and break of workflow it causes. It's very minor.

Also the workaround should really be rename it to something else. `@` should only be used as a last resort since it is not something the majority of developers are familiar with, and it causes quite a bit of confusion the first time a developer sees it.

**Comment by jmarolf** [comment]
What is there was a code fix that offered to add '@'?

**Comment by jmarolf** [comment]
And an alternate code fix that offered rename?

**Comment by ashmind** [comment]
Yes, you can just append `@`, but I don't really see it as an argument against this. I think language shouldn't only grow by adding new features, but also by straightening minor inconveniences and special cases, such as this one.

As @RichiCoder1 said, it's not something I see C# team investing time in, however I would like to get a green light for community contribution.

**Comment by AlgorithmsAreCool** [comment]
For the sake of argument, I would assume that demoting these keywords to contextual keywords would have breaking changes on existing code, would it not?

**Comment by amcasey** [comment]
I can't think of any places where 'int' is allowed but an identifier is not, so I don't think there's a technical reason not to make this change.  However, I do think that there would be a lot of potentially breaking changes.  For example, any library already containing a class called '@int' would probably be surprised to have occurrences of 'int' start binding to that class.  Similarly, it might be worrisome if a library redefined 'string'.

Incidentally, in the foreach example above, I'm a little curious why "char" was chosen as the iteration variable name.  For brevity I would have chosen "c" or "ch" and for clarity I would have chosen "character".  Is it just the appeal of giving the type and the variable the same name?  If so, why use "var"?

**Comment by ashmind** [comment]
> However, I do think that there would be a lot of potentially breaking changes. For example, any library already containing a class called '@int' would probably be surprised to have occurrences of 'int' start binding to that class. Similarly, it might be worrisome if a library redefined 'string'.

Hmmm, that is a valid argument, and one I haven't thought of. Not very likely, and yet still worrisome. I suppose it's worth leaving it up to .NET team to decide.

> Incidentally, in the foreach example above, I'm a little curious why "char" was chosen as the iteration variable name. 

Even though 'character' would be better, in all .NET char is always called char, so it's not surprising people stop seeing it as an abbreviation. I think `byte` demonstrates the same idea without this question.

**Comment by gafter** [comment]
It is hard to imagine that we'd spend any effort here to do anything. The benefit is nearly nonexistent.
