### ISSUE TITLE
ERRWRN_Last breaks string resource loading of actual last warning or error

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#20701]
`ERRWRN_Last` is defined as `ERRWRN = WRN_Experimental`. As a result, `ErrorFactory.IdToString()` may return `"ERRWRN_Last"` rather than `"WRN_Experimental"` when attempting to load the string resource for `WRN_Experimental`.

See test [failures](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit64_prtest/7796/).

**Comment by AdamSpeight2008** [comment]
Is there any reason to keep `ERRWRN_Last`? If it has the same value as `WRM_Experimental`.

**Comment by AdamSpeight2008** [comment]
Alternative fix in #20714
