### ISSUE TITLE
IDE does not offer to simplify qualified name in 'is pattern'.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#20725]
With the given code:

```c#
public class Class1
{
    int i;

    public override bool Equals(object obj)
    {
        return obj is global::Class1 @class &&
               this.i == @class.i;
    }
}
```

IDE does not offer to simplify "global::Class1" to "Class1".  This is due to the same issue reported here: https://github.com/dotnet/roslyn/issues/20724

**Comment by CyrusNajmabadi** [comment]
@gafter You should be able to repro this by writing a simple unit test that takes the above tree and then attempts to rewrite ```obj is global::Class1 @class && this.i == @class.i``` into ```obj is Class1 @class && this.i == @class.i``` and binds that rewritten node in a speculative semantic model.

In the original semantic model GetTypeInfo returns System.Boolean (since it's an && expression).  In the speculative model GetTypeInfo returns an Error type.

Note: to get the rewritten node, we actually replace ```global::Class1``` with its RHS.  i.e. we use the actual ```Class1``` node that was in the original tree.

I hope this is enough to create a good unit test you can use to repro this.

**Comment by gafter** [comment]
Why isn't this just a dup of #20724?

**Comment by CyrusNajmabadi** [comment]
They're *very likely* the same.  But i haven't actually established that that's the case.  This is also a much simpler repro that doesn't involve nearly as many steps as in #20724 .  Feel free to handle these as you wish.

**Comment by sharwell** [comment]
@gafter Sometimes we apply "special logic" to handle known edge cases in simplification in order to improve performance on hot paths (it's come up a few times recently with work on IDE0004). I believe the use of separate issues here is primarily to ensure a dedicated test is included for this code path.

**Comment by zaytsev-victor** [comment]
I've looked at this issue. I found that for simplified expression ```localSymbol.ScopeBinder.ValidateDeclarationNameConflictsInScope(localSymbol, diagnostics)``` returns true (in ```Binder.BindDeclarationPattern``` function).
And since we have an error (error CS0136: A local or parameter named 'class1' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter) speculative model GetTypeInfo returns an Error type.

**Comment by CyrusNajmabadi** [comment]
Looks like an issue in the compiler layer.  Assigning to area-compilers.  @gafter  who would be bestt to look at this?

**Comment by CyrusNajmabadi** [comment]
@gafter @jaredpar Is there someone this should be assigned to?

**Comment by gafter** [comment]
I suspect this is due to the speculative semantic model seeing a duplicate declaration (of a name that is already in scope), which is an error. I'm not sure how we want the APIs to respond in this situation.

**Comment by CyrusNajmabadi** [comment]
> I suspect this is due to the speculative semantic model seeing a duplicate declaration (of a name that is already in scope),

@gafter which duplicate declaration is it seeing?

**Comment by CyrusNajmabadi** [comment]
Oh.  You do you mean because the original has "obj is global::Class1 @class"  and the speculative has "obj is Class1 @class"?  And thus there are two '@class's in scope?

**Comment by gafter** [comment]
Yes, that is what I suspect. This didn't happen before because expressions did not introduce locals before.

**Comment by CyrusNajmabadi** [comment]
@gafter Here's an idea:

The current problem seems to stem from the compiler being very 'position oriented' when it comes to speculating.  i.e. the user takes an existing piece of code, and asks what a new expression means at a certain position.  

However, we could instead perhaps get more value saying "i want to speculate what things mean if i replace this expression/statement with this other expression/statement".  Ideally the speculative model would still use nearly all the semantic data *outside* of the method body.  But we would figure out the new meaning of hte method body cheaply so we could use it for answering semantic questions properly.

If we did this, we wouldn't have the issue of having a conflict between two locals.  i.e. instead of asking:

```c#
// What does "obj is Class1 @class" mean at the start of:
return obj is global::Class1 @class && ...
```

We would then ask:

```c#
// What does "obj is Class1 @class" mean if we replace 'obj is global::Class1 @class' with it in
return obj is global::Class1 @class && ..
```

What do you think @gafter

**Comment by CyrusNajmabadi** [comment]
tagging @DustinCampbell as well as he has a ton of experience and insight about how simplification works and how we use speculation.

**Comment by CyrusNajmabadi** [comment]
Another, simpler, solutoin would be that we use the existing speculative approach *however* we make teh compiler more resilient with duplicate locals.  i.e. the problem we have here is as i stated above:

> In the original semantic model GetTypeInfo returns System.Boolean (since it's an && expression). In the speculative model GetTypeInfo returns an Error type.

Even if we had duplicate locals, we could make the compiler handle that case better.  For example, if the locals have the same name and same type, we could have it not error out here when doing the rest of binding.  

Thoughts @gafter ?

**Comment by CyrusNajmabadi** [comment]
(i prefer the latter as it would require no API change.  It would just be about having the compiler change things so we don't do this:

> And since we have an error (error CS0136: A local or parameter named 'class1' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter) speculative model GetTypeInfo returns an Error type.

**Comment by gafter** [comment]
I think it would make much more sense to have the compiler tolerate duplicate locals between a speculation and the program in which it is speculated.

**Comment by gafter** [comment]
I could not repro this in the `features/recursive-patterns` branch.

**Comment by CyrusNajmabadi** [comment]
@gafter 

> I could not repro this in the features/recursive-patterns branch.

Do you have a test that demonstrates that this works inside a speculative model?  That would be valuable i think.  I can try to resurrect this feature again to see if i still have a problem here.

**Comment by gafter** [comment]
I added a couple of tests for that in https://github.com/dotnet/roslyn/pull/26295
