### ISSUE TITLE
SemanticModel.GetSymbolInfo(...).Symbol returns null

### ISSUE THREAD

**Issue by rogeralsing** [dotnet/roslyn#20731]
**Version Used**: 
I have tried both 2.0 and 3.0 dev from myget

**Steps to Reproduce**:
Clone and run the CsToKotlin solution found here: https://github.com/rogeralsing/ProjectExodus/tree/roslyn3
(note branch "roslyn3")

Run the main application and wait for the debugger to hit.

There is a bit of code in "VisitorHelper.cs" which handles this

```csharp
          var si = _model.GetSymbolInfo(type);
            var s = si.Symbol;
            if (s == null) //symbol is null
            {
                Debugger.Break(); 
```

![image](https://user-images.githubusercontent.com/647031/27996134-d2510d82-64db-11e7-9b7a-9a97cc6edcfd.png)

**Expected Behavior**:

`_model.GetSymbolInfo(type).Symbol` should not return null.

**Actual Behavior**:
The application breaks on the above mentioned Debugger.Break() due to returned type Symbol being null.

This happens in _some_ documents for _some_ types.
for example, in the project "Proto.Actor" many documents fail on resolving "System.Threading.Task", while in the small debug project also included in the same solution, Task resolves just fine.

![image](https://user-images.githubusercontent.com/647031/27996139-ef432f6a-64db-11e7-8dbf-9d3ef72b3d9c.png)

**Comment by jcouv** [comment]
@rogeralsing Thanks for reporting this. To make this issue more actionable, could you try and narrow the problem to a code sample that demonstrates the problem?

**Comment by rogeralsing** [comment]
I've tracked this down somewhat, adding the nuget `microsoft.extensions.logging` to a clean full .NET 4.6.1 console application makes it unable to resolve Task.

I will create a smaller example for this.

**Comment by rogeralsing** [comment]
I'm unable to reproduce this in any isolated form so far.
It does seem to have something to do with assembly versions in the analyzed solution as adding certain nugets to the projects in the solution makes those projects fail,

I will continue to dig into this

**Comment by rogeralsing** [comment]
I've found the issue.
Adding some nuget packages adds this to the csproj file:

```
  <Import Project="..\..\packages\Microsoft.Packaging.Tools.1.0.0-preview2-25401-01\build\Microsoft.Packaging.Tools.targets" Condition="Exists('..\..\packages\Microsoft.Packaging.Tools.1.0.0-preview2-25401-01\build\Microsoft.Packaging.Tools.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\..\packages\Microsoft.Packaging.Tools.1.0.0-preview2-25401-01\build\Microsoft.Packaging.Tools.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\Microsoft.Packaging.Tools.1.0.0-preview2-25401-01\build\Microsoft.Packaging.Tools.targets'))" />
    <Error Condition="!Exists('..\..\packages\NETStandard.Library.2.0.0-preview2-25401-01\build\NETStandard.Library.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\NETStandard.Library.2.0.0-preview2-25401-01\build\NETStandard.Library.targets'))" />
  </Target>
```

Removing those lines makes everything work as expected

**Comment by Pilchie** [comment]
@rogeralsing had you restored the packages?

**Comment by jaredpar** [comment]
Closing down due to inactivity.
