### ISSUE TITLE
Would like some way to decide if an analyzer should run on on syntax tree at all.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#20736]
Several IDE analyzers only do work if a specific LanguageVersion or .editor_config option is set.  For example, we don't want to offer to convert code to use some new language feature if the language version is less than the version where that feature was added.

Right now the analyzer must register for some sort of syntax node to be called back on.  This mean it might get thousands of callbacks for a file, and each callback will need to do an option check to then bail out.  If the analyzer could run first on the syntax tree and decide it doesn't need to do any work, we could save those thousands of callbacks.

**Comment by CyrusNajmabadi** [comment]
Tagging @srivatsn @mavasani

**Comment by CyrusNajmabadi** [comment]
For example, here's an analyzer that has this issue:
https://github.com/dotnet/roslyn/pull/19907/files#diff-64e1a867f5d1363da7ca518cdb658623

It will execute this code on *every* if-statement and while-statement in the entire solution:

```c#
if (((CSharpParseOptions)syntaxTree.Options).LanguageVersion < LanguageVersion.CSharp7)
```

**Comment by AdamSpeight2008** [comment]
I've been asking for this for ages. 
Is there an interface we could opt into?
```
interface IAnalyserParseOptions()
  function Applicable(Of T As ParseOptions)(options As T) As Task(Of Boolean)
end interface 
```
Also we should look at making the Feature Checking code public *(even as unsupported)*, so we have a common method of checking and thus not re-implementing in each analyser.

**Comment by sharwell** [comment]
@CyrusNajmabadi Why not register the callback in a compilation start action (assuming the language version cannot vary within a single compilation)?

**Comment by AdamSpeight2008** [comment]
If the `Initialize(context As AnalysisContext)` provided the ParseOptions this could work.

**Comment by CyrusNajmabadi** [comment]
> Why not register the callback in a compilation start action

> I've been thinking a bit about the configuration case in the past but haven't arrived at a conclusion.

That's why :)   I'd just like to have a single solution that addresses this.  Most of the cases i care about still have the feature needing to check a configuration option.  So we'd still have thousands of callbacks even if the option is off.

**Comment by CyrusNajmabadi** [comment]
> If the Initialize(context As AnalysisContext) provided the ParseOptions this could work.

I'm not sure how this would work.  It seems like it would be too finicky.  What would the parse options be indicating?  Would SyntaxTrees have to have their options exactly match it?  How would you indicate "only run this if the tree version is X or higher" or "only run this if the tree version is X or lower"?

**Comment by sharwell** [comment]
> Most of the cases i care about still have the feature needing to check a configuration option.

Note that there are two specific cases which would be considered different bugs:

1. **Disabling a rule based on language version:** the compilation start callback registrations are designed to address this case.
2. **Disabling a rule based on severity specified in .editorconfig:** after the design for specifying severity in .editorconfig is complete and implemented, the analyzer infrastructure will be expected to automatically apply this case to avoid callbacks for files where a rule is disabled.

Can you elaborate on some cases which do not fall into these buckets, which would especially benefit from reducing the number of callbacks?

**Comment by CyrusNajmabadi** [comment]
Support for this was added, and our analyzers were fixed up to bail early if they don't need to run.
