### ISSUE TITLE
[Question] Use latest version of Roslyn with VS2015

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#20732]
Hi guys,

We have an extension for VS (2015 no update to 2017) providing custom rules (based on roslyn 1.0) and we are wondering if you could think of any better way than duplicating the code (or part of it) so that we could use the latest API while still remaining compatible with VS2015 no update?

Thanks for your feedback!

**Comment by sharwell** [comment]
It is possible to retain compatibility with Visual Studio 2015, but the mechanism to do so varies substantially based on the specific API you are trying to use. Can you clarify each specific API you would like to use?

**Comment by Evangelink** [comment]
Hi @sharwell!

Not sure whether you want the list of old APIs or the list of the new ones. Basically we have this code base ([SonarC#](https://github.com/SonarSource/sonar-csharp/tree/master/sonaranalyzer-dotnet)) and we want to keep compatibility with VS2015 no update (at best and Update 3 at worst) while being able to rely on new features (especially everything around the syntax of C# 7). We haven't had the opportunity to make many tests yet but simply updating Roslyn NuGet makes the analyzer no longer working with VS2015 no update. If you have some documentation/guidance around how to solve this issue we would be really glad!

I do understand the question might be a bit vague but as we are developing static code analyzers based on Roslyn we tend to use a wild range of the APIs you provide.

**Comment by sharwell** [comment]
@Evangelink I'm looking for a list of new APIs you want to use.

For *syntax specifically*, the StyleCop Analyzers rolled a wrapper for everything that is compatible with 2015 and 2017. See DotNetAnalyzers/StyleCopAnalyzers#2370. For other APIs let me know.

**Comment by Evangelink** [comment]
@sharwell We will have a look at this wrapper and will get back to you with a precise list.

Thanks

**Comment by Evangelink** [comment]
Hi @sharwell.
We have decided to split the analyzer into 2 solutions that will use different versions of Roslyn in order to support C#7.

I think you can close this ticket.
