### ISSUE TITLE
Exception filters and pattern matching syntax

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#2074]
F# treats exception handling as a specialized case of pattern matching:

F# - try:
```fsharp
try
    expression
with
    | pattern -> expression
    | pattern -> expression
```

F# - match:
```fsharp
match expression
with
    | pattern -> expression
    | pattern -> expression
```

On the surface it seems like a good idea and made me question whether this was really a good moment to add exception filtering to C# syntax.

C# - try:
```csharp
try { … }
catch (MyException e) when (myfilter(e))
{
    …
}
```

C# - match: ? What options do we have now:

* ```try-catch``` and ```switch``` diverge in terms of syntax?
* expression syntax is created for ```try-catch``` as well?

PS: a bit trollish, but has a point - http://tomasp.net/blog/2015/csharp-pattern-matching/index.html

**Comment by gafter** [comment]
Love that link.

**Comment by gafter** [comment]
Closing. We cannot change existing syntax.
