### ISSUE TITLE
(-(2147483648)).GetType () different result than csc.exe

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/roslyn#2075]
I think this is bug:
```csharp
using System;
 
namespace roslynChanges
{
	class MainClass
	{
		public static void Main (string[] args)
		{
			Console.WriteLine ((-(2147483648)).GetType ());
		}
	}
}
```
Compiled with VS2015(roslyn) output of this program is:
System.Int32
Compiled with VS2013(csc) output of this program is:
System.Int64

**Comment by AdamSpeight2008** [comment]
Numeric Literals without a decimal point or type specifier are Int32.

**Comment by gafter** [comment]
The type depends on the value of the literal. From 2.4.4

> The type of an integer literal is determined as follows:

> •	If the literal has no suffix, it has the first of these types in which its value can be represented: int, uint, long, ulong.
•	If the literal is suffixed by U or u, it has the first of these types in which its value can be represented: uint, ulong.
•	If the literal is suffixed by L or l, it has the first of these types in which its value can be represented: long, ulong.
•	If the literal is suffixed by UL, Ul, uL, ul, LU, Lu, lU, or lu, it is of type ulong.
If the value represented by an integer literal is outside the range of the ulong type, a compile-time error occurs.

> As a matter of style, it is suggested that “L” be used instead of “l” when writing literals of type long, since it is easy to confuse the letter “l” with the digit “1”.

> To permit the smallest possible int and long values to be written as decimal integer literals, the following two rules exist:

> •	When a decimal-integer-literal with the value 2147483648 (2<sup>31</sup>) and no integer-type-suffix appears as the token immediately following a unary minus operator token (§7.7.2), the result is a constant of type int with the value −2147483648 (−2<sup>31</sup>). In all other situations, such a decimal-integer-literal is of type uint.
•	When a decimal-integer-literal with the value 9223372036854775808 (2<sup>63</sup>) and no integer-type-suffix or the integer-type-suffix L or l appears as the token immediately following a unary minus operator token (§7.7.2), the result is a constant of type long with the value −9223372036854775808 (−2<sup>63</sup>). In all other situations, such a decimal-integer-literal is of type ulong.

Roslyn is apparently too liberal in handling the penultimate bullet, improperly ignoring the parens.

**Comment by AlekseyTs** [comment]
@VSadov Please verify
