### ISSUE TITLE
Weird Formatting Issue With String Interpolation

### ISSUE THREAD

**Issue by JasonBock** [dotnet/roslyn#2076]
When I parse code that contains string interpolation, I end up getting formatting issues that leave the resulting code in a state that cannot be compiled.

To reproduce, create a "Compiler Platform Console Application" in VS2015 CTP6, and put the following code into Program.cs:

```C#
using System;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace StringInterpolationIssue
{
	class Program
	{
		static void Main(string[] args)
		{
			var code =
@"public class MyClass
{
	public string Foo(int a)
	{
		return $""Message is {a}"";
   }
}";

			var tree = SyntaxFactory.ParseSyntaxTree(code)
				.GetCompilationUnitRoot().NormalizeWhitespace();

			Console.Out.WriteLine(tree);
		}
	}
}
```

What I see in the console window is this:

```
public class MyClass
{
    public string Foo(int a)
    {
        return $"Message is
        {
        a
        }

        ";
    }
}
Press any key to continue . . .
```

If I copy the class code into a CS file, I get 5 compilation errors.

Note that if I take out the call to NormalizeWhitespace() the code is fine (but then I lose the whitespace normalization).

**Comment by mattwar** [comment]
Fixed by #2121
