### ISSUE TITLE
Can't install Roslyn

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#20762]
I though this would be straightforward but alas very few things are these days, especially in the world of software.

I am working on a console app targeting .Net Framework 4.5, I then tried to add Roslyn by adding nuget package Microsoft.CodeAnalysis. But that step fails:

"_Could not install package 'Microsoft.CodeAnalysis.Common 2.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."_

I visited the Nuget page but alas no mention of what frameworks this is compatible with, no mention of any pre-requisities.

Clearly I'm doing something wrong but searching for "installing roslyn" in Google is what led me to try the above.

**Comment by Pilchie** [comment]
I think this got answered in a different issue, but Roslyn depends on .NET 4.6 (at least for the 2.0 series packages).

**Comment by Korporal** [comment]
@Pilchie - Thanks, yes its OK now, but it would be great if someone at MS could edit the Nuget page and list these framework versions etc, that would be so helpful.

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-infrastructure.

**Comment by jasonmalinowski** [comment]
@Korporal Which page were you looking at where you expected to see that info?
