### ISSUE TITLE
Analyze C# and VB in same app?

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#20771]
How can I write a single app (say a console app) that can analyze C# source files and VB? In a (C#) test app I put together, I added Nuget package Microsoft.CodeAnalysis. That added a bunch of assemblies including Microsoft.CodeAnalysis.CSharp (which is where SyntaxFactory lives).

This works fine and I can parse a .cs file and see the tree - all good.

But now I want to also analyze VB source files - since the static class SyntaxFactory is C# specific I guess I need to add another assembly (perhaps Microsoft.CodeAnalysis.VB?) but how?

The libraries for C# were added when I added the Nuget package and it looks like it somehow deduced that my app is written in C# and so added the C# specific libraries.

The Nuget package seems language agnostic and at no point was I asked "Do you want to add the C# or VB analysis library?" so somehow it decided to add C# and only C# libraries.

So what must I do to my console app project (as I say its written in C# and in VS 2017 with .Net 4.6) so that I can access both the C# and VB versions of SyntaxFactory?

Thanks

**Comment by CyrusNajmabadi** [comment]
SyntaxFactory is in a C# namespace.  You can add references to our VB nuget packages, and then use the VB specific syntax factory (in Microsoft.CodeAnalysis.VisualBasic...)

**Comment by Pilchie** [comment]
You should have gotten references to both languages when you added the package.

**Comment by Korporal** [comment]
@Pilchie - The only "Roslyny" assembly references in the project are:

Microsoft.CodeAnalysis
Microsoft.CodeAnalysis.CSharp
Microsoft.CSharp (this was already present before adding the Nuget package).

Now of course I can explicitly add an assembly file references to the assembly within the packages folder, but that then creates an inconsistent setup. I spent time often at work "fixing" messes created by Nuget's idiosyncracies including this where a developer has added a file ref rather than a package ref.

**Comment by Pilchie** [comment]
What exact package ids do you have referenced?  We have:

## Language Neutral
* Microsoft.CodeAnalysis.Common
* MIcrosoft.CodeAnalysis.Workspaces.Common

## C#
* Microsoft.CodeAnalysis.CSharp
* Microsoft.CodeAnalysis.CSharp.Workspaces

## VB
* Microsoft.CodeAnalysis.VisualBasic
* Microsoft.CodeAnalysis.VisualBasic.Workspaces

## Both languages
* Microsoft.CodeAnalysis

**Comment by Korporal** [comment]
@Pilchie - Thanks, here's the full packages.config in the project to which I added the Nuget package:

` <package id="Microsoft.CodeAnalysis.Analyzers" version="1.1.0" targetFramework="net46" />
  <package id="Microsoft.CodeAnalysis.Common" version="2.2.0" targetFramework="net46" />
  <package id="Microsoft.CodeAnalysis.CSharp" version="2.2.0" targetFramework="net46" />
  <package id="System.AppContext" version="4.3.0" targetFramework="net46" />
  <package id="System.Collections" version="4.3.0" targetFramework="net46" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="net46" />
  <package id="System.Collections.Immutable" version="1.3.1" targetFramework="net46" />
  <package id="System.Console" version="4.3.0" targetFramework="net46" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net46" />
  <package id="System.Diagnostics.FileVersionInfo" version="4.3.0" targetFramework="net46" />
  <package id="System.Diagnostics.StackTrace" version="4.3.0" targetFramework="net46" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="net46" />
  <package id="System.Dynamic.Runtime" version="4.3.0" targetFramework="net46" />
  <package id="System.Globalization" version="4.3.0" targetFramework="net46" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="net46" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="net46" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net46" />
  <package id="System.Linq" version="4.3.0" targetFramework="net46" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="net46" />
  <package id="System.Reflection" version="4.3.0" targetFramework="net46" />
  <package id="System.Reflection.Metadata" version="1.4.2" targetFramework="net46" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net46" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net46" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net46" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="net46" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net46" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="net46" />
  <package id="System.Text.Encoding.CodePages" version="4.3.0" targetFramework="net46" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="net46" />
  <package id="System.Threading" version="4.3.0" targetFramework="net46" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="net46" />
  <package id="System.Threading.Tasks.Parallel" version="4.3.0" targetFramework="net46" />
  <package id="System.Threading.Thread" version="4.3.0" targetFramework="net46" />
  <package id="System.ValueTuple" version="4.3.0" targetFramework="net46" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="net46" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="net46" />
  <package id="System.Xml.XmlDocument" version="4.3.0" targetFramework="net46" />
  <package id="System.Xml.XPath" version="4.3.0" targetFramework="net46" />
  <package id="System.Xml.XPath.XDocument" version="4.3.0" targetFramework="net46" />`

Almost all of these were added indirectly as a result of me adding the 2.2.0 of Microsoft.CodeAnalaysis package (to my rudimentary C# console app - .Net 4.6).

You'll notice that no entry exists for Microsoft.CodeAnalysis.VisualBasic.

**Comment by Korporal** [comment]
Also, will the VB code analysis allow me to analyze old VB ASP Classic VB source code/pages?

**Comment by Pilchie** [comment]
> You'll notice that no entry exists for Microsoft.CodeAnalysis.VisualBasic.

Right - you added `Microsoft.CodeAnalysis.CSharp`, not `Microsoft.CodeAnalysis`.  You can add `Microsoft.CodeAnalysis.VisualBasic` to add compiler level support for VB, or add `Microsoft.CodeAnalysis` to get VB *and* the Workspaces layer.

> Also, will the VB code analysis allow me to analyze old VB ASP Classic VB source code/pages?

No - Roslyn only supports VB.NET, not VB6.
