### ISSUE TITLE
Validate file headers during the build

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#20785]
Currently the header used in source files is not validated as part of the build. An existing (third-party) analyzer rule provides the ability to combine this validation with a code fix that inserts/corrects the header as necessary. Adopting this analyzer would be helpful for a few reasons:

1. It helps ensure files have the expected headers
2. It helps Roslyn developers working on the IDE experience understand the desired behavior of additional analyzers and code fixes
3. It defers the work on this particular code style feature so we can better consider the design choices to make it relevant to a broad audience

**Comment by Youssef1313** [comment]
@sharwell Was that done with IDE0073?

**Comment by sharwell** [comment]
Yes, let me figure out which PR enabled it.
