### ISSUE TITLE
Remove BinderOpt and UseSetterForDefaultArgumentGeneration workaround in C# bound nodes

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#20787]
BoundIndexerAccess and BoundObjectInitializerMember have temporary workaround for IOperation implementation. We should remove the temporary fields BinderOpt and UseSetterForDefaultArgumentGeneration

**Comment by jinujoseph** [comment]
dupe of https://github.com/dotnet/roslyn/issues/19603
