### ISSUE TITLE
Null conditional operator cannot be applied on Func<T>

### ISSUE THREAD

**Issue by busesorin94** [dotnet/roslyn#20786]
**Version Used**: 
Compiler: 2.2.0.61624
Visual Studio 15.2 (26430.14)

**Steps to Reproduce**:

1.  Create new Generic class with a "T" parameter
2.  Add a new Func of "T" property
3.  Create a method invoking the delegate using null-conditional operator

Example:
```
class Test<TValue>
    {
        private Func<TValue> func;
        public TValue CallFunc()
        {
            return func?.Invoke();
        }
    }
```
Edit: I actually need this to be used in this form:

```
class Test<TValue>
    {
        private Func<TValue> func;
        public object CallFunc()
        {
            return func?.Invoke();
        }
    }
```
which, from my point of view is equivalent to:
```
class Test<TValue>
    {
        private Func<TValue> func;
        public object CallFunc()
        {
            if(func != null)
                return func.Invoke();
            return null;
        }
    }
```

**Expected Behavior**:
The code should compile and the null check should be done at runtime.

**Actual Behavior**:
Syntax error: CS0023 Operator '?' cannot be applied to operand of type 'TValue'

**Comment by sharwell** [comment]
The problem here is `TValue` could be a value type, like `int`. Consider the following example:

```csharp
class Test
{
  private Func<int> func;
  public int CallFunc()
  {
    return func?.Invoke();
  }
}
```

Here, you get an error message which makes things very clear: the type of `func?.Invoke()` is `int?`, but your method returns `int`.

There are two ways to resolve this:

1. Constrain `TValue` so that it becomes a reference type:

    ```csharp
    class Test<TValue>
      where TValue : class
    {
      // ...
    }
    ```

2. Use `default(TValue)` (or just `default` for C# 7.1+) as a fallback:

    ```csharp
    return func?.Invoke() ?? default(TValue);
    ```

**Comment by jaredpar** [comment]
> The problem here is TValue could be a value type, like int. Consider the following example where I replaced TValue with int everywhere:

`TValue` shouldn't be in play here though, the `?.` operator is applied to `Func<TValue>` whose type we know. The `TValue` type should only come into play if the `?.` is applied to the result of `Invoke`.

``` c#
func.Invoke()?.ToString()
```

**Comment by sharwell** [comment]
Ah, I see. If the generic type is unconstrained, it would need to be written in the long form:

```csharp
return func != null ? func() : default(TValue);
```

**Comment by jaredpar** [comment]
Hmm, maybe it's the application to the `TValue` as a result of the `?.Invoke` that is being flagged here. 

@gafter

**Comment by sharwell** [comment]
Without knowing whether `TValue` is a reference type or a value type, the result type of `func?.Invoke()` is not known - it's `TValue` for reference types or `TValue?` for value types.

**Comment by gafter** [comment]
From https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#null-conditional-operator

> - Otherwise, let `T0` be the type of `E0`.
>   - If `T0` is a type parameter that is not known to be a reference type or a non-nullable value type, a compile-time error occurs.

The compiler is enforcing this language constraint.
