### ISSUE TITLE
Find All References shows error dialog on alias symbols defined via project property pages

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#2079]
1. Create a VB Project
2. Introduce an [Alias -ed User Imported Namespace](https://msdn.microsoft.com/en-us/library/t4ttw1f9.aspx) through the Project Property page
3. Open a file in the project and reference the Alias.
4. Invoke Find All references on the alias usage.

**Actual**: an error dialog with message "object instance not set to instance of an object". This also implies that highlight references won't work too.
**Expected**: Find All Refereces and Highlight References work.

**Comment by balajikris** [comment]
It no longer throws the exception dialog, but doesn't find references either.

**Comment by Pilchie** [comment]
In that case, I think we can ship 1.0 with this.  Defining aliases in project properties is pretty rare.

**Comment by balajikris** [comment]
Sounds good. I have an initial implementation with commit 754b242 but there are other considerations that i need to address - edgier cases, more tests and guarding against potential performance regressions (if it should be added to [FindReferenceCache](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/FindSymbols/FindReferences/FindReferenceCache.cs)

**Comment by CyrusNajmabadi** [comment]
Closing out as this doesn't seem important enough to fix.  Have heard no external customer feedback on this at all.
