### ISSUE TITLE
Code style to recommend to name arguments that are literals

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#20800]
Relates to [non-trailing named arguments](https://github.com/dotnet/roslyn/issues/19890) feature.

It is common for code reviewers to ask to name arguments that use literals. For example, in `M(true, x);`.
With non-trailing named arguments, this can be done without polluting the remaining arguments that were not ambiguous.

@CyrusNajmabadi @Pilchie I'm separating this work item we had discussed into an issue, since this is the only one left, and it is not blocking 15.5.

**Comment by sharwell** [comment]
Possible duplicate of #19186?

**Comment by jcouv** [comment]
Yes, duplicate. Thanks!
