### ISSUE TITLE
[IOperation] Should we expose Children publicly

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#20803]
We originally implemented `IOperationWithChildren` as a workaround for nodes which did not yet have a corresponding IOperation implementation, so that the OperationWalker could reach them. In order to implement parent pointer support, we're going to be keeping `IOperationWithChildren` around long term. Should we consider making the `Children` publicly accessible as well? FYI @dotnet/analyzer-ioperation @cston @jcouv @AlekseyTs.

**Comment by 333fred** [comment]
https://github.com/dotnet/roslyn/pull/20766#issuecomment-314545460

**Comment by sharwell** [comment]
> implement parent pointer support

Is this simply referring to an `IOperation.Parent` property? If so, what prevents this from working without `IOperationWithChildren`?

**Comment by CyrusNajmabadi** [comment]
We will likely need this.  We should investigate how this can be provided in an allocation free manner (perhaps with a Struct-Enumerator + 'Slot' mechanism like we have with SyntaxNodes).

**Comment by mavasani** [comment]
@heejaechang I think this is done?

**Comment by heejaechang** [comment]
yes. it is now public.
