### ISSUE TITLE
Goto Definition doesn't work on alias symbols defined via project property pages

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#2080]
1. Create a VB Project
2. Introduce an [Alias -ed User Imported Namespace](https://msdn.microsoft.com/en-us/library/t4ttw1f9.aspx) through the Project Property page
3. Open a file in the project and reference the Alias.
4. Invoke Goto definition on the usage of the alias.

**Actual**: message "cannot navigate to symbol under caret"
**Expected**: Dev12 used to navigate to the target symbol via object browser. But Dev14 switched to using Metadata as source and we don't navigate on Namespace symbols? So, this could be by-design.

**Comment by Pilchie** [comment]
Yes, I'm totally comfortable with this behavior.
