### ISSUE TITLE
Bug: A C# comment with HORIZONTAL ELLIPSIS (U+2026) results in incorrect parse

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#2081]
Compile this:

    // Test.cs
    // Hello … world

Result:

    csc.exe /target:library Test.cs
    Microsoft (R) Visual C# Compiler version 1.0.0.50415
    Copyright (C) Microsoft Corporation. All rights reserved.

    test.cs(3,2): error CS0116: A namespace cannot directly contain members such as fields or methods

Expect:
Compiles with no error.

**Comment by pharring** [comment]
Introduced by commit [#117d8bbb86c3c9b7877fe11b2ea50aea3c53389f] (https://github.com/dotnet/roslyn/commit/117d8bbb86c3c9b7877fe11b2ea50aea3c53389f)
PR #2000

**Comment by pharring** [comment]
I think the problem is that, under Latin1, HORIZONTAL ELLIPSIS maps to \u0085 which counts as a line break character (TextUtilities.IsAnyLineBreakCharacter)

**Comment by pharring** [comment]
The problem here is that the file is saved as ANSI, but we are decoding with Latin1.

**Comment by jaredpar** [comment]
@pharring hmm.  That particular change was made because code page 1252 isn't supported on CoreCLR.  Latin1 seemed like the natural fall back in that case.  Let me see if there is a better encoding to use.

**Comment by mavasani** [comment]
Is #2048 also related to this? That seems like codegen difference in unit test with ... in a string.

**Comment by pharring** [comment]
@mavasani yes, from your description, it appears to be the same root cause.

**Comment by pharring** [comment]
@jaredpar By observation (decoding all bytes in the x00 to xFF range through Encoding.Default), the only non standard chars are in that "Control Set" range, 0x80 to 0x9F.
Here's the table:
0080 -> 20ac
0082 -> 201a
0083 -> 0192
0084 -> 201e
0085 -> 2026
0086 -> 2020
0087 -> 2021
0088 -> 02c6
0089 -> 2030
008a -> 0160
008b -> 2039
008c -> 0152
008e -> 017d
0091 -> 2018
0092 -> 2019
0093 -> 201c
0094 -> 201d
0095 -> 2022
0096 -> 2013
0097 -> 2014
0098 -> 02dc
0099 -> 2122
009a -> 0161
009b -> 203a
009c -> 0153
009e -> 017e
009f -> 0178

I think it should be easy enough to create a "custom" encoding (only the decoder is needed) that does that mapping.
