### ISSUE TITLE
VB: Intellisense falters when typing line that begins with an attribute.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#20837]
**Version Used**: 

Visual Studio Community 2015

**Steps to Reproduce**:

Type the following code:

```vb
<Extension> Public Sub Foo()
```

**Expected Behavior**:

After you've typed `<Extension>` and you start typing "public", Intellisense should pop-up and offer to complete the keywords "Public" then "Sub", the same way it does this when you type the line without using an attribute:

```vb
Public Sub Foo() 'here Intellisense kicks in immediately you type P
```

**Actual Behavior**:

After you've typed `<Extension>` its like Intellisense doesn't know what to do next. You have to type out the entire word `Public` by hand, then when you press space it magically returns and offers keywords like `Sub` for auto-completion. I suspect the Intellisense trigger logic is thrown off by the presense of the `<Extension>` attribute when there's nothing else on the line yet.

**Comment by MarcelDevG** [comment]
I've notiticed the same problem in vs2017 (15.2 (26430.15)) and previous versions.
Also when the attribute is on a line of its own:

```
<Extension>
Public sub Foo()

```
