### ISSUE TITLE
Expression-bodied members code style does not consider destructors

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#20849]
Currently the code style rules for expression-bodied members do not consider the availability of this feature for destructors. Destructors could be treated in a manner similar to constructors for when and how to apply this functionality.

⚠️ Due to the exceedingly rare use and general discouragement from using destructors in new C# code, if this feature is implemented then particular care should be taken to ensure it does not negatively influence performance of the analyzer in code that does not contain destructors.

**Comment by Neme12** [comment]
But it probably shouldn't reuse the same message?

**Comment by CyrusNajmabadi** [comment]
Closing out for lack of feedback.
