### ISSUE TITLE
Allowing fixes to run during project load can lead to breaking projects

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#20845]
![image](https://user-images.githubusercontent.com/4564579/28146337-f4ee860e-672d-11e7-837b-fb861bbf61be.png)

This seems to be due to CPS asynchronously actually loading projects in the background.  SO whne a fix tries to apply it will undo any of the changes that CPS has made in the intervening period.

We need a way to know if CPS is actually done so we can suppress fixes before then.  (Note: we also need some way to let the user know why things are suppressed since it will just seem like the product is broken).

**Comment by CyrusNajmabadi** [comment]
Tagging @Pilchie @sharwell @davkean

**Comment by davkean** [comment]
Yeah, there's other things that don't work as expected either - which is painfully obvious in Roslyn because it takes so long for us to catch up. Find All References, Navigate To, etc.

**Comment by CyrusNajmabadi** [comment]
Definitely.  My primary concern here though is that CodeFixes are mutating operations.  And allowing them to run is actually destructive.  That's definitely in a worse category than FAR/NavTo which are simply queries and only show incomplete results during load.

**Comment by davkean** [comment]
This falls back to the whole flag/handshake thing. During load, we do a quick evaluation and you all "static" sources files. Later down the track, we kick off a design-time build (previously blocking project load in legacy) - that comes in and fills in the details; generated files, references, options, analyzers, etc. We currently set this flag; IWorkspaceProjectContext.LastDesignTimeBuildSucceeded which prevents squiggles and symantec errors, do we need something similar? Or can we reuse this?

**Comment by CyrusNajmabadi** [comment]
Strange.  If we're suppressing diagnostics during this time, then why are code-fixes even having diagnostics to run off of?  Tagging @heejaechang

**Comment by davkean** [comment]
Didn't @sharwell mention something around this?

**Comment by CyrusNajmabadi** [comment]
Sounds familiar.  If we have a bug, we can dupe this against that.  But this def seems bad, so i wanted something tracking this.

**Comment by davkean** [comment]
I think it's because we're conflating, "design-time build failed or hasn't finished" with "failed to build skeleton assembly or an assembly reference is missing"

**Comment by sharwell** [comment]
This is a critical bug if there are cases where the destructive fixes are actually getting applied. I haven't seen this happen so far, but I also haven't tried particularly hard to make it happen.

Assuming the changes are for now just a bug in the presentation and a delay before things work as expected, there are two ways to improve the experience:

1. The diff should show use the Solution given to the fixer as the base for the changes, no the current solution of the workspace. This ensures it is always an accurate reflection of the changes made by the code fix.
2. We should work to find ways to get the fixes to still work during the load. What these are, I'm not quite sure yet.

**Comment by Pilchie** [comment]
Is this the same issue as https://github.com/dotnet/roslyn/issues/16083?

**Comment by sharwell** [comment]
@Pilchie Yes a duplicate
