### ISSUE TITLE
Breaking change in right shift operator after moving from VS2015 to VS2017

### ISSUE THREAD

**Issue by mareklinka** [dotnet/roslyn#20854]
Visual Studio 15.2
One of our solution was recently migrated to VS2017 from VS2015. After migration, one of the projects fails to build.

Offending code:
```
private static byte[] StringToByteArray(string hex)
{
    if (hex.Length % 2 == 1)
        throw new Exception("The binary key cannot have an odd number of digits");

    byte[] arr = new byte[hex.Length >> 1];

    for (int i = 0; i < hex.Length >> 1; ++i)
    {
        arr[i] = (byte)((GetHexVal(hex[i << 1]) << 4) + (GetHexVal(hex[(i << 1) + 1])));
    }

    return arr;
}
```
Error messages:
Error	CS0118	'hex' is a variable but is used like a type
Error	CS0307	The variable 'i' cannot be used with type arguments
Both at the part __i < hex.Length >> 1__

**Expected Behavior**:
The right shift should be evaluated first and the result applied as operand in the comparison

**Actual Behavior**:
Basically, the compiler sees the comparison operator and the first > of the shift operator as a generic type parentheses and tries to construct `i<some type>` out of it, instead of evaluating the bit shift.

Workaround is to put the shift into parens:
```
for (int i = 0; i < (hex.Length >> 1); ++i)
{
    arr[i] = (byte)((GetHexVal(hex[i << 1]) << 4) + (GetHexVal(hex[(i << 1) + 1])));
}
```

Additional compiler output:
```
1>------ Build started: Project: ..., Configuration: Debug x64 ------
1>Build started 13.07.2017 10:15:04.
1>CoreResGen:
1>  No resources are out of date with respect to their source files. Skipping resource generation.
1>GenerateTargetFrameworkMonikerAttribute:
1>Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
1>CoreCompile:
[skipped for brevity]
1>  Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn
1>C:\Git\CAMP\ILIAS-BEL\Source\IliasBel.Data\BelData\BelDataFacade.cs(258,33,258,36): error CS0118: 'hex' is a variable but is used like a type
1>C:\Git\CAMP\ILIAS-BEL\Source\IliasBel.Data\BelData\BelDataFacade.cs(258,29,258,45): error CS0307: The variable 'i' cannot be used with type arguments
1>
1>Build FAILED.
```

**Comment by AdamSpeight2008** [comment]
Have you got the version number of the compiler? 
As I thought this had been fixed #17626

**Comment by mareklinka** [comment]
Ah, that might be the case. The version as reporter by csc.exe is 2.2.0.61624.

I take it version 2.3 should correct this?

(Also, sorry for the duplicate, I did a quick search in the issues but I must have overlooked it).

**Comment by AdamSpeight2008** [comment]
@mareklinka Unfortunately I don't know, but knowing what version will help those that do.

**Comment by mareklinka** [comment]
Alright. I'll try to update the roslyn package and see if this goes away, I'll post my results when I have them.

Cheers!

**Comment by mareklinka** [comment]
After installing the Microsoft.Net.Compilers 2.3 resolved the compilation issue. VS still underlines the code in red, but it compiles successfully. Thanks for the advice!

Closing the issue.
