### ISSUE TITLE
IDE0032 Use Auto Property code fix mangles code in preexisting property with getter

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#20855]
**Version Used**: d15rel 26711.00

**Steps to Reproduce**:

```
git clone https://github.com/microsoft/vs-threading.git
cd vs-threading
git checkout 0404d41776090ad54fd892081dcd1bd2b9165698
cd src
MSBuild /t:restore
.\Microsoft.VisualStudio.Threading.sln
```

1. Once in VS with the solution open, navigate to AsyncQueue.cs.
1. (I had netstandard1.1 selected as the language service context)
1. When the language service fades out the first field in the class (`syncObject`) activate the "Use Auto Property" code fix.

**Expected Behavior**:

No compile errors and no incorrect changes to code.

**Actual Behavior**:

The `SyncRoot` property which exposed the `syncObject` property is badly mangled. It was this:

```csharp
        protected object SyncRoot
        {
            get { return this.syncObject; }
        }
```

And was changed to this (including the comments, invalid syntax, etc.):

```csharp
        protected object SyncRoot {
/* Unmerged change from project 'Microsoft.VisualStudio.Threading(netstandard1.1)'
Before:
            get { return this.syncObject; }
After:
            get { return set; }
*/
 get; private this.SyncRoot; }
```

Note that there are absolutely no `#if` directives anywhere in the file. But this file is in a project that has 3 target frameworks.

**Comment by Pilchie** [comment]
@dpoeschl first report of conflict markers appearing in the wild!

**Comment by Pilchie** [comment]
@dpoeschl does the fix need to know to modify both project simultaneously?
