### ISSUE TITLE
Implement a code style rule to check tuple names

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#20850]
Starting with 15.5, the compiler will no longer enforce tuple element names as a language requirement (#20528, #20838). In order to provide a seamless experience for users developing with tuples, a new code style feature implemented as a build-integrated analyzer should be provided at the same time the language feature is removed.

* Aside from severity, the analyzer behavior should be identical to the compiler behavior prior to 15.5
* The analyzer should ignore cases where the language version is less than 7
* The analyzer should not report diagnostics on tuples which contain one or more named elements, as these cases will continue to be validated by the compiler as part of the language (#20838)

**Comment by CyrusNajmabadi** [comment]
Closing out for lack of feedback.
