### ISSUE TITLE
Collapsed xml doc comment is missing a space

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#20865]
**Version Used**: d15rel 26711.1

**Steps to Reproduce**:

```csharp
        /// <summary>
        /// A flag indicating whether the <see cref="OnCompleted"/> has been invoked.
        /// </summary>
        private bool onCompletedInvoked;
```

**Expected Behavior**:

Collapsed appears like this:

```csharp
        /// <summary> A flag indicating whether the OnCompleted has been invoked.
        private bool onCompletedInvoked;
```

**Actual Behavior**:

Collapsed appears like this:

```csharp
        /// <summary> A flag indicating whether the OnCompletedhas been invoked.
        private bool onCompletedInvoked;
```

![image](https://user-images.githubusercontent.com/3548/28183170-51665f16-67c3-11e7-9ed4-fc6128372637.png)

**Comment by sharwell** [comment]
Heh, we specifically tested the case where we don't want the space, but looks like this was missed.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/20694

**Comment by CyrusNajmabadi** [comment]
Currently looks like:

![image](https://user-images.githubusercontent.com/4564579/28219295-57e49fbc-6870-11e7-9e45-6cfae6383140.png)

**Comment by sharwell** [comment]
Duplicate of #20679.

**Comment by AArnott** [comment]
Thanks
