### ISSUE TITLE
Nuget: *.Features packages still on v2.2 while rest is on v2.3 release

### ISSUE THREAD

**Issue by fabianoliver** [dotnet/roslyn#20866]
Hi,

not sure if intended, but seems like some Roslyn packages on Nuget - the *.Features ones specifically - haven't been updated to v2.3 release versions yet, i.e.

https://www.nuget.org/packages/Microsoft.CodeAnalysis.Features
https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Features
https://www.nuget.org/packages/Microsoft.CodeAnalysis.VisualBasic.Features

while the other ones are on v2.3 already, e.g.
https://www.nuget.org/packages/Microsoft.CodeAnalysis/

In my case, I've run into issues after running a nuget update on my solution, which left me with a mix of 2.2 (*.Features) and 2.3 (everything else) packages causing issues - e.g. MefHostServices looking for/failing to load the wrong versions. Haven't spent much time on it - happy to provide more details if needed, but suppose this is just straightforward due to the version conflicts.

**Comment by Pilchie** [comment]
Tag @shyamnamboodiripad, @jaredpar - weren't those 2.3 packages supposed to be unlisted still?

**Comment by jaredpar** [comment]
The decision we came to was the following:

1. Don't publish RTM packages as unlisted. It creates too much confusion and truthfully doesn't accomplish what we wanted. 
1. Only publish Workspaces down since that is all Net Core required.
1. Once we hit actual VS RTM all of the packages will be published under 2.3.1.

**Comment by Pilchie** [comment]
But this breaks anyone using the 2.2 packages above workspaces if they do an update, since their app won't have binding redirects.

**Comment by jasonmalinowski** [comment]
We've now uploaded the rest of them too.
