### ISSUE TITLE
Calling Formatter.Format with invalid arguments shouldn't throw AggregateException

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#20884]
**Version Used**: Microsoft.CodeAnalysis.CSharp 2.2.0

**Steps to Reproduce**: Call `Microsoft.CodeAnalysis.Formatting.Formatter.Format(node, null);`.

**Expected Behavior**: The call throws `ArgumentNullException`.

**Actual Behavior**: The call throws `AggregateException`, which contains `ArgumentNullException` as `InnerException`.

This might not seem like a significant issue, since no information is lost and since `ArgumentNullException` should never be caught. But it does make diagnosing the issue harder and other exceptions likely behave the same.

**Comment by Pilchie** [comment]
Assigning to myself to track getting #20885 merged.
