### ISSUE TITLE
Editorconfig rule for space before and after curly braces

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#20887]
I want to enforce that if a pair of braces is empty and both braces are on the same line, they must contain a single space.

```c#
// Allows
public void Foo()
{
}

// Disallows
public void Foo() {}
public void Foo()
{}

// Disallows
public void Foo() {  }
public void Foo()
{  }

// Allows
public void Foo() { }
public void Foo()
{ }
```

Thinking about more cases, what I really want is for there to be a single space before and after every opening curly brace, and a single space before every closing curly brace, except at the beginning or end of a line.

```c#
// Allows
public void Foo()
{ // code
}

// Disallows
public void Foo()
{// code
}

// Disallows
public void Foo() {  /* code*/  }

// Disallows
public void Foo()  { }
public void Foo(){ }

// Allows
new { Foo = true }.DoSomething()
```

**Comment by sharwell** [comment]
❓ What about the following?

* `<see cref="Nullable{T}"/>`
* `$"{text}"`

**Comment by jnm2** [comment]
@sharwell Ooh, good one. Exceptions for those, I guess? Any way to simplify?

**Comment by sharwell** [comment]
Right now there's an open issue regarding the design of formatting-related code style diagnostics. Formatting style falls into two categories:

1. Preference: What should the formatter use when adding/generating code or changing code as part of other code fixes?
2. Enforcement: If existing code deviates from the preference, what (if any) notice should be given?

After experiences with StyleCop Analyzers, I'm starting to think it would be preferable for all spacing-related format deviations to get reported with a single diagnostic ID. Successfully doing this would require the ability to selectively disable enforcement for certain classes of spacing violations. For example, it may be possible to have these values for configuring the preference:

| Value | Generated code and manual formatting | Reported by analyzer |
| --- | --- | --- |
| Require | Updated to match | Deviations reported |
| Prefer | Updated to match | No |
| Ignore | Keep existing | No |
| PreferNot | Updated to match | No |
| Prohibit | Updated to match | Deviations reported |

**Comment by Pilchie** [comment]
More related to https://github.com/dotnet/roslyn/issues/7067
