### ISSUE TITLE
Building csc projects breaks due to signing output with public key error

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#20898]
**Version Used**: 
VSUML 26714.1. 

**Steps to Reproduce**:
1. Create a new C# Console Application
2. Build the application. (Can be done through the start debugging green arrow button)

**Expected Behavior**:
Project builds
**Actual Behavior**:
Error	CS7027	Error signing output with public key from file 'StringMissingValue' -- File not found.

**Comment by jaredpar** [comment]
Fixed via #20888
