### ISSUE TITLE
Move Microsoft.NETCore.Compilers to a release package

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#20900]
This should be an "official" release package for CoreCLR as soon as https://github.com/dotnet/roslyn/issues/16717 is completed.

**Comment by jcouv** [comment]
@agocke I noticed that OP is in milestone 15.5, but it is dependent on an issue that is assigned to 15.later.

**Comment by jcouv** [comment]
@agocke @khyperia What's the proper milestone for this work item?

**Comment by jcouv** [comment]
Ping @agocke @khyperia 
What is the status and proper milestone for this issue? Thanks

**Comment by jcouv** [comment]
Moving to 15.6 from discussion with Andy, as there is a known issue with quoted parameters that should be resolved before the package is marked as "release", and that bug is only getting fixed in 15.6.

**Comment by agocke** [comment]
Resolved by #24400
