### ISSUE TITLE
devenv spinning CPU in 15.3 Preview with .NET Core projects loaded

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#20918]
**Version Used**: d15rel 26712.00

**Steps to Reproduce**:

```
git clone https://github.com/microsoft/vs-threading.git
cd vs-threading
git checkout 6dbaa57825a334a9732509fe954fe77f8a0ff8bb
cd src
Microsoft.VisualStudio.Threading.sln
```

I was editing files (specifically, editing `#if DESKTOP` lines in my threading.tests project).

**Expected Behavior**:

Very little CPU usage as I was just editing.

**Actual Behavior**:

1-2 cores are working very hard, regardless of whether I interact with VS or not. I collected an ETL trace for over a minute showing the CPU spin, and during which time I did not interact with VS at all.

Full trace: `\\andarno1\public\dumps\dotnet-roslyn-20918-VSBusy.etl.zip`

Name | Exc % | Exc | Inc % | Inc | Fold
-- | -- | -- | -- | -- | --
stylecop.analyzers!StyleCop.Analyzers.AnalyzerExtensions+<>c__DisplayClass2_0.<RegisterSyntaxTreeActionHonorExclusions>b__0(value class Microsoft.CodeAnalysis.Diagnostics.SyntaxTreeAnalysisContext) | 13.3 | 12,319 | 16.6 | 15,381 | 12,319
clr!? | 7.9 | 7,281 | 92.9 | 86,008 | 1,150
Process32 devenv (3920) Args: | 3.8 | 3,485 | 100.0 | 92,545 | 3,485
microsoft.codeanalysis.csharp.ni!Microsoft.CodeAnalysis.CSharp.OverloadResolution.PerformMemberOverloadResolution[System.__Canon](Microsoft.CodeAnalysis.ArrayBuilder`1>, Microsoft.CodeAnalysis.ArrayBuilder`1, Microsoft.CodeAnalysis.ArrayBuilder`1, Microsoft.CodeAnalysis.CSharp.AnalyzedArguments, Boolean, Boolean, Boolean, System.Collections.Generic.HashSet`1 ByRef, Boolean, Boolean) | 2.0 | 1,834 | 19.5 | 18,078 | 1,815
microsoft.codeanalysis.csharp.ni!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1[Microsoft.CodeAnalysis.CSharp.SyntaxKind].TryExecuteDeclaringReferenceActions(Microsoft.CodeAnalysis.SyntaxReference, Int32, Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState, Boolean, Boolean, Boolean, Boolean, Boolean, System.Threading.CancellationToken) | 1.7 | 1,597 | 31.8 | 29,475 | 1,564
microsoft.codeanalysis.csharp.ni!??Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SingleVariableDesignationSyntax..cctor() | 1.7 | 1,581 | 1.7 | 1,581 | 26
microsoft.codeanalysis.csharp.ni!Binder.BindExpressionInternal | 1.6 | 1,442 | 23.6 | 21,814 | 1,391
microsoft.codeanalysis.csharp.ni!CSharpDiagnosticFilter.Filter | 1.6 | 1,441 | 1.7 | 1,567 | 1,387
microsoft.codeanalysis.ni!Microsoft.CodeAnalysis.SyntaxNode+<DescendantNodesAndTokensIntoTrivia>d__168.MoveNext() | 1.5 | 1,398 | 3.1 | 2,853 | 699
microsoft.codeanalysis.csharp.ni!Binder.BindInvocationExpressionContinued | 1.4 | 1,283 | 1.6 | 1,495 | 1,221
microsoft.codeanalysis.ni!AnalyzerDriver.IsGeneratedOrHiddenCodeLocation | 1.2 | 1,143 | 1.4 | 1,322 | 1,102
microsoft.codeanalysis.csharp.ni!MethodCompiler.CompileMethod | 1.2 | 1,142 | 20.1 | 18,587 | 1,133
microsoft.codeanalysis.csharp.ni!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteSyntaxNodeActions[Microsoft.CodeAnalysis.CSharp.SyntaxKind](System.Collections.Generic.IEnumerable`1, System.Collections.Generic.IDictionary`2>>, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer, Microsoft.CodeAnalysis.ISymbol, Microsoft.CodeAnalysis.SemanticModel, System.Func`2, System.Action`1, System.Func`2, SyntaxNodeAnalyzerStateData) | 1.2 | 1,093 | 22.3 | 20,599 | 1,045
microsoft.codeanalysis.ni!Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers+<GetAnalyzerSyntaxDiagnosticsAsync>d__51.MoveNext() | 1.1 | 1,056 | 7.1 | 6,528 | 1,055
microsoft.codeanalysis.csharp.ni!DocumentationCommentCompiler.DefaultVisit | 1.1 | 1,052 | 1.1 | 1,062 | 1,046
mscorlib.ni!System.Threading.ThreadPoolWorkQueue.Dispatch() | 1.0 | 967 | 18.5 | 17,083 | 934
microsoft.codeanalysis.csharp.ni!SourceAssemblySymbol.ForceComplete | 1.0 | 965 | 1.0 | 965 | 965
microsoft.codeanalysis.csharp!Binder.GetAwaitableExpressionInfo | 1.0 | 948 | 4.3 | 3,991 | 936
microsoft.codeanalysis.csharp.ni!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor+<>c__43`1[Microsoft.CodeAnalysis.CSharp.SyntaxKind].<ExecuteSyntaxNodeAction>b__43_0(System.ValueTuple`2,Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext>) | 1.0 | 927 | 17.0 | 15,707 | 920

**Comment by Pilchie** [comment]
Tagging @mavasani and @sharwell

**Comment by mavasani** [comment]
Investigating

**Comment by mavasani** [comment]
Tagging @heejaechang - stylecop and simplify type name analyzer seems to be taking up bulk of the CPU stacks in devenv.exe. HeeJae, shouldn't 3rd party stylecop analyzers be executed OOP?

**Comment by mavasani** [comment]
I also see large number of threads trying to execute the analyzers. @heejaechang don't we ensure we execute the analyzers sequentially when executed inproc? I am wondering if we are somehow ending up running the analyzers concurrently inproc causing these perf issues.

![image](https://user-images.githubusercontent.com/10605811/28428486-5fd7065c-6d2e-11e7-8b38-347ec7e6c04e.png)

**Comment by Pilchie** [comment]
Also tagging @sharwell, both for his stylecop experience, but also because he made a big win for SimplifyTypeNames in 15.3 for some cases.

**Comment by heejaechang** [comment]
all analyzers run on inproc for open files.

...

are those actually running on multiple threads or just switching between multiple threads? solution crawler runs sequentially, but analyzer driver itself follow concurrent option of AnalyzerOptions which are set to false. (http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.CompilationManager.cs,124)

**Comment by heejaechang** [comment]
> all analyzers run on inproc for open files.

we can move analysis for open files to out of proc if we want to as well, I just didn't since I didn't see any benefit from it (runs frequently, all compilations are already in memory for other features and etc)

moving to OOP won't make CPU cost to be reduced. it will only benefit RAM and GC cost.

**Comment by AArnott** [comment]
> moving to OOP won't make CPU cost to be reduced. it will only benefit RAM and GC cost.

I'm mostly concerned about the seemingly never-ending CPU work. The process it happens in seems irrelevant to whatever is causing the loop, IMO.

**Comment by heejaechang** [comment]
@dotnet/roslyn-analysis  @jinujoseph I think this is an example of why we need the analyzer perf view we talked about with data scientist guys. + why we want to adapt the task center thing VS now provide.

with those, user can notice that "Analyzers" are running, and then see which analyzers are  the expansive ones. and then have a way to disable those analyzers from where they are right at the moment.

...

we can improve each analyzers but there will be always cases where they are expansive. and collectively, they being expansive. either we move analyzers to cloud or we need to give users more control.

**Comment by AArnott** [comment]
Are you sure this is a case of expensive analyzers and not simply a matter of either an endless loop or Roslyn code that suddenly became more expensive?
I haven't changed the version of Stylecop.analyzers I've used in months. Yet this CPU spin issue has shown up quite recently and I suspect it's a regression in recent builds of d15rel.

**Comment by mavasani** [comment]
I have a same feeling as Andrew, I think this is some performance regression in IDE where we are seeing the analyzer execution taking longer or being more aggressive. I will try to see if I can repro this using Andrew's repro steps.

**Comment by sharwell** [comment]
:bulb: @AArnott those stacks suggest you are using a 1.0.x build of StyleCop Analyzers. You should see very different performance behavior for the 1.1.x builds.

**Comment by AArnott** [comment]
For the better, I hope? 
Regardless, I've used 1.0.x for a very long time, so that could not be blamed for this recent regressing behavior.

**Comment by sharwell** [comment]
> For the better, I hope?

Some things are faster, but I think some others may be slower. We haven't done targeted performance work on this yet, but that's partly because with the amount of work we've already done to keep it fast it's rarely showing up as a substantial contributor to build time.

**Comment by mavasani** [comment]
@AArnott do you still see the performance issues on latest builds?

**Comment by AArnott** [comment]
No
