### ISSUE TITLE
We should show a builder during tuple creation

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#20926]
Type the following into a valid location to create a tuple:
```C#
// Capitalization is important, string does not show any completions at all
(String s
```
I'd expect either no intellisense popup after the s, or a name suggestion box. However, I get a full type suggestion intellisense popup, which is not a good experience. FYI @rchande.

**Comment by 333fred** [comment]
@rchande I mean, that's a case right there in your screenshot. Unless there's some other language feature I' missing, types are not valid where your cursor is.

**Comment by rchande** [comment]
@333fred the builder is showing in my screenshot.

**Comment by rchande** [comment]
(It also shows up in the variable declaration below)

**Comment by 333fred** [comment]
I'm not able to repro this scenario, so I'm going to close the bug and reopen if I find a repro.
