### ISSUE TITLE
Cannot use 4.6 reference assemblies on Mac/Linux

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#20932]
Our build uses `<TargetFrameworkRootPath>` to customize the path to the framework reference assemblies. This does not work on Linux / Mac where we have a pure CLI build environment. Instead it produces this error:

``` txt
The reference assemblies for framework ".NETFramework,Version=v4.6"
```

This prevents us from building anything with a net46 TF on Linux / Mac. This should be perfectly supported. It's running the output that should fail.

**Comment by tannergooding** [comment]
https://github.com/dotnet/sdk/issues/826

**Comment by MikhailArkhipov** [comment]
Need this to build https://github.com/microsoft/rtvs on OSX when debugging

**Comment by jaredpar** [comment]
@MikhailArkhipov this bug is just a tracking issue for us. The real bug is dotnet/sdk#826

**Comment by jaredpar** [comment]
@agocke fixed this.
