### ISSUE TITLE
Remove unused variables fix removes too much whitespace

### ISSUE THREAD

**Issue by mgoertz-msft** [dotnet/roslyn#20942]
**Version Used**: 15.3 Preview 4.1

**Steps to Reproduce**:
```
    class Test
    {
        bool TrySomething()
        {
            bool used = true;
            int unused;

            return used;
        }
    }
```
Use lightbulb to remove unused variable.

**Expected Behavior**: Only the line with int unused; gets removed.

**Actual Behavior**: The following blank line is removed as well.

**Comment by CyrusNajmabadi** [comment]
To whoever fixes: sometimes removing this blank line is appropriate.  For example:

```c#
    class Test
    {
        bool TrySomething()
        {
            int unused;

            return true;
        }
    }
```

Here we would want to remove that blank line.
