### ISSUE TITLE
DirectCast(Nothing, StructType) should always throw NullReferenceException

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#2094]
```
Structure S
    Function GetS() As S
        Return DirectCast(Nothing, S)
    End Function
End Structure
```
vbc /t:library /optimize- test.vb

**RESULTS:**
```
  .locals init (valuetype S V_0)
  IL_0000:  nop
  IL_0001:  ldloca.s   V_0
  IL_0003:  initobj    S
  IL_0009:  br.s       IL_000b
  IL_000b:  ldloc.0
  IL_000c:  ret
```

**EXPECTED RESULTS:**
```
  .locals init (valuetype S V_0)
  IL_0000:  ldnull
  IL_0001:  unbox.any  S
  IL_0006:  stloc.0
  IL_000b:  br.s       IL_000e
  IL_000d:  ldloc.0
  IL_000e:  ret
```
(or something similar that uses ldnull/unbox.any instead of initobj)

I was quite surprised when I wrote the code above, tested it (with Debug), and later found that it threw a NullReferenceException when compiled for Release.  It should always throw (to avoid these kinds of surprises).

**Comment by KevinH-MS** [comment]
FYI @AlekseyTs, this was the issue you asked about this afternoon.

**Comment by gafter** [comment]
@ljw1004 @AnthonyDGreen FYI

**Comment by ljw1004** [comment]
In VS2013, I see that the repro *did* used to throw a NullRefException in VS2013. So this looks like a simple regression that is fine to fix.

**Comment by AlekseyTs** [comment]
@KevinH-MS Please verify.

**Comment by KevinH-MS** [comment]
Verified fixed--thanks!

**Comment by gafter** [comment]
@KevinH-MS FYI, in the future please use the label "Verified" to mark an issue as verified.
