### ISSUE TITLE
Find all references on literals should respect partial selection

### ISSUE THREAD

**Issue by GearedToWar** [dotnet/roslyn#20941]
**Version Used**: 15.3.0 Preview 4.1

**Steps to Reproduce**:

1. Use a multi-word string literal in multiple places.
2. Search for part of the literal (say one word)

**Expected Behavior**: References are shown for the part of the literal selected. This allows me to analyze my code better and find more opportunities for refactoring.

**Actual Behavior**: The references shown are for the entire string regardless of the selection.

**Comment by CyrusNajmabadi** [comment]
Non trivial to support.  If anyone wants to take a stab at this, feel free.

**Comment by Pilchie** [comment]
As mentioned elsewhere, Find in Files is a pretty good way of achieving this - this feature is really oriented around the language notion of a literal.

**Comment by CyrusNajmabadi** [comment]
Closing out.  VS already supports a great way for finding `part of the literal`.  Just use the find-in-files feature.
