### ISSUE TITLE
Code fix for missing install System.ValueTuple package no longer seems to work

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/roslyn#20955]
**Version Used**: Visual Studio 2017 version 15.3, build 26717.1.d15rel

**Steps to Reproduce**:
1. Create a new .NET Core console app targeting 1.1
2. Paste the following code
3. Click on the squiggle around the tuple on line 13 (`public (string word1, string word2) Words`)
4.  A dialog that says 'Cannot define a class or member that utilizes tuples because the compiler required type 'System.Runtime.CompilerServices.TupleElementNamesAttribute' cannot be found. Are you missing a reference?' followed by 'Predefined type 'System.ValueTuple`2' is not defined or imported.', followed by a link with code fixes.
5. Click on the 'Show potential fixes'

**Expected Behavior**:
There should be a code fix to add a reference to System.ValueTuples packages

**Actual Behavior**:
I get a code fix to use expression body for properties

**Code**
```csharp
using System;

namespace VsCliConWithNano
{
    class Program
    {
        public string Word1
        {
            get { return "Hello"; }
        }
        public string Word2 { get; }

        public (string word1, string word2) Words
        {
            get
            {
                return (this.Word1, this.Word2);
            }
        }

        Program()
        {
            this.Word2 = "World";
        }

        static void Main(string[] args)
        {
            Program p = new Program();
            Console.WriteLine($"{p.Word1} {p.Word2}!");
        }
    }
}
```

**Comment by Pilchie** [comment]
Do you have the option enabled under Tools\Options\Text Editor\C#\Advanced?

**Comment by gregg-miskelly** [comment]
@Pilchie what is the name of the option I am looking for? I don't see anything obvious.

**Comment by gregg-miskelly** [comment]
Ah, found it. I did not. Is this expected to be off by default?

**Comment by CyrusNajmabadi** [comment]
Yes.  It's expected to be off by default.  This is part of our 'add nuget package' work, and that work causes some extra memory and dll loads, and thus isn't allowed to be on unless we win those same things back elsewhere.

**Comment by gregg-miskelly** [comment]
Got it. Should I just close it then? Or should there be something that tells me I could get a useful code fix if I turned the option on?

**Comment by Pilchie** [comment]
We can just close this one - we're planning on doing some of that winning back and enabling this by default, hopefully in 15.4.
