### ISSUE TITLE
Incorrect "Use of unassigned local variable" for `(x is T y) == false`.

### ISSUE THREAD

**Issue by NightElfik** [dotnet/roslyn#20969]
**Version Used**:
Microsoft Visual Studio Community 2017 
Version 15.2 (26430.16) Release
VisualStudio.15.Release/15.2.0+26430.16
Microsoft .NET Framework
Version 4.6.01586

**Steps to Reproduce**:
This produces "Use of unassigned local variable" but it should not.
```
if ((variable is Type x) == false) {
    return;
}
x.Function();
```

This should be logically equivalent to code above and it works fine.
```
if (!(variable is Type x)) {
    return;
}
x.Function();
```

We like to use `== flase` instead of `!` in our code base for added readability. Unfortunately this does not work with above statement :/ Would it be possible to add it?

Thanks!

**Comment by sharwell** [comment]
> We like to use `== flase` instead of `!` in our code base for added readability.

:memo: Note that for typical C# developers, the use of `== false` implies that the left hand side is the nullable type `bool?` and expressly *not* of type `bool`. For example, the following code would need to use an explicit comparison:

```csharp
void SomeExtension<T>(this List<T> list)
{
  if (list?.Any() != true)
  {
    // The list is null or empty
    return;
  }

  // do something here...
}
```

**Comment by HaloFour** [comment]
As this proposal includes a change to the syntax of the C# language I'd suggest opening it on the [C# Language Repository](https://github.com/dotnet/csharplang/).

**Comment by gafter** [comment]
The C# `!` operator inverts "definitely assigned when true" and "definitely assigned when false". The use of `== false` does not do that. According to the rules of definite assignment, the compiler is correct.

**Comment by CyrusNajmabadi** [comment]
> We like to use == flase instead of ! in our code base for added readability. Unfortunately this does not work with above statement 

@NightElfik Very interesting case.  As Neal points out, this is currently by design as per the C# language, and dotnet/roslyn is for bugs on the C# compiler.

> :/ Would it be possible to add it?

Ah!  Quite possibly.  For us to do that, we'd need a proposal filed over at https://github.com/dotnet/csharplang .   Basically, i think we want a proposal that says that definite assignment should take into account boolean expressions involving == and != when compared to a constant boolean value.

**Comment by NightElfik** [comment]
Thanks @CyrusNajmabadi, I have opened [a new proposal](https://github.com/dotnet/csharplang/issues/801) at dotnet/csharplang.
