### ISSUE TITLE
OOM while navigating around solution

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#20963]
Reported by @lpavel. Dumps are in \\acasey-prime\Dumps\Incoming\lapav.

Note that R# was running.

**Comment by amcasey** [comment]
FYI @mavasani, @Pilchie

**Comment by davkean** [comment]
Which solution?

**Comment by amcasey** [comment]
@davkean, I doubt he's allowed to share it, but I'll leave that to @lpavel.  Not Roslyn, if that's what you mean.

**Comment by lpavel** [comment]
I cannot share the solution, but if you tell me how to give you helpful metrics, I'd be happy to.

**Comment by CyrusNajmabadi** [comment]
Closing out as memory usage concerns are tracked with divisional systems now.
