### ISSUE TITLE
Add field to constructor parameter

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#20977]
*Filed on behalf of a customer.*

The desired experience is to press `Ctrl+.` on a field and add it to an existing constructor's parameter list. 

Today's workaround is to delete any existing constructors and "Generate constructor".

**Comment by Pilchie** [comment]
@CyrusNajmabadi want to tackle this?

**Comment by miloush** [comment]
Was looking for this the other day too. Could work with properties as well.

**Comment by justcla** [comment]
This was originally implemented in HotCommands and is now in [HotRefactorings](https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.HotRefactorings).

There is a CodeRefactoringProvider called [InitializeFieldFromConstructor](https://github.com/justcla/HotRefactorings/blob/master/HotRefactorings/RefactoringProviders/InitializeFieldFromConstructor.cs) that "_Inserts variable as parameter to constructor and initializes it_".

That might be a useful example. The original author was Loren Paulsen (VSTS engineer).

**Comment by chborl** [comment]
The ability to select one or more fields and have them added to the constructor is currently available.  To invoke the refactoring, select one or more fields that you want to have as parameters in the constructor, press Ctrl+. and choose "Add parameters to" or "Add optional parameters to"

![addconstructorparameter](https://user-images.githubusercontent.com/25776963/52675522-f8e54000-2edb-11e9-829b-81e835af5f99.gif)
