### ISSUE TITLE
B08-Add parameter to constructor from callsite

### ISSUE THREAD

**Issue by Tanuja-Kulal** [dotnet/roslyn#20973]
**Steps to Reproduce**:

1. create an instance of object with constructor param of type int in C# application.
2. add null as new param to the same call 
3. press ctrl+ click add parameter to exisiting int constructor.
4. The new param is also added as int.

**Expected Behavior**:
The new param should be of nullable type as it is in VB

**Actual Behavior**:
The new parameter is int and gives error "Argument 1: cannot convert from '<null>' to 'int' "

**Comment by Pilchie** [comment]
@Tanuja-Kulal : Can you supply the sample code you had at the time when you invoked Ctrl+Click?

**Comment by Tanuja-Kulal** [comment]
here is the code sample:
 class Test
    {
        test2 test2 = new test2(null,1);
    }

    public class test2
    {
        private int v;

        public test2(int v)
        {
            this.v = v;
        }
    }

I added the 1st parameter v also by Ctrl+

**Comment by Pilchie** [comment]
(updated sample code to use markdown)
