### ISSUE TITLE
BasicExpressionEvaluator.EvaluatePrimitiveValues failed with COMException

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#20979]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_vs-integration_prtest/6531/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicExpressionEvaluator/EvaluatePrimitiveValues/

```
Stacktrace

MESSAGE:
System.Runtime.InteropServices.COMException : Operation not supported. Unknown error: 0x8971003c.
+++++++++++++++++++
STACK TRACE:
Server stack trace: at EnvDTE.Debugger.StepOver(Boolean WaitForBreakOrEnd) at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Debugger_InProc.StepOver(Boolean waitForBreakOrEnd) at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs) at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg) Exception rethrown at [0]: at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type) at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Debugger_InProc.StepOver(Boolean waitForBreakOrEnd) at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.Debugger_OutOfProc.StepOver(Boolean waitForBreakOrEnd) at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicExpressionEvaluator.Dispose(Boolean disposing) in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicExpressionEvaluator.cs:line 149 at Roslyn.VisualStudio.IntegrationTests.AbstractIntegrationTest.Dispose() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\AbstractIntegrationTest.cs:line 30 at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
```

**Comment by dpoeschl** [comment]
FYI @ivanbasov It looks like you re-enabled this last week but now it's failed again.

**Comment by ivanbasov** [comment]
Yes, there were crashes on Dispose method. We decided that the method is not necessary for the current test configuration, and I removed it. There were no crashes during the test execution the last week or before.

**Comment by dpoeschl** [comment]
This is still happening. https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_vs-integration_prtest/6618/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicExpressionEvaluator/EvaluatePrimitiveValues/

@ivanbasov What should we do? I'm tempted to disable things again.

**Comment by dpoeschl** [comment]
Now just a crash in the same test: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_vs-integration_prtest/6631/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicExpressionEvaluator/EvaluatePrimitiveValues/

**Comment by dpoeschl** [comment]
And another crash in `EvaluateInvalidExpressions` again.

**Comment by dpoeschl** [comment]
More! https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/6741/

**Comment by dpoeschl** [comment]
These tests are now disabled.
