### ISSUE TITLE
Duplicate "case" when doing if->switch conversion

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#20981]
From https://github.com/dotnet/csharplang/issues/754 (@joeloff)

When you have an OR expression and one of the subexpression repeat in an else-if, you get a duplicate case generated when converting from an if to a switch in Visual Studio using the quick refactoring option, e.g.

if ((x==2) || (x==3))
else if (x==3)

The generated switch you get will be something like

switch (x)
{
case 2:
case 3:
break;
case 3:
break;
}

the "else" is effectively dead code

**Comment by Pilchie** [comment]
In the other report, discussion eventually centered on VS doing a better job of detecting code that is unreachable in cases like this.  This relates to https://github.com/dotnet/roslyn/issues/6970, except that it indicates places where we could/should do more analysis than the compiler.

**Comment by CyrusNajmabadi** [comment]
The feature is working well afaict.  It accurately reflects the issue with the user's original code.  And after changing to that code, you get useful compiler diagnostics alerting you to your logic issues.  I don't think we need to do anything here.
