### ISSUE TITLE
Feature Request: Add-null-check should offer to add null checks for all parameters in a signature.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#20986]
Ported from https://devdiv.visualstudio.com/DevDiv/_workitems/edit/466784 / https://developercommunity.visualstudio.com/content/problem/82252/add-null-check-for-all-parameters-of-function-opti.html

**Comment by stcahlon** [comment]
Design Plan: we currently have an option to add a null check for a single parameter.  We're looking to add an option that adds null checks for all parameters.

Question:
In case there are several parameters and some of them are strings. Any strong thoughts about what should be the default check for a string? Options include: 
1. is null
2. is null or empty
3. is null or whitespace
