### ISSUE TITLE
BasicLineCommit.CommitOnSave flaky test run failure

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#20991]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_vs-integration_prtest/6476/artifact/Binaries/Release/UnitTests/VisualStudioIntegrationTests/xUnitResults/Roslyn.VisualStudio.IntegrationTests.dll.out.log

```
Assert.Contains() Failure
      Not found: Sub Main(x As Integer)
      In value:  Module Module1
          Sub Main(x   As   Integer)
          End Sub
      End Module
```

**Comment by dpoeschl** [comment]
And again https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_vs-integration_prtest/6469/

**Comment by dpoeschl** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/6813/

**Comment by tmat** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/7013/

**Comment by tmat** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/8516/

**Comment by chborl** [comment]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_vs-integration/1863/

**Comment by mavasani** [comment]
Another failure: https://ci.dot.net/job/dotnet_roslyn/job/features_dataflow/job/windows_debug_vs-integration_prtest/22/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicLineCommit/CommitOnSave/

**Comment by 333fred** [comment]
Failed again: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x/job/windows_release_vs-integration/113/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicLineCommit/CommitOnSave/

**Comment by 333fred** [comment]
We've been seeing this quite a bit. @jasonmalinowski, please prioritize.

**Comment by 333fred** [comment]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x/job/windows_debug_vs-integration/139/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicLineCommit/CommitOnSave/

**Comment by jasonmalinowski** [comment]
Old bug, will reactivate with new failure info.
