### ISSUE TITLE
Add compiler support for ISupportInitialize during object initializer execution

### ISSUE THREAD

**Issue by kzu** [dotnet/roslyn#2100]
Quite often, it’s necessary to validate an object state when it’s initialized. With constructor arguments, this is easy to do as it can be done at the end or beginning of the constructor code. With object initializers, it’s nearly impossible, as there’s no way to know programmatically when the object initialization is finished.

There’s a built-in mechanism for this that is being used in WinForms and WPF: the ISupportInitialize interface. The initialization code generated by both toolkits checks to determine if the object implements the interface. If it does, it will call BeginInit() before invoking all property setters, and EndInit() at the end. This provides a nice hook for validating all properties and maybe interrelated ones.

Adding this to the IL generated by the compiler for object initializers would make them immensely more useful. I’d be willing to replace many ctor overloads with properties if I had that hook, given the much more readable code that results from using object initializers.

No new syntax is necessary at all, it should just work, just like it does already (via design time code gen) in WPF/WinForms.

**Comment by kzu** [comment]
Would be nice if together with this, the initializer could set private properties when the interface is provided?

**Comment by gafter** [comment]
@kzu Are you assuming in this request that initialization is finished at the end of the object initializer? That is, once that is done you're not allowed to initialize anything else in the object?

**Comment by kzu** [comment]
@gafter that would be up to the implementer of the interface. 

Usually (in WPF and WinForms, that is) the interface is used to suspend all validation and event raising, etc., during initialization, to speed up the process. Then, on the EndInit, all validation and events are applied/raised. But that doesn't mean you can't continue setting additional properties afterwards.

But again, that's the implementer's choice (to throw on setter after isInitialized is true).

**Comment by gafter** [comment]
@kzu Let me reword my question. If the assumption of the language feature that `EndInit` must be called after the initializers appearing in the object initializer expression?

**Comment by HaloFour** [comment]
```cs
var foo = new Foo() {
    X = 1,
    Y = 2,
    Z = 3
};
```

equates to:

```cs
Foo foo = new Foo();
foo.BeginInit();
foo.X = 1;
foo.Y = 2;
foo.Z = 3;
foo.EndInit();
```

Of course that represents different behavior and could be considered a breaking change.

**Comment by taspeotis** [comment]
Do we need to worry about calls to `BeginInit` not being paired with their call to `EndInit`? E.g.

```csharp
Foo foo = new Foo();
foo.BeginInit();
foo.X = 1;
foo.Y = 2; // throws exception
foo.Z = 3;
foo.EndInit();
````

You'd need `try { ... } finally { foo.EndInit(); }` or a variation on that theme:

```csharp
var foo = new Foo();

using (foo.BeginInit()) {
  foo.X = 1;
  foo.Y = 2;
  foo.Z = 3;

  foo.EndInit();
}
```

(That is, the BeginInit method may return something that implements IDisposable).

Also, is there any merit to keeping the validation *outside* of the object. E.g.

```csharp
[SupportInitializeType(typeof(FooInitializationValidator))]
public class Foo { ...
```

**Comment by HaloFour** [comment]
@taspeotis

I don't know, I would argue that an exception that occurs during initialization would mean that the initialization hadn't completed and `EndInit` shouldn't be called.  The designer-generated code doesn't attempt to wrap initialization in `try`/`catch` blocks.

Also, as `ISupportInitialize.BeginInit` returns `void` the `IDisposable` concern is kind of moot.

Then again, since this entire proposal was put into the "probably never" bucket in the C# 7.0 work list it's all probably kind of moot.  :smile:

**Comment by gafter** [comment]
Per #2136, we do not believe this is something we'd ever do. Keeping it open for discussion for now, though.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
