### ISSUE TITLE
Test crash in or before CSharpAddMissingReference.InvokeSomeFixesInCSharpThenVerifyReferences

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21002]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_vs-integration_prtest/6585/artifact/Binaries/Debug/UnitTests/VisualStudioIntegrationTests/xUnitResults/Roslyn.VisualStudio.IntegrationTests.dll.out.log

**Comment by Pilchie** [comment]
Can you take a look?

**Comment by CyrusNajmabadi** [comment]
Dump is missing.  There isn't enough information to do anything here.

**Comment by dpoeschl** [comment]
And it might have been fixed by Ravi's change.

**Comment by JoeRobich** [comment]
Saw this again. [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=121983&view=ms.vss-test-web.build-test-results-tab)

```
System.Exception : Marker 'y.goo' not found in text: using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication1
{
 class Program
 {
 static void Main(string[] args)
 {
 }
 }
}
```

**Comment by JoeRobich** [comment]
Sorry. realize this was for a crash not a test failure. will open a separate issue.
