### ISSUE TITLE
Test VS crash in BasicGoToDefinition.ObjectBrowserNavigation or BasicGenerateTypeDialog.BasicToCSharp, followed by lots of test failures

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21009]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_vs-integration_prtest/6590/artifact/Binaries/Debug/UnitTests/VisualStudioIntegrationTests/xUnitResults/Roslyn.VisualStudio.IntegrationTests.dll.out.log

```
System.Runtime.Remoting.RemotingException : Failed to read from an IPC Port: The pipe has been ended.
```

and then lots of "regular" looking failures, but suspiciously a lot of them.

**Comment by dpoeschl** [comment]
(A couple more examples linked in https://github.com/dotnet/roslyn/issues/20675)

**Comment by Pilchie** [comment]
Can you see if this is a lease timeout, or a real crash)?

**Comment by dpoeschl** [comment]
Likely fixed by https://github.com/dotnet/roslyn/pull/20956

**Comment by dpoeschl** [comment]
Happened again. Reopening. https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/6567/

**Comment by dpoeschl** [comment]
And similarly: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_vs-integration_prtest/6703/

**Comment by dpoeschl** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/6663/artifact/Binaries/Release/Dumps/

**Comment by rchande** [comment]
The dump from 6663 isn't very useful, only has native code of the xunit main thread.

**Comment by genlu** [comment]
This seems to be another instance of this
https://ci.dot.net/job/dotnet_roslyn/job/features_ioperation/job/windows_release_vs-integration_prtest/374/#showFailuresLink

**Comment by CyrusNajmabadi** [comment]
Closing out given hte age and rewrite of integration tests.
