### ISSUE TITLE
Improve Generate Default Constructor by adjusting cursor placement after invocation

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#21008]
When a default constructor is generated, we currently place the cursor at the end of the closing brace:

![image](https://user-images.githubusercontent.com/1402694/28434935-0d6ce450-6d46-11e7-9587-48468211e75d.png)

It makes more sense to leave the cursor in the parameter list so that a user can add parameters:

![image](https://user-images.githubusercontent.com/1402694/28434943-196fd19a-6d46-11e7-8841-ce9a23add90c.png)

Same issue happens when you generate a default constructor from the type declaration:
![image](https://user-images.githubusercontent.com/1402694/28435199-f24f1386-6d46-11e7-99fd-34737c9a7237.png)

It leaves the cursor in the type name:
![image](https://user-images.githubusercontent.com/1402694/28435222-0298df88-6d47-11e7-8d6e-115b6f22ba60.png)

**Comment by zarenner** [comment]
It would additionally be nice if hitting tab (either immediately, or after typing parameters) moved the cursor to the body of the constructor.

**Comment by CyrusNajmabadi** [comment]
> Same issue happens when you generate a default constructor from the type declaration:

I don't agree that we should navigate you to the constructor in this case.  For example, you may want to do something like add a base-type/interface and then implement it.  If we moved you then you'd have to navigate back to the type to handle those case.

**Comment by zarenner** [comment]
I see your point, but it'd be really nice (as I do today with ReSharper's behavior) to be able to create a constructor, then add parameters and introduce fields for them without any manual cursor movement whatsoever.

Personally I find this to be a much more common scenario than the one you describe, which if I understand correctly is creating the constructor and then doing a somewhat unrelated quick action from the type declaration.

Perhaps there's a compromise solution, e.g. hitting tab after constructor generation moves the cursor first to the parameter list, then body.

**Comment by CyrusNajmabadi** [comment]
> Perhaps there's a compromise solution, e.g. hitting tab after constructor generation moves the cursor first to the parameter list, then body.

Sure.  I'd be up for someone implementing this.  If you're interested i'm making this issue up-for-grabs.

**Comment by zarenner** [comment]
> I don't see them as unrelated. I will commonly create a type, generate a constructor from it's header, and then add base-types/interfaces and implement those.

Presumably you come back to the constructor later then and work on it? Or are you creating an empty default constructor to change constructor visibility from the base?

> Sure. I'd be up for someone implementing this. If you're interested i'm making this issue up-for-grabs.

Cool. Don't have time myself right now but may grab it in the future if it doesn't get picked up.

**Comment by miloush** [comment]
Note there is also the `.ctor` snippet. Snippets generally use the tab key to move cursor around, and you could create one that fits your needs.
