### ISSUE TITLE
Test crash in or before CSharpGenerateTypeDialog.CSharpToBasic (could also be CSharpGenerateFromUsage.GenerateLocal)

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21003]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_vs-integration_prtest/6493/artifact/Binaries/Release/UnitTests/VisualStudioIntegrationTests/xUnitResults/Roslyn.VisualStudio.IntegrationTests.dll.out.log

**Comment by Pilchie** [comment]
Please investigate.

**Comment by dpoeschl** [comment]
Likely fixed by #20956, will reopen if it recurs.

**Comment by dpoeschl** [comment]
Again in https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_vs-integration_prtest/6557/
