### ISSUE TITLE
Code action for running/debugging test methods

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#21018]
/cc @davkean filed as requested.

**Comment by sharwell** [comment]
Can you describe the difference between this request and the following menu items?

![image](https://user-images.githubusercontent.com/1408396/28443383-43077726-6d7b-11e7-91db-d1ad1671fa33.png)

**Comment by alrz** [comment]
I think it runs *all* tests. Is that possible to run/debug a single test method/class?

**Comment by Pilchie** [comment]
Those commands run the tests that match the selection IIRC (the current method if you're in a method, current class if you're in a class between methods, etc.

**Comment by alrz** [comment]
>Those commands run the tests that match the selection

Good to know.. that doesn't seem to be very discoverable though! Would be nice if it appears as a lightbulb-like icon next to each method. I will try it as soon as I'm done fighting VS installer and get a successful build.

**Comment by Pilchie** [comment]
@alrz - you should enable Live Unit Testing in VS Enterprise :)

I don't think we're doing to do anything more here right now, but also tagging @ManishJayaswal to see this.

**Comment by alrz** [comment]
LUT is not what I'm asking for. I want to see test results (not test coverage) in the code and the ability to run/debug using a code action. I think this is just lacking in VS and the only reason I'm personally forced to switch to other tools.

**Comment by Pilchie** [comment]
And the CodeLens test indicator doesn't show this for you?

**Comment by alrz** [comment]
Ah didn't know CodeLens show this. I have community edition.

**Comment by ManishJayaswal** [comment]
Yes code lens test indicators show the status of tests covering that method and you can also run/debug tests from there. You can also do this from LUT icons as which also show test pass/fail status in addition to code coverage.

**Comment by alrz** [comment]
@ManishJayaswal 

For your consideration, I'd rather have a code action just for test cases and not use those alternatives. LUT and CodeLens both affect the whole project with information that I don't care (like references count etc). I just want a convenient way to work with my tests. That's all.
