### ISSUE TITLE
Update Analyzer with Code Fix template

### ISSUE THREAD

**Issue by livarcocc** [dotnet/roslyn#21012]
_From @Pzixel on July 18, 2017 9:16_

I'm playing with Roslyn and wanted to create my first analyzer. It works fine, however, when I try to update NuGet packages in analyzer project I get an error because analyzer is supporting .net4.5 only while `Microsoft.CodeAnalysis.Common` 2.* doesn't. When I tried to migrate project manually to .net4.6 or .netstandard I encountered with several problems because I don't understand all switches and custom project sections in generated project and I only get multiple errors, and when I fix ones others comes. Here is #44 and #510 that are helpful in implementing it and it's a step in the same direction. I think that new `Update Analyzer with Code Fix` template must be a .netstandard project referencing packages 2.*. 

P.S. If here is a workaround how to perform such a transformation manually after project got generated it would be really helpful.

_Copied from original issue: dotnet/sdk#1424_

**Comment by livarcocc** [comment]
@tmat @jinujoseph what is the right repo for this issue?

**Comment by livarcocc** [comment]
_From @jinujoseph on July 20, 2017 21:16_

should be under https://github.com/dotnet/roslyn 
cc/ @jmarolf

**Comment by Rohansi** [comment]
Is there any template people can download in the meantime? The csproj and other info [here](https://github.com/dotnet/roslyn/issues/18414#issuecomment-292028741) are good but what about debugging etc?

**Comment by jmarolf** [comment]
fixed
