### ISSUE TITLE
F2 is no longer shortcut to "Rename"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#21025]
**Version Used**: 
Version 15.4.0 Preview 1.0 [26710.3002.d15prerel]

**Steps to Reproduce**:
Looks like F2 is no longer assigned to "Rename" instead it's CTRL+R, CTRL+R. Is this by design?

![image](https://user-images.githubusercontent.com/1103906/28447275-21162ce6-6e13-11e7-87c5-06aa15045a23.png)

**Comment by monoman** [comment]
For a long time now, and I miss it too...
To make things more confusing F2 is still used for renaming files in the solution explorer, AFAIK.

**Comment by davkean** [comment]
I blew away my hive, did this change my settings @CyrusNajmabadi @Pilchie?

**Comment by olegtk** [comment]
It's Ctrl+R Ctrl+R by default (for example in General profile), but should still be F2 (and also Ctrl+R Ctrl+R) in C# profile.

**Comment by davkean** [comment]
What caused me to switch to the General profile? The fact that I blew away my hive?

**Comment by davkean** [comment]
Look at the general profile - there's nothing else assigned to F2 for the editor - why wouldn't have it assigned to rename?

**Comment by olegtk** [comment]
Good question, I don't know why, probably years ago somebody on the C# team decided F2 is a good shortcut for rename and assigned it, but only for C# because VB and C++ already use F2 for something else. Please file a bug, F2 seems unassigned in Text Editor scope in General profile.

**Comment by Pilchie** [comment]
`F2` used to be something else (Object Browser) for VB profile at least?  @DustinCampbell do you remember?

**Comment by DustinCampbell** [comment]
Yes, <kbd>F2</kbd> is for Object Browser in the VB profile (mimicking the behavior in VB 6) and maps to Rename in the C# profile. In the General profile, it's <kbd>Ctrl+R, Ctrl+R</kbd> as it has been for 10+ years.

**Comment by davkean** [comment]
Why did I get switched to the general profile?

**Comment by DustinCampbell** [comment]
No idea. Any bug related to that would be a platform issue.
