### ISSUE TITLE
[C# Feature Request] Static extension methods

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#2103]
*(I expected to see this already requested, but could not find it - apologies if it's a duplicate)*

http://stackoverflow.com/questions/249222/can-i-add-extension-methods-to-an-existing-static-class

Example (from SO):
```csharp
Console.WriteBlueLine("This text is blue");
```

```csharp
public static class Helpers
{
    public static void WriteBlueLine(this Console c, string text)
    {
        Console.ForegroundColor = ConsoleColor.Blue;
        Console.WriteLine(text);
        Console.ResetColor();
    }
}
```

As far as I understand F# already supports it, which kind of proves it is possible and might be useful:

http://codebetter.com/matthewpodwysocki/2008/09/10/object-oriented-f-extension-everything

> Are there any downsides?  Well, at the moment, when we create these extensions to our given classes in F#, they are only available to F#.  That means you cannot access these from C#, VB or any other language at the moment.  That cuts a little bit into the value proposition, but I think still very valuable to the language at this point. 

http://stackoverflow.com/questions/671420/static-extension-methods-on-seq-module

**Comment by Joe4evr** [comment]
Dupe of #996 much?

**Comment by dsaf** [comment]
Yes, thanks.
