### ISSUE TITLE
Suggestion: Have option for intellisense to display method parameters on new lines for readability

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#21036]
**Version Used**:  current

**Steps to Reproduce**:

1.  In code window, hover on a method to view the intellisense window showing the method and all of it's parameter and type info.

**Actual Behavior**:
Currently, intellisense displays the method in one long line, with wrapping at the end of a long line, if needed.

```c#
SyntaxNode SyntaxGenerator.GetAccessorDeclaration([Accessibility accessibility = Accessibility.NotApplicable], [IEnumerable<SyntaxNode> statements = null], ..... etc ...
``` 

**Expected Behavior**:
It would be nice to have an option to display the method with each parameter on a new line.  For example,

```c#
SyntaxNode SyntaxGenerator.GetAccessorDeclaration(
    [Accessibility accessibility = Accessibility.NotApplicable],
    [IEnumerable<SyntaxNode> statements = null]
    ..... etc .....
```

**Comment by Pilchie** [comment]
Related to https://github.com/dotnet/roslyn/issues/5.

I think there is an issue here with our use of classified quick info.  The editor supports some APIs for better wrapping, but I don't think we do in Roslyn.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
