### ISSUE TITLE
Rename Tracking should be able to discern between programmatic edits and user typing

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21044]
1. Paste C#
```C#
static uint foo() => 0;
```

2. Invoke the Naming Violation fixer to change `foo` to `Foo`

**Expected**: Rename Tracking understands that this was a programmatic edit and does not show the dotted border or provide a lightbulb suggestion to rename from `foo` to `Foo`
**Actual**: Rename Tracking sees a text edit from `foo` to `Foo` without knowing what caused the edit, so it assumes somebody typed over the the `f` with an `F`, and offers to finish the symbol rename.

**Note** - This only happens when the symbol renamed only has one location in the document. If multiple locations are updated, Rename Tracking knows to ignore the changes.

**Comment by dpoeschl** [comment]
This is a longstanding bug that was known but I can't find anything to dupe it against. Using this for tracking.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
