### ISSUE TITLE
Out declaration missing type in autocompletion list

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#21055]
**Version Used**: 2.3.0.61907

**Steps to Reproduce**:
```C#
class Program
{
    static void Main(string[] args)
    {
        if (TryParse("", out|

        Program p = null;
    }

    static bool TryParse(string s, out Program p) { }
}
```
(automatic brace insertion disabled)

Try type `if (TryParse("", out Program`...

**Expected Behavior**: `Program` be in the autocompletion list. (I would even welcome if it was preselected.)

**Actual Behavior**: It's not there at all and the list is in completion mode, so you end up with `if (TryParse("", out InvalidProgramException ` without much thinking.

**Comment by Pilchie** [comment]
This is a parsing fault tolerance issue, and doesn't repro without the variable declaration on the next line, which is being consumed as part of the `out var`.

Ah declaration expressions and their ambiguities in partially typed code.

@CyrusNajmabadi any ideas here?

**Comment by CyrusNajmabadi** [comment]
Even if this code gets parsed as an out-declaration-expression, we should still offer proper symbol completion here.  It looks like we handle the out-argument case, but didn't update to handle the out-declaration-expression case.  It should be cheap to add support for that case.

Note to whoever implements this: we also need to support this for all predefined types (int, string, etc.).

**Comment by miloush** [comment]
Note that this seems to work for predefined types.

**Comment by Neme12** [comment]
I don't know what to do here... The compiler doesn't show Program as a class at all in LookupSymbols.
