### ISSUE TITLE
Compiler-generated expression trees do not respect overridden members

### ISSUE THREAD

**Issue by 6A** [dotnet/roslyn#21059]
**Version Used**:  
`Microsoft.CodeAnalysis 2.2.0`

**Steps to Reproduce**:  
1. Create a class `Base`, and define a virtual property `Value`.
2. Create another class `Override` that inherits `Base`, and overrides `Value`.
3. Use a method that requires the compiler to generate a LINQ `Expression` tree.

```csharp
class Base
{
    protected virtual int Value => 0;
}

class Override : Base
{
    protected override int Value => 1;
}

MemberExpression GetExpressionBody(Expression<Func<int>> expression)
{
    return expression.Body as MemberExpression;
}

Base baseObj = new Base();
Override overrideObj = new Override();

Assert.NotEqual(
    GetExpressionBody(() => baseObj.Value).Member,
    GetExpressionBody(() => overrideObj.Value).Member
); // throws
```

**Expected Behavior**:  
The produced `MemberExpression` has a `Member` that references `Override.Value`.

**Actual Behavior**:  
The produced `MemberExpression` has a `Member` that references `Base.Value`.

**Notes**:  
I suspect the [`ExpressionLambdaRewriter.VisitPropertyAccess`](https://github.com/dotnet/roslyn/blob/6969b516a24b460e269b1ae2be09d8c4cd220c27/src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs#L987-L1010) method is causing this issue, by calling [`PropertySymbolExtensions.GetOwnOrInheritedGetMethod`](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Compilers/CSharp/Portable/Symbols/PropertySymbolExtensions.cs#L15-L29). However, it looks like `GetOwnOrInheritedGetMethod` works correctly, which means that... the bug is produced earlier, whilst creating the semantic model.

**Comment by sharwell** [comment]
My guess is this is not a bug in the C# compiler, since the described behavior for expression trees matches the compiler's behavior for other cases as well. For example, the equivalent code produces exactly the same result:

```csharp
Base baseObj = new Base();
Override overrideObj = new Override();

Assert.NotEqual(baseObj.Value, overrideObj.Value);
```

Produces IL like this:

```
IL_0001: newobj instance void Base::.ctor()
IL_0006: stloc.0
IL_0007: newobj instance void Override::.ctor()
IL_000c: stloc.1
IL_000d: ldloc.0
IL_000e: callvirt instance int32 Base::get_Value()
IL_0013: ldloc.1
IL_0014: callvirt instance int32 Base::get_Value()
IL_0019: call void Assert::NotEqual(int32, int32)
```

**Comment by 6A** [comment]
Thanks for your answer.

Oh, and if I remember correctly, the runtime takes care of redirecting `Base::get_Value()` to `Override::get_Value()` with `callvirt`. That's thus normal behavior.

It still poses a problem in this specific situation though, doesn't it?

**Comment by sharwell** [comment]
@6A I'm not sure what the recommended approach would be regarding your situation. I left this open hoping the compilers team can provide more specific feedback for you. 😄

**Comment by gafter** [comment]
I'm not sure why you consider this a bug. According to the C# language specification*, this is an invocation of the base's property, and we produce an expression tree accordingly.

More specifically, this is a *feature* of name lookup in C#. [Name lookup is used to select a *member* of the type on the left-hand-side of the member access operator named on the right-hand-side of that operator.](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#member-access)

> [The members of a class consist of the members introduced by its *class_member_declarations* and the members inherited from the direct base class.](https://github.com/dotnet/csharplang/blob/master/spec/classes.md#class-members)

But an override declaration does not _introduce_ a member in the sense meant by that rule.

> [Except for differences in declaration and invocation syntax, virtual, sealed, override, and abstract accessors behave exactly like virtual, sealed, override and abstract methods.](https://github.com/dotnet/csharplang/blob/master/spec/classes.md#virtual-sealed-override-and-abstract-property-accessors) Specifically, the rules described in Virtual methods, [Override methods](https://github.com/dotnet/csharplang/blob/master/spec/classes.md#override-methods), Sealed methods, and Abstract methods apply as if accessors were methods of a corresponding form...

> [When an instance method declaration includes an `override` modifier, the method is said to be an **override method**. An override method overrides an inherited virtual method with the same signature. Whereas a virtual method declaration introduces a new method, an override method declaration specializes an existing inherited virtual method by providing a new implementation of that method.](https://github.com/dotnet/csharplang/blob/master/spec/classes.md#override-methods)
