### ISSUE TITLE
IDE analyzer experience broken for Roslyn.sln

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#21050]
Pull request #20990 moved the project to the 2.6.0.0 compiler tool chain, including analyzers, prior to the public availability of a build of Visual Studio which supports them. It should be reverted for a proper developer experience, and then merged after a preview of release 15.5 is published.

**Comment by mavasani** [comment]
Note that #20990 was forced to move the compiler toolset forward as the roslyn master was already moved to analyzers version 2.5, which depend on the 2.6 toolset. I think we should temporarily move both the toolset and analyzers back to the 2.3 versions.

@jinujoseph This would also mean we cannot merge features/ioperation into master until we are ready to move master forward to 2.6.
