### ISSUE TITLE
Keyword completion for Recommender.GetRecommendedSymbolsAtPosition

### ISSUE THREAD

**Issue by jbe2277** [dotnet/roslyn#2105]
Please provide keyword completion for C# and VB when using the public API Recommender.GetRecommendedSymbolsAtPosition.

We use GetRecommendedSymbolsAtPosition to provide auto-completion for our "Script" editor. This works really great and it helps much writing script code. If this method would provide the recommended keywords as well then the auto-completion would be nearly perfect :-).

You might have a look at http://dotnetpad.codeplex.com to see how we use Roslyn. I have created this open-source project to evaluate Roslyn.

**Comment by DustinCampbell** [comment]
This has been on our backlog for awhile now. I've been hoping to get to it for a long time.

**Comment by DustinCampbell** [comment]
Hey @jbe2277, we're working on a more fully fleshed-out completion list API that would essentially provide all of the completion items that we show in Visual Studio. Would that be more useful to you than an API that returned keywords? We're tracking the completion API here: https://github.com/dotnet/roslyn/issues/3538.

**Comment by jbe2277** [comment]
Hi @DustinCampbell, this sounds great. Yes, that would be more useful than my request here.

**Comment by DustinCampbell** [comment]
Cool! I'll close this one and we can focus on getting a better general completion list API. Thanks!
