### ISSUE TITLE
Roslyn Code Analyzer - SyntaxKind.ArrowExpressionClause Not Triggered during Unit Test

### ISSUE THREAD

**Issue by Chrisgozd** [dotnet/roslyn#21062]
I'm trying to write a code analyzer using Roslyn, and its going great except for trying to find nodes using SyntaxKind.ArrowExpressionClause when unit testing.  When running the analyzer on a Visual Studio instance, it triggers the breakpoint fine.

This is the basics of my code:

        public override void Initialize(AnalysisContext context)
        {
            var kinds = new[]
            {
                SyntaxKind.ArrowExpressionClause
            };
            context.RegisterSyntaxNodeAction(AnalyzeNode, kinds);
        }

        private static void AnalyzeNode(SyntaxNodeAnalysisContext context)
        {
            var node = context.Node;
        }

This is the code I am trying to trigger the analyzer on:

    using System;

    namespace TestRoslynConsoleApp
    {
        class Program
        {
            object foo2 { get => 5; }

            static void Main(string[] args)
           {
            
           }
       }
    }

Unit Test:

            var test = @"
                    using System;

                    namespace TestRoslynConsoleApp
                    {
                        class Program
                        {
                            object foo2 { get => 5; }

                            static void Main(string[] args)
                           {
            
                           }
                       }
                    }
                ";

            var expected = new DiagnosticResult
            {
                Id = "BoxingAnalyzer",
                Message = Resources.BoxingAnalyzerDescription,
                Severity = DiagnosticSeverity.Warning,
                Locations =
                    new[] {
                            new DiagnosticResultLocation("Test0.cs", 15, 41)
                        }
            };

            VerifyCSharpDiagnostic(test, expected);

If I set a breakpoint on "var node = context.Node;" it triggers fine when running an instance of Visual Studio and creating a program with the above code, but when Unit Testing and debugging on "var node = context.Node;", the breakpoint is not hit.

**Comment by sharwell** [comment]
What version of Roslyn are you testing against? Testing against a version that doesn't understand expression-bodied accessors would cause this. I would recommend updating your tests to always fail if a compiler error is reported. It's saved StyleCop Analyzers from all sorts of expected test failures.

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/commit/746e551b8e7ba1e78b20c30acd003f6846980081

**Comment by Chrisgozd** [comment]
That fixed it. Thanks.
