### ISSUE TITLE
Visual Studio crashes when C# project depends on F# which depends on C# project with FxCop analyzers 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#21061]
Ported from https://github.com/dotnet/roslyn-analyzers/issues/1271

----------------------------------------------------------------------------

#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers  2.3.0-beta1

#### Repro steps

Open solution in Visual Studio 2017 Update 3 Preview 4 : [CrashProblemSimpleSolution.zip](https://github.com/dotnet/roslyn-analyzers/files/1170383/CrashProblemSimpleSolution.zip)

Or:
In Visual Studio 2017 Update 3 Preview 4
 1) Create .NET Core C# project, add FxCop nuget and Feature IOperation
 2) Create .NET Core F# project, add it to solution make it dependent on previous C# project
 3) Create .NET Core C# project, add FxCop nuget and Feature IOperation and make it dependent on previous C# project

#### Expected behavior
no problem

#### Actual behavior
Visual Studio will crash, this is what debugging shows:
Exception thrown at 0x74BCDBE8 in devenv.exe: Microsoft C++ exception: EEException at memory location 0x23EFE56C.
Exception thrown at 0x74BCDBE8 (KernelBase.dll) in devenv.exe: 0xE0434352 (parameters: 0x80004003, 0x00000000, 0x00000000, 0x00000000, 0x72E70000).
'devenv.exe' (Win32): Loaded 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll'. Cannot find or open the PDB file.
CLR: Managed code called FailFast, saying "System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.CreateEmptyCompilation()
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<BuildDeclarationCompilationFromScratchAsync>d__29.MoveNext()"

**Comment by mavasani** [comment]
Tagging @michalkovy

**Comment by Pilchie** [comment]
@jasonmalinowski just fixed this:
https://github.com/dotnet/roslyn/pull/21023

https://github.com/dotnet/roslyn/pull/21035
