### ISSUE TITLE
During async loading, we shoudl assume the compiler version is the 'latest' not the 'default'.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#21070]
_From @CyrusNajmabadi on July 17, 2017 18:3_

During async solution loading CPS doesn't know what version of the compiler to create.  So CPS (or Roslyn, not sure) decides to just create a compiler with the 'default' version.  This leads to unpleasant errors being shown during load like:

![image](https://user-images.githubusercontent.com/4564579/28282479-6ccb709c-6adf-11e7-947b-36e8d782bae7.png)

These errors go away once the project context is finally determined.  But this may take many minutes and the experience is poor.

instead of picking 'default' we should pick 'latest' to have the least amount of errors reported during this time.

_Copied from original issue: dotnet/project-system#2621_

**Comment by srivatsn** [comment]
This would be in Roslyn. The project system doesn't interpret the options - it simply sends the commandline to roslyn. Before the commandline is sent, I assume, getting a compilation would use whatever is the default LangVersion

**Comment by sharwell** [comment]
@heejaechang Wouldn't this count as a semantic error that should be suppressed prior to the project fully loading?

**Comment by CyrusNajmabadi** [comment]
@sharwell Right now this is a syntactic error.  The parser detects and reports that you're using an unsupported feature.  We could move this to be a semantic error (which would have additional benefits) as well.

**Comment by CyrusNajmabadi** [comment]
This no longer applies.
