### ISSUE TITLE
CodeClass2.Parts always empty

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#21074]
From: https://developercommunity.visualstudio.com/content/problem/64170/codeclass2parts-always-empty.html

**Version Used**: 
15.3 Preview 1

**Steps to Reproduce**:

1. When using DTE CodeClass2.Parts used to return all parts of a partial class. In this 2017 preview version it always returns empty.

**Comment by jasonmalinowski** [comment]
Given @carlos-quintero pointed out this was working and re-regressed in #31988 I'm guessing this can be safely closed.

**Comment by carlos-quintero** [comment]
I confirm the bug is fixed in VS 2019 Preview 2
