### ISSUE TITLE
Operator nameof is incorrectly highlighted in red

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#21071]
_From @arespr on July 14, 2017 10:16_

**Version Used**: 
Visual Studio 14.0.25431.01 Update 3
			Visual Strudio 15.2 (26430.15)
**Steps to Reproduce**:
![obraz](https://user-images.githubusercontent.com/3482384/28208380-a18ff63a-688d-11e7-8f73-85859a83b2be.png)

**Code:**:

```csharp
enum EnumExample
{
	Value1
}
public void DoSomething(Action action)
{
}

public void NameOfOperatorError()
{
	var tmp1 = nameof(EnumExample.Value1);
	
	DoSomething(() =>
	{
		var tmp2 = nameof(EnumExample.Value1);

		int a = 3;
		int b = 3;
		
		var c =

	});
}
```

Edited by @sharwell: Fixed formatting of code block

_Copied from original issue: dotnet/project-system#2613_

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  Looks fine here:

![image](https://user-images.githubusercontent.com/4564579/198749199-b80a7231-2a8f-4f7f-9f31-8cdf0ad48ad8.png)
