### ISSUE TITLE
Remove Unused Variable does not consider other targets/heads

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21085]
**Version Used**: 26717.1.d15rel

**Steps to Reproduce**:

1. Create a linked file between two projects with the following content:

```C#
            int x = 7;

#if LIB3
            Console.WriteLine(5);
#else
            Console.WriteLine(x);
#endif
```

2. Give one of the projects a compilation symbol of "LIB3"

**Expected Behavior**: In both project contexts, we don't offer to remove `x` because it is in use

**Actual Behavior**: We offer to remove it if it's not being used in the active context

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
