### ISSUE TITLE
Generate Overrides allows member ordering in the UI but doesn't obey the chosen ordering

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21081]
**Version Used**: 26717.1.d15rel

**Steps to Reproduce**:

1. Paste C#

```C#
    public class B
    {
        internal virtual void M1() { }
    }

    public class D : B
    {

    }
```

2. Ctrl+. on `D`, and choose "Generate overrides..."
3. Pick M1 and GetHashCode, but move GetHashCode below M1

**Expected Behavior**: GetHashCode appears below M1 (or reordering is not possible)

**Actual Behavior**: GetHashCode appears above M1

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
