### ISSUE TITLE
Asp.net WebApi add one item in nested child list when list is set to null in json

### ISSUE THREAD

**Issue by MuhammadNasirKhanYousafzai** [dotnet/roslyn#21098]
I have  the following json Object which i am sending to Web Api controller Using ajax.

   ```
 var dataObject = {
                        LanguageId: 1,
                        SubTenantId: 1,
                        Object:{"TestApplication":{"Aplication":null}} 
                    }
```

Controller function accepts `RequestObject<T>` a generic class.

     `public IHttpActionResult ComplexObject(RequestObject<TestApplicationMain> pubRequestObject)`
        
I am using following Class hierarchy.  
 

  ```
    public class TestApplicationMain
    {
        public TestApplicationMain()
        {
            TestApplication = new TestApplication();
        }
     public TestApplication TestApplication{get; set;}
       
    }

    public class TestApplication
    {
        public TestApplication()
        {
            Aplication = new List<ApplicationSearchParam>();
        }
        public List<ApplicationSearchParam> Aplication { get; set; }
      
    }


public class ApplicationSearchParam
    {
        public ApplicationSearch ApplicationSearch { get; set; }
        public string OrderBy { get; set; }
    }
```

When i send `{"TestApplication":{"Aplication":null}}` json to the controller. I receive One item in `Aplication `List instead of null.All attribute of Application item are set to default values.

Api controller works as expected when i send    `{"TestApplication":{"Aplication":undefined}}` OR  `{"TestApplication":{"Aplication":[]}}` and set `Appliation `to `null`.

**My Question is Why Asp.net WebApi Controller add one item in nested child list when its set to null ?**.

**Comment by Pilchie** [comment]
Roslyn is not the right repo for this - maybe try https://github.com/aspnet/mvc
