### ISSUE TITLE
Suggestion to use pattern matching breaks compilation

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#21097]
**Version Used**: 
```
Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.14) Release
VisualStudio.15.Release/15.2.0+26430.14
Microsoft .NET Framework
Version 4.7.02053
```

**Steps to Reproduce**:

Paste the following code into VS2017:
```cs
public class C
{
  public void M(object o)
  {
    var s = o as string;
    if (s != null)
    {

    }
    else
    {
      if (o is int?)
        s = null;
      s.ToString();
    }
  }
}
```

**Expected Behavior**:
No suggestion to use pattern matching

**Actual Behavior**:
Roslyn suggests to change the code into following:

```cs
public class C
{
  public void M(object o)
  {
    if (o is string s)
    {

    }
    else
    {
      if (o is int?)
        s = null;
      s.ToString(); // Error CS0165: Use of unassigned local variable 's'
    }
  }
}
```
which doesn't compile

I think that the problem is the way [`CSharpAsAndNullCheckDiagnosticAnalyzer`](https://github.com/dotnet/roslyn/blob/6847f1e5a909395aae9456e8f366cbf4deb86b69/src/Features/CSharp/Portable/UsePatternMatching/CSharpAsAndNullCheckDiagnosticAnalyzer.cs) checks definite assignment for suggested code

```cs
        private void CheckDefiniteAssignment(
            SemanticModel semanticModel, ISymbol localVariable, SyntaxNode node,
            out bool isAssigned, out bool isAccessedBeforeAssignment,
            CancellationToken cancellationToken)
        {
            if (node != null)
            {
                foreach (var id in node.DescendantNodes().OfType<IdentifierNameSyntax>())
                {
                    var symbol = semanticModel.GetSymbolInfo(id, cancellationToken).GetAnySymbol();
                    if (localVariable.Equals(symbol))
                    {
                        isAssigned = id.IsOnlyWrittenTo();
                        isAccessedBeforeAssignment = !isAssigned;
                        return;
                    }
                }
            }
 
            isAssigned = false;
            isAccessedBeforeAssignment = false;
        }
```

it looks like this method just checks the first reference for an analyzed variable (which is `s = null` under `if` in the example above) and doesn't check that it will actually initialize the variable. If I remove the `s = null;` line the suggestion disappears.

**Comment by alrz** [comment]
@CyrusNajmabadi This is the issue I've mentioned here: https://github.com/dotnet/roslyn/pull/19907#discussion_r124460246

**Comment by CyrusNajmabadi** [comment]
@alrz Is this addressed by your change?  Or do we still need to do more work here?

**Comment by alrz** [comment]
@CyrusNajmabadi No, my changes were on top of the existing def assignment checking.
