### ISSUE TITLE
csi.rsp includes System.ValueTuple reference

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#21096]
**Version Used**: 2.3.1.61919 (57c81319)

which is problematic on platforms which cannot use bundled System.ValueTuple.dll or you run on .NET 4.7 (or newer) and you need to reference 3rd party assembly which was compiled to target .NET 4.7 and has System.ValueTuple typeref from mscorlib.

**Comment by jcouv** [comment]
@marek-safar Could you describe the repro and the symptoms you observe? Thanks

FYI @tmat @jinujoseph for interactive.

**Comment by marek-safar** [comment]
Yes #21156 is another symptom of hardcoded System.ValueTuple.dll reference

**Comment by jcouv** [comment]
From discussion with @tmat, the problem with #21156 is that the Interactive window in the IDE displays squiggles, despite the script compiling correctly when submitted. The fix will be for the IDE to pass the proper flag to the compiler (prefer ValueTuple type from mscorlib).

The plan is to leave the ValueTuple.dll reference in csi.rsp. So I will close by-design. 
If there is a scenario that is broken, please describe it and re-open. Thanks!

**Comment by marek-safar** [comment]
@tmat @jcouv What proper flag we need to pass to prefer ValueTuple from mscorlib? We need to update msbuild task to do that and also our csi script wrapper

**Comment by jcouv** [comment]
On a C# compilation, do `comp = comp.WithOptions(comp.Options.WithTopLevelBinderFlags(BinderFlags.IgnoreCorLibraryDuplicatedTypes));`.
This API is internal though (it is IVT to EE and scripting, or can be called via reflection). From last discussion with @tmat we're hoping to remove it long-term (ie. we prefer not making it public).

If you are calling the scripting API, it should take care of this already. Are you implementing your own scripting?

For msbuild task, could you clarify the scenario? What compiler API is that task calling?

Also, looking at the PR (https://github.com/dotnet/roslyn/pull/17192) I see that we sort the assembly references to put mscorlib last. Not sure if you'll need something similar.

**Comment by marek-safar** [comment]
@jcouv it's in roslyn codebase, see https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Csi.cs. It invokes csi.exe but how do we make that work with duplicate ValueTuple type?

**Comment by jcouv** [comment]
The Csi task relies on csi.exe which is implemented with `CSharpScriptCompiler`. I see that `CSharpScriptCompiler` already [properly sets](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Scripting/CSharpScriptCompiler.cs,68) this binder flag.

Can you describe the scenario that is broken for you? Thanks

**Comment by marek-safar** [comment]
We run this in scenario where we don't reference System.ValueTuple then simple type access yields

```
> var mmm = typeof(System.ValueTuple);
(1,1): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
(1,18): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

but this looks like Mono issue not csi issue as it works on .net
