### ISSUE TITLE
Hierarchical indentation option for SCSS files does not work

### ISSUE THREAD

**Issue by NoelAbrahams** [dotnet/roslyn#21099]
**Version Used**:  Visual Studio Community 2017 15.3.0 Preview (3)

**Steps to Reproduce**:
1. Go to Tools > Options > Text Editor > SCSS > Advanced.
2. Set "Hierarchical indendation" to "On".
3. **Exit Visual Studio and launch it again** (i.e. restart VS).
4. Add a new `.scss` file and enter the following:
```css
.foo {
    margin: 0;
}

.foo > .bar {
    margin: 0;
}
```
5. Hit Control+K, Control+D (format document)

**Expected Behavior**:
The selector `.foo > .bar` should be indented, since it is further down the hierarchy to `.foo`.

**Actual Behavior**:
There is no indentation.

Strangely, if you now go to Tools > Options and just view the SCSS > Advanced option and exit via "cancel", the indentation starts working again.

Not sure if this is the right place to post this issue. Please advise correct repo if not.

Thanks.

**Comment by Pilchie** [comment]
@toddgrun @madskristensen - is Send Feedback the best way to report this?

**Comment by madskristensen** [comment]
Yes, Send Feedback would be great

**Comment by NoelAbrahams** [comment]
Lovely, didn't think of that (actually didn't realise "Report a problem" had progressed since VS 2008!).

I've [reported the problem](https://developercommunity.visualstudio.com/content/problem/85108/hierarchical-indentation-option-for-scss-files-doe.html). 

Thanks.
