### ISSUE TITLE
ef583af428 CSharpCodeAnalysis.csproj Release doesn't build

### ISSUE THREAD

**Issue by codespare** [dotnet/roslyn#211]
Looks like some refactoring in Symbols\Synthesized\SynthesizedLocal.cs only got applied #ifdef Debug.

**Comment by theoy** [comment]
@JaredPar - was this by chance resolved by your commit dc16ac23ef3d190f959422f0a34632996f3a96ec ?

**Comment by codespare** [comment]
Yes it is.
Minor glitch using f69ac51b77 that misses .\Src\VisualStudio\ErrorList\ErrorListDiagnosticsPackage\ErrorListDiagnostics.csproj but that's transient I guess. Also, it could be there is an /allowUnsafe+ lying in a .rsp or a build environment somewhere but that's not in git, in the Mixed Platforms configuration of Scripting.csproj, that CS0227 in the checked out version.
Very nice to see all the additions you have been releasing over the past few days, and very curious to see where this is leading, trying to figure out what it takes to get Microsoft.VisualStudio.VsInteractiveWindow.vsix to somehow run in vs2013, keep it coming :)
