### ISSUE TITLE
Convert if to switch loses certain trivia

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#21101]
Convert ```if (/* t0 */args.Length /* t1*/ == /* t2 */ 2) return /* t3 */ 0 /* t4 */; /* t5 */ else /* t6 */ return /* t7 */ 3 /* t8 */;```

The comments "t0", "t2," and "t6" disappear.
```C#
            switch (args.Length /* t1*/ )
            {
                case 2:
                    return /* t3 */ 0 /* t4 */; /* t5 */
                default:
                    return /* t7 */ 3 /* t8 */;
            }
```

**Comment by CyrusNajmabadi** [comment]
This does not seem like a real bug.  This seems like something created by synthetically testing.

**Comment by CyrusNajmabadi** [comment]
I'm going to fix /* t0 */ as there's at least some reasonable syntax in the converted code ot map the original code to.  I do not care about t2 or t6.
