### ISSUE TITLE
[suggestion] Convert if to switch should be available for else if, etc

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#21100]
Paste the following into a method in C#.
```
            if (args.Length == 0)
            {

            }
            else if (args.Length == 1)
            {

            }
```

"Convert if to switch" is only available on "if", but it might make sense to offer it on "else" as well.

**Comment by CyrusNajmabadi** [comment]
Closing out as not getting any feedback about issues here.  We can always revise the spans we show based on information from users.  We don't need tracking issues to just indicate tehre may be more places we could consider.
