### ISSUE TITLE
Update "Add Parameter to Constructor" to allow adding multiple parameters at once

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21113]
If I realize I need to pass a bunch of services through a few layers and start at the top, adding arguments to constructor invocations as I go, then I need to invoke Add Parameter to Constructor once per new parameter per level. It would be nice if I could just do all of the new parameters at once.

**Comment by Pilchie** [comment]
See also https://github.com/dotnet/roslyn/issues/20986 and https://github.com/dotnet/roslyn/issues/21114, which mention the possibility of adding a Method level scope for Fix-All.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
