### ISSUE TITLE
Add Parameter to Constructor doesn't generate unique names w.r.t. locals defined in the constructor

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21112]
**Version Used**: 26717.1.d15rel

**Steps to Reproduce**:

1. Paste C#:

```C#
    public C()
    {
        int x = 7;
        Console.WriteLine(x);
    }

    void M()
    {
        int x = 4;
        new $$C(x);
    }
```

2. Invoke "Add Parameter to Constructor" at the $$

**Expected Behavior**: A parameter name other than `x` is chosen, avoiding an error in the updated code

**Actual Behavior**: The new parameter is named `x`, introducing an error in the updated code

**Comment by dpoeschl** [comment]
This will probably never ever be a real problem.

**Comment by miloush** [comment]
I would argue it is more likely you actually want the parameter to be named `x`, with the intention to use it inside the constructor rather than declaring it there.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
