### ISSUE TITLE
"Add Null Checks for Parameter" should let me do multiple parameters at once

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21114]
Today you have to do one at a time (though it's nice you don't have to do them in order 👍)

**Comment by dpoeschl** [comment]
This is probably a dupe of something, but we did also find it during testing.

**Comment by AdamSpeight2008** [comment]
`Update All on Method` or `Update All in project / solution`?

**Comment by dpoeschl** [comment]
Yeah, I've been thinking we might need a "Fix All in Method" (or member or whatever) after filing a bunch of similar issues recently where it seems that would be useful. @pilchie @jinujoseph I don't know the history of the discussion around fix all scopes. Is this something we would entertain?

**Comment by Pilchie** [comment]
It seems reasonable to me.  Also tagging @DustinCampbell and @kuhlenh

**Comment by DustinCampbell** [comment]
Yup. I'm in favor of Fix All in Member

**Comment by jinujoseph** [comment]
makes sense to me . also tagging @mavasani

**Comment by alrz** [comment]
https://github.com/dotnet/roslyn/issues/20986

**Comment by Pilchie** [comment]
Duplicate of #20986
