### ISSUE TITLE
Roslyn setup packages are still shipping parts of System.Composition

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#21119]
The Roslyn packages are currently shipping some of the System.Composition.* assemblies that VS previously wasn't shipping, since we needed more than what VS shipped. This puts it in a really strange state where we're shipping slightly different versions than what VS is shipping, and it's a confusing mess. We should stop shipping those binaries and just ship all of VS MEF wherever that setup package is.

**Comment by Pilchie** [comment]
Isn't this a duplicate of https://github.com/dotnet/roslyn/issues/20620 ?

**Comment by jasonmalinowski** [comment]
Oh hey, it is. :smile:
