### ISSUE TITLE
Short-circuit OR and AND

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#21137]
On the latest version of the source code (master) the following classes are using the or/and operators without the short-circuit evaluation and it is not always clear whether this was the intent.

- [Binder_Await.cs](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Binder/Binder_Await.cs#L30) lines 30 and 31.
- [Binder_Operators.cs](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs#L1675) lines 1675 to 1693.
- [MethodTypeInference.cs](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs#L2539) line 2539.
- [AbstractOverrideCompletionProvider.cs](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/Completion/Providers/AbstractOverrideCompletionProvider.cs#L46) line 46.

**Comment by mikedn** [comment]
What exactly is unclear about 2nd and 3rd examples?

**Comment by Evangelink** [comment]
@mikedn Well this is not so common pattern to use this syntax and so except if there is some comment (or special variable/method name) clearly stating this is wanted it is hard to tell if this is a mistake or not.  And if you think all is crystal clear for you then you can close the ticket.

**Comment by mikedn** [comment]
> clearly stating this is wanted it is hard to tell if this is a mistake or not

It's impossible for something like `f1 | f2` to be a mistake. It makes no difference if it's `f1 | f2` or `f1 || f2`. In the case of `valueLeft.BooleanValue & valueRight.BooleanValue` the intention is clear from context - constant folding of a `&` expression.

The only place where things are really dubious is Binder_Await. Personally I prefer to write that kind of code like:
```C#
bool b = foo();
b |= bar();
b |= koo();
```

> And if you think all is crystal clear for you then you can close the ticket.

Why do people assume that if they get a response to an issue in open source project the response comes from project owners? :smile:

**Comment by Evangelink** [comment]
@mikedn You are right I have assumed you were part of the team but that doesn't change the fact that if some owner reads this and thinks the same way as you they can close it without asking anything :)

And regarding code portions that can't be mistakes, you would be surprised by how often small mistakes can happen in code base (especially large ones).

**Comment by benknoble** [comment]
I think there is a potential for a mistake (though one that likely would have been caught by now). Consider something like (contrived)
```c-sharp
string s = foo();
if (s != null & s.Equals(someOtherS)) {
    bar();
}
```
Since `&` doesn't short-circuit, `Equals` will get called on a null reference in the case that `s == null`.

**Comment by gafter** [comment]
I could not find anything problematic with any of the questioned lines of code.

**Comment by Evangelink** [comment]
Hi @gafter. May I just ask why you guys think this is better to force the evaluation of both sides of the expression rather than to benefit from the short-circuiting behavior?

**Comment by gafter** [comment]
Sure you can ask. Which one are you asking about?
