### ISSUE TITLE
ContainsChildrenGraphQuery.GetGraphicAsync crashes due to invalid characters in path

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#21134]
This is from this community item: https://developercommunity.visualstudio.com/content/problem/76525/creating-a-nuget-package-from-uwp-library-using-th.html and it is likely a .NET Core project.

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetExtension(String path)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Progression.ContainsChildrenGraphQuery.<GetGraphAsync>d__0.MoveNext()
```

**Comment by davkean** [comment]
That feedback item - contains two separate crashes for this.

**Comment by Pilchie** [comment]
Appears to be [here](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Progression/GraphQueries/ContainsChildrenGraphQuery.cs,59)

**Comment by dpoeschl** [comment]
Customer reports that they are no longer encountering the problem.  https://developercommunity.visualstudio.com/content/problem/76525/creating-a-nuget-package-from-uwp-library-using-th.html

**Comment by davkean** [comment]
While I gathered the crashes from that bug - that bug is not related to above.

**Comment by jasonmalinowski** [comment]
Hmm, it appears internal dumps were expired, and I could _swear_ there was a dump somewhere else but can't find it now. Oh well.
