### ISSUE TITLE
issue with VB parent pointer

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#21142]
VB has 2 pending issue on implementing parent pointer.

1) PlaceHolder bound node are shared multiple times in Bound Tree. making 1:1 BoundNode to IOperation not work. we need to decide what to do with PlaceHolder node in IOperation tree. right now, it gets cloned.

2) some bound node, (node -> bound node) exist, but it is skipped when its parent creates its children. basically they disappear from IOperation tree. but direct conversion of (bound node -> IOperation) exist. so user can have multiple IOperation tree based on what node they give to SemanticModel.GetOperation

**Comment by tmat** [comment]
@heejaechang What's the status?

**Comment by heejaechang** [comment]
addressed by https://github.com/dotnet/roslyn/pull/21857

**Comment by jinujoseph** [comment]
@heejaechang  good to close this ?

**Comment by heejaechang** [comment]
yes. I think cloning issue is tracked by other issue.
