### ISSUE TITLE
VS integration test dumps sometimes go to an obscure folder

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21157]
They sometimes land in e.g. https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/6763/artifact/Binaries/Debug/UnitTests/VisualStudioIntegrationTests/xUnitResults/Dumps/ instead of https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/6763/artifact/Binaries/Debug/Dumps/

**Comment by jaredpar** [comment]
Should be fixed no;w.
