### ISSUE TITLE
C# Interactive: The type 'ValueTuple' exists in both 'mscorlib' and 'System.ValueTuple'

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/roslyn#21156]
**Version Used**: 
VS 2017.3 Preview 4+ (26723.0 d15rel)
OS 10.0.16251.0 (rs_prerelease)
**Steps to Reproduce**:

1. Open VS
2. View -> Other Windows -> C# Interactive to open C# Interactive Window
3. Type: ValueTuple.Create() and wait for the error to report

**Expected Behavior**:
There should be no live errors and the code executes after pressing ENTER.

**Actual Behavior**:
There is a live compilation error even the above code can be successfully committed and executed.

Error message: The type 'System.ValueTuple' exists in both assembly 'System.ValueTuple, v4.0.1.0' and 'mscorlib, v4.0.0.0'.

Looks like the System.ValueTuple.dll is by default imported even with .NET Framework 4.7 on Windows 10 (it should not be referenced by default if on Windows 10 with net47.)

**Comment by pdelvo** [comment]
As far as I know this should be fixed: https://github.com/dotnet/announcements/issues/25

**Comment by jcouv** [comment]
![image](https://user-images.githubusercontent.com/12466233/29936891-961a2520-8e38-11e7-90bd-a3e24e9025cc.png)

**Comment by jcouv** [comment]
Fixed by #21851 as part of 15.5

**Comment by mazhou-msft** [comment]
Confirm it is now working good.
