### ISSUE TITLE
Feature request: .editorconfig supports commas at end of certain members

### ISSUE THREAD

**Issue by heaths** [dotnet/roslyn#21151]
To reduce the complexity of diffs (and merges with said diffs), we prefer developers use commas after the last member of enums, and object and collection initializers like so:

```csharp
enum ExampleEnum
{
  Foo,
  Bar,
}

new ExampleClass
{
  Foo = 1,
  Bar = "str",
}

new[]
{
  "foo",
  "bar",
}
```

It would be great if _.editorconfig_ supported commas in these cases, as mere suggestions, required, or forbidden as with other rules.

**Comment by Pilchie** [comment]
Nice suggestion!  Also tagging @kuhlenh and adding it to our backlog.

**Comment by sharwell** [comment]
:memo: An implementation of this style rule is currently available in StyleCop Analyzers.

**Comment by heaths** [comment]
@sharwell looks like a good start. Ideally, we'd like this for enumeration declaration and collection initializers as well. Would you accept a PR for the analyzers to add these as well? I could probably muster some time to implement them.

**Comment by heaths** [comment]
@sharwell I see from the code it works for object, array, and collection initializers. Does that apply to enumeration declarations as well?

**Comment by sharwell** [comment]
@heaths As of DotNetAnalyzers/StyleCopAnalyzers#2239 it does :smile:

**Comment by CyrusNajmabadi** [comment]
Closing as external.  StyleCop handles this.
