### ISSUE TITLE
ServiceHubRemoteHostClient+WorkspaceHost.OnSolutionAdded hang loading Roslyn.sln

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#21166]
**Version Used**: 15.3 Preview 6

The synchronous wait [on this line](https://github.com/dotnet/roslyn/blob/876ffdddce48edd3e7bba355171a16809e22f8e0/src/VisualStudio/Core/Next/Remote/ServiceHubRemoteHostClient.WorkspaceHost.cs#L62) is causing a 1.4 second hang on the UI thread while Visual Studio is opening. This call should be updated to asynchronously invoke the operation, triggered by the OnSolutionAdded event but not waiting for it to completed before returning from the event handler.

**Comment by CyrusNajmabadi** [comment]
This method doesn't exist anymore and we don't have any current traces showing a problem here.  Closing out.
