### ISSUE TITLE
Generate method into closed file hangs (but is cancellable)

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21179]
Saw this failure in an integration test earlier today and thought it to be infrastructure, but I just tried it out and it hangs on 26717.1.d15rel for me. The method is still generated when you cancel. Trying more recent 15.3 bits now and debugging.

**Comment by dpoeschl** [comment]
FYI @Pilchie

**Comment by Pilchie** [comment]
@dpoeschl is currently investigating this.

**Comment by AbhitejJohn** [comment]
On an internal build of VS2019, this isn't cancel-able as well.
/cc: @dpoeschl

**Comment by dpoeschl** [comment]
@jinujoseph I'm not entirely sure what changed, but we can't repro the lack of cancellability on Abhitej's machine anymore.

**Comment by jinujoseph** [comment]
Thanks @dpoeschl for validating.
@AbhitejJohn moving this issue to 16.1 , feel free to ping us if you see the issue again.

**Comment by CyrusNajmabadi** [comment]
Have gotten no reports of this, and i don't see anything in prism related to this.  Given that tehre is no callstack here, and no reports.  I'm going to close out as unactionable.
