### ISSUE TITLE
Suggest IDE0019 throws error CS8202

### ISSUE THREAD

**Issue by huchim** [dotnet/roslyn#21172]
**Version Used**: 
Microsoft Visual Studio Community 2017 Preview (2)
VisualStudio.15.Preview/**15.3.0**-pre.6.0+26724.1
Microsoft .NET Framework
Versión 4.6.01055

**Steps to Reproduce**:

1. Use this code:

```csharp
// TableAttribute is from EntityFramework.
if (type.GetTypeInfo().GetCustomAttributes(typeof(TableAttribute), false).SingleOrDefault() is dynamic tableAttr)
{
    name = tableAttr.Name;
}
```

2. Apply sugestion `IDE0019`.
3.  Compile

**Expected Behavior**:

It works in Microsoft Visual Studio Community 2017 **15.2.0** (+26430.14), but doesn't compile in Visual Studio Community 2017 Preview **15.3.0** (-pre.6.0+26724.1).

**Actual Behavior**:

It doesn't compile but I can change the code without problems.

```csharp
var tableAttr = type
    .GetTypeInfo()
    .GetCustomAttributes(false)
    .SingleOrDefault(attr => attr.GetType().Name == nameof(TableAttribute)) as dynamic;
```

**Comment by CyrusNajmabadi** [comment]
@huchim Can you supply a full repro for this?  I can't repro what you're talkign about with your specific code sample.

**Comment by CyrusNajmabadi** [comment]
Specifically IDE0019 should be offered when teh code looks more like:

```c#
var x = e as T;
if (x != null) F(x);
```

It shouldn't really be offered in code that already has an "is" pattern in it.

**Comment by huchim** [comment]
```csharp
namespace ConsoleApp1
{
    using System;
    using System.Linq;
    using System.Reflection;

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!" + GetTableName(typeof(EntityExample)));
            Console.ReadLine();
        }

        static string GetTableName(Type type)
        {
            var tableAttr = type
                .GetTypeInfo()
                .GetCustomAttributes(false)
                .SingleOrDefault(attr => attr.GetType().Name == nameof(TableAttribute)) as dynamic;
            
            if (tableAttr != null)
            {
                return tableAttr.Name;
            }

            throw new Exception("Table name not found!");
        }
    }
    
    class TableAttribute : Attribute
    {
        public TableAttribute(string tableName)
        {
            this.Name = tableName;
        }

        public string Name { get; set; }
    }

    [Table("Example")]
    class EntityExample
    {
    }
}
```

**Comment by huchim** [comment]
This is message in Visual Studio 2017 (15.2 and 15.3 Preview)

![imagen](https://user-images.githubusercontent.com/5809549/28688773-ab107770-72d8-11e7-9e61-6431c6c333dc.png)

**Comment by CyrusNajmabadi** [comment]
Thanks!  Working on fix now.
