### ISSUE TITLE
Expand 'generated code detection' to support not just C#/VB files

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#21173]
We have code in Roslyn that makes certain determinations based on if a file is generated code or not.  For example:

https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Impl/RoslynVisualStudioWorkspace.cs#L136

This code fails for languages like TypeScript both because it currently crashes (since hte impl of IsGeneratedCode assumes it is working on a C#/VB file), and also because it can't ever actually answer this question properly if it was resilient to getting a file from another language.

This needs to move from an IWorkspaceServie to an ILanguageService to properly support this contract across all languages.

**Comment by CyrusNajmabadi** [comment]
tagging @armanio123

**Comment by Pilchie** [comment]
Fixed by #21174
