### ISSUE TITLE
EnC doesn't work for multi-targeted projects

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#21170]
Repro:
Create two projects:
1) .NET Core ConsoleApp: ```<TargetFramework>net46</TargetFramework>``` 
2) .NET Core Library: ```<TargetFrameworks>netstandard2.0;net46</TargetFrameworks>```

Add reference from ConsoleApp to Library, F5, try edit code in the library.

```
---------------------------
Microsoft Visual Studio
---------------------------
Changes are not allowed if the project wasn't built when debugging started.
---------------------------
OK   
---------------------------
```

Root cause:
When determining the MVID of a project output we only consider a single output, not all outputs. Thus we try to match the output produced for netstandard2.0 with the module loaded into the Console App, which is net46.

**Comment by tmat** [comment]
@jinujoseph FYI

**Comment by jinujoseph** [comment]
Note: Make sure to validate this scenario [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/489743)

**Comment by jinujoseph** [comment]
Reported at [DC](https://developercommunity.visualstudio.com/content/problem/289600/c-edit-and-continue-changes-are-not-allowed-for-cr.html)

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/36727
