### ISSUE TITLE
SolutionCrawlerLogger.LogWorkItemEnqueue boxes a struct enumerator

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#21177]
**Version Used**: 15.3 Preview 6

**Steps to Reproduce**:

1. Open Roslyn.sln

**Expected Behavior**:

Struct enumerator is used to avoid unnecessary allocations.

**Actual Behavior**:

Over ~~60MiB~~ **100MiB** is allocated in `LogWorkItemEnqueue` to box the enumerator returned for `reasons`. `InvocationReasons` should be updated to expose a struct enumerator to avoid this allocation.

**Comment by benaadams** [comment]
Fix https://github.com/dotnet/roslyn/pull/21241
