### ISSUE TITLE
GetSourceDeclarationDiagnostics returns diagnostics that are outside of given span

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#21185]
this asserts

http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Compilation/CSharpCompilation.cs,2318

because 

http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Compilation/CSharpCompilation.cs,2265

returns diagnostic that are outside of given span.

**Comment by heejaechang** [comment]
https://github.com/dotnet/roslyn/pull/20964 disabled the assert for now. please re-enable the assert once it is fixed.

you can live repro by running IOperatinTests.TestClone

**Comment by gafter** [comment]
See #21020 for a repro.

**Comment by mavasani** [comment]
@dotnet/analyzer-ioperation @AlekseyTs @gafter - given that the assert can be repro'ed from a non-IOperation scenario (#21020), I am proposing that we remove the PROTOTYPE comment in features/ioperation and use #21020 to track fixing this assert. Any objections?

**Comment by AlekseyTs** [comment]
Sounds reasonable to me.

**Comment by heejaechang** [comment]
@jinujoseph why is this bug assigned to me? shouldn't it go to compiler team? this is general compiler bug looks like?

**Comment by jinujoseph** [comment]
we already removed the PROTOTYPE , closing this in flavor of #21020
