### ISSUE TITLE
Remove IgnoredNodes list from CSharp/VBOperationFactory and VerifyParentOperations in TestParentOperations

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#21187]
To make parent pointer to work (https://github.com/dotnet/roslyn/pull/20964), I added simple workaround to return null (IOperation) when someone calls GetOperation with a syntax node which cause GetOperation to create one-off Operation tree which doesn't belong to its parent's Operation tree.

We need to make sure such case can't happen for those cases and remove the IgnoredNodes from the OperationFactory

**Comment by heejaechang** [comment]
make sure this is removed from VBOperationFactory once this issue is fixed.

If IsIgnoredNode(boundNode) Then
                ' due to how IOperation is set up, some of VB BoundNode must be ignored
                ' while generating IOperation. otherwise, 2 different IOperation trees will be created
                ' for nodes under same sub tree
                Return Nothing
            End If

**Comment by heejaechang** [comment]
you can live repro by running IOperation tests

**Comment by heejaechang** [comment]
IOperationTests.TestParentOperations also contains list of such cases.

**Comment by heejaechang** [comment]
we need to decide what to do for InvalidExpression and InvalidStatement. right now, children of those 2 operations can't guarantee our contract on IOperation tree. its child (and its sub tree) doesn't include all operations user can through GetOperation

**Comment by jinujoseph** [comment]
**Design Team Decision**
@heejaechang , will gather some examples where he notices the discrepancy between 
tree node -> bound node 
bound node -> Operation tree
and we can revisit this again.

**Comment by CyrusNajmabadi** [comment]
@heejaechang Do you have examples ready to bring today?

**Comment by mavasani** [comment]
@heejaechang is this ready to discuss tomorrow?
