### ISSUE TITLE
semantic.GetCollectionInitializerSymbolInfo(initializerSyntax).Symbol is null for a VB collection initializer

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn#21197]
**Version Used**: 
2.3.1
**Steps to Reproduce**:

1. Debug the following code then examine `symbol` at the end
```csharp
        private static void TestCollectionInitializer()
        {
            var source =
@"Class C
    Dim y = {1, 2, 3}
End Class";
            var ws = new AdhocWorkspace();
            var vbProject = ws.AddProject("vbproject", LanguageNames.VisualBasic)
                .AddMetadataReference(MetadataReference.CreateFromFile(typeof(string).Assembly.Location))
                .AddMetadataReference(MetadataReference.CreateFromFile(typeof(Microsoft.VisualBasic.CompilerServices.StandardModuleAttribute).Assembly.Location))
                .AddMetadataReference(MetadataReference.CreateFromFile(typeof(Enumerable).Assembly.Location));
            vbProject = vbProject.WithCompilationOptions(
                vbProject.CompilationOptions.WithOutputKind(OutputKind.DynamicallyLinkedLibrary));

            var doc = vbProject.AddDocument("Class1.vb", source);
            var semantic = doc.GetSemanticModelAsync().GetAwaiter().GetResult();
            var root = doc.GetSyntaxRootAsync().GetAwaiter().GetResult();

            var initializerSyntax = root
                .DescendantNodes()
                .OfType<Microsoft.CodeAnalysis.VisualBasic.Syntax.CollectionInitializerSyntax>()
                .First();
            var symbol = semantic.GetCollectionInitializerSymbolInfo(initializerSyntax).Symbol;
        }
``` 

**Expected Behavior**:
Information about the collection initializer

**Actual Behavior**:
null

Am I missing anything?

**Comment by AlekseyTs** [comment]
Here is how the API is defined:
```
       ''' <summary>
        ''' Returns what 'Add' method symbol(s), if any, corresponds to the given expression syntax 
        ''' within <see cref="ObjectCollectionInitializerSyntax.Initializer"/>.
        ''' </summary>
        <Extension>
        Public Function GetCollectionInitializerSymbolInfo(semanticModel As SemanticModel, expression As ExpressionSyntax, Optional cancellationToken As CancellationToken = Nothing) As SymbolInfo
```

I do not believe there is a ```ObjectCollectionInitializerSyntax``` anywhere in the repro scenario. The VB code is using an array literal, which is represented by ```CollectionInitializerSyntax```, but no ```Add``` method is used in this case. Note, that, even when ```CollectionInitializerSyntax``` is part of an ```ObjectCollectionInitializerSyntax```, the ```GetCollectionInitializerSymbolInfo``` API is supposed to be called on an "expression syntax within" it rather than on the ```CollectionInitializerSyntax``` directly.

**Comment by jeremymeng** [comment]
@AlekseyTs is there a way to get symbol info for the expression `{1, 2, 3}` in `Dim y = {1, 2, 3}`?

**Comment by AlekseyTs** [comment]
> is there a way to get symbol info for the expression {1, 2, 3} in Dim y = {1, 2, 3}?

What symbol would you expect to get?

**Comment by jeremymeng** [comment]
I remember originally I was trying to get the type of the expression, but now I don't think I need that anymore. Also I should use `GetTypeInfo()` for that. So it's all good. Thanks!
