### ISSUE TITLE
Cancelling inline rename does not revert caret position

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#21207]
**Version Used**: 2.3.2.61921

**Steps to Reproduce**:
```C#
public int My|Int;
```
1. Hit F2
2. Hit Esc

**Expected Behavior**:
```C#
public int My|Int;
```
**Actual Behavior**:
```C#
public int MyInt|;
```

**Comment by sharwell** [comment]
:memo: Given the subtlety of this behavior, a proper regression test will be very important.

**Comment by jcouv** [comment]
@sharwell You may want to point to some tests around this area, as starting point or example, to facilitate someone grabbing this issue. Thanks

**Comment by Pilchie** [comment]
@jasonmalinowski @dpoeschl care to point out where in the InlineRename tests this would go?

**Comment by jcouv** [comment]
Thanks, found some: http://source.roslyn.io/#Roslyn.Services.Editor2.UnitTests/Rename/InlineRenameTests.vb,79780df2fe47cac9

It looks like they already have logic to figure out caret position (`Dim caretPosition = workspace.Documents.Single(Function(d) d.CursorPosition.HasValue).CursorPosition.Value`), which is the part I had not seen in other tests.

**Comment by CyrusNajmabadi** [comment]
Haven't heard about thsi from any other sources.  Unlikely to make this change.
