### ISSUE TITLE
Unexpected IL on switch statement with bool

### ISSUE THREAD

**Issue by jp2masa** [dotnet/roslyn#21200]
**Version Used**: Visual Studio 2017 Version 15.2

**Steps to Reproduce**:
(C#) A simple switch case on a bool:
```cs
bool xBool = false;
switch (xBool)
{
    case true:
        break;
}
```
The generated IL (local 0 is xBool):
```
ldloc.0
ldc.i4.1
beq.s IL_0015
```

**Expected Behavior**:
xBool should be compared to 0, and it's true if it's not 0. Also, an optimization would be expected, so a brtrue would be generated instead of this comparison.

**Actual Behavior**:
xBool is compared with the constant value 1, but bool behaviour is implementation specfic.

**Comment by mikedn** [comment]
> but bool behaviour is implementation specific

Sort of. Both Roslyn and the JIT assume 0/1 bools and optimize according to that. Attempting to use any value other than 1 as `true` will cause problems.

That said, the IL generated in this case is inconsistent with the code generated for `if` statements. I would expect to be identical. That is, something like `ldloc/brtrue`.

**Comment by jp2masa** [comment]
Part of a table from [docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/framework/interop/blittable-and-non-blittable-types)

| Non-blittable type | Description                                               |
|--------------------|-----------------------------------------------------------|
| System.Boolean     | Converts to a 1, 2, or 4-byte value with true as 1 or -1. |

This means that true may be -1, right?

**Comment by mikedn** [comment]
> Part of a table from

That's marshaling related documentation so it's not very relevant. It tells you that can marshal bools to various native representations but it doesn't state anything about how bool itself is represented.

The relevant documentation is in the ECMA spec where bools are:

> III.1.1.2 Boolean data type A CLI Boolean type occupies 1 byte in memory. A bit pattern of all zeroes denotes a value of false. A bit pattern with any one or more bits set (analogous to a non-zero integer) denotes a value of true.

So any non-zero value is supposed to be `true`.

But as already stated, both Roslyn and RyuJIT assume bools to be either 0 or 1. Attempting to use other values can produce unexpected results. Incidentally I know a particular JIT optimization that generates code that misbehaves when you give it `-1`.

See #14262 as well.

**Comment by fanoI** [comment]
I'm mistaking or there is an historical difference between C# and VB.Net on how True is represented? I remember that it was -1 in VB.Net...

**Comment by mikedn** [comment]
>  I remember that it was -1 in VB.Net...

I doubt that true was ever -1 in VB.NET. It may have been in VB6, no idea.

**Comment by jp2masa** [comment]
Is `ldloc; ldc.i4.1; beq` faster than `ldloc; ldc.i4.0; bne` ?

**Comment by mikedn** [comment]
> Is ldloc; ldc.i4.1; beq faster than ldloc; ldc.i4.0; bne ?

Nope, they generate the same number of instructions with similar performance characteristics. Though comparing with 0 generates slightly smaller code on x86/x64 so it is usually preferred. And of course, if you compare with 0 you can simply use brfalse/brtrue because it is shorter (in IL, in assembly it's the same thing).

**Comment by jaredpar** [comment]
This is "ByDesign".

@mikedn is correct here. The C# language specifies that a boolean can be only 1 or 0. It's true that the CLI allows for more numeric values of boolean, however C# only considers the case for 1 or 0. There are several places where this is noticable i the language, switch being one of them.
