### ISSUE TITLE
Code style to recommend null or 0 literal instead of default literal, when possible

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#21208]
For simplest cases (built-in types), like `string s = default;` or `int i = default;`, a more specific literal makes more sense.

FYI @CyrusNajmabadi

**Comment by miloush** [comment]
I am not convinced that much, why does it make more sense?

**Comment by CyrusNajmabadi** [comment]
@jcouv  What context are you referring to?  You mention "recommend null or 0...", but when are you talking about?

**Comment by sharwell** [comment]
This is closely related to DotNetAnalyzers/StyleCopAnalyzers#1976.

**Comment by jcouv** [comment]
Yes, I'm suggesting a code style that recommends more specific literals, when possible.
If you type `string s = default;`, a lightbulb would recommend `null` instead.

**Comment by Pilchie** [comment]
Tagging @kuhlenh too for backlog prioritization.

**Comment by miloush** [comment]
@jcouv why is more specific better?

**Comment by CyrusNajmabadi** [comment]
> If you type string s = default;, a lightbulb would recommend null instead.

I'm confused who would type that :)

**Comment by jcouv** [comment]
@CyrusNajmabadi Another example: `void M(string s) {...}` that you invoke with `M(default)`. If you think users will already use more specific literal, then no need for code style.

@miloush This would be a style (ie controlled by preference). I think more specific literals make the code more readable. Consider `M(default)` or `M(0)`, the latter gives you more context/information.

**Comment by sharwell** [comment]
My main concern here is the ability to expand the feature, i.e. a user-configurable set of "preferred default values".

**Comment by CyrusNajmabadi** [comment]
> Another example: void M(string s) {...} that you invoke with M(default)

My point is this:

What customer does this?  null, 0, etc. have been the way to specify defaults since C# 1.0.  They're so idiomatic.  They're the absolute norm for huge swaths of users.  The only user who isn't using this is because they feel like there is specific value in using 'default' (which, for reference types seems... unlikely).

**Comment by jcouv** [comment]
Makes sense. I'm fine to wait to see if this problem occurs in the wild.

**Comment by alrz** [comment]
> (which, for reference types seems... unlikely).

I would always prefer `default` for default arguments values and assigning out parameters in failure path.

(aside: https://github.com/dotnet/csharplang/issues/583 would help with the latter - you can assign all out parameters with a single assignment.)

**Comment by CyrusNajmabadi** [comment]
Yes.  If we were to provide anything here, it would be much more about making it possible for a person to say that they preferred 'default' everywhere, instead of the the more common 'null/etc.'

**Comment by jcouv** [comment]
Closing as the proposal doesn't seem useful after all. Thanks for the feedback
