### ISSUE TITLE
Roslyn cannot work in netstandard dll?

### ISSUE THREAD

**Issue by scegg** [dotnet/roslyn#21205]
I need to encapsulte Roslyn into a netstandard dll for fx47 and core11 clients.

Source code are available at: https://github.com/scegg/CSharpRoslynHelper

The code to compile in Roslyn:
```
using System;
using System.Collections.Generic;
using System.Reflection;

namespace UserCode
{
    public class UserCodeClass
    {
        public bool Check(string message)
        {
            List<string> x = new List<string>();
            GenericMethod((dynamic)x);
            Console.WriteLine(message);
            return true;
        }

        public void GenericMethod<T>(List<T> data)
        {
            var implant = new Implant<object>();
            implant.Print(data);
        }
    }

    public class Implant<TClass>
    {
        public void Print<TArg>(List<TArg> list)
        {
            var result = string.Format(""TClass: {0} ({1})\nTArg: {2} ({3})"", typeof(TClass).Name, typeof(TClass).GetTypeInfo().Assembly.CodeBase, typeof(TArg).Name, typeof(TArg).GetTypeInfo().Assembly.CodeBase);
            Console.WriteLine(result);
        }
    }
}
```
The assemblies provided with the code:
Microsoft.CSharp, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Linq, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e

**Version Used**: 
VS 2017 15.2 26430.16
Class library for encapsulate Roslyn:
    Standard 1.3
    Nuget: Microsoft.CodeAnalysis.CSharp 2.3.1
    Roslyn won't read from disk for assembly. All assemblies will be provided as byte[] from caller.
App referenced this class library:
    Core 1.1 Console

**Steps to Reproduce**:
1. Get code from github https://github.com/scegg/CSharpRoslynHelper
2. Select CoreTest-Direct to run.
3. Check the error. Id: CS0656; Message: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'

**Expected Behavior**:
The error should not exists coz Microsoft.CSharp is referenced.

**Actual Behavior**:
Error.

Actually, non of 4 tests in this solution can work...
Projects in this solution are:
CSharpRoslynHelper: The encapsulate of Roslyn, in netstardard 1.3
ShandardLibraryAsProxy: A proxy, in netstandard 1.5 and netfx 47, which is designed to provide the images of all required assemblies requested from CSharpRoslynHelper.
CoreTest-ByProxy: Core11 Console App, references ShandardLibraryAsProxy and provide the code only.
CoreTest-Direct: Core11 Console App, references CSharpRoslynHelper and provide images of all required assemblies.
Fx47Test-ByProxy: netfx47 Console App, references ShandardLibraryAsProxy and provide the code only.
Fx47Test-Direct: netfx47 Console App, references CSharpRoslynHelper and provide images of all required assemblies.

**Comment by jaredpar** [comment]
> The assemblies provided with the code:
Microsoft.CSharp, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Linq, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e

How are these assemblies being provided? In general the compiler should never receive System.Privaet.CoreLib as a reference as it's a runtime assembly. Trying to compile directly against it will possibly result in errors. Instead the reference assemblies should be used here,.

**Comment by tmat** [comment]
For more info on what references to pass to the compiler when compiling at runtime: https://github.com/dotnet/roslyn/wiki/Runtime-code-generation-using-Roslyn-compilations-in-.NET-Core-App

**Comment by scegg** [comment]
@jaredpar 
Assembly[] assemblies = new Assembly[]
        {
                typeof(Microsoft.CSharp.RuntimeBinder.Binder).GetTypeInfo().Assembly,
                typeof(Enumerable).GetTypeInfo().Assembly,
                typeof(object).GetTypeInfo().Assembly
        };

And then, find all there files, load from disks.

@tmat 
Thanks for your code. But when I try to load System.Runtime.dll from the trusted list, I got an error while using System.Runtime.Loader....LoadFromStream
System.BadImageFormatException: 'An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)'

**Comment by jaredpar** [comment]
@scegg 

That is unlikely to succeed in this case. It means you're asking Roslyn to compile against the implementation assemblies, not the reference assemblies. That is not supported or tested by the corefx team. 

It is a pain point for sure though. It's caused us a number of headaches in scripting and porting certain MSBuild features to CoreClr.

**Comment by scegg** [comment]
@jaredpar 
Actually, I didn't get your point about the difference between implementation assemblies and reference assemblies. These assemblies are from the netcore app directly.

My goal is setting up a standalone library (in netstandard or multiplatform I think) to handle the Roslyn and some class from the library need to used in the code compiled from Roslyn. This library should support caller from netfx and netcore and the Roslyn generated assembly should work with the caller in the same base standard (netfx for netfx, netcore for netcore). Any idea for this requirement?

**Comment by scegg** [comment]
A simple related question:
If I use roslyn compile a piece of code to dll assembly (no entry), all assemblies are provided in pe-image format from another source, maybe database records, what's the format of the assembly compile? like a netstandard dll?
if it is, and if these images of assemblies are all from netfx, could the dll be referenced into a netfx app just like a netfx class library?

Thanks.

**Comment by jaredpar** [comment]
@scegg 

> Actually, I didn't get your point about the difference between implementation assemblies and reference assemblies. These assemblies are from the netcore app directly.

When building Net Standard / Core projects it's important to understand the difference between reference and implementation assemblies:

- reference assemblies: what the C# compiler reads via the `/reference:` switch. They support compilation scenarios for a given TF.
- implementation assemblies: what msbuild deploys to the `bin` folder. They support execution scenarios for a given TF. 

Passing an implementation assembly to the compiler is not supported. That being said in a lot of cases it will still "work". I'd wager that for most NuGet packages out there you could pass implementation assemblies to the compiler and nothing of significance would change. 

This is not true though for a number of NuGet packages shipped in the core framework. These assemblies fully leverage the room that having a reference / implementation pair allows developers. In particular this is not true for the library that contains `System.Object`. 

``` c#
typeof(object).GetTypeInfo().Assembly
``` 

This series of evaluations is grabbing the implementation assemblies for the various types. Hence your code is passing a set of implementation assemblies to the compiler, not reference assemblies. This isn't a supported scenario for the DLLs, particularly for `System.Object`.

**Comment by scegg** [comment]
@jaredpar 
Thanks a lot for your explanation.

So, if I need to run Roslyn from a netstandard / core app, I need to grab all assembly images from the reference assemblies, rather than implementation ones. Am I right?

And, is that affect the netfx app also?  Thanks.

**Comment by tmat** [comment]
@scegg 
>  I got an error while using System.Runtime.Loader....LoadFromStream System.BadImageFormatException

Can you share the exact snippet of the code? This should work - it's what we do in scripting runtime. 

@jaredpar 
If all references are implementation assemblies from the TPA list there is no reason why compiling against implementation assemblies shouldn't work -- as long as all references passed to the compilation are implementation assemblies (mixing ref and impl doesn't work) and exactly one is "corlib" (defines System.Object and other special types). Reflection.Emit and the C# dynamic binder are in fact compiling against implementation assemblies. The only problem with using impl assemblies is no guarantee on stability of their public APIs.

**Comment by scegg** [comment]
@tmat all source code are available on github: https://github.com/scegg/CSharpRoslynHelper

**Comment by tmat** [comment]
@scegg 
The BadImageFormatException you see is not related to Roslyn. It's the use of CoreCLR AssemblyLoadContext API that's incorrect.
Loading files from bytes only works for IL only images. One of the files you're trying to load is probably ready-to-run image. 

Using ```AssemblyLoadContext.Default.LoadFromAssemblyPath``` should work. I have tried it on all images included in TPA, but for some reason it fails on ```System.Private.CoreLib.dll```, which I don't understand why. I'm looking into it.

BTW: Do you intend to support ```#r``` directives in the source? If not passing ```metadataReferenceResolver``` to the compilation thru options is not necessary: https://github.com/scegg/CSharpRoslynHelper/blob/master/CSharpRoslynHelper/Builder.cs#L141

**Comment by scegg** [comment]
@tmat 
I'm not using #r.
In my project, I need to generate code based on user's class (reflection) and compile it. Due to too many types may be used in generated code, I need to find and reference used assemblies to Roslyn for building.
I use these steps to load assemblies:
1 Get the type object from user's class (reflection);
2 Get the assembly of these type by using .GetTypeInfo.Assembly
3 Get the location of these assembly (I know there is a issue about assembly may not have a location)
4 Load file into byte array.
5 Pass the byte array to metadataReference.

**Comment by scegg** [comment]
Now using all from TRUSTED_PLATFORM_ASSEMBLIES and dotnet standard 2.0, no problem currently.
