### ISSUE TITLE
Consider automatically inserting a banner into a file when creating a new file from a template.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#21227]
From https://github.com/dotnet/roslyn/pull/21204#issuecomment-319245593

Danger here is that there is some random file with a banner that is appropriate for it, but we place that banner in new files even if users would not want that.

**Comment by AdamSpeight2008** [comment]
Why not just have new template with the banner already in it?

**Comment by CyrusNajmabadi** [comment]
@AdamSpeight2008 The point would be to have the IDE automatically detect and adapt to the coding patterns for your project.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi I could imagine that whatever we come up with for enforcing banners (per @sharwell's discussion yesterday) could be used to drive this. Honestly we could also do something a bit smarter -- if we find the same banner in multiple files, then use that as a stronger hint.

**Comment by CyrusNajmabadi** [comment]
>I could imagine that whatever we come up with for enforcing banners (per @sharwell's discussion yesterday) could be used to drive this. 

Yes.  In the presence of the user opting into this, i think we'd handle things very differently.  Tome this feature is much more about providing assistance for a user that doesn't opt into anything, and just wants to hit a keystroke to help them out.

**Comment by CyrusNajmabadi** [comment]
> Honestly we could also do something a bit smarter -- if we find the same banner in multiple files, then use that as a stronger hint.

We could definitely consider that.  Perhaps keep a histogram with a cutoff.  So if we see a header used a certain number of times, we consider that good enough.  That way we don't have to scan everything in the case where users do have headers.  And we're also not thrown off by a lone file with a disparate banner.

**Comment by AdamSpeight2008** [comment]
What about project and solution level properties for banners?
A Solution level banner overrides Project level banners (unless specifically opted out)..

**Comment by jasonmalinowski** [comment]
I imagine any settings we set would be in .editorconfig.

**Comment by AdamSpeight2008** [comment]
What if you're working on two different projects with different banners? Wouldn't that clash?
Would `.editorconfig` banner just be the default?

**Comment by jasonmalinowski** [comment]
You could have separate .editorconfigs that apply to separate projects.

**Comment by CyrusNajmabadi** [comment]
Tagging @sharwell.  We likely really should do this once we have hte .editor_config setting for copyright header

**Comment by sharwell** [comment]
The ideal solution here would be running Code Cleanup when creating a file from a template with the following configuration:

1. Format document
2. Sort using directives (and move them inside the namespace declaration if desired)
3. Add file header

**Comment by sharwell** [comment]
Here's where the formatter is currently run on new files created from a template:

https://github.com/dotnet/roslyn/blob/4d24556df984774dc70cf707eff1ee9d3d96b9b9/src/VisualStudio/Core/Def/Implementation/AbstractEditorFactory.cs#L292-L293
