### ISSUE TITLE
Test plan for "non-trailing named arguments" (7.2)

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#21236]
Test Plan for Non-Trailing Named Arguments
==========================================

The draft specification needs to describe the error situation as an error.

Test for proper execution in simple positive test cases
- [x] Method call `M(1, b: 2, 3)` (see `TestSimple`)
- [x] Constructor `new C(1, b: 2, 3)` (see `TestSimpleConstructor`)
- [x] Indexer `c[1, b: 2, 3]` (see `TestSimpleIndexer`)
- [x] Attribute `[MyAttr(1, b: 2, 3)]` (see `TestInAttribute`)
- [x] Extension method invocation. (see `TestSimpleExtension`)
- [x] Delegate Invocation (see `TestSimpleDelegate`)
- [x] Local function invocation (see `TestSimpleLocalFunction`)
- [x] `this(...)` and `base(...)` (see `TestSimpleThis` and `TestSimpleBase`)

You can set a property in an attribute spec using `[A(a, b, P=1)]`. Ensure you can still do that after a positional argument following an in-place named argument. Is there a way of exercising an equivalent thing in VB?

Test that the above positive cases are errors when language version is < 7.2. (see `TestNamedAndOptionalParamsErrors`, `TestDynamicCallErrors`, `TestDynamicCallErrors`, error `CS1738`, see most Simple test cases which also test old langversion)

Test for errors in simple negative test cases
- [x] Method call `M(b: 2, 3)` (see `TestSimpleError`)
- [x] Other kinds of invocations, above (a couple of combinations are tested, but not all)

Test showing that *any* named argument out of position disallows following values
- [x] Method call `M(b: 2, a: 1, c: 3, 4)` (see `TestPositionalUnaffected2`, error `CS8321`)
- [x] Other kinds, above

Demonstrate interaction with kinds of symbols
- [x] Feature should be operative in symbols from source, metadata, and in a reference to another compilation (see `TestMetadataAndPESymbols`)
- [X] Should work for methods that are generic, permitting type inference from arguments in the call. (see `TestGenericInference`)
  - [ ] VB too (has been hand-verified)

Demonstrate interaction with `params`
- [x] If there is a named argument for the `params` (last) parameter, no further arguments can be specified without names. Not even that same parameter. (see `TestNamedParams`, `TestNamedParams2`, `TestTwiceNamedParams`, `TestNamedParams5`)
- [ ] Even when this feature is used for preceding arguments, a named argument may still name the `params` parameter either in expanded or unexpanded form. (see `TestParams`, `TestParams2`) **Need test for unexpanded form (has been hand-verified).**

Demonstrate that optional parameters may be omitted after taking advantage of this feature for leading parameters.

Demonstrate interaction with `dynamic`
- [x] A dynamic invocation should forbid any positional argument following a named argument. (see `TestDynamicInvocation`)
- [x] Some invocations involving dynamic are not dynamic invocations (i.e. do not involve the use of the dynamic binder to resolve the invocation). Reportedly `c[a: 1, dyn] = dyn` (an indexer) is one example. Test that the feature may be used in those cases. See Ashley's email for a list of cases. (see `TestDynamicWhenNotInvocation`)
- [x] In VB, something similar occurs with `Option Strict Off` and calls that involve the type `Object`. We should not permit non-trailing named arguments in VB late-bound calls. (see `TestDynamicInvocation` in VB)

Demonstrate interaction with [`__arglist`](http://bartdesmet.net/blogs/bart/archive/2006/09/28/4473.aspx)
- [x] `__arglist` should act like a positional parameter that cannot be named
  - [x] Can use `__arglist` after named arguments in proper position (see `TestSimpleArglist`)
  - [x] Cannot use `__arglist` after named arguments out of proper position (see `TestSimpleArglistAfterOutOfPositionArg`)

Language Version
- [x] Feature only works in language version 7.2 (C#)
- [x] Feature only works in language version 15.5 (VB)

IDE integration
- [ ] The "add argument name" IDE action no longer adds names to following arguments in language version 7.2 (see `TestNonTrailingNamedArgumentInCSharp7_2`) **That is a completion test, not a test for 'add argument name'**
- [ ] The "add argument name" IDE action adds names to following arguments in language version < 7.2 (see `TestNonTrailingNamedArgumentInCSharp7_1`) **That is a completion test, not a test for 'add argument name'**
- [ ] It should have an option to "add all argument names" (which before would have been accomplished by adding a name to the first argument) in language version 7.2 [jcouv: this is not currently planned]
- [ ] These should be true for all four invocation forms identifier above
- [ ] Language version upgrade suggested when needed
  - [x] C# *Hand-tested, verified working*
  - [ ] VB **Hand-tested, *verified not working***

Compiler APIs
- [x] The SemanticModel APIs that can return the symbol of an argument name in a named argument work even when this feature is used. 
- [x] What is the kind of result when a call is unambiguous but has a named-arg-out-of-position-followed-by-positional problem `CandidateReason.OverloadResolutionFailure`? Demonstrate. (see ` TestPositionalUnaffected2`)

## Pointers to related links:
- PR to master: https://github.com/dotnet/roslyn/pull/20805
- language proposal: https://github.com/dotnet/csharplang/blob/master/proposals/non-trailing-named-arguments.md
- work items: https://github.com/dotnet/roslyn/issues/19890

**Comment by gafter** [comment]
I've updated the OP to include the test plan inline.

**Comment by gafter** [comment]
I've updated the test plan as a result of our meeting just now.
