### ISSUE TITLE
IOperation API for BoundRangeVariable

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#21238]
Both VB and C# have a BoundRangeVariable node to represent reference to a range variable in query clause. We need to design an IOperation API for it.

**Comment by jinujoseph** [comment]
@mavasani , can you tag this for discussion when we have a proposal

**Comment by jinujoseph** [comment]
@mavasani  can you check if this can be closed

**Comment by mavasani** [comment]
We still have these nodes in the bound tree, but given that we have decided to not expose range variables in v1, we can move this to backlog.

**Comment by mavasani** [comment]
This is no longer required once https://github.com/dotnet/roslyn/issues/23079 is fixed as these bound nodes will not be in operation tree.
