### ISSUE TITLE
Roslyn parser issue

### ISSUE THREAD

**Issue by Sumangalaknair** [dotnet/roslyn#21234]
**vs 2015**: 

**Steps to Reproduce**:

1. I am unable to get identifier base class types for member access expressions nested inside invocationexpressionsyntax.
2. building a new custom parser for setting rules

```
var identifierList = invocation.Expression.DescendantNodes().OfType<SyntaxNode>();
                        foreach (var p in identifierList)
                        {
                            if (p is IdentifierNameSyntax)
                            {
                                IdentifierNameSyntax identifierName = p as IdentifierNameSyntax; // identifierName is your method name
/// need base type of all the tokens inside theinvocation expression inclusing arguments
                            }

                            if (p is MemberAccessExpressionSyntax)
                            {
                                MemberAccessExpressionSyntax memberAccessExpressionSyntax = p as MemberAccessExpressionSyntax;
                                var memberSymbol =  context.SemanticModel.GetSymbolInfo(memberAccessExpressionSyntax).Symbol as IMethodSymbol;
                                
                                //memberAccessExpressionSyntax.Name is your method name
                            }
```

**Expected Behavior**:

**Actual Behavior**:

Edited by @sharwell: Code formatting (preserved original indentation)

**Comment by jcouv** [comment]
I'm sorry, I didn't understand what you are trying to do. Are you trying to construct a syntax tree?

**Comment by Sumangalaknair** [comment]
Yes.. I am trying to identify the node type involved in the " if
conditional expression". Eg: if a.equals(b) is the statement. I need the
base types of a and b to check if it is a specific property derived from a
static class. I need this to implement a customized rule for the developers.

Thanks for your reply.

**Comment by jcouv** [comment]
Maybe Roslyn Quote can help you: https://roslynquoter.azurewebsites.net/

**Comment by Sumangalaknair** [comment]
The application is good when it comes to identifying each node to generate
a code to build it. Thanks. It might help if i get to see your code. My
requirement is to write an analyser for an application which will parse
each node in the if expression expression ti check if there are any enum
usages in the .equals conditions.

**Comment by Sumangalaknair** [comment]
I guess i am able to acheive it. Thanks for your suggestions.

**Comment by jcouv** [comment]
Glad that worked. I'll go ahead and mark the issue as resolved. Cheers
