### ISSUE TITLE
Some VB comments not classified

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#2126]
Ported from TFS WorkItem: **938129**
&nbsp;
<PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: blue"><PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: blue">Class</SPAN> <SPAN style="COLOR: #2b91af">C</SPAN>
    <SPAN style="COLOR: blue">Sub</SPAN> <SPAN style="COLOR: black">M</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: black">x</SPAN> <SPAN style="COLOR: blue">As</SPAN> <SPAN style="COLOR: #2b91af">XElement</SPAN><SPAN style="COLOR: black">)</SPAN>
        <SPAN style="COLOR: green"><FONT color=#ff00ff>' Comment</FONT></SPAN>
        <SPAN style="COLOR: black">x</SPAN><SPAN style="COLOR: #6464b9">.@</SPAN><SPAN style="COLOR: #b96464">Name</SPAN><SPAN style="COLOR: black">=</SPAN> <SPAN style="COLOR: #a31515">"Foo"</SPAN>
    <SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Sub</SPAN>
<SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Class</SPAN></PRE></SPAN></PRE>

Note that it's not classified *at all*.

**Comment by Pilchie** [comment]
Strange - I added a test for this:

```
        <Fact, Trait(Traits.Feature, Traits.Features.Classification)>
        <WorkItem(2126, "https://github.com/dotnet/roslyn/issues/2126")>
        Public Sub CommentBeforeXmlAccessExpression()
            TestInMethod(" ' Comment
                           x.@Name = ""Text""",
                         Comment("' Comment"),
                         Identifier("x"),
                         VBXmlDelimiter("."),
                         VBXmlDelimiter("@"),
                         VBXmlAttributeName("Name"),
                         Operators.Equals,
                         [String]("""Text"""))
        End Sub
```

And it passes, which seems to imply the classifier is doing the right thing.

**Comment by AdamSpeight2008** [comment]
@Pilchie 
Sorry if sound like dumb question but what do mean by classified?
*My thoughts are that it working out what a section source code text is, in the context of the programming language. Eg This section of the text is a comment.* 
Am I'm correct in that thinking?

**Comment by Pilchie** [comment]
Yes, classification is what the editor APIs that control how text is colored in the editor (AKA Syntax Highlighting, Colorization, etc).

**Comment by Pilchie** [comment]
Ah-ha!  A `FullSpan` versus `Span` issue meant we weren't returning results to the editor when they call us line by line.

**Comment by jasonmalinowski** [comment]
Saw the internal resolved bug on me -- I can verify this works.
