### ISSUE TITLE
Incorrect comment in src/Features/VisualBasic/Portable/ReplacePropertyWithMethods/VisualBasicReplacePropertyWithMethods.vb#L23?

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn#21262]
**Version Used**: 
master branch

**Steps to Reproduce**:

I am looking at the code to see what VB properties are not supported by the ReplacePropertyWithMethods feature

https://github.com/dotnet/roslyn/blob/24d55702cb26ab11e22eae8db4cf7ccc5fe3eef5/src/Features/VisualBasic/Portable/ReplacePropertyWithMethods/VisualBasicReplacePropertyWithMethods.vb#L23

**Expected Behavior**:
`' a parameterized property can be trivially converted to a method.`

Seems like it should  be `cannot`?

**Comment by Pilchie** [comment]
@jeremymeng Care to submit a PR?

**Comment by jeremymeng** [comment]
@Pilchie sure.
