### ISSUE TITLE
Documentation required: Compilers/CSharp vs Compilers/Core

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#21270]
Hello,
In the docs I have found no info.
Could you explain what kind of code should  be stored in the "Core" folder and what should be in the "CSharp" folder.

Is "Core" just for code shared by VisualBasic and CSharp?

Kind regards,

Bernd

**Comment by jaredpar** [comment]
This is a general directory pattern that exists in our code base. Essentially

``` txt
Feature
    / Core: code common to both C# and VB implementations
    / CSharp: C# specific implementation
    / VisualBasic: VB specific implementation
```

Occasionally you will also see directories like `CSharp.Desktop` which indicate desktop only versions of the product.
