### ISSUE TITLE
IAddressOfExpression API Review 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21276]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/IAddressOfExpression.cs 

- We don't need to expose this for V1 
- We need to rename this as IPointerAddress

cc @dotnet/analyzer-ioperation

**Comment by sharwell** [comment]
❓ How do we differentiate between `&variable` and `ref variable`? From the perspective of many analysis operations, they could be treated equivalently. Others may want to differentiate. To me this suggests a common operation kind but a property indicating whether the result is a managed reference or an unmanaged reference.

**Comment by 333fred** [comment]
I'm going to close this, as discussion is happening is #21311. See https://github.com/dotnet/roslyn/issues/21311#issuecomment-321346357.
