### ISSUE TITLE
ICatchClause API review

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21277]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/ICatchClause.cs 

- We should get rid of CatchType here

**Comment by sharwell** [comment]
> We should get rid of CatchType here

I assume `ExceptionLocal` will serve this purpose, which may be a discard but either way will have a type?

**Comment by jinujoseph** [comment]
since we are making the API internal for V1 , moving this to backlog to address the change when we make the API public

**Comment by mavasani** [comment]
I think we need to retain the `CatchType` for cases where no exception local is specified, say `catch(Exception) { ... }`. I recall we decided to remove this field as we thought we can use `IOperation.Type` field to hold the catch type - @dotnet/analyzer-ioperation does this sound reasonable or do we think `ICatchClause.Type` should always be null as it is not an expression, in which case we should retain the `CaughtType` field?

**Comment by mavasani** [comment]
Another missing piece here: If catch filter declares a local, we do not expose it anywhere. For example:

```
using System;

class C
{
    static void M(object o)
    {
        try
        {
        }
        catch (Exception) when (o is string s)
        {            
        }
    }
}
```

I think we may need to create either create a new `ICatchClauseFilter` which exposes the filter expression and locals OR we need to expose `FilterLocals` on `ICatchClause`.

**Comment by mavasani** [comment]
@jinujoseph Let us bring this issue to discussion on Thursday.

**Comment by 333fred** [comment]
Could we create a discard variable for that case? It feels to me like it would be better to have a standard pattern for getting the type here, so we don't trip up users with this.

**Comment by mavasani** [comment]
@333fred I found another VB subtlety which would mean we need a richer API. VB allows you to reference an existing non-static local or parameter in the catch statement instead of declaring a new local. Following is legal:

```
Imports System
Class C
    Private Shared Sub M(e As Exception)
        Try
        Catch e
        End Try
    End Sub
End Class
```

So basically, we can have any of 3 different things in the clause:

1. Local declaration (C# and VB)
2. Type expression (C#)
3. Local or Parameter reference expression (VB).

I feel we should expose all 3 with appropriate doc comments.

**Comment by mavasani** [comment]
How about:

```
    /// <summary>
    /// Represents a C# catch or VB Catch clause.
    /// </summary>
    /// <remarks>
    /// This interface is reserved for implementation by its associated APIs. We reserve the right to
    /// change it in the future.
    /// </remarks>
    public interface ICatchClause : IOperation
    {
        /// <summary>
        /// Body of the exception handler.
        /// </summary>
        IBlockStatement Handler { get; }

        /// <summary>
        /// Declaration for the local catch variable bound to the caught exception (C# and VB) OR
        /// type expression for the caught expression type (C#) OR
        /// reference to a non-static local or parameter (VB) OR
        /// an error expression (VB)
        /// </summary>
        IOperation ExceptionDeclarationOrExpression { get; }

        /// <summary>
        /// Filter expression to be executed to determine whether to handle the exception.
        /// </summary>
        IOperation Filter { get; }
    }
```

**Comment by mavasani** [comment]
I have a PR out with the proposed API: https://github.com/dotnet/roslyn/pull/22210/files#diff-3ba5ed996be2c590467f9f33f8f676d3

**Comment by mavasani** [comment]
Design Decision: Have both `ITypeSymbol ExceptionType` and `IOperation ExceptionDeclarationOrExpression` fields. `ExceptionType` should always be non-null and populated for all cases. `ExceptionDeclarationOrExpression` can be null, IVariableDeclaration or ILocalReferenceExpression or IParameterReferenceExpression or IInvalidExpression.
