### ISSUE TITLE
IConditionalAccessInstanceExpression API Review

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21279]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/IConditionalAccessInstanceExpression.cs

- Do we need this at all ? 
- Make sure to check if Analyzers use this 

cc @dotnet/analyzer-ioperation

**Comment by sharwell** [comment]
This *seems* unnecessary since we can just use `IConditionalAccessExpression.Expression`.

**Comment by 333fred** [comment]
@mavasani, I want to bring this to discussion today. Some example code:
```C#
    public void M()
    {
        var o = new object();
        o?.ToString();
    }
```
This generates the following tree:
```
IConditionalAccessExpression (OperationKind.ConditionalAccessExpression, Type: System.String) (Syntax: 'o?.ToString()')
  Left: ILocalReferenceExpression: o (OperationKind.LocalReferenceExpression, Type: System.Object) (Syntax: 'o')
  Right: IInvocationExpression (virtual System.String System.Object.ToString()) (OperationKind.InvocationExpression, Type: System.String) (Syntax: '.ToString()')
      Instance Receiver: IConditionalAccessInstanceExpression (OperationKind.ConditionalAccessInstanceExpression, Type: System.Object) (Syntax: 'o')
      Arguments(0)
```
The problem with removing this is that the instance receiver, in the bound nodes, is a BoundConditionalReceiver. That node doesn't have information about the actual receiver, in this case the ILocalReferenceExpression. It gets even trickier if you consider something like `new object()?.ToString()`: What would we put as the receiver here? We can't just copy the IObjectCreationExpression, as that would make it seem like we're instantiating two different objects. I don't think we can remove this API.

**Comment by 333fred** [comment]
I do think we should add an extension method here though, something like `GetInstance()`, that will walk the parent tree to the actual receiver of the call. Seems like it would be a common thing that users would want to do.

**Comment by 333fred** [comment]
**Design Decision**:
This API is necessary. However, we will add an extension method that will walk the parent tree to retrieve the expression that the `IConditionalAccessInstanceExpression` is referencing.
