### ISSUE TITLE
IMethodBindingExpression API Review 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21289]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/IMethodBindingExpression.cs

**Comment by sharwell** [comment]
:question: Why not `IMethodReferenceExpression` to go with `IMemberReferenceExpression`?

:question: What about cases where the reference can target multiple symbols (`nameof`)?

As an aside, can you clarify how the instance comes into play for something like this? `IMethodBindingExpression` would apply for `ToString`, but where does `new object().` fit in?

```
Func<string> f = new object().ToString;
```

**Comment by CyrusNajmabadi** [comment]
> Why not IMethodReferenceExpression

This is what we're doing.

> What about cases where the reference can target multiple symbols

We have decided for V1 to not have expos ea way to expose a group of methods.  We have not found a compelling need for it for V1.  If there is a good user case, we will consider for vnext.

**Comment by tmat** [comment]
Just a rename.

**Comment by mavasani** [comment]
This is done
