### ISSUE TITLE
IIncrementExpression API Review

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21283]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/IIncrementExpression.cs 

- We should flatten the list of IncrementOperationKind

**Comment by mavasani** [comment]
We decided that we will remove PostFix/Prefix Increment/Decrement from the `UnaryOperatorKind` enum and instead have following 2 Boolean flags on `IIncrementExpression`

```
        /// <summary>
        /// <code>true</code> if this is a decrement expression.
        /// <code>false</code> if this is an increment expression.
        /// </summary>
        bool IsDecrement { get; }

        /// <summary>
        /// <code>true</code> if this is a postfix expression.
        /// <code>false</code> if this is a prefix expression.
        /// </summary>
        bool IsPostfix { get; }
```

Tagging @CyrusNajmabadi and @jinujoseph - we discussed this in our meeting.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/21407
