### ISSUE TITLE
IConditionalChoiceExpression API Review

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21280]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/IConditionalChoiceExpression.cs

- We need to decide if the name looks good

**Comment by sharwell** [comment]
❓ Why not `IConditionalExpression`?

**Comment by jinujoseph** [comment]
**Design Team Decision**
Agree with @sharwell  suggestion
