### ISSUE TITLE
ILocalFunctionStatement API Review

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21287]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/ILocalFunctionStatement.cs

LocalFunctionSymbol  Should be renamed as Symbol

**Comment by sharwell** [comment]
Seems like `Body` could be `IOperation` to avoid overhead from `IBlockOperation` for expression-bodied members. With that said, normalizing expression-bodied members could make it easier to consume the API. Either way, it would be good for the documentation of `Body` to state the behavior in its remarks section.

**Comment by 333fred** [comment]
@sharwell we're already normalizing it. From an API user's perspective, it's much easier to be able to think of all functions as just a block with a number of statements, even if that number is 1. I'll add it to the remarks though, good suggestion.
