### ISSUE TITLE
Outlining cuts off closing }

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#2128]
Ported from TFS WorkItem: **1037510**

---
## ![outlining](https://cloud.githubusercontent.com/assets/312835/7241936/027720ac-e773-11e4-99a4-7cac9aa95ffe.png)

The closing } in the preview is cutoff half through.

**Comment by tuespetre** [comment]
I would like to grab this one please, it has been driving me a tiny amount of crazy for too long now 😉

**Comment by Pilchie** [comment]
@tuespetre Sure thing!  I can't assign it to someone not in the org, so I'll leave it assigned to me, and remove the `up-for-grabs` label.  Ping me with a PR when you're ready.
