### ISSUE TITLE
IInstanceReferenceExpression API Review

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21284]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/IInstanceReferenceExpression.cs

- We should review Implicit/Explicit from the InstanceRefernceKind
- We should get rid of None 
- At which point we should just have a bool in the API saying IsBase and get rid of InstanceRefernceKind completely

**Comment by 333fred** [comment]
See https://github.com/dotnet/roslyn/pull/21625#discussion_r134554531

**Comment by CyrusNajmabadi** [comment]
Yes.  We can remove IsBaseReference.
