### ISSUE TITLE
ILambdaExpression API Review

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21286]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/ILambdaExpression.cs

- API should be renamed to IAnnonymousFunctionExpression
- Signature should be renamed to symbols

**Comment by sharwell** [comment]
❓ The suggestion to rename to `IAnonymousFunctionExpression` suggests (to me) that we might differentiate between `delegate { }` and `() => {}` forms. Can you clarify if this operation applies to both of these forms, or just to the former?

**Comment by CyrusNajmabadi** [comment]
IAnonymousFunctionExpression  is what all non-named-function expressions would map to.  So ```delegate () { ... }```, ```() => ...```, ```function() ...```, ```sub() ...```.
