### ISSUE TITLE
IForEachLoopStatement, IForLoopStatement, IForWhileUntilLoopStatement, IWhileUntilLoopStatement API Review

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21282]
We need to investigate this , 
- IForLoopStatement should not derive from IForWhileStatement ...etc

**Comment by mavasani** [comment]
I had a chat with @AlekseyTs and I think it would be beneficial if we all first decide on how do we want to represent the VB and C# For loop and then I can work on a proposal:

1. Current shape of single IOperation node following the C# structure and generating synthesized expressions for VB ForTo statement to satisfy this shape.
2. Different IOperation nodes for VB and C# For loops
3. Single IOperation node which has fields for both the C# specific shape (initialization, condition and increment) and VB specific shape (control variable, step value, limit value, etc.)

We also need to discuss how to expose VB user defined operators for object loops.

**Comment by CyrusNajmabadi** [comment]
IForFromToStatement.
IForDon'tKnowStatement.

**Comment by mavasani** [comment]
Fixed now...
