### ISSUE TITLE
ISyntheticLocalReferenceExpression API review 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21298]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/ISyntheticLocalReferenceExpression.cs

- we need to get rid of this API

**Comment by sharwell** [comment]
❓ Is the information available as part of the target symbol of a reference? If so, it sounds like we would not even have a feature gap by removing this.

**Comment by CyrusNajmabadi** [comment]
> If so, it sounds like we would not even have a feature gap by removing this.

That is why we're removing it. :)

**Comment by mavasani** [comment]
This will be removed with #21791
