### ISSUE TITLE
IOmittedArgumentExpression API Review 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21292]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/IOmittedArgumentExpression.cs 

cc/ @gen @dotnet/analyzer-ioperation

**Comment by sharwell** [comment]
❓ Does this represent cases where an argument is omitted for a parameter that specifies a default value in C#, or is it only used for VB?

**Comment by tmat** [comment]
Let's make it internal if there is no work in progress yet.

**Comment by mavasani** [comment]
I see that we already have unit tests for this. @jinujoseph @genlu Do you recall if we decided to remove this interface or approved the current API shape?

**Comment by mavasani** [comment]
We already have unit tests here - it is only used for VB.

**Comment by mavasani** [comment]
I dug a bit more and it seems we generate this Operation node only for *error* cases in *VB* where you have an extra `,` for an optional argument. For example, see here: http://source.roslyn.io/#Roslyn.Compilers.VisualBasic.Semantic.UnitTests/IOperation/IOperationTests_IArgument.vb,715

For similar error case in C#, we generate an IArgument with underlying IInvalidExpression:
```
IArgument (ArgumentKind.Explicit, Matching Parameter: null) (OperationKind.Argument, IsInvalid) (Syntax: '')
        IInvalidExpression (OperationKind.InvalidExpression, Type: null, IsInvalid) (Syntax: '')
          Children(0)
        InConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
        OutConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
```

For valid code where we use default value, we generate an IArgument with ArgumentKind.DefaultValue.

I think we should get rid of this node and VB operation factory should match C# behavior. Let discuss it at design meeting today.

**Comment by mavasani** [comment]
Design Decision:

1. Test late binding scenarios with omitted arguments and verify if we generate these nodes - if so, bring it back to the design discussion
2. If not, remove the IOmittedArgumentExpression API and expose the node as OperationKind.None

**Comment by mavasani** [comment]
@AlekseyTs is correct - we also generate omitted argument for valid dynamic invocation with omitted arguments:

```
Option Strict Off

Class P
    Sub M1(o As Object)
        M2(o,,)'BIND:"M2(o,,)"
    End Sub

    Sub M2(x As Integer, Optional y As Integer = 0, Optional z As Integer = 0)
    End Sub

    Sub M2(x As Double, Optional y As Integer = 0, Optional z As Integer = 0)
    End Sub
End Class
```

Given that `OmittedArgumentSyntax` inherits from `ArgumentSyntax`, I would like to propose that we map omitted argument to an `IArgument` with `ArgumentKind.Default`. User can differentiate between omitted argument and default value argument using the underlying syntax node.

**Comment by jinujoseph** [comment]
@AlekseyTs @DustinCampbell  to review the proposal

**Comment by DustinCampbell** [comment]
> Given that OmittedArgumentSyntax inherits from ArgumentSyntax, I would like to propose that we map omitted argument to an IArgument with ArgumentKind.Default. User can differentiate between omitted argument and default value argument using the underlying syntax node.

Seems reasonable to me.

**Comment by AlekseyTs** [comment]
> Given that OmittedArgumentSyntax inherits from ArgumentSyntax, I would like to propose that we map omitted argument to an IArgument with ArgumentKind.Default.

Could you please clarify the proposal, perhaps with examples of scenarios, the current IOperation tree as we have it today and how the proposal will affect them?

**Comment by mavasani** [comment]
Here are the possible implementations, my proposal is (1), but I am fine with any of these.

1. `IArgument` with `OperationKind.Argument` and `ArgumentKind = ArgumentKind.DefaultValue` and `Syntax = OmittedArgumentSyntax` and underlying argument `Value = null`. Doc comments to clarify that Value can be null for omitted arguments case where we cannot bind to a specific value at compile time.
2. Retain current implementation: `IOmittedArgumentExpression` with `OperationKind.OmittedArgumentExpresion` and `Syntax = OmittedArgumentSyntax`
3. Remove `IOmittedArgumentExpression` and `OperationKind.OmittedArgumentExpresion` return a None operation with `Syntax = OmittedArgumentSyntax`.

**Comment by AlekseyTs** [comment]
I was hoping for examples with specific parents. Is the proposal that this node is exposed only for erroneous method/property invocations and for valid late-bound invocations?

**Comment by AlekseyTs** [comment]
I think it will be strange to run into an IArgument node when there are no such nodes for other arguments. I am leaning towards option 2.

**Comment by mavasani** [comment]
Option 2 sounds fine to me. Yes, the node is only exposed for late bound and error cases where we cannot match it to a default argument. I will send a PR with tests for you to get a better sense.

**Comment by DustinCampbell** [comment]
Sounds good

**Comment by mavasani** [comment]
We have retained the existing API shape and added unit tests with https://github.com/dotnet/roslyn/pull/22444. Closing this issue.
