### ISSUE TITLE
ISizeOfExpression API Review

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21296]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/ISizeOfExpression.cs

- The API should derive from IOperation rather than ITypeOperationExpression 
- Why we need ITypeOperationExpression  ?

**Comment by sharwell** [comment]
Is `ITypeOperationExpression` otherwise used? I would suggest the member in it be called just `Type`, but not sure where to put that.

**Comment by CyrusNajmabadi** [comment]
> Is ITypeOperationExpression otherwise used

Currently ITypeOperation is the root type of ISizeOfOperation and ITypeOfOperatoin.  We don't feel like thse benefit from having a common root type (outside of IOperatoin).  So we're removing ITypeOperation.

>  I would suggest the member in it be called just Type, but not sure where to put that.

IOperation already exposes 'Type' (which for ITypeOfOperation would be System.Type).  We need a way to expose the actual Type instance that the ITypeOfOperatoin is giving you the System.Type for.

**Comment by mavasani** [comment]
Should be fixed with https://github.com/dotnet/roslyn/pull/22222
