### ISSUE TITLE
IStopStatement API Review 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21297]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/IStopStatement.cs 

Why we need this ? 

cc @AlekseyTs  , @dotnet/analyzer-ioperation

**Comment by sharwell** [comment]
💡 If we keep this, we should unify it with C#'s `Debugger.Break();`. If it doesn't get translated to an invocation (and this interface removed), I would suggest renaming it to `IDebugBreakExpression` or similar (and in VB wrapping it as an expression statement).

**Comment by CyrusNajmabadi** [comment]
Because of our desire to not lower if we can avoid it, we'll keep this as an IStopStatement.  We hope that our V2 release can expose more lowering capabilities.  In that world, some lowered tree we would see this gone, and you would only see the Invocation expression.

**Comment by tmat** [comment]
Let's delete the API for now and add a good one later.
