### ISSUE TITLE
INullCoalescingExpression API Review 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21290]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/INullCoalescingExpression.cs 

- API Should be named to ICoalesceExpression

**Comment by sharwell** [comment]
:question: Can you clarify whether you meant `ICoalesceExpression` or `ICoalescingExpression` for the rename?

💭 Consider the following renames:

* `PrimaryOperand` &rarr; `Expression`
* `SecondaryOperand` &rarr; `WhenNull`

**Comment by jinujoseph** [comment]
ICoalesceExpression for the rename and completely agree with other renames

**Comment by CyrusNajmabadi** [comment]
> Can you clarify whether you meant ICoalesceExpression 

We mean ICoelesceExpression (matches C#'s SyntaxKind.CoalesceExpression).

> Consider the following renames:

Those seem reasonable to me.
