### ISSUE TITLE
IThrowStatement API review 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21299]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/IThrowStatement.cs 

Why we have IThrowStatement and IThrowExpression ?

**Comment by sharwell** [comment]
💡 Consider unifying `IThrowStatement` to `IThrowExpression` wrapped in an expression statement (and removing `IThrowStatement`).

:bulb: Consider renaming `ThrownObject` to `Expression`.

**Comment by CyrusNajmabadi** [comment]
@sharwell This is what we're doing.
