### ISSUE TITLE
Incorrect linked file in Scripting.csproj

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#2130]
Is this a problem?
https://github.com/dotnet/roslyn/blob/master/src/Scripting/Core/Scripting.csproj#L28-L33

Shouldn't line 32 say AssemblyIdentityExtensions.cs?

**Comment by ManishJayaswal** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/3dfd4a068b22b894edde1911242c8161c8193984
