### ISSUE TITLE
ILiteralExpression API Review 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21300]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/ILiteralExpression.cs

- We should get rid of Text

**Comment by sharwell** [comment]
I'm not opposed to removing `Text`, but the value as written in source should be consumable.

Make sure to consider cases like 1000000000000000000000000000000000000000 that are literals but have no obvious representation due to overflow.

**Comment by CyrusNajmabadi** [comment]
Note: syntax is always available from operations that are backed from source.  So you can always get back to the original representation (without having to know the original source language).  Actual values will be available if the compiler was able to produce a value for the literal.
