### ISSUE TITLE
Do we need Microsoft.NET.Test.Sdk package to run tests?

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#21313]
This is requested by Rider, I wonder if that is not the case for VS/RS.

**Comment by sharwell** [comment]
I'm not sure I understand the question.

The main items added by Microsoft.NET.Test.Sdk are the UnitTestContainer capability and setting the IsTestProject property. The former is supposed to be the trigger for tests, but several older test adapter implementations do not add it. Roslyn [does add it](https://github.com/dotnet/roslyn/blob/39536105ffaa7752d6cbaac258d7daf9f2ea6763/build/Targets/Imports.targets#L148), so the Microsoft.NET.Test.Sdk package should not be needed for an IDE to know which projects are test projects and which ones are not.

**Comment by alrz** [comment]
I've found this https://github.com/Microsoft/vstest/issues/515 I think that's the issue I'm encountering.

**Comment by Pilchie** [comment]
@ManishJayaswal or @srivatsn  - do you know the right home for this?

**Comment by srivatsn** [comment]
Yes the test SDK does a few things like generate a Main method to keep the compiler happy and sets a few other things. There was an investigation about what we can do to either remove the requirement or make the Test.Sdk a real MSBuild SDK instead of a package. Moving to Microsoft/vstest

**Comment by srivatsn** [comment]
This issue was moved to Microsoft/vstest#986
