### ISSUE TITLE
Design Question : Should we have a special node for ref (C# 7.0 feature)

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#21311]
Out Var https://github.com/dotnet/roslyn/issues/18303 
Patterns  https://github.com/dotnet/roslyn/issues/19927 
Tuple https://github.com/dotnet/roslyn/issues/10856

**Comment by jinujoseph** [comment]
We need to discuss how 'ref expression' is handled in Ioperation https://github.com/dotnet/roslyn/issues/21276#issuecomment-320069805

**Comment by jinujoseph** [comment]
**Design Team Decision**

This is big C# 7 feature around perf , we need to do this. we should look into how bound node exposes and follow the similar pattern. Some thing to consider would be to see if we could add a boolean flag for say IAssignment to day this is ref assignment etc

**Comment by 333fred** [comment]
I like @sharwell's approach here, although it will take a bit of work to stitch up GetOperation to do the correct thing, and will likely be blocked by https://github.com/dotnet/roslyn/issues/21406. The general idea is that for the following code:

```C#
namespace ConsoleApp1
{
    class C1
    {
        int i = 1;

        void M1()
        {
            ref int i2 = ref i;
        }
    }
}
```

Getting the IOperation for `ref i` will return an `IAddressOfExpression` with an `ILocalReferenceExpression` as the `Reference` field.

However, I don't like the name `IAddressOfExpression`. It's too similar to VB's `AddressOf` expression, and in reality VB's `AddressOf` has nothing to do with this interface. We should also add a bool field for whether or not this is a managed reference or not (ie whether or not this was `&i` or `ref i`). My proposal:

```C#
/// <summary>
    /// Represents an expression that creates a reference or pointer value by taking the address of a reference.
    /// </summary>
    /// <remarks>
    /// This interface is reserved for implementation by its associated APIs. We reserve the right to
    /// change it in the future.
    /// </remarks>
    public interface IReferenceCreationExpression : IOperation
    {
        /// <summary>
        /// Addressed reference.
        /// </summary>
        IOperation Reference { get; }

        /// <summary>
        /// Whether the pointer is a managed pointer or not. True for ref expressions, false otherwise.
        /// </summary>
        bool IsManagedReference { get; }
    }
```

**Comment by 333fred** [comment]
Tagging @sharwell for comments as well.

**Comment by CyrusNajmabadi** [comment]
That works for me.

**Comment by CyrusNajmabadi** [comment]
@333fred Let's go with your proposal

**Comment by 333fred** [comment]
@CyrusNajmabadi I have one question on ternary I think would briefly visit in discussion. Should be pretty simple.

**Comment by CyrusNajmabadi** [comment]
Design meeting decision: We wil do this as specified above.

**Comment by mavasani** [comment]
Discussion: do we need this for v1?

**Comment by jinujoseph** [comment]
Assigning to @AlekseyTs  to look into design approach to tackle this

**Comment by AlekseyTs** [comment]
This is what we currently have in compiler:

Symbols: 
-	LocalSymbol has RefKind property, but it looks like ILocalSymbol doesn’t have it, it has boolean IsRef property. 
-	IParameterSymbol has RefKind

Bound nodes:
-	BoundAssignmentOperator has RefKind
-	BoundReturnStatement has RefKind
-	BoundConditionalOperator has Boolean IsByRef property

I discussed this with @VSadov and @agocke. 
Here is our proposal:
-	Add RefKind property to ILocalSymbol, adjust implementation of IsRef and its consumers;
-	Add Boolean property IsRef or IsByRef to IAssignmentOperation, this will only be useful for lowered code and when ref re-assignment comes online;
-	Add Boolean property IsRef or IsByRef to IConditionalOperation.

I think it should be fine to not produce any IOperation node associated with RefExpressionSyntax.

**Comment by jinujoseph** [comment]
remove the Addressof

**Comment by VSadov** [comment]
Re: operation for ref expression -    alternatively it could just return the operation for the operand.  
Just an alternative if returning nothing is inappropriate.
