### ISSUE TITLE
Release configuration + 64-bit + aggressive inlining + generic parameter = incorrect behavior

### ISSUE THREAD

**Issue by branko-d** [dotnet/roslyn#21323]
**Version Used**: 

Reproduced under Microsoft Visual Studio Professional 2017 Version 15.2 (26430.16), NET Framework 4.7.

**Steps to Reproduce**:

Please see the attached Console Application project: [BugAggressiveInlining.zip](https://github.com/dotnet/roslyn/files/1200210/BugAggressiveInlining.zip).

The bug manifests as QuickSort algorithm (implemented within the attached project) working properly in some builds, but not working properly in others. The following factors all need to be present to reproduce the bug - if any of them are omitted, the QuickSort works correctly:

1. Release configuration.

2. Deselected "Prefer 32-bit" (in Project Properties / Build).

3. The presence of `[MethodImpl(MethodImplOptions.AggressiveInlining)]`.

4. The usage of:

        static void SomeMethod<TComparer>(TComparer cmp)
            where TComparer : IComparer<T>
        {
            // ...
        }

   Instead of:

        static void SomeMethod<TComparer>(IComparer<T> cmp) {
            // ...
        }

Here is the actual code...

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;

namespace BugAggressiveInlining {

    class Program {

        static void Main(string[] args) {

            var arr1 = new byte[] { 26 };
            var arr5 = new byte[] { 101, 213, 245, 25, 219 };

            TestArr(arr1);
            TestArr(arr5);

        }

        static void TestArr(byte[] arr) {

            var sorted_by_array_sort = new byte[arr.Length];
            Array.Copy(arr, sorted_by_array_sort, arr.Length);
            Array.Sort(sorted_by_array_sort);

            var sorted_by_qsort = new byte[arr.Length];
            Array.Copy(arr, sorted_by_qsort, arr.Length);
            QuickSort(sorted_by_qsort);

            if (!sorted_by_array_sort.SequenceEqual(sorted_by_qsort))
                throw new InvalidOperationException($"{Environment.NewLine}unsorted:   {string.Join(" ", arr)}{Environment.NewLine}Array.Sort: {string.Join(" ", sorted_by_array_sort)}{Environment.NewLine}QuickSort:  {string.Join(" ", sorted_by_qsort)}");

        }

        static void QuickSort<T>(T[] arr) {
            QuickSort(arr, Comparer<T>.Default);
        }

        static void QuickSort<T, TComparer>(T[] arr, TComparer cmp)
            where TComparer : IComparer<T>
        {
            QuickSort(arr, cmp, 0, arr.Length - 1);
        }

        static void QuickSort<T, TComparer>(T[] arr, TComparer cmp, int left_i, int right_i)
            where TComparer : IComparer<T>
        {
            if (left_i < right_i) {
                var middle_i = Partition(arr, cmp, left_i, right_i);
                QuickSort(arr, cmp, left_i, middle_i - 1);
                QuickSort(arr, cmp, middle_i, right_i);
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static int Partition<T, TComparer>(T[] arr, TComparer cmp, int left_i, int right_i)
            where TComparer : IComparer<T>
        {

            var pivot = arr[left_i + (right_i - left_i) / 2]; // We don't simply use `(right_i + left_i) / 2` because of the danger of overflow.

            do {

                while (cmp.Compare(arr[left_i], pivot) < 0)
                    ++left_i;

                while (cmp.Compare(pivot, arr[right_i]) < 0)
                    --right_i;

                if (left_i <= right_i) {

                    var tmp = arr[left_i];
                    arr[left_i] = arr[right_i];
                    arr[right_i] = tmp;


                    ++left_i;
                    --right_i;

                }

            } while (left_i <= right_i);

            return left_i;

        }

    }

}

```

**Expected Behavior**:

QuickSort reorders the array correctly.

**Actual Behavior**:

QuickSort reorders the array incorrectly (the program throws an exception when it detects that), but only when built in a specific way described above.

**Comment by tannergooding** [comment]
@branko-d, did you check the IL to determine if this is bad codgen caused by the compiler (Roslyn) or if it is bad codegen caused by the runtime (CoreCLR)?

I would generally expect it to be the latter as the compiler doesn't really perform an optimizations with generics/aggressive inlining (or even 64-bit mode), that is all up to the runtime.

**Comment by branko-d** [comment]
Sorry, I'm not familiar enough with IL to check it. Have you been able to reproduce the problem?

Please advise if I should file this somewhere else...

**Comment by tannergooding** [comment]
I haven't checked yet. I was just asking since these issues are generally problems that should be logged on `dotnet\coreclr` (not always the case, but generally).

I (or someone else) will probably get around to checking this sometime in the next few hours and will let you know.

**Comment by tannergooding** [comment]
@branko-d, So I am not currently getting this to repro.

I downloaded the project, switched to release mode, validated that `Prefer 32-bit` was not checked (also validated the program does run as 64-bit).

I did try various versions of the compiler and it still succeeds no matter which I use.

Do you know which version of the .NET Framework you have installed? Also could you provide which OS you are using and the version?

Visual Studio should display your .NET Framework version in the `Help->About` dialog.

**Comment by tannergooding** [comment]
I tested on `Windows 10.0.15063` with `.NET Framework 4.7.02046` on Visual Studio 15.2 and Visual Studio 15.3 Preview 7.

**Comment by branko-d** [comment]
Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.16) Release
VisualStudio.15.Release/15.2.0+26430.16
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Professional

Visual Basic 2017   00369-60000-00001-AA547
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA547
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA547
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA547
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.6.00404.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30503.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper Ultimate 2017.1.2    Build 108.0.20170428.75743
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

TypeScript   2.2.2.0
TypeScript tools for Visual Studio

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.26430.06
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

WiX Toolset Visual Studio Extension   0.9.21.62588
WiX Toolset Visual Studio Extension version 0.9.21.62588
Copyright (c) .NET Foundation and contributors. All rights reserved.

**Comment by branko-d** [comment]
Edition: Windows 10 Home Single Language
Version: 1703
OS Build: 15063.483
Processor: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
Installed RAM: 32.0 GB
System type: 64-bit operating system, x64-based processor

**Comment by gafter** [comment]
The Roslyn compilers don't do anything special with inlining. This sounds like a JIT bug in the runtime.

**Comment by gafter** [comment]
Issue moved to [dotnet/coreclr #16312](https://github.com/dotnet/coreclr/issues/16312) via [**ZenHub**](https://www.zenhub.com/)
