### ISSUE TITLE
ProjectTypeGuids is case-sensitive

### ISSUE THREAD

**Issue by tamlin-mike** [dotnet/roslyn#21322]
See:
https://github.com/0xd4d/dnSpy/issues/475

Expected: VS able to parse hexadecimal values [a-f] disregarding case.
Actual: Seemingly, VS is unable to understand that "1a" and "1A" are equivalent.

**Comment by Pilchie** [comment]
Tagging @srivatsn /  @davkean - what's the right home for this issue?

**Comment by davkean** [comment]
This issue was moved to dotnet/project-system#2694
