### ISSUE TITLE
Use different editorconfig files for build configurations

### ISSUE THREAD

**Issue by xperiandri** [dotnet/roslyn#21332]
I want to have different rule sets for debug and release as I do with `ruleset` files.
In debug mode I have relaxed rules that do not disturb from writing code fast.
The in release mode I have strong rules which team need to follow. So that only when feature is implemented you do cleanup and polish your code.

**Comment by Pilchie** [comment]
So far, we've been thinking about having a VS setting that describes how things are reported during development, but this is an interesting alternative approach.

**Comment by sharwell** [comment]
> In debug mode I have relaxed rules that do not disturb from writing code fast. The in release mode I have strong rules which team need to follow. 

:bulb: The way we do this in Roslyn as well as other projects I work on is mark the affected rules as warnings, not errors. Then on the CI build, we use the "treat warnings as errors" option. The advantage of this approach is it still at least shows the warnings to the users during development. Many times this leads to them staying fixed from the start, so the transition to getting it ready to publish involves little to no work.

**Comment by CyrusNajmabadi** [comment]
Closing out given Sam's solution.
