### ISSUE TITLE
Shipped/unshipped tracking didn't catch default value change

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#21353]
See this change: https://github.com/dotnet/roslyn/commit/8e6cfc0fbe71934a4e9a626ba88880bc93085bdc#diff-1bce888eb29ee49820578536c7d426e1R83

Relates to these issues: https://github.com/dotnet/roslyn/issues/20873 https://github.com/dotnet/orleans/issues/3233

@jasonmalinowski I'll stop by to discuss.
FYI @jaredpar

**Comment by jasonmalinowski** [comment]
@jcouv Is this something you're actively working on?

**Comment by jcouv** [comment]
No. I meant to discuss with you, unless Jared already has. 
We had an API regression which our tooling did not catch. Do we know what happened? Can we tighten up the process to avoid it in the future?

**Comment by jcouv** [comment]
Have lost track of this. I'll close.
