### ISSUE TITLE
[Completion] Implement backspace completion for C#

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#21368]
VB.NET can trigger completion on backspace - for example having an identifier 'Main' and backspacing the n it shows a completion list like typing 'Mai' that's a very handy feature C# is missing currently.

**Comment by Pilchie** [comment]
There is an option to enable this behavior - in VS it's at Tools\Options\Text Editor\C#\IntelliSense.  However, it defaults to off, because people with a C# history tend not to expect it.
