### ISSUE TITLE
'To expression body' should not insert new lines

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#21381]
Version 15.2 (26430.16) Release

I have quite a lot of code like this to which I want to apply the "To expression body" fix:

```c#
private bool foo;
public bool Foo { get { return foo; } private set { Set(ref foo, value); } }
```

Problem is it decides this is what I want:
```c#
private bool foo;
public bool Foo { get => foo;
    private set => Set(ref foo, value);
}
```

No amount of .editorconfig juggling seems to impact this.
Fix in project and fix in folder are really appealing, until you factor in cleaning up every single property.

**Comment by CyrusNajmabadi** [comment]
@jnm2 I can't repro this:  

![useexpressionbody](https://user-images.githubusercontent.com/4564579/29096317-367bfa36-7c49-11e7-96c3-c877db97f3af.gif)

Is there more to your repro?  Thanks!

**Comment by jnm2** [comment]
Crap, I'm so sorry! It's ReSharper.
My love-hate relationship is ridiculous at this point. ReSharper is stupid slow and I want to stop using it, but there's just a list of common activities it's so much better at...

**Comment by CyrusNajmabadi** [comment]
Hey @jnm2 .  Definitely let us know what you'd like to see.  I'll see if i can get around to providing it :)

**Comment by CyrusNajmabadi** [comment]
(Please file as issues).

**Comment by jnm2** [comment]
I keep forgetting whether or not I have ReSharper suspended at any given moment these days. :-/
Maybe a note in the issue template along with asking for the version, to remind me to try it in safe mode and not waste everyone's time?

**Comment by CyrusNajmabadi** [comment]
Enh :)  It's no biggie.
