### ISSUE TITLE
[EE] Namespace not found while evaluating expressions with portable PDB

### ISSUE THREAD

**Issue by r-ramesh** [dotnet/roslyn#21386]
**Steps to Reproduce**:
Create a simple C# Console App, set PDB type to portable in Project Properties > Build > Advanced.

Code Snippet (portable PDB):

```
using System;

namespace ManagedFuncEval
{
    class Program
    {
        public Program MyObjectFunc(Program p)
        {
            return p;
        }
 
        static void Main(string[] args)
        {
            Program p = new Program();
            int x = 1;
        }
    }
}
```

1. Set BP on int x = 1, start debugging
2. Evaluate "new Program()" in Watch Window

**Expected Behavior**:
Successful evaluation

**Actual Behavior**:
error CS0246: The type or namespace name 'Program' could not be found (are you missing a using directive or an assembly reference?)

This only repros with portable PDBs, works fine with normal PDBs.
Note that removing the "using System;" in the code snippet causes the evaluation to work.

**Comment by tmat** [comment]
> This only repros with portable PDBs, works fine with embedded PDBs.

@r-ramesh Do you actually mean it works with Windows PDBs?

**Comment by r-ramesh** [comment]
@tmat Absent-minded mistake, I meant normal PDBs.

**Comment by tmat** [comment]
OK, I can repro. The PDB looks ok, so it must be the EE misinterpreting it.
