### ISSUE TITLE
Misc. issues to address before merging `features/ioperation` into `master`

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#21385]
Address all `// PROTOTYPE(IOperation)` comments, perhaps by opening issues.

CSharpParseOptions.cs: Revert or fix callers that are currently creating an ImmutableArray<string> from IEnumerable<string>.
```
        internal CSharpParseOptions(
            LanguageVersion languageVersion,
            DocumentationMode documentationMode,
            SourceCodeKind kind,
-           ImmutableArray<string> preprocessorSymbols,
+           IEnumerable<string> preprocessorSymbols,
```
MemberSemanticModel.cs: Create factory lazily.
```
+           _operationFactory = new CSharpOperationFactory(this);
```

LambdaFrame.cs / LambdaRewriter*.cs: Lots of changes. Are these changes expected or is the branch stale?

VisualBasicParseOptions.vb: Revert or fix callers that are currently creating an ImmutableArray<string> from IEnumerable<string>.
```
        Friend Sub New(
            languageVersion As LanguageVersion,
            documentationMode As DocumentationMode,
            kind As SourceCodeKind,
-           preprocessorSymbols As ImmutableArray(Of KeyValuePair(Of String, Object)),
+           preprocessorSymbols As IEnumerable(Of KeyValuePair(Of String, Object)),
            features As ImmutableDictionary(Of String, String))
```

MemberSemanticModel.vb: Create factory lazily.
```
+           _operationFactory = New VisualBasicOperationFactory(Me)
```

**Comment by mavasani** [comment]
@heejaechang Do you know of these changes in features/ioperation branch?

**Comment by heejaechang** [comment]
not sure about immutable array thing, but sure we can make operation factory lazy. and sounds like a good idea.

...

about Prototype comment stuff, there are some assert turned off for now, we need to turn them back on. all those assert has the prototype comment.

**Comment by mavasani** [comment]
@333fred Do you have bandwidth to work on this? We need to address this before merge.

**Comment by mavasani** [comment]
> CSharpParseOptions.cs: Revert or fix callers that are currently creating an ImmutableArray from IEnumerable

Verified we are in sync with master

> LambdaFrame.cs / LambdaRewriter*.cs: Lots of changes. Are these changes expected or is the branch stale?

Verified we are in sync with master

> VisualBasicParseOptions.vb: Revert or fix callers that are currently creating an ImmutableArray from IEnumerable.

Verified we are in sync with master

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/22135
