### ISSUE TITLE
Provide an API in persistent service where data is owned by 1 VS process

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#21390]
new persistent service added new functionality to share data between 2 processes for same solution (VS and OOP), but removed one that guarantee only 1 VS process owns the data of same solution.

this made 1 better but broke another such as Todo, Diagnostics, Designer Attribute scanner which rely on the fact that 1 VS owns the data in the persistent service.

we should either move those features to other kind of storage or provide new API in persistent service so those feature can get same guarantee as before on top of new benefit new persistent service provides.

more detail on this https://github.com/dotnet/roslyn/pull/21357

**Comment by heejaechang** [comment]
right now, todo, diagnostics, designer attribute might not work correctly if more than 1 VS is opened for same solution.

**Comment by CyrusNajmabadi** [comment]
Note my comment here: https://github.com/dotnet/roslyn/pull/21357#issuecomment-321125629

> Or, as mentioned before, we could just change things under the covers so that this problem is transparent to the clients using the service. i.e. we could guarantee that anything you wrote in a session would be returned within the same session. Then all our existing clients would not have to be rewritten at all, and we would still be fast for the common case of one session, while correct for the rarer case of multiple sessions.

I think we can keep this existing service and make it safe for multi-process use.

**Comment by CyrusNajmabadi** [comment]
@heejaechang Isn't this something you did?  Do we need this issue anymore?

**Comment by heejaechang** [comment]
yep. it is done.

**Comment by heejaechang** [comment]
done by https://github.com/dotnet/roslyn/pull/21532
