### ISSUE TITLE
CC0023 incorrectly raised to Func<T> with Elvis Operator

### ISSUE THREAD

**Issue by giggio** [dotnet/roslyn#214]
This will incorrectly raise `CS0023` on the 3rd line:

````csharp
void Foo<T>(Func<T> func)
{
    func?.Invoke();
}
````

Message is: `Operator '?' cannot be applied to operand of type 'T'	`

If you add a class restriction to the method `Foo` it will not raise `CS0023`:

````csharp
void Foo<T>(Func<T> func) where T : class
{
    func?.Invoke();
}
````

The target of the operator if `Func<T>`, not `T`, so I believe this is a bug.

**Comment by pdelvo** [comment]
The problem is that Invoke returns T. If func is null what is the type of the return value going to be? It can either be `T` (if T is a class) or `Nullable<T>` if T is a struct. This is why you have to either add a ```where T : class``` or a ```where T : struct```. It does not look like a bug to me.

**Comment by VSadov** [comment]
The nullability requirement for the result of evaluation for the expression statement use (like in your example) has been recently removed, so this is essentially "Fixed".
In the master branch the example compiles.

**Comment by VSadov** [comment]
It is still reproducing in CTP5. I guess the fix did not make it in time for CTP5.

Thanks for reporting this though!
