### ISSUE TITLE
Potential errors in unconditional returns

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#21402]
**Version Used**: Latest source code

On the following files there are unconditional return inside a `foreach` loop. Either the return is expected in which case Linq `FirstOrDefault()` seems like a clearer option or there is an unexpected behavior.
More details on each file below.

In [FindReferencesCommandHandler.cs#L171](https://github.com/dotnet/roslyn/blob/7d91673525b5afa7df85296c0c76d894b19c2999/src/EditorFeatures/Core/FindReferences/FindReferencesCommandHandler.cs#L171), either the `return` after the first element is expected in which case `_synchronousPresenters.FirstOrDefault()` seems clearer or there is a missing `if` before the `return`.

In [EnumerableExtensions.cs#L195](https://github.com/dotnet/roslyn/blob/7d91673525b5afa7df85296c0c76d894b19c2999/src/Compilers/Core/Portable/InternalUtilities/EnumerableExtensions.cs#L195) the `foreach` and following `return` could be merged into one: `return !source.Any();`

In [SolutionCrawlerRegistrationService.cs#L222](https://github.com/dotnet/roslyn/blob/7d91673525b5afa7df85296c0c76d894b19c2999/src/Features/Core/Portable/SolutionCrawler/SolutionCrawlerRegistrationService.cs#L222), based on the comment before the foreach I think this `return false` should be removed so that the iteration to try to find the default provider can occur.

In [PEModuleSymbol.cs#L377](https://github.com/dotnet/roslyn/blob/7d91673525b5afa7df85296c0c76d894b19c2999/src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs#L377), the loop and return could be replaced by `_module.GetCustomAttributesOrThrow(token).Any()`.

In [WorkCoordinator.AsyncWorkItemQueue.cs#L262](https://github.com/dotnet/roslyn/blob/7d91673525b5afa7df85296c0c76d894b19c2999/src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.AsyncWorkItemQueue.cs#L262), based on the comment I think the foreach loop is expected and cannot be replaced with `.FirstOrDefault()` and check to null but I prefer to report it so you guys can be sure.

Cheers,
Amaury

**Comment by Pilchie** [comment]
Can you take a look at IDE reports and then move to other teams?

**Comment by Evangelink** [comment]
Happy to help here if there is some approval from your side.

**Comment by Evangelink** [comment]
Feel free to close this ticket as it is pretty old and the code did change a lot so it might no longer be accurate/valid.
