### ISSUE TITLE
Async void methods might results in unexpected behaviors

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#21403]
**Version Used**: latest source code

The following methods are `async void` methods (aka fire and forget), even if this pattern can be correct in some cases it is most of the time incorrect. Besides I have seen you have a [TaskExtensions.FireAndForget](https://github.com/dotnet/roslyn/blob/7d91673525b5afa7df85296c0c76d894b19c2999/src/Workspaces/Core/Portable/Utilities/TaskExtensions.cs#L21) helper to explicitly indicates this is the expected behavior.

- [FindReferencesCommandHandler.cs#L114](https://github.com/dotnet/roslyn/blob/7d91673525b5afa7df85296c0c76d894b19c2999/src/EditorFeatures/Core/FindReferences/FindReferencesCommandHandler.cs#L114)
- [AnalyzerDependencyCheckingService.cs#L62](https://github.com/dotnet/roslyn/blob/7d91673525b5afa7df85296c0c76d894b19c2999/src/VisualStudio/Core/Def/Implementation/AnalyzerDependency/AnalyzerDependencyCheckingService.cs#L62)
- [NavigateToItemProvider.Searcher.cs#L55](https://github.com/dotnet/roslyn/blob/7d91673525b5afa7df85296c0c76d894b19c2999/src/EditorFeatures/Core/Implementation/NavigateTo/NavigateToItemProvider.Searcher.cs#L55)
- [ResettableDelay.cs#L51](https://github.com/dotnet/roslyn/blob/7d91673525b5afa7df85296c0c76d894b19c2999/src/EditorFeatures/Core/Shared/Utilities/ResettableDelay.cs#L51)

Cheers,
Amaury

**Comment by Pilchie** [comment]
Can you take a look at reports for IDE, then move as appropriate?

**Comment by Evangelink** [comment]
Happy to help here if you all agree these methods need refactoring.

**Comment by Evangelink** [comment]
Feel free to close this ticket as it is pretty old and the code did change a lot so it might no longer be accurate/valid.

**Comment by sharwell** [comment]
This has since been fixed, and an analyzer is in place to avoid future regressions.
