### ISSUE TITLE
Local function in generator causes local vars to lose initialization (w/ optimizations on)

### ISSUE THREAD

**Issue by rspeele** [dotnet/roslyn#21409]
**Version Used**:

2.2.0.61624

**Steps to Reproduce**:

1. Create a new console app. I tried it targeting .NET 4.6.1 and 4.6.2 but I don't think it matters.
2. Write the following code:

```csharp
using System;
using System.Collections.Generic;

namespace Buggles
{
    class Program
    {
        private static IEnumerable<int> Problem(IEnumerable<int> chunks)
        {
            var startOfChunk = 0;
            var pendingChunks = new Queue<int>();

            int GenerateChunk()
            {
                if (pendingChunks == null)
                {
                    Console.WriteLine("impossible in local function");
                    return -1;
                }
                while (pendingChunks.Count > 0)
                {
                    pendingChunks.Dequeue();
                }
                return startOfChunk;
            }

            foreach (var chunk in chunks)
            {
                if (chunk - startOfChunk <= 0)
                {
                    pendingChunks.Enqueue(chunk);
                }
                else
                {
                    yield return GenerateChunk();
                }
                startOfChunk = chunk;
                if (pendingChunks == null)
                {
                    Console.WriteLine("impossible in outer function");
                }
                else
                {
                    pendingChunks.Enqueue(chunk);
                }
            }
        }

        private static void Main()
        {
            var xs = Problem(new[] { 0, 1, 2, 3 });
            foreach (var x in xs)
            {
                Console.WriteLine(x);
            }
        }
    }
}

```

3. Build and run the program with and without optimizations turned on (i.e. in debug and release configuration)

**Expected Behavior**:

In both configurations, the program should print:

```
0
1
2
```

**Actual Behavior**:

When optimizations are enabled, the program prints:

```
0
impossible in outer function
impossible in local function
-1
impossible in outer function
impossible in local function
-1
impossible in outer function
```

**Notes**:

I hit this bug in real world code, and I tried to reduce it to something small that still exhibited the problem. In the process the code lost its meaning and purpose so don't try to make sense of why anybody would write the garbage in my sample.

Fortunately in my case the effect was just a baffling NullReferenceException, but as this sample demonstrates, it could potentially cause a wrong turn in program logic and go undetected.

It seems that with optimizations on, the compiler thinks it can store the struct carrying the local variables `startOfChunk` and `pendingChunks` in a local variable within the generated `MoveNext()` method. This leaves `pendingChunks` uninitialized when entering `MoveNext()` after the first time. With optimizations off it persists the struct as an instance field of the `IEnumerator` which works as expected.

My workaround in production was to break out my local function to a static function and pass in everything it needed explicitly. Interestingly it also worked if I changed it to `Func<Whatever> = () => {...};`, which I would've thought would be treated similarly to a local function.

**Comment by agocke** [comment]
@rspeele Thanks for the detailed repro -- this looks nasty, I will investigate ASAP.
