### ISSUE TITLE
[Question] Recommended way to get info about AD0001

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#21404]
Hi guys,

Is there any recommended way to get some context information about a failing `DiagnosticAnalyzer` in release mode? 
When debugging my analyzer (debug mode) I can have a StackTrace and get some useful information to understand where my code fails but when shipped to the end-users (release mode) we only have a AD0001 warning and the same of the failing analyzer so it is sometimes pretty complex to understand what is going wrong. 

Ideally I would be looking for the line of code of the analyzer that is failing and possibly the code that was analyzed when crashing (maybe not the exact code dump only the class/interface/method/... name).

Cheers,
Amaury

**Comment by sharwell** [comment]
I believe when AD0001 appears in the error list, you can click the arrow to expand it with more information. That will show some context around where the error occurred. This is how I got the additional information listed under Stack Trace in #21202.

**Comment by Evangelink** [comment]
@sharwell Yes I have seen this behavior with my analyzer dll in debug mode but it seems like it is not working with release mode (the behavior is coherent with exceptions stacktrace in release).

**Comment by sharwell** [comment]
AD0001 now reports context information during command line builds. See #30660.
