### ISSUE TITLE
Intellisense for member override candidates should filter out hidden members in base classes.

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#21418]
**Version Used**: Version 15.2 (26430.16).Release
 (though this behavior has been true for as long as I can remember...)

**Steps to Reproduce**:

1. Type the following into a C# project:

```
    public class A
    {
        public sealed override bool Equals(object obj) => throw null;
        public sealed override int GetHashCode() => throw null;
        public sealed override string ToString() => throw null;

        public virtual void Moo() { }
    }

    public class B : A
    {
        public new virtual void Moo() { }
    }

    public class C : B
    {
        public sealed override void Moo() { }
    }

```
2. Put the cursor inside "class C"
3. Type "override" then hit space to bring up suggestions for methods to override.

**Expected Behavior**:

No suggestions. I've overridden everything that's overridable.

**Actual Behavior**:

Suggests `Moo()`. This is `A.Moo()` which is hidden by `B.Moo()` and barring some strange C# syntax I've never heard of, it is impossible for class `C` to override this.

While this is a made up example, there's a real-world scenario where this always hits: subclass `System.Type` (which defines a `Module` property which hides another `Module` property on `MemberInfo`.) No matter how diligently you overrride everything, Intellisense always tells you're not overriding `Module`

**Comment by rchande** [comment]
It looks like calling `SemanticModel.LookupSymbols` with a position within `C` and a container of `A` returns `A.Moo()` even though `B.Moo` should be hiding it. @dotnet/roslyn-compiler  is that the expected behavior?

**Comment by AlekseyTs** [comment]
This is hiding by name and signature, right now name lookup doesn't perform hiding by signature, this is delegated to overload resolution. I see that SemanticModel filters out overridden and hidden methods from a method group (see FilterOverriddenOrHiddenMethods helper), perhaps LookupSymbols API should do the same.
