### ISSUE TITLE
Version of language and framework

### ISSUE THREAD

**Issue by scegg** [dotnet/roslyn#21414]
I think it's a simple question and I cannot find the answer from google and documentations...

Which version of C# is supported in Roslyn while calling "emit"? C# 7.0?
Which version of framework is used in compiled assembly / module from Roslyn? dotnet Framework 4.6? dotnet Core 1.0? Or, same as the project which reference Roslyn nuget package?

Thanks a lot.

**Comment by jcouv** [comment]
For language versions available when parsing, see the [`LanguageVersion`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/LanguageVersion.cs,41ddf4073ec089aa) enum. The language version used for parsing a syntax tree is stored in that syntax tree ([see here](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxTree.cs#L28)).
If I recall correctly, when binding and emitting, the greatest language version from all the relevant syntax tree is used.

As for the second question, the compiler has not understanding or expectations of "framework". It receives source code and a set of references, and as long as all the supporting types for this specific program can be found in the references then it is happy.

**Comment by scegg** [comment]
Thanks for your information.
