### ISSUE TITLE
Ubuntu : Document count is 0 for project opened using OpenProjectAsync using Mono

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#21419]
**Version Used**: 
2.3.1
**Steps to Reproduce**:

1. 
 ```
    var workspace = MSBuildWorkspace.Create();
    workspace.WorkspaceFailed += WorkSpaceFailed;
    Project currentProject = workspace.OpenProjectAsync(projectPath).Result;
    Console.WriteLine(currentProject.Documents.Count());
```
2.  When we use the above code to open a .csproj project, currentProject shows 0 documents when run on **Ubuntu using Mono.**
3.  When we use the same code on Windows 7 machine, currentProject shows a valid value.
4. The **WorkspaceFailed** event subscription shows following error:

**Msbuild failed when processing the file '/home/user/Corona/Roslyn_Version_3_0_0_WithExe/AplModel/AplModel.csproj' with message: Could not load type of field 'Microsoft.Build.BackEnd.Logging.LoggingService:_loggingQueue' (20) due to: Could not load file or assembly 'System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. assembly:System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:<unknown type> member:<none>**

**Expected Behavior**:
The code should show valid documents.

**Actual Behavior**:
workspace.OpenProjectAsync(projectPath).Result gives document count as 0.

**Comment by Pilchie** [comment]
System.Threading.Tasks.Dataflow is a dependency of MSBuild.  Do you have the right right version, or a binding redirect in your .exe.config?

**Comment by Pilchie** [comment]
@DustinCampbell did you have to do anything special for System.Threading.Tasks.Dataflow for Omnisharp?

**Comment by DustinCampbell** [comment]
Yes, we include it right here: https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.MSBuild/OmniSharp.MSBuild.csproj#L23.

**Comment by abhijitparkhi1983** [comment]
@Pilchie 

Following is the .exe.config that I have. Its same which works on Windows machine.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.1.0" newVersion="1.2.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IO.Compression" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Security.Cryptography.Algorithms" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IO.FileSystem" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IO.FileSystem.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Security.Cryptography.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Xml.XPath.XDocument" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Thread" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
Not sure what am i missing here. Do we have to have a  System.Threading.Tasks.Dataflow binding redirect in this config?

@DustinCampbell , does this link suggest that there has to be a similar PackageReference in Mono? Dint get this one

**Comment by abhijitparkhi1983** [comment]
@Pilchie any pointer here? How do we go about it?

**Comment by Pilchie** [comment]
I've never used mono, so I'm not sure in that environment. Sorry.

**Comment by abhijitparkhi1983** [comment]
Hello @Pilchie  and @DustinCampbell ,

I could resolve this particular issue. The latest mono version released on 14th August 2017 had the required .dll under the MSBuild folder. 
Copying this .dll along side the application exe resolves this issue.

But this brings us to a blocker with an error : **Workspace failed with: [Failure] Msbuild failed when processing the file '..\RoslynTestApp.csproj' with message: Operation is not supported on this platform.**

This certainly looks like a Roslyn issue and has been reported at https://github.com/dotnet/roslyn/issues/20848 as well.

Any updates on this?

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard any issues on this in 7 years.
