### ISSUE TITLE
Cannot shutdown VS because unloading projects takes so long.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#21429]
I've been waiting here for minutes (at least 5+).  Right now VS only shows this:

![image](https://user-images.githubusercontent.com/4564579/29191036-25a486d6-7dd1-11e7-9b8a-5c2923bf3768.png)

Why are we unloading projects on shutdown? It doesn't make any sense.  If i'm closing VS then we should be trying to do as little work as possible.  I'm collecting a trace to help determine what's going on here.

**Comment by CyrusNajmabadi** [comment]
Tagging @Pilchie @srivatsn @davkean

**Comment by CyrusNajmabadi** [comment]
Still unloading:

![image](https://user-images.githubusercontent.com/4564579/29191166-acea3708-7dd1-11e7-8d3b-ce1e9caebc06.png)

**Comment by CyrusNajmabadi** [comment]
That gives a good sense of how slow this is.  It's only unloading around 10 projects a *minute*.  With 197 projects, that's around 20 minutes to unload.  It's utterly awful.

**Comment by davkean** [comment]
It is, this is likely two things:

1) Waiting for design-time builds to finish, fixed in 15.5.
2) Waiting for dependency node to finish populating: https://github.com/dotnet/project-system/issues/2640.

**Comment by davkean** [comment]
Almost all of this is aggravated by a long design-time build: https://github.com/dotnet/roslyn/issues/21225

**Comment by Pilchie** [comment]
@davkean are you comfortable closing this in favor of the above issues without a trace?

**Comment by davkean** [comment]
treat this "needs more investigation". TBH, I've spent zero time looking at this scenario - so above is really incidental, I'll dupe it against the previous one Cyrus filed: https://github.com/dotnet/project-system/issues/2211.
