### ISSUE TITLE
Cannot publish ASP.NET 5.2.3 project with "Precompile during publishing" option enabled after updating to Microsoft.CodeDom.Providers.DotNetCompilerPlatform 1.0.6

### ISSUE THREAD

**Issue by phristov** [dotnet/roslyn#21422]
Cannot publish ASP.NET 5.2.3 project with "Precompile during publishing" option enabled after updating to Microsoft.CodeDom.Providers.DotNetCompilerPlatform 1.0.6

It works fine with Microsoft.CodeDom.Providers.DotNetCompilerPlatform 1.0.5

**Version Used**
Visual Studio Enterprise 2015
Microsoft.CodeDom.Providers.DotNetCompilerPlatform 1.0.6
Microsoft.Net.Compilers 2.3.1
Microsoft.AspNet.Mvc 5.2.3

**Error**
3>C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_compiler.exe -v / -p C:\Users\phristov\Source\Workspaces\LSSCANS2.0\Cans.Web\Cans.Web\obj\Debug\AspnetCompileMerge\Source -u C:\Users\phristov\Source\Workspaces\LSSCANS2.0\Cans.Web\Cans.Web\obj\Debug\AspnetCompileMerge\TempBuildDir 
3>ASPNETCOMPILER(0,0): Error ASPRUNTIME: Could not find a part of the path 'C:\Users\phristov\Source\Workspaces\LSSCANS2.0\Cans.Web\Cans.Web\obj\Debug\AspnetCompileMerge\Source\bin\roslyn\csc.exe'.

**Comment by Pilchie** [comment]
cc @Jinhuafei

**Comment by Jinhuafei** [comment]
@phristov We are working on the fix and the issue is tracked through [this GitHub issue](https://github.com/aspnet/RoslynCodeDomProvider/issues/13).
