### ISSUE TITLE
Convert to Interpolated String Quick Action sometimes casts to object

### ISSUE THREAD

**Issue by jamre** [dotnet/roslyn#21427]
**Version Used**: 15.2 (26430.16)

Using the Convert to Interpolated String Quick Action sometimes casts to object if there are syntax errors.

**Expected Behavior**:
Using the quick action on this line:
```cs
var s = string.Format("{0}", DateTime.Now);
```
Usually produces this result:
```cs
var s = $"{DateTime.Now}";
```

**Actual Behavior**:
If the statement terminator is missing (or there is another syntax error in the statement):
```cs
var s = string.Format("{0}", DateTime.Now)
var t = Path.Combine(string.Format("{0}", DateTime.Now);
```
It produces this result instead:
```cs
var s = $"{ (object)DateTime.Now}"
var t = Path.Combine($"{ (object)DateTime.Now}";
```

Additionally, if the line is inside a lambda expression and there are any syntax errors *after* the statement, it will also add the cast.
```cs
Action a = () =>
{
    var s = string.Format("{0}", DateTime.Now);
    x
}
```

Even an object will get cast to an object:
```cs
var s = string.Format("{0}", new object())
```
```cs
var s = $"{ (object)new object()}"
```
In all cases, after the syntax error is corrected, the cast is recognized as redundant.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  I get the right result:

![image](https://user-images.githubusercontent.com/4564579/198749944-5e09d5ec-9ce7-448a-ac6c-1bcdcec72181.png)
