### ISSUE TITLE
Proposal: Allow unsafe code in iterators

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#2143]
Today we disallow any usage of pointers in iterators, due to the issues involved with those pointers and the associated state moving to the heap.  But we allow pointers in async methods (which have similar constraints) with the restriction that awaits can't be used in an unsafe context, e.g. this is allowed:

``` C#
unsafe (...)
{
    ... // no awaits
}
await ...;
unsafe (...)
{
    ... // no awaits
}
```

but this is not allowed:

``` C#
unsafe (...)
{
    await ...;
}
```

We could allow unsafe code in iterators, but with a similar constraint: yield is not allowed in unsafe contexts, e.g. this would be allowed:

``` C#
unsafe (...)
{
    ... // no yields
}
yield return ...;
unsafe (...)
{
    ... // no yields
}
```

**Comment by paulomorgado** [comment]
That makes sense!

**Comment by whoisj** [comment]
how do I thumbs up this?

er... +1!

**Comment by agocke** [comment]
@stephentoub Seems fine to me.

More broadly, do you know of any CLR restrictions about spilling unmanaged pointers across the state machine? AFAIK, that seems the be the main restriction around `async` and `unsafe`, so theoretically the compiler could support spilling unmanaged pointers, as long as there are no issues with doing this in the CLR.

**Comment by stephentoub** [comment]
> More broadly, do you know of any CLR restrictions about spilling unmanaged pointers across the state machine?

Are you asking about enabling not just:
```
unsafe
{
    ... // no yields
}
yield return ...;
unsafe
{
    ... // no yields
}
```
but also:
```
unsafe
{
    ...
    yield return ...;
    ...
}
```
?

If so, even if it could be made to work (e.g. storing the pointers into the state machine), I think it would be dangerous, as it'd be incredibly easy to write bad code, e.g.
```
unsafe
{
    int* state = stackalloc int[1];
    state[0] = 42;
    yield return ...;
    Use(state[0]);
}
```

**Comment by agocke** [comment]
@stephentoub Yup, very dangerous, but it is `unsafe`, to be fair.

**Comment by agocke** [comment]
Certain things, like `fixed`, would still have to be prohibited outright, obviously.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #510](https://github.com/dotnet/csharplang/issues/510) via [**ZenHub**](https://www.zenhub.com/)
