### ISSUE TITLE
Locked file in Windows determinism test

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#21435]
Failure looks like 

CSC : error CS0016: Could not write to output file 'D:\j\workspace\windows_deter---2fa6dcc1\Binaries\Obj\TestUtilities\Debug\Roslyn.Test.Utilities.xml' -- 'The process cannot access the file 'D:\j\workspace\windows_deter---2fa6dcc1\Binaries\Obj\TestUtilities\Debug\Roslyn.Test.Utilities.xml' because it is being used by another process.' [D:\j\workspace\windows_deter---2fa6dcc1\src\Test\Utilities\Portable\TestUtilities.csproj]

**Comment by agocke** [comment]
@jaredpar Could this be caused by multi-targeting? It looks like there's no TFM prefix in the Obj directory so I could see us attempting to write to the same XML file twice...

**Comment by tmat** [comment]
@agocke Dup of https://github.com/dotnet/roslyn/issues/21421

**Comment by tmat** [comment]
And yes, TFM needs to be in the path.

**Comment by jaredpar** [comment]
Looks like it may be this sdk issue

https://github.com/dotnet/sdk/issues/475

**Comment by agocke** [comment]
Closing as dup
