### ISSUE TITLE
Callers should be permitted to elide arguments for out parameters

### ISSUE THREAD

**Issue by ygc369** [dotnet/roslyn#2145]
Sometimes we call functions with out parameters, but don't need the value of these out parameters after calling. So the compiler should allow us to omit out parameters.
For example:
int func(int a, out int b) { ... }
int b; int c=func(1, out b); //Currently we have to code like this even if we don't need b.
int c=func(1, out); //I hope to code like this if I don't need the out parameter. The compiler should add the omitted out parameter automatically while compiling.

**Comment by HaloFour** [comment]
Given that the pattern matching proposal #206 will very likely include a syntax for wildcards I would like to see that used in place of `out` parameters that the caller doesn't care about, e.g.:

```cs
string s = "12345";
bool b = int.TryParse(s, *);
```

**Comment by dsaf** [comment]
@HaloFour 

In that case maybe it could be extended to other similar scenarios, e.g. unused lambda parameters?:

```csharp
public class Program
{
    public static void Main()
    {
        RunToday(* => Console.WriteLine("Not interested in any date."));
    }

    private static void RunToday(Action<DateTime> run)
    {
        run(DateTime.Today);
    }
}
```

**Comment by HaloFour** [comment]
@dsaf Exactly:  #20

**Comment by daveaglick** [comment]
+1 to this. I know there's also talk about first-class tuple support for multiple return value scenarios (I.e., #186), but I'd also like to see some sort of support for optional out parameters in addition to that (or before it, if tuples turns out to get delayed). I hate having to declare variables I never intend to use or having to write wrapper methods.

**Comment by alrz** [comment]
@HaloFour @dsaf ignoring all parameters: `delegate { }` ignoring some of them `(case *, x) => {}` (#6067) the `case` is needed because C# won't allow direct patterns in parameters.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

In C# 7 we added support for *discards*, which addresses the use case, e.g.

`if (int.TryParse(s, out _))`
