### ISSUE TITLE
Review trivia preservation for Move Type to File

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#21459]
**Version Used**: 15.3 Preview 7

:link: Originally identified by `MoveTypeTests.MoveTypeUsings1` in #21439.

### Steps to Reproduce

1. Add the following code to **Outer.cs**

    ```csharp
    // Only used by inner type.
    using System;

    // Unused by both types.
    using System.Collections;

    class Outer
    {
        class Inner
        {
            DateTime d;
        }
    }
    ```

2. Place the caret at the beginning of `class Inner`
3. Apply the **Move type to Outer.Inner.cs** refactoring

### Expected Behavior

Unknown, tagging @kuhlenh @CyrusNajmabadi @dotnet/roslyn-ide.

Also tagging @vweijsters, @pdelvo for thoughts.

#### Outer.cs

```csharp
// Only used by inner type.

// Unused by both types.
using System.Collections;

partial class Outer
{
}
```

#### Outer.Inner.cs

```csharp
// Only used by inner type.
using System;

// Unused by both types.

partial class Outer
{
    class Inner
    {
        DateTime d;
    }
}
```

**Comment by CyrusNajmabadi** [comment]
How do we know '// Only used by inner type.' isn't the file banner?  What's if it's actually:

```c#
// Copyright whatever
using System;

// Unused by both types.
using System.Collections;

class Outer
{
    class Inner
    {
        DateTime d;
    }
}
```

?

Seems like we should preserve the top comment.

I'm nto convinced we even need to care about this.  It seems like an extreme corner case, with a exceptionally simple fix: just delete the comment if you don't want it.

**Comment by sharwell** [comment]
I'm fine with the current behavior.

**Comment by CyrusNajmabadi** [comment]
Also fine with this behavior.
