### ISSUE TITLE
Replace methods with property inserts unnecessary line

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#21461]
**Version Used**: 15.3 Preview 7

:link: Originally identified by `ReplaceMethodWithPropertyTests.TestUpdateGetSet` in #21439.

### Steps to Reproduce

1. Add the following to **C.cs**

    ```csharp
    namespace ConsoleApp5
    {
        class C
        {
            int GetProperty()
            {
                return 0;
            }

            void SetProperty(int property)
            {
            }
        }
    }
    ```

2. Place the caret at the beginning of the identifier `GetProperty`

3. Apply the **Replace 'GetProperty' and 'SetProperty' with property** refactoring

**Expected Behavior**:

```csharp
namespace ConsoleApp5
{
    class C
    {
        int Property
        {
            get => 0;
            set
            {
            }
        }
    }
}
```

### Actual Behavior

⚠️ Make sure to test the behavior when `GetProperty` is *not* the first member of `C`. In this case, a blank line should be ensured before the property.

```csharp
namespace ConsoleApp5
{
    class C
    {

        int Property
        {
            get => 0;
            set
            {
            }
        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/21473
