### ISSUE TITLE
Proposal: Implicit Interfaces

### ISSUE THREAD

**Issue by gregsdennis** [dotnet/roslyn#2146]
<div>
<div>

<h3>The Problem</h3>
Define an interface in such a way that its entire purpose is to represent a set of other interfaces.

Suppose you have two interfaces:
<pre><code>interface IA
{
    void SomeMethod();
}

interface IB
{
    void SomeOtherMethod();
}
</code></pre>
Now suppose you want to create a property on an object into which you can place an object of either type. Since they have no common ancestry, you would have three options (that I've seen, you may devise your own):

<ul>
    <li>declare the property as <code>object</code> and then test/cast in order to access the functionality
<pre><code>class MyImpl : IA, IB
{
    public void SomeMethod() { ... }
    public void SomeOtherMethod() { ... }
}

class MyClass
{
    public object MyProp { get; set; }
}

class MyApp
{
    static void Main(string[] args)
    {
        var myClass = new MyClass { MyProp = new MyImpl() };
        ((IA)myClass.MyProp).SomeMethod();
        ((IB)myClass.MyProp).SomeOtherMethod();
    }
}
</code></pre>
</li>
    <li>create a third interface defined as the combination of the two
<pre><code>interface ICombined : IA, IB {}

class MyImpl : ICombined
{
    public void SomeMethod() { ... }
    public void SomeOtherMethod() { ... }
}

class MyClass
{
    public ICombined MyProp { get; set; }
}

class MyApp
{
    static void Main(string[] args)
    {
        var myClass = new MyClass { MyProp = new MyImpl() };
        myClass.MyProp.SomeMethod();
        myClass.MyProp.SomeOtherMethod();
    }
}
</code></pre>
</li>
    <li>create a proxy type which exposes a single field via independent properties
<pre><code>class MyProxy&lt;T, TA, TB&gt; where T : TA, TB
{
    private object _value;

    public TA AsA { get { return (TA)_value; } }
    public TB AsB { get { return (TB)_value; } }

    public MyProxy(T value) { _value = value; }
}

class MyClass
{
    public MyProxy MyProp { get; set; }
}

class MyImpl : IA, IB
{
    public void SomeMethod() { ... }
    public void SomeOtherMethod() { ... }
}

class MyApp
{
    static void Main(string[] args)
    {
        var myClass = new MyClass { MyProp = new MyProxy&lt;MyImpl, IA, IB&gt;(new MyImpl()) };
        myClass.MyProp.AsIA.SomeMethod();
        myClass.MyProp.AsIB.SomeOtherMethod();
    }
}
</code></pre>
</li>
</ul>
The second option is generally the more preferred option, however, it's not always doable. What if, instead of <code>IA</code> and <code>IB</code>, we use <code>IComparable</code>and <code>IConvertible</code>?
<pre><code>interface ICombined : IComparable, IConvertible {}

class MyImpl : ICombined
{
    // IComparable implementation
    public int CompareTo(object obj) { ... }

    // IConvertible implementation
    public int ToInt32() { ... }
    ...
}

class MyClass
{
    public ICombined MyProp { get; set; }
}

class MyApp
{
    static void Main(string[] args)
    {
        var myClass = new MyClass { MyProp = new MyImpl() };
        var comparison = myClass.MyProp.CompareTo(new object());
        var newInt = myClass.MyProp.ToInt32();
    }
}
</code></pre>
This only works for classes which specifically implement the <code>ICombined</code> interface. You would not be able to assign types like <code>int</code>, <code>double</code>, and<code>string</code>, each of which implement both <code>IComparable</code> and <code>IConvertible</code>.
<h3>The Solution</h3>
We introduce a new usage of the <code>implicit</code> keyword for interfaces.
<pre><code>implicit interface ICombined : IComparable, IConvertible {}
</code></pre>
This tells both the compiler and the run-time that any class which implements both <code>IComparable</code> and <code>IConvertible</code> can be interpreted as implementing <code>ICombined</code>.

The remainder of the code could stay the same, but now, in addition to explicit implementations of <code>ICombined</code> we could also assign any type which implements both <code>IComparable</code> and <code>IConvertible</code>, including <code>int</code>, <code>double</code>, and <code>string</code>.
<pre><code>class MyApp
{
    static void Main(string[] args)
    {
        var myClass = new MyClass { MyProp = 6 };
        var comparison = myClass.MyProp.CompareTo(new object());
        var newInt = myClass.MyProp.ToInt32();

        myClass.MyProp = "example";
        var newComparison = myClass.MyProp.CompareTo(new object());
        ...
    }
}
</code></pre>
Additionally, you could use this new interface to define a collection of such objects:
<pre><code>var list = new List&lt;ICombined&gt; { 6, "string" };
</code></pre>
Defining an interface this way, it becomes retroactive. That is, types which implement all base interfaces for the implicit interface also are said to implement the implicit one.
<h3>The Rules</h3>
<ol>
    <li>An implicit interface may combine any number of interfaces.</li>
    <li>An implicit interface may not define any additional functionality. That is, it must be empty.</li>
</ol>
That's really it.

Finally, the run-time will have to do some type checking, which it should do already for the <code>is</code> and <code>as</code> keywords. It wouldn't need to know <em>all</em> implicit interfaces that a type implements, it would just need to check as requested.
<pre><code>var implemented = 6 is ICombined;
</code></pre>
This basically asks, "Does the type of <code>6</code>, which is <code>int</code>, implement <code>ICombined</code>?" To determine that, it sees that <code>ICombined</code> is an implicit interface so it asks, "Does it implement all of the interfaces implmented by <code>ICombined</code>?" So it's equivalent to writing:
<pre><code>var implemented = 6 is IConvertible &amp;&amp; 6 is IComparable;
</code></pre>
Simple field and property assignments would be compiler-verifiable.
</div>

<h2></h2>

</div>

**Comment by HaloFour** [comment]
The compiler might be able to sneakily handle that within the code that it compiled itself but it couldn't affect how other assemblies might treat that type.  To make the CLR recognize `int` as an `ICombined` would require changes to the runtime.

**Comment by dsaf** [comment]
Is it related to intersection types?

**Comment by gregsdennis** [comment]
@dsaf, not really, but I can see the proximity to that idea.

The concept behind this is closer to type verification by implementation.  I remember reading about a feature that some languages have where the class is defined not by some concrete Type concept, but rather by the functionality that the class provides.  By this, a class can be considered to implement an interface simply by implementing the contract it states (whereas C# requires you to explicitly state you're implementing the interface, even if the contract happens to match some other interface).

This could considered be a partial implementation of that feature, but still keeping to the ideals which already exist in C#.

**Comment by gregsdennis** [comment]
@HaloFour,  I was going to say that the CLR wouldn't have to change, citing that

    var implemented = 6 is ICombined;

could be converted by the compiler into

    var implemented = 6 is IConvertible && 6 is IComparable;

before translating to IL.

However, now that I think about it further, it would still need to have a type for any variable which holds an `ICombined` value.  Otherwise, it would have to use `object` and inject a lot of casts to switch between the various interfaces when it needs to process the value.  That could lead to other issues.

Regarding use in other assemblies, those assemblies would have to reference this one to get the type definition of `ICombined`.  How would this be a problem for those assemblies?

**Comment by HaloFour** [comment]
You could handle this via a helper method that does some reflection (obviously caching the results).  I actually had some incubator project some years back to provide a duck-typing helper method that would construct a concrete proxy class in a dynamic assembly that would implement the interface members and point them to compatible members of the target type.  It worked nice but it had the same issues where the proxy type isn't the same as the target type and you can't convert between them.  The compiler would have the same issue.  If it emitted a synthetic type the instance is no longer the original type.  You couldn't pass that `ICombined` to another method and cast it to an `int`.

**Comment by bondsbw** [comment]
@gregsdennis 
>  An implicit interface may not define any additional functionality. That is, it must be empty.

In that case it might make more sense to remove the braces:

```c#
implicit interface ICombined : IComparable, IConvertible;
```

**Comment by gafter** [comment]
I wonder if *intersection types* would be a better fit, since there is little reason to give a name to the combination.

**Comment by benaadams** [comment]
Have lots of these types in https://github.com/dotnet/coreclr/issues/2179 that require naming for ease of use.

**Comment by Thaina** [comment]
I would prefer that we could alias and cast or check for a group of type than making new implicit interface

For solving your problem it would better if we just

```
using ICombined = (IConvertible,IComparable); 
```
```
if(obj is (IConvertible,IComparable))
   return obj as (IConvertible,IComparable);
```
```
var list = new List<(IConvertible,IComparable)>();
```

Syntax is `(type,type)` or maybe `(type & type)` and `(type | type)`

But it would require CLR support

**Comment by gregsdennis** [comment]
@Thaina, I think your idea is good.  I like the idea of declaring the shorthand in the using statement.

I think the `(type | type)` syntax would explain the concept better in code.  It is literally "this or that type."

**Comment by HaloFour** [comment]
The `(A, B)` syntax is proposed for tuples.  I like `(A & B)` since the intersected type would have to implement both interfaces.  The concept of `(A | B)` is interesting, a type that implements either interface and the consumer can only access shared members. Java does have limited typing like this in exception handlers, e.g. `catch (IOException | SQLException exception) { }`.

I wonder how much of either concept that the compiler could implement without CLRsupport.  There are tricks that the compiler could do within a method, but it would have to be pretty limited.

**Comment by gregsdennis** [comment]
@HaloFour, you are correct: the desired syntax for this should be `(A & B)`.  (Early morning; brain not booted.)

**Comment by aluanhaddad** [comment]
Intersection types would add a great deal of expressiveness to the language. I really want to see this implemented and I'm really happy to see renewed interest. This would allow for much more powerful and expressive consumption of generic APIs and allow for powerful, typesafe ad hoc cross axial classification of types. I think the `&` syntax is a good choice and has worked out very well in languages like TypeScript. 

As for the question of declaring a name for some intersection type, I think the `using` syntax would  provide that intuitively.

**Comment by Thaina** [comment]
I have seen many proposal about intersect/union type at `where` clause. And I think it all could be relate to `trait` too

Should we have some thread or tag to sum up all these kind of proposal as `generic enhancement` or `type constraint` ?

**Comment by aluanhaddad** [comment]
@Thaina the problem is that
```C#
where T: IComparable, IEquatable
```
works very well already for specifying intersecting type constraints. It is impossible to call such a method (with resorting to dynamic) without casting to a type implementing both interfaces. Such a definition may not be available, and if it is it is still not ideal. I would welcome a thread gathering ideas for these proposals, but it is about much more than specifying generic constraints.
Basically, 
Union Types would be very useful in generic constraints. 
Intersection types would be very useful for _consuming_ generic methods and for pattern matching.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #344](https://github.com/dotnet/csharplang/issues/344) via [**ZenHub**](https://www.zenhub.com/)
