### ISSUE TITLE
Recent changes not being published to myget feed

### ISSUE THREAD

**Issue by Cisien** [dotnet/roslyn#21471]
**Version Used**: 3.0.0-dev-61717-03

**Steps to Reproduce**:

1. https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.CSharp.Scripting

**Expected Behavior**:
Classes in this package have been updated with the last week, I am expecting a recent build to be available with these changes
**Actual Behavior**:
Nuget packages on the myget nightly feed for many roslyn packages have not been updated in many months.

**Comment by tannergooding** [comment]
@cisien, it isn't obvious from the feed, but there are packages being uploaded nightly.

The feed itself only shows the latest version at the top (v3.0.0) and not necessarily the last uploaded package. As we are not actively doing work in any branches that are v3.0 or higher, there hasn't been any builds uploaded recently.

Each branch contains a `Version.props` file that lists the version moniker for packages produced by that branch: https://github.com/dotnet/roslyn/blob/master/build/Targets/Versions.props#L21

For example, master is currently producing `2.6.0-beta1` packages, and the last package was uploaded last night: https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.CSharp.Scripting/2.6.0-beta1-62012-01

FYI. @jaredpar, @Pilchie, @jasonmalinowski. Maybe a small document that lists branches we are currently publishing and their version moniker would be useful.

**Comment by Cisien** [comment]
Thanks. Having some kind of indicator on which version is current or which package version 'master' currently publishing to would be quite helpful.

**Comment by jaredpar** [comment]
This file contains the documentation on which branch is publishing where with which versions

https://github.com/dotnet/roslyn/blob/master/build/config/PublishData.json

**Comment by tannergooding** [comment]
@jaredpar, maybe we should have a small blurb about that on our README.MD?

It's info customers want/need, but they currently have no way of determining that they should look there to find it.

**Comment by jaredpar** [comment]
I haven't updated the README because this is still a bit of a work in progress. Once we settle on this being the path forward I will update the docs.

**Comment by jasonmalinowski** [comment]
@jaredpar You unlisted these as best you could, right?
