### ISSUE TITLE
Error CS0227 doesn't show up for Local Functions

### ISSUE THREAD

**Issue by am11** [dotnet/roslyn#21485]
**Version Used**: 
v2.2.0.61624 (VS 2017.2)

**Steps to Reproduce**:

```c#
void A()
{
    var bytesA = A1();
    var bytesB = B();

    unsafe byte[] A1()         //      <-- no CS0227
    {
        var bytes = new byte[sizeof(int)];
        fixed (byte* ptr = &bytes[0])
        {
            *(int*)ptr = sizeof(int);
        }
        return bytes;
    }
}

unsafe byte[] B()            //   <--- CS0227
{
    var bytes = new byte[sizeof(long)];
    fixed (byte* ptr = &bytes[0])
    {
        *(long*)ptr = sizeof(long);
    }
    return bytes;
}
```

**Expected Behavior**:
When compiler switch is not provided, CS0227 should show up for local functions saying:

> Error	CS0227	Unsafe code may only appear if compiling with /unsafe

matching the behavior of regular methods.

**Actual Behavior**:
The project compiles without `/unsafe`, without raising any error or warning, if consumer wraps all the unsafe code in a local function.

**Comment by jcouv** [comment]
FYI @agocke
