### ISSUE TITLE
Feature Request: Offer built-in fix to convert static call to extension method to instance call

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#21483]
It would be useful to see a built-in codefix to use instance-style syntax for extension methods when a static-style one is being used. For example, given

```cs
var first = Enumerable.First(items);
```

the name of the extension class (`Enumerable`) would be grayed out. When the user has the cursor anywhere in `Enumerable.First` and hits Ctrl+., a codefix would pop up and offer to convert to

```cs
var first = items.First();
```

This is very useful when you are refactoring and turning non-extension static methods into extension ones. (The example doesn't demonstrate this the best since `Enumerable.First` will always be an extension method, but I wanted to give a quick example.)

**Comment by CyrusNajmabadi** [comment]
Unlikely to do this due to lack of feedback.
