### ISSUE TITLE
Type of invalid expression prepended with ! is inferred as object

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#21486]
**Repro:** ([demo at sharplab.io](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEDMACFAmDBhDAbwFgAoDCrTFAFgwFkBGACgEoizKuMA3CBDADMA9sIwBeDAEsAdnwA2UgCYBRAB4AHBHChQpwmQG5O3ClMEZmI4e0IYAviYqPylJ1Sx162Nh1em+AWsJDABCWQVldS0dPQNjf25zS2tbB3cXeyA==))

```cs
public class C {
    public void M1() {
        var foo = invalidExpression;
        if (foo) { }
    }
    
    public void M2() {
        var foo = !invalidExpression;
        if (foo) { }
    }
}
```

**Expected Behavior:** One error is produced for each method at the site of `invalidExpression`.

**Actual Behavior:** For `M2`, another error is created at the usage of `foo` inside the conditional.

```
error CS0266: Cannot implicitly convert type 'object' to 'bool'. An explicit conversion exists (are you missing a cast?)
```

**Comment by Pilchie** [comment]
This is actually a compiler fault tolerance issue.

**Comment by jcouv** [comment]
Fixed in the quarterly release following version 15.5.

**Comment by jcouv** [comment]
@jamesqo Thanks for reporting this issue :-)
