### ISSUE TITLE
How to reliably crash CSC with Linq

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#21484]
**Version Used**: 
Visual Studio 2017 Update 3 Preview 7

**Steps to Reproduce**:
1.  Create a new C# outlook VSTO addin 

2. Change the two USINGS at the top FROM:
using Outlook = Microsoft.Office.Interop.Outlook;
using Office = Microsoft.Office.Core;
TO:
using Microsoft.Office.Interop.Outlook;
using Microsoft.Office.Core;

3. Add this code:
        private void ThisAddIn_Startup(object sender, System.EventArgs e)
        {
            var MailItems = (from object x in Selection where x is MailItem select (MailItem)x).ToList();
        }

4.  Notice that "Selection" is a type (not a property) so this should generate a warning/error because it isn't valid code.  Instead, it causes the compiler to exit with code -2146232797.

**Expected Behavior**:
I should get a warning/error saying something is wrong with that query.

**Actual Behavior**:
I get a cryptic CSC error code.

**Comment by jcouv** [comment]
@TonyValenti Thanks for the details. I was able to repro.

**Comment by jcouv** [comment]
Fix pending review.

**Comment by jcouv** [comment]
Fix is merged for 15.5
