### ISSUE TITLE
Simple code does not compile in VS2017 Preview

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#21488]
**Version Used**: 
Microsoft Visual Studio Enterprise 2017 Preview
Version 15.3.0 Preview 7.1

**Steps to Reproduce**:

1. Create a new Class Library application
2. Set the Target Framework to .NET Framework 4.7
3. Add the following code:

```
using System.Collections.Generic;

namespace ValueTupleLanguage
{
	public class Class1
	{
		public object A()
		{
			return 5.ToThingy();
		}
	}

	public static class Ext
	{
		public static IEnumerable<(string a, int b)> ToThingy(this int x)
		{
			return null;
		}
	}
}
```
4. Compile

**Expected Behavior**:
```
1>------ Build started: Project: ValueTupleLanguage, Configuration: Debug Any CPU ------
1>  ValueTupleLanguage -> C:\Temp\ValueTupleLanguage\ValueTupleLanguage\bin\Debug\ValueTupleLanguage.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Actual Behavior**:
```
1>------ Build started: Project: ValueTupleLanguage, Configuration: Debug Any CPU ------
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Additional Notes**:
* This project compiles fine in Visual Studio 2017 15.2.

**Comment by mafshin** [comment]
You need to have `System.ValueTuple` package installed.

```
Install-Package System.ValueTuple
```

**Comment by yaakov-h** [comment]
`System.ValueTuple` is already included in .NET Framework 4.7.

That also wouldn't explain why the project builds in 15.2 but not in 15.3.

**Comment by mafshin** [comment]
@yaakov-h, sorry my target was selected as NETStandard 1.4.

I successfully compiled your code against **.NET 4.7** with **VS 15.3.0 Preview 7.1** without any problem.

Can you share the whole project?

**Comment by jcouv** [comment]
@yaakov-h Could you zip and share your project? I was not able to repro either. Thanks

**Comment by yaakov-h** [comment]
@jcouv unfortunately I haven't been able to re-repro either, even on the same machine.

It could have been an intermittent or environmental bug, but I have absolutely no idea what could have caused that so reliably in the 10 minutes it took me to put this bug report together, and then not at all since.

I blame cosmic rays.

**Comment by jcouv** [comment]
@yaakov-h Are you still on the same version? Chances are this was fixed by an update. 
I'll go ahead and close the issue. Feel free to reopen if you run into this again. Thanks
