### ISSUE TITLE
[Req] Modify Type to have operators (`==` & `!=`)

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#2149]
If the type `System.Type` supported the operators `=` and `<>`. We then could use the `Select Case` to do a matching over types.

For example [Portable\SymbolDisplay\ObjectDisplay\FormatPrimative](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/SymbolDisplay/ObjectDisplay.vb#L37) rewritten to use it.

```vb
       Public Function FormatPrimitive(obj As Object, options As ObjectDisplayOptions) As String
            If obj Is Nothing Then Return NullLiteral

            Dim type = obj.GetType()
            If type.GetTypeInfo().IsEnum Then type = [Enum].GetUnderlyingType(type)
 
            Select Case type
                Case GetType(Integer)  : Return FormatLiteral(DirectCast(obj, Integer), options)
                Case GetType(String)   : Return FormatLiteral(DirectCast(obj, String), options)
                Case GetType(Boolean)  : Return FormatLiteral(DirectCast(obj, Boolean))
                Case GetType(Char)     : Return FormatLiteral(DirectCast(obj, Char), options)
                Case GetType(Byte)     : Return FormatLiteral(DirectCast(obj, Byte), options)
                Case GetType(Short)    : Return FormatLiteral(DirectCast(obj, Short), options)
                Case GetType(Long)     : Return FormatLiteral(DirectCast(obj, Long), options)
                Case GetType(Double)   : Return FormatLiteral(DirectCast(obj, Double), options)
                Case GetType(ULong)    : Return FormatLiteral(DirectCast(obj, ULong), options)
                Case GetType(UInteger) : Return FormatLiteral(DirectCast(obj, UInteger), options)
                Case GetType(UShort)   : Return FormatLiteral(DirectCast(obj, UShort), options)
                Case GetType(SByte)    : Return FormatLiteral(DirectCast(obj, SByte), options)
                Case GetType(Single)   : Return FormatLiteral(DirectCast(obj, Single), options)
                Case GetType(Decimal)  : Return FormatLiteral(DirectCast(obj, Decimal), options)
                Case GetType(Date)     : Return FormatLiteral(DirectCast(obj, Date))
            End Select

            Return Nothing
        End Function
```

**Comment by HaloFour** [comment]
System.Type already defines `==` and `!=` operators.  Maybe this is a limitation of VB.NET syntax?

Also, haven't heard much about VB.NET design decisions.  Assuming they're considering the same language enhancements as C# I would think that this functionality would be covered by pattern matching.

**Comment by AdamSpeight2008** [comment]
@HaloFour This the error report, if try and use it as I described.
> BC30452	Operator '=' is not defined for types 'Type' and 'Type'.

**Comment by HaloFour** [comment]
@AdamSpeight2008 Looks like they were added in .NET 4.0:

https://msdn.microsoft.com/en-us/library/system.type.op_equality(v=vs.110).aspx

Your `Select Case` syntax also works fine in VB.NET when targeting that framework.

**Comment by AdamSpeight2008** [comment]
The project is a PCL.

**Comment by HaloFour** [comment]
Oh, well, in that case, wouldn't this be an issue for the CoreFX team?  The compiler already supports the operator if it's there.

**Comment by AdamSpeight2008** [comment]
@HaloFour 
(Core-CLR Post](https://github.com/dotnet/coreclr/issues/764)

**Comment by gafter** [comment]
Closing as external (and probably should be resolved there too as already fixed).

This proposal does not properly handle subtyping, but we'll consider that for the next language update with pattern matching.
