### ISSUE TITLE
move back to ImmutableArray once json.net issue is solved

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#21498]
we want to use ImmutableArray in our interfaces between VS and OOP. but ImmutableArray converter is not supported in all versions of json.net and sometimes, a version that doesnt support ImmutableArray got loaded to VS and cause features to break.

until we figure out how to fix this issue, we will use most safe collection (IList) in the interfaces for now, and then move back to immutable array once it is fixed.

**Comment by CyrusNajmabadi** [comment]
Closing out.  using IMmutableArray is totally supported.
