### ISSUE TITLE
Limit tooltip quickinfo size

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#21493]
It's possible for us to create giant quickinfo tooltips in cases where there are a lot of errors at the position or a complex generic type is instantiated. We should consider ways to limit the size of the tooltip so it does not display text off the screen.

**Comment by gundermanc** [comment]
This sounds like something we should do in the IDE side by default. Filed: https://devdiv.visualstudio.com/DevDiv/_workitems?id=562995

**Comment by CyrusNajmabadi** [comment]
Closing out as this moved to editor.
