### ISSUE TITLE
Generalized async return VerificationException

### ISSUE THREAD

**Issue by palladin** [dotnet/roslyn#21500]
**Version Used**: 
C# 7 using .net framework 4.5.2
**Steps to Reproduce**:

1. Create a custom async method builder 
[AsyncMethodBuilder(typeof(CustomMethodBuilder<>))]
2. 
Implement AwaitOnCompleted, AwaitUnsafeOnCompleted with a custom interface like
where TAwaiter : IFoo
3. 
try to await an awaiter that doesn't implement IFoo

**Expected Behavior**:
Compile error

**Actual Behavior**:
---- System.Security.VerificationException : Method Eff.Core.CustomMethodBuilder`1[System.Int32].AwaitUnsafeOnCompleted: type argument 'MyTestType`1[System.Int32]' violates the constraint of type parameter 'TAwaiter'.

**Comment by jcouv** [comment]
FYI @cston

**Comment by cston** [comment]
@palladin thanks for reporting this issue.
