### ISSUE TITLE
IDE0009 suggested incorrectly in nameof expression used to initialize static member in VS 15.3

### ISSUE THREAD

**Issue by Tan90909090** [dotnet/roslyn#21519]
**Version Used**: VS2017 15.3.0

**Steps to Reproduce**:
1. Open `Opetions`, show `Text Editor -> C# -> Code Style -> General` tab, set `Qualify property access with 'this'` option to `Prefer 'this.'`
2. Create Visual C# Console App Project
3. Copy and paste following code:
```cs
class Program
{
    public int Foo { get; set; }
    public static string Bar = nameof(Foo); // IDE0009 "Add 'this' or 'Me' qualification." suggested here

    static void Main(string[] args)
    {
    }
}
```

**Expected Behavior**:
IDE0009 is not suggested.

**Actual Behavior**:
IDE0009 is suggested.
If I add "this" qualification, I get CS0026 `Keyword 'this' is not valid in a static property, static method, or static field initializer`.

I encountered this issue in real project, which uses Dependency Property: 
```cs
using System.Windows;
class SomeClass : DependencyObject
{
    public bool IsExpanded
    {
        get => (bool)this.GetValue(IsExpandedProperty);
        set => this.SetValue(IsExpandedProperty, value);
    }

    public static readonly DependencyProperty IsExpandedProperty = DependencyProperty.Register(
        nameof(IsExpanded), // IDE0009 suggested here
        typeof(bool),
        typeof(SomeClass),
        new PropertyMetadata(false));
}
```

**Comment by Pilchie** [comment]
Can you take a look at the PR and make sure this gets in?

**Comment by Tan90909090** [comment]
I'm sorry, but I don't know Roslyn code so I can't mention about PR's changes.
However, I tried [PR's Roslyn](https://github.com/dotnet/roslyn/pull/21528/commits/32f3bfbe00d9278575150ca87af3eafcdbf4cb30). I confirmed this issue have been fixed.
Thanks!

**Comment by eriawan** [comment]
@Tan90909090 
Then this issue should be closed. 🙂 

cc @Pilchie

**Comment by sharwell** [comment]
@Tan90909090 @eriawan I believe the comment from @Pilchie was asking @CyrusNajmabadi to take a look and make sure the pull request gets merged in a timely manner. It doesn't do any good for people to send us PRs if we don't get them merged! :smile:

**Comment by eriawan** [comment]
@sharwell 
Agree! Thanks for the reply 👍
