### ISSUE TITLE
Rosyln team should offer "in-place" guidance to help external contributors fix issues.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#21536]
Hi @Pilchie I have had the pleasure of submitting a couple of issues and your name always shows up to tag, organise and assign them. I was really happy that even one bug I reported [#20837](https://github.com/dotnet/roslyn/issues/20837) was assigned and promptly squished!

Ever since that happened I've been motivated to keep reporting issues because I know someone will look at them and even fix them, which is really cool!

But I want to do more. To report the issues, and to **try fixing them myself** (especially for the simpler ones). So towards that end, this "feature request" targets the Rosyln **development process** rather than the actual product itself.

In short, **every time a Rosyln team member reviews an issue and decides to work on it, they should offer "in-place" guidance by commenting on the issue with details to help us external contributors attempt a fix ourselves**. I imagine it would be something like:

1. The code for the bug/feature-request is here and here and here (i.e links to the source files so we can jump straight to it).

2. When touching that code, remember X, Y and Z (i.e. externalize some of the institutional knowledge you guys have gathered over the years working on Rosyln).

3. If you are a first time contributor, go read this, download that, sign this, etc (i.e. help someone get started).

4. After you are done, make sure you do this and that, then finally this (i.e. help someone get through the critical step of finally submitting a pull request).

Details for 1 and 2 would change from issue to issue but 3 and 4 are boiler plate and could be pasted in for convenience.

I am keenly aware that this probably gives you guys more work, but I think it would be a good investment, because over time, more of us out here who want to contribute will be able to do so, giving you guys more time to work on the really big stuff 😄

If I am not off-base here and this resonates with you, then I would like to get guidance like the above so I attempt a fix for issue [#21339](https://github.com/dotnet/roslyn/issues/21339). I am sure @CyrusNajmabadi will volunteer to help 😃

**Comment by Pilchie** [comment]
Hi @ericmutta 

Thanks for the request - I'll pass it along to the team.  I can't promise that we'll remember to do it always, but it's worth aspiring to.

On the other hand, if you do want to try tackling *particular* issues (like #21339), just let us know, and we can generally provide specific guidance about how to approach that particular issue.  If you don't have a particular issue in mind, but would like to help, @sharwell has also been curating a bit of a list of relatively simple issues for newcomers to look at as a way of getting their feet wet and themselves familiar with working in Roslyn.

Glad to hear that you want to get involved!

**Comment by sharwell** [comment]
> @sharwell has also been curating a bit of a list of relatively simple issues for newcomers to look at as a way of getting their feet wet and themselves familiar with working in Roslyn

I don't have any on *my* list right now because I want to make sure to help the people who already submitted solutions get them merged before I add more issues. :smile: There's been some talk between a few members of different teams about ways to improve the ability of new contributors to find these issues in a subject area that particularly interests them. @terrajobst is keeping a watch on some of these ideas and hopefully in the next few months we can lay out some more details about how people can find things they really want to try working on.

**Comment by Pilchie** [comment]
Closing this, but I did mail the team about it yesterday.

**Comment by ericmutta** [comment]
@pilchie many thanks! I was able to try out the PR process yesterday and now with exactly one successful PR under my belt, I can now try some more :-)

> @sharwell There's been some talk between a few members of different teams about ways to improve the ability of new contributors to find these issues in a subject area that particularly interests them.

Glad to hear you guys have been talking about it. I think the easiest way to start is to target the people already reporting issues (especially bug reports) as they already have context and motivation. With the email @pilchie sent out, I figure we will see positive developments over the next few months.

I appreciate both your efforts and thanks for responding!

**Comment by sharwell** [comment]
> I think the easiest way to start is to target the people already reporting issues (especially bug reports) as they already have context and motivation.

This is really interesting, and definitely something to keep in mind moving forward. What I don't currently know (but wish I did) is how many people who file issues are actually interested in trying to fix those issues themselves. If that number is high, then your suggestion would be a big improvement to our daily work. :smile:

**Comment by ericmutta** [comment]
> @sharwell What I don't currently know (but wish I did) is how many people who file issues are actually interested in trying to fix those issues themselves. If that number is high, then your suggestion would be a big improvement to our daily work.

😄 I imagine it certainly would! I think for something like Rosyln you will find anyone who has tinkered enough to notice when it misbehaves would probably be interested in trying to fix the issue, if given pointers right there in the issue's comments (as per the suggestion in the first comment of this issue).

Take me for example...I have been using Visual Studio since before it was called Visual Studio (i.e in the VB 5/6 days). That's 20 years of Visual Studio. If given the chance to write code that could ship in Visual Studio vNext, would I take it? **ABSOLUTELY** I would make sure they noted it on my tombstone too (you know "Father, Husband, Visual Studio Contributor").

In fact as a first go, for issue [#21339](https://github.com/dotnet/roslyn/issues/21339), if you can point me in the right direction so I can find the code that VB uses for the rename refactoring, I would take a stab at it (as I mentioned in that issue, getting lost while rummaging through the code is the biggest hurdle for external contributors).
