### ISSUE TITLE
How to get an instance of  Microsoft.CodeAnalysis.Solution for the solution already loaded in the current Visual Studios instance

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#21541]
**Version Used**: 
2.3.1

**Steps to Reproduce**:

1. Currently we are using **MSBuildWorkspace.OpenSolutionAsync** to open a particular Solution programatically. 
2. Instead, we want to get the Microsoft.CodeAnalysis.Solution object for the solution which is already open in the current instance of Visual Studios. 
3. The initial reference which we have got is to use following code: 

```
var componentModel = (IComponentModel)this.GetService(typeof(SComponentModel));
var workspace = componentModel.GetService<Microsoft.VisualStudio.LanguageServices.VisualStudioWorkspace>();
```
But guess the **this.GetService** code will only work in the context of .vsix plugin and we are not very sure if this is the required code. Is this the right code to be used in the context of .vsix plugin mode?

Is there any way in which we can get the currently loaded solution instance in a console application without using the **OpenSolutionAsync** method.

**Expected Behavior**:
Some way in which we can get the instance of Microsoft.CodeAnalysis.Solution object for the solution which is already open in the current instance of Visual Studios.

**Comment by Pilchie** [comment]
The code you have above is right for an extension loaded in VS.

We do not have any way to get this information from another process.

**Comment by sharwell** [comment]
> Is there any way in which we can get the currently loaded solution instance in a console application 

The workspace APIs are not available in the context of a build-integrated diagnostic analyzer. You can use the workspace APIs in a VSIX-installed analyzer, but there are two limitations to be aware of:

1. VSIX-installed analyzers will only run inside Visual Studio, and will not run as part of the build.
2. The workspace dependency means you cannot use the same analyzer in both VSIX and build-integrated (typically NuGet) forms without rather uncomfortable workarounds.

**Comment by abhijitparkhi1983** [comment]
Thanks @Pilchie.

@sharwell , sorry I dint really get the 2nd point which you have mentioned. Can you please elaborate on this one.

**Comment by Pilchie** [comment]
If you are writing an *analyzer*, and you want it to be usable by csc.exe during command line builds, it can't depend on the Workspace APIs, since the compiler doesn't construct a workspace during builds.

**Comment by abhijitparkhi1983** [comment]
Thanks @Pilchie and @sharwell  for the inputs. These inputs are very helpful to proceed ahead.
