### ISSUE TITLE
VS should offer to replace uninitialized `var` with inferred type if that type is initialized a few lines later

### ISSUE THREAD

**Issue by chucker** [dotnet/roslyn#21548]
**Scenario**
An API call returns a somewhat convoluted type. Because I use `var` to have it inferred, and never much interact with the underlying type, I don't care nor need to what the type is. For example:

```csharp
// it doesn't really matter to me what type `rows` is…
var rows = someORM.Sql("SELECT foo FROM bar;").Execute().Rows;

// …as long as it implements IEnumerable, anyway
foreach (var row in rows)
{

}
```

However, now I want to wrap my code such that explicit typing is required — for example, in a `try/catch` block. I cannot use `var` without initializing, so I have to specify the above type.

```csharp
// this won't compile because of CS0818 Implicitly-typed variables must be initialized
var rows;

try
{
    rows = someORM.Sql("SELECT foo FROM bar;").Execute().Rows;
}
catch { }
```

**Minor improvement**
For this scenario, it would be helpful for VS to have a lightbulb on the first line:

```csharp
// it doesn't really matter to me what type `rows` is…
var rows = someORM.Sql("SELECT foo FROM bar;").Execute().Rows;
```

…which offers to transform it to something like this:

```csharp
IQueryable<Row> rows = someORM.Sql("SELECT foo FROM bar;").Execute().Rows;
```

So that, in the next step, I just have to move `IQueryable<Row> rows` up a few lines and replace the beginning of this line with just `rows`.

**Major improvement**
It would be even better if VS *recognized* this particular scenario. That is, given the non-compiling code from above:

```csharp
// this won't compile because of CS0818 Implicitly-typed variables must be initialized
var rows;

try
{
    rows = someORM.Sql("SELECT foo FROM bar;").Execute().Rows;
}
catch { }
```

, it would be wonderful if VS could offer to substitute `var` with the actual inferred type for the first usage of `rows`.

**Comment by CyrusNajmabadi** [comment]
We would take a targeted community pr here.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
