### ISSUE TITLE
IntoClauseBinder in VB reuses same bound node in different parts of the bound tree

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#21554]
See field [m_GroupReference](http://index/?leftProject=Microsoft.CodeAnalysis.VisualBasic&leftSymbol=x5bpepeg4iir&file=Binding%5CBinder_Query.vb&rightSymbol=olcu66daxcm1), which is used as a child of more than one bound node by this binder. This causes Parent pointer functionality in VisualBasicOperationFactory to assert as it has more than one parent node. We will put a temporary workaround in the operation factory to work around this bug, but it will need to be reverted when this is fixed in the binder.

**Comment by gafter** [comment]
Since we are looking at using IOperation after the lowering phase, which also produces a DAG, I think we have to consider the bug to be in `VisualBasicOperationFactory` which is not resilient to DAGS.

**Comment by gafter** [comment]
Alternatively, we would have to introduce a new invariant of the bound nodes, which apparently `VisualBasicOperationFactory` already assumes.

**Comment by AlekseyTs** [comment]
I think we will have to find a way to deal with DAGS in IOperationFactory, for both languages.
