### ISSUE TITLE
CSharpFormatting.PasteCodeWithLambdaBody3 integration test flakiness

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21559]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/7111/artifact/Binaries/Release/UnitTests/VisualStudioIntegrationTests/xUnitResults/Roslyn.VisualStudio.IntegrationTests.dll.out.log

```
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpFormatting.PasteCodeWithLambdaBody3
      Assert.Contains() Failure
      Not found: 
      using System;
      class Program
      {
          static void Main()
          {
              Action a = () =>
              {
                  using (null)
                  {
                      D d = delegate (int x)
                      {
                          return 2 * x;
                      };
                  }
              };
          }
      }
      In value:  
      using System;
      class Program
      {
          static void Main()
          {
              Action a = () =>
              {
                  using (null)
                  {
      
                  }
              };
          }
      }
```

**Comment by dpoeschl** [comment]
FYI @agocke

**Comment by Pilchie** [comment]
Can you take a look? It seems like the paste hadn't happened yet?

**Comment by dpoeschl** [comment]
PasteCodeWithLambdaBody**2** failure: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/7135/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpFormatting/PasteCodeWithLambdaBody2/

**Comment by 333fred** [comment]
Failure on official integration run: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.5-preview1-staging/job/windows_release_vs-integration/2/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpFormatting/PasteCodeWithLambdaBody3/

**Comment by 333fred** [comment]
@dpoeschl, does this issue need to be retriaged?

**Comment by tmat** [comment]
Also CSharpFormatting.PasteCodeWithLambdaBody2 is failing: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/8435/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpFormatting/PasteCodeWithLambdaBody2/

**Comment by mavasani** [comment]
Another failure: https://ci.dot.net/job/dotnet_roslyn/job/dev15.7.x/job/windows_release_vs-integration_prtest/66/

**Comment by 333fred** [comment]
Another failure: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x/job/windows_release_vs-integration/164/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpFormatting/PasteCodeWithLambdaBody3/. @dpoeschl, have you looked into this at all yet?

**Comment by CyrusNajmabadi** [comment]
Closing out as it's been 2 years without a hit here.
