### ISSUE TITLE
Possible bug - constant expression reported as not being constant.

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#21569]
This elicits an error in the C# compiler in VS 2017:

>         private const string[] supportedAttributes = { DeploymentSection.PROPERTY_NAME_ZONE, DeploymentSection.PROPERTY_NAME_PASSWORD, DeploymentSection.PROPERTY_NAME_CONSISTENT };

Each of the names in the DeploymentSection class are declared as **public const string** and initialized to a string literal like "password" and so on, in said declaration.

I may be missing something but the RHS seems pretty constant to me.

**Comment by HaloFour** [comment]
C# doesn't support declaring a const array.  It doesn't matter that the elements of that array are themselves constants.  The only exception to this rule is when assigning a constructor argument or property of an attribute.

**Comment by gafter** [comment]
Arrays are not among the types that are capable of being constant.

**Comment by Korporal** [comment]
@HaloFour @gafter - This was closed rather suddenly. In that case perhaps the diagnostic message could be improved? If an array isn't capable of being constant then that should be conveyed in the diagnostic message. The actual diagnostic text says this:

_"The expression being assigned to 'deploymentAttributes' must be constant"_

that is, it is complaining about the expression rather than the assignment target, some wording improvement in this scenario would be nice.

**Comment by gafter** [comment]
Well, `null` is a constant array. But an array creation expression isn't constant.

**Comment by Korporal** [comment]
Very well @gafter if you think the compiler error message in this scenario cannot be improved then I guess that's that.

**Comment by gafter** [comment]
@Korporal Even if the array elements are initialized with constant values, they can be assigned later, rendering them non-constant. That's because C# has no concept of a read-only array.

**Comment by miloush** [comment]
Actually, `private const string[] supportedAttributes = null;` compiles. It's what you are assigning that isn't constant.
