### ISSUE TITLE
Missing return type error on previous method

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#21565]
Consider the following code:

``` c#
void M() { } 
G() { } 
```

The compiler will correctly issue CS1520 for this code. But it will be placed on the closing brace of `M`, not on the identifier `G`.

**Comment by gafter** [comment]
@jaredpar I believe this has already been fixed. Can you please verify?

**Comment by jcouv** [comment]
Verified ([sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABALAAgFkAKASnwG98BffAWACgBxMym/IA=)). Closing as fixed.
