### ISSUE TITLE
IntelliSense shows completions for interfaces after new

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#21571]
**Version Used**: VS 15.3.0

Typing `new IL` shows completions for `IList` & other interfaces.

Since interfaces cannot have nested types, there is no way they can ever appear after `new`; they should not appear as completions.

IIRC, older versions did not show interfaces.

**Comment by 0xd4d** [comment]
This is a valid C# expression: `new IMyInterface[100]` where `IMyInterface` is an interface.

**Comment by Pilchie** [comment]
We don't *hide* interfaces, but we generally don't preselect them unless the inferred type is an array.  @SLaks which case are you talking about here?

**Comment by CyrusNajmabadi** [comment]
> Since interfaces cannot have nested types, there is no way they can ever appear after new; they should not appear as completions.

@0xd4d points out, this is not the case "new InterfaceName[...]" is completely legal code, and should be supported.

> IIRC, older versions did not show interfaces.

I don't believe htat's the case.  And if it was, that would be a bug :)
