### ISSUE TITLE
Contents of anonymous types aren't simplified

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#21603]
**Version Used**: 15.3

```C#
var y = "".ToString();
var x = new {
	y,
	z = "".OrderBy(c => new DateTime(c))
};
```

Inlining `y` gives

```C#
var x = new {
	y = "".ToString(),
	z = "".OrderBy<char, global::System.DateTime>(c => new global::System.DateTime(c))
};
```
The same thing happens for Extract Local (in reverse).

And no Simplify Name quick-fixes are offered.

**Comment by CyrusNajmabadi** [comment]
Works fine for me.  I get:

![image](https://user-images.githubusercontent.com/4564579/198750110-2034e954-798b-48aa-8881-222da3cce3b0.png)
