### ISSUE TITLE
Remove cast refactoring should not remove cast if it changes the type of the value.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#21613]
```c#
class C
{
    void M(bool x)
    {
        int? y = x ? (int?)1 : default;
    }
}
```

```(int?)``` cannot be removed here as it changes the meaning of 'default' (from null, to 0), which changes the value of y if x is false.

**Comment by CyrusNajmabadi** [comment]
Tagging @DustinCampbell @jcouv

**Comment by DustinCampbell** [comment]
IIRC, we had tests for this with "null" in place of "default". I'm betting we need a little work here.
