### ISSUE TITLE
[IOperation] Handling user-defined conversions

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#21614]
Currently, for user-defined conversions, we produce an IConversionExpression that looks something like this:
```C#
class C1
{
    void M1()
    {
        C1 c1 = new C1();
        C2 /*<bind>*/c2 = (C2)c1/*</bind>*/;
    }

    public static explicit operator C2(C1 c1) => new C2();
}

class C2 { }
```
```
IVariableDeclarationStatement (1 declarations) (OperationKind.VariableDeclarationStatement) (Syntax: 'C2 /*<bind> ... *</bind>*/;')
  IVariableDeclaration (1 variables) (OperationKind.VariableDeclaration) (Syntax: 'C2 /*<bind> ... *</bind>*/;')
    Variables: Local_1: C2 c2
    Initializer: IConversionExpression (Explicit, TryCast: False, Unchecked) (OperatorMethod: C2 C1.op_Explicit(C1 c1)) (OperationKind.ConversionExpression, Type: C2) (Syntax: '(C2)c1')
        Conversion: CommonConversion (Exists: True, IsIdentity: False, IsNumeric: False, IsReference: False, IsUserDefined: True) (MethodSymbol: C2 C1.op_Explicit(C1 c1))
        Operand: ILocalReferenceExpression: c1 (OperationKind.LocalReferenceExpression, Type: C1) (Syntax: 'c1'
```

However, this is effectively a method call of the conversion method. Because of this VB has some additional complications we're currently not handling, namely around in and out conversions. For example:
```VB.NET
Module Program
    Sub M1(args As String())
        Dim i As Integer = 1
        Dim c1 As C1 = i'BIND:"Dim c1 As C1 = i"
    End Sub

    Class C1
        Public Shared Widening Operator CType(ByVal i As Long) As C1
            Return New C1
        End Operator
    End Class
End Module
```
```
IVariableDeclarationStatement (1 declarations) (OperationKind.VariableDeclarationStatement) (Syntax: 'Dim c1 As C1 = i')
  IVariableDeclaration (1 variables) (OperationKind.VariableDeclaration) (Syntax: 'c1')
    Variables: Local_1: c1 As Program.C1
    Initializer: IConversionExpression (Implicit, TryCast: False, Unchecked) (OperatorMethod: Function Program.C1.op_Implicit(i As System.Int64) As Program.C1) (OperationKind.ConversionExpression, Type: Program.C1) (Syntax: 'i')
        Conversion: CommonConversion (Exists: True, IsIdentity: False, IsNumeric: False, IsReference: False, IsUserDefined: True) (MethodSymbol: Function Program.C1.op_Implicit(i As System.Int64) As Program.C1)
        Operand: ILocalReferenceExpression: i (OperationKind.LocalReferenceExpression, Type: System.Int32) (Syntax: 'i')
```

There is an implicit conversion from int to long in the implicit user-defined conversion here that we are not currently representing. There are two possibilities for how to resolve this. The first is to have represent user-defined conversions in both languages as a function call. The nicety here is twofold: first, the user-defined conversion _is_ a function call. Second, we can represent that the in and out conversion are part of the same conversion step. However, this will make it harder to IOperation users to simply get all conversions, as they'll have to subscribe to all invocations and filter to method symbols that are conversions.
The other possibility (and the one I favor) is to simply insert the in and out conversions as IConversionExpressions if necessary. So the hierarchy would look like this:
```
IConversionExpression (out conversion, if present)
    Operand:
        IConversionExpression (User-defined conversion)
            Operand:
                IConversionExpression (in conversion, if present)
                    Operand:
                        IOperation (Converted expression)
```
I like this because it makes it easy to see that multiple conversions are actually taking place. `IsImplict` on the outer and inner conversion should provide the information that the conversion is actually part of the user-defined conversion. Tagging @dotnet/analyzer-ioperation @AlekseyTs for discussion.

**Comment by AlekseyTs** [comment]
> Because of this VB has some additional complications we're currently not handling, namely around in and out conversions.

I think this is not VB specific, C# performs "in/out" conversions as well.

**Comment by 333fred** [comment]
If it does, then I'd push for the second form even more. afaict, there is no corresponding structure to a BoundUserDefinedConversion in C#, so it appears that when we get to the bound nodes we've already converted the in and out conversions to separate conversions. See https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IConversionExpression.cs#L2793.

**Comment by AlekseyTs** [comment]
I agree, there is something wrong in the base-line for that test:
```
            string expectedOperationTree = @"
IVariableDeclarationStatement (1 declarations) (OperationKind.VariableDeclarationStatement) (Syntax: 'C2 /*<bind> ... *</bind>*/;')
  IVariableDeclaration (1 variables) (OperationKind.VariableDeclaration) (Syntax: 'C2 /*<bind> ... *</bind>*/;')
    Variables: Local_1: C2 c2
    Initializer: IConversionExpression (Implicit, TryCast: False, Unchecked) (OperatorMethod: C2 C2.op_Implicit(System.Int64 c1)) (OperationKind.ConversionExpression, Type: C2) (Syntax: 'i1')
        Conversion: CommonConversion (Exists: True, IsIdentity: False, IsNumeric: False, IsReference: False, IsUserDefined: True) (MethodSymbol: C2 C2.op_Implicit(System.Int64 c1))
        Operand: IConversionExpression (Implicit, TryCast: False, Unchecked) (OperatorMethod: C2 C2.op_Implicit(System.Int64 c1)) (OperationKind.ConversionExpression, Type: System.Int64) (Syntax: 'i1')
            Conversion: CommonConversion (Exists: True, IsIdentity: False, IsNumeric: False, IsReference: False, IsUserDefined: True) (MethodSymbol: C2 C2.op_Implicit(System.Int64 c1))
            Operand: ILocalReferenceExpression: i1 (OperationKind.LocalReferenceExpression, Type: System.Int32) (Syntax: 'i1')
";
```

A conversion from **int** to **long** is exposed, but it is marked as user-defined and even has a method symbol.

**Comment by AlekseyTs** [comment]
I am curious what happens with "out" conversion for C# today.

**Comment by jinujoseph** [comment]
@333fred , @AlekseyTs , Is there some thing we need to take care here ?

**Comment by AlekseyTs** [comment]
> Is there some thing we need to take care here ?

I think at the very least we need to fix C# implementation, the problem is described in https://github.com/dotnet/roslyn/issues/21614#issuecomment-323444633.

**Comment by 333fred** [comment]
Looking at our current implementation, it appears that this is fixed. The case @AlekseyTs mentioned in his comment is this:
```C#
class C1
{
    void M1()
    {
        int i1 = 1;
        C2 /*<bind>*/c2 = i1/*</bind>*/;
    }
}

class C2
{
    public static implicit operator C2(long c1)
    {
        return null;
    }
}
```
This is now generating the following IOperation tree, which looks correct to me. Previously, this generated the tree in the linked comment above.
```
IVariableDeclarationOperation (1 variables) (OperationKind.VariableDeclaration, Type: null) (Syntax: 'c2 = i1')
  Variables: Local_1: C2 c2
  Initializer: 
    IVariableInitializerOperation (OperationKind.VariableInitializer, Type: null) (Syntax: '= i1')
      IConversionOperation (TryCast: False, Unchecked) (OperatorMethod: C2 C2.op_Implicit(System.Int64 c1)) (OperationKind.Conversion, Type: C2, IsImplicit) (Syntax: 'i1')
        Conversion: CommonConversion (Exists: True, IsIdentity: False, IsNumeric: False, IsReference: False, IsUserDefined: True) (MethodSymbol: C2 C2.op_Implicit(System.Int64 c1))
        Operand: 
          IConversionOperation (TryCast: False, Unchecked) (OperationKind.Conversion, Type: System.Int64, IsImplicit) (Syntax: 'i1')
            Conversion: CommonConversion (Exists: True, IsIdentity: False, IsNumeric: True, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
            Operand: 
              ILocalReferenceOperation: i1 (OperationKind.LocalReference, Type: System.Int32) (Syntax: 'i1')
```

Given that, I'm going to close this issue. @AlekseyTs, feel free to reopen if you think I'm missing something here.

**Comment by AlekseyTs** [comment]
@333fred Do we have tests that cover scenarios when a standard conversion is needed on top of the operator method call?

**Comment by 333fred** [comment]
@AlekseyTs we do for implicit conversions, https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IConversionExpression.cs#L4919.
