### ISSUE TITLE
Using the "Comment out" gesture in C# on a single line adds a selection spanning into the next line

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#21610]
:link: from https://developercommunity.visualstudio.com/content/problem/91131/using-the-comment-out-gesture-in-c-on-a-single-lin.html

**Version Used**: 
Visual Studio 2017 version 15.3

I'm using the Key Binding CTRL+E/CTRL+C and CTRL+E/CTRL+U to Comment Out / Comment In the current line where the cursor is (there's no active selection). After the gesture runs, there's a selection that normally spans the newly generated comment. Sometimes though, the selection spans more than necessary. Here are a few examples:

```C#
// run Comment Out on the next line
this.stream = stream;
semaphoreSend = new SemaphoreSlim(1);
// The selection then spans up until and including the space before new
```

When I then run Comment In on the stream line without selection, the new selection only spans from the beginning of the line to the m of the first stream

```C#
// run Comment Out on the next line
var endPoint = EndPointFactory.Create(options.Address);
var socket = new Socket(AddressFamily.Unix, SocketType.Stream, 0);
// The selection then spans the entire second line including the line break at the end
```

Comment In works here as expected and just selects the entire endPoint-line

![9981-comment-uncomment](https://user-images.githubusercontent.com/312835/29468756-658f63f4-83fa-11e7-8c11-9ba4bbd80c0d.gif)

**Comment by Pilchie** [comment]
Can you take a look  at the span tracking and see what might trigger this?

**Comment by CyrusNajmabadi** [comment]
Closing out for lack of feedback.
