### ISSUE TITLE
Cross-language ProjectReferences are not passed to compilation if referenced project doesn't build cleanly

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#2162]
OK, this is a tricky one, took me two full days to investigate.
1. Have a solution with two projects, CSProject and VBProject, VBProject referencing CSProject via a project reference
2. CSProject should have an error
3. Use MSBuildWorkspace to open the solution, get the Project for VBProject and call Project.GetCompilationAsync().
4. The resulting compilation won't have a reference to CSProject at all

This was very hard to track down, but here are some notes:

The stack goes something like this (if you erase TPL and async):

```
Microsoft.CodeAnalysis.MetadataOnlyImage.Create Line 47 C#
Microsoft.CodeAnalysis.MetadataOnlyReference.GetOrBuildReference Line 44    C#
Microsoft.CodeAnalysis.Solution.CompilationTracker.GetMetadataOnlyImageReferenceAsync Line 715  C#
Microsoft.CodeAnalysis.Solution.CompilationTracker.GetMetadataReferenceAsync Line 660   C#
Microsoft.CodeAnalysis.Solution.GetMetadataReferenceAsync Line 2005 C#
Microsoft.CodeAnalysis.Solution.CompilationTracker.FinalizeCompilationAsync Line 598    C#
Microsoft.CodeAnalysis.Solution.CompilationTracker.BuildCompilationFromScratchAsync Line 472    C#
```

>   Microsoft.CodeAnalysis.Solution.CompilationTracker.GetOrBuildCompilationAsync Line 401  C#

If a compilation has any errors or failed to emit, this code just returns an empty image:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/MetadataOnlyImage.cs,47

We need a way to reference compilations in another language even if the referenced project can't emit cleanly.

Here's a useful set of breakpoints that I used:

![breakpoints](https://cloud.githubusercontent.com/assets/679326/7263450/74109054-e836-11e4-9024-a3074c461a2f.PNG)

**Comment by KirillOsenkov** [comment]
Here:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/Solution.CompilationTracker.cs,604

If the metadataReference is null for some reason, we silently "lose" the project reference.

**Comment by jasonmalinowski** [comment]
> We need a way to reference compilations in another language even if the referenced project can't emit cleanly.

What do you mean by this? If the other project couldn't emit, there's nothing that can be referenced in the cross-language case.

**Comment by KirillOsenkov** [comment]
It seems natural to me that if a type is declared in the same project and it has errors, it still appears in IntelliSense and you can navigate to it, etc. All IDE services are designed to work with symbols that have errors.

As a user, I expect that if this type with errors happens to be declared in a different project, I should still be able to see that type in IntelliSense, navigate to it, etc. The fact that it's in a different project shouldn't be significant in any way. Even the fact that it may be in a different language shouldn't be significant. The IDE should be able to work with incomplete code, crossing project and language boundaries.

The current implementation uses skeletons and it prohibits cross-project/language scenario from working, however I think this is just a flaw of the current implementation, and not that the scenario is fundamentally impossible. Within the same project we work with incorrect code just fine, why should we have this "all-or-nothing" situation cross projects?

**Comment by KirillOsenkov** [comment]
BTW @CyrusNajmabadi explained it to me a while back, but I forgot. What I remember is he said that we could consume symbols directly across projects, but it would be a lot of work, so creating skeletons was a much simpler solution.

**Comment by jasonmalinowski** [comment]
"a lot of work" is an understatement. The commonly cited alternative is the C# and VB compilers have to directly consume each other's symbol types. This causes obvious friction when the symbol models are different -- what is a C# compiler supposed to do with a VB module type? And if a third language was ever introduced, do they all have to know about each other's types now? This would be a non-trivial rearchitecting of Roslyn.

There's also an assumption that skeleton builds should not fail. Understanding why your skeleton build failed would be very informative -- if the skeleton build failed then it's possible the symbols would have been in such an unusable state that even if the compilers could understand each other's symbols there wouldn't have been any symbols at all.

I think this bug in it's current form is somewhat unactionable -- yes, we _could_ move away from skeletons, but that's neither a trivial undertaking nor is it clear it's worth the benefit. If you share the underlying reason that the skeleton failed to build, we might be able to provide a solution that actually helps you.

**Comment by KirillOsenkov** [comment]
The proposal of your first paragraph is definitely something we shouldn't do (N^2 explosion of combinations where N is the number of languages, currently 2).

What I don't understand (and it's likely because of my lack of knowledge in this area) is aren't interfaces such as INamedTypeSymbol a sufficient lingua franca for different languages to understand each other? Who cares if it's PENamedTypeSymbol or SourceNamedTypeSymbol from another language? For your "C# looking at a VB module" example, it currently works (it is visible as a PE symbol), but do we really care that it's a PE symbol? Shouldn't the interfaces like INamedTypeSymbol be language agnostic and consumable from different languages?

Regarding my particular problem that I'm trying to solve, this reference to AbstractEncProject doesn't bind:
http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.VisualBasic/ProjectSystemShim/VisualBasicProject.vb,19

Because the index is being rebuilt on a machine that has a slightly different drop of Dev14 than what is used by the latest Roslyn source, so ServicesVisualStudio has an error, so a P2P from BasicVisualStudio to ServicesVisualStudio doesn't work, as a result there's no hyperlink from VisualBasicProject to its parent type AbstractEncProject.

Many people are asking me about these broken hyperlinks, the root cause is this bug.

I guess a workaround is to make sure that http://source.roslyn.io is always built on a machine with exactly the same drop of VS that Roslyn depends on, however this is not something I'm willing to do because of resource constraints.

I can fully understand that the bug might be really hard to fix, however my goal was just to point out a deficiency (cross-language IDE features don't work in presence of errors) and that it impacts user experience of Roslyn users and make sure this issue gets enough visibility.

**Comment by mattwar** [comment]
@KirillOsenkov each compiler retains more state than is available in those interfaces, so you cannot just give a C# symbol to VB, the compilers don't operate against the interfaces.

It might be possible to build language specific wrapper types around the common interfaces though.  So that would be one additional wrapper implementation per language.. (there are already multiple implementations of symbols per language so it wouldn't be all that bad.)  

It might not be possible to represent the compiler symbol with 100% fidelity via the interface, but it would be better than nothing.

**Comment by jasonmalinowski** [comment]
Moving to the ISymbol interfaces also requires care to split out the part of the symbols that are behaviors of the source language versus the consuming language. For example, `INamedTypeSymbol.GetMembers(name)` returns matching symbols by name under the rules of the source language, when in some cases you'd potentially want it to be the consuming language. It's not an insurmountable issue, but would require care to make sure mistakes aren't made.

**Comment by controlflow** [comment]
"a lot of work" is an overstatement. Common CLI symbol model is implemented in ReSharper years and years and years ago, it works, we have no issues with it, it do not requires any kind of "skeleton build", project can be broken in many ways, we can fit C++/CLI there in future. We even use the same type system for code completion in WinJS applications. `INamedTypeSymbol` is enough to be consumable from C#/VB, language-specific types are not publicly-visible now (anonymous types, VB anonymous function types, etc). Case-insensitivity of VB type system is not the real issue, added complexity can be hidden in semantic model.

When this "skeleton build" thing happens? On every edit, on save? What kind of code issues prevent "skeleton" from being built?

**Comment by CyrusNajmabadi** [comment]
Not planning on doing this given low feedback from users that thsi is an issue for them.
