### ISSUE TITLE
Suggest names for VB variables.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#21621]
We didn't do this since in the forward typing case there's no type with which to suggest a name off of.  however, there is still the case where i go to an existing variable and want to rename it.  In that case, i would like the suggestion.  Here we will know the type, and we can do something better.

Tagging @rchande

**Comment by Nukepayload2** [comment]
Suggest a type name is more helpful.
For example:
```vb
Dim timeSpan As ' suggest TimeSpan
Dim sb As New ' suggest StringBuilder
```

**Comment by CyrusNajmabadi** [comment]
Unlikely to change vb behavior now.
