### ISSUE TITLE
Unknown build error when using IEnumerable<ValueTuple[..]> with pattern matching in C# 7.0

### ISSUE THREAD

**Issue by phillyai** [dotnet/roslyn#21656]
**Version Used**: VS2017 15.3.1

**Steps to Reproduce**:

I'm using C# 7.0, and I imported System.ValueTuple in nuget gallery.
Next code is well compiled.

```csharp
int[] list = { 3, 1, 4, 1, 5, 9, 2 };
(int, int)[] dummy = { };
var filtered = list.Select((val, index) => (val, index));
foreach (var (i, v) in dummy)
{
    Console.WriteLine($"{i}: {v}");
}
```

But next code that is just replaced dummy inner foreach to filtered, couldn't be compiled, compiler raise unknown error without any messages.

```csharp
int[] list = { 3, 1, 4, 1, 5, 9, 2 };
(int, int)[] dummy = { };
var filtered = list.Select((val, index) => (val, index));
foreach (var (i, v) in filtered)
{
    Console.WriteLine($"{i}: {v}");
}
```

Even I disassemblied first code and replaced dummy to filtered and it worked very well.

**Comment by 0xd4d** [comment]
Seems to have been fixed by 15.3.2

**Comment by phillyai** [comment]
@0xd4d Excuse me, where can I find version 15.3.2?

**Comment by jcouv** [comment]
@phillyai You should be able to get the 15.3.2 update via the VS installer. It should also appear as a yellow flag in VS itself.
It was released on Aug 22nd: https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#15.3.2

**Comment by phillyai** [comment]
@jcouv Thanks. 15.3.1 was recent version in that day and also there wasn't 15.3.2 on release note. It seems solved now.
