### ISSUE TITLE
'Inline rename' adds an extra Attribute string when renaming an attribute

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#21657]
**Version Used**: VS2017 15.3.1

**Steps to Reproduce**:

Inline rename the attribute below from `MyAttribute` to eg. `XXXAttribute`

```C#
	sealed class MyAttribute : Attribute {
	}
```

**Expected Behavior**:

New name is `XXXAttribute`

**Actual Behavior**:

New name is `XXXAttributeAttribute`

**Comment by Pilchie** [comment]
:link: Also reported at https://developercommunity.visualstudio.com/content/problem/62106/rename-attribute-stuck-with-nameattributeattribute.html

**Comment by JustinMinnaar** [comment]
Yes, I've encountered this problem too.

**Comment by tg73** [comment]
Having recently updated to 15.3.1, I'm now seeing the same problem. A workaround is to comment out the base class declaration, rename, and then uncomment the base class declaration.

**Comment by agr** [comment]
Issue is still present in 15.7.0 Preview 3.0 [27602.0.d15.7]

**Comment by 0x0001F36D** [comment]
I've encountered this problem in present version: 15.7.3

**Comment by OndrejVrsan** [comment]
Workaround: 
1. Temporarily comment out inherited `Attribute` class, so you'll get e.g.
`
public sealed class MyAttribute // : Attribute
`
2. Perform the inline rename
3. Remove the comment so your class inherits `Attribute` again
`
public sealed class MyRenamedAttribute : Attribute
`

**Comment by nvmkpk** [comment]
Well better workaround would be to first rename the class and then update references using the light bulb.

**Comment by yaroslavboev** [comment]
Guys, are you going to fix it? A **year** has passed already.

**Comment by lillo42** [comment]
@CyrusNajmabadi  I would like to try to fix this issue

**Comment by CyrusNajmabadi** [comment]
@lillo42 Great!  Have you contributed to Roslyn before?  Do you have an existing enlistmnet to work out of?  Or would you need to get that set up?

**Comment by lillo42** [comment]
@CyrusNajmabadi I haven't contributed  before, I would like to get that set up. Do you recommend some article or something to read before I begin to fix?

**Comment by jmarolf** [comment]
@lillo42 

[Here](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/compiler-api-model) is a basic overview of roslyn to get you started.

[Here](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building%2C%20Debugging%2C%20and%20Testing%20on%20Windows.md) are instructions on how to build and debug roslyn.

[Here](https://github.com/dotnet/roslyn/tree/master/src/EditorFeatures/Core.Wpf/InlineRename) is where the inline rename code lives.

You can always ask questions on [gitter](https://gitter.im/dotnet/roslyn), team members try to monitor that.

**Comment by lillo42** [comment]
@jmarolf  @CyrusNajmabadi  Thank very much.

**Comment by jinujoseph** [comment]
also reported [here](https://developercommunity.visualstudio.com/content/problem/307050/rename-button-for-class-inherited-from-attribute-i.html)

**Comment by mohitsharmaniit11** [comment]
@OndrejVrsan Your workaround works thanks, issue still not resolved.

**Comment by SaSiNO97** [comment]
This issue still exists (at least in the version of Roslyn used by VS Community 2017 15.8.6)

**Comment by Neme12** [comment]
@SaSiNO97 The fix will be available in VS 2019 Preview 2 (16.0 is the numeric version of VS 2019, just like 15.0 is for 2017), not in 15.8 or 15.9 unfortunately.

**Comment by PCC-UK** [comment]
Why will this issue not be fixed in 15.9?

**Comment by lostllama** [comment]
@Neme12 There was a "Why" at the start of @PCC-UK's question :)

**Comment by SieBrum** [comment]
This is still an issue, why is this still not fixed?

**Comment by CyrusNajmabadi** [comment]
@SieBrum 

> This is still an issue, why is this still not fixed?

Works for me:

![image](https://user-images.githubusercontent.com/4564579/71076191-27562c00-213a-11ea-85d7-61d0a30005f1.png)

![image](https://user-images.githubusercontent.com/4564579/71076213-2f15d080-213a-11ea-9040-c09fe07ade58.png)

![image](https://user-images.githubusercontent.com/4564579/71076227-34731b00-213a-11ea-83fa-5a0ea3ea493e.png)

**Comment by SaSiNO97** [comment]
@Neme12 Thanks, I really appreciate the work you are doing
