### ISSUE TITLE
Incorrect parsing in lambda in C#6 Dictionary initializer

### ISSUE THREAD

**Issue by robhol** [dotnet/roslyn#21666]
**Version Used**: VS 2017 / 15.2 (26430.16)

**Demo code**
```cs
private static readonly Dictionary<Operation, Func<int, int, bool>> OperationFunctions = new Dictionary<Operation, Func<int, int, bool>>
        {
            [Operation.Equal]               = (a, b) => a == b,
            [Operation.LessThan]            = (a, b) => a < b,
            [Operation.LessThanOrEqual]     = (a, b) => a <= b,
            [Operation.GreaterThan]         = (a, b) => a > b,
            [Operation.GreaterThanOrEqual]  = (a, b) => a >= b,
            [Operation.NotEqual]            = (a, b) => a != b
        };
``` 

In this code snippet, the LessThan line is marked with errors...

```
CS0307  The variable 'int' cannot be used with type arguments  (?)
CS0118  'b' is a variable but is used like a type
```

... which suggests that "a < b" is not being interpreted as the obvious comparison "a less than b", but as an attempt to refer to a "type" "a" with a generic argument "b" - neither of which exists, of course, since they're defined like 4 characters previously. :)

One workaround is to surround "a < b" with parentheses, but you wouldn't expect this to be necessary.

**Expected Behavior**:
a < b parsing correctly as "a less than b".

**Other**: 
This bug may have appeared in a reasonably recent version, as the code was perfectly fine in VS2015.

**Comment by gafter** [comment]
This works in the latest public versions of Visual Studio.
