### ISSUE TITLE
Can't remove roslyn analyzer from project in VS 2017 15.3.2

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/roslyn#21663]
**Version Used**: 
VS 2017 15.3.2 (happens with 15.3.1 too, didn't try anything else)
**Steps to Reproduce**:

1.  Create class library project (.NET framework 4.7 in my case)
2.  Add XUnit Beta 2.3.0-beta4-build3742 nuget packages
3.  Go to References-Analyzers, right-click Xunit.analyzer and select Remove.

**Expected Behavior**:
Analyzer is removed

**Actual Behavior**:
HRESULT E_FAIL
![29554714-7b9e173e-8720-11e7-918b-1afdf55fd275](https://user-images.githubusercontent.com/7989549/29584616-a2275ae6-8784-11e7-8435-1869486a9639.png)

Repro:
[AnalyzerRemove.zip](https://github.com/dotnet/roslyn/files/1243197/AnalyzerRemove.zip)

Originally filed as: https://github.com/xunit/xunit/issues/1422

**Comment by Pilchie** [comment]
Tagging @tmeschter

**Comment by tmeschter** [comment]
@Tornhoof Your project is using `PackageReference` elements in the project file to add packages, as opposed to packages.config. As such the analyzer is never added directly the project file, and there is nothing for us to remove. The only way to remove it is to remove the entire package.

You could switch pack to the packages.config package management format. Open Tools | Options | NuGet Package Manager | General, and change the settings under "Package Management". Then you would be able to remove the Xunit.Analyzers analyzer.

If you want to keep using `PackageReference`s but don't want to run the analyzers, you can expand the Xunit.Analyzer node in Solution Explorer, right click on each diagnostic you wish to turn off, choose "Set Rule Set Severity", and then select "None".

**Comment by tmeschter** [comment]
And for those who may come upon this issue later, the discussion on https://github.com/xunit/xunit/issues/1422 contains additional options for specifically avoiding xunit.analyzers.

**Comment by Tornhoof** [comment]
Thank you for your explanation. As this ist apparently by design I close this Bug.

**Comment by RLashofRegas** [comment]
For anyone coming across this later, I was able to fix the problem by clicking "Clear Nuget Cache(s)" under Tools | Options | NuGet Package Manager | General. I had previously migrated to package reference and then had reverted the commit in git. This somehow left me in a bad state so even though "Package Management" was set to "packages.config" I was still having trouble removing Roslyn analyzers from the solution node.
