### ISSUE TITLE
VB.NET: using predefined type name as field name in value tuple automatically replaced by framework type name

### ISSUE THREAD

**Issue by zaytsev-victor** [dotnet/roslyn#21661]
**Version Used**: 
VS 2017 15.3
**Steps to Reproduce**:

```vbnet
Dim product = (id:=1, [date$$]:=DateTime.Now.ToString())
```

Move cursor to the next line of code.
**Expected Behavior**:
```vbnet
Dim product = (id:=1, [date]:=DateTime.Now.ToString())
```
**Actual Behavior**:
```vbnet
Dim product = (id:=1, [DateTime]:=DateTime.Now.ToString())
```

**Comment by Pilchie** [comment]
Note - this is probably in the [`VisualBasicCaseCorrector`](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic.Workspaces/CaseCorrection/VisualBasicCaseCorrectionService.vb,e95e6431023b4252)

**Comment by CyrusNajmabadi** [comment]
Closing out for lack of feedback.
