### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicLineCommit.CommitOnSave test is flaky

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#21668]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.5.x/job/windows_debug_vs-integration/19/

**Comment by Pilchie** [comment]
Can you take a look?

**Comment by 333fred** [comment]
Stack from a recent failure:
```
    Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicLineCommit.CommitOnSave
      Assert.Contains() Failure
      Not found: Sub Main(x As Integer)
      In value:  Module Module1
          Sub Main(x   As   Integer)
          End Sub
      End Module
      
      Stack Trace:
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicLineCommit.cs(81,0): at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicLineCommit.CommitOnSave()
```

**Comment by tmat** [comment]
Seems like a dup of https://github.com/dotnet/roslyn/issues/20991

**Comment by tmat** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/9342/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicLineCommit/CommitOnSave/

**Comment by tmat** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/dev15.7.x/job/windows_debug_vs-integration_prtest/409/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicLineCommit/CommitOnSave/

**Comment by sharwell** [comment]
Duplicate of #26041
