### ISSUE TITLE
[IOperation] Unexpected IPlaceholder Expression

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#21671]
```VB.NET
Option Strict On

Public Class C1
    Public Sub M1()
       Dim o As New Object
        o?.ToString()'BIND:"o?.ToString()"
    End Sub
End Class
```
```
IConditionalAccessExpression (OperationKind.ConditionalAccessExpression, Type: System.Void) (Syntax: 'o?.ToString()')
  Expression: ILocalReferenceExpression: o (OperationKind.LocalReferenceExpression, Type: System.Object) (Syntax: 'o')
  WhenNotNull: IInvocationExpression (virtual Function System.Object.ToString() As System.String) (OperationKind.InvocationExpression, Type: System.String) (Syntax: '.ToString()')
      Instance Receiver: IPlaceholderExpression (OperationKind.PlaceholderExpression, Type: System.Object) (Syntax: 'o?.ToString()')
      Arguments(0)
```

That should be an IConditionalAccessInstanceExpression. See https://github.com/dotnet/roslyn/pull/21624/files#r134356206. Related to https://github.com/dotnet/roslyn/issues/21294.

**Comment by 333fred** [comment]
This is because the node we were expecting to be the receiver here, BoundConditionalAccessReceiver, isn't actually used until local rewriting. Instead this is a BoundRValuePlaceholder node, with the syntax node of the entire conditional expression. I'll update the handling of this case to look for a syntax of that, and dig through the syntax to set it to be that of the actual receiver.

**Comment by jinujoseph** [comment]
To be verified and closed

**Comment by 333fred** [comment]
@AlekseyTs made this more robust in https://github.com/dotnet/roslyn/pull/26395. Closing out.
