### ISSUE TITLE
Changing internal interface breaks public base class even though it doesn't derive from interface

### ISSUE THREAD

**Issue by jabbera** [dotnet/roslyn#21677]
**Version Used**: 
Microsoft (R) Visual C# Compiler version 2.3.2.62019 (b7354608)
Whatever dotnet build does with the 2.0.0 SDK

**Steps to Reproduce**:

Clone: https://github.com/jabbera/InterfaceBug/tree/dotnetcore
Run build.bat

Build.bat 
  compiles version with property on interface
  runs the app
  compiles new BaseClasses.dll with non breaking changes
  copies it over the running app
  runs the app

**Expected Behavior**:

Application should run fine. I've only modified an internal interface in a non derived class.

**Actual Behavior**:

Application crashes with an error in a class that does not derive from the interface directly or indirectly.

I know the subject of this issue sounds crazy, but it's true. If I make a change to an internal interface in an assembly it causes classes derived in **another** library to break even through **it does not, directly or indirectly, derive off the interface in any way**. There is no public api change! Not only that, but it fails with a very strange error. See: https://github.com/jabbera/InterfaceBug for a demo in 4.7 and https://github.com/jabbera/InterfaceBug/tree/dotnetcore for a core 2.0 demo.

You can clearly see that: [ITroubleInterface](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/ITroubleInterface.cs) is internal and is only implemented by: [TroubleClass](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/TroubleClass.cs) which is also internal. The assembly does not expose internals. 

Note: [ITroubleInterface](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/ITroubleInterface.cs) is not Implemented by [TestBase](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/TestBase.cs)

In my derived assembly there is a class [UnrelatedClass](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/DerivedClasses/UnrelatedClass.cs) that derives from [TestBase](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/TestBase.cs) Note again: This does not implement [ITroubleInterface](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/ITroubleInterface.cs). It does however have another interface [IUnrelatedInterface](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/DerivedClasses/IUnrelatedInterface.cs) that has a mirror property of [ITroubleInterface](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/ITroubleInterface.cs)

If I rebuild my base assembly but comment out the [IToubleInterface:QueryContext](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/ITroubleInterface.cs#L5) property, my [UnrelatedClass](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/DerivedClasses/UnrelatedClass.cs) fails to load with the following exception

```
Unhandled Exception: System.TypeLoadException: Method 'get_QueryContext' in type 'DerivedClasses.UnrelatedClass' from assembly 'derivedclasses, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at ConsoleDriver.Program.Main()
```

This exception makes no sense. [UnrelatedClass](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/DerivedClasses/UnrelatedClass.cs) clearly implements [IUnrelatedInterface:QueryContext](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/DerivedClasses/IUnrelatedInterface.cs#L7) since it derives from [TestBase](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/TestBase.cs) which has an implementation [here](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/TestBase.cs#L7).

My understanding is [this change](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/ITroubleInterface.cs#L5) should be ABI compatible. It certainly is source compatible as rebuilding my derived classes fixes the problem. I'm sure this has something to do with having duplicate interfaces with the same property, and that may seem like an anti-pattern, but this is part of a code generator so it's not as crazy as it sounds.

On a side note, if I comment out the property here: https://github.com/jabbera/InterfaceBug/blob/dotnetcore/DerivedClasses/IUnrelatedInterface.cs#L7 the app no longer breaks either way. Also renaming this to QueryContext1 and adding an implementation in the base class also avoids the issue.

Windows 7/10/2008 R2 .NET 4.6.2., 4.7, 4.5.2, core 2.0.0

I've reported this already here: https://github.com/Microsoft/dotnet/issues/457 under 4.7 only, but I'm hoping I can get some traction here?

**Comment by jaredpar** [comment]
I think we should move this issue over to coreclr. The problem being described here is related to how the runtime handles ABI changes to types. The compiler doesn't really get involved in that decision here.

**Comment by jabbera** [comment]
I'll resubmit there.
