### ISSUE TITLE
Missing git tags for 2.3.x releases

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#21686]
When I run `git tag` to list tags for this repo, the end of the output is:

```
version-2.1.0
version-2.2.0
version-2.3.0-beta1
version-2.3.0-beta2
version-2.3.0-beta3
version-2.3.2-beta1
```

[Package versions](https://www.nuget.org/packages/Microsoft.CodeAnalysis/) 2.3.0 and 2.3.1 were released on NuGet, but don't have git tags. I think they should.

According to NuGet descriptions, 2.3.0 should be https://github.com/dotnet/roslyn/commit/281ac90b8b5dd9fd923a353afd4af74f3246ca5c and 2.3.1 should be https://github.com/dotnet/roslyn/commit/57c813192bd494bb15aaa841f415f28f50438e19.

**Comment by Pilchie** [comment]
@brettfo usually does this, but is on vacation right now.  @jasonmalinowski - do you want to take care of it?

**Comment by jasonmalinowski** [comment]
Unfortunately not going to be able to get to this before I leave either. I'll wait for @brettfo to be back next week.

**Comment by sharwell** [comment]
@dotnet/roslyn-infrastructure can you get these added?

**Comment by RikkiGibson** [comment]
https://github.com/dotnet/roslyn/releases/tag/version-2.3.0
https://github.com/dotnet/roslyn/releases/tag/version-2.3.1

For whatever reason the UI indicates that the original committers actually pushed the tags too, but in reality I did it just now :)
