### ISSUE TITLE
Weird missing assembly problem while calling Emit (not in insider version of Windows 10) 

### ISSUE THREAD

**Issue by scegg** [dotnet/roslyn#21684]
I'm trying to using Roslyn to compile C# code in Netfx46. Roslyn package is referred in a multi-targets dll solution, including net46 as one target. MetadataReferenceResolver is provided and ResolveMissingAssembly is overridden.

When I calling Emit from Windows 10 released version, Enterprise x64 15063, no matter VS is installed or not, there will be an exception thrown:

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Cryptography.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
>    at Microsoft.CodeAnalysis.CryptographicHashProvider.ComputeSha1(Byte[] bytes)
>    at Microsoft.CodeAnalysis.AssemblyIdentity.CalculatePublicKeyToken(ImmutableArray`1 publicKey)
>    at Microsoft.CodeAnalysis.AssemblyIdentity.get_PublicKeyToken()
>    at Microsoft.CodeAnalysis.AssemblyIdentity.KeysEqual(AssemblyIdentity x, AssemblyIdentity y)
>    at Microsoft.CodeAnalysis.AssemblyIdentity.EqualIgnoringNameAndVersion(AssemblyIdentity x, AssemblyIdentity y)
>    at Microsoft.CodeAnalysis.AssemblyIdentity.MemberwiseEqual(AssemblyIdentity x, AssemblyIdentity y)
>    at Microsoft.CodeAnalysis.AssemblyIdentityComparer.TriviallyEquivalent(AssemblyIdentity x, AssemblyIdentity y)
>    at Microsoft.CodeAnalysis.AssemblyIdentityComparer.Compare(AssemblyIdentity reference, String referenceDisplayName, AssemblyIdentity definition, Boolean& unificationApplied, Boolean ignoreVersion)
>    at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveReferencedAssembly(AssemblyIdentity reference, ImmutableArray`1 definitions, Int32 definitionStartIndex, AssemblyIdentityComparer assemblyIdentityComparer)
>    at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveReferencedAssemblies(ImmutableArray`1 references, ImmutableArray`1 definitions, Int32 definitionStartIndex, AssemblyIdentityComparer assemblyIdentityComparer)
>    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.AssemblyDataForMetadataOrCompilation.BindAssemblyReferences(ImmutableArray`1 assemblies, AssemblyIdentityComparer assemblyIdentityComparer)
>    at Microsoft.CodeAnalysis.CommonReferenceManager`2.Bind(TCompilation compilation, ImmutableArray`1 explicitAssemblies, ImmutableArray`1 explicitModules, ImmutableArray`1 explicitReferences, ImmutableArray`1 explicitReferenceMap, MetadataReferenceResolver resolverOpt, MetadataImportOptions importOptions, Boolean supersedeLowerVersions, Dictionary`2 assemblyReferencesBySimpleName, ImmutableArray`1& allAssemblies, ImmutableArray`1& implicitlyResolvedReferences, ImmutableArray`1& implicitlyResolvedReferenceMap, DiagnosticBag resolutionDiagnostics, Boolean& hasCircularReference, Int32& corLibraryIndex)
>    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)
>    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation)
>    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetRuntimeMetadataVersion(EmitOptions emitOptions)
>    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetRuntimeMetadataVersion(EmitOptions emitOptions, DiagnosticBag diagnostics)
>    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CreateModuleBuilder(EmitOptions emitOptions, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, IEnumerable`1 manifestResources, CompilationTestData testData, DiagnosticBag diagnostics, CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.Compilation.CheckOptionsAndCreateModuleBuilder(DiagnosticBag diagnostics, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream metadataPEStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, Stream metadataPEStream, CancellationToken cancellationToken)

This exception is thrown while calling Emit. Though MetadataReferenceResolver is provided, but ResolveMissingAssembly is not called.

While running the same code in Windows Insider Version (Enterprise x64 16257), it works like a charm. No problem at all.

And, I tried to send the compiled exe among these testing computers. No matter the exe file came from, exception will always be thrown in Windows released version and not in insider version. Even, the problem is gone after I upgrade one computer from released version to insider version.

Testing source code: https://github.com/scegg/CSharpRoslynAgency
Just download all source code, compile and select to start NetFxConsole project.

Any idea?
Thanks.

**Comment by jaredpar** [comment]
> While running the same code in Windows Insider Version (Enterprise x64 16257), it works like a charm. No problem at all.

@bartonjs have you seen this issue before?

My instinct is this is an issue with app.config missing a binding redirect. However I can't see how it would work in one version of windows but not the other.

**Comment by bartonjs** [comment]
@jaredpar Nope, but my instinct is the same as yours.

**Comment by jaredpar** [comment]
@scegg can you check to see if there is an entry for that DLL in the generated `exe.config` file in the output directory?

**Comment by bartonjs** [comment]
> However I can't see how it would work in one version of windows but not the other.

Maybe the new version has 4.7.1 preview installed, and maybe we have a binder change there.  Two maybes to @AlexGhiondea

**Comment by AlexGhiondea** [comment]
We do have a binder change in 4.7.1 -- but that should work as the facade exists in 4.7.1.
Do you have a repro?

**Comment by scegg** [comment]
Thanks for your reply.
@jaredpar @bartonjs 
Here is the app config:

> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>   <startup>
>     <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6" />
>   </startup>
>   <runtime>
>     <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
>       <dependentAssembly>
>         <assemblyIdentity name="System.IO.Compression" publicKeyToken="b77a5c561934e089" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
>       </dependentAssembly>
>     </assemblyBinding>
>     <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
>       <dependentAssembly>
>         <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-1.2.1.0" newVersion="1.2.1.0" />
>       </dependentAssembly>
>     </assemblyBinding>
>   </runtime>
> </configuration>

@bartonjs 
This solution is built in net46. If the computer has 471 installed, should the chosen one be 4.6?
The computers for testing have net46 framework and net46 target installed.

@AlexGhiondea 
You could download the full code for testing from github and compile it.
https://github.com/scegg/CSharpRoslynAgency

**Comment by scegg** [comment]
My design is compiling code created dynamically and reflecting the generated assemblies into users' host apps. Please give me a way that do not need to change app.config manually, which I cannot do.

**Comment by AlexGhiondea** [comment]
@scegg I looked into this and the exception is coming from trying to load Microsoft.CodeAnalysis. That assembly has a reference to System.Security.Cryptography.Primitives 4.0.0.0.

I added a reference to that to your project (NetfxConsole) and that fixed the issue.

**Comment by scegg** [comment]
@AlexGhiondea 
Thanks. It works but this solution is not acceptable. Referencing System.Security.Cryptography.Primitives in RoslynPackage (which references Roslyn) or NetFxTest (which references RoslynPackage cannot fix this issue. But the exe entry is out of my controlling scope. I have to find a way to fix this in RoslynPackage project. It's weird that you have to reference something specifically because you using a component which used another component need some reference.

**Comment by jaredpar** [comment]
Closing. Agree that this is an issue and a troublesome one for package authors. But fixing this can't be done in Roslyn. Believe this needs to be filed against [corefx](https://github.com/dotnet/corefx)
