### ISSUE TITLE
Runtime Exception : Could not load file or assembly 'Microsoft.VisualStudio.LanguageServices, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.  The system cannot find the file specified.

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#21690]
**Version Used**: 
2.3.1

**Steps to Reproduce**:

1. Create a .VSIX project using Visual Studios 2015 Update 3. 
2. Add Nuget References to following:
 Microsoft.Net.Compilers (2.3.1)
 Microsoft.CodeAnalysis (2.3.1)
 Microsoft.VisualStudio.LanguageServices(2.3.1)

3. Following code is used for getting the current solution instance:
```
var componentModel = (Microsoft.VisualStudio.ComponentModelHost.IComponentModel)Microsoft.VisualStudio.Shell.Package.GetGlobalService(typeof(Microsoft.VisualStudio.ComponentModelHost.SComponentModel));
VisualStudioWorkspace workspace = componentModel.GetService<VisualStudioWorkspace>();
``` 

4. When we run the .VSIX package in debug mode and try to run the above code an exception is thrown :  **Could not load file or assembly 'Microsoft.VisualStudio.LanguageServices, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.  The system cannot find the file specified.**

Important points:
1. I am having Visual Studios 2015 Update 3 Community version and Visual Studios 2017 Community Version installed on my machine.
2. The  **Microsoft.VisualStudio.LanguageServices** dll reference has **Copy Local** option set to **True**.
3.  When in debug mode, if we check on the **Modules** under **Debug**, we can see a reference to 
**Microsoft.VisualStudio.LanguageServices.dll**  and its pointing to the path **C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.LanguageServices.dll**
4. In one of the online posts related to this similar issue (https://stackoverflow.com/questions/45314485/reference-problems-in-visual-studio-extension) a suggestion for using **<ForceIncludeInVSIX>true</ForceIncludeInVSIX>** resolves this exception but throws a casting exception as mentioned. But overall this approach looks a kind of a hack.

**Expected Behavior**:
The current Solution should be loaded in the **VisualStudioWorkspace** reference.

**Actual Behavior**:
Could not load file or assembly 'Microsoft.VisualStudio.LanguageServices, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.  The system cannot find the file specified.

**Comment by Pilchie** [comment]
For extensions to Visual Studio, you need to ensure that you reference the same (or earlier) version of Roslyn, since VS will have already loaded it before your extension.  In this case, for VS 2015 Update 3, that would be 1.3.2.

**Comment by abhijitparkhi1983** [comment]
Thanks @Pilchie 

So do i have to add a package for Microsoft.VisualStudio.LanguageServices alone with Version 1.3.2? 
Or should i even have the packages for Microsoft.Net.Compilers and Microsoft.CodeAnalysis to be of Version 1.3.2?

**Comment by Pilchie** [comment]
`Microsoft.Net.Compilers` doesn't matter - that just indicates what compiler is used to compile your code, it has no effect on dependencies at runtime.

`Microsoft.CodeAnalysis` - this should be at 1.3.2.
