### ISSUE TITLE
Simplifier doesn't offer to remove unnecessary namespaces for generic types referenced inside crefs

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#2170]
![capture](https://cloud.githubusercontent.com/assets/10579684/7265482/5ae8954a-e84f-11e4-961e-a8bad5b3dc2c.PNG)

**Comment by CyrusNajmabadi** [comment]
Not repro.  We do gray it out:

![image](https://user-images.githubusercontent.com/4564579/198702331-b8e1698e-b158-4480-9481-818c22410513.png)

and offer to simplify:

![image](https://user-images.githubusercontent.com/4564579/198702365-a72ebeb5-2f76-494c-9653-97864187a307.png)
