### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpFormatting.PasteCodeWithLambdaBody test is flaky

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#21700]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.4.x/job/windows_debug_vs-integration/16/

**Comment by dpoeschl** [comment]
```
MESSAGE:
System.Runtime.InteropServices.COMException : Call was rejected by callee. (Exception from HRESULT: 0x80010001 (RPC_E_CALL_REJECTED))
+++++++++++++++++++
STACK TRACE:
at EnvDTE._DTE.ExecuteCommand(String CommandName, String CommandArgs) at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.Editor_OutOfProc.Paste(String text) at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpFormatting.PasteCodeWithLambdaBody() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpFormatting.cs:line 107
```

**Comment by tmat** [comment]
Another hit: https://ci.dot.net/job/dotnet_roslyn/job/dev15.5.x/job/windows_debug_vs-integration_prtest/125/

**Comment by rchande** [comment]
@dpoeschl @jinujoseph Can you help assign this to someone else?

**Comment by cston** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master-vs-deps/job/windows_release_vs-integration_prtest/33/

**Comment by mavasani** [comment]
Another failure: https://ci.dot.net/job/dotnet_roslyn/job/features_compiler/job/windows_release_vs-integration_prtest/169/

**Comment by CyrusNajmabadi** [comment]
Haven't seen any failures here in years.  CLosing out.
