### ISSUE TITLE
Add range constrained integer type

### ISSUE THREAD

**Issue by codecore** [dotnet/roslyn#21706]
Instead of code like this:
        public static BessWarnings GetBessWarningForEsu(int esuIndex)
        {
            if (esuIndex < 0 || esuIndex > 15)
            {
                throw new ArgumentOutOfRangeException();
            }
            return (BessWarnings)(1 << esuIndex);
        }
We could have this:

public static BessWarnings GetBessWarningForEsu(int[0,15] esuIndex)
{
    return (BessWarnings)(1 << esuIndex);
}

Also, add new keyword 'retrun' that acts just like 'return' :)

**Comment by jcouv** [comment]
Issues in the roslyn repo track compiler issues. For language issues or suggestions, please use the csharplang repro.
As it stands, this compiler issue is "by design". I'll let you start a  csharplang discussion about the feature request/suggestion. Thanks!

**Comment by codecore** [comment]
Done.
https://github.com/dotnet/csharplang/issues/846
Thanks!
