### ISSUE TITLE
Please make weak reference a language feature instead of class

### ISSUE THREAD

**Issue by ygc369** [dotnet/roslyn#2171]
I have committed this issue in coreclr repo, but they told me to commit here. https://github.com/dotnet/coreclr/issues/756
Current weak reference is class, when we use it, we must alloc slots from short or long weak reference table. Thus we can't use too many weak references. But I think this is not necessary. When GC happens, CLR can update strong references of living objects after compaction, why not update weak references of freed objects to be null at the same time? So weak reference can be a language feature instead of class, for example, use keyword "weakref" to specify a variable to store weak reference of an object.
Example:
Class A
{
weakref int[] a;
weakref object b;
};

**Comment by JohnnyBravo75** [comment]
I vote for this.
Here is another thrad that deals with weak events and weak references.
#101

**Comment by ygc369** [comment]
Apple's Swift language has this feature.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
