### ISSUE TITLE
Possible dead-lock during execution of Roslyn.VisualStudio.CSharp.UnitTests.dll!Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Interactive.Commands.InteractiveCommandHandlerTests.TestExecuteInInteractiveWithDefines test

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#21714]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit32_prtest/9134/

**Comment by AlekseyTs** [comment]
This failure could be the same issue: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.5.x/job/windows_release_unit64/21/

**Comment by dpoeschl** [comment]
Artifacts missing. Reopen if this occurs again.
