### ISSUE TITLE
System.AppDomainUnloadedException is thrown by Roslyn.VisualStudioIntegrationTests

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#21713]
https://ci.dot.net/job/dotnet_roslyn/job/features_DefaultInterfaceImplementation/job/windows_debug_vs-integration_prtest/55/

  Finished:    Roslyn.VisualStudioIntegrationTests
System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.

**Comment by AlekseyTs** [comment]
Here is another instance of the same exception: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration/1489/

**Comment by AlekseyTs** [comment]
Bumping the priority. @dotnet/roslyn-ide Please investigate the test failure.

**Comment by jasonmalinowski** [comment]
This is being tracked by #15497.
