### ISSUE TITLE
Move unix builds back to toolset package

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#21725]
The change to use the 2.0 SDK will disable the toolset compiler when running on Unix. This is due to a chicken and egg problem:

- Microsoft.NetCore.Compilers: contains a csc / vbc pair which target netcoreapp 1.1.
- CLI repo: uses Microsoft.NetCore.Compilers but rewrites deps file make csc / vbc be a netcoreapp 2.0.
- Roslyn repo: can't produce netcoreapp 2.0 binaries until we move to 2.0 SDK.

Our Unix builds work today because we are using dotnet 1.1. This matches the netcoreapp version in our toolset package. But moving to 2.0 SDK moves to dotnet 2.0 and hence csc / vbc will no longer run (1.1 apps don't run on 2.0). 

To make this all work out we will stage the changes as follows:

1. Disable toolset compiler on Unix builds 
1. Merge 2.0 SDK change back into master
1. Make the next Microsoft.NetCore.Compilers package our new toolset for Unix and re-enable toolset builds.

**Comment by jaredpar** [comment]
@agocke I believe u have already fixed this. If so please confirm and close this out.

**Comment by agocke** [comment]
Yes, I fixed this by updating to a new version of the Microsoft.NETCore.Compilers package.
