### ISSUE TITLE
"Internal error in the C# compiler" in Intermediate Window on netcoreapp

### ISSUE THREAD

**Issue by conniey** [dotnet/roslyn#21729]
**Version Used**: 
Microsoft Visual Studio Enterprise 2017 
Version 15.3.0
VisualStudio.15.Release/15.3.0+26730.3
Microsoft .NET Framework
Version 4.7.02046
.NET Core Tools (dotnet --version)
2.0.0

**Steps to Reproduce**:
1. Download IntermediateWindowRepro.zip
2. Put breakpoint on Program.cs: Line 14
3. Press F5
4. In Intermediate Window, try to evaluate: `var version2 = VersionRange.Parse("[15.1.1012]");`

**Expected Behavior**:
* It evaluates it, creates a variable, version2 with the same information as `version` in Line 10. 
* It works when you use a full .NET Framework console application.

**Actual Behavior**:
Internal error in the C# compiler

**Comment by jcouv** [comment]
@conniey Thanks for reporting this. Could you share the link to the zip file with the repro?
Or even better, could you try making a dump file for that crash? ([instructions](https://github.com/dotnet/roslyn/wiki/Troubleshooting-tips#capturing-a-crash-dump)).

**Comment by conniey** [comment]
Oops. I totally forgot to upload the repro. Here it is. I'll go and try to fetch the dump now.
[IntermediateWindowRepro.zip](https://github.com/dotnet/roslyn/files/1252593/IntermediateWindowRepro.zip)

**Comment by conniey** [comment]
I added those registry keys.. but no dumps were generated when I repro'd the issue.
![image](https://user-images.githubusercontent.com/10136526/29726294-0038a06c-8984-11e7-91e5-b2a4deb83153.png)

**Comment by The-MAZZTer** [comment]
I may be seeing a similar issue. Any attempt to create variables in the immediate window seems to cause this error for me.

**Comment by arvin-a** [comment]
Using 15.7.6. This issue still persists.

**Comment by tmat** [comment]
This is a bug in the VS debugger: Tracked internally by https://devdiv.visualstudio.com/DevDiv/_workitems/edit/395494
