### ISSUE TITLE
After installing .NET Compiler Platform SDK in VS 2017(15.3.2), "Roslyn Syntax Visualizer" is not visible in the "Other Windows" list.

### ISSUE THREAD

**Issue by namkilee** [dotnet/roslyn#21735]
**Version Used**: 
* Visual Studio ( 15.3.2 )
![image](https://user-images.githubusercontent.com/5918184/29712064-ea53c44e-89d2-11e7-97be-6456c2af4436.png)
* .NET Compiler Platform SDK ( 2.0.0.6140902 )
![image](https://user-images.githubusercontent.com/5918184/29712084-092512ce-89d3-11e7-9bae-773cc7f8ae3f.png)

**Steps to Reproduce**:
https://github.com/dotnet/roslyn/wiki/Syntax%20Visualizer
1.  .NET Compiler Platform SDK extension install in Visual Studio 2017 Marketplace
2.  Create C# Project using Project Wizard ( C# Console Application .NET Framework )
3.  To launch Syntax Visualizer : View -> Other Windows -> Roslyn Syntax Visualizer
4. Check Other Windows list.

**Expected Behavior**:
Exist "Roslyn Syntax Visualizer" in "Other Windows" list 
**Actual Behavior**:
Not exist
![image](https://user-images.githubusercontent.com/5918184/29712254-f2fbe404-89d3-11e7-9eb4-f7b6244d85cd.png)

**Comment by tanveerbadar** [comment]
Same for me.

**Comment by brandonr1** [comment]
I had the same issue, I ran update 15.3.3 and it resolved the problem.

**Comment by Pilchie** [comment]
@jmarolf ?

**Comment by jmarolf** [comment]
@namkilee are you able to use the templates installed with the SDK? I can't reproduce this on my 15.3 machine

**Comment by namkilee** [comment]
@jmarolf 
Yes, I able to use the template "Analyzer with Code Fix".
However, the menu was still invisible. 
So I reinstalled VS, confirmed that the problem was fixed after the update.
Maybe I have a problem with my machine.

**Comment by nathvi** [comment]
This is not fixed. Who closed this issue.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #83](https://github.com/dotnet/roslyn-sdk/issues/83) via [**ZenHub**](https://www.zenhub.com/)
