### ISSUE TITLE
Handle additional cases in determining VB compound assignments for IOperations

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#21738]
See https://github.com/dotnet/roslyn/pull/21407#issuecomment-324813243

**Comment by mavasani** [comment]
We don't seem to be detecting `x ^= y` and `x &= y` as compound operator expressions. See unit test `TestBinaryCompoundOperators`

**Comment by AlekseyTs** [comment]
I believe that is because there is a conversion on top of the binary operator.
