### ISSUE TITLE
Should we should represent C# + operation with string operands as `BinaryOperatorKind.Concatenate`

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#21737]
We return Concatenate kind only for the VB Concatenate operator. Should we should represent C# + operation with string operands as `BinaryOperatorKind.Concatenate`?

**Comment by mavasani** [comment]
See https://github.com/dotnet/roslyn/pull/21407#discussion_r135129263

**Comment by heejaechang** [comment]
Lets keep the current API, after confirm C# never returns this operator kind.

**Comment by mavasani** [comment]
Confirmed that C# never uses this OperatorKind.
