### ISSUE TITLE
Namespace resolution is buggy.

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#21753]
I'm using VS 2017 and creating some class libraries.

One library has a namespace Me.System.Services - so far so good, nothing major here.

I then added a Form to this project and the Forms designer creates code when I add buttons etc.

The .Designer.cs code fails to compile though.

It says:

`            this.button1 = new System.Windows.Forms.Button();
`

Is errant and underlines 'Windows' citing error: CS0234

`The type or namespace name 'Windows' does not exist in the namespace 'Me.System' (are you missing an assembly reference?)`

I tried to fix this by adding:

`using System = global::System;
`

hoping this would force the compiler to see 'System' as the root term in the namespace, but this has no effect and the compiler error remains. Also no code in the file refers in any way to Me.System, other than the source file's (form's) namespace:

`namespace Me.System.Services
`

Technically there is no ambiguity here yet the compiler claims there is. I'd understand if my namespace began simply 'System' but it begins 'Me.System' to AVOID ambiguity.

As it stands this is not good and pretty much rules out users from using certain terms in their namespaces in ways that are far from easy to understand. Of course - ordinarily - I'd prefix the namespaces in the statements with global:: but I cannot do that here because the code is auto-generated by the designer every time I tweak the UI.

Do others agree this is a bug? Should not: 

`using System = global::System`

be sufficient for the compiler to proceed?

(Bear in mind that this class library has already been published and consumed without issue but now I am unable to add the forms stuff).

Actually I lie, the form has been made generic like:

`    partial class ServiceControllerForm<T> where T : ServiceApplication, new()
`

and ServiceApplication sits in namespace Me.System.Services.

**Comment by svick** [comment]
> Technically there is no ambiguity here yet the compiler claims there is.

No, the compiler claims that `Me.System` takes precedence over `global::System`. That's not ambiguous, even if it's not the behavior you want. I believe this behavior is correct: when you're in the namespace `A.B.C`, `B.D` refers to `A.B.D`, even if it doesn't exist, not to `global::B.D`.

> Should not `using System = global::System` be sufficient for the compiler to proceed?

I suspect this is not a bug (but I haven't checked the spec). What seems to work is to move the using alias directive inside the namespace. Your code will look something like this:

```c#
namespace Me.System.Services
{
    using System = global::System;

    // the problematic types here
}
```

Though this requires you to modify the designer code, so I don't know if it's actually going to help you.

**Comment by Korporal** [comment]
@svick - It helps hugely! I was unaware one could embed using directives within namespaces, your suggestion works fine because the Forms designer does not re-generate the entire .cs file but only the InitializeComponent methods (and appends declared stuff at end of the class. It seems that the added 'using' survives modifications to the form made in the designer, thanks!

**Comment by sharwell** [comment]
The two main options I see are:

1. Modify the forms generator to use globally-qualified identifiers instead of just fully-qualified identifiers
2. Expressly not handle this case

Either way, if something changes it would be part of another project inside Microsoft. It appears the Roslyn portion is handling everything as expected.

@Pilchie suggestions?

**Comment by Korporal** [comment]
@svick @sharwell - I am still inclined to argue that the namespace logic does seem flawed here. I'd (quite reasonably I think) assumed that by defining:

`using System = global::System`

that the compiler would consider all names (within that scope) that begin **System.** to no longer be sub elements of a parent namespace, that's a reasonable thing to assume I think and intuitively arises from the **global::** prefix.

If **global::** doesn't mean "The following namespace name has no parent" then what does it actually mean?

**Comment by sharwell** [comment]
> ... that the compiler would consider all names (within that scope) that begin **System.** ...

@Korporal Your observation is what happens, but the key here is "within that scope". If you place the `using` directive inside the `namespace` element, it will consider the `using` directive before looking to parent namespaces. If you place the `using` directive outside the `namespace` element, it will consider the namespace element (and thus the parent namespaces) before the `using` directive.

**Comment by gafter** [comment]
This is by design. I'm glad you have a workaround for the problem it causes you.
