### ISSUE TITLE
Crash caused by GetEnclosingNamedType returning null in incomplete expression bodied member

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#21766]
```C#
public static class Extensions { public static T Get<T>(this object o) => $$}
```

(Note that the caret is immediately touching the closing brace).
If you type `o` at the caret position, completion crashes because SemanticModel.GetEnclosingNamedType returns null at https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationService.cs#L271.

This seems like a compiler bug given that GetEnclosingNamedType doesn't return null if you put the caret next to the arrow instead.

Ported from https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=420697&_a=edit

**Comment by rchande** [comment]
https://github.com/dotnet/roslyn/pull/21767 adds an IDE regression test--please unskip when fixing.

**Comment by gafter** [comment]
The compiler doesn't have a concept of positions between characters. Its concept is positions on characters. In this case, the character is the close curly brace, which is not considered "within" the scope of the type. We might improve things by changing that.

**Comment by CyrusNajmabadi** [comment]
@Rekkonnect want to submit a PR unskipping the test?
