### ISSUE TITLE
Please trigger an event after GC every time.

### ISSUE THREAD

**Issue by ygc369** [dotnet/roslyn#2176]
Sometimes we want to do someting after GC, but we don't know when GC finish.

**Comment by MrJul** [comment]
That's not a work of the compiler, but the runtime, this should be redirected to https://github.com/dotnet/coreclr

That said, it's already possible today to know when a GC has completed (at least for blocking GCs), please see [GC Notifications](https://msdn.microsoft.com/en-us/library/cc713687%28v=vs.110%29.aspx).
