### ISSUE TITLE
Should IInstanceReferenceExpression use base type or current type for initializers

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#21769]
Currently, when we construct an initializer for a property defined on a base type, it will use the base type as the type of the instance reference, rather than the current type. An example:
```C#
class C
{
    void M1()
    {
        C2 c2 = new C2() { /*<bind>*/P1 = 1/*</bind>*/ };
    }
}

class C1
{
    public virtual int P1 { get; set; }
}

class C2 : C1
{
}
```
```
ISimpleAssignmentExpression (OperationKind.SimpleAssignmentExpression, Type: System.Int32) (Syntax: 'P1 = 1')
  Left: IPropertyReferenceExpression: System.Int32 C1.P1 { get; set; } (OperationKind.PropertyReferenceExpression, Type: System.Int32) (Syntax: 'P1')
      Instance Receiver: IInstanceReferenceExpression (OperationKind.InstanceReferenceExpression, Type: C1) (Syntax: 'P1')
  Right: ILiteralExpression (Text: 1) (OperationKind.LiteralExpression, Type: System.Int32, Constant: 1) (Syntax: '1')
```

Even though we're creating a new C2, the type of the instance being referenced in the initializer is C1. The question here is whether that instance, from an API user's perspective, should be C1 or C2. See https://github.com/dotnet/roslyn/pull/21625#discussion_r134359307. Tagging @dotnet/analyzer-ioperation @AlekseyTs.

**Comment by CyrusNajmabadi** [comment]
Design decision: We would like IInstanceRefExpressoin here to have type C2.  Also, need to validate behavior for VB as well.
