### ISSUE TITLE
Using Deconstruct indicates the whole method body for the source to the PDB

### ISSUE THREAD

**Issue by bartonjs** [dotnet/roslyn#21773]
**Version Used**: 2.0.0-rc-61104-10  5bfc051d4e (Used in dotnet/corefx)

![image](https://user-images.githubusercontent.com/10642668/29795274-6287a190-8c00-11e7-9497-c5a5b7d90650.png)

**Steps to Reproduce**:

1.  Write a method that returns a tuple
2.  Invoke the method with deconstruction syntax
3.  Put a breakpoint on the line previous to the invocation.
4.  Step over (onto the line with the deconstructor call)

**Expected Behavior**: The current statement is highlighted.

**Actual Behavior**:  The entire method is highlighted.

![image](https://user-images.githubusercontent.com/10642668/29795350-b4045e1e-8c00-11e7-99b8-a41922b5c0dd.png)
![image](https://user-images.githubusercontent.com/10642668/29795357-c1bbe39c-8c00-11e7-9402-1127c51b841a.png)
![image](https://user-images.githubusercontent.com/10642668/29795366-cf364c92-8c00-11e7-9e79-1ceebab1f46c.png)

**Comment by tmat** [comment]
@jcouv Seems like a sequence point is off.

**Comment by jcouv** [comment]
Thanks Jeremy for reporting this.
I was able to repro with simple program below on the build you indicated (15.0, 5bfc051d4). The bug no longer repros on 15.3 (compiler version 2.3).
I'll add a test.

```C#
class C
{
   public static void Main()
   {
      var c = new C();
      (var x, var y) = c;
      System.Console.WriteLine(x + " " + y);
   }

   void Deconstruct(out int x, out int y) {
      x = 1;
      y = 2;
   }
}
```

**Comment by jcouv** [comment]
Added test to prevent regressions.

**Comment by bartonjs** [comment]
Looks like CoreFx has now upgraded to 2.0.0-rc4-61404-07 (53f2a8744e), and I don't see the problem anymore.

**Comment by jcouv** [comment]
Nice. Thanks for the validation.
