### ISSUE TITLE
IBlockStatement should not filter out all OperationKind.None

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#21776]
Currently, when we create `IBlockStatement`s, we filter out all `OperationKind.None` operations. We should not do this, and figure out why this is there.

**Comment by AlekseyTs** [comment]
I am surprised we haven't fixed this already. CC @jinujoseph I think issues that lead to a loss of information should be high priority.

**Comment by jinujoseph** [comment]
yes , this looks like got missed among other things. Don't think this meets the 15.7 bar. 
moving to 15.8 
thanks for the ping
