### ISSUE TITLE
Please permit `nameof(global::N)`

### ISSUE THREAD

**Issue by Przemyslaw-W** [dotnet/roslyn#21787]
Hi,

Consider code:
```
namespace N
{
    class C
    {
        void Foo()
        {
            Console.WriteLine(nameof(global::N.C));
            Console.WriteLine(nameof(global::N));
        }
    }
}
```
First statement compiles just fine, second emits error. Why is handling of namespace and class different here?

**Comment by svick** [comment]
> Why is handling of namespace and class different here?

It's not. The error is "error CS8083: An alias-qualified name is not an expression." And that's the issue: syntactically, the code inside `nameof` has to be an *expression*. `A`, `A.B` and `global::A.B` are all syntactically valid expressions, but `global::A` is not.

So, the difference isn't between namespace and class, it's about the exact syntax used. This means that `nameof(global::N.M)` is valid, even though `N.M` is a namespace. And `nameof(global::C)` is not valid, even for class `C` that's in the global namespace.

The decision to make `nameof` accept only code that's syntactically an expression means it has some other annoying restrictions (see https://github.com/dotnet/csharplang/issues/702). If lifting those restrictions was considered, maybe the `global::N` case could be considered at the same time?

**Comment by Przemyslaw-W** [comment]
Now I can see what the issue is, thanks.

Imo this restriction seems a bit artificial and alias qualified names should be legal inside nameof. Please treat this issue as vote up for lifting these restrictions.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #911](https://github.com/dotnet/csharplang/issues/911) via [**ZenHub**](https://www.zenhub.com/)
