### ISSUE TITLE
[Req] CallerArgExpressionAttribute ?

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/roslyn#2178]
Hi!

Our code heavily uses code assertions ala

```cs
Code.NotNull(someArg.SomeProperty, "someArg.SomeProperty");
// or 
Code.AssertArgument(index >=0 && index < Count, "index", "Index out of range");
```

The implementation is pretty trivial (actually, it is not. Details skipped as irrelevant):

```cs
public static void NotNull<T>(T value, string argName) where T: class
{
  if (value == null) throw new ArgumentNullException(argName);
}
public static void AssertArgument(bool condition, string argName, string message)
{
  if (!condition) throw new ArgumentException(message, argName);
}
```

Main issue with this approach is that you need to write the assert condition twice. First, as a code and second - as a text. The second one never shown to user and used to ease issue investigation on failure. 
If there are tens or hundreds of assertions across the code it's not a problem to maintain assertions and text messages in sync. 

But when there are a thousand of them there's always a chance someone will just copy assertion block without correcting the text message.
C# has attributes for similar use cases already: `[CallerMemberName]`, `[CallerFilePath]`, `[CallerLineNumber]`. My proposal is to add the fourth, called something like `CallerArgExpressionAttribute(string argName)`. Example usage:

```cs
public static void AssertArgument(
  bool condition,
  [CallerArgExpression("condition")] string conditionText = "")
{
  if (!condition) throw new ArgumentException("Assertion failed: " + conditionText);
}

Code.AssertArgument(index >=0 && index < Count);
// throws "Assertion failed: index >=0 && index < Count" exception
```

Thanks!

**Comment by jcouv** [comment]
I'll close this issue in favor of the csharplang discussion (https://github.com/dotnet/csharplang/issues/205) and championed issue (https://github.com/dotnet/csharplang/issues/287). Thanks
