### ISSUE TITLE
Formatting document not working with asp.net core 1.1 web project

### ISSUE THREAD

**Issue by developermj** [dotnet/roslyn#21788]
**Version Used**: Visual Studio 2017 15.3.2

**Steps to Reproduce**:

1. Start new asp.net core 1.1 web project
2. Copy paste c# code snippet from anywhere
3. Formatting is not automatically applied
4. Edit -> Advanced -> Format Document doesn't work

**Expected Behavior**:
1. Should format automatically
2. Should format when using "Format Document"

**Actual Behavior**:
1. Does not format at all.

**Comment by Pilchie** [comment]
@developermj - where did you paste the code?  In a .cs file, or a .cshtml file?

**Comment by developermj** [comment]
It was a cs file. However...I did a complete uninstall of VS2017 and my different .net core sdks and reinstalled latest versions and my issue went away. BTW. I didn't install .net core 1.1 sdk. It would seem the .net core 2.0 sdk is covering me (even though my app is still netcoreapp1.1)
