### ISSUE TITLE
Update VisualBasicOperationFactory.CreateBoundConversion to use GetConversion

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#21797]
https://github.com/dotnet/roslyn/pull/21445 will add a GetConversion method for VB, we should update CreateBoundConversion to use that method instead of replicating the functionality.

**Comment by jinujoseph** [comment]
verify and see if this is still needed

**Comment by 333fred** [comment]
Looks like this is not relevant at this point.
