### ISSUE TITLE
Generic Enums (Not sure if this is the right place for this)

### ISSUE THREAD

**Issue by chassq** [dotnet/roslyn#21813]
Recently I was trying to implement something like a Generic Enum Property. I looked at Enum and TEnum but they did not seem to provide what I needed. Is there any work to make Enums more flexible to work with (a la Java)? Thanks!

**Comment by svick** [comment]
Could you explain exactly what do you mean? How would the "generic enum property" look like and what would it do?

**Comment by AdamSpeight2008** [comment]
Is what you need anything like [CSharpLang # 104](https://github.com/dotnet/csharplang/issues/104)?

**Comment by chassq** [comment]
I believe that would be the general idea.

**Comment by sharwell** [comment]
This appears to be a duplicate of dotnet/csharplang#274, dotnet/csharplang#297, and/or dotnet/csharplang#104, depending on how @chassq was planning to use these types.

**Comment by chassq** [comment]
I think it does. Thanks for the response!
