### ISSUE TITLE
UI delay when opening RoslynDev hive with Roslyn.sln open

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#21838]
_From @rchande on July 24, 2017 20:28_

Check out and build the Roslyn master branch. 
Open Roslyn.sln in the Dev15 main hive and wait for the project to finish opening.
Start a new instance of VS in the RoslynDev hive `devenv /rootsuffix RoslynDev`.
Open a C# project in the new VS instance.

For some reason, doing this causes the VS with Roslyn open to hang. It looks like opening a project in the other hive is triggering the project system to reload Roslyn.sln in the main hive. Note that I don't see this if both instances are running in the same hive.

I see lots of blocked time in:
```C#

Name
--
\|                                         + microsoft.visualstudio.projectsystem!Microsoft.VisualStudio.ProjectSystem.TaskDelayScheduler+<ThrottleAsync>d__24.MoveNext()
\|                                          + microsoft.visualstudio.projectsystem.vs.implementation!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.ProjectReloadManager.<ScheduleProjectReload>b__43_0(value class System.Threading.CancellationToken)
\|                                           + mscorlib!AsyncTaskMethodBuilder.Start
\|                                            + microsoft.visualstudio.projectsystem.vs.implementation!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.ProjectReloadManager+<<ScheduleProjectReload>b__43_0>d.MoveNext()
\|                                             + microsoft.visualstudio.projectsystem.implementation!ProjectMultiThreadedService.ExecuteSynchronously
\|                                              + microsoft.visualstudio.threading.ni!JoinableTask.CompleteOnCurrentThread
\|                                               + microsoft.visualstudio.threading.ni!JoinableTaskFactory.WaitSynchronously
\|                                               \|+ microsoft.visualstudio.threading.ni!JoinableTaskFactory.WaitSynchronouslyCore


```

_Copied from original issue: dotnet/project-system#2652_

**Comment by davkean** [comment]
_From @srivatsn on July 24, 2017 20:39_

Is the project being opened in the RoslynDev hive part of Roslyn.sln? The project reloader should only be called if any of the csprojs in Roslyn.sln change - if you let this happen do you see any changes to any csproj in roslyn.sln?

/cc @jviau

**Comment by davkean** [comment]
_From @rchande on July 24, 2017 20:49_

It's a totally unrelated project.

**Comment by davkean** [comment]
_From @jviau on July 25, 2017 3:30_

Is opening the unrelated project causing a change to a .targets or .props file shared by a project in Roslyn.sln?

**Comment by davkean** [comment]
@rchande I believe I understand this - this is the compiler extension generating a new targets file in AppData. We're reloading based on it, we have another bugs that are tracking the performance of this reloading but I'll move this over to Roslyn.

**Comment by davkean** [comment]
@jasonmalinowski Not sure who owns the compiler extension - but can we change it to stop always writing a targets file? It's also breaking the up-to-date check.

**Comment by jasonmalinowski** [comment]
@davkean "owned" is a strong word here. But yes, trivial to change it to avoid the rewrite if the file already has the right content. Other than the perf impact, does it still functionally work if we do the overwrite? If a change is made to the extension and we need to write new contents we'll still have to write then.
