### ISSUE TITLE
Suggest out variable name

### ISSUE THREAD

**Issue by pawchen** [dotnet/roslyn#21837]
Say you have a method contains a bunch of `out` parameters,
```C#
void F(out int abcd, out int efgh, out int blah)
```
It would be great to suggest `abcd` when you type `F(out var `

**Comment by dpoeschl** [comment]
@rchande cool improvement to declaration completion.

**Comment by rchande** [comment]
@diryboy it looks like this already works:
![image](https://user-images.githubusercontent.com/3751401/30506180-b0347698-9a2e-11e7-8f28-59fb176d7683.png)

Can you share an example where it does not?

**Comment by diryboy** [comment]
Thanks for checking. In your screenshot, I also expect `g` on the list, as there could be multiple out variables of the same type.

I tried VS15.4 preview 2 but I did not see any suggested names. Perhaps this was added to a more recent version of VS?

**Comment by CyrusNajmabadi** [comment]
This is how it works now: 

![image](https://user-images.githubusercontent.com/4564579/217620244-22ed171a-89ee-434d-9282-ce8368b623d3.png)

**Comment by jnm2** [comment]
I think a duplicate ended up getting fixed: https://github.com/dotnet/roslyn/issues/43603
