### ISSUE TITLE
Ensure IOperation.Children never contains null

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#21849]
We should do a sanity check on our implementations and make sure that we're never returning null elements for IOperation.Children.

**Comment by sharwell** [comment]
:bulb: I'm really hoping to use cases like this and `ISymbol.Name` (#20493) to validate some of the work being done for nullable reference types.

**Comment by jinujoseph** [comment]
dupe of https://github.com/dotnet/roslyn/issues/21196
