### ISSUE TITLE
Unify handling of expression contexts where `this` is allowed

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#21846]
**Version Used**: Latest master branch with #21528 merged.

### Steps to Reproduce

```csharp
class Program
{
  private readonly object o = |;
}
```

### Expected Behavior

The `this` keyword is not recommended.

### Actual Behavior

The `this` keyword is included in the completion list, even though use of it will result in CS0027.

> Keyword 'this' is not available in the current context

### Additional information

Both `ThisKeywordRecommender` and `CSharpQualifyMemberAccessDiagnosticAnalyzer` need to know which expression contexts may use the `this` keyword. Currently the former fails to detect the above case properly, while the latter uses an inefficient LINQ construct. To resolve this issue, first identify an efficient and accurate means to handle the required cases, and then update both features to use it.

Tests for IDE0009 *should* already cover these cases, but the tests for `ThisKeywordRecommender` will likely need to be updated.

**Comment by Dunkhan** [comment]
Another case

```
var a = 1;
var b = new List<object> { a };//This line generates IDE0009
```

using completion results in compiler error

also 

`var c = new List<object> { null };//This line generates IDE0009`

completion has no effect

**Comment by CyrusNajmabadi** [comment]
closing out due to lack of feedback.
