### ISSUE TITLE
Predefined-type member access in doc comment cref parameter list is mis-parsed.

### ISSUE THREAD

**Issue by rawlinson** [dotnet/roslyn#21847]
**Version Used**: VS 15.4.0 Preview 1.0

**Steps to Reproduce**:
Add the following to an XML doc comment:
```
cref="Test(string.Empty)"
```
**Expected Behavior**:
The contents of the cref attribute should probably parse as:
```
NameMemberCref
    IdentifierName ...
    CRefParameterList
        OpenParenToken
        CRefParameter
            QualifiedName
                PredefinedType ...
                DotToken
                IdentifierName ...
        CloseParenToken	
```
**Actual Behavior**:
The parsing stops after the predefined type and subsequent tokens, including the closing paren, are skipped.
```
NameMemberCref
    IdentifierName ...
    CRefParameterList
        OpenParenToken
        CRefParameter
            PredefinedType
                StringKeyword
        CloseParenToken
            SkippedTokensTrivia ... "."
            SkippedTokensTrivia ... "Empty"
            SkippedTokensTrivia ... ")"
```
**Remarks**:
This only occurs when the predefined type is within a parameter list.
This is blocking a simple fix to #21758.

**Comment by sharwell** [comment]
> ```
> cref="Test(string.Empty)"
> ```

This is not a valid `cref` attribute value. Can you describe what you were attempting to reference, and I can provide the expected syntax?

**Comment by rawlinson** [comment]
You're right, I forgot the scope of cref! It matches the grammar and the equivalent framework type, i.e. `Test(String.Empty)`, parses 'properly', despite it not being a valid attribute value.
