### ISSUE TITLE
Improve and automate optprof data collection for Roslyn assemblies

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#21850]
Our existing scripts for optprof data collection are broken due to numerous changes. This forces us to manually run a bunch of steps to regenerate this data. We need to fix/write new scripts to automate this process. @KevinH-MS and @TyOverby should be able to give input about this work.

**Comment by tmat** [comment]
We also need an automated infrastructure to handle generating optprof data for CoreFX assemblies we insert into VS. This is currently done manually and it's a painful process requiring manual intervention in CoreFX build.

**Comment by tmat** [comment]
Should be addressed by https://github.com/dotnet/arcade/issues/99

**Comment by genlu** [comment]
Closing old OptProf issues. No longer relevant.
