### ISSUE TITLE
Lightbulb in class lib project should recommend adding package references to correct NuGet packages instead of an assembly ref

### ISSUE THREAD

**Issue by danroth27** [dotnet/roslyn#21859]
**Version Used**:  VS 15.3.2

**Steps to Reproduce**:

1. Create a new .NET Standard Class Library
2. Add some code that uses an ASP.NET Core type, like `IHostingStartup` or whatever:

``` C#
    public class KeyVaultHostingStartup : IHostingStartup
    {
    }
```

3. Hit `ctrl-.` on the ASP.NET Core type

**Expected Behavior**:

Light-bulb suggestion to add a package reference to the correct NuGet package (Microsoft.AspNetCore.Hosting.Abstractions in this case)

**Actual Behavior**:

Light-bulb suggestion to add an **assembly reference** to the assembly in the package fallback location

![image](https://user-images.githubusercontent.com/1874516/29949579-9ab982ba-8e6a-11e7-997b-b25701f4cf73.png)

**Comment by Pilchie** [comment]
It's supposed to do this already...

**Comment by DustinCampbell** [comment]
I'm seeing this with 15.5 and it's driving me crazy. I hope we're going to get to this soon, because it breaks the feature pretty badly in .NET Core and .NET Standard projects. We should never be directly references packages in the fallback folder. Could we bump the priority on this one a bit?

**Comment by CyrusNajmabadi** [comment]
We do offer the package reference:

![image](https://user-images.githubusercontent.com/4564579/198750258-3a45b93b-9ab8-48aa-8637-97edb3ea9b50.png)

Closing out.
