### ISSUE TITLE
Generating .dll.config files !

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#21852]
Can anyone explain what is going on here:

https://developercommunity.visualstudio.com/content/problem/29031/dll-appconfig-being-built-in-vs-2017.html

We're building code and finding that .dll.config files are being generated. These are interfering with our applications when we deploy. 

We NEVER saw this with earlier versions of Visual Studio to my knowledge!

Thanks

**Comment by jcouv** [comment]
Relates to https://developercommunity.visualstudio.com/content/problem/19696/vs-always-copies-all-appconfig-files-to-output-fol.html

**Comment by Pilchie** [comment]
Maybe someone in https://github.com/Microsoft/MSBuild could help? @andygerlicher?

**Comment by jcouv** [comment]
The developercommunity issue was close as "not a bug". So I'll close the present issue.
If you want to follow up, the relevant repo is msbuild. Thanks
