### ISSUE TITLE
C# Break nested loop [Requested Feature]

### ISSUE THREAD

**Issue by Danthekilla** [dotnet/roslyn#21864]
In C# it would be fanstastic to have a language feature (probably syntactic sugar) that lets you break nested loops.

Currently these are the 2 ways you can break out of nested loops:

```
var foundValue;
for (int x = 0; x < xMax; x++)
{
    for (int y = 0; y < yMax; y++)
    {
        foundValue = GetValue(x, y);
        if (foundValue == valueToCompare)
            goto ENDOFLOOPS;
    }
}
ENDOFLOOPS:
```

```
var foundValue;
bool shouldBreak;
for (int x = 0; x < xMax; x++)
{
    for (int y = 0; y < yMax; y++)
    {
        foundValue = GetValue(x, y);
        if (foundValue == valueToCompare)
        {
            shouldBreak = true;
            break;
        }
    }
    if (shouldBreak)
        break;
}
```

I would like to propose the ability for a break to have a value for how many loops to break out of. Like so:

```
var foundValue;
for (int x = 0; x < xMax; x++)
{
    for (int y = 0; y < yMax; y++)
    {
        foundValue = GetValue(x, y);
        if (foundValue == valueToCompare)
            break 2;
    }
}
```

Not only is it slightly smaller, but I think easier to read.

Anyone have any thoughts on the matter?

**Comment by jcouv** [comment]
Issue moved to [dotnet/csharplang #869](https://github.com/dotnet/csharplang/issues/869) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jcouv** [comment]
@Danthekilla I moved your language feature request to the csharplang repo for discussion.
