### ISSUE TITLE
Low-level IOperation node with more than one parent

### ISSUE THREAD

**Issue by edgardozoppi** [dotnet/roslyn#21866]
Consider the following example:

```csharp
var i = 0; i++;
```

The `LocalRewriter` reuses some bound nodes when rewriting creating a DAG instead of a tree as result. In this particular example, the same `BoundLocal` node is reused inside the `BoundSequence` node created for `i++`. This cause the operation factories (both for C# and VB) to reuse the same generated IOperation ILocalReference node, leading to a failure in the second condition (`result == parent`) of the last assert of `SetParentOperation` method in `Operation` class.

```csharp
        protected void SetParentOperation(IOperation parent)
        {
            var result = Interlocked.CompareExchange(ref _parentDoNotAccessDirectly, parent, null);

            // tree must belong to same semantic model if parent is given
            Debug.Assert(parent == null || ((Operation)parent).SemanticModel == SemanticModel);

            // make sure given parent and one we already have is same if we have one already
            Debug.Assert(result == null || result == parent);
        }
```

Is very difficult to detect these cases inside the operations factories to clone the nodes instead of reusing them because this happen in a very specific scenarios like the above.

Is the resulting DAG intentional or we can fix this issue by creating a new BoundLocal node while rewriting the assignment expression? It could be probably more cases where the same kind of issue occurs, but I'm not sure. @dotnet/analyzer-ioperation @AlekseyTs

**Comment by AlekseyTs** [comment]
@edgardozoppi Lets discuss possible solution for this problem offline.
