### ISSUE TITLE
Make TypeDeclarationSyntaxExtensions a public class

### ISSUE THREAD

**Issue by vweijsters** [dotnet/roslyn#2186]
The `TypeDeclarationSyntaxExtensions` class is currently an internal class containing very useful extension methods that are unavailable for 3rd party code fix providers. After a quick scan of the code, there seems to be no reason why this class should be internal.

**Comment by CyrusNajmabadi** [comment]
There are good reasons these extensions aren't available.  We change them all the time (see many recent changes to move and refactor them), and we don't want to be beholden to maintaining these internal impl details as any sort of public contract.
