### ISSUE TITLE
default expression does not understand byref methods

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#21874]
**Version Used**: 2.3.1.61919 (57c81319)

**Steps to Reproduce**:

```csharp
struct X<T>
{
	public ref T this[int index] {
		get {
			return default;
		}
	} 
}
```

**Expected Behavior**:

No error or error message which makes sense

**Actual Behavior**:

error CS8150: By-value returns may only be used in methods that return by value

**Comment by svick** [comment]
I think the error message is correct and makes sense, though the wording is kind of confusing. Do you have alternative wording of the message?

**Comment by marek-safar** [comment]
I didn't find the spec for this but my feeling is that default should use `ref T` as the target type only `T` which would force you to write `return ref default` which looks quite odd to me.

**Comment by svick** [comment]
What would it be a reference to? `default` is a value, not a variable; `ref T` means you have to return a reference to some variable (usually a field or location in an array).

And `return ref default` doesn't work either:

> error CS8156: An expression cannot be used in this context because it may not be returned by reference

**Comment by jcouv** [comment]
I believe the current behavior is correct. Namely, in both cases the behavior is the same with `default` as it is with `default(T)`.

Ping @VSadov to confirmed this is the expected behavior with `default(T)`.

```C#
struct X<T>
{
	public ref T this[int index] {
		get {
			return default(T); // error CS8150: By-value returns may only be used in methods that return by value
		}
	} 
}
```
```C#
struct X<T>
{
	public ref T this[int index] {
		get {
			return ref default(T); // error CS8156: An expression cannot be used in this context because it may not be returned by reference
		}
	} 
}
```

**Comment by jcouv** [comment]
Confirmed with Vlad the behavior of `default(T)` (and target-typed `default`) are correct. It is an r-value, so cannot be `ref`'ed.

**Comment by VSadov** [comment]
It is basically a more general/generic case similar to ``` return ref 0 ```

**Comment by VSadov** [comment]
Re: "Methods that return by reference have to return a reference"  - I also think it might be more clear if it is worded this way.
