### ISSUE TITLE
Semantic Model: Required cast is faded as unnecessary

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#21882]
```C#
using System;

class Program
{
    unsafe static void Main()
    {
        int a = 0;
        IntPtr x = (IntPtr)(int*)&a;
    }
}
```

![image](https://user-images.githubusercontent.com/41759/29988082-4befa2d4-8f20-11e7-9247-63177530cc6b.png)

![image](https://user-images.githubusercontent.com/41759/29988108-640a437e-8f20-11e7-84f3-64181df62342.png)

```
Program.cs(8,21,8,27): error CS0119: 'IntPtr' is a type, which is not valid in the given context
```

**Comment by tmat** [comment]
@MadsTorgersen @gafter The error is kind of weird. Why do we not allow to cast an address to IntPtr?

**Comment by DustinCampbell** [comment]
The issue here is that, according to the SemanticModel, there's no conversion between `&a` and `(int*)`. Calling `SemanticModel.GetTypeInfo(...)` for either expression returns the PointerType System.Int32*. So, the cast analysis code sees it as an identity cast.

**Comment by tmat** [comment]
@DustinCampbell I see, seems like an issue in the compiler then. Correct?

**Comment by sharwell** [comment]
The problem here is the parser is trying to treat the `&` is the error case as the binary operator (bitwise AND). The general form for this would be the following:

```
IntPtr x = (IntPtr)(&a);
```

I imagine the reason this works without parentheses with the intermediate cast is `int*` is not a valid expression, so `(int*)` is parsed as a cast instead.

**Comment by DustinCampbell** [comment]
Ah! Of course, thanks @sharwell! This actually looks like a parenthesis simplification issue in that case. Remove Unnecessary Cast adds parentheses around the inner expression of an inner cast expression, and that parenthesized expression has a simplification annotation: https://github.com/dotnet/roslyn/blob/master/src/Features/CSharp/Portable/CodeFixes/RemoveUnnecessaryCast/RemoveUnnecessaryCastCodeFixProvider.cs#L74-L83. The simplifier shouldn't be removing the parentheses in this case.

**Comment by zaytsev-victor** [comment]
Can't reproduce on VS 2017 15.4.0 Preview 1
![914685b67e664e5741c6ab1eedd2559b](https://user-images.githubusercontent.com/23630781/30419661-e14c8530-993f-11e7-8a19-4fa40326f424.gif)
