### ISSUE TITLE
Navigate To doesn't highlight search term in results correctly if the matched string is longer than the search term

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21888]
_Ported from https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20IDE/_workitems?id=460431&_a=edit&triage=true by @davkean_

![image](https://user-images.githubusercontent.com/235241/29989928-3edce1be-8f2b-11e7-8be4-ba31073e8cbe.png)

The search term in "Go To All" includes the "a" at the end, but the bolding of the results in the list does not bold the "a" at the end.

Note: Conversely, we’re also facing an issue if we search “ae” and match æ

Note: The bolding is determined by NavigateToItem.Tag.NameMatchSpans (Microsoft.CodeAnalysis.Text.TextSpan) NavigateToItems are provided to us by the providers, which need to correctly interpret these tricky characters.

**Comment by dpoeschl** [comment]
@nguerrera (or please forward to whoever is doing glob/loc now), does this meet a tenet bar that would move it into an earlier milestone?

**Comment by nguerrera** [comment]
I don't quite understand the bug. It would be helpful to show an expected result vs. an actual result.

**Comment by dpoeschl** [comment]
Sorry, will update the OP. The search term in "Go To All" includes the "a" at the end, but the bolding of the results in the list does not bold the "a" at the end.

**Comment by CyrusNajmabadi** [comment]
The correct span is highlighted:

![image](https://user-images.githubusercontent.com/4564579/198750348-6dba7742-0218-4fd6-98a9-e15ee1ca7123.png)
