### ISSUE TITLE
F# intellisense for unused parameters/values just says "The value is unused"

### ISSUE THREAD

**Issue by cmeeren** [dotnet/roslyn#21891]
This is a rather contrived example, but consider these two images:

In the first one, I'm holding the mouse pointer over `x`:
![correct](https://user-images.githubusercontent.com/7766733/29818475-c7745af0-8cbc-11e7-9a1d-a29fd0cc4409.PNG)

In the second one, I'm holding the mouse pointer over `y`:
![wrong](https://user-images.githubusercontent.com/7766733/29818476-c79e9928-8cbc-11e7-92c3-c57a8e094311.PNG)

I'd expect Intellisense to show me type info also in the second example (together with the existing "unused" message). As it is now, I have to write a dummy usage (e.g. `let y' = y`) in order to get the type info on mouseover.

Due to the extensive type inference in F#, being able to see the type/signature at will seems quite important. (I know that variables shouldn't be unused in production code, but this situation arises frequently during active development.)

I'm using VS 15.3.2. In case it's relevant, the project in question is targeting PCL profile 259 and F# 4.1 (3.259.41.0). Let me know if you need more info.

ref. https://github.com/Microsoft/visualfsharp/issues/3518

**Comment by sharwell** [comment]
💭 This doesn't appear to be a Roslyn issue, but maybe I'm missing something. I tested this just now in C# and found the following using Visual Studio 2017 (15.3.3):

![image](https://user-images.githubusercontent.com/1408396/30062367-85309f2e-9210-11e7-8de5-31b3db04cff2.png)

**Comment by cmeeren** [comment]
What happens if you try it in F#?

There are conflicting reports in https://github.com/Microsoft/visualfsharp/issues/3518 as well. No idea what causes the difference in behavior. Any insights?

**Comment by Pilchie** [comment]
I believe Roslyn has some specific code to merge errors with quick info.  @rchande can you point at it?

**Comment by rchande** [comment]
When you see type info and error squiggles in the same popup, that is the result of two different quickinfo providers working and getting combined into one popup. One is the C#/F# language service providing type info. The other is built into the editor and adds the text from any error/warning squiggles that intersect with the cursor position. 

If F# isn't showing errors and typeinfo together, it's probably an issue with the spans F# is reporting for its error squiggles. 
Note, however, that I can't reproduce this on preview builds of Update 4:
![image](https://user-images.githubusercontent.com/3751401/30171070-b214673c-93a5-11e7-8d83-47d76f24a44d.png)

**Comment by dpoeschl** [comment]
@brettfo Can you confirm this doesn't repro on Update 4 and close out if so?

**Comment by cmeeren** [comment]
The bug appears to be a duplicate of https://github.com/Microsoft/visualfsharp/issues/3056 which contains more information. It appears there's a very simple Roslyn/VS fix (https://github.com/Microsoft/visualfsharp/issues/3056#issuecomment-343449101).

**Comment by cmeeren** [comment]
And by the way, templates are still missing from latest nightly (15.4.1.17111702).

**Comment by bender2k14** [comment]
@cmeeren, it looks to me like this issue can be closed (both because it was a duplicate of #3056 and because #3056 was resolved).  Is that correct?

**Comment by cmeeren** [comment]
Sure!

Wow, I haven't seen the issue badge limit before.

![image](https://user-images.githubusercontent.com/7766733/63360275-5f0cbd00-c36e-11e9-82ef-0a899e6d3000.png)
