### ISSUE TITLE
Discussion：Solution-based macros needed

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#21897]
**Version Used**: 
The latest version of C# or VB.NET

**BackGround**:
Until now in VS, we only have project-based macros, and you can imagine it won't be an easy thing to define macros or remove some of them and do changes for different kinds of publish versions. Imagine if you have many libraries with one executable main program, and some methods of libraries are published ONLY WHEN YOU HAVE THE MACRO OF "PRODUCT", while some published for "FREE"……. (depending on different kinds of conditions globally). Now I have to define these macros step-by-step one by one in "Project"=>"Build"=>"Conditional Compiler Symbol" ,and do removing one by one for different kinds of versions....

A typical example is that suppose I have several C# libraries with one executable Console app, and I have to define duplicated macros in as many as projects I have now. And for different kinds of version publishments, I need to carefully remove some macros or do something else and recompile, which is complicated and easy to make mistakes. Because these macros are managed unitedly belonging to the same solution. Why don't we have a globally-based macro mechanism (of course rules will be defined later after discussion).

**What to do for expections**
In fact there should be a nicer way (something like C++ maybe). I mean we can create some rules or ways to define a globally-based (Solution-based) macros. And all of the solution's files (*.cs) can share the macro and treat them as "pre-defined". This means you don't need to re-define duplicated macros.

**Comment by sharwell** [comment]
The new project system allows you to create a **Directory.Build.props** file in the solution folder (or any folder above the projects), and it will automatically be included in the build. I don't have an example right now where it was used for `DefineConstants`, but he's an example where it was used to suppress a specific pair of warnings across multiple projects:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/a70d5e6687ac818a85fe8c9760f0caf5a78dce99/StyleCop.Analyzers/Directory.Build.props#L49
