### ISSUE TITLE
'Inline out variable' breaks code logic

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#21907]
**Version Used**: 
```
Microsoft Visual Studio Professional 2017 
Version 15.3.3
VisualStudio.15.Release/15.3.3+26730.12
Microsoft .NET Framework
Version 4.7.02053
```

**Steps to Reproduce**:

Paste the following code into VS:
```cs
using System;

class Program
{
  static void Main(string[] args)
  {
    Method<string>();
  }

  public static void Method<T>()
  { 
    T t;
    void Local<T>()
    {
      Out(out t);
      Console.WriteLine(t);
    }
    Local<int>();
  }

  public static void Out<T>(out T t) => t = default;
}
```

**Expected Behavior**:
No suggestion to inline the variable `t` as its type cannot be used explicitly inside the `Local` function

**Actual Behavior**:
Roslyn suggests to change the code into following:
```cs
using System;

class Program
{
  static void Main(string[] args)
  {
    Method<string>();
  }

  public static void Method<T>()
  {
    void Local<T>()
    {
      Out(out T t);
      Console.WriteLine(t);
    }
    Local<int>();
  }

  public static void Out<T>(out T t) => t = default;
}
```

Which does not behave the same as Roslyn changes type argument of the `Out(out t)`  invocation from 'string' to 'int' so the program above prints `0` instead of an empty line.

**Comment by CyrusNajmabadi** [comment]
Inline-variable likely should not allow cross function inlining.

**Comment by sharwell** [comment]
:memo: The big failure here is the refactoring should have detected that the type of `t` changed as a result of the refactoring, and therefore disallowed it.

**Comment by zaytsev-victor** [comment]
I'm agree with @CyrusNajmabadi, because at least it can be a library method which will be used in other project.

**Comment by MhdTlb** [comment]
Can I work on this?

**Comment by sharwell** [comment]
@MhdTlb It looks like @zaytsev-victor already submitted a pull request for this. If you're looking for a good first issue, might I suggest #23043? :smile:

**Comment by TessenR** [comment]
The issue is not fixed correctly. I can still reproduce the same problem in the following code snippets using VS 15.5.1

It seems that the method [CanSafelyMoveLocalToBlock](https://github.com/dotnet/roslyn/pull/22107/files#diff-dc71a06723884de745877463c66827af) only checks if one containing local function hides the variables' type whereas it should check all of them up to the block containing the variable. This issue leads to incorrect suggestion in the following code:

```cs
using System;

class Program
{
  static void Main(string[] args)
  {
    Method<string>();
  }

  public static void Method<T>()
  {
    T t;
    void Local<T>()
    {
      void AnotherLocal()
      {
        Out(out t);
        Console.WriteLine(t);
      }
    }
    Local<int>();
  }

  public static void Out<T>(out T t) => t = default;
}
```

Also this method checks type parameters of a local function containing the variable. This seems pointless since type parameters can flow through nested local functions. Due to this check the following case also has the incorrect suggestion:

```cs
using System;

class Program
{
  static void Main(string[] args)
  {
    Method<string>();
  }

  public static void Method<T>()
  {
    void AnotherLocal()
    {
      T t;

      void Local<T>()
      {
        Out(out t);
        Console.WriteLine(t);
      }
      Local<int>();
    }

    AnotherLocal();
  }

  public static void Out<T>(out T t) => t = default;
}
```

Furthermore the method does not check constructed types properly, i.e. variables of any type which uses type parameters as its part still get incorrect suggestions. E.g. Roslyn incorrectly suggests changes to the following code snippet:

```cs
using System;

class Program
{
  static void Main(string[] args)
  {
    Method<string>();
  }

  public static void Method<T>()
  {
    T[] t;
    void Local<T>()
    {
      Out(out t);
      Console.WriteLine(t);
    }
    Local<int>();
  }

  public static void Out<T>(out T[] t) => t = new[] {default(T)};
}
```

There is also an incorrect assumption that type parameters can only be introduces by containing methods and local functions. Containing types are another possible source of type parameters which cause Roslyn to suggest incorrect changes in the following code:

```cs
using System;

class Program
{
  static void Main(string[] args)
  {
    C<string>.Lambda();
  }

  class C<T>
  {
    public static Action Lambda => () =>
    {
      T t;
      void Local<T>()
      {
        Out(out t);
        Console.WriteLine(t);
      }

      Local<int>();
    };
  }

  public static void Out<T>(out T t) => t = default;
}
```

ping @sharwell, @CyrusNajmabadi, @zaytsev-victor

**Comment by CyrusNajmabadi** [comment]
@TessenR PRs welcome :)

**Comment by binki** [comment]
@CyrusNajmabadi Should this issue be reopened or new issues filed for https://github.com/dotnet/roslyn/issues/21907#issuecomment-350807901 ?

**Comment by CyrusNajmabadi** [comment]
@binki i'd just file a new issue.  Cheers!
