### ISSUE TITLE
AttributeUsage of Methods is not scoped correctly to expression-bodied properties

### ISSUE THREAD

**Issue by Xenoprimate** [dotnet/roslyn#21901]
**Version Used**: .NET Core 2, C# 7, VS 2017 Community 15.3.2

**Steps to Reproduce**:

```
using System;
using System.Runtime.CompilerServices;
					
public class Program {
	
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public string X => "X";
	
	public string Y {
		[MethodImpl(MethodImplOptions.AggressiveInlining)] get => "Y";	
	}
	
	public static void Main() { }
}
```

**Expected Behavior**:

Program compiles; both property `X` and property `Y` are treated identically.

**Actual Behavior**:

Program fails to compile, application of `MethodImpl` attribute to property `X` gives error: "Attribute 'MethodImpl' is not valid on this declaration type. It is only valid on 'constructor, method' declarations."

**Comment by sharwell** [comment]
I believe the current behavior is actually correct. I wouldn't expect users to have the ability to apply a `MethodImpl` attribute to the accessor when using an expression-bodied property unless this syntax was used:

```csharp
[method: MethodImpl(MethodImplOptions.AggressiveInlining)]
public string X => "X";
```

Changing the behavior without requiring `method:` would mean that one of the following occurs:

1. It's no longer possible to apply attributes to the property when using expression-bodied properties. This is certainly not intuitive.
2. The behavior of attributes changes so the `AttributeTargets` starts to affect their application.

In any case, I don't think it's possible to proceed with this request without a language change proposal.

**Comment by Xenoprimate** [comment]
I definitely see where you're coming from and for the most part agree. 

However I might maintain that it is slightly somewhat counter-intuitive for an attribute to be applicable only on one form of two forms of syntax sugar that have identical meaning.

Nonetheless counter-intuitive does sometimes not mean _wrong_ and I think this may be one of those times.

I'm going to close the issue as I agree with your summary and do not think either of the two potential solutions are preferable to no change at all.

**Comment by sharwell** [comment]
@Xenoprimate Currently the `method:` form cannot be used either. It seems like a reasonable request to file in the dotnet/csharplang repository.
