### ISSUE TITLE
Caret incorrectly placed in virtual space after enter with non-standard tab/indent widths

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21919]
Set all tabs and indents to 2. Paste C#
```C#
class C
{
  void N()
}
``` 

Press enter after the declaration of `N`

**Expected**: Caret is 2 positions to the right in virtual space
**Actual**: Caret is 4 positions to the right in virtual space

**Comment by CyrusNajmabadi** [comment]
Unlikely to touch these based on lack of feedback.
