### ISSUE TITLE
Compiler generates incorrect use of `localloc` instruction for `stackalloc` feature in C# 7.2

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#21918]
Before C# 7.2, the `stackalloc` feature could only be used in unsafe code, so it was the programmer's responsibility to ensure it is used safely. In 7.2, we are permitting it to be used in safe code (as part of the Span<T> feature). So the compiler/language must ensure it is used in such a way that the compiler can generate correct code.

The following constraints regarding the CLI `localloc` instruction are not currently obeyed by the implementation in the `features/readonly-ref` branch:

> The `localloc` instruction cannot occur within an exception block: `filter`, `catch`, `finally`, or `fault`.

> Correct CIL required that the evaluation stack be empty, apart from the *size* item.

**Comment by VSadov** [comment]
I think we enforce these rules, although there could be holes.

The "empty stack" could be relaxed eventually by employing stack spiller. 
Or we could just codify that in the spec.

**Comment by OmarTawfik** [comment]
> The localloc instruction cannot occur within an exception block: filter, catch, finally, or fault.
I'll check and we confirm that we have tests for that.
> Correct CIL required that the evaluation stack be empty, apart from the size item.
This is already enforced, by making the `stackalloc` only legal in assignments, or ternary expressions (for now). We have tests that assert this behavior.

**Comment by gafter** [comment]
I see this code in `Binder_Expressions.cs`:

``` c#
            // Check if we're syntactically within a catch or finally clause.
            if (this.Flags.Includes(BinderFlags.InCatchBlock) ||
                this.Flags.Includes(BinderFlags.InCatchFilter) ||
                this.Flags.Includes(BinderFlags.InFinallyBlock))
            {
                Error(diagnostics, ErrorCode.ERR_StackallocInCatchFinally, node);
            }
```

**Comment by OmarTawfik** [comment]
@gafter yes. and this is covered by tests in `UnsafeTests.cs`. I'll close that issue if there are no more concerns.
