### ISSUE TITLE
Debugger "Run To Click" feature should not show icon in non-code files.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#21930]
**Version Used**: 

Visual Studio Community 2017 v15.3.3

**Steps to Reproduce**:

Run some code and stop it under the debugger. Open a non-code file (e.g. an XML file). As you move the mouse around you'll notice the "Run To Click" icon being shown. You can even click it and the debugger will continue execution, except it can never run to where you point because that is not an executable location:

![vs_debugger_run_to_line](https://user-images.githubusercontent.com/20465797/30093054-8a33681a-92cb-11e7-8ab5-a724c0f79690.png)

**Expected Behavior**:

"Run To Click" should only be enabled in source files which contain executable code.

**Actual Behavior**:

Icon appears in XML files and you can even click it, though that makes no sense (interestingly it doesn't ever appear in TXT files).

**Comment by tmat** [comment]
@caslan

**Comment by jsschultz** [comment]
@ericmutta, since the XML language service supports debugging, XML is code; therefore, the Run To Click feature is shown by design.

**Comment by ericmutta** [comment]
@jsschultz since the XML language service supports debugging.

Interesting...how would I get the debugger to step through XML? I was trying to think of scenarios where such a thing is possible (in ASP.NET perhaps?).

@jsschultz the Run To Click feature is shown by design.

OK, showing it makes sense if XML supports debugging. Perhaps the fix should focus on what happens when you do click the icon: the code runs to "wherever" (i.e I can't figure out where it should go since I don't know how VB code can ever jump into XML in an external file). I don't imagine a lot of people will run into to this, so this is more a "nice to fix" rather than "critical bug".

**Comment by jsschultz** [comment]
@ericmutta, see https://msdn.microsoft.com/en-us/library/ms255605.aspx

**Comment by ericmutta** [comment]
@jsschultz I had forgotten about XSLT but it makes sense now. Many thanks for the clarification!
