### ISSUE TITLE
Quick-Fix for BC40003 is missing action to add 'Shadows' modifier

### ISSUE THREAD

**Issue by AnthonyDGreen** [dotnet/roslyn#21946]
Drop this in a new console app.

``` VB.NET
Class Base
    Sub M()

    End Sub
End Class

Class Derived
    Inherits Base

    Sub M() ' <--- Invoke the light bulb on this line.

    End Sub
End Class
```

Invoke the light bulb on the indicated line.

**Expected**
In addition to the "Suppress" option there are two actions. One that adds the 'Overloads' modifier and one that adds the 'Shadows' modifier as either option is correct.

**Actual**
In addition to the "Suppress" option there is only the action that adds the 'Overloads' modifier. This is both incomplete and a bit misleading given that it changes the semantics of the program. The default behavior for VB in the absence of either modifier is to infer 'Shadows'. The most direct way to suppress the warning would be to add that modifier explicitly. Adding 'Overloads' is actually doing something different (however likely it may be that it is preferred).

**Comment by 06needhamt** [comment]
PR is Out! #22871
