### ISSUE TITLE
Improve stackalloc IL emit 

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#21952]
It seems very brute-force

We can do much better:
- stackalloc T[0]     -  should just become "default(target type)"
- stackalloc byte[x]   -  no need to emit " checked(x * 1) " 
- stackalloc int[128]  - we could constant-fold "128 * 4"
- unused stackalloc should be treated as not sideeffecting. The only possible sideeffect is stackoverflow - that is hardly deterministic or useful as a dependency.

**Comment by benaadams** [comment]
> stackalloc byte[x] - no need to emit " checked(x * 1) "

Was recently seeing this in the generated il; thought it was very strange

**Comment by VSadov** [comment]
fixed in https://github.com/dotnet/roslyn/pull/22157
