### ISSUE TITLE
Intermittent test failure: VerifyReorderAndRemoveParametersAcrossLanguages

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#21955]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/7662/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicChangeSignatureDialog/VerifyReorderAndRemoveParametersAcrossLanguages/

```
MESSAGE:
Assert.Contains() Failure
Not found: x.Method(\"str\")
In value: 
Class VBTest
 Sub TestMethod()
 Dim x As New CSharpClass
 x.Method(3.0, \"str\")
 End Sub
End Class
+++++++++++++++++++
STACK TRACE:
at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicChangeSignatureDialog.VerifyReorderAndRemoveParametersAcrossLanguages() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicChangeSignatureDialog.cs:line 132
```

**Comment by CyrusNajmabadi** [comment]
Closing out as this hasn't been flakey for quite some time (and flakey tests now have a dedicated system to track them).
