### ISSUE TITLE
IDE0006 warning in Xamarin

### ISSUE THREAD

**Issue by ZaherHa** [dotnet/roslyn#21961]
I used visual studio 2017

when i create a cross platform App and start debug it the visual studio give me a warning

> `Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled`

then it fall to start the app
what i must to do??

**Comment by Pilchie** [comment]
If you expand the arrow in the error list, or take a look at https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md, get a design time build log, try to identify why it failed.

**Comment by dpoeschl** [comment]
Closing for now. Please re-open if you're able to gather more information.
