### ISSUE TITLE
Consider producing a warning when a ref struct is marked obsolete/deprecated

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#21973]
ref structs are marked `obsolete` with well known marker, unless user obsoletes them in source. 
Then synthesized marker is not emitted. We may want to make the user aware of that.

Another thing to consider - do we _require_ Obsolete to be present on a type when it is ref-like?
Especially, considering that we ourselves may not be able to emit it in this situation?

**Comment by svick** [comment]
Would it make sense to change `ObsoleteAttribute`, so it has `AllowMultiple = true`? It wouldn't help with existing frameworks (where what you're proposing would still be required), but I think it could be a better long-term solution.

**Comment by jcouv** [comment]
From LDM today, the attribute provided by the user in source should win.

**Comment by jcouv** [comment]
This is the current implementation of the compiler. Closing the issue.
