### ISSUE TITLE
Should not be able to convert to delegate instance methods of ref-like types like TypedReference

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#21979]
Spec for the new ref-like types like span specifically prohibit taking delegates of their instance methods.
That is not allowed since indirectly that requires boxing of the receiver instance and that is illegal.

It looks like there is a preexisting bug where method group conversions allowed for TypedReference and the like. That is never a correct code and will crash at runtime.

As a part of implementation of the new ref-like we enforce this rule for the old ref-likes as well, but need to check with compat counsel whether that is ok.

If this is ok, make sure there are tests before closing this.

**Comment by gafter** [comment]
The compatibility council has approved this change. When the change is made, please be sure to include a note in the breaking changes document. For that purpose, you might find the following useful:

Here is an example of code that would no longer compile:

``` c#
static Func<int> M(__arglist)
{
    ArgIterator ai = new ArgIterator(__arglist);
    while (ai.GetRemainingCount() > 0)
    {
        TypedReference tr = ai.GetNextArg();
        return tr.GetHashCode; // delegate conversion causes a subsequent System.InvalidProgramException
    }

    return null;
}
```
The line with the comment would now be a compile-time error.

**Comment by gafter** [comment]
@VSadov Which of us is going to make the code change, and which of us is going to make the doc change?

**Comment by VSadov** [comment]
@gafter  - I will make the change in code - it is easy to do in the readonly-ref branch. There is even a test for this already, it will need to be updated.

I'd appreciate if you make the documentation change. Thanks!!

**Comment by gafter** [comment]
This and a bunch of other things I'm placing in the test plan should feed back into the spec. I'll do that.

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/23055
