### ISSUE TITLE
Switch case is not block level: variable defined in different case is global to all cases.

### ISSUE THREAD

**Issue by mpaine-act** [dotnet/roslyn#21988]
**Version Used**: C# in VS2017.3.3 

**Steps to Reproduce**:

1. This does not compile (Use of unassigned local variable 'b'
```
        public void TestSwitch()
        {
            var a = 2;
            switch (a)
            {
                case 1:
                    var b = 2;
                    break;
                case 2:
                    b = b + 4;
                    break;
            }
        }
```

2. This compiles and works:

```
        public void TestSwitch()
        {
            var a = 2;
            switch (a)
            {
                case 1:
                    var b = 2;
                    break;
                case 2:
                    b = 1;
                    b = b + 4;
                    break;
            }
        }
```

Is this by design, since this works but is unexpected.

**Comment by jcouv** [comment]
Yes, this is by-design and expected.

The locals in a switch statement are actually scoped to the entire switch statement, so `b` is considered declared even in `case 2`.
But flow analysis (which determines if you use a variable before it was initialized) can see that `b = b + 4` will read variable `b` before it is initialized (when the control flow enters `case 2`).
