### ISSUE TITLE
Remove specialcasing for Span and ReadOnlySpan before shipping

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#21981]
We currently assume, regardless of attributes, that Span and ReadOnlySpan are
- ref-like structs
- readonly structs

This is done as a bootstrapping measure to mitigate the situation where some repos have old compilers and some implementations of span types do not have expected annotation.

We should remove the special-casing when before shipping to not set a compat precedent where annotations are unnecessary on span types.

**Comment by OmarTawfik** [comment]
@VSadov quote:
`We should remove the special-casing when before shipping to not set a compat precedent where annotations are unnecessary on span types.`
The change we discussed involving converting them into well known types. Did we consider removing the special casing as well and reading attributes from metadata instead? this will obviously fail on libraries built by older compilers.
