### ISSUE TITLE
dotnet core project with microsoft.net.compilers 2.3.2 fails to build on Ubuntu

### ISSUE THREAD

**Issue by simonjduff** [dotnet/roslyn#21987]
**Version Used**: 2.3.2

**Environment**:
Ubuntu 16.04
and also affects
Windows 10 with Ubuntu bash shell running in Windows Subsystem for Linux

**Steps to Reproduce**:

1. Install Ubuntu 16.04
2. Install .net core following this guide https://www.microsoft.com/net/core#linuxubuntu
3. Create a new project (dotnet new console)
4. Build (dotnet build) succeeds
4. Add compilers (dotnet add package microsoft.net.compilers)
5. Build (dotnet build) fails

**Expected Behavior**:
Successful build

**Actual Behavior**:
Failed build
*Windows 10 with Ubuntu Shell:*
/home/me/.nuget/packages/microsoft.net.compilers/2.3.2/build/../tools/csc.exe: Invalid argument
/home/me/.nuget/packages/microsoft.net.compilers/2.3.2/tools/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.exe" exited with code 1. [/mnt/c/Users/me/source/repos/test/test.csproj]

*Ubuntu 16.04 in hyper-v vm*
 1>/home/me/.nuget/packages/microsoft.net.compilers/2.3.2/tools/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.exe" exited with code 8. [/home/me/test/test.csproj]

**Comment by jcouv** [comment]
FYI @khyperia

**Comment by agocke** [comment]
@simonjduff The `Microsoft.NET.Compilers` package is for the Full .NET 4.6 framework -- since you're running on Linux (through WSL) you'll need the CoreCLR compilers. The dotnet CLI you installed comes with a compatible C# compiler that should work for you. Did that fail for a different reason?

**Comment by simonjduff** [comment]
Thanks @agocke, I'd added the package to a project in order to get C# 7 features enabled (the new tuples etc), while working on a Windows PC. It was only when I tried to build the project on Linux that it failed.
I've just done a basic test and those features are included by default now, so this has ceased to be a problem. Thanks for the answer!
