### ISSUE TITLE
C# PROPOSAL: Add more option to escape from string template

### ISSUE THREAD

**Issue by ParserApprentice** [dotnet/roslyn#21983]
C# PROPOSAL: Add more option to escape from string template
---
VS2017,

**Current Status :**
with C#7 local function,
I can use it as a string template for external lang.
eg.
![cs_prop1](https://user-images.githubusercontent.com/25289483/30196518-8021e60a-948b-11e7-97c5-6cb3bade206a.png)

and this is the simple result ...
![cs_prop2](https://user-images.githubusercontent.com/25289483/30196544-abc7a556-948b-11e7-8057-56a6b0d669cf.png)

or json text
![cs_prop1_1](https://user-images.githubusercontent.com/25289483/30196703-e850879e-948c-11e7-9e9a-9b70dc77cf8a.png)

and the result...

![cs_prop2_1](https://user-images.githubusercontent.com/25289483/30196739-22b44e52-948d-11e7-9275-bf157bae9a63.png)
---

**What I want to PROPOSE** 

"Add more option to escape from string template"
Currently,  It may be specific after $

eg Razor style, $@@""

![cs_prop3](https://user-images.githubusercontent.com/25289483/30196586-11cbb72a-948c-11e7-8e95-f99cd670f399.png)

cs-parse found $ and follow by @@ 
cs-parse should escape when it found @ in the string literal
as if it found { } in C#7 , (see Razor as example)

(and more)  
eg. Json

![cs_prop4](https://user-images.githubusercontent.com/25289483/30196807-8b00ba40-948d-11e7-868d-58c02576e756.png)

currently 
other algorithms of string template should remain the same.

I think  it would be useful in many aspects.
eg 
  1. local data template definition
  2. easy integration with some small data in xml or json format
  3. for the IntelliSense, 
     the IDE can escape from the C# parsing context
     and go to another proper parsing context (eg xml, json , css etc..)

---
Hope you consider this,
or suggest me if you have other ways

Thank you

**Comment by svick** [comment]
Proposals to change the C# language belong in [the csharplang repo](https://github.com/dotnet/csharplang). Could you move this issue there?

**Comment by ParserApprentice** [comment]
This issue was moved to https://github.com/dotnet/csharplang/issues/890

Thank you
