### ISSUE TITLE
Integration test hang in CSharpClassification.VerifyProjectConfigChange

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#21999]
:link: Found in PR https://github.com/dotnet/roslyn/pull/21968
:link: Artifacts at https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/7716/artifact/Binaries/Debug/

Callstack of xunit process is below.  VS process didn't appear to be doing anything.

```
16 0095c47c 06d21d40 Microsoft_VisualStudio_IntegrationTest_Utilities!Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.VisualStudioWorkspace_OutOfProc.WaitForAsyncOperations(System.String, Boolean)+0x3a
17 0095c4a4 00c32de9 Microsoft_VisualStudio_IntegrationTest_Utilities!Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.TextViewWindow_OutOfProc+Verifier`1[[System.__Canon, mscorlib]].CurrentTokenType(System.String)+0x50
18 0095c4f8 7391eaf6 Roslyn_VisualStudio_IntegrationTests!Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpClassification.VerifyProjectConfigChange()+0xc1
```
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpClassification.VerifyProjectConfigChange

**Comment by CyrusNajmabadi** [comment]
This test appears to be working fine now.  Furthermore, the binaries from then are no longer available. Stack trace isn't helpful enough.  So closing out.
