### ISSUE TITLE
.editorconfig doesn't seem to apply if the file is opened in Miscellaneous Files Workspace

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#21998]
@tmat observed some behaviors where if a file was opened in the Miscellaneous Files workspace, .editorconfig files weren't being applied. Once we switched to have a file opened in a project, then the .editorconfig rules were applied.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski I don't really have an issue with that.  Misc files aren't really something i would expect to have any sort of 'rich support' for (and i would count editorconfig understanding as part of htat).  Do we really think we'd do anything here?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Oh, this is a good suggestion; yeah we should do it and would be easy to do. I can think of times at least in huge repo scenarios (like VS) where I might be having some files open as misc files while debugging, and once I step into the file that has the issue I can make a small edit directly there.

**Comment by sharwell** [comment]
One example is opening a random source file for editing in an empty IDE instance, and having the formatter apply the wrong set of rules.

**Comment by CyrusNajmabadi** [comment]
IMO, this is a big ask, and a departure from divisional guidance.  We explicitly do not consider project/solution-less editing scenarios part of Roslyn's purpose.  We try to go the opposite direction, avoiding that at all costs and recommending that everyone use solutions/projects.  If we were to support this, it would both be a big deviation, and be a large ask (needing to now go through and consider how all features interact with the loose file case).

**Comment by CyrusNajmabadi** [comment]
Closing out as far too big an ask.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Why is this a big ask? I'd imagine it's ~30 lines of code just to walk and find the .editorconfigs to apply.

**Comment by CyrusNajmabadi** [comment]
It's a big ask because we do not test MiscWorkspace cases.  And this now opens us up to having to supporting those cases.  This also means we may end up with stability issues for features that are not expecting this.

If you want to maintain and own this perpetually, feel free to contribute a PR.  But we simply do not have hte resources whatsoever to add support for non-mainline scenarios.
