### ISSUE TITLE
Light bulb includes too many code fixes if a warning spans multiple lines

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#2199]
The following screenshot shows a case where one of our StyleCop diagnostics reported a warning for a `set` accessor (we meant it to only report for the keyword, but that's a separate issue).

![image](https://cloud.githubusercontent.com/assets/1408396/7289723/b19ee5d4-e939-11e4-83c5-1f6a9a8b9375.png)

If you use **the mouse** to hover over the last line of this warning, the light bulb appears. If you click to expand the light bulb, the following drop-down appears:
## Actual results

Every code fix for every warning in the set accessor is shown.

![image](https://cloud.githubusercontent.com/assets/1408396/7289745/02ac1b40-e93a-11e4-9d2c-46bcec52e49c.png)
## Expected results

I expected the drop down to only include items whose warning span includes the specific location hovered over, e.g. the following if you hover over the last line of the warning:

![image](https://cloud.githubusercontent.com/assets/1408396/7289781/67040d5a-e93a-11e4-8f49-b23dca0f2355.png)
## NOTE:

This only occurs when using the mouse to select the light bulb. When the keyboard is used (<kbd>Ctrl</kbd>+<kbd>.</kbd>), the expected results occur.

**Comment by heejaechang** [comment]
what you are hovering over is warning squiggle not a token. this case would be not easy to generalize due to nested squiggle case.

**Comment by CyrusNajmabadi** [comment]
Need to determine if this is still an issue, and if it's even worth fixing.  Haven't heard about this in ages, so closing out.
