### ISSUE TITLE
Do not suggest overloads hidden by hidebyname

### ISSUE THREAD

**Issue by ektrah** [dotnet/roslyn#22009]
**Version Used**: Visual Studio 15.3.3

**Steps to Reproduce**:

1. Create an assembly with a base class and a derived class
2. Add one method to each class with the same name but different parameters
3. Mark the method in the derived class as `hidebyname` rather than `hidebysig`
4. Reference the assembly in a C# project
5. Enter `var c = new MyDerivedClass(); c.Foo(`
6. Notice the overloads suggested by Visual Studio  

Referenced assembly:

```vbnet
Public MustInherit Class MyBaseClass
    Public Sub Foo(x As String)
        Console.WriteLine("MyBaseClass.Foo(String)")
    End Sub
    Public Sub Bar(x As String)
        Console.WriteLine("MyBaseClass.Bar(String)")
    End Sub
End Class

Public NotInheritable Class MyDerivedClass
    Inherits MyBaseClass
    Public Shadows Sub Foo(x As Int32)                 ' hidebyname
        Console.WriteLine("MyDerivedClass.Foo(Int32)")
    End Sub
    Public Overloads Sub Bar(x As Int32)               ' hidebysig
        Console.WriteLine("MyDerivedClass.Bar(Int32)")
    End Sub
End Class
```

Referencing assembly:

```csharp
static void Main()
{
    var c = new MyDerivedClass();
    c.Foo(3);
    c.Foo("Hello"); // incorrectly suggested by IntelliSense, correctly rejected when compiling
    c.Bar(3);
    c.Bar("Hello");
}
```

**Expected Behavior**:

One overload being suggested. The overload in the base class is not accessible due to `hidebyname`.

**Actual Behavior**:

Two overloads being suggested.

![screenshot](https://user-images.githubusercontent.com/4752078/30241160-21056018-957e-11e7-8c25-df9666144e1a.png)

**Comment by ektrah** [comment]
@DustinCampbell @dpoeschl Is this something that can be easily fixed without much knowledge of the code base? If yes, I would give it a shot. Just need to know where to start.

**Comment by ektrah** [comment]
@DustinCampbell  I see. I guess this is a "won't fix" then. Too bad. It would have really nicely worked around my problem.

Idea for a workaround: What's the difficulty (and chances of getting accepted) a new EditorBrowsableState that hides a member if it is only inherited by the type of the expression?

```vb.net
Public MustInherit Class MyBaseClass
    <EditorBrowsable(EditorBrowsableState.NeverInherited)>
    Public Sub Foo(x As String)
        Console.WriteLine("MyBaseClass.Foo(String)")
    End Sub
    ...
```

**Comment by DustinCampbell** [comment]
As I said, I'm not sure. It's entirely possible that my memory isn't accurate. :smile:

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in this area.
