### ISSUE TITLE
API review for IAwaitExpression

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22007]
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Operations/IAwaitExpression.cs

Add unit tests when making public

**Comment by sharwell** [comment]
:bulb: Why not just have the property be `Expression`?

**Comment by DustinCampbell** [comment]
agreed

**Comment by DustinCampbell** [comment]
you don't await values anyway.
