### ISSUE TITLE
VB: Flaky UI when adding project-level imports within a .NET Standard library project.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#22014]
**Version Used**: 

Visual Studio Community 2017 v15.3.3

**Steps to Reproduce**:

Create a VB library using the the .NET Standard template, then go to its Properties page under the References tab:

![vs_stdlib_addref_crash5](https://user-images.githubusercontent.com/20465797/30245384-d86d4696-95e0-11e7-9f0b-89934ff3a183.png)

Click on the checkbox to import any of the namespaces (e.g `System.IO`). The properties window shows a "dirty" indicator in its title as if the import was added, but the check box does not appear ticked. If you click Save then close and reopen the window to view imports you will see the namespace ticked. 

When opened the second time, try tick another namespace, same problem happens, the check box isn't ticked. If you try to tick _yet another_ namespace, then the check box appears on previously ticked namespace but not the one you just tried to tick.

**Expected Behavior**:

The check boxes ought to refresh and show the ticked status immediately you tick or untick them.

**Actual Behavior**:

The import happens but the check box does not reflect it until you close and open the properties window.

**Comment by Pilchie** [comment]
cc @tannergooding / @natidea - looks like this should be moved to https://github.com/dotnet/project-system.

**Comment by davkean** [comment]
This issue was moved to dotnet/project-system#2992
