### ISSUE TITLE
VB: IDE crashes when trying to add reference within a .NET Standard library project.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#22013]
**Version Used**: 

Visual Studio Community 2017 v15.3.3

**Steps to Reproduce**:

Create a VB library using the the .NET Standard template, then go to its Properties page under the References tab:

![vs_stdlib_addref_crash4](https://user-images.githubusercontent.com/20465797/30245334-c2e309a2-95de-11e7-9048-5f641731f31a.png)

If you press the Add button on where the label `Add...` appears, it opens the add reference dialog as expected. However if you click on the arrow on the right edge of the button, it is non-responsive and after a few seconds the IDE crashes.

**Expected Behavior**:

If the menu that usually shows when you click the arrow on the Add button is not applicable for VB .NET Standard library projects, there should be some kind of message to say so rather than crashing the IDE.

**Actual Behavior**:

As shown above: IDE crashes and you have to be careful to click on Add button's label, rather than the arrow portion.

**Comment by Pilchie** [comment]
@jasonmalinowski isn't this the bug you fixed in F#'s copy of the property pages?

Cc @tannergooding

**Comment by Pilchie** [comment]
Also cc @natidea - looks like this should be moved to https://github.com/dotnet/project-system.

**Comment by davkean** [comment]
This issue was moved to dotnet/project-system#2991
