### ISSUE TITLE
VB ForTo loop with implicit StepValue has an Operation tree with explicit nodes

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22029]
The conversion on top of the implicit step value literal is explicit instead of implicit, see https://github.com/dotnet/roslyn/pull/21791#discussion_r137702475.

**Comment by AlekseyTs** [comment]
We should also confirm whether we want the implicit Step to be exposed at all, we don't expose any other implicit operations.

**Comment by mavasani** [comment]
Just verify if StepValue is implicit, and if so move out to v2 to address Aleksey's suggestion.

**Comment by AlekseyTs** [comment]
https://github.com/dotnet/roslyn/pull/22705 made sure implicit step is represented by nodes marked as implicit.

**Comment by jinujoseph** [comment]
thanks @AlekseyTs , moving the issue to V2
