### ISSUE TITLE
Ordering of IOperation.Children

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22020]
Do we want to guarantee any specific ordering? If so, we need to decide the principles for the same. See https://github.com/dotnet/roslyn/pull/21791#discussion_r137679295

**Comment by AlekseyTs** [comment]
Perhaps evaluation order should be used. Does this property affect behavior of a visitor?

**Comment by heejaechang** [comment]
@AlekseyTs visitor simply iterates operation returned by Children to visit sub trees.

**Comment by mavasani** [comment]
Design Decision: Use evaluation order.

**Comment by AlekseyTs** [comment]
@heejaechang Have you opened a separate issue to add tests?

**Comment by heejaechang** [comment]
@AlekseyTs I already have PR out I am working on to add test. - https://github.com/dotnet/roslyn/pull/22746

I am fine leaving it open as well. tagging @jinujoseph

**Comment by jinujoseph** [comment]
Closing this out as tracked [here ](https://github.com/dotnet/roslyn/issues/22752)
