### ISSUE TITLE
Should we represent loop control variable in a foreach loop and VB for to loop as an IVariableDeclaration?

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22028]
See https://github.com/dotnet/roslyn/pull/21791#discussion_r137685198. For all other cases where we have an IVariableDeclaration, it is always a child of IVariableDeclarationStatement. I am not sure what is the preferred tree shape.

**Comment by mavasani** [comment]
If we decide to keep this node as an `ILocalReferenceExpression(IsDeclaration = true)`, should we mark it as implicit? See https://github.com/dotnet/roslyn/pull/21791#discussion_r137700079

**Comment by mavasani** [comment]
@AlekseyTs has a proposal here: https://github.com/dotnet/roslyn/pull/21791#discussion_r137702871

**Comment by mavasani** [comment]
Same design should be followed for VB ForTo loops. See https://github.com/dotnet/roslyn/pull/21791#issuecomment-327990873

**Comment by mavasani** [comment]
Design decision: Lets try to get IVariableDeclaration for all cases as these are logically variable declarations. Note this should not be IVariableDeclarationStatement, but just an IVariableDeclaration as we can declare one variable at max.

**Comment by jinujoseph** [comment]
@heejaechang can you take a look at this similar to forloop
