### ISSUE TITLE
Add more tests for C# and VB foreach loop statements

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22030]
See https://github.com/dotnet/roslyn/pull/21791#discussion_r137703488.

PR review comment mentions: `Are there tests that use convert collection to generic IEnumerable, or use For Each pattern? Is for each over a string covered? Same question for C# tests`

Verified we have `IForEachLoopStatement_String` for string case, but we do not have foreach over a collection converted to generic IEnumerable. I will add unit tests to both languages for this scenario.

**Comment by jinujoseph** [comment]
verify and clarify

**Comment by mavasani** [comment]
PR review comment mentions: `Are there tests that use convert collection to generic IEnumerable, or use For Each pattern? Is for each over a string covered? Same question for C# tests`

Verified we have `IForEachLoopStatement_String` for string case, but we do not have foreach over a collection converted to generic IEnumerable. I will add unit tests to both languages for this scenario.
