### ISSUE TITLE
?. expressions are not being treated as Nullable<T> 

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#2203]
The following code does not compile:
```C#
using System;
using System.Collections.Generic;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine(test(null));
    }

    private static int test(List<int> list)
    {
        return list?.Count.GetValueOrDefault();
    }
}
// Error	CS1061	'int' does not contain a definition for 'GetValueOrDefault' and no extension method 'GetValueOrDefault' accepting a first argument of type 'int' could be found (are you missing a using directive or an assembly reference?)	
```

You need to explicitly cast Count to int?
```C#
using System;
using System.Collections.Generic;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine(test(null));
    }

    private static int test(List<int> list)
    {
        return ((int?)list?.Count).GetValueOrDefault();
    }
}
```

However int? will be colorized as unnecessary.

And this obviously fails to compile
```C#
using System;
using System.Collections.Generic;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine(test(null));
    }

    private static int test(List<int> list)
    {
        return list?.Count;
    }
}
// Error	CS0266	Cannot implicitly convert type 'int?' to 'int'. An explicit conversion exists (are you missing a cast?)

```

Either

A: The compiler should treat types returned by in ?. expression as Nullable(Of T) instead of T in all contexts
B: The Simplifier will need to be taught about this very special case.

**Comment by MrJul** [comment]
Sorry if I'm mistaken, but Isn't this behavior normal since `?.` is right-associative?

`(list?.Count).GetValueOrDefault()` compiles fine.

**Comment by controlflow** [comment]
This is absolutely valid behavior, this is how conditional access expression works: it "lifts" three kinds of continuations from the right of `?.` - property/field access, method invocation and indexer access.

In expression `list?.Count.GetValueOrDefault()` the `list?.Count` part is *not* a separate expression! You can't introduce variable from it. The only expression there is `list` and a whole `list?.Count.GetValueOrDefault()`. Only `list` and `list?.Count.GetValueOrDefault()` expressions actually have types.

**Comment by jmarolf** [comment]
@controlflow @MrJul  Thanks guys! you are right.  I'm going going to close this bug and file one only about the simplification issue.

**Comment by VSadov** [comment]
Yes, this is a desired result of the right-associativity.
The whole   "Count.GetValueOrDefault" is conditional or the non-nullness of the list.
