### ISSUE TITLE
stackalloc expressions have limited syntax

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#22046]
Due to a CLR spec limitation, stackalloc instructions cannot be executed unless the evaluation stack is cleared of other items. This means that the following code will not be executed at run-time:

`DoSomething(obj1, stackalloc int[10]);`

For that to happen, we need to save (spill) all prior values on the evaluation stack to temps before executing this instruction. For now, in feature branch `freatures/readonly-ref`, the scope of this instruction is constricted to either (1) initialization statements or (2) ternary conditional operators.

**Comment by alrz** [comment]
We may need this for a hypothetical `params Span<T>` feature.

**Comment by alrz** [comment]
Should this behave the same way we do spilling for `await`? e.g.
```
M(e1, e2, constant, stackalloc int[10]);

->

var t1 = e1;
var t2 = e2;
var p = stackallock int[10];
M(t1, t2, constant, p);
```

**Comment by gafter** [comment]
This is tracked as a language issue at https://github.com/dotnet/csharplang/issues/1412

**Comment by gafter** [comment]
This is relaxed (by spilling) in https://github.com/dotnet/roslyn/issues/28969
