### ISSUE TITLE
Public API Addition: Conversion.IsStackAlloc

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#22045]
This boolean member was added in feature branch in #21746

```csharp
        /// <summary>
        /// Returns true if the conversion is a stackalloc conversion.
        /// </summary>
        public bool IsStackAlloc
        {
            get;
        }
```

Need to get this through API review. This is to align with similar properties to detect conversion types.

**Comment by OmarTawfik** [comment]
cc @gafter @dotnet/csharplangdesign

**Comment by VSadov** [comment]
This is tracked by thr Unshipped.txt
