### ISSUE TITLE
VB: "Rename Tracking" refactoring doesn't work for members near a #Region block.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#22059]
**Version Used**: 

Visual Studio Community 2017 v15.3.3

**Steps to Reproduce**:

Type in the following code:

```vb
Public Class Whatever
#Region "rename method killer"
#End Region

  Public Sub BrokenMethodA()
  End Sub

  Private Sub WorkingMethod()
  End Sub

  Public Sub BrokenMethodB()
  End Sub

#Region "rename method killer"
#End Region
End Class
```

Put the caret at the end of the name  `BrokenMethodA` and type anything extra to extend the name (e.g. `BrokenMethodAA`:

![vs_inline_rename_1](https://user-images.githubusercontent.com/20465797/30305887-f2009786-977d-11e7-8afd-665dd282382b.png)

As shown in the above image, if you try to click the light bulb to invoke the rename refactoring, it doesn't work. Same problem happens if you go to `BrokenMethodB` and type anything extra to extend the name (e.g. `BrokenMethodBB`).

In both cases, I think the problem is that the methods are immediately preceded/followed by `#Region...End Region` block. If you try the same thing with `WorkingMethod` which is immediately preceded/followed by other methods, it works:

![vs_inline_rename_2](https://user-images.githubusercontent.com/20465797/30306138-4aeec40c-977f-11e7-97f8-ccc00ab67ded.png)

This example uses method members, but I have also tried it with the following class declarations and it exhibits the same behaviour:

```vb
Public Class Whatever
#Region "rename class killer"
#End Region

  Public Class BrokenClassA
  End Class

  Public Class WorkingClass
  End Class

  Public Class BrokenClassB
  End Class

#Region "rename class killer"
#End Region
End Class
```

**Expected Behavior**:

Rename Tracking is very useful and it should work for all members regardless of their position in the source file. The "Rename..." (Inline Rename) refactoring available from the editor's context menu works just fine, but is cumbersome to invoke because it needs a mouse click.

**Comment by ericmutta** [comment]
Here is another variant with the same problem:

```vb
#Region " rename killer "
  Private Sub BrokenMethodA()
  End Sub

  Private Sub WorkingMethod()
  End Sub

  Private Sub BrokenMethodB()
  End Sub
#End Region
```

In this version the methods are **inside** a region and the ones where inline rename doesn't work is `BrokenMethodA` which is declared **just after** the `#Region` block delimeter and `BrokenMethodB` which is declared **just before** the `#End Region` block delimeter. It works as expected for `WorkingMethod` which doesn't meet the previous conditions.

**Comment by dpoeschl** [comment]
I've re-titled and re-worded your post a bit. The feature with the dotted outlines and the lightbulb entry for renaming is called "Rename Tracking." The "Rename..." thing in the context menu is "Inline Rename.", so I fixed up the names of those features throughout.

Inline Rename does work in this case, as you've pointed out. You don't _have_ to use the mouse. Depending on your keyboard settings, Inline Rename is usually mapped to `F2` or `Ctrl+r, Ctrl+r`.

**Comment by ericmutta** [comment]
@dpoeschl many thanks for the clarification. I was referring to "rename tracking" as "inline rename" because unlike the "Rename..." action in the context menu, it doesn't show any exta UI like this:

![vs_rename_ui](https://user-images.githubusercontent.com/20465797/30556482-ac179266-9cb3-11e7-9eea-d0463a608d64.png)

**Comment by dpoeschl** [comment]
(I don't remember hitting the close button, but it's reopened now. Oops.)

**Comment by ericmutta** [comment]
Hi @dpoeschl it's been a while. Any chance this bug could be assigned to a near-future milestone? It is causing me a lot of grief :(

**Comment by sharwell** [comment]
@ericmutta We've been busy with other changes, but if a pull request from the community comes in to fix this we'll try to get it merged in the earliest release allowed.

**Comment by ericmutta** [comment]
Hi @sharwell I understand totally, many thanks for following up! 

I am waiting for the performance of the project system to improve (@Pilchie and @CyrusNajmabadi  said something about it being in transition in [#21339](https://github.com/dotnet/roslyn/issues/21339))...then I will take a stab at some of these bugs myself because the pain is real :-)

**Comment by sharwell** [comment]
@ericmutta The latest master branch *should* be in a reasonably good state for performance, as long as you are using one of the more recent 15.4 or 15.5 Preview releases. If you have the ability to install 15.5 Preview as a second copy of Visual Studio, this is the approach I would recommend for performance.

**Comment by ericmutta** [comment]
> @sharwell ...this is the approach I would recommend for performance.

Many thanks for the tip...I have 15.4 right now and will take look at the preview 👍

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not likely to be changing tehse experiences.
