### ISSUE TITLE
[Refactoring] Extract class

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#22053]
This would let you select static methods and extract them into a static class. 

Also would be nice to include "extract base class".

**Comment by kuhlenh** [comment]
FYI @wli3

**Comment by wli3** [comment]
![image](https://user-images.githubusercontent.com/6993335/30301176-f4e314ee-970d-11e7-8b1e-24c587c29e68.png)

This is a intermediate step to extract to a new class 
(
extract to new class;
Extract method
Introduce Parameter, make all value to be passed-in https://github.com/dotnet/roslyn/issues/22051
Make it static
**Extract static class**
Move Parameter to a field and make it non static
create constructor DI with the field
)

**Comment by DustinCampbell** [comment]
Isn't this just a specialization of a Extract Class refactoring? I wouldn't expect that we'd have a separate refactoring just for selecting static methods to produce a static class. Instead, I would expect this to be knobs on a dialog for a more general Extract Class refactoring.

**Comment by wli3** [comment]
@DustinCampbell agree, it does not need to be a separate refactoring. Although "Extract Class" is very hard, you need to have a better separation(abstraction) in the beginning. I have not seem a good automatic refactoring implementation of extract class. (end up with "new" a new class, pass the old one into constructor of the new class and call as usual. -- A circular dependency generator.)

**Comment by ryzngard** [comment]
@jmarolf I believe we can close this now? We have extract base class, extract to new static class, and are adding extract static to existing class in 17.4 (it barely missed 17.3)
