### ISSUE TITLE
New AdhocWorkspace returns System.NotSupportedException: 'The language 'Visual Basic' is not supported.'

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#22060]
**Version Used**: 
VS 2017 15.3.3, Microsoft.CodeAnalysis.Workspaces 2.3.0.0, NuGet 2.3.2
**Steps to Reproduce**:
1. Upgrade Microsoft.CodeAnalysis.Workspaces, from Version=2.2.0.0 to Version=2.3.0.0.
NuGet 2.2.0 to NuGet 2.3.2.
2.  Language = LanguageNames.VisualBasic, parseOptions and compilationOptions  are Nothing.
3. The code below is from Roslyn Samples DiagnosticVerifier.Helper.vb but in the sample CreateDocument is never referenced so CreateProject is never called.
```
        Protected Shared Function CreateDocument(source As String, parseOptions As ParseOptions, compilationOptions As CompilationOptions, Optional language As String = LanguageNames.CSharp) As Document
            Return CreateProject({source}, parseOptions, compilationOptions, language).Documents.First()
        End Function

        Private Shared Function CreateProject(sources As String(), parseOptions As ParseOptions, compilationOptions As CompilationOptions, Optional language As String = LanguageNames.CSharp) As Project
            Dim fileNamePrefix As String = DefaultFilePathPrefix
            Dim fileExt As String = If(language = LanguageNames.CSharp, CSharpDefaultFileExt, VisualBasicDefaultExt)
            Dim projectId As projectId = projectId.CreateNewId(debugName:=TestProjectName)
            Dim projectInfo As ProjectInfo = ProjectInfo.Create(projectId, Nothing, TestProjectName, TestProjectName, language,
                                                             parseOptions:=parseOptions,
                                                             compilationOptions:=compilationOptions)
            Dim solution As Solution = New AdhocWorkspace() _
                               .CurrentSolution _
                               .AddProject(projectInfo) _
                               .AddMetadataReference(projectId, CorlibReference) _
                               .AddMetadataReference(projectId, SystemCoreReference) _
                               .AddMetadataReference(projectId, VisualBasicSymbolsReference) _
                               .AddMetadataReference(projectId, CodeAnalysisReference)
```
**Expected Behavior**:
Solution is created
**Actual Behavior**:
System.NotSupportedException: 'The language 'Visual Basic' is not supported.'

**Comment by Pilchie** [comment]
@paul1956 can you verify that `Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll` is in the same directory as your program?  The workspace layer loads it with MEF to get VB support.

**Comment by paul1956** [comment]
There is only one copy of Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll it is in ProjectName.Vsix\bin\Debug. It is also named in ProjectName.Test.vbproj.FileListAbsolute.txt and ProjectName.Vsix.vbproj.FileListAbsolute.txt. If I manually copy it to ProjectName.Test\bin\Debug then all tests pass. First why is it missing, second why is the error message so misleading. I have not tried but I assume if I Clean the solution this will break again.

**Comment by dpoeschl** [comment]
@jasonmalinowski Any idea what's going wrong here?

**Comment by jasonmalinowski** [comment]
@paul1956 Just to make sure I've got the context here, this is an error coming from the test? Can you share the project file for ProjectName.Test and the packages.config or project.json if you have one?

**Comment by paul1956** [comment]
@jasonmalinowski Sorry I was out of the country with limited internet. The error occurs while trying to run the test after upgrading the project from 4.6.1 to 4.7 and then upgrading all the Roslyn NuGet packages. The problem was solved by manually copying Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll to Test\bin\Debug with no changes to any files.

**Comment by jasonmalinowski** [comment]
@paul1956 Oops, sorry for missing your reply. (I hate GitHub notifications.)

Did you resolve the issue? If not, what type of NuGet was this with? packages.config or project.json or something else?

**Comment by paul1956** [comment]
@jasonmalinowski I have a packages,config file in Test project director or but no project.json files in my solution. My Test.vbproj file also has package references like below. But i am having all kinds of issues with files not found at run time like above in Test and VSIX projects. They work in code refactoring projects.
```
    <PackageReference Include="Microsoft.Build">
      <Version>15.3.409</Version>
    </PackageReference>
```
For example in my VSIX project which does not have a package.config tile I can't find ConfOxide at runtime even though it is listed in vbproj file

**Comment by CyrusNajmabadi** [comment]
@paul1956 are you still having an issue with this?

**Comment by paul1956** [comment]
@CyrusNajmabadi I have not done work with AdhocWorkspace since 2017
