### ISSUE TITLE
The Roslyn CTP forum on MSDN forums should be closed

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#22065]
On MSDN forums, there is [a forum called *Microsoft "Roslyn" CTP*](https://social.msdn.microsoft.com/Forums/vstudio/en-us/home?forum=roslyn). The issues with this forum are:

* It's a ghost town. Most posts don't even receive a reply.
* It's clearly out of date. Roslyn has been out of CTP for a very long time. And the pinned post proudly proclaims that Roslyn is now open source on CodePlex.

Since new posts are still being posted there (sometimes due to a move by someone from MSDN Community Support), could the forum be closed, so that new posts cannot be added? Ideally, anyone arriving there should be pointed here instead.

**Comment by Pilchie** [comment]
Thanks for the heads up - I'll work on getting them closed.

**Comment by Pilchie** [comment]
I posted an announcement, locked it, and marked it as inactive.

**Comment by TobiasBreuer** [comment]
@Pilchie I totally agree that the forum shouldn't be active any more, but now it seems to be gone entirely (i.e. invisible or deleted). It doesn't seem to be archived or the like so at the moment I can't even access my threads from back in the days. In the overview of "My threads" they aren't listed and when trying to reach them via the "History" tab of my profile, I end up on a page telling me that I'm not authorized to perform this action.
While in fact a lot of the stuff mentioned there is not valid any longer, some of the information indeed still is and should IMHO be available at least for archive reasons. So maybe it would be possible to add it to the "Archived Forums M" section?

**Comment by Pilchie** [comment]
I don't seem to have a way to do that :(
