### ISSUE TITLE
Go To Implementation does not focus window if covered

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#22083]
When Go to Implementation is invoked, if the window it's invoked on is covered, it will appear over the covering window and not focus the window underneath. As an example:

1. Open a solution in VS. I'll refer to this as window 1.
2. Open a file from the solution in a separate window, preferably a text file (ie, not a code file with symbols in it). I'll refer to this as window 2. Move this to a second monitor.
3. Close all open files in window 1, so the only open file is the one in window 2.
4. Open a different application. I'll refer to this as window 3. Cover window 2 with window 3.
5. Focus back to window 1 and invoke go to implementation.

Expected:
Preferably, go to implementation opens in the focused window, window 1 in this case. Alternatively, it brings window 2 to focus and opens there. 

Actual:
Go to implementation appears over window 3, and window 2 is still covered. If window 2 has symbols, then the symbol the cursor is over will get populated in the go to impl bar and after a few seconds the window will be focused when the symbol is resolved. If it's a text file, then the window is never focused until you start typing. This is especially disconcerting if window 3 is a separate VS instance, as that makes it look like go to impl magically jumped vs instances (or in my case when I found this, both instance and hive).

**Comment by CyrusNajmabadi** [comment]
Closing out for lack of feedback.    Focus is also handled by VS.  So if this is still a problem, driving through developercommunity is the way to go.
