### ISSUE TITLE
Generation of a new SyntaxNode.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#22087]
So I am implement Guid Literal prototype.
Using the existing literals as starting guide I've add the following definition to `Syntax.xml`
```xml
    <node-structure name="GUIDLiteralTokenSyntax" parent="SyntaxToken">
      <description>Represents a Guid literal token.</description>
      <native-equiv name="GuidLiteralExpression" />

      <node-kind name="GuidLiteralToken">
        <lm-equiv name="TokenKind.GuidLiteralToken" />
        <native-equiv name="tokens.tkGuidCon" />
      </node-kind>

      <field name="Value" type="System.Guid">
        <description>The value of the guid, after removing the enclosing marks.</description>
        <native-equiv name="Token.m_GuidLiteral.m_Value" />
         TODO: Fix this.
      </field>
    </node-structure>
```
Then execute the command `\build\scripts\generate-compiler-code.cmd` to generate and build the new syntax node code.
It fails with the following
```
\src\Compilers\VisualBasic\Portable\Syntax\Syntax.xml(9135): WARNING: node structure 'GUIDLiteralTokenSyntax' has a single kind 'GuidLiteralToken' with non-matching name
\roslyn-AdamSpeight2008\src\Compilers\VisualBasic\Portable\Syntax\Syntax.xml(9135): WARNING: node structure 'GUIDLiteralTokenSyntax' has a single kind 'GuidLiteralToken' with non-matching name
\src\Compilers\VisualBasic\Portable\Syntax\Syntax.xml(9144): System.Guid is not a valid field type. You should add a node-kind entry in the syntax.xml.
\src\Compilers\VisualBasic\Portable\Syntax\Syntax.xml(9135): WARNING: node structure 'GUIDLiteralTokenSyntax' has a single kind 'GuidLiteralToken' with non-matching name
```
@AnthonyDGreen 
What does it mean by `with non-matching name`?
Why isn't `System.Guid a valid field type`?
How do to add `node-kind entry in the syntax.xml.`?

**Comment by CyrusNajmabadi** [comment]
You can look in the VisualBasicSyntaxGenerator project to see how things work.

> What does it mean by with non-matching name?

GUIDLiteralTokenSyntax and GuidLiteralToken have different casing.  One capitalizes GUID and the other SentenceCases it.  These names should not differ in casing.  See all our existing syntax elements and SyntaxKinds.

> Why isn't System.Guid a valid field type?

These are currently the only supported types for token values.
 
                Case "boolean"
                Case "text"
                Case "character"
                Case "int32"
                Case "uint32"
                Case "int64"
                Case "uint64"
                Case "float32"
                Case "float64"
               Case "decimal"
                Case "datetime"
                Case "textspan"
                Case "nodekind"
 
If you add new types it may break higher layers that are not expecting this sort of value to be exposed off of a token.

> How do to add node-kind entry in the syntax.xml.?

This is only supported for adding enum types.  For example ```<enumeration name="TypeCharacter"> and <enumeration name="LiteralBase">```

**Comment by AdamSpeight2008** [comment]
Big Thank You @CyrusNajmabadi , for the second pair of eyes. Your help has helped.
