### ISSUE TITLE
C# Ctrl-click shouldn't be enabled for `get`/`set` when they are keyword

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22097]
press Ctrl and hover over `get` or `set` in a property

Expected:
not linkified

Actual:
shows link, but clicking does nothing except scrolling the editor view.

**Comment by zaytsev-victor** [comment]
@dpoeschl could you please provide me instruction how to enable this functionality?

**Comment by Pilchie** [comment]
Tagging @rchande who implemented the original code.

**Comment by rchande** [comment]
@zaytsev-victor It's available in preview builds of Visual Studio 15.4.

**Comment by zaytsev-victor** [comment]
@rchande thanks. Do you have any ideas why it doesn't work when debugging roslyn project with VS 15.4 Preview 2.

**Comment by rchande** [comment]
@zaytsev-victor Does it specifically only not work while debugging? That may be intentional so as not to interfere with the debugger. I can follow up with the Visual Studio Editor team if having it disabled during debugging is annoying.

**Comment by zaytsev-victor** [comment]
@rchande yes, only on new instance of VS while debugging roslyn project. On instance where roslyn project is opened it works fine.

**Comment by rchande** [comment]
@zaytsev-victor Ah, so you're saying that it doesn't work in the F5'd instance while debugging. Does it work in your F5'd instance if you detach the debugger? (The feature has been ported to master: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/NavigableSymbols/NavigableSymbolService.cs) so I can't think of any reason why it shouldn't work in your F5 instance)

**Comment by zaytsev-victor** [comment]
@rchande with detached debugger it doesn't work as well

**Comment by rchande** [comment]
@zaytsev-victor Can you try setting a breakpoint in the file I mentioned earlier and see if anything happens? Also, can you make sure your dev instance has the feature enabled in Tools Options?
![image](https://user-images.githubusercontent.com/3751401/30502978-4f21f44a-9a1d-11e7-9145-0771ac240bc8.png)

**Comment by zaytsev-victor** [comment]
@rchande , sorry.
It seems I'm using too old master, because I have problems with running test on fresh master.

**Comment by rchande** [comment]
@zaytsev-victor What's preventing you from moving forward?

**Comment by zaytsev-victor** [comment]
@rchande I have a lot of exceptions 'Could not load file or assembly 'System.Security.Cryptography.Algorithms, Version=4.1.0.0' when running tests.

**Comment by rchande** [comment]
@zaytsev-victor Have you tried `git clean -xdf`ing?

**Comment by zaytsev-victor** [comment]
@rchande thanks. It works.

**Comment by Neme12** [comment]
I don't understand. Why shouldn't ctrl+click work? It currently works on all definitions, whether it's a method, local or an accessor, even though it doesn't provide a lot of value on the definition itself. Why should accessors be singled out though?

**Comment by Neme12** [comment]
If you want to remove this functionality, why not remove it on methods and all other symbol definitions too? What makes accessors special?

**Comment by sharwell** [comment]
Design review outcome: the resolution in the original pull request was not as straightforward as originally expected. The issue doesn't seem important enough to make changes to the current behavior, so we've decided to resolve this as **Won't Fix**.
