### ISSUE TITLE
First touch: VisualStudioSetup.Next VS instance fails to create new Console App

### ISSUE THREAD

**Issue by kingces95** [dotnet/roslyn#22091]
Expect first touch experience to be sync, build, launch `VisualStudioSetup.Next`, create new `Console App (.NET Core)`. Actually, failed to create console app with the following exception:

>Request locate failed with message: Cannot find service module info file '*/remoteHostService.servicehub.service.json' in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\common7\ServiceHub\Services', using discovery services failed: 

>VsixServiceDiscovery: More than one service 'remoteHostService' found at: 'C:\USERS\KINGC\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_DA80E4B2ROSLYNDEV\EXTENSIONS\MICROSOFT\ROSLYN LANGUAGE SERVICES FOR VISUAL STUDIO 15\42.42.42.42424\remoteHostService.servicehub.service.json'; 

>'C:\USERS\KINGC\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_DA80E4B2ROSLYNDEV\EXTENSIONS\MICROSOFT\ROSLYN LANGUAGE SERVICES\42.42.42.42424\remoteHostService.servicehub.service.json'

Will try to reproduce starting from a bare Windows 10 install if no one can just tell me where I've gone wrong. 

[Dump](https://microsoft-my.sharepoint.com/:u:/p/chrkin/EQH_S9G0VwNIg8tgO0oYZgUBYW4RBRuEoK2MOs_nwCQdDw)

**Comment by Pilchie** [comment]
Tagging @jasonmalinowski who just changed some of this stuff, and @heejaechang who knows about the servicehub stuff.

**Comment by kingces95** [comment]
Are there any rolling CI tests which launch `VisualStudioSetup.Next` and poke around a bit?

**Comment by jasonmalinowski** [comment]
@kingces95 Yep, we have these queues:

https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration/
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration/

They do a slightly different install path (long story...) but the expectation is they'd catch issues like this. I'll poke around further later today.

**Comment by kingces95** [comment]
@jasonmalinowski Nice! Thanks. 

I'm unable to find a link from the links you posted that show the automation script those lanes are running. Is there some way I could see that?

**Comment by heejaechang** [comment]
@kingces95 that is because you have old bits laying around in

'C:\USERS\KINGC\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_DA80E4B2ROSLYNDEV\EXTENSIONS\MICROSOFT\ROSLYN LANGUAGE SERVICES FOR VISUAL STUDIO 15\42.42.42.42424\*'

@jasonmalinowski 's change moved all stuff in there to 
'C:\USERS\KINGC\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_DA80E4B2ROSLYNDEV\EXTENSIONS\MICROSOFT\ROSLYN LANGUAGE SERVICES\42.42.42.42424\*'

and VS now gets confused because bits exist in 2 places when there should be only one.

delete 15.0_DA80E4B2ROSLYNDEV folders from both %localappdata% and %appdata%\MS\VS folder

and re-launch devenv /rootsuffix RoslynDev

that should fix it.

**Comment by heejaechang** [comment]
@dpoeschl  @jasonmalinowski @Pilchie is there a way to mitigate this situation for roslyn dev? I had same issue which I fixed by removing the roslyndev hive but not sure how it can be resolved automatically.

**Comment by jasonmalinowski** [comment]
@heejaechang It shouldn't have been necessary as I left the old extension there with nothing in it, meaning these *should* have been deleted. Will have to investigate further then.

**Comment by heejaechang** [comment]
@jasonmalinowski hmmm.  somehow, the files where still there. I had to manually delete those.

**Comment by kingces95** [comment]
I deleted the folders `15.0_DA80E4B2ROSLYNDEV` in both directories and was able to create a new project.

I expected to be able to start editing the file but shortly thereafter I encounter a second exception in the `RoslynServices` `.cctor`. I tried to edit the `.cctor` to change it from a lambda to procedural so I could set a breakpoint but after the rebuild the breakpoint didn't bind. I'll investigate further but it's unexpected that change resulted in a BP that couldn't bind.

![image](https://user-images.githubusercontent.com/4120386/30408860-7b36fb9c-98cf-11e7-8adf-6edabe8fb865.png)

**Comment by kingces95** [comment]
I expected enabling the VS power tool to debug child process would capture the `RoslynServices` process so that I could hit a BP in the `.cctor` but it actually didn't attach to the child. I wonder how folks generally attach to the child...

![image](https://user-images.githubusercontent.com/4120386/30409697-c4da6c98-98d4-11e7-8133-fa2c4a896447.png)

**Comment by kingces95** [comment]
Using GFlags, attached to ServiceHub and got a FileNotFoundException in the RoslynServices .cctor that `System.Composition.TypedParts` wasn't found. Quite a pain using GFlags. Real shame the attach to child process power tool doesn't work... :(

![image](https://user-images.githubusercontent.com/4120386/30411168-5fbf80ce-98dd-11e7-8881-3c908e21e83f.png)

**Comment by MaStr11** [comment]
I get the same error as originally posted by @kingces95 but with different locations:

{"Request locate failed with message: Cannot find service module info file '*/remoteHostService.servicehub.service.json' in 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\common7\\ServiceHub\\Services', using discovery services failed: VsixServiceDiscovery: Es wurden mehrere Dienste \"remoteHostService\" gefunden unter: 'C:\\**PROGRAM FILES (X86)**\\MICROSOFT VISUAL STUDIO\\2017\\PROFESSIONAL\\COMMON7\\IDE\\COMMONEXTENSIONS\\MICROSOFT\\MANAGEDLANGUAGES\\VBCSHARP\\LANGUAGESERVICESNEXT\\remoteHostService.servicehub.service.json'; 'C:\\USERS\\UserName\\**APPDATA**\\LOCAL\\MICROSOFT\\VISUALSTUDIO\\15.0_F3B3FB15ROSLYNDEV\\EXTENSIONS\\MICROSOFT\\ROSLYN LANGUAGE SERVICES\\42.42.42.42424\\remoteHostService.servicehub.service.json'"}

There is a `Microsoft.CodeAnalysis.Remote.ServiceHub.dll` in both directories but with different versions:
* ProgramFiles: 2.3.2-beta1-62030-09.
* AppData: 2.6.0-dev-5673500.

I tried to delete the directory 
C:\\USERS\\UserName\\APPDATA\\LOCAL\\MICROSOFT\\VISUALSTUDIO\\15.0_F3B3FB15ROSLYNDEV
but this didn't help. I'm using VS 15.3.4.

How can I convince VS to use the 'C:\USERS\UserName\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_F3B3FB15ROSLYNDEV\EXTENSIONS\MICROSOFT\ROSLYN LANGUAGE SERVICES\42.42.42.42424\remoteHostService.servicehub.service.json' file?

**Comment by MaStr11** [comment]
Figured it out myself. Running `restore.cmd` fixed my issue.

**Comment by kingces95** [comment]
Oh, cool if that works. Deleting the directories worked tool. But now I get a new issue. Perhaps I should close this and open a new issue to not conflate the first with second. We'll see if I get any comments on the second..

**Comment by heejaechang** [comment]
@kingces95 are we still talking about roslyndev hive? if it is, can you check devenv.exe.config in the hive to see where System.Composition.TypedParts is pointing to. and what version is there? you might need to delete the hive and your roslyn binary directory and restore/rebuild whole bits again.

**Comment by kingces95** [comment]
@heejaechang Thanks for your help. If I rebuild from a clean VM then I no longer reproduce this issue. So now I'm working on getting my DEV VM setup. If I can't get it working I'll re-open!

**Comment by jasonmalinowski** [comment]
@kingces95 Going to reactivate this as I still want to look at that dump you provided to better understand what went wrong here. Happy you got worked around...but you shouldn't have to do that!

**Comment by kingces95** [comment]
@jasonmalinowski Thanks. I would have re-opened anyway; While it doesn't reproduce if I start from a clean Windows 10, it does reproduce on my development machine where I first observed the failure.

I need a way to clear out the corrupted state from the previous private hive launches. 

The following command is, apparently, insufficient:  

> C:\git\roslyn>rmdir /s/q C:\Users\kingc\AppData\Local\Microsoft\VisualStudio\15.0_da80e4b2RoslynDev C:\Users\kingc\AppData\Roaming\Microsoft\VisualStudio\15.0_da80e4b2RoslynDev

The latest exception is:

>StreamJsonRpc.RemoteInvocationException: 'The type initializer for 'Microsoft.CodeAnalysis.Remote.SolutionService' threw an exception.'

![image](https://user-images.githubusercontent.com/4120386/30508794-7e9d8a9a-9a6d-11e7-9972-aaa237327193.png)

I'd investigate further except I know that if I can wipe away the stale state then it'll work.

**Comment by kingces95** [comment]
@heejaechang @jasonmalinowski Can we create a script that resets the experimental Roslyn hive? After all, the reason we have an isolate hive is because we expect it to become corrupt. So it only makes sense to provide a way to reset it should that happen.

**Comment by kingces95** [comment]
Oh, but if you still wanna look at the dump then we'll leave it open.

**Comment by jinujoseph** [comment]
@kingces95 closing this as the corresponding issue seems to be fixed.
