### ISSUE TITLE
Offer "using static" from unbound members to their types

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22099]
// Reduced from https://developercommunity.visualstudio.com/content/problem/111688/scenario-2-c-navigation-moves-out-of-process-add-u.html

**Version Used**: latest as of this post

**Steps to Reproduce**:

1. C# code

```C#
using System;

public class C1
{
    public class C2
    {
        public static int CField;
    }
}

public class D1
{
    public static int DField;
}

public class Test
{
    void M()
    {
        var a = C2.CField; // Good, "using static C1;" offered
        var b = CField; // No "using static" offered
        var c = DField; // No "using static" offered
        var d = Max(1, 2); // No "using static System.Math;" offered
    }
}
```

It would be nice if `using static ...` was offered in the 3 later cases, though we'd have to be careful that there aren't so many matches that it gets noisy. The "Math" case is pretty compelling.

**Comment by CyrusNajmabadi** [comment]
Unlikely to make changes here due to lack of feedback.
