### ISSUE TITLE
ContextIntervalTree.GetSmallestContainingIntervalWorker does not find node with equal endpoint on right side of tree.

### ISSUE THREAD

**Issue by mcpherson-sa** [dotnet/roslyn#22090]
In the file ContextIntervalTree in the Microsoft.CodeAnalysis.Formatting namespace, when descending the tree, the algo only goes to the right if end < MaxEndValue(right). Since we could be looking for nodes containing the query interval either inclusively depending on the parameter predicate, the comparison should be end <= MaxEndValue(right)  (as is the case for the left side) otherwise it won't find intervals having end values equal to the end value of the query interval.

**Comment by CyrusNajmabadi** [comment]
@mcpherson-sa Do you have an example where this ends up being an issue?

**Comment by CyrusNajmabadi** [comment]
Closing out.
