### ISSUE TITLE
C# Ctrl-Click should be enabled for other LINQ operators

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22096]
From: https://developercommunity.visualstudio.com/content/problem/111673/c-ctrl-click-should-be-enabled-for-other-linq-oper.html

1. Try Ctrl-Click on LINQ query operator keywords

Seems only `select` has link and goes to `public interface IEnumerable<out T> : IEnumerable`

it would be great to navigate to `Select()` method.

Other keywords do not work: where, orderby, join, etc.

**Comment by zaytsev-victor** [comment]
Tested on latest master branch.
![img](https://i.gyazo.com/f503f1e2956d2746a77aa1b573a441d4.gif)

**Comment by MaStr11** [comment]
@zaytsev-victor The issue is about the query syntax. See [Query Syntax and Method Syntax in LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/query-syntax-and-method-syntax-in-linq) for the differences. I have a PR pending for this here #23049.

**Comment by zaytsev-victor** [comment]
@MaStr11 I missed that it is a bout query syntax. Thanks (:

**Comment by CyrusNajmabadi** [comment]
Does goto-def work here?  If not, it would be nice to support that as well.
