### ISSUE TITLE
Use new telemetry API to send unhashed data for internal users

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#22101]
1.	Don't hash if the user is internal.  We should figure out if there is a way to do that as divorced as we are from the actual telemetry.
2.	Allow our CodeFixProviders to opt-in to just providing their real name, so that we would only hash providers that didn’t opt-in.

**Comment by CyrusNajmabadi** [comment]
Closing out our existing system seems to be workign fine for our needs here
