### ISSUE TITLE
Calculating $(CodeAnalysisPath)/$(CodeAnalysisStaticAnalysisDirectory) in Microsoft.CodeAnalysis.targets takes up 1.3% of evaluation of a solution-wide design-time build 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#22110]
See: https://github.com/dotnet/sdk/issues/1586.

``` XML
 <PropertyGroup>
    <CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'=='' and Exists('$(VsInstallRoot)\Team Tools\Static Analysis Tools\')">$(VsInstallRoot)\Team Tools\Static Analysis Tools\</CodeAnalysisStaticAnalysisDirectory>
    <CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\15.0\Setup\EDev@StanDir)</CodeAnalysisStaticAnalysisDirectory>
    <!-- If we didn't find the first registry path, assume we're in a 64bit process. -->
    <!-- read registry from Wow6432Node -->
    <CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\15.0\Setup\EDev@StanDir)</CodeAnalysisStaticAnalysisDirectory>

    <!-- if we didn't find the registry path yet, then try Win8 Express location -->
    <CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Microsoft\VSWinExpress\15.0\Setup\EDev@StanDir)</CodeAnalysisStaticAnalysisDirectory>
    <!-- If we didn't find the registry path yet, then try Win8 Express 64-bit location -->
    <CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VSWinExpress\15.0\Setup\EDev@StanDir)</CodeAnalysisStaticAnalysisDirectory>

    <!-- If we didn't find the registry path yet, try WP Express locations -->
    <CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Microsoft\VPDExpress\15.0\Setup\EDev@StanDir)</CodeAnalysisStaticAnalysisDirectory>
    <!-- If we didn't find the registry path yet, try WP Express 64-bit locations -->
    <CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VPDExpress\15.0\Setup\EDev@StanDir)</CodeAnalysisStaticAnalysisDirectory>

    <!-- If we didn't find the registry path yet, try WD Express locations -->
    <CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Microsoft\WDExpress\15.0\Setup\EDev@StanDir)</CodeAnalysisStaticAnalysisDirectory>
    <!-- If we didn't find the registry path yet, try WD Express 64-bit locations -->
    <CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\WDExpress\15.0\Setup\EDev@StanDir)</CodeAnalysisStaticAnalysisDirectory>
</PropertyGroup>

 <PropertyGroup>
    <!-- FxCopDir must be considered for backwards compatibility with the Visual Studio 2005 task, except within the context of a Team Build build. -->
    <CodeAnalysisPath Condition="'$(CodeAnalysisPath)'=='' and '$(FxCopDir)'!='' and '$(TeamBuildConstants)'==''">$(FxCopDir)</CodeAnalysisPath>
    <CodeAnalysisPath Condition="'$(CodeAnalysisPath)'=='' and Exists('$(VsInstallRoot)\Team Tools\Static Analysis Tools\FxCop\')">$(VsInstallRoot)\Team Tools\Static Analysis Tools\FxCop\</CodeAnalysisPath>
    <CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\15.0\Setup\EDev@FxCopDir)</CodeAnalysisPath>
    <!-- If we didn't find the first registry path, assume we're in a 64bit process. -->
    <!-- read registry from Wow6432Node -->
    <CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\15.0\Setup\EDev@FxCopDir)</CodeAnalysisPath>
    <!-- If we didn't find the registry path yet, try Win8 Express locations -->
    <CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Microsoft\VSWinExpress\15.0\Setup\EDev@FxCopDir)</CodeAnalysisPath>
    <CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VSWinExpress\15.0\Setup\EDev@FxCopDir)</CodeAnalysisPath>
    <!-- If we didn't find the registry path yet, try WP Express locations -->
    <CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Microsoft\VPDExpress\15.0\Setup\EDev@FxCopDir)</CodeAnalysisPath>
    <CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VPDExpress\15.0\Setup\EDev@FxCopDir)</CodeAnalysisPath>
    <!-- If we didn't find the registry path yet, try WD Express locations -->
    <CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Microsoft\WDExpress\15.0\Setup\EDev@FxCopDir)</CodeAnalysisPath>
    <CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''">$(Registry:HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\WDExpress\15.0\Setup\EDev@FxCopDir)</CodeAnalysisPath>
</PropertyGroup
```

Pass|File|Line #|Expression|Inc (ms)|Inc (%)|Exc (ms)|Exc (%)|#|Bug
---|---|---:|---|---:|---:|---:|---:|---:|---
Total Evaluation||||6159|100%|54|0.9%||
Properties (Pass 1)||||3312|53.8%|9|0.1%||
ItemDefinitionGroup (Pass 2)||||14|0.2%|2|0%||
Items (Pass 3)||||566|9.2%|24|0.4%||
Lazy Items (Pass 3.1)||||1826|29.6%|158|2.6%||
UsingTasks (Pass 4)||||59|1%|59|1%||
Targets (Pass 5)||||327|5.3%|208|3.4%||
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|26|`<CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''" >$(Reg...`|7|0.1%|6|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|29|`<CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''" >$(Reg...`|5|0.1%|4|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|37|`<CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''" >$(Reg...`|5|0.1%|4|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|32|`<CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''" >$(Reg...`|5|0.1%|4|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|42|`<CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''" >$(Reg...`|4|0.1%|4|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|34|`<CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''" >$(Reg...`|4|0.1%|3|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|39|`<CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''" >$(Reg...`|4|0.1%|3|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|44|`<CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'==''" >$(Reg...`|4|0.1%|3|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|25|`<CodeAnalysisStaticAnalysisDirectory Condition="'$(CodeAnalysisStaticAnalysisDirectory)'=='' and Exi...`|6|0.1%|0|0%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|97|`<CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''" >$(Registry:HKEY_LOCAL_MACHINE\Software\Micr...`|5|0.1%|4|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|100|`<CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''" >$(Registry:HKEY_LOCAL_MACHINE\Software\Wow6...`|4|0.1%|4|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|102|`<CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''" >$(Registry:HKEY_LOCAL_MACHINE\Software\Micr...`|4|0.1%|3|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|105|`<CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''" >$(Registry:HKEY_LOCAL_MACHINE\Software\Micr...`|4|0.1%|3|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|108|`<CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''" >$(Registry:HKEY_LOCAL_MACHINE\Software\Micr...`|4|0.1%|3|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|109|`<CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''" >$(Registry:HKEY_LOCAL_MACHINE\Software\Wow6...`|4|0.1%|3|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|106|`<CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''" >$(Registry:HKEY_LOCAL_MACHINE\Software\Wow6...`|4|0.1%|3|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|103|`<CodeAnalysisPath Condition="'$(CodeAnalysisPath)'==''" >$(Registry:HKEY_LOCAL_MACHINE\Software\Wow6...`|4|0.1%|3|0.1%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|95|`<CodeAnalysisPath Condition="'$(CodeAnalysisPath)'=='' and '$(FxCopDir)'!='' and '$(TeamBuildConstan...`|1|0%|0|0%|223|
Properties (Pass 1)|Microsoft.CodeAnalysis.targets|96|`<CodeAnalysisPath Condition="'$(CodeAnalysisPath)'=='' and Exists('$(VsInstallRoot)\Team Tools\Stati...`|5|0.1%|0|0%|223|

**Comment by mavasani** [comment]
Fixed with https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/88928?path=%2Fsrc%2Fedev%2FStaticAnalysis%2Ffxcoptask%2FMicrosoft.CodeAnalysis.targets&_a=overview

**Comment by davkean** [comment]
Thanks!
