### ISSUE TITLE
Simplifier changes semantics of ?. expressions

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#2211]
In the case below, the simplifier will offer to remove the cast to int? as it is unnecessary.

```C#
private static int test(List<int> list)
{
    return ((int?)list?.Count).GetValueOrDefault();
}
```

However in the course of simplifying, it also removes the enclosing parenthesis which changes the semantics of the expression.

**Expected:**
```C#
private static int test(List<int> list)
{
    return (list?.Count).GetValueOrDefault();
}
```

**Actual:**
```C#
private static int test(List<int> list)
{
    return list?.Count.GetValueOrDefault();
}
```

**Comment by shyamnamboodiripad** [comment]
Assigning back to @jmarolf for verification.
