### ISSUE TITLE
Unexpected OperationKind.None for instance receiver of dynamic invocation with errors

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22121]
See https://github.com/dotnet/roslyn/pull/21711#discussion_r138961908

**Comment by jinujoseph** [comment]
Verify and close

**Comment by mavasani** [comment]
We still seem to generate an operation with `OperationKind.None` for a `BoundMethodGroup` node in the bound tree:

```
 string expectedOperationTree = @"
IInvalidOperation (OperationKind.Invalid, Type: ?, IsInvalid) (Syntax: 'M(d)')
  Children(2):
      IOperation:  (OperationKind.None, Type: null, IsInvalid) (Syntax: 'M')
      ILocalReferenceOperation: d (OperationKind.LocalReference, Type: dynamic, IsInvalid) (Syntax: 'd')
";
```

However, that is wrapped with an invalid operation and we have a separate item tracking implementing BoundMethodGroup support: https://github.com/dotnet/roslyn/issues/19965
