### ISSUE TITLE
SyntaxGenerator Tools should throw exceptions.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#22131]
The current implementation of the SyntaxGenerator Tools when it expectations are not met, 
Rather that putting a "dummy" value, that is silent and allow the generation of the syntax, bounds etc to continue.
Those dummy values are only causing problems rather down the line, when doing a build of Roslyn compiler. At which time useful information, that could aid in debugging the errors have be lost.

Now if executing syntax generator tool succeeded without throwing an exception, you're reasonable certain that they are valid.

I think it would a task suitable for `Up For Grabs`.

**Comment by gafter** [comment]
I would prefer that the syntax generator print a nice error message.
