### ISSUE TITLE
Question: is there a NuGet feed for latest IOperation changes?

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#22159]
I'd like to try out the latest changes to the `IOperation` API. I think they are in the features/ioperation branch.

Is there a NuGet feed I can reference or do I need to build that branch from source? I've tried that in the past, but got into signing/versioning issues that prevented me to reference the output assemblies.

**Comment by jasonmalinowski** [comment]
There isn't a feed, but #22173 is now an active PR merging into master. We anticipate it'll merge today or tomorrow.
