### ISSUE TITLE
First Touch Test Failure/Debugger.Break

### ISSUE THREAD

**Issue by kingces95** [dotnet/roslyn#22156]
I expected master, as of the time of writing to restore, build, and test without failure. I actually observe the test run failing. I'm running Windows 10 VM in Parallels on a MacBookPro.

![image](https://user-images.githubusercontent.com/4120386/30508007-fa8e5be2-9a5a-11e7-9646-304cfb6888ff.png)

The gaurd page warning comes from `csrss`. So that's weird. Instead, I attach to the console test runner at 13948:

![image](https://user-images.githubusercontent.com/4120386/30508047-aa82846a-9a5b-11e7-91ea-6f2338786c10.png)

Which has a command line of:

![image](https://user-images.githubusercontent.com/4120386/30508050-be18ea78-9a5b-11e7-9162-22004aabfba6.png)

And I find the runner raised a `Debugger.Break`:

![image](https://user-images.githubusercontent.com/4120386/30508080-74ffce14-9a5c-11e7-9659-7226d1ce8a72.png)

And if I hit `F5` a few times I hit the same `Debugger.Break` until finally the test finishes and I show all tests pass:

![image](https://user-images.githubusercontent.com/4120386/30508114-18972b4e-9a5d-11e7-8bda-bd72560dd075.png)

Though I expected no failures, I'd expect if a dialog pops up because a test hit a debug break point, that ultimately the test runner would show a failed test.

Let me know if you need more information. Happens every time on my VM.

**Comment by jcouv** [comment]
@kingces95 Thanks for raising this issue (very clear bug report).
I'll fix asap.

**Comment by kingces95** [comment]
@Jcouv Could you please link to the PR that fixes this issue?

**Comment by jcouv** [comment]
Fixed by #22158
