### ISSUE TITLE
'Extract method' refactoring breaks compilation if there are local functions

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#22150]
**Version Used**: 

Microsoft Visual Studio Professional 2017 
Version 15.3.0
VisualStudio.15.Release/15.3.0+26730.3
Microsoft .NET Framework
Version 4.7.02046

**Steps to Reproduce**:

Use 'extract method' refactoring in the code below:
```cs
  public void Test()
  {
    int x = 0;
    // extract the two lines below
    void Local() { }
    Console.WriteLine(x);
  }
```

**Expected Behavior**:

```cs
  public void Test()
  {
    int x = 0;
    NewMethod(x);
  }

  private static void NewMethod(int x)
  {
    void Local() { }
    Console.WriteLine(x);
  }
```

**Actual Behavior**:

```cs
  public void Test()
  {
    int x = 0;
    NewMethod();
  }

  private static void NewMethod()
  {
    void Local() { }
    Console.WriteLine(x);
  }
```

There are also other cases where the refactoring breaks code because there is no way to actually execute the refactoring without breaking it. However, it looks like Roslyn should at least warn about conflicts in such cases.

There are currently no conflicts neither in the context menu nor in the preview window in the following case:

```cs
class C
{
  public static void Main()
  {
    void Local() { }
    Local(); // invoke 'extract method' over this statement
  }
}
```

Thanks @jnm2 for contributing to the final form of this bug report in the original discussion [here](https://github.com/dotnet/csharplang/issues/910).

**Comment by jcouv** [comment]
FYI @agocke

**Comment by CyrusNajmabadi** [comment]
This seems to work fine.  Will add test demonstrating as such.
