### ISSUE TITLE
C# Compiler does not accept ?? operator of operands GenericParameterType and throw expression

### ISSUE THREAD

**Issue by ronelm2000** [dotnet/roslyn#22161]
**Version Used**:  Visual Studio 2017 Community with .NET Core 2.0 SDK
**Steps to Reproduce**: 
1. Create a project; Ensure .NET Core 2.0 is installed, and the project is built on .NET Framework 4.7.
2. Type this code in any Class File.
```cs
    class Button<TIScreen> : IGUIEntity<TIScreen> where TIScreen : IScreen 
    // you can replace these with skeleton interfaces. 
    // The important part is it's a generic class. 
    // If it's important, IScreen is also an interface.
    {
        int[] SpriteBatch = null;
        public TIScreen Parent { get; private set; }
        public Button (int[] batch, TIScreen screen)
        {
            SpriteBatch = batch ?? throw new NullReferenceException();
            Parent = screen ?? throw new Exception();
        }
}
```
3. You can make dummy interfaces for IScreen and IGUIEntity. [Optional]

**Expected Behavior**: This will work. The first statement worked since I'm utilizing C# 7 and .NET Standard 2.0 / .NET Framework 4.7
**Actual Behavior**: The second statement throws an error, that operator ?? cannot be applied to operands of type TIScreen and throw expression. (Image used is the actual bug.)
![screenshot 2017-09-17 19 12 08](https://user-images.githubusercontent.com/12634987/30520600-7a7210d6-9be3-11e7-9df2-42e7dc005be6.png)
**Workaround**: Use ? and : operators instead. eg.
```cs
Parent = (screen != null) ? screen : throw new NullReferenceException(ExceptionMessages.ParentIsNull);
```

**Comment by svick** [comment]
Can `TIScreen` be a `struct`? If not, then changing the constraint to `where TIScreen : class, IScreen` will allow you to use the `??` operator.

**Comment by ronelm2000** [comment]
Wait, can structs implement interfaces? If so, that's a total miss on my part.

**Comment by svick** [comment]
[Yes, they can.](https://sharplab.io/#v2:C4LgTgrgdgPgAgBgARwIwG4CwAoHBLKYAUzADMBDAYyKQEkcBvHJFlAFiQFkAKASi2wBfHDgDOwSJWBIAykhB1GzVnADM7LnyQBeAHwpUATm4AiGQDpOSPAFsADgBsiNooVF1LJ/jmG5scACYDAHYlbFYDADYNNAAOPmUWJnCI1gA3cjAkd20kKCIAd1k+AVTWUUsSpAB6aqQAEzwwIikkSnIHB0TU2msdbNKy60r+GrqCYjIqGnbO7u6IuA4AYQB7KHEwcgIieoAeABVdbgOkYF4kAoALEhpThV69M5H0Flq29c3t/Pq2jq6UmUFqw1hsJN9dtxRN5AUhfIIgA=)

**Comment by ronelm2000** [comment]
Thanks. ?? should honestly work with both structs and classes (where ?? always resolves to never return the right-side operand) but that's a different thing.

Closed.
