### ISSUE TITLE
Decide whether we should use highest bound node or lowest bound node to bind statement or root in GetOperation

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#22179]
right now, we use highest bound node for both C# and VB so that we get larger operation tree and then search the tree given node to be conservative. but since we only return explicit operation, it might be just wasting since explicit operation with same syntax node is most likely always lowest one.

we should investigate a bit more and change it to lowest bound node.

**Comment by heejaechang** [comment]
related to #21857

**Comment by jinujoseph** [comment]
@heejaechang can you confirm this and add a assert and invariant document

**Comment by 333fred** [comment]
@AlekseyTs @mavasani any objections to closing this out? I don't think we're about to make any changes here.

**Comment by AlekseyTs** [comment]
> any objections to closing this out?

No

**Comment by mavasani** [comment]
No, sounds good to close.
