### ISSUE TITLE
these tests in OutVarTests call GetOperation with unsupported nodes and expect valid IOperation

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#22175]
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.Scope_DeclaratorArguments_10 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.Scope_DeclaratorArguments_05 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.Scope_DeclaratorArguments_13 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.Scope_DeclaratorArguments_09 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.Scope_DeclaratorArguments_08 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.Scope_DeclaratorArguments_12 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.Scope_DeclaratorArguments_14 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.Scope_DeclaratorArguments_04 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.GetEnclosingBinderInternalRecovery_10 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.Scope_DeclaratorArguments_11 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.GetEnclosingBinderInternalRecovery_09 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.Scope_DeclaratorArguments_03 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.Scope_DeclaratorArguments_01 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.GetEnclosingBinderInternalRecovery_11 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.ElementAccess_05 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.Scope_DeclaratorArguments_06 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.GlobalCode_DeclaratorArguments_02 FAILED:
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.Scope_DeclaratorArguments_02 FAILED:

**Comment by 333fred** [comment]
An example of the issue:
```C#
class C
{
    System.IDisposable Dummy(params object[] x) { return null; }

    void Test1()
    {
        using (var d, e(Dummy(TakeOutParam(true, out var x1), x1)))
        {
            Dummy(x1);
        }
    }

    static bool TakeOutParam<T>(T y, out T x)
    {
        x = y;
        return true;
    }
}
```

The issue here is on `e(Dummy(TakeOutParam(true, out var x1), x1))`. We have a DeclaratorArgumentSyntax node on the VariableDeclarator, but the IOperation node doesn't have a place to put the resulting bound nodes. To fix this, we should add a new field to `IVariableDeclarator`, `IgnoredArguments`, which will be `ImmutableArray<IOperation>`, to match the underlying BoundLocalDeclaration. Similar to how we deal with http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/Loops/IDoLoopOperation.cs,a402528166bbd5ad,references.

**Comment by 333fred** [comment]
Tagging @dotnet/analyzer-ioperation @AlekseyTs for comments.

**Comment by 333fred** [comment]
Design Decision:
Do it.
