### ISSUE TITLE
Script to Reset Roslyn Experimental Instance

### ISSUE THREAD

**Issue by kingces95** [dotnet/roslyn#22183]
I expect that after a fix has been submitted to correct a bug which corrupts the Roslyn VS 2017 experimental instance (see https://github.com/dotnet/roslyn/issues/22091), that there will exist a script contributors can run to reset their experimental instances to a clean state. And in so doing, when they sync, rebuild and deploy with the fix, then the experimental instance will launch. 

Actually, I don't find such a script and trying a few remedies from the web did not allow me to successfully launch my experimental instance (and create a new project).

**Comment by kingces95** [comment]
From the web:

Via [CreateExpInstance /Reset /VSInstance=12.0 /RootSuffix=Exp](https://www.codeproject.com/Tips/832362/Resetting-the-Visual-Studio-Experimental-Instance)
Via [VS plugin](https://marketplace.visualstudio.com/items?itemName=BenDeveloper.ResetExperimentalInstance)
Via [Daniel Cazzulino's Blog](http://blogs.clariusconsulting.net/kzu/resetting-visual-studio-experimental-instance-to-its-super-clean-initial-state/)

They're all slightly different.

**Comment by Pilchie** [comment]
Tagging @jasonmalinowski in this issue too.

**Comment by kingces95** [comment]
@heejaechang I tried to delete the directories listed in https://github.com/dotnet/roslyn/issues/22091 but that issue still reproduces. Is there any chance you could roll a script that nukes all the roslyn directories and registry keys? That way contributors would know whether it's a corrupt install or due to some other environmental issue on their machine...

**Comment by kingces95** [comment]
@jasonmalinowski Any chance this gets scheduled? If not, happy to close it out.

**Comment by jasonmalinowski** [comment]
@kingces95 Nope, leave it open. Even if we can't get it scheduled soon it's something that we'd want to keep on the backlog so it can be. We're just juggling a few other fires right now.
