### ISSUE TITLE
Some CSharpFormattingOptions not getting serialized

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#2218]
The formatting options [`SmartIndent`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Formatting/FormattingOptions.cs,ecf488cca70d0c84,references) and [`NewLine`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Formatting/FormattingOptions.cs,ecf488cca70d0c84,references) are not getting serialized because [`CSharpSettingsManagerOptionSerializer`](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.CSharp/Options/CSharpSettingsManagerOptionSerializer.cs,054f9459b50dd5b4) does not Export the [featurename](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Formatting/FormattingOptions.cs,263f327a8231d7b7,references)

Corresponding intergration tests should be added. Tagging @dpoeschl

**Comment by Pilchie** [comment]
Note: Smart Indent should probably be serialized by `CSharpLanguageSettingsSerializer`, not the `CSharpSettingsManagerOptionSerializer`, since it's actually persisted by the editor.

**Comment by SetTrend** [comment]
Still not working for TypeScript language in version 14.0.23107.0 D14REL.

**Comment by Pilchie** [comment]
@CyrusNajmabadi does typescript need a similar fix?

**Comment by lukefan6** [comment]
I'm using VS2015 Enterprise Version 14.0.25123.00 Update 2 and this issue still occurs from time to time.

Any ideas which VS update package is required to have this issue fixed?

**Comment by Pilchie** [comment]
Hi @lukefan6 can you provide more details about what you're seeing?  This should be fixed in Update 2.

**Comment by lukefan6** [comment]
Hi @Pilchie I was unable to reproduce the issue until now

It happened when I use task manager to force close Visual Studio.

Before force-closing, the c# tabs settings says Keep tabs

After force-closing and reopening Visual Studio, the c# tabs settings went back to Insert spaces.

Hope the information helps

**Comment by JoshuaBStevens** [comment]
@lukefan6, can you provide some information to help us understand what happened?
1. What version of VS are you running?
2. Did you set "Keep Tabs" in the same VS session that you force-closed, or in a previous session?
3. Have you customized the "Automatically save my settings to this file" path under Environment / "Import and Export Settings" in Tools/Options?
4. Can you please attach %localappdata%\Microsoft\VisualStudio\SettingsLogs\*.tsv and the file pointed to by the path in that Options page I asked about in question #3?

Thanks!
-Josh

**Comment by JoshuaBStevens** [comment]
Anyone having this problem on VS 2015 Update 3: please apply the DLLs in the attached zip archive using the patch.cmd script.  This will add more details to %localappdata%\Microsoft\VisualStudio\SettingsLogs*.tsv and also create a new log file %localappdata%\VSProfilesLog.txt.  If you could reply to this thread with the resulting logs after the problem occurs again, it would be very helpful.

Thanks!
-Josh
[SettingsLogPatch.zip](https://github.com/dotnet/roslyn/files/414319/SettingsLogPatch.zip)

**Comment by lukefan6** [comment]
@JoshuaBStevens 
1. Visual Studio Enterprise 2015 Version 14.0.25123.00 Update 2
2. I tried both (same session and previous session), and the results are same, after force-closing, it went back to "Insert spaces".
3. I don't think I did, the path points to "c:\users\lukefan\documents\visual studio 2015\settings\CurrentSettings.vssettings"
4. Please see the attached

[2016-08-12.zip](https://github.com/dotnet/roslyn/files/414540/2016-08-12.zip)

**Comment by JoshuaBStevens** [comment]
Thanks, @lukefan6.  I can clearly see the setting switching back and forth in the log, although the reason why isn't obvious.  Could you try turning off settings synchronization on the "Environment / Synchronized Settings" options page to see if that helps?

**Comment by lukefan6** [comment]
@JoshuaBStevens 
Unfortunately, turning sync off didn't help :(

**Comment by JoshuaBStevens** [comment]
@lukefan6, would you consider installing Update 3?  It's possible there may be a fix in that update for your issue, and even if there isn't, installing the update will allow you to install the patch I uploaded to provide more information about the issue.

**Comment by lukefan6** [comment]
@JoshuaBStevens I installed update 3 and re-apply the patch you provided.
I also tried turning sync on and off after installing update 3.
And the issue still exists :(

Hope the attached log would help


![screenshot at 8 16 12-29-35](https://cloud.githubusercontent.com/assets/8968212/17687983/1fff91a6-63ad-11e6-88a5-f749ff6a9ecf.png)
[2016-08-16.zip](https://github.com/dotnet/roslyn/files/419543/2016-08-16.zip)

**Comment by JoshuaBStevens** [comment]
@lukefan6, I'm not seeing the expected entries in the log.  I don't think the patch is installed correctly on your machine.  Can you try running unpatch.cmd and then patch.cmd again?

**Comment by JoshuaBStevens** [comment]
@lukefan6, a word of caution though: if you run unpatch.cmd, it'll overwrite certain VS DLLs with copies it made when you ran patch.cmd.  So if you've updated VS in between, you'll be left with obsolete DLLs.  If that's the case, *don't* run patch.cmd, just delete %localappdata%\SettingsLogPatchBackup instead so patch.cmd will run.  (If that folder is present, it will just tell you the patch has already been applied.)

**Comment by lukefan6** [comment]
@JoshuaBStevens , noted.
Here's a newer version of log after applying your instructions.
By the way, I couldn't find VSProfileLog.txt under AppData\Local, any idea why?

[2016-08-17.zip](https://github.com/dotnet/roslyn/files/421635/2016-08-17.zip)

**Comment by JoshuaBStevens** [comment]
Thanks, @lukefan6.  Now I can see the extra logging, which suggests that perhaps %userprofile%\documents\visual studio 2015\settings\CurrentSettings.vssettings had been updated to contain the bad setting value.  VS detected the update and imported that file on startup.  (Having %localappdata%\VSProfilesLog -- note the "s" in profiles -- would help, but I don't know why it wasn't created.)  Could you try running Process Monitor to watch writes to that file and see if there is any other process besides devenv.exe touching it?

**Comment by JoshuaBStevens** [comment]
@lukefan6, if you can run Process Monitor to watch the CurrentSettings file as I mentioned, could you also watch for registry operations under HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\14.0\Profile?  That may help pinpoint the root cause.

**Comment by lukefan6** [comment]
It seems the only process that had attempted writing CurrentSettings.vssettings is devenv.exe.
As for registry operations, I set filter to include any path that contains HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\14.0\Profile but nothing related had came out.

**Comment by JoshuaBStevens** [comment]
Good news: we've found the cause of the problem and the fix will be in the next "micro update" (AKA Update 3.5), which should be released soon.  In the meantime, as a workaround, you can edit HKCU\Software\Microsoft\VisualStudio\14.0\Profile\AutoSaveFile to be an invalid file path (such as "c:\/").  VS will complain about being unable to write the file whenever you exit, but you can ignore that.  Thanks for all your help on this issue!

-Josh

**Comment by lukefan6** [comment]
It's such an excellent news!
Thank you guys!

btw, will we receive the "micro update" from the built-in notification center?

**Comment by JoshuaBStevens** [comment]
@lukefan6, yep, it should show up in the notification window just like any other update.

-Josh
