### ISSUE TITLE
AbstractCodeActionOrUserDiagnosticTest.TestMissingInRegularAndScriptAsync(...) forcibly sets ParseOptions to null

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#22181]
This helper looks like so:

```C#
protected async Task TestMissingInRegularAndScriptAsync(
    string initialMarkup,
    TestParameters parameters = default(TestParameters))
{
    await TestMissingAsync(initialMarkup, parameters.WithParseOptions(null));
    await TestMissingAsync(initialMarkup, parameters.WithParseOptions(GetScriptOptions()));
}
```

So, if it's used to test a code action which targets a C# 7.1 language feature, the parse options that the test would set on the `TestParameters` get thrown away. It looks like we need to refactor how parse options get passed into tests. `GetScriptOptions()` above should operate on the existing parse options, not create new parse options.

**Comment by CyrusNajmabadi** [comment]
Closing as this relates to the legacy test harness that we're moving away from anyways.
