### ISSUE TITLE
IOperation statement inserted when it is not needed

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#22208]
see this comment (https://github.com/dotnet/roslyn/pull/21857/files#r139825112)

basically, what is happening is that in some cases such as IVariableDeclarationStatement or ExpressionStatement, it gets inserted into IOperation tree when it is not actually needed.

we need to decide whether we want to get rid of it or add it for all cases.

**Comment by mavasani** [comment]
Just to add some more context. For loop initializers are represented as `SeparatedSytnaxList<ExpressionSyntax` in syntax, but the C# binder converts it into list of bound ExpressionStatements (see [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Binder/Binder_Statements.cs,8ae9da7738784dd5,references).

I agree with @AlekseyTs that we should be consistent in the IOperation tree representation of for loop declaration part and initializers: either all of them should be statements (IVariableDeclarationStatements and IExpressionStatements) OR all of them should be non-statements (IVariableDeclaration and IXXXExpression)

**Comment by heejaechang** [comment]
weird thing about those statements is that IOperation point to non statement syntax node when IOperation itself is a statement.

**Comment by mavasani** [comment]
Design time decision: add back variable declaration statement for loop declaration part and all other cases where more than one variable can be declared simultaneously.
