### ISSUE TITLE
Redesign how workspace kinds work

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#22215]
Having a single string as a workspace kind has limitations. Instead, if workspaces could have multiple kinds, such as "tags", one could export workspace services targeting tags, and not specific workspace kinds.

There should be an M:N relationship allowing all combination between workspace services and workspaces. Case in point: this service is only exported for 3 specific workspaces and if you're not one of them, this service won't get exported for you.

http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/DiagnosticAnalyzerService_IncrementalAnalyzer.cs,14

**Comment by Pilchie** [comment]
There should be an inheritance type relationship (at least, I thought that was the original design).  @DustinCampbell (or even @mattwar) - care to chime in?

**Comment by DustinCampbell** [comment]
There's no inheritance relationship. There are predefined [service layers](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Workspace/Host/Mef/ServiceLayer.cs), e.g. "Editor", "Host". Or, you can use a custom kind that will supersede the layers.

The ExportIncrementalAnalyzerProvider is kind of orthogonal to the workspace kind ask. This is a specialized attribute that shouldn't be quite so locked down. However, I guess that's why it's not public. :smile:

**Comment by KirillOsenkov** [comment]
I kind of like how CPS declares Capabilities - maybe we could use something like this here.

**Comment by DustinCampbell** [comment]
I haven't applied too much thought to the problem, but I'm not sure how to do that in a non-breaking way. Also, I'm not certain of the user scenario. The particular case pointed to here is something that needs fixing IMO, and it's kind of specific to those who have IVT access.

**Comment by KirillOsenkov** [comment]
Right. I'm sure that with some effort it'd be possible to come up with something that preserves existing workspace behavior by default, but also asks if the workspace supports "the new way" and if yes, do the new thing.

**Comment by mattwar** [comment]
The Workspace kind is only used by the workspace to match it up with kind specific services.  It's entirely possible (and easy to do) to expand to a list of kinds.  However, now you might need another heuristic to disambiguate between multiple services that match the workspace, which one do you pick?  Maybe the order they are specified in is the order of preference?

I also remember there were some features that were using the workspace kind to determine behavior, though that was not its original purpose.

**Comment by CyrusNajmabadi** [comment]
@KirillOsenkov Would def be great to have a well defined problem we have currently, and a suggestion on an improvement we could have for it.  Otherwise, i'm not sure this issue will go anywhere.

**Comment by KirillOsenkov** [comment]
We have bigger fish to try. I can reopen if this becomes an actual problem again.
