### ISSUE TITLE
dotnet_style_qualification_for_property has faulty heuristic

### ISSUE THREAD

**Issue by kentcb** [dotnet/roslyn#22212]
**Version Used**: 

VS Enterprise 2017 15.3.4

**Steps to Reproduce**:

1. Add `dotnet_style_qualification_for_property` to your .editorconfig with a value of `true:error`
2. Add an instance property called `Foo`
3. Add a statement to a static member that uses the `nameof` operator against `Foo`

**Expected Behavior**:

No error triggered.

**Actual Behavior**:

Error is triggered because `Foo` is not qualified with `this.`. However, qualifying with `this.` is itself an error because of the static context.

This is a common scenario when using bindable or dependency properties, since the field is declared statically and needs to pass in the name, which is often manifested as an instance property:
```C#
public static readonly BindableProperty FooProperty =
    BindableProperty.Create(
        nameof(Foo),    // this triggers the error, but the suggested fix is impossible
        ...);

public string Foo { ... }
```

Here is a repro: [EditorConfigRepro.zip](https://github.com/dotnet/roslyn/files/1316149/EditorConfigRepro.zip)

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  The usage in the nameof is not marked, while the usage outside of the nameof is:

![image](https://user-images.githubusercontent.com/4564579/217621771-6c055189-fd5a-4bca-8edf-4d0c5b0e2947.png)
