### ISSUE TITLE
VS crash when renaming a field

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#2222]
### Configuration

Visual Studio 2015 CTP 6
dotnet/corefx@0034710b8747ccc3a8ca1119bffc2eb926b77f8c
System.Collections.Immutable.sln

### Steps to reproduce

1. Locate [`ImmutableArray<T>.array`](https://github.com/dotnet/corefx/blob/0034710b8747ccc3a8ca1119bffc2eb926b77f8c/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray%601.cs#L49)
2. Press <kbd>F2</kbd> to rename the symbol
3. Type `A` (instead of `a`) for the first letter

### Expected result

The symbol is renamed.

### Actual result

Visual Studio crashes.

**Comment by dpoeschl** [comment]
@sharwell I can't get this to reproduce locally. The rename succeeds and all the existing Array.Copy invocations are updated to System.Array.Copy invocations (as expected), and the build succeeds with the new name.

Does this still fail for you? If so, can you grab a stack so I can try to figure out if it's a bug we've already fixed? Thanks!

**Comment by dpoeschl** [comment]
Please reopen this if you can repro or encounter the issue again. Thanks!
