### ISSUE TITLE
Bogus assert in EnsureIsReadOnlyAttributeExists 

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#22237]
I saw the assert once while trying to rename a "ref readonly" parameter in CoreFxLab solution.
The assert is ignorable and I could not reproduce it again. 

== Update: 
It seems it can also be cause by solution crawler. 

The assert is benign and seems bogus. 

The following code calls into the helper when attribute is already already known to be needed that bit is "frozen".

```cs
                if (parameter.RefKind == RefKind.RefReadOnly)
                {
                    // These parameters might not come from a compilation (example: lambdas evaluated in EE).
                    // During rewriting, lowering will take care of flagging the appropriate PEModuleBuilder instead.
                    parameter.DeclaringCompilation?.EnsureIsReadOnlyAttributeExists(diagnostics, parameter.GetNonNullSyntaxNode().Location, modifyCompilationForRefReadOnly);
                }
```

Either should not call, or should relax the assert to not be triggered when asking for something that we already asked before. 
I think we should do the latter. -relax the attribute

**Comment by OmarTawfik** [comment]
Actually, the Debug is true, and it indicates that we're trying to generate IsReadOnly attributes when it is too late, or too early. There is an underlying bug there. Looking into it.

**Comment by OmarTawfik** [comment]
Cannot repro still. Will reassign/triage if there is a repro in the future.

**Comment by jaredpar** [comment]
Closing as this hasn't repro'd since September.
