### ISSUE TITLE
Change Signature does not show "ref readonly" modifier on parameters

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#22239]
The Change Signature  shows  other modifiers like "out" but not "ref readonly" - not sure if it does not understand it or because it simply does not fit. There is no much space in that UI.

**Comment by OmarTawfik** [comment]
Root cause: classes in `src/Workspaces/CSharp/Portable/CodeGeneration` don't use compiler helpers to generate refness of signatures, but instead do independent checks. Need to look deeper into that.
