### ISSUE TITLE
preserve receiver even in error case where static method or event is called

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#22233]
see this (https://github.com/dotnet/roslyn/pull/21857#pullrequestreview-64104549) and this (https://github.com/dotnet/roslyn/pull/21857#pullrequestreview-64105067)

right now, when static call or event reference is off instance, we drop that info. people believe we should preserve that info.

**Comment by jinujoseph** [comment]
Error Scenario

**Comment by jinujoseph** [comment]
This should be fixed.
Can you  verify and close

**Comment by mavasani** [comment]
Verified fixed, for example http://source.roslyn.io/#Roslyn.Compilers.CSharp.Semantic.UnitTests/IOperation/IOperationTests_IInvocationOperation.cs,30
