### ISSUE TITLE
Replace lambda with local function loses "ref readonly"

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#22241]
```cs
        delegate ref readonly int D1(ref readonly int arg);

            D1 dd = (ref readonly int a) => ref a;
```

Replace dd with a local function using IDE. - loses "ref readonly"

**Comment by OmarTawfik** [comment]
Root cause: classes in `src/Workspaces/CSharp/Portable/CodeGeneration` don't use compiler helpers to generate refness of signatures, but instead do independent checks. Need to look deeper into that.
