### ISSUE TITLE
Add Accessibility modifier removes "ref" from a ref struct

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#22240]
Invoke Refactor/Add Accessibility modifiers on 

```cs
readonly unsafe ref struct S1 { }
```
The dialog offers adding "private", but also offers to remove "ref"

**Comment by OmarTawfik** [comment]
Root cause: classes in `src/Workspaces/CSharp/Portable/CodeGeneration` don't use compiler helpers to generate refness of signatures, but instead do independent checks. Need to look deeper into that.
