### ISSUE TITLE
Instance/static method compile error

### ISSUE THREAD

**Issue by karczk** [dotnet/roslyn#22249]
**Steps to Reproduce**:

```
    class Program
    {
        static void Main(string[] args)
        {
            var instance = new Test();
            string input = "abc";
            instance.IsValid(input); // <- HERE
        }
    }

    class Test
    {
        public static bool IsValid(string value)
        {
            return true;
        }

        public bool IsValid(object value)
        {
            return true;
        }
    }
```

**Expected Behavior**:
Should compile, there is only one instance method and string is an object.

**Actual Behavior**:
Does not compile: 

> Member 'ConsoleApplication.Test.IsValid(string)' cannot be accessed with an instance reference; qualify it with a type name instead

**Comment by dpoeschl** [comment]
This sounds more like a feature request for the language, since the error message is pretty clear that this is not expected to work. Feel free to port to https://github.com/dotnet/csharplang/issues if you'd like to propose a change to the language.

**Comment by jcouv** [comment]
Moving language design discussions to csharplang repo.

**Comment by jcouv** [comment]
Issue moved to [dotnet/csharplang #1190](https://github.com/dotnet/csharplang/issues/1190) via [**ZenHub**](https://www.zenhub.com/)
