### ISSUE TITLE
Auto Functions - Suggestion

### ISSUE THREAD

**Issue by MichaelPuckett2** [dotnet/roslyn#22256]
**7.1 suggested for 7.2 or later**: 

**Allow a function to auto declare and return a value.**:

**Existing format example:**

        public bool Navigate(Type sourcePageType)
        {
            var success = false;
            if (Application.Current is INavigate navigator)
            {
                success = navigator.Navigate(sourcePageType);

                if (success)
                    CurrentPage = sourcePageType;
            }
            return success;
        }

**Suggested format example:**

        public bool Navigate(Type sourcePageType) as success
        {
            if (Application.Current is INavigate navigator)
            {
                success = navigator.Navigate(sourcePageType);

                if (success)
                    CurrentPage = sourcePageType;
            }
        }

In the suggested format the function automatically initializes a value for success and will automatically return that value whenever return is called.  In this method you can avoid declaring the variable and returning it when we know this will be the behavior anyway.  Thoughts?

**Comment by dpoeschl** [comment]
Hi @MichaelPuckett2, this feature request would probably make more sense over on https://github.com/dotnet/csharplang/issues

**Comment by jcouv** [comment]
Moving the issue to csharplang.

**Comment by jcouv** [comment]
Issue moved to [dotnet/csharplang #1023](https://github.com/dotnet/csharplang/issues/1023) via [**ZenHub**](https://www.zenhub.com/)
