### ISSUE TITLE
Path names with spaces fail in build/scripts/obtain_dotnet.sh

### ISSUE THREAD

**Issue by benknoble** [dotnet/roslyn#22259]
**Version Used**: 
```
$ git describe
Visual-Studio-2017-Version-15.3-3100-gf827f7a88c
```

**Steps to Reproduce**:

1. Clone `roslyn` into a directory with spaces in the path (e.g. `/Volumes/G-DRIVE ev RaW SSD/Home/roslyn`)
2. Run `./build/scripts/obtain_dotnet.sh` to obtain dotnet-CLI in order to build roslyn

**Expected Behavior**:

The pathname is handled accordingly.

**Actual Behavior**:

```
$ ./build/scripts/obtain_dotnet.sh
./build/scripts/obtain_dotnet.sh: line 25: /Volumes/G-DRIVE: No such file or directory
```

**Possible Solution**

Line 25 reads:
```bash
    source ${THIS_DIR}/build-utils.sh
```

There are other lines, both in `obtain_dotnet.sh` and other `*.sh` files that contain *unquoted* variables. This is problematic, as the variables undergo word splitting and causes issues like the above. See e.g. [BashPitfalls](http://mywiki.wooledge.org/BashPitfalls#cd_.24.28dirname_.22.24f.22.29) for many discussions on this.

**Comment by benknoble** [comment]
N.B. I am happy to work on a fix/PR, but would like community input first.

**Comment by khyperia** [comment]
You are welcome to fix up the scripts to improve them and make them more resilient to issues like these, but [it is a known and widespread issue Roslyn doesn't support paths with spaces](https://github.com/dotnet/roslyn/issues/20929). (e.g. many tests improperly quote paths)

A full fix for this issue would be a very large change, and would need to incorporate infrastructure to validate we don't regress it.

**Comment by khyperia** [comment]
Also note that I am currently trying to clean up our Linux story - for example, [this PR](https://github.com/dotnet/roslyn/pull/22145) that tried to clean up `tests.sh` a bit. I plan on creating a bash style guide, similar to our [powershell style guide](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Powershell%20Guidelines.md). I would welcome feedback on that when I find the time to make it!

**Comment by jasonmalinowski** [comment]
@khyperia If we were spaces-in-paths clean we could easily have our CI system start checking out the stuff to validate in a path with spaces. Won't break then!

**Comment by jasonmalinowski** [comment]
But yeah, even though we have problems @benknoble PRs are definitely accepted to make things better.

**Comment by benknoble** [comment]
Hopefully I'll put something together over the weekend and get it out to y'all to review

**Comment by benknoble** [comment]
Do we have test coverage for a change covering something like this? It's possible I've been overzealous and quoted something that shouldn't have been quoted, and would like to know if I'm breaking something.

**Comment by benknoble** [comment]
Currently I'm now having this problem
```bash
$ ./build/scripts/obtain_dotnet.sh 
Downloading and installing .NET CLI version 2.0.0-preview3-006923 to /Volumes/G-DRIVE ev RaW SSD/Home/roslyn/build/scripts/../../Binaries/dotnet-cli
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23479  100 23479    0     0  12006      0  0:00:01  0:00:01 --:--:-- 12003
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview3-006923/dotnet-sdk-2.0.0-preview3-006923-osx-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview3-006923/dotnet-sdk-2.0.0-preview3-006923-osx-x64.tar.gz
mkdir: /Volumes/G-DRIVE/additionalDeps/Microsoft.AspNetCore.ApplicationInsights.HostingStartup/shared/Microsoft.NETCore.App: Permission denied
```

Since the `pwd = /Volumes/G-DRIVE ev RaW SSD/Home/roslyn`, something in the download/installer now fails with spaces and tries to create `/Volumes/G-Drive/...` which doesn't make sense.

**Comment by khyperia** [comment]
> Do we have test coverage for a change covering something like this?

We have no validation that the build works on a path with spaces, but we do have validation that the build works in a path without spaces :) - so if CI passes, you likely didn't break anything.

> something in the download/installer now fails with spaces

Unfortunately, that script is not owned by Roslyn. I believe the script referenced by `https://dot.net/v1/dotnet-install.sh` is [this script](https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.sh) in the `dotnet/cli` repo. If you submit a PR over in that repo, hopefully things will get resolved over here! :)
