### ISSUE TITLE
Explicit tuple name simplification not offered

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#22254]
```C#
int a = 1; 
var t = (a: a, 2);
```
There's no lightbulb offering to remove the explicit tuple name. It does show up for anonymous types though...

**Comment by rchande** [comment]
cc @jcouv

**Comment by rchande** [comment]
![image](https://user-images.githubusercontent.com/3751401/30707673-2054be3e-9eb1-11e7-881c-1b21236cdcdb.png)
anon gets faded but the tuple doesn't

**Comment by dpoeschl** [comment]
Your language version needs to be set to 7.1 to see this feature. Can you double check that and report back? Thanks!

**Comment by rchande** [comment]
Works with lang version set to 7.1
