### ISSUE TITLE
CodeBlock and OperationBlock analysis contexts should expose all owning symbols

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22252]
VB allows field declarations to share same initializer, which means that a code block/operation block can have multiple owning symbols. We currently expose a single owning symbol, but we should allow analyzers to get all owning symbols for a block contenxt. This functionality would be needed by an existing Roslyn analyzer if we implement https://github.com/dotnet/roslyn/issues/21293 and remove the `ISymbolInitializer` APIs

**Comment by mavasani** [comment]
@jinujoseph I am proposing Won't Fixing this issue given we have decided to retain the IFieldInitializer API. The only case where we can have multiple symbols own same code block is VB field initializers sharing the As New clause, and the analyzer can register for OperationKind.FieldInitializer to register them.

**Comment by jinujoseph** [comment]
makes sense
