### ISSUE TITLE
UTF8-no-BOM causes diff window to display erroneous encoding warning

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#22262]
VS 15.3.5, iirc started in VS15.3.0

It happens with both Git and TFVC so it seems to be related to the diff tool itself.
It's not specific to .editorconfig, though `charset = utf-8` certainly exacerbates the existing problem.

Repro:

1. Save a file as UTF8 without BOM and commit to source control.
2. Make a change to the file and resave.
3. View the diff.

It erroneously shows this message at the top:

> These files have different encodings. Left file: Western European (Windows). Right File: Unicode (UTF-8) without signature. You can resolve the difference by saving the right file with the encoding Western European (Windows).

![image](https://user-images.githubusercontent.com/8040367/30716259-65e98ef8-9ee7-11e7-9c07-f0725559ac4f.png)

**Comment by jnm2** [comment]
Let me test it with Git to see if it's TFS-specific.

**Comment by jnm2** [comment]
It happens with Git and also it's not specific to editorconfig, though `charset = utf-8` certainly exacerbates the existing problem.

**Comment by jnm2** [comment]
I also suspect an issue that would be specific to .editorconfig where I'm debugging into opening a new tab and the source doesn't match the original, seemingly at random. In this codebase there are a good number of files that aren't yet utf8-no-bom. I'll have to see if that's reproducible.

**Comment by dpoeschl** [comment]
Hi @jnm2, this sounds like a VS problem, not a Roslyn problem. Do you think Roslyn is getting involved in this somehow? If not, please use the Report a Problem mechanism in VS (upper right corner) so we can get this routed to the correct team. Thanks! Optimistically closing this one, but let me know if you'd like it reopened.

**Comment by jnm2** [comment]
@dpoeschl I thought it was an editorconfig thing at first, but you're right; it wouldn't be Roslyn. Thanks!

**Comment by jnm2** [comment]
Moved to https://developercommunity.visualstudio.com/content/problem/123895.
