### ISSUE TITLE
[Question] How to use EditorFeatures code in my own C# text editor?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#22260]
Hi! I'm building my own text editor app in C#, which I plan to eventually make a C# IDE. I want it to have a rich feature set for manipulating/refactorings for C#, but I don't want to reinvent the wheel. I see that there are lots of such refactorings already implemented at [`src/EditorFeatures/CSharp`](https://github.com/dotnet/roslyn/tree/master/src/EditorFeatures/CSharp). How do I adapt the code in that directory to my editor? (I assume the stuff in there is programmed against interfaces and there's nothing VS-specific in there, correct? So is it possible to just implement a bunch of interfaces and have it work for my editor?)

**Comment by DustinCampbell** [comment]
@jamesqo: The editor features layer takes a dependency on the Visual Studio text buffer and editor APIs.

**Comment by CyrusNajmabadi** [comment]
This is out of scope for the roslyn project.  Effectively, it's all open source, and can be adopted if you want.  But it's basically not somethign we have any investment in making easy.  Our move to LSP though may help out here in the future.
