### ISSUE TITLE
Should we offer a fixer to change "readonly ref" to "ref readonly"?

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#22267]

**Comment by alrz** [comment]
isn't it a (potentially) different thing? in that case, suggesting to "fix" it makes less sense.

**Comment by jcouv** [comment]
At this point `readonly ref` isn't used. Until it does, a fix makes sense.

**Comment by jcouv** [comment]
Based on latest LDM decision, this is no longer relevant. Closing
