### ISSUE TITLE
WorkCoordinator.Reanalyze should avoid duplicate scheduling

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#22274]
**Version Used**: 15.3

:memo: Observed 18,000 scheduled operations during analysis of a heap dump provided for a "low memory" condition. The `HashSet<DiagnosticId>` instances required to queue the requested analysis operations accounted for nearly 1GiB of memory overhead.

`WorkCoordinator.Reanalyze` schedules analysis operations on sets of documents:

https://github.com/dotnet/roslyn/blob/c83a39086d062ae46e4eb333970b0cf59feba1a2/src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.cs#L166-L170

These analysis operations may take time. To avoid unnecessary memory overhead, operations should not be scheduled for a `DocumentId` when another scheduled operation will already update that document.

**Comment by heejaechang** [comment]
thank you. wondering who is asking to re-analyze that many documents...

**Comment by sharwell** [comment]
> wondering who is asking to re-analyze that many documents...

It appears that ~120 documents were open in the editor at the time. When you change tabs, it requests a new analysis of all open documents.

**Comment by heejaechang** [comment]
@sharwell hmmm changing tabs shouldn't re-request. and re-analyze is not something such action would cause it. some external outside of solution crawler must explicitly ask for re-analysis.

**Comment by heejaechang** [comment]
so build can cause re-analyze all open files it looks like.

**Comment by sharwell** [comment]
> so build can cause re-analyze all open files it looks like.

Does LUT trigger this path after edits?

**Comment by heejaechang** [comment]
I dont think so. enc also can cause it for all documents that contains rude edits.

**Comment by sharwell** [comment]
Let me know if there's anything in the heap you want me to look for specifically.

**Comment by sharwell** [comment]
:memo: Lowering the priority of this issue since the problematic user of `Reanalyze` (TypeScript) fixed the acute problem on their side for the 15.4 release.

**Comment by CyrusNajmabadi** [comment]
Unlikely to do anything here.  We're getting rid of that subsystem entirely.
