### ISSUE TITLE
'is' keyword can be converted to "see langword" tag when it is already part of a "see langword" tag 

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#22278]
**Version Used**: 
VSUML 26920.4001
**Steps to Reproduce**:
1.  Create a new VB console app
2. At the start of the file, above module, add summary comments. Inside them add the text: "test 1 is"
3. Select 'is' in the comment, open up quick actions and choose "`Use <see langword= "is"/>`
4. Select is from inside the resulting see tag, and open up quick actions again. As you can see you can make a second tag inside the first tag.
**Expected Behavior**:
Either 'is' shouldn't be selectable at all for this action as 'is' isn't present elsewhere in the code file, or 'is' shouldn't be selectable when it is already in the tag.
**Actual Behavior**:
You're able to make a second `<see langword="is"/>` inside the first.
![image](https://user-images.githubusercontent.com/10537189/30723099-e3e433c4-9ee9-11e7-8cdb-767b7bd1722c.png)

**Comment by mattscheffer** [comment]
@rchande

**Comment by rchande** [comment]
Great find, @mattscheffer

**Comment by chborl** [comment]
@dpoeschl @kuhlenh , one fix would be to not offer the refactoring when already inside an XML tag.  But should we go further and not offer the refactoring when typing a common word anywhere in doc comments, such as is, as, for, of, not, etc...

**Comment by dpoeschl** [comment]
It looks like maybe at one point the language services would translate keywords between languages depending on what language you were viewing from: https://stackoverflow.com/questions/693196/how-do-i-reference-a-c-sharp-keyword-in-xml-documentation#comment506691_693227 -- I have not verified this on a pre-Roslyn VS.

Regardless, I would be for switching to an include-list of keywords where we think people are likely to actually want langword instead. "is" and "as" would not make that list for me, along with some others (we'd have to go through all the keywords and pick out the likely useful ones). This is especially important as the refactoring will trigger a lightbulb when your caret is there, making you think there's something to fix when you were just typing normal English.

**Comment by sharwell** [comment]
@dpoeschl In 9e7db74acb14cca35580760d685b309b5b64d62a I restricted the completion lists to only show a subset of keywords.

**Comment by chborl** [comment]
Thanks @sharwell!  I will use the same keywords that you use.
