### ISSUE TITLE
Microsoft.CodeAnalysis.Editor.UnitTests.Structure.StructureTaggerTests.CSharpOutliningTagger_RegionIsNotDefinition seems to be flakey

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#22277]
It was seen failing windows_debug_unit32_prtest in https://github.com/dotnet/roslyn/pull/22275 , which could not possibly cause this kind of failure.

**Comment by CyrusNajmabadi** [comment]
closing out.  all these tests have been running fine for ages without any skips.
