### ISSUE TITLE
Add file banner doesn't work cross-language

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#22280]
**Version Used**: 
Vsuml 26920.4001

The new feature add file banner doesn't allow you to use 'add file banner' for files of a different language than the original project.
**Steps to Reproduce**:
1. Create a new VB console app.
2. Add 2 CSharp class files, and add appropriate references/packages to compile them
3. Add a comment at the top of one of the CSharp class files like //test
4. Go to the second CSharp class file and attempt to activate quick actions.

**Expected Behavior**:
The quick action should be present to 'add file banner' from the first comment.
**Actual Behavior**:
The option is missing.

It still works for vb if you add a second vb file and attempt the same thing.

Also, I don't know if this feature is planned or supposed to work, but it would be cool to allow you to add file banner across languages with conversions. So a comment " 'test1 " from a vb file could be added/converted to a CSharp one as //test1

**Comment by mattscheffer** [comment]
@rchande

**Comment by dpoeschl** [comment]
I'm not sure if this is a bug or a feature request. I feel like having it work cross-project at all might be iffy, because maybe not all projects have/want the same header.

**Comment by dpoeschl** [comment]
@kuhlenh What do you think the behavior should be here?

**Comment by sharwell** [comment]
:memo: This feature only looks at files in the same directory as the file you are adding the header to.

**Comment by kuhlenh** [comment]
@dpoeschl seems to me like it should be within the same directory. Though, if customers come back and say that they have the same file banner across directories, we can work to change this.

**Comment by CyrusNajmabadi** [comment]
> This feature only looks at files in the same directory as the file you are adding the header to.

Wait, that doesn't seem right to me.  I thought i wrote it so that it would look at any file within your same project.  It doesn't look across projects... but i think that's not too big a deal.  The primary use case is you have an existing project with existing copyrights, and you want to be able to add those to new files easily.

**Comment by CyrusNajmabadi** [comment]
>  I feel like having it work cross-project at all might be iffy, because maybe not all projects have/want the same header.

I agree.  I think it's fine that the user has to have at least one existing file in a project that has a copyright header to drive the decision off of.

**Comment by CyrusNajmabadi** [comment]
CLosing out.  The use case here is marginal, and will be subsumed by teh work @sharwell is doing to allow header-text to be specified in an .editorconfig file.
