### ISSUE TITLE
ArgumentOutOfRangeException in CompletionService.GetCompletionsAsync

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#22289]
**Version Used**: 
2.3.2

**Steps to Reproduce**:
Unfortunately I don't know how to isolate this. This is something I see in logs of my Roslyn-based project, and I wasn't able to reproduce it locally (however I consistently see it in logs).

I hope you might be able to guess something from the stack trace, or suggest a way to get more information about this.

Stack trace (cleaned up from Application Insights):
```
System.AggregateException: One or more errors occurred.
Microsoft.CodeAnalysis.DocumentState+<GetSyntaxTreeAsync>d__41.MoveNext
Microsoft.CodeAnalysis.CSharp.Completion.Providers.AttributeNamedParameterCompletionProvider+<ProvideCompletionsAsync>d__5.MoveNext
Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders+<GetContextAsync>d__31.MoveNext
Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders+<ComputeNonEmptyCompletionContextsAsync>d__24.MoveNext
Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders+<GetCompletionsAsync>d__22.MoveNext

System.AggregateException: One or more errors occurred.
Microsoft.CodeAnalysis.DocumentState+<IncrementallyParseTreeAsync>d__15.MoveNext

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
 Parameter name: start
Microsoft.CodeAnalysis.Text.TextSpan..ctor
Microsoft.CodeAnalysis.Text.ChangedText.Merge
Microsoft.CodeAnalysis.Text.ChangedText.Merge
Microsoft.CodeAnalysis.Text.ChangedText.GetChangeRanges
Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChangedText
Microsoft.CodeAnalysis.DocumentState.IncrementallyParse
Microsoft.CodeAnalysis.DocumentState+<IncrementallyParseTreeAsync>d__15.MoveNext
```

**Expected Behavior**:
There are no exceptions from `CompletionService`.

**Comment by dpoeschl** [comment]
@ashmind Thanks for the report. What's the actual behavioral effect this is having on your project? Is something crashing? Is completion just not returning the right thing?

**Comment by ashmind** [comment]
@dpoeschl  The exception is propagated out of `GetCompletionsAsync` -- I cut off my code from the stack trace, but it goes up to the top-level exception handler. Unfortunately the way Application Insights log it is a bit confusing, but my understanding is that user gets an error instead of completion (unless I handle it).

**Comment by dpoeschl** [comment]
@rchande Any clues what might be going wrong here in the attribute completion code?

**Comment by rchande** [comment]
@ashmind From the inner exception you posted it looks like something's going wrong in your Workspace that's preventing incremental parsing from working. If you can provide one, a dump would be helpful in figuring out what's happening.

**Comment by rchande** [comment]
I don't think this is specific to Attribute name completion. Rather, it is the first provider that runs, and it starts by attempting to get an up-to-date SyntaxTree for the document .http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/Completion/CSharpCompletionService.cs,28

**Comment by ashmind** [comment]
@rchande Is there a method to dump the `Workspace` state, or do you mean full process dump?

**Comment by rchande** [comment]
@ashmind @jasonmalinowski has a tool that can extract workspace state from Visual Studio. I'm not sure if any components therein can be repurposed for use in other hosts. A full process dump would be ideal, yes.

**Comment by jasonmalinowski** [comment]
Yeah, the tool I have isn't really suitable for this. I think we have some other WinDBG extensions that _might_ help? But yes, process dump is what we'd need. 😦

**Comment by ashmind** [comment]
@jasonmalinowski Thanks -- I'll try to implement that (interesting challenge given it's Azure Web App) and let you know. Is it OK if the exception handler triggering the dump wouldn't be first-chance Roslyn one?

**Comment by jasonmalinowski** [comment]
@ashmind First chance is always better -- you can use exception filters to sometimes pull that off. I'm also not sure if Azure Web App stuff has some dumping support that might do that too? I admit I've lost track of all the diagnostic support we have there today. :smile:

**Comment by ashmind** [comment]
@jasonmalinowski I think I managed to reproduce this on local -- got a memdump. How should I send you the link to it? (uploaded to mega.nz) Don't want to post memory dumps in public, just in case.

**Comment by jasonmalinowski** [comment]
@ashmind Email me a link. My work email is listed in my GitHub profile.

**Comment by ashmind** [comment]
@jasonmalinowski Thanks, sent.

**Comment by jasonmalinowski** [comment]
@ashmind Got it, thanks. Will try to look today or tomorrow.

**Comment by jasonmalinowski** [comment]
@ashmind Ah, so yeah, so there's some bug in our GetTextChanges function between two snapshots of changed text:

```
            var startingText = SourceText.From(new string('a', 1000));
            var endingText = startingText.WithChanges(new TextChange(new TextSpan(36, 710), ""))
                                         .WithChanges(new TextChange(new TextSpan(36, 36), "bc"))
                                         .WithChanges(new TextChange(new TextSpan(38, 38), "defg"));

            var diff = endingText.GetTextChanges(startingText);
```

...is an isolated repo. @dpoeschl looks like you can 'enjoy' some really gnarly span manipulation code from here.

**Comment by RikkiGibson** [comment]
is this possibly related to #26305?
