### ISSUE TITLE
Get warning after update all dependencies for package Microsoft.CodeAnalysis on Visual Studio 2017

### ISSUE THREAD

**Issue by liushuanggang** [dotnet/roslyn#22290]
**Version Used**: 
Visual Studio version 2017 15.3.5  &  Package Microsoft.CodeAnalysis version 2.3.2
**Steps to Reproduce**:

1. Create a new Windows Forms project (Target framework .net 4.6.1).
2. Install the package Microsoft.CodeAnalysis version 2.3.2.
3. After installation complete, switch to Updates tab on NuGet Package Manager UI, then select all packages that need to be upgraded.  (Select all packages->update)
4. This issue only occurred on Visual studio 2017, not on Visual Studio 2015.

**Expected Behavior**:
All packages should updated without any error.
**Actual Behavior**:
There are two warning in the error list:
The referenced component 'System.ValueTuple' could not be found.
The referenced component 'System.Security.Cryptography.X509Certificates' could not be found.
![5544](https://user-images.githubusercontent.com/18026611/30743154-0ee387d8-9fcf-11e7-9ab1-0d24fb80db99.png)
![5566](https://user-images.githubusercontent.com/18026611/30743155-0ef659f8-9fcf-11e7-98ab-ad25782f6731.png)

**Comment by vlavrnic** [comment]
After repeating steps from answer to Stackoverflow [question](https://stackoverflow.com/questions/46349993/visual-studio-2017-communnity-incorrectly-updates-roslyn-scripting) I may confirm that if we update these two packages first and than the rest, there is no yellow triangles in reference list. However, after cleaning and rebuilding solution a number of warnings appears (see attached text file) in Error and Output windows.
[Github - 22290 - Warning list.txt](https://github.com/dotnet/roslyn/files/1326188/Github.-.22290.-.Warning.list.txt)

**Comment by vlavrnic** [comment]
Here (see attached file)
[Github - 22290 - Error 01.txt](https://github.com/dotnet/roslyn/files/1326245/Github.-.22290.-.Error.01.txt)
is possible example of impact of removing _assemblyBinding._ This occurs during script execution with application produced with VS 2017. Same application produced with VS 2015 works correctly.

**Comment by vlavrnic** [comment]
After testing with more complex solution built with VS 2017 that is using scripting I did not have any problems. However, we should have in mind that this is basic testing only.

**Comment by vlavrnic** [comment]
It seems that this workaround, at the end, does not work. After couple of days not working on a solution, warning messages reappear again. Biggest change was update of _Azure Functions and Web Jobs Tools_. What is interesting is the fact that not all projects (that are using scripting) within solution are affected. Clean and rebuild and later using application does not produce any error but, I am not using assemblies with warning anyway.

**Comment by CyrusNajmabadi** [comment]
Closing out given lack of feedback on this  issue from community.
