### ISSUE TITLE
GetOperation returns null for CatchFilterClauseSyntax and FinallyClauseSyntax

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22299]
See unit tests `TryCatch_GetOperationForCatchFilterClause` and `TryCatch_GetOperationForFinallyClause` added in https://github.com/dotnet/roslyn/pull/22210

It seems the operation tree has nodes mapping to the underlying expression of the CatchFilterClauseSyntax  and block of the FinallyClauseSyntax, but I would except these two syntax nodes also to map the underlying catch filter expression and finally block respectively.

**Comment by mavasani** [comment]
This also seems to be true in VB for identifier name in catch declaration. See test `Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.IOperationTests.TryCatch_GetOperationForCatchExceptionDeclaration` added in #22210

**Comment by bkoelman** [comment]
Possibly related to #27208
