### ISSUE TITLE
Allow taking an unmanaged pointer off readonly lvalues

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#22306]
Historically we require that lvalue is writable before allowing taking a pointer.

That does not make a lot of sense. While there are ways to "cast away" readonliness, why is that even required before "casting away" most of the type system safeguards?

I think it is just an artifact of old implementation strategy that internally combined "lvalue" and "writeable". 
Now that these concepts are properly  separated, it makes sense to require that the target of "&" is an lvalue, but does not need to be writeable.

**Comment by VSadov** [comment]
I think this would be a cheap change - both technically and conceptually. It would also smooth some edges around use of readonly variables (i.e. ReadOnlySpan indexer and the like) and unsafe code.

If possible this would be beneficial in 15.5

**Comment by jcouv** [comment]
Assigning to Vlad, since he already has a fix.
