### ISSUE TITLE
Visual Studio 2017 (26430.16) Release T4 Scaffolding crashing on model

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/roslyn#22308]
**Version Used**: 

**Steps to Reproduce**:

1. Weird issue when trying to compile the following model

`
    public class basketheader

    {
        [Key]
        public int id { get; set; }

        public int orderId { get; set; }

        public string title { get; set; }

        public string description { get; set; }

        public string emailBasket { get; set; }

        public decimal basketTotal { get; set; }

        public int currency { get; set; }

 
        public bool isDeleted { get; set; }

        public bool isActive { get; set; }

        public DateTime createDated { get; set; }

        public bool isSaved { get; set; }

        public string notes { get; set; }

   
        public int basketSessionId { get; set; }

       

        public string EnteredBy { get; set; }

        public BasketStatus BasketStatusSetting { get; set; }
        public enum BasketStatus
        {
            Basket=0,
            Order = 1,
            Abandon=2,
            FailedPayment=3,
            Discarded=4

        }

    }`

**Expected Behavior**:
Should Complile and product an basket header list page using asp.net mvc .4.6.2
**Actual Behavior**:
Crashes produces the following report in event viewer

Faulting application name: devenv.exe, version: 15.0.26430.16, time stamp: 0x5968f055
Faulting module name: PresentationCore.ni.dll, version: 4.7.2102.0, time stamp: 0x5937170a
Exception code: 0xc0000005
Fault offset: 0x00245bdb
Faulting process id: 0xaf0
Faulting application start time: 0x01d33538be99ac24
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\PresentationCore\e455d647c69dde661983d913460fef16\PresentationCore.ni.dll
Report Id: a9a59056-e157-4f3c-a1b2-23a695355c2b
Faulting package full name: 
Faulting package-relative application ID: 

3 Also when I try to update my version of version studio options are not available to do so.

**Comment by davidbuckleyni** [comment]
![applicationframehost_2017-09-24_15-13-20](https://user-images.githubusercontent.com/5619229/30783450-ef9e6470-a13a-11e7-925d-ff27402210ef.png)
Dialog showing cant modify or update

**Comment by davidbuckleyni** [comment]
Also get this when i donwloaded the exe
![image](https://user-images.githubusercontent.com/5619229/30783493-b89edeae-a13b-11e7-92dc-bb3919e96c9b.png)

**Comment by davidbuckleyni** [comment]
[dd_client_20170924151736.log](https://github.com/dotnet/roslyn/files/1327374/dd_client_20170924151736.log)

Log file

**Comment by dpoeschl** [comment]
@davidbuckleyni Thanks for the report! I don't believe this is Roslyn-related. Can you please file your feedback through the "Report a Problem" mechanism in VS so it can get routed to the correct place internally? Thanks!
