### ISSUE TITLE
Should you be able to take readonly refs to literals?

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#22300]
For instance, `ref readonly int x = ref 42;`. This is currently prohibited. Should it be?

**Comment by agocke** [comment]
The answer from the most recent LDM (9/27) was "no".

**Comment by tannergooding** [comment]
@agocke, was the "no" in response to `Should you be able to take readonly refs to literals?` (the post title) or to `This is currently prohibited. Should it be?` (the question in the first comment)?

**Comment by agocke** [comment]
Response to the title. No readonly refs to literals. You'll have to declare a local, then declare a readonly ref to the local.
