### ISSUE TITLE
When merge window for v15.5 will close? (const parameters)

### ISSUE THREAD

**Issue by 4creators** [dotnet/roslyn#22304]
Couple of weeks ago decision has been taken to implement [Intel hardware intrinsics](). This feature spans several repos and during design review [@jaredpar indicated](https://github.com/dotnet/apireviews/blob/master/2017/08-15-Intel%20Intrinsics/README.md#c-language-feature-requiring-parameters-to-be-literals) that there is a possibility to provide compiler support for enforcing passing compile time constants to method invocations.

Many members of the community are interested in getting this feature released as soon as possible including me. Therefore I have started some preliminary work on implementation of C# const parameters language feature which currently consists of:

- [Language proposal](https://github.com/dotnet/csharplang/pull/886)
- [Prototype compiler implementation](https://github.com/dotnetrt/roslyn/tree/features/constparameters)

I understand that full implementation comprises many parts of the compiler and active participation of Roslyn team member in feature development and that there is a requirement for LDM approval of feature design as a prerequisite to starting actual feature implementation.

My question is if there is any chance to get feature shipped in v15.5 of Visual Studio taking into account all above limitations?

**Comment by sharwell** [comment]
Is there a reason this cannot be implemented as an analyzer? It seems the current analyzer APIs would allow an implementation without even waiting for 15.5.

**Comment by jcouv** [comment]
@4creators For the compiler, we're focused on fixing bugs and polishing 15.5 features. So, no, we will not accept or work on a new feature at this stage in 15.5.
The next window is C# 7.3, which should be Visual Studio 2017 version 15.8 (subject to changes).

I see that you wrote up a language feature proposal (thanks!). I don't recall this being discussed in LDM. I'm tagging this issue for LDM discussion.
That said, I like Sam's alternative (using an analyzer). That may be more appropriate for the scenario.
 
FYI @gafter

**Comment by 4creators** [comment]
@jcouv @sharwell  Thanks for information. It makes me less worry about time frame for implementing any of the chosen solution for the const feature as C# 7.3 as I understand is at least a couple months away.

**Comment by jcouv** [comment]
@4creators This ("const parameters") was discussed briefly in a recent LDM and the conclusion is it feels fine to address with analyzers.
I'll go ahead and close the issue. Thanks
