### ISSUE TITLE
On projects which use .net 4.6 with the roslyn compiler

### ISSUE THREAD

**Issue by akash3456** [dotnet/roslyn#22313]
Is there a specific setting that is needed when compiling .net 4.6 projects when deploying them as an msi. 

it seems by default the roslyn folder is missing when deployment has begun. across both web and console. ?

**Comment by dpoeschl** [comment]
Not sure where to route this. Giving to the compilers team as a first step.

**Comment by jcouv** [comment]
@akash3456 I didn't understand the question.

What roslyn folder do you expect and at what path? Are you getting some error message?
If you have a simple project to reproduce the issue, could you make a zip file and share it?

**Comment by jcouv** [comment]
I just saw a thread that may be related to your issue. Take a look in case that answers your question.
https://github.com/dotnet/roslyn/issues/21627

**Comment by jcouv** [comment]
I didn't hear back on requested clarifications. I'll go ahead and close the issue. Thanks
