### ISSUE TITLE
IOperation Rebaselining tool has been silently removing the BOM from test source files

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#22319]
In Roslyn, our files start with the UTF8 BOM.  The IOperation Rebaselining tool has been silently removing it from the files that it touches.

See: https://github.com/dotnet/roslyn/pull/22263#discussion_r140848226

Since we don't know which files have had their BOM stripped, the effected files need to be found and fixed.

**Comment by TyOverby** [comment]
CC @mavasani @khyperia @dotnet/roslyn-compiler

**Comment by mavasani** [comment]
FYI - this is a test only issue. @333fred easy way to fix all test files which have any IOperation unit test?

**Comment by sharwell** [comment]
I used a script as described in #20541 to convert everything initially.

**Comment by khyperia** [comment]
https://github.com/khyperia/roslyn/commit/9fe9c17e7ed5704fa4535af0f804f93134d65b29

I can submit a PR with this if wanted.

Command was `find . -type f \( -name '*.cs' -o -name '*.vb' \) -print0 | xargs -0 sed -i '1s/^\(\xef\xbb\xbf\)\?/\xef\xbb\xbf/'`

**Comment by 333fred** [comment]
Fixed by #22323. Thanks @khyperia!
