### ISSUE TITLE
Allow modifiers on types in any order (partial, ref, readonly)

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#22322]
From LDM discussion today, this is something we could do after 7.2.

FYI @gafter @VSadov @OmarTawfik

**Comment by gafter** [comment]
I think this belongs in `csharplang`.

**Comment by jcouv** [comment]
I opened this as a compiler issue because LDM made that decision yesterday (we're ok proceeding with compiler work).

**Comment by jcouv** [comment]
Ok, filed https://github.com/dotnet/csharplang/issues/949
Closing this
