### ISSUE TITLE
IDE0016 Null check can be simplified, suggested fix changes order of operations

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22325]
From https://developercommunity.visualstudio.com/content/problem/118012/ide0016-null-check-can-be-simplified-suggested-fix.html

![image](https://user-images.githubusercontent.com/235241/30828103-581f6c18-a1f1-11e7-9114-498a0dd089ba.png)

The refactoring turns the top code into the bottom code, causing `DoSomething` to be called when it wouldn't have been called normally.

**Comment by dpoeschl** [comment]
Note also that you can disable this analyzer by changing the setting at Tools | Options | Text Editor | C# | Code Style | General | 'null' checking: | Prefer throw-expression. You can set the severity to "None" or change the Preference to "No."

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback on this.
