### ISSUE TITLE
String interpolation and ?: operator

### ISSUE THREAD

**Issue by aL3891** [dotnet/roslyn#2233]
Hello :)
In Vs2015 Ctp6 i'm trying to do have a ?: expression inside a interpolated string like this:

    var test = $"{true ? 1 : 2}";

But i get:

    Program.cs(17,36,17,36): error CS1003: Syntax error, ':' expected
    Program.cs(17,36,17,36): error CS1733: Expected expression

Is that not supported it is it a bug? i tried to find similar issues but i only found one related to dynamic so i'm not sure that applies to this

**Comment by MrJul** [comment]
`:` is used as a format separator, like in `String.Format`.

You need explicit parenthesis:
```
var test = $"{(true ? 1 : 2)}";
```

**Comment by aL3891** [comment]
Aah i see.. Great, thanks!
