### ISSUE TITLE
Incorrect completion when adding an argument to an async lambda

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#22343]
**Version Used**: 15.4 Preview 2

**Steps to Reproduce**:

1. Start with the following local variable declaration:

    ```csharp
    Func<object, Task> operationAsync =
        async obj =>
        {
        };
    ```

1. After `object`, type `, CancellationToken` to add a second parameter to the delegate
2. Before `obj`, type `(`
3. After `obj`, type `, ct)`

**Expected Behavior**:

```csharp
Func<object, CancellationToken, Task> operationAsync =
    async (obj, ct) =>
    {
    };
```

**Actual Behavior**:

```csharp
Func<object, CancellationToken, Task> operationAsync =
    async (obj, ctor) =>
    {
    };
```

:memo: `ctor` is added via a snippet expansion.

**Comment by dpoeschl** [comment]
No builder when the lambda is async and the close parenthesis is missing.

**Comment by CyrusNajmabadi** [comment]
Not repro for me.  I get a builder as expected:

![image](https://user-images.githubusercontent.com/4564579/217622186-15c1ed67-4583-4c2f-9700-3b238280ccea.png)
