### ISSUE TITLE
Proposal: create analyzer+fixer for nameof() usage

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#2235]
@pharring suggested to create an analyzer+fixer for #2179.

To me this sounds like an interesting challenge. So I have been thinking how that would work.

One approach is that the analyzer scans all method bodies, flagging all cases where a string literal equals the name of one of the method's parameters.
Aside from maybe expensive to run, it would potentially flag cases it should not, such as:

    public void SetAddress(string address)
    {
        label1.Text = "address"; // WARN: use nameof()
        textBox1.Text = address;
    }

Another approach could be to scan all method bodies for ctor calls to ArgumentException, ArgumentNullException and a few more, like I manually did for #2179. This would benefit the Roslyn codebase, but many codebases that I've seen have helpers such as:

    public static class Guard
    {
        public static void AssertNotNull<T>(string paramName, T paramValue)
        {
            if (paramValue == null)
            {
                throw new ArgumentNullException(paramName);
            }
        }
    }

and in that case, users will not profit from such an analyzer. Maybe they expect it to flag all calls into Guard.ArgumentNotNull(...), which it would not.

Personally I like @jskeet's solution, but it is only helpful when using Resharper's InvokerParameterName annotation:

https://github.com/nodatime/nodatime/search?utf8=%E2%9C%93&q=invokerparametername

For those unfamiliar, [InvokerParameterName] is telling ReSharper that the paramName argument is the name of one of the parameters from the calling (invoking) method, so it will provide code completion that lists all the calling method parameters. This will give a warning in ReSharper if the name is not a parameter, for example, a local variable name.

I'm open to suggestions. Any thoughts what would be feasible for such an analyzer that lives in the Roslyn codebase?

**Comment by AdamSpeight2008** [comment]
The issue I'm also notice when I go the VB.net source to utilise `NameOf` (#2132 , #1879) is the string literal is different to the variable's identifier. Like they renamed the variable, but forgotten to change the contents of the string literal. *Which we've all done at sometime in our coding history. *

**Comment by pharring** [comment]
Well, that's the main reason for nameof in the first place - turning the manual rename into a compiler error.

The analyzer part is easy, but the fixer needs to be designed with care because can never be 100% certain that nameof is a safe replacement. I think, in the case of ArgumentException or ArgumentOutOfRangeException (etc.), then we can be fairly certain that using nameof would be a suitable fix. But elsewhere, there's room for doubt. Certainly an attribute like [InvokerParameterName] would help.

**Comment by Pilchie** [comment]
See also https://github.com/DustinCampbell/CSharpEssentials

**Comment by Pilchie** [comment]
tag @DustinCampbell

**Comment by tmeschter** [comment]
Simply checking if the string literal is passed to a parameter named "paramName" would go a long way without requiring an `[InvokerParameterName]` attribute.

**Comment by DustinCampbell** [comment]
That's just what the analyzer in C# Essentials does. I put it up on the VS Gallery just yesterday.

**Comment by biqas** [comment]
@bartkoelman 

"in that case, users will not profit from such an analyzer"

```csharp
public static class Guard
{
    public static void AssertNotNull<T>(string paramName, T paramValue)
    {
        if (paramValue == null)
        {
            throw new ArgumentNullException(paramName);
        }
    }
}
```

If you analyse the data-flow of the parameter name and make a bottom-up analyse of method invocation you can detect it with the Roslyn analyzer.

**Comment by bkoelman** [comment]
Thanks all for your comments. Below my first attempt, based on `UseNameOfAnalyzer` from @DustinCampbell. 

This version reports only on `*ArgumentException` ctor calls, not matching names in general. If the argument is an identifier instead of a string literal, it tries to find callers, in order to support the `Guard.ArgumentNotNull(...)` scenario.

I also wrote some single-file tests (excluded here) which succeed. However when the callers are spread over multiple files it does not work. See TODO below. I recall reading something about method-body-analyzers not being allowed to report diagnostics in other methods, but I'm not sure.

Also I would appreciate feedback on my approach in general. Suggestions are very welcome.
 

    using System.Collections.Generic;
    using System.Collections.Immutable;
    using System.Linq;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp;
    using Microsoft.CodeAnalysis.CSharp.Syntax;
    using Microsoft.CodeAnalysis.Diagnostics;
    using CSharpEssentials;

    namespace StringParamName
    {
        [DiagnosticAnalyzer(LanguageNames.CSharp)]
        public class StringParamNameAnalyzer : DiagnosticAnalyzer
        {
            public const string DiagnosticId = "StringParamName";

            // You can change these strings in the Resources.resx file. If you do not want your 
            // analyzer to be localize-able, you can use regular strings for Title and MessageFormat.
            internal static readonly LocalizableString Title = new LocalizableResourceString(
                nameof(Resources.AnalyzerTitle), Resources.ResourceManager, typeof(Resources));
            internal static readonly LocalizableString MessageFormat = new LocalizableResourceString(
                nameof(Resources.AnalyzerMessageFormat), Resources.ResourceManager, typeof(Resources));
            internal static readonly LocalizableString Description = new LocalizableResourceString(
                nameof(Resources.AnalyzerDescription), Resources.ResourceManager, typeof(Resources));
            internal const string Category = "Naming";

            internal static DiagnosticDescriptor Rule = new DiagnosticDescriptor(DiagnosticId, 
                Title, MessageFormat, Category, DiagnosticSeverity.Warning, isEnabledByDefault: true);

            public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
            {
                get { return ImmutableArray.Create(Rule); }
            }

            private static readonly ImmutableArray<string> knownParameterNames = 
                ImmutableArray.Create(new[]
            {
                "paramName",
                "argumentName" /* used by System.ComponentModel.InvalidEnumArgumentException */
            });

            public override void Initialize(AnalysisContext initContext)
            {
                initContext.RegisterCompilationStartAction(startContext =>
                {
                    var argumentException = startContext.Compilation.GetTypeByMetadataName(
                        "System.ArgumentException");
                    var argumentNullException = startContext.Compilation.GetTypeByMetadataName(
                        "System.ArgumentNullException");
                    var argumentOutOfRangeException = startContext.Compilation.GetTypeByMetadataName(
                        "System.ArgumentOutOfRangeException");
                    var invalidEnumArgumentException = startContext.Compilation.GetTypeByMetadataName(
                        "System.ComponentModel.InvalidEnumArgumentException");

                    var knownTypes = ImmutableArray.Create(new[]
                    {
                        argumentException,
                        argumentNullException,
                        argumentOutOfRangeException,
                        invalidEnumArgumentException
                    });

                    startContext.RegisterSyntaxNodeAction(syntaxContext =>
                    {
                        var creationSyntax = (ObjectCreationExpressionSyntax)syntaxContext.Node;
                        var ctorSymbol = syntaxContext.SemanticModel.GetSymbolInfo(
                            creationSyntax, syntaxContext.CancellationToken).Symbol as IMethodSymbol;

                        if (ctorSymbol != null && knownTypes.Contains(ctorSymbol.ReceiverType))
                        {
                            AnalyzeObjectCreation(syntaxContext, creationSyntax, 
                                startContext.Compilation);
                        }
                    }, SyntaxKind.ObjectCreationExpression);
                });
            }

            private static IEnumerable<ParameterSyntax> GetParametersInScope(SyntaxNode node)
            {
                foreach (var ancestor in node.AncestorsAndSelf())
                {
                    if (ancestor.IsKind(SyntaxKind.SimpleLambdaExpression))
                    {
                        yield return ((SimpleLambdaExpressionSyntax)ancestor).Parameter;
                    }
                    else
                    {
                        var parameterList = ancestor.GetParameterList();
                        if (parameterList != null)
                        {
                            foreach (var parameter in parameterList.Parameters)
                            {
                                yield return parameter;
                            }
                        }
                    }
                }
            }

            private void AnalyzeObjectCreation(SyntaxNodeAnalysisContext syntaxContext,
                ObjectCreationExpressionSyntax creationSyntax, Compilation compilation)
            {
                var parameters = GetParametersInScope(creationSyntax);
                if (parameters.Any())
                {
                    foreach (var argument in creationSyntax.ArgumentList.Arguments)
                    {
                        AnalyzeArgument(syntaxContext, argument, knownParameterNames, compilation);
                    }
                }
            }

            private void AnalyzeArgument(SyntaxNodeAnalysisContext syntaxContext, 
                ArgumentSyntax argument, ImmutableArray<string> parameterNames, 
                Compilation compilation)
            {
                syntaxContext.CancellationToken.ThrowIfCancellationRequested();

                var argumentInfo = syntaxContext.SemanticModel.GetArgumentInfo(argument);
                if (argumentInfo.Parameter != null && 
                    parameterNames.Contains(argumentInfo.Parameter.Name))
                {
                    var expression = argument.Expression;
                    if (expression?.IsKind(SyntaxKind.StringLiteralExpression) == true)
                    {
                        ReportArgument(syntaxContext, expression);
                    }
                    else if (expression?.IsKind(SyntaxKind.IdentifierName) == true)
                    {
                        AnalyzeCallStack(syntaxContext, expression, compilation);
                    }
                }
            }

            private void AnalyzeCallStack(SyntaxNodeAnalysisContext syntaxContext, 
                ExpressionSyntax expression, Compilation compilation)
            {
                var analysis = syntaxContext.SemanticModel.AnalyzeDataFlow(expression);
                foreach (var callerParameterSymbol in analysis.DataFlowsIn)
                {
                    // TODO: The next line causes crash "symbol not in tree". 
                    // But without it, cross-file diagnostics do not work.
                    //foreach (var syntaxTree in compilation.SyntaxTrees)
                    foreach (var syntaxTree in new[] { syntaxContext.SemanticModel.SyntaxTree })
                    {
                        var invocations = syntaxTree.GetRoot()
                            .DescendantNodes()
                            .OfType<InvocationExpressionSyntax>();

                        foreach (var invocation in invocations)
                        {
                            AnalyzeInvocation(syntaxContext, invocation, 
                                callerParameterSymbol.Name, compilation);
                        }
                    }
                }
            }

            private void AnalyzeInvocation(SyntaxNodeAnalysisContext syntaxContext, 
                InvocationExpressionSyntax invocationSyntax, string parameterName, 
                Compilation compilation)
            {
                var parameters = GetParametersInScope(invocationSyntax);
                if (parameters.Any())
                {
                    foreach (var argument in invocationSyntax.ArgumentList.Arguments)
                    {
                        AnalyzeArgument(syntaxContext, argument, 
                            ImmutableArray.Create(parameterName), compilation);
                    }
                }
            }

            private void ReportArgument(SyntaxNodeAnalysisContext syntaxContext, 
                ExpressionSyntax argumentExpression)
            {
                var stringText = ((LiteralExpressionSyntax)argumentExpression).Token.ValueText;

                syntaxContext.ReportDiagnostic(Diagnostic.Create(Rule, 
                    argumentExpression.GetLocation(), stringText));
            }        
        }
    }

**Comment by DustinCampbell** [comment]
Hey @bkoelman -- we really gave C# Essentials a big push at Build and Ignite. At the moment, I don't think we'd pull this into the product. However, C# Essentials might be a nice staging ground for analyzers and fixers that eventually *do* make their way into the product. Are you interested in submitting your changes to the UseNameOfAnalyzer over at http://github.com/DustinCampbell/CSharpEssentials?

**Comment by Vannevelj** [comment]
Hey guys, I just came across this issue while looking into creating a Code Fix for, well, the same analyzer you've been making as well. I've been comparing my analyzer to yours and I was interested in hearing your feedback on it. If this code is of adequate quality then I'd be happy to contribute it of course, though I'd like eyes on it first.

	using System;
	using System.Collections.Immutable;
	using System.Linq;
	using Microsoft.CodeAnalysis;
	using Microsoft.CodeAnalysis.CSharp;
	using Microsoft.CodeAnalysis.CSharp.Syntax;
	using Microsoft.CodeAnalysis.Diagnostics;
	using VSDiagnostics.Utilities;
	
	namespace VSDiagnostics.Diagnostics.Exceptions.ArgumentExceptionWithNameofOperator
	{
		[DiagnosticAnalyzer(LanguageNames.CSharp)]
		public class ArgumentExceptionWithNameofOperatorAnalyzer : DiagnosticAnalyzer
		{
			public const string DiagnosticId = nameof(ArgumentExceptionWithNameofOperatorAnalyzer);
			internal const string Title = "Suggest using the nameof operator in an ArgumentException.";
			internal const string Message = "The field {0} is used in an ArgumentException as string. Consider using the nameof operator instead.";
			internal const string Category = "Exceptions";
			internal const DiagnosticSeverity Severity = DiagnosticSeverity.Warning;
			internal static DiagnosticDescriptor Rule = new DiagnosticDescriptor(DiagnosticId, Title, Message, Category, Severity, true);
			public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(Rule);
	
			public override void Initialize(AnalysisContext context)
			{
				context.RegisterSyntaxNodeAction(AnalyzeSyntaxNode, SyntaxKind.ObjectCreationExpression);
			}
	
			private void AnalyzeSyntaxNode(SyntaxNodeAnalysisContext context)
			{
				var objectCreationExpression = context.Node as ObjectCreationExpressionSyntax;
				if (objectCreationExpression == null)
				{
					return;
				}
	
				if (!objectCreationExpression.ArgumentList.Arguments.Any())
				{
					return;
				}
	
				var exceptionType = objectCreationExpression.Type;
				var symbolInformation = context.SemanticModel.GetSymbolInfo(exceptionType);
				if (symbolInformation.Symbol.InheritsFrom(typeof (ArgumentException)))
				{
					var arguments = objectCreationExpression.ArgumentList.Arguments.Select(x => x.Expression).OfType<LiteralExpressionSyntax>();
					var methodParameters = objectCreationExpression.Ancestors().OfType<MethodDeclarationSyntax>().FirstOrDefault()?.ParameterList.Parameters;
	
					// Exception is declared outside a method
					if (methodParameters == null)
					{
						return;
					}
	
					foreach (var argument in arguments)
					{
						var argumentName = argument.Token.Value;
						var correspondingParameter = methodParameters.Value.FirstOrDefault(x => string.Equals((string) x.Identifier.Value, (string) argumentName, StringComparison.OrdinalIgnoreCase));
						if (correspondingParameter != null)
						{
							context.ReportDiagnostic(Diagnostic.Create(Rule, objectCreationExpression.GetLocation(), correspondingParameter.Identifier.Value));
							return;
						}
					}
				}
			}
		}
	}

You can find the corresponding unit tests [here](https://github.com/Vannevelj/VSDiagnostics/blob/master/VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/Exceptions/ArgumentExceptionWithNameofOperatorAnalyzerTests.cs).

The functional scope of the above code is limited to diagnosing when an `ArgumentException` (or any subclass thereof) has a string in any of its arguments that corresponds to the case-insensitive string value of one of the enclosing method's parameters. 

I'm also working on a code fix though I'm still figuring out how to do the rewriting correctly. You can find the initial work on the Code Fix [here](https://github.com/Vannevelj/VSDiagnostics/blob/master/VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Exceptions/ArgumentExceptionWithNameofOperator/ArgumentExceptionWithNameofOperatorCodeFix.cs).

**Comment by srivatsn** [comment]
Closing this issue as further discussion on this issue should happen on the CSharpEssentials repo.
