### ISSUE TITLE
Inconsistency in CS0220 with bit shifting

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#22360]
**Version Used**: 

Assumed Roslyn 2.3 - Visual Studio 2017 v15.3.5, .NET Core SDK 2.0

**Steps to Reproduce**:

1. Attempt to compile the following code:

```
using System;

[Flags]
public enum Foo : long
{
    ShouldOverflow1 = 1 << 64,
    ShouldOverflow2 = checked(1 << 64),
    DoesOverflow1 = (1 << 63) + (1 << 63),
    DoesOverflow2 = (1 << 63) * 2,
}
```

**Expected Behavior**:

All four enum values result in `error CS0220: The operation overflows at compile time in checked mode`

**Actual Behavior**:

Only the final two enum values (`DoesOverflow1` and `DoesOverflow2`) result in CS0220.

---

Is this intended behaviour of the language, or is this a bug/inconsistency in Roslyn?

**Comment by jcouv** [comment]
From the [language spec](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#shift-operators):

> Shift operations never cause overflows and produce the same results in checked and unchecked contexts.

That surprised me too.
I'll close the issue as by-design (per current spec). Thanks
