### ISSUE TITLE
GetOperation inconsistency with VariableDeclaratorSyntax in VB

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#22362]
In VB, whether or not `GetOperation` will work with a `VariableDeclaratorSyntax` depends on whether or nod the variable declaration is in the form of `As New`. In this case it works successfully:

```VB.NET
Dim a As New M
```

In this case, it returns Nothing:

```VB.NET
Dim a As Integer = 1
```

This is because of how `GetVariableDeclarationStatementVariables` works, http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Operations/VisualBasicOperationFactory_Methods.vb,3cc49210c7e7ca7d,references. In the case of a `BoundLocalDeclaration`, we create the `IVariableDeclaration` with `boundLocalDeclaration.Syntax`. This syntax node is `a`, the `ModifiedIdentifierSyntax`. The `As New` case uses the `BoundAsNewLocalDeclarations.Syntax`, which is the `VariableDeclarationSyntax` node.

Fixing up the successful bind case here is relatively trivial, as the parent of the `ModifiedIdentifierSyntax` is the `VariableDeclaratorSyntax` we're looking for. However, the invalid syntax case gets a bit tricker. Given the following code:

```VB.NET
Dim a, b As Integer = 1
```

We get a `BoundDimStatement` with two `BoundLocalDeclaration`s under it, both of which use the `ModifiedIdentifierSyntax` as their node. The second `BoundLocalDeclaration` will have the initializer. @AlekseyTs and I did some brainstorming offline, and the theory we've come up with is to somehow detect this case and deduplicate the `IVariableDeclaration` statement, putting both `ILocalSymbol`s in a single `IVariableDeclaration`, with the initializer from the last bound node.

In order to do this, Aleksey proposed that we could modify the bound nodes, such that we see a shape at the end that corresponds to the IOperation shape we want. I'm thinking that we should be able to get away with detecting this scenario by determining if consecutive `BoundLocalDeclaration` nodes have the same `VariableDeclaratorSyntax` as parent nodes to their syntax nodes, as this is the only scenario that can occur in.

As part of this, we should also consider adding a bool property of `AsNewInitializer`, as we cannot currently tell the different between `Dim a As M = New M()` and `Dim a As New M()`

**Comment by DustinCampbell** [comment]
Here's some fun code:

```VB
Dim a(0 To 4) As Integer
    s As String() = {"Hello", "World"},
    sb As New StringBuilder(),
    d%? = 42
```

**Comment by 333fred** [comment]
Design Decision:

We standardize VB and C# on having the same tree structure here. In C#, we will have a `LocalDeclarationStatementSyntax` -> `IVariableDeclarationGroup`, `VariableDeclarationSyntax` -> `IVariableDeclaration`, and `VariableDeclaratorSyntax` -> `IVariableDeclarator`. In C# declarations, we will always have 1 group and 1 declaration, with n declarators.
In VB, we have `LocalDeclarationStatementSyntax` -> `IVariableDeclarationGroup`, `VariableDeclaratorSyntax` -> `IVariableDeclaration`, and `ModifiedIdentifier` -> `IVariableDeclarator`. In VB, we can have 1 group, m declarations, and n declarators. In VB, the initializer for a variable can be either in the declaration or declarator that corresponds to the syntax of the initializer. ie, for `Dim i = 1`, the initializer will be in the declaration, because the `EqualsValueSyntax` containing the initializer is in the `VariableDeclaratorSyntax`. For `Dim i(10) As Integer`, the initializer is in the declarator, because the array initializer is in the `ModifiedIdentifierSyntax`. We group declarators into declarations by their containing `VariableDeclaratorSyntax`.

To help users actually get the correct initializer, we create an extension method `GetVariableInitializer` on `IVariableDeclarator`, which will take care of figuring out whether to get the declarator or the declaration's initializer.
