### ISSUE TITLE
Go To Definition fails to navigate to metadata

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#22367]
**Version Used**: 15.4 Preview 2

**Steps to Reproduce**:

1. Open Roslyn.sln
2. Open AdditionalText.cs
3. Click on `string` or `CancellationToken`
4. Use one of the following commands
    1. Press <kbd>F12</kbd> or use **Go To Definition** from the editor context menu
    2. Press <kbd>Alt</kbd>+<kbd>F12</kbd> or use **Peek Definition** from the editor context menu

**Expected Behavior**:

* Following step 4.1, the editor navigates to the symbol in metadata
* Following step 4.2, the editor shows the symbol in metadata within a "peek" window

**Actual Behavior**:

* Following step 4.1, the editor displays a dialog which reads **Cannot navigate to the symbol under the caret.**
* Step 4.2 works as expected

**Comment by 06needhamt** [comment]
Can't repo this using the master branch and VS 15.4.1

**Comment by sharwell** [comment]
@06needhamt thank you!
