### ISSUE TITLE
Misleading BC37234 when compiling a .Net Framework VB project via dotnet CLI with a missing reference to Microsoft.VisualBasic

### ISSUE THREAD

**Issue by orthoxerox** [dotnet/roslyn#22369]
**Version Used**: 
dotnet cli 2.0
.net 4.6.1 targeting pack

**Steps to Reproduce**:

1. Create a new VB project `dotnet new console -lang VB`
2. Change target framework type to `net461`
3. Add `Dim X : X.Y` to `Program.vb`
4. Try running `dotnet build`

**Expected Behavior**:
An error message about a missing reference to Microsoft.VisualBasic is shown

**Actual Behavior**:

"error BC37234: Late binding is not supported in current project type." is shown

**Comment by Pilchie** [comment]
@livarcocc - sounds like this should go to https://github.com/dotnet/cli to get the reference added to `Microsoft.VisualBasic.dll` on net461?

**Comment by livarcocc** [comment]
@dsplaisted please take a look and move the bug.

**Comment by jcouv** [comment]
FYI @AnthonyDGreen (relates to the VB CLI issue we discussed last week)

**Comment by dsplaisted** [comment]
This issue was moved to dotnet/sdk#1622
