### ISSUE TITLE
Performance telemetry for completion

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#22376]
Need a VS telemetry event for completion that includes time from session triggered to request to editor to show popup (the editor can't implement this because our computation is async)

**Comment by Pilchie** [comment]
Ideally, we would include the async time until the editor *draws* the list, since they defer that to below user interaction.

Can this be added for 15.5 P2?

**Comment by dpoeschl** [comment]
Putting these on @jinujoseph 's radar as well.

**Comment by rchande** [comment]
One way to implement this would be to store the session's start time in the first Model we create and propagate that value through subsequent models. At the time we call the editor to present the list, we could also send a telemetry event. I'm not sure if the editor's completion list has an event we can wait for that will tell us when the list is actually done painting on screen.

**Comment by heejaechang** [comment]
@rchande has a time for me to drop by?

**Comment by jinujoseph** [comment]
closed via #22811
