### ISSUE TITLE
Performance telemetry for "fix all"

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#22377]
We need to augment the existing lightbulb to telemetry to account for invocations of "fix all". This may be a little tricky because fix all currently triggers the "preview changes" dialog, which requires user input in order to continue. It might be worth breaking this up into time to show preview changes and time to apply the fix after "apply" is clicked.

**Comment by Pilchie** [comment]
Can this be added for 15.5 P2?

**Comment by dpoeschl** [comment]
Putting these on @jinujoseph 's radar as well.

**Comment by Pilchie** [comment]
Assigning to @heejaechang per @jinujoseph

**Comment by jinujoseph** [comment]
closed via @22811
