### ISSUE TITLE
What about all the cool features VB can but not C#?

### ISSUE THREAD

**Issue by HugoRoss** [dotnet/roslyn#2238]
ISSUE 1:

In VB I can easily create an inner interface like this (or also an inner class within an interface): 

Public Interface ICustomerService

```
Function Save(customer As ICustomer) As IMethodResult

Interface Version2
    Inherits ICustomerService

    Sub SaveAsync(customer As ICustomer, callback As Action(Of IMethodResult))

End Interface

Interface Version3
    Inherits ICustomerService.Version2

    Overloads Function SaveAsync(customer As ICustomer) As Guid
    Function GetMethodResult(trackingNumber As Guid) As IMethodResult

End Interface
```

End Interface
## When can I do this in C#?

ISSUE 2:

C# compiler is poor in field initializations like this, which the VB compiler handles without any problem:

```
public class OuterClass {

    private InnerClass _InnerClass = new InnerClass(this); // <-COMPILE ERROR!

    private class InnerClass {

        private OuterClass _OuterInstance;

        public InnerClass(OuterClass outerInstance) {
            _OuterInstance = outerInstance;
        }

    }

}
```

Same problem which field initialization of fields that reference a previously initialized field. In VB, no problem, in C# a compile error occurs:

```
public class Test {

    private Int32 _FieldA = 55;
    private Int32 _FieldB = _FieldA * 5; // <-COMPILE ERROR!
    private List<String> _Cache = new List<String>(_FieldA + _FieldB); // <-COMPILE ERROR!

}
```

ISSUE 3:
C# compiler is poor in compiling foreach loops, which the VB compiler handles without any problem:

```
    public void DoSomething(IEnumerable<String> stringCollection) {
        foreach (String myString in stringCollection) {
            myString = myString ?? ""; // <- COMPILE ERROR!
            //Do something with it
        }
    }
```

When are these issues fixed?

Thank you
Chris

**Comment by HaloFour** [comment]
None of these are problems, just differences between the languages.  The languages aren't supposed to be the same.

Issue 1:

This is an inherent difference in how the two languages handle field initializers.  The C# compiler initializes fields before calling the base constructor.  The VB.NET compiler initializes fields after.  As such the C# compiler cannot assign or use `this` in a field initializer because `this` does not exist yet.  At the same time, the VB.NET compiler is incapable of having fields initialized before the base constructor is called.  Neither are wrong, just different.

Issue 2:

The C# compiler explicitly decided that nested interfaces shouldn't be permitted.  This is a design choice.

Issue 3:

It doesn't make a lot of sense for the iterator variable to be modified.  I'd side with C# here in terms of correct behavior.  If you want to have a modified value, assign it to a temporary variable.

**Comment by Eirenarch** [comment]
Please no. Especially 3. I will have to ban it in my projects and I prefer that it just doesn't compile.

**Comment by HugoRoss** [comment]
What's the problem? Variable reassigning and recycling is something one does all the time and why not in an enumeration?

**Comment by dsaf** [comment]
@HugoRoss Actually the best practice would be to never reassign and recycle variables. In some cases I even add local blocks ```{ string someVar; ... }``` just to prevent a var from being mistakenly reused. It reduces the cognitive load the way pure functions and immutability do.

**Comment by HugoRoss** [comment]
This is one opinion, but I disagree. IL has an optimized syntax for a slot size of up to 8 variables. If you keep the number below that, the compiler can compile to the short IL syntax which results in lesser code and faster precompilation. 

As they are local variables, there is no issue with pure functions and immutability, every call to the function/method has its own scope anyway. 

Why should I keep a reference to a variable in memory that I do not need anymore? 
x = x.ToLowerInvariant();
is more efficient than
y = x.ToLowerInvariant();
because the GC can already collect the not anymore used previous value of x.

Or am I now completely off the road?

**Comment by HugoRoss** [comment]
Issue 1:
   In my opinion it would be useful if the compiler would decide if a "this" is involved in field initialization to use VB.NET behavior and have the field initialized after the base constructor was called.
   [Just for clarification] In VB.Net it is also possible to have fields initialized that are accessed e.g. by an abstract base class' constructor. One simply has to use a lazzy initialization in a getter of a property to initialize it.

Issue 2:
   People also ask for static methods within interfaces which was the same design choice and currently it is thought over...

**Comment by svick** [comment]
@HugoRoss If you're not reading `y` anywhere again, then the GC can also collect its value.

**Comment by Eirenarch** [comment]
@HugoRoss I find the idea of reusing variables for performance reasons quite absurd. Maybe an argument can be made that a variable can be reassigned due to the logic of the code but not for performance. In any case if you are doing something so performance critical that the number of variables matter I guess you won't be using foreach to begin with.

**Comment by HugoRoss** [comment]
It was just partial sample code, it assumes the lower-case value would be used for something else throughout the loop.

**Comment by HaloFour** [comment]
@HugoRoss Actually, the optimized "tiny header" is only permitted if you have zero local variables.  You're thinking of the maximum stack size, which defaults to 8 for tiny headers and cannot be changed unless you flip to fat headers.  With tiny headers you're also limited to 64 bytes of IL and no extra sections (so no exception handling).

That said, compiler variables never have to be a 1:1 to IL local slots.  Compilers are smart enough to reuse a slot as variables go out of scope.

All of your complaints are simply design decisions that were made 15 years ago and none of them prevent any functionality.  C# and VB.NET are not intended to be mirror languages and both can do things that the other can't.

**Comment by HugoRoss** [comment]
But what is the reason to keep these 15 year old limitations? I mean, everybody who thinks it is nonsense or ugly programming style to overwrite a variable does not have to code like that, but for us others it just feels natural, and it gives this feeling of being limited by C#. Same with inner interfaces. Company policy now is to use C#. Unfortunately some projects simply can't be converted to C# because they use this 15 year old .NET feature.

Again the question: Why limit the language artificially down if some people would like to use this feature, and the others simply can ignore it?

**Comment by HaloFour** [comment]
@HugoRoss More importantly, what is the reason to remove these 15 year old limitations?  What problems can't be solved due to them?

**Comment by HugoRoss** [comment]
A project can't be converted from VB.Net to C# without changing the public interface, is that reason enough?

**Comment by HaloFour** [comment]
@HugoRoss Not particularly.  The same would be true in inverse, or between C# and F#, or between F# and VB.NET.  That's why the Common Language Specification exists, to define the expected common subset.  As long as the public surface is CLS then it should be reasonable to be ported intact, otherwise there is no guarantee that you can port between languages verbatim.

**Comment by HaloFour** [comment]
Here's Eric Lippert's take on nested interfaces on Stackoverflow:

[Why can't an interface contain types](http://stackoverflow.com/questions/16151614/why-cant-an-interface-contain-types)

**Comment by dsaf** [comment]
@HaloFour 

> ...or between C# and F#...

I wouldn't say 'no' to that :). F# features + C# syntax: heart_eyes:.

**Comment by HugoRoss** [comment]
Inner types are not very useful (one can provide a default implementation or static functions that do something with instances of the declared interface) and I used them very rarely in my VB time, but inner interfaces are a nice way of versioning them.

But I see I'm going to be out-voted, and this is surely a thing that would cost some time and money to implement.

The variable recycling issue I understand less, that's just a nice to have which makes code more readable and allows the GC to collect the variable earlier, I'm really surprised to face such head wind against it.

**Comment by n8ohu** [comment]
As has been said, you're expecting two different languages that use the same common language runtime to be able to do things in exactly the same way. What you need to realize is that VB.NET inherited a lot of its features from the older Visual Basic, and C# is more closely related to C and C++ than some people think. I'm in the process of porting a VB.NET application to C# that is being written by another developer; his code is going to be the main Windows version of the application, while my C# code is going to be the open source version for Windows, Linux and Mac OS. Some of his code is actually based on open source C code ported to VB.NET, which I was able to easily port to C#; other code of his is giving me a headache finding the right way to convert it due to the differences between languages, but I'm certain there is a way to do it.

**Comment by HugoRoss** [comment]
They do not need to do it the same way, but why should C# not implement the good stuff from VB?

2013 I created the nuget package CustomEnum (https://www.nuget.org/packages/CustomEnum.vb) and I didn't manage to convert it to C# in a way that preserves its features. (@HaloFour: By the way, this is a situation where the base constructor of a VB class accesses child fields through getters with lazzy initialization before they are assigned).

One problem arised with the "if (x == null)" or "if (x != null)" bug (you probably call it a feature): VB has the statement of "If x Is Nothing Then" which is the same as in C# "if (Object.ReferenceEquals(x, null))". But an ordinary C# programmer does not use that syntax, they simply write "if (x == null)" which is better readable and also works most of the time. But, unfortunately, it does not work anymore if the target class (here class "x") implements multiple overloads of equality operators. It's already problematic if there is one equality operator (imagine if that equals operator returns false if I compare a null variable to null for some reasons - I'm sure nobody expects that x.ToString() on the following line throws a ReferenceNullException) but if there are multiple ones, the compiler does not know which overload to take and tells the caller that it does not know what to do (The call is ambiguous...). Which renders my work unusable by C# consumers, as the average programmer is not willing to have to cast "if (x == (MyCustomEnum)null)" nor to use "if (Object.ReferenceEquals(x, null))". And if I remove one or both equality overload, I loose that functionality.

So another of my requests is that in future "if (x == null)" and "if (null == x)"  is always compiled to the same as compiling "if (Object.ReferenceEquals(x, null))",
and "if (x != null)" and "if (null != x)" is always compiled to to the same as compiling "if (!Object.ReferenceEquals(x, null))" regardless whether there is no, one or multiple overloads of equals/unquals as this only leads to confusion. (Maybe with a  backwards compatibility compiler instruction if somebody really needs previous behavior).

**Comment by HaloFour** [comment]
@HugoRoss

Actually in your enumeration case the GC cannot collect the original value even if you assign a new value to the variable.  The original value is still held by the instance of the `IEnumerator<T>` used in the enumeration and that root reference won't potentially be dropped until you move to the next element.

And no, `if (x == null)` isn't a bug if it triggers an overloaded `==` operator.  That's exactly what it is supposed to do and what it is documented to do.

**Comment by n8ohu** [comment]
@HaloFour: Exactly; each of the features he's asking for go against the core design principles of C#.

**Comment by HugoRoss** [comment]
Agree to that the value can't be collected. But the readability still is better if I don't have to declare and assign a new variable.

I know that bug/feature is by design like that, but in my humble opinion it is a design error as what sensible answer can an equals overload return without confusing the caller other than what Object.ReferenceEquals returns (in the case a value is compared against null)?

**Comment by HaloFour** [comment]
@HugoRoss 

Well you're welcome to your opinion.  I've made use of those operators to overload how null checking works on a number of occasions, especially when comparing to other types.  Admittedly I've also been bitten by it once or twice when trying to handle a null check within the operator accidentally causing a `StackOverflowException`.  It's probably a good idea for an analyzer to flag such situations.

It doesn't really matter because at this point it's baked into the language and the spec and cannot be changed without breaking existing code.

**Comment by HugoRoss** [comment]
@HaloFour 

cit. [It doesn't really matter because at this point it's baked into the language and the spec and cannot be changed without breaking existing code]

With a little effort it could be done: Create a new compiler switch "-NatvieToNullComparison" or something like that and a checkbox in the C# project settings. In the Visual Studio settings add a NatvieToNullComparison-preference checkbox that initially is true and which is used if a new project is created. Migrated projects of older VS versions are initialized with NatvieToNullComparison = false. And of course the language specs would have to be adjusted accordingly.

**Comment by gafter** [comment]
@HugoRoss VS Checkboxes are not part of the C# programming language.

**Comment by AnthonyDGreen** [comment]
@HugoRoss,

FWIW, VB actually requires nested types in interfaces. Consider this scenario:

``` VB.NET
Interface IA
    Event E(sender As Object, e As EventArgs)
End Interface
```

In Visual Basic, when you declare an event ```E``` with an inline signature the compiler implicitly declares a delegate nested in the same type with that signature and the name ```EEventHandler```. That's the behavior for events declared in classes, structures, or interfaces. So the above definition is exactly equivalent to writing:

``` VB.NET
Interface IA
    Delegate Sub EEventHandler(sender As Object, e As EventArgs)
    Event E As EEventHandler
End Interface
```

If VB didn't support nested types in interfaces event declarations in interfaces would always have to use the explicit syntax. Today this is less worrisome because with .NET 2.0 and generics we have the ```EventHandler(Of TEventArgs)``` delegate type but in 1.x that wasn't the case and this made declaring and consuming events in VB very convenient. Since C# doesn't have that inline event signature feature it doesn't require the nested type feature (not that that's a reason to not do it).

**Comment by levidrain** [comment]
Are nested interfaces that different from static methods on interfaces (at least from a design perspective)?  Neither are CLS compliant, but that's not preventing static methods from being considered. 
As for their usefulness, I can think of lots of cases.  Especially, when generics are considered.
```CSharp
interface IRepository<TObject, TKey>
{
   class SomeRelatedClass { }  // assuming this type uses both TObject & TKey 
}
interface ICustomerRepository : IRepository<Customer, int>
{
}
```
Assuming the code above, I could reference the specific closed inner type
```CSharp
void SomeMethod(ICustomerRepoitory.SomeRelatedClass related) ...
```
Without nested, the related type has to be moved to top-level, making it also generic..
```CSharp
void SomeMethod(SomeRelatedClass<Customer, int> related) ...
```

The type arguments have to repeated and depending on how it's used my or may not generate compile time errors if there's a mismatch.

**Comment by TyreeJackson** [comment]
@levidrain 

One work around for the `IRepository` example you provided above would be:

```cs
public abstract class Entity<TObject, TKey>
{
    interface IRepository {}
    public SomeRelatedClass {}
}
public class Customer : Entity<Customer.DataObject, int>
{
    public class DataObject {}
}
```

Which would be used like:

```cs
void SomeMethod(Customer.SomeRelatedClass related) ...
```

Don't get me wrong, I agree that nesting types in interfaces has uses, especially in the creation of boilerplate supporting types for an interface.  Some of these can be worked around like in this altered version of your example.  Others, you either have to go to VB.Net or pure IL to resolve.  Another alternative to nesting types that share generic parameters would be a new concept like parametric namespaces or generic modules.  I've started an issue to discuss those ideas if you are interested in #4494.

**Comment by TyreeJackson** [comment]
@HugoRoss 

Here is another thing that VB can do that I'm not sure I would want to see in C#, but it may be worth mentioning.  VB supports `ByRef` on the `this` parameter in extension methods!  It's completely *evil*, but *interesting*.

Consider the following extension method:

```vb
<Extension()> _
Public Function InstantiateIfNeeded(Of T as {Class, New})(ByRef value As T) As T
        value = If(value, New T())
        Return value
End Function
```

This extension method will replace the variable assignment in the following usage example:

```vb
Public Class SomeType
    Public Sub DoSomething()
    End Sub
End Class

Public Module Tester
    Public Sub TryIt()
        Dim someObject as SomeType = Nothing
        someObject.InstantiateIfNeeded().DoSomething()    ' <- someObject is magically instantiated!
        Assert.IsFalse(someObject is Nothing)
    End Sub
End Module
```

Again, the above is *evil*, but *interesting*.  Moral of the story, be careful when using extension methods in VB.Net that you are not familiar with.

**Comment by HugoRoss** [comment]
@TyreeJackson 

Totally agree with you about this being evil but interesting. 

I see a lot of extension methods around that accept null values and I think that's totally wrong. In my opinion, the first line of any extension method should always be "If (x Is Nothing) Then Throw New NullReferenceException()" (and no ArgumentNullException for that matter!). Because if I sell a static function as an instance method it should also behave like an instance method. And x.ToString() does not return an empty string if x is nothing, it does not throw an ArgumentNullException, it is always going to throw a NullReferenceException).

But I like the VB-philosophy that does not forbid something just because it's against some guidelines or considered evil by the majority. Why not use it if you have a usecase for it? I'm sure it saves the day of more than one poor programmer out there.

HugoRoss

**Comment by HugoRoss** [comment]
Another thing I would like to have implemented in C# is that it is possible to catch an interface. Starting with C# 6.0 it is possible with the "when" keyword (borrowed from VB by the way which already has it since a long time) to reduce the close-coupling to the exception implementation.

In code: I would like that the following syntax (IMyInterface is the name of the interface the custom exception implements) would be valid:

            try {
                MethodThatMayThrowAnIMyException();
            } catch (IMyException ex) {
                Console.WriteLine(ex.Foo);
            }

and that it would compile to something similair as the compilation of:

            try {
                MethodThatMayThrowAnIMyException();
            } catch (Exception ex2) when (ex2 is IMyException) {
                IMyException ex = ex2 as IMyException;
                Console.WriteLine(ex.Foo);
            }

Thank you

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
