### ISSUE TITLE
High allocations in ProcessMultilineComment (TODO comment processing)

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#22398]
**Version Used**: 15.3

:link: Derived from information in [this developer community](https://developercommunity.visualstudio.com/content/problem/95966/vs-2017-153-high-cpu-usage-for-a-long-period-of-ti.html) feedback by @FransBouma.

**Steps to Reproduce**:

1. Open a solution with a large number of comments

**Expected Behavior**:

The TODO comment processor avoids duplicating all strings to the extent reasonably possible.

**Actual Behavior**:

The processor converts trivia to strings in `ProcessMultilineComment`, whether or not those strings are TODO comments.

**Triage Notes**:

For the feedback item indicated above, this is responsible for roughly 10% of the combined measured allocations in devenv and ServiceHub (Roslyn OOP). However, there is some concern (to me) that some of the allocations related to green-to-red node conversion are unavoidable - even if we don't trigger their creation in the TODO comment processor, they could be created later by another component.

**Comment by CyrusNajmabadi** [comment]
closing out as we haven't seen this show up in traces and this area has been pretty substantially rewritten.
