### ISSUE TITLE
[Ioperation] Verify and add tests for ...

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#22395]
- [ ] https://github.com/dotnet/roslyn/issues/18042#issuecomment-332685154 
- [ ] https://github.com/dotnet/roslyn/issues/18062#issuecomment-332684941
- [ ] https://github.com/dotnet/roslyn/issues/18062#issuecomment-332684941

**Comment by heejaechang** [comment]
this also related to https://github.com/dotnet/roslyn/issues/18061
