### ISSUE TITLE
Feature Request: Light weight property declaration

### ISSUE THREAD

**Issue by jonparker** [dotnet/roslyn#224]
Sometimes a class has many properties with the same type.
For example

```
public class Person
{
  public string FirstName { get;set; }
  public string LastName { get;set; }
  public string EmailAddress { get;set; }
}
```

Would become:

```
public class Person
{
  public string FirstName, LastName, EmailAddress { get;set; }
}
```

**Comment by alanfo** [comment]
I suppose there's some logic to your proposal as one can, of course, already, declare multiple fields on the same line.

`private string s, t, u;`

However, I'm not sure it sits too well with getter-only, mixed accessibility or initialized auto-properties as it might get rather confusing if all the properties were not of exactly the same kind:

`public string FirstName = "John", LastName = "Doe" {  get;set; }, EmailAddress { get; } = "JohnDoe@Anywhere.com";`

**Comment by somebody1234** [comment]
Wouldnt you just have those on a separate line? Like:

    public string FirstName = "John", LastName = "Doe" { get; set; }
    publlic string EmailAddress { get; } = "JohnDoe@Anywhere.com";

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
