### ISSUE TITLE
Add method name to listing of breakpoints

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#22402]
The current listing of breakpoints shows filename and location, as well as details about the breakpoint.
When you have multiple breakpoints in the same file (as shown below), it would be useful to have method names in the listing too.

![image](https://user-images.githubusercontent.com/12466233/30981291-cd5a94be-a438-11e7-9aec-116a2cb50a76.png)

**Comment by alrz** [comment]
And perhaps the breakpoint line itself in case you have multiple breakpoints in a method.

**Comment by tmat** [comment]
Tagging @caslan. The debugger owns this window.

**Comment by caslan** [comment]
@jcouv, if you picked "Function" in the Show Columns drop down, doesn't it accomplish what you want?

**Comment by jcouv** [comment]
@caslan Ah, indeed! Thanks much
Maybe we could consider checking it by default?
