### ISSUE TITLE
Proposal:  Offer to Implement Interfaces or Abstract Class from within type body

### ISSUE THREAD

**Issue by HaloFour** [dotnet/roslyn#22401]
I think it would be nice if the Quick Actions for implementing interfaces and abstract classes would be available when the caret is within the type body, along with "Generate overrides...".  This would remove the need to navigate back to either the type name or the implemented interfaces in order to use this quick action.

Optionally take a page from IntelliJ and if the current type hasn't implemented any required members from the base class or implemented interfaces offer an "Implement members..." quick action within the type body which would be similar to "Generate overrides...".

It would also be nice if the "Generate overrides..." action itself could be more context sensitive and default to override `abstract` members of the base class (assuming that the target type is not itself `abstract`) as well as possibly offering options for implementing interfaces.  Would be nice if that dialog could also group the members by the base type or interface for which the member would override with options to override all members from a particular type.

**Comment by dpoeschl** [comment]
We definitely try to be cautious about where we should quick actions to avoid being noisy. Tagging @kuhlenh on that part.

**Comment by HaloFour** [comment]
@dpoeschl 

I understand.  Probably not a good idea to shove all of them into the menu as there could be quite a few if you have a type that derives from an abstract class and implements a bunch of interfaces.  The quick action menu on the type name currently shows both but only for the first of the unimplemented interfaces.  But it's not even consistent about that.  If you click on the light bulb or hit Ctrl-. the context menu shows both, but if you right-click on the type name and select "Quick Actions and Refactorings" it only shows "Implement Abstract Class".

Another thing I really like about the way this behaves in IntelliJ is that the generated boilerplate source is put where the caret currently is (or I think the nearest closest position if the caret is within a method body, etc.).  The options in Visual Studio are very limited and guarantee that I end up moving the members around after they are generated.

**Comment by CyrusNajmabadi** [comment]
Closing out given lack of feedback.
