### ISSUE TITLE
Using Roslyn to analyze a .NET Framework project with .NET Core

### ISSUE THREAD

**Issue by thauk-copperleaf** [dotnet/roslyn#22415]
I am trying to analyze a .NET Framework project with Roslyn using .NET Core and an EAP build of Rider.

I can compile the solution/project using Rider successfully.

Using Roslyn and a .NET Core project, I am able to create a workspace, add the .NET Framework solution, and find the project I wish to analyze.

# Problem 1

The step `var compilationResult = compilation.GetCompilationAsync().Result` results in an "empty" compilation (no syntax trees), similar to this comment: https://github.com/dotnet/roslyn/issues/17968#issuecomment-299981189

Checking `workspace.Diagnostics` shows the message:

`[Failure] Msbuild failed when processing the file 'C:\Path\To\Solution.csproj' with message: The imported project "C:\Program Files\dotnet\Microsoft.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Path\To\Solution.csproj`

The answer to a similar question at https://stackoverflow.com/a/5695 suggests modifying the project file directly, replacing `MSBuildToolsPath` with `MSBuildBinPath` on this line:

`<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />`

However, this did not help. I tried hardcoding the path and removing `$(MSBuildToolsPath)` completely, but then it died trying to find the next `.targets` file.

I found a temporary workaround by adding the following line of C# code to my analyzer project before creating the workspace, which resolved the diagnostic errors and resulted in the compilation having syntax trees:

`Environment.SetEnvironmentVariable("MSBUILD_EXE_PATH", @"C:\Program Files\dotnet\sdk\2.0.0\MSBuild.dll");`

However, this is not a good solution. I have version 15.3.409 of both `Microsoft.Build` and `Microsoft.Build.Tasks.Core` added as NuGet dependencies, and therefore I should be able to point Roslyn to use those packages instead of whatever MSBuild I happen to have installed globally.

## What is the actual problem here? How can I fix it?

# Problem 2

I am attempting to do something similar to this: https://johnkoerner.com/csharp/creating-a-stand-alone-code-analyzer/

This line works:

`var classDeclarations = tree.GetRoot().DescendantNodesAndSelf()`

However, using `.Where(...)` like this

`var classDeclarations = tree.GetRoot().DescendantNodesAndSelf().Where(x => x.IsKind(SyntaxKind.ClassDeclaration))`

results in an exception, which I can only see if I use Rider and evaluate the expression while debugging:

`{System.NotSupportedException: Assembly.LoadFrom with hashValue is not supported.
   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm)}`

**Comment by svick** [comment]
> an exception, which I can only see if I use Rider and evaluate the expression while debugging

That kind of problem usually means some issue with the debugger. Assuming the code works if you don't use the debugger (even after you evaluate the LINQ query, e.g. using `foreach` or `ToList()`), then I think it makes sense to report this to Rider.

If it doesn't work, can you get the exception's stack trace?

**Comment by thauk-copperleaf** [comment]
Okay, ignore Problem 2. :)

Problem 1 still stands. How do I avoid manually setting the `MSBUILD_EXE_PATH` environment variable? How can I use the MSBuild I've installed via NuGet?

**Comment by CyrusNajmabadi** [comment]
Closing out for lack of customer feedback in this area.
