### ISSUE TITLE
Extract Method: Restore or remove code for option to move locals

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#2241]
In 58c985f4e909, I hid the option to move locals during extract method in the UI.  We should either re-add it, or remove the option.

**Comment by jmarolf** [comment]
@Pilchie Its been  long enough that we should make a call here.

**Comment by Pilchie** [comment]
Let's remove it.  I've heard no feedback asking for anything different, or the re-addition of the option.
