### ISSUE TITLE
Add IOperation API for local symbol initializers

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22429]
@AlekseyTs recommended we add an `ILocalSymbolInitializer` so we have parity with APIs for other symbol initializers (field/property/parameter)

**Comment by AlekseyTs** [comment]
I think my concern was mostly around the fact that we don't map any IOperation nodes to EqualsValueClauseSyntax within VariableDeclaratorSyntax, but do this for field and property declarations.

**Comment by mavasani** [comment]
I agree with @AlekseyTs - I think we should implement this.
