### ISSUE TITLE
Potential data race in the file GCManager.cs

### ISSUE THREAD

**Issue by MSIC-HSR** [dotnet/roslyn#22425]
**Version Used**: 
Master branch as of 29.9.2017 @ 14:40. Most actual commit as of this writing: [0afe1f6 on Feb 17, 2016](https://github.com/dotnet/roslyn/commit/0afe1f6dd3bd77e138f3df11db883827e1d93770)

**Steps to Reproduce**:
Potential data race in the file [GCManager.cs](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/GCManager.cs) on the variable `s_delayMilliseconds`.

**Expected Behavior**:
No data race on the variable `s_delayMilliseconds`.

**Actual Behavior**:
Potential data race on the variable `s_delayMilliseconds`.

**Additional Information**:
Hello

As part of an evaluation with a new static checker of our research, we think we have probably identified a potential (not necessarily critical and maybe very seldom occurring) data race. (A data race is an unsynchronized concurrent read/write or write/write access on the same variable or array element that has undefined behavior in the programming language, thus possibly considered as a formal issue as instructions could be reordered/optimized.) 

The data race may happen between the write access on `s_delayMilliseconds` in class [GCManager](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/GCManager.cs) (line [84](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/GCManager.cs#L48)) in a task launched at line [30](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/GCManager.cs#L30):

```cs
static GCManager() {
  System.Threading.Tasks.Task.Run(() => { // TASK START => CONCURRENT
        // …
        s_delayMilliseconds = DefaultDelayMilliseconds;  // WRITE ACCESS INVOLVED IN DATA RACE
  });
}
```

And read access on the same variable in class GCManager (line [60](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/GCManager.cs#L60)):

```cs
internal static void TurnOffLowLatencyMode() {
 if (s_delayMilliseconds <= 0) … // READ ACCESS INVOVLED IN DATA RACE
}
```

Other accesses such as GCManager.cs line [41](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/GCManager.cs#L41), line [67](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/GCManager.cs#L67), line [93](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/GCManager.cs#L93) may be involved as well.

A possible fix could be to declare the variable `s_delayMilliseconds` as `volatile`. Maybe the constellation is impossible or the issue is very minor or unlikely, we just wanted to hint it.

**Comment by sharwell** [comment]
I don't see an issue with `s_delayMilliseconds` in this context. However, the `TurnOffLowLatencyMode()` method could be updated to force `s_delay` to expire if it's called while `GCSettings.LatencyMode` is `GCLatencyMode.SustainedLowLatency`.

**Comment by MSIC-HSR** [comment]
Yes, `s_delay` is probably also involved in a data race and should be declared volatile, too. 
Did you notice that both variables may cause data races and that data races are per se problematic (.NET memory model)?

The problem with data races is that code may be reordered (as-if-serial semantics) and read/writes may be optimized away (along with other problems). For example, if one task/thread writes x, another thread may not see the latest value of x (unless it is properly synchronized, i.e., has a happened-before relation in the memory model).

**Comment by sharwell** [comment]
@MSIC-HSR In the cases I referred to, it appears all possible orderings produce observably-correct results. It's roughly an operation with this form:

```
if (CheckConditionWhichMayBeTrueOrFalseDueToRaceCondition())
{
  ConsiderDoingSomethingButItsFineToDoItAndAlsoFineToNotDoIt();
}
```

**Comment by CyrusNajmabadi** [comment]
> @MSIC-HSR In the cases I referred to, it appears all possible orderings produce observably-correct results.

@sharwell Do we need to do anything here then?  Or can this be closed out?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of response.
