### ISSUE TITLE
"Upgrade C# Language Version" code fix adds conditional property groups to csproj

### ISSUE THREAD

**Issue by anurse** [dotnet/roslyn#22433]
**Version Used**: Visual Studio 15.4 Preview 3.0

**Steps to Reproduce**:

1. In a C# project with no `<LangVersion>` property attempt to use a language feature not available in the latest major version. For example, a `default` expression.
2. Use the code fix to "Upgrade this project to C# language version 'latest'" (or '7.1', either should do the same thing)

**Expected Behavior**: A single `<LangVersion>` node was added to my unconditional `<PropertyGroup>` at the top:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
```

**Actual Behavior**: Two new conditional `<PropertyGroup>` nodes (one for Release, one for Debug) were added, each setting `<LangVersion>` to the same value:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
```

This seems odd to me as a user. As someone vaguely familiar with the internals of the project system, I do mostly understand what happened, but it's not what I'd expect as a user.

**Comment by jcouv** [comment]
This is a known issue. It's tracked by https://github.com/dotnet/project-system/issues/2732
I'll go ahead and close as duplicate. Thanks

**Comment by anurse** [comment]
Thanks! Gotta remember to search there too when I'm looking for these issues :)

**Comment by jcouv** [comment]
No worries. There are multiple repo, so it's not easy to know where to look. 
Cheers
