### ISSUE TITLE
Naming codestyles should handle local functions

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#22440]
The screenshot below shows the list of specifications we currently support. 
Can we add local functions?

![image](https://user-images.githubusercontent.com/12466233/31037750-6450e604-a527-11e7-9022-381188fa61bb.png)

FYI @kuhlenh @sharwell @agocke

**Comment by kuhlenh** [comment]
@jcouv @dpoeschl Lots of people have asked for local variable support for naming. Do we think local functions would have different style than other locals'?

**Comment by sharwell** [comment]
@kuhlenh I typically name local functions in PascalCase, as opposed to other locals in camelCase.

**Comment by kuhlenh** [comment]
@sharwell so treat local functions like methods? I'm just trying to figure out if there really is a need to call local functions out separately, or if we set the style to match locals or methods.

**Comment by jcouv** [comment]
In compiler code, we use PascalCase for methods, but so far we've used camelCase for local functions. The IDE code uses PascalCase even for local functions.

**Comment by jcouv** [comment]
I've been thinking about this more. Maybe we wouldn't introduce a naming code style for local functions, but rather introduce one for locals (which local functions would be one of).

**Comment by CyrusNajmabadi** [comment]
> but rather introduce one for locals (which local functions would be one of).

I'm not sure i would like that.  I use camelCase for locals, but PascalCase for local methods :)

**Comment by Neme12** [comment]
I think it's clear from this discussion that we need a separate rule :smile:

**Comment by Neme12** [comment]
A style for tuple element names would also be useful.

**Comment by Neme12** [comment]
@sharwell Please reopen, local functions are still not handled.
