### ISSUE TITLE
DeconstructionAssignmentWithRefReadonlyExtension unit test is failing regularly.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#22442]

**Comment by jcouv** [comment]
Looks like my PR (which added the test) was green before Omar's PR removed the `ref readonly` syntax. I'll fix the test and re-enable.
Thanks

**Comment by jcouv** [comment]
Re-opened, as I need to re-enable the test (with `in` syntax, instead of `ref readonly`)

**Comment by jcouv** [comment]
Vlad has a fix in his PR https://github.com/dotnet/roslyn/pull/22405, but I should make sure the test was unskipped.
