### ISSUE TITLE
Default literal diagnostics is over-enthusiastic in conditional operators

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#22448]
**Version Used**: 

- Microsoft (R) Visual C# Compiler version 2.3.2.62116
- VS 2017 Community Edition 15.3.5

**Steps to Reproduce**:

.NET Core 2.0 console app with `<LangVersion>7.1</LangVersion>`.

```csharp
using System;

class Program
{
    static void Main(string[] args)
    {
        string text = null;
        // Visual Studio 2017 offers to "simplify" this...
        int? foo1 = text == null ? default(int?) : Foo(text);
        // To this.
        int? foo2 = text == null ? default : Foo(text);
        // But they're not equivalent:
        Console.WriteLine(foo1); // null
        Console.WriteLine(foo2); // 0
    }

    static int Foo(string x) => x.Length;
}
```

**Expected Behavior**:

Diagnostic shouldn't offer to simplify an expression of `default(int?)` to `default` when the latter is actually equivalent to `default(int)`.

Note that the `(int?)` is greyed out as well, indicating that the analyzer really believes it's redundant.

**Actual Behavior**:

The opposite :)

**Comment by AdamSpeight2008** [comment]
Wouldn't be `default(int?)` if target type is taken into account?

**Comment by svick** [comment]
This sounds like a duplicate of https://github.com/dotnet/roslyn/issues/21638.

**Comment by alrz** [comment]
@AdamSpeight2008

Here the target-type is the type of the other operand, not where the ternary itself is being assigned.

**Comment by jskeet** [comment]
@svick: You're right, this is a duplicate of that. Apologies - I looked first, but because that issue doesn't mention "default literal" I didn't find it :(

**Comment by AdamSpeight2008** [comment]
@alrz  that usage of *target type* is misleading i think it should be *candidate type*.
`targetType target = condition ? canditade0 : candidate1;`
Then use the greatest common type determine the type?

**Comment by alrz** [comment]
I mean, whatever type that the compiler tries to "convert" the other side into.

```cs
class C {
    public static implicit operator string (C c)=>null;
    public void M(string s, bool b) {
        var x = b ? s : this; 
    }
}
```
 `x` is `string` and the conversion operator is called on `this`.

**Comment by AdamSpeight2008** [comment]
@alrz 
My understanding is it work like this
```c#
ProposedTargetType = match( (cadidateType0, cadidateType1) ) with
             {
               | (default, default) => return Error;
               | ( _     , default) => return cadidateType0;  ' default lowered to default<candidateType0>
               | (default, _      ) => return cadidateType1;  ' default lowered to default<candidateType1>
               | ( _     , _      ) => return GreatestCommonType( cadidateType0, cadidateType1 );
             }

{if ProposedTargetType.IsConvertableTo( TargetType ) = False )
{
  Error( ); 
}
 ```

**Comment by alrz** [comment]
It doesn't depend on either side being `default`, just that it doesn't have a type and is implicitly convertible to all types.
>```
>The second and third operands, x and y, of the ?: operator control the type of the conditional >expression. 
>•	If x has type X and y has type Y then
>    o	If an implicit conversion (§6.1) exists from X to Y, but not from Y to X, then Y is the type of the >conditional expression.
>    o	If an implicit conversion (§6.1) exists from Y to X, but not from X to Y, then X is the type of the >conditional expression.
>    o	Otherwise, no expression type can be determined, and a compile-time error occurs.
>•	If only one of x and y has a type, and both x and y, are implicitly convertible to that type, then that is >the type of the conditional expression.
>•	Otherwise, no expression type can be determined, and a compile-time error occurs.
>```

Curretly we don't a concept of "greatest common type", we just use the exact types of expressions.
