### ISSUE TITLE
"Find references" ignores collection element initializers

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#22449]
**Version Used**: 

- Microsoft (R) Visual C# Compiler version 2.3.2.62116
- VS 2017 Community Edition 15.3.5

**Steps to Reproduce**:

Create a console app containing the following class:

```csharp
using System.Collections.Generic;

internal static class NotUnusedPrivateMethod
{
    private static void Add(this Dictionary<int, int> dictionary, int value) =>
        dictionary.Add(value, value * 2);
    
    public static Dictionary<int, int> GetMapping() =>
        new Dictionary<int, int> { 1, 2, 3 };

    public static Dictionary<int, int> GetMapping2()
    {
        var dictionary = new Dictionary<int, int>();
        dictionary.Add(1);
        dictionary.Add(2);
        dictionary.Add(3);
        return dictionary;
    }
}
```

Right click on the "Add" method, and select "Find References".

**Expected Behavior**:

The calls from both `GetMapping` and `GetMapping2` should be shown.

**Actual Behavior**:

Only the calls from `GetMapping2` are shown.

This wouldn't be so bad, but other tools - in my case, CodeRush for Roslyn - appear to use this as an indicator of unused code. If you remove `GetMapping2` in an installation with CodeRush installed, the `Add` method is greyed out, suggesting it can be removed - but of course, it can't, because `GetMapping` relies on it.

**Comment by jcouv** [comment]
Tagging @jinujoseph for triage

**Comment by ivanbasov** [comment]
Using an extension method seems to be not a root cause of the issue. For https://github.com/dotnet/roslyn-analyzers/issues/459, I tried the following code:

```
using System.Collections.Generic;

class Dict : Dictionary<int, MyValue>
{
    public void Add(int key, int a, int b)
    {
        var val = new MyValue();
        val.A = a;
        this.Add(key, val);
    }
    
    public static Dict Create()
    {
        return new Dict()
        {
            {0, 1, 2}
        };
    }
}

class MyValue
{
    public int A;
}
```
No references for 'Add' could not be found.

**Comment by RikkiGibson** [comment]
Related to #38850
