### ISSUE TITLE
Perhaps rename ArgumentSyntax.RefOrOutKeyword to be RefKindKeyword

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#22441]
In addition to `RefKeyword` and `OutKeyword` It can now also have a value `InKeyword` so perhaps the original name no longer fits.

It would be technically a breaking change though in the APIs

**Comment by jcouv** [comment]
We can probably manage the breaking change by adding the new API and marking the old one as obsolete.

**Comment by alrz** [comment]
err, https://twitter.com/jaredpar/status/880171504926720000

**Comment by jcouv** [comment]
Ah, makes sense. 
@dotnet/compiler-api  Should we just add the better named property (leaving the existing one), or stick with just the existing one?

**Comment by alrz** [comment]
Could we have "soft" obsolete warnings that does not turn to errors with warnaserror? `RefOrOutKeyword` is obviously misleading and wouldn't be the last one that needs to be renamed. Even if we add another property, I think it's good to hint the user about the change.

**Comment by sharwell** [comment]
> Could we have "soft" obsolete warnings that does not turn to errors with warnaserror?

It turns out this doesn't exist, because we can't stop people from doing this:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/baeb1267507f71b49b0f57982e6dcd4c99e4f9af/StyleCop.Analyzers/Directory.Build.props#L25-L28

**Comment by gafter** [comment]
There is nothing actively harmful or incorrect about the old overload, so I'm not obsoleting anything.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/22472
