### ISSUE TITLE
IDE visualizes span as [deprecated]

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#22450]
![image](https://user-images.githubusercontent.com/8218165/31048319-795b052c-a5cf-11e7-91b3-bbda0edc7f12.png)

The Obsolete attributes on ref-like types are a part of compiler/runtime handshake and should not be visualized when follow the pattern.

I am not sure on what side this is - symbol display or some higher IDE level, but these obsolete should be filtered out.

**Comment by VSadov** [comment]
I think this is 15.5  since it is very visible.

**Comment by OmarTawfik** [comment]
@VSadov I'll look into it.

**Comment by OmarTawfik** [comment]
@roslyn-ide any pointers where to start digging into this?

**Comment by CyrusNajmabadi** [comment]
@OmarTawfik All IDE resources are named after their english content.  So you can just search for 'deprecated' and you'll find the resource.  You can then FindAllRefs on that to find the location it is used.
