### ISSUE TITLE
Metadata view should not show wellknown/embedded attributes

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#22453]
![image](https://user-images.githubusercontent.com/8218165/31048358-287ddd86-a5d0-11e7-8d9a-5dd0015f3a29.png)

None of the attributes are really expected in this view. 
They do exist in metadata, but since we show something that looks like source, they should be mapped to language features.

This is not a valid syntax. I'd expect something like

```cs
public readonly ref struct ReadOnlySpan<T>
```

Not sure if this is a matter of symbol display (Compiler) or some higher layer in IDE.

**Comment by VSadov** [comment]
I think this is 15.later since this is not directly visible

**Comment by VSadov** [comment]
CC: @jcouv - for triage

**Comment by jasonmalinowski** [comment]
Also adding @jinujoseph for IDE statements of how important this is. This is a pretty common feature...I'd be surprised if we didn't fix this up as we went along.

**Comment by CyrusNajmabadi** [comment]
IMO, this is certainly something that should be fixed.  But it's also not super critical.  i.e. metadata-as-source is certainly not lying to you.  It's showing you the metadata accurately.  Of course, having it closer to the C# representation is def desirable, but that could come later (or be given up-for-grabs) for someone to take.

**Comment by CyrusNajmabadi** [comment]
This correct looks like this now:

![image](https://user-images.githubusercontent.com/4564579/198751174-9df6e10c-1393-4d9a-b6d3-d3529dd3e08e.png)
