### ISSUE TITLE
`in` and `out` arguments should be disallowed in `__arglist`

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#22455]
varargs should disallow  `out` and `in` arguments. There is no way the calee can express its part of the contract.

We currently allow both and `out` was allowed in old compiler versions too. We should disallow both. 

Arguably it would be a breaking change for `out`, but it is very unlikely it would affect real code. 

Example:

```C#

    class Program
    {
        static void Main(string[] args)
        {
            int unassigned;
            int doNotChange = 42;

            Test(__arglist(out unassigned, in doNotChange));  // <--  out?   in?  really?

            System.Console.WriteLine(unassigned);
            System.Console.WriteLine(doNotChange);
        }

        static void Test(__arglist)
        {
            var args = new ArgIterator(__arglist);

            // leave unassigned unassigned
            ref var unassigned = ref __refvalue(args.GetNextArg(), int);

            // assign junk to doNotChange
            ref var doNotChange = ref __refvalue(args.GetNextArg(), int);
            doNotChange = unassigned;
        }
    }
```

**Comment by VSadov** [comment]
15.later since this is in an "undocumented" feature.

**Comment by VSadov** [comment]
CC: @jcouv  for triage
Also @gafter since there is a compat concern here.

**Comment by VSadov** [comment]
@dotnet/roslyn-compat-council - are we ok with this change compat-wise?

**Comment by tannergooding** [comment]
@VSadov, what about `ref`?

**Comment by jaredpar** [comment]
Need to send an email to compat council. Not enough will respond to the github notification.

**Comment by VSadov** [comment]
`ref` is ok. Varargs can be byref and work just fine. 
It is the contracts of `in` and `out` that do not make sense in vararg case - callee essentially cannot promise anything - whether it will or will not write through the refs. 

If we use `in` or `out` at cal site we end up with situation where caller trusts its own annotation, which is pointless.

**Comment by VSadov** [comment]
@jaredpar - right, Will send.

**Comment by jaredpar** [comment]
Compat council agreed on this change. Lets address in 15.7.
