### ISSUE TITLE
Out variable declaration with same name as existing variable causes Internal error in the C# compiler

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#22474]
https://developercommunity.visualstudio.com/content/problem/122978/out-variable-declaration-with-same-name-as-existin.html

Scenario 103-Debugging C# 7 Features

Declare function 
static void R(out double x, out int y) => x = y = 4;

In a Main function pause on this line:
R(out double x, out int y);

In the expression window, enter:
R(out var x, out var y);

Expected: 
error CS0136: A local or parameter named 'x' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter

Actual:
Internal error in the C# compiler

**Comment by ivanbasov** [comment]
Related to more general one: https://github.com/dotnet/roslyn/issues/16062

**Comment by ivanbasov** [comment]
Related to https://github.com/dotnet/roslyn/issues/15132

**Comment by ivanbasov** [comment]
Resolved with https://github.com/dotnet/roslyn/pull/24198
