### ISSUE TITLE
Immediate Window throw expression on null causes Internal error in the expression evaluator.

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#22475]
https://developercommunity.visualstudio.com/content/problem/122928/immediate-window-throw-expression-on-null-causes-i.html 

Scenario 103-Debugging C# 7 Features

In the Immediate Windows for a C# project, enter

(object)null ?? throw null

The throw expression should cause a null-reference exception .

Instead, you see "Internal error in the expression evaluator."

cc @ivanbasov  to triage

**Comment by ivanbasov** [comment]
It seems that there is an issue on the Debugger side. Therefore, I'm reactivating the Feedback issue and resolving this one.
