### ISSUE TITLE
Refactoring 'Move declaration near reference' for VB results in erroneous code

### ISSUE THREAD

**Issue by richaverma1** [dotnet/roslyn#22471]
**Version Used**: d15rel 26927.1

**Steps to Reproduce**:

1. I have this code -
        Dim b As Integer
        Console.WriteLine("")
        Dim k As Integer = 20
        b = Floor(1.7)
2.  Keep cursor on the first line and hit ctrl+. , select 'Move declaration near reference'
3.  Code changes to 
        Console.WriteLine("")
        Dim k As Integer = 20
        Dim b As Integer
= Floor(1.7)

**Expected Behavior**: Resulting code to not have any syntax error

**Actual Behavior**: There is syntax error on the last line of the resulting code.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to be changing these experiences.
