### ISSUE TITLE
Less information in Initializers (ObjectCreationExpression)

### ISSUE THREAD

**Issue by asoifer** [dotnet/roslyn#22489]
**Version Used**:  2.3.2 (Release)

Supose we have this operation:

operation = "new M { Title = "Title", Description = "aaa", ReleaseDate = new DateTime(2007, 03, 12) }"
this operation is an object creation expression... then

In the **previous** version of IOperation interfaces we have, this information:

operation.Initializers.ToList()[0].Kind is OperationKind.**PropertyInitializerInCreation**
operation.Initializers.ToList()[1].Kind is OperationKind.**FieldInitializerInCreation**
operation.Initializers.ToList()[2].Kind is OperationKind.PropertyInitializerInCreation

Im saying you could know if you are assigning a value to a Field or a Property, but now, in the **latest** version you have...

operation.Initializers.ToList()[0].Kind is OperationKind.AssignmentExpression
operation.Initializers.ToList()[1].Kind is OperationKind.AssignmentExpression
operation.Initializers.ToList()[2].Kind is OperationKind.AssignmentExpression

Ok, lets see what can I do with "AssignmentExpression":

var assignmentExpression = operation.Initializers.ToList()[0] as IAssignmentExpression;
Right side: assignmentExpression.Value ==> Thats right, like the previous version
Left side: assignmentExpression.Target ==> this object only contains the type of the property, anything else, and these are equal objects:

((IAssignmentExpression)operation.Initializers.ToList()[0]).Target
((IAssignmentExpression)operation.Initializers.ToList()[1]).Target

Because both of them are the same type symbol!, but... i cant know if im working with properties or fields, this information is not available in the type symbol. then, I have to look for parent symbol (type of my object M) and search a property or field with the same name that assignmentExpression.Target.Syntax.GetText().. or something like that. 

If im not wrong, im telling that you need to know if you are working with properties or fields in initializers. 

Thanks a lot, 
Alex

**Comment by jcouv** [comment]
FYI @jinujoseph @heejaechang  for triage

**Comment by mavasani** [comment]
We should already have this information in the latest initializer API (not sure if it was part of 2.3.2, but should be part of latest API). See the unit test [ObjectCreationWithMemberInitializers](http://source.roslyn.io/#Roslyn.Compilers.CSharp.Semantic.UnitTests/IOperation/IOperationTests_IObjectCreationExpression.cs,14): 

[Source code snippet](http://source.roslyn.io/#Roslyn.Compilers.CSharp.Semantic.UnitTests/IOperation/IOperationTests_IObjectCreationExpression.cs,36
):
```
var x4 = new F() { Property1 = """", Field = 2 };
```

[IOperation tree for this snippet](http://source.roslyn.io/#Roslyn.Compilers.CSharp.Semantic.UnitTests/IOperation/IOperationTests_IObjectCreationExpression.cs,86):
```
IVariableDeclarationStatement (1 declarations) (OperationKind.VariableDeclarationStatement) (Syntax: 'var x4 = ne ... ield = 2 };')
    IVariableDeclaration (1 variables) (OperationKind.VariableDeclaration) (Syntax: 'x4 = new F( ... Field = 2 }')
      Variables: Local_1: F x4
      Initializer: IObjectCreationExpression (Constructor: F..ctor()) (OperationKind.ObjectCreationExpression, Type: F) (Syntax: 'new F() { P ... Field = 2 }')
          Arguments(0)
          Initializer: IObjectOrCollectionInitializerExpression (OperationKind.ObjectOrCollectionInitializerExpression, Type: F) (Syntax: '{ Property1 ... Field = 2 }')
              Initializers(2):
                  ISimpleAssignmentExpression (OperationKind.SimpleAssignmentExpression, Type: System.String) (Syntax: 'Property1 = """"')
                    Left: IPropertyReferenceExpression: System.String F.Property1 { get; set; } (OperationKind.PropertyReferenceExpression, Type: System.String) (Syntax: 'Property1')
                        Instance Receiver: IInstanceReferenceExpression (OperationKind.InstanceReferenceExpression, Type: F) (Syntax: 'Property1')
                    Right: ILiteralExpression (OperationKind.LiteralExpression, Type: System.String, Constant: """") (Syntax: '""""')
                  ISimpleAssignmentExpression (OperationKind.SimpleAssignmentExpression, Type: System.Int32) (Syntax: 'Field = 2')
                    Left: IFieldReferenceExpression: System.Int32 F.Field (OperationKind.FieldReferenceExpression, Type: System.Int32) (Syntax: 'Field')
                        Instance Receiver: IInstanceReferenceExpression (OperationKind.InstanceReferenceExpression, Type: F) (Syntax: 'Field')
                    Right: ILiteralExpression (OperationKind.LiteralExpression, Type: System.Int32, Constant: 2) (Syntax: '2')
```

**Comment by asoifer** [comment]
Thanks Manish, I'll wait for the new releases. 
Regards
