### ISSUE TITLE
Restrict "'default' expression can be simplified"

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/roslyn#22484]
### Motive 

Consider this C# 7.1 snippet in Visual Studio 15.3.5:

![image](https://user-images.githubusercontent.com/2716316/31126369-43449d54-a854-11e7-9688-b33d3609ecaa.png)

The compiler offers to "simplify" `default(DateTime)` with `default`, but that's not just a mere simplification, because the return type of the function is `object`, so `default` will return `null` whereas the default `DateTime`, which is a value type, is an unset tho initialized instance of `DateTime`.
The offer the compiler notifies sounds like it has no impact on the actual code but a syntactic sugar, which is wrong.

Here's another example where the compiler offers to substitute `default(double)` with `default` where it will cause a runtime error by the Xamarin runtime:
![image](https://user-images.githubusercontent.com/2716316/31127644-3ca97380-a858-11e7-943f-69819fe48ab0.png)
And yet another one:
![image](https://user-images.githubusercontent.com/2716316/31127875-c76cf8f2-a858-11e7-95a0-19eec72a33aa.png)
Simplifying will lead to other semantics.

### Conclusion

Simplification of `default(T)` should only be offered when no impact is made by the simplification, and only when the the types before and after simplification will be the same.

**Comment by HaloFour** [comment]
I agree, the analyzer needs to detect the context in which the expression will be used/assigned.  This is also happening in the following case:

![image](https://user-images.githubusercontent.com/10102290/31127090-d8d80a1a-a81b-11e7-9995-e3bbb70d9453.png)

**Comment by weitzhandler** [comment]
I've updated my question with another example.

**Comment by ufcpp** [comment]
https://github.com/dotnet/roslyn/issues/21941

**Comment by weitzhandler** [comment]
@ufcpp,
I'm gonna close this issue then.
