### ISSUE TITLE
C# simplification code fix is not offered for lambda with dynamic parameter

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn#22493]
**Version Used**: Visual Studio 2017 15.3.5

**Steps to Reproduce**:

1. paste the following code into a new C# file
```csharp
using System;

class P
{
    public static void Main(string[] args)
    {
        Action<dynamic> s = (x) => System.Console.WriteLine(x);
    }
}
```

**Expected Behavior**:
Simplification code fix is available for `System.Console.WriteLine(x)` to remove `System.`

**Actual Behavior**:
Simplification code fix is not available.

Note: it became available after replacing `dynamic` with `object`

**Comment by CyrusNajmabadi** [comment]
This is unrelated to lambdas.  A simpler repro is:

```
        dynamic y = null;
        System.Console.WriteLine(y);
```

We don't offer to simplify this either (though we would with `object`).
