### ISSUE TITLE
Code Analysis Null Propagation

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#22491]
copied from https://developercommunity.visualstudio.com/content/problem/32532/code-analysis-null-propagation.html 

Since the inception of the null propagation operator, code analysis thinks that the Dispose method is not being called. This is a huge problem since I have about 3,000 different object that must be disposed in my project. I cannot determine if I actually am missing one since there are thousands of false positives. Please fix the code analysis to recognize null propagation of the dispose method.

**Comment by jinujoseph** [comment]
This is related to Fxcop Analyzers

**Comment by mavasani** [comment]
Fixed in https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers/2.9.0-beta1-63118-01 and future versions of this package.
