### ISSUE TITLE
Breaking change in taking a "reference" to a method

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#2249]
The following code was accepted by the native C# compiler due to a bug in the handling of the "new delegate" expression. Because Roslyn does not have this bug, the following code is not accepted by the new C# compiler.

```cs
class Program
{
    static void M() { }
    public static void Main(string[] args)
    {
        var a = new System.Action(ref M);
    }
}
```

**Comment by gafter** [comment]
My recommendation is to accept this in Roslyn as a concession to compatibility without any diagnostics, but reject it in "strict" mode (which isn't really publicly supported... yet).

**Comment by gafter** [comment]
Note that "ref methodGroup" does not appear to be supported by the native compiler in any other contexts that I was able to determine. It was an oversight that it was not checked in this one context.

**Comment by MattGertz** [comment]
Needs verification.
