### ISSUE TITLE
Cannot rename list when foreach-ing over a list of tuples

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22495]
From Developer Community: https://developercommunity.visualstudio.com/content/problem/123914/rename-loop-variable-for-list-of-lists-of-tuples.html

Screenshots:
https://developercommunity.visualstudio.com/storage/attachments/13710-renameerror1.png
https://developercommunity.visualstudio.com/storage/attachments/13711-renameerror2.png

**Comment by jcouv** [comment]
The deconstruction-foreach uses specific syntax. I'll take a stab at this.

**Comment by jcouv** [comment]
More details in linked issue.

The screenshot shows that references to `tuples` are not tracked in a deconstruction-foreach:
![image](https://user-images.githubusercontent.com/7252342/32067427-2b9173da-ba51-11e7-893f-ff47d5df1f7a.png)

**Comment by jcouv** [comment]
Fix is merged to post-dev15.5-contrib branch (which I think means it will release in 15.6).
Closing
