### ISSUE TITLE
[LB UX Study]Remove Unnecessary Cast has different behavior between primary single fix and fix all occurences so far as removing unnecessary parens goes

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#225]
Ported from TFS WorkItem: <b>1115010</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P>1. Open attached solution</P>
<P>2. Open MainWindow.xaml.cs</P>
<P>3. Place cursor anywhere on Line 39</P>
<P>4. Hit Ctrl + .</P>
<P>5. Select Fix All Occurences for Remove Unnecessary Cast fix</P>
<P><IMG src="https://cloud.githubusercontent.com/assets/20570/6052826/bad590d8-ac8c-11e4-8313-7f396d79cfdf.png" width=753><BR></P>
<P><STRONG>Actual</STRONG>: Notice extra parens that are not removed</P>
<P><IMG src="https://cloud.githubusercontent.com/assets/20570/6052859/e44e2bd2-ac8c-11e4-832c-09846dff5a4b.png" width=511><BR><BR><STRONG>Expected:</STRONG> Extra parens should be removed - they are correctly removed in the primary (single) fix (see preview pane screenshot above / 'preview changes' screenshot below)</P>
<P>&nbsp;</P>
<P><IMG src="https://cloud.githubusercontent.com/assets/20570/6052874/01944686-ac8d-11e4-8970-8f0b617ea53b.png" width=512><BR></P>
<P>&nbsp;</P>
<P><FONT size=1></FONT>&nbsp;</P>

------------------------------

<p><b>Revisions:</b></p>

1) Created by Shyam Namboodiripad (1/26/2015 3:16:08 PM)

Lower pri - but its interesting that fix all and primary fix can have different behavior...

------------------------------

2) Edited by Mark Wilson-Thomas (1/27/2015 10:03:38 AM)

[Marking up as this was identified by an end user in a usability study]

------------------------------

**Comment by mavasani** [comment]
Test issue for porting TFS issues to GitHub - closing.

**Comment by srivatsn** [comment]
Reactivating this since this issue still needs to be fixed.

**Comment by mavasani** [comment]
Should be fixed now.
