### ISSUE TITLE
Allow resizing the Attach to Process window

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#22503]
For some reason, this window has a fixed size, which makes it inconvenient to look through a long list of processes.

![image](https://user-images.githubusercontent.com/12466233/31150825-f83a0ba0-a849-11e7-9c63-ce13a16178e2.png)

Tagging @caslan @tmat

**Comment by Pilchie** [comment]
Owned by the debugger team - better to file in VSTS.

**Comment by jcouv** [comment]
Moved to https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=504678
