### ISSUE TITLE
Suppressing IDE0034 does not work correctly

### ISSUE THREAD

**Issue by smitpatel** [dotnet/roslyn#22506]
Using same example as in #22505 
Since inference was incorrect, I went ahead to suppress the suggestion in file. I used VS to add code for suppression. 
![image](https://user-images.githubusercontent.com/1528107/31153174-730688c2-a854-11e7-982f-84e2dedcf0d1.png)
Even after adding code for suppression as VS suggested, VS still suggest me the code fix.
![image](https://user-images.githubusercontent.com/1528107/31153202-951d68b8-a854-11e7-871a-5bf24d93b8b1.png)

Interesting, the light bulb no longer suggest it.
![image](https://user-images.githubusercontent.com/1528107/31153214-aa27da22-a854-11e7-9912-44bdfc07c832.png)

**Comment by mavasani** [comment]
This looks like a case of stale suggestion diagnostic not cleared in the IDE. Do you see it in the Error list as well?

**Comment by smitpatel** [comment]
@mavasani - It goes away from Error List window after pragma lines are added.

**Comment by mavasani** [comment]
This seems to be an issue with all of our code style analyzers. We seem to create a separate descriptor/diagnostic for unnecessary fading: http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/CodeStyle/AbstractCodeStyleDiagnosticAnalyzer.cs,54, and the suppression applied to the reported IDE code style diagnostic does not suppress the fading unnecessary diagnostic. Assigning to @sharwell

**Comment by CyrusNajmabadi** [comment]
Doesn't repro for me.  Once we suppress, it's gone:

![image](https://user-images.githubusercontent.com/4564579/217623228-f9591f3b-39e1-4946-a92b-5d79408570d7.png)

**Comment by sharwell** [comment]
This was fixed by #46666
