### ISSUE TITLE
Typing (or overtyping) the close paren of a using statement indents the next line

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22508]
From Developer Community: https://developercommunity.visualstudio.com/content/problem/120244/unexpected-indentation-of-unrelated-code-while-wri.html

There's a longer writeup on Developer Community, but the short version is to use this C# code

```C#
class C
{
    void M()
    {
        int x;
        $$
        int y;
    }
}
```

And type `using (null)` (including overtyping the close paren if you have automatic brace completion enabled)

**Expected** The same behavior as `if` and `for` statements, the next line is not indented.
**Actual** The next line is indented.

**Comment by CyrusNajmabadi** [comment]
closing out for lack of feeback.
