### ISSUE TITLE
Find All References on a definition finds all usages of any implicit interface method and all their implementations

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#22509]
I have a class like the following:

``` C#
    internal class RetrievableEntryHashSet<T> : ICollection<T>, IDictionary<string, T>
    {
        public bool TryGetValue(string key, out T item);
    }
```

I want to find all callers to TryGetValue on this type - because I'm about to make a change and see how they use this method. I right click on this and choose Find All References.

This returns me the following results:

![image](https://user-images.githubusercontent.com/1103906/31154101-88912f20-a8f0-11e7-998e-964078885945.png)

Only the RetrievableEntryHashSet and possible IDictionary<TKey, Value>.TryGetValue usages are actually interesting, all these other usages are noise. If I wanted to see them I would have did a FAR on IDictionary<TKey, TValue>.TryGetValue.

How do I stop FAR from returning these other results?

**Comment by Pilchie** [comment]
Great point - if we do a FAR we should not cascade back down to other concrete implementations of implemented interfaces.

**Comment by justcla** [comment]
I had a similar experience.
I saw a FAR list full of results. None of them were applicable.

**Comment by CyrusNajmabadi** [comment]
This fits into the general problem of "sometimes the user is doing a rename. and they want to see all the potential affected downstream usages of this member, so we have to aggressively cascade".  i.e. if you were to change that name, things would break, unless you also changed the interface method.  And if you changed that, then that would affect all the types implementing that interface method.

--

Now, that said, this experience sucks.  No question.  But the cascading does exist for a very real, and very helpful scenario.  My gut tells me that an appropriate way to handle this would be to allow users to say that they don't care about this (i.e. with a checkbox on the FAR window) to stop cascading.

When i talked with Daofa and the editor team, they were open to the ability for FAR providers to be able to add buttons to the window in a generalized fashion.  but i don't think anything came of that.  If someone wanted to drive it, it wouldn't be hard to then have a new checkbox "Find inheritance matches" and hook it up to the FAR engine.

**Comment by CyrusNajmabadi** [comment]
There was also no way for the provider to flexibly collapse/expand sections in the initial window (not sure if the editor exposed that).  If so, we could ideally place all cascades in a separate group *and* collapse it by default.

This would massively declutter this list, while also making the information available for those who needed it.

**Comment by Pilchie** [comment]
That’s what I was thinking too.

--
Kevin Pilch
http://twitter.com/Pilchie
________________________________

**Comment by CyrusNajmabadi** [comment]
This should be fixed now.  We don't cascade through otehr implementation of hte interface method.  Just up/down that member's hierarchy itself only.
