### ISSUE TITLE
Documentation comment tags conversions get stuck when a cref="System.Int32" is present in the comment.

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#22526]
copied from https://developercommunity.visualstudio.com/content/problem/122710/bug-day-101-documentation-comment-tags-conversions.html

Create a new C# console app.
2. Add a property or method that returns an int.
3. Add a documentation comment with this in the summary:
Returns internal int 5 for this class. Will not be a public, static, string, class, struct, or long. This is just a System.Int32 for MyClass.
4. Put carat over "System.Int32" and follow the suggestion (this should change the comment to see cref="System.Int32")
5. Put the carat over another keyword or class name.
6. Hit Ctrl+.

The only suggestion is to simplify "System.Int32" to "int". I would expect that the other refactorings are available as well.

**Comment by jinujoseph** [comment]
cc @dpoeschl

**Comment by CyrusNajmabadi** [comment]
I don't repro this.
