### ISSUE TITLE
C# "prefer inferred tuple element names" option change is not effective immediately

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#22529]
https://developercommunity.visualstudio.com/content/problem/122804/c-prefer-inferred-tuple-element-names-option-chang.html

I have the following code that shows a suggestion to remove "two:" from the code

var a = new { two = 1 };
var t = (one: 1, two: a.two);

2. Open Tools | Options dialog, locate the "prefer inferred tuple element names" option, and change Severity to Error

3. Click OK button

Actual:
I waited and waited, but eventually had to make a change to the code in order for the suggestion to change to an error.

I didn't check other options, is this behavior by-design?

**Comment by CyrusNajmabadi** [comment]
I don't repro this. I get the suggestion very soon after making the chnage.
