### ISSUE TITLE
Missing file banner refactoring doesn't seem to work

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#22523]
from https://developercommunity.visualstudio.com/content/problem/122691/bug-day-101-missing-file-banner-refactoring-doesnt.html 

Created a new C# dotnet core console app, and added a banner like the following:

/// -=----------
/// This is a banner comment!
/// ------------

to the top of the first two files. Adding a third class does not present me with a refactoring to add a banner comment.

**Comment by jinujoseph** [comment]
related to https://github.com/dotnet/roslyn/issues/22280

**Comment by CyrusNajmabadi** [comment]
This is by design.  Those are explicitly *doc comments* (due to the `///`).   Note that the compiler itself will complain here if you do this, stating:

```XML comment is not placed on a valid language element```
