### ISSUE TITLE
C# "Prefer deconstructed variable declaration" scenario is not working

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#22535]
[View on Developer Community](https://developercommunity.visualstudio.com/content/problem/122815/c-prefer-deconstructed-variable-declaration-scenar.html)
Actual:
1. I could not find the option in the Tools | Options dialog

2. trying the steps in the scenario doesn't show the code action to deconstruct of tuple.

**Comment by CyrusNajmabadi** [comment]
Option is here: 

![image](https://user-images.githubusercontent.com/4564579/75836829-f5875580-5d77-11ea-888f-4262f56b496b.png)

The scenario works for me when i try:

```c#
using System;

class C
{
    (int x, int y) GetPoint() => default;

    void M()
    {
        (int x, int y) point = this.GetPoint();
        Console.WriteLine($"{point.x},{point.y}");
    }
}
```

I get offered:

![image](https://user-images.githubusercontent.com/4564579/75836894-22d40380-5d78-11ea-8509-ec34048af315.png)
