### ISSUE TITLE
Moving variable close to use can add more than one blank line

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#22530]
[View on Developer Community](https://developercommunity.visualstudio.com/content/problem/122728/moving-variable-close-to-use-can-add-more-than-one.html)
Console.WriteLine("Hello World!");

            int a = 10;

            Console.Write("hi");

            int sum = a + 10;

was refactored to 

            Console.WriteLine("Hello World!");
            Console.Write("hi");

            int a = 10;
            int sum = a + 10;

Notice the multiple blank lines which should not be introduced that must now be deleted.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  We get the expected result:

![image](https://user-images.githubusercontent.com/4564579/198751331-7b23422a-32f4-49a3-9742-244b54e94e01.png)
