### ISSUE TITLE
Re-enable CSharpIsAndCastCheckWithoutNameDiagnosticAnalyzer

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22531]
It was disabled by @heejaechang in PR https://github.com/dotnet/roslyn/pull/22532

**Comment by sharwell** [comment]
:memo: This analyzer was disabled due to unexpected performance overhead during testing. We'll re-enable it once the underlying performance problem is addressed.

It also needs to be hooked up to the existing option `PreferPatternMatchingOverIsWithCastCheck` at the same time.
