### ISSUE TITLE
Request:  Find All References broken down by use

### ISSUE THREAD

**Issue by HaloFour** [dotnet/roslyn#22545]
This is a feature supported in Red Gate Reflector that I think would be very useful within Visual Studio.

I'd like to see Find References be able to differentiate between the use of the reference and allow either breaking down the references by their use or isolating a specific use type:

1.  Properties by accessor method (**get** vs. **set**)
    ![image](https://user-images.githubusercontent.com/10102290/31236440-1ae04a7e-a9c2-11e7-823e-3a20e21d39aa.png)

2.  Fields, locals and parameters by whether they are **used** or **assigned**
    ![image](https://user-images.githubusercontent.com/10102290/31236570-72eec498-a9c2-11e7-862a-e36d76644400.png)

3.  Types by where they are **instantiated** (via instance constructor invocation), **exposed** (via non-private field, property or method parameter) or **used**
    ![image](https://user-images.githubusercontent.com/10102290/31236383-ee901f12-a9c1-11e7-8f0e-5601af1cdc59.png)

I am currently working on a project where many fields are exposed as `protected` or as `internal` and are frequently referenced directly by other types.  I am trying to discern where those fields are being mutated and in quite a few cases Find All References is identifying over a 100 direct references of each of those fields, but scanning through the results I might identify only a couple assignments.  Doing this manually is both tedious and very likely error prone.

**Comment by jnm2** [comment]
I want something similar but different. ReSharper has right click > "Find usages advanced..." feature where I can find all usages of a property getter or a property setter or the whole property, which I lean heavily on and would like to see in VS.

**Even more useful** to me would be the same thing for fields: find all reads of a field or all writes of a field. (nameof wouldn't count and `ref` would trigger either. `out` would count as a write.)

**Comment by CyrusNajmabadi** [comment]
> Even more useful to me would be the same thing for fields: find all reads of a field or all writes of a field, but don't show me both at the same time and make me wade through a ton of false positives to get to what I need to see. (nameof wouldn't count and ref would trigger either. out would count as a write.)

We have the data for this internally.  It could be expose as a new column in the VS FAR window.  You could hten use that column to 'group by', as you can with the other columns.

**Comment by jnm2** [comment]
I guess that wouldn't be bad, but say you had four classifications: field write, field read, field readandwrite (or ref), and field metadata (nameof). I can sort them but what I really want to do is filter to one of them. Sorting still means I'm scrolling past dozens of hits I don't care about, though the scanning is much nicer with the new column to look at.

**Comment by HaloFour** [comment]
@CyrusNajmabadi 

That would certainly scratch my immediate itch if that information was available for both fields and properties.

I think that there is value to the other references types, too, particularly those around where a type is exposed or instantiated.  When refactoring a public type, e.g. hiding it behind an interface, it would help to have a quick way to identify where that type might leak out of the assembly.

**Comment by CyrusNajmabadi** [comment]
> I think that there is value to the other references types, too, particularly those around where a type is exposed or instantiated. 

You can get instantiation information simply by looking at the references to the type's constructors (which we automatically cascade to when doing a FindReferences on a type). Is that not sufficient?

**Comment by spottedmahn** [comment]
Related User Voice Request: [Find All assignments](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/6210373-find-all-assignments)

> A feature similar to "Find all references", but only includes assignments.

**Comment by HaloFour** [comment]
@CyrusNajmabadi 

> You can get instantiation information simply by looking at the references to the type's constructors (which we automatically cascade to when doing a FindReferences on a type). Is that not sufficient?

It's alright, but it's not great.  When grouping by definition you can see the constructor invocations but they're all separate from one another.  And it looks like any static member invocation or similar use bubbles up the top of the list above the constructors, so you'd likely have to dig through that first.

**Comment by jnm2** [comment]
Fyi– I made it this far on 15.6 without ReSharper this far, but there's no way I can finish the task I have at hand without going back to ReSharper. I have to look through 223 hits, the overwhelming majority of which are usages of the getter, while the tool window title is `'set_ThisProperty' references`.

**Comment by jnm2** [comment]
This is why I reinstalled ReSharper again the other day.

**Comment by CyrusNajmabadi** [comment]
We have the information in our FindRefs API.  It's here: 
https://github.com/dotnet/roslyn/blob/d4dab355b96955aca5b4b0ebf6282575fad78ba8/src/Workspaces/Core/Portable/FindSymbols/ReferenceLocation.cs#L42

@jnm2 Want to just hook it up to the UI?

**Comment by jnm2** [comment]
Where's the UI source?

**Comment by CyrusNajmabadi** [comment]
https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/FindReferences/StreamingFindUsagesPresenter.cs

**Comment by CyrusNajmabadi** [comment]
Let me know if you have any questions.  Gitter or here work for me.

**Comment by jnm2** [comment]
Cool! It's on my list.

**Comment by jnm2** [comment]
@CyrusNajmabadi So what I really want is more accurate behavior like we've been used to (not to make a big deal of it) with ReSharper. If I ask for all references of a property or event, I want all references of that property or event. If I ask for all references of an accessor method, I only want results for that accessor.

<img src="https://user-images.githubusercontent.com/8040367/36404177-418f2d46-15b7-11e8-9eb1-86eb00dffe8d.png" width="60%" />

<img src="https://user-images.githubusercontent.com/8040367/36404200-5eb8c9b8-15b7-11e8-852c-7c9963d87420.png" width="49%" /> <img src="https://user-images.githubusercontent.com/8040367/36404219-723092dc-15b7-11e8-8e38-6c2ee87f8c6a.png" width="49%" />

Don't worry though; if you aren't searching from the definition of the accessor, you won't accidentally search for an accessor when you meant to search for a property:

<img src="https://user-images.githubusercontent.com/8040367/36404383-48974fbe-15b8-11e8-8dd3-19d74dd65ac4.png" width="49%" />

Along the way I discovered that searching for an event accessor is broken.

<img src="https://user-images.githubusercontent.com/8040367/36404334-0512a89c-15b8-11e8-992a-dce9fc78305a.png" width="60%" />

This does not preclude the possibility of adding a reference classification column. I'd want this accessor-level search precision to be added either way.

Implementation (need to figure out tests): https://github.com/jnm2/roslyn/tree/find_only_accessor

Do you have suggestions?

**Comment by CyrusNajmabadi** [comment]
One way this would work IMO, would be to actually not have the properties, or references to it.  Instead, just cascade between the accessors and give results corresponding to both.  You would always get all of them.  but if you only wanted one you would just not collapse the getters (or setters) group.

**Comment by CyrusNajmabadi** [comment]
Actually, probably scratch that suggestion.  this is similar to how we do NamedTypes vs. Constructors.  If you search for the named-type, you get all references (including references to them in consturctor calls).  but if you do a FAR for a constructor, you just find references to that constructor.  

So we should likely do the same here.  THe property should cascade to the accessors.  The accessor shoudl not cascade to the property.  Note: i perused the code, and it looks like that might be what is already happening.  So it's possible some other part of the process is mapping accessors to properties.

**Comment by jinujoseph** [comment]
related to https://github.com/dotnet/roslyn/issues/24877

**Comment by mavasani** [comment]
I believe the primary request here has been addressed by https://github.com/dotnet/roslyn/pull/30155. 

![image](https://user-images.githubusercontent.com/10605811/46490084-dd468c00-c7bb-11e8-9a39-5d46aeca53fd.png)

New FAR column allows classification, sorting, filtering, etc. by reference kind (this will show up in Dev16 Preview2)

@HaloFour Does this meet your request?

**Comment by HaloFour** [comment]
@mavasani 

That looks really nice and solves most of my use cases!

**Comment by jinujoseph** [comment]
@jnm2 does #30155 addresses your requirement

**Comment by jnm2** [comment]
@jinujoseph tl;dr yes.

https://github.com/dotnet/roslyn/pull/28231 addresses what I was asking for in this thread, summarized in the pictures here: https://github.com/dotnet/roslyn/issues/22545#issuecomment-366847223. That's for when I know I want the getter or the setter and nothing else.

https://github.com/dotnet/roslyn/pull/30155 addresses rarer (but just as cool) scenarios: field usages, and searches when I don't know ahead of time that I only want to see one accessor of a property.

**Comment by jnm2** [comment]
@mavasani Super unimportant, but is `NameOnly` going to show up pascal cased in the final UI?

**Comment by mavasani** [comment]
> Super unimportant, but is NameOnly going to show up pascal cased in the final UI?

This is how it has been checked in, but we can surely make a change if it seems appropriate.

**Comment by jinujoseph** [comment]
Thanks for the confirmation @jnm2 
I will go-ahead and close this issue (refer #28231 & #30155 ) 
If there are more improvements to be made on top of the current experience , pls feel free to file an issue

**Comment by jnm2** [comment]
@mavasani It seems like a leaking implementation detail ("look, we used an enum"). I think the style guide for UI elements is sentence casing.

(**UI text** section in https://docs.microsoft.com/style-guide/text-formatting/formatting-common-text-elements, sections in https://docs.microsoft.com/style-guide/procedures-instructions/formatting-text-in-instructions.)

**Comment by CyrusNajmabadi** [comment]
@jnm2 is right. this should be one of:

1. 'Name'
2. 'Name only'
3. 'Name Only'

it def should not be NameOnly :)

**Comment by jnm2** [comment]
\*I pay attention now that your PR is closed (sorry about that 😳)

**Comment by jinujoseph** [comment]
@jnm2 no worries , we can address this as a follow-up PR
