### ISSUE TITLE
Implement Function Breakpoint Binding

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#2254]
This is the last _normal_ desktop debugging scenario that still relies on cscompee.dll...

**Details for implementing IDkmRuntimeFunctionResolver**
- The Enable method on IDkmRuntimeFunctionResolver is called once for each function to be resolved.
- The argument is a DkmRuntimeFunctionResolutionRequest which includes string FunctionName and optional string ModuleName.
- The Resolver will store the Request instances in a DkmDataItem attached to a container such as the DkmProcess. (The DkmDataItem should be immutable so no locking is required in the Resolver.)
- The Resolver will listen for module loaded events and when a module is loaded, will attempt to resolve all functions, and for any function that can be resolved, will call OnFunctionResolved on the corresponding Request with the resolved DkmInstructionAddress.

**Comment by Pilchie** [comment]
Note that the old EE doesn't handle this properly for async methods (though it does for iterator methods).  We should fix that when we do this.

**Comment by amcasey** [comment]
Once this is fixed, confirm that function breakpoints work for {C#, VB} x {async, iterator}.

**Comment by plnelson** [comment]
@KevinH-MS  Assuming you are implementing this on the IDE side, the interface you'll want to implement is `IDkmSymbolFunctionResolver`.  I noticed that the EE shim for cscompee is using `IDkmRuntimeFunctionResolver` and that's why I initially suggested it, but it turns out that one is intended for EEs that are implemented on the remote side.  I can help with this more when you are ready to implement it.

**Comment by KevinH-MS** [comment]
Customer feedback:  If it isn't supported by C# already, it would be good to support basic wildcard regex matching in C# ("SomeClass.*" to match all strings beginning with "SomeClass.", etc).

**Comment by ManishJayaswal** [comment]
Assigning to @cston to take a look.

**Comment by ManishJayaswal** [comment]
@cston can this be closed now?
