### ISSUE TITLE
Request: Find References support for specific property accessor method

### ISSUE THREAD

**Issue by HaloFour** [dotnet/roslyn#22543]
Currently if you highlight a specific accessor for a property and select Find References it will find all of the references for the property regardless of which accessor is invoked.  I'd like for the feature to be able to isolate only the references for the selected accessor method.  This would be helpful in use cases such as identifying specifically where a property is being mutated.

Interestingly, if you do select a specific accessor, the title of the window for the results will show the name of the accessor method, not of the property.

![image](https://user-images.githubusercontent.com/10102290/31234984-4636a1cc-a9be-11e7-819a-a70e2f29af2f.png)

**Comment by Pilchie** [comment]
Similar to https://github.com/dotnet/roslyn/issues/17684.

**Comment by CyrusNajmabadi** [comment]
@HaloFour The FindReferences UI now allows you to see (and group-by) what type of reference this was.  i.e.:

![image](https://user-images.githubusercontent.com/4564579/75836738-aa6d4280-5d77-11ea-8bfa-6bfc36871d66.png)

Is that sufficient for your needs?

**Comment by HaloFour** [comment]
Yes, I think that will be very handy.

**Comment by CyrusNajmabadi** [comment]
Thanks!
