### ISSUE TITLE
A small usability tweak for F2 - Automatically discard surrounding whitespace in requested new name

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#22544]
**Version Used**: 

Visual Studio 2017 - 15.3.5

**Steps to Reproduce**:

1. Hit F2 to rename an identifier.
2. Compose the new name I want into notepad. (Editorial: I <b>vastly</b> preferred the old UI that gave you a regular edit box.)  
3. Absently-mindedly hit ENTER because ... muscle memory.
4. Hit Ctrl-A, Ctrl-C (select ALL, copy into clipboard.)
5. Switch back to VS, hit Ctrl-V (paste)
6. VS errors out "Invalid identifier" due to newline at the end
7. Me [bangs table]: "It's blatantly obvious what I meant. DWIM and call Trim() already."

**Expected Behavior**:

Just call Trim() on the string.

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
Closing otu given lack of feedback.
