### ISSUE TITLE
IOperation tests have lots of trailing whitespace

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#22556]
With https://github.com/dotnet/roslyn/pull/22309 moving lots of tests to have output on multiple lines, the test were not adjusted to not have trailing whitespace. So now a lot of our tests have trailing whitespace inside the strings, usually after lines that had both a header and value on the same line. These should be updated to not have trailing whitespace.

**Comment by mavasani** [comment]
Tracked with https://github.com/dotnet/roslyn/issues/22559
