### ISSUE TITLE
Extract method on local function is incorrect

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#22550]
**Version Used**: 
```
Microsoft Visual Studio Professional 2017 
Version 15.3.5
VisualStudio.15.Release/15.3.5+26730.16
Microsoft .NET Framework
Version 4.7.02046
```

**Steps to Reproduce**:

Extract local function invocation in the following code:

```cs
class C
{
  static void Main(string[] args)
  {
    void Local() { }
    Local(); // this line
  }

  static void Local() => System.Console.WriteLine("changed");
}
```

**Expected Behavior**:
Either semantically equivalent code or conflict.

**Actual Behavior**:

Roslyn produces code that doesn't have any compilation errors but behave differently. This kind of change could be easily overlooked when extracting a big chunk of code.
```cs
class C
{
  static void Main(string[] args)
  {
    void Local() { }
    NewMethod();
  }

  private static void NewMethod()
  {
    Local();
  }

  static void Local() => System.Console.WriteLine("changed");
}
```

**Comment by jcouv** [comment]
FYI @agocke

**Comment by cdie** [comment]
I have an example that in fact does break compilation. Here's some dummy code to demonstrates what is going wrong:

``` 
class Program
    {
        static void Main(string[] args)
        {
            var list = new List<LittleObject>();
            list.Add(new LittleObject { AValue = "a" });

            var firstA = list.FirstOrDefault(o => o.AValue == "a");
            if(firstA != null)
            {
                //Extract from here
                bool areEquals(LittleObject a, LittleObject b)
                {
                    return a.AValue == b.AValue;
                };

                var secondA = list.FirstOrDefault(o => areEquals(o, firstA));
                //To here
            }

        }
    }


    class LittleObject
    {
        public string AValue { get; set; }
    }
```
It gives inconsistent extraction and create a method that doesn't have neither list or firstA as parameter, and does break compilation.
Issue is created on VS dev community, that refer this thread 
https://developercommunity.visualstudio.com/content/problem/148551/extract-method-give-inconsistents-results.html

**Comment by agocke** [comment]
I believe that the parent issue is a consequence of https://github.com/dotnet/roslyn/issues/21975

**Comment by jinujoseph** [comment]
also referred at [DC](https://developercommunity.visualstudio.com/content/problem/373164/c-extract-method-doesnt-pass-local-function.html)

**Comment by CyrusNajmabadi** [comment]
This is fixed.  Will add demonstrative test and close.
