### ISSUE TITLE
Deconstruct Tuple Declaration is missing from 15.5 Preview 1

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22551]
**Version Used**:  15.5.0 Preview 1.0 [26927.1.d15rel]

This feature was introduced in https://github.com/dotnet/roslyn/pull/21870. The commits from that PR are present in the expected branches, including `dev15.5.x`, `dev15.5-preview1`, `dev15.5-preview1-staging`, and the code itself is in those branches as well (it does not appear to have been reverted or disabled). It does not appear in the 15.5 Preview 1 VS build listed above (neither the lightbulb entry nor the option in Tools | Options). It _does_ appear in the RoslynDev hive for the current `master` sources. I have not yet tried with `dev15.5-preview1` sources.

**Steps to Reproduce**:

1. C#:
```C#
using System;
class C
 {
     void M()
     {
         var t1 = GetPerson();
         Console.WriteLine(t1.name + " " + t1.age);
     }

    (string name, int age) GetPerson() => default;
 }
```

2. Make all the squiggles go away by upgrading the C# version, installing System.ValueTuple, etc.
3. Ctrl+. on the declaration of `t1`

**Expected Behavior**: "Deconstruct variable declaration" (or something like that) appears in the lightbulb.
**Actual Behavior**: It does not appear.

**Alternate Steps to Reproduce**: Just check for the presence of the option under Tools | Options | Text Editor | C# | Code Style | General | Variable preferences | Deconstruct tuple declaration (something like that)

**Comment by dpoeschl** [comment]
> I have not yet tried with dev15.5-preview1 sources.

@chborl is trying this now

**Comment by dpoeschl** [comment]
FYI @jasonmalinowski @jinujoseph -- this is a checked in feature from 20 days ago, the code for which is present in the expected branches, that isn't appearing in the product in dogfooding. We don't know why yet.

**Comment by chborl** [comment]
I confirmed that it's working in RoslynDev using the dev15.5-preview1 sources.

**Comment by dpoeschl** [comment]
`C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\CSharp.Features.dll` does not contain the CodeFix on my `15.5.0 Preview 1.0 [26927.1.d15rel]` machine. @jasonmalinowski Any idea what could have gotten out of sync between the `dev15.5-preview1` sources (where it works) and the installed `CSharpFeatures.dll` in my 15.5 Preview 1 VS?

**Comment by dpoeschl** [comment]
Probably should have tagged @dotnet/roslyn-infrastructure instead of Jason directly. Any ideas?

**Comment by jasonmalinowski** [comment]
@dpoeschl What's the version string for that binary on your machine?

**Comment by jasonmalinowski** [comment]
I looked at this with @chborl: the 26927.1.d15rel build contains Roslyn code built roughly on the 14th. Later d15rel builds have a newer insertion that will contain the code.
