### ISSUE TITLE
ref and readonly structs should be displayed in IDE

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#22564]
For both types, quickinfo and symbol display should be able to hint if they're annotated with `ref` and `readonly` keywords or not.

**Current behavior:**

![image](https://user-images.githubusercontent.com/15987992/31255870-0a4f2000-a9e4-11e7-89e2-2f5b153dce6e.png)

@VSadov 's comment on #19421 

> After working with actual ref structs, I am convinced that ref must be surfaced in the symbol display.
> When chasing through an escape violation, it would be useful to know which types are ref structs and which are not.
> Also consider "readonly". It may be useful too, but also longer...

**Comment by VSadov** [comment]
Definitely want to show “ref”.

**Comment by OmarTawfik** [comment]
@VSadov my understanding is that we would want to show both. Correct?
