### ISSUE TITLE
Investigate weird syntax associated with initializer and initializer value

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22575]
See https://github.com/dotnet/roslyn/pull/22546#discussion_r143043591

>= New C2() ... lo World!"} [](start = 80, length = 27)

It looks like the syntax node is correct, but why the string is truncated before the With and doesn't include any indication of truncation?

**Comment by jinujoseph** [comment]
Verify and close

**Comment by mavasani** [comment]
Seems that just the output from the dumper truncates middle characters if syntax is longer then certain limit. Not sure if it is worth fixing the dumper format here.
