### ISSUE TITLE
Incorrect overload resolution when local function has the same name as the enclosing method

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/roslyn#22572]
**Version Used**: VS2017 15.3.3

**Steps to Reproduce**:

1. Write the following method:

```csharp
private static bool IsRetryableError(Exception ex)
{
    switch (ex)
    {
        case WebException webEx when IsRetryableError(webEx.Status):
        case SocketException _:
        case TimeoutException _:
        case IOException _:
            return true;
    }

    if (ex.InnerException != null)
    {
        return IsRetryableError(ex.InnerException);
    }

    return false;

    bool IsRetryableError(WebExceptionStatus status)
    {
        switch (status)
        {
            case WebExceptionStatus.ConnectFailure:
            case WebExceptionStatus.SendFailure:
            case WebExceptionStatus.ReceiveFailure:
            case WebExceptionStatus.ConnectionClosed:
            case WebExceptionStatus.NameResolutionFailure:
            case WebExceptionStatus.ProxyNameResolutionFailure:
            case WebExceptionStatus.Timeout:
                return true;
        }

        return false;
    }
}
```

2. Build

**Expected Behavior**:

The code should compile without error.

**Actual Behavior**:

The compiler emits an error on `IsRetryableError(ex.InnerException)`:

> error CS1503: Argument 1: cannot convert from 'System.Exception' to 'System.Net.WebExceptionStatus'

The recursive call doesn't compile, because the current method is hidden by the local function with the same name. I would have expected overload resolution to work as usual. Is this the intended behavior?

**Comment by HaloFour** [comment]
Given that local functions cannot be overloaded within a method I doubt that they can participate with overloading with other members of the current type.  By using the same name you're effectively shadowing the members which would require that you qualify the function with `this` or the type name.

**Comment by gafter** [comment]
Since the local function is in a different scope than the enclosing method, it shadows it rather than overloading with it. That is intended behavior.

**Comment by thomaslevesque** [comment]
@gafter, thanks for the clarification
