### ISSUE TITLE
CA1821CodeFixProvider should remove finalizer blocks not their MethodStatementSyntax nodes

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#2257]
Ported from TFS WorkItem: <b>945285</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P><B>Affected Branch:</B> $/Roslyn/Main<BR><B>Affected Product Language:</B> VB<BR></P>
<P>The syntax node remover fails because CA1821CodeFixProvider just tries to remove "nodeToFix", the node that it thinks the diagnostic was associated with in both VB and C#.&nbsp; There needs to be specific logic for VB to make sure we remove the finalizer MethodBlockSyntax because the syntax node remover API will fail if we pass it a MethodStatementSyntax. (according to Matt Warren)</P>
<P><BR><B>Steps to reproduce:</B><BR>1. Enable break on System.NullReferenceException (from Debug-&gt;Exceptions menu)</P>
<P><BR>2. Run&nbsp; </P>
<P style="FONT-SIZE: 12pt; FONT-FAMILY: Calibri; MARGIN: 0in"><FONT size=2 face="Segoe UI">Roslyn.DiagnosticFixers.UnitTests:CA1821FixerTests:CA1821BasicCodeFixTestRemoveEmptyFinalizers</FONT></P>
<P style="FONT-SIZE: 12pt; FONT-FAMILY: Calibri; MARGIN: 0in"><FONT size=2 face="Segoe UI">with the debugger.</FONT></P>
<P style="FONT-SIZE: 12pt; FONT-FAMILY: Calibri; MARGIN: 0in"><FONT size=2 face="Segoe UI">This is a test which eventually calls Microsoft.CodeAnalysis.SyntaxNodeExtensions.RemoveNode on a finalizer node.</FONT></P>
<P style="FONT-SIZE: 12pt; FONT-FAMILY: Calibri; MARGIN: 0in"><FONT size=2 face="Segoe UI"></FONT>&nbsp;</P>
<P style="FONT-SIZE: 12pt; FONT-FAMILY: Calibri; MARGIN: 0in"><FONT size=2 face="Segoe UI">3. Step out of the Visit() method</FONT></P>
<P style="FONT-SIZE: 12pt; FONT-FAMILY: Calibri; MARGIN: 0in"><FONT size=2 face="Segoe UI"></FONT>&nbsp;</P>
<P style="FONT-SIZE: 12pt; FONT-FAMILY: Calibri; MARGIN: 0in"><FONT size=2 face="Segoe UI">4.&nbsp;You should now be in&nbsp;Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMethodBlock, and newBegin is set to Nothing because it is to be removed.&nbsp; This is a problem because the method proceeds to create a new MethodBlockSyntax which tries to access members of newBegin.&nbsp; So I'm under the impression that Microsoft.CodeAnalysis.SyntaxNodeExtensions.RemoveNode() does not work correctly and that it is not the fault of the test.</FONT></P>
<P style="FONT-SIZE: 12pt; FONT-FAMILY: Calibri; MARGIN: 0in">&nbsp;</P>
<P><STRONG>Stack trace</STRONG>:</P>
<P>&nbsp;</P>
<P>&gt;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMethodBlock(Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodBlockSyntax node) Line 4996&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodBlockSyntax.Accept(Of Microsoft.CodeAnalysis.SyntaxNode)(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor(Of Microsoft.CodeAnalysis.SyntaxNode) visitor) Line 13795&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor(Of Microsoft.CodeAnalysis.SyntaxNode).Visit(Microsoft.CodeAnalysis.SyntaxNode node) Line 3075&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxNodeRemover.SyntaxRemover.Visit(Microsoft.CodeAnalysis.SyntaxNode node) Line 110&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement(Of Microsoft.CodeAnalysis.VisualBasic.Syntax.StatementSyntax)(Microsoft.CodeAnalysis.VisualBasic.Syntax.StatementSyntax node) Line 83&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList(Of Microsoft.CodeAnalysis.VisualBasic.Syntax.StatementSyntax)(Microsoft.CodeAnalysis.SyntaxList(Of Microsoft.CodeAnalysis.VisualBasic.Syntax.StatementSyntax) list) Line 62&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitClassBlock(Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax node) Line 4714&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept(Of Microsoft.CodeAnalysis.SyntaxNode)(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor(Of Microsoft.CodeAnalysis.SyntaxNode) visitor) Line 10931&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor(Of Microsoft.CodeAnalysis.SyntaxNode).Visit(Microsoft.CodeAnalysis.SyntaxNode node) Line 3075&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxNodeRemover.SyntaxRemover.Visit(Microsoft.CodeAnalysis.SyntaxNode node) Line 110&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement(Of Microsoft.CodeAnalysis.VisualBasic.Syntax.StatementSyntax)(Microsoft.CodeAnalysis.VisualBasic.Syntax.StatementSyntax node) Line 83&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList(Of Microsoft.CodeAnalysis.VisualBasic.Syntax.StatementSyntax)(Microsoft.CodeAnalysis.SyntaxList(Of Microsoft.CodeAnalysis.VisualBasic.Syntax.StatementSyntax) list) Line 62&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitCompilationUnit(Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax node) Line 4519&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept(Of Microsoft.CodeAnalysis.SyntaxNode)(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor(Of Microsoft.CodeAnalysis.SyntaxNode) visitor) Line 8971&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor(Of Microsoft.CodeAnalysis.SyntaxNode).Visit(Microsoft.CodeAnalysis.SyntaxNode node) Line 3075&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxNodeRemover.SyntaxRemover.Visit(Microsoft.CodeAnalysis.SyntaxNode node) Line 110&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxNodeRemover.RemoveNodes(Of Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode)(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode root, System.Collections.Generic.IEnumerable(Of Microsoft.CodeAnalysis.SyntaxNode) nodes, Microsoft.CodeAnalysis.SyntaxRemoveOptions options) Line 19&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode.RemoveNodesCore(System.Collections.Generic.IEnumerable(Of Microsoft.CodeAnalysis.SyntaxNode) nodes, Microsoft.CodeAnalysis.SyntaxRemoveOptions options) Line 629&nbsp;Basic<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.SyntaxNodeExtensions.RemoveNode&lt;Microsoft.CodeAnalysis.SyntaxNode&gt;(Microsoft.CodeAnalysis.SyntaxNode root, Microsoft.CodeAnalysis.SyntaxNode node, Microsoft.CodeAnalysis.SyntaxRemoveOptions options) Line 262&nbsp;C#<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.FxCopDiagnosticFixers.dll!Microsoft.CodeAnalysis.FxCopAnalyzers.Performance.CA1821CodeFixProviderBase.GetUpdatedDocumentAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.SemanticModel model, Microsoft.CodeAnalysis.SyntaxNode root, Microsoft.CodeAnalysis.SyntaxNode nodeToFix, string diagnosticId, System.Threading.CancellationToken cancellationToken) Line 26&nbsp;C#<BR>&nbsp;&nbsp;Microsoft.CodeAnalysis.FxCopDiagnosticFixers.dll!Microsoft.CodeAnalysis.FxCopAnalyzers.CodeFixProviderBase.Microsoft_CodeAnalysis_CodeFixes_ICodeFixProvider_GetFixesAsync(System.Threading.CancellationToken cancellationToken, System.Collections.Generic.IEnumerable&lt;Microsoft.CodeAnalysis.Diagnostic&gt; diagnostics, Microsoft.CodeAnalysis.Document document) Line 32&nbsp;C#<BR>&nbsp;&nbsp;Roslyn.DiagnosticFixers.UnitTests.dll!Microsoft.CodeAnalysis.UnitTests.DiagnosticFixerTestBase.VerifyFix(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Diagnostics.IDiagnosticAnalyzer analyzer, Microsoft.CodeAnalysis.CodeFixes.ICodeFixProvider codeFixProvider, string newSource, int? codeFixIndex, bool useCompilerAnalyzerDriver) Line 52&nbsp;C#<BR>&nbsp;&nbsp;Roslyn.DiagnosticFixers.UnitTests.dll!Microsoft.CodeAnalysis.UnitTests.DiagnosticFixerTestBase.VerifyFix(string language, Microsoft.CodeAnalysis.Diagnostics.IDiagnosticAnalyzer analyzer, Microsoft.CodeAnalysis.CodeFixes.ICodeFixProvider codeFixProvider, string oldSource, string newSource, int? codeFixIndex) Line 33&nbsp;C#<BR>&nbsp;&nbsp;Roslyn.DiagnosticFixers.UnitTests.dll!Microsoft.CodeAnalysis.UnitTests.DiagnosticFixerTestBase.VerifyBasicFix(string oldSource, string newSource, int? codeFixIndex) Line 26&nbsp;C#<BR>&nbsp;&nbsp;Roslyn.DiagnosticFixers.UnitTests.dll!Microsoft.CodeAnalysis.UnitTests.CA1821FixerTests.CA1821BasicCodeFixTestRemoveEmptyFinalizers() Line 54&nbsp;C#<BR></P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By Nate Slottow (5/13/2014 5:21:20 PM)

------------------------------

**Comment by natidea** [comment]
Running the test in the debugger, I no longer see the NullReferenceException
