### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpGoToDefinition.GoToDefinitionWithMultipleResults Failure

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#22577]
Failed in dev15.5-preview1-staging. https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.5-preview1-staging/job/windows_debug_vs-integration/5/
```
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpGoToDefinition.GoToDefinitionWithMultipleResults
      Assert.Collection() Failure
      Collection: []
      Expected item count: 2
      Actual item count:   0
      Stack Trace:
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpGoToDefinition.cs(87,0): at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpGoToDefinition.GoToDefinitionWithMultipleResults()
```
![image](https://user-images.githubusercontent.com/2371880/31287690-ee1f4cf0-aa76-11e7-9b30-6dbdf7130550.png)

**Comment by CyrusNajmabadi** [comment]
Closing out as we ahven't seen additional failures here in years, and we have a system now that tracks bug flakeyness for this.
