### ISSUE TITLE
Revisit logic for implicit variable initializer operation in C#

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22574]
See https://github.com/dotnet/roslyn/pull/22546#discussion_r143105657. This code path sets variable initializer operation as implicit if there is no explicit initializer syntax (equals value clause). Either confirm that this can happen for error cases by adding a unit test OR remove the code path that sets isImplicit = true.

**Comment by AlekseyTs** [comment]
I think we should keep defensive code.

**Comment by mavasani** [comment]
Changed the code to have a Debug.Fail instead - closing this issue.
