### ISSUE TITLE
Should we expose receiver when accessing shared member through instance in VB

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#22585]
In VB, access of shared member through an instance is not an error, but the qualifying expression will not be evaluated in this case. We currently explicitly dropped the receiver for IRaiseEventStatement when the event is shared. (there might be other places do this as well). 

See https://github.com/dotnet/roslyn/pull/22243#discussion_r143186598

**Comment by jinujoseph** [comment]
**Design Team Decision**

Make sure to not drop the instance for static member reference, since we are already ignoring operation like type references
