### ISSUE TITLE
fix IArgument and IArrayInitializer to have null types

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22581]
See https://github.com/dotnet/roslyn/pull/22546#issuecomment-334824971

**Comment by mavasani** [comment]
Adding this assert caused lot of tests to fail - which likely means hidden bugs. We should try to add this assert and investigate failures asap.

**Comment by mavasani** [comment]
It seems the following IOperations have non-null types:

1) IArgument
2) IArrayInitializer
3) PlaceHolderExpression, whose OperationKind is None as we internalized IPlaceHolderExpression.

Skipping these 3 node types allows us to add the above assert.

**Comment by mavasani** [comment]
@jinujoseph marking this for discussion so we can decide if this is expected or we need any product changes here.

**Comment by jinujoseph** [comment]
**Design Team Decision** 

We need to to fix IArgument and IArrayInitializer 
for PlaceHolderExpression we can handle none for now.
