### ISSUE TITLE
Code folding disappears in ASMX files

### ISSUE THREAD

**Issue by iam3yal** [dotnet/roslyn#22583]
**Version Used**: Visual Studio 2010, 2013, 2015, 2017

**Steps to Reproduce**:

1. Create a new Web Forms project.
2. Create a new ASMX file or just copy the following:

```
<%@ WebService Language="C#" Class="Services.Basket" %>

using System.Web.Services;
using System.Web.Script.Services;

namespace Services
{
	[ScriptService]
	public class Basket
	{
		public Basket()
		{
		}
		
		[WebMethod(EnableSession = true)]
		public string Add(int id)
		{
            return null;
		}

        #region Awesome

        #endregion
	}
}
```

**Expected Behavior**: Code folding shouldn't disappear.

**Actual Behavior**: 
Code folding disappears immediately or after few seconds, occasionally it disappears after few minutes but from my tests it's rare so you should reproduce that fairly easily.

The problem with this issue is that it's even worse for people that rely on regions because when it disappears the region expands.

**Comment by CyrusNajmabadi** [comment]
@ryanbrandenburg is this still an issue with the lsp razor editor?  Or can this be closed out?

**Comment by ryanbrandenburg** [comment]
https://github.com/dotnet/razor/issues/7942 is still open for Razor, but between the fact that this says WebForms and the reference to "asmx files" I don't think this issue is connected to that issue, or Razor in general.

**Comment by CyrusNajmabadi** [comment]
Closing out as external to roslyn.
