### ISSUE TITLE
Visual Studios 2013 Roslyn code Extension Exception: Could not load file or assembly Microsoft.VisualStudio.LanguageServices Version 1.3.1.0

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#22596]
**Version Used**: 
1.3.1.0
Visual Studios 2013

**Steps to Reproduce**:

1. We want to get a reference to the current solution in a solution opened using Visual Studios 2013. 
2. For this purpose, we are creating a Visual Studios 2013 Extension Project.
3. In the extension project, we use following  code to get a reference to the current solution:
```
var componentModel =                  (IComponentModel)Microsoft.VisualStudio.Shell.Package.GetGlobalService(typeof(SComponentModel));

VisualStudioWorkspace workspace = componentModel.GetService<VisualStudioWorkspace>();

Solution solution = workspace.CurrentSolution;
```
4. We have added a nugget reference to **Microsoft.VisualStudio.LanguageServices** Version **1.3.1.0**. 
This package installs the required **Microsoft.CodeAnalysis** Version **1.3.1.0** and other required packages.
5. When we run the Extension project in debug mode or installed mode and when the code flow reaches the above code lines, we get an exception **Could not load file or assembly Microsoft.VisualStudio.LanguageServices** Version **1.3.1.0**.

Note: 
1. My assumption is that the base version of Roslyn for plugin code to work in VS 2013 context is version 1.3.1.0. May be my assumption could be a problem and we probably would require further older version. But I am not sure about it.
2. I have checked if the dlls emitted with the .vsix package have the required version and it looks all good.

**Expected Behavior**:
The above code should work and return the reference to the current solution successfully.

**Actual Behavior**:
Exception: Could not load file or assembly 'Microsoft.VisualStudio.LanguageServices, Version=1.3.1.0' or one of its dependencies. The system cannot find the file specified.

**Comment by Pilchie** [comment]
Roslyn is not part of VS 2013 - there is no support for it there.

**Comment by sharwell** [comment]
More specifically, Roslyn 1.x corresponds to the Visual Studio 2015 releases. The minor version number indicates the update, so Roslyn 1.3 would be Visual Studio 2015 Update 3.

**Comment by abhijitparkhi1983** [comment]
Thanks @Pilchie  and @sharwell  for the inputs.

I understand that Roslyn is now not supported for VS2013. But if i remember it right, Roslyn was introduced with a support to VS 2013. 

I need to get the reference to the current Solution using a extension for VS 2013. Is there any other mechanism, some hack, some different approach to do so? 
I can then pass on this solution object to the Code which I have which has the latest Roslyn Version. My only intention is to get a reference to Solution object in the plugin for VS 2013.

A pointer in this direction would be very very helpful.

**Comment by sharwell** [comment]
@abhijitparkhi1983 There is a relatively obscure build (unsupported pre-release) of Roslyn which was available for a short time with Visual Studio 2013. If you build against [that version of Roslyn](https://www.nuget.org/packages/Microsoft.CodeAnalysis/0.6.4033103-beta), you can obtain a `Solution` from a `ITextBuffer` using [this code sequence](https://github.com/tunnelvisionlabs/InheritanceMargin/blob/102eaca2d5a0c3a387711339d16024c77c48b82d/Tvl.VisualStudio.InheritanceMargin.CSharp/CSharpInheritanceAnalyzer.cs#L303-L312). To my knowledge, **you cannot mix this instance** with a later release of Roslyn within the Visual Studio 2013 environment. Note that the code sequence requires a build of **Microsoft.CodeAnalysis.EditorFeatures.Text** which is not available through NuGet, but I have a copy in my Inheritance Margin extension [here](https://github.com/tunnelvisionlabs/InheritanceMargin/blob/master/Reference/Microsoft.CodeAnalysis.EditorFeatures.Text.dll).

**Comment by abhijitparkhi1983** [comment]
@sharwell thanks.

Will try out the above approach. But ya if we cannot mix this instance of solution with later releases of Roslyn, it will be a kind of blocker.

Is there any other way in which can achieve  this in some way?
We have a situation where we have a plugin support working for VS 2015 and VS 2017. But there are couple of people who strongly want a plugin support for VS 2013.

**Comment by sharwell** [comment]
@abhijitparkhi1983 There is no situation in which a Roslyn-based extension running within a Visual Studio 2013 environment is supported. I'm not saying it can't be done, but you are definitely going to be fighting a steep uphill battle likely all on your own.

**Comment by abhijitparkhi1983** [comment]
@sharwell 

Ya i understand. Let me try out with things you have mentioned. Thanks a lot
