### ISSUE TITLE
Inappropriate generation of CS 1612

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/roslyn#22592]
**Version Used**: 
Visual C# 2017 - 00369-60000-00001-AA549

**Steps to Reproduce**:
Unfortunately this error can be inappropriately generated when assigning to a property (i.e. invoking a property setter). An immutable struct can still have a valid property setter, as long as the property setter doesn't actually assign to any fields in the struct. For example, 

```csharp
   public struct Relay { 
       public Relay(Func<string> getText, Action<string> setText) 
       { 
               this.GetText = getText; 
               this.SetText = setText; 
       } 
       private readonly Func<string> GetText; 
       private readonly Action<string> SetText; 
       public string Text { 
           get { return this.GetText(); } 
           set { this.SetText(value); } 
       } 
   } 
   class Example { 
       private Relay Relay { 
           get { return new Relay(() => this.text, t => { this.text = t; });  } 
       } 
       private string text; 
       public Method() { 
           var r = new Relay(); 
           r.Text = "hello"; // not a compile error (although there is a null reference) 
           this.Relay.Text = "hello";  // error 1612 inappropriately generated by the compiler 
           r = this.Relay; 
           r.Text = "hello"; // no compiler error is generated, and none would be appropriate
   } 
```

**Expected Behavior**:
See above. The compiler error should only be generated when a field in the struct is going to be assigned, not when a property is being assigned. 

**Actual Behavior**:
The compiler error is generated when assigning to a property, not only a field.

**Comment by svick** [comment]
Since property setters *very often* write the value to a field and the compiler has no way of knowing whether it does so, I think producing the error makes sense: If the error was not produced, it would be too easy to write buggy code.

This means that in the rare, but valid cases where the property setter does not write to a field, you have to work around this by creating a local variable. I think that's a cost that's worth paying.

**Comment by sjb-sjb** [comment]
I would suggest making cs1612 be a warning rather than an error. This would draw the situation to the programmers attention, preventing buggy code, but still allow the compiler to compile perfectly valid code. The warning at least can be suppressed by the programmer where appropriate; with an error you are stuck. 

It doesn't make sense to have valid code that the compiler refuses to compile simply because some other programmers might not be aware of what they are doing. A warning makes more sense. 

I don't agree with working around it using a temporary variable. First of all this is creating ugliness in user code to make up for a compiler deficiency. But in addition it is not always possible for the programmer to introduce the temporary variable, because the programmer may not have control over how the struct use -- for example in binding scenarios or possibly in generics, where the context of usage cannot be easily changed to introduce a temporary variable. 


Sent from my iPhone

**Comment by sharwell** [comment]
:memo: CS1612 is the following:

> Cannot modify the return value of '{0}' because it is not a variable

**Comment by gafter** [comment]
`this.Relay` is an rvalue, not an lvalue, so you can't modify one of its fields.

**Comment by svick** [comment]
@gafter The point here is that `this.Relay.Text = "hello";` does not try to modify any `Relay` fields, it tries to set a property. And yet the compiler does not allow it.

**Comment by gafter** [comment]
Calling a property set method requires passing a `this` parameter by reference, which can only be done for an lvalue.
