### ISSUE TITLE
 ExpandSelection/ReduceSelection Option 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#22590]
[View on Developer Community](https://developercommunity.visualstudio.com/content/problem/24510/expand-selection-does-not-work.html)
I tried setting both "Edit.ExpandSelection" and, separately, "View.ExpandSelection" to ctrl-w to match my ReSharper workflow, but neither one did anything. Resetting to defaults, alt-1 also does nothing. 

cc @kuhlenh

**Comment by Pilchie** [comment]
This was added by the editor team in 15.5.

**Comment by CyrusNajmabadi** [comment]
Closing out for lack of feedback.
