### ISSUE TITLE
StateSet.ContainsAnyDocumentOrProjectDiagnostics heavy allocator

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#22609]
**Version Used**: 15.4 Preview 4

**Steps to Reproduce**:

1. Open Roslyn.sln
2. Work for a bit

**Result**:

`StateSet.ContainsAnyDocumentOrProjectDiagnostics` allocates ~5% of the total allocation load in devenv.exe. Roughly 75% of this is in `GetActiveFileStates`, while 25% of this is in the concurrent dictionary `GetEnumerator()` call.

**Comment by CyrusNajmabadi** [comment]
Goign to say that thsi was fied with https://github.com/dotnet/roslyn/pull/34762.  Haven't seen this show up since.  Further work can be driven with an up to date trace showing there's still an issue.

**Comment by sharwell** [comment]
I'd prefer to keep this one open. The call to `GetActiveFileStates` has been removed, but we still have a call to `ConcurrentDictionary<TKey, TValue>.GetEnumerator()` on a known allocation hot path.
