### ISSUE TITLE
[EE] Override OnClose for MetadataContextItem

### ISSUE THREAD

**Issue by r-ramesh** [dotnet/roslyn#22617]
This tracks the likely fix for the wretched Watson crash tracked by DevDiv VSO Bug 187805. Previous attempts at slaying this beast (https://github.com/dotnet/roslyn/issues/17788 and debugger changes) seem to have not addressed all code paths causing the issue.

The Watson dumps indicate X64 debugging, with the process object unloaded at the point of attempting to read a dangling pointer returned from the GetMetaDataBytesPtr Concord API. From this, the likely explanation is:
- When the process is unloaded, Concord releases all Dkm objects (marks them as unloaded), releases their data items (calls OnClose), and then starts releasing all components (that aren't currently in flight).
- In this case, the InstructionDecoder component is currently alive and in flight, which has just called into CachingLayer's (a debugger-implemented component) GetMetaDataBytesPtr, which returns a pointer to a blob that it maintains as a member variable on the component itself.
- During (or just after) the GetMetaDataBytesPtr call, the process is unloaded. Once the IP returns to InstructionDecoder, the Concord dispatcher has begun cleanup. It marks all Dkm objects as unloaded, and starts releasing data items by calling their OnClose method. Since no data items in InstructionDecoder have OnClose, Concord moves on to the next phase, i.e. unloading components. CachingLayer is thus released, causing the pointer it just gave out, to be dangling.

The proposed fix, is to not let Concord move to the last phase of unloading components when InstructionDecoder is in flight. We can do this, by having a data item of InstructionDecoder that has an explicit clean up method to be called by the dispatcher (has an OnClose method). This will block Concord from going to the component-cleaning phase, ensuring that the bytes are alive.

Proposed fix:
Add this to MetadataContextItem, which is a data item on DkmClrAppDomain:
`protected override void OnClose() { }`

Note that the previous attempt to fix the issue was similar, but related to module instance unloads. In this case, if a process is unloaded, the module instance unloads are not fired, which is why it did not address this scenario.

**Comment by ivanbasov** [comment]
Related to #22620
Consider resolving two VSO reliability items depending on those two issues when fixed.

**Comment by r-ramesh** [comment]
On further investigation, this is not correct. As of today, the dispatcher takes a lock regardless of if the OnClose method is explicitly overridden, so this fix will not address the problem. This issue can be closed now (I will take back the VSO bug), and I will continue to investigate.
