### ISSUE TITLE
Random hang during shutdown

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#22613]
**Version Used**: 15.0.26927.1 built by: D15REL

Had a random hang during shutdown. I should warn that I had an "external process crashed" gold bar but don't know what happened there. Was running an old build so that bug might be fixed.

**Dump:** ``\\mlangfs1\public\jasonmal\Dumps\Roslyn\22613``

**Comment by jasonmalinowski** [comment]
FYI @heejaechang here's the bug I just asked about.

**Comment by heejaechang** [comment]
@jasonmalinowski thank you I will take a look

**Comment by CyrusNajmabadi** [comment]
Closing out as the OOP system is basically totally changed from what we had back then.
