### ISSUE TITLE
Automatic indentation for method argument attributes is awkward

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#22610]
[View on Developer Community](https://developercommunity.visualstudio.com/content/problem/39656/automatic-indentation-for-method-argument-attribut.html)

If I want to annotate a method argument with an attribute, most commonly for MEF importing constructors, then it can easily happen that the line gets too long and I'd like to have the attribute and argument on separate lines. The suggested indentation of VS is awkward here because it indendts the attribute (ok) and then unindents the actual argument (not ok)

**Comment by CyrusNajmabadi** [comment]
I can't repro this. Indentation seems fine to me:

![image](https://user-images.githubusercontent.com/4564579/75911065-cae2de80-5e03-11ea-984f-91937af6b5e3.png)

If the user can provide a repro we can move forward on this.
