### ISSUE TITLE
VB newly accepts some characters as letters, but does not properly case-fold them

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#2261]
VB native compiler did not consider 'ϴ' (Unicode 0+03f4) to be a letter. The Roslyn compiler now accepts it as a letter, thereby complying with the Unicode spec, but does not case-fold it to the letter 'θ' (Unicode U+03B8), thereby not complying with the Unicode spec.

There are about a dozen other letters in this same state.

If we're going to accept it as a letter, we should case fold properly to avoid breaking compatibility in the future when we fix the case folding.

**Comment by gafter** [comment]
Here is a test case demonstrating the breaking change:

```vb
Option Strict On
Option Explicit Off

Imports System

Module Module1
    Dim ϴ As Boolean = False

    Sub Main()
        Foo()
        Console.WriteLine(ϴ)
    End Sub

    Sub Foo()
        θ = True
    End Sub

End Module
```

**Comment by AdamSpeight2008** [comment]
@gafter Where in the Roslyn source? Is it determined what is or isn't a letter?

**Comment by gafter** [comment]
See https://github.com/dotnet/roslyn/blob/8b65942b9d4921b21e1356a54530c366b4d6b170/src/Compilers/VisualBasic/Portable/Scanner/Scanner.vb#L984

**Comment by gafter** [comment]
The ideal solution to case-folding for VB would be to fully follow the spec, and use the data in ftp://ftp.unicode.org/Public/UNIDATA/CaseFolding.txt .

**Comment by AdamSpeight2008** [comment]
I submitted a pull request #1463 that merged `TryScanToken` and `ScanTokenFullWidth` internals into `ScanTokenCommon`

**Comment by gafter** [comment]
@AdamSpeight2008 I don't know what that has to do with this issue.

**Comment by gafter** [comment]
This was fixed in https://github.com/dotnet/roslyn/commit/f7a1dc21442b877be95c3a36e5198518247f2d63

**Comment by gafter** [comment]
@AlekseyTs Can you please verify this?
