### ISSUE TITLE
"x is var _" results in the expression being true without x being evaluated

### ISSUE THREAD

**Issue by DavidArno** [dotnet/roslyn#22619]
**Version Used**: 
C# 7.1, debug mode

**Steps to Reproduce**:
```cs
internal class Program
{
    private static void Main()
    {
        var test = new Program();
        var result = test.IsVarMethod();
        Console.WriteLine($"Result = {result}");
        Console.Read();
    }

    private int IsVarMethod() => ThrowingMethod() is var _ ? 1 : 0;
    private bool ThrowingMethod() => throw new Exception("Oh");
}
```

**Expected Behavior**:
I'd expect `ThrowingMethod()` to be invoked, resulting in an exception.

**Actual Behavior**:
The method, `IsVarMethod()`, returns `1` and no exception is thrown.

This only occurs if the `x is T y` expression uses the var pattern and a discard. Change `var` to `bool` or `_` to eg `y` and the method is invoked and the exception thrown.

**Comment by jcouv** [comment]
Tagging @gafter
