### ISSUE TITLE
XML Doc Comment parser does not consider tuple syntax to be valid in crefs

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#22626]
e.g.,

```csharp
class C
{
    /// <summary>
    /// <seealso cref="M((string, int))"/>
    /// </summary>
    public void M((string, int) stringAndInt) { }
}
```

Produces warnings

```
warning CS1584: XML comment has syntactically incorrect cref attribute 'M((string, Flag))'
warning CS1658: ) expected. See also error CS1026.
```

**Comment by sharwell** [comment]
Loosely related to #18274.

This is especially problematic due to the way `cref` attribute code completion tries to write exactly the syntax you indicated.

**Comment by sharwell** [comment]
Adding **Area-IDE** since code completion and the compiler need to work together here.

**Comment by CyrusNajmabadi** [comment]
Blocked on https://github.com/dotnet/roslyn/issues/66757.
