### ISSUE TITLE
How to get the actual StartLine of a Method/Class having attributes

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#22629]
**Version Used**: 
2.3.2

**Steps to Reproduce**:

1. In our code we are finding the start line of a Method or a Class based on the below code:
`node.GetLocation().GetMappedLineSpan().StartLinePosition.Line;`
here the node is SyntaxNode for the class/method in picture.
2. The above code works well for all the methods and classes who do not have any attribute decoration associated with it. But in case if the class / method is decorated with an attribute, the above code returns the start line as the first attribute decorated above the class /method.
3. We understand that when we have a attribute for a given class or a method, the attribute is part of the class / method declaration. 
```
1        using System;
2        using System.Threading.Tasks;
3        using NUnit.Framework;
4        namespace Quartz.Tests.Unit
5        {
6              [DisallowConcurrentExecution]
7              [PersistJobDataAfterExecution]
8              public class TestAnnotatedJob : IJob
9              {
10                   public Task Execute(IJobExecutionContext context)
11                    {
12                        return Task.FromResult(0);
13                     }
14              }
15                  
16              public class TestJob : IJob
17              {
18                     public Task Execute(IJobExecutionContext context)
19                    {
20                         return Task.FromResult(0);
21                     }
22             }
23        }
```
4. In the above class, when we try to find the start line of the class **TestJob** using the code `node.GetLocation().GetMappedLineSpan().StartLinePosition.Line` we get the start line as 16 which is logical. 
But when we try to find the start line of the class **TestAnnotatedJob** using the code `node.GetLocation().GetMappedLineSpan().StartLinePosition.Line` we get the start line as 6 instead of 8, which though logical, but does not give the exact line number.

**Expected Behavior**:
Some mechanism in which we can get the actual line number of the start line for a class/method decorated with attribute.
 
**Actual Behavior**:
There is no mechanism which we can use.

**Comment by alrz** [comment]
probably you should get the line number off of the Identifier (method name), since attributes are part of that node and `6` is correct as its start line.

**Comment by CyrusNajmabadi** [comment]
> get the actual line number of the start line

As you mentioned, you are getting the actual line number :)   If you want a different line number, you'll have to be more specific about what you want.  For example, a method might look like:

```c#
[attr1]
[attr2]
public
static
void
Main
(
)
{
     Console.WriteLine(
          0);
}
```

Which of these lines do you consider the "actual line" that the method starts on?

Once you answer that, you'll likely be able to trivially write the code that gives you the value you want :)

**Comment by abhijitparkhi1983** [comment]
@alrz this is what it should be. Thanks for your quick reply.

@CyrusNajmabadi very interesting and valid scenario which you have put in. Like i mentioned, the approach suggested by @alrz sounds the way to go. Thanks for your valuable views

**Comment by mrn-aglic** [comment]
I have a similar question to this one. Looking at the code in Visual studio, the class keyword and name are at line 7, but when I try to get the start of the span, I get the value 6 back (which is the line that contains an open curly bracket). 

Is this by design? I'm a bit confused. I'm loading the code from file.

**Comment by CyrusNajmabadi** [comment]
@mrn-aglic you may be confusing Roslyn's 0-based indices with VS' 1-based ui

**Comment by mrn-aglic** [comment]
Yeah, I was... I noticed it a bit too late, and didn't find the time to remove my comment.
