### ISSUE TITLE
VB: Editor should NOT automatically remove digit grouping character for decimal literals.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#22627]
**Version Used**:

Visual Studio Community 2017 v15.3.3

**Steps to Reproduce**:

Try typing this in any VB project `Dim num = 12_000.29`. The editor automatically removes the `_`  digit grouping character. But if you type `Dim num = 12_000` it remains. Not sure why it does this since it doesn't appear to be a syntax error (Immediate window evals it just fine):

![vs_digit_seperator](https://user-images.githubusercontent.com/20465797/31368037-d647a11c-ad83-11e7-9628-f83c9237cf95.png)

**Expected Behavior**:

The editor should leave decimal literals with digit grouping characters as is, otherwise you can type things like `12_000_000` but can't do `12_000_000.998` which makes no sense to me (unless I am overlooking something).

**Comment by tamlin-mike** [comment]
Is this a problem in/for C# too, or is it VB-only? A literal should remain a string (in this case), no matter the language.

**Comment by ericmutta** [comment]
> @tamlin-mike Is this a problem in/for C# too, or is it VB-only?

This particular one seems to be a VB-only bug. This C# stays the way it is (the `_` is not removed while editing):

```C#
namespace ConsoleApp1
{
  class Program
  {
    static void Main(string[] args) {
      var x = 12_000.29;
    }
  }
}
```

**Comment by AdamSpeight2008** [comment]
@ericmutta What happens if you `format selection` ? To see if it the issue could be in the formatter.

**Comment by ericmutta** [comment]
> @AdamSpeight2008 What happens if you format selection ? To see if it the issue could be in the formatter.

I think it is definitely the formatter. If you type `12_000.29` then move the caret to another line, it kicks in. If you stay on the same line and column then execute format selection it removes it right there and then!

**Comment by AdamSpeight2008** [comment]
@ericmutta 
If we take the Integer case (which does preserve digit separators) then the problem exist for a floating point literal. [ReduceTokensCodeCleanupProvider](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/VisualBasic/Portable/CodeCleanup/Providers/ReduceTokensCodeCleanupProvider.vb) 
We should have an additional check in each of those cases.

**Comment by ericmutta** [comment]
> @AdamSpeight2008 We should have an additional check in each of those cases.

That ought to fix it. I can see by briefly looking at that code that there is a [check](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/VisualBasic/Portable/CodeCleanup/Providers/ReduceTokensCodeCleanupProvider.vb#L92) for digit seperators in the integer literal case which causes it to be returned as is without any replacements.

While on this topic, I think we should file a seperate issue for `Dim x = 001` which is always converted to `Dim x = 1`...behaviour that is pretty annoying when you want to use leading zeroes for alignment, example, this is not possible:

```VB
Dim bytes = New Byte(){
  100, 020, '<--- 020 will be converted to 20.
  024, 126  '<--- 024 will be converted to 24.
}
```

**Comment by tamlin-mike** [comment]
Lucky VB not having to handle octal numbers... :-)

**Comment by AdamSpeight2008** [comment]
@ericmutta I think so too, but have yet to check. It's getting late in England. so if possible I'll look to or the weekend.

**Comment by tamlin-mike** [comment]
As for the wrong return from VisitLiteralExpression, does the following really make sense?
```VB
Const digitSeperator = "_"c
If Not base.HasValue OrElse idText.Contains(digitSeperator) Then
    Return newNode
End If
```
I'd expect it to return the existing, not *new*, if '_' was included in the literal value. Perhaps it's so simple to change 'OrElse' to 'AndNot'?

**Comment by ericmutta** [comment]
> @tamlin-mike Lucky VB not having to handle octal numbers... :-)

Indeed. 20 years writing code and I have never once used octal numbers. Never really figured out why they are are needed (though that may just be laziness on my part 😄)

**Comment by ericmutta** [comment]
> @AdamSpeight2008  It's getting late in England. so if possible I'll look to or the weekend.

Much appreciated my friend, given your adventures in the parser/lexer I think this would be a fix you can do!

**Comment by tamlin-mike** [comment]
> @ericmutta 20 years writing code and I have never once used octal numbers.

I have a decade+ on you, but the same experience. Never (ever!) intentionally used it.
Once got bitten by it badly when trying to "nice"-up some IP's in some early Win3.11 .ini-file; "Say what? Those are parsed by scanf?!". :-) (I'm pretty sure it's still mandated for HOSTS & co.)

I think that's something no language should mimic from C (and therefore C++). Even something ugly like leading "0o" (how's that for unreadable, based on font) would be better.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to make changes in these vb experiences now.
