### ISSUE TITLE
[EE] Unify all classes of CSharpExpressionCompiler

### ISSUE THREAD

**Issue by r-ramesh** [dotnet/roslyn#22620]
Currently, only 1 component of CSharpExpressionCompiler implements the IDkmModuleModifiedNotification and IDkmModuleInstanceUnloadNotification. These interfaces are implemented to guard calls to GetMetaDataBytesPtr, to prevent dangling pointer references (and subsequent AV's like the VSO Bug 187805.

However, all 3 classes of the component call into GetMetaDataBytesPtr, and thus 2 classes (CSharpFrameDecoder and CSharpLanguageInstructionDecoder) are unguarded and potentially running into the same issue.

Ideally, all these 3 classes should be unified into a single class, which should make things easier and potentially fix some instances of the Watson.

**Comment by ivanbasov** [comment]
resolved in 15.6
