### ISSUE TITLE
Running roslyn in another process - dependency problem

### ISSUE THREAD

**Issue by UnderNotic** [dotnet/roslyn#22634]
Hi,

I'm in situation when I can not use:

```
  <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.2.0" newVersion="1.2.2.0" />
  </dependentAssembly>
```
Is there a way do this programmatically because now I'm getting following error:
`"System.TypeLoadException - Could not load type System.Collections.Immutable.ImmutalbeArray1 from assembly "System.Collection.Immutable, Version=1.0.34.0 ..... )`"

**Comment by tmat** [comment]
Could you describe your situation a bit? Are you using Roslyn in a plugin to some other app that you can't modify?
