### ISSUE TITLE
Add IOperation API for BoundDiscardExpression

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22633]

**Comment by 333fred** [comment]
@dotnet/analyzer-ioperation @AlekseyTs do we feel that we need this API in 15.7, or should I put it in the features/dataflow branch and we'll ship it with 15.8?

**Comment by 333fred** [comment]
I'd vote for the latter.

**Comment by AlekseyTs** [comment]
I don't think this has to be bundled with dataflow, regardless of what we decide for the target milestone.

**Comment by 333fred** [comment]
Fair enough. I just thought it would be a convenient branch.

**Comment by AlekseyTs** [comment]
> I just thought it would be a convenient branch.

I think it is a bad idea to link unrelated bus an features. If the feature doesn't ship when we expect, the bug remains.

**Comment by 333fred** [comment]
Fixed in #25820.
