### ISSUE TITLE
Should `LoweredDynamicOperationFactory.GetArgumentInfo` handle `in`?

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#22648]
This was spawned by reviewing code that makes use of `RefKind.Out` and asking whether it should handle `RefKind.In` as well.

```C#
public partial class C 
{
    void M()
    {
        int x = 1;
     	dynamic d = this;
        d.M(ref x); // works
        d.M(x); // runtime error
        d.M(in x); // runtime error
    }
    void M2(in int x) { }
}
```

Tagging @OmarTawfik to confirm this accurately describes what we tested.
FYI @VSadov

**Comment by OmarTawfik** [comment]
It all comes down to the compiler emitting the correct `Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfoFlags`. Right now there is no `in` flag, and the compiler is not emitting anything. So runtime is reading it as a `ref` parameter, and expecting the call to be so.

**Comment by VSadov** [comment]
I think we should make it an error for now and relax that once binder has support for “in”.

**Comment by jcouv** [comment]
Closing as duplicate of #22813
