### ISSUE TITLE
Body of each condition in IF is the same.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#2264]
I'm still in the process of manually going through the vb.net aspects of the project looking for place to utilise `NameOf` and `$" { } "`

When I ran across this conditional .

```vb
        Dim allFields = GetAllFieldsOfStructure(nodeStructure)

        'TODO Merge first and second into a function
        ' First Constructor
        If Not _parseTree.IsAbstract(nodeStructure) Then
            _writer.Write("        Friend Sub New(")
        Else
            _writer.Write("        Friend Sub New(")
        End If

        ' Generate each of the field parameters
        _writer.Write("ByVal kind As {0}", NodeKindType())
        If Not noExtra Then
            _writer.Write(", ByVal errors as DiagnosticInfo(), ByVal annotations as SyntaxAnnotation()", NodeKindType())
        End If


```
[Here](https://github.com/dotnet/roslyn/blob/master/src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/GreenNodes/GreenNodeWriter.vb#L482)

Looks like a copy and paste error.

**Possible Resolutions**
1. Alter one of the branches to what it should really be,
2. Remove to redundancy and just leave `_writer.Write("        Friend Sub New(")`

**Comment by gafter** [comment]
https://github.com/dotnet/roslyn/blob/15dcad3dd2966040c7a0bfb503d27df4ac4183e0/src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/GreenNodes/GreenNodeWriter.vb#L482-L486

**Comment by VSadov** [comment]
It was likely generating slightly different code at some point, but then one of the branches was simplified to be exactly as another. TODO there does not make much sense to me now...
It should be ok to remove redundancy without affecting the output in any way, but I do not see any urgency one way or another.

**Comment by AdamSpeight2008** [comment]
@VSadov I'll grab that one as I'm in in that file anyway doing String-Interpolation utilisations. So I'll change it.

**Comment by gafter** [comment]
@AdamSpeight2008 Please keep your PRs small if possible. One way is to keep separate changes in separate PRs.
