### ISSUE TITLE
Marshalling methods with `in` parameters should have [In] attribute

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#22641]
As an optimization, compiler should place `[InAttribute]` if user didn't on `in` parameters in marshaling methods. This saves an extra copy by the run-time on method return. because right now, it is treated as an ordinary `ref`, and the value is copied in and out.

cc @tannergooding @jcouv

**Comment by tannergooding** [comment]
Related to https://github.com/dotnet/coreclr/issues/11830 and https://github.com/dotnet/csharplang/issues/38#issuecomment-303570195

FYI. @yizhang82

**Comment by jcouv** [comment]
:memo: It's ok to fix this after 7.2, as it is an optimization. Users can manually add the `[In]` as a workaround (when the compiler will add it, it will be superfluous, but won't break).

**Comment by jcouv** [comment]
@OmarTawfik Can you take this one?
