### ISSUE TITLE
Reduce allocation requirements in WriteObjectWorker

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#22659]
The dictionaries used by `WriteObjectWorker` can become large, and occasionally fail when the IDE is under memory pressure. We should identify sets of objects which cannot be multiply-referenced within the object getting serialized, and avoid adding these objects to the map.

https://github.com/dotnet/roslyn/blob/878ffad23b8b06cb229c9ab31eada7634a473508/src/Compilers/Core/Portable/Serialization/ObjectWriter.cs#L805

:link: Watson (internal issue for this): https://devdiv.visualstudio.com/DevDiv/_workitems/edit/485537

**Comment by ivanbasov** [comment]
@sharwell, @jinujoseph, the original VSO issue was resolved as duplicate and was assigned to milestone 15.5. Could you please schedule this one or the original one to at least 15.6?

**Comment by CyrusNajmabadi** [comment]
> We should identify sets of objects which cannot be multiply-referenced within the object getting serialized, and avoid adding these objects to the map.

Interesting.  Currently, i believe we use this for referencing green nodes (which can show up several times in the same tree due to the compilers' aggressive reuse of some nodes).  For example, the same green token may appear many times.  And the compiler also caches small green trees so they can be reused in the same large tree.  

One approach we could take would be to have the compiler add a bit on a green node if it is sharing it.  These would be set for all the well known shareable tokens it creates for the parser.  And it would set this bit if it retrieved a larger node from the cache during parsing.

We could then check for the presence of this bit during serialization and only cache when present.  

--

For all other usages of ObjectReader/Writer i don't believe we have situations where we need or benefit from object references.  And i don't believe there are any cycles in any structures we currently serialize out.

So this could be a big win.

**Comment by sharwell** [comment]
Moved to **Area-Compilers**. Correcting this issue requires understanding and possibly either modifying or documenting constraints for sharing data in the trees used by the compiler.

**Comment by CyrusNajmabadi** [comment]
tagging @VSadov .  I think Vlad did the work on green-node reuse (within the same tree) and would have the best insight on what we could do here.  Note: i think my comment [above](https://github.com/dotnet/roslyn/issues/22659#issuecomment-338038448) still applies.  I think green nodes have a flags enum that might be useful here.  However, i also think flags are pulled up into parent nodes, so it's not clear if that would actually work here.

**Comment by VSadov** [comment]
"shareable" bit is certainly posible. Assuming we have bits left in the flags. 
It would probably be helpful in the node caching code itself as well.

It would be "*non*shareable" bit of course. The negation of "shareable" naturally propagates - we do not reuse nodes that have any of nonshareable children.

**Comment by CyrusNajmabadi** [comment]
> It would be "nonshareable" bit of course. The negation of "shareable" naturally propagates - we do not reuse nodes that have any of nonshareable children.

Ah, brilliant!  :)

**Comment by VSadov** [comment]
The bits are all used up though. There is even some sharing between mutually exclusive bits. Will have to think how to arrange a bit there. 
We would not expand the size of green node by a whole byte just for this, I am afraid.

**Comment by CyrusNajmabadi** [comment]
Hrmm.. that's unfortunate.  Alternate idea might be:

merge flags and slot_count into a single ushort and reduce hte number of bits necessary for slotcount.  We don't ever have more than 16 children for a node right?  We'd only need 4 bits for that, freeing up 4 bits to use as flags.  This would mean a bit more computation as the bits would need to be masked to determine teh count.  not sure if that would be an actual issue in practice.  If we have decent perf tests we should be able to tell.

Also, i didn't realize, but there's an InheritMask.  So if we did put a new bit in, we could have it be the affirmative form, but just say htat it didn't inherit by default.  (just a thought).

**Comment by VSadov** [comment]
By looking at the usage it seems `HasStructuredTrivia` may not be a very efficient use of a NodeFlags bit.

**Comment by CyrusNajmabadi** [comment]
Agreed.  I can't find any transitive uses of that in the IDE at all (unlike HasDirectives).  And we're hte ones who usually like the bits to make walking efficient.

**Comment by VSadov** [comment]
Lists can have more than 16 children. We cache the slot count because there are some scenarios like indexing, where knowing occupancy is extremely helpful and one byte handles a big percentage of cases without any extra indirections. We should probably not disturb that.

**Comment by CyrusNajmabadi** [comment]
> Lists can have more than 16 children.

Sure.  But lists also have to manage with the fact that a byte might not be enough and thus have to get a non-byte value for the slotcount.

That said, i'm not going belabor this.  I agree this is a very delicate area.  And i would def be happy to just repurpose an existing bit safely versus utilizing slotcounts!

**Comment by VSadov** [comment]
`HasStructuredTrivia` is used to limit walking into nodes that do not have doc comments. Considering that we should not descend below method level anyways and that the trees are generally very wide and shallow (most code is method bodies), - that is not a lot of savings.

**Comment by ivanbasov** [comment]
@jaredpar, this issue has a high number of hits in 15.7. It is in the top 15.7 issue list. Since it is in area-compilers and @sharwell is OOF for some time, could you please help driving it? It definitely meets the 15.7 bar. Thank you!

**Comment by ivanbasov** [comment]
@VSadov, @jaredpar the corresponding PR was merged:  #26156 
Should we close this GitHub issue?
