### ISSUE TITLE
Compilation.ObjectType.TypeKind == Error after copying WPF solution to a different location on disk

### ISSUE THREAD

**Issue by debonte** [dotnet/roslyn#22674]
**Version Used**: Visual Studio 15.5 Preview 2 (d15prerel 27009.3000).  Roslyn version appears to be 2.6.0.62126

**Steps to Reproduce**:

1. Start VS
2. Attach debugger to VS and put a breakpoint in one of the following spots:
a. CSharpCompilation.ObjectType.
b. The XamlLanguageService's CompilationProvider.TryGetReady after it retrieves Compilation.ObjectType (vs\src\xaml\designer\source\xamllanguageservice\codeanalysis\compilation\compilationprovider.cs)
2. Create new C# "WPF App" project
3. Once the project is created and MainWIndow.xaml opens, the breakpoint will be hit and Compilation.ObjectType.TypeKind == Class
4. Close solution
5. Copy the solution directory (including .vs directory and all project files) to some other location on disk.
6. Open solution from the new location
7. Open MainWindow.xaml
8. The breakpoint will be hit again.

**Expected Behavior**: Compilation.ObjectType.TypeKind == Class

**Actual Behavior**: Compilation.ObjectType.TypeKind == Error

**Impact**:
1. This is causing DevDiv bug 492839 -- a large perf regression in the XAML IntelliSense file generator.
2. WPF XAML IntelliSense is totally broken/unavailable.

**Workaround**: I haven't been able to find one,  Rebuilding doesn't help.  Closing and reopening VS doesn't help.  At one point I thought that opening a C# file and using C# IntelliSense got me back to a good state, but I was either wrong or it doesn't work consistently.

**Notes**:
1. This is a regression from VS 15.4.  I verified this using d15svc 27004.2002.
2. Rather than copying the solution to another directory, you can also repro this issue by deleting the solution's .vs directory.  When you reopen the solution VS will recreate the .vs directory, but you're still left in a bad state.
3. There's a similar issue with UAP projects but it appears that you can workaround it by rebuilding and then closing/reopening the solution.  I've been told that this isn't a regression.

**Comment by Pilchie** [comment]
@tmeschter can you take a look?

**Comment by debonte** [comment]
We tracked this back to an issue with DTBB where it fails to provide the assembly references to Roslyn when VS is launched from a Razzle prompt.  So, not a Roslyn bug.  You can work around this issue by disabling DTBB ("Allow parallel project initialization").
