### ISSUE TITLE
[IOperation] Should IUsingStatement's block be implicit

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#22679]
See https://github.com/dotnet/roslyn/pull/22630#discussion_r144369564. Crux of the argument is that the IBlockStatement under an IUsingStatement in VB uses the same syntax as the IUsingStatement, but isn't currently implicit. Should that block be considered implicit?

**Comment by mavasani** [comment]
Design team decision: We will mark the IBlockStatement nodes in VB that have no explicit syntax or same syntax as outer IXXXStatement as Implicit. This needs to be done across all statement nodes in VB, not just IUsingStatement.
