### ISSUE TITLE
No verifier spec is available for new codegen used for non-mutating structs

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#22671]
**Version Used**: 2.6.0.62126 (1758d50)

To support the new Roslyn behaviour updated verifier spec should be available also for readonly struct codegen (the similar case was by-ref returns). With that, we could update Mono verifier implementation not to reject newly generated code.

The request is extracted from https://github.com/dotnet/roslyn/issues/22485

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/issues/22872

**Comment by VSadov** [comment]
Proposal of extension to IL verification rules that would account for new features were posed here:

https://github.com/dotnet/designs/pull/17    -  ref returns
https://github.com/dotnet/designs/pull/21    -  readonly references

I think the further discussions should happen over there. 

(note there likely will be some minor work on the Roslyn side to be fully compliant with the rules, once we agree on the rules)
