### ISSUE TITLE
writing a CodeFix to replace methods

### ISSUE THREAD

**Issue by Meir017** [dotnet/roslyn#22698]
I'm working on writing an analyzer that will be able to replace multiple method calls into other method calls.
I'm using this specifically to create analyzers that will report wrong usages of the library `FluentAssertions`.

for example:
The following code:
```cs
IEnumerable<string> actual = new[] { "a", "b" };

actual.Should().NotBeNull()
    .And.NotBeEmpty()
    .And.HaveCount(2);
```
should produce a codefix:
```cs
IEnumerable<string> actual = new[] { "a", "b" };

actual.Should().NotBeNullOrEmpty()
    .And.HaveCount(2);
```
but I couldn't find a way not to lose the next statements after the part I refactored

![image](https://user-images.githubusercontent.com/9786571/31578423-8336091a-b129-11e7-8e55-e7c15c382bc0.png)

the expression that represents `And.HaveCount(2)` contains all of the previous code so replacing `NotBeNull().And.NotBeEmpty()` with the wanted expression is not enough

**Comment by CyrusNajmabadi** [comment]
Sounds like you're incorrectly manipulating the tree.  You should look at the shape of the syntax tree (I recommend the syntax tree visualizer for this), and see how this is structured.  Then debug through and see how your manipulation affects things.
