### ISSUE TITLE
Remove unused None fields in few public IOperation enums

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22694]
1. ArgumentKind.None
2. BinaryOperatorKind.None
3. BranchKind.None
4. CaseKind.None
5. DoLoopKind.None
6. LoopKind.None
7. UnaryOperatorKind.None

**Comment by mavasani** [comment]
Tagging @jinujoseph - needed for 15.5

**Comment by tmat** [comment]
Why are we removing them? I believe it's recommended in .NET design guidelines to have values that correspond to default enum value:

> ✓ DO provide a value of zero on simple enums.
> Consider calling the value something like "None." If such a value is not appropriate for this particular  enum, the most common default value for the enum should be assigned the underlying value of zero.

**Comment by mavasani** [comment]
> Why are we removing them? it's recommended in .NET design guidelines to have values that correspond to default enum value:

Tagging @dotnet/analyzer-ioperation @AlekseyTs @cston 

There was a strong intent in one of our past design meetings to remove unused fields that did not make sense. For example, not sure what BinaryOperatorKind.None would mean. I can definitely change the range of values to start from zero.

**Comment by mavasani** [comment]
Also note that [SymbolKind](http://source.roslyn.io/#Microsoft.CodeAnalysis/Symbols/SymbolKind.cs,30fd9c0834bef6ff), [MethodKind](http://source.roslyn.io/#Microsoft.CodeAnalysis/Symbols/MethodKind.cs,10), etc. do not have a None field, but the range does start from zero. I think we should probably match this for our enums.

**Comment by sharwell** [comment]
`None` is needed for `[Flags]` enum types. Other enums can just let the first value be 0.

**Comment by mavasani** [comment]
Addressed with https://github.com/dotnet/roslyn/pull/22695/commits/53a2153c443d8866e61cbd0d7617f8b0e321020f in https://github.com/dotnet/roslyn/pull/22695
