### ISSUE TITLE
Lightbulb for BC30002 doesn't offer to "fix all"

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#2270]
I have a WinForms app that with code

``` vb
Dim x As Windows.Forms.BindingMemberInfo = ...
Dim y As Windows.Forms.BindingMemberInfo = ...
```

I upgrade to .NET4.6, where that code becomes illegal, since it requires a full qualification to `System.Windows.Forms.BindingMemberInfo`. Fortunately, a lightbulb appears, offering the suggestion to use the full qualification.

WHAT I EXPECT: it should offer to make the fix (fully qualify) in all occurrences in the project.

WHAT I GET: it only offers to fix the current occurrence, as per the screenshot below...

![no-change-all](https://cloud.githubusercontent.com/assets/3316258/7335455/84c40fdc-eb76-11e4-97d1-c1dc0735c4b0.png)

**Comment by CyrusNajmabadi** [comment]
Not likely to make any changes here given the lack of customer feedback.
