### ISSUE TITLE
Compiler should resolve constant variables for expressions used in local functions, when declared in outer scope.

### ISSUE THREAD

**Issue by TylerKendrick** [dotnet/roslyn#22716]
**Version Used**: 

- VS2017 v15.3.5
- .NET 4.7
- C# 7

**Steps To Reproduce**:

1. Copy the code below into a new console application with the version information specified above.
2. Attempt to build the project.

**Code**:
```
namespace ConsoleApp1
{
    public class Program
    {
        private static bool DoWork(bool self, System.Linq.Expressions.Expression<System.Func<bool>> exp) => true;
        public static void Main()
        {
            bool outerScope;
            {   /*This can be any scope declaration (if, try, using, etc.)*/
                bool scopedToInnerBlock;
                /*Build fails when "scopedToInnerBlock" is a parameter,
                and outer scoped variable is used in Expression - not just a delegate such as Func.*/
                bool LocalFunction() => DoWork(scopedToInnerBlock, () => outerScope);
            }
        }
    }
}
```

**Expected Behavior**:
I expect the build to compile, but for the application to do nothing in particular.

**Actual Behavior**:
The VBCSCompiler.exe and csc.exe crash with code "-2146232797".

**Notes:**
- I discovered this error when using a local function to build a linq query joining a collection defined in an outer scope with a local collection.
- This only appears to be an issue if a local function is using an expression that references at least 2 variables declared in two different scope levels.
- This won't be reproduced if the Expression is replaced with a delegate.
- This won't be reproduced if only one variable is referenced in the localFunction.
- This won't be reproduced if both variables are declared in the same scope.
- This won't be reproduced if the local function is changed to a method.

**Comment by TylerKendrick** [comment]
Code doesn't appear to format as expected, so changing comments in code to block style.

**Comment by jcouv** [comment]
Tagging @agocke

**Comment by RikkiGibson** [comment]
This no longer repros in a compiler built from 892f9fae716ffb7b6fbd4a32db1eeca8fd376f6f.
