### ISSUE TITLE
Fix all for simplify name distinguishes between constructors and static member accesses

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#22713]
Fix all  on the "simplify name" lightbulb that appears on each instance of `ConsoleApp47` only fixes that instance. It looks like that's because we treat static member access as distinct from constructor invocation. Not sure what the right behavior is, but this was initially confusing to me.

```C#
namespace ConsoleApp47
{
    class Program
    {
        static int x;

        void foo()
        {
            var z = new ConsoleApp47.Program();
            ConsoleApp47.Program.x = 1;
        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Closing out for lack of feedback.
