### ISSUE TITLE
NullReferenceException after upgrading from 1.2.1 -> 2.3.1

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#22710]
**Version 2.3.1**: 

**Steps to Reproduce**:

1. Clone https://github.com/DotNetAnalyzers/PropertyChangedAnalyzers/tree/8d5fc945d8a879214f76e38e8b53111397547505
2. Run tests

**Expected Behavior**:

All tests passed when using 1.2.1

**Actual Behavior**:

```
System.NullReferenceException : Object reference not set to an instance of an object.
at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<TryAddDocumentMergeChangesAsync>d__19.MoveNext()
```

Debugged it and `oldSolution.Workspace.Services.GetService<IDocumentTextDifferencingService>()` returns null now. http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs,320

Not unlikely that something is wrong in the test fixture but something changed between versions.

**Comment by Pilchie** [comment]
How is your `Workspace` constructed in tests?

**Comment by JeremyTCD** [comment]
I have the same issue with 2.4.0. I'm using the default `AdhocWorkspace` constructor to instantiate a `Workspace` instance to test batch fixes for my diagnostic analyzers:

https://github.com/dotnet/roslyn/blob/ab56a4a6c32268d925014a3e45ddce61fba715cd/src/Workspaces/Core/Portable/Workspace/AdhocWorkspace.cs#L23-L26



`BatchFixAllProvider` attempts to retrieve an `IDocumentTextDifferencingService` from the workspace but is unable to find one. As mentioned by @JohanLarsson, the following `GetService` invocation returns null:

https://github.com/dotnet/roslyn/blob/ab56a4a6c32268d925014a3e45ddce61fba715cd/src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs#L319

Changing the line to the following allows tests to run normally: 
```csharp
var differenceService = oldSolution.Workspace.Services.GetService<IDocumentTextDifferencingService>() ?? new DefaultDocumentTextDifferencingService();
```

I'm not completely certain, but it appears that if a workspace has no `IDocumentTextDifferencingService` then defaulting to `DefaultDocumentTextDifferencingService` is acceptable.

**Comment by ThyPillow** [comment]
I have the same issue with 2.6.1.
I'm using a MSBuildWorkspace to apply several identified code fixes on all projects of a solution, this relates to #2020 as this is exactly what I am doing.

As long as there's only one Diagnostic provided, the code fix is being applied with no error, but as soon as the `BatchFixAllProvider` is trying to merge several of them, the NullReferenceException is thrown.

It seems the `LinkedFileDiffMergingSession` already has the behavior described by @JeremyTCD 
https://github.com/dotnet/roslyn/blob/542daef64095e903bb18dae4c65ac16de7e48cb0/src/Workspaces/Core/Portable/LinkedFileDiffMerging/LinkedFileDiffMergingSession.cs#L89

If you are okay with this proposed behavior I can submit the PR to fix it.

**Comment by CyrusNajmabadi** [comment]
This was fixed.  CLosing out.
