### ISSUE TITLE
Warning CS0219 isn't given for interpolated strings

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#2271]
In this code
```cs
var x = "hello";
var y = $"hello";
```
then I get a warning CS0219 "The variable 'x' is assigned but its value is never used". However I don't get the warning on 'y'. I guess that's technically related to the fact that string interpolation is shorthand for a function-call to String.Format. But it rubs me the wrong way. Glancing at this code, I really think it should give me the warning on 'y'.

![unused](https://cloud.githubusercontent.com/assets/3316258/7335499/8ea9ae3c-eb79-11e4-99fb-9e2f09b4510d.png)

**Comment by gafter** [comment]
This appears to be a dup of #1484
