### ISSUE TITLE
IOperation API Review work items

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#22719]
### Preview

- [x] BinaryOperatorKind.Invalid, DoLoopKind.Invalid, UnaryOperatorKind.Invalid
Can we use None instead?

- [x] Remove IHasArguments and IHasOperatorMethodExpression interfaces
Move their members down. 

- [x] Rename ArgumentsInEvaluationOrder to Arguments

- [x] Rename IIsTypeExpression.IsNotTypeExpression to IsNegated

- [x] Rename IIsTypeExpression.IsType to TypeOperand

- [x] Rename IIsTypeExpression.Operand to ValueOperand

### RTW

- [x] Rename -Expression and -Statement nodes to -Operation

- [x] Unify IIfStatement with IConditionalExpression to IConditionalOperation.

- [x] Rename Microsoft.CodeAnalysis.Semantics namespace to Microsoft.CodeAnalysis.Operations 
Since changing Expressions and Statements to Operations will already break all analyzers we can as well rename the namespace.

## Doc comment updates

- [x] Update doc comments of ICollectionElementInitializerExpression.AddMethod to mention it's null in error cases. Perhaps note that in all cases where IOperation node has a symbol returning property? 

- [x] IExpressionStatement -- Explain that the node represents semantics of dropping the value of the expression.

- [x] IIncrementOrDecrementExpression -- Add a note that unlike unary operation this operation modifies the target.

**Comment by tmat** [comment]
@mavasani @jinujoseph

**Comment by mavasani** [comment]
@tmat We also decided to rename all IXXXExpression and IXXXStatement nodes to IXXXOperationd and merge where appropriate?

**Comment by tmat** [comment]
@mavasani I believe that was the conclusion of the conversation around expression statement (that's the "Rename -Expression and -Statement nodes to -Operation" item).

**Comment by tmat** [comment]
Let's find out what are the nodes that would potentially be merged.

**Comment by mavasani** [comment]
Tagging @dotnet/analyzer-ioperation @AlekseyTs @cston @nguerrera @tmat 

Question on below:
> Unify IIfStatement with IConditionalExpression to IConditionalOperation.

Do we want to even have a single OperationKind for both of these operations? If not, do we retain the Expression or Statement suffixes on the OperationKinds? If we really want to make the operations API to be agnostic of statement/expression semantics, I think we should also have a single OperationKind, say `OperationKind.ConditionalOperation` and probably extension methods on IOperation and SyntaxNode, say `IsStatement` and `IsExpression`, which use the syntax for classification. Implementors of IOperation that do not care about expression/statement semantics never have to deal with it, but we get the expression/statement goodness for clients dealing with C# and VB source analysis. Thoughts?

**Comment by tmat** [comment]
Sounds good to me.

**Comment by tmat** [comment]
I think we could drop the "Operation" from the OperationKind names. We can also add the IsXxx methods later if we find them useful.

**Comment by mavasani** [comment]
> We can also add the IsXxx methods later if we find them useful.

I am wondering if not having `IOperation.IsExpression()` and `IOperation.IsStatement()` and also merging the operation kinds for ternary expression and if statement into a single `OperationKind.Conditional` will mean that analyzer authors that want to analyze just the expression or the statement form, but not both, will be forced to write language specific components in their analyzer that check the type/kind of the syntax node. Similarly, if we decide to merge while and do loops interfaces and operation kinds, as they are semantically the same, analyzer authors that want to analyzer just one specific kind of loop will need to go back to syntax to differentiate.

I understand our desire to make the IOperation API completely a semantic focused API, where constructs that purely differ by syntax do not have different APIs and operation kinds, but this should not hinder *the most important scenario* for IOperation at this point - ability to write language agnostic analyzers. I would like to propose the following principle: **Whenever we decide to merge operation APIs and operation kinds for constructs that are semantically equivalent but have more than one syntax API representation for a language, we *must* expose extension methods on the merged API to allow the clients to differentiate the operations based on the underlying language/syntax constructs.** Does this sound reasonable?

**Comment by tmat** [comment]
@mavasani Sounds like a reasonable principle. They don't need to be extension methods, we can have a "Kind" property on the operation interface directly as we do for a loop: http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/Loops/ILoopStatement.cs,19

**Comment by tmat** [comment]
@CyrusNajmabadi Do you have any opinion on this?

**Comment by mavasani** [comment]
Questions:

1. For IOperations representing more than one syntactic construct (e.g. merged if and ternary, merged loops, etc.), we must expose APIs to help distinguish these cases. Should these be properties on the IOperations or extension methods?
2. Interface names: All operation interfaces must have an Operation suffix.
3. OperationKind and Visit method names: Should match the interface name without the Operation suffix (there might be exceptions)
4. IVariableDeclaration and IVariableDeclarationStatement must be renamed as per our new principles. Does IVariableDeclarationOperation and IVariableDeclarationsOperation sounds good? Better name suggestion for the latter?
5. Naming for IDeclarationExpression and IExpressionStatement: I couldn't come up with better name except for appending Operation to these names. Looking for name suggestions.

**Comment by mavasani** [comment]
Re-opening to track some more API renames needed in OperationExtensions (`dynamicExpression` to `dynamicOperation`)
