### ISSUE TITLE
No information on completion in xml tag in xml doc

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#22720]
There is a little popup that opens when selecting an entry when completing in xml doc, but it shows no information. I'd expect some information about what `c` means, if possible, or no popup.

![image](https://user-images.githubusercontent.com/12466233/31638777-3bcb66f8-b28a-11e7-84b1-d6876852b6f3.png)

```
Microsoft Visual Studio Enterprise 2017 Int Preview
Version 15.4.0 Preview 3.0 [26919.1.d15rel]
VisualStudio.15.IntPreview/15.4.0-pre.3.0+26919.1.d15rel
```

**Comment by CyrusNajmabadi** [comment]
"The third letter of the alphabet" would be a good description to show here.

**Comment by CyrusNajmabadi** [comment]
Closing out given lack of customer feedback.
