### ISSUE TITLE
`ref readonly` returns should not return references to temps when used with PEVerifyCompat flag

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#22721]
PEVerifyCompat forces readonly references of readonly fields be ftched off a copy (since direct references are not allowed by PEVerify). 

The whole point of a ref return, however, is to return a direct reference. 

We should not be returning references to temps in cases which specifically demand references such as ref returns and ref assignments, even if that causes PEverify failure, since returning a reference to a temp completely misses the point.

See testcase `ReadonlyFieldCanReturnByRefReadonly` as an example.

**Comment by jcouv** [comment]
I don't understand.
I thought the purpose of the flag was to avoid a compat break on existing code. We have introduced other features that are not yet PE-verifiable, without trying to implement the compat flag for them.

**Comment by VSadov** [comment]
The flag cannot help this particular case since the scenario cannot peverify. That would be ok since it is a new feature that cannot be found in old code.  

What is not ok is that we still try try honoring the flag and as a result produce bad code.

**Comment by VSadov** [comment]
Fixed in #22772
