### ISSUE TITLE
CodeAction.Priority should be public

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn#22730]
Right now, [CodeAction.Priority](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeActions/CodeAction.cs,c798d8f5a1c87779) is internal.

However, I'd like to provide a "Report an issue" fixer for the diagnostics I produce. For obvious reasons, I want the priority for this to be low, so that other fixers (especially the built-in for suppressions) are reported at a higher priority.  The default priority is medium, which is too high:

![image](https://user-images.githubusercontent.com/5169960/31676360-3b1caf54-b31c-11e7-8499-77403bb26517.png)

**Comment by jinujoseph** [comment]
cc @DustinCampbell

**Comment by CyrusNajmabadi** [comment]
Note: suppressions always go last, no matter what your priority is.  Priority only affects ordering of CodeActions that are located at the same location.

**Comment by terrajobst** [comment]
I see. In that case it probably wouldn't help me.
