### ISSUE TITLE
project.OutputFilePath is null

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#22732]
**Version Used**: 
15.5 Preview 1

**Steps to Reproduce**:

1. Open an F# .NET Core project.

**Expected Behavior**:
`Project.OutputFilePath` is not `null`

**Actual Behavior**:
It is.

:link: https://github.com/dotnet/project-system/issues/2889

When I looked before, I found this:
I think this is a problem with CPSProject in general. 
 
We should be updating it when the project system calls the BinOutputPath setter.  Unfortunately, it appears that this updates stuff in the VisualStudio layer (the AbstractProject and the VisualStudioProjectTracker), but that never gets passed down to the Workspace, so if a CPSProject doesn’t have its outputpath at construction time, it never will).

**Comment by Pilchie** [comment]
@KevinRansom is this still blocking F# P2P ref support?

**Comment by KevinRansom** [comment]
This change is necessary for the F# dotnet project - project reference support.

**Comment by KevinRansom** [comment]
I'm going to look at it, now I have tracked down the other stuff.

**Comment by jasonmalinowski** [comment]
@KevinRansom Should this be assigned to you instead then?

**Comment by jinujoseph** [comment]
@KevinRansom since we have a work around , should this is closed ?

**Comment by CyrusNajmabadi** [comment]
Closing out given lack of response from F# that this is actually needed.
