### ISSUE TITLE
Warn if a value is never or always null

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#22743]
**Version Used**: NullableReferenceTypes branch

**Steps to Reproduce**:
```cs
    public void M(string? o) {
        if (o == null) return;
        var x = o?.Length; //!
    }
```

**Expected Behavior**: warning: `o` is never null

**Actual Behavior**: no warnings

Relates to https://github.com/dotnet/roslyn/issues/25592

**Comment by alrz** [comment]
Ideally I'd expect three warnings:

- Possible null
- Always null
- Never null

This is in-par with other proposed analysis (possibly on the ide side) for "always true/false" to detect more unreachable code.

**Comment by jcouv** [comment]
Tagging @cston

**Comment by jcouv** [comment]
I suspect we won't want to do that because in many cases, the nullable analysis will be imperfect (a trade-off between safety and flooding with warnings). For example, consider `if (a.b.c == null) return; M(a.b); var x = a.b.c?.Length;`.
The compiler may take the lenient view that `a.b.c` is non-null, but `M` could have changed that.

**Comment by alrz** [comment]
@jcouv So in your example it's not proven that c is never null i.e it's "possibly null' (which may or may not produce warning depending on how much we want to be optimistic to avoid flooding). This analysis, on the other hand, would be very local and only triggered on definitive cases.

**Comment by alrz** [comment]
I want to add, a "possible null dereference" warning for a definitive null dereference is a lot less useful when it comes to offering a fix - they demand different fixes outright: you add a null check for the former, but the latter is most likely a bug in the logic, or at best is a leftover from a recent change which might be misleading for the reader later on. All in all, I think it could be done along with "always true/false" warnings since they both are similar in terms of use cases.

**Comment by bkoelman** [comment]
I see great value in the distinction between "possibly" and "certainly" warnings. For example, const field access and locals should be "certainly" while property access should be "possibly". 

The distinction enables teams suppress the "possibly" warnings but require fixing the "certainly" cases.

**Comment by gafter** [comment]
I also see value in the "certainly" analysis.  But it isn't something we're doing or have any plans to do at this time. In code like this
``` c#
    public Result SomePublicApi(Argument a)
    {
        if (a == null)
            throw new ArgumentNullException("A");
```
we should not provide a diagnostic.  It is normal and expected for public APIs to check incoming parameters to ensure they are not `null` at runtime, even though the parameter was declared not to be null.  If we did it, a more precise analysis would permit us to give these diagnostics when we are "certain".

**Comment by CyrusNajmabadi** [comment]
Agree with @alrz.  This could/should only be done for when we can guarantee non-nullness (basically local/constant analysis only).  Anything that flowed in from anywhere else would have to be assumed to be potentially null.

**Comment by alrz** [comment]
Oh, and a "always null" warning would flag `x!!` usages. which seems to be sensible.

**Comment by jcouv** [comment]
Queued those questions on LDM [backlog](https://github.com/dotnet/csharplang/tree/master/meetings/2018#schedule-asap), which means we'll probably discuss in January.

**Comment by gafter** [comment]
At LDM on 2019-02-20 we confirmed that we are not including these diagnostics as part of the nullable reference types feature (though we might introduce them later)
