### ISSUE TITLE
Cannot use array of tuple in Case statement

### ISSUE THREAD

**Issue by alfeg** [dotnet/roslyn#22747]
**Version Used**: 
Visual Studio 15.4 (not sure what version of C# here)

**Steps to Reproduce**:

1. Simple pattern matching switch statement
```csharp
switch (anyVariable) {
    case Tuple<decimal, string>[] tuple:
        break;
}
```
**Expected Behavior**:
In Visual Studio 15.2 this code has no errors to compile

**Actual Behavior**:
In VS 15.4 I've got a bunch of syntax errors

Severity|Code|Description
--------|------|--------------
|Error|	CS1513|	} expected|
|Error|	CS0443|	Syntax error; value expected|
|Error|	CS1003|	Syntax error, ':' expected	|
|Error|	CS1525|	Invalid expression term '['	|
|Error|	CS1525|	Invalid expression term 'decimal'	|
|Error|	CS1525|	Invalid expression term '>'	|
|Error|	CS1001|	Identifier expected	|
|Error|	CS1002|	; expected	|
|Error|	CS1002|	; expected	|

![image](https://user-images.githubusercontent.com/118516/31723310-28d58c60-b427-11e7-9be8-9e58c47af6d5.png)

**Comment by alrz** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/22102 (15.5)

**Comment by alfeg** [comment]
Oh, thanks. I've tried to serach for this issue, and were not able to
