### ISSUE TITLE
IParenthesizedExpression inconsistency

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22751]
Current behavior:
1. C#: Never generated as parenthesis can never change semantics of underlying expression
2. VB: Always generated as parenthesis may change the semantics of underlying expression.

I think we should change 2. so we generate an IParenthesizedExpression only when parenthesis change the semantics of underlying expression in VB, so that the semantics of this operation are clearly defined in a language agnostic fashion. We should update the doc comment on IParenthesizedExpression to explicitly state this and also add an assert in ctor of ParenthesizedExpression.

**Comment by bkoelman** [comment]
Interesting, I have always wondered in what C# code snippet this operation would surface. Well, never, as it turns out. It would be helpful for others to document that on the type.

**Comment by mavasani** [comment]
Design decision: Generate parenthesized operations for C#. This makes it consistent and avoids surprises where GetOperation returns null for a parenthesized expression node.
