### ISSUE TITLE
The "Create new type" dialog layout breaks for long type names

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22750]
Ported from https://developercommunity.visualstudio.com/content/problem/129992/the-create-new-type-dialog-layout-breaks-for-long.html

Version used: 15.4

As you can see below, it also messes up the dropdowns.

![image](https://user-images.githubusercontent.com/235241/31735518-07a6caca-b3f7-11e7-94d7-3210a70ff2c1.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of impact and feedback.
