### ISSUE TITLE
Naming style code fix does not insert underscores between words

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#22754]
**Version Used**: 15.5 preview 1

**Steps to Reproduce**:

Create a style definition for a common test naming style.

1. Add an `.editorconfig` file with the following:

```ini
[*.cs] 
dotnet_naming_rule.public_methods_all_lowercase_with_underscores.symbols= public_methods
dotnet_naming_rule.public_methods_all_lowercase_with_underscores.style = lowercase_with_underscores
dotnet_naming_rule.public_methods_all_lowercase_with_underscores.severity = error

dotnet_naming_symbols.public_methods.applicable_kinds = method
dotnet_naming_symbols.public_methods.applicable_accessibilities = public

dotnet_naming_style.lowercase_with_underscores.capitalization  = all_lower
dotnet_naming_style.lowercase_with_underscores.word_separator = _
```

2. Have code like the following:

```C#
class C
{
    public void ThisIsMyMethod()
    {
    }
}
```

3. Apply fix for naming style violation

**Expected Behavior**:

Method name is changed to all lowercase with underscores: `this_is_my_method`.

**Actual Behavior**:

Method name is changed to all lowercase with common underscores: `thisismymethod`.

![image](https://user-images.githubusercontent.com/116161/31747215-64049026-b420-11e7-90d2-9c93093350a1.png)

**Comment by 06needhamt** [comment]
I am interested in working on this issue. But as I have not contributed to Roslyn before I am not sure where to start. I have already forked downloaded and built Roslyn on my machine and signed the CLA.

Any Help would be great
Thanks

**Comment by 06needhamt** [comment]
PR is Out! #22831
