### ISSUE TITLE
Only add d__x to Async StateMachine when name collisions

### ISSUE THREAD

**Issue by benaadams** [dotnet/roslyn#22761]
Currently statemachines created in the same namespace (or perhaps assembly?) have an ever increasing sequence of `d__N` append to their names

![StateMachine Names](https://aoa.blob.core.windows.net/aspnet/statemachine-names.png)

e.g.
```
<Main>d__0
<AsyncMethod>d__1
<DelayedAsync>d__2
<IntermediateAsync>d__3
```
Is there any need to do this except when there are name collisions?

/cc @JamesNK

**Comment by tmat** [comment]
Yes there is. Why is this a problem?

**Comment by benaadams** [comment]
>  and supports EnC infrastructure

Fair enough :)
