### ISSUE TITLE
Feature Request: adding "when" clause to "yield return"

### ISSUE THREAD

**Issue by mspost** [dotnet/roslyn#22762]
Instead of writing this:
 
```
     IEnumerable<string> foo()
     {
           var stringValue = myVariable.GetOtherValue();
           if (stringValue != null)
                yield return stringValue;
     }

``` 
I would like to be able to write this:
 
     IEnumerable<string> foo()
     {
           yield return myVariable.GetOtherValue() when v => v != null;
     }
 
This seems like a natural extension to the way 'when' is used by exceptions.  Alternatively, given the way a property setter has a fixed value 'value', it could be done that way as well, like this:

```
     IEnumerable<string> foo()
     {
           yield return myVariable.GetOtherValue() when value != null;
     }

```

Since a property setter would never need a yield return, this may be a cleaner way to proceed.

**Comment by jcouv** [comment]
This is a language design discussion, not a compiler bug. I'll move to csharplang repo.

**Comment by jcouv** [comment]
Issue moved to [dotnet/csharplang #1017](https://github.com/dotnet/csharplang/issues/1017) via [**ZenHub**](https://www.zenhub.com/)

**Comment by julielerman** [comment]
sorry, my bad. It was I who pointed Michael to the roslyn repo!

**Comment by jcouv** [comment]
No worries. It's easy to relocate.
