### ISSUE TITLE
CodeRefactoringProvider is not loaded any more

### ISSUE THREAD

**Issue by smourier** [dotnet/roslyn#22765]
**Version Used**: 
Visual Studio 2017 15.4.0, roslyn 2.4.0.0, latest released versions of all.

**Steps to Reproduce**:
1. Clone and compile this simple VSIX project here https://github.com/smourier/VSIXProject1
2. Debug using VS 2017's devenv.exe /rootsuffix Exp
3. Create a CSharp project (library, console, etc.)
4. Type some code and invoke the Quick Actions and Refactorings context menu item

**Expected Behavior**:
The VSIXProject1 dll should be loaded and we should enter the ComputeRefactoringsAsync method.

Code is this:

    [ExportCodeRefactoringProvider(LanguageNames.CSharp, Name = nameof(Refactoring1)), System.Composition.Shared]
    internal class Refactoring1 : CodeRefactoringProvider
    {
        public sealed async override Task ComputeRefactoringsAsync(CodeRefactoringContext context)
        {
            var root = await context.Document.GetSyntaxRootAsync(context.CancellationToken).ConfigureAwait(false);
            if (root == null)
                return;
        }
    }

**Actual Behavior**:
It's not loaded, method is never called.

I'm posting this because initially, I have this VSIX extension here https://marketplace.visualstudio.com/items?itemName=vs-publisher-591.EnumCaseGenerator (source is here: https://github.com/smourier/EnumCaseGenerator) that used to work fine with VS 2015 and VS 2017 and now it does not work (never loaded) in neither of these environments. I've done all sort of testings, uninstall, reinstall, etc., and in the end, the problem is they are just never loaded. There's not error that could help. Has something changed with 3rd party CodeRefactorings loading?

**Comment by paul1956** [comment]
Try waiting a long time (minutes in my case). I am seeing the same thing but If I continue to retry the Quick Actions and Refactoring context menu item eventually my code will be called and I will be offered the refactoring. The errors I am trying to fix appear as soon as I change to the new document, this is a new issue with 15.4 and 15.4.1.

**Comment by smourier** [comment]
The long time may be coming from pdb symbols being loaded. In my case, there are quick actions available, but only the build-in ones. I can wait hours, it doesn't change anything. My dll is never loaded. I've just updated to 15.4.1 and it doesn't work any better...

**Comment by paul1956** [comment]
The built-in ones and my code refactoring's are available immediately but CodeFixes take 10 or more minutes every time I change documents and it is not related to the size of the document but it related to solution size. I don't know if I should open a separate issue or even how to produce a simple case to reproduce.

**Comment by smourier** [comment]
It looks like it was fixed with Visual Studio updates (I'm running Visual Studio 2017 15.4.2)
