### ISSUE TITLE
Investigate performance improvement for GetDiagnostics

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#22770]
In large files containing large numbers of blocks, a diagnostic analyzer which called `GetDiagnostics` on blocks performed poorly (#22637). This was unexpected, since the original intent of the semantic model was caching expensive data so it can be reused. Analyzers written with a similar pattern to the original form would benefit if `GetDiagnostics` was optimized to support this scenario.

**Comment by mavasani** [comment]
This issue actually caused a big performance bottleneck when we tried to implement `IOperation.HasErrors` which invoked `GetDiagnostics(span)` for the underlying operation, see https://github.com/dotnet/roslyn/pull/20990#issuecomment-317134305. If we want to ever support that API, we will need to fix this.

**Comment by CyrusNajmabadi** [comment]
Closing this out as i don't think this bug helps us.  We're aware of issues here.  So if we wnat to do anything we should drive it with a plan with a realistic milestone.
