### ISSUE TITLE
Visual Studio does not like OneDrive Files On-Demand

### ISSUE THREAD

**Issue by trparky** [dotnet/roslyn#22780]
**Version Used**: 
Microsoft Visual Studio Community 2017
Version 15.4.0

**Steps to Reproduce**:
1. Enable OneDrive Files On-Demand in the new Windows 10.
2. Open project contained in OneDrive.

**Expected Behavior**:
Well, I sort of expect it to work.

**Actual Behavior**:
Visual Studio is all kinds of broken with it throwing all kinds of errors, everything from "Object disposed" to just off the wall errors I've never seen before. It's completely and utterly broken when working with a project in OneDrive with Files On-Demand enabled.

**Work Around**:
The only workaround that I can find is to disable OneDrive Files On-Demand but that's not good.

**Comment by pigwing** [comment]
i have the same problem,55555555555555

**Comment by Pilchie** [comment]
Thanks for reporting - we believe these issues will be resolved in the next preview of Visual Studio 2017 version 15.5.  See https://developercommunity.visualstudio.com/content/problem/77492/visual-studio-has-a-conflict-with-onedrive-on-dema.html for more details.

**Comment by munrobasher** [comment]
OneDrive files on demand breaks lots of things...
