### ISSUE TITLE
'langword' completion should not appear after typing <

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#22789]
**Version Used**: 15.5 Preview 1

**Steps to Reproduce**:

1. In a documentation comment, type `<se`

**Expected Behavior**:

1. `see` is selected in the completion list
1. `sealed` is not available in the completion list

**Actual Behavior**:

`sealed` is available in the completion list, and is selected by default. The language-specific keywords were only intended to appear in completion if `<` was not typed before it.

❗️ I am hitting this almost every time I try to add a `<see cref="..."/>` to a documentation comment. This is a "typing memory" regression introduced by the new `<see langword="..."/>` completion feature.

**Comment by CyrusNajmabadi** [comment]
> This is a "typing memory" regression introduced by the new <see langword="..."/> completion feature.

Note: this is not exactly a regression of that form.  For example, say the language added an actual ```<seattle>``` tag.  It would not be a regression that ```<se``` selected "seattle", even though people used to just type ```<se``` expecting it to hit ```<see```.  

That said, i agree with you that in this case ```<somelangword``` isn't actually legal, and we should properly be using the ```<``` to know to not offer that. :(

**Comment by davkean** [comment]
I just hit this regression as well, but can you help me understand a few things:

1) Typing `<sealed` and `TAB` results in `<see langword="sealed"/>` not `<sealed` like you are implying.
2) After living with the new behavior for a day, I actually like it. It makes it significantly easier to write the `<see langword="[langword]"/>` construct, I'm not impressed by my original suggestion here: https://github.com/dotnet/roslyn/issues/11490.

**Comment by sharwell** [comment]
@davkean You can get `<see langword="sealed"/>` by typing `sealed` and pressing <kbd>Ctrl</kbd>+<kbd>Space</kbd>. This means you can also convert any existing use of e.g. `null` in a documentation comment with `<see langword="null"/>` by placing the caret anywhere within the word and pressing <kbd>Ctrl</kbd>+<kbd>Space</kbd>.
