### ISSUE TITLE
Analyzer or warning for NullReferenceException in 'await Foo?.Bar()'

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#22784]
**Version Used**: 
Visual Studio 15.3.5 + C# 7.0

**Steps to Reproduce**:

1. Write some code similar to `await this.quickInfoBroker.GetSession(this.textView)?.DismissAsync(CancellationToken.None)`. Note the use of the `?.` operator.
2. Call in such a way that GetSession() returns null.

**Expected Behavior**:
Based purely on appearance, it’d be reasonable to assume that the code, once compiled, would be roughly equivalent to this, in keeping with the behavior of `?.` in synchronous scenarios.

            var task = null;
            var session = this.quickInfoBroker.GetSession(this.textView);

            if (session != null)
            {
                task = session.DismissAsync(CancellationToken.None);
                task.GetAwaiter().OnCompletion(() => ...);
            }

**Actual Behavior**:
In reality, the code is seemingly compiled more like the following:

            var task = null;
            var session = this.quickInfoBroker.GetSession(this.textView);

            if (session != null)
            {
                task = session.DismissAsync(CancellationToken.None);
            }

           task.GetAwaiter().OnCompletion(() => ...);

Though the behavior isn't really incorrect *per se*, as *await* is not specified to perform a null check, it's not immediately apparent what's happening on this line of code because the syntactic sugar of await obscures what's actually happening. Now that the async/await pattern is part of the language, it's probably a breaking change to add a null check as part of the code but the following seem like they would have little chance of being disruptive and would remove this stumbling block for developers:

1. [Most Disruptive]: Generate a null check for each task that is being awaited before calling GetAwaiter() if and only if the expression being awaited can resolve to null due to the presence of a `?.` operator. In other words, if a developer writes `var foo = await foo?.BarAsync()` there is seemingly no reason why they would want to crash with a NRE instead of evaluating to null. The semantics of `?.` in synchronous code make this case seem counterintuitive and easy to miss.

2. [Mildly Disruptive]: Generate a compiler warning or error that can be ignored whenever the conditions from 1. are met. This is still a breaking change for anyone with WarnAsError enabled, but it seems reasonable and overall less disruptive and accomplishes the end goal.

3. [Non Disruptive]: Add a Roslyn analyzer to Visual Studio that can detect this condition and give users a warning/suggestion to fix it in the IDE.

**Comment by gundermanc** [comment]
@jasonmalinowski pointed me to [an existing proposal](https://github.com/dotnet/csharplang/blob/master/proposals/null-conditional-await.md) that is related to this issue, however, I don't think that the referenced `await?` operator addresses my primary concern.

The lack of a null check for the await operator makes async calls using `?.` a bit of a special case that the developer has to be cognizant of. Simply having a warning and clearer exception message seems adequate to aid the developer in prevention/diagnosis without causing breaking behavioral changes.

**Comment by sharwell** [comment]
For now, an analyzer could be written to handle this. However, `await` could be considered an implicit dereference so this would fall into the warnings already planned for the nullable reference types feature. Considering the new feature is intended to catch scenarios just like this, I'm not sure we need to handle it separately (aside from the separate proposal to make `await` support this case without error).

**Comment by Joe4evr** [comment]
> (aside from the separate proposal to make `await` support this case without error)

Which, as linked, is already tracked on the csharplang repo. :)

**Comment by AArnott** [comment]
FWIW the way I "fix" this in my code is syntax like this:

```csharp
await obj?.SomeMethodAsync() ?? Task.CompletedTask;
```

**Comment by CyrusNajmabadi** [comment]
Interesting.  Definitely subtle though.  Once of those cases where precedence isn't super clear.  For example, i initially read that as: ```(await obj?.Something()) ?? Task.CompletedTask```, which would have still null ref'ed.  It's not obvious that it parses as ```await (obj.SomethingMethodAsync() ?? Task.CompletedTask)```.

**Comment by AArnott** [comment]
Agreed. I've gotten used to it, but I'd love to see a better solution.

**Comment by jcouv** [comment]
@CyrusNajmabadi I'll stop by. I don't understand what is the question for NRT.
The behavior for `await` as far as nullability is straightforward, we check the nullability of `expr` in `await expr` and that is correctly implemented as far as I can tell (test `Await_CheckNullReceiver` illustrates, copied below).

Whether the above parses/groups one way or the other seems unrelated to NRT.

``` csharp
        [Fact]
        public void Await_CheckNullReceiver()
        {
            var source = @"
class C
{
    async void M()
    {
        await Async();
    }
    System.Threading.Tasks.Task<string>? Async() => throw null!;
}";
            var comp = CreateCompilation(new[] { source }, options: WithNonNullTypesTrue());
            comp.VerifyDiagnostics(
                // (6,15): warning CS8602: Dereference of a possibly null reference.
                //         await Async();
                Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "Async()").WithLocation(6, 15)
                );
        }
```

**Comment by jcouv** [comment]
Ran a quick test to see if I'm missing something. Here's the current behavior (ie. we produce an NRT warning):
``` chsarp
using System;
using System.Threading.Tasks;
#nullable enable
public class C 
{
    public async Task M(string? x)
    {
        await x?.Async(); // warning CS8602: Dereference of a possibly null reference.
    }
}
public static class Extension
{
    public static Task<String> Async(this string x) => throw null!;   
}
```

**Comment by CyrusNajmabadi** [comment]
If NRT naturally catches thsi, then i'm going to close this out.  The advice would be to move to use NRT which will naturally check for this and warn when appropriate.

Thanks @jcouv

**Comment by AArnott** [comment]
@jcouv's repro wasn't the original issue, [this was](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwKwG5kDEAdgK4A2ZAhgEZkCm6dRN9yUAzJjOgMLrIBvZOhGZOUAByYAbOgCyACiyoA/OgAeASmGihSUQfQBRdQBcmAZwCWAeyJqb6ALzpSFfPsMioATnQ2VADoAQQsATyIAYwVNDwMAX2RElHFuE3MiaztBHW9xaQAeAGVTACcrIgBzAD50UIjozWda0wALUpsAd1dyMgBCXFEkoA===). But it works with NRT too, so I'm satisfied.
