### ISSUE TITLE
Adding a #pragma suppression can mess up trivia

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#228]
Ported from TFS WorkItem: <b>1107386</b>

---

<p><b>Repro Steps:</b></p>

<P><B>Affected Branch:</B> <BR><B>Affected Build:</B> <BR><B>Affected Product Language:</B> <BR><BR><B>Steps to reproduce:</B><BR><BR>1. Create a new C# class library.</P>

<P>2. Add the following method:</P>

<P>&nbsp;</P>

<P><FONT face=Consolas>void M()<BR>{<BR>&nbsp;&nbsp;&nbsp; int x = 5;<BR>&nbsp;&nbsp;&nbsp; // Foo bar baz<BR>}</FONT></P>

<P>&nbsp;</P>

<P>3. Put the cursor on the "int x = 5;" line.</P>

<P>4. Press Ctrl+. to bring up the light bulb.</P>

<P>5. Hit enter to add the #pragmas.</P>

<P>&nbsp;</P>

<P><STRONG>Expected</STRONG></P>

<P>The indentation of "// Foo bar baz" remains the same.</P>

<P>&nbsp;</P>

<P><STRONG>Actual</STRONG></P>

<P>The comment is pushed over to the right. That is, you end up with something like this:</P>

<P>&nbsp;</P>

<P><FONT face=Consolas>void M()</FONT></P>

<P><FONT face=Consolas>{<BR>#pragma suppress CS2091</FONT></P>

<P><FONT face=Consolas>&nbsp;&nbsp;&nbsp;&nbsp;int x = 5;<BR>#pragma restore CS2091</FONT></P>

<P><FONT face=Consolas>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Foo bar baz<BR>}</FONT></P>

---

<p><b>Revisions:</b></p>

1) Created by Tom Meschter (1/13/2015 12:21:30 PM)

---

2) Edited by Srivatsn Narayanan (1/13/2015 6:46:36 PM)

---

3) Edited by Shyam Namboodiripad (1/14/2015 1:42:19 PM)

This is actually a known bug in the formatter. Unless Kevin is willing to reconsider :) this can be resolved as a dupe of 1079746.

---

4) Edited (Active to Resolved) by Manish Vasani (1/14/2015 2:07:42 PM)

---

5) Edited (Resolved to Active) by Tom Meschter (1/14/2015 2:53:51 PM)

<p>Reactivating.</p>

<p>&nbsp;</p>

<p>I took a look at 1079746 and I think this is a different issue.</p>

<p>&nbsp;</p>

<p>In 1079746 you start with incorrectly formatted code, and inserting the suppression fixes the formatting. We may end up formatting things not directly connected to the trivia we're inserting, but the end result is fine.</p>

<p>&nbsp;</p>

<p>In this bug, you start with correctly formatted code, and inserting the #pragma makes it incorrect. So you then have to run &quot;Format Document&quot; or similar to clean up the results of the suppress action.</p>

<p>&nbsp;</p>

<p>I've updated the repro steps to show the output from the suppress action.</p>

---

6) Edited by Srivatsn Narayanan (1/14/2015 3:11:00 PM)

---

7) Edited by Srivatsn Narayanan (1/16/2015 6:00:22 PM)

---

8) Edited by Srivatsn Narayanan (2/3/2015 10:48:00 AM)

---

**Comment by ManishJayaswal** [comment]
@srivatsn @mavasani @tmeschter  Moved this to 1.1 milestone

**Comment by mavasani** [comment]
Issue here seems to be with the formatter. The Suppression code fix provider creates a `PragmaWarningCodeAction` whose [`GetChangedDocumentAsync`](http://source.roslyn.io/#q=PragmaWarningCodeAction.GetChangedDocumentAsync) seems to generate a new node with correct trailing trivia, but formatter seems to format the comment on next line to have same number of spaces as the added `#pragma warning restore CS0219`", rather than the original code statement `int x = 5;`

Set a breakpoint [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.PragmaWarningCodeAction.cs,52) to observe the above behavior.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  Closing out.
