### ISSUE TITLE
Mark Statemachines with attribute to identify generating method

### ISSUE THREAD

**Issue by benaadams** [dotnet/roslyn#22803]
e.g. a `BuilderMethodAttribute` corefx issue https://github.com/dotnet/corefx/issues/24795

## Motivation

From looking at a stack trace (or using the `StackFrame`s) there's a lot of noise; but perhaps more importantly there isn't enough detail to tell what overloads of a method were called for async and iterators due to the name mangling prior to `.MoveNext()`.

e.g.
```csharp
at Program.<MethodAsync>d__11.MoveNext() 
```
Which of these overloads is it?
```csharp
public async Task<int> MethodAsync(long count, string name);
private static async Task<int> MethodAsync(long count);
private async Task<int> MethodAsync(int count);
```

Using stack traces can be made a more productive experience; whether trying to identify causes from logs and what code to look at, or just to not be daunting to new developers. 

e.g.

Useful stack trace output
```
   at System.Linq.Enumerable.SkipWhileIterator[TSource](IEnumerable`1 source, Func`3 predicate)
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Program.LinqIteration(Int32 count)
   at Program.Iterator(Int64 count, Int32 value)
   at Program.MethodAsync(Int32 count) 
   at Program.ConfiguredAsync(Int32 count)
   at Program.Main(String[] args) 
```
Rather than the more impenetrable 
```
   at System.Linq.Enumerable.<SkipWhileIterator>d__179`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Program.LinqIteration(Int32 count) 
   at Program.<Iterator>d__4.MoveNext()
   at Program.<MethodAsync>d__14.MoveNext()
   at Program.<ConfiguredAsync>d__13.MoveNext()
   at Program.<Main>d__0.MoveNext()
```

## Proposed Api

```csharp
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Constructor | AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
    public class BuilderMethodAttribute : Attribute
    {
        public BuilderMethodAttribute(MethodBase builderMethodType)
        {
            BuilderMethodType = builderMethodType;
        }

        public MethodBase BuilderMethodType { get; }
    }
}
```

## Usage
A compiler (e.g. Roslyn) would add the attribute to the generated class/struct/method that the method builds e.g.
```
.class auto ansi sealed nested private beforefieldinit '<MethodAsync>d__11'
       extends [System.Runtime]System.Object
       implements [System.Threading.Tasks]System.Runtime.CompilerServices.IAsyncStateMachine
{

  .custom instance void 
  CompilerGeneratedAttribute::.ctor() = ( 01 00 00 00 )   
  BuilderMethodAttribute::.ctor(class System.Reflection.MethodInfo) = ...MethodAsync(int count)...
} // end of class '<MethodAsync>d__11'

```

## Related Items

Currently the Builder Method for async/iterators is marked with either `IteratorStateMachineAttribute` or `AsyncStateMachineAttribute` which points at statemachine Type which gets constructed; however there is no-reverse linkage; so it is not possible only using the type system (short of searching) to match back to the source method.

PDBs produce line numbers for the source code rather than generated code; but you don't always have pdbs to produce line numbers. 

Equally it would be useful if stack traces reflected the source code rather than adjunct code 

i.e.
For 99% of cases is 
```
at System.Linq.Enumerable.<SkipWhileIterator>d__179`1.MoveNext()
```
more or less helpful than?
```
at System.Linq.Enumerable.SkipWhileIterator[TSource](IEnumerable`1 source, Func`3 predicate)
```
## Questions

* Is it enough to also cover more general Generators?
* Don't think it covers anonymous types (e.g. lambas/closures)

**Comment by HaloFour** [comment]
@benaadams 

Reading through the coreclr/corefx issues.  Great work!  I've always wanted something like this.  I wrote my own StackTrace formatting code to log exceptions without the async/iterator nastiness some time ago and ran into the same problems.  I relied on the C#-specific name mangling to at least identify the method group of the generator methods but there was no way to disambiguate between overloads.

**Comment by aelij** [comment]
I think this can work for any compiler-generated code (lambdas, iterators, and async). Essentially all of them exist within the scope of a parent method. The compiler would just have to locate the top-level method to emit.

With lambdas though, not specifying the mangled method name could be confusing, since they could run completely out of the scope of the containing method. VS formats the names:
`<Main>b__0_0` -> `Main.AnonymousMethod__0_0`

There's also the case of local functions (which are especially useful for writing iterators); that could be a little more [tricky](https://blogs.msdn.microsoft.com/seteplia/2017/10/03/dissecting-the-local-functions-in-c-7/).

Perhaps include a suggested name (string) in addition to the method token? That could work for both local functions and lambdas.

**Comment by benaadams** [comment]
Local functions are a bit wild

**Comment by benaadams** [comment]
> Perhaps include a suggested name (string) in addition to the method token? That could work for both local functions and lambdas.

Something like:

Local function => Name
Lambda => Lambda_N or Expression_N
Closure => Closure_N or CapturingLamba_N or ExpressionLamba_N

**Comment by benaadams** [comment]
Looks like for source method, attribute will need to be `Type` `MethodName` - can match statemachine to overloads that way; but wouldn't be able to match Local functions or lambdas to an overload that way

**Comment by tmat** [comment]
Now consider async lambda :)

**Comment by benaadams** [comment]
Gone another way
