### ISSUE TITLE
add unit tests for ISymbolSearchService and its related interfaces

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#22808]
we found a regression on the service. we should add tests including OOP parts for it.

**Comment by heejaechang** [comment]
tagging @jinujoseph @dpoeschl

**Comment by heejaechang** [comment]
related to https://github.com/dotnet/roslyn/issues/22806

**Comment by CyrusNajmabadi** [comment]
This feature does have tests for it.  Closing out.
