### ISSUE TITLE
Property is completed in C# object initializer despite being read-only

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#22816]
**Version Used**: 
Visual Studio 2017 (15.5.0 Preview 1)

**Steps to Reproduce**:

````
       //Put this class
        public class OnlyGets {
            public string[] First { get; } = new[] { ""};
            public long[] Second { get; } = new[] { 0L };
        }

            var C = new OnlyGets() {
              //When you create one like this, First and Second both show up as suggested autocompletes but you can't do anything with them.  Shouldn't they not be listed at all?
            };

````

**Expected Behavior**:
No members show up in AutoComplete when I do var C = ....

**Actual Behavior**:
Both First and Second actually show up even though there is no way I can assign anything to them.

**Comment by svick** [comment]
The fixed issue https://github.com/dotnet/roslyn/issues/13158 is almost the inverse of this one. Its fix (https://github.com/dotnet/roslyn/pull/20726) seems to check whether the type or *an interface it implements* has an `Add` method. And array does have that, `T[]` implements `IList<T>`, which has `Add(T)`. But array implements it implicitly, so `new OnlyGets() { First = "" }` doesn't actually compile. I think that check should be modified to account for implicit interface implementations.

(This is a repost of a comment on the original issue (https://github.com/dotnet/csharplang/issues/1038), which I'll delete shortly.)

**Comment by sharwell** [comment]
```csharp
var obj = new OnlyGets()
{
  Second = { [0] = 1 }
};
```

**Comment by sharwell** [comment]
:memo: This is also related to #15205.
