### ISSUE TITLE
PathMap incorrectly handles unix-style root path 

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#22815]
On Windows running this command:

```
D:\temp>csc a.cs /debug:portable /pathmap:D:\temp=/
```

produces document name ```\a.cs``` in the PDB while I expect it to be ```/a.cs```. 

The problem is the combination of trimming separators here:

http://source.roslyn.io/#Microsoft.CodeAnalysis/CommandLine/CommonCommandLineParser.cs,209

and then then not having the separator available in this check:

http://source.roslyn.io/#Microsoft.CodeAnalysis/FileSystem/PathUtilities.cs,643 

As a result we flip the separator from ```/``` to ```\```.

**Comment by tmat** [comment]
@jaredpar @gafter

**Comment by jcouv** [comment]
@khyperia Good to close?
