### ISSUE TITLE
VB: Editor should provide option to preserve whitespace around assignment operator.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#22818]
**Version Used**: 

Visual Studio Community 2017 v15.3.3

**Steps to Reproduce**:

Over the years VB's pretty printer has become "less aggressive" which is quite handy when formatting code for readability/clarity. For example, with the relaxation around line continuation characters we can now easily write this:

```vb
Dim SomeNumber = NumberOne +
                 NumberTwo +
                 NumberThree
```

This flexibilty also applies to the assignment operator, so you can do this:

```vb
Dim SomeNumber = 
    NumberOne +
    NumberTwo +
    NumberThree
```

In the above case, the pretty printer doesn't try to remove the white space between the assignment operator and the first expression, it just leaves it the way you wrote it. However, if the whitespace is a sequence of just tabs/spaces, it insists on removing them so you CAN'T write code that looks like this:

```vb
  With SomeObj
   .ShortName      = Whatever() '<--- pretty printer will remove the spaces before =
   .MuchLongerName = WhateverMore()
   .X =              BlahBlah() '<--- pretty printer will remove the spaces after =
  End With
```

**Expected Behavior**:

It should be possible to tell the pretty printer to preserve all kinds of whitespace (not just line breaks) around symbols (e.g. brackets) and operators (e.g. the assignment operator). This would probably be an addition to the settings under `Options > Text Editor > Basic > Code Style`.

If the request requires significant changes, then an interim quick fix is to just target the assignment operator and allow spaces before/after it. This would allow lining up the left and right hand sides of multiple assignments which appear one after another in separate lines:

```vb
Dim LooooooongName = Foo()
Dim LooooongName   = Foo()
Dim LooongName     = Foo()
Dim LongName       = Foo()
```

**Comment by CyrusNajmabadi** [comment]
Not planning on touching vb formatting at all.
