### ISSUE TITLE
Dynamic invocations + `in` arguments

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#22813]
Master branch @ 24.10.2017.

The following invocations produce the same dynamic call site:
```
class C {
  void M(dynamic d) {
    d.D(d);
    d.D(in d);
  }
}
```

Either disallow `in` modifier in dynamic invocations at all or emit `ref` argument passing instead (this should work with `in` parameters, isn't it?).

p.s. Will `Microsoft.CSharp.dll` be updated to support `in` parameters to allow implicitly `in` arguments passing? cc @VSadov

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/issues/22648

**Comment by VSadov** [comment]
`in` arguments are not expressible in either expression trees or in dynamic.
We should block these scenarios until it is possible to emit such code

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/24164
