### ISSUE TITLE
DiagnosticAnalyzerAttributeAnalyzer and other type initializers are throwing exceptions

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#2281]
I'm seeing this in the Messages area of the VS2015 error list.

| Code | Description |
| ---- | ------- |
| AD0001	| The User Diagnostic Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpRegisterActionAnalyzer' threw an exception with message 'The type initializer for 'Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerCorrectnessAnalyzer' threw an exception.'. |
| AD0001	| The User Diagnostic Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerFieldsAnalyzer' threw an exception with message 'The type initializer for 'Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerFieldsAnalyzer`4' threw an exception.'. |
| AD0001	| The User Diagnostic Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpReportDiagnosticAnalyzer' threw an exception with message 'The type initializer for 'Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerCorrectnessAnalyzer' threw an exception.'. |
| AD0001	| The User Diagnostic Analyzer 'Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerAttributeAnalyzer' threw an exception with message 'The type initializer for 'Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerAttributeAnalyzer' threw an exception.'. |

(note to self for repro details: This was with the "VS MEF" solution open to the StyleCop branch)

**Comment by tmeschter** [comment]
@AArnott Which build of VS are you using?

**Comment by AArnott** [comment]
VSPro_Platform 22820.00

**Comment by srivatsn** [comment]
I suspect this is due to some binary mismatch. @tmeschter can you take a look?

**Comment by tmeschter** [comment]
@AArnott How were these analyzers added to the project? Did you add them yourself, or did they come along as part of a project template?

**Comment by AArnott** [comment]
I believe they were installed to my project because I had installed the Microsoft.CodeAnalysis.CSharp NuGet package to my project.

**Comment by tmeschter** [comment]
I haven't been able to reproduce this with a VSPro_Platform build using the analyzers from the corresponding build of Roslyn. However, this is the sort of error I would expect if there were a binary mismatch between the two (that is, the analyzers were built against a newer/older drop of Roslyn than what is installed with VS).
