### ISSUE TITLE
How should csharp_style_expression_bodied_methods be defined in editorconfig

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#22826]
It is unclear how one should define &quot;When on single line&quot; value for csharp_style_expression_bodied_methods and alike settings in editorconfig. 

ttps://github.com/dotnet/roslyn/blob/master/.editorconfig has a sample using true/false but these settings have 3 values: Never, When possible and When on single line

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/133053/how-should-csharp-style-expression-bodied-methods.html
VSTS ticketId: 510478_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎10‎/‎23‎/‎2017, 06:04 PM (14 hours ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
@kuhlenh It seems the [documentation page](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference) is missing information about the `when_on_single_line` value allowed for these options.

**Comment by kuhlenh** [comment]
This is now documented on [docs.microsoft.com](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#expression_bodied_members).

**Comment by Listbd** [comment]
No sure if it used to be documented at docs.microsoft.com, but it isn't today (7/28/20). After lots of searching finally found this.

**Comment by jmarolf** [comment]
@Listbd  see [here](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019#csharp_style_expression_bodied_methods)
