### ISSUE TITLE
VS 15.4.1 usage unbearably slow when Git source control plug-in is enabled

### ISSUE THREAD

**Issue by maxdeviant** [dotnet/roslyn#22822]
**Version Used**: Visual Studio Enterprise 2017 v15.4.1

**Steps to Reproduce**:

1. Turn on Git source control integration (`Source Control > Plug-in Selection > Git`)
2. Open up solution inside of Git repository referencing one or more projects in the same repository
3. `git.exe *32` memory usage skyrockets (Figure 1)
4. `git.exe *32` process disappears; `devenv.exe *32` memory skyrockets, which results in severe performance degradation while working in VS (Figure 2)
5. Eventually `devenv.exe *32` crashes and a `System.OutOfMemoryException` is shown in the `Output` pane (Figure 3)

**Expected Behavior**:

Visual Studio should be performant and not consume massive amounts of system resources during the course of regular usage.

**Actual Behavior**:

Visual Studio becomes unbearably slow.

**Additional Info**:

- Turning off the Git source control plug-in prevents the issue from occurring.

- We use a monorepo, but it is not considerably large, see here:

```
$ git gc
$ git count-objects -vH
count: 888
size: 1.18 MiB
in-pack: 293427
packs: 1
size-pack: 245.57 MiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
```

**Figure 1:**

![Figure 1](https://user-images.githubusercontent.com/1486634/31950700-2607c2fa-b8aa-11e7-8fb6-c55db04c7111.png)

**Figure 2:**

![Figure 2](https://user-images.githubusercontent.com/1486634/31950693-22534c2e-b8aa-11e7-9832-a21a41a9e2a7.png)

**Figure 3:**

![Figure 3](https://user-images.githubusercontent.com/1486634/31950857-8e5e35aa-b8aa-11e7-90e4-d175ec436290.png)

**Comment by sharwell** [comment]
Hi @maxdeviant, 

That definitely looks unpleasant (to say the least). I've tried to reproduce this but haven't been successful so far. Can you follow the steps in the following page to provide us with data to resolve this? After filing the feedback ticket(s), you can add a comment here with a link to them and I'll go hunt this down. 😄 

https://github.com/dotnet/roslyn/wiki/Reporting-Visual-Studio-crashes-and-performance-issues

**Comment by maxdeviant** [comment]
FWIW this no longer seems to be an issue in VS2019.
