### ISSUE TITLE
[Proposal] Catch StackOverflow with special attribute

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#22829]
>Starting with the .NET Framework  version 2.0, a StackOverflowException  object cannot be caught by a try-catch  block and the corresponding process is  terminated by default. Consequently,  users are advised to write their code  to detect and prevent a stack  overflow.

**Proposal**

Why make it hard for users to deal with SO?

Some methods are prone to SO exception, not by infinite recursive, but simply because recursion becomes too deep, some times `stackalloc` can cause this exception too.

>In prior versions of the .NET  Framework, your application could  catch a StackOverflowException object  (for example, to recover from  unbounded recursion). However, that  practice is currently discouraged  because significant additional code is  required to reliably catch a stack  overflow exception and continue  program execution.

attaching special attribute should make this possible and user is aware of performance or memory overheads.

```
[CatchStackOverflowException]
void Method_SO_Catchable()
{
}
```

**Comment by svick** [comment]
I don't think this a proposal for Roslyn. The compiler has no way to catch the exception, it's the runtime that has to let you do that. As such, I think this proposal belongs to [the CoreCLR repo](https://github.com/dotnet/coreclr/).

**Comment by MkazemAkhgary** [comment]
thanks for noting that. ill move this issue. @svick
