### ISSUE TITLE
Disable code analysis for generated code in SDK-style csproj

### ISSUE THREAD

**Issue by kentcb** [dotnet/roslyn#22860]
Ultimately I am trying to exclude all the _.xaml.g.cs_ files from code analysis when consuming Xamarin.Forms from a netstandard library. This does not seem to be possible, making CA next to useless for Xamarin.Forms projects.

**Version Used**: 

SDK-style csproj in VS2017.

**Steps to Reproduce**:

1. Create SDK-style project.
2. Make sure there is some generated code, like a Resources.resx
3. Install some analyzers

**Expected Behavior**:

Analyzers not applied to generated code.

**Actual Behavior**:

Analyzers are applied to generated code.

**Additional Info**:

I tried adding `<CodeAnalysisIgnoreGeneratedCode>true</CodeAnalysisIgnoreGeneratedCode>` to my csproj but it did not help.

**Comment by kentcb** [comment]
Seems one trick is to add this to the `Initialize` method of the diagnostic:
```C#
context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
```
However, this assumes the consumer has control over the diagnostic, which is true in my case, but am guessing not always.

Also, the heuristic appears to be that generated code is anything with `[GeneratedCode]` or an `<auto-generated>` header. It does _not_ appear to honor `[CompilerGenerated]`.

**Comment by normanhh3** [comment]
@kentcb can you clarify where this ```Initialize``` method you reference is?

**Comment by sharwell** [comment]
> Analyzers not applied to generated code.

This behavior is controlled by the analyzer. Some analyzers, e.g. security analyzers, need to analyze generated code. Others do not. Do you have a link to the specific analyzer which is causing problems?

> Also, the heuristic ... does not appear to honor `[CompilerGenerated]`.

@kentcb Exclusions based on attributes causes tremendous performance overhead. The `GeneratedCode` behavior unfortunately slipped in, but #20498 should allow projects to selectively disable this code path. New attribute-based exclusions should be aggressively avoided.

**Comment by kentcb** [comment]
@normanhh3 I'm talking about the `Initialize` method in the analyzer itself - ie. the subclass of `DiagnosticAnalyzer` can override an `Initialize` method and specify the desired behavior there.

@sharwell It was my own analyzer. I just didn't realize at the time that it was the analyzer itself making this decision rather than the consumer.
