### ISSUE TITLE
We should consider simplifying an assert in BoundInterpolatedStringExpression.Validate 

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#22869]
See https://github.com/dotnet/roslyn/pull/22795#pullrequestreview-71284928

src/Compilers/VisualBasic/Portable/BoundTree/BoundInterpolatedStringExpression.vb
@@ -36,6 +36,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
 #If DEBUG Then
         Private Sub Validate()
             Debug.Assert(Type.SpecialType = SpecialType.System_String)
+            Debug.Assert(Not Contents.Where(Function(content) content.Kind <> BoundKind.Interpolation AndAlso content.Kind <> BoundKind.Literal).Any())
      @jcouv
jcouv 3 days ago Member
Consider simplifying: Contents.All(Function(content) content.Kind = Interpolation OrElse content.Kind = Literal)

**Comment by gafter** [comment]
We don't see any value in the suggestion.
