### ISSUE TITLE
Severity Code	Description Project File Line Suppression State Error "csc.exe" exited with code -1073741819.

### ISSUE THREAD

**Issue by denzelition** [dotnet/roslyn#22866]
**Version Used**: Microsoft Visual Studio Community 2017 Visual C# 2017 

**Steps to Reproduce**:

Try to run any build whatsoever. Like literally something as simple as "Console.Write("hey"); Console.ReadLine();"

**Expected Behavior**: The code runs. The console pops up and I see "hey" and then press Enter to exit it.

**Actual Behavior**: Building takes very long and eventually fails with this error. It's always the same error, no matter what code I use. I've also added the output.

Severity	Code	Description	Project	File	Line	Suppression State
Error		"csc.exe" exited with code -1073741819.	test			

1>------ Build started: Project: test, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.exe" exited with code -1073741819.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I'm sorry if I'm posting this in entirely the wrong place, I'm a simple first year Multimedia and CommunicationTechnology student so I know extremely little of this. I've done a little digging and apparently something's wrong with my compiler? That sounds really bad. I hope this can be fixed, because as it stands I cannot study for my Programming exam in two weeks. :c

![image](https://user-images.githubusercontent.com/33123042/32052323-311f1670-ba58-11e7-83c4-a93291e2d0ba.png)
![image](https://user-images.githubusercontent.com/33123042/32052391-6301a086-ba58-11e7-824a-dbaa5735aed2.png)

**Comment by jcouv** [comment]
Sorry you're having such a bad experience (compiler crash).
To figure out the root of the crash, I would need a crash dump (here are [instructions](https://github.com/dotnet/roslyn/wiki/Troubleshooting-tips#using-a-registry-setting) on getting one, basically set a registry key, then repro the problem, save the resulting dump file).

If you want to get unblocked for your exams, you could also try updating Visual Studio (see the yellow flag in the top right corner).

**Comment by jcouv** [comment]
@denzelition Were you able to update Visual Studio, or capture a crash dump, by any chance?

**Comment by denzelition** [comment]
@jcouv Ah, sorry for taking so long with the response. I've uhh... circumvented the issue by manually deleting the folders Visual Studio is located in and reinstalling. I did this because the Installer didn't do anything, regerdless of permisssions or wether or not it was a fresh copy off of the official website.

So, I just deleted everything, got a fresh installer and everything seems fine now. I suppose that didn't exactly fix the issue, but at least I can study for my exams. "^^

Sorry again for the late reply and the fact that I'm probably no help in fixing this.

**Comment by jcouv** [comment]
Glad things worked out.
I'll have to close the issue as we don't have much information to narrow or repro the issue (does sound like a setup issue). If you encounter this again, please try the "report an issue" button in Visual Studio, as it may capture more information about the state of the installation. Thanks
