### ISSUE TITLE
Provide analyzers with msbuild item metadata for the documents they analyze

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#2287]
The StyleCop.Analyzers project is positioned to replace the legacy StyleCop tools, which supported the user setting ExcludeFromStyleCop=false metadata on a source file to prevent messages being generated based on style issues in that particular file. But Roslyn analyzers can't see such metadata.

These are some reasons why the metadata remains useful:

1. The metadata approach is useful when I can’t control the content of the file (I’m sharing it with another project that I don’t have the freedom to change), and the file doesn’t conform to StyleCop rules.
1. If I can change the file to suppress the messages, what #pragma would I use in the file to suppress all StyleCop messages? There are dozens of rules that are violated by the files I have in mind. Is there a single #pragma that can suppress them all?

See DotNetAnalyzers/StyleCopAnalyzers#726 which tracks this on the StyleCop.Analyzers side.

**Comment by pharring** [comment]
How about MSBuild metadata for suppressing *all* Roslyn analysis on a file. Rather like ```ExcludeFromStyleCop=true```, this would be ```ExcludeFromCodeAnalysis=true```. It's not fine-grained, per-analyzer suppression, but it is a good start.

**Comment by AArnott** [comment]
Yes, that would seem to suit the use case quite well.

**Comment by heejaechang** [comment]
can we modify suppressMessageAttribute to cover this case as well? this one seems just another suppression.

**Comment by srivatsn** [comment]
If we allow for a configuration file at the project level that lets you specify which files to exclude from analysis, this scenario is solved. We wouldn't want to do work specific to msbuild and repeat that for other project systems.

**Comment by srivatsn** [comment]
#3705 tracks the work to provide a configuration file to specify which files to exclude from analysis.
