### ISSUE TITLE
Assert about multiple explicit operation nodes with same syntax in VB

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22879]
I tried to add following VB test as part of https://github.com/dotnet/roslyn/pull/22846 without doing any source changes and I see the following assert fire: `Assert.False(true, $"Duplicate explicit node for syntax ({operation.Syntax.RawKind}): {operation.Syntax.ToString()}");` where both IDelegateCreation and IAnonymousObjectCreation have same syntax

```
        <CompilerTrait(CompilerFeature.IOperation)>
        <Fact>
        Public Sub TestParenthesizedDelegateCreationParent()
            Dim source = <![CDATA[
Class P
    Private Shared Function M1() As Object
        Return CType((Sub() System.Console.WriteLine()), System.Action)'BIND:"CType((Sub() System.Console.WriteLine()), System.Action)"
    End Function
End Class]]>.Value

            Dim expectedOperationTree = <![CDATA[
]]>.Value

            Dim expectedDiagnostics = String.Empty

            VerifyOperationTreeAndDiagnosticsForTest(Of CTypeExpressionSyntax)(source, expectedOperationTree, expectedDiagnostics)
        End Sub
```

**Comment by mavasani** [comment]
Tagging @AlekseyTs

**Comment by AlekseyTs** [comment]
@mavasani Could you temporarily suppress the assert so that you can get the tree and add it to the issue?
