### ISSUE TITLE
Formatting throws an unhandled NullReferenceException after upgrading to 2.x

### ISSUE THREAD

**Issue by jega327** [dotnet/roslyn#22870]
**Version Used**: 

2.4.0

**Steps to Reproduce**:

Run the following sample code:

```
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Formatting;
using System.Collections.Generic;

namespace FormatterTest {
    class Program {
        static void Main(string[] args) {

            var workspace = (AdhocWorkspace)new AdhocWorkspace().AddProject("Project", "C#").Solution.Workspace;

            var modifiers = new List<SyntaxToken>();
            modifiers.Add(SyntaxFactory.Token(SyntaxKind.PublicKeyword));

            ClassDeclarationSyntax testClass = SyntaxFactory.ClassDeclaration("FormattingTestClass")
                .WithModifiers(SyntaxFactory.TokenList(modifiers))
                .WithLeadingTrivia(SyntaxFactory.SyntaxTrivia(
                SyntaxKind.SingleLineCommentTrivia,
                "some comment"));

            var formattedTestClass = (ClassDeclarationSyntax)Formatter.Format(testClass, workspace);
        }
    }
}
```

**Expected Behavior**:

`Formatter.Format()` returns the formatted class like before (1.x Roslyn Version from about December 2016)... or reports an error, if the class' syntax is wrong.

**Actual Behavior**:

Throws an unhandled exception:

_System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.\r\n   bei Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)\r\n   bei Microsoft.CodeAnalysis.CSharp.Formatting.NewLineUserSettingFormattingRule.IsControlBlock(SyntaxNode node)\r\n   bei Microsoft.CodeAnalysis.CSharp.Formatting.NewLineUserSettingFormattingRule.GetAdjustSpacesOperation(SyntaxToken previousToken, SyntaxToken currentToken, OptionSet optionSet, NextOperation`1 nextOperation)\r\n_
[...]

**Comment by jega327** [comment]
I did some further testing and Debugging. The exception was thrown at `var parentKind = node?.Parent.Kind();`, because `Parent` was null.

I checked if just an enclosing namespace is missing, but nope. Looking for an alternative, I discovered that building the SyntaxNodes via a `Document` and `SourceText.From` results in proper formatting:

```
    string sourceText = @"
// some comment
public class FormattingTestClass {
}
";

    Document document = workspace.AddDocument(workspace.CurrentSolution.Projects.Single(p => p.Name == "Project").Id, "Document", SourceText.From(sourceText));

    var formattedTestClass = (Document)Formatter.FormatAsync(document, workspace.Options).Result;
```
Debugging revealed that my class declaration is wrapped with a `CompilationUnitSyntax`. I was able to use this structure with success in my test code:

 ```
       static void Main(string[] args) {

            var workspace = (AdhocWorkspace)new AdhocWorkspace().AddProject("Project", "C#").Solution.Workspace;

            var modifiers = new List<SyntaxToken>();
            modifiers.Add(SyntaxFactory.Token(SyntaxKind.PublicKeyword));

            ClassDeclarationSyntax testClass = SyntaxFactory.ClassDeclaration("FormattingTestClass")
                .WithModifiers(SyntaxFactory.TokenList(modifiers))
                .WithLeadingTrivia(SyntaxFactory.SyntaxTrivia(
                SyntaxKind.SingleLineCommentTrivia,
                "some comment"));

            CompilationUnitSyntax compUnit = SyntaxFactory.CompilationUnit();
            compUnit = compUnit.AddMembers(testClass);

            var formatted = (CompilationUnitSyntax)Formatter.Format(compUnit, workspace);
        }
```

This also does the job for production, so I can use it at least as a workaround.

However, it still looks like a bug to me.

Btw, `CompilationUnitSyntax.WithMembers()` does not accept `ClassDeclarationSyntax` types.

**Comment by CyrusNajmabadi** [comment]
Closing out given lack of customer feedback on this.
