### ISSUE TITLE
Quick actions create duplicate region blocks

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#22881]
Applying quick action IDE0018 (Inline variable declaration) when the code is inside a region block following a previous region block, the second region block gets duplicated.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/137729/quick-actions-create-duplicate-region-blocks.html
VSTS ticketId: 514426_
_These are the original issue comments:_

Michael Bursill on 10/24/2017, 04:57 PM (2 days ago): <p>Recording of problem</p>

_These are the original issue solutions:_
(no solutions)

**Comment by LamerTex** [comment]
This still happens in VS2019 with its Code Cleanup feature, producing a not compiling code!

**Comment by CyrusNajmabadi** [comment]
@LamerTex PRs welcome :)
