### ISSUE TITLE
Bug 60365 - Escaped keywords autocomplete to the unescaped keyword

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#22885]
Type "@class<space>", when hitting space "@class" switches to "class".

See: https://bugzilla.xamarin.com/show_bug.cgi?id=60365

**Comment by Rekkonnect** [comment]
Browsing through very old and dead issues, this one looks for closing:

- Could not replicate this bug
- Original link yields 404

**Comment by CyrusNajmabadi** [comment]
Closing out. Thanks!
