### ISSUE TITLE
Attribute ctor with 'in' parameter + implicit 'in' argument

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#22880]
**Version Used**:

Master branch from 27.10.2017

**Steps to Reproduce**:

```c#
[A(1)]
class A : System.Attribute {
  A(in int x) { }
}
```

**Actual Behavior**:

It compiles :) Cecil [crashes](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4G0CCAKAjASgLoCwAUAAIBMABGhSBSVgHRowwICWwArvBQN7EUqGNgDsKomBQAeOPhQC+xeUA==) when trying to read metadata produced.

**Expected Behavior**:

Compiler error over `1` argument range.

p.s. Error message in the case of passing attribute arguments to `ref`/`out` parameters suggest to use `ref`/`out` modifiers that are not parseable in the context of attribute arguments.

cc @VSadov

**Comment by VSadov** [comment]
Yes, should be an error. Good catch!

**Comment by jcouv** [comment]
@VSadov I feel this is cornercase enough that it wouldn't meet the bar for 15.5. 
15.6 ok?

**Comment by VSadov** [comment]
@jcouv - 15.6  
It would not meet the bar for 15.5 at this point. There are obvious workarounds - "do not do this". 
It is still a bug. Spec should disallow this scenario.

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/23055
