### ISSUE TITLE
Update Roslyn to use RTM version of SDK instead of preview

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#22890]
Follow-up on https://github.com/dotnet/roslyn/pull/22812 which switched us to using SDK `2.1.1-preview-007094`.

Update: it was updated to `2.2.0-preview1-007622` by Jared since.

**Comment by jcouv** [comment]
@jaredpar I had this item tracking updating the SDK to RTM bits. 
Do you think we need to track this? Or should we just leave it on preview version?

**Comment by jaredpar** [comment]
We should just stick with the preview for now
