### ISSUE TITLE
Rename dashboard cross button doesn't look like a cross

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#22892]
**Version Used**: 
VS 2017 15.3
Windows 10 2 monitors, 200% DPI, each monitor 3840x2160
VS light theme, most settings default

**Steps to Reproduce**:

1. In a C# file, rename an element

![image](https://user-images.githubusercontent.com/679326/32119711-f63be6d8-bb0a-11e7-85f8-7c68c98f4e6a.png)

**Expected Behavior**:
Rename dashboard close button in upper right should look like a cross

**Actual Behavior**:
It looks like an empty button on my machine

**Comment by CyrusNajmabadi** [comment]
@ryzngard  this can be closed out now since you rewrote the experience right?
