### ISSUE TITLE
Consider unifying code to extract text from an Xml Documentation Comment

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#2290]
Currently, SignatureHelp and QuickInfo use the same code, but Outlining has it's own codepath that isn't as nice:
- Doesn't handle spaces around punctuation properly.
- Doesn't handle things like generics in crefs.

Note however, that because it synchronously blocks on file open, we probably want to keep outlining syntactic only.

**Comment by sharwell** [comment]
To clarify the last point - it means while special handling for `<see cref="..."/>` or `<see langword="..."/>` would be straightforward improvements, it is unlikely that we would ever see support for *expanding* `<include>` or `<inheritdoc/>` elements as part of the outlining process.

**Comment by Pilchie** [comment]
It's more than just that - the existing quick info code also does things like simplify the typenames in crefs based on usings, etc.  We'll need to make sure there is a path that doesn't do that semantic work.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
