### ISSUE TITLE
Tuple name inference fail to infer @this element name

### ISSUE THREAD

**Issue by SergeyTeplyakov** [dotnet/roslyn#22902]
**Version Used**:  master

**Steps to Reproduce**:

```csharp
class Sample
{
    public void FooBar(int x)
    {
        // (Sample, int x)
        var tpl = (this, x);
    }
}
```

The inferred type is `(Sample, int x)`, but could be `(Sample @this, int x)`.

I work on perf critical application and to avoid closure computation I often pass a tuple into a method similar to [`ConcurrentDictionary.GetOrAdd`](https://github.com/dotnet/corefx/blob/afcbd9a5b9e4ecde2db3a69afd093631f1db91c5/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L1010):

```csharp
class Sample
{
    private readonly ConcurrentDictionary<int, string> _cd = new ConcurrentDictionary<int, string>();

    public string GetValue(int value, bool extraState)
    {
        return _cd.GetOrAdd(
            value,
            (key, tpl) =>
            {
                return tpl.@this.ComputeValue(key, tpl.extraState);
            },
            (extraState, @this: this));
    }

    private string ComputeValue(int value, bool extraState) => value.ToString();
}
```

And in this case, I have to specify a name of the tuple element manually. I understand that my use case is not that common, but I'm curious is there any specific reason why such inference is not implemented? Or this case was just missed?

**Comment by jcouv** [comment]
This is the same behavior as anonymous types: `var x = new { this }; // not allowed` vs `var x = new { @this=this }; // ok`.
I think that's currently by design, so I'll move this suggestion to csharplang repo for discussion.

**Comment by jcouv** [comment]
Issue moved to [dotnet/csharplang #1057](https://github.com/dotnet/csharplang/issues/1057) via [**ZenHub**](https://www.zenhub.com/)
