### ISSUE TITLE
Add Language Support for Pinning Span<T>

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/roslyn#22911]
Today, Span\<T\> can be pinned, but developers have a hard time remembering the syntax/APIs, and it prevents us from hiding DangerousGetPinnableReference, which is, as the name implies, a dangerous API that can be called in safe context. It would be preferable to hide the method and force users to explicitly and exclusively unsafe constructs.

```c#
// this is how it works today
Span<byte> span = new byte[256];
fixed (byte* pSpan = &span.DangerousGetPinnableReference()) {
   ...
}
```

This proposal is to add language support that would allow for the following:
```c#
Span<byte> span = new byte[256];
fixed (byte* pSpan = span) {
   ...
}
```

Similarly for ReadOnlySpan\<T\>

cc: @VSadov, @davidfowl

**Comment by jcouv** [comment]
@VSadov What do you think about this?

**Comment by VSadov** [comment]
I am working on a more general proposal for a pattern-base pinning. 

It should be able to answer the interop question for types such as `ImmutableArray`, `Span`, heapable `Utf8String`, and so on in a more general way. There is clearly a need.

**Comment by davidfowl** [comment]
YESSS!!

**Comment by VSadov** [comment]
FYI: Proposal for the Pattern based fixed statement - https://github.com/dotnet/csharplang/pull/1100

**Comment by VSadov** [comment]
This has been fixed in https://github.com/dotnet/roslyn/pull/25624

Now spans can expose `GetPinnableReference` that returns a [readonly]ref to the first element, or nullptr if span is empty.
