### ISSUE TITLE
Symbol from xmldoc/cref is not constructed

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#22923]
**Version Used**: VS Community 2017 15.4.1

**Steps to Reproduce**:

Let's say I have this code:
```csharp
public class FooException<T> : Exception
{
    /// <exception cref="FooException{T}"></exception>
    private void Foo()
    {
        throw new FooException<T>();
    }
}
```

and I want to check symbols for equality:
```csharp
private static void Foo()
{
    SyntaxTree tree = CSharpSyntaxTree.ParseText(@"
        public class FooException<T> : Exception
        {
            /// <exception cref=""FooException{T}""></exception>
            private void Foo()
            {
                throw new FooException<T>();
            }

        }");

    PortableExecutableReference reference = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);
    CSharpCompilation compilation = CSharpCompilation.Create("Compilation", new SyntaxTree[] { tree }, new MetadataReference[] { reference });
    SemanticModel semanticModel = compilation.GetSemanticModel(tree);
    SyntaxNode root = tree.GetRoot();

    CrefSyntax cref = root.DescendantNodes(descendIntoTrivia: true).OfType<CrefSyntax>().First();
    ObjectCreationExpressionSyntax objectCreation = root.DescendantNodes().OfType<ObjectCreationExpressionSyntax>().First();

    ITypeSymbol a = semanticModel.GetTypeSymbol(objectCreation);
    ISymbol b = semanticModel.GetSymbol(cref);

    Debug.WriteLine(a == b);
    Debug.WriteLine(a == b.OriginalDefinition);
    Debug.WriteLine(b == b.OriginalDefinition);
    Debug.WriteLine(b.OriginalDefinition == b.OriginalDefinition.OriginalDefinition);
}
```

**Output**: 
```
False
True
False
True
```

**Questions**:
* Why `a == b` returns False?
* Why `b == b.OriginalDefinition` returns False?
* If this is correct behavior how can I compare these symbols for equality?

**Comment by sharwell** [comment]
💭 My understanding is symbols cannot be compared reliably using `==` or `!=`. Using `Equals` (or `EqualityComparer<ISymbol>.Default` which uses `Equals` under the hood) is the only supported comparison.

**Comment by JosefPihrt** [comment]
Problem is that `a.Equals(b)` return `false` as well.

I noticed that type of symbol of cref is ConstructedNamedTypeSymbol. Why the symbol is constructed when the expression is FooException\<T\>?

**Comment by sharwell** [comment]
Interesting. The value `T` actually has no semantic meaning in the `cref` attribute. For example, `cref="FooException{T}"`, `cref="FooException{X}"`, and `cref="FooException{Object}"` are all equivalent from the perspective of documentation comments and all resolve to the unqualified type `FooException<T>`.

**Comment by jcouv** [comment]
@JosefPihrt 
Thanks for the detailed repro. I don't think there is a bug here.
`a` is the generic type `FooException'1`, but `b` is a constructed type `FooException<T>` with a `T` defined at the class level.
This constructed type is constructed from the generic type (which is `a`). So `a == b.ConstructedFrom`.

```C#
        [Fact]
        [WorkItem(22923, "https://github.com/dotnet/roslyn/issues/22923")]
        void CRefSymbols()
        {
            SyntaxTree tree = CSharpSyntaxTree.ParseText(@"
using System;
public class MyException<T> : Exception
{
    /// <exception cref=""MyException{T}""></exception>
    private void M()
    {
        throw new MyException<T>();
    }
}");

            var comp = CreateStandardCompilation(tree);
            comp.VerifyDiagnostics();
            var model = comp.GetSemanticModel(tree);
            var root = tree.GetRoot();

            var cref = root.DescendantNodes(descendIntoTrivia: true).OfType<CrefSyntax>().First();
            var objectCreation = root.DescendantNodes().OfType<ObjectCreationExpressionSyntax>().First();

            var a = model.GetTypeInfo(objectCreation).Type as SourceNamedTypeSymbol;
            var b = model.GetSymbolInfo(cref).Symbol as ConstructedNamedTypeSymbol;
            var c = b.ConstructedFrom;

            Assert.False(a == b);
            Assert.True(a == c);

            Assert.True(a == b.OriginalDefinition);
            Assert.False(b == b.OriginalDefinition);
            Assert.True(b.OriginalDefinition == b.OriginalDefinition.OriginalDefinition);
        }
```

I'll go ahead and resolve the issue. Feel free to ping me if that didn't make sense. Cheers

**Comment by jcouv** [comment]
On further reflection, I think this raises the question of whether the symbol from the `cref` should have been constructed too. I don't know the answer.

**Comment by jcouv** [comment]
@dotnet/roslyn-compiler Do you know what is the expected symbol for the `cref` in `/// <exception cref=""MyException{T}""></exception>`? Should we expect a generic type or a constructed type (with `T` from the class definition)?

**Comment by sharwell** [comment]
@jcouv It's not supposed to be constructed.

**Comment by CyrusNajmabadi** [comment]
> It's not supposed to be constructed.

I could see things going one of two ways here.  Because it's a type, and we have no way of representing instantiated generic types in doccomments, we should always just get a non-constructed 'original' type definition here.  i.e.  ```List{X}``` ```List{Y}``` and ```List{Whatever}``` always just give you the 'original' type for ```List<T>```.

However, then there is the case of generic methods.  i.e. something like 

```c#
    /// <summary>
    /// <see cref="Foo{X}(X[])"/>
    /// </summary>
    void Bar()
    {

    }

    void Foo<T>(T[] values)
    {
    }
```

Here we really want that ```X``` to become a real type so that the reference to it in ```X[]``` is a real thing.  If we were just to take the original-method-definition for Foo, then we'd only have type-parameters like 'T'.  It would be very weird (to me at least) to say that 'X' is actually 'T', and not some 'fresh type' called 'T' that we've constructed the Foo method with.  

Given that, for uniformity, i would prefer that for generic types, we have a 'fresh' type variable, and we're always constructing the original type with that fresh type arg.

**Comment by amcasey** [comment]
It looks by design to me.  The two `T`s are unrelated.  You should have `a.OriginalDefinition == b.OriginalDefinition` though.

**Comment by AlekseyTs** [comment]
> It looks by design to me.

This is in line with my recollection of the design. The ```T``` inside ```FooException{T}``` is not a reference to the type parameter in  ```class FooException<T>```. Otherwise, references to APIs in other types simply wouldn't work, the type parameters simply wouldn't be in scope. Therefore, the names inside ```{T}```  do not really matter, each of them "declares" a new "fake" type and ```FooException{T}``` is a reference to a FooException type constructed over the "fake" type named T.

**Comment by jcouv** [comment]
Thanks all for the clarifications. I'll go ahead and close as By-Design.

**Comment by JosefPihrt** [comment]
Thanks for explanation.
