### ISSUE TITLE
Can't report problems

### ISSUE THREAD

**Issue by lostllama** [dotnet/roslyn#22925]
[Video here](https://youtu.be/aaMPxy7jNvc)

**Version Used**: 

Visual Studio 2017 Enterprise v15.4.1

**Steps to Reproduce**:

1. Click "Report a problem"
2. Be told that you need to be signed in.
3. Sign in
4. GOTO 1

**Expected Behavior**:

Login to complete successfully and for me to be able to report a problem.

**Actual Behavior**:

The button always remains as "Sign in" even after being signed in.

---

I used to be able to do this just fine. I used it the day before yesterday with the same version of VS without issues.

If I go onto the VS communtiy website, it tells me to report the problem via Visual Studio. Right...
If I go to the "contact Microsoft" link, it tells me to purchase a support contract to report the problem. I won't get into how shady it is to require someone to purchase a support contract to report a bug with YOUR software, but it's pretty shady.

**Comment by sharwell** [comment]
@lostllama Thanks for taking the time to find another way to get in contact with us. Your feedback is important and someone should reply soon to help figure out why the Report a Problem feature isn't working as expected.

/cc @Pilchie

**Comment by lostllama** [comment]
@sharwell I just tried to open it again just now and it immediately went to the login I had been using previously. Very strange. Temporary server issues, maybe?

**Comment by mariaghiondea** [comment]
Sorry for the issues! From your video, you aren't signed in into Visual Studio either (they are related), which leads me to believe it was a temporary server issue indeed.
Would you mind sending us the contents of your %temp%\servicehub folder to help investigate? It contains sign in log information. You can add them here or email us at vsfeedback at microsoft.com
-  this is a good alias to use when you have issues with ReportAProblem tool that you can't submit through the web. Thanks!

**Comment by nikolami** [comment]
Thanks for reporting this issue! I added a spinner before the loading to make it more obvious something is still loading. Will release in a future update of Visual Studio. 
![image](https://user-images.githubusercontent.com/18406914/32338219-5c253cd8-bfb1-11e7-9116-40b6826c6131.png)
