### ISSUE TITLE
Make SyntaxNodeExtensions.RemoveNode end of line configurable

### ISSUE THREAD

**Issue by maca88** [dotnet/roslyn#22924]
**Version Used**: 2.4.0

Currently, the EOL that [may be added](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Compilers/CSharp/Portable/Syntax/SyntaxNodeRemover.cs#L108) by [RemoveNode](https://github.com/dotnet/roslyn/blob/1102ba506092bd6edfcfe1abdc990162ff337d47/src/Compilers/Core/Portable/Syntax/SyntaxNodeExtensions.cs#L260) or [RemoveNodes](https://github.com/dotnet/roslyn/blob/1102ba506092bd6edfcfe1abdc990162ff337d47/src/Compilers/Core/Portable/Syntax/SyntaxNodeExtensions.cs#L275) is CRLF and cannot be changed.
By making the EOL configurable, we would be able to preserve the EOL of the original document, as we could do it with [NormalizeWhitespace](https://github.com/dotnet/roslyn/blob/1102ba506092bd6edfcfe1abdc990162ff337d47/src/Compilers/Core/Portable/Syntax/SyntaxNodeExtensions.cs#L295).

**Comment by jcouv** [comment]
Tagging @gafter @DustinCampbell for thoughts on this request.

**Comment by CyrusNajmabadi** [comment]
When does RemoveNode add an EOF?  Why is RemoveNode ever adding anything?

**Comment by maca88** [comment]
> When does RemoveNode add an EOF?

One example that occurred to me is when `KeepUnbalancedDirectives` option is used. In [this unit test](https://github.com/dotnet/roslyn/blob/94ab292d2c79b1675de0d6ff0a7361ecfbf20cfb/src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs#L2327) an EOL is added before `#region Fred`.

**Comment by CyrusNajmabadi** [comment]
Oh.  I misread.  I thought it was EOF, not EOL.  Yes.  EOL should be configurable.  SyntaxRemoveOptions would be a good place to put this info.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/23165
