### ISSUE TITLE
Enum type appears as Class when referenced in another project

### ISSUE THREAD

**Issue by pquiring** [dotnet/roslyn#22931]
**Version Used**: 
2.4.0

**Steps to Reproduce**:

1.  Create Enum in classlib
2.  Reference Enum in another assembly
3.  TypeKind appears as Class, not Enum

**Expected Behavior**:
TypeKind should be Enum in both projects

**Actual Behavior**:
TypeKind is Enum in classlib project, but appears as Class in other project that references the classlib.

Here is classlib project:

```
﻿using System;
namespace bug1
{
    public enum TestEnum { v1, v2, v3 };
    public class Bug1 {
        public void func() {
            TestEnum x = TestEnum.v2;
        }
    }
}

```

When you print out SyntaxNode tree, the 'x' TypeKind is Enum as it should be.

Here is console project that references bug1:

```
using System;
using bug1;
namespace bug2
{
    class Program
    {
        static void Main(string[] args)
        {
            TestEnum y = TestEnum.v1;
        }
    }
}

```

When you print out SyntaxNode tree, the 'y' TypeKind is Class, should be Enum.

**Comment by pquiring** [comment]
Note : a workaround is to use BaseType.Name which is "Enum" in both projects.

**Comment by jcouv** [comment]
@pquiring How do you print out the SyntaxNode tree?

When I use semantic model APIs to `GetTypeInfo` on the "TestEnum" type in the second project, I see the expected `TypeKind`.

Here's what I tested (I also tested with the code from the description):
```C#
        [WorkItem(22931, "https://github.com/dotnet/roslyn/issues/22931")]
        [Fact]
        public void EnumFromMetadata()
        {
            string lib_cs = @"
public enum TestEnum { v1, v2, v3 };
";

            var compLib = CreateStandardCompilation(lib_cs);
            var compRef = compLib.EmitToImageReference();
            //var compRef = compLib.ToMetadataReference();
            string client_cs = @"
using System;
class C
{
    static void M()
    {
        TestEnum y = TestEnum.v1;
    }
}
";
            var compClient = CreateStandardCompilation(client_cs, references: new[] { compRef });

            var tree = compClient.SyntaxTrees[0];
            var model = compClient.GetSemanticModel(tree);
            var declaration = tree.GetRoot().DescendantNodes().OfType<VariableDeclarationSyntax>().Single();
            var type = model.GetTypeInfo(declaration.Type);
            Assert.Equal("TestEnum", type.Type.ToTestDisplayString());
            Assert.Equal(TypeKind.Enum, type.Type.TypeKind); // this is expected and works fine
        }
```

**Comment by pquiring** [comment]
I use this project to print the SyntaxNode trees.

github.com/pquiring/CSPrintTree

I'll attach the print outs from bug1 and bug2.

In bug2 you'll see that the Enum looks like a Class according the the Type.TypeKind.

[bug1.txt](https://github.com/dotnet/roslyn/files/1441446/bug1.txt)
[bug2.txt](https://github.com/dotnet/roslyn/files/1441447/bug2.txt)

**Comment by jcouv** [comment]
Binding of symbols cannot complete when there are errors (the compiler will do the best it can) and I see in bug2.txt that there is `TypeKind=Error` in a few places.
Look at the diagnostics to understand why.

**Comment by pquiring** [comment]
The diagnostics say:
`error CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

But I add a reference to the other project using:
`                compiler = compiler.AddReferences(MetadataReference.CreateFromFile(lib));`
Where lib is the dll from the other project.

Why do I get these error messages?

Thanks.

**Comment by CyrusNajmabadi** [comment]
> But I add a reference to the other project using ... Why do I get these error messages?

It's not sufficient to just have a reference to the other project.  The compiler does not transitively pick up metadata references from that project.  After all, say you had the following setup:

```
Project A
   MetadataReference Foo1.dll

Project B
    References Project A
    MetadataReference Foo2.dll
```

This is legal, and normal.  When compiling B, the compiler only uses the you provided to it directly (i.e. the A dll and Foo2.dll.  

So, you need to tell your other compiler instance that it has a metadata reference to dll that defines System.Enum.

**Comment by pquiring** [comment]
I do add a reference to System.Enum with this code:

```
                String lib = typeof(object).Assembly.Location;
                Console.WriteLine("Adding Reference:" + lib);
                compiler = compiler.AddReferences(MetadataReference.CreateFromFile(lib));

```

Then I add the reference to the other project and STILL get errors.

Why doesn't the compiler see System.Enum from this reference?

**Comment by pquiring** [comment]
I found the fix, after googling it I ended up at bug # 16846

> https://github.com/dotnet/roslyn/issues/16846#issuecomment-276443112

So I added this code:

```
            var libs = ((String)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")).Split(Path.PathSeparator);
            foreach(var lib in libs) {
                Console.WriteLine("Adding Reference:" + lib);
                compiler = compiler.AddReferences(MetadataReference.CreateFromFile(lib));
            }

```

And it works now!  Please close ticket.

Please update the documentation for Roslyn.  Just adding the dll from typeof(object).Assembly.Location is not enough.

**Comment by jcouv** [comment]
Glad things worked out. Thanks
