### ISSUE TITLE
Syntax mismatch for GetOperation

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#22943]
The syntax node passed into `GetOperation` and the returned `Operation.Syntax` mismatch, in at least following cases:

```cs
var x = new /*<bind>*/int[0]/*</bind>*/;
```

```cs
class Bar
{
    public bool Field;
}

class C
{
    public void M()
    {
        var x1 = new Bar();
        x1./*<bind>*/Field/*</bind>*/ = false;
    }
}
```

**Comment by mavasani** [comment]
Tagging @AlekseyTs @jinujoseph

**Comment by AlekseyTs** [comment]
@mavasani Is it still reproducible after the fix for the qualified expressions?

**Comment by mavasani** [comment]
Ah, I didn't notice there was a qualified member access. Let me double check, but likely this is no repro. I will close it out.

**Comment by AlekseyTs** [comment]
> Ah, I didn't notice there was a qualified member access. Let me double check, but likely this is no repro. I will close it out.

The first scenario is not a qualified member access. Make sure to check that one too.

**Comment by mavasani** [comment]
Verified that neither of these cases repro.

For the first case, GetOperation on `int[0]` returns null as it is an ArrayTypeSyntax. If I query GetOperation on `new int[0]`, it returns an `IArrayCreationOperation` with same syntax as passed in.

Second case was explicitly handled in the PR that removed GetStandaloneNode.
