### ISSUE TITLE
VB Model.GetTypeInfo returns wrong result for Test Projects and infinite refactorings

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#22942]
**Version Used**: 
2.4
**Steps to Reproduce**:

1. Set up to call Model.GetTypeInfo(expression, cancellationToken) using project APISampleUnitTests, file SymbolsAndSemantics.vb (this requires a lot of code for me to put here)
2. Set expression = New TestCodeContainer(code) which is fount on line 23
3. Execute  Dim typeInfo As TypeInfo = Model.GetTypeInfo(expression, cancellationToken)

**Expected Behavior**:
TypeInfo.Type should be TestCodeContainer
**Actual Behavior**:
APISampleUnitTestsVB.TestCodeContainer

4. Change line 23 in the source to what is recommended by the Type returned by GetType
```
        Dim testCode As APISampleUnitTestsVB.TestCodeContainer = New TestCodeContainer(code)
```
**Expected Behavior**:
no errors
**Actual Behavior**:
BC3002 APISampleUnitTestsVB.TestCodeContainer is not defined and you are offered a refactoring to
```
        Dim testCode As APISampleUnitTestsVB.APISampleUnitTestsVB.TestCodeContainer = New TestCodeContainer(code)
```
Same error with another opportunity to refactor and it continues forever with the line getting longer each time you refactor.

I have only seen this with Test Projects. If I move same to files to regular project I can't reproduce.

**Comment by jaredpar** [comment]
Closing as the samples no longer live in this repository. They have moved to https://github.com/dotnet/roslyn-sdk
