### ISSUE TITLE
Visual Studio crashing when open "App Manifest Designer"

### ISSUE THREAD

**Issue by bidolah** [dotnet/roslyn#22951]
**Version Used**: 
Visual Studio Professional 2015 
Version 14.0.25431.0.1 Update 3
**Steps to Reproduce**:

1. Create new UWP Blank App
2. Go to solution folder and find this file "*.Shared.projitems" in shared project
3. Edit file. Add some items from parent folder ("..\\..\\"). For Example:
```
  <ItemGroup>
        <Content Include="$(MSBuildThisFileDirectory)..\..\Image\1.png"></Content>
  </ItemGroup>
```
4. Go to "*.Windows" project in Visual Studio
5. Open Package.appxmanifest in "App Manifest Designer"

**Actual Behavior**:
Visual Studio crashes and reloaded!

**Example**:
Also you can look bug app on github:
Repository: https://github.com/bidolah/UWPBug
Issue: https://github.com/bidolah/UWPBug/issues/1

**Comment by jcouv** [comment]
@jinujoseph @Pilchie Could you help route? Thanks

**Comment by jinujoseph** [comment]
tracked [here](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/557954)
