### ISSUE TITLE
Work needed to properly split EditorFeatures / Wpf

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#22959]
This PR lists some changes that we needed to do to move MonoDevelop to Roslyn 2.6.0:
https://github.com/mono/monodevelop/pull/3228

 - [x] Need to export InlineRenameService
 - [ ] Need to export PreviewFactoryService
 - [ ] Need to export RoslynWaitIndicator
 - [ ] Need to export SuggestedActionCategoryRegistryService
 - [ ] Need to export IPeekResultFactory
 - [ ] Need to export ISignatureHelpBroker
 - [ ] remove the second generic parameter from IIntelliSensePresenter: http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/IIntellisensePresenterSession.cs

 - [ ] Remove MS.VS.Text.UI.Wpf.dll reference from MS.CA.VisualBasic.EditorFeatures.dll

 - [ ] Investigate removing reference to MS.VS.RemoteControl.dll 14.0.0.0 from EditorFeatures

**Comment by KirillOsenkov** [comment]
cc @jasonmalinowski Remove MS.VS.Text.UI.Wpf.dll reference from MS.CA.VisualBasic.EditorFeatures.dll

**Comment by KirillOsenkov** [comment]
Basically a good exercise would be removing a reference to MS.VS.Language.StandardClassification.dll and see what breaks. Ideally move things needing Peek, SignatureHelp, etc. to EditorFeatures.Wpf.

**Comment by KirillOsenkov** [comment]
Also there are 4 usages of ImageMoniker in EditorFeatures:
```
  Microsoft.CodeAnalysis.EditorFeatures, Version=2.6.0.0
    Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.IconMoniker:ImageMoniker
    Microsoft.CodeAnalysis.Editor.Shared.Extensions.GlyphExtensions.GetImageMoniker(this Glyph glyph):ImageMoniker
    Microsoft.CodeAnalysis.Editor.Tags.DefaultImageMonikerService.TryGetImageMoniker(ImmutableArray<string> tags, out ImageMoniker imageMoniker):bool
    Microsoft.CodeAnalysis.Editor.Tags.IImageMonikerService.TryGetImageMoniker(ImmutableArray<string> tags, out ImageMoniker imageMoniker):bool
    Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.IconMoniker:ImageMoniker
    Microsoft.CodeAnalysis.Editor.Shared.Extensions.GlyphExtensions.GetImageMoniker(this Glyph glyph):ImageMoniker
    Microsoft.CodeAnalysis.Editor.Tags.DefaultImageMonikerService.TryGetImageMoniker(ImmutableArray<string> tags, out ImageMoniker imageMoniker):bool
    Microsoft.CodeAnalysis.Editor.Tags.IImageMonikerService.TryGetImageMoniker(ImmutableArray<string> tags, out ImageMoniker imageMoniker):bool
```

Would be nice to remove those if possible, so we don't have to bring in MS.VS.Imaging and MS.VS.ImageCatalog.

**Comment by KirillOsenkov** [comment]
Looks like we'll also need Microsoft.VisualStudio.CodingConventions.dll

**Comment by KirillOsenkov** [comment]
RemoteControl is a problem for us:
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/SymbolSearch/SymbolSearchUpdateEngine.RemoteControlService.cs,98e79e054c6ed0c9

**Comment by jasonmalinowski** [comment]
OK I've migrated what I think is still the open items to https://github.com/dotnet/roslyn/projects/32. Let's use the project from here on out, since having a mondo issue like this is impossible to carry on conversations about individual items, and means I can't tag them in PRs to keep them closed.
