### ISSUE TITLE
Error CS8338 on (in this T) where T : struct

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#22950]
**Version Used**: 

15.5.0 Preview 2.0

**Steps to Reproduce**:

```cs
static class Extensions
{
    // Error CS8338  The first parameter of an 'in' extension method 'In' must be a value type.
    public static void In<T>(in this T value) where T : struct { }
    // OK
    public static void Ref<T>(ref this T value) where T : struct { }
}

static class Static
{
    // OK
    public static void In<T>(in T value) where T : struct { }
    // OK
    public static void Ref<T>(ref T value) where T : struct { }
}
```

**Expected Behavior**:

[The spec](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/readonly-ref.md) says 

> the this parameter by reference, as long as the type is known to be a struct type (I.E. struct or **a generic type with struct constraint**).

so `(in this T value) where T : struct` should be allowed.

**Actual Behavior**:

Error CS8338

**Comment by jcouv** [comment]
Tagging @VSadov @OmarTawfik

**Comment by VSadov** [comment]
The error is correct. The document is wrong. It is not really a spec it was the initial proposal of the feature. A lot changed since then.

I will try fixing up the document to reflect the final state of readonly references.
