### ISSUE TITLE
Refactoring Attribute: AttributeAttribute

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#22955]
**Version Used**: 
15.5.0 Preview #2.0
**Steps to Reproduce**:
Use this code:
````
public class SomethingAttribute : Attribute {
}
````
Position your cursor on "SomethingAttribute" and press "Control+R R" to rename it.  You'll notice that it only selects "the word "Something" for the renaming.

Give it a name of "CustomAttribute".
The class is incorrectly renamed to "CustomAttributeAttribute"

![rename attribute](https://user-images.githubusercontent.com/13609558/32291970-97a146f8-bf0c-11e7-8c35-0dd83ce85ad4.gif)

**Comment by sputier** [comment]
It seems this one would be a good start for a first contrib on Roslyn. I'll try to handle it !

**Comment by sputier** [comment]
In [InlineRenameSession.cs, line 378](https://github.com/dotnet/roslyn/blob/878ffad23b8b06cb229c9ab31eada7634a473508/src/EditorFeatures/Core/Implementation/InlineRename/InlineRenameSession.cs#L378), there is a use to `IInlineRenameInfo.GetFinalSymbolName()` whose implementation ([AbstractEditorInlineRenameService.SymbolRenameInfo](https://github.com/dotnet/roslyn/blob/878ffad23b8b06cb229c9ab31eada7634a473508/src/EditorFeatures/Core/Implementation/InlineRename/AbstractEditorInlineRenameService.SymbolRenameInfo.cs#L199-L207)) adds the 'Attribute' suffix to the replacement text when renaming an attribute.

I think wiping out this call would fix the issue. I couldn't find any implications for this change, so I created the PR #23032 to apply this. Any remarks are welcome !

**Comment by jinujoseph** [comment]
also reported at [link](https://developercommunity.visualstudio.com/content/problem/149777/renaming-c-attributes-adds-an-additional-attribute.html)

**Comment by IanKemp** [comment]
No review? :( This is a pretty annoying bug!

**Comment by IanKemp** [comment]
Seems like the affected code is now at https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core.Wpf/InlineRename/InlineRenameSession.cs#L397 - I'd be happy to pick this up, but am currently blocked by #27518.

**Comment by jinujoseph** [comment]
@JoeRobich this is already resolved right ?

**Comment by JoeRobich** [comment]
@jinujoseph Yes, This was fixed in #29153

**Comment by jinujoseph** [comment]
thanks @JoeRobich , closing this
