### ISSUE TITLE
Espression not supported when mousing over LINQ/SQLite command at runtime

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#22954]
I'm trying to query my SQLite table by using a LINQ command to search for a string. 

public Task&lt;AppMyItem&gt; GetItemAsync(string itemDesc)
{
    Expression&lt;Func&lt;AppMyItem, bool&gt;&gt; expr = i =&gt; i.ItemDesc == itemDesc;
    return database.Table&lt;AppMyItem&gt;().Where(expr).FirstOrDefaultAsync();
}

This is what I tried and it would compile, but at runtime if I put my mouse over the =&gt; it would give a message saying &quot;Expression not supported&quot;. I'm super confused and I've tried quite a few things. SQLite-net is all up to date, I don't know what else it could be. I'm able to use ToListAsync() to get a list of the data but if I do anything involving the .Where() statement I get &quot;Expression not supported&quot;.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/93222/espression-not-supported-when-mousing-over-linqsql.html
VSTS ticketId: 479496_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
No clue what this is.  Doesn't seem like roslyn at all.  Maybe another extension?
