### ISSUE TITLE
Naming for IMemberInitializerOperation

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22979]
See https://github.com/dotnet/roslyn/issues/22967#issuecomment-341465839 and https://github.com/dotnet/roslyn/issues/22967#issuecomment-341479997 about the confusion.

**Comment by jinujoseph** [comment]
no change to the API name , improve the doc comment

**Comment by mavasani** [comment]
Already done as part of #22983 - closing this issue.
