### ISSUE TITLE
Change Visual studio build path for Ram disk

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#22978]
Currently I have Visual Studio 17 V 15.4.2
Is it possible to set different build path for projects? for example instead of 

`C:\Users\[UserName]\source\repos\[MyProject]\[bin|obj]`

move it on

`M:\Users\[UserName]\source\repos\[MyProject]\[bin|obj]`

note that project it self is inside `C` but temporary files are moved somewhere else. I have drive `M` which is a 16GB ram disk.

**Benefits of using RAM disk**

 - faster build times (no real IO)
 - SSD doesn't wear out with repetitive rebuilds.
 - projects are inherently cleaned up (which brings following benefits)
 - share faster, your projects are not filled with unnecessary files so that you can easily share folders with others. (code size is usually less than 1MB but build objects can go beyond 1GB)
 - fast backups, for same reason your project folders always remain cleaned up and you can backup project much faster. (especially when you have many projects, eg. you would only backup 100MB istead of 10GB)
 - less chance of creating locked files. (which cause build desync, errors etc) in that case formatting ramdisk is easier than mucking with VS settings or restarting it.

**Drawbacks:**
 - there maybe some inconsistency using environment variables related to project location.
 - project build targets may not work if they are only bound to project path. (there are work arounds, I think this has room for discussion)
 - you need much more RAM, in my case I have 32GB which I can spare 16GB for it.
 - if you reset VS or computer you loose compiled objects and you have to rebuild (once)

but in most scenarios benefits of using RAM disk overweight its drawbacks. Note that VS team doesn't have to do anything about RAM disk. all they have to do is to make it possible change path of build into parent drive or folder.

This was originally posted [here
](https://stackoverflow.com/questions/47071194/change-visual-studio-build-bath-for-ram-disk), if you have answer to that I appreciate to get your answer, else this proposal remains as feature request.

thanks in advance, best regards.

**Comment by jcouv** [comment]
You can control where the build process output the intermediate and final files. A quick search yielded [some of the MSBuild properties](https://stackoverflow.com/a/9724626/172315) you can set to that effect.
It's not obvious that using a RAM disk will provide any observable benefit, especially compared to an SSD. Do let us know if you get good results.

**Comment by AlexeiScherbakov** [comment]
I found this issue when I tried to solve similar problem.

I make solution for redirecting obj files of projects to ramdrive.

You need to define environment variable with your ramdrive location (BUILD_RAMDRIVE) and Directory.Build.props with this content.
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <BuildRamdrive>$([System.Environment]::GetEnvironmentVariable("BUILD_RAMDRIVE",System.EnvironmentVariableTarget.Machine))</BuildRamdrive>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(BuildRamdrive)' != '' AND '$(MSBuildProjectFile)' != ''">
        <BaseIntermediateOutputPath>$(BuildRamdrive)\Projects\$(SolutionName)\$(MSBuildProjectFile)\obj\</BaseIntermediateOutputPath>
        <IntermediateOutputPath>$(BuildRamdrive)\Projects\$(SolutionName)\$(MSBuildProjectFile)\obj\$(Configuration)\</IntermediateOutputPath>
        <MSBuildProjectExtensionsPath>$(BuildRamdrive)\Projects\$(SolutionName)\$(MSBuildProjectFile)\obj\</MSBuildProjectExtensionsPath>
    </PropertyGroup>
</Project>
```

I spend few hours to identify right MSBuild variables and make final working solution, so I post it here - may be somebody will find it by using Google :-D

P.S. Also for clearing obj dir on ramdrive you can use Directory.Build.targets file with content
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Target Name="CleanupObj" AfterTargets="Clean">
		<RemoveDir Directories="$(IntermediateOutputPath)" />
	</Target>
</Project>
```

You can extend this solution also to bin folder
