### ISSUE TITLE
Possible refactoring: turn task.Result into await

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#22982]
Sometimes, especially when prototyping, I use an asynchronous API like `HttpClient` from synchronous code, which means I end up with calls to `.Result` (or `.Wait()`) everywhere. If I later decide to make the code asynchronous, I have to change all those `.Result`s into `await`s. It's not a complicated process, but it is tedious. Also, I might miss one `.Result`, which would mean the resulting code is not fully asynchronous. Because of that, I think it would be nice if the IDE could help me with this.

Would it make sense to have a refactoring/code fix that changes calls to `Task<T>.Result` and `Task.Wait()` into `await`? Would Roslyn be the right place for it?

Note that changing from `.Result` to `await` changes exception throwing behavior (no more `AggregateException`), but I think that's acceptable for refactoring.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
