### ISSUE TITLE
Use expression-bodied member doesn't work for local functions

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#22981]
If I have a single-line local function, we don't offer to make it into an expression-bodied member. We do offer this for single-line methods, though.

**Comment by CyrusNajmabadi** [comment]
We likely need to add an option for that.  My guess is these features were added around the same time, so we didn't end up absorbing local functions into the expression-body work. Tagging @agocke .  

Note: should we do the same for lambdas?

**Comment by Neme12** [comment]
Definitely should be done for local functions.

I'd like this for lambdas too. Should they have the same terminology though? They've never been referred to as "expression-bodied" lambdas, and also it's really a different syntactic construct (the arrow is part of the lambda, regardless of where it's expression/block).

**Comment by rik-smeets** [comment]
This was resolved in #31648. This issue can be closed. Can you do that @jinujoseph? Thanks.

**Comment by jinujoseph** [comment]
Sure, thanks @rik-smeets
