### ISSUE TITLE
Update to new version of SQLite

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#22996]
The version to switch to 3.19.3 https://www.nuget.org/packages/SQLitePCLRaw.bundle_green/1.1.8

**Comment by jinujoseph** [comment]
Synced with @AArnott , plan is both team will continue to use 3.16.1 version , till we have a  common shared location (PrivateAssemblies perhaps ) that we can depend on

**Comment by CyrusNajmabadi** [comment]
@AArnott Is there some common sqlite that Roslyn could refer to to use? It would be nice anyways to avoid having to load multiple versions of this.  Thanks!

**Comment by AArnott** [comment]
It's not just a convenience. sqlite has a native module so it can only be loaded *once* in a process. So it's imperative that if you run in-proc you share the same version as the rest of us.
I'm not tracking the version actively though, or whether there's a setup package you need to depend on. @tinaschrepfer should be able to help you I think.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski is there anything we need to do here?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi No idea why this bug was created, but looks like we've upgraded many times since...
