### ISSUE TITLE
Application of formatting rules changed in 1.0.0.0-beta2

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#23]
One of the StyleCop analyzers we implemented (SA1408) adds parentheses around certain expressions in code. The [code fix provider implementation](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/9d5ebc45ac255c38db904e23e0066fc189a282f1/StyleCop.Analyzers/StyleCop.Analyzers/MaintainabilityRules/SA1407SA1408CodeFixProvider.cs#L61-L73) does not use `Formatter.Annotation`, and we have a unit test which [verifies the code fix does not alter existing formatting](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/9d5ebc45ac255c38db904e23e0066fc189a282f1/StyleCop.Analyzers/StyleCop.Analyzers.Test/MaintainabilityRules/SA1408UnitTests.cs#L211-L212) aside from adding `(` and `)` characters.

The unit test in question was successful in the Beta 1 code. With no change aside from updating to Beta 2, the test now fails.

Here is the affected expression as produced by Beta 1:

```csharp
bool z = z ? (true&&true)||false :false;
```

Here is the affected expression as produced by Beta 2:

```csharp
bool z = z ? (true && true) || false :false;
```

The two expressions differ by a total of 4 space characters.

### Questions:

* :question: Is there a way to cause Beta 2 to behave like Beta 1? Our diagnostics and code fixes relate specifically to code formatting so they will not work if the implementation changes unrelated formatting.
* :question: Was the behavior change in Beta 2 intended, and/or will it be reverted in the next release?

**Comment by mattwar** [comment]
A CodeAction now treats any occurrence of elastic trivia the same as if a formatter annotation was attached. Any time you create a token without explicitly specifying leading and trailing trivia, the token gets special elastic marker trivia that acts a hint to the formatter. Normally, this is a good thing, but maybe not in your case.

You have two possible ways to work around this behavior.  

1) always specify the trivia explicitly, even when there is none (use default(SyntaxTriviaList)) 
2) make a sub type of CodeAction that has different logic for post processing documents.

**Comment by srivatsn** [comment]
We've made a change to the codefix engine such that if there are nodes with elastic trivia we automatically add the formatter annotation. This is because most often people are generating new nodes in codefixes through `SyntaxFactory` or `SyntaxGenerator` which have elastic trivia and most often they would want those nodes formatted.

In your cases I assume you are generating the tokens for the parentheses and so I would expect formatter annotation around the parentheses but (without looking at the code) i wouldn't expect the code inside the parentheses to get formatted as well. @mattwar, are we putting formatter annotation on the entire expression here?

You can remove the elastic trivia from your generated nodes and then you shouldn't see the formatting behavior.

**Comment by sharwell** [comment]
I believe the previous behavior had two particular advantages related to code review and unit testing:

1. It was easy to verify during code review that a code action was not reformatting code.
2. For code actions which *do* reformat code, it was easy to see exactly which sections of the tree were subject to reformatting.

Do you have a recommendation for developers to improve the ability to recognize these behaviors during code review (i.e. what should we now be looking for two check the two items I described above even before running the code)?

**Comment by sharwell** [comment]
I implemented a `WithoutElasticTrivia` extension method in DotNetAnalyzers/StyleCopAnalyzers@10e217b to recursively remove `SyntaxAnnotation.ElasticAnnotation`, which seems to do the job from both an implementation and code review standpoint. I'm considering adding a related method `WithoutFormatting` which would involve a recursive removal of both `Formatter.Annotation` and `SyntaxAnnotation.ElasticAnnotation`.

**Comment by heejaechang** [comment]
in unit test, if a specific test doesn't care about formatting, how about comparing sequence of tokens and trivia except whitespace trivia?

**Comment by sharwell** [comment]
I have now implemented the `WithoutFormatting` extension method in DotNetAnalyzers/StyleCopAnalyzers@8973f3afa7958fb71ca7e7c94f29cde0d1278ae8, which addresses the concern of code review and provides a general solution to the issues I mentioned above.
