### ISSUE TITLE
Refactoring icon should be applied per-diagnostic

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#23005]
See #22945

It appears the refactoring icon is being incorrectly triggered currently.

**Expected Behavior**:

* If one or more diagnostics is reported on the line with severity info (suggestion) or higher, show as a fix
* If diagnostics appear on the line, but all have severity hidden (none, silent), show as a refactoring
* If no diagnostics appear on the line but refactoring operations are available, show as a refactoring

**Actual Behavior**:

In some cases, the second item is not followed correctly. This is likely due to one of the following situations (investigation required to be sure):

1. All diagnostics are reported as fixes (i.e. only refactoring providers are considered refactorings)
1. The default severity of the analyzer is used instead of the actual severity applied to individual diagnostics. When rule set files are not used, these values can vary per-diagnostic.

**Comment by gundermanc** [comment]
I have filed the following bugs on DEVDIV tracking similar tweaks + suggestions for icons + ordering:

- https://devdiv.visualstudio.com/DevDiv/_workitems?id=561038
- https://devdiv.visualstudio.com/DevDiv/_workitems?id=561047 
- https://devdiv.visualstudio.com/DevDiv/_workitems?id=561073 

cc: @kuhlenh

**Comment by jmarolf** [comment]
@gundermanc is there a reason these bugs can't be filed on github? We would prefer track work in the open if possible.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and movement.
