### ISSUE TITLE
Fix SemanticModel.GetOperation to return distinct Ioperation nodes for distinct syntax nodes

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#23001]
found by @AlekseyTs 

I looked at some failures flagged by the verifier added by PR https://github.com/dotnet/roslyn/pull/22917.
It looks like many of them are caused by the fact that our implementation adjusts the passed-in syntax node by using SyntaxFactory.GetStandaloneNode method:
        /// <summary>
        /// Gets the containing expression that is actually a language expression and not just typed
        /// as an ExpressionSyntax for convenience. For example, NameSyntax nodes on the right side
        /// of qualified names and member access expressions are not language expressions, yet the
        /// containing qualified names or member access expressions are indeed expressions.
        /// Similarly, if the input node is a cref part that is not independently meaningful, then
        /// the result will be the full cref.
        /// </summary>
        internal static CSharpSyntaxNode GetStandaloneNode(CSharpSyntaxNode node)

For example, for a qualified name “a.b”, if used syntax node corresponds just to “b” part, we expand it to “a.b” before trying to locate IOperation node for it. 
That means that passing “a.b” and passing “b” returns the same IOperation node, which is associated with “a.b”. This potentially can confuse consumers that expect to get distinct IOperation nodes for distinct syntax nodes. Should we stop doing this expansion? Or should we treat cases like this as an exception to the rule?

**Comment by AlekseyTs** [comment]
I think we don't need to fix SyntaxFactory.GetStandaloneNode, we should just stop calling it.
