### ISSUE TITLE
Add Go To Implementation option for Deconstruct calls

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#23012]
Currently (without use of resharper) there is no convenient way to know which deconstruct is being resolved when you for example write this.

    var (x, y) = GetResult();

it would be nice if there was a easy an convenient way to navigate to deconstruct overload that is being used.

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/issues/16529

**Comment by jcouv** [comment]
Also relates to https://github.com/dotnet/roslyn/pull/22934 (PR currently being reviewed), which adds a compiler API exposing information about deconstructions. That can be used by the IDE to find out what `Deconstruct` method is involved at a certain location.

**Comment by jcouv** [comment]
I'll close this issue in favor of #16529. I think GoToDefinition makes more sense, and, regardless, we only need one issue for IDE to track this navigation request. Thanks
