### ISSUE TITLE
GetDeclarationKind on variable declarations never returns DeclarationKind.Variable

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#23017]
https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L2135 checks if the variable declaration's parent is `null`, meaning the declaration must be the root node, before it returns `DeclarationKind.Variable`. I don't think any well-formed C# program can have a variable declaration as the root node, so it seems like a mistake.

**Comment by CyrusNajmabadi** [comment]
I think that check is only looking at new code created.  I think for existing code, it expects to be called on things like the field declaration, or local declaration statement declaration.
