### ISSUE TITLE
Microsoft.CodeAnalysis.Workspaces.Desktop.dll is missing from the netstandard1.3 version of Microsoft.CodeAnalysis.Workspaces.Common NuGet package

### ISSUE THREAD

**Issue by thauk-copperleaf** [dotnet/roslyn#23011]
But it is present in the `net46` version of that package.

Is that an accident? If yes, how can it be resolved?

Is that on purpose? If so, then why isn't that assembly included?

Any help would be most appreciated; I am having great difficulties creating a C# Library project (either targetting .NET Standard, or .NET Framework 4.6.2/4.7.1) that uses Roslyn and a corresponding C# .NET Framework-based Unit Test project, and getting them actually building and running. I am using VS 2017 15.4.2.

**Comment by Pilchie** [comment]
It is on pupose because that assembly relies on APIs that aren't present in .NET Standard.

**Comment by thauk-copperleaf** [comment]
That just means a .NET Core library won't be able to load the DLL; since I'm targeting .NET Standard then I can use the version from `net46`. At least I've copied over the DLL directly into my project, and that seems to work.

**Comment by thauk-copperleaf** [comment]
@Pilchie Is there any task currently scheduled to remove `Microsoft.CodeAnalysis.Workspaces.Desktop`'s dependencies on .NET Framework APIs?

If not, what would you estimate the effort required as? Would this be something plausible for someone external to MS to do, and submit as a PR?

**Comment by sharwell** [comment]
@thauk-copperleaf Currently @DustinCampbell is investigating the possibility of moving one or more APIs from the desktop-only down to .NET Standard, including but not limited to cases enabled by new APIs in .NET Standard 2.0. I know it is a highly-involved task (especially since we have compatibility concerns to consider), so he would be the one to ask about it.

**Comment by DustinCampbell** [comment]
@thauk-copperleaf : Which APIs from Microsoft.CodeAnalysis.Workspaces.Desktop are you trying to use?

**Comment by thauk-copperleaf** [comment]
@DustinCampbell Pretty much just `var workspace = MSBuildWorkspace.Create();`

**Comment by DustinCampbell** [comment]
OK. Yes, this is being worked on in https://github.com/dotnet/roslyn/pull/21670. Ultimately, I expect that we'll move MSBuildWorkspace into a separate package.

**Comment by thauk-copperleaf** [comment]
@DustinCampbell That's good news! Is there a planned release for this change?

**Comment by DustinCampbell** [comment]
Not yet, no.

**Comment by aoancea** [comment]
I'm looking into that exact issue now :)

**Comment by jcouv** [comment]
@DustinCampbell Sounds like this issue is being worked on. Who should it be assigned to?

**Comment by sharwell** [comment]
@jcouv The issue as stated is by-design. The relevant side issue of `MSBuildWorkspace` is linked to above.

**Comment by TheKK** [comment]
So I encounter this problem as well :(

Currently I'm build a visual studio extension command with code like `MSBuildWorkspace.Create()` and when the command is invoke it cry about Microsoft.CodeAnalysis.Workspaces.Desktop.dll is missing.

I know the official fix in on going, just wondering is there any "quick fix" I can use so my project could go on :)

ps. Or, is there other way to convert a .sln file to `Microsoft.CodeAnalysis.Solution`?

**Comment by DustinCampbell** [comment]
@TheKK: If you're building a Visual Studio extension, why are you using `MSBuildWorkspace`?

**Comment by TheKK** [comment]
Oh, I notice that I can use `componentModel.GetService<VisualStudioWorkspace>();` to get workspace from opening solution :)

**Comment by DustinCampbell** [comment]
Correct.That's going to  be much better than loading the same solution *again* in Visual Studio with `MSBuildWorkspace`. I guess `MSBuildWorkspace` would be useful if you were trying to analyze a different solution than the one that is loaded in VS.
