### ISSUE TITLE
Add option to change relative path of project builds.

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#23013]
Please add this option in `Options/Projects and Solutions/Locations`

 - Project Builds Relative Path

default value should be equal to `Projects location` option.

**Notes to consider:**

user should not be able to specify exact build path of project. because it will cause collision on different projects. so if this path is specified for builds:

`C:\Project Builds`

final path of each project will automatically resolve to

`C:\Project Builds\[Project Name]\[bin|obj|etc]`

---

I think my previous request #22978 was quite long so I decided to make it simple here. the compelling reason is there so please check it out. thank you.

**Comment by jcouv** [comment]
You can control your build process by editing the project files using the various properties offered by msbuild.

**Comment by dpoeschl** [comment]
Let us know if @jcouv's solution is insufficient for your needs. If so, probably head over to https://github.com/dotnet/project-system/ to ask them for assistance.
