### ISSUE TITLE
Add support for /features:deterministic for msbuild

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#2303]
Add support to enable `/features:deterministic` to be passed to the compiler through msbuild.

(see #372 for some context)

And while in the area, also add support for the flags `/checksumalgorithm` and `/pathmap` (#949), even though the latter isn't implemented in the compilers yet.

**Comment by gafter** [comment]
@agocke Are you interested in working on this?

/cc @jaredpar

**Comment by jaredpar** [comment]
Fixed via 55bfdd781fcac523f5e4c648ab4ecc3bfebd2dbf
