### ISSUE TITLE
[Design Question] Should DiagnosticData and Diagnostic be round trip-able?

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#2304]
currently it is not. when a diagnostic %1 is converted to diagnostic data and go back to diagnostic %2.

%1 and %2 are two different diagnostics that have slightly different values. (anything related to descriptor)

two were round trip-able before we introduced descriptor directly in diagnostic. with descriptor and diagnostic coupled tightly, two can't be round trip-able anymore since currently we don't have a way to track descriptor.

now, question is whether we want to maintain the round tripping or not.

the thing we would lose by this is once diagnostic converted to diagnostic data, it will lose localizability.

**Comment by srivatsn** [comment]
Let's talk about this in a design meeting.

**Comment by heejaechang** [comment]
re opened since we see some issues that require this for proper fix.

**Comment by heejaechang** [comment]
but removed milestone so that it is not tied to update 1.

**Comment by heejaechang** [comment]
I think it is decided no need to.
