### ISSUE TITLE
UseNullPropagation codefix doesn't recognize `x is null ? null : x.y` pattern

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#23043]
Also, `ReferenceEquals(foo, null) ? null : foo.y`

```C#
        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseNullPropagation)]
        public async Task TestWithNullableTypeAndIsNull()
        {
            await TestInRegularAndScriptAsync(
@"
class C
{
    public int? f;
    void M(C c)
    {
        int? x = [||]c is null ? null : c.f;
    }
}",
@"
class C
{
    public int? f;
    void M(C c)
    {
        int? x = c?.f;
    }
}");
        }
```

**Comment by CyrusNajmabadi** [comment]
I agree with @jcouv that recognizing this pattern isn't really important.  Given that "is null" was added after "?.", it would be unlikely that someone would write this pattern instead of just using ?. directly.

That said, it *would* be nice to detect ```ReferenceEquals(foo, null) ? null : foo...```.  But really it's a very minor improvement.

**Comment by sharwell** [comment]
:memo: I'm planning to reserve this and the `ReferenceEquals` version for a first-time contributor. Details tomorrow.

**Comment by CyrusNajmabadi** [comment]
Agreed.  They would be great 'up for grabs' fixes.

**Comment by sharwell** [comment]
This issue is reserved for a first-time (and non-Microsoft) contributor for the next 3 days. In particular, @MhdTlb has first call.

Helpful starting points:

* Pull request #23014 implemented a very similar feature
* A complete (or near-complete) unit test for C# is provided in the original bug report above
* Here is our getting started document: https://github.com/dotnet/roslyn/wiki/Contributing-Code

If you have any questions, let me know!

**Comment by sharwell** [comment]
Since I haven't heard back from @MhdTlb, I'm going to open this up to other first-time contributors (still reserved for first-time/non-Microsoft).

**Comment by sharwell** [comment]
Tweeted about it: https://twitter.com/samharwell/status/930093456030085127

**Comment by MhdTlb** [comment]
@sharwell  I'm having hard time to build the project with VS2017 on Windows 10 machine.

**Comment by sharwell** [comment]
@MhdTlb Can you be more specific (steps taken, error message seen)?

/cc @dotnet/roslyn-infrastructure

**Comment by schovanec** [comment]
It is possible that @MhdTlb is trying to build the solution in the released version of VS2017? I had issues with that myself as the SDK version that ships with it seems to be too old. I installed the preview version and everything builds fine in that.

I'm looking for somewhere to get started as well so if @MhdTlb can't get it building I can take a stab at this.

**Comment by schovanec** [comment]
I hadn't heard anything so I wasn't sure if I should start on this or not, but I believe I got it working over the weekend. I will put in a pull request.

**Comment by sharwell** [comment]
@schovanec I missed your previous reply from a couple weeks ago. 😦 I'm glad you were able to make progress on this and I'll take a look! 😄
