### ISSUE TITLE
[Compiler Bug?] "Shared ReadOnly Property" in a strucutre type caused Reflection operation failed.

### ISSUE THREAD

**Issue by xieguigang** [dotnet/roslyn#23050]
**Version Used**: 
Microsoft Visual Studio Community 2017 
Version 15.4.2
VisualStudio.15.Release/15.4.2+27004.2006
Microsoft .NET Framework
Version 4.7.03013

Installed Edition: Community

Visual Basic 2017   00369-60000-00001-AA025
Microsoft Visual Basic 2017

I found a bug of Reflection operation on the structure type in VisualBasic, when the structure type have a **shared readonly property**, then this property will cause a ``ReflectionTypeLoadException`` in the Reflection operation example like ``Assembly.GetTypes``.

For example, When I try to get all types from a dll file, then this [**ReadOnly property in strucutre**](https://github.com/xieguigang/sciBASIC/blame/9176a90633427645a8e8fa8ec6e0dce65cbf97d4/Microsoft.VisualBasic.Architecture.Framework/ApplicationServices/Terminal/ProgressBar/ProgressBar.vb#L91) will cause a problem. When the program running at the reflection function call, example like [**Assembly.GetTypes**](https://github.com/xieguigang/sciBASIC/blame/3e1c8061b317cd2ceeaee967fabb455a7ab91a89/Microsoft.VisualBasic.Architecture.Framework/CommandLine/Reflection/CLIToken.vb#L91), the exception ``ReflectionTypeLoadException`` occurred. When I removes this property from the test, then this exception gone away.

Such **shared readonly property** will cause a ``System.Reflection.ReflectionTypeLoadException`` exception. I'm not sure this is a bug that caused by the mechanism of VisualBasic compiler for dealing with such shared readonly property in a structure type or not?

**Steps to Reproduce**:

1. Open the solution file [**core.sln**](https://github.com/xieguigang/sciBASIC/blob/master/Microsoft.VisualBasic.Architecture.Framework/core.sln), 
2. and set ``core.Test`` project as startup project, 
3. and then run the [``reflectionTest``](https://github.com/xieguigang/sciBASIC/blame/9176a90633427645a8e8fa8ec6e0dce65cbf97d4/Microsoft.VisualBasic.Architecture.Framework/core.Test/reflectionTest.vb#L16) module.

**Expected Behavior**:

``Assembly.GetTypes`` work and the ``ColorTheme`` can be loaded correctly without ``ReflectionTypeLoadException``.

**Actual Behavior**:

``ReflectionTypeLoadException`` occurred.

**Comment by jaredpar** [comment]
This didn't reproduce for me locally and the referenced repro project does not exist. Closing for now.
