### ISSUE TITLE
Private Protected for VB

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#23062]
Roslyn, in master, has support for the protection modifier combination `Private Protected` in VB. However, according to the design notes, it was intended that the modifier be named `ProtectedAndFriend`. See https://github.com/dotnet/vblang/blob/master/meetings/2014/LDM-2014-03-12.md

One way to correct this to align with the design notes would be to
1. Add support for `ProtectedAndFriend` and `ProtectedOrFriend` modifiers (as keywords?)
2. Modify the pretty-lister to reformat `Private Protected` as `ProtectedAndFriend`
3. Make `Private Protected` an error in binding.

We could stop at any step along that path.

**Comment by AdamSpeight2008** [comment]
What does the VB language specification say? regarding `ProtectedAndFriend`

**Comment by gafter** [comment]
@AdamSpeight2008 The language specification for existing versions of the VB language don't say anything about those, as those were never previously part of the language. You could have looked that up rather than asking. We generally don't "leave as is" language features in the language that appeared by accident.

**Comment by AdamSpeight2008** [comment]
@gafter I did look it up, point was if it isn't in the specification yet. The LDM can decide to just update the spefication, as the feature has in at least 2 release versions of the language (VB14/15). So changing it now would be breaking source code backwards compatibility, between the updated version and those version of VB.

**Comment by gafter** [comment]
@AdamSpeight2008 No, it hasn't been in 2 released versions of the language.

**Comment by jcouv** [comment]
This should probably be assigned to Neal.
Do we have a plan?

**Comment by gafter** [comment]
@jcouv It is up to @AnthonyDGreen and @jaredpar, who are aware.

**Comment by gafter** [comment]
https://github.com/dotnet/vblang/blob/master/meetings/2018/vbldm-notes-2018.02.21.md#private-protected---discussion
