### ISSUE TITLE
Suggestion: Syntax Visualizer should be able to freeze to a specific document / caret location

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/roslyn#23069]
**Version Used**: 
VS 2017 15.4.2
**Steps to Reproduce**:
When i do analyzer development, I often use syntax visualizer to help me.
but whenever i find out something about a file whose structure i am looking into, and want to code it  into my analyzer, the syntax visualizer refreshes with the caret of my analyzer file where i type.

**Expected Behavior**:
I suggest that the Syntax Visualizer window gets an additional context menu entry named "Freeze" or "Refresh behaviour" or "Locking" with three options:
- No Freezing - this behaviour is the same as it is now; the syntax visualizer follows the caret and always highlights the syntax element where the caret currently is
- Freeze file - the syntax visualizer follows the caret, but stays in the file that is currently visualized. So when i alt-tab or click to another file, the syntax visualizer still displays the things it did before i changed.
but when i click to another location in the visualized file, the syntax visualizer highlights that location
- Freeze file and location - then syntax visualizer doesn't get refreshed at all if the caret goes somewhere else. if the file gets changed, it would either refresh or put a yellow bar on top of the window with a button "refresh"

**Actual Behavior**:
the syntax visualizer wildly jumps with my caret showing everything. this not only is distracting, but also slows down visual studio and the editing experience.

**Workaround**:
the current workaround is to open another instance of visual studio where the syntax visualizer stays in a document.

**Comment by jcouv** [comment]
Tagging @jmarolf

**Comment by bernd5** [comment]
I have the same issue or need....
(in addition it slows down VS a lot...)

Can some one tell us, where we can find the source?

**Comment by dpoeschl** [comment]
The SyntaxVisualizer code lives over at https://github.com/dotnet/roslyn-sdk/tree/master/src/Tools/SyntaxVisualizer

**Comment by dpoeschl** [comment]
Ported to https://github.com/dotnet/roslyn-sdk/issues/82
