### ISSUE TITLE
BoundRangeVariable should not exist in the C# operation tree

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#23079]
As noted in https://github.com/dotnet/roslyn/pull/21356#issuecomment-327624443, we are still exposing bound range variables in C# operation tree, which should have been rewritten to bound parameter references to lambda parameter.

**Comment by mavasani** [comment]
@AlekseyTs @jinujoseph Do we want to target this for 15.5?

**Comment by AlekseyTs** [comment]
> Do we want to target this for 15.5?

I think it would be good to fix for 15.5.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/23080
