### ISSUE TITLE
.vs/{solution}/v15/sqlite3/storage.ide prevents git cleaning

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23073]
Because of this file, I cannot peform this command while Visual Studio is open:

&gt; git clean -fxd

I receive this error:

&gt; Unlink of file '.vs/SimpleExec/v15/sqlite3/storage.ide' failed. Should I try again? (y/n)

This is because Visual Studio is locking this file. To perform a git clean, I have to close Visual Studio, perform the clean, and then re-open Visual Studio. This is very annoying and time consuming.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/144530/vssolutionv15sqlite3storageide-prevents-git-cleani.html
VSTS ticketId: 520036_
_These are the original issue comments:_

Sam Harwell [MSFT] on ‎11‎/‎8‎/‎2017, 09:35 AM (31 min ago): <p>Thank you for your feedback! We have determined that this issue is not a bug. There are many ways in which the IDE can cause a git clean operation to &quot;fail&quot;, either by preventing one or more files from getting deleted or by immediately recreating the files after the operation completes. For a complete clean operation, the recommended sequence of operations is closing the IDE followed by cleaning the directory.</p>

Adam Ralph on ‎11‎/‎8‎/‎2017, 09:57 AM (10 min ago): <p>I'm sorry but that is a poor response. This was not a problem before VS2017. It is a problem that was introduced by VS2017. Whether or not it is a bug isn't relevant. The UX has deteriorated as a result of this change and I find it difficult to believe that it is not possible take some action to alleviate this problem. This is a constant pain for me. Closing the IDE in order to do a git clean isn't a workable solution. VS start up time is significant.</p>

Adam Ralph on ‎11‎/‎8‎/‎2017, 10:04 AM (2 min ago): <p>BTW</p><p>&gt; There are many ways in which the IDE can cause a git clean operation to "fail", either by preventing one or more files from getting deleted or by immediately recreating the files after the operation completes.</p><p>That's fine, I don't care about that, since it doesn't stop me doing a git clean. The problem I mention does.</p><p>A git clean is not only useful for clearing IDE generated files. It's also useful for cleaning stuff which I added myself. Those are the artifacts I see in my working tree. The IDE generated files are already ignored via my .gitignore file so they do not pollute my working tree. I don't care if the IDE re-generates them immediately after my git clean. In those cases where I do care about that, sure, I'll close the IDE before the git clean.</p>

Sam Harwell [MSFT] on ‎11‎/‎8‎/‎2017, 10:06 AM (65 sec ago): <p>Hi Adam,</p><p>I'll go ahead and move this issue to GitHub under the repository responsible for locking this file. Even though it still likely be an unsupported scenario in general (some VS scenarios which it sounds like you aren't using lock other files), maybe someone there will be able to improve this specific case.</p><p>As an immediate workaround, you should be able to use the -e flag of git to skip the specific file that's causing problems. I would expect this to be -e &lt;pattern&gt;, where &lt;pattern&gt; is one of the following:</p><ul><li>storage.ide</li><li>*.ide</li><li>sqlite3/</li></ul><p>Thank you,</p><p>Sam Harwell</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
:memo: This issue is related to #19768 and #23060, but differs specifically in that it requests the git clean operation work *without closing Visual Studio*.

**Comment by adamralph** [comment]
Looking at #23060 - that looks like the exact same issue that I am reporting. I'd say this issue is a duplicate.

**Comment by adamralph** [comment]
BTW @sharwell thanks for the tip with `-e` option. I've wrapped `git clean -fxd -e .vs` in a `cmd` file in my path as a workaround. I'd rather just exclude the entire .vs folder as it doesn't concern me what VS is doing in there. When I want to do a true git clean I'll do that with VS closed and run the usual command.

**Comment by sharwell** [comment]
@adamralph Looks like you are correct. I misread #23060.

**Comment by CyrusNajmabadi** [comment]
I believe another workaround is to not use -x, and to just add .vs to your .gitignore file.

**Comment by adamralph** [comment]
.vs is already in my ignore file. Ideally, I want to "as much of `-fxd` as possible" so I think `-e` is the slightly better workaround for me.

**Comment by Boxer-Property** [comment]
@adamralph I fixed my issue by removing my cache, verify the .gitignore has the .vs folder blocked, folder is there and do another check in. Works great now

**Comment by adamralph** [comment]
I don't see what `.gitignore` has to do with it. All that does is prevent git from recognising changes in the files in that folder. It does nothing to affect the behaviour of `git clean`.

**Comment by CyrusNajmabadi** [comment]
> It does nothing to affect the behaviour of git clean.

It should.  Git clean should not try to cleanup ignored files unless you specifically ask for that with `-x`

**Comment by adamralph** [comment]
Sorry, that's correct. But I _do_ want to clean ignored files, so I want to use `-x`.

**Comment by rahulviaan** [comment]
I was getting the same error while switching from one branch to other ,I found the reason that I was using Git Bash for switching but on the other hand solution was opened in Visual Studio with the branch being switched , So I closed the solution in V.S and run the same command from Git Bash so now the error gone !!!
