### ISSUE TITLE
ETW Sessions enabling RoslynEventSource can severely impact analyzer perf

### ISSUE THREAD

**Issue by mjsabby** [dotnet/roslyn#2308]
I was investigating an internal C# solution that has half a dozen analyzers, spending majority of their time logging to ETW, severely impacting diagnostic performance.

The following callstack is representative of the case I looked at:

 + mscorlib.ni!DomainNeutralILStubClass.IL_STUB_PInvoke(Int64, System.Diagnostics.Tracing.EventDescriptor ByRef, System.Guid*, System.Guid*, Int32, EventData*)
  + mscorlib.ni!Microsoft.Win32.UnsafeNativeMethods+ManifestEtw.EventWriteTransferWrapper(Int64, System.Diagnostics.Tracing.EventDescriptor ByRef, System.Guid*, System.Guid*, Int32, EventData*)
   + mscorlib.ni!EventProvider.WriteEvent
    + mscorlib.ni!EventSource.WriteEventWithRelatedActivityIdCore
     + mscorlib.ni!EventSource.WriteEvent
      + mscorlib.ni!ActivityTracker.OnStop
       + mscorlib.ni!EventSource.WriteEventWithRelatedActivityIdCore
        + mscorlib.ni!EventSource.WriteEvent
         + microsoft.codeanalysis.ni![COLD] Microsoft.CodeAnalysis.Instrumentation.Logger+Block.Dispose()
          + microsoft.codeanalysis.csharp.ni!CSharpSemanticModel.GetTypeInfo
           + microsoft.codeanalysis.csharp.ni!CSharpSemanticModel.GetTypeInfo
            + microsoft.codeanalysis.csharp.ni!CSharpExtensions.GetTypeInfo

Almost all of it was from calling the GetTypeInfo on SemanticModel, but there may be callsites as well.

With @pharring we discovered it was due an ETW session started from Microsoft-VisualStudio-Telemetry-PerfWatson that had enabled RoslynEventSource.

This happened on my developer machine, but I reproduced on a stock Visual Studio 2015 CTP 6 VM as well.

Proposal: At least for some heavily called functions we should have an additional check that can act as a short-circuit to not log to ETW, or tweak the EventMask for PerfWatson sessions.

**Comment by pharring** [comment]
We removed ETW logging from the compiler layer in PR #1057

**Comment by mjsabby** [comment]
Excellent, looks like this issue validated the central hypothesis in the referenced issue.
