### ISSUE TITLE
Question on stepping through Roslyn CodeAnalysis DLL's

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#23106]
**Version Used**: 
2.x
**Steps to Reproduce**:

1. There are instruction on how to contribute that explain how to fix a bug in Roslyn and test that using startup project VisualStudioSetup.Next
2. I can't find instruction on how to test my CodeFix that includes Roslyn Dll's as NuGet packages. I want to step into a Roslyn DLL. If I add my code to Roslyn.sln I need to remove all the NuGet packages, and include the Roslyn parts that were in the NeGet packages and how do do this is no obvious.

**Expected Behavior**:
Simple instructions on how to replace a Roslyn NuGet package with source from master and step into Roslyn.
**Actual Behavior**:
Conflicting instructions that don't really address how to do it. Plus the following error
```
Error	NU1108	Cycle detected. 
  CodeRefactoring1 -> HashLibrary -> Microsoft.CodeAnalysis 2.4.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 1.0.0 -> Microsoft.CodeAnalysis.				
```

**Comment by heejaechang** [comment]
tagging @mavasani

**Comment by mavasani** [comment]
@paul1956 Can you try the following:

1. Build Roslyn.sln with `/p:DeployExtension=true /p:OfficialBuild=true` so the Roslyn bits are deployed to RoslynDev hive and have version 2.6.X.
2. Change the deployment hive in your Analyzer/CodeFix project from `Roslyn` to `RoslynDev`. This can be done by changing the VSIX/Setup project's  `VSSDKTargetPlatformRegRootSuffix`property. Your project file should have: `<VSSDKTargetPlatformRegRootSuffix>Roslyn</VSSDKTargetPlatformRegRootSuffix>`.
3. F5 your analyzer solution and you should be able to step into both Roslyn and your analyzer/fix sources.

**Comment by paul1956** [comment]
@mavasani 
1. Where do I put /p:DeployExtension=true /p:OfficialBuild=true? I know how to build Roslyn using Build.cmd or open Roslyn.sln in Visual Studio and select Build/Build Solution; are you saying  I need to do something different?
2 Everyone has said I need to add my project to Roslyn, and build it. It looks like you are saying I keep my solution separate (which is good because I have menu code in VSIX project). Where do I change Roslyn to RoslynDev and add <VSSDKTargetPlatformRegRootSuffix>Roslyn</VSSDKTargetPlatformRegRootSuffix>.
3. I include Roslyn libraries through NuGet mostly 2.4 Packages, do I need to do something different to connect to the 2.6 libraries in Master?

What I am looking for is a complete set of instructions that anyone could follow without internal knowledge.

**Comment by tmat** [comment]
@paul1956 Let's step back a little bit. I don't think you should need to do anything in Roslyn repository in order to develop and debug your analyzer. Were you not able to debug thru Roslyn assemblies when referencing them from your project outside of Roslyn repository?

**Comment by paul1956** [comment]
I can debug my Analyzer with Roslyn Dlls (NuGet Packages) as a black box I just step over them. But I have found issues where I believe Roslyn is not behaving correctly and I am trying to step into Roslyn specifically the SyntaxEditor.ReplaceNode and ForEachStatementInfo.ElementType where I get unexpected results and don't know where to start.

**Comment by paul1956** [comment]
@tmat any next steps or guidance?

**Comment by tmat** [comment]
@paul1956 I am following up internally on why our public symbols are not working for stepping into Roslyn code. They should be. Will get back to you shortly.

**Comment by mavasani** [comment]
@paul1956 Sorry, I forgot to reply. You can try the following:

1. Open VS developer command prompt.
2. From the root of Roslyn enlistment execute `msbuild /m /v:m /p:OfficialBuild=true /p:DeployExtension=true Roslyn.sln`
3. Open the .csproj file for your analyzer/fixer setup project (VSIX project) and replace `<VSSDKTargetPlatformRegRootSuffix>Roslyn</VSSDKTargetPlatformRegRootSuffix>` with `<VSSDKTargetPlatformRegRootSuffix>RoslynDev</VSSDKTargetPlatformRegRootSuffix>`
4. Set the setup project as your startup project and F5.
5. In the new instance of VS you should have loaded locally built analyzer/fixer assembly and Roslyn bits. You should be able to attach debugger and step into sources using locally built symbols.

**Comment by paul1956** [comment]
1. I think I need /p:SkipApplyOptimizations=true for step 2 or I get errors
2 For step 4 above I am running the production version of Visual Studio when I hit F5 and when did I tell my project to use Roslyn Bits instead of the NuGet packages?
3. When I hit F5 I get a new version of Visual Studio that normally has my VSIX and I load a test project (Roslyn/Samples.sln) that my CodeFix can fix. The stepping happens in the Production Version of Visual Studio. So I still don't see how any of this helps. When I try stepping through Roslyn it just steps over.

**Comment by mavasani** [comment]
@paul1956 Sorry, I had missed couple of things in my steps. I have updated the above comment https://github.com/dotnet/roslyn/issues/23106#issuecomment-344137376 and also performed these steps locally to confirm I can debug both Roslyn and analyzer/fixer sources in the same VS instance. Can you please try again?

**Comment by paul1956** [comment]
@mavasani In step 7 It is not loading from where you said and the symbols are not loading
```
Microsoft.CodeAnalysis.dll ...\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_BB17500CROSLYNDEV\EXTENSIONS\MICROSOFT\ROSLYN LANGUAGE SERVICES\42.42.42.42424\Microsoft.CodeAnalysis.dll	No	N/A	Cannot find or open the PDB file.	1039	42.42.42.42424
```
When I look for Workspace.pdb for example. the only place I find it is 
```
C:\Users\PaulM\Source\Repos\roslyn-master\Binaries\Obj\Workspaces\Debug
C:\Users\PaulM\Source\Repos\roslyn-master\Binaries\Debug\Dlls\Workspaces
```
My project is getting CodeAnalysis from NuGet, do  need to modify it to get the DLL from somewhere else and if so how?

**Comment by mavasani** [comment]
> 42.42.42.42424

Seems like it is using Microsoft.CodeAnalysis.dll built without `/p:OfficialBuild=true`, which should set the version to 2.6.X. Maybe you can try deleting the contents of the entire folder `15.0_BB17500CROSLYNDEV` in your VS hive and try to build again?

> My project is getting CodeAnalysis from NuGet, do need to modify it to get the DLL from somewhere else and if so how?

Your project is just referencing the CodeAnalysis assemblies from nuget package references. At runtime it is using whatever version of Microsoft.CodeAnalysis that is loaded in VS. So if you are able to successfully build and deploy your locally built Roslyn bits into RoslynDev hive, they should be loaded in VS started with `devenv /rootsuffix RoslynDev`.

**Comment by paul1956** [comment]
I deleted C:\Users\PaulM\AppData\Local\Microsoft\VisualStudio\15.0_bb17500cRoslynDev and reran the command above in step 2. Then if I look under extensions\Microsoft\* I see 2.6.0.5673500 so I think that is being built correctly.
![image](https://user-images.githubusercontent.com/12789369/32823610-9e096fda-c992-11e7-8f23-bc34a2d1c9f2.png)

**Comment by mavasani** [comment]
> when I right-click and go to definition on ElementType it takes me to the 2.4 metadata

That is expected. You should either try to step into this property while debugging or open the source file of interest and set a breakpoint in it's accessor.

> I still can't step into ForEachStatementInfo.ElementType which was the original issue event though now symbols are loaded for Microsoft.CodeAnalysis.VisualBasic.dll

This looks like source to symbol mismatch. Are you able to open up the source file with that property and set a breakpoint? If not, you can either uncheck the debugging option "Require source files to exactly match the original version" to set breakpoint OR git clean your Roslyn enlistment and clean your hive before repeating step 2.

**Comment by paul1956** [comment]
@mavasani Could anything we did cause me to be unable to hit a breakpoint. Whenever I run my application all breakpoint are yellow in the breakpoint window and I don't see my modules loaded in the modules window. I have reinstalled Visual Studio and restored my project from a know working version of a couple of weeks ago.
