### ISSUE TITLE
Not filled copyright info in roslyn/License.txt

### ISSUE THREAD

**Issue by vblazhnov** [dotnet/roslyn#23111]
**Version Used**: 
master
**Steps to Reproduce**:

1.  Open https://github.com/dotnet/roslyn/blob/master/License.txt
2. Find " Copyright [yyyy] [name of copyright owner]" template

**Expected Behavior**:
Template is filled

**Actual Behavior**:
Template is not filled

**Comment by ektrah** [comment]
The template is part of a section that explains licensors how to use the Apache License. It's not the actual copyright notice for the licensed software.

It might be a good idea to add the actual copyright notice for Roslyn somewhere the project root, though. I've found myself looking for it in the past as well. Other license texts (e.g., MIT) typically have a template for the copyright notice, so the LICENSE file in the project root is the place where people look for it.

**Comment by gafter** [comment]
As @ektrah explained, the contents are intentional, and appropriate given that they occur in a section that instructs readers how to apply the license to their own projects.
