### ISSUE TITLE
Figure out how to better support Semantic Version Tracking

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#2311]
see this for more information

https://github.com/dotnet/roslyn/pull/2260

**Comment by srivatsn** [comment]
Considering offering this only for projects under version control.

**Comment by heejaechang** [comment]
probably now we will move to checksum rather than version for persistence.

**Comment by CyrusNajmabadi** [comment]
We have moved to checksums over versions.  Closing this out as not planned.
