### ISSUE TITLE
Use local function breaks when passing delegate to method taking object

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#23118]
**Version Used**: 
VS2017 15.5 P3

**Steps to Reproduce**:

```C#
using System;
using System.Threading.Tasks;

class Program
{
    static void Main(string[] args)
    {
        Func<string, Task> f = x => { return Task.CompletedTask; };
        Func<string, Task> actual = null;
        AssertSame(f, actual);
    }

    public static void AssertSame(object expected, object actual) { }
}
```

**Expected Behavior**:
No suggestion to convert `f` to a local function, since it breaks the call to `AssertSame` **or** a cast to the `Func` type at the callsite.

**Actual Behavior**:
Suggestion, which breaks the callsite.

Also the newline in the declaration of `f` looks really bad.

**Comment by Pilchie** [comment]
Tag @CyrusNajmabadi - interested in fixing?

**Comment by CyrusNajmabadi** [comment]
Sure!

**Comment by CyrusNajmabadi** [comment]
Can it be assigned to me so it shows up in my github queries?  Thanks!

**Comment by Pilchie** [comment]
Unfortunately no.  GitHub only allows you to assign to "contributors"

**Comment by CyrusNajmabadi** [comment]
:'(
