### ISSUE TITLE
Flaky test: TestRemoteHostConnect

### ISSUE THREAD

**Issue by khyperia** [dotnet/roslyn#23112]
`Roslyn.VisualStudio.Next.UnitTests.Remote.ServiceHubServicesTests.TestRemoteHostConnect`

Failure in `windows_release_unit32_prtest`: https://github.com/dotnet/roslyn/pull/22291

Failure in `windows_debug_unit64_prtest`: https://github.com/dotnet/roslyn/pull/23053

Failure in `windows_debug_unit32_prtest`: https://github.com/dotnet/roslyn/pull/23141

Failure in `windows_release_unit32_prtest`: https://github.com/dotnet/roslyn/pull/23398

**Comment by jcouv** [comment]
@jinujoseph Could you help route this issue? Thanks
