### ISSUE TITLE
Intermittent build failure after upgrading to latest version

### ISSUE THREAD

**Issue by xt0rted** [dotnet/roslyn#23119]
**Version Used**: 
Microsoft.Net.Compilers 2.4.0
Microsoft.CodeDom.Providers.DotNetCompilerPlatform 1.0.8

The two different messages I'm getting in my build log are
```
C:\projects\eei\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props(17,5): warning MSB3021: Unable to copy file "C:\projects\eei\packages\Microsoft.Net.Compilers.2.4.0\build\..\tools\Microsoft.CodeAnalysis.VisualBasic.dll" to "\bin\roslyn\Microsoft.CodeAnalysis.VisualBasic.dll". The process cannot access the file '\bin\roslyn\Microsoft.CodeAnalysis.VisualBasic.dll' because it is being used by another process. [C:\projects\eei\src\Domain\Domain.csproj]
       CopyRoslynCompilerFilesToOutputDirectory:
         Copying file from "C:\projects\eei\packages\Microsoft.Net.Compilers.2.4.0\build\..\tools\VBCSCompiler.exe.config" to "\bin\roslyn\VBCSCompiler.exe.config".
     CopyRoslynCompilerFilesToOutputDirectory:
         The previous error was converted to a warning because the task was called with ContinueOnError=true.
```
```
C:\projects\eei\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props(23,5):
error MSB4044: The "KillProcess" task was not given a value for the required parameter "ImagePath". [C:\projects\eei\src\EquineExchange.HelloSign\EquineExchange.HelloSign.csproj]
```

I had this happen on Azure/in Kudu a few months ago but was unable to get the build to succeed so I rolled back my NuGet packages to their original versions and builds started working again. At the same time I did get this error on AppVeyor too, but after I switched my build image from VS2015 to VS2017 it went away, but on Azure I wasn't able to fix it. Now I'm seeing it intermittently on AppVeyor after I updated these two packages.

If I rerun the build it usually passes the second time, but my builds on Azure never built so I'm worried that once I go to deploy I'll start getting failures their again too.

**Steps to Reproduce**:

Unable to consistently repro

**Expected Behavior**:

**Actual Behavior**:

**Comment by xt0rted** [comment]
Cross posting from https://github.com/aspnet/RoslynCodeDomProvider/issues/10

>After further investigation it turned out that `Microsoft.Net.Compilers` and `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` were installed to all of my projects. Once I removed `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` from all but the website project the build started succeeding again.

I don't think the issue is related to this repo, so I'm closing the issue since I found a resolution to it. Feel free to reopen or ask for more info if there could be a deeper issue here.

**Comment by AceCoderLaura** [comment]
I can't move my reference to the website project because the code that utilises the nuget package is in a separate c# project. What do I do?

I can delete the line out of the .props file but then the error comes back after restoring my nugets.

**Comment by AceCoderLaura** [comment]
This error happens without fail if the build is initiated at the command line. In Visual Studio it's only intermittent. So this leaves all my automated build processes unable to complete successfully.
