### ISSUE TITLE
VB incomplete assignment gets parsed and compiled successfully

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23126]
Using VB .Net 2017

The lines does not produce any errors:

        dim tl_x, br_x as integer
        dim tl_y, br_y as integer
        ' top-left
        tl_x =  tvCfgCon.Location.X + tvCfgCon.Size.Width   + 5
        tl_y = pnlHeader.Location.Y + pnlHeader.Size.Height + 5
        ' bottom-right
        br_x = pnlBottom.location.X + ' second addend is missed!
        br_y = pnlBottom.location.Y

The second addend is missed in the 7th line ( the line with the br_x assignment ), but the compiler does not produce any error!
The last line is interpreted as a CONDITION : it is evaluated and the result (BOOLEAN VALUE) is added to pnlBottom.location.X!!
So the first parser failure is: the second addend is missed but it has not been checked.
Second parser failure: WITHOUT any continuation character the expression parser has continued on the next line: if You remove the last line, the compiler generates (correctly) an error.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/100766/expression-parser-fails.html
VSTS ticketId: 484645_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jcouv** [comment]
Shrunken [repro](https://sharplab.io/#v2:DYLgbgRgNALiCGBnGUAmIDUAfAsAKAAUBXCYASwGMACAYWCUVvypauNMqoGUSqBZABQBKZqzEARMgFsq8KFQhUAgowCSAOxgBTAOZaATqJYBIeFQC8VAMxUMVI1WOLLAFgcBRdam4l8n73QMQA==), which also shows the syntax tree.
`a = 1 +   b = 2` is parsed as `a = (1 + b) = 2`, which is correct based on precedence. But in VB, that statement isn't an error.

So I think this is by-design. @AnthonyDGreen to confirm.

**Comment by jcouv** [comment]
@gafter @AlekseyTs I think this is by design. I'll go ahead and close.
