### ISSUE TITLE
Enable PE verification in tests of unsafe code

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#23130]
Currently `CompileAndVerify` (`src/Test/Utilities/Portable/CommonTestBase.cs`, line 126) automatically skips PE verification if the compilation has unsafe flag. We should tighten this and identify individual tests for unsafe code that should skip PE verification.

```C#
            if (verify)
            {
                // Unsafe code might not verify, so don't try.
                var csharpOptions = compilation.Options as CSharp.CSharpCompilationOptions;
                verify = (csharpOptions == null || !csharpOptions.AllowUnsafe);
            }
```

Tagging @VSadov

**Comment by VSadov** [comment]
Just specifying AllowUnsafe does not necessarily mean that the result must be unverifiable. 

I think this "don't try" should be removed. It would be ok to suppress verification for individual tests or test areas, but it does not feel right to do at the level of common test helper.

**Comment by jcouv** [comment]
I'll have a PR for https://github.com/dotnet/roslyn/issues/23132 soon. After that, could you help with the tightening the testing for unsafe code?

**Comment by VSadov** [comment]
no problem. It will be mostly adding "verify: false" to select unsafe testcases.

**Comment by jcouv** [comment]
Thanks. Do wait for my PR to go in first. It will use `verify: Verification.Fails` instead of `verify: false`.

**Comment by VSadov** [comment]
Actually fixed in https://github.com/dotnet/roslyn/pull/24062

**Comment by jcouv** [comment]
This was fixed. Closing now
