### ISSUE TITLE
Snippet Misbehavior: value is overwritten

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23138]
(using VS v15.3.5)
Today I noticed a new problem with some of my snippets. I'll give an example using one of the simplest ones--prop.

1. enter &quot;prop&quot;, hit TAB
2. for the type, enter List&lt;int&gt; (hit TAB)
3. with the property name selected, enter &quot;TestProp&quot; (hit TAB)
As soon as TAB is pressed, the &quot;TestProp&quot; is replaced with &quot;list&quot;. The expected behaviour is that each TAB will simply cycle through each item without replacing anything. 

If I repeat the same thing using type int instead of List&lt;int&gt;, there is no problem. Also, if I use List&lt;int&gt; as the type, but enter it *after* the property name is entered, no problem. 

I have also noticed this odd behavior with other snippets.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/133640/snippet-misbehavior-value-is-overwritten.html
VSTS ticketId: 510916_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by dpoeschl** [comment]
Declaration IntelliSense is getting in the way. We show the builder but tab still completes the selected item "list". Should this (and all other completion) just be disabled during snippet sessions? I thought they already were? @rchande for design insights.

**Comment by CyrusNajmabadi** [comment]
Legacy snippets are not being touched.
