### ISSUE TITLE
Unexpected behavior for is operator

### ISSUE THREAD

**Issue by taori** [dotnet/roslyn#23131]
**Version Used**: 
VS 15.4.2 Project set to current minor version of C#.
**Steps to Reproduce**:

		static void Main(string[] args)
		{
			TestWithConcreteOption();
			TestWithInterfaceOption();
			TestWithDerivedOption();
			TestWithObjectOption();

			Console.ReadKey();
		}

		private static void TestWithConcreteOption()
		{
			var interfaceOption = CreateOption();
			var context = CreateContext(interfaceOption);
			if (context is IToolContext<IGeneratorOption> gen)
			{
				Console.WriteLine($"{nameof(TestWithConcreteOption)} -> Expected behavior.");
			}
			else
			{
				Console.WriteLine($"{nameof(TestWithConcreteOption)} -> Unexpected behavior.");
			}
		}

		private static void TestWithInterfaceOption()
		{
			var interfaceOption = CreateInterfaceOption();
			var context = CreateContext(interfaceOption);
			if (context is IToolContext<IGeneratorOption> gen)
			{
				Console.WriteLine($"{nameof(TestWithInterfaceOption)} -> Expected behavior.");
			}
			else
			{
				Console.WriteLine($"{nameof(TestWithInterfaceOption)} -> Unexpected behavior.");
			}
		}

		private static void TestWithDerivedOption()
		{
			var interfaceOption = CreateDerivedOption();
			var context = CreateContext(interfaceOption);
			if (context is IToolContext<IGeneratorOption> gen)
			{
				Console.WriteLine($"{nameof(TestWithDerivedOption)} -> Expected behavior.");
			}
			else
			{
				Console.WriteLine($"{nameof(TestWithDerivedOption)} -> Unexpected behavior.");
			}
		}

		private static void TestWithObjectOption()
		{
			var interfaceOption = CreateObjectOption();
			var context = CreateContext(interfaceOption as IOption);
			if (context is IToolContext<IGeneratorOption> gen)
			{
				Console.WriteLine($"{nameof(TestWithObjectOption)} -> Expected behavior.");
			}
			else
			{
				Console.WriteLine($"{nameof(TestWithObjectOption)} -> Unexpected behavior.");
			}
		}

		private static IOption CreateInterfaceOption()
		{
			return CreateOption();
		}

		private static DefaultOption CreateDerivedOption()
		{
			return new GeneratorOption();
		}

		private static object CreateObjectOption()
		{
			return new GeneratorOption();
		}

		private static GeneratorOption CreateOption()
		{
			return new GeneratorOption();
		}

		private static IToolContext<T> CreateContext<T>(T option) where T : class, IOption
		{
			return new DefaultContext<T>(option);
		}
	}

	public class GeneratorOption : DefaultOption, IGeneratorOption
	{
	}

	public class DefaultOption : IOption
	{
		
	}

	public class DefaultContext<T> : IToolContext<T> where T : class, IOption
	{
		/// <inheritdoc />
		public DefaultContext(IOption option)
		{
			Option = option;
		}

		/// <inheritdoc />
		public IOption Option { get; }
	}

	public interface IToolContext
	{
	}

	public interface IToolContext<out T> where T : class, IOption
	{
		IOption Option { get; }
	}

	public interface IGeneratorOption : IOption
	{
	}

	public interface IOption
	{
	}

**Expected Behavior**:

TestWithConcreteOption -> "Expected behavior."
TestWithInterfaceOption -> "Expected behavior."
TestWithDerivedOption -> "Expected behavior."
TestWithObjectOption -> "Expected behavior."

**Actual Behavior**:

TestWithConcreteOption -> "Expected behavior."
TestWithInterfaceOption -> "Unexpected behavior."
TestWithDerivedOption -> "Unexpected behavior."
TestWithObjectOption -> "Unexpected behavior."

I would expect this to work the way i pointed out. Am i wrong in thinking that? 

If pattern matching is merely a feature which works with compile time information this issue would make sense i suppose - however in that case i would expect an analyzer to point out this potential issue if that is possible.

**PS: using "as" results in the same results.**
**Only TestWithDerivedOption provides a diagnostic pointing out this potential flaw.**

**Comment by gafter** [comment]
You are testing for types that are not the dynamic type of the object.

``` c#
		var interfaceOption = CreateInterfaceOption(); // of type IOption
		var context = CreateContext(interfaceOption); // of type IToolContext<IOption>
		if (context is IToolContext<IGeneratorOption> gen) // no, it is of type IToolContext<IOption>
```

**Comment by taori** [comment]
@gafter Yeah. i guess i can see why it isn't working.

Do you disagree though, that adding analyzer warnings should be added to interface+object creation to avoid this?

My guess is that the is operator works this way to avoid doing reflection on runtime objects to see if the object matches the type which it is being checked for.

**Comment by gafter** [comment]
@taori You are confusing the static type of the container, `IToolContext<IOption>`, with the dynamic type of the thing it contains, `IGeneratorOption`. The type argument of the former does not have to be the same as the latter. The container might not even contain anything that could be checked at runtime, or it may contain multiple things of different types (e.g. if it is a `List<T>`).

I'm not sure what the analyzer you suggest would do here.
