### ISSUE TITLE
Instance member signatures are shown in a static member context

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#23133]
**Version Used**: vs2017 15.4.3

**Steps to Reproduce**:
write: System.Text.RegularExpressions.Regex.Match(

**Expected Behavior**:
Show only static methods overload
**Actual Behavior**:
Show both static and instance methods overload

By the way, there are two repositories "reslyn" & "project-system", which one is the correct place talking about Visual Studio issue？

**Comment by sharwell** [comment]
> By the way, there are two repositories "reslyn" & "project-system", which one is the correct place talking about Visual Studio issue?

Normally you take a best guess: project items go to project-system and C# editor/debugging features normally go in Roslyn. There are other repositories as well. If you send something to the wrong one we will help move it to the right place. 😄 

For this issue, you found the right repository! 🎉

**Comment by CreateAndInject** [comment]
@mikkelbu There's still a bug with `Regex.Match(...)`:
IntelliSence will show  `+ 4 overloads` as soon as I move mouse to it. But it should show `+ 1 overloads`

**Comment by CreateAndInject** [comment]
Anyone is working with it?

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi or @allisonchou please close this. The fixing PR was already merged

**Comment by allisonchou** [comment]
Resolved via https://github.com/dotnet/roslyn/pull/59969
