### ISSUE TITLE
Can not use suggestion completion mode in Watch window.

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#23134]
**Version Used**: vs2017 15.4.3

**Expected Behavior**:
Can toggle between suggestion and standard completion modes or allways use suggestion completion mode in Watch window.
**Actual Behavior**:
Can only use standard completion mode in Watch window.

**Comment by CreateAndInject** [comment]
Will it be adopted?

**Comment by sharwell** [comment]
This works at least in Visual Studio 2019 Preview 2.

**Comment by CreateAndInject** [comment]
@sharwell Do you make mistake? I mean in watch window not code window.
VS2019 16.0.2 doesn't resolve this issue.
