### ISSUE TITLE
Scripting API: Is there a way to abort a long running script?

### ISSUE THREAD

**Issue by KarloX2** [dotnet/roslyn#23145]
**Version Used**: V2.4.0

**Steps to Reproduce**:

1. Use the Scripting API like explained here: https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples
2. Run a script that takes very long or forever (e.g. with an infinite loop or sleeping very long).

**Expected Behavior**:

I'd like to be able to abort the script if it doesn't complete within a defined time span.

**Actual Behavior**:

The ScriptRunner delegate accepts a CancellationToken, but by signalling to it doesn't seem to abort a script that stucks in an operation like

    while (true) ;
or

    Thread.Sleep(99999999);

How can I resolve this? 
Maybe I'd need to put the script execution in a separate AppDomain?

**Comment by tmat** [comment]
If you want a reliable cancellation I'd recommend running the scripts in a separate process. This is how C# Interactive Window in Visual Studio is implemented.

**Comment by KarloX2** [comment]
@tmat Not easy in my case. That would require many changes as the script is given a callback interface that allows access to information held in the server process.
Do you think that a separate AppDomain could solve it?

**Comment by tmat** [comment]
@KarloX2 You will have the same problem with AppDomain. It's harder to cleanly terminate a thread and unload the AppDomain.

**Comment by KarloX2** [comment]
@tmat can you please explain the problem? By saying "harder" do you mean complicated but feasible, or just not possible under certain conditions (which)?

**Comment by tmat** [comment]
@KarloX2 Pretty much impossible to do reliably (Thread.Abort does not guarantee that the thread terminates). Besides implementing calls to another AppDomain is pretty much the same as communication with a process.

**Comment by KarloX2** [comment]
Ok, thank you for your comments!
