### ISSUE TITLE
VB editor provides redundant namespace in IntelliSense

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#23146]
**Version Used**: 
VS 15.4.3, 15.5.0 Preview 3.0
**Steps to Reproduce**:

1. Minimal reproduce code:
```vb
Option Strict Off
Option Infer On
Namespace MyNamespace
    Class A
    End Class

    Module M
        Sub S()
            Dim a
            Dim l = New System.Collections.Generic.List(Of A)
            'here
        End Sub
    End Module
End Namespace
```
2. On the commented line, type `l.Add(New `

**Expected Behavior**:
IntelliSense suggets `A` after `New`. The variable name `a` should not be valid in the context after `New`.

**Actual Behavior**:
IntelliSense says `f as List(Of MyNamespace.A)`, and suggets `MyNamespace.A` after `New`, then says "redundant namespace `MyNamespace`" after completed.

**Another thing**:
15.5.0 Preview 3.0 does not follow default `Option Strict` and `Option Infer` settings and default `Imports` in project file. Should this be opened as a new issue?

**Comment by huoyaoyuan** [comment]
Still observable in 16.3

**Comment by huoyaoyuan** [comment]
No idea how to reproduce this in unit test.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to change tehse experiences.
