### ISSUE TITLE
C# Code Containing LINQ Incorrectly Formatted When Using Surround With Snippet

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23142]
Step 1. Write a multi-line LINQ statement (using the extension methods, not the keywords).

Step 2. Select the statement and type Ctrl-K + Ctrl-S to invoke the snippet menu.

Step 3.  Select the surround with option and use &quot;using&quot;.

Step 4. The LINQ statement is not correctly formatted.

I've wasted lots of time over the past couple of years fixing this text. Ctrl-K + Ctrl-D (auto-format) does not resolve the problem either.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/144123/c-code-containing-linq-incorrectly-formatted-when.html
VSTS ticketId: 519775_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by dpoeschl** [comment]
Yes, this repros for me as well, and we do attempt to format the snippet span. Interesting.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in legacy snippets any more.
