### ISSUE TITLE
add struct as file template.

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#23157]
you can create new class or interface when creating new file. why not list struct for sake of completeness?

**Comment by jcouv** [comment]
Tagging @Pilchie to help route and triage. Thanks

**Comment by Pilchie** [comment]
Tagging @jmarolf - there is currently a discussion about trying to put most of the templates somewhere open so that the community can contribute to them.  

I'm not *against* this, I just don't think it's important enough that we'll get to it any time soon.  (There is also no enum template AFAIK).

**Comment by CyrusNajmabadi** [comment]
This is not something roslyn controls.  Could be a feature request to whoever owns the templates though.
