### ISSUE TITLE
Use Local Function refactoring doesn't work when delegate is invoked with Invoke

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#23150]
The following test shows a case where the Use Local Function refactoring is not available. However, since the *only* member invoked on the delegate is `Invoke`, the refactoring could be provided.

⚠️ A new test will need to be created showing that the refactoring is still not offered if another member is invoked on the delegate, such as `ToString()`.

https://github.com/dotnet/roslyn/blob/3a34dce98a5482652f9976f0fe482a0b54ab5215/src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs#L1438-L1459

**Comment by CyrusNajmabadi** [comment]
> However, since the only member invoked on the delegate is Invoke, the refactoring could be provided.

Agreed.  Note though that the refactoring would have to change the code from an invocation of 'Invoke' to a direct invocation of the local function.  i.e. ```local.Invoke()``` is not ok, but ```local()``` is ok.

**Comment by zaytsev-victor** [comment]
@sharwell I want to take it. I have a fix for this issue, but I found one problem with this refactoring.
This code:
```csharp
class Enclosing<T> where T : class
{
    delegate T MyDelegate(T t = default);

    public class Class
    {
        public void Caller(T t)
        {
            MyDelegate local = x => x;
            local(t);
        }
    }
}
```
is changed to
```csharp
class Enclosing<T> where T : class
{
    delegate T MyDelegate(T t = default);

    public class Class
    {
        public void Caller(T t)
        {
            T local(T x) => x;
            local();
        }
    }
}
```
which is incorrect (local function parameter should have default value).
I fixed this issue too, but it works if we have declaration of this delegate in source code.
If the delegate comes from library (*.dll) refactoring produces the following code:
```csharp
class Enclosing<T> where T : class
{
    public class Class
    {
        public void Caller(T t)
        {
            T local(T x = null) => x;
            local();
        }
    }
}
```
I take info about default value from ```delegateType.DelegateInvokeMethod.Parameters[0].ExplicitDefaultValue``` (in case if it is SimpleLambdaExpressionSyntax)

Are we ok with that or I can take info about default value from another place?

**Comment by CyrusNajmabadi** [comment]
Getting the explicit value from delegateType.DelegateInvokeMethod.Parameters should work for both source and metadata.  Shouldn't it?

**Comment by zaytsev-victor** [comment]
@CyrusNajmabadi it works but as you can see in example above it returns ```null``` instead of ```default```

**Comment by CyrusNajmabadi** [comment]
That's fine.  That's how most of our features work afaik.  for example:

```c#
interface I<T> where T : class
{
    void M(T t = default);
}

class C<T> : I<T> where T : class
{

}
```

Implement-interface here will pick 'null' not 'default'.
