### ISSUE TITLE
Unused parameter in Microsoft.CodeAnalysis.CSharp.Binder.CheckFieldRefEscape (potential bug?)

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#23166]
Enabling CA1801 (unused parameter rule) fires it for [CheckFieldRefEscape](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Binder/Binder.ValueChecks.cs,a204c04b97fd2e6c) and [CheckFieldLikeEventRefEscape](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Binder/Binder.ValueChecks.cs,09e0b3ce0e53064a) for parameter `checkingReceiver` being unused. We should either use this parameter or remove it from the signature.

**Comment by jcouv** [comment]
@VSadov Could you take a look?

**Comment by VSadov** [comment]
the parameters should be removed

**Comment by mavasani** [comment]
> the parameters should be removed

Thanks, I can do this as part of my change to remove all unused parameter references in Roslyn (coming soon). I hope to enable this rule by default in Roslyn after the cleanup.

**Comment by VSadov** [comment]
I already have it as a part of another fix, but if yours goes in first, that would be fine too.
