### ISSUE TITLE
Unused parameter in Microsoft.CodeAnalysis.CSharp.SyntaxFactory.MethodDeclaration

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#23168]
See http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/MethodDeclarationSyntax.cs,35. Parameter `semicolonToken` is unused in the method body, but it seems it should either be passed as the last argument to the call to SyntaxFactory.MethodDeclaration OR we should check that the token is default syntax token and throw an exception otherwise. Either case, we should not ignore an argument to public API completely.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/37493
