### ISSUE TITLE
replace/original feature

### ISSUE THREAD

**Issue by npolyak** [dotnet/roslyn#23176]
What is happening with replace/original feature described in https://github.com/dotnet/roslyn/blob/master/docs/features/generators.md? It seems the keywords are still not part of the language.

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/issues/19505

The language feature is only a part of the end-to-end story, and it turns out the tooling/IDE work to make this a good experience is quite significant. So while the language feature was prototyped in the C# 7.0 timeframe, the feature is not on the roadmap for 7.x or 8.0 at this point.
Thanks for voicing your interest, it will help rank relative to other efforts.

Tagging @cston @jaredpar @jinujoseph as FYI

**Comment by npolyak** [comment]
The **replace** key would be very useful even outside of the full 'generators' story. I wanted to use it for Single File Generators so that the main code would be clean and the partial class generated by a Single File Generator would contain the boilerplate code. I wonder if it is possible to factor the **replace** feature out and implement it separate from everything else?

**Comment by jcouv** [comment]
@npolyak I don't understand the details of your scenario well enough, but my intuition is that you can achieve most **replace** scenarios with `virtual` and `partial`.

LDM didn't feel that `replace` is useful absent source generators, and source generators are costly (IDE, performance, etc). The last [LDM notes](https://github.com/dotnet/csharplang/blob/5cb84f4a66fd27dcd13395b12870f93e232ec3c5/meetings/2017/LDM-2017-02-21.md#replaceoriginal) on that.

**Comment by jcouv** [comment]
I'll close the present issue. Feel free to voice your interest on https://github.com/dotnet/csharplang/issues/107

**Comment by npolyak** [comment]
sorry for a delay answering you. 
Here is an example - a class implementing INotifyPropertyChanged class. Most property simply need to add a boiler plate code like `OnPropertyChanged(nameof(<propName>))` at the end. 
I intended to create a class that would define such properties as Auto properties, and provide an Attribute so that a single code generation would know to convert them to field backed properties defined in a partial class with keyword **replace**. 
Now I'll have to come up with a different contraption to achieve that.
