### ISSUE TITLE
SymbolSearchUpdateEngine needs thinking of how it should work for VS for Mac

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#23184]
@KirillOsenkov claims it's bad [here](https://github.com/dotnet/roslyn/issues/22959#issuecomment-344480992) but didn't articulate.

**Comment by jasonmalinowski** [comment]
@KirillOsenkov can you explain what is bad here?

**Comment by KirillOsenkov** [comment]
Basically it's bringing in Microsoft.VisualStudio.RemoteControl.dll and we see crashes on Mac where we don't have this .dll. We could work on adding it, but it might need bringing more and more dependencies in a transitive fashion.

We'd rather factor out the implementation of how it talks to RemoteControl to EditorFeatures.Wpf or elsewhere, so that behavior is provided by the host.

**Comment by jasonmalinowski** [comment]
@KirillOsenkov thanks!

**Comment by CyrusNajmabadi** [comment]
I think we'd really like to have "Microsoft.VisualStudio.RemoteControl.dll" avaiable on the mac.

Indeed, given how simple the impl is for that dll, it's unclear to me why it wouldn't be available.  All that dll does is proved a nice caching front end for http requests to azure hosted data.  VS already uses it extensively for lots of subsystems that need to do things like update feeds.  It seems like that's generally useful functionality that hsould also be on VS4Mac. :)

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi This is just for NuGet package search feature where we'll also add NuGet packages? If so, then For Now(tm) we'll just move it to a different layer, as we have none of the downstream requirements working for VS for Mac either.

**Comment by KirillOsenkov** [comment]
Longer term I definitely have a work item to make it available. It's just this is blocking high priority short term work, so the quicker the fix the better. Also we suspect there might be a Mono runtime bug to deal with, so I'd rather not get into that now. But overall I agree with the sentiment.

**Comment by CyrusNajmabadi** [comment]
Whatever you think is best :)  I'd like it to be available at a layer such that it works for VS4Mac and VSCode.

**Comment by jasonmalinowski** [comment]
Oh yeah, I want it there too. Unfortunately what I want and what is compatible with our engineering time allotted tend to differ... :-)
