### ISSUE TITLE
EditorFeatures (non-WPF) is importing ISignatureHelpBroker which it shouldn't

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#23183]
ISignatureHelpBroker should only be consumed by the presenter in the WPF layer.

**Comment by dpoeschl** [comment]
@jasonmalinowski Can you help me triage this? Does it need fixed for/prior to 15.7? Is it holding anything up with VS for Mac?

**Comment by jasonmalinowski** [comment]
@dpoeschl If it's in the "non-blocking" section, it's non-blocking and can be fixed when we get to it. For this one we might get a better editor API before we would touch it directly.

**Comment by CyrusNajmabadi** [comment]
This is only in the wpf layer now afaict.  Closing out.
