### ISSUE TITLE
Roslyn needs to unify onto a single version of the wait indicator service

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#23186]
Right now the editor snapshotted a copy of our IWaitIndicator/IWaitContext stuff, which means anybody trying to compose Roslyn has to implement those interfaces twice. One is good, two is bad.

**Comment by jasonmalinowski** [comment]
@olegtk So what's the state of the art here now? As a part of the command handler stuff is some of this is public now, right?

**Comment by olegtk** [comment]
Yes, there is public IUIThreadOperationExecutor/IUIThreadOperationContext (which has no-op default implementation already). But it lacks extensibility point you will need to implement integration with IGlobalOperationNotificationService that exists right now: http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Utilities/VisualStudioWaitIndicator.cs,73
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/550475 tracks it.
