### ISSUE TITLE
Microsoft.CodeAnalysis.VisualBasic.EditorFeatures still references Text.UI.Wpf

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#23182]

**Comment by jinujoseph** [comment]
@jasonmalinowski good to close this ?

**Comment by jasonmalinowski** [comment]
@jinujoseph: nope, [still broken](https://github.com/dotnet/roslyn/blob/42abf2e6642db97d2314c017eb179075d5042028/src/EditorFeatures/VisualBasic/BasicEditorFeatures.vbproj#L35).

**Comment by jinujoseph** [comment]
keeping in 15.6 to understand this more

**Comment by jasonmalinowski** [comment]
Fixed in dev15.7.x-vs-deps.
