### ISSUE TITLE
Consider merging AbstractFlowPass and PreciseAbstractFlowPass

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#23207]
There were good intentions in separating AbstractFlowPass and PreciseAbstractFlowPass, but right now the diff seems to be unused.

In particular `PreciseAbstractFlowPass.VisitTryStatement` is essentially a dead code right now since the containing class is abstract and the method is overriden in the only derived class.

The problem with dead code is that we cannot effectively maintain or evolve it since it cannot be tested.

For once, I think the `PreciseAbstractFlowPass.VisitTryStatement` may have the same bug as in https://github.com/dotnet/roslyn/issues/19831 , or maybe not - I cannot tell one way or another, nor I can tell how it could be fixed and the fix tested.

It can always be fetched from history if needed again. I think we should remove the method and merge two types.

**Comment by VSadov** [comment]
CC: @gafter @AlekseyTs

**Comment by gafter** [comment]
The separation was there to support the dispose checker, which is no longer in the compiler. So is all the infrastructure to track exceptions in the pending branches. If you're getting rid of `PreciseAbstractFlowPass`, then you can get rid of that too.
