### ISSUE TITLE
Two CodeProviders have same names

### ISSUE THREAD

**Issue by Droni** [dotnet/roslyn#23218]
**Version Used**: 15.4.4

```cs
namespace Microsoft.CodeAnalysis.VisualBasic.ConvertToInterpolatedString
{
	[ExportCodeRefactoringProvider("Visual Basic", new string[]
	{

	}, Name = "Extract Method Code Action Provider"), Shared]
	internal class VisualBasicConvertConcatenationToInterpolatedStringRefactoringProvider : AbstractConvertConcatenationToInterpolatedStringRefactoringProvider
	{
        }
}
```

```cs
namespace Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod
{
	[ExportCodeRefactoringProvider("C#", new string[]
	{
		"Visual Basic"
	}, Name = "Extract Method Code Action Provider"), Shared]
	internal class ExtractMethodCodeRefactoringProvider : CodeRefactoringProvider
	{
        }
}
```

**Comment by sharwell** [comment]
@Droni Is this a problem? If so, can you describe the impact?

**Comment by Droni** [comment]
@sharwell it is a not a big problem, we have corrected this behavior on our side. But I think you have automated tests for this situation. We use the provider's name to identify duplicates, and delete if such provider is provided by our extension. In this case we can determine by the type fullname, but I think automated test cases should helps to exclude this situation in the future.

**Comment by Droni** [comment]
Also, "Extract Method Code Action Provider" is not good name for converting to the string interpolation :)

**Comment by CyrusNajmabadi** [comment]
I wouldn't close this.  This def seems worth fixing.  @Droni Would you like to make a PR?  If not, i can do this.

**Comment by Droni** [comment]
@CyrusNajmabadi sure. I thought, since there is no answer, then the problem is not interesting. I have reopened this ticket.

**Comment by CyrusNajmabadi** [comment]
Looks to no longer be an issue.  Closing out.
