### ISSUE TITLE
Proposal: 'this' as return type (true: void, but like return this)

### ISSUE THREAD

**Issue by firda-cze** [dotnet/roslyn#2322]
There are many classes that return the object from most of the methods (e.g. `StringBuilder`) for easier manipulation. Extension methods (e.g. LINQ) do the same - return the interface taken as first 'this' argument.

This is not the same as return type covariance, although the reason for it is sub-classing (derived classes). This could be implemented with attribute. The actual return type would probably be `void`, but the attribute would tell the compiler to emit helper code reusing the variable for chained-calls.

```C#
class MyBase
{
    this DoWork()
    {
        Something();
    //  no return needed as it behaves like 'void'
    }
}
class MyClass: MyBase
{
    this DoNext() {}
}

var my = new MyClass();
my.DoWork().DoNext();
```

The above shows the problem: We cannot call `DoNext()` on returned value because it would be of type 'MyBase' without this extension.

P.S.: It could as well be implemented with *no type*, but I have selected 'this' to distinguish it from constructor.

**Comment by HaloFour** [comment]
Dupe of #155.

**Comment by firda-cze** [comment]
I have moved to https://github.com/dotnet/roslyn/issues/155#issuecomment-97324614
