### ISSUE TITLE
CodeAction GetChangedSolution broken ?

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#23239]
Happens in vs4mac.

action.GetChangedSolutionAsync is missing post processing in the generated code - GetChangedSolutionInternalAsync(true, token); is doing the wrong thing for us. Are we doing something wrong ?

VSTS: https://devdiv.visualstudio.com/DevDiv/_workitems?id=518783&fullScreen=true&_a=edit

This fixes it for us:
https://github.com/mono/monodevelop/pull/3359

**Comment by CyrusNajmabadi** [comment]
> action.GetChangedSolutionAsync is missing post processing in the generated code

That's by design.  If you need the post processing, you should call: GetOperationsAsync
