### ISSUE TITLE
Investigate MS.CA.EditorFeatures.dll usage of Microsoft.VisualStudio.Language.Intellisense.ITelemetryDiagnosticID`1'

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#23230]
MS.CA.EditorFeatures.dll uses `Microsoft.VisualStudio.Language.Intellisense.ITelemetryDiagnosticID`1'` which requires a reference to MS.VS.Language.IntelliSense.dll, which in turn brings more references that are undesired in VSMac.

Is there anything we can do to remove that reference?

**Comment by CyrusNajmabadi** [comment]
Closing out as vsmac is not a thing anymore.
