### ISSUE TITLE
Structure guide lines not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23234]
Structure Guide Lines don't appear where they should for one section of one C# code module.  The code compiles without error, and I can use &quot;Ctrl + }&quot; to jump between open and close braces, so I know I don't have a mis-match of { and }'s.  I do get 5 levels of Structure Guide Lines, but starting with an:

```
else
{
```

they stop, all the way until the closing brace associated with the else block.

Sometimes, when only part of the else block is displayed on the screen, I see the lines appear, but scrolling down makes them disappear.  In other areas in the same method, they appear properly many levels deeper than the 5 that are shown in the problematic section of code.

I've tried closing and re-opening the file, re-starting Visual Studio, re-starting Windows, copying the code into a new file, and deleting the code and re-writing it a few lines at a time, but in all cases the problem remains.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/144006/structure-guide-lines-not-working.html
VSTS ticketId: 519689_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Do you have an example file that demonstrates the issue.  Note: Structure-Guides are syntactic.  So we'd only need hte file, and not the rest of the project the file belongs to.

**Comment by sharwell** [comment]
@CyrusNajmabadi Here's a cropped image:

![image](https://user-images.githubusercontent.com/1408396/32967111-fea1fcf2-cba1-11e7-9de9-915609c39f32.png)

**Comment by CyrusNajmabadi** [comment]
Super wacky.  Do we have a repro of the code involved here?

**Comment by dpoeschl** [comment]
I haven't been able to reproduce the failure thus far.

**Comment by CyrusNajmabadi** [comment]
We haven't been able to reproduce this.  Closing out.
