### ISSUE TITLE
VBCSCompiler.exe leaks handle to directory containing analyzer, preventing cleanup in cloud build

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#2324]
vbcscompiler.exe opens a handle to the directory containing an analyzer assembly and does not release it after compilation is finished.

Repro steps:

1. Create a C# project.
1. NuGet console: Install-Package StyleCop.Analyzers
1. Close VS.
1. Build the project from the command line.
1. While vbcscompiler.exe is still running, try to delete the packages\stylecop.analyzers.1.0.0-alpha005\tools\analyzers directory. It will fail.
1. Also while vbcscompiler.exe is running, use Process Explorer to verify that that process is holding a handle to the tools\analyzers directory.
1. Kill the process. Then delete the folder and it should succeed.

![untitled](https://cloud.githubusercontent.com/assets/3548/7374391/f18e2582-ed86-11e4-8c42-c4d8f5a4d69c.png)

**Comment by tmeschter** [comment]
I strongly suspect, but have not yet verified, that this is because we have a `FileSystemWatcher` open for the analyzer's directory so that we know when the assembly changes.
