### ISSUE TITLE
Dealing with un-annotated library APIs

### ISSUE THREAD

**Issue by fordth** [dotnet/roslyn#23259]
Visual Studio 2017 15.5
Latest BETA version of C# Nullable references

**Steps to Reproduce**:

```csharp
int? age = null;
string? name = null;
Console.WriteLine("{0}{1}", name?.ToUpper(), age?.ToString());
```

**Expected Behavior**:
The program should execute without an issue.

**Actual Behavior**:
The compiler is stating the following issue with name?.ToUpper() "Possible null reference argument", however nullable value types are ok as expected.
![issue](https://user-images.githubusercontent.com/10094080/32965837-dc702524-cba5-11e7-9083-8f5d214e5b34.jpg)

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler We're going to need an issue for every comment we get that's a case involving lack of nullability annotations in reference assemblies.

**Comment by fordth** [comment]
Ok, I think I understand the problem now just from your comment.

**Comment by jcouv** [comment]
@sharwell We can use this one (updated the title).

**Comment by jcouv** [comment]
Just to clarify this is by-design for current prototype of "nullable reference types" feature, but it is something that we're monitoring and think we may need to further address.

**Comment by sharwell** [comment]
Cases I've hit so far:

* `Delegate.CreateDelegate` for a static method
* Trying to compare a `Type` with `null` using operator `==`
* Trying to compare an object with `null` using `ReferenceEquals`
* Invoking a method using `MethodInfo.Invoke` and passing an explicit null to avoid creating an array for empty arguments

**Comment by sharwell** [comment]
`string.IsNullOrEmpty` rapidly moving up my list...

**Comment by Tragetaschen** [comment]
This is going to get interesting...

- Static properties via reflection:
```csharp
PropertyInfo a = …;
a.GetValue(null); // get value of static property
a.SetValue(null, ...); // set value of static property
```
- `new Timer(callback, null, -1, -1)`. `callback`s object parameter inherits the nullability of the second parameter

**Comment by Tragetaschen** [comment]
This one probably deserves a separate comment: The `[Required]` annotation for model binding in ASP.NET (Core) and model validation.

Typically, you have a model class
```csharp
using System.ComponentModel.DataAnnotations;
class MyModel  // shows CS8618
{
  [Required]
  public string MyValue { get; set; }
}
```
and a controller action
```csharp
  public IActionResult MyAction([FromBody] MyModel myModel)
  {
    if (!ModelState.IsValid) // This is the null check
      return BadRequest();
    // myModel.MyValue is known to be non-null
  }
  }

**Comment by yaakov-h** [comment]
Here's what I've found in just a few hours of trying to compile some of my code with the preview:

* Trying to compare an `Assembly` with operator `==`
* `string.Format` with a nullable reference in the params array
* `PropertyInfo.GetValue(object, null)`
* All of the `TryParse` methods (`Guid`, `int`, etc.)
* `Type.GetType(string, null, typeResolverFunc, bool)`
* `ThreadPool.RegisterWaitForSingleObject` with a null `state` object
* `string.IsNullOrEmpty` and `string.IsNullOrWhiteSpace`

The `operator ==` ones are particularly annoying because I can't just compare them against `null`, I have to compare them! against `null!`, i.e. dammit both sides of the operator.

**Comment by sharwell** [comment]
> The operator == ones are particularly annoying because I can't just compare them against null, I have to compare them! against null!, i.e. dammit both sides of the operator.

@yaakov-h You can use `x is null`.

**Comment by IdeaHunter** [comment]
Unit tests affected as well
Assert.IsNotNull // <= throws exception

**Comment by jcouv** [comment]
The general issue has been solved by treating libraries as "oblivious" by default. This avoids un-necessary warnings, but potentially hides some useful ones.
I've scrubbed this issue to identify APIs that fall into that second category and started a list to track such candidates for annotations (https://github.com/dotnet/corefx/issues/33880).

I'll go ahead and close the present issue.
