### ISSUE TITLE
'Use var' should not be suggested when explicit type is not redundant

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#23250]
VS 15.5 Preview 4

```cs
Enum.TryParse("Test", out ConsoleColor x);
```

Roslyn suggests that you replace `ConsoleColor` with `var`, but specifying the type explicitly is actually necessary or the generic type argument for `Enum.TryParse<>` can't be inferred.

**Comment by sharwell** [comment]
Already fixed in #23135 in response to https://github.com/dotnet/roslyn/pull/23135#discussion_r150430010.
