### ISSUE TITLE
Converting setter to block body leaves set keyword on getter line

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#23251]
VS 15.5p4, apologies if there's an existing issue I failed to locate.

I frequently have code like this:

```cs
private bool someProperty;
public bool SomeProperty { get => someProperty; set => Set(ref someProperty, value); }
```

And need to add code to the setter, so I use the block body code action. This results in:

```cs
private bool someProperty;
public bool SomeProperty
{
    get => someProperty; set
    {
        Set(ref someProperty, value);
    }
}
```

I would expect `set` to be on its own line.

**Comment by CyrusNajmabadi** [comment]
we'd take a small community fix on this.
