### ISSUE TITLE
Intellisense should offer extension methods that require adding a using directive

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#23260]
VS 15.5p4.

This is among my top most common uses of ReSharper's intellisense. (I have a goal of being able to use vanilla VS one day.)

Given the following definitions in some other file or library:
```cs
namespace Some.Namespace
{
    public class X { }
    public class Y { }
    public static class Extensions
    {
        public static void IEnumerable<Y> Operation(this IEnumerable<X> source);
    }
}
```

If I am dotting off an expression of type `IEnumerable<X>` and there is currently no using statement to bring the extension method into scope, I want intellisense to offer `Operation() (using Some.Namespace)` somewhere in the list. Upon autocompletion, the using statement should be added. 
(Probably goes without saying but Ctrl+Z should atomically undo this in case of a mistake.)

This way I can autocomplete without being confident of the exact wording and without having to drop the context I'm in and type in the using directive. Which, unlike the extension method name, is usually not a name that is top of mind.

**Comment by Pilchie** [comment]
Part of https://github.com/dotnet/roslyn/issues/7053

**Comment by dpoeschl** [comment]
Closing out, as we definitely want to do this as part of https://github.com/dotnet/roslyn/issues/7053 (as Kevin points out).
