### ISSUE TITLE
Wrapper methods and nullable reference types

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#23267]
**Version Used**: Preview 11152017

**Steps to Reproduce**:

The following code:

```csharp
IVsExpansionEnumeration expEnum = null;
if (ErrorHandler.Succeeded(ErrorHandler.CallWithCOMConvention(() => expansionManager.EnumerateExpansions(language, shortcutsOnly ? 1 : 0, snippetTypes, snippetTypes.Length, includeNullType ? 1 : 0, includeDuplicates ? 1 : 0, out expEnum))))
{
    uint count;
    ErrorHandler.ThrowOnFailure(expEnum.GetCount(out count));
}
```

**Expected Behavior**:

A clear way to update the code to use nullable reference types without the "frustration" operator (`!`).

**Actual Behavior**:

The original code reports a warning when `expEnum` is initialized to null. If the initialization is removed, the use site reports an error that `expEnum` might not be initialized.

💭 The two ways I see to deal with the issue today are the following:

1. Use `null!` where `expEnum` is initialized
2. Add `&& expEnum != null` to the `if` statement condition

Between these two, I lean towards option 1 as preferable, because it seems unlikely to ever have a low-noise "unnecessary null check" warning related to option 2. Therefore, option 1 is easier to revisit in the future, and better expresses the situation as a limitation due to nullable reference types functionality.

**Comment by CyrusNajmabadi** [comment]
I agree.  Ideally, the compiler will also warn (now) or in the future for unnecessary !s.  !s can then be the bit of syntax to help migrate code forwward . Then as it is fixed up, our tooling can get rid of it from places it is no longer necessary.

**Comment by jaredpar** [comment]
>  If the initialization is removed, the use site reports an error that expEnum might not be initialized.

Why do you get this error? The first use is via `out` hence there should be no error.

**Comment by gafter** [comment]
The out argument is inside a lambda.  Which might not be run by the method it is passed to.  The compiler's behavior on these examples is correct.
