### ISSUE TITLE
Return null from async/await function

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#23275]
**Version Used**: 
11152017

**Steps to Reproduce**:

``` csharp
private async Task<object?> foo()
{
    await Task.Delay(1000);
    return null; // CS8600
}
```

**Expected Behavior**:

The "return type" is declared to be possibly `null` (`object?`), so there shouldn't be a warning.

**Actual Behavior**:
There's a warning.

**Comment by CyrusNajmabadi** [comment]
Can you specify if you're using any sort of special branch of Roslyn or the language for this?  "object?" is not legal in C# up through 7.2, but i'm guessing you're trying out a branch with nullable-reference-types support.

If so, please let us know which branch you're using.  Thanks!

**Comment by jmarolf** [comment]
11152017 I believe does refer to the preview of the nullable refs listed here: https://github.com/dotnet/csharplang/wiki/Nullable-Reference-Types-Preview

**Comment by Tragetaschen** [comment]
Yes, that's the one
