### ISSUE TITLE
Quick action to initialize field or property from constructors

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#23271]
(Following the pattern of reporting my most essential quick actions with the goal of being able to use vanilla VS one day.)

When I start a new class or struct, I'll often write out fields and properties with the desired modifiers and accessors. When I'm done, I'll either generate a constructor initializing all of them, or I'll add them to all constructors one by one in the order I want, potentially skipping some.

```cs
public class Test
{
    private readonly Stream backingStream;
}
```

I would expect to be able to <kbd>Ctrl</kbd>+<kbd>.</kbd> on the field declaration and select 'Initialize from constructor' (or 'constructors'). If a constructor exists and already has parameters initializing a field or property declared before or after the declaration I'm on, I'd like the order to be mirrored in the constructor parameters. This is a huge time saver.

```cs
public class Test
{
    private readonly Stream backingStream;

    public Test(Stream backingStream)
    {
        this.backingStream = backingStream;
    }
}
```

I'm happy to provide more examples.

**Comment by CyrusNajmabadi** [comment]
@jnm you can currently do this:

1. Generate constructor flexibly:
![image](https://user-images.githubusercontent.com/4564579/32986045-15506016-cc7d-11e7-96bb-8010df4c1a0c.png)

![image](https://user-images.githubusercontent.com/4564579/32986049-243716d8-cc7d-11e7-9e0b-8bd7d2975239.png)

2. Select the fields you care about directly and create a constructor from them.

![image](https://user-images.githubusercontent.com/4564579/32986062-64823556-cc7d-11e7-8ad5-21b67c403fd7.png)

3. Add a parameter to an existing constructor:

![image](https://user-images.githubusercontent.com/4564579/32986065-73fc4ae4-cc7d-11e7-9251-eb8425497670.png)

4. Create a field from a constructor parameter

![Uploading image.png…]()


At this point, there are an enormous number of mechanisms to speed up creating and working with constructors/properties/fields.  I don't know if we want even more of them, and even more places where these options show up :-/

**Comment by jnm2** [comment]
I wonder why (2) wasn't showing up for me? Obviously that covers part of my ask.

As to (4), that's only covering one direction. If I write the field or property first amd then want to add it to all constructors, I'm out of luck. This is exactly the kind of thing I need fleshed out.

**Comment by CyrusNajmabadi** [comment]
> I wonder why (2) wasn't showing up for me? Obviously that covers part of my ask.

Were you selecting the field(s)?

**Comment by CyrusNajmabadi** [comment]
> As to (4), that's only covering one direction. If I write the field or property first and then want to add it to all constructors, I'm out of luck. 

No you're not.   You can select all the fields you want to make a constructor out of.  If they match an existing constructor, we'll offer to add the new fields to the end of it.  For example:

![image](https://user-images.githubusercontent.com/4564579/32995982-6dadb376-cd31-11e7-9842-d6eb02263b18.png)

Note how many permutations there already are for this sort of case.  We already support making a totally new constructor:

![image](https://user-images.githubusercontent.com/4564579/32995986-7f4613a8-cd31-11e7-8fd2-923458b3e598.png)

A constructor that delegates to the constructor you already have:

![image](https://user-images.githubusercontent.com/4564579/32995991-8a1b7142-cd31-11e7-9dab-c6f6394903e7.png)

And even adding the parameters as optional so as not to break any existing callers:

![image](https://user-images.githubusercontent.com/4564579/32995998-98f45e0e-cd31-11e7-83e6-47c4ced8f84d.png)

--

This is on top of the other mechanisms i listed above.   Right now i think we have nearly a dozen different permutations of ways to create/modify constructors and fields/props.  We even do a lot of work to understand the patterns that are common used.  For example:

![image](https://user-images.githubusercontent.com/4564579/32996009-cdf905f0-cd31-11e7-8a58-52d5cc20e6cd.png)

Here we know that we should respect your parameter ordering in both the assignments, and in the field list.  

--

I'm really hesitant for there to be *even more* ways to do this sort of thing.  We did a ton of work to actually trim down the options and to try to make the experience much more streamlined as these lightbulbs were getting out of hand.  I'm wary about trying to solve the "initialization" pattern problem from every direction, when we already support so many paths already.

**Comment by CyrusNajmabadi** [comment]
Note: 

>I would expect to be able to Ctrl+. on the field declaration and select 'Initialize from constructor' 

Currently, several of htese features require you to make a selection.  That makes sense for when you have multiple fields/props you want to consider.  But it's worth us taking a look at if we should at least offer some of these if your caret is just on a single constructor, even without a selection.

**Comment by jnm2** [comment]
Ah... making a selection is the missing link here. That's not discoverable when you've never been made aware that making a selection (wider than zero) has an effect on the quick actions listed.

I do have a strong preference for a behavior at selection length 0 to be consistent with the behavior as the length approaches the limit 0.

> I'm really hesitant for there to be even more ways to do this sort of thing. 

You keep saying this even after showing me that something already exists that does what I'm looking for. 
Why would I continue asking for a feature which already exists? :D
Now that I know it exists, I may have suggestions like making selects behave consistently but I'm generally opposed to having two ways to do the same thing. The existing way would have to somehow be unrecoverably bad– not the case here.

**Comment by alrz** [comment]
>But it's worth us taking a look at if we should at least offer some of these if your caret is just on a single constructor, even without a selection.

I had also trouble discovering this untill I asked around about it. selection is not the first thing that comes to mind. I think we should have a code generation context menu item that appears in the class body when selection length is zero. once you select "generate constructor" we then show select member dialog with the member at the caret position preselected.

**Comment by CyrusNajmabadi** [comment]
I would be ok with that.  Tagging @kuhlenh since she is the lightbulb whisperer.

**Comment by jnm2** [comment]
Another problem with the current selection logic is that no actions show up if the starting or ending line is partially selected or if you select all the whitespace back to the prior line which is what I do al lthe time because it's faster. For example, skipping `a` to generate a constructor for `b` and `c`:

```cs
{
    private readonly int a;/* Selection start */
    private readonly int b;
    private readonly string c;/* Selection end */
}
```

**Comment by CyrusNajmabadi** [comment]
PRs welcome :)

**Comment by kuhlenh** [comment]
@jnm2 @CyrusNajmabadi - The generate constructor docs are here now: https://docs.microsoft.com/en-us/visualstudio/csharp-ide/code-generation/generate-constructor. Hope that helps!

**Comment by jnm2** [comment]
@kuhlenh This kind of documentation is amazing. Thank you!
