### ISSUE TITLE
Adding a dammit operator can hang Visual Studio

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#23278]
**Version Used**: 
VS 15.5 Preview 4 with the Nullable Reference Types Preview 11152017

**Steps to Reproduce**:
```csharp
using System.Threading;
class bar
{
  bar()
  {
    var foo = new Timer(callback); // Shows CS8622 for callback
  }
  private static void callback(object? _) { }
}
```
When you add a `!` after callback in `Timer`'s constructor VS hangs / crashes.

**Comment by jinujoseph** [comment]
Ivan to triage

**Comment by ivanbasov** [comment]
Tried to reproduce with VS 15.7.0. Could not get the issue.
Steps I tried:
1. Created an .NET Framework Class library project.
2. Inserted the code mentioned.
3. Observed two syntax error in the code
4. Inserted `!` after 'callback' in the Timer's constructor.
As I understand, VS previously hang after the edit. In my case, there were no hangs or crashes. Resolving the issue.

If my steps were incorrect, please provide correct ones. If you still see the issue, the heap dump file will be helpful.
