### ISSUE TITLE
Allow collection to be implicitely casted to IReadOnlyCollection<T>

### ISSUE THREAD

**Issue by Pzixel** [dotnet/roslyn#23289]
Currently we have a wonderful feature that allows to treat `Foo[]` as `IEnumerable<IFoo>`. However, using `IEnumerable<T>` provides several limits as it could be a query and user may be sad because of it.

We currently have a suitable interface `IReadOnlyCollection<T>` which is basically `IEnumerable<T>` + `Count` property.

Now we can write following:
```csharp
public IEnumerable<IFoo> GetFoos() => GetFooArray(domain);
private Foo[] GetFooArray() => { ... };
```
I'd like this being also possible:
```csharp
public IReadOnlyCollection<IFoo> GetFoos() => GetFooArray(domain);
private Foo[] GetFooArray() => { ... };
```

It makes people and tools happier because they don't whine on `Possible multiple enumeration` and it shows an intent `you can treat this collection as a collection of base type, but only if you don't write in it`. This is what `IReadOnlyCollection<T>` is, not `IEnumerable<T>`.

**Comment by ashmind** [comment]
This is currently possible though?

https://sharplab.io/#v2:C4LgTgrgdgPgAgBgARwIwG4CwAoRLUAsW2OcAzEgJZTACmYAZgIYDGtSAkgGID2PSAbwC+pCnABMSXvxCdpgkSVxjJaAOyCcSbSgocASrSYATAPJQANgE8AwjwsXaLYJR5QAPNz4A+JAHFaYGkAZwAKAEokAF5fAKC+AEEwMCYrCOIASAAHMEoANyY6KT4AbQBdf0DpJJS0yJikKFoAd3LBRpbingikIXQkLR1B7XJ8ADYUAnwADh6BYZ1tJub8NQiAOjiQjY4oYKynYHSFxSEgA

**Comment by Pzixel** [comment]
I immediatly regret that I didn't check it yet another time before asking. Thank you for your time.
