### ISSUE TITLE
Provide a formatting option to control new lines between accessors in a property

### ISSUE THREAD

**Issue by EricGriffith** [dotnet/roslyn#23280]
When a property has both getters and setters that are not expression bodies, it's currently possible to format it like this using both `NewLinesForBracesInProperties` and `NewLinesForBracesInAccessors`:

```C#
public string LastName {
    get {
        return _lastName;
    }

    set {
        _lastName = value;
    }
}
```
Ideally, there should be an option like `NewLinesBetweenAccessors` that would allow the new line between the get and set accessor to be removed like this:

```C#
public string LastName {
    get {
        return _lastName;
    }
    set {
        _lastName = value;
    }
}
```

It is a common code style to not have newlines between accessors.  This style is how XSD.exe formats code.  Roslyn is following a similar style whenever accessor bodies are multi-line although the braces are on their own lines.

**Comment by sharwell** [comment]
💭 This is another case where hierarchical options would be helpful. At the top, you could have a setting "Blank line between members", and child options to override the behavior of the top-level settings for specific situations, such as accessors.

**Comment by alrz** [comment]
part of https://github.com/dotnet/roslyn/issues/18186

**Comment by dpoeschl** [comment]
Closing in favor of https://github.com/dotnet/roslyn/issues/18186, which has a note pointing back to this specific case. Thanks!
