### ISSUE TITLE
Visual Studio Installer middle mouse click on release notes creates a second instance of the application

### ISSUE THREAD

**Issue by jltjohanlindqvist** [dotnet/roslyn#23293]
**Version Used**: 
Visual Studio Installer 1.12.111.1002

**Steps to Reproduce**:
1. Open Visual Studio Installer.
2. Press the Release Notes below Visual Studio Professional 2017 using the middle mouse button instead of left mouse button.
3. Another instance of Visual Studio installer is opened that if closed will close both instances.

**Expected Behavior**:
The same behavior as if you press using left mouse button, i.e. opening the release notes in your default internet browser.

**Actual Behavior**:
Opens a second instance of the Visual Studio Installer application, which, if closed will close both the instances.

**Comment by jcouv** [comment]
Thanks for reporting this.
The best way to file this issue would be to use the "report an issue" button in the installer itself.
The Roslyn repo is dedicated to the compiler and IDE integrations (language services, analyzers, ...).

**Comment by jltjohanlindqvist** [comment]
Ah, my bad. I tried googling for the installer on github but couldn't find
it, obviously I should've checked the client itself. Will report it there.
Thanks.

**Comment by sharwell** [comment]
@jltjohanlindqvist It may be unrelated but I got a good laugh out of it anyway. 😆 Thanks for taking time to report this so it can be fixed.
