### ISSUE TITLE
Incorrect line is shown when error has been found

### ISSUE THREAD

**Issue by andrey-messi** [dotnet/roslyn#23291]
I'm not sure this bug is related to Roslyn as a compiler (more chances that it relates to a code analyzer), but I've found this bug simultaneously when I've found a bug in a compiler (see https://github.com/dotnet/roslyn/issues/23290  )

**Version Used**: vs2017 version 15.4.4

**Steps to Reproduce**:

1. Copy and paste this code in VS-editor:
`using System;
namespace Ns
{
    internal static class Program
    {
        private static void Main()
        {
            int notInitializedX;
            int Func3()
            {
                return notInitializedX;
            }
            Func3();
        }
    }
}
`

**Expected Behavior**: error message **Use of unassigned local variable 'notInitializedX'**  should be shown on a line with number 11 

**Actual Behavior**: error message **Use of unassigned local variable 'notInitializedX'**  is shown on a line with number 13.

If a function Func3 was a very big function with a lot of code then it will be very hard to find an actual line that cause to this compile error.

![default](https://user-images.githubusercontent.com/15077988/33019965-e94ba698-ce15-11e7-846e-f9150ee2dc63.png)

**Comment by HaloFour** [comment]
The error is in the correct place.  You're allowed to reference an uninitialized variable from within a local function, but you're not allowed to invoke that local function until those variables are initialized.

**Comment by andrey-messi** [comment]
@HaloFour  you are right. I just added a string
            notInitializedX = 1;
just before call to Func3(); and it then compiled.
