### ISSUE TITLE
Do discussions, feature requests, etc still have to go on Codeplex?

### ISSUE THREAD

**Issue by SirCmpwn** [dotnet/roslyn#233]
And if not, can the contributor guidelines be updated? There seems to be a lot of discussion here on GitHub and that's where I'd personally prefer to participate.

**Comment by jaredpar** [comment]
@SirCmpwn CodePlex is no longer being used.  Our home is GitHub now and all of the discussion, work, etc ... should be occurring here.  

I thought I had cleaned out all of the codeplex references in our WIKI.  Can you point me to the ones you saw so I can remove them?

**Comment by SirCmpwn** [comment]
https://github.com/dotnet/roslyn#contribute

I just looked under the "Contribute!" heading on the readme hoping to find information on contributing :smile:

**Comment by jaredpar** [comment]
@SirCmpwn thanks, I will get that updated here in the next hour or so.

**Comment by SirCmpwn** [comment]
Many thanks.

**Comment by jaredpar** [comment]
Sorry, got trapped in a meeting.  Will take care of this today at some point.

**Comment by SirCmpwn** [comment]
Thanks @jaredpar!
