### ISSUE TITLE
Creating field from ctor param should be offered higher than creating property

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#23308]
I'd like to be able to <kbd>Ctrl</kbd>+<kbd>.</kbd>, <kbd>Enter</kbd> to create and initialize fields and only have to use arrow keys for creating public properties:

![image](https://user-images.githubusercontent.com/8040367/33038932-4bc720a2-ce04-11e7-9b4b-cb0c37118966.png)

**Comment by CyrusNajmabadi** [comment]
This is fundamentally a personal preference.  Some people use fields a lot.  Some people use properties.  I did an analysis and found that properties win out.

Now, one thing we should do is have the code action respect hte current format in your file.  i.e. if the previous parameter was assigned to a field, then the next parameter should offer 'fields' over properties.  I thought i implemented it htat way, but i guess i didn't get around to that tweak.

**Comment by jnm2** [comment]
Public is more common than private? If statistics back that up, I guess I'll believe it. :D I'm used to using the most restrictive visibility by default and would expect that to be subtly encouraged as a good programming practice.

**Comment by CyrusNajmabadi** [comment]
Sure.  As i mentioned, i think it's fine if this feature were updated to:

1. respect the code around it when working on multiple parameters.
2. prioritize the last thing the user did when invoked on a new constructor.

i.e. if you just had a type and did "generate field from parameter" and you then go to a new type, then we should prioritize 'generate field' above 'generate property'.

Note: PRs welcome :)  Be the change you want to see in the world :D

**Comment by CyrusNajmabadi** [comment]
On the topic of PRs: i'm happy to help walk you through things here if you haven't make code changes to roslyn before.

**Comment by jnm2** [comment]
Right now I'm trying to figure out whether or not my muscle memory would appreciate the order switching the way you're planning...

> On the topic of PRs: i'm happy to help walk you through things here if you haven't make code changes to roslyn before.

Heard, also much appreciated. I have some fires to put out at NUnit for a while but a roslyn contribution is something I'd like to do eventually.

**Comment by CyrusNajmabadi** [comment]
> Right now I'm trying to figure out whether or not my muscle memory would appreciate the order switching the way you're planning...

We have a few places where we do this already, and generally things just work amazingly and ones brain doesn't even realize it's happening.  Life just works properly.

For example, completion *heavily* uses MRU to weight things, and will often be picking different items based on what you've recently typed.  this allows you to type less, while still getting the "right" results.  Of course, if you actually wanted to type the non-most-recent-item, it can be a problem.  But the theory is that the majority of the time people are reusing more than they're not reusing.

**Comment by CyrusNajmabadi** [comment]
> but a roslyn contribution is something I'd like to do eventually.

Sounds good.  UNfortunately, getting setup the first time is usually the hardest.  But once up and running, making changes, testing them, and submitting PRs can be done really efficiently :)
