### ISSUE TITLE
Quick action to convert concatenation to interpolation

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#23305]
(Following the pattern of reporting my most frequent ReSharper quick actions with the goal of being able to use vanilla VS one day.)

If I <kbd>Ctrl</kbd>+<kbd>.</kbd> on this expression:

```cs
recipient.Name + " (" + recipient.Address + ")"
```

I would like to have the quick action 'Convert concatenation to interpolation' which replaces with this expression:

```cs
$"{recipient.Name} ({recipient.Address})"
```

**Comment by CyrusNajmabadi** [comment]
Doesn't that feature already exist?

![image](https://user-images.githubusercontent.com/4564579/33040596-65f59724-cdf0-11e7-8b49-90e81a04b004.png)

**Comment by CyrusNajmabadi** [comment]
BTW: please keep filing these. 

1. We want to know what you feel like you're missing.
2. Sometimes we have the feature, but it's not as discoverable or as intuitive as you'd like.  

Knowing about these issues def helps us improve the experience.

Also paging @kuhlenh

**Comment by jnm2** [comment]
Okay, I will. Maybe there's also a reason I keep removing and readding the 'add null check' parameter quick action from my list of todo requests. As far as foggy memory serves, it's there maybe 25% of the time that I expect it to be.

I finally found it. I'm used to sitting on the `+` operator to do it. I didn't realize it would make a difference to start from a text literal. Also, this is weird. Why should I have to have a text literal to convert concatenation to interpolation? Sometimes I have char literals in existing code. Sometimes I just want $"{to}{do}{this}" for whatever reason, like consistency with the surrounding code.

**Comment by CyrusNajmabadi** [comment]
> I finally found it. I'm used to sitting on the + operator to do it.

Great suggestion.  We should do that. 

> Also, this is weird. Why should I have to have a text literal to convert concatenation to interpolation?

I imagine this was partly done for efficiency.  If you have a text-literal, the analyzer has a known place to start from and can avoid having to analyze *the world*.

Also, i think it's far more likely and common for people to want to convert expressions with literal text into interpolations.  i.e. they'll have:

```c#
var v = somethingThatReturnsString() + "-" + name + "-" + date;
```

versus making a string with concatenations and no literals.  i.e.:

```c#
var v = x + y + z;
```

Honestly, in this case, i don't think ti's necessarily valuable to actually offer to convert that to:

```c#
var v = $"{x}{y}{z}";
```

This seems more cluttered and less easy to understand than the idiomatic + form.

**Comment by jnm2** [comment]
> This seems more cluttered and less easy to understand than the idiomatic + form.

Like I said, it might be one of a series of lines of code with an interpolated string in that position. But if it means analyzing the world for `+` operators where one operand ends up with the expression type of `string`, and that's infeasible to make performant, I don't think I'll miss it. Someone can always file an issue later.

**Comment by jnm2** [comment]
I think this is actually fixed/working as I expected.
