### ISSUE TITLE
Nullable Reference Types Preview won't install

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#23301]
@rolandh commented on [Sun Nov 19 2017](https://github.com/dotnet/csharplang/issues/1120)

I get the following stack trace when trying to install the nullable reference types preview on Windows 10 x64 with VS 2017 Enteroprise installed

https://github.com/dotnet/csharplang/wiki/Nullable-Reference-Types-Preview#installation-instructions

> C:\Temp\New folder (5)>install.bat
> Using VS Instance 960d5728 at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise"
> Installing all Roslyn VSIXes
>         Installing vsix\Roslyn.Compilers.Extension.vsix
> "C:\Temp\New folder (5)\tools\vsixexpinstaller\VsixExpInstaller.exe" /rootSuffix: /vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise" "C:\Temp\New folder (5)\vsix\Roslyn.Compilers.Extension.vsix"
>   Running as Admin.
> 
> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=15.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=15.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.Threading.dll' or one of its dependencies. The system cannot find the file specified.
>    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
>    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
>    at VsixExpInstaller.Program.<>c__DisplayClass16_0.<Main>b__0(Object sender, ResolveEventArgs eventArgs)
>    at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
>    --- End of inner exception stack trace ---
>    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
>    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
>    at VsixExpInstaller.Program.<>c__DisplayClass16_0.<Main>b__0(Object sender, ResolveEventArgs eventArgs)
>    at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
>    --- End of inner exception stack trace ---
>    at VsixExpInstaller.Program.<>c__DisplayClass16_2.<Main>g__RunProgram1()
>    at VsixExpInstaller.Program.Main(String[] args)
> Command failed to execute: "C:\Temp\New folder (5)\tools\vsixexpinstaller\VsixExpInstaller.exe" /rootSuffix: /vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise" "C:\Temp\New folder (5)\vsix\Roslyn.Compilers.Extension.vsix"
> System.Management.Automation.RuntimeException: Command failed to execute: "C:\Temp\New folder (5)\tools\vsixexpinstaller\VsixExpInstaller.exe" /rootSuffix: /vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise" "C:\Temp\New folder (5)\vsix\Roslyn.Compilers.Extension.vsix"
> at Exec-CommandCore, C:\Temp\New folder (5)\tools\utils.ps1: line 39
> at Exec-Console, C:\Temp\New folder (5)\tools\utils.ps1: line 71
> at Deploy-VsixViaTool, C:\Temp\New folder (5)\tools\install.ps1: line 29
> at <ScriptBlock>, C:\Temp\New folder (5)\tools\install.ps1: line 41

---

@jcouv commented on [Sun Nov 19 2017](https://github.com/dotnet/csharplang/issues/1120#issuecomment-345617381)

Tagging @cston 

---

@Joe4evr commented on [Mon Nov 20 2017](https://github.com/dotnet/csharplang/issues/1120#issuecomment-345645024)

I've had the same problem. The workaround I've found was copying the MS.VS.Threading DLL from the 15.5 preview installation into the main installation.

**Comment by yaakov-h** [comment]
I had this same issue on a machine with VS2017 15.4.4 **and** VS2017 15.5 Preview installed... which according to the release notes, is not yet supported.

It installs fine into a VM that only has VS2017 15.5 Preview installed.

**Comment by rolandh** [comment]
Copying Microsoft.VisualStudio.Threading.dll version 15.5.11.35176  into tools\vsixexpinstaller fixes the crash.

**Comment by jcouv** [comment]
All known install issues have been fixed in latest preview (published today at https://github.com/dotnet/csharplang/wiki/Nullable-Reference-Types-Preview).
I'll go ahead and close this issue. Feel free to re-open if that didn't resolve the problem. Thanks
