### ISSUE TITLE
Proposal: multiple assignments per using statement

### ISSUE THREAD

**Issue by Arithmomaniac** [dotnet/roslyn#2331]
### Motivating Example

To use `SqlCommand` as an example, I often have code that ends up looking like the following:

	using (var connection = new SqlConnection(connectionString))
	{
		using (var command = new SqlCommand(commandText, connection))
		{
			DoSomething(command);
		}
	}

To cut down on the code clutter, I sometimes do this instead:

	using (var connection = new SqlConnection(connectionString))
	using (var command = new SqlCommand(commandText, connection))
	{
		DoSomething(command);
	}

But like any multi-line unbracketed scope, this is prone to breakage.

### Proposal

- Multiple assignments can be made inside of a `using` block. 
- Each assignment would have to follow the current syntax, and each one would have to be separated by a semicolon.
- This is compiled into a set of nested `using` blocks, with the left-most assignment being of outermost scope.

### Example Usage
This would be equivalent to the motivating example:

    using (var connection = new SqlConnection(connectionString); 
      var command = new SqlCommand(commandText, connection))
	{
		DoSomething(command);
	}

**Comment by svick** [comment]
How exactly is it prone to breakage? If you're talking about something like:

```c#
using (var connection = new SqlConnection(connectionString))
    Some.Statement();
using (var command = new SqlCommand(commandText, connection))
{
    DoSomething(command);
}
```

Then:

1. I think that's very unlikely to happen by mistake, unlike a similar case with unbracketed one-line `if`/`else`/`for`/`using`/….
2. It won't compile, as long as you use `connection` in the second `using` or inside the brackets.

**Comment by Arithmomaniac** [comment]
@svick I'd consider a failure to compile as a break. Not an insidious one, but I'd rather have a syntax that prevents this from happening entirely.

**Comment by svick** [comment]
@Arithmomaniac I don't follow your reasoning. How is failure to compile wrong code a bad thing? In any case, your proposal behaves similarly, you can still write:

```c#
using (var connection = new SqlConnection(connectionString);
  Some.Statement();
  var command = new SqlCommand(commandText, connection))
{
    DoSomething(command);
}
```

So it doesn't "prevent it from happening", it just fails to compile (as long as `Some.Statement()` doesn't return `IDisposable`).

**Comment by Arithmomaniac** [comment]
@svick That's a fair point. But the error would be more directly related to the problem (namely, that using statements can't go there). Again, not solving a big problem, but just streamlining a little one.
I also think bracketless using statements are still abusive notation, but it's easy to disagree with that.

**Comment by GSPP** [comment]
The existing pattern of multiple usings without braces properly solves this issue. All syntax formatting tools support it. It looks like. This proposal does not carry its weight. In fact I consider the new syntax to be worse.

**Comment by h82258652** [comment]
How about this?
```
using(var connection = new SqlConnection(connectionString), var command = new SqlCommand(commandText,connection))
{
// TODO
}
```

use "," to split each using.
all statements must return a disposeable object.
and second statement can use first statement variable, third can use second...

**Comment by gafter** [comment]
The benefit of this proposal seems close to zero, plus or minus epsilon.
