### ISSUE TITLE
C# compiler allows unsafe conversions from method groups to delegates with mismatching `in` modifier

### ISSUE THREAD

**Issue by VladimirReshetnikov** [dotnet/roslyn#23319]
**Version Used**: 
Version 15.5.0 Preview 4.0
VisualStudio.15.Preview/15.5.0-pre.4.0+27110.0

Visual C# 2017   00369-60000-00001-AA127
Microsoft Visual C# 2017

C# 7.2

**Steps to Reproduce**:

Compile and run:

```
using System;

class Program
{
    static void F(in DateTime x)
    {
        Console.WriteLine(x);
    }

    static void Main()
    {
        Action<DateTime> a = F;
        a(DateTime.MaxValue);
    }
}
```

**Expected Behavior**:
A compile-time error.

**Actual Behavior**:
The program compiles successfully, but fails at runtime:
> Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Program.F(DateTime& x) in Program.cs:line 7

**Comment by jcouv** [comment]
Tagging @VSadov

**Comment by VSadov** [comment]
Good catch!! 
Will have to fix.
