### ISSUE TITLE
Refactoring: Convert lambda to local function

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#23310]
```cs
M(x => x);

```
->
```cs
int LocalFunction(int x) => x;

M(LocalFunction);
```
Probably best to wait for https://github.com/dotnet/roslyn/pull/6642 to land, otherwise this causes to generate suboptimal code.

**Comment by CyrusNajmabadi** [comment]
You can already do this in two steps:

1. Select the lambda and say "introduce local variable".  When done, you will be on the name of hte local variable.
2. Bring up the lightbulb and say "Use local function."

![image](https://user-images.githubusercontent.com/4564579/33043408-39c7cdfc-cdfa-11e7-8fcd-50633cce75e3.png)

![image](https://user-images.githubusercontent.com/4564579/33043419-4419f672-cdfa-11e7-99cb-b3c693f3b0f8.png)

I don't know if we need a particular refactoring to take this to one step.

**Comment by alrz** [comment]
The painful part is selecting the whole lambda which can get long. Would be nice if we suggest "introduce local variable" for the expression node that we're immediately touching (selection length is zero), so simply running on `[||]=>` could have the same effect.

**Comment by CyrusNajmabadi** [comment]
Sure.  I would be ok with that change.  note: if you did that, i think that refactoring should have low priority.

**Comment by CyrusNajmabadi** [comment]
I think this is the function you'd have to update:

https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.State.cs#L186-L190

**Comment by alrz** [comment]
@sharwell 

#23341 is merged in so it should be easier now to do this in two steps as described in https://github.com/dotnet/roslyn/issues/23310#issuecomment-345844440. Unless you want it to be a separate feature feel free to close. thanks.

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler Are delegates created from a method group conversion from a local function cached? The situation doesn't seem to suffer from the issues that stalled #6642, and local functions are new enough that it could have been incorporated into the design.

**Comment by CyrusNajmabadi** [comment]
Closing as resolved.  You can introduce the local with your caret on `=>`.  and once introduced, it's easy to convert to a local function.
