### ISSUE TITLE
Null check can be simplified produces code with compilation error

### ISSUE THREAD

**Issue by smitpatel** [dotnet/roslyn#23320]
```C#
using System;
using System.Collections.Generic;
using System.Linq;

namespace NullCheck
{
    class Program
    {
        static void Main(string[] args)
        {
            var blog = GetBlog();

            var queryable = new List<int>().AsQueryable();
            var query = from i in queryable
                        where (blog == null ? null : blog.Id) == "1"
                        select i;

            Console.WriteLine("Hello World!");
        }

        static Blog GetBlog()
        {
            return new Blog();
        }
    }

    public class Blog
    {
        public string Id { get; set; }
    }
}
```

In above code, VS suggests that null check can be simplified.
![image](https://user-images.githubusercontent.com/1528107/33049724-3d68d098-ce16-11e7-9225-0ce67f7a4252.png)

But after applying the code fix using VS
![image](https://user-images.githubusercontent.com/1528107/33049752-56c0c302-ce16-11e7-924d-778ca015b8f3.png)

**Actual Behavior**:
Error message:
1>Program.cs(15,32,15,40): error CS8072: An expression tree lambda may not contain a null propagating operator.

**Expected Behavior**:
VS should not suggest code fix to simplify null check when inside expression tree lambda code.

**Version Used**: 
Visual Studio 15.5.0 Preview 5.0 [27119.0.d15rel]

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me. We don't offer this here anymore.
