### ISSUE TITLE
Multiple line cursor inserting spaces for only last selected line when pasting items

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23328]
When you select multiple lines and paste some text without a space, the laste line you selected autoformats with an extra space character while the other lines are ignored. This is especially annoying if you try any type something after pasting because the first character in the non-autoformatted lines is replaced by default. I expect either all the lines get auto formatted or none of the lines get auto formatted. The work around is to insert text that does not autoformat or undo the autoformat after pasting something.

Reproduction:

1. Create a class in c# with multple getters and setters. Example:

    ```csharp
    public class Basket
    {
        public int orangeCount { get; set; }
        public int mangoCount { get; set; }
        public int pearCount { get; set; }
    }
    ```

2. Find some text to copy, I will use `[JsonIgnore]` to hide the field from appearing in a rest api for an mvc core web app

3. Press <kbd>Alt</kbd>+<kbd>Shift</kbd> and put the cursor in front of the public int lines

4. Paste the text you coppied earlier, depending on how you did your <kbd>Alt</kbd>+<kbd>Shift</kbd> you can get one of the following

    Selected from top to bottom:

    ```csharp
    public class Basket
    {
        [JsonIgnore]public int orangeCount { get; set; }
        [JsonIgnore]public int mangoCount { get; set; }
        [JsonIgnore] public int pearCount { get; set; } //notice the extra space after [JsonIgnore]
    }
    ```

    Selected from bottom to top:

    ```csharp
    public class Basket
    {
        [JsonIgnore] public int orangeCount { get; set; } //notice the extra space after [JsonIgnore]
        [JsonIgnore]public int mangoCount { get; set; }
        [JsonIgnore]public int pearCount { get; set; }
    }
    ```

5. Try typing something after pasting, I tried to type a space character.

    ```csharp
    public class Basket
    {
        [JsonIgnore] ublic int orangeCount { get; set; } //notice the p gets removed
        [JsonIgnore] ublic int mangoCount { get; set; } //notice the p gets removed
        [JsonIgnore] public int pearCount { get; set; }
    }
    ```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/78177/multiple-line-cursor-inserting-spaces-for-only-las.html
VSTS ticketId: 462059_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Multiline cursors are the editor, not roslyn.  Issues here should be filed at developercommunity.
