### ISSUE TITLE
Would like code fix that fixes conditional expression in an interpolation

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#23323]
See https://github.com/dotnet/roslyn/issues/12214#issuecomment-345451129

When an interpolation in an interpolated string contains a conditional expression, the colon is considered to be a delimiter that begins the format string. Thus the conditional expression will be a syntax error. We give a nice syntax error that is specific to this situation. It would be nice to have a code fixer that implements the suggested fix of parenthesizing the conditional expression.

**Comment by CyrusNajmabadi** [comment]
Ping: @sharwell

**Comment by sharwell** [comment]
This is a great idea 👍

**Comment by MaStr11** [comment]
Can be closed as #23587 is being merged.

**Comment by jinujoseph** [comment]
Thanks @MaStr11
