### ISSUE TITLE
Cannot declare extension method with `in this` parameter whose type is a type parameter with `struct` constraint

### ISSUE THREAD

**Issue by VladimirReshetnikov** [dotnet/roslyn#23333]
**Version Used**: 

Version 15.5.0 Preview 4.0
VisualStudio.15.Preview/15.5.0-pre.4.0+27110.0

Visual C# 2017 00369-60000-00001-AA127
Microsoft Visual C# 2017

C# 7.2

**Steps to Reproduce**:

Try to compile:

```
using System;

static class C
{
    public static bool IsEqual<T>(in this T x, in T y) where T : struct, IComparable<T>
    {
        return x.CompareTo(y) == 0;
    }
}
```
**Actual Behavior**:
error CS8338: The first parameter of an 'in' extension method 'IsEqual' must be a value type.

**Expected Behavior**:
I am not sure this error is by design. Although the type parameter `T` is not a value type _per se_, it has `struct` constraint, so it must be a value type at runtime, and this scenario seems useful.

**Comment by VSadov** [comment]
Unlike with actual value types, any use of  generic `x` inside the method will have to be through interface members.  
Interface members are all formally mutating, so every use will have to make a copy.

Allowing generic  `in this T` can only lead user on a wrong path - you would do it to save a copy at the call site, but indirectly introduce multiple copies inside the method. 

`in this T` is always worse than ordinary `this T` when T is a generic type parameter.

Therefore this is disallowed - just use ordinary `this T`.

**Comment by benaadams** [comment]
> Unlike with actual value types, any use of generic x inside the method will have to be through interface members.

If this is invalid
```csharp
public static bool IsEqual<T>(in this T x, in T y) where T : struct, IComparable<T>
{
    return x.CompareTo(y) == 0;
}
```
Why would this be ok?
```csharp
public static bool IsEqual<T>(in T x, in T y) where T : struct, IComparable<T>
{
    return x.CompareTo(y) == 0;
}
```

**Comment by VladimirReshetnikov** [comment]
@VSadov, thanks, I agree with your reasoning. It might be a good idea to have `where T : readonly struct, IComparable<T>` constraints one day.
