### ISSUE TITLE
Generate a linear serializer for compilation units

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#23331]
Currently the green tree is serialized using `ObjectWriter` and operates on `IObjectWritable`.

https://github.com/dotnet/roslyn/blob/93819e3d61e077f3498143456a2818589c7bcca4/src/Compilers/Core/Portable/Syntax/GreenNode.cs#L17

Performance would be improved if a linear (not recursive descent) serializer were generated based on a closed-world understanding of the tree structure.

* Many virtual calls could be eliminated
* Deep trees could be serialized without a trampoline to a new thread

This is nearly impossible to maintain by hand, but could be generated as part of generating code from the XML descriptor for trees.

Internal links to known crashes caused by memory pressure in the recursive descent serializer:

:link: [DevDiv 481118](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/481118)
:link: [DevDiv 486363](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/486363)
:link: [DevDiv 497431](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/497431)
:link: [DevDiv 499584](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/499584)
:link: [DevDiv 503742](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/503742)

Links to feedback tickets resulting from the recursive descent serializer:

:link: [DevDiv 584145](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/584145)
:link: [DevDiv 854054](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/854054)
:link: [DevDiv 934759](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/934759)
:link: [DevDiv 947401](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/947401)

**Comment by genlu** [comment]
@sharwell Do you have a benchmark I can run as a baseline?

**Comment by RikkiGibson** [comment]
Perhaps we could prioritize this issue as part of a "technical debt" milestone in between releases.

**Comment by CyrusNajmabadi** [comment]
We no longer serialize trees.  So closing this out as this isn't in a path that needs fixing.
