### ISSUE TITLE
Unnecessary defensive copy of an `in` parameter is created, whose type is nullable readonly struct

### ISSUE THREAD

**Issue by VladimirReshetnikov** [dotnet/roslyn#23338]
**Version Used**: 

Version 15.5.0 Preview 4.0
VisualStudio.15.Preview/15.5.0-pre.4.0+27110.0

Visual C# 2017 00369-60000-00001-AA127
Microsoft Visual C# 2017

C# 7.2

**Steps to Reproduce**:

Compile and inspect IL:
```
using System;

readonly struct S
{
    readonly decimal d;

    public S(decimal d)
    {
        this.d = d;
    }
}

class P
{
    static void Foo(in S? x)
    {
        Console.WriteLine(x.GetValueOrDefault());
    }
    
    static void Main()
    {
        S? y = new S(5m);
        Foo(y);
    }
}
```
**Actual Behavior**:
The `in` parameter `x` in the method  `Foo` is copied to a compiler-generated local before `GetValueOrDefault()` is invoked.

**Expected Behavior**:
This copy is unnecessary and should be elided. No method or property of a nullable value type can mutate it if the underlying type is a readonly struct.

**Comment by VSadov** [comment]
Nullable and many other simple structs are becoming `readonly`.
See for example https://github.com/dotnet/corefx/pull/24997

We could treat it as `readonly` regardless of decorations. We do in several places already.

**Comment by VladimirReshetnikov** [comment]
Making `System.Nullable<T>` a readonly struct would be a breaking change. Consider the following program:

```
using System;

struct S
{
    int x;

    public override string ToString()
    {
        x = 5;
        return "";
    }

    static void Main()
    {
        S? s = new S();
        Console.WriteLine(s.Value.x); // 0
        s.ToString();
        Console.WriteLine(s.Value.x); // 5
    }
}
```

If `System.Nullable<T>` were a readonly struct, both lines would print `0`.

The constructed type `System.Nullable<S>` can only be optimized as a readonly struct if the value type `S` is itself readonly.

**Comment by VSadov** [comment]
readonly `T` does not really help.  `ToString` can, in theory, just do `this = null`

We can special-case the special methods like `GetValueOrDefault` though. 
They are not mutating and only make sense if they are nonmutating.

**Comment by VladimirReshetnikov** [comment]
@VSadov Sorry, I did not quite understand your comment. I get an error when I try to assign to `this` in an instance method of a `readonly struct`:
```
readonly struct S {
    readonly decimal d;
    S(decimal d) => this.d = d;
    public void Foo() => this = new S(5m); // error CS1604: Cannot assign to 'this' because it is read-only
}
```
Tested on master branch at https://sharplab.io

**Comment by VSadov** [comment]
@VladimirReshetnikov - it was about the outer `Nullable<T>.ToString()` - the containing struct is not readonly and can allow mutations even if inner `value` has readonly type.

**Comment by VladimirReshetnikov** [comment]
But we can assume the implementation of `Nullable<T>.ToString()` is known and is not going to change, right?

**Comment by VSadov** [comment]
or we can assume that implementation of `Nullable<T>.ToString()` is not known and can change at any time. 
For once I do not know what Mono or micro-framework or any other implementation do. 
If I were to implement `ToString`, I would easily make it incompatible. What it does is not at all intuitive or obvious.

In reality only `HasValue` and `Value` are documented in ECMA. It makes sense to specialcase `GetValueOrDefault` since we use it a lot and already rely on specific semantics. We should probably document it as such when there is an opportunity. 

The rest of methods are just methods. There is no need to codify their implementation.
