### ISSUE TITLE
Duplicate completions offered while working on compiler tests

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#23354]
For instance, try typing `ConvertedType` again in ` TupleImplicitNullableAndCustomConversionsWithTypelessTuple`.

![image](https://user-images.githubusercontent.com/12466233/33107872-173f1ae8-ceee-11e7-86d2-4773dea58c7d.png)

![image](https://user-images.githubusercontent.com/12466233/33107878-201e0b2e-ceee-11e7-855f-7c934687fb2c.png)

Note: not all completions appear to be duplicated (`GetHashCode` is there only once):
![image](https://user-images.githubusercontent.com/12466233/33107913-583b5836-ceee-11e7-90d3-c12a02b04db7.png)

**Comment by CyrusNajmabadi** [comment]
That's terrifying. Most of all because there is literally code in the completion list to merge duplicates: 

https://github.com/dotnet/roslyn/blob/9c22296f406d8a970b2d422c1992c22fc09d439a/src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs#L369-L378

**Comment by jcouv** [comment]
@jinujoseph Could you help triage/assign? This regression is still occurring in `Version 15.6.0 Preview 1.0 [27205.0.d15.6]`. Thanks

**Comment by jcouv** [comment]
Never mind, I found the culprit. The duplicate entries came from the Pythia extension.
Closing
