### ISSUE TITLE
Optimize implicit casts from string literals to ReadOnlySpan<char>

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#23358]
If possible, we should just point to the underlying data of the string.

Ideally there is a helper that takes a string token or something like that - to avoid directly dealing with pointers, which us formally unsafe.

realted to: https://github.com/dotnet/corefx/issues/25413

**Comment by jcouv** [comment]
@VSadov fixed with #24621 for 15.7. Closing

**Comment by VSadov** [comment]
It is fixed to the degree that is possible. It is an optional optimization after all.

1+ byte elements will require new APIs. That is not going to happen soon and for that there is a separate bug.
