### ISSUE TITLE
Incorrect suggestion for object initialization simplification

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#23368]
Consider the following code:

``` c#
interface IExample {
    string Name { get; set; }
}

class C : IExample {
    string IExample.Name { get; set; }
}

void Repro() {
  IExample e = new C();
  e.Name = "jared"
}
```

Given this code the IDE will add the suggestion IDE0017, object initialization can be simplified, on the `IExample e` line. The suggested fix is the following:

``` c#
IExample e = new C {
  Name = "jared"
};
```

This results in code that won't compile. The name `Name` is only legal through the type `IExample` but the fix causes `Name` to be evaluated in the context of `C` instead.

**Comment by CyrusNajmabadi** [comment]
@sharwell Good option for community contrib.
