### ISSUE TITLE
Handle user-defined operators in 'use pattern-matching' analyzer

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#23374]
From https://github.com/dotnet/roslyn/pull/20246#discussion_r152680679

> We may be able to improve the experience by allowing user-defined operators, but ensuring a single Fix All operation only corrects operations that use the same operator. For example:
>
> - If all uses of == null and != null for a variable use the default operator, a Fix All on the variable will fix all cases where no user-defined operators are involved
> - If one or more uses of == or != involve a user-defined operator for a variable with the declared type T, then a Fix All on that variable will fix all instances involving variables with declared type T, whether or not they use user-defined operators. Alternately, this scenario could fix all instances involving variables with declared type T which use one or more user-defined operators.
> 
> The equivalence ID of the code fix can be used to "bucket" fixes according to the above conditions.

/cc @sharwell

**Comment by CyrusNajmabadi** [comment]
Closingn out as speculative.
