### ISSUE TITLE
CS1628 error text should also mention local functions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23386]
CS1628 error text does not mention local functions

Example:

```
    public class fkp
    {
        static void m(ref int x)
        {
            void localfunction()
            {
                x = 1;
            }
            {
                localfunction();
            }
        }
    }
}
```

Gives error: CS1628	Cannot use ref or out parameter 'x' inside an anonymous method, lambda expression, or query expression

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/152736/cs1628-error-text-should-also-mention-local-functi.html
VSTS ticketId: 527092_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jcouv** [comment]
Verified [fix](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDk4BstWFiAJQkiQDsBjCAFQE8AHFAGhhCmRiYBMQBqAHwACABgAEggIwBuALAAoQQGZxAJlEBhUQG95ovXqWrRYANb1d+nXP03xEgGziALKIC2ACiRhRASzIxRAA8ASgtbbTDw/UEXLAB7CigsMDhKGB84sndQ6yibKzy8wNEAXlFpUQB6StEIBAQ4hA0AZQcVAA4QDSgyMjiAuGQIUS8mUTi4TnGmv1F6KAQoVwgYOtEAckD13zJkHy5hntEezNpXCeQ3FYALOK4x3FdgLihawPokZD3MsYBHODqtDeHxQ3zIY0aoniiSwxlSFHSmUieQAvsiogVCuFoUkUmkMllgrJcli0STbGSbGSUUA)
