### ISSUE TITLE
IDE editor inserts extra '#endif' when applying IDE0018 "Variable declaration can be inlined"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23387]
The following C# class has an unusual `#if` statement which causes the suggested replacement IDE0018 to fail when applied:

```csharp
    class TestClass
    {
        void foo(out int c) => c = 0;
    
        void bar()
        {
            if (true)
            {
    #if !XXX
            }
    #endif
            int c;
            foo(out c);
        }
    };
```

When applying the suggestion "Variable declaration can be inlined," the editor incorrectly replaces the last two lines with an extra `#endif` statement which (obviously) prevents the file from compiling:

Here is the incorrect result after the "Quick actions and refactorings" operation:

```csharp
    class TestClass
    {
        void foo(out int c) => c = 0;
    
        void bar()
        {
            if (true)
            {
    #if !XXX
            }

#endif
#endif
		foo(out int c);
	}
    };
```

Notice the duplicated `#endif` line.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/154208/ide-editor-inserts-extra-endif-when-applying-ide00.html
VSTS ticketId: 527946_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
related https://github.com/dotnet/roslyn/issues/22881

**Comment by CyrusNajmabadi** [comment]
This now produces the expected result:

![image](https://user-images.githubusercontent.com/4564579/198752594-98540a65-4b44-484b-accb-3705384f1550.png)
