### ISSUE TITLE
tuple Intellisense [very trivial]

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23388]
```csharp
int x;
int y;
(x, y) = MyTupleFunc();
MyOtherFunc(x, y);
```

With Intellisense, if you select `x` or `y` in either their declaration or the `MyOtherFunc()` call, then all instances get highlighted including in the tuple -- as desired.

If you select `x` or `y` inside the tuple, the other instances don't highlight.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/155654/tuple-intellisense-very-trivial.html
VSTS ticketId: 529587_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
cc / @jcouv

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/issues/20115 (we need a dual view of tuples for FindUsages and GoToDefinition).

**Comment by CyrusNajmabadi** [comment]
Closing out, everything is highlighted properly:

![image](https://user-images.githubusercontent.com/4564579/198752693-b25c83b0-9aad-4b7b-b9b6-2f96054f23de.png)
