### ISSUE TITLE
Code metrics should be calculated for portable class libraries.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#23396]
**Version Used**:

Visual Studio Community 2017 v15.4.4

**Steps to Reproduce**:

1. Create a solution consisting of one Windows console application project and one portable class library targeting .NET Standard 2.0 (the library can be in VB or C# - it doesn't matter) 

2. Go click the menu item: Analyze > Calculate Code Metrics > For Solution.

**Expected Behavior**:

The Code Metrics Results window should show metrics for all projects including the portable class libraries.

**Actual Behavior**:

Metrics are shown for non-portable projects (e.g the windows console application project)...but for all portable class library projects you get the following message:

```
One or more projects were skipped. Code metrics are available only for C#, Visual Basic, and C++/CLI projects that are not Web Site projects.
```

![vs_code_metrics_results](https://user-images.githubusercontent.com/20465797/33280193-57126be8-d3b2-11e7-8fba-617609bd2114.png)

(I am reporting this here as I believe the actual calculation of code metrics is done by rosyln components...I may be wrong though in which case this may need to be relocated to a more appropriate site).

**Comment by Overrided** [comment]
Same issue here.

**Comment by mavasani** [comment]
Fixed with internal [VSO PR](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/133019?_a=overview). The fix should be available in Dev16 P1.

**Comment by ericmutta** [comment]
@mavasani thanks a lot for working on this, it had been driving me nuts not knowing how big my portable code base is getting, so I really look forward to Dev16 P1 :+1:
