### ISSUE TITLE
Language version upgrade suggests using the language version 'latest'

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#23392]
**Version Used**: 15.5 Preview 4

**Steps to Reproduce**:

1. Define a ref struct
2. Use the code fix to upgrade the project

**Expected Behavior**:

1. A code fix is provided to upgrade the project to either language version '7.2' *or* to the latest language version
2. Applying the code fix adds the property `<LangVersion>7.2</LangVersion>`

**Actual Behavior**:

1. A code fix is provided to upgrade the project to language version 'latest'
2. Applying the code fix for language version 'latest' adds the property `<LangVersion>latest</LangVersion>` to the project

**Additional Details**:

The key underlying problem here is the use of the special value 'latest' in the code fix output. This value exists for backwards compatibility purposes, and should never actually be used in a project. The IDE fails to take the necessary steps to discourage users from using this value.¹

For those wondering, the key problem with the value 'latest' is it results in a project that varies in behavior depending on the current minor version of C# in use. In a multi-user team, once every few months team members are forced to either upgrade all at exactly the same time, or users on the team will start to see IDE assistance related to functionality that only a subset of the team can use successfully. On the other hand, projects specifying a language version by number see a consistent experience even across different versions of the IDE, reducing the customer risk involved with adopting new versions of the IDE.

The easiest fix is to simply remove 'default' and/or 'latest' from the set of fixes offered to the user. An alternative approach would involve offering 'default' and/or 'latest' when they are newer than the required language version, but updating the code fix to substitute the corresponding specific language version when applying the fix.

¹ The options 'default' and 'latest' remain available from the Advanced Build Settings page, and/or can be specified by manually editing the project file. This issue does not suggest changes be made to the availability or behavior of these settings, but merely intends to modify the apparent recommendation to reflect known best practices that apply to the majority user base.

**Comment by CyrusNajmabadi** [comment]
> but merely intends to modify the apparent recommendation to reflect known best practices that apply to the majority user base.

It seems weird that we need to do this.  Even if this is a 'best practice', it's just an option that a user can take if they so desire.  If we think it's 'less good' than picking an actual specific version, then we could just put it lower in the list right?

**Comment by CyrusNajmabadi** [comment]
Note: i don't really have a horse in this race.  If this option is truly felt to be universally bad, then sure, don't offer it.  However, from my own experience working on a few different projects (including small team projects), some teams are absolutely fine picking 'latest' and having that work well for them.  As an individual, i know i'm ok with this.

**Comment by jcouv** [comment]
This is not a bug (it's by design). The compiler and project files allow "default" and "latest", so I don't see why the IDE should be more restrictive.

**Comment by sharwell** [comment]
@jcouv The compiler and project files allow many things that are not directly exposed in the UI. Sometimes this is a case where we just haven't completed the work, while other times it's an effort to make the UI a "pit of success" for users. This situation falls into the latter case since users are in two groups:

* Users for whom LangVersion=latest is a reasonable choice: These users do not need the Code Fix functionality because the project was already edited by hand to set the value.
* Users for whom LangVersion=latest is *not* a reasonable choice: These users do not need the Code Fix functionality because it produces an undesirable output.

By leaving the current code fix in place, there will be a subset of users in the second category who are mistakenly led to believe they are in the first category. Removing the option serves no other purpose than to dissuade a targeted group of users from selecting an option that they should never select. It does not hinder the ability of the other side to continue using the option in the same way they did before.

**Comment by CyrusNajmabadi** [comment]
> These users do not need the Code Fix functionality because the project was already edited by hand to set the value.

Not necessarily.  They could be in that state because that's how the project was originally created.  Then, when they hit the first language feature that needs an upgrade, they have an easy way to say "yes i want that, and i always want to be on the latest so i don't have to opt into the new language feature."

**Comment by CyrusNajmabadi** [comment]
> These users do not need the Code Fix functionality because it produces an undesirable output.

Yes.  But these users are not hurt by being given the *option* here.  If we feel like this option isn't the best option, we can deprioritize it.  But i don't see the need to actually hide/remove it.

**Comment by sharwell** [comment]
> Not necessarily. They could be in that state because that's how the project was originally created. Then, when they hit the first language feature that needs an upgrade, they have an easy way to say "yes i want that, and i always want to be on the latest so i don't have to opt into the new language feature."

I am opposed to complicating the naturally-discoverable user interface with options that only apply to experimental or hypothetical scenarios, or otherwise negatively impact the scalability of the product with respect to the maintainability of large code bases. The alternative approaches for setting the language version are not excessively difficult, and most importantly, are readily understood by users advanced enough to fall into one of the edge cases where it might make sense.

> But these users are not hurt by being given the option here.

Providing the option means there is a possibility that the user will select it. Selecting this option poses a maintainability risk to team projects with no measurable benefit. In a team setting, language version upgrades need to be made at the team level and not arbitrarily.

**Comment by CyrusNajmabadi** [comment]
> I am opposed to complicating the naturally-discoverable user interface with options that only apply to experimental or hypothetical scenarios

That's not hypothetical :)  That's the default config for VS.  It's hypothetical that people would have manually moved out of that state to get things to 'latest'. 

The question, to me, is what sorts of users we have who will get these 'upgrade' notifications, and what sort of upgrade approaches are reasonable.  Right now, 'latest' seems reasonable for a set of users, as does supplying a specific version.  It's also true that 'latest' is absolutely *not* ok for some other subset of users.  However, as this is a choice that's offered, and it's all user opt-in, i don't see the problem.

**Comment by CyrusNajmabadi** [comment]
>  Selecting this option poses a maintainability risk to team projects with no measurable benefit.

I don't see why these 'team projects' mean that we can't offer the choice to people (or teams) for whom this is an acceptable option.  

It's like saying that when you choose some sort of project dependency, you must specify a nuget/go/npm version explicitly.  Yes, for some projects that's an absolute must and hte only acceptable path.  But for others, it's completely fine to have loose versioning and just taking the latest.  

If we think strict is the better default, then by all means prioritize it appropriately.  But unless 'loose' is universally bad, i don't see why it's a problem to again just offer it as a lower pri choice.  Teams that don't like this can just not pick that option.

**Comment by jcouv** [comment]
Discussed with Neal and we'd be ok to remove "default" and "latest" from options offered by the code fixer.

**Comment by CyrusNajmabadi** [comment]
Works for me.  As @sharwell has pointed out.  It's not that onerous to have to manually make the change to opt into latest.  At the very worst, a user just sees more upgrade offers as they use new language features.  In a way, that's good as it becomes clear to them that they're explicitly takign a dependency on a new language version.

**Comment by CyrusNajmabadi** [comment]
Objections withdrawn :)

**Comment by Suchiman** [comment]
@sharwell 
> The compiler and project files allow many things that are not directly exposed in the UI.

Nit: it actually is exposed in the UI :trollface: 
![Advanced Build Settings](http://csharpcorner.mindcrackerinc.netdna-cdn.com/article/c-sharp-7-2-new-features-with-visual-studio-2017/Images/image015.png)

**Comment by sharwell** [comment]
@Suchiman That's the setting described in the footnote of the original post, above.
