### ISSUE TITLE
Make CSharpCommandLineParser.ScriptRunner public

### ISSUE THREAD

**Issue by filipw** [dotnet/roslyn#23402]
**Version Used**: 
2.4.0

**Steps to Reproduce**:

1. Go to `CSharpCommandLineParser` type

**Expected Behavior**:

`CSharpCommandLineParser.ScriptRunner` is public.

**Actual Behavior**:

`CSharpCommandLineParser.ScriptRunner` is internal. Only `CSharpCommandLineParser.Default` is public.

<hr>

We'd like to use `CSharpCommandLineParser.ScriptRunner` in OmniSharp to support user-defined `.rsp` files for CSX code editing. Since the default C# parser is available, the CSX parser should be available too - especially as there is quite a behavior difference between them. At the moment the workaround is to use reflection to access `CSharpCommandLineParser.ScriptRunner`.

cc @tmat

**Comment by jinujoseph** [comment]
cc @DustinCampbell

**Comment by DustinCampbell** [comment]
also, cc @tmat

**Comment by DustinCampbell** [comment]
@tmat : Should we rename this to `Script` and make it public?

**Comment by DustinCampbell** [comment]
If there's no reason not to, I'll submit a PR.

**Comment by tmat** [comment]
@DustinCampbell Sounds good. Do you think ```Script``` is better than ```ScriptRunner```? It's not a parser for script arguments. It's a parser for csi, which runs the script.

**Comment by DustinCampbell** [comment]
I'm not sure I understand the difference. After all, it's a command-line parser. How would `CSharpCommandLineParser.Script` be representative of anything other than Roslyn's command-line script runner?

**Comment by tmat** [comment]
It's subtle - the command line arguments passed to the runner: ```/u:System.Data copy_data.csx /database Foo /out D:\Temp``` vs. just those passed to the script ```/database Foo /out D:\Temp```. No big deal. ```Script``` is fine too.

**Comment by filipw** [comment]
@tmat while we are at it, would it also be possible to pass globals object type via args/rsp too? this would offer excellent flexibility. All other compiler options seem to be there

**Comment by tmat** [comment]
@filipw That's rather unrelated feature request. Feel free to file another issue.

**Comment by DustinCampbell** [comment]
@tmat : I get the difference now, thanks! I think `Script` is probably fine though since the class is named `CSharpCommandLineParser`. I'll go ahead and submit a PR.

**Comment by filipw** [comment]
Thanks! 🎉
