### ISSUE TITLE
SyntaxFactory.Literal(double) sometimes doesn't create double literals

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#23403]
**Version Used**: Microsoft.CodeAnalysis.CSharp 2.4.0

**Steps to Reproduce**:

Use `SyntaxFactory.Literal` to create literals for the same integer with different types:

```c#
using System;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

class Program
{
    static void Main()
    {
        var literals = new[]
        {
            Literal((int)42), Literal((uint)42), Literal((long)42), Literal((ulong)42),
            Literal((float)42), Literal((double)42), Literal((decimal)42)
        };

        foreach (var literal in literals)
        {
            Console.WriteLine(literal);
        }
    }
}
```

**Expected Behavior**: Each overload of `SyntaxFactory.Literal` preserves the type of its argument.

**Actual Behavior**: The `SyntaxFactory.Literal(double)` overload creates an `int` literal; the output of the above code is:

```
42
42U
42L
42UL
42F
42
42M
```

**Comment by svick** [comment]
One possible way to fix this would be to force `SyntaxFactory.Literal(double)` to always include the suffix. I believe doing that would mean changing the code from:

https://github.com/dotnet/roslyn/blob/f449fd78b19a0871d5ed97c472824b99127db2d9/src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs#L504

to:

```c#
return Literal(ObjectDisplay.FormatLiteral(value, ObjectDisplayOptions.IncludeTypeSuffix), value);
```

**Comment by CyrusNajmabadi** [comment]
Are you sure it creates an int literal?  I imagine the 'Value' property of hte literal is actually the 'double' 42.  It's just that '42' is a totally valid representation for that double.

**Comment by svick** [comment]
@CyrusNajmabadi 

>  I imagine the 'Value' property of the literal is actually the 'double' 42.

Yes, `Value` returns the `double`.

>  It's just that '42' is a totally valid representation for that double.

In that case, isn't `42` also a valid representation for the other types? Why do those use a suffix?

Also, it might be valid reprenation for `double` in cases like `double d = 42;`, but not for `var x = 42;`.

**Comment by CyrusNajmabadi** [comment]
Ah, i see what you mean.  i suppose that's fair.   :)

**Comment by CyrusNajmabadi** [comment]
Another option (perhaps more idiomatic), would be to emit as 42.0.

**Comment by svick** [comment]
Other problematic values are those that don't have C# literals, including `double.NaN` and `double.PositiveInfinity`. I think `SyntaxFactory.Literal` should throw an exception for those values.

**Comment by CyrusNajmabadi** [comment]
> Other problematic values are those that don't have C# literals, including double.NaN and double.PositiveInfinity. I think SyntaxFactory.Literal should throw an exception for those values.

Note that that's not how syntaxfactory works.  It doesn't try to validate that you're creating correct C#.  It trusts that you are doing the right thing. For example, it will gladly allow you to make an identifier that contains the next "Foo.Bar" in it.  

The idea is to be a fast way to generate syntax, not to be a system that has to re-enforce all the rules in the language that are already handled elsewhere in the pipeline.

**Comment by svick** [comment]
@CyrusNajmabadi Interesting, I didn't realize that was the design philosophy of `SyntaxFactory`.

**Comment by CyrusNajmabadi** [comment]
Yup.  You only get safety around:

1. Kind checking (i.e. you can't create a BinaryExpression with SyntaxKind.StringLiteral)
2. Null checking (i.e. you can't pass null for nodes that are not allowed to be null)
3. Type checking (i.e. the .net type system won't let you pass a BinaryExpression where a StatementSyntax is needed)

That's effectively it.  We debated early on trying to actually enforce syntactic rules.  But it turned out to be an absolutely staggeringly large amount of work (effectively redoing all the work of the parser), so we decided to just swing hard in the other direction: no enforcement beyond what's explicitly specified above.

**Comment by MaceWindu** [comment]
For anyone having this issue, we workarounded it with code like this:
```cs
return SyntaxFactory.LiteralExpression(
                    SyntaxKind.NumericLiteralExpression,
                    SyntaxFactory.Literal(
                        ((double)value).ToString(NumberFormatInfo.InvariantInfo) + "D",
                        (double)value));
```

if you work with NaN/Infinity values (we don't) maybe it will require some extra logic.

**Comment by CyrusNajmabadi** [comment]
Closing out as working as expected.  If this is not ok, we'll need an appropriate api proposal to take through our api review process.
