### ISSUE TITLE
Link for NETCompilerPlatformSDK should not be version-specific

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#23404]
_From @jcouv on November 27, 2017 22:13_

Repro:

1. Go to: File | New Project | Extensibility | Dowload the .NET Compiler Platform SDK
2. Click on "Download the .NET Compiler Platform SDK"
3. Click on the Download button

![image](https://user-images.githubusercontent.com/12466233/33292019-a1f81800-d37c-11e7-8165-14153c4c2ce4.png)
![image](https://user-images.githubusercontent.com/12466233/33292028-a8144b0a-d37c-11e7-8513-579b4944f6d9.png)

Actual:
That download button is pointing to ...https://visualstudiogallery.msdn.microsoft.com/2ddb7240-5249-4c8c-969e-5d05823bcb89/file/166162/9/Roslyn%20SDK.vsix 
 
Expected
Instead of point to a vsix, can we point to the marketplace url..so we don’t have worry about the versions?
https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.NETCompilerPlatformSDK

Tagging @ChitraKoppolu 

_Copied from original issue: dotnet/project-system#2989_

**Comment by davkean** [comment]
tag @jmarolf

**Comment by jmarolf** [comment]
We not longer ship this breadcrumb template as of 15.5
