### ISSUE TITLE
SyntaxGenerator.WithModifiers is not adding NotOverridable modifier for VB method

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#23410]
**Version Used**: 
MS.CA 2.6.0-beta3

**Steps to Reproduce**:

1. Enlist in https://github.com/dotnet/roslyn-analyzers repo
2. Run unit test `Microsoft.CodeAnalysis.Analyzers.UnitTests.FixAnalyzers.VisualBasic_VerifyFix_NonSealedType` and verify the code fix failure.

**Expected Behavior**:
Generated method has `NotOverridable` modifier

**Actual Behavior**:
SyntaxGenerator.WithModifiers is not adding `NotOverridable` for VB, when C# case works fine for the same code (`sealed` is added).

**Comment by Youssef1313** [comment]
@mavasani Is this still an issue?
