### ISSUE TITLE
Allocations caused by SQLitePCL.raw database loading

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#23424]
**Version Used**: 
2.6.0-vs-for-mac-62303-01

**Steps to Reproduce**:

1. Use the defautl SQLitePersistentStorage
2. Wait for it to load
3. Observe that 64MB are coming in from SQLitePCL.util.to_utf8

https://gist.github.com/Therzok/9ca7f361caaf0308640fa7b03da3ec8b

**Expected Behavior**:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/SQLite/Interop/SqlConnection.cs,210

Should be using cached values that can be passed to native. `"main"` and `DataColumnName` are both constants. `DataTableName` can also be cached per accessor kind

http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/SQLite/SQLitePersistentStorage.Accessor.cs,5203990dce13d1f4,references

Probably a lower level layer should be used for better performance. Passing in strings will cause SQLitePCL.raw to create byte arrays from the strings every time.

https://github.com/ericsink/SQLitePCL.raw/blob/master/src/cs/util.cs#L125
https://github.com/ericsink/SQLitePCL.raw/blob/d86a5b5311ff4cdbba54cda49c23a776bd888663/src/cs/sqlite3_pinvoke.cs#L282

**Actual Behavior**:
These strings are marshaled to byte arrays on every blob read.

**Comment by sharwell** [comment]
:memo: This is a limitation in the API of SQLitePCL.raw.

**Comment by Therzok** [comment]
```
Memory traffic between Snapshot #1 and Snapshot #2

System.Byte[] allocated 195414900 B in 9770745 objects on stacktrace:

SQLitePCL.util.to_utf8(String sourceText)
SQLitePCL.SQLite3Provider_e_sqlite3.sqlite3_blob_open(IntPtr db, String sdb, String table, String col, Int64 rowid, Int32 flags, IntPtr blob)
SQLitePCL.raw.sqlite3_blob_open(sqlite3 db, String sdb, String table, String col, Int64 rowid, Int32 flags, sqlite3_blob blob)
Microsoft.CodeAnalysis.SQLite.Interop.SqlConnection.ReadBlob_InTransaction(String tableName, String columnName, Int64 rowId)
Microsoft.CodeAnalysis.SQLite.Interop.SqlConnection+<>c__DisplayClass16_0.<ReadBlob>b__0()
Microsoft.CodeAnalysis.SQLite.Interop.SqlConnection.RunInTransaction(Action action)
Microsoft.CodeAnalysis.SQLite.Interop.SqlConnection.ReadBlob(String dataTableName, String dataColumnName, Int64 rowId)
Microsoft.CodeAnalysis.SQLite.SQLitePersistentStorage+Accessor<TKey, TWriteQueueKey, TDatabaseId>.ReadBlob(SqlConnection connection, TDatabaseId dataId)
Microsoft.CodeAnalysis.SQLite.SQLitePersistentStorage+Accessor+<ReadStreamAsync>d__9<TKey, TWriteQueueKey, TDatabaseId>.MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(TStateMachine stateMachine)
Microsoft.CodeAnalysis.SQLite.SQLitePersistentStorage+Accessor<TKey, TWriteQueueKey, TDatabaseId>.ReadStreamAsync(TKey key, CancellationToken cancellationToken)
Microsoft.CodeAnalysis.SQLite.SQLitePersistentStorage.ReadStreamAsync(Document document, String name, CancellationToken cancellationToken)
Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticDataSerializer.ReadStreamAsync(IPersistentStorage storage, String key, Object documentOrProject, CancellationToken cancellationToken)
Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticDataSerializer+<DeserializeAsync>d__5.MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(TStateMachine stateMachine)
Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticDataSerializer.DeserializeAsync(Object documentOrProject, String key, CancellationToken cancellationToken)
Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer+ProjectState.DeserializeAsync(DiagnosticDataSerializer serializer, Object documentOrProject, Object key, String stateKey, CancellationToken cancellationToken)
```

This becomes the 2nd heaviest hitter in allocations while typing.

**Comment by Therzok** [comment]
https://github.com/ericsink/SQLitePCL.raw/commit/210c28f96be1c5b712d7fca41664d5facbffec9a

When this is released, we can switch to caching the byte arrays.

**Comment by CyrusNajmabadi** [comment]
How obnoxious.

**Comment by Therzok** [comment]
There's also allocations from `sqlite3_bind_text` but not as many. Probably worth looking into that too later

**Comment by CyrusNajmabadi** [comment]
that one would be harder as that's how we actually push strings into sqlite.  In that case i don't know how we could avoid the allocation. :(

Note: one option might be if sqlite had an API that took a byte[] and length.  We could then pool the byte arrays and convert our strings into them.  But i don't believe sqlite currently has that (but i could be mistaken).

**Comment by CyrusNajmabadi** [comment]
Note: we already do work to deal with blob allocations.  We read into pooled byte[]s that are added back to the pool.  However, the pool has a cap and we will allocate if we go past that. It would be worth trying to find out why we're having so much traffic here that we're blowing past our pool cap.

**Comment by CyrusNajmabadi** [comment]
So, for the byte[] pool (for blob reading) we will use a pooled byte[] if the size of data is <= 4k.  And we will allow up to 1K pooled byte[]s to be in flight at a time.  In other words, we allow for around 4 MB of pooled data for blob reading.

So either we're reading lots of blobs larger than 4k.  Or we're reading so many *simultaneously* that we're going past the 1k limit.  Both sound like things that could be application bugs.

**Comment by Therzok** [comment]
These are the solution stats:
http://source.monodevelop.com/i.txt
`storage.ide` is around 30MB in size.

**Comment by CyrusNajmabadi** [comment]
> storage.ide is around 30MB in size.

That's a totally reasonable size.  We shoudl add some instrumentation to figure out what's causing hte excess blob allocations.

**Comment by Therzok** [comment]
@CyrusNajmabadi @sharwell https://github.com/ericsink/SQLitePCL.raw/issues/183#issuecomment-347560982

1.1.10 has added API for caching this, might be worth looking at?

**Comment by CyrusNajmabadi** [comment]
Considering how many blobs we read, it seems like it could be really nice.  Would you like to make a PR for this?

**Comment by Therzok** [comment]
Yes, definitely.

**Comment by sharwell** [comment]
The fix for this issue was reverted in #27484.

**Comment by Therzok** [comment]
Did we ever get around to un-reverting the changes?

**Comment by sharwell** [comment]
Updating this assembly requires a coordinated update across the division/product.

**Comment by ericsink** [comment]
FWIW:

SQLitePCLRaw 2.0 is coming soon.  Prerelease versions are up on NuGet, and the Entity Framework Core team plans to transition to this version in their next preview:

aspnet/EntityFrameworkCore#15403

For performance, version 2.0 now uses Span in lots of places.  Full (draft) release notes here:

https://github.com/ericsink/SQLitePCL.raw/blob/v2/v2.md

Please feel free to let me know if I can be of assistance in your use of SQLitePCLRaw, either for transitioning to this new release, or for the 1.x releases.

**Comment by CyrusNajmabadi** [comment]
@ericsink That's fantastic.  There are a lot of byte[] allocations in our current impl.  We go through a pool to help out here.  But that pool is complex, and it would be great if we could remove it.  One thing that would likely be great is (if  you don't already support this already) if you could directly support Streams in the APIs.  We have to do a lot of contortions to map from streams to the primitives that sqlitepcl supports.  It would be great if this was just natively supported at your layer.

If not, it's NBD.  We can def just map from a stream to a stack-allocated `Span<bytes>`.  But i'd just like to not have to do anything at all :)

**Comment by ericsink** [comment]
I'm interested in the possibility of providing a stream feature.  First let me take a look and see how you're doing that, just to make sure I'm envisioning the same thing you need.  I assume I'll find the relevant code here in this repo somewhere?

**Comment by ericsink** [comment]
BTW, related and of possible interest is the blog entry I just posted, FWIW:

https://ericsink.com/entries/utf8z.html

**Comment by CyrusNajmabadi** [comment]
> I'm interested in the possibility of providing a stream feature. First let me take a look and see how you're doing that, just to make sure I'm envisioning the same thing you need. I assume I'll find the relevant code here in this repo somewhere?

Yes.  The code, eventually, boils down to this:

https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.Accessor.cs

We first convert the stream to bytes here:

https://github.com/dotnet/roslyn/blob/6ead316e86d304e8b5bf2b85b71cbdf35bb2b52c/src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.Accessor.cs#L135-L136

Then we eventually write those bytes here:

https://github.com/dotnet/roslyn/blob/6ead316e86d304e8b5bf2b85b71cbdf35bb2b52c/src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.Accessor.cs#L271-L287

**Comment by ericsink** [comment]
1.  To be clear, when we talk about "directly support Streams in the APIs", we're just talking about blobs, right?
2.  So it looks like you're not currently using `sqlite3_blob_write()` at all.  Writes of a blob start with the blob in memory as a `byte[]` and it gets bound to a parameter of in INSERT statement.
3.  OTOH, `sqlite3_blob_read()` is used, but it reads the whole blob into a `MemoryStream` and returns that.
4.  I assume what we really want is an actual subclass of `System.IO.Stream` that wraps the SQLite incremental blob I/O APIs?
5.  And we would want those APIs to be `Span`-oriented, right?
6.  Wherein, for example, the implementation of the `Read<Span<byte>>` overload would use `sqlite3_blob_open()` to read that many bytes, and we would potentially never end up reading a whole blob into memory all at once?

**Comment by CyrusNajmabadi** [comment]
> To be clear, when we talk about "directly support Streams in the APIs", we're just talking about blobs, right?

No, i mean the literal System.IO.Stream type.  As per my links from before we start here:

```c#
            public async Task<bool> WriteStreamAsync(
                TKey key, Stream stream, Checksum checksumOpt, CancellationToken cancellationToken)
            {
```

And are trying to write that into a particular row.

We then convert that Stream into `byte[]` here:

```c#
                        var (checksumBytes, checksumLength, checksumPooled) = GetBytes(checksumOpt, cancellationToken);
                        var (dataBytes, dataLength, dataPooled) = GetBytes(stream);
```

We do this in a pooled manner so we can reuse those `byte[]`s

>So it looks like you're not currently using sqlite3_blob_write() at all. 

We don't do that.  But we do use:

```
        internal void BindBlobParameter(int parameterIndex, byte[] value, int length)
            => _connection.ThrowIfNotOk(sqlite3_bind_blob(_rawStatement.ptr, parameterIndex, value, length, new IntPtr(-1)));
```

to bind the blobs into a statement like so:  `@"insert or replace into ""{DataTableName}""(""{DataIdColumnName}"",""{ChecksumColumnName}"",""{DataColumnName}"") values (?,?,?)"`

> I assume what we really want is an actual subclass of System.IO.Stream that wraps the SQLite incremental blob I/O APIs?

For reading, that would likely be fine (if it can be done safely without corruption).  For writing, i'd like the sqlite api to be able to take in a stream and efficiently (i.e. in a totally non-allocating fashion) write it to a column as appropriate.

> And we would want those APIs to be Span-oriented, right?

No.  I'd like the APIs to be stream-oriented :)  Under the covers they could use spans of course.

**Comment by ericsink** [comment]
> No, i mean the literal System.IO.Stream type

Yes, I understood that. What I meant was whether you are wanting to use System.IO.Stream for column types other than blobs?  I mean, do you write things like text columns using a Stream?  Or integers?

> No. I'd like the APIs to be stream-oriented :)

Yes, but when I said "want those APIs to be Span-oriented", what I meant was whether you are wanting to use things like the `Read(Span<byte>) overload of Stream.  Because I thought "directly support Streams in the APIs" meant that you wanted me to return things as a Stream so that you could manipulate them using the standard methods of Stream.

> For writing, i'd like the sqlite api to be able to take in a stream and efficiently (i.e. in a totally non-allocating fashion) write it to a column as appropriate.

OK, for writing, It looks like you just want to pass Streams down to SQLite as a way of representing a bunch of bytes that may or may not be in memory.  Simply a way of provide a value (for INSERT or whatever) as a Stream (of bytes) instead of a byte[].

Something conceptually similar to this:

```
int sqlite3_bind_blob(sqlite3_stmt stmt, int index, System.IO.Stream blob);
```

I apologize if it seems like I am being difficult.  I did read the code you linked.  I'm just having trouble clearly understanding what you want, and I see no reason to implement something that is NOT what you want.  :-)

**Comment by CyrusNajmabadi** [comment]
You're not being difficult!  And i def understand the desire to get total clarity on things :D

**Comment by CyrusNajmabadi** [comment]
> Yes, I understood that. What I meant was whether you are wanting to use System.IO.Stream for column types other than blobs? I mean, do you write things like text columns using a Stream? Or integers?

Yes, that would be great.  Though I can see the desire to just use ReadOnlySpans/Spans...  perhaps we (roslyn) should first experiment moving over to ROSpans, and deprecate the stream form first before you do anything there.

BTW, i'd really love to discuss this in depth.  Are you available to come to gitter.im?  We could chat directly.  I'd love to walk you through our scenario and the problems I forsee (i.e. around blobs+sqlite limtations).  With your expertise, perhaps we could figure out a better way for roslyn do things!

**Comment by CyrusNajmabadi** [comment]
> OK, for writing, It looks like you just want to pass Streams down to SQLite as a way of representing a bunch of bytes that may or may not be in memory. Simply a way of provide a value (for INSERT or whatever) as a Stream (of bytes) instead of a byte[].

> Something conceptually similar to this:

> `int sqlite3_bind_blob(sqlite3_stmt stmt, int index, System.IO.Stream blob);`

Yes, that is 100% accurate. Though, as per the above post, let's table this for a moment.  It might be more appropriate for roslyn to change waht it is doing.  But i would love to discuss things more with you given your knowledge of the lower layers to see how it might impact how roslyn does things.  Thanks!

**Comment by ericsink** [comment]
Yeah, I can jump on gitter if you like.  Just let me know when and where.

Bigger picture:  Yes, if you have the flexibility to give this area of your code a fresh look, we may find some nice performance improvements.

**Comment by CyrusNajmabadi** [comment]
Now works :)

**Comment by CyrusNajmabadi** [comment]
@ericsink  @Therzok See here for how i addressed thsi: https://github.com/dotnet/roslyn/pull/50841/commits/ce2bf1286308281efc66cdbaacf7f132e4a1719f

I'm not a fan of this solution as it requires 'unsafe'.  However, there were no otehr way i could see to actually create a utf8z on demand without allocing.  Also, i couldn't create and cache utf8z's up front because they are ref-structs.   So this was the best solution i could come up with.
