### ISSUE TITLE
Null ref on GetTrackingLineColumn

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#23436]
variable misuse ML model tool found a null ref bug on https://github.com/dotnet/roslyn/blob/b4006aa257d30a8fcef926444b79063ca57ba6df/src/VisualStudio/Core/Def/Implementation/TableDataSource/AbstractTableEntriesSnapshot.cs#L165

basically, wrong snapshot is given, and null ref exception will be thrown.

**Comment by jinujoseph** [comment]
closed via 23437
