### ISSUE TITLE
Completion Service gives crappy results ....

### ISSUE THREAD

**Issue by lhfiedler** [dotnet/roslyn#23447]
**Version Used**:  2.4

**Steps to Reproduce**:  Code Below

```csharp
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Completion;
using Microsoft.CodeAnalysis.Host.Mef;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Composition.Hosting;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication6
{
    class Program
    {
        static void Main(string[] args)
        {
            var assemblies = new[]
            {
               typeof(string).Assembly,
               typeof(IList<string>).Assembly,
                Assembly.Load("Microsoft.CodeAnalysis"),
                Assembly.Load("Microsoft.CodeAnalysis.CSharp"),
                Assembly.Load("Microsoft.CodeAnalysis.Features"),
                Assembly.Load("Microsoft.CodeAnalysis.CSharp.Features"),
            };

            var partTypes = MefHostServices.DefaultAssemblies.Concat(assemblies)
                    .Distinct()
                    .SelectMany(x => x.GetTypes())
                    .ToArray();

            var compositionContext = new ContainerConfiguration()
                .WithParts(partTypes)
                .CreateContainer();

            MefHostServices host = MefHostServices.Create(compositionContext);

            var workspace = new AdhocWorkspace(host);

            string code = @"
using System;
namespace Test {
    public class TestClass {
        public IList<string> TestMethod() {
            string x = ""test"";
            x.
        }
    }
}";

            
            var document = workspace
                .AddProject("TestProject", LanguageNames.CSharp)
                .AddDocument("TestDocument.cs", SourceText.From(code));

            var service = CompletionService.GetService(document);
            CompletionList list = null;
            int idx = code.IndexOf("x.") + 1;
            list = service.GetCompletionsAsync(document, idx, CompletionTrigger.CreateInsertionTrigger('.')).Result;
        }
    }
}

```

**Expected Behavior**:
list should contain method names on a string object- i.e. .Equals, EndsWith, Length, etc ..
**Actual Behavior**:
"async,await,base,bool,byte,char,checked,const,decimal,default,do,double,dynamic,false,float,for,foreach,global,goto,if,int,lock,long,nameof,new,null,object,ref,return,sbyte,short,sizeof,string,switch,T,Test,TestClass,TestMethod,this,throw,true,try,typeof,uint,ulong,unchecked,unsafe,ushort,using,var,void,while,x,yield"

What am I doing wrong?   If nothing, then this is pretty pathetic intellisense ....

**Comment by sharwell** [comment]
I believe the problem lies here:

```csharp
int idx = code.IndexOf("x.") + 1;
```

This code is asking for completions between the `x` and the `.` (i.e. before the `.`). To get instance members of `string` I would expect a `+ 2` for the position instead.

**Comment by lhfiedler** [comment]
+2 gives a null list.

**Comment by lhfiedler** [comment]
I've written a for loop over the index (i.e 100 - > 500) and they're all junk or empty / null lists at every index.    I tried with a default completion trigger too.

**Comment by CyrusNajmabadi** [comment]
Can you debug through CompletionServiceWithProviders.GetCompletionsAsync and see where things are going wrong for you?

**Comment by lhfiedler** [comment]
Sure. In the meantime, can you guys copy paste the code above and confirm you're getting the same garbage results?

**Comment by CyrusNajmabadi** [comment]
@lhfiedler When i use real completoin (which just uses teh completion service under the covers) i get completely expected results after the dot.  As i mentioned before, you shoudl debug through CompletionServiceWithProviders.GetCompletionsAsync to see where things go wrong for you.

**Comment by lhfiedler** [comment]
Adding 
`                .WithMetadataReferences(new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) });
`
to the project gives me better results.

**Comment by CyrusNajmabadi** [comment]
Terrific!

**Comment by CyrusNajmabadi** [comment]
Closing out.  This question was resolved.
