### ISSUE TITLE
Unable to build on Ubuntu

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/roslyn#23446]
**Version Used**: 
Git HEAD

**Steps to Reproduce**:

```
osboxes@osboxes:~/dotnet/roslyn$ cd build/linux/
osboxes@osboxes:~/dotnet/roslyn/build/linux$ sudo ./setup.sh
```

**Expected Behavior**:
This should build

**Actual Behavior**:

```
Executing: /tmp/tmp.j3JbYhAtFy/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
gpg: requesting key D3D831EF from hkp server keyserver.ubuntu.com
gpg: key D3D831EF: "Xamarin Public Jenkins (auto-signing) <releng@xamarin.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
deb http://jenkins.mono-project.com/repo/debian sid main
Reading package lists... Done
Building dependency tree       
Reading state information... Done
mono-snapshot-latest is already the newest version (1:2017.11.24+01.30.55-1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.10.0-28 linux-headers-4.10.0-28-generic linux-headers-4.10.0-30 linux-headers-4.10.0-30-generic linux-headers-4.10.0-33 linux-headers-4.10.0-33-generic linux-headers-4.10.0-35 linux-headers-4.10.0-35-generic linux-headers-4.8.0-36
  linux-headers-4.8.0-36-generic linux-image-4.10.0-28-generic linux-image-4.10.0-30-generic linux-image-4.10.0-33-generic linux-image-4.10.0-35-generic linux-image-4.8.0-36-generic linux-image-extra-4.10.0-28-generic linux-image-extra-4.10.0-30-generic
  linux-image-extra-4.10.0-33-generic linux-image-extra-4.10.0-35-generic linux-image-extra-4.8.0-36-generic mono-snapshot-2017.10.18+15.29.05 mono-snapshot-2017.10.18+15.29.05-assemblies snap-confine
Use 'sudo apt autoremove' to remove them.
0 to upgrade, 0 to newly install, 0 to remove and 159 not to upgrade.
/tmp ~/dotnet/roslyn/build/linux
--2017-11-28 23:00:40--  http://storage.bos.xamarin.com/bot-provisioning/PortableReferenceAssemblies-2014-04-14.zip
Resolving storage.bos.xamarin.com (storage.bos.xamarin.com)... 198.0.162.157
Connecting to storage.bos.xamarin.com (storage.bos.xamarin.com)|198.0.162.157|:80... failed: Connection timed out.
Retrying.

--2017-11-28 23:02:51--  (try: 2)  http://storage.bos.xamarin.com/bot-provisioning/PortableReferenceAssemblies-2014-04-14.zip
Connecting to storage.bos.xamarin.com (storage.bos.xamarin.com)|198.0.162.157|:80... 
```
and so on.

**Comment by jcouv** [comment]
That's not the script for building.
See instructions on building on Linux at https://github.com/dotnet/roslyn/blob/master/docs/infrastructure/cross-platform.md

I took some additional [notes](https://github.com/dotnet/sdk/issues/1686) when I tried the steps on Ubuntu recently, in case that helps.

**Comment by masonwheeler** [comment]
@jcouv Then what is the script I used supposed to be doing?  Either way, it's broken.

Also, why does this not have a `build.sh` like coreclr and corefx do?  Looking at cross-platform build options is very obviously the wrong thing to do, so if it's *actually* the right thing to do, something is very wrong.  I'm not trying to build cross-platform; I'm trying to build for Linux on Linux, so, lacking a `build.sh` script, the obvious place to look for a build script is in `/build/linux`.

**Comment by jcouv** [comment]
I'm not sure what setup.sh is for. Here's the description about it that I could find: https://github.com/dotnet/roslyn/commit/8928a86c244744ac7a5fede8b2202245df1c0505#diff-6589cd992f0fd2bf7a04e37cfa7f021c

Although I gave you a direct link to cross-platform build instructions, you will find those instructions if you follow the links from the front page:
On https://github.com/dotnet/roslyn you will see:
![image](https://user-images.githubusercontent.com/12466233/33398265-3936f3c6-d503-11e7-8de8-3b489a88de88.png)
Then on https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging you will see:
![image](https://user-images.githubusercontent.com/12466233/33398289-5204d620-d503-11e7-91a3-5bcdcd407883.png)

The link for "Instructions for Building on Linux and Mac" is the link I gave you.

**Comment by masonwheeler** [comment]
All right, running from there worked.
