### ISSUE TITLE
Suggestion - private, default parameters for recursive methods

### ISSUE THREAD

**Issue by series0ne** [dotnet/roslyn#23468]
**Scenario**
Consider the following method that implements the Fibonacci algorithm:
```
public static IEnumerable<int> Fibonacci(int a, int b, int n, List<int> list = null)
{
    list = list?.AddAndReturn(b) ?? new List<int>(new int[] { a, b });
    return list.Count < n ? Fibonacci(b, a + b, n, list) : list;
}
```

This allows me to pass Fibonacci arguments `a` and `b`, an iteration count `n`, and an optional argument `list` to append Fibonacci values to _(used explicitly within the method)_.

**Example**
```
IEnumerable<int> fibonacciSequence = Fibonacci(0, 1, 20);
```

**Problem**
The method leaks an implementation detail _(the list)_ and allows any populated list to be passed in, thus yielding invalid results:
```
List<int> random = new List(new int[] { 123, 456, 789 });
IEnumerable<int> fibonacciSequence = Fibonacci(0, 1, 20, random);
```

**Solution**
A method parameter could allow `private` modification, provided that:
1. The parameter provides a `default` argument.
2. _The method is recursive._

This would prevent leaking implementation details of the method to the outside, whilst allowing the parameter to be set internally; for example:

```
public static IEnumerable<int> Fibonacci(int a, int b, int n, private List<int> list = null)
{
    list = list?.AddAndReturn(b) ?? new List<int>(new int[] { a, b });
    return list.Count < n ? Fibonacci(b, a + b, n, list) : list;
}
```

As illustrated from the example above, the `list` argument can be set explicitly from inside the method, however the following would raise a compilation error:
```
Fibonacci(0, 1, 20, random);
// Error: parameter is inaccessible.
```

**Workaround**
As of C# 7.0, it's possible to use a local method, however this just wraps the current method inside another method that does not expose the `list` parameter:
```
public static IEnumerable<int> Fibonacci(int a, int b, int n)
{
    IEnumerable<int> Fibonacci(int a1, int b1, int n1, List<int> list)
    {
        list = list?.AddAndReturn(b1) ?? new List<int>(new int[] { a1, b1 });
        return list.Count < n1 ? Fibonacci(b1, a1 + b1, n1, list) : list;
    }
    
    return Fibonacci(a, b, n, null);
}
```

I don't particularly like the workaround, because it requires duplicated, but different parameter names, and it just seems a bit...hacky.

**Comment by HaloFour** [comment]
Language proposals belong on the [CSharpLang repository](github.com/dotnet/csharplang/issues).

**Comment by series0ne** [comment]
@HaloFour can this be migrated?

**Comment by jcouv** [comment]
Issue moved to [dotnet/csharplang #1159](https://github.com/dotnet/csharplang/issues/1159) via [**ZenHub**](https://www.zenhub.com/)
