### ISSUE TITLE
Generate PDB files when building Roslyn?

### ISSUE THREAD

**Issue by dpopiashvili** [dotnet/roslyn#23467]
Our company needs to generate OpenCover report for all the open source products we are using. One of them is Roslyn compiler. I'm not very good at either Roslyn or OpenCover, but as far as I understand, I need pdb files to generate cover report. The problem is that, the build steps documented doesn't generate pdb files when building Roslyn from source code, even though default build type is set to Debug. So my question is, how do I force pdb file genereration when building Roslyn?

Thanks

**Comment by tmat** [comment]
The PDBs we generate in a local build are embedded. See ```DebugType``` setting here: https://github.com/dotnet/roslyn/blob/master/build/Targets/Settings.props#L125 
You can override ```DebugType``` and set it to ```full``` to get Windows PDBs. I believe OpenCover currently only supports Windows PDBs.

**Comment by jcouv** [comment]
@dpopiashvili A side note: I assume that you're trying to produce coverage information of running the Roslyn tests on the Rolsyn code. If that's indeed what you're trying to do, would you mind sharing your results once you produce them? Thanks

**Comment by dpopiashvili** [comment]
@tmat Thanks, that worked.
@jcouv sure, I will share it here once it's done.

Thanks guys

**Comment by jcouv** [comment]
I'll go ahead and close the issue, since the question (how to produced PDBs when building Roslyn?) was answered. Thanks
