### ISSUE TITLE
Optimize allocations in IsDefinedInSourceTree hot paths

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#23462]
AnalyzerRunner is showing a few allocation hot paths in `IsDefinedInSourceTree`. The primary cases are:

* 677MB (3.5%): `Symbol.IsDefinedInSourceTree` &rarr; `SourceMemberContainerTypeSymbol.DeclaringSyntaxReferences` &rarr; `MergedTypeDeclaration.SyntaxReferences`
    * 677MB: `SyntaxReference[]`
* 475MB (2.5%): `SourceNamespaceSymbol.IsDefinedInSourceTree` &rarr; `SourceNamespaceSymbol.DeclaringSyntaxReferences`
    * 372MB: `NamespaceDeclarationSyntaxReference`
    * 103MB: `SyntaxReference[]`

**Comment by MaStr11** [comment]
Related #22580

**Comment by sharwell** [comment]
@MaStr11 Yes, this was intended to replace the other issue, but I forgot to go back and mark it as a duplicate after creating this issue.
