### ISSUE TITLE
Unnecessary allocation overhead in ExpressionSyntaxExtensions.TryReplaceWithAlias

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#23461]
AnalyzerRunner testing revealed substantial allocation overhead in `ExpressionSyntaxExtensions.TryReplaceWithAlias` (~7.5% of total). In the sample project, most source files did not contain using alias directives at all, making these allocation unnecessary. Performance of the Simplify Type Name analyzer would be improved by two improvements to the analysis:

1. Fast-path return from `TryReplaceWithAlias` if the document does not contain any using alias directives
2. If the document contains one or more using alias directives, perform a simple name elimination check to determine if any of the directives are relevant to the candidate name

**Comment by zaytsev-victor** [comment]
I want to take it.
@sharwell Could you please provide me info where to get ```AnalyzerRunner``` and any documentation for the tool?

**Comment by sharwell** [comment]
@zaytsev-victor You can check out the latest commit in #23087 and set the AnalyzerRunner project as the startup project. Make sure to check out the OrchardCMS/Orchard project into a directory next to dotnet/roslyn.

**Comment by sharwell** [comment]
@zaytsev-victor I went ahead and submitted a PR for this one this morning.
