### ISSUE TITLE
Jump to definition in metadata result in unexpected language

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#23460]
**Version Used**: 
VS 15.4.5
**Steps to Reproduce**:

1. Open a solution with multiple languages, like Roslyn itself
2. Go to outer definition from a C# file
3. Go to outer definition from a VB file

**Expected Behavior**:
When press "go to definition" from C# file, the metadata should be decompiled as C#, and so as VB.
**Actual Behavior**:
The two actions result in same language, both C# or both VB.

**Comment by jcouv** [comment]
I may be missing something. Why would any decompilation be needed if you use GoToDefinition on a type that is defined within the solution? There already is source for that definition, and as far as I can tell, GoToDefinition just jumps to it (which seems correct behavior).

**Comment by huoyaoyuan** [comment]
I mean symbols not defined in the solution, that "outer definition".

**Comment by jcouv** [comment]
Ah, thanks for clarification.
To take a concrete example, if I GoToDefinition to ImmutableArray type from a VB file, I see VB produced from metadata:
![image](https://user-images.githubusercontent.com/12466233/33446703-c031d26c-d5b5-11e7-8805-254ffcdf9d3e.png)

If I do the same from C#, I see C# produced from metadata:
![image](https://user-images.githubusercontent.com/12466233/33446730-d3956ae4-d5b5-11e7-9056-0acf145d7e68.png)

This seems by-design to me, but I'll let the IDE team confirm. Thanks

**Comment by jcouv** [comment]
Tagging @jinujoseph @kuhlenh to chime in

**Comment by CyrusNajmabadi** [comment]
We had a bug where going to def on a C# symbol could take you to VB metadata-as-source.  It's possible the OP is hitting that.

**Comment by dpoeschl** [comment]
@huoyaoyuan Does this reproduce for you reliably? Can it be reduced to a simple solution (or any solution you can share)? I have not been able to reproduce the problem here. Even when I leave the metadata view open from one language and try from another language, it updates appropriately.

**Comment by huoyaoyuan** [comment]
Observed in some old version (about 15.4.1), but cannot repro in latest version (with the same solution).
I think I can treat this as fixed.

**Comment by huoyaoyuan** [comment]
Additional information: this happened on UWP project in C# and a winmd project in VB.

**Comment by huoyaoyuan** [comment]
Closing. No reproduction in latest versions. Waiting for old project system to retire to reduce inconsistency.
