### ISSUE TITLE
Bug changing signature of deconstruct

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#23487]
**Version Used**:  15.4.5

**Steps to Reproduce**:

1. have a deconstruct like `Foo(out int x, out string y)`
2. have an assignment `var (value, str) = foo;`
3. follow the assignment with `string x = str;`
4. change signature of deconstruct. click on deconstruct method, from lightbulb select `change signature`. re-order parameters, for example move string parameter up and press ok.

you will see that deconstruct assignment remains unchanged. 

**Expected Behavior**:

after changing deconstruct signature it is expected to update usage all over the place.

**Actual Behavior**:

deconstruct assignments remains unchanged and has to be fixed manually.

**Comment by jcouv** [comment]
Thanks for reporting this.
That is a known issue, which is tracked by https://github.com/dotnet/roslyn/issues/23037
I'll go ahead and close as duplicate.
