### ISSUE TITLE
Disallow `default` as a constant pattern.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#23499]
The LDM has tentatively decided to disallow a `default` keyword (literal) as a constant pattern, in order to reduce confusion with "default" cases in switch statements and expressions. A programmer can always write `null`, `0`, or `'\0'` instead. This is technically a breaking change.

In a switch statement, the case label
`case default:`
is proposed to produce an error something like
`error CS8313: A default literal 'default' is not valid as a pattern. Use another literal (e.g. '0' or 'null') as appropriate. To match everything, use a discard pattern '_'.`
We already produce approximately this diagnostic, but as a warning.

In an _is-pattern_ expression and other places where patterns appear
`e is default`
is proposed to produce an error something like
`error CS8405: A default literal 'default' is not valid as a pattern. Use another literal (e.g. '0' or 'null') as appropriate. To match everything, use a discard pattern '_'.`

This will need review from the compatibility council.

**Comment by jcouv** [comment]
Just to clarify the proposal is to produce an error instead of the current warning: ```warning CS8313: Did you mean to use the default switch label (`default:`) rather than `case default:`? If you really mean to use the default literal, consider `case (default):` or another literal (`case 0:` or `case null:`) as appropriate.```

**Comment by gafter** [comment]
Yes. Clarified above.

**Comment by jcouv** [comment]
Should we make this change in 15.6 or 15.7 instead, to reduce the impact of breaking change? Default expressions where introduced in C# 7.1.

**Comment by gafter** [comment]
That is a question for the compat council.

**Comment by jcouv** [comment]
I'm not on that thread ;-)
I think we should do this in 15.6. Thanks

**Comment by gafter** [comment]
For 15.6, the messages are modified as we do not have a discard pattern. For the switch, we recommend the `default:` label. For pattern matching we recommend `var _`.

**Comment by ericwj** [comment]
I disagree.

I see no reason why it is necessary to break my code after fixing `case default:` with `case (default):` based on the warning previously issued.

CS8313 re-introduces code edits that were happily a thing of the past changing the type of a thing.

And the remark `If you intended to write the default label use 'default:' without 'case'.` is totally lame. I don't mean `default:` I mean either `case 0:` or `case null:` depending on the actual type.

**Comment by YairHalberstadt** [comment]
The suggested solution will of course not work for generic types without a class or a struct constraint

**Comment by alrz** [comment]
is it too late to also disallow `goto case default`?
