### ISSUE TITLE
Smart variable naming should support pattern matching syntax

### ISSUE THREAD

**Issue by zaytsev-victor** [dotnet/roslyn#23497]
**Version Used**: 
VS 2017 15.4

**Steps to Reproduce**:

```csharp
using System.Threading;

public class C
{
    public static bool Foo()
    {
        object obj = null;
        return obj is CancellationToken $$
    }
}
```
1. Put the cursor to $$
2. Try to invoke completion

**Expected Behavior**:
Completion should provide variable names

**Actual Behavior**:
Nothing happen

**Comment by sharwell** [comment]
You fixed this bug 1 hour after finding it?

⭐️ to you!
