### ISSUE TITLE
Get offered a refactoring lightbulb, but dropping it disappears

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#23501]
_From @davkean on November 30, 2017 4:25_

1. 
``` C#
    internal interface ITargetFrameworkProvider
    {
        /// <summary>
        /// Parses full tfm or short framework name and returns ITargetFramework instance.
        /// Note: it can throw if framework name has invalid format so we catch it here and 
        /// return null always, to avoid exception. Consumers should handle null.
        /// </summary>
        string GetTargetFramework(string shortOrFullName); 
    }
```

2. Put the cursor before the `;` in the signature.
3. Using keyboard move cursor once to right of screen so that it after `;`

-- Notice refactoring lightbulb ---

Attempting to drop it, causes it to disappear.

_Copied from original issue: dotnet/project-system#3009_

**Comment by davkean** [comment]
_From @Pilchie on November 30, 2017 17:14_

@davkean didn't I see you move this to https://github.com/dotnet/roslyn ?

**Comment by CyrusNajmabadi** [comment]
Doesn't repro.   The lightbulb opens with 'change signature.
