### ISSUE TITLE
Add a link to Tools>Options>…>Code Style to link to EditorConfig documentation

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#23513]

**Comment by kuhlenh** [comment]
Here is a rough mockup:

![image](https://user-images.githubusercontent.com/1402694/33785930-03acb8d8-dc1c-11e7-956b-a90d741f6ab0.png)

**Comment by kuhlenh** [comment]
Text: "The settings configured here only apply to your account. To configure these settings to travel with your solution, use EditorConfig. [Learn more](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference)"

@jasonmalinowski @dpoeschl @jinujoseph to verify the text

**Comment by jasonmalinowski** [comment]
"account" may be a confusing word here. It's correct if it roams, but if they don't have setting sync on, then it's _technically_ correct in that it means your local user account, but that's splitting hairs in a confusing way.

**Comment by jmarolf** [comment]
NOTE: These settings do roam.  So if settings sync is on account would make sense.

**Comment by kuhlenh** [comment]
@jasonmalinowski  - I will just make it "machine" then

**Comment by JieCarolHu** [comment]
fixed and merged
