### ISSUE TITLE
[c# Feature Request] CallerUniqueIdAttribute

### ISSUE THREAD

**Issue by ramoneeza** [dotnet/roslyn#23512]
The Caller(Members/File/Line) Attributes are very useful in "restricted to class" scenarios like "INotifyChanged" interfaces or exceptions.

But It is not complete in a "per application/library" scenario. (Example "Static variables", "Persistent Variables", etc.)

Stackoverflow has an example of "StaticLocal<T>" implementation showing the problem:
https://stackoverflow.com/questions/2393156/does-c-sharp-support-the-use-of-static-local-variables

```
public static class StaticLocal<T>
{
    static StaticLocal()
    {
        dictionary = new Dictionary<int, Dictionary<string, Access>>();
    }

    public class Access
    {
        public T Value { get; set; }

        public Access(T value)
        {
            Value = value;
        }

    }

    public static Access Init(T value, [CallerFilePath]string callingFile = "",
                                       [CallerMemberName]string callingMethod = "",
                                       [CallerLineNumber]int lineNumber = -1)
    {
        var secondKey = callingFile + '.' + callingMethod;
        if (!dictionary.ContainsKey(lineNumber))
            dictionary.Add(lineNumber, new Dictionary<string, Access>());
        if (!dictionary[lineNumber].ContainsKey(secondKey))
            dictionary[lineNumber].Add(secondKey, new Access(value));
        return dictionary[lineNumber][secondKey];
    }

    private static Dictionary<int, Dictionary<string, Access>> dictionary;

}
//It can be implemented within a method like this:

var myVar = StaticLocal<int>.Init(1);
Console.Writeline(++myVar.Value);

```
A real solution with a "CallerUniqueIdAttribute" simplifies that kind of variables:

```
public static class StaticLocal<T>
{
    private static Dictionary<int,Access> dictionary=new Dictionary<int,Access>();
    public class Access
    {
        public T Value { get; set; }
        public Access(T value)
        {
            Value = value;
        }
    }
    public static Access Init(T value, [CallerUniqueId]int callingUniqueId = -1)
    {
        if (!dictionary.ContainsKey(callingUniqueId))
            dictionary.Add(callingUniqueId,new Access(value));
        return dictionary[callingUniqueId];
    }
}

[...]
var myVar = StaticLocal<int>.Init(1);
Console.Writeline(myVar.Value);
[..]

```

I think, it is very simple to the compiler to have a simple counter giving an unique interger value for each [CallerUniqueId] attribute instance when appears.

**Comment by CyrusNajmabadi** [comment]
I'm confused.  You have a working solution that doesn't need this new attribute.  So why would we need this new attribute?

**Comment by CyrusNajmabadi** [comment]
> I think, it is very simple to the compiler to have a simple counter giving an unique interger value for each [CallerUniqueId] attribute instance when appears.

It's wouldn't be.  Furthermore, it wouldn't be sufficient.  Take a simple example:

You have this code in your Util.dll library:

```c#
    public static Access Init(T value, [CallerUniqueId]int callingUniqueId = -1)
    {
        if (!dictionary.ContainsKey(callingUniqueId))
            dictionary.Add(callingUniqueId,new Access(value));
        return dictionary[callingUniqueId];
    }
```

Then you have two projects ProjectA and ProjectB that reference that dll.  In each of those projects you do:

```c#
var myVar = StaticLocal<int>.Init(1);
Console.Writeline(myVar.Value);
```

The compiler will use the uniqueId '0' for each of these since you've only specified "a simple counter".  And now ProjectA and ProjectB will both be updating the same variable, violating the desire for this to represent a static local.

**Comment by ramoneeza** [comment]
CallerUniqueId must be a "GUID" or a Hash calculated from Module Hash ^ Method.Hash

Implementation of Static Variables ( C++ Style) for Regex, Timers, etc... should be fast enough. 

Using several string attributes is not fast.

There are several algorithms and structures (not only static variables) that can make use of this Member Attribute. (And avoid reflection)

**Comment by ramoneeza** [comment]
AS easy as make [CallerUniqueId] = [CallerFilePath].Hash ^  [CallerMemberName].Hash ^   [CallerLineNumber]  at compiler time.

Or enable [CallerFilePath] and [CallerMemberName] as long type (it implies hash calculation at compile time)

**Comment by jcouv** [comment]
I'll go ahead and move to csharplang since this is a language design discussion, not a compiler bug. Thanks

**Comment by jcouv** [comment]
Issue moved to [dotnet/csharplang #1168](https://github.com/dotnet/csharplang/issues/1168) via [**ZenHub**](https://www.zenhub.com/)
