### ISSUE TITLE
Full signing is broken using csc.exe in 15.6.x

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#23521]
Repro:

1. Use `sn.exe` to create a keyfile by calling `sn.exe -k test.snk`.
2. Compile hello world with signing using `csc.exe -keyfile:test.snk hello.cs`.
3. Run `sn.exe -vf hello.exe` to verify that the output is signed.

Expected:
```
Assembly 'hello.exe' is valid
```

Actual:
```
Failed to verify assembly -- Strong name validation failed.
````

**Comment by agocke** [comment]
Update on this: the compiler is correctly marking the binary signed, but the result is not correct (the actual signing is broken). It appears our tests do not actually verify that the assembly that is signed matches the given key.

**Comment by agocke** [comment]
I've confirmed that the problem is the hash of the assembly. This code appears to live in System.Reflection.Metdata, so I'll be trying to fix the code there.

**Comment by tmat** [comment]
@agocke What hash? The checksum?

**Comment by tmat** [comment]
We have tests for that here: https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/tests/PortableExecutable/PEBuilderTests.cs#L636 
Are we missing some case?

**Comment by jasonmalinowski** [comment]
@tmat That's checking your verification function? @agocke is noticing that we don't have any tests that validate the signature we create if we're signing is correct....just that we did sign.

**Comment by jasonmalinowski** [comment]
or whatever bug he is tracking down isn't caught in existing tests.

**Comment by tmat** [comment]
The tests I pointed out validate the implementation of Checksum field calculation in SRM.
There we also validate that the signing produced correct signature.

What e probably don't validate is end-to-end signing in Roslyn - that the SRM APIs are invoked properly. 

There might still be a bug in SRM, if I missed some special cases that are not covered by the SRM tests.

**Comment by agocke** [comment]
I managed to run RSA with the exact private key used to sign the DLL and verification seemed to fail. That's why I think the cause is the hash. Perhaps I'm still missing something.

**Comment by tmat** [comment]
Are we sure extracting the RSA parameters is correct?

**Comment by tmat** [comment]
Oh, this is wrong:

```
 var peBlob = new BlobBuilder();
            var peContentId = peBuilder.Serialize(peBlob, out Blob mvidSectionFixup);

            if (privateKeyOpt != null)
            {
                strongNameProvider.SignPeBuilder(peBuilder, peBlob, privateKeyOpt.Value);
            }

            PatchModuleVersionIds(mvidFixup, mvidSectionFixup, mvidStringFixup, peContentId.Guid);
```

We need to sign after we patch the MVIDs.

**Comment by agocke** [comment]
@tmat Right now I'm not sure of anything, but in this case, I used `sn.exe -i <keyfile>` to copy the keys in the keyfile that I used to sign the assembly into a key container. Since the RSA API supports windows key containers, I then constructed an RSA instance with that key and used that instance for verification. That should bypass the Roslyn code for parsing the keyfile entirely.

**Comment by agocke** [comment]
@tmat Nice catch. I'll test that out.

**Comment by agocke** [comment]
@tmat I'm still running into a problem. The checksums don't seem to come out correct. I'm a bit confused by some of the code in System.Reflection.Metadata. Look here at the code to verify the checksum:

https://github.com/dotnet/corefx/blob/45b724f6b6391910edea8a70f3f22a4a7996696d/src/System.Reflection.Metadata/tests/PortableExecutable/PEBuilderTests.cs#L685

Note that there are no binary modifications before calculating the checksum, so the checksum should include everything in the binary except for the checksum blob itself.

But now look at the signing code itself: https://github.com/dotnet/corefx/blob/45b724f6b6391910edea8a70f3f22a4a7996696d/src/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEBuilder.cs#L505

The checksum is calculated *before* writing the strong name signature, so it's calculated with the zero value. This doesn't look correct to me, and my tests with the CLR signing code seem to indicate that the checksum should include the strong name signature.

Am I missing something?

**Comment by tmat** [comment]
That might be it. So you're saying these two should be flipped? Have you tried that?

```
            uint checksum = CalculateChecksum(peImage, _lazyChecksum);
            new BlobWriter(_lazyChecksum).WriteUInt32(checksum);

            var writer = new BlobWriter(strongNameSignatureFixup);
            writer.WriteBytes(signature);
```

**Comment by tmat** [comment]
Also, is the only problem the checksum? Is the RSA signature correct?

**Comment by agocke** [comment]
Yup, I've used reflection to fixup the checksum after S.R.M signs and everything seems to work now. The signature is now also correct after moving the mvid patch before signing.

**Comment by agocke** [comment]
I've filed an issue on CoreFX here: https://github.com/dotnet/corefx/issues/25829

**Comment by tmat** [comment]
Cool.

**Comment by tmat** [comment]
BTW, does that mean sn.exe is validating the checksum?

**Comment by agocke** [comment]
I don't think it is, but I think the CLR might, so I don't want to risk producing binaries with an invalid checksum.
