### ISSUE TITLE
PathMap should accept and ignore empty mapping

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#23523]
**Version Used**: 

master

**Steps to Reproduce**:

```csc a.cs /pathmap:a=b,```
```csc a.cs /pathmap:a=b,,c=d```
```csc a.cs /pathmap:,c=d```

**Expected Behavior**:

The empty mappings are ignored.

**Actual Behavior**:

```
error CS8101: The pathmap option was incorrectly formatted.
```

Not accepting empty mapping makes logic that concatenates multiple mappings, for example in msbuild targets files, unnecessary complicates as it needs to avoid inserting extra ```,```.

**Comment by jcouv** [comment]
Tagging @khyperia as this may relate to https://github.com/dotnet/roslyn/pull/23053
