### ISSUE TITLE
The "Convert to interpolated string" automated refactoring does not escape curly braces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23536]
The refactoring &quot;Convert to interpolated string&quot; does not escape the exisiting curly braces when converting concatenated strings.

Eg. the statements
int number = 9;
string test1 = &quot;Something {X} = &quot; + number;
string test2 = &quot;Something {&quot; + number + &quot;}&quot;;
become
int number = 9;
string test1 = $&quot;Something {X} = {number}&quot;;
string test2 = $&quot;Something {{number}}&quot;;

The correctly converted strings are:
string test1 = $&quot;Something {{X}} = {number}&quot;;
string test2 = $&quot;Something {{{number}}}&quot;;

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/157181/the-convert-to-interpolated-string-automated-refac.html
VSTS ticketId: 530431_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by rik-smeets** [comment]
Assuming braces in a string literal should always be escaped here, the solution seems to be pretty easy. In `AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs`, replace lines 120 and 121 by:
```cs
var text = piece.GetFirstToken().Text;
var textWithEscapedBraces = text.Replace("{", "{{").Replace("}", "}}");
var textWithoutQuotes = GetTextWithoutQuotes(textWithEscapedBraces, isVerbatimStringLiteral);
```

It resolves this issue. Not sure if this is the best solution though, or if braces can indeed always be escaped in these situations. Any thoughts?

**Comment by CyrusNajmabadi** [comment]
Tagging @DustinCampbell .  @rik-smeets Your fix sounds good to me.  But checking with dustin to make sure nothing else would be a problem.

**Comment by DustinCampbell** [comment]
I think this is fine. Also tagging @jmarolf, who wrote this refactoring.

**Comment by jmarolf** [comment]
@rik-smeets your solution makes sense.  If you want to submit a PR I would be happy to review it :)

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/23589
