### ISSUE TITLE
c# validationattribute this

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23539]
1. Create a class that inherits from validationattribute.
1. Add a constructor that takes a lambda.
1. Apply the attribute to a property and pass a lambda that uses `this.` in its definition.

Visual studio crashes every time

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/156129/c-validationattribute-this.html
VSTS ticketId: 529812_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by zaytsev-victor** [comment]
I can repro it on 15.4.5, but it doesn't repro on VS 15.5 Preview 5

**Comment by sharwell** [comment]
@zaytsev-victor That's good news. Do you have a call stack handy that we can add to this for informational purposes?
