### ISSUE TITLE
SemanticModel.GetTypeInfo().Type is null for array initializers without 

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#23545]
**Version Used**: latest

**Steps to Reproduce**:

```cs
byte[] arr = { };
```

1. Find the `InitializerExpression` node correspoding to `{ }`.
2. Evaluate `semanticModel.GetTypeInfo(node, ct).Type` with this node.

**Expected Behavior**: Returns an `ITypeSymbol` corresponding to `System.Byte[]`.

**Actual Behavior**: Returns `null`. However, `ConvertedType` is `System.Byte[]`. Is this intentional behavior?

Filed on request of @mavasani, https://github.com/dotnet/roslyn-analyzers/pull/1339#issuecomment-347002451

**Comment by gafter** [comment]
Yes, the "expression" `{ }` does not have a type in and of itself, because it has no elements from which a type could be inferred. It only has a type taken from context (i.e., a converted type).
