### ISSUE TITLE
No projects found when building a solution in memory

### ISSUE THREAD

**Issue by kfrajtak** [dotnet/roslyn#23542]
Hi,

I am trying to compile a solution in memory using the Roslyn compiler. I am using the latest stable Nuget packages (version 2.4.0), the project that is compiling the solution is a .Net 4.6.1 class library.

The problem is that the project graph does not contain any projects.

````
var workspace = MSBuildWorkspace.Create();
var solution = workspace.OpenSolutionAsync(solutionUrl).Result;
var projectGraph = solution.GetProjectDependencyGraph();
var projects = projectGraph.GetTopologicallySortedProjects();
if (!projects.Any())
{
   Console.WriteLine($"{projects.Count()} projects :(");
   return false;
}
````

I might be missing some point. I have created a MVP solution in case you'd like to help me. Any help will be appreciated.

Thanks, Karel

**Version Used**: 
2.4.0 (Nuget packages)

**Steps to Reproduce**:

1. Get the repo from https://github.com/kfrajtak/DotIntrospection
2. Set the path to a SLN file
3. Run

**Expected Behavior**:
`projects` not empty

**Actual Behavior**:
`projects` is empty

**Comment by paul1956** [comment]
@kfrajtak Add the line below after the var workspace... and at least you will see what the issue is. I can't get it to work with 2.4.0 (in a test project) and was told at least for Test Projects I needed 2.6.
```
		   MS_Workspace.WorkspaceFailed += (object sender, WorkspaceDiagnosticEventArgs e) =>
		   {
			Debug.WriteLine(e.Diagnostic.ToString());
		   };
```
I also found I needed to call the routine below at the start of my code. With the code below I can load the projects and documents but not compile the solution.
```
		private static void InitializeMSBuild()
		{
			string registryKey = null;
			if (Environment.Is64BitProcess)
			{
				registryKey = "SOFTWARE\\Microsoft\\VisualStudio\\SxS\\VS7";
			}
			else
			{
				registryKey = "SOFTWARE\\Wow6432Node\\Microsoft\\VisualStudio\\SxS\\VS7";
			}
			using (RegistryKey subKey = Registry.LocalMachine.OpenSubKey(registryKey))
			{
				string visualStudioPath = subKey.GetValue("15.0") as string;
				if (!string.IsNullOrEmpty(visualStudioPath))
				{
					Environment.SetEnvironmentVariable("VSINSTALLDIR", visualStudioPath);
					Environment.SetEnvironmentVariable("VisualStudioVersion", "15.0");
					Environment.SetEnvironmentVariable("MSBuildSDKsPath", "C:\\Program Files\\dotnet\\sdk\\2.0.3\\Sdks");
				}
			}
		}
```

**Comment by kfrajtak** [comment]
Reading the diagnostics helped me (I had to add a reference to `Microsoft.CodeAnalysis.CSharp.Workspaces.dll`).

Though, I am still not able to compile the sources ...

> [Failure] Msbuild failed when processing the file 'C:\Temp\mvp\DotIntrospection\DotIntrospection\DotIntrospection.csproj' with message: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets: (84, 5): The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll. Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

Adding `<bindingRedirect />` did not help.

I was able to found out using fuslog that the calling assembly is `Microsoft.Build.Tasks.CodeAnalysis, Version=2.4.0.0` and it requires `Microsoft.Build.Utilities.Core, Version=14.0.0.0`, but it can only find `Microsoft.Build.Utilities.Core, Version=15.1.0.0` since that is referenced in the project.

**Comment by jcouv** [comment]
I don't fully understand the root cause, but there is a common problem with this scenario which people have solved by adding binding redirects to their app.config.
You may want to give [this](https://github.com/dotnet/roslyn/issues/24308#issuecomment-362362524) a try.

Tagging @DustinCampbell in case he has insights on the specific error you reported.

**Comment by kfrajtak** [comment]
After few trial and errors I was able to get to the point when the compilation started, but failed with following error

>[Failure] Msbuild failed when processing the file 'C:\Work\bitbucket\DotIntrospection\DotIntrospection\DotIntrospection.csproj' with message: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets: (84, 5): The "Csc" task could not be instantiated from the assembly "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll". Please verify the task assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one installed on your computer and that your host application is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type 'Microsoft.CodeAnalysis.BuildTasks.Csc' to type 'Microsoft.Build.Framework.ITask'.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets: (84, 5): The "Csc" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
[Failure] Msbuild failed when processing the file 'C:\Work\bitbucket\DotIntrospection\DotIntrospection.Console\DotIntrospection.Console.csproj' with message: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets: (1601, 5): The "GetReferenceNearestTargetFrameworkTask" task could not be instantiated from the assembly "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.Build.Tasks.dll". Please verify the task assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one installed on your computer and that your host application is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type 'NuGet.Build.Tasks.GetReferenceNearestTargetFrameworkTask' to type 'Microsoft.Build.Framework.ITask'.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets: (1601, 5): The "GetReferenceNearestTargetFrameworkTask" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
Compilation failed.

Then I have found some additional binding redirects (but don't remember where) and then it worked!

````
<dependentAssembly>
  <assemblyIdentity name="Microsoft.Build.Framework" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
  <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
</dependentAssembly>
<dependentAssembly>
  <assemblyIdentity name="Microsoft.Build" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
  <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
</dependentAssembly>
<dependentAssembly>
  <assemblyIdentity name="Microsoft.Build.Conversion.Core" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
  <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
</dependentAssembly>
<dependentAssembly>
  <assemblyIdentity name="Microsoft.Build.Tasks.Core" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
  <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
</dependentAssembly>
<dependentAssembly>
  <assemblyIdentity name="Microsoft.Build.Utilities.Core" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
  <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
</dependentAssembly>
<dependentAssembly>
  <assemblyIdentity name="Microsoft.Build.Engine" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
  <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
</dependentAssembly>
<dependentAssembly>
  <assemblyIdentity name="Microsoft.Build.Conversion.Core" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
  <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
</dependentAssembly>
````

**Comment by jcouv** [comment]
Glad this worked out.
Dustin is working to improve the design to address the root cause and help avoid this pitfall. I'll go ahead and close the present issue. Thanks

**Comment by kfrajtak** [comment]
Thank you.
