### ISSUE TITLE
EnvDTE.CodeElement.Kind returns vsCodeElementFunction instead of vsCMElementDeclareDecl for Declare Sub/Function of VB.NET

### ISSUE THREAD

**Issue by carlos-j-quintero** [dotnet/roslyn#2355]
See MS Connect Bug:

https://connect.microsoft.com/VisualStudio/feedback/details/1287398/envdte-codeelement-kind-returns-vscodeelementfunction-instead-of-vscmelementdeclaredecl-for-declare-sub-function-of-vb-net

**Comment by Pilchie** [comment]
BTW @carlos-j-quintero, no need to file in both Connect and here.  We prefer to deal with things here (unless they are security issues, or have sensitive user data of course).

**Comment by carlos-j-quintero** [comment]
Hi @Pilchie ,

So far I was using MS Connect because of a couple of reasons:

1) Bugs that I report on MS Connect are evaluated as a contribution for my next MVP award. They are even automatically added to my MVP profile. 

2) As MVP and as a member of the VSIP program, I receive private CTPs, previews, etc. that are under NDA, which a specific form to fill bugs on MS Connect. I use that form furthermore marking the report "only for Microsoft" rather than "public".

And then I open the bug here pointing to the MS Connect bug report.

In the future I guess I can report bugs only here and import them manually to my MVP profile and not mention the VS build if it is under NDA.

**Comment by Pilchie** [comment]
Just filing them here would be easiest for *us*, but I don't want to cause you more work regarding your MVP status either, so feel free to continue what you're doing.  I'll follow up with some MVP people internally.

For private builds, I suspect it'll be rare that a bug repros *only* on a private build, and in those rare cases, I personally don't mind saying that you have an NDA and got a private build :)
