### ISSUE TITLE
Issue with Workaround: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.Binder.InvokeMember'

### ISSUE THREAD

**Issue by scegg** [dotnet/roslyn#23573]
Hi all.

Today, while I'm using Roslyn to compile some code under netcoreapp 2, I got such an error due to using keyword "dynamic":
Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.Binder.InvokeMember'

If you google this, it will point you to add Microsoft.CSharp as reference while calling Roslyn method. But sadly, it's done in my project.

After several hour digging and testing, I found the problem and solution:
It seems that some methods related to Linq are used in my code. Adding **System.Linq.Expressions** as reference to Roslyn fixes the problem.

Note: Images of these references should be loaded only from TRUSTED_PLATFORM_ASSEMBLIES.

**Comment by jaredpar** [comment]
As you noted in the bug the fix for this error is to add references to the appropriate libraries. In general this is:

- Microsoft.CSharp
- System.Linq.Expressions
