### ISSUE TITLE
.NET Compiler Platform SDK in not compatible with Visual Studio 2017 15.5

### ISSUE THREAD

**Issue by aka-STInG** [dotnet/roslyn#23579]
**Version Used**: 
15.5
**Steps to Reproduce**:

1. Open VS after update
2. Windows about incompatible version displayed
3. .NET Compiler Platform SDK is disabled

**Expected Behavior**:
.NET Compiler Platform SDK should work, please provide extension update
**Actual Behavior**:
.NET Compiler Platform SDK is disabled

**Comment by AdmiralSnyder** [comment]
is it possible that the ".net compiler platform sdk" is now a component that needs to be (re)installed via visual studio installer rather that being an extension to get from the marketplace?
i saw it was not checked despite having visual studio extension development selected.

**Comment by AdmiralSnyder** [comment]
yes, seems so. i uninstalled the package in "Extensions and Updates", and modified the VS installation with the installer selecting ".net compiler platform sdk", and no there is the syntax visualizer again.

**Comment by shaggygi** [comment]
I also see this and put in via the VS Send Feedback.

**Comment by Pilchie** [comment]
Tagging @jmarolf - this *is* by design, but I wonder if there is something we can do to make the transition easier?  At least updating the marketplace page for the old SDK?

**Comment by MaStr11** [comment]
> But I wonder if there is something we can do to make the transition easier?

In the installation instructions for the [Syntax Visualizer tool](https://github.com/dotnet/roslyn/wiki/Syntax%20Visualizer) a Visual Studio 15.5 section could be added.

**Comment by Pilchie** [comment]
Yep - that should help.  @jmarolf - can you take a look at updating that wiki page?

**Comment by aka-STInG** [comment]
Thanks for the explanation and solution.
BTW, please support dark theme!

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #75](https://github.com/dotnet/roslyn-sdk/issues/75) via [**ZenHub**](https://www.zenhub.com/)

**Comment by MaStr11** [comment]
The installation instructions are still out of date. I opened a PR to copy the documentation from the roslyn wiki pages to the new roslyn SDK repo dotnet/roslyn-sdk#108. The wiki still needs to be updated to either reflect the new installation instructions or to point to the new home of the visualizer.
