### ISSUE TITLE
Span<T> stackalloc IntelliSense

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#23584]
**Version Used**: 

VS 15.5.0

**Steps to Reproduce**:

1. type `Span<byte> s = stac`...
2. Ctrl + Space

**Expected Behavior**:

C# 7.2 introduce safe `stackalloc` with the `Span<T>` struct. So `stackalloc` keyword should be listed in the IntelliSense window.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/3760955/33609970-6794aab0-da0d-11e7-879a-aed381229fbe.png)

**Comment by jcouv** [comment]
FYI @OmarTawfik (in case you want to take a look)

**Comment by CyrusNajmabadi** [comment]
Code for this is in StackAllocKeywordRecommender.cs
