### ISSUE TITLE
NuGet Microsoft.CodeAnalysis v2.6.0 stable has beta3 suffix in name

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#23580]
See https://www.nuget.org/packages/Microsoft.CodeAnalysis. Latest stable version according to NuGet is 2.4.0. I believe the 2.6.0-beta3 is misnamed. It should be 2.6.0 without the beta3 suffix.

**Comment by jcouv** [comment]
The [2.6.0-beta3](https://www.nuget.org/packages/Microsoft.CodeAnalysis/2.6.0-beta3) package seems be pre-release.

![image](https://user-images.githubusercontent.com/12466233/33788174-997197e0-dc25-11e7-9bb1-a6afa27f7150.png)

There's also a [2.6.0](https://www.nuget.org/packages/Microsoft.CodeAnalysis/2.6.0) (without `-beta3` suffix) which is marked as released.

Seems correct.

**Comment by bkoelman** [comment]
The stable package was published a day ago, roughly a week after the final bits of VS 2015.5 were released. But good to know it's available now, will switch to that.
