### ISSUE TITLE
VS crash on startup when My Documents folder is unavailable

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#2358]
My virtual machine had mapped [My Documents] folder to D:\UserName\Documents. Then later, in another VM, the D drive was removed. VS2015 CTP6 starts with a message that it will use temporary settings because settings could not be loaded. After a few seconds the same message box is displayed again. Then, after clicking OK, VS crashes and the OS's "... stopped working" dialog is displayed.

**Comment by bkoelman** [comment]
Exact message:

---------------------------
Microsoft Visual Studio
---------------------------
The automatically saved settings file 'd:\bart\documents\visual studio 2015\settings\CurrentSettings.vssettings' cannot be found. You can change this file on the 'Import and Export Settings' Tools Options page. The IDE will use your most recent settings for this session.
---------------------------
OK   
---------------------------

**Comment by Pilchie** [comment]
This is not a Roslyn issue.  Can you file this on http://connect.microsoft.com instead?

**Comment by bkoelman** [comment]
@Pilchie It gives message "You are not authorized to submit the feedback for this connection."

**Comment by Pilchie** [comment]
Can you tell what "connection" you are in?  It should be the Visual Studio one

**Comment by bkoelman** [comment]
@Pilchie Repro (text could differ slightly, because I see it localized in Dutch):
1] Click link http://connect.microsoft.com 
2] "19 products currently accepting bugs", click Browse
3] At the bottom of the list, click "Visual Studio and .NET Framework"
4] Click large pink button "Submit a bug"
5] Redirect to Microsoft account login, enter username/password
6] Message "You are not authorized to submit the feedback for this connection." (https://connect.microsoft.com/VisualStudio/feedback/LoadSubmitFeedbackForm)

**Comment by Pilchie** [comment]
Can you email me (kevinpi@microsoft.com), and we'll follow-up and figure this out?

**Comment by bkoelman** [comment]
@Pilchie I emailed you.

**Comment by davkean** [comment]
What was the resolution to this?

**Comment by bkoelman** [comment]
@davkean It turns out the Connect permissions issue has been fixed by now, so I created https://connect.microsoft.com/VisualStudio/feedback/details/2050590 to track this.

**Comment by davkean** [comment]
Okay, I'll close this issue - Connect should still be able to see it.
