### ISSUE TITLE
Add using operation should prefer top-level using directive

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#23586]
When _Add Using_ is invoked in a context that has using directives on top-level and in a namespace the new directive should be added to top-level.
The current logic breaks style that prefers top-level using directives except in rare cases when the semantics of using in a namespace are needed.
The new logic would also work with the alternative style that declares all using directives in the namespace and no directives at top-level.

**Version Used**: 

15.5.0

**Steps to Reproduce**:

```
using System.Threading.Tasks;

namespace App
{
    using System.IO;

    public class C
    {
        public void Main()
        {
            Console.WriteLine();   // Invoke "Add using System" here
        }
    }
}
```

**Expected Behavior**:

```
using System;                                  // using added here
using System.Threading.Tasks;

namespace App
{
    using System.IO;

    public class C
    {
        public void Main()
        {
            Console.WriteLine(); 
        }
    }
}
```

**Actual Behavior**:

```
using System.Threading.Tasks;

namespace App
{
    using System;                                  // using added here
    using System.IO;

    public class C
    {
        public void Main()
        {
            Console.WriteLine(); 
        }
    }
}
```

**Comment by sharwell** [comment]
I can't see any reason to call the current behavior wrong. Would recommend closing as a won't-fix.

**Comment by tmat** [comment]
It is not desirable. See https://github.com/dotnet/roslyn/pull/23376#discussion-diff-155003362R19

**Comment by sharwell** [comment]
@tmat You are assuming the user wants using directives outside the namespace. This is true for Roslyn, but not necessarily true for other projects. In a mixed-use scenario, it's not possible to confidently tell what was meant.

**Comment by tmat** [comment]
@sharwell I agree it's not possible to confidently tell. However, we can do better anyways. 

There are three styles for a code base:
1) Usings outside namespace by default and inside for some cases when the different semantics is needed/desired (Roslyn style).
2) All usings inside namespace.
3) No consistent style. It doesn't matter to the user where usings are placed.

Currently our implementation works well for 2) and 3) and it makes mistakes for 1).
The proposal would work for all these cases.

Is there a style I'm missing?

**Comment by CyrusNajmabadi** [comment]
What if you have a customer who wants 4:

4. Some common namespaces on the outside.  But most namespaces on the inside.

If we switch the behavior, now they're left out.

Effectively, there is no answer.  We look at your code and go with a sensible position.  We can't read people's minds, and any sort of default choice is going to be wrong for some customer.  We can always add options for things like this.  But really options shoudl be used when tehre is enough feedback that this is needed for two large existing group.  it's unclear that such groups exist.  Indeed, up till now, we've never heard about this.  It's possible that we're the outliers, and updating the feature just for us will not be great for everyone else :-/

**Comment by tmat** [comment]
> Some common namespaces on the outside. But most namespaces on the inside.

That sounds rather arbitrary. 

> updating the feature just for us

Not just for us. Having usings outside the namespace is the default that I get when I create a new project. We should not be breaking the default style.

**Comment by tmat** [comment]
We should also gather some data from github to see how often files belong to the above categories.

**Comment by CyrusNajmabadi** [comment]
> Not just for us. Having usings outside the namespace is the default that I get when I create a new project. We should not be breaking the default style.

We don't.  We respect htis style if the user follows it.  If the user puts usings inside teh namespace, then we respect that as well.

> That sounds rather arbitrary.

No more arbitrary than someone saying i put all my namespaces on the outside, but have a few on the inside. :)

It's not even clear why you have that pattern yourself :)

**Comment by CyrusNajmabadi** [comment]
In the example you linked to, tehre is ```using static DocumentationCommentXmlNames;``` inside the namespace.  I have no idea why that would be there.  Why not just have that on hte outside?

Note: one thing i am amenable to (and thought some work had been done on) is respecting different using-groupings.  So, for example, if someone only has "using statics" inside their namespace, but has normal "usings" on the outside, then we'd respect that depending on what type of using we were adding.

I honestly thought this had been done, but i guess we never got around to it.  

The primary reason for this is that it's pretty common to have using *using **aliases** * on the inside of your namespace (as on hte outside you often have to painfully fully qualify things).  So we don't want newly added usings to group with those, and instead should still go to the primary using-group.  Maybe we did that work, but didn't do the same for using-static?

**Comment by CyrusNajmabadi** [comment]
Yup.  Looks like we did the work to make it so that we don't add the using to the inner namespace if hte inner namespace is only "usings aliases" and the file has normal usings.  We can augment this to respect "using static" as well.  Note: if you do have some *normal* usings inside your namespace, we'll still respect that and use that to put new namespaces in.

**Comment by tmat** [comment]
> We can augment this to respect "using static" as well

That sounds like a good approach that would address the issue.

> We don't. We respect htis style if the user follows it

Note however that there is still one scenario where we actually break the default style. That is - I want my usings outside except for those that *have to be* inside to achieve hiding semantics that allows me to disambiguate types. This is possible since usings inside the namespace take precedence when types are looked up. Perhaps this is rare enough that we do not care.

**Comment by sharwell** [comment]
@JoeRobich does the new .editorconfig functionality cover this case?

**Comment by CyrusNajmabadi** [comment]
Would like to take to design review to close this out.  I believe the behavior we have now is desirable.  Specifically:

There is an option to set what preference you definitely want.  i.e.:

![image](https://user-images.githubusercontent.com/4564579/76058140-6bceb800-5f30-11ea-8e82-f8333c79173c.png)

Absent that, we will fall back to a when-in-rome approach where we look at your current using and use that to determine where to place new usings.  We also understnad the difference between `using` and `using static`.  So if you have an outer `using` and an inner `using static`, we won't place new usings with the inner one.

I thnk the scenario is covered well enough to close this out.

**Comment by sharwell** [comment]
@CyrusNajmabadi The Add Using operation should use the following:

* If no using directives are present in the file, use the specified option
* If using directives are present in only one location in the file, use that location
* If at least one using directive of the same form is present _and_ all such using directives are in the same location, use that location
* Otherwise, use the specified option to determine the location

**Comment by CyrusNajmabadi** [comment]
I believe we do the right thing here now.
