### ISSUE TITLE
'Replaces a method with property' refactoring should not be enabled for a method that overrides a metadata method

### ISSUE THREAD

**Issue by zaytsev-victor** [dotnet/roslyn#23593]
**Version Used**: 
VS 2017 15.5 Preview 5

**Steps to Reproduce**:

```csharp
class C : System.Type
{
     public override int $$GetArrayRank()
     {
     }
}
```
1. Put the cursor to $$

**Expected Behavior**:
'Replaces a method with property' refactoring is not suggested
**Actual Behavior**:
'Replaces a method with property' refactoring is suggested

**Comment by sharwell** [comment]
See also #22082 / #21397.

**Comment by CyrusNajmabadi** [comment]
Sorry, i would prefer to not do this. I just made a change recently where i made one of these changes and found the refactoring useful.  

The idea here is to provide tools that speed up things users want to do.  not necessarily only things that work 100% of the time.  For me, i wanted to change a property to a method, and then have the existing property override (which overrode something from metadata) call into that new method.  Having the refactoring was helpful.

We did decide that it was overkill on System.Object overrides, so we intentionally suppressed those.  But i think it would still be fine for other overrides.  If we don't like that, we can add a warning (both to the preview code, and to the glyph that gets shown to the user in the dropdown).

**Comment by zaytsev-victor** [comment]
@CyrusNajmabadi could you please provide me an example when it usefull?

**Comment by CyrusNajmabadi** [comment]
In my specific case i was doing ReplacePropWithMethod but the idea remains the same.  For me, i was subclassing JsonConverter and i wanted to replace the CanRead property with a method.  The CanRead property then called that new method passing along extra data.

**Comment by zaytsev-victor** [comment]
Probably for this case we can suggest to add property. But replacing is seems odd to me.

**Comment by CyrusNajmabadi** [comment]
How would AddProperty help?  The goal here was to update all my own overrides of this property, and also all the usages of it in my code.  I would have otherwise had to make dozens of manual changes.  To me, conceptually, i had a proeprty, and i wanted it replaced with methods.  That it happened to *also* override a metadata property was an unrelated issue that i was going to deal with *next*.  Having the feature just silently not show up for me would have been very confusing and would have made me feel like the product was broken.

**Comment by CyrusNajmabadi** [comment]
> But replacing is seems odd to me.

Why? :)

**Comment by CyrusNajmabadi** [comment]
Remember that refactorings are routinely used to just speed up manual changes that a user wants to make.  They're intended to try to be very correct, and to preserve semantics, but really it's often the case that users still just want them just so they don't have to go do a bunch of painfully repetitive work themselves.

**Comment by sharwell** [comment]
After reviewing the available options, I agree with @zaytsev-victor here. More specifically, we should do one of the following:

1. Do nothing at all (no refactoring offered)
2. Do something that makes sense

In this case, the form of option 2 is interesting and could certainly be implemented in the future. It would behave like the current Encapsulate Field refactoring, but would encapsulate a property or method instead. The work performed by @CyrusNajmabadi would be either a one- or two-step process involving the following:

1. Encapsulate a property by changing `override` to `sealed override` and delegate the behavior to a newly-created property in the same type
    * (Optionally) replace references to the original property with references to the new property
2. Convert the new property to a method

**Comment by CyrusNajmabadi** [comment]
Not planning on any change here.  I actually did just this refactoring recently and it was nice htat it was not blocked.  I removed the override afterwards and everything was good.
