### ISSUE TITLE
How can I enable C# interactive window in VS2013.4?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/roslyn#236]
Is it already available?

Does it include intellisense and code highlighting?

**Comment by kuhlenh** [comment]
Unfortunately, the C# Interactive Window is not available in VS2013. We are working on the REPL now and yes it will include IntelliSense! You can check out our Interactive Design notes so far: #122, #213.

**Comment by jaredpar** [comment]
In general our VSIX projects cannot be loaded into VS 2013.  We have a pretty strong dependency on the VS SDK that ships with 2015 and this isn't compatible with 2013.

**Comment by weitzhandler** [comment]
Thanks for your kind response.
