### ISSUE TITLE
Cannot build on Mac

### ISSUE THREAD

**Issue by kentcb** [dotnet/roslyn#23609]
**Version Used**: 

2.6.0-beta1

**Steps to Reproduce**:

1. Consume the 2.6.0-beta1 analyzers from a netstandard library
2. Try to build the library on Mac 

**Expected Behavior**:

It builds.

**Actual Behavior**:

```
CSC error CS8032: An instance of analyzer Microsoft.NetCore.Analyzers.Runtime.TestForNaNCorrectlyAnalyzer cannot be created from /Users/vagrant/.nuget/packages/microsoft.netcore.analyzers/2.6.0-beta1/analyzers/dotnet/cs/Microsoft.NetCore.Analyzers.dll : Could not load type of field 'Microsoft.NetCore.Analyzers.Runtime.TestForNaNCorrectlyAnalyzer:_comparisonOperators' (5) due to: Could not resolve type with token 0100008c (from typeref, class/assembly Microsoft.CodeAnalysis.Operations.BinaryOperatorKind, Microsoft.CodeAnalysis, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) assembly:Microsoft.CodeAnalysis, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 type:Microsoft.CodeAnalysis.Operations.BinaryOperatorKind member:<none>. [/Users/vagrant/git/Src/Utility/Utility.csproj]
```

**Comment by kentcb** [comment]
@ivanbasov sorry, I think I created this against the wrong repository. Would you mind moving it to dotnet/roslyn-analyzers as appropriate?

**Comment by ivanbasov** [comment]
@kentcb, thank you! Please move it to dotnet/roslyn-analyzers. NP!

**Comment by kentcb** [comment]
@ivanbasov I don't think I can though (unless I'm missing something?)

**Comment by ivanbasov** [comment]
@kentcb, I think the only option is to close this one and create a new one for another project.

**Comment by kentcb** [comment]
Moved to https://github.com/dotnet/roslyn-analyzers/issues/1453.

**Comment by Pilchie** [comment]
For future reference https://github-issue-mover.appspot.com/ is authorized for dotnet repos if you need to move issues.
