### ISSUE TITLE
Proposal: Set text selection after the refactoring is applied.

### ISSUE THREAD

**Issue by josefpihrt** [dotnet/roslyn#23604]
Currently, developer cannot control text selection (span) after the refactoring is applied.

Let's say I have a refactoring that will wrap statement(s) in if condition.

#### Before
```csharp
Foo();
```
#### After
```csharp
if ()
{
    Foo();
}
```
In this case would be useful to specify that cursor should be inside if condition after the refactoring is applied.

My idea is that it could be achieved by SyntaxAnnotation.

**Comment by CyrusNajmabadi** [comment]
We have NavigationAnnotation, which will take you to the start of the annotated element.  You could probably augment it to specify if the span should be selected.

**Comment by JosefPihrt** [comment]
Thanks for the tip, I did not know about this class.

Could we make it public?

I can, of course, create annotation like this:

```csharp
new SyntaxAnnotation("CodeAction_Navigation")
```

but I think I would be clearer to create it like this:
```csharp
NavigationAnnotation.Create()
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of user feedback on this.
