### ISSUE TITLE
Apply PerformanceSensitiveAttribute to previous work on IsDefinedInSourceTree

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#23615]
From @MaStr11 in https://github.com/dotnet/roslyn/pull/23554#discussion_r155038988:

> This attribute should also be applied to this locations to avoid regressions:
PR #23490
[SourceNamespaceSymbol](https://github.com/sharwell/roslyn/blob/63ffc585a6f0234564075d6cdc9d4ebd6295ba91/src/Compilers/CSharp/Portable/Symbols/Source/SourceNamespaceSymbol.cs#L466) 
[IsDefinedInSourceTree](https://github.com/sharwell/roslyn/blob/63ffc585a6f0234564075d6cdc9d4ebd6295ba91/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs#L873)

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We should either do this or not.  The tracking issue doesn't help us here.
