### ISSUE TITLE
Can't have a project that works on a mix of compilers (CI and Dev)

### ISSUE THREAD

**Issue by bencyoung** [dotnet/roslyn#23613]
Please see https://github.com/dotnet/roslyn-analyzers/issues/1437 for details (was requested to redirect to here)

Basically the issue is that we can't have a build that works on our CI environment which has an older C# compiler and dev machines which have upgraded to 15.5. The suggestion was to add  Microsoft.Net.Compilers 2.6.0-beta3 to the references, but then our .NET Full projects start getting:

[08:18:32][build] BaseComponent.cs(25,43): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

only on the CI environment. We used to have to add NETStandard.Library.NETFramework in .NET Standard 2 Beta for this kind of issue but that was removed when the SDK was released.

**Comment by jcouv** [comment]
Tagging @dotnet/roslyn-analysis for advice and triage.

**Comment by mavasani** [comment]
@jcouv I think @dotnet/roslyn-compiler should be able to advice as to how the customer can consume Microsoft.Net.Compilers toolset compiler NuGet package.

**Comment by bencyoung** [comment]
Anyone have any thoughts on this? Currently I have to work locally in a branch as the master won't compile on my dev box, but if I commit the branch to master then it won't compile on CI...

**Comment by jcouv** [comment]
@bencyoung Sorry for the delay.
With just the information you provided, I don't think I could set up a repro. Can you describe the environment where the problem occurs (is there .NET Framework 4.7 or 4.7.1 installed)?
Do you have access to one of your CI machines (assuming that's where the error occurs)? If yes, could you capture a binary log of your build process (`mbuild /bl ...`). This will record the references passed into the compiler.

**Comment by TaffarelJr** [comment]
I'm having the same issue. I've been keeping up with VS updates, and my small project has been building fine locally and in CI (TeamCity) using FxCopAnalyzers 2.3.0-beta1. With the VS 15.5.2 update, suddenly my project fails to build locally:

```
error CS8032:  An instance of analyzer
Microsoft.NetCore.Analyzers.Runtime.TestForNaNCorrectlyAnalyzer
cannot be created from
C:\Users\<username>\.nuget\packages\microsoft.netcore.analyzers\2.3.0-beta1\analyzers\dotnet\cs\Microsoft.NetCore.Analyzers.dll :
Exception has been thrown by the target of an invocation..
```

I can resolve it locally by upgrading FxCopAnalyzers to 2.6.0-beta2, but then the build fails on CI with a similar message:

```
error CS8032: An instance of analyzer
Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.UsePropertiesWhereAppropriateAnalyzer
cannot be created from
C:\Users\<TC username>\.nuget\packages\microsoft.codequality.analyzers\2.6.0-beta2\analyzers\dotnet\cs\Microsoft.CodeQuality.Analyzers.dll :
Could not load file or assembly
'Microsoft.CodeAnalysis, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
The system cannot find the file specified..
```

I have .NET Framework 4.7.1 SDK installed, and my .csproj is pretty simple:

```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard1.0</TargetFramework>
		<CodeAnalysisRuleSet>..\..\build\DeployedCode.ruleset</CodeAnalysisRuleSet>
		<DocumentationFile>$(AssemblyName).xml</DocumentationFile>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		... NuGet package properties here ...
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
		<Features>IOperation</Features>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AsyncUsageAnalyzers" Version="1.0.0-alpha003">
			<PrivateAssets>All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.3.0-beta1">
			<PrivateAssets>All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta004">
			<PrivateAssets>All</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="..\..\build\StyleCop.json" Link="StyleCop.json" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="1.0.0" />
	</ItemGroup>

</Project>
```

**Comment by 333fred** [comment]
@TaffarelJr did you try including a reference to `Microsoft.Net.Compilers` 2.6.1 in your project?

**Comment by TaffarelJr** [comment]
Bumping FxCopAnalyzers up to 2.6.0-beta2 and adding `<PackageReference Include="Microsoft.Net.Compilers" Version="2.6.1" />` seems to have gotten it working in both locations. Thank you!
