### ISSUE TITLE
NormalizeWhitespace() introduces extra whitespaces and inconsistent where constraint format

### ISSUE THREAD

**Issue by andreycha** [dotnet/roslyn#23618]
**Version Used**: 2.6.0-beta3

`NormalizeWhitespace()` adds extra whitespaces in the following cases:
- `new()` constraint becomes `new ()`
- `typeof(T)` becomes `typeof (T)`
- `default(int)` becomes `default (int)`
- `default(int?)` becomes `default (int? )` (note also extra space after question mark, smth missed in https://github.com/dotnet/roslyn/pull/22234?)

I believe that spelling on the left is kind of "traditional" one, so it would be good to remove extra whitespaces.

Also `where` constraint has different formatting:
- it starts on a new line in case of classes or interfaces:
```
public sealed class Class1<T>
    where T : struct, IEnumerable<T>
```
- in case of methods/delegates it's placed on the same line (and at least leaks whitespace before it):
`public TResult? Func1<TResult>(T? x, IEnumerable<T> y)where TResult : struct`

**Comment by jcouv** [comment]
Fix will be in 15.6 preview 3.
