### ISSUE TITLE
Add a functional test that checks for cross-language assembly loads

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#2362]
Most of our IDE performance tests have a step that checks that we don't load cross-language assemblies (i.e. we don't have VB assemblies loaded in a pure C# solution and vice versa).

Unfortunately, when it fires, it results in widespread failures in the perf lab. The turnaround time to investigate is usually more than 48 hours (often much longer) resulting in loss of performance coverage. To catch these regressions sooner and reach resolution faster, I would like to add a couple of integration tests (one for VB and one for C#) that check the same thing.

**Comment by tmeschter** [comment]
Not really an infrastructure issue.

**Comment by pharring** [comment]
The fix for this is entirely in our Closed source project.

**Comment by pharring** [comment]
This was addressed in the Closed source project.
