### ISSUE TITLE
Stale unused fields in the Error List

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#23631]
Don't have a repro, but I keep getting stale unused field warnings in the error that never go away in 15.6 builds:

![image](https://user-images.githubusercontent.com/1103906/33700724-0969ef96-db6f-11e7-8ae1-df5f437a6c8a.png)

You can see neither of those fields exist (they were renamed).
Full Solution Analysis is turned off - when I close the open file, the warning sticks around.

**Comment by Pilchie** [comment]
Tagging @heejaechang, but IIRC, the compiler only reports/clears those on build 😢

**Comment by heejaechang** [comment]
@davkean these are reported only during build unfortunately. but you can give this bug to me to see whether there is a way to make it live..

**Comment by heejaechang** [comment]
note* 

related to make compilation end action runs on all opened files.

**Comment by CyrusNajmabadi** [comment]
Closing out as these experiences were all rewritten for lsp.
