### ISSUE TITLE
MSBuildWorkspace incorrectly load a project, the configuration of which is different from current

### ISSUE THREAD

**Issue by Droni** [dotnet/roslyn#23638]
The problem is similar to https://github.com/dotnet/roslyn/issues/6709, but in my case the configuration selected in the project is also in the solution.
I configured the Configuration Manager in Visual Studio and the following text for my project was saved in the SLN file:

`{59054095-4DAA-43F2-93D7-3418D0C5340C} .DebugTest | Mixed Platforms.ActiveCfg = Debug | Any CPU
{59054095-4DAA-43F2-93D7-3418D0C5340C} .DebugTest | Mixed Platforms.Build.0 = Debug | Any CPU
`
As you can see with the DebugTest configuration selected in the solution, the project selected the Debug configuration. 
The Roslyn engine is not able to cope with this task and will try to set a non-existent configuration for the project - DebugTest. And as a result, the project can not compile and becomes completely invalid, because the conditional compilation is used in the correct project configuration.

**Comment by Droni** [comment]
I fixed this issue by adding a couple lines of code to Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader. And you can not solve this problem for more than two years.

**Comment by Tejes** [comment]
@Droni Do you mind elaborating on exactly what did you add, maybe in a pull request?
