### ISSUE TITLE
VB IntelliSense reports errors for a VB project while solution builds fine

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn#23644]
**Version Used**: VS 2017 15.5

**Steps to Reproduce**:

1. git clone https://github.com/jeremymeng/TestVB.git
2. start a VS instance
3. open TestVB\TestVB.sln
4. open Class1.vb

**Expected Behavior**:
No errors

**Actual Behavior**:
IntelliSense reports errors for DayOfWeek, DateTime, and BitArray not defined

5. Go to Project Property, Reference Tab, 

**Expected Behavior**:
Some Imported namespaces should have been checked, as specified in the vbproj

**Actual Behavior**:
All shown as unchecked

6. Now try to check `Microsoft.VisualBasic` in the list

** Actual Behavior**:
```
---------------------------
Microsoft Visual Studio
---------------------------
Index was outside the bounds of the array.
---------------------------
OK   
---------------------------
```

7. dismiss the dialog, click on Save All button

** Actual Behavior**:
```
---------------------------
Microsoft Visual Studio
---------------------------
Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
---------------------------
OK   
---------------------------
```

8. dismiss the dialog.  Looks like `.vs` is created and info is cached. From now on everything is fine.

**Comment by Pilchie** [comment]
Dupe of internal bug 533577.

**Comment by Pilchie** [comment]
Sorry - public bug is https://developercommunity.visualstudio.com/content/problem/160241/errors-reported-when-none-exist.html.

**Comment by jeremymeng** [comment]
Thanks @Pilchie. Closing.
