### ISSUE TITLE
TupleElementNames may contain all nulls

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#23651]
`F((x, x))` results in a `BoundConvertedTupleLiteral` where `TupleElementNames = { null, null }` rather than `default(ImmutableArray<string>)`.

**Comment by cston** [comment]
cc @jcouv

**Comment by jcouv** [comment]
From discussion with Chuck, the solution is likely that we should drop the builder for inferred element names if they are all `null` after duplicates have been checked (`RemoveDuplicateInferredTupleNames`).

**Comment by jcouv** [comment]
Fixed in 15.6 preview 3.
