### ISSUE TITLE
Proposal: Make `params` keyword only reserved in method signatures

### ISSUE THREAD

**Issue by DrLeh** [dotnet/roslyn#2365]
As far as I know, `params` can only be used as a keyword in a method signature, so why is it restricted other places? Can `params` be changed so that it's only reserved in the contexts that it's valid for use? There is already a precedent for this with other keywords, like `value` within property setters:

```
void Main()
{
    var params = "Invalid Expression term 'params'"; //why should this be disallowed?
    var value = "totally valid";
}

public string MyProperty
{
    get{ return "";}
    set 
    {
        var value = "A local variable named 'value' cannot be declared in this scope...";
    }
}   

    //whether or not this last example should be allowed is up for debate
    public int ExecuteCommand(string sql, params object[] params){ //identifier expected

}
```

**Comment by HaloFour** [comment]
IIRC none of the original keywords in C# 1.x were contextual, meaning that they couldn't be used anywhere even outside of their specific context.  The spec continues to break down the list between reserved keywords (like `params`) and contextual keywords.  The contextual keywords came later so that the scenarios in which a new language feature would break existing code would be minimized.

To note, you're allowed to use reserved keywords as identifiers by "quoting" them with `@`, e.g.:

```cs
var @params = { 1, 2, 3 };
var @class = "css";
var @event = Party.Time;
```

**Comment by svick** [comment]
@HaloFour C# 1.0 already had `get` and `set`, which are now considered contextual keywords, but it didn't call them that. Quoting from [the C# 1.0 spec](http://download.microsoft.com/download/a/9/e/a9e229b9-fee5-4c3e-8476-917dee385062/CSharp%20Language%20Specification%20v1.0.doc), §2.4.3 Keywords:

> In some places in the grammar, specific identifiers have special meaning, but are not keywords. For example, within a property declaration, the “`get`” and “`set`” identifiers have special meaning. An identifier other than `get` or `set` is never permitted in these locations, so this use does not conflict with a use of these words as identifiers.

**Comment by mburbea** [comment]
Yeah, it would be really nice to be able to use these reserved keywords without the `@`. I'd also recommend `delegate` get the same treatment.

**Comment by thomaslevesque** [comment]
:+1:

Actually, many keywords could be made contextual. It happens quite often that I want to declare a variable named `params`, `event` or `ref`.

**Comment by whoisj** [comment]
> Actually, many keywords could be made contextual. It happens quite often that I want to declare a variable named params, event or ref.

'ref' is about to get a whole lot less contextual. https://github.com/dotnet/roslyn/issues/118

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
