### ISSUE TITLE
VS asks to remove reference to existing solution from the recent list

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#23654]
**Version Used**: VS 15.5 Community

**Steps to Reproduce**:

1. Add new project to solution. Type of project is Windows Classic Desktop Class Library (C#).
2. Do not save the project.
3. Try to open other solution (which does exists) from File - Recent Project and Solutions.
4. Dialog "Save changes to following items" is displayed.
5. Click "Cancel".
6. Dialog is displayed  with text: "xxx.sln" could not be opened. Do you want to remove the reference(s) to it from  the Recent list(s)?

**Comment by JosefPihrt** [comment]
https://developercommunity.visualstudio.com/content/problem/168461/vs-asks-to-remove-reference-to-existing-solution-f.html

**Comment by jcouv** [comment]
Tagging @Pilchie Not sure how to route this issue.

**Comment by Pilchie** [comment]
I moved the internal item tracking the developer community item to the platform team.
