### ISSUE TITLE
Cannot obtain symbol for tuple sequence in foreach

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#23652]
**Version Used**: VS 15.5 Community

**Steps to Reproduce**:

```csharp
void EnumerateTuples(IEnumerable<(int, string)> sequence)
{
    foreach (var (i, s) in sequence)
    {
    }
}
```
I am not able to obtain symbol for 'sequence' in foreach.

**Comment by jcouv** [comment]
A fix was committed recently into 15.6 preview 1.
https://github.com/dotnet/roslyn/pull/22878

Thanks for reporting the issue. I'll go ahead and close as duplicate and fixed.
