### ISSUE TITLE
Generating fields from constructor arguments isn't respecting "this." settings

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#23660]
We have these settings in projectsystem:

```
dotnet_style_qualification_for_field = false:suggestion
dotnet_style_qualification_for_property = false:suggestion
dotnet_style_qualification_for_method = false:suggestion
dotnet_style_qualification_for_event = false:suggestion

```

Yet, generate field from constructor parameter is generating this style:
![image](https://user-images.githubusercontent.com/1103906/33747809-303501a6-dc19-11e7-9764-e97a04ee29dc.png)

**Comment by CyrusNajmabadi** [comment]
"this." is necessary.  Otherwise, the code would be in error (i.e. ```projectServices = projectServices``` isn't legal).  

The qualification rule is about when the user should be told to qualify or unqualify when it would be *legal* to make such a change.  i.e. we won't offer to unquality if that would cause your code to break.

--

Now: it may be the case that you have a naming rule for fields that we're not respecting.  If so, we should definitely do that.

**Comment by CyrusNajmabadi** [comment]
Nope: looks like generating the field respects your field naming settings.  If you have none, we use the general pattern of naming the field the same as your parameter.  And, in that case, "this." is necessary for the code to compile.  If you did have a field naming rule (like "must have _ prefix") you'll see htis behavior:

![image](https://user-images.githubusercontent.com/4564579/33754755-9f8aef10-dba2-11e7-83d9-2aac3bf90ba5.png)


Note the lack of "this." as it isn't necessary.

**Comment by davkean** [comment]
Yep, looks like when I repaired VS it blew away my naming settings.  How do I persist naming settings in EditorConfig?

**Comment by CyrusNajmabadi** [comment]
@kuhlenh or @jmarolf Know where the doc for this lives I think :)

**Comment by Pilchie** [comment]
https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions

**Comment by davkean** [comment]
Thanks, done: https://github.com/dotnet/project-system/pull/3035. Closing this because this behavior is by design.
