### ISSUE TITLE
Grammar.xml layout

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#23674]
Why do the grammar.xml for C# and VB have different node names?
Could they be unified under a single format?

**Comment by CyrusNajmabadi** [comment]
> Why do the grammar.xml for C# and VB have different node names?

Historical reasons.  

> Could they be unified under a single format?

I don't see why not.  But it's also unclear what value that would add.

**Comment by AdamSpeight2008** [comment]
Knowledge learnt changing one language's grammar, is transferable to changing the other's. 
Tools that use the grammar could be made simpler only have to recognise one style of grammar not two.
Also if they share the same format for the grammar it could be added a language service, where we can detects errors at compile time.

**Comment by CyrusNajmabadi** [comment]
> Knowledge learnt changing one language's grammar, is transferable to changing the other's.

Seems marginal :)  I've worked with both, and both are sufficiently clear as to not really benefit that much from knowledge transfer.

> Tools that use the grammar could be made simpler only have to recognise one style of grammar not two.

Sure.  But i would posit that tools should use the actual APIs generated, not the original xml file.

> Also if they share the same format for the grammar it could be added a language service, where we can detects errors at compile time.

**Comment by CyrusNajmabadi** [comment]
IMO, there would be nothing wrong with unifying these.  However, there's also very little value add.  The existing systems serve the needs of the team well, with few problems.  Changing this would just be work for marginal gain.  I doubt hte team would ever sign up for this.  But perhaps they'd take a 3rd party PR if it was done very well.
