### ISSUE TITLE
Consolidate 'remove unused local' fixer in Roslyn and Roslyn-analyzers

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#23684]
See [Roslyn implementation](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs,00b2545738f1c75d,references) and [Roslyn-Analyzers implementation](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/RemoveUnusedLocals.Fixer.cs). Both of these fixer offer removal of unused local/variable.

Note: Fixer in Roslyn-analyzers also removes additional assignments to the variable, while the one in Roslyn just removes the declaration statement. We should port the fixer from roslyn-analyzers to roslyn.

**Comment by ivanbasov** [comment]
Fixed except https://github.com/dotnet/roslyn/issues/24076.
We can plan a workaround for #24076 out of compiler diagnostics for a while.
