### ISSUE TITLE
Workspaces XmlDocumentationProvider should handle redirected XML doc comments

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#23685]
On the Jenkins VS Integration machines (Windows Server 2016?), there are XML doc comment files that contain a "doc redirect" like so:

(From C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.X\mscorlib.xml)
```XML
<?xml version="1.0" encoding="utf-8"?>
<doc redirect="%PROGRAMFILESDIR%Reference Assemblies\Microsoft\Framework\.NETFramework\v4.X\mscorlib.xml" />
```

This is blocking the `TestOpenProject_MetadataReferenceHasDocComments` MSBuildWorkspace test.

**Comment by sanmuru** [comment]
Do we still have this bug in version above [Roslyn 4.5.0 (or VS 2022 v17.5)](https://github.com/dotnet/roslyn/commit/6a5a63bbc9f4449d9bd1e95a8f9624939c3ccdc3)? I run tests and `TestOpenProject_MetadataReferenceHasDocComments` failed with Assert.NotEmpty() Failure (line 2505)

**Comment by CyrusNajmabadi** [comment]
Closing out as we have not gotten broad feedback on this.
