### ISSUE TITLE
[Question] Why does IArgumentOperation.Type return null?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#23687]
I'm working on an IOperation-based analyzer for the roslyn-analyzers repo. I noticed while debugging that `argument.Type` where `argument` is an `IArgumentOperation` returns null, and I tracked it down to [this line](http://source.roslyn.io/#Microsoft.CodeAnalysis/Generated/Operations.xml.Generated.cs,205) which passes null to the Operation ctor. Is this intentional?

**Comment by jcouv** [comment]
Tagging @mavasani

**Comment by mavasani** [comment]
Yes, this is by design and consistent with SemanticModel.GetTypeInfo for ArgumentSyntax node. You should fetch argument.Value.Type.
