### ISSUE TITLE
Space no longer commits override

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#23690]
**Version Used**: 15.6.0 Preview 1

**Steps to Reproduce**:
```C#
class Test
{
    override tos|
}
```
Press space to commit preselected ToString() in the autocompletion list.

**Expected Behavior**: 
`public override string ToString() => base.ToString();` like in previous versions

**Actual Behavior**:
`public override string tos |`

**Comment by sharwell** [comment]
:memo: This behavior appears in both 15.5 and 14.3 (latest Visual Studio 201**5** update) as well.

**Comment by miloush** [comment]
Sorry do you mean the actual or the expected behavior?

**Comment by sharwell** [comment]
@miloush The behavior you describe as "Actual Behavior" is the behavior I observe in the older versions I listed.

**Comment by dpoeschl** [comment]
@rchande Do you happen to know any history here?

**Comment by miloush** [comment]
Hm, both Tab and Enter commit the override so I guess I might have gotten this one wrong.
