### ISSUE TITLE
Passing this to an in parameter crashes

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#23692]
Originally filed by @ufcpp on #23636

```csharp
using System;

static class Ex
{
    public static void InMethod(in X arg) => Console.WriteLine(arg);
}

class X
{
    public void M()
    {
        // pass `this` by in-parameter.
        // `ldind.ref` is not emitted.
        // As a result, ExecutionEngineException is thrown.
        Ex.InMethod(this);
    }
}

class Program
{
    static void Main()
    {
        var x = new X();

        // No problem
        Ex.InMethod(x);

        // throws ExecutionEngineException
        x.M();
    }
}
```

**Comment by OmarTawfik** [comment]
cc @jcouv  and @VSadov

**Comment by OmarTawfik** [comment]
cc @VSadov 
I think we should allow passing `this` by `in` everywhere we allow passing it by val.

**Comment by VSadov** [comment]
Per current design, `this` is not an lvalue in classes. For example you are not supposed to be able to do:

```C#
ref readonly C1 roReference = ref this;
```

If we allow passing `this` as `in` argument, we should also allow passing to `ref readonly` returns and to `ref readonly` locals.  

I think `this` in a class should stay being an rvalue.
- The benefits of passing `this` as a reference are not huge, if there are any at all - it is an object-sized parameter and is typically enregistered (so it would have to be spilled to memory anyways to get a reference to it).
- Relaxing the restriction in the future is not a breaking change, if there are reasons. - As opposed to taking the feature back if it causes problems.

I.E.
```c#
TakesInParameter(in this)   // should fail

TakesInParameter(this)       // should work, pass ref to a copy
```

**Comment by VSadov** [comment]
`ref readonly` returns would not actually work with `this` in classes due to life time issues.

**Comment by tannergooding** [comment]
To confirm, this only applies to classes, correct?

Passing `in this` for a struct should work (and it looks like it does in the current bits)

**Comment by OmarTawfik** [comment]
`If we allow passing this as in argument, we should also allow passing to ref readonly returns and to ref readonly locals.` Can you please explain why? Perf gains (if any) are not the concern here. If you can pass `T obj` to an `in` parameter, so should you be able to pass `this` of type `T` as well.

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/24128
