### ISSUE TITLE
VisalStudioWorkspace's WorkspaceChanged is not called with SolutionAdded kind after full solution load

### ISSUE THREAD

**Issue by ysmoradi** [dotnet/roslyn#23694]
**Version Used**: 
Visual Studio 2017.5

**Steps to Reproduce**:

1. Develop "Package" using VS SDK
```csharp
[ProvideAutoLoad(UIContextGuids80.SolutionExists)]
public class MyPacakge : Package
{}
```
2. In "Initialize" method, Get "VisualStudioWorkspace" using GetService method of component model
3. Subscribe to VisualStudioWorkspace's WorkspaceChanged event

**Expected Behavior**:
WorkspaceChanged gets called by WorkspaceChangeKind.SolutionAdded kind after full solution load. This happens in VS2015.3 to VS2017.4

**Actual Behavior**:
WorkspaceChanged gets called several times with any kind such as ProjectAdded, DocumentAdded etc, but it is not called using SolutionAdded kind

**Comment by Pilchie** [comment]
Tagging @jasonmalinowski, but I think this depends on:

1. The type of projects - .NET Core and .NET Standard projects use the new project system, and initialization happens differently.
2. Whether files were open in the editor when the solution was closed - if so, we fall out of the optimization to initialize the whole solution at once.

I don't expect this has changed in 2017.5.

**Comment by ysmoradi** [comment]
I've developed code generator which relies on Roslyn workspace. At first, it was as easy as getting visual studio workspace from component model. It was working against vs2015.3 to vs2017.2.
It generates codes two times, on solution open and after build.

From vs 2017.3 (without any change in my extension codes) I realized vs workspace is not accurate as before for the first time, so I developed something like this:

If vs workspace is accurate, then use that for code generation, else use ms build workspace. Finally log which of them is used.
Now, if you use vs2015.3 to vs2017.3, you see vs workspace in logs. But in vs 2017.3 to vs 2017.4 it says I'm using ms build workspace for the first time, and vs workspace for the next times!

From vs2017.5, solution open event is not getting fired. All these different behaviors are from happening for a same code of my extension, but different version of vs. And I think it's related to performance optimizations of vs.

My extension is open source at https://github.com/bit-foundation/bit-framework/blob/master/BitTools/BitVSExtensionV1/BitPackage.cs and I'm ready to provide any info you want.

Thanks in advance

**Comment by jasonmalinowski** [comment]
Indeed, the contract has never been that SolutionAdded will be called; it's both normal and acceptable for you to get individual projects adds. The goal of the workspace here is we try to defer adding until as late as possible; ideally we do it in one single batch but we sometimes have to break up batches. As @Pilchie mentions it's really subtle what can cause that to change -- reopening existing solutions will change batching behaviors, whether you had various async models, etc.

@ysmoradi Can you clarify why you're using this approach for code generation as opposed to integrating into the MSBuild pipeline? The workspace model _really_ isn't intended for such use.

**Comment by ysmoradi** [comment]
Code generator itself accepts Roslyn "Workspace". We use Workspace because it provides both syntax and metadata, so as we're enumerating methods of our classes using an approach similar to reflection, we've access to their comments too as an example, that's awesome.

Loading and updating Workspace is not a cheap operation. We've large enterprise projects with hundreds of developers. Visual studio is creating a "VisualStudioWorkspace" and it's getting updated based on solution changes. So the cost of creating and updating workspace is already paid, with or without our extension. In msbuild task, I've no access to that workspace, so I've to use MsBuildWorkspace or other cross platform workspaces out there on GitHub, This increases code generation time from 100ms to 23s for every build! We also run code generation on solution open and we're going to run that on git pull and branch change events when we find their events in visual studio sdk. Our goal is keeping our generated typescript definition close to latest CSharp changes, even before build.

So, I change my code to make it compatible with new changes of vs 2017.5 

I created this issue to inform you about behavioral changes of vs. I understand that having no breaking change at any level is not possible at all. Let me know in case you've any advice for me or any question from me. :)

**Comment by jasonmalinowski** [comment]
@ysmoradi I'm going to close this issue then under the understanding that [a] you've fixed the issue on your side and [b] that this behavior is expected, so there's nothing to really fix here. Let me know if I'm misunderstanding.
