### ISSUE TITLE
Code action which selects text

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#237]
I want to create a code action in my `CodeFixProvider` which causes particular text to be selected in the editor. Is this possible?

Note: this is not a rename operation, and not on a symbol, so adding a `RenameAnnotation` to the node does not work.

The proposal would be to add a `SelectionAnnotation`, which is used similar to `RenameAnnotation` but instead of triggering a rename operation it just sets the text selection.

```csharp
namespace Microsoft.CodeAnalysis.CodeActions
{
    /// <summary>
    /// Apply this annotation to an appropriate SyntaxNode to request that it should be selected in the IDE after
    /// the action.
    /// </summary>
    public static class SelectionAnnotation
    {
        public const string Kind = "CodeAction_Selection";
 
        public static SyntaxAnnotation Create();

        /// <summary>
        /// Creates a selection annotation which selects a subspan within a syntax node to which the annotation is
        /// applied. The index is calculated relative to the start of the <see cref="SyntaxNode.FullSpan"/> of the
        /// syntax node.
        /// </summary>
        public static SyntaxAnnotation Create(int index, int length);
    }
}
```

**Comment by jaredpar** [comment]
Can you give us a bit more context?  What would be the purpose of such an action?  I tend to think of code actions as items which affect the code, selection just effects the editor view.

**Comment by jmarolf** [comment]
Its possible if you are fine with your codefix not being portable and importing services from visual studio.  Anything that can be done in an extension could be done in your code fix under those circumstances.  Understand that we provide no api for this, you would be opting to use the visual studio editor apis.

**Comment by sharwell** [comment]
In addition to the "Finalize placeholder text" action in https://github.com/openstacknetsdk/OpenStackNetAnalyzers/issues/10, I want to provide an "Edit placeholder text" action which selects the placeholder (including the start and end tag). Currently it's frustrating to select that span of text to replace it.

**Comment by CyrusNajmabadi** [comment]
Closing out.  Needs to go through actual API process to make forward progress on this.

**Comment by sharwell** [comment]
Added a proposed API for this

**Comment by CyrusNajmabadi** [comment]
Closing out as this is an api request with no owner.  If you want this, drive this through.
