### ISSUE TITLE
Call to extensions methods using dynamic keyword build time.

### ISSUE THREAD

**Issue by malylemire1** [dotnet/roslyn#23725]
**Version Used**: 
Visual Studio 2017 15.5

**Steps to Reproduce**:
1. Create an extension method for a specific type. (For 100 types with overloads for each types.)
2. Call the extension using dynamic (In other 100 class.)

**Expected Behavior**:
Build time should be 12 seconds.

**Actual Behavior**:
Build time goes from 12 seconds to 2 minutes.
VBCSCompiler take 100% of the CPU.
There is many line of code in the 100 classes that call the extension method.
If I comment the call to the extension using dynamic, build time goes back to 12 seconds.

**Comment by jcouv** [comment]
@malylemire1 Thanks for reporting this. I didn't fully understand however.
Would you mind sharing the code that you used, or a representative snippet?

**Comment by jaredpar** [comment]
Closing as this issue has gone stale.
