### ISSUE TITLE
VBCSCompiler hangs in CLI build

### ISSUE THREAD

**Issue by livarcocc** [dotnet/roslyn#23734]
PR is here: https://github.com/dotnet/cli/pull/8214.

When I tried this branch locally on OSX, the first time we build something using the VBCSCompiler, it actually hangs. If I kill that process, then the build progresses until the next compilation, compiles but then hangs again.

You should be able to repro it by simply checking out that branch and running build.sh. I haven't tried on Windows yet.

**Comment by jcouv** [comment]
Tagging @khyperia as FYI

**Comment by jaredpar** [comment]
@livarcocc are you using any analyzers on the OSX build? I just ran into a problem where I needed to disable them when building on OSX. Symptoms were essentially a hang.

**Comment by nguerrera** [comment]
I think our reference to xunit pulls in analyzers.

**Comment by jaredpar** [comment]
@nguerrera that is likely what is going wrong here then. Here is the issue we're using to track this on Roslyn. @khyperia is looking into it.

https://github.com/dotnet/roslyn/issues/23736

**Comment by nguerrera** [comment]
I've submitted https://github.com/dotnet/cli/pull/8221 to check if disabling analyzers would cause the build to succeed.

**Comment by nguerrera** [comment]
Note that our builds are timing out on Linux too and not just Mac.

**Comment by jaredpar** [comment]
Hmm. Definitely not seeing that. Our Linux runs are the most reliable runs we have. 

Hopefully digging into the Mac failure will uncover a bug that affects both that we're just getting around by some accident.

**Comment by nguerrera** [comment]
Nevermind, dotnet/cli#8221, I thought that bool was in the product targets that pass analyzers to the compiler, but it's not. Turns out it's not easy to disable analyzers across our build.

**Comment by agocke** [comment]
I found one bug here, but it only occurs on Mac and doesn't seem like the bug that's blocking CLI. I'm still investigating to figure out the root cause of the CLI hang.

**Comment by livarcocc** [comment]
@agocke thanks for the update.

**Comment by nguerrera** [comment]
Wild guess, but one thing different about CLI is that the runtimeconfig is altered to run the compiler on the 2.1 runtime.

**Comment by agocke** [comment]
Looking into this more, I'm seeing some strange stuff going on inside MSBuild. The chain of events seems to be

1. MSBuild is running 'pack'
2. MSBuild kicks off some intermediate processes to run the build.
3. Compiler server logger shows build (compile) happened successfully and result was returned.
4. Intermediate processes exit.
5. Now it looks like MSBuild is sitting around in HandleToolNotifications waiting on a process that, based on the process handle, has already exited.

Has MSBuild had any changes recently to this area?

**Comment by nguerrera** [comment]
@rainersigwald @AndyGerlicher @cdmihai ^

**Comment by agocke** [comment]
To add some more detail, the process it is waiting for is definitely the "dotnet pack" execution -- it looks like this is the parent msbuild process and it kicked off "pack" and is now waiting for it to come back. The Process class's info shows that the process has already exited with a return code of 0.

I can also repro the behavior where killing the compiler server continues executing. Is it possible that the processes are somehow reparenting to the parent process and we're waiting on all of the descendent processes to exit instead of just the first one?

**Comment by agocke** [comment]
More info: it looks like the process is stalled waiting for EOF from the output or error stream of the pack process.

**Comment by agocke** [comment]
I believe I've found the cause and have a PR out to fix this issue.

**Comment by livarcocc** [comment]
@agocke What version should we use to try this out again on the CLI?

**Comment by jaredpar** [comment]
We should try with 2.7.0-beta3-62419-03

https://github.com/dotnet/versions/blob/master/build-info/dotnet/roslyn/dev15.6p3/Last_Build_Packages.txt

**Comment by nguerrera** [comment]
I've updated https://github.com/dotnet/cli/pull/8214 to 2.7.0-beta3-62419-03

**Comment by nguerrera** [comment]
It's green. Nice work.
