### ISSUE TITLE
"Use auto properties" code fix produces invalid code for explicitly implemented interface properties

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#23735]
**Version Used**: 
Microsoft Visual Studio Enterprise 2017 Preview
Version 15.6.0 Preview 1.0

**Steps to Reproduce**:

1. Load the following code in the editor:

```cs
namespace RoslynSandbox
{
	public interface IFoo
	{
		object Bar { get; }
	}

	class Foo : IFoo
	{
		public Foo(object bar)
		{
			this.bar = bar;
		}

		readonly object bar;

		object IFoo.Bar
		{
			get { return bar; }
		}
	}
}
```

2. Note that line 15 (`readonly object bar;`) is greyed out.
3. Click on line 15
4. Select the lightbulb
5. Select "Use auto properties"

**Expected Behavior**:

The code fix should either produce workable code, or not be offered.

**Actual Behavior**:

The resulting code is invalid and does not compile:

```cs
namespace RoslynSandbox
{
	public interface IFoo
	{
		object Bar { get; }
	}

	class Foo : IFoo
	{
		public Foo(object bar)
		{
			this.RoslynSandbox.IFoo.Bar = bar;
		}

		object IFoo.Bar { get; }
	}
}
```

**Comment by MaStr11** [comment]
@yaakov-h 

> **Expected Behavior:**
> The resulting code is valid C# and compiles.

I can't think of any "Use auto properties" solution for explicit implemented interface properties. The expected behavior should be "Don't offer *Use auto properties*" therefore (But maybe I'm wrong and you can come up with a counterexample code sample).

**Comment by yaakov-h** [comment]
For read/write properties you could cast this to the interface, but I don’t see any possible solution for getter-only autoproperties. 

But yes, that’s kind of what I meant, but did not say.

A code fix should either produce workable code, or not be offered. There should not be a case where a code fix produces unworkable code. 

(If there is, it should be called a code break. 😁)

**Comment by CyrusNajmabadi** [comment]
PRs welcome :)   Should be easy to fix.

**Comment by MaStr11** [comment]
Related discussion #3342 *Should it be possible to use getter-only auto-properties to explicitly implement an interface property?*
