### ISSUE TITLE
When Roslyn fails it should format callstacks to enter the build's error log

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/roslyn#23743]
Version  2.6.0-beta3-62316-02. Commit Hash: fbe99784a6b17a4aa8b35e5068d01b3c18a4e1d6

Roslyn crashed (in this case due to bad install on my box) and this is all I get in the MSBuild error log and in the console (which is filtering to errors):
```
  91:2>C:\git\corefx\Tools\net46\roslyn\tools\Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.exe" exited with code -532462766. [C:\git\corefx\src\System.Memory\ref\System.Memory.csproj]
```

In the full log is the real information:

```
    34>CoreCompile:
         Using shared compilation with compiler from directory: C:\git\corefx\Tools\net46\roslyn\tools
         
         Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Access is denied.
            at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args)
            at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
    34>C:\git\corefx\Tools\net46\roslyn\tools\Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.exe" exited with code -532462766. [C:\git\corefx\src\System.Collections.Memory\ref\System.Collections.Memory.csproj]
```

This output should be in the error log. To achieve that every line of the console output must be in the same format CSC uses for compilation errors, eg:

```
CSC: error CS0000 : Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Access is denied.
CSC: error CS0000 :             at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args)
CSC: error CS0000 :             at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
```

The initial CSC can be replaced with a path if you have a useful one.

To achieve this you will have to have an exception handler somewhere near the top of the stack (MainCore perhaps) that does this wrapping, then Console.Write's the result of ex.ToString() with each line prefixed, then rethrows it for Watson/debuggers.

When you rethrow, you should do it with `ExceptionDispatchInfo.Capture(ex).Throw();` instead of `throw ex;` because it will not reset the callstack.

**Comment by jaredpar** [comment]
> When you rethrow, you should do it with ExceptionDispatchInfo.Capture(ex).Throw(); instead of throw ex; because it will not reset the callstack.

Why not just use `throw;`? Not sure what the API does here over htat.

**Comment by danmosemsft** [comment]
You're right `throw;` is fine.

**Comment by danmosemsft** [comment]
Not always getting the callstack for some reason, but still, the exception message should still get the prefix so it appears in less than detailed verbosity. Fundamentally the issue is in normal verbosity (the default) and below, the MSBuild console and file loggers drop all console output that does not match the error warning format. So if you build with "msbuild" and therefore have the default logger settings, it is completely lost.

Perhaps if a spawned tool fails, MSBuild should retrospectively dump all its console output...

```
  C:\git\corefx\Tools\net46\roslyn\tools\csc.exe .......
  Using shared compilation with compiler from directory: C:\git\corefx\Tools\net46\roslyn\tools (TaskId:35)
  Could not load file or assembly 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. (TaskId:35)
C:\git\corefx\Tools\net46\roslyn\tools\Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.exe" exited with code 1. 
```

**Comment by agocke** [comment]
@jaredpar `throw` does not work. It only preserves the stack information -- it destroys the locals.

**Comment by danmosemsft** [comment]
@agocke can you clarify -- are you saying that if I have a JIT debugger attached, and it breaks on a `throw;` statement, the locals have been modified by the `throw;` statement?

**Comment by agocke** [comment]
If you catch an exception, then rethrow that exception (the `rethrow` IL instruction), and later turn that into a crash dump, that dump will no longer contain information about the local variables from the stack that caused the original exception.

**Comment by svick** [comment]
I think this is related to https://github.com/dotnet/roslyn/issues/21814.

**Comment by jaredpar** [comment]
@svick agree. Going to dupe that one against this.

**Comment by jaredpar** [comment]
This should be done now.
