### ISSUE TITLE
VS 15.5 option strict error

### ISSUE THREAD

**Issue by vbcodec** [dotnet/roslyn#23768]
There is some bug, that VS do not recognize that Option Strict is OFF
Steps to reproduce
- in VS create VB console app,, make sure that Option Strict is Off in project page -> Compile, and write code
` Dim x As Integer = "0"`
- aave project and solution, exit VS
- run VS again, load console project, and error will appear

**Comment by Pilchie** [comment]
This is https://developercommunity.visualstudio.com/content/problem/160746/errors-big-time-when-visual-studio-2017-community.html - the value is getting set wrong by the IDE.

We're working on a hotfix.
