### ISSUE TITLE
Opening up the pattern matcher?

### ISSUE THREAD

**Issue by cartermp** [dotnet/roslyn#23770]
We currently have a copy of the pattern matching source and all of its supporting code in the Visual F# tools codebase: https://github.com/Microsoft/visualfsharp/tree/master/vsintegration/src/FSharp.LanguageService.Base/PatternMatcher

There are a two problems with this:

1. The source uses Roslyn-isms which necessarily tie it to only one part of our codebase; we cannot port this over to our own language service, because our language service is used in other editors which don't use Roslyn.
2. We likely won't be getting any future bug fixes in this.

Can we open this up for consumption? cc @DustinCampbell

**Comment by olegtk** [comment]
Starting with 15.6 the editor exposes its own copy of the pattern matcher in Microsoft.VisualStudio.Text.Logic.dll. Can you try migrating to it please? It's in Microsoft.VisualStudio.Text.PatternMatching namespace.

**Comment by cartermp** [comment]
We currently depend on VS.VS.Text.Logic via package.  Is this available on NuGet?

**Comment by cartermp** [comment]
Closing this in favor of the VS pattern matching service.  Will track on VF# side

**Comment by CyrusNajmabadi** [comment]
@olegtk Have we compared the editor version vs the Roslyn version?  Roslyn got a lot of perf changes there near the end of 15.5.  It wouldbe good if they could be rolled into the platform.
Thanks!
