### ISSUE TITLE
Overload resolution bug when calling params method from derived class

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#23777]
**Version Used**: Visual Studio 15.5.1

**Steps to Reproduce**:

```cs
    class B
    {
    }

    class C
    {
        void M(B b, params object[] args)
        {
        }

        /*
        void M(params object[] args)
        {
            // Correctly picks up on M(B, object[])
            M(new B(), args);
        }
        */
    }

    class D : C
    {
        void M(params object[] args)
        {
            // Wrongly picks up on M(object[]), leading to StackOverflowException
            M(new B(), args);
        }
    }
```

I picked up this bug while working on an analyzer, funnily enough. Here's the code where I actually ran into the bug: https://github.com/jamesqo/roslyn-analyzers/blob/7b686d8ac75b9f555a2e87417be45c37a3ad79f3/src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotMixBlockingAndAsyncTests.Fixer.cs#L34-L42. I was able to work around it by using named parameters.

**Comment by zaytsev-victor** [comment]
@jamesqo It is language spec "...methods in a base class are not candidates [for overload resolution] if any method in a derived class is applicable". [12.6.4 Overload resolution](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-334.pdf)

**Comment by jaredpar** [comment]
Agree this is by design.
