### ISSUE TITLE
AnalyzerDependencyCheckingService.CheckForConflictsAsync results in 15 seconds of blocked UI opening Roslyn

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#23775]
**Version Used**: 
Visual Studio 2017 version 15.5

**Steps to Reproduce**:
1. Open a large solution where there are analyzer diagnostics in a "leaf" project.

**Expected Behavior**:
Solution should open in a reasonable time

**Actual Behavior**:
It's very slow, because creating the diagnostic requires a full compilation to be built and then examined for source level suppressions, and this happens synchronously on the UI thread as part of solution load.

`microsoft.visualstudio.languageservices   <<microsoft.visualstudio.languageservices!Microsoft.VisualStudio.LanguageServices.Implementation.AnalyzerDependencyCheckingService+<CheckForConflictsAsync>d__14.MoveNext()>> | 11.2 | 9,363.414 | 4,087`

**Comment by davkean** [comment]
Project & Telemetry reached out to us, this is causing 15 of 50 seconds of block UI opening Roslyn.sln.

**Comment by mavasani** [comment]
I'll look at it now...
