### ISSUE TITLE
Test plan for slicing/Range feature

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#23789]
This is a placeholder to track test ideas and open issues.

We should be able to finalize Range API by end of Jan (including review with LDM), so the implementation can be completed in Feb.

Various aspects of proposal:
- Specific vs. generic types: It may be possible to do a generic Range<T> and still implement some enumerables on it (via extensions), but we’re strongly leaning towards specific types (either 1 or 2). Range would be `int`. LongRange would be `long`.
- End included vs. excluded: In `foreach (var i in 1..10)` it makes sense for 10 to be excluded. In `5.in(1..10)` it makes some sense for 10 to be included. Overall, we’re leaning towards excluding the End.
- Start+End vs. Start+Length: Strong preference for start+end to conform to language syntax and other languages.
- Upwards-only vs upwards+downwards

Test ideas:
- [ ] `foreach (var i in 10..0) // decreasing`
- [ ] The `ForEachToFor` refactoring should recognize range syntax

Various links:
- [PR](https://github.com/dotnet/corefxlab/pull/1979) for Range type
- [Another PR](https://github.com/dotnet/corefxlab/pull/1981) for Range type
- Champion issue: https://github.com/dotnet/csharplang/issues/185

**Comment by YohDeadfall** [comment]
I've found that the generic type can not be used for enumerating such things like DateTime because the distance is measured by TimeSpan and not by DateTime.

So if there are specific types should the range type for int be called IntRange? Because for math computations probably will be DoubleRange, for DateTime - DateTimeRange, and so on.

**Comment by AdamSpeight2008** [comment]
Please make Range to be (Inclusive, Inclusive), as to me is indicative of a starting point and an end point.
eg `Starting Line and Finishing Line` or `Frequency Range: 88 MHz To 108MHz`
To me, a Span is indicative of a starting point and length covered.
eg `Frequency Span:  +/-20MHz @ 90MHz `

Making it exclusive also means the full range of values isn't available especially the `.MinValue` and `.MaxValue`, making it inclusive doesn't.
The enumerator for inclusive is relatively simple to write, including the support for step values. Thus giving an alternate to for loops.
 
If you want syntax support for Span, use a different symbol .
```
'  RANGE
syntax RangeExpression ::=
   ( lower : ExpressionSyntax ) [To] ( upper : ExpressionSyntax ) ?( step : StepExpression);
syntax  StepExpression ::= [Step] ( expr : Express );
' SPAN
syntax Span    ::= ( field start) ( field length);
syntax Span<T> <: Span ::= ( field source );
syntax Span<T,S> <: Span<T> ::= ( field Step );
```
example 
```c#
' span = index :: length
span s = 0 :: 10;
span<char> = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"[s]; 'eg ABCDEFGHIJ 
```
```vb
Dim r = 0 To 9 Step 3 ' eg 0 3 6 9
```

**Comment by AdamSpeight2008** [comment]
Alternatively name it `Mem<T>` or **'Slice<T>`** for slicing section of memory or collection.

**Comment by BreyerW** [comment]
Couldn't be possible to provide generic range and specialized one for Time-related stuff which would be silently switched by compiler if possible when compiler see Time-related class? As was mentioned, Range seems to be very useful in many scenarios not only strictly numerical, like `char`. I'm a bit concerned that current solution may lead to peculiar "code explosion". If that not possible, at least consider adding those two ranges AND pattern reconizable by compiler like struct based Enumerable. This way at least, we programmers will have control over how much ranges there will be and you will never have to bother with considering yet another use case (`char`? `DateTime`? custom, in-house classes? etc.) for Range pattern in future.

**Comment by jcouv** [comment]
Closing in favor of https://github.com/dotnet/roslyn/issues/23205
