### ISSUE TITLE
[Proposal] try/catch expressions

### ISSUE THREAD

**Issue by saleyn** [dotnet/roslyn#23790]
I have a feature request to convert try/catch statements to expressions similarly how it's done in C# 7.x.  Additionally, when used with code blocks, the last value is returned as the result of the expression:

Example:

- Current:
```c#
string a;
try
{
  a = SomeFunctionThatMightThrow();
}
catch (Exception a)
{
  Print(e);
  a = DefValue;
}
```

- Proposed:
```c#
var a = try { SomeFunctionThatMightThrow(); } catch (Exception e) { Print(e); DefValue; };
var b = try { SomeFunctionThatMightThrow(); } catch { DefValue };
var c = try   SomeFunctionThatMightThrow();   catch DefValue;
```

**Comment by jcouv** [comment]
@saleyn Language design discussions have moved over to the csharplang.
What you describe sounds much like https://github.com/dotnet/csharplang/issues/980
I'll go ahead and close this issue as duplicate. Feel free to continue the discussion there.
