### ISSUE TITLE
[Question] How can I check if a ITypeSymbol is a readonly struct?

### ISSUE THREAD

**Issue by sonnemaf** [dotnet/roslyn#23792]
I'm trying to create a Roslyn Analyzer which checks whether an InParameter is defined on a non-readonly valuetype (from C# 7.2). I can't find a way to check if an ITypeSymbol is readonly. 

I tried the GetAttributes() method. I expected to have the IsReadOnlyAttribute but it doesn't. It is empty.

`
private static bool IsReadonly(ITypeSymbol type) {
    return type.GetAttributes().Any(a => a.AttributeClass.GetType().FullName == "System.Runtime.CompilerServices.IsReadOnlyAttribute");
}
`

Any suggestions?

I published my code on: [Gist](https://gist.github.com/sonnemaf/0001b88db198be33d83f346a47ad874f)

**Comment by jcouv** [comment]
Tagging @OmarTawfik @VSadov for this question

**Comment by VSadov** [comment]
I do not think there is a public API to retrieve that. (We should add that).

If this is a blocking issue, you may try using SymbolDisplay.ToDisplayParts. I think it will put a `readonly` display part for readonly structs.

This is not an ideal solution, but might be sufficient for your scenario.

**Comment by sonnemaf** [comment]
I have tried the SymbolDisplay.ToDisplayParts() solution but it doesn't return any readonly display part. I hope you will add a public 'IsReadonly' API soon. For now I'm stuck.

**Comment by HellBrick** [comment]
I've hit the lack of `ITypeSymbol.IsReadOnly` too. As a workaround, it's possible to use reflection / code generation to get the value of internal [`TypeSymbol.IsReadOnly`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/TypeSymbol.cs,624) property, but it would definitely be nice to have this exposed publicly and avoid relying on Roslyn internals.

(In the meantime, if anyone else stumbles upon this issue, [here's an implementation of the workaround](https://github.com/HellBrick/HellBrick.Diagnostics/blob/master/src/HellBrick.Diagnostics/Utils/ITypeSymbol.IsReadOnlyStruct.cs).)

**Comment by OmarTawfik** [comment]
@jaredpar doing some clean up, and apparently I cannot reassign my bugs if I'm no longer an owner here :(
Want to make sure this is not forgotten. can you please triage accordingly?

**Comment by sonnemaf** [comment]
Does anybody know when I can use the ITypeSymbol.IsReadOnly property in my Analyzer. Will it be shipped in the Microsoft.CodeAnalysis NuGet package soon? I can't wait to have it.

**Comment by RikkiGibson** [comment]
The API should ship in dev16.1 preview 2.

**Comment by sonnemaf** [comment]
@RikkiGibson 

I have just installed VS2019 Preview 2 and update the NuGet packages to the latest (preview) versions. I can still not find the IsReadOnly property on ITypeSymbol. Can you tell me what I'm doing wrong?

![image](https://user-images.githubusercontent.com/9335559/56645420-ee82b780-667d-11e9-9869-bc83821d236d.png)

I have the following NuGet packages in my Analyzer project.

```
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="2.9.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.1.0-beta1-final" PrivateAssets="all" />
    <PackageReference Update="NETStandard.Library" PrivateAssets="all" />
  </ItemGroup>
```

Thanks,

Fons

**Comment by RikkiGibson** [comment]
Roslyn version 3.2.0 corresponds to VS 16.1 preview2. So if you update your CSharp.CodeAnalysis packages to that you should start seeing it.

**Comment by RikkiGibson** [comment]
Looks like this version isn't on NuGet yet. I would expect 3.1.0-beta2-final to get added there very soon.

For the immediate term you can try including this MyGet version in your project: https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.CSharp.Workspaces/3.1.0-beta2-19223-12

**Comment by RikkiGibson** [comment]
FYI 3.1.0-beta2-final is now available. Thanks @JoeRobich.

https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Workspaces/3.1.0-beta2-final

**Comment by sonnemaf** [comment]
Thanks a lot. It just tested the 3.1.0-beta2-final. It works great.

**Comment by RikkiGibson** [comment]
Excellent. I'll consider this issue resolved. Feel free to reopen if you have any issues with this API.
