### ISSUE TITLE
no longer support msbuild14?

### ISSUE THREAD

**Issue by watashiSHUN** [dotnet/roslyn#23806]
I don't see any code change related to this https://github.com/dotnet/roslyn/commit/09330816fc4d598b117cc95dd1ac18d30eb7f3be why are we updating the toolversion for 2.6.0? is 2.4.0 the last version where msbuild14 user can depend on if we are interested in C#7 features? link to affected issue: https://github.com/projectkudu/kudu/issues/2350

**Comment by jmarolf** [comment]
See https://github.com/dotnet/roslyn/issues/19128.  Versions 1.* were the only ones that supported MSBuild 14.0.  All of the 2.0 versions require MSBuild 15.0 to function correctly

**Comment by jaredpar** [comment]
Closing as a dupe
