### ISSUE TITLE
[ComImport] makes parameter list refs optional

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23828]
The C# code below unexpectedly compiles instead of giving &quot;Argument &lt;n&gt; must be passed with the 'ref' keyword&quot; errors.  Commenting out the [ComImport] line reinstates the errors.  (VS Pro 2017 v15.4.1)

using System;
using System.Runtime.InteropServices;

namespace MissingRefsCompilationOddity
{
    [ComImport, Guid(&quot;12345678-1234-1234-1234-1234567890ab&quot;)]
    interface IDC
    {
        bool GetRange(ref int min, ref int max);
    }

    class Program
    {
        static void Main(string[] args)
        {
            IDC dc = null;
            int min = 0;
            int max = 0;

            // why does this line compile?
            dc.GetRange(min, max);

            dc.GetRange(ref min, ref max);
        }
    }
}

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/137108/comimport-makes-parameter-list-refs-optional.html
VSTS ticketId: 513888_
_These are the original issue comments:_

Andy Gocke [MSFT] on 11/6/2017, 07:31 PM (40 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by ufcpp** [comment]
by-design
https://blogs.msdn.microsoft.com/samng/2009/06/16/com-interop-in-c-4-0/
