### ISSUE TITLE
OperationAction(OperationKind.Argument) is not invoked on generic ref this argument

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#23826]
**Version Used**: 

VS 15.5.2
Microsoft.CodeAnalysis.CSharp.Workspaces 2.6.0

**Steps to Reproduce**:

1. analyzer: `RegisterOperationAction(action, OperationKind.Argument)`
2.  source code: invoke an extension method
  - non-generic by-val: `public static void X(this DateTime x) { }`
  - non-generic by-ref: `public static void X(ref this DateTime x) { }`
  - generic by-val: `public static void X<T>(this T x) { }`
  - generic by-ref: `public static void X<T>(ref this T x) { }`

Sample Code: https://gist.github.com/ufcpp/6ba6d1314d9d12720f2c8747a6319654

This sample analyzer always report error diagnostics for `Argument` operation. The `DateTime.Now.X()` should be error.

**Expected Behavior**:

All of 4 source codes report 1 error diagnostics.

https://gist.github.com/ufcpp/6ba6d1314d9d12720f2c8747a6319654#gistcomment-2294496

**Actual Behavior**:

Generic by-ref this argument is not reported. `Argument` operation is not invoked on `public static void X<T>(ref this T x) { }`.

**Comment by jcouv** [comment]
Tagging @mavasani @AlekseyTs @VSadov

**Comment by mavasani** [comment]
@genlu

**Comment by mavasani** [comment]
@ufcpp Can you also check that there are no compilation diagnostics? Also, can you convert it to OperationBlock analyzer and try to see the root operation tree to confirm whether or not we have an invocation operation and argument operation in the tree?

**Comment by ufcpp** [comment]
@mavasani 
Oh, I've found a bug.

https://gist.github.com/ufcpp/6ba6d1314d9d12720f2c8747a6319654/revisions#diff-a97bcd0d075eb5149fa9826d8da18bbe

Adding `where T : struct` solves the issue.

Thanks.
