### ISSUE TITLE
Property ref get crash

### ISSUE THREAD

**Issue by phillyai** [dotnet/roslyn#23833]
**Version Used**: 
Microsoft Visual Studio 2017, Version 15.5.2
C# 7.2
**Steps to Reproduce**:

1. Write `ref get;` in any property

**Expected Behavior**:
It was just mistake, I just wanted to know can I make property getter as ref return.
**Actual Behavior**:
Visual studio just get crashed.

**Comment by ulln** [comment]
https://aloiskraus.wordpress.com/2017/12/17/crashing-vs2017-15-5-2/

https://developercommunity.visualstudio.com/content/problem/168027/typing-ref-readonly-at-the-wrong-places-will-crash.html

**Comment by jcouv** [comment]
Here's how you declare such a property:  `ref int P { get { ... } }`

Tagging @OmarTawfik @VSadov for crash.

**Comment by OmarTawfik** [comment]
It appears to be a bug in the parser. It gets stuck in an infinite loop in `LanguageParser.ParseAccessorList(bool)`. Will look into it.
