### ISSUE TITLE
Provide API to determine whether one symbol is accessible within another symbol

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#23842]
The code fix I'm writing needs to be able to distinguish whether an attribute constructor is accessible from a property or not. This method does precisely what I need, but it's in an internal class.

https://github.com/dotnet/roslyn/blob/69e99a8ba2a044fcf73339ea7d11e2a51975d11d/src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions_Accessibility.cs#L13-L16

Would you please make this method available in the public API?

**Comment by jnm2** [comment]
It's also in Microsoft.CodeAnalysis.Workspaces which is problematic. My analyzer has `typeof(Workspace)` and this causes CSC to try and fail to load `Microsoft.CodeAnalysis.Workspaces.dll` from `%VS%\MSBuild\15.0\Bin\Roslyn`.

**Comment by jmarolf** [comment]
tagging @DustinCampbell

**Comment by jnm2** [comment]
What's your strategy going to be in general for moving analysis APIs from `Microsoft.CodeAnalysis.Workspaces` to `Microsoft.CodeAnalysis`?

**Comment by jnm2** [comment]
The reason that I ask is that I have to move forward with this analyzer, and @tmeschter strongly advised copying all the logic rather than packing `Microsoft.CodeAnalysis.Workspaces.dll` in the analyzer nupkg together with using reflection. (That approach was working and I'm still not sure what would do wrong, but I believe you.)

The copy-all-the-internal-source approach requires adding `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>` to the .csproj and adding these files:

```
src/Compilers/Core/Portable/InternalUtilities/ArrayExtensions.cs
src/Compilers/Core/Portable/InternalUtilities/EnumerableExtensions.cs
src/Compilers/Core/Portable/InternalUtilities/ExceptionUtilities.cs
src/Compilers/Core/Portable/InternalUtilities/Hash.cs
src/Workspaces/Core/Portable/Shared/Extensions/IAssemblySymbolExtensions.cs
src/Workspaces/Core/Portable/Shared/Extensions/IParameterSymbolExtensions.cs
src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs
src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions_Accessibility.cs
src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs
src/Workspaces/Core/Portable/Shared/Extensions/MethodKindExtensions.cs
src/Workspaces/Core/Portable/Shared/Utilities/SymbolEquivalenceComparer.cs
src/Workspaces/Core/Portable/Shared/Utilities/SymbolEquivalenceComparer.AssemblyComparers.cs
src/Workspaces/Core/Portable/Shared/Utilities/SymbolEquivalenceComparer.EquivalenceVisitor.cs
src/Workspaces/Core/Portable/Shared/Utilities/SymbolEquivalenceComparer.GetHashCodeVisitor.cs
src/Workspaces/Core/Portable/Shared/Utilities/SymbolEquivalenceComparer.ParameterSymbolEqualityComparer.cs
src/Workspaces/Core/Portable/Shared/Utilities/SymbolEquivalenceComparer.SignatureTypeSymbolEquivalenceComparer.cs
src/Workspaces/Core/Portable/Utilities/Contract.cs
```

And heavy editing of these files:
```
src/Compilers/Core/Portable/InternalUtilities/EnumerableExtensions.cs
src/Workspaces/Core/Portable/Shared/Extensions/IParameterSymbolExtensions.cs
src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs
src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs
```

Getting it working burned two hours.

These are important APIs. Analyzers need to be able to see the type system the way VS sees it.

**Comment by CyrusNajmabadi** [comment]
I'm not opposed to these APIs being made available.  But if they are, they need to go through the full public API pass since they can't change once we do this.  They woudl also need a full vetting for correctness**, as well as a full test suite provided.

That said, there are several items listed above that i would not ever want to make public.  For example:
ArrayExtensions/EnumerableExtensions/Hash/etc.  These are not extensions exposing roslyn functionality. 

--

Also, if we did expose, these would need heavy editing.  For example: IParameterSymbolExtensions.RenameParameter would end up exposing the entire CodeGenSymbolXXX api to the world.  That API is not at all ready for 3rd party consumption.  


** For example: ISymbolExtensions.IsAccessibleWithin has not at all been tested to be correct across both VB and C#.  It's intended to be a 'good enough' for IDE purposes.  Indeed, you can imagine most of these extensions shoudl be named .XXX_ButJustGoodEnoughForIDEPurposes_HasnotReallyBeenVettedOrVerifiedToMatchTheActualLanguageSemantics

In that regard, moving to the compiler layer seems like it would be an odd decision.

**Comment by CyrusNajmabadi** [comment]
> The analyzer decides whether or not to report a diagnostic depending on IsAccessibleWithin, so the logic must run outside the IDE.

This is also problematic as many extensions need the workspace.  For example ITypeSymbolExtensions uses the workspace so it can give type symbol information across the solution context.  This is not a concept the compiler layer has *at all*.

**Comment by jnm2** [comment]
> That said, there are several items listed above that i would not ever want to make public.

To be clear: only `ISymbolExtensions.IsAccessibleWithin` would become public.

This is all that would have to move from ITypeSymbolExtensions to the compiler layer:

<details>

```cs
// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

using System.Collections.Generic;
using Microsoft.CodeAnalysis.Shared.Utilities;
using Roslyn.Utilities;

namespace Microsoft.CodeAnalysis.Shared.Extensions
{
    internal static partial class ITypeSymbolExtensions
    {
        public static bool IsErrorType(this ITypeSymbol symbol)
        {
            return symbol?.TypeKind == TypeKind.Error;
        }

        public static IEnumerable<ITypeSymbol> GetBaseTypesAndThis(this ITypeSymbol type)
        {
            var current = type;
            while (current != null)
            {
                yield return current;
                current = current.BaseType;
            }
        }

        // Determine if "type" inherits from "baseType", ignoring constructed types, and dealing
        // only with original types.
        public static bool InheritsFromOrEqualsIgnoringConstruction(
            this ITypeSymbol type, ITypeSymbol baseType)
        {
            var originalBaseType = baseType.OriginalDefinition;
            return type.GetBaseTypesAndThis().Contains(t => SymbolEquivalenceComparer.Instance.Equals(t.OriginalDefinition, originalBaseType));
        }

        public static bool ContainsAnonymousType(this ITypeSymbol symbol)
        {
            switch (symbol)
            {
                case IArrayTypeSymbol a: return ContainsAnonymousType(a.ElementType);
                case IPointerTypeSymbol p: return ContainsAnonymousType(p.PointedAtType);
                case INamedTypeSymbol n: return ContainsAnonymousType(n);
                default: return false;
            }
        }
    }
}
```

</details><br/>

In any case, my real ask is for some vetted API that analyzers can use to determine whether a member is accessible from a given context.

**Comment by CyrusNajmabadi** [comment]
That seems reasonable.  I think such an ask would go to @dotnet/roslyn-compiler .  @jaredpar Is there a recommended way for people to ask for functionality to be exposed from the core compiler layer?

**Comment by CyrusNajmabadi** [comment]
I would also retitle this to something like: No API available to determine if one symbol is accessible within another symbol".  The issue would then have to explain what works like "within" mean, and what the general API contract is needed here.

**Comment by jnm2** [comment]
I have five other compiler-level API requests and one workspace-level API request as well. It would be great to have a process in place. If it makes a difference, I'll offer the manpower to implement whatever the team decides.

**Comment by gafter** [comment]
A new API added in #27312 may be useful to replace some or all uses of the IDE accessibility API.

Please reopen if you find that this API cannot address your use cases (e.g. you don't have a compilation)

**Comment by jnm2** [comment]
Thanks @gafter!
