### ISSUE TITLE
Remove .NET Compiler SDK for VS2017 from Marketplace

### ISSUE THREAD

**Issue by kzu** [dotnet/roslyn#23860]
The version in the [marketplace](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.NETCompilerPlatformSDK) doesn't work with current stable (15.5.2 in my case) and it's super missleading since you should be installing it from Willow itself.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #80](https://github.com/dotnet/roslyn-sdk/issues/80) via [**ZenHub**](https://www.zenhub.com/)
