### ISSUE TITLE
Erroneous 'Using directive is unnecessary' when XML comment requires it

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#23864]
VS 15.5.2

**Steps to Reproduce**:

```cs
using System;

/// <summary>
/// <see cref="InvalidOperationException"/>
/// </summary>
class Foo
{
}
```

**Expected Behavior**:

The using directive should appear in use and removal should not be offered.

**Actual Behavior**:

The using directive appears dim with a diagnostic saying it is unused and a code fix to remove it.

**Comment by CyrusNajmabadi** [comment]
I repro this as well.

**Comment by gafter** [comment]
Dup of #2773

**Comment by jnm2** [comment]
I knew this sounded familiar! Apparently I ran into this [January 1st](https://github.com/dotnet/roslyn/issues/2773#issuecomment-269925184)! 🤣

**Comment by gafter** [comment]
Thanks for the reminder.

**Comment by jnm2** [comment]
It wasn't intentional. ❤️
