### ISSUE TITLE
Discard operator ambiguity

### ISSUE THREAD

**Issue by Logerfo** [dotnet/roslyn#23863]
The following code does not compile if you uncomment anything:
```c#
//public class _ { }
//public interface _ { }
//public struct _ { }
//public delegate void _();
public class C//<_>
{
   public void M(out int x)         
   {
       x = 2;
   }
   public void N()
   {
       M(out _);
   }
}
```
Is this behavior expected for the discard operator? I'm aware that local variables, fields, properties and method groups (did I forget something?) named `_` is an ambiguity, therefore the compiler error seems reasonable for those kinds, but as far as I can see, there is no ambiguity in the code example and the discard should happen normally.

**Comment by jcouv** [comment]
From discussion with @gafter, we consider this by-design. The specified behavior only treating `_` as a discard when the lookup for the identifier returned nothing.
