### ISSUE TITLE
AD0001 NullReferenceException at Microsoft.CodeAnalysis.UseExplicitTupleName.UseExplicitTupleNameDiagnosticAnalyzer.AnalyzeOperation

### ISSUE THREAD

**Issue by nnpcYvIVl** [dotnet/roslyn#23867]
```
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.UseExplicitTupleName.UseExplicitTupleNameDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	App		1	Compiler	Active	Analyzer 'Microsoft.CodeAnalysis.UseExplicitTupleName.UseExplicitTupleNameDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: App
IOperation: FieldReferenceExpression
SyntaxTree: Z:\App\External Libraries\System.ValueTuple\System.ValueTuple\src\System\ValueTuple\TupleExtensions.cs
SyntaxNode: value.Rest [MemberAccessExpressionSyntax]@[38390..38400) (770,37)-(770,47)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.UseExplicitTupleName.UseExplicitTupleNameDiagnosticAnalyzer.AnalyzeOperation(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__44_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

**Comment by dpoeschl** [comment]
Let's take a look, especially to ensure there isn't a deeper problem with IOperation to be found here.

**Comment by jcouv** [comment]
@nnpcYvIVl 
I've tried repro'ing this by opening the `TupleExtensions.cs` from the corefx repo (which is what I assumed revealed the problem in the first place, based on path in the description). But I did not manage to repro, with latest 15.6 preview.

What version of VS did you use? Are you still able to repro? Were you working on corefx, or some other source file?

```
Version 15.6.0 Preview 1.1
VisualStudio.15.Preview/15.6.0-pre.1.1+27205.2004
```

**Comment by nnpcYvIVl** [comment]
@jcouv 
I'm using ```VisualStudio.15.Release/15.5.2+27130.2010``` and still able to reproduce the problem. I don't have 15.6 to test against.

I have attached a sample project with files from corefx. Ignore the compiler errors, this sample project doesn't need to compile for the problem to appear. Open the solution and try to build, AD0001 will appear in the warnings window.

[AD0001 UseExplicitTupleNameDiagnosticAnalyzer.zip](https://github.com/dotnet/roslyn/files/1598127/AD0001.UseExplicitTupleNameDiagnosticAnalyzer.zip)

**Comment by jcouv** [comment]
@nnpcYvIVl Thanks for the repro project.
When I open it, I don't see a warning AD0001 in either the Output or the Error List windows.

I suspect this was fixed.
I'll go ahead and close this issue. Once you update to 15.6, feel free to re-open if you still encounter this. Thanks!

Error List:
![image](https://user-images.githubusercontent.com/12466233/34492329-ee473912-ef9b-11e7-8f2a-a8ad8d5a2802.png)

Output from Build:
![image](https://user-images.githubusercontent.com/12466233/34492339-f6ffede2-ef9b-11e7-979b-7ece81d1780d.png)

**Comment by nnpcYvIVl** [comment]
@jcouv I'm still getting AD0001 in 15.9.6 with the attached repro code so this doesn't appear to be fixed. To trigger the error open the project and double click on TupleExtensions.cs in solution explorer. Building is not necessary.

![valuetuple ad0001](https://user-images.githubusercontent.com/8421414/51920103-580a6700-23aa-11e9-93d7-ad3a1a036888.png)

Also note that in some cases AD0001 is in the error list but only shown as a shrunk row (see attached screenshot)
![valuetuple ad0001 shrunk row](https://user-images.githubusercontent.com/8421414/51920298-be8f8500-23aa-11e9-8fce-0e84ad86048e.png)

**Comment by nnpcYvIVl** [comment]
This is also reproducible in VS2019 2019 RC.1 SVC1.

**Comment by nnpcYvIVl** [comment]
This error is still occurring in 16.2. Is there an ETA for a fix?

**Comment by jcouv** [comment]
I'm able to repro with your zip file. I'll investigate for 16.4.

**Comment by nnpcYvIVl** [comment]
@jcouv Thank you for the quick response and ETA!

**Comment by jcouv** [comment]
Fix merged for first preview of 16.4.

**Comment by nnpcYvIVl** [comment]
@jcouv Thanks for the quick fix!

**Comment by mavasani** [comment]
FYI: Hit this on latest 16.3 dogfood bits.
