### ISSUE TITLE
Eternal loop in one of vsix analyzers prevents other analyzers from running

### ISSUE THREAD

**Issue by JarLob** [dotnet/roslyn#23879]
If one of analyzers gets into eternal loop it also doesn't give a chance to other analyzers to run. 

**Steps to Reproduce**:
Install a dummy vsix analyzer with `while (true) {}` in a registered syntax node action callback.

**Expected Behavior**:
Since there is already an issue for running analyzers in parallel https://github.com/dotnet/roslyn/issues/20390 there should be at least a timeout after which the call to the "hanging" extension is canceled.

**Actual Behavior**:
From user experience it just looks like there are no issues found not only by the buggy analyzer, but by other installed analyzers too, devenv.exe consumes ~10-20% of CPU on multi-core machine, that is almost not noticeable because devenv.exe usually does something in a background all the time.

**Comment by heejaechang** [comment]
currently, error list's "..." indicates that there are something running. but it is probably too subtle and aggregated too much information. (it doesn't distinguish source that are running)

we might need to adapt IVsTaskStatusCenterService  which got added recently. tagging @jinujoseph

**Comment by JarLob** [comment]
Just installed 15.7 and it is still "Error List...". It is written "Ready" in the bottom left corner and when expanded "No background tasks running."

**Comment by heejaechang** [comment]
@JarLob can you give me a repo step? just having bad analyzer is all you need? you should have at least background processing running message.

**Comment by heejaechang** [comment]
@JarLob okay, sorry about the confusion. looks like the fix is in 15.8 preview not in 15.7
