### ISSUE TITLE
Error CS0030 Cannot convert type 'object' to 'System.TypedReference'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23870]
<p>I can't compile the following code with latest version VS 2017 build 15.5.0.</p><pre> void MyMethod(object[] objects)
 {
    TypedReference.SetTypedReference((TypedReference)objects[0], objects[1]);
 }</pre>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/166353/error-cs0030-cannot-convert-type-object-to-systemt.html
VSTS ticketId: 537144_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jcouv** [comment]
Tagging @VSadov to triage and advise. Thanks

**Comment by bprg** [comment]
When will this bug be resolved?

**Comment by gafter** [comment]
This is not a bug. A `TypedReference` cannot be boxed, so there is no conversion between `object` and `TypedReference` in either direction. That is why you cannot cast `objects[0]` to the type `TypedReference`.
