### ISSUE TITLE
Cannot influence layout for "Use local functions" code fix

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#23872]
Use local functions, changes this line:

``` C#
Action onUpdateSolutionCancel = () => { buildCancelled = true; };
```

into:

``` C#
void onUpdateSolutionCancel()
{ buildCancelled = true; }
```

Which doesn't match any of my settings for new lines, and cannot seem to influence it by changing any of these settings. Unsure if this the code fix's fault or the formatter just not being able to format local functions.

I'd expect something more along the line of which matches my method syntax:

``` C#
void onUpdateSolutionCancel()
{
    buildCancelled = true;
}
```

or which would match the lambda:

``` C#
void onUpdateSolutionCancel() { buildCancelled = true; }
```

**Comment by heejaechang** [comment]
@jinujoseph Cyrus already made a fix.

**Comment by jinujoseph** [comment]
I know , this is assigned to you to get this in when  it's good to merge  :-)
