### ISSUE TITLE
[Question] Solving class dependencies

### ISSUE THREAD

**Issue by serdaoezuen** [dotnet/roslyn#23878]
**Version Used**: 
Microsoft.CodeAnalysis 2.6.1

Hello,

I would like to resolve dependencies of classes. I've already read quite a bit about the api and also played with it. However I am still not sure how I would achieve the following:

Imagine 2 classes

```
namespace CsharpAnalyzer
{
    public class TestClass1
    {
        static void main()
        {
            TestClass2 testClass2 = new TestClass2();
            testClass2.stuff();
        }
    }
}

namespace CsharpAnalyzer
{
    public class TestClass2
    {
            public void stuff()
            {
            }
    }
}

```
What I basically want to do is analyze TestClass1 and while analyzing the two example nodes within they should direct me to CsharpAnalyzer.TestClass2 as that is their origin and. Basically TestClass1 has a dependency to TestClass2.

Displaying the Namespace+classname is sufficient for me. So far I came up with the following:

```
class Program
    {
        static void Main(string[] args)
        {
            SyntaxTree tree;
            var path = @"C:\pathTo\TestClass1.cs";
            using (var stream = File.OpenRead(path))
            {
                tree = CSharpSyntaxTree.ParseText(SourceText.From(stream), path: path);
            }

            var root = (CompilationUnitSyntax)tree.GetRoot();
            var compilation = CSharpCompilation.Create("HelloWorld")
                                               .AddReferences(
                                                    MetadataReference.CreateFromFile(
                                                        typeof(object).Assembly.Location))
                                               .AddSyntaxTrees(tree);

            var model = compilation.GetSemanticModel(tree);
            var typesForCurrentClass = root.DescendantNodes().Select(VariableDeclarationSyntax => 
            model.GetSymbolInfo(VariableDeclarationSyntax));

            foreach (var mySymbol in typesForCurrentClass){
                try{
                     Console.WriteLine(mySymbol.Symbol);
                } catch(Exception e){

                }    
            }
        }
    }
```
I do not know where to go from as I can not find what I need within the api. To my understanding I need to be using GetSymbolInfo, although GetTypeInfo supposedly also makes sense sometimes?

**Comment by MaStr11** [comment]
You were close:
```CSharp
            var typesForCurrentClass = root
                .DescendantNodes()
                .OfType<VariableDeclarationSyntax>()
                .Select(variableDeclarationSyntax => model.GetSymbolInfo(variableDeclarationSyntax.Type));
```

**Comment by serdaoezuen** [comment]
Thanks! However, now the actual issue seems to be that I am only parsing one file, meaning that the compiler apparently(?) does not know about TestClass2. I've only been using JavaParser in the past and there it was common that it would be looking at the entire project when trying to solve a Node.

When I put TestClass1 and TestClass2 inside the same file for instance, it works fine, but not when they are inside seperate Files.

I am assuming that I need to change the following:

```
SyntaxTree tree;
            var path = @"C:\pathTo\TestClass1.cs";
            using (var stream = File.OpenRead(path))
            {
                tree = CSharpSyntaxTree.ParseText(SourceText.From(stream), path: path);
            }
```

Wherever I look I can only find exampes where one file at a time is being parsed + I am a c# noob

**Comment by jmarolf** [comment]
@serdaoezuen you can add as many syntax trees as you need to a compilation.  You can also use [MSBuildWorkspace](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/MSBuild/MSBuildWorkspace.cs,25) to open entire solutions and examine them.  Are these cs files organized in a project?  What sort of data do you want to get at the end?

**Comment by serdaoezuen** [comment]
Basically I just have 2 .cs files in a directory. Previously I had 

```
var path = @"C:\pathtoDirectory";
 string[] files = Directory.GetFiles(path, "*.cs", SearchOption.AllDirectories);
 var compilation = CSharpCompilation.Create("Application")
                                               .AddReferences(
                                                    MetadataReference.CreateFromFile(
                                                        typeof(object).Assembly.Location))

foreach (var item in files)
            {
           compilation.AddSyntaxTrees(CSharpSyntaxTree.ParseText(File.ReadAllText(item)).WithFilePath(item));
            }
```

compilation.SyntaxTrees.Length showed that it still was empty however. 

Not sure how MSBuildWorkspaces work yet, but I'll look into it, if it eases the process thanks!

What I ultimately want is just a bunch of strings for each class that tell to which classes dependencies exist.

**Comment by jmarolf** [comment]
[AddSyntaxTrees](http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/Compilation.cs,404) returns a new compilation that you are not observing.  Should be:
```C#
foreach (var item in files){
    var compilation = compilation.AddSyntaxTrees(CSharpSyntaxTree.ParseText(File.ReadAllText(item)).WithFilePath(item));
 }
```
