### ISSUE TITLE
F1 keyword help for `private protected` should not send you to help for `private` or `protected`

### ISSUE THREAD

**Issue by AnthonyDGreen** [dotnet/roslyn#23881]
@BillWagner on the docs team, observed that if you put the cursor on one keyword of a keyword pair like `private protected`, `protected internal` , `Protected Friend` it would be far superior to send the developer to a help topic for the compound modifier instead of for the individual keyword your cursor is on.

Today we have a kludgy workaround where the page for each individual keyword has a link that says "did you mean this..." but we can do better. Today it looks like we detect this case for pairs like `For Each` in VB. It would be great to detect this case for other cases.

**Comment by jcouv** [comment]
We discussed this with @gafter as well, and thought that the page for "private" could have a pointer to the page for "private protected", and the same for the "protected" page.

That said, I agree that the behavior you describe is preferable.

**Comment by BillWagner** [comment]
We have implemented the links that @jcouv mentions:

[private](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/private)
[protected](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/protected)
[internal](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/internal)

If this is implemented, we'll need to update the `protected internal` and `private protected` articles to add the F1 metadata tag. As part of this, we should consider other compound keywords. A partial list would include:

`yield return` in C#
`For Each` in VB

**Comment by Youssef1313** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/46343.

@davidwengier @jinujoseph Can we close please? Thanks!
