### ISSUE TITLE
Inlined variable declaration fails to compile

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23882]
I have a routine signature in a different dll that's referenced with an &quot;out&quot; variable.   I declare the varible I want to capture &quot;out' value.   The IDE says I can make that variable an &quot;inline&quot; variable.   When I compile it fails for making it an inline variable.

Ex:

```csharp
string errMsg = null;

 if (!TokenService.IsTokenValid(rs, out errMsg))
 {
    //works fine.
 }
```

If I move the variable inline based on recommendation to move it inline, it fails to compile.

```csharp
 if (!TokenService.IsTokenValid(rs, out string errMsg))
{
    //won't compile
}
```

This has 2 outcomes - sometimes the error says invalid expression other times it seems to &quot;crash&quot; the compiler.   If you just run the the code it has it didn't compile run currrent version or stop - clicked stop and it displays no errors exists -  restarted visual studio and same result.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/168115/inlined-variable-declaration-fails-to-compile.html
VSTS ticketId: 539780_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by TomSelleck101** [comment]
+1

```
object result; //Recommended by IDE to be declared inline
GetMemberBinder binder = CreateGetMemberBinder(target.GetType(), this.PropertyName);
```

Changed to the following causes a build fail:

```
GetMemberBinder binder = CreateGetMemberBinder(target.GetType(), this.PropertyName);
d.TryGetMember(binder, out object result);
```

Build output:

```
5>C:\Formatters\DeltaContractResolver.cs(73,44,73,50): error CS1525: Invalid expression term 'object'
5>C:\Formatters\DeltaContractResolver.cs(73,51,73,57): error CS1003: Syntax error, ',' expected
```

**Comment by gafter** [comment]
@AlekseyTs Can you think of any recent change that would have affected how out variable declarations are parsed?

**Comment by AlekseyTs** [comment]
> Can you think of any recent change that would have affected how out variable declarations are parsed?

I cannot reproduce the problem. We also have an existing compiler unit-test OutVarTests.Fixed_02 that covers similar scenario. I do not remember making any parser changes in this area recently.
