### ISSUE TITLE
Unable to disable Roslyn lightbulb

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23885]
Why is there no option to use visual studio without the additional frills and bells and whistles that can be generalised under the 'Roslyn' category? When looking under Tools &amp; Extensions, the only option provided next to the entries relating to roslyn, is &quot;Uninstall&quot; (I'd expect to see a &quot;Disable&quot; somewhere), which kindly lets you know that everything else relating to C# development will also get removed should I desire to get rid of said component. Oh the number of times I've found myself staring at the uninstall screen longingly... If only RIDER had better web deploy support.

So please give us a way to _disable all_ visual studio suggestions, code fixes, refactorings, etc etc - the &quot;lightbulb&quot; essentially. The only lightbulb I want to see in my VS is the one belonging to ReSharper. 

The choice of when we switch to VS tools, and IF we do it at all, should be left up to the developer, instead of being opted into features we haven't asked for, with the expectation that we'd be filing bug reports about things that annoy us - that's just lost productivity, on all ends. 

We already had a perfectly good toolkit called ReSharper. Thanks to these &quot;improvements&quot; to VS, our favourite tool has taken a hit in terms of performance as well as feature development. 

Once more for clarity: stop forcing roslyn &quot;helpers&quot; on me and let me disable that junk!

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/159587/unable-to-disable-roslyn-lightbulb.html
VSTS ticketId: 532717_
_These are the original issue comments:_

Cheryl Borley (InConsulting Inc.) on ‎12‎/‎6‎/‎2017, 03:32 PM (14 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
This is a two-part issue:

First, Roslyn needs to provide internal hooks to disable features as an extensibility point. Some code for this can be found in [`InternalFeatureOnOffOptions`](https://github.com/dotnet/roslyn/blob/5aa8207c84f99bc764dc1208d285c414dac7e51d/src/EditorFeatures/Core/Shared/Options/InternalFeatureOnOffOptions.cs#L10) and [`EditorComponentOnOffOptions`](https://github.com/dotnet/roslyn/blob/5aa8207c84f99bc764dc1208d285c414dac7e51d/src/EditorFeatures/Core/Shared/Options/ComponentOnOffOptions.cs#L13).

Once the final names for these feature flags are determined (which may or may not match the names already in place), ReSharper needs to be updated to set values to these flags in order to disable features which are replaced by the extension.

**Comment by vinniefalco** [comment]
I'm sick of these "Quick Actions" light bulbs in the margin which have NOTHING to do with my project, for example:

"Change B to _ARM64_NT_NEON_128::B"

WTF? All of these settings should DEFAULT TO OFF, and the user can OPT-IN by turning them on. They should not default to on.

**Comment by sharwell** [comment]
@vinniefalco can you file a new issue for the case you observed? Actions which are unrelated to your project should not be showing.

**Comment by sanchezis** [comment]
Hide Lightbulb Margin extension from Visual Studio Market place

**Comment by bartwe** [comment]
How can i keep the ctrl+. feature while not have vs animate the screwdriver icon while staying on a line for a few seconds ?

**Comment by CyrusNajmabadi** [comment]
@bartwe it's unclear waht you're asking for.

**Comment by bartwe** [comment]
Whenever my cursor rests on a line for a bit i get a 
![image](https://user-images.githubusercontent.com/117214/147166552-cf18af93-2dfc-4059-89fe-a53c4a6c3768.png)
and i'm asking how can i avoid this distracting icon without disabling the quickaction shortcut ctrl+.

**Comment by CyrusNajmabadi** [comment]
@gundermanc for feedback on disabling the UI.

**Comment by vinniefalco** [comment]
Just default all this stuff to OFF instead of enabling it in every new version

**Comment by CyrusNajmabadi** [comment]
@vinniefalco lightbulbs have been in the product for over 15 years and see usage across nearly the entire userbase. Disabling by default would not be beneficial here.

**Comment by CyrusNajmabadi** [comment]
Please also see what Sam wrote and please submit a bug report if a lightbulb is showing something inappropriate.

**Comment by gundermanc** [comment]
> @gundermanc for feedback on disabling the UI.

@bartwe would you mind filing feedback for this suggestion via Help > Send Feedback? Doing so allows us to collect votes and triage this change with feedback from all VS customers. Roslyn owns the data in the lightbulb margin but VS IDE owns the UX itself, so the triage process is a bit different for a UX change.

@olegtk FYI

**Comment by olegtk** [comment]
Technically Resharper can disable LightBulb margin using DefaultTextViewHostOptions.SuggestionMarginId. There is no user option to do that, but programmatically it's supported (and this is what Tweaks VS extension does). 

Unfortunately, currently disabling LightBulb margin also breaks on-demand Lightbulb (Ctrl+. or Alt+Enter). We are looking to fix this, but indeed need more user feedback to justify the work so please file a feedback ticket.

@bartwe LightBulb icon animating for several seconds is a discoverability feature. It happens only until you first time expand LighgtBulb and never after that.

**Comment by CyrusNajmabadi** [comment]
Closing out as external.  Editor/platform tracks thsi request.
