### ISSUE TITLE
selection doesn't work after deleting a character

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23894]
I'm editing text in C# editor.
I have text like `.Constraint(new[] { "FK_MatchingRule_MatchingProcess" }, MatchingErrorCode.MatchingProcessDoesNotExist`

- enter ',' at the end of the line
- remove it with backspace
- press shift and use arrow key down to select text from the line below

expected: some text in selection

what I get: selection of text is not enabled at all.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/165148/selection-doesnt-work-after-deleting-a-character.html
VSTS ticketId: 536457_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎12‎/‎20‎/‎2017, 08:11 PM (40 min ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
It appears the issue is caused typing <kbd>,</kbd>, which triggers Signature Info. While signature info is visible, selections using the keyboard are disabled.

@Pilchie @DustinCampbell @olegtk @CyrusNajmabadi Do you know if this behavior is by design?

**Comment by CyrusNajmabadi** [comment]
This is by design.
