### ISSUE TITLE
Wrong order of 'in' and 'this' in extension method tooltip

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#23895]
Version: VS2017 15.5.2

Hover over `M`, the tooltip shows `M(this in int a)` which is invalid C# (`error CS8339: The parameter modifier 'in' cannot be used after the modifier 'this'`)

```C#
	static class Extensions {
		public static int M(in this int a) => a;
	}
```

**Comment by jcouv** [comment]
This error is going to be removed. The modifiers on parameters will be allowed in any order, in 15.6.
Fix in review: https://github.com/dotnet/roslyn/pull/23643

I'll go ahead and close this issue as duplicate. Thanks
