### ISSUE TITLE
operator ==() with 'in' (C# 7.2) arguments generate a compilation error if it's in a different assembly

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#23897]
Version: Microsoft (R) Visual C# Compiler version 2.6.0.62329 (5429b35d)

Expected: It compiles and generates a few .NET files

Actual: It refuses to compile assembly # 1 `error CS0019: Operator '==' cannot be applied to operands of type 'S' and 'S'`

Workaround: Move all code to assembly # 1.

**Assembly # 1**

Add a reference to assembly # 2

```C#
using ClassLibrary1;

namespace ConsoleApp1 {
	class Program {
		void M(S s) {
			var copy = s;
			bool b = copy == s && copy != s;
		}

		static void Main(string[] args) {
		}
	}
}
```

**Assembly # 2**

```C#
namespace ClassLibrary1 {
	public readonly struct S {
		public static bool operator ==(in S left, in S right) => false;
		public static bool operator !=(in S left, in S right) => false;
		public bool Equals(S other) => false;
		public override bool Equals(object obj) => false;
		public override int GetHashCode() => 0;
	}
}
```

**Comment by ufcpp** [comment]
dup of https://github.com/dotnet/roslyn/issues/23689
