### ISSUE TITLE
Use Implicit/Explicit type gives wrong suggestion on out parameters and nullable types

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23893]
15.5.1, used to work all right before.

VS suggests to change the following out parameter type to var, despite my setting of preference to built-in types over var. In earlier versions this worked. With plain variable declarations it's OK, only out parameters are problematic now.

On a related note, I'd very much like to see another setting that handles nullable versions of built-in types. I have a preference for built-in types over var but I'd like to see this extended to their nullable versions as well, like bool?, rather than suggesting them to change to var.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/167044/wrong-code-style-suggestion.html
VSTS ticketId: 537874_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
:memo: Built-in types should extend to derivations of these types, including arrays, nullables, pointers, and ref types.

**Comment by jcouv** [comment]
@sharwell What about tuples of intrinsic types? Would those also be considered intrinsic?

**Comment by sharwell** [comment]
@jcouv I don't think tuples would count.

**Comment by jcouv** [comment]
Fix is merged for 15.6 preview 4
