### ISSUE TITLE
Clarify that the default is 'latest major version' on the wiki/NuGet-packages page

### ISSUE THREAD

**Issue by stijnherreman** [dotnet/roslyn#23903]
https://github.com/dotnet/roslyn/wiki/NuGet-packages has a list of versions, and I find it to be misleading in its current form. For example:

> Version 2.6 means C# 7.2 and VB 15.5 (Visual Studio 2017 version 15.5).

That doesn't mean C# 7.2 will be used, it means C# 7.2 is available. By default, C# 7.0 will be used.

The documentation should mention that you need to modify the project properties to target the latest minor version. This can be done via the UI (see the screenshot below), although this simply modifies configurations instead of modifying a `<PropertyGroup>` without `Condition="..."`. So an alternative is to modify the `.csproj` file manually.

![image](https://user-images.githubusercontent.com/1618054/34263466-e6d547a8-e66f-11e7-913d-6d3f8742fe97.png)

**Comment by jcouv** [comment]
Thanks for the feedback.
Added a note about language versions and "default" and "latest".
