### ISSUE TITLE
Document tag <param name=> fails for named tuples

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23915]
In the snippet below, param name give &quot;Cannot resolve symbol&quot; for the named tuples names (current and previous).

```csharp
/// <summary>
/// </summary>
/// <param name="dataPoints"></param>
/// <param name="current"></param>
/// <param name="previous"></param>
/// <returns></returns>
public (List<float> current, List<float> previous) DivideByPhaseAsync(List<float> dataPoints)
{
	var current = new List<float>();
	var previous = new List<float>();
	return (current, previous);
}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/171531/document-tag-fails-for-named-tuples.html
VSTS ticketId: 542449_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
:memo: The method in the code sample does not have any parameter named `current` or `previous`, so the failure is certainly the intended behavior for this case. For a different case where the method has a parameter with a tuple type with named tuple elements, a new feature to reference these elements in the documentation may need to start with a language proposal.

**Comment by jcouv** [comment]
There is already a proposal tracking this in the language design repo: https://github.com/dotnet/csharplang/issues/145
I'll go ahead and close as duplicate. You can continue the discussion there.
