### ISSUE TITLE
CompilerDiagnosticAnalyzer is not enabled for concurrent execution

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#23916]
Currently `CompilerDiagnosticAnalyzer` is not enabled for concurrent execution. As a result, more than 25% of the CPU time during traces like the one provided in [High CPU usage when idle](https://developercommunity.visualstudio.com/content/problem/170828/high-cpu-usage-when-idle-2.html) occur in lock contention. This analyzer needs to be enabled for concurrent execution to eliminate this lock requirement.

**Comment by Youssef1313** [comment]
@sharwell I think this was fixed in https://github.com/dotnet/roslyn/pull/35483 and can be closed?
