### ISSUE TITLE
Document's SemanticModel.GetSymbolInfo always returns a null symbol

### ISSUE THREAD

**Issue by wallnutkraken** [dotnet/roslyn#23913]
**Version Used**: 
Visual C# Compiler version 2.6.0.62329 (5429b35d)

**Steps to Reproduce**:

1. Open a workspace
2. Open an existing solution via the workspace
3. Open a project from the solution
4. Open a document from the solution
5. Get the root and SemanticModel from the document
6. Do a foreach on the root.DescendantNodes()
7. Check if any symbols for the nodes are null

**Expected Behavior**:
Most, if not all, symbols are not null.

**Actual Behavior**:
All symbols are null.

**Minimal working reproduction:**
```c#
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.MSBuild;

namespace CodeAnalysisApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var workspace = MSBuildWorkspace.Create();
            var solution = workspace.OpenSolutionAsync("../../example/example.sln").Result;

            foreach (Project solutionProject in solution.Projects)
            {
                foreach (Document doc in solutionProject.Documents)
                {
                    var semanticModel = doc.GetSemanticModelAsync().Result;
                    var root = doc.GetSyntaxRootAsync().Result;
                    var nodes = root.DescendantNodes();
                    foreach (SyntaxNode node in nodes)
                    {
                        var symbol = semanticModel.GetSymbolInfo(node);
                        if (symbol.Symbol != null)
                        {
                            Console.WriteLine("NOT NULL ON: " + node);
                        }
                    }
                }
            }

            Console.WriteLine("End");
            Console.ReadKey(true);
        }
    }
}
```

**example.sln** has only one file, Program.cs:
```c#
using System.Reflection;
using log4net;

namespace example
{
    class Program
    {
        private static readonly ILog logger = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        static void Main(string[] args)
        {
            logger.Error("Hello!");
        }
    }
}
```

**Comment by AmadeusW** [comment]
Use `GetDeclaredSymbol` instead of `GetSymbolInfo`. I'm not sure why the latter one doesn't work, though.

**Comment by gafter** [comment]
`GetDeclaredSymbol` is for a declaration (that introduces a name), `GetSymbolInfo` is for a use (of a name that was declared elsewhere), and never the twain shall meet.

**Comment by CodeThreader** [comment]
I have the same problem with both of them. They work fine for while, if an exception is thrown, they only return null. Annoying.

**Comment by CyrusNajmabadi** [comment]
> They work fine for while, if an exception is thrown, they only return null.

Do you have a repro for this?
