### ISSUE TITLE
VB Collection with ? gets an error 

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#23928]
**Version Used**: 
VS 2017 15.5.2
**Steps to Reproduce**:
```
                   For Each a In node.AccessorList?.Accessors
                       ' Anything
                   Next
```
1. With the above code I would expect no errors
2. The problem is with the ?. before Accessors 

**Expected Behavior**:
No Error
**Actual Behavior**:
Error	BC32023	Expression is of type 'SyntaxList(Of AccessorDeclarationSyntax)?', which is not a collection type

**Comment by jcouv** [comment]
@AnthonyDGreen Can you confirm the expected behavior for this?

**Comment by paul1956** [comment]
FYI: In C# it works as expected.
'''
					foreach (var a in node.AccessorList?.Accessors) {
					}
```

**Comment by KathleenDollard** [comment]
@paul1956 

I tried to repo this with the code below. Can you see why this is different and/or let me know which version of VB and .NET you're having this issue with. 

```VB
Public Class Class1

    Public Sub Foo()

        Dim B As B = Nothing
        Dim x = B.A?.Bar

        For Each y In B.A?.Bar

        Next
    End Sub
End Class

Public Class B
    Public A As A
End Class

Public Class A

    Public Property Bar As IEnumerable(Of String)
End Class
```

**Comment by svick** [comment]
The question here is whether `foreach` works on a nullable `struct` enumerable (`SyntaxList(Of AccessorDeclarationSyntax)?` is such type).

[In C#:](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEAMACFBGALAbgFgAoElAJgwGESBvEjRrXDAWQAoBlYKAVwGNgAGRgBnYAH4MAGzHAAlAyb1iTNRjgB7KBACG/ABYZ2YXVAwAPDDAB2MufIy0MAXyWM3xTyXF9BGbj9hOTp3LABmDABJAFEbXgBbaF1gbQAeW2AAPgwAcQhgOMTk1Kh2RwBeHPjpaSIvIA)

```c#
using System.Collections.Generic;

class C
{
    void M(StructList? list)
    {
        foreach (var x in list) { }
    }
}

struct StructList
{
    public IEnumerator<int> GetEnumerator() => null;
}
```

[In VB:](https://sharplab.io/#v2:DYLgbgRgNALuCmAnAlgMwJ4B8CSBbADgPaIwDOABAMrqkzy4B0AwocMPAMYzKEB2pDAOLxeSZBwCwAKGlNgAQ1IUm08mqoBXCOQCyACmDJa5AIIVKMRBq4AZIzAD8ASlXq3AMWLkAovI4ALcgAPcmxeckNaVzUASAA5eCCYaJ9eABNNCGlvdPI5RVJpaQsrLg1EeCpLaxg7KKk3AAUtQw5ydw1eLh5w4RgcjVwkeRhiPSdTCmwBocQRsYB5VFDeOgBzJBcGt3UAJXgYcvC4whh/ZF41lJyMjq7uPmzckpry+CA==)

```vbnet
Imports System.Collections.Generic

Class C
    Sub M(list As StructList?)
        For Each x In list
    	Next
    End Sub
End Class

Structure StructList
    Public Function GetEnumerator() As IEnumerator(Of Integer)
        Return Nothing
    End Function
End Structure
```

Indeed, the C# code compiles, while the VB code does not.

Interestingly, the C# spec [says that this code shouldn't compile](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements#the-foreach-statement), but Roslyn deliberately violates the spec:

https://github.com/dotnet/roslyn/blob/a550ee116086285f4e3b22a691dc1f2d2d4c0d03/src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs#L508-L509

I didn't check the VB spec, but I assume the behavior of the VB compiler is correct. So I think there is nothing to do here, unless you'd like to propose that VB changes its behavior (which would belong to [the vblang repo](https://github.com/dotnet/vblang/)) or that the C# spec should be changed to accommodate how the compiler currently behaves (which would belong to [the csharplang repo](https://github.com/dotnet/csharplang)).

**Comment by jaredpar** [comment]
Closing as the compiler is behaving as designed for VB here.
