### ISSUE TITLE
VS unresponsive for minutes after build

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#2393]
ETL and memory dump at %internal_share%\public\tomat\Bugs\2393

**Comment by Pilchie** [comment]
Can you look at the profile and see if there is something that can be addressed here?

**Comment by rchande** [comment]
Poaching.

**Comment by tmat** [comment]
Unfortunately the symbols are not available anymore :(

**Comment by tmat** [comment]
msvbprj.dll is calling 

``` 	Microsoft.VisualStudio.CommonIDE.dll!Microsoft.VisualStudio.Build.ComInteropWrapper.ProjectShim.BuildTargetListWithOutputs(string targetList, Microsoft.VisualStudio.Build.ComInteropWrapper.ITargetOutputs targetOutputs, bool isRealBuild, bool isOutOfProcBuild) Line 2050	C#```

with target "ResolveRefrences", which blocks the UI thread in ```ProjectShip.BuildTargetsImpl```
