### ISSUE TITLE
Turn expression-body for methods off by default

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#23934]
This came up in a review that it's confusing for customers to see gray dots in a template, fix it, and then have an icon appear showing to convert it back. 

FYI @jinujoseph @Pilchie

**Comment by sharwell** [comment]
We should add this to a design meeting for the new year.

**Comment by CyrusNajmabadi** [comment]
This is set to never:silent:

```
        public static readonly Option2<CodeStyleOption2<ExpressionBodyPreference>> PreferExpressionBodiedMethods = CreatePreferExpressionBodyOption(
            nameof(PreferExpressionBodiedMethods), defaultValue: NeverWithSilentEnforcement, "csharp_style_expression_bodied_methods");
```

Closing out.
