### ISSUE TITLE
Compiler complains on CS1998 when implementing protected override

### ISSUE THREAD

**Issue by damageboy** [dotnet/roslyn#23947]
**Version Used**:  Visual Studio 2017 Version 15.5

**Steps to Reproduce**:

1. Create a Base class with abstract async method
2. override in subclass with a non awaiting implementation
3. CS1998 is emitted

**Expected Behavior**:

In the specific case of overriding protected async methods, CS1998 should be suppressed IMO since the implementer cannot control what he/she are implementing

**Actual Behavior**:

CS1998 is emitted

**Comment by HaloFour** [comment]
> Create a Base class with abstract async method

This should already result in the error `CS1994: The 'async' modifier can only be used in methods that have a body.` It doesn't make sense for an `abstract` method to be marked as `async` because that is an implementation detail which does not impact how that method might be implemented in a derived class.

**Comment by jcouv** [comment]
@damageboy 
`async` doesn't change the signature of a method, just how the compiler processes the body.
If the override implementation doesn't have an `await`, then it doesn't need `async` on its declaration. But it is still a valid override.

See this [example](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGArAbgFgAoElAZgwmFgQgGMYsAmDAIWjhIG8SN+slarQZMUANgwBZABQBKIsQC+ZSilYARRAEsAbnAAmGEO048+AihgD2+hAm0G4WSbLkYA9B4wA7a1gAODChtH3pnPywATgt+XmIBRIwYAAsEawB3XzgsnAA6ADlrGABJMAAHABs4MDgfeAMAUQAPcPKYbWsfeUVElWVVFgwtB30DVhMOKC5ieMSrW0QHJ0CXaXlYjDmBAEgUKJc8gGFrCuqGiXxPb2BrAwBPDABXaahogBpg/1rUu4wneiVCAIQwYDLaVKBTaJVLpLI+HJYbCFYplKo1OoNFptDpdHqbJQYEhKIA).

**Comment by damageboy** [comment]
Thanks, and sorry!
