### ISSUE TITLE
System.IO.PathTooLongException while calling MSBuildWorkspace.OpenProjectAsync

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#23952]
**Version Used**: 
2.3.2

**Steps to Reproduce**:

1. Windows Server 2012 RC machine.
2. Create MSBuildWorkspace reference and try to call  method **OpenProjectAsync** on a .csproj path whose project path has more than 260 characters.
3. `
    var projectPath = "C:/ProgramData/Apps/App1/data/user/151436921087345345345345543/checkouts/9e07304ab4559f49507f3f159796d094/src/Main\Build\Tools\CheckinPolicy\CodeReviewPolicy\CodeReviewPolicyVS\CodeReviewPolicyCoreTest\CodeReviewPolicyCoreTest.csproj" 
    var workspace = MSBuildWorkspace.Create();
     currentProject = workspace.OpenProjectAsync(projectPath).Result;`
3. We know that this is a limitation with the Windows. But there has to be some way out.
4. Note: We dont have the control over the Project path. 

**Expected Behavior**:
Some way in which the path size limit can be modified for the application so that **OpenProjectAsync** does not throw an exception and instead loads the project.

**Actual Behavior**:
System.IO.PathTooLongException.

This is not a direct issue with Roslyn, but we need to understand how can we configure Roslyn to accept large file path projects.

We are aware of option like editing **LongPathsEnabled** under registry. But not sure how safe is this option.

**Comment by abhijitparkhi1983** [comment]
@Pilchie , @sharwell
Please help me on this issue with your valuable suggestions.

**Comment by abhijitparkhi1983** [comment]
@jcouv @DustinCampbell 
Guys this is one blocker issue i am facing. Can some one please help me on this ?

**Comment by jmarolf** [comment]
@abhijitparkhi1983 if you are running on .NET Framework 4.6.2 or newer you can opt you app into new behavior that allows for longer paths (see [this blog post](https://blogs.msdn.microsoft.com/dotnet/2016/08/02/announcing-net-framework-4-6-2/)) but the underlying OS still needs to support long paths.  I believe Windows Server 2012 RC  only supports long paths on ReFS not NTFS.  You can also try adding the `\\?\` prefix to tell windows to treat the path as a [UNC path](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#maxpath).

**Comment by DustinCampbell** [comment]
@abhijitparkhi1983: It looks like @jmarolf's answer is the right one. Let us know if this doesn't solve your issue.
