### ISSUE TITLE
CodeLens blinks for a long time

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#23963]
![blinking-codelens](https://user-images.githubusercontent.com/12466233/34429495-be2cfe56-ec0d-11e7-9372-1249199af3b4.gif)

It was not easy to capture, because it's not very consistent. Sometimes there is not blinking (the spot gets filled in once and settles). Sometimes it settles after a couple of blinks. In the screenshot above it blinked for 15 seconds.

Version 15.6.0 Preview 1.1
VisualStudio.15.Preview/15.6.0-pre.1.1+27205.2004

**Comment by heejaechang** [comment]
@jinujoseph I don't think it is our bug. @paulvanbrenk can you let us (@jinujoseph  and me) know who we should contact in code lens team for this kind of issue in future?

**Comment by jinujoseph** [comment]
moved to editor [team](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_queries/edit/548842/?triage=true)
