### ISSUE TITLE
Wrong TypeKind from different assembly on netcoreapp

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#23976]
**Version Used**: 

VS 15.5.2
Microsoft.CodeAnalysis.CSharp 2.6.0

**Steps to Reproduce**:

Run https://github.com/ufcpp/UfcppSample/tree/master/Demo/2017/Roslyn2_6_0PossiblyBug

```cs
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

public struct ExternalStruct { }

class Program
{
    static void Main()
    {
        var cu = ParseCompilationUnit(@"
public class X
{
    public ExternalStruct e;
    public InternalStruct i;
    public System.DateTime d;
}

public struct InternalStruct { }
");

        var sem = GetSemantics(cu);

        var classX = (ClassDeclarationSyntax)cu.Members[0];

        // X.e (struct ExternalStruct)
        ShowTypeInfo(sem, (FieldDeclarationSyntax)classX.Members[0]);

        // X.i (struct InternalStruct)
        ShowTypeInfo(sem, (FieldDeclarationSyntax)classX.Members[1]);

        // X.d (struct DateTime)
        ShowTypeInfo(sem, (FieldDeclarationSyntax)classX.Members[2]);

/* results
# with net47:
Struct ExternalStruct
Struct InternalStruct
Struct DateTime

# with netcoreapp2.0:
Class ExternalStruct
Struct InternalStruct
Struct DateTime
*/
    }

    private static void ShowTypeInfo(SemanticModel sem, FieldDeclarationSyntax field)
    {
        var t = sem.GetTypeInfo(field.Declaration.Type).Type;

        Console.WriteLine($"{t.TypeKind} {t.Name}");
    }

    private static SemanticModel GetSemantics(CompilationUnitSyntax cu)
    {
        var compilation = CSharpCompilation.Create("sample")
            .AddReferences(
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(Program).Assembly.Location))
            .AddSyntaxTrees(cu.SyntaxTree);

        var sem = compilation.GetSemanticModel(cu.SyntaxTree);
        return sem;
    }
}
```

**Expected Behavior**:

The `TypeKind` of the `ExternalStruct` should be `Struct`.

**Actual Behavior**:

It is `Class` on netcoreapp runtime.

**Comment by ufcpp** [comment]
FYI

```cs
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

public struct ExternalStruct { }

class Program
{
    static void Main()
    {
        var cu = ParseCompilationUnit("public class X { public ExternalStruct e; }");
        var sem = GetSemantics(cu);

        var classX = (ClassDeclarationSyntax)cu.Members[0];
        var f = (FieldDeclarationSyntax)classX.Members[0];
        var t = sem.GetTypeInfo(f.Declaration.Type).Type;

        // None instead of System_ValueType
        Console.WriteLine(t.BaseType.SpecialType);
    }

    private static SemanticModel GetSemantics(CompilationUnitSyntax cu)
    {
        var compilation = CSharpCompilation.Create("sample")
            .AddReferences(
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(Program).Assembly.Location))
            .AddSyntaxTrees(cu.SyntaxTree);

        var sem = compilation.GetSemanticModel(cu.SyntaxTree);
        return sem;
    }
}
```

**Comment by jcouv** [comment]
Would you mind trying with previous version of compiler package? (is it a regression?)

**Comment by ufcpp** [comment]
Trying now. the same even with Microsoft.CodeAnalysis.CSharp 1.0.0.

**Comment by ufcpp** [comment]
I tried to inspect and found that
TypeKind is Class
because [BaseType.SpecialKind is None](https://github.com/dotnet/roslyn/blob/0f6b30e54f0e18e7ebb5cbb1c9ae082cb4b62ca0/src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs#L1630)
because [BaseType.DeclaredAccessibility is NotApplicable](https://github.com/dotnet/roslyn/blob/0f6b30e54f0e18e7ebb5cbb1c9ae082cb4b62ca0/src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs#L310)
because [BaseType is MissingMetadataTypeSymbol](https://github.com/dotnet/roslyn/blob/94ab292d2c79b1675de0d6ff0a7361ecfbf20cfb/src/Compilers/CSharp/Portable/Symbols/ErrorTypeSymbol.cs#L363)
because [BaseType.ContainingAssembly (System.Runtime) is MissingModuleSymbol](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Compilers/CSharp/Portable/Symbols/MissingModuleSymbol.cs#L144)
because [it's not bound](https://github.com/dotnet/roslyn/blob/d4dab355b96955aca5b4b0ebf6282575fad78ba8/src/Compilers/CSharp/Portable/Symbols/ReferenceManager.cs#L726)

This is my limit... I can't find the reason why System.Runtime isn't bound.

**Comment by gafter** [comment]
@ufcpp I suggest inspecting the compiler diagnostics.

**Comment by ufcpp** [comment]
@gafter 

No diagnostics

```cs
using System;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

public struct ExternalStruct { }

class Program
{
    static void Main()
    {
        var cu = SyntaxFactory.ParseCompilationUnit("public class X { public ExternalStruct e; }");
        var sem = GetSemantics(cu);

        var classX = (ClassDeclarationSyntax)cu.Members[0];
        var f = (FieldDeclarationSyntax)classX.Members[0];
        var t = sem.GetTypeInfo(f.Declaration.Type).Type;

        // None instead of System_ValueType
        Console.WriteLine(t.BaseType.SpecialType);
    }

    private static SemanticModel GetSemantics(CompilationUnitSyntax cu)
    {
        // System.Private.CoreLib.dll
        Console.WriteLine(typeof(ValueType).GetTypeInfo().Assembly.Location);

        var compilation = CSharpCompilation.Create("sample", options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .AddReferences(
                MetadataReference.CreateFromFile(typeof(object).GetTypeInfo().Assembly.Location),
                MetadataReference.CreateFromFile(typeof(ValueType).GetTypeInfo().Assembly.Location),
                MetadataReference.CreateFromFile(typeof(Program).GetTypeInfo().Assembly.Location))
            .AddSyntaxTrees(cu.SyntaxTree);

        var sem = compilation.GetSemanticModel(cu.SyntaxTree);

        // No Diagnostics
        foreach (var d in compilation.GetDiagnostics())
        {
            Console.WriteLine(d);
        }
        return sem;
    }
}
```

**Comment by ufcpp** [comment]
I know System.Runtime on netcore is a type forwarder (facade library). System.ValueType is contained in System.Runtime at build time but System.Private.CoreLib at runtime. Should Roslyn compiler solve type forwarding?

An actual problem I'm faced is that [my analyzer](https://github.com/ufcpp/NonCopyableAnalyzer) can't work with structs from different assembly.

![image](https://user-images.githubusercontent.com/3760955/34458757-40d5a0dc-ee21-11e7-8b00-96fb66cec731.png)

This is because the analyzer can't recognize `NotifyPropertyChanged` as a struct.

**Comment by jaredpar** [comment]
Running this locally I do see diagnostics producde:

> (4,12): error CS0012: The type 'ValueType' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

This is expected given the way in which this compilation is built. Using `typeof(object).Assembly.Location` is not sufficient to build a compilation on .NET Core. That requires a bit more work. 

CC @terrajobst about constructing proper reference sets on .NET Core.
