### ISSUE TITLE
Suggestion: Allow ignored lambda parameters to have the name _

### ISSUE THREAD

**Issue by erik-kallen** [dotnet/roslyn#2397]
When writing lambdas you quite often end up not caring about all parameters, but you need names for them anyway. In F# you can use `_` as the name for such parameters, and that is also possible in C# but only as long as there is only one such parameters. If there is more than one you need to come up with names (or use names such as `_1`, `_2` etc).

My suggestion is to allow multiple symbols in the same scope be named `_`. Of couse, when doing this you can't use any of the symbols with that name, but it will enable you to write things like `MyMethod((a, _, _) => a + 1)` which is sometimes convenient (especially when using mocking libraries).

**Comment by AdamSpeight2008** [comment]
Doesn't work for vb.net `_` is the line continuation character,

**Comment by xbelt** [comment]
Well it does not necessarly need to be the underscore. I could also imagine somethind like:
(a, ?,?) => a + 1
or simply
(a, ,) => a + 1
Personally I find this a nice idea

**Comment by HaloFour** [comment]
Check out #20 and #2145.

Since the pattern matching spec is very likely to include a wildcard, which thus far as been `*`, I'd recommend reusing that character in these cases.

Note that `_` is a legal identifier today.  Changing the meaning would break code.  The C# team is a lot less willing to do this than the Java team (where this very transition is already underway).

**Comment by AdamSpeight2008** [comment]
@xbelt I also like the look of the second option `(a, , )`, as I think of that form of syntax as a tuple. It is a `tuple<parameter,parameter,parameter>`

**Comment by erik-kallen** [comment]
My suggestion is for C# although it might be useful for vb too but I don't use that language,

Using the underscore for this would not be a breaking change in C# as long as the rule is specified to be that "if more than one symbol in a scope has the name _, an error is not issued but none of those symbols can be accessed". It is not a breaking change because such program is illegal today.

**Comment by HaloFour** [comment]
Maybe, but it would be silly to have multiple wildcard operators in different contexts.  If pattern matching is going to use `*` then it doesn't make sense for parameter ignoring to use `_`, especially since `_` is a perfectly legal C# identifier.

**Comment by aluanhaddad** [comment]
@HaloFour Yes, the syntax should definitely align with that of pattern matching

**Comment by gulshan** [comment]
This is probably done now with `_` discard.

**Comment by alrz** [comment]
Not just yet. AFAIK it only works on type switch, deconstructors, and simple assignments.

**Comment by jcouv** [comment]
I'll go ahead and close this language proposal in favor of the one in the csharplang repo https://github.com/dotnet/csharplang/issues/111
Thanks
