### ISSUE TITLE
PtrDiff between pointers generate DIV with 1

### ISSUE THREAD

**Issue by fanoI** [dotnet/roslyn#23988]
**Version Used**: 
VS 15.5.2

**Steps to Reproduce**:
During our work in the Cosmos AOT compiler we had encountered this function used in UTF8Encoding class:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Text/UTF8Encoding.cs#L794

it seems that there is a problem in the optimization of this code as the IL generated is this:

```
IL_0000: nop
IL_0001: ldarg.0
IL_0002: ldarg.1
IL_0003: sub
IL_0004: ldc.i4.1
IL_0005: div
IL_0006: conv.i8
IL_0007: conv.u4
IL_0008: ldc.i4.1
IL_0009: shr.un
IL_000a: stloc.0
IL_000b: br.s IL_000d
IL_000d: ldloc.0
IL_000e: ret
```

ILSPY decompile this IL in C# in this way that makes no sense:

```cs
private unsafe static int PtrDiff(char* a, char* b)
{
    return (int)((uint)((long)((a - b) / 1 * 2)) >> 1);
}
```

That is not the hyper optimized code that this complicated casting wanted to obtain...

**Expected Behavior**:
No DIV by 1 should be present

**Actual Behavior**:
DIV by 1 is present

**Comment by mikedn** [comment]
I don't get it, what exactly is the problem? That the compiler did not eliminate the useless div?

> ILSPY decompile this IL in C# in this way that makes no sense:

Surely the fact that ILSPY is broken isn't the C# compiler's problem.

**Comment by fanoI** [comment]
The problem is that trying to optimeze the compiler **generates a div** in the original C# code there was not a div but in IL it is: 

```cs
return (int)(((uint)((byte*)a - (byte*)b)) >> 1);
```

**Comment by mikedn** [comment]
> The problem is that trying to optimize the code

But it that code compiled with optimizations enabled? The nop at the start and the branch at the end make me think that the code is compiled with `/o-`.

**Comment by fanoI** [comment]
It is code part of CoreRT so I imagine it has been compiled with optimizations enabled.

**Comment by mikedn** [comment]
Let's try some simple code:
```C#
static long Test(byte* a, byte* b) => b - a;
```
when compiled with `/o+` generates
```
  .method private hidebysig static int64
          Test(uint8* a,
               uint8* b) cil managed noinlining
  {
    // Code size       7 (0x7)
    .maxstack  8
    IL_0000:  ldarg.1
    IL_0001:  ldarg.0
    IL_0002:  sub
    IL_0003:  ldc.i4.1
    IL_0004:  div
    IL_0005:  conv.i8
    IL_0006:  ret
  } // end of method Program::Test
```
So yes, the C# compiler generates a useless `x div 1` even when optimizations are enabled. Fortunately the JIT removes it.

**Comment by mikedn** [comment]
This also applies to explicit division - `long Test(long x) => x / 1;` also generates a useless `div` instruction. `x + 0` and `x * 0` do not generate useless instructions.

**Comment by Therzok** [comment]
> `x * 0`

Do you mean `x * 1`?

**Comment by tannergooding** [comment]
`x * 0` is also useless, it should always return 0.

Hopefully `x * 1` also doesn't generate anything useless, since it should always return `x`

**Comment by mikedn** [comment]
> Do you mean x * 1?

Nope. But now that you mentioned it, I checked that `x * 1` also does not produce a useless instruction. Same for `x >> 0` and `x << 0`.

Funnily enough, `x | 0`, `x & 0` and `x ^ 0` do produce useless instructions. `x ^ 0` even manages to pass through the JIT unharmed and ends up producing a glorious `xor eax, 0` :smile:

**Comment by fanoI** [comment]
This case of PtrDiff() and of:
```cs
static long Test(byte* a, byte* b) => b - a;
```
are more "wrong" as there no explicit DIV here; in case of "x / 1" one could argue than at least in debug mode could be correct to generate DIV opcode, but in these two cases where DIV comes from?

Well why Roslyn does not optimize IL in release mode well it is continues source of comments... why AOT compiler (as IL2CPU and CoreRt) or the Jitter should be fed with unuseful instruction and optimize the assembler?

**Comment by tannergooding** [comment]
> why AOT compiler (as IL2CPU and CoreRt) or the Jitter should be fed with unuseful instruction and optimize the assembler?

The AOT/JIT should generally try to produce good code, regardless of what IL it is given. Good IL should only help it more by reducing the work it needs to do.

**Comment by mikedn** [comment]
> but in these two cases where DIV comes from?

Well, in general pointer subtraction does involve division, it's `(addr2 - addr1) / sizeof(type)`. I wouldn't expect the compiler to make a special case out of types that happen to have size 1 and skip the division.

> why AOT compiler (as IL2CPU and CoreRt) or the Jitter should be fed with unuseful instruction and optimize the assembler?

Eh, my guess is that in this particular case the answer is simply "because nobody noticed it and bothered with fixing it".

And anyway, I expect native code generators to deal with such basic things. They have to, even if the C# compiler eliminates `x / 1` it's still possible to end up with `x / 1` at JIT time, due to other optimizations (e.g. the JIT may inline a function that returns 1).

**Comment by Suchiman** [comment]
@fanoI you should upgrade your ILSpy to 3.x, ILSpy 2.x has a lot of bugs around arithmetic that were fixed by the "new decompiler" in ILSpy 3.x. ILSpy 3.0.1 produces this code when decompiling:
```csharp
private unsafe static int PtrDiff(char* a, char* b)
{
	return (int)((uint)((byte*)a - (byte*)b) >> 1);
}
```

**Comment by gafter** [comment]
Marking this as a feature (optimization) requested for performance, however I don't have any data to back up the assumption that it would make any difference.

**Comment by gafter** [comment]
Closing as we have no evidence of an actual performance effect of the proposed change.  If you come up with any such data showing there would be a benefit, please reopen.
