### ISSUE TITLE
Unlike lambdas, local functions do not capture scripting globals

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#23996]
There are workarounds but they are irritating during what should be simple refactors. I use Roslyn Scripting the most via Cake. This issue seems to be with Roslyn itself (2.6.1).

```cs
public static class Program
{
    public sealed class Globals
    {
        public int SomeGlobal => 42;
    }

    public static async Task Main()
    {
        // Works– global captured by lambda
        var script = "var lambda = new System.Action(() => { _ = SomeGlobal; });";

        // Does not work– global captured by local function declared inside lambda
        var script = "var lambda = new System.Action(() => { void LocalFunction() { _ = SomeGlobal; } });";

        // Does not work– global captured by local function declared inside method
        var script = "void Method() { void LocalFunction() { _ = SomeGlobal; } }";

        // Works– global captured by lambda declared inside lambda
        var script = "var lambda = new System.Action(() => { var innerLambda = new System.Action(() => { _ = SomeGlobal; }); });";

        await CSharpScript.RunAsync(script, globals: new Globals());
    }
}
```

**Expected:**

Local functions capture the global; all examples run successfully.

**Actual:**

> Microsoft.CodeAnalysis.Scripting.CompilationErrorException: '(1,44): error CS0120: An object reference is required for the non-static field, method, or property 'Program.Globals.SomeGlobal''

If this is according to the spec, please make it a feature request. I don't see any reason why local functions should fail to capture globals.

**Comment by jcouv** [comment]
Tagging @agocke

**Comment by jnm2** [comment]
Can someone confirm whether this is per spec or a bug?

**Comment by agocke** [comment]
cc @tmat 

Scripting basically has its own design, so I have no idea what the expected behavior of any C# language feature is in scripting.

**Comment by jnm2** [comment]
If I submitted a PR (don't laugh 😜) would you take it?

**Comment by tmat** [comment]
@jnm2 Absolutely.

**Comment by jnm2** [comment]
@tmat When you say 'script variables,' do you mean this?

```cs
int variable = 42;

void Method()
{
    void LocalFunction()
    {
        _ = variable;
    }
}
```

**Comment by jnm2** [comment]
Ah, found it:

```cs
var script = "int someVariable = 4;";
var state = await CSharpScript.RunAsync(script, globals: new Globals());
await state.ContinueWithAsync("void Method() { void LocalFunction() { _ = someVariable; } }");
```

**Comment by jnm2** [comment]
I've traced the problem this far.

Because `currentMember` (the local function) has `IsStatic` = `true`, the receiver is determined to be `null`.

https://github.com/dotnet/roslyn/blob/467c216fa6e49b85c2bff58721115b0263f5f402/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs#L1676-L1678

Which causes this code to report `CS0120: An object reference is required for the non-static field, method, or property 'Program.Globals.SomeGlobal'`.

https://github.com/dotnet/roslyn/blob/467c216fa6e49b85c2bff58721115b0263f5f402/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs#L6166-L6169

**Comment by jnm2** [comment]
So the question is, why is LocalFunctionSymbol considered to be static?

https://github.com/dotnet/roslyn/blob/467c216fa6e49b85c2bff58721115b0263f5f402/src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs#L45-L48

**Comment by jnm2** [comment]
Removing `DeclarationModifiers.Static` causes script globals and script methods to become accessible from local functions, but not script variables.

**Comment by jnm2** [comment]
Removing `DeclarationModifiers.Static` seems to be the entire fix.

**Comment by jnm2** [comment]
3 existing tests begin failing which may shed some light.

**Comment by jnm2** [comment]
99 existing tests begin failing which may shed some light.

**Comment by jnm2** [comment]
Different tack. With an ordinary class, a local function can access an instance property because `member.ContainingType` matches `currentType`. The problem in scripting is that `member.ContainingType` is the globals type or a previous submission type, while `currentType` is the current submission type. This feels warmer:

https://github.com/dotnet/roslyn/blob/467c216fa6e49b85c2bff58721115b0263f5f402/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs#L1622

Seems like the logic that located the member from the globals type should also be responsible to intervene here.

**Comment by jnm2** [comment]
Either local functions need to be conditionally static (seems the more complex guess) or `TryBindInteractiveReceiver` should not always require a non-static `currentMember`.

**Comment by jnm2** [comment]
Yikes! It would appear that the existing code is pretty emphatic about not working with static methods, which local functions apparently are.

https://github.com/dotnet/roslyn/blob/467c216fa6e49b85c2bff58721115b0263f5f402/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PreviousSubmissionReference.cs#L16

**Comment by jnm2** [comment]
Got it!

**Comment by jnm2** [comment]
@tmat PR is up! https://github.com/dotnet/roslyn/pull/24921
