### ISSUE TITLE
Add an API to convert DebugType strings to DebugInformationFormat

### ISSUE THREAD

**Issue by pranavkm** [dotnet/roslyn#23997]
Mvc does runtime compilation which involves reading [`DependencyContext`](https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.Extensions.DependencyModel/CompilationOptions.cs) and builds `ParseOptions`, `CSharpCompilationOptions` etc from it. We recently added support for adding reading the `DebugType` and constructing an `EmitOptions` with the right `DebugInformationFormat` from it. Unlike some of the other enum types which have a string -> type converters (e.g. `LanguageVersionFacts`), parsing `DebugType` is buried inside [`CSharpCommandLineParser`](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs#L612-L641). I couldn't find any other callable pieces of code that do this and ended up effectively copying the block of code. It would nice if this is an exposed as a callable API instead.

**Comment by jcouv** [comment]
@tmat Do we have a public method to parse `DebugType` from string? If not, any concern to add one?

**Comment by pranavkm** [comment]
Closing this as this is no longer a priority for MVC.
