### ISSUE TITLE
Issue with RCS1163, unused parameter...

### ISSUE THREAD

**Issue by usmrtester** [dotnet/roslyn#24001]
.net 4.0, c# 7.2 Roslynator 1.6.10

The following line of code produces RCS1163, Unused parameter (list).  I believe this to be an error as 'list' is required for this lambda expression.

`    
lReasons = lReasons.OrderBy(list => ranDom.Next()).ToList();
`

**Comment by jcouv** [comment]
I think this issue belongs in Roslynator repo (which seems to be https://github.com/JosefPihrt/Roslynator).
Roslyn itself doesn't produce errors with "RCS" prefix.
Thanks

**Comment by usmrtester** [comment]
Got it, oops!  Reposted at https://github.com/JosefPihrt/Roslynator

Thanks!
