### ISSUE TITLE
[Feature Request] Offer to capture a method/property that is repeatedly invoked in a local variable

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#24008]
**Example scenario:**

```cs
var root = await context.Document.GetSyntaxRootAsync(context.CancellationToken).ConfigureAwait(false);
var semanticModel = await context.Document.GetSemanticModelAsync(context.CancellationToken).ConfigureAwait(false);
```

Placing the cursor over `context.Document` and pressing Ctrl+. should yield a code fix like

```cs
var document = context.Document;
// <first location where context.Document is referenced in the method>
...
var root = await document.GetSyntaxRootAsync(context.CancellationToken).ConfigureAwait(false);
var semanticModel = await document.GetSemanticModelAsync(context.CancellationToken).ConfigureAwait(false);
```

**Comment by CyrusNajmabadi** [comment]
@jamesqo This feature exists.  You just need to select "context.Document" and say "introduce variable for all occurrences ..."

**Comment by jamesqo** [comment]
@CyrusNajmabadi +1 for no selection needed. When you say dotted name chains, are you counting methods? I think methods calls/indexers should be allowed in the chain as well.

**Comment by CyrusNajmabadi** [comment]
> When you say dotted name chains, are you counting methods? I think methods calls/indexers should be allowed in the chain as well.

Yup. agreed.  What i don't want to do is have something like ```f$$oo + bar``` expand out to that entire expression.  For that, you'd need a selection.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We've only gotten one request for this.  The existing functionality seems totally fine here.
