### ISSUE TITLE
Microsoft.Net.Compilers langversion not passed to csc.exe by MSBuild

### ISSUE THREAD

**Issue by PhilPJL** [dotnet/roslyn#24000]
VS 2017 15.5.2
VSTS current version

1. Create any C# app
2. Use a C# 7.1 or 7.2 feature 
3. Add Microsoft.Net.Compilers 4.6.1
4. Set the advanced build settings to use the appropriate version of C#

Build locally builds fine
Check in to VSTS and build using hosted build server fails.

See: https://stackoverflow.com/questions/48050676/how-do-i-set-csc-langversion-when-building-in-vsts/48055312#48055312

**Comment by jcouv** [comment]
@srivatsn This seems to be a VSTS-specific problem. Could you take a look and advise?

**Comment by jcouv** [comment]
@srivatsn This seems to be a VSTS-specific problem. Could you take a look and advise?

**Comment by PhilPJL** [comment]
@jcouv 
Sorry for delay in replying.  

You are correct, I had only set the Langversion on the debug build.  Thanks for your help and apologies for not spotting that.
