### ISSUE TITLE
C# compiler only: does not produce complete metadata for optional `DateTime` parameter with default value `default(DateTime)`

### ISSUE THREAD

**Issue by stakx** [dotnet/roslyn#24004]
### Version Used:
Visual Studio 15.5.2

### Steps to Reproduce:

1. Compile and run the following C# program. Note that there will be a runtime error:

   ```csharp
   public class SomeType
   {
       public void Method(DateTime timestamp = default(DateTime)) { }
   }

   class Program
   {
       static void Main()
       {
           var parameter = typeof(SomeType).GetMethod("Method").GetParameters()[0];
           System.Diagnostics.Debug.Assert(object.Equals(parameter.DefaultValue, default(DateTime)));
           // Accessing `parameter.DefaultValue` will throw:
           // System.FormatException : Encountered an invalid type for a default value.
       }
   }
   ```

2.  To back up the claim that this is a problem with the C# compiler, let's do the same in VB.NET. Compile and run the following VB.NET program, which is equivalent to the above C# program. Note that there will be no runtime errors.

   ```vb
   Public Class SomeType
       Public Sub Method(Optional timestamp As DateTime = Nothing)
       End Sub
   End Class

   Module Program
       Sub Main()
           Dim parameter = GetType(SomeType).GetMethod("Method").GetParameters()(0)
           System.Diagnostics.Debug.Assert(parameter.DefaultValue = DirectCast(Nothing, DateTime))
           ' This should work just fine.
       End Sub
   End Module
   ```

I'm providing a solution containing xUnit.NET tests demonstrating the same problem in some more detail: 
[DateTimeBug.zip](https://github.com/dotnet/roslyn/files/1598858/DateTimeBug.zip)

### Expected Behavior:

Both the C# program and the equivalent VB.NET program should terminate without producing any error.

Alternatively, if C# does not actually support this scenario, i. e. `default(DateTime)` as a compile-time constant, it should produce a compile-time error.

### Actual Behavior:

Both programs compile without any errors or warnigns, but the C# program throws a `System.FormatException` with message _"Encountered an invalid type for a default value"_.

### Apparent cause:

The C# compiler does not emit a `[DateTimeConstant]` custom attribute placed on the optional method parameter like the VB.NET compiler does. Instead, it sets the default value to the `nullref` constant (like it would for any other value type). The framework (`ParameterInfo.DefaultValue`) probably doesn't expect this for `DateTime` (it expects to find the default value in a custom attribute; when `MdConstant.GetValue` retrieves a null reference from metadata for `DateTime`, it'll throw, see [here]( https://referencesource.microsoft.com/#mscorlib/system/reflection/parameterinfo.cs,617) and [here]( https://referencesource.microsoft.com/#mscorlib/system/reflection/mdconstant.cs,81) in the .NET Framework reference source).

Here's the IL metadata output (as reported by ILDASM) for the above two programs:

```
// IL output produced by the C# compiler:
.method public hidebysig instance void  Method([opt] valuetype [mscorlib]System.DateTime timestamp) cil managed
{
  .param [1] = nullref
  // ...
}
```

```
// IL output produced by the VB.NET compiler:
.method public instance bool  Method([opt] valuetype [mscorlib]System.DateTime timestamp) cil managed
{
  .param [1]
  .custom instance void [mscorlib]System.Runtime.CompilerServices.DateTimeConstantAttribute::.ctor(int64) = ( 01 00 00 00 00 00 00 00 00 00 00 00 ) 
  // ...
}
```

**Comment by HaloFour** [comment]
This sounds like a bug in the reflection code in the BCL?  If you switch out `DateTime` for some custom struct it works fine.  Well, fine enough, as `ParameterInfo.DefaultValue` returns `null` rather than an zero-initialized copy of that struct.  But in both cases invocation works, which I guess is expected as its up to the compiler to interrogate and respect that metadata.

Here's the relevant source in CoreCLR: [RuntimeParameterInfo.cs#306](https://github.com/dotnet/coreclr/blob/8c74b3bcd691d842a891bc55909a18a8b1e53200/src/mscorlib/src/System/Reflection/RuntimeParameterInfo.cs#L306)

**Comment by HaloFour** [comment]
To note, C# has never emitted the `DateTimeConstantAttribute` attribute for optional parameters as C# doesn't support embedding date/time values as default values and has no literal syntax for defining a constant date/time value.  I'd wager that allowing for default values for structs being the default value of that struct was a blanket decision and always supported by the same `nullptr` metadata in the IL, and that `DateTime` was not given special consideration by the compiler.  I'd also wager that it was not known that the CLR gave `DateTime` special consideration in this case.

**Comment by stakx** [comment]
@HaloFour, thanks for your thoughts. Your second comment has made me see the likely reason why C# doesn't emit `[DateTimeConstant]`: The C# language doesn't have `DateTime` constants, so there are no apparent immediate benefits gained by emitting the custom attribute.

I think the main question will be whether the C# compiler wants to fully honour the .NET Framework's and .NET Core's special treatment of `DateTime` default values (however flawed). In my opinion, it should:

* While invocation of methods with optional `DateTime` parameters works just fine, another valid use case does not: reflection against such parameters. Even if this is due to a bug in the platform (see e. g. https://github.com/dotnet/corefx/issues/12338), the C# compiler produces code *for* that platform, and should do its best to work around any rough edges, if it reasonably can. The VB.NET compiler proves that there's a way to make reflection work correctly.

* The C# compiler *already* does not treat all structs equally (i. e. by emitting a `nullptr` constant value) when encoding default parameter values: It has special treatment for `decimal`. Because the language supports `decimal` literals, the compiler must know to emit `[DecimalConstant]` custom attributes. So there is a precedent case, and emitting `[DateTimeConstant]` would probably be relatively easy to implement. Guessing from the various mentions of `DateTimeConstantAttribute` across the Roslyn code base, I believe the infrastructure necessary for it is already there.

(If Roslyn is determined not to fix this, I'm happy to follow up on this as a framework bug report, however I believe it'll be *much* harder to get the .NET Framework changed than the C# compiler due to back compatibility concerns.)

**Comment by stakx** [comment]
FYI, I've come to agree with @HaloFour that this is a bug in the BCL; see the PR https://github.com/dotnet/coreclr/pull/17877. I guess this present issue is no longer needed.
