### ISSUE TITLE
NET Core SDK 2.2 for Visual Studio 2017

### ISSUE THREAD

**Issue by livarcocc** [dotnet/roslyn#24019]
_From @VE-2016 on December 20, 2017 13:55_

## Steps to reproduce
I would like to build Roslyn platform from sources in Visual Studio 2017. One requirement is to install NET Core SDK 2.2 (preview). After installation of the NET Core SDK 2.2.0_Preview this version is not visible in Visual Studio 2017 in installed NetCore Frameworks

## Expected  behavior
Roslyn cannot be built because Visual Studio 2017 does not find this NET Core SDK 2.2.0 version.  How to install this version for Visual Studio 2017?

## Actual behavior
NET Core SDK 2.2 runs properly from command-line only.

_Copied from original issue: dotnet/cli#8273_

**Comment by livarcocc** [comment]
How are you installing this 2.2.0 SDK? Is it available in your PATH? VS searches for an SDK in your PATH with the version that it is looking for.

**Comment by livarcocc** [comment]
_From @VE-2016 on December 21, 2017 0:9_

After adding to the system and user environment variable Path -
C:\Program Files\dotnet\sdk (with 2.2.0-Preview1 folder)
Visual Studio builds Roslyn solution properly, but the problem probably still exists.

I have added new project to the Roslyn solution ie. MyMSBuildWorkspace, and during running program, the error occured:

SDK 'Microsoft.NET.Sdk' specified could not be found

(NET Core SDK 2.2.0 installed from file - dotnet-sdk-2.2.0-preview1-007622-win-x64.exe)

JK

**Comment by livarcocc** [comment]
You have to add just `C:\Program Files\dotnet`.

If you want to get more details about the error, running msbuild on the failing project should give you a more detailed error message. This is something that we are looking to improve in VS as well.

**Comment by livarcocc** [comment]
_From @VE-2016 on December 21, 2017 15:6_

Now, with projects from Roslyn.sln + own project MyMSBuildWorkspace - I have set:
- Path environment with C:\Program Files\dotnet
- two environmental variables VSINSTALLDIR and VisualStudioVersion   
        ( 
            var installationPath = GetVisualStudio2017InstalledPath()
            System.Environment.SetEnvironmentVariable("VSINSTALLDIR", installationPath)
            System.Environment.SetEnvironmentVariable("VisualStudioVersion", @"15.0")
         )
- one environmental variable MSBuildSDKsPath with C:\Program Files\dotnet\sdk\2.2.0-preview1-007622\Sdks

Solution compiles but when running program from MyMSBuildWorkspace (that references Roslyn MSBuildWorkspce) the following error occurs

The imported project "C:\Program Files (x86)\MSBuild\2.0\Microsoft.Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files\dotnet\sdk\2.2.0-preview1-007622\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props

When running program MyMSBuildWorkspace.exe from VS Command prompt also the same problem occurs.

**Comment by livarcocc** [comment]
You should not have to set `MSBuildSDKsPath`. VS will discover that using the path.

@jaredpar to comment on how to make this work. I don't program against Roslyn and I am not familiar with the solution there.

**Comment by livarcocc** [comment]
_From @jaredpar on December 21, 2017 17:38_

There really shouldn't be anything else required other than installing 15.5 + the specified SDK version. Our solution doesn't hook the SDK lookup in any way so it works using the normal lookup mechanisms. 

> Solution compiles but when running program from MyMSBuildWorkspace (that references Roslyn MSBuildWorkspce) the following error occurs

Are you seeing errors just compiling or when loading from a custom workspace type you've implemented?

**Comment by livarcocc** [comment]
_From @VE-2016 on December 21, 2017 21:48_

It seems to be some configuration problem indeed. Roslyn solution with additional custom project MyMSBuildWorkspace compiles properly in VS, the errors occured during running custom project MyMSBuildWorkspace that opens Roslyn.sln  workspace and loads Roslyn solution by means of OpenSolutionAsync().

With configuring:
- Path environment with C:\Program Files\dotnet
- two environmental variables VSINSTALLDIR and VisualStudioVersion   
        ( 
            var installationPath = GetVisualStudio2017InstalledPath()
            System.Environment.SetEnvironmentVariable("VSINSTALLDIR", installationPath)
            System.Environment.SetEnvironmentVariable("VisualStudioVersion", @"15.0")
         )
- one environmental variable MSBuildSDKsPath with C:\Program Files\dotnet\sdk\2.2.0-preview1-007622\Sdks

 No documents are loaded to the solution projects with errors:
The imported project "C:\Program Files (x86)\MSBuild\2.0\Microsoft.Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files\dotnet\sdk\2.2.0-preview1-007622\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props

When according to remark that MSBuildSDKsPath should not be set, with configuring only:
- Path environment with C:\Program Files\dotnet
- two environmental variables VSINSTALLDIR and VisualStudioVersion   
        ( 
            var installationPath = GetVisualStudio2017InstalledPath()
            System.Environment.SetEnvironmentVariable("VSINSTALLDIR", installationPath)
            System.Environment.SetEnvironmentVariable("VisualStudioVersion", @"15.0")
         )

The project documents are not loaded giving errors:
The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\Users\pb\Downloads\roslyn-master-new\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj (for all projects is the same)

**Comment by daveaglick** [comment]
> The imported project "C:\Program Files (x86)\MSBuild\2.0\Microsoft.Common.props" was not found. Confirm that the path in the declaration is correct, and that the file exists on disk. C:\Program Files\dotnet\sdk\2.2.0-preview1-007622\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props

FWIW I've been struggling with this same error message under different conditions for a while: https://github.com/daveaglick/Buildalyzer/issues/29. In my case it appears to happen regularly with multi-targeted projects. It's as if certain configurations reset some MSBuild props:

> It appears that MSBuildToolsVersion is getting set to "2.0" instead of "15.0" for some reason.

I've also seen this problem in other places: https://github.com/dotnet/docfx/issues/1752#issuecomment-323305211 - so far everyone seems to be dealing with it though a series of hacks. I have yet to see any real explanation for what's causing it at the MSBuild level.
