### ISSUE TITLE
NavigateTo shows no results for types in current solution for a certain period after open solution

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#24026]
_From @mavasani on April 13, 2017 23:58_

![image](https://cloud.githubusercontent.com/assets/10605811/25028526/f8046bd4-2069-11e7-97ac-b7e74a453b68.png)

I am hitting this quite often when working on Analyzers.sln from roslyn-analyzers repo. It doesn't show any results for few seconds to couple of minutes after opening the solution, even though the solution load has completed and I get coloring and intellisense for the type. Not sure if it is bug in the project system or Roslyn.

_Copied from original issue: dotnet/project-system#1992_

**Comment by davkean** [comment]
_From @mavasani on April 14, 2017 0:6_

Actually, things like find all references also doesn't work and this is reproing pretty consistently:

1. git clone github.com/dotnet/roslyn-analyzers
2. Run cibuild.cmd
3. Open src\Analyzers.sln
4. Wait for solution load to complete and open source file `\src\Microsoft.NetCore.Analyzers\Core\Microsoft.Composition.Analyzers\DoNotMixAttributesFromDifferentVersionsOfMEF.cs` - verify no squiggles
5. `Ctrl + ,` and enter DoNotMixAttributesFromDifferentVersionsOfMEFAnalyzer

Got: No results

Try Find All references and get no references found, even though it is used in unit test projects.

**Comment by davkean** [comment]
I'm not sure we could influence anything here in the project system we've added the file to Roslyn.

@CyrusNajmabadi Do you understand how this search works and where we would approach this?

**Comment by davkean** [comment]
_From @CyrusNajmabadi on May 3, 2017 5:49_

Is this normal solution loading? Or are you using anything like "deferred project load"?

**Comment by davkean** [comment]
_From @CyrusNajmabadi on May 3, 2017 5:52_

When i try those instructions, i get:

```
C:\GitHub\roslyn-analyzers [master ≡]> .\cibuild.cmd
Microsoft (R) Build Engine version 4.7.2046.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

C:\GitHub\roslyn-analyzers\RoslynAnalyzers.sln.metaproj : error MSB4057: The target "Restore" does not exist in the project. [C:\GitHub\roslyn-analyzers\RoslynAnalyzers.sln]
ERROR: The process "vbcscompiler.exe" not found.
```

**Comment by davkean** [comment]
_From @Pilchie on December 19, 2017 22:50_

Not sure how this would happen in the example above.  Go To should use all the projects, and the file shown is not part of misc files, so even if it's an evaluation only project, that type should be included in it.

**Comment by davkean** [comment]
_From @Pilchie on December 19, 2017 22:50_

@mavasani have you seen this lately?

**Comment by davkean** [comment]
Project has likely "LastDesignTimeBuildSuceeeded" set to false because design-time build hasn't finished.

**Comment by davkean** [comment]
_From @Pilchie on December 19, 2017 22:54_

Sure, but I don't think that NavigateTo listens to that - only error reporting :-/

**Comment by davkean** [comment]
Going to move this to Roslyn - we don't own this experience, and are simply using a Roslyn API. Roslyn should provide a more progressive experience here.

**Comment by CyrusNajmabadi** [comment]
@mavasani What's your current experience?  If it really is 'minutes' until navigate-to shows anything, that really needs to eb debugged to figure out what's going on.

**Comment by mavasani** [comment]
I am unable to repro this now, and in fact haven't noticed this for quite a while now. I think we are good to close this 👍

**Comment by jinujoseph** [comment]
closing this , please reopen if you see the issue again.
