### ISSUE TITLE
`in` keyword is not contextual

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#24025]
The new `in` keyword is not treated as contextual and breaks older code that used `in` as an identifier.

https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGA3AWACgUBmLAJgwGEMBvIjRrMlAFgwFkAKASjoaaCAlgDsYGURgC8GAKwFCggL5ElQA==

**Comment by tannergooding** [comment]
FYI. @OmarTawfik, @jaredpar, @VSadov, @jcouv

**Comment by OmarTawfik** [comment]
Which version of C# you tested that as legal code?

**Comment by tannergooding** [comment]
Hmmm, looks like I had `_in` and some search replace I did when moving to 7.2 changed it to `in`.

I had forgotten that `in` was a reserved keyword for generics.

**Comment by jcouv** [comment]
@OmarTawfik This looks like valid C# 7 code (just a local named "in").
```C#
public class C {
    public void M() {
        int in = 5;
    }
}
```

**Comment by OmarTawfik** [comment]
@tannergooding  `foreach(var x in collection)`
@jcouv I don't think so. Let me drop by.
