### ISSUE TITLE
Line break options ignored in C# editor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24029]
I just noticed that the C# editor is formatting my code with line breaks after curly braces, contrary to my Text Editor/C#/Code Style/Formatting/New Line options settings. This is *extremely* annoying. Appreciate a bug fix ASAP.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/155722/line-break-options-ignored-in-c-editor.html
VSTS ticketId: 529634_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎11‎/‎27‎/‎2017, 03:40 AM (37 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by lewislong** [comment]
This is a very silly issue to have not solved in over a year. Please re-prioritise this as it is extremely annoying. No other IDE has issues like this and means manually formatting all my code. Is this the 90's?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of repro.
