### ISSUE TITLE
"keyword"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24036]
Thats all the exception tells me. 

Why?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/52762/keyword.html
VSTS ticketId: 431114_
_These are the original issue comments:_

Matthew Gertz on 5/8/2017, 08:33 AM (240 days ago): <p>Thank you for your feedback! For us to investigate this further, could you please provide us with the repro steps that caused this "keyword" error to appear? We look forward to hearing from you!</p>

Andrew Stanton on 5/23/2017, 03:36 AM (225 days ago): <p>I did, but the feedback tool ate the attachment.  It looked like one of the generated and marginally useful Roslyn  `throw new ArgumentNullException(nameof(keyword))`-like statements</p>

_These are the original issue solutions:_
(no solutions)

**Comment by agocke** [comment]
Looks like the API is  SyntaxFactory.InterfaceDeclaration()

**Comment by sharwell** [comment]
@agocke My guess it's the use of this:

```
interfaceDeclaration.WithKeyword(SyntaxFactory.Token(SyntaxKind.PartialKeyword))
```

The keyword token is `interface`, not `partial`.
