### ISSUE TITLE
Extract Method give inconsistents results

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24033]
Extract Method give inconsistents results when a local function is within extracted code (used or described)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/148551/extract-method-give-inconsistents-results.html
VSTS ticketId: 523482_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎11‎/‎13‎/‎2017, 01:34 AM (51 days ago): <p>Thanks for pointing out the difference , opening this back for consideration.</p><p>Thanks for the feedback.</p>

_These are the original issue solutions:_

Jinu Joseph [MSFT] solved on ‎11‎/‎13‎/‎2017, 00:37 AM (51 days ago), 0 votes: <p>Thank you for your feedback! This issue appears to be similar  to <a target='_blank' href="https://github.com/dotnet/roslyn/issues/22550">https://github.com/dotnet/roslyn/issues/22550</a>  We recommend that you follow the reported issue for updates and fix notifications, also feel free to add your specific example in there</p>

Christophe MOMMER on ‎11‎/‎13‎/‎2017, 01:28 AM (51 days ago): 
<p>From my perspective, it seems not be the same issue. I've posted a video attached to this ticket to demonstrate my issue but here's some code :</p>

```csharp
class Program
{
    static void Main(string[] args)
    {
        var list = new List<LittleObject>();
        list.Add(new LittleObject { AValue = "a" });

        var firstA = list.FirstOrDefault(o => o.AValue == "a");
        if(firstA != null)
        {
            //Extract from here
            bool areEquals(LittleObject a, LittleObject b)
            {
                return a.AValue == b.AValue;
            };

            var secondA = list.FirstOrDefault(o => areEquals(o, firstA));
            //To here
        }
    }
}

class LittleObject
{
    public string AValue { get; set; }
}
```

<p>When I try to extract what is within the if statement, I get an inconsistent extraction proposed by visual studio (neither list of FirstA are passed as parameters to the new method, which brokes compilation).</p>
<p>Also, please note that it DOES BREAK the compilation (whereas Github issue mention that compilation is not broken). And finally, the roslyn team added the &quot;area-IDE&quot;, which seems to mean that is a visual studio issue instead of roslyn.</p>
<p>Please note I added my example to the Github thread for more informations to roslyn team.</p>

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/40191.  Have checked the above scenario and also validated we have tests for the same sort of issue.
