### ISSUE TITLE
Options ... Naming Style dialog unusable with Dark theme

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24030]
When VS is configured to use Dark theme, &quot;Naming Style&quot; dialog is unusable - text is white on light background (yet input boxes have dark background), see screenshot attached.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/155718/options-naming-style-dialog-unusable-with-dark-the.html
VSTS ticketId: 529630_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎12‎/‎3‎/‎2017, 04:48 AM (31 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
Here is the screenshot that was attached to the issue:

![image](https://user-images.githubusercontent.com/1408396/34547433-b3af7d98-f0c0-11e7-9153-cc9cb99b918e.png)

**Comment by BhaaLseN** [comment]
I don't see this issue on 15.5.2 on Win10 x64 (1607 Build 14393.1480); labels are present in Black and textboxes have a white background.
Perhaps not directly related to the Dark theme, but some other Color setting (either VS or actually Windows)?

**Comment by sharwell** [comment]
I also wasn't able to reproduce this.

@wdolek are you the one that reported this originally? If so, would you happen to have any insight into the specific theme(s) involved? Thanks (and sorry if you are not the same user)!

**Comment by Thieum** [comment]
Can reproduce in 15.7.5

![image](https://user-images.githubusercontent.com/944894/43002541-24fb61e8-8bf7-11e8-99e5-93f67bf0325d.png)

**Comment by CyrusNajmabadi** [comment]
Unable to repro.
