### ISSUE TITLE
Proposal : parametrized "new" constraints

### ISSUE THREAD

**Issue by 6opoDuJIo** [dotnet/roslyn#2404]
I'd like to be able to have constraint type parameters with specific constructor structure, like this : 
```csharp
    T FOO<T> () where T : new (string, string,int)
    {
         return new T("a1", "a2", 255);
    }
```
In some cases it would be useful, like above.

**Comment by Joe4evr** [comment]
Dupe of #2206.

**Comment by 6opoDuJIo** [comment]
Got it. Closed.
