### ISSUE TITLE
Debugger is not finding source embedded in PDB with SHA256 hash, only SHA1

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#24046]
Consuming PDB with VS 15.5.2, producing PDB with Microsoft.CodeAnalysis 2.6.1 and System.Reflection.Metadata 1.5.0.

Inserting my own embedded source for each document is working great if I use `EmbeddedText.FromStream` with `SourceHashAlgorithm.Sha1` and `MetadataBuilder.AddDocument` with the [SHA-1 guid](https://github.com/dotnet/roslyn/blob/ee2a411ff9aeb2f78da962e2abaa0b69da3f925c/src/Compilers/Core/Portable/PEWriter/DebugSourceDocument.cs#L80).

If I use `SourceHashAlgorithm.Sha256` and the [SHA-256 guid](https://github.com/dotnet/roslyn/blob/ee2a411ff9aeb2f78da962e2abaa0b69da3f925c/src/Compilers/Core/Portable/PEWriter/DebugSourceDocument.cs#L83), VS fails to find the source and even says:

> Locating source for *'original file path*'. (No checksum.)

Why would it say "no checksum" with that path?

https://github.com/dotnet/roslyn/blob/ee2a411ff9aeb2f78da962e2abaa0b69da3f925c/src/Compilers/Core/Portable/PEWriter/DebugSourceDocument.cs#L71-L73

Is something different with Dev15? Would a minimal repro be helpful?

**Comment by jcouv** [comment]
Tagging @tmat

**Comment by gregg-miskelly** [comment]
Yes. @jnm2 Please try in 15.6.

**Comment by tmat** [comment]
We think this has been fixed in VS 15.6. @jnm2 please reopen if it still reproduces.

**Comment by jnm2** [comment]
I apologize. I'll be getting back to the project in the future, and I'll certainly let you know if it's not working! Thank you for the fix!

**Comment by jnm2** [comment]
This is working fine in 2017 Update 9. I appreciate it!
