### ISSUE TITLE
Allow collapsing of multi-line verbatim strings

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#24056]
This would be especially useful in test classes, where I have a bunch of setup code that is extracted to a local const that is copied into every test. Except for the 200 lines of verbatim string, the definitions collapse down enough to be viewed on a single monitor.

**Comment by CyrusNajmabadi** [comment]
Sounds like something good for a community pr!

**Comment by CyrusNajmabadi** [comment]
This is supported:

![image](https://user-images.githubusercontent.com/4564579/198753316-cc1f0b19-ddac-415c-b40d-33c3e1339696.png)
