### ISSUE TITLE
Text Editor setting: Automatic Delimiter Highlighting have no effect in VS2017

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#24052]
Reported by @Justin Clareburt

![image](https://user-images.githubusercontent.com/12449387/34582748-e4443f46-f149-11e7-9cad-5524698fc4d6.png)

In previous versions of Visual Studio, you could turn off this setting to stop the matching brace highlighting (and matching regions, curly braces, brackets, etc).
Reference 1. Reference 2.
Now it seems there is nothing I can do to stop braces/regions/etc from highlighting when the caret is on one.
Turning off the Highlighting settings in C# Advanced doesn’t help. (They are intended for different highlighting purposes.)

![image](https://user-images.githubusercontent.com/12449387/34582762-f3b00e2e-f149-11e7-8a46-0edf7e71032d.png)
Does the Automatic Delimiter Highlighting do anything?

**Comment by jinujoseph** [comment]
from @heejaechang 
I don’t see any options for this tagger defined (http://index/?query=BraceHighlightingViewTaggerProvider&rightProject=Microsoft.CodeAnalysis.EditorFeatures&file=Implementation%5CBraceMatching%5CBraceHighlightingViewTaggerProvider.cs&line=27

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
