### ISSUE TITLE
Support TargetsTriggeredBeforeCompilation property

### ISSUE THREAD

**Issue by geeeyetee** [dotnet/roslyn#24053]
**Version Used**:
2.6.0-beta3

**Existing Related Feature**:

The following line at the end of the `CoreCompile` target in `Microsoft.[CSharp|VisualBasic].Core.targets` enables project file authors to configure a target to run if `CoreCompile` runs-- and not run if `CoreCompile` is skipped (e.g. because the output assembly is already up-to-date with respect to the code). This is very helpful for actions that need to be performed only on newly-generated assemblies. And it relieves the project developer of having to mimic the `CoreCompile` target's `Input` and `Output` attributes and cope with their variance between versions.

    <CallTarget Targets="$(TargetsTriggeredByCompilation)" Condition="'$(TargetsTriggeredByCompilation)' != ''"/>

**Desired Feature**:

A comparable `TargetsTriggeredBeforeCompilation` property (or similar mechanism) that is acted on before the `Csc` task runs would be invaluable for use cases such as updating assembly attributes in code.

**Comment by geeeyetee** [comment]
Sure! Thanks so much for looking into this. The use case I have in mind for a target to be specified in the `TargetsTriggeredBeforeCompilation` property is generating code, such as a `.cs` file with dynamic assembly attribute values using the `[WriteCodeFragment](https://docs.microsoft.com/en-us/visualstudio/msbuild/writecodefragment-task?view=vs-2017)` task.

**Comment by geeeyetee** [comment]
@jaredpar - Great question. Answering it properly led me to create a pull request to resolve this issue, as well as one to correct a documentation page. I am pasting the comment I created with the pull request to resolve this issue, https://github.com/dotnet/roslyn/pull/29671:

## What capability does `TargetsTriggeredBeforeCompilation` add?

There is more than one hook available if a target author would like a target to run before `CoreCompile` is run _or skipped_. However, it turns out that none of the available hooks will run a target _only_ before `CoreCompile` is run, but not before `CoreCompile` is skipped due to its output files being up-to-date with respect to its input files.

## Why did pre-existing hooks not provide that capability?

### `<Target Name="CustomBeforeCompile" BeforeTargets="CoreCompile">`

https://docs.microsoft.com/en-us/visualstudio/msbuild/target-build-order?view=vs-2017#determine-the-target-build-order

>  5.  Before a target is executed _or skipped_, any target that lists it in a BeforeTargets attribute is run.

### `<PropertyGroup>$(CoreCompileDependsOn);CustomBeforeCompile</PropertyGroup>`

https://github.com/MicrosoftDocs/visualstudio-docs/pull/1481

>  4.  Before a target is executed _or skipped_, if its `Condition` attribute was absent or did not evaluate to `false`, its `DependsOnTargets` targets are run.

(I created that documentation pull request just now. It adds to the related correction in an earlier pull request I issued, which was subsequently accepted and merged: https://github.com/MicrosoftDocs/visualstudio-docs/pull/1082)

## How would it be useful?

Generating code presents an inherent catch-22 with respect to incremental build. Suppose a project's output assembly must include an assembly attribute or constant for which the value can only be determined at build time, but that a change in that value alone does not necessitate recompiling the assembly. (Real-world examples of such a value: the current time, or an incrementing version number.) When compilation output files are up-to-date with respect to compilation input files, compilation can be skipped. But if a custom target in the project always writes a value to a `.cs` or `.vb` file before compilation, compilation output will never be up-to-date with respect to compilation input files. The consequence of each unnecessary compilation this causes will be a substantial penalty to build performance, and in the example of the incrementing version number, version gaps that might violate requirements (such as SemVer compliance).

**Comment by rainersigwald** [comment]
Can you not define inputs and outputs for your code-generation step, so that the target is always considered, but is usually skipped as up to date? That's the standard MSBuild approach to this sort of problem.

**Comment by geeeyetee** [comment]
Yeah, I did not include that as an “existing hook” in my comment for the PR, but in the description of this issue I alluded to the downside of that approach while describing the “existing related feature” `$(TargetsTriggeredByCompilation)`:

> it relieves the project developer of having to mimic the `CoreCompile` target's `Input` and `Output` attributes and cope with their variance between versions.

I totally agree that using `Inputs` and `Outputs` is the MSBuild way of achieving this and works well in the vast majority of cases. But for this case it makes it easy for implementations to be incorrect or to become so following updates to MSBuild. The author must create target inputs, outputs and conditions that match those of `CoreCompile`, and must ensure that his target executes after, for example, `_GenerateCompileInputs`. My PR is a one-liner and is consistent with a property already implemented in the same target. That’s my pitch! :)

**Comment by geeeyetee** [comment]
Sure! You continue to ask questions that force me to remember why I created this issue 8 months ago. :) Bear with me as I just go through things and see where it leads. So I recently authored a NuGet package that my organization uses internally to apply versioning functionality to all of our projects. It needed to work on projects that are SDK-style and old-style, and to apply versions not only to assemblies but also NuGet packages generated by 3 possible mechanisms, TFS builds (via logging commands) and in the future DACPACs. Because it could not rely on the .NET SDK, it set `$(GenerateAssemblyInfo)` to `false` and did its own thing. Importantly, in contexts where semver build metadata is supported, it incorporates an encoded build timestamp.

The initial version only supported old-style projects. While developing it I was unaware of the SDK system's inner builds, so it set properties only in-memory rather than persisting anything to files. I spent a lot of time figuring out how to keep its targets from breaking incremental build, finally managing to do so by copy-pasting the `Inputs` and `Outputs` for `CoreCompile`. That was quite verbose and subject to change over time (https://github.com/dotnet/roslyn/pull/12221 https://github.com/dotnet/roslyn/pull/19146 https://github.com/dotnet/roslyn/pull/18058), but it worked.

To be fair, the targets have since evolved work much more like you suggest instead:

```
  <PropertyGroup>
    <Ver_MainDependsOn>
      PrepareForBuild;
...
      Ver_SetAssemblyAttributes;
...
      Ver_WritePackPropsFileAndNuspecAndReadme
```

```
  <Target Name="Ver_Main" BeforeTargets="CoreCompile" DependsOnTargets="$(Ver_MainDependsOn)" />
```

```
  <Target Name="Ver_SetAssemblyAttributes"
          Inputs="$(MSBuildAllProjects);@(Ver_DeveloperFile);$(Ver_TasksAssemblyFullPath);$(MSBuildThisFileDirectory)AssemblyInfoSetAutomaticallyBeforeBuild.cs"
          Outputs="$(Ver_TempCSFile)">
```

```
  <Target Name="Ver_WritePackPropsFileAndNuspecAndReadme"
          Inputs="$(MSBuildAllProjects);$(Ver_TempCSFile);@(Ver_DeveloperFile);$(Ver_TasksAssemblyFullPath);$(MSBuildThisFileDirectory)AssemblyInfoSetAutomaticallyBeforeBuild.cs"
          Outputs="$(Ver_PackPropsPath);$(Ver_NuspecPath);$(Ver_ReadmePath)">
```



However, I still think it would be quite beneficial to have counterpart to the existing hook leveraged here https://github.com/dotnet/buildtools/blob/0fa455c550abb4f49f4830a7f2fa78609f373fd0/src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.task.targets#L6-L14. I might have been spared some of my earlier flailing, and even my more-enlightened snippets above might become a little cleaner. Note how one no longer needs to figure out how they must sandwich their targets' execution between `PrepareForBuild` and `CoreCompile`:

```
  <PropertyGroup>
    <Ver_Targets>
...
      Ver_SetAssemblyAttributes;
...
      Ver_WritePackPropsFileAndNuspecAndReadme
...
    </Ver_Targets>      
    <TargetsTriggeredBeforeCompilation>$(TargetsTriggeredBeforeCompilation);Ver_Targets</TargetsTriggeredBeforeCompilation>
```

```
  <Target Name="Ver_SetAssemblyAttributes"
          Inputs="$(MSBuildAllProjects);@(Ver_DeveloperFile);$(Ver_TasksAssemblyFullPath);$(MSBuildThisFileDirectory)AssemblyInfoSetAutomaticallyBeforeBuild.cs"
          Outputs="$(Ver_TempCSFile)">
```

```
  <Target Name="Ver_WritePackPropsFileAndNuspecAndReadme"
          Inputs="$(MSBuildAllProjects);$(Ver_TempCSFile);@(Ver_DeveloperFile);$(Ver_TasksAssemblyFullPath);$(MSBuildThisFileDirectory)AssemblyInfoSetAutomaticallyBeforeBuild.cs"
          Outputs="$(Ver_PackPropsPath);$(Ver_NuspecPath);$(Ver_ReadmePath)">
```
  
I also think the modestly simpler implementation offered by a `$(TargetsTriggeredBeforeCompilation)` would eventually help more projects "fall into" keeping their builds efficient. I will end with some examples from Microsoft and .NET Foundation public repos of the type of scenario I was trying to describe under _How would it be useful?_.

Here is a target that appears to break incremental build because it has `BeforeTargets="CoreCompile"`; no `Inputs` or `Outputs` attributes; and runs `<WriteCodeFragment... <Output TaskParameter="OutputFile" ItemName="Compile"...`: https://github.com/Microsoft/visualfsharp/blob/6014fe2cd368bed6ece20dac5719d732ec2febc0/build/targets/GenerateAssemblyAttributes.targets#L23-L72.

This final example would not be readily addressed by `$(TargetsTriggeredBeforeCompilation)`, but it is related food for thought. These `.props` files break incremental build when they use `$([System.DateTime]::Now...` in setting `$(VersionSuffix)` and/or `$(Version)`:
- https://github.com/dotnet/corefxlab/blob/6fb9e0e79789d0f46849a73354ea4d962112ddaa/tools/common.props#L4 
- https://github.com/Microsoft/ApplicationInsights-Kubernetes/blob/0dd9036e523d56d523d39fe7bf22e6109367ec6e/src/Directory.Build.props#L20-L21

Although `Microsoft.NET.GenerateAssemblyInfo.targets` tries to preserve incremental build of `CoreGenerateAssemblyInfo` and in turn `CoreCompile` when possible via a [well-placed](https://github.com/dotnet/sdk/blob/ab2176b3447e3e7820b5a340408110b6d498f907/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L117) `WriteOnlyWhenDifferent="True"` attribute, that cache-file-comparison mechanism is always invalidated if any of the properties involved changes with the system time. Here's how: The target `GetAssemblyVersion` uses `$(Version)` in setting `$(FileVersion)`, `$(AssemblyVersion)` and `$(InformationalVersion)`. `GetAssemblyAttributes` then creates 3 `@(AssemblyAttribute)` items in which metadata values are set using those properties. Finally, `CreateGeneratedAssemblyInfoInputsCacheFile` compares the hashes from the previous build's set of `@(AssemblyAttribute)` items with the current set and finds that they differ (though only because time has passed since the previous build).

**Comment by geeeyetee** [comment]
@jaredpar and @rainersigwald - Here is some additional data/explanation:

- [SO: Determine if MSBuild CoreCompile will run and call custom target](https://stackoverflow.com/questions/11667510/determine-if-msbuild-corecompile-will-run-and-call-custom-target) has been viewed ~5,800 times and the accepted answer is to use the same `Inputs` and `Outputs` as `CoreCompile`, adding the custom target's input and output items.

- Explaining the use case for `$(TargetsTriggeredByCompilation)`, @sayedihashimi [said](http://sedodream.com/2012/05/14/MSBuildHowToExecuteATargetAfterCoreCompile.aspx): 
  > ... “How to I create a target which is executed when CoreCompile is, and that is skipped when CoreCompile is skipped?” ... **This is a tricky problem to solve for the general case, but it is pretty easy in your case because CoreCompile has special built in support for this scenario.** ... at the surface it would seem that you could simply copy the Inputs/Outputs of CoreCompile but that doesn't work ...

  The challenge is extremely similar when one asks “How do I create a target which is executed _before_ CoreCompile is, and that is skipped when CoreCompile _will be_ skipped?”, except that `CoreCompile` lacks support for an analogous `$(TargetsTriggeredBeforeCompilation)`.

**Comment by jaredpar** [comment]
Closing for now. We do appreciate the scenario here but at this point we're not convinced the added complexity to the build is worth enabling this. 

Thanks for taking the time to provide the detailed proposal. If we see more scenarios that intersect with this request we will be re-considering this.

**Comment by tkreindler** [comment]
I know this is a stale issue but I'd just like to add that this seems a perfect solution and would solve the immense frustration involved in trying to match inputs and outputs with CoreCompile
