### ISSUE TITLE
Unable to get "Analyzer with Code Fix (.NET Standard)" project in VS2017

### ISSUE THREAD

**Issue by hisuwh** [dotnet/roslyn#24068]
**Version Used**: 
Visual Studio Enterprise 2017 - 15.5.2

**Steps to Reproduce**:

I have been following this tutorial: https://andrewlock.net/creating-a-roslyn-analyzer-in-visual-studio-2017/
I have installed the Visual Studio extension development workload.

**Expected Behavior**:
Able to create a new Analyzer with Code Fix (.NET Standard) project

**Actual Behavior**:
This project is missing from list.  Can only see the following:

![image](https://user-images.githubusercontent.com/4470351/34618261-2183bb92-f236-11e7-9152-523f309cf014.png)

**Comment by jmarolf** [comment]
Is ".NET Compiler Platform SDK" checked in the lower right on the installer?

![image](https://user-images.githubusercontent.com/9797472/34627724-9b8898f6-f216-11e7-8606-ee47faf0b7e5.png)

**Comment by hisuwh** [comment]
It appears I did not and this did indeed fix it.  Not sure why none of the tutorials mention this, they all just say to tick "Visual Studio extension development"
