### ISSUE TITLE
Typo in build.cmd options

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#24061]
1. Clone Roslyn master
2. build.cmd /?

```
Special Test options
  -testBuildCorrectness     Run build correctness tests
  -testDeterminism          Run determinism tests
  -testPerfCorrectness      Run perf correctness tests
  -testPerfCorrectness      Run perf tests
```

**Comment by sharwell** [comment]
@KirillOsenkov Since you have marked this as **good first issue**, can you provide some additional information regarding the typo (e.g. expected and actual output forms)?

**Comment by KirillOsenkov** [comment]
I don't know what's the correct string. @jaredpar?

**Comment by jasonmalinowski** [comment]
@KirillOsenkov What string do you at least think is wrong?

**Comment by KirillOsenkov** [comment]
Here:
```
  -testPerfCorrectness      Run perf correctness tests
  -testPerfCorrectness      Run perf tests
```

I think it should be:
```
  -testPerfCorrectness      Run perf correctness tests
  -testPerf                         Run perf tests
```

But I'm not sure if the -testPerf is the right key and it'll take me a long time to go dig through the scripts.

**Comment by jaredpar** [comment]
@KirillOsenkov your correct, it's `-testPerf`

**Comment by KirillOsenkov** [comment]
Hold on, are you sure? Is it not `-testPerfRun`? https://github.com/dotnet/roslyn/blob/master/build/scripts/build.ps1#L45

**Comment by mikkelbu** [comment]
@KirillOsenkov 

testPerf

```

**Comment by KirillOsenkov** [comment]
Yes, this bug no longer applies since the options have changed significantly.
