### ISSUE TITLE
Distiguishing auto-generated Constructor from an Custom-Constructor from IMethodSymbol.

### ISSUE THREAD

**Issue by msbasanth** [dotnet/roslyn#24066]
**Version Used**: 
Roslyn v2.6.0
VS2017 15.5

**Steps to Reproduce**:

1. Declare a class with no constructor
2. Try to analyze the constructor of the class, IMethodSymbol in an analyzer
3. We won't be able to identify whether the constructor is auto-generated Constructor or not.

**Expected Behavior**:
We should have a property to identify whether in IMethodSymbol whether a constructor is auto-generated or not.

**Actual Behavior**:
There is no way to identify whether IMethodSymbol of a constructor whether it is auto-generated or not.

Thanks
Basanth

**Comment by Joe4evr** [comment]
Thinking out loud: Wouldn't be that farfetched to include distinguishing [the generated constructor for Record types](https://github.com/dotnet/csharplang/blob/master/proposals/records.md#primary-constructor) as well, for when those become a thing.

**Comment by alrz** [comment]
@msbasanth an auto-generated constructor symbol has no `DeclaringSyntaxReferences`.

**Comment by CyrusNajmabadi** [comment]
Better would be to just check ISymbol.IsImplicitlyDeclared   I believe DeclaratingSyntaxReferences will *not* be empty.  Rather, it will point at the class/struct declaration node.

**Comment by msbasanth** [comment]
ISymbol.DeclaringSyntaxReferences is empty for both Auto-generated and normal parameterless constructors. ISymbol.IsImplicitlyDeclared also false for both the cases so I couldn't distinguish using these properties.

**Comment by CyrusNajmabadi** [comment]
> ISymbol.DeclaringSyntaxReferences is empty for both Auto-generated and normal parameterless constructors

I can't repro that.  Are you using metadata symbols or source symbols?  If the former, there is no concept of an implicitly declared constructor.  At the IL level they're all the same.

**Comment by msbasanth** [comment]
I am analyzing IMethodSymbol generated using ObjectCreationExpressionSyntax.
The analysis is happening in the source code where it checks the constructors declared in another assembly(not in the same solution) by getting the IMethodSymbol using SemanticModel.GetSymbolInfo.

protected override void Analyze(ObjectCreationExpressionSyntax syntaxNode, SemanticModel semanticModel, IReporter reporter)
{
            var symbol = semanticModel.GetSymbolInfo(syntaxNode).Symbol as IMethodSymbol;
            if (symbol == null)
            {
                return;
            }
}

**Comment by CyrusNajmabadi** [comment]
> The analysis is happening in the source code where it checks the constructors declared in another assembly(not in the same solution) 

If it's not in the same solution, then you're accessing the symbol through metadata.  And, as i mentioned earlier, there is no concept of an implicit or explicit metadata constructor.  You can validate this yourself.  just open up the IL generated for:

```c#
class C
{
}
```

vs.

```c#
class C 
{
    public C() { }
}
```

You'll see that the IL is exactly the same.

If you actually want to know if the original source code had the constructor declaration or not, you'll need to not just reference some output assembly, but actually reference an actual Compilation object containing the original source files in it.

**Comment by CyrusNajmabadi** [comment]
Note: you can validate thsi behavior yourself.  Try to analyze an object creation object that is instantiating a type that is defined within the SyntaxTree that your SemanticModel represents.  You should see an IMethodSymbol for the constructor that has appropriate DeclaringSyntaxReferences and which accurately exposes IsImplicit or not depending on if the constructor was explicitly created by teh user or not.

However, these questions only make sense for source, so you can only get accurate Roslyn answers about them if you're actually providing the source.  Roslyn (and any other tool) cannot answer these questions if you're only providing a metadata reference that it is hearing about the symbol information from.

**Comment by msbasanth** [comment]
I checked and observed as you explained for syntax tree symbols and metra data symbols. Thanks for the detailed explanation.

**Comment by msbasanth** [comment]
Closing the issue best possible solutions are already discussed.
