### ISSUE TITLE
C# 7.2 'in' keyword not listed in VS 2017 IntelliSense during defining operator

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24079]
Version:
Visual Studio 15.5.2

Steps to Reproduce:
1. type `public static explicit operator double(in`...
2. Ctrl+Space

Expected Behavior:
C# 7.2 introduces `in` keyword for operator's argument. So, `in` keyword should be listed in the IntelliSense window.

Actual Behavior:
Shown in the attached file.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/171613/c-72-in-keyword-not-listed-in-vs-2017-intellisense.html
VSTS ticketId: 542476_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_

Takumi Kadokura solved on 12/20/2017, 06:58 AM (16 days ago), 0 votes: 
<p>Add attached file</p>
<p><img src="https://developercommunity.visualstudio.com/storage/attachments/19418-screenshot.png"></p>

**Comment by jcouv** [comment]
Tagging @VSadov @OmarTawfik FYI

**Comment by jcouv** [comment]
Fix is ready for review.

**Comment by rolandh** [comment]
Is there an update available for this? I can't see any VS new releases. How did this make it through your internal testing either? Literally no one could have tested this out with all the false VS errors that are visible.

![image](https://user-images.githubusercontent.com/1109554/34753586-ca4e3cb8-f608-11e7-9e1b-36f47725571b.png)

**Comment by jcouv** [comment]
@rolandh from your screenshot (and the issue you filled), it looks like you're running into a different (and possibly worse) issue. 
Could you add `#error version· to your code and reply with a similar  screenshot  of the  diagnostic from #error squiggles? Also, could you send the detailed one or two lines VS version (from copying the VS details in about menu or clicking on Preview button in window bar)? Please add both to the bug you filled. Thanks

I suspect you ran into a setup issue, where somehow  the IDE uses  a non-15.5 compiler.
If it used  a 15.5 compiler, it would either accept the C# 7.2 features,  or it would complain about updating the language version setting to 7.2.

**Comment by jcouv** [comment]
The fix was merged for 15.6 (preview 3 I think).
