### ISSUE TITLE
Lost color on type names during copy & paste in wordprocessor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24073]
If I run a code copy &amp; paste from c# code to Wordpad, LibreOffice, Word, etc, the type names of the variables lose formatting. The names used in the declarations retain formatting. Example:

```cs
public class Student
{
   public string FullName;
}

public class School
{
   public List<Student> students = ...
}
```

"Student" used in type dclaration retain formatting. 
"Student" used in declaration of field students lost formatting!

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/173221/lost-color-on-type-names-during-copy-paste-in-word.html
VSTS ticketId: 544121_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by lorienpatt** [comment]
I am also having this issue

**Comment by ufcpp** [comment]
Any progress?
VS 15.7.2 still seems to have this issue.

**Comment by jinujoseph** [comment]
also reported [here](https://developercommunity.visualstudio.com/content/problem/324647/c-nameof-is-not-colored-correctly-when-copypasting.html)

**Comment by CyrusNajmabadi** [comment]
@olegtk Can you route to editor.  afaict, roslyn is not involved here.

**Comment by olegtk** [comment]
This is supported via a checkbox in Tools/Options/Text Editor/Advanced: https://learn.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-advanced?view=vs-2022#use-accurate-classification

**Comment by CyrusNajmabadi** [comment]
woot!
