### ISSUE TITLE
There are two 'Use auto property' warnings: IDE0032 and IDE0032WithoutSuggestion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24075]
There are two 'Use auto property' warnings: IDE0032 and IDE0032WithoutSuggestion, which creates visual clutter in IDE (repeating same information twice) and in suppression (as you have to suppress both, if you chose so).

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/175511/there-are-two-use-auto-property-warnings-ide0032-a.html
VSTS ticketId: 545927_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
@CyrusNajmabadi Do you know off hand why there would be a discrepancy here?

**Comment by CyrusNajmabadi** [comment]
Nope!  Sounds probably like a bug. Iirc the idea is to allow invoking the feature on the field or prop, but only fading/showing-dots on one item.  Likely something got screwed up with how we do the diagnostics, but it wasn't noticed until now

**Comment by chborl** [comment]
>  the idea is to allow invoking the feature on the field or prop, but only fading/showing-dots on one item

@CyrusNajmabadi @sharwell , I'm seeing the behavior Cyrus mentioned above, but I'm not seeing IDE0032WithoutSuggestion in either the light-bulb or the errors list.  I also don't see a way to suppress this diagnostic. 
![image](https://user-images.githubusercontent.com/25776963/42059117-45ec805c-7ad7-11e8-97ef-24a897d4a294.png)

Do either of you know of changes in this area that would have affected this?

**Comment by CyrusNajmabadi** [comment]
@sharwell Just did a bunch of cleanup around diagnostic descriptors.  My best guess is that this fell out from his work.  But i really don't know.

**Comment by chborl** [comment]
Closing as this appears to be fixed in previous work.
