### ISSUE TITLE
VBCSCompiler server not working in .NET Core on Windows 10

### ISSUE THREAD

**Issue by mikeharder** [dotnet/roslyn#24072]
**Version Used**: 
.NET Core CLI 2.2.0-preview1-007870

**Steps to Reproduce**:
1. Windows 10
2. Install CLI (I used the .zip version)
3. `git clone https://github.com/OrchardCMS/OrchardCore`
4. `cd OrchardCore`
5. `dotnet build --no-incremental`

**Expected Behavior**:
Compilation happens inside the `dotnet vbcscompiler.dll` process.

**Actual Behavior**:
The `dotnet vbcscompiler.dll` process is started and stays running, but it's doesn't use any CPU.  Instead, one instance of `dotnet csc.dll` is created for each project in the solution.

**Comments**
The same scenario appears to be working correctly on Ubuntu 16.04 LTS.

**Comment by jaredpar** [comment]
This is fixked now.

**Comment by jaredpar** [comment]
@mikeharder here is the PR to pull it into preview 1 https://github.com/dotnet/cli/pull/8499
