### ISSUE TITLE
View in Object Browser not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24085]
In Solution Explorer selecting dependencies, clicking on a NuGet package, there's an option &quot;View in Object Browser&quot;. However, this menu does nothing. It doesn't open the Object Browser, it doesn't give any error.

- Create a Console Application (.NET Core)
- Add a NuGet package (e.g. Microsoft.Extensions.DependencyInjection)
- In Solution Explorer, click on Dependencies, NuGet, Microsoft.Extensions.DependencyInjection
- context menu, open &quot;View in Object Browser&quot;

Nothing happens
I would expect to open the Object Browser, and to navigate to this NuGet package

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/174723/view-in-object-browser-not-working.html
VSTS ticketId: 545462_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
@Pilchie Should this be moved to project system?

**Comment by Pilchie** [comment]
The implementation of the command is in the language service.  If you can tell us what is missing from the API that the project-system should implement, then feel free.

**Comment by ChrisBashaw** [comment]
You can use VS2017 menu option instead from <View> and then <object browser> which browses all the objects then zero in on the one you want..  This works all the time, the popup context menu works on some objects but not others.

**Comment by CyrusNajmabadi** [comment]
Object browser is in maintenance mode now, and we are not making chnages here.
