### ISSUE TITLE
Move remaining samples from closed to open

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#2408]
Also, samples referencing VS SDK assemblies should all reference the same versions as the rest of Roslyn, otherwise build fails on a machine with multiple VS versions installed.

**Comment by srivatsn** [comment]
There's an internal bug assigned to @AnthonyDGreen. I'll resolve that and keep this one.

**Comment by davkean** [comment]
@AnthonyDGreen What's the status of this?

**Comment by davkean** [comment]
@AnthonyDGreen There's no traction on this and the samples are causing us grief as they are out of date and breaking builds, so I'm going to put our a PR to delete the samples in Closed. Please tell soon if you would like to do something different here.

tag @agocke

**Comment by davkean** [comment]
@jmarolf Assures me that he's going to move them - the timer is ticking... :)

**Comment by jmarolf** [comment]
:athletic_shoe:

**Comment by AnthonyDGreen** [comment]
@jmarolf and I chatted and came to an agreement. He's good to go.
