### ISSUE TITLE
Inline Refactoring Rename Issue with Regions in Visual Basic

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24087]
When I rename a Property in Visual Basic then normally a little light bulb appears and when I click on it, I can push a button to rename the property in the whole project. When the Property is within a Region or even followed by Region this doesn't work. The light bulb appears and when I click on it, it just dissapears.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/171490/inline-refactoring-rename-issue-with-regions-in-vi.html
VSTS ticketId: 542431_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as not repro.
