### ISSUE TITLE
Remove Unnecessary Usings feature doesn't take build directives into account

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24084]
Suppose some particular function calls for a specific namespace are only used within a DEBUG compiler directive. Intellisense will then apparently ignore all other code when it determines what usings are unnecessary, thereby breaking the code that's compiled under release compile mode.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/172621/remove-unnecessary-usings-feature-doesnt-take-buil.html
VSTS ticketId: 543044_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
The known solution for this is placing the using directives inside a `#if` directive. It would be interesting if the IDE operation automatically created these conditional sections when the Remove and Sort operation is used.

**Comment by tgp1994** [comment]
I was the original reporter at the VS dev community - would it be possible to just have Intellisense look at the code from the perspective of all compile modes before it decides what `using`s need to be removed?

**Comment by CyrusNajmabadi** [comment]
>  was the original reporter at the VS dev community - would it be possible to just have Intellisense look at the code from the perspective of all compile modes before it decides what usings need to be removed?

This would be very expensive to do.  Each potential preprocess path (which can grow exponentially), leads to a whole different compilation that needs to be analyzed.  

better is that if a using is only used for one config that it then only be a preprocessor group for that config as well.

**Comment by CyrusNajmabadi** [comment]
Note: as @sharwell has mentioned, this has been a known limitation/design choice that has existed in this feature since it was originally added back in VS2005 (so, basically 13+ years now).  I think the current state of affairs is reasonable.

Now, if you really would like to see this fixed, i think we would be open to accepting a community PR on this.  But i think it would be necessary to see the perf impact found on some reasonably complex code examples with some interesting cases of nested pp-directives.

**Comment by jinujoseph** [comment]
also reported [here ](https://developercommunity.visualstudio.com/content/problem/335462/code-formatting-with-conditional-compilation.html)

**Comment by dpoeschl** [comment]
Design Meeting Notes:
- We are concerned about the performance impact and the cost of implementation. We suggest using the [workaround suggested](https://github.com/dotnet/roslyn/issues/24084#issuecomment-355829182).
