### ISSUE TITLE
Migrate to the new async QuickInfo API

### ISSUE THREAD

**Issue by olegtk** [dotnet/roslyn#24094]
Since VS 2017 15.6 the editor supports new async/cross-IDE QuickInfo. IQuickInfo* API is now deprecated.
This issue tracks migrating Roslyn to the new async QuickInfo API.

**Comment by gundermanc** [comment]
Spec document for IDE Async Quick Info support can be found here: https://microsoft.sharepoint.com/:w:/t/DD_VSIDE/EZ86OPBZuwlMqOfXkF4bn7oBlOoTZhWjaHu2mDV0Tr-HHg?e=c68c0c69ee8c488d8a364ab33bc1d6fc

Please reach out with any questions.

**Comment by gundermanc** [comment]
Are we sure we want to delay this to 15.7? There is a quick info flicker regression that resulted from the underlying API change that regresses the user experience in lightbulb. The problem is that the new API does not support recomputation of the content of an already visible quick info tip, but Roslyn relies on this behavior to not block the UI thread. The flicker tends to occur when querying quick info over an error squiggle.

**Comment by jinujoseph** [comment]
cc @DustinCampbell

**Comment by CyrusNajmabadi** [comment]
> Please reach out with any questions.
I can't seem to read that doc.  Is it limited to only teh MS organization?  Any way that could be made public?

**Comment by gundermanc** [comment]
Sure! I'll try to put it up tomorrow.

**Comment by gundermanc** [comment]
Alright, it's up:

[Modern Quick Info API](https://github.com/Microsoft/vs-editor-api/wiki/Modern-Quick-Info-API) for porting the quick info provider and [Modern ToolTip API](https://github.com/Microsoft/vs-editor-api/wiki/Modern-ToolTip-API) for information about the tooltips APIs upon which they are based.

A few things to look out for:
- Roslyn's event hookup feature used hacks to remove other provider's items from quick info and swallow keystrokes to keep it alive while the user was typing. I dropped the ability to remove content from other sources, so, this feature should be re-implemented using the IToolTipService. It's designed with exactly this scenario in mind, so, there is a parameter you can pass to keep the ToolTip alive during keystroke.
- IViewElementFactoryService is a more generic form of Roslyn's IDeferredQuickInfoContent. You give us ClassifiedTextRuns that map to editor classifications and simply convert them to spans of text formatted per those classifications. The wiki has a bit more info.

Let me know if you need any more info.
