### ISSUE TITLE
IDE0032 fires for explict interface implementation of a property

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24090]
If I have explicit interface implementation, like this:

        string IDeploymentOptions.ProjectUniqueName
        {
            get { return this.projectUniqueName; }
        }

Then I get IDE0032 warning/error suggesting to use auto-property. 

I feel it should not be a warning because people use explict interface implementation for a reason, possibly as a stylistic choice (enforcing that class is used via interface only, for example).

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/175510/ide0032-fires-for-explict-interface-implementation.html
VSTS ticketId: 545926_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I'm not actually seeing an issue here.  The feature is already something you can disable with:

**Comment by CyrusNajmabadi** [comment]
Fixed with Fixed with https://github.com/dotnet/roslyn/pull/23835
