### ISSUE TITLE
vbcrlf does not work (visual basic)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24091]
vbcrlf does not seem to work in my Visial Studio/Visual Basic; it does not produce a linefeed in my code, just seems to ignore it. I have also tried vbLF but that does not work either. vbTab does however work as it shoult. But i need a linefeed in mh code when I iterate through an array. Any suggetions?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/166284/vbcrlf-does-not-work-visual-basic.html
VSTS ticketId: 537113_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by gafter** [comment]
Works for me

``` vb
Module Module1

    Sub Main()
        Console.Write("Hello" & vbCrLf)
        Console.Write("World" & vbCrLf)
    End Sub
End Module
```

**Comment by gafter** [comment]
Please reopen if you can provide a sample that demonstrates the issue.
