### ISSUE TITLE
[VB] Adjusting conditional branches for EnC.

### ISSUE THREAD

**Issue by wschae** [dotnet/roslyn#2411]
We did adjust conditional branches for C# EnC but haven't done for VB. We need a similar change for VB.

**Comment by tmat** [comment]
Can you give an example of what's wrong?

**Comment by wschae** [comment]
The repro:

1. VB console app with code below

Module Module1

    Sub Main()
        FallThroughRemap()
    End Sub

    Sub FallThroughRemap()
        Dim result As Integer = 0
        If Bar() Then
            Console.WriteLine() ' set breakpoint here, Shouldn’t be hit.
        Else
            Console.WriteLine()
        End If
        ' result = 2
        Console.WriteLine(result)

    End Sub

    Function Bar() As Boolean
        Return False ' set breakpoint here
    End Function
End Module

2. Set breakpoints at both lines indicated by the comments.
3. Start debugging.
4. At breakpoint, uncomment ' result = 2
5. Continue debugging

Expected: The code should finish executing
Actual: The debugger goest to the breakpoint inside the true part of the IF statement.

**Comment by tmat** [comment]
We are missing hidden sequence points.
