### ISSUE TITLE
Debugger inserts DisplayText instead of InsertionText.

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#24112]
1. New Console App, set a breakpoint, F5. Do not type in the editor.
2. After hitting the breakpoint, open the Watch window and type an expression.
3. Type "List" and observe that "List<>" is highlighted.
4. Press Tab to commit the "List<>" items.

Expected:
`List` inserted into watch window

Actual:
`List<>` inserted into watch window.

Interesting:
If you do the same in the main editor, `List` is always inserted. After doing this in the main editor, Debugger Intellisense starts inserting `List` instead of `List<>`

This was reported by the Pythia team who received a bug report because their CompletionProvider always inserts an InsertionText that differs from its DisplayText.

**Comment by rchande** [comment]
VS 27228.1.d15.6

**Comment by jcouv** [comment]
Tagging @cston. Can you help route and triage?

**Comment by cston** [comment]
Add @jinujoseph. This repros in Visual Studio 15.5 as well.

**Comment by ivanbasov** [comment]
It seems that it does not meet the bar for 15.6. Moving it to 15.7 for consideration.
