### ISSUE TITLE
Implementing MatchesKind and IsKind in a language independent way

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#24119]
**Version Used**: 
15.5.2
**Steps to Reproduce**:
1. I want to implement MatchesKind and IsKind in a language independent way but SyntaxKind is defined in Microsoft.CodeAnalysis.CSharp and Microsoft.CodeAnalysis.VisualBasic and I don't know how to access "Kind As SyntaxKind" which is two separate Enum's  and defined as two different Types when the compiler returns (Microsoft.CodeAnalysis.CSharp).SyntaxKind is not (Microsoft.CodeAnalysis.VisualBasi).SyntaxKind. The code below will not compile and the fix suggested is to add  Microsoft.CodeAnalysis.CSharp or Microsoft.CodeAnalysis.VisualBasic, but neither will fix the issue.

```
        <Extension>
        Public Function MatchesKind(trivia As SyntaxTrivia, ParamArray kinds() As SyntaxKind) As Boolean
            Return kinds.Contains(trivia.Kind())
        End Function
```

**Expected Behavior**:
One list with all the values and extensions in Microsoft.CodeAnalysis
**Actual Behavior**:
Two lists, one in Microsoft.CodeAnalysis.CSharp and another in Microsoft.CodeAnalysis.VisualBasic, this also breaks other extensions like "Contains" when you try to access both languages from one file.

**Comment by sharwell** [comment]
❓ Maybe I am misunderstanding the question, but can you just fully qualify the type in the extension method?

```vb
<Extension>
Public Function MatchesKind(trivia As SyntaxTrivia, ParamArray kinds() As Microsoft.CodeAnalysis.VisualBasic.SyntaxKind) As Boolean
    Return kinds.Contains((Microsoft.CodeAnalysis.VisualBasic.SyntaxKind)trivia.RawKind)
End Function
```

**Comment by paul1956** [comment]
Copying your code from above VisualBasicExtensions.Kind returns the message below but even if it didn't it does not solve the issue. I want to pass VB and C# SyntaxTrivia to one routine that can process both. The two lists have no conflicts.
![image](https://user-images.githubusercontent.com/12789369/34773717-8fc253dc-f5c1-11e7-8948-ecbd330c17cf.png)

**Comment by sharwell** [comment]
It looks like the call resolved to `Microsoft.CodeAnalysis.VisualBasicExtensions`. I was actually trying to reference `Microsoft.CodeAnalysis.VisualBasic.VisualBasicExtensions` in my example. It may need qualification or something to get the right one.

As for the underlying problem, I'm not sure there's a good solution. AFAIK we try to avoid mixing C# and VB code unless it's operating on an abstracted layer that's shared between them (e.g. `IOperation` APIs).

**Comment by paul1956** [comment]
I am trying to do an abstract layer to process structured trivia and all the code is almost identical. Why have lists with no common values unless someone intended to allow common code to process both. It makes sense to ask if a token is a  trivia. Comment no matter what language it is. Now all that code is duplicated even all the matches code exists twice.

**Comment by svick** [comment]
One approach that I think should work, but is not very nice, is to use [`RawKind`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.syntaxtrivia.rawkind):

```vb
<Extension>
Public Function MatchesKind(trivia As SyntaxTrivia, ParamArray kinds() As Integer) As Boolean
    Return kinds.Contains(trivia.RawKind)
End Function
```

**Comment by CyrusNajmabadi** [comment]
> It makes sense to ask if a token is a trivia.

Tokens are never trivia.  Tokens have trivia.  The types of the elements tell you waht they are.  i.e. trivia in any language is Microsoft.CodeAnalysis.SyntaxTrivia.  You use 'Kinds' when you need to know precisely what sort of Node, Token or Trivia you're dealing with, and that's very language specific.

**Comment by CyrusNajmabadi** [comment]
You can use .RawKind for code that wants to work across both C# and VB.

**Comment by paul1956** [comment]
Thanks RawKind makes sense I will close.
