### ISSUE TITLE
Apply implicit operator for pattern matching

### ISSUE THREAD

**Issue by Logerfo** [dotnet/roslyn#24126]
## Context
Recently, I've opened [this stackoverflow question](https://stackoverflow.com/questions/48115346/cs8121-customt-cannot-be-handled-by-a-pattern-of-type-t), which brought me to https://github.com/dotnet/csharplang/issues/1047#issuecomment-355612447.
The idea is to apply implicit operators when matching unhandleable patterns _(I really hope this word does in fact exist)_.
## Scenario
So, considering the following struct:
```c#
public struct ReadOnly<T> where T : struct
{
   private T? value;
   public T Value
   {
      get => value ?? throw new InvalidOperationException("Value not set");		
      set
      {                        
         if (this.value.HasValue)
            throw new InvalidOperationException("Value already set");

         this.value = value;        	
      }
   }

   public bool HasValue => value.HasValue;

   public ReadOnly(T? value) => this.value = value;

   public static implicit operator T?(ReadOnly<T> value) => value.value; //attention here!

   public static implicit operator ReadOnly<T>(T? value) => new ReadOnly<T>(value);

   public static explicit operator T(ReadOnly<T> value) => value.Value;
}
```
We get:
```c#
var foo = new ReadOnly<int>(2);
if (foo is int bar) { } //CS8121 An expression of type 'ReadOnly<int>' cannot be handled by a pattern of type 'int'.
if ((int?)foo is int baz) { } //Compiles and resolves true.
```
## Suggestion
When a pattern cannot be handled, the compiler should apply the implicit operator which allows the expression to be resolved, if any. If there are multiple possible implicit operators that would cover the issue, nothing should be done and the compilation error must prevail.
This is a suggestion, not a proposal, which means that no detail is final. Feel free to suggest changes or demonstrate barriers.
## Why?
The compiler has some hard code for the `Nullable<T>` to work in this scenario. Implementing this suggestion would allow the struct to have a `implicit operator T`. If so, the hard code would not be necessary anymore, and users could achieve the same behavior with any type.
## Alternative
One can just use a explicit conversion operator (cast) in order to achieve the expression resolution.
## Unanswered questions
```c#
public struct ReadOnly<T> where T : struct
{
   //...
   public static implicit operator T?(ReadOnly<T> value) => value.value;
   public static implicit operator int(ReadOnly<T> value) => value.Value is int x ? x : throw new Exception();
   //...
}
var foo = new ReadOnly<int>(2);
if(foo is int bar) { } //what should happen?
```
```c#
public struct ReadOnly<T> where T : struct
{
   //...
   public static implicit operator T?(ReadOnly<T> value) => value.value;
   public static implicit operator int(ReadOnly<T> value) => value.Value is int x ? x : throw new Exception();
   //...
}
var foo = new ReadOnly<int>(2);
if(foo is int bar) { } //what should happen?
```
```c#
public struct ReadOnly<T> where T : struct
{
   //...
   public static implicit operator T?(ReadOnly<T> value) => value.value;
   public static implicit operator T(ReadOnly<T> value) => value.Value;
   //...
}
var foo = new ReadOnly<int>(2);
if(foo is int bar) { } //what should happen?
```
* Should the base class operators be considered? If yes, should the compiler look at the hierarchy for disambiguation or not?
#
Edit1: added "Why?" and "Alternative" sections.

**Comment by jcouv** [comment]
This is a language design discussion. I'll move to csharplang. Thanks

**Comment by jcouv** [comment]
Issue moved to [dotnet/csharplang #1248](https://github.com/dotnet/csharplang/issues/1248) via [**ZenHub**](https://www.zenhub.com/)
