### ISSUE TITLE
`in` modifier available for operators?

### ISSUE THREAD

**Issue by Logerfo** [dotnet/roslyn#24123]
```c#
public static bool operator ==(in C left, C right) => true; //compiles
public static bool operator !=(ref C left, C right) => false; //CS0631: ref and out are not valid in this context
```
[Sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWAChsBmQgJnwGF8BvS/Dw24gNn2AD2AgDb4BAB0QQYAhPgC88gBQBLAHZN8wuADMYSTQhUBzABYwAlAoB8+GAgCucchU5dCRPoJFjJCabL4AITKCLqa2noGzEZmljb4OhDCUM6UAL6UQA=)

I understand that there is no harm on allowing the `in` modifier for operators, but what's the reason to not use it, then? Isn't it always faster? If so, should the compiler always make operators parameters "readonly ref", for performance optimization?

**Comment by ufcpp** [comment]
https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/readonly-ref.md

**Comment by mikedn** [comment]
>  Isn't it always faster?

No. It can be faster for large value types. For small value types and reference types there's a good chance to end up being slower.

**Comment by Logerfo** [comment]
@mikedn what if the type isn't known? for example:
```c#
public struct S<T> where T : struct
{
   public T value { get; }
   public S(T t) => value = t; //should 'in' be used here?
}
```

**Comment by ufcpp** [comment]
even for large value types, if the method is inlined, in parameter is no longer faster.

**Comment by Logerfo** [comment]
@ufcpp are operator methods inlined by default?

**Comment by mikedn** [comment]
> what if the type isn't known? for example:

Good question. If you have some idea about what types may be used then you may be able to make a choice. If not, you're out of luck. Personally I'd stay away from in/ref by default, I'd use them only when perf measurements indicate that they're an improvement.

Another problem is that the actual performance my depend on the target OS/architecture. The way parameters are passed around is different between x64 win, x64 unix, x86, arm etc.

> even for large value types, if the method is inlined, in parameter is no longer faster.

Hmm, could be. I wouldn't be surprised if the JIT screws things up in certain situations.

> are operator methods inlined by default?

Nothing is inlined by default. If the method is small enough the JIT may inline it.

**Comment by Logerfo** [comment]
Thank you for your time! I'm closing this.
