### ISSUE TITLE
Add "IndentNamespace" formatting option.

### ISSUE THREAD

**Issue by Chaser324** [dotnet/roslyn#24129]
Some people, myself included, prefer to not indent namespace contents. Currently, I don't think the formatting options to enable this are really exposed.

**Comment by Yanpas** [comment]
I guess new method AddNamespaceIndentationOperation should be added `src\Workspaces\CSharp\Portable\Formatting\Rules\IndentBlockFormattingRule.cs`.

Didn't manage to build roslyn yes and don't know how to run code formatting for some test .cs file.

**Comment by kendrahavens** [comment]
Request on developer community for namespace formatting option as well as class formatting option: https://developercommunity.visualstudio.com/content/idea/537886/option-to-disable-indentation-of-namespace-and-cla.html

>Most C# files are really hard to diff on laptop screens, as the lines are very long.
> As most people use 4 spaces to indent, we loose 4 horizontal character spaces just for the namespace offset (you really have to specify a namespace), and another 4 for class offset. While the later sometimes actually makes sense, as devs put trivial types like delegates next to the main class, the former is a complete waste of space, as pretty much no files have more than 1 namespace.

> Could we, please, have an option in Settings -> Text Editor -> C# -> Code Style -> Formatting -> Indentation to disable those two indents similar to the one for case constructs inside switch statements?

> E.g. with both off that:
```csharp
namespace Sample {
    class Foo {
        public void Bar() => Console.WriteLine("Hello world!");
    }
}
```
would turn into:

```
namespace Sample {
class Foo{
public void Bar() => Console.WriteLine("Hello world!");
}
}
```
> I was just trying JetBrains Rider, and that feature works great there.


....
Personally, I do think this option allows users to eliminate a ton of unused whitespace.

**Comment by sttz** [comment]
All the C# files I write have a namespace and only one namespace. I'm really used to not wasting this indent that does not serve legibility.

This is an option that got removed from Visual Studio for Mac when it switched to Roslyn. adding these options would allow VS for Mac to regain some feature parity to before it introduced the new editor.

I was evaluating switching back from VSCode to VS for Mac for performance reasons but this missing feature is a blocker for me.

**Comment by jinujoseph** [comment]
also requested at [DC ](https://developercommunity.visualstudio.com/content/problem/739051/an-option-to-disable-indenting-namespace-contents.html)

**Comment by jinujoseph** [comment]
Design Review Meeting Notes

The scenario doesn't sound compelling to add more options to core formatter. We are going to prioritize making the formatter API to allow others to add these sorts of one-off formatting tracked here #31691

**Comment by sharwell** [comment]
This went to a design review, and our conclusion was to let this scenario fall under the umbrella of #31691. We will keep this issue open as a validating scenario for the new API, but not directly implement the requested option in Roslyn itself. The new API will allow users to implement complicated customizations to formatting relevant for particular projects without the high risk of regressions associated with large numbers of individual formatting configuration options.

**Comment by derwaldgeist** [comment]
I want to chime in on this. Just recently, the uncrustify extension has been pulled from the VSCode marketplace, which let me look for alternatives. However, all my files are formatted with namespaces not being indented, since this was supported by uncrustify. Any chance to implement this in the near future? I am asking because this issue is now 3 years old...

**Comment by CyrusNajmabadi** [comment]
There is almost no chance we would implement this. It may be the case we create an extensibility later for formatting. But it would not be got a while. 

I am championing adding `namespace x.y.z;` to the language though. So that would help.

**Comment by JC3** [comment]
Can we please have this? It's very weird (to me) that it isn't an option (but "indent case labels" is?); it seems rather basic.

- https://developercommunity.visualstudio.com/t/An-option-to-disable-indenting-namespace/739051
- https://developercommunity.visualstudio.com/t/I-need-an-Indent-Namespace-Contents-pr/1433229 (https://github.com/dotnet/roslyn/issues/53725)
- https://developercommunity.visualstudio.com/t/Add-namespace-indentation-option-to-C-e/1442122
- https://developercommunity.visualstudio.com/t/Editor-Config---Cant-suppress-namespace/405612
- https://developercommunity.visualstudio.com/t/Smart-indent-in-C--works-incorrectly/62618 (related)
- https://developercommunity.visualstudio.com/t/Option-to-disable-indentation-of-namespa/537886
- https://developercommunity.visualstudio.com/t/Option-to-not-indent-C-namespace/1189252
- https://github.com/dotnet/roslyn/issues/16343
- https://github.com/dotnet/roslyn/issues/4351 (related)

**Comment by JC3** [comment]
> This went to a design review, and our conclusion was to let this scenario fall under the umbrella of #31691. We will keep this issue open as a validating scenario for the new API, but not directly implement the requested option in Roslyn itself. The new API will allow users to implement complicated customizations to formatting relevant for particular projects without the high risk of regressions associated with large numbers of individual formatting configuration options.

That seems like a lot of work. Also it's been a couple of years. How about just a basic "indent namespaces" option in the editor indenting preferences in the mean time... ?

**Comment by CyrusNajmabadi** [comment]
As stated: > I am championing adding namespace x.y.z; to the language though. So that would help.

This is championed here: https://github.com/dotnet/csharplang/issues/137 
With implementation in progress here: https://github.com/dotnet/roslyn/pull/48937

**Comment by ryzngard** [comment]
@CyrusNajmabadi after the addition of namespace style and analyzer/diagnostic, is there more work here? I think with https://github.com/dotnet/csharplang/issues/137 in and our IDE experience updated this has a compelling experience without updating the formatter

**Comment by CyrusNajmabadi** [comment]
I agree. The addition of this language feature provides a first class way for customers to have Namespace declaration that will not indent.

**Comment by kamyker** [comment]
3 years later Unity still uses C# 9.0, Rider had this option for years. VS formatter breaks completely when file uses Rider formatter and this option enabled.

In other words everyone has to use Rider to get this feature in 2024...

**Comment by sharwell** [comment]
@kamyker I would recommend filing that as a Unity bug. There isn't much we can do from our side. Adding options to the formatter has proven to be impractical and generally a mistake in the long term due to mathematical impossibilities in testing.

**Comment by CyrusNajmabadi** [comment]
@kamyker if you don't want indented namespaces, just use file-scoped-namespaces.  Then you'll get no indent at all.  Note that file-scoped-namespaces emit the excat same code as normal namespaces.  So you can still use high compiler versions, while running successfully on older runtimes/systems.

**Comment by kamyker** [comment]
> @kamyker I would recommend filing that as a Unity bug. There isn't much we can do from our side. Adding options to the formatter has proven to be impractical and generally a mistake in the long term due to mathematical impossibilities in testing.

Bug? Simply file-scoped-namespaces are available from C# 10, not 9.

> @kamyker if you don't want indented namespaces, just use file-scoped-namespaces. Then you'll get no indent at all. Note that file-scoped-namespaces emit the excat same code as normal namespaces. So you can still use high compiler versions, while running successfully on older runtimes/systems.

For some reason they are not treated the same and break Unity's component system. Probably as C# 10 is not supported:
1. Unity embeddeds older C# compiler (workaround: upgrade manually in Unity installation)
2. Unity generates csprojs with langVersion 9 (workaround: change source of Unity VS plugin to make it 10)

After all this mess we have next issue without workarounds:

3. After changing namespace{} to namespace; Unity components break. For some reason they are not treated the same. This is a bug sure but Unity won't fix it as they don't support C# 10.
Before:
![image](https://github.com/dotnet/roslyn/assets/9093037/c3008dfb-b7de-4801-9c33-d8a79d8e7e35)
After:
![image](https://github.com/dotnet/roslyn/assets/9093037/003231c5-ed30-433d-990b-30c94907d5f4)

**Comment by CyrusNajmabadi** [comment]
> For some reason they are not treated the same and break Unity's component system. Probably as C# 10 is not supported: 

This seems like something you should bring up with unity.  I created file scoped namespaces for precisely this sort of scenario.  But we're not going to invest in tooling to work around people not moving to newer versions of the language.

**Comment by kamyker** [comment]
2025 and Unity still uses C# 9, I guess it's time to get rider again...
