### ISSUE TITLE
Compilator using wrong extension method

### ISSUE THREAD

**Issue by Tasteful** [dotnet/roslyn#24121]
**Version Used**:  

- Visual Studio 15.5.2 bundled version.
- .NET Framework 4.6.1 class library

**Steps to Reproduce**:

1. Create extensions method that have overloaded "Generic<T>" type
2. Use the non generic type
3. Compile

**Expected Behavior**:
Compilation selecting correct method.

**Actual Behavior**:
Compilation selecting wrong method. This code is always using the "Generic<T>" method.

**Code samples**
```c#
using System.Collections.Generic;
using Xunit;

namespace ClassLibrary5.Test1
{
    public class Test1Class
    {
        [Fact]
        public void Should_be_generic()
        {
            var item = new object();
            Assert.Equal("generic", item.GetItemsHashCode());
        }

        [Fact]
        public void Should_be_dictionary()
        {
            var item = new Dictionary<string, int>();
            Assert.Equal("dictionary", item.GetItemsHashCode()); // Assert will fail, return type is "generic"
        }
    }

    public static class Extensions
    {
        public static string GetItemsHashCode<TKey, TValue>(this IDictionary<TKey, TValue> dictionary)
        {
            return "dictionary";
        }

        public static string GetItemsHashCode<T>(this T self)
        {
            return "generic";
        }
    }
}
```

VS is showing 
![image](https://user-images.githubusercontent.com/357589/34718449-f6062a78-f536-11e7-826d-59efe5e04d6d.png)

IL Spy is showing 
![image](https://user-images.githubusercontent.com/357589/34718463-ff0d5a2e-f536-11e7-9052-df8144d67541.png)

Code that is working
```c#
using System.Collections.Generic;
using Xunit;

namespace ClassLibrary5.Test3
{
    public class Test3Class
    {
        [Fact]
        public void Should_be_generic()
        {
            var item = new object();
            Assert.Equal("generic", item.GetItemsHashCode());
        }

        [Fact]
        public void Should_be_dictionary()
        {
            var item = new Dictionary<string, int>();
            Assert.Equal("dictionary", item.GetItemsHashCode());
        }
    }

    public static class Extensions
    {
        public static string GetItemsHashCode<TKey, TValue>(this Dictionary<TKey, TValue> dictionary) // <-- Changed param type
        {
            return "dictionary";
        }

        public static string GetItemsHashCode<T>(this T self)
        {
            return "generic";
        }
    }
}
```
or
```c#
using System.Collections.Generic;
using Xunit;

namespace ClassLibrary5.Test2
{
    public class Test2Class
    {
        [Fact]
        public void Should_be_generic()
        {
            var item = new object();
            Assert.Equal("generic", item.GetItemsHashCode());
        }

        [Fact]
        public void Should_be_dictionary()
        {
            var item = new Dictionary<string, int>();
            Assert.Equal("dictionary", item.GetItemsHashCode());
        }
    }

    public static class Extensions
    {
        public static string GetItemsHashCode<TKey, TValue>(this IDictionary<TKey, TValue> dictionary)
        {
            return "dictionary";
        }

        public static string GetItemsHashCode(this object self) // <-- Changed param type
        {
            return "generic";
        }
    }
}
```

**Comment by HaloFour** [comment]
This is the correct behavior.  The compiler is going to choose the overload with the more specific argument types after the generic type arguments have been inferred, and `GetItemsHashCode(Dictionary<string, int>)` is more specific than `GetItemsHashCode(IDictionary<string, int>)`.

**Comment by Tasteful** [comment]
@HaloFour That is what I expect, but if you compare this 2 methods that not is working
```c#
    public static class Extensions
    {
        public static string GetItemsHashCode<TKey, TValue>(this IDictionary<TKey, TValue> dictionary)
        {
            return "dictionary";
        }

        public static string GetItemsHashCode<T>(this T self)
        {
            return "generic";
        }
    }
```
the compiller is selecting the `GetItemsHashCode<T>(this T self)` instead of `GetItemsHashCode<TKey, TValue>(this IDictionary<TKey, TValue> dictionary)`. The `GetItemsHashCode<TKey, TValue>(this IDictionary<TKey, TValue> dictionary)` is for me the overload with the more specific arguments.

OfCorse the `GetItemsHashCode<T>(this T self)` will be translated into `GetItemsHashCode(Dictionary<string, int> self)` that is more specific than `GetItemsHashCode(IDictionary<string, int> self)`.

Will that mean that we should avoid extension methods like `GetItemsHashCode<T>(this T self)` if any plan to have overrides of the method exists?

**Comment by HaloFour** [comment]
@Tasteful 

The overload resolution applies after the generic type arguments are inferred, so the overload that accepts `T` will be more specific than the overload that accepts `IDictionary<TKey, TValue>`.

> Will that mean that we should avoid extension methods like `GetItemsHashCode<T>(this T self)` if any plan to have overrides of the method exists?

Having been bit by this myself I would probably recommend avoiding generic extension methods on `T`.  It's probably better to have a non-generic fallback that just accepts `object`.  Unfortunately you can't avoid boxing in those cases, at least until the compiler starts to consider generic type parameter constraints in overload resolution and then you could have a generic implementation that accepts `T : struct`.
