### ISSUE TITLE
Expose ITypeSymbol.IsSerializable as a public API

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#24133]
**Version Used**: 2.6.0

**Steps to Reproduce**:

Implementation of FxCop rule [CA2235](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2235-mark-all-non-serializable-fields): "Mark all non-serializable fields" requires us to detect if a type is serializable or not. Due to the fact that there are large number of types in metadata (primitive types, DateTime, nullable types, etc.) that are **TypeAttributes.Serializable** (see http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/Metadata/PE/PENamedTypeSymbol.cs,2045) but do not have a `SerializableAttribute`, we cannot detect all such serializable types from metadata. See https://github.com/dotnet/roslyn-analyzers/issues/1510. It would be helpful to expose this property on `ITypeSymbol`.

**Comment by tmat** [comment]
Isn't PENamedTypeSymbol supposed to synthesize the attribute if the metadata flag is set?

**Comment by mavasani** [comment]
> Isn't PENamedTypeSymbol supposed to synthesize the attribute if the metadata flag is set?

It doesn't seem to be doing so. The analyzer is already looking for the attribute, which is correctly set for source types, but doesn't seem to be synthesized for any metadata type.

**Comment by jinujoseph** [comment]
@jcouv for triage

**Comment by jcouv** [comment]
`PENamedTypeSymbol` is indeed supposed to synthesize the attribute if the metadata flag is set. But it currently doesn't. That's tracked by https://github.com/dotnet/roslyn/issues/3898

I'll close the present issue and add a note to that older bug to raise priority.
