### ISSUE TITLE
Event handler references should be counted correctly for derived WPF controls

### ISSUE THREAD

**Issue by rorsulak** [dotnet/roslyn#24146]
**Version Used**: 
Visual Studio Enterprise 2017 version 15.5.2
.NET framework 4.6.2
Visual Studio Enterprise 2015 version 14.0.25425.01 Update 3

**Steps to Reproduce**:
1. Create WPF App.
2. Create derived control (e.g. from Button)
3. Use it in XAML
4. In XAML add any event handler for derived control

Code behind:
```cs
public class MyButton : Button
{
}

public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
    }

    private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
    {
    }
}
```
XAML:
```xaml
  <local:MyButton Click="ButtonBase_OnClick">Wow</local:MyButton>
```
**Expected Behavior**:
CodeLens should show 1 reference for added event handler.
Also [CA1811: Avoid uncalled private code](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1811-avoid-uncalled-private-code) should pass.

**Actual Behavior**:
CodeLens shows 0 references for added event handler.
[CA1811: Avoid uncalled private code](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1811-avoid-uncalled-private-code) is violated.

**Remarks**:
If in XAML instead of MyButton is used not derived Button (``<Button Click="ButtonBase_OnClick">Wow</Button>``), reference count is correct and CA1811 is not violated.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.
