### ISSUE TITLE
Leading underscores in numeric literals (C#7.2 Feature) has squiggly underline error. (likely setup issue)

### ISSUE THREAD

**Issue by rolandh** [dotnet/roslyn#24140]
**Version Used**: 
VS 2017: Version 15.6.0 Preview 1.0
Compiler: C# 7.2

**Steps to Reproduce**:
1.  Make a new project with C# 7.2 and the following line of code
`int binaryValue = 0b_0101_0101;`

**Expected Behavior**:
No warnings or squiggly underlines

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/1109554/34753707-5f3db394-f609-11e7-907e-e59fbc7aee1b.png)
Error indicated however no build errors and application runs as expected.

**Comment by jcouv** [comment]
@rolandh Sorry you're running into this problem. I suspect there is some fairly unique issue with your setup, as I've been using 15.6 previews for the last month with no such trouble.
Below is my attempt to repro (which works as expected). 
Please add your VS information and also `#error version` diagnostic to help troubleshoot. Thanks

`in` with language version 7.0:
![image](https://user-images.githubusercontent.com/12466233/34763679-dde6f412-f5a0-11e7-983e-56b342dbe729.png)

`in` and binary literal with starting underscore, with language version 7.2:
![image](https://user-images.githubusercontent.com/12466233/34763769-1d774834-f5a1-11e7-8ac6-3972da7d7119.png)

My setup is:
```
Version 15.6.0 Preview 1.1
VisualStudio.15.Preview/15.6.0-pre.1.1+27205.2004
```

And here's my `#error version` diagnostic:
![image](https://user-images.githubusercontent.com/12466233/34763818-54b481a4-f5a1-11e7-9ae1-a43b3991c9ca.png)

**Comment by jcouv** [comment]
@rolandh One more thing, could you email me at jcouv@microsoft.com with a reference to the present issue if you'd be available for a live troubleshooting session (desktop sharing via Skype if that's possible for you)? We'll arrange some time.

**Comment by jcouv** [comment]
@rolandh I chatted with some folks from setup and they asked if you could also share some setup logs with us: 
Run this collection program, http://aka.ms/vscollect.exe and share %temp%\vslogs.zip
Thanks!

**Comment by rolandh** [comment]
Sent you an email with the logs.

**Comment by jcouv** [comment]
Thanks @rolandh. Could you also check the `#error version` output (as I showed in a screenshot)?

@cston Is it correct that the nullable ref type preview bits are based on a pre-C# 7.2 codebase? Roland has installed that a preview of nullables on 15.6 and I suspect that is why C# 7.2 features are gone.

**Comment by jcouv** [comment]
@rolandh sent me his compiler version. It is `2.6.0.62405 (4939752b)`. That's the same version I have, so the problem is not related to nullable preview bits.

**Comment by jcouv** [comment]
We've troubleshooted the issue. Disabling ReSharper fixed the issue.
I'll go ahead and close.
Cheers
