### ISSUE TITLE
AbstractEncapsulateFieldCommandHandler disables cancellation and still uses cancellation token afterwards

### ISSUE THREAD

**Issue by olegtk** [dotnet/roslyn#24153]
Something weird I noticed: AbstractEncapsulateFieldCommandHandler disables cancellation, but still uses cancellation token after that.
Some audit is required. 
First - why exactly it disables cancellation? No other similar refactoring command handlers disable it.
Second - if disabling cancellation is required, we should not use cancellation token that will never be cancelled.

**Comment by jasonmalinowski** [comment]
@sharwell has a fix for this (or something close to it).

**Comment by CyrusNajmabadi** [comment]
This doesn't appear to be the case anymore (esp. after we moved to the background wait indicator here).
