### ISSUE TITLE
FormatCommandHandler.ReturnKey.cs is not cancellable, but doesn't disable cancellation

### ISSUE THREAD

**Issue by olegtk** [dotnet/roslyn#24155]
When formatting on Return FormatCommandHandler passes CancellationToken.None:
https://github.com/dotnet/roslyn/blob/d4dab355b96955aca5b4b0ebf6282575fad78ba8/src/EditorFeatures/Core/Implementation/Formatting/FormatCommandHandler.ReturnKey.cs#L18

It should either explicitly disable cancellation or use cancellation token passed via CommandExecutionContext (in the new commanding).

**Comment by jasonmalinowski** [comment]
#24748 merged.
