### ISSUE TITLE
CA1032 cause 2 false positives which disappear as you navigate to them

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#24154]
**Version Used**: 
D15.6 Preview 2 + Manish Vasani's fxcop candidate FXCop vsix
**Steps to Reproduce**:
1. Clone Monogame from https://github.com/MonoGame/MonoGame
2. Open Monogame.Framework.Windows.sln
3. Install Microsoft.CodeAnalysis.FxCopAnalyzers.vsix to all projects from internal share.
4. Run full solution analysis
5. Once all warnings appear filter to just CA1032.
6. Navigate to CA1032. There should be just 2 warnings.

**Expected Behavior**:
Warnings stay there, or don't show up to begin with
**Actual Behavior**:
Warnings disappear after you navigate to them.

**Comment by mattscheffer** [comment]
@mavasani

**Comment by mattscheffer** [comment]
CA1034 appears to have them as well.

**Comment by mavasani** [comment]
@mattscheffer - can you please file a separate bug in roslyn-analyzers if doing an explicit build with error list in "Build Only" setting, you see any one of the following?
1. Unexpected warnings show up OR
2. Excepted warnings donot show up

**Comment by heejaechang** [comment]
@mattscheffer what do you mean by run full solution analysis?

**Comment by jinujoseph** [comment]
@mattscheffer you may want to close this if this doesn't repro with the latest 15.6
