### ISSUE TITLE
AbstractDocumentationCommentCommandHandler performs blocking wait on GetCommandState of the InsertComment command

### ISSUE THREAD

**Issue by olegtk** [dotnet/roslyn#24156]
AbstractDocumentationCommentCommandHandler performs blocking wait on GetCommandState of the InsertComment command. This can lead to a bad user experience if the command is ever placed into a context menu or toolbar.

https://github.com/dotnet/roslyn/blob/14aed138a01c448143b9acf0fe77a662e3dfe2f4/src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs#L558

**Comment by jasonmalinowski** [comment]
Ouch, yep that's bad.

**Comment by jasonmalinowski** [comment]
(I think it *is* in the right click context menu too in VB, unless @kuhlenh removed it...)

**Comment by CyrusNajmabadi** [comment]
Closing out as we no longer do this.
