### ISSUE TITLE
Properly declare NuGet dependencies on Humanizer and ICSharpCode.Decompiler

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#24162]
**Version Used**: 
2.7.0-beta3-62509-03

I'm looking at this family of NuGets and I don't see a dependency on Humanizer and ICSharpCode.Decompiler. These need to be explicitly declared on the Roslyn NuGet packages that require them (EditorFeatures?)

**Comment by KirillOsenkov** [comment]
Otherwise it's impossible to know which exact version of ICSharpCode.Decompiler to take and from where.

**Comment by KirillOsenkov** [comment]
Also need to explicitly declare dependencies on VS Editor:

```
  <package id="Microsoft.VisualStudio.CoreUtility" version="15.6.161-preview" targetFramework="net45" />
  <package id="Microsoft.VisualStudio.Language.Intellisense" version="15.6.161-preview" targetFramework="net45" />
  <package id="Microsoft.VisualStudio.Language.StandardClassification" version="15.6.161-preview" targetFramework="net45" />
  <package id="Microsoft.VisualStudio.Text.Data" version="15.6.161-preview" targetFramework="net45" />
  <package id="Microsoft.VisualStudio.Text.Internal" version="15.6.161-preview" targetFramework="net45" />
  <package id="Microsoft.VisualStudio.Text.Logic" version="15.6.161-preview" targetFramework="net45" />
  <package id="Microsoft.VisualStudio.Text.UI" version="15.6.161-preview" targetFramework="net45" />
  <package id="Microsoft.VisualStudio.Text.UI.Wpf" version="15.6.161-preview" targetFramework="net45" />
```

**Comment by KirillOsenkov** [comment]
And also check ManagedEsent.

**Comment by KirillOsenkov** [comment]
As far as I can see the actual version is https://www.nuget.org/packages/ICSharpCode.Decompiler/3.0.0.3403-beta4

**Comment by KirillOsenkov** [comment]
So this would be super nice to fix soon, because figuring out which Editor packages are needed for the Roslyn version is super hard.

@jinujoseph

**Comment by jinujoseph** [comment]
cc @jasonmalinowski

**Comment by KirillOsenkov** [comment]
@jinujoseph Just to reiterate, this is very painful for us. Would be super nice to have a fix soon, so we can reliable tell for any given Roslyn build which Editor matches it. We're juggling 15.6, 15.7 and master, and we have a fork of VS Editor for each of those, it's a terrible mess. Very hard to keep track of bits.
