### ISSUE TITLE
Determine The Hive

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#24180]
Is there a way to determine which hive an instance of VS2017 is being used whilst it running?
I need to know so I can reset it.

**Comment by AdamSpeight2008** [comment]
Sort work around it by looking the dates of the folders in `...\AppData\Roaming\Microsoft\VisualStudio` to see which had the most recent date. Yet it would be nice get it via Visual Studio

**Comment by jmarolf** [comment]
> I need to know so I can reset it.

Can you explain why you need to do this? Extensions shouldn't have special behavior based on which hive they are installed into.

**Comment by AdamSpeight2008** [comment]
@jmarolf  I'm tinkering on the vb compiler, sometimes the breakpoints are not being hit. So I reset the hive and it works again.

**Comment by jmarolf** [comment]
You can reset from the commandline using
```
"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\VSSDK\VisualStudioIntegration\Tools\Bin\CreateExpInstance.exe" /Reset /VSInstance=15.0_e0227681 /RootSuffix=NAME_OF_EXP_INSTANCE
```

**Comment by jmarolf** [comment]
The VS installation should have created a shortcut to do this for the `Exp` instance.  You just need to change this to `Roslyn` in your case

**Comment by AmadeusW** [comment]
@AdamSpeight2008 to get the instance (e.g. `15.0_e0227681`), read `InstallationID` from `devenv.isolation.ini` which is next to `devenv.exe` (VS process name)
You may also use the [VS Helper tool](https://github.com/amadeusw/vshelper) (and its source code) to get specific installation's command line etc.

**Comment by AdamSpeight2008** [comment]
Thanks @AmadeusW I look in to that. I'll wait to see if the solution to #24571 fixes the issue.
