### ISSUE TITLE
Migrate command handlers to the new editor commanding

### ISSUE THREAD

**Issue by olegtk** [dotnet/roslyn#24194]
In VS 2015 15.6 Preview3 the editor introduced a new commanding system, designed after Roslyn commading, see https://github.com/Microsoft/vs-editor-api/wiki/Modern-Editor-Commanding-API-Revisited.
This issue tracks migration of all Roslyn command handlers to the new editor commanding API.
The work is being done in PR https://github.com/dotnet/roslyn/pull/23769

**Comment by jinujoseph** [comment]
closed via #23769 , Thanks @olegtk
