### ISSUE TITLE
#pragma warning disable not functioning in shared project file

### ISSUE THREAD

**Issue by nnpcYvIVl** [dotnet/roslyn#24207]
**Version Used**: 
Microsoft Visual Studio Enterprise 2017 
Version 15.5.3
VisualStudio.15.Release/15.5.3+27130.2020
Microsoft .NET Framework
Version 4.7.02556

**Steps to Reproduce**:

#pragma warning disable does not function when it's in a file used by a shared project. See attached screenshot.

The solution is a .NET Framework project with a reference to a shared project.

![pragma warning disable not functioning in shared project file](https://user-images.githubusercontent.com/8421414/34888647-ae924c56-f790-11e7-9096-f8d3506d768b.png)

**Expected Behavior**:
No warnings should be shown in files marked with #pragma warning disable

**Actual Behavior**:
Warning are shown in files marked with #pragma warning disable

**Comment by jaredpar** [comment]
Moving to IDE as this appears to be an intellisense warning, not a build one.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
