### ISSUE TITLE
ISymbolKind.Kind: Discard missing

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#24206]
./src/Compilers/CSharp/Portable/Symbols/Symbol.cs switch case in ISymbol.Kind case SymbolKind.Discard is missing and causing an exception on Discard symbols.

**Comment by jcouv** [comment]
How did you hit this?
As far as I can tell, that method can't be reached, as every derived type (including `DiscardSymbol`) overrides the `Kind` property.

**Comment by jcouv** [comment]
@mkrueger From discussion with the team, we think that code is unreachable. Could you share more details as to how you reached that exception?
