### ISSUE TITLE
Microsoft.DiaSymReader.Native package should be added as a dependency to Microsoft.Net.Compilers package

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#2421]
Microsoft.DiaSymReader.Native package includes native binaries for the PDB support invoked by the deterministic PDB writer.
To be able to take advantage of the /features:deterministic flag the Microsoft.Net.Compilers package needs to include these two native binaries.
/cc @agocke @gafter @tmat

**Comment by KirillOsenkov** [comment]
When the native binaries are added as a separate dependency, make sure that the destination .dlls still get copied into the same folder as the compilers (duh) :)

**Comment by tmat** [comment]
Moving to post-RTM.

**Comment by tannergooding** [comment]
@tmat, is there an issue with linking the packages today, or do we need to ensure the deterministic flag is added first?
