### ISSUE TITLE
Workspace: investigate and design multiple solutions side-by-side

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#24218]
MonoDevelop/VSMac can open more than one solution side-by-side. Potentially it would be possible to rewire references across solutions to be ProjectReferences.

We should consider a design where more than one solution can be added to the workspace at a given time. I'm not saying that CurrentSolution should become CurrentSolutions, but just the AddSolution/RemoveSolution/ReloadSolution parts potentially.

I understand it would be hard to break the Workspace.CurrentSolution API, but maybe we could investigate:
1. having more than one solutions, and have a designated "current" one?
2. merge multiple solutions into a single logical CurrentSolution, basically just taking the projects from all opened solutions and merging them into one?

This would greatly help with current problems such as https://github.com/mono/monodevelop/issues/3517#issuecomment-357377904

**Comment by Therzok** [comment]
@KirillOsenkov We don't expose more than 1 Current Solution in MonoDevelop either, we switch the current solution based on the active selection in the solution pad.

**Comment by CyrusNajmabadi** [comment]
This is a large design space that needs to be handled outside of an issue.  If this is a need for this in vs4mac, we should start having meetings about what it would take to get there.
