### ISSUE TITLE
Font in Locals and Callstack windows is very tiny

### ISSUE THREAD

**Issue by t-camaia** [dotnet/roslyn#24217]
This is a fresh install of 15.6 preview 3 and the fonts in the Locals and Callstack window are unacceptably and unusually tiny

![image](https://user-images.githubusercontent.com/35243126/34899226-7363fa14-f7ac-11e7-8e4d-4ebff7dc8ed1.png)

![image](https://user-images.githubusercontent.com/35243126/34899326-1a57abae-f7ad-11e7-90bf-aad880cb5912.png)

![image](https://user-images.githubusercontent.com/35243126/34899673-297bab4c-f7af-11e7-88dc-a41604d9c946.png)

```
Version 15.6.0 Preview 3.0 [27307.3001.d15.6stg]
VisualStudio.15.IntStage/15.6.0-pre.3.0+27307.3001.d15.6stg
```

CC @jcouv

**Comment by jcouv** [comment]
@jinujoseph Do you know how to route this? This makes Caio's (our intern) machine almost unreadable.

**Comment by jinujoseph** [comment]
Following up

**Comment by jinujoseph** [comment]
moved to right team [Link ](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_queries/edit/553371/)

**Comment by jcouv** [comment]
Awesome. Thanks!
