### ISSUE TITLE
Add 'invert if' refactoring

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#24228]
We supposedly already have this written. Can we get it turned on?

@Pilchie for more context here.

**Comment by Pilchie** [comment]
See the code with the commented out export [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/CodeRefactorings/InvertIf/InvertIfCodeRefactoringProvider.cs,094ec074f4218e8d)

**Comment by alrz** [comment]
This should work with `if` statements without `else`. For me that's 90% of use cases ...

**Comment by CyrusNajmabadi** [comment]
@alrz Do you want to do the work to make the feature work with else-less ifs?

**Comment by alrz** [comment]
Sure. I recall I actually wanted to do this some time ago but got busy with other work. I'll give it a try in the coming weeks, hopefully that's not a problem? (I have a few incomplete PRs piled up rn).

**Comment by chborl** [comment]
Hi @alrz , I know you're working on a few different things right now.  Are you planning to do this one soon or should I take a look at it?

**Comment by alrz** [comment]
@chborl I'm on it. I hoped that flow analysis API makes it easier but it would help only in half of the use cases. We'd need CFGs (https://github.com/dotnet/roslyn/issues/24104) to make this precise. I'll try a mixed approach for now and iterate on that. should see if that can cover the cases I have in mind. will open the PR soon.

**Comment by jinujoseph** [comment]
closed via https://github.com/dotnet/roslyn/pull/25233
