### ISSUE TITLE
Can't use applicable_kinds.parameter in Naming conventions in Editor Config

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24221]
I'm creating a .editorconfig file for our team which includes code style settings, but also contains naming conventions.

The issue within the naming conventions is that I can't get the c# editor to show an error under a parameter which violates the rule.

Am I missing something?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/177536/cant-use-applicable-kindsparameter-in-naming-conve.html
VSTS ticketId: 547550_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
Fixed in 15.8.Preview3
