### ISSUE TITLE
Provide a contextual IntelliSense option

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#24226]
We currently preselect an item in the completion list that matches the target type of the current location. Several developers have asked that we additionally offer a 'mode' that will filter the list  to *only* items that match the target type of the current location _and_ name matching.

We can even consider always scoping the list down to matching target types unless there are none, in which case it will revert to the normal completion list.

**Comment by Dreamescaper** [comment]
Maybe it would make sense to put all such items to the top of the list instead?
I know that currently all the items are sorted alphabetically, but don't really get why.

**Comment by justcla** [comment]
@Dreamescaper, yes, it would make sense to sort by relevance, not alphabetically.

In this case, the request is for a **filter** on symbols of the matching type. So the **only** items in the list will be these such items. They will naturally be at the top (and bottom).

However, your comment would apply to the regular IntelliSense completion list sorting.

**Comment by Dreamescaper** [comment]
I understand, but i think that such request wouldn't appear at all if relevant items were shown on top.

**Comment by justcla** [comment]
@AmadeusW has done the work on the platform end.

**Comment by sharwell** [comment]
@justcla keep in mind that sorting and selection are two independent operations in completion. The behavior of either one can be modified with no impact on the other.

**Comment by justcla** [comment]
Thanks @sharwell. Yes, of course. We currently have some level of selection that attempts to pick a variable of matching type. And in VS2017, sorting is done alphabetically. (Yuck!)

What we need is neither sorting, nor selection. We need Filtering. Ie. Show me a list that ONLY contains items of the matching type.

**Comment by AmadeusW** [comment]
I understand @sharwell's vision of very good sorting algorithm, for best experience writing code.
The contextual mode of intellisense would be fantastic for exploration of the APIs, that is, reading code.
At least, contextual mode may provide insightful telemetry needed to build the best sorting algorithm.

Building contextual completion comprises of three steps:
1. VS command which can be bound to a keyboard shortcut, e.g. Ctrl+Shift+Space
2. Command handler which invokes completion in contextual mode
3. Sorting algorithm which takes under consideration the contextual mode

The following code accomplishes step 2. 
All steps may be built within Roslyn.
Ultimately, we will consider moving steps 1 and 2 into the Editor to benefit all languages.

```
[Name("Contextual completion prototype")]
[ContentType("text")]
[TextViewRole(PredefinedTextViewRoles.Interactive)]
[Export(typeof(ICommandHandler))]
class ContextualCompletion : ICommandHandler<InvokeContextualCompletionListCommandArgs>,
{
    [Import]
    private IAsyncCompletionBroker Broker;

    string INamed.DisplayName => "Contextual completion prototype";

    private CommandState GetCommandStateIfCompletionIsAvailable(IContentType contentType, ITextView textView)
    {
        return 
    }

    CommandState ICommandHandler<InvokeCompletionListCommandArgs>.GetCommandState(InvokeCompletionListCommandArgs args)
        => Broker.IsCompletionSupported(args.SubjectBuffer.ContentType, args.TextView.Roles) ? CommandState.Available : CommandState.Unspecified;

    bool ICommandHandler<InvokeCompletionListCommandArgs>.ExecuteCommand(InvokeCompletionListCommandArgs args, CommandExecutionContext executionContext)
    {
        if (!Broker.IsCompletionSupported(args.SubjectBuffer.ContentType, args.TextView.Roles))
            return false;

        var trigger = new CompletionTrigger(CompletionTriggerReason.InvokeMatchingType, args.TextView.TextSnapshot);
        var location = args.TextView.Caret.Position.BufferPosition;
        var session = Broker.TriggerCompletion(args.TextView, trigger, location, executionContext.OperationContext.UserCancellationToken);

        if (session is IAsyncCompletionSessionOperations sessionInternal)
        {
            // RealizeVirtualSpaceUpdateApplicableToSpan(sessionInternal, args.TextView); don't worry about this in prototype
            location = args.TextView.Caret.Position.BufferPosition; // Buffer may have changed. Update the location.
            session.OpenOrUpdate(trigger, location, executionContext.OperationContext.UserCancellationToken);
            return true;
        }
        return false;
    }
}
```

**Comment by scottmcm** [comment]
:+1:, this is the primary thing keeping me needing Resharper.  I make sure I have good types in my code, and can as a result often write code by mashing Ctrl-Shift-Space.

**Comment by genlu** [comment]
The original request was partially implemented by https://github.com/dotnet/roslyn/pull/34655. Closed as completed.

**Comment by justcla** [comment]
The partial implementation does not really satisfy the request.
A user should be able to invoke type-matching completion with a single shortcut, and not be required to open standard completion list first, then hunt for and activate a second feature to limit the list to matching types.

The editor team has already provided a placeholder for this feature to be activated on a single shortcut. Please re-open this issue and apply this feature to a direct shortcut. This would makes it amazing and powerful, instead of it being annoying and painful. Thanks!

**Comment by CyrusNajmabadi** [comment]
We have looked at this and do not think we want yet another shortcut to enter these experiences. Thanks for the feedback.

**Comment by CyrusNajmabadi** [comment]
> Thanks for considering it. I would suggest that, indeed, this is a feature that really does deserve (require) a dedicated shortcut.

This is not something roslyn itself is responsible for. If the platform or editor defines a new feature with a new shortcut, and they expose it through lsp, then Roslyn can implement support for it in our language server @justcla   

This would need to be driven by the platform.

> However, in any event, could you please provide a VS Command for this (automatically opening type-filtered completion list) so that users can map it themselves in the Keyboard mapping settings?

This issue is closed, and this is out of scope for Roslyn. If you want VS to do this, opening an issue within developercommunity is the way to get movement on that. Thanks.

**Comment by justcla** [comment]
Will do. Thanks very much. 
It's good that it's been implemented at the Roslyn end. That's the part we were missing last decade. 
👍
I'll see if Christian wants to pick up from here. 

Thanks again.

**Comment by AmadeusW** [comment]
I'll bring it up with the team in January, thank you @justcla for bringing this up! We'll consider how to enable this in the LSP paradigm.
