### ISSUE TITLE
IntroduceLocal should take into account parameter name when naming locals.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#2423]
Say i have:

``` c#
new TextSpan(int.Parse(a), int.Parse(b));
```

If i introduce local for `int.Parse(a)` then we should suggest calling this local 'start' because of the name of the parameter i'm calling.

**Comment by Pilchie** [comment]
Great suggestion!

**Comment by baks** [comment]
I would like to try to add this feature into introduce local refactoring, if possible.

It looks like the IntroduceLocal refactoring uses GenerateNameForExpression() in ISemanticModelExtensions.
It is a good idea for start to check whether the expression is ArgumentSyntax, next get ParameterSymbol from SemanticModel using this argument and return that parameter name?
Or maybe am I missing something?

**Comment by Pilchie** [comment]
That sounds about right to me.  @balajikris any input?

@baks: Keep in mind that the mapping from ArgumentSyntax to ParameterSymbol isn't always trivial in the case of arguments specified by name.

**Comment by balajikris** [comment]
Yep, that approach sounds right to me. As you might have already noticed, there is a `CreateParameterName` within `GenerateNameForExpression` that probably needs this tweak. Look for name generation related unit test methods at  `IntroduceVariableTests.cs and IntroduceVariableTests.vb`..

Thanks for taking a look.

**Comment by kuhlenh** [comment]
@baks are you still looking to do this? If not, I'll take it...let me know!

**Comment by baks** [comment]
I had problems with dogfooding IDE, so I didn't resolve this issue.

@kuhlenh, I'm not looking at this issue, I'm sorry that I don't stated earlier that I'm not working at this.
