### ISSUE TITLE
Consider 'value is null' instead of 'value == null' for the "Add null check" codefix

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#24237]
It's possible that there could be a custom operator defined for `==`, which could be slower than a simple pointer comparison. `is null` reads better and is guaranteed to be just a pointer comparison.

This may warrant looking into the user's code style to see if they already have a lot of `== null`s or `is null`s, to see which codefix should be offered to maintain consistency.

**Comment by MaStr11** [comment]
This is minor (and more of a detail that needs to be considered once this gets implemented), but `is null` isn't a 1:1 replacement for `== null`. This code
```
    public static void M<T>(T value)
    {
        if (value is null) { } //error CS0403: Cannot convert null to type parameter 'T' because it could be a non-nullable value type.
    }
```
does not compile, while `value == null` would. See also #23581.

**Comment by MaStr11** [comment]
For the sake of completeness, there are some more inconsistencies here (but some ight be unresolvable):

```C#
public class C {
    //struct unconstraint
    public void UnconstraintIs<T>(T v) {
        var b = v is null; //error CS0403: Cannot convert null to type parameter 'T' because it could be a non-nullable value type. Consider using 'default(T)' instead.
    }
    public void UnconstraintNull<T>(T v) {
        var b = v == null; // Fine
    }

    //class
    public void RefconstraintIs<T>(T v) where T:class {
        var b = v is null; //Fine
    }
    public void RefconstraintNull<T>(T v)  where T:class {
        var b = v == null; //Fine
    }
	
    //struct
    public void ValueconstraintIs<T>(T v) where T:struct {
        var b = v is null; //error CS0403: Cannot convert null to type parameter 'T' because it could be a non-nullable value type. Consider using 'default(T)' instead.
    }
    public void ValueconstraintNull<T>(T v)  where T:struct {
        var b = v == null; //error CS0019: Operator '==' cannot be applied to operands of type 'T' and '<null>'
    }
    public void ValueconstraintRefEquals<T>(T v)  where T:struct {
        var b = ReferenceEquals(v, null); // Fine
    }
}
``` 
[sharplab.io](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgZgATIEzoMLoG8BYAKHXPQHpKBnYAJwFcBjYdRgO2YHsO76AhmA7BSFTBmQAWdAFUuvfkJEBJGgB4AKgD4AFJvQA3AJSEx4ioYH10AI3QBeI+jA10HRhAgBuKpQCm9PTcNrgAygAMUhGoIHgCHBzcbDwchoFsHl7owNw5AJ4ADv7ohdYCALb+wIHoAOSadXb+zAKMNCVgKdyeMM3oAu68ALRZEAK2ECVWEIwlwEX+AHR4imAwtcgR9RsAZm0QwPrGTcJ0/gIwS+bkAL43Epgy8qlKwsAAcp4QWnoGJmYyBZyFYbPYnIZHE4xr5qOgAGLCfwPe4kB7UbAPNBPdAAJX8u1eDGUwDUv30RlMAHcABaBEqaEDYQHAkHWOyOZyudzfWGUREcZFAu5YyQyfGExTE95fLzk/6mdC0+noRnM4jCiygjkQqE8rx8gVC8SogCQ6NoDBYok12Ok6AAagJZi0pYJ3mSdBSAcr6AyQPxrSzWdrwVy3DC/IFgqFItFYvFEsl0Kl0vRMt8cnkFsVSuUqjUbA0mrYWm0Oi5ur1+oMkhxRt8JlMjM65gViitcGsNjYtjsCQcjpoTi4+DVLtdNajxHaZE6XUT3SJZT8vQryL7/YHWMHgaHOZCHNDeVGgiE8JEIgBGACccQA8sVBLki0emq0k2xSwNCoUIGB/D6XJ0G4J8EhgNxuF2dsSmLAYOD6Op1DGbQ6hRUUcXnOZFxJCUAFEAEdGGdDQ10pDc6T9VUAytHcNVZFswU5CV6S4fxCOIiAaF0QwoH1CBjD5BEkXQkhbiAA=)

```VB
Public Class C
    Public Sub UnconstraintIs(Of T)(v As T)
        Dim flag As Boolean = v Is Nothing
    End Sub

    Public Sub RefconstraintIs(Of T As Class)(v As T)
        Dim flag As Boolean = v Is Nothing
    End Sub

    Public Sub ValueconstraintIs(Of T As Structure)(v As T)
        Dim flag As Boolean = v Is Nothing ' error BC30020: 'Is' operator does not accept operands of type 'T'. Operands must be reference or nullable types.
    End Sub

    Public Sub ValueconstraintReferenceEquals(Of T As Structure)(v As T)
        Dim flag As Boolean = ReferenceEquals(v, Nothing)
    End Sub
End Class
```
[Sharplab.io](https://sharplab.io/#v2:DYLgbgRgNALu0BMQGoA+AFArhYBLAxgAQDCwAhgM4UkCwAUIY4VjgYQMraECqAdvgHteFGACcyuXjACSFABQB5AGaEAKgEo5YQgEFqG+kyOEAIrgC2hJeQDmu6gCEBA4AFMyvQgF5C22YQA5ARgAC0kbQyYAUV4EDmx6SMYWPCJOCEIAJVclQWExCSlZRRVVexJyKk1tPTV1JOMzS2syO1qnF3dPHz9qINDwhpi49MSGJhS2dMIANTJgTFc8kXFJGXllNXL2MUx8GExRV2ryg3HjUwsrW3KOtw9vX0J/frDeOwByQldRUQFRQgOYgAZgADKCAEygkCED6yL4CAAOPzIMH+hAQAlc1F4wUIZHw+FciJghCRKNi1AEKhgAE9kbDVB8AHSEBTI8SUwjmTAiQgQVyEI5KH6ufiC9G8TDAcg4QV05EUZlDWLxCBjIyTNJcOYLJZCFaFGDZEVHcVRACOmHmG1K212+0Oxy0p3q50aVxabUcznu3SyOVF5qtNq0UECwTeNjdRmGavocdIlAo9CAA===)

**Comment by CyrusNajmabadi** [comment]
> It's possible that there could be a custom operator defined for ==, which could be slower than a simple pointer comparison. is null reads better and is guaranteed to be just a pointer comparison.

Imo, if the user has an overloaded operator == then we should be respecting that.  I think using "== null" is appropriate for that feature.

**Comment by jinujoseph** [comment]
also reported [here]([url](https://developercommunity.visualstudio.com/content/problem/335288/the-add-null-check-refactoring-should-use-is-compa.html))

**Comment by onyxmaster** [comment]
Could this be implemented and configured using an option in .editorconfig? Autogenerating code increases productivity (and I'm talking not only about this specific code fix, but also about auto-generated constructors), yet if one wants to enforce the `is null`/`is object` pattern for `null` checks in the codebase, it just won't work.
P.S. https://twitter.com/jaredpar/status/1115019017297596416 @jaredpar
