### ISSUE TITLE
Go To X - default selection is not intuitive

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24236]
I'm used to Resharper which's GoToX feature works very intuitive. 99% of the time it selects the element I'm looking for.

In VisualStudio it's very strange. See the following examples:

Example1:
![image](https://user-images.githubusercontent.com/12449387/34921802-a7f85078-f93b-11e7-8e69-af5ba9251843.png)

Why would you preselect the file without the right extension? I'd expect (1) to be the first file.

Example2:
![image](https://user-images.githubusercontent.com/12449387/34921818-d100475a-f93b-11e7-81b5-507a11f2541b.png)

Why is the filter 'greedy'. I'd expect (1) to be the first file.

Okay, maybe I can get to my MainViewModel without using the Mouse/Arrow-Keys with some tricks...

Example3:
![image](https://user-images.githubusercontent.com/12449387/34921829-e426bd6e-f93b-11e7-8b31-293cdccd8195.png)

Hmm... okay....

Example4:
![image](https://user-images.githubusercontent.com/12449387/34921839-09d6be88-f93c-11e7-8f00-6bd21ab825ee.png)

ARE YOU SERIOUS??

I'd be very thankful if you could improve the search, since the idea is great but practically it's useless.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/181030/go-to-x-default-selection-is-not-intuitive.html
VSTS ticketId: 550334_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
File selection is not controlled by roslyn.  This goes to the main editor to handle.  Tagging @olegtk

**Comment by olegtk** [comment]
Yes, please send the bug to the editor, @jinujoseph. Btw, these cases are already fixed in 15.6.

**Comment by jinujoseph** [comment]
Thanks Guys , I have moved to issue over to Editor.
