### ISSUE TITLE
editorconfig not working for VB.NET in 15.5.2

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24232]
I updated my Visual Studio to version 15.5.2 since then the editorconfig settings are not applied to vb files anymore.

I created a sample project here: https://github.com/papauorg/editorconfig_vb_issue
It includes an interface that doesn't start with an I and a member variable that starts with `m_` instead of just an `_`. Both rules are included in the editorconfig file but are not applied anymore. When I open the project in a older version of Visual Studio 15.4.0 on my notebook it is working fine. The warnings are displayed as expected.

The warnings and suggestions for C# files seem to work fine, too.

Let me know if I need to provide more information.

Best regards,
Philipp

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/179195/editorconfig-not-working-for-vbnet-in-1552.html
VSTS ticketId: 549243_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by fefrei** [comment]
I don't think this is specific for VB – here's an example for C# that fails to show an error for me: https://github.com/fefrei/vs-editorconfig-mwe

I'm running Visual Studio 15.5.4.

The `.editorconfig` is basically stolen from the example in https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions.

**Comment by CyrusNajmabadi** [comment]
Closing as not repro.
