### ISSUE TITLE
CSharpSyntaxGenerator.GetAllowedModifiers incorrectly ignores unsafe modifier

### ISSUE THREAD

**Issue by KrisVandermotten** [dotnet/roslyn#24246]
**Steps to Reproduce**:

Given

     CodeFixContext context
     ClassDeclarationSyntax declaration

and assuming that
- the document is a C# document, 
- the class declaration has an `unsafe` modifier

then

    var generator = SyntaxGenerator.GetGenerator(context.Document);
    var newDeclaration = generator.WithModifiers(declaration, generator.GetModifiers(declaration));

will remove the `unsafe` modifier.

**Expected Behavior**:

newDeclaration has the same modifiers as the old declaration

**Actual Behavior**:

The `unsafe` modifier is removed.

Root cause is a series of bugs in [`Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.GetAllowedModifiers`](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp.Workspaces/CodeGeneration/CSharpSyntaxGenerator.cs,b5e93738253d0be2), which seems to be ignorant of the existence of the `unsafe` modifier.

This causes issues in CodeFixProviders, such as the one reported [here](https://github.com/u2uconsult/codeanalyzers/issues/16).

**Comment by lorcanmooney** [comment]
It also needs to be updated to support `ref` and `readonly` on structs.

**Comment by KrisVandermotten** [comment]
@sharwell Why did you mark this as "help wanted"? Do you need additional information?

**Comment by jinujoseph** [comment]
@KrisVandermotten Tagging the issue with "help wanted" just says this issue is understood and can be picked by community contributors if interested and we will gladly accept the PR with fix :-)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/32422
