### ISSUE TITLE
PathMap MSBuild property inconsistent with similar properties

### ISSUE THREAD

**Issue by dasMulli** [dotnet/roslyn#24247]
MSBuild properties containing lists are usually separated using semicolons, however `$(PathMap)` needs commas (`,`) as separators, causing confusion when authoring projects since it behaves differently.

E.g. specifying `<PathMap>$(PathMap);$(MSBuildProjectDirecgory)=/project</PathMap>` fails silently (!) because the initial `;` is considered part of the path (or not?), but this looks exactly like how one would expect to safely add to a property containing a list.

This adds to the fact that paths containing `;` aren't really usable in MSBuild anyway without proper escaping.

Suggestion:

Use `;` to separate path mappings for the MSBuild argument, acknowledging that there will be a difference between the MSBuild and the command line argument format. MSBuild users could then escape `;` to `%3B` like they'd have to do for any other place in MSBuild to use it.

**Comment by jaredpar** [comment]
Closing as the behavior here acting as designed.
