### ISSUE TITLE
Edit the .editorconfig causes VS to hang

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#24245]
**Version Used**: Visual Studio Community 2017 v15.5.3

**Steps to Reproduce**:

Can't really reproduce this reliably but edit `.editorconfig` causes VS to hang after few minutes of usage, just a wild guess but maybe it has something to do with the intellisense.

**Comment by sharwell** [comment]
The best thing to do here is capture a performance trace when the IDE hangs and submit it as a feedback ticket. If this were posted via the Report a Problem tool, my typical response would be the following:

> Thank you for providing feedback, and we're sorry to hear it's not behaving as you expect. Based on your description so far, it sounds like you are experiencing a problem which is historically hard to diagnose and resolve using the normal "steps to reproduce". We created a set of instructions for providing additional information which will help us track down the true source of the problems.
>
> Based on the information provided so far, the most likely scenario to follow is for "Performance issues". Please look at the following document to provide the feedback most relevant for the problems you would like to see fixed: https://github.com/dotnet/roslyn/wiki/Reporting-Visual-Studio-crashes-and-performance-issues#performance-issues

**Comment by eyalsk** [comment]
@sharwell Okay, sorry, I thought that the experience for .editorconfig is built-in into VS2017 but apparently as you already stated it's an extension for VS and the hang probably caused by the extension itself, I'll report it there even though I already see that someone reported something about it hanging VS.

Again, thank you.

**Comment by sharwell** [comment]
@eyalsk No problem. 😄 

@kuhlenh Do we already have an issue tracking a feature request for a better **.editorconfig** editing experience?

**Comment by yoyoys** [comment]
I have same issue, i think it's because intellisense form some plugin

**Comment by eyalsk** [comment]
@yoyoys May want to open a new issue about it. :)
