### ISSUE TITLE
Offer keybinding profile for other IDEs/editors in Visual Studio for C#

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#24264]
* Many developers move back and forth between VSCode and Visual Studio and have to adjust to the different shortcuts for the same functionality
* Developers coming from IntelliJ/Sublime Text/Eclipse/other editors and IDEs are used to a specific set of shortcuts for features.

My proposal is to add new "profiles" to our already existing list (and maybe even have a "power user" one where we update the C# 2005 one):

![image](https://user-images.githubusercontent.com/1402694/35011329-8b58e81c-faba-11e7-9621-d53434c5f968.png)

**Comment by CyrusNajmabadi** [comment]
can you do the reverse as well?  Make keybindings for other IDEs that then mimic VS2017?  I'm constantly switching between VSCode and VS and my muscle memory is all VS.  THat then trips me up in VSCode.  I can change all the VSCode keybindings, but i would prefer it if you did the work for me :)

**Comment by jmarolf** [comment]
> can you do the reverse as well?

That may be hard as there are a lot of IDEs out there :)

**Comment by CyrusNajmabadi** [comment]
Cover the main ones :)   it would at least be nice if the core MS ones didn't feel so different :)

**Comment by jmarolf** [comment]
seems reasonable but probably belongs over at https://github.com/microsoft/vscode

**Comment by CyrusNajmabadi** [comment]
Hrmm.. seems like it's more the purview of C#.

**Comment by jmarolf** [comment]
Ah, I missed that you were specifically talking about C# keybindings not, say, that box selection is bound to different key in VS and VSCode.  Yeah, OmniSharp and VS should be in sync where possible

**Comment by jinujoseph** [comment]
this has been done in 15.8.preview4 by editor team

**Comment by jinujoseph** [comment]
![image](https://user-images.githubusercontent.com/12449387/42591403-6fa229d2-84fb-11e8-910a-052686d15d71.png)
