### ISSUE TITLE
Invalid "use var instead of explicit type" fix with explicit interface implementations

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn#24262]
**Version Used**: 15.5.3, 15.5.4

**Steps to Reproduce**:

```cs
    public interface ITest
    {
        string Value { get; }
    }

    public class TestInstance : ITest
    {
        string ITest.Value => "Hi";
    }

    public class Test
    {
        public TestInstance[] Instances { get; }

        public void TestIt()
        {
            // here we get suggestion to change ITest to var
            // which is wrong, because:
            // 1. TestInstance != ITest
            // 2. ITest implemented explicitly
            foreach (ITest test in Instances)
            {
                Console.WriteLine(test.Value);
            }
        }
    }
```

**Expected Behavior**:
no fix proposed

**Actual Behavior**:
proposed fix breaks code

**Comment by JieCarolHu** [comment]
@MaceWindu I tested on the latest 15.6 and it seems already fixed. Could you please upgrade to 15.6 and try it again? Thanks!

**Comment by MaceWindu** [comment]
Installed latest preview and still see this behavior:
![image](https://user-images.githubusercontent.com/1099238/35616768-897c9fbc-0676-11e8-962a-b5a06ee99c32.png)

**Comment by JieCarolHu** [comment]
Thanks for the repro, I am looking into it.
