### ISSUE TITLE
VB: IDE hangs when Intellisense auto-complete is invoked on semantically invalid code.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#24261]
**Version Used**: 

Visual Studio Community 2017 v15.5.1

**Steps to Reproduce**:

Type in the following code into a VB console project:

```vb
Public Module Module1
  Public Class Base(Of T)
    Public Sub New(ArgDoSomething As Func(Of T))
    End Sub
  End Class

  Public Class Derived(Of T)
    Inherits Base(Of T)

    Private mValue As T

    Public Sub New()
      MyBase.New(Function() Me.mV) '<--- this line here has an error.
    End Sub
  End Class

  Public Sub Main()
  End Sub
End Module
```

The line `MyBase.New(Function() Me.mV)` is incomplete, and we want it to reference the `mValue` field so it ultimately reads as follows `MyBase.New(Function() Me.mValue)`. 

If you manually type the remaining letters `alue` , you'll notice Visual Studio CPU usage goes up in Task Manager. 

![vs_hangs_on_generic_1](https://user-images.githubusercontent.com/20465797/34995475-a9466ba6-fae7-11e7-8223-8c1e2b298913.png)

Alternatively, If you position the caret as shown above and invoke auto-complete to tell the editor to insert the remaining letters, Visual Studio hangs. Attempts to click anywhere inside the editor will cause that `Visual Studio is busy` notification to pop up in the Windows tray area.

**Expected Behavior**:

Intellisense should go ahead and complete the code, producing the following:

```vb
    Public Sub New()
      MyBase.New(Function() Me.mValue)
    End Sub
```

...which is semantically invalid as can be seen by the error below:

![vs_hangs_on_generic_2](https://user-images.githubusercontent.com/20465797/34995885-e9173174-fae8-11e7-9c65-3a846de81f8b.png)

You'll notice the error squiggly is on the `Me` keyword. I also tried autocompletion starting with just the letters `mV` as opposed to `Me.mV` and it doesn't hang. It's only when you try to autocomplete `Me.mV` that it hangs, so the presence of `Me.` is somehow involved.

**Comment by ericmutta** [comment]
@sharwell many thanks for the super fast follow-up!

To help you further hunt down the problem, I tried removing all the type parameters and delegates, to get this plain version which has the same semantic error (i.e accessing the object under construction):

```vb
Public Module Module1
  Public Class Base
    Public Sub New(ArgValue As String)
    End Sub
  End Class

  Public Class Derived
    Inherits Base

    Private mValue As String

    Public Sub New()
      MyBase.New(Me.mV) '<--- auto-complete WORKS here just fine.
    End Sub
  End Class

  Public Sub Main()
  End Sub
End Module
```

...the above WORKS as expected, when you do the auto-complete, it DOES NOT HANG.

Next I tried bringing back the delegates but without the type parameters:

```vb
Public Module Module1
  Public Class Base
    Public Sub New(ArgValue As Func(Of String))
    End Sub
  End Class

  Public Class Derived
    Inherits Base

    Private mValue As String

    Public Sub New()
      MyBase.New(Function() Me.mV) '<--- auto-complete HANGS here!
    End Sub
  End Class

  Public Sub Main()
  End Sub
End Module
```

...the above DOES HANG which indicates the problem is connected to using `Me.` in a lambda expression (i.e `Function() Me.mV`) that is a parameter to a base class constructor call.

Hope that helps a little and thanks again for following up! 👍

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  Presumably some issue logn since fixed.
