### ISSUE TITLE
Codefix for Must declare namespace on aspx.cs pages causes error by not updating the Inherits attribute in the aspx page.

### ISSUE THREAD

**Issue by Geneticus** [dotnet/roslyn#24289]
**Version Used**: Microsoft.CodeDom.Providers.DotNetCompilerPlatform v1.0.8

**Steps to Reproduce**:

1. create ASP>Net Web Application (.Net Framework) with masterpage
2. add new file to solution (aspx page C#) create control on page that is set in page_load event.
3. run build solution
4. VS created public partial class
5. roslyn warns to add to namespace
6. apply quick fix
7. reference to cs. file is broken in aspx file because aspx Inherits attribute wasn't updated to include Namespace.PreviousPartialClass

**Expected Behavior**:
Quick fix should prepend namespace added to aspx file.
**Actual Behavior**:
Fixing Warning automatically, causes build error.

**Comment by CyrusNajmabadi** [comment]
This needs to be handled for razor, if they want to support this scenario.
