### ISSUE TITLE
invalid "Use pattern matching" fix for OR condition

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn#24286]
Not sure if it is a separate issue or duplicate of #21097, as it produce the same error but with different code pattern.

**Version Used**: 15.5.3, 15.5.4

**Steps to Reproduce**:

```cs
    public class Test
    {
        public void TestIt(object o1, object o2)
        {
            var test = o1 as Test;
            if (test != null || o2 != null)
            {
                var o3 = test ?? o2;
            }
        }
    }
```
**Expected Behavior**:
no fix proposal

**Actual Behavior**:
```cs
    public class Test
    {
        public void TestIt(object o1, object o2)
        {
            if (o1 is Test test || o2 != null)
            {
                // CS0165: Use of unassigned local variable 'test'
                var o3 = test ?? o2;
            }
        }
    }
```

**Comment by alrz** [comment]
Nope, it's not a duplicate. I guess handling this needs speculation. @CyrusNajmabadi, can you confirm?

**Comment by CyrusNajmabadi** [comment]
Speculation, or possibly just simple syntactic analysis.  Good catch!
