### ISSUE TITLE
Pattern Matching: Consider using VS's algorithm for merging two or more matches

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#24294]
As discussed in #24193 , VS has an algorithm for merging two or matches that we may want to convert to if we don't end up moving over to VS's pattern matching.

Link to source for full algorithm: https://devdiv.visualstudio.com/_search?type=code&lp=apps-projects-Collection&text=patternmatchextensions.cs&result=DefaultCollection%2FDevDiv%2FVS-Platform%2FGBmaster%2F%2Fsrc%2FEditor%2FText%2FImpl%2FPatternMatching%2FPatternMatchExtensions.cs&preview=1&_a=contents

**Comment by CyrusNajmabadi** [comment]
Haven't seen a need to change anything here.  So closing this out as speculative.
