### ISSUE TITLE
ProjectReference to .vbproj should be loaded

### ISSUE THREAD

**Issue by OliverNET** [dotnet/roslyn#24308]
**Version Used**: Microsoft.CodeAnalysis 2.6.1 and Visual Studio 15.5.4

**Steps to Reproduce**:

See attached file for sample code.
[example.zip](https://github.com/dotnet/roslyn/files/1643172/example.zip)

1. Create a new VB.NET console application "ConsoleApp" and add a new VB.NET Class Library project "ClassLibrary"
2. Create a new VB.NET console application "CodeAnalysis" and install nuget package Microsoft.CodeAnalysis
3. Add following code to CodeAnalysis Module1 to compile the ConsoleApp.sln:
```vb
Imports Microsoft.CodeAnalysis
Imports Microsoft.CodeAnalysis.MSBuild

Module Module1

  Sub Main()

    Dim solution As Solution

    Using workspace = MSBuildWorkspace.Create()
      workspace.SkipUnrecognizedProjects = False
      workspace.LoadMetadataForReferencedProjects = True

      solution = workspace.OpenSolutionAsync("C:\source\bug\CodeAnalysis.sln").Result()

      For Each projectId In solution.GetProjectDependencyGraph().GetTopologicallySortedProjects()
        Dim project As Project
        Dim compilation As Compilation
        Dim compileErrors As List(Of Diagnostic)

        project = solution.GetProject(projectId)

        compilation = project.GetCompilationAsync().Result

        compileErrors = (From qItem In compilation.GetDiagnostics() Where qItem.Severity = DiagnosticSeverity.Error).ToList()
        If compileErrors.Count > 0 Then
          Throw New Exception("Compile error in project")
        End If
      Next
    End Using


  End Sub

End Module
```

4. Run the code - it works as expected
5. Now add a reference in ConsoleApp to ClassLibrary. This will generate the following in ConsoleApp.vbproj
```xml
  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary\ClassLibrary.vbproj">
      <Project>{f303af39-f355-4ad6-874d-bce3c832bde1}</Project>
      <Name>ClassLibrary</Name>
    </ProjectReference>
  </ItemGroup>
```
Project can still be built in Visual Studio.

6. Run project CodeAnalysis again. Now there are lot of compileErrors. Property MetaReferences in failing "project" is not loaded completly.

Thanks for any hint how to build the project.

**Comment by VektorPixel** [comment]
I was able to reproduce it, but only in VB.NET.
I hope this issue will get some attention.

**Comment by jcouv** [comment]
Investigating

**Comment by jcouv** [comment]
I'm able to repro as well. For the record, here are the errors we get out of the compilation:
![image](https://user-images.githubusercontent.com/12466233/35696428-49d9e1dc-073c-11e8-9903-e6737a715944.png)

Note that those errors relate to problems with finding types. I don't fully understand the root cause, but @shengyfu ran into this and provided a solution:
Add the following to the `App.config` file in the `CodeAnalysis` project.

Tagging @jaredpar in case he has background on this.

```xml
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Framework" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Engine" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Conversion.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Tasks.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Utilities.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
      </dependentAssembly>
```

Some notes on repro: all the projects in my repro are created as .NET Framework (4.6.1). I tried to reference the CodeAnalysis package versions 2.0 and 2.6.1 (latest), both of which repro'ed the problem.

**Comment by jaredpar** [comment]
CC @DustinCampbell

**Comment by OliverNET** [comment]
Thank you for investigating this issue.
The workaround posted by jcouv works for me.
