### ISSUE TITLE
Back compat issue: ref conditional expression allowed without explicit 7.2

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#24306]
**Version Used**: Multiple, see below

**Steps to Reproduce**:

Create a new library project:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
</Project>
```

Edit `Class1.cs` (or create a new file):

```csharp
class BugDemo
{
    static ref int Valid70(bool condition, ref int x, ref int y)
    {
        if (condition)
        {
            return ref x;
        }
        else
        {
            return ref y;
        }
    }

    static ref int Invalid70(bool condition, ref int x, ref int y)
    {
        return ref condition ? ref x : ref y;
    }
}
```

Build on the 2.0.0 SDK and 2.1.4 SDK.

(I happened to use 2.0.0 in Bash under WSL and 2.1.4 on Windows 10; I don't expect that to make any difference.)

**Expected Behavior**:

Shouldn't build on either, without `LangVersion` being explicitly set.

**Actual Behavior**:

Build with a 2.0 SDK (so C # 7.0): `Invalid70` fails to compile (several issues on the return statement).

Build with a 2.1.4 SDK (so C# 7.2): Builds fine

**Reasoning**

Perhaps the fix to the conditional operator is regarded as a bugfix - but it means that a project which is intended to only require C# 7.0 will build on some machines but not others.

cc @BillWagner, who I discovered this with.

**Comment by jcouv** [comment]
Tagging @VSadov @jaredpar

**Comment by VSadov** [comment]
Ooops. It was prototyped in a separate branch before 7.2 was a thing.

**Comment by VSadov** [comment]
Typically new features introduce some new syntax and that makes it obvious that a version check must be added. 
Most version-specific features are checked at parse time.

For this one, we did not add any new syntax nodes - existing model was sufficient to fit this in. Just what was formerly an error-recovery scenario has become valid. Most work was in binding and we forgot to add a version check.

**Comment by VSadov** [comment]
Thanks for reporting!!

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/24355
