### ISSUE TITLE
SignatureHelp should indicate "ref" for ref indexers

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/roslyn#24311]
**Version Used**: 

Visual Studio 2017 27317.1.d15.6

**Steps to Reproduce**:

1. Create a C# project
2. Add reference to `System.Memory` from NuGet
3. Create an instance of `Span<int>` and access it's indexer, Signature Help should display the definition of the indexer.

**Expected Behavior**:

The Signature Help should display the indexer definition as follow, or similar (with `ref`):

```C#
ref int Span<int>[int index]
```

**Actual Behavior**:

Signature Help does not indicate `ref`, developer may not know this is a ref return.
 
![span](https://user-images.githubusercontent.com/12908526/35114268-052bcb80-fc39-11e7-9dc8-eca9a6d5a2a1.png)

**Comment by jcouv** [comment]
Thanks for reporting this.
Fix for 15.6 preview 4 is pending review.

**Comment by jcouv** [comment]
Fix is merged for 15.6 preview 4.

**Comment by mazhou-msft** [comment]
Verified in 27404.0.d15.6 and it works as expected.
