### ISSUE TITLE
Refactor NavigateTo tests to remove duplicate code

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#24318]
As mentioned in feedback for #24193, there are a lot of duplicate tests between InteractiveNavigateToTests.cs and NavigateToTests.cs.   We should refactor them for maintainability.

The differences between these two files is:
1)	Interactive: => TestWorkspace.CreateCSharp(content, parseOptions: Options.Script);
        Regular: => TestWorkspace.CreateCSharp(content, exportProvider: exportProvider);
2)	Some tests in interactive: VerifyNavigateToResultItem() use Glyph.ClassPrivate when Regular uses Glyph.ClassInternal
3)	Interactive: has an extra test for  FindVerbatimIdentifier, Regular: doesn’t have above mentioned test, but has several more that interactive doesn’t
4)	TermSplittingTest7 is different on both
5)	All later bug fixes were done on NavigateToTests only

**Comment by CyrusNajmabadi** [comment]
Closing out.  Don't see any value in making changes here as the tests are working fine.
