### ISSUE TITLE
C# IntelliSense doesn't work after `in` keyword

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#24326]
_From @MkazemAkhgary on January 15, 2018 11:1_

when I type `in` for in parameter, then writing parameter name in method signatureintellisense doesn't suggest names anymore.

current version: 15.5.2

_Copied from original issue: dotnet/project-system#3145_

**Comment by Pilchie** [comment]
Hi @MkazemAkhgary - do you have the Language Version option set in project properties?

cc @jcouv.

**Comment by Pilchie** [comment]
_From @MkazemAkhgary on January 16, 2018 20:53_

@Pilchie It was set to latest minor version AFAIK.

**Comment by Pilchie** [comment]
@jcouv - let me know if this turns out to be a project system issue after all.

**Comment by jcouv** [comment]
Sure.
@Pilchie I'll take a quick look in case I can confirm the problem and sneak a fix in for 15.6. Otherwise, I'll push back to 15.7. Thanks

**Comment by jcouv** [comment]
One issue is that types aren't completed in method declarations after `in`:
![image](https://user-images.githubusercontent.com/12466233/35128172-0ad5e670-fc6a-11e7-97ea-cf007100bfb5.png)

But they are correctly completed after `ref`:
![image](https://user-images.githubusercontent.com/12466233/35128188-203bffa4-fc6a-11e7-951b-dcaaf6ffefaf.png)

Another issue is that variable names aren't completed in an invocation after `in`:
![image](https://user-images.githubusercontent.com/12466233/35128252-6ac0a9d0-fc6a-11e7-8273-25e6652f98dd.png)

But they are properly completed after `ref`:
![image](https://user-images.githubusercontent.com/12466233/35128238-5f3eed24-fc6a-11e7-94f0-7d46da16f779.png)

**Comment by jcouv** [comment]
Fix is in review.
Thanks @MkazemAkhgary for reporting this

**Comment by jcouv** [comment]
Fixed in 15.6 preview 4.
