### ISSUE TITLE
Support non-trailing named arguments with dynamic.

### ISSUE THREAD

**Issue by JonHanna** [dotnet/roslyn#24334]
Currently with the likes of:

```C#
dynamic s = "abcabc";
int i = s.IndexOf(value: 'a', 2);
```
We get CS8324.

Since support for non-trailing named arguments has [recently been merged into corefx](https://github.com/dotnet/corefx/pull/25819), ideally roslyn could make use of it, rather than raising that error.

In itself this is simple, but identifying whether it will be supported or not is another matter.

**Comment by alrz** [comment]
Relates to https://github.com/dotnet/roslyn/issues/23575

**Comment by jcouv** [comment]
Tagging @VSadov to advise.
Can or should the compiler try to detect runtime capability to decide whether or not to let such code compile?
We've introduced such an API ([RuntimeFeature](https://github.com/dotnet/corefx/issues/17116)) not long ago. Corefx could add `RuntimeFeature.NonTrailingNamedArgumentInDynamicInvocation`, then the compiler could gate its behavior on that.

**Comment by VSadov** [comment]
Yes. We should add some handshake and condutionally enable the scenario.

It would be something similar to the “RuntimeFeature” but in dynamic binder. Perhaps simpler - we probably only need the static aspect of it.

**Comment by VSadov** [comment]
Actually we may add support for ‘in’ argument kind in the binder and use that as a trigger that both ‘in’ arguments and nontrailing names are supported

**Comment by VSadov** [comment]
Although it feels a bit like hack.

More formal “feature X supported” marker like in RuntimeFeature is probably better.

**Comment by JonHanna** [comment]
We should probably allow for `in` anyway, since it's feasible. It's not going to be completely backwards compatible due to the way it affects overloading (unless we insist that `in` must be included at the call site rather than being optional, but that seems a difference from static code that will lead to confusion).

It does seem a bit of a hack to use the relevant enum field to indicate support for a feature that could exist without it (indeed, which does exist without it right now), but it's a hack that needs to further API work, and seems it should be dependable.

**Comment by VSadov** [comment]
`in` at the call site is meaningful for the purpose of overload resolution, so it must be passed to the binder. For that `CSharpArgumentInfoFlags` needs a new entry. And compiler can use the presence of the entry as a key that the feature is supported.

As for the nontrailing names - there is no special API to check. And I feel there will be more features like this. The solution could be something like [RuntimeFeature](https://github.com/dotnet/corefx/issues/17116) , but in `Microsoft.CSharp` namespace.

```C#
namespace Microsoft.CSharp.CompilerServices
{
    public static class RuntimeFeature
    {
        // Presence of the field indicates runtime support
        public const string NontrailingNamedArguments = nameof(NontrailingNamedArguments);

        // Runtime check
        public static bool IsSupported(string feature);
    }
}

// Usage

if (RuntimeFeature.IsSupported("SomeNewerFeature")
{
      // Use feature when emitting code at runtime (CodeDOM, RefEmit etc)
}
```

**Comment by jcouv** [comment]
Sounds good. I will bring this up with LDM first (probably can get it on the agenda for next week).

@JonHanna Would you be able to help drive such API on corefx side (once LDM gives thumbs up)?

Some thoughts ahead of the corefx/API discussion:
I'm not completely sure we need a `RuntimeFeature` API in the `Microsoft.CSharp` namespace, as opposed to simply extending the existing API. 
If package dependencies and versioning work, I think we can ensure that when `Microsoft.CompilerServices.RuntimeFeature.IsSupported("NonTrailingNamedArguments")` returns `true`, then the dynamic binder necessarily supports the feature. If you use an older binder, it depends on an older core library where this API returns `false`.

**Comment by JonHanna** [comment]
> Would you be able to help drive such API on corefx side

Sure.

> If package dependencies and versioning work, I think we can ensure…

Is it possible to use a more recent version of just Microsoft.CSharp? (I pretty much just use what nuget gives me across the board myself, so don't know from experience) and hence for someone to have support for that version while CompilerServices wouldn't think they should?

**Comment by JonHanna** [comment]
If this can be done from the existing API. I wonder if we should start to namespace the string identifiers a bit, so something like `"Microsoft.CSharp.NonTrailingNamedArguments"`. The list of features is something that is only going to get larger, and eventually get to the point where most people will not know what most features are and be lost as to where to look to find out, and which they can quickly dismiss as not of interest to them.

**Comment by jcouv** [comment]
There is a way to ensure that the new `Microsoft.CSharp` binaries depend on new core library: just reference the new member `Microsoft.CompilerServices.RuntimeFeature.NonTrailingNamedArguments` in code.

I don't have a strong opinion on the identifier for this feature, but keep in mind that the pattern for `RuntimeFeature` is to add corresponding properties, but property names can't have punctuation.

**Comment by gafter** [comment]
Moving to `csharplang`.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #2069](https://github.com/dotnet/csharplang/issues/2069) via [**ZenHub**](https://www.zenhub.com/)
