### ISSUE TITLE
Convert delegate to local function suggested fix breaks code in expressions

### ISSUE THREAD

**Issue by UnoSD** [dotnet/roslyn#24344]
**Version Used**: 
2.6.0.62329 (5429b35d)
Visual Studio 15.5.2

**Steps to Reproduce**:
```csharp
void Method(Action action)
{
            
}

Expression<Action> Example()
{
    Action action = () => Method(null);

    return () => Method(action);
}
```

**Expected Behavior**:
Not to suggest a fix

**Actual Behavior**:
A fix is suggested to replace the delegate with a local function; if fix is implemented it breaks the code as local functions cannot be referenced by expression trees.

**Comment by MaStr11** [comment]
This seems to be fixed by #23136. I made a PR with the test case with the snippet above here #24391. Note: I'm not sure why the version used by @UnoSD offered the fix because #23136 was merged a few days before (but into a different branch).
