### ISSUE TITLE
Implement a "Stylistic Check" prerequisite build bot

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#24350]
As the "style" of the language use within pull request seems to "trigger" some member of the team.
Add a build bot that validates the style as prerequisite, thus preventing the build from succeeding. 
Providing both a "trigger warning" to those it may effect, and give feedback to those that violate it.

**Comment by jcouv** [comment]
Code style (as specified by editor config) will be enforced during build. I think @jasonmalinowski has plans for that.

**Comment by AdamSpeight2008** [comment]
@jcouv the style convention wiki entry for visual basic should be updated to explicitly state what is and isn't permitted, not a oblique reference to "similar exists for VB".

**Comment by sharwell** [comment]
:bulb: Our primary stylistic check is currently provided by Git, and exposed via the GitHub UI. When looking at the Diff page, a failing stylistic check can be observed as a pull request which changes the style of code as part a review for a behavior change. Stylistic changes are only expected to appear in a pull request which makes no behavior changes, and preferably contains changes only related to one very specific style choice.

**Comment by jasonmalinowski** [comment]
Yeah, once we have .editorconfig we'll probably enable enforcement, but we don't have that today. And I don't see us implementing a new tool prior to it existing -- that's just time we could spend implementing .editorconfig.

That said, having some better docs on VB formatting would be good. What rules should we document that we're not today?
