### ISSUE TITLE
Whitespace and EndOfLine trivia should default to non-elastic

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#2435]
The public syntax factories for Whitespace and EndOfLine trivia have an optional 'elastic' parameter that defaults to true.  However, it is rare that you would want to construct elastic whitespace, so it should default to false. 

It is true that factories for tokens default to having elastic marker trivia, but that's only in the case when you don't specify the trivia at all. If you are in the business of adding whitespace trivia manually, you usually are trying to be very specific about the whitespace and you don't want the formatter to immediately change it.

**Comment by gafter** [comment]
@Pilchie Can you please verify this?
