### ISSUE TITLE
Add -skipApplyOptimizations to build.cmd

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#24360]
Currently when using build.cmd it doesn't seem possible to pass /p:SkipApplyOptimizations=true to turn off IBCMerge.

It would be nice for local builds that emulate official builds.

**Comment by jaredpar** [comment]
Rather than adding yet another option I think I'll just change the build to skip that step if the NuGet package hasn't been restored.

**Comment by KirillOsenkov** [comment]
:+1: even better. This way I don't even have to worry about passing it.

**Comment by KirillOsenkov** [comment]
Another question: why isn't it restored? I ran restore.cmd.

**Comment by tmat** [comment]
IBC merge is internal tool. It can only be restored in MicroBuild.

**Comment by tmat** [comment]
RepoToolset handles this, btw: https://github.com/dotnet/roslyn-tools/blob/master/sdks/RepoToolset/tools/OptimizationData.targets

**Comment by KirillOsenkov** [comment]
I believe this is fixed now.
