### ISSUE TITLE
Code formatting not working using open directory

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24365]
I cloned a git repo containing a .NET Core project.  I used Open Directory in VS 2017 15.5.3 and 15.6.0 Preview 2.0, and both had the same issue.
When editing code, automatic formatting, such as indentation and brace positioning did not function correctly, either indenting too deeply or not indenting at all.  At least some of the code used framework names (Int64) and some used built-in names (long).
When I added an empty VS solution and then added the project to it, the auto-formatting started working.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/181937/code-formatting-not-working-using-open-directory.html
VSTS ticketId: 551475_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I believe this is all by design.  Loose files get hte misc-experience (which is basically the lowest bar possible of "don't crash").  Rich features come through actually using solutions/projects.
