### ISSUE TITLE
EnvDTE.CodeElement.Name doesn't include interface name for C# methods explicitly implementing interface member

### ISSUE THREAD

**Issue by carlos-j-quintero** [dotnet/roslyn#2437]
When you use the EnvDTE.ProjectItem.FileCodeModel to get the name of a code function, EnvDTE.CodeElement.Name doesn't include the interface name for C# methods that explicitly implement an interface member, such as I1.f1()

Steps to reproduce the problem:

1) Create a package with a menu command that uses this code:

      private void MenuItemCallback(object sender, EventArgs e)
      {
         try
         {
            EnvDTE.DTE dte = base.GetService(typeof(EnvDTE.DTE)) as EnvDTE.DTE;
            ShowCodeElements(dte.ActiveDocument.ProjectItem.FileCodeModel.CodeElements);
         }
         catch (Exception ex)
         {
            System.Windows.Forms.MessageBox.Show(ex.ToString());
         }
      }

      private void ShowCodeElements(EnvDTE.CodeElements codeElements)
      {
         EnvDTE.CodeClass codeClass;

         foreach (EnvDTE.CodeElement codeElement in codeElements)
         {
            switch (codeElement.Kind)
            {
               case EnvDTE.vsCMElement.vsCMElementClass:

                  codeClass = (EnvDTE.CodeClass)codeElement;
                  ShowCodeElements(codeClass.Members);
                  break;

               case EnvDTE.vsCMElement.vsCMElementFunction:

                  System.Windows.Forms.MessageBox.Show(codeElement.Name); 
                  break;
            }
         }
      }

2) Run the package and in the second VS instance, create a C# Class Library with this code:

public interface I1
{
   void f1();
}

public class C1 : I1
{
   void I1.f1() // This implements interface
   {
   }

   private void f1() // This is unrelated to implemented interface
   {
   }
}

3) Click the Tools > My Command Name menu.

The actual results are:

f1()
f1()

The expected results are (like in VS 2013):

I1.f1()
f1()

Notes:

1) About CodeElement.FullName, in VS 2013 the interface name was not returned (C1.f1) but I think it would be more correct to include it too (C1.I1.f1).

2) Review also properties explicitly implementing interfaces (I1.Property1)

3) Review also events explicitly implementing interfaces (I1.Event1)

4) CodeElement.StartPoint, CodeElement.EndPoint, CodeElement.GetStartPoint(part), CodeElement.GetEndPoint(part) cause exception in all those cases. Write tests getting start/end points for these cases of explicitly implemented interfaces and check that fail. Then fix the name problem and then check that they pass. I say this because those functions getting start/end points seem to fail when the name of the code element is not actually "correct", see https://github.com/dotnet/roslyn/issues/146

**Comment by carlos-j-quintero** [comment]
@basoundr,  see my just added comments

**Comment by basoundr** [comment]
@carlos-j-quintero I ran some test to get startpoint for explicitly implemented method and I did not see any crash like you mentioned. Could you please explain the scenario in detail?

**Comment by carlos-j-quintero** [comment]
@basoundr It seems that the bug with start/end points is not related to explicitly interface methods but general. I have opened a separate issue: https://github.com/dotnet/roslyn/issues/2461

**Comment by codecadwallader** [comment]
This issue has been closed, and I don't think any action is needed - but for the archives, here's what I think was originally being reported:

The behavior of CodeElement.Name for explicitly implemented members appears to have changed from VS2013 to VS2015:

In VS2013:
- Events reported just their name (IExplicit.**EventName**)
- Methods reported their name with the interface (**IExplicit.MethodName**)
- Properties reported their name with the interface (**IExplicit.PropertyName**)

In VS2015:
- Events report just their name (IExplicit.**EventName**)
- Methods report just their name (IExplicit.**MethodName**)
- Properties report just their name (IExplicit.**PropertyName**)

I've worked around the change, just sharing some details if somebody else ends up here.
