### ISSUE TITLE
Completion list after deletion breaks snippets flow

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#24377]
**Version Used**: 27310

**Steps to Reproduce**:

1. Enable _Show completion list after a character is deleted_
2. Invoke a code snippet that would offer intellisense e.g. `prop` or `lock`
3. Press <key>Backspace</key> to delete the default value of the placeholder.
4. Press <key>Tab</key> to move to another placeholder.

**Actual Behavior**: The first list in the entry, e.g. `#if` is entered into the placeholder.

**Expected Behavior**: The empty placeholder to remain empty as is the case with performing the 3rd step with <key>Delete</key> instead. Nothing is preselected in the autocompletion list (correct) so the Tab key shouldn't commit anything.

**Comment by miloush** [comment]
This might actually be the same or relevant to #20145.

**Comment by sharwell** [comment]
@miloush It will likely be solved in a manner similar to #20145, but I see them as separate issues.

**Comment by sharwell** [comment]
We should investigate the impact of the following on this:

1. What is the behavior in earlier versions of Visual Studio?
2. What impact does Suggestion Mode have on the scenario?
3. Does the improved design proposal also work to fix the user experience described in #20145?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
