### ISSUE TITLE
Auto completing quotation mark is not working when using CW code snippet

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24376]
If you use the CW code snippet for Console.WriteLine() then you can't auto complete the quoatation mark for the literal string.

If you instead manually type in Console, dot, WriteLine() and type the first quotation mark, then it gets auto completed.

![Snippet](https://developercommunity.visualstudio.com/storage/attachments/21088-vs2017-cw1.gif)

![No Snippet](https://developercommunity.visualstudio.com/storage/attachments/21089-vs2017-cw2.gif)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/185760/auto-completing-quotation-mark-is-not-working-when.html
VSTS ticketId: 555040_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by samirgunic** [comment]
As I recall it, this bug did not exist in Visual Studio 2013 nor in Visual Studio 2015.

**Comment by Pilchie** [comment]
I expect the bug *did* exist in at least VS2015.

Autocompleting braces/quote/etc only works if:

1. The insertion of the first quote is the last non-whitespace thing on the line, OR
2. All other things after it on the line are closing quotes/parens/braces that were inserted by the feature and are currently being tracked (for tab to pass through) for example.

There is nothing that ties the snippet insertion with the feature, so the mere fact that the snippet has more characters after the cursor is what triggers this.

**Comment by samirgunic** [comment]
I can confirm that it does exist in Visual Studio 2015, Update 3.

**Comment by sneakyazshiite** [comment]
I am also experiencing this problem when using CW tab-tab. I am currently using Visual Studio Community 2019, Version 16.7.3

**Comment by samirgunic** [comment]
For what it's worth, it works in VS Code (version 1.49.0).

**Comment by saratpc** [comment]
Visual Studio 2019 Enterprise Edition. cw snippet does not autocomplete quotes. Please fix.

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me on latest builds.
