### ISSUE TITLE
Quick Action: Convert for to foreach and vice versa

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#24381]
just like resharper, allow converting for to foreach and vice versa. me not a genius. me realize index is needed where I wrote `foreach`, me realize index is no more needed where I wrote `for`. thanks.:)

**Comment by sharwell** [comment]
I'm going to close this as a duplicate of #8953 as we continue working on the feature design, though it may get split back out during the implementation portion.
