### ISSUE TITLE
Prefer '-' over '/' for options in "csc - help"

### ISSUE THREAD

**Issue by BillWagner** [dotnet/roslyn#24394]
This is related to dotnet/docs#4072  "Inconsistent switch usage for C# compiler options.

We found that the options documentation used a mixture of `/` and `-` and we wanted to standardize (knowing that both are supported.)  The community response was overwhelmingly in favor of `-`.  

We are well on the way to updating the docs.  

I would make the same changes to https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/CSharpResources.resx so that "csc -help" provided the same experience.

/cc @jcouv

**Comment by sharwell** [comment]
I agree with both unification and the choice of `-`.

/cc @jaredpar

**Comment by jaredpar** [comment]
Yes we should prefer `-` over `/`. It's more cross plat friendly.

**Comment by BillWagner** [comment]
I'll submit a PR to address this.

**Comment by jcouv** [comment]
Fixed in 15.8
