### ISSUE TITLE
[regression] Roslyn deterministic pdb hashing breaks hello world on .net core

### ISSUE THREAD

**Issue by kangaroo** [dotnet/roslyn#2439]
Please see the following issue:

https://github.com/dotnet/coreclr/issues/898

It seems Roslyn presumes the presence of the TransformBlock and TransformFinalBlock methods which are not surfaced in .NET core.

**Comment by gafter** [comment]
Ouch. My fault. This is in support of a feature that isn't even enabled by default.

**Comment by MattGertz** [comment]
Assigning for verification.
