### ISSUE TITLE
EE uses moduleSymbol.GetReferencedAssemblies() in GetIndexOfReferencedAssembly

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#2441]
The compiler used to do this, but it's inappropriate since it preemptively unifies assemblies, meaning GetIndexOfReferencedAssembly may not find the assembly in the list. The EE should check if this is also a change that should be made there.

See https://github.com/dotnet/roslyn/commit/4d9f92693b7502edd42cf87d17fe8fe502e2ed37 for more information.

**Comment by amcasey** [comment]
I managed to construct a test that would hit this case but, apparently, import decoding uses the regular metadata decoder (i.e. is covered by @agocke's fix).  I'll try to figure out where the ```EETypeNameDecoder``` is used so I can construct another test.

**Comment by amcasey** [comment]
@agocke can you please verify?
