### ISSUE TITLE
Cannot get internal members of a Type from within INamedTypeSymbol

### ISSUE THREAD

**Issue by npolyak** [dotnet/roslyn#24412]
I am getting a referenced type from a Roslyn Compilation by using Compilation.GetTypeByMetadataName(...) method. Then I use INamedTypeSymbol.GetMembers() method to get all its member symbols. I am getting all public and protected symbols but neither private nor internal. I do not care much about private member symbols, but internals are a must for me. Is there any way to get them from a Roslyn compilation?

**Comment by jcouv** [comment]
You may be looking for the `ignoreAccessbility` flag on `Compilation.GetSemanticModel`.

**Comment by npolyak** [comment]
I am not even using semantic model - I do not need it for my purpose. Just pulling the type straight from the compilation and checking its members. Can you give me a code example?

**Comment by npolyak** [comment]
It seems like I resolved the problem but not without a hack.

one has to set a hidden property MetadataImportOptions of the compilation to MetadataImportOptions.All (which is 2). Both the CSharpCompilationOptions.MetadataImportOptions member and MetadataImportOptions enumeration are internal to Microsort.CodeAnalysis assembly. I had to use reflection to be able to set it. In particular I did something like:
`MethodInfo withMetadataImportOptionsMethodInfo = 
      typeof(CSharpCompilationOptions).GetMethod("WithMetadataImportOptions, BindingFlags.NonPublic | BindingFlags.Instance);

    MyCompilationOptions = 
        (CSharpCompilationOptions) MethodInfo.Invoke(MyCompilationOptions, (byte) 2);`
(byte) 2 is the MetadataImportOptions.All option.

**Comment by npolyak** [comment]
I opened https://github.com/dotnet/roslyn/issues/24425 requesting to open up the API for setting MetadataImportOptions. 
I'll keep this issue open for now in case some one can come up with a better way of achieving this.

**Comment by jcouv** [comment]
`MetadataImportOptions` will be made a public API in 15.7. See https://github.com/dotnet/roslyn/pull/24468
I'll go ahead and close the issue. Thanks

**Comment by npolyak** [comment]
cool thanks
