### ISSUE TITLE
C# Auto-completion behavior with arrays

### ISSUE THREAD

**Issue by sailro** [dotnet/roslyn#24432]
Issue filled on behalf of Adomas Griskelis from Unity3D QA. cc @jbevain 

Please have a look at the attached super simple and self-contained repro project:
[AutoCompleteRepro.zip](https://github.com/dotnet/roslyn/files/1660980/AutoCompleteRepro.zip)

**Version Used**: 
VS 2017 Entreprise 15.5.4

**Steps to Reproduce**:
1.  Use the attached repro (pure C# project, referencing two included Unity3D assemblies)
2.  Open Program.cs, go to line 24
3.  Type ```Transform[] t = new Trans```
4.  Press "["

**Expected Behavior**:
Should auto-complete to ```Transform[] t = new Transform[]```

**Actual Behavior**:
No auto-complete.

If you retry with the following (actual class and not an array), it will work as expected:
Type ```Transform t = new Trans```
Press "("
And you will get the expected ```Transform t = new Transform()```

**Comment by jcouv** [comment]
Thanks for reporting this. Does seem to be an issue.
In the array case, the completion is soft-selected, whereas in the constructor case it is hard-selected.

![image](https://user-images.githubusercontent.com/12466233/35377732-335225be-0165-11e8-82c7-a612bd57adca.png)

![image](https://user-images.githubusercontent.com/12466233/35377774-55c065d4-0165-11e8-9c3b-ba357a86d04e.png)

**Comment by jcouv** [comment]
Fix is ready for review.
