### ISSUE TITLE
Ctrl+T : Go To File Member

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#24435]
I've had several customers let me know that they had no idea we let them filter by "current document" in Ctrl+T (Go To All). Their expected behavior was that this would be scoped to "current document" by default for members.

![image](https://user-images.githubusercontent.com/1402694/35362206-45ade942-0119-11e8-87b6-7889dda4cc94.png)

Perhaps we can have a smart filter where if they are searching for "files" we default to the solution but if they are searching for a "type" or "member" we scope to the current file? Not sure what others means we can use to help discoverability...

**Comment by kuhlenh** [comment]
One thing that may help is having a keyboard shortcut that is easier. R# users have a command explicitly for "file members" which we can consider doing something similar...

**Comment by tmat** [comment]
> Perhaps we can have a smart filter where if they are searching for "files" we default to the solution but if they are searching for a "type" or "member" we scope to the current file?

👎 I have never wanted to find type or member only in the current file. For type it doesn't make much sense if the project follows one type definition per file convention.

**Comment by CyrusNajmabadi** [comment]
>  but if they are searching for a "type" or "member" we scope to the current file? 

Please, never do this. 99%+ of all my symbol searches are for symbols not in the current file.  If i wanted the current file, i'd likely just do "ctrl-f" to find-in-file.

**Comment by jcouv** [comment]
One idea would be to populate the completion with possible filter shortcuts ("f" for file, etc as shown when pressing "?"). Also that "?" list should include a shortcut for "current document".

**Comment by jmarolf** [comment]
> One thing that may help is having a keyboard shortcut that is easier. R# users have a command explicitly for "file members" 

I think that makes the most sense.  We could look at sorting results such that members in the current file always appear first but that is likely to break some folks muscle memory.

**Comment by Neme12** [comment]
Right now if I want to find a method in the current file I usually do ctr+f to avoid the hassle of doing go to all and then either manually turn on a switch or with a second convoluted keybord shortcut that I will never remember - and even if I did, ctrl+f will always be shorter. This is not ideal. There should be a separate shortcut for navigating within a file.

**Comment by jinujoseph** [comment]
This has been done by editor team in 15.8.Preview4
