### ISSUE TITLE
Refactor Inline Rename command handler to not use chaining

### ISSUE THREAD

**Issue by olegtk** [dotnet/roslyn#24430]
Related to https://github.com/dotnet/roslyn/pull/23769/files#r162170708.

Inline rename command handler still handles some commands in chained way. Seems like it all can be converted to simple non-chained command handler with refactoring of HandlePossibleTypingCommand() method.

Too risky for 15.6 though.

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
