### ISSUE TITLE
Move C# EventHookup feature off of Classic Quick Info

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#24434]
**Version Used**: 
Visual Studio 2017 15.6 Preview

**Steps to Reproduce**:

1. Create new C# Console Application.
2. Create new event `static event EventHandler Foo;` in Main class.
3. In main method, type `Foo +=` and C# language service responds with a helpful tooltip indicating that TAB can be used to auto-insert an event handler.

**Resolution**:
- This feature is currently implemented using the classic IQuickInfo APIs, supplemented by a series of hacks such as IHACK_EventHookupDismissalOnBufferChangePreventerService and a custom quick info source that are used to keep the tip alive on TYPECHAR, and exclude content from other providers, respectively.
- In Visual Studio 2017 15.6, the Editor team has deprecated the IQuickInfo* family of APIs, necessitating a removal of all of its usages.
- Related Issue #24094 tracks replacing IQuickInfo* APIs with IAsyncQuickInfo* APIs.
- To support the presentation of event hookup in C# in the post-IQuickInfo* world, I have introduced an IToolTipService MEF import that can be used to obtain an IToolTipPresenter instance that gives the desired behavior when passed an instance of ToolTipParameters with trackMouse: false, and ignoreBufferChange: true.
- This abstraction service lives in the xplat portion of the editor UI, Microsoft.VisualStudio.Text.UI.dll, and should be usable within Roslyn, even below the WPF layer.
- @DavidKarlas can confirm whether or not this support is present on Mac, but the intention of the design was to expose a single abstraction that works seamlessly on both VS for Mac and VS for Windows.

**Comment by DavidKarlas** [comment]
On Visual Studio for Mac this is atm still on feature branch but will probably be merged for 15.7.
In theory whoever will be working on migration from `IQuickInfo*` to `IAsyncQuickInfo*` won't have to worry about Mac, just make it work on VS and on Mac it should just work.

**Comment by gundermanc** [comment]
Ported [Modern ToolTip API spec](https://github.com/Microsoft/vs-editor-api/wiki/Modern-ToolTip-API) to GitHub.
