### ISSUE TITLE
Allow Decompilation of arbitrary DLLs

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#24455]
With our integration of ILSpy, we should look at allowing opening of an arbitrary dll so the types and methods can be browsed. I ran into an issue with roslyn where I did a local nuget pack and depended on the binaries from another project, but missed deleting the nuget cache so my downstream project had the wrong version at compile time. I used the ILSpy UI to figure out what was going wrong, but we should have integrate it with the Object Browser in VS so it can all be done in program.

/cc @sharwell.

**Comment by CyrusNajmabadi** [comment]
Unlikely to invest int his area without significant user feedback.
