### ISSUE TITLE
show users why find all reference can't read metadata information

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#24459]
find all reference need to read symbol information from metadata references, but as any input, metadata (dll) can contain invalid data, and that can cause exception which cause us to lose any information from that dll for find all references.

for now, we silently ignore it and move on. but it might be better to let users know such failure happened so that user know why find all reference doesn't provide any types from that dll.

...

this issue for now only talk about 1 specific scenario (find all reference), but it would be nice if we have general shared mechanism to report this kind of thing to users so that all features when they encounter this kind of situation, easily report the issue and move on.

**Comment by CyrusNajmabadi** [comment]
Clsoing out as we haven't heard from customers a need for this.
