### ISSUE TITLE
VB TryGetValue with Tuples has issues

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#24467]
**Version Used**: 
VS Enterprise 15.5.4, Roslyn 2.6
**Steps to Reproduce**:
1. With the code below NewNodeList is always empty after TryGetValue
```
    <TestMethod()> Public Sub TryGetValueOfTupleTestMethod()
        Dim Node As Integer = 1
        Dim OldNodeList As New SyntaxList(Of StatementSyntax)
        OldNodeList = OldNodeList.Add(SyntaxFactory.ParseExecutableStatement("Dim X As Integer"))
        Dim RemoveStatement As Boolean
        Dim NewNodeList As New SyntaxList(Of StatementSyntax)

        StatementDictionary.Add(Node, (OldNodeList, True))
        If Not StatementDictionary.TryGetValue(Node, (OldNodeList, RemoveStatement)) Then
            ' Do Something and NewNodeList is correctly empty
            Assert.False(True, "StatementDictionary found something when it shouldn't")
        End If
        'Get here when the node is found in the dictionary, next 3 lines pass
        Assert.NotEmpty(StatementDictionary(Node).Item1)
        Assert.Equal(StatementDictionary(Node).Item1.ToString, "Dim X As Integer")
        Assert.True(StatementDictionary(Node).RemoveStatement)
        ' Next 2 lines both fail
        Assert.True(RemoveStatement, "Boolean Tuple Dictionary Failed")
        Assert.NotEmpty(NewNodeList)
    End Sub
```
But if you execute the statement below NewNodeList has correct value, is something broken with TryGetValue and Tuples
```
    NewNodesList = StatementDictionary(node).Item1
```
**Expected Behavior**:
NewNodeList and RemoveStatement have the value stored in Dictionary when Key Matches or if dictionaries don't work with Tuples I expect an error somewhere.
**Actual Behavior**:
NewNodeList is always empty and ReturnStatement has wrong value

**Comment by CyrusNajmabadi** [comment]
This would be the same as you writing:

```.TryGetValue(key, new AnyStruct())```

It's not a good idea.  :)

**Comment by paul1956** [comment]
Thanks, should there at least be a warning? Does it ever make sense or is this just another case where VB doesn't quite work with Out variables?

**Comment by CyrusNajmabadi** [comment]
You could certainly write an analyzer to find these sorts of things.  But this has been how VB has worked since forever, and adding a warning here would be breaking.

**Comment by paul1956** [comment]
I will chalk it up to I learned something new.
