### ISSUE TITLE
C# tuple name inference refactoring can be incorrect

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#24480]
**Version Used**: VS 15.5.5; csc reports v2.6.0.62329

**Steps to Reproduce**:

Add this code into a project with C# 7.1 or higher enabled:

```csharp
int foo = 10;
var tuple = (foo: foo, foo);
Console.WriteLine(tuple.foo);
```

**Expected Behavior**:

No suggestions for simplification.

**Actual Behavior**:

- The `foo:` is in light grey, with a tool tip of "Member name can be simplified"
- Applying the suggested fix ("Use inferred member name") results in:
        `var tuple = (foo, foo);`
  ... at which point the last line fails, as no member names are inferred due to duplication.

**Comment by jcouv** [comment]
Fix is merged for 15.7
Thanks for reporting this
