### ISSUE TITLE
API request: Provide 'AnalyzeDataFlow(SyntaxNode firstNode, SyntaxNode lastNode)' to give more control over the selected region

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#24488]
Currently we only can define a region given first and and last statements, but there is no way to specify the exact node for the start and end of a region.

For example, if we want to suggest to use out var in the following code:
```cs
int x = 0, y = x;
if (... M(out x) ...) { .. }
```
We need to check if x is not being used from the point of declaration up to the out usage and check if it does not flow in (i.e. is definitely-assigned) from the point of out usage onward.

The former check is simple enough to workaround with a manual walk through all nodes up to the out usage. But for the latter check, we need to accept a single-variable local declaration to form a region starting from the very next statement.

This also helps in https://github.com/dotnet/roslyn/issues/23375

**Comment by gafter** [comment]
[Does this API help](https://github.com/dotnet/roslyn/blob/14aed138a01c448143b9acf0fe77a662e3dfe2f4/src/Compilers/CSharp/Portable/CSharpExtensions.cs#L948)?


``` c#
    public static DataFlowAnalysis CSharpExtensions.AnalyzeDataFlow(
        this SemanticModel semanticModel, ExpressionSyntax expression) ...
```

**Comment by alrz** [comment]
@gafter 

That just accept a single expression while I needed to specify a non-statement node for the starting and ending points of the region. something like `AnalyseDataFlow(SyntaxNode firstNode, SyntaxNode lastNode)`.

**Comment by gafter** [comment]
@alrz I don’t understand what the intended semantics would be for an arbitrary node.

**Comment by alrz** [comment]
They would be used as the bounds of the region, for example,
```cs
var result = semanticModel.AnalyzeDataFlow(firstNode, lastNode);
```
Returns the analysis result for the following region:
```cs
int x = 1, y = /*<bind>*/firstNode;
// ...
return lastNode;/*<bind>*/
```

**Comment by gafter** [comment]
@alrz I understand what they would be used for. I don't understand the intended *meaning* of such an arbitrary region.

**Comment by alrz** [comment]
@gafter Just that the analysis should consider precise starting/ending points of the region for results.

Here's an example,
```cs
bool x = false, y = M() || M(out x), z = Use(x);
```
We want to know if refactoring this to `out var` could led to def-assignment errors (it does)
```cs
bool x = false,  /*<region-start>*/y = M() || M(out x), z = Use(x); 
/* <region-end> */
```
This should result in `x` being in `FlowsIn` collection.

If we do this for the whole statement, `x` no longer flows in.

**Comment by gafter** [comment]
@alrz Even if I understand what it means in that particular example, I do not know what it means in general. The existing APIs ensure there is a direct path from the beginning to the end of the region. This API does not.

**Comment by alrz** [comment]
@gafter How would you imagine we can make this work? maybe we could define regions on a statement range (what we do today) but include/limit usage positions to be returned for FlowsIn etc.

**Comment by alrz** [comment]
I figured all we need is to set `RegionSpan`, the region start/stop is not affected (for flow analysis) but we exclude read/writes that are outside that span from the result.

**Comment by gafter** [comment]
Closing, as I do not see a way to clearly specify the proposed method, and I therefore do not think it is something we would do.
