### ISSUE TITLE
Roslyn doesn't support portable PDBs on Linux

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/roslyn#2449]
We can't create PDBs when building CoreFx on Roslyn/Linux.

**Comment by tmat** [comment]
Portable PDB format is now supported as specified in https://github.com/dotnet/roslyn/blob/master/docs/specs/PortablePdb-Metadata.md

**Comment by tmat** [comment]
Reopening -- we should emit Portable PDB when running on Linux by default (instead of failing to emit Windows-only PDB format).

**Comment by gafter** [comment]
I was hoping that our determinism story is that we would produce the same output for the same inputs (and command line) on different platforms. Having a different default output format on different platforms would undermine that. I'm not saying it isn't worth doing, but it will mean that "build platform" is one of the inputs on which the deterministic output depends.

**Comment by tmat** [comment]
The POR is to add /debug:portable to csc.rsp on Linux/Mac.

Adding /debug:portable command line switch is tracked by https://github.com/dotnet/roslyn/issues/5285
