### ISSUE TITLE
IDE completion for `in` overrides adds unnecessary attributes

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#24490]
Using this code:
```csharp
    class Parent
    {
        public virtual void M(in int x)
        {

        }
    }
```
Now from another assembly, inside the child type, type `override` and wait for the suggestions, and expand `M`, you'll get the following:
```csharp
    class Child : Parent
    {
        public override void M([System.Runtime.CompilerServices.IsReadOnlyAttribute] in int x)
        {

        }
    }
```
That attribute shouldn't be present.

**Comment by jcouv** [comment]
I missed the part about referencing the code from another assembly. I'll try again.

**Comment by jinujoseph** [comment]
@jcouv  thanks for fixing this. closing the issue
