### ISSUE TITLE
Formatter should remove spaces inside interpolated string braces

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#24498]
**Version Used**: 15.6 Preview 2

**Steps to Reproduce**:

Format the following code in Visual Studio:

```csharp
var _ = $"{ 3 }";
```

**Expected Behavior**:

```csharp
var _ = $"{3}";
```

**Actual Behavior**:

```csharp
var _ = $"{ 3 }";
```

:link: Current behavior appears to be implemented in 67cf7c1dcf0db735e1445fab0adbb46297042d64
:link: Related to code review in #24407 
:link: Related to DotNetAnalyzers/StyleCopAnalyzers#2295

**Comment by sharwell** [comment]
@DustinCampbell @kuhlenh Let me know if this needs to go to a design meeting before marking it up for grabs.

**Comment by CyrusNajmabadi** [comment]
I think this should be controlled by an option.  I, for one, prefer spacing here as i feel it helps visually clarify what's going on.
