### ISSUE TITLE
CSC doesn't care if out parameter not assigned

### ISSUE THREAD

**Issue by carlreinke** [dotnet/roslyn#24493]
**Version Used**: Microsoft (R) Visual C# Compiler version 2.6.0.62329 (5429b35d)

**Steps to Reproduce**:

```
c:\temp>type Program.cs
class C
{
    static bool M( out System.ReadOnlyMemory<byte> x )
    {
        return false;  // No error here!?
    }
}

c:\temp>csc.exe /reference:"C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\mscorlib.dll" /reference:"C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\netstandard.dll" /reference:C:\Users\User\.nuget\packages\system.memory\4.5.0-preview1-26011-01\ref\netstandard2.0\System.Memory.dll /reference:"C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Runtime.dll" /out:Test.dll /target:library Program.cs
Microsoft (R) Visual C# Compiler version 2.6.0.62329 (5429b35d)
Copyright (C) Microsoft Corporation. All rights reserved.


c:\temp>
```

**Expected Behavior**: Show error message and fail to compile.

**Actual Behavior**: Compilation succeeds.

**Comment by gafter** [comment]
Please check to see what fields, if any, are contained in `System.Collections.Generic.KeyValuePair` inside of `C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Runtime.dll`. If it contains no fields in that reference assembly, then the compiler is correct. In that case the `out` parameter is definitely assigned because all (zero) of its fields are definitely assigned.

**Comment by gafter** [comment]
To clarify, if that is the case then it is a bug in the reference assembly.

**Comment by carlreinke** [comment]
Indeed, there are no fields in that `KeyValuePair<TKey, TValue>` in the reference assembly.  I replaced the original comment with a different example.  `ReadOnlyMemory<T>` does have fields.

**Comment by carlreinke** [comment]
Err, I guess the *reference* assembly for `System.ReadOnlyMemory<T>` doesn't have fields either... the assembly that gets used has fields.  Why are there no fields in the reference assemblies?

**Comment by gafter** [comment]
That is a bug. We’ll move this bug to an appropriate repository.

**Comment by tannergooding** [comment]
@gafter, I believe the issue has already been dealt with on the CoreFX side: https://github.com/dotnet/corefx/pull/26286 and https://github.com/dotnet/buildtools/pull/1859.

However, it was only merged 15 days ago, so nothing has shipped with the fix yet.

**Comment by gafter** [comment]
@tannergooding I don't see anything specifically changing `KeyValuePair`'s reference assembly. Isn't its reference assembly produced based on hand-written source?

**Comment by gafter** [comment]
Issue moved to [dotnet/corefx #26624](https://github.com/dotnet/corefx/issues/26624) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tannergooding** [comment]
It looks like it has already been fixed, at least somewhere: https://github.com/dotnet/corefx/blob/a3986843153e27e92c89907f58046bb37da0f9eb/src/System.Memory/ref/System.Memory.cs#L108

**Comment by gafter** [comment]
And the fix for `KeyValuePair`?

**Comment by tannergooding** [comment]
I wasn't able to find the contract assembly for KVP and commented as such on the new issue (forgot to comment as such here as well).

**Comment by tannergooding** [comment]
Nevermind, it's in `System.Runtime` and is also correct: https://github.com/dotnet/corefx/blob/master/src/System.Runtime/ref/System.Runtime.cs#L3907

(GitHub search wouldn't find it, `git grep` did).
