### ISSUE TITLE
Errors are not displayed in the error list when opening a C# project (that opens a file containing errors).

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#245]
Ported from TFS WorkItem: <b>1108097</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P>Create a C# console app.</P>
<P>Introduce some errors in program.cs</P>
<P>Close VS</P>
<P>Restart VS and open the solution.</P>
<P>&nbsp;</P>
<P>The errors in program.cs show up as squiggles in the editor but do not appear in the error list.</P>
<P>&nbsp;</P>
<P>Make any change in program.cs (even adding a space to a comment).</P>
<P>&nbsp;</P>
<P>Errors now appear in the error list.</P>

**Comment by heejaechang** [comment]
it doesn't repro anymore.
