### ISSUE TITLE
Completion on declaration should prioritize "new"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#24501]
![image](https://user-images.githubusercontent.com/12466233/35487875-c8c857f8-0435-11e8-96cc-b0e8ac05bc93.png)

Removing "nameof" hopefully will bring "new" to the top, but I'm not certain.

**Comment by CyrusNajmabadi** [comment]
it will bring "namespace" to the top right?  that's the next highest prefix-matching item.

**Comment by CyrusNajmabadi** [comment]
nameof is legal here.  you might be doing something like:

```c#
nameof(Blob).Select(whatever).ToArray();
```

For all we know. :)

**Comment by jcouv** [comment]
Ah, good point. I'll close then.

**Comment by sharwell** [comment]
@jcouv You may need to use `ne` instead of just `n` in the tests that let to this discovery. Separately, it may make sense to prioritize `new` in this case (as a special case without removing `nameof`).

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
