### ISSUE TITLE
Go to definition in VB source goes to metadata view even though corresponding C# project is part of the same solution

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#2450]
In Roslyn solution, go to the following line in src\Compilers\VisualBasic\Portable\Symbols\Source\SourceAssemblySymbol.vb
```
If Not AssemblyIdentity.TryParseDisplayName(displayName, identity, parts) Then
```

Go to definition on **AssemblyIdentity** - two partial definitions in source files are found as expected.
Go to definition on **TryParseDisplayName** - goes to metadata view of AssemblyIdentity type, expected to go to definition is source.

**Comment by Pilchie** [comment]
Dupe of #599.

**Comment by MattGertz** [comment]
Verifying as dupe.
