### ISSUE TITLE
Editor jump bar doesn't go to correct location for multiple conflicting functions

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#24515]
Type this code into the editor:
```C#
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
        }

        static void Main(string[] args)
        {

        }

        static void Main(string[] args)
        {

        }
    }
}
```

The function info bar at the top will have 3 different entries for Main, but clicking on any of them will always bring you to the first such defined function, not the one that corresponds to that entry in the list. This is also true for partial classes in separate files: even clicking the greyed-out entry will always bring you back to the same function as the other entries.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  The three items take you to the three locations respectively.  Closing out.
