### ISSUE TITLE
Why doesn't Roslyn have an IdentifierExpressionSyntax AST node?

### ISSUE THREAD

**Issue by ltcmelo** [dotnet/roslyn#24514]
This isn't an issue, but a question. However, I couldn't find a discussion mailing list about Roslyn itself (only for C#/VB as a whole) or an IRC channel - please, let me know if I missed it.

Why isn't there an "identifier expression" node in Roslyn's AST? Compiler infrastructures I've worked with (and wrote) typically have an `IdentifierExpressionAST` node. This allows me to immediately distinguish between ordinary names in the program and those that are proper expressions.

As an example, consider the declaration `namespace Foo { }` and the statement `i = 10;`. Traversal of Roslyn's AST provides both names `Foo` and `i` in the form of an `IdentifierNameSyntax` (which inherits from `ExpressionSyntax`), but those two kinds of names are fundamentally different: (i) the former is purely for nominative organization; (ii) the latter denotes an actual value, it's a term.

Currently, I distinguished an identifier expressions using a check such as the one below:

        public override SyntaxNode VisitIdentifierName(IdentifierNameSyntax node)
        {
            if (node.Ancestors().OfType<ExpressionSyntax>().Any()
                || node.Parent.IsKind(SyntaxKind.ReturnStatement))
            {
                 //...
            }
            return node;
        }

Is this the correct way of achieving such differentiation? If so, what are the primary advantages of such design that makes every sort of name an expression?

**Comment by AdamSpeight2008** [comment]
There are two kinds of node that represents the source code
[Syntax Nodes](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Syntax/Syntax.xml) Representing the structure of the text of the source code  
[Bound Nodes](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml) Representing the semantic meaning of the code.

**Comment by ltcmelo** [comment]
It seems that's internal API, correct? I'm speaking from the perspective of a Roslyn *user* who's writing source analysis. How would you traverse the AST with CSharpSyntaxWalker/Visitor and, out-of-box, match identifier expressions?

**Comment by AdamSpeight2008** [comment]
It used to generate the syntax nodes and bound nodes, eg the AST.

**Comment by ltcmelo** [comment]
I suspect to have identified at least one potential reason for this design: There's syntax ambiguity in C# and, in order to separately pipeline Roslyn's syntactical and semantic analysis, there's no other way but to make *certain* names expressions (even when they aren't such in a theoretical sense). For a member access expression such as `a.b`, for instance, semantic information is required to identify `a` as either a **type** (for static member access) or a variable (for non-static access, a *real* expression) - having `TypeSyntax` inheriting from `ExpressionSyntax` enables postponing that decision while preserving a unambiguous well-formed AST.

I'd appreciate if anyone involved with Roslyn's design could comment on this.

@AdamSpeight2008 : Thanks for your comments, but I'm afraid they don't touch the aspect I'm questioning here.

**Comment by jmarolf** [comment]
Its kind of hidden on the ReadMe.md file in the root but we have a gitter chat for general questions
[![Join the chat at https://gitter.im/dotnet/roslyn](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/dotnet/roslyn?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

tagging @gafter for a more detailed explanation but I believe the answer is that the nodes in the public API were designed to adhere closely to the language specification itself.

**Comment by CyrusNajmabadi** [comment]
> Why isn't there an "identifier expression" node in Roslyn's AST? 

It does:  It's called. ```Identifier```.  Why is it not called ```IdentifierExpression```?  Because that would have been a wordy mouthful :)

**Comment by CyrusNajmabadi** [comment]
> As an example, consider the declaration namespace Foo { } and the statement i = 10;. Traversal of Roslyn's AST provides both names Foo and i in the form of an IdentifierNameSyntax (which inherits from ExpressionSyntax), but those two kinds of names are fundamentally different: (i) the former is purely for nominative organization;

Roslyn does do what you want for other 'declarations'.  i.e a ClassDeclarationSyntax points at an Identifier **token** not an IdentifierNameSyntax.

However, the reason it's an IdentifierNameSyntax for namespaces is that it's legal to write a namespace like:

```c#
namespace A.B.C.D { }
```

This means namespaces need a way to do dotted names, and we already have a construct for Dotted names: ```QualifiedNameSyntax```.  Because namespace declarations now need to support a NameSyntax node for their name, the question is ```what to put for the NameSyntax when the name is just an identifier```.  We could have had IdentifierNameSyntax for this purpose only, and then had IdentifierExpressionSyntax for expression scenarios.  But we deemed it too much of a PITA to have to deal with two syntactic forms that were structurally identical but only valid in certain circumstances.

**Comment by CyrusNajmabadi** [comment]
> Is this the correct way of achieving such differentiation?

The important question is: why do you need such differentiation.  If you can explain your use case, it would be more possible to explain the code you need to write to properly handle things.

**Comment by CyrusNajmabadi** [comment]
> I'd appreciate if anyone involved with Roslyn's design could comment on this.

I was one of the designers here :)   The truth of the matter was that we were striking a balance between trying to have the system have distinguished typed for every use, and not making it super painful to use the API.

Another case for this was symbols (i.e. ISymbol).  We went back and forth on if there should be the concept of ISymbolReference and ISymbolDeclaration, with ISymbolReference pointing to a declaration, but including information only relevant at a reference point (like type arguments, etc.).  But, in the end, while it had a beauty to that taxonomy, it also made just writing code much more painful because of hte need to handle so many different cases.  

These were pragmatic changes made due to actually using the APIs and feeling like these splits ended up onerously burdening the usage, without providing enough value to make them worthwhile.

**Comment by ltcmelo** [comment]
@CyrusNajmabadi Thanks for the detailed responses and for sharing the design insights. I've recently started with Roslyn and I'm generally satisfied. There a few places, like the one I mention (or in the control-flow API), where I was "surprised".

Here, I don't expect a **token** as `ClassDeclarationSyntax`. The problem isn't that I have an `IdentifierNameSyntax` for an "identifier expression", but that I have an `IdentifierNameSyntax` for constructs that are **not** expressions (from a theoretical standpoint).

While I admit no universally accepted terminology, it's standard that an expression denotes a value; that value might be named (e.g. an `IdentifierExpressionSyntax` or `IdentifierNameSyntax`). But the a namespace's name is anything, but a value. Regardless of its name variety (e.g. `QualifiedNameSyntax`, `SimpleNameSyntax`, etc.), I don't think they should be an `ExpressionSyntax`.

You ask the reason for such differentiation. First, let me clarify that Roslyn does offer me a way to do so, my complain is that it isn't immediate (i.e. I need "extra" code).

Say you wanna write an AST visitor for some kind of expression evaluator - think of data-flow analysis. Ideally, you'll just override the *visit* methods for expressions and implement **only** the *domain* logic. But with `CSharpSyntaxWalker`, I can't do so. This inability exists because I either have to explicitly handle an "identifier expression" from its parents or write an additional check (like in my original snippet) inside `VisitIdentifierName`.

Does my argument make sense? If not, kindly point where I'm mistaken.

**Comment by CyrusNajmabadi** [comment]
> I don't think they should be an ExpressionSyntax.

That's fine.  Understand though that nothing can change here.  It would be a major breaking change, and we don't take those.  :)

> Does my argument make sense? If not, kindly point where I'm mistaken.

My problem is that it's too abstract.  If you wanted an expression evaluator, you'd already have to do major work to understand each sort of expression, as well as understand what context it is contained in.  So you need logic to already understand the surrounding tree no matter what.  Given that you're going to need that already, i don't see much burden in having to understand a few more cases.

**Comment by CyrusNajmabadi** [comment]
BTW, there's a helper for your use case if you want to use it.  SyntaxFacts.IsInNamespaceOrTypeContext will tell you if your expression is in a context where only a type/namespace name is allowed.  And thus where you might see names that should not be thought of as values.  

I think you will still need to explicitly check if you're parented by a NamespaceDeclarationNode.  In other word you should check:

```c#
public static void IsExpressionWithRuntimeValue(Expression expr)
    => !SyntaxFacts.IsInNamespaceOrTypeContext(expr) && !expr.IsParentKind(SyntaxKind.NamespaceDeclaration);
```

**Comment by CyrusNajmabadi** [comment]
> This inability exists because I either have to explicitly handle an "identifier expression" from its parents or write an additional check (like in my original snippet) inside VisitIdentifierName.

Yes.  That's the case.  But realize that that's going to be the case with virtually any taxonomy we generate.  Either we have to explicitly tease apart every syntactic construct (no matter how similar they are) if they might ever mean anything semantically.  That also means there might be more types of identifiers which might be even more annoying for other usages.  

For example, TypeScript has the concepts of NamespaceName, TypeName, and IdentifierReference within the language grammar.  However, actually parsing things out into that structure would have made things much slower (as lookahead would always have been necessary to determine which construct you were on), and would have made certain features that work with trees much more complex as they would now need to know and work equivalently when tehy had "NamespaceName.TypeName" as they would with "NamespaceName.NamespaceName" and "TypeName.IdentifierReference" etc. etc.

At the end of the day this was a pragmatic choice.  It is important to realize that roslyn concrete syntax tree was *specifically* designed for *many* different consumption cases *not just* the compiler/expression-evaluation case.  It was also designed to be pleasant to use in things like IDE features where forcing this sort of taxonomy would have made things more painful.

**Comment by ltcmelo** [comment]
> there's a helper for your use case if you want to use it.

Nice to know, I'll look into `SyntaxFacts.IsInNamespaceOrTypeContext` then.

> At the end of the day this was a pragmatic choice.

I can see that. And you've made good choices, my overall perception of Roslyn is positive - I'm enjoying playing with it. 

Thanks for the informative discussion.

**Comment by CyrusNajmabadi** [comment]
Any time :)

**Comment by Neme12** [comment]
I can understand some of the design choices but it still feels like a little bit of a hack to have an ExpressionSyntax inside a namespace name since it isn't an expression. In my opinion, IdentifierNameSyntax ideally wouldn't be an ExpressionSyntax at all. Even in the case where it's part of a member access expression: `A.B.C` B or C logically aren't expressions, only part of a bigger expression, so there wouldn't be any code duplication required.

**Comment by CyrusNajmabadi** [comment]
Syntactically, there is no way to to tell.  When you have:

```A.B.C.D.E.F``` you have no way to tell which of those (syntactically) are namespaces (not a value), types (not a value) or members (values).  So, at the syntactic level, they all end up the same.  

> But I understand that the distinction can't be made reliably anyway since we don't know if A itself is a variable (expression) or a type (not expression).

Yup.

> IdentifierNameSyntax ideally wouldn't be an ExpressionSyntax at all.

Then you'd need *something* to represent a standalone name which *was* an expression.  i.e. ```(a)```.  

> but it still feels like a little bit of a hack to have an ExpressionSyntax inside a namespace name since it isn't an expression

namespaces aren't typed as having an ExpressionSyntax.  They're typed as having a NameSyntax.  And that is reasonable as it's the Name of a namespace.  It prevents needing identical syntactic hierarchies to represent the same concept.  i.e. we already have names and dotted names, why reinvent a new NamespaceName or NamespaceDottedName construct that just duplicates that hierarchy?

**Comment by Neme12** [comment]
@CyrusNajmabadi My point was that you wouldn't need to have a separate hierarchy, it would all be composed of IdentifierNameSyntax (just as it is today) which would not inherit from ExpressionSyntax.

> namespaces aren't typed as having an ExpressionSyntax. They're typed as having a NameSyntax.

which inherits from ExpressionSyntax

But anyway this isn't going to change (and even if it did it might make the logic slightly better in my opinion but still it can never correctly separate expressions from non-expressions in all cases as you said) so there's no point in debating this, I'm sorry for expanding on it.

**Comment by CyrusNajmabadi** [comment]
> Yes I know the a would either have to be wrapped in an expression containing the name

That is what IdentifierNameSyntax is.  it's the wrapping of the non-expression 'a' token into Expression form .   :)

> My point was that you wouldn't need to have a separate hierarchy, it would all be composed of IdentifierNameSyntax (just as it is today) which would not inherit from ExpressionSyntax.  

This would then be the exact definition of "a separate hierarchy".  it would be a way to describe dotted names that was different from the *other way* of describing dotted names.  As mentioned already, Roslyn did not want to do that as having different syntactic forms for equivalent syntax was felt to be onerous for consumers.  

--

Look, i get that other formalization are possible.  We even considered them at the time.  But they were rejected because there was no end to how deep these taxonomy breaks could be.  It was felt that this was actually harder to deal with, especially on top of an API that already has >100 different syntax types *to start with*.  So, the principle was that we would not create duplicate hierarchies unnecessarily.  It makes some things slightly harder, but overall was a more pleasant API for the entire stack to consume.  :)

**Comment by gafter** [comment]
We made an explicit decision when designing the syntax trees to avoid trees that merely represent "chain productions" of nonterminals in the grammar. One plus of doing things this way is that syntax trees are much more compact. Your observation here is the main downside.
