### ISSUE TITLE
Allow inline variable declaration for in and ref parameter types

### ISSUE THREAD

**Issue by Kentalot** [dotnet/roslyn#24525]
**Version Used**: 
I'm using C# 7.2 and version 15.5.3 of VS 2017 Enterprise.

**Steps to Reproduce**:

``` C#
private static void GetValue(out string input)
{
    input = null;
}
private static void DoNothing(ref string input)
{
}

private static void DoNothingIn(in string input)
{
}

private static void Call()
{
    GetValue(out var x);
    DoNothing(ref var y = x);
    DoNothingIn(in var z = null);
}
```

**Expected Behavior**: Compiles and y is usable after calling DoNothing and z is usable after calling DoNothingIn and all of x, y, and z are basically null;

**Actual Behavior**:
Does not compile since you can't inline declare variables for ref or in keywords.  I hope that's clear.  Thanks!

**Comment by HaloFour** [comment]
Proposals to change the behavior of the language are taken at the [C# Language](https://github.com/dotnet/csharplang/) repository.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #1289](https://github.com/dotnet/csharplang/issues/1289) via [**ZenHub**](https://www.zenhub.com/)
