### ISSUE TITLE
Analyzer silently crashes when calling AnalyzeDataFlow on the semantic model

### ISSUE THREAD

**Issue by taori** [dotnet/roslyn#24537]
**Version Used**: 
VS 15.5.4

**Steps to Reproduce**:

1. call AnalyzeDataFlow on semantic model with a MethodDeclarationSyntax as parameter
2. check analyzer unit test diagnostic for exception

**Expected Behavior**:

analyzer should point out the exception (because i should pass the body property of the MethodDeclarationSyntax  instead of MethodDeclarationSyntax  itself)

**Actual Behavior**:

Analyzer silently crashes and only tells me that there was no diagnostic.

**Note**:
I am not sure whether this is actually a bug in roslyn or if the implementation of DiagnosticVerifier should be modified to point the developer into the direction of the exception instead of silently failing.

**Comment by jcouv** [comment]
@taori Could you share more details on repro? A minimal self-contained project reproducing the problem would be ideal.

Does the `AnalyzeDataFlow` call crash, or a later step? From your description, it sounds like step (1) crashes, and step (2) is not executed.
Could you share a stacktrace?
Does any `MethodDeclarationSyntax` cause the problem, even a simple one?

**Comment by taori** [comment]
The AnalyzeDataFlow raises an exception. The exception itself is useful, but it's swallowed within unit tests, so a unit test will not tell you what exception actually happened

**Comment by jcouv** [comment]
Thanks for the clarification.
What kind of unittest are you describing? Is this a unittest in Roslyn itself, or an unittest created from template project for an analyzer?
Also, could you share the exception raised by `AnalyzeDataFlow`? I'm trying to figure out if the unexpected behavior is in `AnalyzeDataFlow` or in the unittest.

**Comment by taori** [comment]
It was a unit test created from a template project for an analyzer. Since i am unable to reproduce it in an isolated project i suspect it's because i did custom try+catch logging to trace an issue which was lacking in the AD0001 issue which made it "silently fail". In an isolated project this does work just the way one would expect it to.

 #24346
