### ISSUE TITLE
Wiki Samples-and-Walkthroughs page has broken samples links

### ISSUE THREAD

**Issue by wachulski** [dotnet/roslyn#24545]
This wiki page: https://github.com/dotnet/roslyn/wiki/Samples-and-Walkthroughs has at least 2 links that are broken:

1. Samples folder (https://github.com/dotnet/roslyn/tree/master/src/Samples) = GitHub 404
2. Diagnostics folder in the sources (https://github.com/dotnet/roslyn/tree/master/src/Diagnostics) = as above

I found just this instead: https://github.com/dotnet/roslyn/tree/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Samples
but I belive there is something more around.

Could you please fix the links? This is vital for newcomers to Roslyn.

**Comment by jmarolf** [comment]
I need to update this.  In the meantime 
1. Samples were moved here: https://github.com/dotnet/roslyn-sdk/tree/master/samples 
2. Diagnostics where moved here: https://github.com/dotnet/roslyn-analyzers/tree/master/src

**Comment by wachulski** [comment]
Ok, thx.

**Comment by CyrusNajmabadi** [comment]
Closing out.  If someone wants to fix this, feel free.  The issue doesn't help that happen though.
