### ISSUE TITLE
Optimize allocations in IsDefinedInSourceTree hot paths

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#24549]
**Version Used**: 27328.0

:link: https://developercommunity.visualstudio.com/content/problem/188525/ui-delays-in-roslnsln-test-files.html

The performance trace attached to this issue reveals nearly 82MB of `SyntaxReference[]` allocations in `SourceOrdinaryMethodSymbol.IsDefinedInSourceTree`. These should be optimized similar to #23462.

**Comment by CyrusNajmabadi** [comment]
Closing out.  If this is showin gup on current traces we should assign this to a milestone and do it.  Perf traces for things 6 years ago aren't helpful as they may not have any relation to current code.
