### ISSUE TITLE
Large allocation overhead in NameGenerator.GetCollisionIndices

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#24548]
**Version Used**: 15.6 Preview 3

:link: https://developercommunity.visualstudio.com/content/problem/188525/ui-delays-in-roslnsln-test-files.html
:link: https://developercommunity.visualstudio.com/content/problem/692953/ide-frequently-slow-and-unresponsive-at-random-int.html
🔗 https://developercommunity.visualstudio.com/content/problem/817870/intellisense-lag-and-huge-number-of-false-red-squi.html

The performance trace attached to the previous ticket revealed over 500MB of allocations in `NameGenerator.GetCollisionIndices`. The primary problem with the current implementation is these allocations occur within `HasRefactoringsAsync` - meaning the simple operation of showing the light bulb inevitably leads to problems. These allocations should be avoided prior to a preview being requested.

This issue was also seen in a performance trace showing the `EventHookup` feature (which runs after typing `+=` follewed by <kbd>Space</kbd> in C#) executing slowly, with more than 2GiB allocations.

**Comment by sharwell** [comment]
@jinujoseph I may be looking into this for 15.6

**Comment by sharwell** [comment]
I just observed this during a particularly bad VB editing experience. Allocations were 1.37GB over 20 seconds (60% of total).

**Comment by CyrusNajmabadi** [comment]
@sharwell What is the callstack that is leading into this?  I'd like to know which feature is using the NameGenerator here.  Thanks!

**Comment by sharwell** [comment]
@CyrusNajmabadi Here's the backtrace:

![image](https://user-images.githubusercontent.com/1408396/36626192-e366bc1c-18f3-11e8-93fa-d7d978262db6.png)

**Comment by CyrusNajmabadi** [comment]
Talked with @sharwell on gitter.  The primary issue is that IntroduceVariable currently actually *executes* the code action it produces during the GetRefactoringsAsync phase.  The reason for this, afaict, is as follows:

1. Because of venus, some parts of the user's code will 'hidden'.  
2. IntroVariable doesn't want to introduce fields/constants into those hidden areas.
3. So it runs the fix, and then sees if edits happened in those areas.  if so, it does not offer the action.

This is pretty terrible.  

--

The second issue is that NameGenerator is just written in a very memory inefficient manner.  EnsureUniqueness is particularly bad here, with tons of copying and linq calls all over the place, even for algorithms that could be completely non-allocating.  It would be nice to improve this, though it will likely not be an issue if the primary problem is addressed.

**Comment by rolandh** [comment]
Can we get an update on what is being done to fix this issue? It is affecting my entire team on a daily basis killing productivity with no work around.

https://developercommunity.visualstudio.com/content/problem/817870/intellisense-lag-and-huge-number-of-false-red-squi.html

**Comment by CyrusNajmabadi** [comment]
@rolandh how do you know it is this particular issue?

**Comment by CyrusNajmabadi** [comment]
@rolandh can you please follow the steps here to file an accurate trace that can be investigated: https://github.com/dotnet/roslyn/wiki/Reporting-Visual-Studio-crashes-and-performance-issues

Thanks!

**Comment by sharwell** [comment]
@CyrusNajmabadi I have already verified that @rolandh is hitting this issue. It impacts completion following a `+=` to suggest the name of an event handler that will be generated.

**Comment by CyrusNajmabadi** [comment]
@sharwell great, thanks.  LMK if you'd like any help her.e  I can certainly look into optimizing this particular module.  Also, do you have a callstack for how this is being used by the specific `+=` feature?  i want to see if the feature is behaving badly (like we mentioned for another feature here https://github.com/dotnet/roslyn/issues/24548#issuecomment-368208947), or if the feature is fine and it's just this subalgorithm that needs to be significantly improved.

Thanks!

**Comment by rolandh** [comment]
Hello. I have submitted the design time logs as requested. Can someone please give an update?

It is not just +=, it is the entire project having red squiggles under literally everything. This randomly resolves itself and comes back.

**Comment by CyrusNajmabadi** [comment]
@rolandh This seems unrelated.  I submitted a PR to deal with things like the excess allocations.  However, without more info about what you're running into, it will be hard to figure out the cause and fix whatever is going on with you. 

Would it be possible for you to provide a repro project where you're seeingthis behavior?

**Comment by rolandh** [comment]
I have saved a repro on my desktop however its a huge project with lots of proprietary code. I can do a screen share session but I can't send it out.

**Comment by CyrusNajmabadi** [comment]
> I can do a screen share session but I can't send it out.

i can try to set something up with you.  It would be very helpful though if you can apply my fix for the large allocation overhead, and then also file a perf report (again, with my fix applied) using the instructions here: https://github.com/dotnet/roslyn/wiki/Reporting-Visual-Studio-crashes-and-performance-issues

Thanks!

**Comment by CyrusNajmabadi** [comment]
Note: Without a repro project, it is likely we'll need to make several fixes across many domains.  Being able to get solid info, and then iterate on these fixes with you will be the surest way to get to resolving all the problems.  

Thanks!

**Comment by rolandh** [comment]
Unfortunately can't share the code for the same reason you cannot share the full compilable source code for visual studio. 

I can however share a solution which causes a very similar problem here:
https://github.com/nopSolutions/nopCommerce/releases/tag/release-4.00

This solution regularly crawls to a halt with 10+ seconds for intellisense completions or no completion at all. Not responding white window on startup. Massively lag after developing for 4-5 hours and also huge memory usage.

Here are 6 perfview reports I've submitted over the past 12 months. You can view them all here.

The most relevant to this issue are listed in order. I've attached a perfview trace with each of them via the problem reporting tool and also uploaded a dropboxed version in some cases.

You can reproduce these issues by developing on the nopcommerce solution above for ~4 hours and leaving the solution open, come back the next day and continue to develop. 100% reproduction rate of the lag and intellisense red squiggles. I've been dealing with this issue for 18+ months and I cannot get anyone to action it. It affects my entire team.

https://developercommunity.visualstudio.com/content/problem/817870/intellisense-lag-and-huge-number-of-false-red-squi.html

https://developercommunity.visualstudio.com/content/problem/690292/codelense-breaks-after-5-8-hours-of-vs2019-usage.html

https://developercommunity.visualstudio.com/content/problem/660220/vs2019-1630-preview-10-huge-memory-leak-32gb-ram-u.html

https://developercommunity.visualstudio.com/content/problem/818021/vs2019-large-amount-of-ram-15gb-and-large-number-o.html

https://developercommunity.visualstudio.com/content/problem/733862/vs2019-huge-lag-when-debugging-netcore-project.html

https://developercommunity.visualstudio.com/content/problem/650996/stepping-through-debugger-causes-lca-to-reanalyse.html

**Comment by CyrusNajmabadi** [comment]
> edit: You say apply your fix. But I'm not really sure how to

Sam listed steps to follow here: https://github.com/dotnet/roslyn/pull/39974#issuecomment-557701747

> and then install it over the top of my existing build

It installs side-by-side.  i.e. it goes into another VS 'hive' that doesn't touch your existing one.

> This sounds very time consuming and risky.

It is somewhat time consuming.  However, it's the best way for me to actually be able to tell if my fix improves thins for you in any way.  If it does not, we'll have to do another fix.  If it does, but there are still issues, we can then move on to addressing those.

> What exactly is "roslyn". Is it a DLL? Or is it a collection of executables? 

It's a collection of dlls.  

> If the latter how do I ensure I replace the correction version? I have VS2017, VS2019, VS2019 Preview all installed.

The steps that Sam listed handle that :)

**Comment by CyrusNajmabadi** [comment]
> Here are 6 perfview reports I've submitted over the past 12 months. You can view them all here.

@sharwell can you take a look at report back on if there are otehr perf root causes you see?

**Comment by CyrusNajmabadi** [comment]
> . I've been dealing with this issue for 18+ months and I cannot get anyone to action it. It affects my entire team.

...  

I went and worked on a fix for one of the issues reported.  I'm trying very hard to figure out if there are other issues that i can provide fixes for.  However, it's not possible for me from where i sit to do this all on my own.  I understand that this is negatively affecting you and that you want "it" fixes asap.  However, the best i can do from where i sit is to work *with* you to drive solutions and fixes into the product.  This works best when we can cooperate with each other :)

**Comment by CyrusNajmabadi** [comment]
Alternatively, if you are very worried about affecting your current dev environment, you could always use a different machine (or VM) to test things out in an isolated fashion.

Thanks much, and i look forward to hearing from you and working with you toward solutions for all the issues you're running into in Roslyn.

**Comment by CyrusNajmabadi** [comment]
@rolandh see https://github.com/dotnet/roslyn/pull/39974#issuecomment-559899487 as well.  It might be much easier to work with you through gitter/discord on this.  Thanks!

**Comment by CyrusNajmabadi** [comment]
I've made another PR to try to help this scenario out: https://github.com/dotnet/roslyn/pull/40076

**Comment by rolandh** [comment]
Ok I built that commit of roslyn (very cool build environment that you can launch a separate VS like that for testing) and it fixes the issue completely.

I opened the broken solution next in normal VS and the special launch command side by side. The current preview  16.4 Preview 6 takes ~10 seconds to complete and lags the UI completely. This build completes in under a second with no lag at all.

**Comment by CyrusNajmabadi** [comment]
Woohoo!  Thanks for the confirmation!

**Comment by genlu** [comment]
>  Also, do you have a callstack for how this is being used by the specific += feature? i want to see if the feature is behaving badly (like we mentioned for another feature here #24548 (comment)), or if the feature is fine and it's just this subalgorithm that needs to be significantly improved.

I'm interested in this too, unfortunately I will be traveling so don't have time to investigate this myself. @sharwell maybe you can post the stacktrace please?

**Comment by rolandh** [comment]
If you give me instructions I can post the stack trace for you.
