### ISSUE TITLE
Enable Rename file to match class name feature for .Net Core projects

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#24560]
context https://github.com/dotnet/roslyn/issues/16546 
cc @davkean , not sure if this belongs to project system or here.

**Comment by ErikSchierboom** [comment]
This would be great!

**Comment by igsbr** [comment]
This feature also disabled for classic .Net Framework projects with the new SDK style .csproj file structure.

**Comment by davkean** [comment]
@igsbr For those projects, do they have a References node or a Dependencies node?

**Comment by igsbr** [comment]
VS2017 shows Dependencies node in Solution Explorer for new SDK style projects and References node for old style projects.

**Comment by davkean** [comment]
Yeah I was just trying to see which project system you were using, both are using the new project system.

**Comment by igsbr** [comment]
As I know, the new SDK style .csproj is differ. I mean, it contains something like this:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
</Project>
```
But, if you create a clean .Net Framework project in VS2017, you'll end up with the much more verbose .csporj file (old style):
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
...
... 
...
```

**Comment by davkean** [comment]
Yes that's correct. 

You stated: 

>This feature is also disabled for classic .Net Framework projects with the new SDK style .csproj file format.

What I meant above, is that this project is also using the new project system (http://github.com/dotnet/project-system), and hence the same underlying bug.

**Comment by igsbr** [comment]
In the my first statement I just wanted to point out, that this issue is possibly related not only to .Net Core projects. So, I totally agree with your last statement.

**Comment by davkean** [comment]
👍

**Comment by quetzalcoatl** [comment]
We're still missing that feature :( I know that's not a critical one, but are there any plans for patching it up and reenabling?

**Comment by MrTrillian** [comment]
As a user, it wasn't obvious to me that this has to do with .NET Core/SDK-style projects and it just feels like an unfortunate regression in my Visual Studio experience :(
