### ISSUE TITLE
Intellisense propose generic extension for all types if T not resolved

### ISSUE THREAD

**Issue by VanKrock** [dotnet/roslyn#24561]
**Version Used**:  15.5.6

Intellisense propose generic extension for all types if T not resolved

**Steps to Reproduce**:

``` csharp
    public interface ISettable<T>
    {
    }

    public class Control<T> : ISettable<T>
    {
    }

    public static class ControlExtensions
    {
        public static TControl Set<TControl, T>(this TControl control, T value) where TControl : ISettable<T>
        {
            return control;
        }
    }
```

``` csharp
    class Program
    {
        static void Main(string[] args)
        {
            var @object = new object().
        }
    }
```

**Expected Behavior**:
Intellisense propose Set only for `ISettable<>`
ideally `Set(string value)` for `ISettable<string>`, `Set(int value)` for `ISettable<int>`

![vs2017expected](https://user-images.githubusercontent.com/3887988/35640918-70405574-06e0-11e8-91b3-35a61ac675ac.png)

**Actual Behavior**:
Intellisense propose Set for object, this `var @object = new object().Set(1);`  can never be compiled because object not `ISettable<>`

![vs2017](https://user-images.githubusercontent.com/3887988/35640931-7b164a1c-06e0-11e8-920c-26fe320de7d1.png)

**Comment by CyrusNajmabadi** [comment]
@gafter I can see why this would happen.  The IDE just calls: ```LookupSymbols(..., includeReducedExtensionMethods: true)```.  This is clearly a reduced extension method that the compiler would certainly consider.  However, the candidate is not viable as the instantiation of T doesn't match the constraint.

I can see this being a generally difficult issue is we're working with incomplete information. For example, it's potentially possible that a *later* argument might provide enough information to allow the compiler to infer a type for the type parameters that would satisfy constraints. (Though i haven't convinced myself of that).

Would it be reasonable for the compiler to at least check the inferred type parameters *that are utilized in the first arg* to see if they satisfy their constraints @gafter?  Filtering out ones that don't?   If not, the IDE layer could try to do this.  Though i'm not sure if constraint viability checking will be easy to do, or will be very complex.  For example, if there are constraint relationships between type parameters.

**Comment by VanKrock** [comment]
May be it's real to make more than one "this" in extension method?
``` cs
        public static TControl Set<TControl, T>(this TControl control, this ISettable<T> settable, T value)
        {
            return control;
        }
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
