### ISSUE TITLE
Move to a 2.1.300-preview build of .NET Core SDK

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn#24591]
Currently the roslyn build depends on a daily build of .NET Core SDK 2.2.0-preview.  However, following https://github.com/dotnet/designs/pull/29, the .NET Core SDK release that was going to be named 2.2 is now named 2.1.300.  So recent 2.1.300 builds are actually newer than historical 2.2.0 builds. 

Roslyn moving to a 2.1.300 build helps in several ways:

1. We shouldn't reference 2.2.0 SDK in the contributor docs since it no longer corresponds to a real upcoming version of the SDK.
2. Installing a 2.2.0 build on your machine will shadow 2.1.300 so you'll be using this build instead of a 2.1.300 preview (that is really newer) in projects without global.json (*)
3. We'd like to get roslyn on to a newer build to get more dogfooding coverage of recent SDK changes (particularly around build perf).

(*) Folks should also be instructed somewhere to uninstall any 2.2.0-preview on their machines when installing 2.1.300-preview.

cc @jaredpar

**Comment by nguerrera** [comment]
> Folks should also be instructed somewhere to uninstall any 2.2.0-preview on their machines when installing 2.1.300-preview.

Link to https://github.com/dotnet/announcements/issues/57

**Comment by jaredpar** [comment]
done.
