### ISSUE TITLE
Make CodeActionEditHandlerService support multiple ApplyChangesOperations, and other Operations that update the solution

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#246]
Ported from TFS WorkItem: <b>1079724</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P><B>Affected Branch:</B> <BR><B>Affected Build:</B> <BR><B>Affected Product Language:</B> <BR><BR><B>Steps to reproduce:</B><BR></P>
<P><EM>Note: discussed this with HeeJae offline</EM><BR></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><FONT color=#000000>The RenameTrackingCodeAction modifies the solution without extending from ApplyChangesCodeAction, and only one solution-changing CodeActionOperation is allowed/expected by CodeActionEditHandlerService, so a theoretical CodeAction that did what RenameTrackingCodeAction did and also provided another ApplyChangesOperation could trick that infrastructure into applying changes to stale solutions. </FONT></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><FONT color=#000000></FONT>&nbsp;</P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><FONT color=#000000>Talked with HeeJae about this and we agree that we should remove the restriction of having at most one ApplyChangesOperation, which would allow RenameTracking to accomplish its two-phase undo system by providing two ApplyChangesCodeAction instead of its own special CodeAction that applies multiple changes to the workspace. This also protects the CodeActionEditHandlerService from accidentally applying bad edits.</FONT></P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By David Poeschl (11/10/2014 4:14:55 PM)

------------------------------

2) Edited By Manish Vasani (12/11/2014 11:51:33 PM)

<p>I think even this one needs to be discussed at the design meeting/team meeting&nbsp;as there are multiple possible scenarios for creating multiple ApplyChangesOperations in a CodeAction:</p>
<p>&nbsp;</p>
<div id=divRplyFwdMsg style="WHITE-SPACE:normal;WORD-SPACING:0px;TEXT-TRANSFORM:none;COLOR:rgb(33,33,33);FONT:16px Calibri, Arial, Helvetica, sans-serif;LETTER-SPACING:normal;BACKGROUND-COLOR:rgb(255,255,255);TEXT-INDENT:0px;" dir=ltr><font style="FONT-SIZE:11pt;" color="#000000" face="Calibri, sans-serif"><em><b>From:</b><span class=Apple-converted-space>&nbsp;</span>Manish Vasani<br><b>Sent:</b><span class=Apple-converted-space>&nbsp;</span>Thursday, December 11, 2014 5:18 PM<br><b>To:</b><span class=Apple-converted-space>&nbsp;</span>HeeJae Chang; David Poeschl; Srivatsn Narayanan<br><b>Subject:</b><span class=Apple-converted-space>&nbsp;</span>Bug 1079724: Make CodeActionEditHandlerService support multiple ApplyChangesOperations, and other Operations that update the solution</em></font>
<div><em>&nbsp;</em></div></div>
<div style="WHITE-SPACE:normal;WORD-SPACING:0px;TEXT-TRANSFORM:none;COLOR:rgb(33,33,33);FONT:16px Calibri, Arial, Helvetica, sans-serif;LETTER-SPACING:normal;BACKGROUND-COLOR:rgb(255,255,255);TEXT-INDENT:0px;">
<div class=WordSection1>
<p class=MsoNormal style="FONT-SIZE:12pt;FONT-FAMILY:'Times New Roman', serif;MARGIN:0in 0in 0pt;"><span style="FONT-FAMILY:Calibri, sans-serif;"><em>I am not sure I understand the exact design required for this bug. Allowing multiple ApplyChangesOperations could mean all of them are independent and based off the same base solution (batch edits) OR all of them are sequential and each one is based off previous ApplyChangesOperation’s updated solution OR there are a mix of these. For the batch case, we can compute merged changed solution with appropriate merge resolution (like linked file and Fix all batch fixer cases). We can add another field on ApplyChangesOperation ctor to take the base solution for it and then determine if it is batch or sequential case and do the appropriate edit. However, I am not sure if we want to/should support all these cases. Did we have something specific in mind here?</em></span></p></div></div>
<p>&nbsp;</p>
<p>Maybe one of the possible outcome (which I haven't mentioned in the email above) is to retain the current design of allowing a single ApplyChangesOperation. When a code action needs multiple ApplyChanges, possibly interleaved with other operations, maybe its best to let the client deal with applying the changes themselves by using custom code action operations, rather then us having to&nbsp;create a complicated infrastructure of handling serial/batch changes and merging these together, when we don't even know if there would be many scenarios that require this support. </p>
<p>Our current support is quite similar to batch fix all provider, we provided infrastructure for simple code actions with single apply changes operation, but ask the clients to do it themselves for complicated code actions such as rename needing multiple solution updates.</p>

------------------------------

**Comment by dpoeschl** [comment]
Discussed this with @heejaechang and we think the best approach here is to leave continue to only support one ApplyChangeOperation, and to add better documentation to explain that if you require something more complex than a single ApplyChangeOperation, then you should

- Make your own CodeActionOperation
- Don't use *any* ApplyChangesOperations during GetOperationsAsync
- Handle all workspace edits yourself
- Handle the undo stack
- Handle preview generation (you can generate your own preview entirely or have GetPreviewOperationsAsync return a single ApplyChangesOperation to take utilize the built-in preview mechanism)

Assigning this to myself to clean this list of restrictions up and turn into a reasonable doc comment.

**Comment by heejaechang** [comment]
Thank you.

I forgot to assign it to you yesterday ☺


-          Heejae
