### ISSUE TITLE
Test localization failures on non english machines: VisualBasicParseOptions.ValidateOptions localizes error argument eager.

### ISSUE THREAD

**Issue by MaStr11** [dotnet/roslyn#24604]
Extracted from the closed PR #24539 

**Steps to Reproduce**:

Run `Microsoft.CodeAnalysis.VisualBasic.UnitTests.GetDiagnosticsTests.CompilingCodeWithInvalidPreProcessorSymbolsShouldProvideDiagnostics` on a non-english machine. (There are more tests affected by this bug. See the original PR for details).

**Expected Behavior**:

Test passes.

**Actual Behavior**:

Test fails because [VisualBasicParseOptions.ValidateOptions](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/VisualBasicParseOptions.vb#L255) localizes the error argument eager.

**History**

The issue was discussed but not resolved in #24539. The relevant sections are:

@Mastr11
The diagnostic under test is created here like so:
`builder.Add(Diagnostic.Create(MessageProvider.Instance, ERRID.ERR_ConditionalCompilationConstantNotValid, VBResources.ERR_ExpectedIdentifier, symbol.Key))`
If I got you you right it should be created like this one:
```CS
diagnostics.Add(
    messageProvider.CreateDiagnostic(code, Location.None, 
        new CodeAnalysisResourcesLocalizableErrorArgument(errorArgumentResourceId)));
```
It seems there isn't a VBResourcesLocalizableErrorArgument class (at least I couldn't find anything suitable).

@AlekseyTs
There is Microsoft.CodeAnalysis.VisualBasic.LocalizableErrorArgument type.
Alternatively, for consistency with other places where the same diagnostics is created (that is the approach I would prefer), we should be able to call Diagnostic.Create overload that takes DiagnosticInfo. Like this:
```CS
Diagnostic.Create(ErrorFactory.ErrorInfo(ERRID.ERR_ConditionalCompilationConstantNotValid,
                                            ErrorFactory.ErrorInfo(ERRID.ERR_ExpectedIdentifier),
                                            symbol.Key))
```

**Comment by jcouv** [comment]
@MaStr11 fixed this with #25194 in 15.7. Closing
