### ISSUE TITLE
New generic class, No prompts if initialization

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24612]
The generic T constraint is a subclass of an interface with parameterless constructors, both A and B are properties of the interface new t{a=&quot;&quot;,b=&quot;&quot;}; The IDE does not hint

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/173607/new泛型类时若进行初始化则无提示.html
VSTS ticketId: 544394_
_These are the original issue comments:_

Ariel Yang - MSFT on ‎12‎/‎26‎/‎2017, 08:36 PM (37 days ago): <p>Translated from bing :</p><p>A generic t constraint is a subclass of an interface with a parameterless constructor, and A and B are all properties of an interface
<br>New T\{a= "", b= ""};
<br>The IDE does not hint<strong></strong><u></u><sub></sub><sup></sup></p>

Jinu Joseph [MSFT] on ‎1‎/‎7‎/‎2018, 06:00 PM (25 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
This issue concerns code like the following:

```csharp
internal interface IExample
{
    string A { get; set; }
    string B { get; set; }
}

internal class Example
{
    public static T Create<T>()
        where T : IExample, new()
    {
        return new T
        {
            A = "first",
//          ^-- IntelliSense should offer property 'A' here, but it does not
            B = "second",
        };
    }
}
```
