### ISSUE TITLE
F12 on Span type includes unnecessary attributes

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#24615]
In a new .NET Core project, add a reference to `System.Memory` package from myget (see info below).
Then use `Span` in code and GoToDefinition.

The `IsByRefLike` and the `IsReadOnly` attributes are displayed.
This is likely a compiler problem. The `GetAttributes` method should filter those attributes out.

![image](https://user-images.githubusercontent.com/12466233/35760051-728770ee-0832-11e8-8106-3905f09f3af4.png)

![image](https://user-images.githubusercontent.com/12466233/35760034-5e725434-0832-11e8-9f1b-821004f39185.png)

Tagging @VSadov @OmarTawfik 

Relates to https://github.com/dotnet/roslyn/pull/22553 (`[Obsolete]`)
Relates to https://github.com/dotnet/roslyn/pull/22504 (`[deprecated]`)
Relates to https://github.com/dotnet/roslyn/pull/24492 (`in` parameters)

**Comment by OmarTawfik** [comment]
Maybe related to #24490 as well

**Comment by jinujoseph** [comment]
@jcouv thanks for fixing this. closing the issue
