### ISSUE TITLE
SuggestedActionsSourceProvider is not resilient against documents that are not part of a workspace

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#24625]
**Version Used**: 
adbce761b91992740c128b7d4233f51b49541e97

**Steps to Reproduce**:

1. Have a C# .cs document that is not a part of a workspace (content type must be CSharp)
2. Open that document in an editor

**Expected Behavior**:
SuggestedActionsSource should be resilient against the situation where the text view/buffer for the .cs document is not added to the workspace.

**Actual Behavior**:
```
NullReferenceException:

Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.<GetFixLevelAsync>d__40.MoveNext() in /_/src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs:line 736
```

In these locations, we need to gracefully deal with the fact that document may be null:

http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Wpf/Suggestions/SuggestedActionsSource.cs,161
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Wpf/Suggestions/SuggestedActionsSource.cs,899

Note that this location already does the right thing:
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Wpf/Suggestions/SuggestedActionsSource.cs,671

**Comment by CyrusNajmabadi** [comment]
This looks like it's already checking for null: 
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Wpf/Suggestions/SuggestedActionsSource.cs,161
