### ISSUE TITLE
Decompiler: NullReferenceException in DecompileSymbolAsync

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#24626]
**Version Used**: 
adbce761b91992740c128b7d4233f51b49541e97

**Steps to Reproduce**:

When hosting Roslyn outside of Visual Studio we try to go to definition for `System.Windows.Media.Colors` and the decompiler is invoked. When trying to decompile, this line gets called:

http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs,198

This is because `var reference = compilation.GetMetadataReference(symbol.ContainingAssembly);` returns null. It asks for PresentationCore, and there is a PresentationCore in the list of references, however the object in the list is a different instance, and the lookup is simply done using ReferenceEquals, so since the objects are different the lookup fails. Not sure if the lookup in here should be using value identity:
http://source.roslyn.io/#Microsoft.CodeAnalysis/ReferenceManager/CommonReferenceManager.State.cs,420efd0d0f6c08ec
Not sure what the contract of the `GetMetadataReference` method is (reference identity or value identity?)

**Expected Behavior**:
Should work.

**Actual Behavior**:
```
NullReferenceException:
 	Microsoft.CodeAnalysis.CommonReferenceManager<Microsoft.CodeAnalysis.CSharp.CSharpCompilation, Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol>.GetMetadataReference Line 655	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.Compilation.GetMetadataReference Line 726	C#	Symbols loaded.
>	Microsoft.CodeAnalysis.Editor.Implementation.MetadataAsSource.MetadataAsSourceFileService.DecompileSymbolAsync Line 192	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.Editor.Implementation.MetadataAsSource.MetadataAsSourceFileService.GetGeneratedFileAsync Line 121	C#	Symbols loaded.
 	...SymbolNavigationService.TryNavigateToSymbol.AnonymousMethod__2 Line 88	C#	Symbols loaded.

```

**Comment by KirillOsenkov** [comment]
cc @sharwell @siegfriedpammer @tmat

**Comment by CyrusNajmabadi** [comment]
I don't repro this.
