### ISSUE TITLE
Proposal: Change generation of yield enumerator

### ISSUE THREAD

**Issue by stas-sultanov** [dotnet/roslyn#2463]
I would like to suggest to change the way `yield` enumerator is generated so it explicitly implements `IDisposable` instead of `IEnumerato<T>.Dispose()`.

In short: it looks like the only reason that `IEnumerator<T>` inherits from `IDisposable` is that `Dispose()` method is used with `yield` enumerator. 

more information and discussion can be found here [coreclr/issues/645] (https://github.com/dotnet/coreclr/issues/645)

**Comment by HaloFour** [comment]
I assume that you `IEnumerator` and not `IEnumerable`.  The iterator implements `IEnumerator<T>` which already implements `IDisposable`.  At the IL level that requires that the implementing class implement `IDisposable` directly and override those methods, as the iterator does.  The generated class already uses the C# convention for explicit implementation by naming the method `System.IDisposable.Dispose`, although that's an irrelevant detail and it could be named anything.  The override clause is explicitly set to `IDisposable.Dispose`, though.

Not sure what the CoreCLR/CoreFX request adds to the conversation other than the fact that the CoreFX team isn't willing to consider breaking `IEnumerator<T>` by not having that interface extend `IDisposable`.

**Comment by stas-sultanov** [comment]
@HaloFour oh boy. indeed it is about `IEnumerator<T>` not `IEnumerable`.
i'm not familiar with roslyn repo, so could not find where it is implemented now.
