### ISSUE TITLE
Generic extension method with `in this` parameter fails to compile

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#24641]
**Version Used**: 

master branch @ feb 5

**Steps to Reproduce**:

Compile the following code:
```c#
public static class C {
  public static ref readonly T E<T>(this ref T x) where T : struct => ref x;
}
```

**Expected Behavior**:

Successful compilation, the same as for `ref` extension version:
```c#
public static class C {
  public static ref readonly T E<T>(this ref T x) where T : struct => ref x;
}
```

**Actual Behavior**:

> error CS8338: The first parameter of an 'in' extension method 'E' must be a value type

**Comment by sharwell** [comment]
This seems very similar to #24601.

**Comment by controlflow** [comment]
Thanks, @sharwell ! What a confusing corner case, I was not realized any kind of member access would copy the struct in generic code since compiler can't tell if `T` is `readonly` struct or not...
