### ISSUE TITLE
Using ref-assembly feature breaks GoToDefinition

### ISSUE THREAD

**Issue by weltkante** [dotnet/roslyn#24643]
**Version Used**: VS 15.6.0 preview 3

**Steps to Reproduce**:
1. Create a solution with project A referencing project B where A calls a method defined in B
2. Add `<ProduceReferenceAssembly>true</ProduceReferenceAssembly>` to the project file of project B
3. Press F12 on the call site where project A calls project B (works, goes to definition of B)
4. Compile project, restart VS
5. Press F12 on the call site where project A calls project B (fails, goes to ref-assembly stub)

**Expected Behavior**:
It should not matter whether the project was compiled in a previous VS instance, "go to definition" should always go to the definition in project B.

**Actual Behavior**:
If the project is compiled and VS is restarted, Roslyn uses the ref-assembly without connecting it to project B, and instead generates a source file from metadata when doing "go to definition". It does not go to the actual definition in project B.

**Comment by sharwell** [comment]
Can you list the absolute file paths of the implementation and reference assemblies produced when you compile project B?

**Comment by weltkante** [comment]
Ok, I got mixed up while playing around and trying to get the feature to work. It appears the steps above are not enough to reproduce the problem reliably, sorry.

Regarding your comment, due to playing around with the output path I had leftover files
1) E:\_code\ProjectDependencyTest\bin\Debug\ClassLibrary1.dll
2) E:\_code\ProjectDependencyTest\bin\Debug\ref\ClassLibrary1.dll
3) E:\_code\ProjectDependencyTest\ClassLibrary1\bin\Debug\ClassLibrary1.dll
4) E:\_code\ProjectDependencyTest\ClassLibrary1\bin\Debug\ref\ClassLibrary1.dll

maybe that was confusing VS/Roslyn. I'll try to see if I can get it to reproduce on a clean project.

That aside, do you expect the "go to definition" to work for non-project references when I annotate them with a <ReferenceAssembly> tag (parallel to HintPath)? Doing so makes optimized compilation work but breaks go-to-definition features, and its easier reproducable than the failure case for project references.
```
<Reference Include="ClassLibrary2">
  <HintPath>..\ClassLibrary2\bin\Debug\ClassLibrary2.dll</HintPath>
  <ReferenceAssembly>..\ClassLibrary2\bin\Debug\ref\ClassLibrary2.dll</ReferenceAssembly>
</Reference>
```

Thats the case I'm actually more interested in, but I don't know if its supported (or done correctly). If its not supported thats ok and I'll just try to find the breaking case for project references.

**Comment by sharwell** [comment]
Currently the Go To Definition feature is special-cases for reference assemblies only when they are produced by the build for another project in the same solution. See #20833. The specific conditions where it is expected to work are:

1. The reference assembly is produced by another project in the same solution
2. The reference uses `<ProjectReference>` (as opposed to `<Reference>` or `<PackageReference>`)
3. The path to the output assembly is not changed from the `ref` folder to any other location

**Comment by weltkante** [comment]
Ok good to know, then I don't have to keep trying getting it to work for normal references.

I don't know whats wrong with project references though, it's kinda flakey, sometimes they just stop working. I removed all temporary output including .vs directory. Then I keep reopening the solution, building and applying go-to-reference. It works for a while then suddenly breaks (turns into ref-assembly metadata generated source instead of going into the project).

I guess I'll keep trying some more to find some pattern, but for now its not reproducable unfortunately. Sorry, and thanks for the clarifications.
