### ISSUE TITLE
ContributingCode wikipage has missing link to CLA, stale link to style guide

### ISSUE THREAD

**Issue by SamB** [dotnet/roslyn#2464]
[ContributingCode](https://github.com/dotnet/roslyn/wiki/Contributing-Code) on the wiki doesn't appear to have any link for the CLA, and the link for the style guide seems to have gotten out of date.

For the CLA, you could link to either <https://github.com/dotnet/corefx/wiki/Contribution-License-Agreement-(CLA)> or <https://cla2.dotnetfoundation.org/>.

For the style guide, you probably want to link to <https://github.com/dotnet/corefx/wiki/Coding-style> rather than to <https://github.com/dotnet/corefx/wiki/Contributing#c-coding-style>.

**Comment by Pilchie** [comment]
@jaredpar @KevinRansom Either of you want to take a look?

**Comment by jaredpar** [comment]
Thanks for pointing that out.  I've updated the existing links and added a note about the CLA.

**Comment by amcasey** [comment]
The links seem to work.
