### ISSUE TITLE
LinkList.RemoveFirst/Last should return node

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#24669]
Its strange. AddFirst and AddLast returns the node. but remove doesn't return the node. makes it harder to work with LinkList.

I don't think it would be a breaking change to make void method to return something. unless there are reflection uses, but you are not promising on implementation details, do you? please fix it. thank you so much.

**Comment by HaloFour** [comment]
Framework changes belongs in the [CoreFX](https://github.com/dotnet/corefx) repository.

**Comment by HaloFour** [comment]
This change would certainly be a breaking change.  Method binding in IL is done with the full signature of the method, which includes the return type.  Any existing assemblies using that code would be broken.

You can solve the problem relatively easily with extension methods:

```cs
public static LinkedListNode<T> GetAndRemoveLast<T>(this LinkedList<T> list) {
    var node = list.Last;
    if (node != null) {
        list.Remove(node);
    }
    return node;
}
```

**Comment by MkazemAkhgary** [comment]
good to know. thanks.
