### ISSUE TITLE
Update System.Reflection.Metadata dependency

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#24677]
**Version Used**: 2.6.1

Roslyn builds and ships using old System.Reflection.Metadata dependency. The [fix](https://github.com/dotnet/corefx/issues/16354) was made to make System.Reflection.Metadata work on big-endian systems but Roslyn is still using very old version.

This blocks using Roslyn on big-endian systems and also makes features/enhancements like #24621 testing harder.

/cc @jaredpar

**Comment by tmat** [comment]
Once we update to the latest we can clean up: https://github.com/dotnet/roslyn/issues/24712

**Comment by agocke** [comment]
Also #23762

**Comment by tmat** [comment]
And https://github.com/dotnet/corefx/pull/27589

**Comment by davidwrighton** [comment]
And #25185

**Comment by tmat** [comment]
And https://github.com/dotnet/corefx/issues/1815: http://source.roslyn.io/#Microsoft.CodeAnalysis/MetadataReference/ModuleMetadata.cs,170

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/27023
