### ISSUE TITLE
Generate Overrides UI doesn't support multi-selection

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#24697]
**Version Used**: 
![image](https://user-images.githubusercontent.com/41759/35946453-a7edd8a6-0c18-11e8-8f7c-43b3611128fc.png)

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/41759/35946443-9e836a9c-0c18-11e8-8317-4013a8bd7c78.png)

1. Click on an item
2. Shift+Click on another line below the selected item

**Expected Behavior**:

Multiple items should be selected.

**Actual Behavior**:

Single item is selected.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
