### ISSUE TITLE
Test plan for "stackalloc initializers"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#24699]
This is a place to collect test ideas and track work items.
Relates to https://github.com/dotnet/csharplang/pull/1122

- [ ] optimization and endianess issue
- [ ] Test `GetOperation`
- [ ] Test [IDE scenarios](https://github.com/dotnet/roslyn/wiki/Manual-Testing)

Tagging @alrz

**Comment by VSadov** [comment]
I think we can close this now once #25160 exists.
