### ISSUE TITLE
Test with AllInOneCSharpCode should fail when new syntax nodes are introduced

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#24713]
Currently we have to remember to update those tests, and more often than not we forget.

**Comment by alrz** [comment]
It does fail, but apparently some nodes can sneak in. (like refs that you mentioned)

**Comment by jcouv** [comment]
Looking back at this issue, I don't really makes sense anymore. Even though we didn't necessarily always update AllInOneCSharpCode with new syntax, that didn't cause any particular problem.
I'll go ahead and close this.
