### ISSUE TITLE
Feature Request: Removed Unused Usings Ignore List

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#24710]
Copied from https://github.com/OmniSharp/omnisharp-vscode/issues/2018

Regardless of if they are currently used or not in the file, I always like to have 
```
using System;
using System.Linq;
```
In my list of usings. It would be fantastic if there was an option that let us specify which namespace should be ignored when the Remove unnecessary usings function is run.

**Comment by jcouv** [comment]
I agree it's useful to have some unused usings. For instance, the Expression Evaluator won't let you use Linq methods when debugging unless `using System.Linq;` is there. 

If that's the main scenario, another option to consider would be for the EE to always include those namespaces.

Tagging @cston in case something to add.

**Comment by cston** [comment]
I believe unused namespaces are not included in the PDB currently.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
