### ISSUE TITLE
[Idea] SubTokens

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#24734]
With pull request #23984 and #24110 being considered, which rely on parsing a string literal to expose feature / details within that string. Should we have a mechanism that we can hook up to, so can add additional information. These sub tokens will not affect to parsing, syntactic or semantic meaning of the code, that could be used later to provide syntax highlighting.

**Comment by CyrusNajmabadi** [comment]
Sorry, can you clarify what the idea is?

**Comment by gafter** [comment]
> Should we have a mechanism that we can hook up to

We already have a mechanism we can hook up to. It is the string’s value text.

**Comment by AdamSpeight2008** [comment]
@gafter  Try, put current we can only attach diagnostics. It be cool if we could also attach sub-nodes / additional highlighting or visualisations.

Given the following
```vbnet
Imports System
Public Class C
    Public Sub M()
        Const format ="YYYY/MM/DD"
        Const text ="2018/02/12"
        Dim result As DateTime=Nothing
        Dim valid As Boolean = DateTime.TryParseExact(Text,format, ... , ... ,result)
    End Sub
End Class
```
Say we want to highlight the content of the two following string. 
Where the obey the one of the following conditions
  * Is a Constant String Literal
  * Is a Reference to a constant string literal
Only if it is the following context
  * Used as the arguments of `DateTime.TryParseExact`
    * of the `text` and `format` parameters

The mechanism would take as inputs
  * the target node `DateTime.TryParseExact`
  * the named parameters
Returns (via an event)
  * the corresponding node, used for the arguments.
  * mechanism to attach "sub-nodes" to those nodes.
    * ` subnodemechanism.AddSubNode( textnode, classification )`

Now the all of the actual task of highlighting is handled by Roslyn IDE code,
  * Where we could provide an additional sub menu item 
```vbnet
Options
  Fonts And Colors
   Roslyn
      { Highlight Name } ( { Hightlighter Id } )
      { Highlight Name } ( { Hightlighter Id } )
      { Highlight Name } ( { Hightlighter Id } )
```

**Comment by gafter** [comment]
@AdamSpeight2008 We can currently report diagnostics on any span in source, not just on a syntax node or token. No change to the compiler is needed: even a diagnostic analyzer can do it.

**Comment by AdamSpeight2008** [comment]
@gafter Only Diagnostics not other things, which what this is about.

**Comment by gafter** [comment]
I don't know what those other things are. Until we have a language proposal that seems like it is gaining traction and requires this mechanism, I don't see why we should do anything with this issue other than close it.

**Comment by CyrusNajmabadi** [comment]
> True but current we can only attach diagnostics.
It be cool if we could also attach sub-nodes that don't affect the syntax or semantics.

Attaching one piece of data to another is fairly easy in .net.  Just use a ConditionalWeakTable.  In fact, that's how we implement annotations!  They're not actually 'attached' to nodes/tokens/etc.  Instead, we just have a table that maps from the underlying node to the annotation.  

This has the extra benefit of not having to bloat up your instances for data that isn't commonly needed.

If you want to attach data to a node/token.  I would recommend you go this way.

**Comment by AdamSpeight2008** [comment]
I was trying to explain what be embedded languages.

**Comment by CyrusNajmabadi** [comment]
@AdamSpeight2008 It's still not clear waht you're asking for.  thanks!
