### ISSUE TITLE
Installed analyzers should not run in referencing projects

### ISSUE THREAD

**Issue by drauch** [dotnet/roslyn#24732]
I've got two projects "A" and "A.Tests", where the second one is referencing the first one. I installed a Roslyn analyzer (via PackageReference) in project "A" and it works just fine. However, the analyzer is also executed for "A.Tests" which I don't want.

I cannot seem to remove it from "A.Tests" though, it is not contained in the csproj, it looks like the transitive dependency forces the analyzer to project "A.Tests". Is there a workaround to run the analyzer only for project "A" and not for "A.Tests"?

**Comment by drauch** [comment]
Okay, it looks like I have to manually add `<PrivateAssets>all</PrivateAssets>` to the PackageReference in the csproj files!

**Comment by sharwell** [comment]
Duplicate of NuGet/Home#4125
