### ISSUE TITLE
Replace usage of SHA1 with a non-crypto hash algorithm where not used for security purposes

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#24737]
- [ ] Calculating MVID and timestamp of PE file when building deterministically
- [ ] PrivateImplementationDetails.GenerateDataFieldName

**Comment by gafter** [comment]
Why would we do this?

**Comment by gafter** [comment]
I'd rather we move to a more modern crypto hash.

**Comment by jaredpar** [comment]
@gafter

> I'd rather we move to a more modern crypto hash.

I'd rather we move to a non-crypto hash. Having a crypto-hash in your code is essentially code that will always need to be changed. What is modern crypto today is broken crypto tomorrow. This entire issue comes from the fact we thought SHA1 was modern, now it's broken and security people sit on us until we delete it. If we move to a non-crypto hash then the code is done and settled. This is why I prefer crypto only in places we need cryptography. We can still use a strong hash here.

**Comment by tmat** [comment]
We actually do need a strong crypto hash for calculation of PDB checksum.
However, now that we switched the default value of `/checksumalgorithm` to `SHA256`, we can use the hash specified by this parameter everywhere where we currently use hardcoded hash.

**Comment by jaredpar** [comment]
I'd be fine with moving both of these to the default algorithm for the compiler. That doesn't really change our cost here. When the cheese moves we change one entry and all of our uses change with it. 

But I would think we'd tie it the default, not the user specified version. This isn't user visible as far as I know. Hence why vary it at all? Just use the default in both places.

**Comment by tmat** [comment]
Sure, that would work too. We only need to flow the user specified value to PDB checksum and PDB source checksums.
