### ISSUE TITLE
Avoid public fields in Roslyn API

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#2476]
I have noticed we expose some public fields from the compilers (about 30 or so). I believe the .NET API guidelines prefer using properties for public APIs.

**Comment by AnthonyDGreen** [comment]
Are they all static fields? The guidelines still apply but it's less of a clear cut problem for me if they're all the moral equivalent of String.Empty.

**Comment by tmat** [comment]
Some of them are instance fields.

**Comment by AnthonyDGreen** [comment]
Blasphemy!

Regards,

-ADG

Sent from my Windows Phone
________________________________

**Comment by jaredpar** [comment]
I think we should also consider moving many of our static fields to properties.  

Lately I've been doing a bit of work moving our code to Mono.  One difference I've found is Mono is generally less tolerant of static initialization cycles than the CLR.  In many cases it will end with a statkc overflow where CLR will succeed.  Using our code on Mono in that case requires us to switch to a delayed initialization pattern. 

This change is simply but only really possible in places where the static data is exposed as a property.  In the case where it is exposed as a `readonly static` field there isn't much of an option besides first converting it to a property.  

We won't be at full Mono support by RTM hence it's possible more errors are lurking around waiting for us to find.  Moving to properties helps ensure we can fix these issues up later on.

**Comment by tmat** [comment]
@jaredpar I agree.

**Comment by AnthonyDGreen** [comment]
Agreed. I believe the Fx guidelines on static read-only fields is to use properties instead. YAGNI, I know but it also gives us the flexibility to make static state lazy in the future if we need to.

Regards,

-ADG

Sent from my Windows Phone
________________________________

**Comment by tmat** [comment]
Fixed by fb3b7665838bfb932ca9843a1bba01e069d40129

**Comment by tmat** [comment]
@gafter Could you verify? I heard you're currently handling some other public API surface fixes.

**Comment by tmat** [comment]
Reopening. Compiler should be clean, but we have more public fields in Workspace layer.

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/commit/ec34f270932e82bafaa7e37cc15842726bf51ad0
