### ISSUE TITLE
'Use local function' breaks code that uses named arguments

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#24764]
**Steps to Reproduce**:

```c#
delegate void MyDelegate(string arg);

void M()
{
    MyDelegate d = s => { };

    d(arg: "hello");
}
```

after invoking 'Use local function' on `d`:

```c#
void d(string s)
{ }

d(arg: "hello");
```

code doesn't compile because there's no `arg` on `d`.

**Comment by Neme12** [comment]
what should be done here? renaming the parameters in the function signature seems like a bad idea given that everybody uses `Func`s anyway... so should we change all the invocations to the local function argument names?

**Comment by CyrusNajmabadi** [comment]
Two options: 

1. don't offer the fix.
2. rename the named argument (at the invocation point) to be the new name.

**Comment by Neme12** [comment]
if I were to do this should i really make a separate PR with possible conflicts or just put it in the same one?

**Comment by CyrusNajmabadi** [comment]
I'd be fine with it all being in the same PR.
