### ISSUE TITLE
'Use local function' should be offered for anonymous methods as well as lambdas

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#24760]
**Steps to Reproduce**:

```c#
Action a = () => { Console.WriteLine(); };
Action b = delegate () { Console.WriteLine(); };
```

Click on `a`. 'Use local function' is suggested. No such thing on `b`.

**Comment by Neme12** [comment]
Can I take this?

**Comment by CyrusNajmabadi** [comment]
Go for it!

**Comment by Neme12** [comment]
There's still a pending fix that should probably be taken care of: #23465

**Comment by Neme12** [comment]
I found another bug while browsing through the code:
```c#
delegate string MyDelegate(string arg = "");

void Main()
{
    MyDelegate a = x => x;
    MyDelegate b = (x) => x;
    MyDelegate c = (string x) => x;

    a();
    b();
    c();
}
```
`a` and `b` get converted correctly but `c` won't get a default parameter. I will fix this & add a test for it.

**Comment by Neme12** [comment]
I'm afraid there's a much bigger issue with named parameters... but that should go into a separate one.

**Comment by Neme12** [comment]
What to do here:
```c#
Action<string, int> a = delegate { };

 a("", 0);
```

1. fill in parameters from the delegate (in this case & in most cases arg1, arg2)
2. remove arguments at invocation point?

**Comment by Neme12** [comment]
another bug:
```c#
Action x = (a, b) => { };
```
crashes the code fix. will add a test too

**Comment by CyrusNajmabadi** [comment]
```c#
Action<string, int> a = delegate { };

 a("", 0);
```

> fill in parameters from the delegate (in this case & in most cases arg1, arg2)

Yes.

> remove arguments at invocation point?

Definitely not. :)

> another bug:

Could you fix this?  It seems like it's likely just an index out of bounds issue.

**Comment by Neme12** [comment]
@CyrusNajmabadi I already fixed it. It's definitely not an out of bounds issue because in all other cases, the parameters are taken from the anonymous function parameter list, NOT from the delegate. This is obvious with broken code.

**Comment by Neme12** [comment]
yet another bug:
```c#
Action x = null;
x = () => {
};

x.Invoke();
```
is converted correctly but this:
```c#
Action x = null;
x = () => {
    x.Invoke();
};
```
results in a crash.

**Comment by Neme12** [comment]
another one:
```c#
using System;

class C
{
    void M()
    {
        Action a1 = () => { };
        Action a2 = () => { };

        a1.Invoke();
    }
}
```
fix all crashes

**Comment by Neme12** [comment]
and hopefully the last bug:
```c#
Func<string, string> a = s => s;

a.Invoke(a.Invoke(null));
```
also a crash

**Comment by Neme12** [comment]
What does "_Product-level triaged" mean?

**Comment by jinujoseph** [comment]
it means it's been triaged(selected/prioritized) for a particular milestone
