### ISSUE TITLE
C# 7.2 private protected not respected by dynamic

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24775]
Reproducing program:

```csharp
using System;

namespace NetFXAccessTest
{
    class Program
    {
        static void Main(string[] args)
        {
            new B().CheatPrivateProtected(new A());
            Console.Read();
        }
        public class A
        {
            private protected void Method(int x)
            {
                Console.WriteLine(x);
            }
        }

        public class B
        {
            public void CheatPrivateProtected(A a)
            {
                dynamic d = a;
                d.Method(2);
            }
        }
    }
}
```

Expected behaviour:

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: ''NetFXAccessTest.Program.A.Method(int)' is inaccessible due to its protection level'

Actual behaviour:

Outputs '2' to the console.

https://github.com/dotnet/corefx/issues/25521 reports this as far as CoreFX goes. This report is intended as per NetFX.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/159910/c-72-private-protected-not-respected-by-dynamic.html
VSTS ticketId: 532955_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jcouv** [comment]
Tagging @gafter

**Comment by VSadov** [comment]
The bug has been fixed in Core FX. The fix is also tagged as “netfx-port-consider”. 

Note that .NET FX has different release cadence and different bar for fixes, and that also depends on version/milestone. It is hard to tell at the moment when the fix will be ported.

**Comment by jaredpar** [comment]
Thanks for the feedback. This is covered by our umbrella `dynamic` for new language features issue. 

https://github.com/dotnet/roslyn/issues/24815
