### ISSUE TITLE
Microsoft.CodeAnalysis.Common - need NetStandard 2.0 version

### ISSUE THREAD

**Issue by PolywickStudio** [dotnet/roslyn#24772]
**Version Used**: 
Microsoft.CodeAnalysis.Common - 2.6.1

**Steps to Reproduce**:
1. Add Microsoft.CodeAnalysis.Common to dotnet core 2.0 project. 
2. Deploy project on Linux or Windows.
3. Project fails to load in Linux, Windows fresh install. 

**Expected Behavior**:
Error due to dependency on netstandard1.3

**Actual Behavior**:
Need a version that compiles or installs on dotnet core 2.0

**Comment by jmarolf** [comment]
@PolywickStudio can you give the error you are seeing?

**Comment by PolywickStudio** [comment]
On deployment, I get - requires: 
System.Text.Encoding 4.3.0 

and there's no version for netstandard 2.0 ...

**Comment by PolywickStudio** [comment]
is there a way to bind Microsoft.CodeAnalysis.Common to DotNet Core 2.0, or NetStandard 2.0 ?

**Comment by jmarolf** [comment]
I Created a new project that has the following project file contents:
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="2.6.1" />
  </ItemGroup>

</Project>
```

Both `build` and `publish` work for me and I have `System.Text.Encoding.CodePages.dll` deployed correctly to `bin\Debug\netcoreapp2.0\publish\runtimes\win\lib\netstandard1.3\System.Text.Encoding.CodePages.dll` 

I would expect `netstandard1.3` packages to just work in a `netcoreapp2.0`.  Can you give me an example project so I can reproduce the problem? Thanks!

**Comment by sharwell** [comment]
:memo: The versioning policy of .NET Standard mandates this scenario work without creating a new netstandard2.0 build of the library, so we need to figure out the bug but adding a new target isn't the solution here.

/cc @terrajobst

**Comment by PolywickStudio** [comment]
Fixed. it works by putting the System.Text.Encoding.CodePages.dll to: 
 \Debug\netcoreapp2.0\publish\runtimes\win\lib\netstandard1.3\System.Text.Encoding.CodePages.dll
