### ISSUE TITLE
.NET 4.7 -  '\0' char in String causes GetHashCode to ignore remainder -- but on x64 only

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24780]
The `GetHashCode(...)` function for the **ordinal** `String` comparisons In **.NET 4.7** has a grossly different behavior between running on **x86** versus **x64**. Note: ***I am not talking about the different hash code values, per-platform***, since these are intended as opaque -- rather, the issue here is a ***semantic difference*** in runtime behavior between the two platforms.

On **x86**, the full length of a `String` is always hashed, regardless of any `\0` characters.

On **x64**, the hashing terminates at the first `\0` character.

This is trivial to demonstrate:

	var h1 = "\0AAAAAAAAA".GetHashCode();
	var h2 = "\0BBBBBBBBBBBB".GetHashCode();
	var h3 = "\0CCCCCCCCCCCCCCC".GetHashCode();

	// x64 results:
	//		0x162a16fe
	//		0x162a16fe
	//		0x162a16fe

	// x86 results:
	//		0x07b801bc
	//		0x048e22a3
	//		0x21e2037d

As shown above, this affects the `GetHashCode` instance virtual method (overriden by the `String` type), as well as two other **.NET**-provided techniques for obtaining an ordinal-based `String` hash code: `StringComparer.Ordinal.GetHashCode` and also `CultureInfo.CurrentCulture.CompareInfo.GetHashCode` (when using `CompareOptions.Ordinal`). These results are summarized below:

<pre>
-------------------------- x86 --------------------------
&quot;\0AAAAAAAAA&quot;
s.GetHashCode					0x07b801bc
StringComparer.Ordinal.GetHashCode		0x07b801bc
CompareInfo.GetHashCode/CompareOptions.Ordinal	0x07b801bc

&quot;\0BBBBBBBBBBBB&quot;
s.GetHashCode					0x00001505
StringComparer.Ordinal.GetHashCode		0x00001505
CompareInfo.GetHashCode/CompareOptions.Ordinal	0x00001505

&quot;\0CCCCCCCCCCCCCCC&quot;
s.GetHashCode					0x21e2037d
StringComparer.Ordinal.GetHashCode		0x21e2037d
CompareInfo.GetHashCode/CompareOptions.Ordinal	0x21e2037d

-------------------------- x64 --------------------------
&quot;\0AAAAAAAAA&quot;
s.GetHashCode					0x162a16fe
StringComparer.Ordinal.GetHashCode		0x162a16fe
CompareInfo.GetHashCode/CompareOptions.Ordinal	0x162a16fe

&quot;\0BBBBBBBBBBBB&quot;
s.GetHashCode					0x162a16fe
StringComparer.Ordinal.GetHashCode		0x162a16fe
CompareInfo.GetHashCode/CompareOptions.Ordinal	0x162a16fe

&quot;\0CCCCCCCCCCCCCCC&quot;
s.GetHashCode					0x162a16fe
StringComparer.Ordinal.GetHashCode		0x162a16fe
CompareInfo.GetHashCode/CompareOptions.Ordinal	0x162a16fe
</pre>

While I do realize that theoretical practice deems hash codes purely advisory, in practice applications will be designed to expect that hash code collisions are rare. Being able to trivially produce an infinite number of identical hashes, at will -- such as one can do via &quot;\0A&quot;, &quot;\0B&quot;, &quot;\0C&quot;, &quot;\012345...&quot;  (on **x64** all of these give the same hash code as above, `0x162a16fe`)-- is neither in the spirit of hashing nor accepted/expected common practice.

Worse, this only happens on the  x86 platform and not x64, which could cause considerable loss of design and development effort, if such proceeded based on a false impression of consistent behavior.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/196675/net-47-0-char-in-string-causes-gethashcode-to-igno-1.html
VSTS ticketId: 565715_
_These are the original issue comments:_

Glenn Slayden on 2/9/2018, 06:39 PM (2 days ago): <p>I should also mention that the **x64** version of `String.GetHashCode(...)` in fact makes no reference to the string's length whatsoever, neither to incorporate that value into the hash, nor to determine how many characters to compute the hash code for. Instead, the x64 code ***just scans the string forward until it hits the first '\0' char***. If there are no embedded nulls, then it will scan to the end, where the **CLR** ensures there will always be an extra `\0` char (that is not included in the `Length`).</p><p>Thus, by ignoring the stored length of the string, the x64 code *takes a critical dependency* on that zero-terminating char being present. If that `\0` gets corrupted somehow, the failure mode is severe, since that loop can immediately scan off the end of the string into unrelated memory areas. </p><p>Since the **x86** version refers to the stored string length to determine how many chars to hash--it might seem like that code doesn't have the same problem, and it's true that it's not as fatal, as follows:</p><p>The x86 code does actually take a ***different kind of dependency*** on the zero terminator, namely, that loop is written such that the 16-bit terminator value itself is `XORed` into the returned hash value whenever the two lowest bits of the input string length are equal to `0b_00000011 == 0x03`. For that operation to have no effect, the terminator must be zero (since `xor` with zero is a `nop`.)  So if the terminator somehow becomes corrupted, the returned hash code value will be affected, but there won't likely be an immediate `AccessViolationException` (as with the x64 case).</p>

_These are the original issue solutions:_
(no solutions)

**Comment by Joe4evr** [comment]
Curious, does this also repro for the `OrdinalIgnoreCase` variants?

**Comment by jcouv** [comment]
@AlexGhiondea Could you help route? It feels like either a runtime or a BCL issue on desktop.

**Comment by glenn-slayden** [comment]
Yes, it should be BCL. The problem is with MSIL code that exists in the `String.GetHashCode` function in mscorlib.dll. The difference between **x64** and **x86** is due to there being different mscorlib.dll builds for each.

**Comment by glenn-slayden** [comment]
@jinujoseph  The 'Area-IDE' tag doesn't sound right; as I mentioned the problem is with runtime code in the Base Class Library.

**Comment by jcouv** [comment]
I'll move the issue over to corefx

**Comment by jcouv** [comment]
Issue moved to [dotnet/corefx #27098](https://github.com/dotnet/corefx/issues/27098) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jinujoseph** [comment]
thanks @jcouv
