### ISSUE TITLE
Use local function (IDE0039) - introducing allocations and cannot be disabled by pragma

### ISSUE THREAD

**Issue by kindermannhubert** [dotnet/roslyn#24782]
**Version Used**: 15.5.5

**Steps to Reproduce**:
Suppose we have following code:
```c#
class Program
{
    static Action resultAction;

    static void Main()
    {
        var myClass = new MyClass();

        Action a = () => Console.WriteLine();

        myClass.Event += () =>
        {
            resultAction = a;
        };

        while (true)
        {
            myClass.Raise();
        }
    }

    class MyClass
    {
        public event Action Event;

        public void Raise() => Event();
    }
}
```

Action 'a' is allocated only once before while cycle. IDE0039 tells us we can use local function instead of lambda for definition of 'a'. Than we have:
```c#
void a() => Console.WriteLine();
```
But now the code is creating new delegate every time we call 'Raise' method in while cycle.

Not sure if it is even possible to be able to decide if change will lead to this degradation (though it would be ideal solution), but we should at least be able to disable such suggestion. Disabling by pragma work only partially.

Before pragma addion I see (correctly):
![r1](https://user-images.githubusercontent.com/11704036/36098037-b46b2a6e-0ffd-11e8-82ad-6a102f0b36a1.png)

After adding pragma:
```c#
#pragma warning disable IDE0039 // Use local function
        Action a = () => Console.WriteLine();
#pragma warning restore IDE0039 // Use local function
```
I see following in tooltip (incorrectly):
![r2](https://user-images.githubusercontent.com/11704036/36098073-da342bc4-0ffd-11e8-82a9-57f107a15d74.png)
but in Quick Actions it is not listed (correctly)
![r3](https://user-images.githubusercontent.com/11704036/36098075-dc36152c-0ffd-11e8-9a8b-f72c549d5c6f.png)

**Comment by Neme12** [comment]
Are you sure? I checked this in the debugger and only see 1 allocation.

**Comment by sharwell** [comment]
💭 This looks like one of the "stale error list" issues we've seen recently.

**Comment by kindermannhubert** [comment]
@Neme12 Quite sure. I saw the allocation in IL (was also debugging IL). Also if you add following to start of Main method:
```c#
        new Thread(() =>
        {
            while (true)
            {
                Console.WriteLine(GC.CollectionCount(0));
                Thread.Sleep(1000);
            }
        }).Start();
```
you will see a difference. Lambda approach is outputting zeroes but in local function approach GC count is still increasing. I'm running it in Release mode/ 64-bits / .NET 4.7.

**Comment by Neme12** [comment]
@kindermannhubert hm, you're right. My bad.

**Comment by Neme12** [comment]
@CyrusNajmabadi with respect to introducing allocations, is this something we're concerned about? This seems to me like an edge case that you'd be doing this in a loop, but I don't know of course. But when working on UseLocalFunction I *was* thinking that if the function isn't actually called and is only used to be converted back to a delegate, then that analyzer is not very helpful and it would probably be better to keep it as a delegate in that case. Converting it to a local function doesn't really make anything better.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi with respect to introducing allocations, is this something we're concerned about? 

I'm not.  However, i am concerned that one can't disable this suggestion.

**Comment by Neme12** [comment]
Well of course that's the bigger issue here.

**Comment by sharwell** [comment]
> However, i am concerned that one can't disable this suggestion.

@kindermannhubert If you restart the IDE after adding the suppression, do you still see the suggestion dots in the IDE, with a quick info tip saying "Use local function"?

**Comment by kindermannhubert** [comment]
> @kindermannhubert If you restart the IDE after adding the suppression, do you still see the suggestion dots in the IDE, with a quick info tip saying "Use local function"?

Yes, I do even after restart.

> @CyrusNajmabadi with respect to introducing allocations, is this something we're concerned about?

I'm very concerned :). I'm working in environment where allocations are unacceptable and it's unpleasant when IDE suggests you to introduce them (but understand if it's not possible to detect such situations).

I know the example is strange but it is very simplified.

**Comment by CyrusNajmabadi** [comment]
These refactorings are just giving you information about something you can potentially do.  It's not intended to have exactly equivalent semantics across the change.  For example, the feature which converts string concats into an interpolation does not produce code with the exact same runtime semantics.  

> I'm working in environment where allocations are unacceptable and it's unpleasant when IDE suggests you to introduce them 

I would suggest disabling these feature then :)  In general, we don't design them with a view that all allocations are unacceptable.  That's a high specialized environment that doesn't reflect the normal usage case for the majority of customers.

**Comment by CyrusNajmabadi** [comment]
Have validated that suppression works as expected:

![norepro](https://user-images.githubusercontent.com/4564579/76063330-5d869900-5f3c-11ea-80e7-774c69942f44.gif)
