### ISSUE TITLE
Rename of parameter not updating callsite

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#24790]
Repro steps

- Open Roslyn.sln
- Open CSharpTestBase.cs
- Navigate to CompileAndVerify on line 66
- Refactor Rename "additionalRefs" to "references"

Expectation is that it will update callsites using that parameter by name. It does not.

**Comment by jaredpar** [comment]
Hmm, this bug seems to be intermitently reproing only. I used refactor rename a number of times, got 500 errors after but now when I go back and try and use refactor / rename to clean up it's working.

**Comment by CyrusNajmabadi** [comment]
Is it possible Roslyn had not been fully loaded when you invoked the refactoring?

**Comment by jaredpar** [comment]
The solution has been up and loaded for 8+ hours at this point. 

I think more likely is that other errors were interfering with the IDE ability to do semantic analysis. Big change I'm working on. Possible small errors were causing larger binding issues (although F12 still seemed to work in that case).

**Comment by AdamSpeight2008** [comment]
Was it not updating named argument parameters?

**Comment by CyrusNajmabadi** [comment]
Wasn't able to repro this.  It's absolutely possible that if this were done whiel the solution was mid-error that there could be gaps in the set of results.
