### ISSUE TITLE
Cast not simplified or grayed out

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#24791]
Starting from this code, I inline the two variables:
![image](https://user-images.githubusercontent.com/12466233/36126703-88ba352a-100e-11e8-82d9-5e48278e7a67.png)

That produces the following code, with two unexpected and un-necessary casts:
![image](https://user-images.githubusercontent.com/12466233/36126724-9f4a417c-100e-11e8-8baa-f40ba5702f35.png)

Furthermore, those casts are not recognized as un-necessary and so are not grayed out or offered to simplify. I suspect that is another symptom of the same root problem.

The two methods involved and the operators all operate on `bool` types:
![image](https://user-images.githubusercontent.com/12466233/36126764-cf6eb1d0-100e-11e8-83d5-ba649c135c4d.png)

![image](https://user-images.githubusercontent.com/12466233/36126779-e2ed8e0c-100e-11e8-896b-7cce183c664f.png)

I'll try to provide a self-contained repro, but for context the above code is from PR https://github.com/dotnet/roslyn/pull/23356

**Comment by jcouv** [comment]
I'm able to repro this problem with the simple code below:
```C#
    class Program
    {
        bool Bool()
        {
            bool one = Bool();
            bool two = Bool();
            if (!one || !two)
            {
                throw null;
            }
            throw null;
        }
    }
```

**Comment by Neme12** [comment]
In 15.5, it gets inserted but greyed out.

**Comment by jcouv** [comment]
Thanks @Neme12 
Tagging @jinujoseph since looks like regression and adding corresponding label.
I'm using 15.6 preview 5 (`Version 15.6.0 Preview 5.0 [27409.1.d15.6]`)

**Comment by jcouv** [comment]
I tried at home on 15.6 preview 1.1 and got the same result (cast is there after inlining and not grayed out).

**Comment by jcouv** [comment]
Fix is going into 15.7

**Comment by Tragetaschen** [comment]
This looks like it fixes https://github.com/dotnet/roslyn/issues/7877 as well. Correct?

**Comment by jcouv** [comment]
@Tragetaschen I don't think so. The issue I fixed was just with logical boolean expressions.
I later realized that the issue (superfluous casts) is broader than I thought. I've filed https://github.com/dotnet/roslyn/issues/24853 on that.
