### ISSUE TITLE
Introduce Local generates an invalid return statement for void-returning expression methods

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#24807]
**Version Used**:

VS 15.6 Preview 4

**Steps to Reproduce**:

```cs
private void bar(int baz)
{ }

private void foo()
    => bar(100);
```

Mark the `100` and "Introduce local constant"

**Expected Behavior**:
```cs
private void bar(int baz)
{ }

private void foo()
{
    const int Baz = 100;
    bar(Baz);
}
```

**Actual Behavior**:
```cs
private void bar(int baz)
{ }

private void foo()
{
    const int Baz = 100;
    return bar(Baz); // note the additional return statement
}
```

![introduce-local-return](https://user-images.githubusercontent.com/1947968/36148045-dfa54738-10ba-11e8-9f1c-4a939014035e.gif)

**Comment by Neme12** [comment]
I found another bug, which is even more concerning. If you do this inside a local function, it just deletes the whole function:

```c#
private void foo()
{
    int local() => 50;
}
```
introduce local on 50 results in:
```c#
private void foo()
{
}
```

**Comment by Neme12** [comment]
Wow, there's a lot more bugs in this... on constructors for example it doesn't remove the semicolon. I'm taking this.

**Comment by Neme12** [comment]
It is also completely broken for expression-bodied get & set accessors:
```c#
int P
{
    get => 50;
}
```
introduce local on 50 deletes the getter.

**Comment by jcouv** [comment]
FYI @agocke

**Comment by Neme12** [comment]
Can I take care of this?

**Comment by jcouv** [comment]
@Neme12 Absolutely. Go for it!
You can enter the rabbit hole from `InlineTemporaryTests.cs` or `IntroduceVariableTests.cs` and go from there.

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Was this a failure in our test matrix approach?  Or did these features predate the test-matrix system entirely?

**Comment by Neme12** [comment]
There's a lot of tests in pairs like `TestIntroduceFieldInExpressionBodiedProperty` and `TestIntroduceLocalInExpressionBodiedProperty` in the code. I'm adding more for getters & setters & event add remove accessors & void vs non void methods & constructors & destructors & local functions, so there's going to be a lot of it. Do I still need to write a field version for each one as well, even though there shouldn't be any problem in there because theres' no need to rewrite the expression body into a block?

**Comment by CyrusNajmabadi** [comment]
It depends.  Do you feel like there is a reasonable chance that one test could break while the other woudl stay functioning?  If so, add the test.  If you feel like any break would cause all of them to fail, then there's no need for the extra tests.

**Comment by Neme12** [comment]
@jcouv 
> You can enter the rabbit hole from InlineTemporaryTests.cs or IntroduceVariableTests.cs and go from there.

how is this related to inline temporary?

**Comment by jcouv** [comment]
There are two scenarios described in this issue. One is inline temporary and the other is [introduce variable](https://github.com/dotnet/roslyn/issues/24807#issuecomment-365285086).
The two tests files I named are where I would add repros and start the investigation from.

**Comment by Neme12** [comment]
@jcouv I'm sorry I don't understand what's the scenario with inline temporary? The issue only describes a problem with "introduce local". Are you saying inline temporary should convert the method back to an expression body? It currently doesn't do that.

**Comment by jcouv** [comment]
@Neme12 My bad :-) 
I incorrectly read OP (thought it related to inline temporary).
