### ISSUE TITLE
Mispelling of VS code style option

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#24805]
![image](https://user-images.githubusercontent.com/4564579/36144367-b0628a2e-1062-11e8-84f4-86a0cbcdd405.png)

"Prefere" instead of "Prefer".

**Comment by Pilchie** [comment]
Why did you do this to us @CyrusNajmabadi ?

**Comment by CyrusNajmabadi** [comment]
Well... if you prefere it this way, then no need to change it!
