### ISSUE TITLE
Code fix providers should be able to add assembly/nuget references

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#24811]
Apparently Roslyn can already do this internally courtesy of their [IAddMetadataReferenceCodeActionOperationFactoryWorkspaceService](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/CodeRefactorings/WorkspaceServices/IAddMetadataReferenceCodeActionOperationFactoryWorkspaceService.cs) 
and [InstallPackageDirectlyCodeActionOperation](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/AddPackage/InstallPackageDirectlyCodeActionOperation.cs), but these are internal.

I have code fix providers that introduce compile errors into the receiving project unless certain references exist, which I'd like to add as part of the offered fix. Can Roslyn please support this?

**Comment by AArnott** [comment]
CC: @jasonmalinowski

**Comment by jinujoseph** [comment]
cc @DustinCampbell

**Comment by CyrusNajmabadi** [comment]
Closing out.  This needs to go through API review if we wwanted to do this.
