### ISSUE TITLE
Unit-test Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenShortCircuitOperatorTests.ConditionalBoolExpr01b fails on non-English OS

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#2481]
Assemblies Run

Roslyn.Compilers.CSharp.Emit.UnitTests.dll

Summary

Tests run: 3399   Failures: 1, Skipped: 22, Run time: 250.493s

Failed tests

0.312s
✘
 Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenShortCircuitOperatorTests.ConditionalBoolExpr01b : Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : Execution failed for assembly 'C:\Users\alekseyt\AppData\Local\Temp\RoslynTestFailureDump\02913912-2f61-4468-adcb-fb4da6c8fe05'. Expected: False Arithmetic operation resulted in an overflow. Actual: False Переполнение в результате выполнения арифметической операции. 
   в Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, String expectedOutput) в F:\Roslyn\Main\Open\src\Test\Utilities\HostedRuntimeEnvironment.cs:строка 309
   в Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures) в F:\Roslyn\Main\Open\src\Test\Utilities\CommonTestBase.CompilationVerifier.cs:строка 116
   в Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(CommonTestBase test, Compilation compilation, IEnumerable`1 dependencies, TestEmitters emitters, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`2 assemblyValidator, Action`2 symbolValidator, Boolean collectEmittedAssembly, Boolean verify) в F:\Roslyn\Main\Open\src\Test\Utilities\CommonTestBase.cs:строка 344
   в Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, TestEmitters emitters, Action`2 sourceSymbolValidator, Action`2 assemblyValidator, Action`2 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean collectEmittedAssembly, Boolean verify) в F:\Roslyn\Main\Open\src\Test\Utilities\CommonTestBase.cs:строка 237
   в Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(String[] sources, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, TestEmitters emitters, Action`2 sourceSymbolValidator, Action`2 assemblyValidator, Action`2 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, Boolean collectEmittedAssembly, Boolean verify) в F:\Roslyn\Main\Open\src\Test\Utilities\CommonTestBase.cs:строка 170
   в Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(String source, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, TestEmitters emitters, Action`2 sourceSymbolValidator, Action`2 assemblyValidator, Action`2 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, Boolean collectEmittedAssembly, Boolean verify) в F:\Roslyn\Main\Open\src\Test\Utilities\CommonTestBase.cs:строка 134
   в Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(String source, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, TestEmitters emitters, Action`1 sourceSymbolValidator, Action`2 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, Boolean collectEmittedAssembly, Boolean verify) в F:\Roslyn\Main\Open\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:строка 79
   в Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenShortCircuitOperatorTests.ConditionalBoolExpr01b() в F:\Roslyn\Main\Open\src\Compilers\CSharp\Test\Emit\CodeGen\CodeGenShortCircuitOperatorTests.cs:строка 5908

**Comment by jaredpar** [comment]
Fixed in #6633
