### ISSUE TITLE
Add CamelHumps selection similar to that of resharper

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24823]
ReSharper has a CamelHumps option which lets you select segments of text based on the casing. Using Ctrl+Shift + left or right will select segments of CamelCasedText instead of the entire thing. I'd really like to see visual studio support this out of the box.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/46440/add-camelhumps-selection-similar-to-that-of-reshar.html
VSTS ticketId: 419362_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This would be something that would be provided by VS, not roslyn.  Tagging @olegtk .
