### ISSUE TITLE
Can we get NormalizeWhiteSpace that Preserves LineFeeds

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#24827]
**Version Used**: 
All
**Steps to Reproduce**:
1. Add extra EndOfLine Trivia or Put EndOfLIne Trivia after OperandTokens
2. Call NormalizeWhiteSpace
3. This is specifically for VB but it may apply to all languages

**Desired Behavior**:
The EndOfLine Trivia is preserved
**Actual Behavior**:
All unrequired EndOfLine Trivia are removed

Today I need to call NormalizeWhiteSpace for indenting and adding whitespace around tokens but I want to breakup long lines. I have two choices, don't call NormalizeWhiteSpace and I get the CRLF 's I want but a program what will not compile
```
' Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

ImportsSystem
ImportsSystem.Runtime.InteropServices
NamespaceMicrosoft.CodeAnalysis.UnitTests    PublicClassRealParserTests        '''  <summary>
''' Test some specific floating-point literals that have been shown to be problematic
''' in some implementation.
''' </summary>
<Fact>
PublicSharedSubTestTroublesomeDoubles()
CheckOneDouble("0.6822871999174", &H3FE5D54BF743FD1B)
CheckOneDouble("6.6312368714697582767853966302759672433990999473553031442499717587" &
"362866301392654396180682007880487441059604205526018528897150063763" &
"256665955396033303618005191075917832333584923372080578494993608994" &
...
```
With call NormalizeWhiteSpace all the CRLF's I want are removed
```
' Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
Imports System
Imports System.Runtime.InteropServices
Imports Xunit

Namespace Microsoft.CodeAnalysis.UnitTests

    Public Class RealParserTests

        <Fact>
        Public Shared Sub TestTroublesomeDoubles()
            CheckOneDouble("6.6312368714697582767853966302759672433990999473553031442499717587" & "362866301392654396180682007880487441059604205526018528897150063763" & "256665955396033303618005191075917832333584923372080578494993608994" & "251286407188566165030934449228547591599881603044399098682919739314" & "266256986631577498362522745234853124423586512070512924530832781161" & "439325697279187097860044978723221938561502254152119972830784963194" & "121246401117772161481107528151017752957198119743384519360959074196" & "224175384736794951486324803914359317679811223967034438033355297560" & "033532098300718322306892013830155987921841729099279241763393155074" & "022348361207309147831684007154624400538175927027662135590421159867" & "638194826541287705957668068727833491469671712939495988506756821156" & "96218943412532098591327667236328125E-316", &H8000000)
        End Sub
...
```

**Comment by CyrusNajmabadi** [comment]
Why not Normalize, then do a pass where you put in linefeeds where you want them?

If you want more flexible behavior, why not use the formatting functionality exposed through the workspace layer?

**Comment by paul1956** [comment]
I can't do the first because I am adding the CRLF while visiting node in the tree and don't know I am done or where to call it. I will look into the second option, any pointer would be helpful.

**Comment by CyrusNajmabadi** [comment]
> I can't do the first because I am adding the CRLF while visiting nodes in the tree and don't know I am done 

WHy not just do a post pass once you have your 'near' final tree.  i.e. once you call .NormalizeWhitespace, why not just mutate that resultant tree to add newlines where you want them?

> I will look into the second option, any pointer would be helpful.

https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Formatting/Formatter.cs

This is the API the IDE uses to do all formatting for C# and VB documents.

**Comment by paul1956** [comment]
Maybe I don't understand something. I have a Tree A with EndOfLine Trivia everywhere I want it but few spaces. I have Tree B after calling NormalizeWhiteSpace, it has all the pretty formatting but missing my CRLF's and the leading white space after my CRLF's. Is there a way to match the nodes, add the missing EndOfLine and the correct leading whitespace Trivia producing Tree C? I am adding the CRLF's while translating code and they were in the original source, its not like I am deciding a line was too long and breaking it. If the formatter can  just deal with the blanks and leave the CRLF I will go that way.

**Comment by CyrusNajmabadi** [comment]
>  Is there a way to match the nodes, add the missing EndOfLine and the correct leading whitespace Trivia producing Tree C?

you could always add annotations to the nodes so you could find those same nodes afterwards and then re-add the crlfs back to them.  

Right now you are using NormalizeWhitespace.  One of the core concepts about NormalizeWhitespace is that it normalizes.  Effectively, it takes in all input and produces a totally normalized form.  If you want behavior that is different from that then you should either:

1. not use NormalizeWhitespace.
2. perform your changes *after* NormalizeWhitespace *not* before (since NW will just blow them away).
3. use the formatting api instead.

>  If the formatter can just deal with the blanks and leave the CRLF I will go that way.

It might be able to.  The formatter is what VS itself uses to format your code based on both a set of built in configurable options, as well as optional 'formatting rules' you can supply yourself.  For example, here's how i format code in the 'generate equals' feature so that we get wrapping and alignment of expressions. i.e. when we do a 'generate equals...' you get the following:

![image](https://user-images.githubusercontent.com/4564579/36197694-56cdac38-1129-11e8-9d90-7dfd02f7f8d1.png)

https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/FormatLargeBinaryExpressionRule.cs

**Comment by WillianGruber** [comment]
This is already closed but considering that I landed here years after this issue when searching for Preserve LineFeeds in NormalizeWhiteSpace and considering it will not be supported, I would like to share the code that I used to get around this:

(this is part of my code)

Create this property:
```
protected static string LineFeedPlaceholder => "//LineFeedPlaceholder";
```

Use it as a placeholder when generating the code. It will be a comment, as in:
```
...GenerateCode()...
StringBuilder code = new StringBuilder();
...
code.AppendLine(LineFeedPlaceholder);
...
```

Generate the code as follows:
```
string code = GenerateCode();
SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(code);
code = syntaxTree.GetRoot().NormalizeWhitespace().ToFullString();
code = Regex.Replace(code, "\\s*\\/\\/LineFeedPlaceholder", "\r\n");
```
