### ISSUE TITLE
Consider removing SessionWithSolution so that we can make connection truely stateless

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#24836]
right now, we have this
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Remote/RemoteHostSessionHelpers.cs,376af83bf115084c

that has 
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Remote/RemoteHostClient.cs,110

just to remove Solution from each call. not sure whether that's worth it since it just makes things complex since connection becomes stateful.

we might consider just remove that one and make all call to give the solution in and make connection stateless.

**Comment by heejaechang** [comment]
also, when we do, consider renaming KeepAliveSession to StatefulSession

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/40735
