### ISSUE TITLE
Typing does not produce any out of BMP characters during rename session

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#24844]
**Version Used**: 15.6 Preview 5 / 2.7.0.62608

**Steps to Reproduce**:

1. Enable Gothic input language
2. Create a new console application.
3. Enter renaming session, e.g. press F2 to rename the Program class name.
4. Type using the Gothic keyboard.

**Expected Behavior**: Typing renames the class.

**Actual Behavior**: Nothing happening.

Might be related to #24845

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback on this.
