### ISSUE TITLE
Flaky Test - TestRegionCompletionCommitFormatting

### ISSUE THREAD

**Issue by TIHan** [dotnet/roslyn#24846]
```Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests_Projections.TestRegionCompletionCommitFormatting [FAIL]```

Projections.TestRegionCompletionCommitFormatting is skipped because it is flaky.

**Comment by ivanbasov** [comment]
retiring old completion now
