### ISSUE TITLE
Unexpected overload used for completion in incomplete code

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#24841]
**Version Used**:  15.5.5

**Steps to Reproduce**:

write this class

    public class Test<TKey, TValue>
    {
        public void AddOrUpdate(TKey key, TValue value, Func<(TKey key, TValue newValue, TValue oldValue), TValue> updateFunction)
        {
        }

        public void AddOrUpdate(TKey key, Func<TKey, TValue> addFunction, Func<(TKey key, TValue oldValue), TValue> updateFunction)
        {
        }

        public void AddOrUpdate<TArg>(TKey key, TArg arg, Func<(TKey key, TArg arg), TValue> addFunction, Func<(TKey key, TArg arg, TValue oldValue), TValue> updateFunction)
        {
        }
    }

then write this code snippet for test

    new Test<int, int>().AddOrUpdate(key: 0, new object(), t => t.); // see suggestions for "t."

**Expected Behavior**:

I expect to get suggestions `key` and `arg` when typing `t.`, because `object` is not assignable to `int` so first overload and second overload are really out of list and intellisense should already know that.

**Actual Behavior**:

I get suggestions `key`, `oldValue` and `newValue`. if I remove first overload I still get `key` and `oldValue`.

Only if I use named parameter `arg:` then I get correct suggestions.

    new Test<int, int>().AddOrUpdate(key: 0, arg: new object(), t => t.); // correct suggestions.

**Comment by jcouv** [comment]
Tagging @gafter for advisement

**Comment by CyrusNajmabadi** [comment]
I see the expected items:

![image](https://user-images.githubusercontent.com/4564579/198753774-8fa12679-1859-4a2e-82a1-da0b71c96e41.png)
