### ISSUE TITLE
Introduce Local: multiple unnecessary casts generated and also not grayed out

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#24853]
This came up while working on Roslyn test `RefReadOnlyIsWrittenToMetadata_SameAssembly_Method` in PR https://github.com/dotnet/roslyn/pull/24492

Select `((PEModuleSymbol)module)` and invoke "Introduce Local" for all occurrences. The generated code is peppered with unnecessary casts.

![image](https://user-images.githubusercontent.com/12466233/36233488-2d56c87c-119b-11e8-8bfa-efc31eaf2134.png)

![image](https://user-images.githubusercontent.com/12466233/36233519-4ffa1f5a-119b-11e8-8a65-3425fbeb5295.png)

Other simplifications were not made either:
![image](https://user-images.githubusercontent.com/12466233/36233717-276e5c08-119c-11e8-82d5-bdf86061b085.png)

Note: I've run into a similar [issue ](https://github.com/dotnet/roslyn/issues/24791) (unnecessary cast not simplified, when invoking "Inline Temp") a couple of days ago. I hope there is not a more systematic issue here. I haven't had this problem before.
Tagging @jinujoseph FYI

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/issues/7877

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/76218
