### ISSUE TITLE
Ctrl+Alt+Click for Go To Implementation

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#24856]
Several developers have asked us to extend Ctrl+Click for Go To Definition to work for Go To Implementation. They are expecting "Ctrl+Alt+Click" to take them to Implementations.

> Note: if we are considering inlining GoToImpl results (rather than bringing a search result window), these two features would pair well together to round off the feature.

**Comment by CyrusNajmabadi** [comment]
> Note: if we are considering inlining GoToImpl results

What does it mean to "inline" the result? Does that mean "use the peek window"?

**Comment by sharwell** [comment]
:bulb: If this gets implemented, we should account for #25304 in the design.

**Comment by CyrusNajmabadi** [comment]
@jinujoseph Should likely be moved into azdo.  This wouldn't be a roslyn thing.  It would be the editor/platform exposing this functionality and mapping to the existing commands.

**Comment by jinujoseph** [comment]
@olegtk  do we have anything tracking this already on our end ?

**Comment by olegtk** [comment]
not really. I added it to the Editor's backlog (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1550921), but it really needs some PM work to flesh out the idea.

**Comment by CyrusNajmabadi** [comment]
Thanks!
