### ISSUE TITLE
Completion after using keyword should be in suggestion mode

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#24868]
If I type using, completion comes up with a list of namespaces. However, it's in completion mode. If I try to type an alias (e.g. using BF = System.Reflection.BindingFlags) it interferes with me typing the alias. It should be in suggestion mode.

**Comment by CyrusNajmabadi** [comment]
it is.  But ```<space>``` should not complete the item.  so if you type "using BF =" it should to the right thing.

**Comment by mkrueger** [comment]
I need to investigate that - seems we've a bug on our side.

However VS.NET suffers a bit from that as well:

type
using en<space>

it ends up as 

using enum

Howver typing using sy =  works it's not completed as using system. In VS4Mac it currently ends up as 'using system' so it's something we need to fix on our side. However the original bug is still an issue in some cases.

**Comment by CyrusNajmabadi** [comment]
Yup.  This ties into how roslyn completion items can individually customize the 'commit' characters.  Not sure if this data is contained in the info sent over to VS4mac.

**Comment by mkrueger** [comment]
y sure - but it doesn't work for all items in vs.net in that case - "en"<space> should not complete to 'enum' -but it does.

**Comment by CyrusNajmabadi** [comment]
Yup.  Looks like a bug with the snippet-provider.  It needs to adopt this logic as well.
