### ISSUE TITLE
Accept License Terms?

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#24872]
Is there an approved set of license terms that have to be accepted? Before the user can install a roslyn derived compiler VSIX? That is one that is non-official release, or still experimental.

So the we (Microsoft and releasee) can't accept liability for any loses from using it.

**Comment by gafter** [comment]
The code is licensed under the [Apache 2.0 license](https://github.com/dotnet/roslyn/blob/master/License.txt). "Installing" is a kind of copying that would not be permitted unless the recipient is relying on the terms of the license.
