### ISSUE TITLE
take advantage of Trackspan of ITextImage that are used as underlying implementation of SnapshotSourceText

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#24875]
currently, in a lot of places, we move back and forth between roslyn SourceText to Editor ITextSnapshot just to move some span around between snapshots.

if we make SourceText to be able to do so (even for internal only), we probably can remove many places where we need to find Editor ITextSnapshot from SourceText.

**Comment by heejaechang** [comment]
related to this - https://github.com/dotnet/roslyn/pull/24849

**Comment by CyrusNajmabadi** [comment]
Closing out.  Haven't seen a need for this.
