### ISSUE TITLE
Run .Ruleset files using .build files+vs2017

### ISSUE THREAD

**Issue by prasad12k** [dotnet/roslyn#24871]
# Run .Ruleset files using .build files
How to use code analysis in vs2017 to create .ruleset file.Have to create manually or any tool available.
How to create .ruleset file having  .net libraries  (custom rulesets) and include ruleset file in .build file.
Build the solution in command prompt (Vs2017)
we have support to run rulseet files using .build files ?
or 
Any tools to run ruleset file while building the solution.

**Comment by mavasani** [comment]
@prasad12k Kindly refer to https://github.com/dotnet/roslyn/blob/master/docs/compilers/Rule%20Set%20Format.md and https://docs.microsoft.com/en-us/visualstudio/code-quality/using-rule-sets-to-group-code-analysis-rules?view=vs-2019. Kindly open a documentation issue on the latter if this is still not helpful documentation for your use cases.
