### ISSUE TITLE
Find All References should give a better message when not invoked on a symbol

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#24886]
I thought FAR was broken every 1 out of 10 searches because it stated:

![image](https://user-images.githubusercontent.com/1103906/36295075-1dd7750a-1339-11e8-9aa0-71d7cd1a1ef8.png)

Turns out, 1 out of 10 searches I miss the symbol and do a FAR on whitespace, and it shows the above.

Other commands give a better indication that haven't chosen a symbol, FAR should do the same thing.

**Comment by sharwell** [comment]
@kuhlenh for design input
