### ISSUE TITLE
Compiler ignore `new` keyword for properties

### ISSUE THREAD

**Issue by SteamUpdate** [dotnet/roslyn#24887]
**Version Used**: 
All libs are 2.6.0.0:
Microsoft.CodeAnalysis
Microsoft.CodeAnalysis.CSharp
Microsoft.CodeAnalysis.CSharp.Workspaces

**Steps to Reproduce**:

1. Write some code, for example:
```
    public class TestClassBase
    {
        public string Test { get; set; }
    }

    public class TestChildClass : TestClassBase
    {
        public new double Test
        {
            get { return 35;}
            set { base.Test = value.ToString(); }
        }
    }
```
2. Compile this code with Roslyn:
```
            var references = new List<MetadataReference>();
            var allAssemblies = AppDomain.CurrentDomain.GetAssemblies();
            foreach (var asm in allAssemblies)
            {
                if (asm.IsDynamic) continue;
                references.Add(MetadataReference.CreateFromFile(asm.Location));
            }

            var text = File.ReadAllText("E:\\Test\\Test\\Class1.cs");
            var tree = CSharpSyntaxTree.ParseText(text);

            var options = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary,  optimizationLevel: OptimizationLevel.Release, assemblyIdentityComparer: AssemblyIdentityComparer.Default);
            var compilation = CSharpCompilation.Create("Test.dll", new[] { tree }, references, options);
            using (var file = new FileStream("E:\\Test.dll", FileMode.Create))
            {
                EmitResult result = compilation.Emit(file);
                Console.WriteLine(result.Success);
            }
```
`result.Success` return `true`
3. Decompilate `Test.dll` (I use dotPeek)

**Expected Behavior**:
I want to see this code:
```
namespace Test
{
  public class TestClassBase
  {
    public string Test { get; set; }
  }
  
  public class TestChildClass : TestClassBase
  {
    public new double Test
    {
      get
      {
        return 35.0;
      }
      set
      {
        base.Test = value.ToString();
      }
    }
  }
}
```
**Actual Behavior**:
But i see this:
```
namespace Test
{
  public class TestClassBase
  {
    public string Test { get; set; }
  }
  
  public class TestChildClass : TestClassBase
  {
    public double Test
    {
      get
      {
        return 35.0;
      }
      set
      {
        this.Test = value.ToString();
      }
    }
  }
}
```
As u see, `Test` property in `TestChildClass` generated without `new` keyword, and in `set` replace `base` on `this`. 

Problems with `this.Test = value.ToString();`:
1. This is compilation error
2. This is recursive call

Besides, I add `Test.dll` in my console application. When i tried to start it, i get a *System.IO.FileNotFoundException: Could not load file or assembly "Test.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"*

**Comment by HaloFour** [comment]
Sounds like a problem with dotPeek and the source that it generates from IL.  IIRC the `new` keyword doesn't generate anything in IL, it just allows for the developer to be explicit with their shadowing.  The IL would be identical in both cases.

**Comment by sharwell** [comment]
@HaloFour hit the nail on the head here 👍

**Comment by HaloFour** [comment]
The `this.Test` recursion issue would also be a bug in dotPeek.  The compiler emits the appropriate IL:

```
call instance void TestClassBase::set_Test(string)
```

As for the `FileNotFoundException`, it's hard to gauge the cause of that but I would suggest that the assembly that you're generating is not in the probing paths for this console application.

**Comment by SteamUpdate** [comment]
@HaloFour yea, you was right, it's really bug of dotPeek. I use ILSpy for decompilation this dll and see correct code. But bug of dotPeek reproduced only with assembly witch compiled with code from first comment.
If I write same code in Visual Studio (2013\2015\2017) and build it, decompilation with dotPeek display a corrent code.
Build with dotnet.exe and next decompilation returns same result.

As for the `FileNotFoundException`, I found a mistake and fix it
