### ISSUE TITLE
Latest Microsoft.CodeAnalysis nupkg still contains version 1.1.0 of Microsoft.CodeAnalysis.Analyzers

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#24899]
**Version Used**: 2.6.1

**Steps to Reproduce**:

1. Install Microsoft.CodeAnalysis version 2.6.1 as a NuGet package reference to a C# console app
2. Check the version of Microsoft.CodeAnalysis.Analyzers that comes along with the package

OR
1. Create a new Analyzer with Code Fix project
2. Upgrade the Microsoft.CodeAnalysis.CSharp.Workspaces NuGet reference to 2.6.1
3. Check the version of Microsoft.CodeAnalysis.Analyzers that comes along with the package

**Expected Behavior**:
Latest stable version 2.6.0 of Microsoft.CodeAnalysis.Analyzers (https://www.nuget.org/packages/Microsoft.CodeAnalysis.Analyzers/2.6.0) built on top of Microsoft.CodeAnalysis 2.6.0

**Actual Behavior**:
Version 1.1.0 of Microsoft.CodeAnalysis.Analyzers

**Comment by mavasani** [comment]
@jasonmalinowski @jinujoseph @dotnet/roslyn-infrastructure I can fix this if someone can point me to the location of the nuspec where we configure this.

**Comment by svick** [comment]
`Microsoft.CodeAnalysis.Analyzers` is a direct dependency of `Microsoft.CodeAnalysis.Common` (which is a direct or indirect dependency of other Roslyn packages, including `Microsoft.CodeAnalysis`).

So I think the relevant nuspec line is:

https://github.com/dotnet/roslyn/blob/3678d5345745f1853607afedbf0efcbaec04aaac/src/NuGet/Microsoft.CodeAnalysis.Common.nuspec#L18

And the line to fix then would be:

https://github.com/dotnet/roslyn/blob/3678d5345745f1853607afedbf0efcbaec04aaac/build/Targets/Packages.props#L28

**Comment by jmarolf** [comment]
@mavasani We can configure https://github.com/dotnet/roslyn-sdk to install the newest roslyn analyzer packages.

**Comment by RipPer56** [comment]
Can i get the usage of this package, because i get no probem even if delete it from csproj.

**Comment by mavasani** [comment]
@jmarolf I think we also want to update the version dependency in Microsoft.CodeAnalysis.nupkg.

**Comment by jmarolf** [comment]
2.6 the correct version for 2.9?

**Comment by mavasani** [comment]
Actually we need 2.6.1 (not yet produced) as we need Dustin’s latest MSBuild analyzer. I will generate the package on Tuesday.
