### ISSUE TITLE
Convert var to explicit type name.

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#24896]
light bulb to convert `var` to explicit type name and vice versa would be useful. (similar in resharper)

**Comment by Joe4evr** [comment]
This already exists if you configure your Code Style to "Prefer explicit type".
![](https://i.imgur.com/0JNZefW.png)
![](https://i.imgur.com/psQZ9WU.png)

**Comment by MkazemAkhgary** [comment]
Oh, I see. thanks for sharing it.

**Comment by MkazemAkhgary** [comment]
@Joe4evr It was good if it was available as lightbulb. because I only prefer to do this in some cases not always. putting it in suggestion mode is better than error :)

Although I can hide suggestions by clicking on suggestion in "error list" view.

**Comment by CyrusNajmabadi** [comment]
In general we do this as a pair of features.  A CodeFix for when your code doesn't fit your specified coding style, and a CodeRefactoring to still allow you to go in the other-direction when that suits you.  We do that, for example, with "use expression body":

![image](https://user-images.githubusercontent.com/4564579/36303149-f6c37adc-12bf-11e8-8a27-e86b63223715.png)

![image](https://user-images.githubusercontent.com/4564579/36303159-fff1d180-12bf-11e8-855c-61e5163dab74.png)

It would make sense to do the same thing here.  A fix to take you in the direction of your style, and a refactoring to allow you to go in the other direction if that's what you want.

**Comment by Joe4evr** [comment]
> I only prefer to do this in some cases not always

That's why there are 3 separate options to configure your style just how you like it.
> It was good if it was available as lightbulb

~~Setting the severity to anything higher than `None` should make it an option in the light bulb.~~
Actually, I can't seem to get even get the diagnostic to come up if it's not on `Error`. @CyrusNajmabadi Bug report?

**Comment by jcouv** [comment]
@CyrusNajmabadi @sharwell Would it make sense for the analyzer to produce a hidden diagnostic (to trigger the fixer) in such case, or would that be too much of a performance risk?

**Comment by jcouv** [comment]
One general issue with creating a refactoring in addition to the existing analyzer/fixer is that two actions could be offered (one from the refactoring, and one from the fixer). 
It would be great to have a general mechanism to avoid that, or even better to avoid having a separate refactoring...

**Comment by jcouv** [comment]
Made a PR for extending the existing analyzers/fixers to give hidden diagnostics (https://github.com/dotnet/roslyn/pull/25204), but that has some downsides in FixAll scenario.
I also have a [prototype](https://github.com/jcouv/roslyn/commit/20888a4ea7f79d45270c2769736087a1a34d24da) for refactoring approach, but that also has a downside as it can offer a redundant action (when UseImplicitType/UseExplicitType analyzer produced a diagnostic).

**Comment by CyrusNajmabadi** [comment]
> I also have a prototype for refactoring approach, but that also has a downside as it can offer a redundant action (when UseImplicitType/UseExplicitType analyzer produced a diagnostic).

This is the way to go . HOwever, the refactoring should be written to say: "i should not be available if the analyzer would produce a result here".

This is how "use expression/block body" works.  It's an analyzer/refactoring duo.  And the refactoring is only offered if the analyzer is not already offering the same thing.

**Comment by jcouv** [comment]
Cool. I have a PR for this refactoring (https://github.com/dotnet/roslyn/pull/25208). I used a similar design to the UseExpressionBody refactoring, so it avoids producing redundant actions :-)

**Comment by jcouv** [comment]
Merged the fix. It should make it into 15.7 preview 3.
