### ISSUE TITLE
Extract Method with Local Function

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24906]
I selected some code that contained a local function to extract the method.

It created the method without arguments.

For example...

string user = &quot;Mark&quot;;

// Start swipe

&lt;A block with some statements using user&gt;

&lt;A local void function, also with arguments, called from the block above&gt;

// End swipe

Created...

NewMethod() instead of

NewMethod(user)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/196410/extract-method-with-local-function.html
VSTS ticketId: 565295_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as extensive work was done to properly allow extraction of local function (including into other local functions).
