### ISSUE TITLE
Allow collapsing of large, multi-line string literals.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#24919]
Title is self explanatory :)  I have some large constant strings in my file.  It's unfortunate i can't collapse them like any other large construct.

Tnx!

**Comment by JohanLarsson** [comment]
This would be a very nice feature.

**Comment by alrz** [comment]
@CyrusNajmabadi would this be a editor feature or could it be done in roslyn? if so, could you give a hint on required change?

**Comment by CyrusNajmabadi** [comment]
@alrz It would be a pure Roslyn feature.  Look at AbstractSyntaxStructureProvider and its subclasses.  Thanks!
