### ISSUE TITLE
Find and Replace to overwrite previous value of "Look at these file types"

### ISSUE THREAD

**Issue by kasper3** [dotnet/roslyn#24912]
This is a bug from last decade, since VS 2010 days https://stackoverflow.com/questions/9504728/vs2010-look-at-these-file-types-option-keeps-resetting-to-previous-value

* Open an SLN in VS
* Find and Replace (Shift+Ctrl+F)
* Type in key to search
* In `Look at these file types` under `Find Options`, enter *.xml

Hit enter to get results. Close VS and open it again.
Next time when you Find All, `*.xml` will still be there. Clear it out and search. Close VS and open it again.
From this point on, you will always get `*.xml` in that box, unless you clear it from registry.

Either not many people at Microsoft use this option or nobody told the guys responsible for that code.
Either way, it will be good to have it fixed someday. Maybe the fix is to not store that value in registry and instead use some modern way of saving / overwriting it.

**Comment by CyrusNajmabadi** [comment]
@olegtk Can you route this appropriately to the editor?

**Comment by olegtk** [comment]
The trick is to clear it with ```*.*``` instead :) @jinujoseph please route this to the editor.

**Comment by jinujoseph** [comment]
routed to editor [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/571078)
