### ISSUE TITLE
MSBuildWorkspace.OpenProjectAsync cannot resolve $(Configuration) correctly

### ISSUE THREAD

**Issue by nehmebilal** [dotnet/roslyn#24923]
**Version Used**: 2.6.1

**Steps to Reproduce**:

1. Use `MSBuildWorkspace.OpenProjectAsync` to open a ProjectA that references a ProjectB dll using a hint path as follows:
```xml
    <Reference Include="ProjectB">
      <HintPath>..\ProjectB\bin\$(Configuration)\ProjectB.dll</HintPath>
    </Reference>
```
2. Make sure to build in Release **only**.

**Expected Behavior**:
The types in ProjectB to load correctly.

**Actual Behavior**:
The types in ProjectB are unavailable.

Replacing `$(Configuration)` with `Release` fixes the issue, which shows that `MSBuildWorkspace` is replacing `$(Configuration)` with `Debug` instead of `Release`.

**Comment by jcouv** [comment]
@jinujoseph Does IDE team or project-system team own `MSBuildWorkspace`?

**Comment by jinujoseph** [comment]
IDE team owns it .
cc @DustinCampbell

**Comment by DustinCampbell** [comment]
@nehmebilal: Could you provide the full project? Most projects created with Visual Studio contain the following line:

```XML
<Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
```

So, if `Configuration` isn't specified, it gets set to `Debug` by MSBuild. You can control the set of properties used by `MSBuildWorkspace` by specifying them in the `Create(...)` method. For example:

```C#
using (var workspace = MSBuildWorkspace.Create(new Dictionary<string, string> { {"Configuration", "Release"}})
{
    var project = workspace.OpenProjectAsync(pathToProject");
}
```

Does that help?

**Comment by nehmebilal** [comment]
Yes! That makes sense and should fix the issue, thanks.

**Comment by DustinCampbell** [comment]
Glad to hear it. Let me know if you have any trouble.
