### ISSUE TITLE
Strange IOperation tree for single-statement lambda.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#24938]
I've got the following lambda:

```c#
Action a = () => {
            Console.WriteLine();
        };
```

The IOperation tree here is not quite what i expected. Specifically, the IAnonymousFunctionOperation has a body with *two* operations in it.  One operation is the ExpxressionStatement corresponding to Console.WriteLine();.  The second is an Implicit ReturnStatement.  

is that expected?  Seems very strange to me that there's any sort of return statement placed here for this lambda.  

Thanks!

**Comment by CyrusNajmabadi** [comment]
Tagging @333fred

**Comment by gafter** [comment]
The lambda does _implicitly_ return to the caller at the end, because that's the way the language works. I'll bet the return statement says that it was implicit?

**Comment by CyrusNajmabadi** [comment]
>  The second is an Implicit ReturnStatement.

:)

**Comment by 333fred** [comment]
@CyrusNajmabadi while I don't believe we've documented it anywhere, this is consistent across all different forms of lambdas (C# & VB single and multiline). I do agree that it seems a little weird (we don't have implicit returns for void functions in C# after all), but it is correct. We could probably add a remark to the IAnonymousFunctionOperation API that says that in non-dataflow contexts, there will always be an implicit return for void lambdas.

**Comment by CyrusNajmabadi** [comment]
> We could probably add a remark to the IAnonymousFunctionOperation API that says that in non-dataflow contexts, there will always be an implicit return for void lambdas.

**Comment by 333fred** [comment]
In a recent design meeting, we decided that in dataflow contexts, we'd replace anonymous function nodes with something similar to `ICFGAnonymousFunctionOperation`, which is a container for another CFG.

**Comment by bkoelman** [comment]
https://github.com/dotnet/roslyn/issues/27208#issuecomment-397373041

> There are some cases where there are inconsistencies, like the lambda case you pointed out. But I don't think that's an argument for hiding implicit nodes; rather, I think it's an argument for fixing inconsistencies.

@333fred This tracks the issue I was referring to. 

Though I prefer to see this fixed, at the very least this behavior should be documented at https://github.com/dotnet/roslyn/blob/19f49b0f4a0d887547195ec06f9eb6b2e0f21228/src/Compilers/Core/Portable/Operations/IAnonymousFunctionOperation.cs.

Can we have it reopened please?

**Comment by 333fred** [comment]
Yes, we at least need to document this behavior. The question of what "fixed" means in this case is questionable, because as @gafter pointed out, this is how the language works.

**Comment by jinujoseph** [comment]
we don't think we should be documenting the exact shape of the tree , as long as the shape is reasonable we should be good . other languages may represent it differently.
