### ISSUE TITLE
[Suggestion] Better project template search in the new project dialog for term "analyzer"?

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2493]
1. File -> New Project -> Download the .NET compiler platform SDK -> Download the SDK and close VS.

2. Start new instance of VS -> File -> New Project 

3. Search "fix" in the search dialog => Search results return both the "Diagnostic with Code Fix" templates and "Download the .NET Compiler Platform SDK" template.

4. Search "analyzer" in the search dialog => Only "Download the .NET Compiler Platform SDK" templates show up, causing one to probably think that download SDK as part of step 1 failed.

5. Search "diagnostic" in the search dialog => Only "Diagnostic with Code Fix" templates show up.

Expected: It might be good to show both these templates for both search terms: "analyzer" and "diagnostic" to remove any confusion for the end user. I presume it should be a trivial fix to change?

**Comment by jmarolf** [comment]
Fixed with internal Changeset 1471973
