### ISSUE TITLE
Question about Building on Windows

### ISSUE THREAD

**Issue by pieandcakes** [dotnet/roslyn#24949]
In reading https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md, should I be able to, on Windows, do just `enlist`, `restore`, `build` or do I need to install Visual Studio and the other dependencies? My goal is to just do command line build of Roslyn

**Comment by jcouv** [comment]
Yes. You should be able to enlist, restore and build without Visual Studio installed.

Re-open the issue and let me know if that doesn't work for any reason. 
I'll close the issue as answered in the meanwhile.

**Comment by pieandcakes** [comment]
@jcouv I don't know if this was the same for a dev15.6 branch but that's what I did and I'm getting errors that it is missing System libraries. I ended up installing VS and the SDKs and such to get it to work. 

I'll set up a machine and see if I can get you the actual errors. This was on a clean Win 10 machine with nothing else installed.
