### ISSUE TITLE
Proposal: Add new filters to the IntelliSense members list

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#24944]
IntelliSense allow to filter the members list by choosing to view or hide fields, properties, methods, and events.
These filters are not enough. I suggest to add more filters:
-	Inherited: to show or hide inherited members.. It's useful specially with controls and custom controls, where the number of inherited members are huge.
-	Protected: to show or hide inherited members.. It's useful specially inside the form or custom controls blocks, where protected members appear.
- Exceptions: to show or hide Exception classes from the list.
- Atributes: to show or hide Atribute classs from the list.
- EventArgs: to show or hide EventArgs classs from the list.
- Enums: to show or hide Enums from the list.

**Comment by MohammadHamdyGhanem** [comment]
I need some more filters to filter out Exception, Atribute and EventArgs classs from the list.

**Comment by CyrusNajmabadi** [comment]
Do you want to filter *down to* those items, or do you want to filter those items *out* (i.e. so they are nto shown)?

**Comment by MohammadHamdyGhanem** [comment]
Toggle buttons like the existed ones will allow us to choose to show or hide these items.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
