### ISSUE TITLE
Roslyn compiler is copied to root directory

### ISSUE THREAD

**Issue by wpsmmb** [dotnet/roslyn#24940]
**Version Used**: 
1.0.6, 1.0.7, 1.0.8

**Steps to Reproduce**:
Use the compiler in a non ASP.NET project to compile dynamic assemblies as follow:
```
string classSource = "// some source"; 

CompilerParameters options = new CompilerParameters {
	GenerateExecutable = false,
	GenerateInMemory = true,
	IncludeDebugInformation = true,
	CompilerOptions = "/define:DEBUG"
};

CodeDomProvider provider = new CSharpCodeProvider();
CompilerResults result = provider.CompileAssemblyFromSource(options, classSource);
```

**Expected Behavior**:
Roslyn files will be located in subfolder of the project.

**Actual Behavior**:
The compiler is copied to 'C:\bin\roslyn' or if the solution is located on drive D the files are copied to 'D:\bin\roslyn'.

**Comment by wpsmmb** [comment]
@jcouv Here you can find a sample project (VS 2017 - 15.5.7, .NET 4.5.1) 
https://github.com/wpsmmb/RoslynIssue24940

**Comment by wpsmmb** [comment]
Same with target framework .NET 4.7.1 and Microsoft.Net.Compilers v2.6.1

**Comment by jaredpar** [comment]
This looks to be a bug in the RoslynCodeDomProvider package. That lives in the following repository

https://github.com/aspnet/RoslynCodeDomProvider

Can you file the bug with that team?
