### ISSUE TITLE
Avoid using the same text for refactorings and code fixes

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#24946]
Multiple users have mentioned that it's confusing when refactorings and fixes for diagnostics have the same wording. In several cases, the refactorings go the opposite way of the preferred code style (e.g. if the preferred style is expression-bodied, we still offer a one-off refactoring to use block-bodied). The refactoring wording is "Use block body for methods", which is the same wording as you see if the code style prefers block bodies. @jnm2 writes:

> 'Use block body' would honestly beat 'Use block body for method' (singular) IMO.

I understand the sentiment, and think the proposed wording change may be applicable for refactorings - especially in the lack of pluralization. Refactorings don't offer a Fix All so the plural form wouldn't be needed.

/cc @Neme12 @CyrusNajmabadi @jnm2

**Comment by kuhlenh** [comment]
Agreed. We're going to start making a lot more of these "toggles" (e.g., https://github.com/dotnet/roslyn/issues/24227) and the diction will help differentiate.

**Comment by CyrusNajmabadi** [comment]
Closing out.  If we want to do this, then we can just do it with an assigned milestone.
