### ISSUE TITLE
Proposal: Add local functions names to the navigation list

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#24943]
Proposal: Add local functions names to the navigation list
If there is a local function defined as this:
```
void foo1()
{
    void foo2()
    {
    }
}

```
it can appear in the code editor's upper navigation list with the name foo1.foo2
If the local function foo2 is defined inside the constructor of a class Class1, then it should appear with the name Class1.foo2
If it's defined inside the setter or the getter of a property named Property1, then  it should appear with the names Property1.Set.foo2, or Property1.Get.foo2

**Comment by CyrusNajmabadi** [comment]
Not planning on doing this.
