### ISSUE TITLE
CA1822: Mark Member as static does not provide a code fix

### ISSUE THREAD

**Issue by smitpatel** [dotnet/roslyn#24958]
**Version Used**: 
```
Visual Studio 15.6.0 Preview 6.0 [27419.1.d15.6]
PM> dotnet --info
.NET Command Line Tools (2.1.100-preview-007363)

Product Information:
 Version:            2.1.100-preview-007363
 Commit SHA-1 hash:  0468da6ada

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.100-preview-007363\

Microsoft .NET Core Shared Framework Host
  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```
**Steps to Reproduce**:

.NET Core Console App in Visual studio
```C#
using System;

namespace StaticSuggestion
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }

        public int Sum(int a, int b)
        {
            return a + b;
        }
    }
}
```
VS suggests that Method Sum can be made static but there is no associated codefix for it. Change signature dialogue box does not give option to add static either.
![image](https://user-images.githubusercontent.com/1528107/36454329-41d1d300-1650-11e8-8cd8-d1ba658d508f.png)
![image](https://user-images.githubusercontent.com/1528107/36454340-4dbabb50-1650-11e8-86e3-4e9597950e24.png)

**Expected Behavior**:
Code-fix to add static modifier to the method.
**Actual Behavior**:
Manually have to type static.

**Comment by mavasani** [comment]
CA1822 is a diagnostic in Microsoft.CodeAnalysis.FxCopAnalyzers NuGet package, and the latest version (2.6.3) does have a code fix for it.
