### ISSUE TITLE
Type parameters named T should have "T in classname<T>" tooltip in Intellisense completion list

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#24960]
**Version Used**: 2.6.0.62329 (VS 15.5.6), 2.7.0.62608 (VS 15.6 Preview 5)

**Steps to Reproduce**:

1. Copy the class definition below into a C# source file.
2. Invoke Intellisense completion at the two marked locations.

```c#
class TestClass<T, T2>
{
    T$$ a;
    T2$$ b;
}
```

**Expected Behavior**:
About one second after invoking Intellisense, a tooltip reading "T in TestClass<T, T2>" (or "T2 in TestClass<T, T2>", respectively) should appear next to the list entry.

**Actual Behavior**:
A tooltip will appear next to the entry for T, but it won't have any text, while the tooltip for T2 (or any other type parameter not named "T") will appear as expected.

**Comment by ivanbasov** [comment]
closed with https://github.com/dotnet/roslyn/pull/36522
