### ISSUE TITLE
Arrays of tuples don't work with `is`

### ISSUE THREAD

**Issue by lcsondes** [dotnet/roslyn#24975]
I was directed here from https://github.com/dotnet/csharplang/issues/1334

**Version Used**: 

VBCSCompiler.exe is 2.6.0.62329, not sure if that's the version you're interested in

**Steps to Reproduce**:

Compile this:

    using System;
    class A
    {
        void Test()
        {
            (object, object)[] a = new (object, object)[1]; // This line has no errors
            var b = a as (object, object)[]; // No errors
            if (a is (object, object)[]) // CS1525: Invalid expression term 'object', CS0443: Syntax error; value expected
            {
                Console.WriteLine("Hello");
            }
            if (a is (object, object)[] c) // CS1525: Invalid expression term 'object', CS0443: Syntax error; value expected
            {
                Console.WriteLine("World");
            }
        }
    }

**Expected Behavior**:
Successful compilation

**Actual Behavior**:
See embedded comments and also https://github.com/dotnet/csharplang/issues/1334

**Comment by jcouv** [comment]
I think this is currently by-design (tuple types are not allowed in pattern matching).
I'll let @gafter confirm and elaborate on plans.

**Comment by lcsondes** [comment]
@svick noticed on the other issue that this is not itself a tuple, but a type that contains a tuple. `a is List<(object, object)>` compiles.

**Comment by alrz** [comment]
true. `new (int, int)[]{}` also compiles, whereas `new (int,int)` doesn't.

**Comment by jcouv** [comment]
@alrz That last example (`new (int, int)()`) is by-design. The language provides a specific way of instantiating tuple types.
Here are the LDM notes on such instantiation (not much details, but makes the decision explicit): https://github.com/dotnet/csharplang/blob/master/meetings/2016/LDM-2016-10-18.md#use-of-tuples-in-new

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/26088
