### ISSUE TITLE
Expressions validation could be wrong

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn#24973]
I think it will be closed as by design, but I just want to rise this issue here.

Looks like compiler use the same validation logic in Expression code as in regular code which could lead to situations where it produce warnings, which are valid in C# in general but wrong for specific Expression query provider.

Let's use following example:
```cs
source.Where(record => (int?)record.LeftJoinReference.Int32Field == null);
```
For IEnumerable<T> source it is completely valid to generate 
```
Warning	CS0472	The result of the expression is always 'true' since a value of type 'int' is never equal to 'null' of type 'int?'	
```
But when source is a IQueryable<T>, code like that could make sense. In this case LeftJoinReference converted to left join SQL, which makes all it's fields implicitely nullable, which makes comparison to null completely valid.

This specific case could be solved if null coalesce operator will be allowed in expressions (https://github.com/dotnet/csharplang/issues/158), but it will not solve general issue with compiler assume that query providers use C# logic when translate expressions.

Right now I can see only one solution here - disable some validations for expression code (e.g. with compiler flag).

**Comment by jcouv** [comment]
I'll let @VSadov comment.

**Comment by MaceWindu** [comment]
Well, after giving it some thoughts, I think it is not a big issue, as you can always add some no-op (for query builder) wrappers, which will make compiler calm down. So you can close it if you don't plan any changes in this area.

**Comment by jaredpar** [comment]
This behavior is "By Design". The compiler does the same analysis for code inside and outside expression trees. True different providers could make different usage of it but taken broadly that approach would cause us to silence pretty much every warning.
