### ISSUE TITLE
Testplan for stackalloc initializers

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#24983]
I have added a testplan for stackalloc initializers.

Normally we would just create an issue with checkboxes, but I think issues are not all-editable, while docs can be changed in PRs.

Let me know if there is a better way.

The doc is - https://github.com/dotnet/roslyn/blob/features/stackalloc-init/docs/compilers/CSharp/testplans/stackalloc_initializers.md

**Comment by VSadov** [comment]
FYI:@jcouv, @alrz

**Comment by gafter** [comment]
> Let me know if there is a better way.

A better way is to have the test plan issue be created, initially, by the external developer who you would like to be able to edit it. Then that person and the compiler team can all edit it.

**Comment by alrz** [comment]
Agreed. maintaining an md file in the feature branch could be cumbersome. I'll go ahead and move `stackalloc_initializers.md` content to a new issue. (then we can close #24699 and #24983 to track all this in one place)

**Comment by VSadov** [comment]
Sounds good! 👍

**Comment by VSadov** [comment]
I think we can close this now once #25160 exists. 
editing doc via PRs seems tedious.

I was worried that issue is not editable, but it looks like the original author may edit it and we can also use comments to manage the state.
