### ISSUE TITLE
'Spell-check' LightBulb action name is confusing

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#24997]
**Version Used**: 
Visual Studio 2017 15.7 (d15.7stg)

**Explanation:**
'Spell-check' action name in LightBulb sounds like it is intended to parse the entire document looking for grammar + spelling errors in comments when it actually corrects typos in member names to the closest known member name.

It should be renamed something akin to 'Correct typo in [typed name]' to be more clear

![image](https://user-images.githubusercontent.com/5387680/36555443-d9355cfa-17b6-11e8-8dd0-d09307d0d61e.png)

Side note: The sort-order for these actions is sub-optimal. I made a typo, yet, VS's first suggestion is that I touch thousands of files to rename the type to match instead of just correcting the compiler error via spell check, which is most likely to be the correct fix, since it is of 'errorfix' icon category and 'Rename type' is not. See #24996 for a suggestion on how to improve this.

**Comment by CyrusNajmabadi** [comment]
> Side note: The sort-order for these actions is sub-optimal. 

I'd like to see the numbers on how many times people rename using the ligthtbulb vs how many times they fix spelling.  @kuhlenh can you provide?

**Comment by CyrusNajmabadi** [comment]
Note: i do like the "fix typo" suggestion.

**Comment by gundermanc** [comment]
> I'd like to see the numbers on how many times people rename using the ligthtbulb vs how many times they fix spelling. @kuhlenh can you provide?

TBH, I've never discovered the Rename (outside the context of Ctrl+R, Ctrl+R inline rename) or the 'Spell-check' issue until I was looking really closely at the lightbulb so I'd be concerned that the numbers may reflect their relative discoverability rather than their value.

> Note: I do like the "fix typo" suggestion.
👍

**Comment by justcla** [comment]
It could even say "Spelling"

**Comment by gundermanc** [comment]
>It could even say "Spelling"

My original complaint was that 'spelling' sounds like the action is checking words from a dictionary against words in my code. The name should reflect that action is correcting the name of a type/method/property, etc.

![image](https://user-images.githubusercontent.com/5387680/42234667-1f6fa496-7eaa-11e8-961c-441a29343558.png)

**Comment by CyrusNajmabadi** [comment]
I'm making changes here.  I'll fix the string as part of that.  I'm going to go with "Fix typo"
