### ISSUE TITLE
"Resolve using" doesn't respect "Separate using directives groups"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#25003]
![image](https://user-images.githubusercontent.com/1103906/36568834-8b2be438-187f-11e8-82c1-47a3741e710d.png)

Resolve using doesn't respect the "Separate using directives groups"

``` C#
using System;

class Program
{
    static void Main(string[] args)
    {
        Foo // <-- Resolve using
    }
}

namespace Microsoft
{
    public class Foo
    {
    }
}
```

Expected:

``` C#
using System;

using Microsoft;

class Program
{
    static void Main(string[] args)
    {
        Foo
    }
}

namespace Microsoft
{
    public class Foo
    {
    }
}

```

Actual:

```csharp
using System;
using Microsoft;

class Program
{
    static void Main(string[] args)
    {
        Foo
    }
}

namespace Microsoft
{
    public class Foo
    {
    }
}
```

**Comment by JoeRobich** [comment]
What is the expectation when the existing block of using statements aren't already sorted?
What is the expectation when the existing block of using statements aren't already separated into groups?

**Comment by CyrusNajmabadi** [comment]
@JoeRobich The logic up to now has always been:

1. if the existing usings don't follow the preference, then don't do anything more than add the import to them.
2. if the existing usings follow the preference, then add the import to it and ensure the final form still matches the preference.
