### ISSUE TITLE
Decompiler should be smarter around constants

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#25006]
The following:

``` C#
        internal int ActualMaxDegreeOfParallelism
        {
            get { return (_maxDegreeOfParallelism == Unbounded) ? int.MaxValue : _maxDegreeOfParallelism; }
        }
```

gets decompiled to:

``` C#
		internal int ActualMaxDegreeOfParallelism
		{
			get
			{
				if (this.m_maxDegreeOfParallelism != -1)
				{
					return this.m_maxDegreeOfParallelism;
				}
				return 2147483647;
			}
		}
```

Similar to other decompilers, we should be smarter around replacing magic "literals" with their appropriate constants.

**Comment by HaloFour** [comment]
Would the decompiler look for any constants in scope that happen to match that literal?  How would it disambiguate if there is more than one?

**Comment by CyrusNajmabadi** [comment]
@HaloFour Roslyn already has some smarts here.  Namely it looks in the *Type* for that value for any constants matching the value.  If it finds any, it will use them.  As such, it will replace constants with things like int.MaxValue, double.Infinity, etc. etc.

This is the behavior you would get previously with the normal 'metadata as source' feature.

**Comment by sharwell** [comment]
➡️ Moved to icsharpcode/ILSpy#1084
