### ISSUE TITLE
Definite assignment bug with out parameter of type CancellationToken

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/roslyn#25019]
**Version Used**: v2.6.1.62414 (according to csc.exe)

**Steps to Reproduce**:

1. Write this code:
    ```csharp
    void Foo(out System.Threading.CancellationToken cancellationToken) { }
    ```
2. Compile

**Expected Behavior**:
Compilation should fail with CS0177 because the `cancellationToken` out parameter is never assigned.

**Actual Behavior**:
It compiles without error.

Interestingly, I can only reproduce the issue with a parameter of type `CancellationToken`. With any other type, I get the error CS01777 as expected.

**Comment by thomaslevesque** [comment]
> Interestingly, I can only reproduce the issue with a parameter of type CancellationToken. With any other type, I get the error CS01777 as expected.

In fact, I can easily reproduce it with a custom struct:

```csharp
struct Bar { }
void Foo(out Bar x) { }
```

**Comment by svick** [comment]
This looks like a duplicate of https://github.com/dotnet/roslyn/issues/24493.

To sum up, the compiler allows you to not assign the `out` parameter if it's *an empty `struct`*. There was a bug that meant that `struct`s in reference assemblies didn't contain their private fields, so the compiler treated them as empty. This has been fixed, but the fixed reference assemblies probably aren't published yet.

**Comment by thomaslevesque** [comment]
> To sum up, the compiler allows you to not assign the out parameter if it's an empty struct.

I was not aware of this, thanks!

Indeed it's a duplicate, I'll close it.
