### ISSUE TITLE
Linq query in ASP.NET 5 Web Application fails with "CS1061: 'int[]' does not contain a definition for 'Where'..."

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#2501]
1.  Create a new ASP.NET 5 Preview Empty Web Application with the following code:
![capture](https://cloud.githubusercontent.com/assets/6464209/8415995/791d77b8-1e57-11e5-8fb3-fff9c1305ac8.PNG)
2.  Set a breakpoint in the ```async``` lambda and F5
3.  Type ```?numbers.Where(n => n > 0)``` in the Immediate Window

**RESULTS**
```error CS1061: 'int[]' does not contain a definition for 'Where' and no extension method 'Where' accepting a first argument of type 'int[]' could be found (are you missing a using directive or an assembly reference?)```

**Comment by KevinH-MS** [comment]
With the latest bits, I'm now getting:  ```error CS1061: 'int[]' does not contain a definition for 'Where' and no extension method 'Where' accepting a first argument of type 'int[]' could be found (are you missing a using directive or an assembly reference?)```

**Comment by KevinH-MS** [comment]
This looks like the same issue as internal bug 114090.

**Comment by cston** [comment]
Fixed in #6220.
