### ISSUE TITLE
Invalid "Remove Unnecessary Cast" suggestion when casting an IntPtr to a pointer

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#25021]
**Version Used**: 
VS 15.6 Preview 5.0

**Steps to Reproduce**:
```cs
private unsafe void foo()
{
    var address = IntPtr.Zero;
    var bar = (int*)&((long*)address)[10]; // yeah, I know - eye cancer
}
```

**Expected Behavior**:
No suggestion to remove the cast

**Actual Behavior**:
VS suggests to remove the cast to `long*`. However as the preview of the code change already shows, that results in a compile time error: IntPtr doesn't support indexing.

If you add another pair of (redundant) parentheses, the suggestion disappears:
```cs
var bar = (int*)&(((long*)address)[10]); // parens around the expression for the address-of-operator
```
![remove-unnecessary-cast-pointer](https://user-images.githubusercontent.com/1947968/36600997-45fb71d2-18b4-11e8-8c2b-66d95d56c53e.gif)

**Comment by jcouv** [comment]
Tagging @sharwell who's looking into another problem with detecting necessary vs. unnecessary casts (https://github.com/dotnet/roslyn/issues/24853)
