### ISSUE TITLE
Unable to resolve `WithAttributeLists()` extension method

### ISSUE THREAD

**Issue by asser-dk** [dotnet/roslyn#25020]
I hope this is just an extremely stupid question but it's been buggering me all day.

I'm making my first code fix provider which (in my head) should be fairly simple. Add an attribute to a given member. I've found several resources on how to make this type of provider, however; all of them use an extension method called `Microsoft.CodeAnalysis.CSharp.Syntax.MemberDeclarationSyntaxExtensions.WithAttributeLists()` which is not available in my project for some reason.

The Analyzer project is a `.NET Standard 2.0` project with the `Microsoft.CodeAnalysis` (version **2.6.1**) NuGet package installed.

Here's the quick fix class:
```CSharp
using System.Collections.Immutable;
using System.Composition;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CodeActions;
using Microsoft.CodeAnalysis.CodeFixes;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

[ExportCodeFixProvider(LanguageNames.CSharp, Name = nameof(MyPropertyAttributeCodeFixProvider))]
[Shared]
public class MyPropertyAttributeCodeFixProvider : CodeFixProvider
{
    private const string Title = "Add [MyAttribute] attribute";

    public override sealed ImmutableArray<string> FixableDiagnosticIds =>
        ImmutableArray.Create(MyAttributePropertyAnalyzer.DiagnosticId);

    public override sealed FixAllProvider GetFixAllProvider()
    {
        return WellKnownFixAllProviders.BatchFixer;
    }

    public override sealed async Task RegisterCodeFixesAsync(CodeFixContext context)
    {
        var root = await context.Document.GetSyntaxRootAsync(context.CancellationToken);

        var diagnostic = context.Diagnostics.First();
        var diagnosticSpan = diagnostic.Location.SourceSpan;

        var declaration = root.FindToken(diagnosticSpan.Start)
                              .Parent.AncestorsAndSelf()
                              .OfType<MemberDeclarationSyntax>()
                              .First();

        context.RegisterCodeFix(
            CodeAction.Create(
                Title,
                c => AddDataContractAttributeAsync(context.Document, declaration, c),
                Title),
            diagnostic);
    }

    private static async Task<Solution> AddDataContractAttributeAsync(
        Document document,
        MemberDeclarationSyntax memberDeclaration,
        CancellationToken cancellationToken)
    {
        var root = await document.GetSyntaxRootAsync(cancellationToken);

        var attributes = SyntaxFactory.AttributeList(
                                          SyntaxFactory.SingletonSeparatedList(
                                              SyntaxFactory.Attribute(
                                                  SyntaxFactory.IdentifierName(
                                                      "MyAttribute"))))
                                      .NormalizeWhitespace();

        return document
               .WithSyntaxRoot(
                   root.ReplaceNode(
                       memberDeclaration,
                       memberDeclaration.WithAttributeLists(attributes))) // Error CS1061
                       // 'MemberDeclarationSyntax' does not contain a definition for
                       // 'WithAttributeLists' and no extension method 'WithAttributeLists'
                       // accepting a first argument of type 'MemberDeclarationSyntax' could be
                       // found (are you missing a using directive or an assembly reference?)
               .Project.Solution;
    }
}
```

First I assumed that this method may have been removed or renamed so I tried to install earlier versions of the `Microsoft.CodeAnalysis` package (going all the way back to 1.0.0) but it changed nothing.

**Comment by mavasani** [comment]
@asser-dk `Microsoft.CodeAnalysis.CSharp.Syntax.MemberDeclarationSyntax` indeed does not contain any method or extension method named `WithAttributeLists`, because it has one or more sub-types that can never have attributes, see sub-types [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Generated/Syntax.xml.Syntax.Generated.cs,df33ad6325693a18,references).

Recommended way to do this operation is to use [SytnaxGenerator.AddAttributes](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Editing/SyntaxGenerator.cs,20ebf96c50e5d864,references) method, which will look at the syntax kind of the underlying declaration node and either add the attributes (if declaration can have attributes) or return the original declaration (if declaration cannot have attributes). You can see the core logic [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/CodeGeneration/CSharpSyntaxGenerator.cs,1168).

**Comment by CyrusNajmabadi** [comment]
Closing out as the question has been answered. Note that MemberDeclarationSyntax now has an actual instance method on it `WithAttributeLists` to allow you do to this.  No need for any extension methods.
