### ISSUE TITLE
Bugs in SwitchStatementHighlighter

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#25039]
#### 1. It highlights unrelated goto statements

```c#
class C
{
    void M()
    {
        unrelated:
        switch (true)
        {
            case true:
                goto case true;
                goto unrelated;
        }
    }
}
```
Click on switch. Second goto is highlighted. It shouldn't be.

#### 2. It doesn't highlight nested break/goto statements.
```c#
class C
{
    void M()
    {
        switch (true)
        {
            default:
            case true:
                if (true)
                {
                    break;
                    goto case true;
                    goto default;
                }
                break;
                goto case true;
                goto default;
        }
    }
}
```
Click on switch. Top-level break/goto get highlighted, but not those inside the if statement.

**Comment by Neme12** [comment]
I'm working on both.

**Comment by Neme12** [comment]
I came across this weird test:
https://github.com/dotnet/roslyn/blob/6847f1e5a909395aae9456e8f366cbf4deb86b69/src/EditorFeatures/CSharpTest/KeywordHighlighting/SwitchStatementHighlighterTests.cs#L467-L482

1. what is this?! some sort of internal database?
2. how was this ever a bug? this test supports the existing (wrong) behavior of highlighting unrelated goto

**Comment by CyrusNajmabadi** [comment]
Many tests predate the move from Roslyn to open source.  Many even predate C#/Vb being written in managed code :)

> how was this ever a bug? this test supports the existing (wrong) behavior of highlighting unrelated goto statements

Tests are not just used to validate good behavior.  They also record current behavior so that you are notified if that behavior changes.  That ensures that changes don't happen without people realizing it.  If the change is for the better, great.  If not, it means more dev work needs to be done.

**Comment by Neme12** [comment]
can someone tell me something about "Bug3483" then and what the purpose of that test is?

@CyrusNajmabadi the test has a "bug" in its name so presumably it fixed a previous "bug" at some point in the past when that `goto` keyword didn't use to be highlighted. But not highlighting seems like the correct behavior to me and I can't think of a reason why that would have been a bug and why it should be highlighted?

**Comment by CyrusNajmabadi** [comment]
The code is broken (i.e. is in the middle of being written).  As such, someone made a call as to what behavior you should see when you encounter that.  The test simply codifies that behavior so it doesn't change unintentionally.  If there is a good reason for change, then that's fine.

**Comment by Neme12** [comment]
Also, we should probably highlight `when` given that it's highlighted in catch clauses.
