### ISSUE TITLE
VB reports that a type parameter constrained to an interface is a reference type

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#2503]
According to https://github.com/dotnet/roslyn/pull/2425#issuecomment-98883932 , the VB compiler improperly reports that a type parameter that is constrained to an interface type is a reference type (`IsRefernceType` is `true`). The C# compiler correctly returns `false` for the corresponding test.

**Comment by gafter** [comment]
... although @VSadov suspects it is due to an error in the program being analyzed ...

**Comment by bkoelman** [comment]
And he was right.

**Comment by VSadov** [comment]
There is a TODO in the 
http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp/Symbols/ErrorTypeSymbol.cs,89

questioning whether IsReferenceType should return true or false. It currently returns true.

I think, statistically, most types are reference types. 
Reference types compose better and therefore are the majority. It is ok for an error symbol to "guess" that it is likely to be a reference type.

If that line of thought is plausible, we should just remove the TODO although there is no urgency at doing that.
