### ISSUE TITLE
Span<RefStruct> is permitted through an implicitly-typed variable

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#25038]
**Version Used**: https://github.com/dotnet/roslyn/commit/37e71921d2f539854ec3a5ebd45cdda5a1a5eccf head of `features/compilers`

**Steps to Reproduce**:

```cs
ref struct S {}

void M(bool c) {
  // ERROR: The type 'S' may not be used as a type argument
  Span<S> x = c ? stackalloc S[2] : stackalloc S[3]; 

  // OK?
  var y = c ? stackalloc S[2] : stackalloc S[3]; 
}
```

**Expected Behavior**: error in both cases

**Actual Behavior**: error only if `S` is spelt out

**Comment by VSadov** [comment]
I think the second case is where it is a pointer for compat reasons.

What is the type of y ?

**Comment by alrz** [comment]
```
newobj instance void valuetype [System.Memory]System.Span`1<valuetype S>::.ctor(void*, int32)
```
is actually emitted. See the example in [sharplab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLTJgg9gOwOY5QC2EANDCAJYA2APgAIAMABPQIwDcAsAFBJjNmGBHADGMZgGUA3gF9e9AMzM4OZFEisATMwDCzab0HH6AFmYBZABTNgWLNWajSUoQEoDR494BuUBMwAHswAvE4A/BhQogDWUNTUWKKCkgDaWgC6IFGx8YnJaWwZ3Dze8jyyQA=).

AFAIK stackalloc only returns a pointer when it's directly in a local decl initializer.

**Comment by VSadov** [comment]
A bug then :)

**Comment by alrz** [comment]
I *really* wished we hadn't change stackalloc default type based on the context it's being used. as far as I know the motivating example was that in a ternary we didn't want to cast either of operands to Span,
```cs
var x = size < 100 ? stackalloc int[size] : (Span<int>)new int[100]; // x is Span
```
And that stackalloc in local decl initializers already produce a pointer
```cs
var x = stackalloc int[size]; // x is pointer
```
So we changed the default type to Span anywhere except for the above case.

We could address the problem by target typing the whole ternary expression if it fails to cast either of operands to each other.
```cs
Span<int> x = size < 100 ? stackalloc int[size] : new int[100]; 
```
But now it's a breaking change because the above code works with `var`.

Note that that could be useful in other places too,
```cs
IEnumerable<StatemnetSyntax> x = statementSyntax is Block block
    ? block.Statements
    : new [] { statemnetSyntax }; // No cast required,

```


Would it worth it to open an issue in csharplang or it's too late for this?

**Comment by OmarTawfik** [comment]
I'd say it is worth taking the breaking change. Will create a PR and see what others might say about this.

**Comment by OmarTawfik** [comment]
I meant fixing the original bug. `stackalloc T [count]` expressions should always check `T` if it was fit to use in `Span<T>` construction. That's a compiler bug and should be fixed.

**Comment by OmarTawfik** [comment]
@alrz closing as my PR was merged. Please tag me if you've other concerns.
