### ISSUE TITLE
Assertion failure in ControlFlowPass.IntersectWith with local function inside switch statement

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#25043]
1. Checkout master & run a debug build of VisualStudioSetup.Next
2. Paste the following code:
```c#
class C
{
    void M()
    {
        switch (true)
        {
            case true:
                void f()
                {
                }
        }
    }
}
```
3. Select the line with `switch (true)` or any line inside the switch statement. This repros most consistently when selecting the whole line by clicking in the left margin in VS.

This is what I get:
![image](https://user-images.githubusercontent.com/11444821/36645188-474f4a6a-1a65-11e8-9e7f-08ae262f29aa.png)

**Comment by jcouv** [comment]
Tagging @gafter

**Comment by gafter** [comment]
@agocke Could you please have a look? Note: repro required running a debug build of VisualStudioSetup.Next from the master branch.

**Comment by gafter** [comment]
Never mind, I'll look at this, as it may be related to https://github.com/dotnet/roslyn/commit/2dfc006a536bebeedc115e5f1a6ba9b03ef42214#diff-f98023b8b3249fce7398e0d6cf920d32

**Comment by gafter** [comment]
Fixed in dev15.7.x branch
