### ISSUE TITLE
Go To All (Ctrl+T) : Save filters

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#25055]
A couple of customers have expressed confusion that Go To All does not save your filters. The customer scenario is they want to find a type most of the time without having to use the query syntax each time.

- Note: we do have keyboard shortcuts for each category (though their keyboard shortcuts aren't as nice as "Ctrl+T")

**Comment by jinujoseph** [comment]
moved to editor team [Link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/584232)
