### ISSUE TITLE
CSharpUseImplicitTypeDiagnosticAnalyzer crashes on `ref var`

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#25063]
Sample code:

```C#
int i = 0;
ref var y = ref i;
```

This causes the CSharpUseImplicitTypeDiagnosticAnalyzer to crash due to a null ref exception.

**Comment by agocke** [comment]
cc @jinujoseph for triage. As we expand the capabilities of ref variables more, this may become more important to fix.

**Comment by Neme12** [comment]
I can't reproduce this on 15.6.1

**Comment by jcouv** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/27246
