### ISSUE TITLE
Semantic analysis of CSharpScript compilation & syntax tree failing

### ISSUE THREAD

**Issue by ciaphas01** [dotnet/roslyn#25068]
**Version Used**: 
- VS2017 Community Edition with latest updates
- Latest versions of all required NuGet packages

**Steps to Reproduce**:
```cs
                Script script = CSharpScript.Create("int x = 2; x += 1;");
 
                script.Compile();
                Compilation compilation = script.GetCompilation();
                SyntaxTree syntaxTree = compilation.SyntaxTrees.Single();
                SyntaxNode syntaxTreeRoot = syntaxTree.GetRoot();
                SemanticModel semanticModel = compilation.GetSemanticModel(syntaxTree);
                 
                var firstVariable = syntaxTreeRoot.DescendantNodes().OfType<VariableDeclarationSyntax>().First();
                IEnumerable<SyntaxNode> firstVariableParents = firstVariable.Ancestors();
 
                IEnumerable<Diagnostic> diag = semanticModel.GetSyntaxDiagnostics();
                IEnumerable<Diagnostic> declDiag = semanticModel.GetDeclarationDiagnostics();
                SymbolInfo variableSymbol = semanticModel.GetSymbolInfo(firstVariable);
                ISymbol variableDecl = semanticModel.GetDeclaredSymbol(firstVariable);
 ```
**Expected Behavior**:
`variableSymbol` and `variableDecl` should contain results on the variable declaration symbol, or `diag`/`declDiag` should tell me if something is wrong.

**Actual Behavior**:
all four variables at the bottom of the above code fragment are empty of results, or null. firstVariable is set and appears to be pointing to the correct syntax node; using different valid types in the OfType() call doesn't seem to affect this result.

**Comment by CyrusNajmabadi** [comment]
VariableDeclarationSyntax refers to the entire declaration . i.e.:    `int i, j, k`.  So asking what 'declared symbol' you get from that has no meaning in C#.  You need to get the individual "VariableDeclarat**or**"s, and ask for GetDeclaredSymbol on those.

**Comment by ciaphas01** [comment]
Blast, I knew even before writing this that I would miss something that simple. Apologies for using the Issues tracker like a troubleshooter, now I know what I need to do to continue. Thank you for your help, @CyrusNajmabadi
