### ISSUE TITLE
Missing completion in switch 'when' clause

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#25084]
Version used: Visual Studio 15.6 Preview 6 (same behavior in latest master bits)

Sample code:
```c#
class C
{
    void M()
    {
        var condition = true;

        switch (true)
        {
            case true
        }
    }
}
```
After `case true`, start typing `when`.
Expected behavior: `when` is offered and selected
Actual behavior: it's not offered at all

![image](https://user-images.githubusercontent.com/11444821/36731831-33f8c6ae-1bcc-11e8-948b-91a7b218fe9a.png)

After `when`, start typing `condition`. No completion whatsoever:
![image](https://user-images.githubusercontent.com/11444821/36731918-7718473e-1bcc-11e8-9603-bffcaf684667.png)

**Comment by Neme12** [comment]
I'll be working on the `when` keyword itself. It looks like `when` is recommended but only in one specific case - after a declaration pattern (see #24113).  I don't know about expression completion after it though, but I'll try to look into that as well.

**Comment by Neme12** [comment]
I have a question. 
```c#
case identifier $$
```
what to do here? this could be the start of a pattern if `identifier` is a type, or it could be a constant. Just don't offer `when` in that case? Or should I check the the symbol of `identifier` using the semantic model?

**Comment by gafter** [comment]
Using the semantic model might not be helpful, as a type is looked up differently than an expression (e.g. when there is a constant in the enclosing class named Color of type Color). I think you should offer `when` as long as it doesn't interfere with typing an arbitrary identifier.

**Comment by Neme12** [comment]
It interferes with name suggestions:
![image](https://user-images.githubusercontent.com/11444821/36745154-ef8c4590-1bee-11e8-829e-54139950f9e5.png)
it preselects `when` as opposed to the name.

**Comment by Neme12** [comment]
@gafter Thanks for reminding me about the Color Color thing, I forgot about that. I added tests for that and I think I got i

**Comment by Neme12** [comment]
@gafter Thanks for reminding me about the Color Color thing, I forgot about that. I added some tests for it and think I got it right (or at least I hope... it's probably not correct for all cases).

**Comment by Neme12** [comment]
Another somewhat related bug.
Here, constant is offered as expected:
```c#
const bool constant = true;

switch (true)
{
    case con|
}
```
but not before when:
```c#
const bool constant = true;

switch (true)
{
    case con| when true:
}
```

**Comment by Neme12** [comment]
With `is` on the other hand, it's sort of the opposite problem:
```c#
const bool constant = true;

if (true is |
```
It indeed does offer constant, but it sets a general expression context rather than a constant expression context. Therefore it also offers things like `from` (not offered after case.).

**Comment by Neme12** [comment]
How did this slip through? We have a whole language feature with no completion. This seems pretty significant to me.
