### ISSUE TITLE
Test Span<T> with constraint on T

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#25086]
From https://github.com/dotnet/roslyn/pull/25035#issuecomment-368637816
A comment from Aleksey in another PR made me think of this: what if you create a custom Span<T> type with some constraints on T. Do we properly check and report on such constraints?
See BindStackAllocArrayCreationExpression line 3130 (type = spanType.Construct(elementType);).

**Comment by alrz** [comment]
I think this also fix https://github.com/dotnet/roslyn/issues/25038
