### ISSUE TITLE
NewLineUserSettingFormattingRule.IsControlBlock throws if node == null

### ISSUE THREAD

**Issue by 6A** [dotnet/roslyn#25098]
**Version Used**: 2.6.1

**Steps to Reproduce**:  
1. Create a syntax node which contains a null node (in my case, using `SyntaxFactory.StructDeclaration("Foo")`).
2. Call `Formatter.Format(...)` using this node.

**Expected Behavior**:  
A formatted node is returned.

**Actual Behavior**:  
An exception is thrown.

**Additional informations**:  
I've already found the source of the bug, and am submitting a PR right now.

**Comment by dolunay** [comment]
var @namespace = SF.NamespaceDeclaration("Test");
var dh = Microsoft.CodeAnalysis.Host.Mef.MefHostServices.DefaultHost;
var workspace = new AdhocWorkspace();
var o = workspace.Options
    .WithChangedOption(CSharpFormattingOptions.IndentBlock, true)
    .WithChangedOption(CSharpFormattingOptions.IndentBraces, false);
var formattedNode = Formatter.Format(@namespace, workspace, o);  //null referance exception
var formattedSource = formattedNode.ToFullString();

I found solution :

var cu = SF.CompilationUnit();
cu = cu.AddMembers(@namespace);
cu = cu.NormalizeWhitespace();
var formattedNode = Formatter.Format(cu, workspace, o);
