### ISSUE TITLE
Modal Dialog Showing during refactoring tests

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#25097]
A number of integration tests have been hanging because of a change signature modal dialog popping up. I copied a couple of dumps from test runs to "\\mlangfs1\public\frsilb\dumps\devenv_modal_test_hang" for investigation. FYI @jasonmalinowski. @jinujoseph, can you assign this to someone to take a look?

**Comment by jinujoseph** [comment]
@dpoeschl , can you check whats goin on here

**Comment by 333fred** [comment]
Happened again: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x/job/windows_debug_vs-integration/112/

**Comment by 333fred** [comment]
@sharwell it doesn't look like that change into dev15.7.x-preview1, correct? Failed in that branch, but I don't see the UIAComWrapper changes in it either.

**Comment by 333fred** [comment]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7-preview1/job/windows_debug_unit64/1/
