### ISSUE TITLE
[Refactoring] Change member modifiers (public, internal, etc…), virtual, static

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#25094]
Refactoring that allows you to change a member modifier "to internal", "to virtual", "to private", "to public".

**Comment by CyrusNajmabadi** [comment]
isn't that just "the completion list"?

**Comment by Neme12** [comment]
I think there's a feature for this already, it's called keyword completion.

**Comment by Neme12** [comment]
I don't understand how this would be any faster than just selecting the modifier and invoking completion?

**Comment by kuhlenh** [comment]
Adding more clarification from developer: "_changing from non-virtual to virtual, or from abstract to virtual would require code modifications to any base and derived classes in the inheritance hierarchy too (such as abstract -> virtual adding an empty block in the base method)._"

**Comment by CyrusNajmabadi** [comment]
Abstract<->virtual is about the only one i can think of where we need to do modifications.  Not sure how it affects the inheritance hierarchy though.  Unless htis feature is going to add/remove "base.XXX" calls in some manner.

**Comment by Neme12** [comment]
What modifications should this do when changing visibility?

**Comment by allisonchou** [comment]
There has been an ask to consolidate Change Signature feature requests into one issue. Since this enhancement is being tracked by the overarching issue #33977, will close as a dupe.
