### ISSUE TITLE
Preview Changes dialog always shows additional files as empty

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#251]
Ported from TFS WorkItem: <b>1114841</b>

------------------------------

<p><b>Repro Steps:</b></p>
<B>Steps to reproduce:</B><BR><BR>1. Use InstallDogfood to install a recent build of Roslyn.</P>
<P>2. Open Roslyn.sln.</P>
<P>3. Open PublicAPI.txt in Workspaces.Desktop.</P>
<P>4. Delete the four lines at the top related to FileTextLoader.</P>
<P>5. Open FileTextLoader.cs. Note that squiggles appear under the four public types/members in this file.</P>
<P>6. Open the light bulb, and under "Add FileTextLoader to API" click "Preview Changes"</P>
<P>&nbsp;</P>
<P><STRONG>Expected</STRONG></P>
<P>The Preview Changes dialog opens, and when PublicAPI.txt is selected in the top pane, the bottom pane shows the file contents with the FileTextLoader APIs added back in.</P>
<P>&nbsp;</P>
<P><STRONG>Actual</STRONG></P>
<P>The bottom pane shows PublicAPI.txt as an empty file.</P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By Tom Meschter (1/26/2015 11:01:13 AM)

If the errors or the fixer don't appear, make sure the build you've installed with InstallDogfood is compatible with the current toolset compilers/diagnostics.

------------------------------

**Comment by mavasani** [comment]
Moving back to Tom for verification.

**Comment by tmeschter** [comment]
Verified that changes to additional files now show up.
