### ISSUE TITLE
Error executing restore.cmd

### ISSUE THREAD

**Issue by RipPer56** [dotnet/roslyn#25103]
Latest Version: 

I'm trying to build the project so i start by the restore.cmd but i'm getting this error:
**Property 'PositionalBinding' cannot be found for type 'System.Management.Automation.CmdletBindingAttribute'.
At C:\Users\RipPer\Documents\Visual Studio 2015\Projects\Roslyn\build\scripts\build.ps1:17 char:15
+ [CmdletBinding <<<< (PositionalBinding=$false)]
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PropertyAssignmentException**

Also i'd like to know how to build the vsix after modification on the code without opening the solution in VS(because of other problems)

**Comment by jcouv** [comment]
Tagging @jaredpar who'll have more of clue than me.

**Comment by AdamSpeight2008** [comment]
@jcouv Doesn't Roslyn require VS2017 ?

**Comment by jaredpar** [comment]
Looks like the problem is that you've chekced Roslyn out to a path that has spaces. That's not supported in our infrastructure and hence will result in errors like that. 

https://github.com/dotnet/roslyn/issues/20929
