### ISSUE TITLE
C# Pattern matching for cast / null check should match when assigning

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25102]
Consider the following code.

        private Logger logger; /* Logger Implements IDisposable */

        public void Foo()
        {
            var oldLogger = this.logger as IDisposable;
            this.logger = new Logger();
            if (oldLogger != null)
            {
                oldLogger.Dispose();
            }
        }

pattern matching will suggest to replace the cast and the null check with the following:

            this.logger = new Logger();
            if (this.logger is IDisposable oldLogger)

Which results in a bug...

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/204055/c-pattern-matching-for-cast-null-check-should-matc.html
VSTS ticketId: 572536_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
