### ISSUE TITLE
Comment nodes not being renamed

### ISSUE THREAD

**Issue by vsccarl** [dotnet/roslyn#25100]
**Version Used**: 
d15.6 Preview 6 (including d15.6\27426.0)
**Steps to Reproduce**:

1. Paste in the code below
2. Right click on `first` on this line `public static decimal Add(decimal first, decimal b)`
3. Rename
4. Check include comments in the rename dialog
5. Start typing a new name

**Code:**
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClassLibrary1
{
    public static class Calculator
    {
        /// <summary>
        /// Returns a sum of first and second args
        /// </summary>
        /// <param name="first"></param>
        /// <param name="b"></param>
        /// <returns></returns>
        public static decimal Add(decimal first, decimal b)
        {
            return first + b;
        }
    }
}
```

**Expected Behavior**:
The `<param name="first"></param>` should also be renamed.

**Actual Behavior**:
Only the string in the comment is being renamed.
[gif example](https://microsoft-my.sharepoint.com/personal/v-margko_microsoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fv-margko_microsoft_com%2FDocuments%2FVSGifs%2Frenaming%2Egif&parent=%2Fpersonal%2Fv-margko_microsoft_com%2FDocuments%2FVSGifs&slrid=d7b24e9e-20a9-0000-67d3-3cd88e20cae9)

Update(jcouv): Adding screenshot since link didn't work for me.
![image](https://user-images.githubusercontent.com/12466233/36773007-6b501fea-1c0c-11e8-93d7-f92f4cd5a605.png)

**Comment by CyrusNajmabadi** [comment]
Interesting.  this only happens if you have "rename in comments and strings" enabled.  i wonder if there's something about doing two edits in the same comment that is throwing things off.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  With "rename in comments and strings" on or off, you get the right experience.
