### ISSUE TITLE
Generate method picks Func<object> instead of Action

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn#25110]
**Version Used**: 

```
Microsoft Visual Studio Enterprise 2017 Int Preview (Dogfood)
Version 15.6.0 Preview 7.0 [27425.0.d15.6]
VisualStudio.15.IntPreview/15.6.0-pre.7.0+27425.0.d15.6
C# Tools   2.7.0-beta3-62620-07. Commit Hash: e873e69306527a0424e97af2985370556f474019
```

**Steps to Reproduce**:

1. File -> New Project -> .NET Core -> Console App
2. Edit Main.cs to be the following:

``` C#
class Program
{
    static void Main(string[] args)
    {
        DoSomething(() => Console.WriteLine("Hello World"));
    }
}
```

3. Put cursor on squiggly for DoSomething not being found
4. Ctrl-`.` -> Generate method Program.DoSomething

**Expected Behavior**:

The signature chosen for the generated method allows the program to compile successfully:

``` C#
private static void DoSomething(Action p)
{
    throw new NotImplementedException();
}
```

**Actual Behavior**:

The signature chosen for the generated method does not allow the program to compile successfully:

``` C#
private static void DoSomething(Func<object> p)
{
    throw new NotImplementedException();
}
```

* Error CS1662: Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type
* Error CS0029: Cannot implicitly convert type 'void' to 'object'

**Comment by CyrusNajmabadi** [comment]
We now produce: 

![image](https://user-images.githubusercontent.com/4564579/198753932-12ddfde9-1ddb-4c72-abb4-0bcc68c95427.png)
