### ISSUE TITLE
[Compiler Bugs] VB generic function can not overloads each other

### ISSUE THREAD

**Issue by xieguigang** [dotnet/roslyn#25117]
**Version Used**: 

Microsoft Visual Studio Community 2017 
Version 15.5.7
VisualStudio.15.Release/15.5.7+27130.2036
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA624
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA624
Microsoft Visual C# 2017

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.4.2.1331
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

**Steps to Reproduce**:

1. Declare two generic function like this [**demo**](https://github.com/xieguigang/sciBASIC/blame/b38ad6376e266d532e7cbc2aaa4554d0c4394172/Microsoft.VisualBasic.Core/Extensions/Collection/Matrix.vb#L70):

```vbnet
<MethodImpl(MethodImplOptions.AggressiveInlining)>
<Extension>
Public Function Matrix(Of DataSet As DynamicPropertyBase(Of Double))(data As IEnumerable(Of DataSet)) As IEnumerable(Of Double())
    Return Matrix(Of Double, DataSet)(data)
End Function

<MethodImpl(MethodImplOptions.AggressiveInlining)>
<Extension>
Public Function Matrix(Of DataSet As DynamicPropertyBase(Of String))(data As IEnumerable(Of DataSet)) As IEnumerable(Of String())
    Return Matrix(Of String, DataSet)(data)
End Function
```

**Expected Behavior**:
These two generic function should overloads each other based on their parameter type.

**Actual Behavior**:
These two generic function can not overloads each other:
![error](https://user-images.githubusercontent.com/9410171/36778187-fbf41c78-1ca6-11e8-9788-44b572ec49bb.png)

**Comment by jcouv** [comment]
Taggging @AlekseyTs for comment. This may need to be moved to vblang repo (let me know).

**Comment by gafter** [comment]
The [VB language specification](https://github.com/dotnet/vblang/blob/master/spec/type-members.md#methods) says

> Methods can be overloaded, which means that multiple methods may have the same name so long as they have unique signatures. The signature of a method consists of the number and types of its parameters.

These two methods have identical signatures, and are therefore forbidden overloads. The compiler is obeying the language specification here.

**Comment by xieguigang** [comment]
@gafter, No, the parameter type ``DataSet`` they are definitely two different types: one is ``DynamicPropertyBase(Of Double)`` and another is ``DynamicPropertyBase(Of String)``, these two type didn't have the identical signature:

+ ``DataSet As DynamicPropertyBase(Of Double)``
+ ``DataSet As DynamicPropertyBase(Of String)``

**Comment by AlekseyTs** [comment]
@xieguigang Constraints are not part of a signature. In both signatures the DataSet type is just a first type parameter, and type parameters are matched by position. If they are at the same declaration position, they are treated as equal types.
