### ISSUE TITLE
Support all Linq methods in Linq query to linq method conversion

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#25112]
We are going to skip some methods in implementing the first iteration (#8953) of the conversion. Let us consider them as a second iteration.
C#
- Let
- Join

VB
- GroupJoin
- SimpleJoin
- Aggregate
- GroupBy
- Let

Other features and checks:
- check that the conversion works in case of comments mixed with the code
- check that the conversion gives up in case of preprocesser mixed with code
- consider good naming of variables introduces in conversion: now there are 'VBIT' and 'h__TransparentIdentifier', but we can construct something like 'item<X>'.
- consider preserving whitespaces formatting (trivias) in expression generated like 'x*x' should be kept as is and not converted to 'x * x'. However, keeping all trivias can lead to 'select x*x/r/n' to '.Select(x => x*x/r/n/)' which is also not correct

**Comment by CyrusNajmabadi** [comment]
Skipping out on 'let' seems like a big take-back.  It will mean many simple queries won't be translatable.  I get that these will involve transparent identifiers.  But the point, to me, of having this feature is precisely so it can take care of the unpleasantness of translating these sorts of queries for me.  If i only can use this feature for extremely simple lambdas, then it's not really providing me with much value.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We can drive this as individual bug reports/requests, or PRs if people want to add support for a particular construct.
