### ISSUE TITLE
GoTo results should be simpler for multiple target frameworks

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#25128]
Forked from https://github.com/dotnet/roslyn/issues/16587.

This issue is to discuss what can be done to make GoTo results better for multi-targetting scenarios.  For example, instead of:

![image](https://user-images.githubusercontent.com/4564579/36809712-9499b714-1c7d-11e8-8dbb-1f2f841f48d6.png)

We could do:

![image](https://user-images.githubusercontent.com/4564579/36809717-992782ac-1c7d-11e8-8195-cf1078cc6b5d.png)

**Comment by CyrusNajmabadi** [comment]
Tagging @olegtk .  

Oleg, i think doing the above would be possible from the LS side.  Specifically, as we collect results, we could 'merge' them, and then tweak the secondary display string to have the part about ```(net20, net35, ...)```.  One difficulty though is that i don't know if it's possible for us to ask the UI to refresh the information it has for a particular entry.  i.e. these reuslts stream in on the LS side.  As such, the set of projects we know this can be found in will change as the search progresses.  If we want to support streaming, we'd need a way to tell the UI "hey, this item has changed, update teh UI accordingly". 

Do you think such a thing would be possible?

**Comment by CyrusNajmabadi** [comment]
Actually, is this what INavigateToCallback.Invalidate is for?  Is that a way to tell the UI: refresh the display for any NavigateToItem's that have been reported?  If so, this could ideally be done fairly trivially.

**Comment by CyrusNajmabadi** [comment]
I'd be willing to try to do the work for this on the Roslyn side.  however, the basic idea would be that we would update this code in Roslyn's reported:

https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemProvider.Searcher.cs#L124-L135

Specifically, we would keep track of the NavToItems we had created.  Basically, we'd hash somehow on on the Doc/SourceSpan for the INavigableItem.  If we got another result that had a doc that was a linked-file to it, and had hte same source span, then instead of creating a new NavigateToItem, we would then update the existing one, and then tell the UI to refresh.

**Comment by steffenloesch** [comment]
I like the proposed new UI. That's the kind of thing that would make our search experience much better. We have many projects that target multiple frameworks and the multiple entries resulting from that, when searching a type say, are confusing and use too much screen real estate.

**Comment by olegtk** [comment]
@grabalon, @AmadeusW 
 We do have a feature request to de-duplicate GoTo results so this potentially falls into that category.

**Comment by grabalon** [comment]
@CyrusNajmabadi yes, INavigateToCallback.Invalidate is the thing you want here. It will throw away all your provided results and ask again, so your cache would come in handy for that too. FWIW, I've pushed back on de-dup work, hoping that we can depend on providers give unique info. I believe Cyrus' proposal is a good way to improve things.

**Comment by CyrusNajmabadi** [comment]
Oh.  I would really prefer to *not* throw-away+recompute.  Esp. since i don't trust the cache we have due to some other issues we've discovered.

My *ideal* preference would be to be able to invalidate/refresh a single NavigateToItem.  That way we'd basically just be saying "everything is all good.  just the UI for this specific item should update itself.

Would such a thing be possible?  Would is be hard to do?

Thanks!

> We do have a feature request to de-duplicate GoTo results so this potentially falls into that category.

Note: this is not quite deduping.  The items are not all exactly the same.  Rather, they're results that should be 'merged' and which wan the UI to reflect that htey've been merged (i.e. through text like ```(net20, net35, ... etc.)```).

From the LS's perspective, we don't actually really need anything from the UI to merge (since we can do that ourselves).  But we do need a way to tell the UI that an item has changed so that hte UI for that specific item can refresh.  That way we can continue with our streaming model, showing results the moment we get them.

Woudl that be possible?

**Comment by grabalon** [comment]
Not with the current APIs, unfortunately. We can consider that change, but I'd start with calling Invalidate until/unless we take that change.

**Comment by CyrusNajmabadi** [comment]
Ok.  someone can def try this.  But i can't imagine it would be good, right?  During the search you'd get a ton of times when the list would reset/refresh entirely.  That seems like it would be a *super* bad experience.  Unless i'm not understanding how Invalidate works.  Does it have any sort of smarts that would keep the list in the right location, and make it not seem as if it was resetting to 0 items then refilling?

**Comment by grabalon** [comment]
Honestly, I'm not sure. I haven't had to update code that runs through it. The comments around it suggest it just straight-up throws away all the results from the invalidated provider.

**Comment by genlu** [comment]
I think this is done by #50128
