### ISSUE TITLE
Decompiled sources from VB to C# displaying non-disassembled VB

### ISSUE THREAD

**Issue by vsccarl** [dotnet/roslyn#25159]
**Version Used**: 
d15.6\27420.01
**Steps to Reproduce**:
Enable navigation to decompiled sources Tools -> Options -> Text Editor -> C# -> Advanced 

1. Create a C# class library with the code:
`public static int AbsoluteValue(int input) => Math.Abs(input); `
2. Build and close this solution
3. Create a new VB project and add a reference to the above built .dll
4. Add a call to AbsoluteValue 
5. Place the caret on the call, F12 to go to definition

**Expected Behavior**:
Navigation to the decompiled source is displayed in C# with full disassembly.
**Actual Behavior**:
Navigation to the decompiled source is displayed in VB without full disassembly.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this issue.
