### ISSUE TITLE
Test plan for "stackalloc initializers"

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#25160]
In addition to the currently allowed syntax (`stackalloc int[3]`) we should allow stack allocated arrays be created with initialization:
```C#
stackalloc int[3] { 1, 2, 3 }
stackalloc int[] { 1, 2, 3 }
stackalloc[] { 1, 2, 3 }
```

Proposal https://github.com/dotnet/csharplang/issues/1286

Here is the rough testplan for the stackalloc initializers feature.

Some tests may already exist or be part of other tests. In such case we can just check them off. 

### correctness ###
- [x] langver
- [x] simple cases - target is pointer, target is `Span`, target is `ReadOnlySpan`
- [x] nested cases - in conditional expressions.
- [x] use sideeffecting value expressions. Check the order of evaluation.
- [x] when buffer is not used. Check that element sideeffects are not lost.
- [x] when element inits are side-effecting and one throws. Check sideeffects are not lost.
- [x] ~~check that partial result is not visible. - if element throws and exception caught, whole thing is not reassigned to the new value. (try spans and ordinary stackallocs)~~ (not possible due to stackalloc restrictions)
- [x] trivial case - no elements. Check that there is no `localloc`
- [x] put `await` in the size or in the middle of element initializers
- [x] initializer uses a local that is captured by a lambda expression. See that if lambda changes the value of the local, then we see the updated value when initializing
- [x] test data flow. 
	- [x] use of locals in initializers is checked
	- [x] assignments of locals in initializers have effect

### optimizations ###
- [x] initializers are byte-size literals. (blob init)
- [x] initializers are larger than byte-size literals. (elementwise init)
- [x] initializers are byte-size literals  + some nonliterals. (blob init + patching)
- [x] when all bytes in the payload have same values, `initblk` is used, Check 1 and 1+ element size cases.

### errors ##
- [x] parsing tests and error tolerance
- [x] cannot infer array element type (targeting a pointer, a span)
- [x] invalid array shapes - multidimensional, nested, size mismatches, ... 
- [x] bad conversions
- [x] bad local initialization contexts - using, fixed, ref, const, argument ...
	- [x] should actually work in `for` initializer
- [x] should it work in `for(int* x = stackalloc...)`, probably the same ways as before... ?  
- [x] missing initializer and size .
- [x] outer expression is not usable in elements (not assigned yet)
- [x] in the array type inference case, the outer expression cannot be used to determine the type - should be an error and should not be some kind of crash due to circular dependency
- [x] make it to infer strange types. 
	- [x] dynamic
	- [x] ref-struct
	- [x] void   (use a void method to initialize an element)
	- [x] lambda expression   (formally typeless)
	- [x] null
	- [x] discard  `_` - is not even a value. 
- [x] missing span type 
- [x] missing span .ctor 
- [x] pointer variant in `safe` code

## API ##
- [x] Region analysis. 
	- [x] stackalloc with initializer is a write
	- [x] Using locals in in stackalloc is a use 
- [x] GetSymbolInfo
	- [x] on the whole node (checked for ordinary int* and Span)
	- [x] on size expression (including cases when implicit conversions happen)
	- [x] on element expressions (including cases when implicit conversions happen)	
	- [x] In particular thee was an interest about error cases where the expression refers to itself.
- [x] GetDeclaredSymbol
	- [x] the expression does not declare anything, try with whole node, elements, just in case..
- [x] GetOperation
	
## From the  feature review ##
- [x] test with "unmanaged" constraint. Whenever the features are in the same branch.
- [x] More tests for region analysis. 
- [x] Assign to discard - ` _ = stackalloc .. . .` (Also check what semantic model says about this)
- [x] Try stackalloc inside `lock`, `select`, `let`, in a ternary in an initializer of a `for` variable.
- [x] Check semantic model when unexpected/invalid element type is inferred 

## Manual IDE testing ##
The more detailed plan is here https://github.com/dotnet/roslyn/wiki/Manual-Testing although many items may end up N/A.  We will have to go through the list before merging.

(This may not be possible to be done with just public bits)

Preliminary - the scenarios of concern are not many, since this is an expression and fairly simple too.

- [x] extract whole thing to a method (regardless whether that works for stackallocks, it should behave rationally, even if resulting code has errors due to escape rules, etc...)
- [x] extract array size and elements to a method, especially if there are implicit conversions. (should just work if semantic APIs work correctly)
- [x] general typing of the construct 
	- [x] IDE should not autocorrect into something meaningless
	- [x] inside the initializer the dropdowns shoudl be as expected - i.e. variables in scope
	- [x] autocompletion of parens and braces - [] { }

**Comment by VSadov** [comment]
Thanks!

**Comment by VSadov** [comment]
We should use this for tracking purposes and close other bugs and delete the document. - Just so that tracking done in one place.

I may add some more items to the plan if something interesting comes to mind. 

The team will review the testplan next week. The outcome will be 
- whether the existing test coverage (checked boxes) is sufficient to merge into /compiler. 
Otherwise - what is missing.
- whether overall test plan is adequate. 
Otherwise more test ideas. 

Most test items will need to be addressed before merging to the release branch, but not everything needs to be done in a feature branch. Some test work may continue in /compiler. In particular there are tests that rely on features/fixes in other branches anyways so they must wait until the merge.

I can definitely help with the testing. 
(we should mark somehow the items so that we do not work on same things)

I also think the IDE part can not be done externally or would be hard to do. I will look into it. Do not worry about that part.

**Comment by VSadov** [comment]
@alrz - updated some items in the test plan. Mostly to reflect what is already tested.

**Comment by VSadov** [comment]
About the "capturing" scenario - 
That is just to check that lambda rewriter visits initializer of `stackalloc`. 
If there are lambdas in the initializer or captured locals, they should be updated accordingly.

An example:

```C#
using System;
public class C {
    unsafe public void M() 
    {
        // captured by the lambda. 
        byte x = 1;
               
        byte* b = stackalloc byte[]{((Func<byte>)(() => x++))(), x};
        
        // should print 2
        System.Console.WriteLine(b[1]);
    }
}
```
I have checked it on sharplab.io and it looks like the IL is correct, so it should just work.

**Comment by VSadov** [comment]
The testplan review has resulted in the following:

== Need to do before merging.
- IOperation tests. The whole node may not be supported, but we should see info on children expressions.
- Semantic model. In particular thee was an interest about error cases where the expression refers to itself.

(I think https://github.com/dotnet/roslyn/pull/25382 + self-referential case addresses the above)

== More tests (after merge)
- test with "unmanaged" constraint. Whenever the features are in the same branch.
- More tests for region analysis. 
- Assing to discard - ` _ = stackalloc .. . .` (Also check what semantic model says about this)
- Try stackalloc inside `lock`, `select`, `let`, in a ternary in an initializer of a `for` variable.
- Check semantic model when unexpected/invalid element type is inferred 

I will add these items to the testplan.

**Comment by alrz** [comment]
The test plan has been completed.
