### ISSUE TITLE
bufferPosition ArgumentException from CaretElement::InternalMoveTo on moving caret in an InlineRenameSession on .cshtml file

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#2516]
Ported from TFS WorkItem: **1141887**

------------------------------

**Repro Steps:**

1. Download ZIP source from [https://github.com/madskristensen/MiniBlog](https://github.com/madskristensen/MiniBlog)

2. Open Index.cshtml (or any other .cshtml)

3. Start InlineRename Session (ctrl +R, ctrl + R) on any identifier thats definied in source

4. Press Home Key to move the caret to start of the identifier

&nbsp;

Expected: Caret moves

Actual: Exception dialog pops up.

&nbsp;

[http://index/#Microsoft.VisualStudio.Platform.Editor/CaretElement.cs,768](http://index/#Microsoft.VisualStudio.Platform.Editor/CaretElement.cs,768)

------------------------------

**Revisions:**

1) Created By Balaji Krishnan (3/19/2015 12:51:07 PM)

![image](https://cloud.githubusercontent.com/assets/235241/7467285/23190d2e-f2aa-11e4-8fe8-4f3a0dcf21d7.png)

------------------------------

2) Edited By Oleg Tkachenko (3/19/2015 1:27:16 PM)

I'd assume this is by design and Roslyn gives us&nbsp;new caret position in a wrong snapshot (cshtml is a projection scenario).

------------------------------

3) Edited By Mark Wilson-Thomas (3/19/2015 4:44:05 PM)

[t] Per Oleg we think this is by design. Please work with Oleg to fix up the E2E scenario and avoid the exception dialog.

------------------------------

4) Edited By Balaji Krishnan (3/20/2015 12:58:27 PM)

Looks like this could be our bug.

------------------------------

**Comment by dpoeschl** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/2625 (I've been using the wrong "Fixes #xxx" notation)

**Comment by dpoeschl** [comment]
@balajikris - Assigning to you for verification because you filed the issue originally. Thanks!

**Comment by balajikris** [comment]
thanks, will verify.
