### ISSUE TITLE
EditorConfig: trim_trailing_whitespaces rule is not applied to the whole file

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#25163]
**Version Used**: 
D15.6 Preview 6
**Steps to Reproduce**:
1. Add the following rules to editorconfig:
```
[*]
trim_trailing_whitespaces = true
```
2. Add a new Class.
3. Add trailing spaces to each line.
4. Add a method to class also with trailing spaces.

Actual: trailing spaces trimmed only in few lines.
Expected: trailing spaces trimmed in the whole file.
5. Change editorconfig to:
```
[*]
trim_trailing_whitespaces = false
```
6. Remove added method
7. Add trailing spaces for each line
8. Add a method to class also with trailing spaces.

Actual: trailing spaces trimmed in few lines.
Expected: trailing spaces not trimmed in the whole file.
Note: Also nothing changes on Save/Save All.

**Comment by olegtk** [comment]
looks like an editor bug (or probably not meeting expectations), @jinujoseph please route to the editor.

**Comment by jinujoseph** [comment]
moved [link](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/575710)

**Comment by aditya-kadam** [comment]
@mattscheffer Can you please confirm the below:

1. When you added the trim trailing white spaces to each line did you hit enter(i.e. inserted a new line character) after each line? If not can you try the same repro with pressing enter after the whitespaces on each line and see if the whitespaces are trimmed for all those lines?
