### ISSUE TITLE
UseImplicitType should not be offered when an explicit type is necessary for disambiguating between method overloads

### ISSUE THREAD

**Issue by Jayrod246** [dotnet/roslyn#25176]
**Version Used**: 
Microsoft Visual Studio Community 2017 
Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual C# 2017   00369-60000-00001-AA314
Microsoft Visual C# 2017

**Steps to Reproduce**:

1. Write the following code to a file inside a C# project:
```
class Program
{
    static void SomeMethod(out int x) => x = 0;
    static void SomeMethod(out float x) => x = 0.0f;

    static void Main(string[] args)
    {
        SomeMethod(out int val); // IDE0007 warning is thrown.
    }
}
```

**Expected Behavior**:
No warning, as the explicit type is necessary to determine which overload of SomeMethod to use.

**Actual Behavior**:
IDE0007 warning is thrown. Using the fix options (in Visual Studio) leads to CS0121 "The call is ambiguous ..." being thrown.

**Comment by Neme12** [comment]
will you actually tell us what IDE0007 is? :smile:

**Comment by jcouv** [comment]
I think IDE0007 is "use 'var' instead of explicit type"

**Comment by jcouv** [comment]
I wonder if this was already fixed by https://github.com/dotnet/roslyn/pull/24619 (which fixes a very similar problem in UseImplicitType.
Tagging @JieCarolHu to confirm.

**Comment by JieCarolHu** [comment]
It was fixed in https://github.com/dotnet/roslyn/pull/23135
Closing this issue
