### ISSUE TITLE
[Request] Instance left operand without right operand 

### ISSUE THREAD

**Issue by RevensofT** [dotnet/roslyn#2517]
Hi,
I have a request that I think it should be useful when want to write an instance object that only use once and forget about it. However we can't create any object without left operand because language limited(not compiler or IL limited).

Here is an example I wrote, in this code, I save a time and work to create a local variant inside stack frame also make it clean and short code.
``` VB
Dim Stream As System.IO.Stream ' Get a stream from somewhere
Dim Data As String ' Some data for write.

'No need for close StreamWriter because Stream still going to be use.
(New System.IO.StreamWriter(Stream)).Write(Data)
```

**Comment by VSadov** [comment]
If you are creating an instance just to call its method, you can use 'Call' - 
```VB
        Dim Stream As System.IO.Stream ' Get a stream from somewhere
        Dim Data As String ' Some data for write.

        'No need for close StreamWriter because Stream still going to be use.
        Call New System.IO.StreamWriter(Stream).Write(Data)
```

**Comment by RevensofT** [comment]
It work like a charm; Thanks VSadov, I already forgot about it.
