### ISSUE TITLE
Update Roslyn to support building Arm64 binaries

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/roslyn#25182]
**Expected Behavior**:
Roslyn compilers such as vbc and csc should support the /platform:arm64 switch.

**Actual Behavior**:
Arm64 PE files cannot be generated by Roslyn based compilers.

**Comment by jp2masa** [comment]
This should have been closed by #25186, right?

**Comment by davidwrighton** [comment]
Yes, this is fixed.
