### ISSUE TITLE
Generate method fails to generate static method

### ISSUE THREAD

**Issue by Przemyslaw-W** [dotnet/roslyn#2518]
Hi,

Repro code:
```
class C
{
    public string Foo { get; } = CreateFoo();
}
```

Generate method creates instance CreateFoo() method. It should be static

**Comment by jmarolf** [comment]
This repros in RC, but is fixed in builds after RC.  This is the code that is generated:

```C#
using System;

class C
{
    public string Foo { get; } = CreateFoo();

    private static string CreateFoo()
    {
        throw new NotImplementedException();
    }
}
```

I'll reply back here when there is a public build with this fix.
