### ISSUE TITLE
Allow 'ref readonly struct' for 'readonly ref struct'

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/roslyn#25187]
**Version Used**: 
Visual Studio 2017 27428.0.d15.7

**Steps to Reproduce**:

1. Create a C# project for netcoreapp2.1
2. Write a declaration of a ref struct:
```C#
public readonly ref struct S { }
```

**Expected Behavior**:
The order of 'ref' and 'readonly' should not matter; I can either use 'readonly ref struct' or 'ref readonly struct' to declare readonly ref-like types.

**Actual Behavior**:
'ref readonly struct' is not allowed. looks like `ref struct` is a compound keyword like `partial class`.

**Comment by CyrusNajmabadi** [comment]
This is not a compiler issue, but a request for a change in the language.  as such, this should be filed over at dotnet/csharplang.  Thanks!

**Comment by alrz** [comment]
this already championed (https://github.com/dotnet/csharplang/issues/946)

**Comment by jcouv** [comment]
Thanks for reporting this. 
Since this is a known issue, I'll go ahead and close as duplicate. @alrz is close to getting this fix (https://github.com/dotnet/roslyn/pull/23533) into C# 7.3.

**Comment by gafter** [comment]
This was not championed or fixed. What was fixed was the ordering of `ref` and `partial`. There is still an issue with the ordering of `ref` and `readonly`.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #1536](https://github.com/dotnet/csharplang/issues/1536) via [**ZenHub**](https://www.zenhub.com/)

**Comment by alrz** [comment]
@gafter `readonly` is already permitted with any order. I believe this is exacly what is discussed earlier (allowing ref readonly struct)

**Comment by alrz** [comment]
that is, if we relax the order of `ref` the code in the title would compile fine.
