### ISSUE TITLE
[Completion] C# IntelliSense: No completions for [assembly ] Video no completion for XamlCompilation assembly attribute.

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#25188]
No completions for [assembly ] Video no completion for XamlCompilation assembly attribute.

Repro video: https://www.dropbox.com/s/bo7rx8urpyxklxx/vsm-xaml-completion-05.mp4?dl=0

See vsts https://devdiv.visualstudio.com/DevDiv/_workitems/edit/568778

**Comment by jcouv** [comment]
@mkrueger At the very end of the video capture, it looks like there are red squiggles in the code that you typed. What errors do you get there, or if you build the project?

**Comment by Therzok** [comment]
Should be fixed via: https://github.com/dotnet/roslyn/issues/25622

**Comment by Neme12** [comment]
@Therzok  really? I don't think so. Here even the `assembly` keyword isn't offered. And the attribute should be offered currently because there's a using for it, not need to look inside namespaces.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
