### ISSUE TITLE
How to retrieve IMethodSymbol for IfTrue operator

### ISSUE THREAD

**Issue by GeorgeAlexandria** [dotnet/roslyn#25192]
Hi,

I'm used *Microsoft.CodeAnalysis.VisualBasic.1.3.2* and they dependents.

I just want to retrieve a `IMethodSymbol` for the `A.op_True` during getting the semantic info for the  `new A()` node (`ObjectCreationExpressionSyntax`) that is a part of the ` If New A() Then Console.WriteLine("Test")` (`SingleLineIfStatementSyntax` ) node from the code bellow:

```vb
...
    Private Class A

        Public Shared Operator IsTrue(arg As A) As Boolean
            Return True
        End Operator

        Public Shared Operator IsFalse(arg As A) As Boolean
            Return False
        End Operator

    End Class

    Sub Create()
        If New A() Then Console.WriteLine("Test")
    End Sub
```

I tried to retrieve symbol using `GetSymbolInfo` and `GetConversion` but they returned to me `IMethodSymbol` of the `.ctor`. 
I tried to parse this code with `IOperation` feature, disable `OptionsStrict` in the corresponding compilation and retrieve symbol using `GetOperation`, but It also didn't give to me the `A.op_True`.

I know that I can retrieve a returning type of expression, and than try to find in a members collection some conversions and operators by order that was described in [this article](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/istrue-operator#compiler-use-of-istrue), but it doesn't good solution for my case.

So, how I can retrieve `IMethodSymbol`? Any suggestion would be grateful.

**Comment by jcouv** [comment]
I tried a few things, but didn't find a way to get that `A.op_True` from the semantic model API.
Tagging @AlekseyTs @gafter in case they know a way.

Out of curiosity, why are you using operators true/false, as opposed to conversions to `Boolean`? I expect you should be able to get the conversion from the semantic model API.

**Comment by GeorgeAlexandria** [comment]
@jcouv, operators `IsTrue|IsFalse` are used in a some of user codes, that my app just try to analyze, so I can't do anything with it...

**Comment by AlekseyTs** [comment]
I do not think SemanticModel exposes information about this implicit application of IsTrue operator. However, I think one should be able to find that information in IOeration tree, on top of the node corresponding to the condition expression, perhaps with a conversion in between.

**Comment by GeorgeAlexandria** [comment]
@AlekseyTs, Yes, your assumption was right, I tried to retrieve `IOperation` for `SingleLineIfStatementSyntax` and found in the it descendant nodes the `IUnaryOperator` of `A.op_True`, but It would be wonderful if I can retrieve a IOperation tree from the `IOperation` of `new A()` or just it parent. 
Can I do that? 
(I know that can visit `IOperation` node by top-down direction using nodes and `OperationVisitor`)

**Comment by jcouv** [comment]
I suspect that getting the information from just `new A()` won't be possible. The conversion to bool or the `op_true` comes from the context of binding the `if` statement.

**Comment by AlekseyTs** [comment]
> It would be wonderful if I can retrieve a IOperation tree from the IOperation of new A() or just it parent.
Can I do that?

I am confused, if you have IOperation for ```new A()``` what prevents you from going up the parent chain?

**Comment by GeorgeAlexandria** [comment]
@AlekseyTs, oh, I see, that you are added Parent to `IOperation` in a some of new versions. As I pointed out I'm used **1.3.2** where IOperation doesn't have `Parent`. Well, as a workaround for **1.3.2** I can retrieve `IOperation` for `SyntaxNode.Parent` if IOperation for current node doesn't give me that I want.

Thanks for suggestions, I think issue can be closed.
