### ISSUE TITLE
'Use block body' is broken with async

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#25202]
```c#
using System.Threading.Tasks;

class C
{
    async Task M() => await Task.Yield();
}
```

expected behavior:
```c#
    async Task M()
    {
        await Task.Yield();
    }
```

actual behavior:
```c#
    async Task M()
    {
        return await Task.Yield();
    }
```
(doesn't compile)

**Comment by Neme12** [comment]
Note: this affects "introduce local" as well. See #26456

**Comment by sharwell** [comment]
:memo: It's possible that https://github.com/dotnet/roslyn/pull/24624#discussion_r167026792 could be addressed when resolving this issue.

**Comment by Neme12** [comment]
It looks like the PR only fixed "use block body" but not the other features mentioned above. Should this be reopened?

**Comment by CyrusNajmabadi** [comment]
@Neme12 can you please open separate bugs so that things can be tracked appropriately?  Thanks!

**Comment by Neme12** [comment]
I thought it would be appropriate to fix this at once using a new helper

**Comment by CyrusNajmabadi** [comment]
> I thought it would be appropriate to fix this at once using a new helper

Would you like to submit a PR to that effect?  :) In the meantime, it would probably be good to open bugs to track any behavior you think needs improvement so that they don't get lost.  However, i would not gate any work being done on having to fix all issues at once, or having to pick any particular implementation.

**Comment by roryap** [comment]
This defect still exists in VS Pro as of 15.9.13.
