### ISSUE TITLE
UseInferredName offers incorrect fix

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25223]
When a variable is simplified when using With, a simplification of the variable, but rather than simplify it this suggests eliminating.
```VB
Dim form_ As Meform= New Meform With {
.Art = Art,
.Desc = Desc,
.dt = dt,
.AplicaID = AplicaID
}
```
SB suggests simplifying the variables: 
```VB
Dim form_ As Meform= New Meform With {
Art,
Desc,
dt,
AplicaID
}
```
when compiling this brand an error as it should lead '. ' before art.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/202181/error-intelisense.html
VSTS ticketId: 570972_
_These are the original issue comments:_

Ariel Yang - MSFT on 2/22/2018, 05:58 PM (10 days ago): <p>
</p><p>Translated from bing:</p><p>When a variable is simplified when using With, it suggests a simplification of the variable, but instead of simplifying it, it is deleting it.
<br>Dim form _ As Meform = New Meform With \{
. Art = Art,
. desc = desc,
. dt = DT,
. AplicaID = AplicaID
}
<br>Intelisense suggests simplifying variables:
<br>Dim form _ As Meform = New Meform With \{
Art,
Desc,
Dt,
AplicaID
}
<br>When compiling this marks an error because it must carry '. ' Before Art.<strong></strong><u></u><sub></sub><sup></sup></p>

_These are the original issue solutions:_
(no solutions)

**Comment by jcouv** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/23817 already.
