### ISSUE TITLE
ExternalReferences.Lenght equals 0 on macOS

### ISSUE THREAD

**Issue by SergeyChereshnyuk** [dotnet/roslyn#25222]
**Version Used**: 
Visual Studio for Mac Community, version: 7.3.3(build 23)
.NETFramework, Version=v4.6.1
macOS 10.12.6
Microsoft.CodeAnalysis.Common 2.6.1
Microsoft.CodeAnalysis.CSharp 2.6.1
Microsoft.CodeAnalysis.CSharp.Workspaces 2.6.1
Microsoft.CodeAnalysis.Workspaces.Common 2.6.1

**Steps to Reproduce**:
1. Create new .Net Console Project in Visual Studio for Mac
2. Add packages: 
                           Microsoft.CodeAnalysis.Common 2.6.1
                           Microsoft.CodeAnalysis.CSharp 2.6.1
                           Microsoft.CodeAnalysis.CSharp.Workspaces 2.6.1
                           Microsoft.CodeAnalysis.Workspaces.Common 2.6.1 
                           Microsoft.Build 15.6.82
                           Microsoft.Build.Framework  15.6.82
                           Microsoft.Build.Tasks.Core 15.6.82
                           Microsoft.Build.Utilities.Core 15.6.82
3. Write code:

```
 var workspace = MSBuildWorkspace.Create();
 workspace.AssociateFileExtensionWithLanguage("csproj", LanguageNames.CSharp);
  
 var solution = workspace.OpenSolutionAsync(_options.SolutionPath).Result;
 var project = solution.Projects.First();
 var cmp = project.GetCompilationAsync().Result;
         
  foreach(var references in cmp.ExternalReferences) // always cmp.ExternalReferences.Lenght equals 0 on macOS
  {
      Console.WriteLine(references.Display);
  }
```

**Expected Behavior**:
Windows10: Should be display name for each references of project. 
macOS: Should be display name for each reference for project.

**Actual Behavior**:
Windows10: Display list of references
macOS: No display, because cmp.ExternalReferences.Lenght equals 0

**Comment by jcouv** [comment]
Tagging @DustinCampbell to triage/route. Thanks

**Comment by CyrusNajmabadi** [comment]
Does this still repro?
