### ISSUE TITLE
NRE in Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#25237]
**Version Used**: 
VS 15.7

**Steps to Reproduce**:

1. Repo https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/Anycode
2. Branch Dev/rchiodo/add_logical_view_2
3. NuGet restore the main solution (src/Microsoft.VisualStudio.SLNX.sln) and then open in the IDE.

**Actual Behavior**:

Severity | Code | Description | Project | File | Line | Suppression State | Detail Description
-- | -- | -- | -- | -- | -- | -- | --
Error | AD0001 | Analyzer   'Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer'   threw an exception of type 'System.NullReferenceException' with message   'Object reference not set to an instance of an object.'. | Microsoft.VisualStudio.Workspace.Implementation |   | 1 | Active | Analyzer   'Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer'   threw the following exception:'Exception occurred with following   context:Compilation: Microsoft.VisualStudio.Workspace.ImplementationSyntaxTree:   F:\Anycode\Repo\src\Microsoft.VisualStudio.Workspace.Implementation\Workspace.csSyntaxNode:   return; [ReturnStatementSyntax]@[23344..23351)   (485,16)-(485,23)System.NullReferenceException: Object reference not set to   an instance of an object.   at   Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer.GetLeftmostCondition(SyntaxNode   node)   at   Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer.SyntaxNodeAction(SyntaxNodeAnalysisContext   syntaxContext)   at   Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2   data)   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer   analyzer, Action`1 analyze, TArg argument, Nullable`1 info)-----'.

**Comment by rchiodo** [comment]
Feel free to contact for a dmp or live repro if need be

**Comment by jasonmalinowski** [comment]
Also seeing this working in Roslyn itself. Got a few thousand hits if I had FSA on.

**Comment by jasonmalinowski** [comment]
```
Compilation: Microsoft.CodeAnalysis.Debugging.Package
SyntaxTree: F:\Projects\Roslyn\Open\src\Dependencies\CodeAnalysis.Debugging\CustomDebugInfoEncoder.cs
SyntaxNode: return; [ReturnStatementSyntax]@[2940..2947) (88,16)-(88,23)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer.GetLeftmostCondition(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer.SyntaxNodeAction(SyntaxNodeAnalysisContext syntaxContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by mavasani** [comment]
Seems to be introduced with https://github.com/dotnet/roslyn/commit/10726d10d8a88af000c925fa5e3f5776dd7cbf4d#diff-64e1a867f5d1363da7ca518cdb658623

**Comment by jinujoseph** [comment]
cc @alrz @CyrusNajmabadi

**Comment by mavasani** [comment]
@jasonmalinowski - do this require editing/broken code or it repros even with open solution and wait for FSA to complete?

**Comment by jasonmalinowski** [comment]
@mavasani I saw in projects I wasn't editing.

**Comment by 333fred** [comment]
This is reproing for me in Roslyn.sln

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/25258
