### ISSUE TITLE
Test plan for Improved Overload Candidates

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#25235]
Test plan for **Improved Overload Candidates**, aka **Bestest Betterness**.

Championed language proposal: https://github.com/dotnet/csharplang/issues/98
Initial implementation: https://github.com/dotnet/roslyn/pull/24756

## General
- [ ] No change to overload resolution with `/langversion=7.2`
  - [x] Run test pass with `LanguageVersion.Latest = CSharp7_2` to verify (Neal: done 2018-03-19. Many minor changes to the character range associated with the diagnostics for overload resolution changes where the source is still an error. It failed final verification before but now failed to find a candidate; we give the same error message, but where we used to point to the whole invocation, now we point just to the method being invoked. The tests expect the C# 7.3 location but the errors are at the C# 7.2 location)
- [ ] If overload resolution does not find a matching candidate after dropping candidates with new rules, all candidates are considered for error reporting, unchanged from 7.2 (Neal: Roughly correct, verified in all modified tests which test old and new versions. However, these new failure reasons are prioritized for reporting purposes so we generate the same diagnostic that we previously used to report during final validation. It is easy to identify these apparently unaffected but technically affected tests because it changes the character range on which the diagnostic is reported. See https://github.com/dotnet/roslyn/pull/24756)

## Instance and static members
- [ ] Overload resolution ignores _static_ methods and indexed properties when (Indexed properties are not relevant. C# does not support static indexed properties. Soon see `IndexedPropertyTest01`)
  - [ ] invoked with an explicit receiver (see `TestInstanceReceiver01`)
  - [ ] invoked with `this` or `base` (soon see `TestInstanceReceiver02`)
  - [ ] implicitly invoked `Add()` method in a collection initializer (soon see `TestInstanceReceiver03`)
  - [ ] implicitly invoked `GetEnumerator()` and `MoveNext()` in `foreach` (soon see `TestInstanceReceiver04` and `TestInstanceReceiver05`)
  - [ ] implicitly invoked `Deconstruct()` (soon see `TestInstanceReceiver06`)
  - [ ] implicitly invoked `GetAwaiter()` and `GetResult()` for `await` (soon see `TestInstanceReceiver07` and `TestInstanceReceiver08`)
  - [ ] implicitly invoked method from LINQ query on instance (soon see `TestInstanceReceiver09`)
- [ ] Overload resolution ignores _instance_ methods and indexed properties when
  - [ ] invoked with an explicit type qualifier and with no field or property with the same name as the type (see `TestStaticReceiver01` and others)
  - [ ] invoked without a qualifier in a static member (see `TestStaticContext01`)
  - [ ] invoked without a qualifier in a field initializer or property initializer (see `TestStaticContext02`)
  - [ ] invoked without a qualifier in a constructor initializer `this(...)` or `base(...)` (see `TestStaticContext04`)
  - [ ] invoked without a qualifier in an attribute argument (see `TestStaticContext05`)
  - [ ] invoked without a qualifier in a default parameter value (Not so. soon see `TestStaticContext06`. Though today it doesn't make any difference for legal programs, a parameter default value is not a static context in an instance method. That will remain so in order to support the proposal for "with" methods in records.)
  - [ ] implicitly invoked method from LINQ query on type (see `QueryTests.QueryOnLambda`)
- [ ] Overload resolution considers both instance and static methods and indexed properties (unchanged from 7.2) when
  - [ ] invoked without an explicit receiver in instance method (see `TestInstanceContext01`)
  - [ ] invoked with an explicit type qualifier with a field or property with the same name as the type (see `TestAmbiguousContext01`)
- [ ] `SymbolInfo.CandidateSymbols` will include all overloads on failure, including those that would be dropped on success, unchanged from 7.2 (soon see `TestAmbiguous01`)
- [ ] IDE Name Simplification
  - [ ] should not offer to remove receiver from `this.F(...)` or `base.F(...)` if an ambiguous static overload exists
  - [ ] should not offer to remove type qualifier from `Type.F(...)` if an ambiguous instance overload exists
  - [ ] should offer to remove type qualifier from `Type.F(...)` in static contexts (such as field or constructor initializer) even when an instance overload exists

## Constraints not satisfied
- [ ] Overload resolution with generic methods ignores methods where type arguments do not satisfy constraints when
  - [ ] type arguments are implicit (see `TestConstraintFailed01` et al)
  - [ ] type arguments are explicit (see `OverloadResolutionTests.TestConstraintViolationApplicabilityErrors`)
- [ ] Overloads for `ref struct` and `T*` can be invoked successfully even when generic overloads exist since `ref struct` and `T*` are not valid type arguments (see `TestConstraintFailed04`, `TestConstraintFailed05`)
- [ ] `SymbolInfo.CandidateSymbols` will not include methods where type arguments do not satisfy constraints (It does include all overloads on failure. We don't remove "filtered-out" candidates today and this PR doesn't change that. Soon see `TestAmbiguous02` and `TestAmbiguous03`)

## Method group return type or `ref` mismatch
- [ ] Method group conversion ignores
  - [ ] methods for which there is not an identity or implicit reference conversion from the method return type to the delegate type (see `TestReturnTypeMismatch01` et al)
  - [ ] methods that are `ref` returning if the delegate is not `ref` returning (see `TestReturnRefMismatch01`)
  - [ ] methods that are not `ref` returning if the delegate is `ref` returning (soon see `TestReturnRefMismatch02`)
- [ ] **`SymbolInfo.CandidateSymbols` will not include methods that do not match delegate return type** or `ref` (it *will* include them, as we do not remove "filtered" candidates today; soon see `TestAmbiguous04`)

**Comment by cston** [comment]
cc @gafter

**Comment by gafter** [comment]
@cston I've tagged each bullet with a satisfying test.

**Comment by gafter** [comment]
@cston I think this can be closed; there are tests for all items.
