### ISSUE TITLE
Auto-Implemented Property Accessor-Targeted Attributes

### ISSUE THREAD

**Issue by IlyaGrebnov** [dotnet/roslyn#25236]
Unable to apply MethodImpl attribute to Expression-bodied Property Get. Tested with latest version of VS 2017.15.6.0.

Note, program is for illustration purpose only and have no real value.

    class Program
    {
        public int Working1
        {
            [MethodImpl(MethodImplOptions.NoInlining)]
            get { return 1; }
        }

        public int Working2
        {
            [MethodImpl(MethodImplOptions.NoInlining)]
            get;
        } = 3;

        public int Working3
        {
            [MethodImpl(MethodImplOptions.NoInlining)]
            get => 2;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        public int NotWorking1 => 2;

        static void Main(string[] args)
        {
        }
    }

Expected Behavior: Program compiles.

Actual Behavior: Error CS0592 Attribute 'MethodImpl' is not valid on this declaration type. It is only valid on 'constructor, method' declarations.

**Comment by jcouv** [comment]
Issue moved to [dotnet/csharplang #1355](https://github.com/dotnet/csharplang/issues/1355) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jcouv** [comment]
Moved the issue to csharplang, as I can find the requested behavior in the current [language spec](https://github.com/dotnet/csharplang/blob/6027ad5a4ab013f4fb42f5edd2d667d649fe1bd8/spec/attributes.md#attribute-specification) for attributes.
