### ISSUE TITLE
'Open Active Rule Set' doesn't work for existing project

### ISSUE THREAD

**Issue by djohnst10** [dotnet/roslyn#2524]
I have a fairly large existing Visual Studio solution with around 58 projects where, when I open the solution in VS 2015 Enterprise RC, I can't open the active rule set from either the project's Code Analysis property page or the context menu on the Analyzers node in the project's references.

The Code Analysis property page will return an error message when you click the Open button beside the Rule Set selector.

> An error occurred while loading the ruleset file “C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Static Analysis Tools\Rule Sets\MinimumRecommendedRules.ruleset.
>
> Object reference not set to an instance of an object.

![image](https://cloud.githubusercontent.com/assets/2738319/7480155/9784781c-f334-11e4-805e-4b8323c0f3d9.png)

The error message does not reappear if the Open button is clicked again.

A similar error occurs if I select 'Open Active Rule Set' from the context menu for the Analyzers node under references in the project in Solution Explorer. The error messages:

> The rule set file could not be opened.
>
> The parameter was incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

![image](https://cloud.githubusercontent.com/assets/2738319/7480219/2898fe18-f335-11e4-9625-39ed73bab01d.png)

This error message will appear each time I select 'Open Active Rule Set'.

Everything works fine when I do either of these things in an new project created in VS 2015 Enterprise RC.

My solution has C# web projects, C# class library projects, C# and VB executable projects, SQL Server database projects, a couple of WiX projects, and a Powershell project.

**Comment by tmeschter** [comment]
PowerShell projects don't support all parts of the project system that the rule set editor looks at. Specifically, when enumerating the set of `EnvDTE.Configuration` items in `EnvDTE.Project.ConfigurationManager` the `Properties` property is unexpectedly `null`. I'll need to harden the rule set edit against this.

**Comment by tmeschter** [comment]
The underlying issue has been fixed in Roslyn and in the rule set editor.
