### ISSUE TITLE
Improvements for Invert If refactoring 

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#25241]
Suggest we do the following improvements for the Invert If refactoring that will be enable with https://github.com/dotnet/roslyn/pull/25233.  

- [ ]  Handle elseless ifs - in progress https://github.com/dotnet/roslyn/pull/24649- 

- [ ]  Offer more code fix options for compound conditionals, for example
`if ((A || B) && (C || D))` would offer the following choices for the negated conditional in the code fix:
    - negation is not distributed across the conditional `!((A || B) && (C || D))`
    - negation is completely distributed across the conditional `((!A && !B) || (!C && !D))`

- [ ]  For VB, currently we don't handle if statements that contain elseif blocks.  We should offer refactoring on all ifs and elseifs.  For example:
    ```vbnet
    If a Then
        aMethod()
    ElseIf B Then
        bMethod()
    ElseIf C Then
        cMethod()
    Else
        dMethod()
    End If
    ```
would offer to invert if on the `If` keyword and both `ElseIf` keywords

- [ ] Invert conditional operator.  ```condition ? first_expression : second_expression;``` 
- [ ] Move negation code to the abstract layer using IOperation

Other related refactorings:
- [ ] Negate conditional
- [ ] Distribute negation
- [ ] Remove Else clause if it is unreachable

**Comment by alrz** [comment]
>Distribute negation

I guess this is not exactly `if`-related, a couple of other refactorings in the "operator" level:

- flip operands (I'd use this a lot)
- convert `if (a && b)` to `if (a) if (b)`
- convert `if (a || b)` to `if (a) else (b)`

**Comment by CyrusNajmabadi** [comment]
> convert if (a && b) to if (a) if (b)

And vice-versa!

**Comment by CyrusNajmabadi** [comment]
> Handle elseless ifs 

Already supported.

> negation is not distributed


It is now:

![image](https://user-images.githubusercontent.com/4564579/217639527-3d99f9f4-7ce7-4843-be0d-9b99cbdf5797.png)
