### ISSUE TITLE
Breakpoint doesn't bind in store app

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#2525]
Windows 8.1 (hub) store app, ```Windows.UI.Xaml.Application.Start```.  I also tried with the parameter type.  I can invoke the method in the Immediate window, so I don't think it's an ambiguity issue.

**Comment by amcasey** [comment]
Looks like the method is actually native, which would explain the C# behavior.  I'll file a debugger bug about not being able to bind it as C++.

**Comment by MattGertz** [comment]
Verifying as external.
