### ISSUE TITLE
Feature Request: assembly name and path with navigation to decompiled source

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#25252]
**Version Used**: 

VS 2017 15.6.0

**Steps to Reproduce**:

"navigation to decompiled sources" disabled:

![image](https://user-images.githubusercontent.com/3760955/37016246-a16ee9fc-214e-11e8-9c9c-b3e3566d11b1.png)

enabled:

![image](https://user-images.githubusercontent.com/3760955/37016273-c22e0790-214e-11e8-9990-e8eecdf34745.png)

I want the decompiled sources to have assembly name and path information too.

```cs
#region Assembly System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Runtime.dll
#endregion
```

**Comment by sharwell** [comment]
Fixed in #25420
