### ISSUE TITLE
error MSB4064: The "EmbedAllSources" parameter is not supported by the "Csc" task

### ISSUE THREAD

**Issue by ijsgaus** [dotnet/roslyn#25257]
**Version Used**:  Visual Studio 2017 version 15.6 Release

Microsoft.CSharp.Core.targets : error MSB4064: The "EmbedAllSources" parameter is not supported by the "Csc" task

**Comment by Pulits** [comment]
I am also experiencing this, none of my current solutions work now. I tried removing the Microsoft.Net.Compilers package from the .csproj with no success.

**Comment by tmat** [comment]
Any chance you have multiple different VS versions on the machine?

**Comment by ijsgaus** [comment]
I delete string with EmbedAllSources in Microsoft.CSharp.Core.targets. This help,  but ...

**Comment by ijsgaus** [comment]
@tmat no chance. VS Pro 2017

**Comment by ijsgaus** [comment]
Yes, this was in beta, last comment. I have this problem in complex solution, where present ASP.NET MVC (not core). multitargeting to Net471 and Netstandard2.0, In class library code too

**Comment by ijsgaus** [comment]
I think, this is mistake of build release. Same problem was been in previous release, patched by use new prerelease compiler package.

**Comment by lukemcnally** [comment]
I've experienced the same issue. As suggested above, removing the "EmbedAllSources" attribute from the "Csc" tag in the Microsoft.CSharp.Core.targets file allows me to build again. Any ETA on an official fix for this?

**Comment by chucker** [comment]
@lukemcnally are you on an ASP.NET project? If so, try explicitly referencing the NuGet package `Microsoft.Net.Compilers` 2.7 or newer.

**Comment by lukemcnally** [comment]
Hi @chucker, thanks for the quick reply. No we're experiencing the problem with Xamarin.Forms iOS and Android projects.

**Comment by chylex** [comment]
This is happening in a .NET Framework unit test project, because Visual Studio's unit test projects import `Microsoft.CSharp.targets`. No references to `Microsoft.Net.Compilers` anywhere.

**Comment by jaredpar** [comment]
This should be fixed in the latest VS now. I believe there was a spike of this during the initial release do to lag in how ASP.NET was acquiring some of our packages. Now though it should all be in sync.
