### ISSUE TITLE
Compiler generated selectors for Linq queries in C# use regular IObjectCreationOperation instead of IAnonymousObjectCreationOperation

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#25268]
Examine shape of SelectMany selector in base-line for existing unit-test TransparentIdentifiers_FromLet_IOperation in src\Compilers\CSharp\Test\Semantic\Semantics\QueryTests.cs

```
 IObjectCreationOperation (Constructor: <anonymous type: System.Int32 x, System.Int32 y>..ctor(System.Int32 x, System.Int32 y)) (OperationKind.ObjectCreation, Type: <anonymous type: System.Int32 x, System.Int32 y>, IsImplicit) (Syntax: 'from int y in c2')
    Arguments(2):
        IArgumentOperation (ArgumentKind.Explicit, Matching Parameter: x) (OperationKind.Argument, Type: null, IsImplicit) (Syntax: 'from int y in c2')
          IParameterReferenceOperation: x (OperationKind.ParameterReference, Type: System.Int32, IsImplicit) (Syntax: 'from int y in c2')
          InConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
          OutConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
        IArgumentOperation (ArgumentKind.Explicit, Matching Parameter: y) (OperationKind.Argument, Type: null, IsImplicit) (Syntax: 'from int y in c2')
          IParameterReferenceOperation: y (OperationKind.ParameterReference, Type: System.Int32, IsImplicit) (Syntax: 'from int y in c2')
          InConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
          OutConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
    Initializer: 
    null
 ```

Observed:
Even though this represents creation of an instance of an Anonymous Type, the node is  IObjectCreationOperation rather than an IAnonymousObjectCreationOperation. Semantically this is accurate, but some useful information is not exposed and left for the consumer to figure out. In particular, it is hard to say what properties are being initializer with values passed as constructor arguments. Also, a simple direct serialization of the IObjectCreationOperation into syntax will never produce valid syntax because Anonymous Types cannot be explicitly named and, therefore, their constructors cannot be explicitly invoked. The only valid way to represent this in syntax is to use an Anonymous Type creation expression, which is usually mapped to IAnonymousObjectCreationOperation.

Expected: 
IAnonymousObjectCreationOperation node. BTW, this is what happens for VB.

I believe this issue is blocking for "Linq query to method calls" refactoring feature.

CC @dotnet/analyzer-ioperation, @ivanbasov

**Comment by ivanbasov** [comment]
Required for https://github.com/dotnet/roslyn/pull/24759
The root work item for LINQ Conversion is https://github.com/dotnet/roslyn/issues/8953
