### ISSUE TITLE
"Deconstruct variable declaration" introduces error.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#25260]
Start with code:

```c#
        (int x, int y) t = default;
        Console.WriteLine(t.x + t.y);
```

Use 'Deconstruct variable declaration' on 't'.  It produces the following code:

```c#
        (int x, int y) = default;
        Console.WriteLine(x + y);
```

This is not allowed because 'default' is not deconstructable to a tuple.

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv

**Comment by Neme12** [comment]
This is not specific to default. See another repro with an implicit conversion:
```c#
using System;

public class Class1
{
    class EvilClass
    {
        public static implicit operator (int, int)(EvilClass c)
        {
            return (0, 0);
        }
    }

    public static void Main()
    {
        (int x, int y) t = new EvilClass();
        Console.WriteLine(t.x + t.y);
    }
}
```

So the fix to this shouldn't involve a special handling of `default`.

**Comment by CyrusNajmabadi** [comment]
I'm not sure the above case is relevant.  If you have a deconstruct and an implicit tuple conversion that don't behave the same, then your code is likely going to cause problems no matter what.  If addressing that case is complex, then it's fine to not bother as it's too unlikely to occur in practice.

**Comment by Neme12** [comment]
@CyrusNajmabadi  But there's only an implicit conversion in that case and no deconstruction on EvilClass.
I think the solution would be to not offer the code fix if the type of the expression itself is not a tuple as well or by checking for a conversion.

**Comment by CyrusNajmabadi** [comment]
Oh sorry, i assumed you were describing a situation where the type has a deconstruct and also an implicit conversion, which *differed* in behavior (hence 'evil').  Yes.  i agree that if there is no actual available Deconstruct method, the fix would not be offered here.  That's not an 'evil' case to me.  That's just someone who prefers conversions.

**Comment by Neme12** [comment]
Ok sorry for the name... I guess I named it "evil" because it breaks the code fix.

**Comment by CyrusNajmabadi** [comment]
Or, in other words, it's sufficient to just check for a viable .Deconstruct to address the problem for me.  The presence of implicit operators and hte concern that they might behave differently (evily)  isn't that important.

**Comment by CyrusNajmabadi** [comment]
No worries.  I should have paid more attention.  :)

**Comment by Neme12** [comment]
@CyrusNajmabadi I'm not sure if it's a good approach to look for deconstruct methods given that this code fix only works with tuples and no other types regardlss of deconstruct methods.

**Comment by Neme12** [comment]
I think I have a working solution for this, but:
the existing tests contain this:
```c#
class C
{
    void M()
    {
        (int name, int age) [|t1|] = GetPerson();
        Console.WriteLine(t1.name + "" "" + t1.age);
    }

    (string name, int age) GetPerson() => default;
}
```
Notice the type mismatch - (string, int) vs (int, int). Under my solution the analyzer wouldn't fire here. Is that acceptable? Was the type mismatch intentional?

**Comment by Neme12** [comment]
My solution would be to check that the original type of the expression is an equivalent type.

**Comment by Neme12** [comment]
But now I realize that's not a good solution either because you do want the code fix here:
```c#
 (int a, int b) = getData();
(byte, byte) getData() => (0, 0);
```

**Comment by Neme12** [comment]
Well this can now be reopened... turns out I didn't actually fix it.
