### ISSUE TITLE
Enum reference all blue in intellisense tooltip

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#25263]
**Version Used**:  2.7.0.62620 (15.6,0 Preview 7)

**Steps to Reproduce**:

![ss](https://user-images.githubusercontent.com/10546952/37034676-ffe45d26-2141-11e8-910f-e8e263e42d0d.png)

**Expected Behavior**: FileAccess.Write to match the FileMode.Append colors

**Actual Behavior**: FileAccess.Write all blue

**Comment by CyrusNajmabadi** [comment]
This is a problem with the doc comments for that type.  The doc comments contain `<see langword="FileAccess.Write" />` which we render as blue.  Nothing roslyn can do here.
