### ISSUE TITLE
Completion should probably preselect shorter names

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#25283]
Create a new console app. Inside Main method, type `C`.
Expected behavior: Preferrably I get `Console`, but at the very least I would expect something a little less specific than this:
![image](https://user-images.githubusercontent.com/11444821/37064489-70b0beae-219d-11e8-8083-8bb3ecbe54e5.png)

Type `Co`. Expected behavior: I get `Console`. Actual competion: `Comparer<>`

What if completion preselected the shortest item as opposed to the first one by alphabet order?

**Comment by CyrusNajmabadi** [comment]
You should get Console once Console is in your MRU.  In the absence of any signals, preselecting the shortest *might* be what people want.  Or it might not be.  It's unclear to me why something shorter would be better than something longer.

**Comment by Neme12** [comment]
@CyrusNajmabadi 
> It's unclear to me why something shorter would be better than something longer.

Because it's a shorter edit distance. It seems like a reasonable default to me (whereas selecting the longest thing in the completion list after typing just 1 letter seems rather silly). But maybe it is just my feeling, I don't have any data on this of course. This would have to be tried out.

**Comment by Joe4evr** [comment]
Technically it's preselecting the first item in alphabetical order. It just so happens that the first item that starts with a `C` is very long compared to other types/snippets.

**Comment by Neme12** [comment]
@Joe4evr  I know. My suggestion is that it would preselect the shortest item.

**Comment by CyrusNajmabadi** [comment]
One nice behavior of today is that it selects the top of the list, making it very easy for you to just "down down down" to navigate through them.  I'm worried that if we jump into some middle section it could make things more confusing for users (albeit in a very hard to recognize manner).

**Comment by Joe4evr** [comment]
@Neme12 Solution: Create a type named `System.C`. *BOOM!* Shortest item is preselected first. :rofl:
