### ISSUE TITLE
ubuntu_16_mono_debug_prtest  in CI

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#25285]
https://ci.dot.net/job/dotnet_roslyn/job/dev15.7-preview1-vs-deps/job/ubuntu_16_mono_debug_prtest/3/

```
15:58:37 [91mE: Version '5.8.0.108-0xamarin1+ubuntu1604b1' for 'mono-devel' was not found
15:58:37 [0mThe command '/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF &&     (echo "deb http://download.mono-project.com/repo/ubuntu stable-xenial main" |     tee /etc/apt/sources.list.d/mono-official.list) &&     apt-get update &&     apt-get install -y mono-devel=5.8.0.108-0xamarin1+ubuntu1604b1 &&     apt-get clean' returned a non-zero code: 100
```

**Comment by tmat** [comment]
@jaredpar

**Comment by jaredpar** [comment]
CC @angocke, @333fred

**Comment by jaredpar** [comment]
CC @agocke

**Comment by agocke** [comment]
Looks like this branch hasn't merged recently.

**Comment by 333fred** [comment]
@tmat, we need to cherry-pick https://github.com/dotnet/roslyn/pull/25071/commits/c0268736fd24954beb5817148089ee3803abe8f3 to that branch. @agocke, do you want to take care of that?

**Comment by agocke** [comment]
@333fred No, I think that's a job for Tiger.

**Comment by 333fred** [comment]
@Shyam-Gupta, that's you this sprint. Can you cherry-pick that commit over to dev15.7-preview1, which will then flow to -vs-deps? Looks like you'll need both https://github.com/dotnet/roslyn/pull/25005 and https://github.com/dotnet/roslyn/pull/25071.

**Comment by Shyam-Gupta** [comment]
Did cherry-pick of the change to dev15.7-preview1.
Please review the PR: https://github.com/dotnet/roslyn/pull/25339

**Comment by jasonmalinowski** [comment]
I believe this has flowed everywhere we care now.
