### ISSUE TITLE
Annoying completion when adding pattern conditional in front of expression

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#25293]
When inserting some code into an existing expression, I find it common to get an annoying completion when trying to type `null`.
For example, if you want to make a declaration into a conditional (from `var x = z;` to `var x = something is null ? y : z;`), `null` is not offered.

![image](https://user-images.githubusercontent.com/12466233/37071882-9b13422c-2173-11e8-8ff0-062696253561.png)

Tagging @Neme12 who is fixing some other completion issues with patterns.

**Comment by CyrusNajmabadi** [comment]
One thing @Neme12 and i discussed was that snippets with the same name as keywords should not be offered unless that same *keyword* is also offered there.  So something like the "namespace" snippet would not be offered unless it was a place that the LS would also offer the "namespce" keyword.

that would help here.

Note: this doens't mean your scenario will get better.  It depends on 'null' being the best match for when you typing 'n'.  if, for example, the language adds any other 'n' keywords, you would have this same issue.

**Comment by Neme12** [comment]
@CyrusNajmabadi The problem here seems to be that 'null isn't offered at all (so even if you type it out, you'll end up with 'namespace').

**Comment by CyrusNajmabadi** [comment]
Fix it!  :)

**Comment by Neme12** [comment]
This seems to be fixed in my branch #25133.

**Comment by CyrusNajmabadi** [comment]
Curious.  What about that branch would change this behavior?

**Comment by Neme12** [comment]
It should also be covered by existing tests I have added:
`if (i is $$ int`
``if (i is $$ 1`

**Comment by Neme12** [comment]
@CyrusNajmabadi 
Because I did the same thing for a pattern `case`, I made sure there is a constant expression context after `is` too. I think I originally did that because I saw things offered that couldn't be constants, but it also fixed completion after a pattern `is` (I made sure I tested both cases). Previously the completion for `null` would have only been handled by the expression context that is set inside every binary expression (which `is` is).

**Comment by Neme12** [comment]
When you type `var x = something is n$$ z;`, this is a declaration pattern so that's why `null` wasn't offered.

**Comment by CyrusNajmabadi** [comment]
Ah, i see.  You're treating pattern contexts as places where constants go.  Makes sense.

**Comment by CyrusNajmabadi** [comment]
Note: you can probably simplify the NullKeywordRecommender because of this.  It looks like it will not need the ```IsInSelectCaseContext(context, cancellationToken)``` anymore because of your change.  Right?

**Comment by Neme12** [comment]
Yes, you're right, I did that too at the end. But it could have left the logic inside IsConstantExpressionContext as well. After all it's just 2 cases.

**Comment by Neme12** [comment]
@CyrusNajmabadi Looking at that, it has some interesting logic:
https://github.com/dotnet/roslyn/blob/6847f1e5a909395aae9456e8f366cbf4deb86b69/src/Features/CSharp/Portable/Completion/KeywordRecommenders/NullKeywordRecommender.cs#L36-L45

which I already invalidated though because it is caught by IsAnyExpressionContext.

**Comment by CyrusNajmabadi** [comment]
Yes.

**Comment by Neme12** [comment]
Yes what? Do you think it's not useful?

**Comment by CyrusNajmabadi** [comment]
Yes.  i think it's not useful.  It's been subsumed by your current work, so i would just remove it :)

**Comment by Neme12** [comment]
Actually, it seems the code was already dead before. IsConstantExpressionContext was already returning true for after 'case'.

![image](https://user-images.githubusercontent.com/11444821/37083728-b66a5196-21f0-11e8-9e77-19f07236562a.png)

**Comment by CyrusNajmabadi** [comment]
Yes.  I would just remove at this point.

**Comment by Neme12** [comment]
@CyrusNajmabadi And besides, null is actually legal in that context anyway. Consider:
```c#
switch (true)
{
    case null == null:
        break;
}
```
