### ISSUE TITLE
Tool to generate a hyperlinked grammar.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#25298]
@ljw1004 wrote a while back a version Hyperlinked implementation of the [vb and c grammar](https://blogs.msdn.microsoft.com/lucian/2010/04/19/vb-and-c-grammar-for-vs2010/).
We should include a version in the respective repositories. It would make exploring the grammar little easier.
Even better if there was a tool to generate them from the `syntax.xml` and `bound.xml`.

**Comment by gafter** [comment]
Language grammars and tools for managing or visualizing them are not part of the Roslyn project.

Neither Syntax.xml nor BoundNodes.xml represent the language grammar.
