### ISSUE TITLE
Introduce Local: trigger the refactoring with a cursor position but no selection

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#25292]
Currently, you have to select the whole expression that you want to introduce a local for. For example, `[|x.Field.Method()|]`.
But I think in most cases, if not all, it should be possible to trigger from just a cursor position, such as `x.Field.Meth$$od()`.

**Comment by CyrusNajmabadi** [comment]
i would def be concerned about this causign the refactoring to show up too much.
