### ISSUE TITLE
If you choose "No" to the decompiler prompt, you get asked continually for every "Go To Definition"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#25299]
1. CTRL+Click a symbol that is defined outside of your project
2. Click No to the decompile prompt
3. CTRL+Click another symbol that is defined outside of your project

**Expected:** Not to get prompted
**Actual:** Get prompted again

**Comment by CyrusNajmabadi** [comment]
We fixed this to not prompt like this anymore.
