### ISSUE TITLE
Incorrect remove-cast suggestion

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#253]
Ported from TFS WorkItem: <b>1113223</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P>Add the following code to the end of the declaration of CompilationContext (i.e. inside the class) in Closed\ExpressionEvaluator\VisualBasic\Source\ExpressionCompiler\CompilationContext.vb</P>
<P>&nbsp;</P><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">
<P></FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Friend</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Shared</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Sub</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> Test(arg </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">As</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Object</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">)</P>
<P></FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Dim</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> identity = </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">If</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">(</FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT style="BACKGROUND-COLOR: #ffff00" color=#0000ff size=1 face="Courier New">TryCast</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">(arg, </FONT></FONT><FONT color=#2b91af size=1 face="Courier New"><FONT color=#2b91af size=1 face="Courier New"><FONT color=#2b91af size=1 face="Courier New">B</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">)?.A, </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">TryCast</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">(arg, </FONT></FONT><FONT color=#2b91af size=1 face="Courier New"><FONT color=#2b91af size=1 face="Courier New"><FONT color=#2b91af size=1 face="Courier New">A</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">))</P>
<P></FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">End</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Sub</P></FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">
<P></FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Class</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#2b91af size=1 face="Courier New"><FONT color=#2b91af size=1 face="Courier New"><FONT color=#2b91af size=1 face="Courier New">A</P></FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">
<P></FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">End</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Class</P></FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">
<P></FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Class</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#2b91af size=1 face="Courier New"><FONT color=#2b91af size=1 face="Courier New"><FONT color=#2b91af size=1 face="Courier New">B</P></FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">
<P></FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Public</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">ReadOnly</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Property</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> A </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">As</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#2b91af size=1 face="Courier New"><FONT color=#2b91af size=1 face="Courier New"><FONT color=#2b91af size=1 face="Courier New">A</P></FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">
<P></FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">End</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Class</P></FONT></FONT></FONT>
<P>&nbsp;</P>
<P>Expected: No offer to remove cast</P>
<P>Actual: Offers to remove <FONT style="BACKGROUND-COLOR: #ffff00">this </FONT>cast.</P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By Andrew Casey (ROSLYN) (1/22/2015 6:18:10 PM)

<p>For some reason, I have been able to repro this in a standalone project, but none of the types are roslyn types.</p>
<p>&nbsp;</p>
<p>I'm guessing it's related to the conditional access operator.</p>

------------------------------

**Comment by mavasani** [comment]
Andrew, can you please verify the fix for your repro?

**Comment by amcasey** [comment]
Cast is not grayed out in today's build.
