### ISSUE TITLE
Decompilation inconsistently uses keywords in decompiled code

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#25302]
1. Create Console App (.NET Framework)
2. Create Console App (.NET Core)
3. In the following code, CTRL+Click `int` in both projects

``` C#
    class Program
    {
        static void Main(string[] args)
        {
            int foo;
        }
    }
```

In .NET Framework you get:

``` C#
	public struct Int32 : IComparable, IFormattable, IConvertible, IComparable<int>, IEquatable<int>
```

In .NET Core you get:

``` C#
	public struct Int32 : IComparable, IFormattable, IConvertible, IComparable<Int32>, IEquatable<Int32>
```

**Comment by sharwell** [comment]
@siegfriedpammer is this a known issue?

**Comment by siegfriedpammer** [comment]
@sharwell Which branch should I use for debugging?

**Comment by sharwell** [comment]
@siegfriedpammer Either **master** or **dev15.7.x**. After cloning run Restore.cmd and then set VisualStudioSetup.Next as the startup project.

**Comment by siegfriedpammer** [comment]
I cannot reproduce this. On my machine the output is always:

	public struct Int32 : IComparable, IComparable<int>, IConvertible, IEquatable<int>, IFormattable

That being said, using `int` everywhere (except for the name of the struct) is the expected / intended output.

**Comment by siegfriedpammer** [comment]
@davkean @sharwell Would it be possible for you to post the name/path to the assembly which was loaded by VS during decompilation.? I am unable to reproduce this bug without knowing which assembly was decompiled on your machine. As noted above, it seems that in my setup a different assembly was used, which did not trigger this bug. Thank you very much!

**Comment by sharwell** [comment]
I can confirm @siegfriedpammer's conclusions. This problem occurs because the ILSpy integration included in the 15.7 release fails to decompile `Int32` from **System.Runtime** (.NET Core), and instead falls back to Metadata as Source.

**Comment by davkean** [comment]
So this was closed because?

**Comment by davkean** [comment]
But this would be a metadata as source bug then, right?

**Comment by sharwell** [comment]
No, Metadata as Source is also consistent: it always uses the predefined type names.

**Comment by davkean** [comment]
I'm very confused, what generates:

```
public struct Int32 : IComparable, IFormattable, IConvertible, IComparable<Int32>, IEquatable<Int32>
```

**Comment by sharwell** [comment]
From our attempts to reproduce this issue, it seems the Metadata As Source feature generates that. It's the experience you get when decompilation is disabled in options.
