### ISSUE TITLE
Remove "Brace Matching" color and reuse "Brace Matching (Highlight/Rectangle)"

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#2530]
In https://github.com/dotnet/roslyn/pull/2520, we added a "Brace Matching" color to work around an editor bug that prevents us from reusing the "Brace Matching (Highlight)" and "Brace Matching (Rectangle)" colors.

This is problematic because now there are even more BraceMatching-related settings in Fonts & Colors and it's unclear which ones work when. Ideally we'd get rid of this new "Brace Matching" color by either
- Fixing the editor bug
- Finding a way to reuse the existing colors, perhaps as part of our existing [HACK_ThemeColorFixer](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/HACK_ThemeColorFixer.cs,3abb4302b0856100)

**Comment by dpoeschl** [comment]
Would we even want to do this now? We've shipped, and people who care about these colors have probably already adapted to the new colors -- switching back would just get in the way of these users. @Pilchie - Can we close this?

**Comment by Pilchie** [comment]
Yeah, you're probably right.
