### ISSUE TITLE
VB: Smart indent issue with argument lists

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#25323]
**Version Used**: 15.7.0 Preview 1.0 [27506.1.d15.7]

The here is that VB smart indent for argument lists is *always* based on the position of the first argument, regardless of where other arguments are positioned.

**Steps to Reproduce**:

1. Create Visual Basic Console App project
2. Add the following line of code to `Main()`:

``` VB
Console.WriteLine("{0} + {1} = {2}", 19, 23, 19 + 23)
```

3. Place the editor caret before the second argument (`19`) and press ENTER. Then, unindent until the remaining arguments start one tab to the left of `Console`:

``` VB
Console.WriteLine("{0} + {1} = {2}",
    19, 23, 19 + 23)
```

4. Place the editor caret before the third argument (`23`) and press ENTER.

**Expected Behavior**:

The indentation should be aligned with the second argument.

``` VB
Console.WriteLine("{0} + {1} = {2}",
    19,
    23, 19 + 23)
```

**Actual Behavior**:

The indentation is always aligned with the first argument, regardless of where subsequent arguments are positioned.

``` VB
Console.WriteLine("{0} + {1} = {2}",
    19, 
                  23, 19 + 23)
```

Note that this happens for every single argument after the first one. If the user wants a different indentation level, the IDE fights them by trying to force every argument to align with the first argument.

**Comment by jinujoseph** [comment]
fixed via #25344
