### ISSUE TITLE
Better alternatives to MSIL and JIT?

### ISSUE THREAD

**Issue by simonegli8** [dotnet/roslyn#2532]
I don't know how old MSIL is, but aren't there better alternatives to it, like compressed syntax trees? Has Microsoft done any research on it? And as for JIT, has your team tried trace tree compilation? 
I'd suggest you connect with Michael Franz from UIC Irvine, he pioneered a compressed syntax tree compiler two years before Java came up, and has done a lot of research also on trace tree compilation. I think the Mozilla Javasript engine is from him.

From one of his (old) abstracts:
Trace-based compilation is a technique used in managed language runtimes to detect and compile frequently executed program paths. The goal is to reduce compilation time and improve code quality by only considering "hot" parts of methods for compilation. Trace compilation is well suited for interpreter-based execution environments because the control flow of an application program is highly visible and recordable. In this paper, we show that trace compilation is also feasible and beneficial in runtime environments without interpreters where it is more difficult to monitor the control flow of an application.

We present the implementation of Maxpath, a trace-based Java just-in-time compiler for the meta-circular Maxine virtual machine. Maxine uses a tiered compilation strategy where methods are first compiled with a non-optimizing just-in-time compiler in order to collect profiling information, and then recompiled with an optimizing compiler for long-term efficient execution. We record traces by dynamically inserting instrumentation code in non-optimized methods. Execution traces are first collected into trace regions, after which they are compiled, optimized and linked to non-optimized methods for efficient execution. We show that trace-based compilation is an effective way to focus scarce compilation resources on performance critical application regions.

His website is here:
www.michaelfranz.com

PS:
If you want to be the best programmer you can be, pray for wisdom ;-) I once solver a 3 days debugging session in just 10 minutes finding about 5 errors this way.

**Comment by gafter** [comment]
@simonegli8 Can you please submit a pull request that uses that approach so we'll better understand it? ;)

Joking. Seriously, Roslyn has little to do with the runtime environment. The compilers read a program that complies with the C# (or VB) language specification and produces an assembly according to the Common Language Infrastructure specification. It might be valuable to consider an alternative translation and execution environment, but this project isn't involved in that.

**Comment by mjsabby** [comment]
@simonegli8 http://github.com/dotnet/llilc for an AOT compiler based on LLVM.

**Comment by simonegli8** [comment]
I'm not interested in an AOT compiler. I'm interested in something that is portable but still has performance close to AOT with minimal compiled file size (what also contributes to faster dll load times) and minimal JIT time.

**Comment by simonegli8** [comment]
I mean some peace of really good engineering, not just stupid IL with JIT as we have seen it for the last 20 years.
One technique, researched by Michael Franz, is to take the syntax tree, and store it in an efficient compressed format. This way you can do AOT with still portable files very easy, as all semantic information is still available to the JIT. And with trace tree compilation, you can make the thing load faster than JIT, and use a fast non optimizing compiler just at application startup, and then compile the piece again in the background with an optimizing compiler and available runtime information, so eventually it will run with optimal speed. With IL it's probably harder to implement an optimizing compiler, and IL produces bigger files, so it's slower to load. The only drawback of compressed syntax trees is reverse engineering, but this is as well a problem with IL, and someone who needs obfuscation can still use IL.

**Comment by simonegli8** [comment]
I wouldn't mind creating a fork and trying to implement something like this, but even if I tried I wouldn't have the experience of Michael Franz. Let the people do this job that realy know their field. Apart from that, I've quit the religion of computers and work now in a retirement home.

**Comment by gafter** [comment]
@simonegli8 Java's *hotspot* runtime works somewhat as you describe. There is a fast compiler the first time the code is run, but if the code is used frequently an optimizing compiler recompiles it.

**Comment by svick** [comment]
@simonegli8

> take the syntax tree, and store it in an efficient compressed format

One of the guiding principles of .Net is that it is a multi-language platform (C#, VB.NET, F#, Iron languages, …). How would you create a syntax tree that is language-neutral?

> as all semantic information is still available to the JIT

What kind of information is missing in IL?

> With IL it's probably harder to implement an optimizing compiler

I doubt that. IL is a much simpler language than C#, so I think optimizing it is also simpler.

---

But your second proposal (trace compilation) sounds potentially interesting to me. I think you shouldn't conflate the two. (And in any case, that discussion belongs to dotnet/coreclr#938.)

**Comment by VSadov** [comment]
Since this was reopened on the coreclr side as https://github.com/dotnet/coreclr/issues/938
I guess we can close it here.
