### ISSUE TITLE
Anonymous type display mismatch for nullable vs non-nullable

### ISSUE THREAD

**Issue by NickCraver** [dotnet/roslyn#25348]
Non type display has mismatches for anon-types. Regardless of how we want them to infer or work, the display is an issue either way. Minimal repro:

```c#
static void Main(string[] args)
{
    var foo = new { obj = new A() };
}
public class A {
    public string Name { get; set; }
}
```
Here's a view of the tooltips for this case:
![image](https://user-images.githubusercontent.com/454813/37168178-e6702f46-22b8-11e8-864e-4b26800e144c.png)
![image](https://user-images.githubusercontent.com/454813/37168183-e813bac0-22b8-11e8-89b9-7141686c5efc.png)

It's unclear if `obj` is being inferred as nullable or not (separate bug), but in either case the tooltip has an inconsistency issue.

cc @cston

**Comment by jeromelaban** [comment]
Found this issue in a code similar to this one:

```csharp
public void A<T>(T t) where T:class
{
    var c = new F<T>[] { }.Select(v => new { Value = v.Item }).ToArray();

    B(c.First().Value); // error CS8634:
                        // The type 'T?' cannot be used as type parameter 'T' in the generic type or method 'Program.B<T>(T)'.
                        // Nullability of type argument 'T?' doesn't match 'class' constraint.
}

public void B<T>(T t) where T : class { }

private class F<T>
{
    public F(T oldItem) => Item = oldItem;
    public T Item { get; }
}
```

**Comment by jasonmalinowski** [comment]
These all test out fine in current internal 16.3 Preview 3 builds (testing on 29208.141.master internally). Some of the stuff needed for this to work landed a bit later so it's not surprising to me it's all working now.

Thanks for the reports!

**Comment by jasonmalinowski** [comment]
This did however discover another crash #37879 so that's good!
