### ISSUE TITLE
`out var` treated as non-nullable

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#25347]
`out var` is treated as non-nullable, regardless of parameter declaration.
```c#
class C
{
    static void TryGet(out string? s)
    {
        s = null;
    }
    static void Main()
    {
        TryGet(out var s); // string with null assignment warning
        int n = s.Length;  // no warning
    }
}
```

**Comment by cston** [comment]
cc @NickCraver

**Comment by jcouv** [comment]
I'll take this one as part of the `TryGetValue` scenario with `[NotNullWhenTrue]` attribute.

**Comment by jcouv** [comment]
[Confirmed](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDk4BstWFiAJQkiQDsBjCAFQE8AHFAGhhAEssmATEAagB8AAgCYABAGEAsACgA3jNGLRggIwA2ZQBZR1BLQDiEGAAoA9nBjKVABgD8o5AEoFS+dKUeHogLyiy2LABuF0UAXxCrDUFtVQAOY2d3VwiPXQMjMwtRADcoBAdHQNEAemKra1EAdzYYAAs/ANEoZGQ2AHMyAFsIMktKvLI2MjaUpSHLMh8HADoAGR62uqKSsv6EQeGJAGVYtWthEFEABVMWtnwIUS4IJFIeqlFTMCaGnFFbm/uIaYjw6VCgA=) this was fixed. Closing
