### ISSUE TITLE
Strong Name signing with a key installed in a container

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25340]
After upgrading to respectively installing Visual Studio 2017 Version 15.6 no assemblies will be signed with a strong name.

We are using the AssemblyKeyName Attribute in AssemblyInfo.cs.

Using a KeyFile instead (created from the projects properties) will work.

Am I missing something?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/209811/strong-name-signing-with-a-key-installed-in-a-cont.html
VSTS ticketId: 578075_
_These are the original issue comments:_

Matthew Dodds on 3/7/2018, 10:24 AM (12 hours ago): <p>I am also having this problem with using AssemblyKeyName, which is showing up as two different issues. I am using C#, ASP.NET, .NET 4.7.1. Both of these issues were fixed once I reverted to Visual Studio 15.5.7. I also confirmed that using AssemblyKeyFile referencing a .snk instead of using AssemblyKeyName fixed both issues.</p><p>First: </p><p>Attempting to load the program in IIS results in the exception: "Could not load file or assembly '[redacted], Culture=neutral, PublicKeyToken=928c297f0d8e5e72' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference." </p><p>Fusion log contained: "Comparing the assembly name resulted in the mismatch: PUBLIC KEY TOKEN" </p><p><br></p><p>
Second:</p><p>
Building of a solution that references some of our C# libraries built outside of the solution will result in: "Error CS8002: Referenced assembly '[redacted], Version=6.3.0.144, Culture=neutral, PublicKeyToken=null' does not have a strong name." </p><p>Building this solution a second time will result it successfully building, but will always fail if telling Visual Studio to rebuild. </p><p><br></p>

_These are the original issue solutions:_
(no solutions)

**Comment by agocke** [comment]
It looks like we enabled portable signing for 15.6 https://github.com/dotnet/roslyn/pull/23704

Key containers are meant to fall back to the old signing implementation, but it's possible there's a bug there. I haven't yet managed to repro the issue.

**Comment by agocke** [comment]
I've confirmed the failure.

There are two intermediate workarounds until I fix the bug:

1. You can switch to using a keyfile instead of a key container.
2. You can install the Microsoft.Net.Compilers package, version 2.6.1, which represents the compiler used in VS 15.5 and doesn't have this problem.

**Comment by agocke** [comment]
There are two more fixes that may be easier:

1. You can enable a fallback mode by putting the following in your MSBuild project files:
```
<Features>$(Features);UseLegacyStrongNameProvider</Features>
```

2. You can move the name of the key container from the AssemblyAttributes C# file to your project file(s) by adding the following property:
```
<KeyContainerName>the-name-of-your-key-here</KeyContainerName>
```

**Comment by madodds** [comment]
Thank you for the workarounds. 
I have tested adding the XML nodes to my *.csproj files and found that both solutions return the signing back to normal.

**Comment by nigelgbanks** [comment]
Seems like there might be a regression I can't get the workaround using Features to to work with Visual Studio 2017 v15.9.7 when building a .Net 4.5 application.
