### ISSUE TITLE
MSBuild skips a 'copy local' reference if it is only used in XAML

### ISSUE THREAD

**Issue by chucker** [dotnet/roslyn#25349]
**Version Used**: 15.6.0

**Steps to Reproduce**:

1. create a solution with a WPF Windows application project (project **A**)
2. add a WPF class library project (project **B**). Add a project reference so you can use B within A.
3. in project B, reference a library that you will only use from within XAML, such as FontAwesome.WPF in our example. Make sure the library is set to **Copy Local**.
4. in project B, create a user control like this:

```xml
<UserControl x:Class="DatabaseSelection"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:fa="http://schemas.fontawesome.io/icons/"
             mc:Ignorable="d" 
             d:DesignHeight="114" d:DesignWidth="450">

    <fa:ImageAwesome Icon="UserSecret" Margin="1" />
</UserControl>
```

5. in project A, use the user control somewhere.
6. compile the solution. This will work.
7. debug or run the solution. This fails.

**Expected Behavior**:
In step 6, MSBuild should recognize that FontAwesome.WPF must be copied to project **A**'s output directory.

**Actual Behavior**:
MSBuild incorrectly believes that FontAwesome.WPF isn't actually being used and thus doesn't need copying. As a result, when actually trying to *run* the code, `PresentationFramework` tries and fails to load the library:

```
System.Windows.Markup.XamlParseException: 'Could not load file or assembly 'FontAwesome.WPF, PublicKeyToken=0758b07a11a4f466' or one of its dependencies. The system cannot find the file specified.'
```

**Workaround**:
A dummy method somewhere within project **B** causes MSBuild to copy the library. For example:

```csharp
    private static void _FontAwesome_MSBuildXamlFix()
    {
        /*
         * WORKAROUND
         * we need this method so that FontAwesome.WPF.dll gets copied as part of the build process
         * 
         * https://stackoverflow.com/a/18221455/1600
         */

        var type = typeof(FontAwesome.WPF.FontAwesome);
        Console.WriteLine(type.FullName);
    }
```

**Comment by jaredpar** [comment]
Closing as this is an issue in MSBuild, not Roslyn. Can you please reopen this on https://github.com/microsoft/msbuild ?
