### ISSUE TITLE
Property set member using reference

### ISSUE THREAD

**Issue by mallibone** [dotnet/roslyn#25353]
**Version Used**: 2.8.0.62701

**Steps to Reproduce**:

1. define a member variable
2. create a property that sets the value i.e. the member via it's reference (such as in Reactive UI)
3. set the Property in the constructor

**Expected Behavior**:
No warning is being displayed.
**Actual Behavior**:
A null warning is displayed for the member variable.

**Comment by jcouv** [comment]
@mallibone Could you share some code or project to demonstrate the issue?
Also, could you copy the error code and message?

**Comment by jcouv** [comment]
This issue needs more information to reproduce, but we didn't hear from the user in some time.
I'll go ahead and close. We can re-open if more details are provided.
