### ISSUE TITLE
Referencing the latest compiler from MyGet returns in failure due to error in props file.

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/roslyn#25357]
**Version Used**:  2.8.0 and 2.8.0-beta1-62621-05 (from MyGet)

**Steps to Reproduce**:

1. Create a new dotnet core application (`dotnet new console`).
2. Confirm that it runs as expected (`dotnet run`).
3. Add a pacakge reference to the latest Microsoft.NetCore.Compilers.

```csproj
<ItemGroup>
    <PackageReference Include="Microsoft.NETCore.Compilers" Version="2.8.0-beta1-62621-05" PrivateAssets="All" />
</ItemGroup>
```

**Expected Behavior**:
`dotnet run` behaves exactly as it did without the PackageReference and outputs:
Hello World!

**Actual Behavior**:
We get a build failure.
```text
C:\Users\ahkha\.nuget\packages\microsoft.netcore.compilers\2.8.0-beta1-62621-05\build\Microsoft.NETCore.Compilers.props(34,11): error MSB4101: Expected a closing quote after position 153 in condition "'$(BuildingProject)' == 'true' AND                      '$(OS)' != 'Windows_NT' AND                      ('$(CscToolPath)' != '' OR '$(VbcToolPath) != '')". [D:\GitHub\Fork\corefxlab\TestCompiler\TestCompiler.csproj]

The build failed. Please fix the build errors and run again.
```

In the Microsoft.NETCore.Compilers.props file (`C:\Users\<user>\.nuget\packages\microsoft.netcore.compilers\2.8.0-beta1-62621-05\build\Microsoft.NETCore.Compilers.props`), you will notice, we are missing a closing quote around `VbcToolPath`:
**This:**
```csproj
  <Target Name="MakeCompilerScriptsExecutable"
          Condition="'$(BuildingProject)' == 'true' AND
                     '$(OS)' != 'Windows_NT' AND
                     ('$(CscToolPath)' != '' OR '$(VbcToolPath) != '')"
```
**Should be:**
```csproj
  <Target Name="MakeCompilerScriptsExecutable"
          Condition="'$(BuildingProject)' == 'true' AND
                     '$(OS)' != 'Windows_NT' AND
                     ('$(CscToolPath)' != '' OR '$(VbcToolPath)' != '')"
```

**Comment by ahsonkhan** [comment]
**Edit:** Looking more closely, I just realized this was already fixed recently in https://github.com/dotnet/roslyn/commit/930152a8ba37d483fe4e739a5dbb405011f23eba#diff-71e9a985d536f4a8148dfe9cbf143aaeL36 from https://github.com/dotnet/roslyn/pull/25220

Previous issue: https://github.com/dotnet/roslyn/issues/25219

cc @agocke, @VSadov 

Closing the issue.

**Comment by ahsonkhan** [comment]
When can we expect a newer version of the compiler with this fixed? The latest one was published around 2 weeks ago - Fri, 23 Feb 2018.

**Comment by agocke** [comment]
2.8.0-beta2-62708-09 is available and a couple hours old at the most

**Comment by ahsonkhan** [comment]
> 2.8.0-beta2-62708-09 is available and a couple hours old at the most

Thanks! I was looking at the wrong feed. I was grabbing packages from https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.Compilers/2.8.0-beta1-62621-05 rather than roslyn.
