### ISSUE TITLE
ref struct locals are allowed in iterators

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#25350]
We seem to allow ref struct locals in iterators as long as they are not captured.

That is safe, but relies on implementation details. The spec says that ref struct locals in iterators are strictly forbidden.

**Comment by gafter** [comment]
While this is true, it does not rely on implementation details.  Variables and values are spilled if they must be spilled.  If one such is a ref struct an error is produced.  We don't specify "must be spilled" in the language specification, but we implement it as tightly as possible.

I don't expect this to change, as it would be a breaking change.  So this must be OK as it is.
