### ISSUE TITLE
The Roslyn Analyzer for inlining variable declarations in method calls should suggest a discard if the variable isn't used elsewhere

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25365]
Given a method signature such as:

void Foo(out int outVal)

if I call it like this:
void Caller()
{
	int i;
	Foo(out i);
}

Currently I get a suggestion to inline the variable declaration, e.g:

Foo(out int i);

Instead, since i is never used, it should suggest using a discard, e.g.:
Foo(out _);

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/210537/the-roslyn-analyzer-for-inlining-variable-declarat.html
VSTS ticketId: 578732_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
cc @sharwell

**Comment by CyrusNajmabadi** [comment]
This feels like a dupe.  But i can't find the right issue.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
