### ISSUE TITLE
Diagnostic CodeFix for CS1737/BC30202: Optional parameters must appear after all required parameters

### ISSUE THREAD

**Issue by MaStr11** [dotnet/roslyn#25368]
**Steps to Reproduce**:

```CS
public class C {
    public void M(int i1 = 1, int i2)  // CS1737: Optional parameters must appear after all required parameters
    {
    }
}
```

**Expected Behavior**:

Offer fix: "Make 'i2' optional"

```CS
public class C {
    public void M(int i1 = 1, int i2 = 0) 
    {
    }
}
```
Related diagnostic id in VB: BC30202: *'Optional' expected.* (and maybe BC30812: *Optional parameters must specify a default value.* can be fixed by this code fixer too).

Related #23326.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback for this isuse.
