### ISSUE TITLE
Diagnostic CodeFix for CS0708:  'M': cannot declare instance members in a static class

### ISSUE THREAD

**Issue by MaStr11** [dotnet/roslyn#25369]
**Steps to Reproduce**:

```CS
public static class C {
    public void M() // CS0708: 'M': cannot declare instance members in a static class
    {
    }
}
```

**Expected Behavior**:

Offer fix: "Make 'M' static"

```CS
public static class C {
    public static void M()
    {
    }
}
```

No related diagnostic id in VB. Needs FixAll support for copy&paste scenarios.

Related #23326.

**Comment by angelina-dev** [comment]
Hi, what should be Fix All scope? Will it show all possible variants: document, selected block of code, current project, the whole solution?

**Comment by Youssef1313** [comment]
This was implemented in https://github.com/dotnet/roslyn/pull/38908 and can be closed now. cc @jinujoseph
