### ISSUE TITLE
Warning reported for `null` passed to `params` array of nullable elements

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#25375]
Reports: `(8,15): warning CS8600: Cannot convert null to non-nullable reference.`
```
class C
{
    static void F(object x, params object?[] y)
    {
    }
    static void Main()
    {
        F("", null);
    }
}
```

**Comment by chsienki** [comment]
I'd argue that this is actually correct.

`F("", null)` is invoked in normal form, not expanded. So we *are* passing a null reference to a non null reference.

``` c#
class C
{
    static void F(object x, params object?[] y)
    {
        System.Console.WriteLine(y.Length);
    }
    static void Main()
    {
        F("", null);
    }
}
```

Throws a null reference exception on `y.Length`, rather than printing a value of `1`

**Comment by chsienki** [comment]
@cston I'd like to close this as by-design. What do you think?

**Comment by cston** [comment]
@chsienki, you're right, that is by design, thanks. Feel free to close.

Is there a test for `params object[]?`?
```C#
class C
{
    static void F(object x, params object?[] y)
    {
    }
    static void G(object x, params object[]? y)
    {
    }
    static void Main()
    {
        F("", null);
        G("", null); // warning
    }
}
```

**Comment by chsienki** [comment]
@cston, I couldn't find a test that quite captured what's disccussed here, so I added an extra one that explicitly calls out how the behavior of normal/expanded interacts with nullable params
