### ISSUE TITLE
Diagnostic CodeFix for CS0737: 'C' does not implement interface member 'ITest.M()'. 'C.M()' cannot implement an interface member because it is not public.

### ISSUE THREAD

**Issue by MaStr11** [dotnet/roslyn#25385]
**Version Used**: 
2.8.
**Steps to Reproduce**:
```CS
internal interface I
{
    void M();
}
internal class C: I //CS0737: 'C' does not implement interface member 'I.M()'. 'C.M()' cannot implement an interface member because it is not public.
{
    internal void M() 
    {
    }
}
```
**Expected Behavior**:
Offer fix: "Make 'M' public"
```CS
internal interface I
{
    void M();
}
internal class C: I
{
    public void M() 
    {
    }
}
```
**Actual Behavior**:
"Implement interface" and "Implement interface explicitly" are offered which both generate the exact same explicit interface implementation:
 ```CS
internal interface I
{
    void M();
}
internal class C : I
{
    internal void M()
    {
    }

    void I.M()
    {
        throw new NotImplementedException();
    }
}
```

https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0737

There is no corresponding VB diagnostic.

Related #23326.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback for this minor issue.
