### ISSUE TITLE
Exception while saving file 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#25391]
Reported by Deepu Abraham Dogfood channel 

**Version Used**:
15.7. 0 preview 1.0 [27508.1.d15.7]

**Steps to Reproduce**:

1. create Windows Forms Project
2. Add button to the for and save
3. Double click on button to create click handler and open edit code window, save changes
4. back to form designer, delete button and save changes
5. back to code, delete click handler and save changes
6. back to form designer, add button again and save changes
7. Double click on button (nothing happened, it suppose to open form code and add click handler), save changes
8. delete button, save changed -> and then we got error message attached.

**Expected Behavior**:
file saved 
**Actual Behavior**:

![image](https://user-images.githubusercontent.com/12449387/37234874-35b89ba0-23af-11e8-9cc5-e103c5e93680.png)

Stack 

Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.Interop.CleanableWeakComHandleTable<Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.SyntaxNodeKey, EnvDTE.CodeElement>.Add(Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.SyntaxNodeKey key, EnvDTE.CodeElement value) Line 179       C#
> Microsoft.VisualStudio.LanguageServices.Implementation.dll!Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.UpdateCodeElementNodeKey(Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.AbstractKeyedCodeElement keyedElement, Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.SyntaxNodeKey oldNodeKey, Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.SyntaxNodeKey newNodeKey) Line 193       C#
Microsoft.VisualStudio.LanguageServices.Implementation.dll!Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.AbstractKeyedCodeElement.ReacquireNodeKey(Roslyn.Utilities.SyntaxPath syntaxPath, System.Threading.CancellationToken cancellationToken) Line 78 C#
Microsoft.VisualStudio.LanguageServices.Implementation.dll!Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.Interop.IVBFileCodeModelEvents.EndEdit() Line 693 C#
       [Native to Managed Transition]   
       [Managed to Native Transition]   
        Microsoft.VisualStudio.Design.dll!Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomProvider.EndEdit()        Unknown
Microsoft.VisualStudio.Design.dll!Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomGenerator.GenerateCodeFromType(System.CodeDom.CodeTypeDeclaration e, System.IO.TextWriter w, System.CodeDom.Compiler.CodeGeneratorOptions o)        Unknown
Microsoft.VisualStudio.Design.dll!Microsoft.VisualStudio.Design.Serialization.CodeDom.MergedCodeDomGenerator.GenerateCodeFromType(System.CodeDom.CodeTypeDeclaration typeDeclaration, System.IO.TextWriter writer, System.CodeDom.Compiler.CodeGeneratorOptions codeGenOptions) Unknown
Microsoft.VisualStudio.Design.dll!Microsoft.VisualStudio.Design.Serialization.CodeDom.MergedCodeDomGenerator.GenerateCodeFromNamespace(System.CodeDom.CodeNamespace nameSpace, System.IO.TextWriter writer, System.CodeDom.Compiler.CodeGeneratorOptions codeGenOptions)      Unknown
Microsoft.VisualStudio.Design.dll!Microsoft.VisualStudio.Design.Serialization.CodeDom.MergedCodeDomGenerator.GenerateCodeFromCompileUnit(System.CodeDom.CodeCompileUnit compileUnit, System.IO.TextWriter writer, System.CodeDom.Compiler.CodeGeneratorOptions codeGenOptions)    Unknown
       System.dll!System.CodeDom.Compiler.CodeDomProvider.GenerateCodeFromCompileUnit(System.CodeDom.CodeCompileUnit compileUnit, System.IO.TextWriter writer, System.CodeDom.Compiler.CodeGeneratorOptions options)   Unknown
Microsoft.VisualStudio.Shell.Design.dll!Microsoft.VisualStudio.Shell.Design.Serialization.CodeDom.CodeDomDocDataAdapter.Generate()        Unknown
Microsoft.VisualStudio.Design.dll!Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.Write(System.CodeDom.CodeCompileUnit unit)   Unknown
System.Design.dll!System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.PerformFlush(System.ComponentModel.Design.Serialization.IDesignerSerializationManager manager) Unknown
       System.Design.dll!System.ComponentModel.Design.Serialization.BasicDesignerLoader.Flush()  Unknown
    Microsoft.VisualStudio.Design.dll!Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.Flush()        Unknown
Microsoft.VisualStudio.Design.dll!Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.VSCodeDomEventBindingService.ShowCode(System.ComponentModel.IComponent component, System.ComponentModel.EventDescriptor e, string methodName)    Unknown
       System.Design.dll!System.ComponentModel.Design.EventBindingService.ShowCodeIdle(object sender, System.EventArgs e)      Unknown
System.Windows.Forms.dll!System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(int grfidlef)       Unknown
System.Windows.Forms.dll!System.Windows.Forms.ComponentManagerProxy.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(int grfidlef)       Unknown

**Comment by jinujoseph** [comment]
cc @DustinCampbell

**Comment by jinujoseph** [comment]
Repro's in 15.6 as well

**Comment by CyrusNajmabadi** [comment]
Closing out for lack of prism hits.
