### ISSUE TITLE
'use auto property' codefix somethimes creates private setter for readonly fields

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn#25408]
**Version Used**:  15.6.1

**Steps to Reproduce**:
I was't able reproduce it in small example. Even moving full class to an empty project leads to issue disappearance, so I think there are some extra conditions applies.
To reproduce it you will need to download this revision (as I plan to fix it soon) : https://github.com/linq2db/linq2db/tree/538a1f2a2c632f3a56206559d1f5dad5a189c284

1.  open class MergeDefinition from Source\LinqToDB\Data\MergeDefinition.cs
2.  Apply 'use auto property' code fix for any readonly field in MergeDefinition or MergeDefinition.Operation class

**Expected Behavior**:
field and property replaced with property:
```cs
public type Property { get; }
```

**Actual Behavior**:
private settter generated too
```cs
public type Property { get; private set; }
```

**Comment by CyrusNajmabadi** [comment]
Is the field assigned to (outside of the constructor)?  If so, we need to create a setter for it.

**Comment by CyrusNajmabadi** [comment]
Oh strange.  These are all readonly fields.  Hrmm... this needs closer examination.

**Comment by Neme12** [comment]
I was able to reduce the repro. The problem only happens when multi-targeting.
Sample code:
```c#
class C
{
    private readonly int _value;

    public C(int value)
    {
        _value = value;
    }

    public int Value
    {
        get { return _value; }
    }
}
```

with a csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netcoreapp2.0</TargetFrameworks>
  </PropertyGroup>

</Project>

```

Removing either `netstandard2.0` or `netcoreapp2.0` fixes the behavior.
