### ISSUE TITLE
Code fixes (at least use auto property) doesn't respect tabs vs spaces settings 

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn#25407]
**Version Used**:  15.6.1

**Steps to Reproduce**:

.editorconfig
```
root = true

[*]
indent_style = tab
insert_final_newline = true

```

sample code (tabs used everywhere)
```cs
namespace ConsoleApp2
{
	class Program
	{
		private static int _field;

		public static int Field
		{
			get
			{
				return _field;
			}
		}

		static void Main(string[] args)
		{
		}
	}
}

```

apply use auto property fix to _field

**Expected Behavior**:
only tabs used and no extra new lines would be great
```cs
namespace ConsoleApp2
{
	class Program
	{
		public static int Field { get; }

		static void Main(string[] args)
		{
		}
	}
}
```

**Actual Behavior**:
```cs
namespace ConsoleApp2
{
	class Program
	{
/*why this new line added?*/
/*spaces here */public static int Field { get; }

/*and here!   */static void Main(string[] args)
		{
		}
	}
}

```

**Comment by CyrusNajmabadi** [comment]
> ```/*why this new line added?*/```

The line was not added.  It's simply that when _field is removed there is nothing that tries to remove the line that exists between the field and the property.

**Comment by CyrusNajmabadi** [comment]
@heejaechang Do you know what's causing the spaces to be inserted? I thought teh formatting engine would use editor config for this sort of thing.  Thanks!

**Comment by heejaechang** [comment]
it should. probably need to see what OptionSet is given to formatter when formatting runs.

**Comment by heejaechang** [comment]
we have tab issue reported for 15.6.1

might be related to that issue - https://developercommunity.visualstudio.com/content/problem/212253/tabs-settings-broken.html

**Comment by crypto-rsa** [comment]
The same issue happens when changing the signature of a method:
```
// the method below is indented with tabs
		public void Test( int a, int b )
		{
		}
```

When I do Edit - Refactor - Reorder Parameters - delete parameter `a`, then the opening brace of the method gets indented with 8 spaces.

**Comment by heejaechang** [comment]
so this only happens if setting is changed to tab in editorconfig but not when changed to tab from tools->option?

**Comment by crypto-rsa** [comment]
I tried both code fixes with no `.editorconfig` and tabs set in VS options - both were applied correctly with tab indentation.

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  I get:

![image](https://user-images.githubusercontent.com/4564579/216473267-c63b69b2-ecc4-4ea7-a11c-055ec1172142.png)
