### ISSUE TITLE
ImplementInterface adds the 'new' keyword to members that don't actually hide other members

### ISSUE THREAD

**Issue by Jayrod246** [dotnet/roslyn#25406]
**Version Used**: 
Microsoft Visual Studio Community 2017
Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
Microsoft .NET Framework
Version 4.7.02556

**Steps to Reproduce**:

1. Write the following code to a file inside a C# project:
```
using System.IO;

interface IStream
{
    void Read<T>(T[] buffer, int offset, int count);
    void Write<T>(T[] buffer, int offset, int count);
}

public class CustomStream : MemoryStream, IStream
{
}
```
2. Right-click on IStream (underlined in red due to not implemented error) -> quick actions and refactorings ->implement interface.
3. File will now look like this: 
```
using System.IO;

interface IStream
{
    void Read<T>(T[] buffer, int offset, int count);
    void Write<T>(T[] buffer, int offset, int count);
}

public class CustomStream : MemoryStream, IStream
{
    public new void Read<T>(T[] buffer, int offset, int count)
    {
        throw new System.NotImplementedException();
    }

    public new void Write<T>(T[] buffer, int offset, int count)
    {
        throw new System.NotImplementedException();
    }
}
```

**Expected Behavior**:
No 'new' keywords, since no members are actually hidden by the implementation.

**Actual Behavior**:
'new' keywords are added to the implementation.

**Comment by Jayrod246** [comment]
These methods are inherited from Stream/MemoryStream and look very similar to those defined by the interface:
```
int Read(byte[] buffer, int offset, int count)
{ ... }
void Write(byte[] buffer, int offset, int count)
{ ... }
```
I'm suspecting this to be the cause of the problem, in this case.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/42429
