### ISSUE TITLE
VB: Pretty listing and Intellisense break when typing below a line that uses XML axis properties.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#25414]
**Version Used**:

Visual Studio Community 2017 v15.5.6

**Steps to Reproduce**:

This is a bit tricky to explain but I will try:

```vb
    Dim xml = <blank/>

    '<-- pretty listing WORKS here. If you type 'dim' and press space it becomes 'Dim'.
    Dim blah = xml...<blah>
    '<-- pretty listing BREAKS here. If you type 'dim' and press space it STAYS 'dim'.
    '<-- pretty listing WORKS here. If you type 'dim' and press space it becomes 'Dim'.
```

As the comments describe, if you type on the line immediately above `Dim blah = xml...<blah>` the code is **reformatted as you type.** Same thing if you are one extra line below `Dim blah = xml...<blah>`. However if you are on the **line immediately below** `Dim blah = xml...<blah>` the **reformatting only happens when you press enter** after you are done typing (not when you  press space bar).

I suspect the problem is caused by using XML axis properties as seen in the expression `xml...<blah>`. If instead of axis properties you use method calls, everything works as expected:

```vb
    '<-- pretty listing WORKS here like before.
    Dim blah = xml.Descendants("blah") '<-- note use of method call instead of axis property.
    '<-- pretty listing NOW WORKS HERE TOO. If you type 'dim' and press space it becomes 'Dim'.
    '<-- pretty listing WORKS here like before.
```

For Intellisense/autocomplete, the breakage occurs when you try to invoke autocomplete after the expression containing axis properties:

```vb
    Dim qry1 = From e In xml...<blah> sele
```

...in the above code after the letters `sele` **if you try to invoke autocomplete so they can be completed and reformatted to read `Select`, nothing happens**. However if you use method calls instead, Intellisense kicks in and suggests the `Select` keyword as expected:

![vs_axis_properties_break_intellisense](https://user-images.githubusercontent.com/20465797/37266119-40508750-25c9-11e8-81ca-c0a5a538d8f4.png)

**Expected Behavior**:

Something about those xml axis properties is tripping up the pretty listing and Intellisense functionality. And this happens only to code that appears **immediately after** axis property expressions whether on the same line (as in the case of the LINQ queries) or on the line immediately below.

Pretty listing and Intellisense/autocomplete should work everywhere: below, above and within the line containing an xml axis expression.

**Comment by ericmutta** [comment]
Hi @Pilchie, when you get a spare moment, kindly review and tag this one so it doesn't fall through the cracks. Many thanks in advance :+1: :+1:

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not likely to be changing these experiences.
