### ISSUE TITLE
Roslyn is producing a strong-name signed dll even when DelaySign is set to true

### ISSUE THREAD

**Issue by joperezr** [dotnet/roslyn#25424]
**Version Used**: 2.8.0-beta2-62711-03

**Steps to Reproduce**:

We are trying to get the latest version of Roslyn consumed by corefx so that we can start using the compiler server for non-Windows builds. The problem seems to be that after updating to the latest version, we can't force the compiler to NOT strong-name sign the assemblies. In corefx we need this since we run some post-compilation tools on the dll and we manually sign the binaries after that. Here are the parameters we are passing in to the CSC task:

![image](https://user-images.githubusercontent.com/13854455/37302499-ee658fba-25e8-11e8-93c5-60ed521a0543.png)

**Expected Behavior**: output assembly shouldn't be strong-name signed

**Actual Behavior**: assembly is strong name signed causing a build error when we try to sign it manually after running our tools.

This is currently blocking the adoption of roslyn into corefx so it would be appreciated if addressed soon. cc: @agocke @jaredpar

**Comment by agocke** [comment]
@joperezr Can you also check to see if your AssemblyInfo has `[assembly: AssemblyDelaySign(false)]`? I think the command line flag should still take precedence, but we should cover all the bases.

**Comment by joperezr** [comment]
doesn't look like it. Here are the contents of the file:
```cs
using System;
using System.Reflection;
[assembly:System.Security.AllowPartiallyTrustedCallers]
[assembly:System.Runtime.CompilerServices.ReferenceAssembly]
[assembly:System.Reflection.AssemblyFlags((System.Reflection.AssemblyNameFlags)0x70)]
[assembly:AssemblyTitle("CoreFx.Private.TestUtilities")]
[assembly:AssemblyDescription("CoreFx.Private.TestUtilities")]
[assembly:AssemblyDefaultAlias("CoreFx.Private.TestUtilities")]
[assembly:AssemblyCompany("Microsoft Corporation")]
[assembly:AssemblyProduct("Microsoft® .NET Framework")]
[assembly:AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly:AssemblyVersion("1.0.0.0")]
[assembly:AssemblyFileVersion("4.6.26309.0")]
[assembly:AssemblyInformationalVersion(@"4.6.26309.0 @BuiltBy: joperezr-joperezrConsole @Branch: HEAD @SrcCode: https://github.com/dotnet/corefx/tree/8a53590f229741b0b9043db637d5e8f233d01a74")]
[assembly:CLSCompliant(true)]
[assembly:System.Reflection.AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly:System.Reflection.AssemblyMetadata("Serviceable", "True")]
[assembly:System.Reflection.AssemblyMetadata("PreferInbox", "True")]
```
