### ISSUE TITLE
FindAllReference failed to find usages in a referencing project inside the same solution

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn#25428]
**Version Used**: 
15.6 and 15.7 (27504.0.d15.7)

**Steps to Reproduce**:

1. clone the github repo and check out the commit https://github.com/Microsoft/dotnet-apiport/commit/694799594cb021e1e2feb9e224a1133982cb1bd5
2. open src\backend\Functions\Analyze.cs, and invoke FAR on the class `Analyze`

**Expected Behavior**:
FAR should return the two usages in the test\backend\Functions.Tests\AnalyzeTests.cs

**Actual Behavior**:
no references found 

I tried to but haven't been able to get a simplified repro.
Solution explorer shows the project reference.  Solution builds fine. Both projects are in the new SDK style. I have all three Analysis options enabled

![image](https://user-images.githubusercontent.com/7583839/37308994-c2d1fa46-25fc-11e8-9c17-8eda2b578e4e.png)

![image](https://user-images.githubusercontent.com/7583839/37308888-86861d42-25fc-11e8-8f87-dceed5aad1ba.png)

**Comment by jcouv** [comment]
How does GoToDefinition behave when invoked on the usage? Does it go to the definition as expected?

**Comment by jeremymeng** [comment]
> How does GoToDefinition behave when invoked on the usage? Does it go to the definition as expected?

No, it opens metadata as source window

**Comment by jcouv** [comment]
Tagging @Pilchie and @DustinCampbell to help route (might this be a project system issue or workspaces?).

**Comment by Pilchie** [comment]
Seems like the P2P ref is not being hooked up as one.  This happens in Roslyn by matching the output path of the project to the reference.  @jasonmalinowski any idea how to track this down?

@jeremymeng can you try setting `PROJECTSYSTEM_PROJECTOUTPUTPANEENABLED=1` as an env var and running VS, then capturing the output window pane for the project system?

**Comment by jeremymeng** [comment]
> then capturing the output window pane for the project system?

I put the logs at https://gist.github.com/ebb74dfcf7a8e0710c25a278905d2be7

**Comment by jasonmalinowski** [comment]
Installing https://github.com/jasonmalinowski/roslyn-info-logger and making a dump from that would also dump output paths so we could see what is going on.

(We probably should move that to the project system tools now...)

**Comment by jeremymeng** [comment]
`\\scratch2\scratch\yumeng\logs\RoslynWorkspaceStructure.zip` and logged https://github.com/jasonmalinowski/roslyn-info-logger/issues/2 for you @jasonmalinowski :)

Should I move this issue to project-system repo?

**Comment by jasonmalinowski** [comment]
Not yet. Still too many components to blame yet. :-)

**Comment by RipPer56** [comment]
I think it's because you're using an old assmebly of microsoft.Build... packages Even if you installed them, your program still be using thoses from the gac, which are usually old and make this problem pop. So maybe try this #25679
