### ISSUE TITLE
Invertif on VB should work when subsequent block is an elseif

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#25434]
Currently, the VB side of invertif only works if the block following the triggered If or Elseif is an Else block, for example:

the If of an If/Else statement
the ElseIf of an If/Elseif/Else statement
the last Elseif of an If/ElseifBlocks/Else statement
Would like to expand this to work when the subsequent block is an Elseif, for excample:

the If of an If/Elseif/Else statement
any ElseIf block that is followed by either Elseif or Else

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
