### ISSUE TITLE
Move to dotnet pack

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#25439]
Presently our build infrastructure uses `nuget pack` to create our NuGet packages. This means we can only build our packages on Windows. Need to move to using `dotnet pack` for package creation.

**Comment by tmat** [comment]
Looking into this.

**Comment by jaredpar** [comment]
@tmat I actually fixed this quite some time ago. I just forgot to close the issue. We no longer have any dependency on `nuget.exe`.

**Comment by tmat** [comment]
Right, but we don't have `dotnet pack` working either.

**Comment by tmat** [comment]
Most of the packages we produce can be built directly from the projects that produce the binaries. Meta-packages need separate project. Some packages need explicit nuspec.

**Comment by jaredpar** [comment]
@tmat it does work but via a proxy project file. Do you mean `dotnet pack` directly on the project files themselves?

**Comment by tmat** [comment]
Yes

**Comment by tmat** [comment]
Already found some bugs in the custom nuspecs we have today that could be avoided by doing that.
