### ISSUE TITLE
Unknown checkbox in change signature settings

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#25436]
what is this checkbox for? (at change signature settings) version 15.6.1

![capture](https://user-images.githubusercontent.com/15255162/37314576-25c30baa-266a-11e8-9315-68931b2c2ee8.JPG)

**Comment by jcouv** [comment]
Either this was fixed in 15.7 preview 1, or something strange is going on.
Here's a screenshot in 15.7 I took yesterday:

![image](https://user-images.githubusercontent.com/12466233/37251585-b7089a20-24c7-11e8-9bbf-9a301029b229.png)

**Comment by MkazemAkhgary** [comment]
15.6.1 was the latest update I received from VS notification.

**Comment by jinujoseph** [comment]
Doesn't repro in 15.8.2 , might have been fixed in the latest.
