### ISSUE TITLE
Naming: "Stand-alone Code Analysis Tool" should not be hyphenated

### ISSUE THREAD

**Issue by BillWagner** [dotnet/roslyn#25445]
The templates delivered with the .NET Compiler Platform SDK includes one for a "Stand-Alone Code Analysis Tool".  Microsoft naming conventions follow the recommendations in the [American Heritage Dictionay](https://www.ahdictionary.com/word/search.html?q=standalone) where "Stand-alone" should not be hyphenated. It should be "Standalone".

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #112](https://github.com/dotnet/roslyn-sdk/issues/112) via [**ZenHub**](https://www.zenhub.com/)
