### ISSUE TITLE
[VB bugs report] Null member access failed

### ISSUE THREAD

**Issue by xieguigang** [dotnet/roslyn#25443]
**Version Used**: 

Microsoft Visual Studio Community 2017 
Version 15.5.7
VisualStudio.15.Release/15.5.7+27130.2036
Microsoft .NET Framework
Version 4.7.02558

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA986
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA986
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA986
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA986
Microsoft Visual F# 4.1

ASP.NET and Web Tools 2017   15.0.31129.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

Azure App Service Tools v3.0.0   15.0.31106.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Dotfuscator Community Edition   5.32.1.6167-6ce295ebd
PreEmptive Protection - Dotfuscator CE

GitHub.VisualStudio   2.4.1.1219
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.4.11025.7
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

TypeScript Tools   15.5.11025.1
TypeScript Tools for Microsoft Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

**Steps to Reproduce**:

1. Writing code with nullable object for ``For`` iterator:

```vbnet
Dim list = populateNothing()?.data
Dim test2 = TryCast(Nothing, Integer()).SafeQuery

For Each s In list.SafeQuery
Next
For Each s In populateNothing()?.data.SafeQuery
Next

Public Class List
    Public Property data As String()
End Class

Public Function populateNothing() As List
    Return Nothing
End Function

<Extension>
Public Iterator Function SafeQuery(Of T)(source As IEnumerable(Of T)) As IEnumerable(Of T)
    If Not source Is Nothing Then
        For Each x As T In source
            Yield x
        Next
    End If
End Function
```

2. The program compile without error but throw out a ``NullReferenceException`` at ``populateNothing()?.data``

![default](https://user-images.githubusercontent.com/9410171/37328499-60711c72-26d5-11e8-90cc-9966645d87c0.PNG)

**Expected Behavior**:

``populateNothing()?.data`` should returns ``Nothing`` without any error.

**Actual Behavior**:

``populateNothing()?.data`` throw ``NullReferenceException``

**Comment by jaredpar** [comment]
This is executing as designed here. It's not the `?.data` that is throwing the exception but the `data.SafeQuery` that throws.
