### ISSUE TITLE
Remove unused variable should not show up above 'add using'.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#25470]
![image](https://user-images.githubusercontent.com/4564579/37429261-082ff2ce-278c-11e8-99bb-795c75cf0953.png)

This happens when you type your declaration fully, then hit ctrl-dot to 'add using'.  i.e. your cursor is at the end of the line, not on the tyep that is missing.

**Comment by DustinCampbell** [comment]
Yes, this one is important. cc @jinujoseph rather than a random other GitHub user. :smile:

**Comment by CyrusNajmabadi** [comment]
good lord.  there's a @jinujoseph and a jinujoe...   that's not confusing at all! :)

**Comment by Neme12** [comment]
@CyrusNajmabadi I think this is the 4th time I've seen you tag "jinujoe" :smile:

**Comment by CyrusNajmabadi** [comment]
crap!  i wonder if there's a way to search for that.  so we can get the real @jinujoseph on it.

**Comment by jinujoseph** [comment]
According to @vsccarl  , this still repros in latest 15.8

**Comment by Neme12** [comment]
Yes, sorry for the confusion. I wasn't saying that it doesn't repro. I was just wondering because I found an old PR that supposedly fixed this about a year ago. Was it reverted? Or what caused the regression?
