### ISSUE TITLE
Results View does not work in Windows 10 Universal Apps

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#2547]
![capture](https://cloud.githubusercontent.com/assets/6464209/7487528/2d82cd76-f36e-11e4-9eda-182abe8dae47.PNG)

**Comment by pnelsonmsft** [comment]
An aspect of this bug was fixed in the debugger (changeset 1473415).  The debugger was assuming that SystemCore_EnumerableDebugView lived in System.Core.dll.  The fix removed that assumption.  The error message appears to be coming from Roslyn, however.

**Comment by KevinH-MS** [comment]
Thanks!  I'll take a look.

**Comment by KevinH-MS** [comment]
I think it's ok if the error message text is wrong in the event that we do show it (we're just surfacing the compiler error message).  However, we shouldn't be seeing the error to begin with.

I'll add System.Linq to the places that we optimistically add System.Core on error today.

**Comment by KevinH-MS** [comment]
I have a partial fix at 3f2f749305349b5220e7ee17c97b2328d4f5a1e4, but this is blocked by DevDiv 1182590 (the fix is not worth checking in without the corresponding fix in VIL).

**Comment by amcasey** [comment]
Moving to 1.1 (FYI @ManishJayaswal @pnelsonmsft )

**Comment by ManishJayaswal** [comment]
@mattscheffer please verify.
