### ISSUE TITLE
[Refactoring] Extract Resource

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#25497]
This would be a refactoring that allows you to select a hard-coded string in a .cs or .xaml file and use the lightbulb menu to move it to a .resx file (existing or new). 

Look into handling existing resource keys with same value and comments as well.

**Comment by alrz** [comment]
Dupliacte of https://github.com/dotnet/roslyn/issues/16624

**Comment by jinujoseph** [comment]
closed as dupe of  https://github.com/dotnet/roslyn/issues/16624
