### ISSUE TITLE
[BUG] Roslyn outputs incorrect IL according to PEVERIFY for this test case

### ISSUE THREAD

**Issue by bradphelan** [dotnet/roslyn#2549]
The following class when compiled with VS2015rc generates bad IL according to PEVERIFY

	    public class BadBaby
	    {
	        IEnumerable<bool> Children;
	
	        public IEnumerable<object> Foo<TArtifact>()
	        {
	
	            return Enumerable
	                    .Empty<bool>()
	                    .Select(_ => Children
	                        .OfType<TArtifact>()
	                        .Select(c => false)
	                    )
	                ;
	        }
	
	    }
	    
The above minimal code was extracted through trial and error from a much more complex part of our production code.
	    
output from PEVERIFY

	C:\Users\phelan\workspace\BadBadBaby\BadBadBaby\bin\Debug
	> PEVerify.exe .\BadBadBaby.dll
	
	Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.33440
	Copyright (c) Microsoft Corporation.  All rights reserved.
	
	[IL]: Error: [C:\Users\phelan\workspace\BadBadBaby\BadBadBaby\bin\Debug\BadBadBaby.dll : 
	    BadBadBaby.BadBaby::<Foo>b__1_0[TArtifact]][offset 0x0000000B] 
	     [HRESULT 0x8007000B] - 
	 An attempt was made to load a program with an incorrect format.
	
	1 Error(s) Verifying .\BadBadBaby.dll
	C:\Users\phelan\workspace\BadBadBaby\BadBadBaby\bin\Debug
	>
	
The complete project complete with built assemblies can be found at

https://www.dropbox.com/s/mw6x2r4uui54soy/BadBadBaby.zip?dl=0

**Comment by eggapauli** [comment]
It seems that the invalid IL is in the anonymous delegate of the inner select statement (`Select(c => false)`). The error doesn't occur when you either don't capture `Children`, don't use `TArtifact` in the inner delegate or remove the inner select statement entirely.

**Comment by eggapauli** [comment]
Sorry, `BadBadBaby.BadBaby::<Foo>b__1_0` refers to the delegate of the outer select statement. Anyway, Roslyn produces correct IL code when you remove the inner select statement.

**Comment by jaredpar** [comment]
@bradphelan thanks for reporting this!

**Comment by gafter** [comment]
Ever so slightly simpler repro:

```cs
using System;
using System.Collections.Generic;
using System.Linq;

public class BadBaby
{
    IEnumerable<object> Children;
    public void Foo<T>()
    {
        Func<IEnumerable<bool>> x = () =>
            Children
                .OfType<T>()
                .Select(c => true);
    }
}
```

**Comment by bradphelan** [comment]
@jaredpar It was no problem to report. I'm really curious to know what the problem is. Might give me some motivation to look into the compiler source :)

**Comment by VSadov** [comment]
When a lambda expression is compiled, its body is implemented as a synthesised method, often placed in into a synthesized class. During such transformation, generic type parameters of the method that used to contain the lambda become unavailable to the synthesised method and the type parameters  need to be represented as generic type parameters of the synthesized class while all usage of the original method's type parameter in the lambda body must be substituted to refer to the type parameter on that class. If compiler misses a case, then there is a reference in the code that refers to a generic parameter of the containing method where the actual containing method (sythesized one) is not even generic. Such the code is malformed and makes no sense to the runtime. 
It is very likely we have some form of a "missed substitution" case here.

**Comment by gafter** [comment]
The corresponding code in VB has no problem.

```vb
    Dim Children As IEnumerable(Of Object)

    Function Foo(Of TArtifact)() As IEnumerable(Of Object)
        Return Enumerable.
            Empty(Of Boolean)().
            Select(Function(ignored) Children.
                   OfType(Of TArtifact)().
                   Select(Function(c) False))
    End Function
```

**Comment by gafter** [comment]
@VSadov Please verify this fix.
