### ISSUE TITLE
Different VB and C# behaviors for default interface parameter value

### ISSUE THREAD

**Issue by GeorgeAlexandria** [dotnet/roslyn#25493]
Hi,

I'm used **Visual Studio 15.6.1**.

I was surprised when found the different behaviors for **C#** and **VB** compilations for the same examples.

The **C#** code below perfectly compile but implementation has mismatched default parameter value.

```csharp
...
    interface IFoo
    {
        void Create(bool arg = true);
    }

    class Foo : IFoo
    {
        public void Create(bool arg = false)
        {
        }
    }
```

And the same **VB** code bellow doesn't compile (I expected this behavior)

```vb
...
    Interface IFoo

        Sub Create(Optional arg As Boolean = True)

    End Interface

    Public Class Foo
        Implements IFoo

        Public Sub Create(Optional arg As Boolean = False) Implements IFoo.Create
        End Sub

    End Class
```
Doesn't matter what kind of options I try to use for **VB** compilation, it doesn't compile anyway .

So, should these behaviors be the same and what behavior should be a correct?

**Comment by gafter** [comment]
The C# behavior is fine and by specification.

I didn't find anything in the VB specification that makes this an error. But I expect the right fix for that is to amend the specification.

**Comment by GeorgeAlexandria** [comment]
@gafter, I would be grateful if you can provide a link to the C# specification where this behavior is described (I couldn't find it) and I will post the same issue on the [vblang  home repository](https://github.com/dotnet/vblang)

**Comment by gafter** [comment]
The C# specification is at https://github.com/dotnet/csharplang/tree/master/spec and I expect you will not find anything "describing the behavior" here because there is nothing to describe. There is simply no error and each method has its own default (even though one implements the other).

**Comment by GeorgeAlexandria** [comment]
@gafter, "there is nothing to describe"  I can't agree with you, because the one concept of both languages has the different behaivors, so it should has a description to clarify this mismathes and VB spec (I finally found section that contains desciption) clarifies that the default values of optional parameters must match https://github.com/dotnet/vblang/blob/master/spec/general-concepts.md#implementing-methods

Well, I can think that the both behaviors are correct, but VB spec directly describes why he has this behavior.

**Comment by gafter** [comment]
The VB specification describes this situation as an error. The C# specification does not describe it as an error. That is the difference.

In C# you are always invoking either the method from the interface or the method from the class. It is always one or the other, and whichever one it is, that is the one you get your default value from.

We do not have a document enumerating the differences between the languages.

p.s. Did you know in C# it isn't an error to override a base class method with a method having a different parameter default value?

**Comment by GeorgeAlexandria** [comment]
@gafter, "Did you know in C# it isn't an error", no, I didn't know, but I could assume it after I opened this issue.

Anyway, as we discussed out the both situations are correct and VB spec clarifies it behavior, so I can think that the question was answered.

Thanks for your attentions)
