### ISSUE TITLE
[Discussion] Axum and/or Dataflows/Workflows

### ISSUE THREAD

**Issue by xunilrj** [dotnet/roslyn#2550]
(I known that I am grouping different things. It is just a brainstorming because I have searched some keywords and found nothing)

Axum seemed like a promising language. Unfortunately it died. Microsoft TPL Dataflow is sure a great framework. NEsper also have a DSL for dataflow, but I am thinking...

... does anyone sees anything in Axum, TDF or Nesper dataflow that would be great if have some kind of language support in c#? Or this kind of modelling is fully achieved with frameworks only? Or this concepts is so different that must be modelled in another language? Maybe Microsoft should opensource Axum?

I am thinking something like LINQ, with providers and everything. Something like LINDF (Language Integrated Dataflow) or LINW (Language Integrated Workflow)? 

Links:

Axum
http://download.microsoft.com/download/B/D/5/BD51FFB2-C777-43B0-AC24-BDE3C88E231F/Axum%20Programmers%20Guide.pdf

Microsoft TPL Dataflow
https://msdn.microsoft.com/en-us/library/hh228603.aspx

NEsper Dataflow
http://www.espertech.com/esper/release-5.2.0/esper-reference/html_single/index.html#dataflow

**Comment by svick** [comment]
One point to note is that both manipulating collections and querying SQL databases are *extremely* common operations, so improving those even by a little bit results in a huge gain overall. On the other hand, dataflow programming is much rarer, so I don't think having some language support specifically for that would be worth it.

(Personally, I would be interested in seeing some support for custom embedded DSLs, which could solve this in a more general way. But I don't see that happening any time soon.)

That being said, I do think that TPL Dataflow specifically can have very verbose syntax for simple dataflows (things like `new DataflowLinkOptions { PropagateCompletion = true }`). But I don't think improving that would require language support.

**Comment by HaloFour** [comment]
Smells like Rx and IQbservable maybe mixed with a little Cω (to make join patterns a little easier.)

**Comment by xunilrj** [comment]
@HaloFour 
when you say "a little Cω" do you suggest something like Cω Chords?
https://github.com/dotnet/roslyn/issues/1165

I am thinking somethig more like how LINQ works with IQueryProvider that would allow the Cω Chords to implemented, maybe something like MethodChordsProvider.

This first part of this post illustrates this:
http://community.bartdesmet.net/blogs/bart/archive/2009/08/11/statement-trees-with-less-pain-follow-up-on-system-linq-expressions-v4-0.aspx

**Comment by knat** [comment]
LINW (Language Integrated Workflow) -- greate name!
I've created one: #3209 :smile:

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
