### ISSUE TITLE
'use expression body for method' should not be offered on the comments preceding the method.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#25501]
![image](https://user-images.githubusercontent.com/4564579/37487074-a7c34efa-284d-11e8-9cb8-04fce9dbee21.png)

The right span should simply be the signature span of the method.  *Optionally* leading up to the beginning of the line that the method-modifiers/method-return-type are on.  It should not be on lines that only contain the comments/attributes of the method.

**Comment by jinujoseph** [comment]
related [link](https://developercommunity.visualstudio.com/content/problem/265779/expression-body-refactoring-comments-problem.html)
