### ISSUE TITLE
Omit Type for Generic Initialization

### ISSUE THREAD

**Issue by GrayOsmose** [dotnet/roslyn#25527]
We can initialize generics with initial data, but we still have to specify type of the generic. It would be nice to omit type defenition in that case.

Currently following statements are legal.

```C#
int[] array = { 1, 2, 3 };
var array = new[] { 1, 2, 3 };
var list = new List<int> { 1, 2, 3 };
var dictionary = new Dictionary<string, string> { ["key"] = "value" };
```
With syntax proposed in this topic you'd be able to write:

``` C#
var list = new List { 1, 2, 3 };           // List<int>
var dictionary = new Dictionary { ["key"] = "value" }; // Dictionary<string,string>
```

It is simmilar to how type `omit` works for `Generic Methods`.

```C#
...
public static T GetData<T>(T data) => data;
...

// type is omited in this case
var data = GetData(1);

```

Relates to #5865 issue.

**Comment by Neme12** [comment]
belongs to https://github.com/dotnet/csharplang/

**Comment by GrayOsmose** [comment]
Sure, will open there and colse this one. Thank you.
