### ISSUE TITLE
Screwdriver icon does not look like a screwdriver

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#25528]
I always see some sort of a paint brush until I remind myself it's supposed to be a screwdriver.

![image](https://user-images.githubusercontent.com/11444821/37526350-61f2e218-292f-11e8-85f2-d464ccd1be62.png)

Is it just me?

**Comment by CyrusNajmabadi** [comment]
It's not a screwdriver.  it's a Popsicle.  It's supposed to make you think that there will be something tasty for you if you open the dropdown.

**Comment by CyrusNajmabadi** [comment]
Tagging @olegtk

**Comment by Neme12** [comment]
I never found this weird because it would also seem like a reasonable icon sort of representing"cleanup", until I was told it is a screwdriver.

**Comment by olegtk** [comment]
this is hilarious. @jinujoseph  please send the bug to us we will route to the UX team

**Comment by gundermanc** [comment]
Rename the image catalog element to 'PaintBrush' and resolve the bug 💯

**Comment by jinujoseph** [comment]
:-) moved to editor [Link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/585425) cc @kuhlenh

**Comment by Neme12** [comment]
Wow, I found out I'm not alone :smiley: https://youtu.be/N5svo6N7ir0?t=37m49s
