### ISSUE TITLE
Code Editor: Jump to  the start or end of current block

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#25524]
**Version Used**: 
15.6.2

In code editor, Shift+Ctrl+UP and Shift+Ctrl+DOWN are used to jump to prev. and next highlighted word.
Also, Ctrl+] is used to jump to the matching brace to the currently highlighted one. 
I think if you are in the middle of a block, there is no direct way to jump to the start or end of the block. 
So, if there is no word  currently highlighted, I suggest to 
-	use Shift+Ctrl+UP and Shift+Ctrl+DOWN to jump directly to the block start and end respectively
-	use Ctrl+[ and Ctrl+] to jump to the next opening and closing brace respectively.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.  This would also be better as an LSP command.
