### ISSUE TITLE
StackOverflowException in Emit tests

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#25539]
A few signed build failures have come from:
```
2018-03-16T18:20:56.0273975Z          Errors Roslyn.Compilers.CSharp.Emit.UnitTests.dll: 
2018-03-16T18:20:56.0274726Z          
2018-03-16T18:20:56.0275282Z          Process is terminated due to StackOverflowException.
```
I don't have any logs at this point to say what test is actually causing the overflow. Both failures I've seen in the signed builds thus far have come from the dev15.7.x-vs-deps branch. I know @jasonmalinowski saw another one yesterday, any chance there's a log to look at? @dotnet/roslyn-compiler for triage.

**Comment by 333fred** [comment]
https://devdiv.visualstudio.com/DevDiv/_build?buildId=1484916&_a=summary&tab=details
https://devdiv.visualstudio.com/DevDiv/_build?buildId=1486563&_a=summary&tab=details

**Comment by jaredpar** [comment]
Looks like the problematic test is     Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.EndToEndTests.OverflowOnFluentCall

**Comment by gafter** [comment]
I believe we have now adjusted the limits for this test.  Please open a new bug if this recurs.
