### ISSUE TITLE
Missing rude edit: format in interpolated string

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#2554]
I had this string ```$"= {hours:d2}:{minutes:d2}:{seconds:d2}.{millis:d4}"``` and I realized that the last segment should actually have three digits, so I changed ```d4``` to ```d3```.  However, the result of the expression didn't change, presumably because ```d4``` is effectively a string constant.

**Comment by wschae** [comment]
Should be fixed by #4159
