### ISSUE TITLE
Add refactoring to convert between default literal/expression and other literals

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#25556]
*from #25456*

> Generally speaking, this fixer should offer null as a simplification of default(T) when T is a reference type or nullable value type, 0m when T is decimal, 0 when T is another numeric type, false if T is bool, and '\0' if T is char.

It would be nice to have refactorings to
1. convert from a default literal / default expression to another literal (such as 0, null or false)
2. to convert such literals back to a default literal, or if the user's preference of using default literals is set to false, a default expression instead

**Comment by sharwell** [comment]
We covered this in today's design review, and felt that a conversion from `default` or `default(T)` to a literal value (where available) would be reasonable. It did not seem advantageous to offer the reverse as a refactoring, and it also wouldn't need to be an analyzer.

**Comment by Neme12** [comment]
@sharwell Should there then be a separate refactoring from `default` or `default(T)` to a literal, *or* could that be implemented as part of #30464?

**Comment by Neme12** [comment]
The obvious implementation of "inline constant" would cover this as well (expect for all the special cases for enums/CancellationToken).

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
