### ISSUE TITLE
Compilation fails with (nested) project references

### ISSUE THREAD

**Issue by JBildstein** [dotnet/roslyn#25555]
**Version Used**: 

Microsoft.CodeAnalysis 2.7.0
Microsoft.Net.Compilers 2.7.0
Microsoft.Build 15.6.82

**Steps to Reproduce**:

[MultiProjectRepro.zip](https://github.com/dotnet/roslyn/files/1821772/MultiProjectRepro.zip)

1. Open attached solution and run the MultiProjectRepro project
2. See the error output for the second and third project
3. In Program.cs, set the `fixFirstError` variable to `true` (line 16) and run again
4. See the error output for the third project

Short description of what it does: 
The MultiProjectRepro project loads and compiles three .Net Standard library projects and checks for compilation errors.
Those three library projects are referenced in a chain, i.e. Lib3 references Lib2 and Lib2 references Lib1.

**Expected Behavior**: 
All three projects should compile without errors.

**Actual Behavior**: 
The second projects needs the metadata references from the first  project and the third project fails even when adding metadata references from the first and second project.

Errors from the second and third project without the first fix:
```
CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
CS0518: Predefined type 'System.Object' is not defined or imported
CS0518: Predefined type 'System.Void' is not defined or imported
CS0518: Predefined type 'System.Void' is not defined or imported
CS0518: Predefined type 'System.Object' is not defined or imported
CS0103: The name 'Console' does not exist in the current context
CS0518: Predefined type 'System.String' is not defined or imported
CS0518: Predefined type 'System.Object' is not defined or imported
CS0518: Predefined type 'System.Object' is not defined or imported
CS0518: Predefined type 'System.Void' is not defined or imported
CS0518: Predefined type 'System.Object' is not defined or imported
CS0518: Predefined type 'System.Void' is not defined or imported
CS1729: 'object' does not contain a constructor that takes 0 arguments
```
Errors from the third project with the first fix
```
CS0518: Predefined type 'System.Void' is not defined or imported
CS0518: Predefined type 'System.Void' is not defined or imported
```

**Notes**:
I have also tried to add an explicit reference from the third to the first project but it makes no difference.

**Comment by jcouv** [comment]
@JBildstein From quick look, your issue sounds like one I'd had encountered before. Here's [some info on solution](https://github.com/dotnet/roslyn/issues/24308#issuecomment-362362524) you may want to try, assuming it's indeed the same problem.
