### ISSUE TITLE
Unexpected CS0108 (method is hiding other derived method)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25578]
Example:
```C#
using System;
class A {
    public void Scream()
    {
        Console.WriteLine("Error");
    }
}

class B : A
{
    private void Scream() // warning CS0108: 'B.Scream()' hides inherited member 'A.Scream()'. Use the new keyword if hiding was intended.
    {
        Console.WriteLine("Hiding"); 
    }
}
```
new I().Scream() // prints Error aka A.Scream !
Which means it's not hidden, then why itellisense warns of hiding it?

The access modifier is changed, so I'm not hiding it, right?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/213059/intellisense-falsely-reports-method-is-hiding-othe.html
VSTS ticketId: 580864_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This feels by design.  After all, if you had this code:

```c#
class B : A
{
    private void Scream() // warning CS0108: 'B.Scream()' hides inherited member 'A.Scream()'. Use the new keyword if hiding was intended.
    {
        Console.WriteLine("Hiding"); 
    }

    void Foo(B b)
    {
        b.Scream(); // this is calling the new method, because B.Scream hit A.Scream.
    }
}
```

**Comment by gafter** [comment]
This is by design. Anywhere within the body of `B`, `Scream` refers to the hiding method.
