### ISSUE TITLE
Bad highlighting in VS style options preview

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#25573]
Go to code style options in C# and select "Prefere local function over anonymous function".
Expected behavior when clicking on the pieces of code:
![highlighting2](https://user-images.githubusercontent.com/11444821/37571137-eecf74b0-2af8-11e8-9327-e2fd715ab116.png)

actual behavior:
![highlighting1](https://user-images.githubusercontent.com/11444821/37571139-f329989c-2af8-11e8-84ff-9db9acabfd3d.png)

Similar highlighting issues happen with most other options that have the Prefer... Over form.

**Comment by sharwell** [comment]
@Neme12 this is my favorite bug report in a long time
