### ISSUE TITLE
Formatting a method with the formatter annotation indents it at the wrong level

### ISSUE THREAD

**Issue by Vannevelj** [dotnet/roslyn#2557]
I have an analyzer and accompanying code fix that makes a method with a `[Test]`, `[TestMethod]` or `[Fact]` attribute `public`. When recreating the `Modifiers` list I end up with a badly indented method. In order to solve this I apply `Formatter.Annotation` to my method and call the formatter. This results in a formatted method but the method itself is indented a level too low: it's the same as class level.

Is this a bug or am I doing something wrong? Note that I have solved this temporarily by prepending the existing leading trivia to the `public` token.

This is the output:

    using System;
    using System.Text;

    namespace ConsoleApplication1
    {
        [TestFixture]
        public class MyClass
        {
        [Test]
        public void Method()
        {

        }
    }
    }

Relevant Code Fix code:

	private Task<Solution> MakePublicAsync(
                  Document document, 
                  SyntaxNode root, 
                  MethodDeclarationSyntax method)
	{
	    var removableModifiers = new[]
	    {
	    	SyntaxFactory.Token(SyntaxKind.InternalKeyword),
	    	SyntaxFactory.Token(SyntaxKind.ProtectedKeyword),
	    	SyntaxFactory.Token(SyntaxKind.PrivateKeyword)
	    };
	
	    var modifierList = new SyntaxTokenList()
	    	.Add(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
	    	.AddRange(method.Modifiers.Where(x => 
                              !removableModifiers.Select(y => y.RawKind).Contains(x.RawKind)));
	
	    var newMethod = method.WithModifiers(modifierList)
                              .WithAdditionalAnnotations(Formatter.Annotation);
	    var formattedMethod = Formatter.Format(
                   newMethod, 
                   Formatter.Annotation, 
                   document.Project.Solution.Workspace, 
                   document.Project.Solution.Workspace.Options);
	
	    var newRoot = root.ReplaceNode(method, formattedMethod);
	    var newDocument = document.WithSyntaxRoot(newRoot);
	
	    return Task.FromResult(newDocument.Project.Solution);
	}

Full code:

* [Analyzer](https://gist.github.com/Vannevelj/62ce2d27053ad416896f)
* [Code Fix](https://gist.github.com/Vannevelj/f86f95f1c526a9fa44bd)
* [Tests](https://gist.github.com/Vannevelj/a11a472aa5ed3df922f4)

 I was referred [here](http://stackoverflow.com/questions/30031280/formatting-a-method-signature-loses-indentation#comment48283285_30032270) by @Pilchie.

**Comment by Pilchie** [comment]
@mattwar can you take a look?

**Comment by mattwar** [comment]
I'll verify tomorrow, but it looks like the cause is that the formatter is being called just on the modified method node, which doesn't belong to the tree anymore so it doesn't provide the formatter any context for the formatting.  The correct way to do this would be to replace the node in the tree root first and then call format on the new root.

```
var newRoot = root.ReplaceNode(method, newMethod);
var formattedRoot = Formatter.Format(newRoot, Formatter.Annotation, document.Project.Workspace);
```

However, it is unnecessary to call the formatter directly in a code fix since the code fix infrastructure will call the formatter on the returned document anyway.  

Also, the SyntaxGenerator API has a method, WithAttributes, that can be use to change the accessibility of a declaration node. 

```
using Microsoft.CodeAnalysis.Editing;
...
var g = SyntaxGenerator.GetGenerator(document);
var newMethod = g.WithAttributes(method, Accessibility.Public);
var newRoot = root.ReplaceNode(method, newMethod);
var newDoc = document.WithSyntaxRoot(newRoot);
```

**Comment by Vannevelj** [comment]
@mattwar: I can't seem to make it work using your advice. No matter where I add the `Formatter` annotation and whether or not I call `Formatter.Format` explicitly, the indentation remains incorrect.

The `SyntaxGenerator` looks interesting but it looks like we have different versions: the `SyntaxGeneratior.GetGenerator()` overload I have requires 2 arguments and does not contain a `WithAccessibility()` method. Am I using an outdated library?

**Comment by mattwar** [comment]
You'll probably need at least the version of Roslyn that is out with VS RC from last week.

**Comment by Vannevelj** [comment]
I'm using VS 2015 RC and the RC Roslyn SDK templates.

**Comment by mattwar** [comment]
If you change the code to call format on the new tree root after you've replaced the new method, instead of formatting the method and then replacing it into the tree, you will get the correct formatting.

```
var newRoot = root.ReplaceNode(method, newMethod);
var formattedRoot = Formatter.Format(newRoot, Formatter.Annotation, document.Project.Workspace);
```

**Comment by Vannevelj** [comment]
I don't know what to tell you, but that doesn't work according to my unit tests. Is there any chance this is solved in an unreleased update? Am I supposed to update something myself?

If you feel like testing my specific scenario, you can find the code here: https://github.com/Vannevelj/VSDiagnostics.

**Comment by Vannevelj** [comment]
@mattwar I have found the culprit! Namely: me. In my unit tests, the strings were defined as such:

            var original = @"
        using System;
        using System.Text;

        namespace ConsoleApplication1
        {
            class MyClass
            {   
                void Method(Nullable<int> myVar = 5)
                {
                
                }
            }
        }";

Notice the extra tab in front of each line. I realized this when I changed the testing framework to NUnit which tells you the length of the strings when you compare them using `Assert.AreEqual()`: it always indicated a 4-character difference. After removing this unnecessary tab, everything passes as expected. It's still a little bit strange considering both my original and expected sourcecode contains the leading tabs, but I assume that the Roslyn formatter doesn't take into account when an entire document is intended at the second level.

I should note that prior to discovering this I switched to the RC3 nightly build, but I don't believe this had any influence on it.

**Comment by basoundr** [comment]
@Vannevelj This is the intended behavior. Roslyn Formatter expects the entire document to be formatted in a particular format. In this particular case, the annotation was added to a small piece of code and hence only that particular code got formatted. The rest of the code, whether formatted right or wrong, will remain untouched.
