### ISSUE TITLE
Variable name missing from completion after <

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#25572]
**Version Used**: 
Roslyn 2.7.0 that shipped in VS 15.6

**Steps to Reproduce**:

1. Create new C# console app
2. Replace the Program.cs text with this
```
using System.Collections.Generic;
using System.Linq;

class C
{
    void M()
    {
        int foo;
        List<int> list;
        if (list.Count < $$)
        {
        }
    }
}
```
3. Retype $$

**Expected Behavior**:
The identifier `foo` should be in completion

**Actual Behavior**:
It is not in completion

**Comment by CyrusNajmabadi** [comment]
This may be an unfortunate series of events:

1. This looks like you could be typing a partially generic method call.
2. We are able to find a generic extension method Enumerable.Count.  

So, we think you're in a types-only context.

**Comment by KirillOsenkov** [comment]
Yes, I do see completion, looks like it's types-only context indeed.
