### ISSUE TITLE
Enhance Change Signature to allow promotion of return value to out ref parameter

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25582]
Given a function that returns a value, allow me to promote the return value to an out parameter in Change Signature.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/206947/enhance-change-signature-to-allow-promotion-of-ret.html
VSTS ticketId: 576042_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by allisonchou** [comment]
There has been an ask to consolidate Change Signature feature requests into one issue. Since this enhancement is being tracked by the overarching issue #33977, will close as a dupe.
