### ISSUE TITLE
Inccorect 'Null check can be simplified'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25588]
The null check of a generic argument must be done with a 'if', but intelisense says we can simplified with the '??' operator. But the '??' operator is valid only if the Type of the generic argument has the 'class' constraint, the intellisense don't care about that.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/211735/inccorect-null-check-can-be-simplified-1.html
VSTS ticketId: 579839_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Neme12** [comment]
I tried to reproduce this in 15.6.2 but only get the fix offered if I add a class constraint. Could you try updating to a new version and see if the problem persists? Thanks!

**Comment by Neme12** [comment]
This seems like it got fixed in #24173 but merged into 15.7? Maybe there's something wrong with my setup.

**Comment by thomasouvre** [comment]
@Neme12 I updated my VS from the 15.5.7 to 15.6.3 version and it's now fixed. Thank you !
