### ISSUE TITLE
C# "create and initialize property" lightbulb gives "wrong" type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25587]
1) Create new struct, foo
2) Create a ctor for it
3) Add parameter to ctor -- foo(int x)
4) You get a lightbulb that lets you create a property or field for the parameter.
5) This works, but gives the new property/field a data type of &quot;Int32&quot; instead of &quot;int&quot;.
6) Ditto for other built-in types, including &quot;string&quot; that gives &quot;String&quot; (note initial capital).

This is correct, but not what I'd expect (or want).

I'm running VS 15.6.2

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/216383/c-create-and-initialize-property-lightbulb-gives-w.html
VSTS ticketId: 584189_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Neme12** [comment]
I can't reproduce this. Can you reproduce this in a new project? Could you provide some info about what project type or framework version you're using along with sample code? Thanks!

**Comment by Neme12** [comment]
Are you sure your preferences aren't set to "Prefer framework type"? If you go to Tools->Options->Text Editor->C#->Code Style->predefined type preferences make sure you have "Prefer predefined type" selected.

**Comment by CyrusNajmabadi** [comment]
Not repro for me either, and original filer has not responded to the questions that likely indicate teh root cause.  clsoing out.
