### ISSUE TITLE
Change Signature dialog provides no keyboard accelerator for OK button

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25580]
When using Change Signature to add parameters, the Change Signature dialog has no accelerator for the OK button.  This means I have to leave the keyboard and use the mouse or press TAB an inordinate number of times to get to the button.  It should have a keyboard accelerator (&amp;O) or it should have the default dialog accept focus.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/206935/change-signature-dialog-provides-no-keyboard-accel.html
VSTS ticketId: 576033_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jcouv** [comment]
Fixed in 15.8
