### ISSUE TITLE
Could not load file or assembly 'netstandard, Version=2.0.0.0

### ISSUE THREAD

**Issue by Foroughi** [dotnet/roslyn#25586]
Hi
After I install the Vsix file on VS 2017 (15.6.1) I got the following error for each analyzer i have inside my project :

`Warning AD1000  An instance of analyzer {AnalyzerName} cannot be created from {UserDir}\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_ED9751FD\EXTENSIONS\JHLRIAYO.RAN\{Ext Name}.dll: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.The system cannot find the file specified.`

Based on what i read in others posts like this there should be a mismatch version somewhere but i can not find. 
Just inform you about the situation here is the structure of solution : 

### MainProject (.Net Standart Class library)
Framework Version : 
4.6.1
References : 

- Microsoft.CodeAnalysis.CSharp.Workspaces (2.4.0)
- NETStandard.Library (2.0.1)
- Second Library

### MainProject.Vsix (Vsix project)
Framework Version : 
4.6.1
References : 
- Main Project 
- Second Library

### SecondLibrary (.Net Standart Class library including some classes)
Framework Version : 
4.6.1
References : 
- Microsoft.CodeAnalysis.CSharp.Workspaces (2.4.0)
- NETStandard.Library (2.0.1)

**Comment by Foroughi** [comment]
I check that `{UserDir}\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_ED9751FD\EXTENSIONS\JHLRIAYO.RAN\` folder and I noticed that.Net Standard libraries are missing, So I copied those libraries from MainProject.Vsix bin folder to that folder and restarted vs. my analyzers work now, but how can I copy those files during the Vsix installation process!

**Comment by Foroughi** [comment]
Problem solved by adding this code to vsix csproj file : 

```
<Target Name="IncludeNETStandardFacadeInVSIX" AfterTargets="ImplicitlyExpandNETStandardFacades">
  <ItemGroup>
    <Content Include="@(_NETStandardLibraryNETFrameworkLib)" Condition="%(Filename) == 'netstandard'">
      <IncludeInVSIX>True</IncludeInVSIX>
      <VSIXSubPath>/</VSIXSubPath>
    </Content>
  </ItemGroup>
</Target>
```

**Comment by gafter** [comment]
@Foroughi Should we close this issue?

**Comment by Foroughi** [comment]
@gafter , yeap , problem has been solved

**Comment by jmarolf** [comment]
> Are analyzers compiled against .NET Standard 2.0 a supported scenario in Visual Studio?

They are not.  Currently the highest recommended version is NET Standard 1.3.  If you target .NET Standard 2.0 it will be impossible for you to deploy the correct set of framework assemblies to consumers of the analyser as they need different versions depending on whether they are running on .NET Framework 4.6, 4.6.1, 4.7.0 or 4.7.1.

@Foroughi is there some set of APIs available in  .NET Standard 2.0 that is forcing you to pick that as a target?

**Comment by jmarolf** [comment]
> What do you recommend?

@Foroughi I chose to have the Roslyn templates (source here: https://github.com/dotnet/roslyn-sdk) default to using .NET Standard 1.3.  I would recommend changing you project back to caontaining this:
```XML
 <TargetFramework>netstandard1.3</TargetFramework>
```

> As I long as I know the previous version was based on VSix file. Then they found out that they can make analyzer based on Nugget Packages. 


The default analyzer project creates botha nuget package and a VSIX on build in VS 2017

**Comment by jaredpar** [comment]
@jmarolf has the right analysis here.

**Comment by jmarolf** [comment]
@Karvan performance is orthogonal in this case.  This is about being able to correctly load your assemblies and is unrelated to performance

**Comment by silviacampo** [comment]
I have the same problem and got fixed when updating the .NET Framework from 4.6.2 to 4.7.1
