### ISSUE TITLE
Show captured variables in quickinfo for query syntax

### ISSUE THREAD

**Issue by MaStr11** [dotnet/roslyn#25593]
### Customer scenario
Quickinfo was extended in #23970 to show captured variables for local functions and lambdas and #23049 enabled quick info for query syntax. This issue is about bringing both together like this:

![2018-03-19 14_21_04-](https://user-images.githubusercontent.com/24472128/37597855-ddcb7294-2b80-11e8-9651-1472ba5d02a9.png)

### User interface

I did a prototype for the `where` clause and it turned out to be quite complicated. There are several areas that need to be discussed.

#### How should captured variables be shown.

The `where` clause is bound to e.g. the `Enumerable.Where<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)` method. Quick info shows the ISymbolInfo for this method but any captures would takes place in the `predicate` parameter. There are at least three ways how this problem can be solved:

1. Show the captured variables on the appropriate keyword 

The quickinfo implementation in #23049 already maps tokens of a query to IMethodSymbols. Most of these methods have exactly one parameter that takes a lambda, so there is a one to one relationship between the method and the lambda parameter to show captured variables for. If there is more than one parameter that takes a lambda (e.g. `GroupJoin<TOuter, TInner, TKey, TResult>(this IEnumerable<TOuter> outer, IEnumerable<TInner> inner, Func<TOuter, TKey> outerKeySelector, Func<TInner, TKey> innerKeySelector, Func<TOuter, IEnumerable<TInner>, TResult> resultSelector);`) the captures for all lambdas could be shown (The captures could be bound to particular key words e.g. captures of `outterKeySelector` could be shown on `on` and `innerKeySelector` could be shown on `equals`).

2. Show the captured variables on the expression that represents the lambda parameter

Instead of the keyword the capture information is shown along the quick info for the expression. This could be combined with 1.

3. Show always all captured variables

The query expression is analyzed as a whole and every lambda parameter of every method involved is taken into consideration. Every quick info shown above any part of the query always shows all captured variables.

#### What about range variables

AFAIK range variables are created by e.g. `let` and passed using anonymous types from one method to the next in the chain. This shouldn't involve any capturing.

#### What about `IQueryable` and `Expression`

It is arguable if a variable captured in e.g. LinqToEntity is really a captured variable as the whole construct is never actually executed. I would say that it is still a valuable information to see which parts of the query are purely internal and which parameters are coming from the outside.

### Implementation

The current entry point for collecting capture information is [AbstractSymbolDisplayService.AddCaptures(ISymbol symbol);](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/LanguageServices/SymbolDisplayService/AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.cs#L185). The method is called once the ISymbol to display quick info for is calculated. The ISymbol for the `where` clause is e.g. the extension method `Enumerable.Where`. What we actually need is the ISymbol of the lambda associated with the predicate. This symbol is retrievable via (pseudo code):

```CS
var whereConditionExpression = whereClause.Condition;
var operation = semanticModel.GetOperation(whereConditionExpression, cancellationToken);
var anonymousFunction = operation.GetParent(OperationKind.AnonymousFunction) as IAnonymousFunctionOperation;
var symbol=anonymousFunction?.Symbol;
```

This means we have several ISymbols for QuickInfo. One for the bound method and one or more for the anonymous functions passed to the method. The latter is only needed for the AddCaptures logic. In the prototype I just added the ISymbols for the captures to the ISymbols array for QuickInfo. This leads to the `(+1 overload)` message marked red in the screenshot above (and all kinds of other issues). Depending on the UI design we need to find another solution for this problem.

/cc @sharwell @jcouv @CyrusNajmabadi

**Comment by MaStr11** [comment]
I started a prototype that allows to implement 1. 2. or 3. I currently implemented 2. and it looks like this:

![querycaptures](https://user-images.githubusercontent.com/24472128/37878190-4027c080-3065-11e8-8e3f-ea4b5430b01a.gif)

To support this scenario I needed to do some major changes to the SematicQuickInfo infrastructure. As described above the main issue is that there is a mismatch between the symbol that quick info is showing information (a method that takes one or more delegates) for and the capturing of variables (takes place in the delegates passed to that method). I solved that mismatch by passing more information to the `ISymbolDisplayService.ToDescriptionGroupsAsync` method. This method took a list of ISymbols to display information for. Now it also takes a list of SyntaxNodes to calculate captured variables. This work was done [here](https://github.com/MaStr11/roslyn/commit/75d88161d9cf2051762a4450b2661565a86389d9). Based on that foundation showing captures is fairly easy and flexible as shown [here](https://github.com/MaStr11/roslyn/commit/c1cdc4c58b38f7872c0a6e53723478801c708968).

This work lives in this [branch](https://github.com/MaStr11/roslyn/commits/ShowCapturesInQuerySyntax) right now. I can't create a PR at the moment because doing so either requires VS 15.7 preview or the PR contains some unrelated commits.

@sharwell It would be nice to get your thoughts about this feature.

**Comment by CyrusNajmabadi** [comment]
> I can't create a PR at the moment because doing so either requires VS 15.7 preview or the PR contains some unrelated commits.

Can you just create hte pr and call out the sections to ignore for now?  i'd really prefer to look at it there in a form i can comment on.

**Comment by MaStr11** [comment]
@CyrusNajmabadi Done: #25711 and thanks for taking care.

**Comment by MaStr11** [comment]
@sharwell I need some feedback from the IDE team. I'm especially interested in whether they

* Want this feature at all, and if so 
* What it should look like

I'm in favor of displaying it on the keywords (as does @CyrusNajmabadi [gitter.im](https://gitter.im/dotnet/roslyn?at=5ab80a64c574b1aa3e300d3c)). Here is my pros/cons list

### Display over keyword

#### Pros:

* Shows the info in conjunction with the high-order-function. That is close to where the capturing takes place.
* Works great for the places where capturing is likely (`let`, `where` and `select`) because the high order functions involved here are taking a single lambda and the mapping is quite obvious
* Even works for `orderby` if the same rules are applied as for the shoeing the signature (e.g. using the comma as a trigger to show the signature and captures of `ThenBy`)
* Should work for high order functions taking more than one lambda (e.g. inner join takes several lambda parameter but also has a lot of keywords. A mapping should be possible.)
* Is cheap at runtime because the logic is only triggered on well defined keywords.

I was thinking about displaying the name of the lambda parameter next to capture info, like so: In case of `where i == capture` we could display the symbol info with:

`Enumerable.Where<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)`

And the capture like this:

Variables captured by **'predicate'**: capture

I think this could be possible by following the conventions that describe how the query syntax is mapped/bound to the high order functions.

#### Cons:

* It's technically wrong (The keywords are showing the signatures of the high order function. The capturing is taking place in the parameters of the high order function.). That's the exact reason, why I was thinking about displaying the parameter name.
* Requires some kind of planning/proposal (which capturing lambda parameter is displayed on which keyword)

### Display over expression

#### Pros:

* The capturing is shown at the place were the capturing really happens
* Does work even in the most complicated cases
* Doesn't need a proposal

#### Cons:

* It's irritating, because the capturing info is not really related to the symbol info that is displayed (see the animated screencast above: e.g. The capturing is displayed below the == operator, the + operator or the range variable. None of these are involved in the capturing)
* It's slightly more expensive as it requires a walk up the syntax tree to see whether the actual node belongs to some kind of query syntax (not a big issue though)

**Comment by CyrusNajmabadi** [comment]
When you say "Display over expression" can you clarify what the user is actually hovering over?

--

Notes: looking at the cons for 'Display over keyword', these don't really seem like cons to me.  For example:

> It's technically wrong (The keywords are showing the signatures of the high order function. The capturing is taking place in the parameters of the high order function.). That's the exact reason, why I was thinking about displaying the parameter name.

It seems technically fine to me.  This 'clause' caused certain lambdas to be created.  Those lambdas captured values or they didn't.  I just want to know what was captured.  I've got that answer.  I don't really need to know or care which specific lambda caused the capture IMO.

> Requires some kind of planning/proposal (which capturing lambda parameter is displayed on which keyword)

As you mentioned, for most keywords, there's only one.  So the answer there is clear.  If there are cases where there is more than one (could you list those btw?) like 'join', then just aggregate all the values that are captured.  i.e. if i hover over:

```join x in y on a equals b```, then i don't mind if this says: "Captures: 'x', 'y', 'a', 'b'".

**Comment by MaStr11** [comment]
> When you say "Display over expression" can you clarify what the user is actually hovering over?

One could say the capture info is displayed on everything between two keywords that causes quick info to appear. You can see it in the screen cast above when I hover over ToString, capture6, i, == and +.

**Comment by CyrusNajmabadi** [comment]
>One could say the capture info is displayed on everything between two keywords that causes quick info to appear. You can see it in the screen cast above when I hover over ToString, capture6, i, == and +.

yeah... i find that very confusing :)

**Comment by MaStr11** [comment]
> where there is more than one (could you list those btw?) like 'join', then just aggregate all the values that are captured.

I will do the list tomorrow (on the phone now). I will base this on the [query pattern](https://github.com/MaStr11/roslyn/blob/fce28d03dd6872b283757f092fe2ae7eabc95bb9/src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionTests.vb#L2304-L2334).

 It's also worse taking a look at VB (e.g the aggregate keyword) for the planing to keep the experience consistent. The join case is handled the way you described it in the prototype so you can see it in the screen cast (the display of the variables is a little bit broken).

**Comment by CyrusNajmabadi** [comment]
Honestly, thinking aobut it more, i'd also be ok with the quick info showing the captures only when hovering over the first "from".  Basically, to me, the only thing interesting is "does my query capture anything, and if so, what?"  It's the same thing you want to know for a lambda/local-function.

So, i'm fine with this on individual keywords.  But i think that's actually more painful for a user as they have to check 'n' keywords.  I think it would just be better to roll it all up as information you provide on the query itself.  

Thoughts?

**Comment by MaStr11** [comment]
This like option 3. What I like about it is that we could use the first from. This keyword doesn't show anything right now.

On the other hand you only have to check were, select, let and maybe orderby in practice because on the other keyword you hardly ever capture. Then again I do remember having writen a query with maybe 20 let clauses in it in the past.

Note: displaying on the first from will be challenging as we need to force the SymbolDisplayService to show the capture info while there isn't any symbol.

**Comment by CyrusNajmabadi** [comment]
> Note: displaying on the first from will be challenging as we need to force the SymbolDisplayService to show the capture info while there isn't any symbol.

This doesn't ahve to be part of SymbolDisplayService at all.  This can be entirely part of quick info.

**Comment by CyrusNajmabadi** [comment]
> On the other hand you only have to check were, select, let and maybe orderby in practice because on the other keyword you hardly ever capture. Then again I do remember having writen a query with maybe 20 let clauses in it in the past.

I'd like to drive this from a perspective of user value and solving real problems a user may have.  I'm not sure if i can envision a case where a user comes along and says "i want to know if this specific clause captures anything".  On the other hand, i absolutely can see them saying "what method did this part of the query bind to?".   However, it *is* very reasonable for them to ask "does this query capture anything?", just like they woudl for a lambda/local-function.  

So, to me, the real feature is: allow a user to figure out if a query captures things.  And, the most sensible and consistent place for that in both VB and C# is just on hte initial from-keyword.  This can all be done within quick info.

**Comment by MaStr11** [comment]
@sharwell  Can anybody from the IDE team weigh in here? We have several options on the table and it would be good to hear what the IDE team prefers.

**Comment by jcouv** [comment]
@kuhlenh Can this be added to agenda for next IDE design meeting?

**Comment by jcouv** [comment]
@MaStr11 It looks like this will be discussed by IDE team tomorrow. I'll update afterwards.

**Comment by MaStr11** [comment]
The IDE team decided to abandon this feature in favor of the semantic classification feature.

From @jcouv https://github.com/dotnet/roslyn/pull/25711#issuecomment-378422277

> The conclusion is that we would rather not take this approach (QuickInfo on LINQ query to show captures) after all and instead make the semantic classification feature serve the scenario (highlighting places where something is captured).
One consideration is that we don't expect code that uses LINQ queries to be very performance sensitive. This rules out showing very granular QuickInfo capture information, as the benefit would not outweight the real-estate cost.
So if the proposed classification approach doesn't work (I'm not sure it can be designed sensibly and cheaply, because querying for capture information requires to select a region first...), then we would fall back to the QuickInfo approach, with a preference with showing a single set of captures for the entire query.

This issue can be re-opened in case the classification approach doesn't work.

**Comment by Joe4evr** [comment]
![](http://i0.kym-cdn.com/entries/icons/original/000/000/854/vader_NOOOO.jpg)
