### ISSUE TITLE
Incorrect "case already handled" with tuples in features/recursive-patterns

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#25591]
**Version Used**: 68c9801, the latest commit on features/recursive-patterns

**Steps to Reproduce**:

Try to [compile the following code](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgDQwgEI5gCeAPgAIBMABAMICwAKADeQ7uO7sALNwCyACgD2wAFYQMMbooCUYiaMESj3ZAHccMDAAtu8pdW4AGbbsPHxB9+4xRkEWwBiiorcYMEOAPraIHpeXsBIUADWANyxcdw+frYAQlAI3MD5kdHpGRIJ0KllEgC+6fWCjUJc3EEhwtzNgq15BZ21QA==):

```c#
class C
{
    void M(object o)
    {
        switch ((o, 0))
        {
            case (Foo foo, _):
                break;
            case (Bar bar, _):
                break;
        }
    }
}

class Foo { }

class Bar { }
```

**Expected Behavior**:

The code compiles.

**Actual Behavior**:

The second `case` produces:

> error CS8120: The switch case has already been handled by a previous case.

I realize that the branch is just a prototype. So, my question is: is this currently expected to work? If this is a known problem due to the branch being a prototype, feel free to close this issue.

**Comment by gafter** [comment]
That branch is a little behind due to code reviews taking a while (hint @agocke). My current branch https://github.com/gafter/roslyn/tree/rpatterns10 handles this just fine. I'll add a test for it.

**Comment by gafter** [comment]
Test added in #26018
