### ISSUE TITLE
Proposal: support await in Catch and Finally in VB

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#256]
VB does not currently allow an await expression in a Catch block or a Finally block.

Remove this restriction.

**Comment by AdamSpeight2008** [comment]
Highly likely due to co-evolution promise.

**Comment by gafter** [comment]
@AnthonyDGreen You might want to consider this in your current investigation.

**Comment by AnthonyDGreen** [comment]
It was always our intention to do this going back to VB14. It was only a last minute scheduling issue that delayed it.

**Comment by gafter** [comment]
This is now tracked at https://github.com/dotnet/vblang/issues/37
