### ISSUE TITLE
GetCompilationAsync() taking so much time

### ISSUE THREAD

**Issue by RipPer56** [dotnet/roslyn#25600]
**Version Used**: 2.7.0

**Steps to Reproduce**:
I'm trying to get the compilation of a project that references around 500 other projects and it taking more than 20 minutes. 

The problem is that it took only a minute in an older version 2.6.0 or 2.6.1. And since the upgrade upgraded other nuget packages like typedParts and immutable.. i can't possibly know their older version too so i'm stuck with 15 - min for projects that are referencing too many projects.

**Comment by CyrusNajmabadi** [comment]
Are these projects different languages?  Or are they all C# or all VB?

Also, could you collect a performance trace?  Instructions here: https://github.com/dotnet/roslyn/wiki/Performance-Investigations

Just tracing a couple of minutes of this should provide very usable results.  Thanks!

**Comment by RipPer56** [comment]
All are in c#. The problem is it used to takes less than 2 minutes so i don't know what happend.

**Comment by RipPer56** [comment]
Also, when i say a project references 500 projects i means transitively and not directly ofc.

**Comment by CyrusNajmabadi** [comment]
Ok.  That rules out one thing: building skeletons for cross-language metadata.

A trace would be very helpful.  And/or just provide the project you're having problems with.

**Comment by RipPer56** [comment]
I'm having problem with all projects that are referencing too many projects. I'll try to get a trace because i'm not allowed to get any information of the company i work at. 
Also is there any versions of **System.Collections.Immutable** or **System.Composition.TypedParts** or any other package that i should work with because it's the last update that updated everything else is whta caused this problem.

**Comment by RipPer56** [comment]
I just found out that there are some cpp projects so is there any way to skip them while trying to get the compilation.
