### ISSUE TITLE
Wrong Cast is redundant with Option Strict On in VB

### ISSUE THREAD

**Issue by ehasis** [dotnet/roslyn#2560]
In a VB.NET project with Option Strict On the following code with += operator trigger "Cast is redundant" but when apply the fix, the code became broken:
```vb
Dim b As Byte
b += CByte(1) ' IDE0004 Cast is redundant
```
After the fix:
```vb
Dim b As Byte
b += 1 ' Option Strict On disallows implicit conversions from 'Integer' to 'Byte'.
```
This happens with any data type requires explicit conversion.

**Comment by DustinCampbell** [comment]
Looks like the problem is really around compound assignment statements. It works properly if I expand the compound assignment:

```VB
Dim b As Byte
b = b + CByte(1)
```
