### ISSUE TITLE
Decompiler should add a file header on top like Metadata As Source

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#25612]
Decompiled files should have a comment header on top like Metadata As Source, containing the full path to the assembly being decompiled.

This feature of Metadata As Source is incredibly useful and without it I really don't know how to determine which assembly the symbol is defined in.

**Comment by CyrusNajmabadi** [comment]
I believe this was fixed with https://github.com/dotnet/roslyn/pull/25420
