### ISSUE TITLE
Navigation should work on GetPinnableReference method

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#25610]
- FAR on `GetPinnableReference` should find the `fixed` statements where it comes into play
- GoToDefinition on a fixed statement (or maybe the `=` in the fixed statement) should go to `GetPinnableReference`
- Maybe QuickInfo on a fixed statement should show the `GetPinnableReference`

Relates to language feature https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/pattern-based-fixed.md
Tagging @VSadov FYI

**Comment by CyrusNajmabadi** [comment]
Is there an API that exposes if GetPinnableReference was called, and which particular GetPinnableReference method was called @jcouv ?

**Comment by CyrusNajmabadi** [comment]
Closing out as we've heard nothing from users on this.
