### ISSUE TITLE
[Completion] Autopopup after +=

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#25617]
In VS4Mac we used to auto popup code completion after

"evt += |"

This way we could add anonymous methods or create new ones. Roslyn unfortunately doesn't auto popup in that context. Would be nice if that could be added.

**Comment by CyrusNajmabadi** [comment]
We do suggest

![image](https://user-images.githubusercontent.com/4564579/217938649-1d6f1d5f-40f4-442a-bd79-2617b00d574e.png)
