### ISSUE TITLE
QuickInfo should display the assembly and namespace where the symbol is defined

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#25611]
To make QuickInfo more useful, consider adding these two items to the display:
 1. assembly or project where the symbol is defined
 2. namespace

Of course this is probably not needed for locals, parameters and direct members of the current class.
For partial class maybe mention the file name if the symbol is in another part of a partial class.

Otherwise to find the assembly I used to F12 or Alt+F12 to go to Metadata as Source, which very helpfully displays the assembly, but now with decompilation we lost that.

**Comment by KirillOsenkov** [comment]
Filed #25612

**Comment by KirillOsenkov** [comment]
cc @gundermanc @DustinCampbell

**Comment by gundermanc** [comment]
Using the new API, no change is required from the IDE. Just have to add an item to the vertical ContainerElement Roslyn returns us.

**Comment by DustinCampbell** [comment]
cc @dotnet/roslyn-ide.

**Comment by jinujoseph** [comment]
cc @JieCarolHu

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this topic.
