### ISSUE TITLE
[Highlighting] TODO comments

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#25619]
In VS4MAC we had a list of tags for comments like todo/fixme and so on these got added to the task list - AFAIK VS.NET shares this feature.

VS4Mac added colorization for these tags inside comments - is that something that's planed for VS.NET as well ?

**Comment by CyrusNajmabadi** [comment]
Mike, can you include pictures to show what this experience is like?

**Comment by Therzok** [comment]
This is an outdated page, but something like this:
https://mhut.ch/journal/2011/03/monodevelop_tips_task_comments

Afaik, we used to have a purple-ish text color in the dark theme.

So, together with showing them in the task list, they are highlighted in source code and shown in the task strip on the scroll bar.

When we switching to the roslyn classification highlighting, we lost TODO comment highlighting.

**Comment by Therzok** [comment]
Okay, found a more recent image: https://docs.microsoft.com/en-us/visualstudio/mac/task-comments

**Comment by Therzok** [comment]
@mkrueger I was looking over the old C# syntax highlighting we had:
We lost as-keyword highlighting of nint/nuint/nfloat for mobile profile
We lost regex string highlighting 
We lost string format highlighting
https://github.com/mono/monodevelop/blob/9258f3a8d441b61e76c57642511c70f4ec19b093/main/src/addins/CSharpBinding/MonoDevelop.CSharp.Highlighting/CSharpSyntaxMode.cs#L248

**Comment by Pilchie** [comment]
This seems like something that would be easy to write your own tagger for.

**Comment by CyrusNajmabadi** [comment]
> We lost regex string highlighting

Note: there's a PR for that over here: https://github.com/dotnet/roslyn/pull/25517

Looks like this:

![image](https://user-images.githubusercontent.com/4564579/37729010-0a5839f4-2cf9-11e8-9e60-842a4c094014.png)

**Comment by CyrusNajmabadi** [comment]
>This seems like something that would be easy to write your own tagger for.

**Comment by mkrueger** [comment]
Would help - note that we don't use taggers we use the Microsoft.CodeAnalysis.Classification.Classifier.
Haven't seen any extension mechanism there.

**Comment by Pilchie** [comment]
Classifiers are just taggers that have a tag type of ClassificationTag.

**Comment by mkrueger** [comment]
How to add a classifier to the roslyn API ?

**Comment by mkrueger** [comment]
I can't find any extension mechanism inside the CSharpSyntaxClassificationService the ISyntaxClassifier  seem to be hard coded. Adding a ISyntaxClassifier seems to be the easiest way doing it. 

I can work around on monodevelop level by scanning the comments - I just want to know if there is a cleaner way doing it.

**Comment by mkrueger** [comment]
The CSharpSyntaxClassificationService should just use MEF to collect the DefaultSyntaxClassifiers then they would be extendable.

**Comment by kendrahavens** [comment]
Another customer request for highlighting TODO comments with a blue font. Since we are adding so many color settings in the Visual Studio 2019 previews I think it'd be great to add a customizable setting for TODO in Fonts and Colors.

@sharwell @jinujoseph

**Comment by sharwell** [comment]
Design review conclusion: we are hoping the editor can provide higher-level support for this across multiple languages. Looping in @olegtk for comments.

**Comment by olegtk** [comment]
yes, send it to the editor

**Comment by jinujoseph** [comment]
sent over [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/802912)
