### ISSUE TITLE
I would like a way to find references to a symbol, without cascading being involved.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#25628]
I think @jnm2 has some good ideas on how we could accomplish that.

**Comment by CyrusNajmabadi** [comment]
The essential idea here is that if you ask for no cascading, you should only ever get results back that point back to a single symbol, the same symbol you asked for references for.

**Comment by genlu** [comment]
what's cascading?

**Comment by CyrusNajmabadi** [comment]
Say you have `interface IFoo { void Bar(); } class C : IFoo { public Bar() { } }`

Doing a Find-References on IFoo.Bar will 'cascade' to C.Bar and find references to that member as well.  When doign something like a 'rename', the cascading is important since if you update one, you'd need to update the other to keep the program from breaking.  However, sometimes you are just looking for the direct references to a single symbol.  Removing cascading could speed that up.

**Comment by genlu** [comment]
It does sound like cascading is not needed for "change namespace" feature in #30156

**Comment by CyrusNajmabadi** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/42212
