### ISSUE TITLE
"Paste (Cold) - VisualBasic" perf test is failing in nightly runs

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#2564]
We've been seeing regular failures on the nightly 4-core and 6-core machines for "Paste (Cold) - VisualBasic".
Screenshot shows "An exception has been encountered. This may be caused by an extension.", but we don't have a first chance exception log.

**Comment by Pilchie** [comment]
Moving to 1.1, since at this point, we wouldn't take a fix to the stabilization branch to fix this.

**Comment by rchande** [comment]
@pharring Closing as this appears to have mysteriously fixed itself.
