### ISSUE TITLE
[IDE][Request] GoTo Line Number

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#25668]
When line numbering is enable, we should also a right click menu entry to `GoTo line number`.
So that it is possible to jump straight to a particular line.

**Comment by CyrusNajmabadi** [comment]
@olegtk Can you file with the editor?

**Comment by sharwell** [comment]
Cyrus already mentioned a member of the appropriate team, though as a user who _always_ has editor line numbers enabled I don't see how this would work - there is no context menu for the line number margin.

**Comment by olegtk** [comment]
I'm not sure I understand the suggestion, can you clarify, @AdamSpeight2008 please?

**Comment by AdamSpeight2008** [comment]
@olegtk  When you have line numbering enabled, from with the margin there should a way to go to a 
specific line number. 

In the example below
![gotolinenumber](https://user-images.githubusercontent.com/900107/37783091-7f95b734-2dec-11e8-9008-30ebff728e27.png)
say I want to go to line 12345, I'd currently have to play "hunt the line number" with the scroll bar / wheel. Where as if I some how enter the line I what to go to it would be relatively simpler.

**Comment by svick** [comment]
Are you aware of [Go To Line](https://blogs.msdn.microsoft.com/zainnab/2010/03/08/go-to-a-line-number/) (<kbd>Ctrl</kbd>+<kbd>G</kbd>)?

![](https://user-images.githubusercontent.com/287848/37783494-ec6bc052-2df5-11e8-9f0c-0a0c67ab0e6d.png)

Another option is Go To All (<kbd>Ctrl</kbd>+<kbd>,</kbd>), where you can use the `:` prefix to go to a line.

![](https://user-images.githubusercontent.com/287848/37783596-34790094-2df6-11e8-906b-5395a8bc7bd7.png)

**Comment by AdamSpeight2008** [comment]
I am now. *To me it's now intuitive*

**Comment by AdamSpeight2008** [comment]
@svick  `(Ctrl+G)` brings up the immediate window for me.
