### ISSUE TITLE
open issues from recursive-patterns(6-8)

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#25663]
### These open issues remain from code review of https://github.com/dotnet/roslyn/pull/24059

- In `CheckConsistentDecision`, use some notation like `v != null --> !(v == null)` for more clarity than the English language comment.
- Add a private constructor to prevent construction of `DagStateEquivalence`
- Hint creation size in `            var sectionBuilder = ArrayBuilder<BoundPatternSwitchSection>.GetInstance();`
- Hint creation size in `                var labelBuilder = ArrayBuilder<BoundPatternSwitchLabel>.GetInstance();`
- Suppress subsumption errors on switch expression case if the pattern has an error.
- In `LowerDecision`, we have special handling for decisions on constant-valued input. But such decisions should already have been removed from the decision dag. Assert that this situation cannot occur and remove the special handling code.
- Remove commented code `                            //Debug.Assert(w.WhenTrue != null);`
- Merge two cases in `switch (sortedNodes[0])`
- Add a comment explaining why we don't call `GenerateSwitchDispatch` for the final node in `LowerDecisionDag`
- Comment on `GetDagNodeLabel` seems somewhat redundant.
- In `AwaitExpressionSpiller.cs`, move `VisitSwitchDispatch` to right after `EnterStatement` so it is in the same place where `VisitSwitchStatement` used to be to make deltas more clear in the end.

### These open issues remain from code review of https://github.com/dotnet/roslyn/pull/25544

- In `ComputeLabelSet` delete the commented out code.
- Remove `params` overload `public BoundStatement Switch(BoundExpression ex, params SyntheticSwitchSection[] sections)` and force caller to properly construct an immutable array.

**Comment by gafter** [comment]
The PR https://github.com/dotnet/roslyn/pull/25767 contains fixes for the remaining issues from this list. In two cases the fix precedes the PR.

**Comment by alrz** [comment]
>use some notation .. than *the English language comment*

I think there is a word for that: prose.

**Comment by gafter** [comment]
Addressed in https://github.com/dotnet/roslyn/issues/25767
