### ISSUE TITLE
Await in catch causing Assert in Async rewriter

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#2567]
The Assert fired at line 140 of AsyncExceptionHandlerRewriter, which is:
Debug.Assert(tryStatementSyntax.IsKind(SyntaxKind.TryStatement));

There is an assumption here that the syntax node associated with the bound try node is a TryStatementSytnax, but in this case it is a UsingSyntax.

This simpler repro will cause it to fail:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

class Program : IDisposable
{
    static void Main(string[] args)
    {
    }

    static async Task<bool> DoSomethingWithRetryAsync()
    {
        int count = 0;

        retry:

        try
        {
            using (new Program())
            { 
                return await DoSomethingAsync().ConfigureAwait(false);
            }
        }
        catch (System.OperationCanceledException)
        {
            throw;
        }
        catch (System.IO.IOException e)
        {
            if (++count < 5)
            {
                await Task.Delay(200).ConfigureAwait(false);
                goto retry;
            }

            return false;
        }
        catch (System.IO.InvalidDataException)
        {
            return false;
        }
    }

    static Task<bool> DoSomethingAsync()
    {
        return Task.FromResult(true);
    }

    public void Dispose()
    {
        throw new NotImplementedException();
    }
}
```

**Comment by tmat** [comment]
The assertion is correct and required by EnC. The code that creates the bound node is wrong.

**Comment by tmat** [comment]
I guess the BoundTryStatement that this fails for is the try-finally created for Using Statement.
If that's the case it is safe to modify the assertion to allow UsingStatement.

Debug.Assert(tryStatementSyntax.IsKind(SyntaxKind.TryStatement) || tryStatementSyntax.IsKind(SyntaxKind.UsingStatement));

**Comment by mattwar** [comment]
@tmat, yes that's what is happening.

**Comment by tmat** [comment]
OK :)

**Comment by gafter** [comment]
@mattwar Please verify that this is fixed.
