### ISSUE TITLE
Wrong default value of a nullable parameter with Microsoft.Net.Compilers 2.4.0

### ISSUE THREAD

**Issue by danko-d** [dotnet/roslyn#25677]
**Version Used**: 
C# 7.1 with NuGet package Microsoft.Net.Compilers 2.4.0

**Steps to Reproduce**:

1. In VS2017, create a new console application and change C# version to 7.1
2. Enter the following:

		using System.Diagnostics;

		namespace Test
		{
			class Program
			{
				static void Foo(int? x = default)
				{
					Debug.Assert(x == null);
				}

				static void Main()
				{
					Foo();
				}
			}
		}

3. Run the program. It works because `default` of `int?` is `null`.
4. Add NuGet package Microsoft.Net.Compilers version 2.4.0 (not the latest). 
5. Run the program again. The assertion fails because `x` is `0` (`default` of `int`).

**Expected Behavior**:

The default value of `int?` parameter should be `null`.

**Actual Behavior**:

The default value of `int?` parameter is `0`.

This appears to be fixed in  Microsoft.Net.Compilers 2.6.0 and later, but I have to use 2.4.0 since it is the last version that does not require MS Build v15.0 which is not installed on our build server.

**Comment by ufcpp** [comment]
It's a known bug: https://github.com/dotnet/roslyn/pull/22527

**Comment by danko-d** [comment]
Can it be fixed in Microsoft.Net.Compilers 2.4.x, since we cannot update to C# 7.2 / Microsoft.Net.Compilers 2.6.0 or later?

**Comment by jcouv** [comment]
@danko-d Sorry about this bug. Unfortunately, the only way to get the fix is to update the compiler.
That said, this does not mean that you would update to C# 7.2. You can set the language version in your project(s) to `7.1` to remain on that language version.
I'll go ahead and close the issue since it was fixed already. Thanks

**Comment by jcouv** [comment]
Also worth mentioning, the workaround is to spell out the type in `default(T)`.
