### ISSUE TITLE
Guid is not right

### ISSUE THREAD

**Issue by RipPer56** [dotnet/roslyn#25678]
**Version Used**: any version

I want to know why when i open a solution and get the real guid (the one in .sln or .csproj file). But it just create a new Guid() for each project while opening the solution.

**Comment by jcouv** [comment]
Can you clarify what you mean by "get the real guid"? What API are you using?

**Comment by RipPer56** [comment]
the GUID that identify the project, the only in the tag <ProjectGuid>XXXX...</ProjectGuid>

**Comment by jcouv** [comment]
I'm sorry, I still didn't understand the issue and wouldn't know how to reproduce it.

**Comment by davkean** [comment]
@RipPer56 Need a little more information on what you are referring to and APIs if any you are using. If you can provide more information, feel free to open an issue over on http://github.com/dotnet/project-system.
