### ISSUE TITLE
FatalExecutionEngineError with Microsoft.EntityFrameworkCore 2.0.2 referenced in .NET 4.6.1

### ISSUE THREAD

**Issue by divega** [dotnet/roslyn#25687]
_From @RussKeldorph on March 22, 2018 22:8_

_From @dalibor983 on March 22, 2018 9:42_

When I run IISExpress everything working great  until I rebuild project and IISExpress tries to reload new dlls in memory. Then I get this exception when DbContext is initialized that crashes IISExpress:
```
Managed Debugging Assistant 'FatalExecutionEngineError' 
  Message=Managed Debugging Assistant 'FatalExecutionEngineError' : 'The runtime has encountered a fatal error. The address of the error was at 0x73b03293, on thread 0x6b90. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.'
```
After starting IISExpress again everything working again.

I must restart IISExpress on every new build :(

_Copied from original issue: dotnet/coreclr#17121_

_Copied from original issue: aspnet/EntityFrameworkCore#11391_

**Comment by divega** [comment]
_From @dalibor983 on March 23, 2018 9:25_

I think that maybe Roslyn compiler causes the problems with projects that combines .NET framework and netstandard. I notice that when I kill "VBCSCompiler.exe" process my IISExpress does not crash after project rebuild.

I em not sure because I don't know what this "VBCSCompiler.exe" process does in background. Does it build project silently in the background (independently of visual studio) or what?

**Comment by jaredpar** [comment]
Moving discussion back to the EF issue. There isn't much evidence this is a compiler issue.
