### ISSUE TITLE
Rename crash when overriding method illegally has private accessibility and the overridden method is in another project

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#25682]
Developer Community: https://developercommunity.visualstudio.com/content/problem/124873/refactor-rename-a-method-crashes-vs-2017-everytime.html

1. Create a C# Class Library `ClassLibrary1` with code:

```C#
namespace ClassLibrary1
{
    public class Class1
    {
        public virtual void M() { }
    }
}
```

2. Create a C# Class Library `ClassLibrary2` which references `ClassLibrary1` and has code:

```C#
namespace ClassLibrary2
{
    public class Class2 : ClassLibrary1.Class1
    {
        public override void M() { }
    }
}
```

3. At this point everything will be okay. You can rename M without issue.

4. Remove the `public` accessibility from the override in `ClassLibrary2` (introducing an error), and rename `M` in Class2

**Expected:** Rename should probably still work despite the accessibility error in the code.
**Actual:** VS Crash

```
Message: System.InvalidOperationException: Unexpected false
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message)
   at Microsoft.CodeAnalysis.Rename.RenameUtilities.GetDocumentsAffectedByRename(ISymbol symbol, Solution solution, IEnumerable`1 renameLocations)
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<FindDocumentsAndPossibleNameConflicts>d__24.MoveNext()
```

**Comment by JieCarolHu** [comment]
@dpoeschl I cannot repro this issue, could you please try again on the latest build? Thanks.

**Comment by JieCarolHu** [comment]
For me the method gets renamed correctly:
`namespace ClassLibrary1
{
    public class Class1
    {
        public virtual void A() { }
    }
}

namespace ClassLibrary2
{
    public class Class1 : ClassLibrary1.Class1
    {
        override void A() { }
    }
}
`

**Comment by dpoeschl** [comment]
We were able to repro the crash. It required both the use of Inline Rename (not Rename Tracking) and invoking it from Class2 (not Class1). @JieCarolHu has clarified both of these in the original description.
