### ISSUE TITLE
DirectiveTriviaSyntax.GetRelatedDirectives assumes there can only be one #elif

### ISSUE THREAD

**Issue by dpaoliello** [dotnet/roslyn#2569]
DirectiveTriviaSyntax.GetRelatedDirectives() appears to only be picking up one #elif directives if the code contains multiple #elif directives.

Repro Code:
```c#
const string code = @"
#if A
#elif B
#elif C
#endif
";

SyntaxTree tree = SyntaxFactory.ParseSyntaxTree(code);
DirectiveTriviaSyntax ifDirective = (DirectiveTriviaSyntax)tree.GetRoot().GetLeadingTrivia()[1].GetStructure();
foreach (var trivia in ifDirective.GetRelatedDirectives())
{
    Console.Write(trivia.ToFullString());
}
```

Expected Output:
```
#if A
#elif B
#elif C
#endif
```

Actual Output:
```
#if A
#elif B
#endif
```

The root cause of the error appears to be in GetNextRelatedDirective() and GetPreviousRelatedDirective() which assume that a #elif directive cannot be related to another #elif directive:
```c#
                case SyntaxKind.ElifDirectiveTrivia:
                    while (d != null)
                    {
                        switch (d.Kind())
                        {
                            case SyntaxKind.ElseDirectiveTrivia:
                            case SyntaxKind.EndIfDirectiveTrivia:
                                return d;
                        }

                        d = d.GetNextPossiblyRelatedDirective();
                    }

                    break;
```

I am happy to submit a pull request if this is approved.

**Comment by mattwar** [comment]
Yes, please submit a PR.

**Comment by dpaoliello** [comment]
Ping?
I've submitted a pull request with the fix - can someone please have a look at it?

**Comment by jaredpar** [comment]
:+1: 

CC @gafter, @agocke, @VSadov, @mattwar

**Comment by gafter** [comment]
I suspect you intended to :+1: the PR?

**Comment by jaredpar** [comment]
@gafter ha, yeah :(

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/2688
