### ISSUE TITLE
Produce much better code for CInt(Fix(number))

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#25692]
We believe the code produced for `CInt(Fix(number))` can be significantly improved by emitting an IL instruction for simply truncating the floating-point number to its integral part.
1. Check this assumption, and
2. Change the Roslyn VB compiler to produce the more efficient sequence

This is a compiler-only change that requires no change to the VB language specification, as the emitted code would be functionally equivalent.

See also https://github.com/dotnet/vblang/issues/86 and https://github.com/dotnet/vblang/issues/82

/cc @AnthonyDGreen

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 2)

**Comment by gafter** [comment]
We assert that `CInt(Fix(x))` can be rewritten for code-gen purposes to `(int)x` where `(int)x` is the C#-style integral truncation operator (not directly expressible in VB). Here is the "proof":

1. Note that the original expression is interpreted to mean `(int)Math.Round(Fix(x))`

2. Note that `Math.Round` of a whole number is that same whole number. Since `Fix` returns a whole number, the `Round` operation is a no-op. Reducing leaves `(int)Fix(x)`

3. Note that `Fix(x)` truncates the fractional part, leaving a floating-point whole number. But `(int)x` also truncates the fractional part before converting to an integer. So the `Fix` operation is redundant. Reducing leaves `(int)x`

That is the code we want to generate.

Every step of this proof outline is correct in the face of overflow: if the original expression overflows, the reduced expression does too, and vice versa.

**Comment by AnthonyDGreen** [comment]
Awesome, @gafter !

**Comment by DualBrain** [comment]
I'm so looking forward to getting this in my hands. Thank you... thank you... thank you. :-D
