### ISSUE TITLE
Issues around analyzer exception diagnostics getting suppressed or not reported

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#257]
Ported from TFS WorkItem: <b>1114327</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><B><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; mso-fareast-font-family: "Times New Roman"'>From:</SPAN></B><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; mso-fareast-font-family: "Times New Roman"'> Manish Vasani <BR><B>Sent:</B> Friday, January 23, 2015 3:34 PM<BR><B>To:</B> HeeJae Chang; John Hamby; Srivatsn Narayanan<BR><B>Subject:</B> RE: Code Review: Fix couple of issues in IDE diagnostic service for project diagnostics (mavasani)</SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><FONT size=3 face="Times New Roman">&nbsp;</FONT></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>Based on my exercise, I too feel that carrying these diagnostics along with regular diagnostics will only lead to more bugs. Probably we should have an event to report these diagnostics and a handler in IDE and command line compiler that report/clear out these diagnostics. I’ll open a bug to track this work as well. </SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>I went down this path as I tried to write a test (for the original issue on this thread) with an analyzer that throws when called twice on same symbol/node for a compilation, and the exception or diagnostic never showed up </SPAN><SPAN style="FONT-SIZE: 11pt; FONT-FAMILY: Wingdings; COLOR: #1f497d">J</SPAN><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'></SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>&nbsp;</SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt; mso-outline-level: 1"><B><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif'>From:</SPAN></B><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif'> HeeJae Chang <BR><B>Sent:</B> Friday, January 23, 2015 3:25 PM<BR><B>To:</B> Manish Vasani; John Hamby; Srivatsn Narayanan<BR><B>Subject:</B> RE: Code Review: Fix couple of issues in IDE diagnostic service for project diagnostics (mavasani)</SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><FONT size=3 face="Times New Roman">&nbsp;</FONT></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>Yesterday, I went through some of this code for Watson and wondered by exception diagnostic is handled same way as regular diagnostics from analyzer. Since in this way, unless analyzer consistently throws, the diagnostic will come and go as code is changed.</SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>&nbsp;</SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>Shouldn’t those diagnostic reported differently?</SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>&nbsp;</SPAN></P>
<P class=MsoListParagraph style="MARGIN: 0in 0in 0pt 0.5in; TEXT-INDENT: -0.25in; mso-list: l1 level1 lfo1"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-bidi-font-family: Calibri; mso-fareast-font-family: Calibri'><SPAN style="mso-list: Ignore">-<SPAN style='FONT: 7pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>heejae</SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>&nbsp;</SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt; mso-outline-level: 1"><B><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif'>From:</SPAN></B><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif'> Manish Vasani <BR><B>Sent:</B> Friday, January 23, 2015 3:12 PM<BR><B>To:</B> John Hamby; HeeJae Chang; Srivatsn Narayanan<BR><B>Subject:</B> RE: Code Review: Fix couple of issues in IDE diagnostic service for project diagnostics (mavasani)</SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><FONT size=3 face="Times New Roman">&nbsp;</FONT></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>So investigating this further has exposed a bunch of other issues:</SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>&nbsp;</SPAN></P>
<P class=MsoListParagraph style="MARGIN: 0in 0in 0pt 0.5in; TEXT-INDENT: -0.25in; mso-list: l2 level1 lfo2"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-bidi-font-family: Calibri; mso-fareast-font-family: Calibri'><SPAN style="mso-list: Ignore">1)<SPAN style='FONT: 7pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>Swallowing analyzer exception diagnostics: There seem to a bunch of places where the IDE diagnostic service is swallowing diagnostics from analyzer exception (in fact any diagnostic reported without a location). The most glaring one is if we are running document analysis, the action might throw and we generate a no-location diagnostic. The DiagnosticAnalyzerDriver returns this diagnostic, but the DiagnosticIncrementalAnalyzer filters out all diagnostics without a span, hence even the exception diagnostic and it never shows up in error list.</SPAN></P>
<P class=MsoListParagraph style="MARGIN: 0in 0in 0pt 0.5in"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>Even ReanalyzeAllDocuments which does force analysis of all documents prior to running compilation end actions, throws away all diagnostics, including analyzer exception diagnostics.</SPAN></P>
<P class=MsoListParagraph style="MARGIN: 0in 0in 0pt 0.5in"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>I tried couple of approaches to fix this:</SPAN></P>
<P class=MsoListParagraph style="MARGIN: 0in 0in 0pt 0.75in; TEXT-INDENT: -0.25in; mso-list: l0 level1 lfo3"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-bidi-font-family: Calibri; mso-fareast-font-family: Calibri'><SPAN style="mso-list: Ignore">(a)<SPAN style='FONT: 7pt "Times New Roman"'>&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>By adding a static conditional weak table from compilation to project diagnostics on DiagnosticAnalyzerDriver, such that any no-location diagnostics generated during document analysis are stored away on the map, and these get reported when GetProjectDiagnostics is invoked. This works fine, except for the case where document analysis for some document executes after project diagnostics have been fetched. This is very much possible if our solution crawler low pri queue picks up a project before all of its documents have been processed by high/medium pri processor.</SPAN></P>
<P class=MsoListParagraph style="MARGIN: 0in 0in 0pt 0.75in; TEXT-INDENT: -0.25in; mso-list: l0 level1 lfo3"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-bidi-font-family: Calibri; mso-fareast-font-family: Calibri'><SPAN style="mso-list: Ignore">(b)<SPAN style='FONT: 7pt "Times New Roman"'>&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>Fix DiagnosticAnalyzerService handling of methods that fetch or compute document diagnostics to not filter out no-location diagnostics during document analysis itself. These seems weird from implementation perspective as we will pass around diagnostics without a span, when specifically asked for diagnostics within a document span. I am not sure what all will break with this approach, but I am reluctant to go this path.</SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt 0.5in"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>I am now confused what is the best way to approach this problem.</SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt 0.5in"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>&nbsp;</SPAN></P>
<P class=MsoListParagraph style="MARGIN: 0in 0in 0pt 0.5in; TEXT-INDENT: -0.25in; mso-list: l2 level1 lfo2"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-bidi-font-family: Calibri; mso-fareast-font-family: Calibri'><SPAN style="mso-list: Ignore">2)<SPAN style='FONT: 7pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'>We suppress duplicate AnalyzerException diagnostics per compilation over <A href="http://index/Microsoft.CodeAnalysis/R/f9a2363f6e6d5963.html"><U><FONT color=#0000ff>here</FONT></U></A>. See the first if statement. However, this seems wrong as this method might be invoked twice on the same diagnostic, and we will report it as not suppressed on first invocation, but suppressed on subsequent invocation (blame me, I wrote that!). I am going to remove all the code related to faultyAnalyzerMessages there and open a bug to ensure it gets fixed the right way.</SPAN></P>
<P class=MsoListParagraph style="MARGIN: 0in 0in 0pt 0.5in"><SPAN style='FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d'></SPAN>&nbsp;</P>

**Comment by mavasani** [comment]
This should now be fixed with #673. However, we still don't report diagnostics from SupportedDiagnostics invoked within WorkspaceAnalyzerManager. We have capability of reporting workspace specific diagnostics now in Features layer. I'll address this in a subsequent change.

**Comment by mavasani** [comment]
SupportedDiagnostics invocation has now been fixed in the IDE to catch and report exceptions.
The only pending issue in this area is now captured by #887, I am closing this issue.
