### ISSUE TITLE
"Generate Equals" refactorings produce faulty code when using ref structs

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#25708]
**Version Used**: VS 15.7 Preview 2 (2.8.0.62716)

**Steps to Reproduce**:

1. Copy the source below into a C# source file.
2. Invoke the Quick Fix menu at the marked location and select either "Generate Equals" or "Generate Equals and GetHashCode".
3. Make sure the field "r" is selected in the list, and "Implement IEquatable<ReproA>" is checked. Press "OK".

```c#
ref struct ReproA
{
	ReproB r;

	$$
}

ref struct ReproB
{
}
```

**Expected Behavior**: I'm not sure. (Is it even possible to determine equality/hash code for ref structs with the "traditional" approach?)
VS could a) not suggest these refactorings inside ref structs, and b) not suggest ref struct members in the member selection list.

**Actual Behavior**: The class looks something like this and cannot compile:

```c#
ref struct ReproA : IEquatable<ReproA> // Errors CS0306, CS8343
{
	ReproB r; // Warning CS0169

	public override bool Equals(object obj)
	{
		return obj is ReproA && Equals((ReproA)obj); // Warning CS0184, error CS0030
	}

	public bool Equals(ReproA other)
	{
		return EqualityComparer<ReproB>.Default.Equals(r, other.r); // Error CS0306
	}

	public override int GetHashCode()
	{
		return -947233955 + EqualityComparer<ReproB>.Default.GetHashCode(r); // Error CS0306
	}
}
```

**Comment by CyrusNajmabadi** [comment]
This is one of those interesting cases.  As a refactoring, we usually err toward allowing this sort of thing.  To allow a person to still generate the stuff even if they'll go and need to fix up things later.

However... i really can't figure out what it would mean for a ref-struct to have equality/hashing semantics.  How would you ever put a ref struct into anything?  They can't be used as type parameters.  And you can't make objects out of them.  So even basic object methods seem non-sensical for them.  So i think it would be fine to disable this feature for 'ref structs'.  it would also be interesting to know why this was missed.

@dpoeschl Is "generate equals/gethashcode" not on the list of things to test with new language features?

**Comment by sharwell** [comment]
Design review outcome: We should make two changes to the refactoring to account for `ref struct`:

1. Do not add `IEquatable<T>` as an implemented interface
2. Override `object.Equals(object)` to simply return `false`

The remaining generated methods appear to work without changes, even if their useful scenarios are more limited than other structs. The most helpful features of this refactoring are the generated `Equals(T)` method and the generated equality/inequality operators.

**Comment by jhinder** [comment]
Got it.

Follow-up question: what about nested ref structs (see original example)? When should those show up in the members list? They'd have to implement `Equals(T)` and override `GetHashCode` in order for us to include them in the generated code in any meaningful way (`Equals(object)` and `ValueType.GetHashCode()` don't work, and neither do `EqualityComparer<T>.Default`'s methods).

**Comment by CyrusNajmabadi** [comment]
> They'd have to implement Equals(T) and override GetHashCode in order for us to include them in the generated code in any meaningful way

Sounds like it would be good to just check for that.  If they have that, then include them, otherwise don't.

**Comment by sharwell** [comment]
Or we could generate `field.Equals(other.field)`, which will suggest the user implement equality for the nested ref struct.
