### ISSUE TITLE
[Regression] "Refresh CodeLens Team Indicators" always visible on editor context menu instead of just over CodeLens

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#25715]
**Version Used**: 
Version 15.7.0 Preview 3.0 [27523.0.d15.7]

**Steps to Reproduce**:

1. Create a new Console App (.NET Framework)
2. In status bar, choose Add to Source Control -> Git
3. Right-click on Editor within a method body

**Expected Behavior**:

No **Refresh CodeLens Team Indicators**

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/1103906/37884234-aa571510-30fa-11e8-883f-cc0e755a8050.png)

Tried 15.6.3 and it does not repro, so this appears to be a regression.

**Comment by heejaechang** [comment]
@jinujoseph is it ours? @lineralpha do you know which team this belong to?

**Comment by jinujoseph** [comment]
Routed to [editor ](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_queries/edit/642812/?triage=true)team
