### ISSUE TITLE
No reference when awaiting custom GetAwaiter method

### ISSUE THREAD

**Issue by HaloFour** [dotnet/roslyn#25714]
**Version Used**:   v15.6.4

**Steps to Reproduce**:

1. Create a class with a custom `GetAwaiter` that returns an awaitable.
2. Instantiate that class and `await` on it from a separate `async` method.

**Expected Behavior**:

That the `GetAwaiter` method shows references from being used in an `await` expression.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/10102290/37882519-f914f430-3071-11e8-950b-4181512caddd.png)

**Comment by HaloFour** [comment]
Whether or not the method is shown as having a reference is a bit inconsistent between features.  For example, `GetEnumerator` and `Deconstruct` do reflect the reference if used with `foreach` or deconstruction respectively.  But LINQ-compatible methods don't appear to reflect the reference if used from LINQ query syntax.

**Comment by jcouv** [comment]
Fix will ship in 15.8.Preview5.
