### ISSUE TITLE
[Feature request] Code Fixer for adding /unsafe option

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#25722]
Just like UpgradeProject, we could trigger a fixer when the following diagnostic is produced by the compiler and fix the project for you.
![image](https://user-images.githubusercontent.com/12466233/37922061-6a4a907e-30e0-11e8-97f8-b55b37c7f540.png)

**Comment by kindermannhubert** [comment]
Nice. But it should give you chance to choose if you want to enable unsafe only for current build configuration or for all build configurations (even though I don't think I've ever needed the first variant).

**Comment by jcouv** [comment]
@kindermannhubert I can't think of a scenario where `/unsafe` would be set in only some configurations, so I assumed the fixer should just do it for all. 
Do you have any examples where per-configuration would make sense?

**Comment by kindermannhubert** [comment]
@jcouv I don't, I was more likely afraid it would update only current configuration. I'm completely ok with "update all configurations" approach.

**Comment by Neme12** [comment]
Do we want fix all too?

**Comment by jcouv** [comment]
@Neme12 fixed this for dev16.1 preview1. Thanks!
