### ISSUE TITLE
Workspace.TryApplyChanges(solution) add document invalid folders.

### ISSUE THREAD

**Issue by malylemire1** [dotnet/roslyn#25728]
**Version Used**: Roslyn version is 1.2.2 on vs2017

**Steps to Reproduce**: 
1. Get VisualStudioWorkspace in a Visual Studio Package :

```
IComponentModel componentModel = (IComponentModel)Package.GetGlobalService(typeof(SComponentModel));
VisualStudioWorkspace workspace = componentModel.GetService<VisualStudioWorkspace>();
```
1. Add a document in a project after opening the solution (Before anything else): 

```
Solution solution = workspace.CurrentSolution;

Project project = solution.Projects.FirstOrDefault();

string document = @"
                    using System;
                    namespace Temp
                    {
                        public static class Test
                        {
                        }
                    }
                    ";

project = project.AddDocument("Test.cs", SyntaxFactory.ParseCompilationUnit(document), new List<string> { "ExistingFolder1", "ExistingFolder2","ExistingFolder3" }).Project;

solution = project.Solution;

workspace.TryApplyChanges(solution);
```

**Expected Behavior**:

Changes to solution should be applied.

**Actual Behavior**:

`workspace.TryApplyChanges(solution);`
Return true.

Changes to solution are applied.

workspace.CurrentSolution has invalid folders for added document. Folders count is 0. If a file is manually deleted or added to the project prior to AddDocument, folders are properly updated. Seems like there is some event that is not thrown by VS prior to a manual document add or delete.

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard about this from anyone else.
