### ISSUE TITLE
Interpolated strings not correctly converted to FormattableString when extension method is called

### ISSUE THREAD

**Issue by Timwi** [dotnet/roslyn#25720]
**Version Used**: C# 7.0, .NET 4.6.1

**Code to Reproduce**:

    static class StringExtensions
    {
        public static void DoSomething(this FormattableString str)
        {
            Console.WriteLine(str.Format);
        }
    }

    static class Program
    {
        static void Main(string[] args)
        {
            $"".DoSomething();
        }
    }

**Expected Behavior**:

Interpolated string is converted to FormattableString and extension method is called.

**Actual Behavior**:

Error	CS1929	'string' does not contain a definition for 'DoSomething' and the best extension method overload 'StringExtensions.DoSomething(FormattableString)' requires a receiver of type 'FormattableString'

**Comment by Joe4evr** [comment]
Curious: Does this also reproduce if you actually interpolate something in the string? It could just be that the compiler is optimizing `$""` to a constant string literal, at which point it could be too late to convert the expression to a `FormattableString`.

**Comment by Neme12** [comment]
This seems correct to me.  From the spec:

> An extension method `Ci.Mj` is ***eligible*** if:
>
>*  `Ci` is a non-generic, non-nested class
>*  The name of `Mj` is *identifier*
>*  `Mj` is accessible and applicable when applied to the arguments as a static method as shown above
>*  An implicit identity, reference or boxing conversion exists from *expr* to the type of the first parameter of `Mj`.

**Comment by gafter** [comment]
Yes, as @Neme12 points out, extension methods never use target-type conversions such as this one.

**Comment by Jehoel** [comment]
So what should we do if we *want* to be able to have extension-methods only for `interpolated_string_expression` "values"?

An ergonomics / quality-of-life problem exists in that `interpolated_string_expression` are formatted using `CultureInfo.CurrentCulture` by default - to force `InvariantCulture` we have to use the excessively verbose static-method call `FormattableString.Invariant( $"foo {bar} baz" );`

Another use-case for allowing extension-methods on `interpolated_string_expression` is to make it easier to use domain-specific formatting, such as for HTML-encoding and URL-encoding - I'd love it if I could do this:

```
static String HtmlEncode( this FormattableString fs )
{
    Object?[] formatArgs = fs.GetArguments();
    for( ... ) formatArgs[i] = WebUtility.HtmlEncode( formatArgs[i]?.ToString() );
    return String.Format( CultureInfo.InvariantCulture, fs.Format, arg: formatArgs ):
}

static String UrlEncode( this FormattableString fs )
{
    Object?[] formatArgs = fs.GetArguments();
    for( ... ) formatArgs[i] = Uri.EscapeDataString( formatArgs[i]?.ToString() );
    return String.Format( CultureInfo.InvariantCulture, fs.Format, arg: formatArgs ):
}
```

```
String url = $"a.aspx?foo={bar}".UrlEncode();
String html = $"<div><a href=\"{ur}\"{userProvidedValue}</div>".HtmlEncode();
```

**Comment by lakeman** [comment]
Converting from `interpolated_string_expression` to any type could consider implicit conversions via `FormattableString` as would occur for any other expression.
