### ISSUE TITLE
No code converter provided

### ISSUE THREAD

**Issue by twenzel** [dotnet/roslyn#2574]
At the moment, there is no converter provided to convert VB.Net code (projects) to CSharp and vice versa.

Please provide such a tool.

**Comment by Pilchie** [comment]
Tag - @AnthonyDGreen

**Comment by CyrusNajmabadi** [comment]
This is out of scope for the goals of the Roslyn project.

**Comment by sharwell** [comment]
Reopening to bring to design review with a proposed resolution of **Not Applicable**.

**Comment by CyrusNajmabadi** [comment]
Design review conclusion was that this is out of scope for Roslyn.
