### ISSUE TITLE
Add a cs file as reference to a CSharpCompilation

### ISSUE THREAD

**Issue by Foroughi** [dotnet/roslyn#25745]
I am reading a cs file and use its content SyntaxTree to create its CSharpCompilation instance. here is the cs file : 

```
using System;
namespace appconsole
{
    public class CallerClass
    {      
        public void CallerMethod()
        {
            TestClass obj = new TestClass();
            obj.TestMethod();
        }       
    }
}
```

and here is way i use to get CSharpCompilation of this file : 

```
var compilation = CSharpCompilation.Create("name")
    .AddReferences(
    MetadataReference.CreateFromFile(
    typeof(object).Assembly.Location))
    .AddSyntaxTrees(this.Tree);    
var semantic = compilation.GetSemanticModel(this.Tree);
```

As you can see there is an object of the class TestClass. if I use the following code to get the ISymbole of `obj` object it returns `Error TestClass` which the ContaningNamespace property is null.

`semantic.GetTypeInfo({obj node}).Type`

So I need to add my TestClass file to this CSharpCompilation somehow. is it possible to do this?so when I get `semantic.GetTypeInfo({obj node}).Type.ContaningNamespace` it should return the namespace of the file containing `TestClass` class

FYI here is my TestClass file : 

```
using System;
namespace appconsole
{
    public class TestClass
    {        
        public void TestMethod()
        {            
        }        
    }
}
```

so in this case semantic.GetTypeInfo({obj node}).Type.ContaningNamespace should returns `appconsole`. Obviusly this behavoir is correct because `semantic` doesnt know anything about TestClass. thats the reason i want to add that file as a reference to my CSharpCompilation

**Comment by jcouv** [comment]
You need to pass a second syntax tree (the one with `TestClass` definition) into the compilation.
You can do that by passing an enumerable of syntax trees when you create the compilation, or in your call to `AddSyntaxTrees`.

**Comment by Foroughi** [comment]
@jcouv  thanks. that worked.
