### ISSUE TITLE
Unit test failures in BasicCompilerSymbolTest in es-ES test runs

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#25758]
The following BasicCompilerSymbolTest unit tests fail when run under the es-ES locale:

- [ ] MetadataFileReferenceCompilationTests.BC31007ERR_BadModuleFile1

Full details available in [Roslyn.Compilers.VisualBasic.Symbol.UnitTests.dll.zip](https://github.com/dotnet/roslyn/files/1853156/Roslyn.Compilers.VisualBasic.Symbol.UnitTests.dll.zip)

**Comment by jaredpar** [comment]
Fixed
