### ISSUE TITLE
Add key.ToString into ArgumentException message

### ISSUE THREAD

**Issue by Jes28** [dotnet/roslyn#2575]
An element with the same key already exists in the dictionary.

This message says nothing when meet in log adding key to string into will fix this:

 An element with the same key: 56 already exists in the dictionary.
 An element with the same key: Bla already exists in the dictionary.
 An element with the same key: WhateverReturnsFromToString already exists in the dictionary.

**Comment by Pilchie** [comment]
This should be filed on the corefx repo.  Roslyn does not include the code for `ArgumentException`.

(Unless you are thinking about a particular location where we throw?)
