### ISSUE TITLE
Unit test failures in CSharpCommandLineTest in es-ES test runs

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#25759]
The following CSharpCommandLineTest unit tests fail when run under the es-ES locale:

- [ ] Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.CommandLineTests.FileShareDeleteCompatibility_ReadOnlyFiles
- [ ] Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.CommandLineTests.RefOutWithError
- [ ] Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.CommandLineTests.FileShareDeleteCompatibility_ExistingDirectory

Full details available in [Roslyn.Compilers.CSharp.CommandLine.UnitTests.dll.zip](https://github.com/dotnet/roslyn/files/1853173/Roslyn.Compilers.CSharp.CommandLine.UnitTests.dll.zip)

**Comment by jaredpar** [comment]
Fixed
