### ISSUE TITLE
Unit test failures in CSharpCompilerSyntaxTest in es-ES test runs

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#25762]
The following CSharpCompilerSyntaxTest unit tests fail when run under the es-ES locale:

- Microsoft.CodeAnalysis.CSharp.UnitTests.Parsing.ParserRegressionTests.LexerTooManyBadTokens_LongUnicode
- Microsoft.CodeAnalysis.CSharp.UnitTests.Parsing.ParserRegressionTests.LexerTooManyBadTokens

Full details in [Roslyn.Compilers.CSharp.Syntax.UnitTests.dll.zip](https://github.com/dotnet/roslyn/files/1853215/Roslyn.Compilers.CSharp.Syntax.UnitTests.dll.zip)

**Comment by jaredpar** [comment]
Fixed
