### ISSUE TITLE
Unit test failures in VBCSCompilerTests in es-ES test runs

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#25765]
The following VBCSCompilerTests unit tests fail when run under the es-ES locale:

- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.VbcFallbackNoUtf8
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.MissingReferenceErrorCS
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.VbcFallbackUtf8
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8Output_WithRedirecting_Off_Shared
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.MissingFileErrorVB
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.BadKeepAlive4
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.CscFallBackOutputNoUtf8
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.MissingReferenceErrorVB
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.BadKeepAlive2
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.CompileErrorsVB
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8OutputInRspFileVbc
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8Output_WithRedirecting_On_Shared_CS
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8Output_WithRedirecting_Off_Share
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.InvalidMetadataFileErrorCS
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8Output_WithRedirecting_On_Shared_VB
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.BadKeepAlive3
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.BadKeepAlive1
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8OutputInRspFileCsc
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.CompileErrorsCS
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.CscFallBackOutputUtf8
- Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.MissingFileErrorCS

Full details available in [Roslyn.Compilers.CompilerServer.UnitTests.dll.zip](https://github.com/dotnet/roslyn/files/1853264/Roslyn.Compilers.CompilerServer.UnitTests.dll.zip)

**Comment by jaredpar** [comment]
Fixed
