### ISSUE TITLE
Unit test failures in CSharpCompilerSymbolTest in es-ES test runs

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#25761]
The following CSharpCompilerSymbolTest unit tests fail when run under the es-ES locale:

- Microsoft.CodeAnalysis.CSharp.UnitTests.MethodDocumentationCommentTests.GetMalformedDocumentationCommentXml
- Microsoft.CodeAnalysis.CSharp.UnitTests.LoadDirectiveTests.FileWithErrors
- Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests.Dev10_747421
- Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests.InvalidXmlOnPartialMethods
- Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests.IncludeCycle_Simple
- Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests.IncludeCycle_Containment
- Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests.IncludeWithChildren_Failure
- Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests.IllegalXmlCharacter
- Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests.IncludeCycle_Nesting
- Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests.InvalidXml
- Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests.WRN_FailedInclude_NonExistent_Source
- Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests.InvalidXmlOnPartialTypes
- Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests.MultipleDocComments_SplitXml
- Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests.IncludeNone
- Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests.WRN_InvalidInclude_Source
- Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests.XPathAssumesExpandedInclude
- Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationModeTests.XmlSyntaxError_Inline
- Microsoft.CodeAnalysis.CSharp.UnitTests.CompilationAPITests.EmitOptionsDiagnostics

Full details in [Roslyn.Compilers.CSharp.Symbol.UnitTests.dll.zip](https://github.com/dotnet/roslyn/files/1853199/Roslyn.Compilers.CSharp.Symbol.UnitTests.dll.zip)

**Comment by jaredpar** [comment]
Fixed
