### ISSUE TITLE
It is a error in VB when I declare a Constant of type Some Class = Nothing

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#25769]
**Version Used**: 
15.6.4
**Steps to Reproduce**:
```
Imports System
Namespace Test
    Friend MustInherit Partial Class ConstantValue
        Implements IEquatable(Of ConstantValue)
        Public Const NotAvailable As ConstantValue = Nothing
    End Class
End Namespace
**Expected Behavior**:
No errors when setting NotAvailable to Nothing. This works in C# or if I declare NotAvailable ReadOnly
**Actual Behavior**:
BC30424 Constants must be of an intrinsic or enumerated type, not a class, structure, type parameter, or array type.

**Comment by HaloFour** [comment]
VB.NET only permits declaring constants of a [relatively short list of data types](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/constants-enums/constant-and-literal-data-types), either explicitly or inferred.  The language doesn't permit constants of arbitrary classes assigned to `null` even though IL and C# allow it.  You might want to take it up with the [VB Language repo](https://github.com/dotnet/vblang) if you want that behavior to change.
