### ISSUE TITLE
Unit test failures in CSharpCompilerEmitTest in es-ES test runs

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#25760]
The following CSharpCompilerEmitTest unit tests fail when run under the es-ES locale:

-  Microsoft.CodeAnalysis.CSharp.EditAndContinue.UnitTests.EditAndContinueTests.BrokenPortablePdbStream
- Microsoft.CodeAnalysis.CSharp.EditAndContinue.UnitTests.EditAndContinueTests.BrokenOutputStreams
- Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenTupleTests.UnderlyingTypeMemberWithWrongSignature_2
- Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CompilationEmitTests.BrokenPortablePdbStream
- Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CompilationEmitTests.BadPdbStreamWithPortablePdbEmit
- Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CompilationEmitTests.IllegalNameOverride

Full details in [Roslyn.Compilers.CSharp.Emit.UnitTests.dll.zip](https://github.com/dotnet/roslyn/files/1853184/Roslyn.Compilers.CSharp.Emit.UnitTests.dll.zip)

**Comment by jaredpar** [comment]
Fixed
