### ISSUE TITLE
Unit test failures in EditorServicesTest2 in es-ES test runs

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#25763]
The following EditorServicesTest2 unit tests fail when run under the es-ES locale:

- Microsoft.CodeAnalysis.Editor.UnitTests.NavigationBar.VisualBasicNavigationBarTests.TestGenerateEventHandlerWithDuplicate

Full detail can be found in [Roslyn.Services.Editor2.UnitTests.dll.zip](https://github.com/dotnet/roslyn/files/1853232/Roslyn.Services.Editor2.UnitTests.dll.zip)

**Comment by jaredpar** [comment]
This appears to be a real product issue. The test is throwing an `InvalidOperationException` on the Spanish machines with no obvious cause.

**Comment by CyrusNajmabadi** [comment]
cosing out as we haven't seen this yet.
