### ISSUE TITLE
Formatting does not add whitespace between attribute and parameter

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#2577]
In the code below, the resulting string does not contain a space between attribute and parameter. I would expect that a single space is added. Repro for VS2015 RC1.

```C#
        [Test]
        public void Formatter_fails_to_insert_whitespace()
        {
            const string source = @"

                        public class C
                        {
                            void M(int? p) { }
                        }

                        public class SomeAttribute : System.Attribute { }
                    ";

            const string expected = @"public class C
{
    void M([global::SomeAttribute] int? p) { }
}

public class SomeAttribute : System.Attribute { }
";
            var workspace = new AdhocWorkspace()
                .AddProject("test", LanguageNames.CSharp)
                .AddMetadataReferences(new[]{ MetadataReference.CreateFromAssembly(typeof(object).Assembly) })
                .AddDocument("test", source);
            var document = workspace.Project.Documents.First();

            var compilation = workspace.Project.GetCompilationAsync().Result;
            var typeSymbol = compilation.GetTypeByMetadataName("C");
            var parameterSymbol = ((IMethodSymbol)typeSymbol.GetMembers("M").First()).Parameters.First();

            var parameterSyntax = parameterSymbol.DeclaringSyntaxReferences.First().GetSyntax();

            var attribute = compilation.GetTypeByMetadataName("SomeAttribute");

            var editor = DocumentEditor.CreateAsync(document).Result;
            SyntaxNode attributeSyntax =
                editor.Generator.Attribute(editor.Generator.TypeExpression(attribute))
                    .WithAdditionalAnnotations(Formatter.Annotation);
            editor.AddAttribute(parameterSyntax, attributeSyntax);

            var newRoot = editor.GetChangedRoot();
            var newDocument = editor.GetChangedDocument();

            SyntaxNode rootFormatted = Formatter.Format(newRoot, newDocument.Project.Solution.Workspace);
            string result = rootFormatted.ToString();

            Assert.That(result, Is.EqualTo(expected));

            // result now contains (note the missing space between attribute and parameter):
            /*
public class C
{
    void M([global::SomeAttribute]int? p) { }
}

public class SomeAttribute : System.Attribute { }
                */
        }
```

**Comment by basoundr** [comment]
@Pilchie I checked this behavior with VS2013 and it was the same. Should we change this behavior? If so, we dont have any specific option which mentions spacing between the AttributeList and the parameter in a Method Declaration. 

Suggestions:
1. we could take use the option "Spacing between parameters within Method Declaration" to determine the spacing decision here.
2. Introduce new option
3. Force the space
4. Retain the current behavior

I think the first suggestion seems to sync with what the user wants

**Comment by Pilchie** [comment]
As this is the same as VS2013, we can ship 1.0 this way.  One thing to keep in mind when addressing is that if people rely on this, forcing it to obey an option will change people's code unecessarily.

**Comment by Pilchie** [comment]
Actually, pulling back into 1.0 for now - while the formatter shouldn't change existing code here, we should probably have elastic trivia rules to do something with generated code.

**Comment by bkoelman** [comment]
@basoundr basoundr How can this be the same in VS2013? From what I know, this is a new API. or did there exist something in VS2013 to annotate newly-inserted nodes to get them auto-formatted?

The same appears with indexer parameters. For a similar issue, see #2583.

**Comment by bkoelman** [comment]
Can I test this fix using VS2015 RC? I would like to verify that my Analyzer+CodeFixProvider now applies correct formatting.

I've built my analyzer in Debug mode. Then opened RoslynLight.sln, set OpenSourceDebug as startup project, F5 (described at [Building, Testing, and Debugging](https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging)). 

Upon F5, VS warned me about a release build of Workspace assembly. In the first VS instance, I can see the new source code, but my breakpoint does not get hit when I preview the CodeAction fix and I see no different formatting behavior in my analyzer.

If possible, what additional steps are needed to run my Analyzer+FixProvider on a Roslyn version that I built from source?

**Comment by Pilchie** [comment]
@jaredpar said he's going to try to take a look at OpenSourceDebug today and see what's up.

**Comment by jaredpar** [comment]
The issue #1781 is tracking this problem.

**Comment by bkoelman** [comment]
Thanks for the update, I'll track #1781 then.
