### ISSUE TITLE
Roslyn ignores IVSSymbolicNavigationNotify and IVSRefactorNotify for CPS projects

### ISSUE THREAD

**Issue by rynowak** [dotnet/roslyn#25784]
**Version Used**: 15.7-preview1 

**Steps to Reproduce**:

1. Implement `IVSSymbolicNavigationNotify` and `IVSRefactorNotify` for a CPS-based project (like .NET Core) https://github.com/aspnet/Razor/commit/91b3b222d3a3320175d45c432e0c72f994bad80b
2. Open a project with some generated code: https://github.com/rynowak/RazorIdeTesting
3. Try to go to definition on https://github.com/rynowak/RazorIdeTesting/blob/master/DesignTimeBuild/Program.cs#L19
https://github.com/rynowak/roslyn/commit/40a1e6e5c2a737bf21183855904f57e719341c13

**Expected Behavior**:
Roslyn calls the implementation of `IVsSymbolicNavigationNotify` so that I can implement go to definition from C# -> Razor

**Actual Behavior**:
It doesn't 😢 

What's going wrong here is that at this location: https://github.com/rynowak/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/VsRefactorNotifyService.cs#L29

`hierarchy` is the .NET object for `ConfiguredProjectHostObject` and **not** the COM wrapper. This means that the cast is a normal .NET cast, and not a `QueryInterface`.

This means that my service (exported through CPS) https://github.com/aspnet/Razor/commit/91b3b222d3a3320175d45c432e0c72f994bad80b#diff-4f1af834b38be73a1ebbffeffbde7bffR40 is not called.

I'm honestly not sure what the *right fix* is for this, or whether it should come from Roslyn or the project system. I used the power of HAXXX to create a non-production-quality workaround in my local install and then everything functions as desired.

https://github.com/rynowak/roslyn/commit/40a1e6e5c2a737bf21183855904f57e719341c13

**Comment by CyrusNajmabadi** [comment]
Note: it woudl be great if we could move off of IVSSymbolicNavigationNotify and IVSRefactorNotify .  These APIs are ancient, painful to use, and really throw a wrench in the gears of trying to have a great async story across roslyn.  They also force us to have to go use a way of describing symbols and whatnot that we built based on our old native impl, but which ideally wouldn't be necessary today.

For example, are you guys written in C#/VB?  Are you already referencing roslyn binaries for anything?  if so, we could just use the standard roslyn types here representing the symbols and what not that we were operating on.

**Comment by rynowak** [comment]
If Roslyn added new APIs for us to use for these purposes I think the only barrier would be filtering/avoiding assembly loads based on content type.

We are C#, and already have a dependency on Roslyn APIs. This would also help us eventually put together an omnisharp story.

---

I did spend a few hours wading through RQName jank - and the jank-factor is indeed **high**.

The end to end for IVSSymbolicNavigationNotify for Razor looks something like:
- Roslyn finds a symbol, realizes that it's in generated code
- Roslyn turns a document id into a hierarchy
- Roslyn turns symbol into an RQName and calls IVSSymbolicNavigationNotify
- We get called
- We turn a hierarchy into a document
- We parse the RQName
- We attempt to use the current solution and RQName to find a symbol and and it's definition
- *** We map the symbol's location in the document to an original source location and return that

Note that the only part of this that's really **Razor** is the one with the stars. It's also possible for things to go horribly wrong with the part where we parse the RQName and use it to find a symbol. We're just trying to redo what you've undone in order to call the API.

------

That said, these APIs already exist and are in use, so it's something we can start building on top of.

**Comment by jasonmalinowski** [comment]
@jinujoseph Where do we want to track this? As @CyrusNajmabadi observes this API is...not great....and this should really be holistically developed as a part of the work we're doing for Razor.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
