### ISSUE TITLE
Inconsistent scoping rule for pattern variable in `if` statement

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#25788]
This seems inconsistent:
```C#
public class C {
    void Bar1(object sender)
    {
        if (!(sender is C c)) return;
        c.ToString(); // ok
    }
    void Bar2(object sender)
    {
        if ((sender is C c) == false) return;
        c.ToString(); // error CS0165: Use of unassigned local variable 'c'
    }
}
```
Looking in the [patterns speclet](https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md#scope-of-pattern-variables) (not sure if it's up-to-date):
> The scope of a pattern variable is as follows:
> - If the pattern appears in the condition of an if statement, its scope is the condition and controlled statement of the if statement, but not its else clause.

Tagging @gafter

**Comment by gafter** [comment]
That speclet is out of date. An expression variable declared in the condition of an if statement is in the scope enclosing the if statement.

However, the error you're seeing is not about scope. It is about definite assignment. A pattern variable is definitely assigned when the pattern-matching expression is true. The unary `!` operator reverses assigned-when-true and assigned-when-false. However, the boolean equality operator `==` throws away the distinction between assigned-when-true and assigned-when-false.
