### ISSUE TITLE
Test plan for SkipLocalsInit attribute

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#25780]
First, I will start with a simple feature description. This is not meant to be a specification, just an English-language description of the feature and the intent.

The feature is to add a new well-known attribute to the compiler, System.Runtime.CompilerServices.SkipLocalsInit that causes method bodies nested "inside" the scope of the attribute to elide the ".locals init" CIL directive that causes the CLR to zero-init local variables and space reserved using the "localloc" instruction. "Nested inside the scope of the attribute" is a concept defined as follows:

1. When the attribute is applied to a module, all emitted methods inside that module, including generated methods, will skip local initialization.
2. When the attribute is applied to a type (including interfaces), all methods inside that type, including generated methods, will skip local initialization.
3. When the attribute is applied to a method, the method and all methods generated by the compiler which contain user-influenced code inside that method (e.g., local functions, lambdas, async methods) will skip local initialization.

Given that definition, the test plan follows.

* [x] Specification checked in to `csharplang` and/or `roslyn`.
* [x] Trivial case: method with SkipLocalsInit and >0 locals lists locals but no .locals init flag on emit
* [x] Method with SkipLocalsInit and no locals, but stackalloc doesn't have .locals init flag
* [x] SkipLocalsInit attribute can be mixed with other attributes
* [x] Nested functions inside method with SkipLocalsInit inherit setting
  * [x] Lambdas
  * [x] Local functions
  * [x] Async state machines
  * [x] Iterator state machines
  * [x] Local functions + async & iterator
  * [x] Versions of the previous nested inside one-another
  * [x] SkipLocalsInit *doesn't* apply to constructor of DisplayClass for closures
* [x] SkipLocalsInit on module applies to generated anonymous type
* [x] Other members
  * [x] Attribute on declaration part of partial method, but not implementation part
      * [x] Same with types
  * [x] Properties
  * [x] Indexers
  * [x] Constructors
     * [x] Field initializers that declare locals, e.g. through out var
  * [x] Finalizers
  * [x] Static versions of previous
  * [x] Property-like event handlers
* [x] SkipLocalsInit on type also applies to all previous members and nested functions/generated members
  * [x] Abstract classes/inheritance
  * [x] Also inherited to generated types
  * [x] Nested types
* [x] SkipLocalsInit on modules
  * [x] Applies to nested versions of all previous
  * [x] Works with netmodule emit
  * [x] If assembly references module with attribute, SkipLocalsInit is not automatically applied to other modules
  * [x] Applies to default interface implementations
* [ ] What to emit for EnC? 
* [x] ~~Scripting??~~
* [ ] Add supporting type https://github.com/dotnet/coreclr/pull/20093
* [x] Update Test Plan doc to mention SkipLocalsInit for future testing

## Productivity
* [ ] The diagnostic for missing `unsafe` switch should trigger appropriate fixer to fix the project

**Comment by agocke** [comment]
cc @t-camaia

**Comment by jcouv** [comment]
We need to review the "attribute API" (mostly just the namespace and name, since the attribute is trivial) with BCL team. I would recommend finalizing that API before BCL team consumes this feature (to avoid noise).
The process starts by creating an API issue on corefx, I think.

**Comment by tannergooding** [comment]
The API was reviewed and approved as part of https://github.com/dotnet/corefx/issues/29026. There is a PR adding said API to S.P.Corelib here: https://github.com/dotnet/coreclr/pull/20093 (which is currently just pending the language feature being ready).

**Comment by jcouv** [comment]
@agocke I moved this out to 16.1 based on my understanding. Feel free to adjust as appropriate.
Also, should this feature be in the [feature list](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md)?
