### ISSUE TITLE
Duplicate line doesn't work on method on some spots from a new line

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#25799]
**Version Used**: 
D15.7 Preview 2
**Steps to Reproduce**:
1. Create a new C# Console app
2. Bring the cursor to the opening bracket of the class and hit enter (create a new line)
3. From there highlight through the end of the main method. See picture
![image](https://user-images.githubusercontent.com/10537189/38057523-9c0f641c-3294-11e8-9376-8419550eb88e.png)
4. Hit ctrl E,V to duplicate the method

**Expected Behavior**:
The method duplicates
**Actual Behavior**:
The method doesn't duplicate.

This works correctly if you start the highlight from the beginning of that empty line like so:
![image](https://user-images.githubusercontent.com/10537189/38057657-f751d792-3294-11e8-92cf-f90dcf79cf98.png)

**Comment by jcouv** [comment]
@mattscheffer I'm not familiar with "Ctrl+E, V" shortcut. What command is that? Can it be done via menus too?

**Comment by mattscheffer** [comment]
It's the duplicate line command. Still relatively new. I guess the shortcut recently been changed to Ctrl+D, although the old shortcut still works. It's available here:

![image](https://user-images.githubusercontent.com/10537189/38115868-941670ec-3362-11e8-81ee-bd42255a7e94.png)

**Comment by CyrusNajmabadi** [comment]
I don't believe this is a roslyn feature.  @olegtk Does hte editor own 'duplicate line'?

**Comment by olegtk** [comment]
Hah, virtual space hits again.
Yes, this is a new editor command (since 15.6). It's Ctrl+D in all profiles, but sadly Ctrl+E Ctrl+V in C# profile. 
@jinujoseph please route the bug to the editor.

**Comment by richaverma1** [comment]
Created a duplicate issue in Editor area path.
