### ISSUE TITLE
Consider simplifying argument check for attributes in CastExpressionSyntaxExtensions

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#25790]
This is a follow-up item identified during code review: https://github.com/dotnet/roslyn/pull/20743#discussion_r177727839

**Comment by MaStr11** [comment]
Related #20742

**Comment by CyrusNajmabadi** [comment]
Closing out.  We should either do these things or not.  Having an issue akin to 'consider cleaning this up' lasting for 4+ years isn't valuable.
