### ISSUE TITLE
Intellisense suggests non-viable constructor call in delegating constructor

### ISSUE THREAD

**Issue by BillyONeal** [dotnet/roslyn#2579]
Using VS2015 RC.

When autocompleting calls to `: this()` for delegating constructors, intellisense is suggesting that the constructor call itself:

![Intellisense Suggestion](https://cloud.githubusercontent.com/assets/1544943/7519822/7a27974a-f497-11e4-97a9-a9a0a5303239.png)

Intellisense should suggest only other constructors here.

**Comment by Pilchie** [comment]
There are many places where IntelliSense shows more choices than are valid, this is definitely something that we can ship with.

**Comment by BillyONeal** [comment]
Definitely -- not a huge deal; but wanted to report it nonetheless.
