### ISSUE TITLE
Generate Equals and Hashcode Should Also Implement Operators 

### ISSUE THREAD

**Issue by julielerman** [dotnet/roslyn#25795]
**Version Used**: 
VS 15.6.4

Generate equals and GetHashcode provides a false sense of security. == will return misinformation.

**Steps to Reproduce**:

1. Create a simple class e.g. 
```
 public class Name
    {
        public Name(string givenName,string surName)
        {
            SurName = surName;
            GivenName = givenName;
        }

        public string SurName { get; private set; }
        public string GivenName { get; private set; }
}

```
2.  Use "generate equals and get hashcode" refactoring

This adds in:
```
  public override bool Equals(object obj)
        {
            var name = obj as Name;
            return name != null &&
                   SurName == name.SurName &&
                   GivenName == name.GivenName;
        }

        public override int GetHashCode()
        {
            var hashCode = -1052426677;
            hashCode = hashCode * -1521134295 +
                                  EqualityComparer<string>.Default.GetHashCode(SurName);
            hashCode = hashCode * -1521134295 + 
                                  EqualityComparer<string>.Default.GetHashCode(GivenName);
            return hashCode;
        }
```
3. Test

```
         var name = new Name("julie","lerman");
            var name2 = new Name("julie", "lerman");
             var operatorcompare = (name == name2);
            var equalscompare = (name.Equals(name2));
```
**Expected Behavior**:
 Many devs may expect operator and equals tests to both return true

**Actual Behavior**:
operatorcompare returns false because 

**Expected resulting code: (but you may think of something prettier):**
 ```
       public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }
            var name = obj as Name;
            return SurName == name.SurName &&
                   GivenName == name.GivenName;
          }

        public static bool operator ==(Name x, Name y)
        {
            return x.Equals(y);
        }

        public static bool operator !=(Name x, Name y)
        {
            return !(x == y);
        }

        //no change here
        public override int GetHashCode()
        {
            var hashCode = -1052426677;
            hashCode = hashCode * -1521134295 + 
                                EqualityComparer<string>.Default.GetHashCode(SurName);
            hashCode = hashCode * -1521134295 + 
                                EqualityComparer<string>.Default.GetHashCode(GivenName);
            return hashCode;
        }

```

**Comment by CyrusNajmabadi** [comment]
You can get this today by just selecting the option at the bottom of this dialog:

![image](https://user-images.githubusercontent.com/4564579/38057906-d29ee394-3295-11e8-8c86-2736d0c8b805.png)


![image](https://user-images.githubusercontent.com/4564579/38057895-c56d3e1e-3295-11e8-9808-1d8869e03b28.png)

**Comment by julielerman** [comment]
well that's embarrassing! Thanks though. Now I can go see how it compares to how I implemented it :)

**Comment by CyrusNajmabadi** [comment]
Nothing to be embarrassed about :)   It's debatable if these should selected by default.  However, once you pick them, we remember them for the next time you use the dialog.  And that's good enough for me.

**Comment by julielerman** [comment]
that it remembers your preference is an awesome feature!

**Comment by CyrusNajmabadi** [comment]
@jnm2 I wouldn't be opposed to a new issue asking that we have a new light-bulb that pops up the dialog, even when you have a selection.  I also wouldn't be opposed to a PR to that effect from you :D

**Comment by jnm2** [comment]
https://github.com/dotnet/roslyn/issues/30396 It might happen.
