### ISSUE TITLE
Provide API to retrieve exception diagnostics

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn#2580]
I am using CompilationWithAnalyzers.  Currently exception diagnostics is reported by GetAllDiagnosticsAsync(), along with all other diagnostics.  It would be nice to have an API to get exception diagnostics only.

**Comment by mavasani** [comment]
You can now pass in a custom exception handler into CompilationWithAnalyzers that will be invoked for every analyzer exception diagnostic: http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/CompilationWithAnalyzersOptions.cs,47

**Comment by giggio** [comment]
@mavasani In what milestone whould we expect this? 1.1?

**Comment by mavasani** [comment]
Yes, that is correct.
