### ISSUE TITLE
Implement extensible state cleanup in UseExportProviderAttribute

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#25805]
`UseExportProviderAttribute` should avoid the direct reference to `IForegroundNotificationService` by instead using an extensibility mechanism to locate services in the `ExportProvider` that need to participate in test cleanup.

https://github.com/dotnet/roslyn/pull/25681#discussion_r177924087

**Comment by sharwell** [comment]
Incorrectly closed by 10548cdc31a934ab5f82e9fde52d129707e158ce, which was supposed to close #25806.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to make this change, we should just make the change, or assign into a milestone to make it happen.
