### ISSUE TITLE
VS locks analyzers preventing package restore

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#25811]
VS 15.6.4 Enterprise

**Steps to Reproduce**:

1. Clone https://ci.appveyor.com/project/JohanLarsson/gu-wpf-adorners
2. Build

```
Severity    Code    Description    Project    File    Line    Suppression State
Error        The command ""C:\Git\Gu.Wpf.Adorners\.paket\paket.exe" restore --references-file "C:\Git\Gu.Wpf.Adorners\Gu.Wpf.Adorners\paket.references"" exited with code 1.    Gu.Wpf.Adorners    C:\Git\Gu.Wpf.Adorners\.paket\paket.targets    65 
```

**Expected Behavior**:

Restore to work.

**Actual Behavior**:

From what I have gleaned it looks like VS locks the analyzers preventing paket to restore.

**Workarounds**:
Either of:
- Close VS and run paket restore
- Close VS and build using commandline.

**Comment by JohanLarsson** [comment]
https://github.com/fsprojects/Paket/issues/3137

**Comment by sharwell** [comment]
💭 It sounds like the restore process is trying to write an identical file. Avoiding identical writes for files that are already restored would improve restore efficiency and avoid this problem.

**Comment by CyrusNajmabadi** [comment]
Due to the nature of VS doing tons of IO, it is always possible that IO contention will happen.  Best solution is to close if you're going to be writing to these files.
