### ISSUE TITLE
C# compiler chooses inaccessible extension method over accessible one

### ISSUE THREAD

**Issue by LeonidVasilyev** [dotnet/roslyn#25813]
**Version Used**: 
Microsoft (R) Visual C# Compiler version 2.6.0.62329 (5429b35d)

**Steps to Reproduce**:

1. Create new console application with following code in `Program.cs`:
```csharp
using System;
using System.Collections.Generic;
using System.Linq;

public class Program
{
    static void Main(string[] args)
    {
        var a = new[] { 0 };
        var b = new[] { 1, 2, 3 };
        Console.WriteLine(b.Count(a.Contains));
    }
}

public static class Extensions
{
    // NOTE: private access modifier simulates internal class public method in referenced assembly.
    private static bool Contains<T>(this IEnumerable<T> a, T value) =>
        throw new NotImplementedException();
}
```
2. Build project or wait full solution analysis to complete

**Expected Behavior**:
Project compiled successfully. `System.Linq.Enumerable.Contains()` used as an argument of `System.Linq.Enumerable.Count()` function.

**Actual Behavior**:
Compiler error CS0122: 'Extensions.Contains<T>(IEnumerable<T>, T)' is inaccessible due to its protection level

Original case is described in [C# compiler chooses wrong extension method](https://stackoverflow.com/questions/49554228/c-sharp-compiler-chooses-wrong-extension-method#comment86117664_49554228) question on StackOverflow. [CS0122 wrong member inaccessible when overload does not exist](https://github.com/dotnet/roslyn/issues/15401) issue looks related.

**Comment by Joe4evr** [comment]
Should be something to be improved as part of dotnet/csharplang#98

@gafter It doesn't seem like this is part of those improvements. Is this perhaps a regression? If not, can this still be added as part of the improved overload resolution?

**Comment by jcouv** [comment]
~~Assigning to 15.7 milestone for now, we should confirm whether this is a 15.7 regression.~~
Never mind, the repro is in 15.5 (compiler version 2.6).
I'll let @gafter triage to appropriate milestone.

**Comment by gafter** [comment]
VS2015 behaves exactly the same way.

**Comment by gafter** [comment]
See https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#extension-method-invocations . In the terminology of the spec, we are letting non-***eligible*** candidates short-circuit finding the right method group.

**Comment by gafter** [comment]
In review in #26345
