### ISSUE TITLE
Enable LangVersion 7.3 in master (for 15.8)

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#25816]
We should dogfood C# 7.3 as soon as possible.

For this we need:
- [ ] 15.7 ~~preview 3~~ RTM to be released
- [x] sign-off from source build folks

**Comment by jasonmalinowski** [comment]
@jcouv we've got the first, what about the second? Is this something we should start doing?

**Comment by jcouv** [comment]
@jasonmalinowski Yes. There is a discussion thread from Jared.

**Comment by jcouv** [comment]
Talked to Jared. The source builds folks are ok with this change.
I'll make the change as soon as preview 3 is released and we have nuget packages for the preview 3 compiler bits.
