### ISSUE TITLE
Work to migrate http://source.roslyn.io to a modern ElasticSearch based solution.

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#25824]
This is a long-term tracking issue to move http://source.roslyn.io to the new dynamic engine currently being developed over at https://github.com/ref12/codex

**Comment by Mpdreamz** [comment]
💓 this @KirillOsenkov let me know if I can be of any assistance on the Elasticsearch side of things!

**Comment by russcam** [comment]
Same as @Mpdreamz; let me know if there's anything on Elasticsearch side I can help with :+1:
