### ISSUE TITLE
UI delays opening a large solution due allocation pattern we use for adding project references

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#25823]
Have a large > 350 project that is having UI delays, took a few traces. In this case, 70% of CPU and 100% of the UI time was spent cleaning up Gen1 allocations while adding references to Roslyn:

UI thread view only (note this is CPU not time):
![image](https://user-images.githubusercontent.com/1103906/38120647-110b76a2-3416-11e8-801b-3064be434536.png)

Allocations on this path:
![image](https://user-images.githubusercontent.com/1103906/38121075-c06ae9e6-3418-11e8-8536-16298a2d65d2.png)

Note, this might be particular bad because of this scenario:

- Open solution
- Design-time build finishes -> Add direct ProjectReferences 
- NuGet restore
- Design-time build finishes -> Add transitive ProjectReferences

**Comment by davkean** [comment]
tag @jasonmalinowski

**Comment by davkean** [comment]
Trace is: \\mlangfs1\public\davkean\Roslyn\25823

**Comment by Pilchie** [comment]
When I've seen this before, it's related to the fact that the adds aren't batched for CPS projects.  I think in the non-batching case it ends up creating a project dependency graph in Roslyn on every reference add, whereas in the batched case it only does so once at the end.

**Comment by jasonmalinowski** [comment]
Yeah, that's my gut too. This likely will be improved by the batching support I'm adding for you. That said, it might be worth looking too at the project dependency graph code to see if there's some optimizations that can be made. I could imagine even with batching re-creating 350 graphs in a huge thing might still be allocating like mad, no matter what.

**Comment by jasonmalinowski** [comment]
@Pilchie @davkean Any reason to keep this bug alive separate of the internal tracking bugs we have for this work?
