### ISSUE TITLE
'Introduce local for x' changes code and introduces errors

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25838]
When extracting code with &quot;Introduce local for 'x'&quot; refactoring:
- extension method calls get rewritten to use static method calls;
- unnecessary casts get introduced

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/63032/introduce-local-for-x-changes-code-and-introduces.html
VSTS ticketId: 444218_
_These are the original issue comments:_

Sam Harwell [MSFT] on ‎6‎/‎2‎/‎2017, 00:30 PM (300 days ago): <p>Hi Rafael,</p><p>I'm currently trying to reproduce this. I tested a handful of samples in both 15.2 and 15.3 Preview 1 with things like nullable types and LINQ helper methods, but was so far unable to observe the behavior you described. It sounds like you may have hit a special case related to your specific code that wasn't accounted for by the refactoring yet. Would you be able to share a code sample that reproduces this to help me track it down?</p><p>Thanks,</p><p>Sam</p>

Sam Harwell [MSFT] on ‎7‎/‎3‎/‎2017, 02:38 PM (269 days ago): <p>Thank you for your feedback! For us to investigate this further, could you please provide some sample code which reproduces the issue?  We look forward to hearing from you!</p>

Kevin Pilch [MSFT] on ‎7‎/‎24‎/‎2017, 03:29 PM (248 days ago): <p>Thank you for your feedback! Unfortunately, right now we don't have enough information to investigate this issue and find a solution. If this is still an issue for you, please update to our latest version. If you are still able to repro it, please provide us with more info! Thank you for helping us build a better Visual Studio!</p>

Rafael de Lima Reis on ‎3‎/‎27‎/‎2018, 01:37 PM (2 days ago): Repro steps.Create an extension method like below:       public static Runtime.CompilerServices.ConfiguredTaskAwaitable IgnoreContext(this Task task)        \{            return task.ConfigureAwait(false);        }Call the method from some Task-valued expresion, e.g:         var text = await FileEx.ReadAllText(outputFilePath).IgnoreContext();Select "await FileEx.ReadAllText(outputFilePath)" and activate "Introduce local for" refactoring.Voilá:                        var task = FileEx.ReadAllText(outputFilePath);                        var text = await System.Threading.Tasks.TaskExtensions.IgnoreContext(task);We can observe:        1. The extension method call was rewritten as a static method call.        2. A type variable argument was introduced where there wasn't any.Depending on the case, the result can be way worse (the more complicated the line where you extract the code, the worse). I've seen casts being introduced where none was needed. More fundamentally, all these transformations introduces syntactic changes -- altering the original text of the program.Thanks.
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
Here is a reformatted copy of the repro steps from the last comment:

> 1. Create an extension method like below:
>
>     ```csharp
>     public static ConfiguredTaskAwaitable IgnoreContext(this Task task)
>     {
>       return task.ConfigureAwait(false);
>     }
>     ```
>
> 2. Call the method from some Task-valued expresion, e.g:
>
>     ```csharp
>     var text = await FileEx.ReadAllText(outputFilePath).IgnoreContext();
>     ```
>
> 3. Select `await FileEx.ReadAllText(outputFilePath)` and activate "Introduce local for" refactoring. Voilá:
>
>     ```csharp
>     var task = FileEx.ReadAllText(outputFilePath);
>     var text = await System.Threading.Tasks.TaskExtensions.IgnoreContext(task);
>     ```
>
> We can observe:
>
> 1. The extension method call was rewritten as a static method call.
> 2. A type variable argument was introduced where there wasn't any.
>
> Depending on the case, the result can be way worse (the more complicated the line where you extract the code, the worse). I've seen casts being introduced where none was needed. More fundamentally, all these transformations introduces syntactic changes -- altering the original text of the program.
>
> Thanks.

**Comment by CyrusNajmabadi** [comment]
Looks like an issue with complexification/simplification.
