### ISSUE TITLE
find all reference is throwing causing OOP to halt

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#25836]
basically this is throwing
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/FindSymbols/Extensions.cs,42

more detail here
https://developercommunity.visualstudio.com/content/problem/170285/unfortunately-a-process-used-by-visual-studio-has-4.html?childToView=214851#comment-214851

I made simple fix
https://github.com/dotnet/roslyn/pull/25789

but seems like not right fix. there seems some kind of contract that someone must hold onto SemanticModel before calling these extension methods. but I dont know exactly what the contracts are and who should hold onto semantic model in what situation and where in find all reference.

probably people who is more knowledgeable than me on find all reference should make the right fix.

opening issue since it is one of top cause that bring down OOP.

**Comment by heejaechang** [comment]
tagging @jinujoseph

**Comment by sharwell** [comment]
@heejaechang I submitted a PR for this based on your observation in #25789
