### ISSUE TITLE
Update Roslyn's use of xliff-tasks to a newer version for better merging

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#25849]
@tmeschter added logic to xliff-tasks so it doesn't always insert new strings at the end, asking for endless merge conflicts. This is particularly painful in Roslyn due to the high number of branches we have.

**Comment by jaredpar** [comment]
What version is applicable here and is there a guide to what work is needed? If there is another repository that already took this version can we link to that PR?

**Comment by tmeschter** [comment]
Only the latest version of XliffTasks (0.2.0-beta-62730-03) has this change.

The work on the dotnet/roslyn side is to:

1. Find where we specify the XliffTasks version and update it
2. Try adding a few test items to an existing .resx file, building, and verifying that the new items haven't simply been appended at the end of the .xlf files.

I suggest doing the work in the `dev15.7.x` branch and letting it flow to other branches from there.

No other repos have adopted this updated XliffTasks yet.
