### ISSUE TITLE
use ValueTask in Roslyn

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#25843]
Roslyn has this design where we cache things in WeakReference. 

we do this so that we can support observable reference equality identity. (if someone has object from GetXXX method, consequent call to GetXXX returns same instance without strongly hold onto object)

this pattern is really good candidate for ValueTask since a lot of time, in GetXXXAsync, we check WeakReference and if it exist, we return right away even before reaching the first await in async method.

this should also let us remove TryGetXXX methods for many places. 

previously there was no way to get around cost of Task so we provide TryGetXXX to workaround calling async method. With ValueTask, cheaper code path stay cheap. so I believe we don't need TryGetXXX anymore.

**Comment by heejaechang** [comment]
@dotnet/roslyn-ide thought?

**Comment by jasonmalinowski** [comment]
@heejaechang Make it so! Although not sure if @sharwell knew of some other technical problems we might run into.

**Comment by sharwell** [comment]
@heejaechang We cannot avoid the new assembly load, so #23557 is just waiting for enough supporting evidence.

**Comment by CyrusNajmabadi** [comment]
+1 on this.  I think it would be very good.  However, i have struggled with how would could provide this in a binary compatible manner.  I presume all our public entrypoint would have to stay ```Task/Task<T>```.  So would this just be to get all our internal methods to be ValueTask?

Also, is this something we can do in bulk?  Or does that have hte potential to actually make things worse in some cases.  My primary concern is that if it's good in some cases, but bad in others, it will be hard for IDE devs to know when and where they should use this stuff...

**Comment by sharwell** [comment]
> So would this just be to get all our internal methods to be ValueTask?

I didn't switch all of them. I switched only cases where PerfView showed `Task` allocations in the async state machine prior to suspending (i.e. the value was available synchronously in the majority of cases).

**Comment by heejaechang** [comment]
we can start with non public API, but it would be nice to change public API.

also, I think we can do it systematically. any async method that can return before first await should benefit from ValueTask I believe.

**Comment by sharwell** [comment]
@heejaechang it's not always that simple. For example, `async Task` and `async Task<book>` methods never allocate when they return synchronously. The same applies for `async Task<T>` where `T` is a reference type and the returned value is `null`.

**Comment by Joe4evr** [comment]
I believe all the values that goes for are `true`, `false`, `0`, `1`, `null`, `""`, and the "void" result.

**Comment by heejaechang** [comment]
@sharwell sure. we can consider those optimization in the framework if we want to. 

Either default to Task until proven to be too expansive and move to ValueTask. or default to ValueTask until proven to be more expensive than Task.

fine both way.

but my preference will be default to ValueTask since it is more flexible than Task and the argument of 2 fields vs 1 field is actually matter in real life. especially for code like Roslyn where it operate over zillion of objects/structs already.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We move to ValueTask where we can.  When there is binary compat, we can't.  we can attempt to cache tasks judiciously where possible, but that should be driven by clear need with traces showing the benefit.
