### ISSUE TITLE
GoTo sometimes incorrectly completes with no results

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#25853]
Repro:
1. pick a test name (like `CodeGenStackAllocInitializerTests.TestUnmanaged_Span`)
2. open `Compilers.sln` in VS
3. `Ctrl+T` to invoke "GoToAll" and search for `CodeGenStackAllocInitializerTests.TestUnmanaged_Span` while the solution is still not fully loaded
4. GoToAll may complete with no result
5. Search again and GoToAll may now find the result

The expected behavior is that GoToAll should not complete at step (4), if the solution isn't completely loaded and it didn't get the opportunity to check all the symbols.

**Comment by CyrusNajmabadi** [comment]
@olegtk I thought there was somehting on VS's side where it would mark the go-to results as being possibly incomplete while the solution is loading.  Did that change at some point?

**Comment by Neme12** [comment]
This has happened to me multiple times.

**Comment by Pilchie** [comment]
Tagging @davkean here.  It's likely that work for those projects is still happening asynchronously.

**Comment by olegtk** [comment]
I get this occasionally when invoking GoTo just after opening big solution. @grabalon is this a known issue?

**Comment by CyrusNajmabadi** [comment]
this syste mhas been substantially rewritten.  I have not experienced the issue reported, and we do give messages if you're in solution load and hte index isn't fully built.  i'm going to close this out.
