### ISSUE TITLE
Pasting code in front of Xml doc comments caused strange indentation.

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn#2585]
1. paste the following code to a C# file

``` csharp
class Test
{
    /// <summary>
    /// Summary
    /// </summary>
    /// <param name="x">x</param>
    /// <param name="y">y</param>
    public void Method(int x, int y) { }

    const int i = 1;
}
```
1. select the `const int i = 1;` line, without the new line character
2. put cursor at beginning of the `/// <summary>` line
3. paste

**Actual**

``` csharp
class Test
{
    const int i = 1;    /// <summary>
                        /// Summary
                        /// </summary>
                        /// <param name="x">x</param>
                        /// <param name="y">y</param>
    public void Method(int x, int y) { }


}
```

**Expected**
Maybe don't indent the lines, if the first xml doc comment line isn't starting on a new line.

**Comment by Pilchie** [comment]
My preference would be to force an additional newline in this case.

**Comment by Pilchie** [comment]
Hitting enter and then formatting fixes this, and I think it's probably relatively rare.

**Comment by CyrusNajmabadi** [comment]
Haven't heard from any other customers about this.  Seems niche.
