### ISSUE TITLE
Feature Request: CodeFix to add using for extension method

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#25861]
**Scenario**:
`Windows.Foundation.IAsyncOpearation<T>` does not has definition for `GetAwaiter()`

**Expected**:
Add `Using System;` to make the extension method into scope.

**Comment by sharwell** [comment]
This feature already works for most extension methods, but not for the implicitly called `GetAwaiter()` here. I hit the same thing this week trying to `await TaskScheduler.Default`.

**Comment by CyrusNajmabadi** [comment]
Yup.  seems like a reasonable thing for hte IDE look for and to offer.  We already detect things like linq-queries and offer suggestions in that sort of construct.

**Comment by huoyaoyuan** [comment]
Revisit this in 16.3:
Error message indicates that "missing using directive for System", but no quick action provided.
