### ISSUE TITLE
Recognize backquotes and triple-backquotes in xml docs

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#25867]
![image](https://user-images.githubusercontent.com/12466233/38170615-051a744a-353f-11e8-9312-7458c83b3535.png)

Relates to https://github.com/dotnet/roslyn/pull/23984/files#r178449741

**Comment by CyrusNajmabadi** [comment]
This would be nice to have :)    Look at the DocumentationComment type for where the IDE takes the xml text and processes it.

**Comment by sharwell** [comment]
This needs to go to a design meeting. I have a strong objection to implementation prior to design approval and adoption in the language specification.

**Comment by sharwell** [comment]
See dotnet/csharplang#891 for the language design issue.

**Comment by svick** [comment]
I agree that supporting Markdown (and possibly also some simple syntax for XML elements that don't have counterparts in Markdown) is a great idea. But it should be done all at once in a systematic manner, not "add backquotes, then some other syntax, then another, and end up with complex, undocumented mess".

**Comment by sharwell** [comment]
During a design meeting today, we determined that this feature can't really move forward until *at minimum* one of the following occurs:

* The language specification is updated to define generalized documentation comment support for the proposed syntax
* The Visual Studio editor/platform team puts forward a proposal for unified handling of this syntax across a variety of programming languages supported in Visual Studio, as a visual aid to developers who wish to deviate from features specific to individual languages

The implementation of the second item does not guarantee that the feature will be implemented without support from the language specification; should that situation arise will again consider the available design proposals to decide if the issue should remain blocked.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is more of a language request.  We are interested in markdown cases, so this should go into that discussion.
