### ISSUE TITLE
Inline out variable with existent name causes scope inconsistency in VS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25869]
Sometimes a picture is worth more than a thousand words, so as to keep the description short, please take at the attached image.
![image](https://user-images.githubusercontent.com/12449387/38175081-c8c43e7a-358b-11e8-883c-dde9a64dc928.png)

Essentially, having an inline out variable with the same name as a field variable causes VS to show the wrong value for the field variable even prior to execution of the inline out statement itself.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/222900/inline-out-variable-with-existent-name-causes-scop.html
VSTS ticketId: 589672_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by gafter** [comment]
The variable `orderId` is in scope from the beginning of the block by the language rules. You are seeing its default value before the declaration (which is something you are permitted to do in the debugger).

This is by design.

**Comment by Serenata-Justin** [comment]
This doesn't really explain why mouse-over on the field declaration would show a value of 0, whereas the value is _null_ in the Immediate Window.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
