### ISSUE TITLE
Implement functions are not implements correctly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25878]
Sometimes when I do &quot;Implement missing members&quot;, for example method &quot;void someFunction(bool? isA = false);&quot;
It implements like this: &quot;void someFunction(bool? isA);&quot;

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/207284/implement-functions-are-not-implements-correctly.html
VSTS ticketId: 576470_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Could not repro this.  Will need more info to move forward on this.
