### ISSUE TITLE
Auto-complete in brackets

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25873]
I've noticed this with a few objects but with a dictionary I can walk through it.

With a Dictionary (call it D) if I type D[ the closing bracket appears, then when I put in the quotation mark the second set appears
I type D[&quot;  and the ide gives me D[&quot;&quot;]  (all is good)

It does not have this behaviour inside of brackets 

example: 
if(D[&quot;)   I must manually type the 2nd quote and bracket.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/220250/auto-complete-in-brackets.html
VSTS ticketId: 587269_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I cannot repro this:

![image](https://user-images.githubusercontent.com/4564579/38180927-d295070a-35e4-11e8-96e0-6e92914928ff.png)

**Comment by Neme12** [comment]
@CyrusNajmabadi Try without the parentheses being brace completion inserted by typing this inside an existing `if ()`.

**Comment by Neme12** [comment]
![image](https://user-images.githubusercontent.com/11444821/38197005-4d4123c0-3686-11e8-88c7-95f9390d6fd0.png)

**Comment by Neme12** [comment]
![brace](https://user-images.githubusercontent.com/11444821/38197013-5a1be10c-3686-11e8-951a-bd9047723e56.gif)

**Comment by CyrusNajmabadi** [comment]
Still can't repro this.  I always get the right behavior:

![image](https://user-images.githubusercontent.com/4564579/217939825-d6066be9-1864-4d60-af65-d730299f979e.png)
