### ISSUE TITLE
Enable and audit dispose rule suppressions in Roslyn.sln (CA2000 and CA2213)

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#25880]
https://github.com/dotnet/roslyn/pull/25179 attempts to move us to newer analyzer packages that includes the experimental implementation of CA2000 and CA2213. There are quite a few differing opinions on what should be suppressed vs fixed, and we also have differing opinions on how dispose ownership transfer should be designed for the rule (https://github.com/dotnet/roslyn-analyzers/issues/1617). Hence, we have decided to add suppressions for majority of dispose violations flagged in https://github.com/dotnet/roslyn/pull/25179. This issue tracks auditing these suppressions and fixing OR resolving by design.

**Comment by sharwell** [comment]
Here are my expectations for these rules:

1. A set of rules (guidance) exist for the use of `IDisposable`, which the analyzers aim to enforce
2. The rules of (1) represent a sufficient condition for safe use of `IDisposable`
3. The analyzers implement a documented set of rules which form a conservative subset of rules of (1)
4. Outside of extenuating circumstances, code using `IDisposable` can be written according to the rules of (3) without suppressing analyzer warnings
5. Code adhering to (4) does not report warnings from the analyzers

I consider steps 1-4 hard requirements (prerequisites) for enabling the analyzers in Roslyn.sln, and item 5 may only be relaxed for cases of bugs affecting a minority of code adhering to (4) where the analyzers failed to correctly implement the documented rules of (3). This approach is quite flexible in terms of the final approach, and represents a reasonable minimum acceptance bar that customers will have.

**Comment by mavasani** [comment]
> I consider steps 1-4 hard requirements (prerequisites) for enabling the analyzers in Roslyn.sln

Note that these are *not* new rules, which are being designed from scratch. There are already existing implementations of these rules in the binary FxCop world and there are extremely large number of code bases that rely on the current design/heuristics, especially since they have done the work to audit/suppress the violations. The analyzer implementation matches prior FxCop rule design/heuristics. This was already discussed at prior design meeting(s) and we decided:
  1. Match binary FxCop implementation as much as possible - this is a strict compat requirement.
  2. If we can adopt any further heuristics to reduce the false positives, we should do so. However, we can do so only if we know for sure that we will not introduce any more false positives due to these new hueristic(s). None of the alternate heuristics suggested in https://github.com/dotnet/roslyn-analyzers/issues/1617 by @sharwell satisfy this requirement, and hence have not been implemented.

Hence, we have already satisfied the requirements set by design time for this rule implementation.

**Comment by sharwell** [comment]
It is possible, and acceptable, for the design of CA2000 and CA2213 to deviate from the design of a set of usable `IDisposable` rules (due the compatibility requirement limitation of the former) to the point that the rules never meet the requirements for adoption in Roslyn.sln. In such a situation, I would expect the original rules to be locked to the legacy rules, and then a new rule (or set of rules) implemented for use in code that didn't originally use FXCop. Once the new rule existed (perhaps in beta), it could be enabled for Roslyn.sln. In the interim, Roslyn.sln would not use analyzer rules for `IDisposable`.

**Comment by mavasani** [comment]
> It is possible, and acceptable, for the design of CA2000 and CA2213 to deviate from the design of a set of usable IDisposable rules (due the compatibility requirement limitation of the former) to the point that the rules never meet the requirements for adoption in Roslyn.sln.

I would be *strongly* opposed to having multiple _heuristic_ based implementations of a specific rule, just to satisfy preferred heursitics for different code bases. This is not how we write analyzers, and is not a valuable use of anyone's time and resources. Instead we should attempt to improve the rule implementation to reduce dependence on heuristics, as suggested by possible approaches in https://github.com/dotnet/roslyn-analyzers/issues/1617#issue-300330737.

**Comment by sharwell** [comment]
> I would be strongly opposed to having multiple heuristic based implementations of a specific rule, just to satisfy preferred heursitics for different code bases.

This is fine, provided there is no expectation that analyzer rules for `IDisposable` be adopted by Roslyn.sln or other code bases that didn't originally use FXCop.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
