### ISSUE TITLE
EditorConfig is not used for files included as content

### ISSUE THREAD

**Issue by mikkelbu** [dotnet/roslyn#25888]
**Version Used**: 
Visual Studio Version 15.3.5

**Steps to Reproduce**:

1. Have a project file - in the new format - that includes a file (`ClassB.cs`) as content
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ClassB.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ClassB.cs" />
  </ItemGroup>

</Project>
```
2. And have a .editorconfig file that the class does not follow (e.g. `ClassB.cs` is written using TABs). Note that the .editorconfig should also be different from the default settings in VS.
```editorconfig
root = true

[*]
indent_style = space
indent_size = 7
```
3. When opening `ClassB.cs` it is noted _"user preferences for this file type are overridden by this project's coding conventions"_. However, when manipulating the file (e.g. removing and readding the last `}` or using "Format Document") the settings used are not taken from the .editorconfig file, but from the settings in VS.

I've uploaded a small example to https://github.com/mikkelbu/EditorConfig-and-ContentFiles. The example contains two C# files `ClassA.cs` and `ClassB.cs` that are identical except for the class name, and both files use TABs (thus not following the .editorconfig in the project). `ClassA` is compiled, whereas the content of `ClassB` is copied to the output.

When applying "Format Document" only `ClassA` make use of the .editorconfig-settings (`ClassB` "just" uses the standard settings in VS).

**Expected Behavior**:
That the configuration in .editorconfig is also used for files included as content.

**Actual Behavior**:
That the (default) VS configuration is used for files included as content.

**Comment by CyrusNajmabadi** [comment]
Yes.  This is by design.  Content files are just content.  THey are not treated as code that would be affected.
