### ISSUE TITLE
Flaky test Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.AutomaticCompletion.AutomaticLessAndGreaterThanCompletionTests.TestAttribute_LessThan_Method

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#25885]
https://ci.dot.net/job/dotnet_roslyn/job/dev15.7.x/job/windows_debug_unit32_prtest/1000/

This test appears to be flaky. 

> System.TimeoutException : Failed to clean up listeners in a timely manner.\r\n---- System.OperationCanceledException : The operation was canceled.

**Comment by sharwell** [comment]
This should be fixed by #25892, and if not it should be diagnosable by #25896

**Comment by CyrusNajmabadi** [comment]
Closingo ut as we hven't had any failures here in ages.
