### ISSUE TITLE
Possible race conditions in WeakReference<T>.SetTarget

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#25881]
The following two cases may suffer from race conditions in the use of `WeakReference<T>`, similar to the one described in #25839. 

https://github.com/dotnet/roslyn/blob/4f3739a1141630e710a7ee1c96285c2a88bc80ab/src/Workspaces/Core/Portable/SemanticModelWorkspaceService/SemanticModelWorkspaceServiceFactory.cs#L229-L239

https://github.com/dotnet/roslyn/blob/878ffad23b8b06cb229c9ab31eada7634a473508/src/VisualStudio/Core/Def/Implementation/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManager.RecoverableMetadataValueSource.cs#L58

**Comment by CyrusNajmabadi** [comment]
Closing out as this has been rewritten and does not use weakrefs anymore.
