### ISSUE TITLE
In Roslyn can StringWriter be made Pooled?

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#25902]
In the VB CommandLineTest the is a lot of use of `StringWriter` object.
I wonder if it will be beneficial to make it a Pooled resource.

**Comment by jmarolf** [comment]
We'd only pool a resource if there was significant (say 30%) speedup for the test run.  I find that unlikely here.  It would just add more complexity to the tests.  My hope is that our test suite optimizes for explicitness and readability first.
