### ISSUE TITLE
Some code fixes/refactorings do not respect document EOL settings

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#25927]
**Version Used**: 
2.8.0-beta3-62728-05

**Steps to Reproduce**:

1. See https://github.com/mono/monodevelop/issues/4409 for repro case

**Expected Behavior**:
EOL settings should be respected

**Actual Behavior**:
In some cases, CRLF or LF are inserted regardless of document options.

Analysis:
From what I've seen, the offending code is using `SyntaxFactory.CarriageReturnLineFeed` directly: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Utilities/UsingsAndExternAliasesOrganizer.cs,14

From what I understand, maybe `SyntaxFactory.ElasticCarriageReturnLineFeed` should be used instead, so the formatter call from here uses the right EOL endings:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/AddImport/References/Reference.cs,134
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeActions/CodeAction.cs,275

As an afterthought, maybe all occurences of non-elastic should be looked at and fixed if needed. I only saw these being used:
[CarriageReturnLineFeed](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/SyntaxFactory.cs,a423a39f71bc6b2e,references)
[Space](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/SyntaxFactory.cs,be62a5f285c5a69a,references)
[Whitespace](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/SyntaxFactory.cs,1caba9a5a9e790b7,references)

**Comment by Therzok** [comment]
cc @sharwell @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Want to just create a PR to fix the issue? Thanks!

**Comment by binki** [comment]
This issue claims to be in milestone 15.8 but I still see this issue in visualstudio-15.8.1. If I use a codefix to add a msising `using` statement and that statement is placed at the beginning of the file/prior to other `using`s, it will use CRLF instead of LF even though the file is otherwise LF.

**Comment by binki** [comment]
I have been referred here from https://developercommunity.visualstudio.com/content/problem/300749/codefix-for-adding-missing-using-statement-namespa.html and it is still an issue for me in visualstudio-15.8.1. @sharwell , is this actually a different issue?

**Comment by binki** [comment]
![image](https://user-images.githubusercontent.com/82626/44288494-86521b00-a23e-11e8-9719-ba026cfec5c9.png)
