### ISSUE TITLE
Add member classification for captured locals

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#25924]
As mentioned in https://github.com/dotnet/roslyn/issues/25593#issuecomment-378571152, it would be helpful to support classification of captured locals in the IDE. By applying customized styling to these items, users would have a visual indicator for cases where a variable is captured by a lambda expression or other language construct that allows for implicit captures.

**Comment by Neme12** [comment]
I guess I don't really see what the idea is here. Would locals that are captured (anywhere) have a different text color? Isn't that too noisy?

**Comment by sharwell** [comment]
> Would locals that are captured (anywhere) have a different text color?

By default, nothing would change. I would just add an option to **Fonts and Colors** where you could change the settings if it's something you desire.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we want to do this, we should assign a dev/milestone.
