### ISSUE TITLE
Empty MetadataReferences for project referencing other project from same solution.

### ISSUE THREAD

**Issue by ma-rybak** [dotnet/roslyn#25921]
**Version Used**: 
2.7.0
**Steps to Reproduce**:

1. Create solution with two projects, A and B
2. Reference project B to project A
3. Open project A using 
`var workspace = MSBuildWorkspace.Create(additionalProperties);
 Project project = workspace.OpenProjectAsync(projectPath).Result;`

**Expected Behavior**:
project.MetadataReferences should contain project's references, such as mscorlib.dll
**Actual Behavior**:
project.MetadataReferences is empty.

I found some similar issue, however, I'm not sure if cause is the same: https://github.com/dotnet/roslyn/issues/25311

**Comment by jcouv** [comment]
Tagging @DustinCampbell for expected behavior and triage. Thanks

**Comment by paul1956** [comment]
When I try to install your version I get
```
Install-Package Microsoft.CodeAnalysis.Workspaces.MSBuild -Version 2.9.0-beta4-62819-06 -Source https://dotnet.myget.org/F/roslyn/api/v3/index.json
Restoring packages for C:\Users\PaulM\Documents\Visual Studio 2017\Projects\CSharpToVB\CSharpToVB\CSharpToVB.vbproj...
  GET https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.workspaces.msbuild/index.json
  NotFound https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.workspaces.msbuild/index.json 109ms
Install-Package : NU1101: Unable to find package Microsoft.CodeAnalysis.Workspaces.MSBuild. No packages exist with this id in source(s): 
Microsoft Visual Studio Offline Packages, nuget.org
At line:1 char:1
+ Install-Package Microsoft.CodeAnalysis.Workspaces.MSBuild -Version 2. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'CSharpToVB'.
At line:1 char:1
+ Install-Package Microsoft.CodeAnalysis.Workspaces.MSBuild -Version 2. ...
```

**Comment by jcouv** [comment]
@paul1956 From the error message you pasted, I see that the package was looked up on nuget.org. But the package Dustin shared is on myget.org. 
You'll need to add the myget.org feed to get the package he suggested.

**Comment by paul1956** [comment]
I was able to install after adding myGet with source https://dotnet.myget.org/F/roslyn/api/v3/index.json but now every test returns:

```
Message: System.TypeLoadException : Derived method 'CommonWithMetadataImportOptions' in type 'Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilationOptions' from assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' cannot reduce access.
```
I saw a reference to deleting MSBUILD.* from Output Directory but VB does not have an Output directory and the only place I see MSBUILD files is under the .vs directory.

**Comment by jmarolf** [comment]
> VB does not have an Output

Wherever your compiled assemblies are being run from should be considered the output directory in this case.

**Comment by DustinCampbell** [comment]
> > VB does not have an Output

> Wherever your compiled assemblies are being run from should be considered the output directory in this case.

Correct. For example, `bin\Debug`

**Comment by DustinCampbell** [comment]
@paul1956 : Note that the instructions that I posted above are for two things:

1. Using the currently shipping `MSBuildWorkspace` successfully. That's what https://github.com/FizzerWL/ErrorRepro/pull/1 is about.
2. Using the not-yet-released beta of the next `MSBuildWorkspace` successfully.

If you're going with `2` above, you shouldn't need to remove `Microsoft.Build.*` assemblies from your output because the `Microsoft.CodeAnalysis.Workspaces.MSBuild` will not pull them into your project. However, if you had added your own package references to `Microsoft.Build`, `Microsoft.Build.Framework`, `Microsoft.Build.Tasks.Core` or `Microsoft.Build.Utilities.Core`, you'll want to remove them.

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  Perhaps a misconfigured msbuild locally?
