### ISSUE TITLE
[Feature] Language service for embedded JSON

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#25939]
This feature is worked on in `features/embeddedJson` branch.

- [x] common infrastructure (https://github.com/dotnet/roslyn/pull/25541)
- [ ] JSON parser (https://github.com/dotnet/roslyn/pull/24110)
- [ ] common infrastructure for language service (https://github.com/dotnet/roslyn/pull/25985)
- [ ] Language service (https://github.com/dotnet/roslyn/pull/25518)
- [ ] Tests (https://github.com/dotnet/roslyn/pull/25521)
- [ ] Additional validation before merging

**Comment by CyrusNajmabadi** [comment]
Closing this out.  All this work was done ages ago.
