### ISSUE TITLE
[xUnit] [ERROR] - The result file Roslyn.Services.Editor.UnitTests.dll.xml for the metric 'xUnit.Net' is empty. 

### ISSUE THREAD

**Issue by JieCarolHu** [dotnet/roslyn#25930]
The following error appeared in 2 runs. Will update this issue if the same test fails again.

[xUnit] [ERROR] - The result file 'D:\j\workspace\windows_relea---c796cf20\Binaries\Release\UnitTests\EditorServicesTest\xUnitResults\Roslyn.Services.Editor.UnitTests.dll.xml' for the metric 'xUnit.Net' is empty. The result file has been skipped.

https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x/job/windows_release_unit32/229/

https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x/job/windows_release_unit64/227/

**Comment by sharwell** [comment]
The reason for failure in both of these builds is shown in the commit log:

> 14:33:05 Roslyn Error: test timeout exceeded, dumping remaining processes
