### ISSUE TITLE
Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.DiagnosticsSquiggleTaggerProviderTests.Test_TagSourceDiffer

### ISSUE THREAD

**Issue by JieCarolHu** [dotnet/roslyn#25933]
The following test failed in official build. Will update this issue if the same test fails again.

Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.DiagnosticsSquiggleTaggerProviderTests.Test_TagSourceDiffer

https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_unit32/2122/

**Comment by sharwell** [comment]
This was supposed to be fixed by #25892. Can you determine if this commit was included or not at the time of the failure?

**Comment by JieCarolHu** [comment]
@sharwell the commit you mentioned is not included at the time of failure. I am closing this issue for now. Will reopen the same test fails again.
