### ISSUE TITLE
Microsoft.CodeAnalysis.Editor.UnitTests.SolutionCrawler.WorkCoordinatorTests.FileFromSameProjectTogetherTest

### ISSUE THREAD

**Issue by JieCarolHu** [dotnet/roslyn#25931]
The following test failed in official build. Will update this issue if the same test fails again.
Microsoft.CodeAnalysis.Editor.UnitTests.SolutionCrawler.WorkCoordinatorTests.FileFromSameProjectTogetherTest 

https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x/job/windows_debug_unit32/234/

**Comment by JieCarolHu** [comment]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x-vs-deps/job/windows_release_unit32/90/

**Comment by JieCarolHu** [comment]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x-vs-deps/job/windows_release_unit32/89/

**Comment by JieCarolHu** [comment]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x-vs-deps/job/windows_debug_unit64/86/

**Comment by sharwell** [comment]
@heejaechang This is a new flaky test you added recently.

**Comment by heejaechang** [comment]
@sharwell thank you. taking a look.

**Comment by CyrusNajmabadi** [comment]
Haven't had any issues with this test in years.  And we have a dedicated system for tracking test flakeyness now.
