### ISSUE TITLE
[Feature] Language service for embedded Regex

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#25940]
This feature is worked on in `features/embeddedRegex` branch.

- [x] common infrastructure (https://github.com/dotnet/roslyn/pull/25541)
- [x] Regex parser (https://github.com/dotnet/roslyn/pull/23984)
- [x] common infrastructure for language service (https://github.com/dotnet/roslyn/pull/25985)
- [x] Language service (https://github.com/dotnet/roslyn/pull/25517)
- [x] Tests (https://github.com/dotnet/roslyn/pull/25520)
- [x] Additional validation before merging

Do we want to offer completion?

**Comment by CyrusNajmabadi** [comment]
The only remaining thing is "completion" which is in another branch.  But we can get to that later.

**Comment by jcouv** [comment]
No, this umbrella issue can be closed now. Thanks
