### ISSUE TITLE
Optimize Semantic tagger more

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#25943]
@dpough suggested we should only raise tag change event (re-classify) for the new/reformatted lines.

we shouldn't need to raise tag changed event for all visible lines.

he can add more detail.

**Comment by heejaechang** [comment]
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Classification/SemanticClassificationViewTaggerProvider.cs,30f1647af2ee88f3

**Comment by CyrusNajmabadi** [comment]
> @dpough suggested we should only raise tag change event (re-classify) for the new/reformatted lines.

Can you guys clarify this?  The way async tagging works is that we only raise tags changed for what has actually changed.  If the tags have changed, but we don't send those events (because they weren't in the "new/reformatted lines"), then what experience would the user get?

**Comment by CyrusNajmabadi** [comment]
Closing out.  This already uses the tagging difference system to only report the minimal set of changed classificatoins.
