### ISSUE TITLE
EditorConfig: code isn't formatted if csharp_preserve_single_line_blocks option equals to true

### ISSUE THREAD

**Issue by v-margko** [dotnet/roslyn#25957]
**Version Used**: Microsoft Visual Studio Enterprise 2017 Int Preview Version 15.7.0 Preview 3.0 [27603.0.d15.7]

**Prerequisites**:

- create new C# project (I created .NET Core Class Library)
- add class to project which contains two code blocks:

```csharp
public int Foo { get; set; }

public int MyProperty
{
	get; set;
}
```

**Steps to Reproduce**:

1. Add .editorconfig file to project:
```ini
[*.cs]
csharp_preserve_single_line_blocks = true
```
2. Save changes and close all opened files
3. Open *.cs file with class created above
4. Format document

**Expected Behavior**:
"MyProperty" code block should be on the single line
**Actual Behavior**:
 Nothing has changed
**Note**:
Works as expected if option equals to false. The same issue with csharp_preserve_single_line_statements option.

[Repro Gif](https://microsoft-my.sharepoint.com/:i:/p/v-margko/EQtHd23onAtGhs8puMWFXWkBIqsdEJ_6CQ8NGGx_Nlncag?e=QiXlkR)

**Comment by sharwell** [comment]
Tentatively marking this a **By Design**, but I will take this to a team design review and update the issue based on the meeting outcome.

**Comment by sharwell** [comment]
We confirmed in a design meeting that the current behavior is the intended behavior. The option is "preserve" single-line blocks as opposed to "prefer" single-line blocks. There is no formatting option currently that attempts to force code onto a single line. However, the analyzer infrastructure is certainly capable of covering these cases so if this is a code style you rely on it would be an available option. 😄
