### ISSUE TITLE
IDE0032 "Use Auto Property" breaking VB code with initial value

### ISSUE THREAD

**Issue by shibayan** [dotnet/roslyn#25952]
**Version Used**: 

VS 15.6.5

**Steps to Reproduce**:

1. 

```vb
Public Class Class1

    Private _testProperty As String = "initial value"

    Public Property TestProperty() As String
        Get
            Return _testProperty
        End Get
        Set
            _testProperty = Value
        End Set
    End Property

End Class
```

2. IDE0032 Quick Action

```vb
Public Class Class1

    Public Property TestProperty() As String
= "initial value"

End Class
```

**Expected Behavior**:

```vb
Public Class Class1

    Public Property TestProperty() As String = "initial value"

End Class
```

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/1356444/38356017-8689722a-38f9-11e8-9e5e-35ea4fca52e0.png)

**Comment by davkean** [comment]
Duping this against https://github.com/dotnet/roslyn/issues/26256 which is in 15.8 milestone whereas this is in Unknown.
