### ISSUE TITLE
Exception from quickinfo when hovering over an unnecessary cast

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#25966]
**Version Used**: 
Version 15.7.0 Preview 3.0 [27604.0.d15.7]

**Steps to Reproduce**:

```VB
Imports System

Module Program
    Sub Main(args As String())
        Dim i As Integer = 42
        Console.WriteLine(CInt(i))
    End Sub
End Module
```

Hover over `CInt`

**Expected Behavior**:
No error message, and quickinfo

**Actual Behavior**:
An "extension failed" dialog, and quickinfo flickering like crazy.

**Comment by jasonmalinowski** [comment]
Can confirm I can reproduce this.

**Comment by gundermanc** [comment]
Looking

**Comment by gundermanc** [comment]
Not an IDE bug, whomever is creating QuickInfoDisplayDeferredContent is passing null for the captures text, resulting in a null reference exception in the presenter when the deferred content is rendered to UI.

**Comment by zaytsev-victor** [comment]
@CyrusNajmabadi do you have any idea why the following test passed https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/VisualBasicTest/QuickInfo/SemanticQuickInfoSourceTests.vb#L1177-L1182?

**Comment by CyrusNajmabadi** [comment]
@zaytsev-victor I have no context here.  However, my guess would be that that those tests are just validating things at the Roslyn-quick-info-data-layer.  And, **perhaps** (again, i'm just guessing), it's at a higher layer where these get translated to editor-entities that things crash.  You'd have to debug though to see for sure.

**Comment by CyrusNajmabadi** [comment]
I get no exception.  Quickinfo works fine:

![image](https://user-images.githubusercontent.com/4564579/217940495-3d4041b7-1639-460b-af12-924a63ff1f74.png)
