### ISSUE TITLE
xunit produced no error output but had exit code -2146233082, and there is no dump file

### ISSUE THREAD

**Issue by JieCarolHu** [dotnet/roslyn#25961]
The following error happened in official build. Will update this issue if the same test fails again.

xunit produced no error output but had exit code -2146233082, and there is no dump file

https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x/job/windows_release_unit64/236/

https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x/job/windows_release_unit32/235/

**Comment by jasonmalinowski** [comment]
@sharwell Assigning this to you since you've been driving the conversation. If you get overloaded and we need to redistribute, let me know.

**Comment by Shyam-Gupta** [comment]
Similar issue but with a different error code: 
xunit produced no error output but had exit code -2146232797

https://ci.dot.net/job/dotnet_roslyn/job/features_editorconfig-in-compiler/job/windows_release_unit64_prtest/103/consoleFull#8269377096baeffce-8504-4013-981e-7f26b5265816

**Comment by sharwell** [comment]
Duplicate of #12106
