### ISSUE TITLE
"Find All References" navigates to source locations on every click

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25969]
The &quot;Find All References&quot; dock seems to navigate to source locations on every click, even clicks on the triangle symbol in front of each node. It feels wrong to change the purple preview tab to another file even if one is merely expanding or collapsing a node.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/187527/find-all-references-navigates-to-source-locations.html
VSTS ticketId: 556566_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎2‎/‎5‎/‎2018, 08:23 PM (58 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
> It feels wrong to change the purple preview tab to another file even if one is merely expanding or collapsing a node.

⬆️ This is the key insight for this bug.

**Comment by CyrusNajmabadi** [comment]
I dont' repro this at all.  Clicking on the triangles does not navigate me.  It jsut expands/collapses the child list.
