### ISSUE TITLE
"Place 'System' directives first when sorting usings" option reset after upgrade

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25971]
I believe I checked &quot;Place 'System' directives first when sorting usings&quot; in the C# Advanced Options dialog. But I had to go check it again after upgrading VS.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/191690/place-system-directives-first-when-sorting-usings.html
VSTS ticketId: 560508_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎2‎/‎4‎/‎2018, 10:34 PM (59 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out.  Haven't heard other reports on this.  THere were many platform options bugs in the past.  They coud have easily caused this.
