### ISSUE TITLE
vb.net array length is 1 after call to c dll call used by byref variable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25979]
using array after being used by a c DLL call used with byref, it sets array.length to 1 where byref transfer length is correct 2 i C dll.

Using VS 2017 Com 15.6.4

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/222450/vbnet-array-length-is-1-after-call-to-c-dll-call-u.html
VSTS ticketId: 589380_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎4‎/‎1‎/‎2018, 03:13 PM (4 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
Here is an image showing the original issue:

![image](https://user-images.githubusercontent.com/1408396/38399701-85a7c90c-3911-11e8-9ea6-de703d4ee848.png)

**Comment by CyrusNajmabadi** [comment]
This is not an IDE issue.  Perhaps compielr or runtime.  Closing out as no one else has reported this and it def doesn't relate to roslyn-ide team.
