### ISSUE TITLE
C# alias intellisense trouble

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25978]
In .Net 4.5.2 project i use old System.Threading and System.Reactive libraries for Framework 3.5. I use Aliases property for this reference and change it from &quot;global&quot; to &quot;global, rx&quot;. The project compile fine, but intellisense shows me errors with some code like that:

```
a.ChangedEvents.Subscribe(q => renderProjectionItem.FastUpdateRequest()));
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/215836/c-alias-intellisense-trouble.html
VSTS ticketId: 583809_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎3‎/‎19‎/‎2018, 03:49 AM (17 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I'm not able to repro this.
