### ISSUE TITLE
global namespace imports with alias in VB

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25977]
In project properties we use aliases in imported namespaces as explained in https://docs.microsoft.com/en-us/visualstudio/ide/reference/references-page-project-designer-visual-basic

Since the last VS version the code editor marks this aliases as errors but still compiles the project, see screenshots.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/214141/global-namespace-imports-with-alias-in-vb.html
VSTS ticketId: 581534_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎3‎/‎15‎/‎2018, 04:00 AM (21 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
Image from the original report:

![image](https://user-images.githubusercontent.com/1408396/38399371-ad4d0302-390f-11e8-9d81-180a152648a1.png)

**Comment by VaporiZed** [comment]
In VS2019(Pre) the problem can be solved by using (white)spaces between the left and the right part.
So instead of importing "sc=System.ComponentModel" write "sc = System.ComponentModel". That worked for me. In our community we also saw, that "sc=System.ComponentModel" makes sc irrelevant at all. It's like importing "System.ComponentModel" without the "sc"-alias.

**Comment by wizzardmr42** [comment]
This is very annoying as in VS2017 it gives errors if the aliases do have spaces

**Comment by VaporiZed** [comment]
Hm. In VS2017 (Ver. 15.9.11) I have neither problems with whitespaces nor without, as you can see in my attachment.
![Namespaces](https://user-images.githubusercontent.com/49878115/56923323-8fcc9c00-6aca-11e9-8a54-9c65fd479b3b.png)

**Comment by wizzardmr42** [comment]
oh, it might only be a problem in earlier versions

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't gotten any reports on this in 5 years.
