### ISSUE TITLE
VB use auto property

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25972]
When the IDE suggests using an auto property for a class variable that has a default value, the refactored code adds the value assignment on the following line resulting in an error.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/192529/vb-use-auto-property.html
VSTS ticketId: 561198_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎3‎/‎18‎/‎2018, 10:12 PM (17 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
Sample code:

```vb
Private m_data As UInteger = 5

Public Property Data As UInteger

  Get
    Return m_data
  End Get

  Set(ByVal value As UInteger)
    m_data = value
  End Set

EndProperty
```

Gets converted to:

```vb
Public Property Data As UInteger
= 5
```

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/29686
