### ISSUE TITLE
Download in PDF link doesn't work

### ISSUE THREAD

**Issue by mstechies** [dotnet/roslyn#25989]
**Version Used**: 

**Steps to Reproduce**:

1. Open https://github.com/dotnet/roslyn/wiki/Roslyn%20Overview
2. Select Download in PDF link

**Expected Behavior**:
PDF should be generated and downloaded for the Roslyn documentation

**Actual Behavior**:
This link opens up https://archive.codeplex.com/

**Comment by jinujoseph** [comment]
cc @tannergooding

**Comment by tannergooding** [comment]
CC. @kuhlenh

**Comment by svick** [comment]
I think that page should be redirected to docs.MS instead, see https://github.com/dotnet/roslyn/issues/25744.

**Comment by InRedikaWB** [comment]
Bug stil exists. Is this correct link [https://docs.microsoft.com/en-us/dotnet/opbuildpdf/csharp/roslyn-sdk/toc.pdf?branch=live]? It's link from https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/compiler-api-model

**Comment by JoeRobich** [comment]
The link has been updated to match the link provided on docs.microsoft.com. Thanks
