### ISSUE TITLE
C# code style "prefer 'this.' qualifier" on methods not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25981]
In code style preferences, I want to specify that all methods should be prefixed with the this qualifier in C# files. It doesn't seem to work for methods (as opposed to fields and properties).

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/225029/c-code-style-prefer-this-qualifier-on-methods-not.html
VSTS ticketId: 591906_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎4‎/‎2‎/‎2018, 02:57 AM (3 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
Here is a screenshot from the original issue:

![image](https://user-images.githubusercontent.com/1408396/38400036-ab9b7d50-3913-11e8-81a6-cbe5b6f0ed6e.png)

**Comment by zaytsev-victor** [comment]
https://github.com/dotnet/roslyn/issues/7584
It seems that it isn't implemented.
