### ISSUE TITLE
"Introduce Local" isn't available when the beginning of the selection contains a line break

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#25990]
**Version Used**: 
15.6.4

**Steps to Reproduce**:
```cs
private void foo()
{
    var bar =
        5 * 2
    ;
}
```

Select the whitespace after the equals character (the line break) up until the '2' and open the Quick Actions.

**Expected Behavior**:
The Quick Actions should include "Introduce Local" in addition to "Extract Method". The whitespace in the selection shouldn't make a difference.

**Actual Behavior**:
The Quick Actions only include "Extract Method"

**Notes**
If the leading line break isn't part of the selection (just the space characters and `5 * 2`), "Introduce Local" is available.

![introduce-local-whitespace](https://user-images.githubusercontent.com/1947968/38410142-250ab1ae-3984-11e8-9dfb-81798faf6ffc.gif)

**Comment by CyrusNajmabadi** [comment]
Nope.  This is not intentional.

**Comment by jcouv** [comment]
The problem seems to come from `GetExpressionUnderSpan`. It finds `=` as the `startToken` and `2` as the `stopToken` and that doesn't delineate an expression...
I'm taking a stab at fixing (private branch `extract-local2`).

**Comment by CyrusNajmabadi** [comment]
@jcouv Makes sense. 

Note: it might be good if we could extract this out into a common place so that anyone else who needs to do find-the-appropriate-node(s)-based-on-a-selection, has a well vetted place to start from.
