### ISSUE TITLE
When keyword recommender failure with constant named `var`

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#25999]
Some tests are skipped in the branch `features/recursive-patterns` because the compiler treats `var` as a keyword in pattern contexts. It is not clear if that is intentional.

Here is an example from `WhenKeywordRecommenderTests.cs`:

``` c#
        [Fact(Skip = "https://github.com/dotnet/roslyn/issues/25999"), Trait(Traits.Feature, Traits.Features.KeywordRecommending)]
        public async Task TestForSwitchCase_SemanticCheck_AfterClassAndLocalConstantVar_BeforeBreak() =>
    await VerifyKeywordAsync(@"
class var { }
class C
{
    void M() { const object var = null; switch (new object()) { case var $$ break; } }
}");
```

**Comment by gafter** [comment]
@CyrusNajmabadi Agreed, that's what #26000 says.

**Comment by CyrusNajmabadi** [comment]
SGTM.  Once we get a decision there, we can then decide if/how the feature (and its tests) should be updated.

**Comment by Neme12** [comment]
The issue might be better illustrated with just a constant var, this particular test is unnecessarily complicated.
> It looks like 'var' was previous treated as a type here due to 'class var' being in scope

In this case it would be a constant, that's why `when` was offered at that point.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/26019
