### ISSUE TITLE
Compiler crash csc.exe

### ISSUE THREAD

**Issue by rvhelden** [dotnet/roslyn#25991]
The compiler crashes with an unknown hard error and with exit code -2146232797
When compiling the following class

   ```
public class CrashClass
{
    public async Task OnCrash()
    {
        var switchObject = new object();
        switch (switchObject)
        {
            case InvalidCastException _:
                switch (switchObject)
                {
                    case NullReferenceException exception:

                        await Task.CompletedTask;

                        var myexception = exception;
                        break;
                }
                break;
            case InvalidOperationException _:
                switch (switchObject)
                {
                    case NullReferenceException exception:

                        await Task.CompletedTask;

                        var myexception = exception;
                        break;
                }

                break;

        }
    }
}
```
This is the stacktrace I got

> Application: csc.exe
> Framework Version: v4.0.30319
> Description: The application requested process termination through System.Environment.FailFast(string message).
> Message: System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at System.Collections.Immutable.ImmutableArray`1.Builder.set_Item(Int32 index, T value)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.LocalScopeInfo.GetHoistedLocalScopes(ArrayBuilder`1 result)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.ScopeInfo.GetHoistedLocalScopes[TScopeInfo](ArrayBuilder`1 result, Builder scopes)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.LocalScopeInfo.GetHoistedLocalScopes(ArrayBuilder`1 result)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.ScopeInfo.GetHoistedLocalScopes[TScopeInfo](ArrayBuilder`1 result, Builder scopes)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.LocalScopeInfo.GetHoistedLocalScopes(ArrayBuilder`1 result)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.ScopeInfo.GetHoistedLocalScopes[TScopeInfo](ArrayBuilder`1 result, Builder scopes)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.LocalScopeInfo.GetHoistedLocalScopes(ArrayBuilder`1 result)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.ScopeInfo.GetHoistedLocalScopes[TScopeInfo](ArrayBuilder`1 result, Builder scopes)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.ScopeInfo.GetHoistedLocalScopes[TScopeInfo](ArrayBuilder`1 result, Builder scopes)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.LocalScopeInfo.GetHoistedLocalScopes(ArrayBuilder`1 result)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.ScopeInfo.GetHoistedLocalScopes[TScopeInfo](ArrayBuilder`1 result, Builder scopes)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.LocalScopeInfo.GetHoistedLocalScopes(ArrayBuilder`1 result)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.ScopeInfo.GetHoistedLocalScopes[TScopeInfo](ArrayBuilder`1 result, Builder scopes)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.LocalScopeInfo.GetHoistedLocalScopes(ArrayBuilder`1 result)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.LocalScopeManager.GetHoistedLocalScopes()
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol method, Int32 methodOrdinal, BoundStatement block, ImmutableArray`1 lambdaDebugInfo, ImmutableArray`1 closureDebugInfo, StateMachineTypeSymbol stateMachineTypeOpt, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, DebugDocumentProvider debugDocumentProvider, ImportChain importChainOpt, Boolean emittingPdb, Boolean emitTestCoverageData, ImmutableArray`1 dynamicAnalysisSpans)
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods(TypeCompilationState compilationState)
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0()
> Stack:
>    at System.Environment.FailFast(System.String, System.Exception)
>    at Microsoft.CodeAnalysis.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
>    at Microsoft.CodeAnalysis.FatalError.ReportUnlessCanceled(System.Exception)
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0()
>    at System.Collections.Immutable.ImmutableArray`1+Builder[[Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope, Microsoft.CodeAnalysis, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].set_Item(Int32, Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+LocalScopeInfo.GetHoistedLocalScopes(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope>)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+ScopeInfo.GetHoistedLocalScopes[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope>, Builder<System.__Canon>)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+LocalScopeInfo.GetHoistedLocalScopes(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope>)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+ScopeInfo.GetHoistedLocalScopes[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope>, Builder<System.__Canon>)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+LocalScopeInfo.GetHoistedLocalScopes(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope>)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+ScopeInfo.GetHoistedLocalScopes[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope>, Builder<System.__Canon>)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+LocalScopeInfo.GetHoistedLocalScopes(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope>)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+ScopeInfo.GetHoistedLocalScopes[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope>, Builder<System.__Canon>)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+ScopeInfo.GetHoistedLocalScopes[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope>, Builder<System.__Canon>)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+LocalScopeInfo.GetHoistedLocalScopes(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope>)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+ScopeInfo.GetHoistedLocalScopes[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope>, Builder<System.__Canon>)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+LocalScopeInfo.GetHoistedLocalScopes(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope>)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+ScopeInfo.GetHoistedLocalScopes[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope>, Builder<System.__Canon>)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+LocalScopeInfo.GetHoistedLocalScopes(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Debugging.StateMachineHoistedLocalScope>)
>    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+LocalScopeManager.GetHoistedLocalScopes()
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody(Microsoft.CodeAnalysis.CSharp.Emit.PEModuleBuilder, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, Microsoft.CodeAnalysis.CSharp.BoundStatement, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CodeGen.LambdaDebugInfo>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CodeGen.ClosureDebugInfo>, Microsoft.CodeAnalysis.CSharp.StateMachineTypeSymbol, Microsoft.CodeAnalysis.CodeGen.VariableSlotAllocator, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.CodeGen.DebugDocumentProvider, Microsoft.CodeAnalysis.CSharp.ImportChain, Boolean, Boolean, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CodeGen.SourceSpan>)
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods(Microsoft.CodeAnalysis.CSharp.TypeCompilationState)
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol)
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0()
>    at Roslyn.Utilities.UICultureUtilities+<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
>    at System.Threading.Tasks.Task.Execute()
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
>    at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
> 

**Version Used**: 
Microsoft Visual Studio 2017 15.6.4 and 15.6.5

**Steps to Reproduce**:

1. Compile in Release mode

**Expected Behavior**:
Expected a successfully compiled program

**Actual Behavior**:
Crashes with an hard error and exitcode -2146232797

I have created a repository that is reproducing the issue here https://github.com/rvhelden/CompilerCrash

The history of this issue can be found here https://github.com/dotnet/roslyn/issues/25571

@svick found that after this commit https://github.com/dotnet/roslyn/pull/23930 in the master branch the compiler doesn't crash anymore but he suspects that the commit does not fixes the issue but only hides the error.

The compiler error can be reproduced with this [sharplab](https://sharplab.io/#v2:D4AQDABCCMDcCwAocVoFYGKSAzFATBAMIBOAhgM4AWRANpRUgN5JR4gAcUAbBAPIA7UpSoAKAJSsWiCLNkA3MiQgUA7gEsALgGMqfAEYArAKbbNEALwQBx1RAD2R05omY5stVt0RRnnXqczSRl3aXdw7UpjCABJAUVadQATIkpNAFEAD21jAAdNdXsBCAB9AC5WcKqVDX8fP10DEyDK6tDWtqrIimiAOQBXWloAJWMAM2MSYwEcrJz8wuLjbLyCooqsEM7tkABOHgA6InsAW1zaY01jJJBuTA7t6sVlE4BPZfm14qsP1cW3R6dfRTMgAawBjwAvg82sDjGCIV0orF4mREkk+LlJmQvnM/kVShtATUvFR6rVGoFNMFiWFiXJun1BiNxpNprMVgsCb8uQINjD6VB9rcjqdzpdrrd7ltBXJnhA3jyvpYIEr/gL6XCERrwtDNsSteCkA89RA9ZCgA===)

But it doesn't occure with this [sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGA3AWACh0tsBWAwolAZiwCYMBhBaACyYBtooiBvIljooAHFgBsGAPIA7FuwAUASkEDCGDRoBuEBBigB3AJYwAxmynAAVnFMwMAXgwy4BjAHtrtmMsqaNhibmGAqBZhZedirq/mr+8abQcBgAkjI6nEYAJkzQMACiAB6mcAAOMEbuMhgA+iCC8Y36xuEhYeaWNlENTbE9vY2JUMkAcgCunJwASnAAZohwMiVFJeWV1XDFZRVV9VQxA4coAJwSAHRM7mClnHDwWSjilP2HTTp6YACem6s71U4/bbrPyvAbABBwCAAaxBrwAvi9euDITDEZohsk0hlslJSogIH8VkCqrU9qDmkE2G0Wh1IjBouS4uT0UkMONJjN5hClnAiWsSYD+TI9mjmSdzpdrrd7o9ngdmf53hgvoK/o4MKrgaLycjobDDgj9jqIXqiC9DRhDXCgA=) which is the master branch

**Comment by jcouv** [comment]
Tagging @gafter
