### ISSUE TITLE
Consider moving FxCop analyzers to their own repository

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#2599]
I'm concerned that the inclusion of FxCop rules in this repository will impair their ongoing release cycle after Roslyn 1.0 stable is shipped. I'm also concerned that their inclusion here limits community contributions towards the implementation of these rules. I believe it would be beneficial to this portion of the project if it were developed in a separate repository (or perhaps split into a few repositories according to the target APIs analyzed by various rules, but that is a different discussion).

We've had remarkable success with planning and implementing StyleCop rules in the community, primarily because the project has its own repository where it's easy to track and discuss progress. I would love to see a similar situation for FxCop. :+1:

**Comment by srivatsn** [comment]
Yes I agree we should start moving them once 1.0 ships. We've been factoring the rules into analyzers that are about particular BCL apis and my preference would be for these rules to live next to the sources for those libraries in the corefx repo. For the rules that are not about particular APIs, those could be in a separate repo.

**Comment by srivatsn** [comment]
The FxCop analyzers are in the roslyn-analyzers repo now and will likely live elsewhere factored based on APIs but this repo is no longer the right place for this issue.
