### ISSUE TITLE
Use pattern matching IDE0019 issue

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#25993]
Ported from https://github.com/dotnet/roslyn-analyzers/issues/1660

@PhilPJL reported:

---------------------------------------

#### Version

Microsoft Code Analysis 2017, version [2.6.0.6241393]

#### Repro steps

```
            var fe = e as FaultException<ValidationFault>;
            var ae = e as FaultException<AuthorizationFault>;
            if (fe != null)
            {
                ShowExceptionErrorMessage(fe);
            }
            else if (ae != null)
            {
                ShowExceptionErrorMessage(ae);
            }
            else
            {
```

#### Expected behavior

Both fe and ae should be suggested to use pattern matching.

#### Actual behavior

Only fe is suggested.

However both are suggested if there's no 'else'.

```
            var fe = e as FaultException<ValidationFault>;
            var ae = e as FaultException<AuthorizationFault>;
            if (fe != null)
            {
                ShowExceptionErrorMessage(fe);
            }
            if (ae != null)
            {
                ShowExceptionErrorMessage(ae);
            }
            else
            {
```

**Comment by alrz** [comment]
The problem is that we look for a parent block for the `if` statement for various analyses. We should adjust all of those considering that there is no parent block.
