### ISSUE TITLE
Deleting/renaming a ruleset in SolnExplorer should automatically update ProjectProperties

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#260]
Ported from TFS WorkItem: <b>1115014</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P>1. Open a project with an analyzer and ruleset</P>
<P>2. Delete the ruleset file in SolnExplorer</P>
<P>&nbsp;</P>
<P>What I expect: Build window shouldn't show any warnings about "missing ruleset file". And Analyzers&gt;EditRuleSet should succeed.</P>
<P>&nbsp;</P>
<P>WHAT I GET: a warning about missing ruleset file. And Analyzers&gt;EditRuleSet fails with a message about missing ruleset.</P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By Lucian Wischik (1/26/2015 3:20:38 PM)

<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><i><font color="#000000" size=3 face=Calibri>I would love for &quot;delete ruleset in SolutionExplorer&quot; to be the intended supported way to rename/remove a ruleset, since that's how I use SolnExplorer the rest of the time. I don't want there to be additional hidden settings that I need to tweak.</font></i></p>
<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><em><font color="#000000" size=3 face=Calibri></font></em>&nbsp;</p>
<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><font face=Calibri><font size=3><font color="#000000">The current approach (where you have to go to Project Properties &gt; CodeAnalysis &gt; ruleset) isn't very discoverable.</font></font></font></p>

------------------------------

2) Edited By Lucian Wischik (1/26/2015 3:22:22 PM)

<p>Shyam had filed related bug 1082443 about a variety of ruleset issues. Tom writes:</p>
<p>&nbsp;</p>
<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><span style="COLOR:#1f497d;"><font size=3><font face=Calibri>I think we ended up fixing the issues we knew how to fix at the time, and took a wait-and-see approach to the others.</font></font></span></p>
<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><span style="COLOR:#1f497d;"><font size=3 face=Calibri>&nbsp;</font></span></p>
<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><span style="COLOR:#1f497d;"><font size=3><font face=Calibri>We need to do something better here. I think we can update the project system code to watch for deletes of .ruleset files and simply delete any CodeAnalysisRuleSet properties that refer to the same path. We might be able to handle renames that way, too.</font></font></span></p>
<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><span style="COLOR:#1f497d;"><font size=3 face=Calibri>&nbsp;</font></span></p>
<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><span style="COLOR:#1f497d;"><font size=3 face=Calibri>I hate having to muck around in the project system code, but it’s very silly that we’ve gone to a lot of effort to <i>add</i> the .ruleset file to your project for you and then blow up the moment you delete it.</font></span></p>

------------------------------

**Comment by tmeschter** [comment]
Per previous discussion, moving to @jmarolf for verification.
