### ISSUE TITLE
[Ubuntu tests] build.sh: Permission denied

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#26001]
I get consistent failures in Ubuntu tests on the features/recursive-patterns branch, with messages like this in https://ci.dot.net/job/dotnet_roslyn/job/features_recursive-patterns/job/ubuntu_16_mono_debug_prtest/85/consoleFull

``` none
12:28:10     Merge bcaa4ffa89d0231c486890f75bab356bf989f4df into 8de96ab87ecd16046b24eb65a5ca6973369abbba
12:28:10 ./build/scripts/cibuild.sh: line 27: /mnt/j/workspace/dotnet_roslyn/features_recursive-patterns/ubuntu_16_mono_debug_prtest/build.sh: Permission denied
```

**Comment by sharwell** [comment]
@gafter The executable bit was removed in commit 703c47f83994fb69c161fbbb09ed62424b0e5faf (it was present in both branches leading to this merge, so it was broken during the merge itself). You can restore it by executing the following command:

```
git update-index --chmod=+x build.sh
```

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/26368
