### ISSUE TITLE
VB Keyword recommenders: Protected not suggested after Private regardlesss of langversion

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#26002]
**Steps to Reproduce**:

1. Set language version to 15.5
2. Type:
```VB
Private $$
```

**Expected Behavior**:
`Protected` to be in the completion list.

**Actual Behavior**:
It isn't.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of customer feedback.
