### ISSUE TITLE
SyntaxGenerator ToFullString() not producing legal code.

### ISSUE THREAD

**Issue by bryanar** [dotnet/roslyn#26005]
**Version Used**: 
Microsoft.CodeAnalysis Nuget 2.7.0.

**Steps to Reproduce**:

            var workspace = new AdhocWorkspace();
            var generator = SyntaxGenerator.GetGenerator(workspace, LanguageNames.CSharp);

            var unit = generator.CompilationUnit(generator.NamespaceImportDeclaration("System"),
                generator.ClassDeclaration("TestClass",
                members: new[]
                {
                    generator.FieldDeclaration("Name", generator.TypeExpression(SpecialType.System_String)),
                    generator.MethodDeclaration("Main", null, modifiers: DeclarationModifiers.Static)
                }));

**Expected Behavior**:
Legitimate Code.

**Actual Behavior**:
`usingSystem;classTestClass{stringName;staticvoidMain(){}}
`
I think that my actual issue is with the ToFullString() method, but I haven't checked the source to confirm. A pretty-print of the source would be nice, but I'd settle for something that simply doesn't break intellisense + can be compiled.

**Comment by jmarolf** [comment]
@bryanar You'll want to call `NormalizeWhitespace`. if you are generating code outside of a codefix.  By default generated code has placeholder nodes for whitespace so the formatter can replace them with whatever the users settings are.

**Comment by bryanar** [comment]
Ah, thank you.
