### ISSUE TITLE
Find/GoToAll/FAR: Ability to filter by code vs. test project

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26004]
I don't know if the IDE can tell which projects are product code vs. test code, but it would be useful to be able to search symbols only in product code (tests symbols are very numerous and add a lot of noise).

Tagging @kuhlenh for consideration. I'm not sure if such feature would be in IDE or Editor layer. If IDE, let me know, I could take a look.

**Comment by BhaaLseN** [comment]
Seconded for "Find" (text) and "Find all references".

Although, we have clean class library projects for NUnit tests, and they don't have any special Guids or anything in the csproj (infact, one of our devs has the problem that his VS insists on adding them, which reportedly has been fixed for 15.7), so I have no idea if/how VS would be able to detect that.

**Comment by CyrusNajmabadi** [comment]
So find-refs already has a way to filter out the projects you want or do not want:

![image](https://user-images.githubusercontent.com/4564579/76153036-57e39d00-607b-11ea-8338-da39a71e520e.png)

Closing out for now.
