### ISSUE TITLE
Assertion failure in PreciseAbstractFlowPass: "last comes before first"

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#26028]
1. Checkout master & run a debug build of VisualStudioSetup
2. Paste the following code & put cursor after 'x':
```c#
class C
{
    void M()
    {
        foreach (var x
    }
}
```

This is what I get:
![image](https://user-images.githubusercontent.com/11444821/38473592-b270d7c0-3b92-11e8-9c2f-7431cddfb886.png)

**Comment by CyrusNajmabadi** [comment]
Is this a bug in dataflow?  Or just in ForEachToFor?   Tagging @heejaechang and @gafter

**Comment by tamlin-mike** [comment]
Seems to me `PreciseAbstractFlowPass` is either underdocumented or wrong, or at least dangerous.

See the section https://github.com/dotnet/roslyn/blob/9b8aa38370fe6ad4afa10add7fa5a5bac22a9355/src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs#L171-L180

What if that span is only a single BoundNode, which seems likely this is the exact problem OP reported? Also, the assert text is obviously wrong; in case first and last are the same, `length` is zero, and the assert text becomes invalid. The assert text suggests the check should be `>=`, not `>`.

**Comment by jcouv** [comment]
@gafter Would you mind taking a look? Thanks
