### ISSUE TITLE
Refactoring: Create type from anonymous object creation

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#26020]
```cs
var q = from item in data
        select new { item.Name };
```

->
```cs
class NewType 
{
    public string Name { get; set; }
}
```
```cs
var q = from item in data
        select new NewType { Name = item.Name };
```
could work for tuples as well.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/28066 (and several other feature additions in this space).

**Comment by CyrusNajmabadi** [comment]
![image](https://user-images.githubusercontent.com/4564579/76153020-210d8700-607b-11ea-9b55-9b259366fe0f.png)
