### ISSUE TITLE
Code fix actions missing leads to integration test failure

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#26038]
Example:

https://ci.dot.net/job/dotnet_roslyn/job/dev15.7.x/job/windows_release_vs-integration_prtest/354/

**CSharpCodeActions.GenerateMethodInClosedFile-EqualException-17.09.22.log**:

```
Xunit.Sdk.EqualException: Assert.Equal() Failure
              â†“ (pos 2)
Expected: \r\nusing System;\r\n\r\npublic class Foo\r\n{\r\n   Â·Â·Â·
Actual:   \r\npublic class Foo\r\n{\r\n}\r\n
              â†‘ (pos 2)
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences).GetType().Name
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences)
```

This appears to be caused by the presentation of a code fix with no actions in the light bulb (this test is supposed to have a non-empty preview at this point):

![image](https://user-images.githubusercontent.com/1408396/38522929-ad7f8a40-3c0f-11e8-92a5-cb59e27adfbb.png)

**Comment by jasonmalinowski** [comment]
@heejaechang This looks like an actual product bug. Do we know what's up here?

**Comment by tmat** [comment]
Another hit: https://dev.azure.com/dnceng/public/_build/results?buildId=1404309&view=ms.vss-test-web.build-test-results-tab&runId=40763204&resultId=100274&paneView=debug

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't seen issues here and this test isn't disabled.
