### ISSUE TITLE
Utilise Mutli-Line Strings in VB Unit Tests (IncrementalParser)

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#26046]
* Mainly focused in using String Literals over XML Literals,
** Refactor out (if possible helper methods from above changes).
** Minimise the size the strings (where viable).
** Clean up code.  
Planning to go through the folders with each project, as to minimise pull-request size.
As part of the work discussed in #17124. 

#26040 (Incremental Parser) *which is currently closed*

**Comment by AdamSpeight2008** [comment]
@jaredpar  Reconsider reopening this as it about potential perf improvements of the test code.
Running just the 99 Unit Test in `IncrementalParser` and reading the reported run time from the testrunners.
```
	       CodeRush	TestRunner (Parallel)
Using Strings: 5.52	07.9465125 08.087527  sec
Using XML    : 6.02	13.3898614 08.806287  sec
```

**Comment by gafter** [comment]
We don't care.
