### ISSUE TITLE
[VB] #If. Then. .. #Else.. #End If don't work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#26053]
#If DEBUG Then
    &lt;WebMethod()&gt;
#Else
    &lt;WebMethod(CacheDuration:=86400)&gt;
#End If

Signals a BC30012 (missing #End If)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/179853/vb-ifthenelseend-if-dont-work.html
VSTS ticketId: 549666_
_These are the original issue comments:_

Jinu Joseph [MSFT] on 1/14/2018, 03:53 PM (84 days ago): <p>Thank you for your feedback! </p><p>Tried with simple example </p><p><br></p><p>Dim x As Double</p><p><br></p><p>#If DEBUG Then</p><p>    x = 1</p><p>#Else</p><p>    x= 0</p><p>#End If</p><p><br></p><p>Could it be possible that your attribute selection is not compiling.</p><p><br></p><p>We look forward to hearing from you!</p>

Lino Barreca on 1/15/2018, 00:03 AM (84 days ago): <p>Try with this instead.</p><pre>#If DEBUG Then<br> &lt;WebMethod()&gt;<br>#Else<br> &lt;WebMethod(CacheDuration:=86400)&gt;<br>#End If
Public Function SomeFunction() As String
 Return "Ciao"
End Function </pre><p>Logic is pretty simple: If I'm compiling for debug I want to apply one attribute to the method, if I'm compiling for release I want to apply the other.</p><p>The problem is related to #if and method attributes. compiler syntax analyzer expects the line after the attribute to be the method definition and not the "#end if" keyword.</p><p>Proof of the above statement is that THIS one below compiles correctly but is very bad because I have to define the method twice even if it's the same.</p><pre>#If DEBUG Then
 &lt;WebMethod()&gt;
 Public Function SomeFunction() As String
#Else
 &lt;WebMethod(CacheDuration:=86400)&gt;
 Public Function SomeFunction() As String
#End If
 Return "Ciao"
End Function</pre>

_These are the original issue solutions:_
(no solutions)

**Comment by gafter** [comment]
Are you sure you do not have any extra empty lines?

**Comment by AlekseyTs** [comment]
```
CCIfGroup  ::=
                #  If  CCExpression  [  Then  ]  LineTerminator
                [  CCStatement+  ]
                [  CCElseIfGroup+  ]
                [  CCElseGroup  ]
                #  End  If  LineTerminator
```
```
CCStatement  ::=
                CCConstantDeclaration  |
                CCIfGroup  |
                LogicalLine
```
```
LogicalLine  ::=  [  LogicalLineElement+  ]  [  Comment  ]  LineTerminator
LogicalLineElement  ::=  WhiteSpace  |  LineContinuation  |  Token
```

From section **2.1.2 Line Continuation**:
Some places in the syntactic grammar allow for implicit line continuations. **When a line terminator is encountered:**
after a comma (,), open parenthesis ((), open curly brace ({), or open embedded expression (<%=)
after a member qualifier (. or .@ or ...), provided that something is being qualified (i.e. is not using an implicit With context)
before a close parenthesis ()), close curly brace (}), or close embedded expression (%>)
**after a less-than (<) in an attribute context
before a greater-than (>) in an attribute context**
after a greater-than (>) in a non-file-level attribute context
before and after query operators (Where, Order, Select, etc.)
after binary operators (+, -, /, *, etc.) in an expression context
after assignment operators (=, :=, +=, -=, etc.) in any context.
**the line terminator is treated as if it was a line continuation.**

Therefore, an attribute application used as part of a method declaration is not complete logical line.

**Comment by KathleenDollard** [comment]
I am updating the docs to clarify this point, adding:

 The statements within a conditional compilation block must be complete logical statements. For example, you cannot conditionally compile only the attributes of a function, but may conditionally declare the function:

#If DEBUG Then
<WebMethod()>
Public Function SomeFunction() As String
#Else
<WebMethod(CacheDuration:=86400)>
Public Function SomeFunction() As String
#End If

**Comment by paul1956** [comment]
This is really ugly and leads to errors, I would like if this could be fixed even if an explicit line continuation was required. Once 16.1 is released I would like to attempt to address at least for the explicit line continuation but I believe that was already rejected. It might help in the short term to include @KathleenDollard explanation (or a link) in the error message.

**Comment by KathleenDollard** [comment]
@paul1956 

I need some clarification here. Are you requesting a change to how #if works (probably breaking) or a specific error message that you'd like us to look at?

**Comment by paul1956** [comment]
Both, I will look into a prototype of #if using Explicit Line Continuation because I don't think it would be any more of a breaking change then comments after Explicit Line Continuation and if it is no lose to other resources. Until then (or forever) a much clearer error message is needed. Possibly just a new landing page when someone gets the error explaining what you posted https://github.com/dotnet/roslyn/issues/26053#issuecomment-380288474 above. The C# pattern above is used extensively in Open Source code and the VB solution of duplicating the Function Statement is extremely error prone. Below is typically what happens after a simple refactoring of the function and this is a trivial example.
```VB
#If True Then
    Private Function FindNextMatchingRow1(ByRef NumberReplaced As Integer) As DataGridViewRow
#Else
    Private Function FindNextMatchingRow(ByRef NumberReplaced As Integer) As DataGridViewRow
#End If
```

**Comment by KathleenDollard** [comment]
If we look at this too generally, there may be issues. If we look at the single question of attributes in #If, there might not be breaking changes. For example, I don't think we want to allow the #If anywhere in the declaration after the attribute.

**Comment by paul1956** [comment]
Completely agree, I want to allow just what is below and not even for every case I have seen some multi-part attributes used in tests that I don't understand well enough yet. I think they are attributes that have attributes as parameters and I don't want to split them (yet or ever).
```VB
#If DEBUG Then
    <WebMethod()>
#Else
    <WebMethod(CacheDuration:=86400)>
#End If
    Public Function SomeFunction() As String
```

**Comment by KathleenDollard** [comment]
I'm also wondering about weird attribute combinations. I don't know whether we could restrict it to all attributes or none, both technically and in providing the right functionality. What I mean is allowing

```vb
#If DEBUG Then
    <WebMethod()>
#Else
    <WebMethod(CacheDuration:=86400)>
#End If
    Public Function SomeFunction() As String
```

but not 

```vb
#If DEBUG Then
    <WebMethod()>
#Else
    <WebMethod(CacheDuration:=86400)>
#End If
    <Something>
    Public Function SomeFunction() As String
```

**Comment by paul1956** [comment]
The _ would be required after each attribuate (missing _ currently is the error you get when you try doing it), that said I have not seen real cases for the second example where <something> is part of a multipart attribute connected to  <WebMethod(CacheDuration:=86400)>. I am not sure if C# even supports, but right now I can't remember where I had seen that pattern except that it was part of a test.
