### ISSUE TITLE
Unable to retrieve whether assembly is C# assembly or C++/CLI assembly

### ISSUE THREAD

**Issue by msbasanth** [dotnet/roslyn#26059]
**Version Used**: 
Roslyn - v2.6.0
VS2017 15.6

**Steps to Reproduce**:

1. I have a C++/CLI assembly where I am exposing few APIs
2. I am referring the same from a C# assembly and analyzer the MemberAccessExpressionSyntax
3. I got IMethodSymbol by using semanticModel.GetSymbolInfo(memberAccessExpressionNode).Symbol

**Expected Behavior**:
The property methodSymbol.Language should show C# in the IMethod Symbol and also in the methodSymbol.ContainingAssembly.Language.

**Actual Behavior**:
In both methodSymbol and methodSymbol.ContainingAssembly Language property shows C# not C++/CLI.

I wanted to skip analyzing C++/CLI member access in my analyzer. How can I identify whether I am analyzing C# assembly or C++/CLI assembly?

Regards
Basanth

**Comment by jmarolf** [comment]
@msbasanth on the symbol locations you can check if they are defined in source: `symbol.Locations.All(l => !l.IsInSource)`

Methods defined in C++\CLI will come from metadata references as roslyn doesn't understand C++, therefore they won't have any source definitions.

**Comment by msbasanth** [comment]
In my case, the symbol is a member access to an assembly for which source may or may not be available.
i.e. if I am referring to a C# assembly for which source code is not available it will also come as metadata references.

In this case symbol.Locations.All(l => !l.IsInSource) will return false even for C# assembly right?

Thanks
Basanth

**Comment by jmarolf** [comment]
@msbasanth can you tell me your scenario? If you don't have the source for the symbol you are analyzing what is the difference between VB/C#/C++ or any other .NET language?

**Comment by msbasanth** [comment]
In my case, I am analyzing the API's exposed in C# assembly by analyzing MemberAccessExpression in C# code. Currently, I will be getting MemberAccessExpression & corresponding IMethodSymbol even for C++/CLI API's accessed in my C# source code (I am getting ISymbol from the metadata info as you mentioned). 

Here I want to differentiate the API call is to a C# assembly or a C++/CLI assembly as our analyzer only interested in the analysis if assembly in which API defined is C# one.

**Comment by jmarolf** [comment]
@msbasanth Ok but you don't care about the assembly names themselves? Or any part of the assembly identity? In what scenario is calling a method wrong if the assembly was written in C# but ok if it was written in C++?

To get back to the original issue `methodSymbol.ContainingAssembly.Language` will return the correct language if we have the original source to be able to determine that.  If we just have metadata there is no way  for us to know the original language and so we return the language that is currently being used.  Is you suggestion to have each compiler in the .NET ecosystem provide some metadata so we can determine which compiler originally produced the assembly?

**Comment by msbasanth** [comment]
@jmarolf  Analyzer won't get any insight on whether the assembly is C++/CLI from the assembly names or from the identity. 
**[jmarolf]**In what scenario is calling a method wrong if the assembly was written in C# but ok if it was written in C++?
It is not like calling an API written in C++ is ok, it is just that our internal policy doesn't want to analyze API's exposed by C++/CLI assembly.

**[jmarolf]**Is you suggestion to have each compiler in the .NET ecosystem provide some metadata so we can determine which compiler originally produced the assembly?
We can get to know whether an assembly is 'managed only' by checking PortableExecutableKinds.ILOnly,

```
                Assembly assembly = Assembly.ReflectionOnlyLoadFrom(assemblyFullPath);
                assembly.ManifestModule.GetPEKind(out PortableExecutableKinds portableExecutableKinds,
                    out ImageFileMachine imageFileMachine);
                bool isCSharpAssembly = portableExecutableKinds.HasFlag(PortableExecutableKinds.ILOnly);
```
It would have been great if we can get this information with out loading the assembly again from the file system path. maybe exposed as a property in methodSymbol.ContainingAssembly.

Thanks
Basanth

**Comment by jmarolf** [comment]
> We can get to know whether an assembly is 'managed only' by checking PortableExecutableKinds.ILOnly,

Seems reasonable.  I'm fine with this bug tracking that work.

**Comment by msbasanth** [comment]
Thanks @jmarolf

**Comment by msbasanth** [comment]
Closing as we have an alternative for checking whether an assembly is managed only.
