### ISSUE TITLE
Enum Generic Constraint with struct Constraint usage

### ISSUE THREAD

**Issue by fitdev** [dotnet/roslyn#26066]
**Version Used**: 
C# 7.3 Preview in VS 15.7 Preview 3

**Steps to Reproduce**:

Trying to use this new feature: [System.Enum, System.Delegate and unmanaged constraints.](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-preview-relnotes#csharp)

Consider this code for extension method:
   `public static T ToEnum<T>(this string enumString, T defaultOnFailure = default(T), bool ignoreCase = true) where T : Enum =>`
   `Enum.TryParse(enumString, ignoreCase, out T result) ? result : defaultOnFailure;`

**Expected Behavior**:
It should compile, because Enum is in effect a subset of ValueType.

**Actual Behavior**:
It does not compile: "CS0453	The type 'T' must be a non-nullable value type in order to use it as parameter 'TEnum' in the generic type or method 'Enum.TryParse<TEnum>(string, bool, out TEnum)'"

**Comment by jaredpar** [comment]
CC @OmarTawfik

**Comment by fitdev** [comment]
Thank you! That seems like an obvious fix. Although to me it is still rather strange that the Enum constraint actually includes the base class Enum which is not a value type, instead of including just the actual enums, which is what it would be used in 99% cases.

**Comment by rcollina** [comment]
@fitdev, strange indeed!

I’m also curious as to why they did not pick “enum” and “delegate” (keywords) as constraints. Must have missed that discussion.

**Comment by CyrusNajmabadi** [comment]
> I’m also curious as to why they did not pick “enum” and “delegate” (keywords) as constraints. Must have missed that discussion.

Adding "enum" and "delegate" would be adding a new feature (and can still be done in teh future).  What happened here was simply that the existing restrictions on using System.Enum or System.Delegate were removed and they simply picked up the same behavior as all other named types that you can use as constraints.

**Comment by CyrusNajmabadi** [comment]
> Thank you! That seems like an obvious fix. Although to me it is still rather strange that the Enum constraint actually includes the base class Enum

It's not the "enum constraint" really.  It's just a normal constraint on the .net type "System.Enum".  In other words, it's not special to the language/compiler.  When you add this constraint it's like adding a constraint of System.Whatever.  It's always meant "that class or subtypes", it's never meant "only subtypes".

**Comment by CyrusNajmabadi** [comment]
If you'd like an ```enum``` constraint that truly means "subtypes of System.Enum" i would recommend opening a bug over on csharplang asking for that :)

**Comment by rcollina** [comment]
@CyrusNajmabadi understood, thanks for your reply!

**Comment by OmarTawfik** [comment]
As others already commented, the features just removed the language restriction. The compiler always supported `T : Enum` being imported from other binaries, but just didn't allow it in source.

@rcollina several people suggested using `T : enum` and `T : delegate`. They also suggested being able to specify the underlying type of enum `T : enum(int)` or the delegate signature `T : delegate(???)`, but that would be a language change that requires many other details to be worked out.

@fitdev from comments, I understand the issue is now solved. Please re-open if you see otherwise.

**Comment by springy76** [comment]
Just installed 15.7.0 for just that single feature - and was just pissed within minutes. I'm sorry that I never before thought about System.Enum being some kind of  magic value+ref kind both at the same time.

My suggestion would be to make `where T: enum` a short form of `where T: struct, System.Enum`.

**Comment by CyrusNajmabadi** [comment]
@springy76 : https://github.com/dotnet/roslyn/issues/26066#issuecomment-380188341
