### ISSUE TITLE
Visual Studio 2017 Pro (15.6.5) System.NullReferenceException in bingdev

### ISSUE THREAD

**Issue by wstaelens** [dotnet/roslyn#26064]
see screenshot:

![bingdev](https://user-images.githubusercontent.com/7447285/38549859-50c79652-3cb5-11e8-915d-cfba2d771aa4.png)

**Comment by jcouv** [comment]
@wstaelens The code shown in the screenshot doesn't belong to Roslyn, so it's not clear what is the Roslyn issue here.
Can you describe repro steps, actual behavior and expected behavior? Thanks
