### ISSUE TITLE
[Feature request] Show operator result in Quick Info iff the operands are const values

### ISSUE THREAD

**Issue by Joe4evr** [dotnet/roslyn#26067]
This may be really minor, but I think it would be really neat if Quick Info could show the full expression and result of a const-folded operation when hovering over the operator. This would help around eg. unit-tests, where you use some const values so the test is predictable, but once a few of those values are used in various ways, you may want to have a quick glance at the result of an operation to see if that still lines up with what you expect.

Example 1:
```cs
void M()
{
    const int i = 5;
    const int j = 10;
    Console.WriteLine(i + j);
}
```
Hovering over the `+` would show "5 + 10 = 15" below the operator signature.

Example 2:
```cs
[Flags]
public enum Foo
{
    Bar = 1 << 3,
}
```
Hovering over the `<<` would show "1 << 3 = 8".

Visual mock:
![](https://i.imgur.com/doyd3cD.png)

**Comment by Neme12** [comment]
Seems reasonable.

**Comment by sharwell** [comment]
The design review summary was essentially this:

> This is a small but awesome feature. :shipit: 

We would be looking for it to handle operators of constant expressions. We did not discuss the behavior if the rendered expression or result would be "long", or the definition of "long", so we'd be interested in proposals on how to define and handle those situations.

**Comment by Neme12** [comment]
@sharwell The PR currently trims and adds 3 dots to each of the 3 expressions separately depending on whether they go beyond a certain character limit. Also, did you discuss whether this should be shown on all constant-value expressions? Potentially even identifiers of constants? It seems like the whole discussion from the PR was left out.

**Comment by Neme12** [comment]
Specifically: https://github.com/dotnet/roslyn/pull/30482#issuecomment-429537898

**Comment by Neme12** [comment]
You can see an example of the trimming here:
![quickinfoconstantvaluelongstr](https://user-images.githubusercontent.com/11444821/46892800-f2cc4d80-ce6e-11e8-89a8-caa9aa980b66.png)

**Comment by CyrusNajmabadi** [comment]
To me, that example shows to me why i would not want the full expr built up.  I would like to know the total constant value, but because of the trimming, i lose the information I am likely to care most about. If i need the lower values, i can just hover on those IMO.

**Comment by sharwell** [comment]
> It seems like the whole discussion from the PR was left out.

It was. We ran out of time while we were discussing this one so it got a high-level approval but we'd review the edge cases as they were presented. It sounds like the PR already covers those so if any concerns come up during a review we can revisit them specifically next design meeting.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
