### ISSUE TITLE
.NET Compiler Platform SDK extension broken in latest stable version of VS 2017

### ISSUE THREAD

**Issue by tiesmaster** [dotnet/roslyn#26094]
**Version Used**:  15.6.6

**Steps to Reproduce**:

1. Install latest VS 2017
2. Install .NET Compiler Platform SDK from the Marketplace
3. Start VS again

_I've tried to reproduce this issue on a clean machine, and it reproduces, so I'm sure this is not related to weird machine bahavior._

**Expected Behavior**:
Extension loads successfully.

**Actual Behavior**:
The extension gets disabled with the message that the extension is not compatible with VS Pro 15.0.27428.2037 (see attached screenshot below).

![screen shot 2018-04-11 at 13 22 58](https://user-images.githubusercontent.com/460904/38613903-ac331b5c-3d8b-11e8-9e9f-9ad49ba05d92.png).

**Comment by MaStr11** [comment]
The documentation on the marketplace is outdated. Follow this instructions https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/syntax-visualizer?tabs=csharp#installation-instructions to install the SDK.

**Comment by tiesmaster** [comment]
Awesome, thanks for the quick reply. Looking at your forks, I see the sdk is actually now in a separate repo. Thnx!
