### ISSUE TITLE
Impossible NullReferenceException

### ISSUE THREAD

**Issue by SergeyTeplyakov** [dotnet/roslyn#26091]
**Version Used**: Visual Studio 15.6.2

**Steps to Reproduce**:
The following code throws `NullReferenceException` but not `IndexOutOfRangeException`:

```csharp
public unsafe struct FixedBytes
{
    public const int MaxLength = 33;
    private fixed byte _bytes[MaxLength];

    public FixedBytes(BinaryReader reader, int length = MaxLength)
    {
        if (reader == null) throw new ArgumentNullException();

        var buffer = reader.ReadBytes(length);

        fixed (byte* p = _bytes, s = buffer)
        {
            for (var i = 0; i < length; i++)
            {
                p[i] = s[i];
            }
        }
    }
}
class Program
{
    static void Main(string[] args)
    {
        var ms = new MemoryStream(new byte[0]);
        var dr = new BinaryReader(ms);
        FixedBytes fb = new FixedBytes(dr);
    }
}
```
**Expected Behavior**:
The code should throw `IndexOutOfRangeException`.

**Actual Behavior**:
The code throws `NullReferenceException`.

Here how the decompiled version of this code looks like:

```csharp
public unsafe FixedBytes(BinaryReader reader, int length = 33)
{
	if (reader == null)
	{
		throw new ArgumentNullException();
	}
	byte[] arg_1F_0 = reader.ReadBytes(length);
	fixed (byte** ptr = (byte**)(&this._bytes.FixedElementField))
	{
		byte* p = (byte*)ptr;
		fixed (byte[] array = arg_1F_0)
		{
			byte* s;
			if (arg_1F_0 == null || array.Length == 0)
			{
				s = null;
			}
			else
			{
				s = &array[0];
			}
			for (int i = 0; i < length; i++)
			{
				p[i] = s[i]; // <- This will throw NRE if arg_1F_0 is null or empty
			}
			ptr = null;
		}
		return;
	}
}
```
It means that if a reader returns an empty array, the `s` local is `null` and NRE is thrown.

**Comment by CyrusNajmabadi** [comment]
> An expression of an array_type with elements of an unmanaged type T, provided the type T* is implicitly convertible to the pointer type given in the fixed statement. In this case, the initializer computes the address of the first element in the array, and the entire array is guaranteed to remain at a fixed address for the duration of the fixed statement. [b]If the array expression is null or if the array has zero elements, the initializer computes an address equal to zero.[/b]

https://github.com/dotnet/csharplang/blob/master/spec/unsafe-code.md#the-fixed-statement

**Comment by CyrusNajmabadi** [comment]
This seems to be behaving as per the spec.

**Comment by SergeyTeplyakov** [comment]
@CyrusNajmabadi Thanks! Good to know about this! Even though it is very unintuitive and it took some time to figure out why we're getting NRE in this case.
