### ISSUE TITLE
Local captured by inner local function is shown as captured by the outer local function in quick info

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#26101]
**Version Used**: VS 15.7 Preview 3

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/3105979/38640392-6448e7dc-3de9-11e8-8959-68cce16d8513.png)

/cc @jcouv

**Comment by jcouv** [comment]
Fix was merged for 15.8 preview4.
