### ISSUE TITLE
ENC: previousPDBReader is not set to null with repeating Edits 

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#26109]
1. Run an ENC scenario
2. Make a rude edit
3. Try to continue
4. Get a dialog providing Edit/Stop selection
5. Choose Edit
6. Make a valid Edit
7. Try to proceed with ENC again
8. Fail on the following [VsENCRebuildableProjectImpl.cs,1018:](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/EditAndContinue/VsENCRebuildableProjectImpl.cs,1018) line:
`                    // PDB reader should have been nulled out when debugging stopped:
                    Contract.ThrowIfFalse(previousPdbReader == null);`

Actually, we reproduced the issue trying to reproduce https://devdiv.visualstudio.com/DevDiv/_workitems/edit/597713?src=alerts&src-action=cta

We got another error on the first attempt. Then, tried to Edit and Continue once again and failed on the line mentioned.

**Comment by tmat** [comment]
This has actually been fixed in `15.7.x-vs-deps` branch for a while.
