### ISSUE TITLE
Are VB Scanner Tests around Preprocessing Directives correct.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#26114]
Within written source wouldn't the line ending be `CrLf` rather than`Lf` ?
Due to XML Literal representations of input source code that is used withing the unit tests. 
In other places within test the difference is accounted for and other it isn't.

**Comment by gafter** [comment]
@AdamSpeight2008 If you are attempting to report problems with specific unit tests, please identify them much more specifically. As far as we know our unit tests are correct.
