### ISSUE TITLE
Regex tester tool inside VS

### ISSUE THREAD

**Issue by dleung8** [dotnet/roslyn#26118]
Version: VS2017 Enterprise (15.6.2) 

ReSharper has a regex tester tool where you can put in an expression and type arbitrary test strings that will show if they validate and if groupings are specified, which ones match to what. While there are plenty of online tools to do this, it was very convenient to have a built-in tool that doesn't require switching out of context of the IDE.

I don't need to use it every day, but use it on occasion (maybe 10 times or so a month).

**Comment by alrz** [comment]
something like an extension? (for instance: https://marketplace.visualstudio.com/items?itemName=AndreasAndersen.RegularExpressionTesterExtension)

**Comment by Joe4evr** [comment]
@dleung8 You may also be interested in #23984 which intends to colorize Regex strings as a first-class feature in the compiler (no extension necessary).

**Comment by CyrusNajmabadi** [comment]
@jinujoseph @sharwell Would like to take this to next design review to consider if this is out of scope for Roslyn.

**Comment by jinujoseph** [comment]
cc @kendrahavens @mikadumont for Value Prop on this

**Comment by tmat** [comment]
One can also use the Interactive Window to do this.

![image](https://user-images.githubusercontent.com/41759/76239987-b6ca2300-61ef-11ea-96ba-f6d927f95b10.png)

**Comment by kendrahavens** [comment]
From the design meeting:

This is not high priority as there are popular extensions that fill this need. We recommend to use:
[Regex Tester](https://marketplace.visualstudio.com/items?itemName=RomanKurbangaliyev.RegexTester)
[Regex Editor](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.RegexEditor)
[Regular Expressions Tester Extension](https://marketplace.visualstudio.com/items?itemName=AndreasAndersen.RegularExpressionTesterExtension)
