### ISSUE TITLE
Tests invalid when language version default is 8.0

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#26115]
A number of unit and regression tests are invalidated by changes in C# language versions 7.1, 7.2, and 7.3, but many tests are written to assume that these new features are not present. This shows up in the feature branch `features/recursive-patterns`, where the default language version has been changed to 8.0. I fixed a number of tests where the fix was clear. Remaining, broken tests are marked as skipped with this bug, listed below. I cannot be sure that there are not other issues causing these failures, but no other significant change appears in the branch in which this failure was first observed.

- `Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests.NoKeywordsOrSymbolsAfterNamedParameter`
- `Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.CodeRefactorings.InlineTemporary.InlineTemporaryTests.DontParenthesizeInterpolatedStringWithInterpolation`
- `Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.CodeRefactorings.InlineTemporary.InlineTemporaryTests.DontParenthesizeInterpolatedStringWithNoInterpolation`
- `Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.CodeRefactorings.LambdaSimplifier.LambdaSimplifierTests.TestMissingOnAmbiguity1`
- `Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.UseDeconstruction.UseDeconstructionTests.TestNotWithDefaultLiteralInitializer`
- `Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.Async.UpgradeProjectTests.ListAllSuggestions`
- `Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.Async.UpgradeProjectTests.OnlyOfferFixAllProjectsToDefaultWhenApplicable`
- `Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.Async.UpgradeProjectTests.UpgradeAllProjectsToCSharp7`
- `Microsoft.CodeAnalysis.MSBuild.UnitTests.NetCoreTests.TestOpenProject_NetCoreApp2`
- `Microsoft.CodeAnalysis.MSBuild.UnitTests.NetCoreTests.TestOpenProject_NetCoreMultiTFM`
- `Microsoft.CodeAnalysis.MSBuild.UnitTests.NetCoreTests.TestOpenProject_NetCoreMultiTFM_ProjectReference`
- `Microsoft.CodeAnalysis.MSBuild.UnitTests.NetCoreTests.TestOpenProject_NetCoreMultiTFM_ProjectReferenceWithReversedTFMs`
- `Microsoft.CodeAnalysis.MSBuild.UnitTests.NetCoreTests.TestOpenProjectTwice_NetCoreApp2AndLibrary`
- `Microsoft.CodeAnalysis.MSBuild.UnitTests.NetCoreTests.TestOpenProjectTwice_NetCoreApp2AndTwoLibraries`

**Comment by alrz** [comment]
Shouldn't we use "latest" version as the default version for tests?

**Comment by gafter** [comment]
@alrz Either way, when the default and latest version changed to 8.0, tests broke.

**Comment by CyrusNajmabadi** [comment]
Closing out.  Could find no existing tests skipped with this issue.
