### ISSUE TITLE
Provide an API for mapping between generated source code and original Razor source code

### ISSUE THREAD

**Issue by rynowak** [dotnet/roslyn#26124]
**This issue is part of a larger plan to enable the Find-All-References and Refactoring for the .NET Core Razor editor in Visual Studio.** 

You can find the tracking project for the entire feature here:  https://github.com/aspnet/Razor/projects/13
You can find more context about what's required here: https://gist.github.com/rynowak/ac48949e76e08ce7fdc533ada17c8d16#roslyn

----- 

We need to (with the help of the Roslyn) translate spans in generated C# code back to the original locations in the user's .cshtml sources. This will enable features like Find All References, Code Lens, Code Fixes, and Refactoring that don't work today in Razor source code.

This issue tracks the work on the Roslyn IDE to define a new API that Razor can implement, and then call this API when the results of a Find All References, Codes Lens, CodeFix or Refactoring operation occur in generated code. Roslyn will be responsible for applying edits or showing previews, including in documents that are not tracked as part of the workspace.

Razor will be responsible for implementing this new API, hooking up the implementation to the language services, and for the correctness of results. We currently expect that the implementation of this new API will be provided through the `IWorkspaceProjectContextFactory` during project initialization.

Razor will be responsible for initializing the language service with the generated code, so that these features can find results in Razor's generated output.

This issue is not a design doc for the API, we still need to drill into that once this work is committed.

/cc @jinujoseph @jasonmalinowski

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable currently.  This should just be working with how razor uses LSP and communicates with the roslyn LSP server.  That *is* the api for mapping between things.
