### ISSUE TITLE
No IntelliSense suggestion for readonly struct

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#26120]
Version checked: 15.6.6, 15.7 Preview 3

Keyword `readonly` should be available everywhere that `struct` is available, and only `struct` allowed after it?

**Comment by jcouv** [comment]
@huoyaoyuan I didn't understand the issue.
Please describe what you're typing, what actual completion was provided and how it differed from what you expected. The issue you opened sounds like a question and it is not clear what (if anything) needs to be done to fix it.
Thanks

**Comment by jcouv** [comment]
@CyrusNajmabadi I agree. This should have been covered as part of the feature work.
I see that we tested some completion (https://github.com/dotnet/roslyn/issues/19216 section "Misc"), but this one was missed.
