### ISSUE TITLE
Extract method in an ElseIfBlockSyntax extracts the whole MultiLineIfBlockSyntax in VB.NET.

### ISSUE THREAD

**Issue by lpperras** [dotnet/roslyn#26121]
**Version Used**: 
2.7.0

**Steps to Reproduce**:

1. Create a VB.NET project with the following code:
`Module Module1

    Sub Main()
        If False Then
        ElseIf True Then
            Console.WriteLine()
            Console.WriteLine()
        End If
    End Sub

End Module`
2. Select the two lines 'Console.WriteLine())
3. Trigger the extract method on that selection.

**Expected Behavior**:
It should create a new 'NewMethod()' with the two 'Console.WriteLine()' in it.

**Actual Behavior**:
It creates a new method with the whole If in it.

**Comment by CyrusNajmabadi** [comment]
Closing as we are not likely to be changing these experiences.
