### ISSUE TITLE
refactor AbstractLanguageService and add unit tests for ITextBuffer

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#26133]
See comments to https://github.com/dotnet/roslyn/pull/26128

**Comment by jcouv** [comment]
I'd suggest copying specific suggestions into the present issue, while they are fresh in mind. Digging through threads isn't fun.

**Comment by ivanbasov** [comment]
Thank you, @jcouv! I would definitely agree.  I would also prefer to make the whole with fix the original PR. However, the original work item is a telemetry based VSO bug and the PR is waiting for the escrow approval. Therefore, in this particular case, I think we have to use a separate item to track improvements not required for the escrow approval.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
