### ISSUE TITLE
Which branch can be compiled with Visual Studio 2015?

### ISSUE THREAD

**Issue by desarrollo03TR** [dotnet/roslyn#26147]
I need to compile roslyn in VS 2015, but I'm getting several compilation errors.

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by jaredpar** [comment]
In order to build this repository with VS 2015 you will need to go to the releases/VS2015 branch: https://github.com/dotnet/roslyn/tree/releases/VS2015
