### ISSUE TITLE
Registering a syntax node action on SyntaxKind.GenericName triggers the diagnostic twice on field level

### ISSUE THREAD

**Issue by Vannevelj** [dotnet/roslyn#2614]
When I create an analyzer that should be triggered on each generic type syntax occurrence, it seems to work fine for most places except on field level: then the diagnostic is created twice even though there is only one generic type.

Sample analyzer:

    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    public class Analyzer1Analyzer : DiagnosticAnalyzer
    {
        public const string DiagnosticId = "DiagnosticId";
        public const string Title = "Title";
        public const string Message = "Message";
        public const string Category = "Category";
        public const DiagnosticSeverity Severity = DiagnosticSeverity.Warning;

        internal static DiagnosticDescriptor Rule = 
            new DiagnosticDescriptor(DiagnosticId, Title, Message, 
                                     Category, Severity, isEnabledByDefault: true);

        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
             ImmutableArray.Create(Rule);

        public override void Initialize(AnalysisContext context)
        {
            context.RegisterSyntaxNodeAction(AnalyzeSymbol, SyntaxKind.GenericName);
        }

        private void AnalyzeSymbol(SyntaxNodeAnalysisContext context)
        {
            context.ReportDiagnostic(Diagnostic.Create(Rule, context.Node.GetLocation()));
        }
    }

Test:

    [TestClass]
    public class UnitTest : DiagnosticVerifier
    {
        [TestMethod]
        public void Test()
        {
            var original = @"
    using System;
    using System.Text;

    namespace ConsoleApplication1
    {
        class MyClass
        {   
            private Nullable<int> myVar = 5;
            void Method()
            {
                
            }
        }
    }";

            var expectedDiagnostic = new DiagnosticResult
            {
                Id = Analyzer1Analyzer.DiagnosticId,
                Message = Analyzer1Analyzer.Message,
                Severity = Analyzer1Analyzer.Severity,
                Locations =
                    new[]
                    {
                        new DiagnosticResultLocation("Test0.cs", 9, 13)
                    }
            };

            VerifyCSharpDiagnostic(original, expectedDiagnostic);
        }

        protected override DiagnosticAnalyzer GetCSharpDiagnosticAnalyzer()
        {
            return new Analyzer1Analyzer();
        }
    }

Result:

> Result StackTrace:	
at TestHelper.DiagnosticVerifier.VerifyDiagnosticResults(IEnumerable`1 actualResults, DiagnosticAnalyzer analyzer, DiagnosticResult[] expectedResults) in c:\users\jeroen\documents\visual studio 2015\Projects\Analyzer1\Analyzer1\Analyzer1.Test\Verifiers\DiagnosticVerifier.cs:line 113
   at TestHelper.DiagnosticVerifier.VerifyDiagnostics(String[] sources, String language, DiagnosticAnalyzer analyzer, DiagnosticResult[] expected) in c:\users\jeroen\documents\visual studio 2015\Projects\Analyzer1\Analyzer1\Analyzer1.Test\Verifiers\DiagnosticVerifier.cs:line 91
   at TestHelper.DiagnosticVerifier.VerifyCSharpDiagnostic(String source, DiagnosticResult[] expected) in c:\users\jeroen\documents\visual studio 2015\Projects\Analyzer1\Analyzer1\Analyzer1.Test\Verifiers\DiagnosticVerifier.cs:line 44
   at Analyzer1.Test.UnitTest.Test() in c:\users\jeroen\documents\visual studio 2015\Projects\Analyzer1\Analyzer1\Analyzer1.Test\UnitTests.cs:line 45
Result Message:	
Assert.IsTrue failed. Mismatch between number of diagnostics returned, expected "1" acutal "2"

> Diagnostics:
// Test0.cs(9,21): warning DiagnosticId: Message
GetCSharpResultAt(9, 21, Analyzer1Analyzer.DiagnosticId),
// Test0.cs(9,21): warning DiagnosticId: Message
GetCSharpResultAt(9, 21, Analyzer1Analyzer.DiagnosticId)

**Comment by mavasani** [comment]
I am unable to repro this on the latest Roslyn bits. I tried following repros:

1. Create an analyzer + code fix project and replace the analyzer contents with your analyzer and replace the unit tests in UnitTests.cs with the test you provided. Test pass fine for me, attached screenshot below:

![norepro_2614](https://cloud.githubusercontent.com/assets/10605811/7641335/f835ba58-fa3d-11e4-9320-89406a7fca30.png)

2. I created unit tests for IDE and command line compiler analyzer drivers, and both of them pass. I'll send a PR for these regression tests soon.

**Comment by mavasani** [comment]
Closing as no repro. Please re-activate if you are still able to repro it!

**Comment by Vannevelj** [comment]
This is [the second](https://github.com/dotnet/roslyn/issues/2557) issue I have that can't be reproduced on your team's end. I'm using VS 2015 RC, do I somehow have to update something myself? 

I don't think I'm missing anything:

![stillbugged](https://cloud.githubusercontent.com/assets/2777107/7642659/27f90024-fa93-11e4-8a52-cb0b9b06a89a.PNG)

**Comment by mavasani** [comment]
I think the issue did exist in RC but was fixed post RC. You may want to try moving to newer nuget packages OR have to wait till the latest Roslyn nuget packages are available.

**Comment by Vannevelj** [comment]
Looks like I was still on Beta-1. I have now moved to RC 2 and fixed the API changes that came with it. I can't use my tests though: the *Verifier.Helper classes were provided when creating the Diagnostic with CodeFix template solution.

Can I find an updated version of these test helpers somewhere? More specifically: `AnalyzerDriver` is now not accessible. What should I use instead?

Perhaps a more important question: aren't these test helpers provided through a NuGet package?

**Comment by Vannevelj** [comment]
Alright, it seems like I've got this to work again. For reference, the changes I made to the included test files are these (after updating to RC 2):

DiagnosticVerifier.Helper.cs:

Lines 65-67

    - var driver = AnalyzerDriver.Create(compilation, ImmutableArray.Create(analyzer), null, out compilation, CancellationToken.None);
    - var discarded = compilation.GetDiagnostics();
    - var diags = driver.GetDiagnosticsAsync().Result;
    + var diags = compilation.WithAnalyzers(ImmutableArray.Create(analyzer)).GetAnalyzerDiagnosticsAsync().Result;

Line 162:

    - var solution = new CustomWorkspace()
    + var solution = new AdhocWorkspace()

CodeFixVerifier.cs:

Line 95:

    - codeFixProvider.ComputeFixesAsync(context).Wait();
    + codeFixProvider.RegisterCodeFixesAsync(context).Wait();

I seem to still have issues with code not being formatted correctly but at least the original error I made this issue for is fixed. Thanks for the help!
