### ISSUE TITLE
How CodeActionOperation instances can be registered for processing by the UI thread?

### ISSUE THREAD

**Issue by DmitriiGaidukov** [dotnet/roslyn#26146]
I started working on my first Code Refactoring project recently. I have a refactoring action that creates a new document and I want to modify the action so that newly created document will be opened in the foreground in Visual Studio.  
I tried Workspace.OpenDocument method, but run into an InvalidOperationException «This workspace only supports opening documents on the UI thread».
I started googling and found out that  UI related work have to be implemented in the overrided Apply method of CodeActionOperation class. And for OpenDocument such implementation already exists in OpenDocumentOperation class.
Unfortunately, I failed to figure out how CodeActionOperation instances can be registered for processing by the UI thread. I tried calling Apply directly from the method passed in the createChangedSolution delegate but there was the same InvalidOperationException. Please, guys, help.

**Comment by CyrusNajmabadi** [comment]
> I have a refactoring action that creates a new document and I want to modify the action so that newly created document will be opened in the foreground in Visual Studio.

There are a few options.  As you mentioned, the best one would be to just use  [OpenDocumentOperation](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/CodeActions/Operations/OpenDocumentOperation.cs) in your code action.  Roslyn already knows how to handle this operation and will do the right thing.

We should figure out why that's not working first before we consider other options. 

> Unfortunately, I failed to figure out how CodeActionOperation instances can be registered for processing by the UI thread.

You don't need to do anything.  CodeActionOperations are already processed on hte UI thread.  You just need to return those operations from your CodeAction.ComputeOperationsAsync override.

**Comment by DmitriiGaidukov** [comment]
Thanks, @CyrusNajmabadi ! I’ve changed the code as you suggested and it works. 

Actually, until this moment I knew just of one way to create actions, namely through  CodeAction.Create(). Now I declared my custom class derived from CodeActionOperation and moved refactoring logic into the overrided version of ComputeOperationsAsync. The modified solution is being wrapped into a new instance of ApplyChangesOperation action class and returned in the same collection as OpenDocumentOperation instance. And I’ve just plugged GetOptions() with the Object instance. 

`
public override object GetOptions(CancellationToken cancellationToken)
        {
            return new Object();
        }

protected override Task<IEnumerable<CodeActionOperation>> ComputeOperationsAsync(object options, CancellationToken cancellationToken)
        {
           //... (refactoring logic)

            IEnumerable<CodeActionOperation> operations = new CodeActionOperation[]
            {
                new ApplyChangesOperation(newSolution),
                new OpenDocumentOperation(addedDocument.Id, true)
            };

            return Task.FromResult(operations);
        }`

Unfortunately, I failed to find much of documentation about all this things and was able to continue only through reading Roslyn sources and making experiments and so I have a somewhat vague understanding. It would be great if there is e.g. some really good book on the subject which you could recommend me.

**Comment by DmitriiGaidukov** [comment]
upd. Noticed a minor issue with my CodeActionOperation. The preview window doesn't appear.

**Comment by DmitriiGaidukov** [comment]
@jinujoseph, excuse me, just for double check. Did I provide enough details about my problem?

**Comment by CyrusNajmabadi** [comment]
> it looks like the preview is processed on not UI thread. Can't work out what I've missed.

Correct.  You need to make sure your preview code doesn't do any UI work.

**Comment by DmitriiGaidukov** [comment]
> You need to make sure your preview code doesn't do any UI work. If necessary, that means a different set of work than what your final apply will do.
In my override for CodeActionWithOptions.ComputeOperationsAsync apart from preparation work such as traversing through solution structure, collecting and analyzing 

`protected override Task<IEnumerable<CodeActionOperation>> ComputeOperationsAsync(object options, CancellationToken cancellationToken)
        {
            //...
            var addedDocument = _testProject.AddDocument(fileName, code, folders: fileFolders); 

            IEnumerable<CodeActionOperation> operations = new CodeActionOperation[]
            {
                new ApplyChangesOperation(addedDocument.Project.Solution),
                new OpenDocumentOperation(addedDocument.Id, true)
            };

            return Task.FromResult(operations);
        }`

**Comment by CyrusNajmabadi** [comment]
> In my override for CodeActionWithOptions.ComputeOperationsAsync

You also need an override for "ComputePreviewOperationsAsync" as well if you want your preview code ot be different than your normal code (and, in this case, you do).

```new OpenDocumentOperation(addedDocument.Id, true)```

you don't want that running in preview.  Otherwise the preview code will actually try to open the document.

**Comment by DmitriiGaidukov** [comment]
Now that I've overridden "ComputePreviewOperationsAsync", preview works fine again. Thanks! 

I noticed a subtle issue though. When I apply my refactoring in VS, everything works fine.  However, if I apply the same refactoring again in a few seconds time, then nothing happens. And for some reason, this issue doesn't occur, when I work in VS where JetBrains Resharper is enabled. 
But otherwise everything is ok.

> protected override Task<IEnumerable<CodeActionOperation>> ComputeOperationsAsync(object options, CancellationToken cancellationToken)
>             {
>                 var addedDocument = CreateTextFixtureDocument(cancellationToken);
> 
>                 IEnumerable<CodeActionOperation> operations = new CodeActionOperation[]
>                 {
>                     new ApplyChangesOperation(addedDocument.Project.Solution),
>                     new OpenDocumentOperation(addedDocument.Id, true)
>                 };
> 
>                 return Task.FromResult(operations);
>             }
> 
>             protected override async Task<IEnumerable<CodeActionOperation>> ComputePreviewOperationsAsync(CancellationToken cancellationToken)
>             {
>                 var addedDocument = CreateTextFixtureDocument(cancellationToken);
> 
>                 IEnumerable<CodeActionOperation> operations = new CodeActionOperation[]
>                 {
>                     new ApplyChangesOperation(addedDocument.Project.Solution),
>                 };
> 
>                 return await Task.FromResult(operations).ConfigureAwait(false);
>             }
