### ISSUE TITLE
IDE0019 'use pattern matching' on IDictionary fails

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#26168]
var htmlAttributesDict = htmlAttributesObject as IDictionary&lt;string, object&gt;;
          
            RouteValueDictionary htmlAttributes = (htmlAttributesDict != null)
            ? new RouteValueDictionary(htmlAttributesDict)
            : HtmlHelper.AnonymousObjectToHtmlAttributes(htmlAttributesObject);

Reports:

IDE0019	Use pattern matching	eCtdFtpAutomation.Web	C:\Users\mreri\source\repos\eCTDFTPAutomation\eCtdFtpAutomation.Web\Helpers\SiteHelpers.cs	143	Active

The corresponding fix resulting in the following uncompilable code:

            RouteValueDictionary htmlAttributes = (htmlAttributesObject isIDictionary&lt;string, object&gt;htmlAttributesDict)
            ? new RouteValueDictionary(htmlAttributesDict)
            : HtmlHelper.AnonymousObjectToHtmlAttributes(htmlAttributesObject);

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/230637/ide0019-use-pattern-matching-on-idictionary-fails.html
VSTS ticketId: 597233_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
cc @alrz

**Comment by alrz** [comment]
Doesn't repro.

![image](https://user-images.githubusercontent.com/3105979/38819337-6070bc0a-41b0-11e8-9432-1ab5ccb29d9b.png)

**Comment by CyrusNajmabadi** [comment]
Can't repro this either.  And looks to be covered by existing tests.  Closing out.
