### ISSUE TITLE
Go to Implementation command should not consider abstract declarations with no implementation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#26167]
I have a simple C# project with an abstract base class and and derived class.

Sample code:

    public abstract class Base
    {
        private void CallFoo()
        {
            // Invoking &quot;Go to Implementation&quot; on this line goes to the abstract declaration, instead of the actual implementation
            this.Foo();
        }

        protected abstract void Foo();
    }

    public class Derived : Base
    {
        protected override void Foo()
        {
        }
    }

When I invoke &quot;Go to Implementation&quot; on the call to &quot;this.Foo()&quot;, I get a list of implementations to choose from (the override plus the abstract declaration). The abstract declaration is NOT an implementation, so this should not be considered. It should just immediately navigate to the override (like it did in previous versions), without presenting me with a list.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/231292/go-to-implementation-command-should-not-consider-a.html
VSTS ticketId: 597749_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by dpoeschl** [comment]
For members, we agree that it should skip abstract members. The approach seems correct.
