### ISSUE TITLE
Unable to use Roslyn v2.6.0 built analyzers from Visual Studio 2017 v15.6.6 project in a .Net 4.7.1 installed machine

### ISSUE THREAD

**Issue by msbasanth** [dotnet/roslyn#26169]
**Version Used**: 
Microsoft.CodeAnalysis - v2.6.0
Visual Studio 2017 v15.6.6

**Steps to Reproduce**:

1. We have an analyzer assembly built using new CSPROJ structure and with netstandard2.0 + Roslyn v2.6.0
2. I am using this analyzer assembly in a .Net Framework 4.7 class library project an analyzer in it and that analyzer DLL in another project.
3. I am getting a warning and analyzer is loaded in VS2017
Warning	IDE1003	Analyzer assembly 'XXX.Analyzer.dll' depends on 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' but it was not found. Analyzers may not run correctly unless the missing assembly is added as an analyzer reference as well.

Another error found:
Warning	CS8034	Unable to load Analyzer assembly XXX.Analyzer.dll: Could not load file or assembly 'file:///C:\Users\XXX\AppData\Local\Temp\VS\AnalyzerAssemblyLoader\19af1c9f57f14308b952d8ce23aacc92\14\XXX>Analyzerdll' or one of its dependencies. An attempt was made to load a program with an incorrect format.

Included analyzer assembly and dependencies:
![image](https://user-images.githubusercontent.com/17777813/38808004-2c67db14-419c-11e8-93ca-1296ad84ff49.png)

In the VS2017 UI the analyzer assembly is shown under Analyzers but unable to expand to see analyzers included in the package.
![image](https://user-images.githubusercontent.com/17777813/38808084-756103b8-419c-11e8-9182-c1e35556454a.png)

Expected Behavior:
With .Net Framework 4.7.1 Installed which is having netstandard2.0 implemented we should not get these errors. 

Actual Behavior:
Shows above mentioned errors and it shows unable to create analyzer instance.

The same analyzer when I used older csproj format and Roslyn version 1.6 it worked fine.Any hint on why analyzer is not picking netstandard2.0 dependency from Visual Studio 2017.

Thanks
Basanth

**Comment by jmarolf** [comment]
> The same analyzer when I used older csproj format and Roslyn version 1.6 it worked fine.Any hint on why analyzer is not picking netstandard2.0 dependency from Visual Studio 2017.

This is surprising to me.  Can you give me an example nuget package where a netstandard2.0 analyzer can load successfully in Visual Studio? Analyzers, to my knowledge, have never worked in Visual Studio 2017 with netstandard2.0 because of the way Visual Studio finds and loads assemblies.  Currently all templates default to netstandard1.3 as this is the newest version that has been tested to work.

**Comment by msbasanth** [comment]
@jmarolf It was a typo. I don't have a netstandard2.0 analyzer loaded in VS2017.
Currently, I have my analyzer package targeting netstandard1.6 + Roslyn 2.6.0 which works fine in VS2017 15.5 and above.

Now I have to use few of the Assembly load API's introduced in netstandard2.0, so I switched to netstandard2.0. Is there any assembly redirection possible to make nestandard2.0 analyzer work in VS2017?

NB: I wanted netstandard2.0 API's Assembly.ReflectionOnlyLoadFrom & Module.GetPEKind for retrieving an assembly is managed only or not.
Hope you remember the other issue discussion: https://github.com/dotnet/roslyn/issues/26059

**Comment by jmarolf** [comment]
@msbasanth the problem is that, for a netstandard2.0 analyzer to work reliably you will need to deploy all the framework reference assemblies.  @terrajobst may know what the best way to do this is.  This will make you analyzer package rather large but it would unblock you.

**Comment by jmarolf** [comment]
@bkoelman that is a good point.  A simpler solution would be to target .NET Framework 4.6.  That is assuming you are never going to run these analyzers on a platform that does not have  .NET Framework 4.6.

**Comment by msbasanth** [comment]
Thanks, @bkoelman & @jmarolf 
I can live with retargeting the analyzers to the full framework.
