### ISSUE TITLE
Method reference count is wrong for VB event handlers

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#26166]
The reference count given above a method does show 0 for an event handler in VB that is defined with the Handles clause.
This is a little annoying because when cleaning up code you have to pay special attention to this because removing this event handler (because it's reference count is zero) will not generate a compiler error, but will break the application.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/232149/method-reference-count-is-wrong-for-vb-event-handl.html
VSTS ticketId: 598575_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by JoGillis** [comment]
This issue is even more annoying in VS2019 preview 1 and 1.1 where the analyzers even suggest to remove the code...
![annotation 2018-12-11 115854](https://user-images.githubusercontent.com/27762819/49796147-31ca3280-fd3c-11e8-9d33-feb131865e92.jpg)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to invest in these scenarios.
