### ISSUE TITLE
SyntaxGenerator.AsPublicInterfaceImplementation returns incorrect result for explicit implementations

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2616]
Invoke `SyntaxGenerator.AsPublicInterfaceImplementation`(http://source.roslyn.io/Microsoft.CodeAnalysis.CSharp.Workspaces/R/f860f54a842df309.html) method on a method declaration which explicitly implements an interface method. For example, invoke it on the method implementation below:

```
public interface IGeneral
{
    object DoSomething();
}

public class ImplementsGeneral  : IGeneral
{
    object IGeneral.DoSomething() { return null; }
}
```

**Expected result:**
`public object DoSomething() { return null; }`

**Actual result:**
`public object IGeneral.DoSomething() { return null; }`

The resulting method has semantic error as modifiers are not allowed on explicitly implemented methods.

**Comment by mavasani** [comment]
This returns a different sort of incorrect result when invoked for VB explicit interface implementations:

Original code:
```
Public Interface IGeneral
    Function DoSomething() As Object
End Interface

Public Class ImplementsGeneral
    Implements IGeneral
   
    Private Function IGeneral_DoSomething() As Object Implements IGeneral.DoSomething
        Return Nothing
    End Function
End Class
```

**Expected result:**
```
Public Function IGeneral_DoSomething() As Object Implements IGeneral.DoSomething
    Return Nothing
End Function
```

**Actual result:**
```
Public Function IGeneral_DoSomething() As Object Implements IGeneral.IGeneral_DoSomething Return Nothing
    End Function
```

Note that this introduces a syntax + semantic error. Probably it is being cause by incorrect implements clause being generated here (note the interfaceNode argument passed to this API was generated using `SyntaxGenerator.TypeExpression(symbolForIGeneral)`). 

@srivatsn @mattwar Do you want me to open a separate issue to track the VB bug?

**Comment by mattwar** [comment]
The implementation assumes that you are modifying a normal/default method invocation and turning it into a interface implementation. The original intent of the API is for simple construction of new nodes, so it got missed when updating the API to allow for edits. For C# that's a no-op, it just adds public accessibility.

**Comment by mattwar** [comment]
The VB implementation is assuming the same thing. It is not considering it is already an implementation of an interface method.  It also assumes that the current method name is the same as the name of the method in the interface, so that's how you get the concatenated name.

**Comment by mavasani** [comment]
See skipped unit tests for FxCop rule CA1033 fixer added with #2590, which are affected by this bug. Skipped tests have been marked with this issue.

**Comment by mattwar** [comment]
Okay.  I'll fix this next.

**Comment by mavasani** [comment]
@mattwar No hurries, I just wanted to inform that there are skipped tests which might enable you to repro this more easily, though you might have to tweak the actual output to re-enable them once you fix the underlying issue.

**Comment by lgolding** [comment]
Verified as fixed.
