### ISSUE TITLE
Roslyn release notes

### ISSUE THREAD

**Issue by wbalbal** [dotnet/roslyn#26173]
We deserve some release notes :)
version 2.8.0 beta is out and i don't know what's new and should we do the update

**Comment by jcouv** [comment]
See the [changelog](https://github.com/dotnet/roslyn/wiki/Changelog-for-C%23-and-VB-compilers).
Note: That document currently only covers the compilers.

**Comment by kendrahavens** [comment]
I've added the end user-facing features in release notes [here](https://github.com/dotnet/roslyn/tree/master/docs/ide) for those interested.

**Comment by WeihanLi** [comment]
Is there any release note for the NuGet packages like `Microsoft.CodeAnalysis.CSharp`?

**Comment by CyrusNajmabadi** [comment]
Closing out.
