### ISSUE TITLE
IntelliSense incorrectly attempts to disambiguate generic arguments when they clash with a member followup

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#26170]
**Version Used**: 
15.6.6

**Steps to Reproduce**:

This is a follow up on #21379

```cs
namespace A
{
    class B { }

    public class Test
    {
        static System.Collections.Generic.List<B> B { get; set; }

        public static void Main()
            => B.Add(new $$);
    }
}
```

At `$$`, IntelliSense disambiguates `B` to `A.B` which is then immediately grayed out because it's superfluous.

![invalid-disambiguation](https://user-images.githubusercontent.com/1947968/38806197-badaa1e8-4178-11e8-8faa-559d1a3c5421.gif)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
