### ISSUE TITLE
flaky unit test: VisualStudioDiagnosticAnalyzerExecutorTests.TestCancellation

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#26183]
test is failing with this

    Roslyn.VisualStudio.Next.UnitTests.Remote.VisualStudioDiagnosticAnalyzerExecutorTests.TestCancellation
System.InvalidOperationException: Should have been disposed!

   en Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
   en System.Diagnostics.TraceListener.Fail(String message)
   en System.Diagnostics.TraceInternal.Fail(String message)
   en System.Diagnostics.Debug.Assert(Boolean condition, String message)
   en Roslyn.Utilities.Contract.Assert(Boolean condition, String message)
   en Roslyn.Utilities.Contract.Requires(Boolean condition, String message)
   en Microsoft.CodeAnalysis.Remote.RemoteHostClient.Connection.Finalize()

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't hit this in years and we have a dedicated system for tracking flakey tests now.
