### ISSUE TITLE
Review and finalize public APIs

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26198]
Note: we should remember to update the few places (marked with this issue's URL) where our code should make use of such APIs once they become available.

- `GetTypeInfo` should work on suppressed expression (relates to https://github.com/dotnet/roslyn/pull/34025)

- semantic model should provide nullability information in LINQ queries (range variables)

- `ReferenceTypeConstraintIsNullable`
- `HasNotnullConstraint`

Should we expose through `ITypeParameterSymbol`?

- IncludeNonNullableTypeModifier

For testing, we need an option to show `!` (that's `IncludeNonNullableTypeModifier`). But we also need an option to control whether to show `string?` or `string`.
The IDE will definitely want to show `string?` in some cases (if not all). But if we just make that the default, then we'll be surprising existing clients of our APIs.

Two questions:
- should this option be public rather than internal?
- should this option be opt-in rather than opt-out?

```C#
        /// <summary>
        /// Don't append '!' (or '?') to non-nullable (or nullable) reference types.
        /// Cannot be used in conjunction with <see cref="IncludeNonNullableTypeModifier"/>.
        /// </summary>
        PlainReferenceTypes = 1 << 7,
```

Relates to https://github.com/dotnet/roslyn/pull/25928

Note: this option was renamed in the PR, and another option was added for using `ValueTuple` instead of `(...)` tuple syntax. We should also consider making the latter public.

**Comment by 333fred** [comment]
Broke the naming out into a separate bug: https://github.com/dotnet/roslyn/issues/37441

**Comment by 333fred** [comment]
We're pretty satisfied with the API at this point, closing this bug.
