### ISSUE TITLE
Make Readonly doesn't have a description for the Error List

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#26219]
![image](https://user-images.githubusercontent.com/1402694/38903471-dba42390-4259-11e8-84e3-8ff7d4396003.png)

It shows Description as blank for IDE0044.

**Comment by CyrusNajmabadi** [comment]
Looks like we're using incorrect resources here:

```c#
                new LocalizableResourceString(nameof(FeaturesResources.Add_readonly_modifier), FeaturesResources.ResourceManager, typeof(FeaturesResources)),
                new LocalizableResourceString(nameof(FeaturesResources.Make_field_readonly), WorkspacesResources.ResourceManager, typeof(WorkspacesResources)))
```

Note the use of WorkspacesResources.  @mavasani Something to consider for an anlayzer.

**Comment by jinujoseph** [comment]
also reported at [link](https://developercommunity.visualstudio.com/content/problem/244010/ide0044-has-no-description-in-visual-studio-error.html)

**Comment by grimreaper38uk** [comment]
Why has this been closed??  I haven't seen a description in the error list for IDE0044, ever.

Is there a fix / mod to add the description in?  Again, why has this been closed?!?!

**Comment by whoisj** [comment]
@grimreaper38uk because @sharwell fixed the line of code which was causing this issue. With the issue fixed, the issue is closed. We normally do not keep bugs open until the fixes are released. Perhaps the "closed" state should say "Fixed in Next Release" like we do on DeveloperCommunity.VisualStudio.com, but I do not know if that is even an option on GitHub or not.

**Comment by sharwell** [comment]
I try to use the Milestone to indicate when the fix is expected to appear (15.8 for this bug). Not everyone uses that field though so it may be missing or stale in cases.

**Comment by spottedmahn** [comment]
Thanks to the Roslyn team to getting this fixed!

**Comment by whoisj** [comment]
@spottedmahn I'm seeing 15.8 preview 5 publicly available now.

![image](https://user-images.githubusercontent.com/11578325/43910201-2c2772d0-9bca-11e8-9cb0-15bdc5830770.png)

https://visualstudio.com/vs/preview
