### ISSUE TITLE
Compiler intermittently keeping strong name file locked during compilation causing build failures for proceeding projects

### ISSUE THREAD

**Issue by mrbcmorris** [dotnet/roslyn#26232]
**Version Used**: 
  Toolset 15.0 -- vbc.exe and csc.exe
**Steps to Reproduce**:
No specific reproduction steps have been discovered.  Failure appears intermittently.
**Expected Behavior**:
Project compiles successfully
**Actual Behavior**:
Project fails to compile reporting vbc : error BC36980: Error extracting public key from file '{filename}.snk': The process cannot access the file 'C:\Users\{userfolder}\AppData\Local\Temp\8465c7dc64a54c1995b784c2acab3192' because it is being used by another process. 

OR when csc.exe

Project fails reporting CSC : error CS7027: Error signing output with public key from file '{filename}.snk' -- The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)

---

This seems to be related to the original report with #2840 which appears to have drifted to a different discussion after original report.

We have attempted to update the UseSharedCompilation parameter for each project to false as a workaround.  This seems to be successful though we have one report of it not solving the issue.

Generally wailing, gnashing of teeth and keyboard smashing are utilized with a varying degree of success until the project compiles.

**Comment by jaredpar** [comment]
Do you have any virus scanning software installed on your machine? We've seen this bug a number of times and every time the issue has been virus scanning software locking the binary and preventing the strong naming operation to occur. Try disabling the software for `%TEMP%` and build directories and seeing if the error reproduces.

**Comment by mrbcmorris** [comment]
I do have a virus scanning installed.  Unfortunately, I wasn't able to get clearance to stop scanning %TEMP% or build directories but I've whitelisted both csc.exe and vbc.exe so any files they generate should be ignored from scanning.  Do you have any troubleshooting tips to detect the file locks during compile if the issue resurfaces after the whitelisting of csc and vbc?

Hopefully this will alleviate the issue, and I appreciate your time on the topic!

**Comment by jaredpar** [comment]
>  I've whitelisted both csc.exe and vbc.exe so any files they generate should be ignored from scanning.

Make sure to white list VBCSCompiler.exe as well. 

> Do you have any troubleshooting tips to detect the file locks during compile if the issue resurfaces after the whitelisting of csc and vbc?

Hopefully going forward this won't be an issue. We've changed the compiler to sign in memory now and hence it won't even go to `%TEMP%` except for specific cases around key containers.
