### ISSUE TITLE
Internal error in compiler C #

### ISSUE THREAD

**Issue by jnf007** [dotnet/roslyn#26258]
**Version Used**: 
VS Community 2017 15.6.6
.Net Framework 4.0

I have ASP.NET project and dll project in solution. When I degugging (show watch) in asp.net project, is all ok. When I degugging in dll project, watch window not show variable value, but  (CZ lang) "Vnitřní chyba v kompilátoru C#"  "Internal error in compiler C#".

When I set option "Použít zastaralé vyhodnocovače výrazů C# a VB"   "Use obsolete C # and VB expressions" in settings, I can show variable value in dll project.

This behavior I have on two notebooks and last and previous VS version.

**Comment by CyrusNajmabadi** [comment]
@jnf007 can you provide a project where this repros?

**Comment by jcouv** [comment]
@jnf007 Would you be available for debugging via Skype (voice call in English + shared desktop)?
I'm not sure how to debug this. @cston, would you know where to start, or who to ask?
