### ISSUE TITLE
[Performance] Should eliminate the calls for ProjectChanges.GetChangedDocuments()

### ISSUE THREAD

**Issue by JieCarolHu** [dotnet/roslyn#26254]
when fixing the bug https://github.com/dotnet/roslyn/issues/18199, I noticed the ProjectChanges.GetChangedDocuments() and DocumentState.HasContentChanged() get called too many times for the upgrade project scenario.  
I added 2 similar functions: ProjectChanges.GetTextChangedDocuments() and DocumentState.HasTextChanged() which only get the documents whose text changed without checking things like ParseOption etc.  
Eliminating the calls for GetChangedDocuments() or replace the calls to GetTextChangedDocuments() when possible will get a lot less changed documents to work with, therefore it will help to improve the performance

**Comment by CyrusNajmabadi** [comment]
There doesn't seem to be any traces/scenarios presented demonstrating a need for this, and we are not hearing any continued request on this.  Closing out.
