### ISSUE TITLE
"Make field readonly" should be offered when taking readonly ref

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#26263]
```c#
class C
{
    int i;

    void M()
    {
        ref readonly int j = ref i;
    }
}
```
Add readonly modifier should be offered on 'i'.

**Comment by Neme12** [comment]
Should work with ref conditionals as well.

**Comment by CyrusNajmabadi** [comment]
@VSadov can you point me to the latest docs on ref-expressions/readonly-ref?  i'd like to understand all the locations it can happen and what sort of syntactic/semantic checks i'll need to perform to understand that this is a safe situation to use "make field readonly".  Thanks!

**Comment by CyrusNajmabadi** [comment]
This is offered now:

![image](https://user-images.githubusercontent.com/4564579/152605135-bb19ae72-08e1-4b5d-9f10-9a4909d3df1c.png)
