### ISSUE TITLE
Build of a repo using the latest dotnet SDK drop failed in csc task

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#26273]
**Version Used**: 

.NET SDK 2.1.300-preview3-008646

**Steps to Reproduce**:

Log: `%internal_share%\public\tomat\Bugs\Roslyn26273\Build.binlog`

```
 Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An attempt was made to load a program with an incorrect format.
    at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, IAnalyzerAssemblyLoader analyzerAssemblyLoader)
    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
```

```
E:\A\_work\77\s\.packages\microsoft.netcore.compilers\2.8.0-beta3-62723-11\tools\Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code -532462766.
```

**Comment by tmat** [comment]
@jaredpar @mmitche @weshaggard

**Comment by jaredpar** [comment]
@agocke can you take a look at this.

**Comment by agocke** [comment]
@tmat What does the Microsoft.NETCore.Compilers package have to do with this? Is this a pure dotnet failure or is it a combination of dotnet and the Microsoft.NETCore.Compilers package?

**Comment by tmat** [comment]
The build uses the compiler from Microsoft.NETCore.Compilers. I'm wondering if we need to update the version of the package we're using?

https://github.com/dotnet/roslyn-tools/blob/master/sdks/RepoToolset/tools/DefaultVersions.props#L39

This only happened when the build itself runs dotnet cli 2.1.300-preview3-008646.

**Comment by tmat** [comment]
Odd thing is that the build is not failing all the time.

**Comment by jaredpar** [comment]
Closing as this hasn't repro'd since. Can re-open if we see this again.
