### ISSUE TITLE
Collection Initializer could initialize collections with a capacity

### ISSUE THREAD

**Issue by taspeotis** [dotnet/roslyn#2628]
(I searched the Roslyn code and couldn't find whether this was or wasn't implemented, so sorry if this suggestion is redundant.)

I believe currently the following code:

```
var integerList = new List<int> { 1, 2, 3 };
```

Will be translated as follows:

```
var temporaryList = new List<int>();
temporaryList.Add(1);
temporaryList.Add(2);
temporaryList.Add(3);
var integerList = temporaryList;
```

Note that the `List<int>` has a backing `int[]` array that starts empty then has to be reallocated/resized as more items are added to the list.

`List<T>` has a constructor that specifies a capacity that helps to avoid this reallocations. If Roslyn knows the number of items that are going to be added to the collection in advance, it could call the special constructor instead:

```
var temporaryList = new List<int>(capacity: 4 /* see #2 */);
temporaryList.Add(1);
temporaryList.Add(2);
temporaryList.Add(3);
var integerList = temporaryList;
```

It would appear this would improve performance in nearly every situation the collection initializer syntax is used. There are some things to consider though:
1. If the user could get their hands on the object while it was being constructed then they might see different behavior (depending on where the user could observe `collection.Capacity` it would vary as the items are `Add`'d. With this change the `collection.Capacity` would be static the whole time.)
2. If we initialize the collection with exactly the capacity of the items to be added then the final capacity might differ. Depending on how the collection grows its backing collection (e.g. `List` doubles each time) so if we initialized a `List` with a capacity of `3` for 3 items then the final size would be 3 not 4. So we should specify a `capacity` that's the smallest power-of-two needed to hold all the items.
3. Only the collections in `System.Collections.Generic` are good candidates for this, since they can generally be relied upon not to rely on being initialized with no capacity and then growing. Alternatively, if users think their collections can be initialized with the capacity directly there could be some sort of compiler infrastructure attribute like `[CapacityInitializationOkay(ParameterName = "initialSize")]` that allows third-party collections to opt-in.
4. There's a breaking change in that if a user adds many items that would cause an `OutOfMemoryException`, the `OutOfMemoryException` will be thrown when the collection is constructed, not at the `n`th call to `Add`. E.g.

```
var blobList = new List<byte[16384]>
{
   // 999999... items here
};
```

**Comment by HaloFour** [comment]
Roslyn could potentially do this with a few very well known classes, like `List<T>`.  The issue is that collection initializers is a convention that doesn't care about the type being initialized at all nor does it affect the constructor actually in use (one of the reasons why I hate that initializers in general permit omitting the parenthesis).  As long as the type exposes an `Add` method and the type implements `IEnumerable` the compiler will permit collection initializers.

Note that even with collection initializers you are free to explicitly call a constructor:

```cs
List<int> list = new List<int>(3) { 1, 2, 3 };
```

**Comment by taspeotis** [comment]
Thank you for your response.

I'm aware I can call the constructor with a capacity myself, but now I have a magic number floating around in my code. It's also a maintenance burden. If I add items, I might need to increase the capacity, if I remove items I might need to decrease the capacity.

If you think this is worth pursuing I might take a look at submitting a pull request. If it's not I am happy to close this issue.

**Comment by HaloFour** [comment]
@taspeotis Don't let me discourage you.  I'm just a voice from the peanut gallery.

Always worth checking out language improvements and I think that collection initializers have quite a few opportunities to be improved.  Another good example is why collection initializers can't take advantage of `AddRange` which could provide additional performance benefits.

**Comment by KrisVandermotten** [comment]
This sounds like something that could be handled well by a Code Analyzer.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
