### ISSUE TITLE
Unshipped file creates un-necessary diff noise

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26285]
For instance, in PR https://github.com/dotnet/roslyn/pull/26202, much of the change is just re-ordering.

I think the code lives here: https://github.com/dotnet/roslyn-analyzers/tree/master/src/Roslyn.Diagnostics.Analyzers

- [x] Relax sorting logic in analyzer (https://github.com/dotnet/roslyn-analyzers/pull/1672)
- [ ] Integrate new analyzer package into rolsyn repo (https://github.com/dotnet/roslyn/pull/26399)
- [ ] Add script (or other solution) for infra to sort the files if they need (https://github.com/dotnet/roslyn/pull/26399)

-----
Some notes on working in the roslyn-analyzers repo (which seems to assume VS 2015, rather than VS 2017):
- Initialize repo with `cibuild.cmd`
- Build with `msbuild /v:m /m BuildAndTest.proj /p:Configuration=Debug /p:CIBuild=true /t:Build`
- Test with `"D:\repos\roslyn-analyzers\packages\xunit.runner.console.2.0.0\tools\xunit.console.x86.exe"  Binaries\Debug\Roslyn.Diagnostics.Analyzers.UnitTests.dll -noshadow` (and attach debugger as appropriate)

**Comment by AlekseyTs** [comment]
It looks like code fixer always reshuffles  content of this file. I am not sure why does it have to do this. If it sorts content, is it possible that the sort it uses is environment sensitive? I.e. can produce different result on different machines, etc.

**Comment by CyrusNajmabadi** [comment]
I think the intent is that people always use the code fixer and they do not manually edit the file.  Manual editing can be a problem because it's far more likely for conflicts to happen.  In general, with files that represent lists of data lke this, time-ordered data has more conflicts than sorted data.

**Comment by CyrusNajmabadi** [comment]
Perhaps the file at the top should say that this should not be edited by hand and that you should eiterh use the tool, or keep things sorted.

**Comment by jcouv** [comment]
I don't think anyone edits this file by hand. We suspect that the misordering results from merging different branches.

**Comment by tmeschter** [comment]
There _have_ been instances of the file being edited by hand, but I agree that merging branches is the more likely culprit.

Note that if new items were only added to the end, rather than in sort order, it more or less guarantees perpetual merge conflicts.

**Comment by CyrusNajmabadi** [comment]
ah, interesting.  @tmeschter sounds like a potential issue for sorted xlf files during merge as well, right?

**Comment by tmeschter** [comment]
@CyrusNajmabadi XLF files have a somewhat different use case, and a correspondingly different approach to updates.

With .xlf files we never forcibly sort the whole file. Instead, when inserting a new item we do a linear scan for the first existing item that logically comes after the new one, and insert there. Over time this will produce a file that is generally but not perfectly sorted. This is good enough for the purposes of minimizing merge conflicts by ensuring that new items generally end up in different places in the file, while still being deterministic. Devs do not generally need to examine changes in .xlf files, so this is good enough.

On the other hand, we *do* expect devs to examine changes to the public API files--the whole point is to make such changes highly visible. Imposing an absolute sort order when running the code fix ensures that changes appear in context (e.g., if a member is added, you can easily see all the other members of the type nearby) in addition to minimizing merge conflicts.

**Comment by CyrusNajmabadi** [comment]
Yup.  That makes sense.  The forced sorting here does seem quite problematic.  I like the xlf approach you took.  Seems like a reasonable approach for these files as well.  Keep things mostly conflict free, while ensuring easy reviewability.

**Comment by jcouv** [comment]
From discussion with @AlekseyTs, I'm thinking to modifier the public API fixer to not sort its output. When inserting, it should find the first reasonable place to insert (to keep the file more or less sorted). When updating, it should update the line in-place.
Would that make sense?

**Comment by CyrusNajmabadi** [comment]
Makes sense to me.

**Comment by jcouv** [comment]
Queued PR: https://github.com/dotnet/roslyn-analyzers/pull/1672

**Comment by mavasani** [comment]
@jcouv +1 on relaxing the sorting logic of the public API fixer. However, I feel once in a while (probably at every release), we may want to just sort the whole file in the repo with a separate PR. Can we have the fixer register 2 fixes?

1. `Add x to public API`
2. `Add x to public API and sort file`

The implementation of the code action can share most of the code, with a bool controlling the file sort requirement. Ideally, 2. would just be a separate diagnostic/fix on the additional file, but we don't support code fixes from additional files, so our only option is to take this model. Let me know if you have a better suggestion.

**Comment by jcouv** [comment]
From discussion with @mavasani, I added a script (in PR https://github.com/dotnet/roslyn/pull/26399, which also pulls in the latest RoslynAnalyzer package with the fix to PublicAPI fixer) to help Tiger or whoever needs it to sort the "unshipped" files.
