### ISSUE TITLE
Debugging Roslyn: mismatch between line breaks on Mac vs. in .pdbs

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#26293]
We've discovered that debugging Roslyn on Mac doesn't work because when we git clone Roslyn and checkout the specific SHA on a Mac, it checks out using `\n` line endings, whereas the .pdbs for Roslyn have `\r\n` baked in, and so the debugger checksums don't match. 

My theory is that even though Roslyn stores the sources with `\n` in the Git repo, when the CI machines check out on Windows, they checkout with `\r\n` line endings, and so those are the ones baked into the .pdbs.

I guess one solution is embedding sources into the .pdbs, but this is currently not supported in VSMac debugger, we have to resort to checking out a Roslyn SHA and running `unix2dos` on each file like so:

```
brew install dos2unix
find . -name "*.cs" -exec unix2dos {} \;```

**Comment by KirillOsenkov** [comment]
cc @DavidKarlas

**Comment by sharwell** [comment]
How is GitLink/SourceLink *supposed* to handle this situation? Ideally the following would occur:

* Source files are stored with normalized line endings
* Source files are checked out according to the users local settings
* Debugging works for everyone

Currently the first two cases hold, but the third does not.

**Comment by KirillOsenkov** [comment]
I'm hinting at maybe switching Roslyn `.gitattributes` to `* -text` so that Roslyn sources are checkout as-is on all machines without any line ending conversions whatsoever.

**Comment by sharwell** [comment]
In practice I have observed nothing but disasters from that. In theory you could apply `eol=crlf` to the source files, but that comes with its own set of problems (namely a precondition on repositories attempting to use GitLink/SourceLink which authors, including myself, may object to).

**Comment by CyrusNajmabadi** [comment]
> In practice I have observed nothing but disasters from that.

Funnily enough, i see the opposite.  Having systems *only* treat files as raw data to not be interpreted leads to the best situation, where you don't run into issues exactly like this.  It seems odd htat a system ostensibly about strong guarantees about exact preservation with of file data, would have these sorts of translation steps going on.  It makes it part of hte design of the system that different people can check out data at the same commit point by get *different* data.

**Comment by tmat** [comment]
@KirillOsenkov @DavidKarlas is this still not working well? If so is there an issue tracking the fix on VS Mac side?

**Comment by KirillOsenkov** [comment]
VSMac has implemented checksum calculation with three line ending kinds (original, force LF and force CRLF). Even though I still think it’s best to avoid line ending conversions in Git, this issue is no longer blocking us.
