### ISSUE TITLE
CS8121 : switch perform the implicit cast to int before the pattern matching

### ISSUE THREAD

**Issue by FaustVX** [dotnet/roslyn#26290]
**C# 7.2**: 

**Code**:

```csharp
public abstract class SemanticType<Tbase>
{
    protected SemanticType(Tbase value)
    {
        Value = value;
    }

    public Tbase Value { get; }

    public static implicit operator Tbase(SemanticType<Tbase> type)
        => type.Value;
}

public abstract class EvenOddNumber : SemanticType<int>
{
    protected EvenOddNumber(int value)
        : base(value)
    { }
    public static implicit operator EvenOddNumber(int value)
        => value % 2 == 0 ? (EvenOddNumber)new EvenNumber(value) : new OddNumber(value);
}

public class EvenNumber : EvenOddNumber {}

public class OddNumber : EvenOddNumber {}
```

in Main.cs
```csharp
var number = (EvenOddNumber)0; // number is EvenOddNumber
switch (number)
{
    case OddNumber odd: //CS8121	An expression of type 'int' cannot be handled by a pattern of type 'OddNumber'.
        break;
    case EvenNumber even: //CS8121	An expression of type 'int' cannot be handled by a pattern of type 'EvenNumber'.
        break;
    case var p: // p is int
        break;
}
```

**Actual Behavior**:
the switch convert ```number``` to ```int``` because of ```implicit operator int(EvenOddNumber type)``` in ```SemanticType<int>```

If the cast is now ```explicit operator int(EvenOddNumber type)``` all works fine, but I don't want that.

**Expected Behavior**:
the switch shoud try first to perform a pattern matching with the actual type, and if not, then whith the implicit cast.

**Comment by gafter** [comment]
This behavior is by design. If you want to avoid that conversion, cast the switch governing expression to `object`, and then use the implicit conversion explicitly, e.g. by writing your last case to handle `EvenOddNumber`.
