### ISSUE TITLE
Remove back pointer back to Document from DocumentSpecificOptionSet

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#26307]
Right now, holding onto DocumentSpecificOptionSet will hold onto whole Roslyn solution

http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Options/OptionServiceFactory.cs,d879c3b0847aac0b,references

combined with this bug https://github.com/dotnet/roslyn/pull/26306, holding onto old option will hold onto every roslyn solution snapshots after that.

if possible, it would be good to make OptionSet leaf node in the graph without back pointer back to its parent, so that holding onto OptionSet is cheap.

...

looking at the implementation, looks like we can safely remove _document in the DocumentSpecificOptionSet.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/26309
