### ISSUE TITLE
Invalid argument check in SeparatedSyntaxList.ReplaceSeparator

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#2630]
While debugging DotNetAnalyzers/StyleCopAnalyzers#780, I discovered that `SeparatedSyntaxList.ReplaceSeparator` contains an [invalid bounds check](https://github.com/dotnet/roslyn/blob/8771786e5a80e9d27ffb40702f5cca558ca6fabb/src/Compilers/Core/Portable/Syntax/SeparatedSyntaxList.cs#L527-L530) which makes it impossible to replace a separator falling in the second half of the list of arguments.

I believe the reference to `this.Count` should actually be `nodeWithSeps.Count`.

**Comment by billsfan10** [comment]
Just ran into this.  Found a work around, but this method should work.

**Comment by jaredpar** [comment]
Assigned to @gafter for verification
