### ISSUE TITLE
async Main with multiple entrypoints

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#26315]
I have three console apps in a project with Main entrypoints. I changed one of them to be &quot;async Task Main&quot;. Now, when I go into the project properties, the one that I set to async no longer shows up in the &quot;Startup object&quot; application setting. The two that I left alone still show up.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/235706/async-main-with-multiple-entrypoints.html
VSTS ticketId: 602403_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.CSharp/ProjectSystemShim/CSharpProjectShim.ICSharpProjectSite.cs,ce3e7d81073fb9e3,references

**Comment by JieCarolHu** [comment]
I cannot repro this issue on the latest 15.7.6

![image](https://user-images.githubusercontent.com/17056651/43747770-bddff2c8-99a0-11e8-9615-b6d2b3063292.png)

**Comment by jinujoseph** [comment]
Closing this issue as no repro, pls revert if it repros with latest VS .

**Comment by sharwell** [comment]
This issue concerns this dropdown:
![image](https://user-images.githubusercontent.com/1408396/70951622-b9661380-2018-11ea-81c5-2e29ca931670.png)

**Comment by aktxyz** [comment]
in case anyone else runs into this ... you can manually add this to your csproj file and get passed this issue

```
<PropertyGroup>
   ... 
   <StartupObject>Name.Space.ClassWithMain</StartupObject>
   ...
<PropertyGroup>
```

**Comment by ismaelhamed** [comment]
VS: **16.5.0 Preview 4.0**
.NET: **4.8**

Startup object's dropdown-list doesn't work with an `async Task Main` method, it shows empty (see @sharwell comment). If I change its signature to `void Main`, then it shows up.

**Comment by JulienLynge** [comment]
Confirmed with 2019 16.4.5.

@aktxyz's solution sort of works, but when I switch between startup objects it likes to remove the async one. So it works if you're willing to go into the xml and keep pasting it - not a real solution, unfortunately.

**Comment by aktxyz** [comment]
it wouldn't be a good work around without an annoying side effect ... for the longest time I could not figure out why it kept reverting but eventually found what you found

**Comment by ghosttie** [comment]
In Visual Studio 16.9.3

```cs
public static async Task Main(string[] args) {
```

Still doesn't show up in the property page and if the csproj is edited to set `<StartupObject>` manually, there's a `CS1558	'Program' does not have a suitable static 'Main' method` error.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/75808
