### ISSUE TITLE
IntroduceLocal should rank low when invoked without selection

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26314]
In an invocation `M(2)`, place the cursor on `2` and then press `Ctrl+.`.
The `IntroduceLocal` refactorings should rank low.

![image](https://user-images.githubusercontent.com/12466233/39089232-1b59ac24-4577-11e8-9ca1-a753c42de822.png)

**Comment by CyrusNajmabadi** [comment]
What lightbulb entries would you prefer to see above 'introduce local' and why?

**Comment by jcouv** [comment]
Add argument seems more useful in this case.

**Comment by CyrusNajmabadi** [comment]
i'm not sure that i agree.  Personally, neither seem particularly more important than the other.  Curious what @DustinCampbell thinks.

However, if we did want that, we could just do that by ordering these refactorings  (not necessarily having things be low-priority).

**Comment by jcouv** [comment]
Hum, OK. It's a nit anyways. I'll close  :-)

**Comment by CyrusNajmabadi** [comment]
You don't need to close.   :)  Like i said, i dont' personally see either as more important than the other.  If you and others feel differently we could def change the ordering of these refactorings.  :)
