### ISSUE TITLE
Rename refactor forgets "Preview changes" selection (regression since VS2013)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#26319]
<p>When doing a Rename refactor, Visual Studio 2017 15.5.3 &quot;forgets&quot; my last &quot;Preview Changes&quot; preference every time. This means each time I have to take my hands off the keyboard &amp; use the mouse to manually re-check that checkbox. Very cumbersome, &amp; it did not behave this way in VS 2013 (which always remembered the last setting).</p><p></p><p>
(Note: This issue is actually with VS for Windows; however, there seems to be no way to report a problem in the appropriate Windows channel without using Visual Studio itself, and my development machine is air-gapped &amp; cannot be connected to the internet.  Thus, for lack of an apparent better option, I'm posting it here...)</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/217408/rename-refactor-forgets-preview-changes-selection.html
VSTS ticketId: 585394_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in preview changes experiences.
