### ISSUE TITLE
VB.NET: Intellisense  suggesting primitive types when searching for attributes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#26322]
When trying to apply an attribute (to property, class, function, whatever), Intellisense is also suggesting primitive types (Integer, Decimal, etc) that doesn't make any sense in this context.

I know one can hide them by checking in the approriate intellisense filtering options, but that won't persist to the next intellisense window.

It is something annoying because it pollutes the list and makes it take longer to find what is intended.

Please, see attached screenshot.
![image](https://user-images.githubusercontent.com/12449387/39092505-1b74266a-45c4-11e8-9584-543140d0fc0c.png)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/232831/vbnet-intellisense-nonsense-keyword-list-when-sear.html
VSTS ticketId: 599183_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Unlikely to make changes in these VB areas.
