### ISSUE TITLE
Improve Ctrl+F delay due to IVsLanguageBlock.GetCurrentBlock

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#2632]
I been noticing the "Determining Current Block” wait dialog once or twice a day recently (related to the recent [IVsLanguageBlock.GetCurrentBlock implementation](https://github.com/dotnet/roslyn/pull/2490)). I think I only notice it when I’ve just opened Roslyn.sln and try to find something in an open document before the solution has finished loading or very soon after it has loaded.

Let's consider ways of making this feature faster. For example, it looks like we only use the SemanticModel for making a minimal display string of the symbol at the current position, but we could probably do something reasonable syntactically if we wanted to.

**Comment by KevinH-MS** [comment]
Woops, I mentioned the wrong issue in the merge commit, but this was fixed by 7d359797705226b8cdba0ef4826dc90478c98272.

**Comment by dpoeschl** [comment]
Things have been looking better on my machine. [Waiting](https://github.com/dotnet/roslyn/pull/3331#issuecomment-112572559) for confirmation from @KevinH-MS that the RPS numbers are back in good shape, which I suspect they are. :smile:

**Comment by dpoeschl** [comment]
Kevin -- can you mark this as verified if the RPS numbers are good?

**Comment by KevinH-MS** [comment]
Yes, the RPS regression has been addressed (bug for that was resolved).
