### ISSUE TITLE
Implement interface quick fix does not add class brackets for nested types

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#26323]
**Version Used**: 2.8.0.62811 / 15.7 P4

**Steps to Reproduce**:
```C#
using System;
namespace WPFConsoleApplication1
{
    class Program
    {
        private class Test : ICloneable|

        static void Main(string[] args) { }
    }
}
```
Invoke the Implement interface quick fix.

**Expected Behavior**:
Brackets added, as in the case of top-level class:
```C#
        private class Test : ICloneable
        {
            public object Clone() => throw new NotImplementedException();
        }
```
**Actual Behavior**:
```C#
        private class Test : ICloneable
public object Clone() => throw new NotImplementedException();
```

**Comment by chborl** [comment]
I'm not able to reproduce this either.  @miloush , are you still seeing this behavior?

**Comment by miloush** [comment]
I am sorry to say but I can reproduce this on VisualStudio.15.Preview/15.9.0-pre.2.0+28107.0. I just copied & pasted the code into blank console application and invoked the quick fix for `ICloneable`:

![untitled](https://user-images.githubusercontent.com/10546952/45513113-50e31380-b791-11e8-8de2-890ad334e458.png)

**Comment by jhinder** [comment]
I still can't reproduce this, either on 15.8.4 or 15.9 Preview 2.

![qfix-ii-15_8_4](https://user-images.githubusercontent.com/823398/45516340-18503380-b7ab-11e8-9b04-4bc99346e844.PNG)
![qfix-ii-pre2](https://user-images.githubusercontent.com/823398/45516348-1ab28d80-b7ab-11e8-8d15-486fc74b846f.PNG)

I tried enabling generating expression-bodied methods in the C# style settings, still no repro (this is on 15.9 Preview 2):

![qfix-ii-pre2-exprbody](https://user-images.githubusercontent.com/823398/45516462-70873580-b7ab-11e8-8c84-38ed17bedd6b.PNG)

**Comment by miloush** [comment]
Interesting... I tried to fiddle some settings too but I couldn't get what you are seeing. Any ideas what could affect the behaviour?

![untitled](https://user-images.githubusercontent.com/10546952/45517005-61e55200-b79c-11e8-85c4-797ada33c2f5.png)

**Comment by miloush** [comment]
FYI if I turn off expression methods I still don't get the class brackets:

![untitled2](https://user-images.githubusercontent.com/10546952/45517953-652e0d00-b79f-11e8-9e7e-6a446c309a19.png)

**Comment by CyrusNajmabadi** [comment]
Can you supply all the code you had?

**Comment by miloush** [comment]
Hitting this pretty much anywhere in any project, still in VisualStudio.16.Preview/16.0.0-pre.3.0+28608.199.

I literally just create a new console project at it repros...
[DELETE26323.zip](https://github.com/dotnet/roslyn/files/2879505/DELETE26323.zip)

![image](https://user-images.githubusercontent.com/10546952/53008057-d2258d00-3438-11e9-8ae1-55c4dc630d37.png)

Attached exported vssettings too.

**Comment by miloush** [comment]
New twist:

```C#
class Program
{
    private class C : IComparer<Program>|

    int[] array = new int[4];
}
```
Invoking the implement interface (VisualStudio.16.Preview/16.0.0-pre.4.4+28721.148) results in

```C#
int[] array = public int Compare(Program x, Program y) => throw new NotImplementedException();new int[4];
```

Can anyone reproduce this one?

**Comment by jhinder** [comment]
@miloush I can reproduce half of it: the generated code is inserted at the wrong place (but that's a different issue, I suppose), but I do get the class's braces.

```c#
int[] array = {
    public int Compare(Program x, Program y) => throw new NotImplementedException();
}

new int[4];
```

**Comment by miloush** [comment]
Yeah, could be a different issue indeed. I posted my vssettings on Feb 19, does this still not help to reproduce? If not, sounds like I will have to try debugging it and pointers to where in code the brackets get inserted would be welcome.

**Comment by miloush** [comment]
@CyrusNajmabadi This never stopped reproducing for me, currently on VisualStudio.17.IntPreview/17.5.0-pre.1.0+33027.381.main, through several different computers by now. Can you point me to the code which decides whether brackets should be inserted or not? I can try to debug.

**Comment by CyrusNajmabadi** [comment]
Not repro.

![Image](https://github.com/user-attachments/assets/14a97503-00a0-4e4e-bbfd-089752bb6138)

becomes

![Image](https://github.com/user-attachments/assets/aa0e1c03-8b3f-4fe0-ad14-3eedbc8a5bdb)

**Comment by miloush** [comment]
Still very much repro on VisualStudio.17.Preview/17.13.0-pre.1.0+35507.96:

![Image](https://github.com/user-attachments/assets/525dc17a-a222-4bd3-a2b8-0d6576ee6cb8)

**Comment by miloush** [comment]
@CyrusNajmabadi as I said I am willing to look into this but I need some initial pointer where to look. I think we already established it doesn't repro for everyone, it must be some combinations of settings or something that I seem to have since beginning.

**Comment by CyrusNajmabadi** [comment]
AbstractImplementInterfaceService.ImplementInterfaceGenerator.ImplementInterfaceAsync would be a reasonable start.

**Comment by miloush** [comment]
Initial observation: the declaration node has both `OpenBraceToken` and `CloseBraceToken` at the depicted cursor location before the quick fix, they are of zero length and `IsMissing = true`. After the node is replaced with one with the added member, the `OpenBraceToken` and `CloseBraceToken` are still of zero length and with `IsMissing = true`, but the closing one is now at location after the added member.

The broken case goes through `AddMembersToEndOfDestination`, the working case goes through `AddMembersToAppropriateLocationInDestination`.

@CyrusNajmabadi can you try to repro with the add members at the end setting?

![Image](https://github.com/user-attachments/assets/0f56c29d-a94c-42de-aab5-2492ef170db7)

**Comment by miloush** [comment]
The latter calls `destination.EnsureOpenAndCloseBraceTokens()`

https://github.com/dotnet/roslyn/blob/f6143467d00e1d85d0a2ad2d339c97db1e834d52/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/CSharpCodeGenerationHelpers.cs#L79

There is no such call for `AddMembersToEndOfDestination`.

**Comment by CyrusNajmabadi** [comment]
Fixes with https://github.com/dotnet/roslyn/pull/76083

**Comment by miloush** [comment]
Yay! Thanks for not locking the issue right away.
