### ISSUE TITLE
Glyph enum doesn't contain LocalFunction

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#26327]
discovered here: https://github.com/dotnet/roslyn/pull/26165#discussion_r181797391
See https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/Common/Glyph.cs

Local functions are currently treated as private methods. They should have their own definition which should probably also be exposed in the IDE with a new icon.

![image](https://user-images.githubusercontent.com/11444821/39100211-edac9c76-4686-11e8-89f6-aa491318f7fe.png)

I suppose it could either be a completely new icon as some sort of mix between the icon for a local and a method, or just have a different "subicon" instead of the lock which repesents private: ![image](https://user-images.githubusercontent.com/11444821/39100219-0b5527ca-4687-11e8-8e9e-e651fd4ebf77.png)

**Comment by Neme12** [comment]
Looking at the pattern with other icons and assuming that square brackets represent something is "local", I imagine it could look like this:
![image](https://user-images.githubusercontent.com/11444821/39100418-886629c8-468a-11e8-9863-74fdf6b610d8.png)

**Comment by Neme12** [comment]
Note: The reason I think a separate icon would be appropriate is that if the user has a local function naming preference set to other than local variables, during a local variable declaration, it may be odd to see a method icon:
![image](https://user-images.githubusercontent.com/11444821/47316537-abe90f80-d647-11e8-9868-edc685c42a35.png)

a special icon for local functions would make this clear.

**Comment by dpoeschl** [comment]
Design Meeting Notes
- We like the idea, and can get an icon created for this. We can then surface it in the editor.

**Comment by CyrusNajmabadi** [comment]
Nice!

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement on this.
