### ISSUE TITLE
CompletionItemSelectionBehavior for LINQ methods

### ISSUE THREAD

**Issue by denisbredikhin** [dotnet/roslyn#26333]
**Version Used**: 2.7.0

**Steps to Reproduce**:

1. Call CompletionService.GetCompletionsAsync for following code: `string.Format(s`
2. Call CompletionService.GetCompletionsAsync for following code: `new[] { 1 }.Where(s`
3. Compare SelectionBehavior of all items in these two cases

**Expected Behavior**:
I expect that in first case SelectionBehavior at least for some items would be HardSelection (or Default?) and in second case - SoftSelection, because in VS if I press space after s in frist case - it commits selected value from auto-complete dropdown, while in second case not. 

**Actual Behavior**:
SelectionBehavior is default for all items.

Do I wrongly understand meaning of SelectionBehavior? If yes, can you suggest me which flag do I need to check to have the same behavior in my code editor as in VS?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this issue.
