### ISSUE TITLE
Compiler server isn't unique on *nix

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/roslyn#26338]
On non-Windows OSes, building in MSBuild can create multiple instances of the compiler server listening on the same UNIX domain socket ("named pipe").

**Version Used**: 

```
Microsoft (R) Visual C# Compiler version 2.8.0.62819 (3beafef5)
```

From .NET Core SDK build `2.1.300-preview3-008646`.

**Steps to Reproduce**:

This is probably not minimal, but it's how I encountered it:

1. `git clone --recursive https://github.com/aspnet/Universe.git --branch release/2.1`
2. `./build.sh /p:SkipTests=true /p:CI=true`

**Expected Behavior**:

A single `dotnet vbcscompiler.dll` process handling all compilation.

**Actual Behavior**:

Multiple instances of the compiler server are running:
![image](https://user-images.githubusercontent.com/3347530/39143925-dca7022c-46f4-11e8-8b76-6d470ebf7166.png)

**Comment by rainersigwald** [comment]
My first instinct was that this was related to the non-Windows behavior of the `NamedPipeServerStream` instance cap, but the compiler server doesn't use that, so it must be something to do with Linux Mutex behavior

https://github.com/dotnet/roslyn/blob/82dac747490ba681577b9d1a47524b9f4e0af137/src/Compilers/Server/VBCSCompiler/DesktopBuildServerController.cs#L101-L108

cc @jaredpar

**Comment by jaredpar** [comment]
@rainersigwald to our understanding that code should prevent us from creating multiple servers here. At least for a given pipe name and in this scenario all the pipe names are the same. 

CC @kouvel, @janvorli is our understanding of Mutex incorrect for Unix environments?

**Comment by nguerrera** [comment]
cc @kouvel based on having implemented named mutexes x-plat here: https://github.com/dotnet/coreclr/pull/5030

**Comment by kouvel** [comment]
Is the mutex name prefixed with "Global\"?
https://github.com/dotnet/roslyn/blob/88801fa234db8f1bd16b30c04971311915a04cd7/src/Compilers/Shared/BuildServerConnection.cs#L593-L596

**Comment by rainersigwald** [comment]
I think this was a PEBKAC on my part. `htop` by default displays _threads_ with full command lines, and I confused them for independent processes. Sorry for the randomization.

**Comment by kouvel** [comment]
Didn't notice the pipe name argument in the image above, it doesn't seem to have the `Global\` prefix. By default named mutexes use session scope, which are a bit different on windows and unixes. On unix each shell gets its own session, so if the `Global\` prefix is not already there you may still want to add it, that will ensure one mutex instance system-wide.
