### ISSUE TITLE
Overload resolution for Action/Func<Task> at Runtime

### ISSUE THREAD

**Issue by veler** [dotnet/roslyn#26334]
Hi,

I'm posting my problem here because it happens at runtime, but I think it's related to the following issue : #26077 
I have a similar issue than the one described above, but in my case, it builds correctly. The issue I get is at **RUNTIME**.

**Version used** 
2.7.0

**Step to reproduce**

```csharp
    internal static void Main()
    {
        // MyVoid is a void. Implictly, this lambda should be an Action.
        // But with Microsoft.CodeAnalysis.CSharp 2.7.0, it is considered as a Func at runtime.
        Run(() => MyVoid());
    }    
    
    internal static void MyVoid()
    {
    }
	
    internal static dynamic Run(System.Action action)
    {
        action(); // It doesn't go here, while in VS with .Net 4.7.1 it goes here.
        return null;
    } 
    
    internal static dynamic Run(System.Func<dynamic> func)
    {
        return func(); // Here I get "Cannot implicitly convert type 'void' to 'object'" at RUNTIME.
    } 
```

**See** [https://sharplab.io/#v2:CYLg1APgAgDABFAjAbgLAChYMQVjZgZgQCY4BhODAbwzjrgEsA7AFwFMAnJgQwBtsAbAgAs2ABwAKAJS16NdPUVwA9MrgBZAJ4A1APYNgjAM5xuIgHRwAkgFsADrwYBjFr00AaOCwAWDE724bACNgMyNvXQBXXkMgtlMmbGJzWSUVNQAhSJY4AHcGHw1nDl0jXQAzFnMyXWA2AEEeNyM/aoBlb24OOzhkgHZzGE8C4zgnXSYWuo42Q24TMygcUxyOSNYGGzYUhTS4ACV1iWk4AF4APg0dfWBpKXxFAF9FVMpdumZ2Lj5BESu9AzSV7yJ4YACQr0+nCav2Amh4NmcByOSHMSFI3BcDAmMnecBBe0xLGxTGkyHS1hywF0bCMTAA5DkAOa6ODeThsTy5Xy8eLMODaNp5AreODmABybBywnMA0QjGZNJM7JmOz2CD6cCY0V4D3oz1ekNY0J+SCEcIRSMOpNRSwAPBbAs5LuV1k5cYoCWkoJrXUwnGSKQAJDnWOBMqVwABEZG4TCYuhymwczgKbjGEwAbpwcixNHZ4vSoMJ6V5WfTdEEAFZsFz0qMrA4AVXFABUrOoAKJq/VvF7oR5AA=](url)

**Expected behavior**

1. It should build.
2. At runtime, the lambda should be considered as an Action and it should go in the FIRST "Run" method.

**Actual result**

1. It builds fine (at least there is no error).
2. At runtime, the lambda is considered as a Func<object> and it goes in the SECOND "Run" Method.
3. On the line "return func()", an Exception is throw with the message "Cannot implicitly convert type 'void' to 'object'".

Please note that I can't reproduce the same result with a Console project in VS.
Does this issue has been fixed with the changes you did with the problem described in #26077 or is it another problem to fix ?

Thanks

**Comment by svick** [comment]
Can you clarify how exactly to reproduce the issue? [Your SharpLab link](https://sharplab.io/#v2:CYLg1APgAgDABFAjAbgLAChYMQVjZgZgQCY4BhODAbwzjrgEsA7AFwFMAnJgQwBtsAbAgAs2ABwAKAJS16NdPUVwA9MrgBZAJ4A1APYNgjAM5xuIgHRwAkgFsADrwYBjFr00AaOCwAWDE724bACNgMyNvXQBXXkMgtlMmbGJzWSUVNQAhSJY4AHcGHw1nDl0jXQAzFnMyXWA2AEEeNyM/aoBlb24OOzhkgHZzGE8C4zgnXSYWuo42Q24TMygcUxyOSNYGGzYUhTS4ACV1iWk4AF4APg0dfWBpKXxFAF9FVMpdumZ2Lj5BESu9AzSV7yJ4YACQr0+nCav2Amh4NmcByOSHMSFI3BcDAmMnecBBe0xLGxTGkyHS1hywF0bCMTAA5DkAOa6ODeThsTy5Xy8eLMODaNp5AreODmABybBywnMA0QjGZNJM7JmOz2CD6cCY0V4D3oz1ekNY0J+SCEcIRSMOpNRSwAPBbAs5LuV1k5cYoCWkoJrXUwnGSKQAJDnWOBMqVwABEZG4TCYuhymwczgKbjGEwAbpwcixNHZ4vSoMJ6V5WfTdEEAFZsFz0qMrA4AVXFABUrOoAKJq/VvF7oR5AA=) shows that with Roslyn 2.7.0 the lambda is converted to `Action`, which is the behavior you want.

And if you [switch to Run mode](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIAYAEqCMBuAWACgNscBWQkgZmwCZMBhTYgb2M08wEspgBTMFACGAGzIA2bABYyADgAUASg5d2RLpswB6bZgCyATwBqAe25weAZ0zCZAOkwBJALYAHUdwDGwUYZiYwAAW3Daiwi4ARnB2VkGmEKKWkfy2UGR09qpaOnoAQhDAmADu3MEG3mCmVqYAZsD2jKZw/ACCIn5WoY0AykHCYG6YmQDs9ugBZdaYXqZQXS1g/JbCNnao5LZFkHzcLvxZGjmYAErQCsqYALwAfAYm5nDKSlSaAL6a2SxHnLwCQmJJDJ7mYLMovup3sQAJBfP6CDpAuCGEQubync64ey4BjCHzcOYqH6YSHHPHAAlQZR4XLOIpwUz8KxQADkRQA5qZMEFBPwAsUQqJUrxMMYeiUykFMPYAHL8IrSexjHA8DmMmw8paHY7YEaYKCJUSvLgfL5wvgIwG4KTI1Hos5UrEbAA8toi3jutWgXiJmlJOVQeq9UC81NpAAlec5MOz5ZgAESMYRQKCmIp7DzeMp+GZzABugiKwEMblSLNQ0hZgS5LNMkQAVvwfCz41tTgBVGUAFSc+gAotqTd9PkQ3kA==), you will see that the `Action` overload is executed.

**Comment by veler** [comment]
Oops...
After doing a more complete prototype, I realized that the issue was coming from somewhere else. Nothing to do with Roslyn...
Sorry for the inconvenient.
