### ISSUE TITLE
Code generation change regresses Xamarin applications with .NET Standard and Unsafe Code

### ISSUE THREAD

**Issue by migueldeicaza** [dotnet/roslyn#26335]
**Version Used**: 

Good version: Microsoft (R) Visual C# Compiler version 2.3.2.61928 (ec1cde8b)
Bad version: Microsoft (R) Visual C# Compiler version 2.7.0.62620 (e873e693)

**Steps to Reproduce**:

The full bug description is here:

https://github.com/mono/mono/issues/8403

Compile this code, with the old and new versions of Roslyn:

```
class  X {
    internal struct CaseRange {
        public int Lo, Hi;
        public unsafe fixed int Delta [3];

        public CaseRange (int lo, int hi, int d1, int d2, int d3)
        {
            Lo = lo;
            Hi = hi;
            unsafe {
                fixed (int *p = Delta) {
                    p [0] = d1;
                    p [1] = d2;
                    p [2] = d3;
                }
            }
        }
    }

    static void Main ()
    {
        var a = new CaseRange (0, 0, 0, 0, 0);
    }
}
```

Using the following options, to force the use of .NET Standard 1.5:

```
/noconfig /unsafe+ /checked- /nowarn:1701,1702,1705,1701,1702,2008 /nostdlib+ /errorreport:prompt /warn:4 /tmp/a.cs  /reference:/Users/miguel/.nuget/packages/system.runtime/4.3.0/ref/netstandard1.5/System.Runtime.dll
```

**Expected Behavior**:

Then try running the above with any versions of Mono, with the good version, nothing is printed out, with the bad version, the following error is displayed:

The program should run without any error messages.

**Actual Behavior**:

```
Unhandled Exception:
System.InvalidProgramException: Invalid IL code in X/CaseRange:.ctor (int,int,int,int,int): IL_001b: stloc.1   


  at X.Main () [0x00001] in <82bbf2fc97344f24920e7db85cd72ee0>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidProgramException: Invalid IL code in X/CaseRange:.ctor (int,int,int,int,int): IL_001b: stloc.1   


  at X.Main () [0x00001] in <82bbf2fc97344f24920e7db85cd72ee0>:0 
```

There might be other instances of unsafe code producing problematic code, while testing https://github.com/migueldeicaza/NStack I found this and another instance of invalid IL being produced that trigger the above exception.

There are a few guesses as to what is wrong on the Mono bug report, additionally, I noticed that the local variable signature looks wrong:

```
-               int32& pinned   V_0)
+               int32*& pinned  V_0)
```

**Comment by VSadov** [comment]
Yes the fix in #20548 introduces extra * for the pinned fixed buffers. 

On one hand pointers are all convertible to each other (that is why it works if there is no verification), 
on the other - there is no reason for this extra `*`, so fixed buffers scenario should be tweaked to not have that.

**Comment by VSadov** [comment]
Also, just FYI - in C# 7.3 this `fixed` is unnecessary. The following could work too:

```C#
                unsafe
                {
                    this.Delta[0] = d1;
                    this.Delta[1] = d2;
                    this.Delta[2] = d3;
                }
```

**Comment by marek-safar** [comment]
It's interesting that you already had tests where this issue was visible https://github.com/dotnet/roslyn/pull/20548/files#diff-81058b766239be6e9ea927f22ef45805R8199 but perhaps it was overlooked in the review.

**Comment by jaredpar** [comment]
Yes it was overlooked in the PR (at least by me). The most obvious indicator is the change to FixedSizedBufferTests.cs. The change to UnasfeTests.cs was larger and obscured the move to `&*`.
