### ISSUE TITLE
‘Add null check’ for constructor parameters doesn't notice this(…) or base(…) usages

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#26342]
VS 15.6.6

Given:

```cs
public sealed class Foo<T>
{
    public Foo(ImmutableArray<T> bar)
    {
    }

    public Foo(IEnumerable<T> bar)
        : this(bar.ToImmutableArray())
    {
    }
}
```

If you use the ‘Add null check’ action on `IEnumerable<T> bar`, this is the result:
```cs
public sealed class Foo<T>
{
    public Foo(ImmutableArray<T> bar)
    {
    }

    public Foo(IEnumerable<T> bar)
        : this(bar.ToImmutableArray())
    {
        if (bar == null)
        {
            throw new ArgumentNullException(nameof(bar));
        }
    }
}
```

I would have expected this result:
```cs
public sealed class Foo<T>
{
    public Foo(ImmutableArray<T> bar)
    {
    }

    public Foo(IEnumerable<T> bar)
        : this((bar ?? throw new ArgumentNullException(nameof(bar))).ToImmutableArray())
    {
    }
}
```

Does that make sense to do?
What if the language version is lower than 7?

**Comment by jnm2** [comment]
Refactoring to a static method is what actually happens in real life, out of necessity, but it seems like it would be helpful if the action got me this far so I can take that final step.

> Note: doing nothing also seems viable to me :)

Are you referring to throwing NullReferenceException instead of ArgumentNullException? That always strikes me as the equivalent of not using your turn signal. 😃 There might sometimes be extenuating circumstances, but either way people will perceive it as unhelpful, inept, maybe even lazy.

**Comment by CyrusNajmabadi** [comment]
> Are you referring to throwing NullReferenceException instead of ArgumentNullException? That always strikes me as the equivalent of not using your turn signal. 😃 There might sometimes be extenuating circumstances, but either way people will perceive it as unhelpful, inept, maybe even lazy.

I'm referring to having the feature just do what it does, and leaving it to the user in a situation like this to decide what would be more appropriate for this less common pattern.

**Comment by jnm2** [comment]
Oh, gotcha. I'm sorry!

**Comment by CyrusNajmabadi** [comment]
Nothing to be sorry about :)

**Comment by dpoeschl** [comment]
Design Meeting Notes:

It's not beautiful, but generating the `bar ?? throw new ArgumentNullException(nameof(bar))` syntax would be correct here, so we'd like to do it. Even if it's not the desired syntax, it alerts the user that something special has been accounted for, which they can then refactor from there. If we get enough feedback that we should do the static method approach right off the bat, then we can consider that too, but let's start with this.

**Comment by CyrusNajmabadi** [comment]
Unlikely to change anything here due to lack of feedback.
