### ISSUE TITLE
T4 Templates Intellisense/Editor support?

### ISSUE THREAD

**Issue by japj** [dotnet/roslyn#2635]
Hi, not sure if this is the right place to ask, but I was wondering if it would be possible to use Roslyn for Intellisense/Editor support for T4 Templates.

i.e. if you use c# as T4 template language, would it be possible to use Roslyn to get Intellisense both inside the T4 tags (<# #> and possibly for the generated code (if it is inside a 'normal' text block).

Or are there maybe existing ideas/plans on T4 support?

**Comment by Pilchie** [comment]
The Managed Languages team has no plans to support T4 directly, but interested 3rd parties could create a language service for T4 that hosts the Roslyn editing experience inside projection buffers in T4, similar to the way that razor and aspx work.

**Comment by japj** [comment]
Ok, thanks for the information. 
Is the razor/aspx integration for doing this available somewhere? Or is there a good sample that shows how something like this could be done?

**Comment by Pilchie** [comment]
The razor tooling is not public, but you might talk to @slaks about some of the work he did to host Roslyn in markdown editing for WebEssentials.

**Comment by SLaks** [comment]
The Razor editor, as well as my WE Markdown editor, is built on the HTMLX editor, which has its own wrapper around projection buffers (ContentTypeHandler & LanguageProjectionBuffer) that updates the projections based on source text.

You can see my [source](https://github.com/madskristensen/WebEssentials2015/tree/master/EditorExtensions/Markdown/Classify), and look at Microsoft.Web.Editor.dll in your favorite decompiler, but unless you also build on HTMLX, it won't do you much good.

You should probably use projection buffers directly, which means you'll need to update the projection mappings whenever the user adds or removes a `<# #>` block.
