### ISSUE TITLE
Bad binding redirects when referencing roslyn indirectly

### ISSUE THREAD

**Issue by jairbubbles** [dotnet/roslyn#26359]
Let's consider a simple console application called `RoslynCompiler` which compiles some C# code dynamically (using Roslyn of course).  Let's consider another console application called `Launcher` which references the first project and calls its main directly:
```csharp
namespace Launcher
{
    class Program
    {
        static void Main(string[] args)
        {
            RoslynCompiler.Program.Main(args);
        }
    }
}
```
As you might expect it will not work when running the launcher project but runs perfectly with the first project.

**Version Used**:  NuGet package 2.7.0, / VS 2017 15.6.6 / .NET Framework 4.6.1

**Steps to Reproduce**:
1.  Open the .sln in [DoubleExecutable.zip](https://github.com/dotnet/roslyn/files/1942881/DoubleExecutable.zip)
2. Run `Launcher` project

**Expected Behavior**:
You should get `"Compilation succesful!"` in console. 

**Actual Behavior**:
You get an exception on `System.IO.Compression, Version=4.1.1.0`

**Details:**

When looking at binding redirects in both output directory we see that they are really different. Also the `System.*` stub libraries (which I think are added by the .NET Standard toolchain) are not present.

- RoslynCompiler:
```xml
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.IO.Compression" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.IO.FileSystem.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Security.Cryptography.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Security.Cryptography.Algorithms" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.1.0" newVersion="1.2.1.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.IO.FileSystem" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
    </assemblyBinding>
```

![image](https://user-images.githubusercontent.com/15875066/39189355-59b8bc82-47d2-11e8-923f-330ea5bce6c6.png)

- Launcher
```xml
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.IO.Compression" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.1.0" newVersion="1.2.1.0" />
      </dependentAssembly>
    </assemblyBinding>
```
![image](https://user-images.githubusercontent.com/15875066/39188981-64b83faa-47d1-11e8-90ea-dad92d539a78.png) 

IMO we should get the same binding redirects in both folders.

NOTE : I tested with .NET Framework 4.7.1 and it's still not working but the differences are less subtle (only a difference on System.IO.Compression 4.1.1.0 vs 4.1.2.0).

EDIT:
- it works if I add `<DependsOnNETStandard>true</DependsOnNETStandard>` in `Launcher.csproj`
- it works correctly with .NET Framework 4.7.2

**Comment by jcouv** [comment]
Tagging @jaredpar for triage

**Comment by jaredpar** [comment]
How are you creating your application here? I'm unsure what RoslynCompiler is as it's not actually a type that we define.

**Comment by jairbubbles** [comment]
It's a basic compiler example using `CodeAnalysis.CSharp`, nothing fancy here. 

I don't think it's a Roslyn issue but more a .NET Standard / MsBuild issue, I' don't really know where to report it. Maybe @terrajobst can help?

**Comment by 0xd4d** [comment]
Should be moved, it's reproducible but not a Roslyn issue. I'd like this fixed as well.

**Comment by terrajobst** [comment]
I suspect the issue is that the first project doesn't reference any package so no package restore happens when the first project is built, preventing the automatic binding redirect feature from working properly.

Solutions:

* Reference Roslyn in `Launcher` by adding `<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.7.0" />` to the project file.
* Explicitly enable transitive package restore in `Launcher` by adding `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>`.
