### ISSUE TITLE
AbstractDocumentationCommentCommandHandler has hardcoded Windows line ending

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/roslyn#26358]
**Version Used**: 
Any, 2.8.0-beta2-62708-11. Commit Hash: 88b12d42989e880e935be246dba802678f4ea226

**Steps to Reproduce**:

1. Set TextBuffer option "NewLineCharacter" to "\n"
2. Type `///` above method/class
3. Observe that documentation is inserted with "\r\n"

**Expected Behavior**:
Documentation respects "NewLineCharacter" option
**Actual Behavior**:
Documentation doesn't respect "NewLineCharacter" option

Problem is at https://github.com/dotnet/roslyn/blob/aa892f0/src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs#L82

**Comment by sharwell** [comment]
💭 It's unclear why the following is excluded. The extension method appears to be accessible from this code.

https://github.com/dotnet/roslyn/blob/aa892f070fedf9672a776cd77a5ddd670a2781af/src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs#L81

**Comment by DavidKarlas** [comment]
Later I realized this is called from https://github.com/dotnet/roslyn/blob/aa892f0/src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs#L189 which has few lines lower calls like: `options.GetOption(FormattingOptions.TabSize)` so, it's pretty easy fix, just pass it as argument to `AddLineBreaks` method.

**Comment by KirillOsenkov** [comment]
@jinujoseph it would be nice to prioritize this if possible, this breaks the UX on VSMac quite a bit. Thanks!

**Comment by DavidKarlas** [comment]
@JieCarolHu FYI, I opened PR

**Comment by KirillOsenkov** [comment]
@jinujoseph
