### ISSUE TITLE
SourceBrowser (http://source.roslyn.io/) for feature branches

### ISSUE THREAD

**Issue by mvacha** [dotnet/roslyn#26360]
Is there a way (e.g. URL attribute) to switch branch in http://source.roslyn.io/ or a similar tool to effectively browse the Roslyn source but with support for feature branches? Thanks.

**Comment by jaredpar** [comment]
There is no way to do this to my understanding. The page isn't actually owned by this repository, it lives here

https://github.com/KirillOsenkov/SourceBrowser
