### ISSUE TITLE
Unused property collection in MsBuild workspace

### ISSUE THREAD

**Issue by weltkante** [dotnet/roslyn#2636]
In the [MsBuild ProjectFileLoader.LoadProjectAsync](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Desktop/Workspace/MSBuild/ProjectFile/ProjectFileLoader.cs#L44) the global settings are extended by two special settings:

``` csharp
var properties = new Dictionary<string, string>(globalProperties ?? ImmutableDictionary<string, string>.Empty);
properties["DesignTimeBuild"] = "true"; // this will tell msbuild to not build the dependent projects
properties["BuildingInsideVisualStudio"] = "true"; // this will force CoreCompile task to execute even if all inputs and outputs are up to date
```

[further down in the function](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Desktop/Workspace/MSBuild/ProjectFile/ProjectFileLoader.cs#L58) they are never used.

``` csharp
return new MSB.Evaluation.Project(
    xml,
    globalProperties, // <--- shouldn't this be >> globalProperties: properties << or just >> properties << ?
    toolsVersion: null,
    projectCollection: collection);
```

If the special settings are no longer relevant they should be removed or a comment should be added why they are not used. If its a bug and they are actually needed it should be fixed :-)

**Comment by pharring** [comment]
@Pilchie @mattwar this is interesting. Does the Visual Studio language service go through this code path? If so, I'm surprised we haven't noticed it before.

**Comment by Pilchie** [comment]
Tag @jasonmalinowski too.  This code is not used by VS, but VS *does* set those flags when building to get references.

@mattwar Do you know why we're not passing them in `MSBuildWorkspace`?

**Comment by jasonmalinowski** [comment]
This was probably an oversight during some edit or refactoring. Strictly neither of those flags are necessary -- the process will work (perhaps slower, or with strange edge cases) regardless.

**Comment by mattwar** [comment]
Those properties are meant to be passed in, so this is a bug.
