### ISSUE TITLE
open document doesn't get DocumentClosed events when solution is closed while file is open in editor

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#26377]
this is happening since PushingChangesToWorkspace  set to false, before OnBeforeLastDocumentUnlock for open files gets all remaining locks to become 0.

basically that causes workspace to not raise DocumentClosed event and anything that expects Open/Close pair gets into unknown state.

I went through ones that subscribe to Workspace.DocumentClosed events and most of them seems can get into broken state. (index is broken now, can't link references) but most of them also do this stop bleed thing that if solution is closed, clear all states about open file except one (EditorConfigDocumentOptionsProvider)

for EditorConfigDocumentOptionsProvider, it will leak all those open files and its state that solution got closed before open file is closed.

not sure what is right fix for it.

**Comment by heejaechang** [comment]
tagging @jasonmalinowski since he is expert on workspace events and etc.

**Comment by heejaechang** [comment]
@jinujoseph this is leak. we should fix it . can't be unknown.

**Comment by heejaechang** [comment]
@jinujoseph this should be fixed for 15.8

EditorConfigDocumentOptionsProvider is leaking context task for open files if solution is closed without closing files first.

**Comment by heejaechang** [comment]
@jinujoseph I think @jasonmalinowski is expert on how this should work. I didn't attempt to make fix since things around PushingChangesToWorkspace is very delicate and can have quite bit of impact on system. (pushing changes from project system to roslyn workspace)

**Comment by jinujoseph** [comment]
fixed via #27561

**Comment by heejaechang** [comment]
@jinujoseph what @sharwell did is a work around of the root issue (this issue). actual fix should be done in workspace to make sure it raise document closed events when its owning project/solution is gone/removed.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
