### ISSUE TITLE
Needs to decide what VisualStudioWorkspaceImpl.GetFilePath() should do when documentId not exists

### ISSUE THREAD

**Issue by JieCarolHu** [dotnet/roslyn#26376]
It silently returns null right now when it cannot get back document from the given documentId.

It should either throw exception and make sure all the callers catch exceptions. Or it should be replaced by TryGetFilePath() which return bool to tell if the path exists.

This is part of the  discussion in https://github.com/dotnet/roslyn/issues/18199

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
