### ISSUE TITLE
Bad indentation of LINQ queries when using tab indentation

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#2638]
When writing the Linq query below, pressing enter after the "from arg" expression results in the caret being indented too much for the second line. After typing the second line, the third line is correctly indented with respect to the first line. 

```csharp
using System.Linq;

namespace ConsoleApplication2
{
	class Program
	{
		static void Main(string[] args)
		{
			var foo = from arg
						  in args
					  select arg;
		}
	}
}
```

As you're fixing this, please consider the discussion in DotNetAnalyzers/StyleCopAnalyzers#730 where we discuss how proper use of tabs and spaces for indenting multi-line statements allows tabs to look good no matter what the tab width is.

**Comment by Pilchie** [comment]
Though I know this is frustrating, this is only with the non-default option to use tabs, and also only on enter, it doesn't affect format document if you fix the indentation manually.

**Comment by Pilchie** [comment]
Actually - this isn't related to tabs after all.  It's just that the indenter does the wrong thing after the expression in a from clause.

**Comment by DustinCampbell** [comment]
This no longer seems to repro. Probably needs a regression test.

**Comment by Pilchie** [comment]
This only repros when initially typing the statement.  If the `in` is already present, it indents as you would expect.
