### ISSUE TITLE
IDE0017 does not work correctly when statements are repeated

### ISSUE THREAD

**Issue by IanKemp** [dotnet/roslyn#26385]
**Version Used**: Visual Studio 2017 Enterprise 15.6.6

**Steps to Reproduce**:

```csharp
class Demo
{
    public int A;
    public int Be;
    public int Cee;
}

class Program
{
    static void Main(string[] args)
    {
        var z = new Demo(); // IDE0017

        z.A = 1;
        z.A = 1;
        z.Be = 2;
        z.Cee = 3;
    }
}
```

**Expected Behavior**:

```csharp
class Program
{
    static void Main(string[] args)
    {
        var z = new Demo
        {
            A = 1,
            Be = 2,
            Cee = 3
        };
        z.A = 1;
    }
}
```

**Actual Behavior**:

```csharp
class Program
{
    static void Main(string[] args)
    {
        var z = new Demo
        {
            A = 1
        };
        z.A = 1;
        z.Be = 2;
        z.Cee = 3;
    }
}
```

The behaviour could be improved further by first analyzing if the RHS of an assignment is a constexpr, and if that assignment is repeated, discard all repetitions before running IDE0017. In this case, it would discard the second `z.A = 1`:

```csharp
var z = new Demo
{
    A = 1,
    Be = 2,
    Cee = 3
};
```

However I'm not sure if it's worthwhile adding this into IDE0017. If not, an analyzer to detect repeated "constexpr assignments" would be a nice addition (in the given example, it would trigger on the second `z.A = 1` line).

**Comment by sharwell** [comment]
The expected behavior here is the following:


```csharp
class Program
{
    static void Main(string[] args)
    {
        var z = new Demo
        {
            A = 1,
        };
        z.A = 1;
        z.Be = 2;
        z.Cee = 3;
    }
}
```

Additional notes:

* Property assignments are not reordered by this analyzer
* It's not safe to assume property setters are idempotent, so even if the right hand side is constant duplicate value assignments cannot be removed

**Comment by sharwell** [comment]
I just realized that what I listed as the expected behavior is the same as the code listed in the original comment as the actual behavior. 😃

**Comment by IanKemp** [comment]
@sharwell And what about an analyzer to warn about code in the form:

```csharp
z.A = 1;
z.A = 1;
```

which, in my experience, is almost always a copy-paste error and not intentional?
