### ISSUE TITLE
Remove ResettableDelay type

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#26397]
we have resettableDelay type. I think it is fine but some believe we should not use it. so we should decide either keep it or get rid of it and clean up our code.

**Comment by CyrusNajmabadi** [comment]
That's not an accurate representation of what i was saying.  I was specifically sayign that the usage of this type in pr  #26386 seemed unnecessary and overly complex.  I did not ask you to remove the type entirely.  Merely that you go with the simplest and more idiomatic approach to solving hte problem in that PR.

**Comment by CyrusNajmabadi** [comment]
> and clean up our code.

This is my main concern.  It is not clear to me why an approach was taken in that PR that introduced something that needs to be cleaned up.  I would prefer an appraoch that is just clean to begin with.  I would feel differently if that code *already* was using ResettableDelay.  But it is not.  As such, the main question is: should it be using that type or not.  That decision can be made in the PR, and we do not need a tracking issue to discuss things that can be part of the main discussion.

**Comment by heejaechang** [comment]
I think it is fine. but opened tracking issue since there was disagreement so that people can say their opinion. if people is +1 on not using it then we will remove the type. if people is okay to having the type, then should be fine when it can be used.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
