### ISSUE TITLE
Intellisense doesn't suggest accessible private fields

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#2639]
Consider the following code with `$` representing the caret location: 

``` csharp
    class Outer
    {
        private string _data;

        class Inner  : Outer
        {
            void M()
            {
                Console.WriteLine(_da$);
            }
        }
    }
```

In this location the field `_data` is accessible even though private.  Yet this field is not included in the intellisense suggestion list.  

VS 2013 does show `_data` in the completion list here.

**Comment by cston** [comment]
See https://github.com/dotnet/roslyn/pull/3282 for fix in stabilization branch.
