### ISSUE TITLE
RecoverableSyntaxTrees do not support attaching diagnostic options

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#26391]
A new API has been added to attach diagnostic options to syntax trees, but right now only ParsedSyntaxTrees actually support creating trees with diagnostic options. If workspaces need to create RecoverableSyntaxTrees with diagnostic options, we'll need to add an API to attach diagnostic options.

**Comment by agocke** [comment]
See https://github.com/dotnet/roslyn/pull/25964

**Comment by CyrusNajmabadi** [comment]
Hey Andy, can you explain the design here?  I thought the diagnostic options were  going to travel along with teh ParseOptions.  Did htat change?  If so, why?  It seems very strange to have multiple ways for options that affect parsing results to flow in.

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski on this as this is pretty core workspace model stuff.

**Comment by jasonmalinowski** [comment]
@agocke What's the next step here? Is this requiring an API from you first or it's just a matter of us keeping the data around on our side?

**Comment by agocke** [comment]
I expect this will be part of the Workspaces integration work. I don't expect any new compiler APIs will be needed, it's just making sure the workspace doesn't drop the information.
