### ISSUE TITLE
Don't get offered to generate a field in a lock statement

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#26406]
``` C#
        private void Unregister(Task task)
        {
            lock (_lock)  < --- CTRL+.
            {
                _tasks.Remove(task);
            }
        }
```

Expected: Get offered to generate a field of type "object"
Actual:

![image](https://user-images.githubusercontent.com/1103906/39289980-62419c66-4971-11e8-9cdb-bbf47a351d1a.png)

**Comment by davidwengier** [comment]
I've had a go at fixing this, and hopefully will have a PR ready soon. I've been able to create failing tests, and fix those tests, and verify that VB is not affected (in SyncLock), just dealing with an issue where intellisense isn't popping up at all when debugging.

If there are any tips around debugging that scenario I'd love to hear them, as my breakpoints aren't binding successfully at the moment.

**Comment by davidwengier** [comment]
Worked it out, was running the wrong startup project. Helps to read the docs :)
