### ISSUE TITLE
Crash in AnalyzerDriver

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#26411]
Got it reported but I'm not sure how to reproduce - from source review I do not have any explanation for the exception:

Here is the original report:

https://github.com/mono/monodevelop/issues/4673

Is that bug known/did that get fixed in a newer version ?

**Comment by Therzok** [comment]
I think this bug got fixed via https://github.com/dotnet/roslyn/pull/25496

**Comment by CyrusNajmabadi** [comment]
Haven't gotten any more reports on this.  Closing out.
