### ISSUE TITLE
Error list showing fixed errors.

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#26419]
**Version Used**: 
VS 2017 15.6.6
New csproj netstandard1.3 project.

**Steps to Reproduce**:

Not sure about the steps but it is pretty common for the error list to be in weird state.

![animation](https://user-images.githubusercontent.com/1640096/39323239-50878ed4-498c-11e8-9ecd-66b3d1dba370.gif)

**Comment by CyrusNajmabadi** [comment]
Tagging @heejaechang @mavasani The basic issue @JohanLarsson is seeing is that errors do not go away, even for open files.  He does not have FSA on.

Note that you can see the ellipses in "error list ...", meaning that analysis is never finishing.  According to him, this is not a large project.  So something appears to be getting "stuck" and diagnostics never update or clear.  

Have you guys seen any bugs like this?  If not, what do you need from @JohanLarsson to be able to narrow down what's going on?

**Comment by JohanLarsson** [comment]
[This](https://github.com/GuOrg/Gu.Analyzers/commit/b78dc21ba004be3aaf7b8d9eab2dbb863250711c) is the project but the issue is not unique to that project. The project is really small, just 100 or so classes.

**Comment by JohanLarsson** [comment]
I was using resharper with full sln analysis when it happened.
I'll include disable resharper, build output and a rebuild in the gif next time.

**Comment by CyrusNajmabadi** [comment]
thanks!

**Comment by JohanLarsson** [comment]
What is a design time build?

**Comment by heejaechang** [comment]
design time build - https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md

**Comment by heejaechang** [comment]
@JohanLarsson can you actually copy and paste content of output window here? git doesn't show most of actual content.
 also can you do same for entries in error list? just select or and paste here.

also, can you move to latest VS? looks like you are using a version of VS which had error  list "..." bug which it didn't clear it up when error list is done changing.

**Comment by JohanLarsson** [comment]
I'll close the issue if there is a bugfix in the latest version.

**Comment by heejaechang** [comment]
@JohanLarsson I don't know whether the fix is related to yours or not. please re-open if you had change to try on new version and if it still repro.
