### ISSUE TITLE
Clarify assert assumptions in BetterFunctionMember<TMember> with a comment.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#2641]
See discussion in https://github.com/dotnet/roslyn/pull/2573

**Comment by gafter** [comment]
This is regarding the line

```cs
Debug.Assert(considerRefKinds || Conversions.ClassifyImplicitConversion(type1, type2, ref useSiteDiagnostics).Kind != ConversionKind.Identity);
```

The desired comment is something like

> If considerRefKinds is false, conversion between parameter types isn't classified by the if condition. This assert is here to verify the assumption that the conversion is never an identity in that case and we can skip classification as an optimization.
