### ISSUE TITLE
Remember "Navigate to decompiled sources" user agreement

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#26415]
**Version Used**: 15.7

**Steps to Reproduce**:

1. Enable "Navigate to decompiled sources"
2. Press <kbd>F12</kbd> to navigate to a symbol in metadata
3. Accept the license agreement
4. Restart Visual Studio and repeat the steps above

**Expected Behavior**:

During step 4, the disclaimer should not be shown. In particular, a value of Accept should be remembered in the following conditions:

1. The disclaimer was accepted for the current solution
2. Step 1 was completed on the current machine

The value of accept could be stored in the .suo file to meet the above conditions. If stored in the VS profile somewhere, roaming for the option should be explicitly disabled.

📝  The above design has been approved by legal. Deviations from the above may require separate approval and could delay the work, so at this point the issue is considered a "task" more than a discussion.

**Actual Behavior**:

The disclaimer acceptance state is reset every time Visual Studio is launched.

**Comment by nvmkpk** [comment]
Why should it be on per solution basis? If it is stored in user's visual studio profile that would be great but at least it should be stored in the machine.

**Comment by sharwell** [comment]
> Why should it be on per solution basis? If it is stored in user's visual studio profile that would be great but at least it should be stored in the machine.

I know it's not particularly satisfying, but nevertheless the answer to your question is: because this is what we were told to use by legal.

**Comment by siegfriedpammer** [comment]
I would like to fix this next.

> The value of accept could be stored in the .suo file to meet the above conditions.

I cannot seem to find the appropriate `OptionStorageLocation` for suo files... can somebody please point me in the right direction? Thank you very much!

**Comment by tomkuijsten** [comment]
Did anyone notice that it doesn't matter if you agree or not, you always get the decompiled sources.
