### ISSUE TITLE
Decompiled code is missing backing field attributes on auto properties

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#26422]
**Version Used**: VS 15.7 Preview 5 (2.8.0.62825)

**Steps to Reproduce**:

1. Enable the decompiler feature.
2. Generate a class library from the code below.
3. Reference the generated binary from another project.
4. Write `new Repro.Test().Prop`, put the caret on `Prop` and hit <kbd>F12</kbd>.
5. Accept the licence agreement for the decompiler.

Both projects were configured to use C# 7.3.

```c#
using System;

namespace Repro
{
	public class Test
	{
		[field: Obsolete("Field")]
		[property: Obsolete("Property")]
		public int Prop { get; set; }
	}
}
```

**Expected Behavior**: The disassembled code shows both attributes, with the decompiled code looking similar to the code above.

**Actual Behavior**: Only the property attribute is there. The backing field attribute does not appear in the code.

**Comment by siegfriedpammer** [comment]
See https://github.com/icsharpcode/ILSpy/issues/829 -- the decompiler does not yet support this language feature. We're working hard to catch up as soon as possible.

**Comment by jinujoseph** [comment]
This will be automatically included when we update to an  ILSpy version that supports it.
