### ISSUE TITLE
C# invertif - some trivia on double parentheses is discarded

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#26427]
**Steps to Reproduce**:

1. Create a C# console app and copy/paste this code:
`if (/*1*/(/*2*/a/*3*/)/*4*/) { a(); } else { b(); }`

2. Put cursor on `if` and choose `invert if` refactoring

**Expected Behavior**:
`if (/*1*/(/*2*/!a/*3*/)/*4*/) { b(); } else { a(); }`

**Actual Behavior**:
trivia 2 and 3 are removed:
`if (/*1*/!a/*4*/) { b(); } else { a(); }`

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.
