### ISSUE TITLE
Add `IOperation CreateLazyOperation(BoundExpression exprOpt)` helper method

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#26435]
Add `IOperation CreateLazyOperation(BoundExpression expr)` helper method to `CSharpOperationFactory` and replace instances of `new Lazy<IOperation>(() => Create(expr))`. The helper could avoid creating a `Lazy<IOperation>` instance if `expr is null`, and would reduce the number of closure classes and delegate instances created.

Same comment for `VisualBasicOperationFactory`.

**Comment by CyrusNajmabadi** [comment]
@333fred do we still need this?  we're not lazy in iop anymore right?

**Comment by 333fred** [comment]
We are not.
