### ISSUE TITLE
Decompilation does not support "collapse to definitions"

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#26436]
For example, Decompile "ImmutableArray".  Now try to collapse to definitions.  The option is in the menu, but it has no effect.  This makes decompile a pretty poor MAS replacement as it's super hard to actually get a sense of all the structure of the type.

What is also weird is that some things are collapsed in the decompile view.  For example:

![image](https://user-images.githubusercontent.com/4564579/39327575-49f64a40-494d-11e8-8451-4aa4bfb69298.png)

The attributes are collapsed.  **However**:

1.  The comments are **not** collapsible.
2. Class bodies and method bodies are **not** collapsible.

I actually have no idea what's going on, but it's not good :)

**Comment by CyrusNajmabadi** [comment]
Also: disabling "navigate to external sources" has no effect.  Even if i disable it, if i try to go back to ImmutableArray, it takes me back to this file.

**Comment by CyrusNajmabadi** [comment]
Tagging @sharwell . This is related to: dotnet/roslyn#26426

Namely that decompilation should not hijack MAS while the experience is so jarringly poor (comparatively).

**Comment by CyrusNajmabadi** [comment]
Here is the experience i get with MAS:

![image](https://user-images.githubusercontent.com/4564579/39327752-cfc44dfc-494d-11e8-8f69-ee5d895c8bad.png)

I would love if we could be very close to that, just with actual decompiled code.

**Comment by siegfriedpammer** [comment]
I just discovered the following difference between decompiler output and metadata output:

Decompiled view:
![grafik](https://user-images.githubusercontent.com/344204/40105996-de3d7474-58f4-11e8-8caa-706336184d9a.png)

Metadata view:
![grafik](https://user-images.githubusercontent.com/344204/40106277-9bd16ad6-58f5-11e8-9418-5382dc590c57.png)

Notice that metadata view uses normal one line comments for the documentation vs. the decompiler generates standard XML doc comments. Uncollapsing the region at the top, it can also be seen that multiple lines of single line comments are folded even in the decompiler view.

Question: Can we change the VS to fold XML doc comments as well? If so, where would I have to look at? XML docs are folded in normal user code, so what/where is the difference in MetadataAsSourceService? Any pointers in the right direction would be very welcome.

Another solution would be to change the decompiler to format the XML doc the same way it is done in metadata view.

**Comment by siegfriedpammer** [comment]
Also: The MetadataAsSourceService might need some additonal work to properly fold method body blocks. It seems that it uses a stripped down version, which cannot deal with block statements and documentation comments. After that is fixed, it should be quite pleasant to look at the decompiled source code.

Any pointers in the right direction (area of Roslyn) would be much appreciated!

**Comment by siegfriedpammer** [comment]
https://github.com/dotnet/roslyn/blob/f1b10f7afdbe87d9a244e3330fb57b356494ea90/src/Features/Core/Portable/Structure/Syntax/AbstractSyntaxNodeStructureProvider.cs#L52

I think we'd either have to implement some more `AbstractMetadataAsSourceStructureProvider`s specifically for the `MetadataAsSource` workspace to add the missing features (but this might alter the behavior of plain old metadata view), or we declare the decompiled sources as a different workspace?

Which solution is preferred?

**Comment by CyrusNajmabadi** [comment]
Closing out as the experience is much improved.
