### ISSUE TITLE
Migrate indent guides from IBlockTag to IStructureTag

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#26445]
Roslyn is currently using IBlockTag's, which were introduced in 15.0, but quickly realized to be inadequate for braced languages, and supplanted by StructureTags.

Roslyn's usage of the API also does not follow the API contract, requiring a [Roslyn special case in the editor code](https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform?path=%2Fsrc%2FEditor%2FText%2FImpl%2FStructure%2FLegacy%2FLazyTranslatedStructureTag.cs&version=GBmaster&_a=contents&line=51&lineStyle=plain&lineEnd=55&lineStartColumn=1&lineEndColumn=143). This incorrect usage is the root cause behind #24067.

StructureTag is more or less a superset of IBlockTag that allows the implementer to continue using the same heuristics to position the indent guides or explicitly specify the X position and Y extent relative to characters in the buffer. Using this API, you should be able to address 

[StructureTag is now roughly documented](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.tagging.structuretag?view=visualstudiosdk-2017) on MSFT docs. I am looking to improve the docs with my notes in my spare time.

#16395 can be fixed by correctly fulfilling the API contract or by specifying the absolute position of the guide rather than using the heuristics.

Roslyn is the last holdout on IBlockTags, so migrating off it would allow it to be removed.

**Comment by CyrusNajmabadi** [comment]
@gundermanc Can you clarify this bit: r by specifying the absolute position of the guide rather than using the heuristics.

From our previous conversations, i pointed out that this is not something that roslyn seems able to do.  because it requires roslyn to understnad things like like "what column is this position at".  i.e. *very* view-oriented concepts that actual roslyn stream-oriented languages have no concept of.

From talking earlier, it sounded like the right fix was to always look at the two columns *in the view* and just always pick the *left-most* one.  This is something the view-oriented code can hopefully do trivially.

Is that not feasible here?

**Comment by CyrusNajmabadi** [comment]
> Roslyn is the last holdout on IBlockTags, so migrating off it would allow it to be removed.

Note: tihs is non trivial for roslyn to do.  Either we have to come up with a new API for all our client languages to use (and we have to figure out how they solve the "where should the line go" problem), and get them all to update.

Or, we just use IStructureTag without updating out client api, but we still need an appropriate heuristic in place in the editor side to handle where to draw things.  Note: from our previous discussion we talked about all different kinds of code constructs, xml, and other forms.  From our talk, it looked like the "pick the leftmost of hte two points" approach would work for all of them.

Do you have an actual code construct where that would be incorrect?  I don't even view it as a heuristic.  It just seems like what the actual view of a block is that has a start/end that is unaligned.  After all, if you pick the *rightmost* line, then you will intersect with the contents of hte block.  That just seems busted.

**Comment by sharwell** [comment]
📝 When this feature is implemented, the heavy lifting should be out-of-process.
