### ISSUE TITLE
IntelliSense incorrectly attempts to disambiguate generic arguments when they clash with a member

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#2644]
Given the following:

``` C#
using System.Collections.ObjectModel;

namespace ConsoleApplication34
{
    class Program
    {
        public static ReadOnlyCollection<Bar> Bar
        {
            get;
        }

        static void Main(string[] args)
        {
            Bar = new 
        }
    }

    class Bar
    {
    }
}
```

IntelliSense incorrectly attempts to disambiguate the `Bar` type in the `ReadOnlyCollection<ConsoleApplication34.Bar>` suggestion. It appears to do this because it thinks there is a clash with the `Bar` property.

![image](https://cloud.githubusercontent.com/assets/1103906/7572788/b2381010-f7d5-11e4-85d4-98b847637565.png)

After this, you are immediately asked to simplify the expression:

![image](https://cloud.githubusercontent.com/assets/1103906/7572891/6c9e03d8-f7d6-11e4-802f-fda64b049a8d.png)

**Comment by davkean** [comment]
Make note, while the code doesn't actually compile above (it was a faked up example) - you can repro this with code that does compile. :)

**Comment by Pilchie** [comment]
This may be an issue with `ToMinimalDisplayString`

**Comment by Pilchie** [comment]
Assigning to @rchande to track the PR.
