### ISSUE TITLE
Flaky integration test VisualBasic.BasicWinForms.ChangeControlPropertyInCode

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#26444]
**VisualBasic.BasicWinForms.ChangeControlPropertyInCode** [failed](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/915/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicWinForms/ChangeControlPropertyInCode/) in debug on a non-code PR (https://github.com/dotnet/roslyn/pull/26416) with the following message:

**Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.ChangeControlPropertyInCode** (from Roslyn.VisualStudio.IntegrationTests)

Failing for the past 1 build (Since Failed#915 )
Took 2.7 sec.
Stacktrace
MESSAGE:
Assert.Contains() Failure
Not found: `Me.SomeButton.Text = "ButtonTextGoesHere"`
In value:
```VB
<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class Form1
 Inherits System.Windows.Forms.Form

 'Form overrides dispose to clean up the component list.
 <System.Diagnostics.DebuggerNonUserCode()> _
 Protected Overrides Sub Dispose(ByVal disposing As Boolean)
  Try
   If disposing AndAlso components IsNot Nothing Then
    components.Dispose()
   End If
  Finally
   MyBase.Dispose(disposing)
  End Try
 End Sub

 'Required by the Windows Form Designer
 Private components As System.ComponentModel.IContainer

 'NOTE: The following procedure is required by the Windows Form Designer
 'It can be modified using the Windows Form Designer. 
 'Do not modify it using the code editor.
 <System.Diagnostics.DebuggerStepThrough()> _
 Private Sub InitializeComponent()
  components = New System.ComponentModel.Container()
  Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
  Me.ClientSize = New System.Drawing.Size(800, 450)
  Me.Text = "Form1"
 End Sub

End Class


```
+++++++++++++++++++
STACK TRACE:
at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.ChangeControlPropertyInCode()

**Comment by JoeRobich** [comment]
Saw this again: [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=123658&view=ms.vss-test-web.build-test-results-tab)

**Comment by sharwell** [comment]
@JoeRobich will make a new issue for this
