### ISSUE TITLE
Finalize API for syntax tree diagnostic options

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#26453]
In the current implementation of https://github.com/dotnet/roslyn/pull/25964 there are no methods on SyntaxFactory for passing diagnostic options to trees being created. We should consider whether those are desired and add them if so.

**Comment by jasonmalinowski** [comment]
@agocke Any further work we need to do here?

**Comment by jasonmalinowski** [comment]
I think I hit this in #36903 as I had to switch from calling `SyntaxFactory.*` to `CSharpSyntaxTree.Create*` but I'm not really sure I care.

**Comment by agocke** [comment]
I think this is fine
