### ISSUE TITLE
IntroduceLocal should use a shared helper to convert expression body to block

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#26456]
There should be a shared helper to convert expression bodied constructs to blocks and vice versa, which would be used by the "Use expression/block body" feature itself and other features that need to do this instead of duplicating the logic. See:
https://github.com/dotnet/roslyn/blob/6ba92843d89d90576403c75856c21f27488d1b65/src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs#L193

Right now the code is simple enough to not be a big problem but we definitely need to do this so that bugs like #25202 can be fixed easily across all features, and have a consistent behavior.

**Comment by CyrusNajmabadi** [comment]
If someone wants to do this as part of normal work/cleanup, they're welcome to.  We don't really need a tracking bug saying something can be cleaned up.
