### ISSUE TITLE
Don't offer invertif in single line lambdas

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#26454]
Per feedback on #25233:

VB invert if handles special cases such as:
`Dim x = Sub() If True Then Dim y Else Console.WriteLine(), z = 1'
by adding parentheses.
`Dim x = (Sub() If False Then Console.WriteLine() Else Dim y), z = 1`

C# doesn't have this code so we either need to add it or not offer to invert single-line ifs in single-line lambdas.

**Comment by Neme12** [comment]
Maybe I'm missing something... but what does this look like in C#? Are you talking about the conditional operator? Or an if statement inside braces?

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.
