### ISSUE TITLE
Assertion hit in  MakeTestsAndBindings

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26467]
```C#
                    Debug.Assert(recursive.HasAnyErrors); // line 451
```

![image](https://user-images.githubusercontent.com/12466233/39390934-df9d446e-4a50-11e8-9bea-b190fbc20f7e.png)

I think the assertion is reached before I typed the last character, so it would be `_ = a is ()`.

![image](https://user-images.githubusercontent.com/12466233/39390967-696bb7ac-4a51-11e8-9269-2fbd31819256.png)

Tagging @gafter

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/26481
