### ISSUE TITLE
IDE formatting issues with switch expression

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#26479]
This refers to the prototype on the `features/recursive-patterns` branch.

Typing the following character by character

``` c#
            var q = o switch{1=>2,3=>4};
```

Results in

``` c#
            var q = o switch
            {
            1 => 2, 3 => 4
            };
```

Rather than the desired

``` c#
            var q = o switch { 1 => 2, 3 => 4 };
```

**Comment by CyrusNajmabadi** [comment]
@jcouv You will likely need to have formatting add suppression info if the construct is on a single line.  That's what we do for most block-like constructs.

**Comment by jcouv** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/26555, and included in the BUILD demo (`features/build-demo`).
