### ISSUE TITLE
Feature request: Conversion.IsRepresentationPreserving

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#26471]
When analysing WPF where most things are object I miss this property on `Conversion`

Simple example:

```cs
    public sealed class FooControl : Control
    {
        public static readonly DependencyProperty ValueProperty = DependencyProperty.Register(
            nameof(Value),
            typeof(double),
            typeof(FooControl),
            new PropertyMetadata(1));

        public double Value
        {
            get => (double)this.GetValue(ValueProperty);
            set => this.SetValue(ValueProperty, value);
        }
    }
```

`PropertyMetadata(1)` will throw at runtime as the boxed `int` cannot be cast to `double`. There are of course more places than WPF where this information can be used and it feels reasonable that Roslyn has API here.

**Comment by JohanLarsson** [comment]
`Conversion.IsRepresentationPreserving` would return true if a boxed value can be cast to the destination type. [Here](https://blogs.msdn.microsoft.com/ericlippert/2009/03/19/representation-and-identity/) is a blog by Lippert on the subject.

**Comment by CyrusNajmabadi** [comment]
@JohanLarsson How is this different from just getting the type of the conversion and seeing if it's explicit numeric conversion?

> Conversion.IsRepresentationPreserving would return true if a boxed value can be cast to the destination type. 

How would hte language know?  I presume that "this.GetValue" returns an object.  How would the compiler know if that object could be cast to "double" without throwing or not?  The purpose of hte cast is that *you* are telling the compiler this is safe.  If the compiler could tell if this was a problem it would either disallow this, or give you a warning about what you were doing.

**Comment by JohanLarsson** [comment]
We know more than the compiler here: `(SomeType)(object)expression`. We know that `expression` will be boxed and then cast to `SomeType`.
