### ISSUE TITLE
"Introduce local" moves expression that uses an expression variable before its declaration

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#26473]
Start with
```c#
class C
{
    bool M(object o)
    {
        return o is int i && i > 0;
    }
}
```
or
```c#
class C
{
    bool M(string s)
    {
        return int.TryParse(s, out var i) && i > 0;
    }
}
```
and use "Introduce local" on `i > 0`. This results in an error:
```c#
class C
{
    bool M(object o)
    {
        bool v = i > 0; // error CS0841: Cannot use local variable 'i' before it is declared
        return o is int i && v;
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Note: there's a certain point at which we have to consider that these features are just to enable users to move code around easily.  If the user says they want a local, sometimes we should just give them a local, and let them do whatever they want withthe code to get it into the shape they actually want.

**Comment by Neme12** [comment]
I agree, I don't know that there's anything we can do here. But at the very least I think we should show that something is wrong.

**Comment by Neme12** [comment]
Unless we want to generate this :smile:
```c#
using System;

class C
{
    bool M(object o)
    {
        return o is int i && ((Func<bool>)(() => {
            bool v = i > 0;
            return v;
        }))();
    }
}
```

**Comment by CyrusNajmabadi** [comment]
:shipit:

**Comment by CyrusNajmabadi** [comment]
> I agree, I don't know that there's anything we can do here. But at the very least I think we should show that something is wrong.

That's fair.  It seems like a simple check of the dest location against the declaration location, with a  warning/error annotation would be a good idea.

**Comment by CyrusNajmabadi** [comment]
> Question: why is this marked as a feature request?

Because it's a feature request :)  

This is not considered a bug (to me at least).  Introduce local is simply trying to help you speed things up here.  Perhaps you intend to make several other changes.  We'd rather have the feature and allow you to still do things quickly, even if it's part of several changes you might want to do.  It's better than not having it avialable and confusing you as to why that is.

**Comment by Neme12** [comment]
But I'm not requesting any feature. I'm just calling out an odd behavior. There's no actual feature that I'm requesting. As I said, I don't know what the right thing to do here is.

**Comment by Neme12** [comment]
> Because it's a feature request

Which feature do you have in mind then?

**Comment by CyrusNajmabadi** [comment]
The feature request is to make any change in behavior to the feature.    Most probably, if anything were to be done here, it would be to simply have a warning/error int he preview that the local will move before the declaration point.

**Comment by Neme12** [comment]
I'm not requesting any changes in behavior. I'm simply reporting an odd behavior that I think might be a bug, but don't know whether it is because that's not up to me, that's up to the team to decide. And it seems that it's not clear to them immediately either which is why it was taken to a design meeting to decide whether this is actually a bug, or by-design. I'm not saying it is either of those. But that doesn't mean it's a feature request.

**Comment by CyrusNajmabadi** [comment]
Closing out.  Filer says they are not actually requesting anything, just that htey thought this was a bit odd.  Looking at the scenario, it seems entirely fine and i don't think we need to do anything here.
