### ISSUE TITLE
Allow tuple deconstruction in parameter declarations

### ISSUE THREAD

**Issue by Timwi** [dotnet/roslyn#26487]
**Version Used**: Visual Studio 2015 / 15.5.1

**Steps to Reproduce**:

```cs
// tupleSequence has the type IEnumerable<(int, int)>
var tupleSequence = Enumerable.Range(0, 10).Select(i => (i, i % 3));

// This code doesn’t compile
var furtherProcessing = tupleSequence.Select(((val, modulo)) => modulo);

// This also doesn’t compile
public void DoSomething((int first, int second) (v1, v2)) => v2;
```

**Expected Behavior**:

Variable deconstruction should work for parameters the same way it does for variable declarations such as

```cs
var (v1, v2) = GetValueTuple();
```

In particular, it should be possible to declare a method such as this:

```cs
public void DoSomething((int first, int second) (v1, v2)) => v2;
```

and further, methods with signatures like these:

```cs
public void DoSomething(Func<(int first, int second), int> func) => func((1, 2));
public void DoSomethingElse(Func<(int first, int second), int, int> func) => func((1, 2), 3);
```

should be able to take a arguments such as these:

```cs
DoSomething(((v1, v2)) => v1);
DoSomething(((v1, v2), v3) => v1);
```

**Actual Behavior**:

Parse error. The deconstruction syntax is simply not part of the grammar for parameter declarations.

**Comment by Neme12** [comment]
> The deconstruction syntax is simply not part of the grammar for parameter declarations.

Yes, that is correct. This is a language feature request and should be moved to https://github.com/dotnet/csharplang/ Please also take a look to see if there's an existing issue that tracks this proposal in that repo. Thanks.

**Comment by Joe4evr** [comment]
This is known as "splatting" and has already been proposed/discussed at dotnet/csharplang#424 and a few other threads.

**Comment by Neme12** [comment]
or https://github.com/dotnet/csharplang/issues/258

**Comment by jcouv** [comment]
Yes, this belongs on csharplang discussion. The current behavior is by-design.
Closing this compiler issue in favor of existing language issues. Thanks
