### ISSUE TITLE
Improve completion support for obsolete members

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#26488]
This is a **design** issue related to completion. Implementation issue(s) will be created according to the approved design, once available.

Original issues:

* #16817 by @CanisLupus
* #19583 by @davidfowl 
* #20442 by @mkrueger 
* #26478 by @xCyborg

Options for improving the use of these members include, but is not limited to the following:

* Formatting, e.g. strike-through, gray text, etc.
* Custom glyph(s)
* Modified sort order
* Filtering to exclude the items altogether

**Comment by xCyborg** [comment]
I hope someone is on this.

**Comment by gundermanc** [comment]
To answer @CyrusNajmabadi's question from the previous thread, yes, VS's completion is able to present strikethrough text encoded using the unicode facilities for strikethrough, however, typing the regular text didn't match the strikethrough version from the completion list when I tried it.

My guess is that you could probably get the desired behavior using the right combination of [CompletionItem](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.intellisense.asynccompletion.data.completionitem?view=visualstudiosdk-2019) properties:

- Display text should be strikethrough
- Sort text and filter text and insert text should be non-strikethrough so we can find the item on TYPECHAR and insert the right text.

The same thing looks possible in [language server protocol](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion) by providing both a label and sort text.

@AmadeusW is the feature owner for completion and might know more.

**Comment by CyrusNajmabadi** [comment]
When you are bolding items, you look at the display text though right?  so we would lose bolding here, right?

Note: my preference would be to *not* have the language set strikethrough, but instead expose a boolean stating if this is deprecated/obsolete.  Then, the platform would apply the styling and could do the right thing for all clients in a consistent fashion.  Would that make sense for you @gundermanc ?

**Comment by airbreather** [comment]
In my ideal world, it works like this (n.b.: I haven't seriously looked at how other languages / IDEs handle this):

- If [`ObsoleteAttribute.IsError`](https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute.iserror?view=net-5.0) is `true`, then the member should be **filtered out**.
    - Reasoning: the compiler will **always** emit an error unless you change the member itself, so I see no reason to have the IDE help you add errors to your code.
- Else if the completion item would necessarily cause a diagnostic whose severity is Error, then it should be in the list, but with ~strikethrough~ (perhaps put it to the end of the list to reduce clutter on the "real" members).
    - Reasoning: the compiler would emit an error, but there tend to be auto-fixes in these situations, so I can't justify hiding them outright.  ~Strikethrough~ feels like the next-strongest clue that the member should not be used.
- Else if the completion item would necessarily cause a diagnostic whose severity is anything other than Error, then I think gray text makes sense here.
    - Reasoning: grey text makes it clear that this member is not in the same league as everything else, but I perceive it as being less forceful than ~strikethrough~.
- Else (the completion item would not necessarily cause any diagnostics), let's leave it alone.
    - Reasoning: if the situation isn't even bad enough to give it **any** markings after completion, then I interpret it to mean that it's not bad enough to do anything special before completion either.

In table form:
|[`ObsoleteAttribute.IsError`](https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute.iserror?view=net-5.0)|Diagnostic Level|Action|
|-|-|-|
|`true`|*|filter out|
|`false`|Error|~strikethrough~|
|`false`|Warning|gray text|
|`false`|Info|gray text|
|`false`|Hint|gray text|
|`false`|None|do nothing|

Perhaps another alternative would be to decorate the list item the same way that it would be decorated in the text editor after completion?  e.g., if the completion would result in an error, then give it a red squiggly underline in the list too.

Regardless, as an expert user, I would also appreciate being able to (opt-in) filter out obsolete items from **all** completion lists.

**Comment by PathogenDavid** [comment]
> * Reasoning: the compiler will **always** emit an error unless you change the member itself, so I see no reason to have the IDE help you add errors to your code.

Personally I'd want to see it there anyway because I think it would cause confusion for people who knew about the now-obsolete API and the obsolete message would hopefully point me to the replacement API.

**Comment by jasonmalinowski** [comment]
Design meeting notes: we agreed we should go ahead with strikethrough, since [VS code implemented that](https://github.com/microsoft/vscode/issues/50972). If we get feedback we could also add a filter, but we seem to get be getting a small number of users using filters today.

@genlu will chat with the editor team next to see if this is already supported.

**Comment by gjrfytn** [comment]
@jasonmalinowski will it also be possible to show obsolete members in the end of the suggestion list?
An option to hide them completely sounds great for me too (without the need to hide them every time suggestions show up, I mean some kind of persistent filter).

**Comment by jasonmalinowski** [comment]
Possibly! I'll let @genlu speak to the details. (I was just the note taker.)

**Comment by AmadeusW** [comment]
Looks like LSP offers CompletionItemTag.Deprecated - are we going to go with this for the LSP implementation?

**Comment by CyrusNajmabadi** [comment]
> are we going to go with this for the LSP implementation

Yup.

> I can add a property to the VS CompletionItem

Awesome!  Let us know when it's available. Thanks!

**Comment by genlu** [comment]
> An option to hide them completely sounds great for me too (without the need to hide them every time suggestions show up, I mean some kind of persistent filter).

I think this make sense, and making it the default would be my preference..

**Comment by DamianEdwards** [comment]
Apparently VS Code has a feature like this for symbols in the editor, not just in completion. Would be great to have that in the VS editor too:

![image](https://user-images.githubusercontent.com/249088/101970006-af9bcf80-3bdc-11eb-9fdf-558de6372c6c.png)

Original tweet that brought this to my attention: https://twitter.com/JustinNoelDev/status/1337007045011234817

**Comment by CyrusNajmabadi** [comment]
Closing as fixed with https://github.com/dotnet/roslyn/pull/72156.  We don't have a dedicate glyph, but that doesn't seem necessary to consider this done.
