### ISSUE TITLE
Show return types in completion

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#26489]
This is a **design** issue related to completion. Implementation issue(s) will be created according to the approved design, once available.

Original issues:

* #20442 by @mkrueger 
* #26478 by @xCyborg
* #39516 by @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If there's a discussion to be had here, it can happen at: https://github.com/dotnet/roslyn/issues/75727
