### ISSUE TITLE
Annoying completion when typing `new {` for anonymous object creation

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26518]
If you type `new`, you get a list of completions offered (with `int` pre-selected):
![image](https://user-images.githubusercontent.com/12466233/39452010-907d2fc0-4c85-11e8-909c-488137e3c1e1.png)

If you then type `{`, `int` will be committed:
![image](https://user-images.githubusercontent.com/12466233/39452041-ac59f21e-4c85-11e8-8938-a9e2b2fd3595.png)

That is annoying for typing an anonymous object creation `new { }`.

One way of fixing this would be for `int` not to be pre-selected (make it a soft completion, since no characters have been given to filter the completion).

**Comment by CyrusNajmabadi** [comment]
what's the scenario here?  why were you typing anonymous type after a discard?

**Comment by jcouv** [comment]
I often use discards to avoid typing `var x`.
In most cases, it's the same, but here, it looks like it matters. Typing `var x = new {` works properly.
I'll go ahead and close. Thanks :-)
