### ISSUE TITLE
Should sizeof error message recommend Marshal.SizeOf?

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#26513]
**Version Used**: Roslyn 2.7.0 or master

**Steps to Reproduce**: 

Try to compile [the following code](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4GdhQK4GNgAIDKAsAFADeJuluMAdnvjAF4QDyc+AFAJS4C8AfLhRMIAezgd8XANwkAvkA==):

```c#
struct S
{
    int SizeOfS() => sizeof(S);
}
```

**Actual Behavior**:

> error CS0233: 'S' does not have a predefined size, therefore sizeof can only be used in an unsafe context (consider using System.Runtime.InteropServices.Marshal.SizeOf)

**Expected Behavior**:

Since `Marshal.SizeOf()` is not a direct replacement for `sizeof()`, maybe the error message should not mention it? On .Net Core, it could make sense to suggest [`Unsafe.SizeOf()`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafe.sizeof?view=netcore-2.0#System_Runtime_CompilerServices_Unsafe_SizeOf__1) instead, but that method is not available on .Net Framework or .Net Standard out of the box (it requires [the System.Runtime.CompilerServices.Unsafe package](https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/)), so maybe that suggestion should be removed altogether?

**Comment by jaredpar** [comment]
Rather than this error we should just allow `sizeof` in any context. There is really no reason to have this be unsafe only other than accident of history. I think we should just file a bug on csharplang to do this.

**Comment by svick** [comment]
@jaredpar There are already issues for allowing `sizeof` for generic types constrained to `struct` https://github.com/dotnet/csharplang/issues/1032 and to `unmanaged` https://github.com/dotnet/csharplang/issues/1508. I didn't find one for always allowing it.

**Comment by jaredpar** [comment]
@svick i saw the same when I searched. I think we need a new issue to cover just blanket allowing it. I was surprised we didn't have on already.

https://github.com/dotnet/csharplang/issues/1828
