### ISSUE TITLE
Feature request: add breakpoints from Find All References Window

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#26525]
This is a scenario that I do a lot, and if it is common among other developers, it would be great to have it. I often find myself trying to:
* find why a certain error is reported
* which code path is using some type
* which code path is assigning a variable, etc

I currently do it by finding all references, manually click each reference I want, go to the line it is used at, then placing a break point, then I run the program or the test that might exercise these code paths to find which break point is being hit. It would be great if I've in the context menu of Find all references the option to place a break point at these lines (where applicable). It would save a lot of manual time:

![image](https://user-images.githubusercontent.com/15987992/39460852-99bbf4f0-4cbb-11e8-8a80-c5f5173d3edb.png)

**Comment by jcouv** [comment]
@jinujoseph I suspect this isn't in Roslyn, and should be forwarded to the editor or debugger team. Can you help route? Thanks

**Comment by jinujoseph** [comment]
Thanks routed to [editor](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/641742)
