### ISSUE TITLE
Index out of range exception when attempting to add usings in VB

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#2652]
In VB, I had the following code inside a method:

```VB
Dim installDir = CType(Registry.LocalMachine.OpenSubKey("Software").OpenSubKey("Microsoft").OpenSubKey("VisualStudio").OpenSubKey("14.0").GetValue("InstallDir"), String)
Dim exePath = Path.Combine(installDir, "devenv.exe")
Dim fileVersionInfo = FileVersionInfo.GetVersionInfo(exePath)
```

I attempt to invoke a code action options using CTRL+. to add usings for ```FileVersionInfo```.  Instead, Visual Studio crashes with the following exception:

"Specified argument was out of the range of valid values.\r\nParameter name: index"	System.Exception {System.ArgumentOutOfRangeException}

 	PresentationFramework.dll!System.Windows.Controls.ItemCollection.GetItemAt(int index) Line 364	C#
>	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb.TransitionToExpandedState() Line 255	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb.ChangeState(Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbState newState) Line 196	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb._ctor.AnonymousMethod__0() Line 72	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs) Line 83	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler) Line 37	C#
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl() Line 583	C#
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state) Line 528	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 891	C#
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke() Line 441	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue() Line 2232	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled) Line 2471	C#
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled) Line 341	C#
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o) Line 494	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs) Line 104	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler) Line 37	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs) Line 1445	C#
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam) Line 392	C#

Dump available at: \\\marolf-server\public\Dumps\VB_Lightbulb_Crash.dmp

**Comment by balajikris** [comment]
looks like this happens inside the VSEditor code ? tagging interested parties : @shyamnamboodiripad @olegtk

**Comment by shyamnamboodiripad** [comment]
@jmarolf  Is the repro consistent?

Based on stack trace the bug seems to be on the editor side (Roslyn is not on the stack). Could you please log an internal bug for this?

**Comment by jmarolf** [comment]
filed internal bug 1170689

**Comment by amcasey** [comment]
The internal bug has been closed.
