### ISSUE TITLE
Update Roslyn /errorLog JSON output to SARIF v2

### ISSUE THREAD

**Issue by michaelcfanning** [dotnet/roslyn#26538]
Roslyn today emits SARIF v1 when log files are produced by the /errorLog switch. The SARIF v2 format is close to being finalized as a public standard driven by OASIS (Microsoft is on the technical committee and serves as project editor for the standard).

This is a tracking item request to update Roslyn's support when the standard is finalized. The TC will approve a draft for comment on 5/17.

**Comment by jinujoseph** [comment]
resolved by https://github.com/dotnet/roslyn/pull/37148

**Comment by lgolding** [comment]
Thanks @jinujoseph. I didn't know about the duplicate.
