### ISSUE TITLE
"Name can be simplified" fixer is not helpful

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#26532]
Current behavior of the Fix All for "names can be simplified" is not useful at all, it's faster to find and replace. 

**Steps to Reproduce**:

1. 
``` C#
using System.Diagnostics;

class Program
{
    static void Main(string[] args)
    {
        var debug1 = typeof(System.Diagnostics.Debug); <-- Simplify "name" across Document
        System.Diagnostics.DiagnosticListener debug2;
        System.Diagnostics.DebuggableAttribute debug3;
        System.Diagnostics.DebuggerHiddenAttribute debug4;
        var debug5 = typeof(System.Diagnostics.Debugger);
        System.Diagnostics.DebuggerNonUserCodeAttribute debug6;
        System.Diagnostics.DebuggerVisualizerAttribute debug7;
        System.Diagnostics.DelimitedListTraceListener debug8;
    }
}
``` 

**Expected Behavior**:
``` C#
using System.Diagnostics;

class Program
{
    static void Main(string[] args)
    {
        var debug1 = typeof(Debug);
        DiagnosticListener debug2;
        DebuggableAttribute debug3;
        DebuggerHiddenAttribute debug4;
        var debug5 = typeof(Debugger);
        DebuggerNonUserCodeAttribute debug6;
        DebuggerVisualizerAttribute debug7;
        DelimitedListTraceListener debug8;
    }
}
```

**Actual Behavior**:
``` C#
using System.Diagnostics;

class Program
{
    static void Main(string[] args)
    {
        var debug1 = typeof(Debug);
        System.Diagnostics.DiagnosticListener debug2;
        System.Diagnostics.DebuggableAttribute debug3;
        System.Diagnostics.DebuggerHiddenAttribute debug4;
        var debug5 = typeof(System.Diagnostics.Debugger);
        System.Diagnostics.DebuggerNonUserCodeAttribute debug6;
        System.Diagnostics.DebuggerVisualizerAttribute debug7;
        System.Diagnostics.DelimitedListTraceListener debug8;
    }
}
```

**Comment by davkean** [comment]
Here's another one, simplifier only moves the first one:

``` C#
                            System.Windows.Forms.DialogResult result = dialog.ShowDialog();
                            if (result == System.Windows.Forms.DialogResult.OK)
                            {
                                WorkingDirectory = dialog.SelectedPath.ToString();
                            }
```

**Comment by CyrusNajmabadi** [comment]
Oh, it's not even that.  It's that the feature is designed to only simplify all cases of the *same name*.  i.e. it does this:

```c#
            var id = GetCodeActionId(diagnosticId, node.ConvertToSingleLine().ToString());
            var title = id;
            var codeAction = new SimplifyTypeNameCodeAction(title,
                    c => SimplifyTypeNameAsync(document, node, c),
                    id);
```

I have no idea what is going on with the design here.  Presumably if someone said they wanted to 'fix all' when they were told they could simplify a name, they would want to simplify all names, not just that name.  But maybe this logic has merit.

Tagging @sharwell so this can be discussed if this design is what is wanted, or of this should be fixed up to actually fix all occurrences of any type name that can be simplified.

**Comment by davkean** [comment]
Yeah, if I remember correctly I hacked together a build on Roslyn the last time I went to fix this that changed the id to something common for all simplification cases.

**Comment by CyrusNajmabadi** [comment]
Wow.  I legitimately do not understand what thsi analyzer/fix is doing.  The analyzer already figures out what node can be simplified.  But then the fixer goes and does more work and tries to figure out more stuff.  And the fix all code is just wacky.   This is getting seriously close to my 'burn it all to the ground' point.  But i don't think i have the time to invest in a proper rewrite here.

**Comment by CyrusNajmabadi** [comment]
Oh man... i see what's going on.  It looks like this code is just trying to share a single analyzer/fixer across all the potential cases it might have to deal with.  But the different cases are just so different, that it just makes things so much harder.  It does this, despite using individual IDs already to distinguish these situations.  So it would just be so much cleaner as several different fixers, one per distinct diagnostic ID.

**Comment by CyrusNajmabadi** [comment]
Found the issue.  Have fix available here: https://github.com/dotnet/roslyn/pull/26823

**Comment by sharwell** [comment]
> Oh, it's not even that. It's that the feature is designed to only simplify all cases of the *same name*. 

This is what I understood of the current design. Marking this **Needs Design Review** so we can discuss a proposal to relax or eliminate this. If the proposed behavior is not as simple as just "allow Fix All in simplify type name to cover all names in a single pass", can you write down the specifics of the change to make sure we discuss the right thing?

**Comment by CyrusNajmabadi** [comment]
>  "allow Fix All in simplify type name to cover all names in a single pass", can you write down the specifics of the change to make sure we discuss the right thing?

The only subtlety is what does 'all names' mean.  Right now i've bucketed thigns by diagnostic ID (which we have 5 of):

```
        public const string SimplifyNamesDiagnosticId = "IDE0001";
        public const string SimplifyMemberAccessDiagnosticId = "IDE0002";
        public const string RemoveQualificationDiagnosticId = "IDE0003";
        public const string PreferIntrinsicPredefinedTypeInDeclarationsDiagnosticId = "IDE0012";
        public const string PreferIntrinsicPredefinedTypeInMemberAccessDiagnosticId = "IDE0013";
```

All of these are fixed by the same provider. But they apply to different situations.  i.e. ```PreferIntrinsicPredefinedTypeInMemberAccessDiagnosticId``` is for simplifying ```Int32.Parse``` to ```int.Parse```, whereas ```SimplifyMemberAccessDiagnosticId``` is for simplifying ```System.Console.WriteLine``` to ```Console.WriteLine```

We have different options for these and we present them to the user through different diagnostic IDs.  So i respect that split when actually doing the fix.  If you are fixing IDE0013, then fix-all will only fix up those diagnostics IDs and not any of the others.

Does that make sense?

**Comment by sharwell** [comment]
> Does that make sense?

👍 Yep

**Comment by sharwell** [comment]
This went to a design meeting yesterday. The behavior change proposed in https://github.com/dotnet/roslyn/issues/26532#issuecomment-388587619 was accepted.

**Comment by CyrusNajmabadi** [comment]
Ok.  i can try to make these changes in the next week or so.

**Comment by Neme12** [comment]
@CyrusNajmabadi what changes? Didn't you just ask for #26823 to be merged?

**Comment by sharwell** [comment]
@CyrusNajmabadi Let me know if there's any part of this that isn't already covered by #26823.

**Comment by CyrusNajmabadi** [comment]
I think #26823 Can be taken as-is.
