### ISSUE TITLE
After options changed, analyzer messages are not reevaluated until you modify source code

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#26530]
**Version Used**: 

**Steps to Reproduce**:

1. 
![image](https://user-images.githubusercontent.com/1103906/39462808-6136e332-4d57-11e8-8dd1-1d00490f1006.png)
2.

``` VB
Public Class Class1

    Public Sub Foo()

        Dim list As New List(Of String)
        list.Add("One")
        list.Add("two")

    End Sub


End Class

```

3. Change settings to following and click OK:
![image](https://user-images.githubusercontent.com/1103906/39462820-86ea28d2-4d57-11e8-8044-cb2542864a76.png)

4. Wait for ... to disappear from Error List

**Expected Behavior**:

```
Message	IDE0028	Collection initialization can be simplified	ClassLibrary56	c:\users\davkean\Source\Repos\ClassLibrary56\ClassLibrary56\Class1.vb	5	Active
```

**Actual Behavior**:

Nothing. If you make a change to the source file, then the message appears.

**Comment by sharwell** [comment]
This was fixed for .editorconfig changes in #27280. The global options service could be updated to use `IDiagnosticAnalyzerService` similar to how it's used in d02949bb448461d2f693f415544d4ca33b5caf2d.

**Comment by CyrusNajmabadi** [comment]
I think this now works as this causes a workspace change which should cause an lsp refresh.
