### ISSUE TITLE
File ordering during solution load batching

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#26547]
During solution load, we don't push changes to the `Workspace` immediately.  Because of this, we may not preserve the order documents are passed from the project, since we enumerate a dictionary to populate the `Workspace` in [CreateProjectInfoForCurrentState](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/AbstractProject.cs,310).

NOTE: We probably get lucky and actually do have order since `Dictionary` tends to preserve enumeration order as long as there have only been Add operations.

Tagging @jasonmalinowski to think about when we're fixing the ordering contract between the project system and Roslyn.

**Comment by jasonmalinowski** [comment]
@Pilchie Yeah, that won't work.

> NOTE: We probably get lucky and actually do have order since Dictionary tends to preserve enumeration order as long as there have only been Add operations.

How would that even work?

**Comment by CyrusNajmabadi** [comment]
afaict we do not depend on this order.  the only one who needs ordering is F# and we have hte APIs for them to be explicit about preferred order.
