### ISSUE TITLE
Naming violation fixers need better heuristics

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#26556]
I find myself never using the default naming violation fixer - it almost always suggests nonsensical fixes for a code base as old as mine with various naming styles over the years.

We ran into exactly the same situation when we did naming rules with FxCop, and we added better heuristics to suggest more sensible name. 

As I fix up this Visual Basic code base, I'm going to add all the individual suggestions that I ignored from it:

Syntax|Suggested|What I actually renamed to|Issue
---|---|---|---
`Private Shared m_DefaultInstance As BuildEventCommandLineDialog`|s_m_DefaultInstance|s_defaultInstance|#26566
`m_CommandLine As String`|_m_CommandLine|_commandLine|#26566
`Private ReadOnly _ID As String`|_iD|_id|#31908
`Private _UIShellService As IVsUIShell`|_uIShellService|_uiShellService|#31908
`Protected m_ScalingCompleted As Boolean`|M_ScalingCompleted|ScalingCompleted|#26566
`Private Const s_anyCPUPlatformName As String = "Any CPU"`|S_anyCPUPlatformName|AnyCPUPlatformName|#26566
`Private _DTE As EnvDTE.DTE`|_dTE|_dte|#31908
`Private s_helpTopic As String`|s_helpTopic|_helpTopic|#26566
`Private Shared s_RFSSwitch`|s_rFSSwitch|s_rfsSwitch|#31908
`Private _DTEEvents As DTEEvents`|_dTEEvents|_dteEvents|#31908
`Private Const s_SERIALIZATION_DESCRIPTION As String = "Description"`|S_SERIALIZATION_DESCRIPTION|SERIALIZATION_DESCRIPTION|#26566, #31908

**Comment by sharwell** [comment]
> As I fix up this Visual Basic code base, I'm going to add all the individual suggestions that I ignored from it:

❤️

**Comment by sharwell** [comment]
For StyleCop Analyzers, we strip the prefixes `m_`, `s_`, `t_`, and `_` until there are no more *or* the next step would leave an empty string. Then we apply the expected naming convention to the result.

**Comment by davkean** [comment]
For FxCop, we'd handle both IO and Xml in all forms (pascal, camel case, uppercase).

**Comment by davkean** [comment]
Also please look at the old FxCop naming rules - they have a tonne of history in them.

**Comment by sharwell** [comment]
@davkean With the addition of #31908, I believe all of the items above are captured in linked issues. The one case which might be problematic is the proposed implementation would request `AnyCPUPlatformName` get renamed to `AnyCpuPlatformName`. If you have concerns about this change, please add them to #31908.
