### ISSUE TITLE
Need an analyzer to catch re-used analyzer IDs

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#2656]
A `DiagnosticAnalyzer` should not report multiple `DiagnosticDescriptors` with the same ID, as this makes it impossible to properly merge errors coming from the IDE and errors coming from the build and remove duplicates.

Unfortunately FxCop used to report different (but related) errors under the same ID, so our re-implementation of FxCop rules on top of Roslyn needs to do the same. However, we should discourage authors of new analyzers from doing this. To that end, we should create an analyzer analyzer to check for this situation.

**Comment by tmeschter** [comment]
@srivatsn @lgolding @mavasani Should this be moved over to the dotnet/roslyn-analyzers repo?

**Comment by sharwell** [comment]
I'm not quite sure what this analyzer is checking for. For example, in StyleCopAnalyzers we have two [`DiagnosticDescriptor` instances for SA1633](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/5a61cdf5960a2224681173ae00d74072261f25a6/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/FileHeaderAnalyzers.cs#L86-L98), but we only include one of the two in the [result of `SupportedDiagnostics`](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/5a61cdf5960a2224681173ae00d74072261f25a6/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/FileHeaderAnalyzers.cs#L159). Would this be considered following the rule, or breaking the rule?

**Comment by lgolding** [comment]
IMO, assuming Tom and Sam agree on the meaning of the rule, it does belong in roslyn-analyzers, because we'd address this issue by writing a new analyzer in that repo.

**Comment by Youssef1313** [comment]
@mavasani Is this still needed? If so, can you move to roslyn-analyzers repo, or close if not needed? Thanks!

**Comment by mavasani** [comment]
Closing out, IMO this is no longer relevant as we have various such analyzers in multiple repos - we allow same analyzer to report multiple descriptors with same ID but different message. Additionally, we also have RS0019 for flagging multiple analyzers in the same analyzer assembly that report descriptors with the same ID: https://github.com/dotnet/roslyn-analyzers/blob/c5dbf3127608ed9655c43ec8b81361916e752a6d/src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs#L342-L352
