### ISSUE TITLE
Specialized fields get mistakenly added to MemberRef blob in output PE file

### ISSUE THREAD

**Issue by RenniePet** [dotnet/roslyn#26563]
**Version Used**: Version currently used by Visual Studio 2017, and also current version on Master branch.

**Steps to Reproduce**:

Here's a simple test program:

```
   public class NonGenericClass
   {
      private int _simplePrivateFieldNoReference;
      private int _simplePrivateFieldPublicReference;

      public void ReferencePrivateField()
      {
         var x1 = _simplePrivateFieldPublicReference;
      }
   }

   public class GenericClass<T>
   {
      private int _simplePrivateFieldNoReference;
      private int _simplePrivateFieldPublicReference;

      public void ReferencePrivateField()
      {
         var x1 = _simplePrivateFieldPublicReference;
      }
   }
```
**Expected Behavior**:

I do not think any of the private fields should be added to the MemberRef blob of the output file.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/4259011/39519354-b64b786a-4e06-11e8-853c-1c853a1464a5.png)

**Possible Fix**:

In MetadataWriter.cs, at the start of GetFieldHandle(), add these three statements:

```
     ISpecializedFieldReference specializedFieldReference =
                                                 fieldReference.AsSpecializedFieldReference;
     if (specializedFieldReference != null)
        fieldReference = specializedFieldReference.UnspecializedVersion;
```
In ReferenceIndexerBase.cs, in Visit(IFieldReference fieldReference), following the first four lines add the same three statements shown above.

Or, in the interests of DRY, combine these three statements and the following two statements which are common for the two locations into one new method in MetadataWriter.

If I'm right about this I'd love to submit a pull request, and join the ranks of Roslyn contributors.  :-)

**Comment by jaredpar** [comment]
Thanks for reporting. The MemberRef table seems to be governed by the following rule:

> An entry is made into the MemberRef table whenever a reference is made, in the CIL code, to a method or field which is defined in another module or assembly (also an entry is added for a call to method with VARARG signature even when defined in the same module) 

Given that these entries doe seem a bit unnecessary. I'm unsure that the proposed solution is correct or not though (not an area of the code I'm really familiar with).

**Comment by jaredpar** [comment]
After digging a bit more it appears this behavior is by design. The portion of the spec I referenced above is incomplete with respect to generics. Section 9.8 has a more definitive statement: 

> Members (fields and methods) of a generic type are referenced in CIL instructions using a metadata token, which specifies an entry in the MemberRef table 

This is done irrespective of the model that they are contained in.
