### ISSUE TITLE
"Find all references" Navigation using F8 does not show caret in text editor when a new file is activated

### ISSUE THREAD

**Issue by BhaaLseN** [dotnet/roslyn#26565]
**Version Used**:
Visual Studio Enterprise 2017 15.6.6

**Steps to Reproduce**:
1. Pick any identifier in source that occurs at least twice, but in different files (any class from the System namespace such as `Guid` or C# identifier such as `string` works; not required to be a symbol from the project to trigger the issue)
2. Invoke "Find all references". It seems to make no difference which "Group by" option is active, but it does make a difference if "Find in Files" is used instead to locate a string (and not a reference).
3. Double-click the a result in one file, VS jumps to the result and puts the caret right next to the match. Do *not* single-click preview the file, because it leaves the focus on the Find result/references window and picks a different result instead of moving the caret in the text editor when using Up/Down/etc.
4. Hit F8 (`Edit.GoToNextLocation`) to get the next result. In case the result is in the same file, continue until a new file is activated (because the caret works just fine when it was visible before)

**Expected Behavior**:
VS jumps to the result, just as a double-click on the result would do.

**Actual Behavior**:
VS jumps to the result, but no caret is visible. Attempting to perform keyboard navigation (Up/Down/Left/Right as well as Page Up/Page Down) works, but is very difficult due to the caret not being visible at all. Might be my imagination, but it seems that identifier/keyword/brace highlighting takes a lot longer to complete (which could also be caused by the caret being somewhere else than I'd expect).

**Comment by CyrusNajmabadi** [comment]
Taggign @olegtk
