### ISSUE TITLE
ObjectCreationInitializer completion doesn't escape keywords

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26560]
```c#
class C
{
   int @new { get; set; }
   void M()
   {
        _ = new C() { $$ }; // "@new" should be offered, but "new" is offered instead.
   }
}
```

Follow-up on comment made in https://github.com/dotnet/roslyn/pull/26474 about a related provider.

**Comment by jcouv** [comment]
@mikkelbu The behavior you picture seems good. Go for it :-)

**Comment by mikkelbu** [comment]
@jcouv Ok, I'll create a PR today or tomorrow :).

For `New` the brackets are required in `Dim c As New Customer With {.[New] = 10}` (with the class definition from the example above), but for `Class` the brackets are not necessary `Dim c As New Customer With {.Class = 10}`.
The "funny" part is that if I remove the brackets from `New` then we the focus leave the line, the text `Dim c As New Customer With {.New = 10}` is replaced with `Dim c As New Customer With {.Customer = 10}`.
