### ISSUE TITLE
Preview changes dialog does not show conflicts

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#26576]
**Version Used**: 15.7 Preview 5

**Steps to Reproduce**:

1. Create a property named `Name`
2. Create a method named `Name2`
3. Rename `Name2` to `Name` with Preview Changes enabled

**Expected Behavior**:

The **Preview Changes** dialog appears showing the impact of the change. Conflicts resulting from the name change are highlighted:

* In the list of files (top pane), a glyph appears next to the file and/or snippets containing a conflict
* In the diff view (bottom pane), conflicts appear with the conflict marker UI (by default a red outline)

**Actual Behavior**:

The **Preview Changes** dialog appears with no indication that the rename contained any conflict at all.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and preview-changes not being changed.
