### ISSUE TITLE
Roslyn.Services.Editor.VisualBasic.UnitTests.dll - 2 tests fail in presence of localized resources

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#2657]
Assemblies Run

Roslyn.Services.Editor.VisualBasic.UnitTests.dll

Summary

Tests run: 8323   Failures: 2, Skipped: 63, Run time: 276.222s

Failed tests

0.005s
✘
 Microsoft.CodeAnalysis.VisualBasic.EditAndContinue.UnitTests.ActiveStatementTests.ForEach_Update_Lambda2 : Actual: Diagnostic(RudeEditKind.UpdateAroundActiveStatement, "For Each a In G(Function(a) a)", "!VU3Qz!For Each statement ЁЧЫ!") Differences: ++> Diagnostic(RudeEditKind.UpdateAroundActiveStatement, "For Each a In G(Function(a) a)", "!VU3Qz!For Each statement ЁЧЫ!") --> Diagnostic(RudeEditKind.UpdateAroundActiveStatement, "For Each a In G(Function(a) a)", "For Each statement") 
   в Xunit.Assert.True(Boolean condition, String userMessage)
   в Roslyn.Test.Utilities.AssertEx.SetEqual[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer, String message, String itemSeparator) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Test\Utilities\AssertEx.cs:строка 257
   в Microsoft.CodeAnalysis.EditAndContinue.UnitTests.Extensions.Verify(IEnumerable`1 diagnostics, String newSource, RudeEditDiagnosticDescription[] expectedDiagnostics) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\EditorFeatures\Test\EditAndContinue\Extensions.cs:строка 16
   в Microsoft.CodeAnalysis.EditAndContinue.UnitTests.EditAndContinueTestHelpers.VerifyRudeDiagnostics(EditScript`1 editScript, ActiveStatementsDescription description, RudeEditDiagnosticDescription[] expectedDiagnostics) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\EditorFeatures\Test\EditAndContinue\EditAndContinueTestHelpers.cs:строка 125
   в Microsoft.CodeAnalysis.VisualBasic.EditAndContinue.UnitTests.Extensions.VerifyRudeDiagnostics(EditScript`1 editScript, ActiveStatementsDescription description, RudeEditDiagnosticDescription[] expectedDiagnostics) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\EditorFeatures\VisualBasicTest\EditAndContinue\Helpers\Extensions.vb:строка 39
   в Microsoft.CodeAnalysis.VisualBasic.EditAndContinue.UnitTests.ActiveStatementTests.ForEach_Update_Lambda2() в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\EditorFeatures\VisualBasicTest\EditAndContinue\ActiveStatementTests.vb:строка 2909

0.044s
✘
 Microsoft.CodeAnalysis.VisualBasic.EditAndContinue.UnitTests.ActiveStatementTests.SyncLock_Update_Lambda2 : Actual: Diagnostic(RudeEditKind.UpdateAroundActiveStatement, "SyncLock G(Function(a) a)", "!lp9Rs!SyncLock statement ЁЧЫ!") Differences: ++> Diagnostic(RudeEditKind.UpdateAroundActiveStatement, "SyncLock G(Function(a) a)", "!lp9Rs!SyncLock statement ЁЧЫ!") --> Diagnostic(RudeEditKind.UpdateAroundActiveStatement, "SyncLock G(Function(a) a)", "SyncLock statement") 
   в Xunit.Assert.True(Boolean condition, String userMessage)
   в Roslyn.Test.Utilities.AssertEx.SetEqual[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer, String message, String itemSeparator) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Test\Utilities\AssertEx.cs:строка 257
   в Microsoft.CodeAnalysis.EditAndContinue.UnitTests.Extensions.Verify(IEnumerable`1 diagnostics, String newSource, RudeEditDiagnosticDescription[] expectedDiagnostics) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\EditorFeatures\Test\EditAndContinue\Extensions.cs:строка 16
   в Microsoft.CodeAnalysis.EditAndContinue.UnitTests.EditAndContinueTestHelpers.VerifyRudeDiagnostics(EditScript`1 editScript, ActiveStatementsDescription description, RudeEditDiagnosticDescription[] expectedDiagnostics) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\EditorFeatures\Test\EditAndContinue\EditAndContinueTestHelpers.cs:строка 125
   в Microsoft.CodeAnalysis.VisualBasic.EditAndContinue.UnitTests.Extensions.VerifyRudeDiagnostics(EditScript`1 editScript, ActiveStatementsDescription description, RudeEditDiagnosticDescription[] expectedDiagnostics) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\EditorFeatures\VisualBasicTest\EditAndContinue\Helpers\Extensions.vb:строка 39
   в Microsoft.CodeAnalysis.VisualBasic.EditAndContinue.UnitTests.ActiveStatementTests.SyncLock_Update_Lambda2() в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\EditorFeatures\VisualBasicTest\EditAndContinue\ActiveStatementTests.vb:строка 2621

**Comment by wschae** [comment]
@AlekseyTs Can you verify this fix?
