### ISSUE TITLE
With a large number of files open, it takes 6 - 10 seconds bring up Rename prompt

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#26580]
**Version Used**: 

**Steps to Reproduce**:

1. `git clone https://github.com/dotnet/project-system`
2. `git checkout 8319d977e92da50c3fed1460344fb3c7ef6baaa1`
3. In Explorer, search for "*.vb" under src
4. Drag them into Visual Studio
5. Wait for "..." to removed from Error List
6. Highlight a private symbol in one of the VB files, and press CTRL + R, CTRL + R

**Expected Behavior**:
For Rename symbols to immediately appear

**Actual Behavior**:
It takes 6 - 10 seconds to appear

**Comment by davkean** [comment]
Trace is under `[internalshare]\public\davkean\Roslyn\26580`

**Comment by CyrusNajmabadi** [comment]
I wonder if this is related to https://github.com/dotnet/roslyn/issues/26362

Performance feels absolutely horrible with the latest preview bits.  It def feels like some things have regressed badly in the last few previews.

**Comment by davkean** [comment]
In the same situation, I'm not seeing any noticeable lag in lightbulb time if I rename the symbol first, and then move to the light bulb to run Rename fixer.

**Comment by davkean** [comment]
Just as heads up, there's no multi-targeting projects in play.

**Comment by sharwell** [comment]
Could also be #26339

**Comment by davkean** [comment]
Let me figure out if this is a regression.

**Comment by davkean** [comment]
This isn't a regression, same occurs in 15.6.

**Comment by CyrusNajmabadi** [comment]
Closing out due to age and lack of reports around this scenario.
