### ISSUE TITLE
Parenthesized expression is parsed as a cast if it's followed by 'switch'

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#26584]
**Version Used**:  branch `features/recusrive-patterns`

**Steps to Reproduce**:

```cs
class C {
    void M(bool t)  {
        Console.Write((t) switch {var x => x});
    }
}
```

**Expected Behavior**:

No error.

**Actual Behavior**:

`error CS1525: Invalid expression term 'switch'`
`error CS0118: 't' is a variable but is used like a type`

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/26753
