### ISSUE TITLE
Explicitly implementing an interface with a property shows property accessors

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#26595]
**Version Used**: 2.8.0-beta4-62827-02. Commit Hash: 362ec0eec4c1d61b122e271423840950fedf13ff

1. Create an interface with a property getter.
2. Create a class that implements the interface.
3. Manually write an explicit implementation of that property getter:

![image](https://user-images.githubusercontent.com/201340/39594052-6db0a19c-4ec0-11e8-9cb8-6e80e7a53151.png)

...that getter shouldn't be shown.

**Comment by tokarzkj** [comment]
I would be interested in tackling this bug if no one else has started it.

**Comment by CyrusNajmabadi** [comment]
@tokarzkj Go for it!

**Comment by jinujoseph** [comment]
thanks for the fix @tokarzkj
