### ISSUE TITLE
Suggestion: offer "generate Deconstruct method" fixer

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26597]
Type `(int x, string y) = e; // no Deconstruct method found` and get offered to generate such a method.
This could also apply to recursive patterns: `e is (1, "hello")`.

**Comment by CyrusNajmabadi** [comment]
Note: this should likely just be part of GenerateMethod. All you'd need to fixup is the code that determines the location of the method and the signature to generate.

**Comment by CyrusNajmabadi** [comment]
Now: what would be exceptionally cool would be if we could try to infer the body of hte Deconstruct method.  i.e. we should see if the type already has fields/props that match the deconstructed names (insensitively), and if so, hook things up for you.

**Comment by jcouv** [comment]
I have a PR open for this. It only handles generating the declaration for `Deconstruct`, but doesn't generate a working body (unlike Resharper's `Deconstruct` [generator](https://www.jetbrains.com/help/resharper/Code_Generation_Deconstructors.html)). We could add that later.

**Comment by CyrusNajmabadi** [comment]
> but doesn't generate a working body (unlike Resharper's Deconstruct generator). We could add that later.

This is pretty easy to do.  You can see how i did this in my PR: 

https://github.com/dotnet/roslyn/pull/28257/files#diff-3bcf6488917b42c1df649c2d7a7fd0a0R573

We should probably end up extracting this into a helper so we both can share it.

**Comment by CyrusNajmabadi** [comment]
BTW, question for you.  Currently, we generate different code for the following two Deconstruct impls:

```c#
void Deconstruct(out int x, out int y)
{
    x = this.x;
    y = this.y;
}

void Deconstruct(out int x, out int y)
{
    (x, y) = (this.x, this.y);
}
```

Is the intent that hte latter end up as simple and efficient as the former at some point?

**Comment by CyrusNajmabadi** [comment]
Ah... and i suppose that coudl be observed. say if the previous write did something that affected the second read...
