### ISSUE TITLE
Suggestion: remove/weaken the IEnumerable requirement for collection initializers

### ISSUE THREAD

**Issue by SolalPirelli** [dotnet/roslyn#266]
C# specification §7.6.10.3, _Collection initializers_:  

> The collection object to which a collection initializer is applied must be of a type that implements `System.Collections.IEnumerable` or a compile-time error occurs.

This restriction is explained in [an old blog post](http://blogs.msdn.com/b/madst/archive/2006/10/10/what-is-a-collection_3f00_.aspx) by Mads Torgersen: it ensures that collection initializers cannot be used on types whose `Add` method does not add an element to a collection, but does things like computing a sum.

However, as discussed in a [CodePlex issue](https://roslyn.codeplex.com/discussions/545075), there are a few use cases where the collection initializer syntax is desirable on objects that can't/shouldn't implement `IEnumerable`.

Additionally, collection initializers can already be used on immutable collections if they provide a constructor, since they're likely to both implement `IEnumerable` and have an `Add` method, but this obviously doesn't work properly.

Therefore, I suggest one of the following:
- _Lift the restriction entirely. Allow collection initializers on any object with an `Add` method._  
  The simplest option. I do not have evidence for this, but I very much doubt that people actually try to use collection initializers on types that are not thought of as collections.
- _Keep the restriction, but also allow types to use an attribute indicating that they want to support collection initializers_, as suggested by user 'supercat' in the original discussion.  
  The safest option, ensuring that types won't get collection initializers if they don't want them.
- _Add many attributes to let collection initializers adapt to more patterns, such as immutable types or builders_, as suggested by Jon Skeet (!) in the original discussion.  
  The most complex option, which would probably fit more in a general "make C# more friendly to DSLs" feature.

Another idea (which is orthogonal to these suggestions) is to add an attribute that _disables_ collection initializers, even on types implementing `IEnumerable`.

**Comment by AdamSpeight2008** [comment]
I think a trait (#129) would work as a better restriction.
Something like.
```c#
trait {
  requires: Add (T)-> void
    ensure: _Count.Old < _Count.New; 
}
```

**Comment by gafter** [comment]
This issue was moved to dotnet/csharplang#324
