### ISSUE TITLE
Need annotation for nullable property with non-nullable setter

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26621]
Let's bring this up with LDM.

```C#
        public ITaskItem[]? Sources
        {
            set
            {
                if (UsedCommandLineTool)
                {
                    NormalizePaths(value!); // PROTOTYPE(NullableDogfood): value set should be non-null
                }

                _store[nameof(Sources)] = value;
            }
            get { return (ITaskItem[])_store[nameof(Sources)]; }
        }
```

**Comment by sharwell** [comment]
💭 In most cases where I hit this so far, the property was able to be rewritten in this form. It doesn't work for everything but likely covers many.

```csharp
public SomeType Property
{
  get => _value ?? throw new InvalidOperationException("The object is not yet initialized");
  set => _value = value;
}
```

**Comment by jcouv** [comment]
This was resolved by the new attribute design. We can restrict or relax inbound values with `[Disallow/AllowNull]` and restrict/relax outbound values with `[Not/MaybeNull]`.

See https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-05-15.md
