### ISSUE TITLE
Cannot resolve symbol when System.Threading.Tasks.Dataflow.dll used

### ISSUE THREAD

**Issue by buko1234** [dotnet/roslyn#26625]
**Version Used**: 
2.7.0

**Steps to Reproduce**:

1. 
```
public void Foo3()
{
    new BroadcastBlock<bool>(null);
}
```
2. 
Create compilation
```
AdhocWorkspace adhoc = new AdhocWorkspace();
ProjectInfo projectInfo = ProjectInfo.Create(ProjectId.CreateNewId(), VersionStamp.Default, "TestProject", "TestProject", "C#");
adhoc.AddProject(projectInfo);
adhoc.AddDocument(projectInfo.Id, className + ".cs", sourceText);
Document document = adhoc.CurrentSolution.Projects.Single().Documents.Single();
IDictionary<Document, SyntaxTree> syntaxTrees = new Dictionary<Document, SyntaxTree>();
SyntaxTree tree = doc.GetSyntaxTreeAsync().Result;
syntaxTrees.Add(document, tree);
// metadataRefences contain two values: mscorlib.dll and System.Threading.Tasks.Dataflow.dll
CSharpCompilation compilation = CSharpCompilation.Create("MyCompilation", syntaxTrees: syntaxTrees.Values, references: metadataReferences, options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
SemanticModel model = _compilation.GetSemanticModel(tree);
```
3. 

**Expected Behavior**:
model.GetSymbolInfo() on "new BroadcastBlock<bool>(null);" returns proper SymbolInfo

**Actual Behavior**:
It returns SymbolInfo with OverloadResolutionFailure: candidate symbols are:
Method System.Threading.Tasks.Dataflow.BroadcastBlock<System.Boolean>..ctor(System.Func<System.Boolean, System.Boolean>[missing] cloningFunction)
Method System.Threading.Tasks.Dataflow.BroadcastBlock<System.Boolean>..ctor(System.Func<System.Boolean, System.Boolean>[missing] cloningFunction, System.Threading.Tasks.Dataflow.DataflowBlockOptions dataflowBlockOptions)

It seems like there is a problem with Func type.

**Comment by svick** [comment]
What happens when you print diagnostics for your compilation? (E.g. `foreach (var diag in compilation.GetDiagnostics()) Console.WriteLine(diag);`.) I get:

> error CS0012: The type 'Func<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

When I also add a reference to C:\Windows\Microsoft.NET\Framework64\v4.0.30319\netstandard.dll, compilation diagnostics become empty and `GetSymbolInfo()` will start working on that expression.

**Comment by buko1234** [comment]
In my case it was System.Runtime.dll missing and adding it helped.
