### ISSUE TITLE
[IOperation] C# Collection Initializers do not expose all arguments

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#26643]
In the VB IOperation tree for collection initializers, we expose nodes for default arguments and for param arrays. We do not do the same for C# collection initializers, so those trees only have the arguments that were actually specified in code.

**Comment by jinujoseph** [comment]
@333fred has this been addressed ?

**Comment by 333fred** [comment]
Yes, this was fixed in https://github.com/dotnet/roslyn/pull/26781
