### ISSUE TITLE
Some squiggles missing for nullable warnings

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26644]
I'm using the RoslynDev hive, built from `features/NullableReferenceTypes`, and opening `Compilers.sln` from `features/NullableDogfood` branch.

I build one project (`MSBuildTask`) and look at the warnings that are produced. Some warnings work fine: I double-click on one in the Error List and it takes me to the squiggled source. But some warnings only take me to the source (no squiggles).

![image](https://user-images.githubusercontent.com/12466233/39656175-d9f98920-4fb2-11e8-83c2-5ff483438023.png)

![image](https://user-images.githubusercontent.com/12466233/39656172-d3e61274-4fb2-11e8-8ab2-621d391789f9.png)

@heejaechang @CyrusNajmabadi Any idea how to troubleshoot this?

**Comment by heejaechang** [comment]
is the file opened in right project? not misc project?

**Comment by heejaechang** [comment]
what happen if you make an change like typing a space " "?

**Comment by jcouv** [comment]
I think there was an assertion pop-up that I hadn't seen. I'll close the issue and reopen if I'm able to repro again. Thanks
