### ISSUE TITLE
Investigate removing a dependency on ImageCatalog/Imaging from EditorFeatures

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#26642]
EditorFeatures has a dependency on MS.VS.ImageCatalog.dll and we don't have it on Mac. This place: 
https://github.com/dotnet/roslyn/blob/features/AsyncCompletion/src/EditorFeatures/Core/Implementation/IntelliSense/EditorCompletionImplementation/CompletionItemSource.cs#L121

**Comment by KirillOsenkov** [comment]
when Jit tries to compile the GetImageId() method, it uses types from ImageCatalog:
`return new ImageId(KnownImageIds.ImageCatalogGuid, KnownImageIds.Assembly);`

**Comment by KirillOsenkov** [comment]
![image](https://user-images.githubusercontent.com/679326/39656703-a8541206-4fb6-11e8-97d1-9c48c00cd545.png)

**Comment by jasonmalinowski** [comment]
Also paging @JieCarolHu who might be able to fix this up quick.

**Comment by KirillOsenkov** [comment]
@jinujoseph is there a way to mark bugs that block VSMac somehow? There are a few bugs that would be very nice to fix soon.

**Comment by jinujoseph** [comment]
@KirillOsenkov  would you mail me the list pls

**Comment by KirillOsenkov** [comment]
I've just realized that we have a project to track these: https://github.com/dotnet/roslyn/projects/32
