### ISSUE TITLE
InsertComment logic should respect line break setting (EditorConfig or local)

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#26653]
https://github.com/dotnet/roslyn/blob/990fbbbf1e29eca1b7e73aa755c446ce2858446d/src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs#L82

Here it hardcodes "\r\n" and it should be properly getting the setting from either editor config or current file settings.

**Comment by DavidKarlas** [comment]
This is fixed. Please close.

**Comment by KirillOsenkov** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/27626
