### ISSUE TITLE
Calling GetSemanticModel with the wrong tree resulting in confusing exception message

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#26658]
**Version Used**: 2.8.0

**Steps to Reproduce**:

Execute the following code:

```c#
var tree1 = SyntaxFactory.ParseSyntaxTree("");
var tree2 = SyntaxFactory.ParseSyntaxTree(@"class C
{
    void M() {}
}");

var compilation = CSharpCompilation.Create(null).AddSyntaxTrees(tree1);

compilation.GetSemanticModel(tree2);
```

**Actual Behavior**:

```
Unhandled Exception: System.ArgumentException: SyntaxTree 'class C
{
    void M() {}
}' not found to remove
Parameter name: syntaxTree
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at Program.Main()
```

**Expected Behavior**:

Since the code is not removing anything, the exception message should not talk about removing.

The code that throws the exception is:

https://github.com/dotnet/roslyn/blob/990fbbbf1e29eca1b7e73aa755c446ce2858446d/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs#L1789-L1792

It seems it shares the message `CSharpResources.SyntaxTreeNotFoundTo` with two other methods, which actually do attempt to remove a SyntaxTree.

Also, the exception message probably shouldn't include the whole code of the `SyntaxTree`.

Putting the two issues together, the message could be just:

> SyntaxTree not found

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/26659
