### ISSUE TITLE
Newer builds of features/dataflow branch

### ISSUE THREAD

**Issue by mvacha** [dotnet/roslyn#26662]
I'm working on a prototype analyzer using the new IOperation based CFG APIs and currently, I'm using the version `2.8.0-dataflow-62824-01` from April 23rd. 

Since then there have been some changes (e.g. improved packing of cfg), but I cannot find newer builds on [MyGet.](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.Csharp)  Is it possible to get them somewhere else (e.g. different feed od nuget...)? Or if the publishing of daily builds is not automated, could you please publish a newer version? Thanks

**Comment by jmarolf** [comment]
Looks like we are publishing to MyGet for that branch, but we don't have automated builds set up (they are ad-hoc).  @jasonmalinowski any problem with enabling automated signed-builds for this branch? Otherwise I'll just have us publish on the same schedule as master so people can dogfood the apis

**Comment by jmarolf** [comment]
sorry this took awhile.  I've enabled publishing to myget on every checkin to `features/dataflow` and kicked off a build.  I'll respond back here when a new build is published

**Comment by jmarolf** [comment]
New build can be grabbed from here: https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.CSharp/2.8.0-dataflow-62910-03

**Comment by mvacha** [comment]
Thanks :)
