### ISSUE TITLE
Lightbulb fails to drop down for specific Visual Basic constants

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#26674]
Been running into issues where the light bulb fails to open the first time, and I've got a 100% repro.

**Version Used**: 

**Steps to Reproduce**:

1. `git clone http://github.com/dotnet/project-system`
2. `git checkout 51b8d9efdb99dd65e03814d803d35fc7247dc78c`
3. Open Visual Studio
4. Open src\Microsoft.VisualStudio.Editors\PropPages\ApplicationPropPageVBBase.vb (doesn't need to be in project context)
5. Go to line 498
6. Rename `prjApplicationManifest_Default` using editor until it begins rename tracking

``` VB
    Protected Const prjApplicationManifest_Default As String = "DefaultManifest"
    Protected Const prjApplicationManifest_NoManifest As String = "NoManifest"
```

7. `CTRL+.`

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/1103906/39688700-4d8cbaea-5217-11e8-8a87-946cbc51929f.png)

**Actual Behavior**:
The lightbulb doesn't open, pressing `CTRL+.` *again* causes it to open

**Comment by CyrusNajmabadi** [comment]
Closing out as not repro.
