### ISSUE TITLE
'Use pattern matching' fails to handle multiple type checks in sequence

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#26680]
**Version Used**: 15.7 Preview 6

**Steps to Reproduce**:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/64016d7dc9261d50b9c14bb2ef2920f7161019a3/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/StandardTextDiagnosticBase.cs#L131-L136

**Expected Behavior**:

```csharp
if (summaryNodes[0] is XText firstTextPartNode && summaryNodes[1] is XElement classReferencePart && summaryNodes[2] is XText secondTextPartNode)
{
```

**Actual Behavior**:

```csharp
var classReferencePart = summaryNodes[1] as XElement;
var secondTextPartNode = summaryNodes[2] as XText;

if (summaryNodes[0] is XText firstTextPartNode && classReferencePart != null && secondTextPartNode != null)
{
```

**Comment by alrz** [comment]
Already covered by https://github.com/dotnet/roslyn/pull/26097

**Comment by sharwell** [comment]
@alrz Is this a duplicate of an existing issue, or is it a new issue that I should just move immediately to **In Review**?

**Comment by alrz** [comment]
There's an umbrella issue https://github.com/dotnet/roslyn/issues/23375
