### ISSUE TITLE
C# 7.3 fixed field still requires pinning with implicit `this` reference

### ISSUE THREAD

**Issue by saucecontrol** [dotnet/roslyn#26688]
**Version Used**:  C# 7.3 / VS 15.7

**Steps to Reproduce**:

In reading through the proposal for relaxing the pinning requirement for fixed fields, I believe the following code should now be valid

```C#
unsafe struct Foo
{
    private fixed int Bar[4];

    public int FirstBar => Bar[0];
}
```

But I still get the "You cannot use fixed size buffers contained in unfixed expressions".  However, if I use an explicit `this` reference I don't get the error

```C#
unsafe struct Foo2
{
    private fixed int Bar[4];

    public int FirstBar => this.Bar[0];
}
```

Is there a reason these would be interpreted differently by the compiler?

**Comment by OmarTawfik** [comment]
* `public int M => this.Bar[0];`
* `public int M => Bar[0];`

Both forms were previously illegal, and now the first form is allowed. I think we should relax the constraints and make both forms legal.
