### ISSUE TITLE
[Proposal] Property access modifier to allow private setter access in object initializer (immutability)

### ISSUE THREAD

**Issue by nsarris** [dotnet/roslyn#26682]
Object immutability is currently implemented in c# with the use of constructors. However, this creates code that is both difficult to write (long constructors) and read. It also makes it impossible to use mapping expressions to construct immutable objects.

The proposition here is a new access modifier that explicitly dictates that a value can be set in an object initializer. It could for example be named "immutable" or "readonly" or "initonly" or "init". 

Example:

```csharp
public class Foo
{
	public string A { get; immutable set; }
	public string B { get; immutable set; }
}
```

Would allow this:

```csharp
var foo =  new Foo(){
	A = "a",
	B = "b"
}
```

but produce an error when trying to set the property elsewhere. For all intends and purposes it would be identical to the setter being public in an initializer and private anywhere else.

For anyone working with expressions or functional programming this has greate value. Besides the immutable classes themselves being cleaner and shorter, it maintains consistency when writing mapping expressions because currently you have do this (which is also not very intellisence friendly):

```csharp
query
.Select(x => new Foo(
	a: x.SomeProp, 
	b: x.SomeOtherProp, 
	c: x.AnotherProp))
```

vs this: (for muttable classes)

```csharp
query
.Select(x => new Foo {
	A = x.SomeProp, 
	B = x.SomeOtherProp, 
	C = x.AnotherProp})
```

Another issue with constructors is that you don't have an explicit map between the constructor parameter and the actual property it privately sets, so if you want to using dynamic mapping or cloning expressions with private setters you need to go by convention (name/sequence) or use attributes which means even more code or override the setter restrictions through reflection.

Finally this would make it very easy to refactor current code with immutability as it wouldn't need code changes other than the new accessor itself

**Comment by gafter** [comment]
Language proposals for C# are taken in https://github.com/dotnet/csharplang
