### ISSUE TITLE
VisualBasicCompilation.GetSemanticModel should check that the tree is valid

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#26689]
**Version Used**: 2.8.0, master

**Steps to Reproduce**:

Try to get semantic model for syntax tree that's not part of the compilation or is null:

```c#
var tree1 = SyntaxFactory.ParseSyntaxTree("");
var tree2 = SyntaxFactory.ParseSyntaxTree(@"
Class C
    Sub M()
    End Sub
End Class");

var compilation = VisualBasicCompilation.Create(null).AddSyntaxTrees(tree1);

compilation.GetSemanticModel(tree2);
compilation.GetSemanticModel(null);
```

**Expected Behavior**: Both calls to `GetSemanticModel` throw an exception.

**Actual Behavior**: Both calls to `GetSemanticModel` succeed.

---

The relevant code:

https://github.com/dotnet/roslyn/blob/50d4726c8504ee17a4f98e9212005bd05c2ddc72/src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb#L1858-L1860

https://github.com/dotnet/roslyn/blob/50d4726c8504ee17a4f98e9212005bd05c2ddc72/src/Compilers/VisualBasic/Portable/Compilation/SyntaxTreeSemanticModel.vb#L34-L40

Note that C# performs both checks:

https://github.com/dotnet/roslyn/blob/50d4726c8504ee17a4f98e9212005bd05c2ddc72/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs#L1782-L1795

**Comment by gafter** [comment]
Dup of #20761
