### ISSUE TITLE
Add flag to control nullable feature

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26692]
For the prototype, we're using LangVersion as the flag for both language version and nullable annotations.
At a minimum, we need an ability (separate from LangVersion) to disable nullable warnings.

From discussions with Chuck, we would have to decide whether this flag affects the symbols that we produce:
- pretty clearly, we would want to emit `string` (no nullable annotations)
- you type `string?` in source (with nullable warnings disabled), does QuickInfo show you `string?` back?
- maybe the IDE should grey out any `?`, since it is unnecessary. We can have a code fixer to remove the `?` or to turn on nullable warnings.

Some related questions, when the feature is turned off:
- What if you use `[NonNullTypes]` but the nullable feature is turned off? Warning?
- What about using `?` or `!`?

Tagging @cston @AlekseyTs 

Relates to https://github.com/dotnet/roslyn/issues/26199

**Comment by AlekseyTs** [comment]
I don't think LanguageVersion should affect "shape" of symbols. Otherwise, sharing of symbols is going to be affected in a negative way, as well as this is likely to complicate the Reference manager and make it dependent on ParserOptions, which never happened before.

**Comment by jcouv** [comment]
From LDM discussion today:
- we'll use a separate flag (not warning waves) to control the feature
- the flag implicitly changes top-level NonNullTypes context to be `true`
- the flag enables the flow analysis warnings
- if you use any nullability-related feature (`!`, `?` or `[NonNullTypes]`) and the flag isn't set, then we produce a new warning ("please enable the feature")

**Comment by cston** [comment]
Updated LDM decision to use `[NonNullTypes]` to enable warnings.
