### ISSUE TITLE
CSharpWinForms.RemoveEventHandler Failed in test run

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#26693]
First found in https://github.com/dotnet/roslyn/pull/26665

In [this integration run](https://ci.dot.net/job/dotnet_roslyn/job/features_NullableReferenceTypes/job/windows_release_vs-integration_prtest/426).

**Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.RemoveEventHandler** fails due to there being an error in the error-list but the build succeeded.

```ini
MESSAGE:
Assert.Equal() Failure
Expected: 0
Actual: 1
+++++++++++++++++++
STACK TRACE:
at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.ErrorList_OutOfProc.Verifier.NoBuildErrors()
at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.RemoveEventHandler()
```

![image](https://user-images.githubusercontent.com/9797472/39727166-77a32d02-5206-11e8-880c-8d3f4d1d7d6d.png)

![image](https://user-images.githubusercontent.com/9797472/39727173-84db1bd8-5206-11e8-91c5-dbe361684bef.png)

**Comment by sharwell** [comment]
Haven't seen this recently. Tests are not skipped; closing as Not Reproducible for now.
