### ISSUE TITLE
Suggestion: Use git tags for versions

### ISSUE THREAD

**Issue by SirCmpwn** [dotnet/roslyn#267]
When new versions are released (stable or otherwise), it would be very useful to packagers on non-Windows systems if they were associated with a git tag. This allows the current version to be retrieved with a shell script one-liner (`git describe --tags`).

**Comment by davkean** [comment]
@ManishJayaswal Is this on track for 1.1?

**Comment by ManishJayaswal** [comment]
@SirCmpwn @davkean We have started tagging all public releases. So I am closing this issues.

**Comment by SirCmpwn** [comment]
Thanks!
