### ISSUE TITLE
Optimize function that could be Expression-bodied function

### ISSUE THREAD

**Issue by phillyai** [dotnet/roslyn#26715]
**Version Used**: VS 15.7.0

**Steps to Reproduce**:

```csharp
int AddLambda(int a, int b) => a + b;
int Add(int a, int b) { return a + b; }
```
Two functions are exactly same, but compiler generate different IL code. Function `AddLambda` is optimized, but function `Add` is not.

```IL
g__Add0_0:
IL_0000:  nop         
IL_0001:  ldarg.0     
IL_0002:  ldarg.1     
IL_0003:  add         
IL_0004:  stloc.0     
IL_0005:  br.s        IL_0007
IL_0007:  ldloc.0     
IL_0008:  ret         

g__AddLambda0_1:
IL_0000:  ldarg.0     
IL_0001:  ldarg.1     
IL_0002:  add         
IL_0003:  ret    
```

**Expected Behavior**:

If function can be reduced to expression-bodied function, they should be compiled and generate same IL code.

**Actual Behavior**:

But they don't.

**Comment by svick** [comment]
[The IL you're seeing is generated in Debug mode](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgAQGECwAoA3nusemAHbDoCCMMAMgIYC2ARjAwBTmUNSkXoWASnQBeAHzoG6eIIDcREt2q0uA3v0rD0+dMgDsUmfPQBfPKaA=), to help with debugging.

[In Release mode, the unnecessary instructions are removed, as you expect:](https://sharplab.io/#v2:C4LglgNgPgAgTAAgMIFgBQBvdCcLAO2AQEEATUgGQEMBbAI1KoAoCiqAaPQhOgSgQC8APgRUEAah4BubLlYlyLbhy5E+CDAhgB2UROkIAvukNA==)

```il
    .method private hidebysig 
        instance int32 AddLambda (
            int32 a,
            int32 b
        ) cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 4 (0x4)
        .maxstack 8

        IL_0000: ldarg.1
        IL_0001: ldarg.2
        IL_0002: add
        IL_0003: ret
    } // end of method C::AddLambda

    .method private hidebysig 
        instance int32 Add (
            int32 a,
            int32 b
        ) cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 4 (0x4)
        .maxstack 8

        IL_0000: ldarg.1
        IL_0001: ldarg.2
        IL_0002: add
        IL_0003: ret
    } // end of method C::Add
```
