### ISSUE TITLE
Move type to %typename%.cs does not use correct folder

### ISSUE THREAD

**Issue by Nefarion** [dotnet/roslyn#26716]
**Version Used**: 2.8.0.6283008 (VS 2017 15.8.0 Preview 1)

**Steps to Reproduce**:

1.  Have two Types in File A/A/B/Class1.cs (A.A.B.Class1 & A.A.B.Class2)
2.  Use "Move type to own file" on Class2
3.  Class2 will be moved to A/B/Class2.cs and not to A/A/B/Class2.cs 
(namespaces in file are still correct after move though)

**Expected Behavior**:
Class2.cs created in same Folder.
**Actual Behavior**:
Class2.cs is created in new Folder in project root.
![movetypebug](https://user-images.githubusercontent.com/542084/39754562-e820ee22-52c2-11e8-910d-bb7365fd405a.gif)

**Comment by Nefarion** [comment]
Yes Sorry, i should have put more focus on this fact. It is true, it only happens in this case.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
