### ISSUE TITLE
Nullable types fixer should handle 'as' expressions

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#26738]
**Version Used**: Nullable Reference Types Preview (7 May 2018)

**Steps to Reproduce**:

```csharp
Type type = obj as Type;
```

**Expected Behavior**:

A code fix is provided for converting `Type type` to `Type? type`.

**Actual Behavior**:

No code fix is provided.

@jcouv Following the initial handling of `null`, this appears to be the next most common case for me.

**Comment by jcouv** [comment]
I agree. I'd noticed that one too.
I'll fix that and maybe also take a look at the tuple case `(string, string) M() => (null, null);` or `(string, string) local = default`, although it's less common.

**Comment by jcouv** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/26789
