### ISSUE TITLE
Problems with vNext preview

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#26742]
I downloaded [the vNext preview](https://github.com/dotnet/csharplang/wiki/vNext-Preview) and tried to install it, but failed:

```
>install.bat
Installing C# 8.0 Nullable Preview
Could not find a suitable Visual Studio Version
System.Management.Automation.RuntimeException: Could not find a suitable Visual Studio Version
at Get-VisualStudioDirAndId, C:\Users\Svick\Desktop\Roslyn preview\tools\utils.ps1: line 100
at <ScriptBlock>, C:\Users\Svick\Desktop\Roslyn preview\tools\install.ps1: line 16
```

As far as I can tell, the issue is that the installer considers the two versions of VS I have (`VisualStudio/15.7.1+27703.2000` and `VisualStudioPreview/15.8.0-pre.1.1+27705.2000`) too new.

Looking at the `utils.ps1` scripts, it seems my VS 15.8.0 Preview is filtered out by the `vswhere` command (`-version [15.5,15.8)`) while my VS 15.7.1 is filtered out using `$maxVersion = New-Object System.Version "15.7.0"`.

Also note that while I downloaded the vNext preview, the script says that it's installing the nullable preview.

**Comment by jmarolf** [comment]
Sorry about that I'll have a fix out.  In the meantime, go ahead and change `$maxVersion = New-Object System.Version "15.7.0"` to be `15.8.0`

**Comment by jmarolf** [comment]
@svick the wiki has been updated with the new link https://github.com/dotnet/csharplang/wiki/vNext-Preview thanks for letting me know about this!
