### ISSUE TITLE
C# 7.3 allows unmanaged pointer to fixed field without pinning

### ISSUE THREAD

**Issue by saucecontrol** [dotnet/roslyn#26743]
**Version Used**: C# 7.3 / VS 15.7.1

**Steps to Reproduce**:

Using an explicit `this` pointer to work around #26688, I am able to take the address of a fixed field, giving me an unmanaged pointer without pinning.  If I'm understanding the relaxed restrictions correctly, this should not be possible, as the pointer should only be useable as an indexer.

```C#
unsafe struct Foo
{
	private fixed byte buff1[256];
	private fixed byte buff2[256];

	public void DoUnsafeThing()
	{
		Buffer.MemoryCopy(&this.buff1[0], &this.buff2[0], 256, 256);
	}
}

```

**Comment by jcouv** [comment]
Tagging @VSadov to confirm.

For reference, the [speclet](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/indexing-movable-fixed-fields.md) on the relevant C# 7.3 feature.

**Comment by OmarTawfik** [comment]
* `public int* M => &this.Bar[0];`
* `public int* M => &Bar[0];`

Both forms were previously illegal, and now the first form is allowed (a bug, I believe). I think we should tighten the constraints and make both forms illegal.
