### ISSUE TITLE
Pattern test should inform nullability

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26745]
There should be no warning in the following, since `s is string` only matches if `s` isn't `null`.

```C#
using System;
public class C 
{
    public void M(string? s) 
    {
        if (s is string)
        {
            s.ToString(); // warning CS8602: Possible dereference of a null reference.
        }
    }
}
```

Conversely, `s is null` should also inform nullability.
Also, `s = null!`.

(update: split the null-coalesing issue into separate issue: https://github.com/dotnet/roslyn/issues/26747)

Once fixed, please update this [speclet section](https://github.com/dotnet/roslyn/wiki/Notes-on-nullability#null-tests).

Tagging @cston @gafter

**Comment by cston** [comment]
See also https://github.com/dotnet/roslyn/issues/26737.

**Comment by jcouv** [comment]
Closing this issue as dupe of #26737, and added a note there about `s is null` scenario.
