### ISSUE TITLE
Remove IBuiltInAnalyzer.OpenFileOnly

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#26758]
From #26590:

> This internal method overlaps the behavior of `DiagnosticSeverity.Hidden`. The the few analyzers relying on it for correctness already reported **Hidden** diagnostics by default. These analyzers are updated to include `NotConfigurable`, ensuring that **Hidden** severity will be used for the diagnostics in all configurations.

While the above is generally a true statement, the implementation in #26590 failed to account for two things:

1. (Minor) It started the work to make IDE0005 consistent with other analyzers, but did not complete it
2. See #23695 for a tracking issue to improve this diagnostic; the partial implementation of this behavior was not a specific blocker for removing `OpenFileOnly`.
2. (Major) It failed to account for *all* of the ways a diagnostic severity can be specified:
    1. (Handled) Can be specified as a default severity in the diagnostic descriptor 
    2. (Handled) Can be specified as disabled via the `<NoWarn>` property and/or in the diagnostic descriptor
    3. (Handled) Can be specified via a rule set file
    4. **(Not handled)** Can be specified by using special syntax in **.editorconfig**, like this:

        https://github.com/dotnet/roslyn/blob/9c9e6cae6b8ed91bbe1628f7f8552d7c87249e02/.editorconfig#L34

        In this situation, the maximum diagnostic severity specified in the **.editorconfig** needs to control the behavior of the "open file only" status. Most importantly, if the default severity for a diagnostic is **Hidden**, the **.editorconfig** needs to be able to raise the severity to **Suggestion** or higher and trigger the correct analysis behavior.

:memo: It's possible that #26590 correctly handles all of the above cases already. However, the latter case has not be specifically tested so we wouldn't be comfortable moving forward without increased testing/confidence.

**Comment by heejaechang** [comment]
I am +1 on removing this by the way. hopefully, we can address reasons we added this soon.

**Comment by CyrusNajmabadi** [comment]
Closing out.  If we wan tto do this, then we should create a work item for this actually assigned to a milestone and do it.  Speculative work doesn't help us just floating around for 6 years.
