### ISSUE TITLE
Unable to consume C# 7.2 stack-only types in VB 15.5

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#26752]
Porting over from VB language repo. ([issue](https://github.com/dotnet/vblang/issues/297))

> @Nukepayload2
> If I use stack only type in my VB code, error BC30668 will block compilation. I'm using VS2017 15.6.7.
> 
> **Steps to reproduce:**
> Create a .NET Core VB Console project.
> Edit the .vbproj file, add <LangVersion>Latest</LangVersion> in <PropertyGroup>.
> Create a .NET Standard 2.0 C# class library.
> Create a new C# code file, and add public ref struct StackOnlyType {} in that .cs file.
> Upgrade the C# project to 7.2 .
> In the VB console app, add reference to that C# project.
> Add Dim errorType As StackOnlyType to Sub Main.
> Build the whole solution.
> 
> **Expected behavior:**
> The code should compile, because I'm not trying to put a stack-only variable on the heap.
> 
> **Actual behavior:**
> Error: BC30668 "Types with embedded references are not supported in this version of your compiler"

**Comment by ahsonkhan** [comment]
**Here is a simplified repro of the issue:**

```vb
Imports System

Module Program
    Sub Main(args As String())
        Dim span As Span(Of Byte)
        Console.WriteLine(span.Length)
    End Sub
End Module

```

```vbproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.0-rc1" />
  </ItemGroup>

</Project>
```

Error	BC30668	'Span(Of Byte)' is obsolete: 'Types with embedded references are not supported in this version of your compiler.'.

> vbc /langversion:?
Supported language versions:
default
9
10
11
12
14
15 (default)
15.3
15.5 (latest)
latest

![image](https://user-images.githubusercontent.com/6527137/39952593-e339320a-554e-11e8-891b-ab0161f1f536.png)

**Comment by ahsonkhan** [comment]
Why is the compiler throwing this error in VB?

cc @KrzysztofCwalina, @jaredpar

**Comment by jaredpar** [comment]
This behavior is by design. Stack only types are not supported in VB at this time. It’s very analogous to unsafe code in its usage.

**Comment by AdamSpeight2008** [comment]
@jaredpar I don't consider it `unsafe code`, vbnet should be able to consume them as it. As I see it highly likely to be used with the framework core api for performance. Shouldn't VB user also benefit from that performance?

**Comment by VBAndCs** [comment]
This issue explodes at many .NET core APIs (as in  dotnet/runtime#43253 a) and 3rd party libraries (as in https://stackoverflow.com/questions/65074332/ignore-compiler-error-bc30668-types-with-embedded-references-are-not-supported), and be fixed.

**Comment by paul1956** [comment]
@jaredpar why was this closed? This also effects System.Text.JSON use by VB?

**Comment by CyrusNajmabadi** [comment]
> @jaredpar why was this closed? 

As mentioned in his post:

> This behavior is by design. Stack only types are not supported in VB at this time. It’s very analogous to unsafe code in its usage.

Roslyn is the C# and VB compiler (and IDE experience).  So issues here should be about if those compilers are properly implementing the respective languages.  IN this case, Roslyn is doing that.  The Vb language does not support these types, so the compiler is behaving as expected.  If you want hte VB language to support this, then that is tracked over at: https://github.com/dotnet/vblang/issues/297
