### ISSUE TITLE
TextstructorNavigator.TryFindLeaf NullReferenceException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#26788]
After closing a solution, an error dialog suggested checking the Activity Log.

This is what I found:

System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.CodeAnalysis.Editor.Implementation.TextStructureNavigation.AbstractTextStructureNavigatorProvider.TextStructureNavigator.TryFindLeafToken()

![image](https://user-images.githubusercontent.com/12449387/39910041-3f561c24-54aa-11e8-9a7a-269c2b6466e3.png)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/250784/textstructornavigatortryfindleaf-nullreferenceexce.html
VSTS ticketId: 614549_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't see any hits for this, and we haven't heard about this from anyone else.
