### ISSUE TITLE
Confirm whether misused nullability attributes should produce diagnostics

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26783]
For instance, `[EnsureNotNull]` on a value type parameter, or `[NotNullWhenFalse]` on a parameter whose containing method doesn't return a boolean.

We need to review this, as it poses a compatibility concern.
My personal view is that if we use brand new attributes in the `System.Runtime.CompilerServices` namespace, then such warnings/errors are fair game (users are not supposed to define types in `System`).

Tagging @gafter

**Comment by gafter** [comment]
@jcouv What is to prevent users from compiling code that misuses those attributes that we provide and compiling with an old, or C++ compiler?

**Comment by jcouv** [comment]
@gafter Nothing. And if they do, the flow analysis for nullability will ignore such misused attributes.
Still, I believe we should help users use those new attributes properly.

**Comment by gafter** [comment]
But then the same code will not compile with new compilers - a breaking change.

**Comment by jcouv** [comment]
Closing due to Neal's point about breaking change.
