### ISSUE TITLE
Visual Studio crashes when opening unity solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#26799]
I tried to open my unity solution after upgrading to VS 15.7.0 and it just crashes.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/246703/visual-studio-crashes-when-opening-unity-solution.html
VSTS ticketId: 612076_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_

Martin Midtgaard solved on 5/7/2018, 00:14 PM (3 days ago), 0 votes: 
<p>The problem seem to have gone away after I uninstalled the Roslyn Nullable References preview. (Roslyn_Nullable_References_Preview_March_2018)</p>

**Comment by jaredpar** [comment]
This should be fixed now.
