### ISSUE TITLE
Let nuget dependencies on Immutable and Metadata packages float

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn#2679]
Currently, the roslyn nuget packages depend on fixed versions of BCL packages.

See for example: http://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/1.0.0-rc2

**Dependencies**
* System.Collections.Immutable (**=** 1.1.33-beta)
* System.Reflection.Metadata (**=** 1.0.18-beta)

Once you adopt the stable versions, these should **>=**. There won't be breaking changes and developers should be allowed to upgrade the above without upgrading Roslyn. On the desktop framework, it will require them to have binding redirects, but those can be generated by VS, and on every other platform it will just work.

cc @jaredpar @davkean

**Comment by tmat** [comment]
I have changed the nuspec. Should be updated when we push nugets to nuget.org.
