### ISSUE TITLE
Better exception dialog needed for fixes that fail.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#268]
Ported from TFS WorkItem: <b>1081297</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P><B>Affected Branch:</B> VS2015 Preview<BR><B>Affected Build:</B> <BR><B>Affected Product Language:</B> <BR><BR><B>Steps to reproduce:</B><BR><BR>1.&nbsp; Use the "Make uppercase" diagnostic example</P>
<P>2.&nbsp; Alter MakeUppercaseAsync to return null instead of newSolution.</P>
<P>3.&nbsp; Launch/debug, and open a new project.&nbsp; Wait for squiggle to show up on the type declaration.</P>
<P>4.&nbsp; Apply fix from lightbulb --&gt; get exception dialog, and afterwards lightbulbs don't show anymore.</P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By Matthew Gertz (11/13/2014 9:00:33 AM)

<p>The code applying fixes needs to be more robust against bad Task&lt;Solutions&gt; being returned, since we have to assume that third parties producing these fixes will make mistakes, and we don't want users to get whammied by that.</p>
<p>&nbsp;</p>
<p>(Also, returning null might be completely valid, at least from the user's point of view.&nbsp; &nbsp;See <a href="https://roslyn.codeplex.com/discussions/571072">https://roslyn.codeplex.com/discussions/571072</a>&nbsp;-- a user might simply want to highlight&nbsp;a particular meta-issue via the lightbulb, and not actually apply a fix.&nbsp; Granted, this is a complete mis-use of the fix functionality, and perhaps we'd instead have some sort of advisory functionality that they could register for instead, if the error list wasn't enough (especially given it's new ability to link out) -- but I could also easily imagine a user simply wanting the &quot;fix&quot; to be&nbsp;(for example)&nbsp;a ShellEx which executes something on disk rather than changing actual code.&nbsp; </p>
<p>&nbsp;</p>
<p>(And if there's a better way to do this already, we should make sure that we document it if it isn't already. BUt we definitely shouldn't crash lightbulbs in any case.)</p>

------------------------------

2) Edited By Srivatsn Narayanan (11/13/2014 10:47:16 AM)

Spoke with Matt. We turn off just the analyzer that is faulting. However this isn't obvious from the exception dialog that comes up and it looks like VS has crashes in some way. We need better UX for reporting that we have turned off just that one fixer.

------------------------------

3) Edited By Srivatsn Narayanan (12/19/2014 2:15:26 PM)

The platform has added new APIs to show an info bar in VS and. Let's investigate to see if we can pop up an InfoBar instead of a message box.

------------------------------

**Comment by jmarolf** [comment]
@shyamnamboodiripad can you verify this?
