### ISSUE TITLE
Branch with boostrap removed fails on ubuntu

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26800]
For the `features/NullableDogfood` branch, I need to disable the boostrap, because the branch is based off of master (so as no support for LangVersion 8 or nullable feature).

The error is: `20:32:59 /mnt/j/workspace/dotnet_roslyn/features_NullableDogfood/ubuntu_16_debug_prtest/Binaries/Tools/dotnet/sdk/2.1.300-preview2-008324/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error : Could not find a part of the path '/mnt/j/workspace/dotnet_roslyn/features_NullableDogfood/ubuntu_16_debug_prtest/Binaries/Debug/Dlls/MSBuildTask/netcoreapp2.0/publish/runtimes'. ~~[/mnt/j/workspace/dotnet_roslyn/features_NullableDogfood/ubuntu_16_debug_prtest/src/NuGet/NuGetProjectPackUtil.csproj]`

Here's the PR that repro's the problem: 
https://github.com/dotnet/roslyn/pull/26622#issuecomment-387818050

From discussion with @jaredpar, the problem is in `build.sh`, which has some publishing logic conditionally on bootstrap flag being set.

**Comment by jaredpar** [comment]
Closing as this doesn't seem to be relevant now. Bootstrap is working on our linux builds even after merging in our nullable reference types work.
