### ISSUE TITLE
Incorrect nullability for double assignment

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#26812]
```c#
using static System.Console;
class C
{
    static void Main()
    {
        string? x;
        x = x = "";
        WriteLine(x.Length); // warning CS8602: Possible dereference of a null reference
        string? y;
        x = y = "";
        WriteLine(x.Length); // warning CS8602: Possible dereference of a null reference
        WriteLine(y.Length);
    }
}
```
Reported by @bgrainger.

**Comment by jcouv** [comment]
It seems this was fixed already ([sharplab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDk4BstWFiAJQkiQDsBjCAFQE8AHFAGgBMQBqAHzmQEsyA5gAJkMWLwpCAyrVEQAtgDoAwgHsyyVQQDcAWABQFXMmRDlBgN4GhNkWJgShAN1W8WQgLJR+ACgCU1rZW+rahdgj8AgD8QgAeeiFhNrFCALxxaUIARFkJSTYA6hEwEAAy/BA+sYqlEIIwABZ+2kIA9K1CAO5QCGSRZlIAHABsAAwATCBCAAqqJrz4EEIsEEikdVRCqmBCUEJk2FhCa6sbEIFJohGCMbR5+SnptJk590lFvCXlZJXVtfVNFrtLo9PqCAYjCZTWbzRbLU7rShLba7faHY4kU5Ii5hD5fCo+Wg1OoCRrNHEAXwMFKAA===)).

**Comment by jcouv** [comment]
Added test to verify
