### ISSUE TITLE
Q: How would I generate partial class for decorated target class

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/roslyn#26827]
I have a goal in mind: identify a *Target Class* with known *Attribute* decoration, then generate a partial class aligned within the *Target Class Namespace*.

In the past this might be considered an ``MSBuild`` target, which it still may be given the relative newness of ``Roslyn API``. But I think ``Roslyn`` has the potential to be a pretty good fit for the solution I have in mind.

The chief barrier I am encountering is an apparently rocky road on the migration path from ``Framework 4.x`` (i.e. ``4.6.2``) into the ``Core`` / ``Standard`` domain.

The next barrier I am encountering now are obscure naming conventions of the ``Roslyn API``, sparse documentation, if documented at all, identifying the desired language syntax, keywords, etc.

For instance, assuming ``KnownBase`` class.

```C#
class abstract KnownBase<T>
    where T : KnownBase<T>
{
    protected T SomeOp(T a, T b)
    {
        // do SomeOp involving a and b operands and return a new T
    }
}

class KnownAttribute : Attribute
{
}
```

And an end user usage of that class:

```C#
namespace Some.Name.Space
{
    [Known]
    class TargetClass : KnownBase<TargetClass>
    {
    }
}
```

Then generate the facade:

```C#
namespace Some.Name.Space
{
    class partial TargetClass
    {
        /* TODO: this is for illustrative purposes only;
         yes, I know, '#' is not an operator, per se; sub in operator(s) of interest... */
        public static TargetClass operator #(TargetClass a, TargetClass b)
        {
            return SomeOp(a, b);
        }
    }
}
```

Couple of nuances I expect to handle are:

1. Alignment to ``TargetClass`` ``Namespace``; may or may not preclude nesting within a class
1. Responding to refactor requests, i.e. to rename ``TargetClass``, and all that this implies, such as renaming/replacing generated code file
1. Should add the partial class to the ``TargetClass`` project, if possible as a child element of ``TargetClass``
1. Add auto-generated dislaimer comments to the class and/or overall file
1. And on from there...

I am building upon ``CodeGeneration.Roslyn``, but this is only a minor facade to the deeper ``Roslyn`` related questions.

Further, at least at the moment, I am also running in ``VS2015`` targeting ``NET Framework 4.6.2`` as at least a first draft. Potentially on a migration path into ``NET Standard``, but not right now, or at least not until Core/Standard is more proven. That said, I am not positive that I'm not faced with a ``2017`` migration sooner than later in order to be able to pursue this path.

**Comment by svick** [comment]
First of all, the code you've shown wouldn't work: if you want to have a single class declared multiple times, all declarations need to be `partial`, having just one of them `partial` is not enough.

Second, I suggest you migrate to VS 2017 now. I don't see any good reason to stay on VS 2015. If you want to target .Net Framework 4.6.2, you can still do that from VS 2017.

Third, I'm not sure what exactly are you asking here. Maybe you could ask more specific questions? If you're struggling with figuring out how some C# code is represented in a Roslyn syntax tree, I suggest you use [SharpLab's Syntax Tree mode](https://sharplab.io/#v2:C4LghgzsA+B2YFsCmEAOYDGSAEBlA9sgHQByiSRu6WAsAFADe92L26ATsAJZgA22AAQBM2ACph2AcyTAAwr0gRmrJnVbrsAegBUYgPIARPSGzAAFlwjZL2AGb5213rwCuUdmG4A3HKhftUfAgUbHxYXgBPAG5lDRYIlAAabABJbABrWHwAd2SAcgBiPOsrLOBsMFhQ1CQPYAdkmsdgqOwIFwAjayr8Js8HAAoIAEpQ227gWpRgIlnsbU1YjQEAZkEARgA2MQlpOQUIK17a/scAagHxKRl5RQrkq73bw+wO4aX1VTi4gQB2PEISD0qAGYGSbxiam+AF8lrC6NCgA=). If you then want to  find out how to generate the syntax tree yourself, [Roslyn Quoter](https://roslynquoter.azurewebsites.net/) can help.

**Comment by mwpowellhtx** [comment]
@svick Thanks for the response. I'll have a look at those two bits.

So that's one thing my generator should do, likely, is ensure the target class is also partial when it renders the operators. Thanks for noticing that.
