### ISSUE TITLE
QuickInfo doesn't display nullability on properties

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26830]
Seems like I only fixed the problem for methods, but not other kinds of API.

![image](https://user-images.githubusercontent.com/12466233/39971304-9ac61564-56ad-11e8-96fd-11598a6a55d9.png)

Relates to https://github.com/dotnet/roslyn/issues/26648
Found in nullable dogfood.

**Comment by jasonmalinowski** [comment]
Not sure why that wasn't specifically working, but works fine now.
