### ISSUE TITLE
Nullability fixer for interface implementations

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26833]
When a declaration and an implementation disagree on nullability, a warning is produced.
Given It would be convenient to have a one-click solution to either:
- change the declaration to match this implementation (this would be especially convenient because navigating to the declaration isn't easy at the moment),
- change this implementation to match the declaration.

![image](https://user-images.githubusercontent.com/12466233/39976813-9d0bee9c-56ea-11e8-8865-0bc00b4f2279.png)

There is a similar situation with overrides, but at least there, you can easily GoToDefinition to find the declaration.

Note: this fixer should not have a FixAll.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
