### ISSUE TITLE
Improve the analyzer load failure diagnostics: CS8032, CS8033 and CS8034

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2683]
Currently, the diagnostics generated for analyzer load or instantiation issues are too generic and not to helpful to diagnose the root cause of failure. We have 3 of them (and corresponding VB counterparts), all of which can be enhanced:

1) **CS8032**, i.e. `WRN_AnalyzerCannotBeCreated = 8032` (http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Errors/ErrorCode.cs,1269) invariably has the below message:

```
Severity	Code	Description	Project	File	Line
Warning	CS8032	An instance of analyzer Analyzer5.Analyzer5Analyzer cannot be created from C:\Users\mavasani\Documents\Visual Studio 2015\Projects\Analyzer5\Analyzer5\Analyzer5\bin\Debug\Analyzer5.dll: Exception has been thrown by the target of an invocation..	ClassLibrary1		1
```

We should consider embedding the exception stack trace in the diagnostic's description (on same lines as analyzer exception diagnostics here: http://source.roslyn.io/Microsoft.CodeAnalysis/R/f9e46cc7c756e697.html).

2) **CS8033**, i.e. `WRN_NoAnalyzerInAssembly = 8033` (http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Errors/ErrorCode.cs,1270) has the below message:
`The assembly {0} does not contain any analyzers`.

We generate this diagnostic only when an analyzer assembly has types marked with "DiagnosticAnalyzerAttribute" but has no analyzers for a specific language OR there is mismatch between assembly version of Microsoft.CodeAnalysis.dll referenced by the analyzer vs used by the analyszer host (command line build/IDE). We can make this error message more helpful by pointing out the exact reason, as we already have this information at the point we generate this diagnostic: http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerFileReference.cs,186

3) **CS834**, i.e. `WRN_UnableToLoadAnalyzer = 8034` (http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Errors/ErrorCode.cs,1271). Even this diagnostic has just the exception message that caused Assembly load to fail for the analyzer reference assembly. We should embed the exception stack trace in the description here: http://source.roslyn.io/#Microsoft.CodeAnalysis/CommandLine/CommonCommandLineArguments.cs,347

**Comment by mavasani** [comment]
Moving this out for 1.1, this is an enhancement which is not important for 1.1.

**Comment by gh3x78E** [comment]
What can be the various reasons for a CS8032 error to be thrown? In my case I can compile and use the Analyzer on my machine (VS2015 Update 2), but when our TFS runs the build I get the following message (I translated it to English) for each rule and the build fails:

CSC : error CS8032: An instance of analyzer StyleCop.Analyzers.DocumentationRules.SA1644DocumentationHeadersMustNotContainBlankLines-Analyzers cannot be created from ...: The file or assembly "Microsoft.CodeAnalysis, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" could not be.

However I have the right DLL in the right version checked-in and in place.

**Comment by mavasani** [comment]
> What can be the various reasons for a CS8032 error to be thrown

The primary reasons are:
1. You have an older compiler toolset/VS then the version of Microsoft.CodeAnalysis package that your analyzer was built against. You need to upgrade your compiler toolset/VS if you face this.
2. One of your analyzer dependencies is not marked as an analyzer, and hence can't be found at runtime.

Your above comment indicates that your TFS build is using an older version of compiler toolset. Can you debug into your TFS build machine, trigger a build, open the location of VBCSCompiler.exe and verify the binary version of Microsoft.CodeAnalysis.dll alongside it?

**Comment by gh3x78E** [comment]
@mavasani Thanks for the hint. I actually had to install Visual Studio Update 2 on the machine I run the builds because the analyzers were compiled on a Visual Studio instance which had Update 2 installed.

**Comment by mavasani** [comment]
We now embed the assembly fusion log in the diagnostic, which is sufficient for most cases. We can re-visit this if we get user requests.

**Comment by DNFL** [comment]
I also encountered a similar CS8032 error: unable to create an instance of the parser xxx' from 'path'': failed to load the file or assembly 'yyy' or one of its dependencies. The system cannot find the specified file.
But the strange thing is that when I move the code from 'yyy' into' xxx' and generate it again, there are no errors. And I undo the operation and repeat the error.
