### ISSUE TITLE
Consider colorizing the suppression operator `!` to make it more visible

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26835]
![image](https://user-images.githubusercontent.com/12466233/39978730-0d033960-56f7-11e8-9964-bbcf81ec4cfe.png)

**Comment by CyrusNajmabadi** [comment]
Operators are generally already classifiable.  Do you think there's a need for a specific color here?  Looking at the code it seems hard to miss the ```!```.  Thoughts?

**Comment by jcouv** [comment]
Given that suppression operators are supposed to be rare and generally avoided (especially once `Debug.Assert` and other mechanisms are in place), I do think the `!` should stand out more than other operators. For instance, in this theme, I could see it being blue, or orange, or maybe bold?

It's possible the screenshot doesn't do the problem justice. In a full page of code, it's not easy to spot the `!`, but I feel it should be.

**Comment by sharwell** [comment]
This seems more like a place for a diagnostic than a colorization feature. Also note that we still haven't addressed #1482, which I find is even more prone to misuse.

**Comment by sharwell** [comment]
Tentatively marking this as **Won't Fix** prior to a design review today, but will leave it open until we review this resolution in the review.

**Comment by gafter** [comment]
In support of **Won't Fix**: http://gafter.blogspot.com/2017/06/making-new-language-features-stand-out.html

**Comment by jcouv** [comment]
I'm fine with closing based on feedback so far.
