### ISSUE TITLE
SQLite is too slow

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#26841]
Open Roslyn.sln and I see devenv is consuming 1 CPU full more than 30 seconds and I see that is solely because Sqlite reading data from disk.

I think we should do some benchmark or test to see whether there is better option than Sqlite.

basically, I think Sqlite is just too slow for the way we use it (basically, we use it as key/value (blob) store not structured data store. and I dont think SQLite is good at this usage perf wise)

**Comment by sharwell** [comment]
@heejaechang If you could construct a test sequence that demonstrates this behavior in a controlled environment (easy to measure SQLite performance independent of the rest of the system), it would be _tremendously_ valuable in resolving this.

**Comment by CyrusNajmabadi** [comment]
Agreed.  This was measured when the original sqlite work was done, and there were no regressions at all in performance.  Specifically, neither loading solutions not setting up OOP regressed (this was testing with Roslyn itself).

Maybe something has changed, or there is some usage pattern that is a problem, but we should understand the issue versus just assuming that sqlite is not a good fit for this.

**Comment by CyrusNajmabadi** [comment]
> I see devenv is consuming 1 CPU full more than 30 seconds and I see that is solely because Sqlite reading data from disk.

Can you be specific about which calls are happening?  THis is somewhat surprising as it means we've moved from being IO bound (expected when reading from disk) to CPU bound.  So somehow the computatoin sqlite is doing in your measurements are *more* expensive than actually reading from disk (which would be super surprising).  It would be good to have the traces to understand what part of hte stack is actually costing CPU here.  For example, is it in the low level sqlite library itself? Is it sqlitepcl? etc. etc.

**Comment by CyrusNajmabadi** [comment]
Was not able to repro this.   Have been testing this with the new work to always have this on.  No regressions and no unexpected numbers are popping up.  Closing out.
