### ISSUE TITLE
IDE0032: "Use auto property" introduces an additional newline

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#26858]
**Version Used**: 
15.7.1

**Steps to Reproduce**:
```cs
class Foo
{
    private readonly object bar = new object();

    public object Bar => bar;
    public int Baz => 0;
}
```
Run the code fix for IDE0032 on the `bar` member.

**Expected Behavior**:
```cs
class Foo
{

    public object Bar { get; } = new object();
    public int Baz => 0;
}
```

**Actual Behavior**:
```cs
class Foo
{

    public object Bar { get; } = new object();

    public int Baz => 0;
}
```
Note the additional empty line between `Bar` and `Baz`.

![ide0032-additional-newline](https://user-images.githubusercontent.com/1947968/40052956-d0a937b8-583f-11e8-8622-9e3c86d0e35e.gif)

Another thing that I saw in the gif: Why does VS scroll down the editor window by one line?

**Comment by sharwell** [comment]
:memo: This is similar to #26677, but affects a different code fix
