### ISSUE TITLE
Is with variable assignment should not check the value of a bool

### ISSUE THREAD

**Issue by MichaelRumpler** [dotnet/roslyn#26859]
**Description**:

Generic type checking of a variable with assignment to another variable looks like this:

    if(genericVar is T outValue)

With this code I only want to check the type and not the value of the variable.
Currently this is not the case. If `T` is `bool` and the value of `genericVar` is `false`, then the `if` block is not executed. The `if` checks the value of the variable and not only the type.

**Version Used**: 
VS 15.8.0 Preview 1.1

**Steps to Reproduce**:

	public class Generic<T>
	{
		public T Value { get; set; }
	}

	public void GenericTest()
	{
		var t = new Generic<bool> { Value = true };
		var f = new Generic<bool> { Value = false };

		if (!(t.Value is bool tv))
			throw new Exception("t.Value is no bool");
		if (!(f.Value is bool fv))
			throw new Exception("f.Value is no bool");

		CheckTypeWithIs(t);
		CheckTypeWithIs(f);

		CheckTypeWithIsAndAssignment(t);
		CheckTypeWithIsAndAssignment(f);
	}

	private void CheckTypeWithIs<T>(Generic<T> g)
	{
		if (!(g.Value is T))
			throw new Exception($"g.Value ({g.Value}) is no T");
	}

	private void CheckTypeWithIsAndAssignment<T>(Generic<T> g)
	{
		if (!(g.Value is T gv))	  // the gv at the end is the only difference to the previous method
			throw new Exception($"g.Value ({g.Value}) is no T");
	}

**Expected Behavior**:

This code should run without throwing exceptions. I.e. if I check `if(x is T gv)` then only the type should be checked and not the value of the variable.

**Actual Behavior**:

In the very last case where `CheckTypeWithIsAndAssignment(f)` is called, the value of `gv` in the method seems to be evaluated and the exception is thrown.
It works fine if the type is `bool` and not a generic `T` or if there is no assignment to a variable.

**Comment by Neme12** [comment]
Tagging @gafter

**Comment by gafter** [comment]
The same problem happens with `int` and the value zero.

**Comment by gafter** [comment]
This is a dup of https://github.com/dotnet/roslyn/issues/26387 and will be fixed in 15.8.
