### ISSUE TITLE
C# 7.3 'unmanaged' cannot used by types with const size array fields [MarshalAs(UnmanagedType.ByValArray, SizeConst = xxx)]

### ISSUE THREAD

**Issue by AlexeiScherbakov** [dotnet/roslyn#26854]
In Visual Studio 15.7.1, types with array fields with const size cannot be used in new methods with unmanaged constraint

For example
Old code

```C#
public static unsafe void ReadMessage<TMessage>(byte[] messageBuffer, ref TMessage message)
	where TMessage : struct
{
    if (BitConverter.IsLittleEndian)
    {
        fixed (byte* ptr = messageBuffer)
        {
            var test = (TMessage)Marshal.PtrToStructure(new IntPtr(ptr), typeof(TMessage));
            message = test;
        }
    }
    else
    {
        throw new NotImplementedException("Big endian architecture is not supported");
    }
}
```

New code

```C#
public static unsafe void ReadMessage2<TMessage>(byte[] messageBuffer, ref TMessage message)
    where TMessage : unmanaged
{
    if (BitConverter.IsLittleEndian)
    {
        fixed (byte* ptr = messageBuffer)
        {
            message = *((TMessage*) ptr);
        }
    }
    else
    {
        throw new NotImplementedException("Big endian architecture is not supported");
    }
}
```

Code, which use new function cannot compile with error:
'error CS8377: The type 'TMessage' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'TMessage' in the generic type or method 'MessageUtils.ReadMessage2<TMessage>(byte[], ref TMessage)''

```C#
public struct MessageTest
{
    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 16)]
    public int[] Array;
}
```

What is wrong?

**Comment by svick** [comment]
As far as I understand it, [the `unmanaged` constraint](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/blittable.md) doesn't have anything to do with `MarshalAs` or marshaling in general.

If you want to use a const-size array with `unmanaged`, [you will need to make it `fixed`](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AAgAwAEhAjANwCwAUPYQEykDC9A3vaT+QCykAsgApBcKFAgBzOABVxMUmACU3Xlzq8tpAEpwIAEzETpcJgB5jkmfNgA+YQDsArgBtXSUgjjYly2pq8AL5qPPQAkIQAzOQUAGykzo6S2HD8uvpG4tZm5rJWpg7AuPAA2gC6StmmAELO2KnIXj6k+dUyVSYyqoHapADuABaIaW1daSCJjpCOpgahpBp9PDikwjWYMKwA9o4YCPAIAHQAklAAMpswrnAAoo4GmBCOPcuLC2/YmAAecAZrxXgACpSAAHGAIUgAXk6OTqDUQrze6g+yJ4YHaaRhQOEwjGOSByjBEP8qL6IV62gpbzgrigcDJ70pbxggwQ236pEccE5ADltjATmBQTcMY54AZbt8AMZwcGYXbCABEGykpDgDyejlIEAQ0sGmzg0pgzm8pEwUC5AtIUGcoNB2wOfyVpOZwQWQS09ApjBiSRSaVgCGcxqEmNsME4C2ipC+v3+mHFpAAgggEBBcKV4uUAkEgA=):

```c#
public unsafe struct MessageTest
{
    public fixed int Array[16];
}
```

**Comment by AlexeiScherbakov** [comment]
fixed fields have a drawback - all access to it must be marked as unsafe.

**Comment by mikedn** [comment]
> fixed fields have a drawback - all access to it must be marked as unsafe.

That doesn't change the fact that `unmanaged` doesn't have anything to do with marshaling. Your first example uses marshaling as a form of serialization - to produce an array of bytes out of managed object. Adding a marshalling attribute to a managed object doesn't magically make the object unmanaged.

**Comment by jcouv** [comment]
Tagging @OmarTawfik FYI

**Comment by OmarTawfik** [comment]
That is true. Arrays are managed by default. This is why you're getting the original error. To simplify the example:
```csharp
public class Test
{
    void M<T>() where T : unmanaged
    {
    }
    void N()
    {
        M<MessageTest>();
    }
}
public struct MessageTest
{
    public int[] Array;
}
```
Produces: `error CS8377: The type 'MessageTest' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'T' in the generic type or method 'Test.M<T>()'`
