### ISSUE TITLE
Design assemblies should be built with a lower version of .NET

### ISSUE THREAD

**Issue by dotMorten** [dotnet/roslyn#26874]
**Version Used**: 

Xamarin.Forms 3.0.0.446417
**Steps to Reproduce**:

1. Create a .NET 4.6.1 WPF app and reference Xamarin.Forms.Platform.WPF
2. Compile.
3. Observe warnings

**Expected Behavior**:
No warnings.

**Actual Behavior**:
```
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2052,5): 
warning MSB3274: The primary reference "Xamarin.Forms.Core.Design, Version=2.0.0.0, Culture=neutral, processorArchitecture=MSIL"
 could not be resolved because it was built against the ".NETFramework,Version=v4.7" framework. 
This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.1".

1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2052,5): 
warning MSB3274: The primary reference "Xamarin.Forms.Xaml.Design, Version=2.0.0.0, Culture=neutral, processorArchitecture=MSIL"
 could not be resolved because it was built against the ".NETFramework,Version=v4.7" framework. 
This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.1".
```

The design projects are compiled with a .NET version that is too high. despite these projects saying v4.5 is supported. Design assemblies really shouldn't be running with versions higher than what the design assemblies they are building on top of are built for.

Example:
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core.Design/Xamarin.Forms.Core.Design.csproj#L12

**Comment by sharwell** [comment]
💭 This seems like a bug for [xamarin/Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms/). Am I missing something?

**Comment by dotMorten** [comment]
ARGH! I need coffee. Sorry!
