### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp.PatternSwitchBinder.BindSwitchExpressionAndSections uses C# binder to bind sections that declare locals

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#26896]
See Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.ExpressionVariableInCase_1 unit-test for example

A BoundSwitchSection is created instead of BoundPatternSwitchSection, locals are not preserved in the bound tree and not exposed in IOperation tree. This is blocking CFG work

**Comment by AlekseyTs** [comment]
It would be good make the fix in features/dataflow branch and accompany it with a Control Flow Graph test that asserts that the locals are present in the right region. A unit-test SwitchFlow_29 in src\Compilers\CSharp\Test\Semantic\IOperation\IOperationTests_ISwitchOperation.cs looks like a good example that could be cloned with slightly adjusted scenario.

**Comment by AlekseyTs** [comment]
Here is the unit-test for this issue:
```

        [CompilerTrait(CompilerFeature.IOperation, CompilerFeature.Dataflow)]
        [Fact]
        public void SwitchFlow_34()
        {
            string source = @"
public sealed class MyClass
{
    void M(int result, bool input)
    /*<bind>*/{
        switch (input)
        {
            case TakeOutParam(3, out var x1):
                result = x;
                break;
        }
    }/*</bind>*/
    static bool TakeOutParam(int y, out int x) 
    {
        x = y;
        return true;
    }
}
";
            var expectedDiagnostics = DiagnosticDescription.None;

            string expectedFlowGraph = @"
";
            VerifyFlowGraphAndDiagnosticsForTest<BlockSyntax>(source, expectedFlowGraph, expectedDiagnostics);
        }
```

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/26918
