### ISSUE TITLE
LLVM

### ISSUE THREAD

**Issue by tom3m** [dotnet/roslyn#26897]
Not sure that is right repo for that kind of questions, sorry about that.

Recently Oracle has released GraalVM that opens lot's of possibilities to share code between languages. Like java and all supporting LLVM. This opens lot's of scenarios previously was not possible. Like when you write on the lang and lib you need is not available on that lang is not a problem anymore. That works fine for most of the popular languages but the C#/.NET. LLVM repo seems to be dead, unfortunately. If we could compile to the LLVM we will be able to:
1. Finally, mix Java&.NET and actually LOT's of currently used languages in one process
2. Run .NET code on the GraalVM that is available on more platforms that Core right now 

That could bring a whole new wave of devs starting using .NET as it won't be "that different" anymore, and it won't need them to lock on the Microsoft universe anymore, as will let them to reuse whole world of already written libs on many languages.

**Comment by jaredpar** [comment]
I think this issue would probably be more appropriate on the [coreclr](https://github.com/dotnet/coreclr) repository. It's not really feasible for C# to generate LLVM without some initial driving by the runtime.
