### ISSUE TITLE
Block wrapping option inconsistent with try/catch/finally

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#26899]
**Version Used**: 15.7

**Steps to Reproduce**:

1. Uncheck wrapping option **Leave block on single line**
1. Type the following code:

    ```
    try{}catch(Exception){}finally{}
    ```

**Expected Behavior**:

```csharp
try
{
}
catch (Exception)
{
}
finally
{
}
```

**Actual Behavior**:

```csharp
try
{
}
catch (Exception) { }
finally { }
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback
