### ISSUE TITLE
Collection Initializers don't show Quick Fixes to import extension methods

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#269]
Ported from TFS WorkItem: <b>1105748</b>

------------------------------

@SSL reported:</i><br><br>Source:<br><br>
```C#
class X : IEnumerable 
{
       public IEnumerator GetEnumerator() {		
          new X { 1 };
          return null;
	}
}
namespace Ext {
	static class Extensions {
		public static void Add(this X x, int i) { }
	}
}
```
The `new X` callsite should show a quick fix for `using Ext`.
-----------------------------

**Comment by jmarolf** [comment]
@shyamnamboodiripad can you verify this?

**Comment by shyamnamboodiripad** [comment]
Sure I will
