### ISSUE TITLE
Quick Actions menu loading is canceled on clicking Enter key

### ISSUE THREAD

**Issue by josefpihrt** [dotnet/roslyn#26905]
**Version Used**: VS 15.7.1

When I know in advance that I want to apply first action from the Quick Actions menu I can do it fast by clicking Enter immediately after Alt+Enter. I used this pattern frequently.

Starting from ~15.7 this pattern is not applicable anymore because clicking Enter cancels loading of the menu.

#### Before 15.7
1. Click Alt+Enter
2. Immediately click Enter
3. The menu is displayed first action is applied and menu disappears.

#### After 15.7
1. Click Alt+Enter
2. Immediately click Enter
3. Menu loading is canceled
4. New line is inserted into text

Current state forces me to wait till the menu is displayed and only then I can click Enter even if I know that I want to apply first action.

I would propose to return to previous state where the menu loading is not canceled on clicking Enter. If I want to cancel menu loading I can click cancel button or Esc.

**Comment by CyrusNajmabadi** [comment]
Tagging @olegtk Oleg, i believe i've seen code in the lightbulb that tries to do some 'interesting' async stuff.  Could that be impacting things here?

**Comment by olegtk** [comment]
I don't believe we changed anything in 15.7 though. @gundermanc ?

**Comment by gundermanc** [comment]
No notable changes to lightbulb in this timeframe, just a null check bug fix. Do you have a semi-reliable repro that you can share?

**Comment by JosefPihrt** [comment]
The four steps that I mentioned above are the repro.

I have updated to 15.7.1 so I cannot reproduce previous behavior but it works like that as far as I can remember.

**Comment by sharwell** [comment]
:memo: I've relied on the "Before 15.7" behavior heavily to work around bugs where the lightbulb randomly disappears.

**Comment by sharwell** [comment]
I can reproduce this if I quickly press <kbd>Ctrl</kbd>+<kbd>.</kbd>, <kbd>Enter</kbd> before the light bulb has a chance to appear. I believe that in a previous release, this sequence would block waiting for light bulb information to become available, but it now results in a newline.

Once I wait long enough for the light bulb icon to appear, the rapid sequence works the way I would expect (blocks waiting for the menu to appear, then applies the first action).

**Comment by sharwell** [comment]
@olegtk @mavasani to review the previous comment against expected light bulb behavior.

**Comment by CyrusNajmabadi** [comment]
Clsoing out as external.  @olegtk if anything wants to eb done here.  though we haven'th eard any feedback in 5 years, so probably not.
