### ISSUE TITLE
Invalid simplifications

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#2691]
The IDE incorrectly considers casts (float*) and (uint) to be unnecessary in the following cases:

```C#
        public float ReadSingle(byte* ptr)
        {
            return *(float*)ptr;
        }
```

```C#
        private readonly byte* _endPointer;
        private byte* _currentPointer;

        private void CheckBounds(int byteCount)
        {
            if (unchecked((uint)byteCount) > (_endPointer - _currentPointer))
            {
                ThrowOutOfBounds();
            }
        }
```

**Comment by tmat** [comment]
Consider this P1. These are dangerous incorrect refactorings.

**Comment by Pilchie** [comment]
Clearing milestone and moving to analyzers for triage

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/b309d296329829e2f8ef4cda4e42ccb547dd6903 in stabilization branch.
