### ISSUE TITLE
Setting the LangVersion in .VBProj

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#26933]
**Version Used**:
```Microsoft Visual Studio Professional 2017 Preview
Version 15.8.0 Preview 1.1
VisualStudio.15.Preview/15.8.0-pre.1.1+27705.2000
Microsoft .NET Framework
Version 4.7.03056

Visual Basic Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
```
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>TypeOfManyViaOperators_Example</RootNamespace>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
    <StartupObject>Sub Main</StartupObject>
    <LangVersion>15.5</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.5</LangVersion>
  </PropertyGroup>
</Project>
```

I've tried setting `<LangVersion></LangVersion>` in `vbproj` file with the following values and it seems to not be passed to the IDE or the Compiler via the VS2017 Experimental Instance.
```
15.3
15.5
Latest
```
 As a result I am unable to test / try out my changes.
Note: The Unit Test is working correctly (well it indicate that it passes). (see `[unittest](https://github.com/dotnet/roslyn/pull/26865/files#diff-b5061195acc1fa28a4ef716754f4b9d5)`), Though I am directly setting the language version.

I would help if we enabled the following project feature for VB.net as well to add  [How-to-change-targeted-Csharp-version-in-Visual-St](https://www.codeproject.com/Tips/865579/How-to-change-targeted-Csharp-version-in-Visual-St)

**Comment by jaredpar** [comment]
> I've set <LangVersion>Latest</LangVersion> in vbproj file and it is being passed to the IDE or the Compiler via VS2017. 

Not sure what bug you are reporting here. You've indicated the project file contents correctly pass to the compiler.

**Comment by AdamSpeight2008** [comment]
@jaredpar Sorry I didn't realise that I had miss wrote the original issue. *dyslexic* I've updated it.

**Comment by jaredpar** [comment]
Can you provide the vbproj file where you use latest?

**Comment by AdamSpeight2008** [comment]
@jaredpar It's it that same except for the `15.5` is `Latest`. Also updated the post.

**Comment by svick** [comment]
@AdamSpeight2008 Why does the `vbproj` in the first post specify `<LangVersion>` twice?

**Comment by AdamSpeight2008** [comment]
@svick Trying find out where to place it. _Can't find an example._

**Comment by AdamSpeight2008** [comment]
@jaredpar  Narrowed down the issue. I'm using `VisualStudioSetup` and isn't using the correct value.
