### ISSUE TITLE
Incorrect indentation in for loop

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#26935]
I have a for loop and I'm just writing out the comments to abstract what I have to do. But if I press enter to make a space between my comments, VS indents back to the closing brace instead of aligning with the for loop body.

```
    // comment
    | < here's the cursor, now press enter >
}
```

...

```
    // comment
| < here's the cursor, now aligned with brace >
}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/254087/incorrect-indentation-in-for-loop.html
VSTS ticketId: 617003_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  I get:

![image](https://user-images.githubusercontent.com/4564579/217944188-6553134f-ef93-4dba-8b7f-c5a5e5b02c44.png)
