### ISSUE TITLE
Type inference does not work when a single generic interface is implemented more than once

### ISSUE THREAD

**Issue by impworks** [dotnet/roslyn#26940]
**Version Used**:
C# 7.2

**Steps to Reproduce**:

Compile the following snippet:
```
interface I<T> { }
class X<T> { }
class Y { }
class Z { }
class C : I<X<Y>>, I<Z> { }
public class P
{
	static void M<T>(I<X<T>> i) { }
	public static void Main()
	{
		M(new C());
	}
}
```

**Expected Behavior**:

The code compiles successfully.

**Actual Behavior**:

Compilation error CS0411: The type arguments for method `P.M<T>(I<X<T>>)` cannot be inferred from the usage. Try specifying the type arguments explicitly.

**Suggestions**:

Discussion of this issue with Eric Lippert on StackOverflow:
https://stackoverflow.com/questions/50390761/
He suggests two options: improving the algorithm or the error message.

**Comment by gafter** [comment]
Improving the diagnostic for this case (presumably, to include something like "because the type inherits from more than one instantiation of the interface") might be hard, because at the time we notice that it inherits more than one instantiation, we don't have any idea that inference is going to fail (because we have no other source by which to infer those type parameters).

**Comment by impworks** [comment]
It gets worse when ther's more than one override of `M`:

```
interface I<T> { }
class X<T> { }
class Y { }
class Z { }
class C : I<X<Y>>, I<Z> { }
public class P
{
	static void M<T>(I<X<T>> i) => Console.WriteLIne("Generic");
	static void M(object i) => Console.WriteLIne("Object");

	public static void Main()
	{
		M(new C());
	}
}
```

From the first glance, this must either select the generic override (because it is more specific), or at least fail with an ambiguity error. However, it compiles successfully without even a warning.

**Comment by gafter** [comment]
This is per spec. See https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#lower-bound-inferences .

Moving to the csharplang repo for further discussion.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #1592](https://github.com/dotnet/csharplang/issues/1592) via [**ZenHub**](https://www.zenhub.com/)
