### ISSUE TITLE
Include link to install visualizer VSIX in bread crumb

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#2695]
At some point I think we were going to merge the syntax visualizer VSIX into the project templates VSIX.

But currently they are two separate VSIXes that analyzer authors would need to install. The breadcrumb that we have in VSSDK today only includes a link to install the project templates and there is no mention of the visualizer. This means users have to search online and figure out the correct version to install.

We should fix this by including an additional link to install the visualizer in the below html.

![capture](https://cloud.githubusercontent.com/assets/10579684/7600839/6e921988-f8c4-11e4-963c-fe7d91451beb.PNG)

It would be great to fix this for **1.0** since the visualizer is an essential tool for building analyzers and fixers.

**Comment by shyamnamboodiripad** [comment]
cc @jmarolf @srivatsn

**Comment by jmarolf** [comment]
fixed with Changeset 1471973

**Comment by shyamnamboodiripad** [comment]
@srivatsn Could you please verify this once we have a build with this change in it?

**Comment by lgolding** [comment]
Can't verify this yet because the fwlink hasn't yet been updated.

**Comment by jmarolf** [comment]
Link is updated now.

**Comment by lgolding** [comment]
The link now correctly points to the Roslyn SDK download (which includes the Syntax Visualizer). I think the page itself should be clearer about the fact that when you click the Download button, you're getting the entire SDK (not just a few project templates), but we can talk about that separately.
