### ISSUE TITLE
Dashboard for analyzer management

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#2697]
Today, when we have a crash from a code fix, we display the following yellow info bar 
![capture](https://cloud.githubusercontent.com/assets/10579684/7601557/adba08a2-f8cc-11e4-80b2-bd0551187dc3.PNG)

Internally we log the error (with stack trace) to the activity log - but there is no link / text pointing to the activity log in the displayed info bar. This means that the fix refactoring author has to guess and figure out that they must look in the activity log.

For crashes from analyzers, we display a nice error in the error list with the stack trace embedded in an expanding section. I feel this is a desirable experience for the following reasons 
1. It is easy for analyzer authors to debug such errors while they are developing the analyzer. They don't have to jump out of VS and open the activity log that lives in an obscure location.
2. It is easy for end users to pass on information to analyzer authors when they run into crashes from the analyzer. They can simply copy paste information (including stack trace) from the error list to the bug report.

I think we should enable an identical experience for crashing fixes and refactorings -
1. Continue to display the yellow info bar that alerts users of the crash and allows then to re-enable the failing fix.
2. Display an error (with embedded stack trace) in the error list similar to the experience for analyzers above.
3. Optionally include some text in the info bar telling users that more detailed information about the failure is available in the error list.

I am not sure if we can do this for **1.0 (stable)** but it would be nice to do this soon so that as the community starts building more Roslyn based fixes and refactorings, it is easier for both end users and fix authors to debug failures.

EDIT: This could be part of a larger dashboard that allows permanent disabling, stack trace histories, etc.

**Comment by dpoeschl** [comment]
@shyamnamboodiripad How does the user make the error in the error list go away for an analyzer failure currently? How would they make it go away for a fixer/refactoring failure after this change?

When an analyzer fails, that's very important to know about, because it means that I *may* have non-conforming code and the analyzer is incapable of alerting me about that problem. When a fixer/refactoring fails, it may be before or after it's applied some changes, but either way I can undo or look through the changes (assuming it's under source control) and selectively undo them, so I'm not sure it rises to the level of needing inclusion in the error list. 

I'm **definitely** for adding a way to get failure information here, but I'm not sure the Error List is the correct location. Would a "Details" button in the InfoBar be acceptable? It could launch a popup with various information, including a more detailed description of what the user's options are if they are confused.

**Comment by shyamnamboodiripad** [comment]
What you say sounds reasonable @dpoeschl. The reason I proposed putting this info in the error list above is because users are accustomed to finding / dealing with errors in the error list (and not as accustomed to doing this in the activity log). However, I agree that having a sticky error for a code fix / refactoring that failed sometime in the past would be a less than optimal experience and you are right I can't think of a good point in time when the error can be made to go away. (We could have a separate category of errors in the errorlist that come from 'extensions' and we could allow users to dismiss / close such errors if they don't care about it.. But that would be a significant amount of work and require changes in the error list implementation... BTW @heejaechang probably knows more about how a specific error can be cleaned up from the error list.)

A "details" button sounds acceptable (especially if we can include a link to open the activity log for the error / include richer information about the error). I am not a big fan of modal pop-ups - perhaps we can have an expander / drop down kind of experience within the infobar itself? I don't think the VS infobar supports anything like that today - but I think this would be a reasonable ask for the folks that own the infobar control...

**Comment by heejaechang** [comment]
@shyamnamboodiripad @dpoeschl I am actually against to putting any error in error list that is not actionable to user. what I meant is if it can't be fixed, it shouldn't be in the error list. we should have another mechanism to show that information to users which can manually be cleared like output window.

**Comment by jmarolf** [comment]
Just throwing my hat into the ring.  A "Details" button appeals to me.  The user doesn't need to click on it, so it doesn't bother them, but if they do, they get all the information they need to report a problem.

**Comment by heejaechang** [comment]
+1 on detail button.

**Comment by dpoeschl** [comment]
We should also add some sort of management dashboard for reenabling disabled fixes, more permanent disabling (across VS sessions), and maybe even crazier stuff (custom ordering, etc.).

(We've discussed this a number of times, but I couldn't quickly find the existing item. If someone finds it, please mention it here.)

**Comment by heejaechang** [comment]
:+1:

**Comment by sharwell** [comment]
> We should also add some sort of management dashboard for reenabling disabled fixes, more permanent disabling (across VS sessions), and maybe even crazier stuff (custom ordering, etc.).

Uninstall the extension and file a bug report *should* be adequate. I would focus on enabling this scenario e.g. by providing a stack trace which can be copied, and perhaps information about the analysis context in which the failure occurred (e.g. for syntax node actions identify the syntax node which was being analyzed at the time of the failure).

**Comment by dpoeschl** [comment]
@jmarolf added a feature to show a copyable stack trace on failures. See https://github.com/dotnet/roslyn/pull/13026

**Comment by dpoeschl** [comment]
@jmarolf @Pilchie (and any others) Can we call #13026 sufficient for `2.0 (Preview 5)`?

**Comment by CyrusNajmabadi** [comment]
Closing due to scope.  If we want to do this, we need to commit to resources and a design, and run this as a full feature request that we are comitted to.
