### ISSUE TITLE
Non-public members and types not highlighted and navigable in decompiled view

### ISSUE THREAD

**Issue by siegfriedpammer** [dotnet/roslyn#26989]
Might be related to #25301

**Version Used**: VS 2017 15.7.1 (recent master branch)

**Steps to Reproduce**:

(Turn on decompilation)

1. Create Console App (.NET Framework)
2. In the following, CTRL+Click int

```csharp
class Program
{
    static void Main(string[] args)
    {
        int foo;
    }
}
```
3. When prompted say Yes to decompile
4. Scroll down to `public int CompareTo(object value)`
5. Look at the last line of the method

```csharp
throw new ArgumentException(Environment.GetResourceString("Arg_MustBeInt32"));
```

**Expected Behavior**:

Hovering over `GetResourceString` should show a quick info tooltip and be navigable. (The method is internal, but should be reachable from within mscorlib.)

**Actual Behavior**:

No quick info is shown and navigation is broken.

Additionally: Any other internal type is not highlighted (e.g. __DynamicallyInvokableAttribute or System.Number).

**Notes**:

It seems that the "temporary" solution and project used for the IDE features in metadata view are missing internal types and members. Note that decompilation works, because the decompiler does not use the Roslyn type system, but initializes its own TS as soon as an instance of `CSharpDecompiler` is created. Internally we read all public and non-public types and members of the "main assembly".

**Comment by CyrusNajmabadi** [comment]
closing out due to lack of feedback.
