### ISSUE TITLE
Allow annotating a subset of a source module (URTANN/NonNullTypes)

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#26983]
Allow limiting annotations to particular classes or perhaps members.

**Comment by gafter** [comment]
On proposal, which we called "URTANN", is to have an attribute such as the following:

``` c#
public class UnannotatedReferenceTypesAreNotNullAttribute : System.Attribute
{
    public UnannotatedReferenceTypesAreNotNullAttribute(bool value);
}
```

When you need to interpret the meaning of a reference type without a following `?` appearing in a declaration, you look up to the enclosing symbol to see if it has this attribute. If not, you look to *its* enclosing symbol, all the way up to the assembly level if necessary. As soon as you find an application of this attribute, you use its value. If you don't find the attribute in this search, you treat it as `false`.

A value of `true` indicates that the appearance of a reference type without a following `?` would be treated as being non-nullable.

A value of `false` indicates that the appearance of a reference type without a following `?` would be treated as oblivious (i.e. not trigger the new warnings associated with this features).

**Comment by jcouv** [comment]
Removed "Language Design" label, since LDM approved such an attribute (tentatively named `NonNullTypesAttribute`).

**Comment by jcouv** [comment]
I need to do a bit more verification, especially for PE scenarios, but this is now implemented. I'll close the issue.
