### ISSUE TITLE
Add ability to provide array type conversion for a type

### ISSUE THREAD

**Issue by hawkerm** [dotnet/roslyn#26995]
If I create a class and give it an implicit conversion operator (in C#):

```
        public SomeClass(string value) 
        {
            // ...
        }

        public static implicit operator SomeClass(string value)
        {
            return new SomeClass(value);
        }
```

It'd be nice to also be able to provide an array converter as well, e.g.

```
        public static implicit operator SomeClass[](string[] values)
        {
            return values.Select(value => new SomeClass(value)).ToArray();
        }
```

Currently, the implicit conversion won't happen automatically for the array (even with the singular implicit converter defined); so making an extension to the other type to provide a helper seems to be the only route but a bit messier.

Also found similar questions for this process dating back to 2010 [here](https://stackoverflow.com/questions/3047727/implicit-array-casting-in-c-sharp).

Originally filed [here](https://github.com/dotnet/corefx/issues/29804)

**Comment by svick** [comment]
Sorry to keep you running around, but, [as explained in the README](https://github.com/dotnet/roslyn#language-design-discussion), the right repo to propose a change to the C# language is [dotnet/csharplang](https://github.com/dotnet/csharplang/). Can you move this issue there? Thanks.

**Comment by hawkerm** [comment]
Thanks @svick, I missed that the csharplang was also for features of both, as I think this can be for VB as well.  I'll move it there.
