### ISSUE TITLE
"Convert to full property" creates field with underscore prefix

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#26992]
When there is no custom naming style for fields, the default behavior of "Convert to full property" is to prefix the field with an underscore:
```c#
class C
{
    int P { get; set; }
}
```
```c#
class C
{
    private int _p;

    int P { get => _p; set => _p = value; }
}
```

on the other hand, "Initialize field from constructor" does *not* use an underscore by default, as was discussed in #22884.

There should probably be consistency here.

**Comment by wachulski** [comment]
In 316327ef (13-09-2017) titled _Responded to feedback_ @chborl added:

```csharp
// <summary>
/// Get the user-specified naming rules, then add standard default naming rules 
/// for both static and non-static fields.  The standard naming rules are added at the end 
/// so they will only be used if the user hasn't specified a preference.
/// </summary>
private static async Task<ImmutableArray<NamingRule>> GetNamingRulesAsync(
    Document document,
    CancellationToken cancellationToken)
{
    const string defaultStaticFieldPrefix = "s_";
    const string defaultFieldPrefix = "_";

    var optionSet = await document.GetOptionsAsync(cancellationToken).ConfigureAwait(false);
    var namingPreferencesOption = optionSet.GetOption(SimplificationOptions.NamingPreferences);
    var rules = namingPreferencesOption.CreateRules().NamingRules
        .AddRange(GetDefaultRule(ImmutableArray.Create(new ModifierKind(ModifierKindEnum.IsStatic)), defaultStaticFieldPrefix))
        .AddRange(GetDefaultRule(ImmutableArray.Create<ModifierKind>(), defaultFieldPrefix));
    return rules;
}
```

#22884 concluded its default of `this.p` is dated back to VS2013 and it won't be adjusted to adhere to DotNet OSS coding guidelines. I'm wondering whether it's feasible to change `Convert to full property` default now to align to `this.p`? What about its adoption? Are people used to it enough by now?

**Comment by sharwell** [comment]
Yes, the Convert to Full Property should be updated to use the current code style applied to the project when selecting names for fields.
