### ISSUE TITLE
Type to generate not inferred in expression bodied getter

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#26993]
```c#
class C
{
    int P
    {
        get => newField;
    }
}
```
Generate field on `newField` creates it with type `object` (which of course results in an error):
```c#
class C
{
    private object newField;

    int P
    {
        get => newField;
    }
}
```
The type should be `int` as is correctly generated when using an expression bodied property or a block with a return statement instead.

**Comment by rik-smeets** [comment]
Nice find! This situation is currently not handled in the type interference service. I'm working on a fix for this, should be done later today.

**Comment by Neme12** [comment]
@rik-smeets I don't think setters should be handled because they are void-returning. It should be possible to just get the method symbol of the accessor and check its return type (which would only be `int` for the getter).

**Comment by Neme12** [comment]
Just like event accessors (add, remove) are void returning.

**Comment by rik-smeets** [comment]
You're right, it should only generate as an `int` (in this example) if you do it like:
```cs
int P
    {
        set=> newField = value;
    }
```
Otherwise, it should just generate an object (both already working as expected, it's the same in properties without expression bodied setters, so nothing needs to be done there). Thanks for clarifying!

**Comment by Neme12** [comment]
Yes, `set => newField = value;` should definitely work. Here it should be inferred from the type of `value`, not the return type of the setter. Even though that already works, please make sure you add a test for that too to prevent any regressions.

**Comment by rik-smeets** [comment]
As said in the linked pull request by @Neme12, this issue also occurs in expression bodied local function:
```cs
public int Y()
{
    return Foo();

    int Foo() => y;
}
```
Results in:
```cs
private object y;

public int Y()
{
    return Foo();

    int Foo() => y;
}
```

Generating methods from within these expression bodied getters or local functions has the same issue. The linked pull request resolves all this.

**Comment by Neme12** [comment]
@jcouv @jinujoseph Can somebody close this please?
