### ISSUE TITLE
VB: Editor should include space before null conditional operator used in a With-statement.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#26999]
**Version Used**:

Visual Studio Community 2017 v15.5.6

**Steps to Reproduce**:

Type in the following code in a VB project:

```vb
  Public Function Blah() As Boolean
    Dim obj As Object = Nothing

    With TryCast(obj, Exception)
      If?.Message = "blah" AndAlso?.Source = "bleh" Then Return False
      If .Message = "blah" AndAlso .Source = "bleh" Then Return False

      Dim Condition1 =?.Message = "blah" OrElse?.Source = "bleh"
      Dim Condition2 = .Message = "blah" OrElse .Source = "bleh"

      Return?.Message = "blah" OrElse?.Source = "bleh"
      Return .Message = "blah" OrElse .Source = "bleh"
    End With
  End Function
```

In the above code there are multiple pairs of statements that show how the editor formats code when you access the members of the variable `obj` referenced using the `With` statement. When you use the regular dot syntax to access members, the editor correctly includes a single whitespace before the dot, so you get code like:

```vb
      Return .Message = "blah" OrElse .Source = "bleh"
```

However if you access a member using the `?.` operator, the space is not included so you get this strange-looking result:

```vb
      Return?.Message = "blah" OrElse?.Source = "bleh"
```

I say "strange-looking" because the lack of spacing makes it look like the `Return` keyword and `OrElse` operator are both objects with members that can be accessed via `?.`

**Expected Behavior**:

The editor should include a space before the `?.` operator just as it does for the regular dot operator when used in a With-statement, to give output like:

```vb
      Return ?.Message = "blah" OrElse ?.Source = "bleh"
```

**Comment by ericmutta** [comment]
Hi @Pilchie looks like you guys are really busy out there! When you get a minute, kindly review and tag this so it doesn't fall through the cracks. Many thanks in advance :+1:

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
