### ISSUE TITLE
A command to generate a struct from a tuple

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/roslyn#26998]
If I have a ValueTuple in code like this:
`(Char From, Char To) `

It will be helpful if the context menu offers a command to generate a struct with a default name from this tuple: 

```
    public struct StructName
    {
        public Char From;
        public Char To;

        public CharRange(Char from, Char to)
        {
            From = from;
            To = to;
        }
    }
```
Sometimes I start with a tuple, then discover I want to reuse it many times, so it is easier if I convert it to a struct.

**Comment by CyrusNajmabadi** [comment]
If we did this, i also think it should work for anonymous-types as well.

I imagine there would be two forms of hte fix:

1. Introduce named type for this anonymous-type/tuple
2. 1. Introduce named type for anonymous-type/tuple (and replace all complimentary types). 

Basically, should the fix work just for the current method (which is the concept we have for anonymous-types), or should it expand to work globally.

**Comment by Neme12** [comment]
@CyrusNajmabadi Can you please clarify what you mean by "work for current method" and "work globally"? Are you talking about replacing usages of the tuple type with the generated type?

**Comment by Neme12** [comment]
Would it replace tuples that are unrelated but happen to be the same type?

**Comment by Neme12** [comment]
The design of such replacement raises the same questions as renaming tuple elements - how do we track tuple types and when do we consider them equal? There should be one answer to both (and hopefully one implementation), so should probably wait until the design for tuple renaming is finalized.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi Can you please clarify what you mean by "work for current method" and "work globally"? Are you talking about replacing usages of the tuple type with the generated type?

Yes.  That's what i'm referring to.  I would expect to be able to make this change on a local basis versus making it globally.

> how do we track tuple types and when do we consider them equal? 

I would use types and names.   The point of allowing the user to specify scopes is precisely around if you'd want to consider other tuples with the same 'shape' as equivalent and important to fixup or not.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
> I like this idea. :)

This is new. I should celebrate :)

> If we did this, i also think it should work for anonymous-types as well.
Nice.


I

**Comment by MohammadHamdyGhanem** [comment]
@Neme12 
> The design of such replacement raises the same questions as renaming tuple elements - how do we track tuple types and when do we consider them equal? There should be one answer to both (and hopefully one implementation), so this should probably wait until the design for tuple renaming is finalized.

I didn't ask for replacement. Gust generate the struct and I'll take it from there :)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/28257.  @jcouv @jinujoseph can you close this issue?

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
Thanks. Great work.
