### ISSUE TITLE
"Run Code Analysis and Suppress Active Issues" & "Configure Code Analysis" Issues shows on CPS projects but does nothing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27002]
**Version Used**: 
15.8 Preview 3

We recently made a change that caused Project.Kind to return the legacy project system, this has caused "Run Code Analysis and Suppress Active Issues" and "Configure Code Analysis" to show up despite them not working.

Make note, "Run Code Analysis" does not show up, so it seems like these other two commands have different light up checks to it.

**Steps to Reproduce**:

1. File -> New Console App (.NET Core)
2. Right-click on project and point to Analyze

-or-

2. Select project and choose Analyze

![image](https://user-images.githubusercontent.com/1103906/40292389-67437cba-5d0e-11e8-88e1-b89581de0e49.png)

![image](https://user-images.githubusercontent.com/1103906/40292367-44639ec8-5d0e-11e8-98c3-a54076debc95.png)
![image](https://user-images.githubusercontent.com/1103906/40292379-566fa814-5d0e-11e8-981e-cdc816b73a1a.png)

**Comment by davkean** [comment]
Make note you need to actually load StanPackage first by running one of the Analyze commands in menu bar.

**Comment by mavasani** [comment]
Note: [This](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/133417) VSO PR renames and fixes the command to make it consistent for both CPS and non-CPS based projects, we don't run FxCop now as part of this command.
