### ISSUE TITLE
Nullable Reference Types: With preview installed, Visual Studio hangs when creating a new C# Console App

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#27012]
**Version Used**: 05/14/18 Nullable Reference Types Preview (`csc` reports `2.8.0.62830 (e595ee27)`) with Visual Studio Community 2017 (15.7.1)

**Steps to Reproduce**:

1. Install Nullable Reference Types Preview
2. Start **a fresh instance** of Visual Studio
3. Go to `File` > `New` > `Project...`
4. Select `Installed` > `Visual C#` > `Console App (.NET Framework)`
5. Click `OK`

**Expected Behavior**:

The project and associated solution are created and opened.

**Actual Behavior**:

Visual Studio spins forever on "Creating project 'ConsoleApp1'...". Pressing Cancel does nothing. If you wait long enough, a notification stating that the Visual Studio performance problem was reported to Microsoft briefly appears. The operation seemingly never completes.

If you kill the `devenv.exe` process and inspect the filesystem, you will find that all of the files are created. Opening the solution reveals that the project was never added to the solution, the solution is empty.

**Workaround 1**:

1. Kill `devenv.exe` after it hangs.
2. Open Visual Studio again and open the partially-generated solution
3. Manually re-add the project by adding it as an existing project.

**Workaround 2**:

1. Open any solution that isn't empty. (Empty solutions do not work.)
2. Close the solution.
3. You can now create new C# .NET framework console app projects.

**Misc notes**:

I've reproduced this on both my desktop and my laptop. Both are running Windows 10 1709. (One is running build 16299.371, the other 16299.431)

I've reproduced this issue with all disablable extensions disabled, save for "Roslyn Nullable Reference Types Preview". (Disabling "Roslyn Nullable Reference Types Preview" does not fix the issue either.)

Uninstalling the nullable reference types preview resolves the issue.

Creating a blank solution and adding a new C# .NET Console App project to it also causes the issue. (Therefore, that strategy is not a viable workaround.)

The issue does not happen when you create a .NET Framework C# Class Library or .NET Core C# Console Apps.

**Comment by jmarolf** [comment]
Likely a bug in https://github.com/dotnet/roslyn/blob/master/src/Compilers/Extension/CompilerPackage.cs but I'll need to debug to figure it out.
