### ISSUE TITLE
Changing Code Styles

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27013]
Changing behavior with code styles is not a welcome change and tends to be rather frustrating! Your style selection cannot possibly understand the architecture for the code. Yet it insists that I must use auto properties and I cannot turn this off in the Tools|Options Dialog. There is a bit of information on creating editorconfig files, but that does not seem to work either.

Please add this to the options as being configurable or turn it off.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/252974/changing-code-styles.html
VSTS ticketId: 616248_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
💭 I am not able to reproduce this issue. Changing the following configuration appeared to remove messages associated with this feature:

![image](https://user-images.githubusercontent.com/1408396/40312782-82ed6b2c-5cd9-11e8-8248-6b18b8a7e7f4.png)

**Comment by PathogenDavid** [comment]
Do you have a code analysis rule set configured for your project? They are capable of enabling things like IDE0032 (which is the analyzer that suggests using auto properties.) I've never tested it, but I imagine the rule set overrides the IDE settings and possibly even `.editorconfig`.

**Comment by jinujoseph** [comment]
We were not able to reproduce this issue, the setting shown by @sharwell above should let you set this.
