### ISSUE TITLE
Consolidate options behavior for new parentheses analyzer

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#27038]
**Version Used**: c190e84617b4b5e1d01b8bf1424b46709f326428

This is a proposal for a minor modification to simplify the available options for the new parentheses analyzer (#26013, #26710).

#### Current behavior:

* Two of the options allow the user to select **Require for clarity** or **Remove if unnecessary**. The **Ignore** option is handled implicitly by specifying an option and then selecting **None** as the severity.
* Two other options allow the user to select **Ignore** or **Remove if unnecessary**. The **Ignore** option is included to avoid a situation where the combo box only has one option.
* The .editorconfig support maps to the above options, so users need to understand the limitations to avoid creating a configuration which looks supported but internally will not parse.

#### Proposed behavior

* All options are updated to allow the user to select **Require for clarity** or **Remove if unnecessary**
* For the one option where **Require for clarity** does not currently make sense (the 'Other' category), the preview text for this option simply shows a statement that parentheses will be ignored, but a future release may add parentheses validation if a new operator is created which benefits from explicit parentheses

#### Design review notes

This proposal was created during a review with a subset of the design team, and is pending acceptance from the full team before implementation.

**Comment by CyrusNajmabadi** [comment]
>  to avoid creating a configuration which looks supported but internally will not parse.

I'd much rathre have our parsing code capable of reporting issues.  So we can tell users about the problem.  

> This is a proposal for a minor modification to simplify the available options for the new parentheses analyzer 

Note: this seems a bit more complex.  'add for clarity' def seems confusing for the 'other' category... 

> Two other options allow the user to select Ignore or Remove if unnecessary. The Ignore option is included to avoid a situation where the combo box only has one option.

Hrm... i'm not sure i agree.  There is a distinct difference here.  'ignore' is: "i don't care.  do not tell me about this."   "remove if unnecessary" is "i would prefer to not have these, with different levels of severity.  Lowest severity is just "fade out", then suggestion, then warning, then error.

I'm not sure how you would get this with just one combo box option. :)

**Comment by sharwell** [comment]
> I'd much rathre have our parsing code capable of reporting issues. So we can tell users about the problem.

This came up during the meeting. Everyone agreed it would be a valuable addition, but isn't directly tied to any of the other open designs.

> Note: this seems a bit more complex. 'add for clarity' def seems confusing for the 'other' category...

The **Add for clarity** option in Other would be functionally equivalent to the current Ignore option. Only the name changes. In the future, new operators may be handled by this feature but for now the option would simply disable all reporting for Other operators.


> Hrm... i'm not sure i agree. There is a distinct difference here. 'ignore' is: "i don't care. do not tell me about this." "remove if unnecessary" is "i would prefer to not have these, with different levels of severity. Lowest severity is just "fade out", then suggestion, then warning, then error.

A separate proposal, #26972, is moving forward as a high-priority change which would resolve this limitation.

**Comment by CyrusNajmabadi** [comment]
> A separate proposal, #26972, is moving forward as a high-priority change which would resolve this limitation.

So, just i understand, "Silent" would be what you would use if you wanted fading, but no other editor presentation.  "None" would be equivalent to what 'ignore' is today.  And the rest of the severities (suggestion/warning/error) would behave the same as today. 

Is that right?

If so, that makes sense to me.

**Comment by sharwell** [comment]
@CyrusNajmabadi that is exactly correct

**Comment by CyrusNajmabadi** [comment]
Overall, this all seems reasonable to me.  I feel like i'd like the VS ui to at least not have hte add-for-clarity optoin under the 'other' category so you could not pick it through there.

If you did happen to directly supply 'add for clarity' in editorconfig, that, i would be fine with either our config-parser (or just the feature itself) treating it as 'ignore'. 

I get making it so we support someone getting confused and having written this value.  However, it feels weird to explicitly have our UI proffer it.  

What do you think?  Thanks!

**Comment by sharwell** [comment]
> I get making it so we support someone getting confused and having written this value. However, it feels weird to explicitly have our UI proffer it.

The default option in this case would be 'Remove if unnecessary'. If changed, the preview would indicate that parentheses will be ignored for these types of expressions. Due to the overall complexity of this feature, it does not seem that users would end up confused, as they will be referring to the example pane to understand their selection.

**Comment by CyrusNajmabadi** [comment]
I'm not convinced :)   i think it would just be simpler to just have the two reasonable options.  But i won't belabor the point :)

**Comment by sharwell** [comment]
The design from https://github.com/dotnet/roslyn/issues/27038#issue-325106150 was approved by the team. This is up for grabs but needs to be implemented for 15.8 Preview 3 at the latest. 

/cc @jinujoseph

**Comment by sharwell** [comment]
@CyrusNajmabadi asks:

> Could you explain the overall intuition around "always for clarity" for hte "for other" category? It's unclear to me what that really means...

The main advantage of this change is it switches to a uniform set of available values for each of the new options. `require_for_clarity` results in the addition of parentheses in locations that improves clarity, while `remove_if_unnecessary` does roughly the opposite (ignoring special cases related to problematic operators).

The other category, and to a lesser extent the relational category in VB, also follow this rule. The difference here is the implementation has no cases where parentheses are considered to improve clarity. If that changes in the future, e.g. due to a new operator in one of these categories at a different precedence level, we could modify the implementation to start adding parentheses for it.

**Comment by CyrusNajmabadi** [comment]
> If that changes in the future, e.g. due to a new operator in one of these categories at a different precedence level, we could modify the implementation to start adding parentheses for it.

I like that idea.  Though, it should be said, the idea of the "other" category, was really meant to be "the one we would always remove parens from" category :)    The thought was that if there were other parens we wanted to remove/add, and they weren't one of those binary categories, we'd add an explicit category.

But, overall, this seems mostly reasonable to me :) There might be some confusion, but it seems tiny.  And overall the uniformity does seem beneficial.

Thanks!
