### ISSUE TITLE
Syntax Coloring Lost in Copy and Paste to Word

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27043]
Create Projet in Visual Studio
Enter &quot;Console.WriteLine();&quot; in some method.
Now, keyword &quot;Console&quot; is cyan.
Ctrl+A to select all
Ctrl+C to copy into clipboard
Open Word
Ctrl+V to paste into Word document
Now, keyword &quot;Console&quot; is black.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/146551/syntax-coloring-lost-in-copy-and-paste-to-word.html
VSTS ticketId: 521685_
_These are the original issue comments:_

Nobuyuki Iwanaga on 11/8/2017, 05:02 AM (194 days ago): I have the same problem.Version used: both VS 15.4.3 and VS 15.5 Preview 3A screen shot:https://twitter.com/ufcpp/status/928245625665155074
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
Notes from editor team.

It looks like Roslyn is using the colors from the Extra Contrast theme when copy is invoked. Routing.

**Comment by ufcpp** [comment]
dup of https://github.com/dotnet/roslyn/issues/24073

**Comment by jinujoseph** [comment]
Duplicate #24073
