### ISSUE TITLE
consider update GenerateMethodCodeFixProvider to actually consider diagnostic

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#27041]
see actual code here
http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/CodeFixes/GenerateMethod/GenerateMethodCodeFixProvider.cs,60

current implementation, basically doesn't care where CS1061 error shows up. if it shows up, from the expression, the diagnostic showed up, it walks up the tree to find invocation expression or member binding expression that is the method to generate. 
http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/CodeFixes/GenerateMethod/GenerateMethodCodeFixProvider.cs,71

current implementation is naive, assuming the first matching node is the one that the diagnostics is for. could be good enough, but we have exact diagnostic generated for the expression. so we can use the diagnostic to reduce false positive if we want to.

more detail 
https://github.com/dotnet/roslyn/pull/26959

**Comment by CyrusNajmabadi** [comment]
I looked into this, but couldn't find any way to make this better.  The basic issue is that we cannot make assumptions about where the compiler will put these diagnostics.  So we have to take a conservative route of trying to find the applicable node in the first place.

A better approach altogether would be to not have this driven by compiler diagnostics, but instead have this be an IOp or Semantic analyzer where we walk the tree ourselves and report our own diagnostics on nodes that don't bind properly.
