### ISSUE TITLE
Consolidate diagnostic IDs for predefined types

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#27042]
**Version Used**: The proposal is an implementation detail of #26578 which is called to the surface.

:memo: This change has since been removed from #26578, but is still under consideration as an independent change.

**Current behavior:**

Currently diagnostics related to predefined types have four diagnostic IDs. Suppose a user wishes to use `string` when declaring a variable with this type, but `String` when referring to static members. The following code would produce the two diagnostics:

```csharp
String value // IDE0012
  = string.Empty; // IDE0015
```

Based on the configuration selected by the user, only two distinct IDs can appear in any given file (.editorconfig allows different configurations to apply to different source files, so it's possible a project or solution could reveal all four).

**Proposed behavior:**

The proposed behavior would consolidate all four situations to use the same diagnostic ID. This diagnostic ID would be a different ID from the previous ones, and the current IDs would be retired. The configuration functionality would not change *at all*. The benefit of this change is it allows Fix All operations to fix *all* situations related to this configuration in a single pass, rather than requiring users to make up to four passes to fix everything.

**Breaking change:**

This is a breaking change for cases where diagnostics are suppressed. However, this is a relatively low risk change because the impacted analyzers were never shipped as NuGet packages and thus have never had an impact on the actual build outcome.

**Comment by CyrusNajmabadi** [comment]
I think this would be a good idea.  It would be something i could potentially help out with.  However, i would like this change to be done after the following PRs go in:

https://github.com/dotnet/roslyn/pull/26578
https://github.com/dotnet/roslyn/pull/26823
https://github.com/dotnet/roslyn/pull/26824
https://github.com/dotnet/roslyn/pull/26825

These already are simplifying PRs around this feature area.  It will be much easier to get this design change in once those other changes are made first.

**Comment by sharwell** [comment]
The design from https://github.com/dotnet/roslyn/issues/27042#issue-325116757 was approved by the team, so this is now up for grabs.

**Comment by CyrusNajmabadi** [comment]
@sharwell if you do want this done, would you like me to make a single branch with all of this work done in it?
