### ISSUE TITLE
generate member can generate new member that's already exist

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#27040]
related to https://github.com/dotnet/roslyn/issues/26957

detail https://github.com/dotnet/roslyn/pull/26959

if we take https://github.com/dotnet/roslyn/pull/26959 the repo in https://github.com/dotnet/roslyn/issues/26957 won't work anymore.

but underlying code consider same method signature with different parameter names to 2 different one and let those method to be generated that will cause CS0111 error for generate method

**Comment by CyrusNajmabadi** [comment]
Not clear waht issue this is referring to (a repro case is now present).
