### ISSUE TITLE
Very bad IDE PERF when updating a big enum

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#27051]
Version: VS 15.7

- Create an enum with eg. 4000 elements (eg. exec `seq 4000` and use some regex)
- Add a comment to the last value in the enum, add some words and watch how slow it is

Enum: https://pastebin.com/n781zSSL

```C#
	enum E {
		V1,
		V2,
		// ...
		V3997,
		V3998,
		V3999,
		// add your comment here, oh this is slooooooooooow
		V4000,
	}
```

Seems to be caused by the completion service on thread `PrioritizedTaskScheduler-AboveNormal`

It calls IsGenericTypeArgumentContext() which calls this method which loops for a very long time

```C#
public static bool IsInPartiallyWrittenGeneric(this SyntaxTree syntaxTree, int position, CancellationToken cancellationToken, out SyntaxToken genericIdentifier, out SyntaxToken lessThanToken)
```

Is there a reason why the completion service is running when writing comments?

Is it possible to minimize calls to IsGenericTypeArgumentContext() so it's easier to edit longer initializer lists or enums?

Can IsInPartiallyWrittenGeneric() give up earlier if it has looped, let's say 100 times, instead of looping all 4000 times?

**Comment by CyrusNajmabadi** [comment]
Thanks very much for the report and the breakdown of where the costs are!


> Is there a reason why the completion service is running when writing comments?

We don't really limit completion from running in contexts like these.  We have a plugin based architecture here, so someone might want to provide completion insde a comment (like we already have inside doc-comments)

That said, we could def have the code that calls into IsInPartiallyWrittenGeneric (or what calls that, or what calls that, etc. etc.) not bother if it realizes its in a comment.

> Can IsInPartiallyWrittenGeneric() give up earlier if it has looped, let's say 100 times, instead of looping all 4000 times?

Definitely.  It seems like it would be totally reasonable to give up after even 16 items.  That would effectively support every generic type in the universe.

**Comment by 0xd4d** [comment]
I'll just use notepad, I heard a big update is coming, unix line ending support!

**Comment by CyrusNajmabadi** [comment]
This should be reopened.  It's a definite perf issue with several very feasible things that can be done to improve things.  @jcouv @jinujoseph can you assign accordingly?
