### ISSUE TITLE
Add support for workspace/VS based diagnostic analyzers

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2706]
We have recently had multiple internal and public requests to add support for analyzers that are based on workspace/VS and are primarily designed to run in Visual Studio IDE. The primary features being requested are:

1. Analyzers have workspace/project/document context in which they are executing (for example, for a syntax node action callback, which document does the syntax node belong to?)

2. Analyzers can do solution wide OR cross project analysis

3. Analyzers can perform UI centric operations in VS IDE

Based on the Workspace scenarios, we can broadly categorize analyzers as:

1. Workspace agnostic: Analyzers which are agnostic of whether or not they are being run within a workspace or in command line build with no workspace. All analyzers today are in this bucket.

2. Workspace dependent: Analyzers that can only run within Workspace/Visual studio IDE, but not during command line builds.

3. Workspace configurable: Analyzers which run differently in Workspace configuration and non-Workspace (command line build) configuration, but do want to run in both modes. This is especially helpful over (2) above as they can also be run in command line builds, with some default mode.

There are different ways to design the requested features, based on the actual API overlap:

1. **View 1**: Feature (1) and Feature (2), i.e. analyzers requesting workspace context AND analyzers doing solution wide analysis can be clubbed together. We expose solution/project/document related analyzer actions for such analyzers to satisfy both needs. Category (3) of analyzers, i.e. Workspace configurable, get ruled out with this approach.

2. **View 2**: All 3 features are distinct and should have separate APIs. Feature (1) is about current context of execution, and there should be an easy way to get to current document/project being analyzed on every callback. Feature (2) needs new solution/project/document related analyzer actions for solution wide analysis. Feature (3) is a good to have addition as quite a few VS-based analyzers would need some UI operations, so we would need separate opt-in analyzer callback(s) which are guaranteed to happen on the UI thread.

**Comment by srivatsn** [comment]
We've decided to #3797 instead.
