### ISSUE TITLE
Adding the missing analyzer dependency as analyzer in VS doesn't re-trigger analyzer execution

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2707]
1) Create a C# analyzer + code fix project, say _Analyzer.csproj_.

2) Add a new portable C# class library project to the solution, say _AnalyzerDependency.csproj_. Define a new public string field called _Title_ in the default class with any string initializer.

3) Add a project reference from Analyzer.csproj to AnalyzerDependency.csproj

4) Replace the default _Title_ field in the DiagnosticAnalyzer in _Analyzer.csproj_ with the following:
`internal static readonly LocalizableString Title = new AnalyzerDependency.Class1().Title;`

5) Build solution and copy Analyzer.dll and AnalyzerDependency.dll to separate folders, say _C:\MyAnalyzer\_ and _C:\MyAnalyzerDependency\_ respectively.

6) Start a new VS instance and create a new C# project, say _ClassLibrary1_. Add analyzer: _C:\MyAnalyzer\Analyzer.dll_ to the project.

**Actual**: Get an exception diagnostic in error list (this is expected):
```
Severity	Code	Description	Project	File	Line
Warning	CS8032	An instance of analyzer Analyzer.Analyzer cannot be created from c:\MyAnalyzer\Analyzer.dll: Exception has been thrown by the target of an invocation..	ClassLibrary2		1
```

**Expected**: Diagnostic has additional information about missing analyzer dependency, and hence is actionable.

7) Add analyzer dependency "C:\MyAnalyzerDependency\AnalyzerDependency.dll" as an analyzer to the project

**Expected**: The diagnostic from step 6. is cleared as the missing analyzer dependency has now been resolved by explicitly adding it as an analyzer. Additionally, the **true** analyzer diagnostic from the analyzer gets reported for Class1 having lowercase letters.

**Actual**: No change, exception diagnostic is not cleared and analyzer never executes.

8) Close and re-open ClassLibrary1.sln in the current VS instance.

**Actual**: Exception diagnostic exists and analyzer never executes.

9) Close and restart VS and open ClassLibrary1.sln.

**Actual**: No exception diagnostic OR analyzer lowercase diagnostic in error list. Editor does have the squiggle on _Class1_ and hovering the mouse over it does show the light bulb popup with the analyzer lowercase diagnostic message.

10) Edit the source file to change Class1 to Class2, to re-trigger analysis on a new compilation.

**Actual**: Lowercase diagnostic appears in error list.

**Comment by tmeschter** [comment]
The problem is that an `AnalyzerFileReference` caches the list of `DiagnosticAnalyzers` it retrieves from the underlying analyzer assembly. If a dependency is missing, it won't be able to retrieve anything. Even if the dependency is later satisfied, we still return the cached results.

I see three possibilities

* Update `AnalyzerFileReference` to only cache the results when there are no errors.
* Update `AnalyzerFileReference` with a way to reset the cache.
* Update `AbstractProject` and `VisualStudioAnalyzer` to work together to drop `AnalyzerReferences` with load errors and re-add them whenever a new analyzer is added.

I'll need to ponder the best option.

**Comment by tmeschter** [comment]
@mavasani I've come up with three options for fixing this. I'm leaning towards the last one (dropping and re-adding `AnalyzerReferences` with load errors); what are your thoughts on this?

**Comment by mavasani** [comment]
@tmeschter 3. sounds like a good approach to me too.

**Comment by mavasani** [comment]
@tmeschter @srivatsn So it turns out that Tom's fix and the assembly dependency checker do the right thing for this repro, i.e. at step 6, I get an additional diagnostic about missing AnalyzerDepedency.dll and this diagnostic goes away in step 7.

However, this doesn't seem to change the actual behavior for the exception diagnostics for steps 7 to 10. i.e. adding the analyzer dependency as an analyzer in step 7, causes the exception diagnostic to only momentarily go away, but it returns back immediately, and that diagnostic stays in the error list till step 10. in the repro. Also the actual diagnostic from the analyzer never shows up in the error list till step 10. I am assuming that there is some cached state in our diagnostic service that is not re-computing the new diagnostics for the project, until we have a code change.

I am going to re-open this issue as the original issue still exists. Sorry for the delayed verification..

**Comment by mavasani** [comment]
Clearing the milestone, don't think this is important enough or meets the bar for 1.0.

**Comment by mavasani** [comment]
This seems to be fixed with v2 diagnostic engine in Dev14 Update3.
