### ISSUE TITLE
DeclaredSymbol in IDeclarationPatternOperation shouldn't be null for discard

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#27086]
features/dataflow branch

**Steps to Reproduce**:
Get control flow graph for this code:
```csharp
class C
{
    static void M(object o)
    /*<bind>*/
    {
        if (o is var _)
        {
            return;
        }
    }/*</bind>*/
}
```

**Expected Behavior**:
The declaration pattern should have IDiscardSymbol as the declared symbol.

**Actual Behavior**:
`IDeclarationPatternOperation (**Declared Symbol: null**) `

**Comment by jinujoseph** [comment]
closed via #28469
