### ISSUE TITLE
Make FixAllContext constructor(s) public

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#2709]
Currently the constructors for `FixAllContext` are not public, which makes it very difficult to test a fix all provider. While this has been mentioned in other issues, I wanted to make sure the higher priority issue of simply exposing these constructors can be addressed separately.

This directly affects #1576 and #2020, as well as a variety of issues posted on other issue trackers and mailing lists.

**Comment by giggio** [comment]
Nice! And I can see it is already being fixed!

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/918dd32ccdfd901bfd71d88bdb9f7051adfb3d51
