### ISSUE TITLE
Compiler crashes if it cannot locate resources for analyzer

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#271]
Ported from TFS WorkItem: <b>1116649</b>

------------------------------

<p><b>Repro Steps:</b></p>
<OL>
<LI>Create project that references CTP 5 nuget packages (beta2)</LI>
<LI>Upgrade packages in project from Beta2 to 1.0-rc1</LI>
<LI>Build project</LI></OL>
<P><STRONG>Expected:</STRONG></P>
<P>&nbsp;</P>
<P>Project build successfully</P>
<P>&nbsp;</P>
<P><STRONG>Actual:</STRONG></P>
<P>&nbsp;</P>
<P>We are unable to find the resource file for Microsoft.CodeAnalysis.Analyzers and crash the compiler process.</P>
<P>&nbsp;</P>
<P>Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers.resources, Version=1.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. ---&gt; System.IO.FileNotFoundException: Could not find file 'C:\StyleCopAnalyzers\packages\Microsoft.CodeAnalysis.Analyzers.1.0.0-rc1\tools\analyzers\Microsoft.CodeAnalysis.Analyzers.resources.dll'.<BR>&nbsp;&nbsp; at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)<BR>&nbsp;&nbsp; at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)<BR>&nbsp;&nbsp; at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)<BR>&nbsp;&nbsp; at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference.InMemoryAssemblyLoader.LoadCore(String fullPath)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference.InMemoryAssemblyLoader.CurrentDomain_AssemblyResolve(Object sender, ResolveEventArgs args)<BR>&nbsp;&nbsp; at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)<BR>&nbsp;&nbsp; --- End of inner exception stack trace ---<BR>&nbsp;&nbsp; at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)<BR>&nbsp;&nbsp; at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark&amp; stackMark)<BR>&nbsp;&nbsp; at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark&amp; stackMark)<BR>&nbsp;&nbsp; at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark&amp; stackMark)<BR>&nbsp;&nbsp; at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark&amp; stackMark)<BR>&nbsp;&nbsp; at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)<BR>&nbsp;&nbsp; at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.LocalizableResourceString.ToString(IFormatProvider formatProvider)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.DiagnosticFormatter.Format(Diagnostic diagnostic, IFormatProvider formatter)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CommonCompiler.PrintErrors(IEnumerable`1 diagnostics, TextWriter consoleOutput)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, CancellationToken cancellationToken)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)</P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By Jonathon Marolf (1/28/2015 6:43:07 PM)

Even if we can't find a resource for the analyzer we shouldn't crash the process.&nbsp; We should handle this exception.

------------------------------

2) Edited By Srivatsn Narayanan (1/29/2015 11:46:45 AM)

<p>Is this the old FallbackResourceLocation bug again? </p>
------------------------------

**Comment by mavasani** [comment]
I was able to get a repro and it might possibly be the fallback location issue again, I need to do some more investigation. 
However, there is also another issue in here. Any exception from LocalizableString.ToString() shouldn't go unhandled. As LocalizableString is lazily computed, it is never evaluated until we need the Title/Message/Description. For this repro case, it is within DiagnosticFormatter.Format method called from CommonCompiler.PrintErrors, but this may as well happen from any IDE components in VS and will crash VS. 
We need to fix all callsites that invoke LocalizableString.ToString() to handle this possible exception and report a corresponding diagnostic.

**Comment by jaredpar** [comment]
In addition to this bug we should be hardening the compilation process against analyzer failures.  If an analyzer fails with an unhandled exception the compilation should result in a `Diagnostic` vs. a crash.  

Do we have a bug tracking this yet?

**Comment by mavasani** [comment]
@jaredpar We already ensure that any callbacks into analyzers are wrapped within a try/catch all (see AnalyzerExecutor.ExecuteAndCatchIfThrows method, which is used for all analyzer callbacks). This one is a special case as LocalizableString.ToString() is lazily evaluated only when we need to report/localize a diagnostic. I have a bug to ensure that we wrap all places where LocalizableString is converted to a string with a try/catch.

**Comment by jaredpar** [comment]
@mavasani 

The method seems suspect to me because whether the exception propagates to the rest of the compiler is configurable via the delegate.  That means the compiler must be hardened against analyzer exceptions which we don't actually want to do.

I can't see a reason why that `catch (Exception)` shouldn't be an unconditional catch.  The filter should be deleted.  

Is there a specific reason it exists? 

cc @agocke

**Comment by mavasani** [comment]
The delegate returns false (and hence exception unhandled) only in below circumstances:

1. For our built-in IDE analyzers (EnC analyzer, simplify names, etc.), we need crash dumps for any crashes in there (see IBuiltInAnalyzer). We were planning to move to non-fatal watsons. I think @heejaechang was doing some work for it, but I am not sure if that is already done for IDE analyzers.
2. Tests verifying hardening against analyzer exceptions.
3. OperationCanceledException is thrown with callers cancellation token.

Analyzer authors or consumers have no way to configure this delegate and exception will always be handled.

**Comment by jaredpar** [comment]
For item 1 understand the need for better crash dumps.  But that can be done in the `when` block and still have the exception be caught by the the `catch`.  Essentially consider if the current `Func<Exception, Analyzer, bool>` was instead simply `Action<Exception, Analyzer>`.  That would allow for better dumps and the easy understanding that exceptions never propagate to the compiler.

For item 2 I don't understand the argument.  The handling of exceptions should be testable without the need to conditionally catch the exception.  The `Action` approach I listed above would work just fine.  As would simply testing that the compilation output had the correct error diagnostic.  

I don't understand the third item.  Why do we need a filter for that?  Seems like it should be unconditionally cancelled. 

We can't ship in a state where analyzer exceptions can dictate the stability of the compiler.  The easiest way to verify that is to remove the filter block and just catch unconditionally.

**Comment by mavasani** [comment]
I agree, everything here can be achieved through Action<Exception, Analyzer>. Realistically 1. is the only use case for it, others seem to be just where this got re-used. It will probably be some work on @heejaechang to ensure that non-fatal Watson handler for IDE analyzers is registered with the IDE analyzer driver. @srivatsn Do you agree with the proposed change? Should I open a separate issue to track this work?

**Comment by agocke** [comment]
I don't agree with

**Comment by agocke** [comment]
I don't agree with crashing the compiler until we have a non-fatal Watson story. The analyzers cannot crash the compiler. The compiler is in RC.

If getting dumps is important, I think the work item to produce a non-fatal Watson needs to be elevated.

**Comment by jaredpar** [comment]
@agocke Let me be a bit more clear about my thoughts:

1. An exception from an analyzer should **never** propagate into compiler code.  The caller of the analyzer should wrap in a `try / catch` and convert to the appropriate failure case in the compiler for the specific call. 
2. The host of the compiler should be able to treat analyzer failures as fatal if they like.   For example I think the compiler server should consider taking this approach.  If it identifies a case where an Analyzer is loaded in memory and behaving incorrectly the only sane decision is to take down the process.

**Comment by agocke** [comment]
@jaredpar I agree with this, but I think it also means we need a compiler work item to harden all analyzer entry points against exceptions.

**Comment by mavasani** [comment]
Command line compiler will never crash for explicit callbacks into analyzers, its the exception from IDE analyzers that is under scrutiny here. Its just that this method is in a shared project used by both IDE and compiler drivers.
Additionally, I think @heejaechang has already done the work for non-fatal Watsons and even VS won't crash in this scenarios, it will handle these exceptions, though he can confirm.

I have opened #868 to track Jared's proposal of using Action instead of Func and always catch exceptions.

**Comment by agocke** [comment]
@mavasani @jaredpar 

Despite not being an explicit entry point into the analyzers, I treat hooking the assembly resolve as a compiler entry point into the analyzers.

My position here would be that the entire event handler is wrapped in a try-catch.

**Comment by mavasani** [comment]
Agreed, that is addressed by #865

**Comment by mavasani** [comment]
I am going to merge the PR for this issue and close this issue. Please add any more comments on this scenario into #868

**Comment by mavasani** [comment]
Fixed with commit 600c0e4in PR #835

**Comment by heejaechang** [comment]
non-fatal watson is done. I hope our diagnostic engine v2 work remove the need for delegate completely.
