### ISSUE TITLE
Why doesn't use an invalid name in discards？

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#27101]
As we know, "_" is a valid name:
```
if (int.TryParse("123", out int a))
    Console.WriteLine(a);

if (int.TryParse("123", out int _))
    Console.WriteLine(_);
```
So, I think these 2 are both correct.

Why doesn't use an invalid name (such as * or #) instead of _?
like this:
```
if (int.TryParse("123", out int *))
{
//this time, nobody will try to use:
//Console.WriteLine(*);
}
```

**Comment by svick** [comment]
This is documented in [Language Design Meeting notes for 15 November 2016](https://github.com/dotnet/csharplang/blob/0709623/meetings/2016/LDM-2016-11-15.md#discards) (emphasis mine):

> We got great feedback on "wildcards" at the MVP Summit, including changing its name to the term "discards", which is spreading in industry.
>
> We are also encouraged to use _ as the discard character instead of *. **It works better visually, and is what many other languages already use.**

**Comment by HaloFour** [comment]
@CreateAndInject 

This was a subject of a lot of debate and I still don't agree with the outcome, but that's where we are now.

https://github.com/dotnet/roslyn/issues/14794
https://github.com/dotnet/roslyn/issues/14832
https://github.com/dotnet/roslyn/issues/14862
https://github.com/dotnet/csharplang/issues/1064

**Comment by sharwell** [comment]
@CreateAndInject I believe the answers to your question(s) can be found in the links provided by @HaloFour. If you have additional questions, you can ask them in [dotnot/csharplang](https://github.com/dotnet/csharplang). 😄
