### ISSUE TITLE
Possible type-switch optimization

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#27105]
Consider this switch:

https://github.com/dotnet/roslyn/blob/7e01d845c0978410a9057ead3c9d6c57709c2f79/src/Workspaces/CSharp/Portable/Extensions/SyntaxNodeExtensions.cs#L678-L704

Currently we generate a linear search through all types. So for all cases except for the first one, more than one type check has to be evaluated.

Alternatively, we could find the most common base types and separate the linear search for each:

```cs
if (node is StatementSyntax) {
  // switch on statements
} else if (node is ExpressionSyntax) {
  // switch on expressions
}
```
 and so on. (note: we can run this algorithm recursivly on resultant "child" type switches as well)

In most cases, this would reduce the evaluated type-checks to half of the original code or less.

(It may be the case that the performance of abstract type-checks (which is worse than sealed type-checks) to exceed the time spend on each of type-checks in the linear evaluation.)

Note: with proper DUs we may turn this into an integer binary-search but that wouldn't be applicable to a simple type-switch.

**Comment by CyrusNajmabadi** [comment]
That would be pretty cool.  @gafter for the feasibility of adding smarts to the type-switch code-gen by examining the type hierarchy and eliminating cases.  

Because the 'is' checks seem unobservable, it seems like this would be possible to do (and likely worthwhile) at least for large enough switches.

**Comment by gafter** [comment]
A few comments.
1. I agree, it is worth improving the generated IL for "type switch"
2. It is possible that the jit already generates good machine code for these, particularly in the case of sealed types.
3. If the jit does not generate good code for these, it is possible that we could make it do so.
4. Agree that proper discriminated unions would help (the compiler would generate a Kind field). However, it would principally help for the sealed types, which are probably already not too bad.

**Comment by alrz** [comment]
>If the jit does not generate good code for these, it is possible that we could make it do so.

Runtime optimization for type switches would be huge, although with DUs we get the best of both worlds explicitly without any jit/clr changes.

Types used in long type-switches are already a candidate for DUs, so perhaps it wouldn't worth it to invest in this area just yet.

As you said, sealed type-checks are already fast enough. Adding abstract type-checks in this manner could actually make it *worse* in some cases. So I agree it would make more sense to address the issue here in some others ways.

**Comment by alrz** [comment]
Closing in favor of https://github.com/dotnet/roslyn/issues/31515
