### ISSUE TITLE
Several build issues around referencing MS.VS.Text.Internal.dll

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#27113]
- [ ] This line should have backslashes and not forward slashes: https://github.com/dotnet/roslyn/blob/08a22f8557a7eecbf1862bdcd92d25a9b1ca3b4e/build/Targets/Versions.props#L61
 - [ ]  6 Test projects at EditorFeatures level use this line to reference MS.VS.Text.Internal: https://github.com/dotnet/roslyn/blob/08a22f8557a7eecbf1862bdcd92d25a9b1ca3b4e/src/EditorFeatures/VisualBasicTest/BasicEditorServicesTest.vbproj#L61-L64
- [ ] The Editor's NuGet package for MS.VS.Text.Internal has an empty ref folder - the Editor needs to fix that.

Instead of referencing the .dll by specifying the full path in Include as above, here's what it should be doing instead:

```
<Reference Include="Microsoft.VisualStudio.Text.Internal">
 <HintPath>$(NuGetPackageRoot)\microsoft.visualstudio.text.internal\$(MicrosoftVisualStudioTextInternalVersion)\lib\net46\Microsoft.VisualStudio.Text.Internal.dll</HintPath>
</Reference>
```

**Comment by tannergooding** [comment]
> This line should have backslashes and not forward slashes

I don't think this is correct. The build should work regardless of whether forward or back-slashes are used, as you never know which slash your FS uses (you could be using a network share on Windows, for example).

**Comment by sharwell** [comment]
💭 It now looks like the problem could stem exclusively from our lack of a `PackageReference` that would place this assembly in the NuGet cache.

**Comment by tannergooding** [comment]
@sharwell, I would think we would catch that regularly. We explicitly clear the nuget cache for every MicroBuild CI run: https://github.com/dotnet/roslyn/blob/master/src/Tools/MicroBuild/microbuild.ps1#L86 and https://github.com/dotnet/roslyn/blob/817ade2b2dc8f80e86287b8cf726a9a83782276a/build/scripts/build-utils.ps1#L387

CC. @jaredpar

**Comment by jasonmalinowski** [comment]
First off, my bad for not putting a comment to the editor bug that was on the editor team to fix up their packages. When the code was written, the packages we _did_ reference via PackageReference had Text.Internal as a dependency, so it would get restored all the time.

> Instead of referencing the .dll by specifying the full path in Include as above, here's what it should be doing instead:

You really should never use HintPaths: HintPath only gets considered if all other resolutions fail. A truly fantastic way to have inconsistent builds across machines. NuGet adding them that way in package.config situations is a bug, so don't replicate it.

**Comment by jasonmalinowski** [comment]
And yes, it's correct we use forward slashes in the package path, since that produces paths that work on both Windows and non-Windows builds.

**Comment by KirillOsenkov** [comment]
@jaredpar thank you for being pedantic so I don't have to ;-P I wanted to reply with this exact same thing.

**Comment by jasonmalinowski** [comment]
That pull request has now been merged.
