### ISSUE TITLE
Flaky Tests: Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpReplIdeFeatures.AddUsing Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpReplIdeFeatures.QualifyName

### ISSUE THREAD

**Issue by etbyrd** [dotnet/roslyn#27128]
These tests are failing across multiple PR's are probably flaky/broken:

* Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpReplIdeFeatures.AddUsing
* Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpReplIdeFeatures.QualifyName

**Comment by sharwell** [comment]
Tests were failing due to a NullReferenceException introduced by 21127a0f. Can be observed in latest 15.8 builds if a user attempts to use the Add Using code fix in the C# interactive window.
