### ISSUE TITLE
Can't Click Obsolete Link Nor Copy It

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27139]
I just tried using a method that is marked as obsolete apparently.  That's great it told me this but the url is not clickable nor copyable.

Sidenote: I think VS should give a bigger UI warning that I'm about to use an obsoleted thing.

Please see the video.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/135063/cant-click-obsolete-link-nor-copy-it.html
VSTS ticketId: 512556_
_These are the original issue comments:_

Mike DePouw on 10/20/2017, 07:08 AM (216 days ago): <p><img src="https://developercommunity.visualstudio.com/storage/temp/15072-obsolete-method.png"></p><p>For reference, that is what I see.</p>

Mike DePouw on 10/20/2017, 07:10 AM (216 days ago): <p>As a workaround, I can F12 on the method and get the URL that way.</p><p><img src="https://developercommunity.visualstudio.com/storage/temp/15075-f12.png"></p>

Candy Zhang [MSFT] on 10/23/2017, 01:11 AM (213 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
From #50499:

> The text passed to [`ObsoleteAttribute(string)`](https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute.-ctor?view=net-5.0#System_ObsoleteAttribute__ctor_System_String_) is rendered as a text literal. There is no support for styles; the BCL team would need to define a syntax for styles before we could apply them here.
> 
> /cc @stephentoub @terrajobst

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
