### ISSUE TITLE
VB autoformat misformats second line of attributes

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#2714]
Paste a method declaration with multiple lines of attributes into a VB file (something like this):

```VB
        <Fact>
        <Trait(Traits.Feature, Traits.Features.KeywordRecommending)>
        Public Sub FinallyInTryNestedInCatch2()
            VerifyRecommendationsContain(<MethodBody>
        Try
        Catch
            Try ' Type an 'E' on the next line
            Catch
            |
                Throw
            End Try</MethodBody>, "Finally")
        End Sub
```
After the formatter runs, the second line of attributes is moved out to the margin of the file instead of being indented:

```VB
        <Fact>
<Trait(Traits.Feature, Traits.Features.KeywordRecommending)>
        Public Sub FinallyInTryNestedInCatch2()
            VerifyRecommendationsContain(<MethodBody>
        Try
        Catch
            Try ' Type an 'E' on the next line
            Catch
            |
                Throw
            End Try</MethodBody>, "Finally")
        End Sub
```

**Comment by mattwar** [comment]
@rchande I cannot repro this as a unit test or in ETA.

**Comment by rchande** [comment]
@mattwar A more specific repro: 
1. Open Roslyn.sln and navigate to FinallyKeywordRecommenderTests.vb
2. Copy the last unit test in the file.
3. Place the caret at the last unit test's "End Sub" and press return twice.
4. Ctrl-V to paste.

I can show you in person if neccessary.

**Comment by mattwar** [comment]
Sorry, still cannot repro.  I tried in VS w/ recent dogfood, and then with build from my machine under RoslynDev, both pasted correctly.

**Comment by rchande** [comment]
@mattwar I played around with it. You have to copy the the entirety of the line containing the first attribute, including the leading whitespace (easier to do if you turn on visible whitespace), and you need to paste after the last member in the type (there do seem to be some variations where it happens to the first member, too). Just for fun, I made a gif.
![paste](https://cloud.githubusercontent.com/assets/3751401/7662594/2be44538-fb13-11e4-85a5-a87d5e1b3ecb.gif)

**Comment by mattwar** [comment]
I'm not doubting it happens to you.  I cannot repro exactly this.

**Comment by mattwar** [comment]
One difference is, I don't have codelens on.

**Comment by dpoeschl** [comment]
This also repros for me fairly often in normal coding, and every time when I follow the repro steps (including copying the leading whitespace of the frirst attribute) -- in fact, I'm adding this comment because it just happened to me. :smile: Can @rchande or I swing by to try it out on your machine tomorrow?
