### ISSUE TITLE
please add refactors for init to ctor

### ISSUE THREAD

**Issue by MoonCakeLover123** [dotnet/roslyn#27144]
sometimes it is hard to find the ctor when the class is long.
and when the init needs to be across a few lines, the init needs to be in the ctor.
can a refactor suggestion be added to this?
like:
```cs
class a
{
    public static readonly string staticfield = "hi";
    //...
    public a()
    {
        //ctor stuff
    }
    //...
    public int prop { get; } = 42;
    //...
}
```
when i right click the prop and see suggested refactors, one new option should be available to turn into this:
```cs
class a
{
    public static readonly string staticfield = "hi";
    //...
    public a()
    {
        prop = 42;
        //ctor stuff
    }
    //...
    public int prop { get; }
    //...
}
```
then
```cs
class a
{
    public static readonly string staticfield;
    //...
    static a()
    {
        staticfield = "hi";
    }
    public a()
    {
        prop = 42;
        //ctor stuff
    }
    //...
    public int prop { get; }
    //...
}
```

**Comment by sharwell** [comment]
Design review conclusion:

We would accept a pull request implementing a new pair of refactorings to move a field initialization from the definition to a constructor, or vice-versa. This is straightforward for static fields, but instance fields need to make sure and handle multiple constructor scenarios. When moving the initialization from inline to an instance constructor, it would be acceptable to add the initialization to all instance constructors which do not use `this(...)` for chaining.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
