### ISSUE TITLE
Span<T> in async methods not supported

### ISSUE THREAD

**Issue by glucaci** [dotnet/roslyn#27147]
In actual release ```Span<T>``` cannot be used in async methods.

https://github.com/dotnet/roslyn/blob/5fbba2075b94dceb214ff7ee018a448f714b0275/src/Compilers/CSharp/Test/Semantic/Semantics/SpanStackSafetyTests.cs#L980

It's any plan to remove this constraint?

**Comment by svick** [comment]
See https://github.com/dotnet/csharplang/issues/1331.

**Comment by Bosch-Eli-Black** [comment]
@glucaci Can we close this as a duplicate of https://github.com/dotnet/csharplang/issues/1331 ?

**Comment by glucaci** [comment]
Sure, thanks!

**Comment by Bosch-Eli-Black** [comment]
@glucaci Np! 🙂
