### ISSUE TITLE
Visual Studio 2017 crash using local ref 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27153]
I have a method that takes a ref parameter (value type) like so:

public void Method(ref ValueStruct value)
{

}

I went to type the following in the body of the method:
_values[0] = ref value;

As soon as I put in the &quot;ref&quot; keyword on the line above, visual studio 2017 froze and crashed to the desktop.

I was able to reproduce this several times.  

Using Windows 10.0.17134.48
Visual Studio 2017 Pro (15.7.2, C# 7.3, .NET 4.7.1)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/258925/visual-studio-2017-crash-using-local-ref.html
VSTS ticketId: 620928_
_These are the original issue comments:_

messenger on 5/22/2018, 10:35 PM (2 days ago): Also, I disabled resharper and it still crashes.  So this is definitely something in VS2017.
_These are the original issue solutions:_
(no solutions)

**Comment by jcouv** [comment]
Tagging @agocke

**Comment by jcouv** [comment]
Narrowed down a repro (below). The problem seems to happen with various kinds of expressions on the left-hand-side (multiple kinds of expressions are not properly checked in `CheckValueKind` when the binding kind is `RefAssignable`).
I'm not very familiar with ref re-assignment, so I'll assign to Andy.

```C#
        [Fact]
        [WorkItem(27153, "https://github.com/dotnet/roslyn/issues/27153")]
        public void RefReassignIntoArrayAccess()
        {
            var comp = CreateCompilation(@"
class C
{
    int[] _values;
    void M()
    {
        _values[0] = ref
    }
}");
            comp.VerifyDiagnostics();
        }

        [Fact]
        [WorkItem(27153, "https://github.com/dotnet/roslyn/issues/27153")]
        public void RefReassignIntoDynamicAccess()
        {
            var comp = CreateCompilation(@"
class C
{
    void M()
    {
        dynamic x;
        x.Dynamic = ref
    }
}");
            comp.VerifyDiagnostics( );
        }
```

**Comment by jcouv** [comment]
@agocke This issue would probably still meet the 15.8 bar if you have time. Thanks

**Comment by agocke** [comment]
@jcouv Thanks! I believe all these cases were fixed in https://github.com/dotnet/roslyn/pull/28118
