### ISSUE TITLE
Question about metadata references / project references / compilation errors

### ISSUE THREAD

**Issue by pkrukp** [dotnet/roslyn#27151]
**Version Used**: 

Microsoft.CodeAnalysis 2.8.2

**Details**:

Hi,

I have following projects (attached solution):

1. "RefRefNetStandardWithNuget"
2. "ReferencesNetStandardWithNuget"
3. "NetStandardWithNuget"

Project 1 references project 2
Project 2 references project 3
Project 3 references nuget package "RestSharp"

I'm opening the 1st project, getting Compilation and checking Diagnostics (using MSBuildWorkspace).

Weird things - could you please explain why:

1. Even though I provide all required metadata references, I'm getting compilation errors.
2. If i additionally remove project references detected by MSBuildWorkspace and specify them as MetadataReferences, it works (no compilation errors).

**Reproduction steps**:

Attached files:
* ProjectsWithReferences.zip - contains multiple projects, but only 3 listed above are important
* TestCompilation - contains two projects, one which uses Microsoft.Build.Locator and generates list of references, and another which does not use it but configures references manually
* c1.txt to c4.txt - logs from command listed below

0. download, unzip, compile both solutions

1. use TestCompilation project to generate list of metadata and project references:

`TestCompilation\bin\Debug\TestCompilation.exe ..\ProjectsWithReferences\RefRefNetStandardWithNuget\RefRefNetStandardWithNuget.csproj assembly_ref.txt project_ref.txt > c1.txt 2>&1`

2. use TestCompilationNoLocator to compile without any custom references. Notice build errors (expected):

`TestCompilationNoLocator\bin\Debug\TestCompilationNoLocator.exe ..\ProjectsWithReferences\RefRefNetStandardWithNuget\RefRefNetStandardWithNuget.csproj  > c2.txt 2>&1`

3. Use TestCompilationNoLocator  to compile with providing metadata references (project references still left without change). Notice weird compilation errors, for example about lack of RestSharp, even though RestSharp.dll is on the metadata reference list

`TestCompilationNoLocator\bin\Debug\TestCompilationNoLocator.exe ..\ProjectsWithReferences\RefRefNetStandardWithNuget\RefRefNetStandardWithNuget.csproj assembly_ref.txt > c3.txt 2>&1`

4. Same as previously, but also provide project references (which will clear real project references in MSBuildWorkspace and provide them as metadata references). There are no errors now...

`TestCompilationNoLocator\bin\Debug\TestCompilationNoLocator.exe ..\ProjectsWithReferences\RefRefNetStandardWithNuget\RefRefNetStandardWithNuget.csproj assembly_ref.txt project_ref.txt > c4.txt 2>&1`

[ProjectsWithReferences.zip](https://github.com/dotnet/roslyn/files/2039890/ProjectsWithReferences.zip)
[TestCompilation.zip](https://github.com/dotnet/roslyn/files/2039891/TestCompilation.zip)
[c1.txt](https://github.com/dotnet/roslyn/files/2039894/c1.txt)
[c2.txt](https://github.com/dotnet/roslyn/files/2039895/c2.txt)
[c3.txt](https://github.com/dotnet/roslyn/files/2039896/c3.txt)
[c4.txt](https://github.com/dotnet/roslyn/files/2039897/c4.txt)

**Comment by jcouv** [comment]
Tagging @DustinCampbell

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of response.
