### ISSUE TITLE
Show potential fixes link does not work 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#27168]
Ported from [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/615744)
Affected Branch: [27710.0.d15.8]
Affected Build: 15.8.0 Preview 2.0
Affected Product Language: 

Steps to reproduce:

1. Create new Class Library (.NET Framework) project 
2. Add following code to Class: 

```csharp
public Int32[,] Properties { get; set; } 

public void Foo() 

{ 

    var list = new List<string>(); 

    list.Add("dsfds"); 

  

    var a = DateTime.Now.ToString("MM"); 

} 

  

public string ToString() 

{ 

    return "test"; 

} 
```

3. Hover mouse over `ToString()` 

4. Click on "Show potential fixes" link or click on light bulb near ToString or press Alt+Enter or Ctrl+. 

 

Expected: context menu with fix variants appeared 

Actual: context menu with fix variants is not appeared 

 

Note: click on light bulb on the left side of editor works 

You can also install Microsoft.CodeAnalysis.FxCopAnalyzers NuGet package to get more warnings (which also does not work) 

 

[Repro Gif ](https://microsoft-my.sharepoint.com/:i:/p/v-rodudi/EW6EdGrawN9DoHaST8AZzBgByy3qd5_4wiiakqKvFh72yg?e=XLQHWc)

**Comment by jinujoseph** [comment]
Affected Branch: [27911.0.d15.8]
Affected Build: 15.8.0 Preview 5.0
Affected Product Language: 

Steps to reproduce:

1. Create Class Library C# project
2. Add Class1:
public abstract class Class1
{
    [Obsolete]
    public abstract void Foo();
}
3. Add Class2:
class Class2 : Class1
{
    public override void Foo()
    {
        throw new NotImplementedException();
    }
}
4. Hover mouse over underlined Foo
5. Click on Show potential fixes

Expected: menu with option "add the Obsolete attribute to method" appears
Actual: nothing happens 

6. Place cursor to underlined Foo
7. Press Alt+Enter or Ctrl+.

Expected: option "add the Obsolete attribute to method" is available
Actual: option "add the Obsolete attribute to method" is not available

[Repro Gif](https://microsoft-my.sharepoint.com/:i:/p/v-rodudi/ETXvSlHcmI1LqlY9GXdEWwYBCXQgAs_k11RopNtMpolqDg?e=KqRRiD)

**Comment by CyrusNajmabadi** [comment]
Closing out as this works fine for me locally.  Likely an old issue long since fixed.
