### ISSUE TITLE
Searching 'decompile' or 'decompiler' in quick launch returns no results

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27171]
I'd expect searching either of these to bring up an entry that takes me to the page to enable the built-in .NET decompiler.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/244312/searching-decompile-or-decompiler-in-quick-launch.html
VSTS ticketId: 610143_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
Related to #14975

**Comment by gundermanc** [comment]
#26579 has a link to the file that needs to be updated.

**Comment by sharwell** [comment]
@gundermanc Yes, I picked this direction for the duplicate since the title is more clear. @JieCarolHu implemented one of these recently so she's familiar with the process, but that link to the specific line will be helpful in narrowing down *exactly* where the fix goes. 😄

**Comment by CyrusNajmabadi** [comment]
i get:

![image](https://user-images.githubusercontent.com/4564579/217945017-78431a7a-3a3d-4555-82a9-4a1afd1ddb73.png)
