### ISSUE TITLE
Implementing abstract class should make method async if method returns a Task

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#27181]
From `B`, if you **Ctrl+.** to implement the abstract class, the override isn't marked as async:

![image](https://user-images.githubusercontent.com/1402694/40573870-db9e8a52-607c-11e8-98b3-b2f81a2036d5.png)

**Expected**:
```csharp
public override async Task MyMethodAsync()
        {
            throw new NotImplementedException();
        }
```

Snippet:

```csharp
 public abstract class A
 {
        public abstract Task MyMethodAsync();
 }

    public class B : A
    {

    }
```

**Comment by Neme12** [comment]
This is not a bug. Making the method async isn't often necessary. It's a reasonable request though. Should we always do this when the method returns Task-like? Or when it returns a Task-like *and* ends with "Async"?

**Comment by CyrusNajmabadi** [comment]
I would prefer we not make it async.  Making it async will the just warn that you're not using 'await'.

**Comment by Neme12** [comment]
Is this customer aware they can just hit ctrl. the first time they use an `await` to make the method async?

**Comment by dpoeschl** [comment]
Design Meeting Notes:

We agree that the current behavior is the intended design. 

As @Neme12 points out, the async is easily added the first time an `await` is used, which alleviates much of the annoyance here (assuming someone knows to do it that way).
