### ISSUE TITLE
Please stop adding opinionated style-based code analysis to the error list

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27195]
I upgraded my build in 15.8, and Error List which was previous "clean" under all categories, had about ~500 of these 

```
Severity	Code	Description	Project	File	Line	Suppression State
Message	IDE0046	'If' statement can be simplified	Microsoft.VisualStudio.Editors	E:\project-system2\src\Microsoft.VisualStudio.Editors\SettingsDesigner\SettingsValueSerializer.vb	90	Active
Message	IDE0046	'If' statement can be simplified	Microsoft.VisualStudio.Editors	E:\project-system2\src\Microsoft.VisualStudio.Editors\SettingsDesigner\SettingsValueSerializer.vb	145	Active
Message	IDE0046	'If' statement can be simplified	Microsoft.VisualStudio.Editors	E:\project-system2\src\Microsoft.VisualStudio.Editors\SettingsDesigner\TypeEditorHostControl.vb	513	Active
Message	IDE0046	'If' statement can be simplified	Microsoft.VisualStudio.Editors	E:\project-system2\src\Microsoft.VisualStudio.Editors\SettingsDesigner\TypeEditorHostControl.vb	551	Active
Message	IDE0046	'If' statement can be simplified	Microsoft.VisualStudio.Editors	E:\project-system2\src\Microsoft.VisualStudio.Editors\SettingsDesigner\TypeEditorHostControl.vb	618	Active
Message	IDE0046	'If' statement can be simplified	Microsoft.VisualStudio.Editors	E:\project-system2\src\Microsoft.VisualStudio.Editors\SettingsDesigner\TypeEditorHostControl.vb	787	Active
Message	IDE0046	'if' statement can be simplified	Microsoft.VisualStudio.ProjectSystem.Managed.TestServices	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices\ProjectSystem\ProjectTreeParser\Tokenizer.cs	30	Active
Message	IDE0046	'if' statement can be simplified	Microsoft.VisualStudio.ProjectSystem.Managed.TestServices	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices\ProjectSystem\ProjectTreeParser\Tokenizer.cs	123	Active
Message	IDE0046	'if' statement can be simplified	Microsoft.VisualStudio.ProjectSystem.Managed.TestServices	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices\ProjectSystem\ProjectTreeParser\Tokenizer.cs	145	Active
```

I looked at the changes it wanted to make here's one:

``` VB
    If items.Length = 0 Then
        Return NativeMethods.S_OK
    End If
    Return VsUIShell2Service.SaveItemsViaDlg(CUInt(items.Length), items)
```

It wanted to change to:

``` VB
Return If(items.Length = 0, NativeMethods.S_OK, VsUIShell2Service.SaveItemsViaDlg(CUInt(items.Length), items))
```

I do not believe that it makes the code better or clearer, while I understand that some people like this form, I do not. That's what makes it a style choice. These style based should not appear in my Error List unless I've either got a setting that indicates what behavior I'd like (think var settings) **or** I'll deliberated opt'd in them. Show them as a ... in the editor or whatever, but my Error List are things that I need to address - I should haven't keep turning off rules every time I upgrade my VS.

**Comment by davkean** [comment]
_From @KirillOsenkov on May 27, 2018 2:41_

+1. These bug me a lot too.

**Comment by davkean** [comment]
Ugh wrong repo.

**Comment by sharwell** [comment]
👍

**Comment by CyrusNajmabadi** [comment]
> Show them as a ... in the editor or whatever, but my Error List are things that I need to address -

@heejaechang @mavasani Is there some way we can control things so that these don't go in the error list?  Maybe that's a checkbox that could go along with all the items in the codestyle list?

**Comment by sharwell** [comment]
@CyrusNajmabadi the error list has a filter for "Messages" which can remove items at that severity.

**Comment by Neme12** [comment]
If this is my preferred code style with a severity of suggestion, I *want* this to be in the error list. What if we just changed the default severity to silent?

**Comment by davkean** [comment]
I'm not proposing a design of how this works, but I would expect something like:

1) By default style/opinion-based rules do not appear in Error List
2) They appear someone else, perhaps that ... thing in the editor
3) We let you opt into styles so that they do appear in Error List

**Comment by heejaechang** [comment]
@jinujoseph @kuhlenh if one doesn't want it on error list, it should use different severity (hidden?)

**Comment by CyrusNajmabadi** [comment]
@heejaechang It might be nice if individual fixes could specify if they want to show up in the diagnostic list or not.  ideally, this could be controlled by the user.  The reasoning here is that users use the 'error list' as a worklist, and they want it to be perpetually 'empty' unless htere is something they really feel needs to be 'fixed'.  However, there are 'suggestions' which are generally felt to be useful if the user is looking at that code, but which doesn't rise to the level of needing to actually be 'fixed' in all cases.  

So either we have a new class of diagnostics.  i.e.  it's a suggestion, but shouldn't show in the error list.   Or we want to be able to configure "should this show in the error list" on a per code-style option.  i.e. "for this particular suggestion, let me know in the editor, but *not* in the error list.

I personally feel like there is merit to both.   The error list is often a todo-list for people, and having all suggestions show up in it doesn't necessarily make sense for all users.  Thoughts?

Also tagging @DustinCampbell @Pilchie @sharwell  for their thoughts here as this is a really interesting design space with a lot of subtleties!

**Comment by heejaechang** [comment]
there are multiple things involved on diagnostic presentation.

first is diagnostic analyzer author who augment diagnostic (data) with 1. severity, 2. category, 3. tag and 4. property. those data can alter presentation of the diagnostic reported.

second is users who can modify 1. severity to alter presentation of the diagnostic reported.

and there are presentations such as error list, taggers/adornments, scrollbar and etc. each presentation uses some of (1..4) to figure out how to show data to users.

here only thing user can change is 1. the severity. (2...4) is locked to the diagnostic analyzer author.

..

if we want to let users to decide whether something should show up in error list or not, severity is the thing we should use (unless we want to create yet another mechanism). and for ones that we don't want to show in error list, we already have "hidden" severity.

if we don't want to let users to decide whether something show up in error list or not, and only diagnostic analyzer author should have that power, then we can use (2..4) and change error list to know that contract (it is new thing)

..

I believe currently tagger uses (1. severity + 2. tag) to specialize tagger presentation. so, if we do "hidden", we should introduce new tag (suggestion) so that tagger can still show "..." for (hidden + suggestion) diagnostic (this is new thing)

..

but we can do other way if we want to by creating another system.

**Comment by NickCraver** [comment]
Just found this - I also strongly dislike this refactor suggestion. It wants to turn multi-line `if` statements into ternaries. That's not "simplifying" the code. It makes it harder to read and follow, and thus more error prone. IDEs should not do that. If I have this:
```c#
public object TestMethod(bool condition)
{
    if (condition)
    {
        return new
        {
            Line1 = "true",
            Line2 = "true",
            Line3 = "true",
            Line4 = "true",
            Line5 = "true",
            Line6 = "true",
            Line7 = "true",
            Line8 = "true",
            Line9 = "true",
            Line10 = "true",
            Line11 = "true",
            Line12 = "true",
            Line13 = "true",
            Line14 = "true",
            Line15 = "true",
            Line16 = "true",
            Line17 = "true",
            Line18 = "true",
            Line19 = "true",
            Line20 = "true",
            Line21 = "true",
        };
    }
    else
    {
        return new
        {
            Line1 = "false",
            Line2 = "false",
            Line3 = "false",
            Line4 = "false",
            Line5 = "false",
            Line6 = "false",
            Line7 = "false",
            Line8 = "false",
            Line9 = "false",
            Line10 = "false",
            Line11 = "false",
            Line12 = "false",
            Line13 = "false",
            Line14 = "false",
            Line15 = "false",
            Line16 = "false",
            Line17 = "false",
            Line18 = "false",
            Line19 = "false",
            Line20 = "false",
            Line21 = "false",
        };
    }
}
```
It suggests turning it into:
```c#
public object TestMethod(bool condition)
{
    return condition
        ? (new
        {
            Line1 = "true",
            Line2 = "true",
            Line3 = "true",
            Line4 = "true",
            Line5 = "true",
            Line6 = "true",
            Line7 = "true",
            Line8 = "true",
            Line9 = "true",
            Line10 = "true",
            Line11 = "true",
            Line12 = "true",
            Line13 = "true",
            Line14 = "true",
            Line15 = "true",
            Line16 = "true",
            Line17 = "true",
            Line18 = "true",
            Line19 = "true",
            Line20 = "true",
            Line21 = "true",
        })
: (new
{
    Line1 = "false",
    Line2 = "false",
    Line3 = "false",
    Line4 = "false",
    Line5 = "false",
    Line6 = "false",
    Line7 = "false",
    Line8 = "false",
    Line9 = "false",
    Line10 = "false",
    Line11 = "false",
    Line12 = "false",
    Line13 = "false",
    Line14 = "false",
    Line15 = "false",
    Line16 = "false",
    Line17 = "false",
    Line18 = "false",
    Line19 = "false",
    Line20 = "false",
    Line21 = "false",
});
```
That's just plain silly. And not simpler. It shouldn't suggest it with many-line `if` statements regardless of when it should display at all.

Regardless of *how* (no strong feelings on the implementation): please don't show this to people by default. I am actively disabling it in rulesets across all of our repos because it's only an annoyance.

**Comment by Neme12** [comment]
@NickCraver

I'm sorry but I don't see how that's silly at all except for the bad formatting and redundant parentheses. By using `?:`,  you're factoring out common code and reducing the scope of the branch, which is generally a good thing. Maybe you could make an argument with respect to readability (which *is* a matter of opinion), but there's absolutely nothing simpler about duplicating the return statement.

Regardless of whether this is on or off by default, I don't want to lose the option of having this on multi-line expressions.

**Comment by NathanaelA** [comment]
I have to agree with Nick here; switching to a Ternary does not make it easier to understand, especially when it is multi-lined, because then you are looking for a single character delimiter ```:``` instead of a simple ```} else {``` .   a ``` } else { ``` does not easily get lost in the rest of the characters...

**Comment by sharwell** [comment]
I find most refactorings from if/else to ternary expressions reduce readability. I'm against anything that would *encourage* users to switch to ternary.

**Comment by mavasani** [comment]
In general, any style based analyzer/codefix/refactoring that has so many different (strong) opinions should be disabled by default. Tagging @jinujoseph - we should disable the analyzer by default for now and then look at desirable experience after discussion at design meeting.

**Comment by sharwell** [comment]
> disable the analyzer by default 

I would actually move it to Hidden severity by default so it is still operational, but isn't proactive like it is now.

**Comment by mavasani** [comment]
@sharwell, that works too.

**Comment by jinujoseph** [comment]
I agree with Sam's suggestion lets mark it as hidden till we figure out a better experience

**Comment by heejaechang** [comment]
is hidden codefix and refactoring show same LB? I think for such case like the above, it should show refactoring LB not any of those suggestion or error lightbulb.

since, as long as I understand, we have refactoring specific LB to convey users that this is completely fine to ignore. we just have an automatic code transformation for this code snippet in case you want to change.

**Comment by sharwell** [comment]
@heejaechang Hidden diagnostics are supposed to use the refactoring light bulb, yes

**Comment by CyrusNajmabadi** [comment]
This works for me. This was an open question in the original PR: https://github.com/dotnet/roslyn/pull/26236#discussion_r183218203

However, it was never answered.  I think the presumption was that if this was an issue for people, that we could trivially change hte default later if need be (as we seem to want to now).
