### ISSUE TITLE
Add a command that can comment/uncomment depending on context

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27198]
We currently have a command for comment and command for uncomment. R# has a single command that comments/uncomments based on the context. It would be nice if we add a similar one.

https://twitter.com/janwilmans/status/1000387246774767616

**Comment by Neme12** [comment]
Can you please explain what this means? How would the behavior change based on context?

**Comment by Neme12** [comment]
Ok I think I understand. The command would ether comment or uncomment depending on whether the code is alredy commented out?

**Comment by davkean** [comment]
When selecting the following block and running command, this would be uncommented:

``` C#
// if (foo)
// {
//    Console.WRiteLine(foo)
// }
```

When selecting the following block and running command, this would be comment:

``` C#
if (foo)
{
   Console.WRiteLine(foo)
}
```

**Comment by janwilmans** [comment]
Yes, however, the typical usecase would be:

```
void foo(int bla, double a, double b, double c)
{

}
```
double click 'valueA', '/', 
double click 'valueB', '/', 
double click 'valueC', '/', 

```
void foo(int bla, double /*valueA*/, double /*valueB*/, double /*valueC*/)
{

}
```
This is particularly useful in cases where warings-as-errors in enabled and you are incrementally developing your function

**Comment by jinujoseph** [comment]
cc Editor team (@olegtk  we will like to work together for multiple language consistency)

**Comment by dpoeschl** [comment]
Design Meeting Notes:

1. Should we make a unified command? We're interested in getting more feedback on whether this would be useful enough. 
2. Should there be some sort of special invocation method when text is selected? No, we don't want to interfere with the user's typing for this feature at this time.

**Comment by dpoeschl** [comment]
> particularly, since ctrl-k, ctrl-u, ctrl-k, ctrl-c is almost impossible to type with one hand.

@janwilmans - Is there a reason you can't remap those commands to something one-hand-able for you?

**Comment by olegtk** [comment]
CC @justcla

On the editor level we always wanted such a command (mainly because it's very popular and VS for Mac has it already), but obviously it's language specific. 
We can take on driving some unification design/discussion and defining a command, but each language would have to implement it.

**Comment by justcla** [comment]
Can we please re-label this issue: Add command for ToggleLineComment?

**Comment by justcla** [comment]
There are two keys concepts behind ToggleLineComment.
1. A single shortcut (easy to remember, easy to use) that can be used to comment or uncomment the code.
2. It applies LINE comments to every line that's part of the selection.

Additionally, there should be an option (on by default) to move down to the next line after invoking ToggleLineComment with no selection. This enables users to press it repeatedly as they work down the page marking out lines they don't want. Saves having to pre-select the whole block first.

The current implementation requires the user to remember and invoke two separate shortcuts. The current default shortcuts are both two-handed and require two chords to activate it.
(It's easier to press HOME / / than it is to press Ctrl+K, Ctrl+C.)

The current implementation of Comment will apply a block comment to a selection that exists on just one line. If the selection expands over multiple lines, it applies Block comment.

With a ToggleLineComment comment, the user could comment out the line without first removing their selection.

Ideally, the user should be able to choose if they want a block comment or a line comment. A separate command could be created for ToggleBlockComment.

Suggested shortcuts:
ToggleLineComment - Ctrl+/
ToggleBlockComment - Ctrl+Shift+/

**Comment by justcla** [comment]
There is an example implementation of this in HotCommands

**Comment by justcla** [comment]
Yeah, I had the extension read XML files, just so we could more easily open the files in an XML editor for pretty printing. Go with XML if you can.

**Comment by janwilmans** [comment]
> Can we please re-label this issue: Add command for ToggleLineComment?

Would that not be confusing? as depending on what is selected, the command should do a ToggleLineComment or a ToggleBlockComment ?

**Comment by janwilmans** [comment]
> > particularly, since ctrl-k, ctrl-u, ctrl-k, ctrl-c is almost impossible to type with one hand.
> 
> @janwilmans - Is there a reason you can't remap those commands to something one-hand-able for you?

@dpoeschl if there was a command called ToggleCommentSelection (instead of separate commands UncommentSelection/CommentSelection) I think that would be an acceptable compromise.

**Comment by janwilmans** [comment]
different proposal, what is 'selecting text' would be the first chord ?
![image](https://user-images.githubusercontent.com/5933444/46244465-b1e42b80-c3ce-11e8-8253-361957c21823.png)

That way the user can decide how this behavior works and it would not be tied to a language.
It would still depend on the availability of Edit.ToggleComment for each language. (in which I would vote to add it in C++ :)

**Comment by justcla** [comment]
> > Can we please re-label this issue: Add command for ToggleLineComment?
> 
> Would that not be confusing? as depending on what is selected, the command should do a ToggleLineComment or a ToggleBlockComment ?

I find current behaviour confusing and limiting. With two separate commands, a user can chose whether to comment the lines (with // at the beginning of each line) or comment the selection (with /* */ around the selection).

The way it is today, to toggle line comment on a single line today, a user needs to clear the current selection, otherwise they just get the selected text commented with block comments.

Also, a Comment on a partial line selection over multiple lines will do a Line comment. There is no way to comment just the selected text if your selection spans two or more lines.

Having a ToggleBlockComment would allow users to comment out just what's selected. If they want to comment the entire line, the ToggleLineComment would be available.

Languages like HTML would implement ToggleLineComment by properly escaping and commenting everything on the line. ToggleBlockComment would just comment out the selected text.

Some languages would only need to implement ToggleLineComment.

**Comment by justcla** [comment]
Perhaps ToggleBlockComment might be better understood as ToggleSelectionComment, with ToggleLineComment being the partner.
One pays attention to the selection boundaries, the other acts on all lines spanned by the selection.

**Comment by janwilmans** [comment]
I'd like to chat/talk, are you on skype ? I'm 'janwilmans'

**Comment by janwilmans** [comment]
After a chat with @justcla I think we are in complete agreement that toggling comments should be handled just like toggling 'bold' or 'italic', so there should be a command ToggleSelectionComment.
(and he's btw a wonderful engineer everybody should listen too ! and he totally did not tell me to say that)

While exchanging our viewpoints we actually found that depending on what your current selection is the current behavior of CommentSelection/Uncomment Selection is really weird.

![image](https://user-images.githubusercontent.com/5933444/46249875-111e5c00-c420-11e8-9de6-5f39fa2717d9.png)

ctr-k, ctrl-c, turns it into:

![image](https://user-images.githubusercontent.com/5933444/46249878-17143d00-c420-11e8-864d-bb505e250d5a.png)

![image](https://user-images.githubusercontent.com/5933444/46249870-0368d680-c420-11e8-8a6e-f3c0d5bf13f2.png)

ctr-k, ctrl-c, turns it into:

![image](https://user-images.githubusercontent.com/5933444/46249873-095eb780-c420-11e8-9cda-e21a894b4b47.png)

**Comment by janwilmans** [comment]
And then the way this is invoked is through a single ToggleSelectionComment command.

**Comment by justcla** [comment]
Thanks @janwilmans.

Yes, one command to toggle the selection (ie. ToggleSelectionComment)
and a separate command to toggle the line/s (ie. ToggleLineComment).

Is that how you understand it?

Shortcuts:
The most basic shortcut, (Ctrl+/) should be assigned to ToggleLineComment, as this is the one most people want most often.
ToggleSelectionComment could be assigned Ctrl+Shift+/. The beauty of this from a shortcut standpoint is that Shift is used to create a selection. So it's nice that Shift is added to the ToggleComment to have it apply to a selection. :-)

**Comment by janwilmans** [comment]
There is one part where I'm not sure we are in agreement, when I use ToggleSelectionComment and I happen to have exactly a series of whole lines selected, I would want to the do a ToggleLineComment instead. That way you effectively never have to use ToggleLineComment if you don't want to.

**Comment by justcla** [comment]
Then don't use ToggleSelectionComment. Use ToggleLineComment instead.

Generally, you'd always use ToggleLineComment, and only use ToggleSelectionComment when you want to comment a selection.

To have a command do line comment sometimes and block comment other times would be confusing (as you demonstrated in your example above).

**Comment by janwilmans** [comment]
Anyway, the most important thing is probably to at least have the consistency that is missing now, ctrl-k, c and ctrl-k,u behave different now depend on what is selected. If we could clean that up by adding just ToggleSelectionComment and ToggleLineComment would make me very happy.

**Comment by CyrusNajmabadi** [comment]
Note: i'm finding htis conversation *super* confusing to keep track of.  If any work happens here, it would be great if it could take the approach of listing out example inputs, the command executed, and what the exact output expected should be.  Thanks!

**Comment by janwilmans** [comment]
Right, I will try to be crisp:

![image](https://user-images.githubusercontent.com/5933444/46249943-2f388c00-c421-11e8-87fe-7c2823834e0a.png)

ToggleSelectionComment turns this into:

![image](https://user-images.githubusercontent.com/5933444/46249922-e8e32d00-c420-11e8-85c5-63de16cd7a84.png)

and:

![image](https://user-images.githubusercontent.com/5933444/46249929-fc8e9380-c420-11e8-864d-05cda0bc7d73.png)

ToggleLineComment turns this into:

![image](https://user-images.githubusercontent.com/5933444/46249935-116b2700-c421-11e8-9d79-128cdb262f4c.png)

**Comment by CyrusNajmabadi** [comment]
I'd definitely like examples that crispify how selectiosn matter (especially for ToggleCommentSelection).  Your example is super weird in that the selection starts inside the comment and spreads outside of it.  I'm not sure what i would expect 'toggleselection' to do if invoked on htat again :)

**Comment by janwilmans** [comment]
Sorry, that screenshot is based on the current behaviour which is admittedly weird. I will correct that using paint :)

**Comment by CyrusNajmabadi** [comment]
Usually it's good to use ``~~`` markers if they're very old.  If you mean stuff you just wrote, feel free to edit :)  The problem generally arises if someone has already quoted you and whatnot.  If that hasn't happened, no biggy.  And, evne if it has happened, it's probably ok too :D

**Comment by janwilmans** [comment]
Btw, why is this a /roslyn thing? how is this part of the compiler and not the IDE? 
Asking because I also have a proposal for filtering of the output-pane, should I create an issue here?

**Comment by CyrusNajmabadi** [comment]
Roslyn *is* the IDE as well.  Not just hte compiler.

**Comment by janwilmans** [comment]
Ok, I did not know, that makes sense then :)

**Comment by dibarbet** [comment]
Toggle block comment and toggle line comment were added [starting in 16.1](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#net-productivity).  I believe these two commands should roughly address the requests in this issue.

**Comment by davkean** [comment]
@dibarbet Nice!

**Comment by justcla** [comment]
Bravo!!
Does it include the option to move down a line after invoking ToggleLineComment?

**Comment by justcla** [comment]
https://github.com/dotnet/roslyn/issues/27198#issuecomment-501076030

Really nice to see this in Visual Studio 16.1!!

Obviously, it will be better when applied to a single-key shortcut instead of a chord.

Also, the changing of caret position and selection is really annoying. It keeps moving my caret to the end of the line, which is not helpful.

Notes:
1. For ToggleLineComment applied to a single line with no selection, it would be more useful if it moved the caret down one line. (And keep the caret at the same column position)
- This could be a setting in Tools->Options (on by default)

2. Leave the caret where it started. When applying ToggleLineComment there is no need for the selection to change. Also, there is no need for the caret to move. It can stay where it was. Just need to apply comment markers to the start of each line involved in the selection. (Except for the last line if caret at posn 0).

**Comment by davkean** [comment]
@justcla This bug is closed, please open a new bug.

**Comment by justcla** [comment]
Leave selection unchanged when applying ToggleLineComment #36349

**Comment by justcla** [comment]
Leave caret unchanged when applying ToggleBlockComment #36350

**Comment by justcla** [comment]
Move down one line when applying ToggleLineComment with no selection #36351

**Comment by justcla** [comment]
Done, sir.
Thanks for implementing really great features Dave and team. Keep up the great work.
