### ISSUE TITLE
Incorrect IBinaryOperation.OperatorKind

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#27209]
**Version Used**: 
Microsoft.CodeAnalysis v2.8.0

**Steps to Reproduce**:
1. Obtain `IBinaryOperation` for the next expression (`i` is `int?`):
```csharp
(i != null && i > 5)
```

**Expected Behavior**:
`IBinaryOperation.OperatorKind` equals `BinaryOperatorKind.ConditionalAnd` (0x0d)

**Actual Behavior**:
`IBinaryOperation.OperatorKind` equals `BinaryOperatorKind.And` (0x0a)

Possibly caused at [CSharpOperationFactory.Helper.DeriveBinaryOperatorKind](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Operations/CSharpOperationFactory_Methods.cs,294), where the [Logical](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Binder/Semantics/Operators/OperatorKind.cs,318) flag (0x0002_0000) is cut off by [OpMask](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Binder/Semantics/Operators/OperatorKind.cs,299) (0x0000_FF00).

**Comment by bkoelman** [comment]
Looks like this is a duplicate of #23956.

**Comment by mavasani** [comment]
Yes, this has been fixed and the fix should be in 15.8 Preview3

**Comment by jinujoseph** [comment]
This was fixed in #24263
