### ISSUE TITLE
VB: Auto-complete should offer `MustInherit` keyword when declaring class in module.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#27206]
**Version Used**: 

Visual Studio Community 2017 v15.5.6

**Steps to Reproduce**:

In a VB project, define a module and try to declare a `MustInherit` class in it:

```vb
Public Module SomeModule
  Public Mus '<--- auto-complete should kick in here and offer the MustInherit keyword.
End Module
```

Having typed a few letters `Mus` from the keyword `MustInherit`, auto-complete should kick in an offer to finish off for you, but it doesn't when declaring the class inside a module. When you do it outside a module it works:

![vs_mustinherit_autocomplete](https://user-images.githubusercontent.com/20465797/40615746-c027fcca-6290-11e8-9640-f888cc1f85e6.png)

**Expected Behavior**:

**Auto-complete should offer the `MustInherit` keyword in any context where a class can be declared.** As a matter of fact, I think several keywords suffer this problem (just tried it with `NotInheritable` as well - same problem: it is offered when declaring a class outside a module but not when declaring a class inside a module).

**Comment by ericmutta** [comment]
Hi @sharwell, when you get a second, kindly review and tag this one too so it doesn't fall through the cracks. Many thanks as always :+1:

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
