### ISSUE TITLE
Move type to file is not proposed when a class and a generic version of it are in the same file

### ISSUE THREAD

**Issue by k94ll13nn3** [dotnet/roslyn#27205]
**Version Used**: Visual Studio Entreprise 15.7.2

**Steps to Reproduce**:

1. Create a file named `Class1.cs` with a class `Class1` and a class `Class1<T>` in it
2. Open the refactoring menu on the second class (`Class1<T>`).

**Expected Behavior**: "Move type to file" is proposed and will move `Class1<T>.cs` to a new file named ``Class1`1.cs`` or a similar name.

**Actual Behavior**: "Move type to file" is not proposed.

I search the repo for something similar, the only issue that i found was #13583 on the name of the generic class file, but it assumed that I am able to move the type.

If the second class is named `Class2<T>`, the refactoring is proposed. 

I guess that since `Class1<T>` would be moved to a file named `Class1.cs` and that this is the file where it is, the refactoring does not detect it.

**Comment by sharwell** [comment]
The majority of this is ready to be implemented. The specific name proposed still needs to be discussed in a design review, but the decisions from that review would be easy to apply to an existing implementation of the feature.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack fo feedback.
