### ISSUE TITLE
DocumentEditor.AddAttribute does not always add the assembly keyword.

### ISSUE THREAD

**Issue by kfertitta** [dotnet/roslyn#27200]
15.7.2: 

**Steps to Reproduce**:

1. Open a minimal C# console app in an `MSBuildWorkspace`.
2. Add an assembly-level attribute to one of the source files in the project, say `Program.cs`.
3. Get a `Document` instance for the file.
4. Get a `DocumentEditor` instance for the file.
5. Create an assembly-level attribute via the following:
```
            var attrList =
                SyntaxFactory.AttributeList(
                    SyntaxFactory.SingletonSeparatedList(
                        SyntaxFactory.Attribute(
                            SyntaxFactory.IdentifierName("Foo"))))
                .WithTarget(
                    SyntaxFactory.AttributeTargetSpecifier(
                        SyntaxFactory.Token(SyntaxKind.AssemblyKeyword)));
```
6. Call `DocumentEditor.AddAttribute` on the `CompilationUnit` associated with the file, supplying the above attribute list.
7. Note that the `assembly` keyword is not added to the file.
8. Now remove any assembly-level attributes from the source file.
9. Repeat the experiment and note that the `assembly` keyword is properly added.

**Expected Behavior**:
The `assembly` keyword should always be added if the proper `AttributeTargetSpecifier` is included.

**Actual Behavior**:
The `assembly` keyword is only added if there are no other assembly-level attributes in the compilation unit.

See attached repro.
[RoslynTest.zip](https://github.com/dotnet/roslyn/files/2042865/RoslynTest.zip)

**Comment by CyrusNajmabadi** [comment]
There's this very odd line i can't figure out the purpose of:

```((AttributeListSyntax)node).WithTarget(null);```

at:

https://github.com/dotnet/roslyn/blob/d6f483e56b7089ec08b0af2edc0b9aeda498bfe3/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L929

Seems like it could likely be the culprit.

**Comment by kfertitta** [comment]
Certainly looks suspicious to me, not being a contributor, obviously.

**Comment by kfertitta** [comment]
Has this issue been fixed?  It was reported some time ago and seemed simple enough.
