### ISSUE TITLE
Formatting is applied too aggressively on 'override' completion

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#27207]
**Version Used**: 15.7

The formatting applied when inserting an override includes a larger span than necessary:

* It includes leading trivia from previous lines which is not related to the operation
* It includes trailing trivia which is not related to the operation
* It includes the leading trivia from the next code element, which results in changing the indentation of an unrelated code element

All code (including trivia) on lines before and after the line containing the original `override` keyword should not be altered by this operation.

**Steps to Reproduce**:

```csharp
namespace MyNamespace
{
  class MyClass
  {
  public int MyProperty { get; }
  // Some comment

    override$$

      public void MyMethod1() { }
      public void MyMethod2() { }
  }
}
```

1. Disable all automatic formatting options for C# code (e.g. format on paste, `\`, return, and `}`
1. At the `$$`, press space an use completion to insert an override for `object.ToString()`

**Expected Behavior**:

```csharp
namespace MyNamespace
{
  class MyClass
  {
  public int MyProperty { get; }
  // Some comment

    public override string ToString()
    {
      throw new NotImplementedException();
    }

      public void MyMethod1() { }
      public void MyMethod2() { }
  }
}
```

**Actual Behavior**:

```csharp
namespace MyNamespace
{
  class MyClass
  {
  public int MyProperty { get; }
    // Some comment

    public override string ToString()
    {
      throw new NotImplementedException();
    }

    public void MyMethod1() { }
      public void MyMethod2() { }
  }
}
```

**Comment by CyrusNajmabadi** [comment]
Closing out as won't fix.  We do touch up to the token following the method being generated to ensure the formatting of what iss right after being typed is fixed up.
