### ISSUE TITLE
Indenting doesn't Revert

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27219]
I code in VB.NET. Since the 15.6.6 update, a rather annoying issue has popped up - indents do not revert after completing a block.

In other words, say I start an if statement above some code. That code, and everything below it, auto-indents another tab as expected. However, closing the if statement above that same code will not revert the code below it back to it's correct position. So, I've inserted an if statement block above existing code, it indented, and then I closed off the if above that indented code.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/241877/indenting-doesnt-revert.html
VSTS ticketId: 607746_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎5‎/‎29‎/‎2018, 02:36 AM (5 hours ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to change any of these VB scenarios.
