### ISSUE TITLE
Remove ReflectionEmitter

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#2721]
Related internal bug: 949559

**Comment by amcasey** [comment]
Please unskip ````Microsoft.CodeAnalysis.Scripting.CSharp.Test.InteractiveSessionTests.PrivateImplementationDetailsType``` when this is fixed.

**Comment by KevinH-MS** [comment]
@tmat is this fixed with fe902e14951c946a891d1ea413af6df5666160e9?

**Comment by tmat** [comment]
Yes.

**Comment by amcasey** [comment]
Unskipped test in a0b4cc7.

@tmat, please verify.
