### ISSUE TITLE
IDE0016 should not be dimming the text as that indicates the code is unused. 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27213]
I dont want to turn the inspection off, but it needs to have some other style of annotating the code. 

Also, the recommended action for these combines the property set with an exception throw, and that can makes the text harder to read by either causing line breaks to be added or makes for more scrolling.

I'm not sure if I want this feature at all or not. Its useful when its in a constructor and it can be used for something like

```csharp
_privateField = constructorParam ?? throw new ArgumentNullException(nameof(constructorParam)); 
```

but not for general use in a class where it wants to do take this... 

```csharp
var someObject = new Thing();
var thingCandidateField = _controller.GetStuff(SomeOtherObject.SearchField);
if (thingCandidateField == null)
{
   throw new InvalidOperationException($"Cant make a new thing. The paramter {nameof(SomeOtherObject.SearchField)} had value {SomeOtherObject.SearchField} that returned no results.");
}
someObject.Prop1 = thingCandidateField;
```

and make this...

```csharp
var someObject = new Thing();
var thingCandidateField = _controller.GetStuff(SomeOtherObject.SearchField);
someObject.Prop1 = thingCandidateField ?? throw new InvalidOperationException($"Cant make a new thing. The parameter {nameof(SomeOtherObject.SearchField)} had value {SomeOtherObject.SearchField} that returned no results.");
```

Sorry about the formatting if its bad.  That last statement should be one long single line. This feedback tool is still very hard to use when sharing code.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/256320/ide0016-should-not-be-dimming-the-text-as-that-ind.html
VSTS ticketId: 618902_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
Design review conclusion: fading was used for unnecessary code and also for discoverability, but we believe the noise from this mixed usage has become problematic. Fading should only be used for cases where deleting the faded code will not break the code. This diagnostic should be updated to not fade code, other diagnostics will be evaluated against this rule as needed.

**Comment by jinujoseph** [comment]
reported [here ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/951111)too
