### ISSUE TITLE
Incorrect "Cast is redundant"

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#27239]
``` c#
using System;
public class C
{
    public static void Main()
    {
        object o = null;
        TypedReference r2 = (TypedReference)o;
    }
}
```

![image](https://user-images.githubusercontent.com/3804346/40693540-b91a4ea6-636c-11e8-901b-81838e9b4f39.png)

**Comment by davidwengier** [comment]
I've got a fix for this that prevents this code fix applying where no casts are valid. Will open a PR soon.
