### ISSUE TITLE
Analyze local functions in `NullableWalker`

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#27233]
```c#
class Program
{
    static void F(object? x)
    {
        object y;
        object z;
        f();
        if (x == null) return;
        g();
        y.ToString(); // warning: y may be null
        z.ToString(); // warning?

        void f() => y = x; // warning: x may be null
        void g() => z = x; // warning?
    }
}
```
See [LDM-2018-06-04](https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-06-04.md#local-functions)

**Comment by jcouv** [comment]
From discussion in email and from latest LDM notes, it sounds like we're not sure whether this is doable. Assigned to @agocke, assuming he's the best person to investigate.

**Comment by jcouv** [comment]
FYI, moved to Compiler.Next milestone

**Comment by jcouv** [comment]
@agocke Can this issue be closed?

**Comment by agocke** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/40422
