### ISSUE TITLE
"Add parameter to constructor" ignores successive calls

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#27255]
**Version Used**: 
15.7.2

**Steps to Reproduce**:
In two different files:
```cs
// Foo.cs
public class Foo
{
    public Foo()
    {
    }
}
// Bar.cs
public class Bar
{
    public void Test()
    {
        int t1 = 1, t2 = 2, t3 = 3, t4 = 4, t5 = 5;
        var foo = new Foo(t1, t2, t3, t4, t5); // run here
    }
}
```
quickly run the "Add parameter to Foo()" code five times (for five parameters).

**Expected Behavior**:

Foo's constructor should gain five parameters for five calls.

**Actual Behavior**:

Foo's constructor only got one parameter.

**Notes**
It's important that the code is split into two files. If `Foo` is in the same file as the constructor call, the five calls result in five added parameters.

You have to be "fast enough". If you wait between the successive calls to the code fix, the five calls might result in (up to) five parameters, so this likely depends on the project size as well.

![add-parameter-to-foo](https://user-images.githubusercontent.com/1947968/40729665-2bf5ecd0-642d-11e8-85f4-f2882f7cf752.gif)

**Comment by CyrusNajmabadi** [comment]
Does not repro for me.  I get:

![image](https://user-images.githubusercontent.com/4564579/217946804-c525e3e2-8d5b-49bd-ad61-fb8a82234615.png)
