### ISSUE TITLE
Add editor config option to specify where usings should go by default

### ISSUE THREAD

**Issue by GeertvanHorrik** [dotnet/roslyn#27288]
Some people prefer usings inside namespaces. VS respects the location once it has been set, but there is no way to specify the initial behavior.

I foresee 2 options:

* Outside namespace (default)
* Inside namespace

Pinging @AArnott and @davkean FYI

I am happy to give it a spin and implement this, but might need some pointers once I start this.

**Comment by sharwell** [comment]
@vweijsters has built a rather impressive code fix for this setting that we may be able to leverage.

**Comment by GeertvanHorrik** [comment]
Comment from @AArnott on twitter:

"I suspect both of these can be specified via .editorconfig. Getting roslyn to honor it sounds interesting. I wish I could hope item templates would somehow honor them"

Maybe it's possible to apply code formatting (CTRL K, CTRL + D) after creating a template. Then only 2 things are needed to get a zillion birds with 2 stones:

1. somehow get the logic created by @vweijsters into Roslyn
2. post-run the code format logic after creating a template

**Comment by Pilchie** [comment]
VS already [formats](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/AbstractEditorFactory.cs,23c02d149880b615) new files from templates according to the current formatting settings, and there is work going on somewhere (@JieCarolHu?) to have that incorporate other code style items.  So, someday when our code cleanup story is a little more developed, I would expect this to work for templates.

**Comment by Dreamescaper** [comment]
Considering that corresponding option is added in 16.1.P3, probably this one should be closed.

**Comment by davkean** [comment]
@sharwell @jinujoseph Can we close this if this has been fixed?

**Comment by mavasani** [comment]
Tagging @JoeRobich

**Comment by jinujoseph** [comment]
This should be fixed via https://github.com/dotnet/roslyn/pull/35009 
and should be available in 16.1.Preview3 onwards.
