### ISSUE TITLE
Unhelpful warning when an analyzer could not be loaded because another version of analyzer was loaded for a different project

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2728]
1. Create a C# diagnostic + code fix project (I have "Analyzer5" for this repro) and build solution.

2. In a new VS instance, create another C# diagnostic + code fix project (I have "Analyzer6" for this repro).

3. Rename the output assembly name and default namespace for Analyzer6 project to "Analyzer5" through project property pages. Build solution.

4. In a new VS instance, create a new solution with 2 C# projects, Classlibrary1.csproj and Classlibrary2.csproj

5. Add nuget package "Analyzer5.1.0.0.0.nupkg" to Classlibrary1.csproj to add the analyzer created in step (1).

6. Add nuget package "Analyzer6.1.0.0.0.nupkg" to Classlibrary2.csproj to add the analyzer created in step (3).

**Actual**: Following diagnostics show in the error list.

```
Severity	Code	Description	Project	File	Line
Warning	Analyzer5	Type name 'Class1' contains lowercase letters	ClassLibrary1	C:\Users\mavasani\Documents\Visual Studio 2015\Projects\ClassLibrary2\ClassLibrary1\Class1.cs	8

Warning	CS8032	An instance of analyzer Analyzer5.Analyzer6Analyzer cannot be created from C:\Users\mavasani\Documents\Visual Studio 2015\Projects\ClassLibrary2\packages\Analyzer6.1.0.0.0\tools\analyzers\Analyzer5.dll: Value cannot be null.
Parameter name: type.	ClassLibrary2		1

```

**Expected:**
Given that both the nuget packages have an analyzer with the same name, but different content, it is expected that only one copy of Analyzer5.dll gets loaded in VS and hence analyzer for only one of the projects runs fine. However, the CS8032 generated for Classlibrary2 is not too helpful as it does not indicate anything about the core issue: _"projects have analyzer references to assemblies with same assembly identity but different contents"_

Note that an informative and helpful `AnalyzerDependencyConflict` diagnostic **does** indeed show up if the same mismatch occurs for an analyzer dependency:

```
Severity	Code	Description	Project	File	Line
Warning	AnalyzerDependencyConflict	Assembly 'C:\Users\mavasani\Documents\Visual Studio 2015\Projects\ClassLibrary2\packages\Analyzer5.1.0.0.0\tools\analyzers\AnalyzerDependency_2.dll' used by analyzer 'AnalyzerDependency_1' and assembly 'C:\Users\mavasani\Documents\Visual Studio 2015\Projects\ClassLibrary2\packages\Analyzer6.1.0.0.0\tools\analyzers\AnalyzerDependency_2.dll' used by analyzer 'AnalyzerDependency_1' have the same identity but different contents. These analyzers may not run correctly.	ClassLibrary1		1
```

We should probably have such a diagnostic for the core analyzer assembly conflict as well.

**Comment by tmeschter** [comment]
@mavasani Yeah, when we were using the `InMemoryAssemblyLoader` you could actually load two different analyzer assemblies with the same identity (but not their dependencies) so we didn't check for this conflict. I'm updating `AnalyzerDependencyChecker` to cover this case as well.

**Comment by tmeschter** [comment]
@mavasani Assigning back to you for verification.

**Comment by mavasani** [comment]
@srivatsn @tmeschter The above repro steps still give me the same 2 warnings mentioned in the repro steps:

```
Severity	Code	Description	Project	File	Line	Build tool

Warning	Analyzer1	Type name 'Class1' contains lowercase letters	ClassLibrary1	c:\users\mavasani\documents\visual studio 2015\Projects\ClassLibrary1\ClassLibrary1\Class1.cs	9	Analyzer1

Warning	CS8032	An instance of analyzer Analyzer2.Analyzer2Analyzer cannot be created from c:\users\mavasani\documents\visual studio 2015\Projects\ClassLibrary1\packages\Analyzer2.1.0.5644.25720\analyzers\portable50\cs\Analyzer1.dll: Could not load type 'Analyzer2.Analyzer2Analyzer' from assembly 'Analyzer1, Version=1.0.5644.25613, Culture=neutral, PublicKeyToken=null'..	ClassLibrary2		1	
```

I don't see any assembly conflict diagnostic, just the one that says couldn't load the analyzer type from the pre-loaded conflicting assembly.

**Comment by mavasani** [comment]
Probably the 2nd diagnostic is good enough, and we can resolve this as by design, but I thought I should let you know about the current behavior.

**Comment by tmeschter** [comment]
@mavasani This really should have turned up an issue. Can you make the analyzer NuGet packages you tested with available to me?

**Comment by tmeschter** [comment]
@mavasani Ah, I see the problem. The analyzer assemblies have the same name but different assembly versions. This is enough to convince the `AnalyzerDependencyChecker` that these assemblies won't conflict. However, as neither is strong-name signed the CLR will ignore the version, resolve them based on the name alone, and only load one.

Later we get an error when we try to find Analyzer2 in the assembly and we're unable to do so.

The `AnalyzerDependencyChecker` should be taking into account whether or not the assembly is strong-name signed; I'll file a new issue about that.

**Comment by mavasani** [comment]
Marking this as verified, as we have a new issue tracking the bug: #3562
