### ISSUE TITLE
Improve undo stack titles for ApplyChangesOperations

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#273]
Ported from TFS WorkItem: <b>1090420</b>

------------------------------

<p><b>Repro Steps:</b></p>
Currently, the application of CodeActions that consist of ApplyChangesOperations (so, almost all of them) show in the undo stack as "Text Buffer Change", but it would be nice if it had the fix description there (or some other shorter&nbsp;string provided via some new API for this purpose, but that might be overkill).</P>

**Comment by dpoeschl** [comment]
This is fantastic. Thanks!
