### ISSUE TITLE
Question over section of a function.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#27310]
As part of the research of #27240 
I've found a method that is proving difficult to convert to being an iterator, due the section required to look back at previous value.  [KeywordHighlightingHelpers](https://github.com/dotnet/roslyn/blob/6847f1e5a909395aae9456e8f366cbf4deb86b69/src/EditorFeatures/VisualBasic/Highlighting/KeywordHighlightingHelpers.vb#L79)
Is it needed as it what is doing seems to go against the function's name, highlighting the extended section, between to `await`s, rather that the individual `await` keywords.

**Comment by gafter** [comment]
@AdamSpeight2008 Have you investigated to try to answer the question yourself?

**Comment by AdamSpeight2008** [comment]
@gafter I have.
```
TestMethod_Async_NestedAwaits1
TestMethod_Async_NestedAwaits2
TestMethod_Async_NestedAwaits3

TestMultilineLambda_AsyncExample2_1
TestMultilineLambda_AsyncExample2_2
TestMultiLineLambda_AsyncExample2_3
```
All fail because it is expecting the combine textspan rather than two separate textspans.
The problem starts at [this line](https://github.com/dotnet/roslyn/blob/d4d6f718ff761e4af96925d35793ad6c601de69f/src/EditorFeatures/TestUtilities/KeywordHighlighting/AbstractKeywordHighlighterTests.cs#L40), `testDocument.SelectedSpans` doesn't return the incorrect spans (ie the extended section textspans).

**Comment by AdamSpeight2008** [comment]
Fixed the tests. would have helped if there was some information on the syntax used with the tests.
for example `{|  |}` `[|  |]`

**Comment by CyrusNajmabadi** [comment]
There is.  I documented it in https://github.com/dotnet/roslyn/blob/1e8ba786a9e9895cf06e197f1bf3bac62eaf3053/src/Test/Utilities/Portable/MarkedSource/MarkupTestFile.cs#L16-L36
