### ISSUE TITLE
Adding .editorconfig breaks zoom in Visual Studio editor

### ISSUE THREAD

**Issue by v-rodudi** [dotnet/roslyn#27324]
**Version Used**: Visual Studio 15.8.0 Preview 2.0 [27729.1.d15.8]

**Steps to Reproduce**:

1. Create new project (for example Console App (.NET Framework) C#)
2. Add .editorconfig file to project
3. Close .editorconfig file
4. Open Class1
5. Try to zoom in/out using CTRL + mouse scroll

**Expected Behavior**: zoom changed

**Actual Behavior**: error dialog appeared
![zoom-error](https://user-images.githubusercontent.com/38646068/40840955-7135bc32-65b1-11e8-8c15-350e9e0acb24.PNG)
[**ActivityLog.xml**](https://microsoft-my.sharepoint.com/:u:/p/v-rodudi/EYT5O5nxFjNCqr5tMOeIFtMBPgfjo3Pt5DUygoC4H-nGPg?e=w3qlX7)

6. Close dialog
7. Try to change zoom using drop down in the bottom left corner

**Expected:** zoom changed
**Actual:** VS hangs and then restarts

**Note:** also reproduced on existing projects with .editorconfig file

[Repro Gif](https://microsoft-my.sharepoint.com/:i:/p/v-rodudi/EeIqG3kL1eRPt0ng_eieYtIBIR50igwPQLKNpi4-XSE2_Q?e=lqPEwj)

**Comment by v-rodudi** [comment]
JFYI: ticket author @v-rodudi won't be available after 9/4 so please ask repro-related questions before this date if they are.

**Comment by CyrusNajmabadi** [comment]
I do not repro this.  Zooming works fine.
