### ISSUE TITLE
'IDE0001 Name can be simplified' running when it shouldn't

### ISSUE THREAD

**Issue by GeertvanHorrik** [dotnet/roslyn#27320]
**Version Used**: 

VS2017 15.8 preview 2

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/1246444/40833105-3c992ece-658d-11e8-83a0-8382298d4963.png)

**Expected Behavior**:

Either not run or move 'UpdateHelper.GetUpdateSystemPaths(product)' as replacement.

**Actual Behavior**:

Suggests 'var' as replacement

**Comment by Neme12** [comment]
duplicate of #27210

**Comment by GeertvanHorrik** [comment]
Thanks!
