### ISSUE TITLE
Add public API for "BlockStructure"

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#27332]
The current BlockStructure API is internal, which means we have to write ugly reflection code to consume it in OmniSharp. Please consider creating a public version so that consumers of Roslyn can use its outlining functionality. cc @DustinCampbell 
In reference to: https://github.com/OmniSharp/omnisharp-roslyn/pull/1209 and https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/Structure/BlockStructureService.cs

**Comment by CyrusNajmabadi** [comment]
Note: current BlocKStructure API is currently insufficient for VS itself.  VS has asked for Roslyn to include more info.  So we should probably kill two birds with one stone.

**Comment by DustinCampbell** [comment]
@CyrusNajmabadi : What additional info was requested?

**Comment by CyrusNajmabadi** [comment]
i think it was @AmadeusW who was asking for it (but i could be wrong) :-).  Essentially, the thought from the VS side is that we're not including enough information to exactly know where to place the dotted line for a block-span.

I'm skeptical myself about this.  My feeling is that "taking the leftmost (in view coordinates) of the start/end points" is a sufficient and appropriate algorithm here.  However, before making anything public we should be confident we have the right API that both Roslyn and the Editor feels is sufficient.

Thanks! :)

**Comment by AmadeusW** [comment]
I think it was @gundermanc who asked for it. He uses these APIs extensively for various refactorings, and he'll be able to explain better the scenarios that would benefit from the API.

**Comment by CyrusNajmabadi** [comment]
We would do this through lsp.  closing out.
