### ISSUE TITLE
Analyzing an analyzer project with itself

### ISSUE THREAD

**Issue by mnivet** [dotnet/roslyn#27339]
We have an analyzer project that was developed against Microsoft.CodeAnalysis.CSharp.Workspaces 1.3.2 and targetting portable framework profile 7

We try to migrate it to VS2017 / Microsoft.CodeAnalysis.CSharp.Workspaces 2.8.2 / netstandard 1.3 like it is done in recent versions of the visual studio template to create analyzer projects

Migration seems OK except for one point: we were used to analyze the code of the analyzer with itself, and it was not a problem at all with classic csproj format and the packages.config way to reference nuget packages

But now we have that error:
NU1108 Cycle detected
TalentSoft.Analyzers -> TalentSoft-CodingRules-Settings 2.4.1 -> TalentSoft.Analyzers (>= 1.3.1 && < 2.0.0).	TalentSoft.Analyzers

The reference to our coding rules package is done like that:
```
<PackageReference Include="TalentSoft-CodingRules-Settings" Version="2.4.1" PrivateAssets="All" />
```

I've even done it like that:
```
<PackageReference Include="TalentSoft-CodingRules-Settings" Version="2.4.1" PrivateAssets="All" ExcludeAssets="compile;runtime;contentFiles;native" />
```

But I'm still unable to go through that 'cycle detected' error.

Any idea on how we can achieve the expected behaviour ?

**Comment by jmarolf** [comment]
@mnivet see https://github.com/NuGet/Home/issues/6754

**Comment by mnivet** [comment]
Exactly my issue, thanks for the link.
