### ISSUE TITLE
Provide more statically typed usage of IInternalOptionSet

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#27355]
Moving OptionSet to the compiler caused a number of static checks to be dynamic. We should try to switch over as many places as possible to use an internal OptionSet instead of using dynamic checks.

**Comment by gafter** [comment]
See https://github.com/dotnet/roslyn/pull/27263 for the "Moving" referred to here.

**Comment by jasonmalinowski** [comment]
Closing this -- the change that caused problems was ultimately rolled back.
