### ISSUE TITLE
move CodeFixService to Features

### ISSUE THREAD

**Issue by JieCarolHu** [dotnet/roslyn#27369]
CodeFixService is under EditorFeatures right now, it has a dependency to `ForegroundTaskScheduler`. 

Need to investigate why it is needed. If we can remove the dependency, we will move it under Features

```csharp
  // Have to see if this fix is still applicable.  Jump to the foreground thread
                    // to make that check.
                    var applicable = await Task.Factory.StartNew(() =>
                        {
                            this.AssertIsForeground();
                            return fix.Action.IsApplicable(document.Project.Solution.Workspace);
                        },
                        cancellationToken, TaskCreationOptions.None, ForegroundTaskScheduler).ConfigureAwait(false);
                    this.AssertIsBackground();
```

**Comment by CyrusNajmabadi** [comment]
> Need to investigate why it is needed. If we can remove the dependency, we will move it under Features

I don't think this dependency can be removed.  Or, i don't know of a good way for that to happen.  Tagging @jasonmalinowski to see if he has any ideas.

Effectively, we have an escape hatch for some analyzers that have code that **must** run on the UI thread (and must get the Workspace to make a decision).  To do this, the analyzer does all the work it can on the background, decides it it should show based on everything it knows so far.  Then, later on in the CodeFixService we actually call back into it with a Workspace (and on the UI thread) so it can make a final determination.

**Comment by jasonmalinowski** [comment]
What analyzers use that?

**Comment by jasonmalinowski** [comment]
OK, just wanted to sanity-check what was still using this.

In any case, does standard dependency injection patterns solve this for now? Create a ICodeFixForegroundThreadScheduler that is queried to get that? or something else?

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski yup.  taht could probably do it.   if we can't find such a service, then we'd probably want to consider all those CodeActions inapplicable.

**Comment by sharwell** [comment]
Marking as indefinitely **blocked**. The code fix service calls `CodeAction.IsApplicable`, which has a precondition that it can only be called on the UI thread. One of the following must occur before this change can move forward:

1. Remove the need to call `CodeAction.IsApplicable`
2. Make `CodeAction.IsApplicable` asynchronous
3. Update `CodeAction.IsApplicable` to disallow the use of the UI thread in implementations

**Comment by CyrusNajmabadi** [comment]
> 1. Remove the need to call CodeAction.IsApplicable

This would be ideal. There's only four cases that i know of, and it really feels like we could work with the related teals to get free-threaded ways to ask the questions we currently need to ask on the UI thread.

> 2. Make CodeAction.IsApplicable asynchronous

This is potentially possible.  Though we still have the issue that this is called from a synchronous editor entrypoint (namely ISuggestedActionSource.GetSuggestedActions).  There were talks a while back about making this asynchronous, but they seem to have fizzled out.

> 3. Update CodeAction.IsApplicable to disallow the use of the UI thread in implementations

Thta would somewhat defeat the purpose.  It exists entirely to allow that :D
