### ISSUE TITLE
Investigate possible crash in parentheses analyzer

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#27377]
**Version Used**: e3dcf8c76dc2c228f61b9de8af92f1ec0275f5f8

Reported to me earlier in the day but I didn't get a chance to investigate it yet.

**Steps to Reproduce**:

i try to wrap parens around
```if (lat.Length > 0 && lon.length > 0)```
and then second I do this:
```if ((lat.Length > 0 && lon.length > 0)```
VS crashes

**Comment by jinujoseph** [comment]
@vsccarl  validated in latest 15.8 and not reproing
