### ISSUE TITLE
Hover over ending brace showing empty textbox

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27387]
In C#, when hovering over a end brace to an if statement, no information is present in the textbox 

![image](https://user-images.githubusercontent.com/12449387/40881680-bdfbf506-6681-11e8-8198-16d97f35d550.png)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/263297/hover-over-ending-brace-showing-empty-textbox.html
VSTS ticketId: 623832_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
closing this in favor of https://github.com/dotnet/roslyn/issues/27422
