### ISSUE TITLE
VS2017 can not hit the breakpoint

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#27390]
**Version Used**: VS2017 15.7.3

**Steps to Reproduce**:

1. Uncheck "Enable Just My Code"
2. 
```
        static void Main(string[] args)
        {
            Console.WriteLine();
        }
```
3. Add a function breakpoint "WriteLine"
4.Debug the program

**Expected Behavior**: break in Console.WriteLine

**Actual Behavior**: nothing

**Comment by jcouv** [comment]
Tagging @cston to help route this

**Comment by cston** [comment]
@CreateAndInject, are symbols loaded for the assembly containing `Console.WriteLine`? Function breakpoint binding ignores modules without symbols.

**Comment by CreateAndInject** [comment]
Yes, there's no mscorlib.pdb, but I checked Enable address-level debugging &  Show disassembly ifsource is not avaible

**Comment by CreateAndInject** [comment]
I think Function breakpoint binding should not ignore it if checked Enable address-level debugging & Show disassembly if source is not avaible.
Although there's no source, I can know whether hint a method, and get the local variables.

**Comment by cston** [comment]
cc @jinujoseph

**Comment by ivanbasov** [comment]
Tried to reproduce the issue with the current version of VS (2019 Preivew 2):
1. Disabled the "Enable Just My Code"
2. Used the code
3. Added a funcitonal breakpoint for "WriteLine"
4. hit F5
5. Debugger asked for source code for console.cs.
6. I do not have the source code for this specific version. 
7. The view disassemble option stopped at a breakpoint at the following line:

```
--- f:\dd\ndp\clr\src\BCL\system\console.cs ------------------------------------
7210680C  push        ebp  
```

It seems the function is working properly.
Resolving the issue. Please let me know if there is anything more to review.
