### ISSUE TITLE
Incorrect text inserted from IntelliCode suggestions in Quick Watch screen

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#27395]
**Version Used**: Visual Studio 15.7.3, IntelliCode: 1.0.43.63853

**Steps to Reproduce**:

1. Open the Quick Watch screen
2. Start typing to induce IntelliSense
3. Select a member from IntelliCode (with a star)

**Expected Behavior**:

Highlighted member is inserted and works

**Actual Behavior**:

Highlighted member is inserted with the star, resulting in a syntax error

![intellicode_bug](https://user-images.githubusercontent.com/754264/40894549-d6efc4d0-67ed-11e8-9997-e06986b39e85.gif)

**Comment by davidwengier** [comment]
Apologies if this is not the right repo for this issue. If there is somewhere better to report this please let me know.

**Comment by CyrusNajmabadi** [comment]
This is the right repo.  Tagging @jinujoseph and @dpoeschl .  Note, this may be fixed with: https://github.com/dotnet/roslyn/pull/26764

**Comment by jinujoseph** [comment]
Yes this is already resolved via [link](https://github.com/dotnet/roslyn/pull/26341)

**Comment by dpoeschl** [comment]
@davidwengier If my understanding of this issue is correct, it should be fixed after you run any completion session in the normal editor window. Can you try running completion in the normal editor window, confirm it doesn't repro there, and then go back to the quick watch screen and try again there?

**Comment by dpoeschl** [comment]
This should have been resolved by https://github.com/dotnet/roslyn/pull/26361

**Comment by davidwengier** [comment]
Confirmed, it doesn't repro after completion shows in the normal editor window.
