### ISSUE TITLE
Possible Redundant method?

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#274]
Since `ImmutableArray<T>` implements `IEnumerable<T>` 
[this method](
https://github.com/dotnet/roslyn/blob/cfdd6068c7e8b63c5ad1e71eaddda61962b51b9a/src/Compilers/Core/Portable/InternalUtilities/Hash.cs#L69)
is needed as it covered by [this method](https://github.com/dotnet/roslyn/blob/cfdd6068c7e8b63c5ad1e71eaddda61962b51b9a/src/Compilers/Core/Portable/InternalUtilities/Hash.cs#L43).

Reason the `foreach` that is being used in it implementation matches against the .`.GetEnumerator` method.

**Comment by mikedn** [comment]
ImmutableArray is a struct, if you pass it to the IEnumerable overload it will get boxed, that's one wasted memory allocation.

**Comment by AdamSpeight2008** [comment]
Even if the method signature was?
```c#
  internal static int CombineValues<T>(T values, int maxItemsToHash = int.MaxValue) 
    where T : IEnumerable<T>    
```

**Comment by mikedn** [comment]
Yes. In that case the generic code only knows about `IEnumerable<T>.GetEnumerator()` and it will call that instead of calling `ImmutableArray<T>.GetEnumerator()`. The result is a boxed `ImmutableArray<T>.Enumerator`.

**Comment by AdamSpeight2008** [comment]
According to [this](http://stackoverflow.com/questions/5531948/how-does-a-generic-constraint-prevent-boxing-of-a-value-type-with-an-implicitly) StackOverflow question it isn't boxed.

**Comment by svick** [comment]
@AdamSpeight2008 As @mikedn said, the `ImmutableArray<T>` isn't boxed, but the enumerator is.

When you use `where T : IEnumerable<T>`, that means only methods from `IEnumerable<T>` can be called. And that means the `IEnumerator<T>`-returning `IEnumerable<T>.GetEnumerator()` will be called instead of the `ImmutableArray<T>.Enumerator`-returning `ImmutableArray<T>.GetEnumerator()`.

Maybe code will make it clearer: http://ideone.com/GmYkMV.

**Comment by pharring** [comment]
Right. That's why you'll see overloads taking ImmutableArray<T> all over the Roslyn code base. We're careful to avoid boxing when we can.

**Comment by AdamSpeight2008** [comment]
On what order is boxing slower? x20?
If it could be improved what would be acceptable? x3? x2? x1?

**Comment by mikedn** [comment]
Boxing itself is quite cheap. It's the cost of additional GCs potentially triggered by allocations that matters. And the exact cost depends on the application, you can't assign a definite number to it.

It's also worth mentioning that by avoiding boxing `ImmutableArray<T>` you also avoid interface calls. They're relatively expensive, especially in cases where the enumerator methods are trivial and can be inlined.
