### ISSUE TITLE
Editor Completion: Store the document being used so we don't get out of sync documents

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27417]
// TODO

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Is this still relevant?

**Comment by CyrusNajmabadi** [comment]
Not actionable.
