### ISSUE TITLE
Editor Completion: Confirm that asynchronous work correctly conforms to VS threading rules

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27418]
// TODO

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
@AmadeusW , currently sending an empty description leads to a failure like 

`"   at Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Data.SuggestionItemOptions..ctor(String displayTextWhenEmpty, String toolTipText)\r\n   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.EditorImplementation.CompletionItemSource.<GetCompletionContextAsync>d__5.MoveNext() in C:\\git\\ivanbasov\\roslyn\\src\\EditorFeatures\\Core\\Implementation\\IntelliSense\\EditorCompletionImplementation\\CompletionItemSource.cs:line 69\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.<CallExtensionPointAsync>d__33`1.MoveNext()"`

Please help with a solution or a workaround.

**Comment by ivanbasov** [comment]
@AmadeusW please review GetCompletionContextAsync in https://github.com/dotnet/roslyn/pull/28219 regarding " VS threading requirements". Thank you!

**Comment by AmadeusW** [comment]
Investigating this, I noticed that sometimes the work is performed on a thread other than high priority completion thread. It looks like Roslyn is using `ConfigureAwait(false)` which opts out of the current scheduler.

**Comment by ivanbasov** [comment]
Per discussion with @sharwell , the implementation is correct and correspond to VS threading requirements. If we meet performance issues, we consider them on demand.
