### ISSUE TITLE
Editor Completion: Do external providers need to implement IFeaturesCustomCommitCompletionProvider? [Definitely Pythia]

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27429]
// TODO

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
All providers required to implement this by unit tests coverage already implement it. If other our or external providers need to do so, this can be done on demand per each separately.

**Comment by ivanbasov** [comment]
We removed IFeaturesCustomCommitCompletionProvider
