### ISSUE TITLE
Empty '}' tooltip (15.8 regression)

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#27422]
**Version Used**: 
15.8 Internal Preview 2.0 (dogfooding build)
![image](https://user-images.githubusercontent.com/5387680/40936294-bec78c56-67ef-11e8-86c7-9b596bd320d5.png)

**Steps to Reproduce**:

1. Create a C# project
2. Hover mouse cursor over any closing brace '}'

**Expected Behavior**:
Tooltip with start of 'block'.

**Actual Behavior**:
Empty tooltip

![image](https://user-images.githubusercontent.com/5387680/40936389-0a799536-67f0-11e8-99a6-401fd499601e.png)

Works fine in 15.7.1 so this is a 15.8 regression.

*cc:* @JieCarolHu. Could this be related to 15.8 Quick Info API changes?

**Comment by JieCarolHu** [comment]
I happen to have an older build(27726) and it works fine, so I don't think it is related with the quick info api work which was merged on Apr 24, @jinujoseph do we have a way to check the build date/commit related with build#? 

![image](https://user-images.githubusercontent.com/17056651/40936921-d3e71550-67f1-11e8-984b-d3a2bf548c38.png)

![image](https://user-images.githubusercontent.com/17056651/40936938-e1807a94-67f1-11e8-8784-3f9f4f098ee1.png)

**Comment by Neme12** [comment]
I can repro this on the public preview 2.0

**Comment by Neme12** [comment]
But interestingly, it does not repro on the latest master branch (deployed to preview 2), it works correctly.

**Comment by jinujoseph** [comment]
This does repro with latest dogfood build 278010.1

**Comment by jinujoseph** [comment]
also reported here https://github.com/dotnet/roslyn/issues/27387

**Comment by gundermanc** [comment]
Took at look at this under the debugger and _Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.QuickInfoSourceProvider.QuickInfoSource_ is giving us an empty container element for content, hence the empty tooltip.

**Comment by JieCarolHu** [comment]
pretty weird, I CANNOT repro it on the latest 27806 but it seems both @gundermanc and @jinujoseph can repro it...  Could this relate with any kind of user setting?

**Comment by gundermanc** [comment]
I generally run uncustomized with no extensions. I'd be happy to share a repro. Perhaps it's already fixed?

**Comment by davkean** [comment]
I can repro this on Version 15.8.0 Preview 3.0 [27807.3004.d15.8stg].

**Comment by Neme12** [comment]
> But interestingly, it does not repro on the latest master branch (deployed to preview 2), it looks like this was fixed?

My bad, this regression only exists in `master-vs-deps`, not `master`.

**Comment by davkean** [comment]
@JieCarolHu Can you point to the fix?

**Comment by jinujoseph** [comment]
fixed via https://github.com/dotnet/roslyn/pull/27818
