### ISSUE TITLE
Editor Completion: We have to implement IExperimentationServiceInternal

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27428]
For test purposes.

**Comment by ivanbasov** [comment]
Could not find any reference on IExperimentationSerivceInternal. It seems to be something obsolete.

**Comment by AmadeusW** [comment]
No, it's not obsolete. It's a MEF part provided by Shell, and we're using it specifically for A\B needs of Roslyn. Here's something you can insert into your integration tests to satisfy the import

```
using System.ComponentModel.Composition;
using Microsoft.VisualStudio.Text.Utilities;
    [Export(typeof(IExperimentationServiceInternal))]
    class MockExperimentationService : IExperimentationServiceInternal
    {
        public bool IsCachedFlightEnabled(string flightName) => true;
    }
```

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Is this still relevant?
