### ISSUE TITLE
Editor Completion: Consume the rest of the completion options

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27427]
| Option | User Editable | Used by 3rd parties as visible from //index | Used in Old Completion (sanity) | Handled in Async Completion  | Notes | Estimate if workrequired |
|---|---|---|---|---|---|---|
| EditorCompletionOptions.UseSuggestionMode | Not via Options | ? Microsoft.Ide.Roslyn ? | ✔️ | ✔️ | "Intentionally Not Persisted" |
| EditorCompletionOptions.UseSuggestionMode_Debugger | Not via Options | No | ✔️ | ❓ **Unknown** | Also not persisted, used to keep the setting distinct between regular & debugging | ❓ in the original code, I found only setting the option but not using it. I even found this code in the new completion. It seems there is nothing to do on the Roslyn side. Need to verify with the editor team |
|---|---|---|---|---|---|---|
| CompletionControllerOptions.FilterOutOfScopeLocals | No | No | ✔️ | ✔️ | For debugger scenarios | Implemented on the provider & recomendationService layers | 
| CompletionControllerOptions.ShowXmlDocCommentCompletion | No | No | ✔️ | ✔️  | For debugger scenarios |  Implemented on the provider layer | 
|---|---|---|---|---|---|---|
| CompletionOptions.HideAdvancedMembers | Yes (General) | No | ✔️ | ✔️ (Roslyn-only) | "serialized by the Visual Studio-specific LanguageSettingsPersister" && used for non-completion features too |
| CompletionOptions.TriggerOnTyping | Yes (General) | No | ✔️ |  ✔️ | Was controller layer && "serialized by the Visual Studio-specific LanguageSettingsPersister" | Actually, not controller but provider layer. Working properly |
| CompletionOptions.TriggerOnTypingLetters | Yes (IntelliSense) | Yes (TS) | ✔️ | ✔️ | Was controller-layer ("on letters" as opposed to on `.`) | Actually, not controller but provider layer. Working properly |
| CompletionOptions.TriggerOnDeletion | Yes (IntelliSense) | No | ✔️ | ✔️ | Was controller-layer | Done. Called by CompletionSource|
| CompletionOptions.EnterKeyBehavior | Yes (IntelliSense) | Yes (via the corresponding CompletionItemRule) | ✔️ | ✔️ | |  CommitManager consumes SendEnterThroughToEditor from the original code which uses this option |
| CompletionOptions.SnippetsBehavior | Yes (IntelliSense) | No | ✔️ | ❕ **No** | Need to decide what to do here w.r.t. the options page. https://github.com/dotnet/roslyn/issues/27423 |
| CompletionOptions.ShowCompletionItemFilters | Yes (IntelliSense) | No | ✔️ | ✔️ | Was presentation-layer | Added |
| CompletionOptions.HighlightMatchingPortionsOfCompletionListItems | Yes (IntelliSense) | No | ✔️ | ✔️ | Was presentation-layer | Added |
| CompletionOptions.BlockForCompletionItems | No | Yes (TS) | ✔️ | ❗️ **No** (Editor-only impl) | https://github.com/dotnet/roslyn/issues/29112 | Amadeusz |
| CompletionOptions.ShowNameSuggestions | Yes (IntelliSense) | No | ✔️ | ✔️ (Roslyn-only) | |
|---|---|---|---|---|---|---|
| CompletionRules.DismissIfEmpty | No | No | ✔️ | ✔️ |  |
| CompletionRules.DismissIfLastCharacterDeleted | No | No | ✔️ | ✔️  |  |  |
| CompletionRules.DefaultCommitCharacters | No | ...Yes... (go look) | ✔️ | ✔️  |  | Shoud be fixed |
| CompletionRules.DefaultEnterKeyRule | See as `CompletionOptions.EnterKeyBehavior` for data |
| CompletionRules.SnippetsRule | See `CompletionOptions.SnippetsBehavior`  for data |
|---|---|---|---|---|---|---|
| CompletionItemRules.FilterCharacterRules | No | No | ✔️ | ✔️ | Done |  |
| CompletionItemRules.CommitCharacterRules | No | No | ✔️ | ✔️ |  |
| CompletionItemRules.EnterKeyRule | See `CompletionOptions.EnterKeyBehavior` for data |
| CompletionItemRules.FormatOnCommit | No | No | ✔️ | ❗️ **No** (Roslyn-only) |  #27449 | Medium-easy (code exists in `Controller.Commit` in old completion |
| CompletionItemRules.MatchPriority | No | Yes | ✔️ | ✔️ |  |
| CompletionItemRules.SelectionBehavior | No | No | ✔️ | ✔️ |  |

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Is this still relevant?

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
