### ISSUE TITLE
Editor Completion: Do we show an empty description box instead of no description?

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27420]
// TODO

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Is this still relevant?

**Comment by CyrusNajmabadi** [comment]
No clue what this is in reference to.  Closing out.
