### ISSUE TITLE
Editor Completion: Get automation names for ImageElements

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27430]
//TODO

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
@dpoeschl asked the editor team if they can support automation names for all partners or if each partner should provide our own automation name. Waiting for responses
FYI @AmadeusW

**Comment by AmadeusW** [comment]
Everyone who provides ImageElement should provide accessible description. 
Note that currently in completion this description is not spoken out. Completion items should have a great custom narration in the future. For now, we just need every image to have a text.

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Is this still relevant?

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
