### ISSUE TITLE
Editor Completion: "<see langword" completion shouldn't contain a null character

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27437]
**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
Blocked by #27450

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Is this still relevant?

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
