### ISSUE TITLE
EditorCompletion: Obey the DismissIfEmpty option

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27431]
// TODO

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Is this still relevant?

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
