### ISSUE TITLE
Editor Completion Test Failures: Projection Scenarios

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27446]
`*CaretNotMappableIntoSubjectBuffer`
`_Projections.Test*`

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
This one is blocked by supporting Backspace. All other issues seem to be resolved. A partial commit with enabling 5 out of 6 unit test has been done.

**Comment by ivanbasov** [comment]
@AmadeusW , TestProjections still not working. Please help to keep updates even the subject buffer is not connected.
```
       Dim editorOperations = state.GetService(Of IEditorOperationsFactoryService).GetEditorOperations(view)
	                editorOperations.Backspace()
	                editorOperations.InsertText("b")
	                Await state.WaitForAsynchronousOperationsAsync()
                Await state.AssertSelectedCompletionItem(displayText:="bbb", projectionsView:=view)
```

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Is this still relevant?

**Comment by CyrusNajmabadi** [comment]
These tests are all enabled, so closing out.
