### ISSUE TITLE
Editor Completion Test Failures: Backspace trigger/etc.

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27441]
`Backspace*`
`TestBackspace*`

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
@AmadeusW I tried simple scenarios like
1. Open 
```
using System;
class Program
{
    static void Main(string[] args)
    {
        if (Environment$$
    }
}
```
2. remove $$ and place the caret instead
3. click Backspace

**Expected**
Roslyn is called and decide if to support Backspace or not depending on 'Show completion list after a character is deleted'.

**Actual**
No call of Roslyn API found

**Comment by AmadeusW** [comment]
Use the Editor Nuget package `15.8.525+g60044f8b80.RR` or newer

**Comment by ivanbasov** [comment]
The only issue requires implementation of ICommandHandler<DeleteWordToLeft> on the editor side
