### ISSUE TITLE
Editor Completion Test Failures: Dismissing on commands

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27444]
I think this one is probably on the Editor to figure out.

`SelectAll/Snippets/SurroundWith`

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
@AmadeusW , please confirm that you already support SelectAll/Snippets/SurroundWith/Save and cover them with unit tests. Our action is to track this. No implementation on Roslyn side is required.

**Comment by AmadeusW** [comment]
I have added tests to VS-Platform that verify that completion dismisses upon the following user actions: Cut, Escape, InsertSnippet, Paste, Redo, Rename, Save, SelectAll, SurroundWith, Undo, WordDeleteToEnd, WordDeleteToStart

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Is this still relevant?

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
