### ISSUE TITLE
Editor Completion Test Failures: Soft/Hard Selection

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27447]
`TestCommitCharTypedAtTheBeginningOfTheFilterSpan` -- I think this one is on the editor.
Hard Selecting the Builder -- `TestIncompletedParenthesized*` -- Maybe also editor?

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
@dpoeschl is this still relevant?

**Comment by CyrusNajmabadi** [comment]
Cannot find these tets.  closing out.
