### ISSUE TITLE
Editor Completion Test Failures: TestLargeChangeBrokenUpIntoSmallTextChanges*

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27448]
// TODO

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
@dpoeschl is this still relevant?

**Comment by CyrusNajmabadi** [comment]
these tests are active.  closing out.
