### ISSUE TITLE
Editor Completion Test Failures: CharacterSetModificationRule

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27440]
AttributeNamed*Commit*

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Is this still relevant?

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
