### ISSUE TITLE
Editor Completion Test Failures: Enum Completion Triggers

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27445]
`EnumCompletionNotTriggered*`

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
Need `EditorCompletion.CommitBehavior.Cancel` which will appear in later versions on the editor

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Is this still relevant?

**Comment by CyrusNajmabadi** [comment]
These tests are all enabled, so closing this out.
