### ISSUE TITLE
Editor Completion Test Failures: Box Selection

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27442]
I think this one is probably on the Editor to figure out.

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by dpoeschl** [comment]
Determine what's done in 15.8, how new completion is handling it, and what we want to do.

**Comment by dpoeschl** [comment]
In P1 just to make sure nothing outrageous happens. Doesn't need exact parity yet.

**Comment by AmadeusW** [comment]
I don't have VS prior to 15.8, which already has multi caret support. Perhaps someone on Roslyn team has a 15.7 or earlier build.
Multi caret refactors forces completion to be disabled. I guess this means that "nothing outrageous happens" :)

**Comment by dpoeschl** [comment]
> Multi caret refactors forces completion to be disabled.
I'm sold for P1. Moving milestone.

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Is this still relevant?

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
