### ISSUE TITLE
Self-Reference in Collection Intialiser

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#2745]
Minimal Repo
```vb.net
Dim d As New Dictionary(Of String, Integer) From { {"a",1}, {"b",d("a")+1} }
```
Gives the warning.
`Variable 'd' is used before it has been assigned a value. A null reference exception could result at runtime.`

But according to [MSDN Documentation:Collection Initializers (Visual Basic)](https://msdn.microsoft.com/en-us/library/dd293617.aspx)

> **The Microsoft® Visual Basic® Language Specification (Version 11.0)**
>
> If the type being created is a collection type and has an instance method *Add* (including extension methods and shared methods), the the object-creation expression can specify a collection initializer prefixed by the keyword *From*. An object-creation expression cannot specify both a member initializer and a collection initializer. **Each element in the collection initializer is passed as an argument to an invocation of the Add function.** For example:
> ```vb.net
> Dim list = New List(of Integer)() From { 1, 2, 3, 4 }
> ```
> is equivelent to
> ```vb.net
> Dim list = New List(of Integer)()
> list.Add( 1 )
> list.Add( 2 )
> list.Add( 3 )
> list.Add( 4 )
>```

So according the language's specification the code I provided at the start, should be equivalent to
```vb.net
Dim d As New Dictionary(Of String, Integer)
d.Add( "a", 1)
d.Add( "b", d("a")+1)
```
This doesn't produce any compile or runtime errors. 
So this means the implementation of collection initializers is in disagreement with the specification.

**Comment by HaloFour** [comment]
I think the question there is when `d` is expected to be assigned the collection.  To my knowledge the collection initializer is to be treated as if it is initializing a temporary variable with the collection and not the final variable until the initialization is complete.  The equivalent code would then be:

```
Dim temp As New Dictionary(Of String, Integer)
temp.Add("a", 1)
temp.Add("b", d("a") + 1)
Dim d As Dictionary(Of String, Integer) = temp
```

**Comment by AdamSpeight2008** [comment]
That quoted section is taken straight out of the Visual Basic Language Specification.

**Comment by HaloFour** [comment]
Yes, but that section does not state that collection  instance is assigned to the variable prior to performing the collection initializer, only that an `Add` method is called on the created instance.

**Comment by AdamSpeight2008** [comment]
@HaloFour 
It also states that the following code example are equivalent.
```vb.net
Dim list = New List(of Integer)() From { 1, 2, 3, 4 }
```

```vb.net
Dim list = New List(of Integer)()
list.Add( 1 )
list.Add( 2 )
list.Add( 3 )
list.Add( 4 )
```
Which implies that `list` is initialized before the values are `add`ed to it. Thus implies that it can't be `null`
So if it's initialized and also not null, it means that you can refer to it. There's nothing in the specification *(that I can find)* that restricts / forbids the collection type from being refer to within the collection initializer.

**Comment by HaloFour** [comment]
I'd agree that the spec and the language behavior are at odds, then.  I noticed that under object initialization they at least use the verbiage "roughly equivalent to" rather than "equivalent to".

The spec should probably be updated to reflect the behavior.  I have to agree with how the language behaves, though.  The collection initializer itself is a separate expression from the assignment to the variable/field/argument/whatever.

**Comment by AdamSpeight2008** [comment]
@HaloFour 
What about the following example where the assignment and declaration isn't separate.
```vb.net
Dim list As New List(of Integer)() From { 1, 2, 3, 4 }
```
should be equivalent to
```vb.net
Dim list As New List(of Integer)()
list.Add( 1 )
list.Add( 2 )
list.Add( 3 )
list.Add( 4 )
```

**Comment by HaloFour** [comment]
It's still effectively separate.  That's just shorthand inherited from VB6 (thankfully not including the behavior from VB6).

**Comment by AdamSpeight2008** [comment]
cc: @ljw1004

**Comment by ljw1004** [comment]
I think this is just a spec bug. The spec should say that it's equivalent to
```vb
Dim _tmp As New List(of Integer)()
_tmp.Add( 1 )
_tmp.Add( 2 )
_tmp.Add( 3 )
_tmp.Add( 4 )

Dim list = _tmp
```

I think we'd be doing folks a disservice if we let them reference the object from within the collection initializer. The whole point of the feature is to feel like an "initialization", so by definition if the language allowed it then then you'd be reading from an "partially initialized" object.
