### ISSUE TITLE
Editor Completion Test Failures: TestNamedParameterAgainstMRU [Needs Backspace]

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27456]
**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
lack of backspace support. the root is #27441

**Comment by CyrusNajmabadi** [comment]
@dpoeschl is this still relevant?

**Comment by CyrusNajmabadi** [comment]
this has been enabled.  closing out.
