### ISSUE TITLE
Editor Completion Test Failures: XML Doc Comment Scenarios

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27450]
// TODO

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
@AmadeusW 
Let us consider InvokeWithTrueKeywordCommitSeeLangword. In 

```
class c
{
    /// <summary>
    /// $$
    /// </summary>
    void goo() { }
}
```
we try to type "tru", then SendInvokeCompletionList and then SendCommitUniqueCompletionListItem.
When we call ICommandHandler<CommitUniqueCompletionListItemCommandArgs>.ExecuteCommand, it make callbacks to GetCompletionContextAsync.
Here are callbacks:
1. trigger char = 't', snapshot line '/// t'
2. trigger char = 'r' snapshot line '/// t'
3. trigger char = 'u' snapshot line '/// t'
4. trigger char = '\0' snapshot line '/// t'
So, the snapshot is not updated, when sending type chars and sending invoke. Therefore, we cannot filter items properly.

**Comment by ivanbasov** [comment]
@AmadeusW, there are three tests to fix we need your help on the editor side. Their scenario is as follows. Check that '!' or '[' are PotentialCommitCharacters or ShouldCommitCompletion and then make a commit out of Roslyn.

Please note that Roslyn does not have enought information when calling PotentialCommitCharacters or ShouldCommitCompletion that the commit should be made. We need CompletionItem and SubjectBuffer to make a guaranteed decision. In some cases, we provide 'ok, maybe decision' and then correct it when called. However, we're not called in those following cases:
- CommitCdataNoOpenAngle
- InvokeWithOpenAngleCommitCommentOnCloseAngle
- TestBangFiltersInDocComment

We need PotentialCommitCharacters and ShouldCommitCompletion be corrected.
