### ISSUE TITLE
Editor Completion Test Failures: Old Completion Test Failures

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27452]
// TODO

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
fixed with https://github.com/dotnet/roslyn/pull/25770/commits/89802a19709a2dbbbe7d47386445a667e082f168
