### ISSUE TITLE
Editor Completion Test Failures: TestMissingOnObjectCreationAfterVar2

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27455]
**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
@dpoeschl is this still relevant?

**Comment by CyrusNajmabadi** [comment]
Closing out as this test is enabled.
