### ISSUE TITLE
Editor Completion Test Failures: TestCommitCharTypedAtTheBeginningOfTheFilterSpan

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27453]
Probably the editor team.

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
Scenario failed with new API:

```
class C
{
    public bool Method()
    {
        if ($$
    }
}
```

1. Remove $$ and start at that locaiton
2. Type "Met"
3. Hit Backspace 3 times

**Expected**
"Method" is selected with soft selection
**Actual**
"Method" is selected with soft selection

4. Type "!"
**Expected**
!Met
**Actual**
Method!

In the old API, we check for SoftSelection. If it is, we do not commit. 

@AmadeusW  please take a look

**Comment by CyrusNajmabadi** [comment]
@dpoeschl is this still relevant?

**Comment by CyrusNajmabadi** [comment]
This test doesn't exist.  closnig out.
