### ISSUE TITLE
Editor Completion Failing Tests: VB catchall bug

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27457]
// TODO

**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
could not find any references to the bug in sources

**Comment by CyrusNajmabadi** [comment]
@dpoeschl is this still relevant?

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
