### ISSUE TITLE
TypedReference shoud not be returned from C# 7.0 Local Function

### ISSUE THREAD

**Issue by stjeong** [dotnet/roslyn#27463]
**Version Used**: C# 7.0 ~ 7.3

**Steps to Reproduce**:

C# compiler can't compile next code.

        // Error CS1599 Method or delegate cannot return type 'TypedReference'
        TypedReference GetInstanceFromFunction()
        {
            int x = 100;
            TypedReference tr = __makeref(x);
            return tr;
        }

But, C# compiler can compile next code.

    private static void TestLocalFunction()
    {
        TypedReference inst = GetInstanceFromLocalFunction();
        int value = __refvalue(inst, int);
        Console.WriteLine(value);

        TypedReference GetInstanceFromLocalFunction()
        {
            int x = 100;
            TypedReference tr = __makeref(x);
            return tr;
        }
    }

As you know, it has side effect when the above code compile with Release. (or if some code exists between GetInstanceFromLocalFunction and __refvalue)

**Expected Behavior**:
In Local function, C# compiler must produce CS1599 error when returning TypedReference.

**Actual Behavior**:
In Local function, C# compiler compile normally.

**Comment by agocke** [comment]
@jcouv I'm moving this to 16.0 -- I don't think it meets the bar for 15.8.
