### ISSUE TITLE
error's on razor doesn't navigate to razor file correctly

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#27485]
https://developercommunity.visualstudio.com/content/problem/31017/double-click-in-error-list-item-sometimes-do-nothi.html?childToView=267673#comment-267673

...
Basically have any error in razor (non-existant property name, missing namespace, bad conditional statement etc), and it will appear in the error list of visual studio, but double clicking the error does not jump you to the error like it would for a .cs file.
..

it should work. something around error mapping seems broken.

**Comment by heejaechang** [comment]
tagging @jinujoseph

**Comment by CyrusNajmabadi** [comment]
Closing out as far too stale.  Presumably this all works now through LSP, and if it wasn't working we would fix it there.
