### ISSUE TITLE
Add more tests for code cleanup

### ISSUE THREAD

**Issue by JieCarolHu** [dotnet/roslyn#27497]
So far we have 5 tests for code cleanup, need to add more to cover remaining CodeCleanupOptions, also combinations of different options
tests are in this file: src\EditorFeatures\CSharpTest\Formatting\CodeCleanupTests.cs

1) Simple unit tests, one per option, that verify code cleanup works fine with only single option enabled.
2) Unit tests with multiple options enabled, but the reported diagnostics are not conflicting, hence can all be fixed.
3) Unit tests with multiple options enabled, where reported diagnostics have conflicting spans and hence not all can be fixed. Is this possible for our currently chosen diagnostics/fixers?
4) Verify options persistence after changing the workspace option.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
