### ISSUE TITLE
Add CodeCleanup Options to AutomationObject

### ISSUE THREAD

**Issue by JieCarolHu** [dotnet/roslyn#27511]
http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.CSharp/Options/AutomationObject.cs

![image](https://user-images.githubusercontent.com/17056651/41013489-118ed97e-68fb-11e8-8818-4627653b1e9f.png)

**Comment by sharwell** [comment]
This was made obsolete by #30605
