### ISSUE TITLE
Roslyn solution build fails in Visual Studio: "The 2.1.300-rtm-008866 SDK is required to build this repo but found 2.1.300 instead"

### ISSUE THREAD

**Issue by IanKemp** [dotnet/roslyn#27518]
A small dig into `Imports.targets` leads me to believe this is the same issue reported [here](https://github.com/dotnet/core-setup/issues/3805) - until that is fixed, is there a quick-n-dirty way for me to force MSBuild to pick the `2.1.300-rtm-008866` SDK that `Restore.cmd` downloaded?

If not, will installing this version of the SDK globally (i.e. into `%ProgramFiles%\dotnet\`) achieve this, and is doing so "safe" (will it break my existing installs)?

**Comment by jasonmalinowski** [comment]
@tmat or @jaredpar, want to help out here?

**Comment by IanKemp** [comment]
@jasonmalinowski apparently not... :(

**Comment by tmat** [comment]
Roslyn requires 2.1.300-rtm-008866 to be installed globally. 
@nguerrera Will VS prefer matching SDK version or will it use newer if available?

**Comment by nguerrera** [comment]
If exact match to global.json is found, VS will use it. It will not only select a different patch version if the exact lookup fails. It will fail outright if the only versions available are outside the patch range.

Absent a global.json, VS will use latest version available and 2.1.300 > 2.1.300-rtm-008866.

So it is perfectly safe to install 2.1.300-rtm-008866 side by side with true 2.1.300 RTM or any other version.

I would nevertheless recommend that Roslyn move to a true RTM build.

**Comment by IanKemp** [comment]
> I would nevertheless recommend that Roslyn move to a true RTM build.

Why is it not using RTM, anyway? Just that nobody has had the time to update the build configs?

**Comment by CyrusNajmabadi** [comment]
I'm not sure what is actionable here.  Going to close out unless there is a concrete proposal (ideally PR) that we can take through.
