### ISSUE TITLE
Change Google link in C# Interactive Walkthrough wiki

### ISSUE THREAD

**Issue by RodgerLeblanc** [dotnet/roslyn#27510]
The Google link in [C# Interactive Walkthrough](https://github.com/dotnet/roslyn/wiki/C%23-Interactive-Walkthrough) wiki doesn't work anymore.

It seems I can't do a PR for Wiki pages, here's a gist with a different CSV file downloaded, along with the updated code and wiki.
https://gist.github.com/RodgerLeblanc/55a71fb6b08c5603b12d2343400282d5

The CSV file comes from this page : https://www.microsoft.com/en-us/download/details.aspx?id=45485

**Comment by tmat** [comment]
@ivanbasov Would you mind updating the Wiki?

**Comment by chborl** [comment]
Thank you for the feedback and for providing the code edits. I have updated the page with the new link to CSV file and accompanying changes to the code.
