### ISSUE TITLE
How do i debug Compiler Crashes? csc.exe exited with code -2146232797

### ISSUE THREAD

**Issue by epoyraz** [dotnet/roslyn#27523]
Hi Guys,

i have already spent 2 days figuring out how to report this bug.
During compilation my compiler Crashes.
I am using the VS 15.7.3

![image](https://user-images.githubusercontent.com/1207226/41052183-6d17f81c-69b8-11e8-9737-49368abcbcc1.png)

And when i compile my code. This happens:
![image](https://user-images.githubusercontent.com/1207226/41052064-23dd2294-69b8-11e8-80dc-a271d9b4a3c6.png)
2 seconds later another error pops up:
![image](https://user-images.githubusercontent.com/1207226/41052126-41a9f8a6-69b8-11e8-8bca-e2f1552293c7.png)

Visual Studio Output:
  Microsoft.CSharp.Core.targets(52, 5): [MSB6006] "csc.exe" exited with code -2146232797.

I created a dump and could extract some info:
> OnFatalException():19, FailFast (Microsoft.CodeAnalysis)@Microsoft.CodeAnalysis.dll
> ReportUnlessCanceled():58, FatalError (Microsoft.CodeAnalysis)@Microsoft.CodeAnalysis.dll
> <CompileNamedTypeAsTask>b__0():206, <>c__DisplayClass21_0 (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> HadLambdaConversionError():475, OverloadResolutionResult`1 (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> ReportDiagnostics():127, OverloadResolutionResult`1 (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> ReportDelegateMethodGroupDiagnostics():123, Conversions (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> GenerateImplicitConversionError():16454, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> CreateReturnConversion():16871, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> CreateBlockFromExpression():17047, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindLambdaExpressionAsBlock():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> ReallyBind():0, UnboundLambdaState (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> Bind():0, UnboundLambdaState (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> IsAnonymousFunctionCompatibleWithDelegate():0, ConversionsBase (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> IsAnonymousFunctionCompatibleWithExpressionTree():0, ConversionsBase (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> HasAnonymousFunctionConversion():0, ConversionsBase (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> ClassifyImplicitBuiltInConversionFromExpression():0, ConversionsBase (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> ClassifyImplicitConversionFromExpression():0, ConversionsBase (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> IsApplicable():2494, OverloadResolution (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> IsApplicable():0, OverloadResolution (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> IsMemberApplicableInNormalForm():0, OverloadResolution (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> AddMemberToCandidateSet():0, OverloadResolution (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> PerformMemberOverloadResolution():0, OverloadResolution (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> ResolveDefaultMethodGroup():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> ResolveMethodGroupInternal():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> ResolveMethodGroup():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindMethodGroupInvocation():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindInvocationExpression():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindInvocationExpression():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindExpressionInternal():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindArgumentExpression():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindArgumentAndName():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindInvocationExpression():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindExpressionInternal():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindExpression():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindReturn():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindStatement():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindBlockParts():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindStatement():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindPossibleEmbeddedStatement():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindIfStatement():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindStatement():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindBlockParts():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindStatement():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindPossibleEmbeddedStatement():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindIfStatement():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindStatement():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindBlockParts():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindStatement():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindMethodBody():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindMethodBody():0, Binder (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> BindMethodBody():0, MethodCompiler (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> CompileMethod():0, MethodCompiler (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> CompileNamedType():0, MethodCompiler (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> <CompileNamedTypeAsTask>b__0():0, <>c__DisplayClass21_0 (Microsoft.CodeAnalysis.CSharp)@Microsoft.CodeAnalysis.CSharp.dll
> <WithCurrentUICulture>b__0():0, <>c__DisplayClass5_0 (Roslyn.Utilities)@Microsoft.CodeAnalysis.dll
> Execute():0, Task (System.Threading.Tasks)@mscorlib.dll
> RunInternal():0, ExecutionContext (System.Threading)@mscorlib.dll
> Run():278, ExecutionContext (System.Threading)@mscorlib.dll
> ExecuteWithThreadLocal():0, Task (System.Threading.Tasks)@mscorlib.dll
> ExecuteEntry():0, Task (System.Threading.Tasks)@mscorlib.dll
> Dispatch():0, ThreadPoolWorkQueue (System.Threading)@mscorlib.dll
> [Native to Managed Transition]():0,  ()@

I would like to give more info, but it's really hard to get more insight.
Unfortunately, i can't share my code. ( it's enterprise code and it's huge)¨
I would like to report a proper minimal example. But i am unable to do so, because i don't know what exactly it causes.
**Do you have any tipps, how i can debug this?**

**Comment by gafter** [comment]
@epoyraz Is it possible for you to [try the latest VS preview](https://www.visualstudio.com/vs/preview/) to see if you have the same problem there? The code around where the problem appears to be has changed quite a bit recently.

**Comment by epoyraz** [comment]
@gafter i just tried and i have the same problem :(
But i found out that my code compiles, when i use an older version of roslyn by referencing the Microsoft.Net.Compilers nuget. I am figuring out, between which versions it brakes. i hope this helps.

**Comment by epoyraz** [comment]
@gafter 
`    <PackageReference Include="Microsoft.Net.Compilers" Version="2.6.0-beta3" />` it crashes
`    <PackageReference Include="Microsoft.Net.Compilers" Version="2.4.0" />` it compiles just fine

**Comment by gafter** [comment]
@epoyraz I suggest debugging the issue as follows:
1. Create a git repository that is a clone of https://github.com/dotnet/roslyn
2. In a "Developer Command Prompt for VS 2017", do the following:
    a. `cd Roslyn` (or wherever your git clone of Roslyn is)
    b. `Restore.cmd`
3. Open `Roslyn.sln` in VS 2017
4. Hit `F6` to Build
5. Set "Visual Studio Setup" as your startup project (in the Solution Explorer, under the `Visual Studio` folder)
6. hit `F5` to Start Visual Studio with your new Roslyn under the debugger
7. In the new Visual Studio that pops up, open your solution that exhibits the problem.
8. Reproduce the problem. You will now be in a position to debug it.

Please let us know if you can do this, and if so what you learn.

**Comment by paul1956** [comment]
This might be obvious to some but you must install donnet-sdk-2.1.200-rtm-00-88-66.. before step 4, and F6 does nothing on my version of VS but I can use VS Menus or Ctrl+Shift+B to build.

**Comment by paul1956** [comment]
After including missing SDK, I can start second version of Visual Studio but when I try to open solution the original VS instance crashes
![image](https://user-images.githubusercontent.com/12789369/41207924-1ede465c-6cd2-11e8-86dc-6a63f6d5f6a5.png)
Microsoft.VisualStudio.Composition.CompositionFailedException
  HResult=0x80131500
  Message=Expected 1 export(s) with contract name "Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.MiscellaneousFilesWorkspace" but found 0 after applying applicable constraints.
  Source=Microsoft.VisualStudio.Composition
  StackTrace:
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.AbstractPackage`2.Initialize() in C:\Users\PaulM\Source\Repos\roslyn-master\src\VisualStudio\Core\Def\Implementation\LanguageService\AbstractPackage`2.cs:line 62
   at Microsoft.VisualStudio.LanguageServices.CSharp.LanguageService.CSharpPackage.Initialize() in C:\Users\PaulM\Source\Repos\roslyn-master\src\VisualStudio\CSharp\Impl\CSharpPackage.cs:line 78

**Comment by Neme12** [comment]
@paul1956 Did you try building the whole solution before starting VisualStudioSetup, or at least the Roslyn project? (I think that should be enough)

**Comment by Neme12** [comment]
@paul1956 What version of VS are you using?

**Comment by paul1956** [comment]
@Neme12 I am running the latest production release 15.7.3 and I built all the Roslyn using VS menu and I started with F5.

**Comment by paul1956** [comment]
The suggestion by @sharwell in #27720 allowed the build to complete but does not change anything with the error above. VS still opens but I can't open a solution.

**Comment by gafter** [comment]
My colleague @OmarTawfik suggests
1.	sync to the commit.
2.	`msbuild build\Toolset\Toolset.csproj`
3.	Copy `Binaries\Debug\Exes\Toolset` to another location (`C:\mycompiler`)
4.	And then in the project you want to debug, set this property: `<CscToolPath>c:\mycompiler</CscToolPath>`

**Comment by gtakhar** [comment]
Experiencing the same result upon updating to the latest version of Visual Studio 2017. Added a reference to the older version of the compiler seems to be the short term fix. I hope you guys are able to work through this.

Thanks!

**Comment by paul1956** [comment]
@gtakhar are you referring to the crash I posted  above? If so please detail the workaround.

**Comment by ravtakhar** [comment]
I believe @gtakhar is referring to "including the packkage for 2.4.0 also enables me to compile"

**Comment by ravtakhar** [comment]
Updating the .net compiler to the latest version (2.8.3) resolved the issue for me. I guess it was patched somewhere along the way.

**Comment by gafter** [comment]
@epoyraz Can you please try updating to 2.8.3 and see if that resolves the issue for you?

**Comment by epoyraz** [comment]
@gafter sorry for the late reply. I was on vacation. It seems my coworkers created an issue with a minimal example. See #28419

**Comment by gafter** [comment]
@epoyraz That issue makes the problem clear.  Thank you!

**Comment by epoyraz** [comment]
Update: this was fixed in #29360
Thanks! 🥇 👍
