### ISSUE TITLE
"Open active rule set " missing newly added nugget package rules

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#2752]
I installed the nugget package for 
Microsoft.CodeAnalysis.Analyzers & Microsoft.codeanalysis.csharp.Analyzers ,when I right click the Analyzers “ Open active rule set” this doesn’t show in the list 
![nugetpackagebug](https://cloud.githubusercontent.com/assets/12449387/7639502/51fddcc6-fa31-11e4-8b8f-76853fdfbdce.png)

 

As soon I play with “Set Rule set severity “ it shows up in the “active rule set” …is that the expected behavior ?

**Comment by jinujoseph** [comment]
I was under the impression that the ruleset viewer is auto-refresh. Closing the UI and reopening seems to have fixed the issue.

**Comment by srivatsn** [comment]
Talked to @jinujoseph - this only happens if the ruleset file is already open. That issue is tracked by #92. Closing as a dupe.
