### ISSUE TITLE
Editor Completion - Partner Signoff - Razor Scenarios

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27534]
**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
@AmadeusW I created an ASP.NET application and tried to edit a cshtml file.

Typing '@' and then a letter like 'a', I expect to get a completion. However, I haven't seen it and could not catch that Roslyn completion was called. Please advise.

**Comment by AmadeusW** [comment]
Are you using Razor bits that implement the async completion API? https://github.com/aspnet/Razor/pull/2227

**Comment by dpoeschl** [comment]
Using this issue to track the signoff, and https://github.com/dotnet/roslyn/issues/30188 to track the specific bug above.

**Comment by CyrusNajmabadi** [comment]
@dpoeschl is this still relevant?

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
