### ISSUE TITLE
Cannot infer method type argument when using an implicit cast

### ISSUE THREAD

**Issue by RunDevelopment** [dotnet/roslyn#27559]
**Version Used**: 

C# 7.3

**Steps to Reproduce**:

Consider the following example:

```c#
class Wrapper<T>
{
    public T Value { get; }
    public Wrapper(T value)
    {
        this.Value = value;
    }

    public static implicit operator Wrapper<T>(T value)
        => new Wrapper<T>(value);
}

void Consume<T>(Wrapper<T> wrapper) { /* some code */ }
```

Now, let's try to call `Consume`:

```c#
int i = 0;
Consume(i);
```

**Expected Behavior**:

The type `int` is inferred and an implicit cast is performed.

**Actual Behavior**:

The type is not inferred.
CS0411: The type arguments for method cannot be inferred from the usage. Try specifying the type arguments explicitly.

**Additional thoughts**

Despite that, the following works just fine.

```c#
Wrapper<T> Wrap<T>(T value) => value;

int i = 0;
Consume(Wrap(i));
Consume((Wrapper<int>) i);
Consume<int>(i);
```

**Comment by jcouv** [comment]
I believe this follows current language design, but I'll check in the spec.

Completed example:
```C#


public class Wrapper<T>
{
    public Wrapper(T value) => throw null;
    public static implicit operator Wrapper<T>(T value) => throw null;
}

class Other
{
    void Consume<U>(Wrapper<U> wrapper) => throw null;
    void M(int i)
    {
        Consume(i); // error CS0411: The type arguments for method 'Other.Consume<U>(Wrapper<U>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
    }
}
```

**Comment by gafter** [comment]
This is a type inference language feature request. Moving to `csharplang`.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #2067](https://github.com/dotnet/csharplang/issues/2067) via [**ZenHub**](https://www.zenhub.com/)
