### ISSUE TITLE
Lightbulb does not show up for code fixer

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#2756]
I wrote an analyzer that works fine. When I debug the VSIX project with F5, the squiggle shows up. Then I added a code fixer for the same issue. But the light bulb does not show up.

I placed the zipped-up solution on an internal share \\scratch2\scratch\lgolding\NoLightBulb.zip.

**Comment by shyamnamboodiripad** [comment]
@jmarolf and myself took a look on Larry’s machine and there doesn’t appear to be anything wrong with the rixer itself. Looks like the fixer is not getting MEF imported at all (the SupportedDiagnostics property of the provider is never invoked). An analyzer declared in the same project is being loaded correctly – but the fixer is not. (Note: This is the VSIX case and not NuGet).

And the problem repros only in this one project. If we create a fresh project using the template, the vanilla ‘make upper case’ code fix works fine. But if we copy this vanilla fix provider into the other project it stops working...

**Comment by shyamnamboodiripad** [comment]
This turned out to be because of MEF cache being out of sync. Clearing the cache fixed the problem.

**Comment by lgolding** [comment]
... and it was my fault (pilot error) that the MEF cache was out of sync. I tried to clear something out of the cache by hand because I didn't know the right way to do it. The fact that the cache got out of sync is not another bug.
