### ISSUE TITLE
GetTypeInfo() returns ErrorType for variable declared within a using statement

### ISSUE THREAD

**Issue by cawpat** [dotnet/roslyn#27560]
**Version Used**: 
C# 2.8

**Steps to Reproduce**:
I am using the following code to detect when a method containing the word 'Save' is called on an object with the type of ISession:

```
if (call.Expression.ToString().Contains("Save"))
{
   var innerExpression = call.Expression as MemberAccessExpressionSyntax;

      if (innerExpression != null)
      {
         if (model.GetTypeInfo(innerExpression.Expression).Type.Name.Equals("ISession"))
         {
            //Do some work.
         }
      }
}
```

This code works as expected. However when analysing the following snippet, the SemaniticModel, GetTypeInfo method returns an ErrorType TypeSymbol.

```
using (var session = SessionHelper.SessionFactory.OpenSession())
{
   session.Save(entityObject);
}
```

Roslyn is new to me so I'm not 100% whether this is an issue, or I'm missing something.

**Expected Behavior**:
The GetTypeInfo method to return a TypeInfo object containing type information on the object declared in the using statement.

**Actual Behavior**:
The GetTypeInfo method returns an ErrorType TypeSymbol.

**Comment by svick** [comment]
Can you check if your code compiles correctly by inspecting the result of calling `compilation.GetDiagnostics()` for your compilation?

If it did, can you provide full sample code that reproduces the issue, including both the code you're compiling and the code you're using to compile it? The following code works fine for me:

```c#
using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

class Program
{
    static void Main()
    {
        string code = @"
using System;

class SessionHelper
{
    public static SessionFactory SessionFactory { get; }
}

class SessionFactory
{
    public ISession OpenSession() => null;
}

interface ISession : IDisposable
{
    void Save<T>(T obj);
}

class Program
{
    static void Main()
    {
        var entityObject = new object();

        using (var session = SessionHelper.SessionFactory.OpenSession())
        {
            session.Save(entityObject);
        }
    }
}";

        var tree = SyntaxFactory.ParseSyntaxTree(code);

        var compilation = CSharpCompilation.Create(null)
            .AddSyntaxTrees(tree)
            .AddReferences(MetadataReference.CreateFromFile(typeof(object).Assembly.Location));

        foreach (var diag in compilation.GetDiagnostics())
            Console.WriteLine(diag);

        var model = compilation.GetSemanticModel(tree);

        var call = tree.GetRoot().DescendantNodes().OfType<InvocationExpressionSyntax>().Last();

        if (call.Expression.ToString().Contains("Save"))
        {
            var innerExpression = call.Expression as MemberAccessExpressionSyntax;

            if (innerExpression != null)
            {
                if (model.GetTypeInfo(innerExpression.Expression).Type.Name.Equals("ISession"))
                {
                    Console.WriteLine("It's ISession.");
                }
            }
        }
    }
}
```

**Comment by cawpat** [comment]
@svick I've done more debugging, and I believe the issue to be related to the fact that the SessionFactory class is defined in an external dll, so I don't Roslyn can see the return type of the OpenSession() method and since the session object is declared using var, Roslyn can't find the type of the object.

Is there any way for me to read in the class definition for SessionFactory directly from the external dll?

**Comment by svick** [comment]
@cawpat 

You can add a reference to a library to your compilation using [`AddReferences`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.compilation.addreferences?view=roslyn-dotnet). Your code could look something like:

```c#
var compilation = CSharpCompilation.Create(null)
    .AddSyntaxTrees(tree)
    .AddReferences(
        MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
        MetadataReference.CreateFromFile(pathToDll));
