### ISSUE TITLE
Expose IBinaryOperation.UnaryMethod for True/False operator method used for short circuiting

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#27598]
This method was added as an internal API for control flow graph work. This is tracks exposing it as a public API and adding relevant unit tests.

**Comment by jinujoseph** [comment]
map to the bug from heejae related to this

**Comment by mavasani** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/27598

**Comment by Youssef1313** [comment]
> Dupe of #27598

@mavasani This links to the same issue. I couldn't find any other issues for this. A new issue could be created using the api proposal template.
