### ISSUE TITLE
Test UseLocalFunction with trivia

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#27597]
Following up on https://github.com/dotnet/roslyn/pull/24763#discussion_r193904803

```C#
/* comment 1 */
Action [||]local = null; // comment 2
/* comment 3 */
local = () => local.Invoke(); // comment 4
```

**Comment by CyrusNajmabadi** [comment]
Closing out.  Current experience is acceptable.  We drive trivia fixes through reports about actual areas where things didn't go well.  thanks!
