### ISSUE TITLE
Consider reaching out to remerge with the Mono fork of Roslyn

### ISSUE THREAD

**Issue by SirCmpwn** [dotnet/roslyn#276]
What plans are in place for merging this repository with the Mono fork? A cursory review of the patches leads me to believe that they could be merged into here with little fuss, or with `#if` when appropriate. Why maintain the two seperately?

**Comment by gafter** [comment]
Do you believe the Mono branch works on Windows the same as the dotnet branch?

**Comment by SirCmpwn** [comment]
I'm not sure, but my guess would be "yes". Even if not, though, would there be a problem with surrounding them with `#if` for platform-specific concerns?

**Comment by theoy** [comment]
This is a great idea. We're beginning to work on some cross-platform work as well, and it would be great to work with some mono folks to see where we can land between the two efforts.

@gafter brings up a good point of ensuring that we have the proper functional behavior on Windows (and is compatible for our existing C# customers). However, I would believe that our project and Mono have similar goals along that - so I'm interested in seeing what the final merge would be.

I'm going to ask @vsadov to add this to his radar to see where we can end up with this.

Thanks @SirCmpwn for the suggestion! :smile:

**Comment by VSadov** [comment]
As a part of cross-platform work I am definitely considering the changes done in the Mono fork. Some changes can indeed be just ported over, while other changes appear to be indications of architectural inconveniences. For example, Roslyn is clearly not very friendly to the idea of alternative emitters for debug information and we may need a more comprehensive fix in this area.

**Comment by SirCmpwn** [comment]
Is Roslyn self hosting? Can it be bootstrapped?

**Comment by SirCmpwn** [comment]
Bump.

**Comment by gafter** [comment]
@SirCmpwn We're scheduled to look at this in more detail post VS2015.

**Comment by VSadov** [comment]
@SirCmpwn - Re: Is Roslyn self hosting? Can it be bootstrapped?
The answer is yes and in fact Roslyn relies on bootstrapping now since we use C#6 features unsupported by pre-Roslyn compilers.
We perform self-rebuild as a part of CI tests on Linux, Mac or Windows.

Note that running Roslyn on Linux is very much "work in progress" at the moment and requires multi-step setup, but doable if you are curious:
https://github.com/dotnet/roslyn/wiki/Linux-Instructions

**Comment by SirCmpwn** [comment]
Thanks for the info.

**Comment by VSadov** [comment]
I guess that since Roslyn runs on linux/mac/mono and that the mono branch has not been updated since February, this issue is no longer relevant.
