### ISSUE TITLE
Question: Is Analyzer required to be compiled for netstandard1.3?

### ISSUE THREAD

**Issue by cincuranet** [dotnet/roslyn#27623]
Is Analyzer/CodeFix required to be compiled for `netstandard1.3` (as created by the template in VS)? Is it possible to use `netstandard2.0`?

**Comment by jmarolf** [comment]
> Is it possible to use `netstandard2.0`?

it is possible under certain constrained scenarios.  If you want to write an analyzer that targets macOS, Linux, and Windows and have those analyzers run on .NET Framework 4.6.1 - 4.7.2 you will need to target `netstandard1.3`.

A few questions:

1. What apis from `netstandard2.0` do you need in your analyzer?
2. Would having your analyzer only run on .NET Framework be acceptable?

**Comment by cincuranet** [comment]
> it is possible under certain constrained scenarios.  If you want to
> write an analyzer that targets macOS, Linux, and Windows and
> have those> analyzers run on .NET Framework 4.6.1 - 4.7.2 you will need to target> `netstandard1.3`.

OK. Thanks.

> 1. What apis from `netstandard2.0` do you need in your analyzer?

I needed Assembly property of Type type (using
typeof(TSomething).Assembly. I eventually solved it differently (working
with MetadataReference and passing it from different layer).
> 2. Would having your analyzer only run on .NET Framework be
>    acceptable?
I would rather not constrain the usage unless absolutely necessary.

**Comment by cincuranet** [comment]
Ahh, right. I completely forgot about it. But I solved it anyway moving one level up and using `MetadataReference`. :)
