### ISSUE TITLE
Can no longer right-click a solution folder and choose 'build'

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#27624]
I used to do this all the time in Roslyn.  For example, i would 'build' the 'features' folder or the 'workspaces' folder.  Now, right-clicking on a folder in solution-explorer does nothing.  I'm on:

![image](https://user-images.githubusercontent.com/4564579/41155318-6bc864f4-6aeb-11e8-9b7b-1e47363985f7.png)

This was working just a few weeks ago, so it's a recent regressions.

Tagging @Pilchie @davkean to see if they know anything about this.

Thanks!

**Comment by davkean** [comment]
This is a regression in Preview 2.0.

**Comment by davkean** [comment]
It's known, will be fixed in Preview 3.0.

**Comment by CyrusNajmabadi** [comment]
thanks! @davkean  is there a tracking bug/pr i can watch?  Thanks!

**Comment by CyrusNajmabadi** [comment]
Ah, ok.  Thanks!
