### ISSUE TITLE
SyntacticClassificationTaggerProvider always reports whole file classification changed

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/roslyn#27649]
Problem is at https://github.com/dotnet/roslyn/blob/ad3dd0a/src/EditorFeatures/Core/Implementation/Classification/SyntacticClassificationTaggerProvider.TagComputer.cs#L214 problem is that every time change happens, we need to call `GetTags` and compare which takes time on UI thread...

This is not super urgent, but would be nice to be fixed asap.

**Version Used**: 
Any

**Steps to Reproduce**:

1. Initialize syntactical classification tagger.
2. Make small text change.
3. Classifier reports whole file changed.

**Expected Behavior**:
Report only modified part of syntax highlighting.
**Actual Behavior**:
Reports whole file changed.

**Comment by sharwell** [comment]
@DavidKarlas This is an area I find fascinating and have done work on in the past for other projects. Can you expand on this part of your question so I have a bit more context when I reply:

> ... we need to call `GetTags` ...

Who is 'we' in this case?

**Comment by DavidKarlas** [comment]
VS for Mac, but afaik, VS has same problem...

**Comment by CyrusNajmabadi** [comment]
> problem is that every time change happens, we need to call GetTags and compare which takes time on UI thread...

Can you explain why you need to compare on the UI thread?  

basically, someone is going to do the comparison of tags.  Either Roslyn or the host.  So shuffling this around is only valuable if we change things to not be UI thread based.

**Comment by CyrusNajmabadi** [comment]
> Classifier reports whole file changed.

Note: this is because this classifier basically defers work until actually requested.  So anytime we see the doc is touched, we basically say: "we're stale, call back into us!".  Then, when the host calls back into us, we actually compute the tags.

Note: is there a reason you're calling back with the entire span, instead of just the span you need to display in the editor?

**Comment by DavidKarlas** [comment]
I thought you can do something smarter then running same thing and do compering(which is what we do). Reason we run this on UI thread is because event(TagsChanged) is triggered on UI thread, you are right we should move this off main thread and calculate actual changed and trigger that on UI thread...
