### ISSUE TITLE
Lightbulb suppression assumes the defect to be on single line span

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#2764]
suppression suggestion for single line 

![singleline](https://cloud.githubusercontent.com/assets/12449387/7642126/6b7fdee4-fa43-11e4-9799-74bdd131734b.png)

suppression suggestion for multiple line 

![multipleline](https://cloud.githubusercontent.com/assets/12449387/7642132/7621e9d2-fa43-11e4-825b-48a6f510194b.png)

**Comment by shyamnamboodiripad** [comment]
Note that this does not result in a syntax error (at least in the C# case - but I am not certain this will also be true in the case of VB.

I think we should change the suppression fix to place the ```#pragma restore``` directive on a new line after the last token that is in the warning span.
