### ISSUE TITLE
Add support for Emit tests to Mono runs

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#27642]
Emit tests seem like the most likely place we're going to break Mono and signing in particular has been the cause of servicing fixes. The first task here would be to get the Emit test assembly running during the Mono run and see what we need to skip or fix and then make sure that at least some of our signing tests can run on Mono (key containers will probably never work, so those will always be skipped).

**Comment by jaredpar** [comment]
This work is completed now.
