### ISSUE TITLE
Editor Completion Tests: VB Tests that require CurrentCompletionPresenterSession

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27656]
**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
@dpoeschl is this still relevant?

**Comment by CyrusNajmabadi** [comment]
this is not actionable.
