### ISSUE TITLE
Editor Completion Tests: Enable "SendSelectCompletionItem"

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27654]
**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by ivanbasov** [comment]
from @AmadeusW 

> use the `IAsyncCompletionSessionOperations` interface
> 
> `public interface IAsyncCompletionSessionOperations : IAsyncCompletionSession`
> it has `SelectCompletionItem`
> notice that most of the methods there _enqueue_ an operation
> you'll need to wait for the computation to be complete
> you can `SelectCompletionItem` and then `ItemsUpdated` or `GetComputedItems` to be sure that the last operation has finished

Need a later version of the editor than we currently use.

**Comment by CyrusNajmabadi** [comment]
@dpoeschl is this still relevant?

**Comment by CyrusNajmabadi** [comment]
This is not actionable.
