### ISSUE TITLE
Editor Completion Tests: VB Commit on Enter isn't inserting an extra newline

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27655]
**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
@dpoeschl is this still relevant?

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
