### ISSUE TITLE
Options/Text Editor/C#/Formatting radio buttons show preview incorrectly

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#2767]
Both indentation and spacing radio buttons do not show preview and actually need to be activated by two clicks in order to show the preview of what they do.

Reproduce
=========
Go to Tools > Options > Text Editor > C# > Formatting > Indentation > Label Indentation 

Expected
========
See the preview for the given option. 

Issue
====
The preview is the same for all options.

Notes
=====
 I'm using Visual C++ settings preset and the radio buttons in C++ options show preview correctly.

**Comment by CnSimonChan** [comment]
I had reported this bug when it was CTP3, but someone said it was "fixed"...

https://connect.microsoft.com/VisualStudio/feedback/details/981314/connect-radio-buttons-in-c-formatting-options-pages-behave-incorrectly

**Comment by Pilchie** [comment]
@CnSimonChan: Thanks for letting me know.  We normally have a process to verify that bugs that we claim are fixed actually are (that's the purpose of the "Verified" label on our GitHub issues.  Sometimes they are fixed and then regress again later.  Other times the person working on the fix or the verification has a different interpretation of what the bug is, or what the behaviour *should* be.  I'll follow up to see what went wrong on this issue.

One thing I am working on though is finding a way for people outside Microsoft to try our builds on a more regular basis so that they can actually verify that things are actually fixed.  This might take the form of something like publishing nightly builds of the installer msi for the Roslyn language services for example.

**Comment by Maxwe11** [comment]
What project should I look for fixing this?

**Comment by Pilchie** [comment]
Maybe start here: http://source.roslyn.io/Microsoft.VisualStudio.LanguageServices.CSharp/R/a263f2299cc3b03b.html

Unfortunately, we don't have a good way for people outside Microsoft to build and test that code yet :frowning:

**Comment by jasonmalinowski** [comment]
Turns out I've fixed this in pull request #3298.

**Comment by jasonmalinowski** [comment]
Fixed by #3298.
