### ISSUE TITLE
LocalUserRegistryOptionPersister should be host agnostic

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#27678]
**Version Used**: 
master

**Expected Behavior**:
`IOptionPersister` implementations should not be tied to VS implementation. The implementations can mostly be in `Workspaces.Desktop`.

## [LocalUserRegistryOptionPersister](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Options/LocalUserRegistryOptionPersister.cs,21)

It should be host agnostic to be able to reuse more code. It should be defined in Workspaces.Desktop (or a lower layer), and Roslyn should surface a specific interface `IRegistryManager` that can be implemented in the roslyn VS layer with a `GetRootRegistry()` method that is only used for VS.

If the `IRegistryManager` export does not exist, it should just use BCL APIs.

**Actual Behavior**:
`IOptionPersister` implementations are VS specific

**Comment by CyrusNajmabadi** [comment]
This has been heavily refactored, and there has been no more feedback.  Closing out.
