### ISSUE TITLE
RoamingVisualStudioProfileOptionPersister implementations can be moved to lower layer

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#27677]
**Version Used**: 
master

**Expected Behavior**:
`IOptionPersister` implementations should not be tied to VS implementation. The implementations can mostly be in `Workspaces.Desktop`.

## [RoamingVisualStudioProfileOptionPersister](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Options/RoamingVisualStudioProfileOptionPersister.cs,27)

It should be host agnostic to be able to reuse more code. It should be defined in Workspaces.Desktop (or a lower layer), and Roslyn should surface an `ISettingsManager`-like interface that needs exported that has: `SettingChanged`, `GetValueOrDefault`, `SetValue` methods exposed.

**Actual Behavior**:
`IOptionPersister` implementations are VS specific

**Comment by CyrusNajmabadi** [comment]
Closing out as there hasn't been any movement on this.  if you really want this, i'd recomment starting a discussion, and/or just making a PR for this that can be discussed.
