### ISSUE TITLE
What is the null-state of a local declared with an oblivious value?

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#27686]
My assumption is that following `string s = obliviousString;`, the state of `s` is `string!` (declaration wins over oblivious). Or `ns` should be nullable following `string? ns = obliviousString;`.
Chuck thought the state of `s` and `ns` should remain oblivious.

The same question applies for `OutputsOblivious(out string s);`.

Need to confirm with LDM.
Either way, it is a minor change to the `TrackNullableStateForAssignment`.

Update: A possible related issue is whether `string s = obliviousString;` should be a warning. Either way, you will not get a warning on something that is potentially unsafe (like a subsequent dereference).

**Comment by gafter** [comment]
I believe the LDM already decided that the flow state is independent of the declared type. The flow state is whatever flows.

**Comment by gafter** [comment]
(Doing otherwise would undermine the value of the separation of W warnings and non-W warnings)

**Comment by jcouv** [comment]
I didn't understand your point about W warnings. Could you clarify?

I can't remember LDM discussing the oblivious case, nor could I find any notes related to that. 
The rationale for tracking not-null and maybe-null may be separate than that for tracking oblivious: oblivious means "don't care", which may cease once you indicate that you care, by using types with nullable annotations.

Admittedly, most scenarios behave the same in both views. For example, `string s = obliviousString; s.Dereference(); // no warning either way`.
But there would be a difference in `string? ns = obliviousString; ns.Dereference();`. I think it is useful to warn in that case. If the oblivious string is really non-null, then you should declare the local as non-null.

**Comment by gafter** [comment]
Regarding W warnings... If executable (method body) code that is not annotated is treated as being annotated as you suggest, then we will be computing incorrect flow state that could undermine the analysis. The W warnings were designed to separate the important (non-W) warnings from the W (cosmetic) warnings. But your suggestion makes the annotations on local declarations more than cosmetic, as they affect the computed flow state.

> The rationale for tracking not-null and maybe-null may be separate than that for tracking oblivious: oblivious means "don't care", which may cease once you indicate that you care, by using types with nullable annotations.

Oblivious does not mean "don't care". It means "don't know". Pretending to know based on the lack of annotations in the method body (e.g. in `string s = M();` means that annotations *and lack of annotations* in the method body are significant to the analysis and not merely cosmetic. It means people will be forced to annotate method bodies to get the analysis correct. That is in conflict with the goal of separating W and non-W diagnostics.

**Comment by jcouv** [comment]
>  ... lack of annotations in the method body are significant to the analysis and not merely cosmetic

Could you provide an example where a lack of annotation affects the analysis in an observable way? That would help clarify the stakes and impact of this decision.

As far as I can tell, someone who wants to suppress W warnings and not annotate locals isn't harmed by this design. 
Consider the benefits in a partially annotated project: I use `?` in some URTANN'ed parts of the project, and the rest is oblivious. I'd like to get the benefit from those `?` annotations in the opted-in code. The fact that I put them there is a good indication, and this is likely a case where the user knows better (since flow analysis has no information for oblivious, by the "don't know" definition).

Tagging @cston for thoughts.

**Comment by jcouv** [comment]
From discussion with @gafter, here's a scenario that is impacted: given `void M(List<string?> x)` and `List<T> MakeList<T>(T item)`, write `string s = obliviousString; M(MakeList(s));`.
If we give `s` a non-null state, then the invocation would fail (cannot convert from `List<string>` to `List<string?>`.

**Comment by jcouv** [comment]
From discussion in LDM today (7-11), oblivious is ephemeral. 

For example, `string s = obliviousString;` produces a `string!` for `s`. 
And even `var s = obliviousString;` produces a `string!` for s`.
The same applies in method type inference. For example, if you pass an `obliviousString` into `List<T> F<T>(T t)`, you get back a `List<string!>!`.
This way, you can never hold onto an instance of a type that you could not write.

**Comment by gafter** [comment]
This was fixed and tested in https://github.com/dotnet/roslyn/pull/33648

**Comment by jcouv** [comment]
There is still a mention of this issue in a test (comment/question can be removed now).

**Comment by jcouv** [comment]
There is no mention of this issue anymore in code/test. Closing
