### ISSUE TITLE
Encapsulate field refactoring improvement

### ISSUE THREAD

**Issue by josetr** [dotnet/roslyn#27683]
**Version Used**: 
15.7.3

**This is the refactoring that would be nice to have:**
Before:
`public string Version;`
After:
`public string Version { get; set; }`

**Actual Behavior**:
There's currently only 2 refactoring choices I get which both seem to give the same output:

**1. Encapsulate field (and use property)**

Before:
`public string Version;`
After:
```
private string version;
public string Version { get => version; set => version = value; }
```
**2. Encapsulate field (but still use field)**
Before:
`public string Version;`
After:
```
private string version;
public string Version { get => version; set => version = value; }
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
