### ISSUE TITLE
Regression: Interactive Window doesn't display caret

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#27688]
**Version Used**: 
![image](https://user-images.githubusercontent.com/41759/41205553-64d49fda-6caa-11e8-871e-eaaadfc45898.png)

**Steps to Reproduce**:

Open C# Interactive Window

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/41759/41205582-e5391b10-6caa-11e8-966f-791d21f0bf73.png)

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/41759/41205565-81c6abf6-6caa-11e8-86df-4cf783e32265.png)

**Comment by jinujoseph** [comment]
This doesn't repro , @tmat can you recheck

**Comment by tmat** [comment]
Fixed by the editor.
