### ISSUE TITLE
Editorconfig: Need to enforce anonymous member name to be defined

### ISSUE THREAD

**Issue by devovercome** [dotnet/roslyn#27695]
Hi! 
I am working on setup which includes `dotnet_style_prefer_inferred_anonymous_type_member_names ` for asp.net solution.

Here is global problem - team used to abuse anon object in order to return JSON result. Hovewer, I want to enforce (or encourage at least) write anon object _properties_ of JSON repsonse explicitly. Why? Because if source field of anon object has been renamed - the JSON output will be changed, and JS-frontend would be broken and hard to fix. 

To be more specific, case like:
```
// consider datetime as user-defined structure.
return Json(datetimes.Select(x => new 
{
    x.Mounth // typo, will break js when refactored
//    Mounth = x.Month // wont break after backend refactoring.
})
```

Here is the sampes for the case.
- [editor.config](https://github.com/devovercome/Tmp.EditorConfig.Enforce.AnonTypeNames/blob/master/.editorconfig)
- [csharp code](https://github.com/devovercome/Tmp.EditorConfig.Enforce.AnonTypeNames/blob/master/EditorConfig.Enforce.AnonTypeNames/Program.cs)
- [entire solution (big picture)](https://github.com/devovercome/Tmp.EditorConfig.Enforce.AnonTypeNames)

Environment:
ASP.NET 
.NET 4.7.1
VS 2017 15.6.6

**Comment by CyrusNajmabadi** [comment]
> Here is global problem - team used to abuse anon object in order to return JSON result. Hovewer, I want to enforce (or encourage at least) write anon object properties of JSON repsonse explicitly. 

You can write a Roslyn analyzer to apply whatever sort of code-style preference you want to your organizations code.  Let me know if you need any pointers on this.

**Comment by devovercome** [comment]
Is this a right direction? [Getting Started with Roslyn Analyzers](https://msdn.microsoft.com/en-us/library/mt162308.aspx) Facinating! I'd like to implement this, but dont know is there a reason to leave issue opened until I get it done, or close since it _probably_ answered?

**Comment by CyrusNajmabadi** [comment]
@devovercome Yup.  That's a good place to start.  Closing this out makes sense to me :)

**Comment by Neme12** [comment]
Isn't there an existing option for this, similar to using implcit tuple names?

**Comment by Neme12** [comment]
Why is dotnet_style_prefer_inferred_anonymous_type_member_names set to false not working? That seems like it should work. Is this by design? Can we reconsider this?
