### ISSUE TITLE
Possibly wrong `span1.Contains(span2)` "order"

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/roslyn#27703]
On VSfM sometimes using `ICodeFixService` returns wrong list of code fixes if code changed recently(last ~1sec). I debugged what is happening and my conclusion is that most likely problem is at https://github.com/dotnet/roslyn/blob/9e79136/src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.Executor.cs#L604
What we do from VSfM code, we call `ICodeFixService.GetFixesAsync()` and we use `span` and we put cursor position as `span` so something like `(193,193)` and there is diagnostic at `(190,200)` for `CS0103`(The name XXX does not exist in current context). Which will later be used to produce `Add using ...` or `Generate XXX`...  fixes.
But this doesn't not happen because https://github.com/dotnet/roslyn/blob/9e79136/src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.Executor.cs#L604 filters this diagnostic out, hence no fixes. Should this `span.Value.Contains(diagnostic.Location.SourceSpan)` be `diagnostic.Location.SourceSpan.Value.Contains(span)`?

**Comment by gafter** [comment]
Also perhaps consider testing whether or not the spans overlap.

**Comment by sharwell** [comment]
@mavasani Do you know why this is working in Visual Studio but not in Visual Studio for Mac?

**Comment by mavasani** [comment]
Tagging @heejaechangf - not sure why the behavior differs between VS and VS for Mac. I believe the check is being done for [LatestDiagnosticsForSpanGetter](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs,41), which seems to expect the callers to pass in the complete span within which the diagnostic span must be contained. I don't recall why the API requires containment versus overlap/intersection of spans, @heejaechang do you remember?

**Comment by DavidKarlas** [comment]
In my opinion `Contains` should be changed to `Intersects`, because if diagnostic is multiline, and I ask for current line, logic afaiu won't return diagnostic since it's just intersects with it, but not contains... We request empty span because we are only interested in diagnostics at cursor position when user right clicks... So, if possible I would prefer if this can be changed to `Intersects`.

**Comment by heejaechang** [comment]
@DavidKarlas it looks like it is already intersectsWith actually?

http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs,403
