### ISSUE TITLE
[Diagnostic] for Infinite Looping Constructs

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#27717]
@kuhlenh 
Could we have a diagnostic that detects if you changing the variable in a While Loop.
```
Dim idx = 0
While idx < [End]
 ' code
 ' forget to alter idx.
End If
```
To provide assistance against potential infinite loops in your code.

**Comment by mavasani** [comment]
Potentially already covered by https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers.Exp/Core/Maintainability/AvoidDeadConditionalCode.cs#L19, which identifies always true/false expressions based on flow analysis.
