### ISSUE TITLE
Need a dedicated platform exception type for non-exhaustive switch expression

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#27747]
When a switch expression doesn't have a matching arm at runtime, we need an exception to throw.

**Comment by gafter** [comment]
Something like

``` c#
namespace System
{
    /// <summary>
    /// Indicates that a switch expression that was non-exhaustive failed to match its input.
    /// </summary>
    public class MatchFailureException : SystemException
    {
        public MatchFailureException() { }
    }
}
```

**Comment by jcouv** [comment]
@gafter Please open a corefx issue for design review (something like https://github.com/dotnet/corefx/issues/21809).

**Comment by gafter** [comment]
The `corefx` issue for this is https://github.com/dotnet/corefx/issues/33284
