### ISSUE TITLE
Follow-up on suppression operator feedback (regarding `ref`/`out` arguments)

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#27743]
@AlekseyTs had [more feedback.](https://github.com/dotnet/roslyn/pull/27317#pullrequestreview-127781268) : Should the `!` have any effect on type argument inference?

**Comment by agocke** [comment]
@jcouv I don't really understand the scope of these questions. For instance, is this test sufficient to cover the behavior?

```C#

                // (8,20): warning CS8600: Converting null literal or possible null value to non-nullable type.
                //         string u = t; // warning
                Diagnostic(ErrorCode.WRN_ConvertingNullableToNonNullable, "t").WithLocation(8, 20)
```

**Comment by jcouv** [comment]
For ref:
```C#
void M<T>(ref T) => throw null!;

string? x = "";
M(ref x!); // did the ! affect inference?
```

For out:
```C#
void M<T>(out T) => throw null!;

string? x = "";
M(out x!); // did the ! affect inference?
```

For the `ref` case, I think the answer is no. For purpose of nullability analysis, we're going to require the argument and the parameter types to be identity convertible. So adding `!` would not help anyone.

For the `out` case, I'm not sure. My instinct is that the `!` would only affect the value on the way out and so would not affect inference either.
