### ISSUE TITLE
Snippet IntelliSense broken

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27745]
Repro steps:

1. Create new &quot;Wpf App&quot; project
2. Inside the MainWindow class (in MainWindow.xaml.cs), use the &quot;propfull&quot; snippet (type &quot;propfull&quot; and hit tab twice)
3. For the data type, enter &quot;FrameworkElement&quot; and hit tab to move to the field name.
4. For the field name, type &quot;ui&quot; and hit tab to move to the property name.

Actual: The field name is now &quot;FrameworkElement&quot; instead of &quot;ui&quot;.

Expected: The field name is &quot;ui&quot;.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/104757/snippet-intellisense-broken.html
VSTS ticketId: 487686_
_These are the original issue comments:_

Jinu Joseph [MSFT] on 11/11/2017, 05:41 PM (212 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

John B. on 3/6/2018, 08:16 AM (98 days ago): Please take time to fix this one. It's terribly annoying, and it was broken recently enough it should be easy to troubleshoot.
John B. on 6/11/2018, 01:02 PM (22 hours ago): Jinu, please investigate this. This happens FREQUENTLY. It's painful.
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
cc @dpoeschl

**Comment by jinujoseph** [comment]
Repros in 15.6 onwards

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in legacy snippets.
