### ISSUE TITLE
we are leaking solution in AbstractSymbolCompleteionProvider

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#2776]
we are leaking this

http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/Providers/AbstractSymbolCompletionProvider.cs,b0cd3dba106599c0

we should make sure we clean this up.

**Comment by heejaechang** [comment]
@rchande I assigned it to you

**Comment by rchande** [comment]
Fixed with #2967

**Comment by rchande** [comment]
@heejaechang Can you confirm this leak is fixed?

**Comment by heejaechang** [comment]
sure
