### ISSUE TITLE
Roslyn applies new overload resolution rules no matter what the LangVersion is

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#27775]
This code compiles on Roslyn for all C# language versions but gives the expected CS0121 when compiled with `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>2</LangVersion>
  </PropertyGroup>

</Project>
```

```cs
using System;
using System.Threading.Tasks;

public static class Repro
{
    public static void Foo(Action<int> action)
    {
    }

    public static void Foo(Func<int, Task> asyncAction)
    {
    }

    public static void Surprise()
    {
        Foo(null);
    }
}
```

Repros in vs 15.7.3 and [SharpLab's 2.8.2](https://sharplab.io/#v2:D4AQDABCCMDcCwAocVoFYGKSAzKgbFAEyoDsSA3hNREjVHjISACwQBiA9pwBQxEAeAJYA7AC4A+CAEMAxmKGcRASjo0Ka6gF9NtRPVwEobLrxBph4gDRR8UkAA5+q/et07X1XYabGIAZQBXACcAB2ChAGcAUx4Xeg1EAEgk0x4RQIAbTOVMeg8tIA===) as well as a [random branch from 2017](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQAcEEsBusIAKCA9jBAMZkAmAPgAIAMABHQIwDcAsAFCMusBWLtx50AzPwBsLAEz8A7DwDeTVUx5qWEttLoAWJgDFixABRsZAHiwA7GAD4mUSlmI2AlBrVKvqgL6+6tya4lIsBsZmdALWdgA0LJKOdAAcFp7B3oEBmaqBoTrhTADKiJhYyBCmGZo+3ACQ9ZGmNnAANm3uwpo5fkA=).

Is this part of the overload resolution changes in C# 7.3? Why is it changing the compilation of C# code under versions 2 to 7.2?

**Comment by Neme12** [comment]
I think this has to do with better betterness, not improved overload candidates.

**Comment by gafter** [comment]
@Neme12 You are precisely correct. See https://github.com/dotnet/roslyn/blob/master/docs/specs/CSharp%206/Better%20Betterness.md .

We use the language version primarily to restrict the syntax that the compiler accepts. The compilers do not implement the semantics from all previous versions of the language. This is intentional.
