### ISSUE TITLE
Low perfomance?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/roslyn#27783]
![35ff256d677f72565c72a10c0772083001d79bcdeac3908aa338fd729e7bf75d](https://user-images.githubusercontent.com/16236903/41338187-ff93edca-6f23-11e8-9523-9d3db5eb6ac5.png)

Really?  Why??

**Comment by JimBobSquarePants** [comment]
I suggest you fill the issue template out properly. This is useful to no-one.

**Comment by adamsitnik** [comment]
And provide the code of the benchmark ;)

**Comment by NMSAzulX** [comment]
**Version Used**: 

Microsoft.CodeAnalysis.CSharp.Scripting 2.7.0
.net core 2.0
BenchmarkDotNet 0.10.13

**Steps to Reproduce**:

1. Create a class named Watcher will be tested by BenchmarkRunner.
```C#
 public class Watcher
 {
        ScriptRunner<object> RoslynAction;
        Func<object> EmitAction;


       [Benchmark]
        public void Roslyn()
        {
            RoslynAction();
        }

        [Benchmark]
        public void Emit()
        {
            EmitAction();
        }
}
```
2. Create a method named Runner which will be used by RoslynScript and Emit.
like this: 
```C#
 public static void Runner(string value)
 {
          //just do something for test
          string result = "1";
          result += value;
 }
```
3.  Store fields RoslynAction and EmitAction in the constructor for this class.  Please see the [source code](https://github.com/NMSAzulX/RoslynPerfomanceTest)

4、Run benchmark.
  
  


**Expected Behavior**:

as well as emit-code

**Actual Behavior**:
![35ff256d677f72565c72a10c0772083001d79bcdeac3908aa338fd729e7bf75d](https://user-images.githubusercontent.com/16236903/41338187-ff93edca-6f23-11e8-9523-9d3db5eb6ac5.png)

**Comment by jmarolf** [comment]
Thanks @NMSAzulX I can see the same results on my machine running the code here: https://github.com/NMSAzulX/RoslynPerfomanceTest

``` ini
BenchmarkDotNet=v0.10.13, OS=Windows 10.0.17134
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical cores and 4 physical cores
Frequency=2742189 Hz, Resolution=364.6722 ns, Timer=TSC
.NET Core SDK=2.1.200
  [Host]     : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit RyuJIT
  DefaultJob : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit RyuJIT


```
| Method |      Mean |     Error |    StdDev |
|------- |----------:|----------:|----------:|
| Roslyn | 232.93 ns | 4.4358 ns | 4.3566 ns |
|   Emit |  39.68 ns | 0.7851 ns | 0.7344 ns |

**NOTE:** these two snippets are not semantically equivalent (I believe this is the question you are asking). 

In this first snippet `ScriptRunner<object>` is essentially a convenience method for `Task<ScriptState<T>> Script<T>.RunAsync(object globals, CancellationToken cancellationToken)` which does not return the captured `ScriptState<T>`  (even though it is still calculated).
```C#
Script<object> script = CSharpScript.Create(@"using System;
using RoslynTest;
Watcher.Runner(""123"");
Watcher.Runner(""123"");", 
ScriptOptions.Default.AddReferences(Assembly.GetEntryAssembly()));
script.Compile();
ScriptRunner<object> roslynScriptDelegate = script.CreateDelegate();
roslynScriptDelegate();
```

In this second snippet we just generate and execute a delegate (with no ability to observe any variables it might create as a result of execution).
```C#
DynamicMethod method = new DynamicMethod("Advise", typeof(object), new Type[0]);
ILGenerator il = method.GetILGenerator();
var methods = typeof(Watcher).GetMethod("Runner", new Type[] { typeof(string) });
il.Emit(OpCodes.Ldstr, "123");
il.Emit(OpCodes.Dup);
il.Emit(OpCodes.Call, methods);
il.Emit(OpCodes.Call, methods);
il.Emit(OpCodes.Ldnull);
il.Emit(OpCodes.Ret);
var ilEmitDeleegate = (Func<object>)method.CreateDelegate(typeof(Func<object>));
ilEmitDeleegate();
```

Here is what `script.CreateDelegate()` does:
https://github.com/dotnet/roslyn/blob/287053625791404a5cbaa89b9047ebdfbfddaf3f/src/Scripting/Core/Script.cs#L474-L485

The additional work of capturing script state is what is accounting for the difference in your benchmarks.  It is unlikely that the script execution engine will ever have zero overhead compared to just executing delegates. Its goal is to allow you to iteratively run code and examine the interstitial state.

**Comment by NMSAzulX** [comment]
@jmarolf Thank you~.Ok, I got it. 
I think the C#Script in runtime is very necessary. Lots of my friends want to use it.  We can build EntitiesMapping or DynamicMethod easily.You know programming with emit is hard for big project.  And the performance of executing script is very sensitive. Like using it in Dapper，EF, Json.net , AutoMapping etc.  I even think this is the foundation for coding .net libraries.
So I hope it is a solution for replacing the emit.  Uhh.....Maybe it is necessary to create an other issue. :)

**Comment by jmarolf** [comment]
@NMSAzulX the scripting APIs were never meant to be a replacement for the reflection/emit apis.  They were designed so a scripting environment could be built atop them.

If you want a simpler API to generate code at runtime, see this example [here](https://github.com/dotnet/roslyn-sdk/blob/37e2a003dfd4308007792c06f3fdaafef909b377/samples/CSharp/APISamples/Compilations.cs#L21-L48).  It uses the compiler APIs to generate an assembly in memory, load the assembly into the current process, and invoke the compiled method.

If that does not meet your needs I would suggest filing a new issue outlining the sort of API you need.

**Comment by tmat** [comment]
@jmarolf I don't think using Roslyn compilation APIs directly will make much difference. The emit overhead when compared to Reflection.Emit is caused by the translation of C# syntax to IL. The overhead of the scripting runtime is insignificant.

**Comment by tmat** [comment]
Also, compiling something some code is one thing, running it is another. If you use Roslyn Emit APIs directly you'll need to handle assembly loading yourself. Trust me, that's not business you wanna be in. The scripting runtime provides an assembly loader.

**Comment by jmarolf** [comment]
@tmat  this benchmark https://github.com/NMSAzulX/RoslynPerfomanceTest is only measuring execution performance

Here is the setup for these actions (which is not measured in the benchmark)
 - [Scripting](https://github.com/jmarolf/RoslynPerfomanceTest/blob/4a86e03a30f297be9f2d5fd9204e3ef0029c51f9/RoslynPerfomance/RoslynTest/Watcher.cs#L31-L40)
 - [Compile](https://github.com/jmarolf/RoslynPerfomanceTest/blob/4a86e03a30f297be9f2d5fd9204e3ef0029c51f9/RoslynPerfomance/RoslynTest/Watcher.cs#L42-L70)
 - [Emit](https://github.com/jmarolf/RoslynPerfomanceTest/blob/4a86e03a30f297be9f2d5fd9204e3ef0029c51f9/RoslynPerfomance/RoslynTest/Watcher.cs#L72-L84)

And here are the results of executing the delegates:
``` ini

BenchmarkDotNet=v0.10.13, OS=Windows 10.0.17134
Intel Xeon CPU E5-1620 0 3.60GHz, 1 CPU, 8 logical cores and 4 physical cores
Frequency=3507173 Hz, Resolution=285.1299 ns, Timer=TSC
  [Host] : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0
  Clr    : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0

Job=Clr  Runtime=Clr  

```
|    Method |      Mean |    Error |   StdDev |
|---------- |----------:|---------:|---------:|
| Scripting | 354.49 ns | 4.101 ns | 3.424 ns |
|   Compile |  58.67 ns | 1.262 ns | 1.964 ns |
|      Emit |  69.81 ns | 1.148 ns | 1.017 ns |

Compiling the method using roslyn APIs should be the same as using the emit API.

___

>If you use Roslyn Emit APIs directly you'll need to handle assembly loading yourself. Trust me, that's not business you wanna be in. The scripting runtime provides an assembly loader.

On this we are in agreement. Assembly loading is hard enough that most people reach for it first until they want to improve performance.

**Comment by tmat** [comment]
I see. There are two problems with this benchmark though:
1) You're not really comparing the same things. Script submissions are async and compile into async state machine, which has some overhead. The Reflection.Emit version above emits very trivial code. 
2) This is a micro-benchmark. The extra overhead scripting has is constant. If the script actually did anything useful it would be likely negligible.

That said we might be able to optimize the code path a bit more.

**Comment by tmat** [comment]
One thing that we could potentially do is to implement `T CSharpScript.CreateDelegate<T>(string code, object globals, ScriptOptions options)`, which would create a synchronous delegate without chaining ability. That would allow us to avoid the overhead.

**Comment by NMSAzulX** [comment]
Thanks @jmarolf !  I think ParseSyntaxTree->Compilation->Load->Execute  is a goot option here. It can solve my problem.   
Thanks @tmat !  Your advice is very useful.  "T CSharpScript.CreateDelegate<T>(string code, object globals, ScriptOptions options)" ，it will be an enhanced API?

**Comment by NMSAzulX** [comment]
But does it only run on x86 platforms? How to use it on x64 pc?

**Comment by jmarolf** [comment]
@NMSAzulX

> It raised a exception: System.BadImageFormatException:“Bad IL format.” How can I avoid it?

There was a compile error and it failed to emit. check the `EmitResult` object that is returned by `compilation.Emit`.  I would guess that you forgot to include a reference to a type, see [here](https://github.com/jmarolf/RoslynPerfomanceTest/blob/b1d3c5bc8922d9f7a166cd27a530c0c399041ba3/RoslynPerfomance/RoslynTest/Watcher.cs#L53-L54) for how that is done.

This is what @tmat  meant when he said:

> If you use Roslyn Emit APIs directly you'll need to handle assembly loading yourself.

Finding and passing in all the references that your code needs to compile is your responsibility with the compilation api.

**Comment by NMSAzulX** [comment]
Thanks @jmarolf ,  I can see this infomation in EmitResult:  error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.  Do I need reference an other Runtime Library?  @tmat  is right.

**Comment by NMSAzulX** [comment]
Thanks @jcouv .  I closed this issue.  :)
