### ISSUE TITLE
How to find the commits ahead after reset --mixed?

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#27784]
There're 4 unpushed commits in vs2017.
![1](https://user-images.githubusercontent.com/2529999/41338466-db46999e-6f24-11e8-872d-3eaf0eeb2bb3.jpg)
Select code2 and reset --mixed.
This time I can reset to code3/code4.
But if I refresh it or reopen vs2017
![2](https://user-images.githubusercontent.com/2529999/41338472-df3f53ba-6f24-11e8-9b56-6249ee09c848.jpg)
there're no code3/code4 in the history. so I can't reset to code3.
I can only commit all, but these codes are irrelated.(code3 implement one function, but code4 implement another irrelated function), so I don't want to commited irrelated codes at the same time.
How can I recover code3(fd5beeb5)/code4(ff95f3fe) in order to commit different function and add comment for every one.

**Comment by jinujoseph** [comment]
finding the right team to redirect

**Comment by CyrusNajmabadi** [comment]
Closing out as this is not roslyn.
