### ISSUE TITLE
why is Restore.cmd downloading dotnet-sdk-2.1.300-rtm-008866-win-x64

### ISSUE THREAD

**Issue by hexbinoct** [dotnet/roslyn#27780]
latest master branch as of June 13 20018: 

**Steps to Reproduce**:

1. when I run restore.cmd, it starts downloading a 150mb file dotnet-sdk-2.1.300-rtm-008866-win-x64, after which it fails. Cant I download it myself so i can build the solution offline please?

**Expected Behavior**:
It should not require downloading of huge files, the prereq should inform the user of what they need to install prior to running Restore.cmd

**Comment by jcouv** [comment]
I think this SDK is mentioned in the [build/test instructions for contributors](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md).

**Comment by abubakarm** [comment]
I have that installed already.
