### ISSUE TITLE
Add integration tests for Fix All operations with preview

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#27806]
As of now (master branch 98a1eabbbfac2e2518da03d96a6be1dac19bd0ab), we have no integration tests for any Fix All operations or the Preview Changes dialog it shows. Tests should be created for these features.

**Comment by CyrusNajmabadi** [comment]
@akhera99 assigning to you.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
