### ISSUE TITLE
In-consistency in the ruleset view and reference view.

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#2781]
If I change the severity by selecting "Set rule set severity" the same is not reflected in the ruleset view.

![ruleset](https://cloud.githubusercontent.com/assets/12449387/7647873/76314c18-fa90-11e4-9b8f-61ffd5ced442.png)

**Comment by srivatsn** [comment]
I think this is because the ruleset editor doesn't refresh when the file changes. @tmeschter has a bug to add an info bar saying the file has changed.

**Comment by jinujoseph** [comment]
@srivatsn  , just want to add that closing the ruleset window and re-opening also doesn't reflect the change.

**Comment by jinujoseph** [comment]
Note: More debugging with srivatsn , reviled that editing the Action from RuleSet view works but editing from the solution explorer doesn’t reflect.
That is because the format in which the ruleset expects the rules are based on RuleNamespace to be binaryname rather than AnalyzerName

Ruleset expects the rules as 

<Rules AnalyzerId="regexanalyzer.dll" RuleNamespace="regexanalyzer.dll">
    <Rule Id="ReqexPattern" Action="Info" />
  </Rules>

Solution explorer adds as 

  <Rules AnalyzerId="RegexAnalyzer" RuleNamespace="RegexAnalyzer">
    <Rule Id="ReqexPattern" Action="Info" />
  </Rules>

And I believe the solution explorer pattern should be the right one

**Comment by tmeschter** [comment]
Then this might simply be another manifestation of #2782.
