### ISSUE TITLE
Analyzer ID being wrong; instead of “microsoft.codeanalysis.analyzers.dll” it should be “Microsoft.CodeAnalysis.Analyzers”.

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#2782]
![analyzerid](https://cloud.githubusercontent.com/assets/12449387/7647959/86c75eea-fa91-11e4-824c-0057516e44fd.JPG)

While looking at some other issue for me , @tmeschter noticed that the Analyzer ID is wrong.

**Comment by tmeschter** [comment]
Fixed by 36a01428629df9b63379e69518bbdb8c06727a10.

**Comment by tmeschter** [comment]
@jinujoseph Assigning back to you for verification. When you've verified this is fixed, please mark the issue with the "Verified" tag. If you run into issues, re-open and re-assign it to me.
