### ISSUE TITLE
New Formatting Document Settings do not get applied to a selection

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27824]
**Version Used**: 
Version 15.8.0 Preview 3.0 [27812.3003.d15.8stg]

**Steps to Reproduce**:

1. File -> New Console App (.NET Framework)
2. Change Program.cs to:

``` C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

class Program
{
$$$
    static void Main(string[] args)
    {
        String foo = (String)args[0];
        
        Console.WriteLine(foo);
    }
$$$
}

```
3. Tools -> Options -> Check all "Format Document Settings (Experimental) and click OK
4. Highlight text between the $$$
5. Choose Edit -> Advanced -> Format Selection

**Expected Behavior**:
``` C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

class Program
{
    private static void Main(string[] args)
    {
        var foo = args[0];

        Console.WriteLine(foo);
    }
}
```

**Actual Behavior**:

It remains the same and nothing happens.

**Comment by sharwell** [comment]
Yes, in the current design it only applies to the **Format Document** command. Other commands, e.g. **Format Selection** or **Save**, are on the roadmap but not yet designed or implemented.

**Comment by sharwell** [comment]
This experimental feature was removed in 16.0
