### ISSUE TITLE
Changing new Formatting Settings do not get applied until you modify an open file

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27823]
**Version Used**: 
Version 15.8.0 Preview 3.0 [27812.3003.d15.8stg]

**Steps to Reproduce**:

1. File -> New Console App (.NET Framework)
2. Change Program.cs to:

``` C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

class Program
{
    static void Main(string[] args)
    {
        String foo = (String)args[0];
        
        Console.WriteLine(foo);
    }
}

```
3. Tools -> Options -> Uncheck all "Format Document Settings (Experimental) and click OK
4. Tools -> Options -> Check all "Format Document Settings (Experimental) and click OK
5. Choose Edit -> Advanced -> Format Document

**Expected Behavior**:
``` C#
using System;

internal class Program
{
    private static void Main(string[] args)
    {
        var foo = args[0];

        Console.WriteLine(foo);
    }
}
```

**Actual Behavior**:

It remains the same and nothing happens. You have to edit the document before Format document will respect the settings

**Comment by sharwell** [comment]
:memo: This was fixed for .editorconfig changes in #27280.

**Comment by sharwell** [comment]
I confirmed that this was also already fixed in the latest master branch for Format Document options. I'm not certain which commit corrected it, so I'm marking it as not reproducible.
