### ISSUE TITLE
Creating analyzer package with referenced assembly

### ISSUE THREAD

**Issue by cincuranet** [dotnet/roslyn#27832]
Is there some story how to create the analyzer package, where the analyzer assembly is referencing some other assembly? Or is it expected the analyzer to always be one dll?

Should it go into directly `analyzers/dotnet/cs` (or similar) (works, but shows as another analyzer dll without any analyzer in it) or into `lib` (seems to cause warnings in VS with package restore).

**Comment by jmarolf** [comment]
current recommendation is to put all analyzer dependencies in `analyzers/dotnet/cs`.  I believe we have a bug somewhere to track the work of not showing assemblies if they do not contain any analyzers.

**Comment by cincuranet** [comment]
Thanks.
