### ISSUE TITLE
New Formatting Document Settings does not respect "Separate using directives groups"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27834]
**Version Used**: 

**Steps to Reproduce**:
1. 
![image](https://user-images.githubusercontent.com/1103906/41403606-9e88e586-7008-11e8-87e2-a6bdcf91f2f1.png)

![image](https://user-images.githubusercontent.com/1103906/41403537-71eb42da-7008-11e8-982a-0eff846638c2.png)

2. Format Document on following:

``` C#
using System;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.VisualStudio.Threading;

internal class Program
{
    private static void Main(string[] args)
    {
        var type = typeof(Enumerable);
        var type2 = typeof(Task);
        var type4 = typeof(Foo);

        Console.WriteLine("Hello World!");
    }
}


namespace Microsoft.VisualStudio.Threading
{
    public class Foo
    {
    }

}
``` 

**Expected Behavior**:
``` C#
using System;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.VisualStudio.Threading;

internal class Program
{
    private static void Main(string[] args)
    {
        var type = typeof(Enumerable);
        var type2 = typeof(Task);
        var type4 = typeof(Foo);

        Console.WriteLine("Hello World!");
    }
}


namespace Microsoft.VisualStudio.Threading
{
    public class Foo
    {
    }

}
```

**Actual Behavior**:
``` C#
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.VisualStudio.Threading;

internal class Program
{
    private static void Main(string[] args)
    {
        var type = typeof(Enumerable);
        var type2 = typeof(Task);
        var type4 = typeof(Foo);

        Console.WriteLine("Hello World!");
    }
}


namespace Microsoft.VisualStudio.Threading
{
    public class Foo
    {
    }

}
```

Formatting Document should be equivalent to choosing Remove and Sort Usings.

**Comment by sharwell** [comment]
@JieCarolHu I'm unsure if this is a bug or a feature request

**Comment by davkean** [comment]
We ended up turning this feature off - we wanted to use it but doesn't work in lots of situations and you end up fighting with it:

https://github.com/dotnet/roslyn/issues/27834
https://github.com/dotnet/roslyn/issues/36984

**Comment by davkean** [comment]
https://github.com/dotnet/project-system/pull/5500

**Comment by sharwell** [comment]
The application of full code style formatting has been removed from the Format Document command, so this issue is no longer relevant to product code. See #36984 for an updated issue.
