### ISSUE TITLE
Visual Studio: Format document options

### ISSUE THREAD

**Issue by TheOtherTimDuncan** [dotnet/roslyn#27842]
For the new Format Document options coming out in VS 2017 15.8 preview 3, regarding the option to automatically apply "Remove unused usings", could we include the option to whitelist certain usings so they don't get removed even if unused?

I would consider this a resolution for https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/18647317-bring-back-sort-usings-as-a-separate-option-in-v. 

Reference: https://twitter.com/davkean/status/1007151326784995328

**Comment by sharwell** [comment]
:bulb: "Sort usings" is separate from "Remove unused usings" in this feature.

**Comment by CyrusNajmabadi** [comment]
Not sure what is needed here, and we've heard nothing since this.  Closing out.
