### ISSUE TITLE
System.ArgumentException at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.HostDiagnosticUpdateSource.RaiseDiagnosticsUpdatedForProject

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2784]
**Dump shared at:**
`\\manish-test\share_r\ImmutableArray_ArgumentException\devenv.dmp`

**Message:** `Value does not fall within the expected range`

**Call stack:**
> 	[Managed to Native Transition]	
 	mscorlib.dll!System.RuntimeTypeHandle.GetTypeByName(string name, bool throwOnError, bool ignoreCase, bool reflectionOnly, ref System.Threading.StackCrawlMark stackMark, System.IntPtr pPrivHostBinder, bool loadTypeFromPartialName)	Unknown
 	mscorlib.dll!System.RuntimeType.GetType(string typeName, bool throwOnError, bool ignoreCase, bool reflectionOnly, ref System.Threading.StackCrawlMark stackMark)	Unknown
 	mscorlib.dll!System.Type.GetType(string typeName)	Unknown
 	Evaluation of: Unknown evaluation	
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler) Line 152	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetAsync() Line 102	C#
 	[Resuming Async Method]	
 	[Native to Managed Transition]	
 	System.Collections.Immutable.dll!System.Collections.Immutable.ImmutableExtensions.ToArray<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData>(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData> sequence, int count) Line 110	C#
 	System.Collections.Immutable.dll!System.Collections.Immutable.ImmutableArray.CreateRange<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData>(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData> items) Line 137	C#
>	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ImmutableArrayExtensions.AsImmutableOrEmpty<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData>(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData> items) Line 45	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.HostDiagnosticUpdateSource.RaiseDiagnosticsUpdatedForProject(Microsoft.CodeAnalysis.ProjectId projectId, object key, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData> items) Line 39	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.HostDiagnosticUpdateSource.UpdateDiagnosticsForProject(Microsoft.CodeAnalysis.ProjectId projectId, object key, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData> items) Line 61	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioAnalyzer.OnAnalyzerLoadError(object sender, Microsoft.CodeAnalysis.Diagnostics.AnalyzerLoadFailureEventArgs e) Line 120	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference.GetAnalyzersForTypeNames(System.Reflection.Assembly analyzerAssembly, System.Collections.Generic.IEnumerable<string> analyzerTypeNames, ref bool reportedError)	Unknown
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference.AddAnalyzers(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>.Builder builder, string language)	Unknown
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference.CreateLanguageSpecificAnalyzers(string langauge, Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference reference)	Unknown
 	System.Collections.Immutable.dll!System.Collections.Immutable.ImmutableInterlocked.GetOrAdd<string, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>, Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference>(ref System.Collections.Immutable.ImmutableDictionary<string, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>> location, string key, System.Func<string, Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>> valueFactory, Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference factoryArgument) Line 170	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference.GetAnalyzers(string language)	Unknown
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.HostAnalyzerManager.CreateDiagnosticAnalyzersPerReferenceMap(System.Collections.Generic.IDictionary<string, Microsoft.CodeAnalysis.Diagnostics.AnalyzerReference> analyzerReferencesMap, string languageOpt) Line 371	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.HostAnalyzerManager.CreateProjectDiagnosticAnalyzersPerReference(Microsoft.CodeAnalysis.Project project) Line 165	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateManager.ProjectStates.CreateAnalyzerMap(Microsoft.CodeAnalysis.Project project) Line 132	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateManager.GetOrCreateStateSets(Microsoft.CodeAnalysis.Project project) Line 81	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetAsync() Line 68	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.TryAppendDiagnosticsForSpanAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan range, System.Collections.Generic.List<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData> diagnostics, System.Threading.CancellationToken cancellationToken) Line 457	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.IncrementalAnalyzerDelegatee.TryAppendDiagnosticsForSpanAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan range, System.Collections.Generic.List<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData> diagnostics, System.Threading.CancellationToken cancellationToken) Line 167	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.TryAppendDiagnosticsForSpanAsync.AnonymousMethod__0() Line 84	C#
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task<bool>>.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown

**Comment by srivatsn** [comment]
I think @heejaechang fixed this a couple of days ago. HeeJae?

**Comment by heejaechang** [comment]
@mavasani are you using latest bits? AbstractHostDiagnosticUpdateSource wasn't thread safe and got corrupted when called from background thread. not sure whether you have a bit that has fix or not.

**Comment by srivatsn** [comment]
@mavasani - this is likely fixed by HeeJae. Closing this bug - if this crash was repro'able or if you see this happen again please reactivate.

**Comment by mavasani** [comment]
@srivatsn @heejaechang I am on a slightly older signed build. I'll move to a newer build today and re-open this if it repros again.
