### ISSUE TITLE
Request: Support emitting structured data (for third-party tooling)

### ISSUE THREAD

**Issue by Phrohdoh** [dotnet/roslyn#27840]
Original ticket: https://github.com/dotnet/cli/issues/9486

---

This is a very general, wide-reaching request.

I envision an invocation similar to the following:

```shell
$ dotnet build --message-format json
```

Which, upon error CS0539 (for example), would emit such a structure:

```
{
    "status": "error",
    "errors": [{
        "code": "CS0539",
        "message": "The type or namespace 'Foo' could not be found",
        "notes": [{ // can be used for things like "X is already declared <here>"
            "message": "Are you missing a using directive or an assembly reference?",
            "origin": null,
        }],
        "origin": {
            "relative_file_path": "rel/path/to/file.cs",
            "absolute_file_path": "/home/foo/foobar/rel/path/to/file.cs",
            "span": { // a byte range
                "start": 123,
                "end": 456
            }
        }
    }]
}
```

The resulting structured data could be used by foundation- and community-built tooling for many things (one example is error messages that include source code).

This request is inspired by [`cargo`](https://github.com/rust-lang/cargo) `--message-format` functionality.

I fully realize that this is a *very large* request and the above structure is a minimal, illustrative example.

**Comment by bkoelman** [comment]
Most of that can be built by invoking the compiler API from a console app and query compiler diagnostics, which returns a collection of [structured data](http://source.roslyn.io/#Microsoft.CodeAnalysis/Diagnostic/Diagnostic.cs,18). Example usage: https://github.com/bkoelman/RoslynTestFramework/blob/master/AnalysisTestFixture.cs#L93

**Comment by jmarolf** [comment]
@Phrohdoh there is already the [binary log format](https://github.com/Microsoft/msbuild/wiki/Binary-Log) which is built into MSBuild.  There is at least one viewer built on top of this format (http://msbuildlog.com/#features).

**Comment by Phrohdoh** [comment]
Actually, upon further investigation the [binary log format](https://github.com/KirillOsenkov/MSBuildStructuredLog) advertises itself as "A logger for MSBuild that records a structured representation of executed targets, tasks, property and item values." which does not, apparently, cover compilations errors, warning, etc.

**Comment by jmarolf** [comment]
> which does not, apparently, cover compilation errors, warning, etc.
@Phrohdoh it does cover these cases, all this info is given to MSBuild by the compiler and it included in the binlog
