### ISSUE TITLE
NavigateToItemProvider hurts Go To File performance by providing irrelevant results

### ISSUE THREAD

**Issue by olegtk** [dotnet/roslyn#27850]
**Version Used**: 
27813.1 d15.8 (latest dogfood build) 

**Steps to Reproduce**:

1. Open big solution like Rolslyn
2. Invoke Go To File (Ctrl+Shift+T)
3. Type a file name to find

**Expected Behavior**:
Matching file names displayed and search has finished

**Actual Behavior**:
Matching file names displayed but search progress bar is going on because Roslyn's NavigateToItemProvider doesn't realize user is searching for a file and provides symbol results, whoch are being silently ignored.

The fix is to implement INavigateToItemProvider2, which lets providers express what kind of search they support and know what kind of search user initiated.

**Comment by CyrusNajmabadi** [comment]
Can you link to docs on INavigateToItemProvider2?  The docs.microsoft.com stuff doesn't explain at all how you would use it...

**Comment by CyrusNajmabadi** [comment]
Dumb question: if the user is doing "search for file" why is a language provider even loaded?  Wouldn't all language providers basically just check and bail out?  Why not have it be that in that case, only teh single actual file-searcher gets run?

**Comment by olegtk** [comment]
So with INavigateToItemProvider there is no way to know that user only searches files. We added filters only in INavigateToItemProvider2. It was probably a mistake to still call INavigateToItemProvider providers on a filtered search and just throw away non-relevant results...
Yeah, MSDN docs are broken, I filed a bug for the doc team to update it.
Here it is:
```csharp
    /// <summary>
    /// Extends INavigateToItemProvider with filtering functionality.
    /// </summary>
    public interface INavigateToItemProvider2 : INavigateToItemProvider
    {
        /// <summary>
        /// Lists the kinds this provider will possibly return.  This will be used
        /// to optimize the filtering by avoiding even calling the provider to
        /// search if it knows that nothing will be returned.
        /// </summary>
        ISet<string> KindsProvided { get; }

        /// <summary>
        /// The provider has the ability to filter itself and will only return
        /// items matching the filtering parameters.  The provider will be called
        /// with the <see cref="StartSearch"/> overload with the <see cref="INavigateToFilterParameters"/>
        /// parameter.
        /// </summary>
        bool CanFilter { get; }

        /// <summary>
        /// Indicates that the provider should begin a new search.
        /// If the provider is in the middle of a search, it should be
        /// terminated as soon as possible as the results of that search will
        /// now be ignored.
        /// Implementations of this method should move all work to a separate
        /// thread and allow this call to return as soon as possible.
        /// </summary>
        /// <param name="callback">A callback specific to this search.</param>
        /// <param name="searchValue">The search query string.</param>
        /// <param name="filter">
        /// A filter specific to this search. The callback should not receive items
        /// blocked by the filter.
        /// </param>
        void StartSearch(INavigateToCallback callback, string searchValue, INavigateToFilterParameters filter);
    }
```
Where predefined kinds are defined in https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.navigateto.interfaces.navigatetoitemkind

**Comment by CyrusNajmabadi** [comment]
>  It was probably a mistake to still call INavigateToItemProvider providers on a filtered search and just throw away non-relevant results...

Can we fix that mistake instead ? :)

**Comment by CyrusNajmabadi** [comment]
Can you show the docs for: INavigateToFilterParameters 

Thanks!

**Comment by olegtk** [comment]
hmm, what happened to our MSDN docs, lots of interfaces are without any text.

```csharp
    /// <summary>
    /// Defines Navigate To search filtering parameters.
    /// </summary>
    public interface INavigateToFilterParameters
    {
        /// <summary>
        /// The search will only add a <see cref="NavigateToItem"/> if the <see cref="NavigateToItemKind"/>
        /// is contained within this collection or if the collection is empty.
        /// </summary>
        ISet<string> Kinds { get; }
    }
```

**Comment by olegtk** [comment]
> It was probably a mistake to still call INavigateToItemProvider providers on a filtered search and just throw away non-relevant results...

> Can we fix that mistake instead ? :)

Possibly in VS.next, too late in 15.8

**Comment by CyrusNajmabadi** [comment]
vs.next seems fine.  It looks like the right fix to apply.  And it means you don't need *every single provider* to have to make the fix that Roslyn is about to have to make themselves.
