### ISSUE TITLE
Pattern matching should decide on how to deal with restricted types

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#27851]
A recent bug (#27803) revealed how pattern matching interacts with restricted types in interesting ways (when doing type checks).
We should discuss with LDM on whether this should be banned (like pointer types), and if there are actual use cases that need it.

**Comment by OmarTawfik** [comment]
cc @gafter

**Comment by gafter** [comment]
Added the following to https://github.com/dotnet/csharplang/issues/1054
### Restricted types

A recent bug (https://github.com/dotnet/roslyn/pull/27803) revealed how pattern matching interacts with restricted types in interesting ways (when doing type checks).
We should discuss with LDM on whether this should be banned (like pointer types), and if there are actual use cases that need it.
