### ISSUE TITLE
[Bug] Implement interface through static member referred wrong member name in generic classes

### ISSUE THREAD

**Issue by CnSimonChan** [dotnet/roslyn#2785]
I'm using Visual Studio 2015 RC.

**Code example:**

```` C#
class Issue2785<T> : IList<object>
{
    private static List<object> innerList = new List<object>();
}
````

**Note:**

1. The class must be a generic class.
2. The member must be a static field or property.

**Steps:**

1. Put caret on `IList<object>`.
2. Press `Ctrl + .`, choose `Implement interface through "innerList"` menu item.

**What happened:**

Visual Studio generates code using `Issue2785.innerList` to refer this member, causes code failed to compile (missing generic type arguments).

**What should happen:**

Visual Studio uses `innerList` to refer this member, when this member is not static or this class is not generic, Visual Studio will do it correctly.

**Another question:**

When uses "Implement interface explicitly", Visual Studio generates code for members already implemented implicitly, is it a bug or by design?

**Comment by Pilchie** [comment]
@JohnHamby: Can you take a look at the generation of the member?  For the extra question, it's by design that implement explicitly generates members that have already been implemented implicitly.

**Comment by jmarolf** [comment]
@dpoeschl could you verify please?
