### ISSUE TITLE
Roslyn in memory compilation: adding metadata reference to System does not solve System.Console

### ISSUE THREAD

**Issue by RaicuRobert** [dotnet/roslyn#27899]
Sorry from the start for the bad formatting. I do not know how to resolve the problem with the code section and strings.

So i'm having this problem.

I'm trying to compile code in memory and adding namespace references by searching the syntax tree so i do not add them manually. Trying to simulate how Visual Studio maybe does it.

I'm a bit over my head in the compilation department. Even if i add a metadata reference to System while reading the syntax tree it does not find System.Console.

The key is that i want it to include the assemblies by itself, i do not want to add a "MetadataReference.CreateFromFile(....,"System.Console").

I explained the code below so that is clear what is happening.

**Version Used**: 
dotnet-sdk-2.1.300-preview2-008324-win-x64
**Steps to Reproduce**:
Run the code

```C#
class App
{
    static void Main(string[] args)
    {
        //creating the syntax tree for the program
        SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(@"
            namespace ns{
                using System;
                public class App{
                    public static void Main(string[] args){
                        Console.Write(""dada"");
                    }
                } }");

        //creating options that tell the compiler to output a console application
        var options = new CSharpCompilationOptions(
           OutputKind.ConsoleApplication,
           optimizationLevel: OptimizationLevel.Debug,
           allowUnsafe: true);

        //creating the compilation
        var compilation = CSharpCompilation.Create(Path.GetRandomFileName(), options: options);

        //adding the syntax tree
        compilation = compilation.AddSyntaxTrees(syntaxTree);

        //getting the local path of the assemblies
        var assemblyPath = Path.GetDirectoryName(typeof(object).Assembly.Location);
        List<MetadataReference> references = new List<MetadataReference>();
        //adding the core dll containing object and other classes
        references.Add(MetadataReference.CreateFromFile(Path.Combine(assemblyPath, "System.Private.CoreLib.dll")));

        //gathering all using directives in the compilation
        var usings = compilation.SyntaxTrees.Select(tree => tree.GetRoot().ChildNodes().OfType<UsingDirectiveSyntax>()).SelectMany(s => s).ToArray();

        //for each using directive add a metadatareference to it
        foreach (var u in usings)
        {
            references.Add(MetadataReference.CreateFromFile(Path.Combine(assemblyPath, u.Name.ToString() + ".dll")));
        }

        //add the reference list to the compilation
        compilation=compilation.AddReferences(references);

        //compile
        using (var ms = new MemoryStream())
        {
            EmitResult result = compilation.Emit(ms);

            if (!result.Success)
            {
                IEnumerable<Diagnostic> failures = result.Diagnostics.Where(diagnostic =>
                    diagnostic.IsWarningAsError ||
                    diagnostic.Severity == DiagnosticSeverity.Error);

                foreach (Diagnostic diagnostic in failures)
                {
                    Console.Error.WriteLine("{0}: {1}, {2}", diagnostic.Id, diagnostic.GetMessage(), diagnostic.Location);
                }
            }
            else
            {
                ms.Seek(0, SeekOrigin.Begin);
                AssemblyLoadContext context = AssemblyLoadContext.Default;
                Assembly assembly = context.LoadFromStream(ms);
                assembly.EntryPoint.Invoke(null, new object[] { new string[] { "arg1", "arg2", "etc" } });

            }
        }
    }
}
```

**Expected Behavior**:
Console app outputing dada
**Actual Behavior**:
CS0103: The name 'Console' does not exist in the current context

**Comment by jmarolf** [comment]
The following code will not work because `ChildNodes()` only returns the immediate children of a node, not all descendant children.

```C#
var usings = compilation.SyntaxTrees.Select(tree => tree.GetRoot().ChildNodes().OfType<UsingDirectiveSyntax>()).SelectMany(s => s).ToArray();
```

Instead use `DescendantNodes()`

```C#
var usings = compilation.SyntaxTrees.Select(tree => tree.GetRoot().DescendantNodes().OfType<UsingDirectiveSyntax>()).SelectMany(s => s).ToArray();
```

This will still not fix your problem.  `Console.Write()` is located in `System.Console.dll` but thats only if you want to target .NET core 2.1. You cannot guess the assembly reference locations from the using statements.

> The key is that i want it to include the assemblies by itself, i do not want to add a "MetadataReference.CreateFromFile(....,"System.Console").

Can you explain why you cannot do this?

**Comment by RaicuRobert** [comment]
Having "using System" in code and in Main "Console.Write()" i want to achieve something similar to how vs compiles in the sense that it automatically finds the reference to Console. I am not that familiar to assemblies.

Would it work if i store the original references from code then for each one add it's children? Is there a better solution?

**Comment by svick** [comment]
> i want to achieve something similar to how vs compiles in the sense that it automatically finds the reference to Console

As far as I can tell, what VS does is to rely on MSBuild (which in turn relies on the .Net Core SDK) to figure out what assemblies to reference. It certainly doesn't search for references based on what's in your code.

And specifically for .Net Core 2.1, it seems reference assemblies are found in [the Microsoft.NETCore.App package](https://www.nuget.org/packages/Microsoft.NETCore.App), which can be found on disk on Windows in C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1.

**Comment by jaredpar** [comment]
> As far as I can tell, what VS does is to rely on MSBuild (which in turn relies on the .Net Core SDK) to figure out what assemblies to reference. It certainly doesn't search for references based on what's in your cod

This is correct. 

> The key is that i want it to include the assemblies by itself, i do not want to add a "MetadataReference.CreateFromFile(....,"System.Console").

This is going to be required though. The compiler itself needs this reference in order to successfully compile this scenario. If it's not added then the code will fail (as it should).
