### ISSUE TITLE
csharp_preferred_modifier_order differs to visual_basic_preferred_modifier_order

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27894]
Is it by design that `visual_basic_preferred_modifier_order` differs to `csharp_preferred_modifier_order`?

In particular, `csharp_preferred_modifier_order` doesn't list "Partial" whereas `visual_basic_preferred_modifier_order` lists it first, resulting in different orders (C# lists it last, VB lists is first).

**Comment by CyrusNajmabadi** [comment]
Yes.  This was by design.  Due to previous versions of the VB editor putting the partial modifier first, whereas C# (unless it recently changed) has always required it right before the type-specifier (i.e. class/interface/struct).

**Comment by sharwell** [comment]
@kuhlenh @DustinCampbell This already went through a design review and reached the current conclusion. Please reopen if you'd like to bring a change proposal for review.
