### ISSUE TITLE
Roslyn does not issue CS1684 warning for incorrect types contract

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#279]
Repro files: http://s000.tinyupload.com/?file_id=71495172019288651030

Compile files as test-912.cs -r:test-912-lib.dll -r:test-912-lib-missing.dll

Native csc result:

test-912-lib.dll: warning CS1684: Reference to type 'IFoo' claims it is defined in 'test-912-lib-missing.dll', but it could not be found

Managed csc result:
--no warning or error--

**Comment by VSadov** [comment]
This seems ByDesign. The type in the first dll claims to implement an interface in the second, but that interface does not exist. C# spec does not prescribe any particular way of handling invalid metadata. Typically compiler gives errors on invalid metadata when it discovers issues. However compiler does not try to aggressively validate all metadata, especially parts that it is not using (or not even loading).
That, unfortunately, may lead to implementation specific behavior in cases where one compiler is more eager than another when it comes to metadata loading/analyzing. 
I am not sure there is an easy way around this without requiring compiler to do comprehensive metadata validation and there are better tools for that, like PEVerify.
