### ISSUE TITLE
ObjectNotFound Exception while installing nuget package 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#2791]
![exception](https://cloud.githubusercontent.com/assets/12449387/7657071/ea581dc6-fae3-11e4-9cd5-280cb829f964.png)

I created a nugget package ( for an analyzer and codefix) and copied to C:\Nuget. Installation , analysis and codefix all works as expected but while installing it throw this ObjectNotFound exception.

**Comment by jinujoseph** [comment]
@srivatsn helped debug this and we found that foreach loop (Get-ChildItem $languageAnalyzersPath ) in install.ps1 assumes that there will be separate language specific folders, and in absence of finding one it fails.

**Comment by jmarolf** [comment]
Fixed with internal changeset  1474285

**Comment by jmarolf** [comment]
@jinujoseph could you please verify?
