### ISSUE TITLE
Intellisense highlights wrong parameter in attribute when it contains a params in constructor and a property

### ISSUE THREAD

**Issue by mikkelbu** [dotnet/roslyn#27921]
**Version Used**: 
Visual Studio 15.6.7

**Steps to Reproduce**:

Given the following program
```csharp
  [MyAttribute(1, "Hello", "World")]
  public class Class1
  {
    MyAttribute t = new MyAttribute(2, "f", "g");
  }

  [AttributeUsage(AttributeTargets.Class)]
  public class MyAttribute : Attribute
  {
    public Type[] AffectedTypes;

    public int Priority { get; }

    public string[] Names { get; }

    public MyAttribute(int priority, params string[] names)
    {
      Priority = priority;
      Names = names;
    }
  }
```

**Expected Behavior**:
That `"World"` and `"g"` highlights the parameter `params string[] names`.

**Actual Behavior**:
`"g"` correctly highlights the parameter `params string[] names`, but `"World"` wrongly highlights `[AffectedTypes = Type[]]` (probably due to the property).
![image](https://user-images.githubusercontent.com/1007631/41488900-4580191e-70ee-11e8-95ee-41c35d11eb8d.png)

If more arguments are added to the attribute then nothing is highlighted.
![image](https://user-images.githubusercontent.com/1007631/41488907-4c4655ce-70ee-11e8-851c-4c1ee624cc0a.png)

**Comment by jhinder** [comment]
This is a duplicate of #13067.

**Comment by mikkelbu** [comment]
@jhinder You are right. I did several searches for an existing issue before creating this, but did not find any. I'm closing this.
