### ISSUE TITLE
Change the span for "Unnecessary Parentheses" diagnostic

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#27925]
In the code style setting we're adding, we currently squiggle only the first parenthesis:
![image](https://user-images.githubusercontent.com/1402694/41491975-09b0f9fe-70b1-11e8-8c73-0fa4fa578752.png)

This UX is hard to see (because it is so small) and looks like a mistake (sort of a dead pixel vibe). Instead, can we squiggle the entire expression, e.g.,  `(a < b)`?

**Comment by CyrusNajmabadi** [comment]
> Instead, can we squiggle the entire expression, e.g., (a < b)?

1. The expression may be *very large*.
2. That could likely make it seem as if all parts of the expression are not relevant and can be removed.  

I'm wary of this.  Could you show what this would actually look (esp. with large expressions) so we can make some more informed decisions here?

**Comment by CyrusNajmabadi** [comment]
As an example:

```c#
var v = (from x in y
         ...
         select ...);
```

Do we really want that entire query expression to be faded out?

--

One nice thing about the current treatment is that it's *mild*.  Meaning people can ignore it without much of an impact on their day-to-day coding.  If you make it severe, it will rise to the level of 'seriously annoying', and will make it so that people don't even want the feature on at all...

**Comment by kuhlenh** [comment]
@CyrusNajmabadi Couple things:
- Only the parentheses should be faded **not** the entire expression (only the parentheses are *unnecessary*).
- If you want it to be subtle, you would set it to suggestion and only the first two characters will have dots. If you set it to an error, it should be obvious where the error is (especially when errors break your build).

**Comment by CyrusNajmabadi** [comment]
Ah, you specifically mean the span for *just* the squiggles.  Sorry, i missed that.  I would be fine with trying out your approach :)

**Comment by kuhlenh** [comment]
Yes! Apologies for any confusion
