### ISSUE TITLE
NullReferenceException in ParameterSymbolAdapter.cs

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#2793]
We've gotten a report of a crash (DevDiv 1167553) on the following line of `ParameterSymbolAdapter.cs` (line 73)
```cs
       if (constant.SpecialType != SpecialType.None)
```
This appears to be a bug in `PEParameterSymbol`.  It overrides both `HasMetadatConstantValue` and `ExplicitDefaultConstantValue`.  The former should never return `true` unless the latter is guaranteed to return a non-`null` value.  The base implementation explicitly checks for this but the override does not and hence we end up with a NRE in this method.

**Comment by gafter** [comment]
CC @jasonmalinowski

**Comment by tmat** [comment]
@gafter What kind of bad metadata is involved? Could it be written in IL?

**Comment by agocke** [comment]
@tmat The mini dumps weren't super helpful, but it looked like the HasDefault flag was specified in metadata, but there was no row in Constants table. Can't be sure because there was a fair amount of missing information.

**Comment by tmat** [comment]
@agocke I think that case can be easily constructed in ILASM.

**Comment by agocke** [comment]
@tmat Can it? My copy of the spec says

>Reserved flags (cannot be set explicitly; mask 0xF000):
>* [no ILASM keyword\] (0x1000) The parameter has an associated Constant record

**Comment by tmat** [comment]
oh, ok then :)

**Comment by gafter** [comment]
@AlekseyTs Assigning to you as you offered to investigate and prepare a fix.

**Comment by AlekseyTs** [comment]
@gafter Please verify.
