### ISSUE TITLE
List of anonymous tuple peek defintion goes to struct

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27936]
When declaring a List of anonymous tuple; if I initialize it with members, go to definition no longer works. It takes me to the definition of the Tuple

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/270855/list-of-anonymous-tuple-peek-defintion-goes-to-str.html
VSTS ticketId: 631815_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
![image](https://user-images.githubusercontent.com/1408396/41611219-d2ddfa92-73b4-11e8-9720-cf00301cad2f.png)

**Comment by CyrusNajmabadi** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/29523
