### ISSUE TITLE
csharp_style_conditional_delegate_call in editorconfig only working on true value

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27937]
I have the following setting in my editorconfig

`csharp_style_conditional_delegate_call = false:warning`

I expect the use of conditional delegate calls to have a warning and a quick action to change to an explicit null check with ternary. Actual result is that I do not receive any warning in the following code. 

`MyEvent?.Invoke();`

If changed to suggestion or error, it also does not display any suggestions/errors.

However, if the setting is set to

`csharp_style_conditional_delegate_call = true:warning`

or any other severity level, the following code does successfully get style enforced and a quick action appears.

`if ( null != ManagersInitializedEvent )
{
	ManagersInitializedEvent();
}`

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/265757/csharp-style-conditional-delegate-call-in-editorco.html
VSTS ticketId: 625519_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
> `if ( null != ManagersInitializedEvent ) { ManagersInitializedEvent(); }`

This buggy code is the reason why `false` isn't an enforced value. I've marked this for design review, but I'm going to recommend against implementing this feature for the following reasons:

1. This is an area people are known to implement incorrectly using C# 6 (or earlier).
2. The request can already be enforced by setting `LangVersion` to C# 6 (or earlier).
3. The analyzer APIs allow this logic to be implemented rather easily to create a custom code style solution.

**Comment by sharwell** [comment]
Tentatively marked **By Design** since the current behavior was not unintentional; will update with discussion outcome following design review.

**Comment by sharwell** [comment]
This went to a design review 22 June 2018. The conclusion from the review was the following:

> By principle, we don’t want to enforce people in the opposite direction away from using new language features. We will need to update the documentation to make it clear that these unilateral options exist and that in those cases, `false:<anything>` has the same behavior.

Based on the review, I'm changing this to a documentation bug.
