### ISSUE TITLE
Refactoring parameter order with delegate as argument could change program semantics

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27935]
When refatoring the parameter order of a method (&quot;F&quot;) which is passed as a delegate parameter to another method (&quot;G&quot;), Visual Studio does not attempt any refactoring at the parameter site.

Given the above, in the case where the refactor causes the type signature to change (that is, the types of the reordered parameters differ), a compiler error occurs as expected, as the type signature of method &quot;F&quot; has changed and no longer matches the type signature required by the parameter of method &quot;G&quot;. (This is expected.)

However, in the case where the factor does NOT cause the type signature to change (that is, the types of the reordered parameters are equal), a compiler error is NOT generated and (potentially) different semantics without the developer being aware!

In this case, I recommend the delegate should be replaced with an eta-expanded lambda method with the previous order of parameters at the parameter site (or some other corrective action making the developer aware of the problem).

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/270388/refactoring-parameter-order-with-delegate-as-argum.html
VSTS ticketId: 631532_
_These are the original issue comments:_

Kyle D. Blocher on 6/13/2018, 00:38 PM (3 days ago): <p>I submitted lots of detailed information (video recording, solution file, test results, etc.) with this report. I cannot see it from here - did it get lost?</p>

_These are the original issue solutions:_
(no solutions)

**Comment by kdblocher** [comment]
Does the development team still have access to the repro case / video / code that was posted at https://developercommunity.visualstudio.com/content/problem/270388/refactoring-parameter-order-with-delegate-as-argum.html ? If not, I can provide it again here.

By the way, the problem here is a symptom of a general problem: Roslyn does not seem to consider eta-expansions of lambda expressions for refactoring.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and high complexity of suggestion.
