### ISSUE TITLE
CanReplaceDelegateWithLocalFunction doesn't handle equivalent type parameters

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#27950]
**Version Used**: Master with #23465 merged

The following unit test reproduces this issue:

https://github.com/dotnet/roslyn/blob/44e67c5796d99ff0dccda995063e0f1092b9cd6f/src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs#L2095-L2134

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
