### ISSUE TITLE
Code fix for 'if' statement can be simplied produces incorrect code with yield return

### ISSUE THREAD

**Issue by smitpatel** [dotnet/roslyn#27960]
```C#
using System;
using System.Collections.Generic;

namespace YieldReturn
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }

        public static IEnumerable<string> GetStrings(int value)
        {
            if (value % 2 == 0)
            {
                yield return "Even";
            }

            yield return "Number";
        }
    }
}
```
![image](https://user-images.githubusercontent.com/1528107/41551702-8701e602-72e1-11e8-9ae3-b9d34cfe5223.png)

**Expected Behavior**:
`yield return value % 2 == 0 ? "Even" : "Number";`
**Actual Behavior**:
`return value % 2 == 0 ? "Even" : "Number";`

**Version Used**: 
VS 15.8.0 Preview 3.0 27813.1.d15.8

**Comment by CyrusNajmabadi** [comment]
Fascinating.  I wonder if this is expected.  @mavasani I'm using IOperation here.  Is it expected that you get an IReturnOperation for "yield return" statements?

Thanks!

**Comment by CyrusNajmabadi** [comment]
Ah, i see.  There are three 'kinds' that you can get with IReturnOperation ('return', 'yieldreturn' and 'yieldbreak').  Should be a simple fix.

**Comment by CyrusNajmabadi** [comment]
Note: there are two 'reasonable' fixes here.

1. just don't offer the feature.  super simple to do if these are IReturnOperations without the right kind.
2. offer the feature, but intelligently generate ```yield return ...``` if both return statements are the ```yield reutrns```.

**Comment by smitpatel** [comment]
I would prefer combine if both are yield else no suggestion.

**Comment by CyrusNajmabadi** [comment]
@smitpatel Yup.  That's what my PR does.  Cheers! :)
