### ISSUE TITLE
In FolderView : Comment Out Selected Lines Does Not Work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27965]
In both C# and VB.NET, I cannot comment out selected lines, either by keyboard shortcut (Ctrl+K, Ctrl+C) or by menu button/command.  I also cannot format the document, again either by keyboard shortcut (Ctrl+K, Ctrl+D) or by menu button/command.

I am running Visual Studio Enterprise 2017 15.1 (26403.3) on an x64 machine, Windows 10 1703 (15063.138).

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/43554/comment-out-selected-lines-does-not-work.html
VSTS ticketId: 418523_
_These are the original issue comments:_

Skyler Sedate on 4/12/2017, 00:32 PM (432 days ago): <p>I realize now that I was in "Folder View", even though I had the code file open and was editing it.  Once I opened the solution, everything started working as expected.  Not sure if this is a bug, or a feature.</p>

Visual Studio Team on 4/14/2017, 02:28 PM (429 days ago): Thank you for your feedback! This is expected behaviour ...Designer category doesn't work very well in folder view. Adding the request in our backlog to see if we can improve the experience.

rymorris [MSFT] on 5/7/2018, 01:53 PM (41 days ago): Ctrl-k, Ctrl-c is not working on C# files to comment the selection.
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
Repro steps 

- Create a console Application ( .net core)
- Make sure Comment/Uncomments are working 
- Close the solution 
- Open the same via File -> Open -> Folder 
- check if comment/Uncomment works 

Actual 
- Currently its not working

**Comment by aguayUmbt** [comment]
I've got the same problem : I can't comment or uncomment code or format it.
I'm working with a web app .net core 2.0, and sometimes when i'm working inside of views my comment function stop working. however when i'm in a controller or a model it seems it's always fine, I've got no problem at all.
On this picture I can format or comment
![image](https://user-images.githubusercontent.com/39703106/43798973-2613f8da-9a5a-11e8-8e6d-372602834767.png)
But on the second I can't, note the line that disapear..
![image](https://user-images.githubusercontent.com/39703106/43799006-3f25df64-9a5a-11e8-8164-6b6bd716d522.png)

**Comment by jtpolizzi** [comment]
I have a similar issue - but with C#.  The comment / uncomment shortcut keys (or when selected from the menu) don't work in C# - but they DO work with typescript, SQL, etc.

Also - Format Document doesn't work

**Comment by CyrusNajmabadi** [comment]
FormatDocument would potentially be hard to provide (unless you have a .editorconfig), because it's not clear what formatting options should be used.  Comment/Uncomment should be allowed though.

**Comment by CyrusNajmabadi** [comment]
@jinujoseph I don't repro this myself.  Even when i open a C# file from "Open Folder" i.e.:

![image](https://user-images.githubusercontent.com/4564579/43939191-27ecb664-9c1d-11e8-8bbd-aae0181435c6.png)


I'm still able to comment/uncomment selected lines.

**Comment by aguayUmbt** [comment]
I've always open my project with Open -->  folder I don't think it matters

**Comment by mayoevelyn** [comment]
This is still an issue. Oddly, in 'Quick Actions' window, I can see that my code is commented! Just not in the real code.

**Comment by nevsaynev** [comment]
I'm seeing the same issue of today 2020/10/19. Any suggestion on how to recover?

**Comment by GalGreenfield** [comment]
Still an issue in Community Edition in 2022 for me.

**Comment by phochstrasser** [comment]
> Still an issue in Community Edition in 2022 for me in the editor.

same for me.

**Comment by CyrusNajmabadi** [comment]
Closing out as no repro for c#.  If you're having an issue with another language (likke teh javascript examples above), then that's not roslyn.
