### ISSUE TITLE
Double-click doesn't select the whole word

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#27963]
**Version Used**: 15.8.0 Preview 3.0 [27817.0.d15.8]
AKA Microsoft Visual Studio Enterprise 2017 Int Preview updated as of 2018-06-18

**Steps to Reproduce**:

1. Double-click over the middle of an identifier

**Expected Behavior**:

The identifier is selected

**Actual Behavior**:

The text from the beginning of the identifier to the position of the cursor is selected

**Comment by sharwell** [comment]
This is an editor bug: [DevDiv 635127](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/635127)
