### ISSUE TITLE
Roslyn should not display popups on Debug.Assert

### ISSUE THREAD

**Issue by mmitche** [dotnet/roslyn#2796]
For purposes of automation, it's bad to have user-interactive popups.  Debug.Assert's behavior by default is to pop up a dialog box.  This can be changed through app.config to simply abort the process by default.

**Comment by davkean** [comment]
@jaredpar Said this was regressed in the move to xUnit 2.1, but you're saying that you were hitting in this before then? 

I suspect this a cause of "deadlocks" in many of our flaky tests: https://github.com/dotnet/roslyn/labels/Flaky.

**Comment by davkean** [comment]
I've asked Brad: https://github.com/xunit/xunit/issues/382, he's won't fixed for the moment.

**Comment by davkean** [comment]
Brad states:

> There are mechanisms for this kind of assembly-wide overriding of behavior: custom test > frameworks. The implementation of ITestFramework and friends can be mostly pass-thru to the existing code.

> We resist the notion of having dozens of these one-off hooks in the framework itself because > everybody's pet "thing I want to override" just bloats the framework. We ensure that our extensibility story allows user to do what they need to do so that the core framework stays leans and focused.

> The ObservationExample does more than you need/want, but should at least set you down the right path.

**Comment by davkean** [comment]
Looking into this.

**Comment by davkean** [comment]
Looks like this run was probably blocked by something similar: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/869/consoleFull#-16758747638101fac1-935e-4556-95f9-7a0e25ca0b52.

**Comment by davkean** [comment]
@jasonmalinowski found that we can just remove the default trace listener, and define our own in the app.config that we pass to xUnit.

**Comment by jasonmalinowski** [comment]
I already started a PR for this locally...I can resurrect it if needed.

**Comment by jaredpar** [comment]
@jasonmalinowski if you have something that would be great.

**Comment by jasonmalinowski** [comment]
Turns out I had a made a local branch, and did nothing further. Oops. In any case, pull request #7896 is now available for your reviewing pleasure.
