### ISSUE TITLE
Document the behavior specification and test plan for the Code Cleanup "gold bar"

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#27974]
This new feature should have a clear behavior specification and test plan. Since we are changing the default behavior of a long-standing feature (Format Document), we want to make sure users are aware of the change and how to restore the original behavior if they choose to do so.

**Comment by davkean** [comment]
I would say this stronger; we should not change behavior of Format Document unless the user has clearly opt'd into the behavior. Visiting Tools -> Options is not an opt-in.

**Comment by JieCarolHu** [comment]
The gold bar only shows when user click Ctrl+K,D, and the code cleanup is not configured yet
And code cleanup is considered Configured if user goes to the Formatting setting page and click "Ok" to exit.
One of the scenario that user may never see the gold bar is:
User open the formatting setting page via tools->options without Ctrl+K,D, and click OK.
I didnot explicitly write any code telemetry for code cleanup, so unless we have some "built-in" tememetry with the gold bar, we probably don't the telemetry...

**Comment by davkean** [comment]
> And code cleanup is considered Configured if user goes to the Formatting setting page and click "Ok" to exit.

I think this behavior needs to change. We should never consider this as acknowledging the behavior change.

**Comment by sharwell** [comment]
> I think this behavior needs to change. We should never consider this as acknowledging the behavior change.

:memo: This issue is focused on documenting the current behavior and ensuring we have test coverage for the implemented design. There is a technical limitation which led to the behavior you're observing here which I'll be able to point out once the design is written up, and we can see about a solution that avoids the issue you're seeing.

**Comment by davkean** [comment]
Have you considered changing this to; have I prompted the user with the yellow bar?

**Comment by sharwell** [comment]
I was concerned that would be easy to miss, especially given that Format Document can be invoked by extensions. But it might make sense to show it if *either* the current check holds or the bar hasn't been shown yet.

**Comment by davkean** [comment]
Well, at least add an & in there:

``` C#
if (UserHasBeenPrompted & UserClickOKOnWhileShowingFormatting)
{
}

```

right now its:

``` C#
if (UserClickOKOnWhileShowingFormatting)
{
}

```

**Comment by Neme12** [comment]
> Scenario 2: User installs 15.8 p3 and finds the Tools>Options page for Format Document. They will see our defaults suggested the first time they arrive to this page. They can choose to alter the config and press OK. 

I agree with @davkean that this seems unexpected. Basically I visit formatting either to explore some other stuff or accidentally while looking for something else, and by pressing OK (while not changing any checkboxes) I'm actually changing some options. I would expect that if I open any options page, keep everything as-is and hit OK, nothing has changed. But this seems like the mere fact of visiting that page changed some options.

**Comment by davkean** [comment]
To clarify, I saw no relationship to me opening Options and the behavior change.

**Comment by kuhlenh** [comment]
@davkean did you change a setting on the Formatting page when you accidentally got there? Or did you exit Tools>Options by pressing OK on the Formatting page? If you pressed OK from a different page, that is definitely a bug.

I agree with Cyrus's design he pitched in the other thread: we add a checkbox for "Perform additional code cleanup during formatting". This checkbox will be *unchecked* by default (with our original options checked but all faded out). Then when a user navigates to this page they will have to explicitly check that new top-level box to enable the new Format Document behavior:

![image](https://user-images.githubusercontent.com/1402694/41691894-00abf2dc-74b2-11e8-8fe4-d5363d54dd1c.png)

**Comment by davkean** [comment]
Yes that would help.

I would still say that if you want to advertise the feature still prompt the yellow bar on very first format regardless of whether I've opened this page.

**Comment by kuhlenh** [comment]
@JieCarolHu will we be able to get the above redesign in for 15.8?

It will include: 
* top-level checkbox labelled "Perform additional code cleanup during formatting". Keep it unchecked by default.
* nest our original code cleanup options under that and fade them until the top-level checkbox is marked. Keep our original set of options checked though in here.

I agree with @davkean that for the sake of marketing our feature, it would be nice to show everyone the gold bar *once*, but I'm not willing to block the above design on that.

**Comment by CyrusNajmabadi** [comment]
Note: i think everyone is in agreement.  However, the crux of hte issue really comes down to:

> Or did you exit Tools>Options by pressing OK on the Formatting page?

Pressing "OK" on a dialog *that you did not modify* is not consent/opt-in.  It's equivalent to just saying "dismiss/cancel/esc/ignore".  It's just how someone gets rid of the dialog.  We happen to use the word "OK", but that's not the user mental model.  "Ok" only means "yes i want to commit my changed setting" when an actual change of settings has been made explicitly by the user on that page. 

This is why the above suggestion to add a top-level checkbox is the appropriate approach to mitigate the problem here.  It takes an actual demonstrative action on the part of the user that directly demonstrates they are opting into this feature.  At that point, 'ok' is just committing that confirmation.

**Comment by sharwell** [comment]
> Keep it unchecked by default.

I would prefer to keep it checked by default, as we do implicitly today.

**Comment by CyrusNajmabadi** [comment]
> I would prefer to keep it checked by default, as we do implicitly today, at least for the initial previews that contain the feature (and we won't have a choice for Preview 3).

I would be ok with this if it was **only** for previews.  For a real release, it seems like it would not be ok to just implicitly assume teh user is opting in just because they visited the page.  For a preview we can be more aggressive as part of the point of those is to get people trying things out and reporting feedback.

**Comment by kuhlenh** [comment]
Yes, I think everyone agrees with this principle. Let's make this option checked by default for 15.8 previews but it must be off in the RTW.

**Comment by JieCarolHu** [comment]
Cool. I will add the top level checkbox and make it checked for preview and off in RTW by default.

**Comment by JieCarolHu** [comment]
filed https://github.com/dotnet/roslyn/issues/28068 to reminder myself to set this value to false for RTM

**Comment by JieCarolHu** [comment]
Test plan is added in onenote

**Comment by devedse** [comment]
Hi all, I just noticed this feature was added. However I would like to be able to also kick off code cleanup seperately (and maybe even on the whole solution). Is this also possible?
