### ISSUE TITLE
Suggestion: 'cycle format' command

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#27971]
One or more command(s) that toggle expressions, lines, and parameters between all on one line and various styles of wrapping, initialization, and whitespace... I'm constantly finding myself wrapping long lines by hand, adding signature items, converting methods from expression-bodied, to braced, and properties from auto to explicit, all of which, require by-hand tweaking.

Think of this as analgous _clipboard ring_ but for common per-member formatting styles that frequently are used interchangeably. As opposed to the lightbulb, this can freely toggle between them irrespective of _editorconfig_ settings so long as we keep the number of stops small (3-5) and it can support whitespace changes, which are not currently supported by lightbulb, and don't fit its 'fix/refactor' metaphor well.

Some possible method definition, method call, and property, and expression formats:

*Single line:*
  - `void Foo(int bar, string baz, float bam)`
  - `this.Foo(3, "Four", 5.0);`
  - `int X { get; private set; }`

Unwraps and puts everything on one line.

*Wrapped when too long:*

```
void Foo(int bar, string baz,
       float bam)
```
```
this.Foo(3, "Four",
        5.0)
```

*On each line:*
```
void Foo(
    int bar,
    string baz,
    float bam)
```
```
this.Foo(
    3,
    "Four",
    5.0)
```
```
int X
{
    get;
    private set;
}
```

@kuhlenh FYI, ported from IM.

**Comment by CyrusNajmabadi** [comment]
This would be an editor/lsp feature.  If someone wants to propose that, roslyn would consider implementing our side of it.
