### ISSUE TITLE
Improvements to foreach to LINQ refactoring

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#27980]
based on feedback to https://github.com/dotnet/roslyn/pull/27130
- [ ] Split refactoring into chained refactorings like 
- convert foreach to linq
- merge list decl with usage 
- inline return or something like that.
- [ ] We can support not only lists but other defined collections like hashSet.UnionWith( ... ) rather than list.AddRange( ... )

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
