### ISSUE TITLE
Add Tests for product bug: VB Line Commit happening without the caret leaving the line

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#27988]
A couple repros in the latest `d15.8stg`:

-----
Default VB file, `Ctrl+a, Tab`, nothing gets indented because LineCommit fixes the indent

-----
1) Paste this into a VB project:
```VB
Class Program
    Shared Sub Main(args As String())
        Program
    End Sub
End Class
```
2) Select the whole thing (bottom-to-top, to avoid the first repro above) and tab it in a bunch
3) Put the caret after the `Program` in the method body (If this causes it to get reformatted, Ctrl+z until you have the same shape as above but indented a few tabs)
Then type, `.Ma` and hit the left arrow
*Actual* Line Commit kicks in and un-indents a couple lines

-----
In a VB method body, type `If Tr` followed by a left arrow. Line commit inserts the missing `Then` token

-----
In a VB method body, paste this:
```VB
If True Then
End If
```
Select the "Then" and hit Delete. Nothing happens

**Comment by dpoeschl** [comment]
It turns out this is because the `CaretPositionChangedEventArgs` the editor is providing us (from the new multi-caret infrastructure) seems to always report the `OldPosition` as 0. So when you move the caret on Line 3, the event args make us thing the caret moved from Line 1 --> Line 3, so we perform a Line Commit.

**Comment by dpoeschl** [comment]
Ported & assigned to the editor team in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/635902

**Comment by dpoeschl** [comment]
Re-opening to track the adding of explicit tests for this (rather than the super-lucky implicit testing that was happening before).

**Comment by CyrusNajmabadi** [comment]
Closing as speculative
