### ISSUE TITLE
Function resolution for Nothing argument

### ISSUE THREAD

**Issue by rhuijben** [dotnet/roslyn#27984]
**Version Used**: 
Visual Studio 15.7.4 and a few earlier 15.x builds
</p>
**Steps to Reproduce**:
</p>
In VB.Net add two functions
<pre>
    Sub Add(ob as Object)</p>
    Sub Add(kv as KeyValuePair(Of String, Object))
</pre>

And now try to call this function as
`Add(Nothing)`

</p>
**Expected Behavior**:
I would expect either an invocation of the first overload or a compiler warning/error.
</p>
</p>
**Actual Behavior**:
I see a call to the second function, with both fields of the KeyValuePair value class set to `null`
</p>
</p>

The only way to trigger a warning is to also add another overload `Add(I as Integer)`

**Comment by jcouv** [comment]
I think this is expected: there are two candidates, but one is more specific, so the other one is removed from the candidate list. See [overload resolution rules](https://github.com/dotnet/vblang/blob/master/spec/overload-resolution.md) (bullet 6).
