### ISSUE TITLE
Missing IOperation - Constructor call on struct creates IInvalidOperation

### ISSUE THREAD

**Issue by mvacha** [dotnet/roslyn#27997]
**Version Used**: 
2.9.0-beta7-63018-03

**Steps to Reproduce**:
1. Create CFG from source which contains call to struct constructor:
```
var source = @"class Program{ int Main() { var d = new DateTime(); }}";
var compilation = Compile(source);
var cfg = GetTreeCFG(compilation);
```
Compilation is with `flow-analysis` and C#7. [Compile and GetTreeCFG implementations](https://gist.github.com/mvacha/6b8102e0c3c3eba90ee750b87fb2c122) (not interesting)
 
**Expected Behavior**:
Something like: IStructCreationOperation which does not exist yet.

**Actual Behavior**:
Tree contains InvalidOperation inside the assignment to the local symbol `d`
`IInvalidOperation (OperationKind.Invalid, Type: DateTime, IsInvalid) (Syntax: 'new DateTime(10)')`

**Comment by mavasani** [comment]
@mvacha Your source snippet seems to be missing a `using System;` for `DateTime`, which causes the compilation error leading to unbound type `DateTime`, which causes `new DateTime()` to be an invalid operation.

**Comment by mavasani** [comment]
> Expected Behavior:
Something like: IStructCreationOperation which does not exist yet.

@mvacha With a valid source code snippet, you will get an [IObjectCreationOperation](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/IObjectCreationOperation.cs,19) node for the constructor invocation. Kindly re-open the issue if it is not so.
