### ISSUE TITLE
Cannot build latest master branch

### ISSUE THREAD

**Issue by JieCarolHu** [dotnet/roslyn#28004]
VsdConfigTool.exe : error XAC9999: INTERNAL COMPILER ERROR. Unhandled exception (System.UnauthorizedAccessException). [
C:\GitHub\roslyn\src\VisualStudio\Core\Def\ServicesVisualStudio_juodxupa_wpftmp.csproj]
  --------------------------------------------------------------------------
  Access to the path 'C:\Microsoft.VisualStudio.LanguageServices.vsdconfig' is denied.
     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
     at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileS
  hare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy,
  Boolean useLongPath, Boolean checkHost)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Fi
  leOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
     at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
     at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
     at XapiConfigRuntime.Processor.Run(ProcessorArguments args)
     at VsdConfigTool.EntryPoint.Main(String[] args)
  --------------------------------------------------------------------------
C:\GitHub\roslyn\build\Targets\Vsdconfig.targets(19,5): error MSB3073: The command ""C:\Users\carhu\.nuget\packages\\Mi
crosoft.VSSDK.BuildTools\15.8.68-develop-g109a00ff\tools\VSSDK\bin\vsdconfigtool.exe" "ManagedEditAndContinueService.vs
dconfigxml" "C:\GitHub\roslyn\Binaries\Obj\ServicesVisualStudio\Debug\\Microsoft.VisualStudio.LanguageServices.dll" "\M
icrosoft.VisualStudio.LanguageServices.vsdconfig"" exited with code -1. [C:\GitHub\roslyn\src\VisualStudio\Core\Def\Ser
vicesVisualStudio_juodxupa_wpftmp.csproj]

----------------------------------
I got the same build errors on 2 boxes and if I switch to an earlier branch it builds fine.

Vsdconfig.targets has the following line, so it looks like $(OutDir) is empty:
<Exec Command="&quot;$(_VsdConfigTool)&quot; @(VsdConfigXml -> '&quot;%(RelativeDir)%(FileName)%(Extension)&quot;', ' ') &quot;$(IntermediateOutputPath)\$(AssemblyName).dll&quot; &quot;$(OutDir)\$(AssemblyName).vsdconfig&quot;" />

**Comment by etbyrd** [comment]
Same as https://github.com/dotnet/roslyn/issues/28003?

**Comment by JieCarolHu** [comment]
yes, I am closing this one then :)
