### ISSUE TITLE
Is "error CS0012" a bug for .netcore2.0 ?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/roslyn#28009]
Version Used:

Microsoft.CodeAnalysis.CSharp.Scripting 2.7.0
.net core 2.0
BenchmarkDotNet 0.10.13

**Steps to Reproduce**:
Here is the src [issue](https://github.com/dotnet/roslyn/issues/27783) .
Here is the src [code](https://github.com/jmarolf/RoslynPerfomanceTest/blob/4a86e03a30f297be9f2d5fd9204e3ef0029c51f9/RoslynPerfomance/RoslynTest/Watcher.cs#L42-L70) .
**Expected Behavior**:
Run and show the result.
**Actual Behavior**:
 error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

It works on .net framework4.7, but failed in core2.0.

**Comment by NMSAzulX** [comment]
Will this problem be solved?   In .net core 3.0

**Comment by NMSAzulX** [comment]
source :  #27783

**Comment by svick** [comment]
It will not be solved, because it's not a bug. When you create a `Compilation`, you need to add all necessary references and you did not do that.

Though finding all the right references is not trivial. I believe the best way to make sure you did it correctly is to use `<PreserveCompilationContext>`, and `DependencyContext`, as explained in https://github.com/dotnet/core/issues/2082#issuecomment-442713181.

**Comment by NMSAzulX** [comment]
@svick Thank you. But I raised a new questions. Here is the [source code](https://github.com/NMSAzulX/Roslyn28009). 
When I call a custom method dynamically, it prompts that **the namespace cannot be found**, which means that my .dll (ConsoleApp1.dll) was not introduced. How to solve this problem?

**Comment by svick** [comment]
If you want to get all references from the current context, you can't use that filter for `Microsoft.NETCore.App`, you should use the previous snippet:

```c#
MetadataReference[] _ref = 
    DependencyContext.Default.CompileLibraries
    .SelectMany(cl => cl.ResolveReferencePaths())
    .Select(asm => MetadataReference.CreateFromFile(asm))
    .ToArray();
```

With this, your code works for me.

**Comment by NMSAzulX** [comment]
Yeah, it works.  BechmarkDotNet made a mistake.  But my problem seems to have been solved.  Thank you.

**Comment by NMSAzulX** [comment]
I'll do more tests later. If I find any other problems, I will open a new ISSUE.

**Comment by NMSAzulX** [comment]
Thanks to everyone on the Roslyn team.
