### ISSUE TITLE
Port C# compiler tests to Mono

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#28011]
This tracks the progress of porting our compiler tests to run on Mono.

- [x] C# syntax tests
- [x] C# symbol tests
- [x] C# emit tests
- [x] C# semantic tests
- [x] C# IOperation tests

**Comment by agocke** [comment]
Emit tests should be prioritized as an RCA bug being tracked here: https://github.com/dotnet/roslyn/issues/27642

**Comment by jaredpar** [comment]
Semantic currently blocked on https://github.com/mono/mono/issues/10280

**Comment by Therzok** [comment]
Looks like a really old mono. Were the package repos correctly added?
