### ISSUE TITLE
editorconfig: Bad interaction between end_of_line=lf and insert_final_newline=true with CRLF templates in VS

### ISSUE THREAD

**Issue by binki** [dotnet/roslyn#28027]
**Version Used**: 

VisualStudio-15.7.4

**Steps to Reproduce**:

1. Create a `.editorconfig` in the root of your C# project with the following contents:

       root = true
       
       [*]
       end_of_line = lf
       insert_final_newline = true
2. Create a new XML file from a template.
3. Type a root element, for example `<x/>`, on the last line of the XML template. Your file should look like the following and have no newline at the end:

       <?xml version="1.0" encoding="utf-8" ?>
       <x/>
3. Save the new XML file. The editor should add a newline at the end so that VS displays the file as having three lines.

   ![image](https://user-images.githubusercontent.com/82626/41679445-3897ec52-749c-11e8-99d2-4f4437a41d53.png)

**Expected Behavior**:

Best: The entire file is LF.

Acceptable: The entire file is CRLF.

**Actual Behavior**:

The first line is terminated with CRLF and the second line is terminated with LF.

    $ hexdump.exe -C XMLFile1.xml
    00000000  3c 3f 78 6d 6c 20 76 65  72 73 69 6f 6e 3d 22 31  |<?xml version="1|
    00000010  2e 30 22 20 65 6e 63 6f  64 69 6e 67 3d 22 75 74  |.0" encoding="ut|
    00000020  66 2d 38 22 20 3f 3e 0d  0a 3c 78 2f 3e 0a        |f-8" ?>..<x/>.|
    0000002e

or, as Emacs renders it:

    <?xml version="1.0" encoding="utf-8" ?>^M
    <x/>

When I open the file again in the future with VS, it prompts me if I want to fix the newlines to be consistent.

The newlines originally were self-consistent, but VS made them inconsistent when it appended the newline at the end of the file.

**Comment by sharwell** [comment]
This is a bug in the core Visual Studio editor, not Roslyn. I recommend filing a feedback ticket with the same information you've provided above, and it will get routed to the appropriate team.

/cc @olegtk @AmadeusW

**Comment by binki** [comment]
I have posted to the feedback community at https://developercommunity.visualstudio.com/content/problem/277772/editorconfig-bad-interaction-bewteen-end-of-linelf.html . Thanks for the help!

**Comment by sharwell** [comment]
@binki I'm impressed. Not sure I could file a bug report that cleanly presented myself!
