### ISSUE TITLE
[Refactoring] Move VisualStudioSymbolRenamedCodeActionOperationFactoryWorkspaceService

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#28020]
It's this service:

http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Workspace/VisualStudioSymbolRenamedCodeActionOperationFactoryWorkspaceService.cs,19

We need it as well in visual studio for mac and we simply 1:1 copy that code - if it would be moved to another layer we could get rid of some code duplication.

**Comment by jinujoseph** [comment]
cc @jasonmalinowski , @JieCarolHu

**Comment by CyrusNajmabadi** [comment]
Closing out as having had no movement since original request.  If you guys need this, i recommend starting a convo and making an explicit request on it (ideally just make a PR).
