### ISSUE TITLE
Rationalize use of DisplayName vs Id

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#2802]
Originally, we only had `AnalyzerReference.DisplayName`. This was meant only as a friendly string to show to the user, but various parts of the VS code base used this as an identifier of some sort.

Later we added `AnalyzerReference.Id`, which is meant to serve as the canonical ID of a reference.

We need to review the uses of both, and figure out which should actually be `DisplayName` and which should be `Id`. Until we do so, `AnalyzerFileReference` will have to return the same value from both. This means that, at least in some cases, we won't load two analyzers that have the same name but different versions, even though that should be perfectly legal (so long as they are strong-name signed).

The `HostAnalyzerManager` in particular needs to be reviewed. It sometimes indicates that it is using a name where it is actually using an ID.

**Comment by heejaechang** [comment]
@tmeschter I make a change and gave you the link in #2801 

now you shouldn't need to make id to use same as Displayname.

**Comment by heejaechang** [comment]
fixed #2820

**Comment by tmeschter** [comment]
There's no particular verification that needs to be done here.
