### ISSUE TITLE
[Refactoring] MoveVisualStudio/CSharp/Impl/Debugging/CSharpLanguageDebugInfoService.cs

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#28041]
https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/CSharp/Impl/Debugging/CSharpLanguageDebugInfoService.cs

We need it as well in visual studio for mac and we simply 1:1 copy that code - if it would be moved to another layer we could get rid of some code duplication.

**Comment by jinujoseph** [comment]
cc @jasonmalinowski

**Comment by jasonmalinowski** [comment]
@mkrueger Should it just be moved down to the EditorFeatures layer?

**Comment by jasonmalinowski** [comment]
(or I guess maybe Workspaces or Features if it really relies on no editor stuff)

**Comment by CyrusNajmabadi** [comment]
Closing out as having no traction on it from original asking team.
