### ISSUE TITLE
Difference in SemanticModel behavior between VB and C# for unbound alias (affects Simplifier.Expand API)

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#2805]
Paste the following code in visual studio -

```
using System;
namespace NS
{
    using Short = LongNamespace;
    class Test
    {
        public object Method1()
        {
            return (new Short.MyClass()).Prop;
        }
    }
}
```

Right click on the identifier `Short` in the `return` statement above and click on `Go to definition`. This works even though the namespace `LongNamespace` that the alias binds to does not itself bind to anything.

Now try the corresponding scenario for VB -

```
Imports System
Imports ShortName = LongNamespace
Namespace NS
    Class Test
        Public Function Method1() As Object
            Return (New ShortName.Class1()).Prop
        End Function
    End Class
End Namespace
```

In this case, clicking on the identifier `ShortName` and clicking on `Go to definition` does not work. In other words, the alias itself fails to bind if the namespace it is binding to fails to bind.

The underlying reason for the above `Go to definition` behavior is that the VB `SemanticModel` fails to produce a symbol for ShortName if I call `SemanticModel.GetSymbolInfo`.

This also manifests in a difference between C# and VB for the `Simplifier.Expand()` API. While this API is able to expand the identifier `Short` to `LongNamespace` in C#, it is not able to do the same in VB.

**Comment by shyamnamboodiripad** [comment]
I have added a skipped test for this issue. **When you fix this issue, please remember to enable this test.**

**Comment by AlekseyTs** [comment]
PR https://github.com/dotnet/roslyn/pull/3603 made SemanticModel behavior consistent between VB and C#. However, the behavior doesn't match the one requested above. I.e. now GetSymbolInfo doesn't return any symbol for both languages and this is according to the API's design. Consider changing Simplifier's implementation accordingly.

**Comment by dpoeschl** [comment]
@shyamnamboodiripad It looks like the SemanticModel has been made consistent, which is that there's no symbol provided. And Go To Definition works for both languages in this case. However, your disabled test is asserting that a symbol is returned, rather than just checking if Go To Definition works. Can we just remove that test and close this issue, or is there some other non-GTD case that you're worried about?

**Comment by shyamnamboodiripad** [comment]
I believe the issue I had run into had to do with the simplifier API - <quote>*This also manifests in a difference between C# and VB for the  Simplifier.Expand()  API. While this API is able to expand the identifier  Short  to  LongNamespace  in C#, it is not able to do the same in VB*</quote>

@dpoeschl you may want to confirm that the behavior of the simplifier API is consistent between VB and C# and that it is possible to expand aliases in both. If not, then the simplifier implementation probably needs changes as @AlekseyTs indicated above.

**Comment by Pilchie** [comment]
I think we've lived with this for long enough.
