### ISSUE TITLE
Improve compiler behaviour for extension methods with constraints

### ISSUE THREAD

**Issue by Makeman-Makeloft** [dotnet/roslyn#28074]
**Version Used**: master on sharplab.io

**Steps to Reproduce**:
[The source code](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABABgAJiBGAbgFgAoYgZkqoDZKAmNgdnIDejciMqtqnYgBY2ADgAUASkHDRagJaYY5deQC85UvQZqNAOgCSUJcdOjSl64tt3ymOAHdyAeWAArOABjGCVHG1U7agBOeQAiQB4NwBB92OcI8gBfNLSJShkAFThYAB48gD55PPIAD2U9Uuqw1IZMhkYWNkkeABkAUUYhE1d2nOAAe1GAG3IrEvKYAAt1KHJK0dr60Z1lvOMWtvEObnJegH0AZRgMYP60tWHDscnpqFn5BaWV8jXyD3nEOE+IHIsCu2jq5Eu6DgLkiB04jymMzKb0WywQcAAZp9vr9/oDgZDgvp6pDoYw9kw4UdTgBhCbQKA3QawjrkBHPV7vbZfZS49H44g8cGbACEBkw6AmE12QA=)

For example, at some cases I prefer to use custom extension methods instead native operators
```c#
public static class LE_Generic
{
        public static bool Is<T>(this T o) => o is T;

        /* ... and another overloads */
}
```
For me looks more pretty
```c#
if (person.Is()) ...
// instead
if (person != null) ...
```

Then I decide to optimize performance of my method because there are some lacks

```c#
public static class LE_Struct
{
        public static bool Is<T>(this ref T o) where T : struct => true;
}

public static class LE_Class
{
        public static bool Is<T>(this T o) where T : class => o != null;
}
```
So, with C# 7.3 I can use this two overloads together, but I got some limitations

```c#
var i = 0;
i.Is();
0.Is(); // error CS1510: A ref or out value must be an assignable variable

static void Test<T>(T x) => x.Is(); // error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'LE_Struct.Is<T>(ref T)'
```
Looks that complete set of custom methods

```c#
public static class LE
{
        public static bool Is<T>(this T o) => o is T;
}

public static class LE_Struct
{
        public static bool Is<T>(this T o) where T : struct => true;
        public static bool Is<T>(this ref T o) where T : struct => true;
}

public static class LE_Class
{
        public static bool Is<T>(this T o) where T : class => o  != null;
}
```

**Expected Behavior**:
Successful compilation

```c#
int i = 0;
i.Is(); // bool Is<T>(this ref T o) where T : struct
0.Is(); // bool Is<T>(this T o) where T : struct
new Object().Is(); // bool Is<T>(this T o) where T : class

static void Test<T>(T x) => x.Is(); // bool Is<T>(this T o)
```

**Actual Behavior**:
Compiler errors for three cases

```
error CS0121: The call is ambiguous between the following methods or properties: 'LE.Is<T>(T)' and 'LE_Struct.Is<T>(T)'
error CS0121: The call is ambiguous between the following methods or properties: 'LE.Is<T>(T)' and 'LE_Struct.Is<T>(T)'
error CS0121: The call is ambiguous between the following methods or properties: 'LE.Is<T>(T)' and 'LE_Class.Is<T>(T)'
```

**Comment by gafter** [comment]
The runtime compiler (jit) already produces excellent specialized code for the general version. There is no need to specialize in source. Moreover, there is no need for these methods at all.

Since you have been banned from this repository, please refrain from posting with any of your accounts.

**Comment by Makeman-Makeloft** [comment]
@gafter 
Thank for your answer but I closely research this question and looks that for some special cases JIT generate not optimal code. Moreover there are differences between .NET Framework and Core CLR.

Some details you may found here https://github.com/dotnet/coreclr/issues/17981

In general this issue is about extension methods at all, not only about 'is' operator, it is like a sample.
