### ISSUE TITLE
Feature request: Partial class (master, child)

### ISSUE THREAD

**Issue by juanfranblanco** [dotnet/roslyn#28073]
Partial classes are normally used for code generation.

The problem arises when a different implementation of a property or a method is required, these properties or methods cannot be simply overridden, and partial methods forces to not have an implementation.

A simple approach would be to be able to mark a partial class (Attribute at the class level) as the Partial.Master.

In this scenario, if you need to implement a completely new method or property, the ones in the Master will be used. Taking it further an end user will only need to create this Partial Master class when needed.

**Comment by juanfranblanco** [comment]
An example:

```csharp
 public partial class TheClass
    {
        //Generated don't modify

        public int MyVal { get; set; }

        public void Jump()
        {
            //....
        }

    }

    [PartialClass.Master]
    public partial class TheClass
    {
        public string MyVal { get; set; }

        public void Jump()
        {
            //My new implementation
        }
    }
```

**Comment by HaloFour** [comment]
Language proposals should be submitted to the [CSharpLang](https://github.com/dotnet/csharplang/issues) repository.
