### ISSUE TITLE
Debugger will crash when loading some obfuscated assembly.

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#28076]
**Version Used**: VS2017 15.7.4

**Steps to Reproduce**:

1. Create a project, place [ConsoleApp1.zip](https://github.com/dotnet/roslyn/files/2128391/ConsoleApp1.zip) to the build path, write this code:
```
static void Main(string[] args)
{
    var assembly = Assembly.LoadFrom("ConsoleApp1.exe");
    Console.WriteLine(assembly);
    Console.ReadKey();
}
```
2. F10 to debug it

**Expected Behavior**: Nothing

**Actual Behavior**: Debugger will crash after this line: `var assembly = Assembly.LoadFrom("ConsoleApp1.exe");`
I can't get any tip when my mouse point something, I allways get this error when writing something in the watch window:
`error CS0009: Metadata file 'ConsoleApp1.exe' could not be opened -- Invalid public key.`

**Comment by CreateAndInject** [comment]
VS2010 can debug it without any error.

**Comment by tmat** [comment]
@CreateAndInject What do you mean by "Debugger will crash"? Is the VS crashing, or is it just reporting `error CS009` in watch window?

**Comment by CreateAndInject** [comment]
VS doesn't crash, and it can hit breakpoints, but I can't view variables, there's no tip pop up when my mouse point some variable, and I will get that error when I type something in the watch window.

**Comment by sharwell** [comment]
We confirmed with the team that we are not planning to make changes to our tools to work around behaviors introduced by a code obfuscation tool. These tools are known to produce invalid outputs for the purpose of breaking end user development/debugging experiences; if/when they are successful in doing so the bug should be filed with the creator of the tool that produced the invalid code.
