### ISSUE TITLE
IFieldSymbol.ConstantValue for Android Enum value is null

### ISSUE THREAD

**Issue by DVaughan** [dotnet/roslyn#28077]
**Version Used**: 
Visual Studio 15.7.4
Microsoft.CodeAnalysis 2.8.2
[RoslynAndroidEnumRepro.zip](https://github.com/dotnet/roslyn/files/2128425/RoslynAndroidEnumRepro.zip)

**Steps to Reproduce**:

1. Create a .NET console application
2. Create an Xamarin Android class library with an Enum
3. Retrieve the fields as in the following excerpt:

```cs
static void Main(string[] args)
{
	var work = MSBuildWorkspace.Create();
	Solution solution = work.OpenSolutionAsync(@"..\..\..\RoslynTest.sln").Result;
			
	PrintFields(solution, "DotNet", "DotNet.DotNetEnum");
	PrintFields(solution, "DotNetCoreLibrary", "DotNetCoreLibrary.DotNetCoreEnum");
	/* IFieldSymbol.ConstantValue for Android enum value is null. */
	PrintFields(solution, "AndroidClassLibrary", "AndroidClassLibrary.AndroidEnum");

	Console.ReadKey();
}

static void PrintFields(Solution solution, string projectName, string fullyQualifiedTypeName)
{
	Project project = solution.Projects.First(x => x.Name == projectName);
	var compilation = project.GetCompilationAsync().Result;

	Console.WriteLine(fullyQualifiedTypeName + ":");

	INamedTypeSymbol targetType = compilation.GetTypeByMetadataName(fullyQualifiedTypeName);
	var fieldSymbols = targetType.GetMembers().OfType<IFieldSymbol>();

	foreach (IFieldSymbol symbol in fieldSymbols)
	{
		Console.WriteLine("ConstantValue: " + symbol.ConstantValue);
	}

	Console.WriteLine("-------------------------------------------");
}
```

**Expected Behavior**:
The IFieldSymbol.ConstantValue property should be returned for the int literal. This occurs as expected in the .NET core and .NET projects in the attached repro.
**Actual Behavior**:
The IFieldSymbol.ConstantValue property is null for Xamarin Android projects.

**Comment by jinujoseph** [comment]
cc @mavasani

**Comment by mavasani** [comment]
@jaredpar @jinujoseph Why is this issue marked with Area-Analyzers instead of Area-Compilers? The bug seems to be about constant value of a field symbol.

**Comment by jinujoseph** [comment]
This works in Desktop / Core looks like some thing missing to make it work in Android.

**Comment by svick** [comment]
Does the compilation contain any errors or warnings? You can print them using code like:

```c#
foreach (var diagnostic in compilation.GetDiagnostics())
    Console.WriteLine(diagnostic);
```

**Comment by DVaughan** [comment]
The compilation reports:
error CS5001: Program does not contain a static 'Main' method suitable for an entry point

**Comment by CyrusNajmabadi** [comment]
Does the MSBuildWorkspace.Diagnostics itself report any errors?
