### ISSUE TITLE
Naming convention code style is missing for method parameters and local variables

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28088]
I'm trying to enforce a naming convention for method parameters and local variables inside methods, just as I can do for types, fields, properties, etc.  It doesn't seem to exist in the list of available naming style settings.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/276387/naming-convention-code-style-is-missing-for-method.html
VSTS ticketId: 635579_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
Duplicate of #18121
