### ISSUE TITLE
A suggestion syntactic sugar.

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#28089]
I think `if (obj !is string)` /  `if (obj is! string)` is more elegant than `if (!(obj is string))` / `if (obj is string == false)`

**Comment by PathogenDavid** [comment]
C# language features belong over in the [csharplang](https://github.com/dotnet/csharplang) repo.

This feature proposal already exists there as https://github.com/dotnet/csharplang/issues/1338

However it sounds like language designers are leaning towards a syntax like this:

```csharp
if !(obj is string)
{ }
```

The proposal for that particular syntax is tracked by https://github.com/dotnet/csharplang/issues/568 and is championed as a C# 8.0 candidate by https://github.com/dotnet/csharplang/issues/882.
