### ISSUE TITLE
AttributeData.NamedArguments is not Populated on Xamarin Android

### ISSUE THREAD

**Issue by DVaughan** [dotnet/roslyn#28092]
**Version Used**: 
Visual Studio 15.7.4
Microsoft.CodeAnalysis 2.8.2

**Description**
`AttributeData.NamedArguments` is correctly populated in .NET and .NET Core, but not in a Xamarin Android project.

**Steps to Reproduce**:

[RoslynAndroidCustomAttributes.zip](https://github.com/dotnet/roslyn/files/2131228/RoslynAndroidCustomAttributes.zip)

1. Create a Xamarin Android class library.
2. Create a custom System.Attribute in the Xamarin Android project, like so:
```cs
namespace SomeNamespace
{
	public class CustomAttribute : Attribute
	{
		public string Foo { get; set; }
	}
}
```
3. Decorate a class in the android project like so:
```cs
namespace SomeNamespace
{
	public class ClassWithDecoratedProperty
	{
		[Custom(Foo = "Some value.")]
		public string Bah { get; set; }
	}
}
```
4. Retrieve the `NamedArguments` property of the `AttributeData` object for the attribute.

```cs
static void PrintFields(Solution solution, string projectName)
{
	Project project = solution.Projects.First(x => x.Name == projectName);
	var compilation = project.GetCompilationAsync().Result;

	Console.WriteLine(projectName + " custom attribute arguments:");

	INamedTypeSymbol targetType = compilation.GetTypeByMetadataName(
						"SomeNamespace.ClassWithDecoratedProperty");

	var properties = targetType.GetMembers().OfType<IPropertySymbol>();
	foreach (IPropertySymbol propertySymbol in properties)
	{
		AttributeData attribute = propertySymbol.GetAttributes().First();

		foreach (KeyValuePair<string, TypedConstant> pair in attribute.NamedArguments)
		{
			Console.WriteLine($"{pair.Key} = {pair.Value.Value}");
		}
	}

	Console.WriteLine("-------------------------------------------");
}
```

**Expected Behavior**:
The `AttributeData.NamedArguments` should be populated with an entry for the custom attribute, which includes the name and value of the attribute's property.
**Actual Behavior**:
The `AttributeData.NamedArguments` property is not populated on Android. (It is in .NET and .NET Core)

**Comment by jaredpar** [comment]
Moving to IDE. Given that it works in Desktop / Core this sounds like a hookup issue on Android.

**Comment by jinujoseph** [comment]
cc @mavasani

**Comment by CyrusNajmabadi** [comment]
Does the MSBuildWorkspace.Diagnostics itself report any errors?
