### ISSUE TITLE
IDE0009 misfires when using dictionary initializer syntax within LINQ expression

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#28091]
Similar to #23381, except related to dictionary initializer instead of object initializer.

**Version Used**: VS 15.8.0 Preview 3 (27821.2.d15.8)

**Steps to Reproduce**:

```cmd
git clone https://github.com/AArnott/Nerdbank.GitVersioning.git
cd Nerdbank.GitVersioning
src\Nerdbank.GitVersioning.sln
```

Open the Nerdbank.GitVersioning.Tasks/SetCloudBuildVariables.cs file and check out the error list.

**Expected Behavior**:

No warnings.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/3548/41822764-b70121e8-77a9-11e8-9d87-c6d49c1bfbce.png)

https://github.com/AArnott/Nerdbank.GitVersioning/blob/e0ccd4cf350a11df24d73dd3a06c225f17eb9474/src/Nerdbank.GitVersioning.Tasks/SetCloudBuildVariables.cs#L57-L59

**Comment by TheEres** [comment]
Does not seem to be linked (!) to Linq.
The offered fix as no preview, and does not modify code.
Pragma suppress in source correctly disable it.

**Version**: VisualStudio.15.Preview/15.8.0-pre.4.0+27906.1
**Project**: .NET Standard 2.0 Class Library
![image](https://user-images.githubusercontent.com/12914051/42623114-5077c900-85c2-11e8-93ed-99158cb6b07e.png)
![image](https://user-images.githubusercontent.com/12914051/42623667-ba3da412-85c3-11e8-99aa-d7ddd95a83a6.png)

**Comment by jinujoseph** [comment]
@JieCarolHu validate and close

**Comment by JieCarolHu** [comment]
Verified on master
