### ISSUE TITLE
Extension method to map an IBranchOperation to the parenting ILoopOperation or ISwitchOperation

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#28095]
See the second bullet point in Nice to have listed by @bkoelman in this comment: https://github.com/dotnet/roslyn/issues/27208#issuecomment-396575101

**Comment by mavasani** [comment]
[IBranchOperation.Target](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/IBranchOperation.cs,22) points to the destination label symbol. [ILoopOperation](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/Loops/ILoopOperation.cs,19) now exposes the break and continue label symbols and [ISwitchOperation](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/ISwitchOperation.cs,19) exposes an exit label symbol, so the extension to match the branches with parent loop/switch should be simple to implement .

**Comment by wachulski** [comment]
I can start working on it. Could you advise on where you place such extension methods?
