### ISSUE TITLE
More tests for pattern using

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#28102]
Follow up to https://github.com/dotnet/roslyn/pull/27729

Jared suggested a variety of useful tests that weren't included in the original PR. They are:

* Tests to ensure we bind correctly when presented with the pattern + an interface implementation
* Tests where the receiver is a generic parameter constrained
   * To an interface that implements an interface that meets the disposable pattern but is not IDisposable
   * To an interface that implements an interface that meets the disposable pattern and implements IDisposable
   * To an interface that does not meet the disposable pattern directly but indirectly through an extension method.
   * The first two items above but additionally with the struct constraint and IL verification that we call Dispose in a non-boxing fashion.

We should follow up with these before merging the final feature branch.

**Comment by chsienki** [comment]
These are no longer relevant; the only time we allow pattern based disposal is for `ref` structs, which can't implement interfaces.
