### ISSUE TITLE
NetCoreTests failing in Jenkins

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#28104]
These tests: Microsoft.CodeAnalysis.MSBuild.UnitTests.NetCoreTests.TestOpenProject_NetCoreMultiTFM_ProjectReferenceWithReversedTFMs
Microsoft.CodeAnalysis.MSBuild.UnitTests.NetCoreTests.TestOpenProject_NetCoreMultiTFM
Microsoft.CodeAnalysis.MSBuild.UnitTests.NetCoreTests.TestOpenProject_NetCoreMultiTFM_ProjectReference

are failing on master

https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_spanish_unit32/lastFailedBuild/

Will skip the tests until they are fixed.

**Comment by tmat** [comment]
There are a few issues with these tests:
- restore errors are not reported 
  - at least the tests should assert that `dotnet restore` succeeded and print out any errors if it fails
  - ideally restore binlog would be stored in artifacts for inspection when the test fails
- the tests assumes `dotnet` is installed and its location is in `PATH` and uses whatever version is found there 
  - instead the one that is installed by the build scripts should be used
- explicitly specify package sources
  - the test should use a nuget.config with explicit package sources and `<clear />` entry 
- explicitly specify restore package cache via `NUGET_PACKAGES` environment variable

See https://github.com/dotnet/sourcelink/blob/master/src/TestUtilities/DotNetSdk/DotNetSdkTestBase.cs

**Comment by jasonmalinowski** [comment]
This should be moved out of the infrastructure path. @jinujoseph or @Pilchie who is owning our MSBuildWorkspace going forward? The work here was done by @DustinCampbell so can't assign it to his "team"... :smile:

**Comment by DustinCampbell** [comment]
I'll take this. IDE is fine for the area label.

**Comment by DustinCampbell** [comment]
Fix in PR: #30490
