### ISSUE TITLE
Provide a mechanism to skip over broken source code

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#28113]
As an analyzer author, it seems nearly impossible to know when syntax/symbol/operation properties can be `null`, as a result of source code that contains errors. Usually because the user is still typing.

Of course, I can be defensive and put a null check around *every* member access. But that makes the analyzer sources hard to read, so I would rather not do that.

I've tried a few analyzer packs in the past, and observed the yellow crash bar appear about every five minutes while writing code. I think analyzer authors are struggling with this.

Writing analyzer unit tests for broken code quickly becomes endless. And it's difficult to reconstruct what broken code leads to which properties being `null`. Lots of trial and error. Even dogfooding against large code bases does not help, because they do not contain broken code.

In the past I used `IOperation.HasErrors`, which has been removed [for various reasons](https://github.com/dotnet/roslyn/issues/27208#issuecomment-399991699).

Therefore it would help if a general mechanism would be available to only run analyzer callbacks on non-broken code. So that an analyzer author can safely assume that, for example, `ILocalSymbol.Name` will never be `null` or an empty string.

Another solution would be to document when members can be null and under which circumstances. For example, provide a snippet of broken code in the documentation comments of generated syntax nodes. However as implementations change over time (and documentation becomes outdated), putting such logic inside the compiler would probably be more future-proof.

/CC @mavasani

**Comment by mavasani** [comment]
Tagging @AlekseyTs @333fred @dotnet/analyzer-ioperation 

@bkoelman `IOperation.HasErrors` was deliberately removed as it conflated two different concepts - (a) semantic tree that exposes semantics of code and (b) diagnostics produced by compiler for invalid syntax or semantics, the latter just being a side effect of compiler execution. Latter information is realistically not needed to analyze semantic tree.

It is recommended that analyzer authors analyze operations based on the _contracts_ associated with the operation nodes and values of it's children and/or properties, which should be in the public API documentation and should always be up-to-date. For example, consider `IInvocationOperation`:

```
    public interface IInvocationOperation : IOperation
    {
        /// <summary>
        /// Method to be invoked.
        /// </summary>
        IMethodSymbol TargetMethod { get; }
        /// <summary>
        /// 'This' or 'Me' instance to be supplied to the method, or null if the method is static.
        /// </summary>
        IOperation Instance { get; }
        /// <summary>
        /// True if the invocation uses a virtual mechanism, and false otherwise.
        /// </summary>
        bool IsVirtual { get; }
        /// <summary>
        /// Arguments of the invocation, excluding the instance argument. Arguments are in evaluation order.
        /// </summary>
        /// <remarks>
        /// If the invocation is in its expanded form, then params/ParamArray arguments would be collected into arrays. 
        /// Default values are supplied for optional arguments missing in source.
        /// </remarks>
        ImmutableArray<IArgumentOperation> Arguments { get; }
    }
```

`TargetMethod` is guaranteed to be non-null, but `Instance` may be null for static methods. For overload resolution failures, we generate an `IInvalidOperation` not an `IInvocationOperation`.

We have our [TestOperationVisitor](http://source.roslyn.io/#Roslyn.Test.Utilities/Compilation/TestOperationVisitor.cs,f1ab5572f2538701) that makes these contracts explicits, and this visitor is executed as part of every Roslyn compiler unit test. We have ensure that the documentation on `IOperation` nodes matches the contracts in this visitor, and any discrepancies between them or lack of documentation on public APIs for existing asserts in this visitor should be treated as bugs.

**Comment by 333fred** [comment]
That being said, I can see the demand for having an analyzer option that only runs over "lines" that user is not actively editing, though the granularity of that statement is definitely a question. @bkoelman, what granularity would you envision that being on? Would you expect _all_ code to have no compile errors, or would you expect to only be run on statements that have no syntactic or semantic errors? The latter could be difficult, because there are scenarios where there are diagnostics but the statement is otherwise complete (such as returning something that isn't implicitly convertible to the return type).

**Comment by bkoelman** [comment]
> For overload resolution failures, we generate an `IInvalidOperation` not an `IInvocationOperation`.

Although operation contracts are mostly well-documented, syntax nodes are not. And if operations are turned into `IInvalidOperation` in case of errors (instead of a halfly-populated object) then I'm satisfied and this issue concerns symbols and syntax only.

> (such as returning something that isn't implicitly convertible to the return type)

Then I would expect an `IInvalidOperation` instead of `IReturnOperation` with `.ReturnedValue` being `null`. But since `ReturnedValue` is typed as `IOperation` it may return any operation (including `IInvalidOperation`). So I need to try-cast, which is expected. Just the property being `null` is unexpected.

As I tried to point out, documenting is sub-optimal because these contracts change over time. Nobody is going to re-read all documentation and re-rationalize nullability in all their analyzer code, each time a new version of roslyn comes out. Especially since API *changes* do not get published. So I think all analyzer authors would benefit if such details are coded in the compiler itself behind a mechanism, because the compiler team can best determine when code is broken, how that affects the AST and how that changes over time.

> what granularity would you envision that being on?

The syntax/symbol/operation node itself and its subtree. I am mostly concerned about hitting expected `NullReferenceException` *when traversing properties that are not documented to be null in case of broken code*. When I try to correlate data from individual nodes myself, then I expect that may fail. Similar to how I expect that `Compilation.GetTypeByMetadataName("System.Boolean")` may fail.

Some more examples: I only want to reason about and report on the cases in a switch statement when there are no duplicate case labels (because I put them in a dictionary and did not consider duplicates may occur). I do not want to analyze `if` statements that have no condition. Or methods that have no name yet. Or locals without a name or type. Or loops without a body. Or execute dataflow analysis (expensive) on the method parameters when the method body has errors like 'unassigned `out` parameter' and '`in` parameter is being written to'.

If all this means my analyzer must run later in the compiler-pipeline I would be fine with that.

**Comment by CyrusNajmabadi** [comment]
> Some more examples: I only want to reason about and report on the cases in a switch statement when there are no duplicate case labels (because I put them in a dictionary and did not consider duplicates may occur)

Note: this is hard to rationalize with:

> The syntax/symbol/operation node itself and its subtree. 

Because perhaps your tree will have *no* errors underneath it, but there are still errors elsewhere that break the invariants you have assumed in your own code.  For example, maybe you are analyzing the entire switch, and there are no errors in the switch, but the switch switches over an an enum that *itself* has errors (for example, duplciated enum members).  If you then walked the enum, and added those members to something (Assuming they were unique) you might then crash there.

--

So, really, it sounds like you're trying to say "i only want to run if there are *no* erorrs at all. that way i can assume all the code i may look at is totally cool and i don't have to worry about anything".

IMO, such a thing *would* be valuable.  HOwever, it would also be very limiting.  You would likely rarely run, and you'd only really run after a successful compilation.  If that was ok with you, great.  But if you want finer grained granularity, then things are going to get far more complex (and you're still going ot have to run into issues where the tree underneath you is fine, but other code you go look at is now not ok and you crash on that).

**Comment by CyrusNajmabadi** [comment]
> I do not want to analyze if statements that have no condition. Or methods that have no name yet. Or locals without a name or type. Or loops without a body.

ONe of the simplest things you can do is just call: SyntaxNode.HasDiagnostics.  Or call SyntaxNode.GetDiagnostics() and check for Errors (since warnings are also put on nodes/tokens).  All of the above cases would hit this.

**Comment by bkoelman** [comment]
Great tips, thanks.

**Comment by mavasani** [comment]
@bkoelman I believe @CyrusNajmabadi has made very good arguments explaining our current stance and has also provided workaround(s) in case you still want to execute only when there are no errors/diagnostics. We are responsible for documenting and validating the tree shapes (syntax and semantic) and the analyzer authors are responsible for understanding the possible values of child nodes when analyzing an operation node's sub-tree. You are free to have checks upfront in your analyzer to reduce the scope of your execution, but this not something we plan to add to the analyzer API anytime soon. Is it fine to close this issue?

**Comment by heejaechang** [comment]
perhaps, all they want is us using nullable reference in API so that user know which API they need to expect null or not.
