### ISSUE TITLE
Auto format document with config styles sorts usings incorrectly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28148]
The .editorconfig has this line in it:

dotnet_sort_system_directives_first = true:suggestion

But applying the new format document incorrectly sorts the usings to put the System in alphabetical order instead of the top.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/281386/auto-format-document-with-config-styles-sorts-usin.html
VSTS ticketId: 638859_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by JieCarolHu** [comment]
We have different types of options in .editorconfig
bool option only support <bool>
Code style options support <bool>:<notification level>

dotnet_sort_system_directives_first is a bool option, so it only supports true or false. It will work if you set:
dotnet_sort_system_directives_first = true

**Comment by onovotny** [comment]
I'm not sure I understand. I have true, with a severity specified...
