### ISSUE TITLE
Capture crash information for devenv.exe in integration tests

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#28169]
This could be done with procdump or by recording the .NET event logs after a crash.

/cc @jaredpar @dotnet/roslyn-infrastructure

**Comment by jaredpar** [comment]
For context: today during CI procdump is attached to every process explicitly launched by our test runner. The devenv process is indirectly launched and as such procdump is not attached.

**Comment by sharwell** [comment]
This was resolved by using registry keys:

https://github.com/dotnet/roslyn/blob/c9a68b6a2fed69b1a48505b401dd1bb3d09dc45a/eng/build.ps1#L332-L336
