### ISSUE TITLE
AnalyzerRunner rocks!

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#28161]
No issue this time. Just wanted to express my happiness about AnalyzerRunner. It has enabled me very well to investigate analyzer performance. Command-line switches are useful and the logging too. I have been wishing for a tool like this for years!

Thanks a lot for creating and providing it!

Little suggestion: Maybe in time it can move to https://github.com/dotnet/roslyn-sdk and get distributed in binary form.

/cc @sharwell

**Comment by jmarolf** [comment]
@bkoelman can you file and issue on https://github.com/dotnet/roslyn-sdk to add analyzer runner as a tool.  @sharwell are there any issues with licensing?

**Comment by jinujoseph** [comment]
This issue was moved to dotnet/roslyn-sdk#242
