### ISSUE TITLE
IDE0039 'Use local function' suggestion breaks code.

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#28175]
**Version Used**: 

Microsoft Visual Studio Enterprise 2017 Preview
Version 15.8.0 Preview 3

**Steps to Reproduce**:

1.  Write the following code:

```csharp
using System;

namespace IDE0039
{
    public class IDE0039
    {
        void Foo<T1, T2, T3>(Action<T1, T2, T3> func) { }

        public void InvokeFoo()
        {
            Action<object, string, int> func = (o, s, i) => { };
            Foo(func);
        }
    }
}

```

2. Invoke the IDE0039 code-fix on line 11

**Expected Behavior**:

Resulting code is valid C# and still compiles.

**Actual Behavior**:

Error CS0411: The type arguments for method 'IDE0039.Foo<T1, T2, T3>(Action<T1, T2, T3>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

Transformed code:

```csharp
using System;

namespace IDE0039
{
    public class IDE0039
    {
        void Foo<T1, T2, T3>(Action<T1, T2, T3> func) { }

        public void InvokeFoo()
        {
            void func(object o, string s, int i) { }
            Foo(func);
        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
@agocke Is this an expected compiler error?  Note: if you use an lambda, even without a type, this works as expected:

```c#
Foo((object o, string s, int i) => { })
```

This properly infers the type parameters for 'Foo'.  

So it's somewhat surprising that an near equivalent piece of code that uses a local function *with those same parameters, and known return type*, cannot infer properly here.  That definitely doesn't seem expected to me. 

Thoughts?

**Comment by agocke** [comment]
I get the same error if func is a method. This is probably something in overload resolution.

**Comment by mazong1123** [comment]
I'd like to take a look at this one. 

I think we either modify transform the code to the compile-able one:

```
            void func(object o, string s, int i) { }
            Foo<object, string, int>(func);
```

Or improve the inference system to infer `Foo(func);`. Which one could be preferred for current Roslyn design?

**Comment by CyrusNajmabadi** [comment]
@mazong1123 We need information first if the language is behaving as expected.  i'm hoping @agocke and @gafter might be able to shed some light on that.

If this is hte language behaving properly, and we don't want to update the language here, then we either need to:

1. disable the fix in this code.
2. make the change you specified.

For the latter, we have a system to help out here.  Effectively we can 'Expand/Simplify' code as part of a refactoring.  'Expanding' will added these sorts of things (like type parameters), and 'Simplifying' will attempt to remove if possible.  In this case, since it seems not possible to remove, it should do the right thing.

The APIs for this are in the 'Simplifier' class.  Let me know if you need more details.

**Comment by mazong1123** [comment]
@CyrusNajmabadi thanks! It's very helpful. I'll look into `Simplifier` class and get familiar with the whole system.

**Comment by spottedmahn** [comment]
I too get `IDE0039` and when I use it, my code won't compile.

```csharp
//before suggestion
Func<List<TResult>> getDataFunc = () => dataHelper.GetDataFromAQuery<TResult, TProfile>(query);
var results = await Task.Run(getDataFunc);

//after suggestion
List<TResult> getDataFunc() => dataHelper.GetDataFromAQuery<TResult, TProfile>(query);
var results = await Task.Run(getDataFunc);
```
>Error	CS0121	The call is ambiguous between the following methods or properties: 'Task.Run\<TResult>(Func\<TResult>)' and 'Task.Run(Func\<Task>)'

**VS Version:** 15.9.4

Is this the same case or a different case?

**Comment by CyrusNajmabadi** [comment]
Not repro.  I get:

![image](https://user-images.githubusercontent.com/4564579/199097041-463c4023-d4f8-44e1-b13f-178348cbdcf0.png)

which is expected.
