### ISSUE TITLE
VBCSCompiler is still being treated as critical process

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#28174]
According to https://github.com/dotnet/roslyn/issues/24610 and https://developercommunity.visualstudio.com/content/problem/164302/visual-studio-updates-should-not-hang-on-vbcscompi.html, vbcscompiler should no longer be treated as critical process in 15.7. But testing on the latest internal build of 15.8, it still is.

**Version Used**: 
Setup: 1.17.1250.618
VS: Version 15.8.0 Preview 4.0 [27821.3001.d15.8stg]

**Steps to Reproduce**:

1. File -> New Console App (.NET Framework)
2. Build
3. Close VS
4. Open Visual Studio Installer
5. In the same instance as above, modify installation by unchecking/checking an optional feature and choose Install

**Expected Behavior**:
Install to proceed without prompts

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/1103906/42011508-0d93e4d4-7ad7-11e8-99de-01e480e498a9.png)

**Comment by agocke** [comment]
Everything looks fine on the compiler side. We should loop Setup into this @jaredpar

**Comment by davkean** [comment]
It looks like this gets into a catalog.json, any idea where that is stored or how it is produced?

**Comment by jaredpar** [comment]
This is fixed now.
