### ISSUE TITLE
Experimental "fix accessibility modifiers" option does not respect dotnet_style_require_accessibility_modifiers in editor config

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28176]
When the following is set in the editor config: &quot;dotnet_style_require_accessibility_modifiers = never&quot;

The new experiemental option in Visual Studio Preview &quot;fix accessibility modifiers&quot; adds accessbilitity modifiers despite being set to never.

Note the option is located in: Options &gt; Text Editor &gt; C# &gt; Code Style &gt; Formatting &gt; General

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/281438/experimental-fix-accessibility-modifiers-option-do.html
VSTS ticketId: 638951_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by JieCarolHu** [comment]
Tried on the latest 15.8 Preview 5 (27922),  cannot repro this bug and the dotnet_style_require_accessibility_modifiers = never works as expected
