### ISSUE TITLE
Feature request: null coalescing code fix for wider scenarios

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#28180]
### Before
```csharp
var c = source as C;
if (c == null)
    throw new ArgumentException();
// use c
```

### After
```csharp
var c = source as C ?? throw new ArgumentException();
```

### Update
This actually applies for every scenario that initializes an variable and compares to null.
```csharp
var c = something;
if (c == null)
    throw new Exception();
```
comes to:
```csharp
var c = something ?? throw new Exception();
```

Current code fix seems to only apply when `something` is a variable or parameter, not expression?

**Comment by CyrusNajmabadi** [comment]
@huoyaoyuan can you give an example that doesn't work that you want to work?
