### ISSUE TITLE
ArgumentException at AbstractCodeGenerationService.CheckDeclarationNode

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#282]
Ported from TFS WorkItem: <b>1096007</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P><B>Affected Branch:</B> <BR><B>Affected Build:</B> <BR><B>Affected Product Language:</B> <BR><BR><B>Steps to reproduce:</B><BR><BR>From activity log:</P>
<P>&nbsp;</P>
<P>&lt;description&gt;System.AggregateException: One or more errors occurred. ---&amp;gt; System.ArgumentException: Destination type must be a EnumDeclarationSyntax, TypeDeclarationSyntax or CompilationUnitSyntax.<BR>Parameter name: destination<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.CheckDeclarationNode[TDeclarationNode1,TDeclarationNode2,TDeclarationNode3](SyntaxNode destination)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationService.AddField[TDeclarationNode](TDeclarationNode destination, IFieldSymbol field, CodeGenerationOptions options, IList`1 availableIndices)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.&amp;lt;&amp;gt;c__DisplayClass35.&amp;lt;AddFieldAsync&amp;gt;b__36(SyntaxNode t, CodeGenerationOptions opts, IList`1 ai)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.&amp;lt;GetEditAsync&amp;gt;d__1.MoveNext()<BR>--- End of stack trace from previous location where exception was thrown ---<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.GenerateMember.GenerateVariable.AbstractGenerateVariableService`3.GenerateVariableCodeAction.&amp;lt;GetChangedDocumentAsync&amp;gt;d__1.MoveNext()<BR>--- End of stack trace from previous location where exception was thrown ---<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeActions.CodeAction.&amp;lt;GetChangedSolutionAsync&amp;gt;d__1.MoveNext()<BR>--- End of stack trace from previous location where exception was thrown ---<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeActions.CodeAction.&amp;lt;ComputeOperationsAsync&amp;gt;d__1.MoveNext()<BR>--- End of stack trace from previous location where exception was thrown ---<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeActions.CodeAction.&amp;lt;ComputePreviewOperationsAsync&amp;gt;d__1.MoveNext()<BR>--- End of stack trace from previous location where exception was thrown ---<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeActions.CodeAction.&amp;lt;GetPreviewOperationsAsync&amp;gt;d__1.MoveNext()<BR>--- End of stack trace from previous location where exception was thrown ---<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.&amp;lt;&amp;gt;c__DisplayClass8.&amp;lt;&amp;lt;GetPreview&amp;gt;b__10&amp;gt;d__0.MoveNext()<BR>&nbsp;&nbsp; --- End of inner exception stack trace ---<BR>&nbsp;&nbsp; at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)<BR>&nbsp;&nbsp; at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.&amp;lt;&amp;gt;c__DisplayClass8.&amp;lt;GetPreview&amp;gt;b__9()<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunction[T](IExtensionManager extensionManager, Object extension, Func`1 function, T defaultValue)<BR>---&amp;gt; (Inner Exception #0) System.ArgumentException: Destination type must be a EnumDeclarationSyntax, TypeDeclarationSyntax or CompilationUnitSyntax.<BR>Parameter name: destination<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.CheckDeclarationNode[TDeclarationNode1,TDeclarationNode2,TDeclarationNode3](SyntaxNode destination)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationService.AddField[TDeclarationNode](TDeclarationNode destination, IFieldSymbol field, CodeGenerationOptions options, IList`1 availableIndices)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.&amp;lt;&amp;gt;c__DisplayClass35.&amp;lt;AddFieldAsync&amp;gt;b__36(SyntaxNode t, CodeGenerationOptions opts, IList`1 ai)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.&amp;lt;GetEditAsync&amp;gt;d__1.MoveNext()<BR>--- End of stack trace from previous location where exception was thrown ---<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.GenerateMember.GenerateVariable.AbstractGenerateVariableService`3.GenerateVariableCodeAction.&amp;lt;GetChangedDocumentAsync&amp;gt;d__1.MoveNext()<BR>--- End of stack trace from previous location where exception was thrown ---<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeActions.CodeAction.&amp;lt;GetChangedSolutionAsync&amp;gt;d__1.MoveNext()<BR>--- End of stack trace from previous location where exception was thrown ---<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeActions.CodeAction.&amp;lt;ComputeOperationsAsync&amp;gt;d__1.MoveNext()<BR>--- End of stack trace from previous location where exception was thrown ---<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeActions.CodeAction.&amp;lt;ComputePreviewOperationsAsync&amp;gt;d__1.MoveNext()<BR>--- End of stack trace from previous location where exception was thrown ---<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.CodeActions.CodeAction.&amp;lt;GetPreviewOperationsAsync&amp;gt;d__1.MoveNext()<BR>--- End of stack trace from previous location where exception was thrown ---<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<BR>&nbsp;&nbsp; at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<BR>&nbsp;&nbsp; at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.&amp;lt;&amp;gt;c__DisplayClass8.&amp;lt;&amp;lt;GetPreview&amp;gt;b__10&amp;gt;d__0.MoveNext()&amp;lt;---<BR>&lt;/description&gt;<BR></P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By David Poeschl (12/14/2014 3:34:17 PM)

Who owns the code generation service?

------------------------------

2) Edited By Kevin Pilch-Bisson (12/15/2014 9:44:47 AM)

Will this go away with Matt's changes?

------------------------------

3) Edited By Srivatsn Narayanan (12/15/2014 10:27:48 AM)

When Matt moves the IDE over to the new API and deletes codegenerationservice, it would go away i suppose :)

------------------------------

**Comment by mattwar** [comment]
@dpoeschl  Is there any more context to this bug?  Is this still a problem?

The CodeGenerator seems to be throwing because a field is being added to a parent node that is not a enum, type or compilation unit.

**Comment by mattwar** [comment]
There is no actual repro here, just a call stack.  It is unclear how the problem came to be, but from examination of the call stack, the code generator is only throwing because its been asked to add a field to a symbol that cannot contain a field.  It is possible the refactoring is being offered on the wrong symbol.

**Comment by jasonmalinowski** [comment]
According to telemetry, this is one of top crashes we're currently seeing in Visual Studio 2015 in Roslyn. I'm adding crash dump information in the internal bug mentioned in the original bug information.

**Comment by mattwar** [comment]
With crash dumps I was able to narrow this down to an Encapsulate Field refactoring being offered on a field declaration outside of a class declaration.  In this case, it is in a namespace (not global) and so it is not even technically legal script code.  However, the compiler still parses it as a FieldDeclarationSyntax and it is still assigned a symbol.  

Two problems:
1. We shouldn't be offering this refactoring in this case
2. The Lightbulb/suggestions logic is not catching exceptions from code action providers in this code path.

The code path travels through LightBulbMenuItem.HasNestedActions property which triggers execution of the code action previews.
