### ISSUE TITLE
VB prettylister gets spacing wrong for labels in With statement

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#2822]
Repro: write this code
```vb
Module Module1
    Sub Main()
        With New List(Of Integer)
            .Capacity = 15
        End With
    End Sub
End Module
```
Now add a "label:" on the line that assigns to Capacity, and cursor-down.

What I get: only a single whitespace between label and ".Capacity". What I expect: the label shouldn't change the alignment of the statement.

![vb-misformat](https://cloud.githubusercontent.com/assets/3316258/7664386/6c4dabc0-fb39-11e4-826b-312c5815fd0f.png)

(Note: this issue was first reported via "send-a-frown" in VS).

**Comment by dpoeschl** [comment]
Tested with yesterday's ```1.0 (stable)``` build. Looks good.

![image](https://cloud.githubusercontent.com/assets/235241/8196645/b89c7962-1442-11e5-9184-0fb7658eb304.png)
