### ISSUE TITLE
FindAllReferences should handle `Add` methods used in collection initializers

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#28229]
See comment in `ComputeImplicitReferenceConflictsAsync`: ` // TODO: handle Dispose for using statement and Add methods for collection initializers.`

Relates to https://github.com/dotnet/roslyn/pull/28230

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/66700.
