### ISSUE TITLE
Does RunAsync gurantee running on a separate thread?

### ISSUE THREAD

**Issue by pongba** [dotnet/roslyn#28235]
I was doing some performance bechmarking and found that RunAsync is actually running on my current thread, so I have two questions:

1. Is this behavior expected? Because I'm trying to do this and RunAsync being actually synchronous will break my code:
```csharp
var task = script.RunAsync(globals);
task.Wait(1000/*ms*/);
```
since RunAsync only returns after script completes the run, there's no point in task.Wait(...).

2. But I don't want to simply "wrap up" the RunAsync in a separate thread either, because it could be the case that under some circumstances the RunAsync would _actually_ truely run asynchronously (is it?)

**Comment by ufcpp** [comment]
Yes, it is expected.

```cs
async Task RunAsync()
{
    // runs synchronously
    await Task.Run(() => {});
    // runs with TaskScheduler (ThreadPool by default)
}
```

**Comment by pongba** [comment]
@ufcpp Thanks! Could you elaborate a little bit? I'm not sure I follow. Why would a method called XxxAsync not run asynchronously?

**Comment by ufcpp** [comment]
```cs
async void RunAsync()
{
    // A
    await Task.Delay(1);
    // B
    await Task.Delay(1);
    // C
}
```

↓
compiler-generated code:

```cs
    Action a = null;
    int state = 0;

    a = () =>
    {
        Task t = null;
        switch (state)
        {
            case 0:
                // A
                state = 1;
                t = Task.Delay(1);
                break;
            case 1:
                // B
                state = 2;
                t = Task.Delay(1);
                break;
            case 2:
                // C
                state = 3;
                return;
            default:
                return;
        }
        if (t.IsCompleted) a();
        else t.ContinueWith(_1 => a());
    };
    a();
}
```

↓

similar execution flow:

```cs
void RunAsync()
{
    // A
    Task.Delay(1).ContinueWith(_ =>
    {
        // B
        await Task.Delay(1).ContinueWith(__ =>
        {
            // C
        }
    })
}
```

**Comment by sharwell** [comment]
@pongba This appears to be an external issue, but to point you in the right direction I need to know the type of `script` in your example.

**Comment by pongba** [comment]
@sharwell thanks. Here's my code:

**script.csx**
```csharp
#r "System"

using System;
using System.Threading;

Console.WriteLine("I'm a sleeping beauty..");
Thread.Sleep(1000000); 
```

**main.cs**
```csharp
var content = File.ReadAllText("script2.csx");
var script = CSharpScript.Create<int>(content);
var c = script.Compile();
var task = script.RunAsync();
Console.WriteLine("script should still be running..");
```

**Expected Behavior**:
I'm a sleeping beauty..
script should still be running..

**Actual Behavior**:
I'm a sleeping beauty..

**Remarks**
It's not that I don't understand why the behavior is so, what I don't get is why the API semantics is "synchronously run the script" while the naming is xxxAsync - I don't see where the async behavior is, did I miss anything?

**Comment by pongba** [comment]
I think I know the reason now, here's what I think: (@sharwell correct me if I'm wrong here)

The RunAsync doesn't mean the C#Script is being run on a separate thread, but rather it means the script can use `await` to make itself `async`, e.g.:

**script2.csx**
```csharp
#r "System"

using System;
using System.Threading;
using System.Threading.Tasks;

await Task.Run(()=> { Console.WriteLine("I'm a sleeping beauty..."); Thread.Sleep(1000*10); Console.WriteLine("I'm awake.."); });
Console.WriteLine("ending script");
123
```
**main.cs**
```csharp
static void test0()
{
    var content = File.ReadAllText("script2.csx");
    var script = CSharpScript.Create<int>(content);
    var c = script.Compile();
    var task = script.RunAsync();
    Console.WriteLine("{0}: script should still be running..", DateTime.Now);
    Console.WriteLine("{1}: script result: {0}", task.Result.ReturnValue, DateTime.Now);
}
```
or more precisely, the (generated-by-Roslyn since C#script doesn't explicitly declare entry point method) implicit entry point method of the C#script is marked as an `async` method:
```csharp
// in ScriptBuilder.cs
private Func<object[], Task<T>> Build<T>(
    // ...
    return runtimeEntryPoint.CreateDelegate<Func<object[], Task<T>>>();
}
```

**Comment by sharwell** [comment]
> In short, RunAsync means the scripting code is treated effectively as an async method, not that the method itself is invoked on a separate thread.

Yes, this is correct. The behavior of `RunAsync` is consistent with the general guarantees of other asynchronous methods in the framework (i.e. the method is allowed but not guaranteed to yield before returning). If you want to force the code to run asynchronously, you can call the method like this:

```csharp
var task = Task.Run(() => script.RunAsync());
```
