### ISSUE TITLE
Project Context switch icon changes when moving caret

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#28236]
**Version Used**: 
VisualStudio.15.Preview/15.8.0-pre.3.0+27825.0

When moving the caret, the icon in projects context switch changes back and forth between icons:
![icons](https://user-images.githubusercontent.com/1103906/42146159-612a1cdc-7e09-11e8-8023-600cfc0fcd94.gif)

**Comment by davkean** [comment]
tag @jasonmalinowski

**Comment by jasonmalinowski** [comment]
Oh that's cute. :smile:

**Comment by jasonmalinowski** [comment]
So I think this is what is going on, with some help from @olegtk:

The navigation bar APIs only speak in terms of legacy HIMAGELISTs, so we go through a [particularly gnarly bit of code](https://github.com/dotnet/roslyn/blob/2868849409d44fcd5ecb84bef45575a98018a8c6/src/VisualStudio/Core/Def/Implementation/Extensions/VisualStudioWorkspaceImplExtensions.cs#L25-L66) to go from the ImageMoniker we get from the IVsHierarchy and convert it to an HIMAGELIST. The expected lifetime of this HIMAGELIST is pretty unclear but it's further muddied in two ways:

1. Roslyn has a cache (`s_hierarchyToItemIdToImageHandle`) that seemingly _tries_ to ensure the HIMAGELIST is alive for the duration of the hierarchy's existence, but it has one fatal flaw: if somebody asks for the image for the same IVsHierarchy/itemid pair again, it creates a new list and overwrites the old one, so the old one is eligible to be reclaimed.
2. The editor has a caching system which Roslyn is opted into, which assumes that HIMAGELIST is a safe key to use in a cache lookup, i.e. an imagelist (by _handle_) cannot change once one has been created.

These behaviors conspire. Roslyn might end up causing image lists to disappear and get recreated, with different contents. If the HIMAGELIST happens to be the same as a previous one given, then the editor will reuse old icons which could be any other icon we had from somewhere else.

The easy fix here would be to opt Roslyn out of the caching (there's is a flag to do exactly that), but @olegtk pointed out it might be masking other bugs here we don't realize yet. Roslyn could match the expected contract here of the cache and just keep moniker to HIMAGELIST maps around forever, which is a sane change and although a memory leak in some sense it's probably fine. @olegtk also pointed out that we should really just deprecate this and give navbar a proper way to hand ImageMonikers around directly, which would avoid both sides having to work around each other's insanity.

@davkean and @jinujoseph, how much do you want this for 15.8? I can make changes here, but @olegtk correctly points out this might be better in the long run just to add a new API which avoids all this dancing around in the first place.

**Comment by jasonmalinowski** [comment]
FWIW, the code we have is also being used by the 'preview changes' dialog, so it's entirely possible fixing this is also necessary there too. @ivanbasov any idea if we've seen any crashes in the preview changes dialog around icon handling?

**Comment by jinujoseph** [comment]
@jasonmalinowski is this a regression ? if so what caused it ? 
I think we should investigate to handle this in 15.8 , new API addition seems like a long term work so we should provide a workaround in the mean time if possible.

**Comment by jasonmalinowski** [comment]
I'm guessing this has always been broken, but we might have not noticed; test projects having a new icon would mean we have a chance of seeing this now in our own dogfooding.

**Comment by jasonmalinowski** [comment]
@jinujoseph I'm guessing this has always been broken, but we might have not noticed; test projects having a new icon would mean we have a chance of seeing this now in our own dogfooding.

**Comment by olegtk** [comment]
From the editor perspective this is a legacy troublesome component with inadequate-to-absent test coverage. It would be very risky to make any changes now that we are in Escrow. Let's just fix it the right way in Dev16.

**Comment by davkean** [comment]
This makes editing files inside of a test project in the new project system very annoying due to the distracting icon change. Why does legacy test projects icon not show in that drop down? Can we cheaply do the same thing for CPS projects?

**Comment by jasonmalinowski** [comment]
@olegtk Was a new API for using ImageMonikers landed? I know I saw the work.

**Comment by 333fred** [comment]
An example I'm having while working in Compilers.sln.
![image](https://user-images.githubusercontent.com/2371880/48236053-6df12880-e375-11e8-93ff-0ba3804e09f2.png)

**Comment by olegtk** [comment]
Should ready for Preview2, API is already in d16.0stg, inserting editor support today.

**Comment by jasonmalinowski** [comment]
Fix is now merged to use the new editor API. Thanks @olegtk!
