### ISSUE TITLE
CSharpScript WithReferences vs WithImports

### ISSUE THREAD

**Issue by soul4soul** [dotnet/roslyn#28234]
What are the differences between `WithReferences` and `WithImports`? The [documentation](https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples) shows a code snippet for how to use each but no description of what is actually happening.

**Comment by tmat** [comment]
I have updated the [documentation](https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples#addimports) with more details. Hope this helps to clarify.

**Comment by soul4soul** [comment]
That does help. I was hoping to figure out how to automatically add using statements to my scripts. So now I can confirm `*Imports` are the methods I want to use. 

1. In the example
```csharp
var result = await CSharpScript.EvaluateAsync("Sqrt(2)", 
     ScriptOptions.Default.WithImports("System.Math"));
```
Why does this add a `using static System.Math` instead of just `using System.Math`?


2. Based on the documentation I was expecting the following to work but it doesn't.
```csharp
    var result = CSharpScript.RunAsync("Thread.Sleep(5000);Console.WriteLine(\"Hello\");",
           ScriptOptions.Default.WithImports("System.Threading", "System.Console"));
```
I get an exception `ex.Message = "(1,20): error CS0103: The name 'Console' does not exist in the current context"`


3. Can you add documentation for the `WithReferences` method?

4. What is the difference between the `Add` and the `With` methods? Is it true that `WithImports` will overwrite the currently configured set of imports with new imports. Where as `AddImports` keeps the currently configured set of imports plus adds the new imports?

**Comment by tmat** [comment]
> Why does this add a using static System.Math instead of just using System.Math?

Because `System.Math` is a type, not a namespace.

> I get an exception ex.Message = "(1,20): error CS0103: The name 'Console' does not exist in the current context"

`System.Console` is a type, so the import imports its members. Change it to `System`.

> Is it true that WithImports will overwrite the currently configured set of imports with new imports. Where as AddImports keeps the currently configured set of imports plus adds the new imports?

Yes.

**Comment by soul4soul** [comment]
I should of reviewed the documentation more closely. Thank you for clarifying that information. 

I'm just putting this here so others can possible find the information. In order to setup the environment so a script can access code from a custom assembly and namespace both `WithImports` and `WithReferences` must be used. 

```csharp
using MyCompany.MyNamespace;

ScriptOptions.Default.WithReferences(typeof(MyType).Assembly)  // This adds a reference, assuming MyType is a type defined within the MyCompany.MyNamespace
                     .WithImports("MyCompany.MyNamespace"); // This adds a using statement
```
