### ISSUE TITLE
Overload resolution weirdness

### ISSUE THREAD

**Issue by IanKemp** [dotnet/roslyn#28237]
Visual Studio 2017 version 15.7.4, Windows 10 x64 version 1803 (build 17134.112)

The following code compiles:

```csharp
public static class ArrayExtensions
{
    public static bool Equals(this Array left, Array right)
    {
        return true; // actual implementation irrelevant
    }
}

class Program
{
    static void Main(string[] args)
    {
        bool a = true, b = false;

        ArrayExtensions.Equals(a, b); // compiles!!!
    }
}
```

Inspecting the output reveals that the `ArrayExtensions.Equals` line is silently being transformed to `object.Equals` which is what allows the code to compile. The IDE also grays out "ArrayExtensions" and suggests a code fix that rewrites it as just "Equals" (the same as the output, in other words).

I *assume* this is in some way related to overload resolution, since... well... nothing else makes sense. To my mind it should be a straight compile error, because `ArrayExtensions.Equals` is explicitly being invoked.

**Comment by gafter** [comment]
`ArrayExtensions` contains three `Equals` methods - two are inherited from `object` and one you've declared. Overload resolution has selected the only one of these that works for the actual arguments.
