### ISSUE TITLE
Request: Use Levenshtein distance (or similar) to improve errors in the event of a misspelled ctor name

### ISSUE THREAD

**Issue by Phrohdoh** [dotnet/roslyn#28244]
Say I have a class:

```csharp
public class ClassA { }
```

I add a ctor but misspell it accidentally:

```csharp
public class ClassA
{
    public ClasA() { ... }
}
```

Instead of getting `error CS1520: Method must have a return type` it would be more helpful to get something similar to the following:

```
error <code>: Did you mean to make the method `ClasA` a constructor for `ClassA`?

hint: Method `ClasA` does not specify a return type and is similar in spelling to the containing type `ClassA`
```

I'm sure this could be expanded to other areas but I believe this would be immediately beneficial with the smallest surface area.

---

This issue was moved from [dotnet/csharplang](https://github.com/dotnet/csharplang/issues/1688) to here.

**Comment by Phrohdoh** [comment]
@HaloFour suggested implementing this as an analyzer.

I believe this would be most useful if this were shipped, by default, to all users.

Is it possible to write an analyzer that would get shipped to everyone, or would a nuget package need to be discovered by every user before they could benefit?

**Comment by CyrusNajmabadi** [comment]
Fix available here: https://github.com/dotnet/roslyn/pull/28245

**Comment by CyrusNajmabadi** [comment]
Fix looks like:

![image](https://user-images.githubusercontent.com/4564579/42187751-feb5bb90-7e05-11e8-8c73-cfc3a7f4d245.png)

**Comment by Phrohdoh** [comment]
Does this change the `dotnet` CLI experience at all?

**Comment by CyrusNajmabadi** [comment]
> I believe this would be most useful if this were shipped, by default, to all users.

Sure, that's true of *everything*.  but we really can't follow that policy.  otherwise, all that would end up up with is that we'd have to ship 100% of all analyzers with the compiler all the time.

**Comment by CyrusNajmabadi** [comment]
> Does this change the dotnet CLI experience at all?

Ideally no. This should only change the experience for people who use Roslyn's built 'Feature-Layer' analyzers.

**Comment by Phrohdoh** [comment]
I figured so which is why I was hoping for a more specific / helpful error message and hit.

But some change is better than none!

**Comment by CyrusNajmabadi** [comment]
> I figured so which is why I was hoping for a more specific / helpful error message and hit.

The problem here is that the space of "specific/helpful" error messages is basically "unbounded".  For example, should the compiler also scan all your referenced assemblies and say: "did you miss adding a 'using X.Y.Z' that has a type called 'Blorp' in it?".   

What about scanning *all* assemblies on the machine an saying "did you miss referencing this possible assemby, and and adding this using, and changing the spelling like so...?" etc. etc. etc.

We've purposefully kept he compiler lean and mean in terms of this sort of thing.  We then have the entire analyzer ecosystem that can then decide what's the suitable amount of "effort" and "smarts" that can go into the analysis.

**Comment by Phrohdoh** [comment]
Then as you and @HaloFour have said this should be implemented as an analyzer instead of directly in the compiler which means it can provide more specific information, IMO.

I do understand that there is a certain threshold of reasonable effort and this is why I've outlined this specific case where you look at a method name and calculate the distance the containing type's name and, if within range, offer a specific fix.

**Comment by CyrusNajmabadi** [comment]
> I do understand that there is a certain threshold of reasonable effort and this is why I've outlined this specific case where you look at a method name and calculate the distance to the containing type's name and, if within range, offer a specific fix.

Understood.  Right now though, the 'certain threshold of reasonable effort' is that spell-checking (i.e. edit-distance checking) is past that threshold.  Happy to improve things in the higher layers though where it does fall in the threshold though :)
