### ISSUE TITLE
Add SymbolDisplay option to append suffix for unannotated reference types

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#28242]
There are currently `SymbolDisplay` options to append a suffix for the display of nullable and non-nullable reference types. Consider appending a suffix for unannotated types as well, perhaps `~`.
```
string?
string!
string~
```
Perhaps rename the existing `IncludeNonNullableTypeModifier` option and use a single option to specify whether a suffix is added for non-nullable and unannotated types.

**Comment by cston** [comment]
cc @jcouv

**Comment by jcouv** [comment]
@jasonmalinowski @333fred @cston Do you think we need such an option?
I'm tempted to close this issue until we have an explicit driving scenario.

**Comment by 333fred** [comment]
I would agree. No one but the compiler team would even understand what a ~ even means.
