### ISSUE TITLE
Incorrect suggestion in the Visual Studio for object creation by global namespace

### ISSUE THREAD

**Issue by GeorgeAlexandria** [dotnet/roslyn#28258]
Hi,

I'm used **Visual Studio 15.6.6**. 
When I try to create a new object, that is contained in a referenced assembly and its namespace is a part of my custom namespace (for example Newtonsoft.Json ), Intellisense give to me the correctly determined suggestion, look at the image below:

![globalavoidexample](https://user-images.githubusercontent.com/13402478/42211223-b717306e-7ebb-11e8-85d5-89efc4e4b1b0.png)

but after applying it doesn't put the global namespace as prefix for correct usages, and, of course, I receive compile time errors at the code below:

```c#
using System;

namespace MyNamespace.Newtonsoft.Json
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            global::Newtonsoft.Json.JsonSerializerSettings settings = new Newtonsoft.Json.JsonSerializerSettings
        }
    }
}
```

If this issue should be moved to the [Visual Studio Community](https://developercommunity.visualstudio.com/spaces/8/index.html) instead of Roslyn repository, let me know about it.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lacck of feedback.
