### ISSUE TITLE
CS0695 reported for type parameters that do not unify

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#28255]
```c#
interface I<T> { }
class C<T, U> : I<T>, I<U>
    where T : struct
    where U : class
{
}
```
```
(2,7): error CS0695: 'C<T, U>' cannot implement both 'I<T>' and 'I<U>' because
they may unify for some type parameter substitutions
```

**Comment by cston** [comment]
Same error reported for:
```c#
interface I<T> { }
class A { }
class B { }
class C<T, U> : I<T>, I<U>
    where T : A
    where U : B
{
}
```

**Comment by gafter** [comment]
Not a bug. According to [the specification](https://github.com/dotnet/csharplang/blob/master/spec/interfaces.md#uniqueness-of-implemented-interfaces):

> If any possible constructed type created from `C` would, after type arguments are substituted into `L`, cause two interfaces in `L` to be identical, then the declaration of `C` is invalid. **Constraint declarations are not considered when determining all possible constructed types**.

(my emphasis)
