### ISSUE TITLE
Undo granularity for completion is too coarse

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#28251]
**Version Used**: 

**Steps to Reproduce**:

1. Add the following code

    ```csharp
    public class Class1
    {
        void Repro()
        {
            Example(1);
            Example("1");
        }

        void ExampleTakesString(string value)
        {
        }

        void ExampleTakesInt32(int value)
        {
        }
    }
    ```

2. Place the caret at the end of the first call to `Example`
3. Press <kbd>Ctrl</kbd>+<kbd>Space</kbd>, then <kbd>Tab</kbd>
4. Place the caret at the end of the second call to `Example`
5. Press <kbd>Ctrl</kbd>+<kbd>Space</kbd>, then <kbd>Tab</kbd>
6. Press <kbd>Ctrl</kbd>+<kbd>Z</kbd> (Undo)

**Expected Behavior**:

Only the second completion is undone, leaving the following:

```csharp
public class Class1
{
    void Repro()
    {
        ExampleTakesInt32(1);
        Example("1");
    }

    void ExampleTakesString(string value)
    {
    }

    void ExampleTakesInt32(int value)
    {
    }
}
```

**Actual Behavior**:

Both completions are undone, leaving the original code:

```csharp
public class Class1
{
    void Repro()
    {
        Example(1);
        Example("1");
    }

    void ExampleTakesString(string value)
    {
    }

    void ExampleTakesInt32(int value)
    {
    }
}
```

**Notes**:

This is a regression from the behavior of Visual Studio 2013 first introduced in Visual Studio 2015.

**Comment by CyrusNajmabadi** [comment]
I'm going to close this out as even if it is a regression, we've gotten absolutely no feedback on it.  At this point, i'd be worried about changing again and screwing up someone new.
