### ISSUE TITLE
Right-click SuppressMessage in source file puts [SuppressMessage] attribute above XML doc comments

### ISSUE THREAD

**Issue by rkeithhill** [dotnet/roslyn#2825]
I have some CA1001 warnings about types holding disposables should implement IDisposable.  When I right-click on the error (treats warnings as errors is enable), VS puts the attribute *above* the doc comments.  
```C#
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable")]
    /// <summary>
    ///              Implements a node, the building block of a <see cref="XTree"/>.
    /// </summary>
    ///...
    public class Node {
```
This generates an editor error (red squiggle) at start of XML doc comment saying the XML comment has not been placed on a valid language element.

Once I moved the attribute below the XML doc comment and just above the class declaration the editor was happy again.

**Comment by DustinCampbell** [comment]
Fixed with PR #2947.
