### ISSUE TITLE
Question: Is there any way to pass configuration to a Roslyn code analyzer?

### ISSUE THREAD

**Issue by jonathanbyrne** [dotnet/roslyn#28260]
Is there anyway a Roslyn code analyzer can make use of external configuration?  Below are examples of what I was looking for but it appears neither of them are possible.

*  Analyzer has access to MSBuildWorkspace object to read project file settings
*  Analyzer is passed properties on "<Analyzer ... />" tag in project file

**Comment by sharwell** [comment]
We are currently working on the ability for analyzers to access values in **.editorconfig**, but the work is not yet complete. Until then, analyzers can access data provided by AdditionalFiles through the `AnalyzerOptions.TryGetValue` API. An example of this usage can be seen in StyleCop Analyzers (which uses it to read **stylecop.json**):

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/57821a1c4d014e8d80b3e236ff444e0e30d8a112/StyleCop.Analyzers/StyleCop.Analyzers/Settings/SettingsHelper.cs#L136

**Comment by jonathanbyrne** [comment]
Thank you!

**Comment by francisminu** [comment]
Hi,
I have a custom analyzer created. How can I make it to read the rule details from a config (like the DiagnosticId, DiagnosticSeverity etc)
