### ISSUE TITLE
Refactoring options not available when caret immediately to the right

### ISSUE THREAD

**Issue by justcla** [dotnet/roslyn#28266]
Certain code fixes only become available when the caret is on a specific item. For many of these, the code fix will not be available if the caret happens to be at the right of the token.

In this example, I have just typed "2.0". My caret is to the right of the "0". (Indicated in Yellow)
When I open the lightbulb menu there is no option so introduce local var.

![image](https://user-images.githubusercontent.com/17131343/42238974-631e518a-7eb7-11e8-8d9f-4b188eaee1ce.png)

But when I move the caret one position to the left, the options become available.

![image](https://user-images.githubusercontent.com/17131343/42238980-6a0d5d4c-7eb7-11e8-8d8a-e0ed7adfa7be.png)

**Comment by justcla** [comment]
Another example.

Against a string:

![image](https://user-images.githubusercontent.com/17131343/42239036-90a25de0-7eb7-11e8-9aae-16a8d8759808.png)

No option to generate a constant.

Move caret one spot to the left. Now options appear.

![image](https://user-images.githubusercontent.com/17131343/42239100-bc1a2246-7eb7-11e8-90eb-4c815bd2cb96.png)

**Comment by jmarolf** [comment]
Sounds like we need to allow these refactoring to work on larger spans than they do today.

**Comment by CyrusNajmabadi** [comment]
@jmarolf In general, the problem is that most of the features just do a simple 'findtoken' which will find the token on the right of the caret.  They need to check if they're not on anything viable and then look left to see if that works.

**Comment by justcla** [comment]
Wider spans are a different thing. The problem here is that it doesn't find something it's touching.

Is it possible there could be something viable on the right, but you intend the one on the left?
Not sure if it applies to any real Roslyn situations. But it's an issue with Expand Selection because, in the case of the first pic (at the top of the issue), it will choose the right parens instead of the "2.0". Though the right parens might be a viable token, I want the one with the "inner scope". I saw "inner scope" because the same would apply if the caret was just inside the parens - one the left of the "1.0". Here, I wouldn't want left or right preference, but "inner scope" preference so that it would choose the "1.0" before the left parens.

**Comment by CyrusNajmabadi** [comment]
> Is it possible there could be something viable on the right, but you intend the one on the left?
Not sure if it applies to any real Roslyn situations.

It doesn't really.  We don't ever have a situation where two viable things can be touching (in C# or VB) such that the caret is ambiguous.  

These are simply cases where the logic in each of these features for determining what to operate on is simply not written well and did not take "user is on the right side" into account.  They should each be about a 5 minute fix.

> But it's an issue with Expand Selection because, in the case of the first pic (at the top of the issue), it will choose the right parens instead of the "2.0".

Please file another bug if you're seeing issues with expand selection.  These systems are unrelated.

**Comment by jmarolf** [comment]
@CyrusNajmabadi yeah, I guess the right fix is to create some general infrastructure similar to `findtoken` that can be used such that a wider variety of nodes are searched

**Comment by Neme12** [comment]
Isn't "expand selection" just doing a walk up the syntax tree? That means it finds the argument list as the parent node and takes it whole span. This would likely have to be special-cased, possibly in a lot more cases where we'd prefer a different behavior.

**Comment by CyrusNajmabadi** [comment]
> Isn't "expand selection" just doing a walk up the syntax tree? That means it finds the argument list as the parent node and takes it whole span. This would likely have to be special-cased, possibly in a lot more cases where we'd prefer a different behavior.

I think the special casing is: if i was on a node in a list, 'expanding' then just selects the span of all the list members.  If that's hte same as when i started (because the list only contains one element), then go up to the parent like today.

I have a prototype of this working.  Seems reasonable.
