### ISSUE TITLE
Code cleanup runs too slow when there are a lot changes

### ISSUE THREAD

**Issue by JieCarolHu** [dotnet/roslyn#28272]
When doing code clean up for this LanguageParser.cs file with the "Remove this. qualifier" checked, it tooks 100 seconds to finish the cleanup, as it removes hundreds of "this." qualifier.

**Comment by heejaechang** [comment]
@JieCarolHu what is perf if you turn off this qualifier fix?

**Comment by CyrusNajmabadi** [comment]
Sounds like we shoudl just have a specialized fixer here.  I'm willing to write one.  We're likely going through the simplifier, instead of just directly using SyntaxEditor.  

However, like @heejaechang I would like to know how long this takes without this feature checked.

**Comment by JieCarolHu** [comment]
@heejaechang it took 20 seconds if I check all the fixer except the Remove "this." qualifier fixer.

**Comment by CyrusNajmabadi** [comment]
> @heejaechang it took 20 seconds if I check all the fixer except the Remove "this." qualifier fixer.

@JieCarolHu What is the next most expensive fix we are running?

**Comment by heejaechang** [comment]
@JieCarolHu 

what is time of default without "this" qualifier fixer? also what is time of all fixers on except "this" qualifier and unnecessary cast fixer?

also, can you also check in the change we made to add Logger instrument? so that people can run it under perf view to see all the perf marker?

**Comment by CyrusNajmabadi** [comment]
FYI, i've written a fixer here that matches the pattern we should be using as much as possible for all our analzyers/fixers.  With my fix, we do this in under 1 second (down from 60+).

**Comment by CyrusNajmabadi** [comment]
@JieCarolHu Can you try out my branch with yours: https://github.com/dotnet/roslyn/pull/28280

At let me know what the next most expensive thing is?
