### ISSUE TITLE
Integration tests failed with "Could not find a suitable Visual Studio Version"

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#28278]
See https://github.com/dotnet/roslyn/pull/28264#issuecomment-402333155:

The integration test results here were weird. The [release tests](https://ci.dot.net/job/dotnet_roslyn/job/dev15.8-preview3-vs-deps/job/windows_release_vs-integration_prtest/10/) passed without issue and the log looks like it ran the tests, but the [debug tests](https://ci.dot.net/job/dotnet_roslyn/job/dev15.8-preview3-vs-deps/job/windows_debug_vs-integration_prtest/10/) failed with:

```
11:27:49 Could not find a suitable Visual Studio Version
11:27:49 System.Management.Automation.RuntimeException: Could not find a suitable Visual Studio Version
11:27:49 at Get-VisualStudioDirAndId, D:\j\workspace\windows_debug---422252a8\build\scripts\build-utils.ps1: line 376
11:27:49 at Deploy-VsixViaTool, D:\j\workspace\windows_debug---422252a8\build\scripts\build.ps1: line 628
11:27:49 at Test-XUnit, D:\j\workspace\windows_debug---422252a8\build\scripts\build.ps1: line 551
```

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
