### ISSUE TITLE
Publish Output folder

### ISSUE THREAD

**Issue by TakhirMamirov** [dotnet/roslyn#28289]
I'm using the latest 2.8.2 versions of Microsoft.CodeAnalysis and Microsoft.Net.Compilers in VS2017 for my .netcore application. I'm wondering if I should see the bin/roslyn folder on publish? I don't see that either locally or in Azure deployment. Actually, my app doesn't generate the bin folder at all. 

The question came from the next issue. We have MVC app along with API (mentioned above), and this API is deployed under wwwroot/services folder in Azure. Once we're trying to access it in Azure, it throws an error that cannot compile C# 6 feature code using C# 5 compiler. And I'm not sure if adding two roslyn libraries should ever help my API app to compile in Azure.

Any thoughts? I've spent two days on this issue without any luck.

**Comment by jaredpar** [comment]
> I'm wondering if I should see the bin/roslyn folder on publish? I don't see that either locally or in Azure deployment.

No you shouldn't see that. The packages you listed there don't produce that output:

- Microsoft.CodeAnalysis: this is just a simple library
- Microsoft.Net.Compilers: this is the C# / VB compiler + MSBuild tasks packaged up as a build tool. It won't appear in the output of your project. It's really meant for hot fixing builds vs. general consumption.

It sounds like you're looking for the RoslynCodeDomProvider package

https://github.com/aspnet/RoslynCodeDomProvider

This is the package that will create the `bin\roslyn` folder in your output during build.
