### ISSUE TITLE
[Request] Module(static class)'s method with 1 or 2 arguments should be an extension method by default.

### ISSUE THREAD

**Issue by RevensofT** [dotnet/roslyn#2828]
Since vb.net module class already expose its methods, why don't make them as an extension method too. Extension method is much more readable when it has 1 or 2 arguments( 3 arguments maybe fine but more than this should be normal call).

```vb
I.love(VB)
'Instead of
love(I, VB)

Dim Section() As Integer = Data.Section(5, 10)
'Instead of
Dim Section() As Integer = Section(Data, 5, 10)

Dim Section() As Integer = Data.From(5).To(10)
'Instead of
Dim Section() As Integer = To(From(Data, 5), 10)

'Global method should be call like an extension method too.

Dim My_int As Integer = My_Double.CInt()
'Instead of
Dim My_int As Integer = CInt(My_Double)

Dim My_element = My_panel.DirectCast(Of Element)()
'Instead of
Dim My_element = DirectCast(My_panel, Element)
```

**Comment by gafter** [comment]
This sounds like it would be an incompatible change.

**Comment by ljw1004** [comment]
Imagine if you had
```vb
Module Module1
  Sub Handle(sender As Object, e As EventArgs) ...
End Module
```

Under this proposal, the method "Handle" would now appear in *every single* intellisense drop-down completion list, for every kind of object. For instance `Dim x = "hello" : x.Handle(...)`.

I wouldn't like that at all!
