### ISSUE TITLE
Rename does not refactor return objects namespaces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28291]
When renaming a class to the same name used in another namespace, the return objects are not renamed with enough namespace to match the specfic class and therefore creates an ambigious reference after refactor

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/280798/rename-does-not-refactor-return-objects-namespaces.html
VSTS ticketId: 638519_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this topic.
