### ISSUE TITLE
IntelliSense: Does not suggest statement corrections correctly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28290]
In a class, I have a boolean property, declared thus:

public bool IsEnabled =&gt; Settings.IsEnabled;

Elsewhere in the same class, I was attempting to write a comparison statement and wrote this statement:

if (isEnabled == isEnabled)

&quot;isEnabled&quot; was the parameter to the function I was writing this code in. &quot;IsEnabled&quot; is the name of the property declared earlier.

As expected, IntelliSense squiggly-lined the IF as soon as I wrote it. But the suggestion was not what I expected at all !!!

Instead of making the suggestion to change one of the &quot;isEnabled&quot; to &quot;IsEnabled&quot; in the IF statement, it was asking me to SUPRRESS the warning itself !

Screenshot attached.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/284249/intellisense-does-not-suggest-statement-correction.html
VSTS ticketId: 640882_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by vatsalyaagrawal** [comment]
Design meeting notes:
- Approved for merge.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/42256
