### ISSUE TITLE
ExtractMethod -- Always extract something, even if advanced techniques cannot be applied

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#283]
Ported from TFS WorkItem: <b>1097177</b>

---

<p><b>Repro Steps:</b></p>

<P><B>Affected Branch:</B> <BR><B>Affected Build:</B> <BR><B>Affected Product Language:</B> <BR><BR><B>Steps to reproduce:</B><BR><BR>Today, lots of attempts to extract method can fail for difficult-to-determine reasons, but often users would be okay with <EM>something </EM>happening, even if it's not a perfect experience.</P>

<P>&nbsp;</P>

<P>If the selection is perfectly extractable without errors, then the user would have the same experience.</P>

<P>&nbsp;</P>

<P>If the selection contains code that we would not extract today, then we could include the error messages&nbsp;in our summary text in the preview pane (e.g. "The resulting code may contain errors because not all code paths return."), but still offer&nbsp;to do a best-effort refactoring. </P>

<P>&nbsp;</P>

<P>This avoids the&nbsp;user needing to manually do the extraction whenever something fails (the reason for which can be difficult to discover), and also&nbsp;prevents general annoyance at the partial availability of the feature.</P>

---

<p><b>Revisions:</b></p>

1) Created By David Poeschl (12/16/2014 2:02:18 PM)

---

2) Edited By Kevin Pilch-Bisson (12/17/2014 9:45:39 AM)

We were discussing this at lunch yesterday.&nbsp; David and Dustin have some ideas here if you need more clarification, but we think this would be an improvement.

---

**Comment by dpoeschl** [comment]
FYI @kuhlenh

**Comment by ryzngard** [comment]
@arkalyanms This looks like a feature ask. I've been going through bugs in Extract Method first, we should discuss where this sits in priority.

**Comment by CyrusNajmabadi** [comment]
This is how the feature works.  The user is prompted and can proceed.  We really only bail when we truly can't do anything.
