### ISSUE TITLE
Proposal: Allow stripping private & internal members from XML documentation file

### ISSUE THREAD

**Issue by KristianWedberg** [dotnet/roslyn#28318]
**Background**

Adding XML comments to `internal` and `private` members of a class library is very useful to have them show in IntelliSense, and to document exceptions, complex behavior etc.

When generating an XML documentation file however, the `internal` and `private` member documentation is _included_ in the file. This means the file can't be used when publishing the library, e.g. as a public NuGet package, since the `internal` and `private` comments often contains information that is secret, such as identifiers before any obfuscation, confidential algorithms and details, internal links, etc.

**Proposal**

Provide settings in msbuild and Visual Studio to exclude or include `internal` and `private` members from the XML documentation file. Personally I would prefer to have them _excluded_ as the default.

**Version Used**: VS 15.7.4

**Steps to Reproduce**:

1. Enable creating the XML documentation file for a C# class library.
2. Add and build the following code:

```C#
namespace XmlDocumentationFile
{
    /// <summary>
    /// MyPublic summary.
    /// </summary>
    public class MyPublic
    {
        /// <summary>
        /// _myPrivate summary.
        /// </summary>
        private int _myPrivate;
    }

    /// <summary>
    /// MyInternal summary.
    /// </summary>
    internal class MyInternal
    {
    }
}
```

**Expected Behavior**:

```XML
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>XmlDocumentationFile</name>
    </assembly>
    <members>
        <member name="T:XmlDocumentationFile.MyPublic">
            <summary>
            MyPublic summary.
            </summary>
        </member>
    </members>
</doc>
```

**Actual Behavior**:

```XML
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>XmlDocumentationFile</name>
    </assembly>
    <members>
        <member name="T:XmlDocumentationFile.MyPublic">
            <summary>
            MyPublic summary.
            </summary>
        </member>
        <member name="F:XmlDocumentationFile.MyPublic._myPrivate">
            <summary>
            _myPrivate summary.
            </summary>
        </member>
        <member name="T:XmlDocumentationFile.MyInternal">
            <summary>
            MyInternal summary.
            </summary>
        </member>
    </members>
</doc>
```

**Comment by CyrusNajmabadi** [comment]
Hi @KristianWedberg Can you clarify this sentence:

> When generating an XML documentation file however, the internal and private member documentation is included in the file, which then can't be used when publishing the library, e.g. as a public NuGet package.

What actually breaks here?  Thanks!

**Comment by KristianWedberg** [comment]
Revised 2nd paragraph above to say that `internal` and `private` XML comments expose confidential information.

**Comment by KristianWedberg** [comment]
Thanks @jhinder, I had missed that issue.

The main difference is that #12485 only mentions reducing the size of the XML file as a reason for the request, whereas this issue highlights the problem of including confidential information in the XML file, which (at least for me) makes the priority of implementing it significantly higher.

**Comment by jcouv** [comment]
I'll go ahead and close this issue as duplicate #12485.
@KristianWedberg Please do add the extra motivation (problem with confidential information) to the original issue. Thanks
