### ISSUE TITLE
SourceLink information is stripped from our symbols on public symbol server

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn#28316]
See also [VSO 643491](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/643491)

If our PDBs are pulled from public symbol server, then they do not have source link information.

Per @tmat, we are moving to a new symbol uploader that should fix this. This is a tracking issue to validate that our public symbols have source link information once we have moved to the new uploader.

**Comment by tmat** [comment]
@nguerrera I think we can close this issue now - symbols are uploaded via dotnet symbol uploader, which doesn't strip any info.
