### ISSUE TITLE
Refactor ContainedDocument.cs to extract reusable logic

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#28322]
To allow VSMac to avoid maintaining a fork of this file we should extract the reusable logic from
https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/Venus/ContainedDocument.cs
and place it into EditorFeatures layer (make an internal helper). 

Start pulling at `FilterTextChanges` and `AdjustIndentation`. If those two are extracted with all dependencies I have a feeling it will tear away nicely, leaving VS-specific goo.

Also would be nice to cover the extracted logic with unit-tests, because it's highly non-trivial. Capture some typical cases from debugging simple real Venus scenarios and create unit-tests. E.g. (from my notes):

```
Good changes:

[1063,1065) \r\n
[1167,1197) \r\nSPACE*16
editorVisibleSpansInOriginal: [1181,1221)
filtered: [1185,1197) -> SPACE*16

Bad changes:

[1065,1067) \r\n
[1171,1191) \r\nSPACE*16
editorVisibleSpansInOriginal: [1185,1205)
filtered: [1187,1191) -> ""

TryGetSubTextChanges:
GetSubTextChanges bad:
changeInOriginalText: [1171,1191)
visibleSpanInOriginaltext: [1185,1205)
leftText: SPACE*16\n\t\t\t
rightText: \r\nSPACE*16
offsetInOriginalText: 1171

leftTextWithReplacement:                 {|n|}			
rightTextWithReplacement: {|r|}{|n|}                

GOOD:
TryGetWhitespaceGroup: 
left:
                
[0,16) [18,30)
right:
                
[0,0) [2,18)
```

**Comment by sandyarmstrong** [comment]
@jinujoseph can we schedule this for 16.5?

**Comment by CyrusNajmabadi** [comment]
Closing out as there's been no movement on this. If this is needed, we need to actually design and schedule this work.
