### ISSUE TITLE
Deadlock in VBCSCompiler.exe building a project with analyzer enabled

### ISSUE THREAD

**Issue by RedX2501** [dotnet/roslyn#28325]
**Version Used**: 

Visual Studio 2017 15.7.4

**Steps to Reproduce**:

I tried compiling a Unit Test Project in Release mode. The same project and solution work fine in Debug mode.

Executing with msbuild does not change the situation.

I do have "Enable code analysis on build" disabled for this project.

I have found the similar issue #4858 fixed by #5183 but neither of them contained anything that helped me circumvent the problem.

**Expected Behavior**:

It compiles.

**Actual Behavior**:

VBCSCompiler.exe deadlocks. No memory consumption change, no CPU consumption

Here is a picture of the Stack:

![http://pichost.org/images/2018/07/06/2018-07-06_09h04_00.png](http://pichost.org/images/2018/07/06/2018-07-06_09h04_00.png)

These are the packages used in the project:

![http://pichost.org/images/2018/07/06/2018-07-06_09h21_26.png](http://pichost.org/images/2018/07/06/2018-07-06_09h21_26.png)

![http://pichost.org/images/2018/07/06/2018-07-06_09h22_28.png](http://pichost.org/images/2018/07/06/2018-07-06_09h22_28.png)

If I can help in any way by adding more information please let me know.

**Comment by jcouv** [comment]
@agocke @davkean  for advice on troubleshooting this. Would it be helpful to get a dump file of the process?

**Comment by agocke** [comment]
Yup, that would be useful.

**Comment by jcouv** [comment]
@RedX2501 Would you be able to share a dump file of the hung process? You can do that from Task Manager:

![image](https://user-images.githubusercontent.com/12466233/42392334-4eed5286-8107-11e8-8212-26fa53383f19.png)

Then share the resulting `.dmp` file with us (via some online drive like DropBox, Google Drive, SkyDrive, ...). Thanks

**Comment by davkean** [comment]
Create a dump from 32-bit TaskMgr (%WINDIR%\SysWow64\TaskMgr.exe) so that SoS will work.

**Comment by jaredpar** [comment]
Closing due to lack of response.
