### ISSUE TITLE
Expand Selection: Select all parameters before selecting parens

### ISSUE THREAD

**Issue by justcla** [dotnet/roslyn#28334]
When using Expand Selection, if expanding inside a parameter list in a method call, all parameters should be selected before the selection encompasses the enclosing parentheses.
This allows users to easy select all the parameters and clear them.

The current implementation moves from selecting a single parameter to selecting all parameters plus the enclosing parenthesis.

Expanding goes from here:
![image](https://user-images.githubusercontent.com/17131343/42400475-9297f17a-8126-11e8-936f-d6dcd28a78e8.png)

To here:
![image](https://user-images.githubusercontent.com/17131343/42400493-a38aa9aa-8126-11e8-80ea-c15a2563874c.png)

**Expected behavior:**
Expanding should select all the parameters - but not the parenthesis.
![image](https://user-images.githubusercontent.com/17131343/42400540-d18338ea-8126-11e8-8117-ad2c0859ed49.png)

**Comment by CyrusNajmabadi** [comment]
I'm also worried about changing expansion logic and potentially breaking people who are accustomed to the current behavior.

**Comment by justcla** [comment]
> I'm also a bit worried about changing expansion logic and potentially breaking people who are accustomed to the current behavior. But i could be convinced it's ok if the new behavior is substantively improved.

I'll address this first.
This feature has only just been released and has very little usage at the moment.
Also, the current behavior is a result of not having time to complete the feature - specifically, these very issues I'm raising now that should have been part of the original implementation but were outside the scope of the Editor team.

**Comment by CyrusNajmabadi** [comment]
> Also, the current behavior is a result of not having time to complete the feature 

Sorry, i'm not seeing where that conclusion is coming from.  Isn't this the ITextStructureNavigator API?  If so, roslyn implemented this 5+ years ago IIRC.

> - specifically, these very issues I'm raising now that should have been part of the original implementation but were outside the scope of the Editor team.

I'm not sure i understand this statement.  The scope of what constitutes "enclosing/firstchild/next/previous/sibling" has always been under the purview of the language.  And roslyn implemented this logic as per what we thought made sense here.

**Comment by justcla** [comment]
>> When using Expand Selection, if expanding inside a parameter list in a method call, all parameters should be selected before the selection encompasses the enclosing parentheses.
This allows users to easy select all the parameters and clear them.

> I don't get the use case. Why would you want to clear all the parameters here?

Methods can have different overloads based on different parameters. You might want to clear all params so you can put in new parameters.
The other option is you are clearing the contents because you're about to copy the line and fill it with other params.

On the contrary, can you think of a case where it's better to skip over the params and grab the braces? Not sure how that's useful.

>> if expanding inside a parameter list in a method call, all parameters should be selected before the selection encompasses the enclosing parentheses.

> Should the expansion also include successive parameters as you expand? Or should it jump from one parameter to all the parameters?

It should go from one parameter to all parameters.

**Comment by justcla** [comment]
> I'm not sure i understand this statement. 

Maybe it's better to chat with Christian about it. I'm talking about the Expand Selection implementation, which is very new. It was implemented by the Editor team. There is only so much that can be done at the platform level and the rest of the work requires tweaks from Roslyn.

This is one such tweak.

**Comment by CyrusNajmabadi** [comment]
> On the contrary, can you think of a case where it's better to skip over the params and grab the braces? Not sure how that's useful.

Because i want to grab them all to place them somewhere else.  

> It should go from one parameter to all parameters.

Can you explain the reasoning there?  Your use case for selecting all was: " You might want to clear all params so you can put in new parameters."

What if someone wants to clear out the last N parameters?  Woudln't the same logic apply?

**Comment by CyrusNajmabadi** [comment]
> There is only so much that can be done at the platform level and the rest of the work requires tweaks from Roslyn.

My primary issue is that it's unclear to me if the tweaks being suggested are actually improvements.  I'm not saying they're not.  But they're just being stated that they are by fiat.  For example, i don't see why expanding on a list of things should go from 1 to N, instead of from 1 to 2 to 3 to ... etc. etc.

I'm trying to understand the logic here so we could come up with a principled set of rules to implement for roslyn.  Right now our rules are simple and clear.  We walk the actual language-tree and map the TextStructureNavigator nouns (next/previous/etc.) to our same nouns.  if we need to map them to something else we can't just do that as one-off hacks.  We need principled rules for how they map to our tree.

**Comment by justcla** [comment]
The principle of Expand Selection is to grab increasingly larger selections of content in a meaningful manner. (Hence, a strict "get the next block as defined by the language block tagger" is too simplified an implementation.)

It is not designed to add siblings to the selection. This is why it does not get 1, 2, 3, etc.

It is designed to quickly expand to parent "groups".

For a better understanding of the feature, there are similar implementations in some other products.

**Comment by CyrusNajmabadi** [comment]
> The principle of Expand Selection is to grab increasingly larger selections of content in a meaningful manner. 

Ok... but what defines 'meaningful' :)    

> It is not designed to add siblings to the selection. This is why it does not get 1, 2, 3, etc.

That's odd, given that the interface we were asked to implement has GetSpanOfNextSibling and GetSpanOfPreviousSibling :D

Perhaps those should be used instead.  Then if the user wants to select all the parameters in your example, they can hit "expand to previous sibling" once.  IN general, you won't have that many parameters.  So you would only hit this a few times at most.

> For a better understanding of the feature, there are similar implementations in some other products.

Perhaps our behavior is better/more appropriate :D    

--

In all seriousness, i think i can get behind this suggestion.  But i'd like to take a principled approach on things like this.  It can't just be: other product over there does it this way.   It needs to be: this is substantively better and here's why.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
