### ISSUE TITLE
Feature request: Declare multiple properties are identical during property initialization

### ISSUE THREAD

**Issue by Mawootad** [dotnet/roslyn#28331]
Something that I recently ran into that would be fairly easy and uncontroversial as a language feature would be the ability to declare that two properties are equal to the same (given) value when declaring an object with property setting. For example instead of having to do this:

```
MyObject obj = new MyObject() {
  Prop1 = "value",
  Prop2 = "value"
}
```

You could do this:

```
MyObject obj = new MyObject() {
  Prop1 = Prop2 = "value"
}
```

I'm uncertain of the low-level handling of property assignment is handled in terms of ordering for object declarations, but depending on how things work the actual code could be equivalent to either:

```
var tempValue = "value"
MyObject obj = new MyObject() {
  Prop2 = tempValue,
  Prop1 = tempValue
}
```

Or to

```
MyObject obj = new MyObject();
obj.Prop1 = obj.Prop2 = "value";
```

**Comment by jaredpar** [comment]
Thanks for the suggestion. This is actually a language feature request vs. a compiler feature. Could you please re-open this issue on the https://github.com/dotnet/csharplang repository? That is the appropriate place for language requests.
