### ISSUE TITLE
Expand Selection: Needs to select the inner-most element - even when caret to the right of the token

### ISSUE THREAD

**Issue by justcla** [dotnet/roslyn#28333]
When using Expand Selection, if the caret is on the right of a token (and touching it), the Expand Selection function does not look at the token to the left. Instead it operates on the token to the right.

This is a problem when trying to select the variable you just typed.
In this example, when the caret is to the right of the variable "secondValue", pressing Expand Selection results in the right parenthesis being selected, instead of the variable.

![image](https://user-images.githubusercontent.com/17131343/42400253-b685015a-8125-11e8-9d0c-0758bef0caa5.png)

**Expected behavior**: When there is a choice of two viable alternatives, Expand Selection should favor the one that has the inner scope.

![image](https://user-images.githubusercontent.com/17131343/42400302-deea45e2-8125-11e8-9939-bcca482fd071.png)

**Comment by justcla** [comment]
This issue first mentioned in issue #28266

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
