### ISSUE TITLE
Expand Selection: Select all lines in block - separated by blank line

### ISSUE THREAD

**Issue by justcla** [dotnet/roslyn#28336]
When using Expand Selection, expanding from a full line selection should select all lines in the current block - up to the point where a new line is introduced.

The current implementation expands to all lines in the block - regardless of blank lines. Typically, this is everything inside the curly braces.

The expected behavior is to expand from a full line selection
![image](https://user-images.githubusercontent.com/17131343/42400958-577da556-8128-11e8-9933-b00c4b9f6469.png)

to all the lines in the block - up to the next (or previous) new line.
![image](https://user-images.githubusercontent.com/17131343/42400987-72045636-8128-11e8-986f-be04783d3f30.png)

The next Expand operation would expand to the whole block (up to but not including the braces):
![image](https://user-images.githubusercontent.com/17131343/42401027-a316ac9c-8128-11e8-8dc6-e570ea218803.png)

**Comment by CyrusNajmabadi** [comment]
> When using Expand Selection, expanding from a full line selection should select all lines in the current block - up to the point where a new line is introduced.

A lot of these issues are missing the "why" part of a files issue.  It's unclear to me why the proposed solution is better than the current behavior. When i've expanded the selection on a statement it's been to select all statements in a block.  This would break that beahvior.

If i want to make line selections, btw, i just make line selections.  i.e. shift-up/down.  I use 'expand selection' precisely to select a language-oriented view of what my parent is.  I'm not a fan of these proposals that suggest changing htat.

**Comment by CyrusNajmabadi** [comment]
We don't plan on doing this. Uniform whitespace handling should be handled by the editor. That way it works properly for all languages.
