### ISSUE TITLE
Remove/replace INavigateToSearchService

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#28343]
Pull request #28294 introduces a new interface `INavigateToSearchService_RemoveInterfaceAboveAndRenameThisAfterInternalsVisibleToUsersUpdate` which contains a new definition for `INavigateToSearchService`. 

1. The F# and TypeScript projects should migrate their implementations of `INavigateToSearchService` to `INavigateToSearchService_RemoveInterfaceAboveAndRenameThisAfterInternalsVisibleToUsersUpdate`
2. After the first step is complete, dotnet/roslyn along with F# and TypeScript can coordinate to remove the current `INavigateToSearchService` interface and rename `INavigateToSearchService_RemoveInterfaceAboveAndRenameThisAfterInternalsVisibleToUsersUpdate` to `INavigateToSearchService`

**Comment by CyrusNajmabadi** [comment]
This makes me sad.  can we do this?

**Comment by CyrusNajmabadi** [comment]
tagging @DanielRosenwasser  for visibility to see if this has been done for TS.

**Comment by DanielRosenwasser** [comment]
I dunno what's happening here. Maybe @uniqueiniquity does.

**Comment by uniqueiniquity** [comment]
This makes me sad too. 😄 
We have moved to the interface with the horrible name.

**Comment by CyrusNajmabadi** [comment]
@sharwell Can we remove the awfulness now that F# and TS have moved forward. Thanks :)
