### ISSUE TITLE
nameof(): clarify when invocation is classified as 'nameof' expression

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#2834]
This code compiles fine and expression is classified as `nameof` expression:
```c#
class Nameof1 {
  int nameof = 42;
  string F() => nameof(F);
}
```
But if we replace field with method:
```c#
class Nameof2 {
  int nameof() => 42;
  string F() => nameof(F);
}
```
...it produces compiler error:
> CS1501: No overload for method 'nameof' takes 1 arguments

My expectations: invocation of name `nameof` is only classified as `nameof()` expression when there is no symbols named `nameof` *of any kind*, available in particular scope.

Or am I getting something wrong?

**Comment by sharwell** [comment]
This reminds me of ... oh wait y'all just hired him nevermind.

**Comment by ljw1004** [comment]
The current behavior of `nameof` is very similar to the behavior of `var`...

This works fine:
```cs
class Var1
{
	int var = 42;
	void f() { var x = 15; }
}
```

And this gives an error that it can't convert '15' to Var2.var:
```cs
class Var2
{
	class var { }
	void f() { var x = 15; }
}
```

I think this is great! And it matches my expectation!

**Comment by MadsTorgersen** [comment]
Agreed with Lucian! This is by design. We already have a distinction between "invokable" and not, that we use in member lookup. We feel that is right to apply here as well. Thereby we are keeping the case of the nameof feature being blocked to a very narrow compatibility scenario.

**Comment by leppie** [comment]
`nameof` should be identical in behavior to `typeof` in a lexical sense in my opinion. It is much more specific construct than `var`.
