### ISSUE TITLE
F12 navigation on an overloaded method doesnt take me to the right method signature definition

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28358]
1. I've a solution file in which i cant navigate to function definitions properly. i've enabled code analyzer on build for many of the c# projects in my solution. When i do F12 on an overloaded method i get taken to another method with the same name but not identical signature, eg:  i press F12 on SearchDocuments(a,b,c..30 args) and get taken to SearchDocuments(..5 args). i'm on VS 15.7.4 enterprise

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/281372/f12-navigation-on-an-overloaded-method-doesnt-take.html
VSTS ticketId: 638837_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Would need a repro case on this.  this is not actionable.
