### ISSUE TITLE
Declared type precedence in new operator (regression)

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#2836]
Mentioned but not addressed in comments at CodePlex [#138](https://roslyn.codeplex.com/workitem/138).

```csharp
bool b;
Program p = new |
b = false;
```

This results in Intellisense offering `bool` instead of `Program`. There is no scenario where `bool` would be acceptable at this place (or where the code after cursor would be relevant to what is following the `new` operator).

This worked in previous version of Visual Studio.

**Comment by Pilchie** [comment]
I believe this is a dupe of something @rchande recently fixed.  Can you find the issue and close?

**Comment by rchande** [comment]
This was tracked by an internal workitem, but is fixed by this commit: https://github.com/dotnet/roslyn/commit/a97484ae74646712bbc17fc33f06a01fbb9c6d7b.

**Comment by tmat** [comment]
Still reproes.

![image](https://cloud.githubusercontent.com/assets/41759/8097829/64aa23e0-0f9c-11e5-8e72-6b8f9cd550a5.png)

**Comment by Pilchie** [comment]
Can you take a look?

**Comment by rchande** [comment]
Ah, this is slightly different than the case I fixed.

**Comment by balajikris** [comment]
Submitting a PR shortly.

**Comment by balajikris** [comment]
Fix submitted to master for Update 1.

**Comment by balajikris** [comment]
Test and address compound assignment cases, if the fix doesn't address it:

```C#
int i;
Program p = new |
i += 1;
```

**Comment by miloush** [comment]
Still seeing this (15.0.25428.1/2.0.0.60620):

```C#
int[] array;

Program p = new |
array[4] = 4;
```
