### ISSUE TITLE
VBCSCompiler.exe crashes frequently on Windows 7 with an analyzer installed

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#2838]
This only repros on a Windows 7 machine. Windows 8 and above is fine.

1. Log into `ddandarno021.redmond.corp.microsoft.com` (ping me and I can make you admin)
2. Open the solution in C:\git\Threading\src
3. Rebuild the solution.

VBCSCompiler.exe will *crash* a few times. Each time with this exception.

> System.ArgumentException was unhandled
Message: An unhandled exception of type 'System.ArgumentException' occurred in Microsoft.CodeAnalysis.dll
Additional information: The directory name ..\packages\StyleCop.Analyzers.1.0.0-alpha005\tools\analyzers is invalid.

>	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler) Line 152	C#
 	VBCSCompiler.exe!Microsoft.CodeAnalysis.CompilerServer.ServerDispatcher.Connection.ServeBuildRequest.AnonymousMethod__0() Line 156	C#
 	[Native to Managed Transition]	
 	System.dll!System.IO.FileSystemWatcher.FileSystemWatcher(string path, string filter) Line 145	C#
 	System.dll!System.IO.FileSystemWatcher.FileSystemWatcher(string path) Line 125	C#
 	VBCSCompiler.exe!Microsoft.CodeAnalysis.CompilerServer.CompilerServerFileWatcher.AddPath(string path) Line 37	C#
 	VBCSCompiler.exe!Microsoft.CodeAnalysis.CompilerServer.CSharpCompilerServer.RunCompiler(string clientDirectory, string[] args, string baseDirectory, string sdkDirectory, string libDirectory, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader analyzerLoader, System.IO.TextWriter output, System.Threading.CancellationToken cancellationToken, out bool utf8output) Line 32	C#
 	VBCSCompiler.exe!Microsoft.CodeAnalysis.CompilerServer.CompilerRequestHandler.CSharpCompile(string currentDirectory, string libDirectory, string responseFileDirectory, string[] commandLineArguments, System.IO.TextWriter output, System.Threading.CancellationToken cancellationToken, out bool utf8output) Line 154	C#
 	VBCSCompiler.exe!Microsoft.CodeAnalysis.CompilerServer.CompilerRequestHandler.CSharpCompile(Microsoft.CodeAnalysis.CompilerServer.BuildRequest req, System.Threading.CancellationToken cancellationToken) Line 127	C#
 	VBCSCompiler.exe!Microsoft.CodeAnalysis.CompilerServer.CompilerRequestHandler.HandleRequest(Microsoft.CodeAnalysis.CompilerServer.BuildRequest req, System.Threading.CancellationToken cancellationToken) Line 69	C#
 	VBCSCompiler.exe!Microsoft.CodeAnalysis.CompilerServer.ServerDispatcher.Connection.ServeBuildRequest.AnonymousMethod__0() Line 154	C#
 	mscorlib.dll!System.Threading.Tasks.Task<Microsoft.CodeAnalysis.CompilerServer.BuildResponse>.InnerInvoke() Line 680	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Line 2861	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2767	C#
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() Line 2704	C#
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820	C#
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Line 1161	C#

**Comment by mavasani** [comment]
@tmeschter fixed this last week.

**Comment by jaredpar** [comment]
@mavasani can you point to a PR / Commit so we can close this?

**Comment by tmeschter** [comment]
@mavasani @jaredpar The crashing code was removed entirely in b615c03e76b91d523ebb160c69ac6a0eb66f6385.

**Comment by jaredpar** [comment]
@tmeschter thanks for getting the info!
