### ISSUE TITLE
Null-coalescing Assignment Work Items

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#28381]
Tracking issue for null-coalescing work items:

* [x] Expand Tests:
    * [x] Typeless tuples `(null, null)`
    * [x] Tuples that differ by names.
    * [x] `default`
    * [x] `outParam ??= value` (and any other parameter types, like `in`)
    * [x] Chaining `x ??= y ??= z`
    * [x] checked vs unchecked `nullableIntLocal ??= longValue`
    * [x] stackalloc RHS (should fail)
    * [x] Obsolete conversion from RHS to LHS
    * [x] Deconstruction-like syntax
    * [x] Use-site conversion diagnostics
* [ ] Write/update feature doc
* [x] Add feature to compiler test plan
* [x] Follow up with @gafter on https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs#L1716-L1717
* [x] Follow up on https://github.com/dotnet/roslyn/pull/28598#discussion_r203168514

**Comment by jcouv** [comment]
Only work item left is documentation. Moving to Compiler.Next milestone.

**Comment by 333fred** [comment]
The spec for this has been updated for a while. Not sure what else there would be to write, so I'm closing this out.
