### ISSUE TITLE
Different roslyn version generating different IL for pointers

### ISSUE THREAD

**Issue by WardenGnaw** [dotnet/roslyn#28395]
Not sure if this is an known change but with different versions of Roslyn, the IL generated is different.

**Version Used**: 3.0.0.61717 (09da1925) and 2.9.0.63026 (1c015ea4)

**Steps to Reproduce**:

1. Use the code snippet below:
```
using System;
using System.Diagnostics;
using System.Linq;

unsafe class P
{
    static void Main()
    {
        var p = new P();
        p.F();
    }

    void F()
    {
        int i = 4;
        byte* ptrNull = null;
        IntPtr intptrNull = IntPtr.Zero;
        fixed (decimal* ptrDecimals = m_decimals)
        {
            fixed (MyEnum* ptrEnums = m_enums)
            {
                Debugger.Break();
            }
        }
    }

    long GetPtrInt(void* ptr)
    {
        return (long)ptr;
    }

    enum MyEnum
    {
        VAL_0 = 0,
        VAL_1 = 1,
        VAL_2 = 2
    }

    decimal[] m_decimals = Enumerable.Range(0, 10).Select(i => (decimal)i).ToArray();
    MyEnum[] m_enums = Enumerable.Range(0, 3).Select(i => (MyEnum)i).ToArray();
    byte* m_ptr1 = null;
}


```
2.  Compile with:
```
csc.exe /nologo /warn:4 /define:DEBUG;TRACE /errorendlocation /nowarn:1998 /debug /unsafe /nostdlib+ /noconfig /platform:x86 /fullpaths /r:"C:\windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll" /r:"C:\windows\Microsoft.NET\Framework\v4.0.30319\System.dll" /r:"C:\windows\Microsoft.NET\Framework\v4.0.30319\System.Core.dll" /r:"C:\windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.CSharp.dll" /r:"C:\windows\Microsoft.NET\Framework\v4.0.30319\System.Windows.Forms.dll" /r:"C:\windows\Microsoft.NET\Framework\v4.0.30319\System.Xml.dll" /r:"C:\windows\Microsoft.NET\Framework\v4.0.30319\System.Xml.Linq.dll" /r:"C:\windows\Microsoft.NET\Framework\v4.0.30319\System.Data.dll" /r:"C:\windows\Microsoft.NET\Framework\v4.0.30319\System.Drawing.dll" "program.cs"
```
3. ildasm program.cs -> P -> F

**Expected Behavior**: 2.9.0.63026 create P::F : void() IL as  
```
.method private hidebysig instance void  F() cil managed
{
...
           [3] valuetype [mscorlib]System.Decimal* ptrDecimals,
...
} // end of method P::F

```

**Actual Behavior**: While  3.0.0.61717 creates P::F : void() IL as
```
.method private hidebysig instance void  F() cil managed
{
...
           [3] valuetype [mscorlib]System.Decimal& pinned ptrDecimals,
...
} // end of method P::F
```

The Decimal& broke our test and we were just wondering if this was an expected change or should the IL still be generated as a Decimal*

**Comment by jmarolf** [comment]
the version 3.0 hasn't been updated from master in over a year.  @WardenGnaw Why are you consuming an unreleased compiler version from that long ago?

**Comment by WardenGnaw** [comment]
We are grabbing the latest via `nuget install Microsoft.Net.Compilers -Source "https://dotnet.myget.org/F/roslyn/api/v3/index.json" -ExcludeVersion -Prerelease`

**Comment by kelltrick** [comment]
We are consuming Roslyn from here: https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.Net.Compilers (which has clearly gone out of date)

Where can we pickup a *real* latest version?

**Comment by jmarolf** [comment]
>Where can we pickup a *real* latest version?

[The latest public nuget release](https://www.nuget.org/packages/Microsoft.Net.Compilers/2.8.2) should be sufficient for whatever you want to compile.  I don't understand why you want your code compiled with an unreleased (and therefore unsupported and not fully tested) compiler.  

We have several partner teams that consume packages from us via  https://dotnet.myget.org because they need newer api surface area, I assume that is your use-case as well somehow? [2.9.0-beta8](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.Net.Compilers/2.9.0-beta8-63109-03) represents the work currently in master.  You can find more information about our packages and their versions [here](https://github.com/dotnet/roslyn/wiki/NuGet-packages#versioning).  Unfortunately all of our packages go into the same feed regardless of branch to impart less of a burden on consuming teams infrastructure.

**Comment by tannergooding** [comment]
> We are grabbing the latest via nuget install Microsoft.Net.Compilers -Source "https://dotnet.myget.org/F/roslyn/api/v3/index.json" -ExcludeVersion -Prerelease

Keep in mind that "latest version" does not necessarily mean "most up to date" (in the context of pre-release packages)

**Comment by tmat** [comment]
What is the test that depends on the exact instructions emitted by Roslyn actually testing? Is this just a test issue or does the debugger have some dependency on the exact instructions?

**Comment by kelltrick** [comment]
We don't depend on exact instructions, but we do depend on the source info / instruction mapping in the PDBs to be correct. In the past, we have encountered issues where changes to exact instructions will yield malfunctions in the PDB reader libraries which will surface in our tests.

**Comment by tmat** [comment]
Could you point to those issues? Whenever such an issue is discovered we need to add a PDB test to Roslyn repo that covers it. What PDB reader libraries do you use?
