### ISSUE TITLE
Compiler Server is intermittently keeping .snk file locked past compilation

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#2840]
```
8>vbc : error BC36980: Error extracting public key from file 'C:\R0\src\Tools\Microsoft.CodeAnalysis.Toolset.Open\Strong Name Keys\RoslynInternalKey.Private.snk': The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
```

**Comment by jaredpar** [comment]
Did you run handle and verify that it was VBCSCompiler that is holding this in memory?  Or is this just guessing?

**Comment by tmat** [comment]
Yes. Verified. Worked after killing VBCSCompiler process.

**Comment by jaredpar** [comment]
So you didn't use handle to verify?

**Comment by tmat** [comment]
I did. Then I killed the process.

**Comment by jaredpar** [comment]
Any other info you could provide here to help track this down? 

- What solution were you compiling?
- What options were you passing to MSBuild?
- Was this a command line or IDE build?

**Comment by tmat** [comment]
src\Roslyn.sln from VS.

**Comment by jaredpar** [comment]
I've spent about 30 minutes trying to repro this and am unable to do so.  I've also sluethed through the code and cannot find anyplace which could potentially cause this.  All of our use the SNK in the compiler is done in one shot operations like `File.ReadAllbytes`.

Closing for now.  Please reopen if you can get a dump of the failure.

**Comment by tmat** [comment]
Now I see 
```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4385,5): warning MSB3061: Unable to delete file "C:\R5\Binaries\Debug\Microsoft.DiaSymReader.Native.amd64.dll". Access to the path 'C:\R5\Binaries\Debug\Microsoft.DiaSymReader.Native.amd64.dll' is denied.
```
while building from VS.
![image](https://cloud.githubusercontent.com/assets/41759/7693961/74f63b28-fd8e-11e4-830f-e0b810ae7866.png)

Memory dump of VBCSCompiler.exe:

**Comment by tmat** [comment]
@agocke FYI

**Comment by jaredpar** [comment]
@tmat this report differs significantly from the bug title.  In this case the item being held in memory is the DLL which is loaded by the compiler for processing vs. an external file.  I would expect this behavior to by By Design.  The server is running and it's holding one of its dependent DLLs in memory.  

Yes it's a bit odd to be loading from there but that can happen given the proper environment setup.

**Comment by tmat** [comment]
@jaredpar Fair enough. Just another locking problem. I have opened a new issue: #2898. I don't think the compiler should be loading DLLs from random places. That seems like a security concern. In any case, it's moot now sine we are not gonna ship Diasymreader with RTM. But if we do in future it should always be loaded from next to the compiler (if present). This can't be by design, it actually breaks dogfooding.

**Comment by jaredpar** [comment]
The compiler uses DllImport to load this DLL so it's not random. As stated earlier the design of DllImport allows for it to pick DLLs not located next to the compiler.

**Comment by tmat** [comment]
Then perhaps we shouldn't use DllImport.
