### ISSUE TITLE
MSBuildWorkspace opens the solution wrongly.

### ISSUE THREAD

**Issue by eugenr79** [dotnet/roslyn#28414]
**Steps to Reproduce**:

1.  I use the latest roslyn sdk: https://github.com/dotnet/roslyn-sdk/tree/dev15.8.x
2.  Then create xUnit Test Project (.NET Core) from the new project wizard see screencast https://www.screencast.com/t/CotFlvZK04zR
3. Run the SolutionExplorer project from samples and open the test solution
4. If Visual Studio Professional 2017 is installed on the computer then the Project element contains the References. But if Visual Studio Enterprise 2017 if installed, the metadata references list is empty.

**Expected Behavior**:
Opened solution should contain the metadata references 

**Actual Behavior**:
Opened solution does not contain the references.

See the screencast: https://www.screencast.com/t/fYVnH57Xk1qg

**Comment by DustinCampbell** [comment]
Hi! A couple of questions:

* Does the project open properly in that install VS 2017 Enterprise? If not, do you have the appropriate workloads installed into that VS?
* If you debug the Solution Explorer sample and inspect the MSBuildWorkspace, does it have metadata references on the loaded solution? I'm wondering if the problem is an issue in the code that populates the solution explorer.
* Have you restored the project?

**Comment by eugenr79** [comment]
Hi,
- Yes, the project opens well in the install VS 2017 Enterprise. Here is an image illustrating this.
https://www.screencast.com/t/L3BPaaMa7k
- Yes, when I debug I see the metadata references in the first case and do not see in the another.
- Here is a project to test on.
[CoreProject.zip](https://github.com/dotnet/roslyn/files/2192013/CoreProject.zip)
and here is a video illustrating my test scenario.
https://www.screencast.com/t/XyEBd5rEMlkn

**Comment by DustinCampbell** [comment]
I was able to load the references from the project successfully after running `dotnet restore` on the project at the command line:

![image](https://user-images.githubusercontent.com/116161/42785420-44af4056-8907-11e8-999b-f0f08c85b9d4.png)

**Comment by eugenr79** [comment]
yes, dotnet restore solves the problem. Thank you for help.

**Comment by DustinCampbell** [comment]
Glad to hear it! Thanks!
