### ISSUE TITLE
"Roslyn Error: test timeout exceeded, dumping remaining processes"

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#28410]
https://github.com/dotnet/roslyn/issues/26681
https://ci.dot.net/job/dotnet_roslyn/job/features_compiler/job/windows_debug_spanish_unit32_prtest/69/consoleFull#138080395683554902-aff0-4799-9e92-0ada24ce2a06

```
01:19:46.545    1 running,  0 queued, 53 completed
01:27:05.578 Roslyn Error: test timeout exceeded, dumping remaining processes
01:27:05.578 Could not locate procdump
01:27:08.072 Command failed to execute: D:\j\workspace\windows_debug---e5ac73d0\Binaries\Debug\Exes\RunTests\RunTests.exe
etc.
```

**Comment by dpoeschl** [comment]
Again
https://ci.dot.net/job/dotnet_roslyn/job/dev15.8.x-vs-deps/job/windows_debug_vs-integration_prtest/21/consoleFull#-192897211283554902-aff0-4799-9e92-0ada24ce2a06
https://github.com/dotnet/roslyn/pull/28457

**Comment by Shyam-Gupta** [comment]
Another instance: https://ci.dot.net/job/dotnet_roslyn/job/master-vs-deps/job/windows_debug_vs-integration_prtest/272/consoleFull#69118994783554902-aff0-4799-9e92-0ada24ce2a06

PR: https://github.com/dotnet/roslyn/pull/28394

**Comment by Shyam-Gupta** [comment]
Requesting @jinujoseph to assign it to someone for investigation. It is affecting codeflow a lot.

**Comment by dpoeschl** [comment]
Another one: https://ci.dot.net/job/dotnet_roslyn/job/master-vs-deps/job/windows_release_vs-integration_prtest/271/console

PR: https://github.com/dotnet/roslyn/pull/28439#pullrequestreview-137192849

**Comment by sharwell** [comment]
Submitted #28523. We've been running up against the current timeout for a while, and it seems we're now over.

**Comment by JoeRobich** [comment]
Build failure in https://github.com/dotnet/roslyn/pull/31410 due to test timeout - [build log](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/5402/)

**Comment by JoeRobich** [comment]
Hit this again in #31591 [Build logs](https://dnceng.visualstudio.com/public/_build/results?buildId=53879)
