### ISSUE TITLE
"The method or operation is not implemented" when setting next statement

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#2841]
Was working on a fix to #1729 and was doing some EnC debugging while running unit tests.

I initially had basically
```C#
...
// return true;
return complicatedExpression;
...
```
And I broke on ```complicatedExpression``` and EnC'd to
```C#
...
return true;
// return complicatedExpression;
```
This put the active statement after both returns, so I dragged it back up to the ```return true```, which caused the below dialog:

![image](https://cloud.githubusercontent.com/assets/235241/7672536/ad8b5692-fcaa-11e4-957b-ba3aa92b20ea.png)

The session continued, but I'm not sure whether it actually obeyed the updated next statement.

**Comment by dpoeschl** [comment]
Not sure whether problems setting next statement go under Interactive-Debugging or Interactive-EnC, so adding both sub-labels.

**Comment by tmat** [comment]
@dpoeschl As soon as we get a new signed build all IP dragging should work.
