### ISSUE TITLE
Add more cases to 'unused variable' detection

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#28418]
If a variable is assigned but never used, we don't currently flag it as unused.

```csharp
public void Method()
{
    var numbers = new List<int>();
    var c = 1;
    for (var i = 0; i < numbers.Count; ++i)
    {
        c *= numbers[i];  // c is assigned but not used in the rest of the body; numbers is never updated nor used
    }
}
```

**Comment by CyrusNajmabadi** [comment]
FWIW: This has been an explicit design in the language since v1.  This is commonly done by people who want variables so that they they can 'read' them through some other means (often by the debugger).  

If we do this, it will likely be something a user has to opt-into.  Otherwise it will noisely make the experience worse for many users.

**Comment by anujc** [comment]
A simpler example is 
var numbers = new List<int>();

and never use numbers in your code. R# will grey out the unused code which catches your attention that it needs to be deleted. Expecting something similar in VS.

**Comment by CyrusNajmabadi** [comment]
@333fred I'm curious about adding a feature to support this in the IDE.   Would the new CFG stuff be any help for determining that a variable is only written to and never read?

**Comment by 333fred** [comment]
Should be possible with the CFG API, though it might be easier if one used the region analysis apis that extract method uses as that should let you ask the simple question of "Is x read in this region" without having to determine whether a variable reference in the CFG is a read or write (there is an open issue to add this information. It's determinable with the existing info, but requires some piecing together).

**Comment by CyrusNajmabadi** [comment]
@333fred One annoyance though with the region analysis API is that you need to know the span of statements to actually check.  This is somewhat annoying to determine (unless someone provides an API to figure that out for you).

**Comment by alrz** [comment]
Relates to https://github.com/dotnet/roslyn/issues/15695

**Comment by CyrusNajmabadi** [comment]
> A simpler example is
var numbers = new List();

> and never use numbers in your code. R# will grey out the unused code which catches your attention that it needs to be deleted. Expecting something similar in VS.

This is the behavior i see: 

![image](https://user-images.githubusercontent.com/4564579/76155902-7eb7c880-60a7-11ea-9741-5c069a2f0bee.png)

**Comment by 333fred** [comment]
I think that @mavasani has since implemented this. Can it be closed?

**Comment by mavasani** [comment]
Yes, this is implemented as IDE0059. Closing it out...
