### ISSUE TITLE
cache aggregatedProjectTypeGuid

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#28426]
the guid is used in error list provider and it depends on STA VS API call (which switch to UI thread to work) we should cache it (it will not change once project is created) so that it becomes free-thread for roslyn usage.

http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Telemetry/ProjectTypeLookupService.cs,27

related issue - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/637811

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
