### ISSUE TITLE
EditorConfig: Code fix for naming violation in subnamespace is missing

### ISSUE THREAD

**Issue by smitpatel** [dotnet/roslyn#28437]
Editor Config file used: https://gist.github.com/smitpatel/4c19bbd0c166e23fdb491a6d70c97a56

For simple program like this:
```C#
using System;

namespace EditorConfig
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```
It detects namespace naming style violation.
![image](https://user-images.githubusercontent.com/1528107/42538192-132d19dc-844c-11e8-8b41-26b931da726e.png)
Lightbulb also offers correct code fix
![image](https://user-images.githubusercontent.com/1528107/42538212-20cae8f8-844c-11e8-8cb2-bdf920987fd9.png)

When it comes to subnamespaces, it detect the error
![image](https://user-images.githubusercontent.com/1528107/42538243-35c0fd74-844c-11e8-88b0-8cf0717e467d.png)
but there is no codefix just suppression
![image](https://user-images.githubusercontent.com/1528107/42538265-4c739414-844c-11e8-92fa-e25235153fc9.png)

**Version Used**: 
VS 15.8.0 Preview 4.0 27907.0.d15.8

**Expected Behavior**:
Code fix should be available for any violation in namespace.

**Actual Behavior**:
Subnamespaces do not have code fix for violation.

I am facing weird behavior in much larger project (when dealing a lot of subnamespaces where it identify violation/code fix in random fashion).

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
