### ISSUE TITLE
ServicesVisualStudio depends on C# and VB specific projects

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#28468]
Specifically: 

![image](https://user-images.githubusercontent.com/4564579/42592965-11b690ce-8500-11e8-89ca-025fed21a401.png)

CSharp.Workspaces and VisualBasic.Workspaces

This seems like a layering violation.  @jasonmalinowski Is this intentional?

**Comment by jasonmalinowski** [comment]
I have no idea why that would be like that. Can't imagine it's intentional. It dates back to the beginning of us pushing the code into GitHub, so I can't even find somebody to blame. What happens if you remove it? :-)

**Comment by CyrusNajmabadi** [comment]
I'll try :D
