### ISSUE TITLE
Can't view managed variable content in debugger (mixed mode) due to System::Object in System.Runtime assembly

### ISSUE THREAD

**Issue by pongba** [dotnet/roslyn#28477]
**Version Used**: 
latest version of C# Scripting API

**Steps to Reproduce**:

1. create a native project (exe)
2. create another C++/CLI project (dll) that bridges the native project with CLR and reference & use C# scripting API
3. write any simple usage of the scripting API and debug run
4. watch any managed variable's value in debug "watch" window

**Expected Behavior**:
value can be shown

**Actual Behavior**:
Unable to resolve reference to type 'System::Object' in assembly 'System.Runtime'.

![image](https://user-images.githubusercontent.com/320863/42606607-6e15c532-8533-11e8-8886-e5fa60ea6ad6.png)

Notes:
[1] If I create C# project and use the API, debugger works fine.
[2] Some suggests that it has to do with the fact that the roslyn scripting package targets .net standard instead of .net framework (my C++/CLI project targets .net4.6)

**Comment by tmat** [comment]
Could you please share your projects?

**Comment by muffadalis** [comment]
I am having the same issue.

**Comment by pongba** [comment]
@tmat I think it might be due to the fact that somehow the debugger tries to find System.Runtime assembly for all the fundamental types (System.Object, System.Int32, etc.). I thought System.Runtime is a .NET Core assembly? My mixed assembly builts atop .NET Framework, maybe that's why.

cc @muffadalis
