### ISSUE TITLE
CS1998 is not suppressed by SuppressMessage when building with MSBuild.exe

### ISSUE THREAD

**Issue by PeteBoyRocket** [dotnet/roslyn#28479]
**Version Used**: 
MSBuild from VS2017 15.7.5

**Steps to Reproduce**:
We see this on our build server and I've reproduced it locally.

Using the SuppressMessageAttribute successfully suppresses the warning in Visual Studio, but when rebuilding using MSBuild the warning is still reported in the console output.
`[SuppressMessage("Compiler", "CS1998")]
public async Task Foo()
{
}
`

Still gives the warning:

`  
Program.cs(16,27): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider usi
ng the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background
thread. [D:\temp\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
`

1. Run &"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe" .\
ConsoleApp1.sln /t:rebuild
2. Observe console output.

**Expected Behavior**:
CS1998 is suppressed when building with MSBuild.exe

**Actual Behavior**:
CS1998 is not suppressed when building with MSBuild.exe

Example solution that reproduces it:
[ConsoleApp1.zip](https://github.com/dotnet/roslyn/files/2188113/ConsoleApp1.zip)

**Comment by jaredpar** [comment]
This behavior is "By Design". The `SuppressMessageAttribute` does not control compiler warnings but rather other diagnostic sources.

**Comment by PeteBoyRocket** [comment]
@jaredpar What would the recommended way be to suppress warnings in this scenario?

**Comment by PeteBoyRocket** [comment]
So we should favour `#pragma` over `SuppressMessage` in general too, as suppressing the message locally is irrelevant if our CI system will always detect it

**Comment by giggio** [comment]
@jaredpar We couldn't find this information on the docs. Is there somewhere or does it need amending?
