### ISSUE TITLE
EE appears to use LangVersion=default instead of latest

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#28486]
![image](https://user-images.githubusercontent.com/12466233/42655931-77b20ec6-85d2-11e8-89e9-e54df8fb6287.png)

FYI @cston

**Comment by cston** [comment]
Tagging @jinujoseph to assign.

**Comment by ivanbasov** [comment]
@jcouv as far as I understand, the language version is defined here: https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs#L318 (same for VB)

The tree EE provides to the compilation is empty. Therefore, the language version is set as default here:
https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs#L377

1. Please let me know what would be the proper approach to pass the language version to CSharpCompilation. Should we add it to CSharpCompilationOptions?
2. What would be the priority of selecting version in CommonLanguageVersion? SyntaxTree then options then default?

**Comment by gafter** [comment]
I would suggest passing a tree to the compilation, even if it is empty.

**Comment by tmat** [comment]
Already looking into this. Dup of https://github.com/dotnet/roslyn/issues/31179
