### ISSUE TITLE
Implement BatchFixAllProvider.AddProjectFixesAsync

### ISSUE THREAD

**Issue by giggio** [dotnet/roslyn#2850]
Currently `BatchFixAllProvider.AddProjectFixesAsync` is not implemented, and is throwing:

https://github.com/dotnet/roslyn/blob/3faf03a3e52c1b46bbc3967060cf6406d4ecc9af/src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs#L162

It should be implemented.

**Comment by srivatsn** [comment]
This would be need when we start supporting FixAll from outside the editor (where there's no document available). Today that's not a scenario and so we only go down the path where FixAllContext.Document is not null.

**Comment by CyrusNajmabadi** [comment]
This method does nto throw anymore.  It simply returns immediately.  Subclasses can still override as appropriate.
