### ISSUE TITLE
Incorrect switch snippet applying in Visual Studio for enum which has the same values

### ISSUE THREAD

**Issue by GeorgeAlexandria** [dotnet/roslyn#28507]
Hi,

I'm used **Visual Studio 15.6.6** (VS). 

I try to use snippet of `switch` in VS under the enum, which contains the same values (I don't think that is a bad practices to use the same values), just or example, it would be `Microsoft.CodeAnalysis.MethodKind, Microsoft.CodeAnalysis 2.7.0`, which has `AnonymousFunction = 0, LambdaMethod = 0`. And when you apply `switch` snippet under this enum VS generates the all cases includes cases for the same values, and, of course, you receive a compile time errors at the code bellow:

<details> <summary><b>Generated code</b></summary>

```c#
...
// Symbol is IMethodSymbol
switch (Symbol.MethodKind)
{
    case MethodKind.AnonymousFunction:
        break;
    case MethodKind.LambdaMethod:
        break;
    case MethodKind.Constructor:
        break;
    case MethodKind.Conversion:
        break;
    case MethodKind.DelegateInvoke:
        break;
    case MethodKind.Destructor:
        break;
    case MethodKind.EventAdd:
        break;
    case MethodKind.EventRaise:
        break;
    case MethodKind.EventRemove:
        break;
    case MethodKind.ExplicitInterfaceImplementation:
        break;
    case MethodKind.UserDefinedOperator:
        break;
    case MethodKind.Ordinary:
        break;
    case MethodKind.PropertyGet:
        break;
    case MethodKind.PropertySet:
        break;
    case MethodKind.ReducedExtension:
        break;
    case MethodKind.StaticConstructor:
        break;
    case MethodKind.SharedConstructor:
        break;
    case MethodKind.BuiltinOperator:
        break;
    case MethodKind.DeclareMethod:
        break;
    case MethodKind.LocalFunction:
        break;
    default:
        break;
}
``` 
</details>

P.S. I'm not sure what is the good behavior for this case, but it you think that the current behavior is incorrect or something else, let me know about it.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
