### ISSUE TITLE
code fix for IDE0032 analyser (Use auto property) creates broken code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28511]
The code fix for IDE0032 analyser (Use auto property) creates broken code. Please check the following example:

```csharp
using System.Windows;
using FluentAssertions;
using Xunit;

namespace CleanupBug
{
    public class CleanupClass
    {
        private Rect bounds = Rect.Empty;

        public Rect Bounds => this.bounds;

        public void Setup()
        {
            this.bounds = new Rect(new Point(10, 10), new Point(20, 20));
            this.bounds.Offset(10, 10);
        }
    }

    public class TestClass
    {
        [Fact]
        public void Test()
        {
            var sut = new CleanupClass();
            sut.Bounds.Should().BeEquivalentTo(Rect.Empty);

            sut.Setup();

            sut.Bounds.Should().BeEquivalentTo(new Rect(new Point(20, 20), new Point(30, 30)));
        }
    }
}
```

In VS2017 (15.7.4) the field &quot;bounds&quot; will be identified to be convertible to auto property.
Before applying the code fix the UnitTest succeed.
After applying the code fix the UnitTest fails.

The reason - I think - is that the Rect data will be copied when accessing the auto property with the Offset method, because Rect is a struct.
So, the original data will NOT be modified.

Either the analyzer should not get struct fields or the code fix should take care modifying access.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/289507/code-fix-for-ide0032-analyser-use-auto-property-cr.html
VSTS ticketId: 644840_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
:bulb: Someone should add the **expected** and **actual** behaviors for this bug so it's clear from reading the bughow the code is breaking.

**Comment by lukas-ais** [comment]
Actual: The test method TestClass.Test in the sample above will pass. The field "bounds" will be marked with IDE0032 to be rewritten to auto-property. If you do so, the test method will fail.
Accessing the Rect struct using field, the Offset method will directly change the field. But, accessing the Rect struct using the property, the Offset method will change a COPY of the struct.

Expected: The field should not be marked with IDE0032 if it is a struct and modifying access exists.

@sharwell, hope this is sufficient information.

**Comment by CyrusNajmabadi** [comment]
@ygoe That's the same issue as above.  Both are writes of a mutable value-type field.

**Comment by ygoe** [comment]
@CyrusNajmabadi I know, but it wasn't obvious (to me) from the initial report that the code fix causes a compiler error, just a wrong runtime behaviour.
