### ISSUE TITLE
Link to download PDF on wiki is dead

### ISSUE THREAD

**Issue by renzet** [dotnet/roslyn#28521]
On the wiki page [Roslyn Overview](https://github.com/dotnet/roslyn/wiki/Roslyn%20Overview) the link to download the page as PDF leads to [codeplex](https://www.codeplex.com/Download?ProjectName=roslyn&DownloadId=822125) and is no longer working.

**Comment by jinujoseph** [comment]
to be duped

**Comment by sharwell** [comment]
Duplicate of #25989
