### ISSUE TITLE
Tool to analyze current composition

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#28525]
Currently, when implementing a Host, there's a ton of hoops that need to be done to ensure the service surface that roslyn defines as possible to implement is done.

Specific scenario 1 - Service is stubbed
There is a stub workspace service implementation in Roslyn, Hosts do not do anything, there is no way to figure out if something is missing. This meant that there was no service to hold recent compilations in memory.

I.e. IProjectHostCacheService.

Specific scenario 2 - service is hard coded via implementation detail
After implementing that service and we got rid of our custom compilation retaining system, we noticed that the only thing holding Compilations in memory were weakreferences from WeakValueSource, causing us to continuously recompute Compilations. The fix was to add a BackgroundCompiler.

Specific scenario 3: service is missing
This means that exceptions will be thrown by the composition. This is okay, but might be better to have as a build-time report.

**Comment by Therzok** [comment]
The idea of a MEF analysis tool is too broad to be Roslyn's responsibility.

The main issue we had was that some services are optional, some end up stubbed with a NOP implementation, and functionality is enabled in the Workspace based on figuring out which services need to be implemented by a different host.

Not a problem anymore, for us, I think.

**Comment by jmarolf** [comment]
I think a set of analyzers that help with MEF composition would be appropriate for the [roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers) repo

**Comment by Therzok** [comment]
In case anyone hits this in the future, [vsmefx](https://github.com/microsoft/vs-mef/blob/c3e284a93bbd2ede8a8ee3a398a0637035ddadbd/doc/vsmefx.md) dotnet tool is great
