### ISSUE TITLE
The Generate Constructor fix uses variable from the class 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#28528]
Affected Branch: [27911.0.d15.8]
Affected Build: 15.8.0 Preview 5.0
Affected Product Language: 

Steps to reproduce:

1. Create new Console App C#
2. Add new class - Class1.cs:
class Class1
{
    private int v;
}
3. Add to Main method in Program.cs:
var c = new Class1(123);
4. Open Quick Actions for underlined Class1 and choose "Generate constructor in Class1"

Actual: the generated constructor uses the already existing variable v
Note: if you rename variable v in Class1 (e.g. to t) then generated variable v and constructor that uses it

[Repro Gif](https://microsoft-my.sharepoint.com/:i:/p/v-rodudi/EdEjkzkgbMBLtqPWs40WzjsBw6T57VIMOBykvslp8MULLA?e=5mdrY6)

**Comment by v-rodudi** [comment]
JFYI: ticket author @v-rodudi won't be available after 9/4 so please ask repro-related questions before this date if they are.

**Comment by CyrusNajmabadi** [comment]
Closing out as acceptable current behavior.
