### ISSUE TITLE
Option to prevent code format from removing extra inline spaces

### ISSUE THREAD

**Issue by JohannesMP** [dotnet/roslyn#28536]
## Overview

(Visual Studio 2017 15.7.3)

The automatic code formatting portion of Visual C# projects in Visual Studio can be very useful. It allows you to maintain a consistent code style across your project. However there is one case where I feel an option for it to be less aggressive would solve a lot of formatting woes.

Specifically, if there are more in-line whitespaces than an auto-formatting rule would dictate, I would like the option to have auto-formatting not remove them.

## Basic Example

1. If a user enables `C# > Code Style > Formatting > Spacing > Set spacing for operators > Insert space before and after binary operators` then the following line:

```c#
a+b
```

Auto-formats to:

```c#
a + b
```

----

2. However this line:

```c#
a     + b
```

Also auto-formats to:

```c#
a + b
```

I would like to have the option of, while still enforcing behavior 1. (adding the spaces if the minimum of one space is not met), having behavior 2. (removing extra spacing above the minimum of one space) not occur.

## Another Example

Given the following (deliberately contrived) example snippet:

```c#
     namespace Foo
{
    public static class Bar
        {
private static int a                =1;
        public  static int some_very_long_b=2;
    public  static double Derp(double value)
    {
    if      (value<a               ) return 0;
       else if (a    >some_very_long_b) return 1;
     return value;
}
}
}
```

With the behavior I am describing, running code format would yield:

```c#
namespace Foo
{
    public static class Bar
    {
        private static int a                = 1;
        public  static int some_very_long_b = 2;

        public  static double Derp(double value)
        {
            if      (value < a               ) return 0;
            else if (a     > some_very_long_b) return 1;
            return value;
        }
    }
}
```

Note how:
1. In accordance with the default `Formatting > Indentation` options, all scopes are correctly indented.
2. In accordance with the default `Formatting > Spacing > Set spacing for operators` option, the `=` and `<` operators have been padded with an extra space if they didn't already have one.
3. However any additional whitespace was not removed.

## Summary

I'm not sure exactly what the implementation specifics would be, but in general I feel like it would be useful to have options to `don't remove extra whitespaces` for some of the rules in `Formatting > Spacing`. 

I'm fine if a rule dictates that there needs to be a space in a specific case for one to be added, but if additional spaces are present I would like an option to just not remove them and let the user handle that themselves.

**Comment by sharwell** [comment]
I'm going to tentatively mark this as **Won't Fix**, but will bring up the topic in a design meeting with the team and will update (or close) the issue as appropriate from the conclusion in that meeting. My reasons for this are the following:

1. This is a relatively infrequently used code style
2. It is relatively easy to write an analyzer which validates the desired code style during the build
3. Our Code Cleanup feature (first introduced in the 15.8 release) has a long term goal of allowing other analyzers (including 3rd-party analyzers) to participate in the Code Cleanup process

Item (1) means this feature is a relatively low priority feature for the team, so it could take some time to complete and it still raises questions of maintenance. Item (3), on the other hand, is a high-priority feature we are actively working on a design for. Combining options (2) and (3) would allow a team to deliver this feature in a completely customized manner *without* the delay from item (1), making it an overall superior path forward.

**Comment by JohannesMP** [comment]
Hi sharwell, thanks for the quick reply! I definitely look forward to further developments on the code cleanup feature.

While the specific code style I described is infrequent, the desire to have code align a certain way is pretty common and there are of course [many](https://blog.jetbrains.com/dotnet/2017/11/28/aligning-code-columns-resharper-rider/) [solutions](https://marketplace.visualstudio.com/items?itemName=wwm.better-align) [for](https://github.com/steve8708/vscode-align) [that](http://www.codemaid.net/) [already](https://marketplace.visualstudio.com/items?itemName=cpmcgrath.codealignment-vscode). 

I personally am fine with manually aligning my code and if it would be possible to have an analyzer that only touches leading whitespace and then only adds whitespace (`a+b` becoming `a + b`, etc) but doesn't remove whitespace within a line, I honestly think it would make most of these solutions unnecessary for my workflow.

**Comment by sharwell** [comment]
@JohannesMP I agree with your statements in general. The place where this gets challenging is here:

> ... the desire to have code align a certain way is pretty common ...

While true, there are a very large number of edge cases where different people have different opinions about the exact number of spaces that apply. In the end, the following approach seems to work well (at least for now):

* Provide a solution out-of-the-box that works well for *most* users which is consistent and easy to maintain
* Make it easy for end users to create fully customized solutions that work just as well as the one we provide

As we watch how the second item develops over time, I believe we will all gain a better understanding of the primary points where configuration is needed and used, and start to consolidate solutions to a few that stand out as widely used.

**Comment by sharwell** [comment]
Today's design review confirmed the **Won't Fix** resolution, and further confirmed the desire for the Code Cleanup feature to expand to support independent implementations of a feature like this through third-party analyzers, code fixes, and/or refactorings.

**Comment by BararDiHoumes** [comment]
The code looks really messy almost 5 years after this post.
Is there so much work that this can not be fixed ?

**Comment by sharwell** [comment]
> Therefore, a statement like "This is a relatively infrequently used code style" , please excuse me, feels a bit derogatory given my experience as a programmer. 

Please don't read what I said as derogatory. I'm simply stating things as they have been observed. There are literally millions of developers working with this language, so even if we identified a few hundred people passionate about the style you describe it could still be "relatively infrequent".

**Comment by JVimes** [comment]
I want this feature.
