### ISSUE TITLE
VB: Autocomplete produces incorrect closing tag for XML literals with computed names.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#28534]
**Version Used**: 

Visual Studio Community 2017 v15.5.6

**Steps to Reproduce**:

Suppose you want to type the XML literal `<foo></foo>`. So you type the opening tag name until `<foo`:

![vs_xml_autocomplete_1](https://user-images.githubusercontent.com/20465797/42720200-858e3920-872b-11e8-8280-73fcc1665f42.png)

When you type the closing `>` the editor handily autocompletes the closing tag `</foo>` so you end up with:

![vs_xml_autocomplete_2](https://user-images.githubusercontent.com/20465797/42720214-b03fa4b0-872b-11e8-9ddf-799c70bf0fc8.png)

However if the name of the tag is computed by an expression and you type:

![vs_xml_autocomplete_3](https://user-images.githubusercontent.com/20465797/42720221-d745e27c-872b-11e8-87df-c1221fcf07c9.png)

...then followed by the closing `>`, autocomplete kicks in for the closing tag like before, but it duplicates the expression and uses it as the closing tag, which is an error:

![vs_xml_autocomplete_4](https://user-images.githubusercontent.com/20465797/42720232-ffc1989a-872b-11e8-8cd4-735db2465a39.png)

**Expected Behavior**:

The closing tag for elements with a computed name is `</>` and that's what the editor should produce for correct results:

![vs_xml_autocomplete_5](https://user-images.githubusercontent.com/20465797/42720244-552ec1a4-872c-11e8-9c24-1bbc0fe14ae5.png)

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to change tehse vb experiences.
