### ISSUE TITLE
VB: Autocomplete does not work for XML elements nested immediately inside elements with computed names.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#28535]
**Version Used**: 

Visual Studio Community 2017 v15.5.6

**Steps to Reproduce**:

This may be related to #28534 (I noticed it shortly after filing that issue). Type the following code into a VB project:

```vb
Public Module Module1
  Public Sub Main()
    Dim xml = <<%= "foo" %>>
                'elements nested here will NOT have autocompletion for closing tags
              </>

    Dim yml = <bar>
                'elements nested here WILL have autocompletion for closing tags
              </bar>

  End Sub
End Module
```

As mentioned by the text in the XML literals above, when an outer XML literal has a literal name like `<bar>`, any nested elements in it WILL have autocompletion for their closing tags, as expected. So inside `<bar> ... </bar>` if you were to type something like `<baz>` the editor will automatically insert `</baz>`:

```vb
    Dim yml = <bar>
                'elements nested here WILL have autocompletion for closing tags

                <baz>
                  'closing tag was autocompleted for this element.
                </baz>
              </bar>
```

**However trying the same thing inside an XML literal with a computed name, you just end up with the opening tag you typed manually, the editor does NOT create the closing tag as expected**:

```vb
    Dim xml = <<%= "foo" %>>
                'elements nested here will NOT have autocompletion for closing tags 
                <baz>
                    'editor should have created the closing tag for the nested element baz above
                </>
```

Pressing enter after typing `<baz>` above causes the closing`</>` tag to be indented almost as if the editor thinks it matches with `<baz>` instead of the outer literal `<foo>` which has a computed name.

Interestingly enough, it appears the `</>` tag is causing the editor to trip up, because if you nest an element with a regular closing tag, then try to nest another element inside THAT, autocomplete will add closing tags as expected:

```vb
    Dim xml = <<%= "foo" %>>
                <baz>
                 'elements nested here WILL have autocompletion for closing tags
                 'it seems to depend on whether the parent element has a computed name or not
                </baz>
              </>
```

**Expected Behavior**:

Autocompletion for XML closing tags of nested elements should work regardless of whether the parent element has a literal name or computed name.

PS: this was a bit tricky to explain, if needed I can try again with step by step screenshots like in #28534.

PPS: now that Microsoft owns Github, it would be nice to see colour-coding support for all features of VB code typed into these issues (e.g. XML literals are not supported at all right now).

**Comment by CyrusNajmabadi** [comment]
Clsing out as we're unlikely to change these VB experiences.
