### ISSUE TITLE
C# Quick Actions doesn't work with Extension Methods with out parameters

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28552]
<p>C# Quick Actions &quot;Generate method stub for '...' in '...'&quot; doesn't work if the following conditions are satisfied:</p><p>The method that doesn't exist</p><ol>
<li>is in an extension method</li><li>has the same name as the extension method</li><li>has an out parameter</li></ol><p>In Visual Studio 2013, it works fine even if these conditions are satisfied. In Visual Studio 2017, it doesn't work. This is the problem.</p><p># Visual Studio 2013</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/5322-vs2013ctrlperiod.png"> Image:5322-vs2013ctrlperiod.png</a></p><p># Visual Studio 2017</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/5323-vs2017ctrlperiod.png"> Image:5323-vs2017ctrlperiod.png</a></p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/51358/c-quick-actions-doesnt-work-by-a-condition.html
VSTS ticketId: 429124_
_These are the original issue comments:_

![image](https://user-images.githubusercontent.com/12449387/42732150-6492f30a-87d0-11e8-86a7-399986ed5d2b.png)

**Comment by CyrusNajmabadi** [comment]
I don't repro this:

![image](https://user-images.githubusercontent.com/4564579/152606130-ee1bfc7a-8f08-4853-97a7-c2c920250005.png)
