### ISSUE TITLE
VB IDE support for using latest Compiler Version

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#28557]
@paul1956 commented on [Fri Jun 01 2018](https://github.com/dotnet/vblang/issues/308)

I am trying to use Features of VB 15.5 (named parameters with param arrays) and keep getting messages about using latest compiler but there is no way I found in Visual Studio to specify compiler version or to use latest. For C# there is a CodeFix and IDE option plus the ability to Use Latest (major or minor version) though they are a little buried.

---

@AnthonyDGreen commented on [Sun Jun 03 2018](https://github.com/dotnet/vblang/issues/308#issuecomment-394147247)

@paul1956 ,

Here's the issue tracking this feature: https://github.com/dotnet/project-system/issues/3141
@jcouv implemented it for C# and might know how the work is coming along for VB.

---

@MohammadHamdyGhanem commented on [Sun Jun 10 2018](https://github.com/dotnet/vblang/issues/308#issuecomment-396080567)

Is there minor releazes of vb? I see a new minor releaze of C# every couple of month.
I disagree with the new policy about VB.net, and I believe it should be introduced to beginners on other OSs as well, and it will gain a wide popularity on these systems too.

---

@paul1956 commented on [Sun Jun 10 2018](https://github.com/dotnet/vblang/issues/308#issuecomment-396083516)

@AnthonyDGreen I don't think #3141 addresses the problem (but it might fix it by accident), the issue is clearly covered in #17495. It is not about some future new feature, it is about using features that were added in 15.3 and 15.5 and existing errors from the compiler without help getting them fixed.

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/issues/17495

**Comment by CyrusNajmabadi** [comment]
Closing out a we are not changing these vb experiences.
