### ISSUE TITLE
Brace formatting does not work with "Open Folder"

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#28553]
**Version Used**: 15.8 Preview 4

:link: Originally reported on developer community:
[brace completion with auto formatting, indentation broken in c#](https://developercommunity.visualstudio.com/content/problem/35614/brace-completion-with-auto-formatting-indentation.html)

**Steps to Reproduce**:

:memo: In each of the code examples, `|` represents the caret location.

1. Use the **Open Folder** feature of Visual Studio to open a folder containing C# source files
2. Type the following inside a class:

    ```csharp
    void Method()|
    ```

3. Press <kbd>Enter</kbd>
4. Press <kbd>{</kbd>
5. Press <kbd>Enter</kbd>

**Expected Behavior**:

```csharp
        void Method()
        {
            |
        }
```

**Actual Behavior**:

```csharp
        void Method()
            {
}           |
```

**Comment by sharwell** [comment]
I've seen a handful of formatting bugs related to using Open Folder. We should review these as a group.

**Comment by andreacarrarini** [comment]
Still no solution?
Had this happening today form nowhere, VS has worked fine for days and today started doing this stuff.
I also noticed that if you close and re-open VS the first time the indentation is ok, from the second one it starts doing this mess.

**Comment by xmarklar** [comment]
Same. Was happening on VS 2017.  But now also on VS 2019 too... v. 4.7.03056

**Comment by CyrusNajmabadi** [comment]
Closing out as 'open folder' is a not a scenario we are investing in.
