### ISSUE TITLE
Remove csc2/vbc2 from the NuGet package and update the NuGet package to use the new build task.

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#2857]
The NuGet package currently uses csc2/vbc2 to talk to the compiler server. We should instead use the build task to talk to the compiler server. We also only want to do this if the client has explicitly signed up.

The NuGet authoring and props file for the Microsoft.Net.Compilers package should be updated to do this.

**Comment by agocke** [comment]
* Customer scenario - The customer wishes to use the compiler server by using a NuGet package. Currently they are forced to use csc2/vbc2 which are not intended to ship as 1.0 or be supported in the future. Instead, the NuGet package should bundle the build task for compiler server interaction.
* Fix description - (Note: fix in TFS internal review) Include the build task in NuGet authoring and remove csc2/vbc2. Replace calls to csc2/vbc2 by default to csc/vbc and allow for compiler server opt-in using the included build task.
* Testing done - Manual testing on C#/VB console app on Windows by installing locally built NuGet package and rebuilding. Verified that correct compiler was being invoked. Also verified that when project file was modified to use the `UseSharedCompilation` property to use the compiler server the correct VBCSCompiler instance was started and used to serve the compilation.

**Comment by MattGertz** [comment]
MoreInfo 5/29 by ML Shiproom.

**Comment by agocke** [comment]
Resolved with CS 1479511 into Main and 1479522 into stable
