### ISSUE TITLE
VB: Strange "unresolvable conflicts" error when renaming field of anonymous type.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#28572]
**Version Used**: 

Visual Studio Community 2017 v15.5.6

**Steps to Reproduce**:

Type the following code:

```vb
Public Module Module1
  Public Sub Main()
    Dim qry = From v In {"foo", "bar"}
              Select StringVal = v, StringLength = v.Length

    Dim res = qry.FirstOrDefault()

    Dim sval = res.StringVal
    Dim slen = res.StringLength
  End Sub
End Module
```

The LINQ query assigned to the variable `qry` uses an anonymous type with two fields `StringVal` and `StringLength`. Right click on `StringVal` and choose Rename, so you can rename it to say `StringValue`:

![vs_rename_anon1](https://user-images.githubusercontent.com/20465797/42743050-0b3c61ac-88c9-11e8-9658-d0cb26a090ff.png)

As shown above, the Rename dialog pops up and waits for you to proceed. But as you type the extra letters `ue`, the Rename dialog complains about "unresolvable conflicts":

![vs_rename_anon2](https://user-images.githubusercontent.com/20465797/42743101-6be8c57c-88c9-11e8-991e-68020d01cc14.png)

...which is confusing to me because there's absolutely nothing else in that code called `StringValue` such that the new name would conflict with it in some way.

**Expected Behavior**:

I believe this Rename operation should be supported. I do know for example you can't rename members of anonymous types by starting from an expression such as the one on the line:

```vb
Dim sval = res.StringVal '<-- can't rename StringVal from here.
```

...the operation is rejected outright with a clear message:

![vs_rename_anon3](https://user-images.githubusercontent.com/20465797/42743192-5d70f5f4-88ca-11e8-9e00-4622c3d6a6f3.png)

Perhaps in the interim the same error can be shown if you attempt to rename from the LINQ query instead of that "unresolvable conflicts" one?

Ultimately, it would be awesome to be able to rename fields of anonymous types at any location :+1:

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not intending to invest in these scenarios anymore.
