### ISSUE TITLE
Localize strings used in new Tools->Options .editorconfig generation feature

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#28584]
I submitted a PR [here](https://github.com/dotnet/roslyn/pull/28472) to generate an .editorconfig file from Tools->Options settings. There are some hard-coded strings that may need to be localized.

**Comment by Neme12** [comment]
I am a little bit worried about localizing comments inside `editorconfig` itself. `editorconfig` is almost always intended for teams as opposed to individual developers and it doesn't seem desirable to localize comments in that file based on any particular user's language preference.

For example let's say that my language was other than English but I'm creating an editorconfig for an open-source repo where we use english as a common language. Do I have to change my UI language to english temporarily and then change it back? I would prefer this either isn't localized at all or if it is, there's an option in the UI for which language to generate.

**Comment by CyrusNajmabadi** [comment]
> I am a little bit worried about localizing comments inside editorconfig itself. editorconfig is almost always intended for teams as opposed to individual developers and it doesn't seem desirable to localize comments in that file based on any particular user's language preference.

Falling back to english is equally non-desirable.  If you are a team in japan, entirely populated with japanese team members, why are we emitting english?

> . It is not necessarily true that my language would be shared by everyone on the team.

This is true of effectively all localization tasks.  We have to gets signals from somewhere, and it's somewhat reasonable to use the locale of the current user as such a signal.  I don't think we need to go to the level of trying to provide support for customizing this.

**Comment by mavasani** [comment]
This is complete.

**Comment by 20chan** [comment]
This happened to me.
Visual Studio 2019 16.3.6, Korean, C#.
https://gist.github.com/20chan/a5bcb788d64769fe9a5eb1cdec3b011e

**Comment by sharwell** [comment]
@20chan The text in comments (lines starting with `#`) is localizable. All of the other lines are significant syntax defined as the character sequence you see and cannot be localized.

**Comment by sharwell** [comment]
Note that there are some special cases in naming rules that _look_ localizable, but only part of the lines can be localized. For example, the sections circled in the following image come from text that a user could modify, which means they can be partially localized:

![image](https://user-images.githubusercontent.com/1408396/67863078-74296900-fae0-11e9-8342-e2d751045dc1.png)

**Comment by 20chan** [comment]
@sharwell Oh it's my mistake. Wrong issue.
