### ISSUE TITLE
PrettyListing should insert parentheses around single argument invocations

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#2858]
In VS2013 and previous, we would insert parentheses around a single argument method call like:

``` VB
MsgBox "Hi There"
```

We stopped doing that in Roslyn because people found it irritating when they pasted blocks of text that didn't parse quite right and the pretty-lister added a bunch of parentheses everywhere.

We should consider bringing the feature back in a more selective way.  Some ideas we had are:
1. Do it only if the identifier binds as something invocable.
2. Do it as part of end construct instead of pretty-listing, so that it happens only on enter.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not changing these vb experiences.
