### ISSUE TITLE
Code Style Options set via Tools → Options do not automatically refresh

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#28581]
**Version Used**: 15.8 Preview 4

**Steps to Reproduce**:

1. Set a code style option in Tools &rarr; Options &rarr; Text Editor &rarr; C# &rarr; Code Style
2. Open a document which contains a diagnostic for the item configured in (1)
3. Update the code style option to change the preference and/or severity

**Expected Behavior**:

The diagnostics update in the open file to reflect the new preference(s).

**Actual Behavior**:

The diagnostics do not update until the file is closed and reopened.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
