### ISSUE TITLE
Analyzers have a different result for build and intellisense

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28582]
After adding static code analyzers:

```xml
<package id="Microsoft.CodeQuality.Analyzers" version="2.6.0" targetFramework="net452" developmentDependency="true" />
<package id="Microsoft.NetCore.Analyzers" version="2.6.0" targetFramework="net452" developmentDependency="true" />
<package id="Microsoft.NetFramework.Analyzers" version="2.6.0" targetFramework="net452" developmentDependency="true" />
<package id="StyleCop.Analyzers" version="1.0.2" targetFramework="net452" developmentDependency="true" />
<package id="Text.Analyzers" version="2.6.0" targetFramework="net452" developmentDependency="true" />
```

The project does not compile, but Intellisense shows no errors.

If I create a ruleset that uses the same rules that cause the compilation to fail, then intellisense shows red squiggles (as would be expected for a failing build)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/249067/analyzers-have-a-different-result-for-build-and-in.html
VSTS ticketId: 613536_
_These are the original issue comments:_

Sam Harwell [MSFT] on ‎5‎/‎21‎/‎2018, 09:23 AM (56 days ago): <p>Thank you for your feedback! For us to investigate this further, could you please provide specific steps to reproduce the issue.  We look forward to hearing from you!</p><p><br></p><p>Hi tiba,</p><p><br></p><p>In the image attached with this feedback report, the IDE appears to be reporting errors that would cause the project to not build. It's not clear to be which part of the experience is producing unexpected results. Can you provide a set of steps to reproduce the original issue, and also a description of the expected behavior and actual behavior so we can more easily see the difference?</p><p><br></p><p>Thank you,</p><p>Sam Harwell</p>

tiba on ‎6‎/‎13‎/‎2018, 08:03 AM (33 days ago): <p>Hi Sam,</p><p>I can write code like</p><pre>public int[] ImportantValues \{ get; set; }</pre><p>And then I add the packages as indicated above.</p><p>Now the build will fail as I should not have an array as a property.</p><p>However, the IDE will not have put red squiggles underneath, unless I change the rules first.</p><p>I would expect that the out-of-box functionality of this to be that IDE (intellisense) puts red squiggles underneath when the build is going to break because of a rule violation - rather than having to build, and then go through the build errors to find what's wrong.</p><p>I managed to get the red squiggles working as expected by opening the rules, and then manually setting everything to what was already shown.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.
