### ISSUE TITLE
#Else not offered in #If'd out VB code (but is offered in C#)

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#286]
Ported from TFS WorkItem: <b>1089194</b>

---

<p><b>Repro Steps:</b></p>

<P><B>Affected Branch:</B> <BR><B>Affected Build:</B> <BR><B>Affected Product Language:</B> <BR><BR><B>Steps to reproduce:</B><BR><BR>1. Copy/Paste VB:</P>

<P>&nbsp;</P><PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: blue">Imports</SPAN> <SPAN style="COLOR: black">System</SPAN>
<SPAN style="COLOR: blue">Imports</SPAN> <SPAN style="COLOR: black">System</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">Collections</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">Generic</SPAN>
<SPAN style="COLOR: blue">Imports</SPAN> <SPAN style="COLOR: black">System</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">Linq</SPAN>
 
<SPAN style="COLOR: blue">Module</SPAN> <SPAN style="COLOR: #2b91af">Program</SPAN>
    <SPAN style="COLOR: blue">Sub</SPAN> <SPAN style="COLOR: black">Main</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: black">args</SPAN> <SPAN style="COLOR: blue">As</SPAN> <SPAN style="COLOR: blue">String</SPAN><SPAN style="COLOR: black">())</SPAN>
<SPAN style="COLOR: blue">#If</SPAN> <SPAN style="COLOR: black">Foo</SPAN> <SPAN style="COLOR: blue">Then</SPAN>
<SPAN style="COLOR: gray">
        $$
 
</SPAN><SPAN style="COLOR: blue">#End</SPAN> <SPAN style="COLOR: blue">If</SPAN>
    <SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Sub</SPAN>
<SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Module</SPAN></PRE>
<P>&nbsp;</P>

<P>2. Remove the $$ if necessary and type #</P>

<P>&nbsp;</P>

<P><STRONG>Expected</STRONG>: Completion list offered with, for example, "Else" (see Dev12 for full list)</P>

<P><STRONG>Actual</STRONG>: No completion offered</P>

---

<p><b>Revisions:</b></p>

1) Created By David Poeschl (12/1/2014 1:38:18 PM)

---

2) Edited By Kevin Pilch-Bisson (12/2/2014 8:50:50 AM)

I think we'd have to special case a # being typed inside disabled text trivia, since the parse tree actually does treat all of this as disabled text.

---

**Comment by CyrusNajmabadi** [comment]
We would take an external PR for this.

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to change tehse VB experiences.
