### ISSUE TITLE
Intellisense should suggest static members of target type

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#28603]
(Visual Studio 15.7.5)

Intellisense should suggest static members of the target type which return an instance of the target type.

After typing `Foo(e`, wanting to pass an empty immutable array:

![image](https://user-images.githubusercontent.com/8040367/42826164-c48ff752-89b1-11e8-847a-2628f28c573c.png)

After typing `Foo(e` (ReSharper):

![image](https://user-images.githubusercontent.com/8040367/42826353-30f2433c-89b2-11e8-9fef-02af60468ce7.png)

Visual Studio, after typing `Foo(e)`:

![image](https://user-images.githubusercontent.com/8040367/42826441-667ee29e-89b2-11e8-89e6-d716e64c0e17.png)

With ReSharper, after typing `Foo(e)`:

![image](https://user-images.githubusercontent.com/8040367/42826402-4dfff8a2-89b2-11e8-9033-a46f9c4e1282.png)

This is also quite useful for hand-rolled discriminated unions. (`foo = Foo.Bar`, `foo = Foo.Baz(3)`, etc.)

**Comment by sharwell** [comment]
The easiest initial generalization would be an expansion of the current support for enum values: include target-typed static fields and properties of the target type in completion.

**Comment by RikkiGibson** [comment]
It feels like there's no need for this to end at fields/properties, you could also be typing 'cr' and benefit from getting `ImmutableArray.Create<T>()`

**Comment by Joe4evr** [comment]
> The easiest initial implementation would be a generalization of the current support for enum values: include target-typed static fields and properties of the target type in completion.

Does this also include assignments?

**Comment by jnm2** [comment]
@Joe4evr I would expect that.
