### ISSUE TITLE
Revisit line ending checks in MarkupTestFile.Parse

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#2861]
I have removed the below check since it was causing failures on Mac:

http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_mac_prtest/834/console

The root cause is unknown atm.

```
 private static void Parse(string input, out string output, out int? position, out IDictionary<string, IList<TextSpan>> spans)
         {
            if (input.Contains("\n") && !input.Contains("\r\n"))
            {
                throw new ArgumentException("Shouldn't pass stuff with bad line endings!");
           }
```

**Comment by Pilchie** [comment]
The problem here is when input comes from xml literals, it only has `\n` for line endings, and (at least in the past), various features didn't work the same with differing line endings.

**Comment by davkean** [comment]
Dropping infrastructure, adding IDE and assigning to @CyrusNajmabadi, he mentioned that this check shouldn't have been present in the first place. I'll let him close it out.

**Comment by CyrusNajmabadi** [comment]
Removing this code was the right thing to do.
