### ISSUE TITLE
Immediate window can't resolve dictionary member in UWP app

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#2863]
Repro:
(1) File>New>VB>Windows>Blank UWP app
(2) Add a Sub New to MainPage.xaml.vb as follows:
```vb
Sub New()
    InitializeComponent()
    Stop
End Sub
```
(3) When execution halts at the "Stop" statement, go to the immediate window and type in "? App.Current.Resources.First.Key"

WHAT I GET:
```vb
? App.Current.Resources.First.Key
'Key' is not a member of 'Windows.Foundation.Collections.IIterator(Of System.Collections.Generic.KeyValuePair(Of Object, Object))'.
```

WHAT I EXPECT: it should give an exception on "First" because the size of App.Current.Resources.Count is zero.

**Comment by cston** [comment]
App.Current.Resources.First binds to ResourceDictionary.First() which returns IIterator(Of KeyValuePair(Of Object, Object)) rather than System.Linq.Enumerable.First().

**Comment by ljw1004** [comment]
This isn't right...

(0) The bottom line is that ImmediateWindow should be binding to the same thing that the compiler binds to. There's nothing about this case that justifies a divergence. And at compile-time, ResourceDictionary.First does bind to the extension method.

(2) There isn't a method called ResourceDictionary.First.

(3) ResourceDictionary implements IIterable in winmd terms, but this is projected by the CLR into an IEnumerable.

(4) Are you sure about what you wrote? I can't understand why there would ever be a method called First() which returns an IIterator.

(5) When I do App.Current.Resources.First() in the immediate window, intellisense shows it as the IEnumerable extension method, and it fails with the message "Method 'First' in ComImport class 'Windows.UI.Xaml.ResourceDictionary' must implement an interface method."

**Comment by cston** [comment]
The EE binds to the (private) method ResourceDictionary.First rather than Enumerable.First since the EE ignores accessibility. This is consistent with the legacy EE.

However with the repro steps, not all modules are loaded to allow the legacy EE to bind ResourceDictionary.First initially. Change the repro the following instead and use the legacy EE to see the same behavior as the new EE.

        InitializeComponent()
        Application.Current.Resources.Any()
        Stop

**Comment by ljw1004** [comment]
Dang!
