### ISSUE TITLE
GC leak tests are failing on x64 runs

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#28639]
A number of our tests to ensure we don't leak memory are failing on x64 runs:

```
Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.ProjectCacheHostServiceFactoryTests.TestCacheKeepsObjectAlive1 [FAIL]
      Reference should have been released but was not.
      Expected: False
      Actual:   True
```

These all pass on Jenkins today but fail in VSTS and locally on developer boxes. The suspicion is that the root cause is a change in the .NET Framework version being used to run the tests. It's unclear what version of .NET Jenkins is running but in all cases the failure is seen the version is 4.7.1+. 

Disabling these tests for now while we dig into this.

The failure happens on both Win10 Client and 2016 Server.

**Comment by jaredpar** [comment]
We've confirmed the difference here is RyuJIT. This is not to say it's a bug in RyuJIT. It's saying that the pattern we use for leak detection doesn't work on RyuJIT here. Probably just a better pattern we should move to. Working with CLR team.

**Comment by CyrusNajmabadi** [comment]
This test doesn't exist anymore.
