### ISSUE TITLE
EditorConfig properties not taken into account when using a snippet

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28638]
🔗 [AB#524086](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/524086)
🔗 [AB#1232158](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1232158)
🔗 [AB#1446357](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1446357)

Hi,

my .editorconfig file has the property &quot;end_of_line&quot; set to &quot;lf&quot;. When I type in a source file, it's working as expected, all lines end with &quot;lf&quot;.
But when I insert a snippet in VS2017 (15.4.3), even though my snippet has no &quot;crlf&quot; in it (I specifically put &quot;lf&quot; only), the file contains &quot;crlf&quot; instead of &quot;lf&quot; on all added lines.

So it looks like there is a pass of auto-indent that is called after the snippet is pasted, and editorconfig is not triggered.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/149424/editorconfig-properties-not-taken-into-account-whe.html
VSTS ticketId: 524086_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in legacy snippet experiences.
