### ISSUE TITLE
VS remove the empty line from the editor in VS 15.8 preview 4 (latest public)

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#28630]
Create a C# class and (it's internal by default, without specifying the access modifier).

When I format my class it's adding the internal. Is it part of VS functionality or something else, I have Intellicode installed in my VS.

I write 2 static property and 2 non-static property in my class. I put an empty line between these 2 and 2 property.

VS remove the empty line in format when I don't define the access modifier like private and public.

it's work fine if the lines have public and private. This is an issue.

**Comment by CyrusNajmabadi** [comment]
@anirudhagupta I don't repro this myself.  Here's the code i tried to test with:

```c#
class Foo
{
    static int A { get; }
    static int B { get; }

    int C { get; }
    int D { get; }
}
```

When i run format-document, i get:

```c#
internal class Foo
{
    private static int A { get; }
    private static int B { get; }

    private int C { get; }
    private int D { get; }
}
```

The spacing seems to have been preserved.  Could you provide a more complete example that demonstrate the problem?  Thanks!

**Comment by anirudhagupta** [comment]
namespace abcd.Models
{
    internal class abcd
    {
        private static string API_KEY;
        private static string Endpoint;

        string _keyword;
        string abc;



    }
}

This is my code, I rename variable and it's producing same, I have tested it on the latest preview 158 preview 4.

**Comment by CyrusNajmabadi** [comment]
@anirudhagupta Thanks for the updated information.  I repo this now myself.  Looks to be related to fields, not properties.  A nice minimal repo is:

Start with teh following code:

```c#
    internal class c
    {
        private static readonly string a;

        readonly string b;
    }
```

Run Format-Document on it (with the 'add accessibility modifiers' code cleanup setting on).  It will produce:

```c#
    internal class c
    {
        private static readonly string a;
        private readonly string b;
    }
```

Instead of the expected:


```c#
    internal class c
    {
        private static readonly string a;

        private readonly string b;
    }
```

**Comment by CyrusNajmabadi** [comment]
In the meantime @anirudhagupta you can disable this behavior by going here:

![image](https://user-images.githubusercontent.com/4564579/42865399-65c83c8a-8a1e-11e8-8011-3523f862841a.png)

And unselecting: 
![image](https://user-images.githubusercontent.com/4564579/42865421-7382cb24-8a1e-11e8-8dbb-aa906061a7c2.png)

**Comment by anirudhagupta** [comment]
Thanks, done.

**Comment by Neme12** [comment]
@CyrusNajmabadi are you working on this?

**Comment by CyrusNajmabadi** [comment]
Nope.  Go ahead if you want to :)

**Comment by anirudhagupta** [comment]
Nope, I just report bugs here, Let me know if I can help,  I can contribute in c#.

**Comment by Neme12** [comment]
@anirudhagupta Of course you can contribute if you're interested! Do you know at least a little bit about Roslyn syntax trees and trivia?

**Comment by anirudhagupta** [comment]
@Neme12  please tell me where I can get started learning "Roslyn syntax trees and trivia". I never heard this term before.

**Comment by jmarolf** [comment]
@anirudhagupta here is where I would start in terms of learning the roslyn APIs.

- [syntax analysis](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/get-started/syntax-analysis)
- [syntax transformation](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/get-started/syntax-transformation)
- [semantic analysis](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/get-started/semantic-analysis)

You can also ask questions on [gitter](https://gitter.im/dotnet/roslyn) about anything and I will be happy to help.

**Comment by Neme12** [comment]
@anirudhagupta If you've never worked with Roslyn before, you can also find some introductory videos to writing analyzers and code fixes (which this feature is), for example here: https://www.youtube.com/watch?v=Iq43Bq0Hen8 If you prefer video, you might find these useful to get started and understand the basics. I also recommend trying to experiment and write your own analyzer or refactoring.

**Comment by Neme12** [comment]
Well, it looks like this is not an easy fix and probably not a good first issue.

The code fix and the syntax generator seem to be working fine (although I would definitely expect it to be simpler). It seems there's the same elastic trivia in both cases (field & property). The difference must be caused by the formatter, my would guess would be that this is somewhere in http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Formatting/Rules/ElasticTriviaFormattingRule.cs,158

Either the formatter is at fault or the syntax generator creates too much elastic trivia (in both cases).

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
