### ISSUE TITLE
VS 2017 does not recognize comments placed between function definition and its body

### ISSUE THREAD

**Issue by abelkine** [dotnet/roslyn#28640]
VS 2017

**Steps to Reproduce**:

```csharp
void
f()
{
    // Color comment
}
```

```csharp
void
g()
// Uncolored comment
{

}
```

**Expected Behavior**:

Comments should always be of the same color

**Actual Behavior**:

Comments placed between function definition and its body are not recognized.

**Comment by jinujoseph** [comment]
Closing this as No Repro, please update with example if you find otherwise
