### ISSUE TITLE
Enable searching/filtering of member-selection dialogs (e.g. picking members to override)

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#28661]
When attempting to add overrides for a class with a large number of methods (such as visitors), the default sorting according to declaration order in the base class is extremely unhelpful. We should add sorting mechanisms (at least alphabetical) so that users can actually find the method they're trying to override.

**Comment by CyrusNajmabadi** [comment]
> the default sorting according to declaration order in the base class is extremely unhelpful. 

Hrmm... i'm not sure that's the case.  The intent was to preserve any sort of intentional order on the part of hte base class.  

> We should add sorting mechanisms (at least alphabetical) so that users can actually find the method they're trying to override.

if we're going to do this, i would say that we still need to sort by symbol-kind first.  For example, it's likely i might want to override several grouped properties   ```DProp, EProp, FProp```.  However, if we now put .Equals in betwen that, that's not helpful.

**Comment by 333fred** [comment]
> The intent was to preserve any sort of intentional order on the part of hte base class.

I can certainly see the use case in some scenarios. Often what I find, though, is that I know what I'm going to implement, and I just need to find those 3 or 4 methods.

**Comment by dpoeschl** [comment]
Design Meeting Notes
- We'd like to add a search/filter bar to such member-listing/selection dialogs (move member, extract interface, etc.). @333fred Would this be sufficient for your needs, or is there a scenario where sorting is superior to filtering?

**Comment by 333fred** [comment]
@dpoeschl perfect :)

**Comment by dpoeschl** [comment]
FYI @Cosifne

**Comment by Cosifne** [comment]
> 
> 
> FYI @Cosifne

Thanks David.

Sound cool, I would like to follow this thread

**Comment by CyrusNajmabadi** [comment]
Pick members dialog now allows for search/filter.
