### ISSUE TITLE
GFU lightbulb items truncated, can't tell what they do

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#2869]
With sufficiently long type names, the description of light bulb items is truncated. If you look carefully at the preview, you can see that one item includes the text "Adding 'PackageIdentity'...", but the individual menu items are indistinguishable.

![ligthbulb](https://cloud.githubusercontent.com/assets/3751401/7689803/f1421556-fd63-11e4-8026-12e0c3c2a7fd.png)

**Comment by srivatsn** [comment]
The limit is 80 characters and that is imposed by the editor. Please open an internal bug against the editor.

**Comment by rchande** [comment]
Opened an editor bug.
