### ISSUE TITLE
VB Completion on Backspace prefers Enum preselection over prefix/exact match

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#287]
Ported from TFS WorkItem: <b>1015792</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P><B>Affected Branch:</B> <BR><B>Affected Build:</B> <BR><B>Affected Product Language:</B> <BR><BR><B>Steps to reproduce:</B><BR><BR>1. Copy/paste VB code:</P>
<P>&nbsp;</P><PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: blue">Enum</SPAN> <SPAN style="COLOR: #2b91af">E</SPAN>
    <SPAN style="COLOR: black">Bat</SPAN>
<SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Enum</SPAN>
 
<SPAN style="COLOR: blue">Class</SPAN> <SPAN style="COLOR: #2b91af">C</SPAN>
    <SPAN style="COLOR: blue">Sub</SPAN> <SPAN style="COLOR: black">Test</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: black">param</SPAN> <SPAN style="COLOR: blue">As</SPAN> <SPAN style="COLOR: #2b91af">E</SPAN><SPAN style="COLOR: black">)</SPAN>
        <SPAN style="COLOR: blue">Dim</SPAN> <SPAN style="COLOR: black">b</SPAN> <SPAN style="COLOR: blue">As</SPAN> <SPAN style="COLOR: #2b91af">E</SPAN>
        <SPAN style="COLOR: black">Test</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: black">b</SPAN><SPAN style="COLOR: black">.</SPAN>$$<SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Sub</SPAN>
<SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Class</SPAN></PRE>
<P>&nbsp;</P>
<P>2. Remove the $$ if necessary and make sure there's no completion session active (hit ESC for good measure).</P>
<P>&nbsp;</P>
<P>3. Hit backspace.</P>
<P>&nbsp;</P>
<P><STRONG>Expected</STRONG>: Selected completion item is "b" field</P>
<P><STRONG>Actual</STRONG>: Selected completion item is "E.Bat" enum value</P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By David Poeschl (8/26/2014 2:44:41 PM)

------------------------------

**Comment by dpoeschl** [comment]
Regression: previous release

**Comment by rchande** [comment]
@dpoeschl Want to verify this?
