### ISSUE TITLE
Using-var rewriter can be folded into LocalRewriter

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#28707]
I originally proposed a new rewriter pass for the `using var` feature, but I think it's simple enough that it could be put into the VisitBlock in the LocalRewriter. There are only two things I think we need to watch out for:

1. We currently generate a `using` block from `using var` and expect it to be rewritten by a later rewriter. If we keep this structure we need to make sure that the `using` statement rewrite happens after we do the `using var` rewrite.
2. The epilogue and prologue instrumentation is added after local lowering. We may want to adjust it to run before local lowering so it gets nested in the using blocks. This isn't specifically a requirement, but more of a design decision of where instrumentation goes.

**Comment by gafter** [comment]
The design philosophy of the local rewriter forbids visiting nodes generated during lowering. We have methods called `MakeXyzzy` to make a given bound node in lowered form; it takes the fields of an Xyzzy node and produces it’s lowered form (never making an Xyzzy as an intermediary). This helper can be used both for lowering an Xyzzy node and elsewhere where a Xyzzy node would be an intermediate lowered form.

I recommend this design pattern be used here.

**Comment by agocke** [comment]
I had @gafter's idea in mind, as well. That is, in my bullet point (1), when I say "if we keep this structure" -- I don't think we should keep this structure.
