### ISSUE TITLE
Consider passing null as this to optimize cached lambdas

### ISSUE THREAD

**Issue by GSPP** [dotnet/roslyn#28727]
The C# compiler uses a delegate to an instance method when caching a lambda expression. That's being done for performance because delegates to static method are slower.

This:

        new int[0].Select(x => x + 1);

becomes this: https://sharplab.io/#v2:D4AQDABCCMDcCwAocVoDoAyBLAdgRwUSRAGYoAmCAYQgG8kJGoyQAWCAWQAoBKOhpoJwBTAO4RcAFwDaYALpoAysIA2wgMaSuADwgBeAHwRdAagjQehQQF8ktxEA

This means that a dummy instance of a generated type must be created. While reading https://www.red-gate.com/simple-talk/blogs/introduction-to-open-instance-delegates/ I thought that this dummy instance could be avoided by creating a delegate that passes `null` as the `this` parameter. That way a few one-time allocations can be saved.

The article does it through reflection but surely this is possible in IL as well. It appears safe, verifiable code.

It's not a big optimization but I thought I'd contribute the idea. I did not find this mentioned before on this issue tracker.

<hr>

I also noticed the pattern `<>c.<>9__0_0 ?? (<>c.<>9__0_0 = <>c.<>9.<M>b__0_0)`. It would be faster to initialize the cached delegated in a `beforefieldinit` static constructor rather then checking it at each use. Probably, this has already been discussed but I'm mentioning it at this opportunity to make sure the point is noticed.

**Comment by benaadams** [comment]
Just writing as c# with a cast from null to type then calling instance, I get?

`TypeInitializationException: Delegate to an instance method cannot have null 'this'`

On second point; rather than:
```csharp
private sealed class <>c
{
    public static readonly <>c <>9 = new <>c();

    public static Func<int, int> <>9__0_0;

    internal int <M>b__0_0(int x)
    {
        return x + 1;
    }
}

public void M()
{
    new int[0].Select(<>c.<>9__0_0 ?? (<>c.<>9__0_0 = <>c.<>9.<M>b__0_0));
}

```
It could be?
```csharp
private sealed class <>c
{
    public static readonly Func<int, int> <>9__0_0 = new <>c().<M>b__0_0;

    internal int <M>b__0_0(int x)
    {
        return x + 1;
    }
}

public void M()
{
    new int[0].Select(<>c.<>9__0_0);
}
```

**Comment by benaadams** [comment]
Though I suppose its an issue with multiple lambdas as that would cause early creation of all of them; rather than lazy init?

```csharp
public class C {
    public void M() {
        new int[0].Select(x => x + 1);
        new int[0].Select(x => x + 2);
    }
}
```
```csharp
private sealed class <>c
{
    public static readonly <>c <>9 = new <>c();

    public static Func<int, int> <>9__0_0;

    public static Func<int, int> <>9__0_1;

    internal int <M>b__0_0(int x)
    {
        return x + 1;
    }

    internal int <M>b__0_1(int x)
    {
        return x + 2;
    }
}

public void M()
{
    new int[0].Select(<>c.<>9__0_0 ?? (<>c.<>9__0_0 = <>c.<>9.<M>b__0_0));
    new int[0].Select(<>c.<>9__0_1 ?? (<>c.<>9__0_1 = <>c.<>9.<M>b__0_1));
}
```
vs
```csharp
private sealed class <>c
{
    public static readonly <>c <>9 = new <>c();

    public static readonly Func<int, int> <>9__0_0 = <>c.<>9.<M>b__0_0;

    public static readonly Func<int, int> <>9__0_1 = <>c.<>9.<M>b__0_1;

    internal int <M>b__0_0(int x)
    {
        return x + 1;
    }

    internal int <M>b__0_1(int x)
    {
        return x + 2;
    }
}

public void M()
{
    new int[0].Select(<>c.<>9__0_0);
    new int[0].Select(<>c.<>9__0_1);
}
```

**Comment by GSPP** [comment]
Yes, all lambdas would be created. I suppose that was deemed an issue. I'm thinking of the `Enumerable` class here as an example. The compiler could generate one class per lambda although that surely has other overheads. The lambdas could be batched into N (maybe 10) per static class. That would bound the overhead. For some reason that seems too elaborate to me.

**Comment by jaredpar** [comment]
@davidwrighton can you comment on whether the `null` passing trick is legal according to CLR? I'm sure it works on desktop in a few specific cases but I'm unsure if it's a generally applicable solution. 

@GSPP 

>  It would be faster to initialize the cached delegated in a beforefieldinit static constructor rather then checking it at each use. Probably, this has already been discussed but I'm mentioning it at this opportunity to make sure the point is noticed.

Why do you feel this would be faster? Static constructors have a number of downsides associated with them that cause performance penalties elsewhere.

**Comment by benaadams** [comment]
> > It would be faster to initialize the cached delegated in a beforefieldinit static constructor rather then checking it at each use. Probably, this has already been discussed but I'm mentioning it at this opportunity to make sure the point is noticed.

> Why do you feel this would be faster? Static constructors have a number of downsides associated with them that cause performance penalties elsewhere.

Inline static initalization `.beforefieldinit` rather than an explicit static .ctor only cause a perf issue in the first method that calls them (for Jit rather than AOT); this initalization penalty is then removed if its a hot-path method with tiered jitting (to enabled by default in Core 2.2 https://github.com/dotnet/coreclr/issues/18973)

It also then makes the use more inlinable. However... there were concerns with this before https://github.com/dotnet/roslyn/issues/13624 with response https://github.com/dotnet/roslyn/issues/13624#issuecomment-285493478

**Comment by GSPP** [comment]
@jaredpar what performance penalties are there? As I understand it the JIT runs the cctor before jitting. Then, field accesses compile into a single `mov` and `readonly static` fields are constant from the perspective of the JIT (leading for example to `int` values being burned into the source code).

But @benaadams pointed to an issue where this solution was discarded for understandable reasons.

**Comment by svick** [comment]
@jaredpar 

> Static constructors have a number of downsides associated with them that cause performance penalties elsewhere.

At least in this specific case, the generated class already has a `beforefieldinit` static constructor to initialize the field that contains the dummy instance. So this change wouldn't be adding a new static constructor, just adding to what it does.

**Comment by MichalStrehovsky** [comment]
This is not safe. The runtime expects to be able to access the `this`. E.g. shared generic code assumes it can obtain the generic context from the `this`. So e.g. if we have:

```csharp
public class C {
    public void M<T>() {
        new object[] { new object()}.Select(x => x is T);
    }
}
```

This would crash with a null this for `M<string>` because to find the T at runtime, the runtime is going to look at `this`.

It would not crash for `M<int>` because of how generic sharing works. It's sketchy territory.

IL Linker also considers this an optimization opportunity - if a type is never allocated but instance methods are called on it, illink has to leave the methods in (because they're called), but it will stub them out because practically you're going to reach a NullReferenceException before the body is executed. This is a pretty powerful optimization opportunity and results in 5+% size savings.

**Comment by jaredpar** [comment]
Closing as the optimization isn't runtime safe.
