### ISSUE TITLE
Introduce local for 'this' is not very useful

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#28730]
**Version Used**: VS 15.7

**Steps to Reproduce**:

1. Move caret to `this` and press `Ctrl+.`

```C#
	sealed class C {
		readonly string s;
		public C(string s) {
			this.s = s;
		}
	}
```

**Expected Behavior**:

Roslyn either doesn't offer to introduce a local for 'this' or it moves this refactoring to the bottom of the list.

**Actual Behavior**:

Roslyn thinks the most useful refactoring is storing 'this' in a local.

Even if it's a struct, it's not very useful to show this refactoring, especially if it's a constructor.

**Comment by Neme12** [comment]
Why is this a bug?

**Comment by dpoeschl** [comment]
Design Meeting Notes:

Since `s` is `readonly`, it will cause an error. But more broadly, consider the following (explained in the comments).

```C#
sealed class C
{
    readonly string s;
    string t;
    C car = null;

    public C(string s)
    {
        this.s = s; // Introduce Local offered anywhere on `this`, with or without selection
        car.t = s; // Introduce Local only offered on `car` when it is selected 
    }
}
```

Let's treat `this` like `car`.

**Comment by dpoeschl** [comment]
@Neme12 is there a good use case for this that we've missed?
