### ISSUE TITLE
Optimization of exception handling in async methods

### ISSUE THREAD

**Issue by Kirill-Maurin** [dotnet/roslyn#28759]
Current implementation of async methods works like this code:
```cs
TaskLike<T> Method()
{
    try
    {
        return TaskLike.FromResult(Body);
    }
    catch (Exception e)
    {
        return TaskLike.FromException(e);
    }
}
```
1. Any exception is caught and wrapped in TaskLike.
Current awaiters throw exception when TaskLike contains exception or canceled.
1. This is extremely inefficient. An exception is thrown at each nesting level of the asynchronous method. 
This applies not only to exceptional situations, but also simple task cancellations.
1. As a solution, I use special awaiters and extension methods
```cs
public readonly struct TaskAwaiter<T> : IResultAwaiter<T>
        {
            public TaskAwaiter(Task<T> task) => _task = task;

            public void OnCompleted(Action continuation) => Inner.OnCompleted(continuation);

            public void UnsafeOnCompleted(Action continuation) => Inner.UnsafeOnCompleted(continuation);

            public bool IsCompleted => _task.IsCompleted;

            public Result<T> GetResult() 
                => _task.TryGetException(out var e) ? e.ToFail<T>() 
                : _task.IsCanceled ? new TaskCanceledException().ToFail<T>()
                : _task.Result.ToSuccess();

            private ConfiguredTaskAwaitable<T>.ConfiguredTaskAwaiter Inner => _task.ConfigureAwait(false).GetAwaiter();

            private readonly Task<T> _task;
        }
```
* This allows you to process exceptions (and cancellations) thousands times faster.
https://github.com/Kirill-Maurin/FluentHelium/blob/master/FluentHelium.Benchmarks/Program.cs
* But it forces you to use LINQ-like code instead sync-like. This either looks worse, or slower than normal code without exceptions.
* I think that the compiler and standard awaiters could take this job on themselves

**Comment by svick** [comment]
> I think that the compiler and standard awaiters could take this job on themselves

How do you suggest that would be done? What are the specific changes that you are proposing?

Would this change affect stack traces?

**Comment by jaredpar** [comment]
Want to echo @svick here on how you're proposing this be done.

**Comment by sharwell** [comment]
Duplicate of #65863
