### ISSUE TITLE
VS unresponsive during FAR

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#2876]

**Comment by tmat** [comment]
ETL trace and memory dump: %internal_share%\public\tomat\Bugs\2876

**Comment by tmat** [comment]
@pharring FYI

**Comment by Pilchie** [comment]
Can you take a look at the ETL and see what's up here?  We should have a cancellable ThreadedWaitDialog up.

**Comment by rchande** [comment]
@tmat According to the dump, we have the wait dialog up and it's showing some animation. Do you have any repro guidance?

**Comment by tmat** [comment]
@rchande Not really, I was just working in Roslyn.sln looking for various public APIs in the compiler related to scripting. I don't think I saw any dialog. The UI was frozen.

**Comment by rchande** [comment]
@heejaechang in @tmat's trace/dump, it looks like FAR and Solution Crawler are both serializing tons of trees, so he spends like 80% of the trace time in the GC. How hard do you think it would be to suspend Solution Crawler during FAR?

**Comment by rchande** [comment]
HeeJae is working on something that fixes this. @heejaechang can you close this once your change is in stabilization?

**Comment by heejaechang** [comment]
#2986

it should be fixed if root cause was this

**Comment by heejaechang** [comment]
done
