### ISSUE TITLE
Generate local not available inside expression body

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#28762]
Generate local 'foo' is offered here:
```c#
using System;

class C
{
    void M()
    {
        Console.WriteLine(foo);
    }
}
```

but not here:
```c#
using System;

class C
{
    void M() => Console.WriteLine(foo);
}
```

The code fix should to be so kind and create a block body for me.

**Comment by Neme12** [comment]
A lot of this code could be shared with introduce local.

This code fix lags behind in other areas too. For example it can't create a block in an embedded statement, whereas "introduce local" does do that.

**Comment by Neme12** [comment]
It also doesn't know how to insert into a switch case:
```c#
using System;

class C
{
    void M()
    {
        switch (true)
        {
            case true:
                Console.WriteLine(foo);
                break;
        }
    }
}
```
results in
```c#
using System;

class C
{
    void M()
    {
        var foo = false;
        switch (true)
        {
            case true:
                Console.WriteLine(foo);
                break;
        }
    }
}
```

In my opinion this should all behave like "introduce local", which generates the local as close to the expression as possible.

**Comment by CyrusNajmabadi** [comment]
@Neme12 would you like to take this and update these fixers to share more code?

**Comment by Neme12** [comment]
I'm probably not going to be able to do this any time soon.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback about this topic and lack of movement here.
