### ISSUE TITLE
Roslyn no longer warning about missing .ConfigureAwait when awaiting expression.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#28764]
Not sure when this stopped worked.  However, i just noticed it.  Has there been any change to the analyzers we use for developing Roslyn itself?  Was this change intentional?

**Comment by jaredpar** [comment]
Duping off of https://github.com/dotnet/roslyn/issues/28985

Sorry lost track of this but got reminded when @333fred filed his bug yesterday. He and I tracked it down this morning and assigned it out to be fixed.
