### ISSUE TITLE
Create an analyzer for unnecessary using directives

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#28773]
**Version Used**: 15.8 Preview 3

Currently unnecessary using directives are reported by the compiler as CS8019. By design, these diagnostics do not filter out generated files and do not consider global suppressions. While this behavior ensures unnecessary using directives are correctly faded in all source files (including generated sources), they prevent the diagnostic from ever being used at a severity higher than Hidden.

A new diagnostic analyzer needs to be created which exposes Unnecessary Using Directive analysis for use in builds.

* The new analyzer should read all CS8019 diagnostics for the current file, and report a new IDE diagnostic for them
* The new analyzer should be configured to not show diagnostics in generated code (this is the default for our code style analyzers)

📝 I set out to implement this once in the past, but encountered a design subtlety that I need to take for a design review. Currently, the code fix to remove unnecessary using directives appears if the caret is placed on *any using directive*. I had modified this to only show the code fix if the caret was placed on *an unnecessary using directive*. While the implementation was notably simplified, this is a clear change in behavior that needs to go for a design review.

**Comment by CyrusNajmabadi** [comment]
>  I had modified this to only show the code fix if the caret was placed on an unnecessary using directive. While the implementation was notably simplified, this is a clear change in behavior that needs to go for a design review.

Yup.  I very much like the current behavior.  👍  on not changing it.   Note: it seems like it would be pretty simple to maintain the existing behavior.  The start and end of the usings-range is very easy to figure out.  Why would we not just put the trigger span on that entire span?

**Comment by sharwell** [comment]
> Currently, the code fix to remove unnecessary using directives appears if the caret is placed on any using directive.

During a design review today, the team confirmed that this behavior is desired and should be preserved.

**Comment by MSThug** [comment]
Can someone explain what the "fix" was here? I still get these warnings on my latest projects where the generated code has // <auto-generated>.

**Comment by mkamoski** [comment]
This is still a bug in Visual Studio 2019 16.4.2 as of now.

**Comment by sharwell** [comment]
@MSThug @mkamoski I am not aware of a bug currently in this space. If you are experiencing a problem with this diagnostic, can you file a new issue with the details so we can investigate it?

**Comment by YetAnotherCodeMaker** [comment]
On my point of view, if it is not a bug, it is at least a problem.
Since years, people are asking to exclude generated files from code analysis, not only CS8019. If I try to google this case, I always fall on GitHub, with multiple duplicates, resolutions, merges, and so on (I'm probably to stupid to follow it on GitHub).
In a "small" solution with around 20 projects only, I have 725 occurrences of CS8019, only one in my own code, with nearly no way to easily retrieve it, so this rule becomes totally inapplicable (and it's not the only one).
So, maybe it is not a bug, maybe it is not the good place to ask for that, but my only point here is "when will I be able to correctly check the warnings which apply to my code among the hundreds due to auto-generated code"?

**Comment by sharwell** [comment]
@YetAnotherCodeMaker CS8019 is reported in all files. IDE0005 is the same diagnostic, but it does not get reported in generated files.

**Comment by azabluda** [comment]
@sharwell Is IDE0005 reported only in IDE? If yes, then what would you recommend to use e.g. on the build server?

**Comment by sharwell** [comment]
Currently IDE0005 is only reported in the IDE. I'll see about including this one in the code style layer (where IDE0055 already is and works for command line builds) for the 16.6 release.

**Comment by mkamoski** [comment]
> @MSThug @mkamoski I am not aware of a bug currently in this space. If you are experiencing a problem with this diagnostic, can you file a new issue with the details so we can investigate it?

@sharwell - I am sorry but this seems to be no longer an issue for me, in fact (I admit) I may have been mistaken altogether, I apologize if I misreported it, and for now, I am all-set as-is, and furthermore I still need to move to VS 2019 16.4.3 as generally I do NOT want to report anything unless I am on the latest-and-greatest, etc. Thanks. -- Mark Kamoski.

**Comment by sharwell** [comment]
@mkamoski It's no problem. I get mixed up on things myself all the time!

**Comment by prjm** [comment]
After reading a lot of closed github issues, I'm still not able to suppress the CS8019 warnings from generated files. I add the following line in the root editor config which is located in the solution folder:

    [{**/obj/**,**/bin/**}]
    dotnet_analyzer_diagnostic.severity = none 

I'm getting the following warnings:

![CS81019](https://user-images.githubusercontent.com/11259216/113770750-d600f000-9722-11eb-9993-9f6c3e47f427.PNG)

What can I do in this case (using Visual Studio 16.9.3)? I am not seeing this warnings when I use msbuild.

**Comment by sharwell** [comment]
@prjm CS8019 does not treat generated files any differently from non-generated files. The severity of CS8019 should always be set to Hidden (the default); any other option will make it impossible to build the project without warnings.

**Comment by prjm** [comment]
@sharwell Thank you for your fast reply. After setting the severity of the rule back to hidden, the warnings are gone. From an end user perspective it is confusing that I can configure the severity of a rule, which I shouldn't touch at all. On the other side, I have to admit that i've simply set the severity of all rules via a ruleset file to warning via the ruleset editor, without looking up the details of every rule.

**Comment by sharwell** [comment]
@cz3rwo What you are observing is the expected behavior. Diagnostic CS8019 does not filter out generated code, so if you set its severity to warning or error you will be expected to ensure all generated code contains only the necessary using directives. If you only want to report warnings for non-generated code, set IDE0005 to warning instead of CS8019.
