### ISSUE TITLE
"Add parameters" to constructor duplicates parameter

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#28775]
```c#
class C
{
    int i;
    int k;
    int j;

    public C(int i, int j)
    {
        this.i = i;
        this.j = j;
    }
}
```

Select all 3 lines with `i`, `j` and `k` fields and then Add parameters to C(int, int)
![image](https://user-images.githubusercontent.com/11444821/43049713-afe35c3c-8dfc-11e8-8c95-ee492eb8aee1.png)

The result is bad:
```c#
class C
{
    int i;
    int k;
    int j;

    public C(int i, int j, int j)
    {
        this.i = i;
        this.j = j;
        this.j = j;
    }
}
```

**Comment by chborl** [comment]
@CyrusNajmabadi , how should the Add parameters feature work?  Do you select only the field you want to add to the constructor or do you select all of the fields that you want to be in the constructor?

**Comment by CyrusNajmabadi** [comment]
@chborl What i think would be *best* would be to take the selected fields, and try to match them up to parameters (using name and type.  We have code for this scattered over several features, potentially even in this one.  Then, we determine which parameters are *missing*, and we then try to figure out where in the parameter list the missing field should go.

Note: several features already behave this way.  For example, if you have:

```c#
class C
{
    int i;
    int j;

    public C(int i, int j)
    {
        this.i = i;
        this.j = j;
    }
}

// and you add parameter like this:

class C
{
    int i;
    int j;

    public C(int i, int newParam, int j)
    {
        this.i = i;
        this.j = j;
    }
}

// we will generate

class C
{
    int i;
    int newParam;
    int j;

    public C(int i, int newParam, int j)
    {
        this.i = i;
        this.newParam = newParam;
        this.j = j;
    }
}
```

i.e. "initialize from parameter" knows how to find the 'right place' for both the field *and* the `this.newParam = ...` statement.

We effectively want similar logic here.  We need match up existing parameter-to-field pairs, then use the position of unmatched fields to determine where to put the new parameters and parameter-initializatin-statements.
