### ISSUE TITLE
Introduce local in Select produces invalid code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28771]
If I highlight code in the IEnumerable.Select extension and try to introduce a local using &quot;Ctrl-.&quot;, it produces code that doesn't compile.

I might be wrong, but I don't thing we can even define a local in a Select, so the analyzer should not be showing up.

![image](https://user-images.githubusercontent.com/12449387/43043768-e3bafaaa-8d4e-11e8-96ad-02ca0d48c474.png)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/296716/introduce-local-in-select-produces-invalid-code.html
VSTS ticketId: 651027_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
