### ISSUE TITLE
Downgrade or install the same major version+edition of Visual Studio side by side 

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#28772]
Currently, we can't downgrade or install the same major version+edition of Visual Studio side by side are there any plans for this?

The reason I'm asking this is currently I want to contribute and I'm on version 15.7.5 and in the contribution document you make the following requirement: 

* Ensure Visual Studio is on Version "15.7" or greater

Apparently I should be on the safe side and it should all just work but in practice it [fails](https://github.com/dotnet/roslyn/issues/28758) so the "greater" part is not guaranteed or enforced, it's really better to specify a specific version and allow us to have multiple versions installed or at least downgrade, maybe both, I don't know.

Besides the failure I'm getting I'm sure different people would want this feature for different reasons.

p.s. Please don't tell me to post this on UserVoice or the clunky Visual Studio feedback tool because I won't.

**Update:** Just for clarification, the reason I made this issue is because I don't really know what is broken, Roslyn or VS. probably the former but I just threw it here because again don't know what's wrong.

**Comment by Neme12** [comment]
The Visual Studio feedback system isn't "clunky". The majority (if not all) of bug reports I posted there have been fixed. There's probably a bigger chance of your problem getting looked at there than on GitHub.

**Comment by eyalsk** [comment]
@Neme12 Is clunky and I reported it before, not gonna have this discussion here.

**Comment by eyalsk** [comment]
I've discussed this on Gitter with @Neme12. I'll try to install the preview and see how it goes because like @Neme12 I think that my failure has nothing to do with VS but with Roslyn so I'm closing this.
