### ISSUE TITLE
Selection to trigger 'Generate constructor' is finicky 

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#28774]
VS 15.8 Preview 4

When selecting lines, I always use vertical motions of the mouse since it's easier and takes the previous newline with it which is 99% of the time what I want. If I'm typing, I'll use <kbd>Shift</kbd>+<kbd>↑</kbd> for each line I want to select which does the same thing.

However, this type of selection never triggers the expected code actions. This is what it looks like. First I do the selection that I'm used to, and no refactoring icon shows up (<kbd>Ctrl</kbd>+<kbd>.</kbd> does nothing, which is what I actually use). Then, I do the slower selection to demonstrate the refactoring options that I'd expect to appear the first time:

![sensitive selection](https://user-images.githubusercontent.com/8040367/43049255-8a540bc2-8dc2-11e8-88e2-86814474b930.gif)

**Comment by CyrusNajmabadi** [comment]
To fix ths, update ISyntaxFactsService.GetSelectedMembers.

Note: we should do this for C# and VB.

**Comment by jnm2** [comment]
Fixed for both languages in https://github.com/dotnet/roslyn/pull/28779.
