### ISSUE TITLE
Perf improvement, make AbstractObjectBrowserLibraryManager constructor lazier

### ISSUE THREAD

**Issue by JieCarolHu** [dotnet/roslyn#28788]
Copied from VSO: https://devdiv.visualstudio.com/DevDiv/Default/_workitems/edit/639095

**Comment by sharwell** [comment]
@JieCarolHu Can you provide some details about how this was found/measured?

**Comment by jasonmalinowski** [comment]
@sharwell as a part of us looking at solution load times, I look at a CPU time trace of SetSite and saw where time was going. For this one, I saw we were doing some stuff eagerly that could easily be moved lazy, and filed it.
