### ISSUE TITLE
Rename method changes meaning of program with no warning

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#28785]
In the following program, if you rename `var1` to `var`, it completely changes the meaning of the body of `M`, but there is nothing to warn you about that.

This is probably low priority. One doesn't normally name methods to start with a lowercase letter.

**Comment by gafter** [comment]
"The following program" is

``` c#
using System;

class A
{
    static int x, y;
    void M()
    {
        // try renaming var1 to var; it completely changes the meaning of the program!
        var1(x, y) = this;
    }

    static A _var;
    ref A var1(int x, int y)
    {
        return ref _var;
    }

    public void Deconstruct(out int X, out int Y) => (X, Y) = (x, y);
}
```

**Comment by CyrusNajmabadi** [comment]
Yes.  The priority of this would be extremely low.  It's just not a realistic user scenario to even get into this case in the first place :)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback about this being an issue.
