### ISSUE TITLE
Typing fast with "Show completion list after a character is deleted" option [NEEDS BACKSPACE]

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#28796]
**Steps to Reproduce**:
This is reproducible with the current (old) completion.

1. Enable "Show completion list after a character is deleted" in options
2.  Debug 
```
    class Program
    {
        static void Main(string[] args)
        {
int[] arr = new int[4];
        } // set breakpoint here
      }
```
3. Set the breakpoint
4. In the watch window type `arr[0]`
5. Set the caret just after '0'
6. Type **very fast**: Backspace 1 Enter (customer mentioned just fast but I could reproduce it typing extremely fast in my environment. Typing normally leads to the expected behavior. My speed of typing allows me to get the issue 1 time out of 10 but the customer says he can get it regularly with a fair fast speed of typing.

**Expected Behavior**:
arr[1] in the watch window

**Actual Behavior**:
enter created a new line in the watch variable. Then you see just `]` in the watch window. Then if hitting enter once again you get `arr[1`

We should 
1. Verify that this is not reproducible with the new async completion.
2. Try to reproduce it more regularly and consider creating a test covering this.

**Comment by ivanbasov** [comment]
depends on #27441. Then, we will need to make a validation.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
