### ISSUE TITLE
VS Intellisense usability - Deprioritize the nullary constructor for structs if other constructors exist.

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#28795]
**Version Used**: 

Latest (it's been around forever)

**Steps to Reproduce**:

1. Author a struct with an actual constructor that takes parameters.
2. Write "new MyStruct("
3. Hit space to request auto-completes.

**Actual Behavior**:

If I explicitly declared a constructor with parameters, one can reasonably infer that it's because I don't particularly like the default nullary constructor that the CLR wishes on us for all structs.

Yet, the nullary constructor is always the first one that Intellisense offers me! This is almost never what I want.

**Expected Behavior**:

Make the nullary constructor for structs the last choice, not the first.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
