### ISSUE TITLE
With "Full Solution Analysis" turned on, certain syntax errors get duplicated

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#28808]
**Version Used**: 
Version 15.8.0 Preview 5.0 [27922.0.d15.8]

**Steps to Reproduce**:

1. Open attached solution ([Solution.zip](https://github.com/dotnet/roslyn/files/2223463/Solution.zip))
2. Close all documents
3. Turn on Full Solution Analysis
3. Right-click on Solution and choose Rebuild
4. In Error List, choose "IntelliSense only"

**Expected Behavior**:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1022	Type or namespace definition, or end-of-file expected	ClassLibrary1	C:\Users\davkean\Source\Repos\ConsoleApp167\ClassLibrary1\Class1.cs	10	Active

**Actual Behavior**:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1022	Type or namespace definition, or end-of-file expected	ClassLibrary1	C:\Users\davkean\Source\Repos\ConsoleApp167\ClassLibrary1\Class1.cs	10	Active
Error	CS1022	Type or namespace definition, or end-of-file expected	ClassLibrary1	C:\Users\davkean\Source\Repos\ConsoleApp167\ClassLibrary1\Class1.cs	10	Active

**Comment by davkean** [comment]
This isn't just syntax errors:

``` C#
    class Program
    {
        static int Main(string[] args)
        {
            return default;
        }
    }
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8107	Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.	ConsoleApp207	C:\Users\davkean\Source\Repos\ConsoleApp207\ConsoleApp207\Program.cs	13	Active
Error	CS8107	Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.	ConsoleApp207	C:\Users\davkean\Source\Repos\ConsoleApp207\ConsoleApp207\Program.cs	13	Active

```

**Comment by davkean** [comment]
tag @heejaechang

**Comment by davkean** [comment]
Attached is a project that repros this:

[CPS.zip](https://github.com/dotnet/roslyn/files/2351057/CPS.zip)

**Comment by CyrusNajmabadi** [comment]
I dont' repro this.  System has been heavily refactored so it's likely long gone (and we haven't heard from others).
