### ISSUE TITLE
VB: Changing "Show outlining for code level constructs" doesn't work properly when files are closed.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#28802]
**Version Used**: 

Visual Studio Community 2017 v15.5.6

**Steps to Reproduce**:

First the setting in question is under `Tools > Options > Text Editor > Basic > Advanced > Outlining`:

![vs_outlining_broken_codelevel_1](https://user-images.githubusercontent.com/20465797/43110074-ac69b7c6-8ef2-11e8-9796-e7fafe3d42bd.png)

Make sure it is ticked as shown above, the paste the following code into a file called `CodeFoldingTest.vb` (the file name doesn't really matter, it is just for reference in this issue):

```vb
Public Module CodeFoldingTest
  Public Sub foo()
    If True Then
      Try
        Do

        Loop
      Catch ex As Exception

      End Try
    End If
  End Sub
End Module
```

Now with `outlining for code level constructs` enabled you get the little plus/minus icons on the left so you can outline the `If...End If`, `Try...End Try` and `Do...Loop` statements:

![vs_outlining_broken_codelevel_2](https://user-images.githubusercontent.com/20465797/43110258-9c7abca6-8ef3-11e8-8808-e1f2699f820f.png)

Now go ahead and collapse the `Do Loop` statement so you have:

![vs_outlining_broken_codelevel_3](https://user-images.githubusercontent.com/20465797/43110335-1397f362-8ef4-11e8-96c1-59031566b053.png)

Then collapse the `Try...End Try` statement so you have:

![vs_outlining_broken_codelevel_4](https://user-images.githubusercontent.com/20465797/43110343-1f690690-8ef4-11e8-841a-f79cd8dc3c22.png)

Then finally collapse the `If...End If` statement so you have:

![vs_outlining_broken_codelevel_5](https://user-images.githubusercontent.com/20465797/43110359-363cf2c8-8ef4-11e8-8ff7-33b3d1541893.png)

Everything so far works as expected. Now while still viewing the `CodeFoldingTest.vb` in the editor, go to settings and UNTICK `outlining for code level constructs`. **The editor CORRECTLY AND IMMEDIATELY expands the collapsed statements leaving a plus/minus only for the `Sub...End Sub` block as well as the `Module...End Module` block**:

![vs_outlining_broken_codelevel_6](https://user-images.githubusercontent.com/20465797/43110463-c84ed1e0-8ef4-11e8-99cf-1629229d1a4d.png)

Again while still viewing the `CodeFoldingTest.vb` in the editor, go to settings and TICK `outlining for code level constructs`. **The editor CORRECTLY AND IMMEDIATELY restores the plus/minus icons so you can collapse the statements again**:

![vs_outlining_broken_codelevel_2](https://user-images.githubusercontent.com/20465797/43110258-9c7abca6-8ef3-11e8-8808-e1f2699f820f.png)

So go ahead and collapse, the `Do...Loop` statement, then the `Try...End Try` statement, then the `If...End If` statement. Everything is fine so far and you end up with:

![vs_outlining_broken_codelevel_5](https://user-images.githubusercontent.com/20465797/43110359-363cf2c8-8ef4-11e8-8ff7-33b3d1541893.png)

**NOW THE CRITICAL STEP: CLOSE THE FILE `CodeFoldingTest.vb` AND THEN GO TO SETTINGS AND UNTICK `outlining for code level constructs`**. At this point you've disabled outlining for code level constructs, however **WHEN YOU REOPEN THE FILE, `OUTLINING FOR CODE LEVEL CONSTRUCTS` IS STILL DONE AND IT RENDERS INCORRECTLY**. First you see this (the `If...End If` block is collapsed with no preview of its text):

![vs_outlining_broken_codelevel_7](https://user-images.githubusercontent.com/20465797/43110741-5dca7886-8ef6-11e8-9420-4e664ba7c7c2.png)

When you expand the outline, you see this (the `Try...End Try` block is still collapsed with no preview of its text):

![vs_outlining_broken_codelevel_8](https://user-images.githubusercontent.com/20465797/43110825-cb3893b2-8ef6-11e8-96d4-b35d9a71dace.png)

And when you expand the outline, you see this (the `Do...Loop` block is still collapsed with no preview of its text):

![vs_outlining_broken_codelevel_9](https://user-images.githubusercontent.com/20465797/43110897-1ba9774e-8ef7-11e8-8369-645b7bb7bafe.png)

Finally you expand the last outline, you see this (**all blocks have been expanded and can STILL be collapsed again even though we've disabled outlining for code level constructs**):

![vs_outlining_broken_codelevel_2](https://user-images.githubusercontent.com/20465797/43110258-9c7abca6-8ef3-11e8-8808-e1f2699f820f.png)

**Expected Behavior**:

The editor is correctly able to respond to changes in the  `outlining for code level constructs` setting as long as a file is currently open when the setting is changed. **It should also honour that setting when OPENING files** (I know the editor has a way of remembering how you outlined a particular file and restores that configuration when you reopen the file. I think that code needs to be enhanced to account for the fact that the outlining levels may have changed between the file being closed and being reopened possibly days or weeks later).

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback and that we're not going to be changing these vb experiences.
