### ISSUE TITLE
Microsoft.VisualStudio.LanguageServices.Implementation.dll does not have symbols published to the internal symbol server

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#28800]
This dll does not have symbols published to the internal symbol server:

Microsoft.VisualStudio.LanguageServices.Implementation.dll	Microsoft.VisualStudio.LanguageServices.Implementation.dll	c:\program files (x86)\microsoft visual studio\15.9stg\enterprise\common7\ide\commonextensions\microsoft\managedlanguages\vbcsharp\languageservices\Microsoft.VisualStudio.LanguageServices.Implementation.dll	Yes	No	Cannot find or open the PDB file.		204	2.09.0.63115	<Unknown>	269F0000-26A4A000	[379112] devenv.exe	[1] DefaultDomain	

These other dlls *do have* symbols:

Microsoft.VisualStudio.LanguageServices.CSharp.dll
Microsoft.VisualStudio.LanguageServices.dll	
Microsoft.VisualStudio.LanguageServices.SolutionExplorer.dll

**Comment by jinujoseph** [comment]
cc @tmat , @Shyam-Gupta @jasonmalinowski

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski do you know what would cause this?  what should we do here?

**Comment by jasonmalinowski** [comment]
The bug is too old to know what happened, but @tmat recently did work to publish in the newer system so we can call this closed.
