### ISSUE TITLE
code completion: constructor to assign a member does not show argument candidates

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#28806]
There is a code completion bug that appears to happen when 1) we try to use constructor and 2) the assignee is field or property, not local variable.

Repro code fragment is like this:

```
public class C
{
    Uri uri;

    public void M ()
    {
        uri = new Uri  // <<<=== continue from here
    }
}
```

![image](https://user-images.githubusercontent.com/53929/43043366-4c50b914-8dcd-11e8-8f52-01345252f5b2.png)

**Comment by mkrueger** [comment]
See https://github.com/mono/monodevelop/issues/5477

**Comment by CyrusNajmabadi** [comment]
Sorry, i'm not quite understanding what the actual bug is.  What is the expected behavior that is wanted here, and what are the precise repro steps.  I'm not sure what is meant by "continue from here."
