### ISSUE TITLE
Assert that range/index expressions can be used in expression trees

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#28828]
For range (`1..2`) and index (`^1`) expressions, need to investigate if they're convertible correctly to LINQ expression trees, specially when either or both operands are lifted.
Tests should be added accourdingly.

**Comment by OmarTawfik** [comment]
@jaredpar another one here :)

**Comment by agocke** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/42011
