### ISSUE TITLE
IDE0019 fix leads to CS0165

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28821]
class Program
{
    static void Foo(System.Activator bar)
    {
    }

    static void Main(string[] args)
    {
        var a = new object();
        var b = a as System.Activator;
        if ((b == null) &amp;&amp; false)
        {
        }
        else
        {
            Foo(b);
        }
    }
}

VS suggests to use pattern matching with variable b. When applying the fix, the compiler will complain that the local variable b is unassigned where Foo is called.

Work around:
Removing the superfluous braces at the if statement suffices to let IDE0019 disappear.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/286146/ide0019-fix-leads-to-cs0165.html
VSTS ticketId: 642519_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@alrz Do you have an idea why your definite-analysis work doesn't pick up this case?

**Comment by alrz** [comment]
@CyrusNajmabadi Couldn't repro with my latest change (#26097). Added a regression test.
