### ISSUE TITLE
Go to implementation (Ctrl+F12) is broken for  interface async methods

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28827]
I defined an interface with async methods in a .Net Standard 2.0 project. And two implementations in two .Net Core 2.1 projects.  
When I press Ctrl+F12 over the interface name, the  Visua Studio 'implementations' window displays the two implementations.
But when I press Ctrl+F12 over a method whose implementation has async keyword method, it doesn't find any implementation, presenting a dialog into saying &quot;This symbol has no implementations&quot;.
The expected result is that the 'implementations' window should present the two implementations of the method.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/295266/go-to-implementation-ctrlf12-is-broken-for-interfa.html
VSTS ticketId: 649802_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by paulovila** [comment]
Hi @jinujoseph is there any progress with this bug?

**Comment by jinujoseph** [comment]
@paulovila not yet , it's in our list todo

**Comment by paulovila** [comment]
Any time this year?

**Comment by CyrusNajmabadi** [comment]
@paulovila Would you be interested in contributing a fix here?

**Comment by paulovila** [comment]
Definitely, I'd be glad to help, my email is paulovila@live.com

**Comment by CyrusNajmabadi** [comment]
Great!  I'd recommend starting with: https://github.com/dotnet/roslyn/wiki/Building-Testing-and-Debugging

When you've gotten to a buildable state, let me know.  Thanks!

**Comment by ryzngard** [comment]
The problem comes in because the types and namespaces are equivalent up through the global namespace, but the `ContainingSymbol` for each global namespace is different. One is `NetModule System.Runtime.dll` and one is `NetModule netstandard.dll`  when calling [AreEquivalentWorker](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Shared/Utilities/SymbolEquivalenceComparer.EquivalenceVisitor.cs,158).
