### ISSUE TITLE
Issue with delegate constraint not compiling

### ISSUE THREAD

**Issue by taori** [dotnet/roslyn#28835]
C# 7.3

**Steps to Reproduce**:

	public class MyClass<TDelegate> : IMyInterface<TDelegate> where TDelegate : Delegate
	{
            // COMPILER COMPLAINS HERE about OnEvent needing to be a Delegate, which it kind of has to be, because of the constraint?
		private event TDelegate OnEvent;

		/// <inheritdoc />
		public void Add(TDelegate handler)
		{
			throw new NotImplementedException();
		}

		/// <inheritdoc />
		public void Remove(TDelegate handler)
		{
			throw new NotImplementedException();
		}
	}

	public interface IMyInterface<TDelegate> where TDelegate : Delegate
	{
		void Add(TDelegate handler);
		void Remove(TDelegate handler);
	}

**Expected Behavior**:
I would expect this to compile, unless i am using it wrong.

**Actual Behavior**:
It does not compile.

The project in question is configured as Crosscompile net40/net45/nestandard1.1 if that makes any difference (which i don't think it does anymore)

**Comment by CyrusNajmabadi** [comment]
> I would expect this to compile, unless i am using it wrong.

Unfortunately, in this case, you are not using it correctly.  The constraint ```where T : Delegate``` means ```T is a System.Delegate (or one of its subtypes)```.  However, you cannot use ```System.Delegate``` iteself as the type of an event.   I.e. you can't write ```public event Delegate E``` (if you try, you'll get the same error listed here).  

Unfortunately, there is no way to say "i want T to be a *subtype* of System.Delegate".

**Comment by taori** [comment]
That seems like a usability hole regarding how useful the Delegate constraint is, doesn't it? At least to me it does not seem to be that much of an unlikely scenario when working with this constraint.

Having to know implementations of the service (in order to know the delegate type) completely obliterates the usefulness of the constraint to me.

**Comment by gafter** [comment]
@taori I agree that this constraint is not useful for your scenario. Nevertheless, the compiler is behaving as specified. If you think the language should change, please make a proposal at the csharplang repo.

**Comment by CyrusNajmabadi** [comment]
> That seems like a usability hole regarding how useful the Delegate constraint is, doesn't it? 

Well, it's not really "the Delegate constraint".  It's really just a 'class-type' constraint as specified here: https://github.com/dotnet/csharplang/blob/master/spec/classes.md#type-parameter-constraints

System.Delegate is simply a class, and like any other class (modulo some exceptions), you are allowed to constrain to it.

It does sounds like you'd like something like a "a constraint that specifies that it is a subtype of Delegate, but not Delegate itself".  This would *not* be a new type of constraint different from the existing class-type constraints that already exist.  Perhaps you would be able to state it like so: ```T : delegate```.  

Personally, i think that would be a nifty idea.  However, as @gafter mentioned, this is currently working exactly as spec'ed.  If you'd like teh spec changed (i.e. to add a new type of constraint to type parameters), a proposal will have to be made for it.  Note: such a proposal may already exist.  I would suggest searching for that first.

Cheers!

**Comment by taori** [comment]
@CyrusNajmabadi @gafter Thanks for your feedback - i'll check out csharplang as you suggested.
