### ISSUE TITLE
Heavy Publish Files

### ISSUE THREAD

**Issue by FluffyDragon24** [dotnet/roslyn#28833]
80MB is a bit heavy for a hello world app i think.

Will dotnet core soon be adding mono style publish of only including what is needed instead of everything?
e.g for a hello world app. you should only need the net cores bootloader and apis and the System and mscorlib.

**Comment by ericstj** [comment]
That's for self-contained.  You can use a shared framework application if you rely on a runtime installed on the machine in which case your application will be very small (a couple KB for hello world).

For trimming of self-contained there are two other projects:
- [Microsoft.Packaging.Tools.Trimming](https://github.com/dotnet/standard/blob/master/Microsoft.Packaging.Tools.Trimming/docs/trimming.md) which does assembly-level trimming of your application.
- [ILLink.Tasks](https://github.com/dotnet/core/blob/master/samples/linker-instructions.md) which links and trims assemblies (using the same codebase as the mono linker)
