### ISSUE TITLE
Edit and continue does not work in Preview 5

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#28845]
**Version Used**: Microsoft Visual Studio Enterprise 2017 15.8.0 Preview 5 [27922.0.d15.8]

**Steps to Reproduce**:

1.  Create a new .NET Framework Console App
2.  Set a breakpoint and begin debugging
3.  Attempt to make any edit to the file

**Expected Behavior**:
Edit and continue suceeds

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/9797472/43243699-bdac803e-905c-11e8-91b4-4883137a6108.png)

**Note**: These are my debug settings
![image](https://user-images.githubusercontent.com/9797472/43243777-14e64d62-905d-11e8-8bf6-6c191cf884fc.png)

**Comment by jinujoseph** [comment]
@jmarolf  just tested in 27924 and seems to be working fine. Can you retry on the latest ?

**Comment by jmarolf** [comment]
@jinujoseph I'll update and report back.  I am using enterprise and suspect that it is due to intellitrace

**Comment by jinujoseph** [comment]
@jmarolf  closing this out. revert if you see this again

**Comment by tmat** [comment]
@ivanbasov could you please take a look?
