### ISSUE TITLE
What is the good option to trace/log the custom analyzer implementation? 

### ISSUE THREAD

**Issue by msbasanth** [dotnet/roslyn#28851]
**Version Used**: 
Roslyn v2.6.0

**Steps to Reproduce**:

1. We are getting intermittent crashes and additional file load issues from build machine. 
    Unfortunately this happens only in build machine where we run automated scripts.
2. This we are unable to trace as we don't have tracing or logging mechanism in place.

**Expected Behavior**:
This is not an issue reporting. But wanted to know what is the good option to log/trace analyzers for troubleshooting such scenarios. It would be great if we could get additional tracing/logs in the msbuild output.

**Actual Behavior**:
Currently we only have findings reported gets printed to msbuild log.

Regards
Basanth

**Comment by sharwell** [comment]
@mavasani Do you have a recommended strategy for this that you've found helpful in the past?

**Comment by msbasanth** [comment]
Just adding what I did in our analyzer package which works Ok with few open points.

1. Added a simple logger class which will open a file and write the log (Info, Debug, Error, Exceptiopn).
2. Made each write thread safe using lock.
3. Used static methods and each traces used this class to write to log file.
4. Control enabling and disabling of tracing using setings file which is passed in as AdditionalFile to analyzer.

**Observations:**
Considered log4net initially, the cons is we have to deploy log4net dll along with our analyzer dlls in the _Globals folder.

Another one tried is System.Diagnostics.Trace with TraceListener (even if we don’t have full features in netstandard1.6).
Here,
We have to add TraceListener like,
        Trace.Listeners.Add(myFileListener);
and we add tracing using,
        Trace.WriteLine(traceString);
and we have to keep listener/file open and we don’t have(with my understanding) an event with which we can close or dispose the trace file.
So to keep it simple and to close the trace file each time, used a file writer. **Issue is** cost when we we enable tracing.

Any better approach you tried or come across which will keep the trace file open & close gracefully.

Regards
Basanth

**Comment by sharwell** [comment]
One approach that I like is using performance tracing tools to log exceptions. I'll see if I can find the old branch where I did this for Roslyn as an experiment. The files are very big, but it will have the data you need to deal with the problem.

**Comment by msbasanth** [comment]
@sharwell that would be helpful if you could share.

**Comment by sharwell** [comment]
@msbasanth You can see the approach in #29448.
