### ISSUE TITLE
Rosyln files locked during deployment(msdeploy) and fails with ERROR_FILE_IN_USE

### ISSUE THREAD

**Issue by sabmah** [dotnet/roslyn#28856]
**Version Used**: 

- MVC 5
- .Net version 4.6.1
- Microsoft.CodeDom.Providers.DotNetCompilerPlatform 2.0.0
- Microsoft.Net.Compilers 2.8.2

- Windows Server 2016
- IIS 10.0.14393.0
- TeamCity 2018.1

**Steps to Reproduce**:
NOTE: I'm doing all this from TeamCity CI
1. Build and Deploy MVC5 project with roslyn compiler to IIS
2. Once step 1 is deployed, Deploy again (occasionally its successful and lot of times it errors )

**Expected Behavior**:
Successfully deployed the site to IIS

**Actual Behavior**:
Error Code: ERROR_FILE_IN_USE
[16:18:10]More Information: Web Deploy cannot modify the file 'csc.exe' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.

**Also:** Every file in bin\roslyn folder has same issue. It shows different files being locked on every deployment with that error. My razor views are also using c#6 features.

**Comment by sharwell** [comment]
@jaredpar We think this is likely **Area-External** but weren't sure. Can you move it if it's not compilers?

**Comment by jaredpar** [comment]
@sabmah thanks for taking the time to file this. The actual bug is in the https://github.com/aspnet/RoslynCodeDomProvider repository. Can you please file the bug over there?

**Comment by sabmah** [comment]
@jaredpar  Thank. I will file the bug over there. To answer your question on if I can move if its not compilers, yes, I can move without compilers.
