### ISSUE TITLE
Analyzer incorrectly proposes removal of unnecessary cast.

### ISSUE THREAD

**Issue by kfertitta** [dotnet/roslyn#28867]
**Version Used**: 
15.7.5

**Steps to Reproduce**:

1. Create a statement such as the following:
```
int? a = false ? 1 : default;
Console.WriteLine(a.HasValue);
```
2.  The result of this statement is, somewhat surprisingly, `True`.  The literal `1` apparently forces the type of the ternary to `int` and, consequently, the `default` expression to effectively be `default(int)`.
3. Modifying the ternary, like so, yields the (arguably more "expected") result of `False` for `HasValue`:
```
int? a = false ? (int?)1 : default;
Console.WriteLine(a.HasValue);
```

Note the cast of the literal to `(int?)` forces the ternary to be of nullable type.  However, the analyzer dims the cast and proposes a "Remove unnecessary cast" suggestion.  That will change the behavior of the code.

4. Interestingly, the analyzer *does* seem to have some level of awareness of the literal `1` forcing the ternary type to `int` because the following also yields `False` and the analyzer does *not* suggest removal of the argument to the `default` keyword.
```
int? a = false ? 1 : default(int?);
Console.WriteLine(a.HasValue);
```

**Expected Behavior**:
The analyzer should not propose removal of the cast to `(int?)` because the removal changes behavior.

**Actual Behavior**:
The analyzer does propose removal of a cast to `(int?)` even though such removal changes behavior.

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv and @DustinCampbell

**Comment by gulbanana** [comment]
this also happens with nullable reference types in C# 8. the analyzer proposes "Remove unnecessary cast" for code like
```
void Foo(Bar bar)
{
    var nullableBar = (Bar?)bar;
    nullableBar = null;
}
```

**Comment by CyrusNajmabadi** [comment]
I'm not seeing either of these behaviors.  Adding tests to confirm this so we can close this out.
