### ISSUE TITLE
Rename All Intellisense Pop-Up Disappears Often in VS2017 VB.NET WPF Solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28874]
<p>Using VS2017 Version 15.6.6, this one has become a bit annoying. It seems that very often (at least 33% of the time - particularly in larger solutions), when you rename a variable, the quick menu / down arrow that pops up that allows you to select rename all shows briefly and then disappears permanently as you try to click on it with the mouse. Using the Alt+Enter keyboard shortcut seems to work better than trying to get at the pop-up menu with the mouse but is only marginally better. This for sure happens in WPF solutions in VB.NET. I believe I've also seen it in .NET Standard solutions.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/292934/rename-all-intellisense-pop-up-disappears-often-in.html
VSTS ticketId: 648186_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎7‎/‎21‎/‎2018, 03:40 AM (6 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

Jinu Joseph [MSFT] on ‎7‎/‎27‎/‎2018, 03:47 AM (8 hours ago): <p><a rel="user" href="https://developercommunity.visualstudio.com/users/86972/e2afb424-b232-661b-a682-4a7b11654dfd.html" nodeid="86972">@Travis Morrison</a> will you be able to provide a small repro scenario that we could try to reproduce and investigate</p>

Travis Morrison on ‎7‎/‎27‎/‎2018, 09:01 AM (3 hours ago): <p>It really doesn't seem to be project specific. It literally happens in almost every solution I have :( , and, it doesn't happen every time. When it does happen, it usually keeps happening until I restart VS.</p>

_These are the original issue solutions:_

Travis Morrison solved on ‎7‎/‎26‎/‎2018, 11:27 AM (25 hours ago), 0 votes: <p>I didn't realize how much I use this feature until it broke :( . This one has become extremely annoying (to the point where I might have to revert back to VS2015). Hopefully someone can look at this soon.</p>

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  clsoing out.
