### ISSUE TITLE
Today's latest preview build broke the MSBuild

### ISSUE THREAD

**Issue by anirudhagupta** [dotnet/roslyn#28871]
I install the latest preview and try to open my c# projects (.sln) and none of them worked in latest peview, work fine in 15.7.5

something is wrong with today's preview build (VS 15.8 preview 5).
![capture1](https://user-images.githubusercontent.com/2105258/43321437-763c59ae-91c9-11e8-9d72-8552c44cae62.PNG)

**Comment by anirudhagupta** [comment]
@jaredpar I tried repair few days ago and this issue resolved.

**Comment by jaredpar** [comment]
Thanks for following up and glad it's resolved.
