### ISSUE TITLE
Cross-platform support for AbstractStructureTaggerProvider 

### ISSUE THREAD

**Issue by minestarks** [dotnet/roslyn#28902]
Currently TypeScript implements a [`BlockStructureProvider`](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/Structure/BlockStructureProvider.cs) to provide outlining. However it's not activated in VS Mac because [`AbstractStructureTaggerProvider`](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core.Wpf/Structure/AbstractStructureTaggerProvider.cs) is not available cross-platform. We'd like it to be available on Mac so JS outlining comes online.

**Version Used**: 2.9.0-beta4-63001-02

**Comment by CyrusNajmabadi** [comment]
@minestarks Can you clarify what you would like to be done on the Roslyn side?

**Comment by minestarks** [comment]
The WPF dependencies will need to be severed. @jasonmalinowski has more specifics.

**Comment by sharwell** [comment]
This appears to be related to #26445

**Comment by CyrusNajmabadi** [comment]
Definitely let me know.  I don't see anything about AbstractStructureTaggerProvider that would have a WPF dependency...

**Comment by minestarks** [comment]
I think it's more than just that specific class. @jasonmalinowski thought it may have to do with this comment

https://github.com/dotnet/roslyn/commit/4a546a32e75372c4eb702cd6fe55c89585ae418e

> Right now some of this depends on our ability to make text views when we hover over things, so for now we'll leave it up here. This is a fairly weak dependency and will be able to move back soon.

**Comment by decriptor** [comment]
I think some of the work for this might already be in the works on the VSmac side. See https://github.com/mono/monodevelop/tree/editorCompletion

/cc @KirillOsenkov @DavidKarlas @Therzok

**Comment by CyrusNajmabadi** [comment]
@minestarks is this still needed?

**Comment by minestarks** [comment]
Probably not, since I believe this is getting LSP-ified, but tagging @zkat / @MariaSolOs to confirm we won't need this class for VSMac in the near term.

**Comment by MariaSolOs** [comment]
Funny, @zkat and I were actually talking about this today. @minestarks is right. We plan on LSPifying this soon, so this request is no longer needed.

**Comment by CyrusNajmabadi** [comment]
Closing out then.
