### ISSUE TITLE
F# Project Options for Project

### ISSUE THREAD

**Issue by TIHan** [dotnet/roslyn#28919]
Currently, F# has no way to retrieve project options from a project. Because of this, we have a serious amount of complexity surrounding how we get this data to our editor features.

I would really like us to figure out how we can make this happen. In my mind, it's almost as simple as a project containing a string of command line arguments. From there, we can easily parse this information and pass it to the F# compiler services.

Tagging @jasonmalinowski.

**Comment by sharwell** [comment]
@TIHan Are you referring to .editorconfig/code style values or to some other options?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of response.  If changes are requested, we should be explicit about them and assign them to cross team work items and milestones.
