### ISSUE TITLE
Suggest default names for Anonymous Type and ValueTuple elements when values are returned by methods

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/roslyn#28928]
This code:
```C#
var Res = from Control c in Controls
          orderby c.Name
          group c by new {c.GetType(), c.Enabled};
```

gives the syntax error:
> Invalid anonymous type member declarator. Anonymous type members must be declared with a member assignment, simple name or member access.

The editor doesn't suggest any solutions. I think it can suggest this solution:

> add an explicit name:

```C#
var Res = from Control c in Controls
          orderby c.Name
          group c by new {Name1 = c.GetType(), c.Enabled };
```
Similar situation with Tuples:
```C#
var Res = from Control c in Controls
          orderby c.Name
          group c by (c.GetType(), c.Enabled);
```

This will not cause any error, but the Tuple definition will be
```(Type, bool Enabled)```

An analyzer can give the following suggestion:
> add an explicit name:

Similar situation with Tuples:
```C#
var Res = from Control c in Controls
          orderby c.Name
          group c by (Name1 = c.GetType(), c.Enabled);
```

Note that this is a general proposal. LinQ is just an example, but this sould apply to Anonymous Type and ValueTuple anywhere.

**Comment by CyrusNajmabadi** [comment]
Why is 'Name1' an appropriate name to suggest?

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
It is just a placeholder. It should be highlighted to be replaced. Feel free to suggest any other naming scheme. In fact I wish to infer a suitable name based on the method name or its return value. In GetType we can get red og Get and use type. This will need to analyze all method names to set some rules. I think this is too much work, and it is easier to suggest any default name and highlight it. Fast and Cheap.

**Comment by CyrusNajmabadi** [comment]
> It is just a placeholder. It should be highlighted to be replaced. Feel free to suggest any other naming scheme. In fact I wish to infer a suitable name based on the method name or its return value. In GetType we can get red of Get and use type. This will need to analyze all method names to set some rules. 

@MohammadHamdyGhanem Can you create a prototype with this behavior as we can try it out.  That would make it easier to assess if this is a good idea or not.  I can help you with creating that prototype if you want.

**Comment by sharwell** [comment]
> Why is 'Name1' an appropriate name to suggest?

The suggested name should be `Type`.

**Comment by sharwell** [comment]
I'm marking this as **help wanted**, because a design review should not be required to implement one specific section of this: in the event a compilation error is reported due to the lack of a name for a member of an anonymous type, the *existing name suggestion feature* can be used to provide a name that corrects the compilation error.

**Comment by MohammadHamdyGhanem** [comment]
@sharwell 
Suggesting a proper name based on a method name is not easy. Some method names can be used as is, others need to add d, ed, or ing, others can take only the first part or the last part of the name and somethimes the name should be totally different. First I thought the compiler should guess the name, but the developer may not like it, so, I thought it will be better if the editor give him a hifhlighted suggested name so he can change it. This will help begginers to realize where the error came from and how it can be corrected. If this is the case, then the solution will be similar for Anonymous Type and ValueTuple. Otherwise, if the "existing name suggestion feature" you are referring to can solve this issue, it is OK to so so. But please give me a link for more info about it.

**Comment by MohammadHamdyGhanem** [comment]
@sharwell 
Another point: How will you suggst the names for expressions, or string letirals llike ```new { "test", c.Enabled }```

**Comment by CyrusNajmabadi** [comment]
@MohammadHamdyGhanem I can walk you through implementing this if you're interested.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
Thanks for your kindness. My mind is full now, and there is no room for more. I hope I can finish the tasks in hand so I can participate in these interesting tasks.
