### ISSUE TITLE
VS tooltip should prioritize errors over warnings

### ISSUE THREAD

**Issue by 0x53A** [dotnet/roslyn#28937]
**Version Used**: 

VS 15.7.3

**Steps to Reproduce**:

Create a new Lib and enable the XML Documentation File.

The warning CS1591 hides the error CS0542 and the error is only visible after fixing the warning.

![grafik](https://user-images.githubusercontent.com/4236651/43385681-a95c7264-93e1-11e8-820b-fdbc27da4ab9.png)

![grafik](https://user-images.githubusercontent.com/4236651/43385707-bc34df34-93e1-11e8-87de-5c90bddfbfd5.png)

__Actual:__

It shows only the warning.

__Expected:__

Errors should have a higher priority than warnings, it should show either only the error, or both.

**Comment by Neme12** [comment]
Duplicate of #26022

**Comment by 0x53A** [comment]
Ah, yeah, thanks!
