### ISSUE TITLE
Stale errors after rename in the editor

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#28939]
**Version Used**: 
15.8.0 Preview 5.0

**Steps to Reproduce**:
I don't know specifically. I moved all code from a base class to the derived class, removed the base class, and changed the `protected` `const` and `readonly` fields to `private`. After that, squiggles appeared because those two fields started with a capital letter instead of lower case. I `F2`-renamed both fields to a lower case first letter and the two shown squiggle categories remained.

After the next edit (hitting `space` somewhere), the errors disappeared.

**Expected Behavior**:

No errors / squiggles. There's nothing wrong with the code and the errors refer to a situation that's not valid anymore or has never been valid.

**Actual Behavior**:
Squiggles.

`const` member:
![image](https://user-images.githubusercontent.com/1947968/43398350-1df2963c-9408-11e8-951d-a24df36ce52f.png)
`readonly` member:
![image](https://user-images.githubusercontent.com/1947968/43398393-42d06704-9408-11e8-999b-b66319cf3740.png)

**Comment by sharwell** [comment]
@jinujoseph This feels like a duplicate of one or more other issues related to stale data in the Error List.

**Comment by Tragetaschen** [comment]
![image](https://user-images.githubusercontent.com/1947968/43846324-574ffe38-9b2e-11e8-92fd-1d9c335ed971.png)

I just prepended the existing `await...` with the `var sent = `

**Comment by JieCarolHu** [comment]
This issue is duplicated with https://github.com/dotnet/roslyn/issues/23631
Please continue commenting on https://github.com/dotnet/roslyn/issues/23631

**Comment by Tragetaschen** [comment]
I'm not sure those are related.

The errors reflect a state that only briefly existed while editing
- The Rename example from the OP shows the state between renaming the member and renaming the references
- The `vaawait` case existed after hammering in the characters to generate the declaration

Most importantly, the errors go away with the very next edit in the open document and thus never survive in the error list.

So an layman's terms (mine :)) it looks like sometimes a running semantic analysis of the code isn't properly cancelled on subsequent edits. Instead it blocks the analysis of the code that's actually shown in the editor.

I've seen numerous other examples while editing, but none qualify as reproducible. I'm only seeing red squiggles that don't reflect the current state of the document, do another edit, and then they are gone again.

**Comment by Tragetaschen** [comment]
Here's a very strange one:
![image](https://user-images.githubusercontent.com/1947968/44101488-d51a7ee8-9fe7-11e8-96a0-dda7d2328f44.png)

Again, gone after the next edit.

**Comment by Tragetaschen** [comment]
And another one.
![image](https://user-images.githubusercontent.com/1947968/45883962-d7f84300-bdb2-11e8-8242-e8b9f91b6a9e.png)
I've copied the first two lines and changed the prefix twice.

Maybe it's related: I've been opening another solution in a new VS instance in the background. This means my 2-Core Core-i7 was rather occupied with that. Is there a timeout in IntelliSense that might have canceled the code analysis?
