### ISSUE TITLE
Poor error for using nullable type in pattern

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#28949]
```
public class C {
    public void M(object o) {
        _ = o is string? x;
    }
}

//error CS1003: Syntax error, ':' expected
//error CS1525: Invalid expression term ';'
//error CS0103: The name 'x' does not exist in the current context
```

**Comment by gafter** [comment]
Parser says: That's not a nullable type in a pattern. That's the condition of a ?: operator, in which the second operand is x.

**Comment by gafter** [comment]
I don't think this has anything to do with nullable reference types. You get the same thing for this:

``` c#
public class C
{
    public void M(object o)
    {
        var q = o is int ? x;
    }
}
```

You get the same errors for older language versions too.

**Comment by jcouv** [comment]
Hum, I'm afraid you're right (we can't do anything) :-(
I'll close

**Comment by CyrusNajmabadi** [comment]
well, as it's an error under any grammar production, we could tweak the parser to detect these cases and give better messages.  Whether or not that's important enough (or easy enough) to do is a different matter though :)
