### ISSUE TITLE
Implement FindNode with ChildThatContainsPosition instead of FindToken

### ISSUE THREAD

**Issue by PranavSenthilnathan** [dotnet/roslyn#28947]
Currently there is a todo in the code for FindNode:
TODO: This should probably be reimplemented with ChildThatContainsPosition.

FindNode traverses the syntax tree to find the node at a given span. The current implementation finds the leaf token at the start of the span and works back up to find the child node that contains the end of the span. Instead this can be done in a single pass by checking the end of the span as we traverse down the tree.

It's a minor change with a little bit of perf benefit (shorter traversal and avoiding unnecessary red node allocation). I'd like to work on this change as my first contribution if it's triaged/approved.

**Comment by CyrusNajmabadi** [comment]
@PranavSenthilnathan Go ahead :)  It would be useful to have a perf demonstration that shows your change is helpful and does not hurt anything.

**Comment by CyrusNajmabadi** [comment]
Moving to compilers.  This is not an IDE issue.  Given the lack of movement from the original filer, this can likely be closed out.

**Comment by CyrusNajmabadi** [comment]
Closing out.
