### ISSUE TITLE
Quick Actions on String Literal Hangs

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28972]
When invoking Quick Actions (whether by Ctrl+., Alt+Enter, or the on-screen button) on a string literal, the 'Gathering Suggestions' dialog box shows up and remains for an inordinately long time (sometimes upward of 60 seconds), but eventually the Quick Actions do show up (albeit not quickly).

Problem arose seemingly out of nowhere - I used Quick Actions to introduce constants for a number of strings with no issues, then I tried one and this behavior happened and has repeated ever since.

Thus far I haven't had problems opening Quick Actions on any other types.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/297522/quick-actions-on-string-literal-hangs.html
VSTS ticketId: 652190_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by JieCarolHu** [comment]
I was not able to repro this issue in the latest 15.8 Preview 6. Here is my repro steps, please let me know if I missed any steps. Thanks!

1) Parse the following code in a C# project
`        public void TestAddingActivePPDirective()
        {
            var text = "";
            var tree1 = SyntaxFactory.ParseSyntaxTree(text);
            var tree2 = tree1.WithInsertAt(0, "#if true $$\r\n\r\n#endif");

            VerifyEquivalent(tree1, tree2, topLevel: true);
            VerifyEquivalent(tree1, tree2, topLevel: false);
        }
`
2) Click on the $$ in the string literal to set focus
3) Press Ctrl+.
Then I got this quick action right away 
![image](https://user-images.githubusercontent.com/17056651/43481459-db9d4558-94ba-11e8-934b-ae241966bbbd.png)

**Comment by jinujoseph** [comment]
Closing as No Repro, feel free to reach us with more specific failing scenario
