### ISSUE TITLE
Auto formatting a file from outside the solution removes necessary usings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28973]
These are sequence of actions I took to encounter this issue.

1. Open a solution that is a subset of the entire code base.
2. Add some breakpoints, attach the debugger, and stop on a breakpoint.
3. Move to a file up the stack trace. The file is ours, but not included in the solution I have open.
4. Stop the debugger and make a change in that file.
5. Press ctrl e+d (auto format) and save.
6. With the exception of &quot;System.*&quot; and aliased &quot;A = Microsoft.Something&quot; usings, all other usings are removed.
7. Build fails, I check the diff in Git and notice the missing usings.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/292075/auto-formatting-a-file-from-outside-the-solution-r.html
VSTS ticketId: 646462_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by JieCarolHu** [comment]
The repro steps can be simplified as following:
1) Start a VS instance, and open a C# file from an existing solution
2) Run code cleanup with "remove unnecessary usings" checked, Click Save
3) Close the file, and open the solution and try to build

**Comment by sharwell** [comment]
This is a compiler bug. Unused usings should never be reported if a binding failure occurs anywhere in the compilation unit outside of the list of using directives itself.

**Comment by gafter** [comment]
If the compiler does not find a use for the `using`, it is reported unused.  If the IDE thinks that should not cause the usings to be removed in the presence of other errors, the IDE should act accordingly.

(This is probably not so easy in the compiler either)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in experiences in misc files.
