### ISSUE TITLE
UseNamedArguments doesn't trigger in incomplete invocation

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#28988]
While typing an invocation, SignatureHelp is able to find the correct overload (single one in the case depicted below), but UseNamedArguments doesn't offer to name an argument I typed (`arity:` in this example).

![image](https://user-images.githubusercontent.com/12466233/43499178-1fde4854-94ff-11e8-8877-8415aba98f44.png)

![image](https://user-images.githubusercontent.com/12466233/43499196-306d413e-94ff-11e8-96be-d5191a1e654d.png)

**Comment by CyrusNajmabadi** [comment]
closing due to lack of feedback.
