### ISSUE TITLE
Compiler is loading native dependency from random directory, not the directory it is running from

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#2898]
```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4385,5): warning MSB3061: Unable to delete file "C:\R5\Binaries\Debug\Microsoft.DiaSymReader.Native.amd64.dll". Access to the path 'C:\R5\Binaries\Debug\Microsoft.DiaSymReader.Native.amd64.dll' is denied.
```
while building from VS.
![image](https://cloud.githubusercontent.com/assets/41759/7693961/74f63b28-fd8e-11e4-830f-e0b810ae7866.png)

Memory dump of VBCSCompiler.exe:
%internal_share%\public\tomat\Bugs\2840

The compiler is running from the toolset:
```
C:\R5\packages\Microsoft.Net.ToolsetCompilers.1.0.0-rc3-20150510-01\tools\VBCSCompiler.exe
```

The current directory of the process is 
```
C:\R5\packages\Microsoft.Net.ToolsetCompilers.1.0.0-rc3-20150510-01\tools\
```

So it should not be loading binaries from  C:\R5\Binaries\Debug

**Comment by jaredpar** [comment]
This is not random. The compiler uses DllImport to load this DLL. The rules of DLlImport allow for this case and isn't something we attempt to override.

**Comment by tmat** [comment]
Let's keep this open. This is really breaking builds when dogfooding.

**Comment by jaredpar** [comment]
Re-closing.  I don't see why this DLL should be special cased over the other items we currently load via `DllImport` (of which there are several).  

To my knowledge the `DllImport` code uses the same probing logic of other DLL loads in a process.  If the user environment chooses to override this load order to pick a new DLL then we should be respecting that, not disrupting it.  

Note: if the compiler is choosing a different DLL it likely has something to do with your local environment. In particular probably the `%PATH%` value.

**Comment by tmat** [comment]
Yes, it's picking it up from ```%PATH%```. We could use LoadLibrary from a specific and GetProcAddress. It seems safer and enable app local deployment. I guess if we version the COM interfaces we use globally we are ok. It's just weird to be loading stuff from some other place.

**Comment by jaredpar** [comment]
@tmat yes we could use a combo of `LoadLibrary` + `GetProcAddress` but at that point we are basically re-implementing `DllImport` to work around it's defined, and expected, behavior.  Such a change shouldn't be for a specific DLL here but instead should be a code base wide decision.  I don't see us making that type of change.

**Comment by tmat** [comment]
@jaredpar http://source.roslyn.io/#Microsoft.CodeAnalysis/SqmServiceProvider.cs,e8c8e2780a8ca4bd

**Comment by jaredpar** [comment]
@tmat I don't see how `LoadLibrary` and `DllImport` differ any in behavior here.  They both follow the standard DLL search order as far as I can tell:

> https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586%28v=vs.85%29.aspx

The reason we have the behavior you are seeing is DiasymReader is not present next to VBCSCompiler because it's not included in Microsoft.Net.ToolsetCompilers.  Hence the remainder of the DLL search algorithm kicks in.  Eventually it discovers it in one of the values of `%PATH%`.  This means both `DllImport` and `LoadLibrary` will end up loading the DLL from `%PATH%` in this case. 

I'm unsure why we chose to use `LoadLibrary` in that particular example but it looks suspect.  Seems like it should follow instead the same pattern we have for DiasymReader loading.

**Comment by tmat** [comment]
@jarepar The search doesn't kick in if a full path is used in LoadLibrary. 

Correct, the %PATH% is only relevant if the native library is not present next to the managed one. However, both scenarios (SQM and custom Diasymreader) are light-ups so that will be the case.

The plan was to package the library with compiler server, but don't include it in VSIX when installed with VS, since 1) only EnC uses Emit from within VS process, 2) EnC doesn't require deterministic PDB generation or any other fix that we have in the custom build, 3) VS has a dependency on FX 4.6. Thus it's unnecessary to load the Diasymreader into VS process. So we'd fall back to the one in .NET Framework 4.6.

Now consider that someone has Roslyn nuget deployed in a directory that is on their %PATH%. They want to use csc from it on command line so they include it there. Then they run VS from the same environment. Now we are going to load Diasymreader into VS process and use it for EnC, which we didn't test. It *should* still work OK. It's gonna take away another megabyte of VS address space though.

**Comment by jaredpar** [comment]
@tmat 

> The search doesn't kick in if a full path is used in LoadLibrary.

Correct.  Haven't seen that proposed as a solution yet though.  

> Now consider that someone has Roslyn nuget deployed in a directory that is on their %PATH%. ... Then they run VS from the same environment.

If someone is running VS with a `%PATH%` value that contains `DllImport` values then bad things are going to happen.  That is simply the nature of DLL loading.

**Comment by tmat** [comment]
@jaredpar Yeah, that's why DllImport is broken for light-up native dependencies, which is why I filed this bug. How do they know to not include such %PATH%? Does a common developer inspect all VS binaries to see what dependencies they might have and validate their %PATH% doesn't accidentally contain them?

**Comment by jaredpar** [comment]
@tmat 

> Yeah, that's why DllImport is broken for light-up native dependencies, which is why I filed this bug

I simply disagree with this statement.  There is nothing broken about `DllImport`.  It uses the defined behavior of DLL loading on Windows which has been in place for decades.  It has behaviors that may not be ideal for our situation but they are well understood and tolerated by loads of other applications.  

> How do they know to not include such %PATH%?

Messing around with `%PATH%` has an impact on every platform out there (Windows, Linux, etc ...).  I don't see the value in fixing a subset of scenarios that Roslyn cares about when the rest of Visual Studio, and really the world, doesn't take the same approach.  There is simply no reason for us to differentiate here.  

> Does a common developer inspect all VS binaries to see what dependencies they might have and validate their %PATH% doesn't accidentally contain them?

Do other VS components use `LoadLibrary` over `DllImport` because of this perceived failing in the loading order?  No.  We shouldn't either.

**Comment by tmat** [comment]
@jaredpar  There are (at least) two well-understood and standard ways to load native dependencies. Load by relative path (DllImport) and load by absolute path. One is more suitable for what we want to do. So we don't use it.

**Comment by jaredpar** [comment]
@tmat 

> Load by relative path (DllImport) and load by absolute path.

I don't understand the inclusion of `DllImport` here.  `DllImport` and `LoadLibrary` have **identical** load semantics: both support absolute or relative paths and both follow the same search sequence.  The choice is simply between absolute and relative paths.  

True it's easier to support `LoadLibrary` with absolute paths given they can be calculated dynamically.  But there is no fundamental limitation with `DllImport`.

**Comment by tmat** [comment]
BTW, just found this:
https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.dllimportsearchpath(v=vs.110).aspx

We should use that.

**Comment by jaredpar** [comment]
@tmat at a glance that doesn't appear to be a portable API.  If it was (or is just incorrectly labelled in MSDN) I agree we could consider it.  But it is something we would need to discuss more broadly with the team.

**Comment by tmat** [comment]
@jaredpar It is not portable, but that doesn't matter since it's an attribute. The CLR is looking up the attribute by name. So we can define an internal attribute of the same shape and it should be matched.

**Comment by amcasey** [comment]
Seems like this requires some sort of closure, so adding "Bug".
