### ISSUE TITLE
CSC.exe not found when running Application through "OpenWith..." Windows context command

### ISSUE THREAD

**Issue by OmegaSyrus** [dotnet/roslyn#28981]
**Version Used**: 2.0.0.0

**Steps to Reproduce**:

1. Create project, add NuGet reference to DotNetCompilerPlatform
2. Open your project through OpenWith on a file via right-click OpenWith... in Windows
3. reach line containing - var provider = CSharpProvider();
4. run provider.CompileAssemblyFromSource(parameters, sources); 
I don't think parameters or sources is relevant to bug.

**Expected Behavior**:
csc.exe is found and used for compilation

**Actual Behavior**:
Roslyn looks for C:/System/Windows/Roslyn/csc.exe instead of in the path of your App.exe workingpath

**Comment by jaredpar** [comment]
Thanks for reporting this. Unfortunately this looks to be an issue in a different component. 

https://github.com/aspnet/RoslynCodeDomProvider

Can you refile the bug there?
