### ISSUE TITLE
Analyzers not getting run during build

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#28985]
We're not passing any analyzers to CSC during build. Investigating.

/cc @jaredpar @dotnet/roslyn-infrastructure

**Comment by jaredpar** [comment]
@tmat looks like this PR broke Roslyn analyzers https://github.com/dotnet/roslyn/pull/28319

This change removed the `<ProjectLangauge>` element from our build files. The Roslyn diagnostic analyzers use that to load themselves into the build. 

``` xml
  <ItemGroup Condition="'$(ProjectLanguage)' == 'CSharp'">
    <Analyzer Include="$(NuGetPackageRoot)\microsoft.codequality.analyzers\$(RoslynDiagnosticsNugetPackageVersion)\analyzers\dotnet\cs\Microsoft.CodeQuality.Analyzers.dll" />
    <Analyzer Include="$(NuGetPackageRoot)\microsoft.codequality.analyzers\$(RoslynDiagnosticsNugetPackageVersion)\analyzers\dotnet\cs\Microsoft.CodeQuality.CSharp.Analyzers.dll" />
```

**Comment by tmat** [comment]
The analyzer targets files should use `Language` instead of `ProjectLanguage`. `ProjectLanguage` is not .NET SDK concept, it was a custom property only defined in Roslyn repo.

**Comment by tmat** [comment]
https://github.com/dotnet/roslyn-analyzers/pull/1749
