### ISSUE TITLE
CS0103 code fix could probably do better in overloaded situations.

### ISSUE THREAD

**Issue by brian-reichle** [dotnet/roslyn#28996]
**Version Used**:  Visual Studio 15.7.2

**Steps to Reproduce**:

Use the CS0103 code fix on the `Bar` and `Baz` identifier in the following to generate methods.

    abstract class Barry
    {
        public void Method()
        {
            Foo(Bar); // suggests creating a 'Bar' method with a signature matching Action -- all good here.
            Foo(Baz, null); // suggests creating a 'Baz' method with a signature matching Action -- can't work.
        }

        protected abstract void Foo(Action action);
        protected abstract void Foo(Action<object> action, object arg);
    }

**Expected Behavior**:
I would expect that when generating methods from the `Bar` and `Baz` identifiers, they would be generated as `void Bar()` and `void Baz(object arg)` respectfully.

**Actual Behavior**:
Both the `Bar` and `Baz` methods are generated without an argument, which means that the `Foo(Baz, null)` gets another error because the generated method has the wrong signature.

Perhaps the code fix could filter the list of overloads based on the other arguments provided when trying to determine which signature to use for the generated method. If it's still ambiguous, then present a code fix for each of the viable options and let the user decide.

**Comment by sharwell** [comment]
@brian-reichle I know it's not fun to hit these, but this is a pretty cool bug report (I enjoyed reading it and understand why it should be fixed). 👍

**Comment by jnm2** [comment]
I'm hitting this too, when generating a method from `Task.ContinueWith(NewName, state)`.
