### ISSUE TITLE
Incorrect simplification of Nullable{T} in XML comment

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#29]
The following shows an incorrect **Simplify name** proposal for a reference to `Nullable<T>` within an XML documentation comment.

![image](https://cloud.githubusercontent.com/assets/1408396/5793849/a8315136-9f19-11e4-8f1e-e7e5665c3e5a.png)

This can be reproduced in Visual Studio 2015 Preview (CTP 4?) and CTP 5 with the following code:

```csharp
/// <summary>
/// The <see cref="Nullable{T}"/> type has been defined not using the C# shorthand.
/// </summary>
public class Foo
{
}
```

**Comment by shyamnamboodiripad** [comment]
Related bugs #2170, #2189, #2196 and #2197

**Comment by shyamnamboodiripad** [comment]
@jmarolf Could you please verify this fix?
