### ISSUE TITLE
Prefix unmerged changes from linked projects with "TODO"

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#290]
1. Create a linked C# file between two projects, one with "ONE" defined and the other with "TWO" defined. 
2. Copy/paste this code:
   
   ``` csharp
   class C
   {
       void Test(int i)
       {
           Test(7);
       }
   
   #if ONE
       void Test(double x) { }
   #elif TWO
       void Test(long x) { }
   #endif
   }
   ```
3. Rename T to Test

**Expected**: The inserted comment should look like:

``` csharp
/* TODO: Unmerged change from project 'LinkedFileRenameTwo'
Before:
        Test(7);
After:
        Test((long)7);
*/
```

**Actual**: The inserted comment looks like:

``` csharp
/* Unmerged change from project 'LinkedFileRenameTwo'
Before:
        Test(7);
After:
        Test((long)7);
*/
```

**Comment by dpoeschl** [comment]
Clearing the milestone so @Pilchie can triage this. :smile:

**Comment by CyrusNajmabadi** [comment]
Closing out.  Haven't done this in 8 years.  Haven't heard anything on this.
