### ISSUE TITLE
Assign with await operator alternative for await

### ISSUE THREAD

**Issue by bigdnf** [dotnet/roslyn#29002]
We have a lot of async code nowadays and code is polluted with await keywords. Maybe it would be simpler to do this with special operator so instead of

`var result = await AsyncFunction();`

we could write something like this

`var result &= AsyncFunction();`

or similar to c++ pointer resolution

`var result = *AsyncFunction();`

The best solution would be to resolve value by default and not do this when on left side we have Task but this would break existing code so maybe operator?
What do you think about this approach?

**Comment by CyrusNajmabadi** [comment]
1. Language suggestions should be made at dotnet/csharplang.  
2. Both of those syntaxes are already legal and already have meaning in the language.  Overloading them for Tasks seems like a worrying idea.

**Comment by bigdnf** [comment]
Ok I will rethink this and post in dotnet/csharplang - is teher any option to delete issue here?

**Comment by CyrusNajmabadi** [comment]
Not that i know of.  Someone will come along and simply close this out.
