### ISSUE TITLE
C# Ignore checked return

### ISSUE THREAD

**Issue by h82258652** [dotnet/roslyn#2900]
Take an example:

```
        public string GetDatas(int pageIndex,int pageSize)
        {
            // check parameters.
            try
            {
                var forCheck = checked(pageIndex * pageSize);
            }
            catch (OverflowException)
            {
                throw new ArgumentException();
            }

            // get data from DB or WebService.
            // ...... 
        }
```

The keyword "checked" use like this must use a variable to point to the result.
Why can we remove the variable? We don't need the variable.

```
        public string GetDatas(int pageIndex,int pageSize)
        {
            // check parameters.
            try
            {
                checked(pageIndex * pageSize);
            }
            catch (OverflowException)
            {
                throw new ArgumentException();
            }

            // get data from DB or WebService.
            // ...... 
        }
```

**Comment by tmat** [comment]
You can achieve the above in more efficient and succinct way:

```C#
if ((long)pageIndex * pageSize) > int.MaxValue) throw new ArgumentException();
```

**Comment by h82258652** [comment]
@tmat 
But if the parameter are both Int64, we still need checked.

**Comment by gafter** [comment]
The proposal, if I read it correctly, is to add the checked expression to the set of allowed expression forms in an expression-statements.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

See also https://github.com/dotnet/roslyn/issues/18002 for a general discussion of closing and/or moving language issues out of this repo.

**Comment by gafter** [comment]
I have not moved this feature request to the csharplang repo because I don't believe it would ever rise in priority over other requests to be something we would ever do in any particular release. However, you are welcome to move discussion to the new repo if this still interests you.
