### ISSUE TITLE
Standardize on PascalCase for local functions in dotnet/roslyn

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#29019]
Currently the code in **src/Compilers** uses camelCase for local functions while the rest of the code base uses PascalCase. It would be nice to standardize the style on the latter.

Context: https://github.com/dotnet/roslyn/pull/28872#discussion_r207079079

**Comment by gafter** [comment]
I disagree. It would be nice to standardize on the former. PascalCase is for a name that is an API (e.g. methods and fields). camelCase is for local names (local variables and local functions).

**Comment by CyrusNajmabadi** [comment]
I personally like pascal case.  Camel case indicates a variable (i.e. a local or param).  As such, the distinction helps make it clear what is actually a delegate instance, vs what is a function (local or external).

**Comment by sharwell** [comment]
I've been appreciative of the distinction between local functions (PascalCase) and delegate instances (camelCase). If local functions were just syntactic sugar for delegate instances (similar to the relation between anonymous functions and lambdas), I would totally understand keeping the style the same. However, this is a very different situation.

**Comment by gafter** [comment]
I've been appreciative of the distinction between methods (PascalCase) and local functions (camelCase).

**Comment by sharwell** [comment]
@gafter Feel free to close as **Won't Fix** if it won't change. The .editorconfig I added already marks **src/Compilers** as using camelCase for local functions.
