### ISSUE TITLE
Add documentation/samples to guide the fix authors on correct way to implement a FixAllProvider

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2902]
`FixAllProvider` seems to be a very common scenario where the expectations from the code fix author are not very clear and they end up getting confused/making mistakes on the following:

1. When should I use the `BatchFixer` vs write a custom `FixAllProvider`?
2. When should I provide an `EquivalenceKey` for code actions, and what value should it be? How does it affect the fix all application, scope. etc.?

We should add more documentation/samples to guide the fix authors about this.

**Comment by sharwell** [comment]
Also:

:question: What strategies can be used to test a custom `FixAllProvider`?

**Comment by sharwell** [comment]
Addressing #201 could make this *much* easier.
