### ISSUE TITLE
Unit Test Failure: error CS0016: Could not write to output file '.../Roslyn.Test.Utilities.xml' 

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#29039]
PR: https://github.com/dotnet/roslyn/pull/28983
Failure: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit32_prtest/15587/

```
CSC : error CS0016: Could not write to output file 'D:\j\workspace\windows_relea---a23004dd\Binaries\Obj\Roslyn.Test.Utilities\Release\Roslyn.Test.Utilities.xml' -- 'The process cannot access the file 'D:\j\workspace\windows_relea---a23004dd\Binaries\Obj\Roslyn.Test.Utilities\Release\Roslyn.Test.Utilities.xml' because it is being used by another process.' [D:\j\workspace\windows_relea---a23004dd\src\Test\Utilities\Portable\Roslyn.Test.Utilities.csproj]
```

**Comment by tmat** [comment]
Another one: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit32_prtest/15773/console

**Comment by tmat** [comment]
I think this might be caused by bad path to the .xml file. The project is multi-targeted, but there is no TFM in the path of the .xml file.
