### ISSUE TITLE
Xamarin.Form UWP Local Machine can't connect to WebAPI/HttpClient but Android do

### ISSUE THREAD

**Issue by Kimoalking** [dotnet/roslyn#29046]
I had upgraded my VS2017 15.2 to VS2017 15.7.5 with use. I am working by Xamarin.Form with .Net Standard. In 15.2 my apps can connect to online WepAPI/HttpClient  and get data into 3 platforms Android, IOS, and UWP. But when I upgraded to VS2017 15.7, I can get data in all platforms except UWP Although there is no syntax error and the app started fine but no data from/to online WepAPI. I searched in the internet I found some solutions:

1. enable Capabilities in Package manifest  of the UWP project, and check Internet (Client) and Private Networks(Client & Server).

2. Cleaning the project.

3. Increasing and Describing Targeting SDK.

4. Installing all Windows SDK from VS_installer in individual components tab.

But All these solutions doesn't work for me at all.

![capabilites](https://user-images.githubusercontent.com/41854826/43631628-ffb93cd0-9703-11e8-8419-5c5e070c932f.PNG)

![individual componants](https://user-images.githubusercontent.com/41854826/43631654-18e6f684-9704-11e8-9fda-f615abced38c.PNG)

**Comment by davkean** [comment]
Please file this using Help -> Send Feedback -> Report a Problem. This repro is for C# and Visual Basic IDE & Compiler bugs.
