### ISSUE TITLE
Opening Solution with empty Xamarin.IOS Unified project fails

### ISSUE THREAD

**Issue by Belorus** [dotnet/roslyn#2904]
await workspace.OpenProjectAsync(ProjPath)

error CS1703: Multiple assemblies with equivalent identity have been imported: 'Microsoft.Build.Framework.dll' and 'Microsoft.Build.Framework.dll'. Remove one of the duplicate references.

At the same time project can be compiled without any issues

**Comment by Belorus** [comment]
I'm pretty sure this issue should be fixed on Xamarin side, the only reason why i created ticket here is that everything builds perfectly.

**Comment by Pilchie** [comment]
Can you take a look and see if this is something we're doing wrong?

**Comment by Belorus** [comment]
Same for WP8 and Xamarin.Android.

Only windows forms works ok for me

**Comment by mattwar** [comment]
I'm not sure what is going on.  Is it the xamarin.ios app in VS producing the error on compile?  Is it an app using msbuild workspace producing these errors after opening a project?  Is the xamarin.ios app using msbuild workspace or is it just the msbuild workspace attempting to open the xamarin.ios app?

Can you supply a small code sample that produces the error?

**Comment by mattwar** [comment]
@belorus do you have more information to clarify this problem?

**Comment by Pilchie** [comment]
Unfortunately, without any more information we're not going to be able to do more here, though this looks similar to an error @joshvarty mentioned.
