### ISSUE TITLE
[Feature] Have optimizer aggressively fold branches

### ISSUE THREAD

**Issue by scalablecory** [dotnet/roslyn#29051]
I'd like Roslyn to detect when one branch leads to another branch, and fold them into a single branch.

I'm sure this optimization has a specific name in compiler theory, but I don't know it. If you'll excuse a dumb example:

```
int InitialBranching(string x)
{
    if (x == "foo") return 0;
    if (x == "bar") return 0;
    if (x == "baz") return 1;
    return -1;
}

string SubsequentBranching(string x)
{
    int y = InitialBranching(x);

    if (y == 0) return x + "0";
    if (y == 1) return x + "1";
    return "other";
}
```

Here, a sufficiently advanced compiler should be able to transform this into something like:

```
string Folded(string x)
{
    if (x == "foo") goto zero;
    if (x == "bar") goto zero;
    if (x == "baz") goto one;
    goto other;

    zero:
    return x + "0";

    one:
    return x + "1";

    other:
    return "other";
}
```

**Why?**

Obviously, the dumb example is not what I'm actually doing. For performance purposes I'm updating a text parser from depending on `char` to be encoding-agnostic. In some places, it needs to allow injecting inlineable sub-parsers that handles encoding-specific things:

```
// returns length of newline if matched, 0 if not matched, -1 if more data is needed.
int IsNewLine<T>(ReadOnlySpan<T> data);
```

This sits right in a hotspot in my code: optimizing this bit makes a huge difference. I've found the extra tests needed to check the return value are causing the code to perform at about 1/4th the speed when compared to a non-agnostic version with `IsNewLine` manually inlined. Having the compiler optimize away these tests would make a huge difference to me.

**Comment by gafter** [comment]
The runtime compiler can do this. It is not specific to C# or VB. I think this request belongs in https://github.com/dotnet/coreclr .

**Comment by scalablecory** [comment]
oh jeez, i thought that's where i put this. will close and open there.
