### ISSUE TITLE
ENC: Create a list of supported / unsupported / future features in the wiki

### ISSUE THREAD

**Issue by davidroth** [dotnet/roslyn#2905]
The upcoming ENC feature in Roslyn/VS2015 is really awesome. This is a real productivity boost for every developer - so great work and a big compliment to everybody involved in the team!

Unfortunately some features are still not supported. 
I often find myself asking why a certain ENC operation is not supported and if it is possible to support it in the future. Currently there is no public document which describes which features are supported/unsupported etc.

It would be great if you could create a list in the wiki, where users can look at to see which features are supported or unsupported. If a features is currently unsupported, it would be interesting to see if it may be added in the future.

Furthermore if a feature is not possible or hard, it would be interesting to hear what would be needed to support it (e.x. "Requires CLR support") or why it is not possible.

The list could look something like this:

| Edit operation| Status | Planned? | Info |
| ------------- |:-------------:| -----:| -----:|
| Adding a linq/lambda statement     | Supported | - | - |
| Modifying a generic method      | Not supported |   YES | Requires CLR support | 
| Adding await expression  | Not supported   |   In Progress | ... |
| Changing method signature  | Not supported   |  No  | Not possible because of reason xy ... |

Do you also think such a list would be valuable?
Would you consider creating such a list?
Would you accept a docu pull request with an initial set of features?

**Comment by kuhlenh** [comment]
@davidroth I am working on making a wiki page for this (unfortunately, some edits aren't that cut-and-dried...).

For now, you can see supported edits [here](http://blogs.msdn.com/b/csharpfaq/archive/2015/02/23/edit-and-continue-and-make-object-id-improvements-in-ctp-6.aspx) and [here](http://blogs.msdn.com/b/dotnet/archive/2015/04/29/net-announcements-at-build-2015.aspx). Hope that helps temporarily, and please let me know if any phrases were confusing!

**Comment by kuhlenh** [comment]
[Here](https://github.com/dotnet/roslyn/wiki/%5BDRAFT%5D-EnC-Supported-Edits) is the working draft on our wiki.

**Comment by davidroth** [comment]
@kuhlenh 

Cool, the first draft looks very good.

Some feedback:

**General feedback**
It would be great if the "planned" and "additional info" columns could be completed.  If a features is currently unsupported, it would be interesting to see if it may be added in the future of what would be needed to implement it.

**Add and modify async/await expressions:**

There are some limitations which are missing in the wiki. For example:

- Adding an await expression to a method, which already contains an existing await expression is not supported (ENC0021)
- Adding 'await expression' around an active statement is not supported (ENC0060)

**Add lambda expressions**

Lambdas cannot capture a variable which has not been captured previously. 
You mentioned this in the wiki: *Lambda expressions can only be added if they are static and access the “this” reference that has already been captured or access captured variables from a single scope*

For example the following does not work:

```cs
private static void ParamTest(string[] args) 
{
// Adding the following linq in edit & continue will not work because of this error: 
// ENC0048: Capturing variable 'args' that hasn't been captured before will prevent the debug session from continuing
    var r = (from x in args
         where x == args[0]
         select x);
}
```
This is very annoying because I think it is a common use case to capture a variable in linq which hasn't been captured before.

It would be interesting to know why this does not work and if it can be resolved in the future.
I think that everything that is needed for this is "already" here (ex. adding new classes and methods at runtime)

My poor mans approach for simulating this feature worked without any problems:

```cs
private static void ParamTest(string[] args) 
{ // [BreakPoint] When hitting this breakpoint  ...

 // ... Edit and continue the following:
 // Step 1: Add the new display class "c__DisplayClass1_0"
 // Step 2: Add the linq code:

  var d = new c__DisplayClass1_0();
  d.args = args;
  var r = args.Where(d.b__0);
}

// Add the following class via edit&continue
sealed class c__DisplayClass1_0
    {
        public string[] args;
        internal bool b__0(string x)
        {
            return x == this.args[0];
        }
    }
```
I am obviously in no way an expert on this topic, but when looking at my simulated enc at the top it looks like this could be enabled. Am I missing something in the puzzle? 

As you can see, I am really interested in how things work behind the scene, and why certain features are not enabled yet (or not even possible).

Thanks :)

**Comment by kuhlenh** [comment]
@tmat Can you please address @davidroth's question around the limitations of capturing a variable in linq which hasn't been captured before?

**Comment by kuhlenh** [comment]
@davidroth I am going to mark this issue as closed because we have added the [wiki page](https://github.com/dotnet/roslyn/wiki/EnC-Supported-Edits) now. 

I will update the wiki with your other suggestions when we begin planning/designing EnC improvements.

**Comment by tmat** [comment]
@davidroth We can indeed enable more scenarios. We are currently somewhat conservative for two reasons: 1) we want to be absolutely sure that an edit doesn't corrupt the state of the program 2) it is relatively easy to explain what is and what is not allowed. We will certainly consider enabling more kinds of edit in future, including the one you mentioned.

**Comment by OmerRaviv** [comment]
@kuhlenh I think the wiki page is missing the limitation on adding a using statement, which has been the one I've personally stumbled onto the most. Also - just a suggestion - but if you don't already do it, it might be a cool idea to collect telemetry on which types of rude edits people run into the most, and then prioritize future E&C improvements against that data.

**Comment by tmat** [comment]
@OmerRaviv 
Yeah, we are aware of the need to be able to add usings (and it would also be useful to be able to a add a reference).
Re telementry: We do exactly as you suggest :)

**Comment by kuhlenh** [comment]
@OmerRaviv oops! Thanks for pointing that out. Added to the list of unsupported edits.
