### ISSUE TITLE
"Getting Started C# Syntax Transformation" walkthrough example has error and is outdated

### ISSUE THREAD

**Issue by keith-anders** [dotnet/roslyn#29085]
The wiki page at https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Syntax-Transformation has two errors in code toward the end of the file.

```C#
// ...
            String rewriterPath = @"..\..\TypeInferenceRewriter.cs";
            String rewriterText = File.ReadAllText(rewriterText);
            SyntaxTree rewriterTree =
                           CSharpSyntaxTree.ParseText(rewriterText)
                                           .WithFilePath(rewriterPath);


            SyntaxTree[] sourceTrees = { programTree, rewriterTree };

            MetadataReference mscorlib =
                    MetadataReference.CreateFromAssembly(typeof(object).Assembly);
            MetadataReference codeAnalysis =
                    MetadataReference.CreateFromAssembly(typeof(SyntaxTree).Assembly);
            MetadataReference csharpCodeAnalysis =
                    MetadataReference.CreateFromAssembly(typeof(CSharpSyntaxTree).Assembly);

            MetadataReference[] references = { mscorlib, codeAnalysis, csharpCodeAnalysis };

            return CSharpCompilation.Create("TransformationCS",
                                            sourceTrees,
                                            references,
                                            new CSharpCompilationOptions(
                                                    OutputKind.ConsoleApplication));
        }
    }
}
```

The line reading `String rewriterText = File.ReadAllText(rewriterText);` is a compiler error (variable cannot be initialized using itself) and should be `String rewriterText = File.ReadAllText(rewriterPath);`. Also, the rest of the code block uses the obsolete `MetadataReference.CreateFromAssembly(Assembly assembly)` API and should be changed to (I presume) use the `MetadataReference.CreateFromFile(string path)` API.

Note that the `CreateFromFile` method takes the path, not the `Assembly`, so a `.Location` will have to be added to each of the assembly accesses.

Also note that these errors each occur twice in the document: once in the sample code under step 19 and once as that code was copy-pasted into the "Your Program.cs file should look like this now" complete example under step 20.

I would make a PR, but github doesn't support PRs for wiki pages.

**Comment by dibarbet** [comment]
Updated!  Thanks for the report.
