### ISSUE TITLE
remove trivia temproary stroage service

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#29111]
we have this default implementation of the service

https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Workspace/Host/TemporaryStorage/TrivialTemporaryStorageService.cs

..

the purpose of temporary storage service is so that we can offload data from memory. this default implementation basically lies about it. it doesn't actually offload from memory anything. this actually makes things worse since it keeps everything in memory but with a lot more allocations. much better just keeps objects in memory rather than convert things to stream and back.

our usage of temporary service is to reduce VM. this basic implementation probably fine for test but not in product actually will imrease VM due to allocation overheads.

...

I believe this default implementation should be removed.

**Comment by CyrusNajmabadi** [comment]
I don't see how we can remove this.  It's used here:

![image](https://user-images.githubusercontent.com/4564579/217952929-4f30ac31-aec2-4a2a-bed5-cdd722a583ff.png)

As long as we have some systems that don't support these features, we'll need this fallback.
