### ISSUE TITLE
make sure all our async service to bail out on Host shutdown

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#29114]
right now, our async services doesn't track VS shutdown. we need to create a machanism to do so so that https://github.com/dotnet/roslyn/pull/29066#issuecomment-410861816 kind of issue doesn't happen.

**Comment by heejaechang** [comment]
new AsyncPackage now has this
http://index/?query=AsyncPa&rightProject=Microsoft.VisualStudio.Shell.15.0&file=AsyncPackage.cs&line=43

we should propagate this to all our services (we could link all our cancellation token to this or expose this through workspace or other host service or something else..) and use this to bail out.

rather than creating our own mechanism, I believe we should just use the one provided and open a bug if that cause race on shutdown (other package starts get shut down before us, and our token not set yet so we don't know about the shutdown)

**Comment by heejaechang** [comment]
we can introduce abstraction (HostService) for this or put the concept directly in Workspace

...

You can implement IVsShellPropertyEvents, then AdviseShellPropertyChanges, and in OnShellPropertyChange do whatever you need to do when propid == (int)__VSSPROPID6.VSSPROPID_ShutdownStarted.

I just did this recently. Here’s an example:
https://devdiv.visualstudio.com/_search?type=code&_a=contents&text=ReviewDeactivationEventResponder&result=DefaultCollection%2FDevDiv%2FCascade-reviews%2FGBmaster%2F%2Fsrc%2FVS%2FMicrosoft.VisualStudio.RichReview.UX%2FReviewDeactivationEventResponder.cs

**Comment by heejaechang** [comment]
I think we can combine the DisposingToken and this Shutdown event and regular cancellationToken and create cancellation token for every our service.

**Comment by CyrusNajmabadi** [comment]
@tmat is this still an issue?

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
