### ISSUE TITLE
Editor Completion -- Support CompletionOptions.BlockForCompletionItems to enable TestNoBlockOnCompletionItems* tests [impacts TypeScript and F#]

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#29112]
**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by dpoeschl** [comment]
Still deadlocking. Only appears to impact TypeScript.

**Comment by dpoeschl** [comment]
Starting point for investigation: http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/IntelliSense/Completion/Controller_CommitUniqueCompletionListItem.cs,45

**Comment by AmadeusW** [comment]
This is now implemented. I added the `NonBlockingCompletion` editor option

**Comment by ivanbasov** [comment]
@AmadeusW , we have 4 tests TestNoBlockOnCompletionItems1-TestNoBlockOnCompletionItems4. They failed (actually hung). Please take a look.
