### ISSUE TITLE
Intermittent NullReferenceException in CSharpDiagnosticAnalyzerApiUsageAnalyzer

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#29119]
**Version Used**: 
Microsoft.CodeAnalysis.Analyzers v2.6.1

**Steps to Reproduce**:

1. Clone https://github.com/WiseTechGlobal/WTG.Analyzers at commit 223095d2
2. Build from source

**Expected Behavior**:

No null reference exceptions in MS analyzers

**Actual Behavior**:

Sometimes null reference exception in MS analyzers

> CSC : error AD0001: Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\projects\wtg-analyzers\WTG.Analyzers.Test\WTG.Analyzers.Test.csproj]

**Comment by sharwell** [comment]
@jinujoseph Can you move this to dotnet/roslyn-analyzers

**Comment by jinujoseph** [comment]
This issue was moved to dotnet/roslyn-analyzers#1771
