### ISSUE TITLE
enable Filters_EmptyList* tests [Editor should take over these test scenarios, but we also need test-time discoverability & editing of filter state]

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#29110]
**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by dpoeschl** [comment]
Would Roslyn implementing the presenter be sufficient here?

**Comment by ivanbasov** [comment]
Currently, we do not have API (provided by VSSDK) to arrange those tests. Either tests should be done on the editor side or an API should be provided
