### ISSUE TITLE
Intellisense doesn't offer some extension methods in a netcoreapp2.0/netstandard2.0 project

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#29120]
**Version Used**: 
15.8.0 Preview 5.0

**Steps to Reproduce**:
I have an SDK project with
```xml
<TargetFrameworks>netstandard2.0;netcoreapp2.1</TargetFrameworks>
```
and I'm trying to use the `System.Net.Sockets.SocketTaskExtensions.SendAsync` extension methods which are available in both target frameworks.

**Expected Behavior**:
IntelliSense always offers those methods.

**Actual Behavior**:
When I configure the Editor to `netstandard2.0` (the left drop-down above the editor), then `SendAsync`'s behavior is weird:
- typing `socket.` opens IntelliSense and moving to `SendAsync` says there are four overloads (correct)
- typing `socket.SendAsync(` opens IntelliSense, but there's only one overload shown, the non-extension-method with the `SocketAsyncEventArgs` parameter
- typing `SocketTaskExtensions.` opens IntelliSense and moving to `SendAsync` shows a yellow exclamation mark noting that there are three overloads (correct), but that these are only available in `netcoreapp2.1` (wrong)
- typing `SocketTaskExtensions.SendAsync(` doesn't open IntelliSense.

In all cases, I can finish the `SendAsync` extension method call without the help from IntelliSense and there are no compilation errors.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
