### ISSUE TITLE
Microsoft.NetCore.Compilers packages do not support Arm64 runtimes

### ISSUE THREAD

**Issue by 4creators** [dotnet/roslyn#29126]
**Version Used**: `Microsoft.NetCore.Compilers` package v2.8.0

**Steps to Reproduce**:

1. Download package
2. Verify it's content which is missing support for `win10-arm64` platforms in `tools\bincore\runtimes\` while platform `win8-arm` is supported

**Expected Behavior**:

`win10-arm64` platform is supported

**Actual Behavior**:

`win10-arm64` platform is not supported

**Comment by pragmanomos** [comment]
I contacted Sam Harwell to understand whether this is being picked up or not.

**Comment by jaredpar** [comment]
The Microsoft.NetCore.Compilers package is deprecated as noted on it's nuget.org page. 

> Note: This package is deprecated. Please use Microsoft.Net.Compilers.Toolset instead

Support like this is not expected to occur in this package. Please use Microsoft.Net.Compilers.Toolset instead which is the newer package. 

Overall though the expectation is customers should not be regularly using any of these packages. These packages are meant for the .NET team to do hot patching of toolsets as well as to allow us to hot patch customers hitting critical issues. It is not meant as a general purpose distribution for the compiler. Customers should use the .NET SDK for that.
