### ISSUE TITLE
MSBuildWorkspace can't open a VS2017 .NetStandard v2 project

### ISSUE THREAD

**Issue by antonioxxl** [dotnet/roslyn#29121]
**Version Used**:
Visual Studio 2017 Version 15.7.6
Microsoft.Build (from Nuget) 15.7.179  

**Steps to Reproduce**:

1.  Open .netstadart project with MSBuildWorkspace 
2.  Subscribe to event WorkspaceFailed
3.  Have an Diagnostic message in failed event: 
_Msbuild failed when processing the file with message: The path is not of a legal form._

**Expected Behavior**:
The number of documents should be greater than 0 after execute method OpenProjectAsync.

**Actual Behavior**:

I have next code for open project with MSBuildWorkspace:

```
public WorkspaceGenerator(string absoluteProjPath)
{
      MsBuildWorkspace = MSBuildWorkspace.Create();
      MsBuildWorkspace.WorkspaceFailed += MsBuildWorkspaceOnWorkspaceFailed;
      Project = MsBuildWorkspace.OpenProjectAsync(absoluteProjPath).Result;
}

private void MsBuildWorkspaceOnWorkspaceFailed(object sender, WorkspaceDiagnosticEventArgs e)
{
      Console.WriteLine(e);
}
```

I trying to open next .csproj file (project reference also a netstandard2.0 projects):
```

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.5.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\YumaPos.Common.Infrastructure\YumaPos.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\YumaPos.FrontEnd.Infrastructure\YumaPos.FrontEnd.Infrastructure.csproj" />
    <ProjectReference Include="..\YumaPos.Packages.TimeZones.Infrastructure\YumaPos.Packages.TimeZones.Infrastructure.csproj" />
  </ItemGroup>

</Project>

```

After execution WorkspaceGenerator i have message in MsBuildWorkspaceOnWorkspaceFailed (path exists and valid):

_Msbuild failed when processing the file 'C:\Projects\dev\YumaPos-Server-WCF\Submodule.YumaPos.Shared\YumaPos.Shared.Infrastructure\YumaPos.Shared.Infrastructure.csproj' with message: The path is not of a legal form._

Also project doesn't have documents

**Comment by DustinCampbell** [comment]
To use `MSBuildWorkspace`, you must provide an instance of MSBuild that it can use. Unfortunately, with MSBuild 15.0, the MSBuild assemblies are no longer included in the GAC. So, you must either include all of the `Microsoft.Build.*` assemblies with your application, or use the `Microsoft.Build.Locator` package to find an instance of MSBuild on the current machine. For an example, see the project template in the Roslyn SDK for creating an application that uses `MSBuildWorkspace`: https://github.com/dotnet/roslyn-sdk/blob/master/src/Templates/VS2017/ProjectTemplates/CSharp/ConsoleApplication/Program.cs.
