### ISSUE TITLE
Native PDB writer incorrectly assumes UTF8 3 character max encoding

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#29130]
The native PDB writer has a quick check on name length that assumes UTF8 can only use three bytes per character.

``` csharp
            if (str.Length < maxLength / 3) //UTF-8 uses at most 3 bytes per char
            {
                return false;
            }
```

https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs#L1444

The UTF8 spec allows for four. 

https://www.fileformat.info/info/unicode/utf8.htm

**Comment by gafter** [comment]
When a Unicode code point is encoded in four bytes in UTF8, it results in two UTF16 "characters" (a pair of surrogates). So it is less than three to one.

**Comment by jaredpar** [comment]
Ah yes. Possibly just need to update the comment here. I think the logic itself is fine.
