### ISSUE TITLE
Add documentation/samples to guide correct implementation of stateful analyzers

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2914]
Analyzers that store mutable state, which is initialized, manipulated and consumed across actions need guidelines around:

1. State management: How do I define/manipulate state in my stateful analyzers? What should be the lifetime/cleanup strategy for resources allocated during my analysis? Does the read/write to my resources need to be thread-safe?
2. Ordering guarantees on analyzer actions: [This document](https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Analyzer%20Actions%20Semantics.md) has a detailed explanation about this, but probably needs to be surfaced in a more visible way through doc comments and/or sample code snippets.

**This issue tracks adding explicit documentation AND samples for the same.**

Following is my initial take on this, but should be refined and reviewed by @JohnHamby before adding it to our documentation. We **must** add code samples on the correct way to write such analyzers though.

1. State management:
    1. Lifetime of analyzer: State stored on fields of analyzer can live very long, as analyzer instances can live for whole lifetime of analyzer host (i.e. in IDE for entire VS session for VSIX based analyzers). Only state that should be stored as fields:

        1. Immutable data that is computed in Initialize and re-used across all actions, is independent of compilation/symbols/syntax etc. and is purely some analyzer specific data.

        2. Mutable data that is compilation/symbol dependent but expensive to re-compute for every compilation that an analyzer might execute on (say for typing scenarios in IDE). You should be very careful in how this is done, as you can end up leaking compilation/symbols. Conditional weak tables are probably needed for this to be done correctly. This should be avoided as much as possible.
    
    2. State corresponding to compilation/code blocks etc.: For stateful analysis, you must define a start action corresponding to the logical entity where you need stateful analysis. There are couple of recommended ways to then define/manipulate state:

        1. Locals defined in the start action: These are available to all the nested registered actions for the scope of analyzer execution on the corresponding logical entity.

        2. Define a new private nested type in analyzer that defines the nested actions, and the state can then be stored as fields on this type. Instantiate this type for every start action callback.

       Guideline here is to initialize state in the start action (or constructor of nested type for approach 2), manipulate it in the nested non-end actions, and finally use the accumulated state in the nested end action to report diagnostics.

2. Ordering guarantees: Nesting action registration is the best way to define your order-dependency on actions. You are guaranteed to have start actions run before any nested action, so this should be the most reliable implementation. However, as the semantics document suggests, we want to guarantee ordering for actions that logically belong inside an executable code block to run after code block start action, regardless of the point where syntax node actions were registered.

**Comment by JohnHamby** [comment]
These recommendations are good. I think we need a short tutorial on authoring analyzers that includes and expands on this information.

**Comment by mavasani** [comment]
@ManishJayaswal @srivatsn @JohnHamby I think we need this for 1.0 to ensure correct and functional stateful analyzers.

**Comment by mavasani** [comment]
Moving this to 1.0, please let me know if you disagree. Probably @JohnHamby would want to take this up. John, let me know if you need any helping hand here..
