### ISSUE TITLE
EnC allows adding explicit interface implementation methods

### ISSUE THREAD

**Issue by davmason** [dotnet/roslyn#29145]
[ENCMetadataCrashTest.zip](https://github.com/dotnet/roslyn/files/2267748/ENCMetadataCrashTest.zip)

**Version Used**: 
VS 15.8 Preview

**Steps to Reproduce**:

See attached project, the issue repros with a subclass where it implements interfaces defined in another module, then adds explicit implementations of methods with the same signature from two different interfaces.

1.	Set a breakpoint in Main
2.	Make sure string IConflict.Get() and string IConflict2.Get() are commented out in SubClass
3.	Start debugging
4.	Uncomment string IConflict.Get() 
5.	Step once
6.	Uncomment string IConflict2.Get()
7.	Step once more
8.	AV in RegMeta::PreSave

**Expected Behavior**:
Rude edit is reported and user cannot proceed debugging

**Actual Behavior**:
VS crashes

**Comment by tmat** [comment]
@ivanbasov Could you take a look? We need to detect that a method that is being added implements an interface method and report a rude edit.
