### ISSUE TITLE
Mechanism to annotate unconstrained type parameters

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#29146]
We don't allow `T?` when `T` is unconstrained. But we need some other mechanism that is equivalent.
One scenario is:
```C#
F<T>(T x, T y) where T : IEquatable<T>
{
    // guard x
    x.Equals(y) // this ought not to warn on argument `y`
}
```

Some proposed designs:
1. static inference
2. flow inference (current LDM principle, see `MakeArray` scenario)
3. modify the constraint `IEquatable<T>` with some annotation/attribute
4. modify the definition of `IEquatable`.

The latter would look like:
```C#
interface IEquatable<T>
{
    bool Equals(T /*annotation*/ other); // even if `T` were `string!`, we can compare to a `string?`
}
```
Note that the annotation must be enforced for implementers of this method (ie. you must null-check `other`).

There may be a need to place the annotation on a nested type parameter. But we'd need to identify some compelling scenario first.
```C#
interface I<T>
{
   void Method(List<T /*annotation */> list);
}
```

**Comment by jcouv** [comment]
I'll organize a discussion on attributes, which can include this topic. The last discussion with LDM floated the idea of using `[MaybeNull]` for this.

**Comment by jcouv** [comment]
LDM discussed this again and we are going to prototype `T??` (https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-11-25.md)

**Comment by cston** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/45993.
