### ISSUE TITLE
Test plan: null coalescing assignment `a ??= b`

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#29168]
Language proposal: https://github.com/dotnet/csharplang/blob/master/proposals/null-coalescing-assignment.md
LDM notes: https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-07-16.md
Implementation: https://github.com/dotnet/roslyn/tree/features/null-operator-enhancements

- [x] Check language version 8.0
  - [x] Upgrade Project available
- [x] Parsing
  - [x] parses regardless of language version
  - [x] has same precedence as simple assignment
  - [x] associativity
  - [x] `??=` is a token
- [x] `a ??= b` is an r-value of type `A`, even if `A` is nullable and `B` is not
- [x] `a` must be a reference type or nullable value type or unconstrained type parameter
- [x] Test is `a is null`, `operator==` is ignored
- [x] Conversions of `b` only; no conversions of `A`
  - [x] implicit conversion from `B` to `A` or `A0` (where `A` is `A0?`)
  - [x] implicit user-defined conversion from `B` to `A` or `A0`
    - [x] `operator` can be defined in either `A` or `B`
  - [x] `null` conversion
  - [x] `default` conversion
    - [x] test conversion of `default` is to `A` not `A0`; issue warning since conversion to `Nullable<A0>` was probably not intended
- [ ] `a` is an l-value and r-value
  - [x] by-val or `ref` local, possibly captured
  - [x] by-val or `ref` parameter, possibly captured
  - [x] writable field
  - [x] read/write property or readable `ref` property
  - [x] read/write indexer or readable `ref` indexer
  - [x] read/write COM indexed property
  - [x] read/write event
  - [x] `ref` returning invocation
  - [x] member of `dynamic` receiver
  - [x] `this` is not allowed, for `class` and `struct`
  - [x] pointers are not allowed
- [x] `b` is an r-value expression including
  - [x] by-val or `ref` local, possibly captured
  - [x] by-val or `ref` parameter, possibly captured
- [x] `a ?? b` is supported for unconstrained type parameters (no reference or value type constraints)
  - [x] `A` is an unconstrained type parameter and `B` is implicitly convertible to `A`, with result type `A`
  - [x] `A` is an unconstrained type parameter and `A` is implicitly convertible to `B`, with result type `B`
  - [x] `A` is an unconstrained type parameter and `B` is `dynamic`, with result type `dynamic`
- [x] `a ??= b` is supported for unconstrained type parameters (no reference or value type constraints)
  - [x] `A` is an unconstrained type parameter and `B` is implicitly convertible to `A`, with result type `A`
- [x] `await` is supported within `a` and `b`
  - [x] with side-effects in `a` and `b`
- [x] `ref`
  - [x] `ref a ??= ref b; // error`
  - [x] `ref a ??= b; // error`
- [x] `in` parameter: `void M(in object x) { }`
  - [x] `M(a ??= b); // ok`
  - [x] `M(in (a ??= b)); // error`
- [x] `a ??= throw expr` is not allowed
- [x] Val escape
  - [x] `Span<int>? a = expr; a ??= stackAllocIntoSpan;`
- [x] Flow analysis
  - [x] Variables definitely assigned in `a` are definitely assigned before `b` and after expression
  - [x] Variables only assigned in `b` are not definitely assigned after expression
  - [x] `out var` in `b` is definitely assigned in remainder of `b`, but not definitely assigned after `??=`
- [x] Lowering
  - [x] `a ??= b` is lowered to `tmpA ?? (tmpA = b)`
  - [x] Side-effects are executed exactly once for `a`, even if `a ??= b` is used as an expression
  - [x] Side-effects are only executed for `b` if `a` is `null`
- [x] SemanticModel
  - [x] `GetTypeInfo` includes the type and converted type of `b`
  - [x] `IOperation`
  - [x] CFG
- [x] IDE
  - [x] Auto-formatting does not add space between `??` and `=`

**Comment by cston** [comment]
cc @333fred

**Comment by 333fred** [comment]
Test Notes:
*  `Span<int>? a = expr; a ??= stackAllocIntoSpan;`
    * Does not get to the point of val escape, as `Span<int>?` produces an error during initial binding.

**Comment by 333fred** [comment]
The test plan has been completed.
