### ISSUE TITLE
DataTips don't work in MVC5 Web App (Razor cshtml)

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#2916]
1.  Create a new C# ASP.NET Web Application (MVC)
2.  Set a breakpoint in ViewStart.cshtml
3.  F5
4.  Hover mouse over a variable or property

**RESULTS:**
![after](https://cloud.githubusercontent.com/assets/6464209/7711434/6840adc8-fe1f-11e4-9f48-8e35ec55c8a1.png)

**EXPECTED RESULTS:**
![before](https://cloud.githubusercontent.com/assets/6464209/7711443/70156912-fe1f-11e4-8c5a-94092a9cfb47.png)

**Comment by KevinH-MS** [comment]
In ```VenusCommandFilter.GetDataTipText```, we only consider spans with Length 1 when mapping down from the data buffer to the subject buffer.  If I change the check to match spans with Length 0, everthing *seems* to work.  Investigating why the length of the Span is 0 instead of 1...

**Comment by KevinH-MS** [comment]
It is correct that the length of the Span should be 0.  The number of spans that we are passed as an argument should be 1.  I think the original author may have conflated the two...

**Comment by KevinH-MS** [comment]
Fixed with commit a143c9035b64507f28bbc0bea1f6c5cdc9392117.

**Comment by KevinH-MS** [comment]
@amcasey, could you verify this?  (did you have some simple MVC app that you created for testing?)

**Comment by amcasey** [comment]
I tried the templates under both Web and Cloud, just in case they were different.
