### ISSUE TITLE
Escape character classification needs to be bikeshedded.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#29173]
Original PR: https://github.com/dotnet/roslyn/pull/28927

We need to think through the appropriate colors here for light/dark/contrast etc.  Notable, whatever we come up with for the dark theme needs to be integrated into the VS build.

Note: this also needs to be done for regexes.

**Comment by jcouv** [comment]
Note: when the themeing work is done in VS, we probably won't need the `#define dark_theme` in `ClassificationTypeFormatDefinitions.cs` (see discussion https://github.com/dotnet/roslyn/pull/28927#discussion_r208749266 for more context)

**Comment by jcouv** [comment]
Tagging @jinujoseph to assign (this needs a VS change).

**Comment by jinujoseph** [comment]
resolved via [link](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/145745?_a=overview. )
