### ISSUE TITLE
need an option for output referenced assembly files to destination directory when build or publish a .netstandard project

### ISSUE THREAD

**Issue by chenyj796** [dotnet/roslyn#29175]
**Version Used**: 
Visual Studio 2017 15.7.4
**Steps to Reproduce**:

1. Create a .Net Standard project
2. Add Some NuGet package, such as Newtonsoft.Json
3. Publish the project, and will generate only a .nupkg file

**Expected Behavior**:
Output all referenced assembly files like .net core project, and a .nupkg file
**Actual Behavior**:
Only a .nupkg file.

**Comment by sharwell** [comment]
@jinujoseph Can you move this to SDK?

**Comment by jinujoseph** [comment]
This issue was moved to dotnet/roslyn-sdk#134
