### ISSUE TITLE
VS doesn't automatically save modified additional document

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#29185]
When an additional document is modified through a code fix/action, the document does not automatically save if the additional document is already open somewhere else. This is inconsistent behavior in VS since regular documents automatically save; for example, when the suppression file is modified, it automatically saves after modification even if already open.

**Steps to Reproduce**:

1. Have the additional document open in another tab in editor
2. Modify additional document through a code fix/action

**Expected Behavior**: Additional document will automatically save when modified.

**Actual Behavior**: Additional document is modified but does not automatically save -- user must save document themselves for changes to persist.

**Comment by sharwell** [comment]
It's my understanding that files are saved automatically if (and only if) at least one file impacted by the code action is *not* open in the editor. If only one file is modified and that file is open in the editor, I would not expect it to be saved automatically.

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
