### ISSUE TITLE
Incomplete to-do in SimplifyTypeNamesDiagnosticAnalyzerBase.cs

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#29184]
In the method TrySimplifyTypeNameExpression, there is an incomplete to-do on line 168:

https://github.com/dotnet/roslyn/blob/6028e95b6d8268decfc27754b0e8dcc70142a5c8/src/Features/Core/Portable/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs#L150

This is affecting the analyzer's ability to correctly report the name of the code style option when producing the diagnostic. My current project is working on a feature to configure severity level from editor which requires the name of the code style option.

**Comment by Youssef1313** [comment]
@mavasani Do you have some background on this?

This code still exists here:

https://github.com/dotnet/roslyn/blob/02aa5ba2d76195a2eba9dd3c90051cc8971201c0/src/Features/Core/Portable/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs#L183-L185

But almost all of the analyzers don't add options or languages to the properties bag.

The values are used here:

https://github.com/dotnet/roslyn/blob/02aa5ba2d76195a2eba9dd3c90051cc8971201c0/src/VisualStudio/Core/Def/PreviewPane/PreviewPaneService.cs#L95-L100

**Comment by CyrusNajmabadi** [comment]
Closing out as not-actionable righ tnow.
