### ISSUE TITLE
Do not get any code fixes when you highlight a parameter

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#29190]
1. Double-click on "value" to highlight it

``` C#
    class Program
    {
        public Program(string value)
        {

        }
    }

```

2. Ctrl+.

Expected:

![image](https://user-images.githubusercontent.com/1103906/43932028-2248014c-9c85-11e8-8956-e9e9603fd6ad.png)

Actual:

Nothing

**Comment by CyrusNajmabadi** [comment]
Yup.  Not good :)  Have create fix here: https://github.com/dotnet/roslyn/pull/29193

Definitely keep filing these situations where you think you have a reasonable selection/position, but the refactoring doesn't show up.

**Comment by davkean** [comment]
Yeah I filed a few more, I ran into most of these during a talk or preparing for a talk.
