### ISSUE TITLE
csc.dll code 139 error when building project on .NET Core 2.1.302 Ubuntu 16.04 ARM64

### ISSUE THREAD

**Issue by gauravagarwal28** [dotnet/roslyn#29194]
I have downloaded .NET Core SDK for linux ARM64 on my Jetson TX2 running ubuntu 16.04.

```
nvidia@tegra-ubuntu:~$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-arm64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
nvidia@tegra-ubuntu:~$ 

```

However I am unable to run any dotnet application (even the hello world example) on my Jetson TX2.

```
nvidia@tegra-ubuntu:~$ dotnet new console -o myApp --force
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on myApp/myApp.csproj...
  Restoring packages for /home/nvidia/myApp/myApp.csproj...
  Generating MSBuild file /home/nvidia/myApp/obj/myApp.csproj.nuget.g.props.
  Generating MSBuild file /home/nvidia/myApp/obj/myApp.csproj.nuget.g.targets.
  Restore completed in 1.58 sec for /home/nvidia/myApp/myApp.csproj.

Restore succeeded.
```
```
nvidia@tegra-ubuntu:~/myApp$ dotnet run
/usr/share/dotnet/sdk/2.1.302/Roslyn/Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code 139. [/home/nvidia/myApp/myApp.csproj]

The build failed. Please fix the build errors and run again.
```

I wish to build iotedge for Jetson TX2 and dotnet Core 2.1 is a dependency for the same.

**Comment by gauravagarwal28** [comment]
https://github.com/Azure/iotedge/issues/136

**Comment by jaredpar** [comment]
@gauravagarwal28 do you have a binary log of the build or a core dump you can share out here?

**Comment by gauravagarwal28** [comment]
This is my binary log file. I had to rename it with a .zip extension to upload here.

just rename the file from msbuild.binlog.zip to msbuild.binlog

[msbuild.binlog.zip](https://github.com/dotnet/roslyn/files/2296720/msbuild.binlog.zip)

**Comment by jashook** [comment]
@gauravagarwal28 I noticed something similar last week while doing work in dotnet/coreclr. Although the issue with 2.1 has not been understood I have had success running the 2.2 sdk/cli. The latest preview of 2.2 can be found https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.2.1xx/dotnet-sdk-latest-linux-arm64.tar.gz. If the link no longer works see: https://github.com/dotnet/core-sdk for more downloads.

**Comment by gauravagarwal28** [comment]
@jashook I'm trying to build iotedge for ARM64 which requires 2.1 sdk.
I'm not sure if using 2.2 will work for what I aim to do.

**Comment by gauravagarwal28** [comment]
@jaredpar I have seen this issue being encountered by a lot of people for ARM64.

https://github.com/dotnet/roslyn/issues/26505
https://github.com/dotnet/roslyn/issues/28038

A solution to this would be highly appreciated.

**Comment by jaredpar** [comment]
@gauravagarwal28 at this point ARM64 is still in beta. This is likely to be an issue with the runtime, not the compiler, given the scenario and new-ness of the runtime involved. I think this issue should be moved over to CoreClr where it can be looked at by runtime developers.

**Comment by gauravagarwal28** [comment]
Filed the same as per your suggestion on the coreclr repo too:

https://github.com/dotnet/coreclr/issues/19578

**Comment by jkotas** [comment]
Moved to CoreCLR
