### ISSUE TITLE
"Replace with method" only shows up if you are within the name of a property

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#29196]
Unlike "Convert to full Property", "Replace with method" only shows up if you are within the name of a property.

1. Highlight between the $

``` C#
    class Program
    {
        $public int Food$
        {
            get;
        }
    }
```

Expected: 
Replace to method to show
![image](https://user-images.githubusercontent.com/1103906/43941015-b3efb13c-9cb5-11e8-871c-b9d87de0b7e0.png)

Actual:
![image](https://user-images.githubusercontent.com/1103906/43941054-e9cb74bc-9cb5-11e8-9dae-d5d5480f2aaf.png)

**Comment by CyrusNajmabadi** [comment]
I think i agree with this.  I think we'll want to have a few concepts of what should be considered 'selecting a member'.  Those should include (but not necessarily be limited to):

1. Selecting the entire syntax node.
2. having hte cursor on the 'Name' portion of the node.
3. selecting the 'Name' portion of the node.
4. (new): Selecting an appropriate 'signature' of the node.  

So, in this case, you've selected the 'signature' of this property, and thus we should think the property was selected.  This would not apply, for example, if you selected ```public [|int|] Food``` or ```public int Foo { [|get;|] }```

**Comment by CyrusNajmabadi** [comment]
Ideally, we would make these into helpers, so we could reuse the same logic in applicable refactorings to get a more consistent experience.  Right now many refactorings write their own custom logic each time, leading to a veyr inconsistent experience wrt all of this stuff.

**Comment by sharwell** [comment]
Marking https://github.com/dotnet/roslyn/issues/29196#issuecomment-411992764 for a priority design review. An abstraction (helpers) means we can start the implementation and later tweak the helpers to match the final design. The main thing I'm looking for early is whether there are any cases that *shouldn't* fit the same pattern as everything else, because those cases would break if we took this approach.

**Comment by CyrusNajmabadi** [comment]
> Marking #29196 (comment) for a priority design review. An abstraction (helpers) means we can start the implementation and later tweak the helpers to match the final design. 

Agreed.  Maybe just have a couple of people go off and write up a set of rules with examples to help drive discussion?

> The main thing I'm looking for early is whether there are any cases that shouldn't fit the same pattern as everything else, because those cases would break if we took this approach.

In general, rules 1-3 work well for type-members *except* that for multi-decl-fields, you have to decide what selecting the whole member means.  i.e. ```[|int a, b|]```.

rule 4 seems like it would work well for many **members**, but we need to decide what 'signature' means.  For parameterized members, would it include parameters?  Woudl it include type parameters?  It should probably never include attributes.  etc. etc.

rule 4 is something we already have for a few **type-oriented** (i.e. classes/structs/interfaces) constructs, but even there we need to decide what it means.  Does it include type-parameters?  inheritance section?  constraints?

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/38166

![image](https://user-images.githubusercontent.com/4564579/76155992-a3f90680-60a8-11ea-90fb-a09cf7f0a6e6.png)

tested lots of combinations here and this is working well.
