### ISSUE TITLE
Editor Completion -- Properly support Microsoft.CodeAnalysis.Completion.EnterKeyRule instead of having VB language check [working except After Fully Typed Word]

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#29220]
See a comment by @CyrusNajmabadi https://github.com/dotnet/roslyn/commit/824a70331b26bcc8a6811773b1844aea939211dd#commitcomment-29837206

**Comment by dpoeschl** [comment]
It doesn't. Need to update `TryCommit` to check the option instead of do a VB language check.

**Comment by dpoeschl** [comment]
But be careful about the "After Fully Typed Word" option.

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
