### ISSUE TITLE
Variable scope computation is wrong when `o is string s == true` is used

### ISSUE THREAD

**Issue by SergeyTeplyakov** [dotnet/roslyn#29222]
**Steps to Reproduce**:

Here are two equivalent C# programs (the compiler generates exactly the same IL):

```csharp
static void PatternMatchingSample1(object o)
{
    if (o is string s)
    {
        // Everything is fine: s is defined
        Console.WriteLine(s);
    }
}

static void PatternMatchingSample2(object o)
{
    if (o is string s == true) // or o is string s is true
    {
        // Local variable might not be initialized
        Console.WriteLine(s);
    }
}
```

These two programs generate exactly the same IL but the **second version fails to compile** with 'Local variable 's' might not be initialized'.

The reason why I think it makes sense to support the other patterns is to allow this (inverted) case:

```csharp
static void PatternMatchingSample2(object o)
{
    if (o is string s is false)
    {
        return;
    }
    
    // Local variable 's' might not be initialized
    Console.WriteLine($"o is '{s}'");
}
```

IMO, ` if (o is string s is false)` is more readable than ` if (!(o is string)` but the case mentioned above fails to compile with the same reason: `s` variable might not be initialized.

**Comment by gafter** [comment]
This behavior is as specified in the C# language specification and therefore the compiler is behaving as required. The specification for `==` never produces "definitely assigned when true". If you'd like the specification to change, your suggestion/discussion belongs in the csharplang repo. I believe there are already one or two issues for this in that repo (but I'm too laze to look it up).
