### ISSUE TITLE
String Interpolation parses an expression as Text.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#29231]
**Version Used**: `Visual Basic Tools   2.9.0-beta8-63119-10`

**Steps to Reproduce**:

1. The is a repo of the issue. 
```VBNET
Class Example

            Public ReadOnly Property [End] As Integer

           Public Overrides Function ToString() As String
                Return $"{End.ToString()})"
            End Function

    End Class
```
The classifier / parser thinks the `End.ToString()` is text and not an expression.
2.  Now escape the `End` eg `[End]`
3.  Classified / Parsed correctly

I'd expect the expression to be parsed correctly with and error diagnostic (to indicate the identifier `End` could not be found.). A possible additional diagnostic could be possible, to indicate an unescaped keyword identifier usage.

**Comment by CyrusNajmabadi** [comment]
> I'd expect the expression to be parsed correctly

This is error code, so parsing it 'correctly' is somewhat ill defined.

> he classifier / parser thinks the End.ToString() is text and not an expression.

Correct.  It first sees the `{` and says "ok, i need an expression here".  It then sees `End` and goes "whoa... that's definitely not an expression.  Things are bogus here.  I'll stop tryying to parse out this expression and will just report a missing `}`".

At that point, it's back in the string.  so `End.ToString()` is just text up until it reaches the end of hte string or the next interpolation.

> (to indicate the identifier End could not be found.)

`End` is a keyword, not an identifier.

**Comment by AdamSpeight2008** [comment]
@CyrusNajmabadi 
I'm think that we should look ahead at the next token to see if it is qualifier token, eg `.` `!` , `?` .
If the next token is a qualifier,  consider the _keyword_ as an identifier and not a keyword
Continuing to parse as if it is an identifier. This would allow string interpolation to parse "correctly" in this case. Additionally we can then attach a diagnostic to `End` eg `'End' Keyword is being treated as and expression.`, which then permits a codefix to escape it. 

If the next token  isn't a qualifier then continue to parse as we currently do.
