### ISSUE TITLE
SDK path is non-configurable and always searched first for references on desktop

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#29252]
C# has a notion of "SDK path" which is really the runtime directory where the compiler is running. On CoreCLR this is null, because the runtime directory of CoreCLR doesn't have referenceable assemblies, but it's always present on desktop, including Mono. The SDK path is also always searched first for referenced assemblies, so bare references like "-r:System.dll" will always resolve to the SDK path on desktop. This is undesirable for two reasons:

1. The user may want to prefer a custom '-lib' directory for all references.
2. The behavior will differ when switching between Mono and CoreCLR or CoreCLR and the desktop CLR.

**Comment by jaredpar** [comment]
This amounts to adding a new option to the compiler: `sdkPath`.  This is already an option to the compiler at an API level, just not at the command line one. 

It does create one ambiguity: does the command line win over the value passed to the API? The answer seems to be yes given we have symetry with `baseDirectory` here and the command line parameter wins out in that case.

**Comment by RikkiGibson** [comment]
I can't find a command line switch for `baseDirectory` in CSharpCommandLineParser. Am I missing something?

**Comment by jaredpar** [comment]
There isn't a direct switch. The `/out` switch indirectly controls `outputDirectory` which is related to `baseDirectory`
