### ISSUE TITLE
Implicit line continuation should continue across comment-only lines

### ISSUE THREAD

**Issue by bandleader** [dotnet/roslyn#29257]
**Roslyn Bug, first discussed at https://github.com/dotnet/vblang/issues/183**

**Version Used**: 15.5.5.4

Implicit line continuation should continue across comment-only lines.
This allows multi-line comments.

**Steps to Reproduce**:

```vb
Dim x = {1, 2,
    'Comment here!
    'Even another line
    3}
```
**Expected Behavior**:
Should compile.
**Actual Behavior**:
Does not compile.

# Additionally: blank lines
In my opinion, it should similarly continue across blank lines, which allows for better spacing:
```vb
Dim x = {1, 2,

    'Some more values
    3, 4,

    'Even more values
    5, 6}
```

**Comment by jaredpar** [comment]
This looks like a language request though, not a compiler bug.
