### ISSUE TITLE
Discuss strategy for handling failures in IDE features

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#29262]
There's been discussion about this internally, and it's come up more acutely in https://github.com/dotnet/roslyn/issues/23887#issuecomment-412441521. Let's discuss this example as well as the general guidance / philosophy at our design meeting.

**Comment by sharwell** [comment]
:memo: Related to #29273

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
