### ISSUE TITLE
[BUG] Can't use left shift operator in XML doc comments

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/roslyn#29266]
**Version Used**: 
Visual Studio Professional 2017 Preview
Version 15.8.0 Preview 5.0

**Steps to Reproduce**:

1. Write code for a variable or method
2. Write a XML documentation (summary) to the method
3. Write a left shift operator into the XML documentation

**Expected Behavior**:
* A left shift (and right shift) operator should be accept inside the XML documentation and not parsed to a possible HTML tag

**Actual Behavior**:
* The left shift operator is interpreted as start signs of a HTML tag
* Hover on the variable or method don't show any information
![2018-08-14 07_59_54-webvis - microsoft visual studio preview](https://user-images.githubusercontent.com/17874713/44074234-227416c2-9f98-11e8-8609-493e90cf7eba.png)

**Current workaround**
* Replace the left shift operator with a word group
![2018-08-14 08_03_15-webvis - microsoft visual studio preview](https://user-images.githubusercontent.com/17874713/44074381-a437ed50-9f98-11e8-8c00-be8c62e876af.png)

**Comment by CyrusNajmabadi** [comment]
Use `&lt;`

This is an 'xml' doc comment. So the rules of xml apply here.

**Comment by sharwell** [comment]
@CyrusNajmabadi is correct. These characters need to be XML-escaped within an XML documentation comment.
