### ISSUE TITLE
Incorrect IDE0004 "Cast is redundant" with enum cast to int as dictionary key

### ISSUE THREAD

**Issue by ChaosinaCan** [dotnet/roslyn#29264]
**Version Used**: Visual Studio 15.7.6

**Steps to Reproduce**:

```C#
using System.Collections.Generic;
using Windows.UI.Xaml.Controls;

static class Example
{
    public static readonly Dictionary<int, string> Icons = new Dictionary<int, string>
    {
        [(int)Symbol.Accept] = "accept.png",
    };
}
```

**Expected Behavior**: Don't suggest removing the cast to int

**Actual Behavior**: Visual Studio suggests removing the cast to int, which results in a compile error.

**Comment by JoeRobich** [comment]
@dpoeschl  It is very similar to #22804. Removing the cast will break indexer access in both cases.

**Comment by JurjenBiewenga** [comment]
I'd like to take a stab at this one.

**Comment by jinujoseph** [comment]
Sure @JurjenBiewenga , go for it.

**Comment by jinujoseph** [comment]
thanks @JurjenBiewenga
