### ISSUE TITLE
IDE Code Fixes available via Error Window.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#29268]
It would be good to have code fixes available via the Error Window.
Eg Right Click in over and Error in the Error Window, 
![errorwindow_01](https://user-images.githubusercontent.com/900107/44096458-32f9c7ea-9fd3-11e8-9059-56b48f000599.png)
and have a sub menu `Code Fixes -> Escape Keyword`.

**Comment by markw-t** [comment]
@sharwell your approach definitely has some advantages - and as an added bonus, the error list already has the grouping features needed to make #1 happen.   Would just need a way to surface the fixers per grouping as you imply at #3 . Or maybe it could be as simple as a right click to fix. 

In my imagination my earlier approach was simply to use lightbulbs on each row as the preview opportunity, just inlining the preview one by one. But your way might be more efficient, at least reducing the "per diagnostic kind" load by grouping.

**Comment by CyrusNajmabadi** [comment]
Closing out.  This would need to be driven by platform if they want to support this.
