### ISSUE TITLE
Enable VSTHRD002 (Avoid problematic synchronous waits)

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#29271]
From #28781:

> Many of the violations reported by this can be fixed by a code fix, but the code fix is a bit buggy and I'm waiting for Microsoft/vs-threading#338 so it's easier to prepare the fixes.

**Comment by CyrusNajmabadi** [comment]
Subsumed by https://github.com/dotnet/roslyn/issues/29275
