### ISSUE TITLE
Enable VSTHRD200 (Use "Async" suffix for async methods)

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#29274]
From #28781:

> Will send a follow-up PR to enable this and fix all cases that aren't exposed (public API and/or IVT). It affected too many files to include here.

**Comment by CyrusNajmabadi** [comment]
@sharwell isn't this enabled for us?

**Comment by CyrusNajmabadi** [comment]
Subsumed in https://github.com/dotnet/roslyn/issues/29275
