### ISSUE TITLE
Enable VS-threading analyzers.

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#29275]
From #28781:

> This diagnostic is enabled, but its accuracy relies heavily on configuration files provided separately. The configuration for VSSDK types ships with the VSSDK analyzers, which are not yet enabled for the full Roslyn build.

- [ ]  VSTHRD010 (Invoke single-threaded types on Main thread)
- [ ] VSTHRD200 (Use "Async" suffix for async methods)
- [ ] VSTHRD103 (Call async methods when in an async method)
- [ ] VSTHRD002 (Avoid problematic synchronous waits)
- [ ] VSTHRD003 (Avoid awaiting foreign Tasks)

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we want to do this, it should be assigned to a dev/milestone.
