### ISSUE TITLE
VB compiler put generated anonymous types under the root namespace, not in the global

### ISSUE THREAD

**Issue by wschae** [dotnet/roslyn#2928]
Both Dev12 VB and Dev14 C# compiler put anonymous types under the global:

![2](https://cloud.githubusercontent.com/assets/4300700/7716388/78d7abf6-fe46-11e4-9aca-2b4697a008bf.png)

This is what EE and EnC expects but Dev14 VB compiler put anonymous types under the root namespace, which violates many assertions in EE and EnC. For example, #2775 (and internal bug 1170899):

![3](https://cloud.githubusercontent.com/assets/4300700/7716390/7c83fcaa-fe46-11e4-8aac-d296acb8e5ea.png)

**Comment by wschae** [comment]
@AlekseyTs Filed as suggested.

**Comment by AnthonyDGreen** [comment]
It appears to do this even if the actual anonymous type is generated from an expression in a class that escapes the root namespace through use of an explicit Namespace Global block.

**Comment by AlekseyTs** [comment]
@wschae Please verify
