### ISSUE TITLE
Audit uses of ContinueWith, etc.

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#29285]
From https://github.com/dotnet/roslyn/pull/28781#discussion_r208378244:

> Audit uses of `ContinueWith`, `SafeContinueWith`, `StartNew`, `SafeStartNew`, and `Task.Run` to identify cases where simpler approaches are viable

**Comment by CyrusNajmabadi** [comment]
Subsumed by https://github.com/dotnet/roslyn/issues/30463
