### ISSUE TITLE
Resolve inconsistent use of TestWorkspace.GetService<T>

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#29286]
From https://github.com/dotnet/roslyn/pull/28781#discussion_r208962835:

> Inconsistent use of `TestWorkspace.GetService<T>` and `TestWorkspace.ExportProvider.GetExportedValue<T>`

**Comment by CyrusNajmabadi** [comment]
Closing out.  If we want to do this, we should just do this.
