### ISSUE TITLE
Eliminate JoinableTaskFactoryTaskScheduler

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#29280]
From https://github.com/dotnet/roslyn/pull/28781#discussion_r208393493:

> Eliminate JoinableTaskFactoryTaskScheduler, or at least add it to the set of legacy thread switching types

Related to #29277

**Comment by CyrusNajmabadi** [comment]
Subsumed by https://github.com/dotnet/roslyn/issues/30463
