### ISSUE TITLE
Use pattern switch in SuppressFormattingRule.AddSpecificNodesSuppressOperations

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#29293]
This method is written as a series of if-then-else statements but it could instead be written as a pattern-based switch statement.

**Comment by gafter** [comment]
Similarly for IndentBlockFormattingRule.AddEmbeddedStatementsIndentationOperation

**Comment by CyrusNajmabadi** [comment]
Don't need tracking issue for this.
