### ISSUE TITLE
Create dark theme colors for Regex classification

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#29298]
Following up on https://github.com/dotnet/roslyn/pull/25517/files#r210114960

When that is done, the `#if dark_theme` section in `ClassificationTypeFormatDefinitions.cs` can be removed.

Relates to https://github.com/dotnet/roslyn/issues/29173 (create dark theme for classification of escaped sequences in string literals)

**Comment by jinujoseph** [comment]
resolved via [link](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/145745?_a=overview. )
