### ISSUE TITLE
Feature flag machinery improperly deleted. Please restore.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#29291]
The machinery for enabling language features by a feature flag was partially deleted in https://github.com/dotnet/roslyn/pull/22383. But this machinery was not designed just for IOperation, and its deletion from a parent branch prevents this code from being shared in child branches.

Please restore the machinery for enabling language features by feature flags (even if no specific features are enabled by this flag). This machinery belongs in a common parent branch.

/cc @mavasani @AlekseyTs @cston

**Comment by gafter** [comment]
@mavasani Can you please restore the deleted feature flag support?

**Comment by mavasani** [comment]
@gafter The feature flag code was removed as no code was exercising that path and for some cases it didn't make any sense to leave it (for example, what would [this switch](https://github.com/dotnet/roslyn/pull/22383/files#diff-a672b28d02b502f46551f7ece1c4c5d8L189) be without any experimental features?). Additionally, given that it was mostly deletion of code, the assumption was that bringing that code back up shouldn't be that hard - you can just copy most of the deleted code from that PR.

I can send out a PR to resurrect that machinery, but there will be no test or code path exercising it when the PR is submitted. I think it is instead better to have it as a separate first commit of the PR that exercises this code path and has unit tests. Let me know what if you still want me to create a separate PR for this.

**Comment by gafter** [comment]
The code is present specifically as a framework to use on experimental branches.  The switch you ask about would have only a default case, and probably a comment explaining what to do when adding an experimental feature.

The "first commit" of code exercising this code path would be on an experimental branch, and because it is not in master the work of adding it as a first commit would be work that would have to be repeated on every experimental branch.  Since we want to avoid repeated work, we should instead do the work once in the parent branch.

Yes, please create a PR to restore it.

**Comment by gafter** [comment]
Please target the `features/compiler` branch as the parent branch of your PR.
