### ISSUE TITLE
Close Milestones

### ISSUE THREAD

**Issue by shaggygi** [dotnet/roslyn#29308]
Now that 15.8 is released, can milestones [15.6](https://github.com/dotnet/roslyn/milestone/29), [15.7](https://github.com/dotnet/roslyn/milestone/32) and [15.8](https://github.com/dotnet/roslyn/milestone/33) be closed?

**Comment by shaggygi** [comment]
Looks like 15.6 & 15.7 are now closed.

**Comment by jinujoseph** [comment]
yes , 15.8 is still open for any servicing update.
