### ISSUE TITLE
Generate class ignores default namespace when creating folders

### ISSUE THREAD

**Issue by jods4** [dotnet/roslyn#29316]
**Version Used**: VS 15.8

**Steps to Reproduce**:

1. Create a .NET Core C# project with `<RootNamespace>XX.YY</RootNamespace>`
2. In `Program.cs` reference a non existing class in a sub namespace such as `new ZZ.Test()`.
3. VS suggests a Quickfix _Generate class Test_, use that.

**Expected Behavior**:
A new class `Test` is created in namespace `XX.YY.ZZ` inside file `ZZ/Test.cs`.

**Actual Behavior**:
Everything compiles and is alright but the file `Test.cs` is placed inside a subfolder `XX/YY/ZZ/Test.cs`.
If `XX/YY` is my root namespace, I expect the quickfix to not create that folder structure.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
