### ISSUE TITLE
Don't get offered to "resolve using" for extension methods that provide awaiters

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#29313]
Unlike normal extension methods (such as LINQ), you don't get offered to resolve a using if it provides a `GetAwaiter` method:

``` C#
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

internal class Program
{
    private static async Task Main(string[] args)
    {
        await TaskScheduler.Default; // <-- Expect to get offered to resolve using
    }
}

namespace Microsoft.VisualStudio.Threading
{
    public static class AwaitExtensions
    {
        public static CustomAwaiter GetAwaiter(this TaskScheduler scheduler)
        {
            return default(CustomAwaiter);
        }

        public struct CustomAwaiter : INotifyCompletion
        {

            public bool IsCompleted
            {
                get;
            }

            public void OnCompleted(Action action)
            {
            }

            public void GetResult()
            {
            }
        }
    }
}

```

Error:
```
Error	CS1061	'TaskScheduler' does not contain a definition for 'GetAwaiter' and no accessible extension method 'GetAwaiter' accepting a first argument of type 'TaskScheduler' could be found (are you missing a using directive or an assembly 
```

If I manually add the using, this code compiles.

**Comment by CyrusNajmabadi** [comment]
Seems like an interesting idea.  But also very low pri given how few people will be writing their own custom awaiters.

**Comment by davkean** [comment]
It's not the writing of custom awaiters, its the consumption. I ran into this one a lot with Micorosft.VisualStudio.Threading.dll.

**Comment by CyrusNajmabadi** [comment]
Sure.  That's what i was referring to  :).  The usage of custom awaiters is going to be orders of less magnitude than the usage of Linq for example.

**Comment by sharwell** [comment]
I'm with @davkean. This is super annoying with vs-threading, and hits virtually all cases where code needs to run as a background operation.

**Comment by gmori1018** [comment]
Does it still happen if you move the `CustomAwaiter` struct outside of `AwaitExtensions`?

**Comment by davkean** [comment]
No.

**Comment by CyrusNajmabadi** [comment]
I don't have any issue with this being done :)   It's just something low-pri to me.

**Comment by nick-morhun** [comment]
Has this been done? In VS 15.8.1 there is a suggestion in that case.
