### ISSUE TITLE
Don't suggest name changes on [DllImport] tagged methods; all this can do is break code.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29335]
Code:

private static class NativeMethodsMacOSX
        {
            [DllImport(&quot;libdl.dylib&quot;, CharSet = CharSet.Ansi, SetLastError = true)]
            internal static extern IntPtr dlopen(string path, IntPtr flags);
        }

IDE1006: These words must begin with upper case characters: dlopen

Heck no! dlopen() exists. Dlopen() doesn't. There is no point in requesting naming changes to functions tagged [DllImport]. This is really asking to change the name of a function in another project, usually a system library.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/309452/dont-suggest-name-changes-on-dllimport-tagged-meth.html
VSTS ticketId: 662738_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jhudsoncedaron** [comment]
For the record, I am the actual OP. This was migrated from https://developercommunity.visualstudio.com/content/problem/309452/dont-suggest-name-changes-on-dllimport-tagged-meth.html

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  I get no IDE suggestion to change this name.

**Comment by jhudsoncedaron** [comment]
@CyrusNajmabadi On checking  found it was fixed between me filing it and now.
