### ISSUE TITLE
Version used in VS 15.8 not available on NuGet (Breaks VS extension using MSBuildWorkspace)

### ISSUE THREAD

**Issue by alphaleonis** [dotnet/roslyn#29334]
It seems Visual Studio 15.8 is using version 2.9.0 of the Microsoft.CodeAnalysis assemblies. But these assemblies are not available on NuGet currently.

It seems that MSBuildWorkspace was moved to a new assembly in 2.9.0, which currently breaks one of our Visual Studio extensions. (Also don't know how to make an extension compatible with both 15.8 and older versions, but that may be a discussion for another topic I guess).

**Comment by alphaleonis** [comment]
As a though, could this have been avoided if `TypeForwardedToAttribute` had been applied for all types that were moved? And if so, shouldn't that be added?  (According to https://docs.microsoft.com/en-us/dotnet/framework/app-domains/type-forwarding-in-the-common-language-runtime)

**Comment by alphaleonis** [comment]
Oh, thanks... wasn't aware of the requirement to reference the assembly to which the type was forwarded. So I take it the breaking change was deemed necessary then, which of course is unfortunate for some of us.  
But any time frame for when the 2.9.0 versions will be pushed to NuGet so we can at least re-write the extension for 15.8 and get it working there?

**Comment by sharwell** [comment]
@alphaleonis Yes, the old API needed updates that involved signature changes, so even with type forwarding the compatibility would have broken. You can see how the signature change impacted a use of `OpenSolutionAsync` in DotNetAnalyzers/StyleCopAnalyzers@87c80dbdd549d41c2986cefdf44106e87fd4a184.

**Comment by jinujoseph** [comment]
also referred [here ](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_queries/edit/664422/?triage=true)

**Comment by Pilchie** [comment]
Tagging @Shyam-Gupta about the uploading timeframe.

**Comment by alphaleonis** [comment]
@sharwell Couldn't find much of a signature change in the commit you referenced, but I trust you there were some.  We'll just have to create a separate extension for 15.8 it seems as soon as version 2.9.0 has been released to NuGet. Thanks for the information though.

**Comment by paul1956** [comment]
The error message tells me I need to add a package reference to Microsoft.CodeAnalysis.Workspaces.MSBuild that doesn't exist and then says see go.microsoft.com/fwlink/?linked=874285 for instruction to use MSBuildWorkspace successfully but this is a 2017 article that does not mention MSBuild.

**Comment by alphaleonis** [comment]
@paul1956 It seems that they have now uploaded *some* of the 2.9.0 packages to NuGet, but the new Microsoft.CodeAnalysis.Workspaces.MSBuild package still seems to be missing. :(

**Comment by genlu** [comment]
Just uploaded `Microsoft.CodeAnalysis.Workspaces.MSBuild` to nuget.org. It is a new package, some extra steps were involved for publishing it, hence the delay. It should appear shortly.

**Comment by alphaleonis** [comment]
Thanks for the quick fix! :)
