### ISSUE TITLE
VisualBasicAddParameterCheckCodeRefactoringProvider exception & InfoBar when passing a lambda with incorrect number of parameters

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#29333]
Impacts both `VisualBasicAddParameterCheckCodeRefactoringProvider` and `VisualBasicInitializeMemberFromParameterCodeRefactoringProvider`

This is particularly painful/common because it occurs in the process of typing a valid invocation in which you're passing a lambda.

```VB
Class C
    Sub M(a As Action(Of Integer, Integer))
        $$
    End Sub
End Class
```

Delete the $$, and at that location we'll type an invocation of `M`. Type the following (you can allow brace completion to add the close parens or not, either way repros):
    
```VB
        M(Sub(x
```

Now the lambda being passed has too few parameters for the `Action(Of Integer, Integer)` being expected. This causes the InfoBar with this exception:

```text
System.InvalidCastException : Unable to cast object of type 'LazyNoneOperation' to type 'Microsoft.CodeAnalysis.Operations.IBlockOperation'.
   at Microsoft.CodeAnalysis.VisualBasic.InitializeParameter.InitializeParameterHelpers.GetBlockOperation(SyntaxNode functionDeclaration,SemanticModel semanticModel,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.InitializeParameter.VisualBasicAddParameterCheckCodeRefactoringProvider.GetBlockOperation(SyntaxNode functionDeclaration,SemanticModel semanticModel,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`3.ComputeRefactoringsAsync[TParameterSyntax,TStatementSyntax,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Notes:
- Never seems to repro when the lambda has 0 parameters
- Once the lambda has > 0 parameters, it seems to happen any time there's a parameter count mismatch

**Comment by dpoeschl** [comment]
Probably worth having an `IOperation` person take a quick look to see if it's indicative of a systemic problem. Or even whether the API will lead others into making this same usage mistake.

@mavasani @333fred Can either of you immediately tell if this is indicative of something wrong in `IOperation` itself, or just in the `InitializeParameterHelpers` usage of `IOperation`?

**Comment by jinujoseph** [comment]
cc @AlekseyTs

**Comment by dpoeschl** [comment]
(If we just want a targeted fix for _this_ case in lieu of some more structural change, I'd nominate this for the `Small Fixes` project.)

**Comment by mavasani** [comment]
In general, assuming that node with specific SyntaxKind maps to certain specific OperationKind or kinds, is not safe, especially for broken code. This refactoring seems to assume such a [syntax](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic.Features/InitializeParameter/InitializeParameterHelpers.vb,11) to [operation](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic.Features/InitializeParameter/InitializeParameterHelpers.vb,18) mapping, which seems to not hold for this broken code example. We should change the latter helper to be more conservative and attempt to cast to specific operation kinds, and bail out for unexpected operation kinds.

**Comment by dpoeschl** [comment]
I've put this in the `Small Fixes` project to handle the helper for these particular features like Manish has suggested.

**Comment by jeremyj563** [comment]
![image](https://user-images.githubusercontent.com/12220868/45094926-5d58d380-b0e2-11e8-8f0a-fa3a62cc7b1a.png)

Same issue here too

**Comment by dpoeschl** [comment]
@jinujoseph I've moved this into the `16.0` milestone. Built-in refactorings causing gold bars in a legal forward typing scenario should really be avoided. Let me know if you disagree at all with this milestone change.

**Comment by jinujoseph** [comment]
Also reported [here](https://developercommunity.visualstudio.com/content/problem/333752/visualbasicaddparametercheckcoderefactoringprovide.html) @chborl  can you validate the fix addresses this as well
