### ISSUE TITLE
why can't we use re-throw with the ternary operator?

### ISSUE THREAD

**Issue by a-a-k** [dotnet/roslyn#29343]
In C#7 we can write this:

`var a = 1 < 2 ? "true" : throw new Exception();`
why can't we to do rethrowing? For example:

```
try
{
    var er = 1/0;
}
catch (Exception ex)
{
    var a = ex.InnerException == null ? ex.Message : throw;
}  
```
As far as my understanding of standart using try-catch-throw, there is some «context» (contains throwed exception) in the try-catch block passed into throw as non-obviously argument. Isn't it?

The same question with the null-coalescing operator - `??`.

**Comment by CyrusNajmabadi** [comment]
This post is asking about a potential change to the language.  Requests for language changes should be filed at: dotnet/csharplang.

Thanks!

**Comment by jinujoseph** [comment]
This issue was moved to dotnet/csharplang#1789
