### ISSUE TITLE
Keyboard bindings to jump to the next outer and inner stack frames

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#29349]
It's common for me to pull up the stack frame window, bring the mouse over to the frame above or below the current frame, and double-click. It would flow better for me to stay at the keyboard and use keyboard shortcuts to jump to the next outer or next inner stack frame, maybe sometimes two or three times rapidly.

**Comment by jinujoseph** [comment]
moved to [debugger ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/665271)

**Comment by jnm2** [comment]
@jinujoseph It has moved to a place that I can't follow the discussion. Would I ping here for updates from time to time?

**Comment by jinujoseph** [comment]
@jnm2 , let me find a point of contact.

**Comment by r-ramesh** [comment]
@jnm2 , Currently you can navigate to the Stack frame drop down in the debug location toolbar through "Ctrl + 7" (on my VS installation) and then you can use the Up/Down arrow keys, Enter to set the current frame.
The downside of this currently is that Ctrl + 7 always ends up selecting the top most frame by default (not your current location). Does this help?

**Comment by jnm2** [comment]
@r-ramesh I'm based on the Visual C# keyboard preset and Ctrl+7 tries to navigate to bookmark 7, but Ctrl+D, C puts the focus in the call stack window without selecting the top stack from.

So to move in: Ctrl+D, C; Up; Enter.
To move out: Ctrl+D, C; Down; Enter.

It's not ideal but it does help! Thank you.
