### ISSUE TITLE
Add refactorings to split and merge nested if statements

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/roslyn#29347]
I frequently need to adjust complex if statements and miss some refactorings that could speed up this process.

For example I would like to be able to invoke a quick action on the first `&&` to split
```C#
if (con1
    && (con2 || !con3)
    && !con4)
{

}
```
into
```C#
if (con1)
{
    if ((con2 || !con3)
        && !con4))
    {

    }
}
```

And a refactoring on the nested `if` to do the reverse.

**Comment by jinujoseph** [comment]
Awesome, thanks @Neme12

**Comment by Neme12** [comment]
@jasonmalinowski Can you please close this? The PR was merged.
