### ISSUE TITLE
EnvDTE.CodeVariable.Attributes returns empty collection for VB.NET enum members (it works for C# enum members)

### ISSUE THREAD

**Issue by carlos-quintero** [dotnet/roslyn#29353]
Members of an enum are mapped to EnvDTE.CodeVariable. Calling EnvDTE.CodeVariable.Attributes returns an empty collection for this VB.NET code:

```
Enum Enum1
   <System.ComponentModel.Description("")>
   EnumMember1 = 1
End Enum
```
That's because the method:

[Public Overrides Function GetAttributeNodes(node As SyntaxNode) As IEnumerable(Of SyntaxNode)](http://source.roslyn.io/Microsoft.VisualStudio.LanguageServices.VisualBasic/a.html#13b757deda39757e)

of file CodeModel\VisualBasicCodeModelService.vb lacks the EnumMemberDeclarationSyntax case.

(for C#, the [public override IEnumerable<SyntaxNode> GetAttributeNodes(SyntaxNode parent)](http://source.roslyn.io/Microsoft.VisualStudio.LanguageServices.CSharp/a.html#0311a1745d048aed) method doesn't lack it)

**Comment by CyrusNajmabadi** [comment]
@carlos-quintero Would you like to submit a PR to fix that up?  That would be very helpful :)

**Comment by jinujoseph** [comment]
Fixed via https://github.com/dotnet/roslyn/pull/29374
Thanks @carlos-quintero
