### ISSUE TITLE
Add simplify conditional

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/roslyn#29350]
A refactoring to change `foo ? true : false` to `foo` and `foo ? false : true` to `!foo`

Similar to https://github.com/dotnet/roslyn/issues/28999

**Comment by jinujoseph** [comment]
cc @jcouv

**Comment by alrz** [comment]
A few other simplifications in this category:
```cs
return c ? true : m();
return c || m();

return c ? false : m();
return !c && m();
```
etc
