### ISSUE TITLE
Ensure we have tests that confirm the command line compilers can load analyzers compiled aganist older API versions

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#29367]
It seems we recently broke the generation of binding redirects in the compiler .exe.config files, which could have potentially broken the ability to load analyzers that were built against older versions of Roslyn. But nothing seemed to fail, which means either:

1. We broke them in a way that happened to still work, and that's interesting.
2. We don't actually have tests that ensure this, and that's interesting.

Chatting with @jaredpar he pointed out that our bootstrap build _should_ catch things like this. It is probably also worth having an explicit unit test in the standard test suite in case if we also break the bootstrap build.

**Comment by jaredpar** [comment]
> Chatting with @jaredpar he pointed out that our bootstrap build should catch things like this

The bootstrap build will catch cases like this but its effectiveness is limited by the runtime on the Jenkins machines. Most of them are running net471, and VSTS is running net472. That means netstandard2.0 is built in and we pretty much have automatic unification for any `System.*` facade used in the compiler. Hence all the bootstrap is, and really can, validate is 

- System.Collections.Immutable
- System.Refelction.Metadata
- Microsoft.CodeAnalysis.* 

Everything else will just work pretty much no matter how bad we screw it up.

**Comment by jaredpar** [comment]
Closing as this is sufficiently covered at this point. There is some sanity coverage in our own CI that ensures we can load older versions of analyzers. That will catch the majority of cases. Further we fairly aggressively deploy the compiler to environments where older analyzers are used and we get incidental coverage from that.
