### ISSUE TITLE
Add .editorconfig support for Visual Studio "Format Document Settings".

### ISSUE THREAD

**Issue by wanton7** [dotnet/roslyn#29364]
**Version Used**: Visual Studio 15.8.0

**Expected Behavior**:
I would expect to have .editorconfig support for this new feature, so that we can add it to source control and share settings with whole team.

**Actual Behavior**:
No .editorconfig support. We can't share settings easily through source control.

**Comment by sharwell** [comment]
@wanton7 I'm not sure what the request is for here. You should be able to configure formatting settings using .editorconfig already:
https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017#formatting-conventions

Can you provide a bit more information about what you were hoping to see?

**Comment by wanton7** [comment]
These settings
![formatdocumentsettings](https://user-images.githubusercontent.com/1009930/44548373-8f535880-a726-11e8-938a-d53e7309832b.png)

**Comment by sharwell** [comment]
Ah, no, those are intentionally left for users to configure in a manner that works best for them. Analyzers are able to validate that the state of code at a point in time (pull request, commit, or equivalent) adheres to a desired style, but developers may choose for themselves when and how to meet those requirements (automatic, manual, or some combination).

**Comment by sharwell** [comment]
:memo: We are working to improve the experience in the 16.0 release. While the configuration will still be per-user, it will be more flexible and some consideration is being given to sharing settings (though not sure where it will end up).

**Comment by wanton7** [comment]
Well I hope you don't end up somewhere where someone doing format document causes a huge diff because you can't share same settings :)

**Comment by sharwell** [comment]
> Well I hope you don't end up somewhere where someone doing format document causes a huge diff because you can't share same settings :)

I fully agree. This is a very important consideration for the ongoing design.
