### ISSUE TITLE
Regex error messages should be localized in a way that matches CoreFx's localization

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#29361]
For the regex parser, the loc strings were copied from: https://github.com/dotnet/corefx/blob/455f969867ee332bf1793cbf55db136ef7833087/src/System.Text.RegularExpressions/src/Resources/Strings.resx

This ensures that the IDE errors will be the same as the ones the user would get if they actually executed the regex.

It would be good if, when localized, we also did the same.  However, i have no idea where the actual localized versions of these strings are.  

--

@jcouv @dpoeschl to help drive :)

**Comment by CyrusNajmabadi** [comment]
@danmosemsft  @ViktorHofer  Do you know where the loc'ed versions of this file is: https://github.com/dotnet/corefx/blob/455f969867ee332bf1793cbf55db136ef7833087/src/System.Text.RegularExpressions/src/Resources/Strings.resx

?

**Comment by ViktorHofer** [comment]
we do not localize System.Text.RegularExpressions in .NET Core. Strings.resx is the only locale we do have. But do have locals in .NET Framework, I can dig them out if you need them?

**Comment by CyrusNajmabadi** [comment]
> But do have locals in .NET Framework, I can dig them out if you need them?

Could you clarify this a bit more?  If you don't localize the strings, then what would the locals be for? Thanks! :)

> we do not localize System.Text.RegularExpressions in .NET Core.

Interesting!  Well, that makes Roslyn's life easier i suppose...   Out of curiosity, why don't you localize them?

**Comment by danmosemsft** [comment]
@CyrusNajmabadi we have not gotten much feedback on it. Of course, these messages are not just for developers as in practice many apps display them to users - this is often necessary to show all necessary information such as the path in an IO exception - and for those apps the localization that .NET Framework did was probably valuable.

**Comment by CyrusNajmabadi** [comment]
The interesting thing here is that this probably means i shouldn't even make these localized strings within Roslyn. Otherwise hte loc team *will* localize them, and that will end up leading to a strange situation for users where Roslyn gives them a loc'ed message, but running the regex will give them an english message.  So i might just hardcode in the strings directly.

Do you have any thoughts on this @danmosemsft ?

**Comment by danmosemsft** [comment]
> strange situation for users where Roslyn gives them a loc'ed message, but running the regex will give them an english message. 

Presumably I'm already used to a mixture of localized VS with un-localized exception messages. I would think at least having the Roslyn messages localized would be an improvement for me, and be consistent if all other Roslyn originating diagnostics are already localized.

**Comment by dpoeschl** [comment]
Paging @tmeschter

**Comment by tmeschter** [comment]
@CyrusNajmabadi Localize them. Providing IDE tooling in the user's native language trumps concerns about consistency and accuracy. There's a fair chance the Loc team already has good translations for these strings, and even if not a localizable string can be improved over time.

**Comment by CyrusNajmabadi** [comment]
@tmeschter Works for me.  @danmosemsft You guys might want to consider loc'ing your regex strings.  They're already resources... so all that would have to happen would be getting loc to write the localizations (ideally in concert with Roslyn) and to then ship them.

Thanks!

**Comment by CyrusNajmabadi** [comment]
> When adding the strings to the .resx file please make use of the <notes> section for each string to provide guidance to the translator. At a minimum document each placeholder in the string. A brief explanation of where and how the string will be used would also be helpful.

Will do!

**Comment by danmosemsft** [comment]
> They're already resources... so all that would have to happen would be getting loc to write the localizations (ideally in concert with Roslyn) and to then ship them.

The "ship" them is probably most of the work -- it presumably means changes to build and packaging, scripts that upload the product, pages that link to downloads, etc. Anyway - it's something we're aware of.

**Comment by dpoeschl** [comment]
@tmeschter @CyrusNajmabadi If I understand correctly... we do want to localize these strings in Roslyn, and I have confirmed that Cyrus has indeed localized them with appropriate comments. So I think we're done here.

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Not quite.  The core concern here is the loc burden and deviations between roslyn's loc, and msdn's loc.  

i.e. i copied the english parts of msdn into roslyn.  The roslyn loc people likely loc'ed in as best they could.  but msdn's loc people will have done the same.  There's nothing really ensuring that hte roslyn loc matches well with the msdn loc.

That said... this probably isn't important enough to track.  if people complain about loc issues, we can drive that directly.
