### ISSUE TITLE
Inconsistent handling of escaped identifiers in <param> and <paramref>

### ISSUE THREAD

**Issue by ccmcgeek** [dotnet/roslyn#2936]
An extremely minor bug, but filing per @jasonmalinowski's request to be captured and triaged appropriately :smile:

## Environment
Windows 8.1 x64 with Media Center, fully patched.
Visual Studio Community 2015 RC, Version 14.0.22823.1 D14REL

## Repro Steps

In a new C# file, enter code:
```csharp
namespace Foo
{
    interface Bar
    {
        void Baz(object @event);
    }
}
```
Open a new line above method declaration and type `///` to trigger automatic xmldoc generation. Text is updated to this:
```csharp
namespace Foo
{
    interface Bar
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="@event"></param>
        void Baz(object @event);
    }
}
```
Note that hovering over `@event` *does not* raise a tooltip identifying this as a reference to `(parameter) object @event` in the same manner that hovering over the parameter identifier itself does, in the method declaration.

Begin entering this text as the contents of the summary: `Processes the <paramref name=""/>` and note that Intellisense suggests `event` as the contents of the `name` attribute.  Accept the suggestion (i.e. do not include the `@` escape).

Note that hovering over this `<paramref>` *does* yield a tooltip identifying the method parameter.  (Hideous fake cursor mine :stuck_out_tongue_winking_eye:)
![image](https://cloud.githubusercontent.com/assets/1765921/7719468/c9811e08-fe86-11e4-970c-f382ac307a24.png)

The behavior of Intellisense is consistent for both `<param>` and `<paramref>`.  If the `@` escape is included, no tooltip is shown.  If it is elided, a tooltip is shown.

## Observed Results
The behavior of the auto-generated xmldoc is inconsistent with the Intellisense behavior.  The auto-generated documentation includes the escape for the escaped identifier while Intellisense does not.  Further, intellisense offers tooltips only when not escaped.

## Expected Results
The behaviors should be consistent. Either the auto-generated documentation should elide the `@` escape, or Intellisense should include it.

I cannot find (or am not understanding :smile:) a definition of the correct behavior in Appendix A of the C# Language Specification, so I am not sure the correct outcome here other than to request that they be consistent.

Thanks!

**Comment by Pilchie** [comment]
@amcasey do you know what the compiler expects here?

**Comment by amcasey** [comment]
No @ escaping in crefs.  There are probably tests in CrefTests.cs.

**Comment by Pilchie** [comment]
Same in `<param name="" />` and `<see paramref="" />` ?

**Comment by amcasey** [comment]
I misremembered.  I believe crefs support verbatim identifiers and name attributes do not.
http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Parser/Lexer.cs,3757

**Comment by amcasey** [comment]
And here's the test I was thinking of: http://source.roslyn.io/#Roslyn.Compilers.CSharp.Symbol.UnitTests/DocumentationComments/ParameterTests.cs,257

**Comment by amcasey** [comment]
@ccmcgeek I couldn't find it in the spec either. :)  We worked backwards from the old implementation.

**Comment by ccmcgeek** [comment]
@amcasey Heh, fair enough!  Wasn't sure if there were crisper definitions to some of the terms that would have elsewhere distinguished an escaped identifier from otherwise. :)

**Comment by AArnott** [comment]
I'll close my duplicate bug #4456 but copy to here that Dev14 RTM behavior causes two compiler warnings to exist in the generated code:

> Warning	CS1572	XML comment has a param tag for '@o', but there is no parameter by that name
Warning	CS1573	Parameter 'o' has no matching param tag in the XML comment for 'GitExtensions.foo(object)' (but other parameters do)

**Comment by ccmcgeek** [comment]
Thanks @diryboy and @Pilchie & team!  It's very awesome to see the community approach is working for .NET!

**Comment by diryboy** [comment]
My first bug fix for Roslyn, people are nice, experience is good, yeah it's awesome!
