### ISSUE TITLE
Warning IDE0044 not valid for Fields

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29373]
Declaring in a VB class

Private HasFree() As Boolean

This is marked as IDE0044, but this is not valid if later onfor example a Redim is declared.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/312744/warning-ide0044-not-valid-for-fields.html
VSTS ticketId: 665072_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Added info:

IDE0044 is "Make field readonly".
The field here is  of type `boolean()` (it's not a func/sub).

**Comment by jinujoseph** [comment]
@mavasani can you check if this is already fixed

**Comment by mavasani** [comment]
The root cause is lack of IOperation support for Redim statement in VB: https://github.com/dotnet/roslyn/issues/30175

**Comment by mavasani** [comment]
I have a PR out to fix this and add IOperation support: https://github.com/dotnet/roslyn/pull/30217

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/30217
