### ISSUE TITLE
Update Microsoft.CodeAnalysis package to 2.9.0 is not straightforward. Missing MSBuildWorkspace

### ISSUE THREAD

**Issue by aka-STInG** [dotnet/roslyn#29375]
**Version Used**: 2.9.0

**Steps to Reproduce**:

Update package `Microsoft.CodeAnalysis` from 2.8.2 to 2.9.0

**Expected Behavior**:
Updating meta package should not break things.
**Actual Behavior**:
`MSBuilsWorkspace` not found
Workaround: Reference new package `Microsoft.CodeAnalysis.Workspaces.MSBuild` explicitly

**Comment by aka-STInG** [comment]
It would be nice to have TL;DR. According to this it should have been smooth process https://github.com/dotnet/roslyn/pull/21670#issuecomment-340312809.

Roslyn team should have a blog on msdn to announce such things and reasoning behind it.
Roslyn is a very powerful tool, but lack of documentation, breaking changes and issues on mac platform (although it mostly MSBuild related) really slows down its wide adoption.

**Comment by jmarolf** [comment]
@aka-STInG thanks! I'll see if we can get a blogpost out.  Regarding your other comments:

> lack of documentation

We have some docs here:
- [Roslyn Overview](https://docs.microsoft.com/dotnet/csharp/roslyn-sdk/)
- [API Documentation](https://docs.microsoft.com/dotnet/api/?view=roslyn-dotnet)

What more would you like to see in this area?

> breaking changes

Other than this incident, what other breaking changes have affected you?

> issues on mac platform (although it mostly MSBuild related)

We haven't solved using MSBuildWorkspace on .NET core but it should work under mono.  Can you elaborate what the other issues are?

**Comment by DustinCampbell** [comment]
Here's an article-in-progress that describes the issue: https://gist.github.com/DustinCampbell/32cd69d04ea1c08a16ae5c4cd21dd3a3

**Comment by DustinCampbell** [comment]
> According to this it should have been smooth process #21670 (comment).

Unfortunately, that PR contains a lot of discussion that diverged a bit.

**Comment by aka-STInG** [comment]
@jmarolf 

> Other than this incident, what other breaking changes have affected you?

>> issues on mac platform (although it mostly MSBuild related)

> We haven't solved using MSBuildWorkspace on .NET core but it should work under mono. Can you elaborate what the other issues are?

I was hitting same issue as described here
https://github.com/dotnet/roslyn/issues/20848 and here https://github.com/Microsoft/msbuild/issues/2554

This comment had the solution https://github.com/dotnet/roslyn/issues/20848#issuecomment-340294584
Now everything works. And big thanks for that solution!
But should it be more straight forward that you have to set `Environment.SetEnvironmentVariable("MSBUILD_EXE_PATH", msBuildDllPath);` on mac and
`Environment.SetEnvironmentVariable("VSINSTALLDIR", vs2017InstallDir);
 Environment.SetEnvironmentVariable("VisualStudioVersion", @"15.0");`
on windows for comlipation to actually work?

If you google this expressions they appear anywhere on the internet about solving issues with Roslyn, but in docs on github or in @DustinCampbell gist.

**Comment by CyrusNajmabadi** [comment]
> Now everything works. And big thanks for that solution!

Closing out as fixed.
