### ISSUE TITLE
Offer more alternatives for suppressing warnings

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#29395]
It would be nice if the suppress warning flyout had the following options:

- statement (in source today)
- in file
- in .ruleset

![image](https://user-images.githubusercontent.com/1640096/44330697-f5f71e80-a467-11e8-9b5f-ca539a456f9f.png)

**Comment by alrz** [comment]
[source-only attributes](https://github.com/dotnet/csharplang/issues/1452) (which could be applied to statements and expressions) is another option for this.

**Comment by sharwell** [comment]
> in file

This would be interesting. I've done this many times manually.

> in .ruleset

This one has a few additional considerations. It would handled in one way or another by the ongoing effort to simplify the specification of preferred styles in .editorconfig.

**Comment by JohanLarsson** [comment]
@sharwell .ruleset will be a pain with undo if it is not part of the solution.

**Comment by jcouv** [comment]
Another option worth considering is "in project" (and maybe even "in all projects").
![image](https://user-images.githubusercontent.com/12466233/45202000-47572a00-b22c-11e8-9a8a-5e894bb94561.png)

**Comment by sharwell** [comment]
> Another option worth considering is "in project" (and maybe even "in all projects").

This would likely be done either in the rule set or .editorconfig. Changes to that text field in project properties tend to do more harm than good to the project file structure.

**Comment by jmarolf** [comment]
@mavasani I believe this has been solved now correct?

**Comment by mavasani** [comment]
Yes, that is correct @jmarolf. I'll close out this issue.
