### ISSUE TITLE
Create Roslyn Diagnostic Analyzer that makes sure SupportedDiagnostics are used only in one place

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#294]
no one except AnalyzerManager should call analyzer.SupportedDiagnostics to make sure we cache them and only call it once. reasoning behind it is that the SupportedDiagnostics is a metadata and we should guard us from analyzer author mis-using it by us calling it only once.

**Comment by CyrusNajmabadi** [comment]
Closing out.  This doesn't seem actionable (and currently we do have multiple codepaths calling SUpportedDiagnostics).
