### ISSUE TITLE
AdditionalText.GetText return null in compiler, empty SourceText in IDE

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#29409]
**Version Used**: 
2.10.something

**Steps to Reproduce**:

1. Add the PublicAPI analyzer to a project via NuGet
2. Configure the PublicApi.txt to be a file that doesn't exist

**Expected Behavior**:
Same behavior when opening the project as on the command line.

**Actual Behavior**:
On the command line, you'll get an AD0001 because `GetText` will return `null` [here](https://github.com/dotnet/roslyn-analyzers/blob/af8c297b65db728debfda84555a515298a3ee9ab/src/Roslyn.Diagnostics.Analyzers/Core/DeclarePublicAPIAnalyzer.cs#L213).

In the IDE, nothing will happen, because the Workspace's [`AdditionalTextDocument.GetText`](http://source.roslyn.io/Microsoft.CodeAnalysis/AdditionalTextFile.cs.html#44) will return a SourceText that is empty.

**Comment by jaredpar** [comment]
Brief conversation indicated the IDE behavior is the outlier here.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
