### ISSUE TITLE
Inconsistencies in Analyzer+CodeFixProvider C# project template

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#2940]
Please address the following issues in the C# Analyzer+FixProvider project template:

* {AnalyzerName}.Test\Helpers\DiagnosticVerifier.Helper.cs, line 9: Unused namespace import for `System.Threading` can be removed.
* {AnalyzerName}.Test\Helpers\DiagnosticVerifier.Helper.cs, lines 27 + 28: Unused semi-constants `CSharpDefaultFilePath` and `VisualBasicDefaultFilePath` can be removed.
* {AnalyzerName}.Test\Helpers\DiagnosticVerifier.Helper.cs, line 51: DocComment refers to non-existing `spans` parameter.
* {AnalyzerName}.Test\Helpers\DiagnosticVerifier.Helper.cs, line 119: local variable `fileName` is never used. It can be removed, along with its containing `for` loop. 
* {AnalyzerName}.Test\Helpers\DiagnosticResult.cs, line 15: Argument in `ArgumentOutOfRangeException` ctor is a message, but for this overload it must be a parameter name instead.
* {AnalyzerName}.Test\Helpers\DiagnosticResult.cs, line 19: Argument in `ArgumentOutOfRangeException` ctor is a message, but for this overload it must be a parameter name instead.
* {AnalyzerName}.Test\Verifiers\DiagnosticVerifier.cs, line 2: Unused namespace import for `Microsoft.CodeAnalysis.CSharp` can be removed.
* {AnalyzerName}.Test\Verifiers\DiagnosticVerifier.cs, line 243: Placeholder `{0}` is missing in format string.
* {AnalyzerName}.Test\UnitTests.cs, line 7: Unused namespace import for `{AnalyzerName}` can be removed.

**Comment by bkoelman** [comment]
Some more:

* {AnalyzerName}.Test\Helpers\DiagnosticVerifier.Helper.cs, line 9: Unused namespace import for `System.Threading` can be removed.
* {AnalyzerName}.Test\UnitTests.cs, line 7: Unused namespace import for `{AnalyzerName}` can be removed.
* {AnalyzerName}.Test\Verifiers\DiagnosticVerifier.cs, line 2: Unused namespace import for `Microsoft.CodeAnalysis.CSharp` can be removed.

**Comment by bkoelman** [comment]
Additional suggestions for improvement:

* {AnalyzerName}\DiagnosticAnalyzer.cs, lines 19-22: Fields `Title`, `MessageFormat`, `Description` and `Category` can be made private.
* {AnalyzerName}\DiagnosticAnalyzer.cs, line 24: `Rule` field can be made readonly and private.
* {AnalyzerName}.Test\Helpers\DiagnosticResult.cs, lines 27-29: Fields `Path`, `Line` and `Column` can be made readonly.

**Comment by jmarolf** [comment]
Fixed with internal changeset 1474285

**Comment by jmarolf** [comment]
@shyamnamboodiripad could you please verify?

**Comment by lgolding** [comment]
As we discussed: Make Title/MessageFormat/Description/Category/Rule private.

**Comment by jmarolf** [comment]
Fixed with internal changeset 1483043

**Comment by lgolding** [comment]
Verified as fixed.
