### ISSUE TITLE
Inconsistencies in Analyzer+CodeFixProvider VB project template

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#2941]
Please address the following issues in the VB Analyzer+FixProvider project template:

* {AnalyzerName}.Test\Helpers\DiagnosticVerifier.Helper.vb, line 5: Unused namespace import for `System.Threading` can be removed.
* {AnalyzerName}.Test\Helpers\DiagnosticVerifier.Helper.vb, lines 22 + 23: Unused semi-constants `CSharpDefaultFilePath` and `VisualBasicDefaultFilePath` can be removed.
* {AnalyzerName}.Test\Helpers\DiagnosticVerifier.Helper.vb, line 109: local variable `fileName` is never used. It can be removed, along with its containing `for` loop. 
* {AnalyzerName}.Test\Helpers\DiagnosticVerifier.Helper.vb, line 112: local variable `Project` should be renamed to `project` to comply with naming guidelines. 
* {AnalyzerName}.Test\Helpers\DiagnosticVerifier.Helper.vb, line 145: local variable `Solution` should be renamed to `solution` to comply with naming guidelines. 
* {AnalyzerName}.Test\Verifiers\DiagnosticVerifier.vb, line 276: Placeholder `{0}` is missing in format string.
* {AnalyzerName}.Test\Helpers\DiagnosticResult.vb, line 13: Argument in `ArgumentOutOfRangeException` ctor is a message, but for this overload it must be a parameter name instead.
* {AnalyzerName}.Test\Helpers\DiagnosticResult.vb, line 17: Argument in `ArgumentOutOfRangeException` ctor is a message, but for this overload it must be a parameter name instead.

**Comment by bkoelman** [comment]
Additional suggestions for improvement:

* {AnalyzerName}\DiagnosticAnalyzer.vb, lines 8-12: Fields `Title`, `MessageFormat`, `Description` and `Category` can be made private.
* {AnalyzerName}\DiagnosticAnalyzer.vb, line 13: `Rule` field can be made readonly and private.
* {AnalyzerName}\DiagnosticAnalyzer.vb, line 26: Sub `AnalyzeSymbol` should be private.

**Comment by jmarolf** [comment]
Fixed with internal changeset 1474285

**Comment by jmarolf** [comment]
@shyamnamboodiripad could you please verify?

**Comment by jmarolf** [comment]
{AnalyzerName}\DiagnosticAnalyzer.vb, lines 8-12: Fields Title, MessageFormat, Description and Category can be made private.
{AnalyzerName}\DiagnosticAnalyzer.vb, line 13: Rule field can be made readonly and private.

I am not marking private because it can be useful to have tests verify these values.  If the analyzer author wishes them to be private they may do so

**Comment by lgolding** [comment]
As we discussed: Make Title/MessageFormat/Description/Category/Rule Private.

**Comment by jmarolf** [comment]
Fixed with internal changeset 1483043

**Comment by lgolding** [comment]
Verified as fixed.
