### ISSUE TITLE
How to get correct xml doc reference to generic type?

### ISSUE THREAD

**Issue by Przemyslaw-W** [dotnet/roslyn#29437]
I have instance of NamedTypeSymbol type, which is generic. How to get its xml doc reference? E.g. something like "T:MyNamespace.MyType{T}"? or at least "MyNamespace.MyType{T}"? Is there a public API available for this?

**Comment by sharwell** [comment]
StyleCop Analyzers starts by calling `SyntaxFactory.TypeCref`, and then uses the following method to transform it to a form that works inside XML:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/57821a1c4d014e8d80b3e236ff444e0e30d8a112/StyleCop.Analyzers/StyleCop.Analyzers/Helpers/XmlSyntaxFactory.cs#L126-L135

**Comment by Przemyslaw-W** [comment]
Thank you @sharwell . That helped.
