### ISSUE TITLE
OpenProjectAsync backwards compatible overload missing in 2.9

### ISSUE THREAD

**Issue by Ziriax** [dotnet/roslyn#29435]
In version 2.9, `OpenProjectAsync` has 3 arguments (the second being `IProgress`)

In previous versions, an `OpenProjectAsync` overload existed with just 2 arguments (the second being `CancellationToken`)

It would be a minor fix to add the same overload to 2.9, so upgrading is easier.

**Comment by jmarolf** [comment]
@Ziriax can you show the code where this breaks? `IProgress` and `CancellationToken` are optional arguments

**Comment by jmarolf** [comment]
@Ziriax I see, adding the parameter name would fix this.

```C#
Project project = await workspace.OpenProjectAsync(@"C:\source\myproj.csproj", cancellationToken: CancellationToken.None);
```

**Comment by DustinCampbell** [comment]
This was an intentional source break. We felt that this was acceptable because a source breaking change was already introduced by moving MSBuildWorkspace to a new assembly and NuGet package that could not be type-forwarded to.
