### ISSUE TITLE
Everytime I stop debugging any application (all of a sudden, today) Visual Studio 2015 has stopped working. Crashes and exists the application.

### ISSUE THREAD

**Issue by Yusha813** [dotnet/roslyn#29444]
**Version**: Visual Studio 2015 Version 14.0.23107.0

**Steps to Reproduce**:

1.  Create a **Console** application or _any_ application.
2.  **Run** the application
3.  Press **Stop Debugging**

**Expected Behavior**:Take me back to the Visual Studios IDE to look at my code

**Actual Behavior**: Microsoft Visual Studio 2015 has stopped working
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	devenv.exe
  Application Version:	14.0.23107.0
  Application Timestamp:	559b7ead
  Fault Module Name:	msdia140.dll
  Fault Module Version:	14.0.23918.0
  Fault Module Timestamp:	56eb9144
  Exception Code:	c0000005
  Exception Offset:	0002f607
  OS Version:	6.3.9600.2.0.0.16.7

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

In the Event Viewer I am getting two errors.

**1**. Faulting application name: devenv.exe, version: 14.0.23107.0, time stamp: 0x559b7ead
Faulting module name: msdia140.dll, version: 14.0.23918.0, time stamp: 0x56eb9144
Exception code: 0xc0000005
Fault offset: 0x0002f607
Faulting process id: 0xfcc
Faulting application start time: 0x01d43a39d547c74e
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Packages\Debugger\msdia140.dll
Report Id: 5b184dbf-a62e-11e8-8102-005056bc4d6c
Faulting package full name: 
Faulting package-relative application ID: 

**2.** Faulting application name: StandardCollector.Service.exe, version: 14.0.25123.0, time stamp: 0x56f2261c
Faulting module name: ntdll.dll, version: 6.3.9600.18821, time stamp: 0x59ba86db
Exception code: 0xc000000d
Fault offset: 0x0000000000102b50
Faulting process id: 0x1a30
Faulting application start time: 0x01d43a3ae584267c
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\DiagnosticsHub\Collector\StandardCollector.Service.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 0fb8b7ae-a62f-11e8-8102-005056bc4d6c
Faulting package full name: 
Faulting package-relative application ID: 

This has never happened before. I have no idea what is going on. 

**No**, I haven't recently done any VS updates.

**Comment by Yusha813** [comment]
In the Event Viewer I am getting two errors.

**1**. Faulting application name: devenv.exe, version: 14.0.23107.0, time stamp: 0x559b7ead
Faulting module name: msdia140.dll, version: 14.0.23918.0, time stamp: 0x56eb9144
Exception code: 0xc0000005
Fault offset: 0x0002f607
Faulting process id: 0xfcc
Faulting application start time: 0x01d43a39d547c74e
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Packages\Debugger\msdia140.dll
Report Id: 5b184dbf-a62e-11e8-8102-005056bc4d6c
Faulting package full name: 
Faulting package-relative application ID: 

**2.** Faulting application name: StandardCollector.Service.exe, version: 14.0.25123.0, time stamp: 0x56f2261c
Faulting module name: ntdll.dll, version: 6.3.9600.18821, time stamp: 0x59ba86db
Exception code: 0xc000000d
Fault offset: 0x0000000000102b50
Faulting process id: 0x1a30
Faulting application start time: 0x01d43a3ae584267c
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\DiagnosticsHub\Collector\StandardCollector.Service.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 0fb8b7ae-a62f-11e8-8102-005056bc4d6c
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Yusha813** [comment]
**UPDATE**: All of a sudden **magically** my issue was resolved by:

1. Creating and running a project on my local **Virtual Machine**.
2. Logging back into my **development server** and re-running the console application...

Weird.

**Comment by jinujoseph** [comment]
@Yusha813 as jhinder mentioned this doesn't look related to Roslyn and considering this has been resolved closing this issue.
