### ISSUE TITLE
Proposal: support attribute constraints on generic type parameters

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#2944]
This will make it possible to constrain in a flexible cross-cutting way without having a common base type or an interface. It would be quite beneficial for DSLs and AOP at least.

Example syntax:

``` csharp
public static class Sample
{
    public static string Validate<T>(T instance) where T : [Validatable]
    {
        //...
    }
}
```

It has been asked and upvoted on StackOverflow multiple times:

http://stackoverflow.com/questions/221687/can-you-use-where-to-require-an-attribute-in-c

http://stackoverflow.com/questions/4146674/using-attributes-for-generic-constraints

Being very specific about what is allowed and pushing as much as possible into compile-time validation is something in the spirit of C# and Roslyn. People definitely want more of different constraints: #158, #262. E.g. this suggestion would make it possible to define a constraint that would only allow not just any enum but a specific "family" of enums, since enums don't support inheritance and thus there is no possiblity to define a base type.

Could be considered while looking at all other attribute requests in #2136 as it could enhance/augment them, e.g. #117.

**Comment by KalitaAlexey** [comment]
@dsaf Could you write an example of using attribute constraint? Because I have no idea how to use methods of unknown type which implements my protocol

**Comment by dsaf** [comment]
@KalitaAlexey You would have to use reflection, as most of internal DSLs do.

**Comment by KalitaAlexey** [comment]
Reflection is slow. I think (templates|traits) would make much more effort

**Comment by dsaf** [comment]
@KalitaAlexey Performance of reflection is not necessarily a problem. Roslyn is using it, ASP.NET is using it, Entity Framework is using it, most of IoC containers are using it - all without any problems. Traits are more about defining behaviour rather than a contract. At the moment the closest thing is misusing interfaces AKA "using marker interfaces".

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

See also https://github.com/dotnet/roslyn/issues/18002 for a general discussion of closing and/or moving language issues out of this repo.
