### ISSUE TITLE
InteralsVisibleToCompletionProvider: Inserts wrong assembly name if name has dots

### ISSUE THREAD

**Issue by MaStr11** [dotnet/roslyn#29446]
**Version Used**: 
15.8.1
**Steps to Reproduce**:

1. Create a project with two or more assemblies and name the assemblies with dots
2. Insert an `InternalsVisible` attribute and enter some text with dots and place the cursor right to a dot
3. Invoke the InteralsVisibleToCompletionProvider and commit any assembly.

**Expected Behavior**:
The commited assembly name replaces the entire existing assembly name
**Actual Behavior**:
The commit inserts the new assembly name in the existing assembly name

Screencast of the failure:
![internalsvisibletobug](https://user-images.githubusercontent.com/24472128/44483100-6fe6fd80-a64a-11e8-9330-bed6ea9c933b.gif)

**Comment by jinujoseph** [comment]
closed via #29447
