### ISSUE TITLE
False positive IDE0047 : "Parentheses can be removed"

### ISSUE THREAD

**Issue by SirDuke** [dotnet/roslyn#29454]
**Version Used**: 
Microsoft Visual Studio Professional 2017 
Version 15.8.1
VisualStudio.15.Release/15.8.1+28010.2003
Microsoft .NET Framework
Version 4.7.03056
Installed Version: Professional

**Steps to Reproduce**:
` var c1 = (UIKind)(--i);`

**Expected Behavior**:
Parentheses required

**Actual Behavior**:
IDE0047: Parentheses can be removed

![2018-08-23_14-09-01](https://user-images.githubusercontent.com/426500/44522343-df0e3180-a6de-11e8-807e-558ca35dcece.png)

**Comment by Neme12** [comment]
tagging @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
indeed.
