### ISSUE TITLE
IDE0041 does not make any changes to the code

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#29455]
**Version Used**: VS 15.8.1, Roslyn 2.9.0.63208

**Steps to Reproduce**:

1. Paste the code below into a C# file.
2. Invoke Quick Actions at the marked location.
3. Select "Use 'is null' check." (IDE0041).

```c#
class C
{
    void M()
    {
        var x = $$ReferenceEquals(this, null);
    }
}
```

**Expected Behavior**: The code fix suggests to transform the call to `this is null`.

**Actual Behavior**: No code preview is shown. Invoking the action does nothing. The "Fix all occurences" window shows "No changes" and a black box.

![ide0041](https://user-images.githubusercontent.com/823398/44533203-47680d80-a6f5-11e8-87df-367bbda6329f.PNG)
![fao-empty](https://user-images.githubusercontent.com/823398/44533221-5484fc80-a6f5-11e8-97ed-335e568b83d1.PNG)

**Comment by NickCraver** [comment]
Is this fixed in 16.0 or 15.9? https://github.com/dotnet/roslyn/pull/29458 shows 16.0, but this shouldn't be a bug in 15.9 that lingers. It is a regression.

If it has to wait until 16.0, then IDE0041 should be disabled for 15.9 RTM.

cc @mavasani @CyrusNajmabadi

**Comment by Neme12** [comment]
That seems to be the way things are done. For example #30837, which stuck around for 15.8 has had a countless number of duplicate issues at this point, because it occurs in such a common scenario (I assume most projects would have a list initializer somewhere).

**Comment by Neme12** [comment]
This seems like it's not only less common but also has a lower impact because it just does nothing. It doesn't crash or generate invalid code. I don't think this will meet the bar for 15.9
