### ISSUE TITLE
Translation error from .net 4.6.1

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#29489]
It seems there are a large number of translation error(Chinese) from .net 4.6.1
For example:
ToolStripSplitButton.Enabled
获取或设置一个值，该值指示是否启用了 ToolStripItem 的父控件。 (.net 2.0--4.6)
获取或设置一个值，该值指示是否的父控件的 ToolStripItem 已启用。 (.net 4.6.1--4.7.2)

ToolStripSplitButton.SplitterBounds
获取 ToolStripSplitButton 的标准按钮和下拉按钮部分之间的分隔符的边界。 (.net 2.0--4.6)
获取的标准和下拉按钮部分之间的分隔符的边界 ToolStripSplitButton。  (.net 4.6.1--4.7.2)

IntelliSense gives us error translation for .net 4.6.1+

**Comment by jinujoseph** [comment]
cc @tmeschter to triage

**Comment by tmeschter** [comment]
@dotnet/localizers FYI, this bug report concerns the translation of the .NET Framework (specifically, the Chinese translation).
@jinujoseph This doesn't have anything to do with the dotnet/roslyn sources. After our Loc team has had a chance to look at it, we can resolve it as an external issue.
