### ISSUE TITLE
Possibly incorrect logic in IsMyNamespace extension method

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#2948]
BasicWorkspace\Extensions\SymbolExtensions.vb - (18, 112) : (containingNamespace.IsGlobalNamespace OrElse Object.Equals(containingNamespace, compilation.RootNamespace))
- I believe it should only check for RootNamespace, checking for global namespace when it doesn't match the root namespace is wrong.
- RootNamespace property is never a merged namespace, the input could be a merge namespace. It is not clear what behavior do we want in this case.

**Comment by Pilchie** [comment]
This is an internal extension method, and looking at the 3 callers, the outcome don't seem to warrant tightening this for 1.0.

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't had any issues here.  Unlikely to change this absent a real reported customer problem.
