### ISSUE TITLE
Out variable name suggestion needs work

### ISSUE THREAD

**Issue by wanton7** [dotnet/roslyn#29487]
**Version Used**: 
Visual Studio 15.8.1

**Steps to Reproduce**:

1.  Interface with bool TryGetSelectedWorkspaceForCurrentUser(out Division workspace); method

**Expected Behavior**:
Parameter name "workspace" to be suggested by Intellisense ~~and preferred over "division"~~.
Edit: Maybe preferred is not so good after all, lot of "value" parameter names out there.

**Actual Behavior**:
When I write that method only parameter name "division" is suggested by Intellisense.

**Comment by sharwell** [comment]
Moving this one to **help wanted**. A name from the parameter should be included in the suggestions, and filtering/selection will proceed on the rules already in place (i.e. no forced selection of this item, but could occur based on MRU).

**Comment by sharwell** [comment]
@mikadumont Can you add this to the list of items we're tracking for improving suggested names?

**Comment by NTaylorMullen** [comment]
Conclusion: Add the "out variable" parameter name to the completion list when consuming a method with an out param / using out var.

**Comment by CyrusNajmabadi** [comment]
This was fixed: 

![image](https://user-images.githubusercontent.com/4564579/199103454-10e1b076-2f83-43af-8be4-616ccb1b7641.png)
