### ISSUE TITLE
Intellisense partly assumes the wrong overload between Action<T> and Action<T1, T2> arguments

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#29493]
**Version Used**:
15.8.1

**Steps to Reproduce**:

1. Create an empty ASP.NET Core project
2. Add the `Autofac.Extensions.DependencyInjection` NuGet
3. In Program.cs, extend the `CreateWebHostBuilder method to
```
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .ConfigureServices(services => services.AddAutofac())
        .UseStartup<Startup>();
```
and open the Quick Actions on the `AddAutofac` method.

**Expected Behavior**:
IntelliSense should offer to add the relevant Autofac namespace.

**Actual Behavior**:
No quick actions are available.

**Details**:
IntelliSense cannot really decide which overload of the two available `ConfigureServices` it should use:
![image](https://user-images.githubusercontent.com/1947968/44585621-45fa1c00-a7ad-11e8-9977-12e5b33217c9.png)
The highlighted method between the source code and the peeked definition is the one with the `Action<IServiceCollection>` parameter, while the type of the `services` argument of the lambda is `WebHostBuilderContext`, which is clearly from the `Action<WebHostBuilderContext, IServiceCollection>` overload. Since `WebHostBuilderContext` doesn't have an `AddAutofac` extension method, I'm assuming this is the reason for missing out on the Quick Action.

When I add the namespace (`Autofac.Extensions.DependencyInjection`) manually, the error goes away and IntelliSense correctly shows `IServiceCollection` as the type for the `services` argument of the lambda.

**Comment by sharwell** [comment]
Loosely related to #29313

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
