### ISSUE TITLE
Unable to find output path of current compilation from analyzer

### ISSUE THREAD

**Issue by msbasanth** [dotnet/roslyn#29491]
**Version Used**: 
v2.6.0

**Steps to Reproduce**:

1. There is no API exposed for identifying OutputPath used by the current compilation session [from analyzer implementation].
2. Currently I tried reading CSPROJ for finding the OutputPath by checking the current PropertyGroup.
3. Need Platform used by the compilation to identify the PropertyGroup.
Observation:
CompilationOptions.Platform gives the PlatformTarget tag inside the PropertyGroup which may or maynot be matching Platfrom inside 'Condition'. So we cannot rely on CompilationOptions.Platform.

**Expected Behavior**:
An API directly gives which is the OutputPath used by the compilation.

**Actual Behavior**:
No API gives which is the OutputPath used by the compilation.

Regards
Basanth

**Comment by sharwell** [comment]
Analyzers are not expected to access the file system on which the project is located. In fact, analyzers are allowed to run on compilations that are not located on the file system at all, e.g. when operating on a Workspace that directly accesses data for a commit stored in Git without checking out the files locally.

@mavasani should be able to provide more clarification about the usage of these APIs.

**Comment by mavasani** [comment]
@msbasanth As mentioned by @sharwell, analyzers and compilations in general are neither tied to a file system nor a specific host (such as command line compiler or VS IDE live analysis). Can you please clarify why you need the file path? What is your analysis scenario?

**Comment by msbasanth** [comment]
This query is related to https://github.com/dotnet/roslyn/issues/23673

I could not retrieve the XML Documentation of an assembly from an analyzer for symbols from a custom assembly referenced. XmlDocumentationProvider is internal, and ISymbol.GetDocumentationCommentXml() returns string.Empty.

To read the XML Documentation from the Output directory, so that I can parse it for analyzing the XML documentation.

**Comment by mavasani** [comment]
@msbasanth I am going to close this issue as the workaround you are trying to get around #23673 is not supported. Please use  #23673 to track your required feature request.
