### ISSUE TITLE
Highlight usages of user-defined operators

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#29492]
We do have quick-info on operators, but making user-defined operators distinguishable in the source text would be a lot more useful to catch unintended usages (e.g. incorrect reference equality).

**Comment by sharwell** [comment]
❓ Can you clarify which of the following you are interested in?

1. A new classification type for user-defined operators that works with semantic highlighting (allowing users to define a style/color for these operators)
2. An expansion of the reference highlighting feature to highlight instances of the *same* user-defined operator within the context of a document where an operator is selected

**Comment by alrz** [comment]
I meant the first one here, I didn't find myself looking for the "same instance" highlighting on operators.

**Comment by JoeRobich** [comment]
implemented in https://github.com/dotnet/roslyn/pull/31231
