### ISSUE TITLE
SyntaxGenerator.AsPublicInterfaceImplementation doesn't set the accessibility to public in VB

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#295]
Repro:

```csharp
SyntaxGenerator generator = SyntaxGenerator.GetGenerator(document);
var method = generator.MethodDeclaration("Test");
method = generator.AsPublicInterfaceImplementation(method, generator.IdentifierName("IDisposable"));
var acc = generator.GetAccessibility(method);
```

In VB, the method gets the Implements clause but is not made public. In C#, the method is made public.

**Comment by AnthonyDGreen** [comment]
Is this because the VB default accessibility for methods is public? Should/does the generator always specify accessibility? Should this be configurable?

**Comment by mattwar** [comment]
The generator should be changing the method to public.

**Comment by mattwar** [comment]
The problem is the accessibility is only getting changed when the method/property is a statement, not a block.  The accessibility changing logic is in the wrong place.
