### ISSUE TITLE
Pending issues for DeadCodeAnalysis

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#29519]
Design issues that were brought up in https://github.com/dotnet/roslyn/pull/29511:

- [x] 1. Should we turn off the analyzers for named types which have `IInvalidOperation` in it's executable code? - _Current implementation of this analyzer does this. Should MakeReadOnly also be changed to be consistent?_
**Design decision: In general, it is better to have the analyzer ignore unrelated invalid operations, but given this analyzer operates purely on reference analysis, we cannot be sure which invalid operation can or cannot be related to symbol references. We will stick with the current approach of bailing out in presence of syntax/semantic errors.**
- [x] 2. Do we need a separate diagnostic ID and message for two cases handled the PR:
   1. Members with no read or writes: `Type '{0}' has an unused private member '{1}' which can be removed.`
   2. Only writes: `Type '{0}' has a private member '{1}' which can be removed as the value assigned to it is never used.`
_Current implementation of this analyzer has two separate rule IDs and messages._
**Design decision: Separate diagnostic IDs as they are different kind of issues.**
- [x] 3. How do we handle the code fix for case ii. above? Current implementation removes the declaration, but does not alter the references as it probably needs user action on whether to retain the assigned value computation or not. Also this is inline with the decision we made a while ago on remove unused parameters code fix. - _Current implementation has no code fix for case ii._
**Design decision: We did not discuss this in detail, but the general view is this can be done subsequently based on the user feedback, especially given there will still be large number of cases that cannot be covered. We will not tackle this right now.**
- [x] 4. Handle diagnostic + fix better for cases where member is only used in nameof/typeof/sizeof expressions. See comment https://github.com/dotnet/roslyn/pull/29511/files#r212735506 - _This is not relevant if we decide no code fix for 3._
**Design decision: Same conclusion as 3. above. We will not tackle this right now.**
- [x] 5. Tools/Options UI for rule configuration: This analyzer, and especially the rule ii. above without a code fix, is not a code style rule, but a code quality rule. What is the configuration story for such a rule, given we are likely to add more code quality rules in future as well?
   1. Create a new `Code Quality` page under `Text Editor -> C# -> Advanced`, which uses the same UI as the code style rules to allow users to configure both severity and preferences for such rules 
   2. Create a separate `Analysis` section in the `Text Editor -> C# -> Advanced` page, with check boxes for each code quality to rule to enable/disable the rule. Changing severity and/or preferences will need to happen through explicit edits in .editorconfig file.
   3. No configuration UI for such rules. User has to explicitly edit the team's .editorconfig for configuration.
**Design decision: We decided to go with option iii. Non-code style rules that do not need special options, but only severity configuration will be treated in par with third party analyzers/rules. If in future we get feedback about lack of clarity on how these can be configured, we can consider implementing option i. or ii.**

Below are the pending follow-up work items for the PR, not design issues:
- [ ] 1. Move code in Find-refs to use the new extension method `GetValueUsageInfo` added in the PR. See https://github.com/dotnet/roslyn/pull/29511/#discussion_r212735745
- [ ] 2. Handle private members referenced in documentation comments from different parts of compilation. See https://github.com/dotnet/roslyn/pull/29511#discussion_r213418852

**Comment by CyrusNajmabadi** [comment]
1. What about symbols that are referenced in XML?

This feature has a fix-all component.  And, even if it didn't, i strongly feel that it is broken if i run this feature and then:

1. end up with a compiler error due to the symbol *actually* being referenced in some way) or
2. end up with semantics changed due to the execution of the value of hte initializer (even if it is never read directly through the field).

Users *will* assume that we are telling them: hey... it is safe to remove this variable.  

If it is not actually safe, we should address that.  We should not assume users will run this expecting that they then have to go fix up code breaks, or that their code will now change meaning because it depended on things like initializer evaluation.

**Comment by mavasani** [comment]
Tagging @jinujoseph @kuhlenh to bring this up in IDE design meeting.

**Comment by CyrusNajmabadi** [comment]
I mostly agree.  Except for this part: 

> There cannot be a truly safe code fix here (except probably for the case where all the references are target of assignments with a constant value). The best we can do is to offer a refactoring that removes the declaration to introduce explicit compiler errors at the reference sites that need to be reviewed by the user, but this is likely to confuse the user more than aid in resolving their issue as you have already cited.

I think we can have a safe fix here for many cases, even without having to have constants involved.  For example, if i have:

```c#
int neverRead;
if (x.TryGet(y, out neverRead)) { }

// this can be replaced with:

if (x.TryGet(y, out _)) {}
```

Similary, if we see a variable written with a computed value, we can still likely remove the variable, but keep the computed value in source.  i.e.:

```c#
int neverRead = Computation();

// becomes
Computation();
```

We can enumerate these safe cases and we can provide a 'fix' for them that preserves semantics.  If we run into something that isn't in the enumerated safe cases, we do not offer a fix in *that* case.

**Comment by CyrusNajmabadi** [comment]
> Bucket (1) are the truly unused symbols, that meet the IDE definition for no references, are simple to comprehend for all end users and have a trivial code fix that removes the declaration.

Agreed.  IMO, we can even just break apart the PR now, have that feature alone and get it in yesterday :)

> I am wondering if we should change this feature implementation to the following:
> Use two separate diagnostic IDs and options for the two buckets.

Yes.  These are different enough and require such different handling that i think they should not be merged.

> Bucket (1) would use the existing diagnostic ID, option, terminology and code fix.

Yup.

> Bucket (2) would use a different diagnostic ID, option, terminology and have no code fix. 

As per my previous post, i think we can still have the code-fix for many cases.   That said, we may not have a *fix-all*.  Or, we only fix-all ones that are totally safe to remove because we know how to fixup all the point in the code where they are written, but not read.

> I am not sure what is the correct succinct terminology to convey members that have at least one or more references, but none of them affect or contribute to the runtime semantics of the program, suggestions welcome.

"X is only ever written, and not ever read.  It can be removed, but may require some manual changes to the code."

> Error scenarios: Bucket (1) diagnostics should never be reported in presence of errors. Bucket (2) diagnostics don't need to take error cases into consideration as we already have one or more references to the symbol, and there is no code fix or fix all to potentially lead to silent code breaks.

As i think Bucket2 may have fixes, i think we need to take error cases into account.

**Comment by mavasani** [comment]
@CyrusNajmabadi I understand your view about possibility of providing safe semantic preserving code fixes for Bucket (2) from my original comment. However, I feel this is likely to do more harm then help for the user code. For example,

```
// _neverRead is a field
_neverRead = Computation();

// becomes
Computation();
```

It is likely that the `Computation` here is an essential piece of code that needs to run for correct execution. It is equally likely that the computation is a redundant code and hence a performance overhead, especially given the assignment is made to a field that is never read. Not providing an explicit code fix forces the client to look at each reference and determine if the assigned value computation is dead code that can be deleted or must be retained in code without requiring to store the result into a field.

Regardless, of what we decide here, I am going to target my current PR to implement the things we agreed upon:
1. Implement diagnostic + code fix + option for Bucket (1)
2. Implement a separate diagnostic + option for Bucket (2), with no code fix or refactoring for now.

**Comment by CyrusNajmabadi** [comment]
> t is likely that the Computation here is an essential piece of code that needs to run for correct execution. It is equally likely that the computation is a redundant code and hence a performance overhead, especially given the assignment is made to a field that is never read. Not providing an explicit code fix forces the client to look at each reference and determine if the assigned value computation is dead code that can be deleted or must be retained in code without requiring to store the result into a field.

@mavasani That's a very interesting point.

I'm on the fence here.  IMO, saying we won't help fix things because people need to go manually examine all the cases seems overly nanny-ish to me.  I'd prefer to just provide the fix and allow people to put in whatever level of consideration is normal for them when making any code changes.  I think it's sufficient to have this be a different ID/message to convey to the user the situation.  i.e. this will not be "this symbol is never references and can be safely removed".  it will be "this symbol is only ever written to.  It can be removed, but code should be audited for potential performance problems." :)

I also think this stuff will normally show up the moment someone looks at their code diff.  

> Regardless, of what we decide here, I am going to target my current PR to implement the things we agreed upon:

Note: '1' sounds good to me.  

'2' can be done, but we'll need a way of presenting this to the user in Tools|Options.  Since this is purely an analyzers, with no fixes, and is definitely *not* 'code style': it seems like the right location is next to this

![image](https://user-images.githubusercontent.com/4564579/44676261-9fe62600-a9e7-11e8-8df5-97f73e5d6b0f.png)

We could even break this out into its own "Analysis" section, or something like that.

**Comment by mavasani** [comment]
> '2' can be done, but we'll need a way of presenting this to the user in Tools|Options. Since this is purely an analyzers, with no fixes, and is definitely not 'code style'

@CyrusNajmabadi I believe that we are likely going to add more 'Code quality' analyzers in the IDE, which identify performance or subtle functionality issues, which likely will not have a code fix. These will need to have a UI similar to the Code style options, as we want to enable users to configure severity and preference and also see code snippets/description regarding the analyzer in a pane below it - a check box will not be sufficient. We will need to design the correct Tools|Options location for these, likely a 'Code quality' section under C# and Basic or a separate section under C#|Advanced as you mentioned. For now, I am going to keep this in Code Style alongside the remove unused members option from '1', and file a separate issue to move it to the correct location. I will tackle that issue as soon as this PR goes in. Does that sound reasonable?

**Comment by mavasani** [comment]
Actually, I see your point @CyrusNajmabadi. Retaining '2' as a code style option, even temporarily, would mean adding a new code style option [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeStyle/CodeStyleOptions.cs,203) and defining a editorconfig code style option name and location. I will take the easier route as per your original suggestion and add a temporary checkbox in the C#|Advanced page, and file an issue to decide on the correct option design.

**Comment by CyrusNajmabadi** [comment]
> Does that sound reasonable?

Yes, if this is true: 

> I will tackle that issue as soon as this PR goes in.

:D

**Comment by CyrusNajmabadi** [comment]
>@CyrusNajmabadi I believe that we are likely going to add more 'Code quality' analyzers in the IDE, which identify performance or subtle functionality issues, which likely will not have a code fix. These will need to have a UI similar to the Code style options, as we want to enable users to configure severity and preference and also see code snippets/description regarding the analyzer in a pane below it - a check box will not be sufficient. We will need to design the correct Tools|Options location for these, likely a 'Code quality' section under C# and Basic 

Agreed.  Given the need for a preview, i think we need new UI.  We can reuse the actual WPF primitives, but i don't think we should hijack "Code Style".

**Comment by CyrusNajmabadi** [comment]
> and add a temporary checkbox in the C#|Advanced page, and file an issue to decide on the correct option design.

Sounds good.  When we add that, we can then add that "check my format string" option there.  I love the idea of calling it "code quality" as opposed to "style".  quality and style are very different things, and not conflating them would be good (even if under the covers tehy share so much infrastructure).

**Comment by mavasani** [comment]
@CyrusNajmabadi Actually, I am going to keep it even more simpler to avoid any temporary UI piece or options/settings getting checked in - I am going to leave the code quality diagnostic under '2' to be `IsEnabledByDefault = false` from the DiagnosticDescriptor ctor, and enable it only when we have designed the user experience.

**Comment by CyrusNajmabadi** [comment]
Works for me.  Let me know when you want another review.  And thanks for all the discussion!

**Comment by mavasani** [comment]
@CyrusNajmabadi @sharwell I have updated the first comment in this issue with the design decisions from today. Primarily, we will stay with the current implementation, and add features/configuration UI based on user feedback.

I am going to work on a PR that does the following:
1. Enable the rules be default
2. Remove all the workaround/hacks for disabling the rules for product and enabling for tests.
3. Address offline feedback from @sharwell about avoiding deriving the tests from `TestBase`.
4. Separate out the pending non-design related work items from first comment into separate issues.

Let us know if you have any pushback. Thanks again for reviewing the PR and design discussions!

**Comment by CyrusNajmabadi** [comment]
Looking now :)

**Comment by CyrusNajmabadi** [comment]
Just to check:

> Design decision: We did not discuss this in detail, but the general view is this can be done subsequently based on the user feedback, especially given there will still be large number of cases that cannot be covered. We will not tackle this right now.

Stated in other terms: We will notify the user about fields that never read.  However, we will provide no fix at all for this.  It's up to the user to determine what they should do about it.

Is that correct?

**Comment by mavasani** [comment]
> We will notify the user about fields that never read. However, we will provide no fix at all for this. It's up to the user to determine what they should do about it.

That is exactly correct.

**Comment by CyrusNajmabadi** [comment]
I'm 100% ok with the updated design notes.  Let me know if/when you'd like the feature code reviewed.

Thanks!

**Comment by mavasani** [comment]
Thanks @CyrusNajmabadi - I will work on the PR this week and tag you and @sharwell for review.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement/feedback.
