### ISSUE TITLE
c# release optimization changed behavior and removes in if clause even if it has side effects

### ISSUE THREAD

**Issue by noamarbel** [dotnet/roslyn#29524]
There is a difference in behavior between .Net 3.5 and 4+.
The code:
```C#
private int myVar;
        static void Main(string[] args)
        {
            var n = new Program();
            n.TestShortCircuit();

            Console.ReadKey();
        }

        private void TestShortCircuit()
        {
            Console.WriteLine("Starting");

            object foo = null;
            foo = TestFunc();

            if (foo == null)
            {
                Console.WriteLine("In If");
            }

            Console.WriteLine($"Done {myVar}");
        }

        private bool TestFunc()
        {
            Console.WriteLine("In Test Func");
            myVar = 1;
            return true;
        }
```

Output in debug:
```
Starting
In Test Func
Done 1
```

Output in Release .Net 3.5
```
Starting
In Test Func
Done 1
```

Output in Release .Net 4.0 and up
```
Starting
Done 0
```
So it looks like the compiler first in-lines the call to `TestFunc()` and then sees that a bool can never be null, so the function never gets called, even though it has side effects (or is it affects?)

Thanks.

**Comment by svick** [comment]
I can't reproduce this when compiling with VS 2017 15.8.1 and running on .Net Framework 4.7.2. What compiler are you using? What version of .Net Framework are you targeting and what version are you actually running on?

**Comment by jaredpar** [comment]
> There is a difference in behavior between .Net 3.5 and 4+

If changing the runtime changes the behavior of the program then it is likely a runtime issue, not a compiler one. 

> So it looks like the compiler first in-lines the call to TestFunc()

The C# compiler doesn't inline calls.

**Comment by noamarbel** [comment]
I am no longer able to reproduce this either. Not sure what had changed.
