### ISSUE TITLE
System.ComponentModel.TypeDescriptor.GetProperties(codeElement) doesn't return additional properties of EnvDTE80 code elements as in VS 2013

### ISSUE THREAD

**Issue by carlos-quintero** [dotnet/roslyn#2952]
When you use the file code model (EnvDTE.ProjectItem.FileCodeModel) from a package and you call System.ComponentModel.TypeDescriptor.GetProperties(codeElement) you get less properties in VS 2015 compared with VS 2013. 

Consider a package with this code:

        private void MenuItemCallback(object sender, EventArgs e)
        {
           EnvDTE.DTE dte;

           dte = base.GetService(typeof(EnvDTE.DTE)) as EnvDTE.DTE;

           ShowCodeElements(dte.ActiveDocument.ProjectItem.FileCodeModel.CodeElements);
        }

      private void ShowCodeElements(EnvDTE.CodeElements codeElements)
      {
         System.ComponentModel.PropertyDescriptorCollection propertyDescriptorCollection;
         EnvDTE.CodeNamespace codeNamespace;
         
         foreach (EnvDTE.CodeElement codeElement in codeElements)
         {
            switch (codeElement.Kind)
            {
               case EnvDTE.vsCMElement.vsCMElementNamespace:

                  codeNamespace = (EnvDTE.CodeNamespace)codeElement;
                  ShowCodeElements(codeNamespace.Members);
                  break;

               case EnvDTE.vsCMElement.vsCMElementClass:

                  propertyDescriptorCollection = System.ComponentModel.TypeDescriptor.GetProperties(codeElement);
                  System.Windows.Forms.MessageBox.Show(propertyDescriptorCollection.Count.ToString());
                  break;
            }
         }
      }

And run it against this code sample:

namespace N1
{
   class C1
   {
   }
}

In VS 2013 you get 32 properties for the class code element. In VS 2015 you get only 25 properties.

This is because in VS 2013 the code element is considered an EnvDTE80.CodeClass2 (which has 32 properties) while in VS 2015 is "only" considered an EnvDTE.CodeClass (which has 25 properties). This breaks extensions which try to get properties that appear only in EnvDTE80.CodeClass2 (such as ClassKind, InheritanceKind, etc.) in that scenario.

It also happens with other code elements that have representation in the EnvDTE80 namespace, such as EnvDTE.CodeProperty2 / EnvDTE.CodeFunction2 (OverrideKind property), etc.

**Comment by Pilchie** [comment]
Can you investigate?  I know we do implement CodeClass2 and friends, (see http://source.roslyn.io/Microsoft.VisualStudio.LanguageServices.Implementation/R/11125c075c08e894.html) for example, but for some reason TypeDescriptor doesn't see those :frowning:

**Comment by DustinCampbell** [comment]
Hmmm... yeah, I'll take a look.

**Comment by carlos-j-quintero** [comment]
@Pilchie @DustinCampbell It also happens with EnvDTE.ProjectItem.FileCodeModel ( EnvDTE80.FileCodeModel2). FWIW, the bug has an easy workaround, so it is not required a fix for RTM if you feel it is risky.

**Comment by DustinCampbell** [comment]
The issue here is that the ```[ComDefaultInterface]``` attribute on the various CodeElements specifies the wrong interfaces -- e.g. EnvDTE.CodeClass rather than EnvDTE80.CodeClass2.

**Comment by DustinCampbell** [comment]
Fixed! :smile:

**Comment by carlos-quintero** [comment]
Great, thanks!
