### ISSUE TITLE
VB: Indenting for type parameters should work the way it does for normal parameters.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#29521]
**Version Used**: 

Visual Studio Community 2017 v15.5.6

**Steps to Reproduce**:

Start with the following code:

```vb
Public Module Module1
  Private Class CFoo(Of TOne As Class, TTwo As Class, TThree As Class)
  End Class

  Public Sub Main()
  End Sub

  Private Sub SomeLongMethodNameHere(ArgOne As String, ArgTwo As String, ArgThree As String)
  End Sub
End Module
```

Now suppose you want to put the parameters to `SomeLongMethodNameHere()` on seperate lines, so you put the caret before `ArgOne`, press Enter to move it down, and then Backspace several times to get this:

```vb
  Private Sub SomeLongMethodNameHere(
                ArgOne As String, ArgTwo As String, ArgThree As String)
  End Sub
```

Next you put the caret before `ArgTwo` and press Enter. The editor correctly indents it so it aligns with `ArgOne`:

```vb
  Private Sub SomeLongMethodNameHere(
                ArgOne As String,
                ArgTwo As String, ArgThree As String)
  End Sub
```

Then you repeat for `ArgThree` and the editor correctly indents it so it aligns with `ArgOne` and `ArgTwo`:

```vb
  Private Sub SomeLongMethodNameHere(
                ArgOne As String,
                ArgTwo As String,
                ArgThree As String)
  End Sub
```

All this works as expected and I usually move the closing bracket to the next line too so it ends up like this:

```vb
  Private Sub SomeLongMethodNameHere(
                ArgOne As String,
                ArgTwo As String,
                ArgThree As String
              )
  End Sub
```

This behaviour should apply to the type parameters for class `CFoo` but it doesn't. Like before, we begin by placing the caret before `TOne`, press Enter and then backspace several times to get this:

```vb
  Private Class CFoo(Of
                  TOne As Class, TTwo As Class, TThree As Class)
  End Class
```

Next we place the caret before `TTwo` and press Enter. The expectation is that it will align with `TOne` (similar to how `ArgTwo` was aligned with `ArgOne`) but instead the editor seems to indent "further in" so it lines up with the end of the `Of` keyword, giving this messy result:

```vb
  Private Class CFoo(Of
                  TOne As Class,
                       TTwo As Class, TThree As Class)
  End Class
```

If you repeat for `TThree` it is aligned once again with the end of the `Of` keyword, which also means it lines up with `TTwo`:

```vb
  Private Class CFoo(Of
                  TOne As Class,
                       TTwo As Class,
                       TThree As Class)
  End Class
```

Ultimately, you have to manually edit the indents for all parameters to get a result similar to this:

```vb
  Private Class CFoo(Of
                  TOne As Class,
                  TTwo As Class,
                  TThree As Class
                )
  End Class
```

**Expected Behavior**:

When indenting the second and subsequent parameters to methods like `SomeLongMethodNameHere()` the editor correctly aligns those parameters **using the indent level applied to the first parameter**. This behaviour should also apply to type parameters to classes like `CFoo`. At the moment the editor seems to insist on aligning subsequent type parameters with the `Of` keyword instead of with the first type parameter.

**Comment by ericmutta** [comment]
As an additional note, **it appears that the indenting problem only happens at the declaration site of the type parameters**. If you try indenting at the `Inherits` clause, the editor correctly lines up subsequent parameters with the first one. Consider this:

```vb
  Private Class CBar
    Inherits CFoo(Of InvalidTimeZoneException, InvalidCastException, TypeAccessException)
  End Class
```

You place the caret before `InvalidTimeZoneException`, press enter then add several spaces to get this:

```vb
  Private Class CBar
    Inherits CFoo(Of
               InvalidTimeZoneException, InvalidCastException, TypeAccessException)
  End Class
```

Now if you place the caret before `InvalidCastException` and press enter, it will correctly match the indentation of the first type argument `InvalidTimeZoneException':

```vb
  Private Class CBar
    Inherits CFoo(Of
               InvalidTimeZoneException,
               InvalidCastException, TypeAccessException)
  End Class
```

Same thing happens with `TypeAccessException` which is lined up with the previous two type arguments:

```vb
  Private Class CBar
    Inherits CFoo(Of
               InvalidTimeZoneException,
               InvalidCastException,
               TypeAccessException)
  End Class
```

If you place the caret before the closing bracket and press enter, it too is aligned with all the parameters:

```vb
  Private Class CBar
    Inherits CFoo(Of
               InvalidTimeZoneException,
               InvalidCastException,
               TypeAccessException
               )
  End Class
```

I usually press backspace several times to align the bracket with the name of the class being inherited from (i.e `CFoo`), giving this final result:

```vb
  Private Class CBar
    Inherits CFoo(Of
               InvalidTimeZoneException,
               InvalidCastException,
               TypeAccessException
             )
  End Class
```

**Comment by CyrusNajmabadi** [comment]
Closing as we are not changing these vb experiences.
