### ISSUE TITLE
Roslyn demands unrestricted permissions to everything

### ISSUE THREAD

**Issue by ekolis** [dotnet/roslyn#29525]
**Version Used**: 
2.9.0

**Steps to Reproduce**:

1. Call Roslyn from an AppDomain where the permissions are restricted to, say, Internet zone.

**Expected Behavior**:
Scripts run and only crash if they call on code that requires elevated permissions such as file I/O.

**Actual Behavior**:
Roslyn crashes immediately demanding unrestricted permissions to everything: this is the permissions that the SecurityException says it is demanding:

<PermissionSet class="System.Security.PermissionSet"version="1"Unrestricted="true"/>

Unless I'm missing something here, this make Roslyn completely unusable for scenarios where potentially untrustworthy code could be executed, e.g. plugin architectures or game modding.

[RoslynClassLibrary.zip](https://github.com/dotnet/roslyn/files/2321949/RoslynClassLibrary.zip)

**Comment by tmat** [comment]
.NET Framework does no support Code Access Security (CAS) as a security boundary anymore.

https://docs.microsoft.com/en-us/dotnet/framework/misc/how-to-run-partially-trusted-code-in-a-sandbox

We consider this feature obsolete and won't support it in Roslyn. If you need to isolate untrusted code you need to run it in separate process.

**Comment by ekolis** [comment]
A separate process? How can I secure it that way? How would I set permissions on a process without using code access security?

**Comment by tmat** [comment]
See https://docs.microsoft.com/en-us/windows/desktop/procthread/process-security-and-access-rights

**Comment by ekolis** [comment]
That looks like a C++ API, and I see nothing there about restricting access to the filesystem...

**Comment by CyrusNajmabadi** [comment]
> That looks like a C++ API

It is a windows API.  :)   You can call it from anything that can call into the Windows API.  This does include .Net (though you may need pinvokes).  Can't help you with the filesystem bit, you'll have to see what Windows is capable.  It's not really a Roslyn/C# question.
