### ISSUE TITLE
Broken link in FAQ

### ISSUE THREAD

**Issue by nick-morhun** [dotnet/roslyn#29526]
**Version Used**: 
GitHub docs

**Steps to Reproduce**:

1.  Go to [this page](https://github.com/dotnet/roslyn/wiki/FAQ#what-components-can-i-run-locally-in-visual-studio).

**Expected Behavior**:
Link to '/master/docs/contributing/Building, Debugging, and Testing on Windows.md' works.

**Actual Behavior**:
The link has invalid format and is therefore broken.

**Comment by chborl** [comment]
Thank you for your feedback.  I have updated the link so it will work correctly now.
