### ISSUE TITLE
Empty type in peek definition for tuples

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#29523]
**Version Used**: VS15.8.1

Alt+F12 on `int` in the tuple

![image](https://user-images.githubusercontent.com/3105979/44627929-17ff0e00-a94c-11e8-99f1-7ec2529b1cd0.png)

**Comment by alrz** [comment]
Also F12 on `ValueTuple` in `ValueTuple<int, int> a = (1, 2);` won't work either.

**Comment by sharwell** [comment]
:memo: In the first example, it should actually show `struct Int32`, but in the second example (or to the left of the opening `(` in the first example) it should show `ValueTuple<T1, T2>`.

**Comment by CyrusNajmabadi** [comment]
Not repro:

![image](https://user-images.githubusercontent.com/4564579/216472559-d487a7a9-56c3-4ac5-a131-6e263d1685b9.png)
