### ISSUE TITLE
IDE0009 - add this or me qualification within object initializer

### ISSUE THREAD

**Issue by sevensc** [dotnet/roslyn#29528]
**Version Used**
VS 2017 Enterprise, 15.8.1

When i use the object initializer, the quick actions suggests to add this qualifier to everything.
The warning dissapears, when i change the `'this.' preferences: -> "Qualify method access with 'this'" to: Do not prefer 'this'`

<img width="720" alt="add-this-qualifier" src="https://user-images.githubusercontent.com/22618943/44659369-4c360580-aa04-11e8-8636-3e53890a877a.png">

**Comment by CyrusNajmabadi** [comment]
@jinujoseph Another dupe.  We should really backport this fix to 15.8.  Lots of people will hit this.

**Comment by jinujoseph** [comment]
The fix should be available in [15.9.Preview2](https://github.com/dotnet/roslyn/pull/29449)
