### ISSUE TITLE
Convert to Automatic generated property

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29522]
Why is the following Property candidate but not the second one?

```vb
 Public Property LoadRootHolidaysOnly() As Boolean
            Get
                Return theLoadRootHolidaysOnly
            End Get
            Set(Value As Boolean)
                theLoadRootHolidaysOnly = Value
            End Set
        End Property

 Public Property LoadRootHolidaysOnly() As Boolean 
            Get
                LoadRootHolidaysOnly =theLoadRootHolidaysOnly
            End Get
            Set(Value As Boolean)
                theLoadRootHolidaysOnly = Value
            End Set
        End Property
```

This may be C# thinking

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/317956/convert-to-automatic-generated-property.html
VSTS ticketId: 668775_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jhinder** [comment]
The second property's `Get` body doesn't follow the required structure. You may only return a field in order to be eligible for auto-property conversion. (See also [the relevant bit of code](https://github.com/dotnet/roslyn/blob/master/src/Features/VisualBasic/Portable/UseAutoProperty/VisualBasicUseAutoPropertyAnalyzer.vb#L102)).

**Comment by sharwell** [comment]
Tentatively marking this on as **Won't Fix**, but I added it to the schedule for an upcoming design review and I'll provide more information from that meeting before closing the issue.

**Comment by sharwell** [comment]
This is a low priority issue, but we'd entertain a pull request to implement this if someone cares enough to submit one.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to be making changes in these areas.
