### ISSUE TITLE
Display the analyzers and extensions causing "Gathering suggestions" to block

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#29530]
In VS 15.8.1 when I press Ctrl+. in a certain section, this dialog blocks the VS interface for around 30 seconds:

![image](https://user-images.githubusercontent.com/8040367/44668023-6367f980-a9ea-11e8-9d19-d4b0eb4437f8.png)

Instead of a mostly empty dialog, it would be nice to see the analyzer or extensions currently responsible for the wait. Maybe a format like "Waiting for [Longest running task] and 2 others..."?

Armed with this information, I'll have some idea if it's a particular analyzer or VS extension and I'll be able to proceed from there by reporting and disabling.

**Comment by dpoeschl** [comment]
We can do the following as an initial approach:
1. Being able to see it's not stuck or how much longer it might take -- Update it to show progress through the _stages_ (Getting compilation, getting diagnostics, finding applicable fixes, etc...)
2. Blaming particular diagnostics/fixes -- Show the "currently running" analyzer/etc.
