### ISSUE TITLE
Native compiler crashes on `await` combined with `ref`

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#2953]
Consider this code:

``` csharp
    public class Launcher
    {
        private static int _foo;

        private static async void RefreshCache()
        {
            Interlocked.Exchange(ref _foo, await Cache());
        }

        private static Task<int> Cache()
        {
            return Task.FromResult(0);
        }

        static void Main(string[] args)
        {

        }
    }
```

This will cause a crash in the native compiler.  Roslyn correctly handles this case but we should add a test case to lock in the better behavior.  

Source:

- https://twitter.com/YuvalItzchakov/status/601100730062110720
- http://stackoverflow.com/q/30358141/23283

**Comment by Yuvalos** [comment]
It would also be interesting to understand why it isn't working in the native compiler.

**Comment by Servy215** [comment]
Simpler reproduction:

    public class Worker
    {
        private static int foo;
        private static async void DoWork()
        {
            DoNothing(ref foo, await Task.FromResult(0));
        }
        private static void DoNothing(ref int item, int other)
        {
        }
    }

**Comment by jaredpar** [comment]
@Yuvalos agreed. 

@Servy215 thanks!

**Comment by jaredpar** [comment]
Looks like we already have a regression test here

http://source.roslyn.io/#Roslyn.Compilers.CSharp.Emit.UnitTests/CodeGen/CodeGenAsyncSpillTests.cs,658fb588fd9c2000
