### ISSUE TITLE
Avoid reallocating of non-mutated value arrays.

### ISSUE THREAD

**Issue by jlennox** [dotnet/roslyn#29535]
**Proposal**
Value arrays which can be determined as non-mutating can be singleton allocated. In the attached sample, this could be done by storing the array passed to `DoesNotMutate` as a static or other non-local context.

This proposal is to have value arrays which can be determined by the compiler as non-mutating be promoted to a static scope to prevent reallocation.

Because of the behavior of strings, this behavior should also happen for static strings.

One issue is it's possible the developer may have an extremely large array that would be undesirable to keep in memory. The promotion could have an upper limit on memory size.

```CSharp
using System;

namespace NS
{
    class Program
    {
        static void Main(string[] args)
        {
            for (var i = 0; i < 10; ++i)
            {
                DoesNotMutate(new[] { 1, 2 });
                DoesMutate(new[] { 2, 1 });
            }
        }
        
        static bool DoesNotMutate(int[] array)
        {
            return array.Length == 2;
        }
        
        static void DoesMutate(int[] array)
        {
            if (array.Length == 2)
            {
                array[0] = 3;
            }
        }
    }
}
```

**Desire Behavior**:

1 allocation of `[1, 2]` and 10 allocations of `[2, 1]` occur.

**Actual Behavior**:

10 allocations of `[1, 2]` and 10 allocations of `[2, 1]` occur.

**Comment by huoyaoyuan** [comment]
Currently, large literal number arrays do exist in assembly, and loaded by `System.Runtime.CompilerServices.RuntimeHelpers.InitializeArray`. Your suggestion is to change the action from _copy_ to _reference_.
I think it's quite difficult to work, because immutable array is not a language concept nor a primitive type, so the condition

> which can be determined by the compiler as non-mutating

needs many track steps, including write checks, store checks, then falls into a language concept like nullable reference type.
Moreover, some scenarios can be manually solved using `ReadOnlySpan<T>` or `ReadOnlyMemory<T>`, making this feature worth less.

**Comment by jlennox** [comment]
@huoyaoyuan There's two things I'm trying to address here:

1) The needs of an inner method bloating more accessible scope (a private static being considerably higher scope than method scope)
2) Ease of use. As it's a predictable desire, it would be nice if it was handled automatically instead of not.

I can understand 2 adds a lot of additional complexities. Perhaps my request should instead be for method scoped statics (which would be a language change, not a compiler change)?

If that's the general consensus I'll close this issue.

**Comment by CyrusNajmabadi** [comment]
> This proposal is to have value arrays which can be determined by the compiler as non-mutating be promoted to a static scope to prevent reallocation.

How does the compiler determine this?

**Comment by jlennox** [comment]
> How does the compiler determine this?

Any array who's reference is only stored on the stack and is never cast to a pointer should be able to be determined if it's non-mutating.
