### ISSUE TITLE
Reference semantics with structures and interfaces

### ISSUE THREAD

**Issue by ENikS** [dotnet/roslyn#29563]
### Problem
Structures might implement interfaces and could be accessed via these interfaces. The penalty for such an access is boxing of the struct. This is well known problem and advised against for high performance implementations.

### Feature Request
C# 7.2 implements assigning and passing value types and specifically struct by reference. So theoretically it should be possible to get reference to the struct via one of the interfaces it implements. This should eliminate boxing and provide all the benefits of abstraction provided by interfaces.

Since interfaces inherently readonly integrity of the data should not be an issue.

Example:
```c#
interface IService 
{
...
}

ref struct  ServiceStruct :  IService 
{
...
}

void SomeMethod(IService service)
{
...
}

  // Usage:
... scope()
{
    var originValue = new ServiceStruct(...);

    ref IService iReference = ref originValue; 

    SeomeMethod(ref originValue);
}
```

**Comment by alrz** [comment]
Language feature requests should be opened on [dotnet/csharplang](https://github.com/dotnet/csharplang) repo.

**Comment by ENikS** [comment]
Thx, I'll resubmit it these

**Comment by ENikS** [comment]
This does not require any language changes. It has more to do with how compiler deals with getting references.

**Comment by CyrusNajmabadi** [comment]
> This does not require language change, everything you need already there. It has more to do with how compiler deals with getting references.

Sorry, it's unclear to me what you're asking the compiler to do.  What specific IL do you want it to generate in this case?

**Comment by CyrusNajmabadi** [comment]
> This does not require language change,

Your example has: 

```c#
ref struct  ServiceStruct :  IService 
{
}
```

But this is not legal *as per the language*.  So if you wanted this to work, the language would *first* have to be updated, *then* teh compiler would be updated to match the language specification.  The compiler is not written to intentionally deviate from the actual language spec as that would make life super awful and difficult to deal with :)  You'd have:

1. what the language says
2. what the compiler actually does

Figuring out what things should actually do in such a world is *not fun*.
