### ISSUE TITLE
Lambda Bodied Properties: [method: .... attribute target

### ISSUE THREAD

**Issue by AlexanderMorou** [dotnet/roslyn#29566]
**Version Used**: 
Visual Studio 15.8.0

**Steps to Reproduce**:
1. Create a property with a lambda body:
```
public bool PropertyName => SomeExpression;
```
2. Attempt to put an attribute on the method:
```
[SomeMethodAttribute]
public bool PropertyName => SomeExpression;
/* or */
[method: SomeMethodAttribute]
public bool PropertyName => SomeExpression;
```

**Expected Behavior**:
On a lambda bodied property, the `[method: AttributeName]` syntax on the property itself should allow you to target the get method of the property.  There is no other mechanic I can think of to allow this behavior as the usual `{ /* insertion point */get { ` is not available on lambda-bodied properties.

**Actual Behavior**:
You receive the following C# warning:
Warning	CS0657	'method' is not a valid attribute location for this declaration.

**Comment by CyrusNajmabadi** [comment]
> Create a property with a lambda body:

Nit: we call these 'expression bodied' members, not 'lambda body'.  

--

As to your issue: you have filed this in the Roslyn repo. However, the Roslyn repo is where the C# *compiler* exists, and AFAICT, the compiler is operating correctly as per the C# Language Specification.  If you would like the *language* changed to support this concept, then that needs to be filed over at dotnet/csharplang.  If your proposal is accepted into the language, then teh compiler will be fixed up accordingly.

Can you please move this over?  Thanks!

**Comment by AlexanderMorou** [comment]
Thank you for your nit and redirect.  When I have the time I will move it over.

**Comment by CyrusNajmabadi** [comment]
Closing out as this has already been moved.
