### ISSUE TITLE
Signficant trailing whitespace being deleted

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#29565]
**Version Used**: 
15.8.1
**Steps to Reproduce**:

1. Open src/EditorFeatures/VisualBasicTest/Classification/SyntacticClassifierTests.vb 
2. Make any change (change a comment for example)
3. Save File

**Expected Behavior**:
X below is a whitespace and I expect it to be there after saving
```
        <Fact, Trait(Traits.Feature, Traits.Features.Classification)>
        Public Async Function TestBug927678() As Task
            Dim code =
"'This is not usually aX
'collapsible comment block
x = 2"
```
**Actual Behavior**:
The space at the end of the line **"'This is not usually a **  is deleted.
Also Git Compare version shows the missing whitespace but also says the line is unchanged.
Picture and details below 
https://github.com/dotnet/roslyn/pull/28327#issuecomment-416499485

**Comment by CyrusNajmabadi** [comment]
I cannot repro this.  Are you sure this is roslyn, and not some other tool you have installed?

**Comment by paul1956** [comment]
It just started happening with 15.8, is there any way to load VS without any extensions except the ones built?

**Comment by CyrusNajmabadi** [comment]
You could just disable your extensions in `Tools | Extensions & Updates`

**Comment by CyrusNajmabadi** [comment]
@jmarolf Is there any way to load vs with a hive that doesn't have unnecessary extensions?

**Comment by jmarolf** [comment]
@paul1956 from a developer command prompt launch Visual Studio using [safemode](https://docs.microsoft.com/visualstudio/ide/reference/safemode-devenv-exe)
```cmd
devenv /safemode
```

**Comment by paul1956** [comment]
It does not happen in safemode, thanks for that, It looks like CodeMaid is doing this I will close here and Open there.
