### ISSUE TITLE
"Add accessibility modifiers" C# formatting rule breaks code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29561]
We do not use &quot;private&quot; and &quot;internal&quot; everywhere because they are default modifiers and we don't want to see defaults in our code. That rule adds them, making lots of diffs for no reason. This rule should not be opt-out, it should be opt-in.

Another problem is methods with &quot;extern&quot; modifier. This rule removes &quot;extern&quot;, breaking our interop code. Please don't do that.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/293507/add-accessibility-modifiers-c-formatting-rule-brea.html
VSTS ticketId: 648040_
_These are the original issue comments:_

Jinu Joseph [MSFT] on 8/5/2018, 00:53 AM (22 days ago): <p>Thank you for your feedback! For us to investigate this further, could you please provide code snippet which leads to this issue, specific example will help us to investigate better.  We look forward to hearing from you!</p>

Roy Scheerens on 8/5/2018, 03:28 AM (22 days ago): <p>I have this problem as well, and it seems to happen with every extern function/method that doesn't have an access modifier. If I enable the additional code cleanup, and the 'add accessibility modifiers' option, it will remove extern and replace it with private.</p><p><img src="https://developercommunity.visualstudio.com/storage/temp/36550-missingextern.png"></p><pre>using System;<br>using System.Runtime.InteropServices;<br><br>namespace ConsoleApp8<br>\{<br>  class Program<br>  \{<br>    [DllImport("User32.dll", CharSet = CharSet.Unicode)]<br>     static extern int MessageBox(IntPtr h, string m, string c, int type);<br><br>    static void Main(string[] args)<br>    \{<br>      MessageBox(IntPtr.Zero, "hello world", "My Message Box", 0);<br>    }<br>  }<br>}</pre>
![image](https://user-images.githubusercontent.com/17056651/44694435-464f1d00-aa22-11e8-8b6b-d8e17c16ce76.png)

Jinu Joseph [MSFT] on 8/5/2018, 10:52 PM (21 days ago): <p>thanks much for the example, we will investigate the issue</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
The syntax generator used by this code fix should definitely not be removing the `extern` modifier. 🐛

**Comment by sharwell** [comment]
> We do not use "private" and "internal" everywhere because they are default modifiers and we don't want to see defaults in our code. That rule adds them, making lots of diffs for no reason. This rule should not be opt-out, it should be opt-in.

Many of our code style rules default to the majority use case, while allowing alternative configurations. This is one of those rules; you can specify the preferred behavior in **.editorconfig** under the `dotnet_style_require_accessibility_modifiers` rule:

```
dotnet_style_require_accessibility_modifiers = omit_if_default:warning
```

**Comment by d-dizhevsky** [comment]
@sharwell I would like to take this. Is this the right place to start from? 
https://github.com/dotnet/roslyn/blob/6193ddfc950a7f6b2d8a7509d113711c99c0539f/src/Features/Core/Portable/AddAccessibilityModifiers/AbstractAddAccessibilityModifiersCodeFixProvider.cs#L51

**Comment by jinujoseph** [comment]
also reported at [link](https://developercommunity.visualstudio.com/content/problem/381827/code-fix-add-access-modifier-removes-extern.html)

**Comment by FrankHileman** [comment]
Is there a converse rule, to remove the noise from the redundant modifiers, private and internal?

**Comment by sharwell** [comment]
@FrankHileman Yes, see https://github.com/dotnet/roslyn/issues/29561#issuecomment-416660897
