### ISSUE TITLE
Generate Compiler Code does not produce enumerators with values.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#29564]
**Version Used**: 
```
VisualStudio.15.Preview/15.9.0-pre.1.0+28016.0
Visual Basic Tools   2.10.0-beta1-63119-07
```
**Steps to Reproduce**:

1.  Modify the `Syntax,xml` file, so an enumeror has an associated value.
eg
```xml
    <enumeration name="LiteralBase">
      <description>
        The four possible number bases that a literal can be written in.
      </description>
      <native-equiv name="LiteralBase"></native-equiv>

      <enumerators>
        <enumerator name="None" hexvalue="0"/>
        <enumerator name="Binary" hexvalue="2"/>
        <enumerator name="Octal" hexvalue="8" />
        <enumerator name="Decimal" hexvalue="A"/>
        <enumerator name="Hexadecimal" hexvalue="10"/>
      </enumerators>
    </enumeration>
```
2. Run the command file. `...\build\scripts\generate-compiler-code.cmd`

'Syntax.xml.Syntax.Generated.vb`

**Expected Behavior**:
```vbnet
''' <summary>
''' The four possible number bases that a literal can be written in.
''' </summary>
    Public Enum LiteralBase
        None = 0
        Binary = 2
        Octal = 8
        [Decimal] = 10
        Hexadecimal = 16 
    End Enum
```
or something similar possibly with hex constants,

**Actual Behavior**:

```
''' <summary>
''' The four possible number bases that a literal can be written in.
''' </summary>
    Public Enum LiteralBase
        None
        Binary
        Octal
        [Decimal]
        Hexadecimal 
    End Enum
```

*I don't know if this also occurs with C#'s generated compiler code*

**Comment by CyrusNajmabadi** [comment]
This is a public enum.  The values of it are baked into the resulting assembly as constants.  The cannot be changed.  So this will never be taken as a change to Roslyn.  

Can you explain why you're trying to do this?  You can just create your own extension that goes from these enum values to whatever value you want.  It would not require breaking Roslyn :)

**Comment by AdamSpeight2008** [comment]
@CyrusNajmabadi 
Seeing that the schema allowed it, was just experimenting *(on my branch)* and noticed the issue with the outputted code. 

The fix for the issue is on line 199 in [RedNodeWriter.vb](https://github.com/dotnet/roslyn/blob/master/src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/RedNodes/RedNodeWriter.vb#L200) is adding ` OrElse (enumerator.ValueString IsNot Nothing)` to the final argument.

**Comment by CyrusNajmabadi** [comment]
If it's your own branch, then you can just change your version of it :)  I doubt anyone would make this change unless there was an actual need for this functionality in the actual roslyn codebase.
