### ISSUE TITLE
Editor Completion: CompletionItemRules.FilterCharacterRules

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#29576]
See https://github.com/dotnet/roslyn/issues/27427

**Comment by ivanbasov** [comment]
We call 
`Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.IsFilterCharacter(CompletionItem item, char ch, string textTypedSoFar)`
from the CommitManager and from the ItemManager

**Comment by ivanbasov** [comment]
Corresponding tests are enabled.
