### ISSUE TITLE
Editor Completion - Figure out how `EditorCompletionOptions.UseSuggestionMode_Debugger` works

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#29571]
See https://github.com/dotnet/roslyn/issues/27427

**Comment by ivanbasov** [comment]
In the old completion code, I found only ToggleCompletionMode but not using those values. I see this code now on the editor side. I do not see any work on the Roslyn side but will keep open for the Editor verification.

**Comment by ivanbasov** [comment]
The option is used in both old and new completion for making decisions between soft and hard selections. I have verified to algorithms at both completion implementations look similar. The new completion involves the option on the editor side. The new implementation seems to support the option the same way as the old one. Let us consider the issue closed until the opposite is proven.
