### ISSUE TITLE
Editor Completion: CompletionOptions.TriggerOnTyping & CompletionOptions.TriggerOnTypingLetters & CompletionOptions.TriggerOnDeletion

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#29573]
See https://github.com/dotnet/roslyn/issues/27427

**Comment by ivanbasov** [comment]
- TriggerOnjDeletion is used in ShouldTriggerCompletion called by completion source
- TriggerOnTypingLetters and TriggerOnTyping are implemented for individual completion providers
