### ISSUE TITLE
VB: "Rename tracking" doesn't work on parameters created via "Generate constructor".

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#29585]
**Version Used**:

Visual Studio Community 2017 v15.5.6

**Steps to Reproduce**:

Start with the following code:

```vb
Public Class Blah
  Public ReadOnly Name As String
  Public ReadOnly Age As Integer

  Public Sub foo(One As String)
    Dim temp = One
  End Sub
End Class
```

Now let's say you want to rename parameter `One` of method `foo()` so it reads `ArgOne`. You put the caret before `One` in the parameter list and type the letters `Arg`. The "rename tracking" feature kicks in and shows a dotted rectangle around the new name, along with the light bulb so you can invoke the rename operation:

![vs_rename_gencon_1](https://user-images.githubusercontent.com/20465797/44809415-4fcdb600-abd7-11e8-9090-8dc376cb79ff.png)

You can then click the light bulb and choose the rename operation:

![vs_rename_gencon_2](https://user-images.githubusercontent.com/20465797/44809518-94f1e800-abd7-11e8-9b6b-a3930b4f53c4.png)

...which works as expected leaving you with this:

![vs_rename_gencon_3](https://user-images.githubusercontent.com/20465797/44809582-c7034a00-abd7-11e8-8770-8a84e70be02f.png)

The problem however is the above procedure doesn't work for parameters in a constructor that is generated via the "Generate constructor" refactoring. To see this, click on the blank line above method `foo()` and choose "Generate constructor" from the light bulb menu:

![vs_rename_gencon_4](https://user-images.githubusercontent.com/20465797/44809725-3b3ded80-abd8-11e8-8e0e-fd9baed1066b.png)

Then press OK in the Pick Members dialog window to generate a constructor which takes parameters to initialise the fields `Name` and `Age`:

![vs_rename_gencon_5](https://user-images.githubusercontent.com/20465797/44809829-83f5a680-abd8-11e8-9f3d-af9b2e1da018.png)

The operation works as expected, leaving you with code like this:

![vs_rename_gencon_6](https://user-images.githubusercontent.com/20465797/44809943-dd5dd580-abd8-11e8-9e1d-0de080519b43.png)

Now, following the steps we used to rename `foo()`'s parameter `One` to `ArgOne` earlier above, we want to rename the generated constructor's parameter `name` to read `ArgName`. So we place the caret before `name` and type the letters `Arg`. Like before, rename tracking kicks in and the light bulb appears:

![vs_rename_gencon_7](https://user-images.githubusercontent.com/20465797/44810235-cbc8fd80-abd9-11e8-8ca2-659652cf3898.png)

This time however **clicking the light bulb to invoke the rename operation does nothing. You click it but no menu is shown, it simply ignores the click**. It doesn't matter what you try (e.g you can move the constructor several lines down, you can cut the whole thing and paste it again, etc), the rename operation can't be invoked from the light bulb.

**Expected Behavior**:

Renaming parameters from their declaration site should work in both regular methods (as we saw with method `foo()`) and in constructors that were generated via "Generate constructor". Interestingly enough, if you type out a constructor by hand, such as the following:

```vb
  Public Sub New(test As String)
    Dim x = test  'can rename test from its declaration site in this constructor.
  End Sub
```

...the rename operation following the above procedures works just fine. Also if you do the rename by right clicking the identifier and choosing "Rename...", it popups that rename dialog and always works.

Finally, for the problematic generated constructor, the rename operation works via the light bulb if you do the rename operation at any point where the parameter is used (it only fails if you do the rename where the parameter is declared):

```vb
  Public Sub New(name As String, age As Integer)
    Me.Name = name '<-- can rename "name" to "ArgName" fine from here.
    Me.Age = age
  End Sub
```

**Comment by ericmutta** [comment]
On a related note (maybe I should file a seperate issue?) **it would be really useful if we could specify the prefixes/suffixes to add to various automatically generated elements**.

For example: in my code all parameters are prefixed with the letters `Arg` to make it easy to tell whether I am dealing with a local variable whose value is under my control or an argument whose value is determined by calling code. Having the "Generate constructor" refactoring automatically prefix the parameters with letters chosen by the user, would make the entire rename operation irrelevant and the problem filed in this issue would vanish.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in these scenarios.
