### ISSUE TITLE
Consider tweaking cetain accessibility defaults when generating members.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#29584]
Feedback came in through https://gitter.im/dotnet/roslyn that some people are unhappy with some of the defaults around accessibility we have when generating members.  Specifically, that our default of picking 'least privilege' can be annoying, and non-idiomatic for them.  *Specifically* though it is about ever picking "internal" as the accessibility as some people perceive that to be a smell.  

The open design question is: should we limit the accessibility we generate only to private/public/protected.

--

In a similar vein (though this may be a separate issue), there is a question about if we should default toward 'protected' when generating things like abstract members in abstract classes.  "protected abstract" feels far more idiomatic and common than "internal abstract".  

--

We could satisfy these both by either:
1. just changing our defaults unilaterally.
2. having an optoin in tools|options like "Prefer 'internal' if possible over 'public' or 'protected' when generating members".  

Note: this would only be about *members*.  Having *types* still default to internal seems to not be contentious.

**Comment by CyrusNajmabadi** [comment]
Tagging @dpoeschl @jnm2

**Comment by CyrusNajmabadi** [comment]
Note: long ago we did default toward being more 'public' and we got strong feedback that that was not desirable from a lot of people.  That's why we went with going for 'least privilege'.  Because of that, i'm leaning toward option '2' as it means it can be a choice and it isn't some large switch we throw that then upsets some group of people.

**Comment by jnm2** [comment]
For types, `internal` is often great. For members, using `internal` indicates that encapsulation is being broken. Sometimes that's what you want, but IMO it's not a good thing to default people to.

**Comment by MaStr11** [comment]
Another case where I don't like the defaults is in [AbstractInitializeMemberFromParameterCodeRefactoringProvider](https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs#L171). When a read-only property is generated from a constructor parameter it defaults to  *public*. If you do constructor dependency injection the parameter type is an interface of a service and I do change the visibility of the property to *protected* all the time. But *public* being the default makes sense for this provider, it just doesn't fit my needs. Nevertheless, this refactoring is a big time saver anyway. Thanks, @CyrusNajmabadi for implementing it!

**Comment by vatsalyaagrawal** [comment]
Design Meeting Notes:

These issues will be taken up on a case to case basis. We are not planning any generic fix. 
@CyrusNajmabadi to outline specific changes for the two fixes the are planned.
