### ISSUE TITLE
Inline lightbulb that does nothing is shown for analyzers that do not have an associated code fix

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#29589]
If an analyzer provides a warning, but has no associated code fix, Roslyn always shows an inline light bulb that when clicked does nothing.

![lightbulb](https://user-images.githubusercontent.com/1103906/44824443-e1c1d700-ac48-11e8-8d28-4b6ad9f5cdd3.gif)

I would expect at least being offered to suppress this.

**Comment by gundermanc** [comment]
👍 on this. Another repro:

**Version Used**: 
2.11.0-beta2
VS 16.0 Internal Preview 28414.103.d16.0stg

**Steps to Reproduce**:

1. Create new console app.
2. Wait for 'args' argument to main to be greyed out.
3. Hover mouse, wait for lightbulb to appear.
4. Click lightbulb

**Expected Behavior**:
Lightbulb expands and offers a fix.

**Actual Behavior**:
❗️ Lightbulb is dismissed and returns no items. Looking under debugger it appears Editor isn't getting any Suggested Actions back from Roslyn when we ask for them.

📝  There are 2 different code paths and this same scenario works fine when you click the margin bulb.
![lightbulb repro](https://user-images.githubusercontent.com/5387680/50125270-e1ac0e00-021c-11e9-9a94-206203ef54fc.gif)
📝 I also noticed that this behavior repros with the FxCop analyzers, regardless of VS version.

**Comment by sandyarmstrong** [comment]
VSmac bundles various analyzers from Refactoring Essentials that do not have associated code fixes, so these disappearing lightbulbs can be very common for our users.

It would be great if, as @davkean suggests, there were at least menu items to suppress the analyzers.

**Comment by davkean** [comment]
@CyrusNajmabadi Do you know where the right place to make this change would be?

**Comment by davkean** [comment]
@jinujoseph I believe this priority should be upped, we ship an analyzer out of the box (unused parameters) that runs into this issue on every Main method from every File -> New -> Project. Not a great introduction to analyzers/code fixes.

**Comment by mavasani** [comment]
It seems like filtering of the suppression fixes and refactorings happen for the light bulb under the squiggle over here: https://github.com/dotnet/roslyn/blob/eb170a1af38c3d3ec197f94e7f60aa8bd828689c/src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs#L342-L348

It seems like this is an explicitly coded behavior, and git blame shows it has been like this for few years at least. @heejaechang @CyrusNajmabadi, do any of you have more context on this filtering?

**Comment by mavasani** [comment]
I think we need to do either of the following changes:

1. Fix in the VS platform/light bulb engine layer to not show the light bulb if no fixes are returned OR
2. Remove the above filtering logic to include suppression fixes even when light bulb asks for `PredefinedSuggestedActionCategoryNames.CodeFix`

**Comment by sandyarmstrong** [comment]
@mavasani the third option would be for Roslyn to properly return `null` when there are no fixes available. Then the light bulb wouldn't show up in the first place.

**Comment by mavasani** [comment]
I think I figured out the issue. Roslyn side implements [ISuggestedActionsSource2.GetSuggestedActionCategoriesAsync](https://github.com/dotnet/roslyn/blob/eb170a1af38c3d3ec197f94e7f60aa8bd828689c/src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs#L1074), which is a check to verify if any fixes exist, and we return true in presence of suppression fixes over [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/CodeFixes/CodeFixService.cs,511), but then when asked to provide fixes, we filter out suppression fixes. So the fix needs to from the Roslyn side. Do we prefer the lightbulb under the squiggle to show up only in presence of suppression fixes?

**Comment by CyrusNajmabadi** [comment]
Unfortunately I have no knowledge/context here.  All the suppression stuff happened while i was over on TypeScript.  I don't actually have any idea how any of it works.  Sorry! :)

**Comment by davkean** [comment]
I've personally always found it odd that I cannot suppress a warning when using inline light bulb.

**Comment by sharwell** [comment]
Design review conclusion: both light bulbs should show the same items. @mavasani will file a follow-up item to investigate improving the light bulb experience for cases where the only fix suggested in the dropdown is applying a suppression.

**Comment by davkean** [comment]
By "both items should show the same items", you mean by factoring in context too? The margin lightbulb shows items for everything on that line, the inline one only shows items specific to the span its dropped down on, I hope we don't change that.

**Comment by mavasani** [comment]
> the inline one only shows items specific to the span its dropped down on, I hope we don't change that.

Yes, the only fix here is to now show suppression items for diagnostics in the span its dropped down on.
