### ISSUE TITLE
we should report some kind of error message to user when an analyzer's SupportedDiagnostics throws an exception

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#296]
currently we silently disable the analyzer and move on. we should also report the issue to user.

**Comment by AdamSpeight2008** [comment]
This would be useful when debug a problematic analyser, as current to get some information about what went wrong by digging through the error log.

**Comment by srivatsn** [comment]
This is a subset of the work required for #257. Let's get to this as part of that issue.

**Comment by heejaechang** [comment]
@jmarolf is your work something we can use in this case? in other words, is it a service?

**Comment by jmarolf** [comment]
@heejaechang In short: yes. In long: the plan of record is to catch all exceptions and show the user an infobar indicating that an analyzer or codfix has crashed and been disabled.  The user could then decide to re-enable it by clicking in the infobar.  The enable/disable analyzers functionality currently lives in [features](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/EditorLayerExtensionManager.cs,47).  May move that to workspaces if it makes sense. The prototype infobar stuff will live in the VSWorkspace.   If you catch an exception and hand off to the error handler service everything should just work.

**Comment by heejaechang** [comment]
@jmarolf  I was thinking something more like a layered service

IInfoBarService <= generic service - it lets someone to show something in info bar
IErrorListService (or IHostDIagnosticSource) <= generic service - it lets someone to show something in error list as info.

IAnalyzerNotificationService <= analyzer specific service which anyone can report issues related to analyzers. and it internally tracks which analyzer reference the exception is associated with.

when an issue is reported, it shows the issue in both infobar (to get an attention) and error list (as a log). if the analyzer reference that issues is associated with get removed, then entry in the error list also goes away.

something like that.

**Comment by jmarolf** [comment]
@heejaechang Sounds like a good idea.  I'll keep you in the loop.
