### ISSUE TITLE
Move Roslyn to target netstandard 2.0 / net472

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#29601]
This is a place holder item to track the roslyn repository, and our produced packages, to target netstandard2.0 and net472.

**Comment by tmat** [comment]
Resolved by https://github.com/dotnet/roslyn/pull/30914. @jaredpar anything more we need to do before closing this issue? Perhaps updating docs, specifically re analyzers being able to target netstandard 2.0 now? @mavasani

**Comment by jaredpar** [comment]
Nope we are good to go now :)

**Comment by tmat** [comment]
Roslyn: 3.0.0, once we actually build them.
Dev16 P1

**Comment by gewarren** [comment]
I'm not sure if we have a good spot in the docs to put the new targeting info. Perhaps [this section](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix#explore-the-analyzer-template) that describes creating a new analyzer project in VS? @BillWagner @gregvanl do you know of a better spot?

**Comment by BillWagner** [comment]
I think that's the right location @gewarren 

I created dotnet/docs#9358 to track the updates needed there.

**Comment by michsco** [comment]
What release vehicle will this be addressed in? We are still seeing it (see [this](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2921)).

**Comment by tmat** [comment]
VS 2019.
