### ISSUE TITLE
IDE analyzer/fixer test framework should always force enable analyzer rules by default

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#29615]
Current implementation does not attempt to force enable analyzer rules that are `IsEnabledByDefault = false`. This forces the analyzers to have a test only path to force enable the rules for unit tests, see https://github.com/dotnet/roslyn/pull/29511#discussion_r214402729. This issue tracks adding functionality to test framework to always enable all supported diagnostics reported by an analyzer during unit test.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
