### ISSUE TITLE
Question: Is it correct that ReplaceNode throws an exception here?

### ISSUE THREAD

**Issue by taori** [dotnet/roslyn#29610]
CodeAnalysis.CSharp.Workspaces 2.6.1 is used.

This the code for my quickfix: 

```

private SyntaxNode CreateSuppressionAttributeSyntax(Diagnostic diagnostic)
{
	var nameSyntax = ParseName(typeof(System.Diagnostics.CodeAnalysis.SuppressMessageAttribute).FullName);
	var argumentList = ParseAttributeArgumentList($@"(""{string.Format(Resources.SuppressMessageCategoryText_0, diagnostic.Id)}"",""{diagnostic.Id}"")");
	var attribute = Attribute(nameSyntax, argumentList);
	return attribute;
}

private async Task<Document> GetTransformedDocumentAsync(CodeFixContext context, CancellationToken cancellationToken, CSharpSyntaxNode attributeTarget, Diagnostic diagnostic)
{
	var documentEditor = await DocumentEditor.CreateAsync(context.Document, cancellationToken);
	var attributeSyntax = CreateSuppressionAttributeSyntax(diagnostic)
				.WithAdditionalAnnotations(new SyntaxAnnotation[]{ Formatter.Annotation, Simplifier.Annotation});
	var modAttrTarget = attributeTarget.WithAdditionalAnnotations(Formatter.Annotation);
	documentEditor.ReplaceNode(attributeTarget, modAttrTarget);
	documentEditor.AddAttribute(modAttrTarget, attributeSyntax);
//		documentEditor.AddAttribute(attributeTarget, attributeSyntax);
	var changedDocument = documentEditor.GetChangedDocument();

	return await Formatter.FormatAsync(changedDocument, context.Document.Project.Solution.Workspace.Options, cancellationToken);
	return changedDocument;
}
```

Note that this codefix works perfectly fine and is formatted correctly when used from within VS without Formatter.FormatAsync.

What i am trying to do here is write my CodeFix in a way where only specific areas are touched by format (my injected attribute and the targetSyntax), so my unit tests are formatted correctly without dealing with trailing+leading whitespace all the time.

If i just use 
```documentEditor.AddAttribute(attributeTarget, attributeSyntax);```

The codefix already does what functionally complete and formatted as intented in VS.

I do not want to use 

```return await Formatter.FormatAsync(changedDocument, context.Document.Project.Solution.Workspace.Options, cancellationToken);```
because that would alter the whole documents formatting.

The reason why i am doing this:
```
var modAttrTarget = attributeTarget.WithAdditionalAnnotations(Formatter.Annotation);
documentEditor.ReplaceNode(attributeTarget, modAttrTarget);
documentEditor.AddAttribute(modAttrTarget, attributeSyntax);
```
is because i am attempting to just mark both the attribute target, as well as the attribute, with formatter annotations so only their formatting is touched - unfortunately when ReplaceNode is executed, for some reason it's throwing an exception telling me "The node is not part of the tree."

Why does `documentEditor.AddAttribute(attributeTarget, attributeSyntax)` work as standalone, if `documentEditor.ReplaceNode(attributeTarget, modAttrTarget)` throws an exception? I don't quite understand that. If the arguments were swapped it would make sense obviously.

**Comment by CyrusNajmabadi** [comment]
It's really hard to tell what's going on as your sample code is not complete.  For example, with GetTransformedDocumentAsync, i have no idea where `CSharpSyntaxNode attributeTarget` came from.

**Comment by taori** [comment]
@CyrusNajmabadi The full code is here https://github.com/dotnet/roslyn/issues/29611#issue-355919889

Essentially attributeTarget can be FieldDeclarationSyntax, ClassDeclarationSyntax, MethodDeclarationSyntax. What's puzzeling me about this is that, AddAttribute correctly identifiers attributeTarget as part of the documentEditor's syntax tree, while ReplaceNode doesn't think that it is.

**Comment by CyrusNajmabadi** [comment]
@taori here are some things that are going wrong with your above code:

```#
var modAttrTarget = attributeTarget.WithAdditionalAnnotations(Formatter.Annotation);
documentEditor.ReplaceNode(attributeTarget, modAttrTarget);
documentEditor.AddAttribute(modAttrTarget, attributeSyntax);
```

The problem here is that each edit is applied *sequentially*, but using the *original* tree as the way the make the determination about what to do.  So, when you do 'AddAttribute', you're saying "i want to add this attributeSyntax onto the modAttrTarget".  However, "modAttrTarget" is not a node from this document, so the editor doesn't really know what's going on.

Instead of doing all the above, what you should do instead is just do something like the following:

```c#
documentEditor.AddAttribute(attributeTarget, attributeSyntax);
documentEditor.ReplaceNode(attributeTarget, (current, _) => current.WithAdditionalAnnotations(Formatter.Annotation);
```

This may look confusing.  It looks like you're adding an attribute to something only to immediately replace it.  However, the way the editor works with the call to ReplaceNode is that it goes and find 'attributeTarget' (even after 'attributeSyntax' has been added to ti), it then passes that *updated* target through to 'current' in the lambda, allowing you to see the 'current' form of and allowing you to mutate *that*.

**Comment by taori** [comment]
@CyrusNajmabadi I see. You're right in that being confusing. I would not have imagined the DocumentEditor to do so much tracking for me. Since ReplaceNode does not throw an exception if used the way you suggested i'll close this one.

Thanks alot for the clarification. Much appreciated.
