### ISSUE TITLE
"Add accessibility modifiers" lightbulb fix dialogue misleading

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#29633]
With the following .editorconfig file:

`[*.cs]`
`dotnet_style_require_accessibility_modifiers = never:warning`

I would assume that when the rule is violated, the lightbulb pop-up would display "Remove accessibility modifiers". Instead, it displays "Add accessibility modifiers", even when the modifier is being removed, which I think is a little misleading.
 
![accessibilitymodifiers](https://user-images.githubusercontent.com/16968319/44936451-a2b78280-ad29-11e8-8541-036fd7ad267f.png)

**Comment by CyrusNajmabadi** [comment]
Title should also not be "Accessibility modifiers required".  But more like "Redundant accessibility modifiers not allowed."
