### ISSUE TITLE
Operation Action is not triggered in VS 2017

### ISSUE THREAD

**Issue by dropsonic** [dotnet/roslyn#29648]
**Version Used**: 
v1.3.2 (Roslyn packages), Visual Studio 2017 (v15.7.5)

**Steps to Reproduce**:
I have an analyzer which registers an operation action. This action is triggered in my unit tests with IOperation feature enabled. But in Visual Studio (analyzers are deployed in VSIX package) this action is not triggered at all(I checked it under debug).
Project file that I use for testing purposes contains IOperation feature:

    <PropertyGroup>
        <Features>IOperation</Features>
    </PropertyGroup>

The code inside the analyzer:

    public override void Initialize(AnalysisContext context)
    {
    	context.RegisterCompilationStartAction(compilationStartContext =>
    	{
    		compilationStartContext.RegisterOperationAction(c => AnalyzeLambda(c), OperationKind.LambdaExpression);
    	});
    }

    private void AnalyzeLambda(OperationAnalysisContext context)
    {
        // some code
    }

The code that I'm analyzing:

    ...
    DoSomething((a, b) => a + b);
    ....

**Expected Behavior**:
Operation action is triggered.
**Actual Behavior**:
Operation action is not triggered at all.

**Comment by sharwell** [comment]
Stable IOperation APIs are not available in Roslyn 1.x. You will need to use one of the following approaches:

1. Use the same version of the compiler your analyzer is compiled against (1.3.2) to use the experimental APIs
2. Recompile your analyzers against the stable API (or any newer version)

The IOperation APIs were first added in either 2.6.0 or 2.7.0 (the tags for these releases are missing on GitHub, so I can't determine the APIs that shipped in the final 2.6.0 build).

**Comment by dropsonic** [comment]
@sharwell thanks a lot!
