### ISSUE TITLE
C# formatter's "Make private fields readonly" option fails to consider conditionally complied code.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29646]
The feature works great up until the field is only used for some compile options.
At which point it makes an assigned field readonly when it does get used, just not with the currently selected (in the navagation bar) compile constants.

Ran into this issue when making a library support mutliple targets (netstandard2 and net451).

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/321181/c-formatters-make-private-fields-readonly-option-f.html
VSTS ticketId: 671722_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
@mavasani This is another item to consider for future improvements to the conflict reporting UI. The current behavior of the analyzer is correct for the given context, but we should improve awareness surrounding breaking changes outside the current analysis scope.

**Comment by sharwell** [comment]
Tentatively resolving as **Won't Fix**, but taking it to a design review and will update the issue based on that meeting.

**Comment by mavasani** [comment]
Completely agree with @CyrusNajmabadi here.

**Comment by sharwell** [comment]
Design review conclusion: @CyrusNajmabadi described the recommended approach. The current analyzer behavior is already aligned with our general approach.
