### ISSUE TITLE
Someone please help me getting know how Decimal is sealed class ? or can we inherit class from struct class like Decimal ?

### ISSUE THREAD

**Issue by anirudhagupta** [dotnet/roslyn#29659]
I am trying to write 

```
 public class Deciphal: Decimal
    {

    }
```

Today I was checking if Decimal is sealed a class, it's not the sealed class, I am trying to make a class derived from that class. I am getting an error that Decimal is sealed class.  Please clear the confusion, it's happening because Decimal is a struct.

Is it possible to inherit a class from decimal, If I can't make a custom type inherited from Decimal, what could be other option available for me?

**Comment by d-dizhevsky** [comment]
`System.Decimal` is a struct and thus you cannot inherit it.
https://github.com/dotnet/corefx/blob/816056b2a835f5c68f3b2bfaa81bd4bb5ba0932a/src/Common/src/CoreLib/System/Decimal.cs#L58

**Comment by jaredpar** [comment]
As @d-dizhevsky mentioned the `Decimal` type is a `struct` and it's not possible to inherit from a `struct` in C# (and most .NET languages).
