### ISSUE TITLE
VB semantic tests dumping core on Linux

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#29660]
Not much data other than the following:

```
14:10:25 [m/mnt/j/workspace/dotnet_roslyn/master/ubuntu_16_debug_prtest/build/scripts/tests.sh: line 55:  6337 Aborted                 (core dumped) ${runner} "${xunit_console}" "${file_name[@]}" -xml "${log_file}" -parallel none
14:10:33 Assembly /mnt/j/workspace/dotnet_roslyn/master/ubuntu_16_debug_prtest/Binaries/Debug/UnitTests/Microsoft.CodeAnalysis.VisualBasic.Emit.UnitTests/netcoreapp2.0/Microsoft.CodeAnalysis.VisualBasic.Emit.UnitTests.dll failed
14:10:33 Running dotnet /mnt/j/workspace/dotnet_roslyn/master/ubuntu_16_debug_prtest/Binaries/Debug/UnitTests/Microsoft.CodeAnalysis.VisualBasic.Semantic.UnitTests/netcoreapp2.0/Microsoft.CodeAnalysis.VisualBasic.Semantic.UnitTests.dll
14:10:34 xUnit.net Console Runner (64-bit .NET Core 4.6.0.0)
```

The tests causing the crash in CodeGenExprLamba are now commented out. This bug tracks re-enabling them once the CoreClr issue is fixed.

**Comment by jaredpar** [comment]
This looks like a dupe of the GC stress bug now. Since moving to the 2.1.3 runtime I can run the VB semantic tests locally 100 times in a row.

**Comment by agocke** [comment]
This is also happening with WinRT tests. I'm going to disable them on Linux. WinRT tests aren't very relevant for Linux anyway.

**Comment by jaredpar** [comment]
Can you include a link to the failure?

**Comment by jasonmalinowski** [comment]
@jaredpar: I was looking in Microsoft.CodeAnalysis.VisualBasic.Semantic.UnitTests.vbproj for unrelated reasons and I see this is still open -- is it worth removing the block and seeing if it's still happening?

**Comment by jaredpar** [comment]
Yeah it's been four years, hopefully that bug is fixed now :smile:

**Comment by jasonmalinowski** [comment]
Time to find out with https://github.com/dotnet/roslyn/pull/58659!
