### ISSUE TITLE
Edit and Continue for members of generic types

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#29667]
Modifying or adding a method in a generic type is not currently supported: https://github.com/dotnet/roslyn/wiki/EnC-Supported-Edits#not-supported-edits This seems like a big-ticket item, but please consider implementing it.

It comes up a lot for me. Right now, for example, I'm debugging an application and want to try eight permutations in a generic class's constructor. Building and setting up the scenario eight times is not as fun as EnC would be.

**Comment by tmat** [comment]
Note that this requires support in the CLR and the debugger. If it gets implemented it will likely be for Core CLR only.

**Comment by jnm2** [comment]
@tmat 

> If it gets implemented it will likely be for Core CLR only.

It would be fantastic if this could be shared with .NET Framework. Even after .NET Core 3.0 arrives, there are so many library and application projects I'm involved in that target or multitarget .NET Framework.

**Comment by tmat** [comment]
Implemented by https://github.com/dotnet/roslyn/pull/67918

**Comment by wouterst79** [comment]
Awesome, I can't wait to try it!

**Comment by tmat** [comment]
Note: requires the latest .NET 8 preview.
