### ISSUE TITLE
Attribute data is printed differently on CoreCLR

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#29672]
The `NonNullTypesAttribute_Injected` test is failing on both CoreCLR legs in CI.
The `AttributeData.ToString()` method prints the flags in different orders.
That method gets its ordering from `MetadataReader` (`MetadataReader.GetTypeDefinition(typeDef).GetFields()`).

On CoreCLR:
`System.AttributeUsageAttribute(System.AttributeTargets.Class | System.AttributeTargets.Constructor | System.AttributeTargets.Delegate | System.AttributeTargets.Enum | System.AttributeTargets.Event | System.AttributeTargets.Field | System.AttributeTargets.Interface | System.AttributeTargets.Method | System.AttributeTargets.Module | System.AttributeTargets.Property | System.AttributeTargets.Struct)`

On Windows:
`System.AttributeUsageAttribute(System.AttributeTargets.Module | System.AttributeTargets.Class | System.AttributeTargets.Struct | System.AttributeTargets.Enum | System.AttributeTargets.Constructor | System.AttributeTargets.Method | System.AttributeTargets.Property | System.AttributeTargets.Field | System.AttributeTargets.Event | System.AttributeTargets.Interface | System.AttributeTargets.Delegate)`

**Comment by jaredpar** [comment]
@jcouv I can't find this test in our code base any longer. Is it relevant now that we've moved to the `#nullable enable` design?

**Comment by jcouv** [comment]
No, can be closed indeed. Thanks
