### ISSUE TITLE
Array type conversions and checks don't work for arrays of primitive types

### ISSUE THREAD

**Issue by RunDevelopment** [dotnet/roslyn#29680]
**Version Used**: 

C# 7.3

**Steps to Reproduce**:

Consider the following example:

```c#
object foo = new int[] { -1, 2, 3 };

Console.WriteLine(foo is int[]); // True
Console.WriteLine(foo is uint[]); // True
Console.WriteLine(foo as uint[]); // System.Int32[]
Console.WriteLine(((uint[]) foo)[0]); // 4294967295

switch (foo)
{
    case uint[] arr:
        Console.WriteLine("I will be executed.");
        break;
    case int[] arr:
        Console.WriteLine("I cannot be reached.");
        break;
}
```

So far so horrific but the best thing is that when you make it `int[] foo`, everything will work as expected.

This also extends to other primitive types:

```c#
((object) new byte[0]) is sbyte[] // true
((object) new short[0]) is ushort[] // true
((object) new int[0]) is uint[] // true
((object) new long[0]) is ulong[] // true
((object) new IntPtr[0]) is UIntPtr[] // true
((object) new IntPtr[0]) is ulong[] // true if 64 bit OS
```

(I used empty arrays as an example for simplicity because extra content does not change the result.)

`GetType()` still works as expected.

```c#
object bar = new int[] { 1, 2, 3 };
(bar as int[]).GetType() == (bar as uint[]).GetType() // true
```

Interestingly, I cannot produce this effect with `char`, `float`, or `double` and user-defined value types don't work anyway even if they have the same width as a primitive type.

**Comment by jaredpar** [comment]
> So far so horrific but the best thing is that when you make it `int[]` foo, everything will work as expected.

Why do you feel the behavior is horrific here? This is just reflecting the realities of the .NET type system where certain forms of type punning are allowed. The C# type system itself does not support them which is why you can't directly caste `int[]` to `uint[]`. However .NET itself allows them and C# won't let developer code attempt to cast from `object` to any reference or value type. 

> Interestingly, I cannot produce this effect with char, float, or double and user-defined value types don't work anyway even if they have the same width as a primitive type.

This is because there is no type punning allowed at the runtime level for these types.

**Comment by RunDevelopment** [comment]
> certain forms of type punning are allowed.

Is there a specification of what forms are allowed. Because I was unable to find this kind of type punning. I mean, I'm just doing type casts and nothing fancy/unsafe like using pointers. (At least on the C# surface.)

> Why do you feel the behavior is horrific here?

Because this is a place where I do not expect type punning to happen. 
Plus this seems like such a strange behavior of managed code that I can only consider this a bug.
Or is actually how C# is supposed to behave?
```c#
((object) new byte[0]) is sbyte[] // true
```

**Comment by jaredpar** [comment]
> Is there a specification of what forms are allowed

@davidwrighton probably has a full list. The ones I'm aware of are `int[]` to `uint[]` and `byte[]` to `sbyte[]`. 

> Or is actually how C# is supposed to behave?

Yes / no. The C# type system is a layer on top of the .NET Type system. In many cases it's a 1:1 relationship but there are cases where C# adds additional restrictions and cases where it adds additional capabilities. 

The inability to convert from `int[]` to `uint[]` is one such restriction that exists in C# but not .NET. This typically can't be observed but it can be if you know how to subvert the checks C# is capable of making. In this particular case casing to `object` subverts the C# compiler ability to verify you're not casting `int[]` to `uint[]`

Now as to why the C# team originally decided to do this ... I have no idea. Likely a decision lost to history.

**Comment by RunDevelopment** [comment]
Is there something that explains the differences between the .Net Type systeme and the C# type system because all artikels I found say that they are the same.

**Comment by davidwrighton** [comment]
@RunDevelopment There isn't a particular reference for the differences between the .NET type system and the C# type system that I'm aware of. Sorry. But for the detail on what is convertible... See Section I.8.7 of partition one of the ECMA 335 standard. https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf 

In particular, Rules 5,6 and 7 of Section I.8.7.1 and the definition of "array-element-compatible-with" defined later in that section, and then the definition of the "reduced type" of a type T in section I.8.7

Effectively, arrays of int/uint, short/ushort, long/ulong, byte/sbyte are compatible. In addition, arrays of enums, also can support such casts. And finally, the rule 7 is incomplete, and all compatible runtimes actually support the rule 7 rule for IList<T>, IEnumerable<T>, ICollection<T>, (and on runtimes which support the interfaces... IReadOnlyList<T>, and IReadOnlyCollection<T>)

**Comment by RunDevelopment** [comment]
@davidwrighton Thank you!

I'm going to close this issue now as it is not a bug.
