### ISSUE TITLE
Various C# Text Editor Options don't show up in search

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#29681]
**Repro**
1. Open Visual Studio
2. Open `Tools->Options`
3. In the search box, type something like `decompile`

**Expected Behavior**
The `Enable navigation to decompiled sources (experimental)` option should appear (it lives under `Text Editor->C#->Advanced`)

**Actual Behavior**
The search finds nothing.

![image](https://user-images.githubusercontent.com/10487869/45119174-79bf3500-b10f-11e8-87fb-6f259f1b5493.png)

**Comment by dpoeschl** [comment]
A similar issue came up with Cyrus' RegEx work -- see https://github.com/dotnet/roslyn/pull/25517#discussion_r211345546

**Comment by tannergooding** [comment]
I marked this as "up for grabs". CC. @sharwell, @JieCarolHu
