### ISSUE TITLE
csc.exe crash/error (long method chain)

### ISSUE THREAD

**Issue by Nirklav** [dotnet/roslyn#29695]
We just have tool that ganerated code with very long methods chain.

**Version Used**: 
Rider - 2018.2.1
csc.exe - 2.7.0.62715 (db02128e)

**Steps to Reproduce**:

Try to build project: [CscCrash.zip](https://github.com/dotnet/roslyn/files/2356072/CscCrash.zip)

Or

1. Create project with code:
```
  internal class Program
  {
    public static void Main(string[] args)
    {
    }
  }

  public class Chain
  {
    public Chain Method()
    {
      return this;
    }
  }
```
2. Write code in main:
```
new Chain()
        .Method()
        .Method()
        .Method()
        .Method()
        .Method()
    /// ... and more calls (900+)
```
3. Compile this project.

**Expected Behavior**:
Project built.

**Actual Behavior**:
- csc.exe crash
- Microsoft.CSharp.Core.targets(84, 5): [MSB6006] "csc.exe" exited with code -2146232797.

**Comment by jaredpar** [comment]
The Roslyn compiler has limits on the maximum expression nesting level a single statement can have. Deep method chains like this can cause the compiler to overflow. This is an issue we're trying to address but it's quite involved and likely won't happen until at least the next major release. In the short term this can be worked around by breaking up the fluent calls into separate statements (around 500 calls is my recomendation). 

Duping against #9795
