### ISSUE TITLE
Improve 'Can not implicit convert' error message

### ISSUE THREAD

**Issue by olmobrutall** [dotnet/roslyn#29693]
Just a low hanging fruit to make Roslyn more usable.

1. The error should have an break line after 'to' to make it MUCH easier to read.

```
HARD TO READ
Cannot implicitly convert type 'Signum.Utilities.ResetLazy<System.Collections.Generic.Dictionary<IntTec.Entities.Codes.RecordCodeCharacteristicEntity, System.Collections.Generic.Dictionary<string, IntTec.Entities.Codes.RecordCodeAttributeEntity>>>' to 'Signum.Utilities.ResetLazy<System.Collections.Generic.Dictionary<IntTec.Entities.Codes.RecordCodeCharacteristicEntity, System.Collections.Generic.Dictionary<string, IntTec.Entities.Codes.RecordCodeAttributeDescriptionEmbedded>>>'
```

```
EASYTO READ
Cannot implicitly convert type 
'Signum.Utilities.ResetLazy<System.Collections.Generic.Dictionary<IntTec.Entities.Codes.RecordCodeCharacteristicEntity, System.Collections.Generic.Dictionary<string, IntTec.Entities.Codes.RecordCodeAttributeEntity>>>' to 
'Signum.Utilities.ResetLazy<System.Collections.Generic.Dictionary<IntTec.Entities.Codes.RecordCodeCharacteristicEntity, System.Collections.Generic.Dictionary<string, IntTec.Entities.Codes.RecordCodeAttributeDescriptionEmbedded>>>'
```

2. Removing all the namespaces in the error message (except if they are the only difference): 

```
Cannot implicitly convert type  

'ResetLazy<Dictionary<RecordCodeCharacteristicEntity, Dictionary<string, RecordCodeAttributeEntity>>>' to 
'ResetLazy<Dictionary<RecordCodeCharacteristicEntity, Dictionary<string, RecordCodeAttributeDescriptionEmbedded>>>
```

Thanks in advance

**Comment by CyrusNajmabadi** [comment]
I'm all for better errors.  But we have to be careful here.  For example, if the error is "Cannot concert type foo.BlahBlah to bar.BlahBlah", then that better not simplify down to "Cannot convert BlahBlah to BlahBlah".  Note: this is not a hypothetical concern.  TypeScript has some errors like this and it's majorly annoying to figure out what the problem is.

**Comment by jaredpar** [comment]
Very much agree with @CyrusNajmabadi here. In some cases the inclusion of the namespace can cause messages to be verbose but at the same time removing them can make them entirely unactionable. 

> The error should have an break line after 'to' to make it MUCH easier to read.

C# in general prefers single line error messages and leaves formatting up to the host of the compiler.

**Comment by svick** [comment]
@jaredpar The issue mentioned by @CyrusNajmabadi sounds to me like something that can be solved, not a deal-breaker.

You would probably want to be very careful, to make sure important information is not lost (e.g. if the message is "Cannot convert from 'Foo.Derived' to 'Bar.Base'", you want to keep the namespaces there), but I think that still leaves common cases where namespaces can be safely hidden (like the one in the original post).

**Comment by CyrusNajmabadi** [comment]
Yes.  To be clear, i wasn't saying that this should *not* be done.  Merely that one has to be *super careful* when doing this work.  The cure shouldn't be worse than the disease after all :)
