### ISSUE TITLE
SymbolSearch throws on task center

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#29694]
got this exception while doing other work

>	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.TaskStatusCenter.TaskStatusCenterModel.PreRegister(Microsoft.VisualStudio.TaskStatusCenter.TaskHandlerOptions options, Microsoft.VisualStudio.TaskStatusCenter.TaskProgressData data) Line 137	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.SymbolSearch.VisualStudioSymbolSearchProgressService.OnDownloadFullDatabaseStartedWorkerAsync(string title) Line 68	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.SymbolSearch.VisualStudioSymbolSearchProgressService.OnDownloadFullDatabaseStartedAsync(string title) Line 35	C#
 	Microsoft.CodeAnalysis.EditorFeatures.Wpf.dll!Microsoft.CodeAnalysis.SymbolSearch.SymbolSearchUpdateEngine.Updater.DownloadFullDatabaseAsync() Line 230	C#
 	Microsoft.CodeAnalysis.EditorFeatures.Wpf.dll!Microsoft.CodeAnalysis.SymbolSearch.SymbolSearchUpdateEngine.Updater.UpdateDatabaseInBackgroundWorkerAsync() Line 186	C#
 	Microsoft.CodeAnalysis.EditorFeatures.Wpf.dll!Microsoft.CodeAnalysis.SymbolSearch.SymbolSearchUpdateEngine.Updater.UpdateInBackgroundAsync() Line 120	C#
 	Microsoft.CodeAnalysis.EditorFeatures.Wpf.dll!Microsoft.CodeAnalysis.SymbolSearch.SymbolSearchUpdateEngine.UpdateContinuouslyAsync(string source, string localSettingsDirectory) Line 81	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.SymbolSearch.VisualStudioSymbolSearchService.UpdateSourceInBackgroundAsync(string sourceName) Line 108	C#

....

with this exception
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: DisplayTaskDetails
  Source=Microsoft.VisualStudio.Shell.UI.Internal
  StackTrace:
   at Microsoft.VisualStudio.TaskStatusCenter.TaskStatusCenterModel.PreRegister(TaskHandlerOptions options, TaskProgressData data) in F:\dd\src\env\shell\UIInternal\Packages\TaskStatusCenter\Model\TaskStatusCenterModel.cs:line 139

basically, this code

```csharp
 private static TaskHandlerOptions GetOptions(string title)
        {
            var options = new TaskHandlerOptions
            {
                Title = title,
                ActionsAfterCompletion = CompletionActions.RetainOnFaulted
            };

            return options;
        }
```

doesn't set DisplayTaskDetails and the TaskStatusCenterModel.PreRegister throws since it is a contract violation to have ActionsAfterCompletion but doesn't have DisplayTaskDetails set.

Exception has been reported as NFW but since it is not on by default, probably we haven't noticed it? 
tagging @ivanbasov 

anyway, so, after exception, try/catch catch the exception, report NFW and ignore the failure and move on. 

this is cosmetic (progress bar), so doesn't feel like high priority, but looks like has been broken since 2017.

not sure why this particular code path is wrapped in try/catch and set to ignore exception though. the code path... doesn't do anything except progress.

**Comment by CyrusNajmabadi** [comment]
> doesn't set DisplayTaskDetails and the TaskStatusCenterModel.PreRegister throws since it is a contract violation to have ActionsAfterCompletion but doesn't have DisplayTaskDetails set.

That is a breaking change.  This was not in the contract of this API before.

**Comment by heejaechang** [comment]
I dont know. simple history shows, it was like this since 2017 when this file is first introduced. but it could come from other file, so. anyway, it is how it is now.
