### ISSUE TITLE
Bad local function capture analysis for nameof operator

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#29721]
**Version Used**: 
Visual Studio 15.8.2

**Steps to Reproduce**:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/5644458/45226206-db8ac500-b2f0-11e8-9f2d-61093b13828e.png">
<img width="239" alt="image" src="https://user-images.githubusercontent.com/5644458/45226221-e6455a00-b2f0-11e8-94e2-f7308d899c3b.png">

**Expected Behavior**:
The `nameof` **references** the parameter, but does not actually **use** it (in generated IL). It's quite a special case, and no other element behaves like it. 

**Actual Behavior**:
Currently `nameof` is considered like other operators.

**Comment by agocke** [comment]
I can't repro this behavior. It doesn't look like the generated code creates any space in the closure environment frame for `nameof` values.

**Comment by huoyaoyuan** [comment]
@agocke The generated code is fine, but IDE quick info is mismatched with it.

**Comment by agocke** [comment]
That's true, but that list just means variables that are free within the local function scope, meaning that they are defined in the outer scope, so `offset` should appear there. Consider, if you were to make offset a variable in a nested scope that doesn't include the local function, the nameof call would fail, so for that purpose it's still important to know if it's captured.

**Comment by huoyaoyuan** [comment]
I think displaying real compiled capture information is more useful than just semantics structure.
