### ISSUE TITLE
use new JsonRpc automatic proxy generation feature

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#29725]
right now, we do something like this to call remote side

InvokeAsync("MethodNameAsync", arguments and etc)

but with new feature in JsonRpc we can do this

IMyInterface proxy = jsonRpc.Attach<IMyInterface>(...)

proxy.MethodNameAsync(....)

so that we can use strongly typed interface rather than using string.

see this - https://github.com/Microsoft/vs-streamjsonrpc/blob/6972f058360aade5ed47a7e0d6b417ff0cabf910/src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs#L23-L59

**Comment by tmat** [comment]
Also, let's use some faster serialization than Newtonsoft.Json. Perhaps a binary serialization like protobuf or [Bond](https://github.com/Microsoft/bond).

**Comment by tmat** [comment]
@peterwald

**Comment by heejaechang** [comment]
@AArnott is adding support that to JsonRpc.

but Bond or protobuf requires redefining DTO types using their spec language. so we might just directly use Stream and do conversion ourselves using ObjectWriter/Reader.

**Comment by heejaechang** [comment]
I already use ObjectWriter/Reader + stream directly without JsonRpc to move data between VS and OOP for Roslyn workspace which is fast enough and doesn't require us to redefine every single roslyn types in Bond or protobuf.

**Comment by heejaechang** [comment]
linking to other discussions we have been having

https://github.com/dotnet/testimpact/pull/2690#discussion_r215794259

**Comment by CyrusNajmabadi** [comment]
We're already doing this.  closing out.
