### ISSUE TITLE
Parentheses code-style is fading non-parentheses tokens

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#29736]
**Version Used**: VS 15.8.3

**Steps to Reproduce**:

```csharp
class Program
{
	static int Main()
	{
		var x = (Foo$$
	}

	static int Foo() => 0;
}
```

**Expected Behavior**:
`Foo` is never faded.

**Actual Behavior**:
`Foo` flickers to faded and back as you type. This doesn't happen if the leading `(` isn't present.

**Other Notes**:
What combination of settings will it take to stop fading parentheses entirely? It seems that, regardless of what code style settings I have, VS is constantly second-guessing what I've typed and making it harder to read my code.

**Comment by sharwell** [comment]
:memo: For whoever works on this, the solution is pretty easy. Simply avoid creating the diagnostic if either of the parentheses tokens is missing. :smile:

**Comment by CyrusNajmabadi** [comment]
Note: i would take it one step further.  I would fix up the helper ('CanRemoveParentheses') that these all sit on top of.  The reason for this is that we don't want the analyzer showing up here, but we *also* do not want any simplification passed executed by *other* features to remove these.
