### ISSUE TITLE
inappropriate suggestion in Generate From Usage in VB.NET

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#29748]
**Version Used**: 
VS.NET Community 15.7.4

In Generate From Usage there is something that bothers me, in VB.NET
```
  Dim X As Class1
  X.Value = 3
  Class1.Y = "Test"
```
In the second line, the suggestion list suggests many things, first of them is to define a method named Value ! No Function in VB.NET can accept a value assignment, especially that VB.NET doesn't define ref-return functions!
I waited two pr more versions to see this suggestion eliminated, especially that it were not there when the " Generate From Usage" first appeared!
I hope you erase such inappropriate suggestion.

**Comment by CyrusNajmabadi** [comment]
@MohammadHamdyGhanem Are you interesting in contributing a fix here?  I can point you to the relevant code.  Thanks!

**Comment by CyrusNajmabadi** [comment]
> So you only need to get the solution from the early version.

It unfortunately doesn't work that way :)   It's not like someone came a long and said: i will make it now work just for this case, and we can just remove that line of code.  What happened was that support was added for VB non-parenthesized method calls.  i.e.  you could write:  ```dim x = y.foo``` and want to generate a method for ```foo```.  So it's not a matter of just undoing that change as it would make that case also not work.  The solution will require ensuring that the above still works while making the other case not light up.

**Comment by CyrusNajmabadi** [comment]
Doesn't repro for me:

![image](https://user-images.githubusercontent.com/4564579/217961627-54b83893-9cfa-4344-a3a0-893f5b4f2a4f.png)
