### ISSUE TITLE
Avoid dependency on System.Collections.Immutable in AbstractConvertForEachToForCodeRefactoringProvider

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#29740]
The implementation of `AbstractConvertForEachToForCodeRefactoringProvider` [special cases ImmutableArray](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/ConvertForEachToFor/AbstractConvertForEachToForCodeRefactoringProvider.cs,258). 

It should instead work for any type that has `Length` property and implements an indexer `get_Item(int)`.

Test `ConvertForEachToForTests.ImmutableArray` also references System.Collections.Immutable as a metadata reference. It should instead define a minimal ImmutableArray-like type that implements pattern recognized by `AbstractConvertForEachToForCodeRefactoringProvider`.

Skipping the test for now since it references netstandard2.0 version of System.Collections.Immutable with .NET Framework 4.5 System.Runtime facade.

**Comment by sharwell** [comment]
> Test `ConvertForEachToForTests.ImmutableArray` also references System.Collections.Immutable as a metadata reference.  

A test written in this form is expected to pass. A test written in the alternative form would also be expected to pass, but is unrelated to the problem that led to skipping the test.

**Comment by tmat** [comment]
The main problem is that the test should not depend on the target framework the test project is build against. The test can either include an exact copy of ImmutableArray implementation in source form, or the functionality can be generalized to not require ImmutableArray at all.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
