### ISSUE TITLE
IDE0009 when using `new` in list initializers

### ISSUE THREAD

**Issue by jeremyVignelles** [dotnet/roslyn#29744]
**Version Used**: VS pro 15.8.3

**Steps to Reproduce**:

This code shows the error:
```
                var test = new List<string>
                {
                    new string('c', 2)
                };
```

**Expected Behavior**:
I'm not using a field, `this` is not relevant here

**Actual Behavior**:

> IDE0009 : Add 'this.' ...

The quick fix does nothing.

**Comment by zaytsev-victor** [comment]
@jeremyVignelles as I know it is already fixed in master. But it isn't ported to 18.x version (or even in 19.x).
I hope that it will be ported to 18.x because it breaks "use 'this'" rule (especially with new formatting rules.)

**Comment by CyrusNajmabadi** [comment]
@jinujoseph Another report of this issue. Still on hte list to consider porting back to 15.8?

**Comment by jinujoseph** [comment]
this has been ported over to [15.9](https://github.com/dotnet/roslyn/pull/29449) , doesn't meet the 15.8 bar
