### ISSUE TITLE
CS1503 reported for array of error type

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#29751]
**Version Used**: 38f415

**Steps to Reproduce**:

```csharp
namespace Namespace1 {
    using Namespace2;
    
    public static class Client {
        public static void Method(IntPtr value) {
            Host.Method(value); // No error here 👍
        }

        public static void Method(IntPtr[] value) {
            Host.Method(value); // Error here 😒
        }
    }
}

namespace Namespace2
{
    using System;

    public static class Host {
        public static void Method(IntPtr value) { }
        public static void Method(IntPtr[] value) { }
    }
}
```

**Expected Behavior**:

Two errors:

```text
error CS0246: The type or namespace name 'IntPtr' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'IntPtr' could not be found (are you missing a using directive or an assembly reference?)
```

**Actual Behavior**:

Three errors:

```text
error CS0246: The type or namespace name 'IntPtr' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'IntPtr' could not be found (are you missing a using directive or an assembly reference?)
error CS1503: Argument 1: cannot convert from 'IntPtr[]' to 'System.IntPtr'
```

**Comment by jaredpar** [comment]
This behavior is "By Design". The compiler has determined that it has sufficient information to do method body binding. At that point yes overload resolution is doomed to failure for this parameter but the compiler will still attempt to do it.

**Comment by sharwell** [comment]
@jaredpar We currently have a check to avoid cascading errors in some scenarios:

https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs#L1067-L1072

What if we simply expand this to avoid return without additional diagnostic if the argument's type contains an error type?

**Comment by jaredpar** [comment]
Possibly reasonable. @gafter has more context

**Comment by sharwell** [comment]
Thanks, I hit this during some testing of the new analyzer test library where `DiagnosticResult` changed namespaces and a large number large files used `DiagnosticResult[]`. The fallout of errors made it difficult to focus on the ones most relevant to fix first.
