### ISSUE TITLE
csc2.exe crashes after reinstalling toolset package

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#2979]
This repros on VSPro_Platform 22919.00

1. Create a new C# console application
2. Run these commands in the Package Manager Console:

        install-package Microsoft.Net.ToolsetCompilers -version 1.0.0-rc2-20150415-05
        install-package StyleCop.Analyzers -version 1.0.0-alpha006

3. Rebuild (no errors printed in error list or output window – yay!)
4. Run these commands in the Package Manager Console:

        uninstall-package Microsoft.Net.ToolsetCompilers

5. Rebuild (Lots of errors in output window and error list, as expected)
6. Reinstall toolset:

        install-package Microsoft.Net.ToolsetCompilers -version 1.0.0-rc2-20150415-05

7. Rebuild

Csc2.exe crashes
It will crash repeatedly with each rebuild after this (even from the command line).

**Comment by jaredpar** [comment]
I tried and was unable to reproduce this using VSPRO_1 22905 patched with the latest Roslyn compilers.  I'm unsurprised though because we've recently made several fixes in this area (and more on the way).
