### ISSUE TITLE
Inlining with [MethodImpl(MethodImplOptions.AggressiveInlining)] doesn't work

### ISSUE THREAD

**Issue by Necronux** [dotnet/roslyn#29795]
I don't know if roslyn repo is the right place to post, or it should be posted in coreclr repo. Excuse me for the mistake.

**Steps to Reproduce**:

```csharp
using System;
using System.Runtime.CompilerServices; 

public static class DecimalExtensions
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]    
    public static decimal Round(this decimal @this)
    {
        return decimal.Round(@this);
    }
}

public static class Program {
    public static void Main() {
        var x = 1.2134m.Round();
        var y = decimal.Round(1.2134m);
        Console.WriteLine(x);
    }
}
```

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAGAAhwEYBuAWACh8jiA6AJQFcA7GNMOOgYQHswADpkQBlRADc0AYzhRSBKjgBMeKooDMtAGxElBACJwpHCBgCiAD3gsoaXjaoBvKgVcEA2gFk4MABa8AEwBJQQwACm8/QJCBDAB5AXZ7KDoAQQBzdIRZW3E4IJYMNBZi9IBKAF03BUpqnE0SHQCjEwwCBl5WALC/NCgCZuNINpwcXqgylzdnWuq3HAB2AZbhxk6WbtHxsopZ1wBfKkPKDW1dWiWZuobiHRwAFgJPCGKwsoIruddxCAQCCwIAF4CPQlMR1PcwGsum9dl9vr8CABPIHLIamaEbMKg8GQnZTL4kACcYQs+L2BGO+yAA

**Expected Behavior**:

`1.2134m.Round()` should look the same as call to `decimal.Round(1.2134m)`

**Actual Behavior**:

Call to `.Round` extension method calls wrapper instead of round directly.

**Comment by tannergooding** [comment]
You should log this against dotnet/coreclr. Roslyn/C# doesn't do anything special with this attribute, or is interpreted by the runtime

**Comment by tannergooding** [comment]
It's also worth mentioning that the IL view is the wrong view to look at for this optimization, the emitted IL call will always be to the extension method. The JIT does inlining when producing the actually native assembly code.

You may also want to check against the current CoreCLR bits, as I believe sharplab currently only displays the JIT ASM for full framework on Windows.

**Comment by Necronux** [comment]
> as I believe sharplab currently only displays the JIT ASM for full framework on Windows.

Thanks. I will verify that.

If the JITted ASM will be the same as sharplab I will open this issue in CoreCLR's repo.
