### ISSUE TITLE
Can't build latest roslyn from VS

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#29808]
I have the latest master.  I'm also on 15.9 Preview 2.  I've done a `git clean -xdf` and a `./restore`.  Trying to build in VS produces a ton of errors like this:

```
1>C:\GitHub\roslyn\Binaries\Obj\Microsoft.CodeAnalysis\Debug\cs\Microsoft.CodeAnalysis.resources.cs(14,30): error CS0433: The type 'AssemblyCompanyAttribute' exists in both 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
1>C:\GitHub\roslyn\Binaries\Obj\Microsoft.CodeAnalysis\Debug\cs\Microsoft.CodeAnalysis.resources.cs(15,30): error CS0433: The type 'AssemblyConfigurationAttribute' exists in both 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski @sharwell @jinujoseph any ideas?

**Comment by jaredpar** [comment]
Did you install the new .NET SDK version?

**Comment by jaredpar** [comment]
https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building%2C%20Debugging%2C%20and%20Testing%20on%20Windows.md

**Comment by CyrusNajmabadi** [comment]
@jaredpar That worked.  Thanks!  Feel free to send feedback to relevant parties about the lack of message here :)

**Comment by jaredpar** [comment]
CC @KathleenDollard, @nguerrera 

Hmm. That's really surprising. I would've thought our global.json would've warned the incorrect SDK was installed. 

Also worried as this may be a bug in the new SDK. We took a new SDK not for any build features but as a precursor to merging a PR that depended on some new features. That PR is still open hence it's not the build cause here. Effectively we just took a new SDK version and then somehow implicitly depended on it. I don't _think_ we made a change here that depended on this. CC @tmat in case he knows of one.

**Comment by nguerrera** [comment]
https://github.com/dotnet/project-system/issues/2467

**Comment by nguerrera** [comment]
Actually, this looks different. I have never seen the errors in the original post before having any relationship to SDK resolution. Did anyone else see those errors? Are there repro steps?

**Comment by jaredpar** [comment]
My guess is that you can reproduce this by:

1. Installing only the 2.1.300 RTM SDK
1. Attempting to build Roslyn master

**Comment by jaredpar** [comment]
Adding dupe to CLi issue as well: https://github.com/dotnet/cli/issues/6795
