### ISSUE TITLE
Transient build errors related to SourceLink

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#29816]
I regularly encounter the error below while working in inner loop (changing code and running unittests).
Trying to re-run the unittest usually works.

```
1>------ Build started: Project: CSharpCompilerSemanticTest, Configuration: Debug Any CPU ------
1>C:\Users\jcouv\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63001-01\build\Microsoft.Build.Tasks.Git.targets(28,49): error MSB4064: The "LocalRepositoryId" parameter is not supported by the "Microsoft.Build.Tasks.Git.GetRepositoryUrl" task. Verify the parameter exists on the task, and it is a settable public instance property.
1>C:\Users\jcouv\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63001-01\build\Microsoft.Build.Tasks.Git.targets(28,5): error MSB4063: The "Microsoft.Build.Tasks.Git.GetRepositoryUrl" task could not be initialized with its input parameters.
1>Done building project "CSharpCompilerSemanticTest.csproj" -- FAILED.
```

@tmat Any idea what might be causing this?

For what it's worth, I'm using a recent 15.9 preview 2.

**Comment by tmat** [comment]
This indicates that an msbuild process is reused for building projects that reference different (incompatible) versions of SourceLink.

**Comment by jcouv** [comment]
I'm having trouble to square this explanation with my observations: 
- following your comment, I killed all background `msbuild.exe` processes. Yet the problem still occurs (note that I have a single VS instance running and didn't do any command-line builds).
- why does re-trying works?

So I'm left wondering, how did I get into this situation (both on my home and work machines) and how do I get out of it?

**Comment by tmat** [comment]
hmm, that's odd.

**Comment by tmat** [comment]
so it never repros when building from command line?

**Comment by jcouv** [comment]
I haven't tried from the command-line. I only build from VS (as part of running tests), and any time I make a code change I was getting this error, then I would re-try and the build would succeed.
I'll try from the command- line.

**Comment by tmat** [comment]
Are you running tests from Test Explorer?

**Comment by jcouv** [comment]
Yes, I use VS command corresponding to the "Run Test(s)" menu (`TestExplorer.RunAllTestsInContext`).

**Comment by jcouv** [comment]
I was not able to repro the issue from the command line (`msbuild /v:m /m <path-to-test-proj>`).
The issue does repro with TestDriven.Net however.

**Comment by tmat** [comment]
@jcouv Is this still a problem?

**Comment by jcouv** [comment]
No longer a problem. Not sure what fixed it. Closing
