### ISSUE TITLE
Suggestion: Figure out a way to make Task<TResult> covariant

### ISSUE THREAD

**Issue by chrisaut** [dotnet/roslyn#2981]
**Problem statement**
If you have a Method eg.

``` C#
public Task<string> GetStringAsync() 
{
    return Task.FromResult("This is annoying");
}
```

you cannot view the ```Task<string>``` as a ```Task<object>```, although logically this should work just fine.

For example you cannot then pass the Task to another (general) method that takes a ```Task<object>``` (it could take a non-generic Task only).

Let's say I have an interface:

``` C#
public interface IAsyncValueProducer<T>
{
    Task<T> ProduceValueAsync();
}
```

I cannot mark it as ```IAsyncValueProducer<out T>``` because ```Task<T>``` is not covariant.

Thus, I cannot view an ```IAsyncValueProducer<string>``` as an ```IAsyncValueProducer<object>``` etc., although this would work fine for non Async versions and it should just work logically.

``` C#
public interface IValueProducer<out T>
{
    T ProduceValue();
}
```

**Suggestion:**
Define an interface 

``` C#
public interface ITask
{ /* Whatever */ }
public interface ITask<out TResult> : ITask
{
    TResult Result { get; }
} 
```

and make ```Task<TResult>``` implement that. Then this would chain down to other interfaces containing such methods as expected.

Furthermore, I believe currently you can only use the asnc keyword on Methods that return a Task (not an ITask),
so even if you wrap the Task yourself, eg. like this community project: https://github.com/jam40jeff/ITask
it's not a proper solution. As is explained in their wiki:
"Unfortunately, the C# compiler only supports marking methods with the  async  keyword if they return a  ```System.Threading.Tasks.Task``` or a  ```System.Threading.Tasks.Task<TResult> ```."
So this would have to be changed in the compiler, thus the suggestion is here instead of in corefx.

I understand async when using await is hardcoded to produce these Task objects, it could still do that when it sees the method returing ```ITask<T>```.

Thoughts?

Edited to fix Generic Type display

**Comment by AdamSpeight2008** [comment]
I was think that we could add a `narrowing ctype` cast to `task<t>`.
By constraining `<T where T : U >`  then realised that to do that it has to implement as a property and we currently don't permit generic args on properties.

**Comment by chrisaut** [comment]
TBH I don't understand what you mean by "narrowing ctype". It seems to be a custom, special cased solution for Task.

I think the only proper solution that will play nice with all the other language covariant scenarios is to do this properly by either creating interfaces as I suggested, or somehow add the ability to mark classes themselves as co/contravariant (check only public members) but I'm not sure if there are good reasons not to do that.

That being said, it would be nice to mark classes/structs directly, one of my other pet peeves is KeyValuePair, which could also perfectly be covariant. Argghh. Annoying. And Tuple, which might become much more relevant in the future with the proposed Tuple support in the language directly.

For these cases an interface is not ideal, as we don't wanna pay the cost of virtual method calls (and boxing) for something like an access to a KeyValuePair which as I understand it would be required if they simply implemented a newly created interface.

**Comment by ilmax** [comment]
+1 on this

**Comment by svick** [comment]
I have created [a UserVoice suggestion](https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/5754247-make-task-t-implement-covariant-interface-itask-o) for this some time ago.

**Comment by MgSam** [comment]
+1 Although I think this probably belongs in the .NET repo and not Roslyn. I remember reading WinRT had something to do with why Task<T> wasn't covariant. I always thought that was such a shame, given WinRT is such a narrow slice of the overall usage of .NET.

**Comment by bradphelan** [comment]
You can IObservable<T> instead of Task<T>. They are mostly interchangable.

**Comment by chrisaut** [comment]
@bradphelan I don't think that's true. IObservable<T> is to Task<T> as IEnumerable<T> is to T, what I mean is, it conveys a will push out valueS (emphasis on plural).

Furthermore, I cannot await, I have to wire up subscribers and all that. 
While one can probably find workarounds by rewriting their stuff as IObservable instead of Task of T, this suggestion is to make it "right", not to find workarounds.

**Comment by svick** [comment]
@chrisaut While I agree that `IObservable<T>` and `Task<T>` are not interchangeable, you *can* `await` `IObservable<T>` (it returns the last value before the sequence competed).

**Comment by AdamSpeight2008** [comment]
@chrisaut  A narrowing ctype or cast, where the result has the potential to lose some information.
In this example, we lose the fact the inner type is a T
```vb
Public Class eg(Of t)
  Public Shared Narrowing Operator CType (e As eg(Of t)) As eg(Of object)

  End Operator
End Class
```

**Comment by chrisaut** [comment]
@svick interesting, but this does not seem to work for me (VS2015 RC)
```C#
public class Test
{
    public IObservable<string> SObs()
    {
        throw new NotImplementedException();
    }

    public async Task AwaitIObsAsync()
    {
        await SObs(); // I cannot await here
    }
}
```
Compiler informs me:
```
Severity	Code	Description	Project	File	Line
Error	CS1061	'IObservable<string>' does not contain a definition for 'GetAwaiter' and no extension method 'GetAwaiter' accepting a first argument of type 'IObservable<string>' could be found (are you missing a using directive or an assembly reference?)
```
Is this something that Rx brings in maybe? In any case we agree that it's probably not the right approach to tackle this annoyance.

@AdamSpeight2008 thanks I see. Even if you could get that to work automatically, this would be like java: type erasure :-) I don't think it's a proper solution either.

**Comment by svick** [comment]
@chrisaut 

> Is this something that Rx brings in maybe?

Yes, it is. `IObservable` is nigh useless without Rx, so I didn't consider anyone would be using `IObservable` without Rx.

**Comment by whut** [comment]
Just a note about the initial suggestion from @chrisaut  on introducing:

````
public interface ITask
{ /* Whatever */ }
public interface ITask<out TResult> : ITask
{
    TResult Result { get; }
} 
````

There should be also an interface like:
````
public interface ITaskWithResult
{
    object Result { get; }
}
````
And the Task<T> should implement it using explicit interface method implementation, just like the .NET collections do in such scenario. This way I could easily consume task result without knowing what the T is. I think this should be a general design rule for generic types in .NET: provide also non-generic interface, to allow to access the functionality in "generic way".

For example then I could have code like:
````
void ConsumeAllTasks()
{
    foreach(ITaskWithResult task in someTasks)
    {
        PassTheResultSomewhereElse(task.Result);
    }
}
````
Now it is not possible to write such code, as I need to provide the T generic parameter. Such type of code is often needed to write somewhere deep inside application infrastructure, where I do not know the T, so I can't make the `ConsumeAllTasks` also a generic method. Now I need to use reflection to access the Result.

BTW ThreadLocal<T> have the same issue.

**Comment by paulirwin** [comment]
Here's an example that I ran into that perfectly demonstrates this problem (anonymized):

```C#
public Task<IReadOnlyCollection<long>> GetIdsAsync() {
    return _context.Foos.Where(... some logic here...).Select(i => i.Id).ToListAsync(); 
    // Compiler error: Cannot implicitly convert type 'Task<List<long>>' to 'Task<IReadOnlyCollection<long>>'
}
```

Of course, there is a workaround to this by marking the method as async and adding await after the return, but this results in an unnecessary performance hit as now it has to generate the full async state machine and synchronization context work instead of just passing the Task along. I'm not sure if there's a straightforward way for the compiler to auto-elide the async/await in this case because the covariance problem still remains. 

(Of course, more involved workarounds also exist, like creating your own `IQueryable<T>.ToReadOnlyCollectionAsync()` extension method.)

If there were an `ITask<out T>` interface on `Task<T>` that would solve this problem, I think?

**Comment by CyrusNajmabadi** [comment]
This looks like something that needs to be on csharplang (if it's asking for a language change), not dotnet/roslyn.  Though it's unclear to me what the actual proposal is.

**Comment by ares128** [comment]
+1

**Comment by ares128** [comment]
think of u have a interface 
interface Base<out T>where T : U
{
 T DoSomeThing();
}
to async interface 
interface Base<out T>where T : U
{
 Task<T> DoSomeThing();
}
but u can not

**Comment by KalleOlaviNiemitalo** [comment]
> this would have to be changed in the compiler

The compiler has been changed and <https://github.com/jam40jeff/ITask/pull/5> lets you implement `async ITask<TResult>` methods.

**Comment by chrisaut** [comment]
I still think this should be provided "out of the box", but with custom awaitables this can be implemented ourselves now as that library demonstrates. Closing.

**Comment by MgSam** [comment]
@chrisaut I don't think this issue should be closed. The fact that it's technically possible using a library is nice, but providing such types should be addressed at the framework level. This is especially poignant given C# 9.0 added covariant return types- a feature you cannot take advantage of in `async` methods because Task<T> does not allow covariance.

**Comment by svick** [comment]
@MgSam 

> This is especially poignant given C# 9.0 added covariant return types- a feature you cannot take advantage of in `async` methods because Task does not allow covariance.

Technically, you can. Any library that supports `async ITask<T>` methods (including e.g. the MorseCode.ITask mentioned above) also supports covariant return types.

**Comment by MgSam** [comment]
@svick  Yes, that was my point. It requires third party libraries currently. It needs to come out of the box.

**Comment by iam3yal** [comment]
@CyrusNajmabadi 

> This looks like something that needs to be on csharplang (if it's asking for a language change), not dotnet/roslyn. Though it's unclear to me what the actual proposal is.

Allow to do things like this:
```
public Task<ICollection<T>> ToListAsync<T>(IQueryable<T> queryable)
    => queryable.ToListAsync();
```
When unwrapped `ToListAsync` returns `List<T>` but what I really need to return is `ICollection<T>` so atm I need to either rely on a 3rd-party lib as mentioned above that is absolutely a no go in my case or use async/await that is just a waste in this case. I hope it's clear.

**Comment by CyrusNajmabadi** [comment]
@iam3yal ICollection<T> is no variant at all.  So i don't see how this could possibly work.

**Comment by sethzollinger** [comment]
Since this will not be included OOTB. Could anyone share a working example or library/nuget? Otherwise I believe this is still relevant / not possible, because it breaks covariance in task-based code.

I tried to use [MorseCode.ITask](https://github.com/jam40jeff/ITask), it seems to no longer be maintained, nevertheless it compiles/runs. But code using it can no longer be [debugged]( https://github.com/jam40jeff/ITask/issues/14). It tried to create my own (simplified) library using the documentation: [Async Task Types in C# ](https://github.com/dotnet/roslyn/blob/main/docs/features/task-types.md). I also tried to - like MorseCode.ITask did - just proxy `System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>`, so I would not have to copy/manage too much boiler plate code. But I ended up having the same problem. Either the Visual Studio debugger does not support custom task method builders or I am just missing something that is either obvious or not documented or this is just not really supported in code outside the core runtime/sdk.

A simple task-like-type just implementing `GetAwaiter` works as expected, which however leads to lots of methods producing a `Task` requiring to be proxied with a wrapper method, to return an `ITask`.

**Comment by idchlife** [comment]
With the lack of attention to this situation and the richness of the .NET ecosystem, I assume that not many people have really had problems implementing feature-rich, resilient tools without a covariant Task.

Meaning, we are the few people who probably think the wrong way.

Can anyone point me in the right direction? How would one write code like this without using Task<out T>?

```csharp
public interface IRepository<out TType> where TType : MyBaseInterfaceType {
  public TType FindById(int id);

  public Task<TType> FindByIdAsync(int id); // Whoops error
}
```

I want repositories to provide ability to use them synchronously or asynchronously. Almost each database driver have 2 method types, sync and Async. Those can be utilized in repositories.

I think this is a somewhat good approach which allows the end user of the library to structure their code and decide: use threads or asynchronous approach.

Any ideas?
