### ISSUE TITLE
Track Nullable Value Type Null State

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#29817]
LDM decided that we want to track the null state of nullable value types as well. This work item tracks our implementation.

While implementing, we need to update the public API docs to reflect that nullable value types are tracked, as the docs currently say they are not.

**Comment by jcouv** [comment]
I think we're done with the implementation of this. Can this be closed? If not, could you clarify what is left to do?

**Comment by gafter** [comment]
I believe this was done in or before https://github.com/dotnet/roslyn/pull/33648.
