### ISSUE TITLE
Remove beta tag from C# 8.0 and VB 16 and update default and latest

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#29819]
Should be more or less reverting the fix for https://github.com/dotnet/roslyn/issues/29150

Also, we should revert test changes from https://github.com/dotnet/roslyn/pull/29973 (which changed TestOptions.Regular to mean C# 8.0 and VB 16)

Note we should also remove the beta tag from the IDE drop-down in project-system. (PR that added it: https://github.com/dotnet/project-system/pull/4091)

We don't yet have an appropriate milestone to track this, so I'm parking in 16.0 for now.

As we make that change, we'll want to careful and explicitly document that "default" will change meaning in that `16.<something>` release, as we are going with option (1) below.

-----

When fixing this, we should also fix https://github.com/dotnet/roslyn/issues/33821 (help message for langversion)

-----
Previously it would have been possible for an entire team to use VS2017 (15.0 through 15.9) with LangVersion=default.
But with dev16, if some team members are on 16.0 (default -> 7.0) and some others are on 16.3 (default -> 8.0, for sake of discussion), there will be a problem with LangVersion=default.

Some options:
1. accept this and educate users 
2. keep ‘default -> 7.0’ for the entire release. But that breaks the meaning of “default” (ie. latest major release).
3. renamed C# 8.0 to C# 7.4
4. ship all the runtime-independent features as C# 8.0 (RTM, not beta) with dev16 RTM, and the remaining features ship in dev16.3 with .NET Core 3.0 as C# 8.1

----
The beta label was added for C# 8.0 drop-down in https://github.com/dotnet/project-system/pull/4091

**Comment by 333fred** [comment]
We need to additionally revert this PR: https://github.com/dotnet/roslyn/pull/29973
