### ISSUE TITLE
Error after updating Visual Studio 2017 to v15.8.2 when running unit tests: Method 'Microsoft.Build.Utilities.ToolLocationHelper.GetPathToStandardLibraries' not found

### ISSUE THREAD

**Issue by mgmccarthy** [dotnet/roslyn#29810]
Posted in developercommunity.visualstudio.com as well:
https://developercommunity.visualstudio.com/content/problem/333202/error-after-updating-to-1582-when-running-unit-tes.html

After upgrading to Visual Studio 2017 v15.8.2 and running rosyln-based unit tests, they all fail.

The failure is on the line of code at **workspace.Diagnostics.Any** query:

```
[SetUpFixture]
public class SolutionSetup
    {
    [OneTimeSetUp]
    public async Task Load()
    {
        EnsureMsBuildCanBeFound();
        var solutionPath = GetSolutionPath();
        var workspace = MSBuildWorkspace.Create();
        Solution = await workspace.OpenSolutionAsync(solutionPath);

        if (workspace.Diagnostics.Any(d => !d.Message.Contains("If you have not done a build you can ignore this error")))
            Assert.Fail($"Failed to load solution: {string.Join(", ", workspace.Diagnostics.Select(d => d.Message))}");
        ...
        }
...
}
```

Full stack trace:
Msbuild failed when processing the file 'D:\Projects\IXRS\Study\IXRS.Client.Web.Tests\IXRS.Client.Web.Tests.csproj' with message: **Invalid static method invocation syntax**: "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget), $(TargetFrameworkRootPath), $(TargetFrameworkFallbackSearchPaths))". **Method 'Microsoft.Build.Utilities.ToolLocationHelper.GetPathToStandardLibraries' not found**. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, b)). C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets

## Things I've Tried
Update Microsoft.CodeAnalysis package from 2.6.1 to 2.9.0 (and all subsequent dependencies that go along with that package).
![image](https://user-images.githubusercontent.com/2428993/45448051-6ed04b80-b69f-11e8-88c0-aced3d5119e4.png)

This didn't work as once the upgrade was done, the compiler threw an exception that is no longer recognized MSBuildWorkspace
![image](https://user-images.githubusercontent.com/2428993/45448077-7e4f9480-b69f-11e8-91a0-89277301105b.png)

I then went out to find the missing NuGet package (where MSBuildWorkspace was moved to) and installed it:
![image](https://user-images.githubusercontent.com/2428993/45448102-8b6c8380-b69f-11e8-98b3-e939cd01babe.png)

the compiler error went away, but the same exact exception was thrown when running the roslyn-based tests

I THINK this is an MSBuild issue... just strange that upgrading to VS 2017 v15.8.2 would cause this type of failure.

**Version Used**: 
![image](https://user-images.githubusercontent.com/2428993/45449073-2c5c3e00-b6a2-11e8-99c9-269fbf0b1579.png)

**Comment by DustinCampbell** [comment]
Hi @mgmccarthy. What does the `EnsureMSBuildCanBeFound()` method do? Have you tried using the `Microsoft.Build.Locator` package to locate an instance of MSBuild?

**Comment by mgmccarthy** [comment]
@DustinCampbell, I've included the code below for `EnsureMSBuildCanBeFound()`. Although since it's returning void and would throw an exception if MSBuild could not be found, and the exception is thrown later in the `Load()` test method, I didn't think that code mattered:

```
private static void EnsureMsBuildCanBeFound()
{
    //Visual Studio 2017 ~15.3 introduced a bug in resolving the current version of MS Build
    //Below is the description of the issue as well as the work around
    //GitHub Issues:
    //https://github.com/Microsoft/msbuild/issues/2369
    //https://github.com/dotnet/roslyn/issues/15056
    var visualStudio2017 = GetVisualStudio2017Instance();
    if (visualStudio2017 != null)
    {
        Environment.SetEnvironmentVariable("VSINSTALLDIR", visualStudio2017.GetInstallationPath());
        Environment.SetEnvironmentVariable("VisualStudioVersion", "15.0");
    }

    var projectCollection = new ProjectCollection();
    if (projectCollection.GetToolset("15.0") == null)
        throw new Exception("MSBuild for Visual Studio 15.X not found - Let the Architecture Team know if this happens");
}
```

and here is the `GetVisualStudio2017Instance()` method:
```
private static ISetupInstance2 GetVisualStudio2017Instance()
{
    try
    {
        var visualStudioInstances = new SetupConfiguration().EnumAllInstances();

        int fetched;
        var instances = new ISetupInstance[1];
        do
        {
            visualStudioInstances.Next(1, instances, out fetched);
            if (fetched <= 0)
                continue;

            var instance = instances[0];
            var state = ((ISetupInstance2)instance).GetState();

            if (!Version.TryParse(instance.GetInstallationVersion(), out Version version))
                continue;

            if (state == InstanceState.Complete && version.Major == 15)
                return (ISetupInstance2)instance;

        } while (fetched > 0);
    }
    catch { }

    return null;
}
```

**Comment by DustinCampbell** [comment]
Thanks for added detail. You'll definitely want to try the Microsoft.Build.Locator package which includes the logic similar to what you have above. Here's an example from one of the Roslyn SDK templates that shows how to use it with MSBuildWorkspace: https://github.com/dotnet/roslyn-sdk/blob/master/src/Templates/VS2017/ProjectTemplates/CSharp/ConsoleApplication/Program.cs#L31-L34. Let me know if it works for you.

In addition, I have a draft out for an article that explains a little more of the background around the changes to MSBuildWorkspace and how to be successful with it: https://gist.github.com/DustinCampbell/32cd69d04ea1c08a16ae5c4cd21dd3a3.

Finally, we have produced a sample that shows MSBuildWorkspace (along with `Microsoft.Build.Locator`) in action: https://github.com/dotnet/roslyn-sdk/tree/master/samples/CSharp/SolutionExplorer.

**Comment by mgmccarthy** [comment]
@DustinCampbell, thanks so much for the guidance on this one. Unfortunately, because our team does not control our build server, which directly translates into our team not being able to control what version of MSBuild is installed on the build machine, even if Microsoft.Build.Loctator worked for running the Rosyln-based tests, those tests would fail when sent to the build server.

However, I'm going to spend my time creating a new branch of our project that does use Microsoft.Build.Locator and use the draft article you've published as a guide.

Thanks so much for the responsiveness and guidance on this one. I plan to circle back to this issue and update when I have Microsoft.Build.Locator working locally for me.

**Comment by DustinCampbell** [comment]
FWIW, so long as your build server is using VS 2017, the MSBuild locator will *probably* work with it (unless the version is very, very old). I'd aim for VS 2017 >= 15.6, but say, 15.3, would probably work.

**Comment by Chetic** [comment]
I started getting this issue after a visual studio upgrade. I have tried calling both `MSBuildLocator.RegisterDefaults()` and `MSBuildLocator.RegisterInstance(MSBuildLocator.QueryVisualStudioInstances().First())` before `MSBuildWorkspace.Create()`.

- "gacutil /l Microsoft.Build" does not list any 15.x versions
- I only have one instance of Visual Studio 2017 with MSBuild 15.9 installed
- Calling MSBuild.exe on the solution _does_ work
- The error is the following for every .csproj in the .sln: `Invalid static method invocation syntax: "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget), $(TargetFrameworkRootPath), $(TargetFrameworkFallbackSearchPaths))". Method 'Microsoft.Build.Utilities.ToolLocationHelper.GetPathToStandardLibraries' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets`

Please help.
