### ISSUE TITLE
Add tests to check tools|options pages against search keywords in VSPackage.resx file

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#29812]
Related to this PR: #29764,  we need to add tests to ensure we keep our options page in sync with our search keywords.

- Create a test that verifies the text of each text control in the options page control appears in this resource
- Create a test that verifies each substring (separated by ;) of this resource appears as the text of a control

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
