### ISSUE TITLE
EditorCompletion: Add a test for HandleNormalFiltering where itemsInList.IndexOf(i => Equals(GetOrCreateRoslynItem(i.CompletionItem), bestItem)) returns -1

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#29814]
Razor scenario: The scenario that is failing is typing ^j inside an empty @{} block in a razor document. Previously, this would invoke C# completion, however, it now doesn’t

Fix was applied. Need to cover it with a test.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
