### ISSUE TITLE
need to improve partial solution

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#29813]
we have GetDocumentWithFrozenPartialSemantics - http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Text/Extensions.cs,93

which in turn do this
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/SolutionState.cs,1632

it looks like we introduced a bug in this logic. since dev15, we start getting watson on Document.GetSemanticModelAsycn which throwing exception saying tree given to compilation doesn't belong to the compilation.

http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Compilation/CSharpCompilation.cs,1840

watson
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/169962?src=WorkItemMention&amp%3Bsrc-action=artifact_link

all Watsons are coming from the partial solution we created from the API above.

so far, all watsons (about 30 of them) I looked are from completion set. but the API seems used in completion, debug info and signature help. 

I tried to see how much this partial solution actually help improve user observable perf but i couldn't find any data.

so, now question is whether we keep this code for unknown perf benefit or just delete this optimization and just always use the regular solution.

probably need to discuss.

**Comment by heejaechang** [comment]
tagging @jinujoseph @ManishJayaswal @Pilchie  @dotnet/roslyn-ide 

my opinion is do A/B testing on this. and if there is no perceivable perf changes from a/b testing, we delete the perf optimization.

fortunately, a/b testing is quite easy

we either return the partial solution from the method (GetDocumentWithFrozenPartialSemantics) or return regular solution based on flight.

and we already have completion telemetry. so look that to see whether it actually changes anything.

**Comment by heejaechang** [comment]
sure, if we believe this actually improve perf enough for us to maintain the perf optimization, then we should spend time to improve it.

**Comment by heejaechang** [comment]
sure. I know what it is doing. but it does more optimization than that. we can start from getting rid of things like _lastestSolutionWithPartialCompilation or _timeOfLatestSolutionWithPartialCompilation.

**Comment by CyrusNajmabadi** [comment]
closing out as not planned.
