### ISSUE TITLE
Semantics of GetAnonymousFunctionControlFlowGraph and GetLocalFunctionControlFlowGraph

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#29836]
[ControlFlowGraph.GetAnonymousFunctionControlFlowGraph](http://source.roslyn.io/#q=GetAnonymousFunctionControlFlowGraph) and [ControlFlowGraph.GetLocalFunctionControlFlowGraph](http://source.roslyn.io/#q=GetLocalFunctionControlFlowGraph) currently work only if the input (`IFlowAnonymousFunctionOperation` or the local function `IMethodSymbol`) is defined in the method for the corresponding flow graph. However, if the local function or lambda is defined in an even outer scope, it does not work.

For example, consider the below source:
```
class Test
{
    void M1()
    {
        MyLocalFunction1();
        return;

        void MyLocalFunction1()
        {
            MyLocalFunction2();  // Need the control flow graph for invoked local function here.
        };

        void MyLocalFunction2()
        {
        };
    }
}
```

While analyzing the CFG for `MyLocalFunction1`, when we run into invocation `MyLocalFunction2()`, attempting to invoke `GetLocalFunctionControlFlowGraph` on MyLocalFunction1's CFG fails. This forces the analysis to always track the chain of parent control flow graphs to get the correct local function flow graph:
```
       public ControlFlowGraph GetLocalFunctionControlFlowGraph(IMethodSymbol localFunction)
             => _controlFlowGraph.LocalFunctions.Contains(localFunction) ?
                _controlFlowGraph.GetLocalFunctionControlFlowGraph(localFunction):
                _parentControlFlowGraphOpt?.GetLocalFunctionControlFlowGraph(localFunction);
```

The implementation is even more messier for getting the flow graph for anonymous functions/lambda, as we do not expose the defined lambdas on `ControlFlowGraph`:
```
        public ControlFlowGraph GetAnonymousFunctionControlFlowGraph(IFlowAnonymousFunctionOperation lambda)
        {
            try
            {
                return _controlFlowGraph.GetAnonymousFunctionControlFlowGraph(lambda);
            }
            catch (ArgumentOutOfRangeException)
            {
                return _parentControlFlowGraphOpt?.GetAnonymousFunctionControlFlowGraph(lambda);
            }
        }
```

**Feature Requests:**
1. Either change the semantics of `GetAnonymousFunctionControlFlowGraph` and `GetLocalFunctionControlFlowGraph` to walk up the parent chain of control flow graphs OR expose new helper methods on `ControlFlowGraph` to do the walk. I personally prefer the former, i.e. change semantics of existing APIs, unless we see big performance concerns.
2. Expose `ControlFlowGraph.FlowAnonymousFunctionOperations` similar to `ControlFlowGraph.LocalFunctions` which we currently expose.

**Comment by mavasani** [comment]
Tagging @AlekseyTs @gafter @333fred @DustinCampbell @tmat @jinujoseph @dotnet/analyzer-ioperation. We can discuss this at next CFG design meeting.

**Comment by AlekseyTs** [comment]
> as we do not expose the defined lambdas on ControlFlowGraph

I am not sure why this matters. Can lambdas be referenced by nodes that do not belong to the graph that defines it?

**Comment by mavasani** [comment]
@AlekseyTs @333fred @jinujoseph @heejaechang @gafter I found the test for the lambda case. Invocation myDelegate2 is the one where getting CFG fails.

```
using System;

class A : IDisposable
{
    public void Dispose()
    {
        throw new NotImplementedException();
    }
}

class Test
{
    delegate void MyDelegate(ref A a1, out A a2);
    void M1()
    {
        MyDelegate myDelegate2 = (ref A param3, out A param4) =>
        {
            param3 = new A();
            param4 = new A();
        };

        MyDelegate myDelegate1 = (ref A param1, out A param2) =>
        {
            myDelegate2(ref /*2*/param1, out /*2*/param2);
        };

        A a1 = null, a2;
        myDelegate1(ref /*1*/a1, out /*1*/a2);    // This should fire two diagnostics.
    }
}
```

**Comment by mavasani** [comment]
**Design Decision:**

1. Expose `ControlFlowGraph.Parent` property, which will be non-null for local function/anonymous function flow graphs and null otherwise.
2. Expose extension methods on `ControlFlowGraph` that walk up the parent chain to find a local function/anonymous function flow graph.

Additionally, we should expose `ControlFlowGraph.OwningSymbol` (or `ControlFlowGraph.ContainingSymbol`) property for exposing the symbol owning the executable code block/original operation for the control flow graph. This is not as trivial as other two items as our `ControlFlowGraph.Create` APIs only provide the root operations for which to generate the CFG, not the owning symbol. We may want to consider exposing such an owning symbol directly on `IOperation`, as each operation is owned by a specific member symbol, and then CFG's owning symbol can be trivially implemented using it's OriginalOperation's owning symbol. I will file a separate issue to track the design and implementation for this.

**Comment by mavasani** [comment]
Filed https://github.com/dotnet/roslyn/issues/30394: _Expose IOperation.OwningSymbol and/or ControlFlowGraph.OwningSymbol_

**Comment by mavasani** [comment]
> If we are tracking delegate values, can we even assume that the lambda is in any parent graph?

The analysis is conservative to only track values for lambdas declared in current method, and makes the PointsTo value as unknown if the reference can be assigned outside the current method. You are correct that a fully precise interprocedural analysis would need to link back to the method that defines the lambda and get its flow graph from it.
