### ISSUE TITLE
Changes to additional files don't seem to be taken into account by msbuild

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2983]
1. Rebuild BasicCodeAnalysis.csproj from command line with msbuild:
    1. `cd \src\Compilers\VisualBasic\Portable\`
    2. `msbuild /m /t:rebuild`, verify build succeeds.

2. Now delete a few lines from any of the PublicAPI.txt files in the folder.

3. Build vb compiler using msbuild: `msbuild /m`

**Expected:** Build fails due to analyzer errors

**Actual:** Build is not even executed and shows succeeded with original assembly. It seems that msbuild OR our Vbc msbuild task is not even invoking the VB compiler when only the additional files for the project have changed from previous build. 
If you explicitly invoke vbc/vbc2, then the build does fail as expected.

I am not sure if this an msbuild bug or a bug in our msbuild task, so filing it on compilers area path.

**Comment by jaredpar** [comment]
This is an external issue.  We don't control the rebuild logic in MSBuild.

**Comment by tmeschter** [comment]
@jaredpar That's not quite true. We own the core .targets files for C# and VB. It's up to us to tell MSBuild what our inputs and outputs are. If we're not doing that with additional files then MSBuild will have no idea that a change in an additional file requires a rebuild.

Once we've verified that the .targets files properly capture additional files as inputs, we can move this back to Area-External.

**Comment by mavasani** [comment]
@tmeschter is correct. Our .targets files doesn't specify `AdditionalFiles` as inputs for the target: https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Shared/Microsoft.CSharp.Core.targets#L4. We need to fix the targets.
