### ISSUE TITLE
workspace.TryApplyChanges may cause CurrentSolution.ProjectIds.Count to 0

### ISSUE THREAD

**Issue by gamert** [dotnet/roslyn#29876]
**Version Used**: 
2.9.0
**Steps to Reproduce**:

1. newSolution=Renamer.RenameSymbolAsync 
2. m_workspace.TryApplyChanges(newSolution)
3. check m_workspace.CurrentSolution.ProjectIds.Count

**Expected Behavior**:
Count !=0
**Actual Behavior**:
Count may be 0.

**Comment by CyrusNajmabadi** [comment]
These repro steps are not sufficient.  Can you please supply the code you are executing, along with all relevant projects/assets it will reference, so we can try to repro this?

**Comment by gamert** [comment]
Modify renamed file after Renamer.RenameSymbolAsync, and before the 
m_workspace.TryApplyChanges(newSolution)  will cause this。So My fault:)
