### ISSUE TITLE
Compiling netstandard libraries

### ISSUE THREAD

**Issue by raffaeler** [dotnet/roslyn#29878]
I did not find any advice about two different scenarios:
1. compiling code that has references who depends on both netstandard 1.5 and 2.0 (or any other version)
2. generating a new netstandard class library (which is meant to be generated and consumed on both Windows and Linux at runtime)

Can anyone please clarify what is the right way to proceed?

**Comment by jaredpar** [comment]
Can you give a bit more background here? This doesn't seem related to the C# compiler. Possibly an SDK issue.

**Comment by raffaeler** [comment]
The questions are about using programmatically (at runtime) the compiler to comply those two tasks from an application (no VS or other dev tools are involved out of Roslyn itself).
So I don't have any csproj to leverage.
Is this the right place for those questions?

**Comment by jaredpar** [comment]
Are you trying to compile against netstandard2.0 in memory then?

**Comment by raffaeler** [comment]
Yes, in some cases the assembly is persisted on disk. Other times it is just directly loaded from a stream.

**Comment by jaredpar** [comment]
Okay. If it's in memory compilation then you're going to have to provide all of the reference assemblies in memory as well. For netstandard2.0 you can likely get away with just using the netstandard2.0 reference DLL but for netstandard 1.3 you will need to include a lot of System.* facade assemblies. The full set is hard to layout as it depends quite a bit on what you are compiling.

**Comment by raffaeler** [comment]
In the first scenario (referencing a dll that is a nestandard library), if it depends on netstandard1.5, it is currently working by just referencing netstandard.dll 1.5 that gets copied in the bin folder.

The problem is that now the bin folder contains libraries both being dependent on 1.5 and 2.0 netstandard dependencies, so I am asking:
- is netstandard.dll 2.0 binary compatible with 1.5? Can I just copy netstandard2.0 in the bin folder (replacing the netstandard.dll 1.5)?
- what is the best location to reference netstandard 2.0 during memory compilation? Can I just force the copy of netstandard.dll 2.0 on my bin folder or what else?

Finally the second scenario. Let's say I will now **generate** dynamically only netstandard2.0 libraries. You are saying that all I should do is referencing netstandard.dll 2.0 and get rid of the mscorlib and other references normally used in .net 4.x, right?

Thanks!

**Comment by tmat** [comment]
See also https://github.com/dotnet/roslyn/wiki/Runtime-code-generation-using-Roslyn-compilations-in-.NET-Core-App

**Comment by jaredpar** [comment]
> The problem is that now the bin folder contains libraries both being dependent on 1.5 and 2.0 netstandard dependencies

Don't do this. It may function but it's definitely not correct. This is outside the scope of the compiler and probably belongs on dotnet/sdk where the experts live. How you go from a compiled DLL / EXE to a deployable set of binaries is best asked there.

**Comment by raffaeler** [comment]
@jaredpar I am not sure to have explained well the situation.
I am going in production with an app that will generate and execute code. Among the references of the generated code there could be both netstandard1.5 and netstandard2.0. So my question what is the best way to satisfy these requirements.

Most of the times, the generated binary is than generated and loaded from memory. In some cases it will be in a private folder, so the bin problem is not about the generated code but how to collect the needed references.
With mscorlib it is easy to have an 'official' folder, but this no more true with netstandard, since the dynamic compilation does not leverage nuget.

**Comment by tmat** [comment]
As noted on the wiki I'd recommend creating an empty C# project that has the same dependencies as you expect to have when you compile at runtime, run `msbuild /v:detailed test.csproj` and find what reference assemblies are passed to csc. Include those in embedded resources and pass them to the compilation.

**Comment by raffaeler** [comment]
Referencing the reference assemblies from a separate location resolved my issue. Thanks
