### ISSUE TITLE
Code fix "if statement can be simplified" doesn't optimise bool

### ISSUE THREAD

**Issue by ygoe** [dotnet/roslyn#29880]
**Version Used**: 

Visual Studio 15.8.3

**Steps to Reproduce**:

1. Write this code:

```csharp
bool Method()
{
    if (!Method2()) return false;
    return true;
}

bool Method2()
{
    return true;
}
```

2. Apply the code fix "if statement can be simplified"

**Expected Behavior**:

```csharp
bool Method()
{
    return Method2();
}
```

**Actual Behavior**:

```csharp
bool Method()
{
    return !Method2() ? false: true;
}
```

**Comment by CyrusNajmabadi** [comment]
Should be fixed with: https://github.com/dotnet/roslyn/pull/29036

**Comment by jinujoseph** [comment]
yep Validated against 15.9.P2 as well.

**Comment by ygoe** [comment]
No, I cannot confirm this fixed. The wrong fix is still applied in Visual Studio 15.9.6.

**Comment by CyrusNajmabadi** [comment]
@ygoe Can you try on a 16.0 preview?

**Comment by CyrusNajmabadi** [comment]
On my 16 preview i see:

![image](https://user-images.githubusercontent.com/4564579/52075530-63dc6180-2541-11e9-9b6e-f83457bf15d2.png)

**Comment by ygoe** [comment]
@CyrusNajmabadi Sorry, I don't have VS 2019 installed yet. It's just marked as fixed in 15.9 so I tried it. I'll try again when I have 16.0, I'll keep this on my follow-up list.

**Comment by CyrusNajmabadi** [comment]
@ygoe Sounds good.  Note: you can isntall these builds side-by-side without any issues.

**Comment by ygoe** [comment]
@CyrusNajmabadi Still cannot confirm the fix in VS 16.4.2. The code fix is not available anymore. Instead, I can invert the `if` statement which works as one might expect it. It doesn't simplify the code as described in the first coment though. Is that intentional?

**Comment by CyrusNajmabadi** [comment]
One 16.5p1:

![image](https://user-images.githubusercontent.com/4564579/71769010-979dd500-2ed0-11ea-99a7-7069badf6acb.png)

![image](https://user-images.githubusercontent.com/4564579/71769011-9d93b600-2ed0-11ea-8f08-40a85b3cd0c2.png)

On 16.4.2:

![image](https://user-images.githubusercontent.com/4564579/71769022-b43a0d00-2ed0-11ea-886c-e9148e377f78.png)

![image](https://user-images.githubusercontent.com/4564579/71769026-ba2fee00-2ed0-11ea-85c9-3f0748b462ee.png)

**Comment by ygoe** [comment]
Hm, I don't have that option. But it's good to see that it's supposed to work.
