### ISSUE TITLE
Proposal: Member scoped to property (and event)

### ISSUE THREAD

**Issue by erik-kallen** [dotnet/roslyn#2989]
Sometimes I find myself in a position where I want to guard against the use of a backing field from a property, even from the same class. I therefore propose a feature to scope a member to a property (or event) definition. E.g:

    class C {
        public int P {
            int _p;
            get { return _p; }
            set { ValidateNewP(value); _p = value; }
        }

        public void M() {
            _p = 10; // error
            P = 20; // (of course) OK
        }
    }

**Comment by bbarry** [comment]
exact duplicate #850

but yes :+1:

**Comment by jnm2** [comment]
Using a backing field without naming it was considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md
