### ISSUE TITLE
(Proposal) Coding Guidelines allowances.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#299]
The coding guidelines should be alter to allow the following styles. which aids the readability of the code.

* Align on the `:` of named parameters rather than lefthand edge of parmeter name
```c#
public static ImmutableArray<Diagnostic> GetAllMethodBodyDiagnostics(CSharpCompilation compilation, CancellationToken cancellationToken) 
{ 
  DiagnosticBag diagnostics = DiagnosticBag.GetInstance(); 
  CompileMethodBodies( 
                compilation: compilation,  
           moduleBeingBuilt: null,  
          generateDebugInfo: false,  
       hasDeclarationErrors: false,  
                     filter: null,  
                 filterTree: null,  
       filterSpanWithinTree: null, 
                diagnostics: diagnostics,  
          cancellationToken: cancellationToken ); 
  DocumentationCommentCompiler.WriteDocumentationCommentXml(compilation, null, null, diagnostics, cancellationToken); 
  compilation.ReportUnusedImports(diagnostics, cancellationToken); 
  
  return diagnostics.ToReadOnlyAndFree(); 
} 

```
vs
```c#
public static ImmutableArray<Diagnostic> GetAllMethodBodyDiagnostics(CSharpCompilation compilation, CancellationToken cancellationToken) 
{ 
    DiagnosticBag diagnostics = DiagnosticBag.GetInstance(); 
    CompileMethodBodies( 
         compilation: compilation,  
         moduleBeingBuilt: null,  
         generateDebugInfo: false,  
         hasDeclarationErrors: false,  
         filter: null,  
         filterTree: null,  
         filterSpanWithinTree: null, 
         diagnostics: diagnostics,  
         cancellationToken: cancellationToken); 
    DocumentationCommentCompiler.WriteDocumentationCommentXml(compilation, null, null, diagnostics, cancellationToken); 
    compilation.ReportUnusedImports(diagnostics, cancellationToken); *
    return diagnostics.ToReadOnlyAndFree(); 
} 

```

* Simple IF 
If the If statement is small and has no else, and the code block is small enough.
The combined width is less than the 80 character width limit.
```c#
if( arg0 == null ) throw new ArgumentException( nameof( arg0 ) );
if( arg0 == null ) { throw new ArgumentException( nameof( arg0 ) ); };
```
vs
```c#
if( arg0 == null )
{
    throw new ArgumentException( nameof( arg0 ) );
}
```
Consider multiple guards statements you are approaching halve of the length of the screen, ever before you've reached the core of the method.

* Simple case clause
```c#
select ( value )
{
 case 0: return "Zero";
 case 1: return "One";
 case 2: return "Two";
 // ...
 case 9: return "Nine";
 default:
   return "Foo";
}```
vs
```c#
select ( value )
{
 case 0:
   return "Zero";
 case 1: 
   return "One";
 case 2:
    return "Two";
 // ... 
 case 9:
    return "Nine";
 default:
   return "Foo";
}
```
15 LoC rather than 25 or 35 if you need to include the `break`
```
case 0: output = "Zero"; break; 
```

* 2 space indentation  
Consider the case of pattern-matching, each scope gets indented, 5 levels of indentation and you're already used a quarter of the permitted code width.

* Method Parameter align vertically  
If the method signature is getting "too" wide, then consider vertical alignment.
```c#
internal static MethodSymbol DefineScriptEntryPoint
  (    CSharpCompilation           compilation,
         PEModuleBuilder      moduleBeingBuilt,
              TypeSymbol            returnType,
                    bool  hasDeclarationErrors,
           DiagnosticBag  diagnostics
  ) 
{ 
```
```c#
internal static MethodSymbol DefineScriptEntryPoint(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuilt, TypeSymbol returnType, bool hasDeclarationErrors, DiagnosticBag diagnostics) 
{
```

**Comment by gafter** [comment]
It is more important to have coding guidelines than that they be any particular way. For every group of n people we are able to find 2n opinions about coding guidelines.

**Comment by jaredpar** [comment]
I do want to clear up one little bit.  The coding style is not just a Roslyn guideline, this is a guideline that is being embraced across the entire [.NET Foundation](https://github.com/dotnet) on GitHub.  The goal is to make it as easy as possible for customers who want to contribute or learn by presenting a single style, set of guidelines, API review process, etc ... across the organization. 

As such I'm closing this issue.  Decisions like this which affect all of the .NET Foundation are more appropriately discussed on the [corefx](https://github.com/dotnet/corefx) repo.  

Note: I do not believe that at this point significant changes to our style guidelines will be made.  As said before individual choices are very subjective, the important aspect is consistency.  Any changes at this point would require reformatting many thousands of files across a number of repos.  It's hard to justify that type of work.  

For the curious the following commit has a pretty detailed discussion of the motivation for having a single style and to a degree some of the individual style choices. 

> https://github.com/dotnet/corefx/commit/3251c1cae5860785cfb716d3822d11149a88e0fa

**Comment by jaredpar** [comment]
Also note that braces on an `if` are not required.  The argument validation logic can be shortened to:

``` csharp
if(arg0 == null)
    throw new ArgumentException(nameof( arg0 ));
```

**Comment by AdamSpeight2008** [comment]
@jaredpar Did you actually read my post?

I don't say anything about changing exist code's style, but amending the guidelines to allow alternative forms. If someone wants to go through and change the existing code, they can. Whether that pull-request would get excepted is a different question. 
If you did read it, you would have also have seen that I as included your example.

**Comment by jaredpar** [comment]
Yes I read the post. As I said in my response though the guidelines are not something the Rosyln team owns but rather the .NET Foundation. Discussions on changing it or amending them should occur on corefx.
