### ISSUE TITLE
DiagnosticEventTaskScheduler should name its threads

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#29922]
http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/DiagnosticEventTaskScheduler.cs,30

Looks like Roslyn starts long-running threads to spin the DiagnosticEventTaskScheduler. We should call `Thread.CurrentThread.Name = "Roslyn Diagnostics"` so that the threads used by Roslyn are clearly visible in the debugger. 

![image](https://user-images.githubusercontent.com/679326/45593429-5b411100-b93b-11e8-94bb-356e5aa47302.png)

**Comment by KirillOsenkov** [comment]
Same for http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/IntelliSense/Completion/PrioritizedTaskScheduler.cs,32

**Comment by ryzngard** [comment]
@heejaechang I'm happy to take this as a good way to dip my toes in

**Comment by heejaechang** [comment]
just checked. looks like since now we moved to .Net standard from portable. we have access to Thread type. so yes, we can do this. just do exactly same as what the other did.

**Comment by funcylambda** [comment]
@ryzngard - Are you still planning to take this? If not I'm happy to have a look tomorrow! :)

**Comment by ryzngard** [comment]
Sure, I'll get a PR up soon :) I have the changes locally

**Comment by yaakov-h** [comment]
With #30162 merged, should this be closed now?

**Comment by yaakov-h** [comment]
With #30162 merged, should this be closed now?

**Comment by yaakov-h** [comment]
With #30162 merged, should this be closed now?

**Comment by yaakov-h** [comment]
With #30162 merged, should this be closed now?

**Comment by KirillOsenkov** [comment]
Thank you so much! Much appreciated.
