### ISSUE TITLE
Erroneous IDE0044 messages in VS 15.8.1

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29925]
When a Class Level variable is only used as the index of a For Next loop within a Sub, message &quot;IDE0044 Make field readonly&quot; is displayed:

Imports Microsoft.VisualBasic
Public Class Class1
    Dim j As Integer
    Sub abc()
        Dim k As Integer
        For j = 1 To 3
            k += j
        Next
    End Sub
End Class

However, changing this to: &quot;ReadOnly j as Integer&quot; displays message: BC30064 'ReadOnly' variable cannot be the target of an assignment.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/319659/erroneous-ide0044-messages-in-vs-1581.html
VSTS ticketId: 669865_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't repro this.
