### ISSUE TITLE
EditorConfig: rules concerning var break code

### ISSUE THREAD

**Issue by lellid** [dotnet/roslyn#29935]
**Version Used**: VS Community editon 15.8.4

**Steps to Reproduce**:

When using the following .editorconfig file

```
# top-most EditorConfig file
root = true

[*.cs]
# Implicit and explicit types
csharp_style_var_for_built_in_types = true:none
csharp_style_var_when_type_is_apparent = true:silent
csharp_style_var_elsewhere = true:none
```

to format the code:
```
using System;
using System.Collections.Generic;
using System.Text;

namespace OutVarSimplification
{
  public class Example<TKey, TValue, TToken> where TKey : IComparable<TKey>
  {
    public bool TryPeek(out TKey key, out TValue value)
    {
      throw new NotImplementedException("Implementation irrelevant");
    }

    public bool TryPeek(out KeyValuePair<TKey, TValue> result, out TToken token)
    {
      throw new NotImplementedException("Implementation irrelevant");
    }
 
    public KeyValuePair<TKey, TValue> Peek()
    {
      KeyValuePair<TKey, TValue> result;
      TToken token;
      TryPeek(out result, out token);
      return result; // details irrelevant
    }
  }
}
```

the resulting code is no longer compilable due to an ambiguity between the two TryPeek methods:

```
using System;
using System.Collections.Generic;
using System.Text;

namespace OutVarSimplification
{
  public class Example<TKey, TValue, TToken> where TKey : IComparable<TKey>
  {
    public bool TryPeek(out TKey key, out TValue value)
    {
      throw new NotImplementedException("Implementation irrelevant");
    }

    public bool TryPeek(out KeyValuePair<TKey, TValue> result, out TToken token)
    {
      throw new NotImplementedException("Implementation irrelevant");
    }

    public KeyValuePair<TKey, TValue> Peek()
    {
      TryPeek(out var result, out var token);
      return result; // details irrelevant
    }
  }
}
```

**Expected Behavior**:

Don't execute formatting rules that lead to code that no longer compiles.

**Actual Behavior**:

Code does no longer compile due to an ambiguity between two methods (TryPeek).

**Comment by CyrusNajmabadi** [comment]
Hrmm.. weird.  I tried this out and i don't get any sort of compiler error.  But i def see some strange behavior here.  If you started with:

```c#
      TKey result;
      TValue token;
```

Then we offer to inline, but then the semantics change from one overload to the other.

**Comment by lellid** [comment]
Sorry, I forgot to mention that I used the menu (Edit->Advanced->Format Document) to format the document and that in Options/TextEditor/C#/CodeStyle/Formatting/Perform additional code cleanup during formatting all checkboxes (with the exception of the very first and the very last) were checked.

**Comment by ryzngard** [comment]
I'm able to repro this, the only real setting needed Is "Perform addition code cleanup during formatting" > "Apply inline 'out' variable preferences". 


Specifically, individual refactoring using ctrl+. to perform IDE0018 will keep one of the two types explicit so you don't get disambiguation like `TryPeek(out var result, out var token)`. Applying to the whole document doesn't do this.

**Comment by ryzngard** [comment]
I should note that I tested this on 15.8.8. I can start looking into fixing this.
