### ISSUE TITLE
Test Failure: ubuntu_16_debug_prtest tests failing for unknown reasons

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#29941]
Example: https://ci.dot.net/job/dotnet_roslyn/job/dev16.0.x/job/ubuntu_16_debug_prtest/13/ (see that queue for more examples)

Ends with `Build step 'Execute shell' marked build as failure`.

**Comment by dpoeschl** [comment]
@jaredpar Is this queue mostly owned by the compiler team? Have you seen this before?

**Comment by jaredpar** [comment]
Jenkins does a poor job of surfacing this error. Have to go up in the log a bit

```
01:03:19 [m/mnt/j/workspace/dotnet_roslyn/dev16.0.x/ubuntu_16_debug_prtest/build/scripts/tests.sh: line 55: 72140 Aborted                 (core dumped) ${runner} "${xunit_console}" "${file_name[@]}" -xml "${log_file}" -parallel none "${@:4}"
01:03:39 Assembly /mnt/j/workspace/dotnet_roslyn/dev16.0.x/ubuntu_16_debug_prtest/Binaries/Debug/UnitTests/Microsoft.CodeAnalysis.VisualBasic.Semantic.UnitTests/netcoreapp2.0/Microsoft.CodeAnalysis.VisualBasic.Semantic.UnitTests.dll failed
```

I recently saw this and disabled the VB semantic tests while I figure out what is going on here.

https://github.com/dotnet/roslyn/pull/29861
