### ISSUE TITLE
Finalize IDE support for `??=`

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#29948]
There are likely a few more places in the IDE layer to update for `??=` support after it's merged to dev16.0.x, including:
`UnwrapCompoundAssignment`: http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/ReplacePropertyWithMethods/AbstractReplacePropertyWithMethodsService.cs,6d51fab341c857cd,references
`IsCompoundAssignment`: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/SyntaxNodeExtensions.cs,efadba0caa88db20,references
`GetOperatorPrecedence`: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/ExpressionSyntaxExtensions.cs,f23f53d9b91d5532,references

**Comment by CyrusNajmabadi** [comment]
Have you looked at IsAnyAssignmentXXX and IsAssignmentXXX helpers?  we should walk backwards from those to see what is affected.  Also, can we have some type inference tests?  i.e. if i have:

```x ??= <-- what IDE type is inferred here```.

This matters for things like completoin preselection (i.e. if 'x' is an enum type), as well as code-gen for things like ```x ??= NewMethod(); <-- gen method here```

**Comment by jinujoseph** [comment]
cc @jasonmalinowski

**Comment by CyrusNajmabadi** [comment]
This will also affect: https://github.com/dotnet/roslyn/pull/29919

**Comment by 333fred** [comment]
Manual Testing Notes:

1. Formatting - Verify spacing around, no spacing inside
2. Indentation - Typing Enter in an unfinished statement indents the next line
3. GoToDef/Impl/FAR - Verify doesn't break
4. Find References on LHS shows as read/write /cc @mavasani 
5. Colorization - verify is colored as punctuation
6. Extract Method/Introduce Variable - Verify nothing is offered
7. Inline Temp - Verify nested cases `a ??= (b ??= 1) // b is inlined`
8. Convert to compound - do not attempt to convert `a = a ?? throw null` to `a ??= throw null // Throw expressions not allowed` /cc @CyrusNajmabadi 
9. Quick Info - Verify nothing shown
10. Ilspy - Verify something sensical is spit out
11. EE - What happens in immediate window
12. Breakpoint spans - Verify it makes sense

**Comment by CyrusNajmabadi** [comment]
1. Need completion to show up on the right side if this is an enum type.
2. if someone is generating a method on the left or right side, it should figure out the right type.

**Comment by jcouv** [comment]
@jinujoseph Can you assign for remaining validation? Compiler did the validation documented above.

**Comment by CyrusNajmabadi** [comment]
@333fred is there anything more to do with this issue?

**Comment by 333fred** [comment]
@CyrusNajmabadi I have no idea. I'm not sure what the IDE team has looked at here.

**Comment by CyrusNajmabadi** [comment]
Closing out as things are fine here.  we can run anything else as bugs.
