### ISSUE TITLE
Generated XML comments missing unicode

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29942]
To repro, open the metadata C# for InvalidOperationException. (I.e. press F12 on an &quot;InvalidOperationException&quot; keyword.)

Notice that the summary looks like this:

```csharp
// Summary:
//     The exception that is thrown when a method call is invalid for the object&#39;s
//     current state.
```

It has a unicode apostrophe character. It should stay as a unicode character in the XML that we see on screen. Instead, it's getting converted to the XML escape code, which is much less readable.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/330115/generated-xml-comments-missing-unicode.html
VSTS ticketId: 678463_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jnm2** [comment]
Is this https://github.com/dotnet/roslyn/issues/30092?

**Comment by sharwell** [comment]
@jnm2 No, this seems to be different

**Comment by jnm2** [comment]
Ah. I wondered if maybe the XML documentation itself was the common factor somehow.

**Comment by sharwell** [comment]
This is not a bug with Roslyn. The example is produced by Roslyn correctly interpreting the following incorrectly-written documentation comment (taken from System.Runtime.xml in Microsoft.NETCore.App 2.1.0):

```xml
<member name="T:System.InvalidOperationException">
  <summary>The exception that is thrown when a method call is invalid for the object&amp;#39;s current state.</summary>
</member>
```
