### ISSUE TITLE
Debugger can't evaluate list[0].first if T=ValueTuple

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#29951]
**Version Used**: VS15.8

**Steps to Reproduce**:

Compile this, follow the comments in the code:

```C#
using System;
using System.Collections.Generic;

namespace ConsoleApp8 {
	class Program {
		static void Main(string[] args) {
			var list = new List<(string first, string second)>();
			list.Add(("first", "second"));
			// Add the following expressions to the Watch window or hover over the expressions below:
			//		list[0].first
			//		list[0].second
			//		list[0].Item1
			//		list[0].Item2
			Console.WriteLine(list[0].first);
			Console.WriteLine(list[0].second);
			Console.WriteLine(list[0].Item1);
			Console.WriteLine(list[0].Item2);
			var tmp = list[0];
			// This works
			Console.WriteLine(tmp.first);
		}
	}
}

```

**Expected Behavior**:

When hovering over 'first', the string "first" is shown in the tooltip

**Actual Behavior**:

null is shown

**Comment by arveduil** [comment]
I would like to fix it, any hints for beginners?

**Comment by jinujoseph** [comment]
cc @jcouv , @tmat

**Comment by 0xd4d** [comment]
This can be closed and moved, it's not a Roslyn bug, it's a bug in the .NET debugger.

A `DebuggerValueTypeSlot` is created and its `m_dict` has two keys (fields) but instead of field type `System.String`, it's `System.__Canon`.

Field passed to GetField(): `System.String Item1`

Field stored in m_dict: `System.__Canon Item1`

The dictionary lookup fails.

**Comment by jcouv** [comment]
Thanks @0xd4d for the bug report and analysis. I have filed an [internal issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/694770) on the debugger.
I'll go ahead and close this roslyn issue.

**Comment by tmat** [comment]
Dup of https://github.com/dotnet/coreclr/issues/25519.
