### ISSUE TITLE
Comment Lines command changes 1 line, selects 10

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29982]
Reported by @AArnott 

When my caret is on just one line in the editor and I execute the Comment Lines command (Ctrl+K, Ctrl+C), the line is commented, but the next 9 lines are selected. If I repeat the command, all selected lines get commented.

I do not expect the selection to be extended 9 lines!

See repro steps.
Clone https://github.com/aarnott/nerdbank.streams   
and try on below method ( have not been able to repro outside this repro ) 

![99abe45e-0fd7-43c1-b718-4a88f165269e](https://user-images.githubusercontent.com/12449387/45656514-ca814700-ba9a-11e8-8121-85ee0ab8d533.gif)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/309271/comment-lines-command-changes-1-line-selects-10.html
VSTS ticketId: 662408_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@AArnott Can you supply your code so it doesn't have to be retyped?

**Comment by AArnott** [comment]
The file and method shown in the screenshot comes from here: https://github.com/AArnott/Nerdbank.Streams/blob/41a78421f145ccfc7c92e6dce6a14792e72ca966/src/Nerdbank.Streams.Tests/StreamUseStrictPipeReaderTests.cs#L44-L70

I haven't seen the repro for just a loose file though. It only seems to repro while in the context of a project. So you may need to clone the repo.

**Comment by CyrusNajmabadi** [comment]
Closing out as i can't repro this and we haven't heard about this from any othe rcustomer.
