### ISSUE TITLE
Allow collapsing 'case' blocks for switch statements.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#29998]

**Comment by AdamSpeight2008** [comment]
@CyrusNajmabadi
Just informing you that respective implementation for (`Select Case` blocks) is PR#27617

**Comment by CyrusNajmabadi** [comment]
@AdamSpeight2008 Great!  Can you roll the C# side of htis into your PR as well?

**Comment by jinujoseph** [comment]
**Design Meeting Notes**
Seems like a good idea, We should not collapse the case value itself, but anything under its body should be collapsible.  
also see related issue https://github.com/dotnet/roslyn/issues/35792

**Comment by kendrahavens** [comment]
[Developer community feedback +2](https://developercommunity.visualstudio.com/content/idea/467938/case-statements-in-a-switch-should-be-expandcollap.html)

**Comment by melicaster** [comment]
Anyone working on this? I think this is a good feature to have as now I have cases that is super big.

**Comment by sharwell** [comment]
@melicaster this is still up-for-grabs. Would you happen to be interested in picking it up? 😄

**Comment by AdamSpeight2008** [comment]
@melicaster  @sharwell  Other than the linked pull-request in the first reply?

**Comment by jmarolf** [comment]
@AdamSpeight2008 I believe you closed that PR, do you still want to work on this?

**Comment by AdamSpeight2008** [comment]
@jmarolf To honest I couldn't care less about who implements it, it was I (and the community) have wanted. So I implemented a version. Who implements "the version" don't care.

**Comment by CyrusNajmabadi** [comment]
@AdamSpeight2008 would you be willing to complete that original PR?  Someone else could potentially do the C# side (or you could do it if interested).  Thanks!

**Comment by CyrusNajmabadi** [comment]
@AdamSpeight2008 can you let us know what your plans are here?  thanks!

**Comment by AdamSpeight2008** [comment]
@CyrusNajmabadi  It was completed 4 years ago, I moved on.
You are someone else can rebase the pull request on the latest branch.

**Comment by ptuga** [comment]
Hello arkalyanms,

What does this mean?
I'm sorry but I don't understand. I've raised an issue with Microsoft and ended here.
Was the interface changed between 2017 and twas this feature removed in 2020?
I don't see any advantage removing the collapse symbols inside each case statement.

Please advise.
Many thanks.

Kind regards,
ptuga

**Comment by ptuga** [comment]
@AdamSpeight2008  Hello, sorry for my ignorance on the topic. I'm new on this environment. The pull request 27617 has comments going back to  Oct 31, 2018. Does this means the coding to enable the function I reported has been implemented or will be implemented at some point in the future (is it possible to know when)? As far I can experience, this isn't available in Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.4.1. Could you please clarify? Thank you

**Comment by CyrusNajmabadi** [comment]
@ptuga Taht PR was abandoned.  No work has been done since to enable this feature.  We would likely accept a PR from Adam (or you) on this topic if either of you are interested.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/66724.
