### ISSUE TITLE
rationalize AnalyzerReference/DiagnosticAnalzyer de-duplication logic

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#300]
it is possible for compilation to have more than one logically same analyzer reference/diagnostic drivers.

it could happen more easily in VS IDE, since there 2 entry points for analyzer references. one is through MEF and one is through project analyzer reference.

in those cases, we should de-duplicate the references to one so that we don't report same diagnostics twice.

currently we should AnalyzerReference.Display as its identity but that seems too fragile, we probably need to think a bit more about it.

**Comment by srivatsn** [comment]
This has been fixed now.
