### ISSUE TITLE
VB: Autocomplete should show and insert simplified name for enum members.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#30008]
**Version Used**:

Visual Studio Community 2017 v15.5.6

**Steps to Reproduce**:

Start with the following code:

```vb
Public Class CParent(Of TFoo)
  Protected Enum EFoo
    Blah
    Bleh
  End Enum
End Class

Public Class CChild
  Inherits CParent(Of Object)

End Class
```

Now we want to create a private field `TheEnumField` in class `CChild` whose type is the enum `EFoo` defined in the parent class `CParent(Of TFoo)`:

![vs_enum_autocomplete_1](https://user-images.githubusercontent.com/20465797/45718038-68ad0400-bba4-11e8-9453-a155139ab123.png)

As the above image shows, autocomplete is able to figure out that the enum type `EFoo` is in scope within class `CChild` and can be referenced without the fully-qualified name shown in the tooltip. This is expected and when you accept the suggestion, you end up with:

```vb
Public Class CChild
  Inherits CParent(Of Object)

  Private TheEnumField As EFoo
End Class
```

Now for some reason, if you want to initialise `TheEnumField` to some member of the enum `EFoo`, this time autocomplete suggests the fully-qualified names for the enum members:

![vs_enum_autocomplete_2](https://user-images.githubusercontent.com/20465797/45718435-a199a880-bba5-11e8-9223-4d9381ecd5c2.png)

If you accept one of the suggestions, the editor inserts the fully-qualified enum member name then immediately suggests that you remove the qualification!

![vs_enum_autocomplete_3](https://user-images.githubusercontent.com/20465797/45718641-7ebbc400-bba6-11e8-907a-a35bcf0538ca.png)

**Expected Behavior**:

The editor is already aware that the enum type `EFoo` is in scope within class `CChild` which is why it suggested the name in unqualified form when declaring the field `TheEnumField`. By extension, it also knows you can access enum members like `Blah` as `EFoo.Blah` (i.e without fully-qualifying the `EFoo` part) which is why it offers to simplify the name immediately after you accept its suggestion of the fully qualified enum member name `CParent(Of Object).EFoo.Blah`.

I believe the autocompletion behaviour for enum types and their individual members should be identical: in both scenarios, the simplified name should be shown and automatically inserted. It seems counter-productive to insert the fully-qualified name then immediately offer to simplify it!

**Comment by CyrusNajmabadi** [comment]
Note: this issue is not VB specific.  It affects C# as well.

**Comment by ericmutta** [comment]
@CyrusNajmabadi many thanks for following up, as always! :+1: :+1:

**Comment by ericmutta** [comment]
@jinujoseph thanks a lot for following up on this (and several other issues that I have filed) :+1: :+1:

**Comment by CyrusNajmabadi** [comment]
Unlikely to make any changes in these vb scenarios.
