### ISSUE TITLE
UseCompoundAssignment refactoring should support `??=` operator

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#30009]
The null-coalescing compound operator is being merged to master (https://github.com/dotnet/roslyn/pull/30006).

Once that is done and [UseCompoundAssignment](https://github.com/dotnet/roslyn/pull/29919) is merged, then it can be used for `??=` too.

**Comment by Paxxi** [comment]
I'm interested in this

**Comment by jcouv** [comment]
@Paxxi nice. Go for it. 
FYI @333fred @CyrusNajmabadi (they could provide pointers; I'm on vacation)

**Comment by CyrusNajmabadi** [comment]
@Paxxi Hopefully https://github.com/dotnet/roslyn/pull/29919 makes it clear enough what would need to be updated.  Let me know if you need more info!

**Comment by Paxxi** [comment]
I think I got it all, doubted myself a while because the design was so nicely done that just adding the syntax/expressionkind got it working 😄

**Comment by jinujoseph** [comment]
thanks @Paxxi
