### ISSUE TITLE
Building roslyn creates >10GB of duplicated data.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#30005]
After i build roslyn, i end up with >10GB of data duplicated across my drive.  This is both an intensely large amount of IO generated, and it just takes up valuable space.  for example, i'm on a 128GB laptop, so just building ends up taking up a massive amount of space. 

Here's an image to show how bad it is:

![image](https://user-images.githubusercontent.com/4564579/45715062-281f9d00-bb48-11e8-9206-bdb64f8d21c1.png)

As an example, there are over a dozen copies of Test.Resource.Proprietary, for >1GB of space just for that single file.  

It would be great if Roslyn could be much better here.  Either just building to a single location, or having these files hardlink to themselves.

**Comment by CyrusNajmabadi** [comment]
This is extremely bad when i have to switch between debug/release.  Basically, every time i do, i have to delete the *other* set of built files.

**Comment by CyrusNajmabadi** [comment]
tagging @sharwell @jcouv for ideas here.

**Comment by CyrusNajmabadi** [comment]
> Building to a single location isn't really an option. It violates basic build principles (double writes), causes write races during build and leads to non-deterministic errors when we mis-predict how NuGet and the SDK layout binaries.

Why would there be double-writes?  If someone already built the file, wouldn't it then satisfy the reference for whatever else needed it?

The main oddity is see is that we even need to lay things out in the first place such that there are N copies of this.  

It feels weird given that we should only be building it once (right?), so then anyone who needs it should just reference the single built version...

> Note: you should be able to just enable hard linking via environment variables before launching VS / MSBuild and have it take effect. It will work correctly and save space during build.

Could you link me (har har) to any info on how to do this?  I'm happy to try it out.

**Comment by tmat** [comment]
I wonder why NuGet doesn't make files in NuGet cache read-only. Wouldn't that prevent hard-linked files from accidental overwrites?

**Comment by jaredpar** [comment]
@CyrusNajmabadi 

> Why would there be double-writes? If someone already built the file, wouldn't it then satisfy the reference for whatever else needed it?

That isn't how MSBuild works. If you build two projects to the same output directory then every binary for each project will be copied. That means every shared dependency turns into a double write and a build race. 

This is still correct-ish when the dependencies are identical. Multi-targeting though mandates we have to partition our build though on some levels as dependencies are not identical. Attempting to predict what will be identical, which is necessary when you share build outputs, is not practical higher up the stack where you are mixing many different target framework monikers. You essentially have to re-implement NuGet and RAR. 

> Could you link me (har har) to any info on how to do this? I'm happy to try it out.

This seems to have the comprehensive list of variables to use.

http://automagik.piximo.me/2013/07/using-hard-links-in-your-builds.html

I may start using this again locally. As long as you don't try funny business like editing binaries in the output directory it will be just fine. We have a lot of validation logic to our build is correct and hence can support this.

**Comment by jaredpar** [comment]
@tmat 

> I wonder why NuGet doesn't make files in NuGet cache read-only. Wouldn't that prevent hard-linked files from accidental overwrites?

My guess would be compat. Likely a lot of code out there which depends on writing to the cache. Just a guess though.

I believe your suggestion would work though. I'm not 100% certain but I believe readonly is attached to the file and not the link.

https://docs.microsoft.com/en-us/windows/desktop/fileio/hard-links-and-junctions

**Comment by jaredpar** [comment]
This discussion reminded me it's been about ~2 years since I last ran a hard link experiment on my box. Decided to do it again and here are the results:

| | Build Time | Binaries Size Explorer | Binaries Size DU |
|-|-|-|-|
| No hard link | 4:00 | 13.9GB | 14.9GB |
| Hard links | 3:28 | 13.8GB | 1.5GB |

This machine is pretty beefy so it's possible the build time will be more dramatic on other machines. The binary size is fairly dramatic and will be consistent between machines.

Notes: 
- Binaries size explore measured by looking at file explorer output
- Binaries size DU measured using [du](https://docs.microsoft.com/en-us/sysinternals/downloads/du)
- Command lines
    - No hard links: `msbuild /v:m /m Roslyn.sln /p:DeployExtension=false`
    - Hard links: `msbuild /v:m /m Roslyn.sln /p:DeployExtension=false /p:CreateHardLinksForCopyFilesToOutputDirectoryIfPossible=true /p:CreateHardLinksForCopyAdditionalFilesIfPossible=true /p:CreateHardLinksForCopyLocalIfPossible=true /p:CreateHardLinksForPublishFilesIfPossible=true
`
- Before each run I ran `git clean -dxf .` and restored the solution

**Comment by xoofx** [comment]
> That isn't how MSBuild works. If you build two projects to the same output directory then every binary for each project will be copied. That means every shared dependency turns into a double write and a build race.

Wow, really, I thought that using `<UseCommonOutputDirectory>true</UseCommonOutputDirectory>` was precisely for this kind of scenario (assuming that projects don't output the same files)... but now reading @KirillOsenkov [blog post about it](https://blogs.msdn.microsoft.com/kirillosenkov/2015/04/04/using-a-common-intermediate-and-output-directory-for-your-solution/) he was mentioning this.  I was assuming that shared dependencies were not copied (ProjectReference at least, for the assembly reference I could workaround it with a proper CopyLocal), so it is not the case?

**Comment by jaredpar** [comment]
I’m less crisp on how common out directory functions. It’s possible they can’t avoid double write with dependencies. Seems unlikely though particularly in corner cases. Perhaps there is way I’m missing though. 

Real problem with common output is verifying it’s correct (no double writes). Also keeping it sane with all of the multi-targeting we have to do + ensuring subtle project changes don’t break the layout. 

The current method, which is really not anything custom just the basically the default, is easy to verify is correct. Used to have a lot of build headaches before we did this.

**Comment by jaredpar** [comment]
After thinking on this further I decided we should make this easy to use for developers. Have a PR out which lets you opt into this behavior by setting the environment variable `%ROSLYNUSEHARDLINKS%` to any value. Going to be experimenting with this myself going forward.

**Comment by jaredpar** [comment]
MSBuild followup issue https://github.com/Microsoft/msbuild/issues/3788
