### ISSUE TITLE
create signature help service like completion service

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30000]
unlike completion, quickinfo and signaturehelp are tightly coupled with interaction to editor.

for completion, one can use completionservice (http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionService.cs,63488567b33cdef8) to find out data on specific location, and completion itself uses that data to provide completion list to users.

but for quickinfo and signature, there is no such abstraction so, it is hard for someone to see what quickinfo or signaturehelp will be provided at specific location as pure data API. it requires one to go through editor interaction to get those data.

we should consider having data api for these.

**Comment by heejaechang** [comment]
tagging @jinujoseph

**Comment by CyrusNajmabadi** [comment]
Don't we have a Data api here for QuickInfo?  It's QuickInfoService: https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/QuickInfo/QuickInfoService.cs

It's already public and consumed by third parties.

**Comment by CyrusNajmabadi** [comment]
I think someone was working on something similar for SignatureHelp, but i'm not sure the state it ever got to.  SigHelp is definitely a big harder as the concept of a 'signature' is pretty hard to nail down across languages.

**Comment by heejaechang** [comment]
nice that we have one for quickinfo. I tried to search and somehow it didn't get hit. anyway. so, only thing left is signature help then.

**Comment by jinujoseph** [comment]
yep @JieCarolHu did the work to move quickinfo. 
Signature help is in editors todo list (not hi-priority at the moment)

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
