### ISSUE TITLE
Assert fired at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsCoreAsync

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#3001]
I hit the below assert while self-building Roslyn.sln with debug bits of Roslyn compiler as the toolset. This doesn't seem to affect release build of the compilers (from the same sources), so probably the assert needs to be re-adjusted here...

Below assert fires:
```c#
                try
                {
                    e = await CompilationEventQueue.DequeueAsync(cancellationToken).ConfigureAwait(false);
                }
                catch (TaskCanceledException)
                {
                    // When the queue is completed with a pending DequeueAsync return then a 
                    // TaskCanceledException will be thrown.  This just signals the queue is 
                    // complete and we should finish processing it.
                    Debug.Assert(CompilationEventQueue.IsCompleted, "DequeueAsync should never throw unless the AsyncQueue<T> is completed.");
                    break;
                }
```

**Call stack:**
>	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsCoreAsync(System.Threading.CancellationToken cancellationToken) Line 373	C#
 	[Resuming Async Method]	
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070	C#
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask) Line 810	C#
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3617	C#
 	mscorlib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetCanceled(System.Threading.CancellationToken tokenToRecord, object cancellationException) Line 654	C#
 	mscorlib.dll!System.Threading.Tasks.UnwrapPromise<Microsoft.CodeAnalysis.Diagnostics.CompilationEvent>.TrySetFromTask(System.Threading.Tasks.Task task, bool lookForOce) Line 7272	C#
 	mscorlib.dll!System.Threading.Tasks.UnwrapPromise<System.__Canon>.Invoke(System.Threading.Tasks.Task completingTask) Line 7146	C#
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3626	C#
 	mscorlib.dll!System.Threading.Tasks.Task.InternalCancel(bool bCancelNonExecutingOnly) Line 3478	C#
 	mscorlib.dll!System.Threading.CancellationCallbackInfo.ExecuteCallback() Line 1021	C#
 	mscorlib.dll!System.Threading.CancellationTokenSource.CancellationCallbackCoreWork(System.Threading.CancellationCallbackCoreWorkArguments args) Line 863	C#
 	mscorlib.dll!System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(bool throwOnFirstException) Line 808	C#
 	mscorlib.dll!System.Threading.CancellationTokenSource.NotifyCancellation(bool throwOnFirstException) Line 743	C#
 	mscorlib.dll!System.Threading.CancellationTokenSource.Cancel() Line 363	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.CommonCompiler.RunCore(System.IO.TextWriter consoleOutput, Microsoft.CodeAnalysis.ErrorLogger errorLogger, System.Threading.CancellationToken cancellationToken) Line 527	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.CommonCompiler.Run(System.IO.TextWriter consoleOutput, System.Threading.CancellationToken cancellationToken) Line 296	C#
 	VBCSCompiler.exe!Microsoft.CodeAnalysis.CompilerServer.CSharpCompilerServer.Run(System.IO.TextWriter consoleOutput, System.Threading.CancellationToken cancellationToken) Line 48	C#
 	VBCSCompiler.exe!Microsoft.CodeAnalysis.CompilerServer.CSharpCompilerServer.RunCompiler(string clientDirectory, string[] args, string baseDirectory, string sdkDirectory, string libDirectory, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader analyzerLoader, System.Threading.CancellationToken cancellationToken) Line 38	C#
 	VBCSCompiler.exe!Microsoft.CodeAnalysis.CompilerServer.CompilerRequestHandler.CSharpCompile(string currentDirectory, string libDirectory, string responseFileDirectory, string[] commandLineArguments, System.Threading.CancellationToken cancellationToken) Line 151	C#
 	VBCSCompiler.exe!Microsoft.CodeAnalysis.CompilerServer.CompilerRequestHandler.CSharpCompile(Microsoft.CodeAnalysis.CompilerServer.BuildRequest req, System.Threading.CancellationToken cancellationToken) Line 125	C#
 	VBCSCompiler.exe!Microsoft.CodeAnalysis.CompilerServer.CompilerRequestHandler.HandleRequest(Microsoft.CodeAnalysis.CompilerServer.BuildRequest req, System.Threading.CancellationToken cancellationToken) Line 55	C#
 	VBCSCompiler.exe!Microsoft.CodeAnalysis.CompilerServer.ServerDispatcher.Connection.ServeBuildRequest.AnonymousMethod__0() Line 154	C#
 	mscorlib.dll!System.Threading.Tasks.Task<Microsoft.CodeAnalysis.CompilerServer.BuildResponse>.InnerInvoke() Line 680	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2756	C#
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820	C#
 	[Async Call]	
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsAsync.AnonymousMethod__0() Line 338	C#
 	[Async Call]	
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsAsync(System.Threading.CancellationToken cancellationToken) Line 350	C#
 	[Async Call]	
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.Initialize.AnonymousMethod__1() Line 98	C#

**Comment by srivatsn** [comment]
Could this result in a release crash? If the assert's assumption is wrong then that's not a 1.0 fix but if there's a bug hiding here we should consider that for 1.0

**Comment by mavasani** [comment]
Nope, it doesn't. I verified that as well. We should move it to 1.1.

**Comment by mavasani** [comment]
Doesn't repro for me anymore, and also the assert had no impact on release build.
