### ISSUE TITLE
Use "is null" quick action not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30019]
VS 15.8.2

VS is identifying a &quot;ReferenceEquals(x,null)&quot; and indicating it can be simplied.  The quick action pop-up lists &quot;use is null&quot; as an option.  But invoking it hasn't been doing anything for a short while now even under various different contexts.  Other quick actions, such as &quot;implement interface&quot; have been working.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/331599/use-is-null-quick-action-not-working.html
VSTS ticketId: 680149_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
📝 I wasn't able to find an obvious cause in the data submitted with the issue, so the initial goal here will be finding a way to reproduce the issue.

**Comment by tokarzkj** [comment]
I would like to take a look at this if no one has grabbed it already. I was able to reproduce it using a basic use case

![useisnull](https://user-images.githubusercontent.com/13357505/47397617-25433980-d6fe-11e8-93ae-3fc073a78c1e.gif)

**Comment by CyrusNajmabadi** [comment]
Hey @tokarzkj !  Thanks for the offer.  However, this issue was already fixed in this pr: https://github.com/dotnet/roslyn/pull/29458

Sorry!

**Comment by tokarzkj** [comment]
No worries. Thanks for letting me know @CyrusNajmabadi !

**Comment by jinujoseph** [comment]
closed via #29458 
Thanks @CyrusNajmabadi
