### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.' not telling which thing is null

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30018]
I'm gett an NullReferenceException but the dialog is not telling me what is null.

Please see the video.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/325134/systemnullreferenceexception-object-reference-not-2.html
VSTS ticketId: 674567_
_These are the original issue comments:_

Mike DePouw on 8/30/2018, 03:02 PM (19 days ago): <p><img src="https://developercommunity.visualstudio.com/storage/temp/39182-untitled-dsffa.png" style="background-color: initial;"></p><p>what is null is missing 😱</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Not actionable.  Would need repro on this.
