### ISSUE TITLE
Add tests for ??= with non-nullable value types

### ISSUE THREAD

**Issue by chsienki** [dotnet/roslyn#30024]
PR #29985 brought up that we don't have any explicit tests to check that non-nullable value types (like Span<T>) are an invalid target for the LHS of the ??= operator. 

Currently we correctly error in this case, but we should add tests to ensure we keep the behavior covered, and thus never have to implement escape check logic for ??=

**Comment by 333fred** [comment]
Not sure why this wasn't auto-closed, but this was fixed in https://github.com/dotnet/roslyn/pull/30025.
