### ISSUE TITLE
Dead assignment in VB compiler conversion from double to long

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#3003]
See https://github.com/dotnet/roslyn/blob/b2addcbb2479453adf0ec1430948d63d0d25d44f/src/Compilers/VisualBasic/Portable/Semantics/CompileTimeCalculations.vb#L636

The assignment is dead, as the variable is unconditionally overwritten before being used again.

**Comment by AlekseyTs** [comment]
@gafter Please verify.

**Comment by AnthonyDGreen** [comment]
Verified that the initialization is removed in master.
