### ISSUE TITLE
Certain C# code style options are defined in the core/shared code style options

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#30042]
See the following three `CodeStyleOptions`:

1. [CodeStyleOptions.PreferDeconstructedVariableDeclaration](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeStyle/CodeStyleOptions.cs,21cc18d5006d858e): `csharp_style_deconstructed_variable_declaration`
2. [CodeStyleOptions.PreferInlinedVariableDeclaration](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeStyle/CodeStyleOptions.cs,57fd8062ad62477c): `csharp_style_inlined_variable_declaration`
3. [CodeStyleOptions.PreferThrowExpression](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeStyle/CodeStyleOptions.cs,4cf8d56d93885df9): `csharp_style_throw_expression`

Note that all the three options above have a `csharp_` editorconfig prefix, while the rest of the options in this type have `dotnet_` prefix. These options are defined as `PerLanguageOption`, while they are clearly specific to C#. These options should be moved to `CSharpCodeStyleOptions`, and in future if we have VB equivalents, they should be defined in `VisualBasicCodeStyleOptions`.

**Comment by GKotfis** [comment]
Hi. I'd like to start working on that!

**Comment by mavasani** [comment]
> Hi. I'd like to start working on that!

Thanks!
@chborl Have you started working on this? Otherwise, I am fine with @GKotfis picking this up.

**Comment by chborl** [comment]
I started to but didn't get too far.  Go right ahead, @GKotfis !

**Comment by castholm** [comment]
Hi! I stumbled upon this issue while browsing through the source code for editorconfig options. Considering that it has been a year (coincidentally, almost to the minute) since @GKotfis offered to start working on it and no work seems to have been done, is this issue still up for grabs? If so, I'd be very interested in taking a stab at it.

**Comment by mavasani** [comment]
@castholm It is still up for grabs. Let us know if you need any pointers to start on this one.

**Comment by GKotfis** [comment]
Hi.
Last year I did some changes but stuck in some point of refactoring. I even asked on slack channel if I should create PR with things that I already but still no compiling. I can get back to this but first need to make my branch up to date after such a long time :)

**Comment by castholm** [comment]
@GKotfis Do you have any plans to work on this issue and submit your changes soon-ish? I was planning on picking this up immediately and working on it over the weekend, but if you think you'll be able to get your changes working within that time frame I can take a step back and let you deal with it.

**Comment by GKotfis** [comment]
@castholm I'll definitely not finish this over the weekend. Feel free to take it!
