### ISSUE TITLE
Test plan for enhanced using and foreach

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#30053]
Three features are included:
- `using` declaration https://github.com/dotnet/csharplang/issues/1174
- pattern-based `using` https://github.com/dotnet/csharplang/issues/1623
- extension-based `foreach` https://github.com/dotnet/csharplang/issues/1623

Some scenarios and test ideas:
- [ ] `StructRefEnumerator GetEnumerator<T>(this T[] @this)`
- [ ] pattern-based `Dispose` in foreach
- [ ] `await using var` declaration
- [ ] IDE: FindAllReferences on `Dispose` method or extension, and `GetEnumerator` extension
- [ ] handle EnC
- [ ] integrate with async-streams (https://github.com/dotnet/roslyn/issues/24037)
- [ ] verify sequence points and debugging experience

FYI @agocke @chsienki

**Comment by tmat** [comment]
Note that `using` declaration will need special handling in EnC.

**Comment by alrz** [comment]
I think `GetEnumerator<T>(this T[] @this)` would be a good candidate to be included in corefx, but I'm not sure if we're allowed to optimized that away with a simple `for` loop. That looks like a language feature merely enabled by corefx.

**Comment by alrz** [comment]
And a question, do we run a normal lookup for GetEnumerator or it has to be an extension method?

**Comment by jcouv** [comment]
Closing in favor of https://github.com/dotnet/roslyn/issues/28588
