### ISSUE TITLE
Add support for generating current naming rules/options in the editorconfig generator

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#30086]
See the discussion here: https://github.com/dotnet/roslyn/pull/30043#discussion_r219246165. Current editorconfig file generation only handles formatting and code style options, but we should extend it to generate entries for naming rules as well.

**Comment by jinujoseph** [comment]
also requested via [DC ](https://developercommunity.visualstudio.com/content/idea/411815/include-also-naming-convention-when-export-to-edit.html)
