### ISSUE TITLE
Public API design for IOptionWithGroup

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#30085]
https://github.com/dotnet/roslyn/pull/30043 added notion of grouping options in the same feature (such as CodeStyleOptions, CSharpCodeStyleOptions, FormattingOptions, CSharpFormattingOptions, etc.) into sub-features or groups (such as "this. preferences", "expression-level preferences", etc.). This enables the editorconfig generation to group the related options, without explicit knowledge of each option group. This PR used an internal interface `IOptionWithGroup`, which is workaround to avoid tying up public API design with that PR. This issue tracks correctly designing a public API around this.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an api review.
