### ISSUE TITLE
Follow-up naming changes to .editorconfig generator

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#30083]
https://github.com/dotnet/roslyn/pull/30043 used the naming conventions from https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017#example-editorconfig-file, but https://github.com/MicrosoftDocs/visualstudio-docs/issues/1550 tracks improving this in the documentation. Once the docs issue has been fixed, we should update the EditorConfigGenerator.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
