### ISSUE TITLE
Method Signature Markup for Declaring Reference Ownership Intent

### ISSUE THREAD

**Issue by whoisj** [dotnet/roslyn#3008]
C# is a managed language. One of the primary things that's “managed” is memory, a key resource that programs require. Programs are able to request memory from the system and that memory can be reclaimed automatically by the system's garbage collector (GC). The GC can only perform its job correctly when references, which is uses to determine if memory is used or available for collection, are managed correctly. Correct management of references means keeping control of the use and count of those references.

When references are passed to third-party code, developers are forces to take a leap of faith that method or class invoked does all of the right things: not keep referenced beyond the time they need them, not pass them to misbehaving code that keeps the references too long, etc. In many cases it is completely unexpected that a reference would be taken for any reason and it can cause unwanted memory leaks.

I propose a method mark up, similar to C++ pass by reference, which creates a contract that the method will not keep a reference longer than its scope and will not pass the reference to a method that might keep the references longer its scope.

```
public Matrix Multiply(Matrix& other)
{
    Matrix A = this,  B = other; // legal because B is scoped to the method body

    double t11 = A._1_1 * B._1_1 + A._1_2 * B._2_1 + A._1_3 * B._3_1;
    double t12 = A._1_1 * B._1_2 + A._1_2 * B._2_2 + A._1_3 * B._3_2;
    double t13 = A._1_1 * B._1_3 + A._1_2 * B._2_3 + A._1_3 * B._3_3;
    
    double t21 = A._2_1 * B._1_1 + A._2_2 * B._2_1 + A._2_3 * B._3_1;
    double t22 = A._2_1 * B._1_2 + A._2_2 * B._2_2 + A._2_3 * B._3_2;
    double t23 = A._2_1 * B._1_3 + A._2_2 * B._2_3 + A._2_3 * B._3_3;
    
    double t31 = A._3_1 * B._1_1 + A._3_2 * B._2_1 + A._3_3 * B._3_1;
    double t32 = A._3_1 * B._1_2 + A._3_2 * B._2_2 + A._3_3 * B._3_2;
    double t33 = A._3_1 * B._1_3 + A._3_2 * B._2_3 + A._3_3 * B._3_3;

    return new Matrix(t11, t12, t13
                      t21, t22, t23,
                      t31, t32, t33);
}

public Matrix Copy(Matrix& other)
{
    m_lastCopied = other; // illegal because m_lastCopied is not scoped to the method
    new Matrix(other.t11, other.t12, other.t13,
               other.t21, other.t22, other.t23,
               other.t31, other.t32, other.t33);
}
```

Since this would invalidate a lot of existing code, an alternative approach of marking references the callee intends to keep beyond its scope. Using a similar to, but different from, syntax from the C++ by reference syntax.

```
public void Add(T% item)
{
    m_internalList.Add(%item); // legal because the reference is marked as allowing retention
}

public void IsValid(string value)
{
    m_unnecissaryStringCache.Add(value); // illegal because the reference is scoped on to this method
    return value != null && m_validationRegex.IsMatch(value);
}
```

I offer the alternative because I'd like to manage the scope of passed references and I feel the common case is to not keep a reference beyond the scope of a method, and the case where a reference is retained is exceptional case.

**Comment by svick** [comment]
I think that this would complicate the language too much just to fix a relatively rare issue. A significant benefit of GC is that you usually don't have to think about references too much, it just works.

And your proposal probably wouldn't even fix the issue completely. Consider a LINQ method like `Enumerable.Select()`: it takes a reference to a lambda (which in turn can reference some local variable) and stores it in an object which it returns. I believe this would violate your `&` constraint, which would mean you can't ever use LINQ while referencing a `&` value in the lambda.

You could try to solve this specific case somehow, but there are probably lots of other coding patterns that wouldn't work well with your proposal.

Also, wouldn't the alternative syntax invalidate much more existing code (since it would change what unadorned type of a parameter means)?

**Comment by whoisj** [comment]
I don't see this as a complication, especially if the second option is provided because only storage classes would need to be updated. Honestly, this would not be needed if the lifetime of objects could be controlled - but over reliance on the GC limits our ability to do so.

@svick, in your example the LINQ query would be scoped correctly, thus there would be no issues unless the results were to be preserved, cached, or otherwise retained beyond the scope.

**Comment by OzieGamma** [comment]
Isn't the whole point of a managed language, not having to care about memory management ?
This would make the language more complicated without any real benefit.
You'll still have to 'trust' that libraries don't use slow algorithms, have an efficient implementation ect ...

**Comment by whoisj** [comment]
@OzieGamma that's true, we do still have to trust that libraries use efficient algorithms, etc.

However, I still find myself wishing I could put a contract on the API I write which guarantees that I won't hold a reference on my caller's objects.

**Comment by gafter** [comment]
This is what #160 is all about.

**Comment by whoisj** [comment]
@gafter not exactly.

#160 is about adding a `move` operator so that destructible types can escape their scope.

This is more about, here's a cheap weak reference to my allocation. When I want it deallocated, it is deallocated and you cannot prevent that from happening.

Today we rely on `IDisposable.Dispose` to put object, that we cannot destruct, into a bad state to prevent their use. IMO it's a terrible hack and dangerous to say the least.

**Comment by gafter** [comment]
I hear you. We'll look at this if/when we look at the cluster of related issues.
