### ISSUE TITLE
Microsoft.Build.Tasks.CodeAnalysis.dll does not specify an NgenApplication

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#30088]
`Microsoft.Build.Tasks.CodeAnalysis` does not specify which application settings should be used for ngen:

https://github.com/dotnet/roslyn/blob/515ff80d2b4a8b506ccf053dd5e3ff597d9ddd2e/src/NuGet/Microsoft.Net.Compilers/CompilerArtifacts.props#L42

Typically this is specified like this:
https://github.com/dotnet/roslyn/blob/515ff80d2b4a8b506ccf053dd5e3ff597d9ddd2e/src/NuGet/Microsoft.Net.Compilers/CompilerArtifacts.props#L24

@ManishJayaswal 	@jinujoseph 	@tmat 	this is blocking OptProf generation.

@jaredpar 	@agocke 	I assume the build tasks should use MSBuild.exe as the application config for assembly resolution?

**Comment by jmarolf** [comment]
@tmat this causes the following invalid json to be placed in the manifest:

```json
{
  "fileName": "/Contents/MSBuild/15.0/Bin/Roslyn/Microsoft.Build.Tasks.CodeAnalysis.dll",
  "sha256": "A763C077BEF53497D62C31629CE5B0E951309C6570064AFCDD6CB747B955912F",
  "ngenArchitecture": "All",
  "ngenApplication": "[installDir]\\MSBuild\\15.0\\Bin\\Roslyn\\"
}
```

**Comment by tmat** [comment]
If NgenApplication is unspecified it's supposed to be vsn.exe by default.

**Comment by tmat** [comment]
There is a typo in src\Setup\DevDivVsix\CompilersPackage\Microsoft.CodeAnalysis.Compilers.Setup.csproj:

```
        <NGenApplicationString Condition="'%(CompilerArtifact.NgenArchitecture)' != ''"> vs.file.ngenApplication="[installDir]\MSBuild\15.0\Bin\Roslyn\%(CompilerArtifact.NGenApplication)"</NGenApplicationString>
```

The condition should be `'%(CompilerArtifact.NGenApplication)' != ''`

**Comment by jmarolf** [comment]
Ah got it thanks!

**Comment by jaredpar** [comment]
Closing as the PR appears to have resolved this.
