### ISSUE TITLE
Nullable: Fixer to add `#nullable` and project-level setting

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#30099]
- Handle presence of existing `#nullable disable`
- Allow setting project-level option
  - [ ] code fixer
  - [ ] project system property or API https://github.com/dotnet/project-system/issues/4058

**Comment by jcouv** [comment]
@CyrusNajmabadi I'm thinking about how to offer a fix to add `[module: NonNullTypes]`.

Currently, I see three possible approaches:
1. inject in current file
2. some heuristic to pick a file in current project (if there is an `AssemblyInfo.cs` pick that one)
3. modify msbuild so that the task that generates `AssemblyInfo.cs` can generate `[module: NonNullTypes]`, then the code fixer would fix the csproj to trigger that.

Any thoughts?

**Comment by CyrusNajmabadi** [comment]
I would have the logic try to do '2', but fallback to '1' if it can't.  

If users decide they don't like the location we put hte `[module:]` attribute in, they can always easily move it.  The core part (for me at least) is that they wouldn't know how to turn this on.  Once they run the fixer, it becomes clear.  And they can then just choose a suitable location if our heuristic isn't what they prefer.

**Comment by Neme12** [comment]
Is there an MSBuild property that could be set that would generate this attribute? If not, I assume there might be one in the future?

**Comment by jcouv** [comment]
@Neme12 Yes. Adding an MSBuild property for `WriteCodeFragment` to generate this in a generated `AssemblyInfo.cs` is option (3) above. Then the code fixer would offer to set this property (either on the current `csproj`, or maybe on a `dirs.proj`) and the build process would do the rest.

**Comment by jcouv** [comment]
From discussion with @nguerrera we'd like to explore the following design:

The fixer would try the following, in order:
1. query the project system to check if it is CPS and if it has the GenerateAssemblyInfo "capability". If yes, then modify the csproj. (We'd modify `WriteCodeFragments` to generate a module-level attribute)
2. look for an `AssemblyInfo.cs` file. If one is found, inject `[module: NonNullTpes]` there.
3. otherwise, inject in the current file.

**Comment by jcouv** [comment]
From follow-up discussion with @davkean, it turns out that project-system already implements a pattern like this for some other properties. The only difference is that the last case would create an `AssemblyInfo.cs` file (since none exists).
In this design, the code fixer can just ask the project-system to enable NonNullTypes and project-system will handle the different cases and fall back.

**Comment by jcouv** [comment]
Closing issue in favor of https://github.com/dotnet/roslyn/issues/42509
