### ISSUE TITLE
Completion MRU alternates two most recently used items

### ISSUE THREAD

**Issue by AmadeusW** [dotnet/roslyn#30097]
**Version Used**: 
branch `asynccompletion` at ` https://github.com/ivanbasov/roslyn`

**Steps to Reproduce**:

`public double Ma(double m) => m;`
type the following on the keyboard: `M(M(M(M(`

**Expected Behavior**:

![image](https://user-images.githubusercontent.com/1673956/45902685-17fffb80-bd9c-11e8-97e4-28e0b1a15a07.png)

**Actual Behavior**:

The two MRU items don't alternate, and I get `Ma(Ma(Ma(Ma(` with `Ma` selected as the top completion item

**Comment by ivanbasov** [comment]
@AmadeusW 
I have added a new test: TestMRUKeepsTwoRecentlyUsedItems
It shows that the new implementation alters 'Ma' and 'm:'.  The expected value is 'Ma(m:(Ma(m:('. The current version passes the test.

**Comment by AmadeusW** [comment]
What's the desired behavior from the user point of view? Shouldn't the test be the absolute truth (and therefore fail)?

**Comment by ivanbasov** [comment]
The current behavior in the new completion corresponds to the behavior in the old one. To fix it, it is necessary to correct the current provider. It is suggested to postpone correcting the current functionality until merging the original async completion PR.

Here is the test:

```
        Public Async Function TestMRUKeepsTwoRecentlyUsedItems(completionImplementation As CompletionImplementation) As Task
            Using state = TestStateFactory.CreateCSharpTestState(completionImplementation,
                              <Document>
class C
{
    public double Ma(double m) => m;

    public void Test()
    {    
        $$
    }
}
                              </Document>)

                state.SendTypeChars("M(M(M(M(")
                Await state.AssertNoCompletionSession()
                Assert.Equal("        Ma(m:(Ma(m:(", state.GetLineTextFromCaretPosition())
            End Using
        End Function
```
