### ISSUE TITLE
Expose useful APIs

### ISSUE THREAD

**Issue by davidfowl** [dotnet/roslyn#301]
Lik everything in this file:

https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs

**Comment by heejaechang** [comment]
APIs here probably is good to be exposed as toolkit rather than compiler APIs since it uses only public compiler APIs.

**Comment by tmat** [comment]
Some of that functionality might be easier to implement in the compiler.
Also APIs like finding out what interface method a specified method implements are very fundamental and should be part of compiler API.

**Comment by mkrueger** [comment]
In fact almost all extensions methods to tokens, nodes, symbols and so on should be added to public. They're really useful.
The goal for the API should be that the CSharp.Features shouldn't rely on internal API anymore.
If it's possible to implement Completion, ExtractMethod and so on with the roslyn public API the API is a good one.

**Comment by heejaechang** [comment]
I didn't mean that it shouldn't be public. but by putting in a toolkit, we have less restriction on breaking changes.

**Comment by Pilchie** [comment]
In general, we don't want to "easy to write" extension methods be public, because that leads to a confusing API surface area.  

We'd rather have one complete, albeit verbose API and allow people to write their own helpers to avoid questions like: When should I use this method versus the primitives it's built on?

If there are *specific* extension methods that you think are generally useful and provide real value because the implementation is hard to get write, please send us PR's to make them accessible.

**Comment by davidfowl** [comment]
sigh :smile:

**Comment by mkosieradzki** [comment]
I fully agree with @Pilchie . I am implementing my own small scripting IDE based on Roslyn and all usefull APIs that contain actual COMPLEXITIES are exposed. There is no point in exposing trivial stuff like for example keyword recommenders (in my case) or helpers methods like that.

It would make maintenance of API extremely hard. If you really like this helper logic just copy code from this file.

**Comment by tmat** [comment]
I generally agree. However there is one specific method in this type that seems pretty complex to implement: FindImplementationsForInterfaceMember.

**Comment by Pilchie** [comment]
We already expose `SymbolFinder.FindImplementedInterfaceMembersAsync` and `SymbolFinder.FindImplementationsAsync`

http://source.roslyn.io/Microsoft.CodeAnalysis.Workspaces/R/2ff44ec7ffcdbeaf.html
http://source.roslyn.io/Microsoft.CodeAnalysis.Workspaces/R/6de07857600d87fb.html

**Comment by tmat** [comment]
There is also ITypeSymbol.FindImplementationForInterfaceMember. I missed it for some reason. @davidfowl, does this not work for you?

**Comment by heejaechang** [comment]
You could take all of Roslyn utility extension methods (that depend on public Roslyn APIs) to another git hub project and change all of them public and publish them as another nugget package.


-          heejae

**Comment by mkrueger** [comment]
That's basically what NR6 is about :)
