### ISSUE TITLE
Restore.cmd fails

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#30101]
After getting latest master branch (as of 1060b7c1bfabc92ee01738bff8afcb33daf9985c) and having a clean repo, this is what I get when running Restore.cmd using Developer Command Prompt:

```
Repo Dir C:\Users\neme1\Source\Repos\roslyn
Binaries Dir C:\Users\neme1\Source\Repos\roslyn\Binaries
Running restore
Restore using dotnet at C:\Program Files\dotnet\dotnet.exe
Restoring Roslyn Toolset
Restoring RepoToolset
Restoring Roslyn
Command failed to execute: C:\Program Files\dotnet\dotnet.exe restore --verbosity quiet Roslyn.sln
System.Management.Automation.RuntimeException: Command failed to execute: C:\Program Files\dotnet\dotnet.exe restore --verbosity quiet Roslyn.sln
at Exec-CommandCore, C:\Users\neme1\Source\Repos\roslyn\build\scripts\build-utils.ps1: line 68
at Exec-Console, C:\Users\neme1\Source\Repos\roslyn\build\scripts\build-utils.ps1: line 100
at Restore-Project, C:\Users\neme1\Source\Repos\roslyn\build\scripts\build-utils.ps1: line 405
at Restore-Packages, C:\Users\neme1\Source\Repos\roslyn\build\scripts\build.ps1: line 200
at <ScriptBlock>, C:\Users\neme1\Source\Repos\roslyn\build\scripts\build.ps1: line 620
```

And this is the output of running Restore.cmd from regular cmd:
```
Repo Dir C:\Users\neme1\Source\Repos\roslyn
Binaries Dir C:\Users\neme1\Source\Repos\roslyn\Binaries
Downloading vswhere
Downloading RoslynTools.MSBuild
Running restore
Restore using dotnet at C:\Program Files\dotnet\dotnet.exe
Restoring Roslyn Toolset
Restoring RepoToolset
Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
System.Management.Automation.MethodInvocationException: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified" ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
at Exec-CommandCore, C:\Users\neme1\Source\Repos\roslyn\build\scripts\build-utils.ps1: line 45
at Exec-Console, C:\Users\neme1\Source\Repos\roslyn\build\scripts\build-utils.ps1: line 100
at Run-MSBuild, C:\Users\neme1\Source\Repos\roslyn\build\scripts\build.ps1: line 182
at Restore-Packages, C:\Users\neme1\Source\Repos\roslyn\build\scripts\build.ps1: line 196
at <ScriptBlock>, C:\Users\neme1\Source\Repos\roslyn\build\scripts\build.ps1: line 620
```

**Comment by Neme12** [comment]
When running this command manually:
```
C:\Program Files\dotnet\dotnet.exe restore --verbosity quiet Roslyn.sln
```
it exits after about 2-3 seconds with no output (or maybe a single line break).

The Binaries folder only contains Debug\Logs (with no files).

**Comment by sharwell** [comment]
> --verbosity quiet

What if you drop this part?

**Comment by Neme12** [comment]
@sharwell Still no output.

**Comment by sharwell** [comment]
What about `msbuild /t:Restore`?

**Comment by sharwell** [comment]
@jaredpar @tmat  We narrowed down the issue but I'm stuck. Can you help get Šimon going again?

Also /cc @tannergooding in the off chance you can help or point other people this way.

**Comment by Neme12** [comment]
Here's the output if I run the same command with `--verbosity detailed`: [output.txt](https://github.com/dotnet/roslyn/files/2408015/output.txt)

One thing that stands out is this at every project:
> MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

**Comment by Neme12** [comment]
Running `msbuild /t:Restore Roslyn.sln` seems to have "worked" because it filled up Binaries\Obj\. If I open Roslyn.sln I now get IntelliSense but still can't build though due to this repeated error:

> C:\Users\neme1\Source\Repos\roslyn\build\Targets\Imports.targets(107,5): error MSB4062: The "Roslyn.MSBuild.Util.ValidateBuildEnvironment" task could not be loaded from the assembly C:\Users\neme1\.nuget\packages\Roslyn.Build.Util\0.9.8-beta\lib\net46\Roslyn.MSBuild.Util.dll. Could not load file or assembly 'file:///C:\Users\neme1\.nuget\packages\Roslyn.Build.Util\0.9.8-beta\lib\net46\Roslyn.MSBuild.Util.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Comment by Neme12** [comment]
I don't think this is a problem with Roslyn. I get the same error if I create a new .NET Core console app.

**Comment by Neme12** [comment]
Fixed by fixing up `MSBuildSDKsPath` to point to 2.1.401 (found here: https://github.com/Microsoft/msbuild/issues/2532)
