### ISSUE TITLE
Feature request merge ifs refactoring

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#30100]
Before:
```cs
if (a)
{
[|  if(b)|]
    {
        ...
    }
}
```

After:
```cs
if (a && b)
{
    ...
}
```

**Comment by jinujoseph** [comment]
@JohanLarsson this looks like dupe of https://github.com/dotnet/roslyn/issues/29347 
what do you think?

**Comment by JohanLarsson** [comment]
@jinujoseph yes, sorry about the, dupe, closing this.

**Comment by jnm2** [comment]
Didn't find a duplicate for the `||` (consecutive) case, so I opened a new one: #30114
