### ISSUE TITLE
Removing an EF Core Migration in the Package Manager Console throws exception

### ISSUE THREAD

**Issue by raboud** [dotnet/roslyn#30115]
**Version Used**: 15.8.5

**Steps to Reproduce**:

1. Create a .NetCore application that includes EF CORE
2. Add Migration
3.  Remove Migration

**Expected Behavior**:
Migration to be removed with no popups

**Actual Behavior**:
Migration is removed.
error popup appears

=====================
9/24/2018 8:53:37 AM
LimitedFunctionality
System.Runtime.InteropServices.COMException (0x8001010E): This operation should only take place on the UI thread.

	Stack Trace:
		VerifyOnUIThread at offset 125 in file:line:column <filename unknown>:0:0
		NotifyPropertySinks at offset 55 in file:line:column <filename unknown>:0:0
		Update at offset 107 in file:line:column <filename unknown>:0:0
		GetNodeProperties at offset 388 in file:line:column <filename unknown>:0:0
		Create at offset 59 in file:line:column <filename unknown>:0:0
		get_Properties at offset 40 in file:line:column <filename unknown>:0:0
		CallSite.Target at offset 214 in file:line:column <filename unknown>:0:0
		Run at offset 82 in file:line:column <filename unknown>:0:0
		Run at offset 142 in file:line:column <filename unknown>:0:0
		Run at offset 142 in file:line:column <filename unknown>:0:0
		Run at offset 142 in file:line:column <filename unknown>:0:0
		Run at offset 43 in file:line:column <filename unknown>:0:0
		RunVoid1<T0> at offset 170 in file:line:column <filename unknown>:0:0
		RunClause at offset 887 in file:line:column <filename unknown>:0:0
		Complete at offset 367 in file:line:column <filename unknown>:0:0
		DoComplete at offset 192 in file:line:column <filename unknown>:0:0
		DoCompleteCore at offset 140 in file:line:column <filename unknown>:0:0
		SynchronousExecuteEnumerate at offset 348 in file:line:column <filename unknown>:0:0
		InvokePipeline at offset 531 in file:line:column <filename unknown>:0:0
		Run at offset 301 in file:line:column <filename unknown>:0:0
		Run at offset 142 in file:line:column <filename unknown>:0:0
		Run at offset 142 in file:line:column <filename unknown>:0:0
		Run at offset 142 in file:line:column <filename unknown>:0:0
		Run at offset 43 in file:line:column <filename unknown>:0:0
		RunVoid1<T0> at offset 170 in file:line:column <filename unknown>:0:0
		InvokeWithPipeImpl at offset 2025 in file:line:column <filename unknown>:0:0
		<InvokeWithPipe>b__0 at offset 93 in file:line:column <filename unknown>:0:0
		RunActionIfNoRunningPipelinesWithThreadCheck at offset 179 in file:line:column <filename unknown>:0:0
		InvokeWithPipe at offset 343 in file:line:column <filename unknown>:0:0
		InvokeUsingCmdlet at offset 249 in file:line:column <filename unknown>:0:0
		ProcessRecord at offset 359 in file:line:column <filename unknown>:0:0
		DoProcessRecord at offset 13 in file:line:column <filename unknown>:0:0
		ProcessRecord at offset 750 in file:line:column <filename unknown>:0:0
		DoExecute at offset 74 in file:line:column <filename unknown>:0:0
		AddToPipe at offset 172 in file:line:column <filename unknown>:0:0
		Add at offset 83 in file:line:column <filename unknown>:0:0
		_WriteObjectSkipAllowCheck at offset 191 in file:line:column <filename unknown>:0:0
		DoWriteObject at offset 30 in file:line:column <filename unknown>:0:0
		Run at offset 214 in file:line:column <filename unknown>:0:0
		WriteObject at offset 132 in file:line:column <filename unknown>:0:0
		WriteObject at offset 51 in file:line:column <filename unknown>:0:0
		ProcessRecord at offset 198 in file:line:column <filename unknown>:0:0
		DoProcessRecord at offset 13 in file:line:column <filename unknown>:0:0
		ProcessRecord at offset 750 in file:line:column <filename unknown>:0:0
		DoExecute at offset 74 in file:line:column <filename unknown>:0:0
		Inject at offset 375 in file:line:column <filename unknown>:0:0
		SynchronousExecuteEnumerate at offset 268 in file:line:column <filename unknown>:0:0
		InvokePipeline at offset 531 in file:line:column <filename unknown>:0:0
		Run at offset 301 in file:line:column <filename unknown>:0:0
		Run at offset 142 in file:line:column <filename unknown>:0:0
		Run at offset 142 in file:line:column <filename unknown>:0:0
		Run at offset 43 in file:line:column <filename unknown>:0:0
		RunVoid1<T0> at offset 170 in file:line:column <filename unknown>:0:0
		RunClause at offset 680 in file:line:column <filename unknown>:0:0
		DoEndProcessing at offset 101 in file:line:column <filename unknown>:0:0
		Complete at offset 122 in file:line:column <filename unknown>:0:0
		DoComplete at offset 192 in file:line:column <filename unknown>:0:0
		DoCompleteCore at offset 140 in file:line:column <filename unknown>:0:0
		SynchronousExecuteEnumerate at offset 348 in file:line:column <filename unknown>:0:0
		InvokePipeline at offset 531 in file:line:column <filename unknown>:0:0
		Run at offset 301 in file:line:column <filename unknown>:0:0
		Run at offset 142 in file:line:column <filename unknown>:0:0
		Run at offset 142 in file:line:column <filename unknown>:0:0
		Run at offset 43 in file:line:column <filename unknown>:0:0
		RunVoid1<T0> at offset 170 in file:line:column <filename unknown>:0:0
		RunClause at offset 887 in file:line:column <filename unknown>:0:0
		Complete at offset 550 in file:line:column <filename unknown>:0:0
		DoComplete at offset 192 in file:line:column <filename unknown>:0:0
		DoCompleteCore at offset 140 in file:line:column <filename unknown>:0:0
		SynchronousExecuteEnumerate at offset 348 in file:line:column <filename unknown>:0:0
		InvokeHelper at offset 1491 in file:line:column <filename unknown>:0:0
		InvokeThreadProc at offset 411 in file:line:column <filename unknown>:0:0
		ThreadStart_Context at offset 157 in file:line:column <filename unknown>:0:0
		RunInternal at offset 229 in file:line:column <filename unknown>:0:0
		Run at offset 22 in file:line:column <filename unknown>:0:0
		Run at offset 65 in file:line:column <filename unknown>:0:0
		ThreadStart at offset 68 in file:line:column <filename unknown>:0:0

   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.VerifyOnUIThread()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.DynamicTypeBrowseObjectBase.NotifyPropertySinks()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.DynamicTypeBrowseObjectBase.Update(IProjectTree projectTree, IProjectVersionedValue`1 projectTreeSnapshot)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleHierarchyNode.GetNodeProperties()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProperties.Create(Object parent, SimpleHierarchyNode hierarchyNode)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.get_Properties()
   at CallSite.Target(Closure , CallSite , Object )
===================

**Comment by tmat** [comment]
@davkean @Pilchie This looks like Project System issue.

**Comment by Pilchie** [comment]
@lifengl - Core CPS?

**Comment by TeamBrett** [comment]
I have just started seeing this error and it is only occurring when I have a call to `HasData` as part of the model creation.
