### ISSUE TITLE
Add refactorings to split and merge consecutive if statements

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#30114]
Very similar to #29347, but the `||` version:

```c#
if (a) return;
if (b) return;
```

Refactoring:

```c#
if (a || b) return;
```

And vice versa. I probably use this during refactoring the same amount as #29347.

**Comment by jinujoseph** [comment]
@jnm2 dupe of https://github.com/dotnet/roslyn/issues/29347 ?

**Comment by jnm2** [comment]
@jinujoseph It doesn't look like #29347 covers `||`, only `&&`.

**Comment by Neme12** [comment]
@jasonmalinowski Can you please close this? The PR was merged.

**Comment by jnm2** [comment]
@Neme12 I got it. Thanks for doing that work! This will be awesome! 🎉
