### ISSUE TITLE
DeclareAsNullable fixer should trigger when assigning "maybe null" values to non-null variable

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#30110]
Currently (https://github.com/dotnet/roslyn/pull/26630), DeclareAsNullable only triggers when assigning the `null` literal.
Once we have a public API to expose the null-state of an expression, we could trigger on assignment of "maybe null" values.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
