### ISSUE TITLE
PreciseAbstractFlowPass can be inlined into AbstractFlowBase

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#30127]
This is a tracking issue from discussion with @gafter 
Some parts (like `_trackExceptions`) may be obsolete.

**Comment by gafter** [comment]
See also https://github.com/dotnet/roslyn/issues/23207

**Comment by jcouv** [comment]
Closing this as dupe of #23207 then. Thanks

**Comment by jaredpar** [comment]
Closing based on last comment. Let me know if you meant to keep this ope.
