### ISSUE TITLE
Provide option to disable autospace between empty braces

### ISSUE THREAD

**Issue by EchoReaper** [dotnet/roslyn#30126]
**Version Used**: 
VS 2017 Community Edition

There is no option to disable spacing between empty braces in Tools > Options > Text Editor > C# > Code Style > Formatting > Spacing. 
If I type SomeType 
someVariable[] = {};, it is forcibly changed to SomeType someVariable[] = { }; 
When I press left arrow to enter items into the braces, 
I get { 1, 2, 3} instead of {1, 2, 3}.

Hilariously, this issue can be spotted in code that is copy+pasted from Visual Studio e.g.
https://www.tutorialspoint.com/csharp/csharp_arrays.htm

![Image](https://i.imgur.com/ssfwsbA.png)

**Comment by CyrusNajmabadi** [comment]
I don't think we've ever had an option for this.  Given that, i would say it's probably better to just have code follow the pattern that VS has been spitting out since forever.  This keeps code more consistent and prevents unnecessary community bifurcation.

**Comment by jinujoseph** [comment]
**Design Meeting Notes**
Low Priority, typing semicolon at the end or format document should fix this. Not seeing a value of adding an option for the same.
