### ISSUE TITLE
Compiler crash on implicitly scoped using inside try block

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#30131]
See repro [HERE](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQQHYAsoYMYQAmqcyAlhgOYA+AAgAwAEtAjANwCwAULQMzMAmRgGFG3AN7dG05v1oAWRgFkAFAEoxXGY3Hap2mTAQBPTQZmSt5gw0YA3KAkZRGAXkYYIAd0YARMsgADgD2yFDAADYQ6pxW5gC++uZ4sHhYjCoAogAeBIEwZMEYakkGltY2LACcKgBEAMpQhB7BXrVqsRWJcYzdej2BCGQOMBCCfgEhYZEQIIwAkv5BoeFROqXafMyKS1PRGuJ9Mt3xQA=).

**Comment by chsienki** [comment]
Fixed with #32165
