### ISSUE TITLE
Address signature change of CommonCompletionUtilities.GetWordSpan that broke an internal consumer

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#30133]
See [this change](https://github.com/dotnet/roslyn/pull/29447/files#diff-1be1969f251b6e01f671985101baacc1R24). Changing that signature broke an internal consumer.

- We could add that overload back
- The added parameter has a default value, so I think that consumer could just recompile.

I'd prefer we add the overload back.

**Comment by jinujoseph** [comment]
closed via #30148
