### ISSUE TITLE
ReplaceTypeParameterBasedOnTypeConstraintVisitor.cs incorrectly uses WaitAndGetResult

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#30159]
https://github.com/dotnet/roslyn/blob/863af8bef91c9568f5b2636763767eb52fb1772f/src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.ReplaceTypeParameterBasedOnTypeConstraintVisitor.cs#L102-L103

These lines are using WaitAndGetResult, but this can be called on a background thread in various code fixes. Because it's on a background thread, the assert that says you shouldn't call that on a background thread can fire.

@sharwell @CyrusNajmabadi thoughts here? Can we make this not be a visitor and keep everything async? We can switch this to WaitAndGetResult_CanCallOnBackground but fixing this would be even better.

**Comment by CyrusNajmabadi** [comment]
You've summed it up fine :)   Feel free to make it not a visitor.  If it's too obnoxious to reimplement that visiting logic in async form, then feel free to use WaitAndGetResult_CanCallOnBackground .  Either are reasonable choices to me depending on how much effort you want to put in :)

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi I think my main concern is I can't figure out what this is actually doing. :smile:

**Comment by CyrusNajmabadi** [comment]
oh. lol.  looking.

**Comment by CyrusNajmabadi** [comment]
oh god... i remember this.  i didn't write it, but i remeber it was for some crazy generate-method case, or something like that.  basically, it was generating code into a location that couldn't reference something from the original location... and hten it decided "let me see if i can go find some sort of type i coudl jam in here to make it legal".

Easiest thing to do is disable this and see waht tests break.  Then you can see what scenario it was designed for.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/42141
