### ISSUE TITLE
Editor Completion - Partners - Debugger - Support completion in debugger

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#30153]
1. Roslyn does not provide any items when ‘$’ is the first char typed. The user experience would be a lot better if all items would be present but filtered out
2. Even if our “$...” items are in the completion list they are not scrolled to or filtered correctly. Ex. Start a session by typing x, then backspace, then $

**Comment by dpoeschl** [comment]
There's much further discussion in the email thread.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
