### ISSUE TITLE
Feature requests - Goto file members: prepopulating result panel, 'ctor' search string for declared conctructors

### ISSUE THREAD

**Issue by mariasm75** [dotnet/roslyn#30168]
Hi,
I think prepopulating the result list would be really nice similarly to 'Goto recent files'. Many times I recognize the required name more easily on a list than I recall it. If there are a bunch of members, the first 50-100 items would be enough.
It would be also a nice help if typing 'ctor' would list the constructors.
Thanks

**Comment by jinujoseph** [comment]
cc @olegtk

**Comment by olegtk** [comment]
good idea, route it to us

**Comment by jinujoseph** [comment]
[moved ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/694550)to Editor Team
