### ISSUE TITLE
Implement Code cleanup menu for document/project/solution

### ISSUE THREAD

**Issue by JieCarolHu** [dotnet/roslyn#30165]

**Comment by heejaechang** [comment]
@jinujoseph editor team wants us to support this in preview 2 and asking who they should work with. is it @sharwell ?

**Comment by jinujoseph** [comment]
yes it's @sharwell

**Comment by vikramdadwal** [comment]
Is this available now in 2019 GA ?

**Comment by sharwell** [comment]
@vikramdadwal This will be in 16.1
