### ISSUE TITLE
MSBuildWorkspace is not honoring Configuration property for project references

### ISSUE THREAD

**Issue by jirikopecky** [dotnet/roslyn#30174]
**Version Used**: 2.9.0

**Steps to Reproduce**:

1. Have project with project references, build it in Release configuration and make sure no Debug binaries are present
2. Create MSBuildWorkspace with property Configuration set to Release
3. Set LoadMetadataForReferencedProjects to true
4. Open project that have project reference using OpenProjectAsync
5. Try get compilation using GetCompilationAsync

**Expected Behavior**:
Compilation is returned with referenced project loaded as MetadataReference

**Actual Behavior**:
ArgumentException with message "Reference of type 'Microsoft.CodeAnalysis.UnresolvedMetadataReference' is not valid for this compilation." is thrown.
Further analysis showed that the UnresolvedMetadataReference points to Debug output path of referenced project.

Minimal repro implemented here: https://github.com/jirikopecky/roslyn-issue-repro

**Comment by DustinCampbell** [comment]
Thanks for the repro!

Hmmm... I'm seeing similar behavior at the command line if simply run MSBuild to produce the C# compiler arguments (which is essentially what MSBuildWorkspace does). Here's the MSBuild command line that produces that I'm using.

```
> msbuild InspectedLibrary\InspectedLibrary.csproj /t:Compile;CoreCompile /p:DesignTimeBuild=true /p:BuildingInsideVisualStudio=true /p:BuildProjectReferences=false /p:BuildingProject=false /p:ProvideCommandLineArgs=true /p:SkipCompilerExecution=true /p:ContinueOnError=ErrorAndContinue /p:Configuration=Release
```

That command line produces a blob with the C# command line args like so:

```
Microsoft (R) Build Engine version 15.9.19+g938f3292a0 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 10/17/2018 2:28:42 PM.
Project "D:\Projects\roslyn-issue-repro\InspectedSolution\InspectedLibrary\InspectedLibrary.csproj" on node 1  (Compile;CoreCompile target(s)).
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respec t to the input files.
CoreGenerateAssemblyInfo:
Skipping target "CoreGenerateAssemblyInfo" because all output files are up-to-date with respect to the input
files.
CoreCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin\Roslyn\csc.exe

*** GIANT BLOB OF C# COMMAND LINE ARGUMENTS ***
 
Done Building Project "D:\Projects\roslyn-issue-repro\InspectedSolution\InspectedLibrary\InspectedLibrary.csp roj" (Compile;CoreCompile target(s)).


Build succeeded.
    0 Warning(s)
    0 Error(s)
```

Looking carefully at that blob, I see `/reference:D:\Projects\roslyn-issue-repro\InspectedSolution\ReferencedLibrary\bin\Debug\netstandard2.0\ReferencedLibrary.dll`. So, there must be some other property that needs to be set to make this work, of there's an MSBuild issue here.

Continuing to dig...

**Comment by DustinCampbell** [comment]
I found it. The issue is that there's an MSBuild property that is set to true when the other properties are set, which allow MSBuildWorkspace to produce a design-time build. This property is `ShouldUnsetParentConfigurationAndPlatform`, and it gets set to true [here](https://github.com/Microsoft/msbuild/blob/d1af34332573aab3de6482ac1d0b35e1d7951564/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1473-L1474):

```XML
<ShouldUnsetParentConfigurationAndPlatform Condition="'$(ShouldUnsetParentConfigurationAndPlatform)' == '' and ('$(BuildingInsideVisualStudio)' == 'true' or '$(BuildingSolutionFile)' == 'true')">true</ShouldUnsetParentConfigurationAndPlatform>
<ShouldUnsetParentConfigurationAndPlatform Condition="'$(ShouldUnsetParentConfigurationAndPlatform)' == ''">false</ShouldUnsetParentConfigurationAndPlatform>
```

The first condition sets the value to true because MSBuildWorkspace sets the `BuildingInsideVisualStudio` property to true. This should be an easy fix. However, as a workaround, you can set `ShouldUnsetParentConfigurationAndPlatform` to `false` when you create your MSBuildWorkspace.
