### ISSUE TITLE
Operation.None generated for VB ReDim statement/clause

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#30175]
This is the root cause of https://github.com/dotnet/roslyn/issues/29373. MakeFieldReadOnly analyzer attempts to analyze read/writes using IOperation API, but does not correctly identify the write for ReDim, causing a false report.

**Comment by Neme12** [comment]
Can IOperation just show the method call it compiles to?  :smile:

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/30217
