### ISSUE TITLE
Editor Completion - Partner Signoff - Razor - Completion not firing

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#30188]
Originally discussed in https://github.com/dotnet/roslyn/issues/27534

> I created an ASP.NET application and tried to edit a cshtml file. Typing '@' and then a letter like 'a', I expect to get a completion. However, I haven't seen it and could not catch that Roslyn completion was called. Please advise.

> Are you using Razor bits that implement the async completion API? aspnet/Razor#2227

**Comment by ivanbasov** [comment]
validated with the VAL build: works fine
