### ISSUE TITLE
Editor Completion - Partners - TS - "Exception and assert when completing inside import path"

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#30182]
Tracking issue in email. We think it's the use of an older editor binary:

> Editor will now accept empty (but not null) toolTipText.

**Comment by dpoeschl** [comment]
@ivanbasov to check if we're sending the null instead of string.Empty

**Comment by ivanbasov** [comment]
@dpoeschl , @AmadeusW . we really send null. replacing this with string.Empty
