### ISSUE TITLE
[Feature] Extension Properties.

### ISSUE THREAD

**Issue by viniciusjarina** [dotnet/roslyn#3019]
Extension methods are very useful, but sometimes you want to extend a type with a property

References: http://blogs.msdn.com/b/ericlippert/archive/2009/10/05/why-no-extension-properties.aspx
http://stackoverflow.com/questions/619033/does-c-sharp-have-extension-properties

**Comment by sharwell** [comment]
Duplicate of #112.

**Comment by sharwell** [comment]
(By the way @viniciusjarina, duplicates are fine. We don't expect you to automatically know what the 3018 items created before yours was, although a search is advised. If you add your support to an existing proposal it helps build momentum. :smile: )

**Comment by viniciusjarina** [comment]
Hey @sharwell I did a superficial search, and didn't find Sorry :wink:
