### ISSUE TITLE
Elastic marker only when necessary

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#302]
We're working on diagnostics and code fixes that affect the coding style within files. As such, it's very important that the changes we make preserve the original formatting for everything not directly related to the change being made. For example, if the code fix is supposed to remove parentheses from an expression, then the input and output could resemble this:

``` csharp
// input:
int x =  (0 +2- 1-1) ;
// output:
int x =  0 +2- 1-1 ;
```

We're having trouble with certain cases where the code fix _must_ insert a space for correctness, such as the following:

``` csharp
// input:
return(0);
// output:
return 0;
```

It seems like the option we want is to add `SyntaxFactory.ElasticMarker` to the leading trivia of the expression. Unfortunately, when we use this, the formatter treats this as a request to reformat the entire expression (or at minimum both the leading and trailing trivia for the expression, even if no changes are required).

We found a solution by using `SyntaxFactory.ParseSyntaxTree` to check if the actual output without a space is equivalent to our intended output, but this seems like a _very_ expensive approach, and we aren't even 100% sure it works in all cases.

We want to be able to include a `SyntaxTrivia` which means the following:

> This trivia contains no text, unless omitting it would change the meaning of the code. In the latter case, the trivia is written as exactly one space. No alterations will be made to any other `SyntaxTrivia` as a result of using this trivia.

Solution using `ElasticMarker` which caused undesired reformatting:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/450

Solution using `ParseSyntaxTree` which we'd like to avoid:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/453

**Comment by heejaechang** [comment]
this is probably a bug in code where it uses elastic trivia to find place to format without using FormatAnnotation.

Roslyn formatter is token based formatter, so there is no reason to format whole expression, it can just format two tokens.

**Comment by heejaechang** [comment]
adding both ide and analyzers since I am not sure whether the code belong to analyzer team or ide team.

**Comment by mattwar** [comment]
You could use elastic markers only when necessary (if there is no trivia remaining between two tokens after your edit.

```csharp
        [Fact]
        public void RemoveParens()
        {
            var ws = new AdhocWorkspace();

            TestRemoveParens("return(x);", "return x;", ws);
            TestRemoveParens("return   (  x  )  ;", "return     x    ;", ws);
        }

        private void TestRemoveParens(string code, string expected, Workspace ws)
        {
            var statement = SyntaxFactory.ParseStatement(code);
            var parens = statement.DescendantNodes().OfType<ParenthesizedExpressionSyntax>().First();

            // remove tokens and leave trivia
            var withoutParens = parens.Expression
                .WithLeadingTrivia(parens.OpenParenToken.LeadingTrivia.AddRange(parens.CloseParenToken.TrailingTrivia).AddRange(parens.Expression.GetLeadingTrivia()))
                .WithTrailingTrivia(parens.GetTrailingTrivia().AddRange(parens.CloseParenToken.LeadingTrivia).AddRange(parens.CloseParenToken.TrailingTrivia));

            withoutParens = ConditionallyAddElasticMarker(withoutParens, parens);

            var newStatement = statement.ReplaceNode(parens, withoutParens);
            var actual = Formatter.Format(newStatement, SyntaxAnnotation.ElasticAnnotation, ws).ToFullString();

            Assert.Equal(expected, actual);
        }

        // only adds elastic marker on exterior if there is no trivia between node and enclosing tokens
        private TNode ConditionallyAddElasticMarker<TNode>(TNode newNode, SyntaxNode oldNode) where TNode : SyntaxNode
        {
            var firstToken = newNode.GetFirstToken();
            var prevToken = oldNode.GetFirstToken().GetPreviousToken();
            if (!prevToken.HasTrailingTrivia && !firstToken.HasLeadingTrivia)
            {
                newNode = newNode.WithLeadingTrivia(SyntaxFactory.ElasticMarker);
            }

            var lastToken = newNode.GetLastToken();
            var nextToken = oldNode.GetLastToken().GetNextToken();
            if (!nextToken.HasLeadingTrivia && !lastToken.HasTrailingTrivia)
            {
                newNode = newNode.WithTrailingTrivia(SyntaxFactory.ElasticMarker);
            }

            return newNode;
        }
```

**Comment by Pilchie** [comment]
Given the workaround @mattwar proposes, I don't we'll tackle this for 1.0.

**Comment by sharwell** [comment]
This is the solution we took in DotNetAnalyzers/StyleCopAnalyzers#646.
