### ISSUE TITLE
AnalyzerDependencyChecker creates spurious warnings in the Error List

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#3020]
Analyzer assemblies with code fixes end up with a reference to System.Composition.AttributedModel. The `AnalyzerDependencyChecker` verifies that all of an analyzer assembly's references are either satisfied by other analyzer assemblies, or are already loaded in the process. System.Composition.AttributedModel ships with VS but may not be loaded when this check is performed, leading us to create an unhelpful warning in the error list:

> Analyzer assembly 'D:\Roslyn\Main\Open\Binaries\Debug\Microsoft.CodeAnalysis.FxCopAnalyzers.dll' depends on 'System.Composition.AttributedModel, Version=1.0.27.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' but it was not found. Analyzers may not run correctly.

Within VS we should just white-list all assemblies that start with "System"; that is, assume that even if we don't know where they are and they aren't already loaded, they will be found by VS when and if needed.

This would also bring us in line with the behavior of VBCSCompiler.exe.

### Repro Steps ###

1. Create a new C# Console Application project.
2. Add Microsoft.CodeAnalysis.FxCopAnalyzers.dll and Microsoft.CodeAnalysis.CSharp.FxCopAnalyzers.dll as analyzer references.
3. Save the project.
4. Restart VS.
5. Open the console application project again.

#### Expected Behavior ####
No warnings in the error list.

#### Actual Behavior ####
The above warning appears for each of the analyzer references.

**Comment by tmeschter** [comment]
@mavasani Would you be able to verify this fix?

**Comment by mavasani** [comment]
Verified fix.
