### ISSUE TITLE
Upgrading NuGet.CommandLine breaks Analyzer project

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#3021]
Repro:
1. Create a project from the "Analyzer with Code Fix (NuGet + VSIX)" template
2. Build the project: it succeeds.
3. In Solution Explorer, right-click the Analyzer project node and select Manage NuGet packages.
4. In NuGet package manager, upgrade NuGet.CommandLine from 2.8.2 (which comes in the template) to latest available (2.8.5 at time of this writing).

Expected: I can still build my project.

Actual: The build fails with the error:

C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4707,5): error MSB3073: The command ""C:\Users\lgolding\Documents\Visual Studio 2015\Projects\MyAnalyzers\packages\NuGet.CommandLine.2.8.2\tools\NuGet.exe" pack Diagnostic.nuspec -NoPackageAnalysis -OutputDirectory ." exited with code 3.

This is because the project file has a postbuild step that runs "nuget.exe pack" explicitly from the 2.8.2 directory, and upgrading to NuGet.CommandLine.2.8.5 doesn't change this.

**Comment by sharwell** [comment]
This is completely fixed if the templates adopt the second suggestion I made in [this comment](https://github.com/dotnet/roslyn/issues/2710#issuecomment-101795942) (using the NuGet package I created for packaging NuGet packages from the output of a single project).

**Comment by davkean** [comment]
Moving to SDK.

**Comment by ronelm2000** [comment]
Hey, to anyone experienced this error, I made a band-aid workaround for the real problem.

1. Go to your project directory/packages and find the NuGet.CommandLine.<version> folder. Copy the folder name.
2. Go to your Analyzer Project (Portable) and click on Properties.
3. Go to Build Events
4. Replace the deprecated folder name with the necessary folder name.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #34](https://github.com/dotnet/roslyn-sdk/issues/34) via [**ZenHub**](https://www.zenhub.com/)
