### ISSUE TITLE
Should `NonNullTypes` be constructed from single enum parameter?

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#30215]
Currently, the attribute stores two bits of information:
- a bool for interpreting un-annotated reference types as `non-null` rather than `null-oblivious`
- a bool for disabling the flow analysis warnings

We discussed allowing more options for controlling the warnings.
Also, some combinations of options don't make sense `[NonNullTypes(false, Warnings = true)]`.

**Comment by cston** [comment]
No longer applies.
