### ISSUE TITLE
Investigate impact of allowing and emitting explicit ```object``` constraint for a type parameter on interop with VB

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#30227]
There was at least one negative impact caught by unit-tests. There still can be other effects.

Because of this change the following unit test got broken:
```
        [ClrOnlyFact]
        public void InheritedObjectConstraint2()
        {
            var csCompilation = CreateCSharpCompilation("InheritedObjectConstraint2CS",
@"using System;
public abstract class Base1<T>
{
    public virtual void Goo<G>(G d) where G : struct, T { Console.WriteLine(""Base1""); }
}
public class Base2 : Base1<Object>
{
    public override void Goo<G>(G d) { Console.WriteLine(""Base2""); }
}",
                compilationOptions: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
            var csVerifier = CompileAndVerify(csCompilation);
            csVerifier.VerifyDiagnostics();

            var vbCompilation = CreateVisualBasicCompilation("InheritedObjectConstraint2VB",
@"Imports System
Class Derived : Inherits Base2
    Public Overrides Sub Goo(Of G As Structure)(ByVal d As G)
        Console.WriteLine(""Derived"")
    End Sub
End Class

Module Program
    Sub Main
        Dim x As Base1(Of Object) = New Derived
        x.Goo(1)
    End Sub
End Module",
                compilationOptions: new Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilationOptions(OutputKind.ConsoleApplication),
                referencedCompilations: new[] { csCompilation });
            vbCompilation.VerifyDiagnostics();
        }
```

In order to mitigate this, a change was made to implementation of MethodSignatureComparer.AreConstraintTypesSubset for VB. In particular, now it simply ignores an explicit ```object```  constraint, the same way C# implementation does. 

Note that, before this change, the following code was invalid in VB:
```
Interface IA(Of T)
    Sub M(Of U As T)()
End Interface

Class C
    Implements IA(Of Object)

    Public Sub M(Of U)() Implements IA(Of Object).M
        Throw New NotImplementedException()
    End Sub
End Class

Public MustInherit Class Base1(Of T)
    Public Overridable Sub Goo(Of G As {Structure, T})(d As G)
    End Sub
End Class
Public Class Base2
    Inherits Base1(Of Object)
    Public Overrides Sub Goo(Of G As Structure)(d As G)
    End Sub
End Class
```
```
(8) : error BC32078: 'Public Sub M(Of U)()' cannot implement 'IA(Of Object).Sub M(Of U)()' because they differ by type parameter constraints.

    Public Sub M(Of U)() Implements IA(Of Object).M
                                    ~~~~~~~~~~~~~~~
(19) : error BC32077: 'Public Overrides Sub Goo(Of G As Structure)(d As G)' cannot override 'Public Overridable Sub Goo(Of G)(d As G)' because they differ by type parameter constraints.

    Public Overrides Sub Goo(Of G As Structure)(d As G)
```

Now, it is valid and it doesn't look like there is a good reason to disallow implementing or overriding like that. Especially that an explicit ```Object``` constraint is not allowed in VB. Nevertheless, we need to confirm that this is a change that we really would like to make and whether it should be tied to a new language version, or, perhaps, should be treated as a minor bug fix.

**Comment by jaredpar** [comment]
@AlekseyTs 

> In particular, now it simply ignores an explicit object constraint, the same way C# implementation does.

Where does the explicit object constraint come into play here? I didn't see one in the code. 

Is this back from when the compiler emitted an object constraint as a part of our metadata code generation to indicate a non-null constraint?

**Comment by AlekseyTs** [comment]
> Is this back from when the compiler emitted an object constraint as a part of our metadata code generation to indicate a non-null constraint?

Yes, I believe that is the case. I believe we stopped doing this.
