### ISSUE TITLE
Restore.cmd keeps downloading dotnet SDK that is already installed

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#30224]
Restore.cmd wasn't working for me in the `features/compiler` branch (which requires .NET Core SDK 2.1.300-rtm-008866) because I always got the following result - the script kept trying to download the sdk, even though I knew it was already installed (this is a little frustrating experience as you can imagine).
```
Repo Dir C:\Users\neme1\Source\Repos\roslyn
Binaries Dir C:\Users\neme1\Source\Repos\roslyn\Binaries
Downloading CLI 2.1.300-rtm-008866
```

I kept digging into the scripts and found Ensure-DotnetSdk which contains the installation procedure, and then Test-DotnetDir which checks to see if a certain sdk & runtime is installed:
https://github.com/dotnet/roslyn/blob/4c84e35e122c0b91c7d147d7236cfcfcf0bf98a8/build/scripts/build-utils.ps1#L114-L118

I then discovered that I do not have the runtime that this function is trying to find, which was 2.0.7. This runtime doesn't actually come with the specified SDK version, 2.1.300-rtm-008866. It comes with 2.1.105.

I would appreciate if the tool
1. Didn't try to download and install a dotnet sdk unless prompted (especially if it is already installed)
2. Told me that I have to additionally install a certain runtime version (or another SDK that comes with it)

so that I or another user doesn't have to spend a few hours trying to pin this down next time. Thanks

**Comment by Neme12** [comment]
tagging @jaredpar

**Comment by jaredpar** [comment]
> Didn't try to download and install a dotnet sdk unless prompted

The goal of build.ps1 is to keep the Roslyn experience as simple as possible. The repository is built by a wide range of users and across a wide range of environments. This includes installing any SDKs, tools or runtimes that we need in order to build. Not doing this by default would break a large number of scenarios.

> Told me that I have to additionally install a certain runtime version

This is an odd duck case. Typically we never want to require an SDK + a runtime. We'd prefer to just install the SDK and use the runtime. In this specific case we got into a situation where we couldn't update the SDK but had to update the runtime. Now that we're back onto the 2.1.400 train of releases this shouldn't be necessary again.

**Comment by Neme12** [comment]
Ok but I spent a whole day trying to find out what's wrong 😞 Couldn't there be a better experience in case this happens again than seeing a dotnet sdk being downloaded that is already installed?

I though there was something wrong with my dotnet instalaltion and reinstalled all sdks 2 times, tried repairs, messing with environment variables, deleting all folders and caches... There must be a better way to show something is wrong here.

**Comment by Neme12** [comment]
> The goal of build.ps1 is to keep the Roslyn experience as simple as possible

Couldn't the script then also download the correct runtime if it doesn't exist, and only download the sdk if it's the sdk itself that doesn't exist, not the runtime?

**Comment by Neme12** [comment]
Then reason I didn't let it just download, extract and use that version is because I was getting path too long errors.

**Comment by jaredpar** [comment]
> Couldn't the script then also download the correct runtime if it doesn't exist, and only download the sdk if it's the sdk itself that doesn't exist, as opposed to the runtime?

If we have to do a runtime / SDK split again I'll likely look into this. 

> Then reason I didn't let it just download, extract and use that version is because I was getting path too long errors.

What OS are you on? One thing we've been tossing around a bit is whether or not to move past `MAX_PATH` for our infrastructure. Today we're pretty careful to keep our max file path (src + binaries directory) around the low 200s to avoid problems for contributors. If you're hitting it though it may invalidate our assumptions that most contributors could easily absorb this.

**Comment by Neme12** [comment]
winver says `Windows 10 Version 1803 (OS Build 17134.285)`

My repo folder is `C:\Users\neme1\Source\Repos\roslyn` (the default for cloning in Visual Studio) and I was hitting long path errors deep inside the extracted dotnet sdk inside Binaries.

**Comment by CyrusNajmabadi** [comment]
Not able to repro this.  Closing out as too old.
