### ISSUE TITLE
Formatting option for space after //

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#30239]
I was encouraged by @sharwell's feature request in #30089, so I'm creating one of my own. :smile:

After typing `//` for a block comment and an alphanumeric character, I'd like a single space inserted before that character, so that my `//` and text are never touching.

**Steps to Reproduce:**

Type a new character inside the comment (`|` indicates caret position)
```c#
//|
```
**Expected behavior**
```c#
// a|
```

**Actual behavior**
```c#
//a|
```

I'm not sure whether this is something too aggressive for Roslyn to do out of the box, but I thought I'd give it a try. If this was an option that was turned off by default, there's risk that the majority of users would not discover this so there would be no usage.

**Design considerations**

- It would probably be easiest to implement this as a command handler, but this is something that could potentially also be part of formatting, so that it can be fixed as part of Format and Code Cleanup. Should that be the case?
- This could theoretically even be a code style, but I'm not sure if that's a good option, especially when we get a formatting analyzer that would flag all formatting violations including this one (if it was a formatting violation).
- Should the line comment command create a space too? I don't think I have a preference here. The vast majority of my comment command usage is commenting out code, but I don't care whether commented out code is indented with a space or not, especially because I almost never commit commented out code. (Actually, it might even be beneficial to distinguish commented out code and regular comments. The fact that there is a space before the text could indicate it is a regular comment, and no space would be a sign of commented out code. But that's just an idea.)
- I'm not sure whether this should be any kind of formatting violation or an analyzer with a diagnostic at all. I'm personally not as much bothered if I see a comment without a space, I just want it to be automatically inserted when I type a new one.

**Comment by CyrusNajmabadi** [comment]
This feels too aggressive to me.  But i'd be ok with it if there were an option here.  I personally do `//whatever` a lot, and so i don't like the idea that that would be updated across all code-bases.

**Comment by dpoeschl** [comment]
Design Meeting Notes
- Have a formatting option (.editorconfig) for this
- No changes to edit-time typing experiences

**Comment by CyrusNajmabadi** [comment]
Clsoing out as not planned.
