### ISSUE TITLE
Code fix for CS1002: "; expected"

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#30238]
I'd like a code fix that inserts the semicolon for me.

**Comment by MaStr11** [comment]
The fix should also support [CS1003](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1003), [CS1513](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1513), [CS1043](https://docs.microsoft.com/de-de/dotnet/csharp/misc/cs1043) and maybe other related compiler errors.

**Comment by Neme12** [comment]
> #23326 and search in that issue for 'expected' to find more candidates.

Thanks for the link. Is that supposed to be kept as an updated list of compiler diagnostics and issues or code fixes for them? if so, it would be nice for this to exist somewhere in Roslyn where anyone could contribute to that.

**Comment by Neme12** [comment]
That spreadsheet is very nice, but I think it might be a good idea to make a textual form of this or something that people can contribute to.

**Comment by MaStr11** [comment]
I went through the excel sheet and this is what I came up with. The fixer can be made to support these error codes:

Error | Error code | Errortext
-- | -- | --
ERR_SemicolonExpected | CS1002 | ; expected
ERR_CloseParenExpected | CS1026 | ) expected
ERR_RbraceExpected | CS1513 | } expected
ERR_LbraceExpected | CS1514 | { expected
ERR_InExpected | CS1515 | 'in' expected
ERR_ExpectedContextualKeywordOn | CS0743 | Expected contextual keyword 'on'
ERR_ExpectedContextualKeywordEquals | CS0744 | Expected contextual keyword 'equals'
ERR_ExpectedContextualKeywordBy | CS0745 | Expected contextual keyword 'by'

There is also the more general 

Error | Error code | Errortext
-- | -- | --
ERR_SyntaxError | CS1003 | Syntax error, '{0}' expected

This one has some complications (e.g. the *character* needs to be transported from the compiler to the fixer via the diagnostic) and needs careful planing (maybe a separate CodeFix).

There are some errors that come up with alternatives:

Error | Error code | Errortext
-- | -- | --
ERR_SemiOrLBraceOrArrowExpected | CS8180 | { or ; or => expected
ERR_SemiOrLBraceExpected | CS1043 | { or ; expected
ERR_ThisOrBaseExpected | CS1018 | Keyword 'this' or 'base' expected
ERR_BadVarDecl | CS1528 | Expected ; or = (cannot specify   constructor arguments in declaration)
ERR_InvalidArray | CS0178 | Invalid rank specifier: expected ','   or ']'

These might be usefull to consider depending on how often they appear. If any of these are supported the CodeFix should be implemented to support alternative fixes (nested CodeActions).

Error | Error code | Errortext
-- | -- | --
ERR_ReturnExpected | CS0161 | '{0}': not all code paths return a   value

This one could insert a `return ;` and place the cursor between `return` and `;` but I'm not sure that such a fix would be a good idea.

Error | Error code | Errortext
-- | -- | --
ERR_UnexpectedCharacter | CS1056 | Unexpected character '{0}'

This one could offer to delete the unexpected character.

While technically all of this is possible, the team needs to decide whether it is usefull to offer such fixes at all. These errors come up quite often and there is the danger that such fixes would clutter the context menu.

**Comment by Neme12** [comment]
> there is the danger that such fixes would clutter the context menu.

You're right. In my opinion, these should be quite low in priority so you would only get them at the top if you have no other errors. For example:
```c#
int M()
{
    return Foo()
}
```
Here you'd like to hit Ctrl+. and generate method `Foo` even though you don' have a semicolon yet.

**Comment by CyrusNajmabadi** [comment]
Closing out.  Unclear how a codefix is better/faster here than just hitting `;`.
