### ISSUE TITLE
Custom Attribute type is always ErrorType in NetCore

### ISSUE THREAD

**Issue by abrunetta** [dotnet/roslyn#30248]
**Version Used**: Microsoft.CodeAnalysis.CSharp 2.9.0

**Steps to Reproduce**:

1. Create a NetCore assembly with a Custom Attribute in it, named `MyCustomAttribute`, inheriting `Attribute` and using `AttributeUsage=Method`.
2. Create a NetCore assembly referencing _CodeAnalysis.CSharp 2.9.0_ to try to get the type of the attributes of a method. Add the first assembly as a `MetadataReference` of the compilation.
3. Analyze an arbitrary code (a `string`) with a method using `MyCustomAttribute` and check the attribute type.

**Expected Behavior**:
The attribute type should be `NamedType` (MyCustomAttribute) and `CandidateSymbol` should be `null`.

**Actual Behavior**:
The attribute type is always resolved to an `ErrorType`, `CandidateSymbol` is `MyCustomAttribute` and `CandidateReason` is `NotAnAttributeType`.

**Observations**:
- The same code targeting NetFramework 4.6 appears to work as expected with the same Roslyn version (2.9.0), so maybe this is related to NetCore.
- If we specify a custom type (a class) from the same referenced assembly as the return type of the same method, `ReturnType` is resolved as `NamedType` (as expected), so the issue appears to be related to attributes.

I'm attaching some sample code with unit test cases.
[RoslynAttributeTest.zip](https://github.com/dotnet/roslyn/files/2435230/RoslynAttributeTest.zip)

**Comment by jaredpar** [comment]
What diagnostics are reported here?

Also what references are you providing to the compilation?

**Comment by WenningQiu** [comment]
I just ran into a similar issue with DataContractAttribute. Adding a reference to "System.Runtime.dll" in addition to typeof(DataContractAttribute).Assembly.Location appears to help.

@abrunetta

**Comment by Vlad-Stryapko** [comment]
Hey guys, I've just tried to write a Roslyn analyser using a standard VS 2019 template (though I've updated the NuGets and .NET Core to newer versions) and encountered the same issue. 
Here's the repo with a reproducible case: 
https://github.com/Vlad-Stryapko/AnalyserPoc

1. Place a breakpoint [here](https://github.com/Vlad-Stryapko/AnalyserPoc/blob/master/AnalyserPoc/AnalyserPoc/AnalyserPocAnalyzer.cs#L44)
2. Debug the UT from [here](https://github.com/Vlad-Stryapko/AnalyserPoc/blob/master/AnalyserPoc/AnalyserPoc.Test/AnalyserPocUnitTests.cs#L25)
3. Observe the attributeClasses variable content. 

Expected: NamedTypes for all three attributes.
Actual: ErrorType for all three attributes with a CandidateSymbol of corresponding attribute and CandidateReason equal to NotAnAttributeType.

Notes:
I've included all the metadata references as can be seen [here](https://github.com/Vlad-Stryapko/AnalyserPoc/blob/master/AnalyserPoc/AnalyserPoc.Test/Helpers/DiagnosticVerifier.Helper.cs#L155).

[This line](https://github.com/Vlad-Stryapko/AnalyserPoc/blob/master/AnalyserPoc/AnalyserPoc.Test/AnalyserPocUnitTests.cs#L55) works correctly and the result is NamedType.

**Comment by TomasEkeli** [comment]
I have the same issue while trying to run my analyzers in tests. 

This is my full helper-class to compile and run an analyzer on a given source as a string if it helps:

`using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Runtime;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Analyzers
{
    public class can_compile_and_analyze
    {
        protected static async Task<IEnumerable<Diagnostic>> CompileAndAnalyze(
            Project project,
            DiagnosticAnalyzer analyzer
        )
        {
            var compilation = await project.GetCompilationAsync();

            var compilationWithAnalyzer = compilation
                .WithAnalyzers(
                    ImmutableArray.Create(analyzer)
                );

            // does not work with await!
            return compilationWithAnalyzer
                .GetAnalyzerDiagnosticsAsync()
                .Result;
        }
        protected static Project MakeProjectWith(string class_source)
        {
            var projectId = ProjectId.CreateNewId("test");
            var sln = new AdhocWorkspace()
                .CurrentSolution
                .AddProject(
                    projectId: projectId,
                    name: "test",
                    assemblyName: "testAssembly",
                    language: LanguageNames.CSharp
                )
                .AddMetadataReference(projectId, CorlibReference)
                .AddMetadataReference(projectId, SystemRuntimeReference)
                .AddMetadataReference(projectId, NetStdReference)
                .AddMetadataReference(projectId, SystemCoreReference)
                .AddMetadataReference(projectId, CSharpSymbolsReference)
                .AddMetadataReference(projectId, CodeAnalysisReference)
                .AddMetadataReference(projectId, GDPRAnalysisReference);

            const string filename = "class_as_string.cs";
            var documentId = DocumentId.CreateNewId(projectId, filename);
            sln = sln.AddDocument(
                documentId,
                filename,
                SourceText.From(class_source)
            );

            return sln.GetProject(projectId);
        }

        static readonly MetadataReference CorlibReference =
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location);
        static readonly MetadataReference SystemRuntimeReference =
            MetadataReference.CreateFromFile(typeof(GCSettings).Assembly.Location);
        static readonly MetadataReference NetStdReference =
            MetadataReference.CreateFromFile(typeof(Attribute).Assembly.Location);
        static readonly MetadataReference SystemCoreReference =
            MetadataReference.CreateFromFile(typeof(Enumerable).Assembly.Location);
        static readonly MetadataReference CSharpSymbolsReference =
            MetadataReference.CreateFromFile(typeof(CSharpCompilation).Assembly.Location);
        static readonly MetadataReference CodeAnalysisReference =
            MetadataReference.CreateFromFile(typeof(Compilation).Assembly.Location);
        static readonly MetadataReference GDPRAnalysisReference =
            MetadataReference.CreateFromFile(typeof(PersonalDataAttribute).Assembly.Location);
    }
}`

Funny thing is it seems to work when I run the analyzers as part of the build where I'm using them. This leads me to suspect there's something missing in the setup of the AdHocWorkspace.

Hope this helps!
