### ISSUE TITLE
Slow performance in ImportAdder + Simplifier + Formatter combination

### ISSUE THREAD

**Issue by ulrichb** [dotnet/roslyn#3024]
In Roslyn 1.0.0-rc2, calling `ImportAdder`, `Simplifier`, and `Formatter` after each other on a C# document with about 1000 lines of code takes nearly a second.

Repro sample: https://gist.github.com/ulrichb/8ec9737d75c7f9fce741

Timing results (executed multiple times to eliminate one-time effects):

```
Execution #1
ImportAdder.AddImports() Elapsed: 00:00:01.5558438
Simplifier.ReduceAsync() Elapsed: 00:00:00.8915521
Formatter.FormatAsync() Elapsed: 00:00:00.2153323

Execution #2
ImportAdder.AddImports() Elapsed: 00:00:00.4169663
Simplifier.ReduceAsync() Elapsed: 00:00:00.5196688
Formatter.FormatAsync() Elapsed: 00:00:00.0478881

Execution #3
ImportAdder.AddImports() Elapsed: 00:00:00.4154774
Simplifier.ReduceAsync() Elapsed: 00:00:00.5244430
Formatter.FormatAsync() Elapsed: 00:00:00.0455732
```

In our scenario, this becomes a problem because we need to format hundreds of files at once.

Note that while we were analyzing this problem, the distribution of time spent over the three methods was highly volatile: sometimes `Formatter` would take most of the time, sometimes `Simplifier`. This was with different inputs; with the repro sample, the distribution seems to be stable as given above.

Calling the three async methods using `await` rather than evaluating the `Result` synchronously doesn't change anything. (And they need to be called in a row due to the data dependency.)

**Comment by Pilchie** [comment]
@pharring @rchande Any input on this?

**Comment by pharring** [comment]
@ulrichb Is this a regression from a previous build?

**Comment by ulrichb** [comment]
@pharring We don't know. Roslyn 1.0.0-rc2 was the first version where we used `ImportAdder`/`Simplifier`/`Formatter` for bigger files and observed the performance hit within our application.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is a perf report from 8 years ago.  These components are designed to be fast-enough for the IDE features we ship them in.  If someone uses tehm as an api and wants/needs them to be faster, we would accept PRs to accomplish that.
