### ISSUE TITLE
Brace Matching should format embedded statement owner when inserting braces

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#3025]
From https://connect.microsoft.com/VisualStudio/feedback/details/1338564/connect-formatting-issue.

When automatic brace completion reformats on enter after it inserts the `}`, it only formats the span from `{` to `}`.  With normal format on '}`, we extend the span to the embedded statement owner if there is one.

We should do the same here.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this in nearly 10 years.
