### ISSUE TITLE
WinForms generated code warns about uninitialized fields

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#30268]
This was reported recently by a preview user on .NET Core 3, and also previously (by Pilchie).

![winforms](https://user-images.githubusercontent.com/12466233/46365599-dd188600-c62d-11e8-90a0-40c9fe9fcb38.png)

**Comment by jaredpar** [comment]
Related to #32745

**Comment by jcouv** [comment]
Updating the bug to reflect that the fix made it into dev16 preview4.
