### ISSUE TITLE
Analyzer .nuspec file hardcodes values that should come from assembly attributes

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#3026]
Repro:
1. Create a project from the "Analyzer with Code Fix (NuGet + VSIX)" template.
2. Build the project.
3. In the output directory, rename the .nupkg to .zip, open the zip file, and examine the .nuspec file. Note that it specifies version=1.0.0.0 and authors={project name}.
4. Modify AssemblyInfo.cs, setting (for example) AssemblyVersion=2.0.* and AssemblyCompany=Contoso
5. Rebuild the project.
6. Again examine the .nuspec file in the generated .nupkg.

Expected: The version and authors metadata should match the corresponding assembly attributes.

Actual: The metadata is unchanged.

This is because the postbuild step that creates the .nupkg specifies the .nuspec file as input, and the .nuspec file hardcodes the metadata.

If instead the postbuild step specified the project file $(MSBuildThisFileFullPath), and the .nuspec file used placeholders for the metadata (such as $version$ and $author$), then the .nupkg would automatically carry the metadata specified in the assembly attributes.

**Comment by jmarolf** [comment]
fixed with internal changeset 1480632. Larry, can you verify this?

**Comment by lgolding** [comment]
Verified, with the one change we discussed (setting $username$ as default for <authors>).
