### ISSUE TITLE
Changes to GetValueUsageInfo for invocations on structs

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#30269]
See comments from @Neme12: https://github.com/dotnet/roslyn/pull/30155#issuecomment-425120266 and https://github.com/dotnet/roslyn/pull/30155#issuecomment-425128179

We need to do the following test work as part of this change:
1. Add unit tests for all analyzers consuming this API ([current references](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Extensions/OperationExtensions.cs,ad91198d4e134ece,references) indicate it is used by MakeFieldReadOnly and RemoveUnunsedMembers analyzers)
2. Verify values for the new `Kind` column in Find All References window (manual verification)

**Comment by Neme12** [comment]
> Note: the ref/in extension method part affects classes as well.

Actually no, it doesn't, ref extension methods are only allowed on structs... don't listen to me :smile:

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
