### ISSUE TITLE
Allow CompletionProviders via nuget package's Analyzers

### ISSUE THREAD

**Issue by kzu** [dotnet/roslyn#30270]
Currently, you need a VS extension to provide one. Since a completion provider might provide completion to an accompanying library, it might be more useful to ship it together with the library via a nuget package, just like the analyzers and code fixes can.

See https://github.com/dotnet/roslyn/issues/15974#issuecomment-426364738

**Comment by kzu** [comment]
I'd love to see this implemented, since it would also make it for a compelling way to extend the IDE experience in a cross platform way (VS and VSfM).

Thanks!

**Comment by kzu** [comment]
Maybe if I got some pointers, I could give it a shot at implementing it if there's an agreement that it would be useful?

**Comment by kzu** [comment]
Circling back on this, are there any tips you could share so I can try to implement this? Or do you foresee this being a complex and risky feature? I'd love to learn more and see if I can help. 

Thanks!

**Comment by SamPruden** [comment]
I'd love this, but I'm not sure if my specific use case is covered by normal completion providers. I'd like to be able to filter out and hide some completion items according to context. Sometimes I know that a member should never be used in a particular place. I can make an analyzer mark it as an error, but I would prefer to also tell the IDE not to suggest it.

I can also see libraries offering context aware autocompletion templates as a very nice thing.
