### ISSUE TITLE
Fix failure to dispose 'scope' after failure to dispose 'connection'

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#30271]
In the following code, an exception during the call to `connection.Dispose` will result in `scope` not getting disposed. This eventually leads to an exception in the finalizer of `PinnedRemotableDataScope`.

https://github.com/dotnet/roslyn/blob/1f082e40860963edcd81d1567069aae924d9369f/src/Workspaces/Core/Portable/Remote/RemoteHostSessionHelpers.cs#L43-L46

:link: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/671157

**Comment by heejaechang** [comment]
yep. thank you for the analysis. I will take a look.
