### ISSUE TITLE
Failed pattern match makes variable become nullable

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#30278]
_From @Suchiman on October 2, 2018 23:24_

**Version**: 15.8.6 using latest 09/11/18 nullable reference types preview

In the following code, the presence of the `if (ex is ArgumentException)` will make `ex` become analyzed as nullable in the else branch
```csharp
try
{
    throw new InvalidOperationException();
}
catch (Exception ex)
{
    Console.WriteLine(ex.ToString()); // ok

    if (ex is ArgumentException)
    {
        throw;
    }

    Console.WriteLine(ex.ToString()); // null dereference reported here
}
```

_Copied from original issue: dotnet/csharplang#1904_

**Comment by jcouv** [comment]
Yes. That's a known issue :-(
We should be able to fix that before the next preview. https://github.com/dotnet/roslyn/issues/29318
Closing as duplicate.

**Comment by Suchiman** [comment]
@jcouv it's not tracked as known issue on the wiki page

**Comment by jcouv** [comment]
Good point. I'll add a note. Thanks
