### ISSUE TITLE
Bug with ternary ref assignment

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#30298]
**Version Used**: 
Visual C# Compiler version 2.10.0.0 (750236a7)

**Steps to Reproduce**:

Compile with `csc /langversion:latest test.cs`
```C#
using System;

class Program
{
    static void Main()
    {
        Node x = new Node(), y = new Node();
        bool flag = true;

        ref Node n = ref x;
        n = flag ? ref n.Left : ref n.Right;
        n = y;

        Console.WriteLine(x.Left);
    }
}

class Node { public Node Left, Right; }
```

**Expected Behavior**:

Outputs:
```
Node

```
due to x.Left being set to y.

**Actual Behavior**:

Outputs:
```

```
empty lines, with x.Left remaining null.

If I instead change:
```C#
n = flag ? ref n.Left : ref n.Right;
```
to be:
```C#
if (flag)
{
    n = ref n.Left;
}
else
{
    n = ref n.Right;
}
```
then it behaves as expected.

**Comment by stephentoub** [comment]
Why is the ref needed both before flag and before each side?

**Comment by alrz** [comment]
I think `b? ref x : ref y` is actually the same as `b? x : y` except that it becomes an L-value. So in any case we should `ref` the conditional to get a reference of the result. `M(ref b? ref x : ref y)` etc.

**Comment by Neme12** [comment]
I'm not completely sure... you'd have to ask someone from @dotnet/roslyn-compiler (try tagging them, it doesn't work if I do it as an outside contributor).

The way I understand it, the ref after the `=` is part of the assignment operator, not part of the expression , and it makes this a "ref assignment". The ref on each side od ?: makes this a ref conditional expression. Now a ref conditional can be used in a lot more cases, for example:
```c#
(flag ? ref n.Left : ref n.Right) = null;
```
a ref conditional makes the whole conditional expression an l-value. But that doesn't itself make all assignments ref-assignments. Why does the if statement work with just 1 ref then? Well, n.Left already *is* an lvalue. So you just add ref to the `=` operator to indicate that you want to ref-assign it.
