### ISSUE TITLE
Slow Compile with Analyzers

### ISSUE THREAD

**Issue by olmobrutall** [dotnet/roslyn#30291]
I'm distributing a Signum Framework a git submodule ([example application](https://github.com/signumsoftware/southwind)) and instead of distributing a Roslyn Analyzer as a Nuget package, I'm just [pointing to a dll](https://github.com/signumsoftware/southwind/blob/master/Southwind.Entities/Southwind.Entities.csproj#L85) stored in the source code.

In .Net Framework that was working OK, but now migrating to .Net Core this forces the project to recompile. 

**Version Used**: 
.Net Core

**Steps to Reproduce**:
1. *Recomended:* install [BuildVision](https://marketplace.visualstudio.com/items?itemName=stefankert.BuildVision) to see clearly which projects are being built a which not. 

**In .Net Framework Projects:** 
2. Clone https://github.com/signumsoftware/framework in branch `master`
3. Compile project Signum.Entities
![image](https://user-images.githubusercontent.com/720953/46426120-e5f87d00-c73d-11e8-8cf7-7fff71e0feb9.png)
4. Compile project Signum.Entities again 
![image](https://user-images.githubusercontent.com/720953/46426145-f6105c80-c73d-11e8-93d6-99b32162a2a9.png)

👌 Everithing is ok, the second time nothing is done 

**In .Net Core Projects:** 
2. Clone https://github.com/signumsoftware/framework in branch `core`
3. Compile project Signum.Entities ![image](https://user-images.githubusercontent.com/720953/46426482-07a63400-c73f-11e8-8ed5-64b999180f25.png)
4. Compile project Signum.Entities again ![image](https://user-images.githubusercontent.com/720953/46426513-17be1380-c73f-11e8-8787-94b5e81991a3.png)

💥 The project is always compiled. 

**Expected Behavior**:
The project does not need to be recompiled the second time.
**Actual Behavior**:
The project is recompiled the second time. 

This is what I've found so far: 
* The problem happens only when you have a `<Analyzer Include="..\Framework\Signum.Analyzer\Binaries\Signum.Analyzer.dll" />`
* The problem happens only on .Net Core, not in .Net Framework. 
* Analyzers distributed via Nuget do not suffer from this problem, only direct references. 

I'm going to switch to distribute it via Nuget anyway. But maybe you want to have a look at the source problem. 

Thanks in advance.

**Comment by mavasani** [comment]
This is likely an issue with MSBuild or the project system. I am going to port it to project-system repo to start with, and it can be moved over to MSBuild repo if the bug lies there.

**Comment by mavasani** [comment]
Ported to https://github.com/dotnet/project-system/issues/4117
