### ISSUE TITLE
VB: "Change signature" refactoring dialog should show modifiers in VB syntax.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#30296]
**Version Used**: 

Visual Studio Community 2017 v15.8.5

**Steps to Reproduce**:

Type the following code upon which we will invoke the `change signature` refactoring:

```vb
Public Class CFoo
  Public Sub Blah(ByVal ArgOne As String, ByRef ArgTwo As String)
  End Sub
End Class
```

Place the caret on the `Blah` method name and select `change signature` from the actions menu:

![vs_changesig_1](https://user-images.githubusercontent.com/20465797/46441792-41dbf980-c770-11e8-9338-03c4368eeab1.png)

The `change signature` refactoring dialog is displayed but uses the C# parameter modifier `ref` even though this is VB code and `ByRef` should be used instead:

![vs_changesig_2](https://user-images.githubusercontent.com/20465797/46441942-c4fd4f80-c770-11e8-849c-6db6d7febf49.png)

**Expected Behavior**:

Since the only thing you can do in this dialog is reorder the parameters, I am not sure why the `Modifier` column is needed at all, but since it is currently there, it should show the modifiers using the current project's language syntax (i.e `ByRef` in VB projects and `ref` in C# projects).

**Comment by ericmutta** [comment]
> Potential Solution in PR #30332

@AdamSpeight2008 (and @CyrusNajmabadi) thanks in advance for working through this! :+1: :+1:

**Comment by heejaechang** [comment]
fixed by the PR above

**Comment by ericmutta** [comment]
@heejaechang @jinujoseph many thanks for pushing this to completion :+1:
