### ISSUE TITLE
Declaration of ref/out parameters in lambdas without typename

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/roslyn#303]
Hello! 

I have a little suggestion for C# language. 
Let us have delegate like this:

``` cs
delegate T Parse<T>(string text);
```

and we want to create an instance:

``` cs
Parse<int> parse = text => Int32.Parse(text);
```

All is OK. What about ref/out parameters in a delegate?

``` cs
delegate bool TryParse<T>(string text, out T result);
```

when we want to create an instance…

``` cs
TryParse<int> parse1 = (string text, out int result) => Int32.TryParse(text, out result);
```

…we shoud to specify types on parameters.

Why is this required? What about a syntax below:

``` cs
TryParse<int> parse2 = (text, out result) => Int32.TryParse(text, out result);
```

?

**Comment by mikedn** [comment]
In this particular case you don't need to write any of the parameter stuff, it's just:

```C#
TryParse<int> parse1 = Int32.TryParse;
```

**Comment by alanfo** [comment]
This would be a worthwhile improvement to type inference, in my view.

As `ref` and `out` are *full* keywords, they can't possibly be type names and so there appears no reason why the compiler won't be able to infer the type from the delegate signature.

**Comment by paulomorgado** [comment]
I'm not sure I understand what you are proposing.

Would you care to elaborate a bit more?

**Comment by ViIvanov** [comment]
@paulomorgado Of course! Let us see a code below:
```cs
delegate T Parse<T>(string text);
delegate bool TryParse<T>(string text, out T result);

static void Main() {
  // We can create an instance of Parse<int> like this:
  Parse<int> parseHex1 = (string text) => Int32.Parse(text, NumberStyles.HexNumber);
  // or like this (and, I think, this way is more simple and more readable):
  Parse<int> parseHex2 = text => Int32.Parse(text);

  // To create an instance of TryParse<int> delegate
  // we must explicitly specify a types of arguments in a lambda expression:
  TryParse<int> tryParseHex1 = (string text, out int result) => Int32.TryParse(text, NumberStyles.HexNumber, null, out result);

  // And we can not now use a sintax like this:
  TryParse<int> tryParseHex2 = (text, out result) => Int32.TryParse(text, NumberStyles.HexNumber, null, out result);
}
```

Why this is meaningful: 
1. In some scenarios user can have a delegates with a few (three, four, …etc) parameters and when at least one of them has a `ref` or `out` modifier user must explicitly specify types of all "delegate parameters".
2. Follows from previous - we can not use anonymous types as type-parameters in delegates with `ref` or `out` parameters.

**Comment by omariom** [comment]
:+1:

**Comment by paulomorgado** [comment]
I ink you are missing the fact that, although you can't declare by reference type parameters in C#, when a parameter is expressed as of being of type __ref T__ (or __out T__, which is the same for the CLR - just extra validation from the compiler), the type is, actually, __&T__, which is not the same as __T__.

**Comment by ViIvanov** [comment]
@paulomorgado Excuse me, can you explain what do you mean? Why in you point of view
```cs
TryParse<int> tryParseHex1 = (string text, out int result) => Int32.TryParse(text, NumberStyles.HexNumber, null, out result);
```
is correct (it is valid C# code) and
```cs
TryParse<int> tryParseHex2 = (text, out result) => Int32.TryParse(text, NumberStyles.HexNumber, null, out result);
```
is not? In a both examples, types of arguments exactly the same. But, in the second line, it calculated by the compiler, not specified by user explicitly.

**Comment by paulomorgado** [comment]
I was trying to understand your issue, and I think I got it: the compiler should be able to infer the types from usage when there are __out__ parameters. Is that it?

**Comment by ViIvanov** [comment]
@paulomorgado Exactly! I'm sorry for my bad and poor English.

**Comment by alrz** [comment]
:+1:

**Comment by Thaina** [comment]
+1

thanks

**Comment by asvishnyakov** [comment]
:+1:

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #338](https://github.com/dotnet/csharplang/issues/338) via [**ZenHub**](https://www.zenhub.com/)
