### ISSUE TITLE
Assert in EngineV1.DiagnosticIncrementalAnalyzer.StateManager.VerifyDiagnosticStates

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#3030]
>	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateManager.VerifyDiagnosticStates(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateSet> stateSets) Line 173	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateManager.ProjectStates.VerifyDiagnosticStates(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateSet> stateSets) Line 219	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateManager.ProjectStates.GetOrUpdateAnalyzerMap(Microsoft.CodeAnalysis.Project project) Line 90	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateManager.ProjectStates.GetOrUpdateStateSets(Microsoft.CodeAnalysis.Project project) Line 38	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateManager.GetOrUpdateStateSets(Microsoft.CodeAnalysis.Project project) Line 72	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.AnalyzeSyntaxAsync(Microsoft.CodeAnalysis.Document document, System.Collections.Immutable.ImmutableHashSet<string> diagnosticIds, bool skipClosedFileChecks, System.Threading.CancellationToken cancellationToken) Line 143	C#

**Comment by amcasey** [comment]
I just opened CSharpCompletionService.cs.

**Comment by amcasey** [comment]
FYI @heejaechang @mavasani

**Comment by amcasey** [comment]
Dump is at %mymachine%/Dumps/DiagnosticAssert20150522.dmp.  Symbols are adjacent.

**Comment by heejaechang** [comment]
@tmeschter @mavasani @srivatsn @shyamnamboodiripad so, the actual issue is the way I create unique string for analyzer. so I need to fix it.

but the reason it surfaced now is because the way we create ID for AnalyzerFileReference.

we used to not consider assembly version and that was intentionally done that way. now 2 assembly with different version will be considered two different references rather than considered as same one. (the change in ID made de-dup to consider versions)

should we change it or should we now consider it as two different reference?

**Comment by mavasani** [comment]
@heejaechang I think we may want to allow different versions as different references, especially given 2 different projects might be referencing these separate versions (that seems like the most common real user scenario, correct?). Does the assert cause any bad behavior, or is it benign? If it is the latter, we may want to move this to 1.1.

**Comment by heejaechang** [comment]
@mavasani I think, regardless of the id issue, we want to fix this. so, now if there is any change in AssemblyIdentity we will consider two references to two different ones then. I am fine with it as long as that is what we expects.

**Comment by heejaechang** [comment]
done

**Comment by dpoeschl** [comment]
This just happened on my machine with sources/dogfood more recent than the fix, I think. Dump at %share%\public\davip\VerifyDiagnosticStates.dmp

**Comment by heejaechang** [comment]
David, do you have symbols for the dump?


-          heejae

**Comment by dpoeschl** [comment]
We figured it out -- I'm using recent stabilization sources, and this fix wasn't ported to stabilization as it didn't meet the bar.

**Comment by amcasey** [comment]
@dpoeschl I did the same thing. :)

**Comment by amcasey** [comment]
I opened roslyn.sln and it didn't assert.
