### ISSUE TITLE
ExtractMethod isn't aware of nullability

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#30314]
![image](https://user-images.githubusercontent.com/12466233/46496799-c7da5d80-c7cd-11e8-96c7-2ba3df9bb67d.png)

FYI @dpoeschl 

Note this can only be fixed once the compiler exposes public APIs for nullability of expressions (see [workitems list](https://github.com/dotnet/roslyn/issues/22152))

**Comment by CyrusNajmabadi** [comment]
>Note this can only be fixed once the compiler exposes public APIs for nullability of expressions (see workitems list)

This somewhat worries me.  Is each feature going to have to know about these types?  That seems... not good.  Shouldn't this just fall out, just like any other type change (like adding tuples)?

**Comment by jasonmalinowski** [comment]
Note that this one is somewhat special: if there's a variable that's being assigned throughout a method and we're lifting it to the other method, we need to declare it nullable if _any assignment to it_ could be nullable.

**Comment by jasonmalinowski** [comment]
Fixed by #37851.
