### ISSUE TITLE
PeekDefinition doesn't seem to work with nullability

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#30326]
When I invoked PeekDefinition (`alt+F12`) on a simple method, the inline popup appeared, but not contents got displayed (only a spinner animation).

![peek-definition](https://user-images.githubusercontent.com/12466233/46498832-5dc4b700-c7d3-11e8-84f1-769b09e5e117.gif)

FYI @dpoeschl

**Comment by jasonmalinowski** [comment]
I'm guessing this may be explained by #38002 -- if @jcouv was originally running a debug build Peek would potentially have just been broken. With that fix Peek seems to work, but we'll still have to investigate further.

**Comment by jcouv** [comment]
I was likely running a debug build (this was before the feature was in internal preview builds), so I'm fine to close this with your fix.

**Comment by jasonmalinowski** [comment]
Closing this then as not repro; I wouldn't have had another explanation why it wouldn't have worked than that.
