### ISSUE TITLE
MetadataAsSource isn't aware of nullability

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#30327]
The output from MetadataAsSource is lacking nullability annotations (`?`).
The `[Nullable]` attribute is displayed, instead of the `?` in the proper location(s).

![image](https://user-images.githubusercontent.com/12466233/46499305-9022e400-c7d4-11e8-9298-b0f49d681304.png)

Note: we need to display `#nullable enable/disable` which can be tricky

FYI @dpoeschl

**Comment by jasonmalinowski** [comment]
@jcouv @333fred So adding the ?s back is easy enough, but what's the plan for the attribute? I had _thought_ that generally the compiler took a tact that attributes that were processed by the compiler and reflected in the symbol API were dropped so things round tripped better, but it looks like we also spit the [Dynamic] attribute so maybe that's not the case. Any other recollections of how we represented things like this in the symbol API?

(I might be confusing this with the "special" attributes that don't become attributes but rather special bits in metadata, I don't recall.)

**Comment by RikkiGibson** [comment]
@jasonmalinowski Certain special attributes get "filtered out" by the compiler when you call e.g. `PEMethodSymbol.GetAttributes()`.

See this helper method used to implement `PEMethodSymbol.GetAttributes()`:
https://github.com/dotnet/roslyn/blob/f0c9a94f883c01dca80d424f08ff771bc6b6c932/src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs#L408

It seems like there are some other compiler-aware special attributes that don't get filtered out in MetadataAsSource. I think NullableAttribute should get filtered out for method, property, field, event, and parameter symbols in order to be a "best effort" at replicating the original source member signatures.

**Comment by jasonmalinowski** [comment]
Yeah, I see we don't filter out dynamic either; I wasn't sure what the intended compiler design is here. It's not hard for us to filter on the IDE side of things and I don't mind doing it....I just didn't recall if it was the compiler's job to do it in the first place and we wanted to keep it consistent.

**Comment by jcouv** [comment]
My take is that we shouldn't show `[Nullable(...)]` in metadata-as-source, only annotations because we have actual language syntax to represent them (although oblivious vs. not-annotated is a bit tricky/verbose).
In my mind `[Dynamic]` should also be filtered out. Not sure why it wasn't.

**Comment by jasonmalinowski** [comment]
And yes, it absolutely should be filtered out; I was surprised to see the `[Dynamic]` issue and wasn't sure if that was an oversight or something got broken.

**Comment by jasonmalinowski** [comment]
@jcouv Did some filtering ultimately get done in the compiler layer? I'm seeing some bugs fixed I didn't expect to see fixed.

**Comment by jasonmalinowski** [comment]
Ah I think I see what happened: I had some scenarios where NullableAttributes weren't be applied because NullableContextAttributes were, and we were incorrectly dropping those.

**Comment by jasonmalinowski** [comment]
(well incorrectly in the sense of "we seem to be dropping attributes of all kinds, including NullableContextAttributes")

**Comment by jasonmalinowski** [comment]
Where this is now:

We correctly spit ? in the various places, but we don't spit anything to give you a good hint of whether the original source was a #nullable enable or #nullable disable context. We need to handle things like that for other scenarios as well, so this will still need updating accordingly. We also still spit the attributes as well which is annoying but something we'll be cleaning up in 16.4.

**Comment by CyrusNajmabadi** [comment]
Where did we land on this @RikkiGibson @jcouv @jasonmalinowski ?  Is compiler supposed to strip this from teh API (that would be my preference), or will the attributes be there, and the consumers need to ignore them because they're redundant?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi I don't think we decided; until somebody wanted to actually do the much more complicated bit of sticking the `#nullable enable` things everywhere this is just on the backlog.

**Comment by RikkiGibson** [comment]
I'm honestly not sure. If we strip the NullableAttribute and just ensure that metadata type symbols have the correct nullable annotations, we get a lot of the way there for showing when types are **nullable**. But if we also strip the NullableContextAttribute for consistency, I don't see how MetadataAsSource will be able to insert `#nullable enable` directives in the appropriate spots to show whentypes are **non-nullable**.

Is there some kind of tag that could be placed on the syntax that would indicate the equivalent to "this node is in a `#nullable enable` context`? Then MetadataAsSource could keep a stack of nullable contexts as it looks through the declaration tree.

**Comment by CyrusNajmabadi** [comment]
Ok, talked to @RikkiGibson offline about this.  There should be enough information in the type-symbols for what we're generating to be able to figure this out.   Similar to how we have to look at the types to know if we have to add the `unsafe` modifier, since htat's not actually in a symbol.
