### ISSUE TITLE
UseLocalFunction isn't aware of nullability

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#30322]
![image](https://user-images.githubusercontent.com/12466233/46498119-5ef4e480-c7d1-11e8-8050-c237235b9a43.png)

FYI @dpoeschl

**Comment by jasonmalinowski** [comment]
Still reproduces even after our current set of fixes.

**Comment by jasonmalinowski** [comment]
Oops I just fixed this.

**Comment by jasonmalinowski** [comment]
(We still need to add tests)
