### ISSUE TITLE
Links from Error List et all should not open in VS

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#3033]
We should not be opening links from the Error List, Light Bulb previews, or Solution Explorer using the in-VS browser. Instead, we should open these links using the system browser via `IVsUIShellOpenDocument.OpenStandardPreviewer()` or `Microsoft.VisualStudio.Shell.VsShellUtilties.OpenSystemBrowser()`.

**Comment by artl93** [comment]
This will let you address the issue that the built-in browser is forever stuck in IE7 quirks mode.

**Comment by heejaechang** [comment]
done

**Comment by tmeschter** [comment]
Fix verified.
