### ISSUE TITLE
Passing null into (CSharp|VisualBasic)CommandLineParser.Parse as a base directory gives invalid key paths

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#30349]
If you pass in null as a base directory to our CommandLineParsers.Parse, they add that null into the KeyFileSearchPaths (which is invalid). It's unclear to me if that's a bug (and it shouldn't add them), or I shouldn't be calling with null in the first place.

**Comment by jaredpar** [comment]
The code base generally seems to explicitly support `null` as a valid value for `baseDirectory` in the called functions.  For example it eventually gets passed to `ResloveRelativePath` which explicitly allows `null`. Hence the bug seems to be unconditionally adding it to `KeyFileSearchPaths`.
