### ISSUE TITLE
Msbuild workspace fails to load projects properly when running older tasks.

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#3034]
msbuild.exe and devenv.exe use redirects in config files so that msbuild tasks built against older versions of msbuild API can load & run in the process.  In order to get any app that uses msbuild API or roslyn's msbuild workspace to function correctly, the same redirects must exist in the users app's config file too.

This is an obscure and non-obvious solution.  We should do better.

We can make MSBuildWorkspace solve this problem for the user by processing msbuild within an app domain that has the proper redirect assigned by msbuild workspace automatically.

**Comment by Pilchie** [comment]
Putting in 1.0 for consideration.

**Comment by Pilchie** [comment]
@mattwar Are you still thinking about doing anything here?

**Comment by mattwar** [comment]
Nope.
