### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp throw an System.IO.FileNotFoundException when anything from the namespace is called

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30358]
Visual Studio 15.8.2

Steps:
Create new Solution: TestSln
Create a project: Console (.net framework 4.7.2)
Create a project: Library (.net standard 2.0)
Console -&gt; Add Reference -&gt; Library
Library -&gt; Install NuGet package 'Microsoft.CodeAnalysis.CSharp' 2.9.0

Library -&gt; Class1.cs -&gt;
&quot;using System;

namespace Library
{
    public static class TestClass
    {
        public static void TestMethod()
        {
            Microsoft.CodeAnalysis.CSharp.LanguageVersion version = Microsoft.CodeAnalysis.CSharp.LanguageVersion.CSharp1;
        }
    }
}&quot;

Console -&gt; Program.cs -&gt;
&quot;using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Console
{
    class Program
    {
        static void Main( string[] args )
        {
            Library.TestClass.TestMethod();
        }
    }
}&quot;

Then I receive when I start Console
&quot;System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'&quot;

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/325337/microsoftcodeanalysiscsharp-throw-an-systemiofilen.html
VSTS ticketId: 674733_

**Comment by jinujoseph** [comment]
Related [here](https://developercommunity.visualstudio.com/content/problem/336527/microsoftcodeanalysissharp-version-290-cannot-find.html)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of prism hits.
