### ISSUE TITLE
publish fail on vs2015 generation (visual itself and tfs with a vs2015 agent) on compilers version > 2.4

### ISSUE THREAD

**Issue by toasteur** [dotnet/roslyn#30367]
**Version Used**: 
v2.8.2, v2.9.0
**Steps to Reproduce**:

1. create a new web application in vs2015 (i tried webform or mvc, same behavior)
2. update compilers nuget to last versions (Microsoft.CodeDom.Providers.DotNetCompilerPlatform and Microsoft.Net.Compilers)
3. try to publish the website to webdeploy package

**Expected Behavior**:
build succeed and publish succeed.
**Actual Behavior**:
build succeed and publish fail with no message whatsoever.

changing the Microsoft.Net.Compilers to 2.4 and restarting visual studio resolve the problem, publish works again.
vs2015 was used as an exemple, since i use vs2017 for development but tfs has a vs2015 agent (with msbuild 14 which would be more relevant since compilation is supposed to be independant by using nuget compilers?)
anyway, the build/publish on this tfs has exactly the same behavior as by using vs2015.

for reference, this thread helped me resolve my problem:
https://stackoverflow.com/questions/47951177/can-not-publish-project-into-file-system

**Comment by jaredpar** [comment]
Thanks for taking the time to report this. This looks like an issue in the DotNetCompilerPlatform package hence the issue should be filed at https://github.com/aspnet/RoslynCodeDomProvider
