### ISSUE TITLE
IDE0051 should not be reported for certain methods

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#30377]
In ASP.NET web app `Application_Start` is marked as unused:

![image](https://user-images.githubusercontent.com/41759/46624509-d4b8c300-cae5-11e8-8c0a-4b1df4d2bec3.png)

**Comment by CyrusNajmabadi** [comment]
What designates this function as something used by ASP?  Is it simply convention?

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/31036
