### ISSUE TITLE
Add 'Current Member' scope for fix-all code action

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#30375]
Currently it's not possible to apply a fix only to the **current member's block**,

![image](https://user-images.githubusercontent.com/3105979/46621573-aa422680-cb34-11e8-8f28-2fccf53e93eb.png)

It's useful when you want to modify a limited portion of the code rather than the whole "Document".

**Comment by alrz** [comment]
With this, the "preview" dialog would be less useful (actually I never use it because I can always review changes from git diff). Would be nice to make "Preview changes" here a checkbox so we can opt-out.

**Comment by dpoeschl** [comment]
Design Meeting Notes:
- Fixers will be opted in by default if they support the Document FixAllScope. They can opt out via some API.
- The engine will fix all of the diagnostics in the relevant member and apply those changes. We'd also somehow like to warn/alert the user if the fixes for that set of diagnostics contains changes outside the member.

**Comment by alrz** [comment]
On the UI: I think we should turn this into a menu because:

- Currently you would have to use mouse to select the scope
- If we mention the member name the text gets kinda long
- There could be other scopes that we want to add, like `current class`

**Comment by alrz** [comment]
White we're at it, consider a "Folder" scope as well.

**Comment by alrz** [comment]
Implemented in 17.3p1 (except for the "Folder" scope)
