### ISSUE TITLE
Object Browser does not display different icons for static versus non-static members

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#30370]
_From @verelpode on October 4, 2018 16:45_

Hello, the Object Browser window is wonderfully useful (I use it every day), but it would be better if it displayed different icons for **static** members (including static methods, static properties, etc).  See screenshots following.

The problem is that currently we're forced to individually click on each member before we can see whether it is static or non-static.  A lot of clicks could be avoided if we could see at a glance which members are static -- an overview, simply by looking at the icons and noticing that static members have a different icon -- that would be great.

When you click the cog icon, you can tick or untick **"Show Protected Members"** etc, but surprisingly this menu does not have the option to filter by static members.  I suggest the addition of 2 new menu items there:
* **"Show Per-Instance (Non-Static) Members"**
* **"Show Non-Instance (Static) Members"**

![object browser - no icons for static members](https://user-images.githubusercontent.com/32857007/46489427-a7c69080-c805-11e8-8c68-79ece442510d.png)

![object browser filter options](https://user-images.githubusercontent.com/32857007/46489438-ae550800-c805-11e8-8e34-f00a3a89fb7c.png)

_Copied from original issue: dotnet/project-system#4084_

**Comment by CyrusNajmabadi** [comment]
Object browser is in maintenance mode and is getting no further work.  Any changes here would need to come through some new system (which would effectively be a rewrite).
