### ISSUE TITLE
Member selection generates Equals without dialog and without respecting defaults

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#30396]
VS 15.8.6

It's not useful to me (or ideal for anyone) to put everything in `Equals(object)` and skip generating the typed `Equals`. Either the fix should respect the last used defaults in the dialog and generate both (and equality operators), or the fix should simply show the dialog.

![nodialog](https://user-images.githubusercontent.com/8040367/46677664-0f3b6200-cbb1-11e8-83a9-c7d2f93ffab5.gif)

**Comment by CyrusNajmabadi** [comment]
I don't believe either of the above are good choices.  A more appropriate fix would be to offer "Generate 'Equals'..." as a third option, which then opens the dialog with the right members selected based on the user's selection.

**Comment by sharwell** [comment]
We are going to revisit this in a later meeting. My alternative proposal is to update the refactoring behavior for a value type `T` to automatically include all of the following:

1. Override `object.Equals(object)` (already done)
2. Override `object.GetHashCode()` (already done)
3. Define `T.Equals(T)`
4. Update the default implementation of `object.Equals(object)` to delegate to `T.Equals(T)`
5. Define `T.operator ==(T, T)` and `T.operator !=(T, T)`

While it would be possible to make this an option, the above is a more efficient overall pattern than simply relying on the same behavior being provided by `System.ValueType`.

**Comment by jasonmalinowski** [comment]
The decision in the design meeting was that _for Value Types_ we should do as @sharwell proposes above: we should generate the strongly typed Equals overload and operator overloads as well.

**Comment by Youssef1313** [comment]
@jinujoseph Can you close this? It was fixed by https://github.com/dotnet/roslyn/pull/42260, but GitHub didn't close it since the PR  was targeting a release branch not `master`.
