### ISSUE TITLE
(VB) Shorter Case Clause in Scanner

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#304]
[This case clause](
https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Scanner/Scanner.vb#L274) could made similar by doing  
```VB.net
Case "a"c To "z"c, "A"c To "Z"c, "'"c, "_"c
    EatThroughLine() 
    condLineStart = _lineBufferOffset 
    Continue While 
```
What impact do the use the `To` form have?

**Comment by gafter** [comment]
It causes the code generator to emit an IL switch rather than an IL range test.

**Comment by AnthonyDGreen** [comment]
Hey Adam,

I did some comparisons of Select Case block using both styles and I think this is an IL optimization. As written we emit a single 'switch' instruction in IL where as when written with the proposed style we emit something closer to a set of If/ElseIf/Else statement - several checks are done sequentially to narrow down which branch to enter. The former yields better performance, which is critical for the scanner. It would be interesting if we could improve our code generation here to still emit the optimal code while allowing users to write idiomatic VB code. If and only if such an optimization were to be done would we consider making such a change.

Regards,

**-ADG**
