### ISSUE TITLE
Expose IsManagedType on INameTypeSymbol

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#30427]
Useful information that I don't know how to dig out using existing API.

**Comment by JohanLarsson** [comment]
Use case is in https://github.com/DotNetAnalyzers/ReflectionAnalyzers where we want to check:

```cs
typeof(C<>).MakeGenericType(typeof(Foo));

class C<T> where T : unmanaged
{
}
```

**Comment by CyrusNajmabadi** [comment]
Same comment as your other bug.  What is the analyzer trying to do, and what information is the new API needed for.  THanks!

**Comment by JohanLarsson** [comment]
The goal of the analyzer is to produce a warning if `MakeGenericType` is called with types that do not satisfy the constraints on the type parameter.
It would give us a chance to find & fix issues that would be runtime errors at compiletime.

**Comment by CyrusNajmabadi** [comment]
Definitely seems like something reasonable to expose. Or perhaps .IsUnamanaged.   @gafter Do you have any thoughts around exposing this? Any concerns?  It seems like a pretty simple and basic API that already exists on TypeSymbol.  This woudl just be exposing it through ITypeSymbol.  Thanks!

**Comment by gafter** [comment]
I can't think of any problems exposing it.

**Comment by jaredpar** [comment]
Yeah we really should expose that member. Especially now that the `unmanaged` constraint exists.
