### ISSUE TITLE
Error List re-orders and scrolls after selecting one entry

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#30423]
I'm fixing a number of build errors following a merge. I'm looking at the error list, scrolling to the top and double-clicking on the first entry.

I expect the list to stay put, as I will want to fix the second entry next.
The errors at the bottom of the list are not interesting to me, as they are just "Metadata file could not be found" produced by dependent projects (they are not the root cause of the build failure).

Instead, the item I selected jumps to the bottom of the list and the list scrolls. That means that I need to scroll all the way back to the top once I'm done with that error and I'm ready to proceed to the second error.

Note: this is with 15.9 preview1.

![error-list-jumps](https://user-images.githubusercontent.com/12466233/46711079-931c3b00-cbff-11e8-90cf-1426971caf18.gif)

**Comment by CyrusNajmabadi** [comment]
This would go to platform/editor.  Letting @kayle  know.
