### ISSUE TITLE
Improve Go To Last Edit Location

### ISSUE THREAD

**Issue by Ifn00b** [dotnet/roslyn#30428]
**Version Used**:  15.8.6

**Steps to Reproduce**: ç

Execute command  "Go To Last Edit Location"

**Expected Behavior**:
if i execute multiple time the command  "Go To Last Edit Location" should navigate over all historical.
(How work "Navigate Backward")

**Actual Behavior**:
It only supports one level of history

**Comment by jinujoseph** [comment]
cc @olegtk @gundermanc

**Comment by olegtk** [comment]
please route to the editor as a suggestion. thanks!

**Comment by jinujoseph** [comment]
[done](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/704173)
