### ISSUE TITLE
EvaluationContext.CompileExpression used in expression compiler can't override language version

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#30436]
Right now most of the expression compiler tests use EvalationContext.CompileExpression to run tests simulating the EE. It appears that this method uses a hardcoded parse options value with a language version of `Latest`, which is problematic for C# 8.0 features since the `Latest` language version is actually C# 7.3.

It's possible this may even apply to the EE product, since this helper may also be used in the shipping EE.

**Comment by jinujoseph** [comment]
cc @tmat
