### ISSUE TITLE
DiagnosticIncrementalAnalyzer allocates large amounts of memory just finding/figuring out analyzers

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#30449]
In the SDK version of https://github.com/dotnet/project-system/issues/4078, https://developercommunity.visualstudio.com/content/problem/354199/memory-consumption-with-sdk-projects.html, the following is responsible for ~12% of the trace (330 MB). GC is at 18.9% of the total CPU.

![image](https://user-images.githubusercontent.com/1103906/46785460-89204680-cd7d-11e8-8921-f2487c6a86f5.png)

Digging in - there seems to be lots of overhead in just getting figuring out what analyzers to run, for example, there's 40 MB in just creating type names:

![image](https://user-images.githubusercontent.com/1103906/46785537-bec52f80-cd7d-11e8-9e28-7381974ccb10.png)

**Comment by sharwell** [comment]
> ~12% of the trace (330 MB). GC is at 18.9% of the total CPU

Unless this is a *very* short trace or the system is under extreme memory pressure, these numbers are not consistent with my general expectations. They suggest the trace may be missing data or incorrectly presenting results somehow.

**Comment by sharwell** [comment]
This should be an easy fix. We don't need to construct the type name until after we determine the set of supported languages is not empty. Currently, all type names in all assemblies listed as analyzers get expanded. After the change, only type names for types registered as analyzers would be expanded.

**Comment by davkean** [comment]
Bear in mind that type name is just one case that I pulled, I did not dig further into the other cases.

**Comment by heejaechang** [comment]
this part shouldn't be different between SDK vs classic projects so the big difference should come from different part though?

but regardless, any reduction of allocations is good if possible +1!

**Comment by iharwell** [comment]
I'll take a shot at the type name issue.

**Comment by davkean** [comment]
@sharwell Can you please look at the trace to look at the other data being produced? The type name was just one example.

**Comment by sharwell** [comment]
@davkean I didn't see any other low hanging fruit on this path which would result in an observable improvement.

**Comment by davkean** [comment]
So analyzers allocating 12% of opening a project is expected?

**Comment by sharwell** [comment]
@davkean The last time I measured the analyzer path, the overall allocations were around 50-60GiB of data. The 40MiB improvement was kept for its simplicity, but generally we'd be looking at a target of 1GiB for a small improvement here. Also, keep in mind the trace data was only a snapshot, so it's not possible to make any claim regarding the overall percentage of solution load. If you are interested in capturing a larger snapshot to make further improvements to the scenario, I would recommend starting with the GC Only scenario on [this page](https://github.com/dotnet/roslyn/wiki/Recording-performance-traces-with-PerfView).
