### ISSUE TITLE
Promote constant to field

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#30466]
It would be nice to have a refactoring to move a local constant into a field. It would be available on the name of the constant in the declaration, and possibly on the const keyword as well.

Example:
```c#
class C
{
    void M()
    {
        const int value = 5;
    }
}
```
converts into:
```c#
class C
{
    const int value = 5;
    void M()
    {
    }
}
```

**Comment by CyrusNajmabadi** [comment]
This seems less helpful to me.  it seems like mostly the equiv of cut/paste.  i'm not opposed.  but marginal benefit seems low.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
