### ISSUE TITLE
[Feature Request] Inline constant

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#30464]
I'd like a refactoring to replace a binary expression or an identifier name whose value is a constant with its constant value. Examples:

1. **On binary operators**
```c#
class C
{
    const int value = 5;

    void M()
    {
        var result = value + 7;
    }
}
```
after applying the refactoring with cursor on the `+` the result would be:
```c#
class C
{
    const int value = 5;

    void M()
    {
        var result = 12;
    }
}
```

second example:
```c#
class C
{
    const string hello = "Hello ";

    void M()
    {
        const string result = hello + "world";
    }
}
```
results in
```c#
class C
{
    const string hello = "Hello ";

    void M()
    {
        const string result = "Hello world";
    }
}
```

2. **On identifiers**

```c#
class C
{
    const int value = 12;

    void M()
    {
        var result = value;
    }
}
```
after applying the refactoring with cursor inside `value`:
```c#
class C
{
    const int value = 12;

    void M()
    {
        var result = 12;
    }
}
```

**Comment by Neme12** [comment]
@CyrusNajmabadi Probably, but it's harder to enumerate all the cases and spans in which the refactoring would be allowed.

**Comment by sharwell** [comment]
This is an interesting idea for sure. It seems related to other refactorings we have, such as Inline Variable. We'll certainly want to make sure the refactoring cooperates with the Extract Local Variable refactoring since they are triggered in many of the same locations.

**Comment by Neme12** [comment]
I don't think this would be in conflict with inline variable in particular in any contexts, because inline variable is always only offered at the declaration, whereas this one would be offered at the expression.

**Comment by sharwell** [comment]
> I don't think this would be in conflict with Inline Variable in particular in any contexts

Agreed. I'm using Inline Variable as an example of why this feature request might be likely to be accepted.

**Comment by Neme12** [comment]
It's true that there seems to be too many items in the list:
![image](https://user-images.githubusercontent.com/11444821/46831075-a4ea1380-cda2-11e8-8749-5765f6a86c13.png)

**Comment by CyrusNajmabadi** [comment]
@Neme12 teh main problem there is that 'intro var' doesn't follow hte behavior of other refactorings. it should place those items in a nested code action.  That way, if there few items, it just shows you all of them in the top level list (since we auto-inline in that case). But if there are many, we jsut show a single top level "Introduce constant" item, with the others nested.

**Comment by CyrusNajmabadi** [comment]
For example, like what we do here:

![image](https://user-images.githubusercontent.com/4564579/46831340-09cc4c00-cd58-11e8-9033-0d0b607645c5.png)

**Comment by CyrusNajmabadi** [comment]
@Neme12 I opened https://github.com/dotnet/roslyn/pull/30469 to help out here.  Now, if we're inlining the constant, we'll be less likely to have that huge honking list :)

**Comment by jcouv** [comment]
Fixed in preview2

**Comment by CyrusNajmabadi** [comment]
@Neme12 This should be better now.  Looking forward to your fix!

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
