### ISSUE TITLE
Remove use of workspaces layer by Formatting Analyzer during compilation

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#30472]
The code style layer should not embed workspaces assemblies in the NuGet package or load them during compilation scenarios.

> This feels fairly hacky. We should be tracking the removal of this with a bug link.
> 
> ---
> In reply to: [222536172](https://github.com/dotnet/roslyn/pull/28873#discussion_r222536172) [](ancestors = 222536172)
> 

_Originally posted by @jaredpar in https://github.com/dotnet/roslyn/timeline_

**Comment by Neme12** [comment]
Why not? What's wrong with "code style" analyzers using features from workspaces?

**Comment by sharwell** [comment]
@Neme12 The workspaces layer is not available during compilation. Without elaborate workarounds involving manual assembly resolvers (undesirable all around), analyzers referencing the workspace layer will only work inside the IDE and not from command line compilation scenarios.

**Comment by Neme12** [comment]
Sorry, I don't understand. If the code styles layer can be made available during compilation, why not workspaces?

**Comment by sharwell** [comment]
The workspaces layer is large and has many dependencies not present in the compiler layer. It is omitted from compilation by design as a matter of principle (performance).
