### ISSUE TITLE
editorconfig ignored for format document/selection on C# files in Makefile project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30500]
* First, make sure Tools -&gt; Options -&gt; Text Editor -&gt; C# -&gt; Tabs is set to &quot;Insert spaces&quot; (the default)

* Create a Makefile project, add a C# file named Test.cs, add some valid C# code. All indentation should be spaces.

* Add a .editorconfig file in the source (or parent) directory with the following content:

root = true

[*]
indent_style = tab

* Go back to Test.cs and format document (Ctrl + K, Ctrl + D).

Note that the document doesn't get formatted to use tabs as expected. However, pressing Tab does indeed insert tabs.

This is different from when the project is a proper C# project. Seems to not work for Makefile projects. This is a problem since Unreal Engine 4 projects are all Makefile, and they include both C# and C++ files under them (the *.build.cs and *.target.cs files used for their build system).

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/352988/editorconfig-ignored-for-format-documentselection.html
VSTS ticketId: 701018_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
We are not doing any investment in makefile projects for c#.
