### ISSUE TITLE
The execution Restore.cmd has an exception

### ISSUE THREAD

**Issue by wangchaoyuwangchaoyu** [dotnet/roslyn#30515]
**Version Used*Roslyn15.8 VS2017*: 

**Steps to Reproduce**:

1. The following figure:MSBUILD : error MSB1008: Only one project can be specified.
2. 
![2](https://user-images.githubusercontent.com/37067106/46933129-4dd78d80-d085-11e8-8d28-8778d3e76bb8.jpg)

3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by jaredpar** [comment]
Spaces are indeed not supported as a part of our enlistment paths. That's one of the restrictions listed in #20929
