### ISSUE TITLE
Applying suggested changes "IDE0018 Variable declaration can be inlined" generates non-compilable code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30518]
REPRODUCTION STEPS

 - latest Visual Studio 2017 version
 - create new Visual Studio Project of type &quot;Console App (.NET Framework)&quot; (.NET Framework 4.7)
 - paste the following code into the generated Main method body (Program.cs attached)

            var actionArray = new[] 
            {
                new Action(() =>
                {
                    var someValue = "2";
                    int valueAsInt; // suggested changes in this line
                    if (int.TryParse(someValue, out valueAsInt))
                    {
                        Console.WriteLine(valueAsInt);
                    }
                })
            };

 - apply suggested changes &quot;IDE0018 Variable declaration can be inlined&quot; in the line &quot;int valueAsInt;&quot;
 - the line below is changed to &quot;if (int.TryParse(someValue, out intvalueAsInt))&quot; which will produce a build error
 - the line should be &quot;if (int.TryParse(someValue, out int valueAsInt))&quot;

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/341937/applying-suggested-changes-ide0018-variable-declar.html
VSTS ticketId: 690311_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_

Jinu Joseph [MSFT] solved on 10/14/2018, 05:04 PM (8 hours ago), 0 votes: <p>Thank you for your feedback! This issue appears to be identical to  <a target='_blank' href="https://github.com/dotnet/roslyn/issues/17743">https://github.com/dotnet/roslyn/issues/17743</a>  We recommend that you vote on and follow the earlier reported issue for updates and fix notifications.</p>

**Comment by ryzngard** [comment]
I can take this one
