### ISSUE TITLE
When using "Implement Interface" to generated methods, VS adds them inside #region

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30512]
When using &quot;Implement Interface&quot; to generated methods unimplemented methods. Then newly generted methods are generated inside of a #region .... #endregion block.

Visual studio should not append the generated methods inside existing region block. It should insert them outsize a region block.

The reason I recoommed this is if there are multiple collapsed regions in a class, it is hard to know that the methods were generate and where.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/353035/when-using-implement-interface-to-generated-method.html
VSTS ticketId: 701063_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by dnxit** [comment]
what is the solution ??? even after 2 years nothing

it mess up all the existing code with new definitions by sorting functions putting in all regions

**Comment by CyrusNajmabadi** [comment]
@dnxit PRs welcome :)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback on this.
