### ISSUE TITLE
Document format problem with operators ++/--

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30513]
Code to format: var x = val1+++++val2;

Corect result: var x = val1++ + ++val2;
VS17 result: var x = val1++++ + val2;

Also if we give code: var x = val1+++val2;
VS17 format it as var x = val1++ + val2;
But there is another correct formating:
var x = val1 + ++val2;

Here we have ambiguity between these two formatings, as both ar valid. But the final code produces different results, so i think that VS must inform the user.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/353655/document-format-problem-with-operators.html
VSTS ticketId: 701563_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
> Also if we give code: var x = val1+++val2;
VS17 format it as var x = val1++ + val2;
But there is another correct formating:
var x = val1 + ++val2;

The second formatting is not correct, as it would change semantics.  

> Here we have ambiguity between these two formatings, as both ar valid. 

The is not the case.  If you format as `val1 + ++val2;` this will break the meaning of the code which is currently parsed as if it was `val1++ + val2`

**Comment by CyrusNajmabadi** [comment]
> Corect result: var x = val1++ + ++val2;
VS17 result: var x = val1++++ + val2;

This is not correct.  As far as the compiler and language are concerned `v1+++++v2` is parsed as if you wrote to `((v1++)++)+v2`.  That needs to be preserved post formatting.  Here the formatter is doing the right thing.

**Comment by CyrusNajmabadi** [comment]
@jinujoseph This can be closed as by-design.  The formatter is respecting the language/compiler's view of what this code means.
