### ISSUE TITLE
Allow initializing property from constructors

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#30523]
Say you have this class:

```cs
public abstract class Foo
{
    public int SomePublicProperty { get; }

    protected Foo(int somePublicProperty)
    {
        SomePublicProperty = somePublicProperty;

        // Some manually-written constructor logic
    }
}
```

And it's time to add a protected property. The intuitive thing to do would be to write the property and Ctrl+. to initialize it from the constructor, but Roslyn doesn't seem to have a refactoring for this. You either have to delete the existing constructor and generate from scratch, losing custom logic and exception messages, or you have to start by finding and navigating to an existing constructor and writing the parameter and generating a property. Then you have to navigate to the generated property and fix it by making it `protected` among other customizations you may have had in mind from the beginning, such as XML documentation or attributes or setter existence and visibility.

I would like to be allowed to start by writing out the higher-information property declaration and generating the constructor parameter in the correct position based on that instead of vice versa.

If there are multiple constructors, ones that assign other properties or fields should also assign the new one. Constructors that delegate field/property initialization to another constructor should simply pass the parameter value along to the chained `this` call.

**Comment by sharwell** [comment]
It seems reasonable to support this feature via the existing **Add Parameter** refactoring. Edge cases related to existing usages are already covered by the design of that refactoring, so I'll focus on items unique to this case:

* If more than one constructor exists, it's not clear whether one should be updated or all should be updated
* The existing constructor(s) might contain parameters that do not correspond to an existing field or auto-property by matching names
    * The unmatched parameter might be assigned to a field or auto-property with a different name
    * The unmatched parameter might be passed through to a base class constructor
    * The unmatched parameter might be used in some other way
* The order of constructor parameters might not match the order of fields and/or auto-properties
* The order of constructor parameters may vary between constructors, which under some possible designs could result in the new parameter being placed in different positions for different constructors

**Comment by CyrusNajmabadi** [comment]
This is already supported:

![image](https://user-images.githubusercontent.com/4564579/76916149-d6f78300-687c-11ea-8ce2-426051ae9bfd.png)

We also support the case of multiple constructors:

![image](https://user-images.githubusercontent.com/4564579/76916195-fe4e5000-687c-11ea-8a44-19c915eadace.png)
