### ISSUE TITLE
Issue with object initializers and csharp_new_line_before_open_brace in editorconfig

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30529]
Hi!

I'm using the editorconfig file to fine-tune the coding style settings across multiple visual studio instances. Specifically, I want to configure the placement of the open brace. The csharp_new_line_before_open_brace setting gives me some headache:

When I set

csharp_new_line_before_open_brace = all

I get new lines for Object Initializers like so:

            var foo = new Foo
            {
                Name = &quot;Hello World&quot;,
                Id = 0,
            };

When I explicitly specify the individual settings, (which I want, because I'd like to disable specific things like the new line for control statements) like so:

csharp_new_line_before_open_brace = accessors, anonymous_methods, anonymous_types, control_blocks, events, indexers, lambdas, local_functions, methods, object_collection_array_initializers, properties, types

the code formatter produces this (the opening brace is _not_ (!) placed on new line):

            var foo = new Foo {
                Name = &quot;Hello World&quot;,
                Id = 0,
            };

Note, I enabled all available values according to https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017#newline).

So, AFAICT this should be the same as &quot;all&quot;.

Am I missing something, or is this an issue within VS?

Thanks, david

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/350663/issue-with-object-initializers-and-csharp-new-line.html
VSTS ticketId: 699427_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
🐛 The underlying problems is the following setting is misspelled.

https://github.com/dotnet/roslyn/blob/14e0068d9d529ade86c0ed1544477a221809d0e0/src/Workspaces/CSharpTest/Formatting/EditorConfigOptionParserTests.cs#L94

We need to update the code so the correct spelling is supported, and also preserve support for the original value.

**Comment by Rumpel78** [comment]
I will pick this up and fix it, if it's ok for you?

**Comment by sharwell** [comment]
@Rumpel78 sure thing!

**Comment by jaroslav-rfe** [comment]
still happening in visual studio professional 2017 15.9.7

**Comment by sharwell** [comment]
@jaroslav-rfe This issue was fixed for the first release of Visual Studio 2019.
