### ISSUE TITLE
Compiler crash when compiling switch (int? ?? await Task<int>)

### ISSUE THREAD

**Issue by marektq** [dotnet/roslyn#30521]
Compiler crashes (csc.exe invokes FailFast) when compiling the below.

What's very strange, this does not happen if int is replaced with double (and return 1.0; in Get method below). Does not happen with double. Happens with other types (tried with int-based enum)

**Version Used**: 
master Oct 13 2018. Observed this also in stock VS 2017 where it crashes csc.exe.

**Steps to Reproduce**:

1. compile the below
``` c#
    //fails with int, does not fail with double
    using System;
    using System.Threading.Tasks;
    public class C {
        
        public async Task<int> Get() {
            return 1;
        }
        
        public async Task FAILS(int? val) {
                switch (val ?? await Get())
                { 
                    case 1:
                    default:
                        throw new NotImplementedException("This crashes csc.exe");
                }
            }
    
    }
```

you can also try this online: https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+B6bAzCASwBsoACAd0JgAszCA7GAWACg2ABABjI4EYA3Jx78ArENYcAzLwBMZAMJkA3mzLqyajdN4AOXgDYAPIxgA+MgHE4MABQBKFVo3aA7GUHOyAXy9edHPocBmQAYgCCAJIAMgDKtqYA/GQAbhDEjqqsLjkaUFQwAMZ0tmnEZInJHACcVjYO9l656sqa2c0dhdBwHiBNHRoocAQArsQwfe0DA7QIAPYUZAxwiwByczCRYAAOxHBgcExwKACiAB6FcNswhHMMtgBEACo0hOSFCNA0cO9QhQB0cDOcAe9gk03UvimOShbG8QA==

this is the double version which does not crash: https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+B6bKD2cUABAHb4zEBmEAlgDbEDutMAFsQQK7D1wCEAWABQIgAIAGYmICMAbnFTZAVgXCxAZmkAmYgGFiAbxHFTxE2c3SAHNIBsAHm684APmIBxODAAUASiMLM0sAdmIZADoJNWCAXyDzYWCrMVsxO2IAMQBBAEkAGQBlH2c+AH5iADcIegDjJODG0ygWGABjDh9qxjKKsQBOT29/PwSm00NE8eniNug4cJAxmdMUOBouehglhpXp9gR8JjI4Y4A5ClywAAc+MDhSeBQAUQAPNrhrmFp8Uh8AIgAKmxaCQ2ghoGwiLMoG0InBXnB/n4Ynt4rtGuiRLEgA===

**Expected Behavior**:
No crash, compiles the code.

**Actual Behavior**:
``` none
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary. at System.Collections.Generic.Dictionary`2.get_Item(TKey key) at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.RecordVarWrite(LocalSymbol local) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Compilers\CSharp\Portable\CodeGen\Optimizer.cs:line 1859 
...
```

Crashes csc.exe.

**Comment by gafter** [comment]
I suspect this is a bug in our IL optimization pass.

**Comment by gafter** [comment]
Note that this bug exists in VS2017; I have not tested earlier versions.
