### ISSUE TITLE
Bail out from MakeFieldReadOnlyDiagnosticAnalyzer in presence of errors

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#30536]
See https://github.com/dotnet/roslyn/pull/30473#issuecomment-429469674 for details

**Comment by jinujoseph** [comment]
Lets get a policy for error handling documented in the design meeting and then move this back to small fixes

**Comment by sharwell** [comment]
The policy is: an IOperation-based analyzer which relies on semantic information for correct behavior should not be proposing modifications if the portion of the operation tree required to determine the outcome contains semantic errors.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
