### ISSUE TITLE
stackalloc initializers can have incorrect behavior when a large number of the outputs are explicitly zeroed

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#30535]
### Summary
A quick view of the issue can be seen by looking at: https://sharplab.io/#v2:EYLgHgbALANAJiA1AHwAIAYAEqCMBuAWAChjUBmTAQ2AGcAXAJ0oGM7MBXAOxsoDMBTbACZMAFX70AwgBtKNGsQDexTKuwVcEbFDES6OABTAAnnUEA3StPb8AlCrXKial5ksNMABwBKE9tLYAXkx6FgBrK2kAe2ZMEzMAbRwAXQdXTCd09Mtrfhg01wBfQmc1QoKC8mwcLVQdcXohI1MLKxt7UtVMrPcvXxp/IJC6cMiYuJaEoVTO126stRybfNmF9BWF4oLy2cqNGu1dejJmszc2uwL5116fPwDMYNDmCOlo2Pj+BLIZheuFpZ5AprDYLNTrYFlEouHYuPbVWr1PRQU6tXIdFz/RaUDx3AYPJ4jF5jD6TKC/LJY7IXUFgzAQ1ZZBl01TMrJbWY7QpAA

### Repro

Compile and look at the IL for the following code:

```csharp
public unsafe class TestClass
{
    public static void Test4(byte value)
    {
        var pResult = stackalloc byte[4]
        {
            value,
            0,
            0,
            0,
        };
    }
}
```

It produces IL similar to:
```il
.method public hidebysig static 
    void Test4 (
        uint8 'value'
    ) cil managed 
{
    // Method begins at RVA 0x2050
    // Code size 12 (0xc)
    .maxstack 4
    .locals init (
        [0] uint8*
    )

    IL_0000: nop
    IL_0001: ldc.i4.4
    IL_0002: conv.u
    IL_0003: localloc
    IL_0005: dup
    IL_0006: ldc.i4.0
    IL_0007: ldc.i4.4
    IL_0008: initblk
    IL_000a: stloc.0
    IL_000b: ret
}
```

### Expected Behavior

The generated IL should end up doing `pResult[0] = value`

### Actual Behavior

The generated IL only zeroes out `pResult` and never consumes arg 0

**Comment by tannergooding** [comment]
CC. @jaredpar

**Comment by jaredpar** [comment]
Yes this appears to be a duplicate.
