### ISSUE TITLE
make all IWorkspaceProjectContext methods async

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30533]
http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/CPS/IWorkspaceProjectContext.cs,bf5544f19d42a24f

right now, all Methods are sync, but we want to make those async so that we don't block any BG threads.

**Comment by CyrusNajmabadi** [comment]
Clsoing out.  We should drive this with known scenarios that have to be improved.
