### ISSUE TITLE
No Option to Disable C# Code Style

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30530]
In text editor &gt; c#-&gt; code style there is no option in severity column to disable specific check. Minimum severity is &quot;refactoring only&quot;. In my opinion, code are always recommendations to developers style checks IDE from authors and IDE MUST have to option to disable any of this check.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/346741/no-option-to-disable-c-code-style.html
VSTS ticketId: 694566_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
"refactoring only" means there's no severity.  You get no ellipses, warnings or errors when you set hte value to this.

**Comment by sharwell** [comment]
@CyrusNajmabadi is correct. This behavior has actually existed from the start of Visual Studio 2017. The severity (and behavior) previously listed as "None" was renamed to "Refactoring Only" to better reflect the behavior.

There are two ways to *completely* disable a code style rule for the project:
1. Starting with the 15.8 release, you can set the severity of the code style rule in .editorconfig to `none`
2. In 15.0 and newer, you can use a rule set file to set the severity of a diagnostic ID to **None**

In Visual Studio 2019, we are planning to have a way to disable diagnostics by ID in the .editorconfig file, which will provide additional options for shared code style.
