### ISSUE TITLE
First run experience tooltip for screwdrivers says "Light Bulb"

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#30547]
**Version Used**: 

16.0stg

**Steps to Reproduce**:

1. Open Visual Studio for the first time
2. Have some code that shows a screwdriver
3. Check the tooltip

**Expected Behavior**:

Tooltip should refer to the screwdriver as a screwdriver.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/754264/47047393-2d254a00-d1e3-11e8-919b-dfc6550d2cd5.png)

**Comment by CyrusNajmabadi** [comment]
Tagging @olegtk Can you move this over to the editor?

**Comment by Neme12** [comment]
Right. It should say "paint brushes" of course :smile:

**Comment by olegtk** [comment]
@jinujoseph please route to the editor. thanks!

**Comment by jinujoseph** [comment]
[Moved ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/707330)
