### ISSUE TITLE
Make nullable common type rules associative

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#30540]
See https://github.com/dotnet/csharplang/issues/1925#issuecomment-430340546 for details.

This change should be done after #29727 has been merged to minimize churn and because that PR implements the current LDM decision. It is a single line implementation change (plus probably lots of test changes). It would probably be worth adding a test corresponding to the test program in https://github.com/dotnet/csharplang/issues/1925#issuecomment-430340546 .

**Comment by jcouv** [comment]
@gafter I think you fixed this issue with PR https://github.com/dotnet/roslyn/pull/30990
Please clarify if there is something else to do, or close. Thanks

**Comment by gafter** [comment]
There are tests now that confirm that the rules for nullable annotations and nullable states are associative, commutative, and absorptive, as required for them to be lattices.
