### ISSUE TITLE
SemanticModel.AnalyzeDataFlow returns invalid states

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30548]
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp39
{
    class Program
    {
        void Method(out object test)
        {
            test = null;

            var a = test != null;
            [|if (a)
            {
                return;
            }

            if (A == a)
            {
                test = new object();
            }|]
        }
    }
}
```

for the span [| - |], SemanticModel.AnalyzeDataFlow returns the symbol "test"
in DataFlowsIn, but NOT in ReadInside which shouldn't happen.

**Comment by heejaechang** [comment]
skipped test added for compiler - SymbolInDataFlowInButNotInReadInside in RegionAnalysisTests.cs

**Comment by heejaechang** [comment]
related to https://github.com/dotnet/roslyn/issues/30538

**Comment by CyrusNajmabadi** [comment]
tagging @gafter 

> SemanticModel.AnalyzeDataFlow returns the symbol "test" in DataFlowsIn, but NOT in ReadInside which shouldn't happen.

How is the value 'read inside'?  It doesn't look 'read' in the example you provided.  

Note: teh docs for DataFlowsIn only says this:

```c#
        /// <summary>
        /// The set of local variables which are assigned a value outside a region
        /// that may be used inside the region.
        /// </summary>
        public abstract ImmutableArray<ISymbol> DataFlowsIn { get; }
```

It simply says that it is 'used' in the region.  Not read.  @gafter can you shed light on hte expectations here?

**Comment by gafter** [comment]
Expanding on what @agocke said, the variable is considered to flow into the region because the region relays the `out` variable to the caller through the `return` statement.

**Comment by agocke** [comment]
Ah I somehow totally missed the return statement. Yes, this is the correct behavior.
