### ISSUE TITLE
Handle task-like types in type inference

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#30559]
> :bulb: For task-like types (including `ValueTask<T>`), the type does not need to match `Task<T>`. For our purposes, we can treat it as the first generic argument of the type, or `void` if the type is not generic. It appears the original code did not handle these cases either, but considering the effort you put into eliminating the known bugs in this code it seems like something you may want to cover at the same time. 😄

_Originally posted by @sharwell in https://github.com/dotnet/roslyn/pull/30211_

> I am aware of this but I would prefer if this was fixed separately since it affects many other features as well, such as "use block body" and "introduce variable". In my opinion there should be one helper function to unwrap a task-like that they could all use.

_Originally posted by @Neme12 in https://github.com/dotnet/roslyn/pull/30211_

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
