### ISSUE TITLE
make extract method not to show info bar if it is called from code refactoring not from command handler

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30553]
currently extract method gets called automatically even though user didn't ask for it when there is a selection in the editor through code refactoring.

we should stop showing info bar when it is called from refactoring but only show it when it is called explicitly from command handler reducing noise.

**Comment by CyrusNajmabadi** [comment]
> we should stop showing info bar when it is called from refactoring 

Why do this?  

THe distinction isn't meaningful.  We shouldn't show goldbars unless we crash.  And we shouldn't have code that intentionally crashes by assuming information not in evidence.  Crashing a feature should only happen for things we didn't anticipate and thus we have buggy code.  For things we anticipate, we should either handle the cases, or silently log telemetry or a NFW if it's something we need to know more about.

We shouldn't gold-bar in that case, because that's effectively disables the feature for the user.  And there's no need for that for cases like this.

**Comment by CyrusNajmabadi** [comment]
To put it in perspective.  No other features do this.  No other features have needed to do this.  Only EM strangely behaves this way.

**Comment by heejaechang** [comment]
in my point of view, the info bar showed up since extract method encountered situation it believes shouldn't happen. so, info bar is doing what is supposed to do.

we can discuss how extract method should behave on such case like rather than throwing, return failed status or something, but right now info bar is behaving as expected.

also, current info bar behavior is not different than any other code refactoring throwing exception.

all question comes down to whether extract method should or should not throw in certain situation. and so far, in my point of view, it has thrown cases where it designed to throw.

either new language features is added that extract method didn't know how to handle, so it threw. or compiler API it is using returned state that It believes it couldn't happen.

**Comment by heejaechang** [comment]
also, don't assumes extract method is only one that made info bar to show up. in NFW, we have hundreds of NFW logged from various refactoring throwing.

**Comment by CyrusNajmabadi** [comment]
> also, current info bar behavior is not different than any other code refactoring throwing exception.

No other code feature throws afaik in case it checks for but doesn't know how to handle.  

> . in NFW, we have hundreds of NFW logged from various refactoring throwing.

We don't have any other features that intentionally do this. ExtractMethod is the only one as far as i know.

> we can discuss how extract method should behave on such case like rather than throwing

Yes.  That's what i'm discussing.  You're throwing based on no information that i can gather.  From teh code in question it says this:

```c#
            // meaning of each boolean values (total of 69 different cases)
```

But there is nothing i can find in any documentation *anywhere* that indicates there are only 69 different cases you may get.  This is not a sound assumption to make.  In other code, when we have an assumption we can't validate with some invariant elsewhere, we remove teh assumption and handle when things aren't as we expect.  

EM is the only case i've seen that just keeps adding cases with the assumption that it knows what is exhaustive, but keeps hitting cases it didn't consider.  My point is that unless EM can definitely prove this list is exhaustive, it should be written with the assumption that it isn't and it should not be throwing and degrading the experience with a gold-bar.  

You can certainly have it log telemetry for this sort of thing.  That would be great in terms of you learning about cases that you didn't know about.  But literally throwing in that case isn't appropriate.

**Comment by CyrusNajmabadi** [comment]
> either new language features is added that extract method didn't know how to handle, so it threw. 

New langauge features are added all the time.  We should try to write our features so that they don't throw when this happens.  This is not difficult to do.  Most features do this (and in cases where they don't, and we discover it, we fix it up).  EM has had this issue for years.  I still don't know why it's persists in this behavior, unlike literally all other features we have...

**Comment by heejaechang** [comment]
those list is created after going through all possible combination of variables returned DataFlowAnalysis APIs.

whenever combination that was not in the list was found, most of time, it was a bug in the DataFlowAnalysis.

so, far, I had only 1 case I remember that wasn't compiler bug. and even that 1 case was due to new language feature added.

there was other bug that is not related to the matrix but related to code assuming certain value from tree or semantic model that got changed due to new language feature changing tree shape and etc.

no idea what you are talking about on matrix keep throwing. if it has thrown, probably should have checked whether DataFlowAnalysis is giving right value or not rather than hiding compiler bugs. since that matrix has found more than 10 bugs on the APIs since it was written.

anyway, wanted to see after fixing C7 issue, whether we will get any more issue from matrix or not. but looks like you went ahead and enabled best efffort.

I wanted to enable that for years, but couldn't since people was against, but looks like since this time it is you, people seems fine. so I am fine as well!

**Comment by CyrusNajmabadi** [comment]
This is no longer necessary as we fixed the underlying issue with throwing code in the extract method matrix code.  As such extract method is no longer behaving in an abnormal way and does not need special compensation when used by the code-refactoring subystem.
