### ISSUE TITLE
VB single-line to block If conversion does not convert parent single-line If

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#30567]
Logging this to be helpful, in case someone feels like fixing it, but I don't use VB myself.
VS 15.8.7

There is an existing feature to rewrite the `If` in block form when you press enter:

![control case](https://user-images.githubusercontent.com/8040367/47118835-b0bc5680-d236-11e8-8778-5ca471312ca5.gif)

But if this is done for an `If` nested in a single-line `If` statement or its `Else` clause:

![error case](https://user-images.githubusercontent.com/8040367/47118885-e6613f80-d236-11e8-85ac-be5071d1e5af.gif)

Expected:

![image](https://user-images.githubusercontent.com/8040367/47118994-4526b900-d237-11e8-8ac8-167ce73ed5ae.png)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not changing these VB experiences now.
