### ISSUE TITLE
Compiler exits with error code compiling Async Stream project

### ISSUE THREAD

**Issue by darenm** [dotnet/roslyn#30566]
**Version Used**: 
Branch Dev16.0.x

**Steps to Reproduce**:

See attached solution.

1.  Open attached solution.
2.  Compile.
3.  Compile fails - check output window, etc.

**Expected Behavior**:
Successfully compile, or report the issue with the code.

**Actual Behavior**:
Compiler fails with an error code.

```log
c:\users\darenmay\appdata\local\microsoft\visualstudio\15.0_641a84e6roslyndev\extensions\microsoft\roslyn compilers\42.42.42.4242424\Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.exe" exited with code -2146232797.
```

@jcouv This is the issue we discussed.

[AsyncStreamRepro.zip](https://github.com/dotnet/roslyn/files/2489052/AsyncStreamRepro.zip)

**Comment by jcouv** [comment]
When I try to build that project locally (using VS 15.9 preview4 with dev hive built from `dev16.0.x` branch), I get this output:
```
1>------ Build started: Project: AsyncStreamRepro, Configuration: Debug Any CPU ------
1>Program.cs(50,34,50,41): error CS0234: The type or namespace name 'Sources' does not exist in the namespace 'System.Threading.Tasks' (are you missing an assembly reference?)
1>Program.cs(36,32,36,41): error CS0305: Using the generic type 'ValueTask<TResult>' requires 1 type arguments
1>Program.cs(83,16,83,37): error CS0246: The type or namespace name 'ValueTaskSourceStatus' could not be found (are you missing a using directive or an assembly reference?)
1>Program.cs(113,89,113,120): error CS0246: The type or namespace name 'ValueTaskSourceOnCompletedFlags' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "AsyncStreamRepro.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

I still get this output even after adding a reference to package `Tasks.Extensions` (4.5.1). I suspect this is because your project is a netcoreapp2.1 project, but I didn't get to drill in very far.
Attached a project that works for me. I've been using a netstandard2.0 library to put the async-iterator code, and a simple console app to invoke it.

[CoreConsole.zip](https://github.com/dotnet/roslyn/files/2489655/CoreConsole.zip)

Note: FYI, I'm about to push a change to using `await foreach` syntax (instead of `foreach await`).

**Comment by jcouv** [comment]
@stephentoub for questions on `Tasks.Extensions` package (4.5.1): 
Is it expected that `ValueTask` (non-generic) and `System.Threading.Tasks.Sources` namespace are available in `netstandard2.0` target, but not `netcoreapp2.1`?

**Comment by darenm** [comment]
Funny on the “await foreach” change - I tried to write it that way 3 times before realizing it was “foreach await”

Thanks,

Daren

________________________________

**Comment by jcouv** [comment]
I'm glad to hear that `await foreach` was your first instinct. We went back and forth on that syntax. Hopefully other folks will feel the same.

**Comment by jcouv** [comment]
Strange. I only managed to create an async-iterator by targeting netstandard2.0 so far.

The async-streams feature should become available on the internal preview channel of dev16 (in next couple of days) if you want to give it a try while I’m away. 
The bug has a simple repro project attached, which demonstrates the problem, even after adding a reference to Tasks.Extensions (4.5.1).

When I added that package reference, I can see from the [command-line arguments](https://github.com/dotnet/roslyn/files/2489775/command-line.txt) that `Tasks.Extensions.dll` is referenced, as well as `System.Runtime.dll`:
`C:\Users\jcouv\.nuget\packages\microsoft.netcore.app\2.1.0-preview1-25929-02\ref\netcoreapp2.1\System.Threading.Tasks.Extensions.dll` (which is **empty**)
`C:\Users\jcouv\.nuget\packages\microsoft.netcore.app\2.1.0-preview1-25929-02\ref\netcoreapp2.1\System.Runtime.dll` (which **does not contain ValueTask**)

**Comment by darenm** [comment]
@jcouv I tried the CoreConsole.sln and it was able to compile, however the dotnet.exe failed to launch it with an error code - I did note that the solution has a different version of the 2.1 preview than I have installed, so I edited the csproj file to match my preview:

```xml
    <RuntimeFrameworkVersion>2.1.0-preview2-26406-04</RuntimeFrameworkVersion>
    <NETStandardImplicitPackageVersion>2.1.0-preview2-26406-04</NETStandardImplicitPackageVersion>
```

However dotnet.exe still failed (with an error code) to run the compiled app.

So, I switched over to using a .NET FW 4.7.2 Console app (LangVersion set to 8.0) and copied the CoreConsole code over and referenced the 2.0 Standard library. That compiles and runs successfully. 

I am going to try switching to the FW console for my "full" demo app to see if that addresses the issues I had there.

**Comment by jcouv** [comment]
@jaredpar FYI in case you want someone to take a look this soon. Sorry about that.
Thanks @darenm for narrowing down the repro.

**Comment by jcouv** [comment]
@jaredpar thinking about this more, what about just adding a diagnostic ("not supported yet") for this scenario for preview 1? (yield return await x)
I can fix when I return.

**Comment by jaredpar** [comment]
@agocke is going to try and get to this next week.
