### ISSUE TITLE
Find all references of a switch statement over an enum type

### ISSUE THREAD

**Issue by Kryptos-FR** [dotnet/roslyn#30575]
**Version Used**:  Visual Studio 15.8.7

**Steps to Reproduce**:

1. Select a `switch` statement that checks against an `enum` type
2. Right-click "Find All References"

**Expected Behavior**:
All `switch` statements in the solution against the same `enum` type are returned to the "references" window.

**Actual Behavior**:
"Search found no results"

**Rationale**
When refactoring an `enum` (e.g. adding a new item or changing the actual value of one), it is necessary to revisit all `switch` statements to make sure they properly handle that change. Right now, it is a laborious and manual process which make missing some instances easy.

At the moment, that proposal only considers `enum` types because other types are too generic (e.g. `int`) and might return a lot of false positives.

**Comment by dpoeschl** [comment]
Design Meeting Notes:

- Handle as a separate command that populates the FAR window with only this kind of "reference" in the context menu when on the switch keyword or an enum type.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
