### ISSUE TITLE
Report an error if unable to synthesize NonNullTypesAttribute

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#30583]
Compile the following:
```c#
#nullable enable
namespace System.Runtime.CompilerServices.NonNullTypesAttribute
{
    class C { }
}
```
Result: No errors but generated assembly does not include synthesized attribute type `System.Runtime.CompilerServices.NonNullTypesAttribute`.

**Comment by cston** [comment]
See `NullableReferenceTypesTests.NonNullTypesAttributeInMergedNamespaceSymbol`.

**Comment by jcouv** [comment]
Closing since we're no longer relying on NonNullTypes attribute.
