### ISSUE TITLE
[Question] How to diagnose problems in csc.exe

### ISSUE THREAD

**Issue by Chrissx** [dotnet/roslyn#30581]
Hi guys,

One of our application build got pretty slow, so we started diagnose with MSBuildStructuredLog and we found most of the spend in csc.exe Is there any "easy" way to see/visualize/diagnose whats actually happening inside the compiler and know why long build time happening?

**Comment by PathogenDavid** [comment]
One thing you can check is whether any analyzers are taking a long time. Add `<ReportAnalyzer>true</ReportAnalyzer>` to a `<PropertyGroup>` in your csproj and rebuild with MSBuild verbosity set to at least "Detailed". This makes the compiler print out a summary of how long each analyzer took.

**Comment by jmarolf** [comment]
@Chrissx in general I would follow [this](https://github.com/dotnet/roslyn/wiki/Recording-performance-traces-with-PerfView) guide to get a local perf trace of csc and see that is causing the problems.  In general there are several algorithms in the compiler that are, as per the language specification, NP-Hard such as method overload resolution.  If you have patterns in your code base that are slowing down compilations it should also present itself as slow IDE interactions as well.

**Comment by jcouv** [comment]
This question was answered with our best information and the thread didn't make progress in a long time. I'll go ahead and close the issue.
Please re-open if still applicable.
