### ISSUE TITLE
Finalize the story around NonNullTypesAttribute

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#30588]
We need to finalize the story around NonNullTypesAttribute:
- Do we still emit it and when?
- If we emit it, we likely need to change the way we inject it into an assembly because we no longer need to to be able to bind to it in source.
- If we emit it, we need to make sure proper errors are reported if its definition is "bad" in any way.

**Comment by AlekseyTs** [comment]
Related to https://github.com/dotnet/roslyn/issues/30583

**Comment by jcouv** [comment]
Closing since we're no longer relying on NonNullTypes attribute.
