### ISSUE TITLE
[VB] PooledObjects usage in FlowAnalysis

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#30589]
The following flow analysis use hashsets and dictionaries, that have the potential to be changed to their pooled variants.
```
AbstractFlowPass
AbstractFlowPass.Regions
AlwaysAssignedWalker
DataFlowPass
DatFlowsInWalker
DataFlowsOutWalker
ReadWriteWalker
IteratorAndAsyncCaptureWalker
```
Is there some aspect of these implementation, that are not suitable to be pooled?
Where should the pooled object be `.Free()` in.

**Comment by gafter** [comment]
@AdamSpeight2008 We don't have any specific reason to think that changing these data structures to use a pooled variant would be a performance (space or time) win. If we did have a specific reason to think it would be a win, we'd probably advocate for making such a change. Do you have any performance measurements to share that would shed light on this? Or were you just wondering?

**Comment by AdamSpeight2008** [comment]
@gafter Mainly curious, just wondering and exploring. *(hence the questions eg "Beware here be dragons")* Initial impression (no hard data) is that the of 56 test partitions that are tested, they seem to executate quicker. Slowing down during the last few.
