### ISSUE TITLE
No warning for second dereference in same expression

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#30598]
The following should result in two warnings dereferencing `x`:
```c#
[System.Runtime.CompilerServices.NonNullTypes]
class Program
{
    static object F(object[]? x)
    {
        return x[          // warning: possibly null
            x.Length - 1]; // no warning
    }
}
```

[jcouv update:] There are multiple references to this issue in code, which need to be addressed before this can be closed.

**Comment by AlekseyTs** [comment]
While the lack of the second diagnostics feels not that critical, the current implementation is likely to provide misleading nullability information to clients of SemanticModel.

**Comment by CyrusNajmabadi** [comment]
> While the lack of the second diagnostics feels not that critical, the current implementation is likely to provide misleading nullability information to clients of SemanticModel.

I'd actually be ok with things if the semanticModel only reported one being nullable (although, intuitively, my feeling is that it should be the inner one).

The intuition here for me is that: if `x` is `null`, then `x.length` would throw.  So you'd never execute `x[...]` in the first place.  So the 'nullability' state of `x[...]` isn't even relevant.  Indeed, that x must *not* be null for it to even execute.

--

This is similar to how some compilers view static analysis in other 'impossible' circumstances.  i.e. if you could only reach code from undefined/impossible circumstances, it can be assumed that that code doesn't matter and shouldn't be checked.

--

Just an FYI on my thoughts here.  If this also changed to have both be considered nullable, it wouldn't bother me either.  But i also wouldn't have a problem with things staying like this.

**Comment by jcouv** [comment]
This was fixed already. I'll add a test to verify

**Comment by jaredpar** [comment]
The expectation is that only one warning should be emitted here but it should be on the indexer, not on the `Length` member.

**Comment by jcouv** [comment]
Moved to backlog milestone after discussion with @gater, as this affects the location of the diagnostic, but we could not come up with a scenario where we currently produce a diagnostic we should not, or miss a diagnostic.

**Comment by 333fred** [comment]
There is a subtlety here that makes this issue significantly more complicated than it initially appears:

```cs
c.M(c.ToString()); // We should learn from the inner deref and not warn on c.M
c.M(c = new C(), c.ToString()); // We should _not_ learn from the inner assignment for c.M, but we should learn for c.ToString()
```

We need to keep this scenario in mind when designing a solution to this problem: it may not be feasible.

**Comment by 333fred** [comment]
After talking with @jaredpar, we're not going to invest in trying to fix the diagnostic locations here. Too much work involved without rewriting a large portion of the nullable analysis engine.

**Comment by CyrusNajmabadi** [comment]
I actually prefer this outcome.  it seems reasonable to just tell the user about one issue and not overly inundate them with what is effectly the same issue to address.

**Comment by 333fred** [comment]
> it seems reasonable to just tell the user about one issue and not overly inundate them with what is effectly the same issue to address.

That isn't what the issue is about. The issue is that the warning (and thus our public API) is in the wrong place. There would still be only one warning.
