### ISSUE TITLE
Reenable the RenamingOpenFilesViaDTE test

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#30599]
The RenamingOpenFiles integration test was disabled as part of the free-threaded work. The functionality seems fine if you manually test, but the test needs additional async waits: when the rename has happened, it has to wait until the rename has been applied to the workspace before the assert is valid. Even without my change, it's not doing that, so the test is likely passing often when it shouldn't, but there's not a window where the UI thread is available when the file is attached to the miscellaneous files workspace. With my change, that window now exists and the test gets mixed up.

**Comment by sharwell** [comment]
> Even without my change, it's not doing that, so the test is likely passing often when it shouldn't, but there's not a window where the UI thread is available when the file is attached to the miscellaneous files workspace.

It does have a wait:

https://github.com/dotnet/roslyn/blob/9a8e958483fd7ad665d0a382cbb39bd3f7f473b3/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/SolutionExplorer_OutOfProc.cs#L127

**Comment by jasonmalinowski** [comment]
There's two problems:

1. That wait doesn't do anything to ensure the project system has pushed state to us.
2. I don't think I hooked up wait intervals for the delay around open file wireup, so that WaitForAllAsyncOperations won't actually do anything. :smile:

@sharwell Are you beginning to do a pass to clean up the disabled tests?

**Comment by sharwell** [comment]
@jasonmalinowski I already completed the pass. I'm just waiting for #32128 to be merged before sending a PR.

**Comment by sharwell** [comment]
📝 As indicated in af66a1c, this test currently only fails when both of the following occur:

1. The rename is performed via DTE (automation API)
2. The project is a CPS project

**Comment by CyrusNajmabadi** [comment]
This test seems to be gone now.
