### ISSUE TITLE
No completion in Razor on Ctrl+J, Ctrl+Space Type @ => ctrl + space or ctrl + j = IntelliSense pops up

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#30604]
https://i.imgur.com/ecEPtd5.gifv

A: Razor's InitializeCompletion simply returns CompletionStartData.ParticipatesInCompletionIfAny. They depend on Roslyn to provide ApplicableToSpan.
Roslyn correctly acts when user types "e.g. @D$$", but not if caret is at "@$$" and user presses Ctrl+J or Ctrl+Space
Please return SnapshotSpan of length 0 at caret location

The VAL build I have has the issue

**Comment by CyrusNajmabadi** [comment]
I've seen 'VAL' a couple of times now.  What does it stand for?  Thanks! :)

**Comment by jinujoseph** [comment]
Val = > Validation build

**Comment by jmarolf** [comment]
even more context: Validation builds are complete install-able builds of Visual Studio with a given set of roslyn changes.  The reason we want this is so we can hand this build off to the perf validation infrastructure to see if we regressed something.

**Comment by NTaylorMullen** [comment]
Validated that even with my Razor completion source bits in the box that this does not work.
