### ISSUE TITLE
VSIX packages links are not working

### ISSUE THREAD

**Issue by azchohfi** [dotnet/roslyn#3061]
http://visualstudiogallery.msdn.microsoft.com/849f3ab1-05cf-4682-b4af-ef995e2aa1a5
http://visualstudiogallery.msdn.microsoft.com/70e184da-9b3a-402f-b210-d62a898e2887

None of the download links are working. Still, you can download the packages thru VS extension explorer.

**Comment by jmarolf** [comment]
I unlisted the old VSIX so people would not accidentally use then in newer builds, but could still access them from the old builds.  These are the links for CTP 6 [ [Vizualizer](https://visualstudiogallery.msdn.microsoft.com/0f18f8c3-ec79-468a-968f-a1a0ee65b388), [SDK](https://visualstudiogallery.msdn.microsoft.com/ecefb773-36a6-4316-98db-4a87ed8cf5dc)] and RC [[Vizualizer](https://visualstudiogallery.msdn.microsoft.com/32fe332c-51ad-411a-a74c-9fdbc2a03bb7), [SDK](https://visualstudiogallery.msdn.microsoft.com/e2e07e91-9d0b-4944-ba40-e86bcbec1599)]

**Comment by azchohfi** [comment]
Thanks!

**Comment by amcasey** [comment]
Confirmed that the new links are live.
