### ISSUE TITLE
IDE0004 : incorrect invalid cast suggestion in VB

### ISSUE THREAD

**Issue by RachelDavids** [dotnet/roslyn#30617]
VS 15.8.7

```vb
	Public Function GetYear(Value As String) As Integer
		Dim year As Integer
		If IsDate(Value) Then
			With CDate(Value)
				year = .Year
			End With
		End If
		Return year
	End Function
```

After applying the quick-fix to the solution I discovered several of these now broken since the With Value expression has changed type and hence the code no longer compiles.

**Comment by CyrusNajmabadi** [comment]
@RachelDavids 

> After applying the quick-fix to the solution

Which quick fix did you apply?

**Comment by RachelDavids** [comment]
I applied the "Remove unnecessary cast" fix.

Applying the the code in the sample above produces the following output
`
	Public Function GetYear(Value As String) As Integer
		Dim year As Integer
		If IsDate(Value) Then
			With Value ' CDate removed
				year = CInt(.Year) ' CInt added, but now .Year is invalid
			End With
		End If
		Return year
	End Function
`

**Comment by CyrusNajmabadi** [comment]
@RachelDavids you can use ```vb  
to format your code.

**Comment by CyrusNajmabadi** [comment]
Yup.  I repro the issue: 

![image](https://user-images.githubusercontent.com/4564579/47208857-cec3ad00-d343-11e8-9332-124f15f57132.png)

'CDate' should not be considered a removable cast here.  Thanks for the report!

**Comment by RachelDavids** [comment]
@CyrusNajmabadi  I suspect it may not quite be as simple as that - 

Consider the following

```vb
Dim a as object
With CStr(a)
    Dim x as Integer = .Length
End WIth
```
This suggests that avoiding With expressions may be what is needed especially if the resultant cast is  referenced

**Comment by CyrusNajmabadi** [comment]
@RachelDavids That seems like the same issue.  A cast within a 'with' isn't properly handled and is marked as being somethign that can be removed.
