### ISSUE TITLE
Argument Null Checking

### ISSUE THREAD

**Issue by mikernet** [dotnet/roslyn#30625]
I don't see argument null checking anywhere in any of the Roslyn projects that I've played with so far. At first I thought that maybe there was a post-build weaver adding null checking but I tested calling some of the public API with null arguments and indeed there is no null checking happening and `NullReferenceException`s get thrown.

The [code conventions](https://github.com/dotnet/roslyn/wiki/Contributing-Code#coding-conventions) indicate that public boundaries should be null checked. What's going on here?

-Slightly confused Roslyn newbie

**Comment by CyrusNajmabadi** [comment]
>  What's going on here?

You've run into bugs.  Feel free to file issues and/or submit PRs.
