### ISSUE TITLE
The debugger display for sizeof is inconsistent

### ISSUE THREAD

**Issue by pdelvo** [dotnet/roslyn#3062]
Consider this code:
```csharp
using Assembly2;

public class Class1
{
    static unsafe void Main()
    {
        System.Console.WriteLine(sizeof(Foo));
    }
}
```
```csharp
namespace Assembly2
{

    public struct Foo
    {

    }
}
```
Both files have to be in different assemblies. The WriteLine will print 1, but the debugger display and the intermediate window will show 0 for the sizeof expression.

**Comment by cston** [comment]
@pdelvo I am unable to repro this issue with recent builds. (In the Immediate Window, sizeof returns 1, as does hovering over the "sizeof" expression in the editor.) What build of VS are you using to repro? Thanks.

**Comment by cston** [comment]
@pdelvo I am unable to repro this issue with recent builds. (In the Immediate Window, sizeof returns 1, as does hovering over the "sizeof" expression in the editor.) Is there more to the repro that I might be missing?

**Comment by pdelvo** [comment]
Thats weird. I just tried it again and Im able to repro it consistently. Maybe it is already fixed post rc? I uploaded a repro projec to https://github.com/pdelvo/RoslynRepro3062.

![repro](https://cloud.githubusercontent.com/assets/1710209/7924503/02776444-08bc-11e5-9b88-f8944d42d311.PNG)

**Comment by cston** [comment]
I am able to repro this with an earlier build, so it appears to have been fixed recently. Thanks.
