### ISSUE TITLE
QuickInfo, FAR, MAS etc don't work on operators of built-in/well-known types

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#30642]
**Version Used**: VS 15.8.7 (Roslyn 2.9.0.63208)

**Steps to Reproduce**:

1. Write some code that invokes the operator of a type that is built-in/has a keyword (`string`, `int`, `System.Int64`, ...)
2. For comparison, do the same with a regular type (`DateTime`, `Guid`, ...)
3. On each operator, invoke QuickInfo, FAR and MAS. (Other tools are probably affected, too.)

Example code:

```c#
void M()
{
    // Well-known types:
    var a = "test" == "test";
    var b = 1 == 1;
    var c = Int64.MaxValue <= Int64.MinValue;
    // Other types:
    var d = default(Guid) == default;
    var e = default(TimeSpan) >= TimeSpan.Zero;
}
```

**Expected Behavior**: FAR finds all references/usages, MAS goes to the symbol definition in metadata, QuickInfo shows an operator tooltip.

**Actual Behavior**:

* QuickInfo shows the operator as a regular method instead of an operator (different glyph), and shows no documentation text.
* FAR doesn't find any references, including the one you selected.
* MAS says "Cannot navigate to the symbol under the caret".

Example with `string`:
![builtin-op](https://user-images.githubusercontent.com/823398/47295599-4ded0580-d610-11e8-98d4-6450071089ad.png)

Example with `System.Guid`:
![type-op](https://user-images.githubusercontent.com/823398/47295602-4fb6c900-d610-11e8-8654-25a7ed0f7f82.png)

**Comment by CyrusNajmabadi** [comment]
I'm not certain how MAS would work.  For many types these operators do not actually exist in metadata.  

That said, string's operators do exist.  So i'm not sure why navigating to them isn't working.

**Comment by CyrusNajmabadi** [comment]
Note: we do support finding user defined operators.  We don't support finding built-in operators.  It would not be hard to support though.  The major issue is simply that it likely won't be very efficient.  FAR benefits from syntactic indices that allow us to limit the amount of documents to search.  If you are searching for `==`, then we'll effectively have to search *every* file in your entire solution.  So, we can def do it.  But it's not going to win any speed awards :)

**Comment by CyrusNajmabadi** [comment]
@gafter I'm seeing something very weird for System.String.  The type itself has a normal PR method symbol for `operator ==`.  However, there is also a synthesized `operator ==` produced for it that the compiler returns.  Can you explain why both of these exist?  My guess is that it relates to the language's view that this op must exist, even if we happened to load metadata where it didn't exist... But that's just a WAG.  I'm not sure what's really going on.

**Comment by CyrusNajmabadi** [comment]
Ok.  I have fixes out for several of htese issue.  However, the request for Find-Refs on regular built-in operators (like `==` for ints) will have to be done as extra work.  It's effectively a feature-request for the find-refs engine to support builtin operators.

**Comment by CyrusNajmabadi** [comment]
Closing out. this work was done.
