### ISSUE TITLE
Switch expression as a statement expression

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#30649]
From https://github.com/dotnet/csharplang/issues/1054

> It has been requested that we permit a switch expression to be used as a statement expression. In order to make this work, we'd
> 
> Permit its type to be void.
> Permit a switch expression to be used as a statement expression if all of the switch arm expressions are statement expressions.
> Adjust type inference so that void is more specific than any other type, so it can be inferred as the result type.
> **Resolution 2018-10-10**: Yes! This requires a more precise spec, and it needs to handle a?.M() where M() returns an unconstrained T.

This might not be implemented for C# 8, but it would be good if it were.

**Comment by alrz** [comment]
>Permit a switch expression to be used as a statement expression if all of the switch arm expressions are statement expressions.

Does this recursively applies to itself - meaning we can nest switch expressions in such switch expressions?
```cs
e switch {  _ => a switch { _ = > M() } };
```
If this is valid, I'll adjust #31812 accordingly.

**Comment by gafter** [comment]
@alrz Probably yes, but I would not write any IDE code depending on this getting into C# 8 until it is in the language.  It may be some time, or it may not make it into C# 8.

**Comment by gafter** [comment]
Closing pending LDM decisions about what the feature should look like.
