### ISSUE TITLE
Simplify bi-directional map in CSharpFormattingOptions

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#30643]
> 💡 This one does not need to be a bi-directional map. I'll file a follow-up item to change it to `ImmutableDictionary<string, NewLineOption>` (or just inline it).

https://github.com/dotnet/roslyn/blob/9e8cb6e4ce946d0206b62b9bd8ec55de42b96a91/src/Workspaces/CSharp/Portable/Formatting/CSharpFormattingOptions.cs#L43-L47

_Originally posted by @sharwell in https://github.com/dotnet/roslyn/pull/30638_

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
