### ISSUE TITLE
Allow setting breakpoints on ternary branches

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#30646]
The penalty for using ternaries instead of `if` statements is that breakpoints can't be set for each branch. When you're in the middle of debugging, it's too late to refactor. Sometimes you can set a breakpoint on the whole statement and duplicate the effective condition, but this expression may be nested inside another ternary or in a long initializer expression; even when you can duplicate the condition without side effects, it's frustrating to put together.

Similar to https://github.com/dotnet/roslyn/issues/30645, possibly covered by https://github.com/dotnet/roslyn/issues/22016.

**Comment by jnm2** [comment]
Besides common debugging scenarios, another reason I'm really hoping for sequence points to be emitted for expressions is that Live Unit Testing (last I tried it), ReSharper's teest coverage, and NCrunch all use statement or line granularity. Because of the lack of expression granularity, this obfuscates the true branch coverage situation.

**Comment by jnm2** [comment]
When switch expressions arrive, this will become even more important.

**Comment by jinujoseph** [comment]
looks same as https://github.com/dotnet/roslyn/issues/22016 , cc @tmat

**Comment by tmat** [comment]
Yes, this is covered by #22016. I don't think we need to track it in multiple issues.

**Comment by jnm2** [comment]
Now tracked by https://github.com/dotnet/roslyn/issues/43092
