### ISSUE TITLE
IDE0041 Null check can be simplified codefix cannot be applied

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#30644]
**Version Used**: Visual Studio 15.8.7

**Steps to Reproduce**:

1. Create a new project and add the following code
```C#
class C
{
    public static void NotNull<T>(T value)
    {
        if (ReferenceEquals(value, null)) // IDE0041
        {
            return;
        }
    }
}
```
2. Attempt to invoke codefix `IDE0041` on `ReferenceEquals`

**Expected Behavior**:

Code fix succeeds

**Actual Behavior**:
Code fix is invoked but no fix is applied.
![image](https://user-images.githubusercontent.com/9797472/47299373-ec587700-d5ce-11e8-899d-1b26d370a0bd.png)
![image](https://user-images.githubusercontent.com/9797472/47299406-f7aba280-d5ce-11e8-88dd-e1994cdf1e42.png)

@sharwell 	related to https://github.com/dotnet/roslyn/issues/23581

**Comment by CyrusNajmabadi** [comment]
Known issue that was fixed:

![image](https://user-images.githubusercontent.com/4564579/47310350-acec5380-d5eb-11e8-8f2d-34e46f1ff2b1.png)


Tested on 15.9p3

**Comment by jmarolf** [comment]
Confirmed fixed in newer builds

**Comment by Neme12** [comment]
Duplicate of #29455
