### ISSUE TITLE
Allow setting breakpoints on the right side of ??

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#30645]
Deep in an object initializer, there's a `Prop = expr1 ?? expr2`. It would be convenient to be able to set a breakpoint on the right expression operand.

Possibly covered by https://github.com/dotnet/roslyn/issues/22016, similar to https://github.com/dotnet/roslyn/issues/22015 but more general.

**Comment by tmat** [comment]
Covered by #22016. I don't think we need to track it in multiple issues.

**Comment by jnm2** [comment]
Now tracked by https://github.com/dotnet/roslyn/issues/43092.
