### ISSUE TITLE
Compilation without generics

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#3064]
The C#/VB compilation teams used to be pretty keen on supporting compilation for runtime without generics support, for example, using pattern-based approaches.

The Roslyn compiler does not seem to really care, and while probably nobody builds desktop CLR 1.x applications, the .NET Micro Framework's CLR does not support generics for limited resources reasons and currently needs to use the old compilers because of recent incompatibility changes.

The most limiting is the decision to implement events using generic `Interlocked.CompareExchange<T>`. Also, bit shift operators in VB require `Nullable<T>`. There are more difficult or impossible cases (like anonymous types) but these two are fundamental language features.

The only option for .NET MF to move on to Roslyn as is is to introduce post-build IL transformations that would have to be kept up-to-date to match IL generated by Roslyn. I wonder whether we could rather make the compiler either more concerned about generics (verify the required types/methods are available and use non-generic variants if possible) or give it a hint that generics are not available...

Any thoughts?

**Comment by miloush** [comment]
(Note: The `Interlocked.CompareExchange<T>` issue was fixed with [changeset 1371805](http://roslyn.codeplex.com/SourceControl/changeset/b458647488ef176d879f069cc280bd6d14e583c8).)

**Comment by gafter** [comment]
I think the compilers should generate code that works around the absence of these particular APIs.

**Comment by Sebazzz** [comment]
Isn't it an option to lower the language version or am I missing the point?

**Comment by jantheman** [comment]
@Sebazzz: You don't necessarily want to lower the language version, LINQ for example works fine without generics.

**Comment by miloush** [comment]
@Sebazzz: You don't necessarily want to lower the language version, for example LINQ works fine without generics.

**Comment by gafter** [comment]
One issue is the compiler's use of constrained/callvirt when calling a virtual method of a struct, which we do to preserve (not box) the identity of the receiver. This instruction was added with generics. This is observable if, for example, you override the ToString method on a struct and it has a side-effect (for example, cacheing the string form into a field of the struct for performance reasons). To get those semantics without constrained/callvirt we'd could use a direct call if the method is overridden, but that makes the change (adding or removing the override of ToString) a binary-incompatible change.

**Comment by miloush** [comment]
From the email thread it looks like `constrained` should not be a problem for .NET Micro Framework. It also supports `unbox.any` for example, which was introduced with generics too. The trick here is that in the case of MF, it is not strictly CLR 1.x, but rather CLR 2.0 without generics and unsafe.

I am not sure if Roslyn needs to support pre-CLR 2.0 or similarly limited customers but I would like to avoid a solution with either "CLR 1.x mode" or no mercy. That would happen again with 2.0 when compiler starts to depend on CLR 4.0 features etc. I personally think the way most of Roslyn works now with patterns where possible is great and should be the way forward.

**Comment by miloush** [comment]
Just found out that unlike the latest native compiler, Roslyn does not seem to require `Nullable<T>` for shift operators in VB.

**Comment by gafter** [comment]
@miloush It sounds like the only remaining issue among those discussed above is the use of generic `Interlocked.CompareExchange<T>` to implement events. Can you please tell me what the specific situation is in the source that causes an issue, what we generate today, and what you would prefer we generate? Which language(s) are affected?

Also, are there any other specific changes that would be helpful for your scenario?

**Comment by jaredpar** [comment]
Wanted to ping this issue.  Has there been any progress on the last remaining item?

**Comment by miloush** [comment]
Yes I am sorry this is on my backlog. My current understanding is that both VB shift operators and events now work without generics. There are some questions about how `constrained` is being used in the compiler but my believe now is that .NET Micro Framework should get its implementation on par with the desktop runtime (assuming it's job of `constrained` to handle `ldarga.s` for `char`). I wanted to do more language testing to update this issue, but have not got a chance yet. Is there a noteworthy deadline to keep in mind?

**Comment by jaredpar** [comment]
@miloush there is about one month of bug fixing left in our current release.  After that we could still do the work but it would roll over to the next release.

**Comment by gafter** [comment]
@miloush If you don't have any specific things for us to fix, I'd like to close this issue. Is that OK with you? Of course you're welcome to open up an issue (or reopen this one) if you identify something specific we need to fix.
