### ISSUE TITLE
Microsoft.VisualStudio.LanguageServices has added many new nuget dependencies 

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#30662]
**Version Used**: 2.11

**Expected Behavior**:
In [2.10](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.VisualStudio.LanguageServices/2.10.0-beta2-63410-10) the Microsoft.VisualStudio.LanguageServices  dependencies were: 
- Microsoft.CodeAnalysis (= 2.10.0-beta2-63410-10)

**Actual Behavior**:
In [2.11](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.VisualStudio.LanguageServices/2.11.0-beta1-63422-06-da76391f) they are now:
- Microsoft.Build (>= 15.1.0-preview-000458-02)
- Microsoft.CodeAnalysis.Common (= 2.11.0-beta1-63422-06-da76391f)
- Microsoft.CodeAnalysis.EditorFeatures.Common (= 2.11.0-beta1-63422-06-da76391f)
- Microsoft.CodeAnalysis.EditorFeatures.Text (= 2.11.0-beta1-63422-06-da76391f)
- Microsoft.CodeAnalysis.EditorFeatures.Wpf (= 2.11.0-beta1-63422-06-da76391f)
- Microsoft.CodeAnalysis.Elfie (>= 0.10.6)
- Microsoft.CodeAnalysis.Features (= 2.11.0-beta1-63422-06-da76391f)
- Microsoft.CodeAnalysis.Workspaces.Common (= 2.11.0-beta1-63422-06-da76391f)
- Microsoft.DiaSymReader (>= 1.3.0)
- Microsoft.VisualStudio.Debugger.Engine-implementation (>= 15.7.2082401)
- Microsoft.VisualStudio.SDK.EmbedInteropTypes (>= 15.0.17)
- Microsoft.VisualStudio.Shell.Interop.15.7.DesignTime (>= 15.7.1)
- Microsoft.VisualStudio.Threading (>= 15.8.99-rc)
- Microsoft.VSSDK.BuildTools (>= 15.8.68-develop-g109a00ff)
- Newtonsoft.Json (>= 9.0.1)

**Comment by jasonmalinowski** [comment]
So *some* of these are definitely OK...some aren't. The list of things that are definitely bad are:

- Microsoft.VSSDK.BuildTools (referencing us shouldn't bring along VSIX packaging)
- Microsoft.VisualStudio.Debugger.Engine-implementation (that's an implementation package)
- Microsoft.Build (nope nope nope nope nope)

**Comment by jasonmalinowski** [comment]
FYI to @tmat.

**Comment by JoeRobich** [comment]
These are the dependencies for [3.2.0-beta4](https://www.nuget.org/packages/Microsoft.VisualStudio.LanguageServices/3.2.0-beta4-final):
- Microsoft.CodeAnalysis.Common (= 3.2.0-beta4-final)
- Microsoft.CodeAnalysis.EditorFeatures.Text (= 3.2.0-beta4-final)
- Microsoft.CodeAnalysis.Features (= 3.2.0-beta4-final)
- Microsoft.CodeAnalysis.InteractiveHost (= 3.2.0-beta4-final)
- Microsoft.CodeAnalysis.Workspaces.Common (= 3.2.0-beta4-final)
- Microsoft.VisualStudio.Composition (>= 15.5.23)

@tmat Are there any remaining that we want to remove?

**Comment by CyrusNajmabadi** [comment]
@jmarolf is this actionable?

**Comment by jmarolf** [comment]
I believe this has been fixed

**Comment by jasonmalinowski** [comment]
Yeah, it was.
