### ISSUE TITLE
Weird behavior having two assemblies with same name

### ISSUE THREAD

**Issue by biqas** [dotnet/roslyn#3066]
Hi,

I would suggest enhancement options if you reference from a project two different projects with identical assembly name.

1.
It should be avoided through reference explorer with dynamic analysis.

2.
During compilation getting the warning that an assembly is overwritten. (Instead of: MSB6006)

**Comment by CyrusNajmabadi** [comment]
Haven't heard any customer feedback on this in nearly 10 years.  Closing out.
