### ISSUE TITLE
Rename tracking crashed

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#30661]
The initial blame of the null reference is here:

https://github.com/dotnet/roslyn/blob/5a8dabf92d3abb17b47b9c54d33d93313dc8d725/src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.StateMachine.cs#L123

Although as is often the case, it might be a few lines earlier or later since I haven't done a careful analysis.

Dump is available at `\\mlangfs1\public\jasonmal\Dumps\Roslyn\30661\`

**Comment by sharwell** [comment]
@jasonmalinowski I'm seeing this intermittently in integration tests.

**Comment by jasonmalinowski** [comment]
@sharwell OK, I'll prioritize then.
