### ISSUE TITLE
Implementation of GetHashCode for constructed/substituted named type symbols is incorrect for some edge cases

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#30673]
In some rare cases substituted/constructed type is considered equal to its original definition. For example, when comparison is ignoring Custom Modifiers. Implementation of GetHashCode should account for this and return OriginalDefinition.GetHashCode for symbols like that, but it doesn't.

**Comment by AlekseyTs** [comment]
Once we ensure that all implementations of GetHashCode are not sensitive to aspects that can be ignored by different flavors of type symbol comparison, we should consider removing TypeComparisonKind checks from implementation of MemberSignatureComparer.GetHashCode(Symbol member).

**Comment by jcouv** [comment]
I'll take a look at this
