### ISSUE TITLE
[Proposal] Multiple assignment using tuples

### ISSUE THREAD

**Issue by zgxnet** [dotnet/roslyn#307]
Dynamic languages such as python support multi-value assignments based on tuple, which is useful especially for multi return value functions.
In C#, there can be a similar implementation:

Tuple\<TypeA, TypeB\> F();

var a, b = F(); //a,b are defined by var
a,b = F(); //a, b are defined previously
var a, = F(); //only fetch the first part
var ,b = F(); //only fetch the second part

For readability, we can also specify the type explicitly, 
var TypeA a, TypeB b = F();
or just var TypeA a,b = F();  // if typeA=typeB
The using of var is to let it easily distinguishable from the normal case: TypeA a, b=somevalue;

Of cause, the language details can still be discussed.

I know that C# support out keyword to return multi values, but in many cases, e.g. async/await we cannot use out keyword. Besides, this is a more elegant way to enable a function to return multi values.

**Comment by Miista** [comment]
What you are essentially asking for is tuple deconstruction.

**Comment by zgxnet** [comment]
Yes, it is tuple deconstruction, very powerful feature. And I think it is very easy for C# to support it.

**Comment by jibal** [comment]
> I'm not sure I like having a function return multiple values.

You don't have to write such functions.

> Isn't that somehow a sign that the function is maybe doing more that it's supposed to?

Every function is *maybe* doing more than it's supposed to, but returning a tuple doesn't imply it, any more than returning any other composite value, or having out parameters, implies it. And there's already a Tuple type, so this is a red herring. As you said, this proposal is about tuple deconstruction, so any objections should be about that, not about returning multiple values.

**Comment by gafter** [comment]
Specified in #6400; treating as a dup of that.
