### ISSUE TITLE
Support the tadpole operators

### ISSUE THREAD

**Issue by GSPP** [dotnet/roslyn#3072]
VC++ is going to support new arithmetic operators that seem to be exceptionally useful: The tadpole operators (http://blogs.msdn.com/b/oldnewthing/archive/2015/05/25/10616865.aspx).

![t](https://cloud.githubusercontent.com/assets/12032350/7799782/e0f89222-030a-11e5-8bad-f4c5e6a2a6e8.PNG)

C# should support those operators to be aligned with VC++!

**Comment by pdelvo** [comment]
I dont really see the value in this. Whats so fundamentally wrong with y + 1/- 1 that it justifies two new operators?

**Comment by svick** [comment]
@pdelvo I believe that's the joke. Similar to the "goes to" operator: `while (x --> 0)`.

**Comment by GSPP** [comment]
@svick what do you mean by joke? We need the "goes to" operator as well!

**Comment by pdelvo** [comment]
With the features that get requested you never know if its meant to be a joke or not ;)

**Comment by Joe4evr** [comment]
What exactly is wrong with using `i++` and `i--`?

**Comment by svick** [comment]
@Joe4evr They modify `i`, whereas `-~i` or `i+1` don't.

**Comment by bradphelan** [comment]
It's a joke for sure but it already works because the operators _-_ and _~_ are applied one at a time. See

```
using System.IO;
using System;

class Program
{
    static void Main()
    {
        int i = 1;
        Console.WriteLine(~-1);
        Console.WriteLine(-~1);
    }
}
```

outputs

```
0
2
```

as expected ;)
