### ISSUE TITLE
Intellisense suggestion mode does not work after backspace

### ISSUE THREAD

**Issue by Dunkhan** [dotnet/roslyn#30725]
**Version Used**: VS 2017 15.8.7

**Steps to Reproduce**:

1. Switch to suggestion mode
2. in a function context, type the characters "as."
3. press backspace twice
4. Type '.' once again

Please note backspacing past a '.' or space or similar character is necessary, the reproduction does not work otherwise

**Expected Behavior**:
The text should read "a."

**Actual Behavior**:
The text reads "AccessKeyEventArgs."

Related issues: 
#5200 
#28921

**Comment by Dunkhan** [comment]
I don't agree that this is a feature request. Is it the current behaviour intended?

**Comment by zinvob** [comment]
Why is this still an issue? They destroyed IntelliSense with 2017, and never fixed it. This should be of high priority. It's a daily frustration when suggestion mode suddenly is not active and random tekst is entered into the editor while writing. NEVER should you be locked to write "a." and get something else. People that want this annoyance may select it, but it should not be forced on you. Number >1< priority of an editor should be that you can 100% certain that what you type is what get's written.

This is 100 times more important than any of the new features in 2019..

**Comment by Dunkhan** [comment]
I checked the documentation and it says 
`You can also change to suggestion mode, in which only the text you type is inserted into the code`
in https://docs.microsoft.com/en-us/visualstudio/ide/using-intellisense?view=vs-2017
at the bottom of the paragraph "List Members"

Given that this bug explicitly describes a situation where text which was **not** typed is inserted into the code, that means either the documentation is wrong or this is a bug, not a feature request.

A suggested correction for the documentation would be "...only the text you type is inserted into the code, unless you have recently pressed backspace, and the deleted character was a non-word character"

**Comment by CyrusNajmabadi** [comment]
@Dunkhan @zinvob Would you be interested in contributing a fix?  I can help point you to likely locations in the code to investigate.  As this issue is not assigned to anyone, it's likely that that would lead to a positive resolution for you two the fastest way possible.

**Comment by Dunkhan** [comment]
It is certainly a useful suggestion to write some code locations here. Whether I will have time to work on it myself is uncertain, but it is possible.

**Comment by zinvob** [comment]
This seems to be in the Visual Studio Editor code, not the Intellisense API's for Roslyn. Is that part also public?

**Comment by Dunkhan** [comment]
This is fixed in 2019. I will close it.
