### ISSUE TITLE
Compile errors when building master

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#30739]
**Version Used**: master (6801607)

**Steps to Reproduce**:

1. `git clean -xdf`
2. `Restore.cmd`
3. `Build.cmd`

**Expected Behavior**: Build succeeds.

**Actual Behavior**:

> Build FAILED.
> 
> C:\code\roslyn\src\VisualStudio\Core\Def\RoslynPackage.cs(254,13): error CS0103: The name 'BulkFileOperation' does not exist in the current context [C:\code\roslyn\src\VisualStudio\Core\Def\Microsoft.VisualStudio.LanguageServices_vgqnzifs_wpftmp.csproj]
C:\code\roslyn\src\VisualStudio\Core\Def\RoslynPackage.cs(259,13): error CS0103: The name 'BulkFileOperation' does not exist in the current context [C:\code\roslyn\src\VisualStudio\Core\Def\Microsoft.VisualStudio.LanguageServices_vgqnzifs_wpftmp.csproj]
    0 Warning(s)
    2 Error(s)

Possibly related to https://github.com/NuGet/Home/issues/5894?

**Comment by jasonmalinowski** [comment]
@svick Hmm, are you still running into this? I can't reproduce on my machine. Good call on the NuGet bug, but that would explain why it's fine for me...

**Comment by svick** [comment]
No, build seems to work fine now, closing.
