### ISSUE TITLE
Add using should not add normal usings to a group of only-using-aliases.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#30734]
A not-uncommon pattern in C# is to have:

```c#
using normal_stuff
using more_normal_usings;

namespace A.B.C
{
     using static SomethingFromThisProject;
     using static SomethingElseFromThisProject;

    class Whatever
    {
         // here.
    }
}
```

In a case like this, if someone invokes add-using, we always put hte using in the nearest contained using section that has existing usings.  We do this regardless of the kinds of using-statements already in that block.  IN a case like this, if the user is adding a using-static, it should go in the inner block of usings, while a regular using should go in the outer block. 

We see ths fallout from this in PRs quite a bunch where people quick add the using, but then it is noticed during PR that it's in the wrong location.

**Comment by jinujoseph** [comment]
cc @JoeRobich

**Comment by jinujoseph** [comment]
fixed via https://github.com/dotnet/roslyn/pull/33125
