### ISSUE TITLE
Confusing error message about determinism and AssemblyVersion in VB

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30738]
Recently updated to Visual Studio 2017 v 15.8.5

Changing AssemblyInfo.vb
from default (swapping comments):

```
' You can specify all the values or you can default the Build and Revision Numbers
' by using the '*' as shown below:
' <Assembly: AssemblyVersion("1.0.*")>
<Assembly: AssemblyVersion("1.0.0.0")>
<Assembly: AssemblyFileVersion("1.0.0.0")>
```

to:

```
<Assembly: AssemblyVersion("1.0.*")>
'<Assembly: AssemblyVersion("1.0.0.0")>
'<Assembly: AssemblyFileVersion("1.0.0.0")>
```

gives the following error:

Error BC36962 The specified version string does not conform to the required format - major[.minor[.build|*[.revision|*]]]

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/346841/bc36962.html
VSTS ticketId: 694617_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by agocke** [comment]
We fixed this for C# here: https://github.com/dotnet/roslyn/issues/22660 but forgot about VB.

**Comment by A9G-Data-Droid** [comment]
Just got this error today on a new project. This ticket has been open for a long time. It was fixed in October?

**Comment by chewiiieee** [comment]
Did this ever get fixed in VB???  Seems to be still happening in VS 16.2.1.

**Comment by chewiiieee** [comment]
Nevermind.  For anyone who read this the fix is to add the following to your *.vbproj file.

  <PropertyGroup>
    <Deterministic>False</Deterministic>
  </PropertyGroup>

**Comment by PeterAdam** [comment]
Still unfixed. Please.

**Comment by adamint** [comment]
@jaredpar @sharwell we've received two feedback tickets in the past month about this

**Comment by BitBucket3** [comment]
When, if EVER, is this going to be fixed? It is VERY frustrating to have to remember to manually change the build number every time and has lead to several incorrect versions being used.

**Comment by agocke** [comment]
I no longer work on the compiler, but if someone wants to try fixing this themselves, porting https://github.com/dotnet/roslyn/pull/22973 over to VB should be simple. The symbol model for VB is a mirror of the C# one. It would basically be taking the changes to the C# SourceAssemblySymbol and making the same changes to the VB source assembly symbol.

I think this would be a good fix for someone who's never contributed to Roslyn before.
