### ISSUE TITLE
Why does missing class identifier cause skipping parsing members?

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#30749]
**Version Used**:  master (6801607)

**Steps to Reproduce**:

Run the following test:

```c#
        [Fact]
        public void MissingNameForClassWithField()
        {
            var source = @"class
{
    int i;
}
";
            var root = SyntaxFactory.ParseSyntaxTree(source).GetRoot();

            var classDecl = root.DescendantNodes().OfType<ClassDeclarationSyntax>().Single();
            Assert.True(classDecl.Identifier.IsMissing);
            Assert.False(classDecl.OpenBraceToken.IsMissing);
            Assert.False(classDecl.CloseBraceToken.IsMissing);
        }
```

**Expected Behavior**: Test passes.

**Actual Behavior**:

Test fails on the last `Assert`. According to Roslyn Quoter, the code is parsed as:

```c#
CompilationUnit().WithMembers(List<MemberDeclarationSyntax>(new MemberDeclarationSyntax[]{
    ClassDeclaration(MissingToken(SyntaxKind.IdentifierToken))
        .WithCloseBraceToken(MissingToken(SyntaxKind.CloseBraceToken)),
    FieldDeclaration(VariableDeclaration(PredefinedType(Token(SyntaxKind.IntKeyword)))
        .WithVariables(SingletonSeparatedList<VariableDeclaratorSyntax>(
            VariableDeclarator(Identifier("i")))))
        .WithSemicolonToken(Token(
            TriviaList(), SyntaxKind.SemicolonToken,
            TriviaList(Trivia(
                SkippedTokensTrivia().WithTokens(TokenList(
                    Token(SyntaxKind.CloseBraceToken)))))))}))
```

Notice that the `class` has a missing `CloseBraceToken` and is followed by a "global" field and a skipped `CloseBraceToken`.

I think that parsing it like this is not great. Is there a reason for this?

The code that's causing this behavior is:

https://github.com/dotnet/roslyn/blob/6801607c96126ccc123c17fbd7348af30aec0b88/src/Compilers/CSharp/Portable/Parser/LanguageParser.cs#L1530-L1534

If I delete the `name.IsMissing` condition, all Roslyn tests still pass and the above test also passes.

Note that I got into a this situation while renaming a class in VS: first I deleted the old identifier and then I wanted to write the new one.

**Comment by CyrusNajmabadi** [comment]
The concern here is how "off hte rails" things can go.  In general, trying to proceed when you don't have enough helps in these sorts of 'delete' cases, but can hurt in a lot of other cases.

**Comment by CyrusNajmabadi** [comment]
> Note that I got into a this situation while renaming a class in VS: first I deleted the old identifier and then I wanted to write the new one.

Sure.  There are *many* cases where deleting any critical token can cause similar impacts.  But, in practice, it shouldn't actually impact things negatively as this is just an ephemeral state during typing.  To put it in context, this behavior has been here since probably around VS2002, and really hasn't been an issue :)

**Comment by svick** [comment]
@CyrusNajmabadi 

Thanks.

> In general, trying to proceed when you don't have enough helps in these sorts of 'delete' cases, but can hurt in a lot of other cases.

In that case, shouldn't there be tests that verify that these other cases behave well? As far as I can tell, there aren't any.

**Comment by CyrusNajmabadi** [comment]
> In that case, shouldn't there be tests that verify that these other cases behave well? 

Sure.  That would be sensible.  I'm happy to have more tests :)

**Comment by svick** [comment]
@CyrusNajmabadi Can you provide some examples of those "other cases" for which tests could be added?
