### ISSUE TITLE
IDE0004 on cast from unconstrained generic type to 'object' in null check.

### ISSUE THREAD

**Issue by iharwell** [dotnet/roslyn#30759]
**Version Used**: 
Microsoft Visual Studio Community 2017 
Version 15.8.8
Microsoft .NET Framework
Version 4.7.03056

**Steps to Reproduce**:

Place the following method in any class with IDE0004 enabled.
`bool Method<T>(T item) => ((object)item) is null;`

**Expected Behavior**:
Nothing happens, as all parts are necessary.

**Potentially Better than Expected Behavior (Not presently valid code)**
`bool Method<T>(T item) => item is null;`

The method above returns false whenever T is a value type, as item is not ever null in this case. This would avoid the cumbersome syntax above. I am not sure what, if any, ripple effects this would have, though.

**Actual Behavior**:
This gives IDE0004 on the cast to object, and the fix for that removes the cast, resulting in error CS0403: "Cannot convert null to type parameter 'T' because it could be a non-nullable value type. Consider using 'default(T)' instead."

While the suggested fix is appropriate in some cases, there are situations where the default(int), or zero, would be entirely valid in the code, but null would not.

**Comment by CyrusNajmabadi** [comment]
This is by design.  The language was changed to allow `is null` for generic type parameters.
