### ISSUE TITLE
Bad tooltip on structure guidelines in VB

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#30762]
**Version Used**: 15.9p3

**Steps to Reproduce**:
```vb
<Serializable>
Friend Class C
    Sub M()
        If True Then



        End If
    End Sub
End Class
```
Hover over the vertical line between If and End If:

![image](https://user-images.githubusercontent.com/11444821/47524160-2741ff80-d89a-11e8-8f8e-0d5b0617eedc.png)

I'm not sure if this is even supported in VB or not. If the class doesn't have an attribute, there is no tooltip at all. So if VB isn't supported, "expected" behavior would be nothing. Ideally though, it should be,

**Comment by jinujoseph** [comment]
Related to #26445

**Comment by CyrusNajmabadi** [comment]
Doesn't repro for me:

![image](https://user-images.githubusercontent.com/4564579/217974477-e9943f7c-d423-4a97-8c97-6b8aea3a2ab7.png)
