### ISSUE TITLE
Wiki has a bad URL for signing the CLA

### ISSUE THREAD

**Issue by AlexTalavari** [dotnet/roslyn#30769]
**Version Used**: 

**Steps to Reproduce**:

1.Open https://github.com/dotnet/roslyn/wiki/Contributing-Code 

**Expected Behavior**:
CLA link pointing to https://cla.dotnetfoundation.org/
**Actual Behavior**:
CLA link point to https://cla2.dotnetfoundation.org/

**Comment by jinujoseph** [comment]
Thanks for the report @AlexTalavari , this has been resolved
