### ISSUE TITLE
Error when using extension methods with "ref this" and T not enforced as struct

### ISSUE THREAD

**Issue by DeathArrow01** [dotnet/roslyn#30778]
**Version Used**: 
C# 7.2, Visual Studio 15.8.8

**Steps to Reproduce**:
```C#
public class ClassA
{
    public void Something() { }
}

public class ClassB
{
    public void Something() { }
}

public static class TestExtension  {

    public static T PassAnyType<T>(ref this T arg) 
    {
        switch(arg)
        {
            case string s:
                s = "Test Message";
                break;
            case int i:
                i++;
                break;
            case ClassA a:
                a.Something();
                break;
        }

        return arg;
    }

    public static T PassReferenceType<T>(ref this T arg) where T: class
    {
        switch (arg)
        {
            case ClassA a:
                a.Something();
                break;
            case ClassB b:
                b.Something();
                break;
        }

        return arg;
    }
}
```
**Expected Behavior**:
The code should be allowed to compile.

**Actual Behavior**:
error CS8337: The first parameter of a 'ref' extension method 'PassReferenceType' must be a value type or a generic type constrained to struct.
error CS8337: The first parameter of a 'ref' extension method 'PassAnyType' must be a value type or a generic type constrained to struct.

**Comment by jhinder** [comment]
That's intentional: `ref` extensions are only allowed on struct types. The reasons are explained in the [language feature proposal](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/readonly-ref.md#refin-extension-methods).

**Comment by jaredpar** [comment]
This behavior is "By Design" as noted by @jhinder
