### ISSUE TITLE
C# Safe Navigation do not Call Operator Overloading for "!=" or "=="

### ISSUE THREAD

**Issue by hknielsen** [dotnet/roslyn#30781]
Based on the SharpLab
https://sharplab.io/#v2:CYLg1APgAgDABFAjAbgLACgNQMwIExwAqApgM4AuAcgK4A2tA3hgJA4KLykDK5ATnAwDmxcslIjkAXwzTM6NlAIBhARjjqNcNRoUAWOAFkAFAEpV6TZpIUa9OOTJU6tOAF44AO2doLl9QDcAQ34KfncHG2cAfgA6bj4fP3VtPwinO3DHWxcoqM9iAHciLOdTRI1ZSSA=

And Docs. It seems like the ?. operator should behave 1:1 as checking for null manually.
It seems not to be the case.
Overloading operators will not be called, and it seems like they should from all the manuals and docs that explains that it's the same, just shorter.

I also can't find any information in ECMA standard, or the C# 6 Draft
http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-334.pdf

Looking in the IL I can see that the Operation Overload function is not injected when using the ?. operator. Even though that the basic IL basically do a `!=`

**Expected Behavior**:
I would expect the overloading Operator being called.

**Actual Behavior**:
No overloading Operator being called.

**Comment by svick** [comment]
The latest version of the ECMA standard describes C# 5.0, so you won't find information about C# 6.0 operators there.

But [the C# 6.0 draft spec does explain the behavior](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#null-conditional-operator):

> The null-conditional operator applies a list of operations to its operand only if that operand is non-null.

Note that it says nothing about calling an overloaded operator, what matters is if the value is actually `null`. The following paragraphs of the spec make this more explicit by comparing with null using `(object)P != null`, where the cast to `object` ensures no overloaded operators are called.

So, I think there is no issue in the compiler. But if the existing documentation lead you to believe the behavior should be different, then there might be an issue in the documentation. Could you point to the parts of the official documentation that made you think it behaves this way?

**Comment by svick** [comment]
> And what Sharplab.io spits out.

[If you use a type that does overload `==`, it shows that the overloaded operator is not used.](https://sharplab.io/#v2:CYLg1APgAgzABFATHAKgUwM4BcByBXAGwIG8BYAKAEhYEBGABjgwGUsAnOYgczSwG4MvPgF8KccXDESaUWgDY4AIwD2ygnGUAHNGwCGWZWwC8RgBTps+InAAeAGlSZchdQE8AlHCMA+OOzxofFLiMvJKqupaOvqGAIRmFs7W9o6WLnAeXr4AZroEgkHkouQUMsgAwpzBEpLkNTIALHAAsqaeZHU1EolW6lhOvV5wAHYuhV0SAG66HNgcRn4DLgD8AHQs7OMSxcJAA===)

> it multiple places says its the same as you doing null checking your self

But if your type overloads `==`, then `x == null` is not null checking anymore. In that case, if you wanted to perform null checking yourself, you would have to use `(object)x == null`, `object.ReferenceEquals(x, null)` or `x is null`. As far as I can tell, it never says it's exactly the same as writing `x == null` yourself.

**Comment by hknielsen** [comment]
Thanks for clearing it up
