### ISSUE TITLE
Can't modify the code at the time of debugging ( in .net core) like it supported in .net framework.

### ISSUE THREAD

**Issue by anirudhagupta** [dotnet/roslyn#30789]
I have this issue from months, When I was debugging .net framework console application I can modify the .net framework code and continue to code.
now in .net core, I can't do that. for example, take a look, I just add one line and it stops working. Am I missing something here or this is a known issue.

![image](https://user-images.githubusercontent.com/35772421/47582640-8bd08d80-d972-11e8-9651-bebf3abe39f1.png)

**Comment by jinujoseph** [comment]
cc @tmat
