### ISSUE TITLE
Make Indenter public

### ISSUE THREAD

**Issue by jrieken** [dotnet/roslyn#3079]
For OmniSharp it would be a big bonus to have something like the `Indenter` public: http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp.EditorFeatures/Formatting/Indentation/CSharpIndentationService.Indenter.cs,93877f82bd311eb9. Similar to the `Formatter` or `Renamer` in CodeAnalysis.Workspaces.

**Comment by Pilchie** [comment]
Can you take a look?  IIRC, Indenter depends a bunch on the editor APIs.

**Comment by CyrusNajmabadi** [comment]
@jrieken can omnisharp use the [ISmartIndent](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.editor.ismartindent?view=visualstudiosdk-2019) interface?  We do export that through MEF.

**Comment by jrieken** [comment]
🤷‍♂ I haven't look at omnisharp in the last couple of years..

**Comment by JoeRobich** [comment]
OmniSharp could have access to the indenter through their ExternalAccess library now that it has moved into the Features layer.

**Comment by CyrusNajmabadi** [comment]
Closing out.  There are ways to access this if necessary.  We would only make thsi public going through the API propsoal process.
