### ISSUE TITLE
Move to File not behaving as expected

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#30793]
**Version Used**: 2.11.0-beta1-63422-04+98737be0c4177d8acd850537dac5be6e36774dd7

**Steps to Reproduce**:

1. Create a new desktop C# Class Library
2. Append `public class Stuff { }`
3. Move the cursor to "Stuff" and apply the move-to-file refactoring

**Expected Behavior**:

1. Class Stuff is moved to Stuff.cs
2. Class1.cs is dirty
3. Stuff.cs is open and focused

**Actual Behavior**:

1. Class stuff is moved to Stuff.cs (good)
2. Class1.cs is not dirty (undo brings back the text but it remains not-dirty)
3. Stuff.cs is not open

**Comment by amcasey** [comment]
Playing with the undo stack in the not-dirty file (Class1.cs) can freeze the UI thread.

**Comment by CyrusNajmabadi** [comment]
> Stuff.cs is not open

This is very much by design.  Our refactorings explicitly do not move to the new code. This is to help the general pattern of someone working in some code and doing a bunch of cleanup/refactoring steps.  We don't want to jump them to those locations, forcing them to jump back.

**Comment by CyrusNajmabadi** [comment]
> Class1.cs is not dirty (undo brings back the text but it remains not-dirty)

I believe this is a limitation of the 'global undo' system (which we use because we're making multiple edits).  When it performs it's action, files are saved.  I believe you'll see this with things like 'rename' as well.  If you rename a variable, affected files (even the open ones) aren't in the dirty state.  The changes are made to them and persisted.  AFAIK, this is a VS limitation.  But maybe @jasonmalinowski can shed some more light here.

**Comment by amcasey** [comment]
> Stuff.cs is not open
I'll have to investigate.  In implemented the functionality in TS because I saw code that did it for C#.  However, I see that it doesn't happen in practice.

> Class1.cs is not dirty (undo brings back the text but it remains not-dirty)

I find it confusing that it's is non-dirty both before and after undo but it's been like that since at least 15.6.

**Comment by amcasey** [comment]
This is the code I was thinking of: http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/CodeActions/CodeActionEditHandlerService.cs,263

**Comment by CyrusNajmabadi** [comment]
You don't have to necessairly close yet :)   Jason may have some undo ideas for all we know :)

**Comment by amcasey** [comment]
It's not a regression and the behavior is by design, so I don't think there's anything left to do.

**Comment by jasonmalinowski** [comment]
Late, but yeah, my gut is saying @CyrusNajmabadi is right and it's probably global undo. We do a global undo transaction for all lightbulb applications _unless_ it's a single source edit in a single file, so this probably isn't new.
