### ISSUE TITLE
Blocker: Project.Documents.Count() returning 0 for most of C# code bases suddenly

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#30792]
**Version Used**: 
2.9.0
**Steps to Reproduce**:

1. We are trying to get the SemanticModel for a document which is part of a .csproj project (Sample.csproj). This .csproj in turn is part of a .sln solution which has multiple .csproj's.
2. For getting the SementicModel, the code first opens the .csproj and then brows through each document of the Project object using below code:
```
using (var workspace = MSBuildWorkspace.Create())
{
         Project currentProject = workspace.OpenProjectAsync(projectPath).Result;
          workspace.LoadMetadataForReferencedProjects = true;
          workspace.WorkspaceFailed += OnWorkSpaceFailed;

          if (project.Documents.Any())                
         {
	       foreach (var document in project.Documents)
               {
                      SemanticModel sementicModel = document.GetSemanticModelAsync().Result;
               }
	 }
 }
```
3. The machine on which this code runs has Visual Studios 2017 Build Tool installed with loads for .NET Standard, .NET Core SDK, .NET 4 t0 .NET 7.2 frameworks etc. The tool has been installed on this machine around 4-5 months back.  The then version of Roslyn then was 2.7.0. 
4. The above code use to work all well on the said machine. 2 days back we had a requirement of deploying the same application  on another machine. So we installed VS 2017 Build tool on that machine along with the exact same loads which we had added for the earlier machine's VS 2017 Build tools installation. 
5. After setting up this new machine and running our application on it for sample .Net projects, suddenly the Documents.Count() returns 0 always for most of the projects which were running all good earlier. 
We also assumed that may be updating Roslyn version to 2.9.0 might resolve this issue. But upgrading Roslyn version has not helped either. 
6. Looks like some thing has changed in the VS 2017 Build tool installation which has failed the  OpenProjectAsync functionlity.
7. Also. the WorkscapeFailed event hooked does not get fired in any projects on this new machine. So we are not getting any kind of information on this sudden behavior.
8. We have also tried setting 4 more machines by installing VS 2017 Build tool on them with all the same settings. But the above strange behavior is common across. 
9. For getting a quick feedback, I have uploaded  the code which opens the csproj and checks for documents count at following location: https://www.dropbox.com/sh/6bog8n56iosg1z5/AABi-MBuqpuB1_OwqJ3wZFKya?dl=0. 

**Expected Behavior**:
Documents.Count() for Project should return valid count similar to what it returns on the existing machine.

**Actual Behavior**:
Documents.Count() for Project returns 0 for all the projects which return valid count on the earlier machine set 4-5 months back

An urgent help will be very very helpful.

**Comment by jmarolf** [comment]
1. You do not seem to be registering an MSBuild instance like is done [here](https://github.com/dotnet/roslyn-sdk/blob/ce35be575b079d12cbe21b6b8fa9c45a5a82d697/src/Templates/VS2017/ProjectTemplates/CSharp/ConsoleApplication/Program.cs#L34) which could lead to problems with your code populating the workspace.
2. You register for the workspace events *after* they have already fired.

What happens for the following code in your project? (Note: you will need to add nuget package `Microsoft.Build.Locator`)
```C#
// Attempt to set the version of MSBuild.
var instance = MSBuildLocator.QueryVisualStudioInstances().Single();
Console.WriteLine($"Using MSBuild at '{instance.MSBuildPath}' to load projects.");

// NOTE: Be sure to register an instance with the MSBuildLocator 
//       before calling MSBuildWorkspace.Create()
//       otherwise, MSBuildWorkspace won't MEF compose.
MSBuildLocator.RegisterInstance(instance);

using (var workspace = MSBuildWorkspace.Create())
{
    workspace.LoadMetadataForReferencedProjects = true;
    // Print message for WorkspaceFailed event to help diagnosing project load failures.
    workspace.WorkspaceFailed += (o, e) => Console.WriteLine(e.Diagnostic.Message);

    Project currentProject = workspace.OpenProjectAsync(projectPath).Result;
    if (project.Documents.Any())
    {
        foreach (var document in project.Documents)
        {
            SemanticModel sementicModel = document.GetSemanticModelAsync().Result;
        }
    }
 }
```

**Comment by abhijitparkhi1983** [comment]
@jmarolf and @DustinCampbell 

Thanks for the inputs. I tried using your suggestion in the sample code that i have shared at https://www.dropbox.com/sh/6bog8n56iosg1z5/AABi-MBuqpuB1_OwqJ3wZFKya?dl=0.

But this has not given me any luck. The console just prints following info:

2018-10-27 04:23:43,743 INFO RoslynWalker: Using MSBuild at 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin' to load projects.
2018-10-27 04:23:46,727 INFO RoslynWalker - Project Name: isserverplusconnector .Project Document Count: 0
2018-10-27 04:23:46,751 INFO RoslynWalker - Project Name: isserverplusconnector.test .Project Document Count: 0
2018-10-27 04:23:46,775 INFO RoslynWalker - Project Name: modulename .Project Document Count: 0
2018-10-27 04:23:46,790 INFO RoslynWalker - Project Name: modulename.externalinterface .Project Document Count: 0
2018-10-27 04:23:46,806 INFO RoslynWalker - Project Name: modulename.internalinterface .Project Document Count: 0
2018-10-27 04:23:46,822 INFO RoslynWalker - Project Name: modulename.ps .Project Document Count: 0
2018-10-27 04:23:46,842 INFO RoslynWalker - Project Name: modulename.ps.test .Project Document Count: 0
2018-10-27 04:23:46,857 INFO RoslynWalker - Project Name: modulename.test .Project Document Count: 0
2018-10-27 04:23:46,873 INFO RoslynWalker - Project Name: is_service_manager .Project Document Count: 0
2018-10-27 04:23:46,889 INFO RoslynWalker - Project Name: is_service_runner .Project Document Count: 0

For some projects i also get following error in the WorkspaceFailed event: 

..\modulename.externalinterface\modulename.externalinterface.csproj
Msbuild failed when processing the file '..\modulename.externalinterface\modulename.externalinterface.csproj' with message: The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries(.NETFramework, v4.5, '', '')" cannot be evaluated. Object reference not set to an instance of an object.  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets

And then it still gives 0 documents. 

FYI: If i run the same app on the older machine where VS 2017 Build tool was installed 5-6 months back, we get valid documents count. 

Please let me know what else should i look at. Its pretty urgent. Its a blocker on my end and i am completely clueless on what exactly is happening.

**Comment by abhijitparkhi1983** [comment]
@jmarolf and @DustinCampbell any help that you can offer please ?

I also tried logging the firstchanceexception which gives following error:

```
System.TypeInitializationException: The type initializer for 'BuildEnvironmentHelperSingleton' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance()
   at Microsoft.Build.Shared.NativeMethodsShared.get_IsMono()
   at Microsoft.Build.Utilities.ToolLocationHelper.ChainReferenceAssemblyPath(String targetFrameworkDirectory)
   at Microsoft.Build.Utilities.ToolLocationHelper.GetPathAndChainReferenceAssemblyLocations(String targetFrameworkRootPath, FrameworkName frameworkName, Boolean chain)
   at Microsoft.Build.Utilities.ToolLocationHelper.GetPathToReferenceAssemblies(String targetFrameworkRootPath, FrameworkName frameworkName)
   at Microsoft.Build.Utilities.ToolLocationHelper.GetPathToReferenceAssemblies(FrameworkName frameworkName)
   at Microsoft.Build.Utilities.ToolLocationHelper.GetPathToReferenceAssemblies(String targetFrameworkRootPath, String targetFrameworkFallbackSearchPaths, FrameworkName frameworkName)
   at Microsoft.Build.Utilities.ToolLocationHelper.GetPathToReferenceAssemblies(String targetFrameworkIdentifier, String targetFrameworkVersion, String targetFrameworkProfile, String targetFrameworkRootPath, String targetFrameworkFallbackSearchPaths)
   at Microsoft.Build.Utilities.ToolLocationHelper.GetPathToStandardLibraries(String targetFrameworkIdentifier, String targetFrameworkVersion, String targetFrameworkProfile, String platformTarget, String targetFrameworkRootPath, String targetFrameworkFallbackSearchPaths)
   at Microsoft.Build.Utilities.ToolLocationHelper.GetPathToStandardLibraries(String targetFrameworkIdentifier, String targetFrameworkVersion, String targetFrameworkProfile, String platformTarget)
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance()

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance()
```

But I am not sure if this error will give any more insight.

**Comment by abhijitparkhi1983** [comment]
Hello team Roslyn,

The issue got resolved for me in a weird way which has been detailed by @DustinCampbell at https://github.com/FizzerWL/ErrorRepro/pull/1.

For any one who comes across this issue, following were the things which I had to do:

After removing the Microsoft.Build.* , the application stared working again. But removing them was not enough. I had to update Roslyn version to the latest version 2.9.0 (which was 2.7.0 earlier). 

The earlier code was using Microsoft.Build.Locator package already using code ` MSBuildLocator.RegisterDefaults();` But it is not sufficient for fixing this issue. Instead we have to use below code:

```
var instance = MSBuildLocator.QueryVisualStudioInstances().Single();
MSBuildLocator.RegisterInstance(instance);
```

The only hitch is, I had to write a post-build script for removing Microsoft.Build.dll and Microsoft.Build.Framework.dll using below code:

```
del Microsoft.Build.dll /Q /S
del Microsoft.Build.Framework.dll /Q /S
```

@DustinCampbell , is there any way in which this can be handled ?

**Comment by jmarolf** [comment]
@abhijitparkhi1983 can this solution build on the machine that you've deployed your tool to?  If you cannot run `msbuild isserverplusconnector.csproj` successfully on this machine then there is no hope of the MSBuild workspace being able to load it, as it is using msbuild behind the scenes.  Looking at your project on dropbox I would recommend not creating a new workspace for each project you are trying to load, instead do this:

```C#
static void Main(string[] args)
{
    try
    {
        // Attempt to set the version of MSBuild.
        var instance = MSBuildLocator.QueryVisualStudioInstances().Single();
        Console.WriteLine($"Using MSBuild at '{instance.MSBuildPath}' to load projects.");

        // NOTE: Be sure to register an instance with the MSBuildLocator 
        //       before calling MSBuildWorkspace.Create()
        //       otherwise, MSBuildWorkspace won't MEF compose.
        MSBuildLocator.RegisterInstance(instance);

        //Change this path as per required.
        string[] projectsToParse =
            Directory.GetFiles(args[0], "*.csproj", SearchOption.AllDirectories);

        using (var workspace = MSBuildWorkspace.Create())
        {
            workspace.LoadMetadataForReferencedProjects = true;
            // Print message for WorkspaceFailed event to help diagnosing project load failures.
            workspace.WorkspaceFailed += (o, e) => Console.WriteLine(e.Diagnostic.Message);

            Console.WriteLine("Projects to Parse: " + projectsToParse);
            foreach (var currentFile in projectsToParse)
            {
                Console.WriteLine("Project: " + currentFile);
                BrowseProjectsToParse(workspace, currentFile);
            }
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.StackTrace);
    }
}
```

**Comment by CyrusNajmabadi** [comment]
@abhijitparkhi1983 Does this still repro for you?

**Comment by abhijitparkhi1983** [comment]
Ohh yes it had worked. Sorry i should have closed the issue in time .Thanks to the team
