### ISSUE TITLE
Tests in PropertySubpatternCompletionProviderTests fail when LanguageVersion != 8.0

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#30794]
Many tests in `PropertySubpatternCompletionProviderTests` do not work when the language versions is not 8.0. Since the default language version is less than 8, they fail by default.

Also some tests in `GenerateVariableTests`, which are skipped with this URI.

**Comment by gafter** [comment]
@CyrusNajmabadi Could you please have a look at this? I don't understand the way these tests work well enough to know why they still fail after I unskip them given that the default language version is now 8.0.

**Comment by CyrusNajmabadi** [comment]
sure.  assigning to myself.
