### ISSUE TITLE
"Add using" code fix mis-sorts between namespaces sharing a prefix

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#3080]
Roslyn's Add Using code fix adds the new statement with a sort order inconsistent with the Sort Usings refactoring.

Consider a C# console application with this source code:

```csharp
namespace Microsoft.MyApp
{
    using Win32;

    class Program
    {
        static void Main(string[] args)
        {
            SafeRegistryHandle h;
        }
    }
}
```

Position the caret at the `SafeRegistryHandle` line and execute the add using code fix. This changes the using statements at the top to be:

```csharp
    using Win32.SafeHandles;
    using Win32;
```

But this sort order is incorrect. And Roslyn knows it, because then if you execute a Sort Usings command you get the right sort order:

```csharp
    using Win32;
    using Win32.SafeHandles;
```

This repros on VSPro_Platform 22915.00

Note in my experimentation this relies on the `using` statements appearing within a namespace block that starts with `Microsoft` (since `Win32` is shorthand for `Microsoft.Win32`). So in general I think when short-hand namespaces are specified due to overlap with the containing namespace block, that "add using" sorts incorrectly.

**Comment by jmarolf** [comment]
@dpoeschl could you verify please?
