### ISSUE TITLE
Automatically inserted "using" statement always placed outside of namespace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30811]
In our team, we follow StyleCop's advice to place using statements inside the namespace.

In VS2015, when auto-adding a new using statement, it was placed alongside the others.
In VS2017, though, it's always placed outside the namespace, requiring us to perform a manual move.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/112990/automatically-inserted-using-statement-always-plac.html
VSTS ticketId: 494544_
_These are the original issue comments:_

Candy Zhang [MSFT] on ‎9‎/‎14‎/‎2017, 04:02 AM (407 days ago): <p>Thank you for your feedback. We are evaluating the impact of this issue and will determine its priority from further customer impact. Thank you for helping us build a better Visual Studio.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by JoeRobich** [comment]
I tried various scenarios trying to reproduce this issue in VS 15.8.9

✔️ Passing: When a Using is within the namespace, AddImport tries to add using within the Namespace.
```csharp
using System.Collections.Generic;

namespace Test
{
    using System;

    public class C
    {
        Task t;[||]
    }
}
```

✔️ Passing: When a Static Using is within the namespace, AddImport tries to add using within the Namespace.
```csharp
using System.Collections.Generic;

namespace Test
{
    using static System.Math;

    public class C
    {
        Task t;[||]
    }
}
```

❌ Failing: When a Using Alias is within the namespace, AddImport tries to add using in the CompilationUnit.
```csharp
using System.Collections.Generic;

namespace Test
{
    using SAction = System.Action;

    public class C
    {
        Task t;[||]
    }
}
```

The code responsible for choosing the correct Using container to add into is choosing to prefer the container with an existing Using over the container with an existing Using Alias on line 87.
https://github.com/dotnet/roslyn/blob/23e981bcbea4b68258ce3a4e9ac047cb6d6bfe05/src/Workspaces/Core/Portable/AddImports/AbstractAddImportsService.cs#L78-L91

**Comment by sharwell** [comment]
@JoeRobich Without the new usings placement feature, it seems like we should choose the innermost location containing a using directive of the same kind (normal, alias, or static), and if none matches then choose the innermost location of any kind.

**Comment by JoeRobich** [comment]
@sharwell In that case it is the middle scenario (using static) that is broken because `GetImportContainer` doesn't draw a distinction between regular and static using directives when choosing a container.

I tested with each scenario with no using directive in the compilation unit and it correctly tried to add the using to the namespace.

**Comment by jinujoseph** [comment]
note: https://stackoverflow.com/questions/15434846/adding-usings-inside-the-namespace
