### ISSUE TITLE
 `Ctrl + .` doesn't implement quick actions and refractoring

### ISSUE THREAD

**Issue by ranjan-ranjan** [dotnet/roslyn#30826]
**Version Used**: .Net Framework 4.7.2

**Steps to Reproduce**:

1. I am trying to get values from` app.config` in a WPF project
2. So, I have added reference to `System.Sonfiguration.Configurationsettings.Appsettings[""]`
3. This gives a warning and workaround
4. We can't use `Ctrl + .` to implement quick actions and refractoring
5. `Ctrl + .` should implement quick actions and refractoring
6. I have added snapshot as a reference
![change required](https://user-images.githubusercontent.com/16834561/47648972-b8b6b780-dba1-11e8-899f-c770044c0119.png)

**Expected Behavior**:
 `Ctrl + .` doesn't implement quick actions and refractoring

**Actual Behavior**:

 `Ctrl + .` should implement quick actions and refractoring

**Comment by sharwell** [comment]
📝 This is a request for a new code fix to update code reporting a warning for use of the following obsolete property:
https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationsettings.appsettings?view=netframework-4.7.2

**Comment by sharwell** [comment]
I'm tentatively marking this as **External**, but will confirm the resolution in a design review later today before closing it. API-specific analyzers and code fixes (such as this one for APIs in the System.Configuration assembly) are typically implemented either alongside the assembly itself or as part of the dotnet/roslyn-analyzers repository. Every code fix to update uses of an obsolete API must be created specifically for that API, so it's expected that many such APIs will not currently offer a fix. The message included with the warning should normally provide the information necessary to manually update the code.

**Comment by sharwell** [comment]
The IDE reports the warning for obsolete members as-written in the original source code. While the error in this case suggests a replacement API, it's not safe to assume that all obsolete members will have an error message of this form, nor is it safe to assume that the new API is a drop-in replacement for the obsolete API. Fixes may be written for these cases, but each of these fixes will typically be a one-off fix targeting a specific obsolete member or obsolete type. The fix would be implemented by the maintainers of the type which is marked obsolete, which for this case would be [dotnet/corefx](https://github.com/dotnet/corefx/). If you are interested in a code fix for this API, you can file a feature request on that repository with the details. 😄
