### ISSUE TITLE
Using prop shortcut to generate property in an interface includes access modifier

### ISSUE THREAD

**Issue by tokarzkj** [dotnet/roslyn#30835]
**Version Used**: 15.8.8

**Steps to Reproduce**:

1. Create an interface
2. Use the prop shortcut to generate a property

**Expected Behavior**:
The generated property should not include an access modifier when used within an interface

**Actual Behavior**:
The generated property has an access modifier and results in an error.

![propinterface](https://user-images.githubusercontent.com/13357505/47687208-89aa4100-dbb5-11e8-8efd-75566b7abe52.gif)

**Comment by Joe4evr** [comment]
I wonder if it's actually worth "fixing" this, since having access modifiers on interface members will become legal soon anyway.

**Comment by tokarzkj** [comment]
@Joe4evr - I was unaware that this was becoming legal. I agree it probably makes more sense to leave as is then.

**Comment by Joe4evr** [comment]
Another thing to consider is that snippets can be inserted anywhere with no regard for surrounding context at all. Like outside of a namespace, where almost nothing is allowed. Given the assumed complexity that'd have to be involved in making snippets contextually aware, I don't see this changing anytime soon.

**Comment by CyrusNajmabadi** [comment]
This would be covered by semantics snippets now.  iff there's an issue with those, we can file an issue and fix there.
