### ISSUE TITLE
"Alias ambiguous type" order is inconsistent with "Fully qualify"

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#30838]
I'm seeing this right now:

![image](https://user-images.githubusercontent.com/11444821/47725223-74d2b980-dc58-11e8-876e-03708d970643.png)

![image](https://user-images.githubusercontent.com/11444821/47725228-77cdaa00-dc58-11e8-932c-61fdc94f8b6b.png)

In "Fully qualify", System.Threading.Tasks is first, but in "Alias ambiguous type", it's the second item. I would expect these to have the same order.

Small repro:
```c#
using System.Threading.Tasks;
using Microsoft.VisualStudio.Shell;

class C
{
    async Task M()
    {
    }
}

namespace Microsoft.VisualStudio.Shell
{
    class Task { }
}
```

**Comment by sharwell** [comment]
👍 Further, the order should account for the value of `dotnet_sort_system_directives_first`.
