### ISSUE TITLE
"Alias ambiguous type" should show up above "Fully qualify"

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#30839]
If there are no using statements, the code fix to add using always shows up above "Fully qualify":
![image](https://user-images.githubusercontent.com/11444821/47725683-44d7e600-dc59-11e8-865c-352267dd566d.png)

On the other hand, when the is an ambiguous type, the code fix to add using to disambiguate appears below "Fully qualify". In my opinion this code fix is analogous to the "Add using" code fix and should show up above too.

![image](https://user-images.githubusercontent.com/11444821/47725854-a0a26f00-dc59-11e8-99a4-4283330fe496.png)

```c#
using System.Threading.Tasks;
using Microsoft.VisualStudio.Shell;

class C
{
    async Task M()
    {
        await M();
    }
}

namespace Microsoft.VisualStudio.Shell
{
    class Task { }
}
```

**Comment by CyrusNajmabadi** [comment]
@sharwell @kendrahavens for telemetry-oriented question.  Between "fully qualify" and "alias ambiguous type", which is used more?  Thanks!

**Comment by Neme12** [comment]
"Alias ambiguous type" was just added recently. Isn't "fully qualify" much older? I think that will affect the usage.

**Comment by Neme12** [comment]
"Fully qualify" is the same code fix in both cases, whereas "Add using" and "Alias ambiguous type" are different ones. We need the telemetry for cases where both "Fully qualify" and "Alias ambiguous type" appear in the list.

**Comment by sharwell** [comment]
I tend to agree with consistency here. I've long wanted the ability to add using alias directives, but they simply weren't available through the menu. I'll add this to our design review for next Monday.

**Comment by CyrusNajmabadi** [comment]
Fully qualify is picked 10x more often than Aliasing.  Keeping the order as is.
