### ISSUE TITLE
When keyword recommender failure with var patterns

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#30848]
A [recent change to the syntax](https://github.com/dotnet/roslyn/issues/29297) to support `var` patterns caused `WhenKeywordRecommenderTests` to fail in the `features/recursive-patterns` branch (during CI tests). They are skipped with this bug ID.

/cc @Neme12

**Comment by Neme12** [comment]
Can you please make a separate issue for the semantic classifier tests? I will send a PR to fix the recommender but not those.

**Comment by gafter** [comment]
@Neme12 Yes. This issue will be for `WhenKeywordRecommenderTests` only.

**Comment by gafter** [comment]
@Neme12 The skipped tests are now in `features/recursive-patterns`.

**Comment by Neme12** [comment]
Thanks, I'll submit a PR.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/30870
