### ISSUE TITLE
Hi!, I am wondering if you support .NET Standard 2.0?

### ISSUE THREAD

**Issue by learnersm** [dotnet/roslyn#30859]

**Comment by jhinder** [comment]
There is an open issue (#29601) to add .NET Standard 2.0 as a target framework. However, many packages already target .NET Standard 1.x today (e.g. [Microsoft.CodeAnalysis.CSharp](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.csproj#L10)), which you can reference from a .NET Standard 2.0 project.

**Comment by learnersm** [comment]
Thanks a lot for the clarity @jhinder . Apologies for the inconvenience.

**Comment by khellang** [comment]
You might be interested in https://github.com/dotnet/roslyn/pull/30914
