### ISSUE TITLE
Enums completion in XML comments includes a "default" constructor

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#30858]
**Steps to Reproduce**:

1. Show completion at $

``` C#
using System; 

internal class Program
{
    /// <summary>
    ///  <see cref="DayOfWeek.$"/>
    /// </summary>
    private static void Main(string[] args)
    {
    }
}

```

**Expected Behavior**:
No default constructor listed, similar to usage within the body of a member.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/1103906/47759987-4dd2c100-dd06-11e8-9403-1f2d5017f8c0.png)

**Comment by jhinder** [comment]
While `new EnumType()` is certainly unusual (as it's essentially equivalent to `default(EnumType)`), it's perfectly valid.

> No default constructor listed, similar to usage within the body of a member.

You never get offered constructors in that completion list, because you don't invoke them that way.

I don't really see why we should treat enums any different from other struct types in this regard.

**Comment by davkean** [comment]
Jan, notice that Equals/GetHashCode/ReferenceEquals aren't offered either? Enums are and have always been treated specially.

**Comment by jhinder** [comment]
Equals/GetHashCode/ToString are only offered if the type overrides them. ReferenceEquals is only provided as a member of `object`.

I don't see how enums are treated specially, w.r.t. the cref completion list.

![barestruct](https://user-images.githubusercontent.com/823398/47784064-cd5f9080-dd04-11e8-9d5a-2d83dbfe49c4.png)

![expl-impl-2](https://user-images.githubusercontent.com/823398/47784123-f7b14e00-dd04-11e8-9c72-eeac0334ccf3.png)

![refeq-1](https://user-images.githubusercontent.com/823398/47784252-51b21380-dd05-11e8-93f8-1cb436458d30.png)

**Comment by sharwell** [comment]
The following is a valid use of a `<see>` element in a documentation comment (will compile without warnings to reference a code member that exists):

```xml
<see cref="DayOfWeek.DayOfWeek"/>
```

Per a prior design decision, IntelliSense should show valid items in completion lists even if those elements are unlikely to be used.

📝 @jhinder is correct about `Equals`/`GetHashCode`. `cref` attribute values do not resolve inherited members.

**Comment by davkean** [comment]
@sharwell By completion list, you mean only `<see cref` construct or anywhere? That's not a true statement either way, Clearly `DayOfWeek.DayOfWeek` does not show up in a method body, nor do internals or privates of non-accessible types in `<see cref` despite them being validly referenced.

**Comment by sharwell** [comment]
The precedent was established during a design review of #15205. If you find other discrepancies, they can be filed as separate bugs.

**Comment by davkean** [comment]
Are you referring to normal completion or `<see cref`?

**Comment by sharwell** [comment]
To date I have not seen a distinction made between the two, so I would say both.

**Comment by davkean** [comment]
Do a normal completion of an enum/delegate, what shows up?
