### ISSUE TITLE
VB intellisense doesn't show "color color" cases

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3086]
As per the screenshot below, VB completion list isn't showing static members off of an instance, even though the "color color" rule lets the compiler happily consume them.

![intellisense-vb-color-color](https://cloud.githubusercontent.com/assets/3316258/7817986/9a851f6c-038d-11e5-8dd6-bbf646254203.png)

WHAT I EXPECT: completion list should show Y.
WHAT I GET: it doesn't.

This repro shows a const member "Y". The same bug also manifests for *shared* members in class C.

**Comment by gafter** [comment]
Filing against the IDE, though I suspect this is a result of the semantic model. If that is determined to be the case, please let us know which API is behaving this way as redirect to the compiler team.

**Comment by Pilchie** [comment]
@rchande can you take a look and route if necessary?

**Comment by rchande** [comment]
@gafter Is there any reason to believe that the behavior of LookupSymbols has changed recently? If not, this looks like it may simply be a very old IDE bug.

**Comment by rchande** [comment]
@Pilchie @DustinCampbell I fixed this and actually broke a test asserting the behavior. Do you remember why we did this?

```VB
<Fact, Trait(Traits.Feature, Traits.Features.Completion)>
        Public Sub NoSharedMembers()
            Dim test = <Text>
Class C
    Sub M()
        Dim s = 1
        s.$$
    End Sub
End Class
</Text>.Value

            ' This is an intentional change from Dev12 behavior where constant
            ' field members were shown
            VerifyItemIsAbsent(test, "MaxValue")
            VerifyItemIsAbsent(test, "ReferenceEquals")
        End Sub
```

**Comment by ljw1004** [comment]
@rchande I wonder if there are two separate issues?

(1) In "non color-color" cases it should NOT show constants.
(2) In "color color" cases it SHOULD show constants.

I wonder if the intentional change from Dev12 was to fix (1), but it accidentally threw out (2) as well?

**Comment by Pilchie** [comment]
@ljw1004 is right (though it applies to all `Shared` members, not just constants).

**Comment by rchande** [comment]
@Pilchie @ljw1004 Sounds good, I'll make sure both cases work.

**Comment by rchande** [comment]
@ljw1004 Could you verify this?

**Comment by rchande** [comment]
Verified.
