### ISSUE TITLE
try to figure out view roles we want to set on preview views

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30883]
right now, we set these

http://index/?leftProject=Microsoft.CodeAnalysis.EditorFeatures.Wpf&leftSymbol=jqbc8ze4eo3i&rightProject=Microsoft.VisualStudio.LanguageServices&file=Implementation%5CFindReferences%5CEntries%5CDocumentSpanEntry.cs&line=143

but this brings in features like highlight current line. we should clean up around here. we might just make all our adornment/taggers/fontandcolor to support preview role and only set preview role for preview view.

**Comment by jcansdale** [comment]
👋 Thanks for the ping @sharwell 

I've put my spelunking up here:
https://github.com/jcansdale/SnippetColorizer

I'm interested to know how create a temporary `ProjectInfo` for your preview views. At the moment I'm using reflection to call `MiscellaneousFilesWorkspace.CreateProjectInfoForDocument`, which isn't great. 😉

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
