### ISSUE TITLE
"Private members is unused" fires on ShouldSerializeXXX pattern

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#30887]
#### Repro steps

``` VB
        <VBDescription(My.Resources.Microsoft_VisualStudio_Editors_Designer.ConstantResourceIDs.PPG_WebReferenceNameDescription)>
        <MergableProperty(False)>
        <HelpKeyword("Folder Properties.FileName")>
        Public Property Name() As String
            Get
                Try
                    Return _projectItem.Name
                Catch ex As Exception When Common.ReportWithoutCrash(ex, NameOf(Name), NameOf(WebReferenceComponent))
                    Return String.Empty
                End Try
            End Get
            Set(value As String)
                _projectItem.Name = value
                _page.OnWebReferencePropertyChanged(Me)
            End Set
        End Property

        ' Prevent using Bold Font in the property grid (the same style as other reference)
        Private Function ShouldSerializeName() As Boolean
            Return False
        End Function
```
#### Expected behavior
No warning on ShouldSerializeName()

#### Actual behavior
Severity	Code	Description	Project	File	Line	Suppression State
Message	IDE0051	Private member 'WebReferenceComponent.ShouldSerializeName' is unused.	Microsoft.VisualStudio.Editors	E:\project-system2\src\Microsoft.VisualStudio.Editors\PropPages\WebReferenceComponent.vb	41	Active

ShouldSerializeXXX is a pattern used by controls & things that show up in the property grid that determines whether they are written to InitializeComponent for a WinForms component. The associated FxCop original rule has an exclusion for this.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/31036
