### ISSUE TITLE
add ReferenceLocationDescriptor json converter

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30888]
right now ReferenceLocationDescriptor lists all members as primitive types for simple default json conversion. 

use json converter so that we can put custom types that group info together rather than list all as primitive types.

**Comment by sharwell** [comment]
🔗 Also related to https://github.com/dotnet/roslyn/pull/30733#discussion_r229404908

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
