### ISSUE TITLE
Switch statement should be simplified by using commas to separate cases, using braces to drop the break statement and support types [c#]

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#30897]
[View developer community](https://developercommunity.visualstudio.com/content/idea/369109/switch-statement-should-be-simplified-by-using-com.html)

Use braces to enclose statements for each case and drop the break statement. 
Use comma to separate options for a single case. 
Automatically indent and align the cases, and statements. 
Add support for types inside switch statements.

	switch (e.Property.Name)
            {
                case nameof(Session.CurrentServer): 
                case nameof(Session.CurrentUser):   RebuildAll(); break;
                case nameof(Session.CurrentModule): RebuildModules(); break;
                case nameof(Session.CurrentEntity): RebuildEntity(); break;
            }
becomes

	switch (e.Property)
        case Session.CurrentServer,
             Session.CurrentUser    { RebuildAll(); }
        case Session.CurrentModule  { RebuildModules(); }
        case Session.CurrentEntity  { RebuildEntity(); }

**Comment by Neme12** [comment]
@jinujoseph It looks like this is a request for a new language feature. I think it should be moved to https://github.com/dotnet/csharplang/

**Comment by jinujoseph** [comment]
This issue was moved to dotnet/csharplang#1977
