### ISSUE TITLE
don't lazily subscribe to an event but just do that up front

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30891]
https://github.com/dotnet/roslyn/pull/30733

here, VisualStudioProject._eventSubscriptionTracker is used to lazily subscribe to IDynamicFileInfoProvider.Update event. 

but rather than doing that, let's just subscribe to all changes up front and remove the tracking for lazy subscription.

https://github.com/dotnet/roslyn/pull/30733#discussion_r229471903

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
