### ISSUE TITLE
FakeSign and IBCMerge together break incremental build

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#309]
Repro steps:
1. cd Open\src\Compilers\Core\Portable
2. MSBuild /m /p:Configuration=Release
3. Repeat step 2.
Result:
Build fails with: 
  EXEC : error : The module D:\Roslyn\Open\src\Compilers\Core\Portable\obj\Release\Microsoft.CodeAnalysis.dll, already contains an IBC resource. [D:\Roslyn\Open\src\Compilers\Core\Portable\CodeAnalysis.csproj]

The problem is that the FakeSign step has modified the DLL after IBCMerge, thwarting the .timestamp file that each step writes out.

We need to come up with a technique so that multiple 'rewriters' can modify the binary and keep incremental builds working.

**Comment by pharring** [comment]
@jasonmalinowski Let's talk about this on Monday. Since the two tasks in question are both in VSL.Imports.Closed.targets, it's probably easy enough to coordinate.

**Comment by jasonmalinowski** [comment]
Hah. When I did the FakeSign changes I thought about this and figured nobody would ever have both happening at the same time. :-)

**Comment by pharring** [comment]
I'm working on a fix.
