### ISSUE TITLE
Add csharp_prefer_braces to .editorconfig

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#30908]
Roslyn expects braces to be used, including places where the language says they are optional. The .editorconfig setting for this is `csharp_prefer_braces`, but it's not currently set. ~~It should be added to .editorconfig with severity Warning.~~ (see https://github.com/dotnet/roslyn/issues/30908#issuecomment-435129541)

**Comment by Neme12** [comment]
This comment disagrees: https://github.com/dotnet/roslyn/pull/29853#discussion_r229117810, tagging @gafter

**Comment by Neme12** [comment]
Maybe it's different for compilers & IDE?

**Comment by sharwell** [comment]
The comment is technically correct (the best kind, right?). We should it to true:warning in the root .editorconfig, and override it to true:suggestion in src/Compiler/.editorconfig.

**Comment by sharwell** [comment]
In case anyone is wondering, the general guidelines that are *documented* were described coming up on four years ago now in https://github.com/dotnet/corefx/issues/381#issuecomment-69474542. However, despite being the "official" guidelines for Roslyn, code reviewers frequently request changes to code that follows the guideline. I'll review the state with the team to decide which of the following outcomes will hold:

1. We change the documented style for Roslyn and use .editorconfig to enforce it
2. We start reviewing code according to the documented style as opposed to the way things are going today

**Comment by sharwell** [comment]
➡️ After review, the setting closest to our documented guidelines without producing noise in cases where developers are allowed to omit braces is `true:silent`.

**Comment by Neme12** [comment]
@sharwell Does that mean omitting braces is allowed then? I know this is something that @CyrusNajmabadi always pushed back against.

**Comment by CyrusNajmabadi** [comment]
> ➡️ After review, the setting closest to our documented guidelines without producing noise in cases where developers are allowed to omit braces is true:silent.

IDE defacto guideline (for 20+ years) has been `true:error` TBH.  It has been strictly gated in PRs.  That this was not necessarily written down or enforced (since we only even had an in-IDE enforcement only very recently) isn't relevant to me.  We should not override defacto guidelines like this.  If it is necessary for defactor guidelines to be codified somewhere, then we should just do that.
