### ISSUE TITLE
Matching nullables with var pattern

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#30906]
**Version Used**: features/recursive-patterns

**Steps to Reproduce**:

```cs
using System;
class C {
    extern static (int, int)? Get();   

    static void Test() {
        if (Get() is var (x, y)) {
            Console.Write(x);   
            Console.Write(y);   
        }
    }
}
```

**Expected Behavior**: Should check for HasValue and deconstruct.

**Actual Behavior**: Error.

Note: should work for any deconstructible, not just tuples.
Note: in effect, this should be equivalent to the `(var x, var y)` pattern.

**Comment by Joe4evr** [comment]
> Note: in effect, this should be equivalent to the `(var x, var y)` pattern.

I'm not so sure, the `var` pattern is supposed to match everything, regardless of the value. Once we get those coveted Property patterns, this might naturally fall out of using the Empty Property pattern as a null-check:
```cs
if (Get() is {} (x, y))
{
    //code....
}
```

**Comment by alrz** [comment]
> the `var` pattern is supposed to match everything,

A var-pattern with a parenthesized designation cannot possibly match everything. Now, the current behavior comes from deconstruction assignment `var (x, y) = e;` (you can't deconstruct a nullable tuple). But since here we're talking about patterns (rather than mere deconstruction), we can actually fail the match on null.

>`if (Get() is {} (x, y))`

First off, this is an invalid pattern, unless x and y are constants. If you want to introduce variables you should use `var x` instead. The identifiers alone only work in a var-pattern, just like the example above.

Also you don't need to do `{}` when you're matching with a deconstruction pattern,
```cs
if (Get() is (var x, var y))
```
This check for null (if needed) and deconstruct into variables.

I believe the same behavior is expected with the shorthand form `var (x, y)`.

**Comment by alrz** [comment]
I think `new object() is var (x, y)` should match with `ITuple`, I suspect it would have the same fix.

**Comment by gafter** [comment]
Yes, `new object() is var (x, y)` should yield `false`.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/31056
