### ISSUE TITLE
Add code fix to replace default literal when used in C# 7.0 or lower

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#30909]
To fix the following error and corresponding errors for other language versions:
```c#
class C
{
    void M()
    {
        int i = default; // error CS8107: Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.
    }
}
```

It should replace the default literal with another literal, a default expression or a special member access, abiding by the same design as https://github.com/dotnet/roslyn/issues/30360#issuecomment-434462320

The easiest implementation of this would be to add the new supported error messages to the existing code fix, implemented in #30430. That can only be done after this compiler bug is fixed: #30384.

For future reference, this was partially implemented (just for generating default expressions) in #30359.

**Comment by CyrusNajmabadi** [comment]
Closing out.  It's not a goal to have features that are basically there only for converting to old-style constructs.
