### ISSUE TITLE
[EnC] Delta Metadata for C# anonymous type seems wrong

### ISSUE THREAD

**Issue by wschae** [dotnet/roslyn#3090]
* Create C# Console Application with the following code:
```
using System;

class Program
{
    static void Main(string[] args)
    {
        var v = new { A = 1 };
    }
}
```
* Update "A=1" to "A=10" and check the delta metadata for this update:

```
   TypeRef (0x01):
   ==============================================
      Scope                     Name  Namespace  
   ==============================================
   1: 0x23000003 (AssemblyRef)  #470  #45e       
   2: nil                       #3f9  nil        
   3: 0x23000003 (AssemblyRef)  #433  #45e  
```

The second entry seems wrong and it causes EE crashed when reading it.

**Comment by tmat** [comment]
@wschae I'll take a look.

**Comment by wschae** [comment]
Thanks! Note that you may need two edits to see this behavior.

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/commit/18f61a5712f5706c766a21f41b0cf03c2225d4b2

**Comment by wschae** [comment]
Verified using {1.0 (stable)-Signed-Release}\20150528.2
