### ISSUE TITLE
Upgrading LangVersion quick fix in a linked file checks out all files in the project

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#30901]
**Version Used**: VisualStudioPreview/15.9.0-pre.4.0+28219.56

**Steps to Reproduce**:

1. Have a solution under TFS control with two projects where one project (P1) has a linked file from the other project (P2).
2. Ensure everything is checked in.
3. My Source Control -> Environment settings are as follows:
![untitled](https://user-images.githubusercontent.com/10546952/47849634-555b9e00-ddca-11e8-9331-dda6dfb6c90e.png)
4. Edit the linked file in a way that requires a new language feature. You will be allowed to edit the file without cheking out. If you hit Save, you will be asked to check out the file.
5. Invoke the quick fix that updates the project language version.
6. You will be asked to check out the project that has the file as linked file (P1). Fair enough, I assume it's trying to upgrade all projects that use the file.

**Expected Behavior**: Only the csproj file gets checked out. Exactly as when you rename/add/delete a file and save the project.

**Actual Behavior**: Checking out the project causes _all files in the project_ to check out, you will be asked one by one.

**Comment by jinujoseph** [comment]
Looping @jasonmalinowski instead of Carol

**Comment by jasonmalinowski** [comment]
Indeed, we thought we fixed this.

**Comment by jasonmalinowski** [comment]
@miloush I've tried to reproduce this on current previews of Visual Studio 2019 which is where we would be targeting the fix. What type of projects were involved here? And for the linked file, when you opened it where you opening it from the project where the file "really" is or the one with the linked file?

If you're still able to reproduce it, I might ask you to send me a crash dump of the point where you're getting prompted.

**Comment by miloush** [comment]
Thanks Jason. This seems to be fixed in VisualStudio.16.Preview/16.0.0-pre.2.2+28602.52 (there are now separate quick fixes for this vs all projects and both behave as expected). Great!

**Comment by miloush** [comment]
Hm, I have just hit this on VisualStudio.16.Preview/16.1.0-pre.2.0+28822.285 (when choosing "this project"), is it possible there has been a regression?
