### ISSUE TITLE
Roslyn doesn't build from sources - missing NuGet packages

### ISSUE THREAD

**Issue by Jake456** [dotnet/roslyn#3091]
When executing `Src\.nuget\nuget restore Src\Roslyn.sln`, I get the following:

Unable to find version '1.0.0-rc3-20150510-01' of package 'Microsoft.Net.ToolsetCompilers'.
Unable to find version '1.0.0-rc3-20150510-01' of package 'Microsoft.Net.RoslynDiagnostics'.
Unable to find version '1.1.36' of package 'System.Collections.Immutable'.
Unable to find version '1.0.21' of package 'System.Reflection.Metadata'.

Tried with [latest](https://github.com/dotnet/roslyn/commit/5ad851b32367476829755d0ae2d89753235fbbe1) revision.

**Comment by Jake456** [comment]
I resolved this by enabling nuget.org (https://www.nuget.org/api/v2/) in the package sources list.

**Comment by dhusemann** [comment]
@Jake456 since vs2015 will have nuget v3. should it also build from v3, ??

**Comment by Jake456** [comment]
IMO it should. (To clarify, currently it doesn't.)

It seems like a broader comparability issue between Nuget's command line tool and the v3 API.
Various commands (like list & restore) no longer work; The api responds with `Bad Request (400)`.

I'm not a Nuget expert, but I think this can be solved by overriding the Machin's config in the solution's config, enabling the mentioned package source. (I enabled it at the machine level).
