### ISSUE TITLE
VB prettylister gets indent wrong for "End Sub" of a multiline lambda whose final line is a comment

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3092]
In VB, if I have a multiline lambda whose last line is a comment, then it gets the spacing of the final "End Sub" incorrect.

REPRO:
![vb-prettylist](https://cloud.githubusercontent.com/assets/3316258/7822413/2d533c72-03aa-11e5-8202-373493fd3996.png)

Look at the above code. Try typing in a space or two or three spaces in front of either "End Sub" line, and then cursor off.

WHAT I EXPECT: the End Sub should snap to directly underneath the "Sub".
WHAT I GET: the End Sub snaps back to the start of the line.

Note that this problem doesn't repro if you put in enough spaces to have the End Sub directly line up under the Sub. In that case the End Sub stays exactly where you put it.

This problem also doesn't repro if the final line of the sub isn't a multiline comment.

(I haven't tried to see what happens with empty lines).

**Comment by Pilchie** [comment]
Can you take a look?

**Comment by MattGertz** [comment]
Rejected 6/2 by ML Shiproom.
