### ISSUE TITLE
AddImports to support using alias?

### ISSUE THREAD

**Issue by pongba** [dotnet/roslyn#30943]
Currently ScriptOptions.AddImports only supports using namespaces and using static classes, I find it very useful if it can support using alias e.g. AddImports("SysRun=System.Runtime")

Reason for this is I have some old script in which they use some type names (from Globals object) I want to deprecate, but I don't want to add new methods to my interface to achive this (seems overkill and awkward to start a new version of interface or add new method *just* for this). 

All I really need is the equivalence of C++'s typedef so that I can (in the interface assembly) do:

```cpp
typedef NewShinnyTypeName OldDeprecatedTypeName;
class NewShinnyTypeName { ... }; // renamed from OldDeprecatedTypeName
```

However, the only language feature that comes close to this is C#'s using alias, but it's file-scoped, so even if I put the using OldDeprecatedTypeName=NewShinnyTypeName; inside a common.csx file and load it into the target csx, I still doesn't get to influence the target csx.

**Comment by pongba** [comment]
Never mind, even with this supported my requirement remains unmet, since I found out that C# using is a flawed construct in the first place - it doesn't even support composition, i.e.

using NameAddress = Tuple<string, string>;
using IDBook = Dictionary<string, NameAddress>;  // illegal

this truly, truly surprises me. 

This is why nobody is using the using anyways...

see rants here: https://stackoverflow.com/questions/161477/equivalent-of-typedef-in-c-sharp/51295920
and here: http://chrisoldwood.blogspot.com/2016/06/my-kingdom-for-c-typedef.html

We really need to fix the language construct first.

**Comment by CyrusNajmabadi** [comment]
dotnet/roslyn is not the right location for complaints about the language.  If you have a proposal on how to change the language, please file an issue over at: dotnet/csharplang.  Thanks!
