### ISSUE TITLE
Object IDs should preserve the leading '$' in the Locals window.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#3094]
After creating object IDs for some local variables (parameters to the current method), they appeared in the Locals window as `1` and `2` but should have appeared as `$1` and `$2` just like `$exception`.  See screenshot:
![objectid](https://cloud.githubusercontent.com/assets/926281/7823265/25ab9352-03af-11e5-836c-993606caf127.png)

**Comment by ManishJayaswal** [comment]
Adding a watch on these object IDs don't work either so the user will need to know to type $1 which is not a great experience.

**Comment by KevinH-MS** [comment]
Potential fix:  8641a39e129d7128bd3d7d00b46e09c8b2e1c106

Working on a solution that involves changing VIL to add the '$' so the EE can just pass it through...

**Comment by ManishJayaswal** [comment]
@KevinH-MS  @cston . Change on EE side looks pretty straight fwd so either solution is fine. If we pursue VIL change then it should be tested E2E before checking in change from either side.

**Comment by amcasey** [comment]
@brettfo, can you please verify?
