### ISSUE TITLE
[API request] ToDisplayParts() for constant values

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#30951]
Currently both `CSharp.SymbolDisplay` and `VisualBasic.SymbolDisplay` have a `FormatPrimitive` method thats returns a nice language-specific string representation of a value.

Usually it's the literal, but in cases where that's not possible it might be a non-language element (for example `double.PositiveInfinity` returns Infinity), or in case of VB even an invocation (`ChrW`) or a concatenation of string literals (for multiline strings, it's `"Hello" & vbCrLf & "World"`).

It would be nice to have a similar method that returns `SymbolDisplayPart`s rather than string. Properly splitting and tagging parts of the string is especially not a trivial task for VB. This is already implemented in `SymbolDisplayVisitor` for displaying constant values of field symbols, but this functionality is not exposed on its own:
https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Constants.cs
https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/SymbolDisplay/SymbolDisplayVisitor_Constants.vb

This API would be very useful for #30482

I'm not sure what a proper name would be, since the existing value formatter is called FormatPrimitive and the symbol formatting methods are ToDisplayString & ToDisplayParts. Something along the lines of FormatPrimitiveToDisplayParts? FormatPrimitiveParts? PrimitiveToDisplayParts? Or an overload of ToDisplayParts that takes a value?

**Comment by Neme12** [comment]
@jcouv @gafter Does this sound like a good API addition? Thanks.

**Comment by CyrusNajmabadi** [comment]
'PrimitiveToDisplayParts' seems reasonable to me looking at the existing public surface area of SymbolDisplay.

> Or an overload of ToDisplayParts that takes a value?

I'm personally not a fan of this because it seems too easy for people to mess things up and muddy that API.

The split between 'make a symbol into a set of display parts', versus take a constant-value and make a set of display parts seems worthwhile to me to have.

**Comment by Neme12** [comment]
@CyrusNajmabadi suggested in the PR that there should a type called SymbolDisplayConstantValueOptions - similar to the existing SymbolDisplayXOptions enums, instead of taking 2 boolean flags like the existing FormatPrimitive method does.

This would be useful because as described in https://github.com/dotnet/roslyn/pull/30482#discussion_r230891606, the currently proposed API don't allow us to get the equivalent behavior as  constant values of symbols returned from `ToDisplayParts`. That is because while there is a boolean flag to turn on/off hexadecimal numbers, it affects both literals for integer types as well as numbers inside VB `ChrW()`, whereas the current behavior of `ToDisplayParts` is to use decimal literals for integers and hexadecimal numbers inside `ChrW()` (which actually sounds like a good default). Having a new type with 3 options - use quotes, decimal/hexadecimal for numbers, decimal/hexadecimal for characters would be a nice solution and unify the behavior btween ToDisplayParts and FormatPrimitiveToDisplayParts.

**Comment by Neme12** [comment]
Additionally, he pointed out that because we might want to add support for binary literals as well in the future, a better approach instead of having a SymbolDisplayConstantValueOptions enum with members UseHexadecimalNumbers and UseDecimalCharacterValues (to change from the default to a different format), there should really be `enum NumberFormat { Decimal, Hexadecimal }` and SymbolDisplayConstantValueOptions would then have to be a struct/class containing `NumberFormat`s for numeric literals and character values. Apart from there having to be a new struct, this has an inconvenience that the default value for character literals would have to be decimal as well. Even if we extend all the default formats inside `SymbolDisplayFormat` to set hexadecimal as the default for character values, it would still technically be a breaking change because a custom `SymbolDisplayFormat` created from the constructor would still have decimal as the default for character values, while the current behavior is for those to be hexadecimal. Maybe this is not a big deal though because it only affects users creating their own `SymbolDisplayFormat` from scratch and only affects the display of numbers inside `ChrW` in VB.

@dotnet/roslyn-compiler Please advise. Which solution do you think is preferrable? Thanks.

**Comment by CyrusNajmabadi** [comment]
> Apart from there having to be a new struct, this has an inconvenience that the default value for character literals would have to be decimal as well.

This is not necessarily the case.  You could just have an enum value of "LanguageDefault".  This would allow each language to decide what it thinks is best if no information is supplied.

**Comment by Neme12** [comment]
@CyrusNajmabadi I think you misunderstood. This is not about a language difference. This is difference between NumericLiteralFormat and CharacterValueFormat (two properties of the same enum type). But I understand your point about their being a Default value.

**Comment by Neme12** [comment]
I was wrong. The struct can supply its own default value.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
