### ISSUE TITLE
Incorrect IDE0051 (private member is unused)

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#30965]
**Version Used**: 2.11.0-beta1-63430-07+c96268112e069a5282fe6ab2b55db213c524b80c

**Steps to Reproduce**:

```CSharp
interface I
{
    event System.Action E;
}

class C : I
{
    event System.Action I.E // Incorrect IDE0051
    {
        add { }
        remove { }
    }
}
```

**Expected Behavior**: No IDE0051 on interface impl

**Actual Behavior**: IDE0051 on interface impl

Seems like it might be specific to events.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/30982
