### ISSUE TITLE
have better ExcerptMode naming

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30973]
currently, it has singleline/tooltip.

open to any better naming.

See https://github.com/dotnet/roslyn/pull/30733#discussion_r229425148

**Comment by CyrusNajmabadi** [comment]
Instead of a mode, why not just allow caller to decide how many additional lines of context can be supplied?  The tooltip code can pass in '3' saying that that's relevant to its use case.  I'd even be fine with this being an optional parameter (or overload) that defaults to 1.

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
