### ISSUE TITLE
Asynccompletion: add copy of TestNavigationBeforeCompletedComputation for SendMoveToNextCharacter and for SendTypeChars(".")

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#30970]
TestNavigationBeforeCompletedComputation uses SendMoveToPreviousCharacter
1 .Add a similar test for SendMoveToNextCharacter 
2. Add a copy of this test using the same SendMoveToPreviousCharacter as the current test, but trigger the completion session using SendTypeChars(".") instead of the current SendTypeChars(".Ma"). Since the move to the previous character moves to a different context, this test case should also not have a completion session.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
