### ISSUE TITLE
Remove workaround added to RemoveUnusedMembersDiagnosticAnalyzer for VB handles clause

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#30981]
This bug tracks removing [this workaround](https://github.com/dotnet/roslyn/pull/30980/files#diff-9e75940c1b487c924cc438f2c6e31cc4R27) added in https://github.com/dotnet/roslyn/pull/30980 for VB handles clause, once #30978 and #30979 are fixed.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are nto changing these vb experiences.
