### ISSUE TITLE
Erase inferred nullability when nullable inference fails

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#30989]
In https://github.com/dotnet/roslyn/issues/30966 (to implement the spec change described in https://github.com/dotnet/roslyn/pull/30670) we change the nullability inference so that it is associative and commutative. However, the result is that when we have a failure to infer nullability (thereby reporting a warning), we end up using non-nullable as the resulting nullability annotation.  That can result in cascaded diagnostics.

I propose that when we report a failure to infer nullability, the caller (of type inference) would then erase (to oblivious) the nullability in the result of type inference.  That will reduce cascaded diagnostics.

**Comment by jcouv** [comment]
@gafter I believe this can be closed given the new behavior implemented in https://github.com/dotnet/roslyn/pull/32947 (namely that best type and other type inference doesn't produce nullability warnings).

**Comment by jcouv** [comment]
This was fixed. Type inference no longer produces nullability warnings.
