### ISSUE TITLE
Diagnostic to suggest replacing write-only properties with methods

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#30983]
See discussions in https://github.com/dotnet/roslyn/issues/30894

**Comment by CyrusNajmabadi** [comment]
Note: as per discussions in other PRs, this should be under a code-quality bucket.  Though, IMO, i'm pretty heavily against us having a diagnostic here *period*.  I think it's extremely strange for us to be telling someone "you shouldn't have a write-only property".  What is that based on?  What group came up with that guidance?  What is the policy by which we determine if/when something is low/high quality?

With 'style' it was pretty simple, we could see large communities of people wanting to be able to pick a stylistic choice.  i.e. having 'var' or an 'explicit' type is a choice within a method that doesn't impact your surface area/API.  We're now getting into the realm of API checking, and that is definitely not a 'style' concern.

**Comment by CyrusNajmabadi** [comment]
@mavasani  can you move to Roslyn-Analyzers.  This doesn't really fit into core Roslyn IDE.
