### ISSUE TITLE
Use last token in type name for #nullable context

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#30985]
Use the last token in the type name for the `#nullable` context. For instance, use the `]` for arrays and `>` for constructed types.
```c#
using System.Collections.Generic;

class Program
{
#nullable disable
    string
#nullable enable
        [] names; // string~[]!

    Dictionary<string,
#nullable disable
        string>
#nullable enable
        map;      // Dictionary<string!, string~>~
}
```

**Comment by jcouv** [comment]
@cston @AlekseyTs I think that was already implemented by Aleksey in https://github.com/dotnet/roslyn/pull/31607
If there is a remaining issue, could you clarify it?
Otherwise, please close

**Comment by jcouv** [comment]
@cston Do we need to keep this issue open?
