### ISSUE TITLE
Create a new Tools/Option tab for C#/VB Code Quality rules

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#30986]
See https://github.com/dotnet/roslyn/pull/30777#discussion_r231171949

Also move unused parameters .editorconfig configuration setting to this tab.

**Comment by CyrusNajmabadi** [comment]
Note: we should get signoff on what we think the .eidtorconfig option names should be.  We don't want to ship names we regret that we then have to keep support for for compat reasons.

**Comment by sharwell** [comment]
Design review conclusion: there is no need to create this page at this time, since we only have a single option relevant to this proposed page. We can revisit the situation if/when it becomes apparent that more options will be applicable.
