### ISSUE TITLE
NullRef trying to change analyzer severity

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#3098]
I was playing with changing analyzer severity via the Solution Explorer context menu, and one particular analyzer stopped working at some point and started producing

![image](https://cloud.githubusercontent.com/assets/235241/7825354/dbe7155e-03c0-11e5-819b-5beac1ffd2ad.png)

Other analyzers in the same assembly continue to work correctly while this one keeps failing.

**Comment by tmeschter** [comment]
@dpoeschl Do you know what build of VS you were using, and what build of Roslyn (if you changed it)?

**Comment by dpoeschl** [comment]
I think I was using the current team basedrop + Main-Signed-Release 20150525.2.

**Comment by tmeschter** [comment]
This can happen when you have multiple `<Rule>` elements with the same ID and set the severity to "Default" in the Solution Explorer. Having multiple elements with the same ID is legal, and likely to happen with former FxCop rules--you'll end up with one copy under the "Microsoft.Analyzers.ManagedCodeAnalysis" analyzer (from FxCop) and one under "Microsoft.AnalyzerPowerPack.CSharp" (from a Roslyn-based analyzer).

When "Default" severity is specified we enumerate all the `<Rule>` elements with the given ID and remove them. However, removing them in the middle of the enumeration screws up the enumerator, and leads to the `NullReferenceException`.

The essential fix here is to first create a list of items to remove, and then remove them. That way we don't have to worry about tripping up the enumerator.

However, there are no unit tests for this code, so a better approach would be to refactor some of it out into a helper class and write tests against that.

**Comment by lgolding** [comment]
Verified as fixed.
