### ISSUE TITLE
Extremely laggy errors

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#30993]
Semantic errors in dev16 (28305.56) are extremely slow, sometimes taking over a minute to propagate after making changes to the code.

**Comment by 333fred** [comment]
This is a noticeable regression over Sunday's build.

**Comment by jasonmalinowski** [comment]
@333fred If I broke this, it would have broken weeks ago.

**Comment by jasonmalinowski** [comment]
This is believed to be fixed by #31265, but there could be more to it once we see the issue in large scale. The change did show improvements in small tests but it's always hard to say.
