### ISSUE TITLE
make ExcerptResult for regular C#/VB file self contained

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#31001]
this test is failing after Razor FAR work.

FindReferencesToSharedField

reason is this returning wrong value
case StandardTableKeyNames.Text:
                        return _lineText.ToString().Trim();

the reason it is returning wrong value is my assumption on span returned by the below is wrong
var classificationResult = await ClassifiedSpansAndHighlightSpanFactory.ClassifyAsync(documentSpan, CancellationToken).ConfigureAwait(false);

I assumed spans returned by it is based on document given in. but that is not true. it is true for classified span but not for highlight span.

highlight span is based on the implementation detail of CreateLineTextInlines. more specifically, it depends on how classified spans are reconstructed.

without that internal knowledge, it is not possible to figure out what highlight span means or what the span is against.

not going to refactor this code to be self contained or against same base text or etc.

for now, I will just fix the StandardTableKeynames.Text issue.

**Comment by heejaechang** [comment]
the Text is used in 2 cases.

1 in test. second is for copy and paste to text editor.

**Comment by heejaechang** [comment]
highlight span's 0 is from the place where non whilespace start with the line where given span.Start is

so, yes, if one knows about all these detail, sure they can reconstruct it, but otherwise, can't reconstruct it.

it has the assumption that the given span always not start with whitespace (since the span is the reference span), so the classification will not return "text" as the first classified span. and there is no gap within returned span so it can calculate the position off the classified span and etc.

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.
