### ISSUE TITLE
ExceptionHelpers.SuppressFailFast does not do anything

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#31014]
**Version Used**: 1abe9656700bc7b8021d13154545354b30b2dde2

See the following tests:

* ExceptionHelpersTests.TestExecuteWithErrorReportingWithSuppressFailFast
* ExceptionHelpersTests.TestExecuteAsyncWithErrorReportingWithSuppressFailFast

**Comment by jasonmalinowski** [comment]
It's correct it does nothing: we should just delete the members entirely. The suppression stuff was a hack we should finally get rid of for good. The fact it does nothing means we have good indication that's right!

**Comment by jasonmalinowski** [comment]
And why it doesn't work: there was never any handling for cross-thread or AsyncLazy related behaviors. One thread could say it wanted to suppress a fail fast, it'd join something else that'll do a fail fast anyways...and it'll still fail fast.

**Comment by sharwell** [comment]
Marking as **help wanted** for someone to remove this type.
