### ISSUE TITLE
Support unsigned assembly builds

### ISSUE THREAD

**Issue by jakesays** [dotnet/roslyn#3101]
Currently it is not possible to produce an unsigned Roslyn build without hand editing target files.

A simple fix would be to add `Condition="'$(SignAssembly)' == 'true'"` to the `<RoslynInternalKey/>` setting in VSL.Imports.targets.

With this condition in place, I can simply do:

`msbuild /t:Build /p:PublicBuild=True /p:Configuration=Debug /p:NonShipping=true /p:SignAssembly=false`

and end up with an unsigned build.

**Comment by jaredpar** [comment]
Could you add a bit of context on this?  In particular what scenario is blocked by our current method of signing?

**Comment by jakesays** [comment]
I cannot create an unsigned build due to the RoslynInternalKey being set, even with SignAssembly = false. The internals visible to files are still created with RoslynInternalKey, which obviously doesnt work. With this fix that becomes a non issue, and creating unsigned builds is easy.

**Comment by jaredpar** [comment]
@jakesays but why do you need unsigned assemblies in the first place?

**Comment by jakesays** [comment]
For custom builds. I need access to internal functionality, and dealing with signing is a real pain in the butt (not to mention being completely unnecessary in certain use cases.)

**Comment by jaredpar** [comment]
Ah okay.  So the scenario is that you are consuming Roslyn from an unsigned location and want access to internal types.  This is failing because `InternalsVisibleTo` from signed to unsigned doesn't work (both sides must be signed or unsigned).  Is that the scenario?

**Comment by jakesays** [comment]
Basically, yes. The issue I'm addressing here is, with `<RoslynInternalKey/>` populated and `SignAssembly=false`, the roslyn build fails, because the `InternalsVisibleTo` attributes are generated with the contents of the internal key. Since the 'visible to' signatures no longer match, nothing is actually made visible.

**Comment by jakesays** [comment]
Closed because things are working as-is.
