### ISSUE TITLE
Expose DependentTypeFinder through a public API

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#31022]
> I use the internal type `DependentTypeFinder` in my [Inheritance Margin](https://visualstudiogallery.msdn.microsoft.com/3a55d546-0cb2-4991-a002-e6be8ce09f08) extension.
> 
> https://github.com/tunnelvisionlabs/InheritanceMargin/blob/566f0d677cccc431a2f146a9f567b3eec3e97485/Tvl.VisualStudio.InheritanceMargin.CSharp/CSharpInheritanceAnalyzer.cs#L70-L76
> 

_Originally posted by @sharwell in https://github.com/dotnet/roslyn/issues/16#issuecomment-70677512_

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/43636
