### ISSUE TITLE
csharp_prefer_braces does not support .NET Foundation code style

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#31032]
The code style rules used for dotnet/roslyn, dotnet/corefx, dotnet/coreclr (among others) cannot be enforced using a built-in Roslyn analyzer. The `csharp_prefer_braces` option is too granular, and fails to account for the two exceptions allowed by the documented code style.

Without this support, the `csharp_prefer_braces` could only be partially applied to this repository (#30908).

**Comment by Neme12** [comment]
I personally follow these rules:
1. In an if statement/else clause/else if chain, if any of the branches use braces, then they all have to use braces.
2. If the embedded statement is spread across multiple lines, then it has to be in braces.
3. If the embedded statement is an embedded statement container, it has to be in braces. For example if we have an if statement inside a for loop, the if statement can omit braces, but the for loop cannot:
    ```c#
    for (int i = 0; i < list.Count; ++i)
    {
        if (list[i] == null)
            return false;
    }
    ```
    Of course if we follow the rule that an embedded statement has to be on the next line and that multiline statements have to be inside a block (2.), then rule (3.) follows from that.

**Comment by sharwell** [comment]
@Neme12 That's almost identical. There are two additional rules:

* If the condition is spread across multiple lines, then it has to be in braces
* A `using` statement may omit braces if the embedded statement is a `using` statement

**Comment by Neme12** [comment]
@sharwell I forgot those two. 👍  I think it should be allowed to omit braces in nested `using`s no matter what the preference is, just as is the case for an `if` statement inside an `else` clause. That is so idiomatic I considered that a given.

**Comment by sharwell** [comment]
@dotnet/roslyn-ide I'm proposing `when-multiline` as the name for the new option.

**Comment by kendrahavens** [comment]
In the design meeting today we discussed and approved the proposal @sharwell describes.
