### ISSUE TITLE
Collection initializer does not catch type inferance mismatch

### ISSUE THREAD

**Issue by DarkWalker** [dotnet/roslyn#31067]
**Version Used**: .Net 4.7.2

**Steps to Reproduce**:

This is a simple program that will throw NullReferenceException in runtime:

		void Main()
		{
			new A
			{
				B = {1,2}
			};
		}
		
		public class A
		{
			public List<int> B {get;set;}
		}

**Expected Behavior**: a compiler warning that type of B should be List<int> or compiling into actually working code (if {1,2,} is interpreted as collection initialize for list)

**Actual Behavior**: runtime exception NullReferenceException: Object reference not set to an instance of an object.

**Comment by gafter** [comment]
I think the compiler is producing correct code.  Although `A` declares a property of type `List<int>`, when constructed it leaves that property `null`.  The property initializer for `B` is attempting to add elements to it as required by the language spec, but the list it is adding to is `null`.

See https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#collection-initializers
