### ISSUE TITLE
Workspace.TryApplyChanges throwing not supported exception

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#31074]
we have this in Workspace.TryApplyChanges
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Workspace.cs,1168

that can throw if new solution contains changes the host can't support.

but, it doesn't looks like we actually handle the exception in Roslyn or host.

due to that, when such situation happens, we sometimes show infobar, or generic VS exception mesasge box or crash.

probably need to figure out how to handle it in VS.

**Comment by CyrusNajmabadi** [comment]
Needs to be driven with a real use case where this is demonstrating a problem.
