### ISSUE TITLE
Include modifiers in tool tips for methods

### ISSUE THREAD

**Issue by Scott-Caldwell** [dotnet/roslyn#31083]
Referencing https://github.com/dotnet/roslyn/issues/26947#issuecomment-390831445.

**Version Used**: 
Version 15.9.0 Preview 5.0

**Steps to Reproduce**:
1. Add a modifier (i.e. `abstract`, `static`, `override`, `sealed`, `extern`, or `virtual`) to a method.
2. Hover over the method to display the tool tip.

**Expected Behavior**:
The modifier is displayed in the tool tip. In the spirit of providing useful information to the end user, it makes sense to expand upon the precedent set by fields and display modifiers on methods too.

The expectation is that only the following modifiers would be displayed: `abstract`, `static`, `override`, `sealed`, `extern`, and `virtual`.

`async`, `new`, `unsafe`, and `partial` would continue to be ignored.

**Actual Behavior**:
The modifier is not displayed in the tool tip.

![image](https://user-images.githubusercontent.com/2829282/48292387-25ef0600-e448-11e8-9f3d-c2b3addf1c92.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
