### ISSUE TITLE
Suggest using ref conditional expression

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#31107]
I would like a code style option to suggest converting
```c#
if (condition)
{
    a = Foo();
}
else
{
    b = Foo();
}
```
to
```c#
(condition ? ref a : ref b) = Foo();
```
(where possible)

In my opinion it would fit well alongside the existing two options for preferring a conditional expression:
![image](https://user-images.githubusercontent.com/11444821/48314520-18ae5480-e5cb-11e8-9993-2581f1773814.png)

**Comment by CyrusNajmabadi** [comment]
I'd be very hesitant about having a particular code style for this.  This seems like a pretty complex approach that would only be used sparingly by people.  That said, i would be fine with a refactoring that might offer this.

**Comment by Neme12** [comment]
This seems like a reasonable thing to have a code style for because this is something people will likely have disagreements on - some will love it (and prefer to use whenever possible), some will hate it (and prefer to never use it). That's why I think it would be appropriate for this to be a code style, not a refactoring.

**Comment by CyrusNajmabadi** [comment]
> I'm sorry but what exactly is complex here? The original code is more complex. The resulting code is simpler and removes duplication.

`ref` is not something i would consider 'simple' by any stretch of the imagination :)

**Comment by Neme12** [comment]
How can a keyword be "complex"? It doesn't get more simple than a keyword.

**Comment by CyrusNajmabadi** [comment]
The concept of manipulating storage locations and being able to conditionally refer to them in an expression level is a complex concept.

**Comment by CyrusNajmabadi** [comment]
That it is a keyword isn't really the relevant part :)   Keywords *can* be extremely complex (see volatile, and others).  The intent of 'ref' was to open up very advanced scenarios (usually around structs, and usually around not copying them).  You can tell how advanced they are as they lkely will not even be covered until very late (or not at all) in any sort of materials that cover C#.  

Even when releasing teh versions of C# that had this functionality (and other things in this area), messaging has always been that these are advanced concepts for specific scenarios where other approaches may not be suitable.  

It's similar to 'unsafe' in that manner.  It's there for when you need it, and you know what you're doing.  But it is not, in general, something intended to be broadly applicable or in use for mainline coding scenarios.

**Comment by Neme12** [comment]
> The concept of manipulating storage locations and being able to conditionally refer to them in an expression level is a complex concept.

Why is it a complex concept though? I don't see anything about this being complex other than the fact that it's new and unfamiliar.

> Even when releasing teh versions of C# that had this functionality (and other things in this area), messaging has always been that these are advanced concepts for specific scenarios where other approaches may not be suitable.

Yes, I agree that's true for ref locals and ref returns. But there isn't even a ref local here. It's simply the "ref conditional expression" which is necessary to keep the result an lvalue, but that's just a peculiarity of the language.

This sort of thing is possible in C/C++ without any ref or pointers at all:
```c#
int a = 0;
int b = 0;
bool condition = true;
(condition ? a : b) = 1;
```
Is this example of C code complex too, simply because the ternary is on the left of an assignment?

**Comment by CyrusNajmabadi** [comment]
> Why is it a complex concept though?

Because storage locations are traditionally not retargettable or conditionally referable.   People traditionally think of expressions as returning values, not locations, and only a small set of narrow cases have generally been available to ever work with locations.

> Is this example of C code complex too

Yes.  Definitely.  Especially for many people coming from C#.  

> I agree that having to use "ref" in C# makes it seem much more advanced, which is unfortunate.

It is advanced.  C# helps call that out by not doing this sort of thing implicitly.  

> It's simply the "ref conditional expression" 

The 'ref conditional expression' is already one of hte most advanced topics you might get in expression in C#.  

Look, it doesn't look like this is really productive.  I've given my opinion.  This seems far too advanced and niche a thing to codify as a style choice.  I've already stated that i think having a refactoring here would be fine.  I'm not sure what the benfit of the back and forth on this is FWIW.

**Comment by Neme12** [comment]
@CyrusNajmabadi is right.

**Comment by CyrusNajmabadi** [comment]
Note: as per above, i'm definitely amenable to refactorings here if you (or anyone else) wanted to make them :)
