### ISSUE TITLE
Improve Introduce Variable support in Conditional Access Expressions

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#3110]
From discussions at https://github.com/dotnet/roslyn/pull/2414/

@balajikris wrote:
|F(New C)?.F(New C)|]?.F(New C) is an invalid selection. The selection cannot be represented as a single expression in the syntax tree. They are two invocation expressions under two different parent conditional access expressions. Introduce variable does not expand selection, so, in this case, the selection is just invalid.

Here is a comparison screenshot of syntax trees for F().F().F() and F()?.F()?.F()
![image](https://cloud.githubusercontent.com/assets/4213867/7830373/918165e6-0401-11e5-908f-2f7cc26c6516.png)

@dpoeschl wrote:
It's definitely tricky when the selected expression splits one of the non-ConditionalAccess expressions apart. `[|a?.b|].c` would be complicated because the right-hand side isn't on a ConditionalAccess boundary, and if you extract `a?.b` into something named `e`, then if `e` is null it needs to know whether it was null because `a` was null (should cause `.c` to be skipped) or if `b` was null (should cause `.c` to throw a NullReferenceException). 

But, when the selection ends on a ConditionalAccess boundary, then I think we could still do something reasonable. With the selection on a ConditionalAccess boundary, we can simplify to `e1?.e2?.e3?...` with no regular member accesses in between. If the specific example of `[|e1?.e2?.e3|]?.e4`, imagine it already has parentheses around the part we're trying to extract, `(e1?.e2?.e3)?.e4`. This changes the tree from `CA<e1, CA<e2, CA<e3, e4>>>` (where e1, e2, and e3 are split between multiple expressions making it hard to extract) to `CA<CA<e1, CA<e2, e3>>, e4>` without changing which expressions get evaluated or the order in which they're evaluated<sup>[[1]](#footnote1)</sup>. It's then easy to extract the part we want. (In the implementation, you could even just add the parentheses and have the parser construct the extractable node for you.)

If we did this, we'd have to add some ConditionalAccess-specific handling to the Find All Occurrences fixer, as it would again involve traversing the ConditionalAccess tree structure.

<a name="footnote1">[1]</a> When e2 is null in `e1?.e2?.e3?.e4` it skips the entire rest of the expression all at once, but when it is null in `(e1?.e2?.e3)?.e4` it has to skip the rest of the expression in two phases, once to complete the parenthesized expression, and then again to skip the rest of the larger conditional access. This probably only slows things down on very hot code paths, if ever.

Extract Method doesn't have specific knowledge about ConditionalAccess expressions today either (invoking on `[|a.b|].c` extracts `a.b` while invoking on `[|a?.b|]?.c` extracts `a?.b?.c`), but as conditional access expressions gain more usage I suspect that the differences in behavior for all of these features will become frustrating. It would be nice if there was some shared code that could rewrite a given ConditionalAccessExpression to group together some left-most "sub-expression" that these features could all use. If we don't update IntroduceVariable to support these cases as part of this fix, let's at least track this additional work in a separate public issue.

@Pilchie said:
Yes, I agree that this is something that we want to support, but I'd like to do it in a separate issue and track it for 1.1.

@balajikris said:
sounds good. I'll create a workitem for 1.1

On _"Extract Method doesn't have specific knowledge about ConditionalAccess expressions today either (invoking on [|a.b|].c extracts a.b while invoking on [|a?.b|]?.c extracts a?.b?.c)"_, Extract Method does selection expansion.

**Comment by CyrusNajmabadi** [comment]
Would take a PR to help out here.

**Comment by CyrusNajmabadi** [comment]
Haven't heard about this from anyone else.

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't gotten any feedback on this.
