### ISSUE TITLE
Add Editor Guideline on column

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#31102]
Customer Request from [twitter](https://twitter.com/GarethOates/status/1061087160391163904): 

In referring to VSCode editor.ruler setting:
> Can you get ruler lines natively in @VisualStudio as well? That would be awesome.

> ...a line after 80 or 100 characters. I think in @Code they’re in settings as editor.Rulers. I’ve seen an extension that does it but nothing that’s as simple to set as in @Code.

Paul Harrington has a VS extension that does this: [Editor Guidelines](https://marketplace.visualstudio.com/items?itemName=PaulHarrington.EditorGuidelines)
![image](https://user-images.githubusercontent.com/8293542/48305588-4d92ac80-e4e2-11e8-831b-bbb13b884ac8.png)

VSCode Example:
![image](https://user-images.githubusercontent.com/8293542/48305594-6ac77b00-e4e2-11e8-929b-c779be38231b.png)

VSCode Settings:
![image](https://user-images.githubusercontent.com/8293542/48305590-5daa8c00-e4e2-11e8-8267-f1fc707283f1.png)

**Comment by Neme12** [comment]
Yes! I forked that extension and modified it to have a different line color and be a little more subtle as opposed to the glaring dotted (and in my opinion not very pretty) red in the original. It has the same color as the horizontal lines highlighting the current line and it looks like this:
![image](https://user-images.githubusercontent.com/11444821/48305990-514f1f00-e534-11e8-8920-3988251c6527.png)

it would be nice to have something like this builtin.

**Comment by Neme12** [comment]
Actually, this seems like a feature request for VS, not Roslyn. It could apply to any language.

**Comment by kendrahavens** [comment]
I definitely think a more subtle color would help. This bug very well may be rerouted to the editor team, but I believe we'd still want an editorconfig setting for .NET.

**Comment by jinujoseph** [comment]
cc @olegtk

**Comment by olegtk** [comment]
yeah, a known feature request, please route to the editor.

**Comment by jinujoseph** [comment]
Tracked at editor side [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/945432)
