### ISSUE TITLE
Suggestion: VB.NET lightbulb for removing setter bulk code

### ISSUE THREAD

**Issue by hartmair** [dotnet/roslyn#31101]
It would be nice to have a lightbulb quickaction for removing redundant setter bulk code `(value as …)`. Originated from https://github.com/dotnet/vblang/issues/344#issuecomment-434957726

**Version Used**: 
15.8.9
15.9.0 Preview 5.0

**Steps to Reproduce**:
```VB.NET
Class Class1
    Property Property1 As Integer
        Get
            ...
        End Get
        Set(value As Integer)
            ' do something with value
        End Set
    End Property
End Class
```

**Expected Behavior**:
Lightbulb QuickAction to remove redundant setter bulk code `(value as ...)`
```VB.NET
Class Class1
    Property Property1 As Integer
        Get
            ...
        End Get
' lightbulb on next line which changes into
        Set
            ' do something with value
        End Set
    End Property
End Class
```

**Actual Behavior**:
None

**Comment by CyrusNajmabadi** [comment]
@hartmair Would you be interested in contributing such a fix?

**Comment by Neme12** [comment]
Interesting... would this fall into "code style" or "code quality"? I can imagine some people preferring to always be explicit here.

**Comment by CyrusNajmabadi** [comment]
I would count it as 'style' as it's effectively a decision about implicit/explicit naming here.

**Comment by CyrusNajmabadi** [comment]
@Neme12 Would you like to take this one?

**Comment by Neme12** [comment]
I'll add this to my backlog, but VB is not something I am super excited about :smile:

**Comment by CyrusNajmabadi** [comment]
fair enough :)

**Comment by hartmair** [comment]
@CyrusNajmabadi
> @hartmair Would you be interested in contributing such a fix?

Yes, however, I would need a lot of guidance since I don't know anything of Roslyn yet.

@Neme12 
> I'll add this to my Backlog

thx. I am glad to help if it is useful to you.

**Comment by jrmoreno1** [comment]
Would this be done with an Analyzer/CodeFixProvider?

**Comment by CyrusNajmabadi** [comment]
@jrmoreno1 Yes it would.

**Comment by jrmoreno1** [comment]
I'd be willing to take it on as well, if @Neme12  doesn't mind.

**Comment by jrmoreno1** [comment]
Should it be in VB or C#?  
https://github.com/dotnet/vblang/issues/360

**Comment by CyrusNajmabadi** [comment]
@jrmoreno1 This should be written in VB.

**Comment by jrmoreno1** [comment]
Perhaps it’s a silly question.  I was first going to create a project outside of the Roslyn solution and wanted to know what framework version to use, but on thinking about it that probably won’t mattter when I figure out where to put it.  I’ll try to get further on my own before bothering you again.

**Comment by CyrusNajmabadi** [comment]
@jrmoreno1 Ah gotcha.  

And don't worry about bothering me.  I'm happy to help.  Note: it may be faster to use gitter.im for that purpose though.

**Comment by jrmoreno1** [comment]
Would this be expected to operate or not on code decorated with generated code attributes?

GeneratedCodeAttribute, CompilerGeneratedAttribute, others?

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not chnaging these vb experiences now.
