### ISSUE TITLE
GetAllTypes Can't get baseType

### ISSUE THREAD

**Issue by wangchaoyuwangchaoyu** [dotnet/roslyn#31115]
**Version Used*15.8*:  I upgraded Roslyn Version from 1.1.0 to 2.9.0

**Steps to Reproduce**:

Step 1
```
namespace BrnMall.Web.MallAdmin.Controllers
{
    class BaseTest : Controller 

    {

    }
}
```

Step 2
```
namespace BrnMall.Web.MallAdmin.Controllers
{
    class ModelOptionalRequiredPropertiesAnalyzer_R1 : BaseTest
    {
        [HttpPost]
        public void Ac() {
        }
    }
}
```
Step 3 
```
var methodSymbol = semanticModel.GetDeclaredSymbol(methodDeclarationSyntax) as IMethodSymbol;
                    if (methodSymbol == null)
                        continue;
                    IEnumerable<ITypeSymbol> iTypes = methodSymbol.ContainingType.GetAllTypes();
```
Step 4
```
public static IEnumerable<ITypeSymbol> GetAllTypes(this ITypeSymbol typeSymbol)
        {
            while (typeSymbol.BaseType != null)
            {
                yield return typeSymbol;
                typeSymbol = typeSymbol.BaseType;
            }
        }
```

**Expected Behavior**:
Can get to the BaseTest and Controller
**Actual Behavior**:
Can not  get to the BaseTest and Controller

**Comment by wangchaoyuwangchaoyu** [comment]
If you extend the class oneself created, you cannot get the base class description.
If direct extend Controller,you can get the base class description.

**Comment by CyrusNajmabadi** [comment]
What do you get instead?  Is 'Controller' coming back as an error type?

**Comment by jaredpar** [comment]
How are you creating the `Compilation` that contains all of the types here?

**Comment by wangchaoyuwangchaoyu** [comment]
> How are you creating the `Compilation` that contains all of the types here?
"MethodDeclarationSyntax" is the syntax tree corresponding to the source code.
"semanticmodel" In the figure below.
![semanticmodel](https://user-images.githubusercontent.com/37067106/48394364-42dc4f80-e74e-11e8-9978-7071109a977a.jpg)

**Comment by wangchaoyuwangchaoyu** [comment]
> `BaseType` properties to be returning
workspace is MSBuildWorkspace instance?
Is this because the workspace was built incorrectly?
So how do you build your workspace correctly

**Comment by wangchaoyuwangchaoyu** [comment]
> That is possibly the issue then. If the Workspace is built up incorrectly then it's possible for the `BaseType` properties to be returning `null` as you're seeing in this particular example.
> 
> @DustinCampbell

Which version does not have this bug?I'm going to use that version for the moment
