### ISSUE TITLE
VB.NET: Undo moved code inside region will mess up code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31116]
In VB.NET if code inside a region was moved by using the mouse then an undo will mess up the code.
Simple case:
- create a new Windows Forms App project
- add region &quot;Test&quot;
- add functions Test1 and Test2 inside region
- select function Test2 (see attached 1.png)
- move the selected code by using the mouse to above function Test1 (see 2.png)
- press Undo button (function Test2 will disappear, 3.png)
- press Undo button (function Test2 will appear again but twice and above Test1 instead of below Test1, 4.png)

![undomess](https://user-images.githubusercontent.com/12449387/48339235-92baf980-e61c-11e8-9a6f-688e0fdd514b.gif)

**Note**: Happens only if the selected text contains empty line.

With more complicated code it gets messed up more. In C# it works fine, without regions it works fine and with copy/paste it works fine.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/371895/vbnet-undo-moved-code-inside-region-will-mess-up-c.html
VSTS ticketId: 721029_

**Comment by CyrusNajmabadi** [comment]
We're not changing these vb experiences now.
