### ISSUE TITLE
interface generation double bug

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31112]
I have a partial class A in a shared project, and partial class A in a c# project. I ask to extract the interface, VS fails.

I copy the sources from the shared project to the c# project, then ask again to generate the interface, it succeeds, but partially: the interface contains all public properties and methods *twice*.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/360383/interface-generation-double-bug.html
VSTS ticketId: 707584_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I can't repro this.  Extract interface works fine here.  Would need a repro case that demonstrates this.
