### ISSUE TITLE
async completion. Perf. GetHighlightedList provides highlights for all items. Consider making this for visible items only.

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#31136]

**Comment by CyrusNajmabadi** [comment]
Thanks! note: if perf tests reveal no problems here, then i have no problem with this approach.  It would definitely be nicer.  But we def had to implement the old approach due to the costs of things.

**Comment by ivanbasov** [comment]
As I understand from @olegtk and @AmadeusW, current perf tests showed no regressions. Keeping the issue open for a while but moving out of preview 3.
