### ISSUE TITLE
Automate enforcement for objective Roslyn style rules on IDE code.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#31140]
We will be turning on the 'formatting analyzer' for the IDE. This tools can ensure that code at least does not violate the patterns enforced by the built-in IDE formatter.  However, it doesn't ensure enforcement of many other defacto patterns the IDE has upheld for decades.  This issue will be used to track producing hte suitable enforcement tools to ensure that violations of those patterns do not creep in.

It is a requirement that any rule we create must have an automated fixer provided as well.  Users should not have to guess at how to fixup their code.  They should just be able to run the fixer and be compliant.  Ideally, automated enforcement can also come through ctrl-k-d.

This list is not exhaustive, and items will be added to it as the team discovers defacto styles that are not currently enforced but which they would like to be.  

PRs that add new enforcements should also be combined with a PR (or separate commit) that shows the effect of running the fixer on the IDE codebase.  This will allow the team to review the impact of the analyzer/fixer and determine if it fits the intent of the team.  

Note: the rules specified may need slight tweaking based on things we discover in the code base.  They are not meant to be taken in their form and applied verbatim.  Instead, they express an intent of "in the style we've grown to understand organically" and should attempt to follow that style.  So the rules below help give an intuition of hte intent, but actual examination of current practices will certainly reveal subtleties we'll want to codify.

Rules currently identified (not at all exhaustive):
- [ ] No splitting of multi-punctuation sequences.  i.e. `?.`
- [ ] Multi-line methods with `=>` should have `=>` on the subsequent line, indented one level.
- [x] ~~Some brace matching policy~~ (will be covered by moving IDE0011 to the code style layer)
- [ ] Close braces whose next token is not on the same line, and which is not a close brace itself (or an `else/catch/finally` keyword, should be followed by a blank line.  We may discover additional cases where a blank line isn't necessary. 
- [ ] Exactly one blank line between non-field/constant/single-line-property constructs.  Note: the rule may also end up being stated as "one blank line between multi-line member constructs".  
- [ ] Wrapping of entities should be one of some allowed form.  Or, alternatively, certain forms should be disallowed.  For example, wrapping where the items are at some random indent that doesn't correspond to anything.  This item itself will likely expand into many smaller rules for the different sorts of things that are generally wrapped.
- [ ] Where `:` goes in a wrapped `this(...)/base(...)` constructor initializer.
- [ ] Location of binary operators in wrapped expressions.  Note: this may involve picking a default that people are more passionate about, and then fixing up a *lot* of code to match it.

**Comment by CyrusNajmabadi** [comment]
Tagging @sharwell @jinujoseph

**Comment by CyrusNajmabadi** [comment]
Open question, should this just be for formatting?  Or should it apply other defacto rules we can also chekc for?  For example, IDE traditionally avoids optional cancellation tokens in internal APIs to prevent cases where people accidentally forget to pass teh cancellation token along.  Would that go here?  Or in some other location?

**Comment by jnm2** [comment]
Another rule at @sharwell's request: embedded statements must start on a new line.

**Comment by sharwell** [comment]
* Each field must be declared separately (observed in #39544)

**Comment by CyrusNajmabadi** [comment]
this was done.
