### ISSUE TITLE
[Regression] Go To All is broken in recent builds

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#31163]
**Version Used**: 

Version 16.0.0 Preview 2.0 [28312.106.d16.0stg]

**Steps to Reproduce**:

1. File -> New Console App (.NET Framework)
2. CTRL + T
3. Enter t Program

**Expected Behavior**:
Program type to show up

**Actual Behavior**:
No results

![image](https://user-images.githubusercontent.com/1103906/48451849-6a8bf000-e800-11e8-9af3-88a52bcb9018.png)

**Comment by davkean** [comment]
Note, the file provider still works, but any data from Roslyn is not showing.

**Comment by davkean** [comment]
Note: this is probably similar: https://github.com/dotnet/roslyn/issues/31190.

**Comment by davkean** [comment]
Actually strike that the CTRL+T works in the build called out in #31190.

**Comment by jinujoseph** [comment]
@davkean seems to working fine 
![image](https://user-images.githubusercontent.com/12449387/49617281-d0cfe280-f968-11e8-8ae2-c874ec2d5c31.png)


Build 28406.118.d16.0stg  , still seeing the issue ?
