### ISSUE TITLE
GetAnalyzerDiagnosticsAsync returns nothing if a DiagnosticAnalyzer has an empty Initialize

### ISSUE THREAD

**Issue by davunderscorei** [dotnet/roslyn#3116]
Given the following code

    private static async Task<ImmutableArray<Diagnostic>> GetDiagnosticsAsync(
        Project project,
        ImmutableArray<DiagnosticAnalyzer> analyzers)
    {
        var compilation = await project.GetCompilationAsync();
        var withAnalyzers = compilation.WithAnalyzers(analyzers);
        var diagnostics = await withAnalyzers.GetAnalyzerDiagnosticsAsync();

        return diagnostics;
    }

and that `analyzers` contains a `DiagnosticAnalyzer` which matches an issue in `project`
then `diagnostics` should contain matches to that code issue, `diagnostics.Count != 0` - which works as expected.

If `analyzers` *also* contains a `DiagnosticAnalyzer` with an empty `Initialize` method:

    public override void Initialize(AnalysisContext context)
    {
        // nothing here
    }

then `diagnostics` should contain matches pertaining to the first issue only.

Actual: `diagnostics.Count == 0`.

-----

The issue seems to be that `CompilationWithAnalyzers._driver.DiagnosticQueue` is not getting populated in the second case.

-----

This issue is discussed in [this StackOverflow question](http://stackoverflow.com/q/30476539/1185053).

**Comment by srivatsn** [comment]
I believe @mavasani just fixed this. Manish, can you make sure?

**Comment by mavasani** [comment]
Yes, this is fixed in the stabilization branch with https://github.com/dotnet/roslyn/commit/96bbb86dd1f216cef0d7a8500b063b76c6b7366b

I don't think it has yet been ported back to master.

**Comment by mavasani** [comment]
It has now been ported to master.

**Comment by davunderscorei** [comment]
<3 open source.
