### ISSUE TITLE
Are nullable annotations part of array specifiers?

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#31165]
Current meaning:
- `string[]?[] a1; // outer array is nullable`
- `string[][]? a2; // inner array is nullable`
- `string?[][] a3; // element is nullable`

This makes sense per current language design, but has problems.
Raised by @gafter, so created a tracking issue.

**Comment by alrz** [comment]
> * `string[]?[] a; // outer array is nullable`
> * `string[][]? a; // inner array is nullable`

to be clear, does that mean:


 * `string[]?[] a; // a non-nullable array of string[]?`
 * `string[][]? a; // a nullable array of string[]`

?

**Comment by jcouv** [comment]
The [specified order](https://github.com/dotnet/csharplang/blob/master/spec/arrays.md#array-types) is reverse of what you'd expect. C# picked up the order from C++. 
So `string[][]? a2 = null;` [produces a warning](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDk4BstWFiAJQkiQDsBjCAFQE8AHFAHwFgAoAbQAEBGAOkJwyMAJYBbCHwDCAezH0RBBAGUICAG4iqyPuhllMOOo2QBddlwDMAAi4Ama1OvsA3u2sfbNrgBZrAWQAKAEpnNk9rN3DPAEheAAZrDlNkgH5rKGsAXmsybCwAbmsAemLrAHcoBDIRMgBzR2UADgA2ePiQR311NVF63PzrLBEYNSgsaxkEa3oZZGQRfAgBnGt1cbhlmBlc/VQ8nDwCaxgGSXdPAF92S6A===). `a2` is *not* nullable... 
This is an open issue because it is so counter-intuitive and we're considering some options.

**Comment by jcouv** [comment]
This was resolved in LDM today. Notes should be published in next couple of days.

**Comment by gafter** [comment]
Some people might find the LDM-decided behavior surprising, particularly `M2` and `M3` below.

The resolution is as follows:

``` c#
    M1(string?[][] a)
    {
        a = null; // warning: a is not declared nullable
        a[0] = null; // warning: middle arrays are not nullable
        a[0][0] = null; // ok: elements are nullable strings
    }

    M2(string[]?[] b)
    {
        b = null; // ok: b is declared nullable at the top level (!)
        b[0] = null; // warning: middle arrays are not nullable; warning: indexing possibly null b (!)
        b[0][0] = null; // warning: elements are not nullable; warning: indexing possibly null b
    }

    M3(string[][]? c)
    {
        c = null; // warning: c is not nullable at the top level (!)
        c[0] = null; // ok: middle arrays are nullable (!)
        c[0][0] = null; // warning: elements are not nullable; warning: indexing possibly null c[0]
    }
```

**Comment by alrz** [comment]
> Some people

The word "some" covers the [entire human kind](https://user-images.githubusercontent.com/3105979/49247862-9d9fc780-f42d-11e8-816c-036821bb7f5e.png), right?
 

Seriously, even with that commented example I find myself surprised at every line.

**Comment by jnm2** [comment]
M1 was intuitive. I guessed wrong at M2 and M3.

**Comment by alrz** [comment]
Yep. The initializer is a good mental model to understand what's going on.

```cs
string[1][]? a = { arrayOfNullables };
```

**Comment by jcouv** [comment]
@gafter @cston I think this issue can be closed, as LDM confirmed the current interpretation: `string [] /* top-level annotation */ [] /* nested annotation */`.
I'll go ahead and close
