### ISSUE TITLE
Immediate window language version

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31179]
Even if the project is using the latest version of the C# language, the immediate window does not take this setting.
For example if I try to use the following extension method in the immediate window:
public static T[] ToArray&lt;T&gt; (this ref System.Buffers.ReadOnlySequence&lt;T&gt; sequence);

I get this error:
sequence.ToArray()
error CS8107: Feature 'ref extension methods' is not available in C# 7.0. Please use language version 7.2 or greater.

Please enable the latest version of the C# language in the immediate window. There is not even reason to limit the usage to the same version of the currently debugged project.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/373174/immediate-window-language-version.html
VSTS ticketId: 721644_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by raffaeler** [comment]
Since it was a Visual Studio specific issue, I wrote the feedback on developercommunity.visualstudio.com instead of here.
Thank you for moving it automatically.
