### ISSUE TITLE
Invalid nuget licenses

### ISSUE THREAD

**Issue by Sigvaard** [dotnet/roslyn#31173]
https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Workspaces/
https://www.nuget.org/packages/Microsoft.CodeAnalysis.Workspaces.Common/

Shouldn't it be MIT? Correct me if I'm wrong.

**Comment by jhinder** [comment]
Roslyn does not use a MIT licence, but the [Apache 2.0 licence](https://github.com/dotnet/roslyn/blob/master/License.txt).

For a previous discussion on package licences, see issue #20169.

**Comment by Sigvaard** [comment]
@jhinder yeah but nuget points to https://www.microsoft.com/net/dotnet_library_license.htm instead of apache 2.0

**Comment by sharwell** [comment]
Duplicate of #20169
