### ISSUE TITLE
get the "SemanticModel" block for special projects

### ISSUE THREAD

**Issue by wangchaoyuwangchaoyu** [dotnet/roslyn#31172]
**Version Used* 2.9.0*: 

**Steps to Reproduce**:

1. 
![block](https://user-images.githubusercontent.com/37067106/48463997-de39f700-e818-11e8-8fab-f09645011676.jpg)

2. source code
![source](https://user-images.githubusercontent.com/37067106/48464508-b8155680-e81a-11e8-8eb8-9f983c0d4cfc.jpg)

3.Because of privacy issues.
 I'm very sorry, I can only give you this way
Download link for the full project,
https://pan.baidu.com/s/1-bpAoyX9L4agMhX8UEYXIg

**Expected Behavior**:

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
Closing out as it's not at all specified what hte issue is or what behavior is wanted.
