### ISSUE TITLE
Want an analyzer that prevents calling virtual methods from the constructor.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#3118]
We should have an analyzer that prevents calling virtual methods from the constructor. That is a very dangerous programming practice because you may be invoking a method on a partially constructed object.

That might not catch all cases (e.g. you could still call a non-virtual method that calls a virtual method, and it would not be diagnosed.), but it would be useful even if imperfect. Or perhaps it could catch those cases as well?

/cc @MadsTorgersen

**Comment by srivatsn** [comment]
This is a FxCop rule CA2214 and we've already reimplemented it in Roslyn [here](https://github.com/dotnet/roslyn/blob/master/src/Diagnostics/FxCop/Core/Usage/CA2214DiagnosticAnalyzer.cs)

**Comment by ManishJayaswal** [comment]
Closing since we have implemented this rule already.
