### ISSUE TITLE
Verify ref assembly behavior regarding embedded resources

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#31197]
From discussion with Neal, the expected behavior is that resources should not be embedded into secondary assemblies:
- refout: main assembly has resources, ref assembly doesn't
- refonly: ref assembly has resources

@jonathanpeppers [reported](https://github.com/Microsoft/msbuild/issues/2646) that updating resources causes the ref assembly to change.

A quick look at the implementation and tests make me unsure about the current behavior, so I'll investigate further.

Ref assembly spec: https://github.com/dotnet/roslyn/blob/master/docs/features/refout.md
Ref assembly main PR: https://github.com/dotnet/roslyn/pull/19417

**Comment by jonathanpeppers** [comment]
Here is a log where I updated a `<EmbeddedResource Include="foo.txt"/>` in a netstandard project and ran an incremental build: [msbuild.zip](https://github.com/dotnet/roslyn/files/2586685/msbuild.zip)

What made me think there might be an issue here, is this in the log:
```
Target Name=CoreCompile Project=HelloForms.csproj
...
Input file "foo.txt" is newer than output file "obj\Debug\netstandard2.0\ref\HelloForms.dll".
```

I was using [this example project](https://github.com/jonathanpeppers/HelloWorld/tree/producereferenceassembly), and added `<ProduceReferenceAssembly>True</ProduceReferenceAssembly>` to `HelloForms.csproj`.

**Comment by jcouv** [comment]
That log line seems fine.

What would be an issue is if the timestamp of the `HelloForms.dll` reference assembly (at `C:\Users\jopepper\Desktop\Git\HelloWorld\HelloForms\HelloForms\bin\Debug\netstandard2.0\ref\HelloForms.dll`) is updated when you modify the resource file and build. 
If that timestamp is updated, then dependent projects will have to build too, even though the change was not significant for them.

**Comment by jonathanpeppers** [comment]
Yeah, later in the log in a project referencing it:
```
Target Name=CoreCompile Project=HelloForms.Android.csproj
...
Input file "C:\Users\jopepper\Desktop\Git\HelloWorld\HelloForms\HelloForms\bin\Debug\netstandard2.0\ref\HelloForms.dll" is newer than output file "obj\Debug\90\HelloForms.Android.dll".
```

**Comment by jcouv** [comment]
Confirmed the issue. A fix is pending for the next version of VS (dev16).

**Comment by jonathanpeppers** [comment]
@jcouv just so I can try this when it is out, which Dev16 preview will this be in? thanks.

**Comment by jcouv** [comment]
The [PR](https://github.com/dotnet/roslyn/pull/31244) is still in process. There is an open question on behavior for `/refonly`.
I'm aiming for dev16 preview2.

**Comment by jcouv** [comment]
Fix slipped out of preview2. It's being reviewed for preview3.
