### ISSUE TITLE
Naming for the new suppression scope

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#31196]
https://github.com/dotnet/roslyn/pull/31092 added a new namespace scope to suppress diagnostics in namespace and all its descendants. The current naming is "NamespaceAndChildren", but we probably want a better name that is easier to understand.

**Comment by sharwell** [comment]
📝 'children' is not the correct term because the implementation uses a transitive closure. 'descendants' is the transitive closure of 'children'.

**Comment by gewarren** [comment]
I like namespaceanddescendants or just namespacedescendants. Some other suggestions:

namespaceplus
namespaceandbelow
namespacerecursive

**Comment by JosefPihrt** [comment]
Besides my original proposal "NamespaceAndDescendants" I have another suggestion: "NamespaceAndContent"

**Comment by mavasani** [comment]
We have decided to rename the scope to `NamespaceAndDescendants`. I will send a PR soon.

**Comment by XtroTheArctic** [comment]
So, it's merged. Does that mean I can use this?
I'm on VS 15.9.4 and this doesn't seem to work.
Any idea why?

**Comment by CyrusNajmabadi** [comment]
@XtroTheArctic It was merged into a branch that is in the 16.0 line.  So you'll need a very recent build of VS2019.  Probably VS2019 preview 2 (which hasn't been released yet).

**Comment by XtroTheArctic** [comment]
That's awesome news! Thank you very much.
