### ISSUE TITLE
VB auto complete does not add missng THEN after ElseIf

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#3119]
This does work for If and #If

**Comment by Pilchie** [comment]
Oops :frowning:.  Let's bring this back.

**Comment by MattGertz** [comment]
Looks like the VisitElseIfStatement was never overridden to call the AddMissingOrOmittedTokenTransform, which in turn means that SetOmittedToken will need to be updated for ElseIf as well.

**Comment by MattGertz** [comment]
And ProcessOmittedToken as well.

**Comment by Pilchie** [comment]
@MattGertz - looks like you didn't like your commit or PR to the issue, so it didn't auto close.  Do you want to add a link and close?

**Comment by MattGertz** [comment]
D'oh, Jared warned me this might happen due to a workaround we had to do to commit it that day, I meant to follow up and forgot.  #5727.
