### ISSUE TITLE
[Regression] Go To Definition, Go To Implement, Find All References do nothing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#31190]
**Version Used**: 
Version 16.0.0 Preview 2.0 [28314.107.d16.0stg]

**Steps to Reproduce**:

1. Create Console App (.NET Framework)
2. Click on Main and choose Find All References

**Expected Behavior**:
Find Results window to show

**Actual Behavior**:
Nothing

**Comment by davkean** [comment]
My MEF logs states: https://gist.github.com/davkean/88c85ec550cfef1df7b6c4adb18674e5.

**Comment by davidwengier** [comment]
I can repro this, but only when using the context menus. All of my keyboard shortcuts still work fine.

I'm on Version 16.0.0 Preview 2.0 [28314.105.d16.0stg]

**Comment by davkean** [comment]
Yes the same. Shortcuts work for me.

**Comment by davkean** [comment]
It's not all menu items either, Quick Actions, Paste, etc all work.

**Comment by heejaechang** [comment]
let me take a look latest d16.0stg

**Comment by heejaechang** [comment]
it works fine for both d16.0stg and d16.0 for latest preview2 drop.
