### ISSUE TITLE
Control characters in strings colored differently from control character literals

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#31200]
Dev16: 28307.51.d16.0

![image](https://user-images.githubusercontent.com/3751401/48586262-4dc8e880-e8e4-11e8-9c68-b8aab23b59d1.png)

**Comment by CyrusNajmabadi** [comment]
Note: we should do this for consistency.  However, there was less of a need for this given that char literals are just a single character, and it's not hard to see what's going on.  With string-literals, it can be super confusing (esp as you have tons of `\`s when doing multiple levels of escaping.

**Comment by Neme12** [comment]
That color looks weird to me. Why not just bold escaped characters? That way it could be consistent with escaped characters inside regex. They'd have the appropriate color by what the actual character is *and* be bold indicating it's an escape sequence.

**Comment by CyrusNajmabadi** [comment]
Tagging @dpoeschl for final decisions on escaping/regex colors.

**Comment by Neme12** [comment]
Not that i'm particularly opposed to pink but it doesn't work well with the regular string color.

**Comment by sharwell** [comment]
This went to a design review recently, and we concluded that escape sequences in character literals should be classified the same as escape sequences in string literals.
