### ISSUE TITLE
Visual Studio does not suggest <see langword=""/> for some keywords

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/roslyn#31208]
**Version Used**: 
Visual Studio Community 2017 15.9.0 with ReSharper Ultimate 2018.2.3.
**Steps to Reproduce**:
1. Type language keywords 'enum', 'delegate', 'event' in an XML comment.

**Expected Behavior**:
VS should suggest using &lt;see langword=""&gt; when the pointer is on those keywords, like other keywords such as null, true and false.

Example:
![5](https://user-images.githubusercontent.com/42944058/48588601-19ecd200-e97b-11e8-9a3e-74584fc0ab3a.png)

**Actual Behavior**:
VS does not suggest using &lt;see langword=""&gt; if such keywords are used. Though, It does render like other langwords in the tooltip if I manually type it in.
![6](https://user-images.githubusercontent.com/42944058/48588655-4c96ca80-e97b-11e8-8cd1-0d03f6a7e5b2.png)
![8](https://user-images.githubusercontent.com/42944058/48588646-4274cc00-e97b-11e8-9627-80d32a4336ae.png)

**Note**: Although I haven't turned Roslyn analysis off (I've ignored suggestions from ReSharper "Disable Roslyn full solution analysis" and "Do not Include Roslyn lightbulb actions into ReSharper lightbulb"), I do think that ReSharper may be doing something that prevents such thing from happening. Could someone confirm that this happens in VS w/o ReSharper too?

Also, could you tell if this is an issue that only happens to me? #1516 doesn't look like it's been fixed, langword "true" is just displayed as plain text.
![9](https://user-images.githubusercontent.com/42944058/48589042-fa56a900-e97c-11e8-93a7-ac4a8ea550c3.png) 

Perhaps a related issue: #11490 (closed)

**Comment by sharwell** [comment]
We discussed this in a design review yesterday. The current list of supported keywords was taken from Sandcastle Help File Builder's set of supported language keywords, which made it easy to support several keywords without triggering two usability problems:

1. Adding all language keywords might make it difficult to find other items in the completion list
2. Adding keywords such as `is` or `as`, which are also common in English sentences, could be problematic

We are not opposed to expanding the current set of supported keywords if it makes sense, especially for keywords that avoid the second problem. However, it's important to keep in might that not everything that can be a keyword needs to be marked as such in documentation. The feature was originally created to improve rendered documentation for keywords like `null`, which is represented by a different name `Nothing` in Visual Basic. For most users, the ability to show different keywords for different language examples might not be as important, but we still want to focus on cases that meet one of the following:

1. The keyword is meaningful *as a keyword* in documentation. For example, 'true' and 'false' may have multiple representations in an application, but the `true` and `false` literals have a specific well-defined representation.
2. The keyword can be used to describe a concept in code, which has a very different word in Visual Basic or another language. For example, a type could be `abstract` in C#, or `MustInherit` in Visual Basic.

This feature request is now waiting for someone to create a proposed table of current keywords, with an indicator of whether they should or should not be included in the default list. We can then verify the set of keywords for inclusion at a follow-up design meeting.
