### ISSUE TITLE
Add CodeQualityOption<T> and CodeQualityOptions to Workspaces layer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#31225]
https://github.com/dotnet/roslyn/pull/30777 adds a new code quality option `UnusedParameters`, and it is the first code quality option. The current implementation in that PR uses `dotnet_code_quality_unused_parameters` as the .editorconfig name, but the option is still a `CodeStyleOption<T>` and added to `CodeStyleOptions` type. This issue tracks the work of introducing `CodeQualityOption<T>` and `CodeQualityOptions`, which should be new public APIs, and then moving this option to `CodeQualityOptions`.

**Comment by sharwell** [comment]
Marking this as **blocked** until we get compiler API support for .editorconfig in place and determine our versioning/distribution strategy for NuGet analyzer packages.

**Comment by Youssef1313** [comment]
> Marking this as **blocked** until we get compiler API support for .editorconfig in place and determine our versioning/distribution strategy for NuGet analyzer packages.

@sharwell This is no longer blocked now right?

**Comment by Youssef1313** [comment]
@mavasani Do we still want to introduce such an API?

**Comment by mavasani** [comment]
I don’t believe we will add any more code quality analyzers in Roslyn. I am going to close this one.
