### ISSUE TITLE
Can't install Roslyn on dev15.9

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#31239]
I tried `msbuild /v:m /m Roslyn.sln` and `devenv /rootSuffix RoslynDev` with latest bits from `master` today and VS crashed as soon as I opened a project.
The exception in the crash dump mentioned `System.Memory`.
This means that contributors will not be able to test IDE changes until dev16 preview2 becomes public.

One option would be to temporarily remove this dependency and add it back when we are closer to shipping preview2.

@agocke @jasonmalinowski @jaredpar to advise.

**Comment by SyntaxNode** [comment]
I encountered the same issue today. Builds successfully, but crashes when loading a project on dev15.9.0 and dev15.9.1 while trying to load the recently added System.Memory, Version=4.0.1.0 dependency for Microsoft.CodeAnalysis.

Is it possible to add System.Memory and it's dependencies to the deploy for dev15 compatibility?

**Comment by jcouv** [comment]
Note: one workaround is to work off of a commit that pre-dates System.Memory, such as fe2b7a61ab07b3fcc5248102cd6da8edaca692c6. This only works if you don't need other changes that went in since.

**Comment by jasonmalinowski** [comment]
@agocke fixed this in #31221 which was merged just moments ago.
