### ISSUE TITLE
Parsing text to syntax and inserting into class generates invalid output with #endregion at the end

### ISSUE THREAD

**Issue by WernerGe** [dotnet/roslyn#31242]
**Version Used**: 
Microsoft.CodeAnalysis.CSharp 2.10.0

**Steps to Reproduce**:

1. Parse a code snippet enclosed with #region, #endregion with CSharpSyntaxTree.ParseText()
2. Insert code snippet with SyntaxFactory.ClassDeclaration("test1").AddMembers(syntaxNodes1) in a class syntax

**Expected Behavior**:
* The code snippet should be contained as it was (containing the #endregion, too).
* Valid class output 

**Actual Behavior**:
* The #endregion directive is missing if it is the last line in the code snippet. 
* Output generates 'classtest1'  which is not valid

Appending any statement after the #endregion the #endregion is considered correctly. An attached LinqPad sample shows both cases.
[ParsingGeneratingLastEndregionMissing.zip](https://github.com/dotnet/roslyn/files/2593247/ParsingGeneratingLastEndregionMissing.zip)

Output of LinqPad sample

```*** Class 1 FAILS

classtest1{#region <<< INotifyPropertyChanged [Implementation] >>>
public event PropertyChangedEventHandler PropertyChanged;
}
*** Class 2 WORKS
class test2
{
#region <<< INotifyPropertyChanged [Implementation] >>>
    public event PropertyChangedEventHandler PropertyChanged;
#endregion
    int n = 5;
}```

**Comment by CyrusNajmabadi** [comment]
How did you get "syntaxNodes1"?  It's likely you're not including the trivia that would be attached to the EOF token in the tree you got back from `CSharpSyntaxTree.ParseText()`

**Comment by CyrusNajmabadi** [comment]
> Output generates 'classtest1' which is not valid

You did not specify any trivia.  Either specify trivia when creating the tree, or explicitly format the tree with .NormalizeWhitespace.

**Comment by CyrusNajmabadi** [comment]
Ok.  Looking at your code, the problem is: 

```c#
var syntaxNodes1 = Parse<MemberDeclarationSyntax>(snippet1)
...
public static TSyntax[] Parse<TSyntax>(string code)
        {
            var syntaxNodes =
                CSharpSyntaxTree.ParseText(code, CSharpParseOptions.Default)
                    .GetRoot()
                    .ChildNodes();

	return syntaxNodes.OfType<TSyntax>().ToArray();
}
```

You're only returning the MemberDeclarationSyntax node.  But the `#endregion` will be attached to the EOF token, not the member declaration.  This is how the roslyn syntax model works.  You can read more about that here: 

https://github.com/dotnet/roslyn/wiki/Roslyn-Overview#syntax-trivia
https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/get-started/syntax-analysis

> Syntax trivia represent the parts of the source text that are largely insignificant for normal understanding of the code, such as whitespace, comments, and preprocessor directives.

> Because trivia are not part of the normal language syntax and can appear anywhere between any two tokens, they are not included in the syntax tree as a child of a node. Yet, because they are important when implementing a feature like refactoring and to maintain full fidelity with the source text, they do exist as part of the syntax tree.

> You can access trivia by inspecting a token’s LeadingTrivia or TrailingTrivia collections. When source text is parsed, sequences of trivia are associated with tokens. In general, a token owns any trivia after it on the same line up to the next token. Any trivia after that line is associated with the following token. The first token in the source file gets all the initial trivia, **and the last sequence of trivia in the file is tacked onto the end-of-file token, which otherwise has zero width.**

Relevant part bolded.

**Comment by CyrusNajmabadi** [comment]
@jcouv @jaredpar I believe this is by design as a core part of how the Roslyn syntax model works.

**Comment by WernerGe** [comment]
Hi, thanks for the prompt analysis and information links. Yes, the issue is by design. I solved it by moving the endregion from EOF Token (which drops out as only MemberDeclarations are returned) as trailing trivia to the last member node.
