### ISSUE TITLE
On VS startup, squiggles appear but error list is empty

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#3125]
Repro:

1. In my main instance of VS, I press F5 to debug my analyzers assembly.
The sandbox instance of VS appears.

1. In the sandbox instance, I open a test solution that contains a source file that demonstrates the issues my analyzers detect. I open the source file.
The green squiggles appear, and the issues appear in the error list.

1. In the sandbox instance, I uninstall the "Analyzers1" VSIX that still happened to be installed, and then restart VS.

Expected: The same document would be open, I would still see the green squiggles, and the error list would still be populated.

Actual: The same document was open, I saw the green squiggles, but the error list was empty.

HeeJae thinks it's because the error list populates asynchronously, and there's a race condition where it populates the error list before the document opens. On this theory, it's irrelevant that I was using the sandbox instance, or that I uninstalled a VSIX. It's just relevant that I restarted VS while a document with squiggles was open.

**Comment by heejaechang** [comment]
it looks like a race is not in error list population but in the diagnostic service eventing itself.

**Comment by heejaechang** [comment]
related to devdiv # 1182186

**Comment by heejaechang** [comment]
fix checked in. closing this.
