### ISSUE TITLE
Visual Studio Solution Explorer Analysers colorized icons

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31284]
{reader[descriptionIndex]}

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/385034/visual-studio-solution-explorer-analysers-colorize.html
VSTS ticketId: 731485_
_These are the original issue comments:_

Eric Bl dev on 11/16/2018, 10:37 AM (4 days ago): <p><a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2017" target="_blank">Microsoft Docs page linked<br></a></p><p>why can't we add link here??<br><a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2017" target="_blank"></a></p>

Fiona Niu[MSFT] on 11/18/2018, 08:22 PM (41 hours ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>

**Comment by CyrusNajmabadi** [comment]
@tmeschter do you know who owns the icons for the Analyzer's entry in Solution Explorer?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of response.
