### ISSUE TITLE
Simplifying expressions interacting strangely with #if

### ISSUE THREAD

**Issue by Marti2203** [dotnet/roslyn#31280]
**Version Used**: The current version in Monodevelop(v3)

**Steps to Reproduce**:
1. Make a conditional that returns a value, which is inside a compilation #if
2. After it add a return
3. A suggestion has been made

**Expected Behavior**:

```
#if Example
                if (!flag) return 2;
#endif
                return 3;

```
remains unchanged

**Actual Behavior**:
It can be simplified to this
```
#if Example
                return !flag
                    ? 2
                    : 3;
#endif
```

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  We do not offer 'use conditional here':

![image](https://user-images.githubusercontent.com/4564579/217981870-e19a78f5-3a1c-4fc4-a294-ef9442cb8288.png)

But we do if there is no pp directive:

![image](https://user-images.githubusercontent.com/4564579/217981917-878cfeae-e2e4-4894-9963-78e58dcf944c.png)
