### ISSUE TITLE
VS2017 Memory and CPU with converted Projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31290]
I basically followed this guide: http://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/ and got it to the point where all our projects were building with no errors/warnings, and our application behaved as expected, but VS performance was abysmal. We have 93 projects in our solution with approx 6000 .cs files. Mostly dlls, 6 web projects and a couple exe projects in there. I've already done 1 and 2 from this: https://github.com/dotnet/roslyn/wiki/Performance-considerations-for-large-solutions I have not tried the other solutions as I'm weary having to make registry changes across the team.  With the old csproj format, our solution took about 750MB on fresh start and was ready in about 30s.  With the new csproj format, that same solution now takes 2.5GB+ on fresh load, and the IDE is not responsive for at least 5 minutes.  Even after that point, CPU usage stays high and never goes down.  ReSharper will not even load with the new format, the system just completely hangs indefinitely.

Using VS 2017 15.3.2 on a i7-7700K with 32GB of RAM and Samsung SSD 950 with Windows 10 1703 with all latest updates.  No virus scanners at all.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/100072/vs2017-memory-and-cpu-with-converted-projects.html
VSTS ticketId: 484198_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by pengjie012** [comment]
我也遇到了上述的那个问题 我发现可以先在外部创建一个git厂库,再在里面新建工程就可以了.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  Given all the perf work done, i'm closing out.
