### ISSUE TITLE
error CS8374: Cannot ref-assign 'x!' to 'x' because 'x!' has a narrower escape scope than 'x'.

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#31297]
**Version Used**: 

Branch C# 8.0: Nullable reference type (29 Oct 2018)
https://github.com/dotnet/csharplang/blob/master/proposals/nullable-reference-types.md
Latest commit 2f8fef by AlekseyTs:
Compare Nullable modifiers while comparing type symbols by default. (#30770)

**Steps to Reproduce**:

```cs
class C
{
    void M()
    {
        ref var x = ref NullableRef();
        x = ref x!;
        
        // interestingly enough this one works
        ref var y = ref NullableRef()!;
        y = ref y!;
    }
    
    extern ref string? NullableRef();
}
```

https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDk4BstWFiAJQkiQDsBjCAFQE8AHFAHwAEAmAAgGEBYAKADe/DiI4sALBwCyACgCUw0UL6jVHJGA4A3KAg4APDgF51JDphx4CxMPIDcitQeOnN+gIQOVTjo7UB6fw4ASzIYCCRkGFCAcyxaDggyAHs4GIALDhh04OQOZLIIDgB3ZIQAa2Q/VQ1tXQ4Ek1qLXHwiEnlPatFG1wau7xEAXz8/CH1whDI+lgBGAAYAfnNsVusOuS8hoA===

**Expected Behavior**:

No errors

**Actual Behavior**:

`error CS8374: Cannot ref-assign 'x!' to 'x' because 'x!' has a narrower escape scope than 'x'.`

----
[jcouv update:] I've tagged some code with this issue (`CheckValueKind`, `GetValEscape`, `CheckValEscape`). Please search for them when resolving this issue.

**Comment by jaredpar** [comment]
Wow, nice find.
