### ISSUE TITLE
5% of overall allocations loading a large solution is the Project Id -> Project map in Roslyn

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#31306]
GC Rollup By Generation
--
Gen | Count | MaxPause | MaxPeak MB | Max AllocMB/sec | TotalPause | TotalAlloc MB | Alloc MB/MSec GC | Survived MB/MSec GC | MeanPause | Induced
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ALL | 426 | 741.5 | 4,106.9 | 1,112.349 | 9,601.4 | 2,118.8 | 0.2 | 0.269 | 22.5 | 7
0 | 282 | 35.3 | 2,087.1 | 1,112.349 | 3,548.3 | 1,389.3 | 1.7 | 0.029 | 12.6 | 0
1 | 138 | 63.7 | 4,106.9 | 396.323 | 2,764.4 | 709.1 | 1.3 | 0.025 | 20.0 | 1
2 | 6 | 741.5 | 2,070.8 | 10.006 | 3,288.7 | 20.3 | 1.6 | 0.369 | 548.1 | 6

We've been doing analysis on huge solutions with the aim to quadruple the number of projects we can open, and in this solution with 780 projects, Roslyn's ImmutableHashMap mapping id -> project is causing 5% of all allocations:

![image](https://user-images.githubusercontent.com/1103906/48873432-e6f68280-ee41-11e8-8025-074c2abc31ae.png)

I can provide the trace on request.

**Comment by davkean** [comment]
tag @jasonmalinowski

**Comment by jasonmalinowski** [comment]
Just to understand: the allocations _of the overhead of the map itself_ is 5% across the entire product? That's...surprising.

**Comment by jasonmalinowski** [comment]
(and terrifying)

**Comment by davkean** [comment]
This is just allocations during solution load, but yes, this is surprising given you wouldn't expect this to grow anymore than 780 times.

**Comment by jasonmalinowski** [comment]
Not quite, it's being resized potentially 780 * number of changes to workspace times: Roslyn Solution snapshots share Project**State** instances between snapshots, but this is a "red node" style API that means we create a new wrapper Project for each Solution. So it's just a thin instance that forwards, but if things are aggressively asking for it, that'll be bad.

I was looking at some other traces yesterday to see what other hotspots appeared after all of our work, and GetProject jumped out as a CPU cost too. It looks like it's doing a Interlocked spin on the hash map, so it's possible that's "missing" a lot and creating lots of garbage. In any case this was wasting around 200ms of time on the UI thread loading Roslyn.sln which we'll want to fix.

**Comment by jasonmalinowski** [comment]
So I can do a targeted fix on that one place I saw this being used to just use the underlying ProjectStates, which will avoid the creation there. I'm not sure if I'm just moving that time to somewhere else though. The map is lazy too in that it's trying to only create them on demand -- if it turns out in the "real world" that the red node wrappers are always made, then we might just want to create them up front which will then avoid all the overhead of the immutable data structures.

**Comment by jasonmalinowski** [comment]
Fun discovery: I assumed this was using ImmutableDictionary from the BCL. It's not...it's got it's own implementation for memory optimization reasons. 😦

**Comment by davkean** [comment]
Thanks!
