### ISSUE TITLE
reference intellisense

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31305]
The one where you display the full statement when you hover over references found.  Get rid of it.  It's extremely annoying, takes up time while I maneuver away from it.  I can always click the reference to see the line in question.  This feature adds to the the over-cluttered 'developers experience' and makes me think you invent additions just because you can - not because it helps anyone.  I need and use a  lot of intellisense features.  This one definitely shows you've gone past optimal.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/352888/reference-intellisense.html
VSTS ticketId: 700379_
_These are the original issue comments:_

scott barnes on 10/9/2018, 06:55 PM (42 days ago):  https://docs.microsoft.com/en-us/visualstudio/ide/finding-references?view=vs-2017 describes the misuse I'm talking about - "You can also hover the mouse over any search result to see a preview of the reference."  This is what I want to disable.  Is there a setting anywhere in Visual Studio that stops this pointer position results obliteration?
Cytheria Ji (MSFT) [MSFT] on 10/10/2018, 06:50 PM (41 days ago): <p>Thank you for your feedback! </p><p>For us to investigate this further, could you please provide your project type and language?</p><p>We look forward to hearing from you!</p>

scott barnes on 10/13/2018, 03:59 AM (39 days ago): <p>c# desktop app.  I found this feature goes as far back as Visual Studio 2015.  There is a column to the left of references that doesn't show the hover clutter, but I WANT to put the cursor over the reference.  Wish there was an easy switch to stop this.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
FWIW,  use this all the time.  It's a quick and simple way to get context about a reference without having to navigate or otherwise intrude on the document i'm currently editing.
