### ISSUE TITLE
SimpleTypeName snippet function does not return expected value

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31309]
I was creating a snippet to apply a custom attribute.  I Used the SimpleTypeName function to get the attribute name literal to be printed.  But the value returned is not as expected.

snippet
=======
        &lt;Literal Editable=&quot;false&quot;&gt;
          &lt;ID&gt;Test&lt;/ID&gt;
          &lt;ToolTip&gt;
          &lt;/ToolTip&gt;
          &lt;Default&gt;
          &lt;/Default&gt;
          &lt;Function&gt;SimpleTypeName(global::Company.Product.Project.Framework.MyXXXAttribute)&lt;/Function&gt;
        &lt;/Literal&gt;

below the code uses &quot;[$Test$(...]&quot; in it.
==========================

Now, when I insert this snippet, I find two issues as below
1.  The expansion does not remove the 'Attribute' part which is a normal case with using  applying attributes.

2.  If I am inside a class which is inside a namespace Company.Product.Project.YYYY and I already have using Company.Product.Project.Framework; the snippet still expands to [Framework.MyXXXAttribute] instead of [MyXXX]

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/356498/simpletypename-snippet-function-does-not-return-ex.html
VSTS ticketId: 705077_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
the existing system is in maintenance mode.  closing out.
