### ISSUE TITLE
"Calcualte Code Metrics" should be moved to Analyze sub menu on solution context

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#31322]
**Calculate Code Metrics** is on the **Analyze** menu bar:

![image](https://user-images.githubusercontent.com/1103906/48924964-b3cff400-ef12-11e8-897f-8c21188ffb32.png)

And on the **Analyze** sub menu for a project:

![image](https://user-images.githubusercontent.com/1103906/48924981-07424200-ef13-11e8-8343-e9c818bd4b5f.png)

The same cannot be said for the menu item on the solution context menu:

![image](https://user-images.githubusercontent.com/1103906/48924959-93a03500-ef12-11e8-9913-ff48fb43b90d.png)

Given we've added 2 more menu items from this team this release (Run Test, Debug Tests), can we please move this menu to reduce the size of the context menu?

**Comment by CyrusNajmabadi** [comment]
I don't believe this is us.  Closing out absent evidence otherwise :)
