### ISSUE TITLE
Multi-targeting context can never work via VSHPROPID_ActiveIntellisenseProjectContext

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#31366]
In the new language-service integration rewrite, we were told to move over to using VSHPROPID_ActiveIntellisenseProjectContext. 

How it's supposed to work:

1. Changing the editor context, causes VSHPROPID_ActiveIntellisenseProjectContext to be set
2. This causes the IVsHierarchy to be set VSHPROPID_ActiveIntellisenseProjectContext
3. This raises an property change event, and causes Roslyn to react to the context change

Debugging this, 2 never occurs in VisualStudioWorkspaceImpl.SetContext.

**Comment by sharwell** [comment]
@jasonmalinowski is this part of what you were working on in the project system?

**Comment by sharwell** [comment]
@davkean I'm not sure how to triage this. Is it related to (or cause of) #31365?

**Comment by jasonmalinowski** [comment]
This is already tracked by https://devdiv.visualstudio.com/DevDiv/_workitems/edit/661547.
