### ISSUE TITLE
Autocompletion for pattern matches in switch 

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#31367]
**Version Used**: VisualStudio.15.Preview/15.9.0-pre.6.0+28307.53

**Steps to Reproduce**:

```C#
switch (object)
{
    case A a|
}
```
Now hit colon.

**Expected Behavior**: `case A a:`

**Actual Behavior**: `case A as:`

If I am correct `as` is not a valid syntax at this point, maybe the autocompletion should be in the names suggestion mode?

**Comment by Neme12** [comment]
@CyrusNajmabadi This is not a problem in the when keyword recommender (it's not offered here, assuming A is a type name). The suggestion is to remove `as` from the completion list. It's possible though that some of the logic from the when keyword recommender for determining whether the expression is a type might be useful here.

**Comment by Neme12** [comment]
> maybe the autocompletion should be in the names suggestion mode?

It *is* in name suggestion mode, but naming suggestions are disabled for single character type names.

**Comment by Neme12** [comment]
It seems the fact that naming suggestions are not offered here (even though it's just a single character) is causing a problem. Typing `A` Ctrl+space will complete `as`, whereas if `a` was in the completion list it would have been unchanged as `a`. I propose removing this character length limitation of naming suggestions. @CyrusNajmabadi thoughts?

**Comment by CyrusNajmabadi** [comment]
I'm just tagging you since you know this area well :)  Not because it has to do with 'when' :)

**Comment by CyrusNajmabadi** [comment]
> It is in name suggestion mode, but naming suggestions are disabled for single character type names.

Hrmm.... That's interesting.  Why is that?

**Comment by rchande** [comment]
@CyrusNajmabadi At the time, we thought it would be uninteresting/annoying to bring up the completion list with one, single-letter name in it. If the team wants to change that behavior, I don't have any strong objections. In this particular case, though, it sounds like we need to stop showing `as` at this position :).

**Comment by Neme12** [comment]
Why would it be annoying if it's in suggestion mode?

**Comment by Neme12** [comment]
IMO single-letter type names are probably not that common anyway, so it's not like we'd show an extra completion list in a super common scenario.

**Comment by Neme12** [comment]
I have noticed this before when writing some sample code for a repro or an issue, and it generally feels to me like something isn't working when I don't see what I expect to see.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi At the time, we thought it would be uninteresting/annoying to bring up the completion list with one, single-letter name in it.

But... don't we do that:

![image](https://user-images.githubusercontent.com/4564579/49110161-8d2af980-f241-11e8-8ebd-0bd3a6b6efec.png)

Here we have a suggestion case, and the suggestion is just a single letter...

**Comment by Neme12** [comment]
> it sounds like we need to stop showing as at this position :).

I don't think that's the underlying issue. It's possible that both naming suggestions and another keyword would be valid suggestions at the same time. Consider a type named `W` and a constant named `W`. When I type `W |`, I could type `w` for a variable name, or `when`, in which case `w` will bind to the constant. The issue would still be here. I believe the appropriate fix is to remove the limitation from name completion.

**Comment by CyrusNajmabadi** [comment]
I'm still not  really understanding "the limitation".  My picture shows a case where we are in suggestion mode (since you can be typing a new name) and it's fine to have that name be a single letter.  It's unclear to me why this isn't the exact same case (no pun intended) as what we're seeing in the switch.

We may be writing a legal keyword, or we may be intrducing a name.  As such, we should be in suggestion mode...  Wouldn't that eliminate the problem here?  Specifically, the problem where the items in the list interfere with teh new name a person is trying to write.  Items in teh list can't interfere if we're in suggestion mode.  That's the point of it :)

**Comment by Neme12** [comment]
Yes, it wouldn't be able to interfere. That's why I don't understand why @rchande said it would have been annoying to show the completion list.

**Comment by rchande** [comment]
From the first post in this issue, is it valid to write `as` at the caret in this text?
```switch (object)
{
    case A a|
}
```
If it's not, we should fix the keyword recommender. 

There's a totally orthogonal question to whether the name suggestion feature should suggest single letter names. Like I said earlier, if the team wants to change the design they're welcome to do so. BTW, here's a quick mspaint mockup of what that would look like. 
![image](https://user-images.githubusercontent.com/3751401/49112217-0aa53880-f247-11e8-898b-01e0b0b68ba2.png)

**Comment by Neme12** [comment]
I disagree. IMO whether or not `as` is offered here is a totally orthogonal issue. The issue here is that because name completion isn't in the completion list, another item is committed instead. In this specific case it could be "resolved" (or rather the issue could be hidden) by removing those other suggestions, since they're redundant, but that's not at all a fundamental rule that they will always be redundant. I gave you an example of where the other item in the completion list would not be redundant.

**Comment by rchande** [comment]
@CyrusNajmabadi @Neme12 I remembered why we don't show single-letter names. The name suggestion feature tries to break up names into their constituent words and suggest all the individual words, as well as subsequences of increasing length starting at the beginning and end of the name. Eg, `MyCatFactory` would suggest [1]. We wanted to avoid suggestions like `I` for `ICatFactory` but could obviously relax that restriction for names that started out as one character. That said, I 
don't understand the resistance to fixing the keyword recommender. Even if you change name suggestions, the `as` keyword will still be present and wrong. 

Another thing--the name suggestions feature is optional. Anyone who turns it off is still going to encounter the specific case of this bug. The general solution for cases where the user could type a new name or use an existing one (as shown in https://github.com/dotnet/roslyn/issues/31367#issuecomment-442209097) is called "Suggestion mode". 

Here's what I suggest
* Fix the keyword recommender
* Make sure the list of cases for suggestion mode is up to date with the latest language features 
* If it inherently makes sense for the naming suggestions feature (and not to paper over missing suggestion mode cases), show single letter identifiers

[1]
* My
* Cat
* Factory
* MyCat
* CatFactory
* MyCatFactory

**Comment by Neme12** [comment]
I am not resisting any keyword recommender fixes. But I don't think that's the primary issue here.

**Comment by Neme12** [comment]
> Another thing--the name suggestions feature is optional. Anyone who turns it off is still going to encounter the specific case of this bug.

No, they're not. Anyone who turns it off doesn't expect to hit tab when typing a declaration name and have the name completed. There would be no bug for them.

**Comment by Neme12** [comment]
Ah, OP actually mentios hitting colon as opposed to tab. But that shouldn't commit anything since it's in suggestion mode. I can't repro this.

**Comment by rchande** [comment]
@Neme12 Well actually, the bug is about typing colon to start the switch case, and if you type `a:` with name suggestions off you will insert as:
![image](https://user-images.githubusercontent.com/3751401/49117108-8659b200-f254-11e8-9653-a28b8763fd0a.png)

**Comment by Neme12** [comment]
Hm I can't repro that :confused:
![image](https://user-images.githubusercontent.com/11444821/49117145-153fec00-f2a0-11e8-8034-00c106beccc1.png)

**Comment by Neme12** [comment]
But in that case the primary issue is that completion should be in suggestion mode.

**Comment by rchande** [comment]
@Neme12 You turned on consume-first mode by typing ctrl-alt-space.

**Comment by rchande** [comment]
Right, the way to generally achieve that is to fix the suggestion mode feature, not to change naming suggestions.

**Comment by Neme12** [comment]
I did not.

**Comment by Neme12** [comment]
Can you please show me a complete repro? Thanks

**Comment by CyrusNajmabadi** [comment]
> That said, I
don't understand the resistance to fixing the keyword recommender. Even if you change name suggestions, the as keyword will still be present and wrong.

I'm not resistant to that.  But it will only be a partial fix.  Other *legal* completoin items here will still cause problems.  That's why i want us to have suggestion-mode on here.  Since you could be completing to an exsiting construct/keyword *or* you could be introducing a new name, we should have suggestion mode.

**Comment by Neme12** [comment]
> @Neme12 You turned on consume-first mode by typing ctrl-alt-space.

I don't understand why you would accuse me of doing that. I being honest and trying to help, not undermine the discussion.

**Comment by rchande** [comment]
@Neme12 It's not a personal accusation, it's my inference of what happened on your machine based on the screenshot you shared.

**Comment by rchande** [comment]
@CyrusNajmabadi Right, I think we agree, see my list of recommendation at https://github.com/dotnet/roslyn/issues/31367#issuecomment-442247910

**Comment by Neme12** [comment]
![image](https://user-images.githubusercontent.com/11444821/49117534-508eea80-f2a1-11e8-8f65-7781c99bca94.png)

**Comment by rchande** [comment]
@Neme12 Can you share the same screenshot but with nothing typed? Eg, ctrl-space to bring up the list at that position?

**Comment by Neme12** [comment]
![completion](https://user-images.githubusercontent.com/11444821/49117634-ac597380-f2a1-11e8-9cb2-e478f56ad1ab.gif)

**Comment by Neme12** [comment]
Can you please provide a complete code example where you repro the issue? Thanks

**Comment by rchande** [comment]
@Neme12 I have the same code as you, but I turned the name suggestions feature off to demonstrate why that's not where the fix belongs. I think you still have it turned on based on the <Name> text in the builder?

**Comment by Neme12** [comment]
You're right, if I turn name completion off, it's not in suggestion mode.

**Comment by Neme12** [comment]
But then I don't understand this part of the report:
> maybe the autocompletion should be in the names suggestion mode?

**Comment by rchande** [comment]
I don't want to speak for the OP but it sounds like it was a speculative suggestion for how to fix the bug.

**Comment by Neme12** [comment]
Yes but it's odd given that OP has name suggestions turned off.

**Comment by miloush** [comment]
This escalated quickly. :-)

Few notes:
1. This is not a single letter issue. As @rchande already showed in the screenshot, the problem occurs regardless of the length of the type name.
2. I have not disabled name suggestions, at least if we are talking about Settings > Text Editor > C# > IntelliSense > Show name suggestions, I have that checked.
3. Enabling or disabling name suggestions does not matter, the intellisense should be in suggestion mode, with names or without.
4. If we started cutting contextually invalid entries from the list then I agree `as` and `is` shouldn't be offered if they were invalid.

Clearly there has been some concerns about the repro. Can we check we are using the same version? I also have "Perform editor feature analysis in external process (experimental)" enabled. Any other settings that might influence completion/suggestion mode behavior?

**Comment by Neme12** [comment]
@miloush I'm using 15.9 Preview 6 too with external process enabled. Is it possible you have one of those C# 8 language feature previews installed, which would replace your version or Roslyn?

**Comment by miloush** [comment]
> Is it possible you have one of those C# 8 language feature previews installed

No, nothing extra installed. I tried disabling external process and it didn't help.
I also checked in 16.0.0 Preview 1 and cannot repro there.
