### ISSUE TITLE
Add an overload for NameGenerator.GenerateUniqueName that handles local name clashes in nested scopes

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#31373]
See discussion https://github.com/dotnet/roslyn/pull/30777/files#r236088758. See unit test [ExpressionStatement_UnusedLocal_NameAlreadyUsed_03](https://github.com/dotnet/roslyn/pull/30777/files#diff-a47cfb2acf76bb4a59b6e9088d9e8483R290) for the kind of clashes that should be handled. As part of this work, we should also audit the existing callers of `NameGenerator.GenerateUniqueName` overloads to see which ones desire the new functionality and move them over to the new overload.

**Comment by CyrusNajmabadi** [comment]
We have ISemanticFactsService.GenerateUniqueName for this.  It should be a one-liner.  I would just make the PR change prsonally rather than track this through an issue.  We know that issues like these rarely go anywhere.

**Comment by mavasani** [comment]
Makes sense. Never knew that API existed. Thanks!

**Comment by CyrusNajmabadi** [comment]
> NameGenerator.GenerateUniqueName that handles local name clashes in nested scopes 

Note: we don't want to actually touch NameGenerator.  It is intended to just be a language-agnostic, non-compiler-related, helper file/lib.  Basically, it's used to just form a non-conflicting name given some rules. But the idea is that other libraries (like ISemanticFactsService) will build up logic around it.  

Thanks! :)

**Comment by CyrusNajmabadi** [comment]
Definitely!
