### ISSUE TITLE
DefaultSeverity of analyzers ignored when isEnabledByDefault: false

### ISSUE THREAD

**Issue by Romanky** [dotnet/roslyn#31371]
**Version Used**: 
2.6.2

**Steps to Reproduce**:
1. Analyzer with defaultSeverity: DiagnosticSeverity.Error and isEnabledByDefault: false
2. Create ruleset and activate analyzer by ticking the box

**Expected Behavior**:
The analyzer is activated with action Error

**Actual Behavior**:
The analyzer is activated with action Warning

**Comment by sharwell** [comment]
@mavasani Can you mark this **help wanted** if the code in question is part of dotnet/roslyn? If it's instead part of the internal rule set editor implementation it would need to be implemented by someone with access to that code.

**Comment by mavasani** [comment]
This is a known limitation of the Ruleset editor - the default column value for the "Action" column for every rule is "Warning", so when you enable a rule by just checking the rule checkbox, you generate an entry in the ruleset file with severity Warning, not the default severity. You can change this behavior by changing the column combo box to the desired severity when checking the checkbox.

![image](https://user-images.githubusercontent.com/10605811/49024825-3d6c0580-f14f-11e8-9b1a-8201c27026ea.png)
