### ISSUE TITLE
ExtractInterface could work in parallel on updates

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#31378]
It might be possible to get performance gains from ExtractInterface when working on multiple documents. Since the code could be doing independent actions across multiple documents that aren't serial, moving to parallel may be beneficial. 

See #31183 for more context on changes in this area.

**Comment by CyrusNajmabadi** [comment]
closing out.  we should drive this with an actual scenario showing a perf problem that would warrant this.
