### ISSUE TITLE
Test plan for "unmanaged generic structs"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#31374]
Proposal: https://github.com/dotnet/csharplang/issues/1744

This issue is a place to collect test ideas and track their validation. Use the [compiler test plan](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Compiler%20Test%20Plan.md) as a tool for brainstorming.

- [x] validate with LangVersion 7.3
- [x] test with tuple type ([SO](https://stackoverflow.com/questions/53992855/how-do-a-struct-containing-valuetuple-can-satisfy-unmanaged-constraint-but-valu) thread) #32103 
- [x] write speclet (contained under Design section of proposal)
- ~~[ ] update compiler test plan~~ (doesn't appear to be anything to add)
- [x] test public API `IsUnmanagedType` in new scenarios
- [x] Test for ref structs
- [x] Test the IsManagedType API as suggested by Julien
- [x] Test moveability (existing rules should be sufficient)
- [x] Have at least one test spit some IL to look at and have a few tests run with "expected output" to make sure the CLR can handle the code.
- [x] Stackalloc array of items
- [x] (Mutually) Recursive struct definition
  - [x] Also check the IsUnmanagedType API for these
- [x] Fixed-size buffer inside generic struct
- [x] Also check across metadata (metadata struct definition has private object or unmanaged field)
  - [x] Also private `T` field
- [x] For all places unmanaged type is required, we should have a test that covers that code path and ensures that the required feature diagnostic is produced at language version < 8.0
  - [x] addressOf `&`
  - [x] `fixed` with address of field
  - [x] `fixed` with array of generic structs
  - [x] `sizeof`
  - [x] `stackalloc` with size
  - [x] implicit `stackalloc` with initializer
  - [x] field of type pointer to unmanaged generic struct
  - [x] unmanaged constraint

**Comment by RikkiGibson** [comment]
from @agocke 

> Test for ref structs
Test the IsManagedType API as suggested by Julien
Test moveability (exiting rules should be sufficient)
Have at least one test spit some IL to look at and have a few tests run with "expected output" to make sure the CLR can handle the code.

**Comment by RikkiGibson** [comment]
Closing because the feature has been merged
