### ISSUE TITLE
async completion: check that TextTypedSoFarMatchesItem support typing English names in non-English locales

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#31384]
We borrowed the following code from the original completion:

```
     return item.DisplayText.StartsWith(textTypedSoFar, StringComparison.CurrentCultureIgnoreCase) ||
                       item.FilterText.StartsWith(textTypedSoFar, StringComparison.CurrentCultureIgnoreCase);
```

It should be re-considered to support non-English items.

**Comment by CyrusNajmabadi** [comment]
is there something blocking supporting this?  isn't this a pretty core case?

**Comment by CyrusNajmabadi** [comment]
Sounds good.  For my own understanding, do we think we ahve a chance in behavior here with how Roslyn currently works in non-english locals?

**Comment by CyrusNajmabadi** [comment]
Closing out.
