### ISSUE TITLE
Duplicate diagnostics in error list

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#31381]
![image](https://user-images.githubusercontent.com/10605811/49052309-23a6de80-f1a0-11e8-92c0-9cf6e9658065.png)

Found this while dogfooding the new unused expression analyzer from https://github.com/dotnet/roslyn/pull/30777. Attaching the debugger, I confirmed the IDE diagnostic service is calling the analyzer twice for the same operation block, leading to duplicate diagnostics in the error list + duplicate diagnostics being passed to FixAll invocation, which in turn can cause the fixer to randomly throw on FixAll code path.

**Comment by mavasani** [comment]
Tagging @heejaechang

**Comment by heejaechang** [comment]
I can take a look. but I am not sure why it shows up twice if 2 are from exactly thing (proejct/file/analyzer) since second one should just replace previous one.
