### ISSUE TITLE
async completion: re-consider using snapshots for caret positioning after edit

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#31383]
1. `edit.Apply();` provides a snapshot with Roslyn changes but with potential extension changes in it.
2. `subjectBuffer.CurrentSnapshot `is the original snapshot

re-consider which one to use in:
1. `view.TryMoveCaretToAndEnsureVisible`
2. `triggerSnapshotSpan.TranslateTo`

**Comment by CyrusNajmabadi** [comment]
What does hte original completoin code do here?

**Comment by ivanbasov** [comment]
@CyrusNajmabadi this corresponds to the following original code:

1. `view.TryMoveCaretToAndEnsureVisible` corresponds to 
https://github.com/dotnet/roslyn/blob/master-vs-deps/src/EditorFeatures/Core/Implementation/IntelliSense/Completion/Controller_Commit.cs#L159

where we execute 
```
private void SetCaretPosition(int desiredCaretPosition)
{
    // Now, move the caret to the right location.
    var graph = new DisconnectedBufferGraph(this.SubjectBuffer, this.TextView.TextBuffer);
    var viewTextSpan = graph.GetSubjectBufferTextSpanInViewBuffer(new TextSpan(desiredCaretPosition, 0));
    var desiredCaretPoint = new SnapshotPoint(TextView.TextBuffer.CurrentSnapshot, viewTextSpan.TextSpan.Start);
    TextView.Caret.MoveTo(new SnapshotPoint(TextView.TextBuffer.CurrentSnapshot, viewTextSpan.TextSpan.Start));
}
```

2. `triggerSnapshotSpan.TranslateTo` corresponds to https://github.com/dotnet/roslyn/blob/master-vs-deps/src/EditorFeatures/Core/Implementation/IntelliSense/Completion/Controller_Commit.cs#L171

```
    var spanToFormat = triggerSnapshotSpan.TranslateTo(
    this.SubjectBuffer.CurrentSnapshot, SpanTrackingMode.EdgeInclusive);
    var document = this.GetDocument();
    var formattingService = document?.GetLanguageService<IEditorFormattingService>();
```
