### ISSUE TITLE
Proposal: Adapter assemblies (external IVT replacement proposal)

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#31393]
I propose creating an adapter assembly in dotnet/roslyn for each assembly (or project) that currently has IVT access to Roslyn but does not live in this repository.

* IVTs from Roslyn layers to the adapter assemblies would be allowed
* IVTs from Roslyn layers to assemblies outside of dotnet/roslyn would not be allowed
* ~~IVTs from the adapter assemblies to assemblies outside of dotnet/roslyn would not be allowed~~ This rule was eliminated in order to prevent unknown other components from treating the adapter interfaces as public APIs.

This proposal maximizes the ability of developers working in dotnet/roslyn to make changes to non-public APIs without breaking downstream code. In cases where an internal API is used by a product primarily used outside of dotnet/roslyn (e.g. TypeScript), the change to the internal API can be accompanied in the same pull request by a corresponding change to the adapter assembly. From the perspective of the outside product, these changes would be non-breaking.

This proposal also avoids the requirement that external projects create or use an analyzer to avoid breaking changes due to IVTs.

The primary drawback of this proposal is some code duplication may occur in the adapter assemblies. However, this duplication serves a specific and valuable purpose: it isolates downstream code from refactoring operations performed in Roslyn.

**Comment by CyrusNajmabadi** [comment]
To clarify: This is the approach that Xaml took, right?  We'd just be expandin this out for TS/JS/F# as well?

Or is this approach different than the Xaml approach in some significant way?

Thanks!

**Comment by sharwell** [comment]
> To clarify: This is the approach that Xaml took, right?

This is slightly different. The Microsoft.VisualStudio.LanguageServices.Xaml assembly has the following IVT, which would not be allowed under this proposal:

https://github.com/dotnet/roslyn/blob/ca25a73345d5b89f60a4332f4eeb919a2441ec9d/src/VisualStudio/Xaml/Impl/Microsoft.VisualStudio.LanguageServices.Xaml.csproj#L23

**Comment by CyrusNajmabadi** [comment]
Ok.  So they woudl need to export anything they needed publicly?  I personally don't have a problem with htat.  Though would there be a concern with *other* parties then taking a dependency on these dlls?

**Comment by jmarolf** [comment]
Allowing IVT on the adapter assemblies still seems like a better place to be than where we are today though.

**Comment by sharwell** [comment]
The framework for this proposal was implemented in #31941, and the adapter assemblies may now be used to progressively eliminate IVTs.
