### ISSUE TITLE
Pending issues to address in Unused value code fix provider 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#31398]
This issue tracks addressing all pending comments from https://github.com/dotnet/roslyn/pull/31387 and https://github.com/dotnet/roslyn/pull/30777 as a follow-up PR to https://github.com/dotnet/roslyn/pull/31391

- [x] https://github.com/dotnet/roslyn/pull/31391#commitcomment-31472938
- [x] https://github.com/dotnet/roslyn/pull/31387/files#r236553196
- [x] https://github.com/dotnet/roslyn/commit/dacca3d1bd6509935e4d01cf3f0e242075c217f2#r31465616
- [x] https://github.com/dotnet/roslyn/commit/dacca3d1bd6509935e4d01cf3f0e242075c217f2#r31467539
- [ ] https://github.com/dotnet/roslyn/commit/dacca3d1bd6509935e4d01cf3f0e242075c217f2#r31467546
- [ ] https://github.com/dotnet/roslyn/commit/dacca3d1bd6509935e4d01cf3f0e242075c217f2#r31467552 and https://github.com/dotnet/roslyn/commit/dacca3d1bd6509935e4d01cf3f0e242075c217f2#r31472982 and https://github.com/dotnet/roslyn/commit/dacca3d1bd6509935e4d01cf3f0e242075c217f2#r31473038
- [x] Consider https://github.com/dotnet/roslyn/commit/dacca3d1bd6509935e4d01cf3f0e242075c217f2#r31467643

**Comment by mavasani** [comment]
Tagging @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
👍 It would be good to enumerate the issues.  But otherwise, i'm good :)

**Comment by mavasani** [comment]
@CyrusNajmabadi Added list to the description

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing out.
