### ISSUE TITLE
using statement allows possible race condition that prevents disposing

### ISSUE THREAD

**Issue by MichaelPuckett2** [dotnet/roslyn#31426]
**Version Used**: *, 7.3 (all previous versions)

**Steps to Reproduce**:

1. Start a ```using``` with some disposable type (preferably in a separate thread).
2. Abort the thread by any means after initializing the type but before entering the auto wired ```try```
3. The disposable type never gets disposed properly.

**Expected Behavior**:
We should expect that ```using``` statement will always dispose of a type regardless of error.

**Actual Behavior**:
The disposable type used via a ```using``` statement is exposed to a possible race condition where it may never get disposed.

The currently generated IL when using a ```using``` statement works like this:

```
R r = new R();
try
{
    //Do something with r
}
finally
{
    r?.Dispose();
}

```
IL Generated:

```
  IL_0001:  newobj     instance void Question_Answer_Console_App.R::.ctor()
  IL_0006:  stloc.0
  .try
  {
    IL_0007:  nop
    IL_0008:  nop
    IL_0009:  leave.s    IL_0016
  }  // end .try
  finally
  {
    IL_000b:  ldloc.0
    IL_000c:  brfalse.s  IL_0015
    IL_000e:  ldloc.0
    IL_000f:  callvirt   instance void [mscorlib]System.IDisposable::Dispose()
    IL_0014:  nop
    IL_0015:  endfinally
  }  // end handler
```

Note that there is a possible race condition when initializing ```R``` or before entering ```try``` with ```R``` which prevents the opportunity for ```finally``` to be called for disposal.

Here is one solution that would allow ```R``` to be initialized inside of the ```try``` with a ```using``` statement.  Have the ```using``` auto generated code work more like this:

```
R r = null;
try
{
    r = new R();
    //Do something with r
}
finally
{
    r?.Dispose();
}
```
IL Generated something like this:

```
  IL_0001:  ldnull
  IL_0002:  stloc.0
  .try
  {
    IL_0003:  nop
    IL_0004:  newobj     instance void Question_Answer_Console_App.R::.ctor()
    IL_0009:  stloc.0
    IL_000a:  nop
    IL_000b:  leave.s    IL_001c
  }  // end .try
  finally
  {
    IL_000d:  nop
    IL_000e:  ldloc.0
    IL_000f:  brtrue.s   IL_0013
    IL_0011:  br.s       IL_001a
    IL_0013:  ldloc.0
    IL_0014:  call       instance void Question_Answer_Console_App.R::Dispose()
    IL_0019:  nop
    IL_001a:  nop
    IL_001b:  endfinally
  }  // end handler
```

Here is a console app demonstrating the problem with using:  

```
using System;
using System.Threading;

namespace Question_Answer_Console_App
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Start Main");

            Thread thread = null;
            thread = new Thread(new ThreadStart(() =>
            {
                Console.WriteLine("Thread Started");
                using (var r = new R(thread))
                {
                    Console.WriteLine($"Using {nameof(R)}");
                }
            }));

            thread.Start();
            thread.Join();

            Console.WriteLine("End Main");
            Console.ReadKey();
        }
    }

    public class R : IDisposable
    {
        public R(Thread thread)
        {
            Console.WriteLine($"Init {nameof(R)}");
            //Comment out the line below to see R used as expected; leave as is to expose the possible race condition.
            thread.Abort(); //We abort during initialization and never get disposed. Although aborting here doesn't initialize or assign the type to a variable it can be assumed aborted just as if it happened immediately after the assignment and before the try.
        }

        public void Dispose()
        {
            Console.WriteLine($"Disposed {nameof(R)}");
        }
    }
}
```
This outputs:

> Start Main
> Thread Started
> Init R
> End Main

When we are expecting the output to be this:

> Start Main
> Thread Started
> Init R
> Using R
> Disposed R
> End Main

**Comment by gafter** [comment]
The proposed code sequence still has a race condition (if an exception occurs before the `stloc` instruction).

**Comment by MichaelPuckett2** [comment]
@gafter Which ```stloc``` are you referring to?  ```IL_0002``` or ```IL_0009```?

**Comment by MichaelPuckett2** [comment]
@gafter Maybe the fix I've suggested isn't the correct answer but please don't place those tags on this issue.  I'm asking you look into this deeper for the community; there is a lot of confusion and discussion about this issue online and the best fix is to avoid the ```using``` statement and write your own ```try finally``` much like I've done above.  Once we enter ```try``` we assume we are safely going to also enter ```finally``` but with the ```using``` statement we can't safely assume the same.

**Comment by sharwell** [comment]
Related: http://joeduffyblog.com/2009/03/13/managed-code-and-asynchronous-exception-hardening/

**Comment by gafter** [comment]
@MichaelPuckett2 There is no "correct answer". There is no code sequence that could ensure that the object resulting from `new R()` is disposed whenever an exception occurs. The proof is simple. When an exception occurs, the evaluation stack is cleared and the runtime begins processing the exception. `new R()` leaves the new object on the stack. If an exception occurs on the instruction following it, the stack is cleared. Once the stack is cleared, the newly allocated object is unreachable and therefore cannot be disposed by the user's code.

This is, admittedly, a flaw in the design of the CLR virtual machine. But it isn't something that Roslyn can do something about. That's why this is marked "Won't Fix".

**Comment by sharwell** [comment]
The solution here is to never, ever use `Thread.Abort()`.

**Comment by sharwell** [comment]
Relabeling as Language Design since the language specification [explicitly specifies](https://github.com/dotnet/csharplang/blob/master/spec/statements.md#the-using-statement) this behavior.
