### ISSUE TITLE
Missing nullable warnings in member initializers

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#31440]
**Version Used**: 

Branch C# 8.0: Nullable reference type (29 Oct 2018)
https://github.com/dotnet/csharplang/blob/master/proposals/nullable-reference-types.md
Latest commit 2f8fef by AlekseyTs:
Compare Nullable modifiers while comparing type symbols by default. (#30770)

**Steps to Reproduce**:

Compile the following code
```cs
#nullable enable
public class C {
    public static string? field;
    public string s = field.ToString(); // no warning
    public void M() => field.ToString(); // warning CS8602: Possible dereference of a null reference.
}
```

https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDk4BstWFiAJQkiQDsBjCAFQE8AHFAHwGIztd8IACCMvAgFgAUAAEAzN1EAmbgGFuAbxHdVUyaICMANimaADAH5uYAJYQsAEwDcKtRL37uybgF4T5qwDpqAewDKMAimZADmABQAlNbcAPSx3GS+3ADuUAhkIaF2qg6iACzcALJRbgB8HhaWPgFBWVEx8anpmWEiAL5AA

**Expected Behavior**:

Consistent warnings for both dereferencing of `field`.

**Actual Behavior**:

Field initializer does not have the warning

**Comment by DarthVella** [comment]
This is also a problem when directly assigning null to a non-nullable member. However, it only arises if there is no explicit constructor (or static constructor, for static variables). For instance:

```csharp
using System;
#nullable enable

class MyObject 
{
    public static string myStaticString = null; //no warning

    public string myString = null; //no warning
}

class MyOtherObject 
{
    public static string myStaticString = null; //correct warning
    static MyOtherObject() { }

    public string myString = null; //correct warning
    public MyOtherObject() { }
}
```

**Comment by cston** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/33093.
