### ISSUE TITLE
Investigate moving certain IDE features (Outlining) from EditorFeatures.Wpf down to EditorFeatures

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#31458]
For VSMac we need Outlining to work in the portable layers (since we're not including the EF.Wpf layer in our MEF composition.

We'd need to investigate moving it down to the EditorFeatures layer or maybe some other solution. Perhaps if we move the core logic down then we can have a thin tagger on our side, without the need to move all of it down.

The timeline for this is pretty aggressive (January) so it would be really nice to have this prioritized.

**Comment by gundermanc** [comment]
Adding context from last time I touched structure in the editor:

The main WPF dependency in Roslyn's outlining appears to be for hosting WPF text views in Preview/Structure tips. Editor now provides a default tooltip, so, Roslyn can just delete their `IBlockContextSource` and they'll get our structure tips.

Outlining tips aren't provided by default yet, however, so Editor would need to make a similar change to provide a default presentation: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/561174

**Comment by decriptor** [comment]
The default tooltip doesn't provide a view with colored classifications though, right?

**Comment by gundermanc** [comment]
I don't think there is a default tooltip. That bug suggests adding one with colorization so that all VS languages can benefit.

**Comment by gundermanc** [comment]
IMO, the right thing would be for editor to provide a default colorized experience for these tips. Getting this done might take some time, however, as we're deep in P2 prep at the moment. Maybe start a thread with Kirill and Editor team?

**Comment by CyrusNajmabadi** [comment]
Can the editor not just do what roslyn does and just create a tiny projection/ellision buffer here?

**Comment by gundermanc** [comment]
Yep, it can, and that's what I'm advocating for. It's an issue of scheduling.

**Comment by CyrusNajmabadi** [comment]
@gundermanc Gotcha.  Could you literally just take our code and use that?  Then it would just be something cheap and easy to slot in in some sprint?

**Comment by jasonmalinowski** [comment]
This has been cleaned up now.
