### ISSUE TITLE
Trivia gets shuffled around when batch fixing InlineDeclaration codefix

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#31459]
Follow up to #28793

**Steps to Reproduce**:
https://github.com/dotnet/roslyn/blob/fd8e3abfa79223eba321d8c29cfb14cef5da4df4/src/EditorFeatures/CSharpTest/InlineDeclaration/CSharpInlineDeclarationTests_FixAllTests.cs#L312-L330

**Expected Behavior**:
```csharp
void M() 
{ 
    /* leading */
    // trailing
    int.TryParse(v, out int i1);
    int.TryParse(v, out int i2);
}
```
**Actual Behavior**:

```csharp
void M() 
{ 
    // trailing
    /* leading */
    int.TryParse(v, out int i1);
    int.TryParse(v, out int i2);
}
```

**Comment by CyrusNajmabadi** [comment]
The repro-steps link doesn't work.

**Comment by Suchiman** [comment]
@CyrusNajmabadi i don't understand why the link broke given that it's a permalink but it was about this test: https://github.com/dotnet/roslyn/blob/cb5675ac75e1f90aab34c8f816b22de8f3bbfbe7/src/Analyzers/CSharp/Tests/InlineDeclaration/CSharpInlineDeclarationTests_FixAllTests.cs#L352-L374
However it looks like that in the meantime, https://github.com/dotnet/roslyn/pull/30917/files#diff-9cc3f991b0a003fc73ad859e16ab11c3a5e91d24d7eba4e6a5e36d2e85e57391L324-L327 fixed this behavior.

**Comment by CyrusNajmabadi** [comment]
Closing as fixed.  Thanks!
