### ISSUE TITLE
Listing recent files in "GoTo All" by default

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#31467]
Hitting `r` should not be necessary.

**Comment by sharwell** [comment]
@olegtk Would this be an editor feature request instead of Roslyn?

**Comment by olegtk** [comment]
yes. @jinujoseph, please route to the editor.

**Comment by jinujoseph** [comment]
Moved to editor team [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/739238)
