### ISSUE TITLE
Incremental search in Ctrl+. menu

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#31468]
With more analyzers from various sources (like roslynator), finding options gets tedious.

**Comment by jinujoseph** [comment]
cc @olegtk for info

**Comment by olegtk** [comment]
good idea, please route to the editor.

**Comment by jinujoseph** [comment]
Ported to [editor](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/740042) team

**Comment by alrz** [comment]
Thanks.
