### ISSUE TITLE
Wrong result of 'introduce local' for interpolated string target typed to FormattableString

### ISSUE THREAD

**Issue by MadsTorgersen** [dotnet/roslyn#3147]
``` c#
static void Main(string[] args)
{
    string s = FormattableString.Invariant($"");
}
```
(Needs .NET 4.6 for availability of `FormattableString`). 

Select `$""`, and control-dot to "Introduce local".

The result:

``` c#
static void Main(string[] args)
{
    var v = $"";
    string s = FormattableString.Invariant((FormattableString)v);
}
```

With a red squiggle under `(FormattableString)v`. This is wrong. The extraction should have been:

``` c#
static void Main(string[] args)
{
    FormattableString v = $"";
    string s = FormattableString.Invariant(v);
}
```

So that the interpolated string continues to be correctly target typed to `FormattableString`.

**Comment by DustinCampbell** [comment]
Fixed with PR #3158
