### ISSUE TITLE
Why symbol for ArrayTypeSyntax or ElementAccessExpressionSyntax is null sometimes?

### ISSUE THREAD

**Issue by ceztko** [dotnet/roslyn#31471]
**Version Used**: 
2.10.0

**Steps to Reproduce**:

1. Compile and execute in the following class:

```c#
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ConsoleApp1
{
    class Program
    {
        const string TestClass =
@"using System;

namespace HelloWorld
{
    public class Test
    {
        static void Foo()
        {
            double[] test;
            var array = new double[9]; // Symbol for ArrayTypeSyntax double[9] is null
            array[3] = 2;              // Symbol for ElementAccessExpressionSyntax array[3] is null
        }
    }
}
";
        static void Main(string[] args)
        {
            SyntaxTree tree = CSharpSyntaxTree.ParseText(TestClass);

            var root = (CompilationUnitSyntax)tree.GetRoot();
            var compilation = CSharpCompilation.Create("HelloWorld")
                              .AddReferences(
                                 MetadataReference.CreateFromFile(
                                   typeof(object).Assembly.Location))
                              .AddSyntaxTrees(tree);

            var walker = new Walker(compilation);
            walker.Visit(tree.GetRoot());
        }


        class Walker : CSharpSyntaxWalker
        {
            public Compilation Compilation { get; private set; }

            public Walker(Compilation compilation)
            {
                Compilation = compilation;
            }

            public override void VisitArrayType(ArrayTypeSyntax node)
            {
                Debug.Assert(GetSymbol(node) == null); // <-- symbol(double[9]) == null
                base.VisitArrayType(node);
            }

            public override void VisitElementAccessExpression(ElementAccessExpressionSyntax node)
            {
                Debug.Assert(GetSymbol(node) == null); // <-- symbol(array[3]) == null
                Debug.Assert(GetSymbol(node.Expression) != null);
                base.VisitElementAccessExpression(node);
            }

            ISymbol GetSymbol(SyntaxNode node)
            {
                var model = Compilation.GetSemanticModel(node.SyntaxTree);
                return model.GetSymbolInfo(node).Symbol;
            }
        }
    }
}
```

2. Observe behavior of the syntax walker in the `ArrayTypeSyntax` "double[9]" and `ElementAccessExpressionSyntax` "array[3]".

**Actual Behavior**:
The symbol from the `SemanticModel` is null for these syntax nodes.

**Expected Behavior**:
I'm asking if this behavior is by design or the semantic model could provide more useful information in these cases. For example:
- In the case of array initialization `new double[9]`, the symbol info for `double[9]` could be the `ITypeSymbol` for `double[]`.
- In the case of assignment `array[3] = 2;`, the symbol info for `array[3]` could be the `ILocalSymbol` for `array`.

**Comment by CyrusNajmabadi** [comment]
I believe this is all by design.

>  the symbol info for array[3] could be the ILocalSymbol for array.

The goal of roslyn is to be strict and specific about the answers it gives.  `array[3]` is not the same from the language's perspective as `array`, which it what would be implied if GetSymbolInfo returned the same symbol there.

`array[3]` is an expression which has no corresponding symbol from the language's perspective.  it would have a 'type', which is why you can call GetTypeInfo on it.  You can also grab the IOperation tree for this, which would then easily tell you that this was an Array-Access, and the thing being accessed was a local-symbol-reference.

**Comment by CyrusNajmabadi** [comment]
Tagging @gafter .  But this all feels correct and exact to me.

**Comment by gafter** [comment]
Yes, this is by design, as explained by @CyrusNajmabadi.  The expression `array[3]` is not a reference to a symbol.

**Comment by ceztko** [comment]
> Yes, this is by design, as explained by @CyrusNajmabadi. The expression `array[3]` is not a reference to a symbol.

Thank you. Maybe  the case `double[9]` is more interesting? I think in that case it would be quite appropriate for `GetSymbolInfo().Symbol` to return the `ITypeSymbol` for `double[]`?

**Comment by CyrusNajmabadi** [comment]
> Thank you. Maybe the case double[9] is more interesting? I think in that case it would be quite appropriate for GetSymbolInfo().Symbol to return the ITypeSymbol for double[]?

What does GetSymbolInfo give you on `double[]` in `new double[] { 1, 2, 3}`?  If it gives you the type symbol for `double[]`, then i could see an argument that it should do the same for `new double[3] { 1, 2, 3 }`.

**Comment by ceztko** [comment]
> What does GetSymbolInfo give you on `double[]` in `new double[] { 1, 2, 3}`? If it gives you the type symbol for `double[]`, then i could see an argument that it should do the same for `new double[3] { 1, 2, 3 }`.

I Just tried: symbol for `double[]` in the array initializer expression `new double[] { 1, 2, 3}` is still `null`. But thank you **a lot** because now I reasoned and maybe I can explain it myself: if one asks for `double[]` symbol in the initalizer expression it should point to a "constructor" like symbol, if it existed. Because it does not exist, and to not be inconsistent with other initializer expressions which returns a `IMethodSymbol` in this context, better return null. Maybe I confused the `GetSymbolInfo` contract like a best effort attempt to return an useful symbol, but now everything is clearer to me. Thanks also @gafter for support.

**Comment by CyrusNajmabadi** [comment]
Sounds good! :)

     -- Cyrus
