### ISSUE TITLE
Should MatchFailureException capture an unreified tuple input?

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#31482]
We have tests like the following:

``` c#
        [Fact]
        public void UnmatchedInput_06()
        {
            var source =
@"using System;
public class C
{
    static void Main()
    {
        Console.WriteLine(M(1, 2));
        try
        {
            Console.WriteLine(M(1, 3));
        }
        catch (MatchFailureException ex)
        {
            Console.WriteLine($""{ex.GetType().Name}({ex.UnmatchedValue})"");
        }
    }
    public static int M(int x, int y) {
        return (x, y) switch { (1, 2) => 3 };
    }
}
namespace System
{
    public class MatchFailureException : InvalidOperationException
    {
        public MatchFailureException() {}
        public MatchFailureException(object unmatchedValue) => UnmatchedValue = unmatchedValue;
        public object UnmatchedValue { get; }
    }
}
";
            var compilation = CreatePatternCompilation(source);
            compilation.VerifyDiagnostics(
                // (17,23): warning CS8509: The switch expression does not handle all possible inputs (it is not exhaustive).
                //         return (x, y) switch { (1, 2) => 3 };
                Diagnostic(ErrorCode.WRN_SwitchExpressionNotExhaustive, "switch").WithLocation(17, 23)
                );
            CompileAndVerify(compilation, expectedOutput: @"3
MatchFailureException()");
        }
```

Note that the exception throw in this case does not contain the `UnmatchedValue` that was input to the switch expression.  The reason the compiler does not pass that tuple to the exception constructor is that the compiler never constructs the tuple at all.  Rather the compiler produces the decision tree based on the individual values that were the input.  Because of that the generated code does not even have a runtime dependence on the presence of the `ValueTuple` library.

This is consistent with the [design of the `MatchFailureException` type](https://github.com/dotnet/corefx/issues/33284) and the LDM's specification that the captured value shall be provided when it is "trivial" to do so.  However, it would be possible for the compiler to produce code that constructs the tuple just for the failure case.

This is a tracking issue while we seek guidance on how to handle this situation.

**Comment by alrz** [comment]
It's interesting that F# MatchFailureException is quite different

`MatchFailureException(filename, line, col)`

But that's probably is not much useful.

**Comment by alrz** [comment]
I think this totally worth it, so we don't have to throw UnexpectedValue in switch expressions ever.

That said, there should be a way to cleanly suppress the warning in the first place, via `switch!` or alike.

**Comment by gafter** [comment]
The LDM decided today that yes, we should capture a tuple in the `SwitchExpressionException` (the exception's new name).
