### ISSUE TITLE
Roslyn-packages wiki page is missing latest version

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#31496]
[A 2.10.0 package version is on nuget](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Workspaces).

But [the wiki page](https://github.com/dotnet/roslyn/wiki/NuGet-packages) that explains version correlation between Roslyn and VS only goes up to 2.9.

Can we update the wiki page?

**Comment by jinujoseph** [comment]
cc @jcouv

**Comment by jcouv** [comment]
Added 2.10 to the wiki page: https://github.com/dotnet/roslyn/wiki/NuGet-packages

Thanks
