### ISSUE TITLE
Index overloads showing up before int overloads in IntelliSense

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#31514]
With the newly added Index/Range overloads, the `Index` overload is being shown first:
![first](https://user-images.githubusercontent.com/2642209/49415877-03e65c00-f746-11e8-83b1-990cd3d2e96c.png)
before the `int` overload
![second](https://user-images.githubusercontent.com/2642209/49415946-47d96100-f746-11e8-8108-d769330c36f4.png)
as it's ordering them in alphabetical order.

I suggest we tweak IntelliSense so that it orders the `int` overload before `Index`, as it's the simpler concept that's been around for much longer, and doesn't require further investigation into what exactly an `Index` is and how you create one.

cc: @DustinCampbell

**Comment by CyrusNajmabadi** [comment]
Sorting of this is controlled with ISymbolExtensions2.Sort:

```c#
    internal partial class ISymbolExtensions2
    {
        public static ImmutableArray<TSymbol> Sort<TSymbol>(
            this ImmutableArray<TSymbol> symbols,
```

Right now it sorts by typename.  So `Int32 > Index`.  I'm not sure if we'd want a specific rule for this case.  Or a general rule like 'builtins sort befor non-builtins'.

**Comment by Joe4evr** [comment]
Related to IntelliSense sorting, [I made a suggestion a little over a year ago](https://github.com/dotnet/csharplang/issues/39#issuecomment-342937873) about marking a particular overload with some new attribute to prioritize it. In there it was specifically about constructors in Record types, but a more general implementation might be more useful.

**Comment by sharwell** [comment]
> Sorting of this is controlled with ISymbolExtensions2.Sort:

Can we not control selection here instead of indentation?

**Comment by CyrusNajmabadi** [comment]
Indentation?

**Comment by sharwell** [comment]
@CyrusNajmabadi Apparently I wrote that while 😴

**Comment by CyrusNajmabadi** [comment]
> Can we not control selection here instead of sorting?

Potentially.  though i'm not sure why that would necessarily be any better.  It seems like it would be odder (to me at least) to have things sorted 'Indexer -> int' but then select the 2nd item, versus just ordering 'Int -> indexer'.  But i'm not opposed to either approach :)

**Comment by stephentoub** [comment]
Now that C# 8 will support lowering to the int-based indexers, we'll be deleting the new indexers we added to span.  As such, from my perspective this can be closed, but I won't do so in case you want to allow it to track something else.

**Comment by mikadumont** [comment]
Design meeting notes: We will not fix until we have a motivating scenario.
