### ISSUE TITLE
New find-in-files does not properly colorize line.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#31529]
![image](https://user-images.githubusercontent.com/4564579/49478649-38552900-f7d5-11e8-8534-9266130f8e45.png)

This doesn't match the Find-Refs experience, even though it's using the new Find-Refs tree control.  This makes the experience feel inconsistent.

**Comment by davkean** [comment]
@CyrusNajmabadi This is owned by editor, can you Help -> Send Feedback -> Report a Problem if you want to track it, or I can just file internally. I've already filed this one personally internally so I can just do a plus 1 on this if you'd like.

**Comment by jinujoseph** [comment]
@davkean can you point to your internal bug pls

**Comment by davkean** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/719601

**Comment by CyrusNajmabadi** [comment]
Closing out as tracked elsewhere.
