### ISSUE TITLE
Icons missing in solution explorer in 2019.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#31528]
Note sure the best place to file this:

![image](https://user-images.githubusercontent.com/4564579/49475508-494d6c80-f7cc-11e8-9ec0-359b15888d94.png)

**Comment by Pilchie** [comment]
@lifenglu have you heard of this?

**Comment by CyrusNajmabadi** [comment]
Repros in the lavender theme as well: 

![image](https://user-images.githubusercontent.com/4564579/49479123-bf56d100-f7d6-11e8-9f7c-a53d21575434.png)

**Comment by Huy-Nguyen-MSFT** [comment]
@CyrusNajmabadi - Would you please let us know how you opened the Roslyn solution - double click SLN file, from Start Window Most Recently Used list, or from Start Window Open Project button? Thanks.

**Comment by CyrusNajmabadi** [comment]
The first two for certain.  I don't think i did the last one.  I also use this:

![image](https://user-images.githubusercontent.com/4564579/49548841-d01d4a80-f89b-11e8-99e2-3b122d6ff54f.png)
