### ISSUE TITLE
Compiler error deconstructing expression with dynamic

### ISSUE THREAD

**Issue by jamesfoster** [dotnet/roslyn#31533]
I get a compiler error when deconstructing a tuple type when the expressions contains a reference to a dynamic variable. 

```
error CS8133: Cannot deconstruct dynamic objects.
error CS8130: Cannot infer the type of implicitly-typed deconstruction variable '_'.
error CS8183: Cannot infer the type of implicitly-typed discard.
```

Here's a repo which exhibits the compiler errors: https://github.com/jamesfoster/DeepEqual/tree/roslyn-compiler-error

**Version Used**: 
Visual Studio: 15.9.3
.NET Core SDK:   2.1.500
.NET Core runtime: 2.1.6

**Steps to Reproduce**:

1. `git clone https://github.com/jamesfoster/DeepEqual.git`
2. `cd DeepEqual`
3. `git checkout roslyn-compiler-error`
4. `dotnet build src/DeepEqual.sln`

**Expected Behavior**:

No compiler errors since the return type is statically typed.

**Actual Behavior**:

```
error CS8133: Cannot deconstruct dynamic objects.
```

**Comment by HaloFour** [comment]
I believe this behavior is expected.  As soon as a `dynamic` is in the mix the compiler defers evaluation of the entire expression until runtime, including the call to `makeTuple`.  As a result the return value of `makeTuple` in that expression returns `dynamic` as well, and C# doesn't support deconstructing dynamic values.

I'd suggest that the compiler is behaving per spec and that if you're interested in seeing that changed you might want to bring it up on the [csharplang](https://github.com/dotnet/csharplang) repository.

**Comment by jamesfoster** [comment]
I didn't realise the return type was dynamic. I'm closing this as not a bug. It's working as expected.
