### ISSUE TITLE
Time for diagnostics to update in a file has regressed in vs2019

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#31539]
Feels like it's about a second slower than it normally should be.  It's *very* noticible, especially switching back and forth between VS2017 and 2019.

**Comment by CyrusNajmabadi** [comment]
Actually, it's more lke 3-4 seconds slower.  Super bad.  It feels like we're up to like 5 seconds for diagnostics.

**Comment by sharwell** [comment]
@jasonmalinowski Do we already have a bug filed for this?

**Comment by jasonmalinowski** [comment]
Yes, this is a dupe of #30993 which we expect is fixed by #31265.

**Comment by jasonmalinowski** [comment]
Unfortunately, the fix is not in Preview 1.

**Comment by Neme12** [comment]
It's super bad, I'm switching back to 2017 :confused:

**Comment by CyrusNajmabadi** [comment]
Great.  Thanks for letting me know.  Hopefully this will be in a preview coming soon.
