### ISSUE TITLE
provide a service to use structured db

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#31532]
right now, we are using IPersistentStorageService (http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Host/PersistentStorage/IPersistentStorageService.cs,8) to save data to persistent storage. to make it really general it is designed to work as name/value store where value is a stream.

this is the most general form to save any arbitrary data but also it is the most inefficient way to save data. for one, it has to read everthing from the persistent storage, re-construct data and get the data it wants and throw everything away. 

we can't read only the data we want, we can't search data without bring it to memory, we can't update part of data without updating everything per key.

to make things more efficient, I believe we should start to support structured storage such as sql.

.NET already has standardized API set from System.Data.Common (https://docs.microsoft.com/en-us/dotnet/api/system.data.common?view=netstandard-2.0) to abstract out actual engine that supporting sql (ADO.NET)

we should build a service based on that to let components use much efficient form to save data rather than the bare minimum IPersistentStorageService

**Comment by CyrusNajmabadi** [comment]
Could you clarify these bits:

> for one, it has to read everthing from the persistent storage, re-construct data and get the data it wants and throw everything away.

wrt: "it has to read everthing from the persistent storage"

That shouldn't be the case.  Reading can be done on a per-key basis.  

> and get the data it wants and throw everything away.

Could you clarify this as well?  I'm not sure what this means?

We mentioned at one point the idea that one should be able to provide a way to read an existing checksum of the data, outside of needing to read in the data itself.  However, that seems like a simple adjustment to the storage subsystem that would not require moving to a structured db.

**Comment by CyrusNajmabadi** [comment]
Could you clarify some scenarios that would benefit from this approach?  thanks!

**Comment by heejaechang** [comment]
> it has to read everthing from the persistent storage"
That shouldn't be the case. Reading can be done on a per-key basis.

sure, I meant everything saved for the key. it is name/value storage, so sure, it gets data per key.

...

getting checksum is one. reading message, filepath, location, project and the other. 

are you asking since you truly not sure what I meant, or just asking for the ask of asking? value is blob, so one need to read whole blob to convert it to an object and then need to read some part of the data from the object and throw it away.

...

anyone who wants to save and read data will benefit from it. we can save diagnostic data or todo data's property as columns rather than blob. and can read only columns we need or query and read only one that matches query from db.

we can save symbol data and query it from the db rather than read whole thing in memory and then search through it

.. 

not sure what you are looking for.

**Comment by CyrusNajmabadi** [comment]
> are you asking since you truly not sure what I meant, or just asking for the ask of asking?

I don't know what this means.  I was asking since the claim did not seem correct.  

--

> we can save symbol data and query it from the db rather than read whole thing in memory and then search through it

How would you see this working?

**Comment by CyrusNajmabadi** [comment]
I'm working on an exmaple of how i think we coudl solve the largest issue we've seen here easily, without hte need for going whole-hog on a sql approach.

**Comment by heejaechang** [comment]
I am suggesting adding a way to use sql as sql will give us more options on how we save data and implement a feature.

for example, if I had sql from the beginning, I would have saved diagnostic and todo data as normal sql table and each property as column rather than converting it to stream and creating object from it and etc.

this will give us me an oppertunaty of adding new features like searching solution with certain diagnostics IDs or one that contains message much efficient than how we do now (load all diagnostics and then filter and throw things away).

same goes for todo.

if one want to use name/value storage, then let them use it. don't force people who want to use structured db to use name/value storage.

**Comment by CyrusNajmabadi** [comment]
>also, I am not sure what you mean by going whole-hog on sql approach?

I'm saying: we should examine the use cases to determine if we need a full new approach, or if we can built these sorts of capabilities easily onto the existing approach.

**Comment by heejaechang** [comment]
using name/value and using structured db affects how one design on how to persist data fundamentally. and there will be cases where name/value is more appropriate and where structured db is better solution. so I believe providing both solution will let people to choose best solution for thier problem rather than forcing one to choose one over the other just because it is not supported.

since usually features should be written over model where model hide details on how it actually save data. by following existing data model pattern, that concern should be de-coupled from a feature.

also, since we already have established .NET APIs for db, I dont think we have any concern on how it gets exposed to roslyn side from a specific sql engine implementation.

..

probably team will decide but I would prefer using existing sql and ADO.Net implementation rather than creating our own custom system for it. that's just more code for us to maintain.

**Comment by CyrusNajmabadi** [comment]
> probably team will decide but I would prefer using existing sql and ADO.Net implementation rather than creating our own custom system for it. that's just more code for us to maintain.

This is certainly worth looking into.  A core reason at the time was simply the perf around these approaches.  They were simply slower than the alternative, did not allow sharing of data across VS and the OOP process, didn't work across platforms, and had a much more complex data model.  For example, preventing races was more difficult as the burden of consistency was placed on the client of the API instead of having it be built-into hte API provided to the features using it.

**Comment by CyrusNajmabadi** [comment]
>  so I believe providing both solution will let people to choose best solution for thier problem rather than forcing one to choose one over the other just because it is not supported.

Note: i was commenting on things because it's really valuable to have use cases by which we can validate these sorts of assumptions.  Without use cases, it's unclear how we test to find out if things lke the above are true.  Thanks! :)

**Comment by CyrusNajmabadi** [comment]
Closing out.  This lacks a clear use case and a clear consumer that is having a problem that would need a rich sql interface to solve.  Right now the existing system works well both for each reading/writing of a key/value, and allows for high perf efficiency by allowing the client to know if they need to read/write the value with very low overhead.  This seems like a good place to be absent an actual explicit use case.
