### ISSUE TITLE
IFromEndIndexOperation.Symbol should be renamed

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#31544]
This API is named `Symbol`, but returns an `IMethodSymbol` that is specifically a constructor, which is not consistent with the rest of the API surface. We should rename this to something more specific before this ships as RTM and we can't anymore. FYI @dotnet/analyzer-ioperation @agocke.

**Comment by agocke** [comment]
Closed by https://github.com/dotnet/roslyn/pull/34306
