### ISSUE TITLE
NotNullIfNotNull

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#31549]
[jcouv update:] LDM [specified](https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-05-15.md) the `NotNullIfNotNull` attribute.

----

**Version Used**: 

16.0.0 Preview 1.0 with

```xml
    <LangVersion>8.0</LangVersion>
    <NullableReferenceTypes>True</NullableReferenceTypes>
```

**Steps to Reproduce**:

```cs
static class NonNullWhenNonNull
{
    class Base { }
    class Derived : Base { }

    static void M()
    {
        Base[] b = new Derived[] { new Derived() };
        Derived[] d = b.Convert<Base, Derived>(); // expected non-null bacause b is not null, but CS8600
    }

    public static TDerived[]? Convert<TBase, TDerived>(this 
        // I want [NonNullWhenNonNull] attribute.
        TBase[]? array)
        where TDerived : class, TBase
    {
        if (array is TDerived[] x) return x;
        if (array == null) return null;

        TDerived[] d = new TDerived[array.Length];
        TBase[] b = d;
        for (int i = 0; i < d.Length; i++)
            b[i] = array[i];
        return d;
    }
}
```

**Expected Behavior**:

There are some attributes proposed for method annotation e.g. `NotNullWhenTrue`, `NotNullWhenFalse` and so on. I want also a `NotNullWhenNonNull` attribute.

**Actual Behavior**:

No such an attribute.

**Comment by Joe4evr** [comment]
I believe the attribute for this is `[EnsuresNotNull] `.

**Comment by ufcpp** [comment]
@Joe4evr 
No, it's not.

```cs
static void Main()
{
    Assert(null); // throws and never return
    var x = Identity(null); // returns null iff the argument is null
}

[EnsuresNotNull]
static void Assert<T>(T value) where T : class ? { if (value == null) throw new Exception(); }

[NotNullWhenNotNull]
static T Identity<T>(T value) => value;
```

**Comment by Joe4evr** [comment]
Ah, that one is `[NullInNullOut]`.

**Comment by jcouv** [comment]
We're looking at adding an attribute `[NotNullIfNotNull(string)]` where the other parameter would be named. Details at https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-05-15.md#nullness-dependencies-between-inputs-and-outputs

**Comment by drewnoakes** [comment]
I just hit this in the project system (annotating `ProjectRuleSnapshotExtensions`) using 3.3.0-beta1-19327-04.

A smaller repro:

```c#
class C
{
    [return: NotNullIfNotNull("o")]
    object? M(object? o) => o;

    string T()
    {
        return M("").ToString();
        //     ^^^^^ CS8602 Dereference of possibly null reference
    }
}
```
