### ISSUE TITLE
Integration of null coalescing assignment and nullable reference type

### ISSUE THREAD

**Issue by Logerfo** [dotnet/roslyn#31555]
# Context
Currently, both null coalescing assignment and nullable reference types are available together in Visual Studio 19 Preview 1. However, I don't think they work together very well.

# Code
```c#
#nullable enable
namespace A {
   public class C {
      public void M() {
         C? c = null;
         c ??= new C();
         c.M();
      }
   }
}
```

# Expected behavior
The following code emits the same IL as the code above and has no warnings:
```c#
#nullable enable
namespace A {
   public class C {
      public void M() {
         C? c = null;
         if (c == null)
            c = new C();

         c.M();
      }
   }
}
```
For consistency reasons, the expected behavior for the stated code should also be zero warnings.

# Atual behavior
> Warning	CS8602	Possible dereference of a null reference.

**Comment by Logerfo** [comment]
Found this listed on https://github.com/dotnet/roslyn/issues/22152, seems like it's already planned for preview 2.

**Comment by jaredpar** [comment]
Thanks for reporting. This is fixed now and covered sufficiently by ` NullCoalescingAssignment_UseInExpression`
