### ISSUE TITLE
Control+, Go To Type show same info for partial class with certain filename.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31563]
<p>Let's say I have a class Apple</p><p>It use partial class on 3 files</p><p>Apple.visual.cs<br>Apple.io.cs<br>Apple.logic.cs<br>when press Ctrl+, to Go To Type, it will show 3 identical items in the list without mentioning the filename difference.<br>Expected result: show also the file name so user could choose which one to navigate to.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/396810/control-go-to-type-show-same-info-for-partial-clas.html
VSTS ticketId: 738795_
_These are the original issue comments:_

Jane Wu [MSFT] on 12/2/2018, 10:38 PM (2 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by CyrusNajmabadi** [comment]
@sharwell

> However, we'd like to ensure the filename added as a suffix to the first line of each item does not interfere with the filtering logic used by Navigate To All. Is this currently possible?

Filtering/bolding is handled on our end.  We actually implement things like the signature of a method as a just a 'suffix' we jam onto the end of an item.  i.e. 

![image](https://user-images.githubusercontent.com/4564579/49820841-d4c78000-fd2d-11e8-8f6c-c0b9b3fe1d48.png)

We could include the file-name as well.  However, in the past, it made things very noisy.  There was a bug and discussion opened many years back about adding an INavigateToItemDisplay interface that would give you a "string suffix" (or something like that).  The idea here would be that this could be filled and displayed by the UI in a cleaner way (i.e. right-aligned, maybe in gray).  This is similar to the "completion item suffix" discussion happening with @AmadeusW .  I don't know whatever came of that bug/discussion as i do not see any new NavTo interfaces that have this capability.

--

Note: the hardest thing on the impl level is simply that we search a file-based index, reporting results when we get them. At the time we get them, we don't really know if there will be another match that will make us want to disambiguate things.  So, if we were to have this, it would be good to make sure we can report an item with a particular set of data, but then have that data updated in the UI if we do a refresh.  It's unclear to me now if that's how NavTo works.  i.e. does the editor call into us and cache the data we return back?  Or do they always collect it again when we add a new item to the model.

**Comment by sharwell** [comment]
@CyrusNajmabadi The file name would only be included for partial types

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi The file name would only be included for partial types. It would be included for partial types whether or not the partial type is split into multiple files.

That could def work.  :)

**Comment by CyrusNajmabadi** [comment]
We now include the file name info to help disambiguate.  

![image](https://user-images.githubusercontent.com/4564579/152609272-cbc08dc6-3bcd-47f5-a0cb-a0d03eaa2f50.png)
