### ISSUE TITLE
Extend 'using' keyword functionality (C#)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31567]
<p>It will be great to have 'using' keyword in C# like in C++ - for declaring local type aliases in namespace, class/struct, method. Also with specifying access modifier, if defined in namespace or class/struct. </p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/381482/extend-using-keyword-functionality-c.html
VSTS ticketId: 728129_
_These are the original issue comments:_

Fiona Niu[MSFT] on 11/13/2018, 11:11 PM (21 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>
Kendra Havens [MSFT] on 11/20/2018, 02:01 PM (15 days ago): <p>Does the [using Statement]( https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement ) in C# satisfy this request?</p>

Vladyslav Prokopenko on 11/21/2018, 03:05 AM (14 days ago): <p><strong>UPD. </strong>Something went wrong with formatting, code is displayed as plain text (at least for me). Sorry for that.<br><br>Unfortunately, no. Anyway thanks for your suggestion.<br>I mean usage like the following examples:<br>Any of the following applicable for classes nice to have also for interfaces. (In case realization allows.)<br>1) Namespace aliases in namespace or class:</p><p>  Intent: allow avoid putting tons of using statements in the beginning of file, allow handy way for specifying exact class in case you have naming conflict (e.g. you have class CustomNS.StreamReader and use it in one file with System.IO.StreamReader).</p><pre>using SX = System.Xml; //per-file namespace alias
namespace SomeNS
\{
  private using SIO = System.IO; /*visible only in this namespace and nested entities*/
  public using ST = System.Threading; /*available for namespace users*/

  public class /*or interface*/ SomeClass
  \{
    public using TaskNS = System.Threading.Tasks; /*available for class users*/
    private using Generics = System.Collections.Generic; /*visible only for this class and nested entities*/
  }
}</pre><p>2) Type aliases. Now you can define type alias only per file. I propose the following:</p><p>   Intent: see 1), also you can hide actual type from your class user to achieve non-breaking change replacement of some used entities in case you keep the interface. </p><pre>namespace SomeNamespace
\{
  public using Reader = System.IO.StreamReader; /*available for namespace users*/
  private using StreamProvider = SomeCustomStreamWrapper; /*visible only for this namespace and nested entities*/

  public class /*or interface*/ SomeClass
  \{
    public using Collection = System.Collections.Generic.List; /*with possibility specify generic parametr later; not exact syntax, just an example of usage*/
    public using IntCollection = System.Collections.Generic.List&lt;int&gt;;
    /*or even can be like
      public using IntCollection = Collection&lt;int&gt;;*/
  }

  public class /*or interface*/ SomeGeneric&lt;T&gt;
  \{
    public using Param = T; 
    public using Collection&lt;T&gt; = System.Collections.Generic.List&lt;T&gt;;
  }
}
</pre><p>   in this example you can replace List with some other collection and user won't need to make changes in code.</p><p>3) Namespace member usings.</p><p>  Intent: e.g. you want to widely use some class' static method, that called SomeNS.NestedNS.AnotherOneNS.OneMoreNS.SomePublicClass.NestedPublicClass, in <em>just one </em>method. To avoid writing this every time or putting using directive in the beginning of file it will be great to have the following.</p><p>1) inspired by https://en.cppreference.com/w/cpp/language/namespace_alias </p><p>2) and 3) above inspired by 'using' keyword in C++ (https://en.cppreference.com/w/cpp/language/type_alias and https://en.cppreference.com/w/cpp/language/using_declaration)</p><p>Example code (due to broken markup)</p><p>1)</p><p><img src="https://developercommunity.visualstudio.com/storage/temp/49095-example1.png"></p><p>2)</p><p><img src="https://developercommunity.visualstudio.com/storage/temp/49096-example2.png" style="width: 789px;"></p><p>3)</p><p><img src="https://developercommunity.visualstudio.com/storage/temp/49097-example3.png"></p>

Dylan Cottell on 11/21/2018, 05:58 AM (14 days ago): <p>#1 is already a feature that exists on a per-file basis.</p><p>With your example provided in #3, you could easily call a public static method within a public static class after aliasing the namespace.</p><p>What doesn't exist is the ability to add an access modifier to a using statement, meaning that you couldn't set an alias globally for a namespace. I personally cannot think of any use cases for this functionality, and might do more harm than good.</p><p>Hope this helps.</p>

Vladyslav Prokopenko on 11/22/2018, 09:23 AM (13 days ago): <p>You are right about #1, but there was mentioned one more point - using in class.<br>Talking about #3, aliasing in this case is really handy just in that case, we can create alias inside a class (or even method).</p>

Dylan Cottell on 11/22/2018, 09:48 AM (13 days ago): <p>Ah, I understand now. #2 was a little confusing at first.</p><p>I like the idea of being able to set global aliases, or setting a using within a class. Although the use case isn't very clear to myself at this time, I could see some use for this. I'd argue that you'd be better instantiating the class rather than importing the namespace for use and simply use more of the namespace in your definition  to differentiate the two classes, but for some very specific scenarios or for the sake of saving time I could see some potential value.</p>

**Comment by CyrusNajmabadi** [comment]
This is a language request.  Closing out as those are now supposed to go through dotnet/csharplang.
