### ISSUE TITLE
After selecting event source, auto-select first existing event handler (if any)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31566]
<p>Within the code editor, after selecting an event source (such as a button on a form), it would be very helpful if the editor could automatically select the first (in alphabetical order), existing event handler.  I ask because it is a huge waste of time, and a big annoyance, that I need to select a specific event handler every time, even when there is only one, such as for a button's Click event. This was the way it worked in Visual Studio 2005, and even VB6. I'd love to have it back!</p><p>If you don't find it wise to do it for everyone, make it a user-selected (opt-in) option.</p><p>Thanks</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/379865/after-selecting-event-source-auto-select-first-exi.html
VSTS ticketId: 727340_
_These are the original issue comments:_

Fiona Niu[MSFT] on 11/12/2018, 01:47 AM (23 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>

**Comment by jasonmalinowski** [comment]
Also recently found an old bug lurking around that was a Connect report of this same issue.

**Comment by Neme12** [comment]
I don't understand this issue. What do you mean by "selecting" an event source?

**Comment by jasonmalinowski** [comment]
A control that has events; in this case in VB the nav bar experience is somewhat special in that certain controls will be listed in the navbar, and you can then pick an event to generate the handler for, similar to the VB6 experience if you happen to know that.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback here.
