### ISSUE TITLE
VS2019 thinks `int Main` is unused

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#31572]
**Version Used**: 

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 1.0

**Steps to Reproduce**:

1. Create a new .NET Core console project
2. Possibly unrelated, but set language version to 8.0 and enable NRT with `<NullableReferenceTypes>true</NullableReferenceTypes>` in the csproj.
3. Build the following code:

```csharp
using System;

namespace ConsoleApp1
{
    class Program
    {
        static int Main(string[] args)
        {
            if (args.Length == 0)
            {
                Console.WriteLine("Usage: ConsoleApp1 <text>");
                return -1;
            }

            foreach (var arg in args)
            {
                Console.WriteLine(arg);
            }
            return 0;
        }
    }
}
```

**Expected Behavior**:

No diagnostics

**Actual Behavior**:

IDE0051 Private member 'Program.Main' is unused.

**Comment by CyrusNajmabadi** [comment]
Tagging @mavasani
