### ISSUE TITLE
Proposal: Fix all occurrences in open documents

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#31586]
Title says it all.

**Comment by jasonmalinowski** [comment]
@JosefPihrt: just wanted to ask, what is your workflow where this would help? We have been designing a feature where we might allow you to say fix all occurrences _in files I've edited but haven't checked in/pushed_ per source control. We figure what people often want to do is do some work, and then clean up before the submit the changes, and wouldn't want to impact other files.

If you had _that_ feature, would you still want this? Our worry too was that it can be pretty easy to lose track of which files you have open; you might end up applying to files you didn't intended or won't apply to files you did intend.

It's fine of course to say no you really want this, but I wanted to make sure not requesting something without realizing we could give you something else instead.
