### ISSUE TITLE
VS 2017 Enterprise 15.0.28307.145 says it's incompatible with .NET Compiler Platform SDK

### ISSUE THREAD

**Issue by vScottLouvau** [dotnet/roslyn#31588]
I tried to follow the steps to implement a Code Fixer today, on a just-updated copy of VS 2017 Enterprise.

After I installed the .NET Compiler Platform SDK (either from https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.NETCompilerPlatformSDK or from Tools -> Extensions and Updates), VS reports that the SDK is incompatible with Visual Studio.

Is a release coming that will work?
![image](https://user-images.githubusercontent.com/15742033/49605889-a4a36a00-f946-11e8-8122-7b1ee2dea542.png)

**Comment by jmarolf** [comment]
You should not install it directly from the VS installer

![image](https://user-images.githubusercontent.com/9797472/49607452-d0c0ea00-f94a-11e8-9cf1-5d7b15e5992f.png)

**Comment by vScottLouvau** [comment]
Ah, great, installing it that way works fine. 

If the extension can be marked so that it's not for VS 2017 (since it's in the box now) or https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.NETCompilerPlatformSDK was updated to say you should install it via the Installer for VS2017, I would've figured it out on my own. =)
