### ISSUE TITLE
Prefer braces code fix does not support single-line blocks

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#31594]
**Version Used**: 
VS 15.9.3

**Steps to Reproduce**:

1. New C# console app
2. Add this code:
```
using System;

class Program
{
    static void Main(string[] args)
    {
        if (args.Length > 0) Console.WriteLine();
    }
}
```
3. Use this .editorconfig:
```
[*.cs] 
csharp_prefer_braces = true:silent 
csharp_preserve_single_line_statements = true 
csharp_preserve_single_line_blocks = true 
```
4. Format Document

**Expected Behavior**:
Should convert the line to:

```
        if (args.Length > 0) { Console.WriteLine(); }
```

Note that as a combination of the three rules above I'd expect the single-line block to remain on a single line, and the curlies to be added.

**Actual Behavior**:
```
        if (args.Length > 0)
        {
            Console.WriteLine();
        }
```

**Comment by sharwell** [comment]
This seems to be an oversight, but the configuration combination is quite rare. Marking up for grabs in the event someone who uses these settings is interested in implementing the feature. 😄

**Comment by KirillOsenkov** [comment]
@vScottLouvau

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
