### ISSUE TITLE
Samples and Walkthroughs->Getting Started->Semantic Analysis

### ISSUE THREAD

**Issue by daking2014** [dotnet/roslyn#3159]
On the Samples and Walkthroughs page, the Getting Started: Semantic Analysis walkthrough, says to create a C# Roslyn Console Application project by going File-> New-> Project -> Visual C# -> Roslyn -> Console Application. However, I don’t have a Rosyln option under Visual C#.

**Comment by Pilchie** [comment]
The templates have moved to the Extensibility node in the new project dialog.  That one is now called "Standalone Code Analysis Project".

Tag @AnthonyDGreen  and @jmarolf

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #35](https://github.com/dotnet/roslyn-sdk/issues/35) via [**ZenHub**](https://www.zenhub.com/)
