### ISSUE TITLE
`ConfiguredAsyncEnumerable` in netcoreapp3.0 preview is not acceptable with await foreach (CS8142)?

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#31609]
**Version Used**: The one in VS2019 Preview1 and dotnet sdk 3.0.100-preview-009812

**Steps to Reproduce**:

1. using System.Threading.Tasks;
2. await foreach (var z in /*IAsyncEnumerable<T>*/.ConfigureAwait(false))

**Expected Behavior**:
See this on https://github.com/dotnet/csharplang/blob/master/proposals/async-streams.md but seems not see this on #24037, is it still available?

**Actual Behavior**:
CS8412

**Comment by jaredpar** [comment]
@yyjdelete can you clarify what error you're getting here? It's unclear from the bug what the actual error is.

**Comment by yyjdelete** [comment]
### Expected Behavior:
Build successful with no errors.

### Actual Behavior:
Error	CS8412	Async foreach requires that the return type 'ConfiguredAsyncEnumerable<int>.Enumerator' of 'ConfiguredAsyncEnumerable<int>.GetAsyncEnumerator()' must have a suitable public 'MoveNextAsync' method and public 'Current' property

Nightly builds is not tested.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

</Project>

```
```cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }

        public async Task Test2()
        {
            await foreach(var x in Test())
            {
            }

            await foreach (var x in Test().ConfigureAwait(false))
            {
            }
        }

        public IAsyncEnumerable<int> Test() => null;
    }
}
```

**Comment by jcouv** [comment]
Fix merged for preview2.
Note there is a related issue which is not fixed yet. When you use `ConfigureAwait` in an `await foreach` loop, we'll don't call its `DisposeAsync()` method. Tracked by https://github.com/dotnet/roslyn/issues/32316
