### ISSUE TITLE
CS1717 'Assignment made to same variable' should offer 'this.' fix

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#31615]
VS 2019 Preview 1

```cs
class Foo
{
    private object bar;

    public Foo(object bar)
    {
        // CS1717 Assignment made to same variable; did you mean to assign something else?     
        bar = bar;
    }
}
```

This happens during refactoring enough that it would be nice to detect the field in scope with the unqualified name 'bar' and offer a fix to qualify the left-hand side. (Qualifying the right hand side would not be offered because it's a safe assumption that the parameter `bar` should have its value observed, and even if observed earlier, not overwritten.)

Something similar could be done for a field named `_bar`, if that's your cup of tea.

If the statement is in constructor and the field is readonly or the constructor is initializing a struct, that's another strong hint (CS0171 in the latter case) that this fix should be offered.

**Comment by CyrusNajmabadi** [comment]
@jnm2 Would you be interested in contributing a fix here?

**Comment by jnm2** [comment]
Happy to if no one else wants to work on it.

**Comment by NFPN** [comment]
Getting same error when using` variable = +variable`, but not when  `= -variable` wonder if anyone knows why

**Comment by CyrusNajmabadi** [comment]
> Getting same error when using variable = +variable, but not when = -variable wonder if anyone knows why

Can you provide some example code that demonstrates the problem?

**Comment by NFPN** [comment]
Cyrus, apparently it was a cache memory problem, after I restarted OS the warning never showed up again.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/42256
