### ISSUE TITLE
is operator confuses non-nullable references analyzer

### ISSUE THREAD

**Issue by dbolin** [dotnet/roslyn#31610]
Using the 'is' operator within an if statement appears to confuse the non-nullable references analyzer and variables it previously knew to be non-null are subsequently considered to be possibly null.

**Version Used**: .net core 2.2.200-preview-009648

**Steps to Reproduce**:

Compile the following code
```csharp
namespace Test_CS8600
{
    public class ClassBase
    {
    }

    public class ClassDerived : ClassBase
    {

    }

    public class Class1
    {
        public void Test(ClassBase a)
        {
            var x = a;

            if(a is ClassDerived d)
            {

            } else
            {
                x = a; // CS8600
            }
        }
    }
}
```

**Expected Behavior**:
Build outputs no warnings

**Actual Behavior**:
Build outputs `Class1.cs(23,21): warning CS8600: Converting null literal or possible null value to non-nullable type. `

**Comment by jcouv** [comment]
This was fixed in a 16.0 preview (not sure which). Verified on 16.0 preview 4.1.
This `is` test no longer affects both branches of the conditional.
