### ISSUE TITLE
CI feed for Roslyn

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#31612]
Is there a prerelease feed for the Microsoft.Net.Compilers NuGet package which could be mentioned at https://github.com/dotnet/roslyn/wiki/NuGet-packages?

What I'm looking for is a way to reference the Microsoft.Net.Compilers package which contains the same version of Roslyn as in VS2019 Preview 1.

**Comment by svick** [comment]
The about dialog of VS 2019 P1 says that its version of C# tools is 2.11.0-beta1-63519-03+4c7d79a254288388d97d793c4087db6ebf00d2fd. The roslyn MyGet feed contains [Microsoft.Net.Compilers version 2.11.0-beta1-63519-03](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.Net.Compilers/2.11.0-beta1-63519-03) and its description says:

>   This package was built from the source at `https://github.com/dotnet/roslyn/commit/4c7d79a254288388d97d793c4087db6ebf00d2fd`.

So I think that's the one you're looking for.

**Comment by jnm2** [comment]
Could https://dotnet.myget.org/gallery/roslyn and https://dotnet.myget.org/F/roslyn/api/v3/index.json be made easy to find, e.g. in https://github.com/dotnet/roslyn/wiki/NuGet-packages?

**Comment by jinujoseph** [comment]
cc @genlu

**Comment by genlu** [comment]
By the way, the preview 1 version of Roslyn packages were published to nuget.org yesterday.

**Comment by jnm2** [comment]
@genlu Perfect! Thank you!
