### ISSUE TITLE
‘Convert to foreach’ overzealously removes the foreach iteration variable

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#31621]
Visual Studio 2019 Preview 1

If you invoke ‘Convert to 'foreach'’ on:
```cs
foreach (var item in list)
{
}
```

You get:

```cs
for (var i = 0; i < list.Length; i++)
{
}
```

But now I have to write this myself (the actual expression is quite a bit longer than `list`):

```cs
    var item = list[i];
```

I'm not happy about this. Just because I haven't typed the statement yet that will use `item` does not mean `item` should be discarded. It just so happens that I want `i` in scope before I start typing the first statement that uses `item`.

**Comment by heejaechang** [comment]
@jinujoseph @kendrahavens are we good with this suggestion?

**Comment by CyrusNajmabadi** [comment]
i think the suggestion is appropriate.  almost all the time you'll end up wanting this variable.  so it seems better to have people remove the variable in the uncommon case, versus having to add it.

**Comment by CyrusNajmabadi** [comment]
Note: we could also special case this just to empty loops since hte presumption would be that the user wrote hte loop and was converting it.  A loop with contents would be thought to have enough 'signal' to determine if the variable was needed or not.

**Comment by jinujoseph** [comment]
Seems reasonable request to me.
