### ISSUE TITLE
Proposed "Nullability Side Car Representation"

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#31632]
We're considering supporting an additional input file to the C# compiler that would inform the compiler about nullability annotations that should be considered to apply to external program entities.  These annotations replace what the programmer considers to be either missing or incorrect annotations from an imported library.

## Nullability "Side Car" Representation

This document proposes a particular representation for the signature information that augments a program that may lack signature information in its program elements or referenced assemblies.  We call this the "C# nullability signature" file, or CSNS.  When one is present as part of a compilation, the signatures of program entities are augmented with nullability annotations appearing in it.

The CSNS file format is a subset of the C# programming language, and is intended to support only enough of the C# language to express the program element signatures and the nullability annotations that apply to them.  We borrow from C# so that we can assume C# syntax and semantics unless described otherwise.

Each CSNS file is self-contained. It is interpreted independently of the program or other CSNS files. Its interpretation is used to associate a fully-qualified name (without namespace qualification) to each type name appearing in it, and those are used to associate an annotated program element with a corresponding program entity (if any). It is not an error for there to be program elements in the CSNS file that do not correspond to any symbols in the program.

The CSNS file format is the same as a C# program except as follows:
- No modifiers are permitted (not even `public`, `private`, `override`, `new`, `params`, `this`, `partial`, parameter `ref`, `in`, or `out`, etc).
- *variance_annotations* (`in` and `out`) on type parameters are not permitted.
- Method bodies (and ctor-initializers) are forbidden. Each method declaration should end in a semicolon.
- Similarly, constructor, operator, property, and other function member bodies are omitted.
- Default parameter values are forbidden in method declarations.
- Attributes are permitted, but only without attribute arguments.
- tuple element names are forbidden in tuple types
- `dynamic` is forbidden.  `object` is used instead.
- Static constructors and constants may not be declared.
- Explicit interface implementations are forbidden.
- Enum declarations are forbidden.
- No preprocessing directives are permitted, except for #nullable
- No `extern alias` directives, but only in the compilation unit (not in a namespace)
- No `using` directives (except `using` alias directives)

To be clear, the following are permitted:
- comments, including documentation comments (which are ignored)
- `using` alias directives
- `namespace` declarations
- type declarations, including `class`, `struct`, `interface`, and `delegate` declarations.
- `enum` declarations (without a base type or members)
- field, property, method, operator, indexer, constructor, destructor, and event declarations, as well as member declarations of properties and events, but without bodies.
- type parameter constraints

Semantically, there are some differences from C#:
- Type names appearing in a CSNS file bind to a type declared by that name from the CSNS file. The fully-qualified name of the type that is found is used to match it to a type in the annotated program.
- It is an error for a type not to be found, with two exceptions. Language keywords such as `string`, `int` and `double` can be used to refer to fully-qualified names that are considered to always be found. A fully-qualified name written with a `global::` qualifier need not be found. In both cases the language construct naturally provides the fully-qualified name.
- A type declaration in CSNS is not considered to declare a type, so it does not have the same constraints as ordinary C#
  - The requirements that a concrete type implements its interfaces or its base type's abstract members does not apply to a type declared in CSNS
- Pointer types are permitted even without the `unsafe` modifier.

## Alternatives
- We could aim to make the file format suitable for generation of a reference assembly, but that would require that type names bind. We want to use a single CSNS for more than one platform, so we prefer looser semantics.
- We could permit modifiers (and variance annotations, default parameters, `object`, and tuple names) to make it easier to copy-and-paste into a CSNS file. In that case we need to decide what to do with them
  - [x] Forbid them (proposed above)
  - [ ] Ignore them
  - [ ] Require them to match the annotated entity; if they do not match
    - [ ] Produce a diagnostic; or
    - [ ] Consider the CSNS declaration not to annotate that entity

## Open Questions
- What kinds of changes can a CSNS annotated program element make to a program symbol
  1. It can only change an *oblivious* annotation to something else; or
  2. The annotations in a CSNS file fully override the annotations from the program
- Can annotations from one CSNS file "override" those from another?  How do we decide which one to use?  Is there a priority order?
- Do CSNS annotations apply to symbols that are declared in the program itself (that is, in source)? Or are annotations directly in source the only supported way to annotate a symbol in the C# programming language?

**Comment by CyrusNajmabadi** [comment]
Could you clarify this statement:
> We want to use a single CSNS for more than one platform, so we prefer looser semantics.

Also, how about .d.cs as the extension? :)

**Comment by Joe4evr** [comment]
> how about .d.cs as the extension? :)

What does this `d` stand for? :thinking:

**Comment by gafter** [comment]
> Could you clarify this statement:
> 
> > We want to use a single CSNS for more than one platform, so we prefer looser semantics.

Different platforms have different sets of APIs.  We would like it to be possible to produce a single CSNS file that applies to the union of these platform APIs, without it being an error that it contains declarations that don't match any API elements in some particular platform.

**Comment by CyrusNajmabadi** [comment]
Perfect.  Thanks for the clarification @gafter

**Comment by gafter** [comment]
I've updated the specification based on a design meeting on 2018-12-10.  If you want to see what changed, please use the github feature to have it show you the diff (from the pulldown menu under "edited")

**Comment by marek-safar** [comment]
Are generic constraints considered to be part of the signature in this context?

**Comment by marek-safar** [comment]
@gafter does it mean you cannot annotate constraints?

**Comment by gafter** [comment]
Right, I forgot about that.  You definitely need to annotate constraints.  So they are permitted but are not part of the signature for purposes of matching symbols.

**Comment by jcouv** [comment]
@gafter Should we close this issue/proposal?
