### ISSUE TITLE
Semantic classification doesn't always refresh

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#31638]
Version used: 16.0 preview 1

It just happened to me that after opening the Roslyn solution, I was waiting for all types to get colorized to be sure that everything is loaded, but it seemed to take a little longer than usual. When I tried hovering over an uncolored type, I actually got quick info, which means everything was fully bound after all. I just had to close and reopen the document to see the colorization.
Screenshot:
![image](https://user-images.githubusercontent.com/11444821/49687744-b718d180-fb07-11e8-8429-ae5d77fc5ec3.png)

**Comment by CyrusNajmabadi** [comment]
Have not been able to repro this.  This is probably one of those cases we've fixed where we weren't properly broadcasting workspace events.
