### ISSUE TITLE
[Nullable ref Types] Infer throw statements from extension methods

### ISSUE THREAD

**Issue by garuma** [dotnet/roslyn#31642]
**Version Used**: VisualStudio.16.int.d16.0stg/16.0.0-pre.2.0+28408.101.d16.0stg
C# Tools 2.11.0-beta2-63529-05+66aa49da81717aa54090a9e94c2f575ddb1959bb

**Steps to Reproduce**:

Simplified definition:

``` csharp
struct TwoEnumeratorListStack
{
    private readonly ArrayBuilder<Which>? _discriminatorStack;

    public Which PeekNext()
    {
        // Possible dereference of a null reference
        return _discriminatorStack[_discriminatorStack.Count - 1];
    }
}
```

To prevent the warning you can do:

``` csharp
public Which PeekNext()
{
    if (_discriminatorStack == null)
        throw new InvalidOperationException();
    return _discriminatorStack[_discriminatorStack.Count - 1];
}
```

Which removes the warning. However trying to capture the check in a general-purpose extension method:

``` csharp
internal static void ThrowInvalidIfNull<T>(this T? argument) where T : class
{
    if (argument == null)
        throw new InvalidOperationException();
}

public Which PeekNext()
{
    _discriminatorStack.ThrowInvalidIfNull();
    return _discriminatorStack[_discriminatorStack.Count - 1];
}
```
Doesn't remove the warning anymore and requires additional `!` to both array indexer and `.Count`

**Comment by jaredpar** [comment]
Thanks for reporting! This scenario, and others, are covered in the following issue. The intent is definitely to support this 

https://github.com/dotnet/roslyn/pull/32078

**Comment by jcouv** [comment]
The `[System.Runtime.CompilerServices.AssertsNotNull]` [attribute](https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-reference-types.md#null-tests) can be applied on the parameter of `ThrowInvalidIfNull` to help the compiler draw the correct inference.
You may have to define the attribute yourself for now, but we plan to add it to Core 3.
