### ISSUE TITLE
Suggestion: C# should offer a QuickAction to insert explicit cast, like the error message says

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3164]
Look at this screenshot. The C# compiler is smart enough to know that an explicit conversion exists, and suggests that maybe I'm missing a cast. So it should offer a QuickAction to do this (like VB does).
![why-no-quickfix](https://cloud.githubusercontent.com/assets/3316258/7873548/883acc0e-0558-11e5-8c4e-a0fc681f5fea.png)

Full source code for the repro:

``` cs
class Program
{
    static void Main()
    {
        var red = ColorF.FromArgb(255, 255, 0, 0);
        Color c = red;
    }
}

struct Color
{
    public byte A, R, G, B;
    public static Color FromArgb(byte a,byte r,byte g,byte b) => new Color { A = a, R = r, G = g, B = b };
}

struct ColorF
{
    public float A, R, G, B;
    public static ColorF FromArgb(double a, double r, double g, double b) => new ColorF { A = (float)a, R = (float)r, G = (float)g, B = (float)b };
    public static implicit operator ColorF(Color x) => ColorF.FromArgb(x.A / 255.0, x.R / 255.0, x.G / 255.0, x.B / 255.0);
    public static explicit operator Color(ColorF x) => Color.FromArgb((byte)(x.A * 255), (byte)(x.R * 255), (byte)(x.G * 255), (byte)(x.B * 255));
}
```

**Comment by Pilchie** [comment]
One problem with providing a fix for this error is that the C# compiler emits any time an explicit conversion *may* exist (e.g. converting an unsealed type to an interface), and a large majority of the time, inserting the cast will just cause a runtime error.

**Comment by Pilchie** [comment]
In order to fix this, we should first teach the compiler to report distinct errors between:

1. There is *definitely* a valid conversion.
2. There *may* be a conversion, if a derived type happened to implement the interface.

and only offer a fix for the first one.

**Comment by CyrusNajmabadi** [comment]
@y87feng Will your work fix this case?  If so, can you add a test for it in your PR?

**Comment by CyrusNajmabadi** [comment]
This is offered:

![image](https://user-images.githubusercontent.com/4564579/198705046-feb2e8f8-0125-4b38-b7b9-50b688a41606.png)


Closing out.
