### ISSUE TITLE
[Nullable ref Types] default(T) behavior in the context of generic types

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/roslyn#31643]
**Version Used**: VS2019 16.0 Pre1

**Steps to Reproduce**:

Given the following code:

```csharp
public static void TestMethod()
{
    new string[0].AllEquals();
    new int[0].AllEquals();
}

/// <summary>
/// Check if all items of an enumerable are equals, using an optional comparer
/// </summary>
public static bool AllEquals<T>(this IEnumerable<T> items, IEqualityComparer<T> comparer = null)
{
    comparer = comparer ?? EqualityComparer<T>.Default;

    T first = default(T);   // Error CS8625: Cannot convert null literal to non-nullable reference or unconstrained type parameter.
    bool isFirst = true;
    foreach (var item in items)
    {
        if (isFirst)
        {
            first = item;
            isFirst = false;
            continue;
        }
        if (!comparer.Equals(first, item))
        {
            return false;
        }
    }
    return true;
}
```

**Expected Behavior**:
Not sure what to expect here, I do not how to resolve this aside from disabling nullables... if it's unconstrained, should there be a way to tell that T can be nullable for references, and cannot be for value types? Should an explicit `where T:object?` change this behavior [if it were valid](https://github.com/dotnet/csharplang/blob/98043cdc889303d956d540d7ab3bc4f5044a9d3b/meetings/2018/LDM-2018-04-25.md#allow-object-explicitly) ?

**Actual Behavior**:
`Error CS8625: Cannot convert null literal to non-nullable reference or unconstrained type parameter.` on assignation from `default`.

**Comment by jeromelaban** [comment]
The "null forgiving" operator is what I was looking for. I'll give it a spin for other scenarios, thanks!

Should I close this issue, or is worth something more ?

**Comment by danielearwicker** [comment]
@CyrusNajmabadi you can, but then `first` is a non-nullable with the value `null`.

**Comment by jaredpar** [comment]
Thanks for reporting this. The behavior you identify here is "By Design". Because the type parameter `T` is unconstrained it is possible it can be substituted with a non-nullable value and hence this would be incorrect. Example is `AllEquals<string>` is a legal instantiation.
