### ISSUE TITLE
Unable to select TFM in editor

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#31650]
I'm using dev16 preview1 on Roslyn (`Compilers.sln`).

I expect that I can change the TFM and the source would become active/colorized. But instead the TFM reverts itself back to its original selection.

![select-tfm](https://user-images.githubusercontent.com/12466233/49702793-6b226700-fbb1-11e8-9e37-1c16c227ad46.gif)

@jinujoseph for triage/routing

**Comment by jinujoseph** [comment]
@jcouv , known issue https://github.com/dotnet/roslyn/issues/31365
