### ISSUE TITLE
when mixed /**/ and //, uncomment will uncomment // first.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31669]
Example:

```csharp
/*
    public class A
    {
     // this is a class
    }
*/
```

When I press ctrl K + ctrl U to uncomment the code block above, I get my code like this:

```csharp
/*
    public class A
    {
     this is a class   -> uncomment
    }
*/
```

but I expect my code to be this:

```csharp
public class A
    {
     // this is a class
    }
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/400570/when-mixed-and-uncomment-will-uncomment-first.html
VSTS ticketId: 740677_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
@sharwell   related to https://github.com/dotnet/roslyn/issues/29647  ?

**Comment by sharwell** [comment]
@jinujoseph No this is a separate issue

**Comment by StanislavUshakov** [comment]
Hello. I just want to clarify: isn't it a breaking change as current implementation first checks for single line comment, and only if there are none of them, uncomments block comments: [CommentUncommentSelectionCommandHandler.cs](https://github.com/dotnet/roslyn/blob/defeca5d0e44915fc978cfd93d3de2e4a6d0dbf4/src/EditorFeatures/Core/Implementation/CommentSelection/CommentUncommentSelectionCommandHandler.cs#L306-#L315)
In this case we will need to check and modify all the unit tests for this behaviour.

**Comment by dibarbet** [comment]
Resolved in https://github.com/dotnet/roslyn/pull/33188 for 16.1
