### ISSUE TITLE
use RunContinuationsAsynchronously on TaskCompletionSource

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#31667]
TaskCompletionSource.SetResult has the behavior where it runs its continuation inline under await machinary which can cause issue such as this (https://github.com/dotnet/roslyn/pull/31634)

.net now has new otpion RunContinuationsAsynchronously  (http://index/?leftProject=mscorlib&leftSymbol=mlddsr3iavyr&file=system%5Cthreading%5CTasks%5CTask.cs&line=6956)

we should audit our code base to use new option.

I see ones like AsyncQueue.cs doing Task.Run(() => ..SetResult()) to get around the issue.

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.
