### ISSUE TITLE
VS 2019 Preview 1 problem compiling Roslyn

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31668]
To play around with the new Github interface, I asked for Roslyn (https://github.com/dotnet/roslyn.git). It downloaded fine. But when I tried to compile it, it seemed to go too quickly (just a few seconds), and then stopped with &quot;Build failed&quot; down in the status line. It didn't display the Error List, but when I opened it from the View menu, it showed no errors, warnings, nothing.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/398897/vs-2019-preview-1-problem-compiling-roslyn.html
VSTS ticketId: 740002_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by agocke** [comment]
It works just fine for me, I follow the instructions on https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md

**Comment by CyrusNajmabadi** [comment]
Not repro.
