### ISSUE TITLE
nullable reference and linq syntax strips nullability

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31671]
<p>Given:<br></p><pre>var x = new List&lt;string?&gt;();</pre>This should produce a null dereference warning:<br><pre>var y = from a in x
        where a.Length != 0
        select a;</pre>But it doesn't. The nullability of `a` is stripped away immediately by `from ... in`.</p>
</pre>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/402964/nullable-reference-and-linq-syntax-strips-nullabil.html
VSTS ticketId: 744186_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jaredpar** [comment]
This is a dupe of #29863
