### ISSUE TITLE
Additional nullability tests for conversions with type parameters constrained to Nullable<T>

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#31675]
See:
https://github.com/dotnet/roslyn/pull/31499#issuecomment-445681971
https://github.com/dotnet/roslyn/pull/31499#discussion_r240321408

**Comment by VSadov** [comment]
With `Nullable<T>` being a struct, is it actually possible to use it as a constraint?

**Comment by VSadov** [comment]
After a discussion with @cston it looks like the bug is not actionable any more.
