### ISSUE TITLE
Missing compiler required member 'System.Collections.IEnumerator.MoveNext'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31672]
I'm using a custom mscorlib with some of my projects. This has been working fine until the latest update(s) of VS. As of sudden, I'm starting to get the message above (plus other two about get_Current and GetEnumerator) on every foreach loop.

Please note that the interface/methods are correctly implemented and as I noted, this was working fine before. It seems that for some reason, VS/Roslyn are not picking the methods.

While on the library I'm providing the methods are explicitly implemented, I already tried change them to implicit implementations but the problem still persists.

Any guidance on how to make this works again will be appreciated.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/382883/missing-compiler-required-member-systemcollections.html
VSTS ticketId: 729511_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by agocke** [comment]
It's possible this was brought about by a refactoring that more aggressively checks for special type members. However, special types are always supposed to exist and be properly written, so this should be fully compliant, as long as the checks are valid.

**Comment by CheloXL** [comment]
@agocke That was my first assumption when this stopped working, that's why I change the implementation from explicit to implicit, but as I already mentioned, it still doesn't works.

**Comment by agocke** [comment]
Can you post the source for your corlib?

**Comment by CheloXL** [comment]
Sure...
[Cores.zip](https://github.com/dotnet/roslyn/files/2665293/Cores.zip)

**Comment by agocke** [comment]
It looks like both of your IEnumerator interfaces are in the System.Collections.Generic namespace. You need to split the non-generic one into the System.Collections namespace.

**Comment by CheloXL** [comment]
No, they are not. They are in one file, but namespaces are correct
(System.Collections/ System.Collections.Generic).
___________________
Marcelo Volmaro

**Comment by agocke** [comment]
This is the full text of the file that you sent me:

```C#
using System.ComponentModel;
using EfxCompilerAttributes;


namespace System.Collections.Generic
{
	/// <summary>
	///     Supports a simple iteration over a generic collection.
	/// </summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Browsable(false)]
	public interface IEnumerator
	{
		/// <summary>
		///     No implementar. Sólo por infraestructura
		/// </summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		[Browsable(false)]
		object Current
		{
			get;
		}

		/// <summary>
		///     No implementar. Sólo por infraestructura
		/// </summary>
		/// <returns></returns>
		[EditorBrowsable(EditorBrowsableState.Never)]
		[Browsable(false)]
		[NonExistantMethod]
		bool MoveNext();

		/// <summary>
		///     No implementar. Sólo por infraestructura
		/// </summary>
		/// <returns></returns>
		[EditorBrowsable(EditorBrowsableState.Never)]
		[Browsable(false)]
		[NonExistantMethod]
		void Reset();
	}

	/// <inheritdoc />
	/// <typeparam name="T">The type of objects to enumerate.</typeparam>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Browsable(false)]
	public interface IEnumerator<out T> : IEnumerator
	{
		/// <summary>
		///     No implementar. Sólo por infraestructura
		/// </summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		[Browsable(false)]
		new T Current
		{
			get;
		}
	}
}
```

**Comment by CheloXL** [comment]
Ah... sorry... was checking IEnumerable (that's on the correct NS)... let
me change the NS to the correct one and will let you know if that fixes it.
___________________
Marcelo Volmaro

**Comment by agocke** [comment]
Great, glad it's working!
