### ISSUE TITLE
VB SematicModel doesn’t return Symbol information for a compound assignment

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#31678]
From @JoeRobich:
For my classification work, I am looking to classify compound assignment that use overloaded operators separately than those that use the built in. This was not an issue in C# because I was able to use the SemanticModel to get SymbolInfo for AssignmentExpressions. In VB.NET I am having a harder time because SematicModel doesn’t return information for AssignmentStatements. Is there an API where I can get the Symbol information for an AssignmentStatement in VB?

**Comment by 333fred** [comment]
This seems like it would be good information to add to `IOperation` as well.

**Comment by DustinCampbell** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/6366

**Comment by 333fred** [comment]
Closed as dupe.
