### ISSUE TITLE
open and reopen same solution doesn't create new solution in Roslyn

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#31686]
repro

1. create solution1
2. close the solution1
3. reopen the same solution1

when a solution is opened and closed and then reopen, Roslyn used to consider them as 2 different solutions. now we are considering them as the same solution

we should tweak code below to make roslyn to consider them as 2 different solutions.
https://github.com/dotnet/roslyn/blob/2d355454fe78c80e6a68a41b5fb33b037a7fc3fe/src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectFactory.cs#L73

I am not sure what user facing impact this would have. but features/component that tracks solution through solutionId and IVsSolution events will have state tracking messed up since IVsSolution will raise close solution events, but solution id stays same and we will never get SolutionRemoved events.

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski .  This may tie into the convo we were having about if there was a need for multiple-solutions and solution-states.

**Comment by jasonmalinowski** [comment]
Based on what @heejaechang were debugging yesterday, this was just a dumb mistake on my part. :smile:
