### ISSUE TITLE
Nested collection initializer doesn't capture the collection in a temp

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#31688]
**Version Used**: 7.3

**Steps to Reproduce**:

```cs
using System.Collections.Generic;
public class C {
    List<int> P {get;}
    public void M() {
        new C {P={1,2}};
    }
}
```

**Expected Behavior**:
```cs
C c = new C();
List<int> p = c.P;
p.Add(1);
p.Add(2);
```
**Actual Behavior**:
```cs
C c = new C();
c.P.Add(1);
c.P.Add(2);
```

This was surprising to me, because `P` is appeared once in the source, so I'd expect a single call to it.

**Comment by CyrusNajmabadi** [comment]
Spec says: 

> A member initializer that specifies an object initializer after the equals sign is a nested object initializer, i.e. an initialization of an embedded object. Instead of assigning a new value to the field or property, the assignments in the nested object initializer are treated as assignments to members of the field or property. Nested object initializers cannot be applied to properties with a value type, or to read-only fields with a value type.

This is unfortunately pretty vague.  However, the [spec](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#object-initializers) also happens to give some examples that shows that the behavior of the compiler is working as expected.  i.e.:

```c#
var c = new C {
    x = true,
    y = { a = "Hello" },
    z = { 1, 2, 3 },
...

// is equivalent to this series of assignments:

C __c = new C();
__c.x = true;
__c.y.a = "Hello";
__c.z.Add(1); 
__c.z.Add(2);
__c.z.Add(3);
...
```

So i'd say the compiler is working exactly as expected given that this is exactly how the spec says it should translate.

**Comment by alrz** [comment]
Thanks for the pointer.

I'm wonder what's the rationale behind this, since we already ruled out value types:

>Nested object initializers cannot be applied to properties with a value type

**Comment by CyrusNajmabadi** [comment]
Note: this is likely necessary for the case of initializing a mutable struct with fields.  If a temp was made, then nested assignments wouldn't actually update the actual struct in-situ.

**Comment by CyrusNajmabadi** [comment]
> Nested object initializers cannot be applied to properties with a value type

Because the property would return a copy, hence, any assignments/mutations would be effectively lost in nearly all cases.

**Comment by CyrusNajmabadi** [comment]
@alrz Imagine if we had:

```c#
struct ComplexNumber
{
    public double Real;
    public double Imaginary;
}

struct ComplexPoint
{
    public ComplexNumber X;
    public ComplexNumber Y;
}

static class Program
{
    static void Main()
    {
        var p = new ComplexPoint
        {
            X = { Real = 0, Imaginary = 0 },
            Y = { Real = Math.Sqrt(2), Imaginary = Math.Sqrt(2) }
        };
    }
}
```

The compiler translates this to:

```c#
private static void Main()
{
	ComplexPoint complexPoint = default(ComplexPoint);
	complexPoint.X.Real = 0.0;
	complexPoint.X.Imaginary = 0.0;
	complexPoint.Y.Real = Math.Sqrt(2.0);
	complexPoint.Y.Imaginary = Math.Sqrt(2.0);
}
```

This is exactly what we want here, and completely initializes the struct with no unnecessary copies.  If we instead had:

```c#
private static void Main()
{
	ComplexPoint complexPoint = default(ComplexPoint);
        var x = complexPoint.X;
	x.Real = 0.0;
	x.Imaginary = 0.0;
        var y = complexPoint.Y;
	y.Real = Math.Sqrt(2.0);
	y.Imaginary = Math.Sqrt(2.0);
}
```

This wouldn't even be correct.  We'd have to copy the values back with something like:

```
complexPoint.X = x;
complexPoint.Y = y;
```

And this presumes that the location is writable (which it might not be for a readonly-field or prop).  So, the simplest approach, which works in all cases, is to simply write things out like how the compiler does things.  The only 'bad' side is the potential for a slight amount of extra computation on properties to retrieve a value that will probably be the same value.  But trying to optimize that case out somehow likely has never been worth it.

**Comment by alrz** [comment]
Yeah, so this was only necessary for structs, but for consistent side-effects we still do this for reference types. Unfortunate.

**Comment by alrz** [comment]
You're using fields, but with properties this still produce the call for each value, in which case we get a copy anyways? So it looks like a special lowering for structs (struct+field) has been done for anything else!

**Comment by CyrusNajmabadi** [comment]
> but with properties this still produce the call for each value

With properties, this would not be allowed, as these are value types.

**Comment by gafter** [comment]
Since we appear to be acting as expected, moving to `csharplang` to reconsider how we want it to behave.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #2066](https://github.com/dotnet/csharplang/issues/2066) via [**ZenHub**](https://www.zenhub.com/)
