### ISSUE TITLE
support accurate snapshot for error list

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#31694]
currently, even if an errorlist is designed to be immutable, we currently violate that contract by giving them whatever data we have in our cache. since error list and we are updated in different cadency, it is possible to have a time where errorlist ask us old data but we give them newly updated data from cache.

it works this way since we didn't want to duplicate same data twice or holding onto all errors in memory. but error list team want us to follow the contract. so, it seems we don't have any other alternative but duplicating all errors. at least, we can put those data in temporary storage, and most of time, there is not that many errors.

**Comment by CyrusNajmabadi** [comment]
Closing out.  This is going away with LSP.
