### ISSUE TITLE
Newlines not enforced with editorconfig

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/roslyn#31709]
**Version Used**: 

VS2017 15.8.9

**Steps to Reproduce**:

1. Set the following in .editorconfig

```ini
csharp_new_line_before_open_brace = all
csharp_new_line_before_else = true
csharp_new_line_before_catch = true
csharp_new_line_before_finally = true
csharp_new_line_before_members_in_object_initializers = true
```

2. Add the following code

```csharp
try { if (true) { var values = new[] { 1, 2, 3 }; } else { throw new InvalidOperationException(); } } catch { } finally { }
```
 
3. Type Ctrl-K, Ctrl-D (or run Format Document)

**Expected Behavior**:

Line is formatted per the editorconfig rules, resulting in something like:

```csharp
try
{
    if (true)
    {
        var values = new[]
        { 1, 2, 3 };
    }
    else
    { throw new InvalidOperationException(); }
}
catch
{ }
finally
{ }
```

**Actual Behavior**:

Nothing happens. No formatting. No warnings. No errors.

Note: In case, I'm misunderstanding what should happen, I also tried just saving/reopening the document and building the project. But still nothing.

**Comment by CyrusNajmabadi** [comment]
This may be due to:

![image](https://user-images.githubusercontent.com/4564579/49852191-4805dc00-fd98-11e8-89bc-db02fd22de48.png)

What happens if you set these values to false:

```
csharp_preserve_single_line_statements=false
csharp_preserve_single_line_blocks=false
```

?

**Comment by MisinformedDNA** [comment]
So many options. :) Thanks!
