### ISSUE TITLE
Static class using Equals method in vs2019 preview occur crash

### ISSUE THREAD

**Issue by zhangvv** [dotnet/roslyn#31713]
**vs2019 preview 1.1**: 

**Steps to Reproduce**:

1. I have a FtpHelper static class.
2. FtpHelper.Equals(obj,obj)  can cause vs crash,as shwon in the figure.
 
![bug](https://user-images.githubusercontent.com/18322950/49873087-f6238b80-fe55-11e8-9b1d-17cf212318ea.png)

by the way:
 I install vs2017 and 2019 on my win7, and then the "report problems" will not work.Before i install vs2019,it can work on vs2017.

**Comment by CyrusNajmabadi** [comment]
I can't repro this with anything i've tried.  Will need more info from the user (like a full repro, or stack or dump) to be ale to proceed).

**Comment by zhangvv** [comment]
This problem doesn't exist in vs2019 16.5.0.
