### ISSUE TITLE
"using static" directive is not working for extension methods

### ISSUE THREAD

**Issue by VasiliyZhushma** [dotnet/roslyn#31715]
**Version Used**: 
Visual Studio Enterprise 2017 (15.9.2) / C# 7.0 - 7.3

**Steps to Reproduce**:
I have removed base class instance methods to a separate static class and made them extension methods:
```
public static class DataRowExtensions
{
	public static Result<T> GetValue<T>(this DataRow row, string columnName, T defaultValue = default)
	{
		var table = row.Table;
		return table.Columns.Contains(columnName)
				? Result.Ok(row.IsNull(columnName) ? defaultValue : row.Field<T>(columnName))
				: Result.Error<T>(new ArgumentException($"Class {table.TableName} does not contain attribute {columnName}!"));
	}
…
}
```
And since derived classes have many lines using that methods, I've decided to fix them by adding
```
using static CompanyName.Common.DataRowExtensions;
```
to the files with derived classes which use those methods.

**Expected Behavior**:
It is possible to use extension methods (which are effectively just static methods with ExtensionAttribute added) of DataRowExtensions class without specifying class name:
```
var myResult = GetValue<string>(dataRow, "SomeColumn", "default value");
```

**Actual Behavior**:
I get the compiler error CS0103: The name 'GetValue' does not exist in the current context.
If I make GetValue method not extension (remove ```this``` in first parameter), then it becomes usable without class name, as soon as "using static" directive imports it.

**Comment by jaredpar** [comment]
This behavior is "By Design". An extension method cannot be invoked without an explicit receiver. Hence you must add `this.` to invoke the extension method here.
