### ISSUE TITLE
Can't save .cs file after changing the Name property of a Button in Winforms property grid

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/roslyn#31735]
**Version Used**: 
Dev16 (d16.0stg branch), works fine in VS 2017
This is customer feedback from the preview channel - 
https://developercommunity.visualstudio.com/content/problem/400702/cant-save-cs-file-after-changing-the-name-attribut.html

**Steps to Reproduce**:
1 Create a Winforms application.
2 Drag and drop a Button control to Form1 designer.
3 Rename the Name property for this Button control.
4 Save the Form1.cs file.

**Expected Behavior**:
file is saved

**Actual Behavior**:
error box 
<img width="519" alt="image" src="https://user-images.githubusercontent.com/15823268/49908799-f9f0e700-fe30-11e8-8fd9-5f9d86029c17.png">

```
Microsoft.VisualStudio.LanguageServices.Implementation.dll!Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelService.LookupNode(Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.SyntaxNodeKey nodeKey, Microsoft.CodeAnalysis.SyntaxTree syntaxTree) Line 153	C#
  Microsoft.VisualStudio.LanguageServices.Implementation.dll!Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.AbstractKeyedCodeElement.LookupNode() Line 55	C#
  Microsoft.VisualStudio.LanguageServices.Implementation.dll!Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.AbstractCodeElement.GetName() Line 106	C#
  Microsoft.VisualStudio.LanguageServices.Implementation.dll!Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.AbstractKeyedCodeElement.GetName() Line 109	C#
  Microsoft.VisualStudio.LanguageServices.Implementation.dll!Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.AbstractCodeElement.Name.get() Line 117	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
  Microsoft.VisualStudio.Design.dll!Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomGenerator.GenerateCodeFromType(System.CodeDom.CodeTypeDeclaration e, System.IO.TextWriter w, System.CodeDom.Compiler.CodeGeneratorOptions o)	Unknown
```

**Comment by elGuille-MVP** [comment]
Last night happens to me using Visual Studio 2017 Professional v 15.9.4 and the workaround was changing the Designer (using Visual Basic)

**Comment by carlos-quintero** [comment]
The problem happens also (in VS 2019 Preview 1) just renaming the Form1 in the Properties window after the project and form is created, either with C# or VB.NET. No need to add a control or saving the file. See: [https://developercommunity.visualstudio.com/content/problem/412487/error-value-does-not-fall-within-the-expected-rang.html](https://developercommunity.visualstudio.com/content/problem/412487/error-value-does-not-fall-within-the-expected-rang.html)

**Comment by chrisjlocke** [comment]
Just reported this issue (didn't realise it was also reported) and have found editing the code in any way after getting this error seems to clear the error (using VS 2019 preview 1)

**Comment by chrisjlocke** [comment]
Yay, thanks @jasonmalinowski - this and the 'changes not allowed while code is running' bug are the only two issues making the preview very frustrating to use!

**Comment by jasonmalinowski** [comment]
@chrisjlocke Cool, just wanted to make sure we didn't have duplicate feedback floating around.
