### ISSUE TITLE
Consider making `!` sticky

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#31732]
After `!`, the variable should be considered non-nullable until the value is modified.

For instance, there should be no warning for the call to `x.ToString()`:
```c#
class Program
{
    static void F(bool b, object? x)
    {
        if (b)
        {
            G(x!);
            _ = x.ToString(); // no warning
        }
        _ = x.GetHashCode(); // warning: may be null
    }
}
```

Update:
`!` should also be stick on nullable value types:
```C#
void M(int? x)
{
   x!.Value.ToString();
   x.Value.ToString(); // ok
}
```

Should probably apply to things we can infer as non-null.
For example:
```C#
class C { int? field; }
void M(C? x)
{
  x?.field!.Tostring();
  x.ToString(); // ok, from what we learnt above
}
```

**Comment by jcouv** [comment]
I'm marking as language design issue. I don't recall a decision from LDM to make it sticky.

**Comment by jcouv** [comment]
@cston This is partly fixed (after PR https://github.com/dotnet/roslyn/pull/32078).

A scenario that remains is:
```C#
void M(string? x, string? y)
{
    _ = x!;
    x.ToString(); // will still warn
    M2(y);
    y.ToString(); // will still warn
}
void M2(string z) { ... }
```

I think that behavior is correct. `x!` doesn't mean `Debug.Assert(x != null)`, it just means that we suppress conversion warnings and return a non-null top-level nullability.
We only update the state of `x` if `x!` is used in a null-test (dereference, `... is null`, etc).

If this approach is satisfactory, we could close the issue.

**Comment by CyrusNajmabadi** [comment]
My preference would be that this behavior matches TypeScript.  Can we look into what the behavior means there?

**Comment by jcouv** [comment]
Here's what I found on Typescript: https://github.com/Microsoft/TypeScript/pull/7140

> A new ! postfix expression operator may be used to assert that its operand is non-null and non-undefined in contexts where the type checker is unable to conclude that fact. Specifically, the operation x! produces a value of the type of x with null and undefined excluded.

When I [tried it](https://www.typescriptlang.org/play/#src=class%20Greeter%20%7B%0D%0A%20%20%20%20greeting%3A%20string%3B%0D%0A%0D%0A%20%20%20%20constructor(message%3A%20string%3F)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.greeting%20%3D%20message!%3B%0D%0A%20%20%20%20%20%20%20%20this.greeting%20%3D%20message%3B%20%2F%2F%20error%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A), I found that it is not "sticky". `x!` does not assert that `x` is not null in a way that subsequent usages of `x` remember it. It only returns a non-null value.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by jcouv** [comment]
Closing this issue.
The current behavior is that `!` is a suppression, not an assertion.
But because of other inferences rules, if you use it dangerous (eg. a dereference), we will update the null-state.
