### ISSUE TITLE
'Convert anonymous type to tuple' not working.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#31746]
I cannot get the callback code AbstractConvertAnonymousTypeToTupleDiagnosticAnalyzer.AnalyzeSyntax to get called at all.

I've tried debugging why, but got utterly lost in the analyzer codepaths.  I would often be making progress only to hit code that would bail out due to state being set elsewhere.  but it wasn't clear what state was setting that.  After about an hour of rinse/repeat trying to just determine why this analyzer was not being called, i gave up.

@mavasani can you take a look and see why the callback is not getting hit?  The analyzer is simple.  It just does 'RegisterSyntaxAction' with SyntaxKind.AnonymousObjectCreationExpression.  And you shoudl be able to hit this trivially with an anonymous type as simple as `new { A = 1, B = 2 }`.  Thanks!

**Comment by mavasani** [comment]
@CyrusNajmabadi just to make sure, did you confirm the analyzer is running in-proc? At times I have ended up attaching to devenv.exe only to find out that the analyzer executed in service hub process. I can take a look later today...

**Comment by sharwell** [comment]
This was also hit by @jinujoseph and Kendra in testing.

**Comment by mavasani** [comment]
Also looking at the analyzer implementation, it seems it is declaring itself as a syntax-only analyzer with [DiagnosticAnalyzerCategory.SyntaxAnalysis](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/ConvertAnonymousTypeToTuple/AbstractConvertAnonymousTypeToTupleDiagnosticAnalyzer.cs,27), but that category is only meant for analyzers that register only actions which don't require a semantic model, currently only such action is a syntax tree action:

```
        /// <summary>
        /// Analyzer reports syntax diagnostics (i.e. registers a SyntaxTree action).
        /// </summary>
        SyntaxAnalysis = 0x0001,
```

**Comment by mavasani** [comment]
I believe either changing the analyzer to return DiagnosticAnalyzerCategory.SemanticSpanAnalysis OR changing it to register a syntax tree action that then gets all descendant nodes of the required type to report diagnostics will fix it.

I feel as a long term solution, we should get rid of `DiagnosticAnalyzerCategory` and the IDE diagnostic analyzer executor should look at the registered actions of an analyzer (by looking at the [AnalyzerTelemetryInfo](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerTelemetry.cs,10)) to automatically deduce this. This way even the third party analyzer execution is on par. This will also be needed to pull out one more IBuiltInAnalyzer hack for @sharwell's work.

**Comment by CyrusNajmabadi** [comment]
> but that category is only meant for analyzers that register only actions which don't require a semantic model

Oh interesting.  That was never stated.  The messaging around that option was that it was for anything registering syntax actions (i.e. syntax tree, or syntax nodes).

This also explains what i saw where at one point in the engine we bailed out on this analyzer as having no more 'work' to do.  And it looked like it was looking up something syntactic.

Looks like we'll need an audit on this sort of thing.

--

BTW, if this is how it works, then why do things work in tests?  That seems busted to me.  Thanks!

**Comment by sharwell** [comment]
> Looks like we'll need an audit on this sort of thing.

Easiest way is just get rid of `DiagnosticAnalyzerCategory` in a blanket ban.

**Comment by CyrusNajmabadi** [comment]
> Easiest way is just get rid of DiagnosticAnalyzerCategory in a blanket ban.

I would be fine with that.  :)

**Comment by mavasani** [comment]
> BTW, if this is how it works, then why do things work in tests? That seems busted to me. Thanks!

The IDE diagnostic service has a thin shim over the core diagnostic service that filters out built in analyzers for specific syntax/semantic/compilation diagnostic phases for live analysis. This is purely a perf optimization for IBuiltInAnalyzers executed in IDE. The test layer invokes directly into the core diagnostic service.

I agree with Sam, that we should get rid of it, but we also need to make sure that it does not regress perf for built in analyzer execution. If it does, we need to implement such filtering for all analyzers based on registered action counts.

**Comment by CyrusNajmabadi** [comment]
> The test layer invokes directly into the core diagnostic service.

This seems unfortunate, and it's something we usually try to avoid.  In general, a lot of tests invoke the *highest* point in ROslyn they can (or, when sensible, they even invoke from the editor layer).  This way they're both testing as much of hte roslyn scenario as possible, and they're ensuring that the tests reveal things that would be hit in the real VS.

**Comment by mavasani** [comment]
Tagging @heejaechang

**Comment by CyrusNajmabadi** [comment]
> I suggest we do following things as part of this specific bug fix:

That seems sensible.  I would also add:

4. have IDE tests exercise a higher layer of the analysis stack as well.

**Comment by CyrusNajmabadi** [comment]
I'm happy to do '1' and '2'.
