### ISSUE TITLE
CS8620 warning on range indexers of strings

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#31748]
**Version Used**: 

Visual Studio 2019 Preview Version 16.0.0 Preview 1.1

**Steps to Reproduce**:

```cs
class Program
{
    static void Main()
    {
#nullable enable
        string s = "2134567890";
        string sub = s[1..3]; // CS8620
    }
}
```

**Expected Behavior**:

No waning.

**Actual Behavior**:

Warning	CS8620
Nullability of reference types in argument of type 'Range' doesn't match target type 'int' for parameter 'index' in 'char string.this[int index]'.
ConsoleApp1	C:\source\repos\ConsoleApp1\Program.cs	7	24

**Comment by jcouv** [comment]
Thanks for reporting this. Confirmed.

@agocke Is there still some temporary logic in the compiler regarding indexers? 
Note that the diagnostic complains about `char string.this[int index]`, but I expect that a range-based indexer is used.

```C#
        [Fact, WorkItem(31748, "https://github.com/dotnet/roslyn/issues/31748")]
        public void RangeAndNullability()
        {
            var comp = CreateCompilationWithIndexAndRange(@"
#nullable enable
class C
{
    public static void M()
    {
        string s = ""2134567890"";
        string sub = s[1..3];
    }
}");
            comp.VerifyDiagnostics(
                // (8,24): warning CS8620: Nullability of reference types in argument of type 'Range' doesn't match target type 'int' for parameter 'index' in 'char string.this[int index]'.
                //         string sub = s[1..3];
                Diagnostic(ErrorCode.WRN_NullabilityMismatchInArgument, "1..3").WithArguments("System.Range", "int", "index", "char string.this[int index]").WithLocation(8, 24)
                );
        }
```
