### ISSUE TITLE
Nullable and attributes with array args don't work

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#31740]
**Version Used**: 
2.11.0-beta2-63529-05

**Steps to Reproduce**:

1. Open the following project in the IDE, observe two errors.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <NullableReferenceTypes>true</NullableReferenceTypes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Compilers" Version="2.11.0-beta2-63529-05" PrivateAssets="All" /> 
    <PackageReference Include="microsoft.visualstudio.shell.15.0" Version="16.0.28316-pre" />
    <PackageReference Include="xunit" Version="2.4.1" />
  </ItemGroup>

</Project>
```

```c#
using System;
using Microsoft.VisualStudio.Shell;
using Xunit;

[ProvideUIContextRule(ActivationContextGuid,
    "Load Managed Project Package",
"dotnetcore",
new string[] { "dotnetcore" },
new string[] { "SolutionHasProjectCapability:.NET & CPS" }
)]
public class Program
{
    public const string ActivationContextGuid = "";

    [Theory]
    [InlineData(new object[] { new string[] { "Hi" } })]
    public void Main(string[] args)
    {
        Assert.NotEmpty(args);
    }
}
```

**Expected Behavior**:
Compiles fine

**Actual Behavior**:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0182	An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type	ConsoleApp4	C:\Users\kevinpi\source\repos\ConsoleApp4\ConsoleApp4\Program.cs	5	Active
Error	xUnit1010	The value is not convertible to the method parameter 'args' of type 'string[]'.	ConsoleApp4	C:\Users\kevinpi\source\repos\ConsoleApp4\ConsoleApp4\Program.cs	16	Active

**Comment by Pilchie** [comment]
Tagging @jaredpar @cston @jcouv.

Found trying to enable Nullable on https://github.com/dotnet/project-system

**Comment by Pilchie** [comment]
Also, note that the xunit analyzer error is only reported with `<NullableReferenceTypes>` set to true.

**Comment by jcouv** [comment]
I was pointing at the nested arrays (not the simple array in `ProvideUIContextRule`).
That said, nested arrays like `new object[] { new string[] { "Hi" } })` [seem ok](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGA3AWACgBiAOwFcAbSiYSuDOU2+oogbQEEYYEBLYOXgBVKBADmcABTdeAoXAAqEBJJhQAdAFk4MABYB7ACYBKALpEUAZiwAmDFoCes/oPgYQGF/PhEA3kQYQRjsTlKkcADuGAbAAFZwAMYw7GYYfhgR0ThoqekYAEQAEnwFGAC+FeaBwdZYACwOUib55TVBdU7ebtKxCckYAB4tGW2E5UA) (they are single-dimensional).

**Comment by Pilchie** [comment]
The nested array example also comes from shipping code in project-system tests that work until nullable is enabled.

—
Kevin Pilch
https://twitter.com/Pilchie

________________________________

**Comment by jcouv** [comment]
I'm able to repro the compiler error (`1>test.cs(5,2,5,182): error CS0182: An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type`), but I'm not seeing the XUnit error.

**Comment by Pilchie** [comment]
I only see it in VS for some reason?
