### ISSUE TITLE
When implemention of ProvideCompletionsAsync fails error handling is missing

### ISSUE THREAD

**Issue by pgroene** [dotnet/roslyn#31753]
**Version Used**: 
  .ver 2:6:1:0
**Steps to Reproduce**:

1. Implement an CommonCompletionProvider 
2. Throw an exception in ProvideCompletionsAsync
3. Process is ended with Fail Fast

**Expected Behavior**:
Some error handing. In this case we have an AssemblyLoadException even before the method it self is hit. This means we can not catch this exception our selfs. A behavior can be removing the provide from the list on certain exception and swallow other exception with logging. 
**Actual Behavior**:

A fail fast exception which stops the host process

**Comment by CyrusNajmabadi** [comment]
Haven't gotten any more info indicating this is an issue.  closing out.
