### ISSUE TITLE
Generated equality operators should use parameter names 'left' and 'right'

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#31750]
Visual Studio 2019 Preview 1.1

https://docs.microsoft.com/dotnet/standard/design-guidelines/naming-parameters#naming-operator-overload-parameters says:

> ### Naming Operator Overload Parameters  
>  **✓ DO** use `left` and `right` for binary operator overload parameter names if there is no meaning to the parameters.  
>   
>  **✓ DO** use `value` for unary operator overload parameter names if there is no meaning to the parameters.  
>   
>  **✓ CONSIDER** meaningful names for operator overload parameters if doing so adds significant value.  
>   
>  **X DO NOT** use abbreviations or numeric indices for operator overload parameter names.  

However, Roslyn violates the first and last points:

```cs
class Foo
{
    private int value;

    public static bool operator ==(Foo foo1, Foo foo2)
    {
        return EqualityComparer<Foo>.Default.Equals(foo1, foo2);
    }

    public static bool operator !=(Foo foo1, Foo foo2)
    {
        return !(foo1 == foo2);
    }
}
```

**Comment by CyrusNajmabadi** [comment]
It will be :D

**Comment by jnm2** [comment]
Are there other operators Roslyn can ever generate at this point?

**Comment by CyrusNajmabadi** [comment]
Yes.  We do generate conversion operators (it's under the 'generate method' bucket of features).  However, the naming there is likely fine (though i haven't verified).

**Comment by sharwell** [comment]
Design meeting confirmed this as a desired change
