### ISSUE TITLE
IDE Analyzer tests should run over the full IDE analysis stack.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#31757]
Related to https://github.com/dotnet/roslyn/issues/31746

A analyzer feature wasn't working, but was passing all tests.  From the discussion: 

> The IDE diagnostic service has a thin shim over the core diagnostic service that filters out built in analyzers for specific syntax/semantic/compilation diagnostic phases for live analysis. This is purely a perf optimization for IBuiltInAnalyzers executed in IDE. The test layer invokes directly into the core diagnostic service.

The problem is that that the interaction with the analyzer and that shim layer is where the bug existed.  By not testing the shim layer, the entire feature ended up not working.

Our analyzer tests should go through as much of the IDE analysis layer as is reasonable.

**Comment by CyrusNajmabadi** [comment]
Tagging @mavasani @heejaechang

**Comment by mavasani** [comment]
Currently, the test framework invokes into `GetDiagnosticsXXX` entry points in IDiagnosticAnalyzerService, see here: http://source.roslyn.io/#Roslyn.Services.Test.Utilities/Diagnostics/TestDiagnosticAnalyzerDriver.cs,47

I think the tests would need to invoke into the `AnalyzeXXX` incremental analysis entry points over here: http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/SolutionCrawler/IIncrementalAnalyzer.cs,21, but @heejaechang can confirm if that suffices.

**Comment by CyrusNajmabadi** [comment]
Note: we've had similar problems in teh past all over roslyn.  For example, there are a large swath of completion tests that operate at a very low level, but then pretend that htey are doing all the work of the completion-orchestration layer itself (i.e. they figure out how to commit and attempt to figure out how to make the change to the document).  These tests led to tons of bugs happening where we weren't really validating anything true about the user scenario.  in response to taht, we introduced a new completion testin framework that operates above all the IDE completion code.  That way we truly get testing of everything involved in completion.  It also let us do things like validate the behavior of completion with other related features (like sig help + brace matching).  

I'm much more a fan of testing features at the highest reasonable roslyn layer we can.  We get the best coverage, and we get validation that is much closer to the real product.

**Comment by CyrusNajmabadi** [comment]
Closing out.
