### ISSUE TITLE
File.Exists check for named pipe causes EndOfStreamException in compiler server

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#3177]
In BuildClient.cs, we use File.Exists to check for the existence of a named pipe.
See: https://github.com/dotnet/roslyn/blob/34241b100258f437794450fd57b0fdad8a12e5fe/src/Compilers/Core/MSBuildTask/BuildClient.cs#L326

It turns out that this causes an EndOfStreamException to be raised in the server because zero bytes are read from the pipe.

As we've discussed offline, we should be able to try and connect without using File.Exists.

**Comment by agocke** [comment]
Fixed by #5466
