### ISSUE TITLE
Mistyping in the wiki

### ISSUE THREAD

**Issue by monoman** [dotnet/roslyn#3178]
@jaredpar 

There is a subtitle as "Compiler Pipeline Functonal Areas", which makes the correct link "Compiler Pipeline Functional Areas" in the TOC not work.

In the Roslyn Overview page: https://github.com/dotnet/roslyn/wiki/Roslyn-Overview#compiler-pipeline-functonal-areas

**Comment by gafter** [comment]
Fixed.
