### ISSUE TITLE
Proposal: Replace string.Format with concatenation when the string uses only nameof

### ISSUE THREAD

**Issue by IanKemp** [dotnet/roslyn#31790]
#11259 and #22344 proposed additional rules under which `string.Format` (and implictly string interpolation) can be optimised away. Due to the [not superficially obvious issues with calling `ToString()`](https://github.com/dotnet/roslyn/pull/6738#issuecomment-156257037), these proposals have effectively languished.

This proposal (identical to the closed #17356) covers only the most simple of the cases discussed above: when a string being formatted **contains only constant strings and `nameof` expressions**. In that case, **and only that case**, it is completely safe to strip out the format call and replace it with with simple concatenation.

Example:

```csharp
class Foo
{
    const string Bar = $"My method is named { nameof(Main) }";

    void Main()
    {
    }
}
```

Here, `Bar` can be rewritten to:

```csharp
const string Bar = "My method is named " + nameof(Main);
```

which is compiled to:

```csharp
const string Bar = "My method is named Main";
```

This is currently prohibited by the compiler since this optimisation is not performed.

**Comment by gafter** [comment]
As discussed in https://github.com/dotnet/roslyn/issues/11259

**Comment by gafter** [comment]
This proposal is not for an "optimization".  Changing something from not being constant to being a constant is a change in the semantics of the language.  That would require LDM review.

**Comment by gafter** [comment]
Moved to https://github.com/dotnet/csharplang/issues/2077
