### ISSUE TITLE
Support regex syntax highlighting in static Regex methods like Regex.Match()

### ISSUE THREAD

**Issue by Otiel** [dotnet/roslyn#31791]
It has been announced on 2018-12-13 on the [_Visual Studio 2019 Preview .NET Productivity_ blog post](https://blogs.msdn.microsoft.com/dotnet/2018/12/13/visual-studio-2019-net-productivity/):
>Any regular expressions in your C# or Visual Basic files now have syntax highlighting, compiler diagnostics, and code fixes! This parsing support can recognize strings passed to the regex constructor and strings immediately preceded with a comment containing the string `language=regex`. The language features currently included in this release are classification, brace matching, highlight references, and compiler diagnostics.

Following up a comment by _MgSm88_ on this blog post:
>Does the Regex syntax support include the static Regex methods, like `Regex.Match()`? `new Regex()` is a borderline anti-pattern given that regexes will not be cached using them that way.

This issue is to track the implementation of regex syntax highlighting, compiler diagnostics and code fixes on static Regex methods like `Regex.Match()`.

**Comment by CyrusNajmabadi** [comment]
> Does the Regex syntax support include the static Regex methods, like Regex.Match(

Yes.  It does work:

![image](https://user-images.githubusercontent.com/4564579/50029600-1b281380-ffa8-11e8-9779-bde3154a33ed.png)

**Comment by nillkitty** [comment]
How can we add this to an input parameter to a function using an attribute?   Are you saying this is a feature only Microsoft's own Regex class enjoys (aside from the user putting an explicit comment before every use of a regex from an alternate library?)?

**Comment by MoazAlkharfan** [comment]
> How can we add this to an input parameter to a function using an attribute? Are you saying this is a feature only Microsoft's own Regex class enjoys (aside from the user putting an explicit comment before every use of a regex from an alternate library?)?

They just chose a hacky way to add highlighting for regex into the IDE, seems like actual support was never the goal here.

**Comment by CyrusNajmabadi** [comment]
> seems like actual support was never the goal here.

What do you mean by 'actual support'?

**Comment by tigrouind** [comment]
> The only rule is: it has to be a static method on Regex, and the parameter name needs to be "pattern".

It seems the class need to be in `System.Text.RegularExpressions` namespace too.

**Comment by CyrusNajmabadi** [comment]
Yes, that's the type that 'Regex' is referring to.
