### ISSUE TITLE
Implement interface explicitly through

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#31818]
It's a missing 4th option here as a combination of "implement interface through" and "implement interface explicitly":

![image](https://user-images.githubusercontent.com/11444821/50044419-62370700-0083-11e9-89a8-b3578ad95af2.png)

**Comment by sharwell** [comment]
Design review conclusion: this seems like a reasonable behavior in light of the current options. We would accept a pull request implementing this.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
