### ISSUE TITLE
"Convert to interpolated string" should be an analyzer, not just a refactoring

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#31828]
The current refactoring to "Convert to interpolated string" is very useful, but without a "fix all" can't be used to modernize an entire code base. Since it falls into the category of suggestions to use newer language features, I believe it should be a code style. Most other language features have their own code style with an analyzer and can be used on a large scale (like out var, pattern matching, expression bodies, deconstruction....). This one just seems like it's missing.

**Comment by CyrusNajmabadi** [comment]
@Neme12 This is something that would likely be faster to just fix by opening a PR.  Would you be willing to do that?

**Comment by Neme12** [comment]
I forgot that there are actually multiple "convert to interpolated string" refactorings. One converts from `string.Format` and the other one converts from concatenation. My suggestion was to only add an analyzer for `string.Format` because that is a clear improvement.

**Comment by CyrusNajmabadi** [comment]
@Neme12 did you just want to make a pr here?
