### ISSUE TITLE
"Delegate invocation can be simplified" is not offered when calling .Invoke

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#31827]
In this example "Delegate invocation can be simplified" is offered as expected:
```c#
using System;

class C
{
    void M()
    {
        if (Event != null)
            Event(this, EventArgs.Empty);
    }

    event EventHandler Event;
}
```
but here it is not:
```c#
using System;

class C
{
    void M()
    {
        if (Event != null)
            Event.Invoke(this, EventArgs.Empty);
    }

    event EventHandler Event;
}
```

**Comment by CyrusNajmabadi** [comment]
When does the latter happen?  From talking to many devs, we've found that people aren't even aware that this is something to be done.  They just invoke a delegate with invocation-syntax.
