### ISSUE TITLE
CFG in presence of condition directives (#if ... #endif)

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#31820]
```
class C
{
    int M()
    {
        int x = 0;
        int y = 0;
#if DEBUG
        y = x;
#endif
        return y;
    }
}
```

If you request a `ControlFlowGraph` for the above method, such that `DEBUG` is not a defined conditional directive, then the returned CFG has no basic block for the entire `#if ... #endif` block. This is technically correct as that code is disabled based on the current preprocessor defines. However, this leads to incorrect flow analysis. For example, the new IDE analyzer that flags dead assignments, will flag `int x = 0` as a dead assignment in release mode as it does not see a basic block where this value is read, i.e. `y = x`.

I think we should handle this case specially for CFG where we _always_ generate a control flow region for code within conditional directive and there is a conditional branch at the beginning of this region, which goes into this region and a fall through branch that goes to the end of the region - essentially, treat this similar to a regular if statement, where the branch value is a conditional preprocessor symbol define check.

Tagging @AlekseyTs @333fred @gafter @heejaechang @jinujoseph @dotnet/analyzer-ioperation for thoughts.

**Comment by CyrusNajmabadi** [comment]
> I think we should handle this case specially for CFG where we always generate a control flow region for code within conditional directive and there is a conditional branch at the beginning of this region, which goes into this region and a fall through branch that goes to the end of the region - essentially, treat this similar to a regular if statement, where the branch value is a conditional preprocessor symbol define check.

But what would you do inside the region?  Note that ths can be arbitrary code.  There is nothing that ensures that:
1. it is well formed.
2. it won't have an effect on *parsing* the code outside the region.  

For '2', for example, you might have:

```c#
#if DEBUG
if (whatever) {
#endif
// more code
#if DEBUG
}
#endif
```

How would that work in practice?

**Comment by CyrusNajmabadi** [comment]
> If you request a ControlFlowGraph for the above method, such that DEBUG is not a defined conditional directive, then the returned CFG has no basic block for the entire #if ... #endif block. This is technically correct as that code is disabled based on the current preprocessor defines. However, this leads to incorrect flow analysis. 

Note: this has arisen in the IDE many times (since we started having advanced features back in 2003-2005).  The advice always given to users was: write your code such that it is sensible in each expected pp definition config.  So, the above would be written as:

```c#
class C
{
    int M()
    {
#if DEBUG
        int x = 0;
#endif
        int y = 0;
#if DEBUG
        y = x;
#endif
        return y;
    }
}
```

This has been done because no realistic design has even been proposed that can handle what *parsing* even means in a world where we understand the bodies of inactive pp-regions.  And without a reasonable parsing solution, there's no understanding of how we could layer anything more complex on top.

**Comment by CyrusNajmabadi** [comment]
Note: if i'm misreading, and you are instead suggesting a 'weaker' form of  textual analysis.  Then that may be ok.  i.e. if you're going to look inside the inactive code and basically just textually look to see if something seems fishy, then maybe htat's ok.  However, you may end up with undesirable false positives.  i.e. if they have something like:

```c#
#if false
            // Now combine all the comparison expressions together into one final statement like:
            
                  return myType != null &&
                         base.Equals(obj) &&
                         this.S1 == myType.S1;
#endif
```

IDE, for example, has inactive reasons for this sort of documentation purposes.  It's not intended to ever be thought of as real code that needs to ever be analyzed.

**Comment by 333fred** [comment]
I am agreeing with Cyrus here. For things like dead variable analysis, if the variables are only written in debug code, they should be conditionally defined. 

From an implementation standpoint, I'm not sure how we'd do this. As mentioned, this can change how code is parsed and bound, and would be an extremely expensive operation to do.

**Comment by mavasani** [comment]
Also tagging @dotpaul who is currently working on writing bunch of flow based security analyzers based on our CFG APIs. I am actually not that worried about dead variable analysis here, but things like flow based security analysis are a bigger concern, as even they will be affected here. For example, a lot of security analyzers validate that certain operations, such as say a property set, are done on all control flow paths prior to an invocation of a method where that instance is passed as an argument. Presence of conditional directives around such a prior operation might mean that user has to build his code in all possible project configurations to ensure that all security vulnerabilities are identified locally. Probably this is a reasonable experience (given the same is true even for real build errors), but if we had analyzed the code as having a conditionally executed code region, then the analyzer would flag in both debug and release modes, possibly leading to a better IDE experience.

Note, I am fine if we think this is not possible given the way our parsing works, and given the performance concerns. As long as we have made a conscious decision, and can point all flow analysis clients to this issue.

**Comment by CyrusNajmabadi** [comment]
> For example, a lot of security analyzers validate that certain operations, such as say a property set, are done on all control flow paths prior to an invocation of a method where that instance is passed as an argument

It's worth noting that every potential compilation which produces different results really should be analyzed under all configs.  For example, something may not have a security bug in debug, but might have it in release (or vice-versa).  Or it may only have the issue on mono+64bit+release :)   

People often like to think about it as one piece of code.  But each separate compilation is turly truly different with potentially vastly different meaning (and security implications) depending on the config.  So, at least for detecting security issues, people should be analyzing all builds.

**Comment by CyrusNajmabadi** [comment]
> and can point all flow analysis clients to this issue.

I think that might be best.  Or, better, woudl be pointing to a doc/page on how to fix up your code appropriately.  This particular issue may be too much 'in the weeds' as it were.  Whereas as dedicated doc could focus on the problem and the recommended ways to solve it.

**Comment by AlekseyTs** [comment]
To expand on @gafter 's  comment, the code disabled by conditional compilation isn't parsed and is not bound, might contain all sorts of errors, etc. For the compiler, it simply doesn't exist.

**Comment by mavasani** [comment]
Closing this issue, as the right solution here seems to be to make all the flow analysis authors aware about this scenario, and handle it appropriately on a case by case basis. As an end user, one would need to run the analysis on all configurations to identify all possible diagnostics, similar to compiler diagnostics in conditionally excluded code.
