### ISSUE TITLE
"Convert to interpolated string" should be offered on Console.WriteLine

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#31829]
The "Convert to interpolated string" refactoring is offered here:
```c#
using System;

class C
{
    void M()
    {
        Console.WriteLine(string.Format("Hello {0}!", "World"));
    }
}
```
but not here:
```c#
using System;

class C
{
    void M()
    {
        Console.WriteLine("Hello {0}!", "World");
    }
}
```
I think it should be available in the second case as well by either having knowledge of some special methods on `Console` or possibly recognizing this pattern of a string argument named `format` followed by `params object[] arg`.

**Comment by Neme12** [comment]
Other instances of this pattern are `TextWriter.Write/WriteLine` and `Debug.WriteLine`.

**Comment by CyrusNajmabadi** [comment]
@Neme12 would you like to just submit a pr for these?
