### ISSUE TITLE
"Delegate invocation can be simplified" refactoring should have a different title from the analyzer

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#31826]
Repro:
```c#
using System;

class C
{
    void M()
    {
        if (Event != null)
            Event(this, EventArgs.Empty);
    }

    event EventHandler Event;
}
```

![image](https://user-images.githubusercontent.com/11444821/50053972-252f4b00-013d-11e9-9243-76c95d377f5e.png)

The refactoring offered says "Delegate invocation can be simplified". While that is an appropriate name for an analyzer, it's not a good name for a refactoring. A refactoring should suggest an "action" as opposed to saying "there is a problem here". IMO a more appropriate name would be either:
- Simplify delegate invocation
or
- Use conditional delegate call (like the option in Tools->Options says)
![image](https://user-images.githubusercontent.com/11444821/50053977-2fe9e000-013d-11e9-947b-68ece824cdea.png)

**Comment by CyrusNajmabadi** [comment]
@Neme12 This is something that would likely be faster to just fix by opening a PR.  Would you be willing to do that?

**Comment by sharwell** [comment]
Agree the code fix could be changed to just:

> Simplify delegate invocation
