### ISSUE TITLE
"Use pattern matching" isn't available in some trivial cases

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#31835]
"Use pattern matching" shows up here:
```c#
class C
{
    int P { get; set; }

    void M(object o)
    {
        if (o is C)
        {
            var c = (C)o;
            c.P = 1;
        }
    }
}
```
but not here (if the variable is inlined):
```c#
class C
{
    int P { get; set; }

    void M(object o)
    {
        if (o is C)
        {
            ((C)o).P = 1;
        }
    }
}
```
I think it should be available in both cases.

**Comment by Neme12** [comment]
Another instance where it should be available (I'm taking these from a real code base):
```c#
using System.Collections.Generic;

class C
{
    List<object> items;

    void M(object o)
    {
        if (items.Count == 1 && items[0] is C)
        {
            Foo(items[0] as C);
        }
    }

    void Foo(C c)
    {
    }
}
```

**Comment by CyrusNajmabadi** [comment]
@Neme12 This is something that would likely be faster to just fix by opening a PR.  Would you be willing to do that?

**Comment by CyrusNajmabadi** [comment]
This is available for me:

![image](https://user-images.githubusercontent.com/4564579/152608467-5652a6e5-f61f-48be-884c-1d95595e1fe7.png)

Closing out.
