### ISSUE TITLE
Code fix for CS0708 to make member static

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#31838]
```c#
static class C
{
    void M() // CS0708: 'M': cannot declare instance members in a static class
    {
    }
}
```
It would be nice to have a code fix to make `M` static.

**Comment by CyrusNajmabadi** [comment]
@Neme12 This is something that would likely be faster to just fix by opening a PR.  Would you be willing to do that?

**Comment by MaStr11** [comment]
Related #23326

**Comment by Neme12** [comment]
Another possible code fix: remove static from the class

**Comment by sharwell** [comment]
> It would be nice to have a code fix to make `M` static.

This seems straightforward. Marking this as **help wanted** unless someone finds cases during implementation that are more complicated.

> Another possible code fix: remove static from the class

To me, this seems like the less desirable fix.

**Comment by Evangelink** [comment]
@sharwell @CyrusNajmabadi I wanted to give a try at implementing some code fix and found this issue that looked quite simple to start with but I am having some trouble to find where to add the code. Do you agree that this should not be done in this repo but in https://github.com/dotnet/roslyn-analyzers instead? If so shall I link this issue from the other repo issue/PR?

**Comment by sharwell** [comment]
@Evangelink code fixes for compiler errors (C# errors starting with CS and Visual Basic errors starting with BC) can go in dotnet/roslyn.

Two examples you can review are:

* `AbstractAddObsoleteAttributeCodeFixProvider`, `CSharpAddObsoleteAttributeCodeFixProvider`, and `VisualBasicAddObsoleteAttributeCodeFixProvider`. This example shows how to implement a code fix for a compiler warning or error.
* `AbstractAddAccessibilityModifiersCodeFixProvider`, `CSharpAddAccessibilityModifiersCodeFixProvider`, `VisualBasicAddAccessibilityModifiersCodeFixProvider`. This example shows how to implement a code fix that adds a modifier to a member.
