### ISSUE TITLE
Code fix for CS0513 to make class abstract

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#31833]
```c#
class C
{
    public abstract void M(); // CS0513: 'C.M()' is abstract but it is contained in non-abstract class 'C'
}
```
It would be nice to have a code fix to make `C` abstract.

**Comment by CyrusNajmabadi** [comment]
@Neme12 This is something that would likely be faster to just fix by opening a PR.  Would you be willing to do that?

Also, consider another fix to be removing 'abstract' from the method and giving it a body.

**Comment by MaStr11** [comment]
Related #23326
