### ISSUE TITLE
Code fix for CS0509 to unseal a class

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#31832]
```c#
sealed class C
{
}

class D : C // CS0509: 'D': cannot derive from sealed type 'C'
{
}
```

It would be nice to have a code fix to remove `sealed` from C.

**Comment by CyrusNajmabadi** [comment]
@Neme12 This is something that would likely be faster to just fix by opening a PR.  Would you be willing to do that?

**Comment by MaStr11** [comment]
Related #23326

**Comment by Neme12** [comment]
@sharwell I don't understand. Why is this problematic for the first team?

**Comment by Neme12** [comment]
I don't understand why this would be problematic for anyone. They can always do this manually with just a few keystrokes. This feature would just be there to help speed that up even more in case that's what they really want to do.

**Comment by sharwell** [comment]
@Neme12 this feature is not blocked
