### ISSUE TITLE
VB code style to prefer '&' for string concatenation

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#31834]
It would be nice to have a code style that would let me enforce always using `&` as opposed to `+` for string concatenation.

**Comment by CyrusNajmabadi** [comment]
This seems very niche.  If you want such a style preference (Something i don't think we've heard at all from others), why not write an analyzer for this purpose?

**Comment by Neme12** [comment]
Using `&` over `+` seems to be the recommendation.

See https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/addition-operator
> When you use the + operator, you might not be able to determine whether addition or string concatenation will occur. Use the & operator for concatenation to eliminate ambiguity and to provide self-documenting code.

> To eliminate ambiguity, you should use the & operator instead of + for concatenation.

**Comment by CyrusNajmabadi** [comment]
For VB this seems like less of a style preference, and more a behavior of auto-correct.  So in VB this would just automatically use & if it wouldn't change semantics.

**Comment by Neme12** [comment]
That seems very odd to me - but I'm not a VB dev.

**Comment by Neme12** [comment]
Are you sure there aren't people who would prefer to use `+` instead?

**Comment by CyrusNajmabadi** [comment]
I'm sure there are people who want lots of things.  For example, some VB devs probably don't want their modifiers to be ordered automatically by VB.  C'est la vie.

**Comment by CyrusNajmabadi** [comment]
>  I don't think this should be a preference String + String should be obsolete/warning and removed over time even better if the IDE can do it.

Can you please file that over at vblang?  Warnings need to be decided be their LDM.  Thanks!

**Comment by paul1956** [comment]
@CyrusNajmabadi Done as issue #363.

**Comment by vbjay** [comment]
So the issue of using + is when you have a string and a number.  The confusion and unexpected results can be a major issue.  

![image](https://user-images.githubusercontent.com/3629489/50926495-28a7b080-1423-11e9-81e9-2a095479d805.png)


& declares that the values on each side are strings and will force conversion before concatenation and you would get "222" with &.  It is never recommended to use + with strings.

An analyzer that would highlight this is a great idea.

**Comment by CyrusNajmabadi** [comment]
> An analyzer that would highlight this is a great idea.
> Yes. Option strict is recommended.

I don't understand the point of an analyzer to replicate a rule that *already* exists in the language.  Why not just use the existing language feature that already checks this and gives you an error?  It would just be unnecessary duplication.

**Comment by vbjay** [comment]
Not everyone uses option strict.  I know that adding a string and a numeric type results in a numeric type.  The real fun is when you do this.

![image](https://user-images.githubusercontent.com/3629489/50929939-94dae200-142c-11e9-9f55-4919f2d3b6bc.png)

The point is this is a vb feature.  it can be useful.  Knowing when to use + vs & is part of knowing the language.  A warning showing possible conversion to a numeric type is a good idea.

**Comment by vbjay** [comment]
Maybe analyzer was the wrong word. The point was that a warning shows saying numeric conversion likely or some other warning.

**Comment by CyrusNajmabadi** [comment]
> The point was that a warning shows saying numeric conversion likely or some other warning.

Isn't that what 'option strict on' would do?  You turn it on and it says: 

![image](https://user-images.githubusercontent.com/4564579/50935681-ab2f7080-1421-11e9-9871-1caae52e98d3.png)

**Comment by vbjay** [comment]
Look.  I like option strict. IT'S NOT ALWAYS USED!!!!!!  A warning pointing out the issue is a good way for people to be aware of the issue.

**Comment by CyrusNajmabadi** [comment]
> Look. I like option strict. IT'S NOT ALWAYS USED!!!!!! 

But... then why would they use this analyzer?  All an analyzer does is give you a warning/error/whatever when you enable it.  

So... why would people use this anlayzer, but not use the option *that already exists to help find and warn you about these sorts of problems*

**Comment by vbjay** [comment]
Now that explains the thinking better. I taught students at a community college. When they are learning I do tried to get them to use option strict.  Not all students would and some would turn it off in the lab. That was fun for the next student creating a project. 

So. The idea was if an analyzer was provided that would help the non experts. Pointing out issues like I pointed out.

**Comment by CyrusNajmabadi** [comment]
> So. The idea was if an analyzer was provided that would help the non experts. 
> Not all students would and some would turn it off in the lab.

Why wouldn't this be an issue for the 'analyzer'?  Effectively, this would be about providing two ways to do the same thing.  Would the hope then be that these students would not turn off *both* of these things?

Also, how would you deal with the issue of duplication here?  You'd have the compiler and analyzer reporting the same issue.

Finally, think about this from the perspective of someone who does *not* want this error.  First, they turn off option-strict, then they have this analyzer warning tehm, so they have to turn that off as well.  You've forced them to turn off two separate systems telling them the same thing.  There's no precedent for this.  Why would we have analyzer just duplicating all the warnings/errors the compiler already produces?

**Comment by CyrusNajmabadi** [comment]
We are unlikely to change tehse vb experiences.
