### ISSUE TITLE
Code fix for CS0122 to expand accessibility

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#31837]
```c#
class C
{
    void Foo()
    {
    }
}

class D
{
    void M()
    {
        var c = new C();
        c.Foo(); // CS0122: 'C.Foo()' is inaccessible due to its protection level
    }
}
```
It would be nice to have a code fix to make `Foo` public. This code fix would always use the minimum required accessibility to make the code compile, so for example if I'm in a derived class, it would use `protected` instead of `public`.

**Comment by CyrusNajmabadi** [comment]
@Neme12 This is something that would likely be faster to just fix by opening a PR.  Would you be willing to do that?

**Comment by MaStr11** [comment]
Related #23326

**Comment by sharwell** [comment]
This one seems less obvious. It's possible we use this design, but right now it seems more likely that we'd want to wait.

**Comment by Neme12** [comment]
@sharwell What do you mean by "less obvious"?

**Comment by Neme12** [comment]
I'm not saying this is the correct fix that the user should apply 100% of the time, just like it's not always the correct fix to generate a variable, field or a property but they're always offered even if I'm just missing a `using`. It would just be an option.

**Comment by Neme12** [comment]
Inaccessible members don't even show up in IntelliSense. The only time I ever end up typing inaccessible members and getting to this error message is if I know that this member is there and I intend to call it anyway by typing its name and then using "go to definition" to make it public.

**Comment by Neme12** [comment]
Can we stop pretending that users are brainless robots who will do anything the IDE will give them the option to do as opposed to having their own intent as to what kind of code they want to write? It's not like they not offering a code fix will stop them from doing this manually...

**Comment by CyrusNajmabadi** [comment]
> It's not like they not offering a code fix will stop them from doing this manually...

It could be that them doing this manually is totally fine...

**Comment by Neme12** [comment]
So why is doing this through a code fix not fine?

**Comment by sharwell** [comment]
@Neme12 Sorry for not explaining better. I marked this as needing a design review because I'm not sure how the rest of the team will feel and I don't want to make a decision without giving them the opportunity to provide feedback. It's also possible that someone knows of an action to provide for this error which better aligns with the actions real users tend to take after observing this error.

**Comment by sharwell** [comment]
We decided to mark this one as **Won't Fix** for now. The short version is we aren't sure that marking something as public is the desired course of action when this error is encountered (e.g. encapsulation guidance would say use the least-necessary accessibility). It also doesn't seem like this code fix would save users enough time to try and design all the edge cases for how we think it might be used.

In the future, it would be nice to have data related to the actions a user takes to resolve a compilation error after observing it. If we had such information, we might be able to reopen this with a more specific design. However, for now it seems reasonable to leave this error without an automated fix.

**Comment by Neme12** [comment]
@sharwell i guess we're going to disagree. Yes of course this isn't the recommended action and no guideline would suggest making something public that wasn't intended to be public. I agree with your point about encapsulation and admit that this sort of fix is questionable. All that is true, but reality is sometimes different and there are tradeoffs in practice.

It feels to me that this is like saying "you shouldn't use InternalsVisibleTo". Yes, you shouldn't, but sometimes you still do, and you want the IDE to have completion for it as opposed to saying "this is something we don't recommend so we won't help you type that". That's a pretty draconian approach. I don't think it's the purpose of the IDE to judge you or punish you for violating a guideline.

I think I did this exact sort of thing in a Roslyn PR and it was you who said that's fine for now. This is not the ideal thing to do but sometimes it is acceptable.

**Comment by Neme12** [comment]
@sharwell  A good scenario:
I'm splitting a test class into two classes - an abstract class containing the test asserts and a derived class containing the actual tests. When I move the methods I get a bunch of accessibility errors where I have to change some methods from private to protected.
