### ISSUE TITLE
Conflict between IDE name simplification and nullable inference

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#31849]
**Version Used**: 
VS 2019 Preview 1
**Steps to Reproduce**:

```C#
using System.Threading.Tasks;

class C
{
    Task<string?> FooAsync()
    {
        return Task.FromResult("something");
    }
}
```

**Expected Behavior**:
No warning

**Actual Behavior**:
CS8619	Nullability of reference types in value of type 'Task<string>' doesn't match target type 'Task<string?>'.

**Note**:
If I change it to `Task.FromResult<string?>("something");`, then`<string?>` is faded out with an IDE0001.

**Comment by jcouv** [comment]
Changed label to IDE. The compiler behavior is by-design. You cannot assign a `Task<string>` to a `Task<string?>` without a warning, because the type argument is not contravariant (it's not marked as `in TResult`, I don't know why).

**Comment by sharwell** [comment]
> I don't know why

`in` generic type parameters are only allowed for interfaces and delegates. `Task<TResult>` is a concrete type.

**Comment by jasonmalinowski** [comment]
@333fred @jcouv Do we have a tag for bugs blocked by not having a nullability API yet? This would fall into that bucket.

**Comment by jcouv** [comment]
We don't have a label or a formal way of tracking dependency. I'd link to the public API issue: https://github.com/dotnet/roslyn/issues/26198
