### ISSUE TITLE
Command to show or copy value of string literal

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#31842]
String literals can be complicated. They have escape characters, verbatim string literals have double quotes, interpolated string literals have double curlies... It would be nice to have either a command that would
- Copy the value of the string literal to the clipboard
or
- Show a dialog with the (possibly multiline) text, which would make it easy to see and copy the value. This should be the same dialog that is shown when debugging:
![image](https://user-images.githubusercontent.com/11444821/50056464-ddb8b700-015c-11e9-9a87-3369e06b080a.png)

I also propose that this command work not only on regular string literals, but on interpolated strings as well. It would have to either remove the interpolated part altogether or replace it with some kind of a marker.

This would be extremely useful for scenarios like this:

```c#
        [Theory, Trait(Traits.Feature, Traits.Features.TypeInferenceService)]
        [InlineData("IAsyncEnumerable")]
        [InlineData("IAsyncEnumerator")]
        [InlineData("InvalidGenericType")]
        public async Task TestYieldReturnInAsyncMethod(string returnTypeName)
        {
            var markup =
$@"namespace System.Collections.Generic
{{
    interface {returnTypeName}<T> {{ }}
    class C
    {{
        async {returnTypeName}<int> M()
        {{
            yield return [|abc|]
        }}
    }}
}}";
            await TestAsync(markup, "global::System.Int32");
        }
```
Getting the raw string value from this (so that I can test this manually or just see that this represents the string I want it to represent and I didn't make a mistake when escaping) is a very tedious, slow and error-prone task. I have to copy the inside of the string literal, then replace all double curlies & replace all double quotes.

**Comment by CyrusNajmabadi** [comment]
Nifty idea.  @tmat Do you know if hte debuger text-visualizer dialog is available in some manner for other code to call into outside of a debugging session?

**Comment by CyrusNajmabadi** [comment]
Pity.  @Neme12 I'd likely start just by implementing this as a lightbulb option on string literals then.

**Comment by jinujoseph** [comment]
**Design Meeting Notes**
This will be a very useful feature for string esp for json and such. May be good to show for constant expression as well. 

May be related to https://github.com/dotnet/roslyn/issues/31869 cc @sharwell

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
