### ISSUE TITLE
Tools Options | Text Editor | C#  | Code Styles | Formatting:  some option page tabs/settings missing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31859]
1. Open the mentioned tools options dialog page

Expected: same child nodes under Code Styles node, and complete settings in the option pane. Similar to what are in 15.9

Actual:

Sometimes I only see two child nodes: General and Naming.

Sometimes under General, i don't see the section of Format Document Settings (experimental)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/408963/tools-options-text-editor-c-code-styles-formatting.html
VSTS ticketId: 752079_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
> Sometimes I only see two child nodes: General and Naming.

This is the bug.

> Sometimes under General, i don't see the section of Format Document Settings (experimental)

This was intentionally removed for 16.0.

**Comment by ryzngard** [comment]
User is no longer seeing missing section, no known repro
