### ISSUE TITLE
Error List says that it has finished getting results, but analyzer's results haven't been populated

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#31850]
**Version Used**: 

**Steps to Reproduce**:

1. git clone http://github.com/dotnet/project-system
2. git checkout dd356fe61c645eae131112d5eb03583d70d93e93
2. From VS 2019 command-prompt, run `project-system>build`
3. Open ProjectSystem.sln

**Expected Behavior**:
For Error List title to go from `Error List...` to 'Error List` when it has done analyzing the code for issues

**Actual Behavior**:
Title goes from `Error List...` to `Error List` goes away for ~30 seconds, only for analyzer results to come in much later

I captured the last 5 seconds here:
![errorlist2](https://user-images.githubusercontent.com/1103906/50060967-2325c480-01ef-11e9-8a7b-8550a2e176f1.gif)

**Comment by davkean** [comment]
tag @mavasani @heejaechang

**Comment by CyrusNajmabadi** [comment]
Closing out as this was entirely rewritten for LSP.
