### ISSUE TITLE
commenting raw strings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31857]
1) Use some code with raw string
2) Comment out lines with raw string using ctrl+e,c
3) Use refactor ctrl+e,d
4) The comment block is now moved into current block
5) Uncomment lines using ctrl+e, u
6) Use refactor ctrl+e, d
7) I would expect that raw string is align to the left marging but it stays in a block. It's error because raw string contains additional whitespaces

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/408448/commenting-raw-strings.html
VSTS ticketId: 751444_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
Tentatively marking this as **Won't Fix** pending design review. Will update based on the result of the design review meeting.
