### ISSUE TITLE
"Code Cleanup" doesn't "Simplify type name"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31855]
It should refactor, or at least provide an option to refactor, `private readonly System.Boolean myBoolean;` to `private readonly Boolean myBoolean;` or even `private readonly bool  myBoolean;` according to user's preferences.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/409615/code-cleanup-doesnt-simplify-type-name.html
VSTS ticketId: 752510_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
> or even `private readonly bool myBoolean;` according to user's preferences.

📝 This part already works. Leaving the issue open for just the request involving the framework type name, `Boolean`.

**Comment by CyrusNajmabadi** [comment]
Closing out due to age and lack of feedback.
