### ISSUE TITLE
Double-clicking item in "Find all References" does not work if line is in a collapsed regaion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31856]
In VS2017, double-clicking on a result from &quot;Find all references&quot; will correctly take you to that line in the source file but this does not work in VS2019 Preview 1 - double clicking a result takes me somewhere near where the result is but does not put the cursor in the symbol I searched for like VS2017 does.

If the source line in question happens to be inside a collapsed region then double clicking the result simply does nothing at all.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/400941/double-clicking-item-in-find-all-references-does-n.html
VSTS ticketId: 742125_
_These are the original issue comments:_

Fiona Niu[MSFT] on 12/6/2018, 10:30 PM (10 days ago): <p>Thank you for your feedback! In order for us to investigate this further, could you please provide a more detailed description to help us better understand this scenario?  Which project does this happen on(C#/VB, C++ or others)?</p><p> </p><p>We look forward to hearing from you!</p>

Lee Millward on 12/6/2018, 11:23 PM (10 days ago): <p>This was found on a C# solution. I right-clicked on a class, chose "Find All References" then started double-clicking through the list of references in the '&lt;class name&gt;' References tool window but noticed that the actual line with the class reference on was not visible in the code editor window despite there being no floating tool windows which might have been overlapping that source line.</p><p>I noticed that on double-clicking one oft the references the cursor didn't move at all, when I manually navigated to that line I noticed it was in a region that was collapsed. After expanding the region the cursor position was updated when I double-clicked on that reference again but it still wasn't taken to the right location.</p>

Fiona Niu[MSFT] on 12/10/2018, 11:57 PM (6 days ago): <p>Thanks a lot for providing the information. We are forwarding the issue to the engineering team for investigating. The engineer will investigate the issue and keep you posted. </p>
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Not repro for me.  Double clicking the item expands hte collapsed section and takes me to the identifier.  Closing out.
