### ISSUE TITLE
visual studio 2019 preview lightbulb doesn't work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31860]
On a warning that exists at the class level, the lightbulb suggestion mechanism does not work.

When the lightbulb appears after hovering the cursor over the class name, the description of the warning does appear.  But clicking on the lightbulb or the &quot;Show potential fixes&quot; link does not work.

To reproduce:
Create a new class.
Override the equals method but do not implement a GetHashCode method.
Compile your code.
When the warning squiggles appear underneath the class name, hover your mouse over them to show the lightbulb and description.
Click on the lightbulb or &quot;Show potential fixes&quot; link.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/400997/visual-studio-2019-preview-lightbulb-doesnt-work.html
VSTS ticketId: 742191_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't repro this.
