### ISSUE TITLE
CS8603 for explicit interface implementation

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#31867]
**Version Used**: 
VS2019 Preview 1

**Steps to Reproduce**:
```C#
using System.Collections;
using System.Collections.Generic;

public struct Enumerator<T> : IEnumerator<T>
{
    object IEnumerator.Current => Current;

    public T Current => throw null;
    public void Dispose() => throw null;
    public bool MoveNext() => throw null;
    public void Reset() => throw null;
}
```

**Expected Behavior**:
No warning

**Actual Behavior**:
Program.cs(6,35,6,42): warning CS8603: Possible null reference return.

**Comment by cston** [comment]
If `T` is a nullable type (say, `object?` or `int?`), the return value `=> Current` will be treated as nullable.

**Comment by Pilchie** [comment]
So, what are my options for writing an unconstrained Enumerator?

**Comment by cston** [comment]
Perhaps change the nullability of the explicit implementation return type:
```c#
object? IEnumerator.Current => Current;
```

**Comment by Pilchie** [comment]
What do you know?  That does work.  Very unintuitive though it makes sense...

**Comment by jaredpar** [comment]
Closing as this behavior is "By Design".
