### ISSUE TITLE
Casted generic triggers CS8600 and CS8604

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#31866]
**Version Used**: 
3.0.0-beta2-18616-01

**Steps to Reproduce**:
```C#
using System.Collections;
using System.Collections.Generic;

class C<T> : IEnumerable<T>
{
    public void F<U>() where U : T
    {

        var tmp = new Other<U>();
        foreach (T i in this)
        {
            tmp.Add((U)i);
        }
    }

    public IEnumerator<T> GetEnumerator()
        => throw new System.NotImplementedException();

    IEnumerator IEnumerable.GetEnumerator() 
        => GetEnumerator();
}

class Other<T>
{
    public void Add(T t) { }
}
```

**Expected Behavior**:
No warning

**Actual Behavior**:
1>Program.cs(14,21,14,25): warning CS8600: Converting null literal or possible null value to non-nullable type.
1>Program.cs(14,21,14,25): warning CS8604: Possible null reference argument for parameter 't' in 'void Other<U>.Add(U t)'.

**Comment by cston** [comment]
The warnings are expected. `T` may be nullable and `U` might be not nullable: `C<object?>.F<string>()` for instance.

**Comment by Pilchie** [comment]
@cston How would you go about annotating [ArrayBuilder<T>.ToDowncastedImmutable<U>](http://source.roslyn.io/#Microsoft.CodeAnalysis/ArrayBuilder.cs,e9fc70b0518644cb)?

**Comment by cston** [comment]
@Pilchie, the signature of `ArrayBuilder.ToDowncastedImmutable` seems reasonable as is. In the method body, we'll probably need `!` when converting items of `T` to `U` though:
```C#
ImmutableArray<U> ToDowncastedImmutable<U>() where U : T
{
    var builder = new ArrayBuilder<U>();
    foreach (var item in this)
        builder.Add((U)item!);
    return builder.ToImmutableArray();
}
```
