### ISSUE TITLE
Tuple names shouldn't affect nullability of value types

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#31864]
**Version Used**: 
3.0.0-beta2-18616-01

**Steps to Reproduce**:

```C#
using System;

class C
{
    public C()
    {
        DateTime? earliest = DateTime.MaxValue;
        string? earliestPath = null;
        bool hasOutput = false;

        var x = hasOutput
            ? (earliest, earliestPath)
            : (null, null);
    }
}
```

**Expected Behavior**:
No warnings

**Actual Behavior**:
Program.cs(11,17,13,27): warning CS8626: No best nullability for operands of conditional expression '(DateTime? earliest, string? earliestPath)' and '(DateTime?, string?)'.

**Comment by jcouv** [comment]
From discussion with Chuck and Neal, we think there's a way to resolve this by adjusting the rules for merging nullability specifically for tuples (`TupleTypeSymbol.MergeNullability(TypeSymbol other, VarianceKind variance, out bool hadNullabilityMismatch)`).
We'll have to confirm with LDM though, so tagged the issue with Language Design.
