### ISSUE TITLE
Escape characters on paste

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#31869]
It would be nice to automatically escape special characters when pasting content into a string. If the paste operation triggered an escaping operation, then the first Undo operation after paste would undo just the character escaping.

| First position of copied region | Pasting outside a literal | Pasting inside a literal |
| --- | --- | --- |
| Inside a text literal | Unescape on paste | Correct escape sequences that change meaning |
| Outside a text literal | As-is | Escape on paste |
| Raw text (e.g. browser) | As-is | Escape on paste |

**Comment by jinujoseph** [comment]
This should probably be a platform feature to benefit other langs , cc @olegtk

**Comment by sharwell** [comment]
Note that the escaping procedures for raw strings are more complicated, but the overall strategy holds. See https://github.com/dotnet/roslyn/issues/59820.

**Comment by CyrusNajmabadi** [comment]
Fixed fully with https://github.com/dotnet/roslyn/pull/61177.
