### ISSUE TITLE
Enabling NullableReferenceTypes breaks "Theory" xunit tests

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#31872]
**Version Used**: 
3.0.0-beta2-18616-01

**Steps to Reproduce**:

```C#
using System.Threading.Tasks;
using Xunit;

namespace XUnitTestProject1
{
    public class UnitTest1
    {
        [Theory]
#pragma warning disable xUnit1010 // The value is not convertible to the method parameter type
        [InlineData(new object[] { new[] { "Debug|x86" } })]
        [InlineData(new object[] { new[] { "Debug|x86", "Release|x86" } })]
        [InlineData(new object[] { new[] { "Debug|x86", "Release|x86", "Release|AnyCPU" } })]
#pragma warning restore xUnit1010 // The value is not convertible to the method parameter type
        public Task WhenActiveConfigurationChanges_LoadsConfiguredProject(string[] configurationNames)
        {
            return Task.CompletedTask;
        }
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>

    <IsPackable>false</IsPackable>
    <LangVersion>8.0</LangVersion>
    <NullableReferenceTypes>true</NullableReferenceTypes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.8.0" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
  </ItemGroup>

</Project>
```

**Expected Behavior**:
No xUnit1010, and tests pass

**Actual Behavior**:
xUnit1010 errors, and if suppressed, tests fail

**Note**: 
Related to #31740?

**Comment by jcouv** [comment]
Here's the relevant XUnit code: https://github.com/xunit/xunit.analyzers/blob/cebd67a5c3534e43a2e7b5fa0367d9ed1260bb3c/src/xunit.analyzers/InlineDataMustMatchTheoryParameters.cs#L127

It is using `Compilation.ClassifyConversion` to verify the inline data matches the parameters.
I'll build an API-level repro.

**Comment by Pilchie** [comment]
Note: the bigger concern is that the tests fail with nullable enabled, even if the diagnostics are suppressed.

**Comment by jaredpar** [comment]
@Pilchie what error do you get when the tests fail?

**Comment by Pilchie** [comment]
@jaredpar see https://dnceng.visualstudio.com/public/_build/results?buildId=59374&view=ms.vss-test-web.test-result-details

```
System.InvalidOperationException : The test method expected 2 parameter values, but 1 parameter value was provided.
```

**Comment by Pilchie** [comment]
Hmm - I thought I had tested it the other way, but it seems I can only repro this when adding a compiler NuGet package.  I was using `    <PackageReference Include="Microsoft.NET.Compilers" Version="3.0.0-beta2-18616-01" />`.

Also tagging @bradwilson.

**Comment by bradwilson** [comment]
```csharp
[InlineData(new object[] { new[] { "Debug|x86" } })]
public Task WhenActiveConfigurationChanges_LoadsConfiguredProject(string[] configurationNames)
```

This doesn't look correct. I would've expected this instead:

```csharp
[InlineData(new[] { "Debug|x86" })]
public Task WhenActiveConfigurationChanges_LoadsConfiguredProject(string[] configurationNames)
```

**Comment by jcouv** [comment]
@bradwilson The version you proposed [doesn't compile](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgD4ACADAAS0CMA3ALABQtAzMwCZGAYW4BvboymMA2gEkKAGxwUIAEVhQAFKoDujAPbAAVhAwwZAXUZjGeqzcYAiNRGBwA5tQAeADgBsTowAviEAlJaS0nzMACyMALJaYVFSElzSIamM2fJKKuqaOhD6rPQOti5unj4BQcER2TG08QkCydnpmcHcPVzcMcjQihAAJoKMCsqqGjBQAIIwMAg47mSMIMwsAHSLy6twZOJN/FMFswtLK2sQWiQIUAC2yIYmZhbWo5opGdJd0n1etwgA).
I'm not sure why. Like you, I expected the `params` parameter would handle that. I'll leave that question aside for the purpose of the present issue though.

**Comment by Pilchie** [comment]
Doesn't the params parameter handle the argument list, but in order for the argument to be an array, the element in the params array also has to be an array?

**Comment by bradwilson** [comment]
You're right, the `params` stuff is probably broken here. :disappointed: Never mind me, then.

**Comment by bradwilson** [comment]
That probably means there's nothing we can do about xUnit1010, either.

**Comment by jcouv** [comment]
From offline discussion with @Pilchie, it seems the latest compiler fixes the issue (I can no longer repro, nor can he). I'll go ahead and close.
