### ISSUE TITLE
Dependency Property shortcut Change suggestion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31877]
When coding in C# and using the "propdp" shortcut, I would suggest that the dependency register be changed from:

```csharp
DependencyProperty.Register("PropertyName", typeof...
```

to:

```csharp
DependencyProperty.Register(nameof(PropertyName), typeof...
```

This way if the the developer ever uses <kbd>Ctrl</kbd>+<kbd>R</kbd>, <kbd>R</kbd> to rename the Property it will also apply to the Dependency Property

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/406851/dependency-property-shortcut-change-suggestion.html
VSTS ticketId: 750062_
_These are the original issue comments:_

Jane Wu [MSFT] on 12/13/2018, 05:51 PM (3 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by sharwell** [comment]
Blocked on #31879

**Comment by CyrusNajmabadi** [comment]
Closing out as subsumed by smart snippets.
