### ISSUE TITLE
FSA reports warnings about nullability needing to be enabled

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#31870]
**Version Used**: 
Version 16.0.0 Preview 2.0 [28414.103.d16.0stg]

**Steps to Reproduce**:

1. Enable C# 8 and `<NullableReferenceTypes>`
2. Annotate a bunch of code for nullability
3. Turn FSA on.
4. Close all files

**Expected Behavior**:
No warnings

**Actual Behavior**:
A bunch of warnings like:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8632	The annotation for nullable reference types should only be used in code within a '#nullable' context.	Microsoft.VisualStudio.ProjectSystem.Managed	C:\Code\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\Composition\OrderPrecedenceImportCollectionExtensions.cs	59	Active
```

**Comment by Pilchie** [comment]
Tag @jinujoseph @heejaechang

**Comment by Pilchie** [comment]
@sharwell this is not a compilers issue.  It's an issue with the OOP marshalling layer.

**Comment by jinujoseph** [comment]
cc @jcouv
