### ISSUE TITLE
Nullable: dealing with generated code in a project

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#31875]
Reported by @Pilchie 

Presently, there are a few choices ([updated]):
- update the generator (which may be difficult)
- leave the feature off at the project level, and only turn it on for non-generated source files
- detecting "generated" code
- use `.editorconfig` to suppress warnings for some files

Relates to https://github.com/dotnet/roslyn/issues/7000 (different mechanism to detect "generated" code)

**Comment by Pilchie** [comment]
One potential solution (when it's implemented) is to use `.editorconfig` to change the severity of the diagnostics in the files that are generated.

Another would be for the compiler to obey the `[CompilerGenerated]` attribute.

**Comment by jcouv** [comment]
Updating the bug to reflect that the fix made it into dev16 preview4.
