### ISSUE TITLE
Show not defined parameter in popup

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31880]
<p></p><p>When I press CTRL + SHIFT + space key, the intellisense window could show the parameters not passed to a method, with a different color (or bold)</p><p></p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/51387-sugestao-vs.png">sugestao-vs.png</a></p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/402102/show-not-defined-parameter-in-popup.html
VSTS ticketId: 743743_
_These are the original issue comments:_

Jane Wu [MSFT] on 12/9/2018, 08:26 PM (7 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.
