### ISSUE TITLE
Range indexer on array should probably not be ref-returning

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#31889]
The following works:

```C#
using System;
public class C {
    public void M(int[] arr) {
        ref int[] x = ref arr[0..2];
    }
}
```

But I'm not sure it should.

**Comment by sharwell** [comment]
💭 I would have expected `arr[0..2]` to produce `Span<int>`, which is a ref-like type but not `ref int[]`

**Comment by Neme12** [comment]
Does the indexer copy the array? That is very surprising to me.
