### ISSUE TITLE
Foreach missing a W-warning

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#31891]
**Version Used**: 
3.0.0-beta2-18616-01

**Steps to Reproduce**:
```C#
using System;
using System.Collections.Generic;
using System.ComponentModel;

class C<T>
{
    public C(List<T> list)
    {
        foreach (INotifyPropertyChanged item in list)
            item.PropertyChanged += OnItemPropertyChanged;
    }

    private void OnItemPropertyChanged(object sender, PropertyChangedEventArgs e)
        => throw new NotImplementedException();
}
```

**Expected Behavior**:
No warning

**Actual Behavior**:
UnitTest1.cs(10,13,10,17): warning CS8602: Possible dereference of a null reference.

**Comment by Pilchie** [comment]
@sharwell Then why wouldn't that happen with a `foreach` using `var` or the type of the `List`?  The cast changes the behavior, but can't introduce nulls.

**Comment by sharwell** [comment]
In both of those cases, the iteration variable will have type `T` which, as an unconstrained generic type, will not be assumed non-null. You would get a warning CS8602 (possible dereference of a null reference) on the expression `item.PropertyChanged`.

**Comment by Pilchie** [comment]
If that were true, this would make sense.  But it isn't :)  Of course, you can't have a `T.PropertyChanged` without *any* constraints, but by your logic, I would expect CS8602 from the below, and it doesn't happen.  Nor does the warning occur about passing a potential null as an argument if you use `var/T` on an unconstrained T.
```C#
using System;
using System.Collections.Generic;
using System.ComponentModel;

class C<T>
    where T : INotifyPropertyChanged
{
    public C(List<T> list)
    {
        foreach (var item in list)
            item.PropertyChanged += OnItemPropertyChanged;
    }

    private void OnItemPropertyChanged(object sender, PropertyChangedEventArgs e)
        => throw new NotImplementedException();
}
```

**Comment by sharwell** [comment]
The default constraint is `object?`. I used `ToString` in testing because it's defined on object. If you want to do the same test for this event, you should use this:

```
class C<T>
  where T : INotifyPropertyChanged?
```

**Comment by Pilchie** [comment]
Ah right.  Okay.

**Comment by Pilchie** [comment]
It *is* still interesting that an explicit type of `INotifyPropertyChanged` *without* a `?` can still be null in this case, because the cast from null to it would succeed.

**Comment by Pilchie** [comment]
Maybe the warning should appear *in* the foreach if there is an explicit type that doesn't match the enumerated type and the explicit type isn't nullable?

**Comment by jcouv** [comment]
Tagging @cston

**Comment by jcouv** [comment]
Yes, I think there should be a non-safety warning for possible assignment of `null` from the collection into the iteration variable that is declared with a non-nullable type.

**Comment by cston** [comment]
We are generating two warnings currently, for the assignment to the iteration variable, and for the dereference of `item`. That is the expected behavior since `T` may be a nullable type.
```
(9,18): warning CS8600: Converting null literal or possible null value to non-nullable type.
(10,13): warning CS8602: Possible dereference of a null reference.
```
