### ISSUE TITLE
Assigning to readonly field in constructor and getting warned for not assigning

### ISSUE THREAD

**Issue by robertsundstrom** [dotnet/roslyn#31896]
**Version Used**: 
Latest major (in Visual Studio 2017 Preview)

**Description**
Compiler yields warning "Field is never assigned to, and will always have its default value null" for readonly field despite it being assigned to in the constructor.

Project compiles just fine otherwise.

**Expected result**
No warning.

![2018-12-18 4 2](https://user-images.githubusercontent.com/919580/50145657-6137ec80-02b2-11e9-86f9-9e6f98b84ab5.png)

**Comment by jaredpar** [comment]
Do you get this when you compile as an emitted warning (look in the output window) or just in the error list?

**Comment by robertsundstrom** [comment]
I'm not sure. It might just be the IDE. I have switched to VS 2019 Preview and I get errors about targeting an old version of the C# language when using newer features - despite explicitly setting the version. It still builds. There might be something else going on with the tooling.

**Comment by jaredpar** [comment]
Try opening the error list and setting the drop down to say "Build". If the error doesn't show up there but does show up when "Intellisense" is selected then it's an IDE issue. Seems likely though this is the case if this is building successfully.

**Comment by jasonmalinowski** [comment]
@robertsundstrom If you're seeing some version targeting errors in 2019, please file a separate bug. That's something we'll also want to look at, but would be a different problem than whatever is happening here.

For the "will always have default value of null" bug, if you close and reopen VS, _and do not edit any files_, does the squiggle come back?

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard from customer in over a year.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi I think this is still worthy of investigation?
