### ISSUE TITLE
"warning IDE0055" reported for `!` operator

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#31907]
```C#
// warning IDE0055: Fix formatting
var returnType = (_useMethodSignatureReturnType ? _methodSignatureOpt! : method).ReturnType;
```

**Comment by sharwell** [comment]
@cston IDE0055 simply reports cases where **Format Document** would change the formatting. I'm assuming the code above shows the desired formatting for this case. Can you also include an example of what this line looks like after running **Format Document**?

**Comment by cston** [comment]
@sharwell, Format Document removes the space between `!` and `:`:
```C#
var returnType = (_useMethodSignatureReturnType ? _methodSignatureOpt!: method).ReturnType;

```
