### ISSUE TITLE
AD0001 warning when #nullable is used inside of a block

### ISSUE THREAD

**Issue by johnkellyoxford** [dotnet/roslyn#31912]
**Version Used**: VS 2019 Preview 1, C# 8.0 beta, <NullableReferenceTypes> true in .csproj

**Steps to Reproduce**:
Build this:
```
using System;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;

namespace Playground
{
    internal static class Program
    {
        private static void Main(string[] args)
        {
#nullable enable
            string? a;
            #nullable disable
        }
    }
}
```

**Expected Behavior**:
All good, except for the unused warning

**Actual Behavior**:
"Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.Formatting.FormattingDiagnosticAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Unexpected false'."

**Comment by jaredpar** [comment]
The design of `#nullable` is specifically to allow it in blocks. The warning though is unexpected. Moving to IDE

**Comment by jasonmalinowski** [comment]
Not able to reproduce anymore.
