### ISSUE TITLE
EncHoistedLocalInfo doesn't handle equality of nested anonymous types

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#3192]
```PEModuleBuilder.Translate``` doesn’t seem to handle nested anonymous types (such as ```new { A = new { B = 1 } }``` correctly.

It does replace the outer public anonymous symbol with an implementation symbol:

```C#
if (namedTypeSymbol.IsAnonymousType)
{
   namedTypeSymbol = AnonymousTypeManager.TranslateAnonymousTypeSymbol(namedTypeSymbol);
}
```

but the resulting symbol still has public anonymous type as its type argument.

It’s causing trouble for EnC (test ```EditAndContinueStateMachineTests.HoistedAnonymousTypes_Nested```), but I wonder if it also has implications on NoPIA (say the type of B is a NoPIA type).

**Comment by tmat** [comment]
@AlekseyTs

**Comment by AlekseyTs** [comment]
It is not supposed to translate type arguments, they are going to be translated when Cci.IGenericTypeInstanceReference.GetGenericArguments is called. This is how all generic instantiations are handled.

**Comment by AlekseyTs** [comment]
Note that translation translates symbols to interfaces. There is no guarantee you get a Symbol implementing the interface back. Even if you do, casting back to Symbol and interrogating Symbol's APIs is likely inappropriate, doing this often "erases" translation.

**Comment by tmat** [comment]
Reopening since tests associated with this issue are skipped. We'll need to change the symbol matcher to fix the EnC issues.

**Comment by tmat** [comment]
@AlekseyTs The problem is that we have to map current type to the type in the previous compilation. The mapping logic actually works with CCI interfaces (not with symbols). It assumes that it can compare type references by calling ITypeReference.Equals and GetHashCode. That doesn't work though if the type is just partially translated.

**Comment by AlekseyTs** [comment]
@tmat Let's discuss this offline
