### ISSUE TITLE
Check for Enum with CodeAnalysis

### ISSUE THREAD

**Issue by NicolasBrandes** [dotnet/roslyn#31938]
**Version Used**: 
Microsoft.CodeAnalysis.Analyzers.2.6.1
**Description**:
I have the Issue that i want to generate TypeScript from C# Model Classes. Therefore, I have to check, whether the Type of the Property is an Enum with only reading the current Model Class. 
What the Property looks like:
`public Sex Sex { get; set; }`
What the Sex-Class looks like:
```
public enum Sex : int
    {
        Male = 0,
        Female = 1,
    }
```
If it is recognized as an Enum, following line in TypeScript should be generated:
`import { Sex } from '../enums/sex';`
instead of:
`import { Sex, SexSchema } from './sex.model';`

So how does one check for Enum-Type with roslyn?

**Comment by jmarolf** [comment]
I would recommend using the [syntax visualizer](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/syntax-visualizer?tabs=csharp) to see what enums are represented as.

You can use the [roslyn code quoter](http://roslynquoter.azurewebsites.net/) to see how to generate specific syntax

**Comment by CyrusNajmabadi** [comment]
In this case @jmarolf he's starting with teh property, but trying to figure out the return type's meaning.  So the Syntax itself isn't that helpful.

@NicolasBrandes I would recommend gitter.im/dotnet/roslyn for future one-off 'i need help' questions :)

For this one, here's what you would do:

Given a SemanticModel, call 'GetDeclaredSymbol' on the PropertyDeclarationSyntax you have.  From that, you will get an IPropertySymbol back.  This symbol has a 'Type' property telling you the return type of the property.  From that ITypeSymbol you can call get it's 'TypeKind' and check if it's an enum.  Putting it all together, you have:

```((IPropertySymbol)semanticModel.GetDeclaredSymbol(propDeclSyntax)).Type.TypeKind == TypeKind.Enum```

**Comment by Youssef1313** [comment]
@CyrusNajmabadi I think this can be closed as answered.

**Comment by JansthcirlU** [comment]
In case anyone comes across this issue to figure out the type that the enum values are based on, you can convert the enum type symbol to an `INamedTypeSymbol` to get its `EnumUnderlyingType` like this:

Example enum:
```cs
public enum MyByteEnum : byte
{
  Zero,
  Three = 0x03,
  Max = byte.MaxValue
}
```

Finding the underlying type:
```cs
// Based on Cyrus's answer pretending 'MyByteEnum' is the given property type
var type = ((IPropertySymbol)semanticModel.GetDeclaredSymbol(propDeclSyntax)).Type;

// If type is an enum, figure out its underlying type
if (type.TypeKind == TypeKind.Enum)
{
  var enumUnderlyingType = (type as INamedTypeSymbol).EnumUnderlyingType;
  Console.WriteLine($"The enum values are based on {enumUnderLyingType.ToDisplayString().Trim()}.");
  // output: The enum values are based on byte.
}
```

**Comment by davidnjohansson** [comment]
> In this case @jmarolf he's starting with teh property, but trying to figure out the return type's meaning. So the Syntax itself isn't that helpful.
> 
> @NicolasBrandes I would recommend gitter.im/dotnet/roslyn for future one-off 'i need help' questions :)
> 
> For this one, here's what you would do:
> 
> Given a SemanticModel, call 'GetDeclaredSymbol' on the PropertyDeclarationSyntax you have. From that, you will get an IPropertySymbol back. This symbol has a 'Type' property telling you the return type of the property. From that ITypeSymbol you can call get it's 'TypeKind' and check if it's an enum. Putting it all together, you have:
> 
> `((IPropertySymbol)semanticModel.GetDeclaredSymbol(propDeclSyntax)).Type.TypeKind == TypeKind.Enum`

This gives back `false` if the enum is nullable.

How would one use `GetDeclaredSymbol` if `propDeclSyntax` is a nullable of enum?

**Comment by Youssef1313** [comment]
@davidnjohansson You'll need to check for SpecialType being nullable, then get the type parameter and check if it is an enum.
