### ISSUE TITLE
Cannot build the repository

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#31934]
I'm on master using 15.9 latest and I cannot build our repository anymore. Whenever I build I get the following error: 

> C:\Users\jaredpar\code\roslyn\src\ExpressionEvaluator\Core\Source\FunctionResolver\MetadataDecoder.cs(18,13): err or CS0012: The type 'ValueType' is defined in an assembly that is not referenced. You must add a reference to ass embly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [C:\Users\jaredpar\code\r oslyn\src\ExpressionEvaluator\Core\Source\FunctionResolver\Microsoft.CodeAnalysis.FunctionResolver.csproj]

I've tried all manner of debugging this:

- Cleaned my enlistment (`git clean -dfx .`)
- Ran Restore.cmd and manually `msbuild /t:restore` 
- Updated my VS and dotnet installs (15.9 latest and 2.1.401) 
- Looked into the binary log and there is nothnig interesting there.

**Comment by jaredpar** [comment]
CC @tmat

**Comment by jaredpar** [comment]
Deleting my nuget cache fixed this error. I can't explain why that would happen but it did.

**Comment by nguerrera** [comment]
🤔
