### ISSUE TITLE
local variable messes up async result (goto loop vs. scope of captured variable)

### ISSUE THREAD

**Issue by maggo23** [dotnet/roslyn#31939]
**Version Used**: 
Visual Studio Professional 2017 15.9.4

**Steps to Reproduce**:
- Console Application
- .NET Framework 4.7.1
- Any CPU  

Compile and run following code:

```
using System;
using System.Threading.Tasks;

class Program
{
	static void Main()
	{
		Task.Run(async () =>
		{
			Begin:
			var result = await FooAsync();
			Task.Run(async () =>
			{
				await Task.Yield();
				Console.WriteLine(result);
			});
			if (result < 9) goto Begin;
		}).Wait();
		Console.ReadKey();
	}

	static int i = 0;
	static object o = new object();

	static async Task<int> FooAsync()
	{
		await Task.Yield();
		lock (o)
			return i++;
	}
}
```

**Expected Behavior**:
Numbers 0...9 are displayed once.

**Actual Behavior**:
Some numbers are missing and some numbers are displayed more than once.

**Comment by 0xd4d** [comment]
`result` is a captured and can get overwritten by the 1st Task.Run(). You can extract out the 2nd Task.Run() to a new method with `result` as an argument and you should get the result you expect. You can also await the 2nd Task.Run() call.

**Comment by maggo23** [comment]
Thanks for the quick response and your proposal. I found another workaround too (see example below). With this modification the output is as expected. I think this should not be the solution and I want to point to a possible bug.


```
using System;
using System.Threading.Tasks;

class Program
{
	static void Main()
	{
		Task.Run(async () =>
		{
			for (; ; )
			{
				var result = await FooAsync();
				Task.Run(async () =>
				{
					await Task.Yield();
					Console.WriteLine(result);
				});
				if (result >= 9) break;
			}
		}).Wait();
		Console.ReadKey();
	}

	static int i = 0;
	static object o = new object();

	static async Task<int> FooAsync()
	{
		await Task.Yield();
		lock (o)
			return i++;
	}
}
```

**Comment by HaloFour** [comment]
This behavior is expected.  Captures are by reference, not value.  When you modify `result` all lambdas that have captured that variable will immediately see that change.  When you add a `for` loop you are introducing a new scope so the compiler allocates a separate version of `result` for each capture.

**Comment by maggo23** [comment]
Thank you for the explanation and hint. It was not clear to me that implementing a loop with ```goto``` could lead to problems with scope. Now I found a simpler example to illustrate the problem and solution:

```
using System;
using System.Collections.Generic;
class Program
{
       static void Main()
       {
             var l = new List<Func<int>>();
             var i = 0;
             start:
             var v = i; // not in separate scope
             l.Add(() => v);
             if (++i <= 9) goto start;
             foreach (var f in l)
                    Console.Write(f());
             Console.ReadLine();
       }
}
```
Output: 9999999999


```
using System;
using System.Collections.Generic;
class Program
{
       static void Main()
       {
             var l = new List<Func<int>>();
             var i = 0;
             start:
             {
                    var v = i;
                    l.Add(() => v);
             }
             if (++i <= 9) goto start;
             foreach (var f in l)
                    Console.Write(f());
             Console.ReadLine();
       }
}
```
Output: 0123456789
