### ISSUE TITLE
Formatting deconstruction patterns: no space before open paren.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#31942]
The current formatting for a deconstruction pattern adds a space between the type and the open paren. However, there should be no space there.

This derives from a design principle of the syntax for pattern-matching constructs: there is a correspondence between the syntax for creating and matching data.

You create data using the expression syntax `new A(1)`, not `new A (1)`.

Similarly, you should match that data using the pattern syntax `A(1)`, not `A (1)`.

**Comment by sharwell** [comment]
Duplicate of #27268
