### ISSUE TITLE
AnalyzerConfig parser doesn't support '[]' or '[!]' matching

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#31946]
The [EditorConfig site](https://editorconfig.org) includes the following forms in the section glob specification:

Glob pattern | Meaning
-- | --
`[name]` | Matches any single character in `name`
`[!name]` | Matches any single character not in `name`

The current parser doesn't support this, but it should.

**Comment by CyrusNajmabadi** [comment]
@agocke Do you intend to implement this by converting to the equivalent regex form?  If so, be aware of the special sequences/characters .net regexes allow in character-classes.  For example, if someone has the .ec pattern `[a-z]` that should become `[a\-z]` in .net regex-land.  Thanks!

**Comment by agocke** [comment]
@CyrusNajmabadi Yup, all globbing is done by compilation to regex, of which there are many tricky bits.

**Comment by CyrusNajmabadi** [comment]
Cool, thanks! I'm happy to take a peek when you do the work.  Having done the Roslyn regex parser i am now intimately familiar with how .net does things here.  Humorously enough, `[...]` patterns are where i found the most bugs in the .net regex impl!  So i would def recommend potentially just mapping this to the "alternation" (i.e. `|`) approach.

**Comment by agocke** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/34799
