### ISSUE TITLE
Missing delegate nullability mismatch warnings

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#31958]
**Version Used**: 

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 1.1
VisualStudio.16.Preview/16.0.0-pre.1.1+28408.50
Microsoft .NET Framework
Version 4.7.03056

**Steps to Reproduce**:

```cs
#nullable enable
class C
{
  string? M(string s)
  {
    s.ToString();

    var d = (D) M;;
    d(null).ToString();

    return null;
  }

  delegate string D(string? s);
}
```

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWACgABAJgoGFGBvRiipgIwAGAPwUAsgApBQilACUvCjwZ8+UAHQAVAPYBlGAgCWuAOaT5AbkZK+ANwgIKKCgF4KkgCLyJl66rUUSQJieW19QxNzKxsAviYAdgoQwn8+AF9YvhQ4clMIeH5hCk9pYTEFf0yGIA=

**Expected Behavior**:

Nullability mismatch warning for `var d = (D) M;`
The delegate is expected to never return nulls according to its signature but the method can return null.
The delegate is expected to allow nulls passed in its parameter but the method does not.
This in turn leads to no warnings on the `d(null).ToString();` line that effectively pass `null` to `M` and dereference its result which can be `null` without any warnings.

Note that if you use an explicitly typed variable and implicit conversion instead of an implicitly-typed variable and explicit cast both warnings does appear. I.e. `D d2 = M;` results in warnings for both parameter and return types.

**Actual Behavior**:

No warnings at all in the code above.

**Comment by jcouv** [comment]
Verified this was fixed (I think it was in https://github.com/dotnet/roslyn/pull/32850)
I'll add a test to close
