### ISSUE TITLE
Target framework drop down has duplicate entries

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#31968]
Repro Steps

- Install Dev16P2 28419.233
- Restore.cmd
- Open Compilers.sln
- Open PrivateProtected.cs
- Expand the target framework drop down

Expected to have two entries: net472, netcoreapp2.1

Actual:

![image](https://user-images.githubusercontent.com/146967/50312886-9e40e200-045e-11e9-8241-d5f96d147312.png)

**Comment by JoeRobich** [comment]
To give a little more information this is how I repro'd:
- I started by opening a new instance of VS
- I then opened Roslyn.sln and PrivateProtected.cs. 
- Checked the target frameworks and saw only one entry for both 472 and netcoreapp2.1
- I then opened Compiler.sln **in the same instance of VS** and opened PrivateProtected.cs
- Checked the target frameworks and saw two entries for each
- Opened Roslyn.sln in the same instance of VS and opened PrivateProtected.cs
- Checked the target frameworks and saw three entries for each
- I then opened Compiler.sln in the same instance of VS and opened PrivateProtected.cs
- Checked the target frameworks and saw four entries for each
- Opened Roslyn.sln in the same instance of VS and opened PrivateProtected.cs
- Checked the target frameworks and saw five entries for each
- Stopped to write this

**Comment by jasonmalinowski** [comment]
This is a dupe of #32036.
