### ISSUE TITLE
Error list filtering results in error code allocations

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#31964]
This method should use a cache for the ID&rarr;error code mapping to reduce allocations.

🔗 Observed in https://developercommunity.visualstudio.com/content/problem/412691/typing-lag-in-preview-2.html

https://github.com/dotnet/roslyn/blob/51638c7f7adf70c72c80eae27732e0337de3ccca/src/Compilers/Core/Portable/Diagnostic/CommonMessageProvider.cs#L102-L105

**Comment by 333fred** [comment]
@sharwell did the trace give you any clue as to how many _individual_ error codes were generated? ie, how big this cache would need to be?
