### ISSUE TITLE
Switch expressions currently disallow trailing comma

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#31962]
Trailing commas are currently disallowed, which is inconvenient when copy/pasting a line.

```C#
public class C 
{
    public void M() 
    {
        _ = 3 switch 
        {
                2 => 1,
                _ => 2, // error
        };
    }
}
```
[Example](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgD4CwAUAAIDMABIwEysDCrA3g1ZD2bRgBZWAWQAUASn6DhSgPqsAvKzbIA7jhgYAFq0VKhA+qcumuagHysAjABoTVy6rusOT1gHpfrOQIAPYIrkoAvgDcrhEMEUA===)

In contrast, we allow trailing commas in array initializers.

**Comment by CyrusNajmabadi** [comment]
A big :+1: on this.  For anything that is commonly multi-line, not allowing the trailing comma is often a PITA.  Thanks!

**Comment by gafter** [comment]
I advocated for this but the LDM shot it down.  I'll be happy to bring it back up based on "experience".

**Comment by CyrusNajmabadi** [comment]
That would be great.  Thanks @gafter .

**Comment by alrz** [comment]
Hopefully also for property patterns which is an unordered list. 👍

**Comment by sharwell** [comment]
@gafter This will be super obvious to StyleCop Analyzers users if it turns out to be a "special" list (i.e. a list that does not allow a trailing comma). There's [a rule](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1413.md) for that.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #2098](https://github.com/dotnet/csharplang/issues/2098) via [**ZenHub**](https://www.zenhub.com/)
