### ISSUE TITLE
Refactoring: Add parameter if an identifier doesn't exist

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#31970]
Current options:

<img src="https://user-images.githubusercontent.com/3105979/50313611-3079d200-04c1-11e9-8f2f-27e813c88df8.png" alt="image" width="500">

There should be another one to add `missingIdentifier` as a parameter on the method `Test`.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
