### ISSUE TITLE
'Generate GetHashCode' unnecessarily uses EqualityComparer for Nullable<>

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#31984]
Visual Studio 2019 Preview 1.1

There should be more consistency between `int` and `int?`. Actual:

```cs
private int a;
private int? b;

public override int GetHashCode()
{
    var hashCode = 2118541809;
    hashCode = hashCode * -1521134295 + a.GetHashCode();
    hashCode = hashCode * -1521134295 + EqualityComparer<int?>.Default.GetHashCode(b);
    return hashCode;
}
```

Expected:

```cs
var hashCode = 2118541809;
hashCode = hashCode * -1521134295 + a.GetHashCode();
hashCode = hashCode * -1521134295 + b.GetHashCode();
return hashCode;
```

`Nullable<>.GetHashCode` does not throw NullReferenceException because the struct overrides `Object.GetHashCode` and the overriding implementation has no null reference to operate on.

**Comment by jnm2** [comment]
Willin to PR. Looks like the logic is here:

https://github.com/dotnet/roslyn/blob/3bb73cf7f31cda72f057ae50ab6ce4b147efb115/src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateGetHashCodeMethod.cs#L182-L197

**Comment by CyrusNajmabadi** [comment]
@jnm2 Feel free to PR.  I would approve it as per the gitter discussion.

**Comment by CyrusNajmabadi** [comment]
> Nullable<>.GetHashCode cannot throw NullReferenceException because the struct overriddes Object.GetHashCode.

This is not the reason it can't throw NRE.  A struct can throw NRE inside its methods (and many structs do).  The reason it can't throw NRE here is because htat's how it was spec'ed: 

https://docs.microsoft.com/en-us/dotnet/api/system.nullable-1.gethashcode?view=netframework-4.7.2

> The hash code of the object returned by the Value property if the HasValue property is true, or zero if the HasValue property is false.

**Comment by jnm2** [comment]
@CyrusNajmabadi The difference is where the NRE is thrown: at the line of the call site or on a line inside the method.

It can't throw/directly cause an NRE to *call* GetHashCode, even if GetHashCode decides to take it upon itself to throw NRE once you've called and transferred control to the inside of the method.

**Comment by CyrusNajmabadi** [comment]
> Updated to make the point I was trying to make: that Nullable<>.GetHashCode would have to go far out of its way to achieve an NRE in any circumstance.

FWIW, earlier designs and impls of Nullable behaved this way (and many people though it should behave that way).  After all, if it represents a null-value, it shoudl throw null.  Heck, that's how .Value behaves.  Other 'structs' also throw NullRef often if they represetn data that could be 'null-like'.  For example, ImmutableArray does this a lot.

That said, we're tangenting off the main point, which is that the IDE could certainly special-case Nullable. I'm 100% in support of that happening :)

**Comment by jnm2** [comment]
Would there be any problem expanding this to cover all struct types that can be proven to not box the value when calling GetHashCode? (I.e., all struct types that can be proven to override GetHashCode?)

**Comment by CyrusNajmabadi** [comment]
i see no problem with that.

**Comment by jnm2** [comment]
I'm not sure why I was thinking that boxing mattered. No matter what code you generate, it's either *never* going to box or *always* going to box when you call GetHashCode (when the runtime type does or doesn't override object.GetHashCode).

The actual emitted IL doesn't care whether the type available at compile-time type overrides GetHashCode:

```il
ldarg.0
ldflda {...}
constrained. !TBar
callvirt instance int32 [System.Private.CoreLib]System.Object::GetHashCode()
```

Since boxing IL can never be emitted for GetHashCode and the jitted code already only boxes when necessary, GetHashCode should be called directly on all value types.
