### ISSUE TITLE
Implementing IEquatable<T> offers a "Make uppercase" code fix

### ISSUE THREAD

**Issue by Vannevelj** [dotnet/roslyn#3199]
I forked the repo, started a new debugging session and implemented the following code:

    class Program : IEquatable<Program>
    {
        static void Main(string[] args)
        {
        }

        public bool Equals(Program other)
        {
            throw new NotImplementedException();
        }
    }

This shows a strange warning + code fix advising me to change `Program` to `PROGRAM`. At the same time, the diagnostic's information has default values: "DiagnosticId" for ID and "Message" for Description. The only thing that could be an indication is the Code Fix action which is named "Make uppercase" though I can't find this string anywhere in the solution.

![weirdmakeuppercaseerror](https://cloud.githubusercontent.com/assets/2777107/7900010/209c48aa-073f-11e5-9673-af971e80088e.png)

**Comment by sharwell** [comment]
:laughing: I can't wait to see where this goes.

**Comment by Vannevelj** [comment]
Well, this is embarrassing. Apparently the VS instance that's started when debugging, has extensions that aren't shown in the extension list of the working VS instance. I completely forgot that this is the default example for an analyzer project.

**Comment by sharwell** [comment]
And here I was hoping for an RC "Easter Egg". :smile:

**Comment by mattwar** [comment]
That would be the code fix that offers to convert your identifiers into Hungarian notation.

**Comment by ljw1004** [comment]
And you thought that "ALL-UPPERCASE" menus in VS2013 were over by now. Oh no. They were just the beginning :)
