### ISSUE TITLE
Allow ref structs to return fields by reference

### ISSUE THREAD

**Issue by tmds** [dotnet/roslyn#31992]
**Steps to Reproduce**:

```cs
    ref struct A
    {
        private int i;
        public ref int Int => ref i;
    }
```

generates a compilation error:
```
error CS8170: Struct members cannot return 'this' or other instance members by reference
```

Maybe this can be allowed?

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #2107](https://github.com/dotnet/csharplang/issues/2107) via [**ZenHub**](https://www.zenhub.com/)
