### ISSUE TITLE
Code completion for Null conditional element access operator only works on simple name expressions

### ISSUE THREAD

**Issue by tenor** [dotnet/roslyn#32]
Open up VS 2015 CTP 5 and type:

String s = "g";
s?[    (At this point the parameter completion popup appears as it's supposed to)

Now try the following expressions:

new String() ?[ (Popup DOESN'T come up)
""?[ (Popup DOESN'T come up)
(" ")?[ (Popup DOESN'T come up)

**Comment by pdelvo** [comment]
It works for me

**Comment by tenor** [comment]
@pdelvo Not working for me in the latest CTP (in the static Main method of a C# console application). It didn't work in the previous VS 2015 Preview either.

**Comment by paulomorgado** [comment]
It's working for me too.

**Comment by Pilchie** [comment]
I'm able to repro this as well.  Note that @tenor is talking about the Signature Help tooltip not appearing when typing [.  The Completion List *does* appear when you type a letter inside the indexer.

**Comment by paulomorgado** [comment]
Oh, that! Now I see it too.
