### ISSUE TITLE
Proposal: Allow |= in object initializer syntax

### ISSUE THREAD

**Issue by emsaks** [dotnet/roslyn#32002]
It would be nice if you could use the `|=` operator within the object initializer syntax (i.e. `new myObj { Attributes |= myObjAttribute.SomeFlag }`).

This would enable adding a flag to existing flags set in the constructor.

[There's another proposal for extending the initializer syntax for event handlers [here](https://github.com/dotnet/roslyn/issues/5365).]

**Comment by YairHalberstadt** [comment]
I would suggest you move this request to dotnet/csharplang where language requests are taken

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #2108](https://github.com/dotnet/csharplang/issues/2108) via [**ZenHub**](https://www.zenhub.com/)
