### ISSUE TITLE
Is this GC behaviour behaving as intended?

### ISSUE THREAD

**Issue by taori** [dotnet/roslyn#32009]
I was trying to reproduce some odd behavior i was experiencing when i noticed this, which seems odd too.

I also found [this](https://github.com/dotnet/coreclr/issues/9674), but even if i leave the program running for a while the finalizer isn't called either.

**Steps to Reproduce**:

program.cs

```
using System;
using System.Threading.Tasks;

namespace AwaitBehaviorTest
{
	class Program
	{
		static async Task Main(string[] args)
		{
			Console.WriteLine($"Starting tests.");
			Task.Run(async () =>
			{
				await Task.Delay(1500);
				Console.WriteLine($"GC.");
				GC.Collect();

				await Task.Delay(3000);
				Console.WriteLine($"GC.");
				GC.Collect();

				await Task.Delay(3000);
				Console.WriteLine($"GC.");
				GC.Collect();
			});
			await Task.WhenAll(ReturnOfTaskWithAssignment(), AwaitedCall(), ReturnOfTaskWithoutAssignment());
			Console.WriteLine($"Waiting for input.");
			Console.ReadLine();
		}

		private static async Task AwaitedCall()
		{
			var holder = new Holder(nameof(AwaitedCall));
			await holder.SomeWork();
		}

		private static Task ReturnOfTaskWithAssignment()
		{
			var holder = new Holder(nameof(ReturnOfTaskWithAssignment));
			return holder.SomeWork();
		}

		private static Task ReturnOfTaskWithoutAssignment()
		{
			return new Holder(nameof(ReturnOfTaskWithoutAssignment)).SomeWork();
		}

		public class Holder
		{
			public string Name { get; }

			public Holder(string name)
			{
				Name = name;
			}

			~Holder()
			{
				Console.WriteLine($"holder {Name} disposed.");
			}

			public async Task SomeWork()
			{
				int i = 0;
				while (i++ < 3)
				{
					await Task.Delay(TimeSpan.FromSeconds(1));
					Console.WriteLine($"Work {i}");
				}
				Console.WriteLine($"Done.");
			}
		}
	}
}
```

csproj

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		
		<TargetFramework>net461</TargetFramework>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

</Project>

**Expected Behavior**:
I would expect 3 disposals here

**Actual Behavior**:
only 2 holder objects are disposed

**Comment by svick** [comment]
As far as I can tell, this happens due to a combination of expected behaviors.

The core of this is that when an `async` method completes, its continuations are run *synchronously*. So, when the last one of the three calls to `SomeMethod` completes, it synchronously completes the `WhenAll` `Task`, which will synchronously execute the following `Main` code, including the blocking `ReadLine()`. Since all of this is happening synchronously, that last `SomeMethod` is still on the stack, including its reference to `this`, which explains why it's not garbage collected, as long as the `ReadLine` is blocked.

I think this could be solved by the compiler: just before it completes the `async` `Task`, it could zero-out all fields of the async state machine. Though I'm not sure if that's actually worth doing.

**Comment by taori** [comment]
@svick Very interesting. Getting rid of Console.ReadLine and replacing it with asynchronous waiting code indeed fixed the last holder to being disposed.

That is super interesting though. i was always under the impression that it did not matter at all if there was an async present or not and that everything a task runs will always be asynchronous work as long as you don't use Wait/Result/etc.

This GC behavior happens if the code for the method is this as well:

	private static async Task ReturnOfTaskWithoutAssignment()
	{
		await (new Holder(nameof(ReturnOfTaskWithoutAssignment))).SomeWork();
	}

Do you reckon this might be worth a diagnostic? I assume the chances of this happening in production code are rather slim.

**Comment by svick** [comment]
> Do you reckon this might be worth a diagnostic?

I don't think so. Even if there was a reasonable way to detect this situation from the compiler (or an analyzer), it still won't matter most of the time. It will only matter if you rely on a finalizer (which you shouldn't do) or if the `async` method prevents a large amount of memory from being collected and the blocking lasts for a long time (which shouldn't happen very often).

**Comment by taori** [comment]
ok. sounds reasonable.
