### ISSUE TITLE
Wiki FAQ link broken

### ISSUE THREAD

**Issue by tsasioglu** [dotnet/roslyn#3201]
FAQ.md line 28 is broken around the "var". 

Should be "    \* \[How do I get type info for a variable in a declaration, with inferred ('var') or explicit variable type\]\(#how-do-i-get-type-info-for-a-variable-in-a-declaration-with-inferred-var-or-explicit-variable-type\)"

(Is there any approved workflow to contribute to the wiki (a la http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github/11481887#11481887)?)

**Comment by amcasey** [comment]
Fixed.  Thanks for the report!

(As your link points out, the wiki doesn't seem to be part of the repo - not sure why that is.)
