### ISSUE TITLE
Default Interface Method Base Calls

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#32054]
[The LDM decided](https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-11-14.md#default-interface-implementations) on the base invocation syntax `base(N.I1<T>).M(s)`.  We also decided that the syntax should be permitted in classes (e.g. to invoke an implementation from a skip-base class or a base interface).

This needs to be implemented in the compiler.  Also, we need to decide on an implementation strategy.  What IL would that generate?  Since interface implementations are currently private methods, it may require further CLR changes.

**Comment by gafter** [comment]
According to my notes, for a base call like

``` c#
base(Type).M();
```

where `Type` is an interface type,
1. The invocation needs to be unambiguous - there needs to be a unique *declaration* of `M` that is binds to.  That declaration would be in the type `Type` or some base interface of `Type`.
2. The compiler also needs to check that `Type` has a unique most specific override for the method selected by overload resolution.  In other words, the following must be an error

``` c#
interface A
{
    void M();
}
interface B : A
{
    override A.M() {}
}
interface C : A
{
    override A.M() {}
}
interface D : B, C
{
}
interface E : D
{
    override A.M()
    {
        base(D).M(); // error due to A.M not having a most specific override in D
    }
}
```

**Comment by AlekseyTs** [comment]
LDM (2019-04-29) decided to remove the base(Type) syntax from the scope of C# 8.0. This issue is tracking the work to put it back into the product once we have support from CLR.

**Comment by AlekseyTs** [comment]
Closing for now because we don't have concrete plan to add this feature in the next release.

**Comment by AndriySvyryd** [comment]
Related: https://github.com/dotnet/csharplang/issues/2337
