### ISSUE TITLE
"Rename" refactoring should consistently be the first item in IDE ctrl+dot box

### ISSUE THREAD

**Issue by tristanlabelle** [dotnet/roslyn#32058]
**Version Used**: VS 2017 15.9.4

**Steps to Reproduce**:

1. Create a new C# project
2. Type this code `public readonly struct Foo { public int X { get; } }`
3. Place the caret after "Foo" and type "bar"
4. Press ctrl+dot and immediately press enter

**Expected Behavior**: The rename refactoring is invoked. 
**Actual Behavior**: The "override equals on value types" refactoring is invoked.

This is annoying because it is unpredictable. Making the struct non-public or removing its field makes it such that the rename refactoring is the default suggestion again, and this doesn't happen with other types of symbols (enums, classes, variables, etc.). Moreover, when the file is big enough, the equal operator overrides are added to the end of the struct declaration, out of sight, and it looks like the rename just silently failed.

![image](https://user-images.githubusercontent.com/2314287/50540726-eab9ab00-0b4b-11e9-9110-17c2ce391c16.png)

**Comment by CyrusNajmabadi** [comment]
@MrTrillian It looks like you may have a third party analyzer installed.  Roslyn has no code-fix with that name.  So it would be up to that analyzer to order things properly here using the Roslyn exported name for the Rename fixer.

**Comment by CyrusNajmabadi** [comment]
@jinujoseph This does not appear to be a Roslyn issue, but rather a 3rd party analyzer not behaving appropriately.

---

@TheFanatr Did you see this with another code-fix? (i.e not "override equals and ...")  If so, you'd need to open another bug on that.

**Comment by Neme12** [comment]
@CyrusNajmabadi Is it even possible to make a refactoring have higher priority than an analyzer though?

**Comment by CyrusNajmabadi** [comment]
@Neme12 Rename is implemented as an analyzer/code-fix-provider pair.  It's not implemented as a 'refactoring'.  Cheers!

**Comment by MrTrillian** [comment]
@CyrusNajmabadi I'm surprised that would be the case. This is a new empty project and everything that appears in the visual studio extensions list are required components (I can't uninstall them without removing major language dev features). Plus the error that shows up first is documented on MSDN: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1815-override-equals-and-operator-equals-on-value-types

**Comment by jinujoseph** [comment]
cc @mavasani 

@MrTrillian  are you running Fxcop analyzers [link](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/)/ enabled code analyzers  by any change ?

**Comment by CyrusNajmabadi** [comment]
> We do not currently have any way to enforce a deterministic ordering for code fixes coming from different packages - here it is FxCop analyzers package (likely coming from Microsoft Code Analysis VSIX installed by you

I don't believe that's the case.  The Analyzer package could put the right `[Order(After =...` attribute on its code fixer. 

> The correct fix here you should likely come from code fix engine somehow treating IDE code fixes specially and always ordering them above any third party code fix.

I actually don't think the IDE should be special here.

Though, one thing we can do is consider 'rename' to be 'high priority' (wheras everything is 'normal' by default).  The downside here is that if there is something out there currently depending on having high-pri to order above 'Rename' that will now no longer work.

**Comment by mavasani** [comment]
> Though, one thing we can do is consider 'rename' to be 'high priority' (wheras everything is 'normal' by default). The downside here is that if there is something out there currently depending on having high-pri to order above 'Rename' that will now no longer work.

Yes, I think the only good short term solution here is to specialize this case in the code fix engine - knowledge of built-in IDE code fixes should not be required in third party packages.

**Comment by mavasani** [comment]
Also note that rename tracking analyzer/fixer is not even a true diagnostic analyzer/fixer:
1. It's working depends on the current state of the text buffer and the last known text edits, see http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/RenameTracking/RenameTrackingDiagnosticAnalyzer.cs,31.
2. It will never run in CI, even after we NuGetize all IDE analyzers.

This indicates it is very similar to the _add usings for pasted code_ feature that was implemented by @JoeRobich recently. Joey, was it implemented as a diagnostic/code fix? If not, it might be worth even doing the right fix here and switch renaming tracking to be written the same way as that feature, but that might be lot more work.

**Comment by mavasani** [comment]
Tagging @heejaechang as well

**Comment by CyrusNajmabadi** [comment]
> Yes, I think the only good short term solution here is to specialize this case in the code fix engine - knowledge of built-in IDE code fixes should not be required in third party packages.

I guess my major issue is this:I don't see why the IDE analyzers should be considered special.  We've taken a grab-bag of feature we think are useful and have made analyzers for them.  It may be the case that other fixes *should* be higher priority.

That said, 'rename' is one of the most important and hyper-focused fixes available.  There is something to be said about the 'stateful/tracking'-type fixes that indicates they should always be highest priority. 

So, a proper 'fix' for this might be to desginate a certain category for that type of fix and just put Rename/Add-Using-On-Paste into it.

**Comment by sharwell** [comment]
This situation should be addressed by ongoing work to improve our ability to organize suggestions in lists containing both code fixes and refactorings. @mavasani can provide additional information about the status of this work.

**Comment by CyrusNajmabadi** [comment]
Closing out.  rename is prioritized at the top of hte list.
