### ISSUE TITLE
Throw Exception in method call not recognized for nullable ref-type check (CS0165)

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/roslyn#32065]
The following code example results in CS0165
Error	CS0165	Use of unassigned local variable 'key
If I throw directly in the code below the error is not shown.

**Version Used**: 
VS 2019 Preview 1.1
.NET SDK Version: 3.0.100-preview-009844
**Steps to Reproduce**:
1. Create project and set:
```xml
    <LangVersion>8.0</LangVersion>
    <NullableReferenceTypes>true</NullableReferenceTypes>
```
2. Copy following source code into the project:
```csharp
namespace ConsoleApp8
{
    public class Test<T>
    {
        public void DoStuff(ReadOnlySpan<byte> input)
        {
            string key;
            Dictionary<string, bool> dictionary = new Dictionary<string, bool>();
            if(typeof(T) == typeof(byte))
            {
                key = Encoding.UTF8.GetString(input);
            }
            else if(typeof(T) == typeof(char))
            {
                key = Encoding.Unicode.GetString(input);
            }
            else
            {
                ThrowNotSupportedException();
                //  throw new NotSupportedException();
            }
            dictionary[key] = true;
        }

        private static void ThrowNotSupportedException()
        {
            throw new NotSupportedException();
        }
    }
}
```
3. Look at the errors.

**Expected Behavior**:
No error
**Actual Behavior**:
Error CS0165

If you uncomment the throw in the else branch it works.

**Comment by gafter** [comment]
This is by design.  According to the language specification, the body of a called method has no influence on the analysis of the body of the calling method.

**Comment by Tornhoof** [comment]
@gafter Ok, I admit I didn't know that. Does that apply to attributes too, e.g. a  ``[NeverReturnsAttribute]``, similar to that ``[PureAttribute]``?
Or an annotation like ``Debug.Assert(key != null)`` after the call to the Throw method? (This one currently does not work, ``key`` is not assigned)

That trick to put the exception throwing into a method is kinda widespread by now, I think it started due to some issues with the inlining analysis?
