### ISSUE TITLE
If you write Else after an Exit "iterator" Intellisense shown ElseIf

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32076]
<p>If you write Else after an Exit &lt;iterator&gt; Intellisense shown ElseIf<br><br>If you have a &quot;loop&quot; (For, Do, etc.) and have an If ... End If condition wich includes an Ext &quot;loop&quot; if you try to wrtite an Else clause, Intellisense shows only ElseIf (see attached capture).<br>If the IF/End If don't have an Exit clause shows both Else and ElseIf as expected.<br><br>It happens in Visual Studio 2019 Preview 1.1 (16.0.0) and also in Visual Studio 2017 15.9.4<br><br>I'm using Visual Basic. With C# there is no problem only shows else :-)<br><br>For example:<br><br>For i = 1 To 10<br>    Dim j = 3<br>    If j&gt;2 Then<br>        Exit For<br><br>        ' If you write Else, Intellisense only shows ElseIf<br><br>    End If<br>Next</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/413645/if-you-write-else-after-an-exit-intellisense-shown.html
VSTS ticketId: 755189_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to change these vb experiences.
