### ISSUE TITLE
Crash "Visual Studio" at rename variable in code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32086]
<p>If the code contains a line with an error, and you are trying to rename the variable, the development environment crashes and Visual Studio restarts.

Visual Studio Verion 15.9.3 
Simple code: (Console app, Visual Basic)

```
Module Module1

    Sub Main()

        ' Try renaming the variable "val". (Right Click -> Rename...)
        Dim val As Integer = 10

        ' Line code with error
        For (Int() i = 0; i <val; i++)

    End Sub

End Module
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/394687/crash-visual-studio-at-rename-variable-in-code.html
VSTS ticketId: 736894_
_These are the original issue comments:_

Fiona Niu[MSFT] on 11/29/2018, 06:20 PM (32 days ago): <p>Thank you for your feedback. In order for us to investigate this further, could you please give us a dump file so that we can conduct further research? </p><p> </p><p> 1. Please follow the instructions below, especially &quot;Provide a trace and heap dump&quot; section to record the issue you are experiencing.</p><p> 2.  https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017 </p><p> 3. The recorded files can be found under %TEMP%\Microsoft\VSFeedbackCollector.</p><p> 4. Upload the files to this ticket by choosing insert file tag on add comment field then submit.</p><p> </p><p>We look forward to hearing from you!</p>

Тютрюмов Максим on 11/29/2018, 08:42 PM (32 days ago): <p>Sent a record. Is that what you wanted?</p><p>Memory_8252_1543552764291.dmp 669 100 Kb (O_O). This is madness.</p>

Fiona Niu[MSFT] on 11/29/2018, 11:32 PM (32 days ago): <p>Thank you for providing the information. We are forwarding the issue to the engineering team for investigating. The engineer will investigate the issue and keep you posted. </p>
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
stack 

Сообщение: System.InvalidCastException: Не удалось привести тип объекта "Microsoft.CodeAnalysis.VisualBasic.Syntax.ParenthesizedExpressionSyntax" к типу "Microsoft.CodeAnalysis.VisualBasic.Syntax.IdentifierNameSyntax".

   в Microsoft.CodeAnalysis.VisualBasic.Rename.LocalConflictVisitor.VisitForOrForEachBlock(ForOrForEachBlockSyntax node)

   в Microsoft.CodeAnalysis.VisualBasic.Rename.LocalConflictVisitor.VisitForBlock(ForBlockSyntax node)
