### ISSUE TITLE
C# code format for linq should with an indent

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32082]
1. Create a new C# project, and type code just in the Main function:

```
var s = (from c in "test" select c).Distinct();
```

2-A. Press Enter before `select`, the code format will be:

```
var s = (from c in "test"
         select c).Distinct();
```

`select` will align to `from`, not good.
What about the new format:

```
var s = (from c in "test"
    select c).Distinct();
```

2-B. OR, Insert Enter before “.” will be:

```
var s = (from c in "test"select c)
.Distinct();
```

&quot;.&quot; will align to &quot;var&quot;, not good.
What about the new format:

```
var s = (from c in "test" select c)
    .Distinct();
```

2-C. OR, Insert Enter before “select” will be:

```
var s = (from c in "the"
select c).Distinct();
```

&quot;.&quot; will align to &quot;var&quot;, not good.
What about the new format:

```
var s = (from c in "test"
    select c).Distinct();
```

In a word, any new line in one code line block should always with an indent.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/409183/c-code-format-for-linq-should-with-an-indent.html
VSTS ticketId: 752329_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
2-A: This is the by-design behavior of the formatter. Multi-line LINQ queries are always vertically aligned.

2-B: This is a bug. The formatter is supposed to be using the proposed form already.

2-C: I don't understand how this case is different from 2-A. It's possible the formatting of the example was messed up by the bug reporting tool. Can you verify that the examples now have the form you expected?

**Comment by miaodadao** [comment]
2-A:
```
var s = (from c in "test"
         select c).Distinct();
tab1tab2@----
```
In this case, "select" will aligned to "from". If you use tab for indent, one space will be added before "select", when multi-line linq, too many spaces appear.
What about indent for 4 space or 1 tab always?

**Comment by justinmchase** [comment]
#### `.editorconfig`
```
indent_size = 2
indent_style = space
```

## expected

#### `<enter>` before `.`
```cs
var s = (from c in "test" select c)
  .Distinct();
```

#### `<enter>` after `(`, before `)`
```cs
var s = (
  from c in "test" select c).Distinct();
```
```cs
var s = (
  from c in "test" select c
).Distinct();
```
