### ISSUE TITLE
Consider adding complete statement support for additional statement kinds

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#32095]
- [ ] What about a local-function with an expression body?
- [ ] What about goto-default?
- [ ] What about 'break/continue'?
- [ ] What about 'yield'?
- [ ] What about using-directives?
- [ ] What about a delegate-decl?
- [ ] What about a property with an expression-body (or any member with an expression body)?

_Originally posted by @CyrusNajmabadi in https://github.com/dotnet/roslyn/pull/30743#discussion_r242672376_

**Comment by CyrusNajmabadi** [comment]
Closing out.  We can drive these as bug fixes as necessary.
