### ISSUE TITLE
Style preferences to include `this.` don't work in ctor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32093]
A constructor calling its base class' constructor can't use `this.`, but auto-formatting applies the chage.

```csharp
public class Base{
  public string Name{get;}
  public Base(string name){...}
}

public class Child: Base{  
  public Child():
     base(AppContext.GetValueFor(nameof(this.Name)){
}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/415902/style-preferences-to-include-this-dont-work-in-cto.html
VSTS ticketId: 757067_
_These are the original issue comments:_

Jinu Joseph [MSFT] on 1/1/2019, 05:31 PM (17 hours ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
Here's a simple reproducer for this issue:

**.editorconfig**

```
root = true

[*.cs]
dotnet_style_qualification_for_property = true:suggestion
```

**Source file**

```csharp
public class Base
{
    public string Name { get; }
    public Base(string name) { }
}

public class Child : Base
{
    public Child()
        : base(nameof(Name))
    {
    }
}
```

**Comment by sharwell** [comment]
We have a group of tests here that are supposed to catch `nameof` cases like this. The new test could be added after the tests already in this group:

https://github.com/dotnet/roslyn/blob/317e9f191e1f49633e8d73d63474d5d68a3f9658/src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs#L1287-L1375

**Comment by sharwell** [comment]
### Reserved Issue

This issue is reserved for the next three days to give [Kyle White](https://twitter.com/kgrwhite86/status/1103321395487039489) the opportunity to let us know if he's interested in working on it. If there is no response by 10 March 2019, it will be moved back to up-for-grabs.

**Comment by kgrwhite** [comment]
Hi Sam, Thanks for the advice. I'll gladly look into the issue and update accordingly.

**Comment by NRKirby** [comment]
I'd like to pick this up unless Kyle already has?

**Comment by sharwell** [comment]
@kgrwhite did you get a chance to look at things? If you're in the middle of working on this or still interested, I want to make sure you have time to figure things out. Please let me know if you have any questions.

@NRKirby based on his previous reply, it sounds like Kyle was interested in taking a look at this. Since it can take some time for a new contributor to get set up for making a change like this, I want to make sure we don't rush things.

**Comment by kgrwhite** [comment]
@sharwell i'm in the middle of working this issue at the moment. Should hopefully have an update soon :-)

**Comment by kgrwhite** [comment]
@sharwell I'm happy to hand over this issue to other contributors. 
It would help me study how this was fixed for further issues while familiarising myself with the codebase.
