### ISSUE TITLE
Extra ':' added when typing named argument

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#32096]
16.0 build 28501:

In a compiler unit test, say `LocalFunctionTests.RefReturningAsyncLocalFunction`, enter:
```
    CreateCompilation(source, parseOptions:
```

Result:
<img width="401" alt="extracharacter" src="https://user-images.githubusercontent.com/10732005/50606209-d17d6b00-0e79-11e9-9c0e-bc92a3bb8668.png">

**Comment by jasonmalinowski** [comment]
Was new completion enabled by chance here?

**Comment by jinujoseph** [comment]
It should not be enabled , @ivanbasov  can you verify this
