### ISSUE TITLE
Add parameter quick fix does not support multiple parameters

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#32098]
**Version Used**: VisualStudio.16.Preview/16.0.0-pre.1.1+28408.50

**Steps to Reproduce**:

```C#
static void Main()
{
    Test(true, true, true);
}

static void Test() { }
```
1. Invoke 'Add Parameter to Program.Test()'

**Expected Behavior**:
```C#
static void Test(bool v, bool v1, bool v2);
```

**Actual Behavior**:
Quick fix does not result in compilable code as it needs to be invoked for all parameters individually.
```
static void Test(bool v);
```

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
