### ISSUE TITLE
C# extensibility and metaprogramming experiment

### ISSUE THREAD

**Issue by knat** [dotnet/roslyn#3209]
Hi, I'd like to show my efforts in this area.
Metah.W(MW) is a C#-derived metaprogramming language for Windows Workflow Foundation 4.5. It provides an alternative way of composing activities to the WF designer.
Screenshots:
![preview](https://cloud.githubusercontent.com/assets/10220052/7905195/9e6a0346-0846-11e5-9fd0-39af87317164.png)
![preview2](https://cloud.githubusercontent.com/assets/10220052/7911207/e3e9830a-088d-11e5-9e3f-7ae4ee64a0ea.png)
Please visit https://github.com/knat/Metah for more info.
I'd love to hear your comments.

**Comment by dsaf** [comment]
It looks like a very impressive effort, but the project's GitHub home page is enormous. I am personally not going to read it all despite my love of metaprogramming and workflows/actor model. Do you want to post a short syntax-specific technical description here? It would be great to describe how it  applies to Roslyn, as I doubt there will be many people interested in WWF here.

PS: if there was a *simple* way for me to *easily* add custom language-level keywords and operators the way you do and still get the full power of IDE via Roslyn/ReSharper - that would be so awesome. I could imagine e.g. Akka.NET code could look like the killed C#-Axum code in the end.

**Comment by knat** [comment]
I think there are two ways of extending C# syantx and implementing metaprogramming:
1. Modify the Roslyn source code. Pros: product quality. Cons: (very) hard for those who are not in Redmond, because it will take hundreds (maybe thousands) hours to fully understand the Roslyn source code.
2. Use ANTLR to implement an almost complete C# parser, so you can extend C# syntax easily. Then use roslyn as a [binary component](http://www.nuget.org/packages/Microsoft.CodeAnalysis) to analyze the semantics and generate code. That is, ANTLR for the complier front-end, Roslyn for the compiler back-end. Pros: ease(at least for me). Cons: just for language prototypes.
So, I implemented [the MW parser](https://github.com/knat/Metah/blob/master/Source/Metah.Compilation/AntlrParsing/W.g3) using ANTLR3, [created the Roslyn syantx tree from the ANTLR parsing tree](https://github.com/knat/Metah/blob/master/Source/Metah.Compilation/Base.cs#L19), [created the MW syantx tree from the ANTLR parsing tree](https://github.com/knat/Metah/blob/master/Source/Metah.Compilation/W/W.cs), translated the MW syntax tree to the Roslyn syntax tree, created the Roslyn `CSharpCompilation` from the final syntax tree and checked the semantical errors(e.g. `delay 123` is a semantical error), finally, generated the result C# code :)

**Comment by dsaf** [comment]
That is quite impressive, but if I was still using WWF I would prefer an internal DSL instead. Yes, it would mean losing expressivity and fitting a new paradigm into a general-purpose language, but transport language (C#) familiarity and deep IDE support are hard to beat.

My experience in a similar situation:

1) Implemented an external DSL based on XML transport - bad idea, but I am a fan of XAML - gone now.

2) Briefly contemplated ANTLR - too involved, IDE support for new language will be missing, making Visual Studio add-ins is not easy.

3) Settled on an internal DSL.

Now I am waiting for project Nitra to be finished. It's JetBrains' bet against the Roslyn and Monaco threats:

http://blog.jetbrains.com/blog/2013/11/12/an-introduction-to-nitra
http://blog.jetbrains.com/blog/2014/05/27/nitra-goes-open-source
https://confluence.jetbrains.com/display/Nitra/Home 
https://github.com/JetBrains/Nitra

**Comment by dsaf** [comment]
Hopefully C# 8 gets some metaprogramming features #2136.

**Comment by paulomorgado** [comment]
If an activity is method-like, it should have an explicit return type, like iterator and asynchronous methods.

**Comment by knat** [comment]
```C#
activity A1<T>(int Arg1, ref T Arg2) as IEnumerable<T> where T : class, new() //returns IEnumerable<T>
{
    //...
}
activity A2() //returns void
{
    //...
}

//
//another syntax design:
//
activity IEnumerable<T> A1<T>(int Arg1, ref T Arg2) where T : class, new()
{
    //...
}
activity void A2()
{
    //...
}
```
It's just a prototype. :smile:

**Comment by paulomorgado** [comment]
What I was saying is that, if iterators return `IEnumerable<T>` or `IEnumerator<T>` and async methods return `Task` or `Task<T>`, those activities should return some `Activity<T>`.

**Comment by knat** [comment]
MW is a metaprogramming language. The following C# code is generated from activity `A1<T>` and `A2`:
```C#
//some.mw.cs, generated by the MW compiler
class A1<T> : global::System.Activities.Activity<IEnumerable<T>> where T : class, new()
{
    public global::System.Activities.InArgument<int> Arg1 { get; set; }
    public global::System.Activities.InOutArgument<T> Arg2 { get; set; }
    //...
}
class A2 : global::System.Activities.Activity
{
    //...
}
```

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
