### ISSUE TITLE
Baselining new rules (aka. grandfathering in debt) on a large repo is quite difficult

### ISSUE THREAD

**Issue by bichuga** [dotnet/roslyn#32102]
**Version Used**: 
2.9

**Steps to Reproduce**:
With the goal of bringing Roslyn Analyzers as a build-breaking code hygiene tool to your large, many-sln codebase....

1. Wire up Roslyn to run a default set of analyzers as part of every project. This will likely require .targets changes and build.props edits.
2. Run a build. As expected, the build is broken in potentially thousands of places.
3. Grandfather in all existing debt.

**Expected Behavior**:
Feature exists to baseline the entire repo.

**Actual Behavior**:
No such feature exists. 

Since the feature does not yet exist, we built a custom [ScopeIdentifier analyzer](https://o365exchange.visualstudio.com/O365%20Core/_git/bothell?path=%2Fsources%2Fdev%2FAnalyzers%2Fsrc%2FRoslyn%2FScopeIdentifier%2FScopeIdentifier.cs&version=GBmaster) which generates all of the missing information needed to be able to crunch a Roslyn SARIF file into a LocalSuppressions.cs. We include this scopeidentifier like a normal analyzer `<Analyzer Include="…ScopeIdentifier.dll" />` and drop an `<errorlog>foo.Sarif</errorlog>` during a build. From there we have a [Roslyn suppressor tool](https://o365exchange.visualstudio.com/O365%20Core/_git/bothell?path=%2Fsources%2Fdev%2FTools%2Fsrc%2FRoslynSuppression&version=GBmaster) combine these two files into LocalSuppressions.cs.

**Comment by bichuga** [comment]
Suggestions: 

1. Output the missing scope and target information into the SARIF file. 
2. Build a feature by which Roslyn will generate the suppressions file and update the csproj to include this file. The functionality already exists in VS to do essentially this (via right click -> suppress all in suppressions file). We need this functionality to be available natively in msbuild.

**Comment by mavasani** [comment]
Extracted out (1) to https://github.com/dotnet/roslyn/issues/42489

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
