### ISSUE TITLE
Wrong region indenting in switch block

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32104]
This code gets wrongly indented:

switch (...)
{
    case ...

    #region Name

    case ...:
        break;

    #endregion Name
}

The endregion line is indented one level too far to the right. This is reproducible by simple selecting  such code, cutting and pasting it back.

Reported at https://developercommunity.visualstudio.com/content/problem/328622/wrong-region-indenting-in-switch-block.html

**Comment by CyrusNajmabadi** [comment]
Tagging @heejaechang

**Comment by ygoe** [comment]
I reported this through VS feedback.

**Comment by jinujoseph** [comment]
also reported [here](https://developercommunity.visualstudio.com/content/problem/495607/endregion-misaligned-in-switch-statement.html)

**Comment by CyrusNajmabadi** [comment]
closing out due to lack of feedback.
