### ISSUE TITLE
Error list sometimes doesn't clear on solution close

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#32121]
Observed in some recent integration test runs.

⚠️ The following workaround should be removed when this issue is fixed:

https://github.com/dotnet/roslyn/blob/f4e99378935b880202d49e3a75ca99cbd8f498c3/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/ErrorList_InProc.cs#L106-L112

**Comment by sharwell** [comment]
This is likely caused by #32036, but I'm leaving this issue open since the above workaround still needs to be removed before this can be closed.

**Comment by jasonmalinowski** [comment]
I'll send out the deletion of this _after_ the fix for #32036 is merged; if there's something deeper going on I don't want that fix being blocked up on this.

I agree that this is likely the cause.
