### ISSUE TITLE
Expand complete statement tests to include formatting and completion variations

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#32126]
Follow-up issue for #30743 
 
Complete statement tests should include permutations of the following features enabled/disabled
1. formatting
2. brace completion
3. normal completion
4. "complete statement" (this feature).

As requested by @CyrusNajmabadi  https://github.com/dotnet/roslyn/pull/30743#discussion_r231997757

**Comment by tmat** [comment]
Removing "Test-Scenario". This is rather a missing unit test, not an end-to-end scenario.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
