### ISSUE TITLE
Remove node fails in Visual Basic.

### ISSUE THREAD

**Issue by petterek** [dotnet/roslyn#3213]
Fails while generating preview. 
 
    <ExportCodeRefactoringProvider(LanguageNames.VisualBasic, Name:=NameOf(MoveClassToFileCodeRefactoringProvider)), [Shared]>
    Friend Class MoveClassToFileCodeRefactoringProvider
    Inherits CodeRefactoringProvider

    Public NotOverridable Overrides Async Function ComputeRefactoringsAsync(context As CodeRefactoringContext) As Task
        ' TODO: Replace the following code with your own analysis, generating a CodeAction for each refactoring to offer

        Dim root = Await context.Document.GetSyntaxRootAsync(context.CancellationToken).ConfigureAwait(False)

        ' Find the node at the selection.
        Dim node = root.FindNode(context.Span)

        ' Only offer a refactoring if the selected node is a type statement node.
        Dim typeDecl = TryCast(node, ClassStatementSyntax)
        If typeDecl Is Nothing Then
            Return
        End If

        Dim a2 = CodeAction.Create("Delete class", Function(c) MoveClassToFile(context.Document, typeDecl, c))

        ' Register this code action.
        context.RegisterRefactoring(a2)

    End Function

    Private Async Function MoveClassToFile(document As Document, typeDecl As ClassStatementSyntax, cancellationToken As CancellationToken) As Task(Of Document)

        Dim currentSyntaxTree = document.GetSyntaxTreeAsync().Result
        Dim currentRoot = currentSyntaxTree.GetRootAsync().Result
        Dim replacedRoot = currentRoot.RemoveNode(typeDecl, SyntaxRemoveOptions.KeepNoTrivia)

        Dim ret = document.WithSyntaxRoot(replacedRoot)

        Return ret
    End Function

    End Class

Tested in c# by altering the Language to CSharp and the ClassStatementSyntax to ClassDeclarationSyntax, it's working fine :(

**Comment by mattwar** [comment]
VB is trickier to get right since there are both xxxStatementSyntax nodes and xxxBlockSyntax nodes. You cannot remove a xxxStatementSyntax node if it's part of a xxxBlockSyntax, you have to remove the xxxBlockSyntax node instead.

**Comment by mattwar** [comment]
You will need to remove the ClassBlockSyntax node.

**Comment by petterek** [comment]
OK.. I will try it out

**Comment by petterek** [comment]
That worked  :+1: Thank you very much
