### ISSUE TITLE
Visual Basic editor election is off

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32130]
When I copy text from an edited line and then Control+Click another word and paste, the word is not replaced correctly.

Instead it replaces the selection shifted. This seems to occur when the source line will be formatted once the caret leaves the line, selecting the same amount of text in the new location.

I noticed this started about one or two updates ago and I was hoping it would be fixed. It's really annoying so I'm reporting it now.

![visualbasicbug](https://user-images.githubusercontent.com/12449387/50657122-5b950480-0f4a-11e9-91a2-fb8a844c77e3.gif)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/408239/visual-basic-editor-election-is-off.html
VSTS ticketId: 751139_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
