### ISSUE TITLE
Refactor: Extract Local Function

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32135]
<p><strong>Given</strong></p><pre>public void Add()
{
    var radius = 1.23;

    var area = 3.14 * radius * radius
}</pre><p><strong>When<br></strong></p><p>&quot;Quick Actions and Refactorings&quot; menu is opened and &quot;Extract Local Function&quot; is selected<br><strong></strong></p><p><strong>Then<br></strong></p><pre>public void Add()
{
    var radius = 1.23;
    NewLocalFunction();

    void NewLocalFunction()
    {
        var area = 3.14 * radius * radius;
    }
}</pre>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/360438/refactor-extract-local-function.html
VSTS ticketId: 707648_
_These are the original issue comments:_

Fiona Niu[MSFT] on 10/17/2018, 07:11 PM (77 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>
Kendra Havens [MSFT] on 10/31/2018, 00:53 PM (64 days ago): <p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

Kendra Havens [MSFT] on 1/3/2019, 00:35 PM (58 min ago): <p>To clarify, is this request specifically for providing an option for the extracted method to be local as opposed to the current <a target="_blank">extract method refactoring</a>? Would you prefer both options to appear in the Quick Actions drop down all the time or only in a specific context? I appreciate any details that help explain your preferred experience.</p>

Lopez Marc Rainier on 1/3/2019, 00:51 PM (42 min ago): <p>The request is specifically for providing an additional option for the extracted method to be local in addition to the current extract method refactoring. Both options appearing in the Quick Actions if the code to extract is inside a regular method and not already in a local function is my preferred experience.</p>

**Comment by 333fred** [comment]
@jinujoseph do we have any plans to enable this in the near future? I find myself wishing for this every few days.

**Comment by jinujoseph** [comment]
@333fred , hopefully soon 
![image](https://user-images.githubusercontent.com/12449387/62647541-a2dedb80-b905-11e9-8477-0a779efc04e2.png)
