### ISSUE TITLE
Navigate to has an error when open two solutions one by one

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#32132]
**Affected Branch:** d16.0stg 
**Affected Build:** 28419.233
**Steps to reproduce:**
1. Open a new and then open a solution1
2. Close solution1 and open a solution2
3. Search "Main" in navigate to box

**Expect:** Only one result

**Actual:** There are two results, including solution1 result

![image](https://user-images.githubusercontent.com/1408396/50656931-7cfdec80-0f5a-11e9-848b-980dc7461aad.png)

Note: This issue worked well on early d16.0stg[28417.116]

**Comment by sharwell** [comment]
Probable duplicate of #32036

**Comment by jasonmalinowski** [comment]
Yep, this is a dupe.
