### ISSUE TITLE
The ability to collapse a #region at #regionend

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32146]
<p>Just so you don't have to scroll up to look for the start of the region, a minus box at #endregion would be nice.</p><p>I suppose that would extend to brackets as well, but I haven't run into that need.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/411260/the-ability-to-collapse-a-region-at-regionend.html
VSTS ticketId: 753515_
_These are the original issue comments:_

Jane Wu [MSFT] on 12/18/2018, 11:46 PM (15 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by Neme12** [comment]
I just discovered that this is already possible if you double click the vertical bar on the left:
![image](https://user-images.githubusercontent.com/11444821/51115184-c296a100-1807-11e9-8a8f-af8bf1fd0efe.png)

**Comment by sharwell** [comment]
This is controlled by the editor, not by Roslyn.

Also @Neme12 is correct. The feature is already available by double clicking the outlining margin to the left of `#endregion`. 😄
