### ISSUE TITLE
Breaking change: CTP3, please make CreateSubmission public again

### ISSUE THREAD

**Issue by mkosieradzki** [dotnet/roslyn#3214]
I have been using CTP2 version of Roslyn in following scenario:
1. I was parsing syntax tree as Interactive
2. Compiling and computing semantic model using CreateSubmission
3. Translating SyntaxTree (using computed SemanticModel) to System.Linq.Expressions. (Applying my own "symbol access restrictions" as a security layer, preventing all "imperative" constructs).

Great points about this:
1. System.Linq.Expressions is the only way I know to execute dynamic code inside in Universal Apps and .NET Core. All the Roslyn assemblies required to perform this process were also portable.
2. I was able to utilize incremental parsing and incremental handling of SourceText.

If possible:
1. Please make CSharpScript cross platform (afaik impossible or at least difficult) or
2. or please provide xplat wrapper for CreateSubmission allowing to process interactive expression and get proper SyntaxTree and then SemanticModel
3. or please give us back ;) CreateSubmission and parsing as interactive expression
4. or provide out of the box xplat CSharp to System.Linq.Expressions converter
5. or provide any other solution/guidance allowing to achieve my scenario

**Comment by tmat** [comment]
@mkosieradzki CreateSubmission is coming back. We have temporarily made it internal for VS2015 RTM as a part of public API surface cleanup - since the implementation is not finished we don't want to expose it as public API that can't be changed in future.

**Comment by mkosieradzki** [comment]
@tmat Phew! Thanks for your response! I was kinda scared, when I installed CTP3 today from Nightly build and core API I am depedning on has dissappeared ;). 

I assume that my scenario is supported and expression parsing as interactive (which currently throw NotSupportedException) is coming back as well - or any other way to deal with such a scenario.

I fully understand and agree with your point. CreateSubmission API is not as nice and flawless as other APIs in Roslyn) even it is extremely usefull and efficient. One could for example expect some high-level wrapper to the submissions array.

**Comment by tmat** [comment]
@mkosieradzki "parsing as interactive" is also coming back.

**Comment by glopesdev** [comment]
@mkosieradzki, @tmat it looks like **CreateSubmission** is public again on the last 1.1 pre-release. I'm trying to do exactly the same thing, parsing a top-level expression into a LINQ expression tree (btw, this looks like this a very recurrent scenario, would be great if it was trivial to solve in Roslyn).

Anyway, **GetSemanticModel** is throwing an **ArgumentException** for me in the following example:

```csharp
var script = @"1+1";
var tree = CSharpSyntaxTree.ParseText(script, new CSharpParseOptions(kind:SourceCodeKind.Interactive));
var root = (ExpressionSyntax)tree.GetRoot().DescendantNodes().OfType<ExpressionSyntax>().First();
var compilaton = CSharpCompilation.CreateSubmission("ScriptTest");
var semantics = compilaton.GetSemanticModel(tree, ignoreAccessibility:false);
var type = semantics.GetTypeInfo(root);
```

I've tried adding the syntax tree before calling **GetSemanticModel** or changing the *ignoreAccessibility* argument and it's still throwing with a cryptic message ***"Additional information: tree"***.

Is the semantic computation of interactive expression still not supported in the current pre-release?

**Comment by tmat** [comment]
@glopesdev The error message should indeed be better, could you share the stack trace? 

You need to create a compilation with the tree in it -- pass it as an argument to CreateSubmission. 

BTW, since you are not actually creating a chain of submissions you should be able to just create a regular compilation via ```CSharpCompilation.Create("ScriptTest", tree);```

**Comment by glopesdev** [comment]
@tmat If I pass the tree to ```CSharpCompilation.CreateSubmission``` it actually does not throw, but when I later call ```GetTypeInfo``` on the root it returns **ErrorType**. I'm using:

```csharp
var script = @"1+1";
var tree = CSharpSyntaxTree.ParseText(script, new CSharpParseOptions(kind:SourceCodeKind.Interactive));
var root = (ExpressionSyntax)tree.GetRoot().DescendantNodes().OfType<ExpressionSyntax>().First();
var compilation = CSharpCompilation.CreateSubmission("ScriptTest", tree);
var semantics = compilation.GetSemanticModel(tree, ignoreAccessibility: false);
var type = semantics.GetTypeInfo(root);
```

Is there anything I'm missing in order to correctly evaluate the expression?

Regarding the stack trace when the tree was not passed to ```CreateSubmission```, it's simply:

> Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(Microsoft.CodeAnalysis.SyntaxTree syntaxTree, bool ignoreAccessibility) + 0xc6 bytes	
> CodeAnalysisTest.exe!CodeAnalysisTest.Program.Main(string[] args) Line 59 + 0x10 bytes

I can't seem to obtain symbols for the pre-release package from SymbolSource. Are they hosted somewhere else?

**Comment by glopesdev** [comment]
@tmat Ok, got it to work! It turns out I was forgetting to pass the **mscorlib** metadata reference to the submission. The following snippet correctly evaluates to **System.Int32**:

```csharp
var script = @"1+1";
var corlib = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);
var tree = CSharpSyntaxTree.ParseText(script, new CSharpParseOptions(kind: SourceCodeKind.Interactive));
var compilation = CSharpCompilation.CreateSubmission("ScriptTest", tree, new[] { corlib });
var semantics = compilation.GetSemanticModel(tree, ignoreAccessibility: false);
var root = (ExpressionSyntax)semantics.SyntaxTree.GetRoot().DescendantNodes().OfType<ExpressionSyntax>().First();
var type = semantics.GetTypeInfo(root);
```

Is using ```typeof(object).Assembly.Location``` the best way to reference **mscorlib**? I didn't find an overload that would take an **Assembly** object directly.

**Comment by tmat** [comment]
@glopesdev Re reference to mscorlib - depends on what your tool is supposed to do. If you aim for runtime-only compilation and execution, then ```typeof(object).Assembly.Location``` is the way to go for now (until we add MetadataReference.CreateFromAssembly for this purpose). 

Otherwise you should use a reference assembly for the target platform.

**Comment by mkosieradzki** [comment]
@glopesdev for translations to LINQ expressions: typeof(object).Assembly.Location is the best solution IMO. For other compilation purposes you can look up reference assemblies in: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework they are grouped in many variants, for every possible .NET version :)
