### ISSUE TITLE
Nagivate up / down the inheritance chain

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32149]
<p>It's currently really inconvenient to navigate from interface to all implementations. Or from a method in implementation upwards to interface definition.</p><p>Prior art:</p><p>https://www.jetbrains.com/help/resharper/Navigation_and_Search__Go_to_Base.html</p><p>https://www.jetbrains.com/help/resharper/Navigation_and_Search__Go_to_Inheritor.html</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/411986/nagivate-up-down-the-inheritance-chain.html
VSTS ticketId: 754193_
_These are the original issue comments:_

Jane Wu [MSFT] on 12/18/2018, 11:48 PM (15 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by kendrahavens** [comment]
I believe this partially duplicates #20383, except this asks for Go to Inheritor rather than a way to navigate to all overrides.

**Comment by sharwell** [comment]
🔗 I would be interested in hearing how well my [Inheritance Margin](https://marketplace.visualstudio.com/items?itemName=SamHarwell.InheritanceMargin) extension addresses this request.

**Comment by CyrusNajmabadi** [comment]
I also wrote an inheritance margin.  But it was stripped out when i went to TypeScript.  @dpoeschl might know where the code for it ended up :(

**Comment by mikadumont** [comment]
If @dpoeschl knows where the code is we have icons approved by UX for this.

**Comment by mikadumont** [comment]
Proposal: 

Similar to @sharwell's [Inheritance Margin](https://marketplace.visualstudio.com/items?itemName=SamHarwell.InheritanceMargin) extension have inheritance icons in the margin of the Visual Studio text editor. Clicking on the icon helps you navigate to the following: 

1. Inheritors / Implemented  ![Implemented 15 9](https://user-images.githubusercontent.com/46729679/95367291-6f8d3900-0889-11eb-8fc3-e2cabb00cc15.png)
2. Implementing / go to base ![Implementing 15 9](https://user-images.githubusercontent.com/46729679/95367347-8469cc80-0889-11eb-9944-66c0af981745.png)
3. Inheritors / Implemented + Override  ![Overridden 15 9](https://user-images.githubusercontent.com/46729679/95367449-a2373180-0889-11eb-8122-8d2a474111b7.png)
4. Overriding / go to base but being overridden ![Overriding 15 9](https://user-images.githubusercontent.com/46729679/95367475-abc09980-0889-11eb-9873-dbedd34054ad.png)

![image](https://user-images.githubusercontent.com/46729679/95367572-c5fa7780-0889-11eb-88e4-6c04c63b423f.png)

**Comment by Cosifne** [comment]
Inheritance Margin is in 16.11 now. And it provides the user ability to move up/down the inheritance chain
