### ISSUE TITLE
"Wrap every parameter/unwrap and indent all paramaters" is higher than "create/initialize parameter"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#32151]
These new code fixes have been given a higher priority than "create/initialize parameter" which feels wrong because the former is something you probably do once, the latter I do all the time just after I've written a parameter:

![image](https://user-images.githubusercontent.com/1103906/50671149-3a084b80-1024-11e9-9200-7d769b4d05e5.png)

Can we change the priority of this?

**Comment by CyrusNajmabadi** [comment]
Agreed.  These may just need to go in the 'low priority' bucket.

**Comment by genlu** [comment]
It's not as simple as lowering the priority of the for formatting codefix. There's some simple logic to decide whether to show refactoring first or codefix first.

http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Wpf/Suggestions/SuggestedActionsSource.cs,183

**Comment by CyrusNajmabadi** [comment]
this is not a codefix though.  this is a refactoring.
