### ISSUE TITLE
Seems like the wiki page 'Building Testing and Debugging' needs a small correction

### ISSUE THREAD

**Issue by monoman** [dotnet/roslyn#3216]
Tried to follow the Getting the code instructions in https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging

I could not make RoslynLight.sln compile in the VS2015RC unless I first got into the command line and did:

    nuget restore Roslyn.sln

So

## Getting the code

1. Clone https://github.com/dotnet/roslyn
2. Open RoslynLight.sln

should be

## Getting the code

1. Clone https://github.com/dotnet/roslyn
2. In the command line inside the src folder do: nuget restore Roslyn.sln
3. Open RoslynLight.sln

**Comment by tmeschter** [comment]
This has been fixed.
