### ISSUE TITLE
Using Declarations should be a rude edit-and-continue edit

### ISSUE THREAD

**Issue by chsienki** [dotnet/roslyn#32168]
As per https://github.com/dotnet/roslyn/blob/6f83204ee88fd684a3a00565d4712476cb21802a/src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs#L135-L141

We should check that edit-and-continue works correctly with using declarations. Suspect it wont, and we should make using declarations a rude-edit.

**Comment by jcouv** [comment]
FYI I talked with Tomas about using declarations. I opened a tracking issue: https://github.com/dotnet/roslyn/issues/32589

**Comment by chsienki** [comment]
Implemented via #32589
