### ISSUE TITLE
Classifier for accessibility modifiers 

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/roslyn#32160]
As a follow-up to dotnet/roslyn#31231, it looks like one type of classifier was omitted -- one for visibility modifiers (public, internal, etc). Some people like to color those differently to call attention to them.

**Comment by sharwell** [comment]
Design review conclusion: while we are somewhat concerned that this could lead to a long tail of small feature requests that complicate an already long list of classifications in the Fonts and Colors editor, it seems like there may be space for a concrete proposal that covers two specific use cases:

1. Some users, including @onovotny, prefer code styles that omit redundant access modifiers. Highlighting these modifiers with a specific color calls attention to them which could make sense for these users.
2. In other situations, users are especially interested in highlighting *externally exposed* members, which should account not only for the access modifier itself but also the accessibility of any containing types.

The proposal should include descriptions of how each of the above users could expect to work with the new feature.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
