### ISSUE TITLE
Refactor SemicolonIsMissing and RequiredDelimiterIsMissing methods in Complete Statement

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#32163]
As asked for in https://github.com/dotnet/roslyn/pull/30743#discussion_r231757706 and https://github.com/dotnet/roslyn/pull/30743#discussion_r245098282 and https://github.com/dotnet/roslyn/pull/30743#discussion_r245082434

After all statement completion cases are addressed, refactor the SemicolonIsMissing and RequiredDelimiterIsMissing methods.

**Comment by CyrusNajmabadi** [comment]
Closign out.
