### ISSUE TITLE
Build correctness leg should prevent "PROTOTYPE" markers in master branch

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#32170]
FYI @jaredpar

**Comment by jaredpar** [comment]
Think it's a bit more complex because we don't always merge back into master. Example is we often merge back into dev16 style branches from time to time. Need to check this in any shipping branch.

**Comment by jcouv** [comment]
Maybe into branches that have empty nuget package monikers?

**Comment by jcouv** [comment]
I would think that a simple grep for `PROTOTYPE` would suffice. We should not just scan source files, but project and other files too (xml, txt, etc).
