### ISSUE TITLE
"Language features" wiki should also list once available then cut features

### ISSUE THREAD

**Issue by NickCraver** [dotnet/roslyn#3217]
The language features page, here: https://github.com/dotnet/roslyn/wiki/Languages-features-in-C%23-6-and-VB-14 lists all of the features currently on the table for C#6. What it doesn't mention are **removed** features for this release.

For example, I was just trying to use inline `out` parameters and despite reading up on C# 6 quite a bit, had no clue they were removed. I think what Microsoft is doing developing in the open is _awesome_. There is however a downside: Google rot even before release. While there are dozens to hundreds of blog posts saying how inline `out` parameters work (just like any other C#6 feature), I had to go to twitter and ask where to find why they weren't working/were removed.

I'm not debating their removal - if a feature is not ready then it's not ready. I do think once something is significantly publicized though, the canonical list of changes for a C#/VB release (currently that wiki page as far as I can tell) should include a section for removed items that were available then later removed.

**Comment by matijagrcic** [comment]
@NickCraver If it helps you can look at C# 7 Work List of Features https://github.com/dotnet/roslyn/issues/2136 where declaration expressions https://github.com/dotnet/roslyn/issues/254 are under Unbucketed section of the list. I agree that it would be more useful if features that were dropped from the table were marked as dropped and not removed.

**Comment by NickCraver** [comment]
@matijagrcic Thanks! That is a very helpful list that's not at all easy found via google. I'd add to this discussion that linking to the working set of features for the next version (or the final in another wiki I assume, once it's RTM) would be helpful on [the features wiki](https://github.com/dotnet/roslyn/wiki/Languages-features-in-C%23-6-and-VB-14) as well.

I am assuming here that all of these things are easy to find (or at least I hope) for those working on the core language daily, they're just not that discoverable from the outside. I'd love to see this improved in general - right now the amount of blog posts with outdated information are drowning out accurate, current information about all of the latest from the .Net teams at Microsoft. I think with the canonical sources established and improved, Google with naturally elevate them in search results and improve life for everyone (including Microsoft devs, which I see answering out-of-date questions in JabbR very, very often).

**Comment by dhusemann** [comment]
Announcement on Codeplex before the move to Github.  https://roslyn.codeplex.com/discussions/568820

**Comment by NickCraver** [comment]
@dhusemann oh I have found that *now*, my point is that it is extremely hard to find. It's really not far off from "read through the mailing list" in terms of discoverability. If there are canonical sources (e.g. the wikis, which are at the top level) - they should reflect such major changes. The hope is that a Google query for "C# 6 Features" (for which this Wiki is currently number 5 for me and for anonymous users) would eventually rank #1 (I think that will naturally happen with page rank) and land you here.

All of this content being on GitHub is fantastic. There's finally a canonical source of information which is surfaced much better than MSDN docs are for similar things (MSDN is generally bad at not-code *lists* of things, I assume somewhat due to localization concerns). This issue is proposing it can be improved further.

When weighing the value of such things, I only ask people do this: find a set of Google terms that tells me inline `out` params were removed, any query at all that's on the first few pages of Google results (or any similar exercise - C# changing while in public development is the point)...then judge if that's at all intuitive.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
