### ISSUE TITLE
Syntax Highlighting gets messed up when using string interpolation in a url.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32205]
Syntax Highlighting gets messed up when using string interpolation in a url.

Example:
var someVariable = &quot;hello&quot;;
var url =$&quot;https://www.google.com/{someVariable.Replace(&quot;hello&quot;, &quot;world&quot;)}&quot;;

![image](https://user-images.githubusercontent.com/12449387/50734394-5c4cb700-1153-11e9-9cae-01457872a6a6.png)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/135605/syntax-highlighting-gets-messed-up-when-using-stri.html
VSTS ticketId: 512911_
_These are the original issue comments:_

Rick Harker on 1/5/2019, 10:48 PM (2 hours ago): This bug still happens as of Visual Studio 2017 15.9.4.The entire hyperlink is visible as a continuous blue link, reguardless of the interpolations.Can we get this fixed, please?
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is not a roslyn issue.  This is an editor feature that attempts to find urls in strings.  You can enable/disable that here: 

![image](https://user-images.githubusercontent.com/4564579/50746122-6e296b00-11e2-11e9-8228-234c19cca0cd.png)

@olegtk Do you know who this would go to?

**Comment by jinujoseph** [comment]
Moved the DC Issue to your area path. closing this one
