### ISSUE TITLE
Disable CS8170 and CS8157 ("escaping this") for `ref struct` types

### ISSUE THREAD

**Issue by glenn-slayden** [dotnet/roslyn#32203]
As I understand it, the point of `ref struct` is essentially to publish limitations on the value-type's use that redound as a guarantee that its `this` pointer is in some way fixed, typically in an upper stack frame, or perhaps unmanaged memory, but never boxed or otherwise GC heap-bound.

If this is the correct, then it seems like there's significantly less danger, if any, to allowing the escape of `this`  from a value-type's instance methods (and isn't doing so the whole point anyway?) when it is marked as a `ref struct`. As such, the following errors should be either demoted to warnings or not emitted at all from within instance methods of `ref struct` types.

<code>error CS8170: Struct members cannot return 'this' or other instance members by reference</code>

<code>error CS8157: Cannot return 'x' by reference because it was initialized to a value that cannot be returned by reference</code>

The problem with these (and perhaps others of their ilk), is that they are prone to false-positives. There are numerous cases where special knowledge that the compiler can't see or infer in fact ensures that the escaping `this` is previously, ultimately, or in some other way correctly contained.

Furthermore, owing to the use limitations, `ref struct` can really only be deployed in pretty advanced situations requiring experts, and these types of developers are likely to have less need or desire for the aggressive static analysis of **CS8170** / **CS8157**, as they currently stand.

**Comment by gafter** [comment]
The language specification currently requires an error for these situations. You are requesting a language change. Such as request exists in the csharplang repository at https://github.com/dotnet/csharplang/issues/2107.
