### ISSUE TITLE
Auto generated ref assemblies does not include xml documentations.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/roslyn#32215]
**Version Used**: 

latest with .NET Core 3 and Visual Studio 2017 15.9.4 Preview 1.

**Steps to Reproduce**:

1. Create a package and setup reference assemblies similar to how it is done for https://github.com/AraHaan/XmlAbstraction/
2. build and package
3. Install it with a new project then try to use the package’s classes, and the members of the classes.

**Expected Behavior**:
For Visual Studio, Rider or any other ide to display xml documentation according from the metadata of the reference assemblies.

**Actual Behavior**:
No xml documentation is added to the metadata and no xml documentation file for the reference assembly is generated either.

cc: @jcouv

**Comment by jaredpar** [comment]
@AraHaan why do you feel this is a bug in reference assemblies? The compiler doesn't control the pack process here. Is there something specific you feel like the compiler isn't doing here that it isn't?

**Comment by jcouv** [comment]
Tagging @gafter 

Ref assemblies are currently defined narrowly as assemblies that you can substitute to real assemblies without affecting a compilation. See [original definition](https://github.com/dotnet/roslyn/issues/2184) of the feature.

By that definition, the current behavior is by-design, since the compiler does need to load xml documentation.

**Comment by AraHaan** [comment]
I just was wanting to be able to see my xml documentations from my nuget packages that provides reference assemblies like linked above on the configuration so that way new users or I can see them like I can see the .net core and the .net framework xml documentations in the ide. I guess I have to manually package xml documentation files in the ref folders too on my *.csproj files.

You can check the XmlAbstraction package (when generatated locally from the tip of the current master branch) on a new visual studio project if you like to verify that in fact the documentation disappears vs. the version on nuget.org (v1.2.1).

**Comment by nguerrera** [comment]
Looks like the reference assemblies are being forced into the package here:

https://github.com/AraHaan/XmlAbstraction/blob/7a27bf52fa27a8425d7b462885ca85b644f3f65e/src/XmlAbstraction/src/XmlAbstraction.csproj#L35-L37

Why is this being done?

**Comment by AraHaan** [comment]
I thought they was supposed to be forced in.

**Comment by jaredpar** [comment]
@AraHaan 

> I thought they was supposed to be forced in to use them in places like the ide only or whatever.

The only thing you should need to do is set ProduceReferenceAssembly to true.

``` xml
<ProduceReferenceAssembly>true</ProduceReferenceAssembly>
```

Everything else will be enabled once that is set.

**Comment by jcouv** [comment]
I'll go ahead and close the issue since the question was answered. Please re-open if that's not the case.
