### ISSUE TITLE
StaticKeywordRecommender doesn't give a stable answer between usings in script

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#32214]
This test fails with `absent: true` and `absent: false`. The reason is that `CSharpSyntaxContext.IsGlobalStatementContext` changes after one character is typed.

```C#
        [Fact, Trait(Traits.Feature, Traits.Features.KeywordRecommending)]
        public async Task TestNotBetweenUsings()
        {
            var source = @"using Goo;
$$
using Bar;";

            await VerifyWorkerAsync(source, absent: true, Options.Script);
        }
```

Relates to (but precedes) https://github.com/dotnet/roslyn/pull/32187

**Comment by CyrusNajmabadi** [comment]
Closing out.  Scripting is not a scenario we are investing in.
