### ISSUE TITLE
"Remove unused parameter" doesn't recognize serialization constructors

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#32227]
**Version Used**: 
Version 16.0.0 Preview 3.0 [28507.140.d16.0stg]

**Steps to Reproduce**:

``` VB
        Private NotInheritable Class PropertyPageSerializationStore
            Implements ISerializable

            Private Sub New(Info As SerializationInfo, Context As StreamingContext)
                _serializedState = DirectCast(Info.GetValue(KEY_STATE, GetType(ArrayList)), ArrayList)
            End Sub
        End Class
```

**Expected Behavior**:
No warning

**Actual Behavior**:
Severity	Code	Description	Project	File	Line	Category	Suppression State
Message	IDE0060	Remove unused parameter 'Context'	Microsoft.VisualStudio.AppDesigner	E:\project-system2\src\Microsoft.VisualStudio.AppDesigner\PropPageDesigner\PropertyPageSerializationService_Store.vb	127	Style	Active

**Comment by CyrusNajmabadi** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/32133 ?

**Comment by davkean** [comment]
Yep.
