### ISSUE TITLE
CSharpAddMissingReferenceCodeFixProvider encountered an error and has been disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32231]
Trying to use a .NET Standard 2.0 library in a .NET 4.6.2 ASP.NET web site. Getting a compiler error that says:  &quot;The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.&quot;

I went to the line of code with the error and attempted the suggested fix of &quot;Add reference to 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'&quot;. When attempting the fix, a yellow bar appears on top that says &quot;CSharpAddMissingReferenceCodeFixProvider encountered an error and has been disabled.&quot;

Stack Trace:
System.AggregateException : One or more errors occurred. ---&gt; Unable to cast COM object of type 'System.__ComObject' to interface type 'VSLangProj.VSProject'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{2CFB826F-F6BF-480D-A546-95A0381CC411}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.&lt;&gt;c__DisplayClass18_0.&lt;InvokeCore&gt;b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---&gt; (Inner Exception #0) System.InvalidCastException : Unable to cast COM object of type 'System.__ComObject' to interface type 'VSLangProj.VSProject'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{2CFB826F-F6BF-480D-A546-95A0381CC411}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryAddReferenceToProject(ProjectId projectId,String assemblyName)
   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioAddMetadataReferenceCodeActionOperationFactoryWorkspaceService.AddMetadataReferenceOperation.Apply(Workspace workspace,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeActionOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(&lt;Unknown Parameters&gt;)&lt;---

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/335717/csharpaddmissingreferencecodefixprovider-encounter.html
VSTS ticketId: 684188_
_These are the original issue comments:_

Adam Humpherys on 10/25/2018, 01:28 PM (74 days ago): Trying to add a .NET Standard 2.0 NuGet package to a .NET 4.7 ASP WebForms project and it tells me to reference netstandard. Attempting to have Visual Studio do this for me fails with:'CSharpAddMissingReferenceCodeFixProvider' encountered an error and has been disabled.And clicking Show Stack Trace provides the following output:System.AggregateException : One or more errors occurred. ---> Unable to cast COM object of type 'System.__ComObject' to interface type 'VSLangProj.VSProject'. This operation failed because the QueryInterface call on the COM component for the interface with IID '\{2CFB826F-F6BF-480D-A546-95A0381CC411}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.b__0()   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)---> (Inner Exception #0) System.InvalidCastException : Unable to cast COM object of type 'System.__ComObject' to interface type 'VSLangProj.VSProject'. This operation failed because the QueryInterface call on the COM component for the interface with IID '\{2CFB826F-F6BF-480D-A546-95A0381CC411}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryAddReferenceToProject(ProjectId projectId,String assemblyName)   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioAddMetadataReferenceCodeActionOperationFactoryWorkspaceService.AddMetadataReferenceOperation.Apply(Workspace workspace,CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.CodeActions.CodeActionOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync()<---Only manually adding  to the web.config fixes this issue.
_These are the original issue solutions:_

Adam Humpherys solved on 10/25/2018, 01:31 PM (74 days ago), 0 votes: 
<p>A workaround for an ASP.NET project is to manually add this to your web.config at system.web/compilation/assemblies:</p>
<pre>&lt;add assembly=&quot;netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&quot;/&gt;</pre>
<p>Which I presume CSharpAddMissingReferenceCodeFixProvider is attempting to do when it encounters an error.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out.  I don't see prism hits here.
