### ISSUE TITLE
Predefined type 'System.Object' is not defined or imported

### ISSUE THREAD

**Issue by wangchaoyu1992** [dotnet/roslyn#32232]
**Version Used**: 

**Steps to Reproduce**:

1. MSBuild Upgrade to the15.7.9
2. Parse the project with Roslyn
3. Predefined type 'System.Object' or 'System.*'is not defined or imported
4.[mycode](https://github.com/wangchaoyu1992/First/blob/master/444.jpg)
I test project is https://github.com/sschmid/Entitas-CSharp
**Expected Behavior**:

**Actual Behavior**:
I've installed .net framwork 4.6 but
Unable to find .net framwork
If you can
Can you tell me how I can find .net framwork
Thanks.

**Comment by wangchaoyu1992** [comment]
I'm doing static code analysis and use rosly parsing source code

**Comment by wangchaoyu1992** [comment]
How can you avoid this problem。
My project is in a hurry to release。
thank you very match

**Comment by jmarolf** [comment]
@wangchaoyu1992

> Predefined type 'System.Object' or 'System.*'is not defined or imported

Where is this message coming from? 
Does the project you are analyzing build without errors on your machine?
Does your code target .NET Core or .NET Framework?

> I'm doing static code analysis and use rosly parsing source code

You shouldn't need to have any references to parse.  Again, can you paster the full error you are seeing as well as steps to reproduce it?

**Comment by sharwell** [comment]
@jmarolf Based on the screenshot, it looks like this is an `MSBuildWorkspace` question. The additional information you requested would still be very helpful.

**Comment by jmarolf** [comment]
> it looks like this could be an MSBuildWorkspace question.

@sharwell 	Good point @wangchaoyu1992 	what messages do you see if you register an event on `WorkspaceFailed` before calling `OpenSolutionAsync`?
```C#
// Print message for WorkspaceFailed event to help diagnosing project load failures.
workspace.WorkspaceFailed += (o, e) => Console.WriteLine(e.Diagnostic.Message);
```

Do any project fail to load?

**Comment by wangchaoyu1992** [comment]
> @ wangchaoyu1992
> 
> > 未定义或导入预定义类型“System.Object”或“System。*”
> 
> 这条消息来自哪里？
> 您正在分析的项目是否在您的计算机上无错误地构建？
> 您的代码是针对.NET Core还是.NET Framework？
> 
> > 我正在进行静态代码分析并使用rosly解析源代码
> 
> 您不需要任何引用解析。再一次，你能看到你看到的完整错误以及重现错误的步骤吗？
[Gets the compiler error code](https://github.com/wangchaoyu1992/First/blob/master/5555.jpg)
my code target .NET Framework
this is my [code](https://github.com/wangchaoyu1992/First/blob/master/11.cs)
Remark :
My error is after the packaging run error, debug run not error.
The debug environment is installed with VS2017.
The packaged environment runs without VS2017.
所以我判断是打包环境缺少组件,但是不知道是什么组件
打包环境安装MSBuild 15 and .NET Framework 4.*

**Comment by wangchaoyu1992** [comment]
> > 看起来这可能是一个MSBuildWorkspace问题。
> 
> @sharwell 好点@ wangchaoyu1992 如果你`WorkspaceFailed`在打电话之前注册了一个事件，你会看到什么消息`OpenSolutionAsync`？
> 
> ```cs
> //打印WorkspaceFailed事件的消息，以帮助诊断项目加载失败。
> 工作区。WorkspaceFailed  + =（ o， e） =>  控制台。WriteLine（例如， Diagnostic。消息）;
> ```
> 
> 任何项目都无法加载？
My MSBuild15 is an offline package downloaded by command
vs_buildtools. exe - layout E: \ MSBuildTools - add Microsoft VisualStudio. Workload. MSBuildTools - lang en - US
e.Diagnostic.Message is:
@"Msbuild failed when processing the file
 'D:\source_code\Entitas-CSharp-master\Addons\Entitas.Blueprints\Entitas.Blueprints.csproj' 
 with message: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets: (1657, 5): 
 The ""GetReferenceNearestTargetFrameworkTask"" task was not found. 
 Check the following: 
 1.) The name of the task in the project file is the same as the name of the task class. 
 2.) The task class is ""public"" and implements the Microsoft.Build.Framework.ITask interface. 
 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the ""C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"" directory."

**Comment by jmarolf** [comment]
@wangchaoyu1992 	I see, your MSBuild install is invalid then.  I don't know what package that is but it doesn't contain the necessary targets to build your project.  If MSBuild is unable to load your project then MSBuildWorkspace will fail.

You can
1. Install MSBuild and the necessary targets to build your project
2. If your don't actually need the semantic information use `CSharpSyntaxTree.ParseText` method from [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/CSharpSyntaxTree.cs,363).

**Comment by wangchaoyu1992** [comment]
> @ wangchaoyu1992 我看，你的MSBuild安装无效。我不知道它是什么包，但它不包含构建项目的必要目标。如果MSBuild无法加载您的项目，则MSBuildWorkspace将失败。
> 
> 您可以
> 
> 1. 安装MSBuild以及构建项目所需的目标
> 2. 如果您实际上不需要语义信息，请使用[此处的](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/CSharpSyntaxTree.cs,363)`CSharpSyntaxTree.ParseText`方法。[](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/CSharpSyntaxTree.cs,363)

Thank you very match.
I installed the Microsoft.VisualStudio.Workload.NetCoreBuildTools to solve the problem。
May I ask you another question？
"Microsoft.Net.4.6.1.FullRedist.NonThreshold" and "Microsoft.Net.4.6.1.FullRedist.Threshold" what is the difference?
I need to install a.net Framework but don't know which one to install

**Comment by jmarolf** [comment]
"Threshold" refers to one of the first code names for Windows 10.  `Microsoft.Net.4.6.1.FullRedist.NonThreshold` is for operations systems like windows 8. `Microsoft.Net.4.6.1.FullRedist.Threshold` is for Windows 10 and newer operating systems.
