### ISSUE TITLE
[Dev16]Error "Changes are not allowed while code is running" shows while ENC about VB framework app

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#32247]
There are some VSO bugs / Feedback requests. Here are some of them: https://developercommunity.visualstudio.com/content/problem/410323/vs-2019-preview-11-cannot-edit-code-in-break-mode.html
https://developercommunity.visualstudio.com/content/problem/415406/edit-and-continue-is-not-working.html

**[Machine]**

OS: Windows-10-Enterprise-RS4

Product: VS Enterprise ENU d16.0stg 28405.127
 

Steps to reproduce:

1. Create a VB Console app(.Net Framework) and add code as following:
```
Sub Main()
For index = 1 To 10
Console.WriteLine("hello")
Next
End Sub
```
2. Set a BP at line which contains string "Console.WriteLine("hello")" 
3. F5
4. Press "Enter" key on the end of the line while it hit BP

**[Expected]**
It could modify code successfully.

**[Actual]**
It cannot ENC(see Capture.PNG).

Microsoft Visual Studio
Changes are not allowed while code is running.
OK   
![image](https://user-images.githubusercontent.com/5455484/50856161-c1b0cb80-133e-11e9-9ff3-b36a370aeca8.png)

 [Investigate]

1. The issue cannot repro on VB core console app.

**Comment by ivanbasov** [comment]
Here is another item that was scheduled to preview 3: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/740863

**Comment by raisinc** [comment]
I notice the settings to "Enable Edit amd Continue" in the Tools/Options/Debugging/General settings are ticked but not enmabled (grey color). In spite of it indoicating that I can "Edit and continue" after breaking in my code while debugging, I too get this message saying Changes are not allowed.
Is this a bug, or is there some other setting I have missed?

**Comment by yzermans** [comment]
Same issue as raisinc listed previously. This should be a high priority item if it is not already. There is no sense testing the 2019 update if this feature is not working. There is to much time lost when debugging large applications.

**Comment by camainc** [comment]
I'm not getting the error message, I'm just not able to make any changes in debug mode. If I do, I'm forced to stop and restart the application.

AspNetCore.App (2.2.0) 
AspNetCore.Razor.Design (2.2.0)
VisualStudio.Web.CodeGeneration.Design (2.2.0)

**Comment by drk-mtr** [comment]
Was this fix VB specific? I still have the issue with an F# Fabulous UWP app...

**Comment by koohsaran** [comment]
I have this problem too.so what is the fix? no answer? no responsibility? no support?
