### ISSUE TITLE
can't run restore.cmd

### ISSUE THREAD

**Issue by emilefokkema** [dotnet/roslyn#32241]
Can someone help? I apologize in advance if I'm missing something very obvious.

**Version Used**: latest `master`. I have powershell 3.0

**Steps to Reproduce**:

1. run `restore.cmd`

**Expected Behavior**: no error

**Actual Behavior**:
I get an error saying
```
Method invocation failed because [System.Version] doesn't contain a method named 'new'.
```

**Comment by jmarolf** [comment]
@emilefokkema 	which version of windows are you using?

**Comment by emilefokkema** [comment]
@jmarolf Windows 7 Enterprise

**Comment by jmarolf** [comment]
@emilefokkema 	thanks can you also include the full error message including the stack trace?

**Comment by emilefokkema** [comment]
@jmarolf strangely, there is no stack trace. On one line it says `Roslyn.sln:` and on another is the error message I mentioned. That's all.

**Comment by emilefokkema** [comment]
@jmarolf Might this line be the problem here?
https://github.com/dotnet/roslyn/blob/master/eng/common/tools.ps1#L184

**Comment by sharwell** [comment]
@emilefokkema Yes, that syntax requires PowerShell 5.0.

**Comment by sharwell** [comment]
@jaredpar @tmat Can we make **build.ps1** fail if the user does not have PowerShell 5.0 or newer?

**Comment by jmarolf** [comment]
Just a quick note that we should update out contribution guidelines [here](https://github.com/dotnet/roslyn/blob/e8f03e407226a43c122ce004c66e1795883f564b/docs/contributing/Building%2C%20Debugging%2C%20and%20Testing%20on%20Windows.md#developing-with-visual-studio-2017)

They state that powershell 3.0 is the minimum version required

**Comment by emilefokkema** [comment]
@jmarolf @sharwell Thank you both!

**Comment by NRKirby** [comment]
I've updated the docs in PR #33848. 

I saw this comment

> @jaredpar @tmat Can we make **build.ps1** fail if the user does not have PowerShell 5.0 or newer?

Is this something you want implemented? If so, can I attempt it and submit a PR?

**Comment by tmat** [comment]
> Is this something you want implemented? If so, can I attempt it and submit a PR?

Go for it.

**Comment by NRKirby** [comment]
@tmat  I've added a check in [build.ps1](https://github.com/dotnet/roslyn/blob/master/eng/build.ps1) in [this commit](https://github.com/dotnet/roslyn/pull/33848/commits/947698d6b1bbe9b6597dd9421303968af6c7360e#diff-891b50b7d5fe7380fc246ed310019d61R17). 

Please let me know if you want the check on a different line

**Comment by NRKirby** [comment]
Can this be closed now @tmat? 

#33848 Got merged earlier this week
