### ISSUE TITLE
[c# 7.3] cannot pass this with in? Seems like you should

### ISSUE THREAD

**Issue by Thraka** [dotnet/roslyn#32251]
**Version Used**: 7.3

**Steps to Reproduce**:

1. Use the code below

```csharp
class A
{
    public string Name;
    public void MapObjectB(in B obj) { }
}

class B
{
    public string Name;
    public void DoWorkWithA(A obj) => obj.MapObjectB(in this);
}

class Program
{
    void Main()
    {
        var a = new A();
        var b = new B();
        a.Name = "Bob";
        b.DoWorkWithA(a);
    }
}
```

**Expected Behavior**:

I could use `in this` as `this` is passed with `in`, it is read-only and not assignable.

**Actual Behavior**:

Error that you cannot pass `this` by `ref`

**Comment by gafter** [comment]
The compiler is correct.  `this` is a value, not a variable.  Nevertheless, this is a reasonable feature request so I'm moving it to `csharplang`.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #2129](https://github.com/dotnet/csharplang/issues/2129) via [**ZenHub**](https://www.zenhub.com/)
