### ISSUE TITLE
[Wiki] Mistake in markdown file 

### ISSUE THREAD

**Issue by InRedikaWB** [dotnet/roslyn#32254]
On page https://github.com/dotnet/roslyn/wiki/Labels-used-for-issues#general mistake in markdown. 

Above the "General" header:
- **Expected**: `## Areas`
- **Actual**: `##Areas`

![image](https://user-images.githubusercontent.com/22368203/50863702-9a92e200-13b0-11e9-8e4d-caa39dfdeebd.png)

**Comment by sharwell** [comment]
Thanks!
