### ISSUE TITLE
use NoProjection option once it becomes public API

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#32253]
related to this PR
https://github.com/dotnet/roslyn/pull/32248

we should use
http://index/?query=NoProjection&rightProject=Microsoft.VisualStudio.Text.Internal&file=TextLogic%5CTagAggregatorOptions2.cs&line=59

in here
https://github.com/dotnet/roslyn/blob/9cb17ff35bd69a8e4f0bfcbe6ea87e14b5807024/src/VisualStudio/Core/Def/Implementation/Venus/ContainedLanguage.cs#L149

to make sure we don't create tagger not directly related to our buffer.

we expect the option to be public in preview 3. so we should consume the option once it becomes public.

**Comment by CyrusNajmabadi** [comment]
Closing out.
