### ISSUE TITLE
Nullable array type improperly accepted in array creation

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#32258]
As pointed out in https://github.com/dotnet/roslyn/issues/31991#issuecomment-451384616:

> Another case where this is incorrectly accepted:
> ```cs
> #nullable enable
> public class C {
>     public void M() {
>     	_ = new C?(); // error 
>         _ = new string[50]?; // no error (incorrect)
>         _ = new string[50]?[,]; // no error (incorrect)
>     }
> }
> ```
> Looks like the same issue.

See also https://github.com/dotnet/roslyn/issues/32243 which shows that this is a breaking change.

**Comment by alrz** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/32169

**Comment by gafter** [comment]
Duplicate of #32169
