### ISSUE TITLE
EnC: support async-iterator methods

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#32266]
I noticed that there is some EnC for handling iterator and async methods, so there will likely be some handling for async-iterator methods too.

FYI @tmat @ivanbasov @jinujoseph 
Let me know what you think in terms of scheduling. If this could be looked at in preview3, then I don't need to block this scenario.
Thanks

Async-streams umbrella: https://github.com/dotnet/roslyn/issues/24037

**Comment by jcouv** [comment]
Here's the design document for async-iterator methods, `await foreach` and `await using` statements:
https://github.com/dotnet/roslyn/blob/master/docs/features/async-streams.md
It includes code snippets for the lowered form of different constructs.

I also have a draft article with more details: https://github.com/jcouv/roslyn/blob/blog-post/async-iterator.md

From discussion with @tmat, a few C# 8 features seem relatively straightforward:
- async-iterators: when we build the sequence of awaits, to make sure that it is not changed, we should also include `yield return` and `yield break`, as well as new `await` constructs (`await foreach`, `await using` statement and declaration). Users are prevented from editing those.
- `await foreach`: very much like a `foreach`. We need to confirm whether it adds any locals. Users are prevented from editing the declaration part of the `await foreach` once it is entered.
- `await using` statement: very much like a `using`. We need to confirm whether it adds any locals. Users are prevented from editing the declaration part of the `await foreach` once it is entered.

The one that seems more trouble is the `using` declaration and `await using` declaration. I filed a separate issue for those (https://github.com/dotnet/roslyn/issues/32589).

**Comment by tmat** [comment]
This is now implemented.
