### ISSUE TITLE
[perf] SyntaxListBuilder + SyntaxListBuilder.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#3226]
# SyntaxListBuilder + SyntaxListBuilder

Say we want to add the contents of one [SyntaxListBuilder](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Syntax/SyntaxListBuilder.vb) to other. 
We have to iterate through a each item, add it to target. eg
```vb
Dim n = more.Count
For i = 0 To n - 1
  tList.Add(more(i))
Next
```
[Source](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Scanner/Scanner.vb#L792)
This runs the risk of resizing multiple times. 

There should be away of doing a bulk add (`AddRange`) which potentially does a singe resize.
Ok so let's say that we implement the following overload.
```vb
        Public Sub Add(builder As SyntaxListBuilder)
            Me._builder.AddRange(builder.ToList)
        End Sub
```
It works true, but it involve the creation of a second list of nodes only to discard it afterwards.

So is there a more efficient way of doing a bulk add?

**Comment by gafter** [comment]
This is an internal API. External users of Roslyn should not be using internal APIs.

If you have a particular example of source code for which the compiler performs poorly, please report that as a performance issue.
