### ISSUE TITLE
Permit a trailing comma inside a switch expression

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#32292]
Per LDM 2019-01-09 we have accepted the proposal in https://github.com/dotnet/csharplang/issues/2098 to allow a trailing comma inside a switch expression
``` c#
_ = e switch
    {
        1 => 2,
        3 => 4, // comma now allowed here
    }
```
Similarly, we have accepted a proposal to allow a trailing comma inside a property subpattern.
``` c#
_ = e is T
    {
        X: 2,
        Y: 3, // comma now allowed here
    };
```
This needs to be implemented.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by alrz** [comment]
what about property patterns?

**Comment by gafter** [comment]
https://en.wikipedia.org/wiki/Whataboutism ;)

**Comment by gafter** [comment]
@alrz Yes, inside property patterns too (approved yesterday).

**Comment by CyrusNajmabadi** [comment]
Awesome!
