### ISSUE TITLE
Allow pattern-based disposal in `foreach`

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#32317]
It seems that `foreach` only every binds disposal via the interface, and never via pattern-based approach.
I expect that `foreach` would bind pattern-based `Dispose()` methods on ref struct enumerators, at least.

Note: in that scenario, the compiler should not produce `enumerator as IDisposable` logic.

Note: there is a similar issue with pattern-based disposal in `await foreach`, except that we likely need to lift the ref struct restriction there. (see https://github.com/dotnet/roslyn/issues/32316)

Update (1/16): from [LDM today](https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-01-16.md#pattern-based-disposal-in-await-foreach), we've decided that extension methods will not contribute to pattern-based disposal, even if we decide they contribute for binding pattern-based `GetEnumerator()` in a `foreach`.

Tagging @agocke 

----

Per [notes](https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-12-12.md#when-we-start-recognizing-pattern-dispose-do-we-call-it-in-foreach) (emphasis mine):

### When we start recognizing pattern Dispose, do we call it in foreach?

__Certainly__, it seems very important for the feature. Since a ref struct
cannot implement interfaces, pattern Dispose is the only way to implement
disposal.

There are a number of possible breaking changes:

1. A pattern enumerable type did not implement IDisposable, but had a
   Dispose method. This method would now be call.
2. If there are two Dispose extension methods, that will now produce
   an ambiguity and thus a compilation error.

**Conclusion**

Let's narrow the pattern-based Dispose change down to ref structs only.
This means every other type will be required to implement IDisposable.

----
Umbrella for enhanced-using feature: https://github.com/dotnet/roslyn/issues/28588

**Comment by chsienki** [comment]
This is implemented and working
