### ISSUE TITLE
Assert in CSharpSymbolMatcher.MatchSymbols.TryFindAnonymousType

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#3233]
%mymachine%\dumps\AnonType20150601.dmp
%mymachine%\dumps\AnonType20150601.zip

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication139
{
    class Program
    {
        static void Main(string[] args)
        {
            var result =
                from a in args
                let x = a.Reverse()
                let y = x.Reverse()
                where x.SequenceEqual(y)
                select new { Value = a, Length = a.Length };
            var first = result.First();
            args = args.Concat(from r in result select r.Value.ToString()).ToArray();
            result.ToString();
        }
    }
}
```

1. Do a bunch of stuff.
1. Run to ```result.ToString()```.
1. Change ```a.Length``` to ```a.Length + 1```.
1. Set next statement to ```var result = ...``` (might actually happen before previous step)
1. Step.

**Comment by amcasey** [comment]
Also, it looks like if you stop on ```var first = ...``` and change ```Length = a.Length``` to ```a.Length + 1```, result is nulled out and you get a null-ref exception when you step again.

**Comment by amcasey** [comment]
Confirmed: run to ```var first``` and then add ```+ 1``` to the length.  Stepping results in ```ArgumentNullException``` and ```result``` is null in the Locals window.

**Comment by tmat** [comment]
The root cause is the same as #3168. The problem occurs in pretty common query scenario, so moving #3168 to RTM.

**Comment by tmat** [comment]
@amcasey verify please

**Comment by amcasey** [comment]
Verified as part of the next iteration of the original buddy test.
