### ISSUE TITLE
c# 8 null checking in lambdas

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32356]
It seems null-elimination of class members is not working in lambdas

In the attached code you will see that when the member &quot;Parameters&quot; is used outside the lambda, the compiler understands it cannot be null. When it's captured in the lambda it doesn't. 

Either there's something about ref values in closures I'm not getting, or there's no good reason this happens.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/414633/c-8-null-checking-in-lambdas.html
VSTS ticketId: 756306_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by agocke** [comment]
The repro code is essentially:

```C#
class C
{
      string? _field;
      void M()
      {
           if (_field == null) throw new NullReferenceException();
           Action a => () => Console.WriteLine(_field.Substring(0)); // access to _field gives nullable warning
      }
}
```
