### ISSUE TITLE
Suspicious logic in ```LocalDataFlowPass<TLocalState>.GetOrCreateSlot``` method

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#32357]
```
        protected int GetOrCreateSlot(Symbol symbol, int containingSlot = 0)
        {
            if (symbol.Kind == SymbolKind.RangeVariable) return -1;

            containingSlot = DescendThroughTupleRestFields(ref symbol, containingSlot, forceContainingSlotsToExist: true);

            VariableIdentifier identifier = new VariableIdentifier(symbol, containingSlot);
            int slot;

            // Since analysis may proceed in multiple passes, it is possible the slot is already assigned.
            if (!_variableSlot.TryGetValue(identifier, out slot))
...
```
It looks like DescendThroughTupleRestFields can return -1. Does it make sense to continue in this case? It looks like we will go ahead and allocate a new slot for the member even in this case. It also looks like that slot is going to be shared across distinct original containers, effectively treating members of different containers as the same storage location.

**Comment by gafter** [comment]
This looks to be part of the fallout of https://github.com/dotnet/roslyn/issues/20648 .  Ideally tuples should behave just like other value types and should require no special logic in the flow pass.  When https://github.com/dotnet/roslyn/issues/20648 is fixed this code will likely be deleted.

**Comment by gafter** [comment]
`DescendThroughTupleRestFields` is supposed to return `-1` when a symbol is static (e.g. a static field), which is behavior that was introduced for the nullable walker.  That is currect behavior.  Since static members are shared among distinct objects, the same symbol should get the same slot no matter the container.

In short, it appears this is by design.
