### ISSUE TITLE
Project doesn't compile with c#8.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32354]
protected virtual object ReformatReadValue(object value)
{ 
...
return value is byte[] ? new Guid((byte[])value) : new Guid(value.ToString());
}

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/408628/project-doesnt-compile-with-c80.html
VSTS ticketId: 751838_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by gafter** [comment]
Dup of #32141.  I am working on this issue now.
