### ISSUE TITLE
Nullable + dynamic

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32364]
If there is defined class A which overloads + operator such that it returns always null then it is possible to write program throwing ArgumentNullException but has no warnings by dynamics.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/401974/nullable-dynamic.html
VSTS ticketId: 743594_
_These are the original issue comments:_

libor.drozdek on 12/7/2018, 01:58 AM (34 days ago): <p>I have problems with formatting when I use "insert Code" so I will post the code here:

```csharp
#nullable enable 
class Program
{
    private static void Main()
    {
        A obj = new A();
        var x = f(obj); 
        // Null reference exception but no warning
        x.ToString();
    }
    
    public static object f(dynamic a)
    {
        if (a == null)
            throw new System.Exception();

        return a + a;
    }
    
    public class A
    {
        public static A? operator +(A fst, A snd) => null;
    }
}
```

_These are the original issue solutions:_
(no solutions)

----
[jcouv update:] I referenced this issue in code. Please find those references before closing this issue.

**Comment by jcouv** [comment]
There's a number of questions around `dynamic` and nullability analysis. We'll have to confirm with LDM, but my sense is that once you enter the world of `dynamic` you exit the world of static analysis, including static nullability analysis. 
We can track top-level nullability, but nothing about members/methods.

A few scenarios that need discussion:
```C#
dynamic d = something;
int y = d.x.y; // ok
d.x = null; // ok
d.M(); // ok
d.M!(); // useless

d = null;
d.M(); // warn
int x = d.x; // warn
```

**Comment by jcouv** [comment]
I'm re-opening this issue as I've used this to track questions relative to dynamic and nullable. (see updated I made to OP)

**Comment by gafter** [comment]
This behavior was confirmed by the LDM on 2019-04-03.
