### ISSUE TITLE
RuntimeBinderException when trying to subscribe from C# to dynamic object event defined in C++/CLR module

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32365]
When I'm trying to subscribe in C# to event defined in C++/CLR module using dynamic object I get RuntimeBinderException {&quot;The event 'Event' can only appear on the left hand side of += or -=&quot;}

It works when dynamic object comes from C# module or when I use C++/CLR object directly (without dynamic). 

This problem doesn't occur in latest VS2017.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/399539/runtimebinderexception-when-trying-to-subscribe-fr.html
VSTS ticketId: 740220_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by gafter** [comment]
If the problem doesn't occur in the latest, then it has been fixed.  Please let us know if it recurs.
