### ISSUE TITLE
C#8.0 feature block the past code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32362]
```csharp
public static string PrintArray(object[] array)
  => string.Join(
    ",",
    array.Aggregate(
      new object[0].AsEnumerable(),
      (a, b) => a.Concat(b is object[] ? (object[]) b : new[] {b})));
```

in VS2019 perview, C# Console Project and target C# 7.3,this code can not compile.but it can compile in VS 2017 15.9.3.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/407690/c80-feature-block-the-past-code.html
VSTS ticketId: 750482_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by gafter** [comment]
This is a dup of #32141.  I am working on it now.
