### ISSUE TITLE
CS4009 should not be suppressed in the Error List window when set to "Build + Intellisense" VS2019

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32361]
Create a new console application containing this code. I reproduced this in both a .NET Core 3.0 and .NET Framework 4.7.2 project.

```csharp
class Program
{
    static async void Main(string[] args) { }
}
```

Open the Error List window, and set it to &quot;Entire Solution&quot;, no filter, and &quot;Build Only&quot;. Build the solution.

Observed and expected behavior: Error CS5001, error CS4009, and warning CS1998 appear in the Error List window.

Set the Error List window to &quot;Build + Intellisense&quot; instead of &quot;Build Only&quot;

Observed behavior: Error CS4009 is removed from the Error List window.

Expected behavior: Error CS4009 should not be removed from the Error List window, unless the user changes the code in a way that resolves the error.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/414443/cs4009-should-not-be-suppressed-in-the-error-list.html
VSTS ticketId: 756143_
_These are the original issue comments:_

Dale McCoy on 1/3/2019, 00:08 PM (7 days ago): <p>This looks to me like this is the Visual Studio 2019 version of https://github.com/dotnet/roslyn/issues/17259 and https://github.com/dotnet/roslyn/issues/29698</p>

_These are the original issue solutions:_
(no solutions)

**Comment by gafter** [comment]
It is the IDE that decides when and where these errors are displayed.
