### ISSUE TITLE
Using ternary operator with a type check

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32363]
The following code does not compile in VS2019, but works in VS2017:

```csharp
var test = new byte[5];
var res = test is byte[] ? "yes" : "no";
```

There error seems to be the parser thinking the '?' is trying to set byte[] to a nullable reference type and I see the error message:

'Feature nullable reference type is not available in C# 7.0.'

The parser should recognize the difference between a nullable type, and the ternary operator syntax.

The issue is resolved by converting the 'res' line to:

```csharp
var res = (test is byte[]) ? "yes": "no";
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/408856/using-ternary-operator-with-a-type-check.html
VSTS ticketId: 752025_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by gafter** [comment]
This is a dup of #32141. I am working on it now.
