### ISSUE TITLE
Typing closing brace of switch expression results in duplicate brace

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#32373]
The deduplication of the closing brace works if the switch expression is typed on a single line.
But it doesn't work for a multi-line switch expression.
I expect the same behavior as typing a multi-line `if` statement with braces.

![switch-closing](https://user-images.githubusercontent.com/12466233/51007429-5280d600-14fc-11e9-830c-da9c2d65b501.gif)

CC @gafter 

Umbrella for recursive-patterns: https://github.com/dotnet/roslyn/issues/25935

**Comment by ryzngard** [comment]
@jcouv 	this behavior is expected afaict. All other cases of multiline braces behave this way (I tried with lambda and array initialization). If we want this improved, we should categorize as a feature request and handle accordingly.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an editor request i believe.  Roslyn doesn't control this.  Rather, this is a core part of the design of hte editor brace-matching engine.  We just state what the braces are.  They then track them and decide how matching/overwrite works.  In this case, i believe they effectively will not match once newlines have been added.
