### ISSUE TITLE
Stepping through switch expression is wrong

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#32370]
The whole statement with the switch expression never gets highlighted as I step forward.

![switch-stepping](https://user-images.githubusercontent.com/12466233/51006761-8c041200-14f9-11e9-8738-029e04f8ec81.gif)

When fixing this, please also verify that LUT (live unittesting) instrumentation works.

**Comment by gafter** [comment]
The switch expression should have no impact on LUT.  I will add switch expressions to some existing LUT tests to confirm that there is no change in expected LUT results.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/32755 for dev16.0
