### ISSUE TITLE
Compiler should not declare var as dynamic if it is the result of a function call with typed return value

### ISSUE THREAD

**Issue by rangp** [dotnet/roslyn#32389]
**VS 2017 C# Tool 2.10.0-beta2*: 

**Repro Steps**:

Function has return type `string`:

```
        private static string ToStringFromDynamic(dynamic dynamicString)
        {
           return dynamicString?.ToString() as string;
        }
```

Usage like this:

```
  dynamic y = string.Empty;
  var x = ToStringFromDynamic(y);
```

**Expected Behavior**:

x is declared as string because of the function return type.

**Actual Behavior**:

x is also declared as dynamic.

Interestingly if I declare `ToStringFromDynamic` as local func:

```
string ToStringFromDynamic(dynamic dynamicString)
        {
           return dynamicString?.ToString() as string;
        }

  dynamic y = string.Empty;
  var x = ToStringFromDynamic(y);
```

it works as expected.

**Comment by gafter** [comment]
The language specification requires the current behavior, so I'm moving this to csharplang.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #2136](https://github.com/dotnet/csharplang/issues/2136) via [**ZenHub**](https://www.zenhub.com/)
