### ISSUE TITLE
VB codespit for "Implement Interface" fails to add "Overloads" modifier where necessary

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3238]
Look at the kind of bad codespit I get:

![vb-implements](https://cloud.githubusercontent.com/assets/3316258/7924771/008f9b22-0873-11e5-9299-2cd1c2c4b1d0.png)

REPRO: (1) Start with this class

``` vb
Class C
    Public Overrides Function ToString() As String
        Return ""
    End Function
End Class
```

(2) Add an "Implements IFormattable" clause and press Enter to perform the "Implement Interface" quickfix:

``` vb
    Implements IFormattable

    Public Function ToString(format As String, formatProvider As IFormatProvider) As String Implements IFormattable.ToString
        Throw New NotImplementedException()
    End Function
```

What I expect: it should spit it out as `Public Overloads Function ToString`.

What I get: it fails to spit out the `Overloads` modifier, and hence is in error.

(The same issue doesn't apply to C#...)

**Comment by Pilchie** [comment]
Keeping in 1.0, since this produces code with an error.

**Comment by jmarolf** [comment]
@Pilchie I don't think this meets the bar for 1.0.  Please move it back if you disagree.

**Comment by CyrusNajmabadi** [comment]
Closing out as we're not changing these vb experiences.
