### ISSUE TITLE
MissingMethodException when compiling with Visual Basic in a UWP Application since UWP version 6.1.9

### ISSUE THREAD

**Issue by nseveno** [dotnet/roslyn#32396]
**Version Used**: Microsoft.CodeAnalysis.VisualBasic package version 2.10.0

**Steps to Reproduce**:
1. Create a new UWP Application in Visual Studio 2017
2. In the nuget package manager, select Microsoft.NETCore.UniversalWindowsPlatform package to a version >= 6.1.9
3. In the nuget package manager, add a reference to the Microsoft.CodeAnalysis.VisualBasic package.
4. Add a button on the main page and in the Click event, write the following code :
```
VisualBasicCompilationOptions options = new VisualBasicCompilationOptions(
                        OutputKind.DynamicallyLinkedLibrary,
                        optimizationLevel: OptimizationLevel.Release,
                        embedVbCoreRuntime: false,
                        optionStrict: OptionStrict.Off,
                        optionInfer: true,
                        optionExplicit: true);

                VisualBasicCompilation compilation = VisualBasicCompilation.Create(
                    "Test",
                    new[] { VisualBasicSyntaxTree.ParseText("Public Class Test\r\nEnd Class").WithFilePath("Test.cs") },
                    new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) },
                    options);

                using (MemoryStream peStream = new MemoryStream())
                {
                    EmitResult emitResult = compilation.Emit(peStream);
                }
```

I attached a repro project : [ReproCompilation.zip](https://github.com/dotnet/roslyn/files/2749886/ReproCompilation.zip)

The problem does not happen if I change the Microsoft.NETCore.UniversalWindowsPlatform package to version 6.1.7. This could be a problem for our product if we need to move to a more recent version.

**Expected Behavior**:
Compilation should succeed.

**Actual Behavior**:
And exception is thrown :

> System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void System.Reflection.PortableExecutable.DebugDirectoryBuilder.AddPdbChecksumEntry(System.String, System.Collections.Immutable.ImmutableArray`1<Byte>)'.
  Source=Microsoft.CodeAnalysis
  Arborescence des appels de procédure :
   à Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   à Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   à Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, Boolean includePrivateMembers, Boolean emitTestCoverageData, String pePdbFilePath, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   à Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream metadataPEStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken)
   à Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, Stream metadataPEStream, CancellationToken cancellationToken)
   à TestFocus.MainPage.<>c.<Button_Click>b__1_0() dans D:\Projets\Recherche\TestFocus\TestFocus\MainPage.xaml.cs :ligne 59
   à System.Threading.Tasks.Task`1.InnerInvoke()
   à System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by gafter** [comment]
Sounds like a problem with the way the app is deployed by the build process.  @agocke How should this issue be directed?

**Comment by nseveno** [comment]
Hi,

We migrated the Microsoft.CodeAnalysis.VisualBasic package to version 3.1.0. Our UWP application uses Microsoft.NETCore.UniversalWindowsPlatform package 6.2.8 and SDK 10.0.16299 (1709). And it works.

So for me this is issue can be closed...
Regards,

Nicolas Séveno
