### ISSUE TITLE
[CodePlex] Error CS7023 'is' for static classes [breaking compiler change]

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#324]
Originally from [http://roslyn.codeplex.com/workitem/315](http://roslyn.codeplex.com/workitem/315)

@JanKucera reported:
The `ShellProperty<T>` class from `WindowsAPICodePack `stopped compiling in Roslyn.

It uses the `Nullable` class in the way similar to this:

```
class MyClass<T>
{
    public bool IsNullable(T value)
    {
       return value is Nullable;
   }
}
```

which, since `Nullable` is a static class, likely does not do what intended.

Roslyn generates

```
error CS7023: The second operand of an 'is' or 'as' operator may not be static type 'System.Nullable'.
```

However, shouldn't this be treated more as "The result of the expression is always 'false'" warning?

**Comment by theoy** [comment]
:+1: for restoring this behavior for compat reasons. While I can see the case for elegance for disallowing this, it's been in the language for too long... and at this point it will cause confusion if upgrading users get broken. Thanks, Neal! (@gafter)

**Comment by gafter** [comment]
Note to self: This needs to be documented in the compiler spec before being marked verified.
