### ISSUE TITLE
Expand the scope of catching PE writing exceptions to all of PE writing

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#3240]
PR #3237 introduces a try/catch that is meant to catch issues when getting the input stream while signing the output file.

This is too narrow in scope -- we should catch all errors in PE writing and surface a diagnostic. We're not doing it now because we cannot add an understandable localized error message for the diagnostic.

**Comment by jaredpar** [comment]
Keeping in 1.2 as we've seen this show up in Watson dumps.

**Comment by TyOverby** [comment]
What would the generic error message be?  Should we have multiple error messages for different failure cases?

**Comment by jaredpar** [comment]
I think it should be pretty general and print out the message of the failing exception.  Along the lines of 

> `An exception occurred emitting the PE / PDB: {0}`

**Comment by TyOverby** [comment]
Ok, so leave the specialized IO message, and add a more general one that catches the rest?

**Comment by jaredpar** [comment]
I'll let @agocke  comment on that

**Comment by agocke** [comment]
Add a general message -- the reason I didn't add a general message when I tried to hotfix this for the 1.0 release was that we had already locked down localization, so I couldn't add any new localizable strings to Roslyn.

**Comment by agocke** [comment]
Also, you should add the `try..catch` in PEWriting, rather than where I did the spot-fix here.

**Comment by TyOverby** [comment]
@agocke Is there a reason that this catch https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Compilation/Compilation.cs#L1922 doesn't have a `return false`.

**Comment by agocke** [comment]
@TyOverby I believe https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Compilation/Compilation.cs#L1936 deals with that, but you can debug to verify the code path.
