### ISSUE TITLE
Use events for WaitForNoErrorsInErrorList

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#32401]
Currently this helper method loops until a timeout expires. It should be updated to simply wait for the asynchronous features responsible for error updating to complete and then assert that the list is now empty.

https://github.com/dotnet/roslyn/blob/1252f52b623bf2df7dbf6361a28c37b247c8c370/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/ErrorList_InProc.cs#L27-L30

**Comment by CyrusNajmabadi** [comment]
This method doesn't exist.  Removing.
