### ISSUE TITLE
AsynchronousOperationListenerTests.IgnoredCancel Test Failed

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#32404]
Saw this on #32390 - Windows Desktop Debug Test32 - [Test Logs](https://dnceng.visualstudio.com/public/_build/results?buildId=70891&view=ms.vss-test-web.test-result-details) Attempt 1

```
Error message
We waited for the cancelled task to finish.\r\nExpected: False\r\nActual: True
Stack trace
   at Microsoft.CodeAnalysis.Editor.UnitTests.Utilities.AsynchronousOperationListenerTests.IgnoredCancel() in /_/src/EditorFeatures/Test/Utilities/AsynchronousOperationListenerTests.cs:line 293
```

**Comment by JoeRobich** [comment]
Saw this again in #32417 - [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=72079&view=ms.vss-test-web.test-result-details) Attempt 1

**Comment by sharwell** [comment]
In the past 30 days, this test has failed 3 times out of a total 3528 times it ran, for a failure rate of 0.085%.

**Comment by JoeRobich** [comment]
Saw this again in #32897 - [Build logs](https://dev.azure.com/dnceng/public/_build/results?buildId=82123) Spanish_Unit_Tests Attempt 1
