### ISSUE TITLE
Read/Write Kind in FAR Appears Offscreen

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#32405]
Using Int Preview 25810.146, hitting FAR on an identifier has the Read/Write Kind off the side of the screen, I have to resize the Code section to see it. If I didn't know it was there, I wouldn't discover it.

**Comment by mavasani** [comment]
Tagging @dpugh - seems to be related to https://devdiv.visualstudio.com/DevDiv/_queries/edit/723028

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard more on this.  If this does repro, it's not part of roslyn, but needs to go through devcom.
