### ISSUE TITLE
Language icon nondeterministically switches between C# and VB when in a C# file in the CSharpCompilerEmitTest project

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#3241]
When I open any C# file in the CSharpCompilerEmitTest project and click around the file, the language icon at the top of the file will often show VB, not C#. There doesn't seem to be a clear pattern to when it will be VB or C#, but it often settles on VB. See the following image for an example:

![languageicon](https://cloud.githubusercontent.com/assets/515774/7925086/eebe4c10-0875-11e5-8ad9-ff6a6c0a0007.png)

**Comment by Pilchie** [comment]
I believe VB is the default value in some error cases in this codepath.

**Comment by dpoeschl** [comment]
Maybe User Friendly effecting?

**Comment by Pilchie** [comment]
affecting maybe, effecting, no :smiley:

**Comment by dpoeschl** [comment]
Low Priority for User Friendly. Punting back to Unknown.

**Comment by davkean** [comment]
Dup'ing against https://github.com/dotnet/roslyn/issues/28236 which has more context.
