### ISSUE TITLE
SyntaxGenerator's GetAllowedModifiers is buggy

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#32423]
As a result, `WithModifiers` will ignore modifiers it doesn't think are allowed. Discovered in https://github.com/dotnet/roslyn/pull/32422/files#r247326449

**Comment by Neme12** [comment]
Fixing this would fix #29561

**Comment by CyrusNajmabadi** [comment]
Can you be more specific?  How is GetAllowedModifiers 'buggy'?

**Comment by Neme12** [comment]
It returns incorrect lists of allowed modifiers.

> These lists should be reviewed. I can see at least a few bugs right away:
> 
> * ref & readonly for structs isn't allowed
> * readonly is allowed for properties but shouldn't be
> * nothing is allowed for local declarations, but const should be
> * nothing is allowed for parameters, but ref, in & out should be

**Comment by mavasani** [comment]
Looking at [DeclarationModifiers](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Editing/DeclarationModifiers.cs,63) and its properties, it seems it is designed only for top level declarations - i.e., namespaces, types, methods, fields, properties, and events, but not for other symbols such as locals or parameters. Its not good that there are absolutely no comments or even doc comments on the type, especially given its a public API.

If we are planning to extend `DeclarationModifiers` to now include modifiers for non-top level declarations, then we need to extend it to include modifiers such as `out`, `in`, `volatile`, etc. - we need a more exhaustive list. Additionally, this needs to go through a design meeting as we are extending the scope of an existing public API (although completely undocumented).
