### ISSUE TITLE
async function generates wrong return

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32429]
<p>Consider the following code: <br><br>    async Task DoAsync() =&gt; await NoExistsAsync();<br><br>Where the function NoExistsAsync doesn't yet exist. The function NoExistsAsync is meant to return Task according to this code. Now I try using ctrl + . to generate a new function. <br><br>Expected result: <br><br>    Task NoExistsAsync() {<br><br>Actual result: <br><br>    Task&lt;Task&gt; NoExistsAsync() {</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/410064/async-function-generates-wrong-return.html
VSTS ticketId: 752719_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Neme12** [comment]
@jinujoseph This was fixed in #30211

**Comment by jcouv** [comment]
Thanks. I'll go ahead and close this. The fix was merged into preview2.

**Comment by jinujoseph** [comment]
thanks @Neme12
