### ISSUE TITLE
C# Interactive crash VS2019 preview 1.1 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32426]
With the use of using statements in the C# Interactive in VS2019 preview 1.1, studio crashes when I try to autocomplete code suggestions with tab. 

Steps:
&gt;using System.Text.RegularExpressions;
&gt;Regex.IsMatch(&quot;foo&quot;, &quot;bar&quot;, *tab to autocomplete RegexOptions*)

Studio crashes and I can't find any helpfull logs.

Visual Studio 2019 Professional Preview
Version 16.0.0 Preview 1.1

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/418789/c-interactive-crash-vs2019-preview-11.html
VSTS ticketId: 759558_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Neme12** [comment]
maybe related to regex language service? tagging @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
My guess is that this is hte sig help overload indexing issue.  @jnm2 ran into this too, but it had nothing to do with Regex.

**Comment by jnm2** [comment]
If so, I think it's already fixed. https://github.com/dotnet/roslyn/issues/31263#issuecomment-447140017

**Comment by jinujoseph** [comment]
Should be fixed in 16.0.Preview2 via #30997
