### ISSUE TITLE
No way to make nullable pattern variable in nullable analysis

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#32433]
**Version Used**: `features/NullableReferenceTypes`

**Steps to Reproduce**:

```cs
void M(object o) { 
  if (!(o is string s)) s = null; // wraning: Converting null literal or possible null value to non-nullable type.
  var l = s.Length; // warning: Possible null dereference
}
```

Using `null!` would resolve both warnings but there's no way to keep the second warning - making `s` a nullable type for nullable analysis.

**Comment by gafter** [comment]
This is by design.  If you need a nullable local variable, don't declare it inside a pattern.
``` c#
var v = (o is string s) ? s : null;
```
