### ISSUE TITLE
improve GetPrevious/GetNextToken performance

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#3244]
look devdiv # [1089540 ](https://vstfdevdiv/DevDiv2/DevDiv/_workitems/edit/1089540)for more detail.

GetNextToken takes 40% of time (of several minutes)

**Comment by AdamSpeight2008** [comment]
GetNextToken definition in [source](https://github.com/dotnet/roslyn/blob/8771786e5a80e9d27ffb40702f5cca558ca6fabb/src/Compilers/Core/Portable/Syntax/SyntaxToken.cs#L575)

**Comment by heejaechang** [comment]
for the same file in the bug, smart indenter on "}" in array initializer also spends most of its time on GetNextToken. (16 seconds in my machine)

**Comment by CyrusNajmabadi** [comment]
Dont' currently have any issue indicating we still have a problem here.  So closing out.
