### ISSUE TITLE
implicitly typed array of nullables has wrong type

### ISSUE THREAD

**Issue by Spongman** [dotnet/roslyn#32459]
```c#
var foo = new [] { default(string?) };
```

hover over `foo`, it shows type `string[]`, i would expect `string?[]`

**Comment by jasonmalinowski** [comment]
This is at this point blocked on the compiler finishing up API support, I believe.

**Comment by jasonmalinowski** [comment]
@333fred: if I look at ILocalSymbol, I'm seeing the array's element nullability is "Disabled". Is that expected?

**Comment by 333fred** [comment]
I'm not sure that `var` inference is implemented right now, so it's very possible that `GetDeclaredSymbol` will be returning the wrong thing here.
