### ISSUE TITLE
non-nullability of anonymous type properties in lambdas are messed up

### ISSUE THREAD

**Issue by Spongman** [dotnet/roslyn#32465]
```c#
System.Linq.Expressions.Expression<int>? first;
var q = first?.Parameters.Select(f => new { f });
```

hover over the `f` in `new { f }`:

![image](https://user-images.githubusercontent.com/1088194/51151855-385b3680-1821-11e9-9add-c5625f21397a.png)

which is it? is `f` nullable or not?

**Comment by Spongman** [comment]
here's another one:

```c#
{
	void Foo(Dictionary<string, int> _) { }
	Foo(new string[] { }.Select(e => new { e }).ToDictionary(p => p.e, p => 1)); // warning CS8620: Nullability of reference types in argument of type 'Dictionary<string?, int>' doesn't match target type 'Dictionary<string, int>' for parameter '_' in 'void Foo(Dictionary<string, int> _)'.
}
```
there's nowhere there where anything should be nullable.

**Comment by Spongman** [comment]
i think this is the simplest:
```c#
void Foo(string str) { }
var v = Array.Empty<int>().Select(_ => new { e = "" }).First();
Foo(v.e); // possible null reference
```

**Comment by sharwell** [comment]
@Spongman I moved two of your comments to a separate issue so they can be handled by the appropriate team.

**Comment by jasonmalinowski** [comment]
This appears to be working now. At the time the bug was filed I don't think the compiler had implemented some of the symbol model stuff yet so I can't say I'm terribly surprised it would acted funny before.

Closing. FYI to @333fred if we think we need more tests here or that something further is screwy.

**Comment by 333fred** [comment]
I expect that this has been fixed when I made `GetSymbolInfo` work with method calls, but I suspect we'll get some other bugs in this vein that won't be fixed until we fully implement that API.
