### ISSUE TITLE
nullability checking inconsisten between locals & parameters

### ISSUE THREAD

**Issue by Spongman** [dotnet/roslyn#32463]
```c#
public void Foo(string? param)
{
	if (param != null)
	{
		var l1 = param.Length;
		var l2 = new[] { 0 }.Select(_ => param.Length);  // CS8602
	}

	string? local = "";
	if (local != null)
	{
		var l1 = local.Length;
		var l2 = new[] { 0 }.Select(_ => local.Length);
	}
}
```

only `param` get a `warning CS8602: Possible dereference of a null reference.`.

for some reason the `local` doesn't get the same warning.

- both should be consistent.
- really, since both are read-only in the method, _neither_ should get that warning.

**Comment by Spongman** [comment]
not sure if this is related, but

```c#
public static void Foo(bool? param = null)
{
	if (param != null)
	{
		object f = param; // warning CS8600: Converting null literal or possible null value to non-nullable type.
		Console.WriteLine(f);
	}
}
```

i would expect `param` to be considered non-nullable inside the `if` statement's block.

**Comment by gafter** [comment]
This will probably be resolved by https://github.com/dotnet/roslyn/pull/34300
