### ISSUE TITLE
Capture extra invalid dimensions for SemanticModel and IOperation

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#32464]
In invalid code such as `void M(string[20] x)`, we should capture the expression `20` for use in the `SemanticModel` and `IOperation`. These were previously a syntax error and result in skipped tokens, but they are now being parsed but not bound after https://github.com/dotnet/roslyn/pull/32431

**Comment by YairHalberstadt** [comment]
Do you think I might be able to help here?

**Comment by gafter** [comment]
@YairHalberstadt I think this one is likely to require significant additions to the compiler's symbol table data structures, as there is no place to store the bound nodes for these expressions today, e.g. a type in a field declaration, base type declaration, etc. How would you try to solve this? I would welcome your help, but I cannot promise that we will like the solution you come up with.

**Comment by YairHalberstadt** [comment]
Looking at the code over the last couple of evenings, I see two possible approaches.

One is to subclass BoundTypeExpression with BoundArrayTypeExpression. This would have a field for the dimensions.

The alternative is to have a catch all field in BoundTypeExpression (or even BoundNode) which stores an array of BoundNodes, called `InvalidExtraNodes`. Each BoundNode would have an associated enum which would indicate what exactly it is. In this case the enum would be dimension.

Then code which reads the BoundTree could choose to check these nodes or ignore them.

Do either of these sound like they are on the right lines?

**Comment by gafter** [comment]
> One is to subclass BoundTypeExpression with BoundArrayTypeExpression. This would have a field for the dimensions.

There are no bound nodes for declarations.

> The alternative is to have a catch all field in BoundTypeExpression

There are no bound nodes for declarations.

**Comment by gafter** [comment]
@YairHalberstadt After discussing it here with my coworkers, I think the approach you propose would improve the situation within method bodies... and that is the primary scenario that we are concerned about.  So yes, we'd love to have your help, and the approaches you suggest would do the trick.

**Comment by YairHalberstadt** [comment]
Thanks.
Do you have any idea, which would be preferable?
I'm going to try finish up a couple of other prs first, then have another tackle at this.

**Comment by YairHalberstadt** [comment]
@gafter 
Currently an `IVariableDeclaratorOperation` has an `IgnoredArguments` Property.
This is used for cases like the `10` in:

```csharp
int x[10];
```

Does it make sense to use the same property for
```csharp
int[10] x;
```

avoiding the necessity of increasing the public API surface?

The alternative is to add an `IgnoredDimensions` property with almost identical usages as IgnoredArguments. This is trivial to do, but I don't know if it is most helpful.

Note that either way we will have to solve cases such as typeof(int[10]) where there is no variable declaration separately.

At the Back End, I'm adding a `DimensionsOpt` field to a  `BoundTypeExpression` which stores any rankSpecifiers associated with an array.

**Comment by YairHalberstadt** [comment]
Scrap that. IgnoredDimensions is part of `InvalidDeclarationOperation` not `InvalidDeclaratorOperation`

**Comment by YairHalberstadt** [comment]
An initial pull request has been created, which just does this for IVariableDeclarationOperation

**Comment by gafter** [comment]
@YairHalberstadt fixed this in #32843.  Thanks for the contribution!
