### ISSUE TITLE
Allow Obsolete attribute on getters and setters

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#32472]
Currently in C# the Obsolete attribute is not allowed on property getters and setters. 

```
using System;

class C
{
    int P { get; [Obsolete] set; }
}
```
Has the error 

`error CS1667: Attribute 'System.ObsoleteAttribute' is not valid on property or event accessors. It is only valid on 'class, struct, enum, constructor, method, property, indexer, field, event, interface, delegate' declarations.`

In VB it is allowed, and seems to work as expected.

It would also be useful, for example when I want to start making a property readonly, and so mark usages of the setter obsolete in the meantime. Also a property setter might have to be declared for eg. XmlSerialization, but I don't want anyone else using it, so I would like to mark it obsolete.

Since the obsolete attribute seems to be unique in this regard among attributes, I'm guessing this is either a compiler or a language feature.

I'm not sure which repository is the correct place for this issue, so I'm asking it here, and if necessary I will move it to csharplang.

**Comment by YairHalberstadt** [comment]
The ecma specification seems silent on this:

> **9 24.4.3 The Obsolete attribute**
> The attribute Obsolete is used to mark types and members of types that should no longer be used.
> ````csharp
>      using System;
> 	[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct |
> 					AttributeTargets.Enum | AttributeTargets.Interface |
> 					AttributeTargets.Delegate | AttributeTargets.Method |
> 					AttributeTargets.Constructor | AttributeTargets.Property |
> 					AttributeTargets.Field | AttributeTargets.Event)]
> 	public class ObsoleteAttribute : Attribute
> 	{
> 		public ObsoleteAttribute() { ... }
> 
> 		public ObsoleteAttribute(string message) { ... }
> 
> 		public ObsoleteAttribute(string message, bool error) { ... }
> 
> 		public string Message { get { ... } }
> 
> 		public bool IsError { get { ... } }
> 	}

> If a program uses a type or member that is decorated with the Obsolete attribute, then the compiler shall issue a warning or error in order to alert the developer, so the offending code can be fixed. 
> 
> Specifically, the compiler shall issue a warning if no error parameter is provided, or if the error parameter is provided and has the value false. The compiler shall issue a compile-time error if the error parameter is specified and has the value true.

I guess it's opinion on this depends on how you define Member

**Comment by YairHalberstadt** [comment]
the C# 6 draft specification is identical: https://github.com/dotnet/csharplang/blob/master/spec/attributes.md#the-obsolete-attribute

**Comment by svick** [comment]
@jinujoseph As far as I can tell, attributes on property accessors are allowed if the attribute has `AttributeTargets.Method`, which `ObsoleteAttribute` does have.

Though I think this is not really about `AttributeTargets`: for some reason, Roslyn contains code specifically to ensure `ObsoleteAttribute` is not applied to accessors:

https://github.com/dotnet/roslyn/blob/9e501093bc44a15361704aa057ebbdaf477fa9a2/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs#L1167

https://github.com/dotnet/roslyn/blob/9e501093bc44a15361704aa057ebbdaf477fa9a2/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs#L1211-L1228

**Comment by sharwell** [comment]
@svick Thanks for the details there. Hopefully the compiler team can shed some light. 😄

**Comment by jaredpar** [comment]
@gafter

**Comment by YairHalberstadt** [comment]
I have removed the code disallowing the Obsolete Attribute, and confirmed that everything works as expected, without requiring any further changes:

https://github.com/YairHalberstadt/roslyn/tree/AllowObsoleteOnPropertyAccessors

If this is considered not to require approval from the LDC, I will open a PR.

**Comment by CyrusNajmabadi** [comment]
based on @svick's analysis, i'm leaning toward this simply being a bug.  As far as i can tell, the rest of the compiler consider accessors to just be methods as far as other attributes go.  So it seems reasonable to be consistent there with this specific attribute.  Barring something in the language spec itself disallowing this (and i don't see anything https://github.com/dotnet/csharplang/blob/master/spec/attributes.md#the-obsolete-attribute that would make me think that exists), then it seems like this makes sense given how we've interpreted `AttributeTargets.Method` everywhere else.

**Comment by gafter** [comment]
We'll discuss this on Jan 23.  If the LDM likes it we'll review the PR.

**Comment by YairHalberstadt** [comment]
Thanks

**Comment by jnm2** [comment]
I'd expect `nameof` and XML crefs not to give warnings if only one accessor was obsolete.

Should it fail to compile if you obsolete both accessors, since you should move the obsoletion to the whole property? Valid configurations would be:
- No obsoletion
- Obsoletion of entire property
- Obsoletion of exactly one accessor

**Comment by YairHalberstadt** [comment]
Note the exact same question arises if the getter is obsoleted and there is no setter, or vice versa.

If obsoletion of both accessors was allowed (which I think is pointless, but kind of like from a symmetry standpoint), I would suggest nameof ought to still work on the property, as the property has not been declared obsolete. But this is a relatively trivial detail TBH.

Also, I'm guessing this discussion ought to me be to the championed issue.

**Comment by jnm2** [comment]
> I would suggest nameof ought to still work on the property, as the property has not been declared obsolete. 

This feels like a pitfall to me. Maybe you need a different message between the two, but what's the meaning of obsoleting all accessors versus obsoleting the property versus both? For a getter-only property, why should it be legal or desirable as well?

**Comment by YairHalberstadt** [comment]
What does VB do?

**Comment by YairHalberstadt** [comment]
https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-02-27.md

It looks like the LDC has supported this proposal.

**Comment by gafter** [comment]
The LDM asked to ensure that this works for `ObsoleteAttribute` as well as `DeprecatedAttribute` (and that there be tests for that)

**Comment by YairHalberstadt** [comment]
I'm in the middle of cleaning up and finishing off the original pull request.

I intend to allow Obsolete and Deprecated on property accessors, but not event accessors.

I also will change current behaviour so that an obsolete or deprecated attribute on any accessor (property or event) will suppress warnings from the usage of obsolete/deprecated symbols in that accessor.

A new error will be needed to indicate that deprecated and obsolete attributes cannot be used on event accessors but can be used on property accessors.

The error for using obsolete/deprecated on an attribute pre C# 8 will be changed to indicate that this will be allowed in C# 8.

No work needs to be done to consume these attributes correctly, as they were already legal in VB.

**Comment by gafter** [comment]
@YairHalberstadt That all sounds perfect.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/32571
