### ISSUE TITLE
Emitting Debug.Assert(e != null) via null-supression operator

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#32478]
When we're passing a `e!` where `e` is not the literal `null`, we expect it to be not null at that point but the flow analysis couldn't infer that, so I think we should emit `Assert(e != null)` to catch an unexpected null early, rather than silently passing it through until a thought-to-be-safe dereference occurs.

**Comment by gafter** [comment]
This is a request to change the planned language specification for the nullable feature.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #2149](https://github.com/dotnet/csharplang/issues/2149) via [**ZenHub**](https://www.zenhub.com/)
