### ISSUE TITLE
Find all references on a property returns unrelated properties

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32486]
Using VS 2017 professional (15.9.4):
Given a large solution with 61 projects and about 21000 .cs files, hitting Shift+F12 on a property sometimes returns matches that belong to different class hierarchies, and thus acts more like &quot;Find in files&quot;, rather than &quot;Find all references&quot;.

Simplified example:

```csharp
class Foo{
 public int MyProperty { get; set; }
}

class Bar{
 public int MyProperty { get; set; }
}

class Other
{
  void Method()
  {
    var foo = new Foo();
    foo.MyProperty = 1;  // hitting Shift+F12 on MyProperty here
  }
}
```

The references belonging are obviously the assignment and the declaration of MyProperty in the Foo class.
At least in our large solution, the results of Find All References sometimes include other code elements (I am not sure whether this is limited to properties) having the same name, which in the simplified example would mean that also Bar.MyProperty is included, but that's wrong.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/419689/find-all-references-on-a-property-returns-unrelate.html
VSTS ticketId: 760763_
_These are the original issue comments:_

jonas on 1/7/2019, 04:17 AM (8 days ago): Note that I was a bit lazy when I wrote the example. The thing is that simple projects show references as expected, but within a certain large solution, I am experiencing false positives, which is confusing to work with.I can't share the source code. The problem extends to (at least) methods as well, not only properties.The symptom is basically that "find all references" works like "find in files" to some extent.
_These are the original issue solutions:_
(no solutions)

**Comment by heejaechang** [comment]
I can't repro this.

**Comment by CyrusNajmabadi** [comment]
I can't repro this either.  Closing out.  If customer can provide a repro we can move forward with this.

**Comment by pedrob80** [comment]
dez 2022, it is still there. C++ VS 2019.

**Comment by CyrusNajmabadi** [comment]
@pedrob80 Roslyn has nothing to do with c++ :-)
