### ISSUE TITLE
Unsuitable code suggestion in ExpandoObject

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32482]
On version 15.7
When you declare an object of type ExpandoObject a code suggestion will show up to simplify the object initialization. This will not work as expected because the class members are dynamic and they are late binding

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/411147/unsuitable-code-suggestion-in-expandoobject.html
VSTS ticketId: 753395_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
Possible dupe of #18847

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/17860
