### ISSUE TITLE
Bulk fix "add braces to if statement" results in broken code.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32480]
This code:

```csharp
#if DEBUG
    if (!mSmmEndOfRideGenerated)
#endif
    record = null;

will become this:

#if DEBUG
    if (!this.mSmmEndOfRideGenerated)
    {
#endif
        record = null;
    }
```

which obviously won't compile without the DEBUG directive. If there is a compiler directive found before the statement, it better be left as is.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/390182/bulk-fix-add-braces-to-if-statement-results-in-bro.html
VSTS ticketId: 734356_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by dibarbet** [comment]
This bug applies to any multi-line add braces suggestion (while, lock, using, fixed).  If a compiler directive comes in between the statement and embedded statement the meaning will change.

**Comment by dibarbet** [comment]
resolved in https://github.com/dotnet/roslyn/pull/32744
