### ISSUE TITLE
IntelliSense broken on large files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32487]
<p>No matter how many times you close IntelliSense bug reports, it's still not fixed. :-)<br><br>I have a 492k source file in my project. No, I can't and don't want to split it up, it's a large data list, initialized in code, I need it. There's no problem with the compilation and the functioning of the program whatsoever. But as soon as I as much as open this file for a moment. IntelliSense stops working for the whole solution until I restart VS. No error messages will ever be shown, neither during typing nor after compilation (!).<br><br>Sometimes deleting .vs is required, sometimes it isn't. IntelliSense clearly cannot cope with otherwise perfectly fine larger files and it can't let them go correctly, either.</p><p>I can't send you the file but it's easy to reproduce. Just create a struct with a dozen or so items, add an array initialization like:</p><pre>    public static MyStruct[] LargeTabe = new MyStruct[] {
      new MyStruct(...),
      new MyStruct(...),
      ...
      new MyStruct(...),
    };</pre><p>repeat it a couple thousand times and that's it.</p>
</pre>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/419744/intellisense-broken-on-large-files.html
VSTS ticketId: 760798_
_These are the original issue comments:_

Yanghua Zhang[MSFT] on 1/8/2019, 04:15 AM (7 days ago): <p>Thank you for your feedback! Could you please tell us what type of project did your problem appear in? We tried repro this issue with a VC++ console project, it has many errors and intellisense is not broken. We record a video for your reference (<a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/54701-repro.gif">repro.gif</a>). If we miss something, please tell us. For us to investigate this further, could you please share more detail information to us(e.g. repro project and so on). We look forward to hearing from you!</p>

Gábor Deák Jahn on 1/8/2019, 11:57 AM (6 days ago): <p>Plain and simple C# .NET.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I could not repro this.  Perhaps it was the name-generation core algorithm which blew up on memory?  I'm going to close this out. If you are still seeing this, please provide the version of VS you're using and an exemplar file that can be used to determine waht the core cause is.
