### ISSUE TITLE
Nullable reference type inspections should not make assumptions about custom equality operators

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#32498]
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 1.1
VisualStudio.16.Preview/16.0.0-pre.1.1+28408.50
Microsoft .NET Framework
Version 4.7.03056

**Steps to Reproduce**:

Compile and run the following code
```cs
#nullable enable
class C
{
  public static bool operator ==(C? c1, C? c2) => true;
  public static bool operator !=(C? c1, C? c2) => true;

  public static void Main()
  {
    M(null);
  }

  static void M(C? c)
  {
    if (c != null)
    {
      c.ToString();
    }
  }
}
```
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWACgABAJgoGFGBvRiipgMz8AjADYKwAPaTCFSQAdEEGJIQUAvOoAU7APwUAxsKQd9BlgEoNAPgowE+OAG5e/IUzETpshUpVqAQm09Q2NTQ0sbOwdnRldBEXEmABYKAFkIAEtcLQtXHgY+PjStAmILF0KKAF84qo8k1JKQgzyqgqKKTIAzCi0DCiCKMsI2zo7OwwA6ABVJAGV7bIBzXMrO2qrN6qA==

**Expected Behavior**:
`Possible dereference of a null reference` for `c.ToString();`

**Actual Behavior**:
No warnings for nullable reference types. The program crashes at runtime with a `NullReferenceException`

**Comment by alrz** [comment]
>Nullable reference type inspections should not make assumptions about custom equality operators

absence of a warning is precisely because the compiler does not make assumptions about user-defined operators.

**Comment by jcouv** [comment]
I was reminded in LDM that we had discussed this before. The conclusion at the time was that we should make the assumption that all equality operators (builtin or custom) imply nullability sameness: `true` is only returned if nullabilities match.
I'll have to dig up meeting notes to confirm this.

**Comment by jcouv** [comment]
The current behavior is by design. I'll go ahead and close. Thanks
