### ISSUE TITLE
IDE0004 quickfix is incorrect when casting IntPtr to pointer

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32491]
Given something like this:

```csharp
struct Block<T>
    where T : unmanaged
{
    IntPtr m_ptr;
    unsafe ref T GetRef( int index )
    {
        return ref ((T*)m_ptr)[index];
    }
}
```

I get a quickfix suggestion to remove the cast to T*, which is obviously incorrect.

Amusingly, the IDE actually puts the red squiggly under the suggested change in the quickfix preview popup itself. :D

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/423511/ide0004-quickfix-is-incorrect-when-casting-intptr.html
VSTS ticketId: 763320_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
Duplicate of #25021
