### ISSUE TITLE
Code suggestions are applied to linked source files even if unchecked

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32490]
In a C# project containing both regular source files and linked source files (Project | Add Existing Item | drop down on Add button | Add as Link), enter some code that will generate a suggestion (eg. potential inline variable declaration (IDE0018)).
In the project's own source file, select the corresponding code suggestion tip icon in the editor gutter and choose to apply it to the Project.
Uncheck the linked file, so that the correction should only be made to the project's own file, and click Apply.
The project's own file will only be modified if it was checked (good). The linked file will be modified even though it was unchecked (bad).
I've seen this with multiple suggestions (IDE0018, 19, and 20), so it seems to be a bug in the Preview Changes | Apply logic.
The attached screenshot shows the check state; in this case Utils.cs is a linked file, and is modified when Apply is clicked, even though it shouldn't be.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/422759/code-suggestions-are-applied-to-linked-source-file.html
VSTS ticketId: 762694_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
@mavasani can you check if you can repro this

**Comment by mavasani** [comment]
I am able to consistently repro this - seems like selection choices in FixAll preview changes dialog are not honored for linked files.
