### ISSUE TITLE
QuickInfo on close curly at end of scope block shows too much code

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#325]
Ported from TFS WorkItem: **887257**

------------------------------

**Repro Steps:**

**Affected Branch:** <BR>**Affected Build:** <BR>**Affected Product Language:** <BR><BR>**Steps to reproduce:**<BR><BR>1. Copy/paste C# code:

&nbsp;
<PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><FONT size=2><SPAN style="COLOR: blue">using</SPAN> <SPAN style="COLOR: black">System</SPAN><SPAN style="COLOR: black">;</SPAN>
 
<SPAN style="COLOR: blue">class</SPAN> <SPAN style="COLOR: #2b91af">Program</SPAN>
<SPAN style="COLOR: black">{</SPAN>
    <SPAN style="COLOR: blue">static</SPAN> <SPAN style="COLOR: blue">void</SPAN> <SPAN style="COLOR: black">Main</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">string</SPAN><SPAN style="COLOR: black">[]</SPAN> <SPAN style="COLOR: black">args</SPAN><SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: black">{</SPAN>
        <SPAN style="COLOR: blue">if</SPAN> <SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">true</SPAN><SPAN style="COLOR: black">)</SPAN>
        <SPAN style="COLOR: black">{</SPAN>
            <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
            <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
 
            <SPAN style="COLOR: blue">if</SPAN> <SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">false</SPAN><SPAN style="COLOR: black">)</SPAN>
            <SPAN style="COLOR: black">{</SPAN>
                </FONT><FONT size=2><SPAN style="COLOR: green">/*
                This
                is
                the
                if
                block
                */</SPAN>
            <SPAN style="COLOR: black">}</SPAN>
 
            <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
            <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
 
            <SPAN style="COLOR: black">{</SPAN>
                </FONT><FONT size=2><SPAN style="COLOR: green">/*
                This
                is
                just
                a
                block
                */</SPAN>
            <SPAN style="COLOR: black"><FONT style="BACKGROUND-COLOR: #ff8000">}</FONT></SPAN> <SPAN style="COLOR: green">// ******** Hover on the close curly ********</SPAN>
 
            <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
            <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
 
            <SPAN style="COLOR: blue">for</SPAN> <SPAN style="COLOR: black">(;</SPAN> <SPAN style="COLOR: black">;)</SPAN>
            <SPAN style="COLOR: black">{</SPAN>
                </FONT><FONT size=2><SPAN style="COLOR: green">/*
                This
                is
                the
                for
                block
                */</SPAN>
            <SPAN style="COLOR: black">}</SPAN>
        <SPAN style="COLOR: black">}</SPAN>
    <SPAN style="COLOR: black">}</SPAN>
<SPAN style="COLOR: black">}</SPAN></FONT></PRE>

&nbsp;

2. Hover on the close curly brace on line 34 (<FONT style="BACKGROUND-COLOR: #ff8000">highlighted</FONT> above).

&nbsp;

**Expected:** Less code. Maybe just the **{**, or the **{** and the line immediately after?

**Actual**:
<PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: black">{</SPAN>
<SPAN style="COLOR: #2b91af"><FONT color=#ff69b4>    </FONT>Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
    <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
 
    <SPAN style="COLOR: blue">if</SPAN> <SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">false</SPAN><SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: black">{</SPAN>
        <SPAN style="COLOR: green">/*
        This
        is
        the
        if
        block
        */</SPAN>
    <SPAN style="COLOR: black">}</SPAN>
 
    <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
    <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
 
    <SPAN style="COLOR: black">{</SPAN></PRE>

------------------------------

**Revisions:**

1) Created By David Poeschl (2/19/2014 12:58:04 PM)

It's currently just going to the block's parent, which is usually correct but not in this case.

**Comment by dpoeschl** [comment]
@Pilchie Is this required for 1.0 (stable)? Can we mark this as Up For Grabs instead?

**Comment by Pilchie** [comment]
No, you are right, this can go in Unknown/Up for Grabs
