### ISSUE TITLE
[Proposal] lazy expression and evaluating only-once

### ISSUE THREAD

**Issue by sgjsakura** [dotnet/roslyn#3251]
# Background

In practice, "Evaluate while First Access" is a common requirement in library and application developement, especially in property design. A common simple design model for this requirement may like:

``` C#
public string Data
{
  get
  {
    if (_Data == null)
    {
      _Data = GetData(); // some evaluate method
    }

    return _Data;
  }
}
```

However this method is not perfect because:
1. It's not thread-safe.
2. It requires an explicit field decleration.
3. the comparion with `null` is not safe. (The method may also return null or any other perdefined value).

The `System.Threading.LazyInitializer` helper class give and easier way to create lazy evaluated values with thread-safe lock, however, it still requires declaring and state flag, sync lock and background field.
# Proposal

All of the above items may be implemented by compiler, which can greatly reduce the workload
of developers. For implementation, language may introduce a new "lazy" keyword, which can be applid on any field, property, or even in-line expressions.
## Lazy Expressions

for example:

``` C#
var data = lazy GetMyName();
```

the "lazy" keyword indicate the followed expression should be computed only once using an EnsureInitialized call with one compiler generated state flag and compiler generated backfield value. The generated code may like:

``` C#
// Compiler generated state flag
private bool $Code$_Initialized = false;
// Compiler generated sync lock
private object $Code$_SyncLock = new object();
// Compiler generated backfield with default value
private string $Code$_BackField = default(string);

var data = LazyInitializer.EnsureInitialized($Code$_BackField, $Code$_Initialized, $Code$_SyncLock, ()=>GetMyName());
```

And then the evaluation will be only once, and the subsequent calls of this code snippet will not evaluate the expression again.

The lazy expression can be valid language expressions, and the whole expression will always be wraped with an anomynous (or compiler generated) method. e.g. the expression `lazy (M1() + M2())` is always acceptable.
## Lazy Properties and Fields

The lazy keyword may also be applied on an property, which means the whole 'get' accessor should be wrapped with an lazy expressions. e.g. `public lazy string MyName => GetMyName();` is equivelent to `public string MyName => lazy GetMyName();`. This is especially usefull when the 'get' accessor is complex. Of course lazy properties cannot have a 'set' part.

"lazy" keyword may also applied to fields which contians in-place initializers, it may useful for intialization static fields in a non-thread-safe context. 
# Problems
## Clourses

The most important problem for lazy expressions may be clourse due to introducing local variables. This problems is just the same as LINQ and should be carefully designed. Right now I'm no detailed solution aboue this :-( Limited the keyword application for only on properties and fields may mitigating this problem since they do not generate clourses.
## Lazy Implementation

Beside the `LazyInitializer`, `System.Lazy<T>` is also an alternative lazy evalutation mode. Thus `lazy GetMyName()` can also be converted to `$Code$_Lazy.Value`, where `$Code$_Lazy` is an generated Lazy instance using `new Lazy(()=>GetMyName())`. `LazyInitializer` and `Lazy<T>` are internally different, and lazy expression may choose one of them, or even provide a new implementation.
## Lazy Expression Object

Lazy Expression may be recongnized as two different forms: (1) Simple Right-Value with the same type of lazyed values, e.g. `lazy 1` is recongnized as right value expression with type int. (2) `Lazy<T>` or other equivlent wrapped type, e.g. `lazy 1` will be considered as type `Lazy<int>` in compiling time. The second implementation may cause a lot of addtional problems such as operator overload promotion, nested lazy expression handling, etc. It may also increase the cost for lazy evaluating implementation since developers may have to use `Lazy<T>.Value` to access the real value. However, wrapped type may also introduce some benefits for more complex scenes as shown below.

An alternative handling method similar with string interpolation also can be considered, which means the lazy expression can be explained as either type `T` or type `Lazy<T>`, according to the declared type during assignment. If implicit type infering using keyword `var` is used, the default behavior is recgonized as type `T`. The following code snippet will illuminate this design:

``` C#
string data1 = lazy "123"; // OK
Lazy<string> data2 = lazy "123"; // Also OK
var data3 = lazy "123"; // data 3 is considered as type string
```
## Value Maintenance

Sometimes we may want to discard, update or explicit evaluating the lazy expressions. Under such circumstance, `Lazy<T>` may provide this related features as `Update`, `Discard`, and `Evaluate` methods. The Discard method may internally reset the state flag to make effect. For simple designed lazy expressions (The first design method in the previous section), compiler has to introduce addtional keywords for these features.
## State and SyncLock Sharing

The EnsureInitialized method requires both a state flag and a sync-lock object. In some situations, library designer may share state or sync lock between objects. The `Lazy<T>` type in the 2nd design method may provide some configure methods. However, the lazy expression is not designed for everything, while introducing these features may enhance the difficulty in compiler design,  and thus it may not suitable for implementing them.
## Serialization, etc

Infrastructure for lazy expressions should be carefully considered, and certain CLR level support may also needed.

**Comment by bbarry** [comment]
duplicate? #524

**Comment by sgjsakura** [comment]
@bbarry Seems duplicated in some aspect but lazy expression will be more flexible for lazy property.

P.S. I've searched the word 'lazy' for issues but found nothing :-(

**Comment by emreaydinceren** [comment]
this implementation would be cleaner than #524

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
