### ISSUE TITLE
IntroduceVariableCodeRefactoringProvider ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by nnpcYvIVl** [dotnet/roslyn#32537]
Type a space after the plus symbol then double click the mouse to cause ```IntroduceVariableCodeRefactoringProvider ArgumentOutOfRangeException : 'end' must not be less than 'start'.```

```csharp
namespace IntroduceVariableCodeRefactoringProvider_ArgumentOutOfRangeException
{
    public class Class
    {
        public string Test => "123" +
    }
}
```

I'm using Visual Studio 15.9.5.

**Comment by jinujoseph** [comment]
@JoeRobich  dupe of https://github.com/dotnet/roslyn/issues/27949?

**Comment by JoeRobich** [comment]
@jinujoseph Yes, this one is a duplicate.
