### ISSUE TITLE
Add support for splitting & merging "consecutive" conditional expressions

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#32538]
Followup to #30640

Please allow me to invoke the refactoing on code like this
```c#
        return
            a || b ? "foo" :
            c ? "bar" :
            "foobar";
```
to convert to
```c#
        return
            a ? "foo" :
            b ? "foo" :
            c ? "bar" :
            "foobar";
```
and vice versa.

This might seem like it would make the refactorings unnecessarily more complicated but I suspect that won't be the case thanks to the way the actual if-statement manipulation is abstracted into `IIfLikeStatementGenerator`. I expect this to be fairly easy or at worst take about as much work as #32535 and possibly only require changes in `IIfLikeStatementGenerator` itself.

cc @jasonmalinowski

**Comment by CyrusNajmabadi** [comment]
Nifty!  I assume this would probably be another impl of IIfLikeStatementGenerator?

**Comment by Neme12** [comment]
Hm, I hadn't thought of it that way. I thought we'd just update the existing implementation but having a separate impl altogether sounds like it might be a better idea since you can't freely mix & match the statement & expression forms

**Comment by CyrusNajmabadi** [comment]
Nifty^2!

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
