### ISSUE TITLE
Add support for splitting/merging VB single-line if statements

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#32535]
Followup to #30640 

Some notes:
> > Keep in mind that `If a Then If b Then Console.WriteLine(a AndAlso b) Else Console.WriteLine() Else Console.WriteLine()` is (unfortunately) a valid statement in VB. 
>
> I know. I just spent another hour trying to handle single-line ifs but gave up after realizing that they have the same dangling else problem as C# does, but there's no way to resolve it like in C#.
>
> > I'm not sure we want to bring all the functionality to VB single line ifs,
> 
> I agree. I think the best behavior when encountering a single-line if would be to just convert it to multi-line. I don't think splitting single-line ifs into nested single-line ifs or into single-line else ifs is a good idea.

cc @jasonmalinowski

**Comment by CyrusNajmabadi** [comment]
Closing uot as we are not planning on changes VB experiences.
