### ISSUE TITLE
Use DoNotAllowVarAnnotation.Kind instead of DoNotAllowVarAnnotation.Annotation

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#32567]
I would propose to use `DoNotAllowVarAnnotation.Kind` instead of `DoNoAllowVarAnnotation.Annotation`.

This would allow 3rd party developers to create their own `DoNotAllowVarAnnotation`. Currently, if `csharp_style_var_for_built_in_types` is set to `true` any type with `Simplifier.Annotation` will be simplified to `var` even if a developer intends to keep explicit type.

This change would be consistent with `NavigationAnnotation` which is also `internal` but uses `Kind` property and thus allow anybody to create their own `NavigationAnnotation`.

**Comment by CyrusNajmabadi** [comment]
This would need to go through API review.
