### ISSUE TITLE
Allow use of AdhocWorkspace within custom debug visualizer

### ISSUE THREAD

**Issue by zspitz** [dotnet/roslyn#32568]
**Version Used**: 
Microsoft.CodeAnalysis v. 2.10.0

**Steps to Reproduce**:

1. Create a visualizer that calls `new AdhocWorkspace` on the debuggee side:
```csharp
using Microsoft.CodeAnalysis;
using Microsoft.VisualStudio.DebuggerVisualizers;
using System;
using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Controls;

[assembly: DebuggerVisualizer(typeof(_testVisualizer.TestVisualizer), typeof(_testVisualizer.TestVisualizerDataObjectSource), Target = typeof(System.Linq.Expressions.Expression), Description = "Test Visualizer")]

namespace _testVisualizer {
    public class TestVisualizer : DialogDebuggerVisualizer {
        protected override void Show(IDialogVisualizerService windowService, IVisualizerObjectProvider objectProvider) {
            var data = (TestVisualizerData)objectProvider.GetObject();
            var txt = new TextBlock();
            txt.SetBinding(TextBlock.TextProperty, "Status");
            var window = new Window {
                DataContext = data,
                Content = txt
            };
            window.ShowDialog();
        }
    }

    [Serializable]
    public class TestVisualizerData {
        public TestVisualizerData() { }
        public TestVisualizerData(System.Linq.Expressions.Expression expr) {
            var workspace = new AdhocWorkspace();
            Status = "Success";
        }
        public string Status { get; set; }
    }

    public class TestVisualizerDataObjectSource : VisualizerObjectSource {
        public override void GetData(object target, Stream outgoingData) {
            var expr = (System.Linq.Expressions.Expression)target;
            var data = new TestVisualizerData(expr);
            base.GetData(data, outgoingData);
        }
    }
}
```
2. Write code with the target type of the visualizer:
```csharp
using Microsoft.VisualStudio.DebuggerVisualizers;
using System;
using System.Linq.Expressions;

namespace _testVisualizer {
    class Program {
        [STAThread]
        static void Main(string[] args) {
            Expression<Func<bool>> expr = () => true;

            // this call forces Microsoft.VisualStudio.DebuggerVisualizers.dll to be loaded
            var visualizerHost = new VisualizerDevelopmentHost(null, typeof(TestVisualizer));

            Console.ReadKey(true);
        }
    }
}
```
3. Hover over the `expr` variable, click on the arrow next to the magnifying glass, and select "Test Visualizer"
![Choose the "Test Visualizer"](https://user-images.githubusercontent.com/312166/51334818-4ad7a900-1a89-11e9-8b26-86dda4fc9a40.png)

**Expected Behavior**:

Display the WPF window with data from the serialized visualizer data class:

![screenshot2](https://user-images.githubusercontent.com/312166/51336129-76a85e00-1a8c-11e9-847b-f9c16cf78c26.jpg)

**Actual Behavior**:
A window pops up with the following message:

> Unable to perform function evaluation on the process being debugged.
>
> **Additional information**
>
> The function evaluation requires all threads to run.

![screenshot3](https://user-images.githubusercontent.com/312166/51336291-d69f0480-1a8c-11e9-8ef9-e3001e904db0.jpg)

**Additional information**
I know this is happening at the `AdhocWorkspace` constructor, because a `throw new NotImplementedException()` before the constructor shows a different message, but not after the constructor.

SO post requesting a workaround -- https://stackoverflow.com/questions/54171930/this-function-requires-all-threads-to-evaluate-after-new-adhocworkspace-wi

**Comment by zspitz** [comment]
@vatsalyaagrawal @jinujoseph @tmat I am describing a use case for the code generation features of Roslyn (inside a debugging visualizer), in which there is a problem when calling the  `AdhocWorkspace` constructor. Is it appropriate to label this as "Question"?

The question on SO is "how can I work around this incompatibility?" and is indeed a question. This issue is a request to fix the source of the incompatibility.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
