### ISSUE TITLE
Formatting: space after "delegate" in anonymous methods doesn't respect the "Space between method call and opening parenthesis" option

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#3257]
From: http://connect.microsoft.com/VisualStudio/feedback/details/1391351/inline-delegate-call-should-not-have-space

Assume following code fragment: 

``` C#
var list = new List<object>(); 
list.Sort(delegate(object file1, object file2) { 
return 0; 
}); 
```

In Visual Studio 2012 auto-formatting (Ctrl+K, Ctrl+F) would keep this formatting. In Visual Studio 2015 auto-format changes code to: 

``` C#
var list = new List<object>(); 
list.Sort(delegate (object file1, object file2) { 
return 0; 
}); 
```

Do notice extra space after delegate keyword. 
I would expect auto-format to behave as in Visual Studio 2012 and NOT insert that extra space after delegate keyword. 
Whether delegate has space after or not should be controlled either by "Insert space between method name and its opening parenthesis" (under Tools->Settings->Text Editor->C#->Formatting->Spacing) or a new setting should be created. Space should not be added without configuration especially since given behavior wasn't present in Visual Studio 2012.

_Note_ Let's create a new option here, since most people are used to formatting anonymous methods _with_ a space, but _not_ having a space for method calls.

**Comment by Pilchie** [comment]
I just took another look at this - it turns out that VS2013 just used the "space between method call and opening parenthesis" option here.  People couldn't have been used to having a space, because they couldn't have the app.

**Comment by Pilchie** [comment]
In fact, we now seem to respect the "Insert space between method name and its opening parenthesis" option under "Set spacing for method declarations" set, instead of the "Set spacing for method calls" set.

**Comment by quadban** [comment]
Hi,

I see this item has shifted milestones a couple times now. Is there a new estimate on when it will be included in a public release? My team uses delegates heavily and upgrading to VS 2015 will cause whitespace changes across our codebase, since our delegates up until now do not have a space between "delegate" and the open parenthesis. It is still an issue in VS 2015 Update 2.

Thanks for your response,
Matt

**Comment by CyrusNajmabadi** [comment]
Closing out as unplanned.  First, an anonymous delegate is not in any way a 'method call'.  Second, anonymous delegates were superceded by lambdas, and are much less used now.  We would not invest in this space.
