### ISSUE TITLE
Add support for .razor files

### ISSUE THREAD

**Issue by danroth27** [dotnet/roslyn#32570]
ASP.NET Core 3.0 adds support for Razor Components, a new way to write client-side web UI. Razor Component files are Razor files (like .cshtml files) that get compiled to .NET classes that render to a structured presentation of the DOM. This allows the runtime to efficiently figure out exactly which parts of the DOM need to be updated. Because Razor Components use a fundamentally different compilation model from MVC views/pages they will have a different file extension: .razor.

Broadly speaking we need all our partner teams that special case .cshtml files today to also support .razor files. In .razor files you should get a rich C# editing experience and rich debugging experience in both web and class libraries just like you do with .cshtml files today. We want to land this work to support .razor files in the first update preview of VS2019 so that folks can start trying it out with the new Razor Component support in .NET Core 3.0.

@kendrahavens @rynowak @jinujoseph @heejaechang @jasonmalinowski

**Comment by rynowak** [comment]
To be super clear: the ask is to treat `.razor` the same as `.cshtml`. If you any places in code that special case `.cshtml` based on the file extension then they need to be updated. 

If you have places in code that special case Razor via editor content-type, then that is not impacted and does not need to change.

**Comment by rynowak** [comment]
I did a github search and didn't find any instances of this other than a few unit tests. https://github.com/dotnet/roslyn/search?p=2&q=%22.cshtml%22&unscoped_q=%22.cshtml%22

Most of the occurrences are in comments

**Comment by heejaechang** [comment]
I don't think we care about file extension as long as project system feed that to us like cshtml through you guys to us for closed file FAR. and open file as contained document for now.

**Comment by rynowak** [comment]
Yeah, I'm not aware of any issue, and I didn't find any code in your repo that hardcodes the file extension. So I think that this can be closed if there is nothing to do.

The project system already did the work for for this in their 16.1 branch.

**Comment by CyrusNajmabadi** [comment]
Closing out.  This would go to the razor team.
