### ISSUE TITLE
EnC: support `using` declarations, including asynchronous ones

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#32589]
In C# 8, you can transform a local declaration (`var x = y;`) into a `using` declaration: `using var x = y;`. It works if `y` implements `IDisposable`.
You can even transform it into an `await using` declaration: `await using var x = y;` (if `y` implements `IAsyncDisposable`).

@tmat mentioned this is likely to be tricky for EnC.
FYI @ivanbasov @jinujoseph

**Comment by tmat** [comment]
This is now implemented.

**Comment by jessicah** [comment]
Will this fix scaffolding in Visual Studio? I have code such as:
```
using Stream stream = await httpClient.GetStreamAsync(url);
using StreamReader streamReader = new StreamReader(stream);
using JsonReader reader = new JsonTextReader(streamReader);
```

However, when I try to scaffold an item for ASP.NET Core, like a Controller or View, it fails to complete. When I transform the above code into the previous `using` form, then scaffolding would work again.
