### ISSUE TITLE
QuickInfo should display decoded XML literals

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/roslyn#32595]
**Version Used**: 
Visual Studio 2019 Preview 2 28516.60.d16.0

**Steps to Reproduce**:

1. Create a .NET Core  C# project
2. Write some code that have usages of value tuples such as:
```c#
return (a: 1, b: 2, c: 3, d: 4);
```
3. Mouse over to any of the fields (a, b, c or d)
4. QuickInfo displays the field definition as well as the XML comments summary.

**Expected Behavior**:
The XML comments summary text should correctly display `'s`

**Actual Behavior**:
It displays `&#39;` See the below image, it does not decode the literal (') encoded in XML.

![image](https://user-images.githubusercontent.com/12908526/51365465-45805b80-1a95-11e9-80d8-c9d79bf39d26.png)

**Comment by sharwell** [comment]
> Probably because the XML comments for ValueTuple need to be changed?

Yes, this is correct. It's hard to find specific builds where the documentation for items contains `&amp;#39;`, but if you do find such a case please file a bug against that library. I went ahead and verified that the item shown in the image above is currently correct:

https://github.com/dotnet/coreclr/blob/40bee916727e7b2ef5f1aa99e7e5ce1d345711a8/src/System.Private.CoreLib/shared/System/ValueTuple.cs#L905-L908
