### ISSUE TITLE
"Quick Actions" (Ctrl + .) should offer suggestions for errors in enclosing block (e.g. Implement Abstract Class)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32593]
<p>Currently &quot;Quick Actions&quot; (Ctrl + .) offers suggestions for errors/refactoring on the current line where the cursor is positioned.</p><p>This feature would be monumentally more useful if it offered suggestions regarding errors in the scope of the enclosing code block, for example: Implement Abstract Class error. </p><p>Imagine starting to code this subclass:</p><p>1.  class MyClass : AbstractBase {</p><p>
2.</p><p>3.  }</p><p>Type line 1 and hit enter, indentation and the closing bracket are automatically created and your cursor is on line 2. Now you'll get squiggly line under &quot;MyClass&quot; saying that abstract members must be implemented. Currently, we have to move the cursor back up to line 1 and right underneath &quot;MyClass&quot; in order to benefit from &quot;Ctrl + . &gt; Implement Abstract Class&quot;, whereas it would be a fantastically better UX to be offered &quot;Implement Abstract Class&quot; while the cursor is on line 2. </p><p>For comparision, Android Studio has a similar &quot;alt + enter&quot; shortcut for &quot;Project quick fix (show intention actions and quick fixes)&quot; which offers a nice hierarchical list of suggestions starting with those relevant to the current line, then the current code block, and all the way up to the current document.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/8987/quick-actions-ctrl-should-offer-suggestions-for-er.html
VSTS ticketId: 420981_
_These are the original issue comments:_

Arash Motamedi on 12/25/2016, 04:24 PM (753 days ago): <p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/947-quickactionsuggestion.png">quickactionsuggestion.png</a></p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
