### ISSUE TITLE
do not search symbols in obj folder

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32596]
attempt to navigate to symbol alway hit these autogenerated files in obj folder, please stop doing that

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/6793/do-not-search-symbols-in-obj-folder.html
VSTS ticketId: 413006_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
Design review outcome: We are interested in experimenting with designating items considered generated (under the same rules that analyzers follow) as *External*, allowing the current External Items filter in **Navigate To** to exclude or include these items based on a users wish. @olegtk do you see any reason to not proceed with this?

**Comment by olegtk** [comment]
sounds reasonable to me, I'd personally use it.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
