### ISSUE TITLE
Code transformation results in error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32597]
While trying out the Uint128.cs files from
https://github.com/ricksladkey/dirichlet-numerics Intellisense suggests turning the s0 and s1 fields into auto properties. If I allow it, the transformation leads to uncompilable code, their usage will become unassigned out parameters in many functions below.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/425210/code-transformation-results-in-error.html
VSTS ticketId: 765035_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
cc @mavasani

**Comment by deakjahn** [comment]
Well, I would have expected this to be fixed in VS 2019...

**Comment by CyrusNajmabadi** [comment]
@deakjahn There is no one assigned to work on this.  Would you be interested in contributing a fix?

**Comment by deakjahn** [comment]
Well, you know, I'm the VS user who originally reported this bug and was sent here by the link in the bug report. I've never seen the insides of this code, so I might not be the best candidate to fix it.

**Comment by CyrusNajmabadi** [comment]
Lots of people contribute fixes :)
