### ISSUE TITLE
Implement extension method rewrite for Expanding within conditional access expressions

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#3260]
https://github.com/dotnet/roslyn/pull/3250 implements a defensive fix to bail out on extension method rewrite (`RewriteExtensionMethodInvocation`) if it is within a conditional access expression.

We should replace this defensive fix with actually performing the extension method rewrite. See skipped tests:
1. `CSharp_ExpandExtensionMethodInConditionalAccessExpression`
2. `CSharp_ExpandExtensionMethodInConditionalAccessExpression_2`
3. `VisualBasic_ExpandExtensionMethodInConditionalAccessExpression`
4. `VisualBasic_ExpandExtensionMethodInConditionalAccessExpression_2`

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  We haven't seen a need to do this.
