### ISSUE TITLE
Update nuspec for Microsoft.CodeAnalysis NuGet package

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#32618]
_From @mavasani on January 18, 2019 15:14_

Currently, this NuGet package has a development dependency on version 2.6.1 of Microsoft.CodeAnalysis.Analyzers NuGet package. That version of the analyzers package has a [known bug](https://github.com/dotnet/roslyn-analyzers/issues/1888), that causes an AD0001 diagnostic for large number of code bases. That bug is fixed in the latest version (2.6.3) of Microsoft.CodeAnalysis.Analyzers NuGet package, so we should updating the nuspec for Microsoft.CodeAnalysis to use version 2.6.3

_Copied from original issue: dotnet/roslyn-sdk#243_

**Comment by jinujoseph** [comment]
_From @jmarolf on January 18, 2019 15:32_

`Microsoft.Codeanalysis` nuget is defined in dotnet/roslyn.  This issue should be moved there

**Comment by mavasani** [comment]
@dotnet/roslyn-infrastructure Need some help on this issue - where can I find Microsoft.CodeAnalysis.nuspec that is used to produce our shipping Microsoft.CodeAnalysis.nupkg? The NuGet package needs to be updated to reference latest stable version of Microsoft.CodeAnalysis.Analyzers instead of 2.6.2, which has a known bug causing frequent NRE.

Tagging @shyamnamboodiripad who is hitting the NRE quite often.

**Comment by jasonmalinowski** [comment]
There isn't NuSpec files anymore, some csproj projects just directly produce their own packages. For metapackages there are csproj "projects" under https://github.com/dotnet/roslyn/tree/master/src/NuGet.

**Comment by mavasani** [comment]
Thanks @jasonmalinowski - I just found https://github.com/dotnet/roslyn/blob/a85a21fe9596757c9e3cdb770e86220395ed9b30/src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj#L43, which seems to be bringing in this dependency. Thanks!

**Comment by mavasani** [comment]
Seems that https://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/3.2.0-beta4-final now has an updated dependency: `Microsoft.CodeAnalysis.Analyzers (>= 2.9.3)`
