### ISSUE TITLE
Quick Action ability to Change/Add a prefix to the field variable when adding a parameter to a constructor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32637]
<p>When I am adding another parameter to class constructor and I like, IAprovalResolver approvalsResolver, and press Ctrl+ (Quick Actions). it gives me the option to Create and initialize property 'ApprovalsResolver' or Create and initialize field 'approvalsResolver'.  I usually select the initialize field, but when it does it creates it without any prefix.  I end up with:</p><pre>private readonly IApprovalResolver approvalsResolver;
</pre><p>And in the constructor I get:</p><pre>this.approvalsResolver = approvalsResolver;
</pre><p>I would really like to be able to set a prefix for the field variable.  Our coding standard is to have an _ before field variables.  I want it to end up generating this code: </p><pre>private readlonly IApprovalsResolver _approvalsResolver;</pre><p>And then in the constructor, I would want:</p><pre> _approvalsResolver = approvalsResolver;
</pre><p>Currently, I have to go change it myself and then remove the this</p><p>That is probably the biggest Quick Action that I would like to have control over the code it generates.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/380765/quick-action-ability-to-changeadd-a-prefix-to-the.html
VSTS ticketId: 727649_
_These are the original issue comments:_

Fiona Niu[MSFT] on 11/12/2018, 07:29 PM (66 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>

**Comment by Neme12** [comment]
This is already possible. If you set your naming style to prefer undescore prefix to prviate fields, the refactoring will respect that.

Here's an example of how you can do this in .editorconfig:
https://github.com/terrajobst/minsk/pull/45

You can also set this as a personal setting in Visual Studio in Tools -> Options -> Text Editor -> C# -> Code Style -> Naming. These preferences will take affect on code bases that don't have an .editorconfig.

**Comment by erenken** [comment]
@Neme12 thank you very much.  Setting the naming style worked.  I was wondering if changing that would work, but I couldn't find it in the see of settings.  

This was my original feedback on Visual Studio.  I am going to try the .editorconfig setting.

**Comment by CyrusNajmabadi** [comment]
Closing this out as this works when setting naming styles.
