### ISSUE TITLE
Be able to write notes/comments in the code without requiring rebuild

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32639]
<p>I'm not even asking for modifying the pdb to reindex lines if necessary (though that would be cool).  I'm just saying to have a temporary comment object that is not inserted into the code, which could be then converted to source code comments when the code stops executing or when the developer wants it to be converted.</p><p>Use case:</p><p>Trying to keep track of what a large code base does and why is complex.  Yes, we could write notes at some other location, but then they can get lost, mislabeled, etc and then have to be typed/copied in afterwards, requiring to open the file again, find the line and copy from the notes.</p><p>Having the ability to put a note down at some location in the code and not have it result in the debugger complaining that the source code has changed and then have them able to convert to proper source code comments when the developer wants would be of <b>immense</b> value. </p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/376672/be-able-to-write-notescomments-in-the-code-without.html
VSTS ticketId: 724712_
_These are the original issue comments:_

Fiona Niu[MSFT] on 11/7/2018, 01:07 AM (72 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>

**Comment by gafter** [comment]
This is not a compiler feature request.  It is an IDE feature request.  The closest thing to the requested feature is the already available `Stash` feature on the `Changes` page of the `Team Explorer`.  You can save code comment changes there, but apply them later.

**Comment by gafter** [comment]
Approximations to this request are already available as part of edit-and-continue.

**Comment by Ma-XX-oN** [comment]
Hi @gafter,

You're right, but only when edit-and-continue work, which doesn't for many projects, esp complex ones.  I work with a very complicated, multiproject solution that is 20+ years old and it is very inconvenient when I am trying to document what is going on.  If edit-and-continue did work, this would be a non-issue.

**Comment by CyrusNajmabadi** [comment]
Would like to bring this to next design meeting to see if this is out of scope for Roslyn and should be something the editor could provide.

**Comment by Ma-XX-oN** [comment]
I'd be totally for it being an editor change as that is how I envisioned it when I first reported it in the Developer Community.  I never even thought of this as a compiler change.  I just want to be able to document the code easily and be able to embed the documentation as comments after finishing debugging.

**Comment by CyrusNajmabadi** [comment]
Closing out as out-of-scope for roslyn.
