### ISSUE TITLE
12% of opening a document is Roslyn overhead

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#32669]
**Version Used**: 
Version 16.0.0 Preview 3.0 [28517.116.d16.0stg]

**Steps to Reproduce**:

1. `> git clone http://github.com/dotnet/project-system`
2. `> cd project-system`
3. `project-system> build.cmd`
4. `project-system> ProjectSystem.sln`
5. File -> Open -> File
6. In project-system\src, search for ext:"cs"
7. Select All to selected all files
8. Open 

6% of the CPU time is just calling GetService over and over again. The overhead is almost all due the JoinableTaskFactory.Run call underneath inside VS's global service provider.
![image](https://user-images.githubusercontent.com/1103906/51453456-a8266f80-1d93-11e9-91f3-5fe87ddd9bd5.png)

This line should be cached: https://github.com/dotnet/roslyn/blob/a6bc53bee0fbc893ec5e24c97fc2b510a86a6953/src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractPackage%602.cs#L121.

**Comment by davkean** [comment]
There's another lookup in VisualStudioWaitIndicator.StartWait as well, which only uses it to find `VisualStudioWorkspace`, it can skip the GetService for that and just import VisualStudioWorkspace directly in the constructor.

**Comment by jasonmalinowski** [comment]
@davkean Did you by chance have the "Find in Files" window open? There's a path where it queries the language service for the block to say "search in current block". That's what it shows is happening on that stack, which is most unexpected.

**Comment by jasonmalinowski** [comment]
Not that we can't cache that; I just wouldn't expect that to be happening ever.

**Comment by davkean** [comment]
I had zero source files open before I did this.

**Comment by sharwell** [comment]
@AArnott can you check if the build mentioned above includes your changes to reduce contention in JTF?

**Comment by sharwell** [comment]
📝 It looks like this is actually a bug in `IVsFindTarget.GetCapabilities`, which calls `GetCurrentBlock` only to discard the result.

**Comment by davkean** [comment]
I'm changing this bug to represent all the unneeded overhead in opening a document:

![image](https://user-images.githubusercontent.com/1103906/111420064-a58aef00-873e-11eb-84eb-02de86326cba.png)

**Comment by sharwell** [comment]
@davkean per https://github.com/dotnet/roslyn/issues/32669#issuecomment-456610448, none of the methods highlighted in that trace are used. The methods are called, and the results are immediately discarded.

**Comment by davkean** [comment]
The call is expensive because its doing silly things; god help we make GetCurrentBlock cheaper.

**Comment by sharwell** [comment]
> god help we make GetCurrentBlock cheaper

We can make it cheaper, but not free, and free is the target. Lack of caching the service is only a small minority of the problematic time in the previous image. What's the breakdown inside the call to `Wait`?

**Comment by CyrusNajmabadi** [comment]
@sharwell @davkean is there remaining work to be done here?

**Comment by sharwell** [comment]
This was fixed by the editor for 16.10.
https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/315775?_a=files
