### ISSUE TITLE
Cannot build latest roslyn

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#32676]
I'm getting:

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(126,5): error : The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0.
```

**Comment by CyrusNajmabadi** [comment]
@jaredpar @jasonmalinowski can you advise?  Thanks!

**Comment by agocke** [comment]
I hit this as well -- my solution was to install the SDK listed in the contributor documents

**Comment by agocke** [comment]
https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md#developing-with-visual-studio-2017

**Comment by CyrusNajmabadi** [comment]
Thanks!  I'll try that.  Is there some reason we can't just make the Restore script do this?  Or check for this and give the right advise on how to fix things?

**Comment by agocke** [comment]
No idea, sorry

**Comment by CyrusNajmabadi** [comment]
Closing out as @agocke 's solution fixed this.  Thanks!
