### ISSUE TITLE
CodeRefactoring in nuget package doesn't work

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#32705]
**Version Used**: Microsoft.CodeAnalysis 1.0.0

**Steps to Reproduce**:

1. Install the nuget package for my Serilog Analyzer https://github.com/Suchiman/SerilogAnalyzer from https://www.nuget.org/packages/SerilogAnalyzer
2. Attempt to invoke a CodeRefactoring like the ShowConfigCodeRefactoringProvider like shown here https://github.com/Suchiman/SerilogAnalyzer#refactors

**Expected Behavior**:
Works as in the gif

**Actual Behavior**:
Nothing happens, Analyzers and CodeFixes work fine but CodeRefactorings only work in the VSIX version.

**Comment by Suchiman** [comment]
Minutes later @jmarolf responded on gitter
> today refactorings are only installable as VSIXes because they are a VS only thing (the user must interact with them in the IDE).  Codefixes coming along woth analyzer fell out of the fact that you want analyzers to run on your commandline build so you want them to install via nuget.  You don't want to clone a repo, build it, get errors/warnings from analyzers and then need to install separate VSIXes to be able to fix these quickly.  Because of this we build the infrastructure to load Codefixes from nuget packages.  We couldn't construct a scenario for why refactorings installed via nuget would be a good thing

so in that case, i'd like to raise this as a feature request as i don't see a good reason not to do this. Otherwise my users would have to install the nuget package for build time checks and the vsix package for additional code refactorings or rewrite the code refactorings as analyzer + codefix pair that raise an invisible diagnostic. IIRC @sharwell told me nuget is the preferred distribution mechanism anyway.

**Comment by mavasani** [comment]
Tagging @heejaechang 

I believe [this type](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/CodeFixes/CodeFixService.ProjectCodeFixProvider.cs,17) needs to be extended to extend to work for CodeRefactorings, currently it only detects CodeFixes. Additionally, the CodeRefactoringService needs to be extended to compute per-project refactorings, just like the CodeFixService computes per-project fixers [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/CodeFixes/CodeFixService.cs,700).

**Comment by jasonmalinowski** [comment]
Removing Design Review tag because the belief was this wasn't really a design problem and more just a code problem that needs to be fixed.
