### ISSUE TITLE
CompilationOptions.Features is unintentionally part of the "public" API

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#3270]
See https://github.com/dotnet/roslyn/blob/stabilization/src/Compilers/Core/Portable/Compilation/CompilationOptions.cs#L190

The property `CompilationOptions.Features` is part of the "public" API because it is `protected internal`, even though there is no supported way to use or extend it outside Roslyn. We discovered recently that it has the "wrong" type for its internal uses.

Please remove this from the "public" API by making it `internal`.

**Comment by jaredpar** [comment]
The method `CommonWithFeatures` should be removed as well.

**Comment by gafter** [comment]
None of the "common" APIs should be publicly visible

-Neal

On Jun 2, 2015, at 5:20 PM, Jared Parsons <notifications@github.com<mailto:notifications@github.com>> wrote:


The method CommonWithFeatures should be removed as well.

-

**Comment by jaredpar** [comment]
Issue #3287 tracks this now.
