### ISSUE TITLE
After configuration change in desktop csproj, project.OutputFilePath still points to old output path

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#32711]
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 Int Preview Version 16.0.0 Preview 2.0 [28522.59.d16.0]

**Steps to Reproduce**:
We have a solution-crawler based analyzer (for source-based unit test discovery)  that detects and reacts to project configuration changes via the `IIncrementalAnalyzer.AnalyzeProjectAsync(Project project, bool projectConfigurationChanged, CancellationToken token)` API.

In a desktop csproj, after a solution-wide configuration change (i.e. change Debug -> Release in VS drop-down), the solution crawler correctly calls the above method on our analyzer with `projectConfigurationChanged = true`. However `project.OutputFilePath` points to the old (Debug) output path instead of the new (Release) path.

On debugging, looks like `project.Solution.Workspace.CurrentSolution.Projects.First().OutputFilePath` is also set to the old (Debug) path. So looks like the output path is not being updated in Roslyn's internal project system abstractions after a configuration change.

**Expected Behavior**:
`project.OutputFilePath` should point to the new (Release) output path.

**Actual Behavior**:
`project.OutputFilePath` still points to the old (Debug) output path.

**Comment by shyamnamboodiripad** [comment]
FYI @jasonmalinowski - could this have something to do with your 16.0 changes to `OutputFilePath` (as part of the async loading changes).

Also tagging @heejaechang @peterwald

**Comment by jasonmalinowski** [comment]
Do you see this with CPS projects? Or is it just the legacy projects?

**Comment by shyamnamboodiripad** [comment]
Just tried a CPS project - looks like the path change is being reflected correctly for CPS projects. So this is only broken for legacy projects. (cc @peterwald)
