### ISSUE TITLE
Watch for anonymous type member has invalid syntax

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#3272]
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

class Program
{
    static void Main(string[] args)
    {
        var inner = new { A = 1, B = 2 };
        var outer = new { C = (object)inner };
        System.Diagnostics.Debugger.Break();
    }
}
```

1. Run to breakpoint
1. Expand ```outer``` and then ```C``` in the Locals window
1. Add watch on ```B```.

Expected: Expression that evaluates to value of ```Outer.C.B```.
Actual: ```((<>f__AnonymousType0<int, int>)outer.C).A	(1,3): error CS1525: Invalid expression term '<'```

Note: Dev12 emits the same watch expression but is able to compile it.

**Comment by amcasey** [comment]
@cston I vaguely recall that the lexer once accepted such identifiers in debugger mode.  Do you remember if/why we pulled that out?

**Comment by cston** [comment]
Removed in 7683a0a74 since we weren't aware of a scenario where it was needed.

**Comment by tmat** [comment]
I don't think we should parse such expression. Couldn't we produce an Object Id for the instance? $n would then be typed to the runtime type.

**Comment by jaredpar** [comment]
IIRC that expression was only parsable in the watch window because of the exact scenario that @amcasey laid out here.  The intent was not to support users directly writing out the type.

**Comment by cston** [comment]
I agree with @tmat that we should not parse the syntax, in part because that would limit future additions to the language. If we can't produce an object id easily, could we disable "Add Watch" for these cases insted?

**Comment by cston** [comment]
I agree with @tmat that we should not parse the syntax, in part because that would limit future additions to the language. If we can't produce an object id easily, could we disable "Add Watch" for these cases instead?

**Comment by KevinH-MS** [comment]
Returning null or string.Empty for the full name in these cases (effectively disabling "Add Watch") would seem reasonable to me, although I'm not sure it's a significantly better user experience than what we have today.  I'd vote for:  "make it work with object ids or just leave it as is..."

**Comment by jaredpar** [comment]
Curious: under what circumstances is the full named queried for today?  In the old EE it would be called for every single object displayed (and many which weren't actually visible to the user).  

If that's the case in the newer EE then I'm not sure how "Add Watch" could work.  The code would be forced to create an object ID for every anonymous type expansion.  Seems like that could get a bit large in certain apps.  If it's done more on demand though then object ids seem like a good option.  

Another consideration is to insert custom metadata into the full name.  Essentially for unparsable strings, insert a header which tells the EE the string needs to be parsed in a different mode.  This is how VB used to handle similar situations in the EE.

**Comment by KevinH-MS** [comment]
We only get called for the objects being displayed, but that's a good point.  The object id approach may lead to considerable bloat, because object ids don't normally go away when the object is out of scope.

We've avoided putting special syntax in the full name thus far, but that's another approach worth considering.

**Comment by amcasey** [comment]
I'm not sure the EE has a way to trigger Add Watch - I believe that's handled by the debugger UI.

I seem to recall that there are already nodes that don't support Add Watch, so there's probably an existing mechanism.

**Comment by amcasey** [comment]
I'll see what it would take to disable Add Watch.

**Comment by amcasey** [comment]
Looks like we just need to set FullName to null to suppress the action.  Maybe we could bail out of the FullName computation if we see a mangled name and then just return null.

**Comment by amcasey** [comment]
That works.  I'll fix both languages and add tests.

**Comment by amcasey** [comment]
Snag: We don't consistently null-check parent FullNames.  I haven't seen it fail yet, but I wouldn't be surprised if it did.

**Comment by amcasey** [comment]
@cston can you please verify?
