### ISSUE TITLE
Enhanced colors feedback.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#32723]
Overall i like it.  Feels like vscode (which is good).  One thing i don't like at first blush is the bolded statics.  They just make things feel 'off balance' without there being a good reason for it.

i.e. 'bold' is generally used for emphasis or impact.  But i see no reason (and do not feel good about) statics having that.  This is quite likely because static stuff is generally *less* important to me.  It's stuff like helpers.  Or utilities.  And it ends up feeling like it's *more* important despite being stuff i care far less about.

Thanks!

**Comment by JoeRobich** [comment]
@CyrusNajmabadi Thanks for opening this issue and thanks for your feedback!

**Comment by CyrusNajmabadi** [comment]
FYI, i gave this a couple of days to see if i got used to this.  And i definitely have *not*.  Love the new colors . Hate the bolding.  Cheers! :)

**Comment by CyrusNajmabadi** [comment]
Here's another oddity in this area:

![image](https://user-images.githubusercontent.com/4564579/51792885-a16d7300-216c-11e9-95d7-a8df0564749f.png)

Notice that `FormattingOptions` is bold (because it's a static type), but `CancellationToken` is not (since it's a normal struct.  However, this feels *very* inconsistent since it's not the *declaration* of the type that matters here, but how it is used instead.  In both cases, i'm accessing a static member, so i'm accessing the *static* side of the type.

**Comment by JoeRobich** [comment]
Just to update this. We are no longer bolding statics by default in preview 3. You can still enable this via Tools > Options > Fonts and Colors  `Symbol - Static` classification.

**Comment by CyrusNajmabadi** [comment]
Awesome thanks!
