### ISSUE TITLE
Error message for pattern-based using in C# 7.3

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#32728]
**Version Used**: 

Visual Studio 2019 Preview Version 16.0.0 Preview 2.0
LangVersion latest (C# 7.3)

**Steps to Reproduce**:

```cs
using System;

class Program
{
    static void Main()
    {
        var y = Console.ReadLine() switch { _ => 0 };
        // ↑ CS8370  Feature 'recursive patterns' is not available in C# 7.3. Please use language version 8.0 or greater.

        using (var x = new X()) { }
        // ↑ CS1674  'X': type used in a using statement must be implicitly convertible to 'System.IDisposable'
        // Why not CS8370?
    }

    ref struct X { public void Dispose() { } }
}
```

**Expected Behavior**:

CS8370 error in line 10.

**Actual Behavior**:

CS1674

**Comment by jcouv** [comment]
@chsienki Are we missing a language version check?

**Comment by chsienki** [comment]
We do the check, but just don't attempt to look up if its langver < 8, which results in the same error as before.

Presumably it would be considered a breaking change if we reported a different error when targeting a lesser langver?

**Comment by jcouv** [comment]
Hum, technically, we should always bind with latest understanding of the language (rather than bind conditionally based on language version), so this may be a bug. The only thing that should be different is the diagnostic, but we should bind the same way regardless of language version.
