### ISSUE TITLE
Linked file with rooted path with '..' shows up in Miscellaneous Files

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#32730]
**Version Used**: 15.9.5, 16.0 Preview 2

**Steps to Reproduce**:

1. Create a csproj C# project (was not able to reproduce with the new project system)
2. Link a source file using a rooted file path containing a `..`, e.g.:

        C:\Users\sam\source\repos\ConsoleApp1\ConsoleApp1\..\Source\Program.cs

3. Reload the project and open the source file

**Expected Behavior**:

The file shows up as part of the project.

**Actual Behavior**:

The file opens in the **Miscellaneous Files** workspace.

🔗 Originally filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/132040

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to do this, we should create an issue with a milestone and do it.
