### ISSUE TITLE
Breaking change in switches over a boolean value

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#32732]
**Version Used**: 

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 2.0
VisualStudio.16.Preview/16.0.0-pre.2.0+28522.59
Microsoft .NET Framework
Version 4.7.03056

**Steps to Reproduce**:

Compile and run the following code:
```cs
using System.Runtime.InteropServices;

class C
{
  [StructLayout(LayoutKind.Explicit)]
  public class M
  {
    [FieldOffset(0)]
    public bool b;

    [FieldOffset(0)]
    public int i;
  }

  static void Main()
  {
    var b = new M() { i = 42 }.b;
    System.Console.WriteLine(Test(b));
  }

  static int Test(bool b)
  {
    switch(b)
    {
      case true: return 1;
      case false: return 2;
      default: return 3;
    }
  }
}
```

**Expected Behavior**:
The code should print `3` as it does now in VS2013-2017 and VS 2019 preview 1.

**Actual Behavior**:
The code prints `1` since VS 2019 preview 2.

**Comment by gafter** [comment]
We do not "support" boolean values that contain values other than `true` and `false` (such as 42).  I'll add documentation to the effect that such code has undefined behavior.

**Comment by TessenR** [comment]
FYI this is still a breaking change even without undefined behavior as the following code compiles fine in VS2017 but does not compile in VS2019
```cs
using System;

class C
{
    public const bool A = true;
}

class B
{
    public bool A;
}

class D
{
  void M(Func<C, int> f) { }
  void M(Func<B, int> f) { }
    
  void Test()
  {
    // the call becomes ambigouous when you update the compiler
    M(C => 
      {
          switch (C.A)
          {
              case true: return 1;
              case false: return 2;
          }
      });
  }
}
```
