### ISSUE TITLE
Support additive classifications in ClassifiedSpans and TaggedText 

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#32770]
Currently ClassifiedSpans and TaggedText can be tagged with a single classification. Now that we added the additive classification Static Symbol the same span or text could have two classifications. We should handle this gracefully.

**Comment by JoeRobich** [comment]
Remove AdditiveClassification filters added by https://github.com/dotnet/roslyn/pull/34315

**Comment by CyrusNajmabadi** [comment]
Closing out as this doesn't identify an actual place where we need to do anything.  AFAICT, lsp understands this case and handles it properly.
