### ISSUE TITLE
Consider making IHostDiagnosticAnalyzerPackageProvider public

### ISSUE THREAD

**Issue by nosami** [dotnet/roslyn#3277]
.... and `HostDiagnosticAnalyzerPackage` so that OmniSharp could provide global analyzers in a similar fashion to VS's vsix analyzer packages.

http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.Features/Diagnostics/IWorkspaceDiagnosticAnalyzerProviderService.cs,3afe074625cf41cc

**Comment by Pilchie** [comment]
Tag @DustinCampbell

**Comment by sandyarmstrong** [comment]
In https://github.com/dotnet/roslyn/pull/39956, this class was renamed to `IHostDiagnosticAnalyzerPackageProvider`.

**Comment by KirillOsenkov** [comment]
In https://github.com/dotnet/roslyn/pull/43009, this class seems to have been completely removed.

@tmat can this issue be closed now, unless I'm mistaken?

**Comment by tmat** [comment]
Global analyzers can be referenced from Solution now.
