### ISSUE TITLE
Overload Resolution Error

### ISSUE THREAD

**Issue by TylerBrinkley** [dotnet/roslyn#32787]
**Version Used**: VS 15.9.6

**Steps to Reproduce**:

```c#
class Program
{
    static void Main(string[] args)
    {
        Derived derived = new Derived();
        ulong value = 10;
        derived.Write(value);
    }
}

public class Base
{
    public void Write(ulong value) => Console.WriteLine("ulong");
}

public class Derived : Base
{
    public void Write(object value) => Console.WriteLine("object");
}
```

**Expected Behavior**:
"ulong" would be written to the console.

**Actual Behavior**:
"object" is written to the console.

**Comment by gafter** [comment]
@TylerBrinkley Is your expectation based on reading the relevant portion of the language specification?  In https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#overload-resolution we read

> methods in a base class are not candidates if any method in a derived class is applicable

and in https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#method-invocations we read

> The set of candidate methods is reduced to contain only methods from the most derived types

**Comment by TylerBrinkley** [comment]
@gafter Thanks, you're right. I guess it'd be nice if the language spec was updated to allow this but I suppose there could be other issues created doing that.

**Comment by gafter** [comment]
If the language spec were updated to allow that many existing programs would change behavior. That would be a disaster.
