### ISSUE TITLE
After upgrading from VS 2019 preview1 to preview2 some code related to Nullable References stop working

### ISSUE THREAD

**Issue by YandyZaldivar** [dotnet/roslyn#32786]
**Version Used**: 

Visual Studio 2019 preview 2

**Steps to Reproduce**:

```csharp
public object? TestA() => default;
public T? TestC<T>() where T: class => (T?)TestA();
public T TestB<T>() => (T)TestA();
```

![image](https://user-images.githubusercontent.com/13922845/51747872-b10b8f80-2078-11e9-8db2-9ecfe0e166f3.png)

**Expected Behavior**:

`TestB` should work.

**Actual Behavior**:

`TestB` shows compile time error.

**Comment by jcouv** [comment]
That's expected. 
If `T` were `string` (ie. non-nullable), then this would convert a `null` (from `TestA`) to a non-nullable `string`.
A suppression `(T)TestA()!` should silence that warning, but it's possible there's a bug on that (fixed in preview4).

**Comment by jcouv** [comment]
Just to be sure, I went to check our spec: 
> Explicit cast [...] may produce a W warning.

https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-reference-types.md#explicit-cast

**Comment by YandyZaldivar** [comment]
@jcouv thanks for the answer, but shouldn't be unconstrained `T` equivalent to `object?` by default on a nullable reference context?

I can't add a suppression as you suggest in `(T)TestA()!`, because I want it to also return `null` depending on the type of `T`.

How do we address the case where `T` could be `int`, `int?`, `string`, `string?` (nullable and non-nullable, class and struct) and work for every case? Or, is there any annotation or constraint I can set on `T` to be able to return either `int`, `int?`, `string`, `string?` in a construction like `T Test<T>()` ?

![image](https://user-images.githubusercontent.com/13922845/52026473-fba46600-24d5-11e9-8596-427008890675.png)

Why this was working for me in VS2019 preview 1 and stop working on preview 2?

Why `TestD` works and `TestE` doesn't in the following code?

```csharp
public T TestD<T>(IEnumerable<T> items) => items.FirstOrDefault();

public T TestE<T>(IEnumerable<T> items)
{
    if (items.Count() > 0)
        return items.First();

    return default;
}
```

![image](https://user-images.githubusercontent.com/13922845/52023488-45d41a00-24cb-11e9-9fd7-86b573b03df3.png)

**Comment by jcouv** [comment]
I'll think about this more.

> Why this was working for me in VS2019 preview 1 and stop working on preview 2?

As is expected with previews, including C# 8.0 beta, many things are still changing. 
I don't know specifically which change caused this change. We did a deep re-work of analysis of unconstrained types parameters like `T`.
