### ISSUE TITLE
Removing leading/trailing brackets

### ISSUE THREAD

**Issue by rmnblm** [dotnet/roslyn#3278]
I'm trying to get the body of a method (without leading and trailing braces). Either the `ToString()` method on the BlockSyntax object is not working nor both methods `WithoutLeadingTrivia()` and `WithoutTrailingTrivia()`. When debugging, both properties `HasLeadingTrivia`and `HasTrailingTrivia`are `true`.

Am I doing something wrong?
    
    var syntaxTree = CSharpSyntaxTree.ParseText(code);
    var syntaxRoot = syntaxTree.GetRoot();
    var method = syntaxRoot.DescendantNodes()
        .OfType<MethodDeclarationSyntax>()
        .FirstOrDefault(m => m.Identifier.Value.ToString() == "SomeMethod");
    return method.Body.WithoutLeadingTrivia().WithoutTrailingTrivia().ToString();

Any help is appreciated! :smiley:

**Comment by Pilchie** [comment]
Braces are not considered trivia - they are actually tokens that are syntactically important to the structure of the code.

Trivia is for things that are ignored by the lexer and parser - whitespace, comments and preprocessor directives for example.

**Comment by rmnblm** [comment]
And how can I effectively remove leading and trailing brackets (tokens)?

**Comment by whoisj** [comment]
`.Trim('{','}')`?

**Comment by Pilchie** [comment]
From the string, or from the tree?  What is the larger task you are trying to accomplish?

**Comment by rmnblm** [comment]
@whoisj It's not that easy what I'm trying to accomplish.
@Pilchie My task is the following: I'm trying to read the body of a method

    public string DoSomething() {
        return string.Empty;
    }

What I want is the body `return string.Empty;` w/o any leading or trailing brackets, tabs, whitespaces and so on. Of course I can do `.ToString().Trim('{', '}').Trim();`to remove everything. This works actually fine.
The next task is, I want to edit the body and set it to the method.
Let's say I want to replace `return string.Empty;`with `return "Test";`. This also works fine except that I'm getting this

    public string DoSomething() {
        return "Test";}

(Notice that the trailing bracket is on the same line like the method body.)

**Comment by rmnblm** [comment]
I'm doing the replacement of the body with following code snippet

    var oldBody = method.Body;
    var newBody = SyntaxFactory.Block(SyntaxFactory.ParseStatement(bodyString))
        .WithOpenBraceToken(oldBody.OpenBraceToken)
        .WithCloseBraceToken(oldBody.CloseBraceToken);

**Comment by Pilchie** [comment]
Where is this code running?  Do you have access to the `Workspace` layer?  If so, you should follow your re-write with a call to the `Microsoft.CodeAnalysis.Formatting.Formatter` to fix that sort of issue.

Alternatively, you don't create a new Block, instead use [`BlockSyntax.WithStatements`](http://source.roslyn.io/Microsoft.CodeAnalysis.CSharp/a.html#7600b1e7619ed3e2)

Note: Unfortunately trivia processing is often one of the trickiest parts of doing this sort of re-write.

**Comment by rmnblm** [comment]
I'm already formatting the code with a Formatter

    var cw = MSBuildWorkspace.Create();
    cw.Options.WithChangedOption(CSharpFormattingOptions.IndentBraces, true);
    cw.Options.WithChangedOption(CSharpFormattingOptions.IndentBlock, true);
    cw.Options.WithChangedOption(CSharpFormattingOptions.NewLinesForBracesInMethods, true);
    cw.Options.WithChangedOption(CSharpFormattingOptions.NewLinesForBracesInTypes, true);
    var formattedNode = Formatter.Format(syntaxRoot.ReplaceNode(method,method.ReplaceNode(oldBody, newBody)), cw);

When using the `BlockSyntax.WithStatements` method, the resulting body is empty.

    var syntaxList = new SyntaxList<StatementSyntax>();
    syntaxList.Add(SyntaxFactory.ParseStatement(body));
    var newBody = method.Body.WithStatements(syntaxList);

**Comment by Pilchie** [comment]
`SyntaxList` is an immutable type.  `Add` returns a new list with the changes, but the original list is not modified.

Same thing with your option changes above.  They aren't affecting the options object you are passing in, they return a new `OptionSet` with the value changed.

**Comment by rmnblm** [comment]
You're right. I always forgot that they're immutable types. I'm getting closer to what I want. 
The only problem I now have is that when parsing a multiline body.

    public string DoSomething() 
    {
        string t = string.Empty;
        string s = string.Empty;
        return t;
    }

After replacing the body, the `.ToString()`method returns

    public string DoSomething() 
    {
        string t = string.Empty;
    string s = string.Empty;
    return t;
    }
