### ISSUE TITLE
Instructions for automatically deploying .nupkg are out of date

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#3279]
The instructions in the ReadMe.txt file in the "Analyzer with Code Fix (NuGet + VSIX)" project template say that if you want to automatically deploy the .nupkg file to your local feed, you should edit the "Post-build event command line" box in the project properties. But since #3026 was fixed, the project file in the template doesn't use a post-build event; it uses an AfterBuild target. You have to edit the project file directly instead of using the project properties UI (which is fine, but the documentation needs to be updated).

**Comment by jmarolf** [comment]
Closed with internal Changeset 1483043

**Comment by lgolding** [comment]
Verified as fixed
