### ISSUE TITLE
Extension methods in method groups when using static imports

### ISSUE THREAD

**Issue by matkoch** [dotnet/roslyn#32798]
```
using static A;

public static class A
{
    public static bool M(string path) // add 'this' modifier here
    {
        return true;
    }
}
public static class B
{
    static void Main()
    {
        var list = new string[0];
        list.Where(M);
    }
}
```

**Expected behavior**

Adding `this` has no impact whether `M` can be used as method group.

**Actual behavior**

Compile error. Note that fully qualifying the method with `A.M` fixes the error.

**Comment by gafter** [comment]
By design.  From https://github.com/dotnet/csharplang/blob/master/spec/namespaces.md#using-static-directives

> Within member declarations in a compilation unit or namespace body that contains a using_static_directive, the accessible nested types and static members (**except extension methods**) contained directly in the declaration of the given type can be referenced directly.

(emphasis added)

**Comment by matkoch** [comment]
@gafter this is a very surprising design decision, given that extension methods are considered to be just normal static methods, which _can_ be called like instance methods. Why should adding a `this` modifier break existing code?
