### ISSUE TITLE
Banner of "Add file banner" filename  refactoring in the header should replaced with the target filename

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32792]
When I execute "Add file banner" (even with disabled ReSharper 2018.3.1), I always get the following file banner:

```csharp
//-----------------------------------------------------------------------
// <copyright file="MfctCommandHandler.cs" company="Fubar Development Junker">
//     Copyright (c) Fubar Development Junker. All rights reserved.
// </copyright>
// <author>Mark Junker</author>
//-----------------------------------------------------------------------
```

The problem is two-fold:

1. It always inserts `MfctCommandHandler.cs` as file - even though I tried to add it to a different file
2. I'd like to reconfigure the banner to something like the following:

```csharp
// <copyright file="LangCommandHandler.cs" company="Fubar Development Junker">
// Copyright (c) Fubar Development Junker. All rights reserved.
// </copyright>
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/435193/banner-of-add-file-banner-code-fix-is-not-configur.html
VSTS ticketId: 776909_
_These are the original issue comments:_

Mark Junker on 1/24/2019, 03:35 AM (31 hours ago): <p>The `&lt;`/`&gt;`, etc... seems to be an encoding problem with issues sent over the "Visual Studio Feedback" tool.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
Design review outcome: if `FileName.cs` appears in the header of a file **FileName.cs**, then the filename in the header is replaced with the target filename when using the "Add file banner" refactoring. We are considering a configurable analyzer for this feature as a separate/future feature.
