### ISSUE TITLE
Go to definition fails on GetChar() in Scanner.vb

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#328]
Where is [GetChar()](https://github.com/dotnet/roslyn/blob/6f53207a6f0c20db549b303cc37b4473ef3e7a83/src/Compilers/VisualBasic/Portable/Scanner/Scanner.vb#L440) defined?

**Comment by JoshVarty** [comment]
Is this what you're looking for? 

http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Scanner/ScannerBuffer.vb,137

**Comment by Pilchie** [comment]
I think @AdamSpeight2008 means [GetChar](https://msdn.microsoft.com/en-us/library/4dhfexk4%28v=vs.90%29.aspx) from the VB runtime.  That is not (yet) Open Source.

**Comment by AdamSpeight2008** [comment]
@Pilchie I actually wanted referenced by @JoshVarty 
GoTo Definition won't work on the method.

**Comment by Pilchie** [comment]
Doh, My bad.  I'll convert this to a bug tracking why Go To Definition doesn't work there.  (I suspect it's related to the VB Runtime helper though).

**Comment by balajikris** [comment]
Hmm.. seems to work for me in more recent Roslyn bits. Navigates to the definition in ScannerBuffer.vb.
