### ISSUE TITLE
Switch Expression Exhaustiveness needs to be conditions on langver

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#32806]
```C#
namespace ConsoleApp1
{
    class Program
    {
        static int Main(string[] args)
        {
            bool? test = null;

            switch (test)
            {
                case true:
                    return 1;
                case false:
                    return 0;
                case null:
                    return -1;
            }
        }
    }
}
```

This code currently compiles in a brand-new C# project on dev16, but will not compile with an older 7.x roslyn compiler because it did not do the exhaustiveness checking that the new compiler will do. We need to condition this on langver 8.

**Comment by gafter** [comment]
@333fred You can work around this compiler bug by adding `when true` to one of the cases of your switch.  That will be accepted by both the old and new compilers.
