### ISSUE TITLE
Absent Public API 

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#32834]
The following public api isn't in either of the PublicAPI files.
```vbnet
Public Shared ReadOnly Property [Default] As VisualBasicParseOptions = New VisualBasicParseOptions()
```
[VisualBasicParseOptions.vb](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/VisualBasicParseOptions.vb#L17).

This is due to how the exist DeclarePublicAPIAnalyzer works, I am implementing an update to recognise auto-implemented properties. It also raises another question, should the analyser recognise changes to `ReadOnly` / `WriteOnly` of a property? 
eg
```
Public Property [Property]() As Integer
' to
Public ReadOnly Property [Property]() As Integer
```
or visa-versa?

If it did it would produce thousand of diagnostics against the Roslyn code base, as it currently isn't being accounted for.

**Comment by jinujoseph** [comment]
cc @jaredpar

**Comment by CyrusNajmabadi** [comment]
@adamralph any part of the public surface area should be placed into the API files.  This includes auto-props, as well as any accessible getter/setter.

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.
