### ISSUE TITLE
C# console app, turn virtual space on

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#32837]
**Version Used**: Visual Studio 2015

Originally filed as https://devdiv.visualstudio.com/DevDiv/_workitems/edit/173194

**Steps to Reproduce**:

C# console app, turn virtual space on.

Main(null); |

press <kbd>Ctrl</kbd>+<kbd>Backspace</kbd> couple of times to get rid of the null

**Expected Behavior**:

Main(|

like in previous Visual Studio version. 

**Actual Behavior**:

Main( |

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
