### ISSUE TITLE
Consider using IBlankLineIndentationService as a language service

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#32832]
Obtaining `IBlankLineIndentationService` as a language service could avoid the need for language-specific overrides.

Originally requested in https://github.com/dotnet/roslyn/pull/32809#discussion_r251176526.

**Comment by CyrusNajmabadi** [comment]
That interface has been removed.  And there is one true IIndentationService that is a language service and can be retrieved as a data API in the normal way: https://github.com/dotnet/roslyn/blob/153fec7d2ada17d32788e60e97dd9c297ce610b4/src/Workspaces/Core/Portable/Indentation/IIndentationService.cs#L44
