### ISSUE TITLE
Cannot comment code with 'REM'

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#32835]
**Version Used**: Visual Studio 2019 Preview 2

:link: Originally filed as https://devdiv.visualstudio.com/DevDiv/_workitems/edit/159051

**Steps to Reproduce**:

Type `REM` to start a line comment in VB.

**Expected Behavior**:

Autocomplete does not replace `REM` when <kbd>Space</kbd> is pressed.

**Actual Behavior**:

Autocomplete replaces `REM` with `RemoveHandler` when <kbd>Space</kbd> is pressed.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this, and we're not likely to change these vb experiences snow.
