### ISSUE TITLE
Avoid creating instances of IBlankLineIndentationService on-the-fly

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#32831]
`CSharpIndentationService` and `VisualBasicIndentationService` are stateless, but instances of these types are created on-the-fly in refactorings. Consider using a singleton instance instead.

Originally requested in https://github.com/dotnet/roslyn/pull/32809#discussion_r251176464

**Comment by CyrusNajmabadi** [comment]
This is the current way things work.  You can either grab the singleton instances through ILanguageService or statically reference https://github.com/dotnet/roslyn/blob/153fec7d2ada17d32788e60e97dd9c297ce610b4/src/Workspaces/CSharp/Portable/Indentation/CSharpIndentationService.cs#L25
