### ISSUE TITLE
Refactor /features options and flags

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#3283]
The features options should be parse options only. A compilation should check that the features specified on all of its supplied parse trees are consistent. A compilation's features can then be taken from any of the underlying parse trees.

In order to do this, features-related data should be removed from `CompilationOptions` and its subclasses. Tests that use those should set the parse options instead.

When parsing the command-line, the syntax should be

```none
/features:a=b,c=d
```

Which sets the value of feature `a` to `b`, and feature `c` to `d`. Any number of features can be set on the command line this way. If the `=b` part is missing, it is assumed to be `=true`.

**Comment by khyperia** [comment]
Resolved by the above PR.
