### ISSUE TITLE
VB FAR appears to be case-sensitive for anonymous type property names

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#3284]
FAR on the ```.A``` in ```x``` finds the ```.A``` in y but not the ```.a``` in ```z```.
FAR on the ```.a``` in ```z``` doesn't find the ones in ```x``` or ```y```.

```VB
Class C
    Sub M()
        Dim x = New With {.A = 1}
        Dim y = New With {.A = 2}
        Dim z = New With {.a = 3}
    End Sub
End Class
```

**Comment by amcasey** [comment]
The semantic model returns symbols that are .Equals but not identical.

```VB
            Const source = "
Class C
    Sub M()
        Dim x = New With {.A = 1}
        Dim y = New With {.A = 1}
        Dim z = New With {.a = 1}
    End Sub
End Class
"
            Dim comp = CreateCompilationWithMscorlib({source})
            Dim tree = comp.SyntaxTrees.Single()
            Dim model = comp.GetSemanticModel(tree)

            Dim decls = tree.GetRoot().DescendantNodes().OfType(Of AnonymousObjectCreationExpressionSyntax).ToArray()
            Assert.Equal(3, decls.Count)

            Dim types = decls.Select(Function(d) model.GetTypeInfo(d).Type).ToArray()

            Assert.Equal(types(0), types(1))
            Assert.Equal(types(0), types(2))

            Assert.NotSame(types(0), types(1))
            Assert.NotSame(types(0), types(2))
```

**Comment by mattwar** [comment]
We should never be comparing symbols by identity.  It is common for SemanticModel to return different instances for symbols declared within method bodies.

**Comment by Pilchie** [comment]
@mattwar: Agreed (I wish I still had the code I wrote years ago to verify that we never did == on symbols so I could make it an analyzer :frowning: )

However, unless we can identify a worse user scenario than this, I think it can be fixed in Update 1.  I believe pointer types, arrays and generics are also not identity equal, but we never do operations like FAR on them, only on the underlying types.

**Comment by amcasey** [comment]
Using ```==``` instead of ```Equals``` would certainly cause problems for anonymous types, but I'm not sure that's what's going on here.  Note that the two distinct declarations with uppercase A *do* work with FAR.
