### ISSUE TITLE
VB: When changing the type of a property, the type of it's setter should be updated automatically

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#3285]
``` VB
Public Class C

        Private _field As String
        Public Property Prop As String
            Get
                Return _field
            End Get
            Set(value As String)
                _field = value
            End Set
        End Property

End Class
```

In the code above, change the type of the property from `String` to `Integer`
## Expected

The type of the value parameter in the set accessor should bee updated to match.
## Actual

It's not.
## Note

This is a regression from VS2013 :frowning:

**Comment by CyrusNajmabadi** [comment]
Closing out as we're not changing these vb experiences.
