### ISSUE TITLE
IDE0060 - Remove unused parameter should not fire for user-defined operators

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/roslyn#32852]
Removing the parameter isn't an option when it's required. Compare this to the case of implementing an interface and not using a parameter, which is fine and doesn't cause IDE0060 to fire.

```csharp
class Op
{
    // IDE0060 - Remove unused parameter
    public static Op operator -(Op op) => throw new NotImplementedException();
}
```

**Comment by CyrusNajmabadi** [comment]
> Removing the parameter isn't an option when it's required. 

I dunno.... your example seems very suspect.  When do you have an operator defined where you aren't using the parameter?

**Comment by bartdesmet** [comment]
I hit this particular error in code where an algebra is defined using user-defined operators for use within expression trees (i.e. to generate expression trees nodes representing the user intent). The code is never invoked, only interpreted algebraically for purposes of translation to a DSL or serialization to another compute node in the network, thus the body of all operators is implemented to throw.

My main annoyance is that a bulk fix of these warnings led to a bunch of compile errors. I'd assume quick fixes should not be offered if they will leave the resulting code invalid (just like an unused parameter from a method implementing an interface does not produce the suggestion).

As another example, consider some `Unit` type:

```csharp
struct Unit
{
    public static bool operator ==(Unit u1, Unit u2) => true;
    public static bool operator !=(Unit u1, Unit u2) => false;
}
```

**Comment by CyrusNajmabadi** [comment]
> The code is never invoked, only interpreted algebraically for purposes of translation to a DSL or serialization to another compute node in the network, thus the body of all operators is implemented to throw.

> As another example, consider some Unit type:

In these cases, it seems reasonable to just suppress the warning for those cases.  They're suitably niche to not warrant disabling the feature.  i.e. hte 99.9% case is that the warning is relevant and indicates an error.  These specific cases (expr-trees, or sentinel operators) are just so rare that it's ok to just suppress.

**Comment by bartdesmet** [comment]
I agree that suppressing the warning is fair for these corner cases. This said, should the quick fix be provided if it's known that applying the "fix" will result in invalid code? Right now, for the sample shown above, the fix produces:

```csharp
class Op
{
    public static Op operator -() => throw new NotImplementedException();
}
```

and an error results. I'd be happier with an experience where one performs a bulk fix across the document or project or solution, and ends up with code that still compiles. The remaining warnings are then to be addressed manually because they can't be fixed automatically in a meaningful way.

**Comment by bartdesmet** [comment]
Turns out I had a combo of Roslyn extensions that made it seem like IDE0060 also led to providing an incorrect code fix. I went down the route of suppressing these warnings for those occurrences now.

**Comment by bartdesmet** [comment]
I ran into this again today, but it was CA1801 offering an incorrect fix. See https://github.com/dotnet/roslyn-analyzers/issues/4697.
