### ISSUE TITLE
Public API checker should ignore protected members on uninheritable types

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#3287]
This concerns APIs which are `protected` on `public` types which can't be inherited from by customers.  In particular:

- Types which are `sealed`
- Types whose constructors are all `internal` or `private`

For such types the effective accessibility to customers is `internal`.  We should be free to modify, delete, etc ... those members post RTM.  The Public API checker should be updated to reflect that. 

---- Additions 2015-06-09 by @gafter ----

In addition we will give an **error** when an API occurs with the following pattern:

1. `Type1` is public but has only `internal` (no `public` or `protected`) constructors.
2. `Type2` extends `Type1`, is `public` and is not `sealed`, and has a `public` or `protected` constructor.

In that case the public API checker will report an error on each offending constructor in `Type2`. The reason is that `Type2` might be exposing members of `Type1` that are not considered part of the public API of `Type1`. To put it another way, `Type1` is considered "not inheritable by customers" but `Type2` violates that by making it inheritable.

**Comment by gafter** [comment]
@tmeschter I'll work on this unless you've already started.

**Comment by tmeschter** [comment]
@gafter You are welcome to pick this up.

**Comment by AdamSpeight2008** [comment]
What is the equivalent in VB?

**Comment by gafter** [comment]
@AdamSpeight2008 It is a common base class for both the C# and VB APIs.

**Comment by gafter** [comment]
Or rather, the analyzer is language-independent.

**Comment by gafter** [comment]
@tmeschter @jaredpar FYI the spec in this issue has been revised, and I'm now working on a revision of the PR for its implementation.

**Comment by gafter** [comment]
Fixed via #3308.

**Comment by gafter** [comment]
@tmeschter Can you please "Verify" that this fix made it into the stabilization branch?

**Comment by tmeschter** [comment]
Note that the work isn't really done until we update Microsoft.Net.Compiler and Microsoft.Net.RoslynDiagnostics packages in stabilization. That's the point at which the PublicAPI.txt files will actually be updated. This is being tracked by #3475.

**Comment by gafter** [comment]
@tmeschter Yes, good point.

**Comment by tmeschter** [comment]
Pull request #3475 has been merged in, and the PublicAPI.txt files adjusted accordingly.
