### ISSUE TITLE
Missing warnings for nullable references under `throw` statement/expression

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#32877]
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 2.0
VisualStudio.16.Preview/16.0.0-pre.2.0+28522.59
Microsoft .NET Framework
Version 4.7.03056

**Steps to Reproduce**:

Compile the following code:
```cs
#nullable enable
class C
{
  void M1() => throw null;
  void M2(System.Exception? ex = null) => throw ex;
}
```

**Expected Behavior**:
Nullable reference types warnings e.g. `Possible dereference of a null reference` for `throw null` and `throw ex` expressions.

**Actual Behavior**:
No warnings

**Comment by jcouv** [comment]
Thanks for reporting this. Fixed in dev16.1 preview1 by https://github.com/dotnet/roslyn/pull/32991
