### ISSUE TITLE
Pattern matching with ValueTuple causes Compiler Error 

### ISSUE THREAD

**Issue by rlvandaveer** [dotnet/roslyn#32882]
**Version Used**: 
Microsoft (R) Visual C# Compiler version 2.10.0.0 (b9fb1610)

**Steps to Reproduce**:

Add a case statement to a switch statement that checks for a ValueTuple<bool, string> and checks for the value of Item1 e.g.,

```c#

switch (val)
{
  case ValueTuple<bool,string> t when t.Item1 == true
    // do stuff
    break;
  // extraneous code omitted
}
```

Note that val is of type object.

The error can be overcome by two different syntax changes:
1. Move the value checking logic from the case and into the case body:

```c#
case ValueTuple<bool,string> t:
if (t.Item1 == true) do stuff...
```

2. Change equality `==` to `is` e.g., `case ValueTuple<bool,string> t when t.Item1 is true`

**Expected Behavior**:
Code should compile

**Actual Behavior**:
1>Build FAILED.
1>
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.exe" exited with code -2146232797.
1>    0 Warning(s)
1>    1 Error(s)
1>
1>Time Elapsed 00:00:04.04
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by gafter** [comment]
This appears to be fixed in VS 2019.
