### ISSUE TITLE
A variable from tuple deconstruction offers "Use discard" refactoring even when captured in a local function

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#32903]
**Version Used**: 
16.0.0 Preview 2.0

**Steps to Reproduce**:
https://github.com/Tragetaschen/DbusCore/blob/a4c1292b3df5fb8885c94a153e7c82f32019e477/src/Dbus/Decoder.cs#L225
![image](https://user-images.githubusercontent.com/1947968/51894602-8c7d2380-23a8-11e9-8df9-0dbbf0147d72.png)

**Expected Behavior**:
The "Use discard" should not be offered

**Actual Behavior**:
The "Use discard" code fix creates invalid code.
![image](https://user-images.githubusercontent.com/1947968/51894541-52ac1d00-23a8-11e9-9683-5f22f513408b.png)

**Comment by mavasani** [comment]
@jinujoseph This was _likely_ fixed by https://github.com/dotnet/roslyn/pull/31775 - would you be able to confirm if that PR went in Preview2 or later?

**Comment by mavasani** [comment]
I tried the following repro on latest dogfood build and don't see this issue. @Tragetaschen can you quickly confirm if the below code leads to fading for `var (getInt, value)` for you?

```csharp
public class C
{
    (Func<int>, int) createDelegate()
    {
        return (() => 1, 1);
    }

    public Func<int> M()
    {
        var (getInt, value) = createDelegate();

        int LocalFunction()
        {
            int result = 0;
            while (value > 0)
            {
                result = getInt() + value;
                value--;
            }

            return result;
        }

        return LocalFunction;
    }
}
```

**Comment by Tragetaschen** [comment]
I've pasted your code directly below my function from the OP: No, neither `getInt` nor `value` are grayed out and VS doesn't offer the "Use discard" refactoring.

**Comment by Tragetaschen** [comment]
Got it:
```csharp
public class C
{
    private (int, int) createTuple() => (1, 1);

    public (Func<int>, bool) M()
    {
        var (value1, value2) = createTuple();

        int LocalFunction() => value1 + value2;

        return (LocalFunction, true); // This is important
    }
}
```

The local function has to be referenced in a tuple itself. Just returning it doesn't trigger the bug.

**Comment by mavasani** [comment]
Great thanks, can repro it now!
