### ISSUE TITLE
Weird comment coloring on #region's

### ISSUE THREAD

**Issue by nmoschkin** [dotnet/roslyn#3291]
At least in Visual Basic, if you have a comment after #End Region ... in Visual Studio 2013, these comments next to collapsed regions would be green like normal comments.  Now they're white, in VS 2015...

![issue_image1](https://cloud.githubusercontent.com/assets/5912337/7972496/94e51b12-0a12-11e5-8083-3b0d0a9c9764.png)

**Comment by AdamSpeight2008** [comment]
Is there any in the `Options / Fonts and Colors` that match that style?

**Comment by Pilchie** [comment]
Interesting.  The classification is correct while the region is expanded, which leads me to believe that this might be a bug in the editor where it doesn't ask for the classification at the end of the line after an elision buffer.

@AdamSpeight2008 It appears that it is not being classified at all, and therefore picking up the "Text" color.

**Comment by Pilchie** [comment]
I'll start a mail thread to follow up with the editor.

**Comment by Pilchie** [comment]
I followed up with the editor, but from their debugging it looks like we *weren't* returning classifications for it, though I don't know how outlining would affect our tagger either.  Want to take a look?
