### ISSUE TITLE
#nullable enable causes bogus cycle in struct layout error

### ISSUE THREAD

**Issue by MrTrillian** [dotnet/roslyn#32934]
**Version Used**: VS2019 Preview 2

**Steps to Reproduce**:

1. Create a new .NET core C# library project
2. Change the C# language version to 8.0
3. Type the following code

```
#nullable enable
struct Foo<T>
{
	static Foo<T> Bar;
}
```

**Expected Behavior**: Code compiles fine whether or not `#nullable enable` is used
**Actual Behavior**: With `#nullable enable` the compiler emits this error:

`Error CS0523: Struct member 'Foo<T>.Bar' of type 'Foo<T>' causes a cycle in the struct layout`

**Comment by fitdev** [comment]
Happens in VS2019 Preview 3 as well.

**Comment by MrTrillian** [comment]
@jcouv Milestone 16.1 means that this will be fixed in a post-release of VS2019, right? Because I hit the issue with Preview 5 and RTM both :(

**Comment by jaredpar** [comment]
@MrTrillian yes this will be fixed in the update 1 tree. The initial preview of update 1 will have this fix.
