### ISSUE TITLE
The focus of IntelliSence is not right in  vs2019preview2 when async code completion=on

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#32940]
**Version Used**: The one in vs2019 preview2

The testcase used to be crash in vs2019preview1(#31263), so not sure what happened in preview1. And works well in vs2017 15.9.5.

**Steps to Reproduce**:

1. Set Options/Environment/Preview Features/`Use asynchronous code completion in C# and Basic` to on.
2. Type `string.Equals("","",StringComparison.[cursor here, and an autocompleted char ')']` in an .cs file
3. Press arrow up/down.

**Expected Behavior**:
Switch between members of `StringComparison`, like it does in vs2017 15.9.5

**Actual Behavior**:
Switch between the overload of method `string.Equals`.

**Comment by CyrusNajmabadi** [comment]
@ivanbasov Note: we have a test for this somewhere.  So i'm surprised if this regressed

**Comment by ivanbasov** [comment]
Thank you, @yyjdelete and @CyrusNajmabadi ! Let me investigate this.

**Comment by yyjdelete** [comment]
Updated: 
Seems this only happen when Options/Environment/Preview Features/`Use asynchronous code completion in C# and Basic` is set to on, and not for default or off.

**Comment by ivanbasov** [comment]
@AmadeusW it seems that this now happens on the Editor side. I'm not sure we can do anything on the Roslyn side. Could you please review?

**Comment by CyrusNajmabadi** [comment]
I'm curious how our testing missed this.  I am like 98% sure we have tests for this.  This is why we even have the tests that include both signhelp and completion together to validate this behavior.

**Comment by CyrusNajmabadi** [comment]
i could have sworn it was an integration test.  but all this stuff has changed so much over time :-/

**Comment by AmadeusW** [comment]
I see that Roslyn interacts with SignatureHelp when handling the up\down keys

![image](https://user-images.githubusercontent.com/1673956/52225573-8a5f0d00-285f-11e9-86be-524d5f636bd5.png)

SignatureHelp itself does not have means to check for presence of completion [SignatureHelp/Controller_NavigationKeys](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/IntelliSense/SignatureHelp/Controller_NavigationKeys.cs) 

The logic which determines whether completion or signature help should handle a command is here: [AbstractIntelliSenseCommandHandler](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/CommandHandlers/AbstractIntelliSenseCommandHandler.cs,9fa224facfe17d4b)
This class does not support completion implemented outside of Roslyn

**Comment by AmadeusW** [comment]
Since command handlers return bool, we lack fidelity to express that SignatureHelp command handler _should not_ run, but subsequent command handlers _should_ run.

If we `return true` from [AbstractCompletionCommandHandler](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/CommandHandlers/AbstractCompletionCommandHandler.cs), then signature help won't act. However, this will mark the entire command handled and Editor won't run, either.

Anyways, I believe that the fix is somewhere between `AbstractIntelliSenseCommandHandler` and `AbstractCompletionCommandHandler`

**Comment by ivanbasov** [comment]
@jinujoseph a fix on Roslyn is available but it is large and risky, and it also requires a fix on the editor side which is not yet available. So, i have moved this to 16.1.

**Comment by davkean** [comment]
This bug is very annoying and breaks arrows on any overload usage:

![image](https://user-images.githubusercontent.com/1103906/53074041-d4254400-353d-11e9-8d50-da47f007d90f.png)

**Comment by davkean** [comment]
Moving this back to 16.0 P4 as per conversations internally.

**Comment by ivanbasov** [comment]
Fix merged. Target: 16.0 Preview 4
