### ISSUE TITLE
Roslyn.Compilers.Extension.SetGlobalGlobalPropertiesForCPS throwing exception

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#32963]
in latest d16.0 with latest Roslyn preview 3, we get this

```
Microsoft.VisualStudio.Composition.CompositionFailedException
  HResult=0x80131500
  Message=An exception was thrown while initializing part "Roslyn.Compilers.Extension.SetGlobalGlobalPropertiesForCPS".
  Source=Microsoft.VisualStudio.Composition
  StackTrace:
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.Lazy`1.CreateValue()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Inner Exception 1:
MissingMethodException: Method not found: 'Microsoft.VisualStudio.ProjectSystem.IProjectServices Microsoft.VisualStudio.ProjectSystem.IProjectService.get_Services()'.
```

it is due to this change

https://devdiv.visualstudio.com/DevDiv/_git/CPS/commit/9e27f2e3a53c7945fe7053e79fb3d568121d10d1?refName=refs%2Fheads%2Fmaster&_a=compare&path=%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem%2FCore%2FProjectService%2FIProjectService.cs

..

according to @davkean this is intentional public API changes.

**Comment by heejaechang** [comment]
tagging @agocke

**Comment by agocke** [comment]
What steps do I actually have to do to repro this problem?

**Comment by agocke** [comment]
@heejaechang I tried adding the `TargetVersion` change as @davkean suggested and got 

```
31>VSSDK : error VSSDK1312: The version range '16' is invalid.
31>VSSDK : error VSSDK1086: An asset of type 'Microsoft.VisualStudio.VsPackage' cannot specify a target version.
```

**Comment by agocke** [comment]
OK, I removed the TargetVersion change from VsPackage and just added it to MefComponent and the proposed fix doesn't work.

**Comment by agocke** [comment]
@jaredpar For triage to someone who knows what they're doing

**Comment by heejaechang** [comment]
it's kind of in the email. but here is how you can repro

sync dev16.0-preview3-vs-deps and build with preview 3 rel/d16 drop.

run devenv /rootsuffix RoslynDev

create Net.Core console app

build.

build will fail.

**Comment by jaredpar** [comment]
I have no idea what this is. I think @jasonmalinowski may have more context.

**Comment by jasonmalinowski** [comment]
What's the question?

**Comment by davkean** [comment]
Not the package @agocke , but the MEF component. Let me look at the code to see if there's a better way to avoid the breaking changes.

**Comment by davkean** [comment]
Nope impossible to avoid the breaking changes.

**Comment by agocke** [comment]
Here's my change, I don't have any idea why this doesn't work: https://github.com/dotnet/roslyn/compare/master...agocke:fix-compiler-vsix?expand=1

**Comment by agocke** [comment]
We're currently using the following package: https://www.nuget.org/packages/Microsoft.VisualStudio.ProjectSystem.Managed.VS/

Is that the wrong one?

**Comment by davkean** [comment]
Yes it is the wrong one, it should be Microsoft.VisualStudio.ProjectSystem and one of the recent dev16 versions, such as https://www.nuget.org/packages/Microsoft.VisualStudio.ProjectSystem/16.0.374-pre.

**Comment by agocke** [comment]
Tried updating the version, now the extension doesn't work at all. Someone else will need to chase down all the failures here. @jaredpar

**Comment by jaredpar** [comment]
Think we need to step up a bit here. 

- Yes this code is in the compiler VSIX but it was added by [IDE / project system](https://github.com/dotnet/roslyn/commit/3ffc85bb38bdbee18475ae885a692474bd566b71#diff-c0b5492a955df68b2b4a31f85fafa844). This means we basically have zero context here on the compiler team: both to why this was needed or what we need to do. 
- Is there an explanation of what broke anywhere that we should be looking at?
- Given this is a breaking change what is the guidance by the team that did the break for how to work around this?

**Comment by jasonmalinowski** [comment]
This was contributed in #26684 and nobody from the IDE understands this either. @jmarolf might know more what is going on here.

**Comment by jasonmalinowski** [comment]
What I think this *is* generally trying to do is our dogfood VSIX works by globally adding a file into the AppData directory that hooks the build. To make sure that doesn't impact everything, it goes and checks for a MSBuild global property to be set so it only impacts builds invoked from that instance of VS. Somehow this is trying to set that global property.

**Comment by yodax** [comment]
Hi, this is probably unrelated to the original issue, but I hope you can help me out. I'm experiencing the same error while getting the project XML for the new project file structure introduced in VS2017.

```MissingMethodException: Method not found: 'Microsoft.VisualStudio.ProjectSystem.IProjectServices Microsoft.VisualStudio.ProjectSystem.IProjectService.get_Services()'.```

This is only happening under VS2019. The link posted in the opening post is not accessible to me. 

I was wondering if you raised this internally and if we can expect a fix for the missing method exception.

**Comment by jmarolf** [comment]
@yodax 	the issue is that the project system intentionally made a breaking change in VS 2019 

This:
`Microsoft.VisualStudio.ProjectSystem.IProjectServices Microsoft.VisualStudio.ProjectSystem.IProjectService.get_Services()`

Is now this:
`Microsoft.VisualStudio.ProjectSystem.ProjectServices Microsoft.VisualStudio.ProjectSystem.IProjectService.get_Services()`

**Comment by jmarolf** [comment]
@jasonmalinowski 	@davkean 	We can make the change in master-vs-deps so that it consumes the new VS 2019 APIs but since master needs to remain build-able against VS 2017 I see no way to fix is so that if you deploy master to a VS 2019 hive it doesn't break.  Is the requirement still that master is F5-able from VS 2017 or can we require VS 2019 previews?

**Comment by jasonmalinowski** [comment]
@jmarolf Can we just use reflection in this case?

**Comment by jmarolf** [comment]
@jasonmalinowski 	This is a MEF import so I am not sure how you would manage this

**Comment by jasonmalinowski** [comment]
What changed? It was previously an import of the interface name and now it's an import of a concrete type? You should be able to MEF import via contract name which is just a string.

**Comment by jmarolf** [comment]
@jasonmalinowski 	👍

**Comment by jasonmalinowski** [comment]
@jmarolf Yeah you should hopefully be able to either import with `[Import("some string name", AllowDefault=true)] object foo` to conditionally grab one (and use two imports), or it might be easier to explicitly import the ExportProvider and just call GetExports() on it to probe one or the other.
