### ISSUE TITLE
Need trim start whitespace per line in string of $@ format

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/roslyn#32965]
_From @chenyj796 on January 30, 2019 11:12_

### Steps to reproduce

When I declare a string in a method as below:
``` csharp
void Test()
{
    var str = $@"
line one
line two
";
}
```

I hope it can be writen as below:
``` csharp
void Test()
{
    var str = $@"
          line one
          line two
         ";
}
```
and the compiler can auto remove the leading whitespace if I add a property in the csproj file, such as:
``` xml
<TrimStartWhitespaceForStringDeclaration>true</TrimStartWhitespaceForStringDeclaration>
```

### Environment data
`msbuild /version` output:

OS info:

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

_Copied from original issue: Microsoft/msbuild#4110_

**Comment by CyrusNajmabadi** [comment]
This violates the goal of C# to not have 'dialects'.

**Comment by Therzok** [comment]
Could this not be done as a IL post processing?

**Comment by jcouv** [comment]
Language design proposals should be on csharplang. The roslyn repo is for compiler and IDE bugs. Thanks

**Comment by CyrusNajmabadi** [comment]
We have raw strings for this now. :)
