### ISSUE TITLE
Code style > Expression preferences > Prefer range operator has incorrect sample code

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#32986]
**Version Used**: 
![image](https://user-images.githubusercontent.com/41759/52023187-fe409480-24b0-11e9-81aa-ea391cbc0bbc.png)

![image](https://user-images.githubusercontent.com/41759/52022577-5b871680-24ae-11e9-8a94-849b6f53738a.png)

**Comment by CyrusNajmabadi** [comment]
nice....
