### ISSUE TITLE
Support `if` pattern in "use null coalescing assignment" refactoring 

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#32985]
Currently "use null coalescing assignment" refactoring only triggers for patterns like 
```cs
x = x ?? y;
```

It'd be nice to expand the support to `if` patterns

```cs
if (x == null)
{
    x = y;
}

if (x is null)
{
    x = y;
}
```

**Comment by mavasani** [comment]
If implemented, we should implement this as an analyzer/code fix, so we can support build time enforcement. See https://github.com/dotnet/runtime/pull/71361 for this request.
