### ISSUE TITLE
csharp_preferred_modifier_order is missing from the table in Tools > Options > Text Editor > C# > Code Style > General 

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#32989]
**Version Used**: 
![image](https://user-images.githubusercontent.com/41759/52023187-fe409480-24b0-11e9-81aa-ea391cbc0bbc.png)

The table listing styles settings does not include `csharp_preferred_modifier_order` but the generated `.editorconfig` file does.

```
# Modifier preferences
csharp_preferred_modifier_order = public,private,protected,internal,static,extern,new,virtual,abstract,sealed,override,readonly,unsafe,volatile,async
```

**Comment by CyrusNajmabadi** [comment]
I recall this being intentional.  Namely because we didn't want to create UI to manage configuring this.

**Comment by sharwell** [comment]
Tentatively marking this as **Won't Fix** and will update after design review.

**Comment by sharwell** [comment]
Design review conclusion: full parity of **Tools&rarr;Options** with .editorconfig is not required. At this time, we do not plan to design/develop/maintain a UI for this option since the team experience for any non-default setting is better when the setting is maintained through .editorconfig.
