### ISSUE TITLE
Generate .editorconfig file from settings should initialize Save file dialog with solution dir

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#32987]
**Version Used**: 
![image](https://user-images.githubusercontent.com/41759/52023328-89ba2580-24b1-11e9-99ad-f7a1ead6c0f8.png)

**Steps to Reproduce**:

Tools > Options > Text Editor > C# > Code Style > Generate .editorconfig file from settings.

**Expected Behavior**:

For convenience, the Save Dialog should open in the directory where the current solution is loaded from if a solution is open. 

**Actual Behavior**:

The Save Dialog opens in a random directory (the current directory of the drive?)

**Comment by sharwell** [comment]
I agree with solution folder (issue description) as opposed to project folder (issue title). :+1:

**Comment by tmat** [comment]
Fixed the title.
