### ISSUE TITLE
IWorkspaceProjectContext does not grantee workspace is update-to-date on method return

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#32984]
[IWorkspaceProjectContext.cs](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/ProjectSystem/CPS/IWorkspaceProjectContext.cs) as I understand it is supposed to have the following contracts

**Expected:** 

If `StartBatch` has not been called

- Upon the call to any `Add*` or `Remove*` method returning execution to the caller the workspace shall be up-to-date

If `StartBatch` has been called

- Upon a call to `EndBatch` returning execution to the caller the workspace shall be up-to-date

**Actual:**

If there are open files the running-document-table is consulted and updated asynchronously making it take an unknowable amount of time for the workspace to be brought up to date

**Comment by jasonmalinowski** [comment]
@jmarolf Just so I have the background, is this just a generic tracking bug or is this causing a particular problem?

**Comment by jmarolf** [comment]
This is for general tracking. I've worked around it as best I can. There are several things I want to be able to do that are blocked on this, but they are 16.1

**Comment by jasonmalinowski** [comment]
@jmarolf What is blocked by it?

**Comment by jmarolf** [comment]
Knowing when the workspace is up-to-date for perf testing reasons is one of them.  I cannot determine when a project is finished "populating" today because, it the user previously had files open it takes some unknown amount of time for the workspace to be done.

Renaming a file offering to rename the type is the other one.  Both csproj.dll and CPS will not be able to work reliable 100% of the time if files are open (rather common).

**Comment by jasonmalinowski** [comment]
And to clarify why I'm asking: besides just prioritization, to do this really well requires pushing on various other teams to thread a "golden path" through of free-threadedness that I can leverage. Having concrete scenarios always helps both the prioritization for them and also making sure we're building what you ultimately expect.

**Comment by jasonmalinowski** [comment]
It also occurred to me that I can probably do this without changes to VS by keeping a free-threaded abstraction over the RDT that just updates itself on the UI thread when documents are opened, so we can do a "get me the ITextBuffer" in the free threaded approach.

**Comment by jasonmalinowski** [comment]
And lastly, if the perf testing you're doing is automated testing, we should make sure the waiter infrastructure is all wired up right if it's not already.

**Comment by jmarolf** [comment]
> How does this impact the second case? If a file is open you will have the file in the workspace; GetText() will just give the file contents on disk. I guess is the problem where you are triggering a rename, you rename the file and then you don't know how long to wait until you can do the symbolic rename?

What I am observing is:
1. project system removes a file from the workspace
2. project system adds a file to the workspace
3. calls to Workspace.CurrentSolution will have the old file path for the renamed document iff it is open until
4. After some indeterminate amount of time the workspace is updated with the new file path

This is observable on csproj.dll and CPS

> And lastly, if the perf testing you're doing is automated testing, we should make sure the waiter infrastructure is all wired up right if it's not already.

In tests I can special case things so there are no files open.  Ideally I'd like telemetry for this so when we make a change we can prove its actually had an impact on real users project-readiness time

**Comment by jasonmalinowski** [comment]
You definitely shouldn't be seeing that. Structurally, you should see the new file present immediately -- only it's contents may be wrong. Do you have a repro or a breakpoint I can drop somewhere to investigate further?

**Comment by jmarolf** [comment]
In practice it is possible to call `RemoveSourceFile` with batching off and still observe a document that has the removed path.

Consider [this line](https://github.com/jmarolf/project-system/blob/1da351c0558c85781b1437f9a999f902c753a5c2/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/CSharpOrVisualBasicFileRenameHandler.cs#L195) which, according to the contract you describe, should never be hit.

However, if you 

1. clone and build this repo

```cmd
> git clone -b fix-file-rename --single-branch https://github.com/jmarolf/project-system.git 
> cd project-system
> build.cmd /rootsuffix RoslynDev
> Launch.cmd /rootsuffix RoslynDev
```

2. Create a new .NET Core app
3. Attach the debugger
4. Continue to rename Program.cs (`Program` -> `Foo` -> `Bar` -> `Baz`)

You will eventually hit the [this line](https://github.com/jmarolf/project-system/blob/1da351c0558c85781b1437f9a999f902c753a5c2/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/CSharpOrVisualBasicFileRenameHandler.cs#L195)

**Comment by jmarolf** [comment]
To further clarify.  The rename code is called [here](https://github.com/jmarolf/project-system/blob/1da351c0558c85781b1437f9a999f902c753a5c2/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs#L185-L189) which, to my understanding, should ensure we have finished publishing changes to the workspace

**Comment by jasonmalinowski** [comment]
Thanks for the concrete thing I can debug.

> to my understanding, should ensure we have finished publishing changes to the workspace.

That's not what I'm seeing. If I drop breakpoints on VisualStudioProject.AddSourceFile, VisualStudioProject.RemoveSourceFile, the batch processing code and that line you highlighted, I hit scenarios where:

1. BeginBatch is called.
2. RemoveSourceFile is called.
3. AddSourceFile is called.
4. Your `GetDocument(..., oldFilePath)` is hit.
5. EndBatch is called.

I'm also seeing cases too where EndBatch is called "first" in time but that other code fires. I suspect the reason is because if they're running in parallel threads, one thread captured the Solution snapshot before EndBatch happened, so it's still on an old snapshot.

You're definitely applying the rename, but there seems to be no synchronization happening between the source file changing and the special rename handler there. Given I should never be able to see that order but am hitting it without problems I'm going to close this as External, and make a separate tracking item for the specific case of content being wrong to avoid any confusion here.

**Comment by jasonmalinowski** [comment]
The tracking work item for the case where the _contents_ are stale is https://devdiv.visualstudio.com/DevDiv/_workitems/edit/787200.
