### ISSUE TITLE
Regex: could warn on duplicate characters in character set

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#32997]
```csharp
using System.Text.RegularExpressions;

namespace ConsoleApp27
{
    class Program
    {
        static void Main(string[] args)
        {
            var MyRegex = new Regex(@"folder[aaa]name");
        }
    }
}
```

Expected:
A warning that duplicate characters are not needed in character set

Actual:
No warning

**Comment by CyrusNajmabadi** [comment]
It's a core goal of the regex engine that it produces the exact same warnings/errors as the underlying .net engine.  If you want to have the underlying .net engine also produce these, then i'd be ok with Roslyn's version doing the same.  otherwise, this just means we get out of sync with them.
