### ISSUE TITLE
Rename using

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33002]
I send screenshot of code. Renaming A works fine but renaming B does not rename correctly and leads to compile time error.

![image](https://user-images.githubusercontent.com/12449387/52043400-70869880-24f4-11e9-8d20-0c5322f3c379.png)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/433879/rename-using.html
VSTS ticketId: 776278_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Not repro.  Renaming 'B' worked fine for me:

![image](https://user-images.githubusercontent.com/4564579/218131262-6b17dbfd-0bda-414d-a872-8af112e05ad0.png)
