### ISSUE TITLE
VB "simplify name" greys out entire method in cases where it should only grey out generic type parameters

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3300]
![vb-grey2](https://cloud.githubusercontent.com/assets/3316258/7975856/13448910-0a28-11e5-9493-7e199eed00fc.png)

What I expect: it should only grey out the generic type parameter `(Of String)` and `(Of Integer)`

What I get: it actually greys out the method name Select as well.

(Note that C# gets this right. Note that, despite the incorrect grey span, the quickfix does the right thing in both cases).

**Comment by Giftednewt** [comment]
I've had a look through and I think that this line is causing the issue https://github.com/dotnet/roslyn/blob/master/src/Workspaces/VisualBasic/Portable/Extensions/ExpressionSyntaxExtensions.vb#L1185

the C# implementation is returns
```
issueSpan = genericName.TypeArgumentList.Span;
```

**Comment by Giftednewt** [comment]
If I create a PR for this is someone able to verify that this change does indeed resolve the issue?

**Comment by jmarolf** [comment]
@Giftednewt I'd be happy to take a look
