### ISSUE TITLE
In documentation, mark <para> will generate empty line in tooltip

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33001]
When using &lt;para&gt; to insert a new line in the documentation, &lt;para&gt; will generates additional empty lines in the Tooltip displayed by IntelliSense or mouseover on keywords.
this problem is start at VS 2013, please fix it

![image](https://user-images.githubusercontent.com/12449387/52042691-a88cdc00-24f2-11e9-87f0-1dea3c2063db.png)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/441448/in-documentation-mark-will-generate-empty-line-in.html
VSTS ticketId: 782031_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
The blank line is added here:

https://github.com/dotnet/roslyn/blob/cb2475f98b714871c6ee9753940b8285cb2796ba/src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs#L82-L86

The separation is by design, but we don't *need* it to be so large. @olegtk is there a way to do paragraph separations in Quick Info without such a large gap?

**Comment by olegtk** [comment]
@gundermanc ?

**Comment by Flithor** [comment]
I think this line spacing should be configurable, some people like compact tooltip text (such as me), some people need a certain spacing, some people like to use large fonts need to set a specific spacing

**Comment by gundermanc** [comment]
TBH, it looks like the screenshot has a font with a larger line height (if that's a thing) leading to more space between items than the default.

@sharwell [ContainerElement](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.adornments.containerelement.-ctor?view=visualstudiosdk-2017) is used for stacking or wrapping multiple pieces of content together. It's not very customizable, however, you can choose to add a fixed amount of blank space between items or omit it via [ContainerElementStyle](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.adornments.containerelementstyle?view=visualstudiosdk-2017).VerticalPadding.
