### ISSUE TITLE
Allow upcasting Task<T> to Task<T?>

### ISSUE THREAD

**Issue by roji** [dotnet/roslyn#33010]
Apologies if this has already been raised/discussed...

While working on annotating a codebase, I've been running into the following kind of case:

```c#
Task<string> Foo() => Task.FromResult("foo");
Task<string?> Bar() => Foo();
```

It seems like it should be possible to upcast a Task<T> into Task<T?>. Moreover, there doesn't seem to be an easy workaround for this (aside from disabling nullability checking).

**Comment by benaadams** [comment]
Would have to create a new task
```csharp
Task<string?> Bar() => await Foo();
```
As they are fundamentally different sized objects. 

`string` is `IntPtr` sized, however `string?` is `IntPtr + bool + padding` sized

**Comment by benaadams** [comment]
Ah! Nullable references; so its just `null` and the same size...

**Comment by roji** [comment]
Yeah, exactly :)

**Comment by jaredpar** [comment]
This behavior is "By Design". This would be allowed in the case where the type parameter was covariant but it is not here hence this conversion is correctly disallowed.

**Comment by gafter** [comment]
The workaround is to invoke this method
``` c#
Task<T?> ToNullableTask<T>(Task<T> task) where T: class
{
    return await task;
}
```

**Comment by roji** [comment]
@jaredpar @gafter thanks for your answers. The workaround above causes another Task to be allocated on the heap, which is what I was hoping we could avoid. It also adds the overhead of a new state machine (although `ToNullableTask()` could probably be written without async to avoid that). Finally, without #2194 we'd need two methods, one for reference types and one for value types.

@jaredpar my hope was that covariance could be implemented in the language for nullable reference types specifically, otherwise we're going to see a lot of needless allocations and copying for something that isn't even a real type in runtime, only to bypass a compiler-imposed limitation. Efficient async programming is only one example, I'm sure that many others will pop up (e.g. cast `List<string?>` to `List<string>`).

Does it make sense to open a different, more general issue for covariance and nullability, or has the team discussed this idea and rejected it?

**Comment by jaredpar** [comment]
@roji 

> The workaround above causes another Task to be allocated on the heap, which is what I was hoping we could avoid.

The other solution is to use the `!` operator to allow for the conversion. 

> Does it make sense to open a different, more general issue for covariance and nullability, or has the team discussed this idea and rejected it?

That's appropriate if you'd like to discuss but csharplang is a better place to open this as it's language design. This was discussed though and compiler behavior today represents the decisions. The type conversion code allows for co/contra variance in type parameters for nullability as it does for all other types. 

I doubt we would end up special casing it for nullability though. Allowing implicit co / contravariance for nullability just leaves the door wide open to allow for nulls to enter the program. The only way to allow for it safely is to mark the type parameter itself and let the existing language rules play out.

**Comment by jmarolf** [comment]
This matches the behavior of not allowing this for `Nullable<T>`

```C#
Task<int> Foo() => Task.FromResult(42);
Task<int?> Bar() => Foo(); // Error	CS0029	Cannot implicitly convert type 'System.Threading.Tasks.Task<int>' to 'System.Threading.Tasks.Task<int?>'
```

Breaking this symmetry would be difficult to explain imho, but feel free to file an issue on csharplang and make your case :)

**Comment by roji** [comment]
@jaredpar

> The other solution is to use the `!` operator to allow for the conversion.

Thanks, I wasn't aware that was possible and it definitely works well around the problem (i.e. no allocations or copying).

> Allowing implicit co / contravariance for nullability just leaves the door wide open to allow for nulls to enter the program.

I don't see how that can happen but I'm surely missing something... In any case I've opened https://github.com/dotnet/csharplang/issues/2225 to discuss.

@jmarolf 

> This matches the behavior of not allowing this for `Nullable<T>`
> [...]
> Breaking this symmetry would be difficult to explain imho, but feel free to file an issue on csharplang and make your case :)

That's true, although the asymmetry between NVTs and NRTs already exists deep within the language - in the former cases there's two different runtime types, whereas in the latter there's only one. This would also not be the only visible asymmetry (#1865). For reference, https://github.com/dotnet/csharplang/issues/1301 requests co/contravariance for NVTs.
