### ISSUE TITLE
#nullable offered in completion when using version of C# <8

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#33027]
In a project that is using LanguageVersion 7.3 or lower
1. Open a .cs file
2. Type '`#` on an empty line 
3. Observe that `nullable` is in the completion list, although it requires C# 8 or higher

![image](https://user-images.githubusercontent.com/611219/52091361-03f9b100-2569-11e9-8b81-2ee0d3317f62.png)

**Comment by CyrusNajmabadi** [comment]
This is working as expected.  The user gets a clear message about why this is not ok, and a good fixer to fix it up.  This is actually a pattern i think we should encourage.  Esp. as users will read about features and want to try them out.  Having the IDE fight them on this isn't something good.
