### ISSUE TITLE
VS2015RC, Unhandled exception/crash in Microsoft.CodeAnalysis.Workspaces.dll

### ISSUE THREAD

**Issue by radioman** [dotnet/roslyn#3303]
**Reduced Repro**

```C#
// In Class1.cs
partial class C
{
    private static void M() // Rename M to Method
    {
        M();
    }
}

// In Class2.cs
partial class C
{
    private static void Method()
    {
    }
}
```

**Original Report**

Unhandled exception/crash in Microsoft.CodeAnalysis.Workspaces.dll
version: 1.00.0.50411
original location: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.Workspaces.dll

i cant find F:\Builds\6272\Roslyn\Dev14RC-Signed-Release\src\Open\src\Workspaces\Core\Portable\obj\Release\Microsoft.CodeAnalysis.Workspaces.pdb

so that all, cheers ;} select code, right click, action, extract method

System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" 

Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandl

ed exception</Description><AppDomain>DefaultDomain</AppDomain><Exception><ExceptionType>System.Collections.Generic.KeyNotFoundException, mscorlib, Version=4.0.0.0, 

Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>The given key was not present in the dictionary.</Message><StackTrace>   at 

System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.&amp;lt;&amp;gt;c__DisplayClass3_0.&amp;lt;ComputeDeclarationConflictsAsync&amp;gt;b__2

(Location t)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.&amp;lt;ComputeDeclarationConflictsAsync&amp;gt;d__3.MoveNext

()</StackTrace><ExceptionString>System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.&amp;lt;&amp;gt;c__DisplayClass3_0.&amp;lt;ComputeDeclarationConflictsAsync&amp;gt;b__2

(Location t)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.&amp;lt;ComputeDeclarationConflictsAsync&amp;gt;d__3.MoveNext

()</ExceptionString></Exception></TraceRecord>

-------------------------------- copy of callstack

>	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler)	

Unknown
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!<Unknown function>	Unknown
 	[Native to Managed Transition]	
 	mscorlib.dll!System.Collections.Generic.Dictionary<System.__Canon, System.__Canon>.this[System.__Canon].get(System.__Canon key)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!

Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.ComputeDeclarationConflictsAsync.AnonymousMethod__2(Microsoft.CodeAnalysis.Location t)	Unknown
 	System.Core.dll!System.Linq.Enumerable.WhereSelectEnumerableIterator<Microsoft.CodeAnalysis.Location, Microsoft.CodeAnalysis.Location>.MoveNext()	Unknown
 	mscorlib.dll!System.Collections.Generic.List<Microsoft.CodeAnalysis.Location>.InsertRange(int index = 0, 

System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Location> collection)	Unknown
 	mscorlib.dll!System.Collections.Generic.List<System.__Canon>.AddRange(System.Collections.Generic.IEnumerable<System.__Canon> collection)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!<Unknown function>	Unknown
 	mscorlib.dll!

System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.<ComputeDeclarationConfl

ictsAsync>d__3>(ref Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.<ComputeDeclarationConflictsAsync>d__3 stateMachine)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.ComputeDeclarationConflictsAsync(string 

replacementText, Microsoft.CodeAnalysis.ISymbol renamedSymbol, Microsoft.CodeAnalysis.ISymbol renameSymbol, 

System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.ISymbol> referencedSymbols, Microsoft.CodeAnalysis.Solution baseSolution, Microsoft.CodeAnalysis.Solution 

newSolution, System.Collections.Generic.IDictionary<Microsoft.CodeAnalysis.Location, Microsoft.CodeAnalysis.Location> reverseMappedLocations, 

System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.AddDeclarationConflictsAsync(Microsoft.CodeAnalysis.ISymbol 

renamedSymbol = Method void NanoLABas.CoreData.Validator.EntryValidator.STATUS_ANTIPASS(NanoLABas.PlateInfo plateInfo), Microsoft.CodeAnalysis.ISymbol renameSymbol = 

{Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolution}, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.ISymbol> referencedSymbols = Count = 3, 

Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolution conflictResolution = IsCancellationRequested = false, 

System.Collections.Generic.IDictionary<Microsoft.CodeAnalysis.Location, Microsoft.CodeAnalysis.Location> reverseMappedLocations = Method void 

NanoLABas.CoreData.Validator.EntryValidator.NewMethod(NanoLABas.PlateInfo plateInfo), System.Threading.CancellationToken cancellationToken = Count = 0)	Unknown
 	mscorlib.dll!

System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.<AddDeclarationConflictsAsync>d__9>(ref 

Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.<AddDeclarationConflictsAsync>d__9 stateMachine)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.AddDeclarationConflictsAsync(Microsoft.CodeAnalysis.ISymbol 

renamedSymbol, Microsoft.CodeAnalysis.ISymbol renameSymbol, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.ISymbol> referencedSymbols, 

Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolution conflictResolution, System.Collections.Generic.IDictionary<Microsoft.CodeAnalysis.Location, 

Microsoft.CodeAnalysis.Location> reverseMappedLocations, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.IdentifyConflictsAsync

(System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.DocumentId> documentIds = Count = 1, Microsoft.CodeAnalysis.ProjectId projectId = 

{Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolution}, Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolution conflictResolution = (ProjectId, 

#ef9ab61b-7466-4cab-86c4-0016601ad7cf - D:\gits\v2\Core\CoreData\CoreData.csproj))	Unknown
 	mscorlib.dll!

System.Runtime.CompilerServices.AsyncTaskMethodBuilder<bool>.Start<Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<IdentifyConflictsAsync>d__18>(ref 

Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<IdentifyConflictsAsync>d__18 stateMachine)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.IdentifyConflictsAsync

(System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.DocumentId> documentIds, Microsoft.CodeAnalysis.ProjectId projectId, 

Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolution conflictResolution)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.ResolveConflictsAsync()	Unknown
 	mscorlib.dll!

System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<ResolveConflictsAsync>d__1

7>(ref Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<ResolveConflictsAsync>d__17 stateMachine)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.ResolveConflictsAsync()	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.ResolveConflictsAsync

(Microsoft.CodeAnalysis.Rename.RenameLocationSet renameLocationSet, string originalText, string replacementText, Microsoft.CodeAnalysis.Options.OptionSet optionSet, 

System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!

Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.AbstractEditorInlineRenameService.InlineRenameLocationSet.GetReplacementsAsync(string replacementText = 

"STATUS_ANTIPASS", Microsoft.CodeAnalysis.Options.OptionSet optionSet = {Microsoft.CodeAnalysis.Options.OptionSet}, System.Threading.CancellationToken cancellationToken = 

IsCancellationRequested = false)	Unknown
 	mscorlib.dll!

System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.AbstractEditorInlineRenameService.Inlin

eRenameLocationSet.<GetReplacementsAsync>d__7>(ref 

Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.AbstractEditorInlineRenameService.InlineRenameLocationSet.<GetReplacementsAsync>d__7 stateMachine)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!

Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.AbstractEditorInlineRenameService.InlineRenameLocationSet.GetReplacementsAsync(string replacementText, 

Microsoft.CodeAnalysis.Options.OptionSet optionSet, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!

Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.UpdateConflictResolutionTask.AnonymousMethod__0()	Unknown
 	mscorlib.dll!

System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.(ref 

Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.<>c__DisplayClass61_0.<<UpdateConflictResolutionTask>b__0>d stateMachine)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!

Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.UpdateConflictResolutionTask.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task<Microsoft.CodeAnalysis.Editor.IInlineRenameReplacementInfo>>.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object 

state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool 

preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot = Id = 328901, Status = Running, Method = 

"System.Threading.Tasks.Task`1[Microsoft.CodeAnalysis.Editor.IInlineRenameReplacementInfo] <UpdateConflictResolutionTask>b__0()", Result = "{Not yet computed}")	

Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown

**Comment by jasonmalinowski** [comment]
I believe we've already fixed this through reports from Windows Error Reporting. @dpoeschl, does this look familiar?

**Comment by dpoeschl** [comment]
@radioman Thanks for reporting this. This happened to you during Extract Method? Does it happen all the time when you Extract Method, or just sometimes? Can you share a piece of code where Extract Method reliably causes this?

It looks very similar to #2352, but Extract Method would not construct the situation described in the reduced repro of that bug. I wouldn't be surprised if there were some single-document way of causing the same problem (of the declaration document not being included in the construction of ```reverseMappedLocations```), so I'm inclined to close this as a duplicate unless there's a repro available for us to test out.

**Comment by radioman** [comment]
VS2015RC crash if the extract method name contains already existing method name without hitting enter, meaning if you do a lot of refactoring and you type similar name and it has a match, yeah, good luck with that.. ;/ please fix in release

// program.cs
namespace ConsoleApplication1
{
    public struct Test
    {
        public int a;
        public int b;
    }

    partial class Program
    {
        static void Main(string[] args)
        {
            Test t = new Test();

            t.a = 1; // try extract method to RR2
        }
    }
}

// program2.cs
namespace ConsoleApplication1
{
    partial class Program
    {
        private static Test RR(Test t)
        {
            t.b = 8;
            return t;
        }
   }
}

**Comment by dpoeschl** [comment]
Thanks for the repro. It looks like the fix to #2352 will need to be updated to take partial types into account. Let's consider for 1.0 (stable).

**Comment by dpoeschl** [comment]
Adding reduced repro to the original post.

**Comment by dpoeschl** [comment]
Fix understood. Working on a review.

**Comment by dpoeschl** [comment]
@radioman Thanks again for the bug report! This has been fixed by #3303.

**Comment by radioman** [comment]
cheers! and thanks for roslyn, helps a lot.

**Comment by dpoeschl** [comment]
Brett, can you verify this? It's a similar case to #2352 which you looked at previously.
