### ISSUE TITLE
Simplify foreach when converted to LINQ (query and method forms)

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#33037]
Reported By @jfleisher  [ ported from [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/781662)

Affected Branch:  d16.0stg
Affected Build:  Preview3
Affected Product Language: 

**Steps to reproduce:**

LINQ generated when foreach is converted to query or method form contains an extraneous trailing Select.

**Example in method form:**

foreach(a in mylist){
   if(a.isUsed){
      doSomethingWith(a);
   }
}

**becomes:**
foreach(a in mylist.Where(a => a.isUsed).Select(a => a)){
  doSomethingWith(a);
}

**simpler form would be:**
foreach(a in mylist.Where(a => a.isUsed)){
  doSomethingWith(a);
}

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
