### ISSUE TITLE
Curious about Decimal implementation

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#33046]
I see something unexpected with Decimal types, look at this code:

```cs
                var dec1 = 100M;
                var dec2 = 100.00M;

                var ss1 = dec1.ToString();
                var ss2 = dec2.ToString();

```
If you run this and look at the resulting strings you'll see that ss2 ends with ".00" and ss1 doesn't. So even though 100 is numerically identical to 100.00 somehow the decimal type stores these differently.

I don't think this is a side effect of the fact that compiler can see (and perhaps eliminate the dec vars) because I see the same thing when passing decimals to external libraries.

How/why is that done?

Thx

**Comment by CyrusNajmabadi** [comment]
From the docs: https://docs.microsoft.com/en-us/dotnet/api/system.decimal?view=netframework-4.7.2#remarks

>  A decimal number is a floating-point value that consists of a sign, a numeric value where each digit in the value ranges from 0 to 9, and a scaling factor that indicates the position of a floating decimal point that separates the integral and fractional parts of the numeric value.

> The binary representation of a Decimal value consists of a 1-bit sign, a 96-bit integer number, and a scaling factor used to divide the 96-bit integer and specify what portion of it is a decimal fraction. The scaling factor is implicitly the number 10, raised to an exponent ranging from 0 to 28. Therefore, the binary representation of a Decimal value the form, ((-296 to 296) / 10(0 to 28)), where -(296-1) is equal to MinValue, and 296-1 is equal to MaxValue. For more information about the binary representation of Decimal values and an example, see the Decimal(Int32[]) constructor and the GetBits method.

> The scaling factor also preserves any trailing zeros in a Decimal number. Trailing zeros do not affect the value of a Decimal number in arithmetic or comparison operations. However, trailing zeros might be revealed by the ToString method if an appropriate format string is applied.

**Comment by Korporal** [comment]
OK I see its a fixed number of digits with a movable decimal point Thkx
