### ISSUE TITLE
Display localized string from the resource when hovering on the resource strings.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33055]
<p>It would be useful to lookup the actual resource strings whenever I hover over a Resource string object. this would help speed what the actual string values are. Would be nice if it worked with other resource types as well.</p><p></p><p>To elaborate the feature, If hover a resource object in the code it currently shows the comment of the property ErrorMessageText, would be cool if the actual resource string was displayed.</p><p></p><p>Resources.ErrorMessageText</p><p></p><p>Thanks in advance</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/412450/display-localized-string-from-the-resource-when-ho.html
VSTS ticketId: 754431_
_These are the original issue comments:_

Jane Wu [MSFT] on 12/19/2018, 08:24 PM (43 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>
SP on 12/19/2018, 08:25 PM (43 days ago): <p>Thank you very much for the quick response.</p>

Kendra Havens [MSFT] on 2/1/2019, 03:29 PM (2 min ago): <p>Thank you for filing this feedback! I think this information would make sense to show in quick info when hovering. I'm going to move this bug to our open source GitHub repo for further discussion with the community.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out as this works today with modern resx generator.  It does put the loc string in the summary text.  So you see this by default.
