### ISSUE TITLE
Nullable reference types cannot be enabled with project-wide <NullableReferenceTypes> tag

### ISSUE THREAD

**Issue by ssg** [dotnet/roslyn#33069]
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 2.1
VisualStudio.16.Preview/16.0.0-pre.2.1+28529.54
Microsoft .NET Framework
Version 4.7.03190

C# Tools   3.0.0-beta2-19068-12+231aeb8be8357239499d45c0574e5a9a8c9174f0
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

**Steps to Reproduce**:

1. Write this .NET Core console app using LangVersion = 8.0:

```csharp
using System;

class Program
{
    static T Foo<T>() => default;

    static void Main()
    {
    }
}
```

2. Add `#nullable enable` at the top of the source code. 
3. Get a compiler warning CS8603 for the function declaration.
4. Remove `#nullable enable` line and add `<NullableReferenceTypes>true</NullableReferenceTypes>` in the project, right after the LangVersion 8.0 tag.

**Expected Behavior**:
The same compiler warning when `#nullable enable` was used.

**Actual Behavior**:
No compiler warnings, therefore nullable reference types are not enabled for the project.

**Comment by ufcpp** [comment]
see https://blogs.msdn.microsoft.com/dotnet/2019/01/24/do-more-with-patterns-in-c-8-0/

> We’ve added more options to control nullable warnings both in source (through #nullable and #pragma warning directives) and at the project level. We also changed the project file opt-in to ´<NullableContextOptions>enable</NullableContextOptions>´.

**Comment by ssg** [comment]
@ufcpp thanks! that solves it for me.
