### ISSUE TITLE
I would like a refactor in the C# editor that will reflow a multiline comment at some margin.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33066]
<p>when editing a multiline comment, I often need to reflow the comment after I have edited it so that it can be more easily read.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/432431/i-would-like-a-refactor-in-the-c-editor-that-will.html
VSTS ticketId: 774419_
_These are the original issue comments:_

Jane Wu [MSFT] on 1/22/2019, 02:11 AM (10 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by sharwell** [comment]
Related to #15406

**Comment by CyrusNajmabadi** [comment]
Would lke to bring to review.  This plugin works very well, and it seems like it would be strange to try to duplicate everything it does for C#/VB when they already exist and work across all VS languages.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is well handled by an existing extension.  If a feature was to be added here, it should be requsted at devcom so it can come through as an editor request.
