### ISSUE TITLE
Compiler gives CS8158 on certain ref return methods with ref parameters

### ISSUE THREAD

**Issue by Thealexbarney** [dotnet/roslyn#33072]
**Version Used**: 
SDK 2.1.503 / Roslyn 2.10.0.0 (45b37117)

**Steps to Reproduce**:

```
public class Example
{
    private byte[] Data { get; set; }

    public ref int GetStructField(out int field)
    {
        ref MyStruct s = ref GetStruct(Data, out _);
        field = 9;
        return ref s.B;
    }

    private static ref MyStruct GetStruct(byte[] data, out int field)
    {
        ref MyStruct s = ref MemoryMarshal.Cast<byte, MyStruct>(data)[0];
        field = s.B;
        return ref s;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    private struct MyStruct
    {
        public int A;
        public int B;
    }
}
```

**Expected Behavior**:
Unsure. I don't know if this is by design or an issue with Roslyn. In any case, it seems odd or unintuitive to me.

**Actual Behavior**:
`CS8158 - Cannot return by reference a member of 's' because it was initialized to a value that cannot be returned by reference`

However, when I change `GetStructField` to this, it compiles.
```
public ref int GetStructField(out int field)
{
    ref MyStruct s = ref GetStruct(Data, out field);
    field = 9;
    return ref s.B;
}
```

**Comment by gafter** [comment]
You cannot return a reference to a local variable, as the local variable goes away when you return.

**Comment by Thealexbarney** [comment]
Except there aren't any local variables being returned, are there? Everything being referenced resides on the heap

**Comment by Thealexbarney** [comment]
Ah, I made a better example and now I see what's happening.
`Cannot use a result of 'Example.GetStruct(byte[], out int)' in this context because it may expose variables referenced by parameter 'outField' outside of their declaration scope`

```
public class Example
{
    private byte[] Data { get; set; }

    public ref byte FuncA(out int field)
    {
        field = default;
        int unused;
        return ref FuncB(Data, out unused);   // Error here
    }

    private static ref byte FuncB(byte[] data, out int outField)
    {
        outField = default;
        return ref data[0];
    }
}
```

`FuncB` could return a reference to `outField` which is `unused` on the stack.  
Doing `return ref FuncB(Data, out _);` unfortunately wouldn't change anything because it's just syntactic sugar for a temp variable.

**Comment by copygirl** [comment]
I hope it's not to late to point out this is an issue for me, as well. Suppose you have the following class:
```csharp
public class ArrayStore<T> where T : struct
{
    private static T _default = default(T);
    private readonly T[] _array = new T[10];

    public ref T Get(int index, out bool found)
    {
        if ((index >= 0) && (index < _array.Length)) {
            found = true;
            return ref _array[index];
        } else {
            found = false;
            return ref _default;
        }
    }

    public ref T GetOrThrow(int index)
    {
        ref var value = ref Get(index, out var found);
        if (!found) throw new InvalidOperationException();
        return ref value; // CS8157
    }

    public ref T GetOrThrow(int index, out bool ignoreMe)
    {
        ref var value = ref Get(index, out ignoreMe);
        if (!ignoreMe) throw new InvalidOperationException();
        return ref value; // No error.
    }
}
```
I previously found a comment or article explaining why this restriction exists, but unfortunately I can't for the life of me find it again. I believe it was something along the lines of ref parameters potentially creation a scenario where the returned reference would outlive what it's pointing at.

Though, doesn't the problem arise from specifically `ref` parameters passing in a value? Would an `out` parameter ever be able to cause such a problem?

There seem to be legitimate uses for this. For example I wrote a Dictionary-like class that returns references to its values with a single all-purpose `ref TValue TryGetEntry(Default|Create|Remove, TKey, out bool found)` method to cut down on code duplication: [`RefDictionary.cs`](https://gist.github.com/copygirl/a2e4ddfbe4eef2d4b03d84f732dd1de8) Similar to the above code, I can't wrap `TryGetValue` inside another method that still returns the same reference, without also including the out parameter in it.

**Comment by Thealexbarney** [comment]
The reason is that you're passing in a local variable as ref. The compiler doesn't know what Get is doing, therefore it has to consider the possibility that Get might return a reference to the reference `found` that was passed to it.

Since this is a local variable, Roslyn must limit the lifespan of the returned reference. If the reference `found` comes from outside the scope of `GetOrThrow`, then `found` won't be dead when exiting the scope, and the reference from `Get` can also leave that scope.

(I don't know how Roslyn actually deals with that all internally, but that's the gist of it.)

**Comment by copygirl** [comment]
I understand you can return a reference to a passed-in `ref` parameter, but is the same true for `out`? If that's not the case, what's in the way of allowing out parameters to be used in this way together with ref returning methods?

**Comment by gafter** [comment]
> I understand you can return a reference to a passed-in `ref` parameter, but is the same true for `out`?

[Yes.
](https://sharplab.io/#v2:CYLg1APgAgzABFATHAwnA3gWAFBzw+AJwFMAzOASwDsAXOAWQAoB7AVzuroA8BKHfDPwH4ucALxwYAbiHCEAdjglyXGbnwBfHBqA)
```csharp
public ref int M(out int x)
{
    x = 3;
    return ref x;
}
```

**Comment by copygirl** [comment]
Hm okay, so the only way to have this as a feature would be for the compiler to figure out the returned ref and ref parameter aren't related?

**Comment by gurustron** [comment]
JFYI it seems that later version of compiler supports the original version of the code - [@sharplab.io](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQCUCuAdgC4CWAtgKbYCSJlATgPYAOAyowG6kDGlAzgG5kyKAGZMMdAFEAHgENyLADaVkAb2Tpt6Fg1Kd5xSugBGAT2MBtALroAIkfnp16AOaVig9P0/eAviJIOpgSDJQAZuikJOgA4p5sxAz4PMQAYqSUysAAFEz4xNGxEVk5AJRaOprBITrhUQCy5kkpaT7oALzoDfGJyanEuY7E8gA06AVFAPrlwrV16KXZwF3oAJzzi9pQAOw9kT7YAEJbOoFIVdp6BkYmWABsB00tA+0JxK2DuRbWdsBOCZTYpFZYVK4uCEhXrNL7tfhrGGUchMBjmRryBj8AAW8mU2AAwvJ+MQADy/SgTWFvYgAPlyANG5SsqBsZ0WYNW3X4J3ZdT2zx8fIuEKscOIABl5OYprkpTLCgBpGLAbAcACO+EoJFIeImAAV5DwANZrAAs5RsEJuhmMPhp6GpbWIEJq21CIPQAEE+SFxJ7ThCLv4gA)
