### ISSUE TITLE
'Is Used By' navigation is broken in Solution Explorer

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#33087]
**Version Used**: Visual Studio 2019 Preview 2

:link: Originally filed as https://devdiv.visualstudio.com/DevDiv/_workitems/edit/192782

**Steps to Reproduce**:

1. From the Solution Explorer, expand a source file item, right click a class/interface in it, select "Is Used By" from the context menu. 
2. Double click any of the item on the list. 

**Expected Behavior**:

The IDE navigates to the item.

**Actual Behavior**:

Nothing happens.

**Comment by sharwell** [comment]
> Seems to be related to IGraphNavigateToItem extension which is implemented by [Roslyn](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Progression/GraphNavigatorExtension.cs).
> Essentially for UsedBy nodes there's no controller returned from that call in GraphNodeItem.cs.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
