### ISSUE TITLE
Peek Definition fails for UWP app

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#33085]
**Version Used**: Visual Studio 2017 15.9.5

:link: Originally reported as https://devdiv.visualstudio.com/DevDiv/_workitems/edit/183407

**Steps to Reproduce**:

1. Create a new UWP class library
2. Add the following code:

    ```csharp
    using Windows.UI;

    namespace ClassLibrary1
    {
        public class Class1
        {
            Color color;
        }
    }
    ```
 
3. Place the caret on `Color` and press <kbd>F12</kbd> (Go To Definition)
4. Place the caret on `Color` and press <kbd>Alt</kbd>+<kbd>F12</kbd> (Peek Definition)

**Expected Behavior**:

1. After step (3), metadata as source shows the definition for `Color`
2. After step (4), peek definition shows the definition for `Color`

**Actual Behavior**:

1. Step (3) works as expected
2. Step (4) shows **Error No information found**

**Comment by KGRWhite** [comment]
I'd like to work on this

**Comment by sharwell** [comment]
@KGRWhite :+1:

I'm not sure how easy or hard this item will be. Sporadic reports go back at least to ~2016 but there isn't much information that would indicate a cause. Hopefully it's something you can easily figure out from debugging, but otherwise please feel free to ask questions and I'll see what we can find out.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
