### ISSUE TITLE
Code fix for sealing a class

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#33092]
**Version Used**: Visual Studio 2019 Preview 2

📝 This was an internal feature request sent to the team. It is somewhat related to #31832, but does not deal with a specific compiler error.

**Steps to Reproduce**:

1. Create a class which is not sealed
2. Press <kbd>Ctrl</kbd>+<kbd>.</kbd> on the class name

**Expected Behavior**:

An option is provided to mark the class as `sealed`.

**Actual Behavior**:

No such option is provided.

**Comment by sharwell** [comment]
💭 I would be more in favor of updating the New Class templates to mark types as `internal sealed class` instead of just `class`. Also, avoiding typing one word doesn't seem worth the maintenance and code size tax described in https://github.com/dotnet/roslyn/pull/32422#issuecomment-454090088.

**Comment by CyrusNajmabadi** [comment]
> Also, avoiding typing one word doesn't seem worth the maintenance and code size tax described in #32422 (comment).

I agree.  Though i've come to be on the fence about this.  

Pros: people come to expect that ctrl-dot is the "read my mind and give me quick access to do whatever i want" feature.
Cons: The list gets so cluttered with random, low-impact, fixes.

I'd be *more* for if there was some different chord that opened these helpers.

**Comment by sharwell** [comment]
Design review conclusion: this refactoring would only save the user 7 characters, and the caret would need to already be on the line where `sealed` needs to be added in order to invoke the refactoring. It might be possible to perform solution-wide analysis at some point in the future and prompt the user to add `sealed` where possible, but the analyzer infrastructure required to implement this functionality *efficiently* is not currently in place. It might be suitable for an analyzer in dotnet/roslyn-analyzers, where work related to improving historically expensive analyzers is ongoing. For dotnet/roslyn, this issue is a **Won't Fix** due to minimal overall value add for what we can reasonably provide today.
