### ISSUE TITLE
Proposal: Parallel async

### ISSUE THREAD

**Issue by repinvv** [dotnet/roslyn#33091]
Typical function

```csharp
async Task<Result> MyFunc(){
var result1 = await getResult1();
var result2 = await getResult2();
var result3 = await getResult3(result1);
return CombineResult(result2, result3);
}
```

it might be preprocessed to something like this. 

```csharp
async Task<Result> MyFunc(){
var __result1 = getResult1();   //1
var result1 = await __result1;  
var __result2 = getResult2(); // 2
var result2 = await __result2;
var __result3 = getResult3(result1); //3
var result3 = await __result3;
return CombineResult(result2, result3);
}
```

suggestion is to make those function calls float up during preprocessing, until there is a curly bracket found or an assignment to variable used as a parameter to function call

```csharp
async Task<Result>MyFunc(){
var __result1 = getResult1(); // 1
var __result2 = getResult2(); // 2
var result1 = await __result1;
var __result3 = getResult3(result1); // 3
var result2 = await __result2;
var result3 = await __result3;
return CombineResult(result2, result3);
}
```

Here 1 and 2 will automatically run in parallel, 3 will execute once 1 is finished.

This would be a breaking change, so new keyword might be used. Did not think it all through.

**Comment by gafter** [comment]
This appears to be a language proposal, which belongs in the repo csharplang
