### ISSUE TITLE
Code analysis is way slower than on VS2017

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33107]
The first thing that I noticed after a few minutes of using VS2019 (in compare to 2017)
is that code analysis - showing errors on error list is a way slower than on prev. version

e.g we have code like this:

```csharp
int test = 5;
test = 5;
```

then we change  &quot;test = 5;&quot; to

test = &quot;&quot;;

and it's being shown as an error on error list after around 2-3sec

meanwhile on VS2017 it's like 0.5-1sec

Any ideas how to speed it up?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/400631/code-analysis-is-way-slower-than-on-vs2017-3.html
VSTS ticketId: 740818_
_These are the original issue comments:_

Jinu Joseph [MSFT] on 12/10/2018, 11:47 AM (56 days ago): <p>Thank you for your feedback! Just tried this in latest 16.0.PReview1 and seeing  the results almost immediately. </p><p>We created a set of instructions for providing additional information which will help us track down the true source of the problems. (<a target="_blank"> https://github.com/dotnet/roslyn/wiki/Reporting-Visual-Studio-crashes-and-performance-issues#performance-issues </a>)</p><p>We look forward to hearing from you!</p>

Bart on 12/12/2018, 01:29 AM (54 days ago): Here's version with Visual Studio 2017
Bart on 12/12/2018, 01:29 AM (54 days ago): Here's version with VS 2019
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
This should be fixed in 16.0 Preview 2. Please open a new issue if you continue to observe it.

**Comment by mavasani** [comment]
Just tried on the latest Preview3 dogfood build and I cannot see the performance lag.
