### ISSUE TITLE
A lot of allocations coming in from SourceNamespaceSymbol.DeclaringSyntaxReferences

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#33129]
**Version Used**: 
2.10.0-beta2-63410-10 (but looks like it's the same in 3.0.0-beta2-19055-09)

**Steps to Reproduce**:

1. Run analyzers on a solution (in my case [this](https://github.com/mono/refactoringessentials/tree/monodevelop2) one)
2. Observe a lot of allocations coming in from SourceNamespaceSymbol.DeclaringSyntaxReferences

**Expected Behavior**:
These allocations should avoided if possible for namespaces? There is a comment in [GeneratedCodeUtilities](https://github.com/dotnet/roslyn/blob/a1805016f9a2fae804d69220a9179fba086ba98f/src/Compilers/Core/Portable/InternalUtilities/GeneratedCodeUtilities.cs#L24) which mentions this perf hit.

**Actual Behavior**:
A lot of allocations. They are coming in from [here](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs#L1537)

```
Stacktrace:

Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol+<>c.<.cctor>b__49_0(SingleNamespaceDeclaration d)
System.Collections.Immutable.ImmutableArray.CreateRange<TSource, TResult>(ImmutableArray<T> items, Func<T, TResult> selector)
Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.get_DeclaringSyntaxReferences()
Microsoft.CodeAnalysis.CSharp.Symbol.get_DeclaringSyntaxReferences()
Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.IsGeneratedCodeSymbol(ISymbol symbol)
Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.TryProcessSymbolDeclared(SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisStateOpt, CancellationToken cancellationToken)
Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.TryProcessEventCore(CompilationEvent e, AnalysisScope analysisScope, AnalysisState analysisStateOpt, CancellationToken cancellationToken)
Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<ProcessCompilationEventsCoreAsync>d__70.MoveNext()
```

This is one of the heaviest contenders while typing in VSMac.

**Comment by CyrusNajmabadi** [comment]
@Therzok is this still an issue that needs focus?

**Comment by Therzok** [comment]
I haven't had a chance to look at allocation traces on a version that didn't have the cancellation exception allocation spam.
