### ISSUE TITLE
Request: don't show so many built-in esoteric code actions

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3312]
Look at this picture.
![toomanyactions](https://cloud.githubusercontent.com/assets/3316258/7991910/7e6827e6-0ab0-11e5-8206-0a82ec3b6fa0.jpg)
I have just a simple problem (copied+pasted the method from one file to another, which is lacking the necessary Imports statement). But it gives me EIGHTEEN quick actions to choose from! One of them (the first) is obviously correct. The others are just noise, pretty esoteric, and overwhelming.

Can we simplify it down please? Maybe relegate the esoteric actions to a sub-menu?

**Comment by ljw1004** [comment]
I think that the Roslyn team should hold off from solving this through some general-purpose public framework/infrastructure for submenus.

Instead Microsoft should just set its own house in order first. Make sure the built-in code-actions that it provides are clear, and no more confusing that competitors. Make sure the right usability testing has been done. And in the first instance just have third-party analyzers show up in the top-level menu. That also has the advantage that it doesn't impact the APIs used by third-party analyzers.

Once there has been a release or two to prove that the ontology/usability of the built-in code actions is correct and simple enough, only then will it be the right time to open it up to third parties.

Incidentally, I think the problem is much worse for the build-in code actions. That's because the built-in actions are generally about refactoring, and there are always tens or hundreds of refactorings you can perform at any valid piece of code. Third-party analyzers seem to be more about detecting errors and fixing them, or giving best-practice guidance in code-aware libraries. These typically have only 0 or 1 actions you can perform on any valid piece of code.

**Comment by Pilchie** [comment]
Can we collapse the sets of 4 "generate type" options into one with flavors?

**Comment by dpoeschl** [comment]
As well as the three spell-check options into one with flavors...

**Comment by Pilchie** [comment]
Let's keep #5139.
