### ISSUE TITLE
Cannot see all parameters in intellisense

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#33128]
**Version Used**: Filed against Visual Studio 2013 Update 5

🔗 Originally filed as https://devdiv.visualstudio.com/DevDiv/_workitems/edit/202782

## Description

If you have a method with a large number of parameters, when calling the method the intellisense parameter prompt box is fixed and cannot display all required parameters. 

## Repro Steps

create a method with so many parameters, that when called from anther piece of code, the list extends beyond the popup window. 

## Impact

You have no way of knowing what parameters to supply, when method is inside an external lib.

**Comment by CyrusNajmabadi** [comment]
Trying this out, i can easily see up to 100 parameters:

![image](https://user-images.githubusercontent.com/4564579/218132764-646df16c-f13d-4e10-807b-8f896aca6601.png)

This seems entirely fine.  Methods that go beyond that are so much of an outlier that it's fine for us to have this as the experience.  We'd need a *lot* more feedback that this was some sort of common pattern to do anything here on this.
