### ISSUE TITLE
Warning 4014 (not awaited task) doesn't work properly when a method returns Task<Task>

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33126]
```csharp
public static Task ReturnTask() => Task.CompletedTask;
public static Task<Task> ReturnTaskOfTask() => Task.FromResult(Task.CompletedTask);


public async Task Main()
{
  ReturnTask(); // Gives warning - as expected
  ReturnTaskOfTask(); // Gives warning - as expected
  await ReturnTask(); // No warning - as expected
  await ReturnTaskOfTask(); // No warning - probably a bug
  await await ReturnTaskOfTask(); // No warning - as expected
}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/405018/warning-4014-not-awaited-task-doesnt-work-properly.html
VSTS ticketId: 748615_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by gafter** [comment]
We are tracking this at https://github.com/dotnet/roslyn/issues/35232
