### ISSUE TITLE
CodeRefactoringProvider is not loaded 

### ISSUE THREAD

**Issue by EgorBo** [dotnet/roslyn#33139]
**Version Used**: 
Visual Studio VS2017 15.9.7
Microsoft.CodeAnalysis.Analyzers: 2.6.3
Microsoft.CodeAnalysis.CSharp.Workspaces: 2.10.0

**Steps to Reproduce**:

1. Create a project from "Code refactoring (.NETStandard)" or "Analyzer with CodeFix (.NETStandard)" templates in VS.
2. Run `%projectName%.Vsix` - the Refactoring/CodeFix is loaded and works
3. Add an item to the Vsix project: Add/Extensions/"Tool Window" via VS -- it will add a window and AsyncPackage to the Vsix project
4. Run `%projectName%.Vsix` again - the refactoring or CodeFix won't be loaded, breakpoints won't work

I tried different parameters in `source.extension.vsixmanifest` (in Asset node) but without luck.
This issue looks similiar to https://github.com/dotnet/roslyn/issues/22765 but `Update` didn't help. Tried VS2017 15.9.6 and 15.9.7

**Comment by jmarolf** [comment]
It is likely that the MEF catalog is failing to compose. If you turn on first chance exceptions and debug Visual Studio can you observe any exceptions?

Also, could you post your `source.extension.vsixmanifest` file?

**Comment by EgorBo** [comment]
@jmarolf found the problem - the `%projectName%.Vsix` project has AssemblyName=`%projectName%` instead of `%projectName%.Vsix`. If rename it to `%projectName%.Vsix` before the 3rd step - everything works fine. Could not find the templates in this repo though.

**Comment by sharwell** [comment]
@EgorBo The templates are in [dotnet/roslyn-sdk](https://github.com/dotnet/roslyn-sdk).
