### ISSUE TITLE
Continuing typing too fast after running "Add using" doesn't add the code fix

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#33140]
**Version Used**: 
15.9.6, 16.0.0 RC

**Steps to Reproduce**:

1. Write code that can be fixed by adding a using
2. Run the Add Using code fix
3. Immediately continue typing

**Expected Behavior**:
The new using directive should be added every time.

**Actual Behavior**:
Depending on the timing between 2. and 3. there are three different outcomes.
1. If you are slow enough, the using will always appear and the next edit is also present
2. If you are way too fast, the using is added, but the next edit is discarded (with a Windows notification sound)
3. If you hit the right timing, the using isn't added, but the next edit is present.

Needless to say, that this is quite counter productive for my muscle memory :)

The following gifs show with the cursor behind the closing bracket of `List<int>` the same key presses each time namely: `<CTRL+.>` `<RETURN>` `<SPACE>`

Slow enough (case 1)
![add-using-everything](https://user-images.githubusercontent.com/1947968/52273041-e94c8100-2948-11e9-9911-f609f779c57d.gif)

Too fast (case 2)
![add-using-no-edit](https://user-images.githubusercontent.com/1947968/52273145-3c263880-2949-11e9-90a9-314cbdcadfb1.gif)

Middleground (case 3)
![add-using-no-using](https://user-images.githubusercontent.com/1947968/52273155-46483700-2949-11e9-9c6e-d499069a5813.gif)

**Comment by jmarolf** [comment]
This is likely a race condition in applying the codefix.  By the time the codefix is calculated the solution snapshot is changed and can no longer be applied.

**Comment by CyrusNajmabadi** [comment]
IIRC, the editor themselves did something to make things non-blocking here.  That does lead to the situation (as @jmarolf pointed out) where keystrokes can enter in before the application of the fix.  The applicaiton then says "things changed, so i'm going to bail out so you don't lose work".

I think we'd need to pull in Christian or Oleg to help out here as i don't think this is on the Roslyn side.

**Comment by miloush** [comment]
I am running into this all the time. I believe I have already reported this before - I have suggested to make the edits local, so that it does not replace the whole document (which might also fix #10938). Cyrus preferred changes on VS side to make the quick fix edits synchronous. Could that be done only for the document currently being edited? I guess applying fix to other documents should still be async...

**Comment by Tragetaschen** [comment]
I think in the context of Blazor, this has become much more of a problem.

When I have been editing in a Razor file and then continue in a different C# file
a) CTRL+. frequently fails to open successfully and only shows a spinner
b) Even when it opened, a code fix like "Add using" has no effect, just like described as option 3 in the OP

**Comment by CyrusNajmabadi** [comment]
This should be fixed for C#.  For razor, this is handled by teh razor team through LSP and would have to be reported to them directly.
