### ISSUE TITLE
Visual Studio hangs with switch expression

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/roslyn#33144]
**Version Used**: 
Visual Studio 2019 16.0 Preview 3 (28604.53.d16.0)

**Steps to Reproduce**:

1. Create a C# project
2. Write the following code that uses `switch` expression
```c#
string path = "" switch { }
```

**Expected Behavior**:
When typing `{`, Visual Studio should auto complete `}`, and the cursor should be in between the braces.

**Actual Behavior**:
Visual Studio hangs; and restarts automatically after around 2 minutes.
![image](https://user-images.githubusercontent.com/12908526/52291273-dcb73100-2926-11e9-8802-325ede3cf219.png)

**Comment by jinujoseph** [comment]
cc @gafter

**Comment by gafter** [comment]
Dup of #32749 with a PR to fix it awaiting approval in https://github.com/dotnet/roslyn/pull/32755
