### ISSUE TITLE
Autobrace completion should trigger autoformatting

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#33154]
Reported by Ben Randall ( internal customer) 
![autobasefix](https://user-images.githubusercontent.com/12449387/52309763-00de3680-2956-11e9-8b37-d1591633d787.gif)

I should get the same experience with auto-brace completion what happens when i type in "}" and format my condition above.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
