### ISSUE TITLE
Inline temp for an array literal with anonymous types in the initializer doesn't work

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#3315]
Inline temp local `linked` below:

``` vb
Option Strict Off
Imports System.Runtime.CompilerServices

Module Module1

    Sub Main()
        Dim linked = {1, 2, 3}.Reverse().Aggregate(
                If(False, New With {.head = CInt(Nothing), .tail = Nothing}, Nothing),
                Function(total, curr) New With {.head = curr, .tail = CObj(total)})

        Dim f = linked.Select(Function(x) x - 1).ToArray()
        Dim plus =
            From x As Integer In linked
            Let y = x + x
            Order By y - x, x - y
            Select x - 1

        For Each p In plus
            Console.WriteLine(p)
        Next
    End Sub

    <Extension>
    Public Iterator Function [Select](Of TResult)(source As Object, selector As Func(Of Object, TResult)) As IEnumerable(Of TResult)
        While source IsNot Nothing
            Yield selector(source.Head)
            source = source.Tail
        End While
    End Function

End Module
```

**Got:**
![inlinetempbug](https://cloud.githubusercontent.com/assets/10605811/7993952/b4fb81e6-0abe-11e5-9c2b-54876761f734.png)

Seems like a bug in the Expander.

/cc @amcasey Thanks for reporting this issue!

**Comment by amcasey** [comment]
Alternatively, extract a local for ```{1, 2, 3}```.

**Comment by mavasani** [comment]
Andrew pointed another issue: If we go ahead and apply the refactoring, even in presence of conflicts, an assert is fired about "Code action introduced error in error free code". We should probably guard the assert [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/CodeActions/CodeActionEditHandlerService.cs,182) to be invoked only for non-conflict code action applications.

**Comment by dpoeschl** [comment]
@mavasani - That's a debug-only assert so we notice when the fix applied turns code without errors into code with errors, which is what happened here. Seems like it's working as designed.

For the original issue, does expand/reduce generally not know what to do with anonymous types?

**Comment by mavasani** [comment]
@dpoeschl Agreed, but the assert might be less noisy if not fired for cases where the refactoring already detected conflicts and user decided to ignore them.

@srivatsn Might have more context about your question regarding anonymous types in expand/reduce.

**Comment by DustinCampbell** [comment]
Moving to 1.1. I have a hard time seeing this meet the bar for stabilization. Let me know if you disagree.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in this area.
