### ISSUE TITLE
RenameRewriter infinite loop in bad code

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#3316]
Rename ```p``` (e.g. to ```q```).

```VB
Option Strict Off
Imports System.Runtime.CompilerServices

Module Module1

    Sub Main()
        Dim p As IEnumerable(Of Integer) = {1, 2, 3}
        Dim linked = Enumerable.Aggregate(Of Global.<anonymous type: head As Global.System.Int32, tail As Global.System.Object>)(
CType(CType(p, IEnumerable(Of Integer)).Reverse(), IEnumerable(Of Integer)), If(False, New With {.head = CInt(Nothing), .tail = Nothing}, Nothing),
                Function(total, curr) New With {.head = curr, .tail = CObj(total)})

        Dim f = linked.Select(Function(x) x - 1).ToArray()
        Dim plus =
            From x As Integer In linked
            Let y = x + x
            Order By y - x
            Select x - 1

        For Each p In plus
            Console.WriteLine(p)
        Next
    End Sub

    <Extension>
    Public Iterator Function [Select](Of TResult)(source As Object, selector As Func(Of Object, TResult)) As IEnumerable(Of TResult)
        While source IsNot Nothing
            Yield selector(source.Head)
            source = source.Tail
        End While
    End Function

End Module
```

**Comment by amcasey** [comment]
In debug builds, there's an assert from the RenameRewriter about not expecting to be in a ```CType``` expression.  I'm not sure why an exception being thrown results in a retry.

**Comment by amcasey** [comment]
FYI @rchande @dpoeschl

**Comment by amcasey** [comment]
Incidentally, the bad code arose as a result of #3315.

**Comment by balajikris** [comment]
In debug bits, this results in a infinite loop of Assert fail dialogs, each new one popping up after ignoring the previous. In release bits, this brings up the wait dialog and is stuck computing conflicts information.

**Comment by amcasey** [comment]
I'm going to take a shot at this so @balajikris can work on other things.

**Comment by amcasey** [comment]
Same steps as above, but simpler code:

```VB
Module Module1

    Sub Main()
        Dim p As IEnumerable(Of Integer) = {1, 2, 3}
        Dim linked = Enumerable.Aggregate(Of Global.<anonymous type: head As Global.System.Int32, tail As Global.System.Object>)(
            CType(p, IEnumerable(Of Integer)), Nothing, Function(total, curr) Nothing)
    End Sub

End Module
```

**Comment by amcasey** [comment]
There seem to be two issues:
1. Why are we hitting that code path?  ```ctype``` is clearly not an invocation expression.
1. Why does hitting that code path result in an infinite loop?

**Comment by amcasey** [comment]
Oh, we're not actually throwing the exception - we're dropping it on the floor.

**Comment by amcasey** [comment]
When the exception is thrown correctly, VS crashes.

**Comment by amcasey** [comment]
![syntaxtree](https://cloud.githubusercontent.com/assets/10508071/8068996/63c2d29c-0eac-11e5-8030-287efc0ef825.png)

**Comment by amcasey** [comment]
Parsing error recovery made the ```CType``` the receiver of a call.

**Comment by amcasey** [comment]
The equivalent C# code just no-ops, so I'll copy that approach.

**Comment by amcasey** [comment]
@balajikris, can you please verify?
