### ISSUE TITLE
Improve spell-check

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#33163]
**Version Used**: VS 2019 Preview 2.1
Copying a customer request.

**Steps to Reproduce**:
```csharp
const string connnectionString = "TBD";
```

**Expected Behavior**:
Get codefix to correct typo in `connnectionString` to `connectionString` or add the new word to a dictionary as an accepted spelling.

**Actual Behavior**:
No spell check.

**Comment by sharwell** [comment]
Duplicate of #24963
