### ISSUE TITLE
check other calls for Incorrect IDE0004 "Cast is redundant" - https://github.com/dotnet/roslyn/pull/32467

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#33176]
there are other missing check we need here - https://github.com/dotnet/roslyn/pull/32467#pullrequestreview-192737910

**Comment by zaytsev-victor** [comment]
@heejaechang it wasn't broken I think. I've added tests for this in this [commit](https://github.com/dotnet/roslyn/pull/32467/commits/11203fb12b8e4fc6fd1456e7921f3dfbe58f4111). Or it another case?
