### ISSUE TITLE
Allocations while typing from lambda captures in SymbolTreeInfo incremental analyzer

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#33172]
**Version Used**: 
2.10.0-beta2-63410-10 (but looks like it's the same in 3.0.0-beta2-19055-09)

**Steps to Reproduce**:

**Steps to Reproduce**:

1. Run analyzers on a solution (in my case [this](https://github.com/mono/refactoringessentials/tree/monodevelop2) one)
2. Observe a lot of allocations coming in from SymbolTreeInfoIncrementalAnalyzerProvider+IncrementalAnalyzer.UpdateReferencesAync

**Expected Behavior**:
Lambda captures and iterators should be avoided.

**Actual Behavior**:
They are not.

They're causing up to 10MB out of the 100MB allocated during typing in one of my traces (delegate captures, enumerator boxes)

Not much we can do to simplify code, but splitting methods into CurrentProcess/RemoteProcess will at least mitigate the allocations for the in process version.

**Comment by Therzok** [comment]
I'm opening a PR for this.

**Comment by CyrusNajmabadi** [comment]
Something is strange here.  We should only be running this code across projects once, until they change.  I'm really curious why we're seeing so many allocs.  It seems to indicate a potential bug elsewhere.  For example, maybe the analysis subsystem is calling into this incremental analyzer far too many times?  I think we need to root-cause this first, before we attack what may just be a symptom.

**Comment by Therzok** [comment]
Closing the issue, PRs were merged.
