### ISSUE TITLE
PackageInstallerFactory::ProcessProjectChange should only process projects that are ready

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#33187]
When we query NuGet for package information to cache, if the project is not ready NuGet will throw an `InvalidOperationException`. The API necessary to query if the project is ready to be queried is not currently available. This issue is to track updating the logic once the correct API is available and we can accurately determine that calling `GetInstalledPackages` should succeed.

**Comment by ryzngard** [comment]
@jinujoseph @heejaechang this is tracking our need for the platform API. Is there another issue we can reference as a dependency for this?

**Comment by jinujoseph** [comment]
Tagging platform API tracking work item [User Story 690719](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/690719): OP: API to check if solution load stage is in progress

**Comment by CyrusNajmabadi** [comment]
@ryzngard i don't think this is an issue anymore.  Can we close this out?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of response.
