### ISSUE TITLE
Bad Error in Recursive Pattern with Indexed Properties

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#33189]
https://github.com/dotnet/roslyn/pull/33178#discussion_r254487264

See IsPattern_BadRecursivePattern_03. The error reported on the `get` accessor is unclear, as there is a `get` member available, but because it's an indexed property it doesn't work correctly.

**Comment by gafter** [comment]
Treating as a dup of the more general issue https://github.com/dotnet/roslyn/issues/45659
