### ISSUE TITLE
investigate failing OptProf Tests

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#33180]
these 3 OptProf tests are kept failing. see why they are failing.

![image](https://user-images.githubusercontent.com/1333179/52370362-8837b280-2a07-11e9-8468-95c23b1474d7.png)

https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=250651&environmentId=1081950&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&_a=release-environment-extension

**Comment by genlu** [comment]
Closing old OptProf issues. No longer relevant
