### ISSUE TITLE
Convert tuple to struct suggestion only shows up on the single open parentheses character

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#33195]
**Steps to Reproduce**:
```csharp
class Test
{
    void Method()
    {
        var t1 = (a: 1, b: 2);
    }
}
```

If you position the mouse cursor before the first parentheses of the tuple, there is an option to convert the tuple to a struct.  This seems to be the only location where the quick fix suggestion pops up.

This ends up making this feature hard to find, I was looking for it specifically and it took some time to figure out exactly how to trigger it.

**Expected Behavior**:
It seems like it would be better if this suggestion was offered anywhere in between (and including) the tuple's parentheses

**Actual Behavior**:
Suggestion is only offered when cursor is placed directly before the first of the tuple's parentheses.

**Comment by CyrusNajmabadi** [comment]
A general concern in this space is that expressions can be quite large, and you don't want random refactorings for outer expressions showing up in nested locations.

Options that could help would be to make this avialable on the `name:` portion of hte tuple.

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  Isee the feature offered everywhere in that tuple.
