### ISSUE TITLE
Intellisense for RegexOptions enum displays '&quot ;' instead of a quote character.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33200]
<p>Visual Studio Version 16.0.0 Preview 2.2</p><p></p><p>Project type : Console App (.Net Core) C#</p>

![image](https://user-images.githubusercontent.com/12449387/52400607-77715600-2a74-11e9-91b9-168b5e7877b0.png)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/446966/intellisense-for-regexoptions-enum-is-showing-quot.html
VSTS ticketId: 787623_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
This sounds like a bug in the documentation file for `RegexOptions` (where it contains `&amp;quot;` instead of `&quot;`). I just verified on a few projects that `"` appears properly in IntelliSense.
