### ISSUE TITLE
Add test to verify Add Imports is the only extension with priority = CodeActionPriority.High

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#33217]
@chborl Do we have some tests somewhere that grab all of our actions and confirm something like:

> No other extensions are using CodeActionPriority.High so AddImports will now always be listed first.

doesn't change in the future?

_Originally posted by @jasonmalinowski in https://github.com/dotnet/roslyn/pull/33214#issuecomment-461543988_

**Comment by CyrusNajmabadi** [comment]
Closing out as i don't think this sort of test is useful.  It's similar to our tests that say "we have 74 analyzers".  All they serve to do is force updating that test when a new analyzer is added.
