### ISSUE TITLE
Hint text for static string properties should show the static string

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33218]
<p>The hint text of a static string property or field by default only shows the name that field or property. It could show the static string that would be returned. Since it doesn't do this by default developers I work with frequently have ///&lt;summary&gt; comments containing just the string, it duplicates work and increases document size.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/444934/hint-text-for-static-string-properties-should-show.html
VSTS ticketId: 785538_
_These are the original issue comments:_

Blair Wang [MSFT] on 2/4/2019, 08:46 PM (2 days ago): Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.
Mika Dumont on 2/7/2019, 11:08 AM (20 sec ago): <p>Thank
you for the suggestion! I am going to move this to our open source repository
for a further design discussion with the community.</p>

**Comment by sharwell** [comment]
@Neme12 How do you like this as a small addition to the Quick Info support for constants that we've (mostly you 😄 )been working on?

**Comment by CyrusNajmabadi** [comment]
Note: this should likely only be for static-readonly strings.  Showing for any static string would likely be misleading as that might not at all be the value the string will actually be.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
