### ISSUE TITLE
Better experience for using compiler via nupkg and alternating between core and full msbuild

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn#33219]
Currently, there are two different compiler packages for full-framework msbuild and core msbuild, respectively.

However, consider that is common to work with both msbuilds in tandem. For example, alt-tab between command line where you use `dotnet` and VS.

The following seems like it would work:

``` xml
<PackageReference Include="Microsoft.Net.Compilers" Version="2.10.0" Condition="'$(MSBuildRuntimeType)' != 'Core'" />
<PackageReference Include="Microsoft.NETCore.Compilers" Version="2.10.0" Condition="'$(MSBuildRuntimeType)' == 'Core'"  />
```

But it doesn't quite. The problem is that the package used is determined at restore time and you can restore with one msbuild (e.g. `dotnet restore`) and build with another (e.g. `msbuild`)

When you do that, you get complicated errors like this:

```
C:\Users\nicholg\.nuget\packages\microsoft.netcore.compilers\2.10.0\tools\Microsoft.CSharp.Core.targets(52,5): 
error MSB4062: The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly
C:\Users\nicholg\.nuget\packages\microsoft.netcore.compilers\2.10.0\build\..\tools\Microsoft.Build.Tasks.CodeAnalysis.dll. 
Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or 
one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that 
the assembly and all its dependencies are available, and that the task contains a public class that implements 
Microsoft.Build.Framework.ITask.
```

Working around this is possible, but hacky. See https://github.com/dotnet/corefx/pull/35134/commits/9c7bf6731325e3d79af1b83742496173d840633d

I suggest one the following:

1. Make a single package that just works on both msbuilds.
2. Make the full-framework and core packages no-op on mismatched msbuilds. This way they can both be referenced without conditions. 
3. (2) + a meta-package that references both and behaves like (1) would.

cc @ericstj @tannergooding @agocke @jaredpar

**Comment by jaredpar** [comment]
Yeah I've thought about doing this a few times. I agree it would simplify a lot of builds out there.

**Comment by nguerrera** [comment]
Make note that approach (1) will require changes in CLI uptake of compiler. We currently take Microsoft.NETCore.Compilers wholesale. (2) is backwards-compatible and (3) provides the experience of (1) with a new metapackage without breaking anything.

**Comment by tannergooding** [comment]
I dont think (2) is very good in the scenario where you are depending on preview compilers, since nop would presumably mean it falls back to the built-on version.

**Comment by jaredpar** [comment]
The idea I'd been running with in my head was do (1) but continue to produce the existing ones for a time. Then say six months down the road remove the existing indepdent ones. 

The reason for wanting this is these packages are already fairly hard to maintain. I can't imagine trying to add more complexity here for something which is only meant for internal consumption. The few internal customers we actually support can be transitioned off then we can move to a single san package.

**Comment by nguerrera** [comment]
Yeah, that works and means we converge to the simplest, pit-of-success option in the long term. 👍
