### ISSUE TITLE
Deprecate GetSymbolInfo and add identical but renamed GetReferencedSymbolInfo

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#3322]
I consistently make the mistake of calling `GetSymbolInfo` on a method declaration when I should have called `GetDeclaredSymbol`. The name `GetSymbolInfo` doesn't warn me away from using it on declarations -- IOW, the name doesn't tell me to use it only on references.

I suggest you deprecate `GetSymbolInfo` and add `GetDeclaredSymbol` (which can just call `GetSymbolInfo`). The message of the now-deprecated method can tell me to use the more explicitly named method instead -- or at least, if I insist on using `GetSymbolInfo`, to be really sure that this is a reference and not a declaration.

**Comment by AnthonyDGreen** [comment]
We've had a number of discussions about this problem over the years. We had several proposals including renaming GetSymbolInfo as you suggest or folding the functionality of GetDeclaredSymbol into GetSymbolInfo. Ultimately last year we elected to leave them as is feeling that grabbing a symbol from the declaration tree (GetDeclaredSymbol) was a very different operation than invoking the binder and potentially reporting all kinds of semantic errors (GetSymbolInfo). That's the case for leaving them separate. As for the name, the use of GetSymbolInfo is so widespread at this point (and was still so last year) that deprecating it would put a huge burden on anyone who's built anything with Roslyn until now.

I'll propose a softer deprecation. We won't report use-site errors but we can add a GetReferencedSymbolInfo method and merely hide the existing method using EditorBrowsable(Hidden) and update the comment. Current consumer's code will continue to work but IntelliSense will naturally guide people away from that method over time. Perhaps we can consider a QuickFix which aids in migrations as well.

@mattwar, what do you think?

**Comment by lgolding** [comment]
For the sake of correctness, let me fix my mistake above -- although Anthony clearly understood what I actually meant:

"I suggest you deprecate `GetSymbolInfo`  and add  `GetReferencedSymbol` (which can just call `GetSymbolInfo`)."

`GetDeclaredSymbol` is just fine.

I like Anthony's suggestion.

**Comment by CyrusNajmabadi** [comment]
We need an actual API proposal (that goes through our documented process here).  Furthermore, we're really not going to deprecate a core API here that works well and is used in tons of places.  The duality of declaration/reference, and the corresponding split for our APIs is part and parcel of hte roslyn semantic model operations and is not going to change without dramatic need.

**Comment by CyrusNajmabadi** [comment]
We need an actual API proposal (that goes through our documented process here).  Furthermore, we're really not going to deprecate a core API here that works well and is used in tons of places.  The duality of declaration/reference, and the corresponding split for our APIs is part and parcel of hte roslyn semantic model operations and is not going to change without dramatic need.
