### ISSUE TITLE
Deconstruction tooltip and auto complete

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#33236]
Remembering the signature of a class deconstructor is difficult, and it is a wast of time to view the deconstructor code each time we want to use it.
```
var (x, y, z) = obj;
```

I suggest two things:
1- view a tooltip displaying the deconstructor signature when we hover over the obj variable, so we can adjust the syntax on the left side.
2- add some sort of auto complete For examole, when we write:
`() = obj`
then press Tab twice, the editor recognizes this is a deconstruction syntax and writes the right formula on the left side, such as:
`(int x, string y, bool z) = obj;`

**Comment by CyrusNajmabadi** [comment]
@MohammadHamdyGhanem Would you be interested in contributing improvements here?

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
Believe me syrus, I want to, but I'm sinking right now in JavaScript trying to reach the shores of ASP.NET! I hope someday I can contribute in VB.NET to add the missing features or make it work outside windows, even use Xaml and VB.NET to write ASP.NET pages!
I hope I can get there soon.
Thanks.

**Comment by RikkiGibson** [comment]
have been hitting this one recently, might like to take a look or at least propose something.

**Comment by CyrusNajmabadi** [comment]
Closing ouot due to lack of broader feedbback on this.
