### ISSUE TITLE
Cannot be used in a project built with VS2015

### ISSUE THREAD

**Issue by ygoe** [dotnet/roslyn#33245]
**Version Used**: 
2.10.0 (NuGet)

**Steps to Reproduce**:

1. Create a WPF .NET 4.6.2 project with VS2017 and install this NuGet package
2. Add real busieness code
3. Copy the source code to a machine with nothing but .NET 4.6.2 + SDK and VS2015
4. Build with VS2015

**Expected Behavior**:
Builds

**Actual Behavior**:
Does not build because suddenly it can't find types like `Func<,>` or the `>` operator of `int` or `IList<>`. It recommends me to add a reference to "netstandard 2.0.0.0". I don't have that DLL laying around here. Seems like the Roslyn package broke all project references.

The project worked everywhere before, without the Roslyn package. It has 300k LoC in 800 source files.

**Comment by ygoe** [comment]
I've tried to follow the suggestion and add a reference to "netstandard 2.0.0.0". The best thing I could think of was installing the NuGet package "NETStandard.Library 2.0.3" and then update the one outdated dependency it has, "Microsoft.NETCore.Platforms". This increased the number of build errors from around 20 to (more realistic) 4000. They all have the same messages as described above. I'm not sure what that package does, its description is unclear.

My project still has no assembly reference to some "netstandard" and I can't find it anywhere. I would assume it's not required because .NET Framework 4.6.2 already implements that. At least that's what you said when .NET Standard came out.

As a side note: When I build the project with VS 2017 and create the setup package, including the 108 extra DLLs that Roslyn requires (!), the program will run perfectly on a clean Windows 10 and Windows 7 machine. It's just the build with VS 2015 that is causing problems.

PS: I'm sitting here waiting because the work needs to be done. I could do it in my VS 2017 but the client will have to be able to work with his VS 2015 installation.

**Comment by ygoe** [comment]
One more confusing update: I installed the .NET Framework 4.7.0 SDK through Visual Studio (the runtime was already there and could not install) and switched the project to target 4.7.0. I reinstalled all NuGet packages as suggested. Now the build worked fine and the program worked as expected, including Roslyn Scripting.

Now I changed the project back to 4.6.2 and again reinstalled all NuGet packages. The project now also builds (unlike before the 4.7.0 excursion), but it fails to run. The program starts, but the Roslyn Scripting call fails because it can't find the System.Linq assembly (which is already used elsewhere in the program, so it's only Roslyn that fails, not the host app).

I don't know why the build now works when it didn't before. Maybe the existence of the 4.7 SDK changed the environment enough to cause this effect. I verified that the project file is identical to the initial code (switched to 4.7 and back). So there are no leftovers in the project file itself.

I'll try to raise the program's requirements to .NET Framework 4.7 to make this part work. But it's definitely unexpected that Roslyn targeting .NET Standard as low as 1.3 fails with .NET Framework 4.6.2 (if only on VS 2015, not 2017), including errors asking me to add .NET Standard 2.0 (no idea where that version comes from, probably one of the hundred dependencies of Roslyn).

**Comment by ygoe** [comment]
Even more confusing behaviour: I've continued working on the application. Everything's fine in VS 2017. When I copy the new code to the VS 2015 environment that previously worked after upgrading the project from .NET 4.6.2 to 4.7, it fails again. Changing the framework from 4.7 to 4.6.2 and back to 4.7 again doesn't help.

This Roslyn package is completely unusable with VS 2015! And the requirements don't indicate that. In fact they say it should be working just fine (targeting .NET Standard 1.3 on the label, but wanting "netstandard 2.0.0.0" when building). That's a major issue that needs some attention!

I have to recommend my client to either spend money on the 2017 version now, or wait a few months for the upcoming 2019. But further development is currently stopped on their side! A very unexpected and unfortunate state.

**Comment by gafter** [comment]
Projects created with or upgraded to a newer version of Visual Studio may not work with earlier versions.  That's because we add features (e.g. to the project files) and use those features.

**Comment by ygoe** [comment]
I don't think you understood the issue. At least your explanation doesn't sound plausible to it. But anyway, all machines are now updated to VS 2017 so it works everywhere.
