### ISSUE TITLE
Do not suggest static members in property pattern clause context

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#33250]
**Version Used**: 2019 P2

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/3105979/52478249-08057e80-2bba-11e9-947a-3023b3c1b29a.png)

Also upon selection I expect the colon to be inserted too, since it appears on the list.

**Comment by YairHalberstadt** [comment]
Fix in https://github.com/dotnet/roslyn/pull/35220

**Comment by genlu** [comment]
> Also upon selection I expect the colon to be inserted too, since it appears on the list.

I looked at the existing completion providers that have a suffix for items, it seems they all following the same pattern, i.e. not committing the suffix. So I will not fix this to keep it consistent for now. I will create a new issue for design discussion on whether this is the right pattern we want to stick to.
