### ISSUE TITLE
Fix Formatting code fix appears above Add Using, breaking user muscle memory

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#33255]
**Version Used**: Dev16 Preview 3

![image](https://user-images.githubusercontent.com/116161/52492045-50527b80-2b7d-11e9-81e6-540a5b896e39.png)

Trying to add using for `System.Diagnostics` in the screenshot above is broken because a space has already been typed, causing `Fix formatting` to appear. This is a very irritating muscle memory break!

**Comment by DustinCampbell** [comment]
Also, fix formatting is pretty contrived on this code anyway. It feels odd that we would offer that code fix for spans containing syntax errors.

**Comment by sharwell** [comment]
@chborl The ordering is fixed by #33214, right?

**Comment by chborl** [comment]
> @chborl The ordering is fixed by #33214,

Yes, the using suggestion will appear at the top of the list.

**Comment by sharwell** [comment]
> Also, fix formatting is pretty contrived on this code anyway. It feels odd that we would offer that code fix for spans containing syntax errors.

@DustinCampbell Is this item important enough that you want it tracked separately? The main item you reported has already been fixed.
