### ISSUE TITLE
Include naming convention when exporting from Tools > Options to .editorconfig

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#33268]
Originally submitted on [developer community](https://developercommunity.visualstudio.com/content/idea/411815/include-also-naming-convention-when-export-to-edit.html).

**Version Used**: 
Visual Studio 2019 Preview 2

**Steps to Reproduce**:

1.  Create a naming rule in editor settings.
2. Export code style settings to editorconfig

**Expected Behavior**:
Editorconfig has generated naming rule that follows the [dotnet_naming](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions) conventions.

**Actual Behavior**:
Editorconfig does not export naming rules.

**Comment by jinujoseph** [comment]
Duplicate https://github.com/dotnet/roslyn/issues/30086
