### ISSUE TITLE
Essentially identifying if a method has an unreachable exit block

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#33270]
Requested by internal customer Alejandro Dominguez

**Comment by CyrusNajmabadi** [comment]
This needs more information.  We already warn (and the IDE fades out) unreachable code.  Could the customer explain what is mean by 'unreachable exit block'?

**Comment by CyrusNajmabadi** [comment]
Closing out for now.  If internal customer needs info (which hasn't happened in a year), this can be reopened.
