### ISSUE TITLE
VB Immediate Window Defaults to Latest Major Compiler Version

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#33274]
**Version Used**: 
15.9.6
**Steps to Reproduce**:
With any VB program running, break then in Immediate Window type ? followed by any function that takes more than 1 parameter and used named parameters for the first.

```VB
?FilterDiagnostics(Diags:=compilation.GetParseDiagnostics(), SeverityToReport, ErrorsToBeIgnored).
```
error BC30241: Named argument expected. Please use language version 15.5 or greater to use non-trailing named arguments.

**Expected Behavior**:
VB should use latest compiler version for immediate Window, or the Language Version of the project the break occurs, or allow the user to specify. My preference is to fix this issue by setting the language version using the order listed. @davkean thinks it should be Latest https://github.com/dotnet/project-system/issues/3733#issuecomment-461775442
**Actual Behavior**:
It appears Language Version is set to Last Major, causing errors parsing the immediate windows when code is copied from application and pasted in Immediate Window.

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/32799
