### ISSUE TITLE
'if' statement with lambda CANNOT be simplified in C#

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33284]
VSF_TYPE_MARKDOWNThe Visual Studio 2019 (Preview 2) IDE suggests **IDE0045** _'if' statement can be simplified_:

```csharp
    if (containsHighBits)
    {
        write = (char character) => writer.WriteUInt16BigEndian(character);
    }
    else
    {
        write = (char character) => writer.WriteByte((byte)character);
    }
```

Of course, the resulting code gets underlined with a red wavy line. This refactored code does not compile:

```csharp
    Action<char> write = containsHighBits
        ? ((char character) => writer.WriteUInt16BigEndian(character))
        : ((char character) => writer.WriteByte((byte)character));
```

New error: **CS0173** _Type of conditional expression cannot be determined because there is no implicit conversion between 'lambda expression' and 'lambda expression'_

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/444056/if-statement-with-lambda-cannot-be-simplified-in-c.html
VSTS ticketId: 785223_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by YairHalberstadt** [comment]
This should be legal once https://github.com/dotnet/csharplang/issues/2460 is implemented, so it may not be worth doing the fix.

**Comment by CyrusNajmabadi** [comment]
Closign out as this is legal in the language now.

**Comment by CyrusNajmabadi** [comment]
Reopening as i want to add a tst demonstrating htis.
