### ISSUE TITLE
Roslyn fails to apply inferred type arguments' nullability after `?.` access

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#33289]
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 2.1
VisualStudio.16.Preview/16.0.0-pre.2.1+28529.54
Microsoft .NET Framework
Version 4.7.03056

**Steps to Reproduce**:

Compile and run the following code:
```cs
#nullable enable
struct C<T>
{
  public T FieldWithInferredAnnotation;
  public string? ExplicitlyAnnotatedField;
}
class C
{
  static void Main()
  {
    Test(null);
    System.Console.ReadKey();
  }

  static void Test(string? s)
  {
    var nc = M(s);
    nc?.FieldWithInferredAnnotation.ToString(); // no warnings, the program crashes at runtime on this line
  }

  public static C<T>? M<T>(T t) => new C<T>();
}
```

**Expected Behavior**:
Warning `CS8602 Possible dereference of a null reference.` reported for at the line `nc?.FieldWithInferredAnnotation.ToString()`

**Actual Behavior**:
Roslyn fails to warn about possible dereference of a null reference in case of `?.` access to a generic field. The program crashes at runtime with a `NullReferenceException` on the line that doesn't have any warnings.

**Notes**
It looks like Roslyn fails to apply type arguments with inferred nullability after unwrapping a generic struct from `Nullable<T>` with `?.` access. 
Explicitly annotated fields e.g. `nc?.ExplicitlyAnnotatedField.ToString()` and direct unwraps from `Nullable<T>` via its `.Value` property e.g. `nc.Value.FieldWItnInferredAnnotation.ToString()` have correct warnings.

**Comment by jcouv** [comment]
The analysis of the `Test` method seems correct. In this scenario, `FieldWithInferredAnnotation` is a `string!`, so no warning. 
I think the problem is that a struct was initialized with a `null` in a non-nullable field, without producing any warning. The unsuspecting consumer of this struct trusts the API of the struct, but blows up as a result.

**Comment by TessenR** [comment]
@jcouv I believe that `FieldWithInferredAnnotation` should be inferred to be of type `string?` because `T` is `string?` in this case. I've added a second call to `M2` to the example below to demonstrate that `T` is of type `string?` and Roslyn seems to know about it.

I've also modified the initial example to explicitly initialize `FieldWithInferredAnnotation` with a value of type `T` so there's no default construct creation now. Nevertheless the result is the same - Roslyn fails to warn about null reference exception at runtime.

```cs
#nullable enable
struct C<T>
{
  public T FieldWithInferredAnnotation;
  public string? ExplicitlyAnnotatedField;

  public C(T t)
  {
    FieldWithInferredAnnotation = t;
    ExplicitlyAnnotatedField = null;
  }
}
class C
{
  static void Main()
  {
    Test(null);
    System.Console.ReadKey();
  }

  static void Test(string? s)
  {
    var nc = M(s);
    nc?.FieldWithInferredAnnotation.ToString(); // no warnings, the program crashes at runtime on this line
    var correctlyInferred = M2(s);
    correctlyInferred.ToString(); // CS8602 possible dereference of a null reference, correct
  }

  public static C<T>? M<T>(T t) => new C<T>(t);
  public T M2<T>(T t) => t;
}
```

**Comment by jcouv** [comment]
Ah, you're correct. `FieldWithInferredAnnotation` should indeed be inferred as `string?`. Thanks for the correction.
