### ISSUE TITLE
File end up in wrong folder when using "Move type to ..." quick action menu

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33283]
When using &quot;Move type to TypeName.cs&quot; from the quick action menu in c# projects, the new file is always moved to the root of the project structure instead of staying in the same folder (but the class/file retains the same namespace declaration as the source file).

This behavior appears at least when targeting .net framework 4.6. However if I create a new solution targeting .net standard 2.0 it behaves as expected and the new file end up in the same sub folder as the source file. It appears to depend on the selected targeted framework somehow.

Step by step to recreate (in VS 2019 preview 2.1):

1. Create a new solution with a new C# class library targeting .net framework 4.6, lets call it 'MyProject'
2. In the class library, create a subfolder 'Subfolder'
3. Add a class in that sub-folder (ex MyClass, full-name MyProject.SubFolder.MyClass in MyClass.cs )
4. Add another class in the same file (ex MyOtherClass)
5. Use the &quot;Move type to MyOtherClass.cs&quot;, from the quick action menu on the new class
6. The new file has ended up in the project root (MyProject/MyOtherClass.cs) instead of the expected subfolder (MyProject/SubFolder/MyOtherClass.cs)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/442713/file-end-up-in-wrong-folder-when-using-move-type-t.html
VSTS ticketId: 783601_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by ryzngard** [comment]
Not reproduced on VS version 16.1.0 Preview 1.0
