### ISSUE TITLE
Indentation after a comment indents more than expected

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#33282]
If you press return twice after a comment line in a class the second line is indented an extra level compared with the first line. Not sure if this is expected.

![image](https://user-images.githubusercontent.com/341098/52549837-84c07480-2dd5-11e9-920f-0a81a779ced9.png)

Original bug report: https://github.com/mono/monodevelop/issues/7047

**Comment by DavidKarlas** [comment]
Just wanted to comment that I can reproduce in Visual Studio 2017 version 15.8.4 and VS2019 preview 2.

**Comment by sharwell** [comment]
Duplicate of #3321
