### ISSUE TITLE
Avoid using IOperation.Children in OperationExtensions.Descendants

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#33290]
**Version Used**: Visual Studio 2019 Preview 2

**Steps to Reproduce**:

Rebuild Roslyn.sln while profiling allocations.

**Expected Behavior**:

`IOperation.Children` is never used directly on hot paths.

**Actual Behavior**:

`IOperation.Children` is used in `OperationExtensions.Descendants`, a very hot path during compile-time analysis.

https://github.com/dotnet/roslyn/blob/d260ee0c20ed31e1ef057bdc179a451e76cf24da/src/Compilers/Core/Portable/Operations/OperationExtensions.cs#L78-L101

**Comment by mavasani** [comment]
We can probably just use the operation visitor in the implementation

**Comment by 333fred** [comment]
This was fixed with my IOperation work.

**Comment by sharwell** [comment]
@333fred can you set the milestone?
