### ISSUE TITLE
Wrong "Remove unused parameter" suggestion when using compound assigments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33299]
VSF_TYPE_MARKDOWN
```csharp
 public static byte[] Combine(this byte[] first, byte[] second)
        {
            first ??= new byte[0];
            second ??= new byte[0];

            var ret = new byte[first.Length + second.Length];
            Buffer.BlockCopy(first, 0, ret, 0, first.Length);
            Buffer.BlockCopy(second, 0, ret, first.Length, second.Length);
            return ret;
        }
```

The light bulp says `first` and `second` arguments are **unused** but they not.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/447307/wrong-remove-unused-parameter-suggestion-when-usin.html
VSTS ticketId: 787940_
_These are the original issue comments:_

cihanyakar on 2/11/2019, 02:25 AM (9 hours ago): <p>A small info: C# 8.0 nullable feature is enabled</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jnm2** [comment]
I'm hitting this. I almost filed a new bug since I read 16.1.P1 as 16.0.P1.

**Comment by Zenexer** [comment]
Does 16.1.P1 refer to the Visual Studio version?
