### ISSUE TITLE
x64 app with references to x86 dlls

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/roslyn#33294]
Why can't Roslyn run x634 apps that have some x86 components?

**Version Used**: 
VS.NET 2019 Preview 2.2
**Steps to Reproduce**:
I created a simple console app (compiled as X64), and added two trivial .net standard library projects to it, one compiled as x64, and the other as x86. 
**Expected Behavior**:
Run normally!
**Actual Behavior**:
When I run the app, it breaks with this message:
>Your app has entered a break state, but no code is currently executing that is supported by the selected debug engine (e.g. only native runtime code is executing).

and the exception window shows:
> System.BadImageFormatException: 'Could not load file or assembly 'ClassLibrary2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.'

I don't understand why does this happen? Windows 64bit itself can run 32bit apps! Why don't Roslyn have some bridge to run 32 bit dlls on 64bit aps? Even more: why can't it run 64 bit dlls on 32bit apps? these dlls are not true machine code, and they are compiled by JIT compiler, so, is it possible to do something in this stage to bridge the gab?

Otherwise, It will be better to give the programmer a hint from the begging that mixing different platforms in the same app will not work.

**Comment by huoyaoyuan** [comment]
As I know, both x86 and x64 apps can lives in same **OS**, but one **process** must be either x64 and x86, and x64 process cannot run x86 code or dll. This is a rule of Windows.
For CLR, managed only code can be definitely bridged, but there's an AnyCPU config for this scenario. When architecture specified assemblies are used, it means it would operate unmanaged stuffs.
I remember that the compiler does produce a warning for wrong reference architecture.

**Comment by strongrex2001** [comment]
What @huoyaoyuan said was correct. You can compile your project down to x86 and you can run them normally.

**Comment by MohammadHamdyGhanem** [comment]
@huoyaoyuan , @strongrex2001
If I am the owner of the dll source code, sure I can fix such problems, but there are legacy .net dlls which are 32 bits, and they will force us to compile our new apps as x86 if we want to use them! This becomes worst if you have an x64 dll and an x86 dll that you don't have thier source codes and want to use them in same project!
So, I think Roslyn should find a way to solve such problems. JIT can compile x86 to x64 native code if the main app is x64, and vice versa. If there is an unmanaged component, then VS.NET must force all app components to target the same platephorm as that  unmanaged component.
I don't have enough details about the differnce between x86 and x64 IL codes, but if the difference is just some header format or attribute value, then I think solving this incompatabily should be easy.

**Comment by MohammadHamdyGhanem** [comment]
@huoyaoyuan:
> x64 process cannot run x86 code or dll

Can't Roslyn create a temp process to run the x86 dll and make it communicat with the x64 process? In other words: Wrap the dll in a siutable process?
I don't know if this is can be done or be practical. I have no enough knowlage about this, but I faced such a prblem in practice once, and I had to compile to x86 to solve it. This can be impossible if I deal with both x86 and x64 dlls in same project and have not theie source codes.

**Comment by jmarolf** [comment]
> JIT can compile x86 to x64 native code

Sounds like this is a request for a JIT/runtime feature.  This should go in the https://github.com/dotnet/coreclr repo

**Comment by MohammadHamdyGhanem** [comment]
@jmarolf
Thanks. I copied it there also:
https://github.com/dotnet/coreclr/issues/22547

**Comment by jmarolf** [comment]
alright I'll close this one as there is nothing the compiler can do to support this scenario

**Comment by MohammadHamdyGhanem** [comment]
@jmarolf  
Maybe there is: 
> give the programmer a hint from the begging that mixing different platforms in the same app will not work.
