### ISSUE TITLE
custom vs color scheme keeps reseting every upgrade of Dev16

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33301]
I have the solarized light VS color scheme applied to my VS and everytime I update to the latest dogfood build, the syntax highlighting colors gets reset to the default color scheme (i.e. not my custom color scheme). My current workaround is to reapply my vssettings file, but this is getting old having to do this every time I update to the latest build.

The vssettings file can be found at: https://github.com/leddt/visualstudio-colors-solarized/blob/master/vs2017/solarized-light.vssettings

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/433259/custom-vs-color-scheme-keeps-reseting-every-upgrad.html
VSTS ticketId: 775477_
_These are the original issue comments:_

John Schultz [MSFT] on 1/24/2019, 09:29 AM (18 days ago): <p>Update: </p><p>Not sure this has anything to do with upgrading now. I have noticed that it only impacts C# code (C++ always using my custom color scheme) and it seems to reoccur every time I restart VS. This is<em> incredibly</em> annoying to have to re-import my custom colors every time I restart VS.</p>

John Schultz [MSFT] on 1/25/2019, 10:22 AM (17 days ago): <p>Further update:</p><p>It seems to be related to the Preview Feature "Use enhanced colors for C# and Basic". Once I turned this off, my custom color theme remained consistently applied between restarts/upgrades.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
addessed via #33302
