### ISSUE TITLE
Local function hides functions declared in class

### ISSUE THREAD

**Issue by aka-STInG** [dotnet/roslyn#33316]
**Version Used**: 

C# 7.3 (Visual Studio 2017 15.9.6

**Steps to Reproduce**:

    public class Mutator
    {
        public int Mutate(int a, int b)
        {
            bool IsSum(int x)
            {
                return true;
            }

            if (IsSum(a, b))
            {
                return a + b;
            }
            else
            {
                return a - b;
            }
        }

        public bool IsSum(int a, int b)
        {
            return false;
        }
    }

**Expected Behavior**:

Compilation without errors

**Actual Behavior**:

error CS1501: No overload for method 'IsSum' takes 2 arguments

**Comment by aka-STInG** [comment]
Had to edit several times without luck. Sorry about code formatting.

**Comment by gafter** [comment]
This is by design.  The method group contains only one method, which is found in scope.

Moving to `csharplang` repo for any further discussion.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #2218](https://github.com/dotnet/csharplang/issues/2218) via [**ZenHub**](https://www.zenhub.com/)
