### ISSUE TITLE
Suppressions for CA1811:AvoidUncalledPrivateCode should be respected by IDE0051

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#33314]
CPS code base has a bunch of "unused" things that look like this:

```
        /// <summary>
        /// Wires up this service to event notifications that it needs to respond to.
        /// </summary>
        [ConfiguredProjectAutoLoad]
        [AppliesTo(ProjectCapabilities.Cps + " & " + ProjectCapabilities.ProjectReferences)]
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Called by MEF")]
        private void WireUp()
        {
            this.ShellServices.ProjectRenamedInSolution += this.ShellServices_ProjectRenamedInSolution;
            this.ShellServices.ProjectRemovedFromSolution += this.ShellServices_ProjectRemovedFromSolution;
        }
```

For these we get IDE0051:

```
Severity	Code	Description	Project	File	Line	Category	Suppression State
Message	IDE0051	Private member 'ProjectReferenceMaintenanceService.WireUp' is unused.	Microsoft.VisualStudio.ProjectSystem.VS.Implementation	E:\CPS\src\Microsoft.VisualStudio.ProjectSystem.VS.Implementation\ProjectReferenceMaintenanceService.cs	106	Code Quality	Active
```

IDE0051 is exactly the same rule as CA1811, except that it has been removed to the Roslyn tree and renamed. In FxCop days, when we merged rules, we had a mapping table so that existing suppressions would be respected by the new rule. Roslyn should have the same thing.

CPS code base has over 200 instances of this.

**Comment by mavasani** [comment]
Few things to note:
1. IDE0051 reports all unused private members, I believe CA1811 is only for unused methods.
2. CA1811 implementation, or in fact any other CAxxxx rule port has strict compat requirements and so needs to follow the old heuristics. IDE0051 does not have such compat requirements.
3. This is a classical case for https://github.com/dotnet/roslyn/issues/20242, which would be solved by exposing a DiagnosticSuppressor or DiagnosticFilter API (https://github.com/dotnet/roslyn/pull/31603) - FxCop analyzers package would basically include a filter that suppresses all IDE0051 instances.

**Comment by mavasani** [comment]
Tagging @tmat and @jinujoseph

**Comment by davkean** [comment]
AvoidUncalledPrivateCode would fire on accessors and would respect suppressions against the property, like so:

``` C#
        /// <summary>
        /// Gets or sets the configured project.
        /// </summary>
        [Import]
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "MEF")]
        private ConfiguredProject ConfiguredProject { get; set; }
```

**Comment by sharwell** [comment]
One of the primary motivations for changing the diagnostic ID is to decouple ongoing analyzer work from the back-compat expectations of FXCop Analyzers. In addition to the implementation complexity, linking the diagnostic IDs for the purpose of suppressions undermines this goal, so this is a **Won't Fix** item. We are still interested in resolving bugs related to the analysis and reporting of diagnostics, and those can be filed as separate issues.

Should the suppression analyzer proposal move forward, it would be possible for an independent extension to perform the requested analysis and suppressions.
