### ISSUE TITLE
Implement caching for parsed editorconfig values in the code style layer

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#33328]
Identified by @heejaechang in https://github.com/dotnet/roslyn/pull/33291#discussion_r255694197.

Currently `TryGetEditorConfigOption` does not cache results for specific options, which can lead to reparsing of the raw string every time an option is requested.
https://github.com/dotnet/roslyn/blob/a557079b3b5562c16c1feb3bebd0391926a01c6e/src/CodeStyle/Core/Analyzers/Options/AnalyzerConfigOptionsExtensions.cs#L30

📝 This code is intended as an interim solution until the new editorconfig-in-compiler APIs replace it.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need this, we should just do it.
