### ISSUE TITLE
How to interpret entries in roslynRemoteHost.log file

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#33322]
We write a C# and VB.NET Roslyn Analyzer.

We have received some user questions about what is the content of this file and whether this was useful to report it back to us.

I have failed to find some useful information about this file and about its entries, so I am wondering whether you could help me have a clear understanding.

When is this file generated? What is the content (is it linked to performance?)?

Our ticket: https://github.com/SonarSource/sonar-dotnet/issues/2248

**Comment by jmarolf** [comment]
@Evangelink 	These logs are coming from the [PerformanceTrackerService](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Remote/Core/Diagnostics/PerformanceTrackerService.cs). It is simply reporting that these are the most expensive analyzers that were run in the compilation

**Comment by jinujoseph** [comment]
cc @heejaechang

**Comment by Evangelink** [comment]
Thank you @jmarolf!

I guess that the message is displayed as `Error :` because you consider the analyzers were too slow (the list is called `badAnalyzers`)?!

Anyway, we are aware of some perf issues with some of our analyzers but we are having some trouble to do a correct benchmark/profiling so that we can track the evolution over time.
