### ISSUE TITLE
Nullable warnings reported for lifted operators when operands are not null

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#33330]
```C#
#nullable enable

class Program
{
    static void F(int? i)
    {
        if (i.HasValue)
        {
            _ = (int)(i & 0xff); // warning: may be null
            _ = (int)(~i);       // warning: may be null
        }
    }
}
```
Reported by @onovotny.

When resolving this issue, please also track down any references to  https://github.com/dotnet/roslyn/issues/31500 (which was resolved as dupe of present issue).

**Comment by jcouv** [comment]
Are there other code patterns where the compiler adds an implicit `.HasValue` and that we should also verify? Perhaps in disposal, or tuple comparison?

**Comment by gafter** [comment]
This will be fixed in https://github.com/dotnet/roslyn/pull/33648
