### ISSUE TITLE
Allow type inference for class members

### ISSUE THREAD

**Issue by edward-a** [dotnet/roslyn#33331]
I understand that using type inference for class members is a topic already raised in the past but here I want to show how the absence of it is highly detrimental to performance in some cases. In our code we have big auto-generated chunks with lots of lambdas passed as arguments. After removing all bottlenecks related to heap allocation, we are still stuck with delegates for lambdas heap-allocated upon instantiation of an object which significantly slows down the instantiation. We’d like to use class methods instead of lambdas called through static class methods to avoid the delegate allocations but in that case we would lose type inference which is no go for us. Please check the code below that presents the issue and the proposed solution.
`
        class Class1
        {
            bool b;

            static double F(Class1 c) { return c.f(); }
            static Func<Class1, double> _F = F;
            double f() { return this.b ? 10.0 : 20.0; }

            public Class1()
            {
                Class2.Create(this, () => this.b ? 10.0 : 20.0); // Type inference but heap allocation (assume hundreds of this)

                Class2.Create(this, _F); // No heap allocation but can't use type inference for class members

                // Proposal:
                // static var F(Class1 c) { return c.f(); }
                // static var _F = F;
                // var f() { return this.b ? 10.0 : 20.0; }
            }
        }

        class Class2
        {
            public static Class3<T> Create<T>(Class1 c, Func<T> f)
            {
                return new Class3<T>(c, f);
            }

            public static Class3<T> Create<T>(Class1 c, Func<Class1, T> f)
            {
                return new Class3<T>(c, f);
            }

            public class Class3<T>
            {
                public Class3(Class1 c, Func<T> f) { }
                public Class3(Class1 c, Func<Class1, T> f) { }
            }
        }`

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #2227](https://github.com/dotnet/csharplang/issues/2227) via [**ZenHub**](https://www.zenhub.com/)
