### ISSUE TITLE
Code fix for "use pattern matching" should be removing blanks lines it introduces

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#33345]
Unlike other code fixes, "use pattern matching" doesn't remove blank lines when it removes an assignment:

``` C#
                        var receivingData = this.receiveBuffer[i] as IProjectVersionedValue<IProjectSubscriptionUpdate>;

                        // We should prevent processing the same delta again.
                        if (receivingData != null && receivingData.DataSourceVersions == resultUpdate.DataSourceVersions && receivingData.Value.CurrentState == resultUpdate.Value.CurrentState)
                        {
                            this.receiveBuffer[i] = this.processingBuffer[i];
                        }
```

Expected:

``` C# 
                 lock (this.SyncObject)
                 {
                        // We should prevent processing the same delta again.
                        if (this.receiveBuffer[i] is IProjectVersionedValue<IProjectSubscriptionUpdate> receivingData && receivingData.DataSourceVersions == resultUpdate.DataSourceVersions && receivingData.Value.CurrentState == resultUpdate.Value.CurrentState)
                        {
                            this.receiveBuffer[i] = this.processingBuffer[i];
                        }
                 }
```

Actual:

``` C#
                    lock (this.SyncObject)
                    {

                        // We should prevent processing the same delta again.
                        if (this.receiveBuffer[i] is IProjectVersionedValue<IProjectSubscriptionUpdate> receivingData && receivingData.DataSourceVersions == resultUpdate.DataSourceVersions && receivingData.Value.CurrentState == resultUpdate.Value.CurrentState)
                        {
                            this.receiveBuffer[i] = this.processingBuffer[i];
                        }
                    }
```

Hit in: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/164018?path=%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem%2FCore%2FDataflow%2FSyncLinkToLink.cs&discussionId=1641980&_a=files.

Make sure it handles both the case where code _and_ trivia follows it.

**Comment by CyrusNajmabadi** [comment]
Note: this feature is just using the SyntaxEditor to do the removal of this statement.  So we likely want to update the editor to be smarter here and to remove these sorts of extraneous blank lines in these sorts of of very specific cases.

**Comment by davkean** [comment]
Why is it that some code fixes do the right thing here, and others don't?

**Comment by davkean** [comment]
Ah, because these are new patterns that we've not encountered before?

**Comment by CyrusNajmabadi** [comment]
Because not all of them go through the same codepaths.  It's something i've pushed for over hte years, but there is little appetite to make those sorts of larger changes vs smaller targetted fixes for features.

**Comment by emilefokkema** [comment]
@CyrusNajmabadi I would like to have a crack at this. Maybe reduce the number of code paths a little as well.

**Comment by CyrusNajmabadi** [comment]
@emilefokkema Go for it!

**Comment by jinujoseph** [comment]
fixed via https://github.com/dotnet/roslyn/pull/33643
