### ISSUE TITLE
NullableWalker fails to update type for a default expression

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#33344]
In the following code in `NullableWalker`, the result tuple type is not updated to reflect that some of its element types may contain null.

``` c#
        public override BoundNode VisitDefaultExpression(BoundDefaultExpression node)
        {
            Debug.Assert(!this.IsConditionalState);

            var result = base.VisitDefaultExpression(node);
            TypeSymbol type = node.Type;
            if (EmptyStructTypeCache.IsTrackableStructType(type))
            {
                int slot = GetOrCreateObjectCreationPlaceholderSlot(node);
                if (slot > 0)
                {
                    this.State[slot] = NullableFlowState.NotNull;
                    InheritNullableStateOfTrackableStruct(type, slot, valueSlot: -1, isDefaultValue: true, isByRefTarget: false, slotWatermark: GetSlotWatermark());
                }
            }

            // PROTOTYPE(ngafter): this fails to produce an updated tuple type for a default expression
            // (with nullable element types where those element types were capable of containing null)
            _resultType = TypeWithState.ForType(type);
            return result;
        }
```

**Comment by jcouv** [comment]
We may have the same problem with anonymous types.
FYI @cston

**Comment by gafter** [comment]
@jcouv A default value of an anonymous type is just `null`.

**Comment by jcouv** [comment]
Some notes from discussion with @cston.

Relates to https://github.com/dotnet/roslyn/issues/33035 (should we treat tuples like a generic `Pair<T1, T2>` or element-wise?)

Currently, we treat tuples like `Pair`, except that we know to initialize the state of its fields. So `default((object, int))` has an `(object, int)` result type, just like `default(Pair<object, int>)` has a `Pair<object, int>` result type.
This is on LDM backlog for nullable feature.

**Comment by gafter** [comment]
@jcouv Every struct should get default (nullable when apropos) values for its elements from the default (undeclared) constructor. There is nothing special about tuples in this regard.

**Comment by jcouv** [comment]
Sorry, I thought the issue was with setting an incorrect `_resultType`. 

For setting the right state for the fields, I think the existing block (copied below) already does that.
It may be good to illustrate the problem with a scenario.

```C#
            if (EmptyStructTypeCache.IsTrackableStructType(type))
            {
                int slot = GetOrCreateObjectCreationPlaceholderSlot(node);
                if (slot > 0)
                {
                    this.State[slot] = NullableFlowState.NotNull;
                    InheritNullableStateOfTrackableStruct(type, slot, valueSlot: -1, isDefaultValue: true, isByRefTarget: false, slotWatermark: GetSlotWatermark());
                }
            }
```

**Comment by RikkiGibson** [comment]
@jcouv @gafter What scenarios will cause problems to arise from this?

The below program warns on the `tuple.Item1` access, but not on the `default((object, int))` expression. Is that what we want?

```cs
#nullable enable
public class C {
    public void M() {
        var tuple = default((object, int));
        tuple.Item1.ToString(); // warn
    }
}
```

**Comment by jcouv** [comment]
@RikkiGibson Here's a scenario I think may be interesting:
```C#
(object?, string?) tuple = default;  /*T:(object?, string?)*/  // VerifyTypes
tuple.Item1.ToString();
```
The `default` literal

**Comment by RikkiGibson** [comment]
@jcouv I found that scenario passes VerifyTypes locally, but I could still be missing something about what the real problem is here.

**Comment by jcouv** [comment]
Good. Let's add the test and I think we can close the issue. 
Neal will comment if he thinks something else wasn't addressed.
