### ISSUE TITLE
Formatter doesn't work with empty workspace

### ISSUE THREAD

**Issue by Jake456** [dotnet/roslyn#3336]
The following doesn't format the code. Tried also with AdHocWrkspace to no avail.

            var tree = CSharpSyntaxTree.ParseText(code);
            var ws = MSBuildWorkspace.Create();
            var root = Formatter.Format(tree.GetRoot(), ws);
            code = root.ToString();

Tried with latest version (6df49c669c3364326830d6156f4ef95221b60c24).

**Comment by mattwar** [comment]
I believe that overload is only working on ranges identifies by formatter annotations that you don't have any of.  Try the overload that takes a span and give it the tree's full span.

**Comment by mattwar** [comment]
Can you give an example of source text this is not formatting?

**Comment by Jake456** [comment]
namespace N1
                {      
                    
                enum E { A, b, C }

                public class C1
                {
                public   object P1 {get;set;}
                }

                }

The indentations/spaces aren't corrected.

**Comment by mattwar** [comment]
I tried this and it succeeds:

``` C#
        [Fact]
        public void FormatNode()
        {
            var code = @"
            namespace N1
            {      

            enum E { A, b, C }

            public class C1
            {
            public   object P1 {get;set;}
            }

            }
";

            var expected = @"
namespace N1
{

    enum E { A, b, C }

    public class C1
    {
        public object P1 { get; set; }
    }

}
";

            var root = SyntaxFactory.ParseCompilationUnit(code);
            var ws = new AdhocWorkspace();
            var formattedRoot = Formatter.Format(root, ws);
            var formattedText = formattedRoot.ToFullString();
            Assert.Equal(expected, formattedText);
        }
```

**Comment by Jake456** [comment]
Weird, I tried your snippet, and I get `NotSupportedException`:

    Additional information: The language 'C#' is not supported.

at `HostWorkspaceServices.GetLanguageServices()`.

Perhaps you have some uncommitted modifications which address this?

**Comment by Pilchie** [comment]
You need to make sure that `Microsoft.CodeAnalysis.Workspaces.CSharp.dll` is deployed beside `Microsoft.CodeAnalysis.Workspaces.dll` so that it can find C# support.

**Comment by Jake456** [comment]
Adding the dll solved the issue, thanks.
