### ISSUE TITLE
Monodevelop doesn't works with roslyn when Visual Studio 2019 preview installed before

### ISSUE THREAD

**Issue by lopatnov** [dotnet/roslyn#33361]
**Version Used**: 
Microsoft Visual Studio\2019\Preview\MSBuild\15.0\Bin\Roslyn

**Steps to Reproduce**:

1. Install Visual Studio 2019 Preview
2. Compile MonoDevelop as described in guide https://www.monodevelop.com/developers/building-monodevelop/
3. Create any c# project, compile and see an error:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(5,5): Error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the declaration is correct, and that the file exists on disk. (MSB4019) (MyGtkSample)

**Expected Behavior**:
The MonoDevelop should work with Visual Studio 2019 preview.

**Actual Behavior**:
I see an error
I created issue there:
https://github.com/mono/monodevelop/issues/7122
@Therzok says that it's roslyn issue
![52564508-14cde080-2e0d-11e9-8c92-bc39b5a37b02 1](https://user-images.githubusercontent.com/11029246/52741865-15b66c00-2fdf-11e9-824c-dcf8715c0cb2.png)

**Comment by Therzok** [comment]
Already fixed here https://github.com/dotnet/roslyn/pull/33114
