### ISSUE TITLE
AbstractCommandHandlerTestState.WaitForAsynchronousOperationsAsync does not wait for async completion operations to complete

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#33379]
Need to change WaitForAsynchronousOperationsAsync for async completion purposes to wait for completion: it is available either by waiting for session.GetComputedItems (for a specific text view) or by subscribing for events  IAsyncCompletionBroker.CompletionTriggered and then for session.ItemsUpdated.

**Comment by CyrusNajmabadi** [comment]
Just to be clear: `WaitForAsynchronousOperationsAsync` should not have any awareness of completion.  Rather, completion should plug into the async test tracking system by having those respective ops indicate that async work is pending or not.

**Comment by jasonmalinowski** [comment]
@AmadeusW Is that something you already did internal to the editor? Right now if I recall the editor has a copy/paste version of our async tracking work; it might just we have to unify on yours and this all starts working again?

**Comment by AmadeusW** [comment]
We don't support `AbstractCommandHandlerTestState`. I would need to re-implement it within Editor assembly, make it a public API and allow Roslyn to consume it. Currently Ivan is subscribing to events within Completion API to be notified when operation has completed.
