### ISSUE TITLE
errorlog JSON output should escape backslashes

### ISSUE THREAD

**Issue by mpaladin** [dotnet/roslyn#3337]
JSON format requires backslashes to be escaped, I noticed that errorlog JSON output contains unescaped backslashes, i.e. issue location uris containing Windows absolute paths.

**Comment by dbolkensteyn** [comment]
see https://github.com/dotnet/roslyn/blob/f4a6ccd27889960179b14193b5f999c228ee631a/src/Compilers/Core/Desktop/CommandLine/ErrorLogger.cs#L275
