### ISSUE TITLE
VS becomes busy on switch expression

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#33378]
**Version Used**: 

Visual Studio 16.0.0 Preview 3.0
LangVersion 8.0

**Steps to Reproduce**:

```cs
static int M(object x) => x switch
{
    int _ => 0,
};
```

**Expected Behavior**:

No error.

**Actual Behavior**:

The code completion gets wrong and Visual Studio becomes busy.

![image](https://user-images.githubusercontent.com/3760955/52756281-2d740b80-3044-11e9-8d96-110e3f00af66.png)

**Comment by gafter** [comment]
Likely a dup of the bug fixed in https://github.com/dotnet/roslyn/pull/32755

**Comment by ufcpp** [comment]
close as dup
