### ISSUE TITLE
Operator '>' cannot be applied to operand 'default'

### ISSUE THREAD

**Issue by IanKemp** [dotnet/roslyn#33384]
**Version Used**:

VS2019 Preview 3.0
C# language version 7.3

**Steps to Reproduce**:

```csharp
    long foo;

    if (foo > default) // CS8310
    {

    }
```

**Expected Behavior**:

This compiles, as `default` is syntactic sugar for `default(T)` (in this case, `default(long)`).

**Actual Behavior**:

It doesn't compile.

**Comment by gafter** [comment]
This is by design.  See https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-05-31.md#default-in-operators

**Comment by IanKemp** [comment]
@gafter Both `==` and `>` are binary operators and can be overridden. yet `== default` works while `> default` does not. And none of the examples given in that LDM doc make sense, since `var` and `default` don't and can't mix.

I'm probably just being slow, but could you maybe point me to an issue discussing this more thoroughly, and/or provide an example demonstrating the issue?
