### ISSUE TITLE
protected internal virtual Intellisense shows nothing in derrived class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33383]
In the derrived class intellisense doesent show Autocompletion.

*Sample:*
Assembly 1

```csharp
    public class Class2
    {
        public Class2()
        {
            Value = "set in constructor";
        }

        protected internal virtual string Value { get; }

        protected virtual string Value2 { get; } = "bla";
    }
```

*Asssembly2*
```csharp
public class ExtClass2 : Class2
    {
        public ExtClass2()
        {
            
        }

        protected override string // Here should show up Value from baseclass when i hit CTRL+Space

        protected override string Value2 => base.Value2;
    }
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/448161/protected-internal-virtual-intellisense-shows-noth.html
VSTS ticketId: 788425_
_These are the original issue comments:_

Visual Studio Feedback System on 2/14/2019, 04:00 AM (3 hours ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Doesn't repro for me.  I get:

![image](https://user-images.githubusercontent.com/4564579/218141311-5901d62e-c86b-4556-9e77-19cc2b482503.png)
