### ISSUE TITLE
Implement Try Method 

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#334]
It is a fairly common pattern to see `CanGetChar` closely followed by a call to the following methods.
```
PeekChar
GetChar
PeekAheadChar
```
So I think it could be beneficial to have a Try variant of those methods.
```
TryPeekChar
TryGetChar
TryPeekChar
```

It also allow us to the "cache" the character, thus not paying the penalty of multiple call to `PeekAheadChar`

**Comment by theoy** [comment]
On @AlekseyTs to review for submission :smile:

**Comment by AdamSpeight2008** [comment]
if VB.net will support out declarations, them some of those dims can be removed.

**Comment by AdamSpeight2008** [comment]
I've submitted an updated Pull Request (#358) which include affects of the prior comments.

**Comment by AnthonyDGreen** [comment]
@AdamSpeight2008, we did discuss Out declarations for VB 14. It was a much bigger feature than we had time for. It's still on the list for VB 15.

**Comment by gafter** [comment]
Closing this, as the associated pull request is no longer open.
