### ISSUE TITLE
Switch expressions can't be used with delegates/method groups (no best type found)

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#33415]
**Version Used**: VS 16.0 Preview 3

**Steps to Reproduce**:

```c#
class SwitchWithMethod
{
    void M1(int _) { }
    void M2(int _) { }

    enum Method
    {
        One,
        Two
    }

    void M_New(Method m, int a)
    {
        Action<int> action = m switch
        {
            Method.One => M1,
            Method.Two => M2,
            _ => throw null
        };
        action.Invoke(a);
    }

    void M_Old(Method m, int a)
    {
        Action<int> action;
        switch (m)
        {
            case Method.One:
                action = M1;
                break;
            case Method.Two:
                action = M2;
                break;
            default:
                throw null;
        }
        action.Invoke(a);
    }
}
```

**Expected Behavior**: `M_New` and `M_Old` can compile without error.

**Actual Behavior**: Only `M_Old` compiles. `M_New` reports error CS8506 ("No best type was found for the switch expression"), despite all of the non-throwing branches having an identical return type (`delegate void (int)`).

This sort of pattern is useful for dynamic dispatching, e.g. for loggers (switching on the error level and calling one of the logger's methods, all of which have the same signature).

**Comment by gafter** [comment]
This is be design, and just like the `? :` expression.  Just cast one of the cases to the desired delegate type.
