### ISSUE TITLE
Nullability of conditional access with unconstrained type parameters

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#33430]
What is the nullability of `x?.F()`?

```cs
class C<T, U>
    where T : U
    where U : C<T, U>?
{
    static void M(U x)
    {
        U y = x?.F();
        T z = x?.F();
    }
    T F() => throw null;
}
```

#### Resolved 2/13/2019:
The nullability of a conditional invocation is always nullable.

**Comment by gafter** [comment]
Fixed and tested in https://github.com/dotnet/roslyn/pull/33648
