### ISSUE TITLE
Pipename not being quoted when starting VBCSCompiler

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#33452]
The pipename argument is not being properly quoted when starting the VBCSCompiler process from our MSBuild task. That means if there is a space in the name the client and server will have a mismatch and won't be able to communicate. All compilations will fall back to csc / vbc.

Notes: 

- Regression Introduced Here: https://github.com/dotnet/roslyn/pull/32257/files#diff-e9e79a4f1f187c6ba6f94517e04e6c32L385
- Internal Tracking Item: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/795899

**Comment by herebebeasties** [comment]
Looks like this was fixed with #33475.
