### ISSUE TITLE
C# formatter missing linebreak after curly braces of for block

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33458]
When using an for block inside an if condition without curly braces, the else gets put in the same line as the closing brace of the for block.

example:

```csharp
if (true)
    for (int i = 0; i <2; i++) {
       i++;
    } else
     b =5;
```

instead of the expected:

```csharp
if (true)
    for (int i = 0; i <2; i++) {
       i++;
    } 
else
     b =5;
```

correct placement:

```csharp
if(true){
   b=2;
} else
   b=3;
```

and:

```csharp
if(true)
   b=2;
else
   b=4;
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/431619/c-formatter-missing-linebreak-after-curly-braces-o.html
VSTS ticketId: 774047_
_These are the original issue comments:_

roland.fredenhagen on 1/20/2019, 06:42 AM (27 days ago): The Title misses "else" sorry for that, but it seams like I am not able to edit anything.
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
🔗 This was also requested as a line item in #31140

**Comment by sharwell** [comment]
During design review, we realized this was just a small bug. The user configured the formatter to not place a newline before `else`, but the formatter fails to account for the fact that a brace preceding the `else` keyword might not belong to the `if` statement. The newline should only be omitted if the `}` and `else` tokens belong to the same `if` statement.
