### ISSUE TITLE
System.InvalidCastException on pattern matching with when condition

### ISSUE THREAD

**Issue by OnurGumus** [dotnet/roslyn#33451]
**Version Used**: 
7.3 and 8.0
**Steps to Reproduce**:
Run the below code:
```
object s = "a";
switch (s)
{
    case IEnumerable<int> subList when subList.Any():
        break;
    case IEnumerable<object> subList2:
        break;
    case null:
        break;
}

```

**Expected Behavior**:
It should work without matching
**Actual Behavior**:
Fails with below exception:
```
System.InvalidCastException: 'Unable to cast object of type 'System.String' to type 'System.Collections.Generic.IEnumerable`1[System.Object]'.'
```
**Fun fact**: this is the simplest possible case I can reproduce the error. Removing anything from above code fixes the problem

**Comment by gafter** [comment]
Dup of https://github.com/dotnet/roslyn/issues/32774 and already fixed for the next preview.
