### ISSUE TITLE
Shared intellisense shouldn't show warning for field/props that are common to all heads

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3346]
Look at this picture:
![shared-intellisense](https://cloud.githubusercontent.com/assets/3316258/8015461/78e5b508-0b8d-11e5-9d1f-1b1bdfed0f50.png)

What I expect: there shouldn't be a warning icon for "y", since it's present and valid in both heads

What I get: there is (presumably because one is a field and the other is a property).

In general, the rule is "if a given piece of syntax would be valid in both projects, then don't show a warning icon in intellisense". In this case the syntax `c.y` is valid in both projects.

**Comment by Pilchie** [comment]
Your suspected reason seems right to me - we verify that the symbol kind is at least the same to determine if the warning should show or not.

**Comment by rchande** [comment]
Please verify, @ljw1004.
