### ISSUE TITLE
Generic extension does not have lambda intellisense.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33469]
Then I do something like

```csharp
string[] weekDays = { "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" };
weekDays.ForEach(wd => Console.WriteLine(wd));
```

On that first typing of `wd`, intelliesense gets confused and autocompletes with something it thinks is close but does not act like a normal lamda for a built in linq query. Super annoying.

Example extension

```csharp
        public static void ForEach<T>(this IEnumerable<T> collection, Action<T> action)
        {
            if (collection != null)
            {
                foreach (T item in collection)
                {
                    action(item);
                }
            }
        }
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/442247/generic-extension-does-not-have-lambda-intellisens.html
VSTS ticketId: 782643_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
@dotnet/roslyn-ide One possibility here would be using the builder mode for completion of an argument when the method does not resolve to any overload with that name.

**Comment by sharwell** [comment]
In design review we agreed with the above proposal.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  The IDE is appropriately in 'suggestion mode' here:

![image](https://user-images.githubusercontent.com/4564579/216180388-14e6216f-6c72-486f-a991-e9fe2aae0d88.png)
