### ISSUE TITLE
Using-declaration should not trigger RemoveUnusedValues

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#33464]
I suspect this is a compiler issue, as the `AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer` relies on the control flow graph to determine how variables are used.

![image](https://user-images.githubusercontent.com/12466233/52920672-28bd8a80-32c4-11e9-8f0e-82b51439ca2e.png)

![image](https://user-images.githubusercontent.com/12466233/52920667-180d1480-32c4-11e9-99d5-cc59d339e5ec.png)

FYI @mavasani

**Comment by mavasani** [comment]
Thanks @jcouv. This seems to be same as https://github.com/dotnet/csharplang/issues/2235#issuecomment-464308801. Current IOperation tree and ControlFlowGraph have no special operation node for using declaration, it is just an Operation.None node wrapping the variable declaration. This leads to all CFG and IOperation clients that attempt to analyze reads and writes to see a variable declaration, whose underlying declared local is never referenced. I believe this issue will get fixed once we implement IOperation and CFG support for this feature.

**Comment by chsienki** [comment]
We have an open issue on this https://github.com/dotnet/roslyn/issues/32100 which should fix once implemented.

**Comment by jcouv** [comment]
Closed as dupe of https://github.com/dotnet/roslyn/issues/32100. Copied scenario details over there
