### ISSUE TITLE
Roslyn changed how Analyzer assemblies are loaded.  TypeScript analyzers no longer loading.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#3347]
PR https://github.com/dotnet/roslyn/pull/2882 switched the code for loading Analyzer assemblies from:

```c#
                    var type = analyzerAssembly.GetType(typeName);
                    if (DerivesFromDiagnosticAnalyzer(type))
                    {
                        analyzer = (DiagnosticAnalyzer)Activator.CreateInstance(type);
                    }
```

To:

```c#
                    type = Type.GetType(typeName + ", " + analyzerAssembly.FullName, throwOnError: true);
```

However, this now fails to load the TypeScript as we are not in any binding path.  This is high pri as all TypeScript diagnostic scenarios (squiggles/error-list) are broken.

**Comment by CyrusNajmabadi** [comment]
Adding @tmat and @tmeschter

**Comment by CyrusNajmabadi** [comment]
Adding @mavasani as well.

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/commit/0740cbfe97adc64989c823e6d64aac211512407f

**Comment by tmat** [comment]
@CyrusNajmabadi Please verify as soon as you get the new drop.

**Comment by CyrusNajmabadi** [comment]
@tmat Will do.
