### ISSUE TITLE
Let VS .NET and VS Code users Vote!

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/roslyn#33477]
Let VS .NET and VS Code users Vote!
Since MS now owns github, I think it will be better to urge .NET developers to vote on features proposed in .NET repos. So,, I suggest VS.NET frequently shows a startup window asking the developer:
> Do you agree with `<<Subject>>`? Join the discussion here `<<Link>>`. 

The window can also view a brief of the topic and a Yes\No links that are mapped to Like/dislike response on the topic.

You can have the user an option to stop viewing this window at startup, with an alternative command on the help or tools menu to show a report on topmost proposals. User also can choose the repos that interests him most to show their topics on the window/report. VS can make some assumptions about that from the types of projects he usually opens. Issues and proposals can be filtered based on numbers of reactions and comments, the milestone labels or any other suitable factor. Team members can also mark some issues to be viewed in VS.
If this happens, it can grantee participation of ten thousands , or even millions of developers in the dissuasion. This will give a more realistic votes about each new feature and encourage developers to participate in writing the code of these features.

**Comment by CyrusNajmabadi** [comment]
> I suggest VS.NET frequently shows a startup window asking the developer:

dotnet/roslyn does not seem like the right repo for this suggestion. Can you file a suggestion for VS using:

![image](https://user-images.githubusercontent.com/4564579/52979447-81eff180-338a-11e9-9e77-d56e4956553c.png)

For VSCode, you can file an issue over here: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+sort%3Areactions-%2B1-desc

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
OK, but I think this concerns all dotnet repos nad gitbub team. For example: Are admins iof these repos able to handle a huge no. of commentes and issues if such suggestion is accepted?

**Comment by CyrusNajmabadi** [comment]
> OK, but I think this concerns all dotnet repos nad gitbub team.

The VS and VSCode teams can make that determination.  Roslyn doesn't seem to have any relation to the suggestion you want to make.

**Comment by MohammadHamdyGhanem** [comment]
https://developercommunity.visualstudio.com/idea/461627/let-vs-net-and-vs-code-users-vote-on-net-proposals.html

**Comment by CyrusNajmabadi** [comment]
Great.  Can you close out this issue please?

**Comment by sharwell** [comment]
> Are admins iof these repos able to handle a huge no. of commentes and issues if such suggestion is accepted?

We would certainly try 😁

To date, even when things are overwhelming the people working on these projects prefer more people participating.
