### ISSUE TITLE
Intellisense completion fails for 'else' after 'else if'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33470]
```csharp
if (condition)
  DoSomething();
// At this point, Intellisense correctly suggests 'else' as a completion
else if (condition2)
  DoSomethingElse();
// At this point, Intellisense no longer recognizes 'else' as a valid keyword and suggests some ridiculous completions instead
else
  ...
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/431613/intellisense-completion-fails-for-else-after-else.html
VSTS ticketId: 774044_
_These are the original issue comments:_

Cytheria Ji [MSFT] on 1/21/2019, 04:52 PM (27 days ago): <p>Thank you for your feedback! For us to investigate this further, could you please provide your project language? </p><p>We look forward to hearing from you!</p>

Paul Buddington on 1/22/2019, 07:35 AM (26 days ago): <p>C#, build settings for C# 7.3</p><p>I saw this issue with a clean load of Visual Studio Community edition that I installed on a loaner laptop.  I am unable to reproduce the same behavior on my existing Visual Studio Professional 2017 (v15.9.5) installation on my regular laptop, but I have already done a lot to tweak the Intellisense settings on that machine to compensate for all the times Visual Studio thinks it's smarter than I am (e.g. built-in snippets that can't be modified).</p>

_These are the original issue solutions:_
(no solutions)

**Comment by ivanbasov** [comment]
Could not reproduce the issue with VS 2019.1 Preview 2
![else](https://user-images.githubusercontent.com/5455484/56398504-c1f21a00-61fd-11e9-8899-58e13cd85197.gif)
