### ISSUE TITLE
Differences detected in solution checksum

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#33476]
**Version Used**: fec31a956848c23417baf5b02f6a83c4095a3a37

**Steps to Reproduce**:

1. Run `WorkspacesNetCore` integration tests in **Debug** configuration

**Expected Behavior**:

Tests pass.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/1408396/52971647-dd67b280-337d-11e9-95ee-f241982ba87e.png)

**Comment by CyrusNajmabadi** [comment]
I also hit this.

**Comment by CyrusNajmabadi** [comment]
Tagging @heejaechang

**Comment by heejaechang** [comment]
I guess there was new project info added that didn't correctly serialized between VS and OOP

**Comment by CyrusNajmabadi** [comment]
@heejaechang is there some sort of test we can add to catch this?

**Comment by heejaechang** [comment]
I have tests that supposed to catch it but I guess it had a case where it missed. need to take a look.
