### ISSUE TITLE
make solution crawler to run all pending work from previous solution before processing work from new solution

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#33504]
existing solution crawler is designed not to have ordering between pending tasks of different documents/projects. it only guarantees states preserved within the same document/project.

for example, document changed events can fire for document A and document B, but document B has a focus, then event for document B will processed before document A even though events are fired in opposite order.

but if document A is changed and then removed, the ordering of document change and document removed event will be either preserved or aggregated.

this also means, if solution "A" is closed and new solution "B" is opened and then someone opens a document "C" from new solution B and type, then document "C" will get higher priority over "remove document" events from old solution "A".

we are having some feedback such as this (https://github.com/dotnet/testimpact/pull/2727) or stale errors in error list after solution close, so we are going to change solution crawler to process all pending works from the previous solution before processing events from new solution making clear "clean up" boundary between solutions open/close or configuration changes.

* we might or might not still give special handling for active file (file with focus)

**Comment by CyrusNajmabadi** [comment]
Sounds like a good idea!  Hopefully the only events needed to process will be 'remove' events, and those shoudl be fast, right?

**Comment by shyamnamboodiripad** [comment]
@CyrusNajmabadi I believe that is correct. Currently, without this fix, our analyzer relies on assumption that the only notifications that we can receive for old solution after being told about a new solution are 'remove' events for documents and projects from the old solution.

**Comment by CyrusNajmabadi** [comment]
closing out. solution crawler is being removed.
