### ISSUE TITLE
[Regression] Fix alls have started running in generated code

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#33507]
This was fixed during the Dev15 cycle, but seems to have been regressed again. 

1.
```
> git clone http://github.com/dotnet/project-system
> cd project-system
project-system> git checkout 9bac1e669c67e5d0c44486be595d7ec6323461ca
project-system> build.cmd
project-system> ProjectSystem.sln
```
2. Navigate to `ActiveEditorContextTracker.cs`
3. Drop the code fix over `using System.Threading.Tasks` to **Remove unnecessary usings** -> **Solution**

**Expected:**  (15.9)
Two results:
![image](https://user-images.githubusercontent.com/1103906/53065694-ef358b00-3520-11e9-82cf-6ece412403fc.png)

**Actual:** (16.0 Preview 4)
100s of results in auto-generated files:
![image](https://user-images.githubusercontent.com/1103906/53065718-ffe60100-3520-11e9-8901-d09b3d910331.png)

**Comment by sharwell** [comment]
Looks like I broke this in 1b402fb4043864be163804aeaedec8536ac84488. Will fix it tomorrow.
