### ISSUE TITLE
Clean up threading hacks around file watching

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#33506]
There's a few hacks right now in our codebase which need to be removed since they make unit testing difficult:

1. [This hack](https://github.com/dotnet/roslyn/blob/c4bb224f68510e8b0d54a85fbbb068e94e633e6c/src/VisualStudio/Core/Def/Implementation/ProjectSystem/RuleSets/VisualStudioRuleSetManager.RuleSetFile.cs#L170-L171) which defers updating of rule sets when the file is modified. It's now obsolete since we are receiving file change events no longer on the UI thread, and our newer pattern for waiting for files never waits on the UI thread for a background file change mutation operation either. When that's removed, we can remove that async waiter Feature entirely, since it's not otherwise needed.
2. [This hack](https://github.com/dotnet/roslyn/blob/8501a7c0da777222a1e10eb8b67a1516e7f606f8/src/VisualStudio/Core/Def/Implementation/ProjectSystem/FileChangeWatcherProvider.cs#L24) where we're doing a SwitchToMainThreadAsync. That was working around a bug where GetServiceAsync() when called from a background thread might deadlock in the service manager if the UI thread was doing something. That shell bug has been fixed but we haven't cleaned up that hack. This also means we can just implement that code in a straightforward way atop the service provider which will work cleanly in mocks.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we want to clean this up, we should just make an issue assigned to a milestone and do it.  These tracking issues from 5 years ago dont' help us.
