### ISSUE TITLE
258 C# Symbol Unit Tests failing on Linux

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#3350]
258 of the C# Symbol Unit Tests are failing on the Linux CI build (and only the Linux CI build).
### Failing Tests (Microsoft.CodeAnalysis.CSharp.UnitTest.*)
* MSFT.CA.CS.UT.BadSymbolReference.MissingTypeInTypeArgumentsOfImplementedInterface
* MSFT.CA.CS.UT.BadSymbolReference.MissingBaseClass
* MSFT.CA.CS.UT.CompilationAPITests.MissedModuleA
* MSFT.CA.CS.UT.GetSemanticInfoTests.UnambiguousPropertyGroupWithoutBoundParent2
* MSFT.CA.CS.UT.GetSemanticInfoTests.SpeculativelyBindPropertyGroup2
* MSFT.CA.CS.UT.GetSemanticInfoTests.SpeculativelyBindPropertyGroup1
* MSFT.CA.CS.UT.IndexedProperties_BindingTests.IndexedProperties_LINQ
* MSFT.CA.CS.UT.IndexedProperties_BindingTests.IndexedProperties_Set_In_Constructor
* MSFT.CA.CS.UT.IndexedProperties_BindingTests.IndexedProperties_Complete
* MSFT.CA.CS.UT.IndexedProperties_BindingTests.OldGetFormat_IndexedProperties
* MSFT.CA.CS.UT.IndexedProperties_BindingTests.IndexedProperties_Incomplete
* MSFT.CA.CS.UT.SemanticTests.Bug1019366
* MSFT.CA.CS.UT.SemanticModelGetSemanticInfoTests.PropertyGroup
* MSFT.CA.CS.UT.SemanticModelGetSemanticInfoTests.PropertyGroupOverloadsOverridesHides
* MSFT.CA.CS.UT.DocumentationCommentCompilerTests.Pia
* MSFT.CA.CS.UT.DocumentationCommentCompilerTests.UnterminatedElement
* MSFT.CA.CS.UT.MetadataMemberTests.ImportDecimalConstantAttribute
* MSFT.CA.CS.UT.CustomModifierCopyTests.Repro819774
* MSFT.CA.CS.UT.CompilationErrorTests.CS0101ERR_DuplicateNameInNS_13
* MSFT.CA.CS.UT.CompilationErrorTests.CS0438ERR_SameFullNameThisAggThisNs06
* MSFT.CA.CS.UT.CompilationErrorTests.CS0101ERR_DuplicateNameInNS_04
* MSFT.CA.CS.UT.CompilationErrorTests.CS0101ERR_DuplicateNameInNS_08
* MSFT.CA.CS.UT.CompilationErrorTests.CS0101ERR_DuplicateNameInNS_10
* MSFT.CA.CS.UT.CompilationErrorTests.CS0101ERR_DuplicateNameInNS_14
* MSFT.CA.CS.UT.CompilationErrorTests.CS0101ERR_DuplicateNameInNS_09
* MSFT.CA.CS.UT.CompilationErrorTests.CS0438ERR_SameFullNameThisAggThisNs05
* MSFT.CA.CS.UT.CompilationErrorTests.CS0824WRN_ExternCtorNoImplementation03
* MSFT.CA.CS.UT.CompilationErrorTests.CS0101ERR_DuplicateNameInNS_05
* MSFT.CA.CS.UT.CompilationErrorTests.CS0101ERR_DuplicateNameInNS_12
* MSFT.CA.CS.UT.CompilationErrorTests.CS0438ERR_SameFullNameThisAggThisNs03
* MSFT.CA.CS.UT.CompilationErrorTests.CS0101ERR_DuplicateNameInNS_07
* MSFT.CA.CS.UT.CompilationErrorTests.CS0101ERR_DuplicateNameInNS_11
* MSFT.CA.CS.UT.CompilationErrorTests.NameCollisionWithAddedModule_03
* MSFT.CA.CS.UT.CompilationErrorTests.CS0101ERR_DuplicateNameInNS_06
* MSFT.CA.CS.UT.CompilationErrorTests.CS0438ERR_SameFullNameThisAggThisNs04
* MSFT.CA.CS.UT.Symbols.AccessorOverriddenOrHiddenMembersTests.OverridingExplicitInterfaceImplementationFromSource
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSemanticsTests.TestAnonymousTypeInsideGroupBy_Queryable
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSemanticsTests.TestAnonymousTypeInsideGroupBy_Enumerable2
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSemanticsTests.AnonymousTypeSymbols_DontCrashIfNameIsQueriedBeforeEmit
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSemanticsTests.TestAnonymousTypeInsideGroupBy_Enumerable
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousTypeSymbol_Empty
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousType_GetHashCode
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousTypeInConstructedMethod_NonEmpty3
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousTypeSymbol_StandardNames2
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousType_PropertyAccess
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousTypeSymbol_Simple_1
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousTypeSymbol_StandardNames
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.Bug11593b
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousType_BaseAccess
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousTypePropertyValueWithWarning
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousTypeSymbol_InQuery
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousTypeInConstructedMethod_NonEmpty
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.Bug991505
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousType_MultiplyEmitDoesNotChangeTheOrdering
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousType_ToString
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousTypeSymbol_Mix
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousType_Equals
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousTypeInConstructedMethod_NonEmpty2
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.Bug11593a
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousTypeSymbol_Simple
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousType_CustModifiersOnPropertyFields
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousType_Simple
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousTypeInConstructedMethod_NonEmpty4
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousTypeInConstructedMethod_Empty
* MSFT.CA.CS.UT.Symbols.AnonymousTypesSymbolTests.AnonymousTypeSymbol_NamesConflictInsideLambda
* MSFT.CA.CS.UT.Symbols.ConversionTests.NullableIntToStructViaDecimal
* MSFT.CA.CS.UT.Symbols.ConversionTests.CheckedConversionsInExpressionTrees
* MSFT.CA.CS.UT.Symbols.ConversionTests.LiftingReturnTypeOfExplicitUserDefinedConversion
* MSFT.CA.CS.UT.Symbols.ConversionTests.MethodGroupConversion_ContravarianceAndDynamic
* MSFT.CA.CS.UT.Symbols.EnumTests.EnumWithPrivateInstanceField
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.CandidateSearchConversion
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.TypedReferenceCannotBeUsedAsTypeArgument
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.Using
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.ReduceExtensionMethodWithNullReceiverType
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.InnerNamespacesBeforeOuter
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.BoxValueTypeReceiverIfNecessary
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.ExtensionMethodIsDisambiguatedByUsingStaticAtDeeperLevel
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.InternalExtensionAttribute
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.ParamsArray
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.ExtensionMethod_ValidateExtensionAttribute
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.ExtensionMethodWithRefParameterFromMetadata
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.DelegatesFromOverloads
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.AssemblyMightContainExtensionMethodsReset
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.IsExtensionMethod
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.ExtensionMethodsDeclaredInEnclosingNamespaceArePreferredOverImported2
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.SystemLinqEnumerable
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.AssemblyMightContainExtensionMethods
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.ExtensionMethodInTheSameClass
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.CandidateSearchByArgType
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.BoxingConversionOfDelegateReceiver02
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.NumericConversionsAreNotAllowed
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.GenericDelegate
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.ReducedExtensionMethodSymbols
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.OverloadResolution
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.Bug602893
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.CannotCreateDelegateToExtensionMethodOnValueType
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.VBExtensionMethod
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.DelegatesAsArguments
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.ExtensionMethodImportedTwiceNoErrors
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.ExtensionMethodsDeclaredInEnclosingNamespaceArePreferredOverImported
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.DelegateMembers
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.BoxingConversionOfDelegateReceiver01
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.DefinedInSameClass
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.ExtensionMethodFromUsingStatic
* MSFT.CA.CS.UT.Symbols.ExtensionMethodTests.EnumerationConversionsAreNotAllowed
* MSFT.CA.CS.UT.Symbols.GenericConstraintConversionTests.EmitImplicitConversions
* MSFT.CA.CS.UT.Symbols.GenericConstraintConversionTests.EmitExplicitConversions
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.Bug654522
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.RedundantValueTypeConstraint
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.PartialClass
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.RedundantConstraints
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.SpellingOfGenericClassNameIsPreserved5
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.WhereTypeParameter
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.ThrowT
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.SelfReferentialInheritedConstraints02
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.InheritedObjectConstraint2
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.EmittedObjectConstraint
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.DefaultT
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.AccessToMembersOfInheritedConstraints
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.Members
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.OverriddenMethods
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.SpellingOfGenericClassNameIsPreserved4
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.ConstraintWithSameType
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.CatchT
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.ConstraintOnSynthesizedExplicitImplementationMethod
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.NewT
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.ConstraintWithContainingType
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.ExplicitInterfaceMethods
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.Events
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.ConstraintWithTypeParameter
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.MovedConstraints
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.SelfReferentialInheritedConstraints01
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.SubstitutedLambdaConstraints
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.StructAndUnconstrainedTypeParameterConstraints
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.ExplicitImplementation
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.SelfReferentialInheritedConstraints03
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.Fields
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.EffectiveInterfaceSet03
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.ImplicitReferenceTypeParameterConversion
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.NewConstraintWithValueType
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.NewTStatement
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.CatchTLifted
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.PartialClassOverriddenMethods
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.NullT
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.ImplicitImplementation
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.ConstraintsOnOverriddenMethod
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.ContravariantInterfacesInConstraints
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.SpellingOfGenericClassNameIsPreserved
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.LoadAndPersist
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.Indexers
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.SpellingOfGenericClassNameIsPreserved3
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.TryCast
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.DuplicateConstraintTypes
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.SpellingOfGenericClassNameIsPreserved2
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.LookupObjectMembers
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.BaseWithSameType
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.SelfReferentialConstraintsWithLambda
* MSFT.CA.CS.UT.Symbols.GenericConstraintTests.SelfReferentialInheritedConstraints04
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.ObjectInitializer_Errors
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.AmbiguityPropertyAndNonProperty
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.CanBeReferencedByName
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.IndexedPropertyDynamicInvocation
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.QueryStatementIndexedProperty
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.StaticProperties
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.LambdaWithIndexedProperty
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.ComImport
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.IncrementersAndIndexedProperties
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.DefaultProperty
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.IndexedPropertyDynamicColorColorInvocation
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.Hiding
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.Attributes
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.CanBeReferencedByName_InvalidName
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.OverridesHidesImplements
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.IndexedProperties
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.OptionalParameters
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.PropertyAccesses
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.PropertyGroup
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.ParamsArrayParameters
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.RefParameters
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.OverloadResolution
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.LinqMember
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.ObjectInitializer
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.BaseProperties
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.ReadOnlyWriteOnly
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.OptionalRefParameters
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.IndexedPropertyColorColor
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.InterfaceImplementation
* MSFT.CA.CS.UT.Symbols.IndexedPropertyTests.OverloadResolutionWithSimpleProperty
* MSFT.CA.CS.UT.Symbols.IndexerTests.InterfaceImplementations
* MSFT.CA.CS.UT.Symbols.IndexerTests.ExplicitInterfaceImplementationIndexers
* MSFT.CA.CS.UT.Symbols.IndexerTests.OverrideOneAccessorOnly
* MSFT.CA.CS.UT.Symbols.IndexerTests.CanBeReferencedByName
* MSFT.CA.CS.UT.Symbols.IndexerTests.Indexers
* MSFT.CA.CS.UT.Symbols.InterfaceImplementationTests.ExplicitlyImplementedAccessorsWithoutEvent
* MSFT.CA.CS.UT.Symbols.InterfaceImplementationTests.Bug943542
* MSFT.CA.CS.UT.Symbols.InterfaceImplementationTests.GenericTypeWithObsoleteBangAritySuffixIsNotAvailable
* MSFT.CA.CS.UT.Symbols.OverriddenOrHiddenMembersTests.Bug16887
* MSFT.CA.CS.UT.Symbols.OverriddenOrHiddenMembersTests.MethodConstructedFromOverrideWithCustomModifiers
* MSFT.CA.CS.UT.Symbols.TypeTests.MultiDimArray
* MSFT.CA.CS.UT.Symbols.Source.EnumTests.OperatorOnEnumMember
* MSFT.CA.CS.UT.Symbols.Source.EnumTests.ZeroInEnum
* MSFT.CA.CS.UT.Symbols.Source.EventTests.EventInvocation
* MSFT.CA.CS.UT.Symbols.Source.ExpressionBodiedMethodTests.Emit02
* MSFT.CA.CS.UT.Symbols.Source.ExpressionBodiedMethodTests.PartialMethods
* MSFT.CA.CS.UT.Symbols.Source.ExpressionBodiedMethodTests.Emit01
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.CallMethodsDirectly
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.SignaturesDifferByModOptsOnly
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.PropertyWithParametersAndOtherErrors
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.PropertyAccessorDoesNotHideMethod
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.Bug1073332_01
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.CanReadInstancePropertyWithStaticGetterAsStatic
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.PropertyNonDefaultAccessorNames
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.ImportDefaultPropertiesWithParameters
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.SubstitutedPropertyWithParameters
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.PropertyAccessorDoesNotConflictWithMethod
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.PropertyWithParametersHidingMethod01
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.MethodsReferencedInMultipleProperties
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.MethodsAndAccessorsSame
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.WinRtPropertySet
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.PropertyWithParametersHidingMethod02
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.PropertyWithParametersHidingMethod03
* MSFT.CA.CS.UT.Symbols.Source.PropertyTests.NoSequencePointsForAutoPropertyAccessors
* MSFT.CA.CS.UT.Symbols.Source.ExpressionBodiedPropertyTests.Emit01
* MSFT.CA.CS.UT.Symbols.Source.ExpressionBodiedPropertyTests.AccessorInheritsVisibility
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.GenericsClosedOverLocalTypes1_2
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.LocalTypeSubstitution1_1
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.NestedType1
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.CyclicReference_3
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.GenericsClosedOverLocalTypes1_3
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.NestedType4
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.CyclicReference_2
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.GenericsClosedOverLocalTypes1_1
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.LocalTypeSubstitution1_2
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.NestedType3
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.Bug685240
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.CyclicReference_1
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.LocalTypeSubstitution1_3
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.NestedType2
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.GenericType1
* MSFT.CA.CS.UT.Symbols.Retargeting.NoPia.HideLocalTypeDefinitions
* MSFT.CA.CS.UT.Symbols.Metadata.PE.DynamicTransformsTests.TestDynamicTransformsBadMetadata
* MSFT.CA.CS.UT.Symbols.Metadata.PE.LoadingIndexers.LoadBogusParameterNames
* MSFT.CA.CS.UT.Symbols.Metadata.PE.LoadingIndexers.LoadNonIndexer_NoDefaultMember
* MSFT.CA.CS.UT.Symbols.Metadata.PE.LoadingIndexers.LoadParameterNames
* MSFT.CA.CS.UT.Symbols.Metadata.PE.LoadingMethods.TestVirtualnessFlags_CSharpRepresentation
* MSFT.CA.CS.UT.Symbols.Metadata.PE.LoadingNamespacesAndTypes.TestStructParameterlessConstructor_Implicit2
* MSFT.CA.CS.UT.Symbols.Metadata.PE.LoadingNamespacesAndTypes.TestStructParameterlessConstructor_Explicit
* MSFT.CA.CS.UT.Symbols.Metadata.PE.LoadingNamespacesAndTypes.TestStructParameterlessConstructor_Implicit1
* MSFT.CA.CS.UT.Symbols.Metadata.PE.TypeForwarders.EmitForwarder_WithModule
* MSFT.CA.CS.UT.Symbols.Metadata.PE.TypeForwarders.EmitForwarder_OpenGeneric
* MSFT.CA.CS.UT.Symbols.Metadata.PE.TypeForwarders.EmitForwarder_Nested_Private
* MSFT.CA.CS.UT.Symbols.Metadata.PE.TypeForwarders.EmitForwarder_Nested
* MSFT.CA.CS.UT.Symbols.Metadata.PE.TypeForwarders.EmitForwarder_NestedGeneric
* MSFT.CA.CS.UT.Symbols.Metadata.PE.TypeForwarders.EmitForwarder_Simple
* MSFT.CA.CS.UT.Symbols.Metadata.PE.TypeForwarders.EmitForwarder_ConstructedGeneric
* MSFT.CA.CS.UT.Symbols.Metadata.PE.TypeForwarders.EmitForwarder_InNamespace
* MSFT.CA.CS.UT.Symbols.Metadata.PE.TypeForwarders.EmitForwarder_MultipleNested
* MSFT.CA.CS.UT.Symbols.Metadata.PE.TypeForwarders.EmitForwarder_OverlappingGeneric

**Comment by jaredpar** [comment]
This will be fixed as a part of moving to #7138
