### ISSUE TITLE
[Feature] create ObsoleteAttribute CodeFix to replace obsolete method with new one

### ISSUE THREAD

**Issue by Meir017** [dotnet/roslyn#33519]
a possible way could be adding new properties to the `ObsoleteAttribute`

```cs
public sealed class ObsoleteAttribute : Attribute
{
    public Type NewType { get; set; }

    public ObsoleteAttribute(Type newType)
    {
        _message = $"Use {newType.Name} instead.";
        _error = false;
        NewType = newType;
    }

    public ObsoleteAttribute(Type newType, bool error)
    {
        _message = $"Use {newType.Name} instead.";
        _error = error;
        NewType = newType;
    }
}
```

then the warning could also suggest a rename

**Comment by CyrusNajmabadi** [comment]
@Meir017 Sorry, i'm not understanding what this proposal is asking for . Can you flesh it out more (including examples of what the user would start with and what the codefix would do for them)?  Thanks!

**Comment by Meir017** [comment]
an example from https://github.com/aspnet/AspNetCore/issues/7749
each time the `ObsoleteAttribute` is used its called with a message that in plain text suggest the new type to be used. if the new type would be passed in as a parameter it could be used in a code-fix

so instead of writing
```cs
[Obsolete("Use IHostApplicationLifetime instead.", error: false)]
```
it would be
```cs
[Obsolete(newType: typeof(IHostApplicationLifetime))]
```

with 2 new constructors:
```cs
public ObsoleteAttribute(Type newType)
{
    _message = $"Use {newType.Name} instead.";
    _error = false;
    NewType = newType;
}
public ObsoleteAttribute(Type newType, bool error)
{
    _message = $"Use {newType.Name} instead.";
    _error = error;
    NewType = newType;
}
```

**Comment by CyrusNajmabadi** [comment]
This isn't an IDE feature.  You're asking for the BCL to change rt to ObsoleteAttribute.  can you please move this to the corefx repo?

**Comment by Meir017** [comment]
Issue moved to [dotnet/corefx #35498](https://github.com/dotnet/corefx/issues/35498) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sharwell** [comment]
@Meir017 if you use the transfer issue feature of GitHub, it will preserve the correct author of comments and add the appropriate redirects.
