### ISSUE TITLE
[Regression] When both completion and signature help are showing, arrow keys incorrectly change signature help

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#33510]
**Version Used**: 
Version 16.0.0 Preview 4.0 [28619.22.d16.0]

This is a regression from 15.9.

When both signature help and completion window are open, the arrow keys affect the signature help, instead of what previously used to affect the completion window:
![signaturehelp](https://user-images.githubusercontent.com/1103906/53073040-0c775300-353b-11e9-9a23-c5fb278985e1.gif)

**Comment by davkean** [comment]
This is very annoying.

**Comment by CyrusNajmabadi** [comment]
I believe this is a dupe of https://github.com/dotnet/roslyn/issues/32940

**Comment by davkean** [comment]
Agreed.
