### ISSUE TITLE
Switch Expression Evaluates to wrong type

### ISSUE THREAD

**Issue by mharthoorn** [dotnet/roslyn#33527]
**Version Used**: 
Visual Studio 2019 (16.0.0) Preview 3, C# 8

**Steps to Reproduce**:
The following code gives an error:
   
```csharp
    int n = 1;
    string s = (n % 2) switch { 0 => "even", _ => "odd" } + " number";
```
>   Operator '+' cannot be applied to operand of type 'string'

**Observed Behavior**
The compiler seems to evaluate the type of the switch-expression-as-a-whole by the expression before ```switch``` keyword (in this case ```int```?)

**Expected Behavior**:
It seems more logical to evaluate it by the 'return value of the switch expression (in this case ```string```).

**Note**
Putting brackets around the switch expression, mitigates this error. But this should not be needed I think.
```csharp
      string s = ( (n % 2) switch { 0 => "even", _ => "odd" } ) + " number";
```

**Comment by gafter** [comment]
This is likely a parsing precedence error (the switch expression is the same precedence as a comparison operator, while `+` binds more closely).  But the diagnostic should be better.

**Comment by mharthoorn** [comment]
The issue is gone in the latest release (VS2019 - 16.0.0 preview 4)

**Comment by gafter** [comment]
This issue should go away with the precedence change in https://github.com/dotnet/roslyn/pull/34481

**Comment by gafter** [comment]
This is no longer reproducible.
