### ISSUE TITLE
#nullable in linq does not recognize where filter.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33539]
VSF_TYPE_MARKDOWNI have a function that returns a nullable tuple.

```
        static (string Modulename, string Suffix, int Major, int Minor, int Bug, int Build)? ParseFileName(string FileName) {
```
I use it in a LINQ statement:

```
            var SubFolders = diSetupFolder.EnumerateDirectories().Select(di =&gt; (di, Parsed: ParseFileName(di.Name))).
                    Where(t =&gt; t.Parsed != null).
#pragma warning disable CS8629 // Nullable value type may be null. // The line above precludes t.Parsed being null so t.Parsed.Value should not be a problem.
                    OrderByDescending(t =&gt; t.Parsed.Value).
                    Select(t =&gt; (t.di, Parsed: t.Parsed.Value));
#pragma warning restore CS8629 // Nullable value type may be null.
```
The where clause precludes t.Parsed being null, so there should be no problem using t.Parsed.Value. Without the pragmas, I get warnings.

Full code attached.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/437256/nullable-in-linq-does-not-recognize-where-filter.html
VSTS ticketId: 779106_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by gafter** [comment]
This is (unfortunately) by design.  The signature of `Where` does not indicate that it has any effect on the contents of the sequence that it returns, or that it ever invokes the delegate passed to it.

**Comment by gafter** [comment]
If you want the language design changed to accomodate this, please create a specific proposal for how the language specification should be modified to `csharplang`.

**Comment by silversj** [comment]
I am not suggesting that the delegate be executed. Just that the delegate's signature be considered non-nullable if the Where is a test for !=null . This is no different than the C# compiler does for, say:

> if (t.Parsed != null) x=t.Parsed.Value;

**Comment by gafter** [comment]
In a where clause, `Where` is typically of a signature like

What, precisely, do you mean by “the delegate’s signature be considered non-nullable”?

**Comment by silversj** [comment]
With the #nullable flag, the signature should read something like
`IEnumerable<object> Where(this IEnumerable<object?> input, Func<object?, bool> filter)`
when the filter is
`obj => (obj!=null)`

**Comment by gafter** [comment]
That would not be correct if, for example, the implementation of Where returns the input. How should the compiler know what the implementation does?

**Comment by CyrusNajmabadi** [comment]
@gafter, i thnk the idea would be to somehow  these 'Where' methods to convey this information.  Similar to however `string.IsNullOrEmpty` needs to work.  It may be a hyper specialized type of attribute, but would effectively indicate that if you have `.Where(x => <some null check of x>)` then `IEnumerable<X>` you get back is informed appropriately.

Note: i agree that as it stands now, the language is probably behaving as currently designed.  The questions is whether or not there is merit in finding some way to imbue query-expressions (or lambda-taking methods) to help inform the resultant type depending on the lambda passed them.

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv if has any idea.  I'm struggling to think of an easy way to express this.  Everything i come up with seems like a hyperspecialized approach of some annotation that basically means:

> this is a well-behaved 'Filter' method.  If you do a null test against an instance of the generic type, you'll get an appropriate non-null instance on the other end.

**Comment by jcouv** [comment]
I don't have a good idea to make this work without changing the code/query.

One option would be to add another call in the LINQ query.
The method would have a signature like `IEnumerable<T> EnsureNoNulls(this IEnumerable<T?> x) where T : class`. 
In DEBUG, it would assert that all the elements are non-null. 
In RELEASE, it would be a pass-through with a suppression (`!`).

Another option is to cast the `IEnumerable<string?>` to an `IEnumerable<string>` with a suppression.

**Comment by broomfn** [comment]
+1, I
