### ISSUE TITLE
Provide a way to visually inspect the inheritance hierarchy 

### ISSUE THREAD

**Issue by vatsalyaagrawal** [dotnet/roslyn#33532]
View type/member hierarchy - display a hierarchy with links to base and derived types/members. 

Go To Implementation provides a list of derived types/members, but without (a) base types/members or (b) showing the inheritance relationship between different items

**Comment by vatsalyaagrawal** [comment]
related to #32149

**Comment by vatsalyaagrawal** [comment]
Codemap provides support for this. Though it is not very efficient for this purpose.

**Comment by mwelsh1118** [comment]
ReSharper has:
1) Right-click a type/member declaration
2) Inspect->Hierarchies
This shows a window with the type or member inheritance hierarchy displayed as a tree view

**Comment by kendrahavens** [comment]
Another internal note: go to implementation should also offer opening a separate window if there are multiple options to navigate to.

**Comment by mikadumont** [comment]
Tracking with this issue: https://github.com/dotnet/roslyn/issues/32149
