### ISSUE TITLE
An invocation of a "non-virtual" delegate to a default interface implementation calls the method virtually

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#33535]
The underlying CLR issue is tracked here https://github.com/dotnet/coreclr/issues/22728.
A number of test scenarios are affected by this issue and relevant portions of unit-tests are temporarily disabled. Should be enabled once the underlying issue is fixed.

- Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.ExplicitBase_107_Delegate
- Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.ExplicitBase_150_Delegate

**Comment by gafter** [comment]
The `base(T)` feature has been removed from C# 8 and is not supported in the CLR at this time, so this report is obsolete.
