### ISSUE TITLE
If an assignment requires a cast to make it compile, add a refactoring that will introduce cast refactoring

### ISSUE THREAD

**Issue by vatsalyaagrawal** [dotnet/roslyn#33533]
Introduce cast refactoring - if an assignment requires a cast to make it compile, add a refactoring that will add the cast to the right side of the assignment

**Comment by CyrusNajmabadi** [comment]
@vatsalyaagrawal Would you be interested in contributing a PR here?  I can help walk you through this.  Cheers! :)

**Comment by mwelsh1118** [comment]
If the left side of an assignment is of type Whatever, ReSharper supports this with Ctrl+.->Cast to 'Whatever' (where such a cast is legal)

**Comment by y87feng** [comment]
This quick action is added in C# starting with 16.6.P2 with the name **Add explicit cast** 
https://github.com/dotnet/roslyn/issues/40967

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/43351
