### ISSUE TITLE
Add braces refactoring should work for arbitrary selection 

### ISSUE THREAD

**Issue by vatsalyaagrawal** [dotnet/roslyn#33530]
currently, putting the cursor on an if statement without braces will bring up this refactoring. Also allow Add braces around whatever the current multi-line selection is.

**Comment by vatsalyaagrawal** [comment]
possibly related to #31879

**Comment by mwelsh1118** [comment]
With ReSharper, select an arbitrary group of statements, Ctrl+.->Surround with block

**Comment by sharwell** [comment]
Design review conclusion: the user's request is *likely* already available through the Surround With snippets (which already supports things like placing a selection of code within an `if` statement). #33693 was filed as a way to improve discoverability and usability of this feature. If the user is still specifically requesting *just placing code in a block*, we could add a new Surround With snippet for this behavior, but that work is blocked on #31879.

Marking as Need More Info until we determine if the current snippets provide enough functionality to address the request.

**Comment by mwelsh1118** [comment]
The snippets combined with the existing Ctrl+.->Add braces (around single-line ifs/loops) satisfy our request. Thanks.
