### ISSUE TITLE
VS 15.9.7 IDE0025 Codefix Bug

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33561]
IDE0025 changes this:

```csharp
public static bool Value
{
#if DEBUG
    get => true;
#else
    get => false;
#endif
}
```

To this:

```csharp
public static bool Value => true;
```

The codefix should either not be offered for code with directives or refactor with the directives in place.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/465374/vs-1597-ide0025-codefix-bug.html
VSTS ticketId: 797928_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  Seems likely that it was fixed at some point.
