### ISSUE TITLE
Roslyn Package failure on Dev16 master branch

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#33579]
**Version Used**: 16.0.0 Preview 4.0 [28621.89.master]

**Steps to Reproduce**:

1. Open the project system solution (presumable this will reproduce with any managed project)

**Expected Behavior**:

No errors in the activity log

**Actual Behavior**:

```XML
  <entry>
    <record>933</record>
    <time>2019/02/21 22:43:23.753</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [Code Analysis Package]Source: &apos;System.ComponentModel.Composition&apos; Description: Cannot cast the underlying exported value of type &apos;Microsoft.VisualStudio.CodeAnalysis.IVCCodeAnalysisServiceProxy&apos; to type &apos;Microsoft.VisualStudio.CodeAnalysis.IVCCodeAnalysisServiceProxy&apos;.&#x000D;&#x000A;</description>
    <guid>{B20604B0-72BC-4953-BB92-95BF26D30CFA}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>
```

**Comment by jinujoseph** [comment]
cc @agocke

**Comment by jmarolf** [comment]
I actually think this is a product issue @heejaechang 	do you know who owns `IVCCodeAnalysisServiceProxy`?

**Comment by jinujoseph** [comment]
@mavasani , is this standcore package ?

**Comment by mavasani** [comment]
@jinujoseph This is C++ service that Kyle recently added in stanpackage. We should talk to C++ team for help.
