### ISSUE TITLE
Missing possible dereference of a null reference warning in an `if` block that guarantees its wrong

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#33580]
**Version Used**: 28620.216.d16.0

**Steps to Reproduce**:

Create a C# .NET Core project with this class:

```cs
#nullable enable

using System;

class Program
{
    public static void Foo(object o)
    {
        if (o == null)
        {
            //o = null;
            o.ToString(); // I expect CS8602 here!
            throw new ArgumentNullException(nameof(o));
        }

        o.ToString();
    }
}
```

**Expected Behavior**:

I expect CS8602 to show up on the line indicated above.

**Actual Behavior**:

The warning does not show up unless I uncomment the line above it.

While it's true that `Foo(object)` indicates the identifier is non-nullable, it is also true that there is no runtime check to guarantee that, and as a public method I need to throw `ArgumentNullException` if it is null rather than a `NullReferenceException` in case my caller passes in null. So within my `if` block that checks if it is null, if I then dereference it, the compiler should raise a warning. But it only does so if I explicitly set it to the value it is already confirmed by the compiler to be.

**Comment by gafter** [comment]
Dup of https://github.com/dotnet/roslyn/issues/33526
