### ISSUE TITLE
Race condition in SolutionExplorer_InProc.WaitForBuildToFinish

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#33597]
**Version Used**: f32205e548feffc6b763877866abbb47f1719a98

It's possible for `SolutionExplorer_InProc.WaitForBuildToFinish` to never return due to a race condition in managing the event states. This method and `SolutionExplorer_InProc.BuildSolution` should be updated to ensure consistently-correct behavior.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we have an issue here, we should just fix it.
