### ISSUE TITLE
SyntaxFactory allows incoherent values

### ISSUE THREAD

**Issue by Jake456** [dotnet/roslyn#3359]
`SyntaxFactory.ClassOrStructConstraint()` has an overload which accepts both a SyntaxKind and a SyntaxToken.
1. The kind is redundant once the token has been specified.
2. The API doesn't validate that the 2 match.

The following won't throw any error:

    var constraint = SyntaxFactory.ClassOrStructConstraint(
        SyntaxKind.ClassConstraint, 
        SyntaxFactory.Token(SyntaxKind.StructKeyword));

**Comment by gafter** [comment]
The syntax factories aren't really supposed to validate their input very deeply. For example, this method also doesn't check that you have placed a space between the keyword and the identifier that is the name. The parser is used for checking syntactic constraints.

/CC @mattwar

**Comment by Jake456** [comment]
Well, this can lead to much bigger problems when working on the inconsistent trees.
You can get all kinds of unexpected results in the semantic model, which will be very hard to track down.

Notice that the user provides nodes to the compiler by the use of analyzers. If you don't perform proper verifications, you'll be the one to deal with the user complaints later.

IMO this should be fixed ASAP.

**Comment by mattwar** [comment]
@Jake456 The semantics of non-terminals are defined by the syntax kinds, not the keyword tokens.  The tokens exist in the tree to maintain fidelity of the input source.  

Analyzers do not provide nodes to the compiler, they analyze nodes that are provided by the parser.  A code fix may manipulate/create nodes, but that is an editing operation that in the end simply constructs new source text.

Note: It is possible to manually construct new compilations/semantic-models with hand built trees that may have inconsistent tokens, but the semantic model should not depend on them.
