### ISSUE TITLE
Signature info gets incomprehensible in presence of extension methods, generics and tuples

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#33609]
The displayed signature of `SelectAsArray` extension method is:

```C#
ImmutableArray<TResult> ImmutableArray<(DocumentId DocumentId, ImmutableArray<LineChange> Deltas)>.
SelectAsArray<(DocumentId DocumentId, ImmutableArray<LineChange> Deltas), TResult, TArg>(
Func<(DocumentId DocumentId, Immutable<ArrayChange> Deltas), TArg, TResult> map, TArg arg)
```

![image](https://user-images.githubusercontent.com/41759/53264321-30987880-3690-11e9-806e-378d324546c9.png)

It's really hard to parse this when choosing between overloads of the method. We should think about better visualization of complex signatures.

The method itself is conceptually simple - it takes a lamda and applies it to elements of immutable array, but this is completely lost in the signature info. The problem is most apparent when tuples are substituted to generic parameters of Funcs.

**Comment by tmat** [comment]
One idea would be to calculate some metrics that determines complexity of signature with substituted generic parameters. If the metric is greater than some threshold introduce aliases for repeated types. Something like:

```
`T ::= (DocumentId DocumentId, ImmutableArray<LineChange> Deltas)

ImmutableArray<TResult> ImmutableArray<`T>.SelectAsArray<`T, TResult>(Func<`T, TArg, TResult> map, TArg arg)
```

**Comment by tmat** [comment]
@cartermp It seems that F# would have similar issue. Is there some technique you're using to simplify signature info for complex types?

**Comment by CyrusNajmabadi** [comment]
We already do this for anonmous types.  Seems like it might make sense to just expand this out to tuples int he same manner all the time.  Maybe for the simplest tuples we wouldn't have to.  But it seems like it would be generally necessary the moment you get any complexity.

**Comment by cartermp** [comment]
@tmat we wrap docs, but we can also get some explody-looking tooltips as well 😢 

We do extract the concrete type in tooltips:

<img width="902" alt="image" src="https://user-images.githubusercontent.com/6309070/53267068-537a5b00-3697-11e9-8be0-6f850bcf84af.png">


But it's not 100% consistent:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/6309070/53267080-5ffeb380-3697-11e9-89ba-8a2ff8c5b8f1.png">

So I'd say it needs "PM work", but as the first screenshot shows, the tooltip can still be rather large.

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi You fixed this issue in https://github.com/dotnet/roslyn/pull/56025, so it should be closed now

**Comment by CyrusNajmabadi** [comment]
SGTM! :)
