### ISSUE TITLE
Wrap parameters/arguments significantly breaks muscle memory

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#33605]
**Version Used**: Dev16 IntPreview (preview 4.0)

Wrap parameters/arguments seems to show up above almost every useful refactoring. Even worse, it has a submenu, which is auto-expanded on <kbd>CTRL+.</kbd>. So, if I try to bring up the light bulb to reorder parameters, convert a method to an expression bodied member, or even add named arguments, I have to first arrow <kbd>Left</kbd> to get out of the submenu, and then arrow <kbd>Down</kbd> to get to the refactoring or fix that I need.

IMO, this is a nice clean up feature but does not add enough value to warrant being on the top of the light bulb menu. At the moment, it feels like it actively is trying to get in my way. It's even more frustrating that it is offered or parameter and argument list that don't need wrapping!

Just pressed <kbd>CTRL+.</kbd> to add named arguments:

![image](https://user-images.githubusercontent.com/116161/53256236-3be1a900-367c-11e9-9ae1-09c6317f88fd.png)

**Comment by CyrusNajmabadi** [comment]
I believe tehre was discussion about these always being low priority.  Not sure what ever came of that though.

**Comment by DustinCampbell** [comment]
Yeah, it doesn't seem like that ever happened. It's pretty painful right now!

**Comment by D3-LucaPiombino** [comment]
I did always though that the items should be ordered using MRU or LRU(or at least it should be an option somewhere).
Coderush did this and it worked nice in practice.

When doing refactoring sessions it often happen that you need to apply the same action multiple times.

Just my 2c. :)

**Comment by CyrusNajmabadi** [comment]
@D3-LucaPiombino We tried that at one point.  It makes sense if all code actions in all locations are equal. But often they are not.

**Comment by CyrusNajmabadi** [comment]
@DustinCampbell 

> Yeah, it doesn't seem like that ever happened. It's pretty painful right now!

Sorry about that! I've created a PR to help out here!

**Comment by DustinCampbell** [comment]
Thanks @CyrusNajmabadi!

**Comment by jinujoseph** [comment]
also reported [DC ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801341)

**Comment by DustinCampbell** [comment]
@jinujoseph : Did this not meet the bar for 16.0? Are we really going to ship this way?

**Comment by CyrusNajmabadi** [comment]
What's the time delta on 16.0 being released and this PR making it to customers?  It'll ideally only be a few weeks right?  If so, that doesn't seem too bad in terms of time with this behavior.  We've def had other bad behavior slip through that we punted on, so this seems ok.

**Comment by DustinCampbell** [comment]
@CyrusNajmabadi : Unfortunately, no, that's not the case. Not all customers use VS from a Preview channel. The release channel wouldn't see this until the official release of 16.1.

**Comment by CyrusNajmabadi** [comment]
> The release channel wouldn't see this until the official release of 16.1.

Oh, htat's kinda what i meant.  Is 16.1 not going to be very soon after 16?

**Comment by DustinCampbell** [comment]
As always, there will be a preview cycle before 16.1 is finally pushed to the release channel. I can't speak to the length of that cycle.

**Comment by jinujoseph** [comment]
@DustinCampbell  doing a barcheck for 16.0 on this.
