### ISSUE TITLE
Link on delegate inside of anonymous method

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33619]
<p>I suggest to add &quot;this&quot;-analog for anonymous methods for easier use when it is essential to remove handler from event inside of handler itself<br>before</p><pre>Timer timer = new Timer();
//ignoring right signature for simplifying
Action a = null;
a = () =&gt;
{
    //Dosmth
    timer.Elapsed -= a;
}
timer.Elapsed += a;</pre>
after:<br><br><pre>Timer timer = new Timer();
//ignoring right signature for simplifying
timer.Elapsed += () =&gt;
{
    //DoSmth&lt;br&gt;   //thisDelegeate is the link on current delegate. Exactly this i suggest to add&lt;br&gt;    timer.Elapsed -= thisDelegeate;
}</pre>
<br>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/460725/link-on-delegate-inside-of-anonymous-method.html
VSTS ticketId: 795742_
_These are the original issue comments:_

Jane Wu [MSFT] on 2/18/2019, 11:58 PM (3 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by gafter** [comment]
This is a language request.  Moving to csharplang

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #2260](https://github.com/dotnet/csharplang/issues/2260) via [**ZenHub**](https://www.zenhub.com/)
