### ISSUE TITLE
Find All References is broken on mixed F# and C# solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33627]
VSF_TYPE_MARKDOWNWe are waiting for more then two years while the Visual Studio team will fixed this issue. But the issue is still in the VS 2019 Preview 3.
We always need to unload F# projects from the solution for the normal fork with Find All References feature.

I have attached a small sample project. The issue can be reproduced in VS 2017 (15.9.7) and in VS 2019 Preview 3.
Steps to reproduce:
1. Open the attached project
2. Open the Class1 file from the CSLibrary
3. Try to execute Find All References on the GetInt function

Actual result:
The Find All References operation is never be finished

Expected result:
Show all references for the GetInt function.

Please fix this issue before VS2019 will be released.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/464811/find-all-references-is-broken-on-mixed-f-and-c-sol.html
VSTS ticketId: 797556_
_These are the original issue comments:_

Visual Studio Feedback System on 2/21/2019, 00:40 AM (2 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
related to https://github.com/dotnet/roslyn/issues/28474

**Comment by jinujoseph** [comment]
Also reported at [DC](https://developercommunity.visualstudio.com/content/problem/522231/find-all-reference-never-completes-when-f-project.html)

**Comment by CyrusNajmabadi** [comment]
I don't repro this. The FAR operation completes for me on latest VS builds.
