### ISSUE TITLE
More Identifier Colours

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33620]
<p>for C# colour highlighting all Identifiers are coloured the same. My request is for Constant Identifiers, Static Identifiers, Static Methods and namespaces.  to be independently coloured but have the 'default' option follow the 'identifier' option.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/464514/more-identifier-colours.html
VSTS ticketId: 797125_
_These are the original issue comments:_

Jane Wu [MSFT] on 2/21/2019, 02:38 AM (36 hours ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by kendrahavens** [comment]
Currently with Visual Studio 2019 in **Tools > Options > Environment > Fonts and Colors** you can set `Symbol - Static` to bold to distinguish statics. 
![image](https://user-images.githubusercontent.com/8293542/53277701-1ffcf800-36ba-11e9-8fba-2349eddbb4d5.png)

You can also customize constants with the `User Members - Constants` setting.
![image](https://user-images.githubusercontent.com/8293542/53277690-08be0a80-36ba-11e9-8394-f7c65f32f99c.png)

Do these customization options satisfy this request?
