### ISSUE TITLE
Is there any way to get (and apply) all code fixes

### ISSUE THREAD

**Issue by rikimaru0345** [dotnet/roslyn#33629]
How can I apply all code fixes that VS would normally suggest, but from a custom commandline tool.
I've seen
 https://github.com/dotnet/roslyn/issues/2020 
and 
https://github.com/dotnet/roslyn/issues/2709
but I'm not sure how, or if, they are related.

So basically I want to apply all the built-in code fixes like `IDE0049` ("Name can be simplified") to a `Microsoft.CodeAnalysis.Document`.
Is that possible? If so, here would I start?

I've tried to track down the implementations of those fixes, but they're all marked as internal.
But maybe there's some public static list or enumerable somewhere that contains all of them so outside users can still use and apply them?

**Comment by CyrusNajmabadi** [comment]
There is not.
