### ISSUE TITLE
When we compute a nullable annotation in flow analysis, should we use the context?

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#33639]
The current LDM position is that we use the annotation context to compute the annotations (oblivious versus non-nullable).  We don't currently do this.

For example, in the declaration of a local variable.  If a local variable is declared
``` c#
string s;
```
is it oblivious in a disabled state, but non-null in an enabled state?  For locals, I believe oblivious acts the same as nullable (i.e. the state you get on reading is based on tracking, but you're allowed to assign null).

What if the local's type is inferred?
``` c#
#nullable disable
var s = ""; // Is s oblivious?
```

Also, when doing type inference, would we infer oblivious in a context where the nullability annotations are disabled, but non-null where nullability annotations are enabled?

``` c#
#nonnull enable
T Copy<T>(T t) => t;
T M<T>(T t)
{
    // warning: possibly null dereference; the inferred type argument to Copy is unannotated
    Copy(t).ToString();

#nonnull disable
    // no warning; the inferred type argument to Copy is oblivious
    Copy(t).ToString();
}
```

If `t` above were declared as a nullable reference type (possibly containing null), would we get an annotated inferred type in both contexts?

**Comment by jcouv** [comment]
The note you added on csharplang links somewhere else. I think you meant it to link here instead.
Could you add an example to illustrate the scenario (actual vs. alternatives)? Thanks

**Comment by gafter** [comment]
I fixed the link and updated the description.

**Comment by jcouv** [comment]
Another scenario we discussed which is relevant is:
```C#
#nullable disable
var s = ""; // the `var` is an oblivious string
```

**Comment by gafter** [comment]
Blocked on an LDM decision.

**Comment by gafter** [comment]
This was resolved in https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-04-15.md#use-annotation-context-to-compute-the-annotations .  The answer is "no", and the currently implemented behavior is now the specified behavior.
