### ISSUE TITLE
Avoid passing titles to INotificationService when redundant

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#3363]
Some features unnecessarily pass a "title" to the INotificationService.

A good example of when to pass a title is Extract Method:

![image](https://cloud.githubusercontent.com/assets/235241/8025762/58ed065e-0d16-11e5-8e4c-4deedb610d0d.png)

But there's a few bad examples that we could fix up:
- Rename: 
  ![image](https://cloud.githubusercontent.com/assets/235241/8025763/63cf016c-0d16-11e5-9e9f-7c3b1f54a421.png)
- Go To Definition: 
  ![image](https://cloud.githubusercontent.com/assets/235241/8025766/730dc9a6-0d16-11e5-9380-5607cda9936e.png)

**Comment by dpoeschl** [comment]
Dev12 didn't show the unnecessary "Rename" & "Go to Definition" lines in the above examples. I think this happened because one of our testing tools shows the "title" in the *actual* title bar (instead of the Microsoft Visual Studio" title above), but the VS implementation of INotificationService shows them in the description area as above, where they can sometimes be redundant.

**Comment by Pilchie** [comment]
I don't think we need to dedicate time to this, but people can clean it up as they see it.

**Comment by jasonmalinowski** [comment]
Looking at VSNotificationServiceFactory.cs, we just pass title and description over to the VS `IVsUIShell` service. It looks like there might have been a change there to concatenate the strings like this?

**Comment by CyrusNajmabadi** [comment]
This is not repro for me.  Here's what rename looks like:

![image](https://user-images.githubusercontent.com/4564579/152584919-a07c17ec-10a9-4802-9a52-313e7bd436a5.png)

and gotodef:

![image](https://user-images.githubusercontent.com/4564579/152584946-a91a7b1e-cfef-4bb1-b92e-2da038a6fa1e.png)
