### ISSUE TITLE
IntelliSense: double quote character should not be commit character

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/roslyn#33636]
**Version Used**: 
Visual Studio 2019 Preview 3

**Steps to Reproduce**:

Having any item selected in IntelliSense, press `"`

**Expected Behavior**:
IntelliSense item is not commited, `"` is typed

**Actual Behavior**:
IntelliSense item is commited, `"` is typed after item text.

![2019-02-24_11-58-24](https://user-images.githubusercontent.com/17177729/53297746-93724700-382b-11e9-99b4-171bd5d8e22f.gif)

**Comment by sharwell** [comment]
I generally agree, with the exception that it *should* be a completion character if you are already inside a string. This is relevant for the specific case of completion of an `InternalsVisibleTo` attribute.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
