### ISSUE TITLE
C# Code Style settings should expose dotnet_style_require_accessibility_modifiers editorconfig setting

### ISSUE THREAD

**Issue by jimmylewis** [dotnet/roslyn#33634]
**Version Used**: VS2019 Preview 4 (dogfood)

**Steps to Reproduce**:

1. Open Tools -> Options -> C# -> Code Style
2. Try to find an option to match the dotnet_style_require_accessibility_modifiers editorconfig property

**Expected Behavior**:
Option should exist, as this property exists for editorconfig (and is documented).

**Actual Behavior**:
No options exist.

**Comment by sharwell** [comment]
📝 I'm hoping to move away from Tools&rarr;Options for these options because they have many downsides compared to using .editorconfig.

**Comment by jimmylewis** [comment]
As part of moving away from Tools->Options, is there also consideration being given to having a 1st class .editorconfig editing experience, at least as far as the C#/.NET options go?  I.e. bringing something like the [.editorconfig Language Service](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.EditorConfig) in-box?  

Without some in-editor guidance to crafting these files, Tools->Options dialog at least provides a decent overall summary of what's available and what each one means.  It's sometimes more clear - and much closer to the developer who is already in the IDE - than the [documentation](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017).

**Comment by sharwell** [comment]
Yes, that feature has moved up to a very high priority position since it's a common source of customer problems.

**Comment by CyrusNajmabadi** [comment]
Can you enumerate what the downsides are?

At the end of the day `tools|options` should simply be a front end to .editorconfig.  So it's just a way to ensure people can put in the right values, have things organized well, and have things like previews/explanations of what's going on.  The source of truth should be editorconfig, but there should be a great way to still edit that config (similar to how vscode does the split).

**Comment by sharwell** [comment]
Design review: This is a simple change that only relies on any options page functionality we've already used for other code style options, so we would accept a pull request implementing the proposal.

**Comment by CyrusNajmabadi** [comment]
Editorconfig is the location where we are investing in.  Unlikely to invest in one-off UI experiences in Tools | Options for these now.
