### ISSUE TITLE
Proposal: C# null conditional assignment

### ISSUE THREAD

**Issue by HermanEldering** [dotnet/roslyn#3366]
With the introduction of the null conditional operator it might make sense to also add null conditional assignment, for instance like this:

    targetVariable ?= sourceVariable;

Which would be functional equivalent to:

    // normal method
    if (sourceVariable != null) targetVariable = sourceVariable; 
    // slightly shorter method, but less clear (imo)
    targetVariable = sourceVariable ?? targetVariable;

**Comment by gafter** [comment]
I'm trying to understand why this would be a good thing.

**Comment by HermanEldering** [comment]
It would be similar to the ?. operator in that it reduces the verbosity of the code, so it's advantages are similar. Admittedly, it is probably a less frequent operation. A disadvantage is that is less clear which variable is checked for null compared with the null conditional operator.

**Comment by whoisj** [comment]
I can see some value in an operator like this, though I'm not sure that it brings clarity of any kind.

Basically, the proposal is for a null-coalescing-assignment operator. It does reduce some verbosity in some cases, but there's a ton of holes in the current design like: how do you know which choice it made? It seems to a case for simply coalescing the following statement into a single statement:

```
object myRef = Init();

object testRef;
if ((testRef = Update()) != null)
{
    myRef = testRef;
}

// use myRef ...
```

into

```
object myRef = Init();
myRef ?= Update();
// use myRef ...
```

While I suppose I could see uses for this, I'm not it makes for overly clear code. Additionally, in the flow of things I don't have a way to know if the value of `myRef` is its initial value or the reallocated value and have surrendered flow control. If I explicitly do not care about its value, and only care that it has a value the null-coalescing operator is how to do default values.

```
object myRef = Update() ?? Init();
// use myRef ...
```
This is even more concise and is fairly explicit in that the value after the `??` is the default to value.

**Comment by paulomorgado** [comment]
Would it make a lot more sense to allow `??` to be composed with `=` (like `+`, `-`, etc.)?

    targetVariable ??= sourceVariable;

**Comment by whoisj** [comment]
@paulomorgado interesting idea, but I don't think that fulfills the contract of the null-coalescing-assignment which is to say "assign a value but if it is null, use this default value instead".

The `?=` / `??=` operators are saying "assign a value if the it is not null, otherwise do not assign the value", which is still a like odd but maybe useful.

**Comment by paulomorgado** [comment]
That kind of is different than everything already in C#. Isn't it?
