### ISSUE TITLE
Quick action for Add to local/global resource strings

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#33660]
Migrated from [developer community](https://developercommunity.visualstudio.com/content/idea/460166/add-add-to-localglobal-ressource-strings-if-quick.html).

**Steps to Reproduce**
1. Type (Ctrl+.) on a string.

**Expected Behavior**:
1. Context menu: "add to local resource strings" and "add to global resource strings" to speed up localization dramatically.

**Additionally:** If string contains variables like 
```csharp
"Konvertiere Tabelle " + tabelle + "..."
```
Reformat it to:
```csharp
string.Format(Resources.KonvertiereTabelle, tabelle);
```
and create resource string KonvertiereTabelle with value "Konvertiere Tabelle {0}..."

**Additionally 2:** Choose to change "this string" or "all strings like xyz in project" for both commands.

![image](https://user-images.githubusercontent.com/8293542/53359726-a0a13b80-38e8-11e9-9cf2-b4eab86cb3ca.png)

**Actual Behavior**:
No quick action for adding string to local resource available.

**Comment by jmarolf** [comment]
@chborl 	where you looking into this at some point?

**Comment by chborl** [comment]
Yes, this is a dup of https://github.com/dotnet/roslyn/issues/16624.  I believe it's on the back-burner right now but still planned.

**Comment by chborl** [comment]
Closing as dup of https://github.com/dotnet/roslyn/issues/16624
