### ISSUE TITLE
Integration tests should correctly wait for workspace operations

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#33670]
Currently, waits for `FeatureAttribute.Workspace` only wait for operations tracked by Roslyn. These waits should first wait for asynchronous operations to be processed by the underlying project system(s), and then wait for remaining operations tracked by Roslyn.

> This code is not correct, but cannot be made correct today. The project systems do (or will do soon in the case of csproj) design time builds asynchronously, and there is no strict guarantee that states that the design time build must be complete after the rename has been applied from the perspective of DTE. There might be code today that happens to force a synchronization but that's not in the contract. What is required *prior* to the WaitForAsyncOperation is a wait on the project system that it's pushed the work to the workspace, but the API to do didn't get completed in time for 16.0.

_Originally posted by @jasonmalinowski in https://github.com/dotnet/roslyn/pull/33662#discussion_r260043995_

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
