### ISSUE TITLE
"Quick Actions..." in Annotate view causes error dialog.

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#3367]
Take any file under source control and choose the "Annotate" view. Ctrl+&lt;dot&gt; anywhere in the file.

![image](https://cloud.githubusercontent.com/assets/235241/8027266/7203baa6-0d49-11e5-8476-f03c62acd7a1.png)

**Comment by Pilchie** [comment]
Can you take a look and see if this is us or the editor?

**Comment by jmarolf** [comment]
Based on the call stack this is coming from the editor.  Specifically the editor is trying to get the intellisense manager and there is none.

>
Microsoft.VisualStudio.CoreUtility.dll!Microsoft.VisualStudio.Utilities.PropertyCollection.GetProperty(object key) Line 152	C#
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbController.GetController(Microsoft.VisualStudio.Text.Editor.ITextView textView) Line 49	C#
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbBroker.TryExpandSession(Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet requestedActionCategories, Microsoft.VisualStudio.Text.Editor.ITextView textView, Microsoft.VisualStudio.Text.ITrackingPoint triggerPoint, Microsoft.VisualStudio.Text.ITrackingSpan triggerSpan, bool trackMouse) Line 307	C#
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbBroker.TryExpandSession(Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet requestedActionCategories, Microsoft.VisualStudio.Text.Editor.ITextView textView) Line 253	C#
Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.IntellisenseCommandFilter.TryShowSuggestedActionsAtCaret(Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet requestedCategorySet, bool specifyTriggerSpan) Line 558	C#
Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.IntellisenseCommandFilter.Exec(ref System.Guid pguidCmdGroup = {System.Guid}, uint nCmdID = 1, uint nCmdexecopt = 0, System.IntPtr pvaIn = {System.IntPtr}, System.IntPtr pvaOut = {System.IntPtr}) Line 186	C#
Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(ref System.Guid pguidCmdGroup, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut) Line 67	C#
Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(ref System.Guid pguidCmdGroup, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut) Line 51	C#
Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.BraceCompletionCommandFilter.Exec(ref System.Guid pguidCmdGroup, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut) Line 173	C#
Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(ref System.Guid pguidCmdGroup, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut) Line 67	C#
Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(ref System.Guid pguidCmdGroup = {System.Guid}, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn = {System.IntPtr}, System.IntPtr pvaOut) Line 145	C#
Microsoft.VisualStudio.TeamFoundation.VersionControl.dll!Microsoft.VisualStudio.TeamFoundation.VersionControl.ToolWindowAnnotate.IOleCommandTargetExec(ref System.Guid pguidCmdGroup, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut)	Unknown
Microsoft.VisualStudio.TeamFoundation.dll!Microsoft.VisualStudio.TeamFoundation.ToolWindowBase.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(ref System.Guid pguidCmdGroup, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut)	Unknown
Microsoft.VisualStudio.Platform.WindowManagement.dll!Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.Exec(ref System.Guid pguidCmdGroup = {System.Guid}, uint nCmdID = 1, uint nCmdexecopt = 0, System.IntPtr pvaIn = {System.IntPtr}, System.IntPtr pvaOut = {System.IntPtr}) Line 740	C#
Microsoft.VisualStudio.Platform.WindowManagement.dll!Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Exec(ref System.Guid pguidCmdGroup, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut) Line 8705	C#

**Comment by Pilchie** [comment]
Can you file an internal bug and route to them in that case?

**Comment by jmarolf** [comment]
filed internal bug 1185801
