### ISSUE TITLE
Caret position after undo is incorrect

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#33672]
#33663 revealed a bug in the caret placement following two undo operations in the following code:

https://github.com/dotnet/roslyn/blob/28ef94d8b150a1767e7a128ff6fd07f34678aa73/src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpAutomaticBraceCompletion.cs#L222-L228

In both cases, the caret should be placed *inside* the quotes.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.  If there is an issue here affecting users, we can just fix it.
