### ISSUE TITLE
Faulty compiler error message CS0165

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33671]
A compiler error  message CS0165 appears even though the code is correct.

 private static void MicrosoftFehler()
 {
      MsFehler msf = new MsFehler();

      //  It works - no message appears
      if (msf != null &amp;&amp;  msf.Fkt(out int n) == true)
      {
        Console.WriteLine(n);
      }

      // Here a message appears, although the code is correct:
      // Error CS0165 Use of unassigned local variable  &quot;m&quot;
      //------------------------------------------------------------------------------
      if (msf?.Fkt(out int m) == true)
      {
---&gt;        Console.WriteLine(m);                &lt;----------------------------------------------------------------------------
      }

    }

    
    class MsFehler
    {
      public bool Fkt(out int i)
      {
        i = 100;

        return true;
      }
    }

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/47334/faulty-compiler-error-message-cs0165.html
VSTS ticketId: 421730_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by gafter** [comment]
Although I have sympathy, the current language specification does not have separate "assigned when true" and "assigned when false" states for `operator==`.  Therefore this is a language feature request and I am moving it to csharplang.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #2267](https://github.com/dotnet/csharplang/issues/2267) via [**ZenHub**](https://www.zenhub.com/)
