### ISSUE TITLE
Incomplete handling of Preview language version in diagnostics

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#33684]
Look for "8.0" in src\Compilers\CSharp\Test\Semantic\Semantics\NullableReferenceTypesTests.cs. There are a lot of references to C# 8.0 in error messages. For example:
```
// error CS8630: Invalid 'NullableContextOptions' value: 'Enable' for C# 7.3. Please use language version 8.0 or greater.
Diagnostic(ErrorCode.ERR_NullableOptionNotAvailable).WithArguments("NullableContextOptions", "Enable", "7.3", "8.0").WithLocation(1, 1)
```

Expected:
The message to suggest to use "use the 'preview' language version" suggestion instead.

**Comment by AlekseyTs** [comment]
CC @agocke

**Comment by agocke** [comment]
Yes I noticed there was another error when unfortunately I didn't have enough time left to change all the baselines. This bug may be moot since we can't take it for 16.0 and I'm not sure it's worth taking for any of the updates.

**Comment by AlekseyTs** [comment]
CC @jcouv
