### ISSUE TITLE
Object Browser does not show base types for interfaces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33688]
Priority 1 issue tracked by DC 

When you selected an interface in Object Browser, there is no way to see interfaces that it implements.  There is no &quot;Base Types&quot; node under the interface like there is for concrete types.  There is no logical reason for this.  This is a problem much more so now than in earlier times.  With the proliferation of dependency injection, code is increasingly using interfaces rather than concrete types.  With more and more open source NuGet packages being used, this problem becomes severe, because most open source packages have zero documentation.  For such packages, the only way to see what interfaces another interface inherits from is to click Go to Definition and look at the metadata.  But object browser would be a so much quicker solution.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/151976/object-browser-does-not-show-base-types-for-interf.html
VSTS ticketId: 525997_
_These are the original issue comments:_

null on 1/22/2019, 03:52 AM (34 days ago): <p>Strange: This is only a problem if "My Solution" is active. If you select a Framework version there are the nodes "Base Types" and "Derived Types".</p>

_These are the original issue solutions:_

Роман Квасов solved on 3/6/2018, 11:29 AM (356 days ago), 2 votes: 
<p>Hey! Is anybody here? it is broken at least are year, it is time to fix it!</p>

**Comment by wollmich** [comment]
I've the same problem using Visual Studio Professional 2019 (Version 16.11.18).
If I select `My Solution` or  `Custom Component Set` I don't see `Base Types` nor `Derived Types` for interfaces.

**Comment by CyrusNajmabadi** [comment]
Closing out.  object browser is in maintenance mode and is getting no changes.  this would only happen with some new system, which would be a rewrite.
