### ISSUE TITLE
Nullable reference types: property access inside lambda

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#33696]
**Version Used**: 
VS 2019 Preview 3

**Steps to Reproduce**:
Consider the next block of code:
```csharp
if (typeCache.DebuggerNonUserCodeAttribute != null)
{
    ImmutableArray<AttributeData> attributes = memberSymbol.GetAttributes();
    return attributes.Any(attr => typeCache.DebuggerNonUserCodeAttribute.Equals(attr.AttributeClass)); // CS8602
}
```

**Expected Behavior**:
No warning, because property is being checked for `null` before dereferencing it.

**Actual Behavior**:
CS8602: Possible dereference of a null reference
at `typeCache.DebuggerNonUserCodeAttribute` on the last line

**Comment by gafter** [comment]
Dup of https://github.com/dotnet/roslyn/issues/29617
