### ISSUE TITLE
Microsoft.Net.Compilers.Toolset completion

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#33695]
Once [the PR](https://github.com/dotnet/roslyn/pull/33665) for creating Microsoft.Net.Compilers.Toolset is merged there are several follow up actions that need to be done to complete the change:

- [ ] Change the checked in toolset of Roslyn to use the package. Need to wait for an official build to complete though so we have a fully signed package.
- [ ] Change the checked in toolset of arcade to use the package.
- [ ] Reach out to [RoslynCodeDomProvider](https://github.com/aspnet/RoslynCodeDomProvider) to help move them to the new package.
- [ ] Ensure the CLI team has an issue tracking them moving to the new package.
- [ ] Delete Microsoft.Net.Compilers and Microsoft.NETCore.Compilers

**Comment by PathogenDavid** [comment]
I know that these packages are mostly for internal consumers, but can the descriptions of the deprecated packages be updated to point towards it?

I basically discovered this new package on accident. I wouldn't have found out they were deprecated otherwise.

**Comment by Nirmal4G** [comment]
Why not use `Microsoft.NET.Compilers` for both frameworks and create `Microsoft.NETFramework.Compilers` for `.NET Framework` only package.

Thus we'll have

- `Microsoft.NET.Compilers`
- `Microsoft.NETCore.Compilers`
- `Microsoft.NETFramework.Compilers`

The naming is easy, predictable and understandable. I know that these packages are not officially supported but a lot of people are using it. So, simplifying them like this won't hurt.

Also, since `Microsoft.NET.Compilers` is becoming all-in-one package, it's compatible with existing users since they only relied on it being the NETCLR only package and now it contains both.

I've already did the necessary changes in my fork. [Nirmal4G:hotfix/compiler-packs](/Nirmal4G/dotnet-roslyn/tree/hotfix/compiler-packs)

**Comment by jaredpar** [comment]
> Why not use Microsoft.NET.Compilers for both frameworks and create
> ... but a lot of people are using it. 

In order to support both compilers we had to significantly change the layout of the NuPkg. A significant number of people who were using it both depended on the layout of the package and were auto-updating. That meant changing the package in place would be a substantial breaking change for those customers. Hence we decided that a new package was the smoother approach.

**Comment by Nirmal4G** [comment]
The naming I propose is clear, to the point. It's worth the breaking change. Besides, these are not officially supported artifacts, then why the high level of compat?

Depending on NuGet package layout shouldn't be the recommended approach. Publish a Zip or self-extracting package for those scenarios. If you make consumers depend on every aspect of a published artifact, even those that are private to that artifact like layout, meta etc..., then you won't be able to change anything ever. It'll lead you to make worst decisions like this.

If we want redisributables, I can create a publish target that publishes either zip or self-extracting package (7Zip/RAR/CAB). This way you are free to change layout in the future as NuGet packaging evolves.

**Comment by jaredpar** [comment]
> It's worth the breaking change

Disagree.

> Besides, these are not officially supported artifacts, right? Then, why the high degree of compat?

Older versions of `Microsoft.Net.Compilers` are included in supported products and they are supported in that context. 

> If we want redisributables, I can create a publish target that publishes either zip or self-extracting package (7Zip/RAR/CAB). This way you are free to change layout in the future as NuGet packaging evolves.

This isn't necessary. The new package is in circulation, has been adopted in the scenarios that are critical to us and is functioning just fine.

**Comment by jaredpar** [comment]
Closing as this work item is complete
