### ISSUE TITLE
Nullable reference types: parameter nullability not inferred

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#33694]
**Version Used**: 
VS 2019 Preview 3

**Steps to Reproduce**:
Consider the next code snippet:
```csharp
private void Move(DirectoryEntry sourceDirectory, DirectoryEntry destinationDirectory)
{
    if (sourceDirectory.Parent == destinationDirectory)
    {
        var name = sourceDirectory.Parent.Name; // CS8602
    }
}
```

**Expected Behavior**:
No warning, because parameter `destinationDirectory` is declared as not-nullable, so `sourceDirectory.Parent` cannot be null inside the if statement.

**Actual Behavior**:
CS8602: Possible dereference of a null reference
at `sourceDirectory.Parent` inside the `if` statement.

**Comment by gafter** [comment]
Dup of https://github.com/dotnet/roslyn/issues/29617

**Comment by jcouv** [comment]
I was not able to repro this with 16.0 preview 4.1 with the code below.

I'll go ahead and close this issue, but if you're still observing the problem after updating to preview4, feel free to re-open with additional details to repro. Thanks

```C#

#nullable enable
class Program
{
    Program Parent = null!;
    string Name = null!;

    void Move(Program x, Program y)
    {
        if (x.Parent == y)
        {
            var name = x.Parent.Name; // CS8602
        }
    }
}
```

**Comment by bkoelman** [comment]
Confirmed fixed in VS2019 RC.1 SRV1.
