### ISSUE TITLE
Introduce using statement should offer a using declaration in C# 8.0 projects

### ISSUE THREAD

**Issue by vsccarl** [dotnet/roslyn#33699]
Copied from VSO/796019. Original by @davidwengier

**Version Used**: 
Version 16.0.0 Preview 3.0

**Steps to Reproduce**:
I've enabled C# 8 for my project but the Introduce Using fixer is suggesting to create using blocks. That is perfectly valid, so it could just be a matter of adding another fixer, or option for this one, to add the expression style.

Note that the suggested fix in my case would result in a compile error (see red squiggle), so as well as driving adoption of new language features, the expression version is potentially more likely to be correct.

![d52676e2-53a3-4268-8cd8-80c394c0aa94](https://user-images.githubusercontent.com/12900364/53443538-c863d280-39c0-11e9-8f31-f618741a576d.png)

**Comment by CyrusNajmabadi** [comment]
tagging @jnm2 I thought intro-using was supposed to figure out the appropriate block scope that it creates?

**Comment by jnm2** [comment]
@CyrusNajmabadi There was some discussion on what it should do at https://github.com/dotnet/roslyn/pull/30106#issuecomment-427688516. The existing using declaration really changes the game in this scenario.

I thought for a while about implementing to use a `using` declaration as well as a `using` statement, but it felt like just noise. It only adds the token `using`. As long as the `using` statement actually gets the minimal scope right, that one gives you more information about keeping your scope clean and minimal.

@vsccarl Just fyi on the issue title; you wouldn't call this an expression version. The C# team is calling it a "`using` declaration" (`https://github.com/dotnet/csharplang/pull/1703`). So now we have `using` directives, `using` statements, and `using` declarations.

**Comment by davidwengier** [comment]
That title is my bad, I'll update
