### ISSUE TITLE
Provide support for highlighting usage of multiple identifiers.

### ISSUE THREAD

**Issue by vatsalyaagrawal** [dotnet/roslyn#33701]
Highlight usages of multiple identifiers - currently, placing the cursor on an identifier highlights all usages of that identifier; user would like to highlight two or more different identifiers. Also the read and write to be highlighted with different colors.

**Comment by CyrusNajmabadi** [comment]
> user would like to highlight two or more different identifiers.

I'm trying to understand the use case here...

> Also the read and write to be highlighted with different colors.

FindRefs can help out here.  However, there are far more types of references than just reads/writes.  Would we have colors for all the different sorts of refs we can have?

**Comment by AdamSpeight2008** [comment]
Sometime it would be useful to see if to variables interact with each other, especially writes. To see if one could reuse a variable.

**Comment by sharwell** [comment]
Design review: this needs a more specific proposal to account for the behavior of "Move to Next" and "Move to Previous". In particular, while cycling through the references in the file, the proposal must ensure that the complete set of highlighted references stays constant. While we believe cycling through references should cycle through all highlighted references, the precise order and placement of primary/secondary carets needs to be defined.

> Also the read and write to be highlighted with different colors.

@mavasani can you move this to a separate issue and provide some details regarding the new information FAR is leveraging?

**Comment by vatsalyaagrawal** [comment]
Feedback from another customer: "Suppose I have a method that accepts a path-filter and a period-filter for loading data. I want to be able to see where both filters are used"

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
