### ISSUE TITLE
Broken link language feature doc

### ISSUE THREAD

**Issue by CronosTs** [dotnet/roslyn#33716]
Doc page: https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md
Broken links:

- [Feature] Ranges: https://github.com/dotnet/roslyn/blob/features/range/docs/features/range.md
- [Branch] range: https://github.com/dotnet/roslyn/tree/features/range

**Comment by dsychin** [comment]
This issue seems to have been fixed by #33658 and #35418
