### ISSUE TITLE
Place ‘Microsoft’ directives second when sorting usings

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#33711]
Internal customer request.

Some users consider Microsoft usings similar to System usings as they are `1st party` and considered part of the platform. They'd expect to have an option in **Tools > Options > Text Editor > C# > Advanced > Using Directives** to 'Place ‘Microsoft’ directives second when sorting usings'. This means Microsoft usings would follow System and helpfully separate this from the user's other.

**Version Used**: 
VS 2019 preview 3

**Steps to Reproduce**:

1. Open **Tools > Options > Text Editor > C# > Advanced > Using Directives**

**Expected Behavior**:
Be able to optionally group 'first party' directives at top. With checkbox:
`Place ‘Microsoft’ directives second when sorting usings`

![image](https://user-images.githubusercontent.com/8293542/53459072-535ac200-39ed-11e9-96af-d306bac94e8d.png)

**Actual Behavior**:
No option.

**Comment by CyrusNajmabadi** [comment]
this seems like it would get very excessive.  Say another customer then comes along and says "we want our company namespaces after System, but before Microsoft".

This is likely best handled by a third party analyzer/fixer that they can hten supply as much logic as they want for.

--

Note: in general, i'm opposed to this sort of thing because it's now just a way for code to deviate from teh common patterns found almost anywhere else.  At this point, maybe it's better to just say 'no' and have people just accept these forms?

**Comment by KexyBiscuit** [comment]
Then what about `Xamarin` and `Mono` namespaces?

`System` namespace is mentioned in ECMA 335:

>  Implementers should notice, however, that type names beginning with “System.” and bearing the special Standard Public Key are intended for use by the Standard Libraries: such names not currently in use might be defined in a future version of this Standard.

**Comment by sharwell** [comment]
Tentatively marking as **Won't Fix**; will follow up with additional details and conclusion after design review.

**Comment by jrmoreno1** [comment]
@KexyBiscuit : Mono lives in mscorlib.dll, so I for one, would expect it to show up and be sorted at the top.

@CyrusNajmabadi: I believe the various Microsoft namespaces should be grouped together or considered a meta-group. Either they all go above together or they don’t. I don’t see a need for individual preferences.  It seems reasonable, to ask for all MS namespaces to be grouped together at the top.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi: I believe the various Microsoft namespaces should be grouped together or considered a meta-group. 

The only namespace even recognized by the the C# language is the `System` namespace.  It's where it looks for for many types of special types.  The 'Microsoft' namespaces don't have any special meaning here.

My recommendation, if you want this, is to write your own tool that enforces this ordering.  Roslyn provides a number of APIs for this, and you could even make your own code-action+fixer to fix this up in your own IDE instances.

**Comment by sharwell** [comment]
This went to a design review on 4 March 2019. Our conclusion was to not make a change to the supported _orderings_. For _grouping_, @JoeRobich is working on an expansion of the Organize Usings feature that will better support placing blank lines between groups of using directives based on their first identifier. In practice, this will separate `Microsoft.*` from other using directives even though it won't necessarily be first or second in the list.
