### ISSUE TITLE
Should not get private access fix for implemented methods

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/roslyn#33727]
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.0.0 Preview 1.0 [28329.73.d16.0]
VisualStudio.16.IntPreview/16.0.0-pre.1.0+28329.73.d16.0
Microsoft .NET Framework
Version 4.7.03056

**Steps to Reproduce**:

```vb
   Private Sub B() Implements IA1.B
        Throw New NotImplementedException()
    End Sub
```
1.  The code above says that the method is not used, because it is private. This is a normal way to handle implementations that should only be available via the interface. 

**Expected Behavior**:

No error for interface implementation. 

**Actual Behavior**:

Error that the private method is not used, and a fix is offered.

**Comment by CyrusNajmabadi** [comment]
Tagging @mavasani

**Comment by mavasani** [comment]
Very likely fixed in Preview 4, but I will confirm tomorrow.

**Comment by mavasani** [comment]
Verified no repro on latest VS2019 dogfood bits.
