### ISSUE TITLE
`default` <LangVersion> in MSBuild should target `preview` when the target framework is netcoreapp3.0

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#33721]
This is only until netcoreapp3.0 RTMs, when we switch default back to `latest`

**Comment by BillWagner** [comment]
What's confusing about the current behavior is that "default" specifies different behavior than "the LangVersion is not specified".  

Users would reasonably expect that specifying the "default" value would result in "the default behavior", which would be what happens if nothing was specified.

**Comment by agocke** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/37074 which sets the default to 7.3 when not on netcoreapp3.0.
