### ISSUE TITLE
For argument nested nullability mistmatches, should be exactly one error given (not two)

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#33738]
When a ref parameter is of type `C<string?, string>` but the argument is of type `C<string, string?>`, we give two separate diagnostics.  Instead we should give a single diagnostic that the nested nullability must match exactly.

When an in or normal parameter has a mismatch, the rules are slightly difference (we use the contravariant rules) and we could give a different message.

When an out parameter has a mismatch, the rules are slightly difference (we use the covariant rules) and we could give a different message.

Today, in the ref scenario we sometimes give two distinct diagnostics on the precise same syntax node.  We should avoid that because it is confusing.  As a temporary measure, I am suppressing the second diagnostic once one has been given (see https://github.com/dotnet/roslyn/pull/33648), but we should be more complete in a single diagnostic about what the problem is.

**Comment by jcouv** [comment]
When fixing this issue, we should take a look at `SuppressNullableWarning_Ref_WithNestedDifferences`. It currently doesn't report top-level nullability issue because a nested nullability issue is already reported.
