### ISSUE TITLE
Compiler error when using ranges feature

### ISSUE THREAD

**Issue by tomrus88** [dotnet/roslyn#33748]
**Version Used**: 
VS 16.0.0 Preview 4

**Steps to Reproduce**:
Any code that uses ranges feature is failing to compile

    byte[] a = new byte[] { };
    byte[] b = a[0..1]; // error CS0656

**Expected Behavior**:
No compiler error
**Actual Behavior**:
Error CS0656 Missing compiler required member 'System.Range..ctor'

Same project targeting .NET Core 3.0 (Preview 2) had no compiler errors in VS 16.0.0 Preview 3

**Comment by tomrus88** [comment]
I guess we will have to wait for next .NET Core 3.0 preview for this to work properly?

**Comment by watsonsong** [comment]
I met the same error, and my code is right when I use the preview 3

**Comment by adamtuliper** [comment]
Same here. VSCode (v1.18.0-beta8 omnisharp) still runs but shows the error when you mouse-over the range (red lines are under the range 1..10). Visual Studio 2019 Preview 4 won't run it.

**Comment by stjeong** [comment]
Waiting for next .NET Core 3.0 preview, you can include following Ranges.cs file into your .NET project.

'''
namespace System
{
    public readonly struct Index
    {
        private readonly int _value;

        public int Value => _value < 0 ? ~_value : _value;
        public bool FromEnd => _value < 0;
        public bool IsFromEnd => _value < 0;

        public Index(int value, bool fromEnd)
        {
            if (value < 0) throw new ArgumentException("Index must not be negative.", nameof(value));

            _value = fromEnd ? ~value : value;
        }

        public static implicit operator Index(int value)
            => new Index(value, fromEnd: false);
    }

    public readonly struct Range
    {
        public Index Start { get; }
        public Index End { get; }

        public Range(Index start, Index end)
        {
            this.Start = start;
            this.End = end;
        }

        public static Range Create(Index start, Index end) => new Range(start, end);
        public static Range FromStart(Index start) => new Range(start, new Index(0, fromEnd: true));
        public static Range ToEnd(Index end) => new Range(new Index(0, fromEnd: false), end);
        public static Range All() => new Range(new Index(0, fromEnd: false), new Index(0, fromEnd: true));
    }

    static class Extensions
    {
        public static int get_IndexerExtension(this int[] array, Index index) =>
            index.FromEnd ? array[array.Length - index.Value] : array[index.Value];

        public static int get_IndexerExtension(this Span<int> span, Index index) =>
            index.FromEnd ? span[span.Length - index.Value] : span[index.Value];

        public static char get_IndexerExtension(this string s, Index index) =>
            index.FromEnd ? s[s.Length - index.Value] : s[index.Value];

        public static Span<int> get_IndexerExtension(this int[] array, Range range) =>
            array.Slice(range);

        public static Span<int> get_IndexerExtension(this Span<int> span, Range range) =>
            span.Slice(range);

        public static string get_IndexerExtension(this string s, Range range) =>
            s.Substring(range);

        public static Span<T> Slice<T>(this T[] array, Range range)
            => array.AsSpan().Slice(range);

        public static Span<T> Slice<T>(this Span<T> span, Range range)
        {
            var (start, length) = GetStartAndLength(range, span.Length);
            return span.Slice(start, length);
        }

        public static string Substring(this string s, Range range)
        {
            var (start, length) = GetStartAndLength(range, s.Length);
            return s.Substring(start, length);
        }

        private static (int start, int length) GetStartAndLength(Range range, int entityLength)
        {
            var start = range.Start.FromEnd ? entityLength - range.Start.Value : range.Start.Value;
            var end = range.End.FromEnd ? entityLength - range.End.Value : range.End.Value;
            var length = end - start;

            return (start, length);
        }
    }
}
'''

**Comment by tomrus88** [comment]
Works now after updating to .NET Core 3.0 Preview 3.

**Comment by jcouv** [comment]
@agocke I think this was fixed in .NET Core 3 preview 3. Can you confirm and close if appropriate?

**Comment by agocke** [comment]
Confirmed, this is fixed.
