### ISSUE TITLE
Proposal: Boolean Literal Aliasing

### ISSUE THREAD

**Issue by jcdickinson** [dotnet/roslyn#33753]
## Rationale

*Disclaimer: I'm not sure if this is a good idea. All ideas are worth sharing.*

There is a thought school of developers who believe that booleans are evil. Once piece of code I previously worked with had some 10 boolean arguments, leading to code like this:

```c#
wizard.ShowDialog(host, ..., true, false, false, false, false, true, false, true, true);
```

A more relatable example for most is easy to find: `StreamWriter`.

```c#
new StreamWriter("C:\\tmp\\tmp.txt", true, Encoding.UTF8);
```

What does that `true` mean? Finding out might involve re-typing the opening parenthesis, goto definition or opening the documentation, depending on what your editor is capable of doing. There are also security implications. Don't Google-er-Bing this, off the top of your head, what does this mean?

```c#
SslStream ssl;
ssl.AuthenticateAsServer(certificate, true, false);
```

Opponents of booleans recommend either separate methods (`StreamWriter.CreateAppend` vs. `StreamWriter.CreateNew`) or enums (`new StreamWriter(AppendOptions.Append` or `new StreamWriter(AppendOptions.New)`).

An existing way to deal with this problem would be to:

```c#
new StreamWriter("C:\\tmp\\tmp.txt", append: true, encoding: Encoding.UTF8);
```

The problem with that approach is that "all arguments following a named argument must be named." It adds friction to clarifying code in this way.

We can't simply remove booleans from the framework. It would be nice to go over netcore and allow boolean call sites to document themselves.

## Solution

The following constructor prototype (the syntax could use work):

```c#
StreamWriter(string path, bool<Append, Clear> append, Encoding encoding)
```

Is compiled to the following actual constructor prototype:

```c#
StreamWriter(
  string path,
  [System.Runtime.CompilerServices.BooleanAlias("Append", "Clear")]
  bool append,
  Encoding encoding);
```

It can then be used in one of the following ways:

```c#
new StreamWriter("", bool.Append, null); // Equivalent/compiled to:
new StreamWriter("", true, null); // Is still valid in the face of boolean aliases

new StreamWriter("", bool.Clear, null); // Equivalent/compiled to:
new StreamWriter("", false, null); // Is still valid in the face of boolean aliases
```

Treating `bool` like an enum has two advantages:

* Existing code continues to work when, for example, a local variable or field shares the name with an alias.
* In scenarios where a third option is added, the alias can be promoted to an enum during refactoring with, at worst, find and replace. A Rewriter might be able to automate the whole thing for Omnisharp/VS.

## Other Concerns

Would the following be desirable?

```c#
public bool<Found, NotFound> TryGetValue(TKey key, out TValue value);
if (dictionary.TryGetValue(key, out string value) == bool.Found) { }
```

That smells of the `if(true == true)` redundancy, but it does somehow add value in this case. The existing compiler machinery for named tuple elements could be re-used.

**Comment by CyrusNajmabadi** [comment]
> A more relatable example for most is easy to find: `StreamWriter`.

> ```cs
> new StreamWriter("C:\\tmp\\tmp.txt", true, Encoding.UTF8);
> ```

> What does that `true` mean?

This is pretty simply solved by just writing:

```new StreamWriter("C:\\tmp\\tmp.txt", append: true, Encoding.UTF8);```

The IDE even offers to do this for you if you use the quick-actions feature:

![image](https://user-images.githubusercontent.com/4564579/53544747-0bff2f00-3adc-11e9-9542-dd80360dcc20.png)

**Comment by CyrusNajmabadi** [comment]
> off the top of your head, what does this mean?

> ```cs
> SslStream ssl;
> ssl.AuthenticateAsServer(certificate, true, false);
> ```

it means this:

```c#
            ssl.AuthenticateAsServer(
                certificate, clientCertificateRequired: true, checkCertificateRevocation: false);
```

That seems pretty easy to understand.  It's self documenting.  And it's safe to someone even switching around the order of things.

**Comment by CyrusNajmabadi** [comment]
> The problem with that approach is that "all arguments following a named argument must be named." It adds friction to clarifying code in this way.

This is not true.  See https://github.com/dotnet/roslyn/issues/33753#issuecomment-468150001 as an example :)

**Comment by CyrusNajmabadi** [comment]
> `if (dictionary.TryGetValue(key, out string value) == bool.Found)`

`if (dictionary.TryGetValue(key, out string value)) {` is already idiomatic.  It really doesn't need any changes.

**Comment by gafter** [comment]
Moving to `csharplang` as this is a language feature request.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #2277](https://github.com/dotnet/csharplang/issues/2277) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jcdickinson** [comment]
Thanks @gafter
