### ISSUE TITLE
CS8652 on the RC with C# 8.0

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#33756]
**Version Used**: 

Visual Studio 2019 RC (Version 16.0.0 RC)
LangVersion: 8.0
dotnet version: 3.0.100-preview-010184

**Steps to Reproduce**:

use recursive patterns.

```cs

struct Point
{
    public int X, Y;
    public Point(int x, int y) => (X, Y) = (x, y);
}

class Program
{
    static bool M(Point p) => p is { X: 0 };
}
```

**Expected Behavior**:

No error.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/3760955/53549146-d22f3680-3b76-11e9-87a4-e12c110f4db8.png)

FYI, There is no error if I use VS 16.0.0 Preview 4.0.
I get the same error if I change LangVersion to `preview`.

In addition, I have also the following error on this code in the RC.

Error	NETSDK1045	The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0.	ConsoleAppNetCore30	C:\Program Files\dotnet\sdk\2.2.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	137

**Comment by WilStead** [comment]
Look for this setting (search for "core" to find it easily):

![capture](https://user-images.githubusercontent.com/9659282/53581159-11479280-3b4b-11e9-88a3-7a50f43e5527.PNG)

Make sure "Use previews of the .NET Core SDK" is checked. That should resolve both problems.

**Comment by ufcpp** [comment]
@WilStead 

Oh I see. My issue was solved with that option. Thanks!

**Comment by ufcpp** [comment]
but, the error message is bit confusing...
