### ISSUE TITLE
Infer Tuple item names from method names 

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#33768]
The issue in #28928 has been fixed for anonymous types, but not for tuples.
If I write this:
`var x = (GetType(), Enabled);`
'x' will have the two fields 'Item1' and 'Enabled'. and if I use the pulp suggestions to add the tuple declaration instead of var, it will be:
`(Type, bool Enabled) x = (GetType(), Enabled);`
You can infer the name from method names the same way you did in  #28928 so 'x' declaration becomes:
'(Type Type, bool Enabled);`
and please fix that in the pulp suggestions too.

**Comment by gafter** [comment]
Because this corresponds to the change in #28928, it is an IDE request.

**Comment by sharwell** [comment]
🔗 This issue can be resolved by expanding #29392 (which supports anonymous types) to also support tuple types.

**Comment by CyrusNajmabadi** [comment]
Closing this out as this feature is working correctly.  The original tuple did not have a name for the first member, so the conversion should preserve that.  if the user specified a name in teh tuple, we preserve that when expanding things out.
