### ISSUE TITLE
Settings for using directives not exported to .editorconfig

### ISSUE THREAD

**Issue by jimmylewis** [dotnet/roslyn#33766]
**Version Used**: VS2019 dogfood

**Steps to Reproduce**:

1. Open Tools -> Options
2. Configure settings on Text Editor -> C# -> Advanced for how to style using directives
    * Place 'System' directives first when sorting usings
    * Separate using directive groups
3. Switch to Code Style options and export .editorconfig settings

**Expected Behavior**:
These options for using directives should be exported (dotnet_sort_system_directives_first and dotnet_separate_import_directive_groups respectively)

**Actual Behavior**:
They are not exported to the .editorconfig file

**Comment by sm-g** [comment]
there is also issue with `dotnet_separate_import_directive_groups` itself, it is not recognized:
`Warning	EC112	The keyword "dotnet_separate_import_directive_groups" is unknown.`

**Comment by HenrikWM** [comment]
I can take a look. WIP PR: https://github.com/dotnet/roslyn/pull/34118
