### ISSUE TITLE
Question: Is there an exception filter spec?

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#3378]
I was looking to implement exception filters in Microsoft's Razor language but it looks like there's yet to be an exception filter spec published. The syntax seems relatively simple but wanted to drive the added capability off of a spec to be certain.

Does there happen to be any in-progress specs available for exception filters? If not is there a guestimation for when they may become available?

**Comment by MadsTorgersen** [comment]
@NTaylorMullen The C# 6 language spec is still work in progress, but the exception filters happen to be done. I've emailed you a draft. The rest of the world will have to wait a bit (it's not in easily sharable state), but if someone has a need, let me know.

**Comment by NTaylorMullen** [comment]
@MadsTorgersen you're awesome, thank you!
