### ISSUE TITLE
GetUnreferencedAssemblyIdentities and GetRequiredLanguageVersion

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#33780]
we have these 2 new APIs

GetUnreferencedAssemblyIdentities (http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/Compilation.cs,f745415ec1de2fab) and GetRequiredLanguageVersion (http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/Compilation.cs,2c1d355382c271f9)

1 is instance API and the other is a static method.

both of them work by going through all diagnostic arguments and see whether it has a certain type of arguments.

and we do that for every diagnostic that is reported.

GetUnreferencedAssemblyIdentities restrict the iteration by checking error code. 
GetRequiredLanguageVersion just do that for every diagnostic ever created.

since IDE needs IDiagnosticPropertiesService (http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Diagnostics/IDiagnosticPropertiesService.cs,f8a99c4cb4320520) per language anyway and it is diagnostic.Arguements that is not exposed (internal) but not error code itself, it looks like we can make GetUnreferencedAssemblyIdentities as static method as well? and IDE side check error code before calling GetUnreferencedAssemblyIdentities ? 

another thing is iterating through arguments for every diagnostic ever created (http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Diagnostics/DiagnosticData.cs,c166a245b2b43d22,references) seems a potential perf bottleneck?

we might be able to either restrict or filter out diagnostics without blindly always iterate through all arguments by using properties of diagnostic?

we can also use a singleton property bag so that reducing allocations?

**Comment by heejaechang** [comment]
tagging @jcouv @mavasani @sharwell 

might be not a problem. just noticed while looking around some code.

**Comment by gafter** [comment]
We cannot change a public instance method to be static as that would be an incompatible API change.
