### ISSUE TITLE
Different handling of unreachable code and default fallthrough in switch block

### ISSUE THREAD

**Issue by cyanite** [dotnet/roslyn#33783]
**Version Used**: 
Visual Studio 2019 RC (csc.exe 3.0.19.12206 (ec366687))

**Steps to Reproduce**:
Compile this code (I used `csc.exe Class1.cs -target:library -langversion:7.3`):

    int Foo(bool a)
    {
        switch (a)
        {
            case true:
                return 1;
            case false:
                return 2;
            default:
                return 3;
        }
    }

**Expected Behavior**:
No warnings.

**Actual Behavior**:
You'll get warning CS0162: Unreachable code detected. This wasn't the case with Visual Studio 2017 (csc.exe 2.10.0.0 (b9fb1610)). This warning is of course promoted to an error if warnings as errors is enabled, which is how I found it. Is this a problem? I realize that analysis may have improved.

However, 2019 then suggests replacing it with:

    int Foo(bool a)
    {
        switch (a)
        {
            case true:
                return 1;
            case false:
                return 2;
            default:
        }
    }

Which now compiles without warnings. This code *fails* with Visual Studio 2017:

    CS8070: Control cannot fall out of switch from final case label ('default')
    CS0161: 'Class1.Foo(bool)': not all code paths return a value

But I am using langversion 7.3 for both. Shouldn't the same language version mean that it should compile with the same result?

**Comment by gafter** [comment]
Yes, this is a bug and I will fix it for update 1.

The workaround is to delete your entire default case.  Or use the default label instead of `case false:`.

**Comment by cyanite** [comment]
> The workaround is to delete your entire default case. Or use the default label instead of `case false:`.

Doing that (deleting default) will give an error that not all code paths return a value (even though they obviously do), both in VS2017 and 2019 ;).

Anyway, good to hear it's being fixed.
