### ISSUE TITLE
Consider adding an option `SymbolDisplayFormat` for `ctor` and `cctor`

### ISSUE THREAD

**Issue by ltcmelo** [dotnet/roslyn#33792]
I've only been able to get the actual (source) name of a constructor. It seems that there's no out-of-the box option to get `ctor` or `cctor`. This feature would be interesting for those writing analysis that require symbols to be named as according to the IL.

**Comment by CyrusNajmabadi** [comment]
A more applicable approach may be to have a SymbolDisplayFormat.MetadataFormat, which people could use when generating metadta-names.
