### ISSUE TITLE
Improve experience around rearranging code elements

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#33798]
Move up and Move down commands move elements within a specific scope up and down relatively to other elements in this scope. For example, you can move up and down types in a file, type members in a type, statements in a type member or in a compound statement, etc, 
Needs changes from Platform team too tracked [here ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/555805)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
