### ISSUE TITLE
Samples should use reference assemblies, not runtime assemblies as references

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#3380]
Currently Roslyn samples are using runtime assemblies such as mscorlib and System for metadata references passed to compilation. That limits their usage to Desktop CLR only. If someone copies the sample to Project K (or Core CLR in general) it won’t work.

Most of the samples might just work with portable reference assemblies, of if not they could still target Desktop FX reference assemblies even when running on Core CLR. But they should certainly use reference assemblies.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #36](https://github.com/dotnet/roslyn-sdk/issues/36) via [**ZenHub**](https://www.zenhub.com/)
