### ISSUE TITLE
Roslyn cannot interpret some kinds of assembly written in IL

### ISSUE THREAD

**Issue by pCYSl5EDgo** [dotnet/roslyn#33841]
I tried to define a struct which inherits another struct in IL.
Roslyn shows very strange behaviour when interpreting that .dll file.

**Version Used**: 
Roslyn 3.0.0-beta4-19126-05

**Steps to Reproduce**:

1. Write IL code and compile it with ilasm.exe.
 https://gist.github.com/pCYSl5EDgo/a271e7f713926117989970a6f712dafa
2.  Set the appropriate reference to the DLL from any project.
3.  Read metadata of A0.

**Expected Behavior**:
`public struct A0
{
    public static A0 GetDefaultA0();
}`

**Actual Behavior**:
`public static struct A0
{
    public static A0 GetDefaultA0();
}`

![d0yyuujuyaekhhq](https://user-images.githubusercontent.com/31692496/53714103-85a66c80-3e90-11e9-90ce-3fa6ba15f8b4.jpg)

**Comment by CyrusNajmabadi** [comment]
>I tried to define a struct which inherits another struct in IL.
Roslyn shows very strange behaviour when interpreting that .dll file.

This isn't somethng supported by the C# language.  That Roslyn showed *anything* here for this struct is fine IMO.  The feature you are using (Metadata as Source) is simply doing it's better effort to display the struct as best as we can understand this.

**Comment by tannergooding** [comment]
> I tried to define a struct which inherits another struct in IL.

This is also not something that is expected to work, in general. ILASM is actually really basic and will allow you to construct and compile all kinds of IL that is technically invalid and/or illegal. Generally, this code will cause some kind of "invalid assembly" error at runtime (best case scenario), it could also result in undefined behavior or crash.

In this case, the runtime specification declares:
> Value types shall be sealed, and they shall have a base type of either `System.ValueType` or `System.Enum`

**Comment by YairHalberstadt** [comment]
Given that it's not clear that there's anything to do here, should this issue be closed, or the help wanted label removed?

**Comment by pCYSl5EDgo** [comment]
Trying to inherit struct is not a matter.
The struct A0 doesn't inherit from any struct types. It extends System.ValueType.
@tannergooding and @CyrusNajmabadi s' comment is worthless.

My question is 'Why unsealed unstatic struct A0 is shown as static struct by the feature(Metadata as Source). Isn't it a Roslyn's bug?'.

**Comment by CyrusNajmabadi** [comment]
@pCYSl5EDgo  you said: I tried to define a struct which inherits another struct in IL.

**Comment by CyrusNajmabadi** [comment]
Does anything change if you add `sealed` to A0?

**Comment by CyrusNajmabadi** [comment]
Roslyn views a metadata type as static if it TypeAttributes.Sealed and is also TypeAttributes.Abstract.  Does reflection gives those bits for your A0 type?
