### ISSUE TITLE
Semicolon typed mid-expression goes to an unexpected location

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#33851]
**Version Used**: Visual Studio 2019 Preview 4 Build 28701.123.d16.0

**Repro**: 
I hit <kbd>;</kbd> between the two invocations in this declaration:

![semicolonweirdlocation](https://user-images.githubusercontent.com/235241/53765071-d794c580-3e83-11e9-8175-361e64f25bc0.gif)

**Expected**: The semicolon is inserted at that location. In my scenario, I could then continue typing a down arrow and then comment current line, thus reducing the declaration to just the first call.

**Actual**: The semicolon goes to the end of the entire declaration. Also, it's not done in a two-step undo, so ctrl+z doesn't put the semicolon back where I typed it.

**Comment by dpoeschl** [comment]
FYI @chborl

**Comment by CyrusNajmabadi** [comment]
I literally just hit this as well.  Seems like we might need some semantics around "can this viably complete the statement here?"  And, if so, we should just insert the semicolon.
