### ISSUE TITLE
DesignerAttributeIncrementalAnalyzer needs to consume the new mechanism for registering "sub type" for CPS projects

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#33854]
For performance reasons we opt'd DesignerAttributeIncrementalAnalyzer out of running for CPS projects: https://github.com/dotnet/roslyn/blob/5abb8f9480ade51baf5011d3e525340d933744c8/src/VisualStudio/Core/Def/Implementation/DesignerAttribute/DesignerAttributeIncrementalAnalyzer.cs#L82.

In https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/167537, we've added a new mechanism for registering these attributes on a background thread and in a batch. This avoids CPS from evaluating and running design-time builds constantly while the analyzer is running. Roslyn needs to consume this new API so that our end-to-end for Windows Forms works.

@jinujoseph @heejaechang 

@lifengl @heejaechang What agreement did we come to for Rolsyn to actually consume the API? They don't have a dependency on CPS yet.

**Comment by davkean** [comment]
Ah, missed this part in the PR:

> This PR is to preview this change, so the contract is defined in CPS. We will move it to a VS assembly.

**Comment by heejaechang** [comment]
@davkean thank you I will send out PR.
