### ISSUE TITLE
VS2019.4: "Convert to interpolated string" refactoring is not always offered and does not work correctly in some circumstances

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33865]
Given the following struct:

```csharp
    public struct ListingIdDealerIdTuple
    {
        public int ListingId { get; }
        public int DealerId { get; }

        public ListingIdDealerIdTuple(int listingId, int dealerId)
        {
            ListingId = listingId;
            DealerId = dealerId;
        }

        public override string ToString()
        {
            return nameof(ListingIdDealerIdTuple) + ": "
                + nameof(ListingId) + $" = {ListingId}" + ", "
                + nameof(DealerId) + $" = {DealerId}";
        }
    }
```

We will be concentrating on its `ToString` method.

### Refactoring not always offered

Place the cursor anywhere between the first space and before the } in `$" = {ListingId}"` or `$" = {DealerId}"` and bring up the Quick Actions menu. Note that the &quot;Convert to interpolated string&quot; refactoring is not offered.

Now move the cursor so that it's before, after, or inside the string `": "` or `", "` and again bring up Quick Actions. This time, &quot;Convert to interpolated string&quot; is present.

However, this refactoring is also available if the cursor is placed before the first &quot;, or after the }, in `$" = {ListingId}"` or `$" = {DealerId}".` This is inconsistent.

### Refactoring generates incorrect output

Invoking &quot;Convert to interpolated string&quot; on the string inside `ToString` results in the following:

```csharp
return $"{nameof(ListingIdDealerIdTuple)}: {nameof(ListingId)}{$" = {ListingId}"}, {nameof(DealerId)}{$" = {DealerId}"}";
```

Note that the $ and {} tokens from the interpolations previously present are included as literals in the resulting string. This is incorrect, they should be omitted:

```csharp
return $"{nameof(ListingIdDealerIdTuple)}: {nameof(ListingId)} = {ListingId}, {nameof(DealerId)} = {DealerId}";
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/474404/vs20194-convert-to-interpolated-string-refactoring.html
VSTS ticketId: 806630_
_These are the original issue comments:_

Visual Studio Feedback System on 3/3/2019, 11:31 PM (26 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  I get:

![image](https://user-images.githubusercontent.com/4564579/198118250-ee5931c9-2b79-4037-b592-5556592f2ca8.png)

Which produces:

![image](https://user-images.githubusercontent.com/4564579/198118316-151d5a31-8e86-43a5-876b-2543ba8ca25f.png)


Which appears to be correct afaict.
