### ISSUE TITLE
provide a unit test for "Fix completion at the start of readonly documents"

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#33864]
Here is a scenario:

1. Create a solution of two independent console applications.
2. Do not build application 1
3. Start debugging application 2 and stop at a break point
4. Go to application 1 in editor and set cursor at position = 0
5. Try to type anything.
6. Get "Changes are not allowed if the project wan't built when debugging started"
7. Hit Enter many times: once to close the dialog and the next one to attempt editing again (the cursor must be in the beginning of the file) , again and again.

Here is the fix: https://github.com/dotnet/roslyn/pull/33830
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/809690 should fix the issue on the Editor side as well

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
