### ISSUE TITLE
Revert workaround for "Restore original behavior of Shift+Enter during completion" when fix available

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#33862]
Revert #33828 when  https://devdiv.visualstudio.com/DevDiv/_workitems/edit/809579 will be available on the Editor side

**Comment by sharwell** [comment]
⚠️ Be careful not to revert the specific change in **CSharpIntelliSense.cs** that pull request which enabled an integration test. 😄

**Comment by ivanbasov** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/34729
