### ISSUE TITLE
Move service hub code over to StreamJsonRpc v2.0

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#33860]
This would help derived unit testing services (live unit testing, source based discovery) to consume StreamJsonRpc v2.0.

**Comment by shyamnamboodiripad** [comment]
cc @heejaechang

**Comment by heejaechang** [comment]
https://github.com/dotnet/roslyn/pull/33960

**Comment by jinujoseph** [comment]
@heejaechang good to close this ?

**Comment by heejaechang** [comment]
done.
