### ISSUE TITLE
Convert "sync namespace" refactoring to an analzer/codefix combo

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#33877]
We have heard feedback both internally and externally about the need to flag out-of-sync namespace and folder hierarchy.

One thing we need to figure out, is how do we let users indicate which projects need to be enforced. Using .editorconfig? Also, do we still keep providing this as a refactoring if there's no indication from user that they want it flagged as diagnostics?

**Comment by felixhirt** [comment]
I like the editorconfig approach. Maybe just make it another visual studio code style setting and make it overwritable with an editorconfig file like the others. I think it is fine if the refactoring is still available with disabled diagnostic. It seems to me there are a lot of refactorings available allready without explicitly enabling them

**Comment by ptasev** [comment]
My team wants to disable the syncing of namespace with folder name and simply use only the `RootNamespace` from the project. Is it possible currently to disable this feature through editorconfig?

Just to be clear, when I add a new C# class in VS by right-clicking a folder, and then going through the dialogs to add, the namespace of the new file becomes `RootNamespace.FolderName`. We want to disable this feature.

If this is not currently possible, is this ask capture by this issue?

**Comment by genlu** [comment]
@ptasev Currently there's no editorconfig rule for sync namespace, and as far as I know, there's no option to change the default namespace when adding a new source file (@jasonmalinowski are you aware of such an option?). 

FYI, we are currently working on this issue, and the editorconfig support will be added as part of that. I believe this is the current plan.
- Always sync namespace to [rootnamespace].[CurrentFolder]. Then when adding new source file, namespace will be [rootnamespace].[CurrentFolder].
- Don't sync namespace. Then when adding new source file, namespace will be [rootnamespace].[CurrentFolder].

It sounds like you are asking for a third option. Is that correct?
- Always sync namespace to [rootnamespace]. Then when adding new source file, namespace will be [rootnamespace].

I think this suggestion makes sense, thoughts @mikadumont?

**Comment by mikadumont** [comment]
Yes, this option sounds good. We will need to do work to apply code cleanup when creating new files for this to work - similar to the work that was done here: https://github.com/dotnet/roslyn/pull/46744

@vritant24 who is currently working on this analyzer for awareness.

**Comment by jasonmalinowski** [comment]
There's no option to disable the .Folder suffixing when you create a new file today. It makes total sense to me to have an .editorconfig to say whether you want files to include the folder or just match the root namespace, and we would just have New File follow that .editorconfig rule. And then the sync feature we can treat as a diagnostic + fix for things that don't line up.

**Comment by ptasev** [comment]
I guess I'm confused about the difference between syncing the namespace and generating the namespace when adding a new file, but I think you understood the ask which is to ignore the folder and use `RootNamespace` only. (the third option mentioned by genlu)

**Comment by logiclrd** [comment]
Apologies in advance, this comment is unrelated to this issue, but my own contribution has ended up tied to it by an action taken as a result of a false-positive somewhere within the system. I submitted a feature request for something _completely different_, and it just got closed as a duplicate of this issue:

https://developercommunity.visualstudio.com/content/idea/1185590/user-defined-root-namespaces-for-separate-import-d.html

Does anybody getting this notification know how to reverse this? I'm hoping that somebody "within the system" is able to find someone in charge of how my issue got tagged as a duplicate of this one.

**Comment by genlu** [comment]
@logiclrd Your suggestion is moved to https://github.com/dotnet/roslyn/issues/47802

**Comment by logiclrd** [comment]
Thanks very much :-) Sorry for the noise!

**Comment by genlu** [comment]
Implemented in #49990. The unimplemented part is tracked by #50686
