### ISSUE TITLE
On private readonly field VS2019 Preview 4 suggest wrong style

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33873]
VSF_TYPE_MARKDOWN
```
public class ProvisioningTests
    {
        private readonly IChatConnector _connector = ThirdPartyIntegrationTestFixture.ServiceCollection.GetRequiredService&lt;IChatConnector&gt;();
        
```

In the above code, VS2019 Preview 4 suggest to rename _connector to Connector with IDE1006 warning.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/474640/on-private-readonly-field-vs2019-preview-4-suggest.html
VSTS ticketId: 806713_
_These are the original issue comments:_

Visual Studio Feedback System on 3/3/2019, 11:46 PM (37 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 3/5/2019, 01:50 AM (11 hours ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by peterdeme** [comment]
Please note, even when explicitly setting it in the IDE settings, it still throws the error:

![image](https://user-images.githubusercontent.com/19969687/55562440-343e0700-56f4-11e9-87eb-5fda567e24d3.png)

**Comment by sharwell** [comment]
This needs investigation to understand the specific steps to reproduce and find the root cause before we can determine a direction for it. At first it looked related to #34210, but that issue was resolved for the final 2019 release.

@peterdeme Is there a **.editorconfig** file in the directory with your source file, or in any parent directory of it?

**Comment by peterdeme** [comment]
@sharwell Apparently it works now. Not sure which VS update fixed it, though. Anyway, this and https://developercommunity.visualstudio.com/content/problem/474640/on-private-readonly-field-vs2019-preview-4-suggest.html both can be closed I believe.

**Comment by sharwell** [comment]
@peterdeme Happy to hear it's working, thanks for letting us know!
