### ISSUE TITLE
NullReferenceException in TryGetImageListAndIndex When Attempting to Apply Changes

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#33884]
Attempting to use the public api analyzer and apply changes to changed APIs when I encountered a null reference exception. Dump file can be found here: `"\\mlangfs1\public\frsilb\dumps\33884\devenv.dmp"`

Edit: I think I just found a consistent repro. Open the `PublicAPI.Unshipped.txt` file and attempt to invoke the update api file refactoring. Appears to crash every time. Does not crash when the document is closed.

**Comment by ivanbasov** [comment]
I reviewed Watson and could not find related issues so far.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of prism hits.
