### ISSUE TITLE
How to build Roslyn with Visual Studio?

### ISSUE THREAD

**Issue by qwertie** [dotnet/roslyn#3388]
It's not clear how one is expected to ask questions on GitHub so I'm doing it with an issue. I noticed that the FAQ doesn't say a lot about how to build Roslyn, but it doesn't build easily. I'd like to see more about building Roslyn in the FAQ. Anyway, here is my experience with trying to building Roslyn:

At first I tried the `Releases/VS2015RC` branch, but encountered way too many errors, and decided to try `master` instead.

I installed VS 2015 RC and when I open RoslynLight.sln in it, I am informed that the following projects are unsupported (the "More information" link in Visual Studio does not tell me why):

- AnalyzerPowerPack
- CodeAnalysisDiagnosticsSetup
- OpenSourceDebug

It loads "125" projects in a progress bar, but then solution explorer says there are only 99. When I build, it starts by "Restoring Nuget Packages", which I guess downloads some stuff, but then there are 94 errors that all say 

> This project requires the Microsoft.Net.ToolsetCompilers NuGet package to build. Use NuGet Package Restore to download the required files ("powershell .nuget\NuGetRestore.ps1"). The missing file is "D:\Dev\Roslyn\src\Tools\Microsoft.CodeAnalysis.Toolset.Open\Targets\..\..\..\..\packages\Microsoft.Net.ToolsetCompilers.1.0.0-rc3-20150510-01\build\Microsoft.Net.ToolsetCompilers.props"

Attempting to run .nuget\NuGetRestore.ps1 on the command line gives a series of errors:

    D:\Dev\Roslyn\src\.nuget>powershell .\nugetrestore.ps1
    The term '\NuGet.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    ...

I fixed this by editing the script, defining `$PSScriptRoot` on the first line of the file:

    $PSScriptRoot = "D:\Dev\Roslyn\src\.nuget"

Then powershell should be able to run the script successfully. After that, the build result is "86 succeeded, 8 failed". The 8 errors are:

- Error		could not find library 'D:\Dev\Roslyn\Binaries\Debug\Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.ExpressionCompiler.dll'	BasicExpressionCompilerTest	D:\Dev\Roslyn\src\ExpressionEvaluator\VisualBasic\Test\ExpressionCompiler\vbc	
- Error		The command ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VSSDK\VisualStudioIntegration\Tools\Bin\vsdconfigtool.exe" D:\Dev\Roslyn\src\ExpressionEvaluator\VisualBasic\Source\ResultProvider\VisualBasicResultProvider.vsdconfigxml obj\Debug\\Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.ResultProvider.dll "D:\Dev\Roslyn\Binaries\Debug\NetFX20\\Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.ResultProvider.vsdconfig"" exited with code 3.	BasicResultProvider.NetFX20		
- Error		The command ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VSSDK\VisualStudioIntegration\Tools\Bin\vsdconfigtool.exe" D:\Dev\Roslyn\src\ExpressionEvaluator\VisualBasic\Source\ResultProvider\VisualBasicResultProvider.vsdconfigxml obj\Debug\\Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.ResultProvider.dll "D:\Dev\Roslyn\Binaries\Debug\\Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.ResultProvider.vsdconfig"" exited with code 3.	BasicResultProvider.Portable		
- Error		The command ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VSSDK\VisualStudioIntegration\Tools\Bin\vsdconfigtool.exe" CSharpExpressionCompiler.vsdconfigxml obj\Debug\\Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExpressionCompiler.dll "D:\Dev\Roslyn\Binaries\Debug\\Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExpressionCompiler.vsdconfig"" exited with code 3.	CSharpExpressionCompiler		
- Error		Metadata file 'D:\Dev\Roslyn\Binaries\Debug\Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExpressionCompiler.dll' could not be found	CSharpExpressionCompilerTest	D:\Dev\Roslyn\src\ExpressionEvaluator\CSharp\Test\ExpressionCompiler\CSC	
- Error		The command ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VSSDK\VisualStudioIntegration\Tools\Bin\vsdconfigtool.exe" D:\Dev\Roslyn\src\ExpressionEvaluator\CSharp\Source\ResultProvider\CSharpResultProvider.vsdconfigxml obj\Debug\\Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ResultProvider.dll "D:\Dev\Roslyn\Binaries\Debug\NetFX20\\Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ResultProvider.vsdconfig"" exited with code 3.	CSharpResultProvider.NetFX20		
- Error		The command ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VSSDK\VisualStudioIntegration\Tools\Bin\vsdconfigtool.exe" D:\Dev\Roslyn\src\ExpressionEvaluator\CSharp\Source\ResultProvider\CSharpResultProvider.vsdconfigxml obj\Debug\\Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ResultProvider.dll "D:\Dev\Roslyn\Binaries\Debug\\Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ResultProvider.vsdconfig"" exited with code 3.	CSharpResultProvider.Portable		
- Error		The command ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VSSDK\VisualStudioIntegration\Tools\Bin\vsdconfigtool.exe" BasicExpressionCompiler.vsdconfigxml obj\Debug\\Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.ExpressionCompiler.dll "D:\Dev\Roslyn\Binaries\Debug\\Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.ExpressionCompiler.vsdconfig"" exited with code 3.	BasicExpressionCompiler		

Many of the errors are preceded in the Output window by "The system cannot find the path specified." Which path? It doesn't say.

One difficulty for newbies is that we don't know whether any of the failing projects are important (and I, for one, don't know what a "vsd" is, or why its "vsdconfigtool" is failing.

So next I thought, "let's see if I can get the samples to run". When I open `src\Samples\Samples.sln` I am told that these 7 projects are unsupported, with no hint about _why_ (a common irritation when using VS with projects from the internet):

- ConvertToAutoPropertyCS
- ImplementNotifyPropertyChangedCS
- MakeConstCS
- ConvertToAutoPropertyVB
- ImplementNotifyPropertyChangedVB
- MakeConstVB
- AsyncPackage

On opening the solution, 69 errors appear before building. On building, 7 succeed and 6 fail. The error is always the same:

> D:\Dev\Roslyn\src\Tools\Microsoft.CodeAnalysis.Toolset.Open\Targets\VSL.Imports.targets(162,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\VSSDK\Microsoft.VsSDK.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Hmm, looks like I should install a Visual Studio SDK of some kind. Perhaps [this one](https://www.microsoft.com/en-us/download/details.aspx?id=46850)? However, trying to install Visual Studio 2015 RC SDK fails with this message:

    Setup Engine
    The system cannot find the path specified.

Oh well.

**Comment by jmarolf** [comment]
We definitely need to get better instructions about how to build and test roslyn.  For now, the main thing that is blowing up is you don't have the VS SDK installed.  Building and debugging roslyn is going to be hard without the VSSDK as many projects are extensions on visual studio (so you can debug visual studio with visual studio to test your changes).  We'll need to look into why the SDK is failing to install.  Which version of 2015 do you have installed?

Another interesting bug is the powershell script not working.  If you can't get the references needed to build (including the bootstrap compiler) very little is going to work.  Nuget.exe should be right next to NugetRestore.ps1, is this not the case on your enlistment?

**Comment by qwertie** [comment]
My VS version is "RC": 14.0.22823.1 D14REL, (.NET 4.6.00057)
I installed it a couple of days ago and I downloaded the VS SDK last night.
NuGet.exe is present. The script doesn't work because $PSScriptRoot is undefined or empty; so $PSScriptRoot\NuGet.exe expands to \NuGet.exe. Which branch of Roslyn should people be trying to build?

**Comment by qwertie** [comment]
By the way, the samples ConsoleClassifierVB and ConsoleClassifierCS build to the same exe file. Imagine my surprise when I stepped into ConsoleClassifierCS and it started in "Program.vb"!

**Comment by jmarolf** [comment]
> My VS version is "RC": 14.0.22823.1 D14REL, (.NET 4.6.00057) I installed it a couple of days ago and I downloaded the VS SDK last night.

So I assume once you installed the SDK most of the errors went away?

> The script doesn't work because $PSScriptRoot is undefined or empty; so $PSScriptRoot\NuGet.exe expands to \NuGet.exe.

Were you running this script from the commandline or the Package Management Console?

> Which branch of Roslyn should people be trying to build?

[VS2015RC](https://github.com/dotnet/roslyn/tree/releases/VS2015RC) is the build you should be working with if you have RC installed.

> the samples ConsoleClassifierVB and ConsoleClassifierCS build to the same exe file. 

That's no good. We should fix it.

**Comment by jmarolf** [comment]
One more question:  Did you install Community, Professional or Enterprise?

**Comment by qwertie** [comment]
Hey, sorry about my slowness to respond. As I mentioned, I was not able to install the SDK, but I decided to try again and—hey!—it worked the second time. There was a Windows Update Reboot With Automatic Loss Of Unsaved Work (or Wurwalouw for short) in between the two attempts, maybe that did something... 

Good question, I installed Community, since I got the impression that it supports VS extensions, and I don't work for a 'MS shop'.

VS now loads the three projects in RoslynLight that it wouldn't before:

- Diagnostics | FxCop | AnalyzerPowerPack.Setup
- Diagnostics | CodeAnalysis | CodeAnalysisDiagnosticsSetup
- Tools | OpenSourceDebug

And VS was able to build everything!
Likewise all 20 sample projects load, and all of them build!

So next I tried to build Roslyn.sln, but 28 of 136 projects failed to build there. So I tried checking out the releases/VS2015RC branch again, and tried to build the full Roslyn.sln there—which, in hindsight, was a mistake. After editing `src\.nuget\NuGetRestore.ps1` as before and running it, VS2015 took nearly two hours to build Roslyn.sln, with a peak 'Commit Size' of 3GB (my laptop has 4GB). Only 90 projects built successfully; 41 failed, producing 11,826 errors. So... I guess I'll stick with Roslyn Light, which needed only about 1GB to build.

**Comment by qwertie** [comment]
Oh, in answer to your other question, IIRC, running that script from 'Package Management Console' produced the same error as running from cmd.exe.

**Comment by jmarolf** [comment]
@qwertie Thanks! Would you be willing to file a bug about the powershell script not working?  Unfortunately Roslyn.sln in the main and stabilization branches is already dependent on components newer than RC, but RoslynLight.sln should always build.  Roslyn,sln from releases/VS2015RC should build with RC.  Would it be possible for you to paste your build output?

**Comment by davkean** [comment]
@qwertie I recently updated the building, testing and debugging section over here: https://github.com/dotnet/roslyn/wiki/Building-Testing-and-Debugging, with explicit instructions around what you need to do to build and test Roslyn. Also, once VS Update 1 releases, we have a very easy way of testing your changes inside Visual Studio, without breaking your current install.

**Comment by qwertie** [comment]
@jmarolf sorry for not doing that, I moved on to other work.

@davkean Thanks. So `master` requires VS "15" to build? The [instructions themselves](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md) still say "VS 2015 Update 3". 

If all I have is VS 2015, I should be able to build the `microupdate` branch, right? However, oddly I cannot find that branch in git:

~~~
C:\Dev\Roslyn>git fetch

C:\Dev\Roslyn>git branch --all
* master
  remotes/origin/EventEnC
  remotes/origin/HEAD -> origin/master
  remotes/origin/core-clr
  remotes/origin/features/local-functions
  remotes/origin/future
  remotes/origin/master
  remotes/origin/portable-pdb
  remotes/origin/preview
  remotes/origin/releases/Dev14CTP5
  remotes/origin/releases/Dev14CTP6
  remotes/origin/releases/Dev14Preview
  remotes/origin/releases/VS2015RC
  remotes/origin/stabilization
~~~ 

Any idea how it is hiding from me?

**Comment by jnm2** [comment]
I would like updated VS2017 instructions as well. Struggled last night. `version-1.3.2` built fine via `cibuild.cmd`, but VS crashes when I open the solution.

**Comment by qwertie** [comment]
@devkean The instructions say "Run Restore.cmd in the command prompt to restore NuGet packages." but there is no such file in master.

Also fun, VS "15" still shows the same error about "ToolsetCompilers" from 18 months ago and NuGetRestore.ps1 is still broken (guess I should have filed that issue). VS "15" Preview 4 doesn't support Roslyn.sln? Oops, that's what I just installed.

**Comment by svick** [comment]
@qwertie [There is.](https://github.com/dotnet/roslyn/blob/master/Restore.cmd) I think you're using [your very old fork](https://github.com/qwertie/roslyn), it's consistent with the list of branches you showed.

**Comment by qwertie** [comment]
OMG @svick, I am humbled that you correctly diagnosed my inflamed moronal lobe! Thank you!
