### ISSUE TITLE
Async Completion: autocomplete for `override` sometimes missing an newline

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#33894]
**Version Used**: VS2019 Preview4/4.1

**Steps to Reproduce**:

1. switch `Async Completion` on
2. Type the below code(without comment)
```cs
        public class XXX
        {
            public override bool Equals(object obj)
            {
                return base.Equals(obj);
            }
        }
```
2. Add an new line after `Equals`, and type the below code(without comment), wait 1sec and press Enter to autocomplete GetHashCode()
```
            override G/*press Enter here to get GetHashCode()*/
```
3. See an new line is missing

NOTE: It sometimes may not reproduceable when press Ctrl+Z or just delete `GetHashCode()`  and repeat step 3, maybe remove all methods works.

**Expected Behavior**:
```cs
        public class XXX
        {
            public override bool Equals(object obj)
            {
                return base.Equals(obj);
            }
            public override int GetHashCode()
            {
                return base.GetHashCode();
            }
        }
```

**Actual Behavior**:
```cs
        public class XXX
        {
            public override bool Equals(object obj)
            {
                return base.Equals(obj);
            }
            public override int GetHashCode()
            {
                return base.GetHashCode();
            }        }
```

**Comment by sharwell** [comment]
@ivanbasov Is this covered by #33626 or #33825?

**Comment by ivanbasov** [comment]
The issue is fixed. I have verified it with 16.0 RC2.
![override](https://user-images.githubusercontent.com/5455484/54316806-d14acb80-459e-11e9-9cf9-3d547996de49.gif)
