### ISSUE TITLE
Support more fine grained behavior for Taggers

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#3389]
Right now Roslyn gets all the tags for a file in one fell-swoop.  This is generally sufficient for VB/C# as these compilers are free-threaded and can still respond to requests on other threads while computing the tag information.  Unfortunately for TypeScript, due to our compiler being written in JS, we are inherently single threaded.  

Because of this, tagging comes at a high cost for us because it effectively blocks us from performing any other LS tasks on that thread while computing tagging results.

The biggest examples of where we run into this is Classification.  The Roslyn side asks us for the Tags(/classifications) for the entire file at once.  For large file files this can definitely be a noticeable issue as other features (like completion) will only run once classification is over.

Ideally, we could have View-Taggers which were a bit smart about how they executed.  Instead of tagging the entire buffer at once, they could tag the buffer in 'chunks' (prioritizing the chunk in view most of the time).  

For most users in VS, there would be no change in behavior (except that things would get more responsive). For users using things like the smart scroll-bar gutter, they might observe that the classifications began with what was in view, and then expanded outwards from that point to the rest of the file.  However, this behavior does not seem like it would actually be bad.  Users would sensibly understand "oh, they're just calculating what the program means from this point on outwards."

Thanks!

**Comment by sharwell** [comment]
Can you point out the method which is called with "too large" a request?

If the Roslyn/Visual Studio interaction components are asking for the entire set of tags for a file after every change, my guess is the implementation was based on the fact that the C# and VB compilers support incremental lexing and theoretically share most of the tag information between versions of a document. Of course this is complete speculation, but I'm interested to know more. :smile:

**Comment by CyrusNajmabadi** [comment]
@sharwell 
> Can you point out the method which is called with "too large" a request?

```C#
Task<IEnumerable<ITagSpan<TTag>>> ITagProducer<TTag>.ProduceTagsAsync(IEnumerable<DocumentSnapshotSpan> snapshotSpans, SnapshotPoint? caretPosition, CancellationToken cancellationToken)
```

While this method is nice in that it *could* be called on a subrange of a document; in practice the snapshot span will encompass the entire document.

Rgd incremental lexing:  TypeScript support incremental parsing and semantics using a very similar model to Roslyn's C#/VB approach.  The primary difference that exacerbates the situation here is that the C#/VB language services and compilers are effectively free threaded, whereas the TypeScript compiler is not.  So while the C# LS is computing tags on some thread, it can also be computing the information for completion lists on another thread.  This is not possible with TypeScript.  Because our compiler executes *within* a JS engine, we are effectively limited to executing one request at a time, with no simultaneous concurrency.  As such, if any single request is too expensive, it can have a significant impact on other important requests we want to get done.

If Roslyn could break up tagging requests for a a buffer (associated with a view) into smaller chunks, then that would alleviate the burden on the TypeScript side by having it only have smaller pieces of work to do.  This would allow us to then run a more important piece of work once that small piece of work was done.  The big difference would be that instead of having to wait a large amount of time before we could execute the important work, we'd only have to wait a small amount of time.

**Comment by sharwell** [comment]
This looks remarkably similar to the situation I faced with the NetBeans editor. There are several possible ways to implement a method with that signature. One of them is to asynchronously compute all the tag spans and place them in a `IList<ITagSpan<TTag>>`, and then return the whole list in the completed task. Another way to implement it is to asynchronously create a state machine which implements `IEnumerable<ITagSpan<TTag>>` (but does not actually precompute any tags), and then return that state machine as the completed task. In NetBeans, it turned out that the editor didn't actually iterate over the entire sequence returned, so the use of a lazily-computed sequence was enough to address the performance concerns.

Depending on the manner in which the TypeScript tools synchronize threads for interaction with the TS compiler, the finer granularity of an iterator may address the concurrent operations issue as well.

**Comment by CyrusNajmabadi** [comment]
@sharwell  We cannot use an IEnumerable/IEnumerator because of the non-free-threaded-compiler issue.  If we return an IEnumerable/IEnumerator, and that is enumerated on another thread (which, indeed, is how Roslyn works), then that will cause us to try to call into our compiler on an inappropriate thread.  This will not work due to the threading constraints of the JavaScript engine that our compiler actually runs within.

Furthermore, Roslyn does not lazily pull on the IEnumerable.  It pulls all the tags from it, and it updates its internal balanced tree of tags.  As such, trying to be lazy doesn't even help as you'll be forced to compute all the values up front.

The problem, as mentioned above, is that we have two conflicting requirements. The first is that Roslyn requires getting all the tags for a document at once (regardless of what is actually in view or not).  The second is that TypeScript can only execute one job at a time on our background thread.  Effectively meaning that any additional work we need to do has to wait until the current task is finished.   These two designs are in conflict with each other.  We'd def like to address this on the TypeScript side.  Unfortunately, we are at the mercy of these limitations of JS engines.  As that is a pretty difficult (or practically impossible) constraint to work around, the best fix seems to be at the Roslyn layer, where it could change how it does Tagging.

IMO this would also be nice for a whole host of other reasons.  Frankly, it's still good, even in a free threaded environment, to have less work be done.  If Roslyn could change its taggers to only tag what was visible (and maybe a small region around that), that would cut down on CPU/Garbage, etc.  

Note: if we were worried about this not being appropriate for all taggers, we could make it a tagger-knob so you would have to opt in/out of this behavior.

**Comment by Pilchie** [comment]
@CyrusNajmabadi You may not recall, but a LONG time ago in Roslyn we did only tag what was visible, and in many cases determining what was visible was more expensive than just tagging the whole file.

**Comment by CyrusNajmabadi** [comment]
@Pilchie I did *not* recall that.  It's somewhat surprising though.  What makes determining what's visible so expensive? Thanks!

@jasonmalinowski Do you recall what the issue was?

**Comment by jasonmalinowski** [comment]
I don't remember anything more than what @Pilchie has already said. (This statement applies globally, not just here.)

**Comment by CyrusNajmabadi** [comment]
Fixed with: https://github.com/dotnet/roslyn/pull/4046
