### ISSUE TITLE
There should be no "Possible dereference of a null reference" warnings for expression tree lambdas

### ISSUE THREAD

**Issue by abartho** [dotnet/roslyn#33923]
When calling a method which expects an expression tree (Expression<Func<T, TProperty>> parameter), and one of the properties in the expression tree is nullable, the compiler produces a nullable reference warning that cannot be worked around.

The following example code is based on a validation framework and simplified:
```csharp
using System;
using System.Linq.Expressions;

namespace CSharp8Test
{
    class Program
    {
        static void Main(string[] args)
        {
            var ep = new ExpressionProcessor<Outer>();
            ep.ProcessExpression(o => o.Inner.S); //"Possible dereference of a null reference" warning
        }

        class ExpressionProcessor<T> 
        {
            public void ProcessExpression<TProperty>(Expression<Func<T, TProperty>> expression)
            {
            }
        }

        public class Outer
        {
            public Inner? Inner { get; set; }
        }

        public class Inner 
        {
            public string S { get; set; } = "";
        }
    }
}
```
For 
`ep.ProcessExpression(o => o.Inner.S);`
I get a warning saying "Possible dereference of a null reference" because o.Inner might be null.
However, when working with Expressions I'm not dereferencing the object members, and I think the warning makes no sense here.

Using a null propagating operator like this: `ep.ProcessExpression(o => o.Inner?.S);` is not supported by the compiler.

**Version Used**: 
.NET Core 3.0.0-preview3-27503-5

**Expected Behavior**:
No warnings for expression tree lambda expressions (my preference)
OR
Support for null propagating operator in expression tree lambda expressions

**Actual Behavior**:
"Possible dereference of a null reference" warning

**Comment by YairHalberstadt** [comment]
A similar bug is #33573.
Perhaps there should be a generalised approach to warnings on expression trees?

**Comment by gafter** [comment]
I believe this is by design.

**Comment by gafter** [comment]
This is by design.  Whether a lambda is an expression tree or converted to a delegate, the compiler has no way to know if you intend to execute it or not.

**Comment by abartho** [comment]
I see. But be aware that nullable references would not play nicely with popular tools such as FluentAssertions or FluentValidation.
