### ISSUE TITLE
Remove BoundExpressionExtensions.GetTypeAndNullability and GetNullableAnnotation

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#33941]
Remove `BoundExpressionExtensions.GetTypeAndNullability` and `BoundExpressionExtensions.GetNullableAnnotation`.

The methods are only used for setting the nullability of inferred locals in initial binding, but initial binding should not infer nullability.

**Comment by jcouv** [comment]
Closing as duplicate of https://github.com/dotnet/roslyn/issues/33925
