### ISSUE TITLE
Please reorder NullableAnnotation values to be in lattice order

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#33952]
The values of NullableAnnotation are not in the order that they appear in the lattice.  Please reorder them so that they are in lattice order; that would permit a much simpler implementation of Meet and Join.

**Comment by cston** [comment]
The `NullableAnnotation` enum values are currently used as is in `[NullableAttribute(values)]` attributes in metadata, so changing the enum will be a breaking change unless we map to/from the current values when writing/reading metadata.
