### ISSUE TITLE
'Generate constructor' should not add null checks for nullable parameters.

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#33963]
**Version Used**: Visual Studio 2019 RC.1 SVC 1

'Generate constructor' with 'Add null checks' currently generates parameters which are pointlessly nullable, since the constructor throws if `null` is actually passed:

```cs
class C
{
    public C(string foo, int? bar)
    {
        Foo = foo ?? throw new ArgumentNullException(nameof(foo));
        Bar = bar ?? throw new ArgumentNullException(nameof(bar));
    }

    public string Foo { get; }
    public int? Bar { get; }
}
```

I'd expect nullable parameters to be passed over. I don't know what happens when you nullable reference types at it, but right now I really care about the experience with nullable value types.

**Comment by YairHalberstadt** [comment]
I'm happy to give this a go.

**Comment by CyrusNajmabadi** [comment]
Sorry @YairHalberstadt .  I didn't see your comment.  I've opened up a fix for this myself.

**Comment by YairHalberstadt** [comment]
@cyrusNajmabadi
No problem. I haven't even started yet.
