### ISSUE TITLE
Xunit sometimes crashes with Win32Exception: Invalid window handle

### ISSUE THREAD

**Issue by khyperia** [dotnet/roslyn#3396]
The test that failed was `Roslyn.InteractiveWindow.UnitTests.dll`

```
  System.ComponentModel.Win32Exception (0x80004005): Invalid window handle
     at MS.Win32.ManagedWndProcTracker.HookUpDefWindowProc(IntPtr hwnd)
     at MS.Win32.ManagedWndProcTracker.OnAppDomainProcessExit()
     at MS.Win32.ManagedWndProcTracker.ManagedWndProcTrackerShutDownListener.OnShutDown(Object target, Object sender, EventArgs e)
     at MS.Internal.ShutDownListener.HandleShutDown(Object sender, EventArgs e)
```

Pinging @jaredpar for thoughts on what we figured out - could be related to app domain shutdown racing with finalizers is what I think we said?

Not sure if it happens on only that single test or others, and how frequently it happens - if anyone has encountered the same or similar thing, more data points might be helpful. (Previously a crash like this was reported as `System.String[]` in the output, but #3307 prints it correctly)

**Comment by davkean** [comment]
Been watching failures pretty closely for the past two months, we've never hit this so I'm going to mark this as no-repro for the moment. Feel free to comment, reopen or open a new bug if we hit this again.

**Comment by masterprogrammer513** [comment]
It's the same as this one, We have the same problem
[https://github.com/dotnet/wpf/issues/7536](https://github.com/dotnet/wpf/issues/7536)
