### ISSUE TITLE
Compilation error "csc.dll" exited with code 139 on ARMv7l

### ISSUE THREAD

**Issue by livarcocc** [dotnet/roslyn#33975]
@NicolasDorier commented on [Thu Mar 07 2019](https://github.com/dotnet/cli/issues/10950)

## Steps to reproduce

On
```
uname -a
Linux odroid 4.14.5-92 #1 SMP PREEMPT Mon Dec 11 15:48:15 UTC 2017 armv7l armv7l armv7l GNU/Linux
```

```
git clone https://github.com/btcpayserver/btcpayserver
cd btcpayserver/btcpayserver
dotnet build -c Release
```

## Expected  behavior

Build succeed.

## Actual behavior

User reported compilation error "csc.dll" exited with code 134 on ARM.
The msbuild seems show error 139 from csc.dll.

## Environment data

@enorrmann can you provide precise `dotnet --version` here?

He tried with SDK `2.1.504` and `2.2.104` with same error it seems.

![image](https://user-images.githubusercontent.com/3020646/54002883-7dea0f00-4193-11e9-88bd-03c161406535.png)

[msbuild.binlog](https://www.dropbox.com/s/4ic7z1j7qnh72iv/msbuild.binlog?dl=1)

Orignally reported on https://github.com/btcpayserver/btcpayserver/issues/600

It seems same issue as https://github.com/dotnet/roslyn/issues/28038 . I opened a new issue because this one happen on ARM32v7.

**Comment by gafter** [comment]
I followed the "Steps to reproduce" and it did not reproduce.

**Comment by codeandcloud** [comment]
FYI,

I had the same error at 

.NET Core WebApi - 3.1.106
Fedora -32 

Issue was that I was using EntityFramework core and have not installed `dotnet-ef`. 

Got the issue resolved by running,

    dotnet tool install --global dotnet-ef
