### ISSUE TITLE
Summary of Possible Change Signature Enhancements

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#33977]
Work in progress attempt at organizing possible Change Signature enhancements.

- Parameter list
    - Individual Parameters
        - Edit Parameter
            - Type**: #40599 
            - Modifiers*
            - Name* (lower priority)
            - Optional status*
            - `params` status*
- Invocation style
    - Add in-editor Change Signature Tracking (think Rename Tracking but for changes to a method's signature).
- Sets of Parameters
    - Decompose Parameter
    - Combine Parameters
- The method itself
    - Change return type**
        - Move return value to out parameter: https://github.com/dotnet/roslyn/issues/25582
    - Change modifiers: #25094
    - Rename method* (lower priority)

`*` denotes having been discussed by the design team: https://github.com/dotnet/roslyn/issues/25144#issuecomment-467472419
`**` denotes having been discussed as needing more design: https://github.com/dotnet/roslyn/issues/25144#issuecomment-467472419

More Links:
https://github.com/dotnet/roslyn/issues/4510
https://github.com/dotnet/roslyn/issues/21446

**Comment by ryzngard** [comment]
Change Signature could also start to incorporate new nullable attributes. Allow adding/removing them to appropriate parameters.

**Comment by anthonypcole** [comment]
One part of the feature request says "Move return value to out parameter"

However I suggest adding the opposite as well, 
Functionality to make **out parameters changeable to be return values**.

With tuple return values, any number of parameters could be moved to be part of the return value as well if there already is one,
however most of the time i normally just have the one

This happens all the time when refactoring code into a method, where the refactorer makes variables out-parameters but I have some that make more sense to be a return values

**Comment by CyrusNajmabadi** [comment]
@anthonypcole we would definitely take such a if you wanted to contribute it!

**Comment by CyrusNajmabadi** [comment]
Closing out as much of this has been done.
