### ISSUE TITLE
IDE0060 when the parameter is needed due to conditional compilation

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#33999]
**Version Used**: VS2019 RC.1 SVC1

Can Roslyn do anything to help this situation, maybe bail if it detects that the method declaration is conditional?

```cs
public static class FeatureToggle
{
    public static bool Foo { get; } = IsFeatureEnabled(nameof(Foo));
    public static bool Bar { get; } = IsFeatureEnabled(nameof(Bar));
    // ...

#if DEBUG
    // IDE0060 Remove unused parameter
    private static bool IsFeatureEnabled(string featureId) => true;
#else
    private static string[] enabledFeatureIds;

    private static bool IsFeatureEnabled(string featureId)
    {
        if (enabledFeatureIds == null)
        {
            enabledFeatureIds = (string[])ConfigurationManager.GetSection("features") ?? Array.Empty<string>();
        }

        return enabledFeatureIds.Contains(featureId, StringComparer.OrdinalIgnoreCase);
    }
#endif
}
```

**Comment by sharwell** [comment]
Tentatively marking this one as **won't fix**, but will confirm in design review later today. Suppressing the warning with a `#pragma` would be one possible recommended resolution; the code already demonstrates that the limited use of preprocessor directives is acceptable in the scenario.

**Comment by sharwell** [comment]
The design review team agreed with the resolution proposed in https://github.com/dotnet/roslyn/issues/33999#issuecomment-471538749.
