### ISSUE TITLE
Allow empty tuples

### ISSUE THREAD

**Issue by Pzixel** [dotnet/roslyn#33998]
In current C# version if you try to create an empty tuple you will get "Tuple must contain at least two elements" error. But it's useful, especially when you are working with generic type `T` and don't care about result. For example, we want to create `TaskCompletionSource`, but we don't care about its result, we only care when it's ran to execution. So `var tcs = new TaskCompletionSource<()>();` could fit ideally, except C# compiler doesn't allow it.

#### Existing workarounds:

Use some small type and ignore it, e.g. `var tcs = new TaskCompletionSource<bool>();`

Pros: already exist in the language
Cons: is not really ideomatic, introduce usable variable that actually has no sense.

**Comment by YairHalberstadt** [comment]
This is a request to create a new language feature, and should be opened on the csharplang repo.

This issue looks similar: https://github.com/dotnet/csharplang/issues/883

**Comment by Pzixel** [comment]
Right, sorry. Have a nice day!

**Comment by YairHalberstadt** [comment]
No problem :-)

**Comment by CyrusNajmabadi** [comment]
You can just use `ValueTuple` directly.  The language simply lacks shorthand syntax for this.  BUt nothing is stopping you from referencing the full type name explicitly.  Since you don't need names for the members, this is equivalent.

**Comment by YairHalberstadt** [comment]
You could also define your own Void type
```csharp
public struct Void {}
```
