### ISSUE TITLE
AnalyzerDriver<T>.Dispose is broken

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#34]
http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerDriver.cs,951

This should override the base method, not shadow it.  (preferably using the standard dispose pattern)
@amcasey points out that it should also skip the loop entirely if `lazyNodeActionsByKind` has not been initialized.

Also, is that property getter supposed to be thread-safe?
If called on multiple threads, you will leak the pool.
Why not use `Lazy<T>`?
Are you trying that hard to save allocations?

**Comment by srivatsn** [comment]
Fixed in 051ee8b
