### ISSUE TITLE
Ahead code execution error during debug

### ISSUE THREAD

**Issue by mcmikecreations** [dotnet/roslyn#34019]
**Version Used**: VS Enterprise 2017 with March 2019 update

**Steps to Reproduce**:
This is hard to explain. Here's the video with my steps: [Youtube](https://youtu.be/oEkkzwy3hX4)
1. I enabled a bunch of debug breakpoints. Further down in the code I have a function that sets the "registers" to "Taken" one by one.
2. I jump one step (command) at a time or more, each time the code ahead is for some reason executed, taking the "register".
3. When I disable the breakpoints, everything works fine.

**Expected Behavior**:
I am able to debug my code without any issues.
**Actual Behavior**:
The debugger executes code ahead, ruining my program.

**Comment by PathogenDavid** [comment]
You should try disabling the "Enable property evaluation and other implicit function calls" option in Tools > Options > Debugging > General.

**Comment by mcmikecreations** [comment]
> 
> 
> You should try disabling the "Enable property evaluation and other implicit function calls" option in Tools > Options > Debugging > General.

Thank you very much, that actually solved the issue. I would have never guessed that it was the reason! Also for any future viewers: don't forget to disable "Call string-conversion function on  objects in variables windows" if you do some complicated ToString conversions!

**Comment by PathogenDavid** [comment]
No problem, glad it helped!

It is worth noting that you're disabling a pretty useful feature of the debugger. If you're having issues when it is enabled, that implies you have property getters or `ToString` methods with side-effects. Ideally you should avoid side-effects in such methods, but for when it can't be avoided you can apply [`[DebuggerBrowsable(DebuggerBrowsableState.Never)]`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggerbrowsableattribute) to properties avoid having them evaluated by the debugger. (You can still manually add them to the watch window, but Visual Studio won't show them in the locals or autos window anymore.) In the case of complex `ToString` methods, you can use [`DebuggerDisplayAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggerdisplayattribute) instead to change how a type is represented in the debugger.
