### ISSUE TITLE
The 'dotnet build' command hangs when building a specific code

### ISSUE THREAD

**Issue by livarcocc** [dotnet/roslyn#34020]
@pavelovcharov commented on [Thu Mar 07 2019](https://github.com/dotnet/cli/issues/10942)

The following code will cause the `dotnet build` command to hang:
```
 class ListItem {
            public ListItem Prev { get; set; }
            public ListItem Next { get; set; }
        }
        void ArrangeNonOverlapping(IList<ListItem> labels) {
            List<ListItem> actualLabels = new List<ListItem>(labels);
            ListItem prev = null;
            ListItem next = null;
            for (int i = 0; i < labels.Count; i++) {
                ListItem label = actualLabels[i];
                label.Prev = prev;
                label.Next = next;
                if (prev != null)
                    prev.Next = label;
                if (next != null)
                    next.Prev = label;
            }
        }
```
There is no issue when this code is built within Visual Studio

## Steps to reproduce
I have prepared a small sample to demonstrate the issue: https://github.com/pavelovcharov/netcore3_dotnetbuildhangs

1) git clone https://github.com/pavelovcharov/netcore3_dotnetbuildhangs
2) cd netcore3_dotnetbuildhangs
2) dotnet build

## Expected  behavior
The ```dotnet  build``` command successfully builds the project

## Actual behavior
The ```dotnet  build``` command hangs

## Environment data
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-010591
 Commit:    6cb32d53bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-010591\

Host (useful for support):
  Version: 3.0.0-preview4-27503-9
  Commit:  04c13d860a

.NET Core SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010124 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-010591 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19067-0383 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19153-01 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27316-4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27503-9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27316-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27501-41 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

---

@livarcocc commented on [Mon Mar 11 2019](https://github.com/dotnet/cli/issues/10942#issuecomment-471779151)

This is actually hanging on Roslyn in the VBCSCompiler. Saw that through Process Explorer. Moving this issue there.

**Comment by vetuomia** [comment]
Minimal example demonstrating the hang:

```cs
class Foo {
    Foo foo;
    
    void Hang() {
        Foo bar = null;
        while (bar == null) {
            bar = new Foo { foo = bar };
        }
    }
}
```

**Comment by jcouv** [comment]
I was not able to repro this. I cloned the repo, ran `dotnet build` and it completed (build succeeded).

Here's what's on my machine:
```
D:\repos\netcore3_dotnetbuildhangs\netcore3_dotnetbuildhangs>dotnet --list-sdks
2.1.4-preview-007237 [C:\Program Files\dotnet\sdk]
2.1.4-preview-007239 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.300-rtm-008866 [C:\Program Files\dotnet\sdk]
2.1.400 [C:\Program Files\dotnet\sdk]
2.1.401 [C:\Program Files\dotnet\sdk]
2.1.500 [C:\Program Files\dotnet\sdk]
2.1.502 [C:\Program Files\dotnet\sdk]
2.1.504 [C:\Program Files\dotnet\sdk]
2.1.505 [C:\Program Files\dotnet\sdk]
2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
2.1.600 [C:\Program Files\dotnet\sdk]
2.1.601 [C:\Program Files\dotnet\sdk]
2.1.602 [C:\Program Files\dotnet\sdk]
2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
2.1.800-preview-009711 [C:\Program Files\dotnet\sdk]
2.2.105 [C:\Program Files\dotnet\sdk]
3.0.100-preview-009762 [C:\Program Files\dotnet\sdk]
3.0.100-preview-010024 [C:\Program Files\dotnet\sdk]
3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]
3.0.100-preview9-013775 [C:\Program Files\dotnet\sdk]
```

**Comment by gafter** [comment]
@pavelovcharov Please reopen if you can repro this on the latest dotnet 3.0 prerelease.
