### ISSUE TITLE
Bad name for SyntaxGenerator.AssignmentStatement()

### ISSUE THREAD

**Issue by bazuka5801** [dotnet/roslyn#34039]
**Version Used**: 
[CSharpSyntaxGenerator.cs](https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs)
**Steps to Reproduce**:

```csharp
_generator.MethodDeclaration(
    ...
    statements: new[] {
        _generator.AssignmentStatement(...)
    }
);
```

**Expected Behavior**:
```csharp
public override SyntaxNode AssignmentStatement(SyntaxNode left, SyntaxNode right)
            => SyntaxFactory.ExpressionStatement(SyntaxFactory.AssignmentExpression(SyntaxKind.SimpleAssignmentExpression, (ExpressionSyntax)left, Parenthesize(right)));
```
**Actual Behavior**:
```csharp
public override SyntaxNode AssignmentStatement(SyntaxNode left, SyntaxNode right)
            => SyntaxFactory.AssignmentExpression(SyntaxKind.SimpleAssignmentExpression, (ExpressionSyntax)left, Parenthesize(right));
```

**Comment by CyrusNajmabadi** [comment]
@bazuka5801 i can't really understand the problem you're having.  Can you explain the issue more clearly?

**Comment by bazuka5801** [comment]
@CyrusNajmabadi Statement is the StatementSyntax, not Expression.
Need to rename AssignmentStatement to AssignmentExpression or change logic as in Expected Behavior.

**Comment by CyrusNajmabadi** [comment]
> Need to rename AssignmentStatement to AssignmentExpression 

We called it that because it is a statement in VB.  And, as such there's no name that fits both.

> Need to rename AssignmentStatement to AssignmentExpression

That would be a breaking change.  It can't be done.

> or change logic as in Expected Behavior.

That would be a breaking change.  It can't be done.  

--

Expected use of these APIs is as follows:  `g.ExpressionStatement(g.AssignmentStatement(...))`.  That will properly produce an assignment-statement in both VB and C#.

**Comment by bazuka5801** [comment]
It is not logical syntactically.
May be can override in CSharpSyntaxGenerator to change logic?

**Comment by bazuka5801** [comment]
Why i need know that vb it statement, but in C# it expression, if i generate C# code?

**Comment by CyrusNajmabadi** [comment]
> May be can override in CSharpSyntaxGenerator to change logic?

That would be a breaking change. We can't do that.

**Comment by CyrusNajmabadi** [comment]
> Why i need know that vb it statement, but in C# it expression, if i generate C# code?

SyntaxGenerator was created at a way to easily write code once that would generate both C# **and** Vb. 

If you just want to generate C# use SyntaxFactory
