### ISSUE TITLE
Extract called method information using roslyn

### ISSUE THREAD

**Issue by doorman02** [dotnet/roslyn#34037]
**Version Used**: 
Latest
**Steps to Reproduce**:

I need to get information about a method call into a DLL using Roslyn. For example, I have the following method where dllObject is part of a DLL file.

```
 public void MyMethod()
 {
     dllObject.GetMethod();
 }
```
Is it possible to extract the method information for GetMethod such as it´s name, class name and assembly name.

**Comment by CyrusNajmabadi** [comment]
> I need to get information about a method call into a DLL using Roslyn

> Is it possible to extract the method information for GetMethod such as it´s name, class name and assembly name.

No, roslyn does not expose any information about the *contents* of a method-body *inside* a dll.  It could tell you the *types and signatures* of the types/methods in your dll, but nothing about the internal contents of those methods.  
--
If you want to analyzer source code though, then Roslyn can help you.

**Comment by doorman02** [comment]
Hi @CyrusNajmabadi thanks, that's what I meant, How can I get the signature ofthe types/methods in the dll? Thanks for your help.

**Comment by CyrusNajmabadi** [comment]
@doorman02 Take a look at many of hte roslyn walkthroughs out there.  For example: https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Semantic-Analysis

Once you have a Compilation, with an attached MetadataReference that points to your dll, it will be simple to just "walk" the symbols of that reference.

**Comment by CyrusNajmabadi** [comment]
I recommend for these style of questions you use gitter.im/dotnet/roslyn.  There will be many more people there that can respond and possibly help out.

**Comment by doorman02** [comment]
Thanks I will have a better look.

**Comment by jinujoseph** [comment]
@mavasani
