### ISSUE TITLE
Nullable walker: Simplify the "set of slots to set non-null"

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#34046]
The nullable walker has a method to compute the set of slots to set to non-null.  It fills the data into an array builder.

We could instead return just the innermost slot and let the caller walk up to the enclosing slots.  Then we'd be returning just an `int` instead of an array builder full of data.

I think the code would be simpler and much more efficient.

**Comment by cston** [comment]
It looks like the method is `NullableWalker.GetSlotsToMarkAsNotNullable()`.

**Comment by cston** [comment]
`GetSlotsToMarkAsNotNullable()` handles several cases in addition to simple dotted names, so there might be some complexity walking up from a single `int`. 

Let's leave the method as is since there we're not aware of a performance issue currently.
