### ISSUE TITLE
IDE0042 Variable declaration can be deconstructed invalid fix

### ISSUE THREAD

**Issue by myblindy** [dotnet/roslyn#34043]
**Version Used**: 
VS2019 RC1, but it happens in current 2017 too. 

**Code to Reproduce**:

    var item = contextcache.GetOrAdd((filename, forcealpha, alphacolor, alphacolorrange), key =>
                (File.Exists(filename) ? new GLTexture(filename, forcealpha, alphacolor, alphacolorrange) : null, DateTime.Now));
    item.LastAccessedAt = DateTime.Now;

Applying the fix, the code gets changed to the following:

    var (Texture, LastAccessedAt) = contextcache.GetOrAdd((filename, forcealpha, alphacolor, alphacolorrange), key =>
        (File.Exists(filename) ? new GLTexture(filename, forcealpha, alphacolor, alphacolorrange) : null, DateTime.Now));
    LastAccessedAt = DateTime.Now;

That is absolutely not equivalent code, because what was before a field update (`LastAccessedAt`) is now a no-op.

**Comment by CyrusNajmabadi** [comment]
> That is absolutely not equivalent code, because what was before a field update (LastAccessedAt) is now a no-op.

It was a field update to the copy in your local code.  i.e. in this code:

```c#
var item = contextcache.GetOrAdd((filename, forcealpha, alphacolor, alphacolorrange), key =>
            (File.Exists(filename) ? new GLTexture(filename, forcealpha, alphacolor, alphacolorrange) : null, DateTime.Now));
item.LastAccessedAt = DateTime.Now;
```

This is not changing the value in the cache.  Because the value in hte cache is another copy of this *ValueTuple*.
