### ISSUE TITLE
Find All References windows does not track source changes

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#34057]
When I do a "Find" to find all occurrences of a string, clicking on the Find results continues to navigate the the relevant found line, even if changes have caused its line number to change between the time the "find" was done and the time the find result line was clicked on.  Nice!  Thank you, Visual Studio!

However, when I do a "Find All References" to find all references to a symbol, clicking on the references result will navigate to the line whose number was the line of the found result at the time the search was performed.  If the source file was edited, that line will likely have nothing to do with the location of the reference to the symbol.

Please make the "Find All References" window track file changes as nicely as the "Find" window does.

**Comment by sharwell** [comment]
Design review: this is a difficult problem in general, but the following specific scenario should be supported:

1. Run Find All References
2. Open a document which contains one or more found references
3. Add or remove lines above the reference in the file
4. Double click a reference in that file in the Find All References window

The ability of (4) to navigate to the correct location should not be impacted by (3).

This scenario should work whether or not the file is saved between (3) and (4), but the behavior if the user _closes_ the document after step (3) is not specified by this design.

**Comment by CyrusNajmabadi** [comment]
Closing as external.  We supply the files/lines/columns.  Platform/editor should track then mappign that across edits the user has made.  Tagging @olegtk .
