### ISSUE TITLE
IDE0019 fails with disposable

### ISSUE THREAD

**Issue by PhilPJL** [dotnet/roslyn#34068]
**Version Used**: 
VS2019 16 P4.2
**Steps to Reproduce**:

...
```
                using (var user = new UserPrincipal(context))
                {
                    user.SamAccountName = request.ClientUserName;

                    using (var searcher = new PrincipalSearcher())
                    {
                        searcher.QueryFilter = user;

// use pattern matching suggested here
                        using (var principal = searcher.FindOne() as UserPrincipal)
                        {
                            if (principal != null)
                            {
                                isValid = (principal.Enabled ?? false) && !principal.IsAccountLockedOut();
                            }
                        }
                    }
                }
```

**Expected Behavior**:
No suggestion? 

**Actual Behavior**:
Uncompilable code

                        using ()
                        {
                            if (searcher.FindOne() is UserPrincipal principal)
                            {
                                isValid = (principal.Enabled ?? false) && !principal.IsAccountLockedOut();
                            }
                        }

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/48110
