### ISSUE TITLE
Public API checker does not distinguish properties from methods

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#3407]
The public API checker does not distinguish between

``` cs
public int Foo { get; }
```

and

``` cs
public int get_Foo();
```

even though this affects (compile-time) clients.

**Comment by jasonmalinowski** [comment]
@mavasani Should we move this to roslyn-analyzers somewhere?

**Comment by mavasani** [comment]
Yes, we should port it to roslyn-analyzers.

**Comment by jinujoseph** [comment]
This issue was moved to dotnet/roslyn-analyzers#1651
