### ISSUE TITLE
Roslyn should not depend on IAsyncCompletionSource to provide completion trigger reason

### ISSUE THREAD

**Issue by tinaschrepfer** [dotnet/roslyn#34089]
Currently, Roslyn sets the completion reason in a property bag when Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CompletionSource.GetCompletionContextAsync is called:

`            session.Properties.AddProperty(InitialTriggerKind, roslynTrigger.Kind);
`
It later attempts to retrieve it in Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.ItemManager.UpdateCompletionList() method to determine if filtering should be done.

This doesn't work when Roslyn is not the one providing completion source.  

Instead, Roslyn should get completion reason through editor through IAsyncCompletionManager.SortCompletionListAsync.

**Comment by ivanbasov** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/34095
