### ISSUE TITLE
`#nullable restore` in generated file should restore nullable context from project 

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#34094]
Currently, this directive behaves like `#nullable disable` in generated files, because the default context of generated files is "disabled".

But in the context of a Razor generated file, which mixes user code with generated code, `#nullable restore` would be much more useful and intuitive if it restored the context from the project.

Also, this would allow Razor to produce a `#nullable restore`/`#nullable disable` pair around blocks of user code and get the behavior that users would expect (ie. their project setting is effective). Razor would then also add `@nullable ...` directive in its own syntax and modulate the code it generates.

FYI @rynowak @NTaylorMullen @chsienki @cston @AlekseyTs @gafter 

Relates to https://github.com/aspnet/AspNetCore-Tooling/pull/349

**Comment by jcouv** [comment]
Assigned to Chris. 
Let's validate with LDM (maybe by email) before making the change though. Thanks

**Comment by NTaylorMullen** [comment]
Curious, will `#line default` be equivalent to doing `#nullable disable` in a Razor generated file?

**Comment by jcouv** [comment]
No, I'd propose that `#line` pragmas including `#line default` would not interact with nullable context or warnings.

**Comment by chsienki** [comment]
The proposed fix for this is here, pending LDM sign off: https://github.com/dotnet/roslyn/compare/master...chsienki:nullable_generated_restore?short_path=4692c24#diff-4692c2430fa5dc4f86e093d9b981e4ec
