### ISSUE TITLE
Fix RS1010 on default Analyzer + Fix project

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#3409]
Recently we added the RS1010 diagnostic to CodeAnalysis analyzers package to help assist in correct and maintainable implementation of CodeFixProviders that support GetFixAllProvider. Unfortunately, this diagnostic is generated for our default Analyzer + Fixer project:

```
Severity	Code	Description	Project	File	Line	Build tool	Detail Description
Warning	RS1010	Provide an explicit argument for optional parameter 'equivalenceKey', which is non-null and unique across all code actions created by this fixer.	Analyzer2	C:\Temp\Analyzer2\Analyzer2\Analyzer2\CodeFixProvider.cs	44	Microsoft.CodeAnalysis.CSharp.Analyzers

A CodeFixProvider that intends to support fix all occurrences must classify the registered code actions into equivalence classes by assigning it an explicit, non-null equivalence key which is unique across all registered code actions by this fixer. This enables the FixAllProvider to fix all diagnostics in the required scope by applying code actions from this fixer that are in the equivalence class of the trigger code action.
```

We should fix the `CodeAction.Create` invocation in the fixer to provide an explicit non-null argument for 'equivalenceKey'. The value can just be the same as the title used for the code action.

**Comment by mavasani** [comment]
@srivatsn @jmarolf We may want to fix this for 1.0 stable milestone. Fix needs to go into both C# and VB fixers.

**Comment by jmarolf** [comment]
fixed with internal Changeset 1486229

**Comment by mavasani** [comment]
@srivatsn @jmarolf I see that the fix made sets the `equivalenceKey` to the name of the CodeFixProvider type: `equivalenceKey: nameof($saferootidentifiername$CodeFixProvider))` I'd think it might make more sense to have the code action 'title' as the default equivalence key, as it will just work as expected if the user registers an additional code action, presumably with a different title. Was there a specific reason we chose the fixer type name here?

**Comment by jmarolf** [comment]
@mavasani no particular reason other than it being unique and us also using the typename as an Id. I can make the change if you like

**Comment by mavasani** [comment]
@jmarolf Yes, I think we shouldn't use code fixer type name as the equivalenceKey as adding a new code action with same equivalence key will cause only a single fix to show up in the light bulb. Can you please change it to use the title instead?

**Comment by BryanKelly** [comment]
Can someone please provide more guidance on how to fix this?  I read the comments in the code and they don't make much sense to me.  It makes me think that I should be using Guid.NewGuid().ToString() as the string.  Thanks.

**Comment by mavasani** [comment]
@BryanKelly  We added documentation for this: https://github.com/dotnet/roslyn/blob/master/docs/analyzers/FixAllProvider.md
Please let us know if that addresses your questions.

**Comment by BryanKelly** [comment]
That does help.  Thanks!  I did not see that documentation.  In fact I didn't see any of that.  I will certainly use that as a go-to moving forward.

**Comment by dbolkensteyn** [comment]
@mavasani I'm not sure that it is a good idea to always fix diagnostics reported by this analyzer: Let's take as an example an analyzer + codefix to detect `.OrderBy()` chains and offer to replace them into `.ThenBy()`:

Example:
```
myList.OrderBy(a).OrderBy(b).OrderBy(c)
```
becomes:
 ```
myList.OrderBy(a).ThenBy(b).ThenBy(c)
```

1. If `null` (or no argument) is used as an `equivalenceKey`, then I do see the 2 possible code fixes on the line level light bulb. Moreover, when fixing all issues in the document, they are all fixed as expected.
2. If `Title` is re-used as an `equivalenceKey`, then on the line level light bulb, I only see one possible codefix action - but 2 suppress warnings suggestions for the same analyzer ID. Fixing all issues in the document works as expected.

So, from a user experience point of view, it seems that 1. is a better way.

In this particular case, I don't really want to limit the bulk code fixer to a given scope: It is able to solve *all* diagnostics of the analyzer.

Does is still make sense to provide an `equivalenceKey` in this case, and if so, why?

**Comment by mavasani** [comment]
@dbolkensteyn The issue you mention in 2. about duplicate suppress warning suggestions is a separate bug tracked by #3311 that we are going to fix soon. You'll have the same behavior for both scenarios then.

Equivalence key basically denotes the set of equivalent fixes offered by the fixer. When showing the available fixes via the lightbulb to the user, we don't want to show duplicate fixes. Additionally, when the batch fix all provider is performing a fix all operation, we only want to fix instances of diagnostics that belong to the same equivalence class. Using a non-null explicit string as an equivalence key ensures that the fixer is maintainable: in future, if you register a new code action in your fixer, you explicitly chose its equivalence class, instead of just defaulting to null.
