### ISSUE TITLE
Find All References does not support LINQ

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34106]
**Version Used**: Visual Studio 2019 Preview 4

🔗 http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/634818

**Steps to Reproduce**:

```csharp
using System;
using System.Collections.Generic;
class C : List<int>
{
    void Zap()
    {
        var q = from v in this
                where v > 1
                select v + 1;
    }
}

static class Extensions
{
    public static IEnumerable<int> Where(this IEnumerable<int> source, Func<int, bool> predicate) => throw null;
    public static IEnumerable<int> Select(this IEnumerable<int> source, Func<int, int> func) => throw null;
}
```

1. Click `Where` (the method definition)
2. Click `where` (the query keyword)
3. Click `Select` (the method definition)
4. Click `select` (the query keyword)

**Expected Behavior**:

1. Both `Where` and `where` are highlighted
2. Both `Where` and `where` are highlighted
3. Both `Select` and `select` are highlighted
4. Both `Select` and `select` are highlighted

**Actual Behavior**:

1. Only `Where` is highlighted
2. Only `Where` is highlighted
3. Only `Select` is highlighted
4. Only `Select` is highlighted

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
