### ISSUE TITLE
Find All References does not support using statements

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34107]
**Version Used**: Visual Studio 2019 Preview 4

:link: http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/522786

**Steps to Reproduce**:

```csharp
class Example : System.IDisposable
{
    public void Dispose() { }
    void Method()
    {
        using (new Example())
        {
        }
    }
}
```

1. Place the caret on `Dispose` (the method definition)
2. Place the caret on `using` (the keyword)

**Expected Behavior**:

1. Both `Dispose` and `using` are highlighted
2. Both `Dispose` and `using` are highlighted

**Actual Behavior**:

1. Only `Dispose` is highlighted
2. Only `using` is highlighted

**Comment by CyrusNajmabadi** [comment]
This is odd, we should have tests for this...

**Comment by sharwell** [comment]
@CyrusNajmabadi yes that's the **Disabled Test** label. :joy:

**Comment by CyrusNajmabadi** [comment]
@jcouv are tehre compiler APIs to let us know which Dispose method was used in a `using` statement or declaration?

**Comment by CyrusNajmabadi** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/28228
