### ISSUE TITLE
'lock' statement fails to report implicit references to Monitor.Enter and Monitor.Exit

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34105]
**Version Used**: Visual Studio 2019 Preview 4

:link: http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/528936

**Steps to Reproduce**:

Use the following code, with `$$` indicating the caret placement for two scenarios.

```csharp
using System.Threading;
using System.Collections.Generic;
class C
{
    void Zap()
    {
        bool lockTaken = false;
        Monitor.TryEn$$ter(null, ref lockTaken); // Scenario 1
        Monitor.Ex$$it(null); // Scenario 2
        lock (new C())
        {
        }
    }
}
```

**Expected Behavior**:

1. The **Highlight References** feature highlights the `lock` keyword
2. **Find All References** finds the `lock` keyword

**Actual Behavior**:

The `lock` keyword is not identified as a reference to `Monitor.TryEnter(object, ref bool)` or `Monitor.Exit(object)`.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
