### ISSUE TITLE
Cref: constructor overload parameter list differences are disregarded in VB

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34104]
**Version Used**: 

🔗 http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/769477
🔗 https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems/edit/93772

**Steps to Reproduce**:

Roslyn as of 8/26/13.
 

1. Open ETA, paste the following VB snippet:

```vb
Class A
    Public Sub New()
    End Sub
    Public Sub New(x As Integer)
    End Sub
End Class
Class Program
    ''' <summary>
    ''' <see cref="A.New()"/>
    ''' <see cref="A.New(Integer)"/>
    ''' </summary>
    ''' <param name="args"></param>
    Shared Sub Main(args As String())
        Dim a As A = New A()
    End Sub
End Class
```

Place cursor on "New" inside cref="A.New(Integer)" - observe both constructor overloads to become highlighted, regardless of parameter list differences (FAR also returns both of them) 
 
2. Paste the analogous C# snippet:

```csharp
class A
{
    public A() { }
    public A(int x) { }
}
class Program
{
    /// <summary>
    /// <see cref="A.A()"/>
    /// <see cref="A.A(int)"/>
    /// </summary>
    /// <param name="args"></param>
    static void Main(string[] args)
    {
        A a = new A();
    }
}
```

Place cursor on last A in cref="A.A(int)" - observe only A(int x) overload becomes highlighted

**Comment by CyrusNajmabadi** [comment]
Closing out.  C# behavior seems good, and we're not investing in the VB side.
