### ISSUE TITLE
Suppressed warning + errorlog + warnaserror -> Silent failed compilation with zero exit code

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn#34101]
**Version Used**: 3.0.19.15604 (7d31dd6e)

**Steps to Reproduce**:

1. Create test.cs
``` C#
#pragma warning disable 1591

public class P {
    public static void Main() {}
}
```
2. `csc.exe test.cs -doc:doc.xml -errorlog:errors.json -warnaserror`

**Expected Behavior**:

Compilation succeeds, test.exe is generated.

**Actual Behavior**:

Csc.exe returns 0, but test.exe is not generated

**Comment by vukelich** [comment]
Thanks for filing this, Nick. It's preventing me from running some required analyzers and giving the errorlog file to one of the 1ES security teams.
