### ISSUE TITLE
Language Feature?

### ISSUE THREAD

**Issue by TheXenocide** [dotnet/roslyn#34116]
I'm not sure what I would call this particular type of syntax sugar, but as I was reading through some source recently I wondered if there wasn't a readable way to simplify the following commonly occurring pattern? (Note: this is from some older sample source; I updated it here to use `out string value` already, where it was previously using `string value;` on the preceding line)

```csharp
return Items.TryGetValue(RedirectUriKey, out string value) ? value : null;
```
Surely it's not the most important feature request, but I figured it wouldn't hurt to ask. Maybe something like
```csharp
Items.TryGetValue(RedirectUriKey, return string value);
```
Allowing `return` to be used in place of `out` or `ref` (possibly even optimizing around allocation behavior? I'm not sure of the internals involved here). I honestly haven't thought super deeply about this so feel free to shoot it down, but it was a thought I figured I'd share.

**Comment by YairHalberstadt** [comment]
This looks like it would be more appropriate for the csharplang repo, where requests for language changes are taken.

Also, if you're not sure of a suitable syntax, you might want to discuss your ideas on www.gitter.im/dotnet/csharplang first.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #2348](https://github.com/dotnet/csharplang/issues/2348) via [**ZenHub**](https://www.zenhub.com/)
