### ISSUE TITLE
Wrap Expression wraps long if in a weird spot

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#34127]
![image](https://user-images.githubusercontent.com/2371880/54391173-5dbdc280-4661-11e9-8d4a-dd9fbe2e2d93.png)

Instead of offering to wrap at the `&&`, it instead offers to wrap in the middle of the `==`, which is not a good place to wrap this expression.

**Comment by CyrusNajmabadi** [comment]
Agreed.  We probably want to pick a location of lower precedence.

**Comment by jasonmalinowski** [comment]
@333fred: so the thing with "wrap expression" was it'll wrap on the operator your caret was on. Was that something you were aware of? (We're asking because it wasn't obvious to many of us either.)

@CyrusNajmabadi: should we just remove the == from wrapping in this case? It was unclear to us whether this is by design or just a bug.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi: should we just remove the == from wrapping in this case? It was unclear to us whether this is by design or just a bug.

I'd be ok with that.  Tough to imagine it's what people want.  Maybe a design review to go through all the ops to see which make sense and which don't.

**Comment by jasonmalinowski** [comment]
We did chat through it, and there were some cases like if you are trying to write `if (foo2.Bar.Baz.Qux.Quux == foo2.Bar.Baz.Qux.Quux)` and want them to align. We just mostly realized we weren't entirely sure what design already existed here to be confident enough we can change it.

**Comment by CyrusNajmabadi** [comment]
Well, the current design is primarily: wrap around the operator the user picked, allowing wrapping as long as you're still hitting operators of the same type (i.e. precedence). That seemed like a reasonable heuristic.  However, i can tehre being desire to take a different approach here.  i.e. it seems like it woud be fine to keep walking up binary expressoins (remember about patterns too!) and then wrap at the highest points.  This feels "more natural" to me.  i.e. if i have:


`if ($$a + b + c + d == x * y * z)`  

then i probably want:

```
if ($$a + b + c + d ==
    x * y * z)
```

Versus

```
if (a +
    b + 
    c + 
   d == x * y * z)
```

**Comment by 333fred** [comment]
> Was that something you were aware of? (We're asking because it wasn't obvious to many of us either.)

Nope, I had no expectation that this was the case, and the revelation, while surprising, does make some about of sense. Not sure how to communicate that more clearly though.
