### ISSUE TITLE
Make it possible to decide style rules based on context

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34129]
.editorconfig is nice, but it's not enough. For example, even though I like to use var when the type is apparent, I think that if the type is not <em>relatively </em><em>obvious</em>, then explicit type should be used. Also, I don't think var should be used when the local is going to be assigned to a dynamic or to a Object (because when code is refactored, no compilation error is emitted in these situations). Thus, setting var for apparent types = true, VS will suggest using var in all of the following situations:

```csharp
// 1
Type x = new Type();

// 2
Type y = GetTypeById(1);

// 3
services.AddTransient<Type>(sp => {
    // lots of logic
    return new Type();
});

// 4
Type z = new Type();
return new { z };
```

Even though I think var should be used only on the first two situations.

Also, there's expression-bodied members (EBM). If I tell VS to use EBM when possible, it will suggest using it in both of the following situations:

```csharp
public void Foo() 
{ 
   Bar();
}
public void Baz()
{
    return TryGetResponseData<IEnumerable<Try<FooBar>>>(await restClient.FooBarEndpoint.Get(2));
}
```

Even though I think EBM should only be used on the first one, since the second one is too long to fit in one line along with the declaration.

Then there's also curly braces and ifs. I think one-line ifs shouldn't have braces, except when something inside them use braces. Thus, if I tell VS to use brace-less ifs, it will in both of these situations:

```csharp
// 1
if (foo)
{
    return bar;
}

// 2
if (foo)
{
    if (bar)
    {
        var baz = GetBaz();
        baz.DoBaz();
        return baz;
    }
}
   
```

Even though I think it should remove braces only in the first situation.

I don't know what the best solution to this would be. It could be something using Roslyn, so that you could intercept every style rule when they're matched, run your own code and decide if the rule should be applied or not.

However, something else that you could do is simply add more rules to these specific, but more general cases, like the three I mentioned. These three style rules I mentioned are not *hugely* popular, but they can be found pretty easily in various repos out there.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/466695/make-it-possible-to-decide-style-rules-based-on-co.html
VSTS ticketId: 800947_
_These are the original issue comments:_

Jane Wu [MSFT] on 2/25/2019, 01:28 AM (17 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by kendrahavens** [comment]
Related #29657

**Comment by andre-ss6** [comment]
Also, another common use-case is wanting to remove unused using directives, but always preserving `using System;`

**Comment by CyrusNajmabadi** [comment]
Closing out as unplanned.
