### ISSUE TITLE
Inline temporary variable should be available on usages of variable, not just declaration

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#34142]
Reported by @drewnoakes 
Affected Branch: 
Affected Build: 16.0.0 Preview 4.1 SVC1 
Affected Product Language: 

Steps to reproduce:

Given code

```c#
var s = "";
Bar(s);
```

The "Inline temporary variable" refactoring should be available on all usages of the `s` symbol (i.e. on both the declaration and the usage).

**Comment by CyrusNajmabadi** [comment]
This would def need a design review.  Thsi could easily make the feature too noisy, and we've already heard from people (including team members that they're finding code-actions noisy enough).

**Comment by drewnoakes** [comment]
A benefit of having it on the usage is the (future) ability to inline only a single usage. This is something ReSharper offers and can be quite useful.

**Comment by sharwell** [comment]
Design review conclusion: it makes sense to allow the inline variable refactoring to work from use sites.

* When invoked from a use site, the variable is inlined the same as it is today (all usages are replaced, and the temporary variable is eliminated)
* When invoked from a declaration, the code fix priority does not change from what it is now
* When invoked from a use site, the code fix priority is low
