### ISSUE TITLE
Feature Request: C# - Runtime parsing of interpolation-tokenized string

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/roslyn#34145]
C# introduced interpolated strings (i.e. $"{varname}") back in 6.0. This is a feature request to extend it in a future iteration of the language/compiler. This could possibly be done using some manner of a compiler trick as well ?

Consider this snippet of code of the as-is scenario:

**Snippet 1:**
```
const string url = "https://login.microsoftonline.com/{tenantId}";
//…


string tenantId = "contoso.onmicrosoft.com";
//…
Uri u = new Uri( url.Replace("{tenantId}, tenantId) );
```

Now, wouldn't it be more useful (reducing lines of code and errors to do with string replacements if this could simply be something like:

**Snippet 2:**
```
const string url = "https://login.microsoftonline.com/{tenantId}";
//…


string tenantId = "contoso.onmicrosoft.com";
//…
Uri u = new Uri( $url );
```

Note that in the 2nd snippet, I have prefixed the `url` variable in the Uri constructor with a `$` indicating that I want the compiler to perform the intended magic.

Can this be?

**Comment by HaloFour** [comment]
I believe this request would be more appropriate over on the [CSharpLang repo](https://github.com/dotnet/csharplang/) as it proposes changes to the language.

**Comment by sujayvsarma** [comment]
Is it possible to MOVE this there? Or do we do the open/close dance?

**Comment by sujayvsarma** [comment]
Closing this as I have created the issue at CSharpLang repo.

**Comment by sujayvsarma** [comment]
The feature was implemented in C# as `FormattableString`s. It achieves the same results that I was looking  for, thank you!

Example: https://docs.microsoft.com/en-us/dotnet/api/system.text.json?view=netcore-3.0

Docs: https://docs.microsoft.com/en-us/dotnet/api/system.formattablestring?view=netframework-4.8
