### ISSUE TITLE
Debugger incorrectly evaluates indexer of generic type

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#34155]
**Version Used**: Microsoft Visual Studio Enterprise 2019 Int Preview Version 16.0.0 Preview 4.3 [28711.165.d16.0stg]

**Steps to Reproduce**:

1.  Compile the following program
2.  Set a breakpoint at the end of `Main`
3.  Evaluate `d[1].Item1` in the Watch window

``` c#
using System.Collections.Generic;

class Program
{
    public unsafe static void Main()
    {
        var d = new Dictionary<int, (string, int)>();
        d.Add(1, ("string", 1));
        var tmp = d[1];
    }
}
```

**Expected Behavior**:

Displays `"string"`

**Actual Behavior**:

Displays `null`

![image](https://user-images.githubusercontent.com/3804346/54448246-7c2ac900-4708-11e9-93af-e444ed036916.png)

**Comment by 0xd4d** [comment]
Looks like https://github.com/dotnet/roslyn/issues/29951

**Comment by tmat** [comment]
Dup of https://github.com/dotnet/coreclr/issues/25519
