### ISSUE TITLE
Gathering Suggestions: Pre-calculate these

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34179]
<p>When using Ctrl+. on an Intellisense red squiggle error, there is a few seconds of delay while &quot;gathering suggestions&quot;.  Perhaps, in some kind of low priority background task, Visual Studio could spend some of my spare CPU cycles working through these BEFORE I come to use Ctrl+.?  This would make for a great improvement to development experience.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/448994/gathering-suggestions-pre-calculate-these.html
VSTS ticketId: 789069_
_These are the original issue comments:_

Jane Wu [MSFT] on 2/11/2019, 02:59 AM (32 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
This is already how things work.  We have kicked off the work to fiure out what to show.  But sometimes it does just take a while as there are many features checking if they're available, and there is limited CPU slots to spare.
