### ISSUE TITLE
Code Snippets for C# just like VB side has by default

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#34173]
[Original developer community feedback](https://developercommunity.visualstudio.com/content/idea/466655/code-snippets-for-c-just-like-vb-side-has-by-defau.html)

**Version Used**: Visual Studio 2019 Preview

**Steps to Reproduce**:
1. Type (Ctrl + K, Ctrl + X) to access C# snippets.

**Expected Behavior**:
Rich snippet library available in Visual Basic also available in C#.

**Actual Behavior**:
C# snippets are limited to some simple 'Surrounds With' and simple syntax options. Visual basic's snippets are more task-oriented code blocks.

>Complete "do this task" snippets, such as Read, Write, or Delete a reg key. Read, Write, Append to a file. Complete little tasks, while C# is just quick access to common things like making a loop, else block, etc. Useful, but nowhere near as useful as VB's long list of actual tasks.

C#
![image](https://user-images.githubusercontent.com/8293542/54460710-96c06a80-4727-11e9-8524-40b5ee855406.png)

Visual Basic
![image](https://user-images.githubusercontent.com/8293542/54460669-7395bb00-4727-11e9-943b-82384b309d7e.png)

**Comment by sharwell** [comment]
Blocked on #31879

**Comment by CyrusNajmabadi** [comment]
Closing out.  The existing snippet experiences in legacy mode and aren't being changed.  We're driving things through a new snippet experience.
