### ISSUE TITLE
Class readonly properties goes wrong

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34170]
VSF_TYPE_MARKDOWNusually , when i write this, it is ok.

```
    Public Class TestClass
        Public ReadOnly Property Name As String
        Public ReadOnly Property Age As Integer
        Public Sub New(Name As String, Age As Integer)
            Me.Name = Name
            Me.Age = Age
        End Sub
    End Class
```

but when i write like this, it goes wrong.

![](https://s2.ax1x.com/2019/03/09/App8Te.png)

```
   Public Class TestClass
        Public ReadOnly Property Name As String
        Public ReadOnly Property Age As Integer
        Public Sub New(Name As String, Age As Integer)
            With Me
                .Name = Name
                .Age = Age
            End With
        End Sub
    End Class
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/484179/class-readonly-properties-goes-wrong.html
VSTS ticketId: 816622_
_These are the original issue comments:_

Visual Studio Feedback System on 3/11/2019, 00:25 AM (4 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by gafter** [comment]
Yes, the `With` statement introduces the members of the with'ed expression into the innermost scope, hiding similarly named things from the outer scope (such as the parameter).
