### ISSUE TITLE
Ca we now use roslyn in Production

### ISSUE THREAD

**Issue by ikourfaln** [dotnet/roslyn#3417]
Hi,

We are working on a big project, and we need to build it with C# 6. But we can't wait anymore for the RTM, so is it safe to start the project with Visual Studio 2015 RC ?

Thanx

**Comment by HaloFour** [comment]
This is probably relevant to your question:

[MSDN Blogs: Roslyn ships v1.0-rc2 with "Go-Live" license](http://blogs.msdn.com/b/vbteam/archive/2015/05/01/roslyn-ships-v1.0-rc2-with-go-live-license.aspx)

**Comment by ikourfaln** [comment]
Thanx a lot, thats exactly what I need :+1:
