### ISSUE TITLE
View in Object Browser Fails for Local Projet

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34188]
VSF_TYPE_MARKDOWNI get an error diagnostic when I try to view one of my projects in the Object Browser.

The image shows a local project highlighted, as well as the diagnostic after I right-click it and select View in Object Browser.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/487037/view-in-object-browser-fails-for-local-projet.html
VSTS ticketId: 818783_
_These are the original issue comments:_

Visual Studio Feedback System on 3/13/2019, 00:54 AM (2 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 3/15/2019, 03:18 PM (4 hours ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
### Steps to reproduce:

1. Open a solution that has projects with the new project system (e.g. Roslyn.sln)
2. Expand the **Dependencies** node, then expand **Projects**
3. Right click on a project and select **View in Object Browser**

### Expected results:

Shows the project in **Object Browser**.

### Actual results:

> Value cannot be null.
> Parameter name: unresolvedReference

![image](https://user-images.githubusercontent.com/1408396/54468160-f3d41480-4757-11e9-8fd0-2b8d11a01a6e.png)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in object browser.
