### ISSUE TITLE
Suggest format specifiers based on type

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#34189]
[Original developer community feedback](https://developercommunity.visualstudio.com/content/idea/482533/suggest-format-specifiers-based-on-type.html)

> I have a TimeSpan object, which I need to convert into a string. When I typed ToString(""), I expected to see a list of common format specifiers with examples that I could use to autocomplete my line. Sadly, this is something that Resharper provides that I have come to rely on, and it's missing in Visual Studio 2019.

> My example above speaks specifically to TimeSpan objects, but it applies generally to DateTime, numerics and any other type that accepts format specifiers, both as as an argument to ToString() and inside interpolated strings.

> Intellisense suggests potential methods, events, properties, etc. I'm talking about suggestions for format specifiers when calling ToString().

**Steps to Reproduce**:

1. Type the code below
```csharp
DateTime.Now.ToString("
```

**Expected Behavior**:
When you type the quote (") you get a autocomplete suggestion like this:
```
t - short time                                               6:30
D - long date                             Thursday, 10 April 2008
d - short date                                         04/10/2008
F - full date long               Thursday, 10 April 2008 06:30:00
f - full date short                 Thursday, 10 April 2008 06:30
G - general long                              04/10/2008 06:30:00
.
.
(etc)
```

Just arrow down to the one you need and hit Enter.

Similar autocomplete suggestions are available for numeric types and TimeSpan, to name a few.

**Comment by CyrusNajmabadi** [comment]
This could be done with the virtual-char service.

**Comment by CyrusNajmabadi** [comment]
@jinujoseph I would be interested in taking this on.

**Comment by jinujoseph** [comment]
@CyrusNajmabadi sure, will appreciate help here

**Comment by CyrusNajmabadi** [comment]
@jinujoseph  Sorry, maybe in the future.

**Comment by lindexi** [comment]
Resharper will do it.

**Comment by Phyyl** [comment]
> Resharper will do it.

I don't use Resharper because it slows down VS on my work computer. Having this in vanilla VS would be great!

**Comment by lindexi** [comment]
> > Resharper will do it.
> 
> I don't use Resharper because it slows down VS on my work computer. Having this in vanilla VS would be great!

Agree

**Comment by CyrusNajmabadi** [comment]
We do have this:

![Image](https://github.com/user-attachments/assets/180c95d8-588c-4f38-81ed-0b0de50ee3e9)
