### ISSUE TITLE
Go to implementation throws The Symbol has no implementations - ONLY for parameterized methods

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34191]
VSF_TYPE_MARKDOWNWhen I hit Go to implementation on a method in Visual Studio 2017 or 2019 Preview 3 - (started happening only on .Net core solution, .Net framework 4.7 works fine) - it throws &quot;The Symbol has no implementations&quot; pop up. 
I know this has been reported and you marked some of them as being duplicate but reporting since i found a narrowing condition. 

If the method in question DOES NOT have parameters (e.g. public void MethodA()) then it works. It throws the error ONLY for methods with parameters. There you go, if that helps at all. 

Will be great to have this resolved because it is very annoying and cumbersome to navigate to methods behind the Interface without it. 

Thanks!

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/470557/go-to-implementation-throws-the-symbol-has-no-impl.html
VSTS ticketId: 802805_
_These are the original issue comments:_

Visual Studio Feedback System on 2/26/2019, 07:06 PM (16 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by wellmonge** [comment]
Could I help on this?

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  We'd need a repro case to move forward on this.
