### ISSUE TITLE
PE TimeDataStamp is wrong in VS2017.

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#34196]
PE TimeDataStamp is seconds passed from 1970-1-1 in old visual studio:
`var dateTime = new DateTime(1970, 1, 1, 0, 0, 0).AddSeconds(TimeDataStamp)`

For example, build any application in VS2015, TimeDataStamp = 5C8D3366 (2019/3/16 17:33:26)

But build it in VS2017, TimeDataStamp = AC884742 (2061/9/22 10:58:10)

Is it a bug?

**Comment by svick** [comment]
This is what's supposed to happen when [deterministic builds](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/deterministic-compiler-option) are enabled.

Based on https://github.com/dotnet/roslyn/issues/5431, I think deterministic builds are enabled by default for .Net Core SDK projects.

So no, I don't believe this is a bug.

**Comment by CreateAndInject** [comment]
Is there any way to determine whether a binary is compiled as deterministic? Or whether the TimeDataStamp of a binary is real.

**Comment by gafter** [comment]
> Is there any way to determine whether a binary is compiled as deterministic?

No.  The point of a deterministic build is to create the same compiler output no matter when you did the build.

> Or whether the TimeDataStamp of a binary is real.

Yes.  In https://docs.microsoft.com/en-us/windows/desktop/Debug/pe-format search for `IMAGE_DEBUG_TYPE_REPRO`
