### ISSUE TITLE
Move EventHookup to EditorFeatures layer

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#34190]
Currently EventHookup code is in the VisualStudio layer. To be consumed by VS for Mac it would be nice to move it down to EditorFeatures. From cursory glance we haven't found dependencies that would be hard to isolate from VS.

Currently VSMac has a copy of the code.

**Comment by jasonmalinowski** [comment]
History: this feature used to do evil things with quick info to display the tooltip, and by "evil" I think I mean "reflection against the VS shims". It looks like when we moved to the new quick info APIs in 15.8 I think the hackery went away.

**Comment by jasonmalinowski** [comment]
@tmat: let me know when it's safe to start cleaning some things up out of the EditorFeatures.Cocoa stuff; I know you still have PRs in flight but there's some pretty obvious cleanups that are available once you're done.

**Comment by tmat** [comment]
I think it's already safe. The only problem is with testing though. It'd be good to have some test coverage before/as we start cleaning up. /cc @davidwengier

**Comment by davidwengier** [comment]
I think we should do one "clean" insertion first, where nothing has changed by the source of the DLL, but no reason PRs can't be opened.

Definitely testing is an issue. I started cleaning up the snippets code by removing unused parameters, and had pretty quickly removed enough code that makes me wonder if its ever actually used.

**Comment by KirillOsenkov** [comment]
FYI @DavidKarlas who wrote the Cocoa layer

**Comment by jasonmalinowski** [comment]
Agreeing with @davidwengier that let's get a clean insertion first, but duh of course I can do PRs now. :smile:
