### ISSUE TITLE
Consider removing GCManager

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34202]
Originally noted by @heejaechang in https://github.com/dotnet/roslyn/pull/34055#issuecomment-473607996.

> do we still need this low latency mode? can we just remove whole GCManager stuff. I know we did this to make our typing to meet ceratin matrix for a perf test we no longer has.
> 
> as follow up work item, I would try to get RPS result without this whole GCmanager thing and see whether it shows up anywhere in RPS test. and if not, just remove this whole thing.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we want to do this we should just assign to a milestone and do it.
