### ISSUE TITLE
Issue with Roslyn Emit API

### ISSUE THREAD

**Issue by keowang** [dotnet/roslyn#34205]
**Version Used**: 
Microsoft.CodeAnalysis: v2.10.0
Microsoft.CodeAnalysis.Analyzers: v2.6.3
Microsoft.CodeAnalysis.Common: v2.10.0
Microsoft.CodeAnalysis.CSharp: v2.10.0
Microsoft.CodeAnalysis.CSharp.Workspaces: v2.10.0
.NET Framework Version 4.7.03056
Microsoft Visual Studio Pro 2015 Version 14.0.25431.01 Update 3

**Steps to Reproduce**:
1. Given the program

    using System;
    using System.Collections.Generic;
    using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
class Program
{
    public static int Ksmallest(int[] a, int k, List<string> _var_names_, List<string> _var_values_)
    {
            HashSet < int >  h = new HashSet<int>(a);
            _var_names_.Add("h");
            _var_values_.Add(string.Join("_^-^-^_", h));
            Array.Sort(a);
            _var_names_.Add("a");
            _var_values_.Add(string.Join("_^-^-^_", a));
            return a[k - 1];
    }
}

2. execute it using Roslyn Emit API:
    public static ExecutionResult.Type RunRoslyn(string code)
        {
            SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(code);

            string assemblyName = Path.GetRandomFileName();
            MetadataReference[] references = new MetadataReference[]
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(Enumerable).Assembly.Location)
            };

            CSharpCompilation compilation = CSharpCompilation.Create(
                assemblyName,
                syntaxTrees: new[] { syntaxTree },
                references: references,
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            using (var ms = new MemoryStream())
            {
                EmitResult result = compilation.Emit(ms);

                if (!result.Success)
                {
                    IEnumerable<Diagnostic> failures = result.Diagnostics.Where(
                        diagnostic => diagnostic.IsWarningAsError || diagnostic.Severity == DiagnosticSeverity.Error);

                    foreach (Diagnostic diagnostic in failures)
                        Console.Error.WriteLine("{0}: {1}", diagnostic.Id, diagnostic.GetMessage());

                    return ExecutionResult.Type.NotCompile;
                }
            }
        }

**Expected Behavior**:
The program should be executed without errors

**Actual Behavior**:
EmitResult result = compilation.Emit(ms);
result.Success returns false

"CS0012: The type 'ISet<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
CS0012: The type 'ISet<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'."

**Comment by tmat** [comment]
As the error says you're missing a metadata reference in the `references` array.

See https://github.com/dotnet/roslyn/wiki/Runtime-code-generation-using-Roslyn-compilations-in-.NET-Core-App.

**Comment by keowang** [comment]
Thanks, I guessed that's the problem. According to the doc you sent. 

    you need and where to get them you can create an empty .NET Core library, set the target framework to the one you need to target, build using msbuild /v:detailed and look for csc.exe invocation in msbuild output. The command line will list all references the C# compiler uses to build the library (look for /reference command line arguments).

To start off how can I create an empty .NET Core library?

**Comment by tmat** [comment]
So the doc is specifically targeting .NET Core. Does you project target .NET Core?

**Comment by keowang** [comment]
No I am building a console application

**Comment by tmat** [comment]
I assume that means console application that runs on desktop.
Then add 
```
MetadataReference.CreateFromFile(typeof(ISet<>).Assembly.Location),
```

**Comment by keowang** [comment]
sure I did it but I guess there must be a more elegant solution than this

**Comment by tmat** [comment]
There is not. You need to list all the metadata references you want to access.

**Comment by keowang** [comment]
Does this mean ISet requires a separate metadata reference than IList?
