### ISSUE TITLE
.editorconfig should have setting to not indent case blocks

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn#34203]
**Version Used**: 15.9.9

**Steps to Reproduce**:

Format this `switch` statement:

```C#
switch (value)
{
    case CaseLabel1:
        return 42;

    case CaseLabel2:
    {
        var x = ComputeValue();
        return x;
    }
}
```

**Expected Behavior**:

Have the option in `.editorconfig` to indent case contents, but not case blocks.

**Actual Behavior**:

I can either not indent case contents, in which case it will look like this:

```C#
switch (value)
{
    case CaseLabel1:
    return 42;

    case CaseLabel2:
    {
        var x = ComputeValue();
        return x;
    }
}
```

or I can choose to indent case contents in which case it will also indent blocks:

```C#
switch (value)
{
    case CaseLabel1:
        return 42;

    case CaseLabel2:
        {
            var x = ComputeValue();
            return x;
        }
}
```

**Comment by sharwell** [comment]
There is already a setting for this. I can look up the name tomorrow when I'm at a computer.

**Comment by tannergooding** [comment]
You want to set:
```
csharp_indent_case_contents = true
csharp_indent_case_contents_when_block = false
```

**Comment by terrajobst** [comment]
Looks like the problem [was missing documentation for me](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1070).
