### ISSUE TITLE
Cancel button saves changes for Editing Naming Style options page

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#34215]
**Version Used**: 
D16.0stg 28717.18
**Steps to Reproduce**:

1. Open VS
2. Go to: Tools -> Options -> Text Editor -> C# -> Code Style -> Naming -> Manage Naming Styles -> Edit Pascal Case
3. Change 'Capitalization' to 'First word upper'
4. Hit cancel
5. Open the edit page for Pascal Case again

**Expected Behavior**:
Capitalization is set to the default option

**Actual Behavior**:
Capitalization is set to 'First word upper'

This occurs for every option on the page aside from 'Naming Style Title'

**Comment by dpoeschl** [comment]
Note: This bug existed in 15.9 as well. 

While the user might be tricked into saving style changes they had intended to throw away, they do not become stuck in that state and can go in to revert it.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
