### ISSUE TITLE
Custom naming definition are not stored

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34210]
VSF_TYPE_MARKDOWNHi, reproduction steps as attachement.

The problem description:
1. execute reproduction steps from attachement
2. Open naming options again
3. All custom naming conventions and specifications are missing

Thank you in advice

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/489466/custom-naming-definition-are-not-stored.html
VSTS ticketId: 820333_
_These are the original issue comments:_

Visual Studio Feedback System on 3/14/2019, 11:38 PM (3 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 3/15/2019, 01:11 PM (2 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by MiroslavMikus** [comment]
Here are the steps from '1. execute reproduction steps from attachement':
![2019-03-14 10_36_47](https://user-images.githubusercontent.com/29312172/54557100-af947e80-49ba-11e9-8068-2bf5c3bdbe8d.png)

**Comment by JoeRobich** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/34212
