### ISSUE TITLE
CSharpInteractiveCommands.VerifyNewLineAndIndent Fails

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#34225]
[Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=126871&view=ms.vss-test-web.build-test-results-tab)

```
System.Exception : Unable to find expected content in REPL within 10000 milliseconds and no exceptions were thrown. Actual content:
[[Resetting execution engine.
Loading context from 'CSharpInteractive.rsp'.]]
```

**Comment by sharwell** [comment]
@JoeRobich the linked test run was deleted along with the logs. Resolving as Not Reproducible.
