### ISSUE TITLE
Add document for DocumentationCommentId in wiki

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#34224]
We have a bunch of public APIs around `DocumentationCommentId` that convert symbol to string and vise versa. Those are used by external components like [BannedApiAnalyzer](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzer.cs#L155). However, I couldn't find any documentation for the string format.

Given that this API was made public, we should document the string format and make sure we don't break them moving forward.

**Comment by sharwell** [comment]
I believe this is covered by [
Documentation comments: ID string format (C# Language Specification)](https://github.com/dotnet/csharplang/blob/master/spec/documentation-comments.md#id-string-format).

**Comment by genlu** [comment]
@sharwell Yes! That's exactly what I was looking for. Thanks!
