### ISSUE TITLE
[Regression] Completion gets in the way attempting to line up arguments

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#34237]
This is a regression from Version 15.9.9.

**Version Used**: 
Version 16.0.0 Preview 4.2 [28711.60.d16.0]

**Steps to Reproduce**:

At $, press ENTER and then TAB:
``` C#
String.Equals("foo", "bar", $StringComparison.CurrentCulture)
```

**Expected (15.9):**

``` C#
String.Equals("foo", "bar", 
        StringComparison.CurrentCulture)
```

**Actual (16.0):** 

``` C#
String.Equals("foo", "bar", 
    StringComparisonStringComparison.CurrentCulture)
```

Here's a video of it:

![Completion3](https://user-images.githubusercontent.com/1103906/54586952-b1ba1400-4a72-11e9-98cd-d69bd47c8388.gif)

**Comment by sharwell** [comment]
@ivanbasov is <kbd>Enter</kbd> ever a completion trigger prior to 16.0? Can you describe the impacted scenarios?

**Comment by dpoeschl** [comment]
Note: This only seems to happen when the corresponding parameter is of an enum type.
