### ISSUE TITLE
Option to cause a procedural call to value-returning function to be an error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34258]
<p>A method, e.g. Foo, might be called functionally, in an expression, e.g.:</p><pre>n = Foo(&quot;Banana&quot;) + 1;</pre><p>or it can be called procedurally, e.g.:</p><pre>Foo(&quot;Banana&quot;);</pre><p>C# inherits from C the discarding the result from a procedural call of a value-returning (non-void) function. I come from the Pascal tradition of not permitting this, so whenever I write a value-returning function, I intend it to only ever be called functionally. </p><p>I'd like to be able to set an option to give me a warning or an error for any procedural call to a value-returning function. This would be valuable to me in catching bugs in my code. </p><p>It would be ideal if the option could be set for a whole project or for a specific class. </p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/481735/option-to-cause-a-procedural-call-to-value-returni.html
VSTS ticketId: 813455_
_These are the original issue comments:_

Jane Wu [MSFT] on 3/7/2019, 08:31 PM (11 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by mavasani** [comment]
This is already implemented as IDE0058, which is a hidden diagnostic by default, but you can bump it to a warning/error if you want more visual:

![image](https://user-images.githubusercontent.com/10605811/62494829-35a63b80-b789-11e9-9dea-cf3d9747316a.png)

https://docs.microsoft.com/en-us/visualstudio/ide/reference/unused-values-parameters?view=vs-2019

**Comment by mavasani** [comment]
Note that you need at least VS2019 16.2 builds.

**Comment by mavasani** [comment]
Tagging @kendrahavens

**Comment by mavasani** [comment]
In 16.3, you can also do the same via an [.editorconfig entry](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019) either `dotnet_diagnostic.IDE0058.severity = error` or https://github.com/dotnet/roslyn/blob/00f3a87e02622107a342b804b701807a9d56222c/src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs#L787-L788

@jasonmalinowski Is there any docs documentation on this new editorconfig support?

**Comment by jasonmalinowski** [comment]
I don't think so _yet_, mostly because we hadn't actually shipped a build yet with it on yet.

**Comment by mavasani** [comment]
Marking this as resolved - hopefully the suggestion in https://github.com/dotnet/roslyn/issues/34258#issuecomment-518398014 suffices.
