### ISSUE TITLE
Using `Index` on string created invalid program

### ISSUE THREAD

**Issue by BillWagner** [dotnet/roslyn#34269]
**Version Used**: 

Inside visual studio: 

- Compiler version: '3.0.19.16505 (df5f5d85)'. Language version: preview.

With the dotnet CLI:  

- Compiler version: '3.1.19.15401 (c32ec290)'. Language version: preview.

**Steps to Reproduce**:

Enter the following as your program text:.  This works with a .NET Core 3.0 console application:

```csharp
using System;

namespace InvalidProgram
{
    class Program
    {
        static void Main(string[] args)
        {
            var phrase = "Hello World! Let's mess around with ranges";
            var phraseRange = phrase[6..^6];

            Index m = phraseRange.IndexOf('m');
            Console.WriteLine(m);
            Console.WriteLine(phraseRange[m]);
            Console.WriteLine(phraseRange);
        }
    }
}
```

Run the program.

**Expected Behavior**:

I'd expect it to run correctly with the following output:

```console
13
m
World! Let's mess around with
```

**Actual Behavior**:

This generates an invalid program exception:

```console
Unhandled Exception: System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at InvalidProgram.Program.Main(String[] args)
```

If you change this declaration

```csharp
Index m = phraseRange.IndexOf('m');
```

to an integer:

```csharp
int m = phraseRange.IndexOf('m');
```

The program works correctly.

**Comment by svick** [comment]
This sounds quite similar to https://github.com/dotnet/roslyn/issues/34209.

**Comment by BillWagner** [comment]
Verified the same behavior on Mac with .NET Core preview 3.0

**Comment by briman0094** [comment]
Both this code and my issue over at #34209 are broken on the `mcr.microsoft.com/dotnet/core/sdk:3.0` Docker image, but working on `mcr.microsoft.com/dotnet/core-nightly/sdk:3.0` one.

**Comment by gafter** [comment]
As observed, this is a dup and appears to be fixed.
