### ISSUE TITLE
Regression in async-completion.  'inline description' no longer supported.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#34271]
Async completion undid the work we did to make inline-descriptions supported in Regex completion:

![image](https://user-images.githubusercontent.com/4564579/54647067-6d247d80-4a5e-11e9-8ff1-d81bd0f40bc7.png)

It now looks like:

![image](https://user-images.githubusercontent.com/4564579/54647075-744b8b80-4a5e-11e9-8df2-ad5da5072e2c.png)

This also affects "completion for other namespaces" as we want to use the 'inline description' to specify where the type is coming from.

**Comment by CyrusNajmabadi** [comment]
Tagging @ivanvasov @genlu.

**Comment by CyrusNajmabadi** [comment]
This happened because we switched from using the CustomCommitCompletion type (which does support this) to the new editor Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Data.CompletionItem type (which does not seem to). 

Did this get missed in all the async work?  Unfortunately, we only do tests that check at the inner-roslyn layer, not higher at the UI layer, so this wasn't caught.

**Comment by CyrusNajmabadi** [comment]
tagging @ivanbasov

**Comment by ivanbasov** [comment]
Thank you, @CyrusNajmabadi ! Just discussed a fix with @genlu . He is going to provide a fix for this.

Unfortunately, InlineDescription was added at the same time when the new completion was added: in parallel. No cross merge was done.

**Comment by ivanbasov** [comment]
ModernCompletionTestState.AssertSelectedCompletionItem missed support for inlineDescription
