### ISSUE TITLE
String quotes not added in pairs

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34281]
VSF_TYPE_MARKDOWNIn Console.WriteLine(); when a quote symbol is added in parens the matching quote is not added.
If the last bracket and semicolon is removed the matching quote pair is added.

Regards
Kerry Brown

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/497338/string-quotes-not-added-in-pairs.html
VSTS ticketId: 822937_
_These are the original issue comments:_

Visual Studio Feedback System on 3/18/2019, 11:53 PM (19 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jbrew138** [comment]
I've noticed this behavior as well. Other functions will automatically create a pair of quotes, which is the expected behavior, but only Console.WriteLine() adds a single character instead of a pair.

**Comment by CyrusNajmabadi** [comment]
Can't repro this:
![norepro2](https://user-images.githubusercontent.com/4564579/76171756-1c64d380-614c-11ea-977e-6c7bdcf12d69.gif)
