### ISSUE TITLE
Roslyn should guard all calls to ServiceHub and not FailFast.

### ISSUE THREAD

**Issue by tinaschrepfer** [dotnet/roslyn#34304]
Based on Watson data, we're noticing a number of crashes in VS because Roslyn is making a call to ServiceHub when the pipe is broken.  Based on discussions with @heejaechang, these are the changes that should be made:

* Guard all service hub calls so that failures don't leak to FailFast.
* Check to see if JsonRpc is disposed (as part of package close) before using it or logging NFE.

Sample calls:
FindReferenceMethodsAsync
FindReferenceMethodsAsync
GetReferenceCountAsync
GetFullyQualified
OnGlobalOperationStarted
Initialize
UpdateSolutionStorageLocation

**Comment by CyrusNajmabadi** [comment]
@tmat is this still relevant with all your changes?
