### ISSUE TITLE
IDE0004 Cast is redundant from class to interface only for fields

### ISSUE THREAD

**Issue by Materix** [dotnet/roslyn#34326]
Visual Studio 2017 Version 15.9.9

**Steps to Reproduce**:

```
public class MyContext : DbContext { }

public class Class
{
    private readonly MyContext _context;
    private readonly DbContext _dbContext;

    public Class(MyContext context)
    {
        _dbContext = context;
        _context = context;

        ((IDisposable)_context).Dispose();
        ((IDisposable)_dbContext).Dispose();

        ((IDisposable)context).Dispose();
        DbContext dbContext = _context;
        ((IDisposable)dbContext).Dispose();
    }
}
```

![obraz](https://user-images.githubusercontent.com/6151485/54738940-8cceb980-4bb6-11e9-91ae-f594702a9997.png)

**Expected Behavior**:
Show IDE0004 message for all cast

**Actual Behavior**:
IDE0004 was only shown when casting for fields

**Comment by sharwell** [comment]
@mavasani do you see any reason why we wouldn't want to report these?

**Comment by mavasani** [comment]
I don't recall or see any reason why we would not flag all the cases here.

**Comment by CyrusNajmabadi** [comment]
It's actually a bug that we report these as simplifiable. Consider something as simple as:

```c#
public class DbContext : IDisposable
{
    public void Dispose()
    {
        Console.WriteLine("Base called");
    }
}

public class MyContext : DbContext, IDisposable
{
     void IDisposable.Dispose()
    {
        Console.WriteLine("Derived called");
    }
}

class C
{
    private readonly DbContext _dbContext;

    void Main()
    {
        ((IDisposable)_dbContext).Dispose();
    }
}
```

That .Dispose call could be to the derived type.  But by removing the IDisposable case, we now call intot he base type.
