### ISSUE TITLE
IntelliSense doesn't support C#8 null-coalescing assignment

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34324]
VSF_TYPE_MARKDOWNSay, I have the following code:

```
MemoryStream ms = null;
ms ??= new MemoryStream();
```
When I type &quot;n&quot; (for &quot;new&quot;) after &quot;??= &quot;, I don't get IntelliSense support. Even when I press Ctr+Space, IntelliSense doesn't show up.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/476800/intellisense-doesnt-support-c8-null-coalescing-ass.html
VSTS ticketId: 807912_
_These are the original issue comments:_

Visual Studio Feedback System on 3/4/2019, 08:10 PM (16 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 3/4/2019, 11:30 PM (15 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jcouv** [comment]
Fixed in 16.1p1.
