### ISSUE TITLE
Find All References should allow grouping by type and member

### ISSUE THREAD

**Issue by vatsalyaagrawal** [dotnet/roslyn#34336]
Find All References should allow grouping by type and member - currently, Definition, Project then Path is the closest analog, but grouping by type is more useful than file path and member is also a useful grouping-level for heavily used symbols.

**Comment by sharwell** [comment]
In design review we formed the following proposal:

1. Add a column to Find All References for **Containing Member**
2. Add a new predefined grouping option for **Containing Member** so it's easy to set the new column as the grouping column

@vatsalyaagrawal @jinujoseph can you verify this proposal meets the expectations of users who asked for this feature?

**Comment by mwelsh1118** [comment]
The new column makes sense.

The grouping is not quite what we had in mind. We would like to be able to group by "Project, Containing Type, then Containing Member" or "Project then Containing Type."

**Comment by CyrusNajmabadi** [comment]
Note: FindReferences is a roslyn extensibility point shared by C#/VisualBasic/TypeScript/JavaScript/F#/Xaml.

When making this change ensure that this is done in a manner that does not ties this too specifically to C#/VB.  In other words, it would likely be good to not hardcode in the concept of "containing type/member" (which may not be something exists in all languages), but may be better to allow languages to supply additional 'attributes' that they could then group by.  C#/VB could then add "containing type" and "containing member" as preferred.  Other language could then flexibly add their own attributes that they could be grouped by.

**Comment by chborl** [comment]
As discussed in Design Review this week, I'll add 2 columns, "Containing Type" and "Containing Member" so user will have more flexibility in ordering.
