### ISSUE TITLE
Ctrl+Q does not work once I uninstalled ReSharper and reset my keybindings to default. 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#34362]
**Version Used**: 
Visual Studio 2019 Preview. 

**Steps to Reproduce**:
1. Uninstall ReSharper
2. Set keybindings to default and click reset.  
3. Restart Visual Studio.
4. Ctrl+Q disappears from the search visual studio box and doesn't trigger. 

**Expected Behavior**:
Expect Ctrl+Q to work after uninstalling ReSharper and resetting my keybdindings to default.

**Comment by jinujoseph** [comment]
moved [over](https://devdiv.visualstudio.com/DevDiv/_queries/edit/866680)
