### ISSUE TITLE
Make compiler parameters available from Project in Workspace layer

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#34371]
Specifically, Edit and Continue needs to know the value of `/out` parameter.

This will also address https://devdiv.visualstudio.com/DevDiv/_workitems/edit/826527.

**Comment by tmat** [comment]
@jasonmalinowski @jinujoseph

**Comment by jasonmalinowski** [comment]
@tmat With the E&C work that you're doing, what do you imagine this bug still means?

**Comment by tmat** [comment]
This will be closed by https://github.com/dotnet/roslyn/pull/34809.

**Comment by jasonmalinowski** [comment]
Cool, you can have this bug then!
