### ISSUE TITLE
Review automated tests for formatting between ) and {

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34399]
From https://github.com/dotnet/roslyn/pull/33983#issuecomment-475332589:

> Not caused by #33983, but observed when looking through the test sequences: we may have a test gap covering the formatting at the end of a line, when multiple spaces appear between `)` and `{`, and the user presses enter somewhere in the middle of this. We should verify tests are present for these cases both for using statements and other types of statements that allow braces.

@heejaechang had some ideas for specific test cases to ensure are covered.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
