### ISSUE TITLE
Roslyn (like the native compiler) allows default(StaticType), array of static type

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#344]
The following program shows that the Roslyn compiler (like the native compiler) allows `default(StaticType)` and allows you to create an array of a static type too. All of these break with things that the C# specification mandates. I don't think this could be fixed because that would be a breaking change, though if anyone is doing this accidentally they'd probably like to know about it.

```cs
class Program
{
    static void Main(string[] args)
    {
        object o = default(C);
        object[] x = new [] { default(C) };
    }
}

static class C
{
}
```

**Comment by gafter** [comment]
I do not think we should break compatibility by "fixing" these (except in /features:strict mode). But we should document these in the compiler specification.

**Comment by theoy** [comment]
> I do not think we should break compatibility by "fixing" these (except in /features:strict mode). But we
> should document these in the compiler specification.
>     -- @gafter

:+1:. Good to document. Bad to break. Also good fodder for an analyzer/FxCop.

**Comment by gafter** [comment]
This is now documented at https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/Static%20Type%20Constraints.md

**Comment by gafter** [comment]
@jaredpar Can you please verify that the documents described are now in the Roslyn repository, and then mark this issue as "Verified"?
