### ISSUE TITLE
Brace completion via Tab does not trigger formatting

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34400]
From https://github.com/dotnet/roslyn/pull/33983#issuecomment-475332589:

> Caused by #33983: users who have automatic brace completion enabled *and* use <kbd>Tab</kbd> to complete the closing parentheses could end up in a state where the indentation of the `using (true)` line is incorrect. We don't believe this will cause problems, but if it does we could end up needing to address it in the future.

**Comment by vatsalyaagrawal** [comment]
Design review conclusion:

- we will wait for more customer feedback before changing the behavior
