### ISSUE TITLE
RenameTracking undo session-restoring behavior fails with intervening destructive edits

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#3440]
1. Copy/paste C# code:
   
   ``` C#
   class C { }
   ```
2. Use Rename Tracking to rename `C` to `CC`. Commit the Rename Tracking session.
3. Delete the entire contents of the document.
4. Undo (puts the entire contents of the document back)
5. Undo (puts back to before the rename started)
6. Undo

**Expected**: Tracking session restored and you can see the dotted border around "CC"
**Actual**: No (visible) tracking session available

Discovered while working on #3439. This is happening because we literally restore the old TrackingSession after that 2nd RenameTracking-related undo (in step 6), which contains an ITrackingSpan that's been tracking the original span the entire time, from the beginning, and it has no way to track through the entire file being deleted/restored.

We should instead store the span itself and create a _new_ ITrackingSpan when the session is restored.

**Comment by dpoeschl** [comment]
I don't think this is ```1.0 (stable)``` worthy, as the common case for using the session-restoration is very soon after an initial commit when you want to pick a different name, and it's unlikely that the document will have gone through a destructive edit between the commit and the undo.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
