### ISSUE TITLE
Consolidate generated code checks for code fixes

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34418]
> I see this generated code kind of checks for fixer in arbitary places.. we probably need to discuss and create some kind of central thing? otherwise, this behavior seems hard to make consistent?

_Originally posted by @heejaechang in https://github.com/dotnet/roslyn/pull/32175#discussion_r267858835_

**Comment by heejaechang** [comment]
other related ones https://github.com/dotnet/roslyn/pull/34009

**Comment by heejaechang** [comment]
other related issues - https://github.com/dotnet/roslyn/issues/34011

**Comment by heejaechang** [comment]
basically, we shouldn't change one-off service to another one off service based on the feeling of that day. we should fix all these related issues based on what we want at the end, and create a system so that we get consistent experiences over our product.

**Comment by sharwell** [comment]
@heejaechang this issue was not intended to be related to #34009 or #34011

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
