### ISSUE TITLE
Use a single representation of non-nullable value types in the compiler

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#34412]
```C#
#nullable enable
public class C
{
	public int i;
}
```

For the above code, `FieldSymbol.TypeWithAnnotations` is different for the field `i` between source and metadata. When the `FieldSymbol` is created from source, it has a `TypeWithAnnotations` of `NotAnnotated`. When the `FieldSymbol` is parsed from metadata, it has a `TypeWithAnnotations` of `Oblivious`. This is because we don't emit a `Nullable` attribute for the field, as it's a value type and can never be null. We should make our handling of these consistent between source and metadata, as this will affect the public API.

**Comment by gafter** [comment]
@333fred How would this affect the public API?

**Comment by 333fred** [comment]
@gafter by affecting the declared nullability of the returned `IFieldSymbol` (or potentially other type of symbol). For a type in Source, it'll be `NotAnnotated` explicitly. When parsed from metadata, even in an assembly with `NonNullTypes(true)`, it'll be marked whatever the public name for `Oblivious` is.

**Comment by jcouv** [comment]
FYI @AlekseyTs

**Comment by AlekseyTs** [comment]
I do not think this matters for value types because annotations for them are meaningless.

**Comment by AlekseyTs** [comment]
Note that we can add a compensating code to public API implementation to always return ```Oblivious``` for non-nullable value types even from source. We don't want to do that for internal implementation in order to avoid checking for value types too early.

**Comment by 333fred** [comment]
> always return `Oblivious` for non-nullable value types even from source.

I don't think that's the correct solution. If we want to compensate I'd rather always return `NotNull`.

**Comment by gafter** [comment]
@333fred You mean `NotAnnotated`?

**Comment by 333fred** [comment]
Yes, `NotAnnotated`.

**Comment by jcouv** [comment]
@333fred Is this still an issue?

**Comment by 333fred** [comment]
Yes, this is still an issue.

**Comment by 333fred** [comment]
@cston, this is the metadata issue I was talking about.

In the compiler in general, we should standardize our handling of value types and only use one representation of this. This bug will track that.
