### ISSUE TITLE
Cleanup project only runs on one target framework

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34419]
> have we considered apply clean up on all context for multitargeted projects? like the way @genlu  did for his sync namepsace to folder name stuff?
>
> asking since context is only exposed through editor but not through solution explorer? or should we ask platform team to expose context in code clean up menu in solution explorer?

_Originally posted by @heejaechang in https://github.com/dotnet/roslyn/pull/32175#discussion_r267840181_

> so, this handle all multitarget project case? so, the service itself can handle multi-targetting? @genlu had some complication on sync folder/namespace fix on multi targetting. so might be good person to code review this area?

_Originally posted by @heejaechang in https://github.com/dotnet/roslyn/pull/32175#discussion_r267852007_

**Comment by CyrusNajmabadi** [comment]
Clsoing out due to lack of feedback.
