### ISSUE TITLE
Auto population of lambda expression for delegate assignment

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#34417]
Customer request copying here.

**Version Used**: Visual Studio 2017 and Visual Studio 2019 Preview

**Steps to Reproduce**:

> Useful feature is auto population of lambda expression for delegate assignment. 

> With Resharper, when you type ServicePointManager.ServerCertificateValidationCallback +=

> You get suggestion with (sender, cert, chain, err) => ; Same when you initialize event. 

> Vs2019 preview 3 only suggests named event handler method. It would be very helpful to 

> suggest lambda expression for delegate. meaning when I type “+=” the lambda expression is 

> in the suggestions. Visual studio’s suggestions include a named method while Resharper 

> suggests both the named method and lambda expression.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
