### ISSUE TITLE
Should reachability affect nullability of ref conditionals?

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#34411]
In `(true ? ref notNullableString : ref nullableString) = null;` we warn that the two nullabilities (`ref notNullableString` and `ref nullableString`) don't match. 
Should we also warn about the assignment of `null`, or instead only consider the reachable branch to determine the L-value annotation of the ternary?

Relates to https://github.com/dotnet/roslyn/pull/34323#pullrequestreview-218426166

**Comment by stakx** [comment]
Sounds a bit academic TBH. Why not give a more practical warning about the conditional expression always evaluating to the same branch instead (and combine it with only considering the reachable branch for nullability analysis)? That would appear to be more useful to me as the code's maintainer and give me an incentive to simply remove the unreachable part... ppof! Problem gone. :-)

**Comment by jcouv** [comment]
This special case doesn't seem useful. Closing
