### ISSUE TITLE
"Pull members up to base type" refactoring should shorten type references

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34427]
<p>Currently when I use the &quot;Pull members up to base type&quot; refactoring, the resulting code in the base type has any generated code fully namespaced.</p><p>For example, consider the following code:</p><pre>using System.Collections.Generic;

public class MyClass : IMyInterface
{
    IList&lt;Info&gt; GetInfo();
}</pre><p>Pulling the GetInfo method below up into the interface results in the following code generated in the interface:</p><pre>public interface IMyInterface
{
    System.Collections.Generic.IList&lt;Info&gt; GetInfo();
}</pre><p>This is a trivial example with only one required namespace, it can look a real mess where more namespaces need to be pulled in.</p><p>My suggestion is that the code refactoring should automatically shorten type definitions, adding in using statements as required.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/501399/pull-members-up-to-base-type-refactoring-should-sh.html
VSTS ticketId: 825054_
_These are the original issue comments:_

Jane Wu [MSFT] on 3/22/2019, 02:04 AM (3 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by ryzngard** [comment]
Pull members up now should add usings. 

![image](https://user-images.githubusercontent.com/475144/75293974-285fa580-57dc-11ea-89bc-d69de66c088f.png)
