### ISSUE TITLE
remove double execute command handler pattern we have.

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#34428]
I think we have this pattern

http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/ExtractMethod/AbstractExtractMethodCommandHandler.cs,81

where we get a document and check things like 
> if (!supportsFeatureService.SupportsRefactorings(document))

and then dig in
> return Execute(args.SubjectBuffer, args.TextView, context.OperationContext);

and get a document again to avoid a case where we get 2 different documents in 1 method.

with @dibarbet clean up - https://github.com/dotnet/roslyn/pull/34314

we should be able to clean up those patterns. and make all these checking to be centralized in some system?

**Comment by heejaechang** [comment]
whatever outcome from this - https://github.com/dotnet/roslyn/issues/34418 - should be used in all command handlers.

**Comment by CyrusNajmabadi** [comment]
closing out.
