### ISSUE TITLE
FakeSign build target does not work if there are white spaces in the checkout path

### ISSUE THREAD

**Issue by robinsedlaczek** [dotnet/roslyn#3442]
FakeSign build target does not work if there are white spaces in the checkout path due to a missing quote in file "\Roslyn\build\VSL.Imports.Closed.targets". The the complete solution cannot be build. Adding quotes to the FakeSign tool path fixes the problem. Please see screenshots.

![probleminbuildtarget](https://cloud.githubusercontent.com/assets/2900224/8106705/0fbb1472-1044-11e5-90cc-17d4f0f1884b.png)
![fixwithquote](https://cloud.githubusercontent.com/assets/2900224/8106706/0fbbf5f4-1044-11e5-9c88-542225ab17d9.png)

**Comment by davkean** [comment]
You resolved this with https://github.com/dotnet/roslyn/commit/5385f8f768bf019028045a8e0fb8b7efad396330. :)
