### ISSUE TITLE
strange errors opening  wpf application

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/roslyn#3443]
Hi, I just opened a wpf .net 4.5 application using 2015 rc and opening the source classes I find these errors 

![untitled](https://cloud.githubusercontent.com/assets/127777/8110259/8ba7f728-105b-11e5-866f-03634b434e4e.png)

It's a editor problem, because application compiles with both vs 2013 and 2015

**Comment by Pilchie** [comment]
This is likely the same issue as https://github.com/dotnet/roslyn/issues/1373.  Do you reference a library that is a Portable Class Library?

**Comment by lucamorelli** [comment]
I'm using the SQLite.Net-PCL library

**Comment by Pilchie** [comment]
Thanks - this sounds like a dupe then.  Can you try adding the workaround mentioned in #1373?  
Add:
```XML
<CheckForSystemRuntimeDependency>true</CheckForSystemRuntimeDependency>
```

to the property group at the top of the .csproj where you reference SQLite.Net-PCL?

**Comment by lucamorelli** [comment]
yes, thanks, now seems is working fine.
