### ISSUE TITLE
Incorrect fading for redundant initialization

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34444]
**Version Used**: Visual Studio 2019 RC

**Steps to Reproduce**:

```csharp
object value = null;
value = new object();
```

**Expected Behavior**:

The initializing expression `= null` is faded out.

**Actual Behavior**:

The variable declaration `value` is faded out, and the initializing expression is *not* faded.

**Comment by CyrusNajmabadi** [comment]
@mavasani this was by design iirc?

**Comment by mavasani** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/47784
