### ISSUE TITLE
IncrementalAnalyzerProcessor.GetActiveProject returns null

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34447]
This method should be fixed or removed.

https://github.com/dotnet/roslyn/blob/b28ec8a8fff49553516e6af0123ff0c2dac08f82/src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.IncrementalAnalyzerProcessor.cs#L262-L275

**Comment by CyrusNajmabadi** [comment]
This method no longer exists.
