### ISSUE TITLE
Review InMemoryStorage.Remove for race conditions

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34443]
What happens if a new item is added to `analyzerMap` after the `IsEmpty` check?

https://github.com/dotnet/roslyn/blob/b28ec8a8fff49553516e6af0123ff0c2dac08f82/src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.InMemoryStorage.cs#L50-L55

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this is a problem we should just fix this, or assign to a milestone to do.
