### ISSUE TITLE
AbstractAddImportCodeFixProvider does not support Fix All

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34457]
**Version Used**: Visual Studio 2019 RC

Currently `AbstractAddImportCodeFixProvider` does not support Fix All operations. Two possible ways to support this feature are:

1. Fix All fixes all cases where the resolution is the same (e.g. add `using System` to all documents with an unresolved reference to `Action`)
2. Fix All fixes all unambiguous cases, similar to how @JoeRobich implemented the Fix Imports After Paste operation

**Comment by CyrusNajmabadi** [comment]
@sharwell  can we merge this into one top-level bucket of: here are codefixproviders we should review to determine if they should have fix-all support or not?

**Comment by sharwell** [comment]
@CyrusNajmabadi I don't think it makes sense to merge them.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We don't need backlog issues just documenting these.  If we want to fix these, we can drive an active bug in a real milestone to do so if the value is htere.
