### ISSUE TITLE
AbstractAddSpecificPackageCodeFixProvider does not support Fix All

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34458]
**Version Used**: Visual Studio 2019 RC

Currently `AbstractAddSpecificPackageCodeFixProvider` does not support Fix All operations. It may be possible to implement at least Fix All in Solution.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We don't need backlog issues just documenting these.  If we want to fix these, we can drive an active bug in a real milestone to do so if the value is htere.
