### ISSUE TITLE
IncorrectExitContinueCodeFixProvider does not support Fix All

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34466]
**Version Used**: Visual Studio 2019 RC

Currently `IncorrectExitContinueCodeFixProvider` does not support Fix All operations. This issue tracks designing and implementing Fix All support for this code fix.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We don't need backlog issues just documenting these.  If we want to fix these, we can drive an active bug in a real milestone to do so if the value is htere.
