### ISSUE TITLE
AbstractResolveConflictMarkerCodeFixProvider does not support Fix All

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34461]
**Version Used**: Visual Studio 2019 RC

Fix All support should be added to `AbstractResolveConflictMarkerCodeFixProvider`, with the ability to apply one of the specific resolutions to all conflicts in the Fix All scope.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/50216
