### ISSUE TITLE
AbstractAddAwaitCodeFixProvider does not support Fix All

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34460]
**Version Used**: Visual Studio 2019 RC

Currently `AbstractAddAwaitCodeFixProvider` does not support Fix All operations. This issue tracks the possibility of implementing this support.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We don't need backlog issues just documenting these.  If we want to fix these, we can drive an active bug in a real milestone to do so if the value is htere.
