### ISSUE TITLE
AbstractFullyQualifyCodeFixProvider does not support Fix All

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34465]
**Version Used**: Visual Studio 2019 RC

Currently `AbstractFullyQualifyCodeFixProvider` does not support Fix All operations. Two possible ways to support this feature are:

1. Fix All fixes all cases where the resolution is the same (e.g. add `System.` to all unresolved references to `Action`)
2. Fix All fixes all unambiguous cases, similar to how @JoeRobich implemented the Fix Imports After Paste operation

Related to #34457

**Comment by CyrusNajmabadi** [comment]
Tracked in https://github.com/dotnet/roslyn/issues/66812.
