### ISSUE TITLE
GenerateEnumMemberCodeFixProvider does not support Fix All

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34464]
**Version Used**: Visual Studio 2019 RC

Currently `GenerateEnumMemberCodeFixProvider` does not support Fix All operations. Unlike most code fixes that extend `AbstractGenerateMemberCodeFixProvider`, generation of enum members seems like a reasonable possibility.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We don't need backlog issues just documenting these.  If we want to fix these, we can drive an active bug in a real milestone to do so if the value is htere.
