### ISSUE TITLE
AbstractSpellCheckCodeFixProvider does not support Fix All

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34462]
**Version Used**: Visual Studio 2019 RC

Currently `AbstractSpellCheckCodeFixProvider` does not support Fix All. This feature could be implemented by applying the same solution to the same spelling error in each case where it applies in the Fix All scope.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We don't need backlog issues just documenting these.  If we want to fix these, we can drive an active bug in a real milestone to do so if the value is htere.
