### ISSUE TITLE
Introduce variable is missing or requires highlighting

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#34497]
[Internal feedback]
**Version Used**: Visual Studio 2019

**Description**
>1. The option is almost always missing from the quick fixes menu when I want it.
> 2. The requirement of highlighting code to enable it is counter productive.

**Scenario**:
> 1. I’m writing a method that sends a request, and adds a header to the response before returning it. 
> 2. I write the method call to send the request, which returns can be awaited for an HttpResponseMessage object. 

```csharp
await base.SendAsync(request, cancellationToken);
```
> 3. I would now like to capture the result of this  invocation by introducing a variable. I can highlight the text given above and access the quick fixes menu only to see the following: 

![image](https://user-images.githubusercontent.com/8293542/55042726-1d126180-4ff0-11e9-9655-2ed2dd16bbd4.png)

**Expected Behavior**:
>My expectation, is to see the introduce variable refactoring option when any non-void expression is highlighted. Unfortunately, I rarely see it when I want it, leading me to believe this is not the implementation.
> In my ideal workflow, I don’t have to touch my mouse for any part of writing code. I use the VIM extension and key binds to navigate files and other shortcuts for switching tabs and opening files.

> With ReSharper using the shortcut to introduce a variable refactoring seems to check the current position of the text cursor (caret). In the above example, any of the following cursor locations would correctly introduce a local variable for the HttpResponseMessage return value:
![image](https://user-images.githubusercontent.com/8293542/55042793-6fec1900-4ff0-11e9-8c3d-ca8d18914077.png)

**Comment by thsackos** [comment]
Thanks for the quick response to feedback!

**Comment by ryzngard** [comment]
Design Review: This should be resolved by work from @petrroll coming in 16.3. Improvements have been made to be consistent with refactoring offerings and handle selection better. Please let us know if this doesn't resolve the issue.
