### ISSUE TITLE
VS Visual Basic offers invalid simplification inside "nameof" expression for Keywords

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#34494]
**Version Used**: 
Visual Studio 17 15.9.10
**Steps to Reproduce**:

1. Create simple statement where NameOf is used with a Keyword inside NameOf.
```
Dim NameOfString as String = NameOf([String])
```
2. Above is valid code and NameOfString will be "String"

**Expected Behavior**:
No offer to simplify
**Actual Behavior**:
VS offers and will simplify and remove the []
This causes an error, as the brackets are required

**Comment by Youssef1313** [comment]
I'm getting an error for your example.

![image](https://user-images.githubusercontent.com/31348972/93622513-8f91b100-f9dd-11ea-9bd5-8433bbea158f.png)

Was this allowed in a previous version and now it's not?

To me, the code shouldn't compile and the compile error I'm seeing is expected.
