### ISSUE TITLE
Explicit implementation of generic interface method with 'T?' parameter does not build

### ISSUE THREAD

**Issue by kindermannhubert** [dotnet/roslyn#34508]
**Version Used**: Visual Studio Proffesional 2019 Preview 16.0.0 Preview 4.4

**Steps to Reproduce**:

```C#
interface I
{
    void Foo<T>(T value);
    void Foo<T>(T? value) where T : struct;
}

//works fine
class C1 : I
{
    public void Foo<T>(T value) { }
    public void Foo<T>(T? value) where T : struct { }
}

//several build errors
class C2 : I
{
    void I.Foo<T>(T value) { }

    //error CS0111: Type 'C2' already defines a member called 'I.Foo' with the same parameter types
    void I.Foo<T>(T? value) { }
}
```

Reproducible also in sharplab:
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRKgEwPYDsA2AnqgLYQnAQLIA+AAgAwAEdAjANwCwAUE30wEtcMKmCgBjCEwCSPfkwDec+fzoAWJgDFs2ADwAVAHwAKfUwBuUfHAgBKLt2UqWG7XqOmA/Bas3bT534AdwALKikzECZkGAQ4cRgHeQBfHgC6ACYmAGFWJijZXn4lIuc6AGYXLR0DEzNLazsAwKYAXkMmGBCEbCCmXDh8fAdm1Ur1avc67wa/UedQ8KZI6Nj4mHmVds7u3v7B4YDUx1KWLOysgoCSlonpADo3WtMfRv9Tlu2unr6BoZGTrcNA8nh59DNfE0PoEvrtfgckvxkkA=

**Expected Behavior**: Compiles fine as in previous version (VS 2017).

**Actual Behavior**: Does not compile.

**Comment by YairHalberstadt** [comment]
I can take a look at this.

**Comment by YairHalberstadt** [comment]
Note that if you switch around the order that the interface methods are declared in everything compiles fine:

```csharp
interface I
{
    void Foo<T>(T? value) where T : struct;
    void Foo<T>(T value);
}

class C1 : I
{
    public void Foo<T>(T value) { }
    public void Foo<T>(T? value) where T : struct { }
}

class C2 : I
{
    void I.Foo<T>(T value) { }
    void I.Foo<T>(T? value) { }
}
```
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDs4BstWFiVKABwEsAfU9GCBMKAYwgAIBJAWACgBvL5/5gAEALMwBiAewkAeACoA+ABSyA/MwBuULHAgBKZgHcAFrRazmIZshgI4DGAG4+AkeKlyl5zdr1POAXy4uQQAmZgBhAEYLNi5eTgEhAGYhUUkZBWUNLR19bmZAhJcU13SPZTVvXMMTJGZzS2tbe2Z8wsLgsPCwyw4eZ35XVgA6MsyvHL1WgoHUtlH3ccrJvJmAoA=

The reason for this error is that as a result of Nullable Reference Types, the method `void I.Foo<T>(T? value) { }` is considered to match `void Foo<T>(T value);`, and so the compiler takes the first matching method.

The relevant logic is in ExplicitInterfaceHelper.cs

**Comment by YairHalberstadt** [comment]
I think the correct solution is try to lookup the correct interface implementation first with the TypeCompareKind.IgnoreNullableModifiersForReferenceTypes not set, and then if that fails, try again with it set.

**Comment by YairHalberstadt** [comment]
We also need to deal with a case of a true ambiguity as to which method is being implemented:

```c#
#nullable enable
interface I
{
    void Foo<T>(T? value) where T : class;
    void Foo<T>(T? value) where T : struct;
}

class C2 : I
{
    void I.Foo<T>(T? value) { }
}
```

This should probably be an error, but it's also worth considering if we need an extra language feature to resolve the ambiguity.

**Comment by jcouv** [comment]
This issue identified a compat break from C# 7, in addition to a design question for nullable reference types feature. We're going to discuss with the team this afternoon.

**Comment by yyjdelete** [comment]
#31676?

**Comment by YairHalberstadt** [comment]
@yyjdelete
I don't think so. As far as I can make out that's caused by a completely different issue in the compiler.

**Comment by YairHalberstadt** [comment]
@jcouv
I've spent quite a few hours on this problem yesterday, and have created a PR. The comment explains in detail the problems, and my suggested solution. https://github.com/dotnet/roslyn/pull/34584
I hope you find it helpful.

**Comment by gafter** [comment]
You can use `Nullable<T>` as a workaround in the explicit implementation.

**Comment by gafter** [comment]
The following three issues appear to be related: #31676 #34508 #34583
