### ISSUE TITLE
IDE0004 incorrectly suggested for method with nullable result and conditional operator with default result

### ISSUE THREAD

**Issue by LeroyK** [dotnet/roslyn#34509]
**Version Used**: 
VS2019 15.9.10

**Steps to Reproduce**:

1. Create the following line of code:
```c
static long? TestParse(string val) => long.TryParse(val, out var parseResult) ? (long?)parseResult : default;
```

**Expected Behavior**:
There should not be a suggestion to remove the (long?) cast. Removing the cast will change the  result type of the conditional expression to "long" instead of "long?".

**Actual Behavior**:
"Remove unnecessary cast" is suggested.

Might be the same issue as #29726

**Comment by jasonmalinowski** [comment]
Looking more closely: this might be working with long? only, so this would have nothing to do with nullable?
