### ISSUE TITLE
create roslyn analyzer analyzer checking async method used in RegisterXXXAction.

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#3450]
https://github.com/code-cracker/code-cracker/issues/375

see, the issue above for more detail.

...

basically, it looks like there is people who does this.

        public override void Initialize(AnalysisContext context) =>
            context.RegisterSymbolAction(AnalyzeAsync, SymbolKind.NamedType);

        private async void AnalyzeAsync(SymbolAnalysisContext context)
        {
            if (context.IsGenerated()) return;
            var symbol = (INamedTypeSymbol)context.Symbol;
            if (symbol.TypeKind != TypeKind.Class) return;
            if (!symbol.Interfaces.Any(i => i.SpecialType == SpecialType.System_IDisposable)) return;
            if (symbol.IsSealed && !ContainsUserDefinedFinalizer(symbol)) return;
            if (!ContainsNonPrivateConstructors(symbol)) return;
            var disposeMethod = FindDisposeMethod(symbol);
            if (disposeMethod == null) return;
            var syntaxTree = await disposeMethod.DeclaringSyntaxReferences[0]?.GetSyntaxAsync(context.CancellationToken);

            var statements = ((MethodDeclarationSyntax)syntaxTree)?.Body?.Statements.OfType<ExpressionStatementSyntax>();
            if (statements != null)
            {
                foreach (var statement in statements)
                {
                    var invocation = statement.Expression as InvocationExpressionSyntax;
                    var method = invocation?.Expression as MemberAccessExpressionSyntax;
                    if (method != null && ((IdentifierNameSyntax)method.Expression).Identifier.ToString() == "GC" && method.Name.ToString() == "SuppressFinalize")
                        return;
                }
            }
            context.ReportDiagnostic(Diagnostic.Create(Rule, disposeMethod.Locations[0], symbol.Name));
        }

**Comment by mavasani** [comment]
Don't we already have a compiler diagnostic for async void methods?
/cc @gafter

**Comment by srivatsn** [comment]
Ported to https://github.com/dotnet/roslyn-analyzers/issues/212, since the codeanalysis analyzers have moved to dotnet/roslyn-analyzers
