### ISSUE TITLE
VB: Indenting of method parameters is broken inside lambda methods.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#34511]
**Version Used**: 

Visual Studio Community 2017 v15.8.5

**Steps to Reproduce**:

Consider the following code:

```vb
  Public Sub TestIndenting()
    Const arg1 As String = "{0} {1}"
    Const arg2 As String = "hello"
    Const arg3 As String = "world"

    Console.WriteLine(arg1, arg2, arg3)

    Dim lambda =
        Sub()
          Console.WriteLine(arg1, arg2, arg3)
        End Sub

    Console.ReadLine()
  End Sub
```

We want to take the `Console.WriteLine` method calls and move the paramaters `arg1` and `arg2` and `arg3` to the next line so the code is ultimately formatted like this:

```vb
    Console.WriteLine(
      arg1, arg2, arg3
    )
```

The first step is to position the caret before `arg1` and press Enter so all the arguments move to the next line. Furthermore they should automatically be indented so they start a few characters into the word `Console`. When doing this with the first `Console.WriteLine` method call, it works as expected and produces this intermediate result:

```vb
    Console.WriteLine(
      arg1, arg2, arg3)
```

However, if you try the same thing for the second `Console.WriteLine` method call inside the lambda, the indentation is NOT done and `arg1` is aligned with the beginning of the word `Console`. You end up with this:

```vb
          Console.WriteLine(
          arg1, arg2, arg3)
```

Visually the differences look like this:

![vs_lambda_indenting](https://user-images.githubusercontent.com/20465797/55095134-ae550700-50c8-11e9-991c-54276b56bd1e.png)

**Expected Behavior**:

The indentation behaviour should be identical regardless of where the method calls happen. In fact after some extra testing, this seems to affect other elements too, not just method calls. For example indentation is broken in the same way for array literals as well if done inside the lambda:

![vs_lambda_indenting2](https://user-images.githubusercontent.com/20465797/55095536-59fe5700-50c9-11e9-9064-3032417c3d35.png)

...same thing happens when pressing Enter to move the right side of an assignment statement to the next line:

![vs_lambda_indenting3](https://user-images.githubusercontent.com/20465797/55095900-fe809900-50c9-11e9-8bcf-499cce7b826a.png)

**Comment by CyrusNajmabadi** [comment]
We are not likely to change to vb formatting due to high risk.
