### ISSUE TITLE
VB wrong codespit for a nested class that (so far) lacks End Class

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3452]
This is what I've written:
![inherit1](https://cloud.githubusercontent.com/assets/3316258/8117116/ce70ef5e-103a-11e5-8d69-54d122178457.png)
I've just finishing typing the declaration of the nested class `Class C : Inherits A` and my caret is at the end of the line. I press enter.

WHAT I EXPECT: it should spit out stubs for all MustOverride members of A inside class C, before the `End Class`

WHAT I GET: Look at the picture below. It actually spits out the `End Class`, followed by the MustOverride members. This is wrong!

![inherit2](https://cloud.githubusercontent.com/assets/3316258/8117123/d07ff29a-103a-11e5-97a9-db7c5d202c6e.png)

**Comment by AdamSpeight2008** [comment]
@Pilchie @ljw1004 
What version are you using? I've tried it in version `(00269-30000-00001-AA469)`
VS2015 `Version.14.0.22823.1.D14REL`
and it works as you would expect.

**Comment by ljw1004** [comment]
I'm using VS2015 RC, which has the same `Version.14.0.22823.1.D14Rel` string. But under Help>About it shows `Visual Basic 2015 RC 00269-3000-00001-AA327`

Here's an animated GIF showing the repro:
![untitled](https://cloud.githubusercontent.com/assets/3316258/8135131/a9f7c544-10e9-11e5-8970-a136ff5a03e7.gif)

**Comment by AdamSpeight2008** [comment]
@ljw1004  This is what I see.
![vb15rc_00](https://cloud.githubusercontent.com/assets/900107/8135544/f0cdcd9c-112f-11e5-89e5-feeb705f783a.gif)

**Comment by ljw1004** [comment]
@AdamSpeight2008 you're not following my repro. In your video you already have the "End Class" for C. In my video I don't, because I haven't yet hit Enter on the line that declares class C.

**Comment by AdamSpeight2008** [comment]
Least we know a cases where it does and doesn't work.

**Comment by Pilchie** [comment]
I can repro this with Enter.

**Comment by CyrusNajmabadi** [comment]
Closing this as we're not changing these vb experiences.
