### ISSUE TITLE
Make sure we can build shipping RTM Roslyn bits with the shipping RTM product

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#3453]
This is important for multiple reasons:
1. So that community can build it with a released product
2. We can service it ( if needed) without running the risk of not finding an internal build that we used to build Roslyn

**Comment by ManishJayaswal** [comment]
@mattscheffer @tmeschter FYI - we would need to do a baseline update for this.

**Comment by tannergooding** [comment]
@ManishJayaswal Confirmed as Working.
