### ISSUE TITLE
Give suggestion or warning on C# dependency injections

### ISSUE THREAD

**Issue by Anduin2017** [dotnet/roslyn#34533]
**Version Used**: 

>Sorry I did not find how to get my version but I am using the latest Visual Studio 2017(15.9.10)

**Steps to Reproduce**:

While I was coding on an ASP.NET Core project, and I need some service in my action, like `_tokenManager`, I have to add a new dependency injection, like this:

![image](https://user-images.githubusercontent.com/19531547/55130454-49e48700-515e-11e9-8896-2fbfc3dfc707.png)

Adding a new dependency for a controller takes me at least 3 lines of code so it was not easy. When I need several dependencies it will cost me lots of time.

BTW, while I was changing my code, some dependency may not be necessary and shall be removed. I have to check those dependencies one by one to make sure each of then is necessary. So Why can't Visual Studio automatically add those dependencies when I try to use them and suggest me to remove those not necessary?

**Expected Behavior**:

Give me warnign or delete useless dependency or suggestions to add dependency

**Actual Behavior**:

Nothing happened.

**Comment by Joe4evr** [comment]
> Give me [...] suggestions to add dependency

This is already built into the Quick Fix/Ctrl+. menu:
![image](https://user-images.githubusercontent.com/1058562/55160366-72bb4b00-5163-11e9-9576-188fa7b5ca45.png)

**Comment by CyrusNajmabadi** [comment]
>  and suggest me to remove those not necessary?

How do you know if it's necessary or not?

**Comment by Anduin2017** [comment]
> > and suggest me to remove those not necessary?

> How do you know if it's necessary or not?

@CyrusNajmabadi If one dependency was injected but was not referenced.

**Comment by CyrusNajmabadi** [comment]
The IDE already grays out unreferenced private fields:

![image](https://user-images.githubusercontent.com/4564579/55207221-89c76080-5196-11e9-9be6-218954934d70.png)

It sounds like these features have already been added :)

**Comment by Anduin2017** [comment]
Ok. Thanks! @CyrusNajmabadi
