### ISSUE TITLE
Remove _Dependency once StreamJsonRpc adds a build target for net472

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#34558]
currently src\Setup\DevDivInsertionFiles\DevDivInsertionFiles.csproj contains following

```
      <_Dependency Remove="Nerdbank.Streams"/>
      <_Dependency Remove="System.IO.Pipelines"/>
      <_Dependency Remove="System.ValueTuple"/>
```

because StreamJsonRpc supports 472 and missing build target for it. once build target is added, we should remove the dependencies.

**Comment by sharwell** [comment]
😕 It looks like StreamJsonRpc already supports net472:
https://github.com/Microsoft/vs-streamjsonrpc/blob/62d81cd2fb23db91c9c0737859564c1d0b96e906/src/StreamJsonRpc/StreamJsonRpc.csproj#L3

**Comment by AArnott** [comment]
Yes, a net472 targeted was added in 2.0.167.
