### ISSUE TITLE
NuGet packages don't need net45 folder anymore

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#3455]
The packages for the layers where we eliminated the .Desktop.dll no longer need to have a net45 folder.

**Comment by agocke** [comment]
I've just added this to the CR for #572.

**Comment by agocke** [comment]
Created CR3455 internally for this.

**Comment by davkean** [comment]
Is this resolved?

**Comment by davkean** [comment]
I believe this has been fixed, please reopen if I'm mistaken.

**Comment by Pilchie** [comment]
No, it's still there in the .nuspecs.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #37](https://github.com/dotnet/roslyn-sdk/issues/37) via [**ZenHub**](https://www.zenhub.com/)
