### ISSUE TITLE
Please add the feature to click a #endregion pragma, so then jumps to the corresponding #region pragma.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34554]
<p>As the title, would you please add the feature to click a #endregion pragma, so then jumps to the corresponding #region pragma?</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/505119/please-add-the-feature-to-click-a-endregion-pragma.html
VSTS ticketId: 827454_
_These are the original issue comments:_

Jane Wu [MSFT] on 3/26/2019, 01:25 AM (2 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
You can use `ctrl-]` to do this.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is already supported.
