### ISSUE TITLE
use JsonRpcEx in ServiceHubRemoteHostClient

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#34555]
ServiceHubRemoteHostClient has 1 JsonRpc connection which is the master connection. 

this controls the lifetime of our OOP process. and it is used to communicate host related states such as telemetry session, UI locale, global operation states, host's persistent storage location and etc.

this one uses JsonRpc as it is.

we also have JsonRpcEx designed to be used as a base of all service calls. this is the connection (and pooled) roslyn features such as code lens, FAR, navigate to, diagnostics and etc get and use and throw away. so it has all kind of error handling code like logging, NFW and info bar to handle service failures.

we should refactor JsonRpcEx so that we can use this as a base for both places.

**Comment by CyrusNajmabadi** [comment]
@tmat is there anything ew need to do here now?

**Comment by tmat** [comment]
Done.
