### ISSUE TITLE
SymbolFinder: FindCallersAsync and FindReferencesAsync return symbol objects but not their associated Compilation

### ISSUE THREAD

**Issue by Stevie-O** [dotnet/roslyn#34562]
**Version Used**: 

Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a 
Microsoft.CodeAnalysis, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 
Microsoft.CodeAnalysis.Workspaces, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 
Microsoft.CodeAnalysis.CSharp.Workspaces, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 
Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 
Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a 

**Expected Behavior**:

I would expect the API to give me everything I need in order to work correctly.

**Actual Behavior**:

It doesn't.  Or, if it does, then the documentation needs to be updated to make it clear just how it's meant to work.
 
The FAQ (https://github.com/dotnet/roslyn/wiki/FAQ) states repeatedly: "Comparing symbols from different compilations has undefined results."  I'm going to assume that, keeping in the spirit of C#, this actually merely means "the return value is meaningless", and not that the results are truly undefined (e.g. format drive, unring bell, nasal demons.)

The discussion on https://github.com/dotnet/roslyn/issues/26347, while concerned with SyntaxTree objects, further supports this idea: if you're dealing with syntax trees, semantic models, and symbols, you'd better keep track of which Compilation you used.

SymbolFinder's FindReferencesAsync (and FindCallersAsync, which is built atop it) throws this idea out the window by generating Compilations for each project in the solution, and returning symbols from those Compilations all in one big list, without bothering to clarify which is which.

If Project.GetCompilationAsync were idempotent -- which I don't see any documented guarantees, although the current implementation appears to work that way -- then for FindReferencesAsync, for the *caller* side, it would be possible to traverse ReferencedSymbol->ReferencedLocation->Document->Project->Compilation (However, there is still no counterpart for ReferencedSymbol.Definition.)
There is hope at all for FindCallersAsync: it remaps each ReferencedLocation to a Location, for which there appears to be no path back.

The result is that trying to do any sort of sophisticated cross-project analysis (in the specific case that tripped me up here, it's static call graph anlysis) is either difficult or impossible, because, because there's no reliable way to "jump" to the correct Compilation in order to be able to compare e.g. the SemanticModel's data type for an expression to the declaring type of a calling/called method in order to see if one is a base class of the other.

**Comment by CyrusNajmabadi** [comment]
> If Project.GetCompilationAsync were idempotent -- which I don't see any documented guarantees

It is guaranteed.  More specifically, if anyone is holding onto anything that could reach the Compilation of Project.GetCompilationAsync, then any calls at teh same time to Project.GetCompilationAsync will return the same compilation.

But differently, you could not observe the compilations being different.

--

In practice, different calls on the same Project to GetCompilationAsync can return different Compilation instances.  There's just no way to observe that's the case.  That's because if someone is holding onto an instance, we'll always return that instance.  We only return a new instance if the old one was actually GCed.

**Comment by CyrusNajmabadi** [comment]
> SymbolFinder: FindCallersAsync and FindReferencesAsync return symbol objects but not their associated Compilation

I don't understand waht that means.  FindReferencesAsync returns a ReferencedSymbol.  And that returns `ReferenceLocation`s.  These give you the Document where the reference was found.  And given that Document, you know the Project (and thus the Compilation) where the reference exists.

**Comment by Stevie-O** [comment]
> > If Project.GetCompilationAsync were idempotent -- which I don't see any documented guarantees

> It is guaranteed. 

Where is that guarantee documented?

> In practice, different calls on the same Project to GetCompilationAsync can return different Compilation instances. There's just no way to observe that's the case. That's because if someone is holding onto an instance, we'll always return that instance. We only return a new instance if the old one was actually GCed.

Unless a Symbol has an internal reference to the associated Compilation, then this is possible:

1. FindReferencesAsync calls GetCompilation for each project and constructs the result set
2. (GC runs. There are no more references to the Compilation instances, so they get GCed)
3. Calls to get the project compilation returns a new object, as you previously stated

This quirk is easy to work around, of course; before using SymbolFinder, simply call GetCompilation on every project in the solution and save them all off somewhere, preventing them from becoming eligible for collection.  But that's the sort of "Gotcha!" that needs to be clearly documented.

> I don't understand waht that means. FindReferencesAsync returns a ReferencedSymbol. And that returns ReferenceLocations. These give you the Document where the reference was found. And given that Document, you know the Project (and thus the Compilation) where the reference exists.

Firstly, that only covers the ReferenceLocations. A ReferencedSymbol also has a "Definition" property of type `Microsoft.CodeAnalysis.ISymbol`, which means it comes from a compilation -- which one?

Secondly, that only holds for FindReferencesAsync. FindCallersAsync doesn't return ReferenceLocations; it returns Locations.

**Comment by CyrusNajmabadi** [comment]
>Where is that guarantee documented?

No clue.  it's just how roslyn works.  Several entities in the system have these invariants.  If the docs are insufficient, we should likely beef it up.

> Firstly, that only covers the ReferenceLocations. A ReferencedSymbol also has a "Definition" property of type Microsoft.CodeAnalysis.ISymbol, which means it comes from a compilation -- which one?

It may not come from a compilation at all.  For example, it may be just a metadata symbol.  Your question doesn't actually have a sound answer because it's not necessarily the case that a symbol needs to be part of any Compilation at all (indeed, it can be part of *many* compilations).

>Secondly, that only holds for FindReferencesAsync. FindCallersAsync doesn't return ReferenceLocations; it returns Locations.

Yeah, i have no clue why it did that.  That said, any of those Locations will have SyntaxTrees. You can then call Solution.GetDocument(SyntaxTree) to find the Document corresponding to that tree.

**Comment by CyrusNajmabadi** [comment]
> Unless a Symbol has an internal reference to the associated Compilation, then this is possible:

Source symbols definitely have a reference to an associated compilation.  It happens by virtue of them having an ISourceAssemblySymbol, which exposes hte owning compilation.  For metadata symbols this is not the case (for the reason i listed above).  That's why i'm uncertain about this issue.  It makes me feel as if something is not necessarily being done properly on your end.

**Comment by Stevie-O** [comment]
> Yeah, i have no clue why it did that. That said, any of those Locations will have SyntaxTrees. You can then call Solution.GetDocument(SyntaxTree) to find the Document corresponding to that tree.

Oh, so *that's* how I can get from a SyntaxTree back to a Compilation!

> It may not come from a compilation at all. For example, it may be just a metadata symbol. Your question doesn't actually have a sound answer because it's not necessarily the case that a symbol needs to be part of any Compilation at all (indeed, it can be part of _many_ compilations).

There is a phrase that is repeated multiple times in the FAQ -- "Comparing symbols from different compilations has undefined results".  If a symbol can come from multiple compilations, then this phrase is nonsensical.

Based on the conversation from issue #34568, it sounds like my main problem is that I'm using FindCallersAsync, which is braindead.

**Comment by CyrusNajmabadi** [comment]
> There is a phrase that is repeated multiple times in the FAQ -- "Comparing symbols from different compilations has undefined results". If a symbol can come from multiple compilations, then this phrase is nonsensical.

Yup.  You are indeed in a rough spot there :)  

In general, the IDE addresses thsi by having its own symbol comparer which implements a reasonably understandable set of semantics that works for many different scenarios.  This is necessary, for example, so one can do reasonable things like "find references on a VB symbol that may end up being referenced by C# projects" (and vice versa).  

As the compiler will not help here, the onus is shifted outwards for tooling to decide what semantics of equality are wanted.

> Based on the conversation from issue #34568, it sounds like my main problem is that I'm using FindCallersAsync, which is braindead.

Quite possibly.

**Comment by Stevie-O** [comment]
> As the compiler will not help here, the onus is shifted outwards for tooling to decide what semantics of equality are wanted.

Well, for what I want, there is a well-defined measure of equality: "if source symbol Sa is defined in project Pa, then inside a project Pb that references Pa, a symbol Sb is equal to Sa if and only if Sb is the corresponding metadata symbol from Pa's assembly."

**Comment by Stevie-O** [comment]
> > Where is that guarantee documented?
> 
> No clue. it's just how roslyn works. Several entities in the system have these invariants. If the docs are insufficient, we should likely beef it up.

Apparently I was too tired last night to call this out -- if that's "just how Roslyn works", then that's an implementation detail, which is the _opposite_ of guaranteed.

**Comment by CyrusNajmabadi** [comment]
> a symbol Sb is equal to Sa if and only if Sb is the corresponding metadata symbol from Pa's assembly."

Even asking that question is non trivial.  For example, retargeting makes that complex.  As does things like having one project be defined against Core and one against Standard.  We've had our own bugs here about these types of scenarios not returning results that people expect due to how this is all interpretted.

**Comment by CyrusNajmabadi** [comment]
> Apparently I was too tired last night to call this out -- if that's "just how Roslyn works", then that's an implementation detail, which is the opposite of guaranteed.

Shrug.  Feel free to file a doc bug on this.  This behavior can't change, and it's how we explicitly designed it to work from the beginning (With tons of code taking a dependency on this).  If the docs don't call this out, it would be worth doing so.  So feel free to either file issue, or open PR yourself to expand on this area.  Thanks! :)
