### ISSUE TITLE
Workspaces NuGet Packages claim to work on .Net 4.5, but require .Net 4.5.2

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#3456]

**Comment by agocke** [comment]
@ManishJayaswal This looks like something we should fix ASAP, are we assigning it out?

**Comment by ManishJayaswal** [comment]
@tmeschter @amcasey FYI

**Comment by agocke** [comment]
Moving to 1.1. We need more time to do this change properly.

**Comment by agocke** [comment]
Not going to fix this. We'll redo the packages for 2.0
