### ISSUE TITLE
Unexpected value 'TypeArguments' of type 'Microsoft.CodeAnalysis.VisualBasic.BoundKind'

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34589]
**Version Used**: f34e1ca35bfaa0c9bf378d91a4ed5e211fd5f458

**Steps to Reproduce**:

1. Check out dotnet/roslyn@f34e1ca35bfaa0c9bf378d91a4ed5e211fd5f458
1. Check out sharwell/roslyn-analyzers@2fab8946033a3369dde57a499a8163af7469e77f next to **roslyn**
1. Open **RoslynAnalyzers.sln**, set the configuration to **Release**, and build everything in the solution folder **Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers**
1. Open **Roslyn.sln**
1. Set **AnalyzerRunner** as the startup project
1. Set the configuration to **Debug**
1. Add the following to **launchProperties.json**:

    ```json
    "Microsoft.CodeAnalysis.CSharp.PerformanceSensitiveAnalyzers Analyzers": {
      "commandName": "Project",
      "commandLineArgs": "$(SolutionDir)..\\roslyn-analyzers\\artifacts\\bin\\Microsoft.CodeAnalysis.CSharp.PerformanceSensitiveAnalyzers\\Release\\netstandard1.3\\ $(SolutionDir)Roslyn.sln /concurrent /stats /log PerformanceSensitive-IOperation.log"
    },
    ```

1. Launch the profile created in the previous step

**Expected Behavior**:

No assertion.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/1408396/55243589-8ae7a480-520d-11e9-85b7-10bbc4a951d1.png)

**Comment by sharwell** [comment]
Just hit this again in ServiceHub.RoslynCodeAnalysisService.exe

**Comment by 333fred** [comment]
This issue is a bit older than https://github.com/dotnet/roslyn/issues/45382, but as that was ported from DevCommunity and this was not, I'm going to close it as a dup. Will link the repro steps from that issue.
