### ISSUE TITLE
SymbolFinder.FindImplementedInterfaceMembersAsync documentation is confusing and inaccurate

### ISSUE THREAD

**Issue by Stevie-O** [dotnet/roslyn#34588]
The documentation for `SymbolFinder.FindImplementedInterfaceMembersAsync` is sparse, but the summary is:
> Find symbols for declarations that implement members of the specified interface symbol

That's not what it does.  What it does is:

> Find interface members that the specified symbol implements.

As an added bonus, if you actually pass the symbol for an interface, you get a NullReferenceException (presumably when the code tries to use `symbol.ContainingType.TypeKind`.)

**Comment by CyrusNajmabadi** [comment]
> That's not what it does. What it does is:
>    Find interface members that the specified symbol implements.

Right, as per it's name.  It "Finds" the "Implemented Interface Members" of the current symbol you're on.

**Comment by CyrusNajmabadi** [comment]
>documentation is confusing and inaccurate

Feel free to submit a PR that improves things here.  Thanks!

**Comment by CyrusNajmabadi** [comment]
No movement by customer.  Closing out as by design.
