### ISSUE TITLE
Incorrect precedence of += operator

### ISSUE THREAD

**Issue by nec4b** [dotnet/roslyn#34582]
**Version Used**: 2.10.0.0

**Steps to Reproduce**:

```
1. int i = 10;
2. i += i++ + ++i;
3. Console.Write(i.ToString());
```

**Expected Behavior**:
_i_ should be 34 because the operator _+=_ should be evaluated last (precedence rules)

**Actual Behavior**:
_i_ equals 32

**Comment by YairHalberstadt** [comment]
32 is correct
This can be transformed as follows
```csharp
i += i++ + ++i;

// is equivalent to

i = (i + (i++ + ++i));

// is equivalent to

temp = i;
i = i + 1;
i = i + 1;
i = (i + (temp + i));
i = (12 + (10 + 12));
i = 32;
```

**Comment by nec4b** [comment]
Unfortunately this transformation is incorrect. You can not transform the expression the way you did, because _+=_ has the lowest precedence and should be therefore executed last. The Visual Studio C++ compiler does this the right way. The answer should be 34 and not 32.

**Comment by YairHalberstadt** [comment]
I am doing it last!

How do you transform it?

**Comment by nec4b** [comment]
```
i = (i++) + (++i) + i;
i= 10 + 12 + 12;
i = 34;
```

or step by step

```
a = i++ = 10++ = 10; i = 11
b = ++i = ++11 = 12; i = 12
c = i = 12

i = a + b + c = 10 + 12 + 12 = 34
```

It is important to remember that both operators _i++_ and _++i_ change the value of the variable _i_ in place (memory location). In other words these operations have side effects.

**Comment by sharwell** [comment]
I also got 32.

```
var temp = i; // read value of LHS of +=
var addedLeft = i; // 10
i = i + 1; // i++
i = i + 1; // ++i
var addedRight = i; // 12
var added = addedLeft + addedRight; // 22
i = temp + added; // 32
```

**Comment by YairHalberstadt** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/addition-assignment-operator

An expression using the `+=` operator, such as `x += y` is equivalent to `x = x + y` except that x is only evaluated once.

```csharp
int i = 10;
i = i + (i++ + ++i);
Console.Write(i.ToString()); //prints 32
```

https://sharplab.io/#v2:C4LgTgrgdgPgAgBgARwIwG4CwAoOBmFAJiQGEAbAQwGcqcBvHJJ5p/FVANhQBYkBZCgEsoACjQIA2gF0kFMAHMqASkYtmDbGq1JhwHUgC8SVAiybtLQYf0BqJCME27zm4KVmLLEgHsoVb2QApgB0AOpggsCBDsEAKt4AysARUPIiSu6qWgC+ONlAA===

**Comment by nec4b** [comment]
```
int i = 10;
i = (i++ + ++i) + i; // This is the correct way. Precedence matters. += has the lowest precedence
Console.Write(i.ToString()); // now it prints 34
```

**Comment by YairHalberstadt** [comment]
@nec4b
That's not what the docs say. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/addition-assignment-operator

**Comment by sharwell** [comment]
@nec4b This is not correct. But I've been in the same situation before so I [completely understand](https://twitter.com/samharwell/status/539796073946963968) how it seems like things should be one way but some other little detail comes into play and turns things on its head.

In this case, there happens to be an explicit example in the C# Language Specification under [Compound Operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#compound-assignment) showing the order. Here's a screenshot of the section:

![image](https://user-images.githubusercontent.com/1408396/55233986-16eed180-51f8-11e9-8325-6ecccd260efa.png)

**Comment by nec4b** [comment]
I'm not disputing that `x += y` equals `x = x+ y`. I'm disputing that `x += y + z` equals `x = x + y +z`, which it does not. The docs says that first `y + z `should be evaluated and than the resulting expression `x += result_of(y + z)` should be evaluated.

Combine:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/

and

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/addition-assignment-operator

@sharwell i'm not a native english speaker but it loks to me that your screenshot confirms what i'm saying.

It maybe is so that c# has some specific different rules about this type of evaluation order than c++ or c, but i haven't seen them so far.

**Comment by nec4b** [comment]
Also if c# compiler is doing it correctly, it means that += operator is not really an operator that has a precedence but only some sort of macro transformation. If that is the case, i can not think of any situation where it would require precedence order. Hence it is either a macro transformation or an operator with a precedence, it can't be both. Or I'm i mistaken?

**Comment by gafter** [comment]
> The Visual Studio C++ compiler does this the right way.

The C++ language makes the behavior undefined because there are multiple writes to the same variable between sequence points.  The C# language defines the behavior precisely.

@nec4b You are mistaken.  This is all based on well-defined precedence rules, not a macro transformation.  Java behaves precisely the same way that C# does.

**Comment by gafter** [comment]
See also https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgDQwgJwUA+AAgAwAELAjANwCwAKCEUoAWxQkMEDgBUUMIQG8hHNVwDMXAExduAdlXqVg9Wc16AbFwAsHALJQcFABQ82AbQC6HKAgDmyACURuYcJgCQUc4wHDgcALwc3GwCglER8QDUSThZWRwF+ThpGTwAnC44QaVRQhnxSSm1EQAKADZwyACiAI5wUO3ILkhgcdQcLkGJAHwcHV0uU7PzAPbIMGA4AB4LyHsjEGPVE8sJc62jO3sHo3FBDy0VVTWh5gC+9RFfPNYx850ev1BsM7v8cBMWABWAA8MTmCBw/gAFjAQukIpFohRYqt2gATABqgzgMlyLX+iJRMAAElAKPiAMo4fFkjhU1FTCk4jgUCAAd2JnTZeKJJJkBQ5tPpTJZEApiV5AqFpKe+iVgvFtU+GJ+3D+PIO0LhOLm7SOMEhsPh7KRqPRUSxmR57UV5rAMC5X2dsQQiqlXoxERY6tdku1Xz1BtirXWm2ugNuRziPOqXyd/1FKrZJW9/z5muFiqz4sKyQVSQL2bVHBLwojuoxvxTMauu0TgMOx1TDsxeZ5ddJitzQfzytLSUHEvLecVVa13pDGurXx1ER17yAA= for a verification of the intended behavior.
