### ISSUE TITLE
Review IDE for switch expression precedence change

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#34593]
In https://github.com/dotnet/roslyn/pull/34481 we changed the precedence of the switch expression from "relational" (like <) to a new precedence level just looser than unary.  It is possible that some IDE features may need to be adjusted as a result.  Please review and make any necessary adjustments.

See also https://github.com/dotnet/roslyn/pull/34481#issuecomment-477234403

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing out.  No changes needed here afaict.
