### ISSUE TITLE
UninitializedFieldWalker should be done inside DefiniteAssignment

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#34598]
Per @gafter's comments on https://github.com/dotnet/roslyn/pull/34316

> This code should be integrated into the definite assignment pass. There is no need for the compiler to repeat all that work. Nearly the same thing is done for the fields of a struct.

and

> This only performs the analysis on the "fall through" path. You also need to perform the analysis on each return statement (a list of which are available in "result"). When a return statement offends, the diagnostic should point to the return statement.

**Comment by RikkiGibson** [comment]
This requires definite assignment analysis (or whatever pass we judge most appropriate) to start running on synthesized methods (i.e. default constructors).

**Comment by RikkiGibson** [comment]
We are instead folding the UninitializedFieldsWalker into NullableWalker
