### ISSUE TITLE
Support "reabstraction" in an interface

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#34591]
On 2019-03-29 the LDM decided to support "reabstraction" in interfaces.  That needs to be implemented.

``` c#
interface I1
{
    void M() {}
}
interface I2 : I1
{
    void I1.M(); // I1.M is abstract in I2 and must be implemented in a derived type
}
```

**Comment by jcouv** [comment]
@AlekseyTs Can we close this now? I think it was fixed by https://github.com/dotnet/roslyn/pull/35756

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/35756 (with a change in syntax, requiring `abstract` on the abstract implementation).
