### ISSUE TITLE
Improve analysis or codegen around scenarios where `_field = null!` is required

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#34599]
In CoreFX, it is not uncommon for us to provide static factory methods or to initialize fields via property setters. If you enable the nullable feature, the compiler will then complain that a given field is not definitely null.

The workaround for this is to currently explicitly set: `_field = null!` and keep the field non-nullable. However, this results in us double-initializing various fields and raises some concerns around regressing perf.

It would be beneficial if the compiler could either improve the codegen here, such as by eliding the assignment in the case of `string _field = null!` (for reference types) or if the analysis could be improved such that this wasn't required in the first place (would be beneficial for value types, where the above isn't possible).

**Comment by gafter** [comment]
There isn’t an issue for value types.  The compiler already requires you to assign all of the fields of a struct in the constructor.

**Comment by stephentoub** [comment]
Is there actually anything to do here?  Seems like the compiler already removes these.
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDk4BstWFiAEQHsBzMY4gEwBoYQBLLAHwAEAGAAlYEYBuALAAoYawDM3AEycAwgB4AKgD5OAb2GdNnAA4IGAN1gROCzgH0YPTgF5OVCGCjYYgoVp17DMY8WAArCABjGHNiK1sAO2wsV3ddAyNOBgiQswZwznZYrQ0teK9jUwtJbM18xN8A4NCS3LLPROTUhlqhAF8gA=

**Comment by gafter** [comment]
@tannergooding I think there is no issue here, so I'm closing.  Please let me know if I have that wrong.
