### ISSUE TITLE
Async Completion - Ctrl+Space isn't filtering the list (when non-unique)

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#34601]
**Version Used**: 28725.219.d16.0stg

**Steps to Reproduce**:

1. Paste C# code:

```C#
class C
{
    void Method()
    {
        Me$$
    }
}

```

2. Delete the `$$`, place your caret there, and press Ctrl+Space

**Expected Behavior**: As per 15.9, a filtered list (only `MemberwiseClone` and `Method`, and backspacing / typing further brings things back into the list).

**Actual Behavior**: The list is initially unfiltered and stays unfiltered (it's acting like Ctrl+J in that respect). But if there's a unique item at the time of Ctrl+Space, it does complete it automatically, so it's not like the two triggers are completely confused.

**Comment by dpoeschl** [comment]
Thanks for the report @AmadeusW 

@ivanbasov I took a very quick look but couldn't figure out where/when this went wrong. Can you take a look?

FYI @jinujoseph

**Comment by sharwell** [comment]
I don't necessarily agree with the behavior in 15.9, but this is an unintentional change so I marked it as **Regression**.
