### ISSUE TITLE
C# Access Modifiers BUG? Or i do not know C#?

### ISSUE THREAD

**Issue by ChinaChenMingQuan** [dotnet/roslyn#34610]
Visual studio version: vs2017 Community 15.9.10
.Net core sdk: 2.2.105

![测试](https://user-images.githubusercontent.com/32387920/55276118-a6949d00-532a-11e9-97da-e305cf9f3d94.png)
![测试2](https://user-images.githubusercontent.com/32387920/55276119-ab595100-532a-11e9-9d52-b93b04ebafaf.png)

**Comment by ChinaChenMingQuan** [comment]
Build Settings

![测试3](https://user-images.githubusercontent.com/32387920/55276173-7994ba00-532b-11e9-9c54-a5bc21dd26c9.png)

**Comment by svick** [comment]
Why do you think that's a bug? Because you can access `internal` methods from a different namespace? That is the correct behavior, `internal` prevents access from other *assemblies*, not namespaces, as is explained in [the documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/internal).

**Comment by ChinaChenMingQuan** [comment]
@svick, thank, can you say class default public?

**Comment by ChinaChenMingQuan** [comment]
or is same assembly, so class default public.

**Comment by ChinaChenMingQuan** [comment]
ok, but i do not like export dll, Ignore it. sorry.

**Comment by svick** [comment]
[The default access for a top-level class is `internal`.](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers#class-and-struct-accessibility) But like I said, `internal` means access within the same assembly is allowed.

**Comment by gafter** [comment]
I think this question has been answered, so I'm closing.  Please let us know if you feel it has not been answered.
