### ISSUE TITLE
NullableReferenceTypes not working with Action and lambda

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#34612]
@Yuzlol commented on [Fri Mar 29 2019](https://github.com/dotnet/csharplang/issues/2376)

Following codes seem to work differently with the NullableReferenceTypes:

            string? nullstring = null;

            Action firstAction =
                () => service.GetAccount(masterAcc.Id, null);    // CompilerWarning
            Action secondAction =
                () => service.GetAccount(masterAcc.Id, nullstring);   // No CompilerWarning

            var action =
                new Action(() => service.GetAccount(masterAcc.Id, null));  // No CompilerWarning

        public interface IAccount
        {
            Account GetAccount(string accountId, string masterAccountId);    
        }

        public Account GetAccount(string accountId, string masterAccountId)
        {
            accountIsAuthorized(masterAccountId);

            return accountExists(accountId);
        }

Bug or Feature?

---

@YairHalberstadt commented on [Fri Mar 29 2019](https://github.com/dotnet/csharplang/issues/2376#issuecomment-478013132)

What did GetAccount look like?

---

@Yuzlol commented on [Fri Mar 29 2019](https://github.com/dotnet/csharplang/issues/2376#issuecomment-478014557)

> What did GetAccount look like?

i updated my post

---

@yaakov-h commented on [Sat Mar 30 2019](https://github.com/dotnet/csharplang/issues/2376#issuecomment-478226497)

The first two lines lines emit warnings, albeit different ones. Odd that the third does not. ([source](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AAgAwAEhAjANwCwAUPbAgK4DGMpAstPAgIKtWpAN7kAzOQpkAkgBNSAXgB8pAEQVVVUgF969AMQA7ZgBsTEYCbik4hi1b11CEwgCZSA1gHtmhjsPpSINJA4OdyABZSACEIBAAKAEoRegBIVMpiAH5SYzNMxVzTE1oGOmCKyXdsTARYSncFUMrKpMUVKEQ0TFY4ADoAcTgYTx8/eMhYRE8+uSQis0StYIB6FdIAYS8wAAdMKwQAdTjDTEMAc2bKhtJO70NZG6byltbk5Vuunv6hkcExmATHjTQSzWTzPImTJLVbrAByXk22z2B2OCFOF0cr1IaDipAg7EwXkMiiu2MMcAA7lV4m0Pp0EN1eoNhqNfIDJrwZnMFiZEjDSGtSAikbt9og0RjLi8groZSF5dI2X5PozvoVIQBCUoVbhTfiCUickGsUpXcJnXjYAnWJX/dlXALyirKji/V3xAoE7zsnkFY0Gn1+OQCoJXOVYsISV2kd328Ze+MwP1SI3AwMAkOOsnBGAACwQXmpWp1wTl2iAA=))

---

@PathogenDavid commented on [Sat Mar 30 2019](https://github.com/dotnet/csharplang/issues/2376#issuecomment-478268818)

This issue is more suited for Roslyn since it's more likely a compiler issue than a spec issue. I believe it is probably covered by https://github.com/dotnet/roslyn/issues/32698 and https://github.com/dotnet/roslyn/issues/32499.

However, those issues are about the nullability mismatch of the signature of the delegate rather than nullability mismatch in the body of the lambda expression. It appears that nullability analysis just ignores explicit delegate creation in general, but it wouldn't hurt to add you example as another case where it isn't working as a comment to either issue. (Probably https://github.com/dotnet/roslyn/issues/32698 since it's about delegate creation syntax in general.)

**Comment by gafter** [comment]
@jcouv possibly the same as #32698

**Comment by jcouv** [comment]
With recent roslyn bits (May 8th), we now have a warning on each invocation of `GetAccount`. See [sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWAChKBiAOwFcAbRiYRufOW19y7AZkIAmfAGF8Ab0r4ZhQdgAs+ALIAKAJIBBAMbaA9vVox8URADcAltrgBKSdNmOnhIrgD8+Bs2IEAvJ6ZGcioKZxliEQAzCwRYCPxfBzDZVTtfAD4Tcys4ADoAcTgYHX1DGFUfXIBRMAAHGABPJADmGxJHAHoOsT06i3YEAHUIBFoLWgBzJKd4031aFHjE0OSUtMzTBEtrAqKSgyMK12q6xuavRh822S78ADk9Hr6B4dHxqZDksxH8CG0YCx6WgJabJWhwADuLiEqlSCQ22R2hWKugO5UqNXqTRajBs13wtweT1q/UQrzGk0o0wAvpRaSsBMJ8PsypJ6dNGeN4AhIn8OFpUWVplIVs4WUZ8MjxejXL9BUZ1Chmj58JBYIhpYr8TIaUA==).

I didn't manage to dig up the specific PR that fixed this.
