### ISSUE TITLE
Poor use of comma in "Remove unused parameter 'x', its initial value is never used"

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#34624]
**Version Used**: 16.0.0 RC.3

```cs
// IDE0060 Remove unused parameter 'x', its initial value is never used
void M(string x)
{
    x = string.Empty;
}
```

Traditionally, two sentences are not just joined with a comma. A conjunction such as 'and' or 'yet' is required to follow the comma. (http://www.sussex.ac.uk/informatics/punctuation/comma/joining)

Here are options that don't feel as odd:

- Remove unused parameter 'x'; its initial value is never used
- Remove unused parameter 'x' because its initial value is never used
- Remove unused parameter 'x' (its initial value is never used)
- Remove unused parameter 'x' whose initial value is never used
- Remove unused parameter 'x'. Its initial value is never used.

While writing in *general*, I'd lean strongly towards breaking up the compound sentence using two periods and two capitals. Run-on sentences are what everyone does by default. I've had feedback that has made me more aware of this. Short sentences make for the easiest reading. However, if Roslyn has no diagnostic messages that end with a period, it would be better to be consistent by not using full sentences.

**Comment by sharwell** [comment]
> Remove unused parameter 'x'; its initial value is never used

This form would be most consistent with other messages I've seen.
