### ISSUE TITLE
BasicLineCommit.CommitOnSave Fails

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#34637]
[Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=139246&view=ms.vss-test-web.build-test-results-tab) - Release Legacy run
```
Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: Sub Main(x As Integer)
In value:  Module Module1
    Sub Main(x   As   Integer)
    End Sub
End Module

   at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicLineCommit.CommitOnSave() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicLineCommit.cs:line 83.GetType().Name
   at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicLineCommit.CommitOnSave() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicLineCommit.cs:line 83
```

![12 30 25-BasicLineCommit CommitOnSave-TargetInvocationException](https://user-images.githubusercontent.com/611219/55343437-f628b500-545f-11e9-9035-2b8d8095adb1.png)

**Comment by sharwell** [comment]
@olegtk when this situation occurs, the user types <kbd>Ctrl</kbd>+<kbd>S</kbd> in the editor, and the file is silently not saved. In addition to the integration test failures, have observed this at least once during normal working. Do you know how I can track this down?

**Comment by tmat** [comment]
Another one: https://dev.azure.com/dnceng/public/_build/results?buildId=438379&view=ms.vss-test-web.build-test-results-tab&runId=13944154&resultId=100307&paneView=debug

**Comment by tmat** [comment]
One more: https://dev.azure.com/dnceng/public/_build/results?buildId=462449&view=ms.vss-test-web.build-test-results-tab&runId=14726318&resultId=100307&paneView=debug

**Comment by olegtk** [comment]
@aditya-kadam

**Comment by tmat** [comment]
Another one: https://dev.azure.com/dnceng/public/_build/results?buildId=471744&view=ms.vss-test-web.build-test-results-tab&runId=15013978&resultId=100307&paneView=debug

**Comment by tmat** [comment]
Another one: https://dev.azure.com/dnceng/public/_build/results?buildId=474968&view=ms.vss-test-web.build-test-results-tab&runId=15114646&resultId=100307&paneView=debug

**Comment by tmat** [comment]
One more: https://dev.azure.com/dnceng/public/_build/results?buildId=475497&view=ms.vss-test-web.build-test-results-tab&runId=15125820&resultId=100307&paneView=debug
