### ISSUE TITLE
SymbolTreeInfoIncrementalAnalyzerProvider does not run anymore for VSMac

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#34631]
**Version Used**: 
master

**Steps to Reproduce**:

1. Open a solution
2. Expect SymbolTreeInfoIncrementalAnalyzerProvider.IncrementalAnalyzer to run
3. It does not

**Expected Behavior**:
It should run and cache symbol tree infos in the database.

**Actual Behavior**:
It does not, thus making symboltreeinfo operations slower in the IDE.

Regression as of https://github.com/dotnet/roslyn/commit/6f5be2ef2849b22dc185081ed9e389f02b80e473#r32981653

**Comment by jinujoseph** [comment]
fixed via #34793
