### ISSUE TITLE
Consider tracking nullability of indexer values

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#34644]
```C#
class Program
{
    static void F(object?[] x, int i)
    {
        if (x[i] != null)
        {
            _ = x[i].ToString(); // warning
        }
    }
}
```
```
(7,17): warning CS8602: Possible dereference of a null reference.
```

**Comment by cston** [comment]
Note, the current behavior is by design: flow analysis tracks the nullability of variables (locals and parameters) and fields and properties of those variables only. Indexer values are not tracked.

**Comment by gafter** [comment]
This would require tracking that the index is "the same value", which is nothing like anything we do now.

**Comment by bkoelman** [comment]
Would be great to make it work only if the indexer is a compile-time constant. This comes up a lot in unit test assertions. For example:

```c#
var response = GetResponse();

Assert.NotNull(response);
Assert.Count(2, response.Items);
Assert.NotNull(response.Items[0]);
Assert.Equal("some", response.Items[0].Value);
```
