### ISSUE TITLE
Feature Request: Indicate Language of a string parameter with an attribute

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#34640]
I'm really enjoying the new support for language highlighting of strings.

I just used it with the Shouldy unit testing framework's [ShouldMatch](https://github.com/shouldly/shouldly/blob/master/src/Shouldly/ShouldlyExtensionMethods/ShouldBe/StringContainsTestExtensions.cs#L98) method as follows:

```csharp
// lang=regex
files.First().Name.ShouldMatch(@"\/license\.[0-9]*\.txt");
```

I was wondering if it might be possible to add an attribute that indicates the language of a string parameter. That way shouldly could mark their method as follows:

```csharp
public static void ShouldMatch(this string actual, [Lang("regex")] string regexPattern);
```

and it would be unnecessary to declare the language in a comment at the use site. Instead I could just write:

```csharp
files.First().Name.ShouldMatch(@"\/license\.[0-9]*\.txt");
```

and roslyn would realize the string is a regex.

Note that I have no connection with the Shouldly Framework, and make no claim that they would use this attribute if it were supported.

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski @sharwell for visiblity.  There are very few attributes that control IDE behavior (though 'EditorBrowsable' is definitely prior-art).

It's worth noting that Jetbrains has a solution here.  We coudl also consider just detecting and supporting their `RegexPatternAttribute` since it already exists: https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#RegexPatternAttribute

**Comment by YairHalberstadt** [comment]
@cyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
@YairHalberstadt Got you by 3 seconds :D

**Comment by jasonmalinowski** [comment]
We discussed a bit here and agreed that an attribute indeed would be a good way to do this. The attribute could be something we had added to the framework, so the framework could also annotate any of their methods. In the ideal world, the IDE wouldn't have to have special handling for the regex class to recognize strings being handed to the static members -- it too would just annotate things with this attribute.

**Comment by jasonmalinowski** [comment]
The next step here would be to actually write up a concrete proposal for the name of the attribute, what namespace it should be in, how the values are defined, etc. and then take that to the corefx team. The IDE would of course also recognize somebody defining that attribute in source just like we do for the various nullability attributes.

**Comment by Entomy** [comment]
Is there any intention of going forwards on this at all? I've got well over three dozen API's that could benefit from this.

**Comment by CyrusNajmabadi** [comment]
@Entomy there has been no forward progress on this.

**Comment by stephentoub** [comment]
For .NET 7 we've added a new `[RegexGenerator(...)]` attribute, which takes the same parameters as the `Regex` ctor, and we'd like colorization for the pattern argument.  In this case we could of course just special-case `RegexGenerator` in Roslyn, as Roslyn does for `Regex`'s ctor, but if there were a general mechanism for this, we could use that instead.

**Comment by stephentoub** [comment]
StringSyntaxAttribute has been merged into .NET 7.  Parameters, properties, and fields that are strings and represent either regular expressions or DateTime format specifiers have also been tagged with the attribute.

**Comment by CyrusNajmabadi** [comment]
@stephentoub thanks!

**Comment by CyrusNajmabadi** [comment]
API impl is here: https://github.com/dotnet/runtime/pull/62995

**Comment by stephentoub** [comment]
@CyrusNajmabadi, FYI one thing that came up offline as I was attributing parameters and the like were DateOnly and TimeOnly.  They allow only a subset of the DateTime format specifiers, i.e. just date-related ones for DateOnly and just time-related ones for TimeOnly.  I did not attribute those then as "DateTimeFormat", but we could consider adding "DateFormat" and "TimeFormat" if Roslyn could recognize those as well and restrict what it displays.

**Comment by CyrusNajmabadi** [comment]
> but we could consider adding "DateFormat" and "TimeFormat" if Roslyn could recognize those as well and restrict what it displays.

That seems totally reasonable to me.  We could def breakup our existing helper to be two internal types (one for dates, one for times). and both would activate for DateTimeFormat.

**Comment by CyrusNajmabadi** [comment]
Closing out as StringSyntax was added to the framework.
