### ISSUE TITLE
Code fix for WRN_ImplicitCopyInReadOnlyMember

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#34649]
Possible fixes include:

- make an explicit copy of 'this'
- modify the invoked member to be 'readonly' if legal

**Comment by Youssef1313** [comment]
@dotnet/roslyn-ide Is there still a interest in having this codefix?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
