### ISSUE TITLE
Feature request: available field name suggestions upon typo (based on e.g. Levenstein distance)

### ISSUE THREAD

**Issue by korsaire** [dotnet/roslyn#34652]
Say you have a simple class:
```
class Animal 
{
	public int Age { get; set; }
	public string Name { get; set; }
}
```

And you make typo when writing value to a field:
```
var x = new Animal(){ Aeg = 10 };
```

Currenly compilation error is as follows:
```
 'Animal' does not contain a definition for 'Aeg'
```
Arguably, it's not very helpful. It's easy to find the right field in this simple example, could be more tricky with tens or hundreds of fields. IMO something like this would be better:
```
 'Animal' does not contain a definition for 'Aeg'. Did you mean 'Age'?
```
Suggestion can be made by calculating the edit distance to all available fields and displaying the one with the smallest edit distance.
The same logic can be applied when user mistypes a variable inside a method but I guess it's much broader problem, so having just accessible field suggestions would be a good start.

**Comment by svick** [comment]
Should such feature be part of the compiler, or the IDE? Or are you talking about situations where you're not using an IDE?

**Comment by CyrusNajmabadi** [comment]
The IDE already does this :)   I'm not sure we need a compiler feature here.  That said, if we did add the compiler feature we should be sure to unify on hte same algorithm (ideally the same code) for computing hte matches.

![image](https://user-images.githubusercontent.com/4564579/55414545-2d5e9b00-5520-11e9-9f6b-dc99e5e7b478.png)

**Comment by gafter** [comment]
We're not going to modify the compiler diagnostics this way.

**Comment by YoshiRulz** [comment]
If there's already an Analyzer which does this, can it be enabled for builds done via the CLI?
