### ISSUE TITLE
`t is null` with LangVersion 7 should produce a diagnostic

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#34678]
The issue was reported by @varobc in https://github.com/dotnet/cli/issues/11020
FYI @peterhuene @333fred 

When this is fixed (likely in 16.1), this should be documented as a breaking change, albeit a short-lived one.

**Comment by gafter** [comment]
See https://github.com/dotnet/roslyn/pull/25995 where this behavior was introduced.

The language feature was championed here: https://github.com/dotnet/csharplang/issues/1284

**Comment by gafter** [comment]
`t is null` should produce a diagnostic when LangVersion is < 8. That diagnostic should indicate that upgrading the LangVersion would make the code compile.
