### ISSUE TITLE
Code fix preview fails to show diff for trailing whitespace changes

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#34670]
The code fix for removing whitespace should say that, instead of "fix formatting"

![image](https://user-images.githubusercontent.com/1103906/55374697-200fd380-5555-11e9-8749-b321319ed820.png)

I did not have visible whitespace turned on and the resulting change showed no diff, so it I was confused at first.

**Comment by sharwell** [comment]
:thought_balloon: This seems less like a problem with the diagnostic message and more like a problem with the diff presentation.

**Comment by sharwell** [comment]
Updated the title to reflect the bug here.

**Comment by sharwell** [comment]
The preview also fails to show leading whitespace changes that are just tabs/spaces conversions.
https://developercommunity.visualstudio.com/content/problem/529208/quick-actions-is-not-showing-the-change-in-code-wh.html

**Comment by CyrusNajmabadi** [comment]
Diff view is owned by editor/platform.  @olegtk can you reroute?
