### ISSUE TITLE
Result of looking up `new` calls to delegates (e.g., Action and Func) is inconsistent with others

### ISSUE THREAD

**Issue by ltcmelo** [dotnet/roslyn#34674]
Given an `ObjectCreationExpressionSyntax` node, I can typically lookup the bound constructor symbol with `var sym = Data.Model.GetSymbolInfo(node).Symbol;`. This works most of the time, but not when such call binds to a delegate such as `System.Action` or `System.Func`, e.g.: 

```
new Whatever(...); // OK
new System.Action(() =>  Console.WriteLine("Hello World"); })(); // Not OK
```

I can still discover the desired symbol using the following logic (for these cases). But I 

```
if (node is ObjectCreationExpressionSyntax ctorCallN)
{
    var tySym = Data.Model.GetSymbolInfo(ctorCallN.Type).Symbol;
    if (tySym != null  && tySym is INamedTypeSymbol namedTySym)
    {
            foreach (var membSym in namedTySym.GetMembers())
            {
                if (membSym is IMethodSymbol methSym
                        && methSym.MethodKind == MethodKind.Constructor)
                    return methSym;
            }
    }
}
```

For consistency, I think the lookup above should be addressed to fix this behavior.

**Version Used**: 
2.10

**Comment by CyrusNajmabadi** [comment]
Tagging @gafter for insight here.

**Comment by CyrusNajmabadi** [comment]
Also @jcouv .  It's not totally clear to me why the compiler behaves how it does.

**Comment by gafter** [comment]
When you write `new Action(Main)`, this is not an object creation expression, and it is not referencing a constructor.  This is a delegate creation expression.  See https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#the-new-operator

**Comment by jcouv** [comment]
Since there is no constructor at the language level (although there is one in the code we emit), Neal said we expect `GetSymbolInfo` to return nothing here.

**Comment by CyrusNajmabadi** [comment]
Thanks for the information @gafter and @jcouv !

**Comment by ltcmelo** [comment]
Thanks for the feedback guys. I understand the explanation, however:

> Since there is no constructor at the language level (although there is one in the code we emit), Neal said we expect GetSymbolInfo to return nothing here.

@jcouv , @gafter Wouldn't it then be case the export such a symbol to the API? Point being is that the end result, from a user perspective, is that the behavior of `GetSymbolInfo` is inconsistent.

**Comment by CyrusNajmabadi** [comment]
> is that the behavior of GetSymbolInfo is inconsistent.

The behavior is intended to be accurate as per the language.  Consistency doesn't really come into play.  for example, if i do `new SomeArray[] { 1, 2, 3 }`, there's no expectation that i would get a constructor call here.

**Comment by ltcmelo** [comment]
Sure, @CyrusNajmabadi . I'm not saying we should get a *constructor*, but it's weird not get any symbol at all. That's why my sugestion above.

**Comment by CyrusNajmabadi** [comment]
> Sure, @CyrusNajmabadi . I'm not saying we should get a constructor, but it's weird not get any symbol at all. That's why my sugestion above.

Gotcha, and i can commiserate.  But it's not particularly clear *what* symbol would be appropriate here.  For example, returning the delegate-type-symbol isn't really correct.  That expression doesn't represent hte delegate-type.  And it's not clear to me that we'd want to "invent" some new symbol just to represent this.

I think this is just the nature of the Roslyn semantic API.  The intent is that you use an appropriate blend of operations like `GetSymbolInfo/GetTypeInfo/GetConstantValue/etc.` to ask your questions.

Note: as an alternative, you might want to consider moving to `IOperation`.  This gives a more semantically enriched and more unified model for accessing all the information you might care about.  There would, for example, be an `IDelegateCreationOperation` in the tree in that spot, which would tell you exactly what was going on here.  

Happy to chat more about this on gitter.im.  But, for now, i think things are actually in an appropriate spot for the APIs.
