### ISSUE TITLE
VB.NET Editor is messed up!

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#34699]
**Version Used**: 
VS.NET 2019 Community Edition.
Win 10 x64 ver 1809 update KB4489899 (OS Build 17763.379)

**Steps to Reproduce**:
I am working on the Vazor project
https://github.com/VBAndCs/Vazor
Try any file in the project, for example: https://github.com/VBAndCs/Vazor/blob/master/WebApp1/Views/Home/Index.vazor.vb

**Expected Behavior**:
A usual editor behavior.

**Actual Behavior**:
The editor doesn't recognize most of the types, no Intellisense most of the time, no red line under unrecognized members and the go to definition command doesn't work! 
I faced some of these issues in the VS.NET 2019 preview, where the editor always shows me an error message at the top of the window after loading the project, but these issues were minimal. This got worst in the release! no error message, but nearly nothing is working!

**Comment by CyrusNajmabadi** [comment]
> The editor doesn't recognize most of the types, no Intellisense most of the time, no red line under unrecognized members and the go to definition command doesn't work!

Sounds like you might not be initializing things properly.  Are you trying to report an actual issue in Roslyn?  Or is this just asking for help to figure out where the problems are in your library?

**Comment by VBAndCs** [comment]
@CyrusNajmabadi 
The project is up and running and published on github. 
I give you one example from https://github.com/VBAndCs/Vazor/blob/master/WebApp1/Views/Home/Index.vazor.vb 

```VB.NET
    Public ReadOnly Property Content() As Byte() Implements IVazorView.Content
        Get
            If _content Is Nothing Then
                Dim html = GetVbXml().ParseTemplate(students)
                _content = System.Text.Encoding.UTF8.GetBytes(html)
            End If
            Return _content
        End Get
    End Property
```

In the line ` Dim html = GetVbXml().ParseTemplate(students)`
When I hover over `GetVbXml()` the tooltip shows the function signature. But when I hover over ParseTemplate no tip appears, goto definition shows an error message and even typing a . after the ` GetVbXml()` call doesn't show the completion list!
I am facing this all over the project in the today's released version. 
If I made a mistake like this: `GetVbXml.test(students)` where there is no such a test member, the editor doesn't compline about it! I feel I am back to VB4 or earlier!

**Comment by VBAndCs** [comment]
I opened an old C# project of mine and the editor works fine. I tried to mess with some names, and the editor listed the error immediately!
This is definitely a VB.NET Editor issue!

**Comment by VBAndCs** [comment]
I also get Error	NETSDK1045:
> The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.0.	

This project was running on the VS.NET 2019 preview as it is. I uninstalled the preview and installed the release. When I press F5 the project runs fine (it uses the previous build although I made changes in the code!!)
I Uninstalled .NET Core 3 SDK preview 3 and re-install it again, and still have Error NETSDK1045!

**Comment by VBAndCs** [comment]
I uninstalled all .net core sdks from control panel, restarted the PC, and Installed .NET core SDK 3 preview 3. This time VB.NET 2019 unable to load any project! The Preview version was able to use .NET core SDK 3 preview 3. What is the problem now?
What should I do? I am not able to complete my work !

**Comment by VBAndCs** [comment]
I tried to create a new C# Web project (.Core) and this is what I got:

![Untitled](https://user-images.githubusercontent.com/48354902/55444906-0f914480-55b9-11e9-86c4-a2a19e9df17b.png)

Although I had .NET Core SDK 3 preview 3 installed:

![Untitle2](https://user-images.githubusercontent.com/48354902/55444942-2df74000-55b9-11e9-8042-e6e11e95bd4d.png)

What is going on?
I installed nearly all VS.NET components except C++ and gaming tools, so I don't think it is a setup mistake.
Why doesn't VS 2019 recognize .NET Core SDK 3 preview 3 ?
What should I do?

**Comment by VBAndCs** [comment]
Seems that the community edition has issues. The preview was the interprise edition, so the problem is in the community edition.  I opens a new thread for this: #34713

**Comment by VBAndCs** [comment]
@CyrusNajmabadi 
The app now runs on .NET core 3.0. preview The editor error label appeared again:

![2](https://user-images.githubusercontent.com/48354902/55473369-d71c5580-560e-11e9-9cec-6aa01dd1b265.jpg)

and this is the link provided by the err:
https://docs.microsoft.com/en-us/visualstudio/ide/not-in-toc/visual-studio-unrecoverable-process-error?view=vs-2019

I think this is the source of VB.NET editor misbehavior I described above. Is there a solution or a fix?

**Comment by CyrusNajmabadi** [comment]
> Is there a solution or a fix?

You'd have to actually diagnose and give more details on what the actual problem is.

**Comment by VBAndCs** [comment]
@CyrusNajmabadi 
The editor behaivs better now. Seems that the problem was caused because VS didn't recognize .net core 3 preview. But that editor error mesage is keeping coming at the load of the project! I dismiss it and continue.
I can live with that, but if you require more diagnoses to fix this, tell me what to do.

**Comment by jmarolf** [comment]
@VBAndCs if you click on Send Feedback -> Report a Problem we will get a trace of what is happening

![image](https://user-images.githubusercontent.com/9797472/55503457-8d7a3d80-5603-11e9-8fe8-b4ce41cf3e71.png)

**Comment by VBAndCs** [comment]
Done.
