### ISSUE TITLE
Implement cycle breaking rule for interfaces

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#34704]
There is a specification for breaking binding cycles while binding an interface's base clause:

> ### Binding base clauses
> 
> Interfaces now contain types.  These types may be used in the base clause as base interfaces.  When binding a base clause, we may need to know the set of base interfaces to bind those types (e.g. to lookup in them and to resolve protected access).  The meaning of an interface's base clause is thus circularly defined.  To break the cycle, we add a new language rules corresponding to a similar rule already in place for classes.
> 
> While determining the meaning of the *interface_base* of an interface, the base interfaces are temporarily assumed to be empty. Intuitively this ensures that the meaning of a base clause cannot recursively depend on itself. 
> 
> When an interface IB extends an interface IA, it is a compile-time error for IA to depend on IB. An interface ***directly depends on*** its direct base interfaces (if any) and directly depends on the type within which it is immediately nested (if any). Given this definition, and the definition of *directly depends on* for classes, the complete set of types upon which an interface depends is the reflexive and transitive closure of the directly depends on relationship.

It is possible that this rule is already implemented, or that some other cycle breaking algorithm is implemented.  Please ensure there is alignment between the implementation and the specification.

**Comment by jcouv** [comment]
@gafter Can we push this to Compiler.Next?

**Comment by gafter** [comment]
It could possibly be a breaking change but I don't see any way to get it into 16.3

**Comment by AlekseyTs** [comment]
@gafter 

We already had machinery dealing with breaking cycles in base clauses. It already dealt with cycles for base clauses for both classes and interfaces, with both interfaces and classes in the base clause. The only part that was missing is handling of protected accessibility check for types nested into interfaces. That part was extended in in the same manner as we handle protected accessibility check for types nested into classes. I believe we now have consistent cycle-breaking behavior across classes and interfaces. Below some of the scenarios I tried. Feel free to provide scenarios that in your opinion exhibit incorrect/inconsistent behavior.

```
        [Fact]
        [WorkItem(34704, "https://github.com/dotnet/roslyn/issues/34704")]
        public void NestedTypes_10()
        {
            var source1 =
@"
interface I1
{
    protected interface I2
    {
    }
}

class C1
{
    protected interface I2
    {
    }
}

interface I3 : I1, I1.I2
{
    private void M1(I1.I2 x) { }
}

interface I4 : I1, I2
{
    I2 MI4();
}

interface I5 : I1.I2, I1
{
    private void M1(I1.I2 x) { }
}

interface I6 : I2, I1
{
    I2 MI6();
}

class C3 : I1, I1.I2
{
    private void M1(I1.I2 x) { }
}

class C4 : I1, I2
{
    void MC4(I2 x) { }
}

class C5 : I1.I2, I1
{
    private void M1(I1.I2 x) { }
}

class C6 : I2, I1
{
    void MC6(I2 x) { }
}

class C33 : C1, C1.I2
{
    protected void M1(C1.I2 x) { }
}

class C44 : C1, I2
{
    void M1(I2 x) { }
}

interface I7 : I8
{
    public interface I8 : I7
    {
    }
}

class C7 : I8
{
    public interface I8
    {
    }
}

interface I9 : I9.I10
{
    public interface I10 : I9
    {
    }
}

interface I11
{
    public interface I12 : I13
    {
    }

    public interface I13
    {
    }

    public interface I14 : I11.I13
    {
    }
}

class C11
{
    public interface I12 : I13
    {
    }

    public interface I13
    {
    }

    public interface I14 : I11.I13
    {
    }
}
";

            var compilation1 = CreateCompilation(source1, options: TestOptions.DebugDll,
                                                 parseOptions: TestOptions.Regular,
                                                 targetFramework: TargetFramework.NetStandardLatest);

            compilation1.VerifyDiagnostics(
                // (16,23): error CS0122: 'I1.I2' is inaccessible due to its protection level
                // interface I3 : I1, I1.I2
                Diagnostic(ErrorCode.ERR_BadAccess, "I2").WithArguments("I1.I2").WithLocation(16, 23),
                // (21,20): error CS0246: The type or namespace name 'I2' could not be found (are you missing a using directive or an assembly reference?)
                // interface I4 : I1, I2
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "I2").WithArguments("I2").WithLocation(21, 20),
                // (23,5): error CS0246: The type or namespace name 'I2' could not be found (are you missing a using directive or an assembly reference?)
                //     I2 MI4();
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "I2").WithArguments("I2").WithLocation(23, 5),
                // (26,19): error CS0122: 'I1.I2' is inaccessible due to its protection level
                // interface I5 : I1.I2, I1
                Diagnostic(ErrorCode.ERR_BadAccess, "I2").WithArguments("I1.I2").WithLocation(26, 19),
                // (31,16): error CS0246: The type or namespace name 'I2' could not be found (are you missing a using directive or an assembly reference?)
                // interface I6 : I2, I1
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "I2").WithArguments("I2").WithLocation(31, 16),
                // (33,5): error CS0246: The type or namespace name 'I2' could not be found (are you missing a using directive or an assembly reference?)
                //     I2 MI6();
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "I2").WithArguments("I2").WithLocation(33, 5),
                // (36,19): error CS0122: 'I1.I2' is inaccessible due to its protection level
                // class C3 : I1, I1.I2
                Diagnostic(ErrorCode.ERR_BadAccess, "I2").WithArguments("I1.I2").WithLocation(36, 19),
                // (41,16): error CS0246: The type or namespace name 'I2' could not be found (are you missing a using directive or an assembly reference?)
                // class C4 : I1, I2
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "I2").WithArguments("I2").WithLocation(41, 16),
                // (43,14): error CS0246: The type or namespace name 'I2' could not be found (are you missing a using directive or an assembly reference?)
                //     void MC4(I2 x) { }
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "I2").WithArguments("I2").WithLocation(43, 14),
                // (46,15): error CS0122: 'I1.I2' is inaccessible due to its protection level
                // class C5 : I1.I2, I1
                Diagnostic(ErrorCode.ERR_BadAccess, "I2").WithArguments("I1.I2").WithLocation(46, 15),
                // (51,12): error CS0246: The type or namespace name 'I2' could not be found (are you missing a using directive or an assembly reference?)
                // class C6 : I2, I1
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "I2").WithArguments("I2").WithLocation(51, 12),
                // (53,14): error CS0246: The type or namespace name 'I2' could not be found (are you missing a using directive or an assembly reference?)
                //     void MC6(I2 x) { }
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "I2").WithArguments("I2").WithLocation(53, 14),
                // (56,20): error CS0122: 'C1.I2' is inaccessible due to its protection level
                // class C33 : C1, C1.I2
                Diagnostic(ErrorCode.ERR_BadAccess, "I2").WithArguments("C1.I2").WithLocation(56, 20),
                // (61,17): error CS0246: The type or namespace name 'I2' could not be found (are you missing a using directive or an assembly reference?)
                // class C44 : C1, I2
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "I2").WithArguments("I2").WithLocation(61, 17),
                // (66,16): error CS0246: The type or namespace name 'I8' could not be found (are you missing a using directive or an assembly reference?)
                // interface I7 : I8
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "I8").WithArguments("I8").WithLocation(66, 16),
                // (73,12): error CS0246: The type or namespace name 'I8' could not be found (are you missing a using directive or an assembly reference?)
                // class C7 : I8
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "I8").WithArguments("I8").WithLocation(73, 12),
                // (80,11): error CS0529: Inherited interface 'I9.I10' causes a cycle in the interface hierarchy of 'I9'
                // interface I9 : I9.I10
                Diagnostic(ErrorCode.ERR_CycleInInterfaceInheritance, "I9").WithArguments("I9", "I9.I10").WithLocation(80, 11),
                // (82,22): error CS0529: Inherited interface 'I9' causes a cycle in the interface hierarchy of 'I9.I10'
                //     public interface I10 : I9
                Diagnostic(ErrorCode.ERR_CycleInInterfaceInheritance, "I10").WithArguments("I9.I10", "I9").WithLocation(82, 22)
                );
        }
```

**Comment by gafter** [comment]
My concern is not just that we have tests for specific cases that we can think of (though that is of course important).  I think it is important that the structure of the compiler aligns with the specification such that it is clear from inspection of the compiler that it implements these two rules:

> 1. While determining the meaning of the interface_base of an interface, the base interfaces are temporarily assumed to be empty. Intuitively this ensures that the meaning of a base clause cannot recursively depend on itself.
>
> 2. When an interface IB extends an interface IA, it is a compile-time error for IA to depend on IB. An interface directly depends on its direct base interfaces (if any) and directly depends on the type within which it is immediately nested (if any). Given this definition, and the definition of directly depends on for classes, the complete set of types upon which an interface depends is the reflexive and transitive closure of the directly depends on relationship.

These two rules probably require different implementation techniques from each other, and it would be helpful to identify the parts of the compiler that directly implement them.  For example, for classes we thread a list of bases being bound to implement the equivalent of rule (1), and for [the equivalent of rule (2)](https://github.com/dotnet/csharplang/blob/master/spec/classes.md#base-classes) we have an explicit computation of the "depend on" relationship that we then test to see if the rule is satisfied in `BaseTypeAnalysis.ClassDependsOn`.  I don't know where to find the equivalent compiler code for interfaces, and the following compiles without error, suggesting that it is not implemented at all.

``` c#
public interface IA : IA.IB
{
    public interface IB { }
}
```

To reduce the scope of a breaking change when we implement the language specification, I am moving this to milestone 16.4.

**Comment by gafter** [comment]
To avoid a breaking change, rule 2 may have to be changed to

> When an interface `IB` extends an interface `IA`, it is a compile-time error for `IA` to depend on `IB`. An interface _directly depends on_ its direct base interfaces (if any) and directly depends on the interface within which it is immediately nested (if any). Given this definition, the complete set of interfaces upon which an interface depends is the reflexive and transitive closure of the directly depends on relationship.
