### ISSUE TITLE
VS.NET 2019 Community Works only with .NET Core 2.1 SDK

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#34713]
**Version Used**: 
VS.NET Community 16.0.0

**Expected Behavior**:
Able to use .Net Core 3 SDK preview3

**Actual Behavior**:
Doesn't even recognize it! Build the project gives Error NETSDK1045:
> The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.0.	

There is something wrong with the community edition. I tried all the sorts of uninstall, restart re-install, and even ran a repair setup, but nothing changes!

**Comment by CyrusNajmabadi** [comment]
> Build the project gives Error NETSDK1045:

Build *which* project?

**Comment by peterhuene** [comment]
Hi @VBAndCs. The .NET Core 3.0 SDK is currently in preview and therefore doesn't get used by default.

To use it with Visual Studio 2019, you need to ensure that the "Use previews of the .NET Core SDK" option is checked under Tools -> Options -> Projects and Solutions -> .NET Core.

**Comment by VBAndCs** [comment]
@peterhuene
Thanks. It worked.
It will be helpful if you append this not to the message.
