### ISSUE TITLE
Why extension methods do not work for dynamic values when method parameters are dynamic already. Compiler error CS1973.

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/roslyn#34716]
**Version Used**:  Any

**Steps to Reproduce**:

1. Create extension method with dynamic parameters already:
```cs
public static class Extensions
{
    public static dynamic If(this bool p, dynamic @then, dynamic @else) => p ? @then : @else;
}
```

2. Call this method with dynamic values.
```cs
    dynamic t = "then";
    dynamic e = "else";
    Console.WriteLine( true.If(t, e) ); // Compiler error CS1973.
```

3. But next code works
```cs
    dynamic t = "then";
    dynamic e = "else";
    Console.WriteLine( true.If((object)t, (object)e) );
```

**Expected Behavior**:

Support extension methods for dynamic values when method parameters are dynamic already.

**Actual Behavior**:

Compiler error CS1973.

**Comment by gafter** [comment]
The current behavior is required by the specification at https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#invocation-expressions .  If you would like it changed please write a detailed proposal and post it to `csharplang`.
