### ISSUE TITLE
Toggle Line Comment

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#34734]
Editor team has implemented a command for toggle line comment.
We need to decide the functionality for this feature as well.

### Removing single line comment(s)
1.  The caret ($$) is inside a commented line.
```csharp
// var b$$ = 1;
```
2.  The caret is on the same line before a block comment with only whitespace.
```csharp
$$    // var a = 1;
```
3.  The selection ([| |])is entirely inside a single line comment
```csharp
// var [|a = |]2;
```
4.  The selection contains a single line comment (plus any whitespace)
```csharp
[|    // var a = 2;|]
```
5.  The selection contains only multiple single line comments (plus whitespace)
```csharp
[|    // var a = 2;
     
     // var b = 1;
   |]
```

### Adding single line comment(s)
Adding block comments will put single line comment markers at the least indentation level in the selection.

1.  Caret is anywhere on an uncommented line.
```csharp
var b$$ = 1;
```
Results in
```csharp
//var a = 1;
```
2.  Selection is inside an uncommented line.
```csharp
var [|a = 1;|]
```
Results in
```csharp
//var a=1;
```
3.  Selection contains multiple uncommented lines.
```csharp
var [|a = 1;
var b =|] 2;
```
Results in
```csharp
//var a = 1;
//var b = 2;
```
4.  The caret is inside a comment on partial commented line.
```csharp
var a = 1; // var b$$ = 2;
```
Results in
```csharp
//var a = 1; // var b = 2;
```
5.  Selection contains uncommented and commented lines.
```csharp
//var [|a = 1;
var b = 2;|]
```
Results in
```csharp
////var a = 1;
//var b = 2;
```
6.  Selection contains lines with different indentations.
```csharp
var a = 1;
    var b = 2;
```
Results in
```csharp
//var a = 1;
//    var b = 2;
```
7.  Selection contains line with partial comment.
```csharp
[|var //a =|] 1;
```
Results in
```csharp
//var //a = 1;
```
8.  Selection contains multiple lines with partial comment.
```csharp
[|var //a = 1;
var b = 2;|]
```
Results in
```csharp
//var //a = 1;
//var b = 2;
```

#### VSCode
No matter selection, it inserts a comment at the beginning of the line at the least indent.  Comments not at the beginning of the line are ignored.

#### Intellij
Similar to VSCode, except comments are inserted at the beginning of the line.

**Comment by CyrusNajmabadi** [comment]
Same comments as 'toggle block', if at all possible, use the existing APIs we have, and try to have a default impl that will work for all roslyn languages.  Tnx much! :)
