### ISSUE TITLE
Duplicate reference when find all reference with mulit TargetFrameworks project

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#34745]
**Version Used**: 
VS2019 16.0.0 Preview5.0
C# Tools 3.0.0-beta4-19170-01+1deafee3682da88bf07d1c18521a99f47446cee8
(Also on VS2017 15.9.7 preview1, 2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a)

**Steps to Reproduce**:

1. dotnet new classlib, and edit `TargetFramework` to `<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>`
2. Type the below codes
```cs
using System;

namespace ClassLibrary1
{
    public class Class1 : IDisposable
    {
        public void Dispose()
        {
            throw new NotImplementedException();
        }

        public void XX1()
        {
            var cts = new System.Threading.CancellationTokenSource();
            cts.Dispose();
        }
    }
}
```
3. Find all reference of `Class1.Dispose` in VS

**Expected Behavior**:
Not sure what's the expected behavior, but should not get more than 2 results
If only find `Class1.Dispose`, should get 0 result.
Or consider `IDisposable.Dispose` and get 1 result(or 2 for both targetframework)

**Actual Behavior**:
Get 3 results, and 2 of them in `netstandard2.0` group.
VS show one is reference to `CancellationTokenSource.Dispose` in `netstandard2.0\ref\netstandard.dll` and another is reference to `CancellationTokenSource.Dispose` in `net461\mscorlib.dll`
![image](https://user-images.githubusercontent.com/1819074/55537389-aad80600-56ee-11e9-810d-ad5ae1c69548.png)

**Comment by CyrusNajmabadi** [comment]
FAR was rewritten to now unify and group linked symbols.  It was also changed so that it doesn't show references to other implementations of an interface method different from teh one you called on.  THe new UI now shows:

![image](https://user-images.githubusercontent.com/4564579/218159308-f29d3b15-dcc6-4dfd-8144-a37f9ad5e151.png)

Which is working as intended.
