### ISSUE TITLE
VS2019 - Expression Trees: Rosyln Analyzer incorrectly suggests converting an anonymous type with property assignment to a tuple

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34749]
In Visual Studio 2019, the Roslyn analyzer suggests converting an anonymous type to a tuple within an Expression Tree.
 
I encountered this while doing a LINQ Join, but can be reproduced with a simple Expression

```csharp 
Expression<Func<string, string, dynamic>> test =
    (par1, par2) => new { Parameter1 = par1, Parameter2 = par2 };
```

The analyzer gives a suggestion to Convert To Tuple and even shows the red squiggly lines denoting an error in preview. Applying the changes will throw a CS8143 error: &quot;An expression tree may not contain a tuple literal&quot;.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/513721/vs2019-expression-trees-rosyln-analyzer-incorrectl.html
VSTS ticketId: 835783_
_These are the original issue comments:_

Visual Studio Feedback System on 4/2/2019, 07:20 PM (30 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by snickler** [comment]
Hello,

I'm the original poster of the issue. If there's any extra information I need to provide, let me know.

**Comment by CyrusNajmabadi** [comment]
@snickler Nope!  This was great!  If you're interested, feel free to file a fix as well.  it should not be hard as several feaures today already have to disable themselves inside expressions.  We (and i mean 'me'), just missed this case when writing the feature :)

**Comment by snickler** [comment]
@CyrusNajmabadi  - Will do! This will be the first time I can contribute to Roslyn.

**Comment by gmorris007** [comment]
Is there any action on this issue? I came across it today using Microsoft Visual Studio Professional 2019, Version 16.11.10.
The solution where this occurs targets .Net Framework 4.8.
Thanks.

**Comment by CyrusNajmabadi** [comment]
@gmorris007 Nope.  This is on the backlog.  As per https://github.com/dotnet/roslyn/issues/34749#issuecomment-479976021 though, we'd happily work with you to create a PR to fix this up.

**Comment by snickler** [comment]
I somehow got mega sidetracked and forgot about making a resolution for this. Looks like it's time to revisit!
