### ISSUE TITLE
Rename preview changes livelocks (cannot close) after edits is preview window

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34743]
1. Create C# Console App.
2. Invoke rename on &quot;Program&quot; class name.
3. Enter new name, check &quot;Preview changes&quot;, click Apply.
4. Set focus on the code preview in the preview window.
5. Try typing some characters on the keyboard.
6. Press OK, Cancel, or X

**Expected** The preview window closes.
**Actual:**  The preview window does not close, need to terminate Visual Studio from Task Manager to get out.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/510757/preview-changes-livelocks-cannot-close-after-edits.html
VSTS ticketId: 833054_
_These are the original issue comments:_

Visual Studio Feedback System on 4/1/2019, 05:08 AM (2 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
Repros on 15.9 as well

**Comment by CyrusNajmabadi** [comment]
I can't repro this.  closing out.  likey fixed with moves to jtf.
