### ISSUE TITLE
Hovering over indent line after catch only shows try

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34746]
Hovering over the ident line of a try catch statement. Hoverying over the line between the try braces shows the same information in the tooltip as hoving over the catch braces. Hovering over the catch braces should should the catch in the tooltip also.

![image](https://user-images.githubusercontent.com/12449387/55540188-5180c000-5677-11e9-9447-b867dd40f2fd.png)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/510755/hovering-over-indent-line-after-catch-only-shows-t.html
VSTS ticketId: 833042_
_These are the original issue comments:_

Visual Studio Feedback System on 4/1/2019, 05:10 AM (2 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by alex-oswald** [comment]
I believe that `catch` should show directly below `try` in the tooltip. It shouldn't be indented past `try`, but it should be visible.

**Comment by vatsalyaagrawal** [comment]
We should also check to see how if/else-if is handled.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
