### ISSUE TITLE
Function names in tooltip of closing bracket get doubled - FunctionNameFunctionName()

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34747]
VS2019 preview 4.3. I haven't noticed this before and it might be temporary, but something is still causing it. It has survived at least one restart. When I point to the closing bracket of any function or class in any project, the name in the tooltip is shown twice in a row - like MainMain(). Only the name, not the keywords or parameters.

in VS 16.0 
![image](https://user-images.githubusercontent.com/12449387/55540827-9f49f800-5678-11e9-839c-634171aea288.png)

In VS 15.9 
![image](https://user-images.githubusercontent.com/12449387/55540936-d0c2c380-5678-11e9-8af0-22ec6c7a9236.png)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/503222/function-names-in-tooltip-of-closing-bracket-get-d.html

**Comment by chborl** [comment]
I can repro this in the current VS dogfood version (16.0 Preview 5), but it is not reproducible in current master branch.

**Comment by chborl** [comment]
This appears to have been fixed during some other code changes in this area, as I am not seeing it in 16.1 Preview 1 either.  

![image](https://user-images.githubusercontent.com/25776963/55590575-208ca380-56e8-11e9-9fd5-e4d83263ab61.png)

If you see this issue in 16.1 Preview 1 or later, please re-open this issue.

**Comment by chborl** [comment]
Will close once I verify it is in the final 16.1 Preview 1.

**Comment by chborl** [comment]
Verified this is fixed in 16.1 Preview 2
