### ISSUE TITLE
Compile warns for `throw <potential-null>`

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#34754]
The compiler currently gives `warning CS8597: Possible null value.` for `throw null`. However, this is "valid" code as the language and runtime both spec this as throwing a `NullReferenceException`.

Given that an exception is being thrown and `throw null;` is considered valid; it might be worth considering not warning in this scenario.

**Comment by tannergooding** [comment]
This would greatly simplify the following pattern by not requiring an exclamation point after the throw statement:
```csharp
if (errorCode < 0)
{
    throw Marshal.GetExceptionForHR(errorCode)!;
}
```

Alternatively, it might be worth considering a way to document that the function will never return `null` if `errorCode < 0`

**Comment by gafter** [comment]
We already discussed this in the LDM and decided that we intend the warning.  The purpose of the nullable reference types feature is to produce warnings when a null value could arise at runtime where a non-null value is expected for the normal semantics of the operation.
