### ISSUE TITLE
Apply code cleanup changes by document instead of all at the end

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34755]
**Version Used**: 7e7f95bd33c1ed3f0256fc69811a0845bc6c7284

**Steps to Reproduce**:

1. Run code cleanup in project or solution

**Expected Behavior**:

Changes for each document are written to disk after the document is cleaned up.

**Actual Behavior**:

All changes are held in memory until the operation fully completes, and only then are written to disk.

**Comment by CyrusNajmabadi** [comment]
this kind of goes against the spirit of roslyn wrt our snapshots.  We try to be all-or-nothing.   We compute the new solution snapshot, then apply this.

I would not expect the above to ahve any difference over the behavior we currently have *except* in the cases of crashes.  And i'm not sure we should change our implementation for that.

Are there other reasons we would want to do this?  THanks!
