### ISSUE TITLE
Rename project file designator from NullableContextOptions to NullableReferenceTypes

### ISSUE THREAD

**Issue by cartermp** [dotnet/roslyn#34759]
`<NullableContextOptions >` feels like we're leaking an implementation detail. Even if the valid values that can be passed in are the same, the bulk will be `enable` or `disable`, so it should probably just be called `<NullableReferenceTypes>`.

**Comment by jcouv** [comment]
Please let us know when the decision is firm and we'll start executing on it (probably for 16.2). I'm not sure who all needs to be involved (probably a thread including LDM would be good).

**Comment by jcouv** [comment]
We landed on "Nullable" for the name.
Subsumed by https://github.com/dotnet/roslyn/issues/35432
