### ISSUE TITLE
Convert foreach to Linq not suggested

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34750]
This applies to Visual Studio 2019 release.

I tried a simple example of convert foreach to Linq using the the following code

```
using System;
using System.Collections.Generic;
using System.Linq;

class Program
{
    static void Main()
    {
        List&lt;string&gt; words = new List&lt;string&gt;( ) { &quot;hello&quot;, &quot;world &quot; };
        
        foreach( string word in words )
        {
            System.Console.WriteLine( word );
        }
    }
}
```
Doing Ctrl dot on the foreach convert to Linq was not suggested, convert to for was. There is a comment on this issue https://developercommunity.visualstudio.com/content/problem/402010/convert-linq-to-foreach-is-not-always-suggested.html saying &quot;Only simple expressions are allowed now.&quot; however the above example is about as simple as I can imagine. 
So is there something else you have to do to switch this on or has it been removed?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/513784/convert-foreach-to-linq-not-suggested.html

**Comment by svick** [comment]
How do you expect that code to be converted to LINQ? If you're talking about `.ForEach`, then:

1. that's not LINQ,
2. using that method is often considered a bad practice.

**Comment by ivanbasov** [comment]
The `.ForEach ` is a method available for List but not for `IEnumerable`. It is not a LINQ method. We should not consider its conversion for Lists to avoid confusion for other collections.

The code sample does not have anything other than .ForEach to be converted to LINQ. As soon as you change it to something like
```
            foreach (string word in words)
            {
                if (word.StartsWith("h"))
                {
                    System.Console.WriteLine(word);
                }
            }
```
it would provide you a conversion suggestion for `foreach `and `if`.

**Comment by elynch100** [comment]
This is still an issue (attempting to get the Convert To Linq to appear & work in the context menu when For Each is selected in the code editor) as of current production version of VS 2019 Community Edition 16.6.3. 

https://docs.microsoft.com/en-us/visualstudio/ide/reference/convert-foreach-linq?view=vs-2019 indicates VB is supported.

C# currently does work. I haven't found a way to get VB to work with any For Each loop.

![ConvertForEachToLinq-VB-00124](https://user-images.githubusercontent.com/25542794/87111222-ce192b80-c236-11ea-901a-d8734705edf5.png)

**Comment by CyrusNajmabadi** [comment]
There is no VB implementation of this feature @elynch100 .  We would take a community contribution to provide one if you're interested though!

**Comment by elynch100** [comment]
So does the page need to be updated? 
https://docs.microsoft.com/en-us/visualstudio/ide/reference/convert-foreach-linq?view=vs-2019

This refactoring applies to:
C#
**Visual Basic**

**Comment by CyrusNajmabadi** [comment]
Seems like it.  @mikadumont ?

**Comment by mikadumont** [comment]
I can go ahead and update the doc.
