### ISSUE TITLE
Support GetServiceAsync in Roslyn

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#34776]
VS is moving from GetService to GetServiceAsync but Roslyn's service is staying as synchronous API.

all is good usually, but there is some case where we want to set up service based on some info from VS which we need to use GetServiceAsync to get information from BG such as 
this
http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Experimentation/VisualStudioExperimentationService.cs,35

right now, we have options either does what the above code does or make initialization lazy.

it would be nice if we also have code path that is GetServiceAsync that calls InitializeAsync after service creation.

and we have something like IAsyncLanguageService and IAsyncWorkspaceService that uses the new pattern.

the point is having a supported way to get a service asynchronously whatever way that is.

**Comment by CyrusNajmabadi** [comment]
We use GetServiceAsync now.
