### ISSUE TITLE
"Use auto property" suggests removing a field in a serializable class

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#34783]
**Version Used**: 

**Steps to Reproduce**:

"Use Auto property" suggests removing a field in a serializable class with zero indication that this will break serialization.

``` VB
        <Serializable()>
        Private NotInheritable Class ResourcesDataFormat
            'List of resources
            Private ReadOnly _resources() As Resource ' <!-- Use Auto Property

            Public Sub New(Resources() As Resource)
                _resources = Resources
            End Sub

            Public ReadOnly Property Resources() As Resource()
                Get
                    Return _resources
                End Get
            End Property

        End Class

```

**Expected Behavior**:

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
I don't think we know that serialization will depend on internal details of the class.  Is there a well known set of attributes that indicates that some system out there will depend on internal details?  If so, we can add them as a potential warning-blacklist.

**Comment by HaloFour** [comment]
@CyrusNajmabadi 

> I don't think we know that serialization will depend on internal details of the class. 

To my understanding every serializer that cares about that attribute will absolutely care about the internal details of the class by default and a field rename will break the contract.  We're talking about the `IFormatter`-based serializers like `BinaryFormatter`.  Any of the other serializers, including the WCF `NetDataContractSerializer`, don't rely on that attribute.
