### ISSUE TITLE
Freezing up when getting compilation

### ISSUE THREAD

**Issue by VasilievSerg** [dotnet/roslyn#34782]
Hello.
There is .sln file, which contains 2 projects: A and B. The  'A'  project refers to the 'B' project and vice versa.

Getting compilation for both projects goes from two threads: `project.GetCompilationAsync(cancellationToken).Result`

It freezes at the stage of getting a compilation.
External code (call stack) for both threads in the moment when they are expecting to get compilation:
```
mscorlib.dll!System.Threading.ManualResetEventSlim.Wait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)
mscorlib.dll!System.Threading.Tasks.Task.SpinThenBlockingWait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)
mscorlib.dll!System.Threading.Tasks.Task.InternalWait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)
mscorlib.dll!System.Threading.Tasks.Task<Microsoft.CodeAnalysis.Compilation>.GetResultCore(bool waitCompletionNotification)
```
CodeAnalysis packages version: **3.0.0**
MSBuild packages version: **16.0.461**

The link to download the project, on which the problem is reproduced: https://drive.google.com/open?id=1ajzX5w5Q97mp67zJZL8U3dhXSMUBl-8o

I hope, this information will be useful.
Thanks.

**Comment by CyrusNajmabadi** [comment]
Closing out as this has been heavily rewritten.  Note: code should use async, not .result.
