### ISSUE TITLE
Crash in VisualStudioDiagnosticListTable with null _errorList

### ISSUE THREAD

**Issue by JsonFreeman** [dotnet/roslyn#3478]
I've hit a null ref exception at https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioDiagnosticListTable.cs#L52 because _errorList is null. Looking at the constructor for VisualStudioDiagnosticListTable, there is a branch where _errorList is initialized to null, and never reinitialized (https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioDiagnosticListTable.cs#L41). It looks like GetCurrentDataSource needs to handle the case where the errorList is null.

**Comment by JsonFreeman** [comment]
Here is the stack trace:
>	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.VisualStudioDiagnosticListTable.GetCurrentDataSource() Line 52	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.VisualStudioDiagnosticListTable.AddTableSourceIfNecessary(Microsoft.CodeAnalysis.Solution solution) Line 82	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.AbstractTable<System.__Canon,System.__Canon>.OnWorkspaceChanged(object sender, Microsoft.CodeAnalysis.WorkspaceChangeEventArgs e) Line 65	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Workspace.RaiseWorkspaceChangedEventAsync.AnonymousMethod__1(System.EventHandler<Microsoft.CodeAnalysis.WorkspaceChangeEventArgs> handler) Line 57	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.EventMap.Registry<System.__Canon>.Invoke(System.Action<System.__Canon> invoker) Line 115	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.EventMap.EventHandlerSet<System.EventHandler<Microsoft.CodeAnalysis.WorkspaceChangeEventArgs>>.RaiseEvent(System.Action<System.EventHandler<Microsoft.CodeAnalysis.WorkspaceChangeEventArgs>> invoker) Line 172	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Workspace.RaiseWorkspaceChangedEventAsync.AnonymousMethod__0() Line 57	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskExtensions.ContinueWithAfterDelay.AnonymousMethod__1(System.Threading.Tasks.Task _) Line 221	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskExtensions.SafeContinueWith.AnonymousMethod__0(System.Threading.Tasks.Task antecedent) Line 61	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskExtensions.SafeContinueWith<bool>.AnonymousMethod__0(System.Threading.Tasks.Task t) Line 128	C#
 	mscorlib.dll!System.Threading.Tasks.ContinuationResultTaskFromTask<bool>.InnerInvoke() Line 111	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Line 2861	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2767	C#
 	mscorlib.dll!System.Threading.Tasks.SynchronizationContextTaskScheduler.PostCallback(object obj) Line 694	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs) Line 111	C#
	...
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam) Line 392	C#

**Comment by Pilchie** [comment]
Can you describe what you were doing?  Is this something that you think needs to be fixed for our 1.0 release?

**Comment by JsonFreeman** [comment]
I installed yesterday's visual studio, launched it, and tried to open a typescript file. I immediately got this crash, so I do think it should be fixed for 1.0. I'm going to try today's build of VS, and I can report back on whether it reproduces there.

**Comment by JsonFreeman** [comment]
I am still getting this crash on today's build.

**Comment by Pilchie** [comment]
Tag @srivatsn

**Comment by JsonFreeman** [comment]
Also, if you discover any workarounds, those would be helpful as well.

**Comment by amcasey** [comment]
@pnelsonmsft is reporting the same thing in our current base drop (unpatched).

**Comment by pnelsonmsft** [comment]
Repro:  Open project \D14Rel\src\debugger\concord\ManImpl\src\vsdebugeng.manimpl.csproj ... crashes with this call stack immediately

**Comment by amcasey** [comment]
FYI @heejaechang

**Comment by heejaechang** [comment]
I looked it with Patrick. _errorList can't be null in VS. so digging more with David revealed that the drop was broken. the reason it was broken was that, he did uninstall and re-install and error list dll that got patched didn't get uninstalled properly. so drop had old error list dll installed in the gac. that was the reason error list didnt work.

...

@JsonFreeman can you try uninstall Microsoft.VisualStudio.ErrorListPkg from gac and see whether it works?

**Comment by JsonFreeman** [comment]
@heejaechang Yes, that worked! Thanks very much!

**Comment by heejaechang** [comment]
I updated getting start page for current dog food bits how to troubleshoot the issue.
