### ISSUE TITLE
Add a suggestion to remove ConfigureAwait where the synchronization context is null

### ISSUE THREAD

**Issue by fekberg** [dotnet/roslyn#34818]
As there is no synchronization context ASP.NET Core, it would be beneficial to have an analyzer hint when `ConfigureAwait(false)` doesn't have an impact.

In the following example adding `ConfigureAwait(false)` does nothing as this is in ASP.NET Core. Having an analyzer identify that the synchronization context is in fact null would be great.

```
public class IndexModel : PageModel
{
    public async Task OnGet()
    {
        var repository = new UserRepository();

        var id = await repository.Create("Filip Ekberg")
            .ConfigureAwait(false);
    }
}
```

**Comment by miloush** [comment]
How would such an analyser know that there is no synchronization context at runtime? Nothing prevents you from using one even if the framework does not use any itself.

**Comment by sharwell** [comment]
This is supported by the Banned API Analyzer, which is part of [dotnet/roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers). Preventing calls to `ConfigureAwait` is one of the active use cases for this analyzer: dotnet/project-system#4389.

**Comment by fekberg** [comment]
@miloush The synchronization context is never captured in ASP.NET Core, if you explicitly use something else in your asynchronous method I'd argue that `ConfigureAwait(false)` is still pointless.

Thanks @sharwell, had no idea something like that was already available. That's great! Sorry to take up your time with a useless github issue :)

**Comment by sharwell** [comment]
> Sorry to take up your time with a useless github issue :)

It's no problem at all, we're happy you found us and happy we had an answer for you 😄
