### ISSUE TITLE
Re-enable upload of build binaries to myget after version update.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#3481]
This is a tracking bug to ensure that we re-enable uploading of our build packages to myget once #3007 is resolved.

**Comment by tannergooding** [comment]
@ManishJayaswal FYI.

**Comment by tannergooding** [comment]
@tmeschter: This has been resolved now, correct?

**Comment by tmeschter** [comment]
@tannergooding Yes. I've confirmed that packages are uploading to MyGet.

**Comment by tmeschter** [comment]
Redirecting to Tanner for verification.
