### ISSUE TITLE
VS 2019 VB editor is very slow

### ISSUE THREAD

**Issue by vbcodec** [dotnet/roslyn#34815]
**Version Used**: 
VS 2019 Community
OS: win 8.1

**Steps to Reproduce**:
Load projest with 50K+ lines

**Expected Behavior**:
As fast as VS 2017 or faster
**Actual Behavior**:
When I make / remove error in code, then editor need some 20 seconds to show / hide errors in Error List and show / remove (red) error squiggles in code. In VS 2017 on the same machine it is much faster (2-3 sec). Projest have some 50K lines, on small project speed seems to be the same as VS 2017

**Comment by VBAndCs** [comment]
Me too!
Sometimes the build fails but with no errors in the error list, because they are not spotted yet!

**Comment by sharwell** [comment]
@vbcodec @VBAndCs Can you file a performance report using the steps here:
https://aka.ms/reportPerf

Once you create the issues on Developer Community, can you add links to them here so we can find them easily?

**Comment by VBAndCs** [comment]
I did this before.
You can generate the error. Open a file of a rather big solution with a text editor, and make a ayntax error. Open the project with VS.Net and run the project immediately. For me, the build fails but the error list doen't show, and when I show it, it is empty. It is a repeated case for me.
