### ISSUE TITLE
solution.WithDocumentFilePath does not update _filePathToDocumentIdsMap

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#34837]
With the latest roslyn

**Steps to Reproduce**:
Create a test workspace with 1 document, change the document's file path, then try to get the documentId from the file path.

Reproduction code in a test.
```csharp
using (var workspace = TestWorkspace.CreateCSharp(markup))
{
    var documentPath = "someNewPath/" + workspace.Documents.First().FilePath;
    var updatedSolution = workspace.CurrentSolution.WithDocumentFilePath(workspace.Documents.First().Id, documentPath);
    workspace.ChangeSolution(updatedSolution);
    var newFilePath = workspace.CurrentSolution.Projects.First().Documents.First().FilePath;
    var documentIdsWithNewFilePath = workspace.CurrentSolution.GetDocumentIdsWithFilePath(newFilePath);
}
```

```newFilePath``` prints "someNewPath/test1.cs", but
```documentIdsWithNewFilePath``` is empty but should contain the documentId for the updated document.

**Comment by jasonmalinowski** [comment]
Oh that's not good. :smile:

**Comment by jasonmalinowski** [comment]
@dibarbet Did you discover this as a root problem of some other issue?

**Comment by dibarbet** [comment]
@jasonmalinowski I discovered this while trying to write some unit tests:
For some LSP work, I needed to change the file path of a document in a test to be a valid URI path.  I attempted to use ```.WithDocumentFilePath``` to do this.  The code I was trying to test calls ```GetDocumentIdsWithFilePath``` which did not return anything when called with the file path passed to ```WithDocumentFilePath```.  This eventually led me to find that _filePathToDocumentIdsMap wasn't updating during ```.WithDocumentFilePath```.

So not a customer facing issue, but a potentially misleading API :)

**Comment by jasonmalinowski** [comment]
@dibarbet: OK, I didn't want to move it out of 16.1 for triage purposes until I had a reason. Thanks!
