### ISSUE TITLE
Allow Code Navigation to {} Patterns

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#34838]
**Version Used**: 

Visual studio 2019, C# 8.0

**Steps to Reproduce**:

create a solution in visual studio with the following code:

```csharp
public class C
{
    public bool IsNotNullOrEmpty(string? str) => str is {} notNullStr && notNullStr.Length != 0;
}
```

Put your cursor in the `{}` pattern and press F12, or right click on the pattern and select "Go To Definition"

**Expected Behavior**:
navigates to the definition of `string`

**Actual Behavior**:
"Cannot Navigate to the symbol under the caret "

**Comment by CyrusNajmabadi** [comment]
Closing out do to lack of feedback.
