### ISSUE TITLE
.editorconfig naming convention for private protected

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34846]
<p>In current version I am able to write</p><pre>dotnet_naming_symbols.private-symbols.applicable_accessibilities = private, protected
</pre><p>But I am not able to specify that I want naming style to apply only on protected internal or private protected members. Please support </p><pre>dotnet_naming_symbols.private-symbols.applicable_accessibilities = private, private protected
</pre><p>Because we want same naming convention for private and private protected members in our project. This is not possible in current .editorconfig</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/518200/editorconfig-naming-convention-for-private-protect.html
VSTS ticketId: 839788_
_These are the original issue comments:_

Jane Wu [MSFT] on 4/8/2019, 02:41 AM (12 hours ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by sharwell** [comment]
The identifier for `private protected` accessibility in .editorconfig is `private_protected`. This was implemented in #27331. 👍
