### ISSUE TITLE
Autoformat on paste in code?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34847]
<p>I'm having to go into Edit &gt; Format Document every time I paste code in C# to format it.  Can it automatically be done just like when I draw text around within the editor?</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/513878/autoformat-on-paste-in-code.html
VSTS ticketId: 835969_
_These are the original issue comments:_

Jane Wu [MSFT] on 4/3/2019, 03:16 AM (5 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
In Tools|Options you can go here:

![image](https://user-images.githubusercontent.com/4564579/55778123-e65c3280-5a56-11e9-830e-6ed4e21f3016.png)

Make sure "automatically format on paste" is checked:

![image](https://user-images.githubusercontent.com/4564579/55778137-f116c780-5a56-11e9-898b-7c9a5116b40f.png)

**Comment by jinujoseph** [comment]
Thats the right settings.
Thanks @CyrusNajmabadi .
