### ISSUE TITLE
Use of unannotated unconstrained type parameter in nullable enabled code

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#34843]
The issue is the treatment of a reference to a type parameter that was declared in a disabled context but referenced in an enabled context.  The compiler treats such as reference as unannotated today, but there is a belief that the LDM intends such a reference to be considered oblivious.  We may need LDM confirmation that is the intent.

See also https://github.com/dotnet/roslyn/issues/30214 and https://github.com/dotnet/roslyn/issues/30214#issuecomment-425509720

``` c#
#nullable disable
class A<T1, T2, T3> where T2 : class where T3 : object
{
#nullable enable
    void M2()
    {
        T1 x2 = default; // is a warning deserved here?
        T2 y2 = default; // is a warning deserved here?
        T3 z2 = default; // is a warning deserved here?
    }
}
```

The is was resolved in https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-04-15.md#declarations-with-constraints-declared-in-nullable-disabled-code .  None of them deserve warnings.

**Comment by gafter** [comment]
Documented as https://github.com/dotnet/csharplang/issues/2409 and queued for LDM resolution.

**Comment by AlekseyTs** [comment]
@gafter If you are working on this issue, please assign it to yourself.

**Comment by gafter** [comment]
I am not working on anything until the middle of next week.

**Comment by jcouv** [comment]
As of 16.5p3, the above code doesn't produce any nullability warnings. I think this is the result of Chuck's earlier change to track the `[MaybeNull]T` state separately.
I'll go ahead and close this issue. Thanks

![image](https://user-images.githubusercontent.com/12466233/73407239-55886900-42ad-11ea-97f5-f3b7dce691e9.png)
