### ISSUE TITLE
Word Errors

### ISSUE THREAD

**Issue by shaggygi** [dotnet/roslyn#3485]
Here are a few more wording errors in code.

1. The following file includes two words.   'teh' and 'contaiing' in comment.
https://github.com/dotnet/roslyn/blob/0382e3e3fc543fc483090bff3ab1eaae39dfb4d9/src/Compilers/VisualBasic/Portable/Syntax/LambdaUtilities.vb
2. The following file includes two words.  'teh' and 'reprsented' in comment.
https://github.com/dotnet/roslyn/blob/ff8413e8d92e4886f4e7348e856e588ba43fd55d/src/Features/VisualBasic/EditAndContinue/VisualBasicEditAndContinueAnalyzer.vb
3. The following file includes the word 'lamda' in comment.
https://github.com/dotnet/roslyn/blob/0382e3e3fc543fc483090bff3ab1eaae39dfb4d9/src/Compilers/VisualBasic/Portable/Lowering/LambdaRewriter/LambdaFrame.vb

**Comment by shaggygi** [comment]
I'm aware the numbers above are all '1'.  They show 1, 2, 3 and 4 when I go into edit mode.  I put in a ticket to GitHub as this looks like a formatting bug.

**Comment by jasonwilliams200OK** [comment]
Looks like you have a Pull Request to offer. :wink:

**Comment by shaggygi** [comment]
@jasonwilliams200OK Good motivation.  I've not attempted a PR until now.  I read over some of the documentation a little and installed the tools.  I created the PR, but will need someone more experienced to verify/merge and such.  Also, I had problems with one of the solutions, so I created another issue #3489 for now.

**Comment by AdamSpeight2008** [comment]
All you need is GitHub and a text editor to submit a Pull Request.

**Comment by jasonwilliams200OK** [comment]
> 
All you need is GitHub and a text editor to submit a Pull Request.

In this age and era, all you need is a GitHub account and a web browser for: http://ide.c9.io/ which enables you to send PRs even from an iPad :smile:

**Comment by AdamSpeight2008** [comment]
@jasonwilliams200OK And also a working internet connection. :tongue:
