### ISSUE TITLE
Unloadable Assembly Produced for structs containing struct of T, even when T avoids circularity

### ISSUE THREAD

**Issue by drunkcod** [dotnet/roslyn#34865]
**Version Used**:  VS2017 with all updates applies, also dotnet core 2.2.101

**Steps to Reproduce**:
1. Compile and run the following:
```csharp
using System;

namespace StructuralMadness
{
	class Program
	{
		public static void Main()
		{
			Console.WriteLine(new MyThing());
		}

		struct IdOf<T> { }

		struct MyThing
		{
			public IdOf<MyThing> Id;
		}
	}
}
```
**Expected Behavior**:
Print: StructuralMadness.Program+MyThing
**Actual Behavior**:
Crashes with:
```
Unhandled Exception: System.TypeLoadException: Could not load type 'StructuralMadness.Program+MyThing' from assembly 'ConsoleApp3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at StructuralMadness.Program.Main()
```

Substituting either of the "struct" for class avoids the issue. 
I'm assuming somewhere there's a problem in assuming the size of "T" needs to be fully resolved before instantiation.

**Comment by tannergooding** [comment]
This should probably be logged against dotnet/coreclr

**Comment by KalleOlaviNiemitalo** [comment]
I get the same exception with .NET Framework 4.7.2 (Release 461814) on Windows 10, so it is not specific to .NET Core.

The rule against recursive struct definitions in ECMA-335 6th edition §II.13 (Semantics of value types) does not forbid this, nor do I think it should. The Microsoft implementation-specific notes downloadable from [ECMA C# and Common Language Infrastructure Standards](https://visualstudio.microsoft.com/license-terms/ecma-c-common-language-infrastructure-standards/) don't say anything more about this.

**Comment by KalleOlaviNiemitalo** [comment]
Using Visual Studio 2017 version 15.9.11 for UWP with .NET Native, `new MyThing().ToString()` returns "App1.MainPage+MyThing" with no exception. If I disable .NET Native, then it throws TypeLoadException again.

**Comment by gafter** [comment]
Dup of https://github.com/dotnet/coreclr/issues/7957

**Comment by Korporal** [comment]
Apparently this particular type load failure has been a recognized and acknowledged bug for over three years.

**Comment by gafter** [comment]
@Korporal This bug has been around much longer than we've been using github.  If it were easy to fix it would have been fixed by now.

Just a reminder - `dotnet` is open source and contributions are most welcome!

**Comment by Korporal** [comment]
@gafter - Really? its that old. OK yes it must be non trivial I understand that. I am simply in no place to attempt to fix it, there's a learning curve for everything in the CLR and that alone makes it prohibitive, perhaps if I was retired I'd be tempted but if the experts here aren't attempting it, I know I'd have a struggle.

I guess I'll just have to wait to resume my work...

**Comment by CyrusNajmabadi** [comment]
> but if the experts here aren't attempting it, I know I'd have a struggle.

Or the experts simply don't think ti's a worthwhile issue to invest time into.  i.e. it may be simple to fix.  But it may also be of such low benefit that even that low effort isn't worth the time.
