### ISSUE TITLE
Visual Studio 2019 seems to forget custom XML Schemas

### ISSUE THREAD

**Issue by Z3roCoder** [dotnet/roslyn#34864]
**Version Used**: 
Visual Studio 2019 Enterprise

**Steps to Reproduce**:

1. Create a Custom XML Schema
2. Use the Schema in Visual Studio 2019 (Open a XML-File, Toolbar "XML" -> Schemas -> Add the Schema)
3. Observe IntelliSense working
4. Restart VS2019
5. Open XML file again
6. Intellisense no more working, no more code highlighting on Syntax Errors, etc.

**Expected Behavior**:
Even through a VS2019 restart, the XML Schemas should be kept.

**Actual Behavior**:
VS2019 seems to just "forget" the schemas, as they are no longer in the schemas list.

** Addendum **
I hope that this is the right place to report this behavior. If not, please tell me where I have to report this - It's making work tedious, either having to re-add the Schemas all the time or doing it without IntelliSense... Thank you.

**Comment by CyrusNajmabadi** [comment]
This sounds like an xml editor issue.  If so, can you file an issue here instead:

![image](https://user-images.githubusercontent.com/4564579/55822217-f9e9b680-5ab3-11e9-952d-0ab32bd86389.png)

Thanks!

**Comment by jinujoseph** [comment]
@CyrusNajmabadi is right 
Could you pls file a VSfeedback issue and it will get routed to right team

**Comment by Z3roCoder** [comment]
Sure thing, thanks!

Jinu <notifications@github.com> schrieb am Di., 9. Apr. 2019, 19:47:
