### ISSUE TITLE
Go to Member - see all members even if you type nothing

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#34877]
Customer request copying here.

> Go to Member - In resharper, If you type nothing, you can see all members. But in VS, it will show nothing. It is sometimes unfriendly, because I just know there is one method indeed, but I cannot recall its name before seeing it.

**Expected Behavior**:
<img width="348" alt="bug" src="https://user-images.githubusercontent.com/46729679/55830336-894b9580-5ac5-11e9-99f6-6ba6728f01b2.png">

**Actual Behavior**:
<img width="436" alt="bug2" src="https://user-images.githubusercontent.com/46729679/55830400-aaac8180-5ac5-11e9-9408-7c6ffc1e3e13.png">

**Comment by billxc** [comment]
vote up.

**Comment by kendrahavens** [comment]
I've opened the issue on [developer community here](https://developercommunity.visualstudio.com/idea/542570/go-to-member-see-all-members-even-if-you-type-noth.html).

**Comment by jasonmalinowski** [comment]
The design review generally agreed we should do this, but since we'd have to ask the editor team for additional work we should wait for additional votes before scheduling the work.

**Comment by CyrusNajmabadi** [comment]
This shoudl be driven by platform/editor.  @veler if you guys want to take this.  You'd need to have an API basically asking us for the members in the current type.  If you add such an API, we will implement our end of it.
