### ISSUE TITLE
Ranges on arrays behavior changed?

### ISSUE THREAD

**Issue by tomrus88** [dotnet/roslyn#34885]
In older C# 8.0 previews following code would return a ref
`byte[] array = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 };`
`Span<byte> subArray = array[1..];`
`subArray[0] = 10; // array[1] is now 10 too`

But in current version subArray now a separate copy. Is that intended? Why?

**Comment by agocke** [comment]
This was a bug: https://github.com/dotnet/roslyn/issues/31889. Also, it returned a ref of the copy. It never returned a ref to the original array.
