### ISSUE TITLE
Mispelled Word in APISampleUnitTestsVB.sln FAQ.vb

### ISSUE THREAD

**Issue by shaggygi** [dotnet/roslyn#3489]
1. The following file includes the word 'declration' in code.
https://github.com/dotnet/roslyn/blob/e002449e7e77d91e26a6204fb26b9619b7400c41/src/Samples/VisualBasic/APISampleUnitTests/FAQ.vb

I attempted to change this with PR #3488, but had problems opening the solution locally.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/commit/6b55eee129271054ee09d928139d7682dbdca3ce#diff-95cb91cdc607a4d4b6b797db97f77935
