### ISSUE TITLE
AD0001 RemoveUnusedParameters Out of Memory Exception

### ISSUE THREAD

**Issue by ooples** [dotnet/roslyn#34894]
I'm using the latest version of Visual Studio 2019 Preview and I can't run my project anymore because I'm now getting this error message

AD0001 'Microsoft.CodeAnalysis.CSharp.RemoveUnusedParametersAndValues.CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer' threw an exception of type 'System.OutOfMemoryException' with message 'Exception of type 'System.OutOfMemoryException' was thrown.'

**Comment by YairHalberstadt** [comment]
Do you have a sample solution where this occurs?

**Comment by mavasani** [comment]
@ooples Can you please provide a repro solution or a performance trace? Otherwise, the issue is not actionable on our end.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of response.
