### ISSUE TITLE
VS 2019 Preview 1 - Refactor.ReorderParameters Command Starts With Period

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34900]
The command description for Refactor.ReorderParameters erroneously starts with a period. See attached screenshot.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/400939/vs-2019-preview-1-refactorreorderparameters-comman.html

![image](https://user-images.githubusercontent.com/12449387/55861373-1a088c80-5b2b-11e9-9df2-38fda836011a.png)

**Comment by jinujoseph** [comment]
declared [here ](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2FVSCommonContent%2Fprofiles%2FkeyboardSchemes%2FVisual%20CSharp%202005.vssettings&version=GBlab%2Fd16.0stg&line=61&lineStyle=plain&lineEnd=62&lineStartColumn=1&lineEndColumn=1)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
