### ISSUE TITLE
URLs in code comments aren't correct when URL contains the # character

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#3490]
This is a regression from VS2013.

VS2015:

![image](https://cloud.githubusercontent.com/assets/1249087/8146839/d69520b8-121c-11e5-8004-b8fb64eee54c.png)

VS2013: 

![image](https://cloud.githubusercontent.com/assets/1249087/8146842/05f119d4-121d-11e5-9605-1a8b865646fb.png)

**Comment by Pilchie** [comment]
Roslyn doesn't actually own the URL tagger (though we are thinking of adding our own at a later point).  At the moment it's owned by the editor team.  Do you want to file a connect bug for them about this so you can see updates, or would you like me to just file a bug on your behalf?

**Comment by AdamSpeight2008** [comment]
Isn't the URL itself parsed as URL or is just treated as a text in a XML Comment.

**Comment by Pilchie** [comment]
No, it's not parsed by the language parser at all.

**Comment by JoshVarty** [comment]
Thanks, I've filed this here: https://connect.microsoft.com/VisualStudio/feedback/details/1436963/urls-in-code-comments-arent-correct-when-url-contains-the-character
