### ISSUE TITLE
Can we special-case some more core framework methods for nullability?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#34901]
The compiler already special-cases some methods like String.IsNullOrEmpty and Debug.Assert:
https://github.com/dotnet/roslyn/blob/43f2329f0e4738b0e05812e68e9f82b78945d74c/src/Compilers/CSharp/Portable/Symbols/ExtraAnnotations.cs
presumably until the relevant members in Corelib are appropriately annotated.

Can we special-case some more, and in particular ones we don't currently have attributes that would let us annotate appropriately?

In particular, there are some core methods with complicated patterns but that are showing up really frequently in code, and it'd be very helpful if the compiler could appropriately suppress nullability warnings for common cases.

1. `Interlocked.CompareExchange(ref target, somethingNonNull, null)`

This is often used for lazy initialization, and shows up in a lot of properties, e.g.
```C#
private object? _syncRoot;

public object SyncRoot
{
    get
    {
        if (_syncRoot == null)
        {
            Interlocked.CompareExchange<object?>(ref _syncRoot, new object(), null);
        }
        return _syncRoot; // compiler warns here
    }
}
```
The compiler currently warns on `return _syncRoot;` because it can't see that the `CompareExchange` will set `_syncRoot` to a non-null value if it's currently `null` (obviously there could be other code racing with this code that would result in that not being true, but that's the case in general for nullability flow analysis and multi-threading issues are ignored).

It's not clear what an attribute for this pattern would look like, and we don't currently have one; until we do, it'd be helpful if the compiler could special-case this.

The compiler would already appropriately suppress the warning if the code were instead:
```C#
if (_syncRoot == null)
{
    _syncRoot = new object();
}
return _syncRoot;
```
so it's a bit ironic that the stronger threading semantics actually cause the compiler to warn :smile:

2. `Interlocked.Exchange(ref target, somethingNonNull)`, `Volatile.Write(ref target, somethingNonNull)`

Similarly, these methods write the second argument to the first, but we don't have an attribute to express that concept, and it's not clear what that would look like.

Related to https://github.com/dotnet/roslyn/issues/26761.  If we think it's likely we'll get attributes for these cases for C# 8 / .NET Core 3.0, then this issue can be closed.

cc: @cston, @jcouv, @dotnet/nullablefc

**Comment by terrajobst** [comment]
I like that.

**Comment by jcouv** [comment]
We've implemented the design spec'ed in https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-05-15.md which includes some well-known methods (Interlocked.Exchange, Equals, etc)
I'll go ahead and close this. Thanks
