### ISSUE TITLE
Inline Rename with Multiple Carets

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#34903]
**Version Used**: 
Dev16 RTM

**Steps to Reproduce**:

1. New C# console app
2. F2 on Program to enter Rename mode
3. Cltr+Alt+Click twice inside the green identifier to have two carets
4. Delete or type a character

**Expected Behavior**:
Works

**Actual Behavior**:
Exception

http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Wpf/InlineRename/AbstractInlineRenameUndoManager.cs,51

Assumes a single caret

Bug found courtesy of @DavidKarlas

**Comment by KirillOsenkov** [comment]
@jasonmalinowski fun one!

**Comment by jasonmalinowski** [comment]
Dunno, the behavior you're seeing is what I'd expect would happen. 😛

**Comment by KirillOsenkov** [comment]
I've just discovered that this is a dupe of https://github.com/dotnet/roslyn/issues/34866

**Comment by sharwell** [comment]
They are related, but not exactly a duplicate.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not likely to do any special investments on this scenario without more customer feedback.
