### ISSUE TITLE
Allow out parameter widening

### ISSUE THREAD

**Issue by mnmr** [dotnet/roslyn#34906]
Given the following code bits (where both CarNode and PlaneNode implement INode):

```
       public ConcurrentDictionary<TreeKey, CarNode> CarNodesByKey { get; } = new ConcurrentDictionary<TreeKey, CarNode>();
        public ConcurrentDictionary<TreeKey, PlaneNode> PlaneNodesByKey { get; } = new ConcurrentDictionary<TreeKey, PlaneNode>();

        public bool TryGetNode(ENodeType nodeType, TreeKey key, out INode node)
        {
            switch (nodeType)
            {
                case ENodeType.Cars:
                    return CarNodesByKey.TryGetValue(key, out node);
                case ENodeType.Planes:
                    return PlaneNodesByKey.TryGetValue(key, out node);
                default:
                    node = null;
                    return false;
            }
        }
```

The problem here is that this does not compile, because the `out node` is `INode` rather than the specific type declared for the collection. But in normal C# code it is perfectly valid to declare a variable of a less specific type and assign a specific type to it, e.g. `INode node = new CarNode()`.

Why is the C# compiler being a PITA in this case? Can we fix it so that scenarios like this are less painful? 

To work around this, each case in the switch must now declare a local variable for the out parameter, so the code looks like this:

```
        public bool TryGetNode(ENodeType nodeType, TreeKey key, out INode node)
        {
            switch (nodeType)
            {
                case ENodeType.Cars:
                    if (CarNodesByKey.TryGetValue(key, out var carNode))
                    {
                        node = carNode;
                        return true;
                    }
                    node = null;
                    return false;
                case ENodeType.Planes:
                    if (PlaneNodesByKey.TryGetValue(key, out var planeNode))
                    {
                        node = planeNode;
                        return true;
                    }
                    node = null;
                    return false;
                default:
                    node = null;
                    return false;
            }
        }
```

This does get tedious to work with rather quickly.

**Comment by jaredpar** [comment]
> Why is the C# compiler being a PITA in this case?

That's because `out` is a C# invention, not anything inherently supported by the .NET runtime. To the runtime `out` is really just `ref`. This means it's invariant and do actions like use `INode` instead of `Node`. 

> Can we fix it so that scenarios like this are less painful?

Seems unlikely. The problem here is today it's competely legal to say override a `virtual` member which has a parameter declared as `out` with a parameter declared as `ref`. This is a common pattern in say VB and F#. Hence making it no longer invariant is a pretty big breaking change.

**Comment by mnmr** [comment]
Ok, that makes sense. Still slightly sad about it though :)
