### ISSUE TITLE
[C# Feature Request] [Small but useful] Allow overriding property accessors (syntax sugar)

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#3491]
Situation:

``` csharp
public abstract class Sample
{
    public abstract string Name { get; }
}

public interface INameable
{
    string Name { get; set; }
}

public class ConcreteSample : Sample, INameable
{
    //???
}
```

Current language workaround:

``` csharp
public class ConcreteSample : Sample, INameable
{
    public override string Name
    {
        get { return ((INameable)this).Name; }
    }

    string INameable.Name { get; set; }
}
```

Suggested syntax:

``` csharp
public class ConcreteSample : Sample, INameable
{
    public string Name { override get; set; }
}
```

Cases:

http://stackoverflow.com/questions/2026546/override-get-but-not-set

http://stackoverflow.com/questions/1227205/why-can-i-not-add-a-set-accessor-to-an-overriden-property

http://stackoverflow.com/questions/1169571/adding-a-set-accessor-to-a-property-in-a-class-that-derives-from-an-abstract-cla

http://stackoverflow.com/questions/6058352/adding-setters-to-properties-in-overrides

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
