### ISSUE TITLE
CSharpOperationFactory `CreateInternal` Should Not Capture

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#34918]
https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs#L321

This captures the `boundNode` element in the lambda for `getChildren`, and it doesn't need to. We should update this to be non-capturing.

I'm going to mark this up for grabs so that anyone in the community who would like to make a small improvement can do so, as I am focusing on the nullable api at the moment. If no has taken this up after that work is completed, I'll probably fix this.

**Comment by YairHalberstadt** [comment]
Since `LazyNoneOperation` doesn't know about `BoundNode` (it's in the wrong assembly), I don't see how this is possible without making `LazyNoneOperation` generic (which is obviously wrong)?

**Comment by 333fred** [comment]
We can make `LazyNoneOperation` specialized to CSharp and VB, much like we do with the other lazy operations. Then we can just hold onto the bound node in the `CSharpLazyNoneOperation` and create children when asked, instead of allocating a lambda and capturing the surrounding scope.
