### ISSUE TITLE
Make CommandLineProject available via NuGet

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#34936]
As of Roslyn 3.0.0 NuGet family the type https://github.com/dotnet/roslyn/blob/0c47f8d51f7f6533b3045f36e63eb55b2f7647c2/src/Workspaces/Core/Desktop/Workspace/CommandLineProject.cs#L17 is not shipping via NuGet.

It is a useful type and we should find a new home for it.

**Comment by sharwell** [comment]
Duplicate of #34151
