### ISSUE TITLE
Option to Debug.Assert implicitly for null-forgiveness operator?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#34934]
As we've been annotating corelib, given a case like:
```C#
_some.Method(); // warns that _some may be null
```
we've often opted to "fix" the warning by doing something like:
```C#
Debug.Assert(_some != null, nameof(_some));
_some.Method();
```
instead of:
```C#
_some!.Method();
```
so that we get better debug/checked-build validation behavior, with an unexpected null fail fasting rather than resulting in an exception that might get eaten, might be harder to diagnose the root case, etc.

But the former is also more code and more clutter for something that should never happen.

Would it be possible for the compiler to provide an option that would enable emitting a Debug.Assert when `!` is used in such situations (it would need to skip when value is known to be null, such as with the workaround for initializing fields, e.g. `private Something _some = null!;`)?  Then we could have the simpler suppression while still getting the more robust validation.

cc: @cston, @dotnet/nullablefc

**Comment by YairHalberstadt** [comment]
https://github.com/dotnet/csharplang/issues/2149

**Comment by jcouv** [comment]
I'll follow-up with @stephentoub to clarify.
`!` is a static-only construct (doesn't emit anything).

The current behavior seems fine, you don't need to write `Debug.Assert` in a scenario like:
```C#
        string? x = null;
        x!.ToString();
        x.ToString(); // no warning
```

**Comment by stephentoub** [comment]
> The current behavior seems fine, you don't need to write Debug.Assert in a scenario like

It's not a question of what I need to write but what I want to write.  In order to suppress a false positive warning, I generally have two options: use `!` or use `Debug.Assert`.  The former is generally simpler/shorter (unless employing the Assert could end up replacing a bunch of `!`s), but the latter provides additional validation that the former doesn't, in the form of fail-fasting rather than null ref exceptions that could end up getting caught, ability to exactly specify what was null rather than a null ref exception that's not specific, etc.  So the question is: could we have a mode where I get to write the shorter/simpler `!` but get the same validation in debug builds that `Debug.Assert` provides.

**Comment by jaredpar** [comment]
Closing as this behavior is implemented now.

**Comment by YairHalberstadt** [comment]
How can this be activated?

**Comment by jcouv** [comment]
Thanks for the ping @YairHalberstadt. Had to re-read the thread as I think I'd misunderstood it earlier today. 
Here's my understanding: the ask is for the `!` suppression to emit a null check (and throw something) in debug builds.

**Comment by jaredpar** [comment]
Re-closing. 

Agree I misread the question initially. At the same time though, given how established the semantics are now I don't see a realistic path for us adding this option.
