### ISSUE TITLE
Creates new SyntaxNode from 3rd-party

### ISSUE THREAD

**Issue by pjc0247** [dotnet/roslyn#34951]
I have a class something like below
```cs
internal class EvaluatedArgumentListSyntax : ExpressionSyntax
{ }
```
This one won't be compiled due to errors.
Some abstract methods have `internal` access modifier, so I can't make a derived class.

https://dotnetfiddle.net/r79Jyw

**Comment by CyrusNajmabadi** [comment]
That is by design. The roslyn SyntaxModel is not something you can inherit from.

**Comment by pjc0247** [comment]
If you think `roslyn` is a compiler __platform__, would be great to add more flexibility without modifying and re-compiling original sources.

**Comment by gafter** [comment]
@pjc0247 We don't think it is a compiler platform.

**Comment by pjc0247** [comment]
@gafter I didn't know that because 'Welcome to the .NET Compiler Platform ("Roslyn")' is the very first line of the this repository

**Comment by CyrusNajmabadi** [comment]
It's a platform for two of MS's .net compilers.  Not a .net platform for compilers in genreal.  i.e. it's parsed as: `((.net compiler) platform)`.  Not `.net (compiler platform)`.
