### ISSUE TITLE
Nullable reference on simple real-life cases

### ISSUE THREAD

**Issue by jairbubbles** [dotnet/roslyn#34958]
*I've been trying out the new nullable reference features on a project which uses null references a little bit too much.*

*Here are 4 cases that I naively though would work. I hope they are useful for you as they are real-life examples. Clearly some of the examples would need a rewrite but for the feature to be widely adopted (which I hope) Roslyn will need to help on the transition path.*

*I added a comment on each to explain what behavior I expected.*

*I hope it will be useful!*

**Version Used**: 

Visual Studio 2019 16.1.0 Preview 1

**Steps to Reproduce**:

- New class library .NET Standard
- Edit .csproj to enable the feature:
```xml
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <LangVersion>preview</LangVersion>
    <NullableContextOptions>safeonly</NullableContextOptions>
  </PropertyGroup>
```
- Paste this code:

```csharp
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace TestNullableReferences
{
    public class LazyInitWithMethod
    {
        List<string>? _items;

        private void InitList()
        {
            _items ??= new List<string>();
        }

        public List<string> Items()
        {
            InitList();

            // I would expect no warning but I get a CS8603: Possible null reference return
            return _items;
        }
    }

    public class BadCast
    {
        public DateTime GetTime(object value)
        {
            if (value is FileInfo)
            {
                var fileInfo = value as FileInfo;
                // I would expect no warning but I get a CS8602: Dereference of a possibly null reference
                return fileInfo.CreationTime;
            }

            return DateTime.MinValue;
        }
    }

    public class LinqLambda
    {
        readonly List<FileInfo> _files = new List<FileInfo>();

        public IEnumerable<FileInfo> GetMatchingItems(FileInfo? item = null)
        {
            // I would expect no warning but I get a CS8602: Dereference of a possibly null reference
            return item == null ? Enumerable.Empty<FileInfo>() : _files.Where(x => x.FullName == item.FullName); 
        }
    }

    public class LinqFunctions
    {
        readonly List<FileInfo> _files = new List<FileInfo>();

        public FileInfo GetFiles(DateTime date)
        {
            // I would expect a warning CS8603: Possible null reference return
            return _files.FirstOrDefault(x => x.CreationTime > date); 
        }
    }
}

```

**Comment by HaloFour** [comment]
For `LazyInitWithMethod` the NRT flow analysis doesn't track through method invocations.  As far the compiler is concerned `_items` is still possibly null.

`BadCast` is probably not a situation the flow analysis expects (and would be much more efficient dumping the first `is`, or converting to pattern matching.)

**Comment by CyrusNajmabadi** [comment]
For:
```c#
            if (value is FileInfo)
            {
                var fileInfo = value as FileInfo;
                // I would expect no warning but I get a CS8602: Dereference of a possibly null reference
                return fileInfo.CreationTime;
            }
```

The IDE will suggest you change that to:

```c#
            if (value is FileInfo fileInfo)
            {
                // I would expect no warning but I get a CS8602: Dereference of a possibly null reference
                return fileInfo.CreationTime;
            }
```

Which should remove the null warning.

**Comment by jairbubbles** [comment]
Hello, thanks for you answers.

Yes I know in most cases a rewrite do fix the warnings but I emphasize on the fact that on a migration scenario to nullable references, you want to limit rewriting code as much as possible.

> the NRT flow analysis doesn't track through method invocations

I didn't expect it to examine all code paths but for such simple cases I naively thought it would work. I often ask programmers to create methods to make the code more readable. I feel sad if it breaks the nullable reference analysis as it might prevent them from doing so.

Please note that it doesn't work even when using a local function:
```csharp
    public class LazyInitWithMethodAndLocalFunction
    {
        List<string>? _items;

        public List<string> Items()
        {
            InitList();

            // I would expect no warning but I get a CS8603: Possible null reference return
            return _items;

            void InitList()
            {
                _items ??= new List<string>();
            }
        }
    }
```

But it works if the code is unrolled:
```csharp
    public class LazyInit
    {
        List<string>? _items;

        public List<string> Items()
        {
            _items ??= new List<string>();

            // I would expect no warning but I get a CS8603: Possible null reference return
            return _items;
        }
    }
```

**Comment by RikkiGibson** [comment]
@cston @gafter is the `is`/`as` behavior observed here by design?
```cs
if (value is FileInfo)
{
    var fileInfo = value as FileInfo;
    // I would expect no warning but I get a CS8602: Dereference of a possibly null reference
    return fileInfo.CreationTime;
}
```

**Comment by CyrusNajmabadi** [comment]
I would expect this.  'as' is specifically the construct that says "i may have null after this, you should check for that".

The expected construct to make a typecast when you're sure it isn't null is either `(FileInfo)value`.

**Comment by RikkiGibson** [comment]
I agree that that's how `as` should be used. But I don't know if that means that nullable analysis should always see the return value of an `as` as nullable. It seems subjective whether that is really the most useful thing for users, especially when converting existing codebases that use patterns which are not "optimal" but we can nevertheless determine to be null-safe.

It seems like the warning is given when the `as` needs to actually perform a cast, but not when the left-hand side is a `FileInfo?`. https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8DEA7AVwwwmAzgAI49TyBYAKAAEAGCpgRgDoBJAeQDcjJgGZ2AJgoBhCgG9GFRezFMALBQCyACgD2wAFZwAxjAp79ASgVL5DJfYpoAZhV0HHUCgDFMcHnicdKzsHRVtQ0IA3CARHAJ0KAF4zd2hvX39AoRCIpQB9JLjArgA5CDA4bNyAX2tFWpyKOuV2dW0fckydAH4inT4ABxhg+3CI51c0eMHTNE8Ov3iRiLHcxWjYqcDCrf6hijSFrqq1xQLk3dLyyub7Brvm5tFWzXEtI/je3ZnlsNulCZab77OYpQwmX4OVZrDZ9HbTfaHDLxE6nc59K4VVEOe5KBrVIA=

**Comment by gafter** [comment]
We don't track the effect of general boolean conditions.  In this case the best thing to do is change this

``` c#
            if (value is FileInfo)
            {
                var fileInfo = value as FileInfo;
                return fileInfo.CreationTime;
            }
```

to this

``` c#
            if (value is FileInfo fileInfo)
            {
                return fileInfo.CreationTime;
            }
```

The lambda case is fixed for update 3.

I don't know why you expect a warning for the last case.  You declared the list to contain non-null values.

**Comment by jairbubbles** [comment]
> The lambda case is fixed for update 3.

That's great!

> I don't know why you expect a warning for the last case. You declared the list to contain non-null values.

Well if there is no matching element in the list if will return the default value. Isn't the default value of a non-nullable reference still null? I agree that from a signature point of view `FileInfo FirstOrDefault<FileInfo>(...)` it's not supposed to return `null`.

Should we use [DefaultIfEmpty](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.defaultifempty?view=netframework-4.7.2)?

**Comment by gafter** [comment]
We're still working on `FirstOrDefault`.  We expect it will be addressed by a `[MaybeNull]` attribute on that method that the compiler is aware of.

**Comment by gafter** [comment]
For case 1, we do not track values between the bodies of distinct methods.  We are aware of the use case and are looking at our options to address it.

I think that answers all of your issues.

In the future, can you please file separate issues (there are four issues reported here)?  Then we can either dup them against existing issues or keep it open to track the reported behavior.  Having said that, if this would discourage you from reporting, we'd rather have them grouped together like this than not reported at all!

Thanks for letting us know of your experience.

**Comment by jairbubbles** [comment]
I'll do that sure. Thx
