### ISSUE TITLE
Reduce allocations related to SyntaxTokenList in MetadataAsSourceService

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#34960]
There are a lot of usages of `new List<SyntaxToken>()` instead of `ArrayBuilder<SyntaxToken>.GetInstance()`. It would be nice to fix this up in the C# and VB MetadataAsSource implementations.

It would also be good to introduce constructor which takes `ArrayBuilder<SyntaxToken>` instead of `IEnumerable<SyntaxToken>` and reduces copying as much as possible.

See https://github.com/dotnet/roslyn/pull/34778#discussion_r272446817 and https://github.com/dotnet/roslyn/pull/34778#discussion_r274684831

**Comment by YairHalberstadt** [comment]
Ill give this a go

**Comment by YairHalberstadt** [comment]
I see the relevant PR is still open, so I'll wait for it to be merged

**Comment by RikkiGibson** [comment]
Thanks for having a look--I'll add the tag back once I get the referenced changes merged in :)

**Comment by RikkiGibson** [comment]
I only just noticed that I didn't add the tag back :) @YairHalberstadt feel free to take this on if you are still interested.
