### ISSUE TITLE
Quick actions and refactorings... Remove region

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34961]
<p>Would be nice to have the option to remove a region with a refactoring. Right now you have to delete the  #region  and #endregion  lines manually to remove them since regions are mostly considered bad practice</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/522170/quick-actions-and-refactorings-remove-region.html
VSTS ticketId: 842445_
_These are the original issue comments:_

Jane Wu [MSFT] on 4/9/2019, 02:05 AM (3 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by ameltzerMSFT** [comment]
Yes, please! ReSharper has supported this for years and this is one thing I'm really missing when using Visual Studio's Quick Actions.

**Comment by CyrusNajmabadi** [comment]
@ameltzerMSFT Would be happy to take a PR here :)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
