### ISSUE TITLE
Undo "restores" garbled code

### ISSUE THREAD

**Issue by c-s-n** [dotnet/roslyn#34975]
**Version Used**: Visual Studio Professional 2017 v15.9.11 (reproducible also in v15.9.8, but not in v15.9.7)

**Background**
Deleting several lines from `.cs` or `.cshtml` files (likely happens for more types) and trying to restore them via undo feature.

**Steps to Reproduce**:
1. Open a larger solution
Suggestion: https://github.com/aspnet/AspNetWebStack.git branch v3.2.7, Runtime.sln
2. Open a file where Visual Studio more likely tends to slow down (Razor)
Suggestion: `src\Microsoft.Web.Helpers\Facebook.cshtml`
3. Go to the middle of the file and press and hold CTRL+X to cut lines or CTRL+L to delete them
Suggestion: 200+ lines
4. Restore via CTRL+Z by holding until nothing happens anymore
-> The file name won't have the asterisk anymore, but still be different from the previously version
5. Diff to the repository version
-> You should see a difference
6. If not yet reproduced, repeat the previous steps (it will get slower each time, thus more likely to happen)

**Expected Behavior**:
The file looks exactly like before.

**Actual Behavior**:
The lines are not restored correctly; often lines are missing.
If you modified the file before, rarely even text fragments are "restored" at positions where they never were before.

![image](https://user-images.githubusercontent.com/615657/56076782-2c0d5800-5dd5-11e9-8559-f7f07b6afa0f.png)

-> Any unsaved previous code is lost or garbage, or at worst it might even be noticed too late that parts are wrong.

**Additional Notes**:
This might be related to the small hangs one can notice during deletion.
The problems seems to be intensified with ReSharper turned on ("We've noticed that extension 'JetBrains ReSharper Ultimate 2018.3.4' is slowing typing performance."), but also happens without.

**Comment by jinujoseph** [comment]
@olegtk should this be moved over to editor team ?

**Comment by olegtk** [comment]
Yes, I think so.

**Comment by CyrusNajmabadi** [comment]
Closing out as an editor issue.
