### ISSUE TITLE
Status request unable to download

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/roslyn#3498]
Hello, what is the status of this? I've bumped into a couple of projects that have "early adopted", which is a little premature IMO, until it's been officially released, but that's a topic for them.

In the meantime, I may as well learn what I can about it myself. In light of that, where can I download? Too early for "VS2015" IMO, so there are extensions for VS2013?

Following the bread crumbs from [Prerelease Software Downloads](http://www.visualstudio.com/en-us/downloads/prerelease-software-downloads-vs.aspx), [.NET JIT Compiler Preview](http://aka.ms/RyuJITinfo) lands me here, that is fine. However, the [Download](http://aka.ms/RyuJIT) yields this:

```
Unfortunately, the program you are trying to join has been closed. We are sorry for this inconvenience.
If you believe that you have reached this page in error, please click on Help, then select Microsoft Connect General Help. Here you can access a form which will be sent to our support team and submit the reasons why you believe you have reached this page in error.
You can also go to the Product Directory to view other programs you may be interested in participating in.
```

Which is unfortunate. Where can the preview be found? Or is there an official release? I've heard through some blogs, SO and others, that possibly there are extensions available to install.

Thank you...

**Comment by davkean** [comment]
Sorry for the late reply. Download the .NET Compiler Platform SDK to get started: https://visualstudiogallery.msdn.microsoft.com/2ddb7240-5249-4c8c-969e-5d05823bcb89.
