### ISSUE TITLE
"Width/width": VB painful regression in case-sensitivity of intellisense

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3499]
I often am in a class (such as Winforms, or XAML) with a property `Me.Width` which I want to pass as argument to a function which takes a parameter of name `width`, e.g. `Dim x As New Rect(0,0,Width,Height)`.

In VS2013 this worked fine. I'd just write "width" as the argument (all lowercase) and rely on intellisense to pick the correct case:
![vs2013-case](https://cloud.githubusercontent.com/assets/3316258/8165016/ddea124e-1341-11e5-9ee2-7729baa171b7.png)

But in VS2015 it doesn't work. When I write "width" lowercase argument, intellisense thinks I'm trying to name the parameter.
![vs2015-case](https://cloud.githubusercontent.com/assets/3316258/8165036/01c7ce90-1342-11e5-8ef5-e81ec8c0a14d.png)

As soon as I hit "comma" or close-parent then it commits it as `width:=`, which is never what I want:
![vs2015b](https://cloud.githubusercontent.com/assets/3316258/8165084/53b28cf4-1342-11e5-9bdb-cc8d2de28f9e.png)

**Comment by Pilchie** [comment]
Fixed by PR #3088.

**Comment by dpoeschl** [comment]
Verified this scenario (despite being dupe'd) against yesterday's ```1.0 (stable)``` build.
