### ISSUE TITLE
Make VisualStudioMefHostServices public

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#34994]
This class is simple and currently needed by Live Share. Let's make it public.

**Comment by daytonellwanger** [comment]
Not currently needed since Live Share has IVTs. But also do not have any objections to making this public 😄 . Just no rush.

**Comment by tmat** [comment]
Rather than making `VisualStudioMefHostServices` public it would be imo better to add a public extension method  `HostServices GetHostServices(this ExportProvider provider)`.

**Comment by sharwell** [comment]
I don't think this is necessary. Microsoft.CodeAnalysis.Testing implements this functionality already without IVTs.

**Comment by tmat** [comment]
@sharwell I'm not sure what you mean by not necessary. Is the type `VisualStudioMefHostServices` not necessary? Should we delete it then? If it is necessary for us then why isn't it necessary for anyone else who creates workspace that needs all Roslyn MEF services? 

Somewhat related:
We insert System.Composition.Hosting and System.Composition.TypedParts into VS External APIs. We should remove them.

**Comment by sharwell** [comment]
> If it is necessary for us then why isn't it necessary for anyone else who creates workspace that needs all Roslyn MEF services?

They can use `MefV1HostServices` or `MefHostServices` with vs-mef, both of which are already public APIs. The former is much easier to use, but doesn't work in .NET Core scenarios and doesn't work at all in 3.0 due to the omission of the Workspaces.Desktop assembly. I haven't had any issue with `MefHostServices` aside from the one-time setup.

**Comment by sharwell** [comment]
If we were to add vs-mef as a dependency of the _workspaces_ layer (not completely unreasonable given its advantages over MEF 2), we could provide VisualStudioMefHostServices as a new public API in the workspaces layer at the same time. I'm not sure it makes sense to expose it in other cases though.

**Comment by CyrusNajmabadi** [comment]
> This class is simple and currently needed by Live Share. 

Is there still a live share request/requirement here?  if not, let's close this. out.
