### ISSUE TITLE
How to go to the same place from diff window to source window?

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#35005]
picture 1:
![diff](https://user-images.githubusercontent.com/2529999/56207867-66e7e800-6082-11e9-885c-591c0647bc78.png)

picture 2:
![source](https://user-images.githubusercontent.com/2529999/56207874-6b140580-6082-11e9-85ed-b45083f02111.png)

For example, when I open picture 1, I find there're some changes near line 54, and I want to edit it more, but I don't want to edit it in diff window, so how can I go to the source window with the same place quickly, like picture 2.

**Comment by CreateAndInject** [comment]
@sharwell : @jinujoseph assigned this to you, are you working it?

**Comment by sharwell** [comment]
@olegtk do you know if there is a command for this already?

**Comment by CyrusNajmabadi** [comment]
Question for editor/platform.  Closing as external.
