### ISSUE TITLE
Is this is bad type name lookup bug?

### ISSUE THREAD

**Issue by ltcmelo** [dotnet/roslyn#35007]
The snippet below is perfectly fine - the reason for `System.String` is because this code comes from a rewriter that uses fully qualified names.

```
using System;

namespace Whatever.Something
{
public class FooBar
{
    public FooBar()
    {
        System.String obj = null;
    }
}
}
```

Now, I add a (empty) namespace whose name is suffixed by `System`, and the snippet no longer compiles, with the diagnostic: **error CS0234: The type or namespace name 'String' does not exist in the namespace 'Whatever.System'**.

```
using System;

namespace Whatever.System {}

namespace Whatever.Something
{
public class FooBar
{
    public FooBar()
    {
        System.String obj = null;
    }
}
}
```

I couldn't verify whether the (old online) C# specification anyhow prohibits such naming convention or this type name lookup works as intended. In either case, this is a awkward behavior (Roslyn 2.10).

Can anyone clarify this?

**Comment by KexyBiscuit** [comment]
This is by design, you may need to add `global::` before the type. See also: [How to: Use the Global Namespace Alias (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/namespaces/how-to-use-the-global-namespace-alias)

**Comment by ltcmelo** [comment]
Thanks for the reply @KexyBiscuit , but shouldn't the behaviour that you point out only happen when there's a type/namespace with the name `System` (as in the example of that page)? In the case I mention, I don't see at all reason for matching the `Whatever.System` namespace.

**Comment by KexyBiscuit** [comment]
@ltcmelo Since `FooBar` is also under `Whatever.Something` namespace.

**Comment by ltcmelo** [comment]
Hum... I see. Thanks for the clarification, @KexyBiscuit .
