### ISSUE TITLE
2019 VS C# and VB expression evaluator is needed in future VS versions

### ISSUE THREAD

**Issue by aarrtturas** [dotnet/roslyn#35003]
**2019 VS**: 

**Steps to Reproduce**:

1. NET Framework 3.5 in big project. In debug mode need "USE the legacy C# and VB expression evaluators"

**Expected Behavior**:
If you will remove (Its advertised that in the future versions of VS you will remove this option from debug options) it will not be possible to debug NET Framework 3.5 project. "Internal error"
**Actual Behavior**:
If this option is enabled debugging works as expected. Without it can't debug legacy project.
More information on:
https://stackoverflow.com/questions/34545354/internal-error-in-the-expression-evaluator

**Comment by jmarolf** [comment]
@aarrtturas its unclear to me what the problem is.  Can you fill out the **Expected Behavior:**/**Actual Behavior:** sections?

**Comment by tmat** [comment]
@aarrtturas Could you share your project? If not please collect a memory dump using 
![image](https://user-images.githubusercontent.com/41759/56233913-f9639980-6038-11e9-842b-e0e0045cb088.png)
