### ISSUE TITLE
Intellisense broken inside of methods that have delegates as arguments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35027]
Intellisense broken for callbacks. Inside of the Foo callback below builder. shows intellisense for the Delegate type instead of the Builder type. This works fine in 16 but broken in 16.1 preview 2.

```csharp
using System;
namespace ConsoleApp40
{
    class Program
    {
        static void Main(string[] args)
        {
            Foo(builder =&gt;
            {
                builder.
            });
        }
        static void Foo(Action&lt;Builder&gt; configure)
        {
            var builder = new Builder();
            configure(builder);
        }
    }
    class Builder
    {
        public int Something { get; set; }
    }
}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/533644/intellisense-broken-inside-of-methods-that-have-de.html
VSTS ticketId: 847803_
_These are the original issue comments:_

Visual Studio Feedback System on 4/15/2019, 08:17 PM (20 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 4/16/2019, 00:07 PM (5 hours ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by ivanbasov** [comment]
Likely caused by https://github.com/dotnet/roslyn/pull/34346

**Comment by davidfowl** [comment]
😄  Next time I'll file it directly on github
