### ISSUE TITLE
Enable nullable analysis on speculative semantic models

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#35037]
We need to determine the extent of nullable analysis support for speculative semantic models. In particular, we need to determine just how precise the speculative model needs to be for nullability. For example:

```C#
class C
{
    object? F;
    static void M(C c)
    {
        var x = new C() { F = c.F?.ToString() };
    }
}
static class ObjectExtensions
{
    object? MyExtension(this object o1, object o2) => null;
}
```

If someone were to speculate about replacing the `ToString()` call with `MyExtension(c.F)`, would we need to be precise enough here to not warn about the `c.F` in the invocation of `MyExtension`, since the conditional access guarantees that that `F` won't be null? @jasonmalinowski, thoughts?

**Comment by jasonmalinowski** [comment]
I admit I don't understand our uses of speculative semantic models well. @heejaechang or @mavasani?

**Comment by 333fred** [comment]
Also, to be clear, I don't think intra-expression speculation is achievable with the analysis structure, so we'll have to have an extremely compelling scenario to attempt to do the work here.

**Comment by 333fred** [comment]
@heejaechang or @mavasani, ping for comments?

**Comment by mavasani** [comment]
AFAIK our IDE usages of speculative models don't try to identify diagnostics in speculated code, just the semantics of nodes being speculated. Given that speculative semantic model essentially just inserts a new binder in the binder chain at the point of speculation, I am presuming those will continue working fine in code with nullable types.

By the way, I think that all the speculative semantic models are subtypes of MemberSemanticModel, which do no support any GetXXXDiagnostics invocations and always throw on them (you should confirm by looking at code).

**Comment by 333fred** [comment]
@mavasani the question isn't about diagnostics. The question is about what the public API will return for nullability information. The question is, if you were to call `GetTypeInfo` on the inner call to `c.F`, would we need to be able to return precise information about the nullability of the property? For reference, the full code with speculative replacement would be this:
```C#
var x = new C() { F = c.F?.MyExtension(c.F /* Call GetTypeInfo on this property access */) };
```

**Comment by jasonmalinowski** [comment]
@333fred I think it has to; the speculative semantic model is always created by replacing a top-level statement, right? So even if we want to speculate deep down, we still have to replace higher up.

**Comment by jasonmalinowski** [comment]
Actually a bit of a deeper thought thinking about what @ryzngard was running into yesterday....

Is your concern that the nullable analysis has to run in general, or that figuring out how to wire up the result of GetTypeInfo is tricky becaues it means lining things back up? Because consider if you had MyExtension being a generic extension a la `T MyExtension(this T arg1, ...)`, and then had something like:

    var x = new C() { F = c.F?.MyExtension<string>(c.F /* Call GetTypeInfo on this property access */) };

I assume you'd need to know if c.F was nullable or not to then know how the extension method call is being inferred. We would be doing a speculative GetSymbolInfo on the MyExtension invocation, which at least means you had to determine it under the covers.

The tricky part here with asking "do I need to do this?" is we aren't the only ones you have to ask. Any analyzer can be doing this speculation too, so this potentially impacts the entire ecosystem. The burden of proof of "I don't have to do this" is very hard to determine.

**Comment by 333fred** [comment]
> the speculative semantic model is always created by replacing a top-level statement, right?

So, I had been assuming this wasn't the case, as the internal API just takes a SyntaxNode and a position. But the public versions are more restrictive in the types of things that you can pass in, which makes my question significantly easier and much more straightforward to answer. The issue we were going to run into is needing to stop nullable analysis in the middle of an expression, but it sounds like we don't actually need to do that.

**Comment by mavasani** [comment]
> The issue we were going to run into is needing to stop nullable analysis in the middle of an expression

Ah yes, SemanticModel.TryGetSpeculativeModel only allows you to pass in top level executable block syntax nodes, so we should be fine!

**Comment by jasonmalinowski** [comment]
> The issue we were going to run into is needing to stop nullable analysis in the middle of an expression, but it sounds like we don't actually need to do that.

OK, my worry was one way I could have read your concern is that we might do a higher level replacement but then ask about some node deep inside of it, but I guess that wasn't your concern. Great!

**Comment by 333fred** [comment]
Implementation design from @AlekseyTs:
Store snapshots at absolute positions in an AVL tree or other sorted dictionary, and use given position to find a snapshot that is either at that exact position or the closest position after the provided position. Bind the provided expression, restore the walker from the given snapshot, and run analysis.

**Comment by AlekseyTs** [comment]
> find a snapshot that is either at that exact position or the closest position after the provided position

After thinking about this more, we might want to look for a snapshot at or before the given position instead. Might be more intuitive and also more natural to deal with speculations at the beginning of a method body.

**Comment by 333fred** [comment]
https://github.com/dotnet/roslyn/pull/36563 wires this snapshot mechanism through for the `SpeculativeSemanticModel`, but after that we still have the `GetSpeculativeTypeInfo`, `GetSpeculativeSymbolInfo`, and `GetSpeculativeConversion` APIs to enable.
