### ISSUE TITLE
Async Completion List does not resize back after it gets too wide

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/roslyn#35045]
**Version Used**: 
Visual Studio 2019 dev16.0 and above

**Steps to Reproduce**:

1. Create a C# project, or open a C# interactive window
2. Type `int`, and try to scroll down the completion list, you will see the width of the list is growing based on the candidate names
3. Type something very short, like `as`, `int` and you will see the completion window never resize back to fit the current candidates' names, make it look odd.

**Expected Behavior**:
1. Completion list will resize based on the candidate names, the legacy completion list preserves this behavior (resizes when completion list is triggered, if the window is already showed, then no resize.)
2. The list should have a min width, if you just `Alt + Right` in interactive window and filter by keywords, you may get a very narrow window that display incomplete iten names.

**Actual Behavior**:
It never resizes back to fit the length, see the screenshot.
![image](https://user-images.githubusercontent.com/12908526/56259957-e2996300-6089-11e9-8bc4-2abcb5982124.png)

**Comment by vatsalyaagrawal** [comment]
@ivanbasov is this a regression?

**Comment by AmadeusW** [comment]
Yes, this is a bug in the Editor where we don't correctly recycle the control.

**Comment by ivanbasov** [comment]
Thank you, @AmadeusW ! Moved to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/850412

**Comment by AmadeusW** [comment]
this will be fixed in VS2019 16.1 preview 3

**Comment by mazhou-msft** [comment]
Sounds good, thanks for the fast tracking :)
