### ISSUE TITLE
Investigate avoiding work if not rewriting for nullable

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#35041]
`NullableWalker` currently has several places where we're doing work to calculate nullabilities when it's only necessary for public API information. We should try to make these conditional on whether or not that info is necessary to avoid work if possible.

**Comment by 333fred** [comment]
Especially anywhere we're manually calling `VisitTypeExpression`, that should be avoidable when API info isn't needed.

**Comment by gafter** [comment]
In normal compilation with an analyzer, we currently run the nullable walker twice per method body, once for diagnostics and once for the semantic model.  We should run it at most once.

**Comment by 333fred** [comment]
https://github.com/dotnet/roslyn/pull/36563#discussion_r295516436
