### ISSUE TITLE
Enabling nullable context causes operator resolve errors 

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#35057]
**Version Used**: 

```
Branch master (17 Apr 2019)
Latest commit 88d7d9 by Andrew Hall:
Merge pull request #34915 Add IVsRefactorNotify changes to MoveToNamespace refactorings

If available, use the host service to provide IVsRefactorNotify changes of the symbols being changed so dependent frameworks

can handle the changes appropriately.

Adds unit tests that verify we have the correct code operations produced when we expect symbols to change.
```

**Steps to Reproduce**:

```cs
#nullable enable
class C<T>
{
  public static extern C<T> operator &(C<T> c1, C<T> c2);
}

class Test
{
  // uncomment the following line to remove the error
  //#nullable disable
  void M(C<string> c1, string s)
  {
    var c2 = GetC(s);
    var c3 = c1 & c2; // CS0034
  }
    
  public static extern C<T> GetC<T>(T t);
}
```

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWACgABAJgoGEAeAFQD5GA3owoUmAZlEBGAGxUAHvAS4OPXhQD2AB0QQY6hBQBkACi58KAY0lIV5iywCUAbkYBfRo1YVucWIOEUAPSBFPi4FupgYNQwFDAAFpQAZurE6gDuAJa4AOYUhNmUehQIcGDqAG5FiVQICPoBwXhEJGSUKJlQtHABTAAsFACyppxMkgAMalY2Y+MUUA4BQgwiIhUQBvYUALwUAOJwMOzGCy4rq+ubErtWRpYsTkEh7ADK4+NifQHu5yK9EmNZHAFIhlGY1AcjqpjNw4s43EA=

**Expected Behavior**:
No errors. The code compiles if you either remove the `#nullable enable` directive or uncomment the `#nullable disasble` directive

**Actual Behavior**:
```
error CS0034: Operator '&' is ambiguous on operands of type 'C<string>' and 'C<string>'
```
I'm not sure what exactly becomes ambiguous if nullable reference types are enabled. Both participating operands as well as their type arguments are explicitly non-nullable.

**Comment by cston** [comment]
@TessenR, thanks for reporting this issue!
