### ISSUE TITLE
error CS0718 in 3.0 SDKs

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#35062]
Create a consoleapp with the following files and `dotnet build` it, no errors. Open `global.json` and uncomment the line that requests the 3.0 sdk and comment the 2.2 sdk. You'll start getting the error: 
```
Program.cs(2,14): error CS0718: 'StaticClass': static types cannot be used as type arguments
```

I wasn't able to fix this by setting a 7.x langversion, so maybe this is a regression?

project.csproj
```c#
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

</Project>
```

Logger.cs
```c#
namespace Pocket
{
    internal class Logger<TCategory>
    {
    }
}
```

Program.cs
```c#
using System;
using static Pocket.Logger<ConsoleApp1.StaticClass>;

namespace ConsoleApp1
{
    static class StaticClass
    {

    }

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

global.json
```
{
  "sdk": {
    // Errors if you uncomment the line below (could be any 3.0 sdk, is just what I happen to have)
    // "version": "3.0.100-preview3-010431" 
    "version": "2.2.102"
  }
}
```

**Comment by rchande** [comment]
cc @333fred

**Comment by jcouv** [comment]
This change came from PR https://github.com/dotnet/roslyn/pull/30737, which validates constraints in usings. Tagging @RikkiGibson 

I think this change is correct. We disallow calling `Logger<StaticClass>.Log(string)` via explicit syntax, and therefore should also disallow calling that `Log(string)` method via static using.

If we don't produce an error for a static type argument, then you could end up with code where a static type gets instantiated ([example](https://sharplab.io/#v2:C4LgTgrgdgPgAgBgARwIwG4CwAoRLUBsSAMgPYDm5ApmADwDKwAhsAJYDGAwgDZMDOfAHxZsONETgAmJIxYce/PjgDeOAL44x0tAHYVOJIfwSALEgCyTVlAAUASgNHV2I65IUbAIk92RrjdgBONbANFBM3CjSZJQ0tAAqnCxU5KRgAJ6C+i5GcADMxihmMTaMYNbkSHx2SMpIjm5IicmpGUgAHkgAvEgAJlQAZkwQ3MB+jfgAdJykUHyk3FSTAOrloTadXT1QI9y+DUgBAUA)).
