### ISSUE TITLE
Completion should provide all in-scope type symbos

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#35060]
```cs
namespace Foo
{
    class Baz {}

}
namespace Foo.Bar
{
    class Baz {}

    class Goo
    {
        $$
    }
}
```

For example, at the cursor location,`Baz` from both `Foo` and `Foo.Bar` should be provided, where `Foo.Bar` should have its containing namespace as inline description. When `Foo.Bar` is committed, it will be completed in qualified form.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
