### ISSUE TITLE
Migrate unit testing features to External Access pattern

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#35078]
We are planning to remove IVT access to dotnet/roslyn from the following assemblies for 16.2 Preview 1:

* Microsoft.CodeAnalysis.LiveUnitTesting.BuildManager
* Microsoft.CodeAnalysis.LiveUnitTesting.BuildManager.UnitTests
* Microsoft.CodeAnalysis.LiveUnitTesting.Orchestrator
* Microsoft.CodeAnalysis.LiveUnitTesting.Orchestrator.UnitTests
* Microsoft.CodeAnalysis.LiveUnitTesting.Test.Utilities
* Microsoft.CodeAnalysis.UnitTesting.SourceBasedTestDiscovery
* Microsoft.CodeAnalysis.UnitTesting.SourceBasedTestDiscovery.UnitTests
* Microsoft.VisualStudio.LiveUnitTesting.IntegrationTests

These assemblies should be updated to operate correctly without IVT access to roslyn, or use an External Access assembly for all access to Roslyn internals. I will be assisting in the creation of the External Access layer if necessary for these components.

**Comment by CyrusNajmabadi** [comment]
This issue is too broad to be useful.  Either this should be scheduled and the work be done.  or we should just merge this into an a single bug with individual pieces for all these different areas.  There's no value in having N issues filling up the repo here.
