### ISSUE TITLE
Verify safe removal of EnC.UnitTests IVTs

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#35071]
The repository currently contains IVTs to the following assemblies:

* Roslyn.Compilers.CSharp.EnC.UnitTests
* Roslyn.Compilers.VisualBasic.EnC.UnitTests

I cannot find a record of these ever existing. The IVTs should be removed if they are no longer in use.

**Comment by tmat** [comment]
I think these can be removed.
