### ISSUE TITLE
Migrate legacy code analysis assemblies to the External Access pattern

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#35080]
We are planning to remove IVT access to dotnet/roslyn from the following assemblies for 16.2 Preview 1:

* CodeAnalysis
* ManagedSourceCodeAnalysis
* StanCore

These assemblies should be updated to operate correctly without IVT access to roslyn, or use an External Access assembly for all access to Roslyn internals. I will be assisting in the creation of the External Access layer if necessary for these components.

**Comment by sharwell** [comment]
ManagedSourceCodeAnalysis needs IVisualStudioDiagnosticAnalyzerService

**Comment by sharwell** [comment]
StanCore needs:

* IVisualStudioDiagnosticListSuppressionStateService
* IVisualStudioSuppressionFixService

CodeAnalysis does not appear to have any requirements.

**Comment by mavasani** [comment]
RestrictedIVT by itself will not suffice - we would need to give both IVT access and RestrictedIVT access. Former is needed to ensure successful build and latter to ensure the analyzer correctly flags the use of internal APIs outside RestrictedIVT namespaces.

**Comment by sharwell** [comment]
@mavasani All restricted IVTs automatically get an `InternalsVisibleTo` entry:

https://github.com/sharwell/roslyn/blob/27288268dff14f19f337cf23242a08b45d59eb34/eng/targets/Imports.targets#L238-L240

**Comment by CyrusNajmabadi** [comment]
This issue is too broad to be useful.  Either this should be scheduled and the work be done.  or we should just merge this into an a single bug with individual pieces for all these different areas.  There's no value in having N issues filling up the repo here.
