### ISSUE TITLE
Migrate ALM IVTs to the External Access pattern

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#35101]
Applies to **Microsoft.VisualStudio.Alm.Shared.CodeAnalysisClient**.

**Comment by jasonmalinowski** [comment]
This can be merged with the CodeSense one -- the assembly name doesn't make it obvious but this is a part of CodeSense.

**Comment by sharwell** [comment]
Thanks, I will combine them in a follow-up PR.

**Comment by sharwell** [comment]
Duplicate of #35086
