### ISSUE TITLE
Compiler is emitting `IsReadOnlyAttribute` for getter only auto properties when not targeting 8.0

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#35113]
The compiler is currently emitting `IsReadOnlyAttribute` on getter only auto properties even when the langversion is not 8.0.

This lead to failures in the GenAPI tool which generates a reference source file based on a given implementation assembly: https://github.com/dotnet/arcade/issues/2555

This should be reviewed and determined whether it is desirable (in which case tools should be updated) or if it is undesirable (in which case the compiler should be updated).

**Comment by tannergooding** [comment]
CC. @RikkiGibson, @jaredpar

**Comment by tannergooding** [comment]
As a note, I'm going to be updating GenAPI, in either case, to workaround this. I can understand the desire to have this emitted since it should be harmless outside the decompilation/recompilation scenario (which probably isn't officially supported anyways) and it allows more code to elide hidden copies where possible.

**Comment by jaredpar** [comment]
> I can understand the desire to have this emitted since it should be harmless outside the decompilation/recompilation scenario

No idea what scenario you're referring to here. 

I agree we probably shouldn't emit this unless you're on C# 8.0 though. Well at least 7.2. There is nothing wrong with us emitting new attributes to existing code patterns as long as it doesn't affect the success of compilations.

The problem I'm actually worried about is PEVerify. The compiler will emit PEVerify compatible code, to the best of its ability, as long as you're referencing C# 7.0 and before. This feature though will allow us to break PEVerify. Consider:

``` csharp
using System;
struct S { 
  static readonly S Field = new S();

  internal int Value { get; set; }

  internal void Example() {
    Console.WriteLine(Field.Value);
  }
} 
```

This will break PEVerify as we don't emit a copy for the `Field.Value` call. That's 100% okay in C# 7.2 and above as we don't guarantee that we emit PEVerify compatible code for 7.2 and above. It's a break for 7.0 though.

**Comment by tannergooding** [comment]
> No idea what scenario you're referring to here.

Scenarios like GenAPI which generate code files based on existing IL assemblies and then recompile those files.

This "bug" was found in ASP.NET since they compile their implementations targeting C# 7 something and then run GenAPI to build their reference sources for compiling the reference assemblies.

I dont think this is a scenario the compiler generally cares about though.

**Comment by jaredpar** [comment]
> I dont think this is a scenario the compiler generally cares about though.

Correct 😄
