### ISSUE TITLE
Can't view overloads by down arrow in watch window.

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#35115]
**Version Used**: VS2017&VS2019

**Steps to Reproduce**:

1. Type `int.Parse(` in watch window
2. Press down arrow

**Expected Behavior**: View different overloads

**Actual Behavior**: Cursor runs to next line.

**Comment by ivanbasov** [comment]
It seems to be an issue in Debugger or Editor not in Roslyn. I have created a VSO bug to track it: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/917435
