### ISSUE TITLE
Compiler is emitting `IsReadOnlyAttribute` for getter only auto properties of readonly structs.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#35114]
The compiler is currently emitting `IsReadOnlyAttribute` on getter only auto properties of a readonly struct.

While this is harmless, it unnecessarily increases metadata size and could likely be stripped given that it isn't emitted for other members (such as methods) and the readonly-ness can be detected from the attribute on the struct.

Also see: https://sharplab.io/#v2:C4LglgNgPgAgDAAhgRgNwFgBQMDMCBOApgIYAmA9gHYQCeCAzsPgK4DGwCAwggN5YICkeGABYEAWQAUASl79BAX3kDlQhGEocAGrwQBzQsFQIlmBUA==

**Comment by tannergooding** [comment]
CC. @RikkiGibson, @jaredpar

**Comment by jaredpar** [comment]
Agree we should not be doing this as it’s redundant.

**Comment by RikkiGibson** [comment]
Just checking my understanding:

- We *do* want to emit the metadata where the `readonly` keyword was specified on the member in source.
- We specifically want to *elide* the `IsReadOnlyAttribute` for a struct instance auto-getter when it's contained within a readonly struct and no `readonly` keyword is present on the member.

**Comment by tannergooding** [comment]
> We do want to emit the metadata where the readonly keyword was specified on the member in source.

I don't see the need to ever emit it directly for members of a readonly struct. The attribute on the struct itself already indicates that all instance members are themselves readonly, so including it in metadata on individual members of a readonly struct (even if manually specified in source) is effectively just bloat.

That is in comparison to readonly members of mutable structs, where the keyword actually conveys additional and useful information.

**Comment by RikkiGibson** [comment]
I think I'm basically on board with your argument, it just means that some symbols will not roundtrip `IsDeclaredReadOnly` as often, and MetadataAsSource and SymbolDisplay will not show redundant `readonly` in some scenarios where it was present in the original source.
