### ISSUE TITLE
properly deal with open file only option with compilation end diagnostic

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#3512]
see this for more info.

https://github.com/dotnet/roslyn/pull/1522

**Comment by heejaechang** [comment]
@mavasani I think you did something on this while you were moving analyzer driver to v2 I believe?

**Comment by mavasani** [comment]
@heejaechang Yes, I think https://github.com/dotnet/roslyn/commit/f67a6e6a28745bad537762458edff1b17fdd6b51 addresses your concern?

By the way, I have an open item tracking some more work for this flag: https://github.com/dotnet/roslyn/issues/4364

**Comment by heejaechang** [comment]
closed the issue. @mavasani already took care of it. other design issue pending though.
