### ISSUE TITLE
Constructor for VisualStudioWorkspaceDiagnosticAnalyzerProviderService should not have thread affinity

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#35137]
**Version Used**: 7d1eef24fc5139c359986120b2660eb9d474e3d8

MEF parts should not have thread affinity in their constructors. Currently the constructor for `VisualStudioWorkspaceDiagnosticAnalyzerProviderService` depends on the main thread.

🔗 This is related to #35138 and should probably be fixed at the same time

**Comment by CyrusNajmabadi** [comment]
This type doesn't exist.  Closing this out.
