### ISSUE TITLE
Find References results should distinguish direct and indirect references

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#35139]
See discussion in #34617.

Currently Find All References on a named type returns references to both the type itself and references to the constructor(s). In this and similar cases, the `FinderLocation` should indicate whether the location is a direct reference to the symbol passed to Find All References, or to a related symbol.

The Find All References presenter should be updated to not show references to a related symbol on the searched symbol whenever the related symbol will also be shown in the results. For example the following image shows a reference location that should not have been presented because it is a duplicate:

![image](https://user-images.githubusercontent.com/1408396/56428465-0c6aa980-6285-11e9-8ee0-ef35a4189040.png)

Related to #32738

**Comment by CyrusNajmabadi** [comment]
> should indicate whether the location is a direct reference to the symbol passed to Find All References, or to a related symbol.

I'm not sure i agree.  The API is much clearer (IMO) at least when it's a mapping from:

Symbol1 -> to direct reference locations to symbol1.
RelatedSymbol1 -> to direct reference locations of RelatedSymbol1
RelatedSymbol2 -> to direct reference locations of RelatedSymbol2
...

I don't think we should have:

Symbol -> to direct and related symbol locations

For 'related symbol locations' we should just put that location in the list of direct references to the *actual related symbol* that is returned in the result.  That makes things very clear IMO what the API is returning.
