### ISSUE TITLE
VisualStudioWorkspaceDiagnosticAnalyzerProviderService should fail gracefully

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#35138]
**Version Used**: 7d1eef24fc5139c359986120b2660eb9d474e3d8

Currently a failure in the constructor causes Visual Studio to crash. #34454 reduces but does not eliminate the chances of this occurring. This implementation should be updated to throw an exception from `GetHostDiagnosticAnalyzerPackages()` rather than crash the process in the constructor.

:link: Identified during review of #34454
:link: This is related to #35137 and should probably be fixed at the same time

**Comment by CyrusNajmabadi** [comment]
Neither VisualStudioWorkspaceDiagnosticAnalyzerProviderService  nor GetHostDiagnosticAnalyzerPackages seem to exist anymore.  Closing out.

**Comment by sharwell** [comment]
The type appears to be removed in a6289ebbc10f56bcc2d5904c6275a6952f6f7974

**Comment by sharwell** [comment]
This issue was fixed by #63912 (specifically by the addition of a factory `IVisualStudioDiagnosticAnalyzerProviderFactory`)
