### ISSUE TITLE
Compiler doesn't take readonly members into account for span safety rules

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#35146]
The language currently disallows you from passing a `Span<T>` to an instance method of a ref struct, unless that ref struct is also `readonly` or an `in` extension method.

The compiler should presumably also take into consideration whether a given member is itself `readonly` on a mutable instance struct and allow that as well.

For reference: https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAGAAhwEYBuAWACgcBmAhOCAEwHsA7DAT3rgDMDYCAK4BjGAQDKAHgAqAPgIBvKgVVE6OACwEAsgAoJABwhtZCgB4BKFWuWU1BAL5VnlKrR79Bo8RIBMZko2qh4MzOxcRNr6RiaBVsFB9mquru4axABsRH4EAMJUdg4eQmxQELxwRFlRBAByBlLAnPAKwNbJqkUOarGmAEItcBYEALwCMBAiANYQGBgsIgTN8ADaAKwAuhSdPcAAdPpWOw6uDoklZRVVJNla9QYBK8PLHQ7dPZLGA0Mj47BTWbzRbLIYbbaJBwAeihBAAouZDHAxHAmAQYCwCAB3FgIaZIARoNgiKr6SwENBQAgmNgsSbwNEYgi08RgIT0qowAAWVSJAOJcCQkLUMOpbEZPIYvFxVREJgA5OJYDKCOZhaoDkdLCcUi4gA

**Comment by tannergooding** [comment]
CC. @RikkiGibson, @jaredpar

**Comment by tannergooding** [comment]
Rikki suggested I also tag @VSadov, offline.

**Comment by RikkiGibson** [comment]
When I first heard this I thought it was related to https://github.com/dotnet/roslyn/issues/34487 but it looks like spilling is not involved. So the fix shouldn't be too complicated.
