### ISSUE TITLE
`#error version` should display product version

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#35140]
The compiler version in Core 3 preview 4 shows as '3.100.19.20907 (01f3eb10)' when I include `#error version` in the code of a simple console app.

But when I look at the Roslyn commit 01f3eb10
https://github.com/dotnet/roslyn/blob/01f3eb103049e2c93e0516c7d50908031deaca74/eng/Versions.props
I see that the version number should be 3.1.0 beta2 or something.

When I look at the binary "C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\Roslyn\bincore\Microsoft.CodeAnalysis.dll" I see both 3.100 and 3.1:
 ![file-version](https://user-images.githubusercontent.com/12466233/56433714-ada62f80-6286-11e9-99ae-1e8df20af9ca.png)

Expected:
`#error version` should display `3.1.0-beta2-...`

Proposal: 
`#error version` should pull the version number from `AssemblyInformationalVersionAttribute` instead:
`[assembly: AssemblyInformationalVersion("3.1.0-beta1-19162-08+b02e2c50a2f2aeabb5b4e5d850c65ad8686848e3")]`

**Comment by agocke** [comment]
I don't see how we could do this given: 1) don't people depend on the current behavior? and 2) informational version is rarely set.

**Comment by jcouv** [comment]
@agocke `#error version` is not documented/supported, so it can be changed. It is primarily useful for troubleshooting, so it should display the information that is most useful for that goal.

**Comment by jcouv** [comment]
Could you clarify what you mean by "informational version is rarely set"?

If that is the case, we can always implement a fallback strategy (prefer the product version, otherwise fall back to file version).

**Comment by agocke** [comment]
Ah, never mind, I'm dumb, the only purpose is to print *the compilers* version, not the code being built. This is fine then.
