### ISSUE TITLE
Turning off all rules and then enabling desired rules

### ISSUE THREAD

**Issue by JamesNK** [dotnet/roslyn#35164]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

Example: v2.9.2

#### Repro steps

1. Add package reference
1. Copy contents of `AllRulesDisabled.ruleset` to local file and reference from csproj
1. Compile

#### Expected behavior

No code analysis warnings because they're all disabled

#### Actual behavior

Code analysis warnings, e.g. warning CA2208: Call the ArgumentOutOfRangeException constructor that contains a message and/or paramName parameter.

**Comment by JamesNK** [comment]
You may have found a different bug. I get warnings even after reopening VS, and when building from the command line.

Repo: [Class1.zip](https://github.com/dotnet/roslyn/files/3100580/Class1.zip)

```
Microsoft (R) Build Engine version 16.1.65-preview+gc86abee47b for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 171.86 ms for C:\Users\James\source\repos\ClassLibrary7\ClassLibrary7\ClassLibrary7.csproj.
C:\Program Files\dotnet\sdk\3.0.100-preview5-011367\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\Users\James\source\repos\ClassLibrary7\ClassLibrary7\ClassLibrary7.csproj]
Class1.cs(9,19): warning CA2208: Call the ArgumentOutOfRangeException constructor that contains a message and/or paramName parameter. [C:\Users\James\source\repos\ClassLibrary7\ClassLibrary7\ClassLibrary7.csproj]
  ClassLibrary7 -> C:\Users\James\source\repos\ClassLibrary7\ClassLibrary7\bin\Debug\netstandard2.0\ClassLibrary7.dll

Build succeeded.

Class1.cs(9,19): warning CA2208: Call the ArgumentOutOfRangeException constructor that contains a message and/or paramName parameter. [C:\Users\James\source\repos\ClassLibrary7\ClassLibrary7\ClassLibrary7.csproj]
    1 Warning(s)
    0 Error(s)
```

![image](https://user-images.githubusercontent.com/303201/56462093-2507ca80-6411-11e9-8311-c0b2c7036468.png)

**Comment by jasonmalinowski** [comment]
@JamesNK @mavasani with both of your repos, what types of C# projects were you using? Were you using .csproj projects that list the individual files (i.e. "old style") or the newer kind i.e. "SDK style"? It looks like this will work fine in old style projects but it seems our handling of the newer style is missing some logic around rulesets.

**Comment by JamesNK** [comment]
SDK style

**Comment by mavasani** [comment]
Me too...

**Comment by jasonmalinowski** [comment]
Alright, thanks @JamesNK and @mavasani for the clean repros, got a fix out now for it.
