### ISSUE TITLE
Suggestion: Suppress AsyncStateMachineAttribute in metadata-as-source

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#35174]
Repros in 15.6, so not a regression.

```c#
#region Assembly ClassLibrary34, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// C:\Users\acasey\source\repos\ClassLibrary34\ClassLibrary34\bin\Debug\ClassLibrary34.dll
#endregion

using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

namespace ClassLibrary34
{
    public class Class1
    {
        public Class1();

        [AsyncStateMachine(typeof(<DoAsync>d__0))]
        [DebuggerStepThrough]
        public Task DoAsync();
    }
}
```

It is not very helpful to see `AsyncStateMachineAttribute` in the metadata-as-source view since it's an implementation detail and exposes mangled names that should not be depended upon.

**Comment by jcouv** [comment]
We should probably do the same for [`AsyncIteratorStateMachineAttribute`](https://github.com/dotnet/roslyn/commit/d3d10fba7f860dd7951566ea1b5122f4a003e080) and `IteratorStateMachineAttribute` as well.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of hits, as well as SourceLink superseding this.
