### ISSUE TITLE
Allow setting/updating DefaultNamespace for project at workspace

### ISSUE THREAD

**Issue by savpek** [dotnet/roslyn#35173]
I tried to make omnisharp-roslyn to support new SyncNamespace refactoring (https://github.com/dotnet/roslyn/pull/30920). However method https://github.com/dotnet/roslyn/blob/c421f1249d1c2ba94e7703037ec49b4341f3b9f4/src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs#L315 is internal. Is there other means to set default namespace for project at workspace?

Omnisharp-roslyn issue https://github.com/OmniSharp/omnisharp-roslyn/issues/1475

**Comment by genlu** [comment]
@jasonmalinowski Should we expose default namespace as a public API?
