### ISSUE TITLE
Committing import completions corrupts Razor cshtml files

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/roslyn#35172]
**Version Used**: 
dev16.1-preview2 (after PR for import completions by @genlu )

**Steps to Reproduce**:

1. Open cshtml file
2. Type @, invoke intellisense 
3. Select and commit any import completion item

**Expected Behavior**:
a) Razor import directive added to current document
or
b) Import completions are disabled for cshtml files

**Actual Behavior**:
Text is removed at random position. Document becomes corrupted.

![2019-04-22_12-47-44](https://user-images.githubusercontent.com/17177729/56494991-dcc5d680-64fc-11e9-86cf-a4b0064cd7d8.gif)

**Comment by genlu** [comment]
@heejaechang We probably need to disable this in Razor doc.

**Comment by genlu** [comment]
@rynowak I'm not familiar with Razor pages. Does it make sense in this scenario to complete with fully qualified type name instead of disable this feature?

**Comment by rynowak** [comment]
I think that would be better than the feature not working. I'd like to find a path to support features like this.

**Comment by genlu** [comment]
@rynowak OK, thanks for confirming.

@heejaechang Is there's anyway to tell if we are in a razor page at Feature layer? `ITextBufferSupportsFeatureService` is only available in EditorFeature.

**Comment by genlu** [comment]
@rynowak Also, is it possible to add usings to a Razor document?

**Comment by rynowak** [comment]
Not using the C# using syntax, it's `@using BlahBlah` in Razor. We don't currently have any API contract with Roslyn that allows this to work.

**Comment by genlu** [comment]
@rynowak This seems to be a similar issue caused by attempting to add an import in Razor file.

https://developercommunity.visualstudio.com/content/problem/514087/problem-in-namespace-refactor.html?childToView=546711#comment-546711
