### ISSUE TITLE
Offer codefixes on selections

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#35180]
## Scenario
Codefixes often don't show if code is selected as opposed to only having your cursor placed within a word.
*  **5 out of the 11 users struggled with this in user studies.** 
* One user **only** ever double-clicked when clicking around the editor. This means he saw fewer codefixes since double clicking always selects the word and we don't show available codefixes in the context. Some users are used to double-clicking around their codebase.

## Proposal
Enable the same codefixes to appear if a block is selected as would appear if the cursor was placed inside a specific name. If this improves discoverability of codefixes we can enable this on a case-by-case basis per refactoring. My study observed more issues with the 'pull members up to base type' refactoring than others though general struggling was observed with many refactorings.

**Example: Pull members up**
Codefix offered when cursor is in the name:
![image](https://user-images.githubusercontent.com/8293542/56520118-8bb3e380-64f8-11e9-94fa-b79c60ed7ddb.png)

Codefix not offered if full line is selected:
![image](https://user-images.githubusercontent.com/8293542/56520215-bf8f0900-64f8-11e9-9022-7a5ebd464553.png)

**Example: Convert local function to method**
Offered if cursor is in name
![image](https://user-images.githubusercontent.com/8293542/56520344-0d0b7600-64f9-11e9-8fb9-6ac6d7b8de69.png)

Not offered when entire local function is selected
![image](https://user-images.githubusercontent.com/8293542/56520368-1ac0fb80-64f9-11e9-92a4-49037caea806.png)

**Example: LINQ to Foreach conversions**
![image](https://user-images.githubusercontent.com/8293542/56521136-1517e580-64fa-11e9-828a-a23aa22d8ce2.png)

If semi-colon is included in selection the conversion does not appear:
![image](https://user-images.githubusercontent.com/8293542/56521033-00d3e880-64fa-11e9-849f-2cc7a675f3ff.png)

**Comment by petrroll** [comment]
Ok, so I've reworked the "Convert to method" refactoring. I think interesting points came up that should be taken into consideration for subsequent work on general discoverability of refactorings. 

I tried to distil all of our conclusions as for when to provide a refactoring: 
1) The whole in question was selected
2) Caret was somewhere on the *header* of the item or it was selected

##### Notes:
- Imprecise selection is forgiven.
  - Leading / trailing whitespace is stripped
  - Partial selection of Tokens is forgiven (goes for the smallest encompassing Node).
- Imprecise location is **not** forgiven.
  - Whitespace isn't stripped for zero-width selections. 

##### Header: 
- Defined per type basis, e.g. name for methods/functions, `for` token for loops, ..., see `IsOnTypeHeader`. 
- As of right now the helper assumes header is _any token_ whose direct parent is Node in question.

##### Current helper: 
- Assumes abovementioned about header.
- Requires refactorings to ask about a SyntaxNode . In essence answers whether given current pos/selection a work on a SyntaxNode type would make sense.
  - ? Do we need more general helpers for other refactorings? 

```
        /// A <typeparamref name="TSyntaxNode"/> instance is returned if:
        /// - Selection is zero-width and inside/touching a Token with direct parent of type <typeparamref name="TSyntaxNode"/>.
        /// - Selection is zero-width and touching a Token whose ancestor ends/starts precisely on current selection .
        /// - Token whose direct parent of type <typeparamref name="TSyntaxNode"/> is selected.
        /// - Whole node of a type <typeparamref name="TSyntaxNode"/> is selected.
```

##### Issues: 
For other refactorings the situation can be s.t. way higher node is selected (e.g. for the foreach one a variable declaration) and we still want to offer a refactoring for LinqExpr -> need for walking down the tree in some way.

**Comment by petrroll** [comment]
Note: Some other refactorings (e.g. AbstractMergeConsecutiveIfStatementsCodeRefactoringProvider) use `Span.IsAround` that takes into account some whitespace (i.e. if selection is around Span but not fullSpan).

1. FindNode -> IfNode
2. Check is current selection is `IsApplicableSpan` -> around some parts of the IfNode (if keywor, ...).

**Comment by petrroll** [comment]
Generally, looking at a few refactorings (`CSharpMergeConsecutiveIfStatementsCodeRefactoringProvider`, `CSharpConvertLinqQueryToForEachProvider`, `CSharpConvertLocalFunctionToMethod`, to a certain degree `AbstractPullMemberUpRefactoringProvider`) it seems that all of them have circa following flow: 

1. FindNode for current selection 
   - Sometimes also GetTouchingWord (AbstractPullUp...) & then FindNode for it.
2. Check if the node is of correct type 
   -  Sometimes also traverses a bit of the tree (goes into ArgumentSyntax (e.g. ConvertLinqTo...) but usually misses some obvious opportunities (e.g. for Declaration).
3. Checks if selection is valid for found Node/Node in question.
   - `IsAround` for current selection (via helper or via manual checking of `Span` and `FullSpan` (MergeConsIf...)
   - Manual checking of identifier's (header) `Span` & `FullSpan` and current selection / caret (PullMember)
4. Some semantic level checks, ...

Am I missing some common step / pattern?

**Comment by petrroll** [comment]
I feel like there're a few issues with abovementioned way it's done nowadays :
1. `FindNode` should first remove trailing/leading whitespace (or be called with stripped selection).  
   - Considering adding and overload with parameter / (?Not sure about changing defaults, could break lots of things).
   -  What are the situations in which we might want to preserve leading/trailing whitespace for `FindNode`?
2. Create some better / common mechanism for traversing the tree. Our current helper `TryGetSelectedNodeAsync` is limited to testing against only one NodeType, and doesn't traverse the tree (only on edges or Spans / direct Token's parent). Doesn't work e.g. for traversing down a ParameterSyntaxNode / FieldDeclaration (as required for ForEach's fix)
3. Manual level checking of Span/FullSpan should move to `IsAround` and should be done by (improved) helper in 2. instead of each individual Refactoring (some might forget -> inconsistent)

**Comment by petrroll** [comment]
Thoughts @CyrusNajmabadi @heejaechang @mavasani ?

Generally I'm trying to come up with set of helpers / guidelines to solve the first part of the discoverability issue -> having consistent experience for when refactorings should be offered. 

Since we want to solve their ordering in the second step I think we can go with enabeling them in more situations than now. Having more of them will get fixed when we figure out how to order them / filter only the relevant in case there's too many of them.

**Comment by mavasani** [comment]
@petrroll I believe you have made very good progress here. Your added helper API in https://github.com/dotnet/roslyn/pull/36592 should account for the refactorings that work on a specific node type. In general, I agree with you that existing helper you added in your current PR will not suffice for all refactorings, and we do need additional shared code/utilities to tackle them. I'd let you decide how to structure this shared code, though I think it might be worthwhile to have following sub-types or some such type hierarchy so it is easy to distinguish the bucket of refactorings and avoid mistakes in each refactoring that might introduce inconsistencies:

1. `internal abstract class SyntaxBasedCodeRefactoringProvider : CodeRefactoringProvider`: Sub-type for all our IDE syntax based code refactorings. They should probably override and seal [ComputeRefactoringsAsync](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeRefactorings/CodeRefactoringProvider.cs,16) and introduce new abstract methods which are node based, say
   1. `public abstract Task<SyntaxNode> TryGetSelectedNodeAsync(Document, TextSpan, CancellationToken);` and
   2. `public abstract Task ComputeRefactoringsAsync(SyntaxNode, Document, Action<CodeAction> registerRefactoring, CancellationToken);`
2. `SyntaxBasedCodeRefactoringProvider<TSyntaxNode> : SyntaxBasedCodeRefactoringProvider`: Sub-type for all single node based refactorings that implement `TryGetSelectedNodeAsync` using your existing helper
3. Another sub-type of `SyntaxBasedCodeRefactoringProvider` for refactorings that need additional massaging/logic to find applicable syntax node from span. This can have the common tree traversing, `IsAround` etc. logic to find the node that each refactoring should operate on. Eventually, some of the refactorings might need to have their own custom logic, and can override specific pieces as appropriate.

**Comment by petrroll** [comment]
Ok, I'll explore common subtype while fixing the ForEach refactoring. Just one thing, where should the type live? 

Also, I've just found `AbstractWrappingCodeRefactoringProvider` and corresponding `AbstractCSharpSeparatedSyntaxListWrapper`. And to be honest I don't immediately see what their purpose.

**Comment by mavasani** [comment]
It should likely go into Microsoft.CodeAnalysis.Features project. We have [AbstractBuiltInCodeStyleDiagnosticAnalyzer](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/CodeStyle/AbstractBuiltInCodeStyleDiagnosticAnalyzer.cs,8) and [AbstractCodeQualityDiagnosticAnalyzer](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/CodeQuality/AbstractCodeQualityDiagnosticAnalyzer.cs,8) for our common sub-types for IDE analyzers and [SyntaxEditorBasedCodeFixProvider](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeFixes/SyntaxEditorBasedCodeFixProvider.cs,11) for a common sub-type for IDE code fix providers.

**Comment by CyrusNajmabadi** [comment]
FWIW, i'm strongly against subtyping here :D    I think it would be far nicer as a set of reasonable helpers, since i think the concept of "map this position/span to something reasonably intuitive in a consistent fashion"  isn't specific to refactorings.

**Comment by CyrusNajmabadi** [comment]
> Thoughts @CyrusNajmabadi @heejaechang @mavasani ?

> Generally I'm trying to come up with set of helpers / guidelines to solve the first part of the discoverability issue -> having consistent experience for when refactorings should be offered.

My thoughts are that we should just keep tackling refactorings one at a time, placin helpers in a consistent location and augmenting them as we go along and learn more.  I think ti's really hard to try to think about this abstractly since it will often come down to the nitty gritty details of each refactoring how we want thins to behave.

I do think though that once we get through around a half-dozen we'll find that there are less and less changes to teh helpers we need to make and that they will be gelling well around behavior we find universally appropriate.

**Comment by petrroll** [comment]
I agree that the implementation shouldn't be in the subtypes but in helpers elsewhere so it could be used elsewhere. I also think that subtypes can be very useful for discoverability reasons (want to write just a quick refactoring -> here's base type that does most of what I need.

That said, you're right that we should probably wait with creating common functionality until more refactorings are tackled with common helpers because the devil to good abstraction is in details we might not see right now.

**Comment by CyrusNajmabadi** [comment]
Given the helpers you made so far, i think we should try to move as many existing *applicable* refactorings over to using it.  many could be banged out easily, and a few will help us discover what gaps remain in those helpers.

once we do that, we can move over to some refactorings that work very differently (i.e. the ones that ask you to select a bunch of a members) to help drive those helpers.  

--

Note: the above can be done in parallel.

**Comment by CyrusNajmabadi** [comment]
> I agree that the implementation shouldn't be in the subtypes but in helpers elsewhere so it could be used elsewhere. I also think that subtypes can be very useful for discoverability reasons (want to write just a quick refactoring -> here's base type that does most of what I need.

I would be ok with a hybrid approach.  The base type for easy subtyping, but the base type *only* calls into the helpers.    Note though, this is a very *low order bit* for me.  My high order bits are refining the helpers you added (by converting over other similar refactorings), as well as determining what other new helpers we need for some of the totally different refactoring cases.

Thanks!

**Comment by CyrusNajmabadi** [comment]
Out for hte next few hours.  Will check in later tonight :)

**Comment by petrroll** [comment]
I agree that @CyrusNajmabadi  plan is probably the safer way to proceed. I'll move the foreach refact. to helpers and we'll see then. 

Also, what about the `ISyntaxWrapper` and `AbstractWrappingCodeRefactoringProvider`, how are those relevant?

**Comment by petrroll** [comment]
Also, am I correct in assuming that as long as it is internal I'm free to change it (if it's reasonable) without breaking anyone on the outside? 

I know that F# has IVT (and that some projects e.g. peachpie maintain fork with IVT) but that should be rare and probably not for these things, right?

**Comment by mavasani** [comment]
> Also, am I correct in assuming that as long as it is internal I'm free to change it (if it's reasonable) without breaking anyone on the outside?

Yeah, you should be fine to refactor any of the refactorings. None of the partners have IVT dependencies on these...

**Comment by petrroll** [comment]
If I were to look for a helper that would extract relevant expressions from statements (e.g. the init expression from LocalDeclarationStatement / assignement) / wrapper expressions (argument) is there anywhere else other than `SyntaxFactsService` to look?

**Comment by petrroll** [comment]
Or rather, if I were to add a method that would extract expressions e.g. from `LocalDeclarationStatement` where should I put it?

**Comment by CyrusNajmabadi** [comment]
I would put them in RefactorinHelpers.  They're definitely *not* 'syntax facts.  (i can explain more if you need more info).

**Comment by petrroll** [comment]
Let's contineu this convo in the PR.

**Comment by petrroll** [comment]
Some other refactorings to handle: 
- ChangeSignatureCodeRefactoringProvider only works for no-selections
- ConvertToConstant  : the same as foreach
- Allmethod/LocalFunction refactorings

**Comment by petrroll** [comment]
Work connected to #35525 (helpers, ..., to provide consistent experience).

**Comment by mavasani** [comment]
@petrroll I believe this issue is now resolved?

**Comment by petrroll** [comment]
Mostly, there're still refactorings that haven't been moved over & thus ?might not support selections. All of the ones specifically listed here are resolved, however.

**Comment by petrroll** [comment]
Fixed.
