### ISSUE TITLE
CompletionListTagCompletionProvider shows results in comments

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#3518]
Split from #3506 (originally filed by @ljw1004):

** Reduced Repro**

```VB
Class C
    Sub Test()
        M(Type2.A)
        ' $$
    End Sub

    Private Sub M(a As Type1)
        Throw New NotImplementedException()
    End Sub
End Class

''' <completionlist cref="Type2"/>
Public Class Type1
End Class

Public Class Type2
    Public Shared A As Type1
    Public Shared B As Type1
End Class
```

Remove the $$ and invoke completion.

Expected: no completion
Actual: ```CompletionListTagCompletionProvider``` provides items despite being in a comment

**Comment by rchande** [comment]
@dpoeschl I'm keeping this open and assigning to you to track porting your earlier PR to master.
