### ISSUE TITLE
Navigate to Decompiled Sources should also generate PDB if it doesn't exist

### ISSUE THREAD

**Issue by vinaychandra** [dotnet/roslyn#35196]
The navigate to decompiled sources decompile most scenarios but are not much helpful while debugging. Enable autogeneration of PDB files (or provide an option similar to ReSharper) for decompiled source code so that breakpoints within decompiled sources work

**Comment by jinujoseph** [comment]
cc @tmat

**Comment by CyrusNajmabadi** [comment]
Closnig out due to lack of feedback.
