### ISSUE TITLE
Source decomipler shows the signature only

### ISSUE THREAD

**Issue by amirhosseinbk** [dotnet/roslyn#35192]
**Version Used**: 
2017
**Steps to Reproduce**:

Enable Navigation to decompiled sources in Visual studio for C# and then try to navigate to the source code of CloudQueue.AddMessageAsync this would only show the signature of the method rather than its implementation details 

**Expected Behavior**:
Resharper would navigate to a decompiled version of DLL and show the details of the function and it is possible to go further into the code.

**Actual Behavior**:
Just the signature of the functions are displayed with no useful code.

**Comment by siegfriedpammer** [comment]
This will be fixed by #41007.

**Comment by CyrusNajmabadi** [comment]
@amirhosseinbk is this still an issue for you?
