### ISSUE TITLE
[Regression] Errors that reported during build become stale if reported before "IntelliSense" category

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#35204]
I cannot repro this in 15.9, but cannot tell if that's because it doesn't repro or because its faster.

I'm running into this a lot in the large solution I'm working in.

**Version Used**: 
Version 16.1.0 [28728.66.d16.1stg]
Version 16.1.0 Preview 2.0 [28817.7.d16.1]

**Steps to Reproduce**:

1. Extract attached solution ([ClassLibrary1.zip](https://github.com/dotnet/roslyn/files/3106503/ClassLibrary1.zip))
2. Delete .vs folder (!important)
3. Open solution
4. In ClassLibrary1\Class1.cs remove the `IComparable` implementation from `Foo`
5. Immediately build via F6 so that the "Build" errors show up before the "IntelliSense" error (!important)

**Expected Behavior**:
Only a single error in IntelliSense & Build category

```
Error	CS1503	Argument 1: cannot convert from 'ClassLibrary1.Foo' to 'System.IComparable'	ConsoleApp407	C:\Users\davkean\Source\Repos\ConsoleApp407\ConsoleApp407\Program.cs	10	Active
```

If I switch to Build category:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 1: cannot convert from 'ClassLibrary1.Foo' to 'System.IComparable'	ConsoleApp407	C:\Users\davkean\Source\Repos\ConsoleApp407\ConsoleApp407\Program.cs	10	N/A
```

**Actual Behavior**:
Two errors in IntelliSense & Build category
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 1: cannot convert from 'ClassLibrary1.Foo' to 'System.IComparable'	ConsoleApp407	C:\Users\davkean\Source\Repos\ConsoleApp407\ConsoleApp407\Program.cs	10	
Error	CS1503	Argument 1: cannot convert from 'ClassLibrary1.Foo' to 'System.IComparable'	ConsoleApp407	C:\Users\davkean\Source\Repos\ConsoleApp407\ConsoleApp407\Program.cs	10	Active
```

If I switch to Build category (notice that the Suppression column is different to Expected):

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 1: cannot convert from 'ClassLibrary1.Foo' to 'System.IComparable'	ConsoleApp407	C:\Users\davkean\Source\Repos\ConsoleApp407\ConsoleApp407\Program.cs	10	
```

If you re-add the `IComparable` implementation (without building), only the second error goes away and the other sticks around and becomes stale until the next build.

If you _wait_ until IntelliSense appears _and then_ build, only a single error appears.

**Comment by davkean** [comment]
tag @heejaechang

**Comment by davkean** [comment]
This is what I'm experiencing in real solutions, everyone of these errors is "stale":

![image](https://user-images.githubusercontent.com/1103906/56565551-031a6d80-65f4-11e9-87e0-105ff222c993.png)

**Comment by heejaechang** [comment]
is it only happen right after solution opened? my guess is build error came in even before we have assigned document id to the file path. so roslyn think the error doesn't belong to current solution and that's probably why it didn't de-dup it with live error.

but, I need to take a look to be sure.

**Comment by davkean** [comment]
No I can repro if the solution is open for a long time.

**Comment by heejaechang** [comment]
alright, let me take a look.

**Comment by heejaechang** [comment]
looks like a dup of http://bung/#/DevDiv/search/table?q=CID%3DDevDiv.813153

**Comment by davkean** [comment]
Thanks for looking into this quickly @heejaechang!
