### ISSUE TITLE
Generate Constructor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35208]
<p>When I use Ctrl+dot, and use the Generate Constructor option, it always creates a <strong>public</strong> constructor. I think this should create a <strong>protected</strong> constructor when the class is abstract.</p><p>public abstract class Example</p><p>{</p><p>     // Ctrl + dot here and select Generate constructor</p><p>}</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/531718/generate-constructor.html
VSTS ticketId: 847234_
_These are the original issue comments:_

Jono on 4/13/2019, 00:01 PM (9 days ago): <p>Oops. I meant to say use ctrl+dot on the <strong>class name</strong> and select the Generate Constructor option.</p>

Jane Wu [MSFT] on 4/15/2019, 01:26 AM (8 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
Kendra Havens [MSFT] on 4/18/2019, 02:28 PM (4 days ago): <p>If the abstract class is not marked public the code fix will generate a protected constructor. <a target="_blank"> https://github.com/dotnet/roslyn/issues/20595 </a></p><p>Just to clarify, you would like the constructor to be protected even when the abstract class is public?</p>

Jono on 4/22/2019, 09:57 PM (12 hours ago): <p>I believe that the constructors for all abstract classes should be protected by default, even if the class itself is public. This is because you can never create an instance of an abstract class. </p><p>So to answer <a rel="user" href="https://developercommunity.visualstudio.com/users/44551/c431bd99-0155-451e-85eb-030dfb2f9783.html" nodeid="44551">@Kendra Havens [MSFT]</a>: Yes please :D</p><p><br></p>

**Comment by CyrusNajmabadi** [comment]
This was fixed here: https://github.com/dotnet/roslyn/pull/25866

**Comment by Nytrodyne** [comment]
I don't believe that #25866 addresses the same issue, because it will declare a public constructor if the abstract class is public. In my opinion, all constructors in an abstract class should be protected by default, making the contract clearer to type designers.
