### ISSUE TITLE
preprocessor colorization is off

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#35216]
repro.

open ContainedDocument.cs

![image](https://user-images.githubusercontent.com/1333179/56611162-00a11f00-65c6-11e9-814c-fc5a73ad03ea.png)

looks like preprocessor is not colorized correctly.

**Comment by CyrusNajmabadi** [comment]
Doesn't repro for me.  

![image](https://user-images.githubusercontent.com/4564579/76178326-34504d80-6174-11ea-8e81-f4a9f1bd286d.png)
