### ISSUE TITLE
Call to non-existant Add() overload in collection initializer shows lambda completions

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#3522]
_corner-case issue_

Source:

``` C#
new Dictionary<Func<int, int>, int> { x };
```

Typing the `x` will show unhighlighted completions as if it were the beginning of a lambda expression, even though it is illegal to pass a lambda (or in fact any expression) there.

When resolving partial brace-less collection initializer calls, you need to check that the method has _exactly_ one argument.

**Comment by dpoeschl** [comment]
Repros on current bits.

**Comment by CyrusNajmabadi** [comment]
Need more info on if this is an issue really impacting users.
