### ISSUE TITLE
IntelliSense doesn't recognize second lambda parameter in collection initializer

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#3523]
Source: 

```C#
new Dictionary<int, Func<int, int>> { { 1, x };
```

Typing `x` shows pre-selected completions, even though that should be the start of a lambda.

Passing a lambda as the first parameter works fine.

After typing `=>`, it is correctly recognized (and type-inferred) as a lambda.

**Comment by dpoeschl** [comment]
This works as expected on the latest bits for me. We made some recent changes to the TypeInferrer for collection initializers, and in this case x is now inferred as System.Func<int, int> and so we show the builder. Does this screenshot match your expectation?

![image](https://cloud.githubusercontent.com/assets/235241/8175868/76c528c8-13a6-11e5-86eb-798b9c277e36.png)

**Comment by SLaks** [comment]
Yes; that's correct.
