### ISSUE TITLE
Remove unnecessary parantheses is confused by nullable types

### ISSUE THREAD

**Issue by Eilon** [dotnet/roslyn#35239]
**Steps to Reproduce**:

1. Create a .NET Standard 2.0 class library (though other project types should have the same issue)
2. Add this code to the class:
```c#
        public void Foo()
        {
            DateTime? date = DateTime.Now;
            Console.WriteLine((date?.AddDays(1))?.DayOfWeek);
        }
```
3. VS offers to remove "unnecessary parentheses":
![image](https://user-images.githubusercontent.com/202643/56683114-c5642600-6681-11e9-9c74-da5ab3b8d396.png)
4. If you accept the suggestion, it generates invalid C# code:
![image](https://user-images.githubusercontent.com/202643/56683173-e0369a80-6681-11e9-9679-3819a06d4fc2.png)

**Expected Behavior**:
It shouldn't offer to remove the parentheses because they are in fact required.

**Actual Behavior**:
It generates incorrect code.

**Comment by jasonmalinowski** [comment]
Removing nullable reference types flags, as this is a bug around nullable *value* types.

**Comment by CyrusNajmabadi** [comment]
Not repro.  We do not offer to remove the parentheses:

![image](https://user-images.githubusercontent.com/4564579/152903148-4c6d5cde-f883-4eeb-9fac-46b54fffbccc.png)
