### ISSUE TITLE
Implicit class-local object field for lock statement

### ISSUE THREAD

**Issue by kameko** [dotnet/roslyn#35233]
**Version Used**: C# 7

I use the `lock` statement a fair bit, and I find it very redundant that for every single time I have used it, across the span of years, I have, in all cases, had to write exactly one read-only object field in every class I use it with, and then reference that object as the object to lock on, only inside the class it was defined. I've never needed more than one object, I've never needed to pass the object outside of the class. Why is it that the lock statement can't simply take the form of
```cs
lock
{
    // ...
}
```
and just create a private internal object field in that class? For multiple statements, they would just refer to that same object. The old syntax would still be there for the edge cases of requiring a handle on the object, but for every case of the `lock` statement I've ever seen, it hasn't been needed in those cases. I don't see this case being any different from an auto-property versus a fully-written property with an explicitly-written backing field.

Sorry if this has already been suggested, but I couldn't find a suggestion already made for it. I would have done this years ago but I figured it was such an obvious idea that it was already suggested and just shot down. It's a complaint I see from new C# users all the time.

**Comment by benaadams** [comment]
Can add `[MethodImpl(MethodImplOptions.Synchronized)]` to the methods instead?

**Comment by kameko** [comment]
> 
> 
> Can add `[MethodImpl(MethodImplOptions.Synchronized)]` to the methods instead?

That doesn't work the same way (synchronizes the entire method instead of only lock-critical parts which is almost always awful for performance), I also recall someone official (I think a blog post from a microsoft employee) that it's a bad idea and might even be deprecated. Although the latter isn't even an issue really, the former issue of not being able to choose where your locking code is and isn't in a method is a bad idea. I use the lock statement very explicitly in my code to only lock over what I absolutely need to, and it's usually preceded or followed by code that really doesn't need to be wasting cycles locking on something for no reason.

**Comment by gafter** [comment]
If this is a language suggestion, please move it to `csharplang`.  I doubt we would do it because it would increase storage allocation without the user seeing where the storage came from.

If this is an IDE suggestion, we can label it as such.  Which is it?

**Comment by gafter** [comment]
Will reopen when we hear what the intent is: language or IDE suggestion.

**Comment by kameko** [comment]
Sorry, it is a language suggestion, I was not aware of the csharplang repo. I'll repost it there. You can close this.
