### ISSUE TITLE
"Introduce 'using' statement" causes compilation error

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/roslyn#35237]
**Version Used**: VS 16.0.0, .NET Core 2.1

**Steps to Reproduce**:

1. Add the following code

```csharp
var connection = new SqlConnection();
var command = connection.CreateCommand();
command.ExecuteNonQuery();
```

2. Go to the first line and type Ctrl+.
3. Select "Introduce 'using' statement"

**Expected Behavior**:

Code continues to compile after refactor.

```csharp
using (var connection = new SqlConnection())
{
    var command = connection.CreateCommand();
    command.ExecuteNonQuery();
}
```

**Actual Behavior**:

The refactor causes a compiler error.

```csharp
using (var connection = new SqlConnection())
{
    var command = connection.CreateCommand();
}
command.ExecuteNonQuery(); // Compiler error
```

**Comment by CyrusNajmabadi** [comment]
tagging @jnm2.  It's def an interesting case.  I think we coudl do the additional analysis to see which variables are going to be wrapped, and to continue extending the scope to enclose their references as appropriate.

**Comment by jnm2** [comment]
@CyrusNajmabadi There was some discussion on what it should do at https://github.com/dotnet/roslyn/pull/30106#issuecomment-427688516. I was thinking along these lines. @Neme12 thought it should do this:

```cs
SqlCommand command;
using (var connection = new SqlConnection())
{
    command = connection.CreateCommand();
}
command.ExecuteNonQuery(); // Compiler error
```

It seems like a safe rule of thumb that any time a disposable appears in a variable declaration's initializer, the disposable's lifespan should be extended to include the lifespan of that variable.

**Comment by CyrusNajmabadi** [comment]
I'd much prefer the expected behavior of https://github.com/dotnet/roslyn/issues/35237#issue-436814352.

If we were to do the splitting, i would think that woudl be a *secondary* fix option for this feature.  i.e. fix-1 would be to extend the range of the using.  fix-2 would be to keep it narrow, but break the dependent variable+initializers.  That said, i don't really think fix-2 needs to be offered.

**Comment by jnm2** [comment]
In the next few weeks it would be unfair for me to carve out time for this from my other OSS commitments, but I'd be interested in fixing it at some point if no one else gets there first.

**Comment by Eilon** [comment]
For reference (and searchability), this shows up as `IDE0067` in the IDE.
