### ISSUE TITLE
Make CompilationErrorException Serializable

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/roslyn#3528]
All public exceptions should be marked as SerializableAttribute. This is extremely important in the case when calling scripting APIs from a different app domain rather than default. This allows the exceptions to be transmitted to the default domain so application components can receive and handle this exception.

**Comment by gafter** [comment]
The concept of serialization is not available in core CLR, so we're not going to do this.
/cc @tmat

**Comment by tmat** [comment]
@mazhou-msft If you expect the exception to cross AppDomain boundary you can catch it, save the information you'll need on the remote other end in your custom serializable exception implementation and throw it.

**Comment by mazhou-msft** [comment]
@tmat  I know this workaround, I just do the exact same thing as you mentioned. 

I don't quite know the reason why CoreCLR does not have the System.SerializableAttribute, however, The .NET Class Library design guidelines require all exceptions types to be marked with this attribute for the desktop versions, just wondering if we can add some conditional flags to make it compliant with the desktop library design: for example:

'''C#
#if !CORE_CLR
[Serializable]
#endif
public sealed class CompilationErrorException : Exception { ... }
'''

**Comment by tmat** [comment]
@mazhou-msft We only build a single set of binaries that work everywhere. No #if-defs. I believe the reason why Serializable attribute is not included is that Remoting and the default binary serialization are obsolete concepts. The guidelines should be updated. @terrajobst

**Comment by ce-smith** [comment]
This issue should be reconsidered given the lack of collectible assemblies. Right now the only way to prevent out of memory exceptions using Roslyn for C# script execution is to execute the script in it's own AppDomain so it can be unloaded on completion.

Also, not marking this exception as serialize violates the principle of least surprise given all other exceptions are marked as such.
