### ISSUE TITLE
Feature Request: Signature Help & Quick Info for collection initializers

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#3529]
When I press Ctrl+Shift+Space in a collection initializer (whether brace-less single argument or multiple arguments wrapped in braces), can you show signature help for every available `Add()` method?  (with a note indicating that it's being called as a collection initializer)

**Comment by DustinCampbell** [comment]
I have a few concerns here. In no particular order:

* Multiple Add overloads are rarely used in single collection initializers. So, the ROI is low.
* Collection initializers are a language abstraction that we'd be leaking a bit by providing tooling while typing.
* Different Add overloads could apply for each element. That seems to indicate that traditional signature help might not be as effective for this particular language construct.

I wonder if Quick Info might be a better experience here. The tool tip on hover should show the Add() method that was picked.

**Comment by SLaks** [comment]
- Even if there aren't multiple overloads, it'd still be useful to see the parameter names, types, & descriptions for the single overload.  Especially for more-interesting usages of this feature like http://blog.slaks.net/2015-06-16/code-snippets-variadic-generics-csharp/ or https://github.com/madskristensen/WebEssentials2013/blob/9316c9f373d4d764148f01e1402a2bf7a2e4ffda/EditorExtensions/CSS/Adornments/ColorTagger.cs#L53-L62

 - So? Even if it's a language abstraction, it's still calling a function that has a defined signature

 - This should apply for each element (inside braces or between commas).

Quick info would also be nice, although I'm not sure where you'd put it when there aren't any braces.

**Comment by DustinCampbell** [comment]
> So? Even if it's a language abstraction, it's still calling a function that has a defined signature

That's a big can of worms though. Would we do the same for query expressions? How about the GetEnumerator in foreach? I expect this would muddy the experience signifcantly. I think there might be a different feature here. Current signature help feels like it wouldn't be the right thing.

FWIW, you *can* get signature help. Just don't use a collection initializer and call the add methods? Why use a language abstraction if you don't want the details abstracted away for you? :sweat_smile: :heart:

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
