### ISSUE TITLE
error CS0019: Operator '==' cannot be applied to operands of type 'KeyValuePair<ulong, string>' and 'KeyValuePair<ulong, string>'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35298]
VSF_TYPE_MARKDOWNpublic class StringColumnActor : IStringColumnActor
    {
        private readonly AsyncGate _gate = new AsyncGate();

        // TODO: replace with persistent storage
        private readonly IDictionary&lt;ulong, string&gt; _valueDictionary = new Dictionary&lt;ulong, string&gt;();

        public StringColumnActor()
        {

        }

        public async Task&lt;ulong&gt; GetOrAddValueAsync(string value)
        {
            using var gateLock = _gate.WaitAsync();

            var kvp = _valueDictionary.FirstOrDefault(kvp =&gt; kvp.Value.Equals(value, StringComparison.InvariantCultureIgnoreCase));

            if (kvp == default(KeyValuePair&lt;ulong, string&gt;))
            {

            }
        }
    }

// Using dotnet core 3.0 preivew
// From Compiler Output. 1&gt;Databases\Columns\IStringColumnActor.cs(34,17,34,60): error CS0019: Operator '==' cannot be applied to operands of type 'KeyValuePair&lt;ulong, string&gt;' and 'KeyValuePair&lt;ulong, string&gt;'

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/475398/error-cs0019-operator-cannot-be-applied-to-operand.html
VSTS ticketId: 807156_
_These are the original issue comments:_

Visual Studio Feedback System on 3/4/2019, 00:46 AM (53 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by agocke** [comment]
FYI @jaredpar This looks like it may be a breaking change

**Comment by agocke** [comment]
Simplied code:

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

public class StringColumnActor
{

    // TODO: replace with persistent storage
    private readonly IDictionary<ulong, string> _valueDictionary = new Dictionary<ulong, string>();

    public StringColumnActor()
    {

    }

    public void GetOrAddValueAsync(string value)
    {
        var kvp = _valueDictionary.FirstOrDefault(kvp => kvp.Value.Equals(value, StringComparison.InvariantCultureIgnoreCase));

        if (kvp == default(KeyValuePair<ulong, string>))
        {

        }
    }
}
```

**Comment by canton7** [comment]
Isn't the simplified code just

```csharp
public void M() {
    var kvp = new KeyValuePair<ulong, string>();
    if (kvp == default(KeyValuePair<ulong, string>)) { }
}
```

And, unless I'm missing something, isn't this just because `KeyValuePair<TKey, TValue>` doesn't define a `==` operator?

**Comment by gafter** [comment]
@canton7 is correct.  The compiler is correct.  `KeyValuePair<TKey, TValue>` does not define any `operator ==`.
