### ISSUE TITLE
Temporary Storage doesn't maintain Encoding

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#353]
it has been fixed and it looks like it got regressed due to other perf optimization change (https://github.com/dotnet/roslyn/commit/ce08a954a59edd07a1dd12e367246ff140fdc489).

I forgot to add an unit test when I fixed the original bug. I will add an unit test and re-opening the bug in GitHub.
(TestTemporaryStorageTextEncoding) in TemporaryStorageServiceTest

**Comment by pharring** [comment]
@heejaechang Sorry about that.

**Comment by heejaechang** [comment]
@pharring sorry, I forgot to add the unit test. I thought I did and apparently I didn't :(

**Comment by pharring** [comment]
I'm working on a fix.
