### ISSUE TITLE
Roslyn’s function name resolver should support DkmBaseDebugMonitorId.TimeTravelTraceInterop

### ISSUE THREAD

**Issue by kceiw** [dotnet/roslyn#35317]
The function breakpoint isn't set to TimeTravelTraceInterop because of this issue https://devdiv.visualstudio.com/DevDiv/_workitems/edit/824993

**Comment by CyrusNajmabadi** [comment]
@kceiw I'm not sure what you're asking us to do here.  Our lang service implements: 

```c#
            public int ResolveName(string pszName, uint dwFlags, out IVsEnumDebugName? ppNames)
```

1. i don't know what DkmBaseDebugMonitorId.TimeTravelTraceInterop is.
2. I don't know when it would be set.
3. i don't know how it would be passed back to you. 

Can you supply some more information/docs on this subject to let us know what we need to do here?
