### ISSUE TITLE
Suboptimal codegen for conditional access on readonly unconstrained generic field

### ISSUE THREAD

**Issue by canton7** [dotnet/roslyn#35319]
This is minor. It does not cause incorrect behavior, but it does cause generated code to be larger than it needs to be in some cases.

**Version Used**: 

Master (26 April 2019)

**Steps to Reproduce**:

```csharp
public class Foo<T>
{
    private readonly T ro;
    private T rw;
    
    public void PrintRo() => Console.WriteLine(ro?.ToString());
    public void PrintRw() => Console.WriteLine(rw?.ToString());
}
```

Look at the emitted IL for `PrintRo`.

[SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWAChsBmQgJnwDEB7ZgHgBUA+Sgb0vyD8ABwQBLAG4R4+BHAgpmAOwA2AT3wdZzchSEjxUmVoQB3XfoFCahACz4ACuKUwASswAUASnwBeLoREAJweCMwA/AB0HMwAyjDOAObeXhbWtNj2TmIurqbefgHEIWZRMfFJKboAvpRAA=).

**Expected Behavior**:

The lowered version of `PrintRo` should look something like (in C#):

```csharp
public void PrintRo()
{
    T copy = ro;
    Console.WriteLine((copy != null) ? copy.ToString() : null);
}
```

**Actual Behavior**:

The lowered version of `PrintRo` makes a copy of `ro` correctly, and then the codegen for conditional access pulls out the full force of its "ensure the receiver is only accessed once while still making sure it receives any mutations" logic, and emits something like this (in C#):

```csharp
public void PrintRo()
{
    T val = ro;
    ref T reference = ref val;
    T val2 = default(T);
    object value;
    if (val2 == null)
    {
        val2 = reference;
        reference = ref val2;
        if (val2 == null)
        {
            value = null;
            goto IL_0038;
        }
    }
    value = reference.ToString();
    goto IL_0038;
    IL_0038:
    Console.WriteLine((string)value);
}
```

**Discussion**:

This involves [`CodeGenerator.EmitLoweredConditionalAccessExpression`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/CodeGen/EmitExpression.cs,386).

It looks like this method got confused. The body of the `PrintRo` method below `T val = ro;` is what is emitted when the receiver of the conditional access is an unconstrained generic which can change between calls (such as the `T rw` field). That's expected in the body of the `PrintRw` method. However in this case the field is `readonly`, and so a copy is created by `EmitReceiverRef` (ultimately [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/CodeGen/EmitAddress.cs,424)), which produces the `T val = ro;`. However the rest of `EmitLoweredConditionalAccessExpression` doesn't notice that it's now working with a copy, and proceeds as if it's accessing the original field.

Looking [at the blame](https://github.com/dotnet/roslyn/blame/a8b934866f7a3c51d3034025cb8d150de9b6d0bf/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs#L401), it looks like this is probably unintentional.

This is a niche case, but it does affect anonymous types' `ToString` methods, [for example](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWAChsBmQgJnwGF8BvS/Dw27AFnwFkAFAEpW7ThIBuEBPgAe+ALz4AdnADurfAE8l+IvgC+5ChMOVDQA===). This `ToString` method is significantly larger than it needs to be.

**Comment by YairHalberstadt** [comment]
I think this can be closed now.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/35979
