### ISSUE TITLE
Possible NullReferenceException in ObjectFormatterHelpers.cs

### ISSUE THREAD

**Issue by pkulikov** [dotnet/roslyn#35322]
When `type` is null, the first operand of `||` evaluates to `false`. That means the second operand is evaluated. The second operand of the `||` operator is `targetTypeName != null && type.FullName == targetTypeName`. If `targetTypeName` is not null, `type.FullName` would throw.

https://github.com/dotnet/roslyn/blob/a8b934866f7a3c51d3034025cb8d150de9b6d0bf/src/Scripting/Core/Hosting/ObjectFormatter/ObjectFormatterHelpers.cs#L88-L92

Source: one of the issues found in #34725

**Comment by jinujoseph** [comment]
cc @tmat

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative and no hits.
