### ISSUE TITLE
Possible NullReferenceException in AbstractConvertForToForEachCodeRefactoringProvider.cs

### ISSUE THREAD

**Issue by pkulikov** [dotnet/roslyn#35320]
If `collectionType.Type` is really null, then the consequent check throws.

https://github.com/dotnet/roslyn/blob/a8b934866f7a3c51d3034025cb8d150de9b6d0bf/src/Features/Core/Portable/ConvertForToForEach/AbstractConvertForToForEachCodeRefactoringProvider.cs#L136-L140

Source: one of the issues found in #34725

**Comment by sharwell** [comment]
:memo: this should be caught by nullable reference types

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/53287
