### ISSUE TITLE
Possible NullReferenceException in TextViewWindow_InProc.cs

### ISSUE THREAD

**Issue by pkulikov** [dotnet/roslyn#35321]
When the exception message is formatted, `action.DisplayText` throws because `action` is null?

https://github.com/dotnet/roslyn/blob/a8b934866f7a3c51d3034025cb8d150de9b6d0bf/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/TextViewWindow_InProc.cs#L380-L385

Source: one of the issues found in #34725

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of hits.
