### ISSUE TITLE
SnapshotSerializationTests.cs seems to be duplicating logic from SolutionCreator.cs

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#35335]
While chatting with @heejaechang we noticed that SnapshotSerializationTests.cs has a helper GetSolutionAsync that reconstructs a solution from a remotable data service. If you squint a bit, that's also what SolutionCreator.cs is doing, but there's just not a shared interface for both of them to be using. This should be unified so we're not maintaining that logic twice, and also so then we get additional test coverage of SolutionCreator.cs.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
