### ISSUE TITLE
Saving .aspx files slow

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35345]
VSF_TYPE_MARKDOWNSaving an smallish (300 front, 400 loc code behind) .aspx control takes seconds vs the second or two for VS 2017.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/470148/saving-aspx-files-slow.html
VSTS ticketId: 802507_
_These are the original issue comments:_

Visual Studio Feedback System on 2/26/2019, 08:55 PM (61 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 2/26/2019, 11:48 PM (61 days ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
The majority of time spent saving in the performance trace attached to the feedback issue is in `SymbolDisplay.ToDisplayParts`. Specifically, when `SymbolDisplayVisitor.VisitNamedType` calls `SourceMemberContainerTypeSymbol.GetEmittedNamespaceName`, the original syntax tree may be required for the result causing slow loads of the syntax trees from temporary storage. The symbol display performance would be substantially improved by eliminating the need to load syntax trees from disk.

**Comment by CyrusNajmabadi** [comment]
We no longer have temporary storage.  Closing this out.
