### ISSUE TITLE
Invalid "Add parameter" suggestion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35342]
VSF_TYPE_MARKDOWN1. Create new .net core console app project;
2. Paste the following code:

```
using System;

namespace AddParameterBug
{
    class A
    {
    }

class B : A
    {
    }

class Program
    {
        static void Main(string[] args)
        {
            var b = new B();
            Foo(b);
        }

private static void Foo(A a)
        {
        }
    }
}
```

3. Change the `Foo(b);` to `Foo(b, 1);` in `Main`;
4. `Foo` call gets the red squiggly;
5. Right click red squiggly and pick &quot;Quick actions and refactorings&quot;;
6. Pick the &quot;Add parameter to 'Program.Foo(A)'&quot;;
7. Notice that `Foo(A a)` became `Foo(B b, A a)`, which is incorrect and unexpected;

Method should change to `Foo(A a, int something)`.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/545907/invalid-add-parameter-suggestion.html
VSTS ticketId: 855387_
_These are the original issue comments:_

Visual Studio Feedback System on 4/25/2019, 01:12 AM (4 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 4/29/2019, 00:33 PM (4 min ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  We get the expected:

![image](https://user-images.githubusercontent.com/4564579/152617609-e304e58c-4129-414a-ae02-a8ebcc2e84e9.png)
