### ISSUE TITLE
Localize the interpolated string feature error message

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#3535]
The interpolated string error message for VB language version is not localized due to a timing issue.  This needs to be corrected in the next release.  

Context: https://github.com/dotnet/roslyn/pull/3526

**Comment by jaredpar** [comment]
Moving diagnostic related issues to 2.0

**Comment by gafter** [comment]
I believe this refers to the following in Parser.vb

```vb
                ' Bug: It is too late in the release cycle to update localized strings.  As a short term measure we will output 
                ' an unlocalized string and fix this to be localized in the next release.
                Return ReportSyntaxError(node, ERRID.ERR_LanguageVersion, languageVersion.GetErrorName(), "interpolated strings")
```

@jaredpar When does it become too late for this release cycle?

**Comment by jaredpar** [comment]
I don't know the exact date but it will be much closer to RTM.
