### ISSUE TITLE
Crash trying to unload project from large solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35358]
**Build filed on** : 15.7.27612.0 
**Priority** : 1 

I have a large (~400 project) solution and I've been experimenting with manually unloading projects (by right-clicking and saying unload in the solution explorer) as an alternative to the Funnel extension that no longer works in VS 2017. Some projects unload no problem. Others take a really long time, or never finish unloading, or crash. I'm attaching a crash dump of a crash, and a recording of unloading the same project that didn't crash but did hang the UI for a long time. I'm guessing the task manager window I brought up during the unload isn't visible but you can see the process consume over 2.8GB of RAM at one point which is presumably right on the edge of crashing.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/236142/crash-trying-to-unload-project-from-large-solution.html
VSTS ticketId: 602709_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by davkean** [comment]
Adding context:
@sharwell said:

> The underlying issue here is 2404 instances of Solution held by RaiseWorkspaceChangedEventAsync (a closure in this method holds a reference to the old solution). These solutions reference 2173 instances of ProjectDependencyGraph through SolutionState, totaling nearly 1GiB of managed memory.

@heejaechang said:

> we should stop using EventQueue that just continuewith tasks blindly. but create actual Async queue.

**Comment by CyrusNajmabadi** [comment]
Clsoing out due to lack of hits on this.
