### ISSUE TITLE
Allow attributes on local function parameters

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#35350]
From discussion in LDM today (4/29/2019), this would help with async-iterator local functions that want to use `[EnumeratorCancellation]`.

We should also test other attributes:
- `[DoesNotReturn]`
- `[DoesNotReturnIf(bool)]`
- `[Disallow/Allow/Maybe/NotNull]`
- `[Maybe/NotNullWhen(bool)]`
- `[Obsolete]`
- ...

FYI @agocke

**Comment by RikkiGibson** [comment]
Closing for simplicity, the scenarios described in this issue are present in #38801
