### ISSUE TITLE
NFW on document navigation service - top 3 on 15.9

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#35353]
Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.CanNavigateToSpan(Workspace,DocumentId,TextSpan)

https://features.vsdata.io/investigatefault?mt=MAC_ADDRESS_HASHES&et=FAULT&sd=2019-03-29&ed=2019-04-28&pn=vs&fn=ide/vbcs/nonfatalwatson&en=nonfatalwatson&fh=64b8d182-a17b-9bfd-493d-ed4a737d2b2d&bl=d15.9$15.9.28307.586$15.9.11$visualstudio.15.release&bl=d15.9$15.9.28307.557$15.9.10$visualstudio.15.release&bl=d15.9$15.9.28307.518$15.9.9$visualstudio.15.release&bl=d15.9$15.9.28307.481$15.9.8$visualstudio.15.release&bl=d15.9$15.9.28307.423$15.9.7$visualstudio.15.release&bl=d15.9$15.9.28307.344$15.9.6$visualstudio.15.release&bl=d15.9$15.9.28307.280$15.9.5$visualstudio.15.release&bl=d15.9$15.9.28307.222$15.9.4$visualstudio.15.release&bl=d15.9$15.9.28307.145$15.9.3$visualstudio.15.release&bl=d15.9$15.9.28307.108$15.9.2$visualstudio.15.release&bl=d15.9$15.9.28307.105$15.9.1$visualstudio.15.release&bl=d15.9$15.9.28307.53$15.9.0$visualstudio.15.release&ex=devenv&ut=external

https://watsonportal.microsoft.com/CabSearch?DateTimeFormat=UTC&MaxRows=100&P3=vs.ide.vbcs.nonfatalwatson&P4=system.argumentoutofrange&P5=microsoft.visualstudio.languageservices&P6=microsoft.visualstudio.languageservices.implementation.visualstudiodocumentnavigationservice.cannavigatetospan

cab
https://watsonportal.microsoft.com/Failure?FailureSearchText=a4a50075-0cc2-7be4-10d5-9cc7f0b5801a#

**Comment by genlu** [comment]
Seems typescript might be involved here? @heejaechang Do you know how can I get the stacktrace to show here?

FYI @amcasey 

![image](https://user-images.githubusercontent.com/788783/59234778-251b7f80-8ba3-11e9-87fa-b68af3fee55b.png)

**Comment by amcasey** [comment]
I'm kind of bothered that you don't have TS symbols.  Were they not available?

**Comment by genlu** [comment]
I have symweb as symbol server. Not sure what's going on. Could you please try to open one of the dumps and see if you can get a complete stacktrace?

**Comment by amcasey** [comment]
I'm seeing 
```
Microsoft.VisualStudio.LanguageServices.dll!Microsoft.CodeAnalysis.ErrorReporting.WatsonReporter.Report(string description, System.Exception exception, System.Func<Microsoft.VisualStudio.Telemetry.IFaultUtility, int> callback)
Microsoft.VisualStudio.LanguageServices.dll!Microsoft.CodeAnalysis.ErrorReporting.WatsonReporter.Report(System.Exception exception)
Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler)
Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.CanNavigateToSpan(Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.DocumentId documentId, Microsoft.CodeAnalysis.Text.TextSpan textSpan)
[Native to Managed Transition]	
[Managed to Native Transition]	
Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.CanNavigateToSpan(Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.DocumentId documentId, Microsoft.CodeAnalysis.Text.TextSpan textSpan)
Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.DocumentSpanExtensions.CanNavigateTo(Microsoft.CodeAnalysis.DocumentSpan documentSpan)
Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.FindUsages.DefinitionItem.DefaultDefinitionItem.CanNavigateTo(Microsoft.CodeAnalysis.Workspace workspace)
Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.TypeScript.Features.GoToDefinition.NamedDefinitionItemExtensions.TryGetNavigableDefinitionItem(Microsoft.CodeAnalysis.Editor.TypeScript.Features.GoToDefinition.NamedDefinitionItem namedDefinition, Microsoft.CodeAnalysis.Solution solution, Microsoft.CodeAnalysis.Editor.TypeScript.Features.GoToDefinition.IFilePathDefinitionItemProvider filePathDefinitionItemProvider, Microsoft.VisualStudio.Threading.JoinableTaskContext joinableTaskContext, out Microsoft.CodeAnalysis.FindUsages.DefinitionItem definitionItem)
Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.TypeScript.Features.GoToDefinition.TypeScriptGoToSymbolService.GetSymbolsAsync(Microsoft.CodeAnalysis.Editor.GoToDefinition.GoToSymbolContext context)
```

AFAIK, I don't have any special symbol settings for TS.

**Comment by genlu** [comment]
OK. I need to check my debug settings, I might have messed up something... I looked at a few dumps for this NFW, they all seems to have the same stacktrace. Do you guys wanna investigate first?

**Comment by amcasey** [comment]
I think @PranavSenthilnathan is already looking at a related issue.

**Comment by jinujoseph** [comment]
@amcasey can you link the bug information , has that been resolved ?

**Comment by jinujoseph** [comment]
Tracked [here ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/867118/)

**Comment by CyrusNajmabadi** [comment]
Closing out as this was fixed ages ago.
