### ISSUE TITLE
Ongoing IDE error messages in VS 2019 for valid code.

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#35363]
**Version Used**:  3.2.0-beta1-19229-02

**Steps to Reproduce**:

1. Create a generic class where `T` is constrained as `unmanaged`
2. Invoke methods on class using a truly `unmanaged struct`

**Expected Behavior**: The code is legal and compiles so the IDE should not report errors.

**Actual Behavior**: Errors are reported in the IDE when editing and when building (but the output window says clean compile and code runs).

The code sample here https://github.com/dotnet/roslyn/issues/35324 does this (even though it compiles).

**Comment by CyrusNajmabadi** [comment]
@Korporal I do not see the behavior you're talking about:

![image](https://user-images.githubusercontent.com/4564579/56979271-3f872580-6b2e-11e9-8c59-8731ba79492b.png)


![image](https://user-images.githubusercontent.com/4564579/56979301-4f9f0500-6b2e-11e9-84d1-b928faead048.png)


![image](https://user-images.githubusercontent.com/4564579/56979317-5cbbf400-6b2e-11e9-97b0-0caae616e0a8.png)


Can you please supply a more complete repro?

**Comment by Korporal** [comment]
@CyrusNajmabadi - Sure, away from office just now will try to clarify later today.
