### ISSUE TITLE
Remove custom entry point finder from Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractEntryPointFinder

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#35376]
Use `Compilation.GetEntryPoint` instead.

Also, use `IEntryPointFinderService` MEF component in `ICSharpProjectSite.GetValidStartupClasses` `IVbCompilerProject.GetEntryPointsList` and move the MEF component to Features.

Update the interface to take a ProjectId instead of a symbol. So that `GetValidStartupClasses` and `GetEntryPointsList` do not access symbols directly.

**Comment by tmat** [comment]
The current implementation seems to be out-of-date and not support `async Main`.

**Comment by CyrusNajmabadi** [comment]
I don't understand how we can actually remove this.  The point here (as i understand it) is that there might be *multiple* entrypoints possible in a project, and this returns the set of them so that teh user can pick from one.

I will update this to understand async main though.
