### ISSUE TITLE
Ctor Initializer normalization is inconsistent with neighboring areas like class decl lists

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/roslyn#35371]
I present the issue by contrast, when I specify a class declaration without trivia then request ``.NormalizeWhitespace()``, I get something like this for a class declaration, which is what I would expect, focus on the colon normalization:

```C#
public class A : B
//            ^^^ I would expect this.
{
   // ...
}
```

However, when I generate a constructor, the constructor initializer does not normalize quite like I would expect, we get this:

```C#
public A(int value): base(value)
//                 ^^ I would not expect this.
{
}
```

The behavior is similar regardless of the *Constructor Initializer*:

```C#
public A(int value): this(value)
{
}
```

I could intercede, possibly, and inject trivia bits, but I'd like not to have to do that for a code generator. I'd rather focus on the business at hand and let the normalization (policies?) handle those issues correctly, or at least as expected, transparently.

By comparison/contrast, typically this formatting is expected:

```C#
public A(int value) : base(value)
//                 ^^^ I would expect this.
{
}
```

For that matter, perhaps new line plus indentation might be a better policy.

Also, if the gitter discussion is any indication, let's not confuse these contexts with others in which ``colon`` is a necessary token in the syntax, i.e. ``switch (x) { case y: ... }``.

Short of a bug fix, is there a way to specify the normalization policy?

**Comment by CyrusNajmabadi** [comment]
@mwpowellhtx You can use the roslyn workspace formatter (not the same as NormalizeWhitespace) to better handle formatting and to more closely align with how people format in VS.  That API is available here: 

https://github.com/dotnet/roslyn/blob/bc1540c4ccf2f07e4b6a3641675b74c85ac29a7a/src/Workspaces/Core/Portable/Formatting/Formatter.cs#L160

**Comment by CyrusNajmabadi** [comment]
>Short of a bug fix, is there a way to specify the normalization policy?

No.  The point of normalization is to remove any sort of policy.  That way it gets *normalized* to one uniform form.

**Comment by CyrusNajmabadi** [comment]
@mwpowellhtx If you would like to contribute a fix here, you can find the requisite code at: https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs

That said, it will take time for that to go through and be released in a form you can then use.  You can use [Formatter](https://github.com/dotnet/roslyn/blob/bc1540c4ccf2f07e4b6a3641675b74c85ac29a7a/src/Workspaces/Core/Portable/Formatting/Formatter.cs#L160) today and get the behavior you want.

**Comment by mwpowellhtx** [comment]
@CyrusNajmabadi Nice try, but I do not have the bandwidth beyond observing the bug and reporting the issue.

**Comment by CyrusNajmabadi** [comment]
>@CyrusNajmabadi Nice try, but I do not have the bandwidth beyond observing the bug and reporting the issue.

This is likely the code to fix:

https://github.com/dotnet/roslyn/blob/bc1540c4ccf2f07e4b6a3641675b74c85ac29a7a/src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs#L391-L398

You could potentially do the PR entirely on github.  Note that you'll have a couple of tests to fixup here:
https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs
