### ISSUE TITLE
Remove CSharpCompilation.WithAdditionalFeatures

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#35374]
Compilation.Features is, by design, supposed to be the a copy of the Features of all of the syntax trees, which are supposed to be the same as each other.  This is checked when the compilation is created.  If they are not the same, we throw `throw new ArgumentException(CodeAnalysisResources.InconsistentSyntaxTreeFeature, nameof(trees))`.

The recently introduced (nonpublic) method `CSharpCompilation.WithAdditionalFeatures` breaks these invariants.  In disaligns the features on the syntax trees with the features in the compilation.  This method should be removed, or alternately it should reparse the input with the new features. Ideally clients of this API should have parsed using the desired features in the first place.

**Comment by gafter** [comment]
It is only used in one place:

``` c#
            // When nullable analysis does not require a feature flag, this can be removed so that we
            // don't need to create an extra compilation
            if (compilation.Feature("run-nullable-analysis") != "true")
            {
                compilation = compilation.WithAdditionalFeatures(("run-nullable-analysis", "true"));
            }
```

But nullable analysis does not require a feature flag.  All of this is therefore dead code and can be removed.

**Comment by 333fred** [comment]
I changed the title to reflect removing this API. Currently, to get information out of the semantic model you must set this feature flag, this bug will track removing the API when this is no longer true.

**Comment by 333fred** [comment]
https://github.com/dotnet/roslyn/pull/36869 will remove the requirement to set the feature flag to get information out of nullable analysis, and also removes this API.
