### ISSUE TITLE
check whether existing analyzer that return true for OpenFileOnly is returning right value

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#35388]
some have concerns that some analyzers return wrong value for OpenFileOnly (http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/IBuiltInAnalyzer.cs,28)

so someone should go through all our analyzers to check whether they return correct value.

**Comment by heejaechang** [comment]
@jinujoseph why is it assigned to me? I have no idea why some analyzers decide to return true for OpenFileOnly.

each author of analyzers should answer what made them to return true for OpenFileOnly?

do you want me to add all ide people to write here why they choose and not choose to return "false" for OpenFileOnly flag?

**Comment by CyrusNajmabadi** [comment]
@heejaechang You can reach out to the respective people to help them figure it out.  it's possible that the analyzer authors won't know and will need your help and assistance to figure out what the right thing is to to here.  You're the best to lead this effort as you know this API the best and understand the implications of what changes here will cause.

**Comment by sharwell** [comment]
> each author of analyzers should answer what made them to return true for OpenFileOnly?

New analyzers are not to use this. Existing analyzers should be migrated off of it.

**Comment by heejaechang** [comment]
looks like @sharwell looked through. so closing this issue. I believe Rename analyzer is now DocumentAnalyzer which only runs on OpenFile.
