### ISSUE TITLE
Refactor Code Model for OOP

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#35386]
Split the implementation into two parts - one that only operates on Roslyn syntax and semantic nodes and is VS independent, and the other that constructs code model objects from `SyntaxNodeKey`. Move the former to OOP and communicate with VS using `SyntaxNodeKey`.

**Comment by CyrusNajmabadi** [comment]
This would need to be somethign we decide as a team must be done, due to the enormous costs involved here.  We'd need to align it with a business need to get resourcing.  If that happens, we can do the work.  But htis issue isn't needed for tracking that.
