### ISSUE TITLE
Expose Rationalized Completion API

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#3538]
Currently, there is an internal API for retrieving the completion items that would be displayed in a completion list. This is not currently in a shape that is ready for public consumption and needs rationalization.

**Comment by dfkeenan** [comment]
Hi @DustinCampbell ,

Just wondering how you are going with this?  Every now and then I check the repository hoping there is a public API.  If there is one I didn't find it. Guess I should just keep an eye on this thread instead :wink: 

Looking forward to putting your fine work to "good" use.

Cheers,
dfkeenan

**Comment by dfkeenan** [comment]
Pushed back to 1.3 :cry: 

Is there any info on what/how this is going to be exposed?  Even code in a branch or something would be interesting to look at.

**Comment by DustinCampbell** [comment]
How about code in a PR? https://github.com/dotnet/roslyn/pull/8170

**Comment by dfkeenan** [comment]
:open_mouth: Quite an epic PR (as expected).  

If I am reading things right shouldn't be a huge amount of work to transition from the original version. Though I'll probably scratch that project I started back when roslyn was a CTP. 

I eventually want to add scripting support to an app I am working on. I have plenty to do before I "need" this though. I look forward to playing with it when it gets released. :smile: 

Keep up the good work.

**Comment by DustinCampbell** [comment]
Yeah, it is a bit... epic. I think @mattwar was going to try to clean up the PR a bit to make it easier to review. 😊

**Comment by DustinCampbell** [comment]
This was implemented with #8170

**Comment by weltkante** [comment]
Consuming the completion API is blocked by issue #11841 unless you are using Microsoft.VisualStudio.Composition as container (normal MEF container cannot load the CSharp.Feature assembly).
