### ISSUE TITLE
IntelliSense window is incorrectly sized

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn#35393]
**Version Used**: latest

**Steps to Reproduce**:
Turn on the experimenal intellisense completion feature. Type `new X` 

**Expected Behavior**:
IntelliSense dialog is sized correctly

**Actual Behavior**:
Dialog is too narrow until you scroll, then it resizes correctly. Initially it cuts off the namespaces. My display is set at 200% display scaling.

![image](https://user-images.githubusercontent.com/1427284/57019717-3f059200-6bf5-11e9-8d5d-a5e4266949c9.png)

/cc @davkean

**Comment by davkean** [comment]
tag @genlu @olegtk Is this Roslyn or editor?

**Comment by olegtk** [comment]
@AmadeusW

**Comment by jinujoseph** [comment]
moved [over](https://devdiv.visualstudio.com/DevDiv/_queries/edit/864717/?triage=true)
