### ISSUE TITLE
Expose CodeFix and CodeRefactoring API

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#3539]

**Comment by pdelvo** [comment]
Was this supposed to be closed? I dont think the PR and this issue are related

**Comment by DustinCampbell** [comment]
Nope was closed unintentionally. Sorry about that!

**Comment by CyrusNajmabadi** [comment]
@DustinCampbell can we close this?  All this seems to be exposed now (unless there's something else this is referring to).  Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing this out in current form as likely too broad.  Note: we will likely have a means to get this through LSP through their contract around CodeActions.
