### ISSUE TITLE
Test Method not catching an exception, thus not producing a result.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#35392]
This thrown exception at [DesktopRuntimeEnviroment.cs#L245](https://github.com/dotnet/roslyn/blob/8b154a48f7e867747599a04f5e2481f4956011c8/src/Test/Utilities/Portable/Platform/Desktop/DesktopRuntimeEnvironment.cs#L245) can cause the method `CompileAndVerify` to not produce a result at all. I'd expect all exceptions to be caught with these methods. 

Note: True this result is due to *(me)* producing an incorrect lowering for the feature. Any how this isn't about that but the issue with the test runner.
[Code](https://github.com/AdamSpeight2008/roslyn-AdamSpeight2008/tree/Failures/ContinueForID)

Set breakpoint [here](https://github.com/AdamSpeight2008/roslyn-AdamSpeight2008/blob/c543e255205bfd9744023397bd7b7ca5ac9b2738/src/Compilers/VisualBasic/Test/Semantic/Binding/Binder_Statements_Tests.vb#L872)
Set breakpoint [here](https://github.com/AdamSpeight2008/roslyn-AdamSpeight2008/blob/c543e255205bfd9744023397bd7b7ca5ac9b2738/src/Compilers/VisualBasic/Test/Semantic/Binding/Binder_Statements_Tests.vb#L910)
Test this unit test with debug. (as if you are stepping through the code.)
I'd expect the second breakpoint `End Sub` to be hit.

**Comment by gafter** [comment]
This does not appear to be reporting any issue with the behavior of the compilers.
