### ISSUE TITLE
Hebrew Character handling in Visual Studio 2019

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35416]
VSF_TYPE_MARKDOWNHey support,

I was making a console application in visual studio and wanted to use some unicode characters.
After inserting the (ﬡ) 'Hebrew Litter Wide Alef' (U+FB21) in the Console.WriteLine(&quot;ﬡ&quot;); method, I wasn't able to remove the character when I wanted to. This may be related to the right-left reading of the alphabet in other languages.

Kind regards,

Carlos Schipper

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/531862/hebrew-character-handling-in-visual-studio-2019.html
VSTS ticketId: 847290_
_These are the original issue comments:_

Visual Studio Feedback System on 4/15/2019, 02:00 AM (16 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by gafter** [comment]
I tried this and the backspace key did remove the character (even though the character appears to the right of the cursor).  I also tried hitting the left arrow key and hitting the delete character, and that worked too.

**Comment by CyrusNajmabadi** [comment]
Closing out for now as we've heard no other reports and we have direct confirmation that this scenario works.
