### ISSUE TITLE
Parallel.ForEach double tab snippet is wrong

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35413]
VSF_TYPE_MARKDOWNIn Visual Studio 2019, open a CSharp project.
In a .cs file, type **Parallel.ForE**, then, the autocompletion will show you &quot;Parallel.Foreach&quot; and suggest you to press the Tab key twice to insert the snippet.

However, if you press Tab twice, the snippet is the &quot;foreach&quot; snippet and not the &quot;Parallel.ForEach&quot; snippet.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/549971/parallelforeach-double-tab-snippet-is-wrong.html
VSTS ticketId: 857791_
_These are the original issue comments:_

Visual Studio Feedback System on 4/29/2019, 00:09 AM (2 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Ankita, do we have a `foreach` snippet?  if so, can you make sure it doesn't show up mid-expression?

**Comment by akhera99** [comment]
We do, this is the old behavior of tabbing after a keyword expands the snippet, since that was the old design. I need to turn off that behavior for the snippets that have replacements.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in these legacy snippets.
