### ISSUE TITLE
"Use Auto Property" should not fade fields as unnecessary

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35415]
VSF_TYPE_MARKDOWNIf a field is only set in the constructor and accessed in a property declared with an arrow, then the field higlight will be the same as for unused fields; however, using a real getter which access the field does indeed display the correct syntax highlighting.

```
public class Foo
{
    public Foo(int x)
    {
        this.a = x;
        this.b = x;
    }

    public int A =&gt; this.a;
    public int B { get { return this.b; } }

    private readonly int a; // incorrectly colorized as if it were not being used
    private readonly int b; // correctly colorized
}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/530412/incorrect-syntax-coloring-for-used-field.html
VSTS ticketId: 846287_
_These are the original issue comments:_

Visual Studio Feedback System on 4/12/2019, 02:08 AM (19 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by epsitec** [comment]
The code snippet should read:

```csharp
public class Foo
{
    public Foo(int x)
    {
        this.a = x;
        this.b = x;
    }

    public int A => this.a;
    public int B { get { return this.b; } }

    private readonly int a; // incorrectly colorized as if it were not being used
    private readonly int b; // correctly colorized
}
```

**Comment by CyrusNajmabadi** [comment]
@epsitec Both are correctly faded out for me:

![image](https://user-images.githubusercontent.com/4564579/57056321-9ab43780-6c56-11e9-9228-1b1396b2b274.png)


The reason they're faded out is because both can be replaced with an auto-property.  i.e.:

![image](https://user-images.githubusercontent.com/4564579/57056326-a7d12680-6c56-11e9-9a93-0676fb464c68.png)


That's what invoking the suggested fix will do.

**Comment by epsitec** [comment]
Indeed, the latest version of VS 2019 16.0.3 I just installed fixes the issue with the different colorization of `a` and `b`. Now both have the same colorization and the implementation of property `A` using `=>` is properly recognized as referring to `a`. It was not the case with the previous versions.

**Comment by sharwell** [comment]
> We decided to 'fade' because we're indicating "you can remove this"

Per a recent design review, we decided to not fade situations like this. Fading should only be used in cases where we believe a true statement is "if you delete this code without other changes, things will not break".

**Comment by sharwell** [comment]
Per https://github.com/dotnet/roslyn/issues/27213#issuecomment-488558419, I'm marking this as a bug, up-for-grabs, and changing the title for clarity. The specific code that incorrectly applies fading is here:

https://github.com/dotnet/roslyn/blob/e051790e791e0ca6ed36404db17307bea868306e/src/Features/Core/Portable/UseAutoProperty/AbstractUseAutoPropertyAnalyzer.cs#L331-L337

**Comment by CyrusNajmabadi** [comment]
@sharwell fair enough.   At the time we thought it was acceptable.  But it seems reasonable that it would just have the `...` as a normal indicator that there is something reasonable to be done here.
