### ISSUE TITLE
Getting IDE0008 while casting to an obvious type 

### ISSUE THREAD

**Issue by Tape-Worm** [dotnet/roslyn#35417]
**Version Used**: 
Visual Studio 2019 16.0.3
.NET 4.7.2

**Steps to Reproduce**:
I have this code `var id = (ulong?)reader.ReadAsDecimal();` and it's giving me an IDE0008 warning.  This is not at all right as I can clearly see that the casted type will be a nullable ulong.

**Expected Behavior**:
I should not be getting IDE0008

**Actual Behavior**:
I'm getting IDE0008

**Comment by sharwell** [comment]
@Tape-Worm Can you include the 'var' preferences currently applied to your project?

**Comment by Tape-Worm** [comment]
Sure:
![image](https://user-images.githubusercontent.com/9710137/57339100-5eb52280-70ed-11e9-97d8-d15bc07e8905.png)

**Comment by sharwell** [comment]
The preference for 'for built-in types' applies first. Since the type is `ulong?` (base type `ulong`), it prefers to use the explicit type even when obvious.

**Comment by Tape-Worm** [comment]
OK, so why am I getting the same result here:
![image](https://user-images.githubusercontent.com/9710137/57457703-3d5b5000-722d-11e9-9185-0f067486d0f5.png)
And here:
![image](https://user-images.githubusercontent.com/9710137/57457851-87dccc80-722d-11e9-9287-67bf11107117.png)

I would assume decimal and float would be considered built-in types yes?
