### ISSUE TITLE
No add reference option

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35420]
No add reference option appears after right-click reference

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/498243/no-add-reference-option.html
VSTS ticketId: 823203_
_These are the original issue comments:_

Visual Studio Feedback System on 3/19/2019, 11:51 PM (42 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jcouv** [comment]
I don't think we have enough information to reproduce or investigate this issue.
I hope the user is monitoring this issue and can provide a more detailed repro. Otherwise we'll have to close the issue.
