### ISSUE TITLE
Visual Studio 2019: in Console App cannot use unicode \u8377 or \u20B9

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35424]
VSF_TYPE_MARKDOWNit gives me console. Writeline(&quot;\u8377&quot;); gives result: ?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/540833/visual-studio-2019-in-console-app-cannot-use-unico.html
VSTS ticketId: 852172_
_These are the original issue comments:_

Visual Studio Feedback System on 4/22/2019, 01:24 AM (9 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by canton7** [comment]
Is this just because `Console.OutputEncoding` needs to be set to a unicode encoding, and [these steps](https://docs.microsoft.com/en-us/dotnet/api/system.console.outputencoding?view=netframework-4.8#notes-to-callers) followed:

> Note that successfully displaying Unicode characters to the console requires the following:

> - The console must use a TrueType font, such as Lucida Console or Consolas, to display characters.

> - A font used by the console must define the particular glyph or glyphs to be displayed. The console can take advantage of font linking to display glyphs from linked fonts if the base font does not contain a definition for that glyph.
