### ISSUE TITLE
Proposal: symbol group equivalence optimization for simplifier

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#35437]
The following hypothesis might be usable for optimizing the simplifier:

> When attempting to simplify `A.B.C` in any scope [edit: where `C` is not an instance member], if the set of symbols named `C` within the current binder is non-empty and only contains symbols in the container `A.B`, then the qualified reference `A.B.C` may be simplified to `C`.

@jaredpar @gafter can you evaluate this hypothesis for correctness with respect to C# and VB?

**Comment by gafter** [comment]
@sharwell This is not correct, as the container A.B may name an instance other than `this` where `C` should be accessed from.

**Comment by sharwell** [comment]
@gafter Does the hypothesis become correct if we restrict `C` to not be an instance member?

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
