### ISSUE TITLE
Change msbuild property to "Nullable"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#35432]
From LDM today (5/1/2019), we landed on `Nullable` rather than `NullableContextOptions` or `NullableReferenceTypes`.
The property should be a string, since it will accept "enable", "disable" and a couple other values.

Tagging @KathleenDollard @rainersigwald to confirm the name is okay in the msbuild ecosystem.

**Comment by jcouv** [comment]
@rainersigwald Do you see any issue with naming this property "Nullable"?
Previously, we picked longer names thinking we should avoid conflicts, but Jared found no github project referencing a property named "Nullable". LDM preferred "Nullable" because it's easier to remember.

**Comment by rainersigwald** [comment]
No objection here. It's impossible to guarantee that someone somewhere won't already be using a property named `Nullable`, but I didn't turn up anything widespread on GitHub either, so the risk seems acceptable.

The only other thing I'd mention is that other project types use MSBuild, including C++. Having names that refer to broad concepts that apply in multiple languages/compilers/tools increases the possibility of user confusion when it doesn't work in $non_csharp_project_type_x. But that's not blocking. I think `Nullable` is fine.
