### ISSUE TITLE
Proposal: member of type optimization for simplifier

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#35438]
The following hypothesis might be usable for optimizing the simplifier:

> When attempting to simplify `T.X` to `X` in any scope, where `T` is a named type, one of the following must be true for the simplification to succeed (necessary but not sufficient):
>
> 1. `T` is a containing type of the current binder
> 2. A `using static` directive for `T` is provided
> 3. The current language is VB, and `T` is a `Module`

@jaredpar @gafter can you evaluate this hypothesis for correctness with respect to C# and VB?

**Comment by jasonmalinowski** [comment]
In VB, if T is a module, then it's automatically imported into anything that imports the containing namespace. Not hard to adjust your rules, but nonetheless a special case.

**Comment by gafter** [comment]
No, those conditions are not necessary.  It is possible that the members of T is not a containing type of the current binder, but simply some type whose static members are desired, and a `using static directive already exists:

``` c#
using System;
using static System.Math;
class C
{
    int M(int x, int y)
    {
        return Math.Max(x, y); // can be simplified, but does not satisfy (1).
    }
}
```
This illustrates that the suggested conditions are not necessary.

**Comment by sharwell** [comment]
@gafter I was saying one of the two conditions must hold. In your example, the first does not hold but the second does hold, so my hypothesis would apply.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
