### ISSUE TITLE
Switch expressions cannot infer shared type

### ISSUE THREAD

**Issue by dkmiller** [dotnet/roslyn#35443]
**Version Used**: 
Visual Studio Version 16.0.3 + dotnet core 3.0.100-preview3-010431

**Steps to Reproduce**:

```csharp
object Foo(string x)
{
    return x switch
    {
        "a" => 1,
        "b" => "hi",
        _ => throw null
    };
}
```

**Expected Behavior**:

Given the signature of `Foo`, the compiler should be able to infer that the return type of the `switch` expression is `object`.

**Actual Behavior**:

The compiler returns error

> CS8506 C# No best type was found for the switch expression.

If I add a cast to `object` in any of the cases in the `switch` statement (e.g. `"a" => (object)1`) then the code compiles.

**Comment by svick** [comment]
I believe this is the expected behavior for the current preview version of C# 8.0. But it will almost certainly behave the way you suggested in the final version of C# 8.0, see https://github.com/dotnet/csharplang/issues/2389.

**Comment by dkmiller** [comment]
@svick that's great to know, and very exciting news! I think this issue can safely be closed then.
