### ISSUE TITLE
`for (;;)` should not be reformatted as `for (; ; )`

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#35444]
**Version Used**: 16.0.3

This has bugged me way back in VS2017 or earlier. I tend to use `while (true)` now, but touching codebases (mine or others') with `for (;;)` is a pain.

Moving @CyrusNajmabadi's [comment](https://github.com/dotnet/csharplang/issues/2475#issuecomment-487769142):

> > An alternative is for (;;), but various tools reformat it to for (; ; ) and it looks like a hack.
> 
> This seems like an IDE bug. I went and looked at the code here and it loos like we try to support this, but then it fails spectacularly. We legit check:
> 
> ```cs
>             // Semicolons in an empty for statement.  i.e.   for(;;)
>             if (previousParentKind == SyntaxKind.ForStatement
>                 && this.IsEmptyForStatement((ForStatementSyntax)previousToken.Parent))
>             {
> ```
> 
> So we know it's empty, but then we go and just do random stuff with the spacing. As if anyone would actually want `for (; ; )` here. Very bizarre.

@sharwell's [comment](https://github.com/dotnet/csharplang/issues/2475#issuecomment-487775162):

> The behavior has changed a few times. During a review of [DotNetAnalyzers/StyleCopAnalyzers#633](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/633) we determined that the `for` syntax is rarely used in C# code.
> 
> We intentionally chose `for (; ;)` as the formatting in StyleCop Analyzers ([DotNetAnalyzers/StyleCopAnalyzers#1489](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1489)).

**Comment by CyrusNajmabadi** [comment]
If he happy for us to land on one form between VSAnd SCA.  I don't care which wins :-)

**Comment by jnm2** [comment]
Would it be safe to request that whitespace is never added or removed when empty?
