### ISSUE TITLE
Clicking rapidly on Intellisense suggestion box scroll arrows causes it to close unexpectedly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35457]
VSF_TYPE_MARKDOWNClicking at about the rate of a double click on the scroll bar arrows closes the intellisense suggestion box, rather than scrolling.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/551321/clicking-rapidly-on-intellisense-suggestion-box-sc.html
VSTS ticketId: 859269_
_These are the original issue comments:_

Visual Studio Feedback System on 4/29/2019, 09:27 PM (2 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@olegtk can you move this to the editor?  Roslyn does not own the tool window.  (note: it's quite possible this no longer reproes either).

**Comment by olegtk** [comment]
Moved back to https://dev.azure.com/devdiv/DevDiv/_workitems/edit/859269, not sure how it got to Roslyn.
