### ISSUE TITLE
Roslyn compilation doesnt go hand-in-hand with MSBuild

### ISSUE THREAD

**Issue by spanb** [dotnet/roslyn#35485]
**Version Used**: 
15.0
**Steps to Reproduce**:

1. Add a #pragma suppression in code for warning type CS0618 (obsolete field/property use)
2. Roslyn compilation actually fails and in the .sarif output, it spits out this violation s a warning but also indicates that its suppressed in source.
3. MSBuild "thinks" compilation succeeded as this warning is suppressed in code. But because roslyn compilation actually fails, the output assembly is not generated. MSBuild throws no compliation errors when actually the assembly has not been compiled.

**Expected Behavior**:
MSBuild should show compilation error as roslyn has actually not compiled it. 
**Actual Behavior**:
No compilation error is shown unless the following is added to the .csproj <WarningsNotAsErrors>CS0618</WarningsNotAsErrors>

**Comment by jcouv** [comment]
@spanb Could you provide a minimal code sample or project to repro this issue? 
Based on your description above, I don't think we have enough information to reproduce and investigate the issue.

**Comment by gafter** [comment]
I could not repro this.

**Comment by gafter** [comment]
@spanb Can you reproduce this in 16.3 preview?
