### ISSUE TITLE
Add generate parameter to Generate Variable code fix options.

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#35496]
Would it be possible for this list to contain an extra option, generate parameter 'configurationServiceFactory'?

![image](https://user-images.githubusercontent.com/29174528/57149204-1c28d880-6dc3-11e9-9a63-e0ec04a35d09.png)

**Comment by CyrusNajmabadi** [comment]
@YairHalberstadt.  It would be.  Want to contribute the fix? :)

**Comment by YairHalberstadt** [comment]
@CyrusNajmabadi
When I get the chance :-) Should it add it to the implemented/overriden methods as well? What about to other implementations/overrides?

**Comment by CyrusNajmabadi** [comment]
i think adding it seems reasonable :)

**Comment by YairHalberstadt** [comment]
Fixed by #35539
