### ISSUE TITLE
Question: How to add the class itself as reference to CSharpCompilation

### ISSUE THREAD

**Issue by bytecod3r** [dotnet/roslyn#35493]
I want to add the entire program as a reference to my CSharpCompilation.
 In my case, I can NOT use 
`MetadataReference.CreateFromFile(typeof(Program).Assembly.Location),`
Because the result would be null, as I am loading a .Net inside PowerShell with 
`$asm = [Reflection.Assembly]::Load` and execute it this way:

`$type = $asm.GetType("TestApp.Program")`
`$main = $type.GetMethod("Main")`
`$main.Invoke($null, $null)`

I had few tries by converting the Assembly.GetExecutingAssembly() to bytes and then bytes to MemoryStream and tried to add that as a reference by `MetadataReference.CreateFromStream(TestStream)`
but no luck so far, it shows me the following error:
`Metadata file '<in-memory assembly>' could not be opened -- PE image doesn't contain managed metadata.`

Appreciate if you can help. Thank you very much!

**Edit: Using .Net 4.7.2 and Microsoft.CodeAnalysis.CSharp = v3.0.0.**

EDIT: I am converting the assembly to MemoryStream with the following code:

```byte[] bytes;
MemoryStream stream = new MemoryStream();
BinaryFormatter formatter = new BinaryFormatter();
formatter.AssemblyFormat = System.Runtime.Serialization.Formatters.FormatterAssemblyStyle.Full;
formatter.Serialize(stream, typeof(Program).Assembly);
bytes = stream.ToArray();
Stream TestStream= new MemoryStream(bytes);```

**Comment by svick** [comment]
What is the input to `Assembly.Load`? If it's a `byte[]`, can you access that instead of trying to recreate it from the `Assembly` object?

**Comment by bytecod3r** [comment]
I also tried that, that didn't work, Is there any way to pass a pointer or something to the code that is going to be compiled that allow it to access the parent program?
My problem is the code inside Syntax tree cant access the class programmatically.
I'm looking for a replacement for this. `MetadataReference.CreateFromFile(typeof(Program).Assembly.Location),`
to get the assembly of Program and add it as reference.
