### ISSUE TITLE
Documentation missing for Workspace DocumentContext/RelatedDocuments

### ISSUE THREAD

**Issue by weltkante** [dotnet/roslyn#355]
What is the point of "context" documents and the RelatedDocuments API? The source code has little to no comments in that part, public functions like SetDocumentContext etc. (which I'm supposed to implement in my Workspace) don't even have a summary comment.

As far as I understand it "related documents" allow to associate multiple DocumentIds with one SourceTextContainer (aka text buffer) and one of these DocumentIds can be marked as "context document" (also called "active document" in some places).

As far as I can tell all documents opened on the SourceTextContainer will subscribe to the change event and update themselves when the SourceTextContainer raises its change-event. Why would anyone need multiple distinct DocumentIds opened into the same text buffer, all being updated with the same text? What's the point of that functionality? Am I missing anything?

**Comment by Pilchie** [comment]
@dpoeschl Can you take a stab at explaining this (and adding some doc comments)?

**Comment by mattwar** [comment]
Two words:  VISUAL STUDIO
You can have the same text buffer shared when you open multiple documents that are really the same linked document file on disk.

The real question here is whether there needs to be references to this VS concept in the basic API.  I think the problem shows up when specific features implemented at layers below VS want to have special behavior concerning the active document (ie which project's flavor of the document is being represented at the moment), so we get this VS concept shoved down to the bottom of the stack.

**Comment by dpoeschl** [comment]
Yes, this concept of multiple documents sharing a SourceTextContainer appears in two Visual Studio features: linked files and Shared Projects.

Some features (e.g. classification) just want to use the active context document, while other features (e.g. completion) want to combine their results across all linked files.

"SetDocumentContext" is internal, so you shouldn't need to implement that (not an excuse for the lack of documentation).

You can see some better documentation on this feature on the public extensions in Microsoft.CodeAnalysis.Text.Extensions, such as this: http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Text/Extensions.cs,82bf34180667ee95, which states (in part):

```
There may be multiple Documents associated with the buffer if it is linked into multiple projects or is part of a Shared Project.
```

We should still improve the documentation on the internal methods related to this feature and consider addressing the inconsistent naming. @weltkante - Am I missing any public APIs where this method needs improved documentation? Thanks!

**Comment by weltkante** [comment]
Thanks for the explanation, the use case of linked documents sharing the same text buffer in VS was the missing link and gives enough context to understand the purpose of the implementation. This question actually came up a while ago for me when trying to implement a Workspace subclass for a plugin editor, I think at that time SetDocumentContext was protected and I wondered if/how I should implement/use it, but could make no sense of it.

About the documentation, the comments in TextEditorFeatures/Extensions.cs actually do a much better job explaining the purpose than the comments in Workspace_Editor.cs

In particular the public API [Workspace.GetRelatedDocumentIds](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Workspace_Editor.cs,bc4227853d6fee6b) could be improved with explanations from [Extensions.GetRelatedDocuments](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Text/Extensions.cs,05471093cd764108) and [Workspace.GetDocumentIdInCurrentContext](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Workspace_Editor.cs,aa099a9b5021d786) with the explanation from [Extensions.GetOpenDocumentInCurrentContextWithChanges](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Text/Extensions.cs,82bf34180667ee95)

Besides that some comments on SetDocumentContext/OnDocumentContextUpdated/OnDocumentContextUpdated would be nice, in particular since one of them is still protected. If the main use case (linked files in multiple projects sharing the same SourceTextContainer) would be discoverable from Workspace_Editor.cs that would be a great improvement for understanding that part of the source.

**Comment by CyrusNajmabadi** [comment]
Closing as stale.
