### ISSUE TITLE
Generate wrong dependency property callback function

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/roslyn#35518]
@vsfeedback commented on [Fri May 03 2019](https://github.com/dotnet/wpf/issues/645)

1.New a WpfApp;
2.In MainWindow class, use propdp+Tab to generate a dependency property;
e.g.

```csharp
 public int MyProperty
        {
            get { return (int)GetValue(MyPropertyProperty); }
            set { SetValue(MyPropertyProperty, value); }
        }

        // Using a DependencyProperty as the backing store for MyProperty.  This enables animation, styling, binding, etc...
        public static readonly DependencyProperty MyPropertyProperty =
            DependencyProperty.Register("MyProperty", typeof(int), typeof(MainWindow), new FrameworkPropertyMetadata(0,FrameworkPropertyMetadataOptions.Inherits, OnMyPropertyChanged));
```

3.mouse over &quot;OnMyPropertyChanged&quot; and generate method &quot;MainWindow.OnMyPropertyChanged&quot; by visual studio

4.The method's return type and second's parameter type is wrong as :

    ```csharp
        private static object OnMyPropertyChanged( DependencyObject d, object baseValue)
        {
            throw new NotImplementedException();
        }
    ```

the ture methos is :

```csharp
        private static void OnMyPropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs baseValue)
        {
            throw new NotImplementedException();
        }
```

this problem also occurs in visual studio 2019 professional edition.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/539816/generate-wrong-dependency-property-callback-functi.html
VSTS ticketId: 851201_
_These are the original issue comments:_

Visual Studio Feedback System on 4/19/2019, 02:18 AM (14 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

---

@thomasclaudiushuber commented on [Sat May 04 2019](https://github.com/dotnet/wpf/issues/645#issuecomment-489305705)

That's an interesting one. It looks like Visual Studio has a problem to find the correct constructor overload if FrameworkPropertyMetadata is used. Everything works like expected for the base class PropertyMetadata.

It's enough to create a new WPF project and put this in the MainWindow.xaml.cs file:

```csharp
    public static readonly DependencyProperty MyPropertyProperty =
        DependencyProperty.Register("MyProperty", typeof(int), typeof(MainWindow), 
          new PropertyMetadata(0, OnMyPropertyChanged));
```

When you look at this in VS, you'll see that only OnMyPropertyChanged is underlined in red:

![image](https://user-images.githubusercontent.com/7116546/57176121-44144c80-6e54-11e9-8769-a1962a29a1e7.png)

When you put the cursor on it to generate the method, VS will generate it with the right parameters. You can see this here in the preview:

![image](https://user-images.githubusercontent.com/7116546/57176135-6efea080-6e54-11e9-9e2c-fb403fdbbee5.png)

But now let's use the FrameworkPropertyMetadata class instead of PropertyMetadata like this:

```csharp
    public static readonly DependencyProperty MyPropertyProperty =
        DependencyProperty.Register("MyProperty", typeof(int), typeof(MainWindow), 
          new FrameworkPropertyMetadata(0, OnMyPropertyChanged));
```

Now VS also underlines the zero, the specified default value, with a red squiggle. It says it can't convert that int value into a PropertyChangedCallback:

![image](https://user-images.githubusercontent.com/7116546/57176151-aa996a80-6e54-11e9-9b1c-261e420ecbaf.png)

Now, when you put the cursor on the OnMyPropertyChanged method and press CTRL+. to generate that method, the preview shows that the second parameter is not matching the delegates signature anymore:

![image](https://user-images.githubusercontent.com/7116546/57176164-d3216480-6e54-11e9-839e-74e587071eba.png)

---

@weltkante commented on [Sat May 04 2019](https://github.com/dotnet/wpf/issues/645#issuecomment-489310547)

Thats a bug in VS not in WPF. You are getting a `CoerceValueCallback` generated because VS picks the constructor overload `FrameworkPropertyMetadata(PropertyChangedCallback propertyChangedCallback, CoerceValueCallback coerceValueCallback)` when it generates the method. You also can notice this because it complains about zero not being convertible to `PropertyChangedCallback`

This Issue was redirected wrongly, it should be moved over to Roslyn.

---

@thomasclaudiushuber commented on [Sat May 04 2019](https://github.com/dotnet/wpf/issues/645#issuecomment-489312086)

@weltkante Yep, I agree, it's a tooling bug, not a WPF bug.

---

@vatsan-madhavan commented on [Sat May 04 2019](https://github.com/dotnet/wpf/issues/645#issuecomment-489352122)

Moving this issue to dotnet/roslyn and closing since this looks like a intellisense-only problem and not a bug in WPF.

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  I get:

![image](https://user-images.githubusercontent.com/4564579/218163095-ffdd8d24-adc3-4745-ada9-17ce62e83abe.png)

**Comment by weltkante** [comment]
I still seem to be able to reproduce it in VS 2022
![grafik](https://user-images.githubusercontent.com/5845814/218824912-5c35110e-b2ee-4ab4-84ac-46fcf388a80e.png)

I just typed the constructor call in some WPF codebase and it insists on picking the wrong overload, not sure why you are getting different results, you seem to be doing the same thing.

**Comment by weltkante** [comment]
Can confirm that on a Desktop Framework project I get the broken behavior, on a .NET 7 WPF project I get the correct resolution.
