### ISSUE TITLE
I got this massage when ever use csc

### ISSUE THREAD

**Issue by Almark20** [dotnet/roslyn#35522]
This compiler is provided as part of the Microsoft (R) .NET Framework, but only
supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see HTTP
://go.microsoft.com/fwlink/?LinkID=533240

**Comment by jcouv** [comment]
@Almark20 The compiler included in the .NET framework only supports language versions up to C# 5. That's correct.
If you want to use newer versions of C#, you can install Visual Studio (2019 was recently released) or .NET Core (2.2 for instance).

**Comment by Magneticdud** [comment]
What if i want to use the old compiler on old code, there's a flag to bypass&ignore the message or i need to install an old unpatched windows 8 image on a vm for that?

**Comment by CyrusNajmabadi** [comment]
> What if i want to use the old compiler on old code,

you can do that @Magneticdud.  You just won't be able to use new language versions as that old compiler won't understand them.
