### ISSUE TITLE
Find in Files is wasting screen estate

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35527]
VSF_TYPE_MARKDOWNIt seems you're trying to copy ReSharper's wasteful UI in Find in Files. In Visual Studio 2017 I can have a window show me 8 results in a very narrow window. In Visual Studio 2019 the extra useless UI and groupings makes it by default show *two and a half results*, if I scroll down. At first glance I get *half a result*. So you can see how this is a lot worse than previously. I either have to make the UI a lot taller and waste space, or live with very small amount of results at a time.

Please allow a setting where I can disable the &quot;Matching lines...&quot; and &quot;Find all...&quot; things, or move them to the top with the options for which files to find in and what grouping to use etc. Or some other way that will make the feature useful again. The functionality in VS2017 is enough usually.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/519940/find-in-files-is-wasting-screen-estate.html
VSTS ticketId: 841186_
_These are the original issue comments:_

Visual Studio Feedback System on 4/8/2019, 01:05 AM (28 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jmarolf** [comment]
@vatsalyaagrawal I believe this is mis-triaged. This should go to the VS Editor team who made this original change

**Comment by sharwell** [comment]
📝 I'm moving this feedback back to the editor team, which is internal.
