### ISSUE TITLE
Completion from unimported types should strip "Attribute" from attributes

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#35540]
When a namespace is unimported, the completion list for attributes doesn't strip the word "Attribute" from the end.

Before importing:
![image](https://user-images.githubusercontent.com/754264/57257204-9b115180-700d-11e9-99b7-df7a460579f6.png)

After importing:
![image](https://user-images.githubusercontent.com/754264/57257233-a9f80400-700d-11e9-8ea1-18e7c160cacd.png)

It would be ideal if both experiences were the same, or at the very least the actual completion dropped the "Attribute" suffix so the resulting code was more idiomatic.

**Comment by jcouv** [comment]
Tagging @genlu

**Comment by Suchiman** [comment]
Not only is the Attribute word not stripped from the completion list but if you accept the conpletion, it will also write Attribute to the code.

**Comment by genlu** [comment]
> It would be great to have non-attributes and abstract classes to be filtered in attribute context as well, as it happens with regular completions.

It seems abstract attributes are provided by regular completion. I think it makes sense to filter them out in attribute context, but for now I will keep import completion consistent with regular one. Will discuss with team and fix them together if needed.

**Comment by jasonmalinowski** [comment]
Do be careful if you're doing filtering: it'd be strange but totally legal to have an abstract base type, and nested classes that you *can* reference. In those cases you'd have do AbstractBaseType.ConcreteNestedType, which requires you to type the abstract base type first.

A similar case exists in catch() clauses: you can filter to Exceptions, but you have to also include "things you might use to qualify an exception type" which is a bit uglier.

**Comment by genlu** [comment]
Fixed by #36395, with one caveat: we don't show unimported attribute types that don't have proper "Attribute" suffix, for perf reason.
