### ISSUE TITLE
Visual Studio steals focus when a breakpoint is hit

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35545]
1. Start some C# project (e.g. a console app)
2. Set a breakpoint
3. Minimize VS
4. Switch to some other app such as a browser
5. When the breakpoint is hit VS steals focus.

If you happen to be typing at the moment you will now type random text into the code editor triggering EnC.

This is extremely annoying. Please do not take focus (ever).

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/510613/visual-studio-steals-focus-when-a-breakpoint-is-hi.html
VSTS ticketId: 832932_
_These are the original issue comments:_

Visual Studio Feedback System on 3/31/2019, 08:28 PM (35 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Steven Knox on 4/4/2019, 00:02 PM (32 days ago): <p>Such an annoying bug/issue</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
This behavior is controlled by an option:
![image](https://user-images.githubusercontent.com/1408396/57311900-26442300-70b2-11e9-9523-9e3ca90360b5.png)

**Comment by GSPP** [comment]
@sharwell Is this VS 2019? I cannot find it in 2017.

**Comment by sharwell** [comment]
@GSPP Interesting. I was not aware of that, but yes it appears to be a new feature added in Visual Studio 2019.
