### ISSUE TITLE
CommitFormatter can lead to deadlock

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#35553]
The following code will deadlock Visual Studio if `GetOptionsAsync` has a main thread dependency.

https://github.com/dotnet/roslyn/blob/d79e5f2ce4d2d74d2c34afdfe40953d9c7caf69a/src/EditorFeatures/VisualBasic/LineCommit/CommitFormatter.vb#L48

Implementation of a fix for this is blocked on dotnet/roslyn-analyzers#2400.

🔗 https://developercommunity.visualstudio.com/content/problem/526877/navagation-bars.html

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If htere's an issue here we should just fix it.
