### ISSUE TITLE
nullability not applied properly for properties used in a constructor

### ISSUE THREAD

**Issue by gghart** [dotnet/roslyn#35569]
**Version Used**:
VS 2019 16.0.3, C#8.0 in .Net Core 2.1

**Steps to Reproduce**:
#nullable enable

namespace TestApp
{
    class Class1
    {
        public string A { get; set; }

        public Class1 (string a)
        {
            A = A.Trim();
        }
    }
}

**Expected Behavior**:
Nullability warning on A.Trim() for de-referencing a null value as A is definitely null at that point in the code.

**Actual Behavior**:
No nullability warnings, but it does generate an unused parameter 'a' since the code should have been "A = a.Trim();"

**Comment by jaredpar** [comment]
This behavior is "By Design". The property is typed to be non-nullable hence it is correctly not reporting a warning when reading the property value here.
