### ISSUE TITLE
Feature Request: Add initialise in constructor refactoring

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#35568]
Would it be possible to add a refactoring to initilise a field or an autoproperty in a constructor?

When selecting a field or a autoproperty, which is not set in any location, this refactoring should appear.

It should add to every constructor a parameter of the same type as the field/property, and set the field from this parameter.

If no constructor exists, it should create a default constructor, and do this.

For example:

```csharp
//before:
public class Class
{
    int [|x|]; //lightbulb suggestion: initialise x in constructor
    public Class(){}
}

//after:
public class Class
{
    int x;
    public Class(int x)
    {
        this.x = x;
    }
}
```

Resharper has this code fix, and I find it invaluable.

**Comment by CyrusNajmabadi** [comment]
We already have this feature.  However, it requires *selecting* the entire field/property.  There's an open request to just make this work when your cursor is just on a single field/prop.  I'd be happy to help you update the feature to support that case

**Comment by YairHalberstadt** [comment]
@cyrusNajmabadi
Thanks - had no idea. Is there any way to see a list of all refactorings/code fixes and how to find them?
I'll look into updating the feature.

**Comment by jinujoseph** [comment]
Duplicate of #23271
