### ISSUE TITLE
ExtractMethod isn't offered if you use shift+down to select the lines to extract

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3557]
Watch this video:
![noextractmethod](https://cloud.githubusercontent.com/assets/3316258/8198794/7e93fcae-1460-11e5-8efc-cea3dd44fe5b.gif)

My natural instinct is to use `shift+down` to select a region of text. Then I want to hit ctrl+dot to extract it out into a method.

Unfortunately this doesn't work -- because after doing `shift+down` my cursor is left on the line *after* the selection, which is apparently outside the span that offers an ExtractMethod refactoring? or some other reason?

As a workaround, I can use `shift+up` to select the text (which I find really unnatural). Or I could use the mouse. But I'd much rather stick to keyboard.

Please let this work!

**Comment by Pilchie** [comment]
That gif looks terrible, except that I can't repro it on the latest builds.  Can you give a newer build a try and see if you still can?

**Comment by ljw1004** [comment]
Seems to be working on a newer build.
