### ISSUE TITLE
Unneeded value assignment according to default constructor: Editorconfig rule and codefix

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#35589]
[Original feedback from developer community](https://developercommunity.visualstudio.com/idea/536246/对editorconfig-的-net-编码约定设置增加默认值规则.html?childToView=559774#comment-559774)

**Summary:**
Today we have a fix to 'Remove redundant assignment'. This request is for a similar code analysis offering that would indicate (and offer a codefix to remove) an unneeded value assignment if the value assigned is the same as what is assigned by the default constructor. This rule should be included in our editorconfig rules.

```csharp
public class Class3
{
    public int A { get; set; } = 0;
}
public class Class2
{
    void M()
    {
        var test = new Class3 { A = 0 };
    }
}
```

**Comment by CyrusNajmabadi** [comment]
> an unneeded value assignment if the value assigned is the same as what is assigned by the default constructor

This is likely to be very niche as only constants could be determined.

**Comment by sharwell** [comment]
In my experience, this is quite a common scenario.

**Comment by Varorbc** [comment]
> > an unneeded value assignment if the value assigned is the same as what is assigned by the default constructor
> 
@kendrahavens I mean, the default value of `int` is 0, and there are two unneeded value assignment. One is attribute assignment value, the other is constructor assignment value, not what you understand

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
