### ISSUE TITLE
Unknown software exception when filtering nameof candidate list

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#35582]
**Version Used**: VisualStudio.16.Preview/16.1.0-pre.2.0+28822.285

**Steps to Reproduce**:
```C#
namespace Test16Bugs
{
    public class Program
    {
        private int _pointsPCA;
        public int PointsPcaEllipses { get; }

        static void Main()
        {
            M(nameof(|
        }
        static void M(params string[] s) { }
    }
}
```
(note that automatic brace completion is off)
1. Type `PCA` in capital letters. Note that the property is not listed in the candidate list:
![image](https://user-images.githubusercontent.com/10546952/57379542-66390200-71a7-11e9-89e4-5969ad1a2e0d.png)
2. Press `Alt+P` to filter the candidate list for properties.

**Expected Behavior**:
1. I would argue the property should be in the list as a case insensitive match.
2. Either way, if the list filter is not available, either pass they key to the VS (current behaviour when not crashing) or discard it (less annoying).

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/10546952/57379332-03e00180-71a7-11e9-942f-6aa867002c14.png)

**Comment by svick** [comment]
I can't reproduce the exception in a new console application on VS 16.1.0 preview 2.0. But I also don't see the two types in the candidate list. (Though adding the necessary `using`s for them doesn't change the behavior.) Do you have any other `using`s? Can you reproduce the exception by exactly following the steps you outlined?

**Comment by miloush** [comment]
The usings do not matter, I can reproduce it without any when only the field is present in the list. I created a clean .NET Framework 4.8 console app and still can repro, every time. Anything else to check?

VisualStudio.16.Preview/16.1.0-pre.3.0+28902.138

**Comment by CyrusNajmabadi** [comment]
Can't repro this either.

**Comment by miloush** [comment]
Cannot repro on VisualStudio.17.IntPreview/17.5.0-pre.1.0+33027.381.main
