### ISSUE TITLE
Properties with mixed readonly accessors should skip escape checks where possible

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#35606]
Related to #35146 and #35597

In some cases involving mixed readonly/non-readonly properties and indexers, we should be able to tell that passing a ref-like variable to a readonly member will not allow that variable to escape, but we're currently pessimistic and require that all accessors be 'readonly' in order to decide the variable won't escape.

```cs
using System;

public ref struct S
{
    int this[Span<byte> span] { readonly get => 0; set {} }

    static void M(S s)
    {
        Span<byte> span = stackalloc byte[10];
        // We know 'span' won't escape because the getter is readonly
        // but we still give an error today.
        _ = s[span];
    }
}
```

**Comment by RikkiGibson** [comment]
@tannergooding are you aware of any use cases that require this fix?

**Comment by tannergooding** [comment]
I'm not sure of any use-cases requiring this today. @JeremyKuhne might have some use-cases for some of the scenarios he's been working on though.

I do think this is an odd hole in the language and it would probably be good to be able to distinguish this case both now and for any potential future language features dealing with `ref` "ownership" semantics.
