### ISSUE TITLE
Referencing Microsoft.CodeAnalysis.Scripting NuGet package should bring in System.Runtime.Loader.dll

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#35607]
VSMac is referencing Microsoft.CodeAnalysis.EditorFeatures NuGet package, which in turn brings in Microsoft.CodeAnalysis.Scripting.dll which references System.Runtime.Loader.dll. 

However the Loader.dll isn't being restored or copied to output.

https://github.com/dotnet/roslyn/blob/fd70a2aa33961bfe92afaecb68a1f15827b8b15b/src/Scripting/Core/Microsoft.CodeAnalysis.Scripting.csproj#L24-L30

For now it doesn't look like we use the codepaths that would result in runtime failures, but it would be nice to fix this properly.

**Comment by KirillOsenkov** [comment]
@tmat

**Comment by tmat** [comment]
That's by design. System.Runtime.Loader.dll is Core CLR only and is dynamically loaded only on Core CLR.

**Comment by tmat** [comment]
@KirillOsenkov OK to close this issue?
