### ISSUE TITLE
remove workaround once https://github.com/dotnet/roslyn/issues/35514 is fixed

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#35615]
remove SolutionCrawlerRegistrationService.EnsureRegistration once the issue (https://github.com/dotnet/roslyn/issues/35514) is fixed.

**Comment by CyrusNajmabadi** [comment]
@heejaechang can this now be removed?  The linked issue you mentioned has been closed.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Solution crawler is going away.
