### ISSUE TITLE
[loc][Query][Roslyn] Localizability of "ref_local_or_expression" 

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#35624]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
ref local or expression

File Name:
Features\CSharp\Portable\xlf\CSharpFeaturesResources.xlf

==========================================
Query:
What does "local" mean here?

**Comment by jcouv** [comment]
"local" means "local variable".

For example, `x` is a local and `y` is a ref local in:
```C#
class C
{
  void M()
  {
    string x = "";
    ref string y = x;
  }
}
```

**Comment by PDostalek** [comment]
Thanks for explanation
