### ISSUE TITLE
Missing Nullable warnings?

### ISSUE THREAD

**Issue by tndata** [dotnet/roslyn#35628]
**Version Used**: 

.NET Core 3, Preview 5, Visual Studio 2019 16.0.3

**Steps to Reproduce**:

In the following code, the last two lines in the method does not get any warnings about nullability

`
```
public class Test
{
    public void DoStuff(string? input)
    {
        string data = input;
        Console.WriteLine(data.Length);

        Console.WriteLine(input.Trim());

        string data2 = input;                 //No warning CS8602: Possible dereference of a null reference here?
        Console.WriteLine(data2.Length);      //and here?

    }
}
````

**Expected Behavior**:

Expected to get 6 warnings in this method, I only get 4 warnings.

**Actual Behavior**:

The last two lines does not get any null warnings.

**Comment by tndata** [comment]
Actually, expected 5 warnings, but got only 3. (not 6 and 4)

**Comment by jcouv** [comment]
Looking at [sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWAChKBiAOwFcAbRiYRufOW19y7AZkIAmfABU4sSgG9K+OYUHYALPgAiAewDKMegDNdACmK4A/PgCWtAA70YASlnyZFea8JECKCDAj4AvBbWtuQubnLEAJwGXj4AdAAyXADmMAAWdiGOYZEGljYwsaII5mAGdhmUWW7G+DEQIgF5wWEtrgD0bQBy6vgA7hAItJZJ+ADCmgAcAGy4QiD4AArqUFDmbBwoiHC6W7QAxhzquvi+DMz4CNu7B/ipWyZVrjl1QgnJaRlhHRC0KLf3lVCcgAvpRgUA===) repro, there's a warning on `input.Trim()`.
If `input` is indeed `null`, then execution will not reach the last two lines, so there is no warning for possibly null `input` in those two lines.

This is the current design. The dereference in `input.Trim()` means that we treat `input` as non-null afterwards.
