### ISSUE TITLE
Type of invalid invocation expression returns a type parameter instead of some kind of error

### ISSUE THREAD

**Issue by ymassad** [dotnet/roslyn#35626]
**Version Used**: 

Microsoft.CodeAnalysis 3.0.0

**Steps to Reproduce**:

1. Use the following code:

```
    var syntaxTree = CSharpSyntaxTree.ParseText(@"
    public static class Class1
    {
        public static TResult Do<TResult>(this TResult param1, int param2) => param1;

        public static void Test()
        {
            var result1 = 
                1.Do(param2: 2);

            var result2 =
                result1.Do(param3: 3);
        }
    }
    ");
            CSharpCompilation compilation = CSharpCompilation.Create(
                "assemblyName",
                new[] { syntaxTree },
                new[]
                {
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
                },
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            var semanticModel = compilation.GetSemanticModel(syntaxTree);

            var invocations = syntaxTree.GetRoot()
                .DescendantNodes()
                .OfType<MethodDeclarationSyntax>()
                .Where(x => x.Identifier.Text == "Test")
                .SelectMany(x => x.DescendantNodes().OfType<InvocationExpressionSyntax>())
                .Select(x =>new
                {
                    Type = semanticModel.GetTypeInfo(x).Type,
                    Line = x.GetLocation().GetLineSpan().EndLinePosition.Line
                })
                .ToList();

            foreach (var invocation in invocations)
            {
                Console.WriteLine(invocation.Line + ":" + invocation.Type);
            }
```

2. 
3. 

**Expected Behavior**:

The type of the following expression:

```
result1.Do(param3: 3)
```

Should be null. Or there should be a way to know that there is something wrong with this expression since there is no overload of Do that takes a parameter called param3.

**Actual Behavior**:

The type of the expression above is returned as TResult, the type parameter.

Note: the same is true for the following expression:

```
1.Do(param2: 2).Do(param3: 3)
```

That is, without the intermediate variable.

This behavior might be intentional. In this case, what API can I use to know that the type of the expression is actually invalid?

**Comment by jcouv** [comment]
If you check the symbol for the invocation (ie. what method is this?), the compiler gives a `null` Symbol and an appropriate reason for not finding one (ie. overload resolution failure):

```C#
        [Fact]
        public void Test()
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(@"
    public static class Class1
    {
        public static TResult Do<TResult>(this TResult param1, int param2) => param1;

        public static void Test()
        {
            var result1 = 
                1.Do(param2: 2);

            var result2 =
                result1.Do(param3: 3);
        }
    }
    ");
            CSharpCompilation compilation = CSharpCompilation.Create(
                "assemblyName",
                new[] { syntaxTree },
                new[]
                {
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
                },
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            var semanticModel = compilation.GetSemanticModel(syntaxTree);

            var secondInvocation = syntaxTree.GetRoot().DescendantNodes().OfType<InvocationExpressionSyntax>().Last();
            Assert.Equal("result1.Do(param3: 3)", secondInvocation.ToString());

            var info = semanticModel.GetSymbolInfo(secondInvocation);
            Assert.Null(info.Symbol);
            Assert.Equal(CandidateReason.OverloadResolutionFailure, info.CandidateReason);
        }
```

That said, I have to say it is a little bit surprising the `GetTypeInfo` returns an actual type (rather than an error type). That's probably better for the IDE experience, but maybe somewhat misleading from an API perspective.

I assume that

**Comment by ymassad** [comment]
@jcouv , thank you for the workaround you suggested.

However, it is not always the case that I have access to the invocation expression.

For example, I might have a local variable and if I try to get its type, I will receive TResult instead of an explicit invalid type.

What might be useful is having the TypeInfo type have a boolean property indicating if this type is invalid (assuming that the current behavior is intentional).

**Comment by CyrusNajmabadi** [comment]
> What might be useful is having the TypeInfo type have a boolean property indicating if this type is invalid 

It's often not possible to tell this.  Any sort of issue wiht the code could lead to any sort of cascading misunderstanding of what's going on.  As everything may have been affected by any sort of error recovery effectively every symbol/type/info would just have the bit set saying "yup, error recovery was invlved somewhere, so all information is suspect".  You can currently already determine that if teh Compilation has any errors anywhere, so the bit would be redundant.

**Comment by ymassad** [comment]
@CyrusNajmabadi , in the example above, the type of the `result1` variable clearly has no problems while the type of the `result2` variable has a problem.

I am in a situation where such information is important.

> It's often not possible to tell this.

Can you give an example where such information is not possible to obtain?

**Comment by CyrusNajmabadi** [comment]
> in the example above, the type of the result1 variable clearly has no problems

It has no problems from *your* perspective.  It's likely your intuition is "would the current compiler report an error somewhere under this call".  If that's your intuition, then the best way to realize that is to use the GetDiagnostics api and use the span of the node you care about.  If there are no diagnostics, then this is a good proxy for what you think of as "has no problems".  If there are diagnostics, you can do whatever you want accordingly.

**Comment by ymassad** [comment]
@CyrusNajmabadi ,
> "would the current compiler report an error somewhere under this call"

I am not sure I understand this. Can you elaborate?

**Comment by CyrusNajmabadi** [comment]
@ymassad You can use the `SemanticModel.GetDiagnostics(span)` api to ask "are there any errors under this span".  You can use thsi to answer your question "is something wrong with this expression".  Cheers!

**Comment by ymassad** [comment]
Thanks @CyrusNajmabadi . I will give this a try and see how it helps.

**Comment by CyrusNajmabadi** [comment]
Good luck!  gitter.im/dotnet/roslyn is also a good place for general questions on how to use Roslyn.

**Comment by CyrusNajmabadi** [comment]
> Here, the Method0(0, 1) expression has no errors (via GetDiagnostics), 

As i said, this is a weak proxy for what you're asking for.


> but clearly the type of the expression is invalid.

Why is it invalid? Because SomeUndefinedType doesn't exist?  You can check the return type if has the .TypeKind `Error`.

> Here, GetDiagnostics returns an error (CS1929) for Method2() but it has a valid type (Int32).

If you're simply trying to as "is this a real type, or an unbound type" you can check the .TypeKind of the ITypeSymbol you're looking at.

Note: as mentioned earlier, this is not the best forum for these questions.  I would recommend gitter.im/dotnet/roslyn

**Comment by ymassad** [comment]
@CyrusNajmabadi , I am not sure how TypeKind will help me. In any case, I have already worked on a solution that does different things in different cases. It works for the cases I have so far. There will always be an edge case that I forget to handle.

> Note: as mentioned earlier, this is not the best forum for these questions.

In this issue, I am trying to suggest a new feature for `TypeInfo`. That is, a flag indicating whether the type is valid.

**Comment by CyrusNajmabadi** [comment]
> In this issue, I am trying to suggest a new feature for TypeInfo. That is, a flag indicating whether the type is valid.

"whether the type is valid" is not a well defined concept.  If you want to know if the type is an error type, such a flag *already* exists.

> @CyrusNajmabadi , I am not sure how TypeKind will help me. In any case, I have already worked on a solution that does different things in different cases. It works for the cases I have so far. There will always be an edge case that I forget to handle.

And if the compiler adds a flag for you, it will only be for a subset of cases as well.  It's not clear ot me what your set of cases actually is, so it's not clear how the compiler would implement this.

Note: as mentioned earlier, **this is not the best forum for these questions**.  Please take further questions on how to best use the Roslyn APIs to gitter.im/dotnet/roslyn.  Absent a strict proposal (ideally with a PR) on how the APIs should work, this issue won't really go anywhere.

**Comment by gafter** [comment]
This is all working as designed.  You are welcome to continue asking questions here or on gitter.
