### ISSUE TITLE
AnalyzerDependencyChecker should take into account whether or not an assembly is signed

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#3562]
The `AnalyzerDependencyChecker` type tries to identify analyzer assemblies that have the same identity but different contents. It warns the user that only one of these assemblies will be loaded at runtime and as such analyzers may not work as expected.

While testing the fix for #2728, @mavasani discovered a hole in the conflict check: if two unsigned assemblies have the same name but different version numbers we will treat them as unconflicting assemblies, even though the CLR will in fact only load one of them. To fix this, we need to take into account whether or not an assembly is signed when looking for conflicts.

As part of this fix we need to consider the following scenarios:

Not signed, different versions
- A1.dll: A, Version=1.0.0, PublicKeyToken=null
- A2.dll: A, Version=1.0.1, PublicKeyToken=null

One signed, same version
- A1.dll: A, Version=1.0.0, PublicKeyToken=null
- A2.dll: A, Version=1.0.0, PublicKeyToken=abcd1234

One signed, different versions
- A1.dll: A, Version=1.0.0, PublicKeyToken=null
- A2.dll: A, Version=1.0.1, PublicKeyToken=abcd1234

Both signed, same version, different key
- A1.dll: A, Version=1.0.0, PublicKeyToken=abcd1234
- A2.dll: A, Version=1.0.0, PublicKeyToken=cdef3456

Also need to consider that in any of these scenarions the CLR behavior may vary depending on which assembly is loaded first.

**Comment by mavasani** [comment]
@tmeschter Thanks for opening the issue. Please re-assign this to me for verification once this has been fixed.

**Comment by heejaechang** [comment]
@tmeschter what should I look for?

**Comment by heejaechang** [comment]
ping. I am still not sure what i am supposed to do.

**Comment by heejaechang** [comment]
@tmeschter @mavasani ping?

**Comment by tmeschter** [comment]
@heejaechang @mavasani The update will need to occur in [AnalyzerDependencyChecker.FindConflictingAnalyzers](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/AnalyzerDependency/AnalyzerDependencyChecker.cs,db024e5e380975d6). Currently we group the analyzer assemblies by their assembly identity, and then within each group check that all the assemblies have the same MVID.

The problem is that the grouping is wrong. If we have two unsigned assemblies with the same name but different versions, e.g.:

 * A, Version=1.0.0, PublicKeyToken=null
 * A, Version=1.0.1, PublicKeyToken=null

then we will put them in different groups even though the runtime considers them to be the same assembly, and will only load one. So we will miss certain conflicts.

The fix is to write a better grouping function that more accurately reflects what the runtime does.

Note that I'm not sure what the runtime does in all the scenarios listed in the original comment. Some investigation will be required.

Does that help?

**Comment by heejaechang** [comment]
Yep! That clear’s a bit what I need to do!

Thank you Tom


-          heejae

**Comment by mavasani** [comment]
@heejaechang Did you end up doing further investigations for this? Can you post your findings here?

**Comment by heejaechang** [comment]
sorry, I haven't.

**Comment by mavasani** [comment]
Closing this out for now - we can investigate if we receive customer feedback about this.
