### ISSUE TITLE
[QUESTION]Roslyn name pattern constants

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/roslyn#35630]
Someone could tell me where is the cs with roslyn constants for generation of name for lambda, async/await state machine etc.

I'm working on coverlet and would like to try some pattern recognition.

**Comment by svick** [comment]
If I understand the question correctly, then I believe the code you're looking for is in [`Microsoft.CodeAnalysis.CSharp.Symbols.GeneratedNames`](https://github.com/dotnet/roslyn/blob/1fcbc51/src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs).

Specifically, I think the name for the method generated for a lambda comes from `MakeLambdaMethodName` and the name for the `async`-`await` state machine is generated by `MakeStateMachineTypeName`.

**Comment by MarcoRossignoli** [comment]
Oh right there thank's!
