### ISSUE TITLE
AddParensForClarity should consider `switch` expressions like `await e switch ...`

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#35636]
(Filed from a note from @jcouv, he can answer questions about it.)

**Comment by jcouv** [comment]
Relates to recent precedence change for parsing `switch` expressions. See details at https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-03-13.md#precedence-of-the-switch-expression

**Comment by jcouv** [comment]
Moving to backlog milestone

**Comment by CyrusNajmabadi** [comment]
Haven't heard any feedback on this.  Closing out as the current behavior seems fine.
