### ISSUE TITLE
Suggestion: Offer fix for upgrading project to Core 3

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#35643]
In a project that targets Core 2, start using the default interface members feature.

You first get an error for the language version. We offer a fix for that.
Then you get an error for the target runtime. We could offer a fix for that too, or at least improve the error message.

![image](https://user-images.githubusercontent.com/12466233/57558728-be9d0a80-7333-11e9-84a6-b7fbc6b15eec.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
