### ISSUE TITLE
`this` keyword should not be recommended within a static local function

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#35644]
![image](https://user-images.githubusercontent.com/12466233/57559770-5a307a00-7338-11e9-88a4-91745f45ce1a.png)

**Comment by YairHalberstadt** [comment]
This will have to wait on https://github.com/dotnet/roslyn/issues/27719 I think, since IsStaticLocalFunction is internal.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/35822
