### ISSUE TITLE
Create and initialize property/field for all unused constructor parameters

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#35665]
This would save me some time regularly. Currently the best alternative I know of is to manually place the caret on each parameter and do Ctrl+., enter on each one. Sometimes there are three or four, other times there are more than ten.

ReSharper has the menu hierarchy 'Introduce get-only auto-property Foo' > 'For all unused parameters'.

**Comment by jinujoseph** [comment]
related to #30523

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/42684
