### ISSUE TITLE
Refactor the PerfRunManager and related utilities into smaller pieces

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#3567]
The PerfRunManager has more evolved over the years than been designed. As such, it's become a pretty big ball of mud that encompasses a lot of unrelated functionality. Refactoring it would help people who want to make targeted changes to perf tests and is probably necessary for putting pieces into the open for public use.

**Comment by davkean** [comment]
This doesn't seem relevant anymore given what we are doing in the perf space (moving to a different model). I'll close it for now, please reopen if you disagree.
