### ISSUE TITLE
Code navigation is broken in Peek window

### ISSUE THREAD

**Issue by jods4** [dotnet/roslyn#35694]
**Version Used**: VS 2019

**Steps to Reproduce**:

1. Open a solution.
2. Use Alt-F12 to peek the definition of a symbol found in another file.
3. Try to use code navigation on symbols in peek window. For example: Shift-F12 (find all references) or F12 (go to definition).

**Expected Behavior**: References are found.

**Actual Behavior**: No references found if the file has not been opened before.
![image](https://user-images.githubusercontent.com/3832820/57692124-4772b980-7646-11e9-97fb-9029acd6aa25.png)

**Important note**: if you have the file opened in a normal tab, it works as expected. Proof:
![image](https://user-images.githubusercontent.com/3832820/57692269-a89a8d00-7646-11e9-8ded-47c1c02f1ef8.png)

Then:
![image](https://user-images.githubusercontent.com/3832820/57692420-04fdac80-7647-11e9-9e97-bf26a6295229.png)

**Comment by vatsalyaagrawal** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/918643

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
