### ISSUE TITLE
KeywordCompletionProvider does not consider CultureInfo.CurrentUICulture

### ISSUE THREAD

**Issue by HSyr** [dotnet/roslyn#35705]
Under Czech Windows 10 I do `CultureInfo.CurrentUICulture = new CultureInfo( "en-US" )`. When  I then call `CompletionService.GetDescriptionAsync` I got different language results (Czech or English) depending on the type of the language element.

- For method `Console.Beep` it returns expected English result _"+1 overload"_ (provider is `Microsoft.CodeAnalysis.CSharp.Completion.Providers.SymbolCompletionProvider`)

- But for C# keyword `while` it returns Czech result _"klíčové slovo"_ instead of expected English _"keyword"_ (provider is `Microsoft.CodeAnalysis.CSharp.Completion.Providers.KeywordCompletionProvider`)

Version: Microsoft.CodeAnalysis.Analyzers version 2.9.2

**Comment by CyrusNajmabadi** [comment]
All we do is `string.Format(FeaturesResources._0_Keyword, keyword)` which seems like it shoudl be the right thing to do (since we don't specify cultures anywhere else when doing string.Format for our resource strings).  

@sharwell do you know if there's anything to do here?
