### ISSUE TITLE
Document Outline is empty

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35708]
When opening the Document Outline it shows _"There are no items to show for the selected document"_. This was in Roslyn codebase on `AbstractMoveToNamespaceCodeAction.cs`.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/565055/document-outline-is-empty.html
VSTS ticketId: 891693_

_These are the original issue comments:_

Andrew Hall 🤘 [MSFT] on 5/10/2019, 05:59 PM: <p>I'm not sure what the document outline is supposed to show. You can find the source used at <a target='_blank' href="https://github.com/dotnet/roslyn/blob/master//src/Features/Core/Portable/MoveToNamespace/AbstractMoveToNamespaceCodeAction.cs">https://github.com/dotnet/roslyn/blob/master//src/Features/Core/Portable/MoveToNamespace/AbstractMoveToNamespaceCodeAction.cs</a></p>

Visual Studio Feedback System on 5/13/2019, 00:49 AM: <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by paulrahme** [comment]
An issue from the Developer Community forum has been closed and redirected here:
[https://developercommunity.visualstudio.com/content/problem/805639/document-outline-is-blank-1.html](url)

Apparently it was made for Winforms/WPF, and has not been implemented for C# files.

Hopefully it gets C# support soon. This is one of the things I miss the most having recently moved from the Mac version of VS (which was based on Xamarin / MonoDevelop) to Windows.

**Comment by sharwell** [comment]
This issue is a subset of experience requested in #36812.

**Comment by mikadumont** [comment]
Proposal: 

`Document Outline` should not be empty when selecting a C# file and have the file structure view: 

![image](https://user-images.githubusercontent.com/46729679/95274487-d6afdc80-07fa-11eb-9915-d52e3aff6bcb.png)

![image](https://user-images.githubusercontent.com/46729679/95274451-be3fc200-07fa-11eb-89a8-98e61ee8ddcb.png)

**Comment by jmarolf** [comment]
Implemented in PR https://github.com/dotnet/roslyn/pull/61784

**Comment by CyrusNajmabadi** [comment]
This was added.

**Comment by bizos** [comment]
I got the same thing, the Docoument Outline window is empty. My Version is 17.4.4

**Comment by payoff** [comment]
Version 17.4.4 with R#
Document Outline is empty, R# File structure displays correct output  

![image](https://user-images.githubusercontent.com/142235/221426668-5e3c4a82-b5fc-4fad-b210-73336aed1de5.png)

**Comment by avdynut** [comment]
Document Outline is empty for C#. Version 17.6.0 Preview 1.0

**Comment by sharwell** [comment]
This was removed due to performance issues. The feature is still present and will return in an upcoming release.

**Comment by BobSammers** [comment]
I was sorry to see this disappear and have only just realised that it was deliberately removed. +1 for "please return this feature," but also +1 for "please put it back as is, marked 'experimental' until it's fixed properly." I wasn't seeing any obvious performance downside, but I'm definitely experiencing the downside of not having it at all.

I appreciate (depending on what was happening) that this may not be sensible, but on my experience, I'm happy to use it as it was.

(As an aside, please make the sort selection stickier when it gets redeveloped.)
