### ISSUE TITLE
Codelens problems when mixing .NET standard with .NET FX

### ISSUE THREAD

**Issue by dchrno** [dotnet/roslyn#35728]
**Visual Studio Version**:
Visual Studio Professional 2019 version 16.0.4

**Summary:**
When a .NET FX 4.7.2 project implements an interface defined in a .NET standard assembly, codelens doesn't show usage for implemented members.

An example solution which reproduces the problem is attached to this issue.

**Steps to Reproduce**:

1. 
Create 3 projects (see attached zip-file)
a. NET 4.7.2 library 'LibraryFX'
b. NET Standard 2.0 library 'LibraryStd'
c. NET 4.7.2 console application 'TestApp'

2. 
Define two identical interfaces in LibraryStd and LibraryFX (IClassStd and IClass FX):

in LibraryFx

    public interface IClassFX
    {
        void Method1();
    }

in LibraryStd

    public interface IClassStd
    {
        void Method1();
    }

3. 
In TestApp, reference the libraries and create a file Impl.cs implementing both interfaces.

    public class ClassStd : IClassStd
    {
        public void Method1() { }
    }
    public class ClassFX : IClassFX
    {
        public void Method1() { }
    }

4.
In Main, create instances of the classes and access the method through their interfaces:

        IClassFX fx = new ClassFX();
        fx.Method1();
        IClassStd std = new ClassStd();
        std.Method1();

5.
Open Impl.cs and inspect the codelens information.

**Expected Behavior**:
Codelens should show "2 references" for the methods in both ClassStd and ClassFX.

**Actual Behavior**:
Codelens shows 0 references for Method1 in ClassStd, and 2 references for Method1 in ClassFX.

If you use explicit interface implementation, codelens correctly shows 2 references:

    public class ClassStd : IClassStd
    {
        void IClassStd.Method1() { }
    }

**User Impact**:
Tracking down usage in larger solutions is hard, relying on using search instead of codelens.
[CodelensProblem.zip](https://github.com/dotnet/project-system/files/3176934/CodelensProblem.zip)

**Comment by davkean** [comment]
Thanks for the report - I've moved this over to Roslyn whom own this feature.

**Comment by huoyaoyuan** [comment]
This also applies for UWP projects.

**Comment by dchrno** [comment]
I'm not permitted to edit labels on my issue, but I assume it should be labeled Bug and IDE-IntelliSense.

**Comment by heejaechang** [comment]
it doesn't repro with latest 16.2stg

![image](https://user-images.githubusercontent.com/1333179/60059661-3f288800-96a2-11e9-8df4-bb659a4df7be.png)

image is from attached zip solution as it is.
