### ISSUE TITLE
Invalid color of an interpolated string parameter of the http URL.

### ISSUE THREAD

**Issue by HSyr** [dotnet/roslyn#35721]
The whole interpolated string including the parameter looks like a link and CTRL + click even follows it. I would expect `{param}` is not displayed as a link and has a different color.

![param](https://user-images.githubusercontent.com/34036102/57769514-663c8300-770e-11e9-803b-a0f555cec120.png)
Version: Visual Studio Community 16.0.4

**Comment by jinujoseph** [comment]
Duplicae of #5863
