### ISSUE TITLE
Parsing VB with SourceCodeKind.Interactive doesn't accept top-level expressions

### ISSUE THREAD

**Issue by albahari** [dotnet/roslyn#3573]
The following evaluates to `{ (1) : error BC30035: Syntax error. }`

``` csharp
VisualBasicSyntaxTree.ParseText ("\"Hello, world\"", new VisualBasicParseOptions (kind:SourceCodeKind.Interactive)).GetDiagnostics()
```

The equivalent with CSharpSyntaxTree works without error.

**Comment by AdamSpeight2008** [comment]
@albahari  The maybe because that isn't how escape the double quotation marks in VB.net.

**Comment by mattwar** [comment]
I believe that VB currently requires a leading "?", just like in the debugger immediate window.

**Comment by albahari** [comment]
You're right, thanks Matt
