### ISSUE TITLE
VB Compiler throws NullReferenceException with non-strict char comparison:

### ISSUE THREAD

**Issue by albahari** [dotnet/roslyn#3574]
The following query causes the VB compiler to crash with a NullReferenceException when calling Emit:
 
Dim query =
      From c In "test"
      Where c <> "t"

**Comment by AdamSpeight2008** [comment]
What do mean by calling `Emit`?

As straight up code in `Visual Basic 2015 RC   00269-30000-00001-AA369` in doesn't crash.

**Comment by albahari** [comment]
I've retested with the current roslyn-master and there's no crash.
