### ISSUE TITLE
Start early work on WebAssembly compilation target

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#3575]
I know it is still in early stage, but could you please make sure that *direct* C# compilation is supported as soon as possible? It would be beneficial if Roslyn team could feed their requirements into the design group very early. I am sure Google will be vocal about Go and Dart.

https://github.com/WebAssembly/design/blob/master/FAQ.md#is-webassembly-only-for-cc-programmers

https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#gcdom-integration

> Beyond the MVP, another high-level goal is to improve support for languages other than C/C++. This includes allowing WebAssembly code to allocate and access garbage-collected (JS, DOM, Web API) objects. Even before GC support is added to WebAssembly, it is possible to compile a language's VM to WebAssembly (assuming it's written in portable C/C++) and this has already been demonstrated (1, 2, 3). However, "compile the VM" strategies increase the size of distributed code, lose browser devtools integration, can have cross-language cycle-collection problems and miss optimizations that require integration with the browser.

It is possible that the C# language design could be affected as well:

https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#coroutines

> Coroutines will eventually be part of C++ and is already popular in other programming languages that WebAssembly will support.

**Comment by JoshVarty** [comment]
(Knowing nothing about WebAssembly) I wonder if it would make more sense to go from IL to WebAssembly? Then you'd get support for VB and F# for free.

**Comment by dsaf** [comment]
@JoshVarty 

Perhaps, but is there a repository for that? Even if there is, I would still submit a request here because Roslyn team:

0) is responsible for the most important .NET language;
1) actually listens to people's needs;
2) considers every request - often giving feedback.

Besides they have a direct input into CLRs future #420.

**Comment by Romoku** [comment]
+1 @JoshVarty

@dsaf From my limited understanding I think the issue will be making [CoreCLR](https://github.com/dotnet/coreclr) compilable to WebAssembly or wait for LLVM to support WebAssembly and use [LLILC](https://github.com/dotnet/llilc).

**Comment by gafter** [comment]
@dsaf The appropriate repo to request this would probably be https://github.com/dotnet/llilc . Please open your issue there.

I think the issue in that context could possibly be titled "Could you folks please hurry up?". :wink:
