### ISSUE TITLE
IDE0060 shown on unimplemented methods

### ISSUE THREAD

**Issue by JranZu** [dotnet/roslyn#35768]
Starting with VS 2019 I am seeing IDE0060 for methods that contain only new NotImplementedException().  These place holder methods should not show this message.

**Comment by CyrusNajmabadi** [comment]
I'm not sure why this woudl be the case.  Even if it's a placeholder method, it's still valid to give this message.

**Comment by sharwell** [comment]
Design review conclusion: identifying methods like this that ended up never getting used is one of the primary values of this analyzer. The described behavior is what we would expect.
