### ISSUE TITLE
Invalid IL generated for stackalloc assigned to Span

### ISSUE THREAD

**Issue by jkotas** [dotnet/roslyn#35764]
3.2.0-beta1-19253-08

**Steps to Reproduce**:

1. Compile System.Private.CoreLib

**Expected Behavior**:

Valid IL generated for `Environment.GetEnvironmentVariableCore` method

**Actual Behavior**:

Invalid IL generated for `Environment.GetEnvironmentVariableCore` method

The ECMA spec requires that IL stack is empty, apart from the size item, for localloc instruction.

Details in https://github.com/dotnet/coreclr/pull/24369#issuecomment-493130547

**Comment by jkotas** [comment]
This blocks upgrading CoreCLR repo to latest Roslyn.

cc @jaredpar

**Comment by tannergooding** [comment]
As per https://github.com/dotnet/coreclr/pull/24369#issuecomment-493134203, this does not look to happen for `release` mode and only occurs for `debug` mode.

This looks related to the `nested-stackalloc` feature as that was merged in the relevant time window (https://github.com/dotnet/roslyn/pull/35385) and it repros for that feature branch on sharplab (which was last snapped on April 30th).

CC. @gafter

**Comment by gafter** [comment]
Repro [shown HERE](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDsUwgE1cmKAYwGsoAbcgeyIBoYQBLc2nEAagB8ABABgAJuARgDcAWABQ3AMyCATPwDC/AN6T+G/gAcEjAG6wIgoQDZBAFn4BxCDACi6PYwRV0AWwjoYANSi6owOQQilRIABTCAgb+gRAAlOqaahKaqfwAylpQ6AA8RAAWfgB8/MBwYJAI/AC8/ATEZJQ0/AV+ANpCcgAcALoi/AD0A/xQdVQeAO6FMPxIUMiuAUH8OBBgUHDkM8iMAF4QiRoAvpJHQA) in sharplab; here is the code which breaks in Debug:
``` c#
using System;
public class C {
    private static void GetEnvironmentVariableCore(string variable)
    {
        Span<char> buffer = stackalloc char[128]; // a somewhat reasonable default size
    }
}
```
which generates
``` none
.class private auto ansi '<Module>'
{
} // end of class <Module>

.class public auto ansi beforefieldinit C
    extends [mscorlib]System.Object
{
    // Methods
    .method private hidebysig static 
        void GetEnvironmentVariableCore (
            string variable
        ) cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 24 (0x18)
        .maxstack 3
        .locals init (
            [0] valuetype [System.Memory]System.Span`1<char>,
            [1] valuetype [System.Memory]System.Span`1<char>
        )

        IL_0000: nop
        IL_0001: ldloca.s 1
        IL_0003: ldc.i4 256
        IL_0008: conv.u
        IL_0009: localloc
        IL_000b: ldc.i4 128
        IL_0010: call instance void valuetype [System.Memory]System.Span`1<char>::.ctor(void*, int32)
        IL_0015: ldloc.1
        IL_0016: stloc.0
        IL_0017: ret
    } // end of method C::GetEnvironmentVariableCore

    .method public hidebysig specialname rtspecialname 
        instance void .ctor () cil managed 
    {
        // Method begins at RVA 0x2074
        // Code size 8 (0x8)
        .maxstack 8

        IL_0000: ldarg.0
        IL_0001: call instance void [mscorlib]System.Object::.ctor()
        IL_0006: nop
        IL_0007: ret
    } // end of method C::.ctor

} // end of class C
```

**Comment by gafter** [comment]
Fix in PR at https://github.com/dotnet/roslyn/pull/35780
