### ISSUE TITLE
Inconsistent naming of With* and Replace* methods

### ISSUE THREAD

**Issue by robinsedlaczek** [dotnet/roslyn#3576]
Names and semantics of Replace* and With* methods of the .NET  Compiler Platform APIs are inconsistent and misleading when talking to developers. Let me give some examples:

            Microsoft.CodeAnalysis.SyntaxNode node;

Here I have some Replace*-methods. Fine so far.

            node.ReplaceNode(...)
            node.ReplaceNodes(...)
            node.ReplaceSyntax(...)
            node.ReplaceToken(...)
            node.ReplaceTokens(...)
            node.ReplaceTrivia(...)

Here we have some With* -methods that replaces elements. 
I would not expect a replacing action in a With* -method. 'With' means to add something.
This method should be named as a Replace* -method, too.

            // Creates a new node from this node with the leading trivia replaced.
            node.WithLeadingTrivia(...)

            // Creates a new node from this node with the trailing trivia replaced.
            node.WithTrailingTrivia(...)

Here we have some Without* -methods. Fine so far as well. 

            node.WithoutAnnotations(...)
            node.WithoutLeadingTrivia(...)
            node.WithoutTrailingTrivia(...)
            node.WithoutTrivia(...)

But why do these methods are Remove* -methods? 
I would expect them as Without* -methods. Or the Without* -methods above should be named as Remove* -methods. I would prefer Remove* -methods to reduce confusion when looking for those methods with IntelliSense. With* and Without* -methods are mixed up in the IntelliSense list. So there is a risk to take the wrong method.

            node.RemoveNode(...)
            node.RemoveNodes(...)

Next inconsistency I was wondering about is in the Document class. When implementing a refactoring I have to respin the complete tree. So at the end when updating the document, I have to replace the root node of the syntax tree in the document. Again, the method I have to use is called WithSyntaxRoot.
I would expect that this method is called something like "ReplaceSyntaxRoot" because With* -method should add something.

            Microsoft.CodeAnalysis.Document document;

            // Creates a new instance of this document updated to have a syntax tree rooted by the specified syntax node.
            document.WithSyntaxRoot(...)

**Comment by Pilchie** [comment]
@mattwar  can you explain the rationale behind the naming here?

**Comment by AdamSpeight2008** [comment]
My thought around the naming are

`Remove` / `Replace` affects a Syntax node and changes the shape of the tree.
`With` / `Without` relate to trivia, not changing the overall shape of the tree.

**Comment by sharwell** [comment]
My observations:

* `With` generally affects the current node.
* `Replace` affects some child of the current node, which is provided in the call.

**Comment by mattwar** [comment]
The general naming pattern for updating/changing a single property of a immutable object is the WithXXX pattern. This is both familiar to users of functional programming languages and a good indication to those unfamiliar to the immutable pattern that the API returns a new instance. However, when it came to naming patterns for collection element manipulation there was not a good pattern to follow, so we kept the existing mutable pattern names; Add, Remove, Replace, Insert, etc.  When adding the API's to manipulate tree descendants, this fit closer to the collection operations than the property ones, so Replace, Insert and Remove were used.
