### ISSUE TITLE
Generate all overrides for Object when generating new class

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#35771]
`ToString`, `Equals`, and `GetHashCode`

Either a quick action, or setting to have these generated with `add class`

**Comment by CyrusNajmabadi** [comment]
note: this is already very easy to accomplish:

![image](https://user-images.githubusercontent.com/4564579/57889590-103d0d80-77ea-11e9-9cb8-6205e5eaeeb1.png)

![image](https://user-images.githubusercontent.com/4564579/57889596-1632ee80-77ea-11e9-9fe0-e0913ed71ffe.png)

You basically only need a tiny handful of keystrokes to do this.  I'd far prefer this being the way for peple to ask for this versus them having to delete the generated code they don't want.

It's also not clear to me that doing this at 'add class' time makes sense.  The class has no state then (and will likely change in the future).  So all the generate code isn't likely to be correct.

**Comment by CyrusNajmabadi** [comment]
Closing out as the scenario is covered more flexibly than in the OP.
