### ISSUE TITLE
Make all multiline statements collapsible

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#35792]
I noticed that this statement is collapsible in the editor:
```C#
var multiline = string.Join("\r\n", new string[] {
                       "Class Test",
                        "     Dim x As Integer",
                        "     Dim Y As Integer",
                        "End Class"});
```

While this is not:
```C#
var multiline = string.Join("\r\n", 
                       "Class Test",
                        "     Dim x As Integer",
                        "     Dim Y As Integer",
                        "End Class");
```

I think any multiline statement (in VB and C#) should be collapsible, whether or not it contains `{}`.

**Comment by jinujoseph** [comment]
**Design Meeting Notes** 
Today you can make any selection and do Edit - > Outline -> Hide selection Ctrl+H Ctrl+M 
We are afraid that by making everything collapsible, it will add too many noises to the UI.

**Comment by CyrusNajmabadi** [comment]
Closing out as per design review conclusion.  There are ample nesting locations offered in the IDE already, and we haven't heard about this from any other sources.  This will likely make things too noisy.
