### ISSUE TITLE
DIM interface overrides report being "sealed".

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#35795]
Our symbol model reports that DIM overrides are "sealed", though the sealed modifier is forbidden.  The symbol model should reflect the language point of view, and the "sealed" modifier does not seem apropos.  From the metadata viewpoint, however, sealed is appropriate, so it would be fine to have `MetadataSealed` true (if there is such a thing).

The reason the method cannot be overridden is that it cannot be named, as it does not introduce a member according to the language specification. In the symbol model, its symbol is one that cannot be named.  Neither of these is the same as being "sealed".

(LDM previously decided that "sealed" isn't permitted because it doesn't make sense for an interface override)

**Comment by AlekseyTs** [comment]
> Our symbol model reports that DIM overrides are "sealed"

This is not the case.
