### ISSUE TITLE
The color of VS2019 is so light, can I use VS2017 style in VS2019?

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#35799]
ScrollBar in Diff window:
![image](https://user-images.githubusercontent.com/2529999/57968219-2689cb80-799a-11e9-9f73-4263fadb3984.png)

![image](https://user-images.githubusercontent.com/2529999/57968231-36091480-799a-11e9-9614-79cced2e567a.png)

Hightlight color in ContextMenu:
![image](https://user-images.githubusercontent.com/2529999/57968140-4967b000-7999-11e9-9c5d-84d39ec7ce15.png)

![image](https://user-images.githubusercontent.com/2529999/57968151-68fed880-7999-11e9-8e85-98733010c062.png)

**Comment by jinujoseph** [comment]
cc @olegtk

**Comment by olegtk** [comment]
route it to the editor, thanks!
