### ISSUE TITLE
Update RenameTrackingDiagnosticAnalyzer to run out-of-process

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#35808]
Currently `RenameTrackingDiagnosticAnalyzer` depends on data stored on `ITextBuffer` instances which is not not available out-of-process. This analyzer will cease to work in its current form when the analyzer infrastructure is moved out-of-process. The analyzer should be updated to remove the in-process dependency, or the analyzer for this feature should be replaced with an alternative implementation that does not rely on analyzers.

**Comment by heejaechang** [comment]
RenameTrackingDiagnosticAnalyzer could be converted to DocumentDiagnosticAnalyzer

**Comment by sharwell** [comment]
That's a great idea @heejaechang
