### ISSUE TITLE
Add using refactoring should take AddImportPlacement setting into account

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/roslyn#35803]
**Version Used**: 
VS2019 16.1 Preview 3

**Steps to Reproduce**:

1. Create empty c# project
2. Add .editorconfig file with "csharp_using_directive_placement = inside_namespace : error"
3. Use 'Add using' refactoring in any c# file without any using directives.

**Expected Behavior**:
Refactoring should add using directive inside namespace. 
If document already has any using directives - it should be added based on existing position (current behavior).

**Actual Behavior**:
Using directive is added outside namespace.

![2019-05-19_21-23-47](https://user-images.githubusercontent.com/17177729/57986379-cfa8f280-7a7c-11e9-9956-965220a695c0.gif)

**Comment by CyrusNajmabadi** [comment]
Not repro for me.  I get it in the right location:

![image](https://user-images.githubusercontent.com/4564579/218173107-f05032f6-9897-4ca5-9f9d-bff9e40bdd86.png)
