### ISSUE TITLE
Add code fix for calling base constructor with missing arguments

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#35805]
I would like a code fix "Add parameter Foo to constructor" in the following situation:

```csharp
abstract class Base
{
    protected Base(Foo foo) {}
}

class Derived : Base
{
    public Derived(Bar bar) {} //cs7036: There is no argument that corresponds to the required formal parameter 'Foo' of 'Base.Base(Foo)'
}
```

The result of the code fix should be:

```csharp
abstract class Base
{
    protected Base(Foo foo) {}
}

class Derived : Base
{
    public Derived(Bar bar, Foo foo) : base(foo) {} 
}
```

It should also be offered if the base constructor is explicitly called, but with missing arguments.

I will be happy to implement this myself, once I am done with the PR I am currently working on.

**Comment by CyrusNajmabadi** [comment]
Closing out for lack of feedback.
