### ISSUE TITLE
C# Code Styles should honor the C# Language Level setting in the Solution explorer

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35807]
VSF_TYPE_MARKDOWN
​We have some legacy projects (.net 4.5/C#5) where we are using VS 2019.  
To keep the text editor from recommending using later features that are not supported in C# 5, we have set the language level to target the correct version.

This works in the text editor however the solution explorer doesn't seem to also honor the setting.

See the 2 screen shots to see what I mean.

Repro 
1. Create a .net Framework 4.5/C# 5.0 project
2. Set the target language to be C# 5.0
3. Write an if statement using the `as` keyword (or any other code that would trigger a c# 7 code styles recommendation)

Expected Result
1. *BOTH* visual studio and the solution explorer should *NOT* recommend the IDE0019 change

Actual Result
1. Solution explorer shows the recommendation as blue squiggly lines.

(I hate poorly written bug reports, hope this give you enough info).

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/569720/c-code-styles-should-honor-the-c-language-level-se.html
VSTS ticketId: 893249_
_These are the original issue comments:_

Visual Studio Feedback System on 5/16/2019, 02:35 AM (4 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 5/19/2019, 02:37 AM (30 hours ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
Solution Explorer does not show squiggles. It appears the external extension used for showing squiggles in Solution Explorer is not updating correctly.
