### ISSUE TITLE
Return value of lambda expressions not resolved in overloaded generics

### ISSUE THREAD

**Issue by fin-ger** [dotnet/roslyn#3581]
I recently worked on a project under mono and did some experimenting with generics. It compiles fine with the mono compiler. When I tried to compile it under Windows with VisualStudio 2013 and .NET 4.6 as target platform the compiler gives me error CS0121.

The compiler is unable to resolve that `stack.Push` returns type `void` and not `bool`!

This is the source code:

```c#
using System;
using System.Collections.Generic;

namespace GenericFail
{
    class GenericFail
    {
        static void Main(string[] args)
        {
            Stack<int> s = new Stack<int>();
            List <int> l = new List <int>(new[] { 1, 2, 3 });
            l.Test(s.Push); // error CS0121
        }
    }

    public static class Extensions
    {
        public static void Test<TSource>(this IEnumerable<TSource> source, Action<TSource> predicate)
        {
            foreach (var s in source)
                predicate(s);
        }

        public static void Test<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)
        {
            foreach (var s in source)
                if (!predicate(s))
                    break;
        }
    }
}
```

**Comment by VSadov** [comment]
I think this is by design. The return type is inferred after the overload resolution and compiler cannot chose between Func and Action.

@AlekseyTs - can you confirm that this is correct or whether there is no some subtle rule that might make this work?

**Comment by AlekseyTs** [comment]
I cannot see an obvious reason for the failure, debugging might give some clues.

**Comment by VSadov** [comment]
CC @MadsTorgersen @gafter    what do you think spec says about this case?
VB seems to be able to resolve similar situation, but this could be a part where languages differ.

**Comment by gafter** [comment]
The convertibility of a method (group) to a delegate type does not take into consideration the return type of the method.

> ### 6.6 Method group conversions

> An implicit conversion (§6.1) exists from a method group (§7.1) to a compatible delegate type. Given a delegate type D and an expression E that is classified as a method group, an implicit conversion exists from E to D if E contains at least one method that is applicable in its normal form (§7.5.3.1) to an argument list constructed by use of the parameter types and modifiers of D, as described in the following.

> The compile-time application of a conversion from a method group E to a delegate type D is described in the following. Note that the existence of an implicit conversion from E to D does not guarantee that the compile-time application of the conversion will succeed without error.

Since the conversion exists and neither of these two methods is more specific, the program contains an ambiguity error. See also #250 for a proposal to "fix" this in the language.

**Comment by CnSimonChan** [comment]
> #### 7.5.3.2 Better function member
> Given an argument list **A** with a set of argument expressions { **E<sub>1</sub>**, **E<sub>2</sub>**, ..., **E<sub>N</sub>** } and two applicable function members **M<sub>P</sub>** and **M<sub>Q</sub>** with parameter types { **P<sub>1</sub>**, **P<sub>2</sub>**, ..., **P<sub>N</sub>** } and { **Q<sub>1</sub>**, **Q<sub>2</sub>**, ..., **Q<sub>N</sub>** }, **M<sub>P</sub>** is defined to be a better function member than **M<sub>Q<sub>** if
> * for at least one argument, the conversion from **E<sub>X</sub>** to **P<sub>X</sub>** is better than the conversion from **E<sub>X</sub>** to **Q<sub>X</sub>**.

Do you think a `compile-time error` is better than a `successfully compile`?
