### ISSUE TITLE
Automated Code Snippets

### ISSUE THREAD

**Issue by dsteketee** [dotnet/roslyn#35811]
Rather than creating code snippets, Visual Studio should be able to prescribe sensible methods to get from Object A to Object B. For example, I have an object, but it's not the right type to send to a particular method. I usually end up googling for samples and they're pretty easy to find, but I suspect some clever tidbits built into the IDE could improve on this approach. There are lots of other common things I encounter regularly like when creating an object with a nullable integer value, there are pretty standard ways to handle that in the code so you don't end up with exceptions. Think of all the time saved if the IDE were smart enough to help developers avoid null reference exception errors by proposing well written code.

**Comment by jinujoseph** [comment]
@dsteketee thanks for the feedback.
Would you pls share a specific idea or example that will benefit with the antomation
