### ISSUE TITLE
Make IRecursivePatternOperation public

### ISSUE THREAD

**Issue by ionoy** [dotnet/roslyn#35843]
**Version Used**: 
3.0.0

**Description**
Right now, there is no way to analyze the operation behind the pattern matching code like this: `a is (var b, var c)`  without using Reflection. Please make `IRecursivePatternOperation` interface public.

**Comment by jinujoseph** [comment]
cc @AlekseyTs @mavasani

**Comment by AlekseyTs** [comment]
CC @jaredpar, @gafter
