### ISSUE TITLE
Rename of generic class does not update error references without type arguments

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#3584]
Split from internal work item 1188436.

Consider updating the error-code reference `Test` (without type arguments) while renaming `Test<T>` in the following code:

``` C#
class C : Test { }
class Test<T> { }
```

**Comment by Vlad5Maxed** [comment]
To my it looks like that:
I typed class C : Test
then I decided to go to definition of class Test to check if I implemented something in it.
While I was in that class I decided that its name not reflect what it does so I decided to rename it.

I think if go to definition works and it actually jumps to definition then Rename should rename it.

**Comment by Pilchie** [comment]
At the moment, rename is pretty strict about things not being in `CandidateSymbols` and IIRC there were some email conversations between myself, @DustinCampbell, and another dev who used to work on rename about what sort of problems we got into when we included places where things were in `CandidateSymbols`. Will try to dig that up.

**Comment by DustinCampbell** [comment]
Having Rename include anything that GTD can jump to doesn't work in practice. GTD tries to be permissive in error cases. For example, it will jump to inaccessible symbols (like private methods) if no better choice exists. Rename needs to be quite a bit more rigorous to create trustworthy results. For example, imagine you started a rename and saw that one reference in another file would be updated. You trust rename to do the right thing and go ahead and commit it, only to find later that it renamed something that didn't quite match and broke your program.

**Comment by Vlad5Maxed** [comment]
Hi Dustin.

You are right. Results should trustworthy. 
The problem that for user it feels like bug. Of course you can try to add some smartness to rename like find how many different Tests but I think price of mistake is very high. So I think better to leave it as is.

**Comment by Pilchie** [comment]
I do think there are some cases where we should be more lenient in error cases, but we should probably evaluate them on a case by case basis.

**Comment by Pilchie** [comment]
In this case, I think it would be find to match - possibly if there is a single item in `CandidateSymbols` and the `CandidateReason` is `WrongArity` or `OverloadResolutionFailure` is a decent heuristic to start with.

**Comment by DustinCampbell** [comment]
Why not just augment the Include Overloads option to work for generic types?

**Comment by CyrusNajmabadi** [comment]
I dn't see anything here that really makes me feel that updating the behavior here would actually be desirable.  i.e. just as often as not it seems like it would be a bad decision.  As such, defaulting to conservative behavior in the presence of this sort of error feels reasonable.

**Comment by sharwell** [comment]
@CyrusNajmabadi Reopening to bring to design review with a proposed resolution of **By Design**.

**Comment by CyrusNajmabadi** [comment]
Design review conclusion is that this behavior is acceptable.
