### ISSUE TITLE
Can't build latest roslyn

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#35849]
This is hte latest master.  I've pulled and restored things.  But if i try to build, i get:

```
5>C:\Program Files\dotnet\sdk\3.0.100-preview4-010963\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(136,5): error MSB4044: The "GenerateDepsFile" task was not given a value for the required parameter "CompileReferences".
```

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski @sharwell @dotnet/roslyn-infrastructure

**Comment by jasonmalinowski** [comment]
After restore, try killing all "msbuild" processes.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski Thanks.  That worked.  Is there some way this could happen automatically during a restore?

**Comment by jasonmalinowski** [comment]
Well, we should actually fix the bug. But at this point @nguerrera can speak better. :-)

**Comment by nguerrera** [comment]
https://github.com/dotnet/sdk/issues/2953

I think arcade made this easier to fix recently

**Comment by jasonmalinowski** [comment]
Yeah, @tmat added support for that I believe.

**Comment by CyrusNajmabadi** [comment]
Thanks all!  feel free to close out if you think this is known and already being handled by other work :)
