### ISSUE TITLE
Find All Associated Types context menu option for namespaces in C# files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35858]
<p>Within Visual Studio (all versions), occasionally I want to see how a namespace is being used within a file. Refactoring hints tell me when a namespace isn't being used so that I can remove it, but that doesn't help me if I want to see how a namespace is already being used. This information is necessary to allow me to make decisions to do the following:</p><ol><li>Replace the using statement for a full namespace with a using alias directive when I'm only using one or two types within that namespace.</li> <li>Remove a namespace entirely by replacing uses of it with something else (if, for example, I want to remove all uses of Linq in a project/file).</li></ol> <p>To facilitate this, it would be very helpful if Visual Studio provided a context sensitive menu option for namespaces in C# files that allows me to identify any type used within that file that is dependent on the using statement. That new capability, combined with the existing Find All References implementation for namespaces, will allow developers to manage their namespace usage properly in their C# projects.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/560270/find-all-associated-types-context-menu-option-for.html
VSTS ticketId: 888714_
_These are the original issue comments:_

Jane Wu [MSFT] on 5/8/2019, 02:46 AM (13 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
