### ISSUE TITLE
Refactor the code handling different TextDocument kinds in the IDE layers

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#35863]
We now have 3 distinct text document kinds: Document (regular source document), AdditionalDocument (additional files) and AnalyzerConfigDocument (editorconfig files). We have large number of places in the IDE layer where each client has to deal with all the 3 different document kinds, also leading to lot of code duplication. This issue tracks refactoring the code so that we have a central service/shim that handles all different document kinds and exposes APIs such that the client does not need to handle each document kind.

See following comments for some ideas on this work:
1. https://github.com/dotnet/roslyn/pull/35691/commits/4c0459a25a556db891b467ed713e53415374095b#r284291020
2. https://github.com/dotnet/roslyn/pull/35762/files#r286224367, https://github.com/dotnet/roslyn/pull/35762/files#r286224882
3. https://github.com/dotnet/roslyn/pull/35762/files#r286232360
4. https://github.com/dotnet/roslyn/pull/35762/files#r286227148
5. https://github.com/dotnet/roslyn/pull/35762/files#r286228639
6. https://github.com/dotnet/roslyn/pull/35762/files#r286235383
7. https://github.com/dotnet/roslyn/pull/35762/files#r286236054
8. https://github.com/dotnet/roslyn/pull/35762/files#r286239878

**Comment by mavasani** [comment]
Tagging @jasonmalinowski @heejaechang @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
