### ISSUE TITLE
Audit the differences in TextDocument handling between different document kinds in the IDE layer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#35862]
This issue tracks auditing all our IDE code base where we have different implementation for either of the following document kinds: Document, AdditionalDocument and AnalyzerConfigDocument.

For example, see the following comments:
1. https://github.com/dotnet/roslyn/pull/35762/files#r286255564

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
