### ISSUE TITLE
Add Convert anonymous type to class refactoring for VB

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35861]
<p>This refactoring exists for C#, please add it to VB too.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/562754/add-convert-anonymous-type-to-class-refactoring-fo.html
VSTS ticketId: 889997_
_These are the original issue comments:_

Jane Wu [MSFT] on 5/9/2019, 03:20 AM (12 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
This feature exists:

![image](https://user-images.githubusercontent.com/4564579/58146262-327bc480-7c0a-11e9-8a17-7d6140f28bee.png)

![image](https://user-images.githubusercontent.com/4564579/58146298-3d365980-7c0a-11e9-9980-40c3c3314a4a.png)

**Comment by JensSamsonPirsol** [comment]
What if a LINQ query produces an anonymous type like this :

DIM Q = from anItem in Items
               select anItem.Property1, anItem.Property2

This declares an IQueryable of an anonymous type but there is no New keyword.

Or what if it produces a ValueTuple like this ?

DIM Q = from anItem in Items
               select (anItem.Property1, anItem.Property2)

**Comment by CyrusNajmabadi** [comment]
> Or what if it produces a ValueTuple like this ?
>
> ```vb
> DIM Q = from anItem in Items
> select (anItem.Property1, anItem.Property2)
> ```

This case is supported.

**Comment by CyrusNajmabadi** [comment]
> What if a LINQ query produces an anonymous type like this :
>
> DIM Q = from anItem in Items
> select anItem.Property1, anItem.Property2

This case is not (neither in C# nor VB).  Taking to design meeting to qualify this as "won't fix".  There's a simple approach.  Just write an anonymous type there and ask to convert it to a class.

**Comment by CyrusNajmabadi** [comment]
Closing out.  Workaround is sufficient.
