### ISSUE TITLE
Should not have select part of a field to generate constructor

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#35875]
I always forget what I have to do to generate a constructor from a field. 

I'm not allowed to generate a constructor from the field with the following:

![image](https://user-images.githubusercontent.com/1103906/58165874-00cb3200-7ccc-11e9-91fe-2dbc86ab6ab9.png)
![image](https://user-images.githubusercontent.com/1103906/58165830-e42efa00-7ccb-11e9-9007-8a29264d2a79.png)
![image](https://user-images.githubusercontent.com/1103906/58165852-f315ac80-7ccb-11e9-89f9-68f19dec1465.png)

But I am if I do the following:
![image](https://user-images.githubusercontent.com/1103906/58165933-16405c00-7ccc-11e9-9793-3c9566ab82d1.png)
![image](https://user-images.githubusercontent.com/1103906/58166197-a383b080-7ccc-11e9-8e32-563dc6f9500b.png)

Why can I do some things to fields by having the cursor before, in or after the field, but I cannot generate a constructor from it?

**Comment by jinujoseph** [comment]
related to #33601 , #28774

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/42173
