### ISSUE TITLE
Inline temporary variable refactoring produces invalid code for while loop

### ISSUE THREAD

**Issue by prjm** [dotnet/roslyn#35887]
**Version Used**:  Visual Studio Community Edition 2019, 16.1.0
**Steps to Reproduce**:

1.  Create a sample application
2. Add this source code (with a matching namespace):

```c#
namespace ConsoleApp4
{
    internal class Program
    {
        private static string CalculateSomething()
            => "a";

        private static void Main(string[] args)
        {
            var d = default(string);
            do
            {
                d = CalculateSomething();
            } while (d != default);
        }
    }
}
```

3. move the cursor to `var d = ...`
4. open the quick actions menu / lightbulb-symbol
5. select _Inline temporary variable_

**Expected Behavior**:

6. refactoring is not provided because `d` can't be inlined 

**Actual Behavior**:

6. refactoring is provided, marked with `Conflicts detected`, produces the following code:

```c#
            var d = default(string);
            do
            {
                d = CalculateSomething();
            } while (default(string) != default);
```

**Comment by prjm** [comment]
I'm not sure about the expected behavior here - is it possible to detected such situations? One way to inline  `d` in this example could be:

```c#
            do
            {            
            } while (CalculateSomething() != default);
```

But this only works if  `d` isn't used later in the loop body.  What makes `d`  a _temporary_ variable here?

**Comment by CyrusNajmabadi** [comment]
This is by design.  

> refactoring is not provided because d can't be inlined

Our preference is for the refactoring to be avialable, but to tell the user there will be an issue (which is what you noticed the actual behavior is0.

> What makes d a temporary variable here?

It's a local that's being initialized.  All 'inline temp' does it replace viable usages of the local with the initialization code.

**Comment by prjm** [comment]
OK I understand this and the issue can be closed. 

I think I was just confused by the name of the refactoring because I would not classify this variable as temporary..
