### ISSUE TITLE
Deleting empty lines causes the cursor to indent

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35883]
VSF_TYPE_MARKDOWNIn Visual Studio 2019, if I have multiple emptly lines of code, I put my cursor on the first line to delete. Pressing the delete key deletes the following line, but also indents the cursor. If I keep pressing delete, the cursor moves more, up to 10 times.  This did not happen in Visual Studio 2015.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/560744/deleting-empty-lines-causes-the-cursor-to-indent.html
VSTS ticketId: 888905_
_These are the original issue comments:_

Visual Studio Feedback System on 5/8/2019, 02:48 AM (14 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me at all.  Closing out.
