### ISSUE TITLE
Reduce the impact of nullable attributes in metadata

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#35888]
The current approach for representing nullable annotations in [metadata](https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-reference-types.md#annotations) can result in a significant number of attributes.

Consider alternatives to reduce the number of attributes.

**Comment by jcouv** [comment]
Also, the current encoding stores a byte even for types that cannot carry annotations. We could probably skip those types while visiting the nested types.
On the other hand, this would be a breaking binary change from the previews...

**Comment by cston** [comment]
There were three separate changes:
1. Add option to emit nullable metadata for public members only https://github.com/dotnet/roslyn/pull/36398
2. Do not include value types in NullableAttribute byte[] https://github.com/dotnet/roslyn/pull/36519
3. Replace most-common NullableAttributes with new NullableContextAttributes at the containing methods and types https://github.com/dotnet/roslyn/pull/36152

**Comment by ufcpp** [comment]
version used: Visual Studio 16.3 Preview 2 (the same result in 16.3 Preview 1)

![image](https://user-images.githubusercontent.com/3760955/62988528-b3500280-be7f-11e9-9b72-e0c9efdfcb74.png)

Is this `Nullable(0)` attribute on class `A` intentional? What does it effect?

**Comment by cston** [comment]
@ufcpp, the `[Nullable(0)]` attribute on `A` represents the annotations for the base class. The attribute value might be a value other than `0` if the base class is a constructed type.

**Comment by ufcpp** [comment]
Make sense. Thanks.

```cs
class Box<T> { public T Value = default!; }

// Nullable(0) (omitted)
class A : Box<int> { }

// Nullable(0, 1)
class B : Box<string> { }

// Nullable(0, 2)
class C : Box<string?> { }
```
