### ISSUE TITLE
Microsoft.CodeAnalysis.EditorFeatures.Wpf NuGet package needs to declare a dependency on Microsoft.VisualStudio.InteractiveWindow

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#35897]
**Version Used**: 
3.1.0-beta4-19261-04

The NuGet package https://www.nuget.org/packages/microsoft.codeanalysis.editorfeatures.wpf contains Microsoft.CodeAnalysis.EditorFeatures.Wpf.dll which reference Microsoft.VisualStudio.InteractiveWindow.dll 2.0.0.0.

However the NuGet package doesn't declare this dependency. The NuGet package needs to declare an explicit dependency on https://www.nuget.org/packages/microsoft.visualstudio.interactivewindow

**Comment by KirillOsenkov** [comment]
Also need to declare a reference to `Microsoft.CodeAnalysis.InteractiveHost, Version=3.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35`

Right now it's unclear how to acquire Microsoft.CodeAnalysis.InteractiveHost and from where.

@tmat @jinujoseph

**Comment by jinujoseph** [comment]
cc @JoeRobich
