### ISSUE TITLE
Go To Definition on anonymous type goes to wrong definition

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#3589]
(I've had a habit of reporting bugs you've already fixed, but I searched and didn't find this one)

Consider the following:

``` CSharp


public class MyClass
{
    public string Prop1 { get; set; }
}
class Program
{
    static void Main(string[] args)
    {
        var instance = new MyClass();

        var x = new
        {
            instance.Prop1 //<- Press F12 on Prop1
        };
    }
}
```

In Visual Studio 2013 pressing F12 on `instance.Prop1` would take you to `MyClass.Prop1`.

In Visual Studio 2015 RC 2 the cursor jumps to the end of `instance.Prop1`

**Comment by Pilchie** [comment]
Ah yes.  The problem here is that `Prop1` in that location is *both* a reference to `MyClass.Prop1` *and* the definition of the `Prop1` property on the anonymous type.

In VS2013, we gave preference to the reference, but now we don't.  This also affects Find All References and Rename IIRC.

**Comment by dpoeschl** [comment]
SymbolFinder.FindSymbolAtPosition currently returns the definition, and it would be a breaking functional change to switch to the reference. Maybe we need another entry with a ```bool preferReference``` argument, or an analogous ```FindSymbolsAtPosition``` API.

**Comment by dpoeschl** [comment]
Have something working here for GTD, but need to tests FAR & Rename as well.

**Comment by CyrusNajmabadi** [comment]
I think what's more appropriate is to possibly change SymbolFinder to be more like "FindSymbol*s*AtPosition".  i.e. recognize that we can get multiple symbols at a single location.
