### ISSUE TITLE
Warning given when the nullability of a method signature is non-nullable but the delegate expects nullable

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#35896]
The following code currently warns:
```csharp
using System;

#nullable enable

public delegate void ContextCallback(object? state);

public class C {
    // warning CS8622: Nullability of reference types in type of parameter 'state' of 'void C.WaitOrTimerCallback_Context_t(object state)' doesn't match the target delegate 'ContextCallback'.
    private static readonly ContextCallback _ccbt = new ContextCallback(WaitOrTimerCallback_Context_t);
    
    private static void WaitOrTimerCallback_Context_t(object state) { }
}
```

I would expect no warning since the method signature does not allow nullable inputs which still fits with the requirements of the delegate signature.

I would expect a warning in the opposite case (a method whose parameter is nullable is passed to a delegate with a matching signature but where the corresponding parameter is non-nullable).

**Comment by tannergooding** [comment]
CC. @cston

**Comment by RikkiGibson** [comment]
I'd guess that this is by design. If you convert the `WaitOrTimerCallback_Context_t` method to `ContextCallback` then pass it off to someone, they can call it with `null`.

**Comment by cston** [comment]
Agreed, this is by design, thanks.

A method with an `object?` parameter could be used for a delegate with an `object` parameter though.
