### ISSUE TITLE
Attribute-typed Identifier Renaming Issue

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35894]
When pressing Ctrl+R+R to rename a Attribute-typed Identifier will end up an additional 'Attribute' word inserted into the new identifier.

For example, when i rename an attribute called 'ExampleAttribute' to 'InstanceAttribute' by replacing 'Example' with 'Instance', i will get 'InstanceAttributeAttribute'.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/550414/attribute-typed-identifier-renaming-issue.html
VSTS ticketId: 857934_
_These are the original issue comments:_

Visual Studio Feedback System on 4/29/2019, 01:23 AM (23 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by vatsalyaagrawal** [comment]
Reproducible in 15.9.12

Repro: Try renaming "ExampleAttribute" to "abcAttribute" using 'Ctrl r r'
`namespace BugTriageApp {
    class Class1 {
        [ExampleAttribute]
        void abc()
        {
            i = j;
        }
    }
    internal class ExampleAttribute : Attribute
    {
    }
}`

Expected behavior: Attribute renames to "abcAttribute"

Actual behavior: Attributes renames to "abcAttributeAttribute"

**Comment by vatsalyaagrawal** [comment]
This has been fixed in 16.1.0 release. Closing the issue.
