### ISSUE TITLE
'CS8602: Dereference of a possibly null reference' if it's a struct property, but not if it's a class property

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#35898]
**Version Used**: VS 16.1

**Steps to Reproduce**:

Compile the following program with nullable reference types enabled

```C#
namespace ConsoleApp13
{
    class Program
    {
        static void Main(string[] args)
        {
            var s = default(S);
            // 2nd 's.Prop': warning CS8602: Dereference of a possibly null reference.
            if (s.Prop != null && s.Prop.Trim().Length == 0) { }

            var c = new C();
            // 2nd 'c.Prop': no warning
            if (c.Prop != null && c.Prop.Trim().Length == 0) { }
        }
    }

    struct S
    {
        public string? Prop => string.Empty;
    }

    sealed class C
    {
        public string? Prop => string.Empty;
    }
}
```

**Expected Behavior**:

No warnings

**Actual Behavior**:

Warnings if it's a struct, but not if it's a class.

**Comment by canton7** [comment]
Can't reproduce on master (22 May 2019) ([SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABABgAJiBGAbgFgAoAYk3QBs2Jg25y5MuPRsQBMlKgHZGAb0bl54gGyUALOQCyEAJaYAFNVIBtALrkICAOZQAlHIWyGCp+QBu58lHIBecjjgAzCHYYXQBla3pHZ3kAehjyEUwccgByKAA6AAUEAHsABxSQcgB3c0wdC3IAYVCADkVSESKAEUQAtswAY14c/zNyPJyoKC1uAE9yVg5yBHbZrrh0u2itPt0M7PzyAEIfKbZyADJDjyzcvPSAFQQtMF1rdIAZfgsYAAtvH1JrcmlyAF9GMtnG4EOROt5JnBitV7pForF4olkilOmd8oVJjkSmUKsCnKtyLo0Zs8js9uwDsdweiLtdbvcni93p9yN9fgDgYCGNzGLAMJ0YORQjJgcQAMziUgAfnIpO8AD4pekAKJgPIwMaRXkMKBwCA8ZKiaqiqLyCVS2XyrxKgyq9Wa7VAA===)), although selecting the "Default interface Methods" branch does produce it. I suspect this might have been fixed fairly recently?

**Comment by jcouv** [comment]
Yes, it looks like we've fixed this already.
Thanks for reporting.
I'll go ahead and close
