### ISSUE TITLE
C# Tuples - Tuple type is inferred as dynamic type in the caller when passing dynamic parameters to the callee

### ISSUE THREAD

**Issue by mirsaeedi** [dotnet/roslyn#35908]
**Version Used**: 7.3

**Steps to Reproduce**:

```C#
 class Program
    {
        static void Main(string[] args)
        {
            dynamic input = "";
            var val = Test(input);
            // val is dynamic here instead of (int X, int y). 
            // you cannot use val.X or val.Y
            // instead you should use val.Item1 or val.Item2
        }

        public static (int X, int y) Test(string x)
        {
            return (0, 0);
        }
    }
```
**Expected Behavior**:
We expect that _val_ be a tuple with strongly typed properties named X and Y, respectively.

**Actual Behavior**:
_val_ is inferred as a dynamic instance. Moreover, CLR cannot access _val_'s properties through X and Y instead we should use Item1 and Item2.

**Comment by svick** [comment]
This is the expected behavior: whenever a call is dynamic, its return type is considered to be `dynamic`. And you can't access tuple element names though `dynamic`.

**Comment by mirsaeedi** [comment]
@svick Thanks for your prompt reply. But here the call is not dynamic. In this example, we call the **_Test_** method which is known by the compiler. So, I believe no matter how we pass the input parameters to the method we should get the _**return type**_ that is defined by the **_Test_** method signature;

**Comment by svick** [comment]
> here the call is not dynamic

It is, any call whose argument is `dynamic` is dynamic. From [the spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#dynamic-binding):

> if an expression is a dynamic expression (i.e. has the type `dynamic`) this indicates that any binding that it participates in should be based on its run-time type (i.e. the actual type of the object it denotes at run-time) rather than the type it has at compile-time. The binding of such an operation is therefore deferred until the time where the operation is to be executed during the running of the program.

So the specification requires the use of dynamic binding here (which makes the return type `dynamic` as a consequence), even though in theory, the compiler could figure out which overload is called here (because there is only one).

**Comment by mirsaeedi** [comment]
@svick Thanks a lot for clarifying this matter :)
