### ISSUE TITLE
Customizing Code Fix previews

### ISSUE THREAD

**Issue by zoepetard** [dotnet/roslyn#3590]
We'd like the option to include additional help text to a Code Fix. For example, when several different Code Fixes are available to handle a particular diagnostic, it would be helpful to be able to explain to the user the difference between these Code Fixes, and provide reasons for choosing one Code Fix over the others.

Potential workarounds:
1.  Add the explanation to the error descriptions but that would describe all the fixes.
2.  Use WarningAnnotation - but that would add a yellow highlight to the node\token which might not look good.
3.  Implement a custom preview - but lose the code preview
4.  Have a comment that shows the text

**Comment by Pilchie** [comment]
@shyamnamboodiripad @srivatsn I know we talked about this before - did we come up with anything else?

**Comment by srivatsn** [comment]
Today we have three strings –
1.	the error message, 
2.	the error description which is a place where you can at length talk about why this is a problem and why it should be fixed an discuss alternate ways of fixing it. 
3.	The fix title.

We did talk about adding a fix description for symmetry reasons. However, we would then need to find a place to show that in the lightbulb UI that didn’t make the preview too long (potentially). The error description is shown in a collapsed region and we could append the fix description there maybe but it wouldn’t be discoverable. We could put it under the code preview but for the cases where there was just one fix, the fix description might not be much more than the title and would be redundant and just waste space.

So we decided to hold off on adding it until there were real scenarios that needed them. What we’ve found so far is that it’s the issue that’s hard to understand and the issue description could say fix it this way or that way and the title of the fix along with the code preview is generally sufficient to explain the fix.

**Comment by Hosch250** [comment]
I'm not a UI expert, but what if you had a drop-down that was closed by default just above the preview? Then, the user decides whether to make the preview box big enough to display both (or it could be display either/or, with the code change being displayed by default, like below).

![image](https://cloud.githubusercontent.com/assets/6299719/25603657/3d828e36-2ec3-11e7-8990-ca3958285f24.png)

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.   Closing out for now.  Note: i would be more hesitant about supplying functionality here as we will have to reconcile how htat would work for VS4Mac, and potentially vscode in teh future.
