### ISSUE TITLE
Codestyle: Require comments on specified members

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#35912]
[Original developer community](https://developercommunity.visualstudio.com/idea/551465/对editorconfig-的-net-编码约定设置增加注释规则.html?childToView=579424#comment-579424
)

> Add annotation rules to the .NET encoding convention settings of Editorconfig
> if a field, property, or method is missing a comment, vs can have suggestions, warnings, or incorrect configuration.

Example:
```
dotnet_style_require_comments.applicable_kinds = field, method, property
dotnet_style_require_comments = true:suggestion
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
