### ISSUE TITLE
CI failing with: update ExpectedDependency list: System.ValueTuple

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#35919]
See https://dev.azure.com/dnceng/public/_build/results?buildId=198851&view=logs&jobId=6a7d83c1-6850-57a3-ff09-22192451ed19 as an example.

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski @sharwell @dotnet/roslyn-infrastructure

**Comment by jasonmalinowski** [comment]
I believe @tmat fixed this?

**Comment by tmat** [comment]
Yes, it's fixed.
