### ISSUE TITLE
[C#] No intellisense on fall-through switch when the code block following is in curly braces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35922]
VSF_TYPE_MARKDOWN
```
enum Foo { Bar, Baz }

...

switch( Foo.Bar )
{
    case Foo.Bar:
    case <x>
    {
        break;
    }
}
```
When typing at location &lt;x&gt; there is no intellisense/auto-complete if the block following is wrapped in curly braces. Attempting to hint by typing _Foo._ also fails to trigger intellisense. If the curly braces are removed intellisense works as expected and shows members of the Foo enum.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/579118/c-no-intellisense-on-fall-through-switch-when-the.html
VSTS ticketId: 897321_
_These are the original issue comments:_

Visual Studio Feedback System on 5/23/2019, 01:59 AM (12 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by vatsalyaagrawal** [comment]
Reproduces on 16.1.0

**Comment by gafter** [comment]
I suspect this has something to do with the fact that the syntax is of a pattern, not a code block (until the colon appears).

**Comment by vatsalyaagrawal** [comment]
Works in VS2017.

**Comment by CyrusNajmabadi** [comment]
Doesn't repro for me:

![image](https://user-images.githubusercontent.com/4564579/218173584-abec2091-4d94-4d7b-beff-b940623ae929.png)
