### ISSUE TITLE
Analyzers and code fixes that require .NET Standard 2.1 features should be disabled in projects not targeting it

### ISSUE THREAD

**Issue by cremor** [dotnet/roslyn#35936]
**Version Used**: Shipped with Visual Studio 2019 16.1

**Steps to Reproduce**:

1. Create a new C# project that targets a framework that does **not** support .NET Standard 2.1 (e.g. any version of .NET Framework, .NET Core < 3.0, .NET Standard < 2.1).
2. Add `<LangVersion>preview</LangVersion>` to the .csproj file.
3. Make sure the C# code style analyzers "Prefer index operator" and "Prefer range operator" are enabled (this is the case by default).
Alternatively add an .editorconfig file with those settings:

``` ini
csharp_style_prefer_index_operator = true:suggestion
csharp_style_prefer_range_operator = true:suggestion
```

4. Add the following code:

``` cs
int[] numbers = { 1, 2 };
string text = "abc";
_ = numbers[numbers.Length - 1];
_ = text.Substring(1, text.Length - 1);
```
5. Check the error list and suggested code fixes in the last two lines of the code.

**Expected Behavior**:
No analyzer messages or code fixes that belong to analyzer messages should be shown.

**Actual Behavior**:
Analyzer messages "IDE0056 Indexing can be simplified" and "IDE0057 Substring can be simplified" are shown.
If you apply the provided code fixes, compile errors are produced because indexers and ranges are not supported in the target framework of the project.

Note: Right now those two analyzers/code fixes are the only ones I know of that show this problem. But of course this should be applied to all analyzers/code fixes that require features of a specific target framework.

**Comment by cremor** [comment]
I can't reproduce this any more in VS version 16.2.0. Is it fixed?

**Comment by JimBobSquarePants** [comment]
I really, really don't wanna be that person but "Is there any movement here"?

**Comment by sharwell** [comment]
😕 According to the following test and #36909, this was fixed for the 16.3 release.

https://github.com/dotnet/roslyn/blob/e78a4a6ee01500e27db35b97fad29da744cfb00a/src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseIndexOperatorTests.cs#L498-L518

**Comment by sharwell** [comment]
I just followed the steps from the top for both **netstandard2.0** and **netcoreapp2.0**, and was not able to reproduce the issue.

**Comment by JimBobSquarePants** [comment]
Hmmm... I’m definitely seeing range and index suggestions on multi-target libraries.

**Comment by sharwell** [comment]
> on multi-target libraries

Yes, this is the expected behavior. The analysis operates in the current context, so if you have a view open that supports these operations it will suggest them. The right fix is exactly what you did: disable the rules in **.editorconfig** since they do not apply for your project.

**Comment by JimBobSquarePants** [comment]
Ah ok, I wasn’t aware of that. That’s ok then thanks!

**Comment by mavasani** [comment]
Agree with @sharwell. This is by-design for all analyzer execution, not just this specific analyzer. @sharwell is this good to close?
