### ISSUE TITLE
ITypeSymbol Equality should ignore nullability

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#35933]
ITypeSymbol equality should only consider things that were available in C# 7.3 by default, and we need to expose a new set of equality comparers to allow for customization in how symbols are compared, including nested nullability.

**Comment by 333fred** [comment]
As part of this, we need to write an analyzer to validate our own usage, as well as consumer usage, of equality. See https://github.com/dotnet/roslyn-analyzers/issues/2493.

**Comment by AlekseyTs** [comment]
> ITypeSymbol equality should only consider things that were available in C# 7.3 by default

We should also consider if we would like to exclude Custom Modifiers by default even though they were included by default in 7.3. Custom modifiers are rare, that is why I think no one complained about their impact on equality, but from the language point of view their presence doesn't make any difference for type equivalence, etc.
