### ISSUE TITLE
Enable debugging/EnC integration tests

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#35965]
This PR disables integration tests: https://github.com/dotnet/roslyn/pull/34027, because it requires the <s>lab/16.2stg</s> 16.10 build with VS debugger insertion which won't be available on the CI machine.

Enable the tests again once the CI machine is upgraded.

Also uncomment `#if TODO` in `WaitForDesignMode`

**Comment by tmat** [comment]
@richaverma1 FYI

**Comment by sharwell** [comment]
Can you add a test that asserts the current version of Visual Studio is less than the version that adds this feature, with a comment that the tests should be enabled again when it starts failing?

**Comment by tmat** [comment]
I don't know what the version will be.

**Comment by CyrusNajmabadi** [comment]
Terrific!
