### ISSUE TITLE
'CS8629: Nullable value type may be null' reported when it can not be null

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#35978]
**Version Used**: VS 16.1

**Steps to Reproduce**:

1. Compile this code (C#8 + NRT)

```C#
using System;

#nullable enable
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            M(default((Guid g, string s)?));
            M(default((Guid g, string s)));
        }

        static void M((Guid g, string s)? t)
        {
            if (t?.g == Guid.Empty)
            {
                // 't': CS8629: Nullable value type may be null.
                _ = t.Value.s;
            }
        }
    }
}
```

**Expected Behavior**:

No warning

**Actual Behavior**:

Warning: CS8629: Nullable value type may be null.

**Comment by 0xd4d** [comment]
Similar example but with reference types

```C#
using System;

#nullable enable
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            M(null);
            M(new C());
        }

        static int M(C? c)
        {
            if (c?.S != string.Empty)
                return 0;
            // 'c': CS8602: Dereference of a possibly null reference.
            c.S.Trim();
            return 1;
        }
    }

    sealed class C
    {
        public string S = string.Empty;
    }
}
```

**Comment by jcouv** [comment]
This was fixed ([sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoUgYgDsBXDDCYDOAAjkoadPbDigAcIAYxYBhAPaUoYpgEE+fYiQDepZmub4NBAOyr1KkuqNaAbBoAszALIQ0lABQ4CABgDaAXWYQEAcygBKPWNmA2Dgq3sAEzgAMwhaGHt7AHFqNEjmHyQtZ2YAgH5/fwBuILC1COi4hKTU9Mzsp1yAotLDMIBfUjKjJzMcSwiUtIysnLz/fOYYQPbg0PL1NBjmexh8gDofZgBeHeY6yI2AUTA+GABPWcX9HpvmAHoH5gByGBeQZhEAZQAOEzwAE5PgA5Wj0RgsABuEAw1BYlz4LEgF2YwBYNDoGzuNwA+rtphsAGqw+EbKBte7MLpzYw0ow0jpAA===) for `Guid` example and [sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoUgYgDsBXDDCYDOAAjkoadPbDigAcIAYxYBhAPaUoYpgEE+fYiQDepZmub4NBAOyr1KkuqNaAbBoAszALIQ0lABQ4CABgDaAXWYQEAcygBKPWNmA2Dgq3saOn8AbiCwtQjKOAB3ZhF7f1j4owBfUhz1JzM7GGt7EQB+ZkFAwzDQhPU0ADNme0FKgDoAZWYAQgBeLWcugFEwPhgATzqmsJxtZmc4+vmAenXmAHJBbZB0noAOE2c8A4ARRDgW68phZjE2iGY+MSgoNEZp5iiMZgQNzuwi6hWCgl6XQAKgg0GBMqt5mpFswCIiwvk1sxMfEoHAIEwACYaPDpeKNYI4ADMI2YfWGTlGEym03RakxuSAA) for `string` example).

We're now able to draw better inferences (learn from) tests on conditional expressions.
I'll go ahead and close this issue as I think we now have good coverage for such scenarios.

Thanks!
