### ISSUE TITLE
"Go to implementation" throws AggregateException

### ISSUE THREAD

**Issue by phil-harmoniq** [dotnet/roslyn#35980]
**Version Used**: 
Unknown, pre-installed in the latest version of Visual Studio 2019 (16.1.1)

**Steps to Reproduce**:

1. Open up a solution containing a class implementing an interface.
2. Attempt to use "Go to implementation" on one of its methods.

**Expected Behavior**:
"Go to implementation" takes me to the implementation of a method.

**Actual Behavior**:
"An exception of type AggregateException has been encountered" is shown

Full exception log
[Activity Monitor Log_xml.txt](https://github.com/dotnet/roslyn/files/3220447/Activity.Monitor.Log_xml.txt)

The given error message suggests that this might be caused by an extension, but I have disabled all extensions and the same error continues to happen. The given exception suggests this is an issue with Roslyn.

**Comment by Nate0922** [comment]
Still happening in 16.1.4. 

===========================================

Microsoft Visual Studio Enterprise 2019
Version 16.1.4
VisualStudio.16.Release/16.1.4+29020.237
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Application Insights Tools for Visual Studio Package   9.1.00429.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.1.429.50124
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.1.429.50124
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.1.429.50124
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.1.429.50124
Azure Functions and Web Jobs Tools

C# Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20419.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Productivity Power Tools 2017/2019   16.0
Installs the individual extensions of Productivity Power Tools 2017/2019

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SonarLint for Visual Studio   4.10.0.9867
SonarLint is an extension to your favorite IDE that provides on-the-fly feedback to developers on new bugs and quality issues injected into their code.

SQL Server Data Tools   16.0.61904.23160
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10506.2004
TypeScript Tools for Microsoft Visual Studio

Viasfora   4.2.188
Add color to your Visual Studio editor!

Visual Basic Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.1.0-beta.19253.3+42526fe359672a05fd562dc16a91a43d0fe047a7
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

**Comment by CyrusNajmabadi** [comment]
Have not seen any prism hits for this.  If you are running into this, please supply a link to your project and where you did gotodef so we can try to repro.  thanks!
