### ISSUE TITLE
The new Intellisense does not omit Attribute suffixes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35990]
VSF_TYPE_MARKDOWNHi,

In VS 2019, after enabling &quot;Show items from unimported namespaces&quot; in the C# intellisense options, attribute names include the Attribute suffix.

See demonstration.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/584851/the-new-intellisense-does-not-omit-attribute-suffi.html
VSTS ticketId: 900293_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Dreamescaper** [comment]
Duplicate: #35540

**Comment by weitzhandler** [comment]
@vsfeedback, looks like this issue can be closed.
