### ISSUE TITLE
CS0306 when stackalloc is used in a nested context

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#36004]
**Version Used**: 
VS 2019 Preview, version 16.2.0 Preview 1.0

**Steps to Reproduce**:

```csharp
using System;

class Program
{
	unsafe static void Main()
	{
		int a = 0;

		var ptrs = stackalloc int*[1] { &a };  // This works...

		Foo(stackalloc int*[1] { &a });   // ...but this doesn't
	}

	unsafe static void Foo(int** ptrs)
	{
	}
}
```

**Expected Behavior**:
The type of the nested `stackalloc` should be `int**`, as in the `var` case.

**Actual Behavior**:
`CS0306	The type 'int*' may not be used as a type argument`
`CS1503	Argument 1: cannot convert from 'System.Span<int*>' to 'int**'`

Whatever rule typed the `var` correctly, should also apply to arguments.

**Comment by lorcanmooney** [comment]
I see that this fails with CS1503 even without the extra level of indirection. It seems that `stackalloc` doesn't do any sort of target-typing for parameters. I guess this is by design then?

**Comment by gafter** [comment]
Stackalloc in nested contexts can only produce values of type `Span<T>`.  If you need it to return a pointer then you need to use stackalloc at the top level.  This is by design.
