### ISSUE TITLE
[loc][Query][Roslyn] Localizability of  the meaning of "base"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#36019]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
The symbol has no base.
'{0}' bases

ID:
0; "The_symbol_has_no_base"
0; "_0_bases"

File Name:
EditorFeatures\Core\xlf\EditorFeaturesResources.xlf

==========================================
Query:
Please clarify the meaning of "base".

**Comment by ryzngard** [comment]
Base in this case refers to a base symbol that is overridden or implemented, such as overriding an abstract method or implementing an interface.
