### ISSUE TITLE
#pragma warning restore CS8625 suppresses later warnings

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#36015]
**Version Used**: VS 16.2.0-pre.1.0+28917.182

**Steps to Reproduce**:

```c#
#nullable enable

string _s = "";

void M()
{
#pragma warning disable CS8625 // Cannot convert null literal to non-nullable reference type.
    _s = null;
#pragma warning restore CS8625 // Cannot convert null literal to non-nullable reference type.

    _s = null;
//       ^^^^ should issue CS8625 here
}
```

**Expected Behavior**:

Warning is restored.

**Actual Behavior**:

Warning is not restored.

**Comment by 333fred** [comment]
I cannot repro this on latest master: https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoHAZgAJ9KBhUgb1MpcoGIA7AVwwwmAxxKcDv0HNWAZRgI0HAOaUoAbgksK1ACyUAsgAoAlJSYk2ABwQR5kSgHcICDnMUATNFDFDakgBwA2PABWSgB6ELoIDg4AexhKAGNojgA3RDjuXkoMNHhLDEoYaMoYjgBaDL4BIQQ4ADNEEXihGABPMzgAOjVWFihKAF5ingxVUwsrG3tHZ2FRKrpfAOCwiKjYhKTUhHThrJzECHzC4qTy4c9KGvqajiaCts7unr7BitGenu6AX1IvoA.
