### ISSUE TITLE
NotNullWhenTrue pattern fails when bool stored in temporary

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#36016]
**Version Used**: VS 16.2.0-pre.1.0+28917.182

**Steps to Reproduce**:

```c#
bool TryGet([NotNullWhenTrue] out object? o)
{
    o = default;
    return false;
}

void M()
{
    bool b = TryGet(out var o);

    if (!b)
    {
        o = new object();
    }

    o.ToString();
//  ^ CS8602 Dereference of a possibly null reference
}
```

Note that if you inline `b` the warning goes away.

**Expected Behavior**:

No warning.

**Actual Behavior**:

Warning.

**Comment by 333fred** [comment]
This is the same problem as https://github.com/dotnet/roslyn/issues/36014.

**Comment by drewnoakes** [comment]
The bug tracking this is #34644.
