### ISSUE TITLE
Interactive Window editor hangs when code outputs very long line

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36022]
VSF_TYPE_MARKDOWNHow do I terminate execution of a script running in the C# Interactive terminal? 

Let's say I wrote a loop that had a logic bug and is now running infinitely. Or there is code that is trying to access a remote resource that is unavailable? 

Right now, when the above happens, I need to wait for the Windows Exec to terminate the process. In the mean time, the VS IDE becomes unusable. 

It would be good if global terminators like CTRL+C or CTRL+BREAK worked to terminate executions within the script window.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/587116/c-interactive-end-execution.html
VSTS ticketId: 900959_
_These are the original issue comments:_

Visual Studio Feedback System on 5/29/2019, 02:29 AM (6 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sujayvsarma** [comment]
Awaiting response.

**Comment by andre-ss6** [comment]
Today the only way to recover from this is to restart the whole IDE! It's absurd. I use the REPL a lot and this has happened quite a lot to me.

Btw, why is this roslyn and not IDE? Couldn't the IDE implement a workaround more quickly like simply restarting the process/thread?

**Comment by tmat** [comment]
There is a Reset button:

![image](https://user-images.githubusercontent.com/41759/66888848-fcfabd80-ef94-11e9-81af-c5f250f49af7.png)

![image](https://user-images.githubusercontent.com/41759/66888852-02580800-ef95-11e9-93ce-5fc49f19ab47.png)

**Comment by andre-ss6** [comment]
Doesn't work :)

![image](https://user-images.githubusercontent.com/15827357/66910908-dfa20f80-efe5-11e9-889a-122c978b64b3.png)

**Comment by sujayvsarma** [comment]
This is my bug. I raised it on DevCommunity that got moved here saying it was a Roslyn issue. 

I can't even click on the darn "reset" button. The whole IDE is hung. Read the statement from the original bug:

> In the mean time, the VS IDE becomes unusable.

The whole darn IDE is stuck. Even Windows slaps a "(unresponsive)" on the window title.

But who even bothers to investigate. They write a silly `while (true);` loop and say kumbaya. 

In my scenarios, I am testing blocks of code from my actual project. Stuff I don't want to run through miles of repro path ways just to see if something is working as expected. And in most cases, these are DLL projects, meaning I'd have to write a client as well to test .. Pasting and running it from REPL seems a quicker way to get quick validation.

But then, Microsoft is only interested in closing out bugs that really bother people without even addressing the issue.

**Comment by sujayvsarma** [comment]
Attention @jaredpar  Is this your area to deal with?

**Comment by andre-ss6** [comment]
> In my scenarios, I am testing blocks of code from my actual project. Stuff I don't want to run through miles of repro path ways just to see if something is working as expected. And in most cases, these are DLL projects, meaning I'd have to write a client as well to test .. Pasting and running it from REPL seems a quicker way to get quick validation.

This is exactly my scenario as well. 

And just like I showed, the IDE can become unresponsive depending on what you do.

> But who even bothers to investigate. They write a silly while (true); loop and say kumbaya.

This is just _so_ frustrating. The way MS, especially IDE, have been addressing feedback is just the most frustrating thing. They just respond in any way they feel like and close the issue. Just like this one, I've seen this happen many, many times. It's really sad. It feels like MS simply isn't prepared to maintain their products, like the teams are overwhelmed or maybe there simply aren't enough skilled people there. Sigh. /rant off

**Comment by sujayvsarma** [comment]
Exactly, and then when you point it out to them, they say you are being "rude" and stop responding to you.

**Comment by tmat** [comment]
I see. It hangs when the code spews lots out output on a single line. Will look into that. 
Updated title accordingly.

**Comment by andre-ss6** [comment]
Wow, now that's some fast bug fixing! 💖 Wish every report on DevCommunity could get this much attention from the team :(

**Comment by tmat** [comment]
It helps if we can easily reproduce the issue. [Your comment](https://github.com/dotnet/roslyn/issues/36022#issuecomment-542634824) helped a lot. Thanks!
