### ISSUE TITLE
dynamic parameter fails to bind method with FormattableString parameter

### ISSUE THREAD

**Issue by pmunin** [dotnet/roslyn#36023]
**Version Used**:  C# 7.1

**Steps to Reproduce**:
```
        [Fact]
        public void TestDynamicBreaksFormattableString()
        {
            dynamic d = 231.45m;
            var x = ShouldBeEqualTo(d, $"my formattable string with parameters");
        }

        public bool ShouldBeEqualTo(decimal value, FormattableString formula)
        {
            //Doing something with formul.GetArguments()...
            return true;
        }
```

**Expected Behavior**:
x = true

**Actual Behavior**:
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 
'The best overloaded method match for 
'....ShouldBeEqualTo(decimal, System.FormattableString)' has some invalid arguments'

```

**Comment by pmunin** [comment]
I'm don't understand why Roslyn has to do some fancy rabit-from-a-hat tricks with interpolated strings, forcefully converting $"blah blah" to string on declaration. Which will treat `$"blah blah"` is a `String`, not a `FormattableString` unless you do `(FormattableString)$"blah blah"`. Why not to treat them the just as a `FormattableString`, with implicit string convertion operator? 

For example Decimals and Doubles:
When you specify in code `var x = 123.00` - it will be double. when you do `var x = 123.00m` - it will be decimal.

Why not to do same: when $"" declares FormattableString instance + provide implicit conversion operator from FormattableString to String?

**Comment by canton7** [comment]
> Won't that make everyone's life easier?

Note that it will make everyone's life slower. Allocating a `FormattableString` will allocate at least 2 new objects, which aren't currently allocated (for small numbers of interpolated expressions). It will also disable optimizations which turn an interpolated string into a call to `string.Concat`, or indeed into a string literal.

It will also be a change to [the spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#interpolated-strings). Currently an interpolated string is specified as having implicit conversions to `string`, `FormattableString` and `IFormattable`.

It will also presumably be breaking, as the behaviour of this would change:

```csharp
public static class Program {
    public static void Main() {
        dynamic d = 231.45m;
        Method(d, $"my formattable string with parameters");
    }
    
    public static void Method(decimal value, string formula)
    {
        Console.WriteLine("string");
    }
	
	public static void Method(decimal value, FormattableString formula)
    {
        Console.WriteLine("FormattableString");
    }
}
```

**Comment by pmunin** [comment]
The example you provided will never call FormattableString overload, unless the parameter type explicitly specified on call:
```
    public static class Program
    {
        public static void Main()
        {
            var d = 231.45m;
            Method(d, $"my formattable string {"blah blah"}");
            Method(d, $"my formattable string {"blah blah"} with parameters {d:C}");
            Method(d, (FormattableString)$"my formattable string {"blah blah"} with parameters");
        }

        public static void Method(decimal value, string formula)
        {
            Console.WriteLine("string");
        }

        public static void Method(decimal value, FormattableString formula)
        {
            Console.WriteLine("FormattableString");
        }
    }
```
**Program.Main will be compiled into**:
```
public static void Main()
{
	decimal d = 231.45m;
	Program.Method(d, "my formattable string blah blah");
	Program.Method(d, string.Format("my formattable string {0} with parameters {1:C}", "blah blah", d));
	Program.Method(d, FormattableStringFactory.Create("my formattable string {0} with parameters", "blah blah"));
}

```

**Comment by canton7** [comment]
> The example you provided will never call FormattableString overload, unless the parameter type explicitly specified on call

My point was that your suggested change would change the behaviour of this sample, as it would no longer call the `string` overload, and would instead call the `FormattableString` overload. It would therefore be a breaking change.

**Comment by pmunin** [comment]
Won't it work calling string overload if FormattableString would have implicit conversion operator returning string?

**Comment by canton7** [comment]
My sample had two methods. One took a `string`, the other took a `FormattableString`. Currently, the overload which takes a string is chosen. If you change interpolated string so that they always produce an `FormattableString` (which has an implicit conversion to a string), then it will choose the overload which takes a `FormattableString`. That is a breaking change in behaviour.

**Comment by canton7** [comment]
I can see an argument for adding an implicit conversion from `string` to `FormattableString` (which could avoid allocating the arguments array), which I think would solve your original issue?

**Comment by pmunin** [comment]
I just tested it, and yes implicit conversion will work:
```
    public static class Program
    {
        public static void Main()
        {
            var fmt = new Formattable($"my formattable string {"blah blah"}") ; 
            Method(fmt); //Will work calling string overload if Formattable overload does not exist
        }

        public static void Method(string formula)
        {
            Console.WriteLine("FormattableString");
        }
        //public static void Method(Formattable formula)
        //{
        //    Console.WriteLine("FormattableString");
        //}
    }

    public struct Formattable
    {
        FormattableString value;

        public Formattable(FormattableString value)  //constructor
        {
            this.value = value;
        }

        public static implicit operator Formattable(FormattableString b)
        {
            var f = new Formattable(b);
            return f;
        }
        public static implicit operator string(Formattable b)
        {
            return b.value.ToString();
        }
    }
```

**Comment by canton7** [comment]
> //WILL CALL THIS BY DEFAULT IF UNCOMMENTED

Yes, that's the "breaking change" bit I was referring to.

Don't comment either of the methods.

 - Before: Calls the overload with `string`
 - After: Calls the overload with `FormattableString`

That is a breaking change in behaviour.

**Comment by pmunin** [comment]
I understand, however even though it is breaking change that new behavior would be more expected, therefore will cause less confusion and will not cause this Exception with dynamic in the main example. Breaking change is a natural thing happening in framework development.

**Comment by pmunin** [comment]
Another consequent issue that shows how confusing this hidden logic is:
```
bool someCondition = true;
var d = 123.45m;
FormattableString v1 = $"blah blah {d:C}"; // Works fine
FormattableString fmt = someCondition ? $"blah blah {d:C}" : null; // Compilation error: Cannot implicitly convert `string` to 'System.FormattableString'
```

**Comment by gafter** [comment]
This is by design.  The specification gives the natrual type of an interpolated string as `string` unless it is subject to a conversion-from-expression to `FormattableString` or the like, which is not the case in this program.

If you want the language changed, please take the discussion to `csharplang`.

**Comment by canton7** [comment]
Note that this is not restricted to `dynamic`. Here are some other things that would break....

Normal method overloading:

```csharp
void Method(string s) { }
void Method(FormattableString s) { }

Method($"foo"); // Before: Method(string) called; after: Method(FormattableString) called
```

Code which depends on when `ToString` is called:

```csharp
public class C
{
    public string Foo { get; set; }
    public override string ToString() => Foo;
}

var c = new C();
var str = $"Hello {c}";
c.Foo = "Foo";
Console.WriteLine(str); // Before: "Hello ", after: "Hello Foo"
```

Code which depends on how many times `ToString` is called:

```csharp
class C
{
    private int i;
    public override string ToString() => (++i).ToString();
}

var c = new C();
var str = $"Hello {c}";
Console.WriteLine(str);
Console.WriteLine(str); // Before: "Hello 1", after: "Hello 2"
```

Code which depends on the runtime type of an interpolated string:

```csharp
void Foo(object o)
{
    if (o is string s)
    {
        Console.WriteLine("Got a string: " + s);
    }
}

Foo($"Hello, World");
```

Another case where the implicit conversion can't be used:

```csharp
string[] strings = new[] { $"Foo", $"Bar" };
```

Generic type inference:

```csharp
void Foo<T>(T t)
{
    if (typeof(T) == typeof(string))
    {
        Console.WriteLine("Got a string!");
    }
}

Foo($"Foo");
```

There are many more, e.g. where the type of an interpolated string has consequences, or where the suggested implicit conversion from `FormattableString` to `string` can't be used.

Did I mention there are optimizations where string literal parameters become part of the format string (so `$""` is just `""`, and `$"Name: {nameof(something)}"` is just `"Name: something"`), and `string.Concat` is used where possible to speed things up?

> Breaking change is a natural thing happening in framework development.

I think you'll quickly find that there is a huge focus on backwards compatibility around here!

This all seems to stem from your conviction that an interpolated string is, first and foremost, a `FormattableString`. I don't think this is how the language designers saw it - it's clear from the spec that an interpolated string is primarily syntactic sugar for `string.Format`. Once you look at all of your examples with that view, then all of a sudden the current behaviour makes sense.
