### ISSUE TITLE
INamedTypeSymbol.Construct() does not have a way to pass in nested nullabilities

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#36046]
INamedTypeSymbol.Construct() lets you take a generic type and construct a, well, constructed generic type. But you can't give nested nullabilities -- it needs an overload or way to pass them in.

**Comment by ryzngard** [comment]
Can we add an `INamedTypeSymbol.Construct()` that does the right thing for our wrapping type, with the intention to remove?

**Comment by jasonmalinowski** [comment]
@ryzngard hmm, that's a good idea, ConstructWithNullability?

**Comment by jcouv** [comment]
@jasonmalinowski @ryzngard I assume this is affecting/blocking some IDE work. Let us know if that's not the case.

**Comment by jasonmalinowski** [comment]
Yes, there's at least a few cases in the type inferrer this is blocking.

**Comment by jcouv** [comment]
@cston Would you have bandwidth to take this issue on?

**Comment by jasonmalinowski** [comment]
#30325 would be another example of an actual product bug filed by @jcouv. :-)
