### ISSUE TITLE
Cursor movement doesn't make sense when renaming

### ISSUE THREAD

**Issue by billwert** [dotnet/roslyn#36043]
This may be too narrow but I hit a case today where it was really annoying, so for your consideration.

I had an enum I was trying to remove the beginning of. (Imagine several values all starting with `Keyword`.) What I wanted to do was:
1) place the cursor after the `d`
2) invoke rename 
3) Hit shift-home to select `Keyword`
4) hit backspace
5) hit enter

**Version Used**: 
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.2.0 Preview 2.0 [28928.284.d16.2stg]
VisualStudio.16.IntPreview/16.2.0-pre.2.0+28928.284.d16.2stg
Microsoft .NET Framework
Version 4.8.03752
**Steps to Reproduce**:

1. Place cursor in the middle of a name
2. invoke rename 
3. press left arrow

**Expected Behavior**:
Cursor is within the name and moves one character

**Actual Behavior**:
Highlight is removed and cursor is at the beginning of the name

**Comment by CyrusNajmabadi** [comment]
This is no longer how rename works.   Editing happens in the popup that appears, not hte editor anymore.
