### ISSUE TITLE
Compilation.Create*Type does not give a way to pass top-level nullabilities

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#36047]
Right now the API gives you no way to specify top-level nullability of the members.

**Comment by gafter** [comment]
Similarly, `INamedTypeSymbol.Construct` gives no way to specify top-level nullability of the type arguments.

**Comment by gafter** [comment]
Similarly `Compilation.CreateArrayTypeSymbol` gives no way to specify the top-level nullability of array element type.

Similarly `Compilation.CommonCreateAnonymousTypeSymbol` gives no way to specify the top-level nullability of the members.

**Comment by jasonmalinowski** [comment]
The Construct case specifically we're tracking in #36046 too.

**Comment by jcouv** [comment]
@jasonmalinowski @agocke @333fred I assume we treat this as important/blocking for RTM. Keeping in 16.3.

**Comment by jasonmalinowski** [comment]
@jcouv Correct, this is blocking some IDE bug fixes.
