### ISSUE TITLE
Scrollbar is nebulous in the diff window of vs2019

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#36057]
It's the same project.
vs2017:
![vs2017](https://user-images.githubusercontent.com/2529999/58643969-ed0a7600-8332-11e9-8f0e-fb16dfbe9831.png)

vs2019:
![VS2019](https://user-images.githubusercontent.com/2529999/58644007-fa276500-8332-11e9-8df2-95eef0d12e71.png)

vs2017:
![vs2017_2](https://user-images.githubusercontent.com/2529999/58699592-6efcac80-83d0-11e9-93e9-55c83d61aec2.png)

vs2019:
![vs2019_2](https://user-images.githubusercontent.com/2529999/58699610-79b74180-83d0-11e9-96e7-6abf1deeb541.png)

vs2017 is clear, but vs2019 is nebulous.

**Comment by vatsalyaagrawal** [comment]
@olegtk where does this one belong?

**Comment by olegtk** [comment]
route it to the editor please. thanks!
