### ISSUE TITLE
OverrideCompletionProvider should allow items to be added 

### ISSUE THREAD

**Issue by avodovnik** [dotnet/roslyn#36060]
**Version Used**: 3.1.0-beta4-19261-04

Visual Studio for Mac has a _special_ behaviour that is specific to the way Xamarin/AppKit works. We offer the user "overrides" where they actually aren't overrides but _protocol member implementations_ (note: this is also _not_ an interface implementation but an Objective-C specific):

![image](https://user-images.githubusercontent.com/1932563/58651162-d4896400-8310-11e9-8d9b-b209e69f3eb6.png)

Picking `AddObserver` in the list above, would result in the following code being added:

```csharp
[Export("addObserver:forKeyPath:options:context:")]
public void AddObserver(NSObject observer, NSString keyPath, NSKeyValueObservingOptions options, IntPtr context)
{
    throw new System.NotImplementedException();
}
```

Recently, when moving away from [our old implementation of how we surface completion](http://source.monodevelop.com/#MonoDevelop.CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs,466) items, we discovered that we can no longer add items to the `override` list. The assumption is that [this](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionServiceWithProviders.cs,263) and [this](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/Providers/AbstractOverrideCompletionProvider.cs,35) are the culprits. 

We're happy to contribute the required change, but feel like it should be discussed first, to make sure we take the right approach. Here are some of the possible ones:

1) Add a way to register completion providers in a way where we un-register the existing one. That way we could derive from `OverrideCompletionProvider` and extend it with our required logic.
2) Enable `OverrideCompletionProvider` to also call down to _another_ set of MEF-provided providers, to retrieve additional items. 
3) Change [this](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionServiceWithProviders.cs,263) to take *all* contexts that had `IsExclusive` set to `true`. Potentially, there could be more metadata on the provider itself (i.e. a `Tag`) and we'd group exclusivity by the same tag as well).

Are we missing something obvious? Is any of the above options something that would be acceptable to PR?

**Comment by CyrusNajmabadi** [comment]
This is definitely an interesting case, which we particularly never created a design for.   What i would likely feel is the most acceptable approach is '3'.  

As to my thoughts on all three options:

> Add a way to register completion providers in a way where we un-register the existing one. That way we could derive from OverrideCompletionProvider and extend it with our required logic.

This would require making OverrideCompletionProvider overridable.  We specifically rarely design for that.  It really puts stringent constraints in place on how you construct your type, and it can be very hard to test/verify.  It also makes it very difficult to change that type in the future.  So i would not be for this idea.

> Enable OverrideCompletionProvider to also call down to another set of MEF-provided providers, to retrieve additional items.

Not a huge fan of this either.  It's basically just a hack to get additional members inserted into a *very* specialized behavior for one extremely special case.  It's not a particularly cohesive design that feels core to completion.

> Change this to take all contexts that had IsExclusive set to true. Potentially, there could be more metadata on the provider itself (i.e. a Tag) and we'd group exclusivity by the same tag as well).

This seems somewhat reasonable to me.  The original idea on 'Exclusive' was there would be at most one, and it meant "don't even bother with any of hte other providers".   We never really considered what it woud mean to have multiple of them.  I can totally see the idea being that it's simply that all the 'exclusive' providres just win-out over the non-exlusive one.

This would ideally work for you, and would not mean that anything about 'override' completoin was special.  Simply that we had a mechanism for multiple providers to play together that doesn't break existing scenarios.

**Comment by avodovnik** [comment]
> This would ideally work for you, and would not mean that anything about 'override' completion was special. Simply that we had a mechanism for multiple providers to play together that doesn't break existing scenarios.

Yes, that seems entirely reasonable. I'll try and get a PR in soon on this. I guess for a first pass there's no need to include anything like tags, and just group all exclusive ones. We do need to ensure that other providers also setting `IsExclusive` are returning an empty completion list.
