### ISSUE TITLE
Formatting of comments with Dotnet Format

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#36069]

**Comment by vatsalyaagrawal** [comment]
@mikadumont please provide some more information about the ask

@JoeRobich for FYI

**Comment by JoeRobich** [comment]
The Roslyn `Formatter` is used by dotnet-format for whitespace formatting. If the ask concerns "formatting" other than spaces or new lines, we may want to move this to the dotnet/format repo.

**Comment by mikadumont** [comment]
@JoeRobich

Customer request copying here:

> Let's say you have:

> // Lorem ipsum dolor sit amet, consectetur adipiscing elit. In fermentum semper orci. Fusce non diam magna. Vestibulum quis est eget massa suscipit commodo. Integer lacinia ultrices aliquam. Cras tempor lacus malesuada, volutpat sem at, blandit ligula.

> or

> // Lorem ipsum dolor sit amet,
// consectetur adipiscing elit. In fermentum semper orci. Fusce non diam magna.
// Vestibulum quis est eget massa suscipit commodo. Integer lacinia ultrices aliquam. Cras tempor lacus malesuada, volutpat sem at, blandit ligula.

> ... and you press Ctrl+.

> Two options should be available: "Tidy using //" and "Tidy using /**/"

> Both options distribute the comment using .editorconfig to determine the maximum characters per line, resulting in (for example):

> // Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
// fermentum semper orci. Fusce non diam magna. Vestibulum quis
// est eget massa suscipit commodo. Integer lacinia ultrices
// aliquam. Cras tempor lacus malesuada, volutpat sem at,
// blandit ligula.

**Comment by CyrusNajmabadi** [comment]
There's already a good extension (rewrap) that provides this functionality
