### ISSUE TITLE
SubscribeExternalErrorDiagnosticUpdateSourceToSolutionBuildEvents relies on implementation detail of KnownUIContexts.SolutionBuildingContext

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#36065]
KnownUIContexts.SolutionBuildingContext throws NRE when `(IVsMonitorSelection)ServiceProvider.GlobalProvider.GetService(typeof(IVsMonitorSelection)))`,
is null.

This happens in tests since we can't mock a global service. 

Ideally, the platform would expose better APIs that notify about solution build events.

**Comment by vatsalyaagrawal** [comment]
@tmat please set the milestone as appropriate.

**Comment by CyrusNajmabadi** [comment]
Closingo ut as we do a null check for this;
