### ISSUE TITLE
Object initializer syntax suggests assignment to Getter-Only Properties

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#36071]
**Version Used**: 
Visual Studio 2019

**Steps to Reproduce**:

If you have this class:
````
public class Foo {
  public string Name {get; set;}
  public int Age {get; private set;}
}
````

When you type:
````
var F = new Foo() {
  //Popup appears here
````
The autocomplete popup lists Age as a member.  It shouldn't.  It can't be set.

**Expected Behavior**:
Don't suggest that I can assign to a getter only property.

**Actual Behavior**:
It suggests that I assign to a getter only property.

**Comment by vatsalyaagrawal** [comment]
Duplicate of #22816
