### ISSUE TITLE
C# Interactive Window - Specify .NET version to use

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/roslyn#36084]
How do you specify the version of .NET (specific version of Framework or Core as it may be) for use with the C# interactive window? 

This is important because if you are developing code in a newer or different version of .NET, you cannot readily use the `#r` to load your current project assembly and test out a path of code. 

I came across this issue recently when I was working on a .NET Core 3.0 P5 project and the C# Interactive threw all manner of funky errors before I realized that the root cause was the different .NET engines.

From what I can see, the VS IDE has no way to set this up via Configuration.

**Comment by jcouv** [comment]
Tagging @tmat

**Comment by tmat** [comment]
We currently do not support any other version of .NET than .NET Framework installed on your machine.

**Comment by IronSean** [comment]
HAs this changed with .Net 5? Is it 5 if installed, or is it still just using the latest version of Framework available?

**Comment by IronSean** [comment]
Has this changed with .Net 5? Is this using .Net 5 now or is it still just using the latest available version of framework? I'm attempting to use features from .Net 5 and getting errors when I test. @tmat

**Comment by Arkane5** [comment]
If anyone lands on this page after a web search, it's possible since VS 2019 (v.16.8.2, it seems) to use `#reset core` in C# Interactive, and it will use .Net/.Net Core.
Use `#reset 32` or `#reset 64` to use .Net Framework 32 or 64 bits.

The original question is still unanswered: How to chose a specific version (among those installed on the system)?
In VS 2022, v.17.10 it uses .Net 8.0 (checked with `Environment.Version`), but what if I want to test something using .Net 6, 7 or 9?

**Comment by mattefowler** [comment]
i'm running into issues with this; i've built a new app with .net 9 and i'm unable to use c# interactive console. it's been broken to various degrees for some time (the issue has usually been "unable to load System.Runtime") but it's now unable to launch at all. 

when i launch it through visual studio i get:
> #reset core
Resetting execution engine.
Failed to launch 'c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\vbcsharp\languageservices\InteractiveHost\Core\InteractiveHost64.exe' process (exit code: -2147450743) with output: 
慆汩摥琠⁯潬摡匠獹整⹭牐癩瑡⹥潃敲楌⹢汤⁬攨牲牯挠摯⁥砰〸㜰〰㈰ഩ倊瑡㩨䌠尺牐杯慲⁭楆敬屳潤湴瑥獜慨敲層楍牣獯景⹴䕎䍔牯⹥灁屰⸸⸰㈱卜獹整⹭牐癩瑡⹥潃敲楌⹢汤൬䔊牲牯洠獥慳敧›潃汵⁤潮⁴潬摡映汩⁥牯愠獳浥汢⁹䌧尺牐杯慲⁭楆敬屳潤湴瑥獜慨敲層楍牣獯景⹴䕎䍔牯⹥灁屰⸸⸰㈱卜獹整⹭牐癩瑡⹥潃敲楌⹢汤❬‮桔⁥祳瑳浥挠湡潮⁴楦摮琠敨映汩⁥灳捥晩敩⹤⠠砰〸㜰〰㈰ഩ䘊楡敬⁤潴挠敲瑡⁥潃敲䱃ⱒ䠠䕒啓呌›砰〸㜰〰㈰਍

love the encoding fail. 

launching it from a powershell terminal is more helpful: 

 .\InteractiveHost64.exe
Failed to load System.Private.CoreLib.dll (error code 0x80070002)
Path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.12\System.Private.CoreLib.dll
Error message: Could not load file or assembly 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.12\System.Private.CoreLib.dll'. The system cannot find the file specified. (0x80070002)
Failed to create CoreCLR, HRESULT: 0x80070002

that file is, in fact, absent (and is present in the analogous .net 9 directory) - however i am using new .net9 features and need the terminal to target the correct runtime. 

how can i configure the c# console to target .net 9? 

i'm making a robotic application and this is an invaluable tool for manual operation of the instrument.
