### ISSUE TITLE
Is it a bug about Stash?

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#36083]
**Version Used**: 16.1.1

**Steps to Reproduce**:

1. Create a console application, Add to source control, Git.
2. Modify program.cs, and Stash All.
3. Apply the Stash
4. Undo changes
5. Apply the Stash again

**Expected Behavior**: Apply succeed.

**Actual Behavior**:
Git operation failed because there are uncommitted changes. Commit or undo your changes before retrying. See the Output window for details.

**Comment by jcouv** [comment]
@jinujoseph Do you know how to route this issue?

**Comment by jaredpar** [comment]
Closing as this looks like a general GIT question, not roslyn or dotnet. Nowhere in the org to route this issue. Suggest asking on stackoverflow.com using the `git` tag.
