### ISSUE TITLE
Ensure we don't leak wrapped symbols from public Workspace APIs

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#36099]
We have a few APIs on the Workspace level that return ISymbols; we should make sure we always return the unwrapped symbols otherwise we might break third parties.

**Comment by CyrusNajmabadi** [comment]
> We have a few APIs on the Workspace level that return ISymbols; we should make sure we always return the unwrapped symbols otherwise we might break third parties.

But what if some other feature calls into that Workspace level API... how would that then work?  Wouldn't they lose the nullability information?  Will we need overloads for them to call? ick... :-/

**Comment by jasonmalinowski** [comment]
A very quick glance looked like most of the APIs we do expose are things that are things like moving up/down inheritance hierarchies where I'm not sure if we even did things like preserve constructed generic types. I'm totally bucketing this is in a "I don't know, but we'll find out once we get there". I also expect that by that point we'll be in a much better place to know if we're just pushing this onto the compiler or what our pattern is going to be.

**Comment by jasonmalinowski** [comment]
Need to keep this in 16.2 until we've evaluated the risk-- this would break extensions otherwise.
