### ISSUE TITLE
Compiler is too restrictive about local variable scopes

### ISSUE THREAD

**Issue by fr0** [dotnet/roslyn#36092]
I understand that C# has always been this way. I'm asking for it to be changed.

**Version Used**: 

C# 7.3

**Steps to Reproduce**:

```
void Foo() {
  {
    int x = 5;
    Console.WriteLine(x);
  }
  int x = 6;
  Console.WriteLine(x);
}
```
```
[CS0136] A local or parameter named 'x' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
```

These are two different variables, and in reality, they have different scopes. Deleting the 2nd declaration of `x` wouldn't suddenly make the compiler think that the 2nd WriteLine was referencing the first `x`; it would be a compiler error.

 Other languages (e.g. TypeScript) get this right. There's no reason why C# can't figure it out.

**Comment by 333fred** [comment]
This is asking for a language change, not a compiler change. Please move your issue to dotnet/csharplang.
