### ISSUE TITLE
Export settings not export all text editor code styles

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36104]
VSF_TYPE_MARKDOWNso there are a lot of parameters in **Options &gt; Text Editor &gt; C# &gt; Code Style &gt; General** that are not exported to **Export Setting** file. i installed a fresh not synced VS instance and exported the setting environment and imported to a modified VS instance and i noticed that not all of code styles are changes, after furthure investigating i realized that not all of the code style rules exported in vssettings file, you can simply test this with below steps:

1- export your vs setting (File 1)
2- change rule **Prefer auto properties** to **Warning**
3- export your vs setting (File 2)
4- examinig the File 1 and 2 with a comparer and relize those are exactly the same

this is ok with top like 5 rules so i sure it should be working but i'm sure some of them are not working, not sure how many but some of them not exported in vssettings file.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/536234/export-settings-not-export-all-text-editor-code-st.html
VSTS ticketId: 849141_
_These are the original issue comments:_

Visual Studio Feedback System on 4/16/2019, 11:43 PM (44 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Rock Li [MSFT] on 4/23/2019, 02:26 AM (38 days ago): <p>Hi Masih, I performed the repro steps you provided that found something interesting:</p><ol>
<li> Export settings file01 from a fresh VS instance, did not restart VS and change the code style option "<strong style="color:rgba(0, 0, 0, 1);">Prefer auto properties</strong><span style="color:rgba(0, 0, 0, 1);background-color:rgb(255, 255, 255);"> to </span><strong style="color:rgba(0, 0, 0, 1);">Warning</strong>", continue to export settings file02.</li><li>Open file01 and file02 by VS, and use command window compare them, almost no difference as picture one shows: </li></ol><p>       </p><p><img id="69783" src="https://developercommunity.visualstudio.com/storage/temp/69783-one.png"></p><p>	3. Repeat the steps but restart VS every times once the settings changed, the compare has a different result: </p><p><img id="69784" src="https://developercommunity.visualstudio.com/storage/temp/69784-two.png"></p><p>I guess something could not correct reload after you changing the settings, so it was not exported immediately.</p><p>could you try restart VS when you change and export settings? does the issue still repro?</p>
</ol>

Masih Akbari on 4/23/2019, 04:23 AM (38 days ago): (private comment)
Visual Studio Feedback System on 4/23/2019, 08:01 PM (37 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

Rock Li [MSFT] on 4/23/2019, 08:02 PM (37 days ago): <p>Thanks for taking the time to report this issue to us. We’ve created a bug for this issue as internal tracking. The status on this Developer Community item will be updated as that bug is resolved. Thanks again for your feedback.&nbsp;</p>
Visual Studio Feedback System on 4/28/2019, 11:24 PM (32 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 4/28/2019, 11:55 PM (32 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
@kendrahavens , Can we evaluate the user voice and figure out what rules needs to be exported over.

**Comment by MasihAkbari** [comment]
My answer to Rock Li [MSFT] is not moved here from developercommunity so i copy it here:

Well i test it again without any luck
this is the freshly installed VS configure
![image](https://user-images.githubusercontent.com/8469800/58744596-28ec2b00-845a-11e9-8a79-ecb5e39c3a58.png)

and i export settings now. then i just change "Prefer auto properties" to warning. noting else

![image](https://user-images.githubusercontent.com/8469800/58744601-32759300-845a-11e9-8675-56cbeba1441b.png)

and export it again.
but nothing is different in settings files. even i closed VS and restart it again and make an export but it's the same too.
i attached setting files
[settings.zip](https://github.com/dotnet/roslyn/files/3243466/settings.zip)

**Comment by kendrahavens** [comment]
@jinujoseph @sharwell The user reported `Prefer auto properties` severity and settings not exporting to the .vssettings file. It looks like we don't export any of the code block preferences to .vssetttings, but other code styles like var/explicit type preferences and expression preferences in the C# code style section are exported to vssettings.

**Comment by CyrusNajmabadi** [comment]
A while back, the messaging was that the .vssettings approach was effectively deprecated (or on life support) and that .editorconfig was the way VS was going to be doing things moving forward.  So we didn't make our new features use .vssettings.  Did something change in that regard?

**Comment by kendrahavens** [comment]
I would think there are a _ton_ of settings that are editor wide that a user would never want to be included in editorconfig which would normally change per project you are working in. For this reason, I'd be surprised if editorconfig was meant to replace vssettings entirely. I thought editoconfig and vssettings were expected to work in tandem. @jinujoseph Maybe a good topic to discuss with the Editor team?

**Comment by jmarolf** [comment]
> A while back, the messaging was that the .vssettings approach was effectively deprecated (or on life support) and that .editorconfig was the way VS was going to be doing things moving forward.

I don't think this true. `.vssettings` is the only way for settings to be synced with your Visual Studio account. I assume that if someone manually specified a set of default styles for themselves in VS once they would like that to roam with them.

**Comment by CyrusNajmabadi** [comment]
Gotcha.  If this is the case, then i'm 100% good with having .vssettings support added back in.  THere must have been some crossed wires.  I could have sworn meetings with editor that were effectively: we're totally backing this horse, this is the way forward.  But it might have been more about just really caring about .editorconfig and *not* caring *less* about vssettings.

Note: i still think we had this discussion at some point.  Primarily because it was always a pain trying to figure out how things should all work with these systems all active at the same time.  However, my github searching has revealed nothing, and i obviously don't have access to my emails anymore.  I really honestly thought we were trying to deprecate and push people to editorconfig since it just solved a bunch of these thorny issues...

Oh well, maybe i'm just losing my mind :)

**Comment by jmarolf** [comment]
@CyrusNajmabadi 	Here is my understanding:
- for user specified options we want to push people to use editorconifg where possible.  It just a better experience, especially with teams.  I would hope that every .Net project on github would have an editorconfig
- until VS creates a different API to roam settings we need to continue to be able to round-trip things and `.vssettings`is the best mechanism we have. Any setting that the user can set from UI in VS therefore needs to be reflected in `.vssettings`

**Comment by SetTrend** [comment]
@CyrusNajmabadi, @jmarolf:

Is there any news on this? Today, end of 2025, I exported my settings from one Visual Studio 2022 installation to a fresh installation on another machine. And still almost none of the factory settings have been updated to my preference.
