### ISSUE TITLE
Replace BoundDagEvaluation.Equals and GetHashCode with specific method for testing equivalence

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#36102]
`BoundDagEvaluation.Equals(BoundDagEvaluation other)` compares original input and ignores any type evaluations (see https://github.com/dotnet/roslyn/pull/35669). That seems misleading for a general `Equals` method.

Since the method is only used for testing equivalence, perhaps `Equals(BoundDagEvaluation)` should be renamed (perhaps `IsEquivalentEvaluation`) and the `GetHashCode()` override could be removed.

**Comment by gafter** [comment]
It is possible that this issue is obsolete based on changes since it was filed.

**Comment by gafter** [comment]
Indeed, the current implementation simply compares all the significant data, without skipping type evaluations.
