### ISSUE TITLE
Support null checking with property in Nullable Reference Type analysis

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/roslyn#36149]
```c#
class Foo
{
    public TaskCompletionSource<bool>? _completionSource;

    public bool IsStopped => !(_completionSource is null);
    // or
    public bool IsStopped => _completionSource != null;

    public void Bar()
    {
        if (IsStopped)
        {
            // Possible dereference
            _completionSource.SetResult(true);
        }

        if (!(_completionSource is null))
        {
            // This is fine
            _completionSource.SetResult(true);
        }
    }
}
```

I know I can stick a dammit operator in there, was just wondering if there are plans to support such null checks in analysis.

**Comment by jcouv** [comment]
There is no plan to support such an analysis at this point.
This issue is similar to https://github.com/dotnet/roslyn/issues/34800

**Comment by MihaZupan** [comment]
Okay. Thanks for the response.

**Comment by jcouv** [comment]
This will be supported in C# 9 after all, but requires an attribute to be placed saying that the return value of `IsStopped` affects our knowledge of the state of `_completionSource`.

```
class Foo
{
    public TaskCompletionSource<bool>? _completionSource;

    [MemberNotNullWhen(true, "_completionSource")]
    public bool IsStopped => !(_completionSource is null);
    
    public void Bar()
    {
        if (IsStopped)
        {
            // Possible dereference
            _completionSource.SetResult(true);
        }

        if (!(_completionSource is null))
        {
            // This is fine
            _completionSource.SetResult(true);
        }
    }
}

namespace System.Diagnostics.CodeAnalysis
{
    [AttributeUsage(AttributeTargets.Method | AttributeTargets.Property, AllowMultiple = true)]
    public sealed class MemberNotNullAttribute : Attribute
    {
        public MemberNotNullAttribute(params string[] members) { }
        public MemberNotNullAttribute(string member) { }
    }
}

namespace System.Diagnostics.CodeAnalysis
{
    [AttributeUsage(AttributeTargets.Method | AttributeTargets.Property, AllowMultiple = true)]
    public sealed class MemberNotNullWhenAttribute : Attribute
    {
        public MemberNotNullWhenAttribute(bool when, params string[] members) { }
        public MemberNotNullWhenAttribute(bool when, string member) { }
    }
}
```

[sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGAdAEQEsIBzAOwHtZCBjKXAYQoBM4BBMiAGwE8pCoAbgCwAKHRZsAVhGiAxGQCuXLhGBc4GOJ3VwxYlACYMAMQoUxAbzEZbWAMxYAbEzAAHDTEIUyAZQqKCDRwADzA5lwAfAD8GAD6NBTunt5+AUFwsjZ2ANoAsnBgwIgAchQwJcpcAOoAFtoAFDAIinAANBgARAlJHnBePv6BwZ0AlAC62bYojuEUXBgAklC+MBRubnDMGAC8kRgAhA09yf2pQxkYAhhKKqOydhhTDlgALBgAQhAIDaPP1qJHo9CAAzDANZardabZh/QFA2wAhEIgD0KIwAAUqPxdBhWAg4CDENpgs9kfFEqcBmlhnBcL5+gAlOBQZQwJotOD3Ml2AC++nhCNB4KOJz61IuwSuUBuVVGcPJSPJdjRGAAKrVrtcQYQyHpBcqxSlBulgvSmSy2RzWtyDY9+QaHQ6xJwwCy3BApTgCMRyFQvHRGCx2JxePwoFZnjk2DBmoRgIp4ABVKCkOANGNxhPwNXfEj9egFGC1FgYJAYTMIeOJuC5hD5mD0DEIdaIGA8DpsFQUADueTZhD6uwwzRtkwNMwwUDg3C2WGMBSKpXKlRUler8AwIArsar2f1jyVCMni+KCDKFSq6/3DQ9CAgYBlODQOXGGDdS4QUFGGEsGAd5InoUZ4XquXDXjWDTPu+wGID+f4AXyYjOqIrrup6mjekQpCUNQgZMKwHDcHwAiRga0a7hucApmmGaUfudYNoW/Qlts5YQTmeYFrgzatgg7adt2fYDkOOwjpyEzPJO06ztsRgYKey6XiodTaBxmjbup/w8tMjiKeeK5VKpZDqQ0cwLD29RkB0d4Pk+2Avm+H5nt+v7/jpLz6aBRlWaZ5kYJZ2gdNBzlwW5iG2E6QA)

**Comment by MihaZupan** [comment]
Thanks! I didn't realize the attribute will be supported on properties as well.

Thanks for reaching out even on such an old and closed issue
