### ISSUE TITLE
Remove unused parameter does not do anything when clicked

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36153]
VSF_TYPE_MARKDOWNI see a parameter in my constructor with a greyed out identifer and the 3 green dots under it. I hover over it and see the message that the parameter is unused. I click on the light bulb icon next to the message but nothing happens.

The parameter is correctly being identified as unused.
The menu offering the option to remove the parameter does not appear. Nor is the parameter removed.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/593322/remove-unused-parameter-does-not-do-anything-when.html
VSTS ticketId: 904617_
_These are the original issue comments:_

Visual Studio Feedback System on 6/3/2019, 08:13 PM (14 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 6/4/2019, 09:07 AM (73 min ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by mavasani** [comment]
We have implemented only the analyzer for flagging unused parameters. There is no code fix, as we might not be able to trivially update all the callsites to remove the arguments without side effects (think about method invocation passed as argument, with say ref/out params). We should still consider offering a code fix that updates all trivial cases (argument is a constant or a reference to a local/parameter/field which can be just removed), and leaves the original arguments as-is in non-trivial case with a warning annotation in fix.

**Comment by mavasani** [comment]
@jinujoseph

**Comment by KirillOsenkov** [comment]
We ran into the same issue: when hovering over inline light bulb it disappears when clicking on it. Ctrl+. pops up the menu to the side and correctly displays 5 menu items.

Repro:
1. Clone https://github.com/cobey/VSM2019_Productivity
2. In QuickActions.cs on line 10, hover over `a` in `int a`

![LightBulbDisappears2](https://user-images.githubusercontent.com/679326/58901575-5208f780-86b6-11e9-8623-54b8ff638a9f.gif)

**Comment by jinujoseph** [comment]
also asked [DC](https://developercommunity.visualstudio.com/content/problem/516042/suggestions-not-doing-anything.html)

**Comment by CyrusNajmabadi** [comment]
I don't repro this.
