### ISSUE TITLE
Use MSBuild Locator's AppDomainManager

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#36165]
Starting with #36113, AnalyzerRunner uses the AppDomainManager from [SourceBrowser](https://github.com/KirillOsenkov/SourceBrowser/) to work around https://github.com/Microsoft/MSBuildLocator/issues/16. Once MSBuild Locator ships its own copy of a custom AppDomainManager, the changes in commit fbc4b38f8d1de75163e10b5f8af07451d77a1d14 should be updated to use that version instead, and the references to SourceBrowser removed from dotnet/roslyn.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to do this, we should just have a milestone and do it.
