### ISSUE TITLE
Missing intellisense error and weird diagnostic when indexing ReadOnlyMemory<T>

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#36178]
**Version Used**: 
16.1.1, netcoreapp2.2, LangVersion=latest

**Steps to Reproduce**:

```csharp
public class C
{
    public void M()
    {
        System.ReadOnlyMemory<int> a = default;
        var b = a[0];
    }
}
```

**Expected Behavior**:
There should be an IntelliSense diagnostic and a compiler diagnostic that `ReadOnlyMemory<T>` doesn't have an indexer.

**Actual Behavior**:
There's no IntelliSense error, b is typed as `ReadOnlyMemory<int>`. When compiling, there's  diagnostic `CS0656: Missing compiler required member 'System.Range.get_Start'`.

It looks like some C# 8 features are leaking.

**Comment by jcouv** [comment]
Tagging @agocke

**Comment by agocke** [comment]
I believe this was fixed in https://github.com/dotnet/roslyn/pull/35170

I can no longer repro this in 16.2 Preview
