### ISSUE TITLE
`this` not recommended between parens in incomplete code

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#36194]
```csharp
        public void something()
        {
            int z = (t$$)
            object o = new object();
        }
```

`this` is not recommended at the caret. It is recommended if I add a semicolon at the end of the line.

**Comment by rchande** [comment]
Originally filed at https://github.com/OmniSharp/omnisharp-vscode/issues/3096

**Comment by CyrusNajmabadi** [comment]
That's due to this being parsed as a cast.   And hte value of limiting what's in the parens to just types outweighs the negatives of offering all possible symbols/exprs in the normal cast case.  

We could consider trying to tweak things literally if there is a newline following the `)`.

**Comment by CyrusNajmabadi** [comment]
Not repro:

![image](https://user-images.githubusercontent.com/4564579/218175086-ca405ed9-bb13-4c17-827d-1b1d283356a8.png)

And i checked that this is because we now special case this:

![image](https://user-images.githubusercontent.com/4564579/218175144-06ed4c26-0f07-4d59-a5c2-4a279f516cda.png)
