### ISSUE TITLE
C# Completion doesn't list 'assembly' keyword  for TypeForwardedTo attribute

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#362]
Ported from TFS WorkItem: **529860**

---

**Repro Steps:**
1. Create a new C# library.
2. Surround any existing classes with a namespace, if they're not already there.
3. Start typing an attribute before the namespace.

**ACTUAL RESULT**

Completion list doesn't apear as I type [assembly] keyword

**EXPECTED RESULT**

`assembly` keyword should have been recommended

---

3) Edited By Jason Malinowski (11/28/2012 7:33:06 PM)

This is being caused by poor parser recovery. If it's before a class or anything else, the parser will start to parse it as a attribute. But if it's before a namespace, it gives up and just skips the [ token.

(TFS Integration from 'DevdivProjects-Roslyn' Id: 14628 (rev 3);)

---

11) Edited By Kevin Pilch-Bisson (5/1/2014 9:00:18 AM)

The request is that when you have:

``` cs

[

namespace Foo
```

or 

``` cs
[]

namespace Foo
```

or

``` cs
[a]

namespace Foo
```

For the parser to treat the [ (and subsequent) tokens as part of an attribute with a missing name, instead of just skipping them entirely.

**Comment by ivanbasov** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/29094
