### ISSUE TITLE
Visual Studio/Visual Basic debugger won't show the values of members of a structure on mouse hover when they're inside "with / end with" statements

### ISSUE THREAD

**Issue by Felcat** [dotnet/roslyn#36208]
**Version Used**: Visual Studio 2017 / Visual Basic

**Steps to Reproduce**:

1. Create a structure. For example:
```
Public Structure Test
  Public SubVar_A As Byte
  Public SubVar_B As Byte          
End Structure
```

2. Create an object with that structure. For example:
`Public TestObject As Test`

3. Use a "with / end with" statement to access the members of TestObject. For example:
```
with TestObject
  .SubVar_A=10
  .SubVar_B=20
end with
```

4. Place a debug breakpoint at .SubVar_B=20, run the program, and once execution stops at the breakpoint hover the mouse over .SubVar_A or .SubVar_B to see their values. Nothing will show. Even if you add them to the Watch list, their values won't show. If, however, you don't use "with / end with" statements, and instead use "TestObject.SubVar_A=10", hovering the mouse over it will show the value when debugging.

**Expected Behavior**: It was expected that hovering the mouse over .SubVar_A or .SubVar_B would show their values when debugging.

**Actual Behavior**: The values won't show.

**Comment by jcouv** [comment]
Tagging @ivanbasov @tmat for triage/routing

**Comment by tmat** [comment]
Seems like an issue in VB EE.

**Comment by Felcat** [comment]
Some Facebook group members (Visual Basic group) informed me that it also doesn't work on Visual Studio 2019.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback ansd us not likely to touch these experiences.
