### ISSUE TITLE
[loc][Query][Roslyn] Localizability of the "cmdidCSharpOrganizeSortUsings"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#36204]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
SortUsings

ID:
0; "cmdidCSharpOrganizeSortUsings"

File Name:
VisualStudio\Core\Def\xlf\Commands.vsct.xlf

==========================================
Query:
Please confirm if this string can be translated

**Comment by JoeRobich** [comment]
@PDostalek This string is a LocCanonicalName and does not need to be translated.
