### ISSUE TITLE
Useless overload resolution error when using static class as generic type argument

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#36203]
**Version Used**: 

Visual Studio 2019 Enterprise v16.1

**Steps to Reproduce**:

Try and compile this code:

```csharp
using System.IO;

public class Serializer
{
    public static object Deserialize<T>(Stream s) => throw null;
    public static object Deserialize<T>(TextReader tr) => throw null;
}

public static class IShouldNotBeUsed { }

public class Victim
{
    public object Foo(Stream s)
    {
     	return Serializer.Deserialize<IShouldNotBeUsed>(s);
    }
    
    public object Bar(TextReader tr)
    {
     	return Serializer.Deserialize<IShouldNotBeUsed>(tr);
    }
}
```

**Expected Behavior**:

An error message warning that I am trying to use a static class as a generic type argument.

**Actual Behavior**:

error CS1503: Argument 1: cannot convert from 'System.IO.Stream' to 'System.IO.TextReader'
error CS1503: Argument 1: cannot convert from 'System.IO.TextReader' to 'System.IO.Stream'

**Notes**:

If I assign the result of `Deserialize<>` to a local variable, instead of returning it, I get [CS0723](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0723).

Sharplab playground [here](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8kAmIA1AD4ACADAATkCMAdAJIDyA3ALABQ35AzLQBM1AMpYIAG0wAvRNwDe3astoD6ANmoB7YACs4AYxjUAInCjipsgDwAVAHwAKETARwIYalACU1ALz21DAAFghaAO7UAHYArhISnFwqqrR0mjr6RqbmljJwdk62cAAeMABK7gSIQQi+AUGhEdFxCdwAvty8amlC1EwiwVpxBAByWjAAQnAAqhYE1PLUHTxc/L0AaphGmGAKSiprGYbGAGJaWs6u7p4++8qKSckAkOQA7KK5sggMZhYImJI8tZ+oNhmNJjM5k4fIlkstkncUkcshMIAhHEVShUIFUEDVvIiHslqC93mJ/oCvj8chSrPkQUMJKNxlNZnACE5XN5YSplm0gA=).

**Comment by gafter** [comment]
When a type argument is given explicitly, we should prioritize an error about using a static type.

**Comment by nbalakin** [comment]
I'd like to grab the issue if there're no objections.

**Comment by nbalakin** [comment]
As I've figured out that should be fixed by adjusting order of diagnostics in ``OverloadResolutionResult`1.ReportDiagnostics`1`` and covering the case with some tests, shouldn't it?

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/37613

**Comment by yaakov-h** [comment]
Thanks!
