### ISSUE TITLE
IDE0059 wrong span for unused assignment

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#36202]
**Version Used**: 
3.1.0-beta4-19261-04

**Steps to Reproduce**:

```csharp
void StreamCopy (Stream source, Stream destination, int start, int length)
{
	var buffer = new byte[1024 * 8];
	var read = 0;
	var left = length;
	while ((read = source.Read (buffer, 0, Math.Min (left, buffer.Length))) != 0) {
		destination.Write (buffer, 0, read);
		left -= read;
	}
}
```

**Expected Behavior**:
`= 0` or `0` is highlighted as unused.

**Actual Behavior**:
<img width="314" alt="Screenshot 2019-06-06 at 08 28 50" src="https://user-images.githubusercontent.com/109974/59009148-24968800-8835-11e9-9f9a-7ab2c712107e.png">

We can see the analyzer knows what's redundant here:
<img width="331" alt="Screenshot 2019-06-06 at 08 26 15" src="https://user-images.githubusercontent.com/109974/59009157-2d875980-8835-11e9-82ed-62efa6b3cb0a.png">

**Comment by Youssef1313** [comment]
This is by-design based on https://github.com/dotnet/roslyn/issues/47784#issuecomment-694316471.

**Comment by CyrusNajmabadi** [comment]
Closing out as by-design based on @mavasani's post.
