### ISSUE TITLE
New class templates should have using directives inside the namespace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36214]
VSF_TYPE_MARKDOWNMany people use ReSharper or StyleCop. Those have a rule enabled by default that the using directives should be inside the namespace declaration. It has been widely debated why that rule is recommended so it should be default for new classes in Visual Studio.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/593327/new-class-templates-should-have-using-directives-i.html
VSTS ticketId: 904651_
_These are the original issue comments:_

Jane Wu [MSFT] on 6/4/2019, 03:39 AM (2 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by davkean** [comment]
This of course should respect the setting called out here: https://github.com/dotnet/roslyn/pull/35009.

**Comment by canton7** [comment]
The discussion in #27186 looks relevant - the issue is specifically about responding .editorconfig settings around accessibility modifiers in templates, but the discussion is around any .editorconfig settings.
