### ISSUE TITLE
Tuple Declaration Hiding

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36211]
VSF_TYPE_MARKDOWNNew code editor suggestion. I love Tuples but they elongate the method declaration. The suggestion is to allow a toggle to collapse them. For example...

```
private static (bool showHelp, bool deleteExistingFiles, string inputFolder, string outputFolder, bool pauseCommandWindow, List&lt;string&gt; Files) ProcessCommandLineArguments(string[] args)
```
... to something like this:

```
private static (tuple... ») ProcessCommandLineArguments(string[] args)
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/582406/tuple-declaration-hiding.html
VSTS ticketId: 899239_
_These are the original issue comments:_

Jane Wu [MSFT] on 5/27/2019, 01:08 AM (10 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out.  The language has approved https://github.com/dotnet/csharplang/issues/4284, which allows one to trivially alias large tuples.  That would be a simpler and cleaner way to allow the use of tuples, without large source overhead (and no runtime overhead at all).
