### ISSUE TITLE
Drag/Drop Using statement

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36213]
<p>Allow dragging a project reference to the using block of a C# file and have it automatically create the correct using statement for that reference.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/589391/dragdrop-using-statement.html
VSTS ticketId: 902201_
_These are the original issue comments:_

Jane Wu [MSFT] on 5/31/2019, 01:54 AM (6 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
