### ISSUE TITLE
Find All References on a method parameters from an interface is inconsistent to methods from an interface

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#36227]
Given the following code:

```
    public interface I
    {
        void M(string param);
    }

    public class C : I
    {
        public void M(string param)
        {
        }

        public void M1()
        {
            M(param: "zz");
        }
    }

    public class D
    {
        public void M2()
        {
            new C().M(param: "zz");
        }

        public void M3(I i)
        {
            i.M(param: "zz");
        }
    }
```

If I invoke Find All References on any `M`, be it call, definition, or concrete implementation, I get the same 3 results covering C.M and I.M. 

Invoking FAR on `param` is inconsistent with this: Invoking it on the implementation (ie, in C.M) returns the 2 calls to the concrete implementation only (ie, calls in M1 and M2) and invoking it on the definition or the interface call, returns only 1 reference to the interface call in M3.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
