### ISSUE TITLE
Rename does not correctly cascade between linked, colocated classes (and other types of members)

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#3623]
1. Create a shared project and add a class.
2. Create 2 console applications and add references to the shared project from both console apps such that the shared file in shared project has atleast 2 heads.
3. Rename the class in shared file via rename tracking and notice the diff preview

**Actual**: Changes before (highlighted in red) and changes after (green highlight) the refactoring are swapped.

**Screenshot**:
![image](https://cloud.githubusercontent.com/assets/4213867/8291380/0e77f1a0-18de-11e5-8521-bd71480df067.png)

**Comment by balajikris** [comment]
Notes: If it has only one head instead of two, this would show "no preview" since there are no other locations that need to be updated.

**Comment by dpoeschl** [comment]
The rename engine itself is broken in this case. RenameLocationSet.ReferenceProcessing.ShouldIncludeSymbolAsync incorrectly rejects the NamedType that the LinkedFileReferenceFinder cascades to. That method should probably be an exclusion list instead of an inclusion list.
