### ISSUE TITLE
Surround with messes the next line when whole lines are selected

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36243]
VSF_TYPE_MARKDOWN1. Start with the following code:

```C#
namespace SurroundWith
{
    using System;

class Program
    {
        static void Main(string[] args)
        {
            var a = MayFail();
        }

static int MayFail()
        {
            return (new Random()). Next(2) == 0 ? 42 : throw new Exception(&quot;nope&quot;);
        }
    }
}
```

2. Select the whole `var a = MayFail();` line: put the cursor at the start of the line and press Shift+Down arrow.
3. Go to Edit -&gt; IntelliSense -&gt; Surround With, select `try` in the &quot;surround with&quot; menu;
4. Notice that the closing brace for the `Main` function is now on the same line as the closing brace for the `catch` statement and separated by a bunch of spaces.

I expect not to have my braces messed up as a result of using that feature.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/588197/surround-with-messes-the-next-line-when-whole-line.html
VSTS ticketId: 901370_
_These are the original issue comments:_

Visual Studio Feedback System on 5/29/2019, 07:37 PM (8 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Vatsalya Agrawal [MSFT] on 6/7/2019, 09:34 AM (90 min ago): <p>Thank you for providing feedback, and we're sorry to hear it's not behaving as you expect. Based on your description so far, we were unable to reproduce the issue. Brace alignment in the latest preview is working as expected when we executed the repro steps. Could you please upgrade to latest preview and try again.</p><p><br></p><p>If the problem persists, please provide a sample project where this issue is occurring.</p>

Andrei Grigorev [MSFT] on 6/7/2019, 10:06 AM (59 min ago): <p>Yes, it still reproduces in the latest preview and it reproduces in *any* project, you don't need any specific one for that. To reproduce you *must* follow the step 2 to the point. The selection must happen top to bottom and include the line break. The cursor must end up on the next line. See the screenshot.</p><p><img src="https://developercommunity.visualstudio.com/storage/temp/77596-vs-selection.png"></p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in legacy snippets.
