### ISSUE TITLE
Missing possible dereference of null reference warning for range / index from end access to nullable strings

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#36241]
**Version Used**: 

```
Branch master (22 May 2019)
Latest commit 04252e by Neal Gafter:
Unskip passing tests. (#35856)

Fixes #35611
```

**Steps to Reproduce**:

Compile and run the following code:
```cs
#nullable enable
class C
{
  static void Main()
  {
    M1(null);
    M2(null);
  }

  static void M1(string? s)
  {
    _ = s[^1];
  }
  
  static void M2(string? s)
  {
    _ = s[1..10];
  }
}
```

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWACgABAJgoGFGBvRiipgIwA2fgBYKAWQgBLXAAoAlLwo8GfPhIFyCxBQG5lGltqKF9ygL6NlgkU3Ga5ggAwB+ClCVqVhigH0KAF4PAG0APQEAXQNvK28bYTFJYxd3T2VVdX8g0IEAOjyBZ2jLRjjGGjA4KAAHCABjSkFuXyZnfnyAJXxcGGkqvPYAezAa6XIEAGVEADdpRqgY1oBmCgQ4CBQh3EIATw8YBHx6mApOiFwAczhfTKz1JlWASVwUOAAPCkmYCARTrgo1xgego5W8934z1eHwoAFFXipAXBgaDrOD7o8zhdrnIXm9PrBfjAkBQ8TDqCgvBC+HdqepvkScoS/jE6Vl4SgchTWdSwXTMbYsVdKAy/gBBGC46EEn5/BRBAB8FFwcAA7kKccziaTpXkOeYGL4sgLEudhXDXhKpfiqK95YElSr1WacWT3nlRdqKQajQ9VoKXZQxcRFcq1Rq4NaPh7Zdq3Xq7Ut0VkQhJkQALIYoJ6jQhyNMwTPZ3MAeRqfW2UDyYsul3WUCg0hmcBehFkskuCkivr4mJLADN+1BkWLXgAZaiXQsUADiyIHQ5H48nhbkslO5Cuhap1NpbPXByJPLZOptWrdOU9x/3/YocnPuqeUAAYggRvqe2ytTlN1P0xQAFpDz+eMADUIEIfA4GvOk4EIYdPzpb9ggffE8nAyDoLRE8+APblEPUC8KQvYIORg6lpFvORiMfF83zAD9kxwikfxXf8gJotCMKg8iITghCmJPFjgk46NuKww1BPuSi7zkfB1wUFilTkhTf2nTBMDveTegUb9lO0mBFLtAiaRM+5CzfdUnQoMUEEufAql6Et8BgAdA1hd5GnLaRtkUXj7j5HCmAAdjDdUF2HGBRxQCct3Te9YxJFigK1A06UCiFMXWTZtj2A4jhOCgIqXGK2M/Pd+VWA9iv+JEUTiHDIQoA9Yr/REgRBDK2T7QdIui1rVwPIZeuREkDzU9MdxPCqcJqnJhsXYEzKyAb/2CCb/KyLrKqSAAROB6krQ5jklIYXOa3oKAWyKSTO05xrYqa2Rmk9ruRHIas26kJpyVavr4BreV8OIwTRSpqjqRoOhadE2g6PJul6fo4EGEYxgmaYEDmBZryyjYth2fZYAK04LxAUlYQAR3wCAfjIOAAB43QVW5PxqBAm1pyhsoJvKDz8GYIJ47DqVTDMsxzGo8wLItJcIMsK1wKsazrapG2bVt2yuLtP0xN010uwXMJJYAhiGQgKH7eiORyfsIOHJ6she6SqKNqCKAZihnEd3dlvUCyhis8NbPsxzXJctzsTgDyvMVvyzO2iiqKt99jKkukBaFyhggAPzdiTGv4m50+pTPMJyfP/MTvgAHoa4oAAVdNKH7c3CEDjsKHZzn4AoQ6leOk4hgQKAKEgWQ8vqbL4E5VuEC7xBb2yqBtgoGAhgoCB7DX5u++b+oAGsoDZjnBd7/WD3zn3TJLvgy/d4JK8/auKDr+uGagBzIAQXYFXYafKAXFPDCGoQx1yd1ppbaQI9ThwTgGHPIDMa6fzAN/X+ut/SJAvJ6UM1l9beyTHSN+HsUFoL/gAzeuBgGfFAeAq4m9TjADgLsbYnISCwCoOQBBSDSG/HQVJE0IgLw2wdGFahcgc4EJFhCMWhYJa5nzOLYsUsFY+SVtWWs9Z1Yth2FrTs3YBGYKEdKCgr4RiegNqcK+5UzIyTkPnD2Xtr73GdnSAOQd1QhwctQcOrl+zuU8nAbyvk0o4RfsaUKeDpT2KzqEiEL9ZGywUTLeRKjgnqJVlopsOi2y4A7DrQxHRjE2jMQxV4liKDWKkq49QdiHGe29mZGpEJ3FiK8WHZyfiAmxzUfHW+qJJKNRCmI/WedYlV2kfcYhH8v58IVJ0ZE+AEBKx3pQWQNp86IOQbMn+LNCkHnEjY/pQIml+1wlRe+lAGnOKGaFHOlz/r3CLmcjEoUHkJ2fpM40qxTbm1JHRVOnJRGXMcc4QhosUnKOlkouWqjKwaNVg2bJms8nawMTtA8c4/GLQqRNZxzSLqnDektQZOE7FPlKYxRqWRiWsTioBO89yr6POef0mlI1TjBHeaSk8wziUTJ5RiVYQxmwIA5m8CgvyLZUxpvBOQQxgAACsDpWNiaGBx0hR4XgAGTav8A4wIwQ5BRneAoK+eRuUYMlWbaV1N7Z3gvEMQsiB7RKhBYaq6zqEAWqfoK75V1RXirWZdLFAAJaA6ZhhvEUKGS1hTBT9ClvMaQRKaiIFpsPcRl81WiNKRY5lwMyhAA

**Expected Behavior**:
Warnings for possible dereference of a null reference for both `s[^1]` and `s[1..10]` since they access the string without checking it for null via `.Length` and `.Substring` respectively.

**Actual Behavior**:
No warnings. Both expressions crash with a `NullReferenceException` at runtime.

**Comment by jcouv** [comment]
Tagging @agocke
