### ISSUE TITLE
IntelliSense suggests name that does not match convention

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#36248]
**Version Used**: Visual Studio 2019 version 16.2 Preview 1

**Steps to Reproduce**:

1. Open Roslyn.sln
2. Type `CancellationToken` and press <kbd>Space</kbd> in a parameter list

**Expected Behavior**:

Naming suggestions:

* cancellationToken
* cancellation
* token

**Actual Behavior**:

Naming suggestions:

* cancellationToken
* cancellation
* token
* CancellationToken
* Cancellation
* Token

**Comment by weitzhandler** [comment]
Can't reproduce:

![image](https://user-images.githubusercontent.com/2716316/95002067-ce785700-05d8-11eb-9d92-637d83ace277.png)

**Comment by Youssef1313** [comment]
@sharwell Are you still able to reproduce this?

**Comment by sharwell** [comment]
> @sharwell Are you still able to reproduce this?

Yes I hit it a few times today.

**Comment by sharwell** [comment]
The problem occurs because we have this line:

https://github.com/dotnet/roslyn/blob/b1fc87ffccd860b2af1796ee18f0683c3e97f1dc/.editorconfig#L140

It shouldn't be necessary to inline the entire set but leave out `parameter` because the naming for parameter is already controlled by a rule with higher priority.
