### ISSUE TITLE
No associated IFieldSymbol is provided for a field-like event

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#36259]
If you create a compilation with the following syntax:

```cs
public class Foo
{
    public int X { get; }

    private event EventHandler Y;
}
```

And you get the ITypeSymbol for the type declaration from the symbolic model, it contains an IFieldSymbol representing the backing field for the property but none for the backing field of the event:

![](https://files.gitter.im/dotnet/roslyn/m0CW/image.png)

Why is an associated IFieldSymbol surfaced for an autoprop but not an auto event?
Is there any chance that an associated IFieldSymbol might not be surfaced for an autoprop in some circumstances if I got the containing ITypeSymbol from a TypeDeclarationSyntax? 

@CyrusNajmabadi reproduced this and asked me to file since this doesn't seem right to him.

https://github.com/dotnet/roslyn/blob/611578d74c11a34da7142f6d62dbb9f0610c4cec/src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs#L17-L24

https://github.com/dotnet/roslyn/blob/611578d74c11a34da7142f6d62dbb9f0610c4cec/src/Compilers/CSharp/Portable/Symbols/Source/SourceFieldLikeEventSymbol.cs#L74-L80

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv and @gafter

**Comment by JohanLarsson** [comment]
Also `AssociatedField` on `SourceFieldLikeEventSymbol` is internal and hence not exposed in `IEventSymbol`.

http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/Source/SourceFieldLikeEventSymbol.cs,114

**Comment by jnm2** [comment]
Made steady progress with https://github.com/dotnet/roslyn/compare/master...jnm2:event_field_symbol (7.5 hours in). Only a few tests still failing.

**Comment by jnm2** [comment]
TODO: 

- [ ] Correct this false statement (C# event-like backing fields are generated as public by Roslyn) and add tests showing that IFieldSymbols are provided as expected from metadata as well as source

   https://github.com/dotnet/roslyn/blob/ec16eac1529da146dd29e222c4bef42fe9d2f5e0/src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs#L1737-L1744

- [ ] Fix remaining tests (7)

**Comment by jnm2** [comment]
15 hours in, PR is up at https://github.com/dotnet/roslyn/pull/40572.

**Comment by jnm2** [comment]
My original use case: https://gitter.im/dotnet/roslyn/archives/2019/06/07?at=5cfb12aa3dcdab40030b066c

Another use case: https://github.com/DotNetAnalyzers/ReflectionAnalyzers/issues/206

**Comment by jnm2** [comment]
After discussion in #40572, closing in favor of https://github.com/dotnet/roslyn/issues/40103.
