### ISSUE TITLE
System.MissingMethodException 

### ISSUE THREAD

**Issue by jerrydx** [dotnet/roslyn#36260]
Hello,

I have a small problem. I am using ROSLYN compiler and tried to invoke RoslynTest.ComputeClass.Compute method, but I got run-time error "System.MissingMethodException: 'Method RoslynTest.ComputeClass.Compute was not found.' The method is in short code in variable g_code in RoslynTest.RoslynInterface.InitCompiler and complette source code in MS VS 2019 is here:

https://drive.google.com/file/d/1TRKshJhApC2ByC961I9f__axjTyGCdnm/view?usp=sharing

and also in in text below. The problem is caused thanks to array-type variable passing to method in 

InvokeCode(ref MyData[,] t_array )

if simple variable e.g. Int32 A is used instead of "MyData[,] t_array" no "MissingMethodException" arose.

Can someone help me where is problem ?

Problem describtion is also here:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/693c34e2-ae7f-4a7c-8de7-4a01012dc396/roslyn-systemmissingmethodexception?forum=csharpgeneral

Many thanks

Jerry

**Comment by gafter** [comment]
You have two different incompatible types called `MyData`: one in the calling program and one in the compiled code.  They are incompatible.
