### ISSUE TITLE
EnC: Changing the type of an expression around an active foreach statement should be a rude edit

### ISSUE THREAD

**Issue by wschae** [dotnet/roslyn#3627]
1. C# App:
```C#
   class Program
   {
       static void Main(string[] args)
       {
           var b = new int[] { 1, 2, 3 };
           foreach (var a in b)
           {
               Console.WriteLine(a); // Add a breakpoint here
           }
       }
   }
```
2. F5 to stop at the breakpoint
3. Update "int[]" to "double[]" of type of b
4. Continue

Expected: Rude edit saying "cannot edit foreach around an active statement"

Actual: NullReferenceException when stepping into the next iteration of the loop

![6](https://cloud.githubusercontent.com/assets/4300700/8292219/41844c4c-18e3-11e5-9986-859758e16ef7.png)

**Comment by wschae** [comment]
Ported from internal bug 1009555

**Comment by wschae** [comment]
Check also 781309 - EnC: Report warning (that local value will be dropped) if local type has changed

**Comment by amcasey** [comment]
Assigning to @drognanar (fyi @tmat).

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/74526
