### ISSUE TITLE
VS 16.1.2 - Suppress In Source Pragma Restore Statement On Wrong Line

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36281]
VSF_TYPE_MARKDOWNWhen I use 'Suppress in source' on the `return` line in the following code: 
```
public class Class
{
    public void Test()
    {
        if (1 == 2)
        {
            return; /// &lt;see cref=&quot;Class&quot;/&gt;
        }
    }
}
```

The `pragma warning restore` line is put after the closing brace of the if statement.
```
public class Class
{
    public void Test()
    {
        if (1 == 2)
        {
#pragma warning disable CS0162 // Unreachable code detected
            return; /// &lt;see cref=&quot;Class&quot;/&gt;
        }
#pragma warning restore CS0162 // Unreachable code detected
    }
}
```

Shouldn't it be directly after the return statement?
```
public class Class
{
    public void Test()
    {
        if (1 == 2)
        {
#pragma warning disable CS0162 // Unreachable code detected
            return; /// &lt;see cref=&quot;Class&quot;/&gt;
#pragma warning restore CS0162 // Unreachable code detected
        }
    }
}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/599633/vs-1612-suppress-in-source-pragma-restore-statemen.html
VSTS ticketId: 911721_
_These are the original issue comments:_

Visual Studio Feedback System on 6/10/2019, 02:33 AM (8 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 6/10/2019, 10:54 AM (95 sec ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by mavasani** [comment]
Reported here: https://developercommunity.visualstudio.com/content/problem/599633/vs-1612-suppress-in-source-pragma-restore-statemen.html

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
