### ISSUE TITLE
C# regression test infrastructure: false failure on unit test PreprocessorInsideInterpolation

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#363]
The unit test `PreprocessorInsideInterpolation` fails due to bugs in

```cs
public static TCompilation DiagnosticExtensions.VerifyDiagnostics<TCompilation>(this TCompilation c, params DiagnosticDescription[] expected)
where TCompilation : Compilation
```

**Comment by theoy** [comment]
Let's try to get our tests clean.

**Comment by davkean** [comment]
Untagging infrastructure, this is test bug in the compiler.

**Comment by jaredpar** [comment]
Closing.  This test is enabled, has been for quite some time, and we haven't seen any recent failures.
