### ISSUE TITLE
[Proposal] Add support of lazy initialization.

### ISSUE THREAD

**Issue by kboryshpol** [dotnet/roslyn#3630]
Native support of lazy initialization will allow to simplify a code.
In current notation:

``` c#
private Something _somethingValue;

public Something SomethingValue
{
    get { return _somethingValue ?? (_somethingValue = LoadSomething()); }
}
```

Suggested:

``` c#
public lazy Something SomethingValue => LoadSomething();
```

**Comment by ljw1004** [comment]
For completeness, here's the idiom in VB code today:

```vb
ReadOnly Property p As String
    Get
        Static Dim _p As String = LoadSomething() : Return _p
    End Get
End Property
```

**Comment by tmat** [comment]
@kboryshpol The above patterns are actually incorrect in multi-threaded environment, unless Something is immutable and its object identity is not significant. Also the exception handling semantics may depend on your needs.

So it's better to either use Lazy<T> like so:
```C#
private Lazy<Something> _lazySomething = new Lazy<Something>(LoadSomething);
public Something SomethingValue => _lazySomething.Value;
```

or Interlocked:
```C#
private Something _somethingValue;

public Something SomethingValue
{
    if (_somethingValue == null)
    {
       Interlocked.CompareExchange(ref _somethingValue, LoadSomething(), null) 
    }
    return _somethingValue;
}
```

The problem of having "lazy" in the language is that the compiler doesn't know what semantics do you actually need. So we would need some way to specify that. Which makes it rather complex.

**Comment by ljw1004** [comment]
Clarification: the VB pattern *is thread-safe*, because that's how the "Static Dim" feature works...

**Comment by tmat** [comment]
@ljw1004 Yes, it is. I have corrected my comment :) However I'd not recommend using VB static locals either if performance is a concern. It's rather inefficient - an initialization allocates additional object which makes the containing type larger and every access takes a lock.

**Comment by svick** [comment]
Some similar proposals: #3415, #3251, #524.

**Comment by pharring** [comment]
```System.Threading.LazyInitializer.EnsureInitialized<T>``` simplifies some of this:

```C#
private Something _somethingValue;

public Something SomethingValue
{
    return LazyInitializer.EnsureInitialized(ref _somethingValue, LoadSomething); 
}
```
But I agree it would be nice to have a compact syntax for this (hide the backing field and the call to EnsureInitialized)

**Comment by kboryshpol** [comment]
@pharring I'm agree with you. That's accurate implementation.

**Comment by pharring** [comment]
Of course, there are limitations:
* ```Something``` must be a reference type where ```null``` indicates the uninitialized state.
* LoadSomething must be safe to call concurrently on multiple threads and should be free of side-effects.
* LoadSomething should never return null
* LoadSomething should not call back into code that may result in a nested call to SomethingValue

And I'm sure there are more I haven't thought of.

**Comment by whoisj** [comment]
> Something must be a reference type where null indicates the uninitialized state.
LoadSomething must be safe to call concurrently on multiple threads and should be free of side-effects.
LoadSomething should never return null
LoadSomething should not call back into code that may result in a nested call to SomethingValue

How often is this ever true though?

Usually, when I'm loading something lazily it is coming from an expensive resource (network, disk, etc) and I really do not want multiple threads utilizing the resource.

**Comment by HaloFour** [comment]
You'd probably want to use one of the expanded versions if that was the case, e.g.:

```cs
public readonly lazy int Foo => CalculateFoo();
```

would expand to:

```cs
private readonly object _sync = new object();

private int _foo_value;
private boolean _foo_initialized;

public readonly int Foo { get; } = LazyInitializer.EnsureInitialized(ref _foo_value, ref _foo_initialized, ref _sync);
```

That would take care of value types and thread-safety.

**Comment by whoisj** [comment]
@HaloFour :heart_eyes:

**Comment by gafter** [comment]
@ljw1004 It looks like your VB idiom uses the same value for the property for all instances of the enclosing class. The requested feature has a cache that is separate for each instance. The equivalent VB idiom is about the same as the C# idiom.

**Comment by ljw1004** [comment]
@gafter no it doesn't! The VB "static dim" keyword doesn't share storage between instances of the enclosing class! (look at the codegen... the backing fields for the "static dim" are instance fields, not shared fields)

**Comment by gafter** [comment]
Oh, I see. Thanks!

**Comment by gafter** [comment]
@ljw1004 So if I understand correctly, VB already has direct support for lazy initialization in a form that would satisfy this C# feature request.

**Comment by ljw1004** [comment]
@gafter yes that was my intention in writing it. I think VB has half-way-okay support for lazy initialization (it's not as terse as what we'll come up with for C#, and not as efficient). But half way is still okay, okay enough to not warrant additional language support.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
