### ISSUE TITLE
Leave selection unchanged when applying ToggleLineComment

### ISSUE THREAD

**Issue by justcla** [dotnet/roslyn#36349]
When user applies ToggleLineComment to a selection, can the selection be left untouched?

--------------------------------------------
#27198 (comment)

Really nice to see this in Visual Studio 16.1!!

Obviously, it will be better when applied to a single-key shortcut instead of a chord.

Also, the changing of caret position and selection is really annoying. It keeps moving my caret to the end of the line, which is not helpful.

Notes:

For ToggleLineComment applied to a single line with no selection, it would be more useful if it moved the caret down one line. (And keep the caret at the same column position)
This could be a setting in Tools->Options (on by default)
Leave the caret where it started. When applying ToggleLineComment there is no need for the selection to change. Also, there is no need for the caret to move. It can stay where it was. Just need to apply comment markers to the start of each line involved in the selection. (Except for the last line if caret at posn 0).

**Comment by dibarbet** [comment]
> Obviously, it will be better when applied to a single-key shortcut instead of a chord.

This was do to limitations imposed by existing shortcuts.  Feel free to rebind them however you wish though!



> When user applies ToggleLineComment to a selection, can the selection be left untouched?

I think I understand this request, but for clarity -
The current behavior is to select the entire line that has been commented.  This of course moves the caret to the end of the line as the last bit of the selection.
The request is to instead leave the selection wherever it was before the command was invoked.
For example, invoking on a selection ([| |])

```csharp
string [|someString|] = "hello"
```
would not change the selection and result in

```csharp
//string [|someString|] = "hello"
```
Is this right?
How would this work with the request in https://github.com/dotnet/roslyn/issues/36351 ?  I guess this would only apply when there is a selection with an actual length (not just a caret)?

**Comment by justcla** [comment]
Yes. That is correct.

I define a "selection" in this context to be a non-zero length selection.
When there is no selection (or zero-length selection), #36351 would apply.

**Comment by dibarbet** [comment]
Hmm I'm not really opposed to this one, even if we leave the selection where it's at in the line, it will still function as a toggle.  And it would be perhaps even more useful in the uncomment case where you could just do something like this - 
```csharp
//string [|someString|] = "hello";
```
Toggle line comment, then you already have the var name selected where you could then modify it.  I think it makes sense.
