### ISSUE TITLE
Future enhancements for code actions to configure code style options and diagnostic severity in editorconfig

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#36348]
1. [Bug Fix] Expand the editorconfig updater to handle per-file sections. See 
https://github.com/dotnet/roslyn/pull/35691#discussion_r291290905
2. [Feature] change the default scope to Sln

3. [Feature] Potentially Codecleanup UI to show all possible options that's applied on the doc. Add code action to fill an existing editorconfig or generate a new editorconfig with all the missing code style settings

6.  [Feature] Add code action to fill an existing editorconfig or generate a new editorconfig with all the effective diagnostic ID and severity entries for all the analyzers executing on the project (built in and third party).

3. [Feature]  Possibly add FixAll support to enable customized discovery of editorconfig to update. The default behavior finds the closest editorconfig to the source file with the diagnostic walking up the ancestor directories upto the project directory, and creating a new editorconfig in the project directory if none exist. We may likely want to allow users to customize this to always walk up to the project or solution level editorconfig (updating all intermediate editorconfigs on the path up the ancestor directories).

4. [Skip] Original implementation only updates the code style option/severity in the editorconfig in the sources, but does not update the Workspace wide options or severities. We may want to expose an option to control whether the code action should also update the Workspace wide settings.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
