### ISSUE TITLE
Leave caret unchanged when applying ToggleBlockComment

### ISSUE THREAD

**Issue by justcla** [dotnet/roslyn#36350]
When applying ToggleBlockComment, can the caret stay to the right of the character it was previously to the right of?

(See #27198)

**Comment by dibarbet** [comment]
Want to make sure I understand the request.  Is this for the case when there is no selection?  How I understand the request currently is as follows
Note - caret position is indicated by $$
```csharp
class Program
    {
        void M()
        {
            stri$$ng someVar = "hello";
        }
    }
```
I invoke toggle block comment on the selection and get this
Note - selection is defined by [| |]
```csharp
class Program
    {
        void M()
        {
            string[|/**/|] someVar = "hello";
        }
    }
```
Are you requesting that instead the caret position be left in the middle of string?  If not, could you provide an example so I could better understand?
Thanks!

**Comment by justcla** [comment]
Yes, I am request the caret remain in the middle of the string. That enables a user to continue typing from where they were - without having to reset the caret position.

Regarding selection, it could go a few ways.
My first thoughts are - whatever was previously selected remains selected. (That would mean NOT selecting the /* and */ markers). Again, so that whatever the user had in selection is still there. They can type over it, or copy/cut it, find matches, etc.
But I'm not sold on that. There might be cases where it makes sense to expand the selection to include the block comment markers. But I can't think of any right now.

Regardless, the caret can remain exactly where it previously was (yes - this could inside a selection)

**Comment by dibarbet** [comment]
I can definitely see the use case for leaving the caret where it's at - it would make it easier to keep editing if we didn't move the caret.  

The problem I have though is that it seems to break the 'contract' of the toggle command, in that invoking it multiple times sequentially would no longer toggle the comment, it would only add.

**Comment by dibarbet** [comment]
I'm going to take these as a batch for design review - would like to see what the team here thinks.

**Comment by justcla** [comment]
Ah, yes, of course. Good point. The comment makers MUST be included in the selection to enable the ability to toggle the block comment off again.

That being said, it would best of the selection grows to include the block comments, but the caret remains unchanged. That would mean the caret is inside the selection - target than being at the start or end.

**Comment by CyrusNajmabadi** [comment]
Unlikely to change this due to lack of feedback.
