### ISSUE TITLE
Invalid 'for to foreach' refactoring

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#36354]
**Version Used**: 16.1.1

**Steps to Reproduce**:
```cs
        class Item { public string Value; }

        static void Test()
        {
            var first = new { list = new List<Item>() };
            var second = new { list = new List<Item>() };

            for (var i = 0; i < first.list.Count; i++)
            {
                first.list[i].Value = second.list[i].Value;
            }
        }
```

**Expected Behavior**: No suggestions

**Actual Behavior**: Suggests to convert to foreach anyways

![image](https://user-images.githubusercontent.com/3105979/59330388-945db480-8d06-11e9-8ac4-f24986d9ed0f.png)

**Comment by CyrusNajmabadi** [comment]
> Expected Behavior: No suggestions

@heejaechang @mavasani We have helpers that can tell if an expression is 'semantically equivalent'.  In this case, 'second.List[i]` should not be semantically equivalent to the list that's actually being iterated over.

**Comment by alrz** [comment]
Note: this was a fatal error for me since the resulting code was a complete blunder if overseen, not easily noticeable in legacy code.

**Comment by alrz** [comment]
> In this case, 'second.List[i]` should not be semantically equivalent

I guess we're actually checking symbols here, `list` points to the same member in both expressions. I think we should probably go with a simple syntax check..

**Comment by CyrusNajmabadi** [comment]
>I guess we're actually checking symbols here, list points to the same member in both expressions. I think we should probably go with a simple syntax check..

That's one of the things the "semantically equivalent" check does, fortunately.
