### ISSUE TITLE
You need to resolve types before naming suggestions for IEnumerable/collections work

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#36352]
Until you've resolved a type, you don't get useful suggestions:

Unresolved:
![image](https://user-images.githubusercontent.com/1103906/59322284-c546e500-8d18-11e9-9dbc-2b47d819d661.png)

Resolved:
![image](https://user-images.githubusercontent.com/1103906/59322270-b9f3b980-8d18-11e9-9465-4ca6755e8759.png)

Maybe this should be name based instead of type based?

**Comment by svick** [comment]
I'm not sure suggestions based purely on the name of the parameter type would work well here: what if the type is `List<T>`, or another type that implements `IEnumerable<T>`? AFAICT, you would get reasonable suggestions today, but not with a name-based approach.

Maybe some kind of hybrid approach could work?

**Comment by sharwell** [comment]
> Until you've resolved a type

This may be resolved by the new feature to automatically import namespaces.
