### ISSUE TITLE
Odd suggested parameter names in some cases

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#36364]
**Version Used**: VS 16.2.0 Preview 2.0

The suggested parameter names don't seem to be very good in some cases.

For `IEnumerable<string>`, the suggested name is `vs`, which does not make sense to me:

![](https://user-images.githubusercontent.com/287848/59351545-f0ccce00-8d1e-11e9-9105-26f22c5b4ca1.png)

For `IEnumerable<T>`, the suggested name is `ts`, which makes sense, but I think is almost never correct. Maybe it would make sense to have a special case for `T`?

![image](https://user-images.githubusercontent.com/287848/59351652-2ec9f200-8d1f-11e9-902e-b0a21b3fcf29.png)

**Comment by sharwell** [comment]
:memo: The expected name in the first case is `strings`. This should be tested against `String`, `object`, `Object`, and `int` as well.

**Comment by Youssef1313** [comment]
The current behavior is different, but is still incorrect.

![image](https://user-images.githubusercontent.com/31348972/103457440-0e4df800-4d08-11eb-86e6-a1df4c737fd9.png)
