### ISSUE TITLE
Roslyn-specific analyzer projects do not use meta-analyzers

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#3636]
That is, the RoslynDiagnosticAnalyzers project (and the related C#- and VB-specific projects) does not make use of Microsoft.CodeAnalysis.Analyzers. If they did, we wouldn't have run into #3626--the problem would have been caught ahead of time.

**Comment by mavasani** [comment]
@srivatsn This probably needs to move to the analyzers repo?

**Comment by srivatsn** [comment]
Ported to https://github.com/dotnet/roslyn-analyzers/issues/277
