### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.Source.UsingAliasTests.AliasWithAnError fails on Mac and Linux

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#3637]
The test was added in https://github.com/dotnet/roslyn/pull/3603.

http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_mac_prtest/1777/console
 Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.Source.UsingAliasTests.AliasWithAnError [FAIL]
      Assert.Equal() Failure\nExpected: ErrorType\nActual:   NamedType
      Stack Trace:
           at Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.Source.UsingAliasTests.AliasWithAnError () 

http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_linux_prtest/2544/console
Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.Source.UsingAliasTests.AliasWithAnError [FAIL]
      Assert.Equal() Failure\nExpected: ErrorType\nActual:   NamedType
      Stack Trace:
           at Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.Source.UsingAliasTests.AliasWithAnError ()

**Comment by jaredpar** [comment]
This will be fixed as a part of moving to #7138
