### ISSUE TITLE
Spaces in declaration statements

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36383]
VSF_TYPE_MARKDOWNGiven the following in .editorconfig:
csharp_space_around_declaration_statements = ignore
csharp_space_between_method_call_name_and_opening_parenthesis = false

In VS2010 'csharp_space_around_declaration_statements = ignore'  only affected the accessibility, type, and name -- it did not affect the initializer if one was specified. (.editorconfig was not supported in VS2010, but I'm writing about the equivalent Text Editor option.)

In VS2019 'csharp_space_around_declaration_statements = ignore' affects the whole statement - other spacing options (e.g. 'csharp_space_between_method_call_name_and_opening_parenthesis = false' are ignored)

Attached before.png shows is the original input.

Attached after.png shows that 'csharp_space_between_method_call_name_and_opening_parenthesis = false' is ignored in the declaration statements.

Changing the meaning of 'csharp_space_around_declaration_statements = ignore' is probably not doable as it would break existing formatting, but in the UI (Options/Text Editor/C#/Code Style/Formatting/Spacing/Ignore spaces in declaration statements) it would be good to have a sub-option to specify that the spaces are not ignored in the initializer.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/603361/spaces-in-declaration-statements.html
VSTS ticketId: 916945_
_These are the original issue comments:_

Visual Studio Feedback System on 6/12/2019, 00:02 AM (16 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by vatsalyaagrawal** [comment]
Tracking this as developer feedback ticket. Closing the git issue.

**Comment by LeeMSilver** [comment]
While this problem existed since at least VS2017 it has become much more prevalent due to the the problem that 31868 solved -- applying 'csharp_space_around_declaration_statements = ignore' to local declarations.

Local declarations are more prevalent and have initializers much more often than Field declarations. Therefore prior to 31868 this did not occur on Locals - but since then it occurs frequently on those declarations.

**Comment by LeeMSilver** [comment]
This was closed as VS issue 603361 for being moved here and here it's closed as "Tracking this as developer feedback ticket." I posted the problem NOT as feedback so I don't know what that means and I don't know how to track the status of this issue.
