### ISSUE TITLE
C#: Naming rule violation with camelCase formatting applied will conflict with static void Main() method inside classes.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36385]
<p>Steps to reproduce:</p><ol><li>Set the C# naming rules to allow camelCase naming applied everywhere, just to be able to get maximum coverage for debugging this issue. </li><li>Replace all PascalCase rules to camelCase rules.</li><li>Set all rules to throw errors, instead of giving suggestions.</li><li> Create a new C# file in a brand new C# project.</li><li> Create a simple Hello World program. </li><li> Observe how the camelCase naming rule violation do not give or provide exceptions to certain methods, like the Main() method, which requires the capital M.</li></ol><p><a href="https://developercommunity.visualstudio.com/storage/attachments/76052-capture.png"> Image:76052-capture.png</a></p><p>I would like to request a feature to the naming rules convention options, to allow exceptions for Main(). Since, in Visual Studio 2019, we have the option for users to give them custom naming rules, if we were to extremely apply our camelCase naming rules to C#, eventually, the &quot;Main()&quot; method will annoy the users.</p><p>Or maybe it could be fixed? I don't know at this point. Hence my feedback.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/588353/c-naming-rule-violation-with-camelcase-formatting.html
VSTS ticketId: 901455_
_These are the original issue comments:_

Visual Studio Feedback System on 5/29/2019, 07:03 PM (13 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
See https://github.com/dotnet/roslyn/issues/43677#issuecomment-623773701 for the design review conclusion.

**Comment by CyrusNajmabadi** [comment]
Closing out.  I don't repro this.  Naming style is not applied to the Main method of a program.
