### ISSUE TITLE
Change Signature reorder parameters should reorder InlineData arguments

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#36384]
**Version Used**: 16.2 Preview 2

**Steps to Reproduce**:

1. Create an xunit test theory with two parameters
2. Add test cases with `[InlineData]`
3. Use the Change Signature dialog to reverse the order of the two parameters

**Expected Behavior**:

The arguments to each of the `InlineData` attributes should be reversed.

**Actual Behavior**:

The arguments to `InlineData` are not reversed.

**Comment by sharwell** [comment]
Design review conclusion:

We would accept a pull request to hard-code knowledge of *this attribute*. If users start requesting additional cases, we can revisit the analyzer to find a more comprehensive way to address similar situations.

**Comment by CyrusNajmabadi** [comment]
closing out due to lack of feedback and complexity of solution.
