### ISSUE TITLE
Understanding roslyn

### ISSUE THREAD

**Issue by alxest** [dotnet/roslyn#3639]
I am familiar with LLVM compiler.
I want to compile C# code to LLVM IR.
I have read through roslyn overview. (https://github.com/dotnet/roslyn/wiki/Roslyn%20Overview)
However, I didn't get what each step's output is.
Does it parse and change original C# code to some IR and then optimize it, like LLVM?
If so, I want to get some information and language reference of it, to make a compiler from roslyn IR to LLVM IR.
Also, what is the final output of roslyn? It is written that "IL emitter" is the last phase, what exactly is that IL? Is it CIL(MSIL)?
Thank you.

**Comment by svick** [comment]
All Roslyn does is to compile C# (and VB) code to CIL (also known as MSIL, specified by ECMA-335). If you're interested in compiling CIL to LLVM IR, you should probably have a look at the existing [LLILC project](https://github.com/dotnet/llilc), which aims to do exactly that.

**Comment by alxest** [comment]
@svick Thank you very much!

**Comment by alxest** [comment]
@svick 
I followed build instructions and I found "Binaries/Debug/csc.exe" is created. This one compiles .cs file into .exe file and I found putting this as an input of Ildasm.exe gives me .il file.
Question is 
- All the build results of roslyn are .exe files in "Binaries/Debug" directory?
- Is it always possible to use "ildasm.exe" to get .il file? or is there another way?
Thank you.

**Comment by HaloFour** [comment]
@alxest As long as the binary (exe or dll) is pure IL then ildasm should be able to extract all of the metadata.  If the binary contains embedded resources they would also be exported as individual files, etc.  However if the binary is mixed and contains both IL and native code then ildasm will not be able to export the native methods.

The ECMA spec for CIL is [here](http://www.ecma-international.org/publications/standards/Ecma-335.htm), should be enough to get started reading the binary files.  The LLILC project is definitely where you'd want to be, though.  Roslyn is only one compiler of many that can potentially produce CIL.

**Comment by alxest** [comment]
@gafter Thanks a lot for your reply!
