### ISSUE TITLE
IPropertySymbol missing accessor

### ISSUE THREAD

**Issue by weltkante** [dotnet/roslyn#36403]
The Roslyn `SymbolInfo` and `IOperation` APIs of the SemanticModel return an IPropertySymbol missing the get-accessor even though the compiled code clearly was using a get-accessor.

(Related to #25057 and #26867, because Roslyn doesn't provide an API to get the Accessor against which it has compiled I'm trying to figure it out myself, but this fails when Roslyn compiles against a different property symbol than what it gives to my analyzer.)

**Version Used**: nuget stable 3.1.0

**Steps to Reproduce**
<details><summary>Source Code</summary>

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.Text;

namespace RoslynBindingBugTest
{
    class Program
    {
        static void Test()
        {
            var doc = new XmlDocument();
            doc.LoadXml("<root test='hi'/>");
            var text = doc.DocumentElement.Attributes["test"].InnerText;
            System.Diagnostics.Debug.Assert(text == "hi");
        }

        const string kSource = @"
using System;
using System.Xml;

class Program
{
    static void Main(String[] args)
    {
        var doc = new XmlDocument();
        doc.LoadXml(""<root test='hi'/>"");
        var text = doc.DocumentElement.Attributes[""test""].InnerText;
    }
}
";
        static void Main(string[] args)
        {
            Test(); // make sure it actually compiles & executes

            var ws = new AdhocWorkspace();
            var proj = ws.AddProject(ProjectInfo.Create(ProjectId.CreateNewId(), VersionStamp.Create(), "Test", "Test", LanguageNames.CSharp)
                .WithMetadataReferences(typeof(Program).Assembly.GetReferencedAssemblies().Select(x => MetadataReference.CreateFromFile(Assembly.Load(x.FullName).Location)))).Id;
            var doc = ws.AddDocument(proj, "Test.cs", SourceText.From(kSource)).Id;
            var cp = ws.CurrentSolution.GetProject(proj).GetCompilationAsync().Result;
            var diag = cp.GetDiagnostics();
            System.Diagnostics.Debug.Assert(diag.Length == 0);
            var model = cp.GetSemanticModel(ws.CurrentSolution.GetDocument(doc).GetSyntaxTreeAsync().Result);
            var access = model.SyntaxTree.GetRoot().DescendantNodes(x => !(x is MemberAccessExpressionSyntax)).OfType<MemberAccessExpressionSyntax>().Where(x => x.Name.ToString() == "InnerText").Single();
            var operation = model.GetOperation(access);
            var syminfo = model.GetSymbolInfo(access);
            System.Diagnostics.Debug.Assert(operation is IPropertyReferenceOperation propRefOp && propRefOp.Property.GetMethod != null);
            System.Diagnostics.Debug.Assert(syminfo.Symbol is IPropertySymbol propSym && propSym.GetMethod != null);
        }
    }
}
```
</details>

**Expected Behavior**:
Property symbol contains the get-accessor against which the program is compiled.

**Actual Behavior**:
Property symbol does not contain a get-accessor even though the program clearly uses one.

**Comment by CyrusNajmabadi** [comment]
Could you clarify what you mean by "Actual Behavior:
Property symbol does not contain a get-accessor even though the program clearly uses one."?

Do you mean you get an IPropertySymbol back, but calling `.GetMethod` on it doesn't return the accessor method for it?

**Comment by weltkante** [comment]
Yes, the GetMethod on the IPropertySymbol is null, presumably because XmlAttribute overrides only the set-accessor. The base class however has both a get- and set-accessor.

**Comment by CyrusNajmabadi** [comment]
Fascinating!  I'm not actually sure what i would expect the correct behavior of hte API to be here.  Tagging @gafter for this interesting case.  I could see arguments for this being by design (or not).  

Thanks for the report!

**Comment by gafter** [comment]
@333fred Can you comment on whether or not you believe this is by design?

**Comment by 333fred** [comment]
Certainly IOperation changed nothing here, `IPropertySymbol` is exactly how it was. @gafter, this seems like intended pre-existing behavior. The setter wasn't defined on this property, it was defined on the property from the base class. To give an example:

```C#
class C
{
    void M1()
    {
        C2 c2 = new C2() { P1 = 1 };
    }
}

class C1
{
    public virtual int P1 { get; set; }
}

class C2 : C1
{
}
```

If you get the property symbol for the `P1` reference in the initializer, then you'd get `C1.P1`. This seems consistent to me.

**Comment by weltkante** [comment]
I wasn't saying that this was an IOperation API problem, actually I mentioned the SymbolInfo API already has the same problem.

My point is that the IPropertySymbol returned by the SymbolInfo (and IOperation) APIs has nothing to do with the source code being compiled because it doesn't have the accessor against which the source code is compiled. After having looked at it for a while I agree with @CyrusNajmabadi that you can argue for either case being "correct" depending on what you are doing.

I realize its way too late to change semantics of the existing API to return the IPropertySymbol where the accessor is actually defined on, but this problem should highlight the need for exposing a SymbolInfo-level API to determine the actual property accessor bindings, since you clearly cannot derive the correct binding just by looking at the existing API.

In #26867 it was suggested to look at [this code](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Extensions/OperationExtensions.cs,23) but I think it solves a different problem, I had to heavily adapt it to return a (hopefully correct) accessor binding. This really needs to be part of the exposed API.

**Comment by gafter** [comment]
When we invoke a virtual method, the compiler provides the symbol for the most derived override of the method in the hierarchy of the receiver.  However, for a property we provide the symbol for the move derived override of the property, even if it doesn't override the accessor which is used.

I know this is not convenient for you, but it is by design.
