### ISSUE TITLE
[Proposal]Allow control structures to return values

### ISSUE THREAD

**Issue by metatron-the-chronicler** [dotnet/roslyn#3640]
In some languages (Ruby, Scala) control structures such as if and for/foreach return values. This enables code like the following:

``` ruby
puts "I like cats"  if cat
```

If cat does not evaluate to some truthy value puts is not executed.

Another example is assigning the result of a loop to a variable

``` scala
val x=for(v <- collection) yield SomeFunction(v)


```

x will be the equivalent of 

``` csharp
var x=collection.Select((v)=>Somefunction(v));
```

One more possible use for this functionality in Csharp would be to make linq expressions like 

``` csharp
var xItems = (
            from responseData in filteredItems
            let parentLevelItems = responseData.Items.Where(adi => ids.Contains(adi.Id))
            select new
            {
                secondLevelData = 
                (from c in secondLevelLabels
                    join secondLevel in responseData.children on c
                    equals string.IsNullOrEmpty(secondLevel.Label) ? 
                                           Constants.BlankData : secondLevel.Label into coun
                    from cn in coun.DefaultIfEmpty()
                    select new
                    {
                        secondLevelLabel = c,
                        parentLevelItems = parentLevelItems,
                        dataItems = cn == null ? response : 
                                                 cn.Items.Where(adi => ids.Contains(adi.Id))
                    })
            });
```

clearer as such statements could be rewritten to

``` csharp
var xItems = (
            from responseData in filteredItems
            let parentLevelItems = responseData.Items.Where(adi => ids.Contains(adi.Id))
            select new
            {
                secondLevelData = 
                (from c in secondLevelLabels
                    join secondLevel in responseData.children on c
                    equals if(string.IsNullOrEmpty(secondLevel.Label))  
                                           Constants.BlankData else secondLevel.Label 
                                            into coun
                    from cn in coun.DefaultIfEmpty()
                    select new
                    {
                        secondLevelLabel = c,
                        parentLevelItems = parentLevelItems,
                        dataItems = if(cn==null){
                                           return response;
                                           }
                                           else{ 
                                             cn.Items.Where(adi => ids.Contains(adi.Id));
                                           }
                    })
            });
```

Now you can use if where you would want to inside complex expressions without having to switch to an equivalent but harder to read ternary expression.

Doing this would also have the benefit of addressing #1665, while at the same time being more powerful and applicable outside of the context of Linq if implemented.

**Comment by svick** [comment]
```ruby
puts "I like cats"  if cat
```

Please, no. I think this is a terrible feature of Ruby that makes code much harder to read. When I had to read Ruby code that used this syntax, the `if` (or `unless`) always surprised me. Worse, it's easy to overlook: if I see `puts` and don't care what exactly is written, I might not examine the rest of the line closely.

---

```scala
val x=for(v <- collection) yield SomeFunction(v)
```

How exactly would this look in C# syntax? Something like this?

```c#
var x = foreach (var v in collection) yield return SomeFunction(v);
```

I don't see any reason to use that over the `Select()` version.

---

While I agree that the ternary operator is not very readable, I don't think adding alternative syntax for it is worth it.

**Comment by HaloFour** [comment]
The pattern matching proposal is likely to include an expression form of the syntax, e.g. `match`.  That would probably handle your general conditional expressions.

**Comment by MgSam** [comment]
I disagree that the words `if` `else` are easier to read than the ternary operator. If you use the operator enough you get used to reading it; like with any language construct.

**Comment by metatron-the-chronicler** [comment]
svick interestingly enough the Ruby syntax mirrors almost exactly the concept of a tag question:http://www.grammar.cl/Intermediate/Question_Tags.htm

Furthermore the ability to use if in that particular way actually creates a more consistent set of semantics for a conditional like if.  There is now one syntax for single line conditions instead of two, with the added ability to use any number of else clauses.

I would personally prefer to use 
```csharp
var x =foreach(var v in collection){ 
                                                        //stuff
                                                    }
```

when I need to further map over sub items as chaining select  and selectmany can get weird.  However I can think of situations where one basically just wants to wait for some process to finish and assign the result to some value after it finishes not just loops that generate collections .

 
@MgSam: Getting used to something, does not make it of equal difficulty to grasp than another thing.  One of the things I dislike about Scala culture is the overuse or rather lack of an easy way to figure out what an otherwise ungoogleable operator actually does.

If I type in ()?: into google I get back nothing related to the ternary operator.  If you are having a brain fart or don't know at all what this is you are more stuck than you otherwise would be if you could search for an actual word.  God help you if you are using a language with powerful operator overloading and need to figure out what a package local operator  actually does and don't realize that it is package local.

@HaloFour: Yes the match expression could work for this kind of thing as far as if statements go.

**Comment by MgSam** [comment]
@metatron-the-chronicler This is C# we're discussing, not Scala. In C#, there is a well known operator that has been inherited from decades-old C heritage and is present in literally dozens of languages. Only novices programmers should be surprised by the ternary operator, in which case they'll likely ask an instructor or friend and find out what it does. This use case (beginners) doesn't seem to justify adding new syntax, in my opinion.

If you want a language where everything is explicitly spelled out using English words, Microsoft already supports such a language- VB.

**Comment by metatron-the-chronicler** [comment]
@MgSam: That isn't the use case if this suggestion.  Some of the use cases have already been pointed out above, the UX argument (Which is really about overall uniformity.) is just one among others.  There is even a request to make the ternary operator do what I am talking about here in the case of if.  This idea solves that idea in a much more powerful way.

**Comment by whoisj** [comment]
The ternary operator is wonderful, it really does not need replacing. The example with ` = if (condition) ...` is significantly less clear in my opinion than `= condition ? ...`.

**Comment by JoergWMittag** [comment]
>In some languages (Ruby, Scala) control structures such as if and for/foreach return values. This enables code like the following:
>```ruby
>puts "I like cats"  if cat
>```

This has nothing to do with `if` being an expression in Ruby. This is the trailing modifier `if` form, which BTW the ISO Ruby Language Specification calls a *statement* precisely *because* in this form the return value makes no sense and is generally ignored.

>Another example is assigning the result of a loop to a variable
>```scala
>val x=for(v <- collection) yield SomeFunction(v)
>```
>x will be the equivalent of
>```csharp
>var x=collection.Select((v)=>Somefunction(v));
>```

This is *not* a `for` loop. It is a `for` comprehension, Scala's way of expressing a monad comprehension, which is dressed up to *look* like a `for` loop in order to not scare away the Java programmers. C# has monad comprehensions as well, except they aren't dressed up to look like `for` loops, they are dressed up to look like SQL queries and are called Query Expressions. You can do what you propose in C#, it looks like this:

```csharp
var x = from v in collection select Somefunction(v);
```

Personally, I am a big fan of "everything is an expression", but the use cases you have provided here are not exactly convincing.

**Comment by metatron-the-chronicler** [comment]
Pedantry is not very useful here. I mean expression in the sense described here: https://en.wikipedia.org/wiki/Expression_(computer_science)  In the case of the guard (statement modifier) the result of if still must be computed to determine whether to execute the left hand side of the whole expression. The value isn't being thrown away at all, it is controlling the flow of the program.  

The whole point of this request is to make all control structures consistent.  So no you really can't do what I am talking about in C#.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
