### ISSUE TITLE
problem with intellisense/autocomplete in an IF statement in VB.Net

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36412]
VSF_TYPE_MARKDOWNDepending upon whether parentheses &quot;()&quot; are used or not, the Visual Studio editor seems to have difficulty with intellisense/autocomplete in VB.Net IF statements.  

For example, in VB.net, what I want to end up with is something like this:

if( gclsEnvironment.LogLevel &gt; 6 )then
    call HandleLogOutput()
    end if

If I type this without using parentheses, autocomplete and intellisense works fine, as expected.  If I try to type it with parentheses, it doesn't work - neither autocomplete nor intellisense.  (In older versions of VS, it did.)  What I end up doing is typing it without parentheses and then going back and adding in parentheses afterwards.  I just like, and am used to, the look of parentheses setting off the logical statement.

All I am asking it that you restore the behavior of previous versions of VS and not penalize me for typing parentheses in VB.Net IF statements.

Thanks,

Bob Kiser

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/604698/problem-with-intellisenseautocomplete-in-an-if-sta.html
VSTS ticketId: 917202_
_These are the original issue comments:_

Visual Studio Feedback System on 6/12/2019, 09:24 PM (13 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by dpoeschl** [comment]
When I type the following, completion appears to work for me using Visual Studio 2019 Update 2:

```VB
Public Class C
    Public LogLevel = 7
End Class

Public Class Test
    Sub M()
        Dim gclsEnvironment = New C()

        ' Type the next line:
        If (gclsEnvironment.LogLevel > 6) Then
        End If
    End Sub
End Class
```

However, the contents of the completion list if you type `If(gcls...)` with no space between `If` and `(`. In that case, the completion shows up but does not include `gclsEnvironment` for some reason...

**Comment by dpoeschl** [comment]
I'd like to know whether the problem was completion not showing up _at all_ (in which case I'd need a more specific repro) or that it doesn't contain the expected symbols.

**Comment by RKiserAL** [comment]
Yes, thanks for looking into this for me.

In my case, I don't get any autocomplete or intellisense until I get to the period in "gclsEnvironment.".

If I type w/o the opening parenthesis, then the program suggests for me the full string: "gclsEnvironment" after I type just the beginning "gcls".  Then I can easily get to whatever property or method I want.  But if I do type the opening parenthesis, I don't get that behavior and have to do a lot more typing before it is willing (or able)  to recognize what I am trying to do.

I would just like to get the same behavior using the parenthesis as I do when not using the parenthesis.

I hope I am making some sense to you.  If not, please advise and I'll elaborate further.

Certainly, not a huge deal but a minor aggravation that perhaps others user like me (who use parentheses) would like to see fixed.

Thanks in advance for your efforts.

Bob Kiser

**Comment by KiwiJaune** [comment]
This is really annoying...
in short : if you dont type a space after "If" and before "(", the autocompletion don't work. And it will replace your word by another...

![autocomplete](https://user-images.githubusercontent.com/7214967/72276500-5627cb00-3630-11ea-913f-cb03e0485989.gif)

**Comment by KiwiJaune** [comment]
Hi,

No news since January ?
This is still bugged in 16.7.2...

![bug](https://user-images.githubusercontent.com/7214967/91046108-299d4e00-e618-11ea-869f-5e1875fd3c48.gif)


Thanks

**Comment by CyrusNajmabadi** [comment]
@KiwiJaune No movement as of yet. If you'd like though, we would likely take an externally contributed pr here.  Thanks!

**Comment by KiwiJaune** [comment]
It would have been a pleasure but I have no knowledge in the roslyn code and I will have no idea where to look for the bug.

**Comment by CyrusNajmabadi** [comment]
This would be the file of interest:
https://github.com/dotnet/roslyn/blob/master/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/LanguageServices/VisualBasicTypeInferenceService.TypeInferrer.vb

:-)

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to be making changes in these experiences.
