### ISSUE TITLE
[Proposal] Implicit factories

### ISSUE THREAD

**Issue by metatron-the-chronicler** [dotnet/roslyn#3641]
In scala when on defines a companion object for a class it is possible to override the apply method so that one may perform various actions and (usually) return a value of the given type.  However it is also possible to do the following:

``` scala
case class Employee(manager:Boolean=false)
case class Manager extends Employee(underlings:List[Employee])


object Employee{
  def apply(m:Boolean)={
    if(m){
       Manager(underlings=someListOfSubordinates)
    }else{
       new Employee()
    }
}
```

Basically you get a factory class for free without having to explicitly design one.  Whenever you call apply on Employee if manager is true you get a Manager back.

This has implications for building types that validate themselves without needing to rely on external classes to handle validation which reduces client classes to maps of data. (Without things like mutability.) 

In the case of Csharp I propose adding a keyword called factory that will serve as the default constructor if one is not defined or be delegated to if one is explicitly defined.

It would look like this:

``` csharp
public class Employee{}
public class Manager:Employee
public class Employee{
     factory(bool argument){
       if(argument){
          return new Manager();
      }
      return this;
   }
}
```

Coupled with the proposed record types this paves the way for easily defined and first class support for encoding business rules of various kinds with fewer objects.

**Comment by SolalPirelli** [comment]
Your Scala code doesn't compile for many reasons: case-to-case inheritance, missing brace, missing arg list for Manager, Employee.apply(Boolean) is defined twice... it makes it hard to understand what you want exactly.  
Also, that "return this" at the end of your factory is confusing; does it mean an Employee is always created, but silently discarded if the factory returns something else?

Anyway, what's the big advantage of this when compared to a static method? I'm no language designer, but IMHO "fewer objects" is pretty weak when compared to the complexity it adds to the language.

**Comment by monoman** [comment]
The problem here is that then the factory is hardcoded and can't be extended

If I then want to create a CEO class that inherits from Employee in another
library, that factory method can't be 'overriden' (although the signature
would probably need to change anyway in this fake example). That's the main
advantage of factories, that they implement interfaces and can be extended
or replaced (specially when they are container injected) when needed,
without needlessly changing the root classes hierarchy.

:-1:

Rafael Teixeira
O..:.)oooo

**Comment by metatron-the-chronicler** [comment]
@SolalPirelli: If I recall correctly In scala when you write "()" on a class you call apply for that instance.
Sorry about the broken I haven't slept.  

As for the psuedo code basically if the if statement evaluates to true then the new type is returned, and the last line is never reached.  Only in the event that the condition returns false does  return this get executed.

In the context of the factory returning this means to return an instance of the type in which the factory is declared. It seemed to weird to me to write return new Employee(args) because that sort of implies running the factory at least twice.

Static methods cannot access this, or non static class members.  With these restrictions static methods don't really cut it as factories if you need to manipulate non static fields while doing work.  You would have to pass in everything explicitly, limiting effectiveness of this kind of alternative to any factory that is not a kind of validator.  

You have to separate type field definitions from their validation  (Unless you are willing to make lots of constructors potentially.) which means you cannot easily enforce rules that govern your types without relying on the honor code to ensure that consumers of your types actually construct valid types and/or handle instantiation failures.

  

@monoman:Really the factory would really only be used on an abstract class _if_ you don't have something like Either<T> as a possible expected return value.  In the case where you do not the factory signature could be changed and a different set of results returned with the possible logical restriction that all results must be subtypes of the type in which the factory is defined.

I simply did not specify that this be restricted to abstract classes because this way of doing things could allow for expressions like 

```csharp
Either<Exception,Someclass> x=new Someclass(arg,arg1,arg2);
```
Do you know of a particular reason why overriding factory in the base class with a different signature would be worse than overloading (or overriding with a different signature.) in a subclass or why overloading of factory could not be implemented? 


If we have traits that work more or less like those in Scala we might define a series of traits with implementations of the factory that call themselves in the order that they were mixed in.

See http://blog.ryannedolan.info/2014/03/scala-pattern-stackable-traits.html for an example in Scala.

**Comment by SolalPirelli** [comment]
> I simply did not specify that this be restricted to abstract classes because this way of doing things could allow for expressions like

>        Either<Exception,Someclass> x=new Someclass(arg,arg1,arg2);

This is already possible with implicit conversions. Unless you're talking about `x` catching a possible exception and making it into a `Failure`, which would require significant changes in C# anyway.

**Comment by metatron-the-chronicler** [comment]
I mean wrapping in a Failure<T>. I wanted to keep the proposal loose enough that people would consider how this would work if it became possible to implement monadic type more cleanly ourselves or if the compiler team gave us one to work with. The proposed match expression if it is ever implemented would go a long way to making working with monadic types much easier to work with.  Currently it is possible to implement Either in C# yourself but it is a total pain to work with since C# doesn't have a nice or (if I remember correctly for this particular use case.) well performing way of dispatching on types let alone destructuring.

**Comment by gafter** [comment]
This was the intent of https://github.com/dotnet/roslyn/issues/206#issuecomment-75619775 , but with the syntax `operator new`.

**Comment by metatron-the-chronicler** [comment]
@gafter I hadn't seen that, but ironically I thought about changing the proposed syntax to new. Well I'm glad other people are also thinking of something along the same lines.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
