### ISSUE TITLE
The #r directive do not support relative path to local assemblies

### ISSUE THREAD

**Issue by the-frank** [dotnet/roslyn#36417]
Stable version 3.1.0 from GitHub

Try to reference any local dll with the r# directive using a relative path.
1. #r ".\MyLib.dll"
2. Then from code try to call that script by passing its content to 
string scriptContent = File.ReadAllText("pathToCsxFile.csx");
CSharpScript.EvaluateAsync(scriptContent)

**Expected Behavior**:
The script will run fine and load the assembly.

**Actual Behavior**:
The method will throw the following exception: error CS0006: Metadata file '.\MyLib.dll' could not be found. If you have an absolute path like #r "D:\Absolute\Path\To\MyLib.dll", the script will run just fine.

See this post for more details and for a proof that different persons are experiencing the issue:
https://stackoverflow.com/questions/56545907/the-r-directive-in-c-sharp-script-does-not-support-relative-paths/56551834?noredirect=1#comment99726286_56551834

**Comment by tmat** [comment]
Relative paths in `#r` are relative to the directory containing the script. In this case however, the script is created w/o a file path, so no directory contains the script.

You can specify the script file path via `ScriptOptions` like so:

```C#
string scriptContent = File.ReadAllText("pathToCsxFile.csx");
CSharpScript.EvaluateAsync(scriptContent, ScriptOptions.Default.WithFilePath(@"D:\Absolute\Path\To\script.csx"));
```
