### ISSUE TITLE
[Feature Request] Support Module Initialization in C#

### ISSUE THREAD

**Issue by rladuca** [dotnet/roslyn#36411]
WPF used to build one of its assemblies, `PresentationCore`, as a hybrid between C++/CLI and C#.  In an effort to reduce our dependencies on `NetModule` and make our build cleaner, we split the C++/CLI portion into a new DLL.

We relied on the use of Module Initialization in `PresentationCore` in order to properly configure defaults for WPF applications.  Due to the split, this was no longer possible to do purely in code as we had used the C++/CLI portion to add this before.

This is now accomplished via IL injection via IL(D)Asm in order to add this back to a pure C# assembly.  This isn't a very sustainable way of doing this and we're worried about this breaking in the future.

WPF would like a supported way to add a module initializer to a C# assembly.  Perhaps a compiler flag/msbuild property that allows a developer to specify a type/function to call on initialization of the module.

You can see how WPF is doing this (a fairly common idiom):
* [Injected IL](https://github.com/dotnet/wpf/blob/master/eng/WpfArcadeSdk/tools/InjectModuleInitializer/ModuleInitializer.il)
* [Assembly level implementation of the initializer](https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationCore/ModuleInitializer.cs)

Something like this would provide an easy way to access this functionality with, it seems to me, minimal risk to breaking existing builds.

**Comment by rladuca** [comment]
CC. @vatsan-madhavan

**Comment by 0xd4d** [comment]
There are at least two nuget packages that can do this today:

https://www.nuget.org/packages/InjectModuleInitializer/
https://www.nuget.org/packages/ModuleInit.Fody/

**Comment by rladuca** [comment]
https://github.com/dotnet/csharplang/issues/2608

**Comment by gafter** [comment]
Indeed, this is a dup of dotnet/csharplang#2608
