### ISSUE TITLE
Eating too much RAM

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36426]
<p>VSF_TYPE_MARKDOWNHi,</p><p>I have installed vs 2019 4.4 update and after that debugging on it is a nightmare.
It’s using too much RAM, going more than 2.8 gb, and is very slow,
just can’t event go through steps, causing raise of a development time.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/508582/eating-too-much-ram-1.html
VSTS ticketId: 830935_
_These are the original issue comments:_

Visual Studio Feedback System on 3/28/2019, 08:00 PM (76 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by agocke** [comment]
cc @jinujoseph

**Comment by CyrusNajmabadi** [comment]
Customer report lacks diagnostic information to determine what's going on here.  Since that release we did a ton of work on memory reductions.  So closing out as resolved, absent new data that shows where an issue remains.
