### ISSUE TITLE
Confirm that OpenSourceDebug.csproj behaves as expected

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#3644]
Can you please make sure that it works with our newer public releases?  I don't think it's been tested since the Fall Preview.

**Comment by amcasey** [comment]
You may with to wait until https://github.com/dotnet/roslyn/pull/3642 has been merged.

**Comment by davkean** [comment]
Is this relevant anymore?

**Comment by davkean** [comment]
I think this is no longer relevant, given the recent changes.
