### ISSUE TITLE
VsHierarchyExtensions.GetMonikerForHierarchyAndItemId loads unrelated docdata objects

### ISSUE THREAD

**Issue by ToddGrun** [dotnet/roslyn#3645]
[This extension method](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Utilities/VsHierarchyExtensions.cs,8cd19b5d59b4a18a) calls IVsRunningDocumentTable.GetDocumentInfo in a loop until it finds a matching hierarchy, itemid pairing. However, each call to GetDocumentInfo ends up creating a docdata for the requested file, which means it might end up creating multiple docdata objects when it only needs to find the document's moniker. A better way to do this would be to use either MPF or IVsRunningDocumentTable4 to find this information.

**Comment by Pilchie** [comment]
The reason creating the doc data's is bad is that it promotes stub documents into full documents pre-maturely.
