### ISSUE TITLE
Go To Definition and Go To Implementation do not focus Tab Group

### ISSUE THREAD

**Issue by jwidar** [dotnet/roslyn#36452]
**Version Used**: 
16.1.3

**Steps to Reproduce**:
![image](https://user-images.githubusercontent.com/15267485/59499540-e2ee8880-8e97-11e9-9ba1-6a3bfcaf92e0.png)

1. Open Class1 in one Tab Group
2. Open Class2 and its interface their own Tab Groups
3. Make sure the caret is NOT on the Foo() line in both Class2 and IClass2
4. In Class1.CallFoo(), put caret on the call to Foo()
5. Now "Go To Definition".
6. The IClass2 editor reacts and makes the Foo definition selected, but the caret is still in Class1:
![image](https://user-images.githubusercontent.com/15267485/59500156-2a294900-8e99-11e9-81e2-527d0217f5af.png)
7. Press Ctrl+Tab to select the IClass2 editor, you can now see that the caret is at the right position but the editor never got activated.

**Expected Behavior**:
When Go To Definition or Go To Implementation is selected, the target editor should be activated even if it is in a different Tab Group.
**Actual Behavior**:
The target Editor is not activated, but the text of the target method is selected in its editor.
This goes for both Go To Definition and Go To Implementation.

**Comment by jinujoseph** [comment]
cc @olegtk  for info and if he knows what might be going on here

**Comment by olegtk** [comment]
Is this a regression from VS 2017, do you know by any chance, @jwidar ?

**Comment by jwidar** [comment]
It works as "Expected behavior" in 15.9.12.

**Comment by jwidar** [comment]
I tested again in 16.1.3 with all non-Microsoft extensions disabled. The problem is still there.

**Comment by jwidar** [comment]
@olegtk 

Now using 16.3.2. Still doesn't work.
All non-microsoft extensions disabled, settings backed up and then reset.

Some of my colleages do not have this problem though.

**Comment by olegtk** [comment]
no idea, @jinujoseph, please investigate first as Roslyn handles both commands.

**Comment by jwidar** [comment]
I mentioned this here:
https://developercommunity.visualstudio.com/content/problem/625201/disappearing-cursor-in-text-editor-vs-2019.html

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.  Focus is not a roslyn concern and this should be handled by editor/platform if there's still an issue that needs fixing here.
