### ISSUE TITLE
Use implicit type Fix All should simplify deconstructions

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#36468]
**Version Used**: 16.2 Preview 2

**Steps to Reproduce**:

1. Always prefer `var`
2. Write a deconstruction variable declaration as:

    ```csharp
    (bool x, bool y) = (true, true);
    ```

3. Apply a Fix All in Document to use implicit types

**Expected Behavior**:

```csharp
var (x, y) = (true, true);
```

**Actual Behavior**:

```csharp
(var x, var y) = (true, true);
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
