### ISSUE TITLE
UseImplicitType incorrectly offered on `out _ `

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#36497]
![image](https://user-images.githubusercontent.com/12466233/59576565-2a7e3b80-9075-11e9-8d0f-b085f873b16f.png)

**Comment by CyrusNajmabadi** [comment]
What's the issue here?

**Comment by jcouv** [comment]
The fix say "use 'var' instead of explicit type" (but there is no explicit type) and the preview shows an explicit type (`TextSpan`) where none exists in source.
On second thought, this is really a nit. I'll close :-)

**Comment by CyrusNajmabadi** [comment]
:D

**Comment by jcouv** [comment]
@sharwell pointed out that I misread the code (and thus hallucinated the problem). There is an explicit type in source. I was looking at the wrong argument (`cursorPosition: out _`), but the fix was offered on `textSpan`.
I just got confused.
