### ISSUE TITLE
implement interface quickfix doesn't implement methods with default implementations

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36505]
VSF_TYPE_MARKDOWNThe Implement Interface Quickfix doesn't work the way I expect it to WRT to interfaces with default implementations, it completely ignores interfaces with default implementations. I can't scaffold a new class with all members.

The Implement Interface quickfix does not appear if an interface is comprised of only default implementations.

```C#
    public interface IBlah
    {
        Thing GetThing() => throw new NotImplementedException();
    }

    public class Blah : IBlah
    {
    }
```

The implement interface quickfix does not implement methods with default implementations

```C#
    public interface IBlah
    {
        Thing GetThing() => throw new NotImplementedException();

        Thing GetAnotherThing();
    }

    public class Blah : IBlah
    {
        public Thing GetAnotherThing()
        {
            throw new NotImplementedException();
        }
    }
```

The current behaviour of the Implement Interface quickfix seems to assume that there will only be one revision of an interface and nobody in the future will want to write an implementation from scratch.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/609081/implement-interface-quickfix-doesnt-implement-meth.html
VSTS ticketId: 922870_
_These are the original issue comments:_

Steve Goodwin on 6/16/2019, 02:06 AM (31 hours ago): I'd prefer to see an attribute that allows methods to opt-out of being scaffolded, and the default behaviour is to implement the entire interface.<br><br>    public interface IBlah<br>    \{<br>        [Scaffold(false)]<br>        Thing GetThing() => throw new NotImplementedException();<br><br>        Thing GetAnotherThing();<br>    }<br>
Visual Studio Feedback System on 6/17/2019, 02:17 AM (7 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Steve Goodwin on 6/17/2019, 03:28 AM (5 hours ago): I've been having a think about this, and it's a conflict between traits where interface implementation is intentional and extending an existing interface where, IMO, the most likely implementation will be:<br><br>    MyNewMethod() => throw new NotImplementedException();<br><br>Given 100% of existing .Net interfaces are pure interfaces, I suggest the Implement Interface's quickfix behaviour I've observed is not desirable as it's current behaviour is not going to be useful for years.<br><br>
Steve Goodwin on 6/17/2019, 03:33 AM (5 hours ago): Oh! Another argument against current behaviour. If I have a non-async interface with say 50 methods, and then introduce a new version with async versions of the 50 methods, that's going to tedious to copy and paste the 50 methods into my class.<br><br>I'll stop now :-)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This behavior is what i would expect.  Implement-interface has always only ever added the members you don't already implement (i.e. if any of your subclasses already have an impl).  The purpose is to give you all the members you *need* to impl, not *all* the interface members.

**Comment by ryzngard** [comment]
Design Review: Current behavior is expected. We may consider a separate refactoring that includes adding default implementation methods from an interface, but current refactoring is as by design. We need feedback from designers of feature and users of similar features (such as Java users) to determine if this would be needed for usual workflow. Right now, use explicit implementation to see available DIM to implement from interface by type `public <interface type>.` to see in intellisense.

**Comment by Tratcher** [comment]
Additional datapoint:
I also hit this the first time I tried to write an interface using DIMs. This is not the behavior I expected.

Normal coding flow:
1. Create the interface
1. Create a class that implements the interface
1. Use the quickfix to generate all the interface members for my class.
1. Fill in the implementation of all the members.

DIMs fail on step 3. The DIM members don't show up under `override` intelligence either, which is the next place you usually have to look for parent members.

DIMs exist for compatibility reasons, but when I'm actively implementing an interface on a type I want to generate all the available members. I'll remove any I don't think are not needed, that's easier than trying to add them all manually.

**Comment by laicasaane** [comment]
Unity ECS provides DIMs for ISystem interface so users can choose to implement only some of them. Currently I have to manually implement at least 2 methods for each system (OnCreate and OnUpdate). For a typical ECS project we usually have a large number of systems. Copy-pasting is now a real labour.
