### ISSUE TITLE
Intellisense changes existing, correct variable to differently capitalized type of the same name

### ISSUE THREAD

**Issue by mqudsi** [dotnet/roslyn#36513]
**Version Used**: Visual Studio 16.2.0 Preview 1.0

**Steps to Reproduce**:

1. Create a C# file with a struct `Structure` and an instance of that `Structure structure`
2. Attempt to autocomplete `structure.`, backspace over the `.` then type in `.` again. 
3. Rinse and repeat.

**Expected Behavior**:

Autocomplete/Intellisense will always provide completions for the valid local variable `structure`. Autocomplete/IntelliSense will never change the `structure` that I typed to `Structure`.

**Actual Behavior**:

As of Visual Studio 16 (perhaps specifically a later preview build), sometimes the `structure` I had previously typed out will be changed to `Structure`. *This appears to be a race condition*, as it does not reproduce every time. 

This is a demonstration of the bug: https://www.youtube.com/watch?v=cEnwzAPYTFc&feature=youtu.be

I am sorry I do not have a 100% reproducible case, but this has been observed for awhile now on multiple PCs since upgrading to Visual Studio 2019 preview.

**Comment by mqudsi** [comment]
I also notice cases of the opposite, where references to class `Foo` are incorrectly changed to also existing instance `foo` after a `.`.

**Comment by ivanbasov** [comment]
Thank you for reporting this, @mqudsi ! Your explanations are great. Let me try to fix it.

**Comment by mqudsi** [comment]
Hey, that was really fast! Thanks!
