### ISSUE TITLE
SourceEventSymbol.ComputeIsWindowsRuntimeEvent is improperly handling WinRT events implemented in derived interfaces

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#36532]
```
        private bool ComputeIsWindowsRuntimeEvent()
        {
            // Interface events don't override or implement other events, so they only
            // depend the output kind.
            if (this.containingType.IsInterfaceType())
            {
                return this.IsCompilationOutputWinMdObj();
            }
            ...
```
Now that we have DIM (Default Interface Methods), the comment "Interface events don't override or implement other events" is not accurate any more. Returning from the '''if``` in that case is likely cause an unexpected behavior of the compiler.

**Comment by gafter** [comment]
Since we are unlikely to have a WinRT runtime that supports DIM any time soon, a fix is probably not urgent.  But for sanity and sanitation we should correct this.
