### ISSUE TITLE
ITypeSymbolExtensions.FindImplementationsForInterfaceMemberAsync uses CPU inefficiently

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#36538]
**Version Used**: 16.1.3

The following scenario needs a controlled benchmarking setup.

### Steps to Reproduce

https://developercommunity.visualstudio.com/content/problem/606520/servicehubhostclrx86-32-bit-high-cpu-returns-in-20.html
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/917965

### Details

* 47.4% ITypeSymbolExtensions.FindImplementations, most of which is evaluating the `FirstOrDefault` call(s) here:

    https://github.com/dotnet/roslyn/blob/9d80dea7fe1b14043b9b2ac4d0b59ed26f508742/src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs#L281

* 21.3% ITypeSymbolExtensions.GetOriginalInterfacesAndTheirBaseInterfaces, most of which is HashSet manipulation
* 20.2% SymbolFinder.OriginalSymbolsMatch here

    https://github.com/dotnet/roslyn/blob/9d80dea7fe1b14043b9b2ac4d0b59ed26f508742/src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs#L178

* 6.8% SymbolFinder.FindSourceDefinitionAsync, most of which is SymbolKey.Resolve

**Comment by CyrusNajmabadi** [comment]
Closing out as much of these subsystems have been substantially rewritten (and are called from higher layers in entirely different ways now).
