### ISSUE TITLE
Backspace completion disappears if entire identifier is removed

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#36546]
**Version Used**: 16.2 Preview 2

:link: https://developercommunity.visualstudio.com/content/problem/567910/vs2019-intellisense-worst-than-vs2010.html

**Steps to Reproduce**:

1. In a VB method, type `Console.W`
2. Press <kbd>Backspace</kbd>

**Expected Behavior**:

Completion is visible, just as though the user just typed `.`.

**Actual Behavior**:

Completion disappears.

**Comment by dddns** [comment]
@sharwell thank you for this. I'll wait for the release and will let you know.
Wrinting here as im unable to reply on the original thread.

**Comment by dddns** [comment]
@sharwell Also this, updated to 16.2.0 and not fixed also.
