### ISSUE TITLE
Proposal: implicit interface implementation for VB

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#3654]
In C# one can implement an interface's members implicitly by writing a set of public members that match the signature of the interface members.

I propose we do the same in VB.

**Comment by Bill-McC** [comment]
I'd like it if there was a context sensitive keyword 'Implies' for this. eg:

Interface Ia
    Sub a1()
    Sub a2()
End Interface

Class Foo 
   Sub a1()
   Sub a2()
End Class

Class Bar
    Inherits Foo
    Implies Ia
End Class

Class Baz
   Inherits Foo
   Implies Ia

    Sub xxx() Implements Ia.a2()
End Class

I think this should work even if Baz inherits Bar : allowing for an implementation to override the mapping by reimplementing the interface, but only requiring parts that you want to remap to be define with "implements" on the member.

**Comment by vbcodec** [comment]
Think this is unnecessary or should be optional. I like in VB clearly expressed relationships, without 'default meaning', at least in this case. With dozens methods in the class, it is much easier to detect where interface is implemented, than go to interface's definition, check what;s inside, and compare with name inside class.

**Comment by Bill-McC** [comment]
I would not call it un-necessary. Take an example where you have base classes generated, yet you want to add an interface mapping to the derived classes. The only way to do that would be to override the base methods (if allowed), or to provide a set of stub methods.
So let's say you go down the route of providing stub methods, that link back to the base method. The class now comes polluted with duplicate names. you could mark them as private but then you can't actually see where the interface is implemented in further derived classes.
The lack of implicit interfaces means you have to add extra stuff, when the correct signature is already there.

As to code navigation, you should be able to select the interface in the code editor and happily navigate to it's members from the drop downs. It should also be possible for the editor to show some visual glyph indicating methods that implicitly implement; although I wouldn't prioritize that last bit: it would be a nice have

**Comment by gafter** [comment]
This is now tracked at https://github.com/dotnet/vblang/issues/38

**Comment by jrmoreno1** [comment]
@Bill-McC : I agree, VB needs either implicit interface implementation OR an explicit syntax that isn't tied to the declaration.  I.e. something like:

   Interface IHasX
      Property X as Integer
   End Interface 

     dim y as Integer
      Public Property Whatever As Integer
          Get
                Return y
          End Get
          Set
               y = x 
          End Set
      End Property 
      
      Property Whatever As Integer Implements IHasX.X

Whatever is defined twice (just like a partial method declaration), once without an implementation, once with.

**Comment by Bill-McC** [comment]
@jrmoreno1  if the base class did a rename, wouldn't  the second Whatever become an auto property ?

Maybe a #Begin Map .... #End Map kind of concept where a mapping could be applied to retrospectively to base classes where there isn't an implicit match by name and sig ..... Or some kind of block construct ?

**Comment by jrmoreno1** [comment]
@Bill-McC : I would hope not.  The rename refactoring tool should fix it, just as it would fix all usages of the property.

**Comment by jrmoreno1** [comment]
@Bill-McC: your right, it would probably need a different syntax.
