### ISSUE TITLE
Make RemoteHost to start itself when someone ask for it.

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#36559]
right now, RemoteHost is designed to start when package is loaded or first workspace event is fired.

if there is someone who ask for it before those, they will think remote host is disabled. 

consider changing remote host to start itself when someone ask for it before roslyn pre-emptively starts it if remote host is enabled.

**Comment by heejaechang** [comment]
also, move nuget package to event listener model.

**Comment by CyrusNajmabadi** [comment]
@tmat is this still something we need to do?

**Comment by tmat** [comment]
IDK. Maybe.

**Comment by CyrusNajmabadi** [comment]
Closing out.
