### ISSUE TITLE
Use block body for getter not available in expression-bodied getter

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#36560]
Given the following code in a getter:

```C#
class C
{
	int Prop { get => 1; }
}
```

When I `CTRL+.` on the getter, I am not offered a refactoring to move to a block body. I _am_ offered a refactoring to move the whole thing to an expression-bodied property. Not useful if I'm looking to expand the body of the getter.

![image](https://user-images.githubusercontent.com/2371880/59728178-ce8af280-91ed-11e9-812a-7eac8223211a.png)

**Comment by 333fred** [comment]
Note my cursor was on the `_lazyGuardedSnapshotManager` reference.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
