### ISSUE TITLE
[RPS] Additional Image loads as part of initializing the Csharp language service

### ISSUE THREAD

**Issue by AbhitejJohn** [dotnet/roslyn#36561]
[This ](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/FindReferences/StreamingFindUsagesPresenter.cs#L53) logic ends up importing all implementations of `ITableColumnDefinition` which is essentially the base interface for any component that has a table control (Test Explorer being one of them since 16.2). This causes unnecessary image loads on solution open/project creation. 

Filing this to track fixing this to be more specific to the column definitions that Roslyn needs.

Additional odities - I haven't seen this repro in IntPreview bits though(VisualStudio.16.IntPreview/16.2.0-pre.4.0+29017.117.d16.2stg) and this specific code has not changed.

**Comment by AbhitejJohn** [comment]
@jinujoseph to help triage this since this is blocking Roslyn insertions into VS master.

**Comment by jinujoseph** [comment]
fixed via https://github.com/dotnet/roslyn/issues/36561
