### ISSUE TITLE
Consider if SuppressionDescriptor should be a struct

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#36568]
https://github.com/dotnet/roslyn/pull/36067 adds a new public API `SuppressionDescriptor` which is analogous to `DiagnosticDescriptor` - `DiagnosticSuppressor` declaratively provides its supported suppression descriptors, similar to the way that `DiagnosticAnalyzer` provides its supported diagnostic descriptors. `SuppressionDescriptor` is a class in the PR for consistency with `DiagnosticDescriptor`. It was suggested [here](https://github.com/dotnet/roslyn/pull/36067#discussion_r295020664) that it could be a struct. This issue tracks whether or not to make this change.

**Comment by CyrusNajmabadi** [comment]
Closing out.
