### ISSUE TITLE
Feature: Translatable strings

### ISSUE THREAD

**Issue by monoman** [dotnet/roslyn#3656]
Basically anyone can use resources, gettext or [managed-commons-core](https://github.com/managed-commons/managed-commons-core),  to translate (localize) strings in its C# code, and it can even be kind of terse like this sample using managed-commons-core:

``` csharp
using System.Collections.Generic;
using Commons.GetOptions;
using static System.Console;
using static Commons.Translation.TranslationService;

namespace TestApp
{
    class AppCommand
    {
            // Returns the translated form of "First mock command"
            public virtual string Description { get { return _("First mock command"); } }

            public virtual string Name { get { return "alpha"; } }

            // Returns the translated form of "Command {0} executed!" with Name substituted
            public virtual void Execute(IEnumerable<string> args, ErrorReporter ReportError)
            {
                WriteLine(TranslateAndFormat("Command {0} executed!", Name));
            }
        }
}
```

Then enters C# 6.0 with its fantastic new feature **interpolated strings** and now that last method can't be *optimized* to use the new feature because:
``` csharp
            public virtual void Execute(IEnumerable<string> args, ErrorReporter ReportError)
            {
                WriteLine(_($"Command {Name} executed!"));
            }
```
would in truth first format and then try to lookup a translation, which would be truly the wrong thing to happen...

This experiment would allow for C# 7 a new syntax for translatable strings that would make that snippet into:

``` csharp
using System.Collections.Generic;
using Commons.GetOptions;
using static System.Console;

namespace TestApp
{
    class AppCommand
    {
            // Returns the translated form of "First mock command"
            public virtual string Description { get { return $_"First mock command"; } }
            public virtual string Name { get { return "alpha"; } }
            // Returns the translated form of "Command {0} executed!" with Name substituted
            public virtual void Execute(IEnumerable<string> args, ErrorReporter ReportError)
            {
                WriteLine($_"Command {Name} executed!");
            }
        }
}
```

Interpolated strings can return an IFormattable, and thus one can do some localization (number formatting for instance), but not truly translation, so this feature is interesting beyond the small gain on shortening code, for the other cases.

But the **killing feature** that adding this to compiler would allow is to have the extraction of translatable texts done by the compiler,  as it does for xml documentation, if the right command line parameter is specified.

$_"Command {Name} executed!"  would be extracted as "Command {0} executed!", automagically.

All is well but some may ask as this, which looks a lot like the way gettext does things would work for extracting to a .resx file, where keys can't be arbitrary strings. Well for this scenario the compiler would generate SHA1 hashes as keys and insert the hashing while calling the TranslationService behind the scenes. TranslationService is a pluggable infrastructure that can have 'translators' sourcing their translations on resources, .mo files, hard-coded dictionaries, whatever...

My experimentation will use managed-commons-core, which I'm the core developer/maintainer, as the backend but if real merit is found on this discussion, surely the runtime team will have to come forward and implement something like it, or just borrow the logic which MIT-licensed from my implementation there.

Experimental work started in https://github.com/managed-commons/roslyn/tree/translatableStrings, parsing for language = 7 is OK, with a few unit tests to match, but no semantics/code-generation yet.

No pull request yet as it would be too premature.

**Comment by monoman** [comment]
Another implementation the compiler needs to support to make this a truly workable solution, is to understand the Translatable attribute which marks method parameters as sources of texts to be translated if they receive string literals, but I'll elaborate on that in another issue, down the road...

**Comment by gafter** [comment]
The interpolated string feature already supports this. If an interpolated string expression is converted to the type `System.FormattableString`, then you get an object that implements that API. That gives you access to the *composite format string* and the *arguments* separately, before formatting.

**Comment by monoman** [comment]
Thanks, I'll continue the experiment anyway to see the dynamic of tooling
around it.

Rafael Teixeira
O..:.)oooo

**Comment by furesoft** [comment]
You can use gettext and make a class who implements the _ function
