### ISSUE TITLE
Unify EnumerableExtensions Classes

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#36590]
https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Collections/EnumerableExtensions.cs
https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/InternalUtilities/EnumerableExtensions.cs

Same static class, different namespaces. We shouldn't have two of these.

**Comment by 333fred** [comment]
This forces us to have to fully-qualify extension methods when both are imported.

**Comment by jcouv** [comment]
@333fred Seems like something we can do opportunistically. You're the most likely person to actually do this, since you raised the issue, so I assigned it to you and I'll let you decide the priority.

**Comment by 333fred** [comment]
I'll try to see if it's as simple as moving the contents of one file to the other, and if not then I'll probably leave it as is until I do a more general refactoring PR.
