### ISSUE TITLE
show progress in task center for solution crawler

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#36606]
right now, task center solution crawler progress uses an indeterministic progress bar. that makes it hard for users to know how much works are left in the queue.

change it so that it shows "m out of n" progress so that it is easier for users to know when BG work will finish.

**Comment by heejaechang** [comment]
other feedback is removing file "extensions" for project and solution. otherwise, it looks like we are analyzing csproj file itself rather than whole project or solution.

**Comment by heejaechang** [comment]
this is incremental update on https://github.com/dotnet/roslyn/pull/35336

**Comment by sharwell** [comment]
@heejaechang I definitely noticed the changes from last round and they were great! I'm looking forward to seeing more of Roslyn's background progress captured by this UI. 👍

**Comment by heejaechang** [comment]
merged to other issue - https://github.com/dotnet/roslyn/issues/37751
