### ISSUE TITLE
Adjust the NullableAttribute type emitted by the compiler

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#36604]
The corefx API review process yielded some minor tweaks, even though the type won't be included in Core 3.

Here's the final API shape is documented [here](https://github.com/dotnet/corefx/issues/36222#issue-423989497). Note that it uses `ReadOnlySpan` for the flags.

**Comment by dougbu** [comment]
@jcouv this change may affect EntityFrameworkCore as well. What .NET Core milestone will include the relevant changes?

**Comment by jcouv** [comment]
Tagging @cston @stoub while I'm out.

________________________________

**Comment by dougbu** [comment]
Think @jcouv meant @stephentoub. Sorry if I'm incorrect @stephentoub

**Comment by stephentoub** [comment]
He did :)

**Comment by cston** [comment]
No further changes are planned for the nullable attributes generated by the compiler. See spec for the API shape as implemented.
