### ISSUE TITLE
IDE offers refactoring to convert switch statement to expression

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#36608]
**Version Used**: 
3.2.0-beta4-19312-10

**Steps to Reproduce**:

```csharp
using System;
public class C {
    public enum Kind {
        Created,
        Moved,
    }
    
    class EventArgs1 : EventArgs {}
    class EventArgs2 : EventArgs {}
    
    event EventHandler<EventArgs1> Created;
    event EventHandler<EventArgs2> Moved;
    
    public object GetHandler(Kind kind)
    {
        switch (kind)
        {
            case Kind.Created:
                return Created;
            case Kind.Moved:
        	return Moved;
            default:
                throw new InvalidOperationException();
        }
    }
}
```

**Expected Behavior**:
IDE offers to convert to switch statement and gets it right (adds object casts) or doesn't offer the refactoring.

**Actual Behavior**:
Refactors the code to this, which doesn't build:

```csharp
static object GetHandler (Kind kind)
{
	return kind switch
	{
		Kind.Created => Created,
		Kind.Copied => Copied,
		_ => throw new InvalidOperationException (),
	};
}
```

**Comment by CyrusNajmabadi** [comment]
Tagging @alrz

**Comment by alrz** [comment]
I believe "target-typed switch expressions" will make this possible, @gafter?

**Comment by vatsalyaagrawal** [comment]
@jasonmalinowski which project should this belong to as C# 8.0 feature polish.

**Comment by alrz** [comment]
Confirmed that this does compile on master

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AAgEwCMAsAFCEDMABCXQMJ0DeVdnD9cAdgK5g6AaUy8AJmw5cZTBHAjxxSaTM4BZAPYZlqugF89exgFEMvGAEEEAcyik6IOmb5XbUNocozT5t3eJHZz9rO08jby44P2DXAAkICQAbRAAeFwtQ+wA+ZnlFOHEAbj1o11iLBOS0jP8oYlytHRLIzj1NYAArOABjGDoAcTgYKvEUhDoAClEJOgBrMXEASj12VrVCAHZ5xbooAHdMGB6ACz0ZNbUrkUWAOjkFJToAXlyHgt1165uJW6bCl6NbSFFRfa4AfUBdBgJwQmn2dF4cARAEleGgIElMOIAPIAB0Qikwml4JgAHj04HiYMTeFMlqDvvoWjIvPogA
