### ISSUE TITLE
Components/Controls/UserControls inconsistently get marked with sub type

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#36609]
**Version Used**: 
Version 16.2.0 Preview 4.0 [29018.107.d16.2stg]

**Steps to Reproduce**:

All steps start with:

1. File -> New -> Windows Forms App (.NET Core)

#### User Control does not get marked with sub type

1. Add -> New Item -> User Control

####  Custom Control does not get marked with sub type

**Expected**: Icon to change to "UserControl", when double-click, Control designer should open

1. Add -> New Item -> Custom Control

**Expected**: Icon to change to "Component", when double-click Component designer should open

#### Changing Form -> Component should fix up sub type

1. Add -> New Item -> Windows Form
2. Right-click -> View Code
3. Change base class to Component

**Expected**: Icon to change to "Component", when double-click Component designer should open

**Comment by heejaechang** [comment]
I just debugged and we correctly report "usercontrol" to update service but solution explorer seems not responding to new data.

**Comment by davkean** [comment]
Moved to: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935124.
