### ISSUE TITLE
Unable to create a delegate pointing to a static local function from within the function

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#36627]
**Version Used**: 
![image](https://user-images.githubusercontent.com/41759/59884314-cc9b6d80-936c-11e9-8139-dffe186182a4.png)

**Steps to Reproduce**:

```C#
    using System.Linq;

    class Node
    {
        public int Value;
        public Node[] Children = Array.Empty<Node>();
    }

    class Program
    {
        static void Main()
        {
            static int f(Node n)
                => n.Value + n.Children.Sum(f);
        }
    }
```

**Expected Behavior**:

Compiles w/o errors.

**Actual Behavior**:

`Error CS8422: A static local function cannot contain a reference to 'this' or 'base'.`

**Comment by jcouv** [comment]
Tagging @cston @agocke

**Comment by jcouv** [comment]
@cston Might this be a simple fix? If not, push out to Compiler.Next

**Comment by tuespetre** [comment]
This should be able to be closed, a duplicate was entered and resolved by @svick about 3 weeks ago:

https://github.com/dotnet/roslyn/issues/38240

**Comment by ericwj** [comment]
The odd thing I run into this only when building from the command line. Visual Studio appears to be happy but `dotnet build` will crash, even with what I presume are the latest bits that Visual Studio should also use -- or not? I still have preview 9 installed but neither VS nor dotnet should be using that anymore.
```
VS 16.4.0 Preview 1
```

```XML
<TargetFramework>netcoreapp3.0</TargetFramework>
<LangVersion>Preview</LangVersion>
``` 
```
dotnet --version
3.0.100
```

**Comment by agocke** [comment]
Confirmed that this is fixed in `master`

@ericwj I believe this fix is in the newest preview of .NET Core. https://dotnet.microsoft.com/download/dotnet-core/3.1
