### ISSUE TITLE
New CSPROJ format: Conditional compilation code not correctly visualized

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36626]
When using the new CSPROJ fomat conditional code elements are not correctly visualized.
Inactive code es expected to be printed in gray.

Visual Studio: 15.3.5

Example:
Switching betwenn Debug and Release mode does not change the color of the two 'Console.WriteLine' statements:

#if DEBUG
            Console.WriteLine(&quot;DEBUG&quot;);
#endif

#if !DEBUG
            Console.WriteLine(&quot;NOT DEBUG&quot;);
#endif

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/140199/new-csproj-format-conditional-compilation-code-not.html
VSTS ticketId: 516771_
_These are the original issue comments:_

Jinu Joseph [MSFT] on 11/1/2017, 00:37 PM (596 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

Igor Pietraszko on 4/21/2018, 08:56 AM (425 days ago): <p>I have noticed the same behaviour but if I shut down VS2017 and then reopen it and go to the file in question, the correct code block is highlighted.  I am on VS2017 15.6.6.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
![image](https://user-images.githubusercontent.com/12449387/59882072-1af93e00-9366-11e9-83c7-cc086992f82b.png)

**Comment by sharwell** [comment]
This should be fixed for Visual Studio 2019.

/cc @jasonmalinowski

**Comment by jasonmalinowski** [comment]
Correct, should work in 2019.

**Comment by vsccarl** [comment]
This is fixed in 16.2, see below:
![image](https://user-images.githubusercontent.com/12900364/59882732-e6868180-9367-11e9-8a62-c57a40f41864.png)
![image](https://user-images.githubusercontent.com/12900364/59882754-f4d49d80-9367-11e9-8da6-d14727477d7d.png)

**Comment by dpoeschl** [comment]
I also played with it a bit and 2019 looks good.
