### ISSUE TITLE
Compiler should optimize conversion from boolean to integer

### ISSUE THREAD

**Issue by carlreinke** [dotnet/roslyn#36625]
**Version Used**: 3.1.1

**Steps to Reproduce**:

```csharp
public static class C
{
    public static int M1(int i) => i < 0 ? 1 : 0;
    public static bool M2(int i) => i < 0;
}
```
Compile with "Optimize Code" enabled.

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAdhMcoAOEAxnAAQByAsAFADetZTZAAgMysCMAbKwExkAwo2YMazCaw4seZAJZYYZALKcAFAqVyAlGQC8APnlkAPGQAMZAPxlOZEBYDcIyVK69gAe08AbFXw1FeV1DYzNzZ3FmAF9aWJogA===

**Expected Behavior**:
Same IL code for both methods.

**Actual Behavior**:
```
.method public hidebysig static 
    int32 M1 (
        int32 i
    ) cil managed 
{
    // Method begins at RVA 0x2050
    // Code size 8 (0x8)
    .maxstack 8

    IL_0000: ldarg.0
    IL_0001: ldc.i4.0
    IL_0002: blt.s IL_0006

    IL_0004: ldc.i4.0
    IL_0005: ret

    IL_0006: ldc.i4.1
    IL_0007: ret
} // end of method C::M1

.method public hidebysig static 
    bool M2 (
        int32 i
    ) cil managed 
{
    // Method begins at RVA 0x2059
    // Code size 5 (0x5)
    .maxstack 8

    IL_0000: ldarg.0
    IL_0001: ldc.i4.0
    IL_0002: clt
    IL_0004: ret
} // end of method C::M2
```

**Comment by CyrusNajmabadi** [comment]
This feels like a an optimization that the jit could do.  Putting it in the compiler just means its only available for C# and not any other .net langauge.  Note: i'm really curious if this could ever matter that much.  How many times do you have a hotpath that literally has the code `i < 0 ? 1 : 0` in it?

**Comment by carlreinke** [comment]
I have an array of `bool`s that I want to pack into an array of `byte`s, so substitute an array access instead of `i < 0`, add some bit operations, and put it in a loop, and you've got my hotpath.

**Comment by CyrusNajmabadi** [comment]
What perf difference do you see?

**Comment by CyrusNajmabadi** [comment]
> and you've got my hotpath.  

can you just use unsafe here?

**Comment by carlreinke** [comment]
I can, but given that C# doesn't have a safe cast between `bool` and numeric types, I don't think it's unreasonable to ask that the compiler generate good IL for the expressions that are used in place of a safe cast.

**Comment by CyrusNajmabadi** [comment]
> I don't think it's unreasonable to ask that the compiler generate good IL

i think the IL is fine.  This is an exceptionally niche case.  And it's unclear to me why this wouldn't be better suited for the JIT to do.  As an IL optimization, you would require all compilers have to implement this optimization.  If you do it in the jit, it is done only once.

**Comment by CyrusNajmabadi** [comment]
> but given that C# doesn't have a safe cast between bool and numeric types

?

```c#
        bool t = true, f = false;

        var bools = new[] { t, f, t, f };

        fixed (bool* bp = bools)
        {
            Console.WriteLine(*(byte*)bp);
            Console.WriteLine(*(byte*)(bp + 1));
            Console.WriteLine(*(byte*)(bp + 2));
            Console.WriteLine(*(byte*)(bp + 3));
        } 
```

**Comment by carlreinke** [comment]
> 
> 
> > but given that C# doesn't have a safe cast between bool and numeric types
> 
> ?
> 
> ```cs
>         bool t = true, f = false;
> 
>         var bools = new[] { t, f, t, f };
> 
>         fixed (bool* bp = bools)
>         {
>             Console.WriteLine(*(byte*)bp);
>             Console.WriteLine(*(byte*)(bp + 1));
>             Console.WriteLine(*(byte*)(bp + 2));
>             Console.WriteLine(*(byte*)(bp + 3));
>         } 
> ```

`error CS0214: Pointers and fixed size buffers may only be used in an unsafe context`

Not "safe".

**Comment by CyrusNajmabadi** [comment]
I mentioned:

> can you just use unsafe here?

If this is a big hotspot, i would just use unsafe here.  Or, i would move this suggestion over to the JIT so it can be applied to all languages.

**Comment by canton7** [comment]
This seems to be the same as the issue which was discussing optimising `foo ? true : false` (although I can't find it at the moment)

**Comment by DoctorKrolic** [comment]
This has already been implemented in https://github.com/dotnet/roslyn/pull/67191. If you follow the link in the issue description and switch to IL view, you will see, that IL for `M1` and `M2` are equivalent and branchless. The issue can be closed as completed now
