### ISSUE TITLE
Source server support broken in VS

### ISSUE THREAD

**Issue by daytonellwanger** [dotnet/roslyn#36641]
I was trying to debug Roslyn in VS. I was able to get symbols from symweb, but when I hit a breakpoint, it was unable to find the source.

I don't know if this is a VS bug or a bug with Roslyn source server support.

**Comment by daytonellwanger** [comment]
I believe @heejaechang has also hit this issue intermittently.

**Comment by daytonellwanger** [comment]
@tmat I believe this is something you own.

**Comment by tmat** [comment]
What version of Roslyn assembly was that?

**Comment by daytonellwanger** [comment]
3.2.0-beta3-19312-05+5905d757a89126ebbcdb383b1a10cadda8c6fdc3

**Comment by tmat** [comment]
This particular version doesn't have Source Link. I recall we had an infrastructure issue that caused Source Link to not be included. Please, try the latest version.
