### ISSUE TITLE
vb-semantic.docx example uses MetadataFileReference which can't be found

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#3665]
In https://github.com/dotnet/roslyn/blob/master/docs/samples/vb-semantic.docx there is the line 

``` vb
Dim compilation As Compilation =
                VisualBasicCompilation.Create("HelloWorld").
                                       AddReferences(New MetadataFileReference(
                                                         GetType(Object).Assembly.Location)).
                                       AddSyntaxTrees(tree)
```

Visual Studio 2015 RC complains Type 'MetadataFileReference' not defined. I have searched all the source and I don't see it.

**Comment by tmat** [comment]
The API changed to MetadataReference.CreateFromFile.

**Comment by AnthonyDGreen** [comment]
@paul1956, thanks for reporting this. I've updated the walkthrough. However, we're retiring the word docs in favor of markdown. Updated versions are available on our wiki. You can find a full listing of them [here](https://github.com/dotnet/roslyn/wiki/Samples-and-Walkthroughs). They should be fully up-to-date but feel free to file bugs if you find any issues we may have missed.

**Comment by AnthonyDGreen** [comment]
FYI, I marked this as "Won't fix" since ultimately we'll be deleting the word docs. Again, the issue should be fixed in the wiki version.
