### ISSUE TITLE
Method CastExpression in Microsoft.CodeAnalysis.CSharp has no VB equlivant

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#3666]
Is this a bug? Can I call the one in CSharp Visual Studio 2015 RC doesn't offer that as a Fix option.

**Comment by AnthonyDGreen** [comment]
Hey @paul1956,

I'm not sure I understand your question. Could you restate it?

**Comment by paul1956** [comment]
Works

        private static ExpressionSyntax Cast(ExpressionSyntax expression, ITypeSymbol targetType)

        {

            if (targetType == null)

            {

                return expression;

            }

 

            var type = ParseTypeName(targetType.ToDisplayString());

 

            return CastExpression(type, Parenthesize(expression))

                .WithAdditionalAnnotations(Simplifier.Annotation);

        }

 

 

Fails

Private Shared Function Cast(expression As ExpressionSyntax, targetType As ITypeSymbol) As ExpressionSyntax

                If targetType Is Nothing Then

                                Return expression

                End If

 

                Dim type = ParseTypeName(targetType.ToDisplayString())

 

                Return CastExpression(type, Parenthesize(expression)).WithAdditionalAnnotations(Simplifier.Annotation)

End Function

**Comment by svick** [comment]
I believe that's because VB simply doesn't have C-style cast. AFAIK, the VB equivalent is [`CType`](https://msdn.microsoft.com/en-us/library/4x2877xb.aspx), so you should probably use that:

```vb.net
CTypeExpression(Parenthesize(expression), type)
```

**Comment by AnthonyDGreen** [comment]
@svick is correct. In the VB API you'll need to construct a CTypeExpression.

**Comment by paul1956** [comment]
It doesn't matter if it is called CType, CTypeExpression or CastExpression the functionality need to be provided and I am not seeing how to get the functionality. Looking at the C# source of CastExpression it calls SyntaxFactory.CastExpression also not available to VB. Below I have ported both to VB.NET. The problem is the line below, and the references to "InternalSyntax". This line produces 9 errors.

            Return DirectCast(Syntax.InternalSyntax.SyntaxFactory.CastExpression(DirectCast(openParenToken.Node, Syntax.InternalSyntax.SyntaxToken), If(type Is Nothing, Nothing, DirectCast(type.Green, Syntax.InternalSyntax.TypeSyntax)), DirectCast(closeParenToken.Node, Syntax.InternalSyntax.SyntaxToken), If(expression Is Nothing, Nothing, DirectCast(expression.Green, Syntax.InternalSyntax.ExpressionSyntax))).CreateRed(), CastExpressionSyntax)



C#
public static CastExpressionSyntax CastExpression(TypeSyntax type, ExpressionSyntax expression)
    {
      return SyntaxFactory.CastExpression(SyntaxFactory.Token(SyntaxKind.OpenParenToken), type, SyntaxFactory.Token(SyntaxKind.CloseParenToken), expression);
public static CastExpressionSyntax CastExpression(SyntaxToken openParenToken, TypeSyntax type, SyntaxToken closeParenToken, ExpressionSyntax expression)
    {
      switch (openParenToken.Kind())
      {
        case SyntaxKind.OpenParenToken:
          break;
        default:
          throw new ArgumentException("openParenToken");
      }
      if (type == null)
        throw new ArgumentNullException(nameof(type));
      switch (closeParenToken.Kind())
      {
        case SyntaxKind.CloseParenToken:
          break;
        default:
          throw new ArgumentException("closeParenToken");
      }
      if (expression == null)
        throw new ArgumentNullException(nameof(expression));
      return (CastExpressionSyntax)Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxFactory.CastExpression((Syntax.InternalSyntax.SyntaxToken)openParenToken.Node, type == null ? null : (Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.TypeSyntax)type.Green, (Syntax.InternalSyntax.SyntaxToken)closeParenToken.Node, expression == null ? null : (Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExpressionSyntax)expression.Green).CreateRed();
    }
VB.NET
    Public Shared Function CastExpression(type As TypeSyntax, expression As ExpressionSyntax) As CastExpressionSyntax
        Return CastExpression(SyntaxFactory.Token(SyntaxKind.OpenParenToken), type, SyntaxFactory.Token(SyntaxKind.CloseParenToken), expression)
    End Function
    Public Shared Function CastExpression(openParenToken As SyntaxToken, type As TypeSyntax, closeParenToken As SyntaxToken, expression As ExpressionSyntax) As CastExpressionSyntax
        Select Case openParenToken.Kind()
            Case SyntaxKind.OpenParenToken
                Exit Select
            Case Else
                Throw New ArgumentException("openParenToken")
        End Select
        If type Is Nothing Then
            Throw New ArgumentNullException(NameOf(type))
        End If
        Select Case closeParenToken.Kind()
            Case SyntaxKind.CloseParenToken
                Exit Select
            Case Else
                Throw New ArgumentException("closeParenToken")
        End Select
        If expression Is Nothing Then
            Throw New ArgumentNullException(NameOf(expression))
        End If
        Return DirectCast(Syntax.InternalSyntax.SyntaxFactory.CastExpression(DirectCast(openParenToken.Node, Syntax.InternalSyntax.SyntaxToken), If(type Is Nothing, Nothing, DirectCast(type.Green, Syntax.InternalSyntax.TypeSyntax)), DirectCast(closeParenToken.Node, Syntax.InternalSyntax.SyntaxToken), If(expression Is Nothing, Nothing, DirectCast(expression.Green, Syntax.InternalSyntax.ExpressionSyntax))).CreateRed(), CastExpressionSyntax)
    End Function

**Comment by AnthonyDGreen** [comment]
@paul1956, if you're trying to construct roughly equivalent syntax in VB for the syntax you're creating in C# then you have to understand the specifics of each language and what the analogs are. You need to call the `Microsoft.CodeAnalysis.VisualBasic.SyntaxFactory.CTypeExpression` factory method. There is not a `CastExpression` method nor should there be. The names of the factory methods reflect the names of the nodes, not the desired semantics. For example, an `IsExpression` in VB (`a Is b`) has a completely different meaning from an `IsExpression` in C# (`a is Type`). Likewise, a `TypeOfExpression` in VB (`TypeOf a Is T`) is different from a `TypeOfExpression` in C# (`typeof(Type)`).

**Comment by paul1956** [comment]
The C# code is from someone else’s VSIX to Refactor String.Format, I want to do the same for VB and could not find the equivalent for CastExpression. Yes I want it to work for VB, but in this case the logic should be identical. 

 

Thanks that was the first answer that made sense to me.

 

I used SyntaxFactory.CTypeExpression and everything works as expected. I think it would help to have a table listing some of these “equivalent” methods.
