### ISSUE TITLE
Compile error in abstract generic class with generic constraint to itself error on using this keyboard to call a method that expects that generic class.

### ISSUE THREAD

**Issue by smartcodinghub** [dotnet/roslyn#36675]
I found a compile error when using generic constraints in an abstract class (`Entity<T>`)that restricts the generic type to inherit from the abstract class itself (`where T : Entity<T>`) and then use methods inside de class using the this keyword. Since its an abstract class, 'this' will always be an object that inherits the abstract class, but the compiler gives an error.

I don't know if this is because the runtime can't support this, that the compiler doesn't support this edge case or this is by the language design (some context on this Eric's post: https://blogs.msdn.microsoft.com/ericlippert/2008/05/19/a-generic-constraint-question/).

The code to play with this issue:

```csharp
public abstract class Entity<T> where T : Entity<T>
{
	Guid Id { get; }
	long Version { get; }
	public List<IEvent<T>> PendingEvents { get; protected set; }
	public List<IEvent<T>> AppliedEvents { get; protected set; }

	public void Load() { ApplyDefaults(this); } // The error is here, on this

	public static void ApplyDefaults(T something) { }
}

public interface IEvent<T> where T : Entity<T>
{
	Guid EventId { get; }
	string EventType { get; }
}

public class Order : Entity<Order>
{
}

public class OrderCreated : IEvent<Order>
{
	public Guid EventId => throw new NotImplementedException();
	public string EventType => throw new NotImplementedException();
}
```

The last two classes (`Order`) is just to give some context, but unnecessary. 

_**I know that I can avoid this with other class design (and I'll have to) but with the language specs I think this must be supported by the compiler and its just an edge cased that has been overlooked**_

**Comment by agocke** [comment]
I don't think this is safe. Consider

```
public sealed class A : Entity<A>
{}
public sealed class B : Entity<A>
{}
```
In `B`, the substituted signature is `ApplyDefaults(A something)`, but `this` is `B`, and the two types have no relationship.
