### ISSUE TITLE
Unable to customize the generated InternalsVisibleTo attributes.

### ISSUE THREAD

**Issue by jakesays** [dotnet/roslyn#3668]
For doing custom, private builds of Roslyn, it is sometimes required to have access to the internals of various assemblies. One example of this need is for code completion.

It is possible to manually edit the requisite project files to inject InternalsVisibleTo attributes, but doing so is tedious and error prone. It must also be done after every pull from upstream.

My proposed solution to this is to add an extension point to VSL.Settings.targets. This extension point would load a local project file that contains `<InternalsVisibleTo/>` elements, which would be injected in to targeted projects during build.

The proposed change to VSL.Setings.targets:

```xml

  <Import Project="$(MSBuildThisFileDirectory)..\..\..\..\..\LocalInternalsVisibleTo.props"
    Condition="Exists('$(MSBuildThisFileDirectory)..\..\..\..\..\LocalInternalsVisibleTo.props')" />

```

And an example LocalInternalsVisibleTo.props:

```xml

<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
	<InternalsVisibleTo Include="MyCustomAssembly" Condition=" '$(MSBuildProjectName)' == 'Features' OR '$(MSBuildProjectName)' == 'Workspaces.Desktop'" />
	<InternalsVisibleTo Include="MyOtherCustomAssembly" Condition=" '$(MSBuildProjectName)' == 'Features'" />
  </ItemGroup>
</Project>

```

**Comment by davkean** [comment]
Based on this https://github.com/dotnet/roslyn/pull/3669, we're not going to do this.
