### ISSUE TITLE
The namespace for "Show items from unimported namespaces" is not visible as you are typing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#36694]
![UnimportedNamespaces](https://user-images.githubusercontent.com/1103906/59992057-3083a600-968d-11e9-89c6-85c751119c22.gif)

**Comment by davkean** [comment]
tag @genlu

**Comment by genlu** [comment]
@AmadeusW Do you know what might have caused this? Looks like an issue on editor side.

**Comment by Dreamescaper** [comment]
I suppose you have type with veeeery long name somewhere there?

**Comment by genlu** [comment]
Filed an internal bug to track this issue:
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/939787

**Comment by AmadeusW** [comment]
I'll try to repro with a combination of long names here and there.

**Comment by AmadeusW** [comment]
I can't repro this, @davkean can you share a link or steps to repro?
The completion list resizes up and even leaves the boundaries of VS.
![image](https://user-images.githubusercontent.com/1673956/61393105-16e11300-a875-11e9-86f4-98e9af0a23a1.png)

**Comment by davkean** [comment]
I can still repro it, here's the repro:

![image](https://user-images.githubusercontent.com/1103906/61416813-63d9ed80-a938-11e9-808e-8defb5faafd4.png)


1. git clone http://github.com/dotnet/project-system
2. `>cd project-system`
3. `build.cmd`
4. `ProjectSystem.sln`
5. Navigate to `WindowsFormsEditorProviderTests.cs`
6. Remove `using Xunit;` in the file
7. Repro above steps exactly
