### ISSUE TITLE
Attributes have a "attribute" suffix when "Show items from unimported namespaces" is turned on

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#36693]
Unlike when they are in scope, attributes in unimported namespaces show up and are committed with the "attribute" syntax.

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/1103906/59991880-72601c80-968c-11e9-8519-43c36d8e8bc6.png)

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/1103906/59991842-48a6f580-968c-11e9-8c64-13791e86c23c.png)

**Comment by davkean** [comment]
tag @genlu

**Comment by Dreamescaper** [comment]
Duplicate : #35540
