### ISSUE TITLE
(Feature request) support for simple .NET core project run without .csproj file 

### ISSUE THREAD

**Issue by longtth** [dotnet/roslyn#36691]
**Version Used**: 
2.1.7 
**Steps to Reproduce**:

1. in a blank folder, create a new file named `Program.cs` with a simple 
```
using Systems; 
void Main() 
{}
```
2. open `cmd` in this folder, input `dotnet run .`  

**Expected Behavior**:
dotnet with scan all cs files in folder and build, then run the Main() 
if there is 2 Main(), throw an exception 

**Actual Behavior**:
Exception throw, required a `.csproj` to build/run 

**Note**
If dotnet core support this feature, it will be incredible easy for teachers to use C# for teaching simple thing like HelloWorld, if, for, while, and demo Algorithm instead of using Python. 
P/S: 
I know we could open the folder in cmd, run `dotnet new console` then edit the `Program.cs` generated.

**Comment by jmarolf** [comment]
I believe this should be moved to https://github.com/dotnet/cli

**Comment by longtth** [comment]
Closed to think more deeper, I will post it to /dotnet/cli later
