### ISSUE TITLE
IDE0067 fires for using declaration with escape 

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#36692]
**Version Used**: 16.2.0-pre.2.0+29006.145

**Steps to Reproduce**:

IDE0067 "disposable object never disposed" should not fire in `M1` and does not fire in `M2`.

```c#
void M1(string path)
{
    using var stream = File.OpenRead(path); // IDE0067 fires
    S(stream);
}

void M2(string path)
{
    using (var stream = File.OpenRead(path)) // IDE0067 does not fire here
        S(stream);
}

static void S(Stream s)
{
}
```

**Expected Behavior**:

No diagnostic.

**Actual Behavior**:

Diagnostic.

**Comment by mavasani** [comment]
This should be fixed with https://github.com/dotnet/roslyn/pull/36734
