### ISSUE TITLE
Please add SyntaxFactory.ParseDeclaration

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#367]
> Subject: Could we have SyntaxFactory.ParseDeclaration(...)?
> From: Mark Zhou
> To: Roslyn Discussion
> Sent: Sunday, December 14, 2014 7:25 PM

Hi, 

I am doing a side analysis project that requires adding/removing `MemberDeclarationSyntax` and derives for the code fix. some code fix providers in my code heavily depend on `SyntaxFactory` and `SyntaxGenerator` APIs. When I explore `ParseXxx` methods from `SyntaxFactory`, I noticed there isn’t one for simply parsing a text into `MemberDeclarationSyntax`. Adding a member into a type becomes a mess for me – since you need to call either `SyntaxFactory.MethodDeclaration` or `SyntaxGenerator.AddMembers` or equivalent. 

My ask is whether we can have one API to parse text to a member declaration? 

Thanks,
Mark.

[Migrated from TFS DevDiv 1096321]

**Comment by mattwar** [comment]
We could have that method.  Constructors and destructors would be a problem.  The typical way it is done without this specific method is to parse a compilation unit with a type declaration containing your member, and then pick the member out of the results.

**Comment by gafter** [comment]
We would change the way we parse constructors to make this work. The error about the name not matching (or better, the return type missing) would be moved to the declaration phase.

**Comment by mattwar** [comment]
How would you know if it was a constructor or a method with a missing return type?

**Comment by gafter** [comment]
@mattwar it would parse as a constructor. Declaration analysis would be responsible for giving a nice error message if the name doesn't match the enclosing type.

**Comment by gafter** [comment]
@AnthonyDGreen Anthony, would you care to chime in on if/when we would want to do this?

**Comment by AnthonyDGreen** [comment]
I believe we need Parse* methods for each of the common scenarios: ParseCompilationUnit, ParseMember, ParseStatement, ParseExpression. ParseMember (or ParseDeclaration) would probably be required for documentation snippets anyway as most examples don't include all surrounding boilerplate.

**Comment by gafter** [comment]
@AnthonyDGreen Great! Please work with @theoy to assign a milestone and it shall be done.

**Comment by mattwar** [comment]
@gafter I still see a problem with the constructor parsing. The parser only ever parses a constructor if there is no type and the method name matches the enclosing type name, otherwise it always comes off as a method.  I originally had a ParseMember method long ago but it would either never produce constructors/destructors or you had to supply the type name to feed into the parser for context.

**Comment by gafter** [comment]
@mattwar The `ParseMember` that I envision would parse a constructor if there is no type, no matter what the name of the enclosing type is. If the name doesn't match you'll get a semantic error about the return type missing from the method declaration.

**Comment by gafter** [comment]
@mattwar FYI, in the current version of the compiler the parser does not use the name of the enclosing type any longer to determine if something is a method or constructor. It bases its decision totally on the local syntax. We still give the same kind of good error message as before, but in semantic analysis (if a constructor is found in a class with a different name, we report a missing return type). The change occurred in https://github.com/dotnet/roslyn/pull/18940.

This work item is therefore unblocked.
