### ISSUE TITLE
Should nullability attributes be honored on ref return values?

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#36703]
We could update the attribute target for `DisallowNull` to allow this target, then we would warn for assigning a maybe-null value to it (for example `RefReturning() = maybeNull;`).

```C#
        [Fact]
        public void DisallowNull_RefReturnValue_05()
        {
            var source0 =
@"using System.Diagnostics.CodeAnalysis;
public class A
{
    public static T? F1<T>(T t) where T : class => throw null!;
    [return: DisallowNull] public static ref T? F2<T>(T t) where T : class => throw null!;
}";
            var comp = CreateNullableCompilation(new[] { DisallowNullAttributeDefinition, source0 });
            comp.VerifyDiagnostics(
                // (5,14): error CS0592: Attribute 'DisallowNull' is not valid on this declaration type. It is only valid on 'property, indexer, field, parameter' declarations.
                //     [return: DisallowNull] public static ref T? F2<T>(T t) where T : class => throw null!;
                Diagnostic(ErrorCode.ERR_AttributeOnBadSymbolType, "DisallowNull").WithArguments("DisallowNull", "property, indexer, field, parameter").WithLocation(5, 14)
                );

            var source1 =
@"using System.Diagnostics.CodeAnalysis;
namespace System.Diagnostics.CodeAnalysis
{
    [AttributeUsage(AttributeTargets.All)]
    public sealed class DisallowNullAttribute : Attribute
    {
    }
}
public class A
{
    public static ref T? F1<T>(T t) where T : class => throw null!;
    [return: DisallowNull] public static ref T? F2<T>(T t) where T : class => throw null!;
    static void Main()
    {
        object? y = new object();
        F1(y) = y;
        F2(y) = y; // DisallowNull is ignored
    }
}";
            var comp2 = CreateNullableCompilation(source1);
            comp2.VerifyDiagnostics();
        }
```

Tagging @stephentoub. What do you think?

**Comment by stephentoub** [comment]
> Tagging @stephentoub. What do you think?

Would that DisallowNull flow through ref assignments?  e.g. if I had `[return: DisallowNull] public static ref T? F2<T>(...)` as in your example, and I did:
```C#
F2() = null;
```
that would warn, but what about:
```C#
ref T? t = ref F2();
t = null;
```
Would that warn?

Allowing `[DisallowNull]` on returns is meaningless in the vast majority of returns, so it could be misleading to allow it?

That said, if we think it's helpful, I don't have strong concerns, and obviously it's a trivial change.  At this point though we're very late for making API changes for 3.0.

cc: @safern, @danmosemsft

**Comment by jcouv** [comment]
> Would that DisallowNull flow through ref assignments?

`DisallowNull` would not flow, so there would be no warning in your second example. The only scenario that we'd be able to protect is direct assignments to an invocation (`RefReturning() = maybeNull;`).
If we wanted to protect ref assignment scenarios, we would probably need a way to mark a ref local with `[DisallowNull]` or something similar, and I'm not sure how useful it would be.

I'm okay to close this issue/question right away since the value does seem limited.

**Comment by jcouv** [comment]
Tagging @cston as FYI (I closed this issue)
