### ISSUE TITLE
/Users/vsts/.nuget/packages/microsoft.net.compilers/3.1.1/tools/Microsoft.CSharp.Core.targets(59,5): error MSB6006: "csc.exe" exited with code 8. 

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/roslyn#36705]
CI:  VSTS
.NET Core:  2.2.105
OS:  MacOS
```
##[error]Error: The process '/Users/vsts/hostedtoolcache/dncs/2.2.105/x64/dotnet' failed with exit code 1
##[error]Dotnet command failed with non-zero exit code on the following projects : 
```
I think this problem is the same as this one.（https://github.com/dotnet/roslyn/issues/36616 ）
How to solve it?

**Comment by jcouv** [comment]
@NMSAzulX Could you provide details of how we might reproduce this issue?

@agocke @chsienki Would you know how to collect a crash dump on MacOS?

**Comment by agocke** [comment]
The `Microsoft.Net.Compilers` package is desktop framework only. You cannot use it on Linux or Mono. Why do you need to downgrade the version of the compiler?

**Comment by NMSAzulX** [comment]
@agocke  @jcouv This is my mistake. Thanks to jcouv told me to use "Microsoft.Net.Compilers.Toolset" to let me solve the problem of this century.  T _ T

**Comment by agocke** [comment]
Do you need to use the package at all? Why do you need to downgrade your compiler version?

**Comment by NMSAzulX** [comment]
@agocke I really need the ability to compile, and for this I encapsulate a [project ](https://github.com/dotnetcore/Natasha)to replace emit.

> Why do you need to downgrade your compiler version?

??? You mean:. NET Core: 2.2.105?   I saw a person in a Issue who said v2.2.105 worked well.
That issue is about error 'MSB6006: "csc.exe" '.

**Comment by agocke** [comment]
I see, I did not know you were using the compilers for a different purpose.
