### ISSUE TITLE
[Proposal] Cached results with auto implemented backing field

### ISSUE THREAD

**Issue by emreaydinceren** [dotnet/roslyn#3671]
![picture3](https://cloud.githubusercontent.com/assets/13038027/8338493/3656238e-1a66-11e5-858b-4707c1651944.gif)

compiler can generate a backing field for method and return value from backing field if backing field is null

**Comment by HaloFour** [comment]
Sounds identical to the following proposals for lazy properties:

#3251 #3415 #3630

**Comment by emreaydinceren** [comment]
@HaloFour  I agree, it looks like #3251 ... I cannot say for the other ones
