### ISSUE TITLE
Requesting "Close All Regions" in document ability

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36739]
VSF_TYPE_MARKDOWNPlease add a tools for closing all Regions in the currently open document. The tool should allow operation by hot-key and toolbar/menu item.

NOTE: By &quot;Regions&quot;,  I am referring to areas of code withing a #Region&quot;&quot;/#End Region block. It should NOT close unfolded sections of code such as methods and classes.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/612877/requesting-close-all-regions-in-document-ability.html
VSTS ticketId: 934093_
_These are the original issue comments:_

Jane Wu [MSFT] on 6/19/2019, 00:39 AM (6 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
@olegtk  this is a request for you guys.  Can you reactivate on your end?

**Comment by olegtk** [comment]
@CyrusNajmabadi the request is to collapse specifically #region/#endregion blocks. I'm not sure we can differentiate these from other collapsible regions (e.g. created by user ad hoc) on the editor side.
