### ISSUE TITLE
Refactoring tool: make function async

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36737]
VSF_TYPE_MARKDOWNIt would be great to have right click -&gt; refactoring tools -&gt; MAKE METHOD ASYNC.
This would make the current function async, and update its callers to await and become async too, recursively.
Functions with out and ref parameters would change their signature to have only 'in' parameters and return all values within a tuple.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/608719/refactoring-tool-make-function-async.html
VSTS ticketId: 919128_
_These are the original issue comments:_

Jane Wu [MSFT] on 6/17/2019, 01:29 AM (8 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by alrz** [comment]
Looks like there's an implementation here: https://github.com/microsoft/vs-threading/blob/master/src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/FixUtils.cs

@sharwell Could we possibly port it to roslyn? if not how we can use that (without installing a package)?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.  There's also an impl for this in vsthreading.
