### ISSUE TITLE
Quick actions show different options on selection

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36756]
<p>Quick actions show different options depending on whether a cursor is placed on an identifier or a character of the identifier is selected. For example, it is not possible to generate a constructor parameter from a field when a cursor is placed on this field's name, it's only possible when at least one character of this name is selected.</p><p>I'd like to be able to generate constructor parameters without having to use selection first.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/618566/quick-actions-show-different-options-on-selection.html
VSTS ticketId: 936358_
_These are the original issue comments:_

Visual Studio Feedback System on 6/24/2019, 03:25 AM (35 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by petrroll** [comment]
This one is not within the immediate scope of my work for #35525 as it deals with selection/usage of _multiple_ nodes. I might try to look at it later.

**Comment by petrroll** [comment]
Unfortunately didn't get chance to move generateXYZ refactorings to new system within the time of my internship.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
