### ISSUE TITLE
Code fixer for `TOpen?` to suggest using nullability attributes

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#36753]
For unconstrained type `T`:
- `T? M() ...` could be fixed to `[MaybeNull] T M() ...`
- `void M(T? x) ...` could be fixed to `void M([AllowNull] T x) ...`
- `void M(ref T? x) ...` could be fixed to `void M([AllowNull, MaybeNull] ref T x) ...`

Thanks @RikkiGibson for the idea

**Comment by jcouv** [comment]
This is no longer applicable since `T?` is now part of the language. Closing

**Comment by RikkiGibson** [comment]
So happy we don't need this!
