### ISSUE TITLE
Incorrect cast is redundant in switch expression with nullable value type.

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#36755]
**Version Used**: 
<img width="213" alt="Capture" src="https://user-images.githubusercontent.com/5749229/60136351-cc2e1880-9758-11e9-9740-d59d084c05f3.PNG">

**Steps to Reproduce**:

Input this code
```csharp
class Program
{
    void M()
    {
        string numberString = "One";
        Numbers? number = numberString switch
        {
            "One" => (Numbers?)Numbers.One,
            "Two" => Numbers.Two,
            _ => null,
        };
    }
}

enum Numbers
{
    One,
    Two
}
```
The cast `(Numbers?)` in case "One" is marked as unnecessary.
<img width="260" alt="Capture2" src="https://user-images.githubusercontent.com/5749229/60136716-cab12000-9759-11e9-96a6-b12df9aef7c2.PNG">

Removing the cast causes a compiler error.
`Error	CS0037	Cannot convert null to 'Numbers' because it is a non-nullable value type`
<img width="255" alt="Capture3" src="https://user-images.githubusercontent.com/5749229/60136762-f03e2980-9759-11e9-8bf4-d99cebd5512b.PNG">

A few followup notes
1.  It is a little confusing that casting the first element of the switch expression is required, even if I explicitly define the expected return type as Numbers?.  The IDE also offers no assistance that casting the first member of the switch expression may fix the compiler error.
2.  Converting a switch statement to switch expression in this instance yields invalid code (it doesn't add the appropriate cast to the first case).

**Comment by dibarbet** [comment]
FYI - @ryzngard @jasonmalinowski as a C# 8 feature

**Comment by sungam3r** [comment]
I faced the same problem.

Before refactoring:
```c#
bool? Convert(byte value)
            {
                switch (value)
                {
                    case 2: return true;
                    case 1: return false;
                    case 0: return null;
                    default: throw new NotSupportedException(value.ToString());
                }
            }
```

after IDE0066 (convert switch statement to expression) automatic refactoring via light bulb suggestion:
```c#
bool? Convert(byte value)
            {
                return value switch
                {
                    2 => true,
                    1 => false,
                    0 => null,   // CS0037	Cannot convert null to 'bool' because it is a non-nullable value type	
                    _ => throw new NotSupportedException(value.ToString()),
                };
            }
```
