### ISSUE TITLE
Dead link in object. Equals snippet

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36757]
VSF_TYPE_MARKDOWNUse the equals snippet, which generates smth like below. The links to the guidelines are dead. Sad.

```csharp
 public override bool Equals(object obj)
        {
            //       
            // See the full list of guidelines at
            //   http://go.microsoft.com/fwlink/?LinkID=85237    --&gt; dead
            // and also the guidance for operator== at
            //   http://go.microsoft.com/fwlink/?LinkId=85238    --&gt; dead
            //

if (obj == null || GetType() != obj. GetType())
            {
                return false;
            }

// TODO: write your implementation of Equals() here
            throw new NotImplementedException();
            return base. Equals(obj);
        }
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/617955/dead-link-in-objectequals-snippet.html
VSTS ticketId: 936159_
_These are the original issue comments:_

Visual Studio Feedback System on 6/24/2019, 02:39 AM (36 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski Do you know how this happens.  Isn't hte point of fwlinks that they should keep working in the future?

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in legacy snippet scenarios.
