### ISSUE TITLE
Auto readonly modifier deletes comments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36759]
Write the following C# code inside a class:

```
//Any comment
private int a, b;
```

Don't use these members anywhere. Visual Studio will suggest adding the &quot;readonly&quot; modifier to them. Pressing alt+enter then adding the modifier adds it as expected, but REMOVES the comment above.
Expected behavior: comment will stay untouched.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/617233/auto-readonly-modifier-deletes-comments.html
VSTS ticketId: 935590_
_These are the original issue comments:_

Visual Studio Feedback System on 6/24/2019, 01:08 AM (38 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by gnovack** [comment]
I'd like to take a look at this one if no one has picked it up already.

**Comment by CyrusNajmabadi** [comment]
@gnovack Go for it!

**Comment by Youssef1313** [comment]
This was fixed by #36994 and can be closed now I think.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Can we close this?

**Comment by CyrusNajmabadi** [comment]
Doesn't repro.  Closing out.
