### ISSUE TITLE
 [loc][Query][Roslyn] Localizability of "such_as___comma__1_comma__2_comma_etc" 

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#36774]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Avoid unnecessary value assignments in your code, as these likely indicate redundant value computations. If the value computation is not redundant and you intend to retain the assignment, then change the assignment target to a local variable whose name starts with an underscore and is optionally followed by an integer, such as '_', '_1', '_2', etc. These are treated as special discard symbol names.

File Name:
Features\Core\Portable\xlf\FeaturesResources.xlf

==========================================
Query:
Our current translation deviates from the source, but we believe in conveys the idea correctly. Backtranslation:

These names are considered special names for the variables being released?

If our guess is not correct, please advise on the meaning

0; "(...) such_as___comma__1_comma__2_comma_etc"
0; "(...) special_discard_symbol_names"

**Comment by jcouv** [comment]
Tagging @tmeschter @mavasani who appear in the git history for the entry with that text.

**Comment by mavasani** [comment]
Looks good to me.
