### ISSUE TITLE
[loc][Query][Roslyn] Localizability of "AddAssemblyReference"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#36773]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Add an assembly reference to '{0}'

File Name:
Tools\ExternalAccess\FSharp\xlf\ExternalAccessFSharpResources.xlf

==========================================
Query:
Does "to" refer to "Add to" or does it refer to "reference to"? Assumed the former, please confirm or advise.

**Comment by jcouv** [comment]
Tagging @KevinRansom since this localization question looks related to F#

**Comment by jinujoseph** [comment]
also cc @brettfo

**Comment by PDostalek** [comment]
Any news? @brettfo or @KevinRansom

**Comment by brettfo** [comment]
Redirecting to @TiHan since he authored the F# external access work.

**Comment by PDostalek** [comment]
@TIHan @brettfo  please proceed at your earliest convenience

**Comment by TIHan** [comment]
So, I think this and a few others can actually be removed. I will create a PR.

**Comment by TIHan** [comment]
https://github.com/dotnet/roslyn/pull/39006
