### ISSUE TITLE
Go to definition from implementation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36783]
VSF_TYPE_MARKDOWNHello,

The go to definition/implementation works very good except in one case: If you are at the 'implementation' of a method the 'go to definition' does not work:

Expected behaviour: Go to the definition in an interface (if any)
Observed behaviour: Go to the current implemtation (as if clicking go to implementation).

The same applies for peek at definition.

As a result there is no 'two' click method to go from a method implementation to its interface definition...

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/618939/go-to-definition-from-implementation.html
VSTS ticketId: 936445_
_These are the original issue comments:_

Visual Studio Feedback System on 6/24/2019, 08:27 PM (37 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out.  The inheritance margin is the way to go here.
