### ISSUE TITLE
"Inline temporary variable" breaks code for 'out' parameter

### ISSUE THREAD

**Issue by gewarren** [dotnet/roslyn#36788]
**Version Used**: Visual Studio 2019 version 16.1

```
static void GetPath()
{
    DirectoryInfo root = null;
    var files = GetAllMarkdownFiles(@"C:\\temp", out root);

    string fullPath = Path.Combine(root.FullName, @"..\\file.txt");
}

private static object GetAllMarkdownFiles(string inputDirectory, out DirectoryInfo rootDirectory)
{
    throw new NotImplementedException();
}
```

Put your cursor in `root` in the first line of the GetPath() method, then select “Inline temporary variable” from the light bulb menu.

**Expected Behavior**: Code that works at run time.

**Actual Behavior**: It generates:

```
static void GetPath()
{
   DirectoryInfo root = null;
   var files = GetAllMarkdownFiles(@"C:\\temp", out root);

   string fullPath = Path.Combine(((DirectoryInfo)null).FullName, @"..\\file.txt");
}
```

`((DirectoryInfo)null).FullName` does not work.

**Comment by dpoeschl** [comment]
Thanks @gewarren.

Inline temporary variable takes the variable's assigned value, plugs it in to every usage, and flags any additional writes as conflicts. Note the red border around "root" on the second line of the diff window here (and the "X Conflict(s) detected." message):

![image](https://user-images.githubusercontent.com/235241/60216811-e3840900-981f-11e9-8972-92c459b2c33c.png)

This is sometimes useful, but probably not in this case. The more recent `out <type> name` argument syntax is generally preferred in this situation, and we do offer to "inline variable declaration" here to convert to that syntax. Without making more fundamental changes to inline temporary variable, I'd propose we simply choose not to offer the refactoring if we recognize this pattern.

**Comment by CyrusNajmabadi** [comment]
Perhaps 'inline temporary varable' should be renamed to 'replace variable with initializer value' to better indicate what is going on?

**Comment by CyrusNajmabadi** [comment]
Closing out as working as expected.
