### ISSUE TITLE
Expose DocumentExtensions.IsGeneratedCode(Document, CancellationToken)

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#36796]
https://github.com/dotnet/roslyn/blob/a571221b42a6166fefe2e1ad016a8af59645fd40/src/Workspaces/Core/Portable/Shared/Extensions/DocumentExtensions.cs#L194-L198

It looks like a useful helper.

**Comment by CyrusNajmabadi** [comment]
Note: this helper should likely be async.  It has to actually load and parse the contents of the syntax tree to answer the question.

**Comment by jinujoseph** [comment]
cc @sharwell

**Comment by CyrusNajmabadi** [comment]
Needs to go through public API review process.
