### ISSUE TITLE
Please make C# editor capable of pinning section headers

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#36819]
See https://twitter.com/jckarter/status/1140131108564062213 for an explanation.

**Comment by jasonmalinowski** [comment]
Tagging @AmadeusW @olegtk on this one -- I've long wanted this too. Where's the right place to track it?

**Comment by olegtk** [comment]
Seems like everybody universally want it now :) I think the best would be to file a suggestion bug for the editor team and @jinujoseph bring it up on the next sync up meeting.

**Comment by jinujoseph** [comment]
sure will do

**Comment by CyrusNajmabadi** [comment]
Me2.  Note: i wonder if this could sit on top of the navbar code.  Effectively, you'd get this bheavior if you were actually just using the caret to move down through the file.  The ask though is for this to work with scrolling.  If scrolling just asked "what would be the current nav-bar contents if the caret was on the top-visible-line", could this just fall out?

**Comment by CyrusNajmabadi** [comment]
Closing out as internal.
