### ISSUE TITLE
Improve file structure view

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#36812]
[Original DevComm feedback](https://developercommunity.visualstudio.com/idea/472007/希望添加类似resharper的-file-structure功能窗口.html?childToView=623413#comment-623413)

Edited quote:
> ... Add a file structure feature similar to resharper that can view the structure of the current document. Although you can view this in the solution explorer and above the current file, navigating the current document is not very convenient, nor very intuitive.

Currently some file structure UI is provided in the Solution Explorer:
![image](https://user-images.githubusercontent.com/8293542/60225230-c0b31e00-983a-11e9-8ef4-ca3bebc569ff.png)

Another user provided specific improvements they'd like to see in this experience:

> The class properties and methods displayed in solution explorer are nice but there are drawbacks :
> 1. It's only shown when manually continuing to expand the tree : when opening a new file, i would love to automatically view it's structure because I use it a lot on every classes.
> 2. It's very very hard to compare several file structure on a quick view : when displayed on another window, I can see similarities or difference between different file structure simply by quickly switching between file tabs. 
> 3. There are not differences between what is overridden or not
> 4. No file regions display : most of the time, regions are used to group methods/class.
> 5. The method/properties name and type have the same color : it would be great to use the same editor colors
> 6. No method/properties highlight I'm currently writing/clicking on : not mandatory but would be appreciated
> 
> I work a lot with very big files (more than 4000 lines and about 100 properties/methods) and I do a lot of code refactoring to try to clean up the mess.
> To me, the file structure window is very important and the biggest missing thing in Visual Studio.

**Comment by johndog** [comment]
May as well use document outline for this: https://github.com/dotnet/roslyn/issues/35708

**Comment by sharwell** [comment]
We are now using this issue to track the high-level request to improve the file structure experience. The **Document Outline** window (#35708) is one possible way this could be improved, but other approaches will be considered as well.

**Comment by mikadumont** [comment]
Adding related customer feedback: 

> “File Structure” window as below, which give an overview view for fields, methods with region structure and management in the window, better than current VS view in right side as second screenshot:

![image](https://user-images.githubusercontent.com/46729679/84935609-ce863280-b08d-11ea-9bad-4ff947b627af.png)

![image](https://user-images.githubusercontent.com/46729679/84935618-d47c1380-b08d-11ea-9f8b-6024ff511fb9.png)

**Comment by CyrusNajmabadi** [comment]
How does thsi differ from teh existing progression view:

**Comment by jmarolf** [comment]
@CyrusNajmabadi I would be curious to dig into the telemetry here. Last I checked I don't think these nodes where used in the solution explorer very much (which would suggest they are not discoverable). I also personally find the solution explorer hard to use for this case since it cannot map to what I am seeing in my editor (which I assume an outline view would be able to do)

**Comment by mikadumont** [comment]
@CyrusNajmabadi The ask was to have the tree view expanded automatically rather than having to expand it manually so they can easily navigate to the field or method they needed.

**Comment by Baptiste31000** [comment]
@CyrusNajmabadi You can read 6 improvement points I've listed that @kendrahavens quoted above...

**Comment by mikadumont** [comment]
Proposal: 

When `track active items` is checked:
![image](https://user-images.githubusercontent.com/46729679/95270252-00173b00-07f0-11eb-81e1-aeee26c38615.png)

Then we automatically expand the nodes within solution explorer of where your selection is in the code:
![image](https://user-images.githubusercontent.com/46729679/95270683-e9251880-07f0-11eb-8ba6-0314bdc6ef55.png)

**Comment by CyrusNajmabadi** [comment]
Please don't do that :)    def do not want these item expanded by default, and i always use 'track active item'. 

Perhaps consider having two options "track active file" and "track active symbol".  The later will do what you're asking about here.

Thanks!

**Comment by mikadumont** [comment]
Direct customer ask copying here: 

> I would like to have a button to explicitly jump to the file I want. Having a right click menu option in the editor or on the file tab and selecting `Navigate in Solution Explorer` to show me where this code is located in Solution Explorer.

**Comment by CyrusNajmabadi** [comment]
This already exists.  You just need to click on this icon:

![image](https://user-images.githubusercontent.com/4564579/101211581-417b6980-362c-11eb-8cec-d2fd8f665a61.png)

**Comment by CyrusNajmabadi** [comment]
You can also set VS to do this automatically here:

![image](https://user-images.githubusercontent.com/4564579/101211642-5657fd00-362c-11eb-817b-5f5180af7fd6.png)

Just choose 'track active ...'

**Comment by mikadumont** [comment]
The user is asking for an option to choose explicitly when they would like to find something in sln explorer similar to this: 

Finding before:
![image](https://user-images.githubusercontent.com/46729679/101212267-4a206f80-362d-11eb-9e94-e5c351b7f031.png)

Finding after: 
![image](https://user-images.githubusercontent.com/46729679/101212327-63292080-362d-11eb-91a3-50d4ed222eae.png)

**Comment by manojbaishya** [comment]
Was going to open an issue at developercommunity2.visualstudio.com but then discovered this.

There is already a discussion thread at StackOverflow regarding this issue: https://stackoverflow.com/questions/2819519/visual-studio-window-which-shows-list-of-methods/2819532
For reference:

1. Visual Studio Code has already implemented this tool window named as Outline View: https://code.visualstudio.com/docs/getstarted/userinterface#_outline-view, that not just supports C# but also JSON, Python, HTML, XML, CSS, C++, Javascript, Typescript, etc, for currently opened file in the text editor.

> The Outline view is a separate section in the bottom of the File Explorer. When expanded, it will show the symbol tree of the currently active editor. The Outline view has different Sort By modes, optional cursor tracking, and supports the usual open gestures. It also includes an input box which finds or filters symbols as you type. Errors and warnings are also shown in the Outline view, letting you see at a glance a problem's location. For symbols, the view relies on information computed by your installed extensions for different file types. For example, the built-in Markdown support returns the Markdown header hierarchy for a Markdown file's symbols.

2. Similar functionality is implemented by JB Resharper's File Structure window: https://www.jetbrains.com/help/resharper/Reference__Windows__File_Structure_Window.html

3. Eclipse implementation:
![image](https://user-images.githubusercontent.com/28330014/146677526-d552e7ed-061f-4647-bdd5-0fcfb0cf59e1.png)
![image](https://user-images.githubusercontent.com/28330014/146677589-aaa44372-2c9c-499f-892c-230421ad0c02.png)
(Copied from https://stackoverflow.com/q/31752352/6483989)

The problem with Resharper is, if you want to have File Structure view, it will also drag a massive amount of baggage into VS, significantly slowing it down (whether the other features are beneficial is subjective). The same applies for the CodeMaid extension, which has named this feature as "digging": https://www.codemaid.net/documentation/#digging, but it does not work for JSON or Python, etc, and includes lots of extra features which a user might not want (does not obey single responsibility principle).

If this tool window is okay'ed for implementation, then may be, VS Code team's inputs regarding the general purpose symbol tree lookup will help, one that works regardless of any file type currently open in the editor. (I think repurposing the Document Outline tool window for this feature is a very solid decision!)

My question is: Can the Navigation Bar or the Solution Explorer display symbols for non-C# file types or expand the current edited file in case of C# file type, and thus have equivalent functionality to the proposed Code Outline/File Structure feature?

I am not very familiar with either VS extension development or Roslyn api-s, so the ramp up time will be significantly higher than if someone already familiar with VS codebase decide to implement it ( depending on priority of course :) )

**Comment by mikadumont** [comment]
Below is a mini spec of what we would like to do:

Similar to [VS Code](https://code.visualstudio.com/docs/getstarted/userinterface#_outline-view) we should populate the existing Document Outline tool window in Visual Studio to show the structure of the current file so when expanded, it will show the symbol tree of the currently active editor.

Currently Document Outline doesnt show anything for C# files:
![image](https://user-images.githubusercontent.com/46729679/165600799-9c0b7854-5bab-4ec9-b470-4ffc83eb5983.png)

Document Outline does get populated for Xaml files:
![image](https://user-images.githubusercontent.com/46729679/165601493-c4a226a2-f5aa-422c-bb44-13f10c91fd15.png)

We would like Document Outline to look similar to VS Code's Outline View:
![image](https://user-images.githubusercontent.com/46729679/165601680-1d491d03-0300-4977-ac9c-82d03788c24d.png)

**Comment by Cosifne** [comment]
Design meeting notes:
People have a lot of thoughts around this, Emily would need to prepare a prototype, get early feedback, improve and see if it is good enough to be put into the releasing product.

**Comment by emilyanas2323** [comment]
Implemented in PR https://github.com/dotnet/roslyn/pull/61784
