### ISSUE TITLE
Debug.Assert() does not change tracked nullability of field

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#36830]
```C#
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

class C<T>
{
    [AllowNull, MaybeNull] T F = default!;

    void M()
    {
        Debug.Assert(F != null);
        F.ToString();
    }
}
```
```
(11,9): warning CS8602: Dereference of a possibly null reference.
```
cc @safern

Relates to https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-05-15.md (attributes for nullability analysis)

**Comment by cston** [comment]
cc @jcouv

**Comment by benaadams** [comment]
Should only do it in Debug mode? Which would then be kinda annoying for release?

**Comment by safern** [comment]
No, when using Debug.Assert it changes the nullability on both configurations.

**Comment by jcouv** [comment]
Thanks @cston. I think what this indicates is that the `[MaybeNull]` attribute should only affect the value read from a field the first time (default state). Does that sound reasonable?
