### ISSUE TITLE
IDE0055 flagging on uses of pattern matching with expression bodied members

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#36835]
In Roslyn.sln right now there's a bunch of these:

	F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\CodeGeneration\CSharpSyntaxGenerator.cs(1591,9): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Workspaces.csproj]
	F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\CodeGeneration\CSharpSyntaxGenerator.cs(1592,13): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Workspaces.csproj]
	F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\CodeGeneration\CSharpSyntaxGenerator.cs(1593,13): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Workspaces.csproj]
	F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\CodeGeneration\CSharpSyntaxGenerator.cs(1594,13): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Workspaces.csproj]
	F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\CodeGeneration\CSharpSyntaxGenerator.cs(1595,13): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Workspaces.csproj]
	F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\CodeGeneration\CSharpSyntaxGenerator.cs(1596,13): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Workspaces.csproj]
	F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\CodeGeneration\CSharpSyntaxGenerator.cs(1597,13): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Workspaces.csproj]
	F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\CodeGeneration\CSharpSyntaxGenerator.cs(1598,9): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Workspaces\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Workspaces.csproj]
	F:\Projects\Roslyn\src\Features\CSharp\Portable\MisplacedUsingDirectives\MisplacedUsingDirectivesCodeFixProvider.cs(249,9): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Features\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Features.csproj]
	F:\Projects\Roslyn\src\Features\CSharp\Portable\MisplacedUsingDirectives\MisplacedUsingDirectivesCodeFixProvider.cs(250,13): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Features\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Features.csproj]
	F:\Projects\Roslyn\src\Features\CSharp\Portable\MisplacedUsingDirectives\MisplacedUsingDirectivesCodeFixProvider.cs(251,13): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Features\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Features.csproj]
	F:\Projects\Roslyn\src\Features\CSharp\Portable\MisplacedUsingDirectives\MisplacedUsingDirectivesCodeFixProvider.cs(252,13): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Features\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Features.csproj]
	F:\Projects\Roslyn\src\Features\CSharp\Portable\MisplacedUsingDirectives\MisplacedUsingDirectivesCodeFixProvider.cs(253,9): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Features\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Features.csproj]
	F:\Projects\Roslyn\src\Features\Core\Portable\MoveToNamespace\AbstractMoveToNamespaceCodeAction.cs(82,9): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Features\Core\Portable\Microsoft.CodeAnalysis.Features.csproj]
	F:\Projects\Roslyn\src\Features\Core\Portable\MoveToNamespace\AbstractMoveToNamespaceCodeAction.cs(83,13): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Features\Core\Portable\Microsoft.CodeAnalysis.Features.csproj]
	F:\Projects\Roslyn\src\Features\Core\Portable\MoveToNamespace\AbstractMoveToNamespaceCodeAction.cs(84,13): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Features\Core\Portable\Microsoft.CodeAnalysis.Features.csproj]
	F:\Projects\Roslyn\src\Features\Core\Portable\MoveToNamespace\AbstractMoveToNamespaceCodeAction.cs(85,13): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Features\Core\Portable\Microsoft.CodeAnalysis.Features.csproj]
	F:\Projects\Roslyn\src\Features\Core\Portable\MoveToNamespace\AbstractMoveToNamespaceCodeAction.cs(86,9): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Features\Core\Portable\Microsoft.CodeAnalysis.Features.csproj]

An example is here:

https://github.com/dotnet/roslyn/blob/e65f0cb2a986fc7176e5221e31521c804135c88b/src/Features/CSharp/Portable/MisplacedUsingDirectives/MisplacedUsingDirectivesCodeFixProvider.cs#L247-L253

The analyzer is firing I guess insisting that the code shouldn't be indented so much. Ignoring what the style is, I couldn't actually *fix* it and make the warning go away; the code fix also didn't really work.

**Comment by jasonmalinowski** [comment]
FYI to @heejaechang and @sharwell.

**Comment by JoeRobich** [comment]
Other issues on this topic #35505 & #34962

**Comment by jasonmalinowski** [comment]
@sharwell I'm seeing what looks like a lot more offenses of this now with a few hundred warnings in Roslyn.sln where a spot check looks like largely this. What's the progress on this?

**Comment by CyrusNajmabadi** [comment]
I'm seeing a lto as well (possibly my fault with some recent PRs of mine).  I'm also a little curious how this is happening. I thought the idea of this analyzer was that it tried to format the document, and if that would make any changes, it gives the warning.  However, despite seeing the warning, it's then unable to actually 'fix' the issue.  This seems bizarre to me as it would only come up with teh warning if it was able to fix them... :)

**Comment by jasonmalinowski** [comment]
Yeah I don't get what's happening here either.

**Comment by sharwell** [comment]
I don't know which pull request fixed the formatter, but #37433 applied in to Roslyn.sln.
