### ISSUE TITLE
Pattern matching is giving IDE0055 formatting around operators

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#36838]
In code like this:

https://github.com/dotnet/roslyn/blob/e65f0cb2a986fc7176e5221e31521c804135c88b/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs#L1401

We're saying there's something wrong with the space between the } and the && which doesn't really make sense.

Full list of issues I think:

    F:\Projects\Roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs(1401,118): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Compilers\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.csproj]
    F:\Projects\Roslyn\src\Compilers\CSharp\Portable\Binder\DecisionDagBuilder.cs(1035,115): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Compilers\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.csproj]
    F:\Projects\Roslyn\src\Compilers\CSharp\Portable\Binder\DecisionDagBuilder.cs(1036,112): warning IDE0055: Fix formatting [F:\Projects\Roslyn\src\Compilers\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.csproj]

FYI to @heejaechang and @sharwell.

**Comment by jcouv** [comment]
There's a second related issue (incorrect IDE0055 when formatting patterns):
![image](https://user-images.githubusercontent.com/12466233/66071172-86c37900-e507-11e9-8b96-22beea1096a5.png)

**Comment by tiesmaster** [comment]
@sharwell I like to pick this one up, though, I don't get this reproduced, is this maybe already fixed?

For example, if I go to `NullableWalker` then the `} &&` does not trigger `IDE0055`. Though, if I _add_ a secondary space after the opening `{`, then it does trigger.

![image](https://user-images.githubusercontent.com/460904/66784955-2acffb80-eedc-11e9-8eae-7a0f1100edd9.png)

The same applies for `isTypeIEquatable` in `ConversionsBase.cs`, it also doesn't trigger there anymore:
![image](https://user-images.githubusercontent.com/460904/66785221-e6912b00-eedc-11e9-9ce9-27b1a35f9719.png)

Please let me know if I'm looking at the issue from the wrong angle ;)

**Comment by jcouv** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/36082
