### ISSUE TITLE
cannot build latest master

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#36840]
I get this error:

```
1>------ Build started: Project: Microsoft.CodeAnalysis, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(257,7): error MSB4064: The "DesignTimeBuild" parameter is not supported by the "ResolvePackageAssets" task. Verify the parameter exists on the task, and it is a settable public instance property.
1>C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(234,5): error MSB4063: The "ResolvePackageAssets" task could not be initialized with its input parameters.
1>Done building project "Microsoft.CodeAnalysis.csproj" -- FAILED.
2>------ Build started: Project: Microsoft.CodeAnalysis.Workspaces, Configuration: Debug Any CPU ------
2>C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(257,7): error MSB4064: The "DesignTimeBuild" parameter is not supported by the "ResolvePackageAssets" task. Verify the parameter exists on the task, and it is a settable public instance property.
2>C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(234,5): error MSB4063: The "ResolvePackageAssets" task could not be initialized with its input parameters.
2>Done building project "Microsoft.CodeAnalysis.Workspaces.csproj" -- FAILED.
```

I have cleaned and restored.  I am on:

![image](https://user-images.githubusercontent.com/4564579/60301020-37a4f100-98e5-11e9-8cf7-2b8238845868.png)

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-infrastructure @jasonmalinowski

**Comment by JoeRobich** [comment]
@CyrusNajmabadi I just pulled, cleaned, restored and built master OK. However the latest .NET Core SDK I have is 3.0.100-preview6-012105 which matches what is specified in the global.json. I am going to download the -012264 build of the SDK and give it a try to see if I can reproduce what you are seeing.

**Comment by dibarbet** [comment]
I've hit this before as well
@heejaechang had a suggestion to kill all the MSBuild tasks
`taskkill /IM MSBuild.exe /F` which has worked for me a couple times.  Not a full resolution but it may help.

**Comment by CyrusNajmabadi** [comment]
@dibarbet Thanks, unfortunately that didn't help.  I have no msbuild instances running.

@JoeRobich Where can i find that version of the .net sdk?

**Comment by JoeRobich** [comment]
@CyrusNajmabadi I was able to build with the same version of the SDK that you have installed, using the same version of VS. Did you have other versions of VS open? If so were they preview or RTM versions?

**Comment by JoeRobich** [comment]
@CyrusNajmabadi We link to it in the [Building, Debugging, and Testing on Windows](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md), but you can download it here - [Windows x64 installer](https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview6-012105/dotnet-sdk-3.0.100-preview6-012105-win-x64.exe). Not sure if your issue is SDK related anymore.

**Comment by CyrusNajmabadi** [comment]
> Did you have other versions of VS open? If so were they preview or RTM versions?

I have no other versions of VS open.  I even rebooted to try to get things into a good state.

**Comment by JoeRobich** [comment]
> I have cleaned

`git clean -xdf` or Build > Clean Solution?

**Comment by CyrusNajmabadi** [comment]
the former.  Thanks!

**Comment by dibarbet** [comment]
I am now also running into the issue again, and my former fix is no longer working.

**Comment by JoeRobich** [comment]
@CyrusNajmabadi All it took was leaving VS up overnight I suppose. 
![image](https://user-images.githubusercontent.com/611219/60358821-0cc1a800-998c-11e9-8ba9-451cfaf88ec7.png)

**Comment by CyrusNajmabadi** [comment]
Any ideas on how to fix this.  @jasonmalinowski @dotnet/roslyn-infrastructure ?

**Comment by CyrusNajmabadi** [comment]
Note: i'm also still getting this:

```
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.CodeAnalysis.PooledObjects.Package could not be loaded.
```

**Comment by CyrusNajmabadi** [comment]
Something strange seems to be happening on build too.  It seems to be trying to restore all packages every time i try to build.  This takes a *looong* time.  like 20s just to do that step.

**Comment by CyrusNajmabadi** [comment]
So what can i do about this:

![image](https://user-images.githubusercontent.com/4564579/60465771-c330c180-9c06-11e9-9c05-1bf62a85744e.png)

?
