### ISSUE TITLE
Missing "CS8656: Call to non-readonly member from a 'readonly' member results in an implicit copy of 'this'" warning on pattern-based indexers usage

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#36872]
**Version Used**: 

master branch 06/28/2019

**Steps to Reproduce**:

Compile the following code:
```c#
struct S {
    public int Count => 0;
    public readonly int this[int index] => 42;
    
    public readonly void M() {
        var t = this[^1]; // missing CS8656
    }
}

struct S2 {
    public int Length => 0;
    public /*readonly*/ int Slice(int a, int b) => 1;
    
    public readonly void M() {
        var t = this[..]; // missing CS8656
    }
}

namespace System {
  public struct Index {
      public Index(int index, bool fromEnd) { }
      public int GetOffset(int length) => 0;
  }
    
  public struct Range {
      public Range(Index start, Index end) { }
      public Index Start => default;
      public Index End => default;
  }
}
```

**Expected Behavior**:

Two compiler warnings CS8656 at indexer invocations.

**Actual Behavior**:

No warnings.

p.s. `readonly` state of synthesized pattern-based indexer must be the `&&` combination of `readonly` states of the `Count`/`Length` properties and `int` indexer/`Slice()` methods involved in pattern.

**Comment by RikkiGibson** [comment]
Interesting, I guess in the ‘struct S’ example we would want 2 warnings if ‘readonly’ were removed from the indexer.
