### ISSUE TITLE
Should we disable "name can be simplified" for Roslyn IDE for usages of `this.`

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#36874]
Right now there are several thousand messages in the IDE code that `name can be simplified` because of hte usage of `this.Foo` (which could be converted to `Foo`).  

I don't actually this this is warranted.  I think it's reasonable for `this` to be in the code for added clarity (i.e. i'm accessing some instance property, not some static member or potentially a type somewhere).

Should we disable/change this to be permissive for IDE code?

I'm ok with any decision made here.  But i will want us to actually make our code consistent with the rule if the severity is not 'none' since this fills my message list with literally thousands of messages.

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @mavasani @jasonmalinowski for thoughts.

**Comment by jasonmalinowski** [comment]
I'm OK with making it permissive.
