### ISSUE TITLE
Namespace info for class in tooltip

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36870]
<p>In a code you can have constructor call:</p> <pre>var obj = new SomeClass()
</pre><p>When you hover mouse over class name, you see tooltip: &quot;SomeClass.SomeClass(args)&quot;. Obviously unnecessary name duplicate and no info about namespace. It could be more informative to see tooltip like:</p><p><strong>Namespace1.Namespace2</strong></p><p><strong>constructor SomeClass(args)</strong></p><p>Then namespace do not disturb you from reading arguments and we eliminate reading of class name twice (it annoys, esp. with variable width font). Frequently you have in code just constructor calls, so you have no way to quickly get class' namespace.</p> <p>One more improvement is to show &quot;standard&quot; namespaces of .NET in different color (in tooltip).</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/609058/namespace-info-for-class-in-tooltip.html
VSTS ticketId: 922875_
_These are the original issue comments:_

Jane Wu [MSFT] on 6/17/2019, 01:16 AM (11 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by sharwell** [comment]
Design conclusion: we can show the following:

```
new Namespace1.Namespace2.SomeClass(parameters...)
```

The class name would be namespace-qualified in this display, even in cases where that name can be simplified by `using` directives already in scope.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
