### ISSUE TITLE
Reintroduce sequence diagrams generation from c# code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36871]
<p>This was part of previous Visual Studio versions and is key to understand/document/share/communicate about existing flows and potential optimizations.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/612434/reintroduce-sequence-diagrams-generation-from-c-co.html
VSTS ticketId: 927465_
_These are the original issue comments:_

Jane Wu [MSFT] on 6/19/2019, 00:40 AM (9 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
This is not a roslyn request.
