### ISSUE TITLE
VB Formatting of LineContinuation Wrong after _ ' Comment 

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#36891]
**Version Used**: 
16.2.0 Preview 3.0
**Steps to Reproduce**:
Type the following into the IDE
```VB
    Private Private ReadOnly s_originCategoryCodeTextExpression As Regex = New Regex(
 _  ' Beginning of line and any amount of whitespace.
    "^\s*" _
 _ ' Match a [optional project number prefix 'ddd>'], single letter + colon + remaining filename, or
 _ ' string with no colon followed by a colon.
      & "(((?<ORIGIN>(((\d+>)?[a-zA-Z]?:[^:]*)|([^:]*))):)" _
 _ ' Origin may also be empty. In this case there's no trailing colon.
      & "|())" _
 _ ' Match the empty string or a string without a colon that ends with a space
      & "(?<SUBCATEGORY>(()|([^:]*? )))" _
 _ ' Match 'error' or 'warning'.
      & "(?<CATEGORY>(error|warning))" _
 _ ' Match anything starting with a space that's not a colon/space, followed by a colon. 
 _ ' Error code is optional in which case "error"/"warning" can be followed immediately by a colon.
      & "( \s*(?<CODE>[^: ]*))?\s*:" _
 _ ' Whatever's left on this line, including colons.
      & "(?<TEXT>.*)$",
       RegexOptions.IgnoreCase)
```

**Expected Behavior**:
Formatting like C# where lines starting from the second are indented OR a Space _ then enough spaces to indent the comment or code to line up 4 space to the right of "Private" OR the comments and blank lines the way they are but the code lines correctly indented.
```C#
    private static readonly Regex s_originCategoryCodeTextExpression = new Regex
        (
        @"^\s*"
        // Match a [optional project number prefix 'ddd>'], single letter + colon + remaining filename, or
        // string with no colon followed by a colon.
        + @"(((?<ORIGIN>(((\d+>)?[a-zA-Z]?:[^:]*)|([^:]*))):)"
        // Origin may also be empty. In this case there's no trailing colon.
        + "|())"
        // Match the empty string or a string without a colon that ends with a space
        + "(?<SUBCATEGORY>(()|([^:]*? )))"
        // Match 'error' or 'warning'.
        + @"(?<CATEGORY>(error|warning))"
        // Match anything starting with a space that's not a colon/space, followed by a colon. 
        // Error code is optional in which case "error"/"warning" can be followed immediately by a colon.
        + @"( \s*(?<CODE>[^: ]*))?\s*:"
        // Whatever's left on this line, including colons.
        + "(?<TEXT>.*)$",
        RegexOptions.IgnoreCase
        );
```
**Actual Behavior**:
The code is all left aligned with one space before the _

**Comment by jcouv** [comment]
If you want to take a stab, I've collected some notes on formatting: https://github.com/dotnet/roslyn/wiki/Notes-on-formatting#newlines
The notes include a PR that shows some of the relevant source and test files (for C#, but I expect something similar for VB).

**Comment by paul1956** [comment]
@jcouv I want to look at fixing this but https://github.com/dotnet/roslyn/wiki/Notes-on-formatting#newlines just takes me to Roslyn Repo

**Comment by jcouv** [comment]
Here's the updated link: https://github.com/dotnet/roslyn/blob/main/docs/wiki/Notes-on-formatting.md

**Comment by paul1956** [comment]
Update https://github.com/dotnet/roslyn/issues/36891#issuecomment-507329764
If you want to take a stab, Julian collected some notes on formatting: https://github.com/dotnet/roslyn/blob/main/docs/wiki/Notes-on-formatting.md
The notes include a PR that shows some of the relevant source and test files (for C#, but I expect something similar for VB).

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to be changing these experiences.
