### ISSUE TITLE
[Regression] Visual Studio becomes unusable if you open large set of VB files

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#36899]
**Version Used**: 
Version 15.9.13 - does not repro
Version 16.2.0 Preview 4.0 [29029.12.d16.2stg] - repros

**Steps to Reproduce**:

-- Clone Repo --
1. git clone http://github.com/dotnet/project-system
2. `cd project-system`
3. `project-system> build`
4. `project-system> ProjectSystem.sln`

-- Disable designers (they will prevent you from opening all the files) --

5. Right-click on Microsoft.VisualStudio.AppDesigner\PropPages\PropPageHostDialog.vb and choose, `Open With` -> `Visual Basic Editor` -> `Set As Default`
7. Right-click on Microsoft.VisualStudio.AppDesigner\PropPages\PropPageUserControlBase.vb and choose, `Open With` -> `Visual Basic Editor` -> `Set As Default`
8. Right-click on  Microsoft.VisualStudio.AppDesigner\ApplicationDesigner\ApplicationDesignerView.vb and choose, `Open With` -> `Visual Basic Editor` -> `Set As Default`

-- Open files --

9. `File` -> `Open`, navigate to the project-system folder above
10. In Search, enter `ext:"vb"`
11. `CTRL+A` to select all, and choose `Open`

-- Wait for files to open --

12. Open Microsoft.VisualStudio.Editors\PropPages\CompilePropPage2.vb, navigate to `EnableDisableWarningControls` right-click on parameter and click Rename
13. Rename and commit the change

**Expected Behavior**:
No UI delays

**Actual Behavior**:
Visual Studio has constant delays that prevent you from interacting with it.

Trace is [internalshare]\davkean\Roslyn\36899.

**Comment by davkean** [comment]
Look at the trace, this looks to be caused by GC:

```
•% Time paused for Garbage Collection: 70.1%
•% CPU Time spent Garbage Collecting: 16.8%
```

Gen | Count | MaxPause | MaxPeak MB | Max AllocMB/sec | TotalPause | TotalAlloc MB | Alloc MB/MSec GC | Survived MB/MSec GC | MeanPause | Induced
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ALL | 217 | 78.7 | 1,359.1 | 591.740 | 8,995.3 | 971.2 | 0.1 | 0.041 | 41.5 | 0
0 | 115 | 74.4 | 1,355.9 | 552.974 | 4,402.8 | 496.6 | 4.5 | 0.024 | 38.3 | 0
1 | 102 | 78.7 | 1,359.1 | 591.740 | 4,592.4 | 474.7 | 4.7 | 0.057 | 45.0 | 0
2 | 0 | 0.0 | 0.0 | 0.000 | 0.0 | 0.0 | 0.0 | NaN | NaN | 0

These are the top allocations:

![image](https://user-images.githubusercontent.com/1103906/60409847-9d0c2100-9c08-11e9-93b2-7669e5bf6049.png)

Other than GC, almost all the CPU is used by:

```
microsoft.codeanalysis.features.ni!Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer+LatestDiagnosticsForSpanGetter+<TryGetAsync>d__14.MoveNext()
```

**Comment by davkean** [comment]
Visual Studio is completely unusable in this state until you close all the documents.

**Comment by davkean** [comment]
Note I open the C# equivalent here: https://github.com/dotnet/roslyn/issues/37264, which looks different.

**Comment by sharwell** [comment]
@davkean The total amount of allocations in the trace don't seem significant enough to cause problems like you describe. It would help to have the combination of performance trace and heap dump like the vsfeedback system submits for https://aka.ms/reportPerf.

**Comment by davkean** [comment]
The repro steps have a clear steps to reproduce this to get any data you would like.

**Comment by CyrusNajmabadi** [comment]
Closing out as Todd has made many changes here to improve things.  Ideally this would also use async loading, only actually incurring lang server costs for visible documents (@olegtk ).
