### ISSUE TITLE
Nullable analysis should learn from calls to Interlocked.CompareExchange

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#36911]
https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-05-15.md#compareexchange

```cs
public static extern object? CompareExchange( 
    ref object? location1, object? value, object? comparand); 
 
public static T CompareExchange<T>( 
    ref T location1, T value, T comparand) where T : class?
```

> The most important case to infer here: If comparand is a constant null and value is non-null, location will be non-null on return.

- [x] nullable analysis of `location1`
- [ ] nullable analysis of return values (non-null if location is non-null)
  - handling via NotNullIfNotNull annotation on CompareExchange

**Comment by jcouv** [comment]
Can this issue be closed?

**Comment by RikkiGibson** [comment]
@stephentoub @safern we think that the return value analysis could be provided without adding a special case in the compiler by decorating the method with `[NotNullIfNotNull("location")]`.

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWAChGABAJgEYWAGC59gOgAqACwRwIKAJa4A5gG5uvAQBFJEGbgD2sSQGMo/AMKaUcAII1CATyiSoCpgxpg4UAA4RdlPv1XqtOvpGJuaWNnaMAN6MFLEUAPSJFAA8UPhgkAhWAHwAym5wupIAZpKuFDDCEDAVwpSa+DBujRQA7pLEFMCUWrgAtASdJbU9EC4oFB4IY3DwCBR2FL0DRIT8yfFpGRBZ2TFxANpmMDAIksCNcACqUOpwABTHp+eXgjsyswYACjszcxSYChPM4XeBvBAfGDfBCaAoIGBWAFAk4g17vT78ABKs3wCFwADUIIR8HAkEDiJpWgBZIgwSRucgUAC8FQQJLJAElcHUzvAJizikSoHAAJQAXX2sWkc0sFGFRLgEzYFAAcpoYCrVhzimqNatgS94BQQMjnqC4JKKNEGHFbQkkql0pkclzJHSiZIAF7lSqUapmy5tN3CEYUaBQTRFaqKya/Fz/ZxwdabJ07HKW22JeIpKZjJYzJkAIlz8cQKpmhb2NrtsSzFBEfqgEajfNj01L80T/FiDYoDSaLXanW6S00/UGhAWxVD73S1BqME0oZLs0QcoKRVKMcWywn/AzcTrGxLVZrsWYAGZVerNcRtbrb4QDeb7nweCu5uWXCLmdkKD921XBAv0oFkPzLGYHAPWsHS2Z1sgAcU+Gcm0jNRW3AzsZmTOC01PM9LyUHgAL+CCXCtChITkCgAF9LTohgGMYRN3E8bwBBEMQJGkGQoktPgADZeFYCguTmQhIwAa0VS1rTPCgDmYAB2E0Hy1HUb1We5Cwk3RqkkMdC3FaClCEzRgAAK0KGAAH4KGMMApjgABRAAPXQqlkB4xGncyrN0WyKF0/SxzJPzrLsgA3Il2T7SyIooXRNEc35cBQEUTLk+S4mi+YYEc5kgsjELcAcbK4mCukx0K6LiTgMryt4JSKkchqawY+STME3gABZ61cGB7gy6sayy8rwoCuzdMK3A4FaOL/MGkU2uy3KKDEGoWQcpy3I8iAvPuHyit0MkJ1O1ZlpM20NqETRcmeWQhpW20OriBiaKAA=

**Comment by stephentoub** [comment]
> we think that the return value analysis could be provided without adding a special case in the compiler by decorating the method with [NotNullIfNotNull("location")]

If that won't mess up the other (more important piece) that we can't get via attribution, then yes, that part can be done by the library, since CompareExchange returns the value found in the first argument.  It's a little strange to me that we'd use attributes to express some of the special-ness when the compiler is already special-casing the method, but if that's deemed the desired outcome for the compiler, then sure.
