### ISSUE TITLE
When moving a class, update the namespace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36912]
<p>When you move a class it keeps its old namespace, it would be nice if after you move the class it updates the namespace. Also it would be nice if after you updated the namespace it updates all references.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/519845/when-moving-a-class-update-the-namespace.html
VSTS ticketId: 841091_
_These are the original issue comments:_

Mike Taylor on 4/5/2019, 06:51 AM (87 days ago): <p>This would literally be the best.</p>

Jane Wu [MSFT] on 4/9/2019, 02:17 AM (83 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment]
cc @genlu

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
