### ISSUE TITLE
Keyboard Setup Confusing

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#36918]
**Feature Goals**: 
Keyboard setup to be less confusing and consolidate the settings wizard experience with the reset keyboard experience. 

**Proposal**: 
1. 'Ok' Saves the keymap profile so instead of it saying 'Ok' have it say 'Save':
![image](https://user-images.githubusercontent.com/46729679/60142359-47e69000-976e-11e9-874c-c2dab52c7e2d.png)

2. 'Reset' resets to default but if a user sets their keymap profile to a non default option and selects 'Reset' they can think its resetting to the keymap profile they chose - perhaps we can surface a message when you hover over 'Reset' to say: 'Reset to default':
![image](https://user-images.githubusercontent.com/46729679/60142479-d9ee9880-976e-11e9-84d1-d5c6054c88ae.png)

3. 'Reset' doesn't seem to fully reset keymap. For instance, a user that uninstalls a third party extension that changed their keymap profile still needs to go into the Import and Export Settings Wizard to actually reset their keymap profile back to default because 'Reset' doesn't seem to do the trick:
![image](https://user-images.githubusercontent.com/46729679/60142531-1ae6ad00-976f-11e9-8457-73005c738786.png)

4. Update keymap profile options since some are outdated: 
![image](https://user-images.githubusercontent.com/46729679/60142703-dad3fa00-976f-11e9-88c4-90c6e4f71ee2.png)

5. Make this a standard search box and have it say 'search' commands containing instead of 'show':
![image](https://user-images.githubusercontent.com/46729679/60142833-6f3e5c80-9770-11e9-84db-e915f79053df.png)

6. Commands can be grouped as: Editor Actions, Main menu, Tool Windows, Version Control. Then each option can expand like a tree view and list the commands that fall under that section. Also command names can be written more clearly: For example: 'Edit.ToggleBlockComment' can simply be 'Toggle Block Comment'.

7. Add tags for search indexing for the following words: shortcut, keybindings, keybind and keymap.

_Originally posted by @mikadumont in https://github.com/dotnet/roslyn/issues/34990#issuecomment-505679939_

**Comment by jinujoseph** [comment]
cc @olegtk @gundermanc

**Comment by gundermanc** [comment]
I'm delighted that there's interest in improving this area! In addition to changes to this dialog, something that'd make keyboard customization more intuitive is to enable customizing command bindings in context.

I'd reach out to someone from IDE Experience as I think they own this area.

**Keyboard mapping margin idea:**

Another idea I've been kicking around is a status bar margin that shows the keybinding for the last command that was run. When the user clicks, they are prompted to press the desired key combination to re-map the command. If the keybinding is already mapped, we then guide the user through the process of remapping any colliding commands one-by-one.

As opposed to just a dialog, a margin is more discoverable and contextual and increases the chance users will discover and interact with keybindings. Increased engagement could yield a lot of interesting data.. we can look to see which commands are remapped most frequently.. to what, and use that to drive improvements to the default keyboard mapping scheme that will positively impact the broadest set of users.

**Comment by CyrusNajmabadi** [comment]
I'm not sure why this is in roslyn.  If we want this to be improved, it will have to be driven through editor/platform.
