### ISSUE TITLE
Disable code formatting for some part of code by using specific comments/region

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36930]
VSF_TYPE_MARKDOWNOther IDEs have this feature for long. Would like to have an option where the formatting for code is disabled between 2 comments like below

```csharp
// @formatter:off
public const string Foo                   =           "foo";
public const string Bar                    =           "bar";

// @formatter:on 
```

This would allow many developers who prefer column aligned code to do it. Visual studio will then not revert their changes while formatting the file.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/481492/disable-code-formatting-for-some-part-of-code-by-u.html
VSTS ticketId: 813186_
_These are the original issue comments:_

Jane Wu [MSFT] on 3/7/2019, 00:10 AM (117 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
Kendra Havens [MSFT] on 7/1/2019, 04:45 PM (16 hours ago): <markdown><p>Thank you for this feedback. You can suppress diagnostics in code with #pragma. <a target='_blank' href="https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-pragma-warning">https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-pragma-warning</a></p>
<p>Does this feaure satisfy this request? Please let us know if something is missing from your experience.</p>
</markdown>
puneetkeshav on 7/1/2019, 07:50 PM (13 hours ago): <p>This is not a warning/diagnostic issue, so it will not get solved by #pragma. Visual studio formats the document if document formatting is turned on. But in some areas of code we want that the default formatting should not take place. If we can have some simple solution as suggested in the first comment that would be very helpful.</p>

Kendra Havens [MSFT] on 7/2/2019, 09:40 AM (34 sec ago): <p>I see, this would be for even the silent auto-formats that don't report diagnostics. Thank you for the additional information! I'll move this issue to our open source GitHub repository for additional design discussion with the community.</p>

**Comment by sharwell** [comment]
This was implemented in #38627 as

```csharp
#pragma warning disable format
public const string Foo                   =           "foo";
public const string Bar                    =           "bar";
#pragma warning restore format
```

**Comment by flyfisher1952** [comment]
I have a similar problem in JavaScript. The formatting ruins a regular expression I use to aid in creating 
a Guid. 
`function newGuid(hasDashes) {
    var guid = hasDashes
        ? ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, c => (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16))
        : ([1e7]+1e3+4e3+8e3+1e11).replace(/[018]/g, c => (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16));
    return guid;
`
When I hit Ctrl-K Ctrl-D the formatter inserts spaces around the '+' and '-' characters. I need to get rid of this behavior so I don't have to constantly fix the code.

**Comment by CyrusNajmabadi** [comment]
> I have a similar problem in JavaScript

**Comment by JuDelCo** [comment]
Hi, I have tried `#pragma warning disable format` and indeed it disables code formatting what is great. But after the region I want to disable format on, if I use `#pragma warning restore format` it doesn't work, is ignored by the code formatter so the entire document is unformatted, not only the specific part of code I need.

I'm using VSCode 1.48.2 with the C# Extension 1.23.0 in Linux PopOS 20.04

**Comment by sharwell** [comment]
@JuDelCo can you file a new bug report for the specific case with a code sample?
Thanks! 😄

**Comment by Sorennnn** [comment]
This feature 
#pragma warning disable format
does not work in Visual Studio 2022.

**Comment by JoseMarcenaro** [comment]
Using Visual Studio 2022 Version 17.5.0 Preview 1.0
This feature would be very useful to avoid reformatting certain HTML blocks in .cshtml pages.
Thanks!

**Comment by CyrusNajmabadi** [comment]
@JoseMarcenaro can you provide an example of what you mean?

**Comment by JoseMarcenaro** [comment]
@CyrusNajmabadi 

Use case 1:   
**Google Analytics script block or other third-party JS plugins**
If the page doesn't render the exact code provider (because of tabs and whitespace) the console page warns you that the tool "is not installed"

Use case 2:
Depending on the styling and whitespace settings
```Toys<b>R</b>Us```

may not render the same results as
``` 
   Toys
   <b>
   R
   </b>
   Us
```

**Comment by CyrusNajmabadi** [comment]
@JoseMarcenaro Neither of those cases seem to involve C# or VB code.  Not sure the correspondence between what you're asking for and the Roslyn project.  Can you clarify?

**Comment by JoseMarcenaro** [comment]
@CyrusNajmabadi  Maybe this is not the right place.

I'm referring to the possibility of include some markup (pragma or other) in .cshtml Razor views.

Thanks!

**Comment by CyrusNajmabadi** [comment]
@JoseMarcenaro can you give an example of that?  e.g. how you'd write the code today and where you'd place the pragmas/comments to disable things?

**Comment by JoseMarcenaro** [comment]
@CyrusNajmabadi  in a Layout .cshtml Razor code

```
    @if (Model..IsLive)
    {
#pragma WHATEVER NEEDED TO AVOID REFORMATTING THE NEXT BLOCK    
        <!-- Google Tag Manager -->
        <script>
            (function(w, d, s, l, i) {
                w[l] = w[l] || []; w[l].push({
                    'gtm.start':
                        new Date().getTime(), event: 'gtm.js'
                }); var f = d.getElementsByTagName(s)[0],
                    j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                        'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
            })(window, document, 'script', 'dataLayer', 'GTM-MRPK48F');</script>
        <!-- End Google Tag Manager -->
#pragma WHATEVER NEEDED TO RESTORE FORMATTING THE NEXT BLOCK    
    }
```

**Comment by 333fred** [comment]
In theory.

**Comment by sharwell** [comment]
@JoseMarcenaro I would not expect the HTML formatter to follow this directive. Due to the way C# formatting works in Razor scenarios, I would also not expect the directive to work for C# code in those scenarios.

**Comment by JoseMarcenaro** [comment]
Ok @CyrusNajmabadi,  @sharwell , @333fred  
That is understandable. Thanks anyway for taking the time to considering the issue!
