### ISSUE TITLE
discuss on JTF usage in Roslyn

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#36937]
we have introduced JTF in Roslyn but it looks like we haven't decided how deeply we will embrace JTF to Roslyn.

here JTF refers to this (https://github.com/Microsoft/vs-threading)

the reason we introduced JTF to Roslyn is that VS (including variants of VS such as VS for mac) uses it.

for VS, it is a core part of VS on how they manage tasks or switch threads (especially UI thread) without deadlock. and it only works if everyone who participates in VS, use JTF. otherwise, VS can get into a deadlock.

for example, if someone did, JTF.SwitchToMainThreadAsync(http://index/?query=SwitchTomainTh&rightProject=Microsoft.VisualStudio.Threading&file=JoinableTaskFactory.cs&line=171) and people who is on UI thread doesn't use proper JTF construct such as JTF.Run on blocking UI thread such as (Task.Wait or Result), VS can get into a deadlock.

so, as long as VS is one of Host Roslyn will support, we need to use JTF. for that, we have this 
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Shared/Utilities/IThreadingContext.cs,11

now the question is how deeply we will embrace JTF. certainly, JTF is a complete framework to do a complex threading model. but the reason Roslyn introduced JTF is not for its full ability, but due to the requirement of VS. especially if we do blocking wait on UI thread on async method that can lead to deadlock in VS.

Roslyn's pattern is making every service a true free thread service which doesn't require any thread affinity to work. and code running UI thread should be free to call Task.Wait from those services.

so, if we keep Roslyn's existing pattern, but avoid deadlock on VS, we could reduce JTF usage to JTF.Run and we abstract that out using IThreadingContext (ex, change http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Utilities/TaskExtensions.cs,51 to accept _IThreadingContext and disallow Task.Wait or Task.Result in Roslyn). so Roslyn can never need to see JTF except for VS layer which has VS specific IThreadingContext implementation. 

or we could go VS route where we fully embrace it and use it for as core currency in Roslyn like how we use Document and etc. 

I am not sure how many external dependencies we use directly in Roslyn without having our own abstraction over it but we could do so with JTF.

we can search on index (http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Shared/Utilities/IThreadingContext.cs,d8df2825cb11e07d) to see how it is used right now.

right now, we are in a weird place where JTF is directly available in Roslyn to lower layer than VS, so we start to use SwitchToMainThreadAsync to jump back to UI thread from BG, but we still use Task.Wait/Result on UI thread which can cause us to deadlock.

since JTF assumes everyone in the host to use JTF, its pattern is not exposing which thread affinity it requires, so in current pattern, there is no way for one to know whether inner code path somewhere it will do "SwitchToUIThread", so one basically can never use Task.Wait/Result on UI thread.

our current Roslyn pattern is code path explicitly checking and state that it requires UI thread.

I think we should choose one and stick to it in whole Roslyn code base rather than mixing 2.

**Comment by sharwell** [comment]
/cc @AArnott 

🔗 https://github.com/dotnet/roslyn-analyzers/pull/2400

**Comment by CyrusNajmabadi** [comment]
Thanks for having this in the open.  I'm very interested in this area.  So even if you discuss things in private, could you please leave your findings someplace (potentially here) so that external contributors know and understand the decisions and directions here?  Thanks!

tagging @jasonmalinowski  as well.

**Comment by AArnott** [comment]
> since JTF assumes everyone in the host to use JTF

strictly speaking, this is not true. JTF was created to survive in a process that didn't use it at all, initially. What it requires is that code invoked from within JTF follows JTF rules. The rest of the process can do whatever it wants.

**Comment by CyrusNajmabadi** [comment]
Closing out, this is not actionable.
