### ISSUE TITLE
Signature Help not classified in Razor

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#36933]
**Version Used**: 
16.1

**Steps to Reproduce**:

1. Show Sig Help in a C# buffer inside .cshtml

**Expected Behavior**:
Sig Help should be classified

**Actual Behavior**:
Sig Help is not classified

See https://devdiv.visualstudio.com/DevDiv/_workitems/edit/533660 for details

**Comment by CyrusNajmabadi** [comment]
Closing as external.  Razor owns these scenarios.
