### ISSUE TITLE
Question about running Samples.

### ISSUE THREAD

**Issue by alxest** [dotnet/roslyn#3695]
I want to check the samples in this page. (https://github.com/dotnet/roslyn/wiki/Samples-and-Walkthroughs)
I succeeded building "RoslynLight.sln", "Samples.sln" in windows 7, with "releases/VS2015RC" branch.
- However, when I execute "ConsoleClassifier.exe" and "FormatSolution.exe", it just exits with error. (I am sorry I cannot exactly paste the error message here, because it is written in Korean)
- Also, for other samples, I think there is no main function, cannot open corresponding .sln in visual studio (like APISampleUnitTestsCS.sln) and no .exe files are created. Is it intended behavior? If so, how should I run these?

Thanks for reading newbie question. I will soon update exact error message in comment.

**Comment by alxest** [comment]
The message's translation is (not exactly same wording)
~~~
Unhandled exception : System.IO.FileNotFoundException: File or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=*blah blah*, or one of the files or assemblies that are dependent upon these cannot be loaded. Cannot find them.
Position : Program.TestFormatterAndClassifierAsync()
Position : Program.Main(String [] args) file *~~~*\ConsoleClassifier\Program.cs Line 16
~~~

**Comment by codespare** [comment]
The samples assume they are run in a directory where their dependent Roslyn .dlls present. Their output directory is set to ./Binaries/Release or ./Binaries/Debug depending on the solution configuration. So ensure you have built Roslyn.sln (or RoslynLight.sln) in the same configuration(s) you are using for Samples.sln.

**Comment by alxest** [comment]
@codespare Thanks a lot, now it works!
