### ISSUE TITLE
Type Syntax Highlighing Not Working in Code Editor

### ISSUE THREAD

**Issue by jamsoft** [dotnet/roslyn#36950]
**Version Used**: 
Microsoft Visual Studio Community 2019
Version 16.1.5
VisualStudio.16.Release/16.1.5+29025.244
Microsoft .NET Framework
Version 4.8.03761
C# Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

**Steps to Reproduce**:

1.  Create class with interface to implement

**Expected Behavior**:
IBlogService
CoreDbContext
Post

Should all be color coded as types.

**Actual Behavior**:
![syntax-highlighting](https://user-images.githubusercontent.com/2502211/60571261-2b98b380-9d6b-11e9-87bc-07e677009862.PNG)

**Comment by CyrusNajmabadi** [comment]
Are you in a miscellaneous project?  You can tell by looking here:

![image](https://user-images.githubusercontent.com/4564579/60616679-e2eef380-9d86-11e9-8140-064b5669c844.png)

**Comment by jasonmalinowski** [comment]
Indeed @jamsoft can you share a full screenshot including the part of the screen that @CyrusNajmabadi is referenecing?

**Comment by jasonmalinowski** [comment]
Closing since we'd need additional info to investigate this. @jamsoft if you're able to provide a full screenshot please do so -- we're happy to reopen the bug.

**Comment by jamsoft** [comment]
Sorry for the delay in responding.

This bug seems to have been addressed as this class is now correctly highlighted as of VS 2019 16.2.0

**Comment by jasonmalinowski** [comment]
@jamsoft Thanks for following up and happy to know the issue has been addressed. Thanks for the report!
