### ISSUE TITLE
Referenced analyzers are slow in 3.0.0-preview6 and 7

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#36963]
The reason why analyzers are slow in preview6 and 7 looks to be that VBCSCompiler isn't sufficient to complete a compilation requests (a separate Csc process is launched) when analyzers are referenced. See below for repro steps.

**Version Used**: SDK 3.0.100-preview7-012687

**Steps to Reproduce**:

Note: You can create your own simple analyzer / console app. Below are just boilerplate templates for your convenience.

1. Unzip [TestAnalyzer.zip](https://github.com/dotnet/roslyn/files/3356784/TestAnalyzer.zip) and [ConsoleApp1.zip](https://github.com/dotnet/roslyn/files/3356785/ConsoleApp1.zip)
2. `dotnet pack` the `TestAnalyzer` project
3. Update the `nuget.config` in `ConsoleApp1` to point to where your `TestAnalyzer` package is.
4. `dotnet build` ConsoleApp1 to ensure build server is running 
5. `dotnet build --no-incremental` ConsoleApp1 to see VBCS fail to fulfill the request.

**Expected Behavior**:
VBCS is able to fulfill the compile for  `ConsoleApp1`.

![image](https://user-images.githubusercontent.com/2008729/60624319-d45e0780-9d99-11e9-84e1-835dde3f10b2.png)

**Actual Behavior**:
VBCS doesn't look to fulfill the compile for `ConsoleApp1` and Csc is invoked.

![image](https://user-images.githubusercontent.com/2008729/60624354-eb045e80-9d99-11e9-9c56-5a7c47f9bea2.png)

**Extra Info**:
This is the log output from setting `$env:RoslynCommandLineLogFile` and running the `dotnet build --no-incremental`
[ConsoleApp1.log](https://github.com/dotnet/roslyn/files/3356800/ConsoleApp1.log)

This was originally reported in the aspnet/AspNetCore repo: https://github.com/aspnet/AspNetCore/issues/11172

/cc @agocke

**Comment by agocke** [comment]
It looks like we're falling back to csc.dll and is a perf penalty. Not sure why, yet.

**Comment by agocke** [comment]
I see, the problem is that a reference exists to netstandard.dll, but that assembly (by design) doesn't exist on disk for .NET Core.

For now, you should be able to work around this by using netstandard1.3 as your analyzer target, instead of netstandard2.0.

**Comment by agocke** [comment]
(Note, you'll have to use an older version, 2.x, of Roslyn to use netstandard1.3)

**Comment by NTaylorMullen** [comment]
Thanks for the workaround @agocke! I think for now our best bet will be to wait for the fix. @mkArtakMSFT / @rynowak feel free to correct me if i'm wrong or if you feel differently.

I imagine the fix will make it into 3.0.0-preview8?
