### ISSUE TITLE
Code refactoring suggestion optimization by use of short-cut keys

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36962]
<p>There are a lot of times where one needs to write boilerplate code and one uses refactoring to generate those backing fields/ properties. Normally one types the PropertyName and assigns the value to it  (constructor variables). I write a lot of ML code and we end up making a lot of read-only properties based on calculations. It would be nice not having to wait for the CTRL+. pop-up to assume what I would like to do but to:</p><ol><li>Select all of them and do it to all</li><li>Have a short-cut key where I press a shortcut key combination and generate one of the actions that's provided.  </li></ol><p>Say use [CTRL]+[.]+[SPACEBAR] or have it assignable by the user.</p><p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/66114-refactor-short-cut-key.png"> Image:66114-refactor-short-cut-key.png</a></p><p>  I'm not saying do all of the once in the list but I am happy with the top 4 as they end up being the once that I find I use the most.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/513768/code-refactoring-suggestion-optimization-by-use-of.html
VSTS ticketId: 835891_
_These are the original issue comments:_

Jane Wu [MSFT] on 4/3/2019, 03:17 AM (91 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out as subsumed by the platform/edtior idea of making the lightbulb searchable like vs4mac used to allow.
