### ISSUE TITLE
Add comments to end statement

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36961]
<p>A small suggestion: add a comment to the end of &quot;end&quot; statements for named program components like class, sub, function. The comment would simply say &quot;'end &lt;name&gt;&quot;. I've found when skipping through methods which are longer than a page I lose track very easily. I'm working in VB.NET but it would apply to other languages as well.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/503076/add-comments-to-end-statement.html
VSTS ticketId: 826381_
_These are the original issue comments:_

Jane Wu [MSFT] on 3/25/2019, 02:18 AM (100 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment]
Have you used "Structure guidelines" 
![image](https://user-images.githubusercontent.com/12449387/60621869-b7263a80-9d93-11e9-9bd4-4a8692e8af27.png)

Does that help with your request?

**Comment by ptoye** [comment]
Yes. But some of my loop structures are bigger than a screen, so I have to keep on collapsing and expanding them to see exactly which 'end' corresponds to which 'do'. If the IDE could automatically (and optionally) add comments as I suggested it would save time and hassle.

I see your screenshot has a 'file health indicator' in it - I don't have that in mine. Is this a recent addition or an add-on?

**Comment by AdamSpeight2008** [comment]
If I understand correctly @ptoye would like the following style to be available.
```vbnet
While valid
 ' ... long section of code
End While '  (While valid)
```
This could be achieved with a code fix, but it has the potential issue of the comment not being in sync with the condition.

**Comment by ptoye** [comment]
Yes, @AdamSpeight2008 , that's exactly what I suggest. I don't quite understand your point about the comment not being in sync. I agree that if you change the condition after initially coding it the comment might also have to be altered, which might be hard to code. I think one could live with this.
