### ISSUE TITLE
Bug with params + attribute

### ISSUE THREAD

**Issue by JamesNK** [dotnet/roslyn#36974]
I came across this issue when updating Newtonsoft.Json to use nullable reference types.

**Version Used**: VS16.2 preview 3

**Steps to Reproduce**:

1. git clone https://github.com/JamesNK/Newtonsoft.Json.git
2. git checkout jamesnk/nullable-types-attributebug
3. Run JsonConverterConstructor_OverloadsWithBaseTypes test

**Expected Behavior**:

Test outputs `{"Overload":"IList<string>"}"`

**Actual Behavior**:

Test outputs `{"Overload":"object(System.Object[])"}`

This is the problem:
```cs
public class OverloadWithBaseType
{
    [JsonConverter(typeof(OverloadsJsonConverterer), new object[] { new string[] { "a", "b", "c" } })]
    public int Overload { get; set; }
}
```

Instead of the constructor getting `new object[] { new string[] { "a", "b", "c" } }` it is getting `new object[] { new object[] { new string[] { "a", "b", "c" } } }`

![image](https://user-images.githubusercontent.com/303201/60627989-fa3fe680-9e43-11e9-9abb-5cdbb182374b.png)

**Comment by jcouv** [comment]
@JamesNK Any chance you might be able to extract a self-contained repro? That would be tremendously helpful.
Here's what I tried on [sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAoEgejIGIA7AVwBt6Jh64ACOa51kk7AZjZ42AeQBuiegHsIKAOoBLGAAsAQtDgAVAJ4AHOCQDeJNqbYBtALLaAgjBgIFwWvAAU1OAHc2U4ACs4AGMYcwBdNkM2D29sfAAGMIi2ACIIZKQU4HSUwOS2AF8CgEpQkzMBNgVqGFEJBGlZJIBzOBgAbjYoVo78kl7SYgrhazsHJxd2EDZRx2d4IzLTCpH7WYnXXQgECDAoH38gkPCoIrYAXgA+NhUEKW86Rja+oA==), but didn't manage to repro the issue. Adding `#nullable enable` does not change what is emitted.

**Comment by JamesNK** [comment]
I tried to create a simplified repro like yours but the bug disappeared. I don't know what exactly in the project is causing it.

**Comment by jcouv** [comment]
Took a look at your test and I'm able to repro the problem in isolation: [sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAoAbQFkBPACgDs4B3AAgHtgArOAYxlIF0mAbyb1m2fAAZ+QpgCIIspHOCymAX3UBKPiWwBmJniYBhISTUkSAYloBXADb2Iwe3CZxaz17oNGqAQRgYBABLYFt4JhAmQOCwiLgSQRImQwMAoNDw+GoABwgECDAoVg5uXgEWTRkLYjUgA).

**Comment by jcouv** [comment]
Fix is in review
