### ISSUE TITLE
"Create and initialize property" should understand "NotImplementedException"

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#36998]
**Version Used**: 
16.2.0 Preview 3.0

**Steps to Reproduce**:

1. Derive from an interface with get-properties ("Name")
2. Run "Implement interface" which creates the properties (`Name => throw new NotImplementedException();`)
3. Create a constructor with a parameter matching the property ("name")
4. Run "Create and initialize property"

**Expected Behavior**:
The quick fix should replace the NIE.

**Actual Behavior**:
The quick fix offers to create another property ("Name1")

**Comment by sharwell** [comment]
@Tragetaschen Thanks for filing this. I think it's a great next step towards completing the picture around these features. I'm guessing it should offer the following?

### Getter only:

```patch
 class SomeType : ISomeInterface
 {
   public SomeType(string name) {
+    Name = name;
   }

-  public string Name => throw new NotImplementedException();
+  public string Name { get; }
 }
```

### Getter and setter:

```patch
 class SomeType : ISomeInterface
 {
   public SomeType(string name) {
+    Name = name;
   }

-  public string Name {
-    get => throw new NotImplementedException();
-    set => throw new NotImplementedException();
-  }
+  public string Name { get; set; }
 }
```
