### ISSUE TITLE
ETL files captured by the feedback tool should report Find Usages operations

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#36991]
We need to be able to identify out-of-process Find Usages operations in performance traces submitted by users.

* Required: an event when a Find Usages operation is started
* Encouraged: an event when a Find Usages operation is ended
    * Status (completed or cancelled)
    * Size (number of results)
    * Time

📝 This is related to, but not necessarily a duplicated of, https://github.com/microsoft/vs-streamjsonrpc/issues/277. If that issue provides access to the same information, it could be implemented instead of this one.

**Comment by CyrusNajmabadi** [comment]
Closing this out as not actionable.  If we need this, we should jsut do it.  Having a tracking issue that isn't acted upon isnt' valuable.
