### ISSUE TITLE
IDE0057 / "Use range operator": incorrect code change (missing parentheses)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36997]
Actual behaviour:
In code like the following:
```
string version = ...;
version = version. Substring(1, (version. IndexOf("-") == -1 ? version. Length : version. IndexOf("-")) - 1)
```
Visual Studio 2019 suggests to &quot;Use range operator&quot;, &quot;IDE0057 Substring can be simplified&quot;, and when invoked, changes the second line to:

```
version = version[1..version. IndexOf("-") == -1 ? version. Length : version. IndexOf("-")];
```
This results in compiler error CS0019: &quot;Operator '==' cannot be applied to operands of type 'Range' and 'int'&quot;, which is correct.

Expected behaviour:
The range operator ``.. `` apparently has higher precedence than the ternary conditional operator ``?:``, so parentheses should have been inserted as appropriate (or rather, in my example, been kept as they were); in this case, the second line might have instead been converted to:
```
version = version[1..( version. IndexOf("-") == -1 ? version. Length : version. IndexOf("-"))];
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/633621/ide0057-use-range-operator-incorrect-code-change-m.html
VSTS ticketId: 942430_
_These are the original issue comments:_

Visual Studio Feedback System on 7/5/2019, 00:57 AM (39 min ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by MarcioAB** [comment]
I would like to just double check if this solution will also solve this situation:
Consider the following code:
**var s1 = "abcabcabc".Substring(2 + 1);**
The Use range operator" quick action transform this code to:
**var s1 = "abcabcabc"[2 + 1..];**
And this is wrong. The correct should be:
**var s1 = "abcabcabc"[(2 + 1)..];**

**Comment by CyrusNajmabadi** [comment]
@MarcioAB that case should be covered. Thanks
