### ISSUE TITLE
Intellisense of params expression method parameter is not as expected

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37005]
<pre>    class Program
    {

        public class Test
        {
            public string Name { get; set; }
        }

        static void Main(string[] args)
        {
            Func(t =&gt; t.Name); 
            // the intellisense here will prompt for Expression&lt;Func&lt;Test, object&gt;&gt;[] 
            // expect intellisense of Expression&lt;Func&lt;Test, object&gt;&gt; 
        }
        static void Func(params Expression&lt;Func&lt;Test, object&gt;&gt;[] param)
        {
            Console.WriteLine(param[0].Body);
        }
    }

</pre><p>The intellisense works as expected with vs2017 and borken in vs2019.<a href="https://developercommunity.visualstudio.com/storage/attachments/76906-intellisense.png"> Image:76906-intellisense.png</a></p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/595166/intellisense-of-params-expression-method-parameter.html
VSTS ticketId: 905319_
_These are the original issue comments:_

Visual Studio Feedback System on 6/5/2019, 03:19 AM (30 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Randy Yoder on 6/6/2019, 05:53 PM (28 days ago): I'm experiencing the same issue. This broke in 16.1.0 or 16.1.1 (worked fine in 16.0.x). It is still broke in 16.1.2. Strangely, if you mouse over the t (in the example above) the tooltip gives the correct information. It is only the intellisense that is broke.
_These are the original issue solutions:_
(no solutions)

**Comment by vatsalyaagrawal** [comment]
Reproduces in 16.2.P4

**Comment by akhera99** [comment]
Does not repro in 16.11 or 17.0, closed.
