### ISSUE TITLE
[Several things] encoutered an error and has been disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37003]
VSF_TYPE_MARKDOWNCopy/paste this into a method in a C# project:

(object) Activator.CreateInstance(typeof(object). Make

BAMMO!  CSharpSpellCheckCodeFixProvider, CSharpGenerateVariableCodeFixProvider and GenerateMethodCodeFixProvider all crash at once.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/632279/several-things-encoutered-an-error-and-has-been-di.html
VSTS ticketId: 942019_
_These are the original issue comments:_

Visual Studio Feedback System on 7/4/2019, 00:49 AM (33 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
Visual Studio Feedback System on 7/5/2019, 10:15 AM (78 sec ago): <markdown><p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by pwx-nwein** [comment]
Seems like this issue has been resolved in VS 2019 16.2 preview 4.

**Comment by joshlang** [comment]
Confirmed - seems good to me too.  No longer having the issue.

**Comment by jinujoseph** [comment]
closing this issue as no repro
