### ISSUE TITLE
Condition #IF DEBUG

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37007]
If I clear the references and have the condition #if Debug even missing the reference it makes the compilation successful which makes it impossible for me to publish the project in all profiles.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/461509/condition-if-debug.html
VSTS ticketId: 795915_
_These are the original issue comments:_

Visual Studio Feedback System on 2/19/2019, 00:21 AM (136 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by gafter** [comment]
There is no problem publishing a library that is created from a single source file all of whose contents are conditionally compiled away.  Such an empty project doesn't need any references.

If this is not your situation, can you please provide a repro?
