### ISSUE TITLE
C# EE: Unable to evaluate expression

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#3701]
Sync Roslyn repo to 60c005864009f6a3d37f03d152089e6284e0eaf1.

Place breakpoint to AppendTypeInstantiation in CSharpObjectFormatter.cs as indicated:

``` C#
private StringBuilder AppendTypeInstantiation(StringBuilder builder, Type type, Type[] genericArguments, ref int genericArgIndex, ObjectFormattingOptions options)
{
     // generic arguments of all the outer types and the current type;
     Type[] currentGenericArgs = type.GetGenericArguments();
     int currentArgCount = currentGenericArgs.Length - genericArgIndex;  // <<< BP here
```

Run test `ObjectFormatterTests.DebuggerProxy_FrameworkTypes_ConcurrentQueue`under debugger until the breakpoint is hit.

Attempt to evaluate currentGenericArgs:
![image](https://cloud.githubusercontent.com/assets/41759/8368797/08f577b0-1b64-11e5-9c5c-ae0f94401d02.png)

Other variables can be evaluated fine.

**Comment by cston** [comment]
@tmat, I was not able to repro this with VS 2015 Update 3. Please re-open if this is still an issue.
