### ISSUE TITLE
Go To Definition shows [from metadata] view if target project has <Package> node

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37012]
VSF_TYPE_MARKDOWNThis happens in VS2019 but doesn't happen in VS2017 with the same solution loaded.

If I remove and re-add the reference to the target project (containing the definition), the issue goes away. The only difference is the presence of the &lt;Package&gt; node, which is not present when the project is re-added (see attached project file diff).

I don't know the purpose of the &lt;Package&gt; node or how it gets added. Should I remove it?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/489592/go-to-definition-shows-from-metadata-view-if-targe.html
VSTS ticketId: 820346_
_These are the original issue comments:_

Visual Studio Feedback System on 3/15/2019, 00:12 AM (112 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 3/15/2019, 01:12 PM (111 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

Matthias Fritsche on 3/22/2019, 02:54 AM (105 days ago): I can observe go to definition showing a metadata page instead of the source, when calling go to definition on a class or interface, that is defined in another project in the same solution.
_These are the original issue solutions:_
(no solutions)

**Comment by adriangodoy** [comment]
I have exactly the same problem:
Azure function template project 1
MSTest template project 2

When I try to navigate to definition from project 2 to 1  it goes to [from metadata] view

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
