### ISSUE TITLE
New feature: classes or members just created (renamed?) should be provided in the completion with a priority (like MRU)

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#37010]
One of scenarios:
1. Edit an existing class `Class1` with many methods by adding a new public method called `abc`
2. Go to another class referencing the former one with an instance `class1`. 
3. Type `class1.`. It would be great if `abc` would be suggested in the completion.

**Comment by ivanbasov** [comment]
Tagging @jinujoseph , @mikadumont , @kendrahavens to consider for planning

**Comment by CyrusNajmabadi** [comment]
Closing uot due to lack of feedback about thsi.
