### ISSUE TITLE
Auto-complete on event-handler generates nullableattribute event handler

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37013]
VSF_TYPE_MARKDOWN
Create a new .NET Core WPF App. Add the following lines of code:

MediaPlayer player = new MediaPlayer();
    player. MediaOpened +=

After this point, use the Tab key to auto-generate a new event handler. The event handler generated looks like this:

private void Player_MediaOpened([NullableAttribute(2)] object sender, [NullableAttribute(1)] EventArgs e)
        {
            throw new NotImplementedException();
        }

The attributes added to the parameters on the event handler won't compile.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/616546/auto-complete-on-event-handler-generates-nullablea.html
VSTS ticketId: 935335_
_These are the original issue comments:_

Morten Nielsen on 6/20/2019, 10:26 PM (14 days ago): <p>I forgot to mention: I have the latest Preview7 nightly of .NET Core installed.</p>

Visual Studio Feedback System on 6/21/2019, 02:39 AM (14 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by agocke** [comment]
fyi @jasonmalinowski

**Comment by jasonmalinowski** [comment]
Fixed by #38038.
