### ISSUE TITLE
Feature Request: Enable using static string properties like  a constan expression  for  Attributes.

### ISSUE THREAD

**Issue by moh-hassan** [dotnet/roslyn#37023]
When trying to localize Attributes using a resource file `EmployeeResx.resx , EmployeeResx.fr.res....`, static class EmployeeResx.Designer.cs is generated with static string properties like:

        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        } 
 
 Trying to use the static string fo localize the Attributes (Option in this example), like:
 
         [Option('l', "lastname",  HelpText = EmployeeResx.LastName)]
         public string  LastName { get; set; }
 
 c# compiler raise error:
>Error	CS0182	An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type	

We have to write long, complex code (for every class Attribute) to localize the Property as:

          [Option('l', "lastname",  HelpText = "LastName" ,  ResourceType = typeof(EmployeeResx))]
          public string  LastName { get; set; }

It's nice if  Roslyn can help to support the static string  for localizing attributes as explained above.
This a common task for localizing Attributes.

**Comment by moh-hassan** [comment]
Can I know why down?
The limitation of using constant expressions in Attributes  push us to write very long, complex code.

**Comment by canton7** [comment]
That fundamentally is not how attributes work. Attributes are baked into the assembly at compile-time. Your localised string is looked up at runtime.

**Comment by moh-hassan** [comment]
Roslyn provide many feature by generating code by compiler used at runtime . This fundamental task of localizing attributes has no in hand solution (but localizing property solved from day 1).
