### ISSUE TITLE
Update compiler diagnostics before running analyzers

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#37029]
After making an edit to a document in Visual Studio, diagnostics (squiggles and error list entries) for compiler-reported errors should be updated before running analyzers.

For example, consider the following code:

```csharp
class SomeType {
  void SomeMethod() {
    return
  }
}
```

The syntax error for the missing semicolon is quickly corrected by the compiler once the user adds `;`. Slower analyzers should not prevent the IDE from updating squiggles and error list to immediately show the correction.

**Comment by sharwell** [comment]
Design conclusion: this is the behavior we already expected to occur. We could have a bug where background processing is overwhelming available resources, leaving the tools unable to complete the update in a timely manner.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is how things work anyways in LSP rewrite.
