### ISSUE TITLE
AllowNullAttribute not working

### ISSUE THREAD

**Issue by JamesNK** [dotnet/roslyn#37024]
Similar to https://github.com/dotnet/roslyn/issues/36986

---

I'm converting Newtonsoft.Json to use nullable types and I can't get `AllowNullAttribute` to work. My remaining warnings are related to generic types.

Note that I have many old targets so I'm using internal nullable attributes (located in NullableAttributes.cs). `NotNullAttribute` and `NotNullWhenAttribute` work fine, but I can't get `AllowNullAttribute` to work. I've tried it in `System.Runtime.CompilerServices` and `System.Diagnostics.CodeAnalysis` namespaces with no result.

Version Used: VS2019 + Microsoft.Net.Compilers.Toolset=3.2.0-beta3-final

Steps to Reproduce:

1. git clone https://github.com/JamesNK/Newtonsoft.Json.git
2. git checkout jamesnk/nullable-types
3. Go to `JsonConverter<T>.WriteJson` method (JsonConverter.cs, line 97)

**Expected Behavior**:

There should not be a nullable warning because [AllowNull] is on the parameter type.

**Actual Behavior**:

There is a warning casting `object?` to `T`.

![image](https://user-images.githubusercontent.com/303201/60747147-538c4f00-9fd7-11e9-9836-61920ccc5ec3.png)

**Comment by jcouv** [comment]
The warning seems to be on converting from `object?` to `T` (which I assume is unconstrained).
Here's a self-contained repro which hopefully represents your situation: [sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDZICYgNQA+AsAFADEAdgK4YYTAZwAEcF9jppAAgMxNcAmJgGEAPABUAfEwDepJgv58uAFiYBZABQB7YACs4AYxgB+JtoCUs+YtsA3CAiYAPJgF4mm8Re0BuGwoAvqSBQA=).
This is currently by-design and the only mitigation is to suppress with `!`.

**Comment by jcouv** [comment]
Updated notes above. This is by-design (assigning maybe-null value to a `T` which may be non-nullable, such as `string`).
