### ISSUE TITLE
Enum member formatting should follow csharp_space_around_declaration_statements

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#37030]
**Version Used**: 

**Steps to Reproduce**:

1. Set `csharp_space_around_declaration_statements` to `ignore`
2. Create an enum with aligned values

    ```csharp
    enum SomeEnum
    {
      First =  1,
      Second = 2,
    }
    ```

3. Format document

**Expected Behavior**:

The spacing in the enum is not changed.

**Actual Behavior**:

The spacing in the enum is changed.

```csharp
enum SomeEnum
{
  First = 1,
  Second = 2,
}
```

**Comment by phizch** [comment]
I've got a fix, but I'm a total noob using git/github, and I don't know how to "properly" submit a pull request. I have also no idea how to sign the CLA. 

See this [gist](https://gist.github.com/phizch/d4b0b0afa1fd65463c02af84e4aa78d7/revisions?diff=split).
The file is "\src\Workspaces\CSharp\Portable\Formatting\Rules\SpacingFormattingRule.cs"

**Comment by nbalakin** [comment]
To submit a pull request you should click "Fork" button, at the top of the page. This will create a copy of repo in your GitHub account. Then just commit the fix to your copy of the repo. After you will be able to create a request to pull from your branch.
