### ISSUE TITLE
Add a new C# operator "in" to check if an item is in the data structure.

### ISSUE THREAD

**Issue by McKabue** [dotnet/roslyn#37037]
I would like to help create the **in** operator in C#, where do i start?

`"hi" in new string[] { "hello", "hi" } => true`

**Comment by huoyaoyuan** [comment]
You should start from the language design repo [dotnet/csharplang](https://github.com/dotnet/csharplang).
There has been several similar proposals, and none has been accepted.

**Comment by jcouv** [comment]
Yes, please find the related issues in csharplang repo (which is dedicated to language discussions, as opposed to compiler bugs).
I'll go ahead and close this issue. Thanks
