### ISSUE TITLE
[Suggestion] C# - Modifying parameter values before sending to Base constructor

### ISSUE THREAD

**Issue by Icidis** [dotnet/roslyn#3703]
Hi,

I would like to see the ability to modify parameter values before sending them to the base constructor. This is currently possible in VB and the way you can do it in C# is by using a static method. I would prefer to do it the VB way.

Thank You

Ryan Gunn

**Comment by mburbea** [comment]
Technically you can do it right now, you just need to do it in a one liner. But there's no stopping you from passing the parameter to a helper method.

```
public Child(string foo, int baz) : base(CleanUpInput(foo),baz+7)
```

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
