### ISSUE TITLE
VS 2019 16.1.3 Crash when Rename in Peek Definition window

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37043]
<p>VSF_TYPE_MARKDOWN16.1.3</p><p>1. Create new project Console App (.NET Core).</p><p>2. Add this class to **new file** next to Program.cs:</p><p>

```CSharp
using System;
using System.Diagnostics;
using System.IO;

public class ClassToRefactor
{ 
    public static void MyFunction() 
    { 
        string targetFrameworkName = AppContext.TargetFrameworkName; 
        foreach (var item in targetFrameworkName) 
        { 
            using (var test = TextReader.Synchronized(TextReader.Null)) 
            { 
                try 
                { 
                    Debug.WriteLine(item); 
                    Debug.WriteLine(item); 
                    Debug.WriteLine(item); 
                    Debug.WriteLine(item); 
                    Debug.WriteLine(item); 
                } 
                catch (Exception) 
                { 
                    throw; 
                } 
            } 
        } 
    } 
}
```

</p><p>Add missing referencies...</p><p>3. In Program.cs in Main method add: ClassToRefactor.MyFunction(); </p><p>4. Build the solution.</p><p>5. Now **close** the tab with the file where is class ClassToRefactor. (If is the file open, it doesn't crash.)</p><p>6. In Program.cs put the cursor on MyFunction and use left Alt+F12 to open partial window (Peek Definition), put cursor on &quot;item&quot; in foreach, click F2 for refactoring and try change name.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/608188/vs-2019-1613-crash-when-rename-in.html
VSTS ticketId: 918820_
_These are the original issue comments:_

Visual Studio Feedback System on 6/17/2019, 03:31 AM (21 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 6/20/2019, 10:54 AM (18 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by dpoeschl** [comment]
Other stuff in Inline Rename doesn't work in Peek either, such as the various checkboxes and buttons in the dashboard.

**Comment by dpoeschl** [comment]
It seems we should either fix the whole thing or block peek windows from participating in inline rename.

**Comment by JoeRobich** [comment]
Neither @dpoeschl or I can repro this scenario in the next preview release of 16.3. This seems to be a behavior change from 16.3 preview1 and earlier where files that participate in rename are now opened when a rename is started.
