### ISSUE TITLE
Problem with ?. operator

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37046]
VSF_TYPE_MARKDOWNProblem 1: There is suggestion to remove braces for `data_2`. After applying this suggestion we get compile time error same as if we just uncomment `data_3`. 

Problem 2:
I think even `data_3` should be legal becase there is no compile time error for `data_1`

```
var abc = "xyz";
var data_1 = abc?. ToString()?. Length; // OK
var data_2 = (abc?. Length)?. ToString(); // OK
// var data_3 = abc?. Length?. ToString(); // ERROR
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/580521/problem-with-operator.html
VSTS ticketId: 897618_
_These are the original issue comments:_

Visual Studio Feedback System on 5/23/2019, 11:16 PM (45 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Andy Gocke [MSFT] on 7/5/2019, 00:55 PM (2 days ago): <markdown><p>This sounds like a bug in the recommender, but FYI,</p>
<p><code>var data_2 = abc?.Length.ToString();</code></p>
<p>does the same thing as <code>(abc?.Length)?.ToString()</code>. The <code>?.</code> operator doesn’t execute the right-hand side if the left is null.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by gafter** [comment]
This is a recommender issue.  It should not remove the parens, or it should remove the ? too.
