### ISSUE TITLE
Feature Request: enum to act like types

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#3704]
It would be very useful if C# enums act like classes, so we can add methods within the enum's block scope:

Java:

``` java
enum DaysOfWeek{
    SUNDAY, 
    MONDAY, 
    TUESDAY, 
    WEDNESDAY,
    THURSDAY, 
    FRIDAY,
    SATURDAY;

    public boolean isWeekDay(){
        return !isWeekEnd();   
    }

    public boolean isWeekEnd(){
        return (this == SUNDAY || this == SATURDAY); 
    }

}

public class Test {
    public static void main(String[] args) throws Exception {
        DaysOfWeek sun = DaysOfWeek.SUNDAY; 
        System.out.println("Is " + sun + " a weekend? " + sun.isWeekEnd());
        System.out.println("Is " + sun + " a week day? " + sun.isWeekDay());
    }
}
```

C#:

``` c#
public enum DaysOfWeek {
    SUNDAY, 
    MONDAY, 
    TUESDAY, 
    WEDNESDAY,
    THURSDAY, 
    FRIDAY,
    SATURDAY
}

public static class DaysOfWeekExtensions {
    public static bool isWeekDay(this DaysOfWeek day) {
        return !day.isWeekEnd();
    }

    public static bool isWeekEnd(this DaysOfWeek day) {
        return (day == DaysOfWeek.SUNDAY || day == DaysOfWeek.SATURDAY);
    }
}

public class Test {
    public static void Main(String[] args) {
        DaysOfWeek sun = DaysOfWeek.SUNDAY; 
        Console.WriteLine("Is " + sun + " a weekend? " + sun.isWeekEnd());
        Console.WriteLine("Is " + sun + " a week day? " + sun.isWeekDay());

        /* Example of how C# enums are not type safe */
        sun = (DaysOfWeek) 1999;
        Console.WriteLine(sun);
    }
}
```

Reference: http://www.25hoursaday.com/CsharpVsJava.html#enums (I modified the C# example with extensions)

**Comment by leppie** [comment]
This will only be useful for virtual methods, and the only one possibly worth changing is `ToString`. I dont think this adds any value.

`using static` also aids in typing overhead. You can for example do:

```
using static System.DayOfWeek;

public static class DaysOfWeekExtensions {
    // it would have been nice if using static could be scoped here    
    public static bool isWeekDay(this DayOfWeek day) {
        return !day.isWeekEnd();
    }

    public static bool isWeekEnd(this DayOfWeek day) {
        return (day == Sunday || day == Saturday);
    }
}
```

**Comment by whoisj** [comment]
Maybe via extension methods?

**Comment by jasonwilliams200OK** [comment]
> Maybe via extension methods?

https://github.com/dotnet/roslyn/issues/3704#issue-91230946

**Comment by whoisj** [comment]
@jasonwilliams200OK I was semi-agreeing, not actually asking a question. Sorry it was from a mobile, without a proper keyboard I tend to be rather terse.

I'm not sure if this is a great idea or not, but I'm willing to accept it does have useful applications, and fit within the current paradigm if done as extension methods and not as inline member methods.

**Comment by alrz** [comment]
Adding a constructor to `enum` or `abstract` members (like Java) would need CLR support, right? So this doesn't include those features?

**Comment by gafter** [comment]
The value this would add is that it eliminates the need to define a separate class of extension methods. It also allows you to define *properties*, which cannot be done today with extensions.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

See also https://github.com/dotnet/roslyn/issues/18002 for a general discussion of closing and/or moving language issues out of this repo.

This specific request is now being tracked at https://github.com/dotnet/csharplang/issues/297
