### ISSUE TITLE
Parameter folding

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37058]
Similiar to current code folding, perhaps single line statements could be folded/expanded.

For example the statement:

    IFOO MyFoo = new MyFoos.Foo2(new Bar(){Prop1=value, Prop2=value}, SomeDependency.EnumNameOfSomeKind.Value);

Is often made more readable as something like

```
IFOO MyFoo = new MyFoos.Foo2(
                                          new Bar(){
                                                 Prop1=value,
                                                 Prop2=value
                                           },
                                         SomeDependency.EnumNameOfSomeKind.Value);
```

Either way, both have advantages depending on context... for example when searching for a specific bit of code it's much nicer to only have a small number of lines to scroll through but when looking at a specific line it much nicer to have the prettified text.

I'd like to suggest some sort of toggle or action that could be taken to produce this effect similiar to how the left margin plus and minus blocks work.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/416082/parameter-folding.html
VSTS ticketId: 757098_
_These are the original issue comments:_

Eightvo on 12/26/2018, 10:13 PM (193 days ago): <p>Possibly this toggle or action could only be availible if the line of text would require line wrapping to appear otherwise.</p>

Jane Wu [MSFT] on 12/27/2018, 02:08 AM (193 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by jinujoseph** [comment]
Related to #13066

**Comment by sharwell** [comment]
❓ To the original author: would you be OK with us implementing #13066 _instead_ of this feature, or would you still be looking for this feature in addition?

**Comment by CyrusNajmabadi** [comment]
We do this now.
