### ISSUE TITLE
FixerWithFixAllAnalyzer does not run in the compiler

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#3706]
The [FixerWithFixAllAnalyzer](https://github.com/dotnet/roslyn/blob/master/src/Diagnostics/CodeAnalysis/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs) takes a dependency on the `CodeFixProvider` and `CodeAction` types in Microsoft.CodeAnalysis.Workspaces.dll. For example:
``` C#
private static string CodeFixProviderMetadataName = typeof(CodeFixProvider).FullName;
```

This works fine in VS but causes a `TypeInitializationException` in the compilers because Microsoft.CodeAnalysis.Workspaces.dll is not available.

This should be relatively easy to fix: just replace `typeof(CodeFixProvider).FullName` with `"Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider"`, and make the related change for `CodeAction`.

**Comment by mavasani** [comment]
@tmeschter That seems like the correct fix, thanks.
