### ISSUE TITLE
Annotating unconstrained generic type in value tuples and delegates

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#37069]
**Version Used**: 3.3.0-beta1-19327-04

**Steps to Reproduce**:

```c#
(string? s, T t) M<T>() => (default, default);
//                                   ^^^^^^^ CS8619
```

```c#
void M<T>(Func<T, T?> func) { }
//                ^^ CS8627
```

How would one annotate these scenarios? Is this a supported scenario? From the [LDM notes](https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-05-15.md#simple-postconditions) it seems like `[MaybeNull]` is intended to handle unconstrained generics, but that attribute cannot be used here as far as I can tell.

**Comment by jaredpar** [comment]
This will work in C# 9 now that we can use `T?` on unconstrained type parameters

```c#
#nullable enable
public class C {
    (string? s, T? t) M<T>() => (default, default);
    void M<T>(Func<T, T?> func) { }
}
```

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoAYgDsBXDDCYDOAAjgvsdJwGYn8mBhJgG9STMUwAUOAgAYA/EyhImAFQUwAlEwCyAHhUA+CVoC8ByQBM4AMwg0Yyq7fsaA3KPE4ALDv1GcAKz6ymrm1lQUAMZaQkwAvqRxQA
