### ISSUE TITLE
AddNullCheck should use new `parameter!` syntax

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#37067]
![image](https://user-images.githubusercontent.com/12466233/60850701-4de46400-a1a5-11e9-99e9-62298b8e3a2b.png)

Instead of inserting `if (parameter is null) throw new ArgumentNullException(nameof(parameter));`, we should just mark the parameter declaration with a `!`.

We should also not offer this fix if the type of the parameter is annotated with `?`.

FYI @fayrose @agocke

**Comment by CyrusNajmabadi** [comment]
Has the compiler side of this been done?  If so, i'm happy to do the IDE side.  Is this currently in a branch, or in master?  What langversion is it gated on?

Thanks!

**Comment by jasonmalinowski** [comment]
@jcouv Is the compiler support in for this?

**Comment by jcouv** [comment]
The compiler feature is in feature branch https://github.com/dotnet/roslyn/tree/features/param-nullchecking
LDM actually decided yesterday to keep this feature out of 8.0, so no rush.

**Comment by jasonmalinowski** [comment]
@jcouv I forget, what langver is this going under? 9.0 or something sooner?

**Comment by jcouv** [comment]
The feature is now targeting 9.0.

**Comment by Youssef1313** [comment]
@jcouv 

> We should also not offer this fix if the type of the parameter is annotated with `?`.

For public method, there is no guarantee that consumers will have NRT feature enabled. So, isn't it better to still offer this fix if the paramater is annotated with `?`, BUT for public methods only?

**Comment by Youssef1313** [comment]
@jasonmalinowski Yes I see my comment is wrong. I don't know what I was thinking about when I wrote that 😄

**Comment by jasonmalinowski** [comment]
@Youssef1313, eh, it's Monday. :smile:

**Comment by CyrusNajmabadi** [comment]
Closing out.  I believe @RikkiGibson has done this.
