### ISSUE TITLE
Supress warning from "Error List" but keep color coding

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#37068]
[Original developer community feedback](https://developercommunity.visualstudio.com/content/idea/540628/supress-warning-from-error-list-but-keep-color-cod.html)

**Background**
Warnings and messages are represented with an entry in the "Error List" as well as a syntax color coding.
![image](https://user-images.githubusercontent.com/8293542/60850781-afa4ce00-a1a5-11e9-9be3-690bcc37318b.png)
![image](https://user-images.githubusercontent.com/8293542/60850799-bfbcad80-a1a5-11e9-89ea-378d5a29242b.png)
There are two methods to get rid of the warning:
 1. replace lastModified with "_". 
 2. supress the warning using #pragma warning disable

**Feature request:**
Make it possible to suppress the warning from the Error List but keep the warning in the syntax color coding.

**Motivation:**
Once the warning has been considered it should no longer be present in the Error List.
Problem with "_" is that it hides information about what is being unused.
Problem with #pragma is that I can no longer see what variable is being unused.

**Solution 1:** 
Keep color coding even if suppressed with #pragma.

Similar to how it's done with CS0162 // Unreachable code detected
Here the unreachable code is still color coded(good) but the warning is removed from the Error List(good), still the unused variable is not color coded anymore(bad).

![image](https://user-images.githubusercontent.com/8293542/60850923-348fe780-a1a6-11e9-83a4-107cfac32f95.png)

**Solution 2:**
Modify **Use discard '_'** to preserve the variable name.
Right now it suggest the following:
![image](https://user-images.githubusercontent.com/8293542/60850831-d5ca6e00-a1a5-11e9-880c-ce1a0f2cdae6.png)
Instead of the above it could suggest:
![image](https://user-images.githubusercontent.com/8293542/60850842-de22a900-a1a5-11e9-8cfc-ce6739848ca9.png)
But then I wish it still used the grey color for the parameter name:
![image](https://user-images.githubusercontent.com/8293542/60850847-e549b700-a1a5-11e9-9fdf-879d9ec36a74.png)
This requires that it's the last parameter, otherwise every parameter needs to be named.

**Comment by mavasani** [comment]
This is already supported via an editorconfig option, which you can set from `Tools -> Options -> Text Editor -> C# -> Code Style` by changing the preference for `Avoid unsued value assignments` from the default value of `Discard` to `Unused Local`

![image](https://user-images.githubusercontent.com/10605811/60912698-d82ad780-a23a-11e9-81a1-dacba1c11a18.png)

After changing the above option, the diagnostic will not fire on redundant assignments to variables as long as that variable has no reads, just only writes.

Editorconfig entry for the same:
`csharp_style_unused_value_assignment_preference = unused_local_variable:suggestion`
