### ISSUE TITLE
Introduce local refactroing generates strange code

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#37075]
```cs
public static void M(Action _)
{
    M(() => Equals(TimeSpan.FromSeconds(1), TimeSpan.FromSeconds(1)));
}
```

Is replaced with:
```cs
public static void M(Action _)
{
    M(() =>
    {
        var objA = TimeSpan.FromSeconds(1);
    });
}
```
![Animation](https://user-images.githubusercontent.com/1640096/60868142-ab6fc380-a22c-11e9-8796-468445b049a9.gif)

**Comment by CyrusNajmabadi** [comment]
Tagging @Neme12 .  Was this something that came out of some of your work to introduce blocks for expression bodied members?

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  I get:

![image](https://user-images.githubusercontent.com/4564579/198150366-0783f887-60bf-46d2-8b70-86a6cc6b4a46.png)

Which looks correct to me. Closing out.
