### ISSUE TITLE
Should `[DoesNotReturn]` affect reachability of all flow analyses?

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#37081]
Currently it only affects nullability flow analysis, but the name of the attribute does not indicate that...

**Comment by CyrusNajmabadi** [comment]
Yes plz :)

**Comment by Joe4evr** [comment]
There was an API Design Review stream that touched on this, and they concluded that `[DoesNotReturn]` is only be honored by nullability because Jared wants non-returning methods (aka `never` "type") to be `modreq`'d.

**Comment by jcouv** [comment]
From discussion with LDM today, we decided that `[DoesNotReturn]` should only affect nullability analysis. More details will be in the notes.
