### ISSUE TITLE
Disable the autocomplete feature (in C#) if spacebar is typed (re-requesting as an added feature)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37088]
<p>PLEASE provide an option to disable the autocomplete feature when the spacebar is typed. Defaulting it to &quot;disabled&quot; would be great but permanently disabling it would be even better as I doubt that there's too many developers out there who like having to backspace when trying to type something new and (OMG) hitting the spacebar.</p> <p>I did see that you currently have this feature change in your queue but that request was for C++ and I'm using C# (and don't know if the editor is the same since I don't use C++).</p> <p>I have Visual Studio Community 2017 Version 15.9.9.</p> <p>Thank you!</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/540630/disable-the-autocomplete-feature-in-c-if-spacebar.html
VSTS ticketId: 852096_
_These are the original issue comments:_

Jane Wu [MSFT] on 4/22/2019, 03:10 AM (78 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment]
@ivanbasov should not the soft selection help here ?

**Comment by ivanbasov** [comment]
There is a suggestion mode for Intellisense. The suggestion mode and the completion mode can be toggled on and off with either CTRL+ALT+Space or with Edit -> Intellisense -> Toggle Completion Mode.

In the suggestion mode, items are soft selected (border highlight). In the completion mode, properly matched items are hard selected (fill highlight).

In the suggestion mode, you can commit items intellisense items with TAB. Space and Enter are not involved with the completion, they act like Space and Enter without completion. I hope this is scenario desired. Please let us know if this solves the issue or if you have more specific scenario.
