### ISSUE TITLE
No new line after pressing Enter with suggestion open

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37082]
VSF_TYPE_MARKDOWNI have set the option to only insert a new line on pressing Enter if the suggested word was typed completely. I always did that and it used to work in VS 2017. Now it doesn't work in VS 2019. The suggestion dropdown closes but no new line is inserted. The cursor remains at the end of the typed word.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/608806/no-new-line-after-pressing-enter-with-suggestion-o.html
VSTS ticketId: 922763_
_These are the original issue comments:_

Visual Studio Feedback System on 6/17/2019, 02:50 AM (22 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 6/24/2019, 00:02 AM (15 days ago): <markdown><p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Tagging @ivanbasov.  Maybe a regression in async intellisense?

**Comment by ivanbasov** [comment]
Thank you for tagging, @CyrusNajmabadi !
Sent #37095

**Comment by ygoe** [comment]
@ivanbasov When will this be available in the release? At least in 16.2 I still had this issue again a few days ago. There's also another open VS Feedback issue for it open.

**Comment by ivanbasov** [comment]
@ygoe this one was fixed with https://github.com/dotnet/roslyn/pull/37095 in 16.3 P3. 16.3 release shoul contain it
