### ISSUE TITLE
IDE0067 fires at file-return controller method

### ISSUE THREAD

**Issue by DenisMayorko** [dotnet/roslyn#37099]
**Version Used**: VS 16.2.0 Preview 3.0

**Steps to Reproduce**:

1. Add the following controller method
```
[HttpGet("download")]
public IActionResult GetBlobDownload([FromQuery] string link)
{
    var net = new System.Net.WebClient();
    var data = net.DownloadData(link);
    var content = new System.IO.MemoryStream(data); //IDE0067
    var contentType = "APPLICATION/octet-stream";
    var fileName = "something.bin";
    return File(content, contentType, fileName);
}
```

**Expected Behavior**:

No message to dispose the content stream

**Actual Behavior**:
Message:

IDE0067	

Disposable object created by 'new MemoryStream()' is never disposed	

Use recommended dispose pattern to ensure that locally scoped disposable objects are disposed on all paths. If possible, wrap the creation within a 'using' statement or a 'using' declaration. Otherwise, use a try-finally pattern, with a dedicated local variable declared before the try region and an unconditional Dispose invocation on non-null value in the 'finally' region, say 'x?.Dispose()'. If the object is explicitly disposed within the try region or the dispose ownership is transfered to another object or method, assign 'null' to the local variable just after such an operation to prevent double dispose in 'finally'

When adding a "using" or dispose at finally block, method cannot execute, throwing "System.ObjectDisposedException: Cannot access a closed Stream"

**Comment by mavasani** [comment]
Can you please provide the code for the invoked method `File(content, ...)`? Does it dispose `content` on all code paths?

**Comment by DenisMayorko** [comment]
> Can you please provide the code for the invoked method `File(content, ...)`? Does it dispose `content` on all code paths?

Yes, it does. method File(content, ...) is default .net core controller method

**Comment by mavasani** [comment]
I suspect this is something that should be fixed in the latest builds. Can you please provide a `compilation repro` for confirmation?

**Comment by DenisMayorko** [comment]
```
    [Route("test")]
    public class TestController : Controller
    {
        [HttpGet("test")]
        [Produces("text/plain")]
        public IActionResult GetTestData()
        {
            var base64string = "dGVzdHBocmFzZQ==";
            var bytes = Convert.FromBase64String(base64string);
            var memorystream = new MemoryStream(bytes))
            return File(memorystream, "text/plain", "text.txt");
        }
    }
```
-works fine, but has message

```
    [Route("test")]
    public class TestController : Controller
    {
        [HttpGet("test")]
        [Produces("text/plain")]
        public IActionResult GetTestData()
        {
            var base64string = "dGVzdHBocmFzZQ==";
            var bytes = Convert.FromBase64String(base64string);
            using (var memorystream = new MemoryStream(bytes))
            {
                return File(memorystream, "text/plain", "text.txt");
            }
        }
    }
```
-was recommended, but gives 500 http status code

**Comment by mavasani** [comment]
Thanks for the repro.
Verified this repros on Dev16.2 bits but does not repro on Dev16.3 preview1 bits.
