### ISSUE TITLE
Microsoft.CSharp.Core.targets(59,5): error MSB6006 docker build failed on windows server 2016 core image

### ISSUE THREAD

**Issue by mchenx** [dotnet/roslyn#37098]
[AspNetWebTest.tar.gz](https://github.com/dotnet/roslyn/files/3376830/AspNetWebTest.tar.gz)

This is a solution with Asp.Net MVC project (.net framework 4.7.1) and it references to a class library TestLib (netstandard2.0). I can build this without any issue on windows 
(using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn)

But when I tried to build this with docker based on mcr.microssoft.com/dotnet/framework/sdk:4.7.1 image (which is based on mcr.microsoft.com/windows/servercore/lstc2016) , it failed 
(using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Current\Bin\Roslyn)

1. on a windows OS which has docker installed
1. download and unpack the attached package
2. go to the Dockerfile folder
3. run below command

  docker build -t aspnetwebtest .

**Comment by gafter** [comment]
What exactly is the failure mode?  Is there an exception from the compiler?  Is there a stack trace?

**Comment by mchenx** [comment]
no detailed exception printed but an error code "MSB6006", line number 59 and exit code -2146232576 . is there anything I can do to produce more details like "--verbose" switch or somehing like that? maybe  -detailedsummary, will try later this week.

**Comment by mchenx** [comment]
I was encountering this in a windows server 2016 core docker image, the same project (git repo) was compiled fine on either windows server 2016 core or on windows 10 by using either MSBuild or VS2017
