### ISSUE TITLE
VB Sample ConvertToAutoPropertyVB doesn't execute

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#3710]
The VB Sample ConvertToAutoPropertyVB and a Refactoring I wrong also fail to execute with identical errors. They load in a new instance of VS 2015 RC, you get the lightbulb but you don't get any options, 

You get to 
        context.RegisterRefactoring(
            New ConvertToAutopropertyCodeAction("Convert to auto property",
                                                Function(c) ConvertToAutoAsync(document, propertyBlock, c)))
 but never get to ConvertToAutoAsync

Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: devenv.exe
  Problem Signature 02: 14.0.22823.1
  Problem Signature 03: 5538ad9e
  Problem Signature 04: Microsoft.CodeAnalysis.VisualBasic
  Problem Signature 05: 1.0.0.50411
  Problem Signature 06: 55295a76
  Problem Signature 07: 550d
  Problem Signature 08: 0
  Problem Signature 09: System.AggregateException
  OS Version:   6.3.9600.2.0.0.400.8
  Locale ID:    1033
  Additional Information 1: 5861
  Additional Information 2: 5861822e1919d7c014bbb064c64908b2
  Additional Information 3: a10f
  Additional Information 4: a10ff7d2bb2516fdc753f9c34fc3b069

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #38](https://github.com/dotnet/roslyn-sdk/issues/38) via [**ZenHub**](https://www.zenhub.com/)
