### ISSUE TITLE
[loc][Query][Roslyn] Localizability of 0; "RudeEdit"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#37104]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Rude edit

File Name:
Features\Core\Portable\xlf\FeaturesResources.xlf
==========================================
Query:
What does "rude edit" mean? Please explain. Translated literally for now.

**Comment by jcouv** [comment]
Tagging @ivanbasov for this  question

**Comment by ivanbasov** [comment]
There is a edit-and-continue functionality in debugging:
1. Start debugging
2. Pause debugging, e.g. with a breakpoint or a Debugger.Break() or whatever.
3. Edit code
4. Proceed with debugging
This means we actually change code _on fly_.

Not all edits on step 3 can be supported (https://docs.microsoft.com/en-us/visualstudio/debugger/supported-code-changes-csharp?view=vs-2019). Some of them are too complex to be applied _on fly_. For those edits, we provide a diagnostic called _rude edit_.

@tmat may want to add more.

**Comment by PDostalek** [comment]
THanks !
