### ISSUE TITLE
Workspace.Kind can be null

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#37110]
While applying nullable annotations I noticed that Workspace.Kind can be null. At first this seems "odd" but arguably is also a feature: the workspace kind is used to find workspace services defined for that specific workspace. A null workspace kind would mean that there are just no special services for the workspace.

I left the annotation as nullable for now and if we decide to keep it this way we may need to add tests.

**Comment by jasonmalinowski** [comment]
We decided to call this an "accidental feature" and will document accordingly. Since everybody's exposure to Kind is just comparing it to specific values, allowing it to be null has no impact to their use.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we want to do something here we shoudl just do it.  These issues don't help us on that.
