### ISSUE TITLE
Attributes applied to async entrypoint method does not have effect

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/roslyn#37122]
**Version Used**: 
Visual Studio 2019 d16.3

**Steps to Reproduce**:

1. Assume I am creating an app for COM interop that requires STA Thread. Create a netcoreapp3.0 Console and reference WinRT contract package
2. Write the code like this
```c#
[STAThread]
static async Task Main() {
    Console.WriteLine(Thread.CurrentThread.GetApartmentState());
}
```

**Expected Behavior**:
Expected to output "STA"

**Actual Behavior**:
Outputs "MTA" (C# language default)

If I change the Main method back from `async` to `void`, it outputs the correct thread state "STA".

I guess it is an issue where the attributes applied to the entrypoint method in code does not bring to the real entrypoint the compiler is generated.

**Comment by onovotny** [comment]
I just hit this when trying to create a generic host for WPF apps where the entry point would be an async Main.

**Comment by svick** [comment]
This has been previously discussed at https://github.com/dotnet/roslyn/issues/22112, where the conclusion was:

> As mentioned in dotnet/csharplang#97, this was explicitly considered and rejected by LDM. […]
>
> Regardless, this needs to be taken through the dotnet/csharplang repo and LDM before we'd consider a compiler change here.

**Comment by onovotny** [comment]
This is a significant issue when dealing with UI apps, which were not necessarily being though of at the time of that LDM.

If you want to have an Async Main entrypoint of a WinForms or WPF app, this feature doesn't work at all, and leads to errors even when the user does what they expect should work.

**Comment by gafter** [comment]
The current behavior is by design.  Do not use an async Main if this is not the behavior you want.

**Comment by onovotny** [comment]
My point here is that the behavior is not obvious that making Main async would break the applied attribute. The attribute is applied and it would be expected to work.

**Comment by mazhou-msft** [comment]
I personally disagree with a resolution by design. If this feature is not available for UI apps, it should error while compiling. When developers consider Async Main, they would think it will work always. It you tell them it doesn't work for adding attributes, they should know it in an easy way, either from a live code analysis, or somewhere documented. Leaving this without any warning will generate code with unexpected behavior and it can not be addressed before run. 

I would like to propose following if LDM's rejection is unable to debate.
- When a `Main` method is `async`, and one or more attributes are associated, generate a compiler error message on the `Main` method saying "The attributes applied to async Main will not apply to the underlying compiler generated entrypoint method."
