### ISSUE TITLE
C# Interface Icon

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#37127]
[Original developer community feedback](https://developercommunity.visualstudio.com/idea/461373/visual-c-interface-icon.html)

C# class and C# interface share the same icon.

Suggestion: if a class file contains only an interface(s) and nothing more, make its icon use "interface-like" picture

**Comment by sharwell** [comment]
😕 I see different icons for the two:

![image](https://user-images.githubusercontent.com/1408396/61318001-eb98ee00-a7b8-11e9-9876-0c440e1fe90c.png)

**Comment by CyrusNajmabadi** [comment]
Not repro.
