### ISSUE TITLE
Quick Info shouldn't show the null state of non-nullable value types or constants

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#37157]
Version used: 3.3.0-beta1-19354-02

The IDE shows the null-state for this enum member, which doesn't really make sense to me because

1. it's a non-nullable value type, and
2. it's a constant, so I can already see in Quick Info that its constant value is non-null.

<img width="496" alt="nullability-quick-info" src="https://user-images.githubusercontent.com/5833655/61080947-faf3f200-a3da-11e9-93fe-a76b9d210023.PNG">

**Comment by 333fred** [comment]
@jasonmalinowski, apparently rikki agrees with me :). /cc @ryzngard

**Comment by davidwengier** [comment]
This confused me too..
![image](https://user-images.githubusercontent.com/754264/61495006-1b373880-a9fb-11e9-9827-42594421ffb4.png)

In particular I think the wording of "is not null here" makes it seem like it sayings it could be null elsewhere.

**Comment by nguerrera** [comment]
I agree too, and find this very confusing.f it must say something, "'x' can never be null" would be clearer, but I'd vote to remove it.

**Comment by 333fred** [comment]
After discussion with @cston, I think the appropriate solution here is to standardize value types on a NullableAnnotation.NotApplicable and NullableFlowState.NotApplicable. You cannot have null value types that aren't Nullable.

**Comment by 333fred** [comment]
Leaving @ryzngard assigned as I'm sure there will be some IDE work to react.

**Comment by cston** [comment]
@ryzngard, after #34412 is fixed, the annotation from the public API for non-nullable value types will be `NotAnnotated` always, so value types will need to be special-cased in the IDE to avoid reporting "is not null here".

**Comment by CyrusNajmabadi** [comment]
> so value types will need to be special-cased in the IDE to avoid reporting "is not null here".

Note: please test nullable value types when you do this to make sure the experience makes sense.
