### ISSUE TITLE
Handle CallerMemberName gracefully in nullable

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#37152]
The cannonical way to use the `CallerMemberName` attribute is by assigning null as a default value to it, like so:
```C#
public void M([CallerMemberName] string param = null) {
}
```
But this will produce a warning, because param is declared as having a default value of null, even though the `null` won't ever actually be used. We should try and support the existing way people write this code, without requiring them to suppress the null.

**Comment by JohanLarsson** [comment]
Also remember to support `param` being nullable. In WPF it is common to have:

```cs
protected virtual void OnPropertyChanged([CallerMemberName] string? propertyName = null)
{
    this.PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
}
```

And passing `null` means notify for all properties. Not sure if `null` and `string.Empty` has different meanings but chances are there is code relying on it.

**Comment by jcouv** [comment]
@333fred Did we conclude that the proper way of declaring `M` is `public void M([CallerMemberName] string? param = null)`?

**Comment by 333fred** [comment]
@jcouv no. The examples on docs.microsoft.com do use "" as the default value, but other than the code examples there is no official guidance on what default value should be used. The question here is a tradeoff I think, because for the scenario that @JohanLarsson outlined above, it would be a bad thing if we didn't warn about `string propertyName = null`.

**Comment by 333fred** [comment]
Seeing that example though, I'm thinking that the current behavior, while unfortunate for some scenarios, is probably correct. If you want to have a defaultValue of `null`, then you need to `!` or declare as nullable.

**Comment by jcouv** [comment]
From discussion with Mads, the current behavior seems fine. I'll go ahead and close. Thanks
