### ISSUE TITLE
CS1935 message is misleading

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#37165]
```
error CS1935: Could not find an implementation of the query pattern for source type 'int[]'. 'Join' not found. Are you missing a reference to 'System.Core.dll' or a using directive for 'System.Linq'?
```

System.Core.dll is not sufficient when targeting .NET Core, System.Linq.dll also must be present. 
Rather than giving a misleading message we should remove the "a reference to 'System.Core.dll' or" part when building for .NET Core.

**Comment by tmat** [comment]
@agocke FYI

**Comment by gafter** [comment]
Roslyn does not currently have a concept of "building for .NET Core".

**Comment by tmat** [comment]
We might want to remove the dll name from the message altogether.

**Comment by kfechter** [comment]
I have a PR ready that removes the reference to the system.core.dll from the CS1935 message. New to contributing. build works and tests pass. Only thing I have a question on is the "needs-review-translation" for the associated language resource files how is that handled? The change to the message text caused a rebuild of the translation xml files.
