### ISSUE TITLE
Detect missing "else" in C# code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37167]
<p>Is it possible for Visual Studio to detect a missing &quot;else&quot;?  For example, I accidentally deleted the &quot;else&quot; in the following code and sadly it took a bit of debugging for it to dawn on me what was wrong...</p> <p>if (x == 3) {</p><p>    //  Do something</p><p>}</p> <p>{</p><p>    MessageBox.Show(&quot;x is not equal to 3!&quot;);</p> <p>}</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/636837/detect-missing-else-in-c-code.html
VSTS ticketId: 943622_
_These are the original issue comments:_

Jay Buckman on 7/8/2019, 08:14 AM (3 days ago): <p>But, I do have to admit that I don't remember having done this before and failed to notice it while pursuing the code.</p>

Jane Wu [MSFT] on 7/9/2019, 03:13 AM (2 days ago): <markdown><p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>
</markdown>
Jay Buckman on 7/9/2019, 04:07 AM (2 days ago): <p>Jane, Thanks!  I've been writing software for over 40 years and I think Visual Studio 2019 is spoiling me because it's so good.  Or I'm just getting old. But thanks for considering the suggestion.</p>

**Comment by canton7** [comment]
Sounds like a job for an analyser?

**Comment by gafter** [comment]
How is the IDE supposed to know there should be an else there?

**Comment by canton7** [comment]
I assume the case "if, followed by a block, followed immediately by another block" would be something an analyser could pick out? Granted that could quite easily be legitimate code, so it would have to be opt-in.

Various standards (such as MISRA-C) also say that if you have an if/else if, you must have a final else (although it can just contain a comment), which is in roughly the same area.

**Comment by CyrusNajmabadi** [comment]
Yes.  This should def be an analyzer.  I don't think however it needs to really be owned by roslyn. it's fairly trivial and i would love a chance to teach a person to fish here.

**Comment by jaybuckman** [comment]
Cyrus - I'm willing to learn...

**Comment by CyrusNajmabadi** [comment]
@jaybuckman This would be a pretty simple [syntactic analyzer](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/get-started/syntax-analysis).  In this case, all the analyzer would have to do is look for an if-statement (without an `else-clause`) followed by a block-statement.  It would then just report a warning that this seems odd and maybe there's a missing `else`.
