### ISSUE TITLE
"Add Using" refactoring should not simplify when using is within namespace block

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#3716]
Roslyn’s “add using” refactoring adds simplified usings. That is, my block of using statements appear inside my namespace block, and Roslyn is trimming off the prefix that is common between my namespace and the namespace being imported.

I find "simplified" using statements to be quite confusing. I'd like to turn off simplification of using statements. Please make this an option (or the default behavior).

**Comment by Pilchie** [comment]
Note that this is part of a set of larger style items around usings (e.g. reporting diagnostics for unsorted ones with a quick fix, etc).

**Comment by nertim** [comment]
Any idea on when this will be available? Our team just upgraded to VS 2015 and would really appreciate the fix for not adding "simplified" namespaces.

**Comment by Pilchie** [comment]
It's not currently scheduled to a milestone.

**Comment by BillHiebert** [comment]
Can we raise the priority of this? Having to manually go back and fix every using is incredibly annoying.

**Comment by CyrusNajmabadi** [comment]
This does not repro for me.  We produce the fully qualified name for an import when adding a using:

![image](https://user-images.githubusercontent.com/4564579/75635267-971c7480-5bc9-11ea-81e7-b00ca1b1d52c.png)
