### ISSUE TITLE
Add classification support for the nullable suppression operator

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#37175]
I'd love it if this was a separate classification type so I could make uses of it red. I'd propose the default is still to have the standard color since people may not like that.

**Comment by jasonmalinowski** [comment]
This was discussed and agreed that people indeed may want to flag this since it's a special and potential evil operator. We'll offer a special classification option but by default it won't do anything.

**Comment by CyrusNajmabadi** [comment]
Closing out.  if we want to do this, we should make an actual work item with a real milestone.
