### ISSUE TITLE
Compiler emits incorrect PDB info for synthesized variable of kind SwitchCasePatternMatching 

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#37172]
```C#
public class C
{
    static int F(int i)
    {
        return N(out var x) switch 
        {
            0 => 0,
            _ => x
        };
    }

    static int N(out int x) => x = 1;
}
```

The compiler generates
```
{
  // Code size       32 (0x20)
  .maxstack  1
  .locals init (int V_0, //x
                int V_1,
                int V_2,
                int V_3,
                int V_4)
  IL_0000:  nop
  IL_0001:  ldloca.s   V_0
  IL_0003:  call       ""int C.N(out int)""
  IL_0008:  stloc.2
  IL_0009:  ldloc.2
  IL_000a:  brfalse.s  IL_000e
  IL_000c:  br.s       IL_0012
  IL_000e:  ldc.i4.0
  IL_000f:  stloc.1
  IL_0010:  br.s       IL_0016
  IL_0012:  ldloc.0
  IL_0013:  stloc.1
  IL_0014:  br.s       IL_0016
  IL_0016:  ldloc.1
  IL_0017:  stloc.3
  IL_0018:  ldloc.3
  IL_0019:  stloc.s    V_4
  IL_001b:  br.s       IL_001d
  IL_001d:  ldloc.s    V_4
  IL_001f:  ret
}
```

and PDB info:

```
<encLocalSlotMap>
          <slot kind=""0"" offset=""28"" />
          <slot kind=""35"" offset=""18"" />
          <slot kind=""35"" offset=""18"" /> 
          <slot kind=""28"" offset=""18"" />
          <slot kind=""21"" offset=""0"" />
</encLocalSlotMap>
```

The temps `V_1` and `V_2` have the same type, kind and syntax offset, which is not allowed. (`CSharpDefinitionMap.CreateLocalSlotMap` fails with `System.ArgumentException : An item with the same key has already been added.` when this method is edited.)

The comment here is no longer valid:
http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/CodeGen/EmitStatement.cs,1440

Due to this issue we can't allow EnC of methods containing switch expressions.

**Comment by tmat** [comment]
@gafter FYI

**Comment by gafter** [comment]
@tmat Please let me know if you still need me to address this.

**Comment by gafter** [comment]
@tmat said

I figured this is caused by this line in switch expression lowering: https://github.com/dotnet/roslyn/blob/4bf14495d477ea2c5d95273e0a3fe56bfa9a4784/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_SwitchExpression.cs#L60

Seems to me that resultTemp is not a long lived variable. It's life only spans the switch expression, correct? If so then the kind should be SynthesizedLocalKind.LoweringTemp

**Comment by tmat** [comment]
Yup. I have a fix for this one.

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/37239
