### ISSUE TITLE
Extract interface needs to copy along #nullable context

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#37177]
If you invoke extract interface into a new file, right now we aren't copying along the nullable context so you might get ?s where you don't support them.

This needs #36101 for us to implement it properly.

**Comment by ryzngard** [comment]
We also need to include Extract Interface as part of this, since it will have similar constraints. 

Duped https://dev.azure.com/devdiv/DevDiv/_workitems/edit/843166 against this

**Comment by jasonmalinowski** [comment]
We discussed this in a few different ways:

**How hard would it be to do this?** The biggest concern was if we have to have any code here reach back to the semantic model APIs to figure out which context was active at each of those points, since we don't flow information like that today. I _believe_ it might be possible to instead base it on the annotation data on the symbols of the members themselves: I'd expect a type in a signature of a method to have annotated/not annotated if we're in a #nullable enable and "None" otherwise; relying on that information would also allow other scenarios too like implement interface -- there we wouldn't have the semantic model in the first place for the source of the signatures.

That all said, this issue was created a few years ago as a part of the general backlog creation for this feature; we haven't really heard much complaining about it. We have one upvote on this, but it's just that: one. We're not sure this sort of mixing is terribly common in a lot of code out there, so we're just going to close this as not planned unless we hear more demand for it.

**Comment by jasonmalinowski** [comment]
And oh: we did confirm that today we don't copy the directives, but we do remove ?s in that case so we arent generating broken code. That's not ideal if the user wanted to keep those around, but we're not generating broken code which is good.
