### ISSUE TITLE
Convert to full property loses nullability

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#37182]
If you write:

```
string? S { get; set; }
```

and try converting this to a full property, the backing field loses the ?.

**Comment by CyrusNajmabadi** [comment]
Out of curiosity, are we keeping track of how much of this stuff would just work if it was the case that type symbols just carried nullability?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi At this point switching to types that carry nullability is the plan, but the compiler is more than underwater at this point to attack that.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski 

> @CyrusNajmabadi At this point switching to types that carry nullability is the plan, but the compiler is more than underwater at this point to attack that.

Understood.  I was not trying to be snarky.  I think the current plan makes a lot of sense and is hte best way forward.  It was more curiosity than anything :)

**Comment by jasonmalinowski** [comment]
Oh, no snark taken!
