### ISSUE TITLE
Navigate to decompiled source doesn't handle nullable attributes

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#37184]
We'll need to update to a newer ILSpy library.

**Comment by jasonmalinowski** [comment]
We should make sure we pick up https://twitter.com/ilspy/status/1160814033299226626?s=20 at least since they have the changes for metadata work.

**Comment by christophwille** [comment]
Our version 5.0 just released https://www.nuget.org/packages/ICSharpCode.Decompiler/ - feel free to pick it up for NRT support in the F12 experience.

**Comment by christophwille** [comment]
https://github.com/dotnet/roslyn/pull/39660 has been opened for stable 5.0.2
