### ISSUE TITLE
notnull constraint is allowed outside of enabled nullable context

### ISSUE THREAD

**Issue by cartermp** [dotnet/roslyn#37199]
**Version Used**: 

Microsoft Visual Studio Community 2019 Int Preview
Version 16.3.0 Preview 1.0 [29111.216.d16.3]
VisualStudio.16.IntPreview/16.3.0-pre.1.0+29111.216.d16.3
Microsoft .NET Framework
Version 4.8.03752

**Steps to Reproduce**:

Create a new .NET Core console app with the following code:

```csharp
using System;

namespace ConsoleApp114
{
    class Foo<T> where T: notnull
    {

    }


    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}

```

**Expected Behavior**:

Unrecognized `notnull` constraint, since I have not enabled a nullable context.

**Actual Behavior**:

`notnull` is allowed.

IMO the severity here is low I suppose.

**Comment by jcouv** [comment]
If I recall, this was by-design (from discussion between Aleksey, myself and possibly others), but not blessed by LDM.
The nullable context affects the interpretation of types (what does `string` mean). But there is no ambiguity for `notnull`...

**Comment by jcouv** [comment]
Got okay on "by design" in email. I'll go ahead and close. Thanks
