### ISSUE TITLE
Files with errors should have a red underline in Solution Explorer

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#37191]
**Version Used**: 

Visual Studio 2019

**Steps to Reproduce**:

Files with errors should be surfaced in solution explorer with a red underline: 

![sln-error-surface](https://user-images.githubusercontent.com/46729679/61146100-0a804300-a48e-11e9-9353-97c574575511.png)

**Comment by CyrusNajmabadi** [comment]
Tagging @kendrahavens .  I would very much like this feature.  It definitely feels absent when using VS versus other IDEs.

**Comment by jmarolf** [comment]
@olegtk 	if I remember correctly there are perf problems in the extension that does this. Would it be a lot of work to resolve those?

**Comment by olegtk** [comment]
There was a perf issue in PPT extension that implements this (still is perhaps), but it was just an inefficient implementation improperly leveraging error list API, not a fundamental limitation. Please drive it, @kendrahavens, @mikadumont.

**Comment by CyrusNajmabadi** [comment]
This is not roslyn.  This should be tracked with an internal issue.

**Comment by CyrusNajmabadi** [comment]
And ideally this falls out with LSP.

**Comment by olegtk** [comment]
Agree. @mikadumont, please file a suggestion ticket so we can start collecting votes for this work.
