### ISSUE TITLE
Testing results progress flashes continuously while running tests in an extremely distracting manner.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#37195]
I can't tell what would cause this behavior.  But it's highly annoying and distracting.

![testing](https://user-images.githubusercontent.com/4564579/61158713-ac178c80-a4ae-11e9-864c-fd23e305cb89.gif)

**Comment by CyrusNajmabadi** [comment]
Tagging @kendrahavens

**Comment by jcouv** [comment]
Tagging @AbhitejJohn

**Comment by CyrusNajmabadi** [comment]
@jinujoseph can this be assigned?  Thanks!

**Comment by jinujoseph** [comment]
following up

**Comment by ManishJayaswal** [comment]
@jfleisher - have you seen this?
@CyrusNajmabadi  - what build are you seeing this in? Is it 16.2 preview 3?

**Comment by CyrusNajmabadi** [comment]
Yes.  I have:

![image](https://user-images.githubusercontent.com/4564579/61251628-e2a01200-a70f-11e9-981d-e967bbb3ec4c.png)


This repros 100% of the time.  Thanks!

**Comment by ManishJayaswal** [comment]
@CyrusNajmabadi  - thanks! We are investigating this.
