### ISSUE TITLE
Can't 'configure' some IDE analyzers

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#37204]
![image](https://user-images.githubusercontent.com/4564579/61175892-062a5780-a56c-11e9-8921-1d57190e246f.png)

@mavasani I can 'suppress' this, but i can't configure this.  For example, if i want to make this an error, i don't see how i can use the UI to do that.  

Is this a bug?  Intentional behavior?

Thanks!

**Comment by JohanLarsson** [comment]
Also it would be nice to be able to make something an "editor error" so that it renders with red squiggles or something similar to really stand out. A typical use case is unused usings, locals, parameters, members

**Comment by mavasani** [comment]
@CyrusNajmabadi The configuration feature has been disabled currently and blocked on https://github.com/dotnet/roslyn/issues/36330 (enabling editorconfig by default in IDE and compiler). Tagging @jasonmalinowski @jinujoseph - when can we expect removal of IDE experimental flag and the MSBuild flag that turns off editorconfig discovery?

**Comment by jinujoseph** [comment]
Hope is that we can enable it default by 16.3.Preview2 , Jason is following up testing this feature

**Comment by jasonmalinowski** [comment]
Yep, we're hoping to merge it this week.

**Comment by JohanLarsson** [comment]
Out of curiosity what is the feature being merged? I don't think unused using being a compiler error is an ergonomic solution.

**Comment by jasonmalinowski** [comment]
There's going to be additional stuff where you can configure the severity in the .editorconfig. @CyrusNajmabadi is alluding to the fact that right now it says "Configure or Suppress" but we don't actually give any configuration options since the new feature is still under feature flag.

**Comment by jasonmalinowski** [comment]
Alright sounds like should be fixed now in 16.3 Preview 2.
