### ISSUE TITLE
Can't build latest roslyn

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#37209]
![image](https://user-images.githubusercontent.com/4564579/61177200-00d90700-a584-11e9-83fd-5376a68e858b.png)

Error is:
Error	CS1025	Single-line comment or end-of-line expected	

Looks like we're trying to use nullable, but the IDE doesn't understand it.  

Not sure what to do about this.

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski

**Comment by jcouv** [comment]
Strange. What version of VS are you using?

**Comment by jasonmalinowski** [comment]
Ah, hmm I didn't think about this -- I guess that implicitly means we now depend on a VS that knows about the syntax. Cyrus I'm guessing you're using 16.2?

**Comment by jasonmalinowski** [comment]
I'd also guess your command line build still works and you can ignore this which I admit is an unpleasant experience.

**Comment by CyrusNajmabadi** [comment]
I'm on: 

![image](https://user-images.githubusercontent.com/4564579/61239653-474d7380-a6f4-11e9-955b-bf813460ca06.png)


This is hte latest version that i've been offered.

**Comment by jasonmalinowski** [comment]
So yeah if that was merged in Preview 4 there isn't a build that supports it that's public. That'll be fixing itself Really Soon Now™ so we're probably best off just not trying to do further mitigations.

**Comment by YairHalberstadt** [comment]
I'm on version 16.1.3 and Restore.cmd is failing with:

```
E:\Git\roslyn\.dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.TargetingPackResolut
ion.targets(85,7): error MSB4131: The "LegacyFrameworkPackages" parameter is not supported by the "ResolveFrameworkRefe
rences" task. Verify the parameter exists on the task, and it is a gettable public instance property. [E:\Git\roslyn\sr
c\Compilers\Core\Portable\Microsoft.CodeAnalysis.csproj]
```

I don't know if this is related at all.

**Comment by jasonmalinowski** [comment]
Preview 4 is now public which will fix @CyrusNajmabadi's issue. @YairHalberstadt are you still seeing that? We can open an new issue to track.

**Comment by YairHalberstadt** [comment]
It seems to be able to build.
