### ISSUE TITLE
Intellisense not listing "var" when starting to write a foreach ref loop

### ISSUE THREAD

**Issue by diryboy** [dotnet/roslyn#37223]
**Version Used**: 
VS16.1.6

**Steps to Reproduce**:

1. Type "foreach" and hit <kbd>tab</kbd> twice
2. Type "ref var" and hit <kbd>tab</kbd>

**Expected Behavior**:

```C#
foreach (ref var item in collection)
{
}
```

**Actual Behavior**:

```C#
foreach (ref EnvironmentVariableTarget item in collection)
{
}
```

**Comment by CyrusNajmabadi** [comment]
@dpoeschl was this missed during the test pass for `foreach (ref`?  i'm surprised that we wouldn't have a standard typing/completion test here.

**Comment by diryboy** [comment]
`foreach (ref |)` does cause `var` in list, but `foreach(ref | item in collection)` doesn't.

Checked Syntax Visualizer, looks like the parser 'fakes' another `(..in..)` before the actual `(ref item in collection)` and turns it into a LocalDeclarationStatement.

![image](https://user-images.githubusercontent.com/159110/61269661-dbd9d380-a7d1-11e9-803a-b417ee96dc5f.png)

**Comment by diryboy** [comment]
Debugged thru code, [VarKeywordRecommender](https://github.com/dotnet/roslyn/blob/master/src/Features/CSharp/Portable/Completion/KeywordRecommenders/VarKeywordRecommender.cs) tests `context.IsLocalVariableDeclarationContext` which uses the result of the following test from [SyntaxTreeExtensions](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs#L1567)

```C#
            // ref |
            // ref readonly |
            if (token.IsKind(SyntaxKind.RefKeyword, SyntaxKind.ReadOnlyKeyword) &&
                token.Parent.IsKind(SyntaxKind.RefType) &&
                token.Parent.IsParentKind(SyntaxKind.VariableDeclaration) &&
                token.Parent.Parent.IsParentKind(SyntaxKind.LocalDeclarationStatement))
            {
                return true;
            }
```

The code looks perfectly matches the result of the Syntax Visualizer, however `token.Parent.IsParentKind(SyntaxKind.VariableDeclaration)` returns `false`, `token.Parent.Parent.Kind()` is really `ForEachStatement`.

**Comment by diryboy** [comment]
OK, I understand the issue. `foreach (ref` is incomplete so `token.Parent.Parent.Kind()` is `VariableDeclaration`, `foreach (ref v x in y)` is complete so `token.Parent.Parent.Kind()` is `ForEachStatement`, I will send PR for this.
