### ISSUE TITLE
Null conditional on Await not working and throwing null exception

### ISSUE THREAD

**Issue by SHuygh** [dotnet/roslyn#37225]
**Version Used**: 
?

**Steps to Reproduce**:

1) Add a method returning a Task to an object class
2) Don't initialise the object
3) use null conditional await TestObject?.TestTask();
4) will result in null reference exception (Without await this works)

Example:
[Sharplab compiled/decompiled](https://sharplab.io/#v2:D4AQTAjAsAUCAMACEECsBuWsQGZlkQGFEBvWRCxABwCcBLANwEMAXAU0QBU2BnFg9nwD2AIwBWbAMYtMMSonKVcyABzIALIgCyACgCUpRfPkgAnIkEtRE6QH4AdNz4gAbPtnyAvkZ9ylecC5efiNDP2NkAJcg5zc9UPkycIilAHZkF3tCIQBbKgAbNnYAE1cPFO9kys8gA==)

Exception due to line
awaiter = ((testobject != null) ? testobject.TestTask() : null).GetAwaiter();

**Expected Behavior**:
Won't run the task and doesn't throw the exception

**Actual Behavior**:
Throws null exception

**Comment by canton7** [comment]
This is expected. `TestObject?.TestTask()` will returns in `null` if `TestObject` is `null`, and `await null` will throw a `NullReferenceException`.

You'll want to null-check `TestObject`, or use `await TestObject?.TestTask() ?? Task.CompletedTask`.

See https://github.com/dotnet/csharplang/issues/35 for a proposal to introduce `await?`, which would not throw in this case.

**Comment by SHuygh** [comment]
Thank you for the update
