### ISSUE TITLE
'new' keyword not hiding method

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37230]
If a base class has a method and a derived class hides the method using the 'new' keyword, if the methods have the same signature but differ only by parameter names, both methods are visible in the derived class. (see attachement for example)

```
using System.Diagnostics;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var c = new DerivedClass();

            c.Method(param1: "Hello World");
            c.Method(param2: "Good Bye World");
        }
    }
}

public class BaseClass
{
    public void Method(string param1)
    {
        Debug.WriteLine($"Base Class {param1}");
    }
}

public class DerivedClass : BaseClass
{
    new public void Method(string param2)
    {
        Debug.WriteLine($"DerivedClass {param2}");
    }
}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/643197/new-keyword-not-hiding-method.html
VSTS ticketId: 946449_
_These are the original issue comments:_

Visual Studio Feedback System on 7/15/2019, 01:04 AM (10 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by HaloFour** [comment]
Apart from being a breaking change, it doesn't feel like shadowing is supposed to make the shadowed method impossible to call?

**Comment by gafter** [comment]
In looking at the language specification, although a `new` declaration does *hide* the declaration from the base, the hidden declaration is still inherited and is a member of the method group, and the invocation resolves uniquely to that method.

There is an error in https://github.com/dotnet/csharplang/blob/master/spec/basic-concepts.md#scopes which says

> The name from the outer scope is then said to be **_hidden_** in the region of program text covered by the inner scope, and access to the outer name is only possible by qualifying the name.

Your example demonstrates that this summary is not correct.  This issue has been reported to [ECMA](https://github.com/ECMA-TC49-TG2/spec/issues/959).
