### ISSUE TITLE
UniqueItem is not triggered when completion is initiated by backspace

### ISSUE THREAD

**Issue by AmadeusW** [dotnet/roslyn#37231]
**Version Used**:  16.1.6, 16.3 preview 1
**Regression**:
This is a regression from 15.9.13

**Steps to Reproduce**:

1. Type AccessViolationException
2. Ensure completion is closed (you can do it using Ctrl+Space)
3. Hit backspace
4. Hit Ctrl+Space

![image](https://user-images.githubusercontent.com/1673956/61238712-153b1200-a6f2-11e9-985f-3468ede150ec.png)

**Expected Behavior**:
AccessViolationException is committed

This will be possible when Roslyn's `IAsyncCompletionItemManager.UpdateCompletionListAsync` sets the `UniqueItem` property

**Actual Behavior**:
AccessViolationException is not committed.

This happens because Roslyn's `IAsyncCompletionItemManager.UpdateCompletionListAsync` does not set the `UniqueItem` property, but it should

**Comment by ivanbasov** [comment]
Thank you, @AmadeusW ! The same happens with C#. Fix will be provided shortly.
