### ISSUE TITLE
Link highlight includes escape character

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37235]
Visual Studio automatically highlights URLs in C# string literals and make them clickable. It does however not handle escaped quotes correctly.

For example, the string &quot;The URL \\&quot;http://www.example.com/foo\\&quot; is an example.&quot; produces a clickable link that goes to http://www.example.com/foo\ . Note the forward slash on the end.
```
static void Main(string[] args)
{
      string t = "The URL \"http://www.example.com/foo\" is an example.";
}
```
The expected behavior is either that it doesn't include any part of the escape sequence (i.e. http://www.example.com/foo ), or that it includes the result of the escape sequence instead (i.e. [http://www.example.com/foo&quot;](http://www.example.com/foo&quot;) ). Including only the escape character (the forward slash) is clearly wrong.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/640043/link-highlight-includes-escape-character.html
VSTS ticketId: 944704_
_These are the original issue comments:_

Visual Studio Feedback System on 7/10/2019, 11:51 PM (4 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by vatsalyaagrawal** [comment]
Reproduces in 16.3.P1

**Comment by olegtk** [comment]
Route the bug to the editor please, @jinujoseph.

**Comment by jinujoseph** [comment]
VSFeedback routed to Editor
