### ISSUE TITLE
Expression bodied method whose expression is a switch expression is missing debug info

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#37261]
```C#
using System;
public class C
{
    static int M() => F() switch
    {
        1 => 1,
        C { P: int p, Q: C { P: int q } } => G(() => p + q),
        _ => 0
    };

    object P { get; set; }
    object Q { get; set; }
    static object F() => null;
    static int G(Func<int> f) => 0;
}
```

Produces no debug info for method `C.M` (specifically, no sequence points).

Analysis:

`ILBuilder.AllocateILMarker` creates 2 ILMarkers, both at BlockOffset = 0: one user-code sequence point and another hidden one.
`RealizeSequencePoints` uses the last defined sequence point for the offset (the hidden one).
`SequencePointList.GetSequencePoints` then emits no sequence points since the only sequence point in the list is hidden.

The issue is with the hidden sequence point emitted for the switch expression closure.

See `PDBTests.SwitchExpression_MethodBody`.

**Comment by gafter** [comment]
> See `PDBTests.SwitchExpression_MethodBody`.

@tmat Where could I find this method?

**Comment by tmat** [comment]
> See `PDBTests.SwitchExpression_MethodBody`.
> @tmat Where could I find this method?

https://github.com/dotnet/roslyn/pull/37262/files#diff-bc2cd65a9d0c06f4c097bb33a5a771c3R8908
