### ISSUE TITLE
Intellisense not listing "T" when starting to write a qualified return type

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#37268]
**Version Used**: 16.2 Preview 3

:link: Found while reviewing #37224

**Steps to Reproduce**:

1. Inside a C# class, type `System.Span<T>`

**Expected Behavior**:

`System.Span<T>`

**Actual Behavior**:

`System.Span<ThreadStaticAttribute>`

**Comment by diryboy** [comment]
I have a fix for both issues locally, will send PR later.
