### ISSUE TITLE
'Introduce using statement' on method call expression statements returning IDisposable

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#37260]
Right now 'Introduce using statement' only shows up for variable declarations:

```cs
var a = MethodThatReturnsDisposableThing(...);

var b = obj as IDisposable;
```

Would it be okay to expand the 'Introduce using statement' refactoring to show up for method calls that ignore the return type when the return type is disposable?

```cs
MethodThatReturnsDisposableThing(out var leasedObject);

foo.DoStuff();
```
After applying:
```cs
using (MethodThatReturnsDisposableThing(out var leasedObject))
{
    leasedObject.DoStuff();
}
```

I saw it happen today when I was with a newer developer, and my instinct was that the refactoring should show up and work. (Even though I knew it wouldn't since I wrote it.) I'm willing to submit a PR if this sounds like something you would accept.

**Comment by CyrusNajmabadi** [comment]
@jnm2 yup. we'd likely take a PR from you on this.
