### ISSUE TITLE
VS 2019 and VS 2019 Preview Class View not working for .Net Core projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37274]
In both the VS2019 RTM and 16.2 Previews, when I load a .Net Core project, the Class View is not loaded. This works fine in VS2017.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/627361/vs-2019-and-vs-2019-preview-class-view-not-working.html
VSTS ticketId: 939701_
_These are the original issue comments:_

Visual Studio Feedback System on 6/30/2019, 11:07 PM (15 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
