### ISSUE TITLE
What would be the best way to weave the IL of a production assembly to make it more testable but only within the unit test project

### ISSUE THREAD

**Issue by kasajian** [dotnet/roslyn#3727]
I am looking for a tool that does something like this:
 - Make class methods, fields and properties virtual so that they can be easily mocked from from unit test code.
 - Do it such that original production assembly is not modified.   But only the version of the production assembly that's placed in the Unit Test project modified.

There are several add-ins for Fody that will do this, but they all require you to modify the original production assembly.   They're trying to solve a different problem which is to automatically make all methods virtual of a given class without marking such classes as virtual.   That's great, but that's not what I need because for my scenario, I would have no problem with marking those methods virtual.

What I do need though not modify the production assembly at all that's within the production project.   But only modify the version of the assembly that gets placed into the unit test output folder as a referenced assembly.

Example: I have a production library called Foo.dll, and a unit test project FooTest.dll and the project that creates FooTest.dll references the project that produces Foo.dll.   Next, Visual Studio, as part of it's build process, copies Foo.dll into the bin output folder of FooTest.dll so that the referenced DLL is in the same folder when the test executes.

I want to ONLY modify the version of Foo.dll that gets copied into the FooTest project as part of the build step.   The original Foo.dll should remain the same.

I looked at Fody to do this, but they told me it won't do that.   In fact, they don't think it's a good idea, which leads me to think that's probably the wrong tool for this job.

I would like to be able to solve this problem because I think it would be really useful to have a general way of making production code testable *without* having to modify it.   I realize some people will think this is a bad idea, but I believe it will have its uses.

I'm curious if there's anything new in roslyn that will help me write such a tool.   I'm also considering using mono-cecil but I'm not sure if that's needed if I can assume I'm going to target roslyn+

Thank you.

**Comment by gafter** [comment]
Roslyn provides nothing to help with this.
