### ISSUE TITLE
GetRecommendedSymbolsAtPosition returns now 'value__' in Visual Basic

### ISSUE THREAD

**Issue by jbe2277** [dotnet/roslyn#3728]
The call Recommender.GetRecommendedSymbolsAtPosition returns now the symbol 'value__' if it provides the enum values (e.g. 'ConsoleColor.').

This symbol was not returned in RC2 but it comes know in RC3. And it comes only in Visual Basic - for C# the symbol is not returned.

*How to reproduce:*
* Download source of http://dotnetpad.codeplex.com/
* Run the app and create a new VB File
* Enter ConsoleColor. and see that auto-completion shows the value 'value__'

Note:
* Enter ConsoleColor. shows 'value__'
* Enter System.ConsoleColor. does not show 'value__'

**Comment by Pilchie** [comment]
Oops, we refiled this as #4136, and fixed it there.
