### ISSUE TITLE
Testrunner should show results monospaced

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#37288]
Here's what you get in VS:

![image](https://user-images.githubusercontent.com/4564579/61337011-6fb69a00-a7e8-11e9-9f09-60517a74040e.png)

This isn't helpful as the before/after don't align, and the ascii arrow position is useless.

In contrast, here is resharper:

![image](https://user-images.githubusercontent.com/4564579/61336977-4eee4480-a7e8-11e9-8211-273ad2e5c0d1.png)

Note how everything aligns and the monospacing makes it so that assertion library output is useful.

Given that these tests are expected to be run in consoles that are nearly universally monospaced, we should also do the same for VS.

**Comment by CyrusNajmabadi** [comment]
Tagging @kendrahavens @jinujoseph

**Comment by jinujoseph** [comment]
Routed to UT team [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/948147)

**Comment by jnm2** [comment]
FYI this is already done in the Visual Studio 16.2 previews:

![image](https://user-images.githubusercontent.com/8040367/61370896-7af9dc00-a861-11e9-8148-88f9ddf5e60a.png)
