### ISSUE TITLE
[loc][Query][Roslyn] Localizability of "ERR_DuplicateNullSuppression"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#37299]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Duplicate null suppression operator ('!')

File Name:
Compilers\CSharp\Portable\xlf\CSharpResources.xlf

==========================================
Query:
Is "Duplicate" a verb or an adjective here?

**Comment by jcouv** [comment]
"Duplicate" is an adjective in this context.
The user typed something like `x!!` with a duplicate `!` and we disallow that.

**Comment by PDostalek** [comment]
Thanks for the reply. I´ll provide the answer to the vendor.
