### ISSUE TITLE
Please publish Microsoft.VisualStudio.LanguageServices 3.1.0 to nuget

### ISSUE THREAD

**Issue by aka-STInG** [dotnet/roslyn#37296]
Please publish stable version Microsoft.VisualStudio.LanguageServices 3.1.0 to match Microsoft.CodeAnalysis.* packages.

**Comment by RikkiGibson** [comment]
@JoeRobich did we overlook this back when we published the stable packages for 16.1?

**Comment by RikkiGibson** [comment]
https://www.nuget.org/packages/Microsoft.VisualStudio.LanguageServices/3.1.0

This says that the package is unlisted. I am not aware of why this happened.

**Comment by JoeRobich** [comment]
@aka-STInG Sorry, I unlisted it due to the packaging issue here - https://github.com/dotnet/roslyn/issues/36056

The 3.2.0-beta4 package is likely to be the same build as the forthcoming 3.2.0 final. Can you use it in the mean time?

**Comment by aka-STInG** [comment]
@JoeRobich the thing is Microsoft.VisualStudio.LanguageServices tightly specifies dependency to Microsoft.CodeAnalysis.* (= not >=).
If you do not have policy to republish package, I would unlisted Microsoft.CodeAnalysis.* packages as well.
Now the case
MyLib -> Microsoft.CodeAnalysis 3.1.0
MyExtension -> MyLib
                     -> Microsoft.VisualStudio.LanguageServices 3.0.0
fails.
Thanks for the answer, I will rollback to 3.0.0.

**Comment by JoeRobich** [comment]
@aka-STInG I am publishing 3.2.1 packages now which removes the InteractiveHost dependency regression. The search should update shortly.
