### ISSUE TITLE
Outdated build instructions

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#3730]
In 13b4e9d434df3dd201a30594a6382d373b1eaf86, Roslyn.sln was moved one folder up. Because of this, the build instructions at https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging are no longer valid.

For example:

> From the command prompt, change directory to `<clone dir>` and run `Src\.nuget\nuget restore Src\Roslyn.sln`

Should be changed to:

> From the command prompt, change directory to `<clone dir>` and run `.nuget\nuget restore Roslyn.sln`

**Comment by davkean** [comment]
Sorry the delay, we've resolved this and updated the documentation. Thanks!
