### ISSUE TITLE
[NotNullIfNotNull] not propagating inference from result to parameters

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#37300]
**Version Used**: 
```
microsoft.net.compilers.toolset\3.3.0-ci.final
Microsoft (R) Visual C# Compiler version 3.3.0-ci (<developer build>)
```

**Steps to Reproduce**:
```C#
class Foo
{
    [return: NotNullIfNotNull("location")]
    public static T Read<T>(ref T location) where T : class? => location;

    public static T ThrowIfNull<T>(ref T? target) where T : class
    {
        if (Read(ref target) == null)
        {
            throw new Exception();
        }
        return target;
    }
}
```
Since the result of `Read` is not `null` if `location` is not null, then when we compare the result of `Read` against `null` and find that it isn't, we also know that the `target` argument to `Read` isn't null.  But the compiler doesn't appear to be inferring that here.

**Expected Behavior**:
No warning.

**Actual Behavior**:
```
error CS8603: Possible null reference return.
```

Is this by design, because `NotNullIfNotNull` only considers the input nullability of `location` and there's nothing here preventing `Read` from changing the `location` to be `null`?  If so, I tried adding `[NotNullIfNotNull("location")] ref T location`, to say that `Read` won't change a non-`null` `location` to be `null`, but it had no effect.

cc: @cston, @jcouv, @MadsTorgersen, @dotnet/nullablefc

**Comment by cston** [comment]
The compiler uses `[NotNullIfNotNull]` to infer that the return value is not null if the parameter value is known to be not null. However the compiler does not infer the parameter value is not null if the return value is otherwise learned to be not null.

The same issue occurs even if `T location` is a by-value parameter.

**Comment by stephentoub** [comment]
> In the example above, presumably Read<T>(ref T location) is free to return a non-null value always, even if location is null.

Hmm, that's true, it's not _iff_.

**Comment by stephentoub** [comment]
And we lack a `[NotNullWhen(null)]` attribute that could be applied to the parameter (though we would have if we'd generalized `[NotNullWhen(bool)]` to accept object instead as we'd discussed 😦 ).

Oh well.
