### ISSUE TITLE
Quick Info shouldn't show oblivious parameters with null default values as 'not null'

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#37314]
Version used: 3.3.0-beta1-19360-03

The IDE shows the null state of this variable as not-null, which seems wrong. This code is in a `#nullable disable` context.

<img width="212" alt="nullability-quick-info-2" src="https://user-images.githubusercontent.com/5833655/61412373-91258d80-a89d-11e9-9fd7-cd2467f398c2.PNG">

A few thoughts:
1. We could learn that this could be null by treating the default value as an assignment that might have occurred.
2. We could stop showing the inferred nullability for oblivious variables, but it seems like users will lose out in other scenarios if we do this.
3. We could decide that although this specific scenario looks weird, we're okay with the current behavior in the `#nullable disable` context and just move on.

/cc @jasonmalinowski @333fred

**Comment by CyrusNajmabadi** [comment]
I hate '3' fwiw.

**Comment by CyrusNajmabadi** [comment]
> We could stop showing the inferred nullability for oblivious variables, but it seems like users will lose out in other scenarios if we do this.

What "other scenarios" with the user "lose out in" if you do this

**Comment by RikkiGibson** [comment]
Basically, we handle oblivious variables by giving them an initially not-null flow state, and we can give you potentially helpful information about the flow state in Quick Info even though you haven't opted into `#nullable enable`.

```cs
void M(object opt)
{
    if (someCondition)
        opt = null;

    // Quick Info will say "'opt' may be null here.", but there won't be a compile warning
    _ = opt.ToString();
}
```

**Comment by jasonmalinowski** [comment]
To me this is a compiler API misdesign and the nullable flow state there should be NotApplicable; that the compiler implicitly sticks in a NotNull to avoid the compiler warnings feels like a leaky abstraction.

**Comment by CyrusNajmabadi** [comment]
> Basically, we handle oblivious variables by giving them an initially not-null flow state, and we can give you potentially helpful information about the flow state in Quick Info even though you haven't opted into #nullable enable.

I don't like that.  That's just confusing to me TBH.  If i'm not using NRT why is anything lighting up as if i were...?

**Comment by jasonmalinowski** [comment]
> If i'm not using NRT why is anything lighting up as if i were...?

Even if you're not using NRT, it's possible for the compiler to be helpful, consider:

```
string s;
if (DateTime.Now.DayOfWeek == DayOfWeek.Tuesday)
{
    s = "Tacos";
}
else
{
    s = "Not Tacos";
}

if (s == null)
{
    throw new Exception();
}
```

The compiler can now realize that exception isn't going to run, even if you don't have any code annotated anywhere.

**Comment by jasonmalinowski** [comment]
We went back and forth on whether offering that was useful though; fundamentally the IDE is just reporting whatever the compiler chooses to report. Now what might be throwing this off too is @RikkiGibson might be in the feature flag experiment which was to run the nullable analyzer no matter what so we could find crashing bugs or perf problems. Possibly not in that flight it won't do this?

**Comment by CyrusNajmabadi** [comment]
> The compiler can now realize that exception isn't going to run

But if i didn't even enable the feature... why si the compiler changing behavior at all?  like, will i now get warnings?  won't that break code?

**Comment by jasonmalinowski** [comment]
Well, you can enable nullable _warnings_ independently of actually annotating things.

**Comment by CyrusNajmabadi** [comment]
Sure, if i have `#nullable warning enable`, then i'd be ok with a warning here.  But absent that...

1. getting anything nullable related seems *super sketchy* to me.
2. having the compiler say "this is not null" when it definitely is null makes me think the feature is just broken.

**Comment by CyrusNajmabadi** [comment]
if you guys are going to run the nullable analysis on code, even when the feature is disabled, then the analysis should at least be accurate.  optional parameters are totally normal, and having the compiler anlayze it and say "it won't be null" just seems utterly and completely broken.

**Comment by jasonmalinowski** [comment]
We've confirmed that @RikkiGibson was a good compiler team dogfooder and set the bit that forces analysis to catch bugs earlier; this might not be what happens on anybody else's machine.

**Comment by 333fred** [comment]
You'll run into this in any project that has started opting into the feature in _any_ file in the project.

**Comment by RikkiGibson** [comment]
Do we have an expectation about whether Quick Info will show nullability in projects that don't have `#nullable enable`/`<Nullable>enable</Nullable>` anywhere?

This particular scenario is "fixed" by just doing option '1', but it seems like there are some common scenarios where just claiming that an oblivious variable is initially not-null is going to cause confusion instead of helping the user. Perhaps we should just not show the flow state in Quick Info within a `#nullable disable` context (i.e. option '2')

**Comment by jasonmalinowski** [comment]
We had discussed offering the help when the compiler could do it "anyways" but I believe that was cut for now, right @333fred?

**Comment by 333fred** [comment]
After discussion with @cston, I think the appropriate solution here is to standardize value types on a `NullableAnnotation.NotApplicable` and `NullableFlowState.NotApplicable`. You cannot have null value types that aren't Nullable<T>.

**Comment by RikkiGibson** [comment]
This issue doesn't discuss value types, were you thinking of #37157?

**Comment by 333fred** [comment]
Whoops, yes I was, thanks @RikkiGibson.

**Comment by jasonmalinowski** [comment]
@333fred so what are we doing here then now that we're not confusing the bugs?

**Comment by 333fred** [comment]
@jasonmalinowski we need to stop displaying flow state in disabled contexts.
