### ISSUE TITLE
Special case `Debug.Assert` in NullableWalker analysis

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#37328]
FYI @cston @stephentoub @safern @agocke 

Relates to https://github.com/dotnet/corefx/pull/39557

**Comment by safern** [comment]
Is `Debug.Assert` the only method we should special case? Should we also special case `string.IsNullOrEmpty` as it also interacts directly with data flow analysis.

**Comment by jcouv** [comment]
Would these be the only two methods? :-S
Is there an alternative to get the required methods properly annotated instead?

**Comment by safern** [comment]
> Would these be the only two methods?

It seems like the special cased methods which were really helpful when we annotated coreclr and we had no support of custom attributes, were:

```cs
// Annotations Specialized
System.Boolean System.Boolean.Parse(System.String)
System.Void System.Buffer.BlockCopy(System.Array, System.Int32, System.Array, System.Int32, System.Int32)
System.Int32 System.Buffer.ByteLength(System.Array)
System.Byte System.Buffer.GetByte(System.Array, System.Int32)
System.Void System.Buffer.SetByte(System.Array, System.Int32, System.Byte)
System.Byte System.Byte.Parse(System.String)
System.Byte System.Byte.Parse(System.String, System.IFormatProvider)
System.Byte System.Byte.Parse(System.String, System.Globalization.NumberStyles)
System.Byte System.Byte.Parse(System.String, System.Globalization.NumberStyles, System.IFormatProvider)
System.String System.String.Concat(System.String, System.String)

// Attribute Specialized
System.Boolean System.String.IsNullOrEmpty(System.String)
System.Boolean System.String.IsNullOrWhiteSpace(System.String)
System.Boolean System.String.Contains(System.String)
System.Void System.Diagnostics.Debug.Assert(System.Boolean)
System.Void System.Diagnostics.Debug.Assert(System.Boolean, System.String)
System.Void System.Diagnostics.Debug.Assert(System.Boolean, System.String, System.String)
System.Void System.Diagnostics.Debug.Assert(System.Boolean, System.String, System.String, System.Object[])
```

Based on: https://github.com/dotnet/roslyn/pull/34916/files#diff-d02e2d6d70e84697ca87520824236d04L22

We would need to annotate them directly in .netstandard2.1 and service .netstandard2.0 with the same annotations. (Plus including the needed custom attributes as part of the .netstandard2.0/2.1 API surface).

cc: @terrajobst

**Comment by jcouv** [comment]
Solved by adding a handful of annotations to netstandard: https://github.com/dotnet/standard/pull/1356
Closing
