### ISSUE TITLE
ConvertToInterpolatedString should interpolate chars as strings

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#37324]
**Version Used**: VS 16.1.3

**Steps to Reproduce**:

![interpolatedString](https://user-images.githubusercontent.com/29174528/61446005-5f1c3600-a946-11e9-9546-1b08450c49c0.gif)

```csharp
var hello = "hello";
var world = "world";
var str = hello + ' ' + world; 
```
use the convert to interpolated string refactoring

**Expected Behavior**:
var str = $"{hello} {world}";

**Actual Behavior**:
var str = $"{hello}{' '}{world}";

**Comment by JoeRobich** [comment]
Thanks Yair!
