### ISSUE TITLE
Edit - GoTo All: Focus is lost when file is auto-opened

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37335]
When hitting Ctrl-, or Ctrl-T and typing something, after a short delay the first search result location is opened in a (new) window. this steals the focus away from the GoToAll window, thus making it impossible to continue typing (or just type slowly) and select from the search result using the arrow keys.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/647887/edit-goto-all-focus-is-lost-when-file-is-auto-open.html
VSTS ticketId: 947772_
_These are the original issue comments:_

Visual Studio Feedback System on 7/17/2019, 01:17 AM (34 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
:memo: I hit this today in either 16.2 Preview 3 or 16.2 Preview 4.

**Comment by ryzngard** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/43586
