### ISSUE TITLE
Auto-generation of control events is not placing code correctly....

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37339]
Visual Studio 2019, editing Visual Basic.Net code.
While working on a windows form with a single button control on the form. double-Clicking the button in design mode causes the &quot;Click&quot; event code to be autogenerated, presumably placed at the end of the form's Class (just before the &quot;End Class&quot; statement.

This usually works. However, if your class contains a #Region/#EndRegion at the end of the Class, AND that #Region contains a sub method, the auto-generated event code Opens the last region and inserts the event code between the EndSub and #End Regiion statements. The auto-generated code SHOULD be inserted just before the End Class statement by default, and not open any existing #Regions.

Please see my attachments for example code.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/589218/auto-generation-of-control-events-is-not-placing-c.html
VSTS ticketId: 902148_
_These are the original issue comments:_

Visual Studio Feedback System on 5/30/2019, 07:27 PM (48 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.

**Comment by ScottyBlazor** [comment]
This happens for me all the time, now on VS 2022 17.5.1 but has always been an issue. 
it should be as easy to reproduce as adding a region with some code in it just before the end class, collapsed the region. 
then use the code window drop down boxes at the top of the screen to add an events code for a control or class, 
it always goes in to the collapsed region (which does expand at that point). so you have to copy the new code and move it out.
I often use a hacky workaround when starting a new code file that will have a lot of events, where I add a new method down the bottom and call it NewMethodsBelowHere() just to stop it constantly expanding my last region and adding the code there.

I think kendrahavens post need consideration still, I posted the same request that was closed, here https://developercommunity.visualstudio.com/t/option-to-add-new-code-methods-at-cursor/553179

I have nicely structured code using regions for functionality, every time I add some new events to the code they go to the bottom and I'm constantly coping them and putting them back up to the location I was already at to keep the functionality nicely grouped.
