### ISSUE TITLE
Lambda type inference Error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37338]
1. I introduced the MORELINQ package, where a type inference error occurs when using the ToDataTable provided by this package.
```
Class Person
       {
Some property.

}
Var lis = new List<Person> (); List.
Todatatable (item=>item.?????);
``` 

The display type is person when the mouse moves to the list in VS, but the properties of the prompt are not properties on this type at all.

But the problem will not recur in vs2015. 2. After the new project is completed (. NET core console), NuGet introduces the package and will find that there is no hint of the package, and no reference error will occur after manual using.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/591568/lambda类型推断错误.html
VSTS ticketId: 904077_
_These are the original issue comments:_

Visual Studio Feedback System on 6/3/2019, 02:13 AM (45 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
