### ISSUE TITLE
Incorrect nullability analysis for single and-operator 

### ISSUE THREAD

**Issue by mharthoorn** [dotnet/roslyn#37344]
**Version Used**: 
Visual Studio 16.2.0 Preview 4

**Steps to Reproduce**:
The following if statement with a single **and**-operator (&), gets analysed as both values being possibly null. That is incorrect.

```csharp
    var monkey = CreatePossibleNullMonkey();
    var business = CreatePossibleNullBusiness();
    if (monkey != null & business != null)
    {
        monkey.Do(); // Dereference of a possibly null reference
        business.AsUsual(); // Dereference of a possibly null reference
    }
```

**Note** 
With a shortcut-and-operator (double &&), the analysis _does_ evaluate both as not null, which is correct.
```csharp
    if (monkey != null && business != null)
    {
        monkey.Do(); // No warning
        business.AsUsual(); // No warning
    }
```

**Inverse**
The inverse has the same problem. Here too, the double **or** ``||`` correctly evaluates both variables as not null which is correct, While the single-or evaluates them as possibly null. Wich is incorrect.

```csharp
    if (!(monkey is null | business is null))
    {
        monkey.Do(); // Dereference of a possibly null reference
        business.AsUsual(); // Dereference of a possibly null reference
    }
```

**Comment by jasonmalinowski** [comment]
This is a compiler issue not IDE.

**Comment by jaredpar** [comment]
The compiler is behaving as designed at the moment. Logical operators are considered in the flow analysis but not binary operators. This is definitely an area we could expand the feature out to in the future though if we see enough uses of this pattern.

**Comment by jnm2** [comment]
I just hit this with `if (left is null | right is null) return false;` which is something I think Jon Hanna convinced me to do rather than `||` because it performed better.

@Suchiman also ran into this with `(left is null) ^ (right is null)` and `(left is null) != (right is null)`.

**Comment by jcouv** [comment]
Registering one more report of this request (https://github.com/dotnet/roslyn/issues/59812).
