### ISSUE TITLE
Generalize InternalImplementationOnlyAttribute Usage

### ISSUE THREAD

**Issue by JasonBock** [dotnet/roslyn#37342]
**Version Used**: 
.NET Core 3.0 preview 6

This isn't a bug per-se. I just noticed recently that I can't create a class that inherits from `ISymbol`. After digging around a bit, I finally realized that the interface (`IOperation` has this as well) has the `InternalImplementationOnlyAttribute` on it. Apparently, this lets Roslyn define public interfaces that can't be part of a class's inheritance hierarchy if it's not within its assembly.

Since `InternalImplementationOnlyAttribute` is `internal`, .NET developers can't use this attribute. But the compiler already knows to create an error (RS1009 is the code) if an interface has it. I've had cases myself where I wanted a public interface that could not be a base type unless it was within the assembly. If `InternalImplementationOnlyAttribute` was made `public`, would it be possible to make this a feature for general consumption by any .NET developer?

**Comment by agocke** [comment]
With default interface implementations, you don't even need a new feature:

```C#
public interface I1
{
    internal void InternalImplementationOnly();
}
```

**Comment by JasonBock** [comment]
@agocke but your answer is different than what `ISymbol` is doing. It's a public interface with public members, and it's done this way so clients can use the types derived from `ISymbol` and its members. While you're right that DIM allows interface members to be `internal`, a client outside of the assembly that `I1` is defined couldn't "see" that internal method.

**Comment by agocke** [comment]
Right, that method is just a dummy method to prevent people from implementing outside your assembly. You should make all your interface members public, but to implement the interface they would have to implement everything, including that internal member, which they can't.

**Comment by JasonBock** [comment]
OK, that makes sense, and it's a neat "trick". But it also forces implementors to have one outlier member that they have to implement, and it has to be known that it's just a dummy member that has no meaning other than preventing clients outside the assembly from implementing it. The `[InternalImplementationOnly]` approach seems much cleaner. But this has already been closed, so there's that :).

**Comment by agocke** [comment]
Oh, that's just because this isn't actually a compiler feature. It's an analyzer we ship with the CodeAnalysis APIs. You could ship one yourself if you want.

**Comment by JasonBock** [comment]
Yeah, I figured with the Code value starting with "RS" that it wasn't a compiler feature, but I wasn't sure. And I could ship my own, but if it was something that was kind of "done"-ish, it would be easier to make it available to everyone.

**Comment by agocke** [comment]
Since it's just for our SDK it's not really "public feature"-level quality.
