### ISSUE TITLE
Localization for "Download the .NET Compiler Platform SDK" template project

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#3734]
See attached snapshots, the messages, name of the template project and the index.html contents all seem to be non-localized in a localized VS drop.

![loc_new_project_dialog](https://cloud.githubusercontent.com/assets/10605811/8416519/2acdd216-1e5b-11e5-831b-b1c94e313f30.png)
![loc_download_roslyn_sdk](https://cloud.githubusercontent.com/assets/10605811/8416518/2acbd8a8-1e5b-11e5-8cee-b9f770b7114f.png)
![loc_analyzer_with_codefix_project](https://cloud.githubusercontent.com/assets/10605811/8416579/9197225e-1e5b-11e5-81d1-9797aa582715.png)

**Comment by mavasani** [comment]
Additionally, the `ReadMe.txt` created for the Analyzer with fix project is also non-localized. Should the contents of this file also be localized?

**Comment by mavasani** [comment]
One more observation: the comments added to the default analyzer + fix project are also in ENU. Probably they should be localized too?

**Comment by jmarolf** [comment]
After talking to @jinujoseph I am moving this to 1.3 and hope to get the authoring in immediately after 1.2 ships

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #39](https://github.com/dotnet/roslyn-sdk/issues/39) via [**ZenHub**](https://www.zenhub.com/)
