### ISSUE TITLE
Temp allocations in SympolDisplay.ToDisplayString

### ISSUE THREAD

**Issue by feng-yuan** [dotnet/roslyn#37345]
There are lots of temp allocations in SymbolDisplay.ToDisplayString. Specifically, there are three issues:

1) ToDisplayParts allocates an ImmutableArray<SymbolDisplayPart> which is only used once.
2) To generate this array, ArrayBuilder<T> is used.. But builder with larger arrays are rejected on returning, causing more allocations later.
3) When generating string from the array, StringBuilder.Append(object) is used, causing boxing of SymbolDisplayPart, which is a struct.

Suggestions:
1) Directly read the ArrayBuilder as IReadOnlyList, no need for array allocation.
2) Change comparison on returning from < 128, to <=128, accepting 128 element array.
3) Change to call StringBuilder.Append(SymbolDisplayPart.ToString()), avoid boxing.

**Comment by feng-yuan** [comment]
Here are the temp allocations needed for a symbol with 96 parts:
1) Grow array inside builder to 64 elements, 1560 bytes
2) Grow array inside builder to 128 elements, 3096 bytes
3) Allocate 96 element array, 2328 bytes
4) Boxing 96 SymbolDisplayPart, 40 * 96 = 3840 bytes.

Total temp allocation for a single symbol: 10,824 bytes.

**Comment by heejaechang** [comment]
I dont believe ToDisplayString is designed to be called a lot of times. what is the scenario that made this allocations matter?

**Comment by feng-yuan** [comment]
microsoft.codeanalysis!AttributeData.IsTargetEarlyAttribute calls ToDisplayString, also microsoft.codeanalysis.csharp!ExplicitInterfaceHelpers.GetMemberName.

ToDisplayString is also called by Symbol.ToString, so could be called by lots of code.

What I'm suggesting are very simple changes, especially:
1) Change < 128 to <= 128. Allow [65..127] is in ArrayBuilder is useless, but 128 is very useful.
2) Change StringBuilder.Append(SymbolDisplayPart) to StringBuilder.Append(SymbolDisplayPart.ToString()).

**Comment by 333fred** [comment]
@feng-yuan do you have an ETL trace you can share? There are a couple of places in the compiler that will call ToDisplayString, but I wouldn't expect any of them to generate a 96-part symbol string. If that level of string realization is coming from the compiler itself, we'd prefer to fix the actual cause of that allocation, rather than making the ToDisplayString path allocate less. I think we can probably take at least suggestion 3 without question, but for 2 we'd want to test profiling in other scenarios to ensure that we're not hanging onto large pools that are only used once or twice.

**Comment by feng-yuan** [comment]
Here 333fred, here is a symbol with 96 parts: Microsoft.Exchange.Data.Directory.ConfigurationXMLHelper.ConfigXmlProperty<T, ValueT>(string, Microsoft.Exchange.Data.ExchangeObjectVersion, Microsoft.Exchange.Data.Directory.ADPropertyDefinition, ValueT, System.Func<T, ValueT>, System.Action<T, ValueT>, Microsoft.Exchange.Data.Directory.MServPropertyDefinition, Microsoft.Exchange.Data.MbxPropertyDefinition, Microsoft.Exchange.Data.Directory.ADPropertyDefinitionFlags)

**Comment by feng-yuan** [comment]
There is another option: you do not need to change upper limit, just growth ratio. Change to old size * 5 / 4, then growth sequence would be 4,5,6,7,8,10,12,15,18,22,27,33,42,52,65,81,101,126. So array of 126 elements would be kept.

**Comment by 333fred** [comment]
I understand that you have a symbol like that, I want to understand the compiler code paths that actually attempt to realize this as a string. The codepath that does this in csc.exe without actually printing a message to the user has a bug in itself, and if that's in the compiler we want to fix it directly.

**Comment by CyrusNajmabadi** [comment]
I think that growth ratio would be less desirable right?  because you'd grow... then very quickly hit the next limit.  right?  or am i misunderstanding the suggestion?

**Comment by agocke** [comment]
@feng-yuan What @333fred is saying is that outside of displaying strings to users, there isn't really a good reason for us to be using SymbolDisplay at all, internally. We try to avoid materializing strings when reasonable, and if this is significant enough to show up in a trace, it's probably significant enough to remove the usage of SymbolDisplay entirely.

We could audit every use of SymbolDisplay, but if you had a trace with the code path, that would make it significantly easier to target the offending code path.

**Comment by feng-yuan** [comment]
You guys are building more than a compiler, people are building lots of analyzers based on your API. So building, and testing is getting slower and slower. I'm interesting in making thousands, if not millions of engineers, more efficient. At least the boxing issue should be considered a simple bug fix.

**Comment by 333fred** [comment]
@feng-yuan we're not saying we don't want to take perf fixes, we certainly do. In your original email chain, you indicated these allocations were analyzed from a trace of a `csc.exe` process. The only thing going on in that process should be mainline compilation, and potentially analyzers that are run as part of that compilation process. Forget the boxing allocations that you're seeing as part of realizing a string, _nothing_ in mainline compilation should be realizing this string at all, and we can potentially get bigger wins by figuring out what is causing this string to be created in the first place. No analyzer or compiler should be creating this string unless they're reporting some kind of warning/error. Certainly we can avoid a few boxing allocations here, but we're thinking that those allocations themselves are a symptom of a likely bigger problem. If you can provide us with an ETL trace of this problem scenario, or instructions on how to re-create this scenario, it would be very helpful in determining this.

**Comment by agocke** [comment]
@feng-yuan As you said, we're interested in making millions of engineers more efficient. That means if we can stop materializing these strings *at all* that would be even better. We make take the analyzer improvements as well, but that's orthogonal.

**Comment by CyrusNajmabadi** [comment]
Note: IDE does use SymbolDisplay a fair amount.  So i'm generally pretty positive about taking perf fixes here.  I think that would be complimentary with any compiler fixes made to just use SymbolDisplay less :)

**Comment by feng-yuan** [comment]
Here is an easy way to get traces: open APV, load "Global Function Inclusive", search for "ToDisplayString".

**Comment by CyrusNajmabadi** [comment]
What is APV?

**Comment by 333fred** [comment]
Azure Profile Viewer, Feng sent us an email offline with instructions.

**Comment by CyrusNajmabadi** [comment]
@333fred does this still apply?  or can we close out?
