### ISSUE TITLE
Errors in code while typing cause all regions to open.....

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37340]
While using Visual Studio 2019 and editing Visual Basic.Net code.....
If you have used #Region/#End Region in your code, then you edit a string prior to those regions, during the editing of the string ALL regions afterwards will open unecessarily. For example:

code
more code
more code
dim a as string=&quot;hello&quot;
more code

#Stuff         &lt;-----First closed region
#MoreStuff   &lt;--------second closed region
#EvenMore Stuff  &lt;-------------third closed region

If you go back and delete the last doublequote on the declaration of the string a=&quot;hello&quot;, the editor will, after a second or two, open every following region in your document. This should not happen.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/589216/errors-in-code-while-typing-cause-all-regions-to-o.html
VSTS ticketId: 902145_
_These are the original issue comments:_

Visual Studio Feedback System on 5/30/2019, 07:26 PM (48 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closingg out as we are unlikely to change these VB experiences.
