### ISSUE TITLE
immediate window is case sensitive for VB

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37350]
In Immediate Windows while debugging a VB program I type &quot;vb&quot; instead of &quot;VB&quot; as shown below where VB is defines as
```vb
Imports VB = Microsoft.CodeAnalysis.VisualBasic
```

In the firsrt case I get and error and in the second it works. Visual Basic is not case sensitive

?ctype(VB_Modifier.LeadingTrivia(0).rawkind,**vb**.SyntaxKind).ToString
error BC30002: Type 'vb.SyntaxKind' is not defined.
?ctype(VB_Modifier.LeadingTrivia(0).rawkind,**VB**.SyntaxKind).ToString
&quot;WhitespaceTrivia&quot;

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/523669/immediate-window-is-case-sensitive-for-vb.html
VSTS ticketId: 843194_
_These are the original issue comments:_

Visual Studio Feedback System on 4/8/2019, 08:19 PM (100 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
