### ISSUE TITLE
The Suggested Name should recognize [ReadOnly]Span/Memory

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#37366]
**Version Used**: 
16.2.0 Preview 4.0

**Steps to Reproduce**:
Create a function parameter of `Span<Value>`.

**Expected Behavior**:
As with `Value[]`, the suggested name should be `values`.

**Actual Behavior**:
The suggested name ist just `span`

![span-suggested-name](https://user-images.githubusercontent.com/1947968/61523256-467a5180-aa14-11e9-8848-35bb71285675.gif)

**Comment by Youssef1313** [comment]
In case this might help a contributor, I think the related part of code:

https://github.com/dotnet/roslyn/blob/9f82a08241f46854e2a1ccb0c3f40195a2c7a70b/src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs#L174

**Comment by Youssef1313** [comment]
> In case this might help a contributor, I think the related part of code:
> 
> https://github.com/dotnet/roslyn/blob/9f82a08241f46854e2a1ccb0c3f40195a2c7a70b/src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs#L174
> 
> Another `if` condition to handle Span/Memory types will be needed.

Or better, handle it here:

https://github.com/dotnet/roslyn/blob/9f82a08241f46854e2a1ccb0c3f40195a2c7a70b/src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs#L186

**Comment by Youssef1313** [comment]
> In case this might help a contributor, I think the related part of code:
> 
> https://github.com/dotnet/roslyn/blob/9f82a08241f46854e2a1ccb0c3f40195a2c7a70b/src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs#L174
> 
> Another `if` condition to handle Span/Memory types will be needed.

Currently, immutable collections are handled correctly, I couldn't figure out where they're handled. There might be a better approach than what I suggested.

**Comment by Youssef1313** [comment]
Instead of hard-coding special runtime types e.g. Span, ReadOnlySpan, etc., I'd suggest we check for types containing GetEnumerator method.
