### ISSUE TITLE
VS crashes when opening roslyn.sln on VS master.

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#37385]
With stack stace-
```
System.ExecutionEngineException
  HResult=0x80131506
  Message=Exception of type 'System.ExecutionEngineException' was thrown.

 

Inner Exception 1:
AggregateException: One or more errors occurred.

 

Inner Exception 2:
AggregateException: One or more errors occurred.

 

Inner Exception 3:
AggregateException: One or more errors occurred.

 

Inner Exception 4:
AggregateException: One or more errors occurred.

 

Inner Exception 5:
FileFormatException: File contains non-text characters

 

"   at Microsoft.VisualStudio.Text.Implementation.TextImageLoader.ParseBlock(Char[] buffer, Int32 length, NewlineState& newlineState, Int32& currentLineLength, Int32& longestLineLength)\r\n   
at Microsoft.VisualStudio.Text.Implementation.TextImageLoader.Load(TextReader reader, Int64 fileSize, NewlineState& newlineState, Int32& longestLineLength, Int32 blockSize, Int32 minCompressedBlockSize)\r\n   
at Microsoft.VisualStudio.Text.Implementation.BufferFactoryService.CreateTextBuffer(TextReader reader, IContentType contentType, Int64 length, String traceId)\r\n   
at Microsoft.VisualStudio.Text.Implementation.BufferFactoryService.CreateTextBuffer(TextReader reader, IContentType contentType)\r\n   
at Microsoft.CodeAnalysis.Editor.Implementation.Workspaces.EditorTextFactoryService.CreateTextInternal(Stream stream, Encoding encoding, CancellationToken cancellationToken)\r\n   
at Microsoft.CodeAnalysis.Editor.Implementation.Workspaces.EditorTextFactoryService.CreateText(Stream stream, Encoding defaultEncoding, CancellationToken cancellationToken)\r\n   
at Microsoft.CodeAnalysis.FileTextLoader.CreateText(Stream stream, Workspace workspace)\r\n
at Microsoft.CodeAnalysis.FileTextLoader.<LoadTextAndVersionAsync>d__8.MoveNext()\r\n
--- End of stack trace from previous location where exception was thrown ---
\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   
at Microsoft.CodeAnalysis.TextDocumentState.<LoadTextAsync>d__29.MoveNext()"
```

There appear to be binary characters in some roslyn files.  Loading these will throw a FileFormatException in the latest versions of VS.

This issue is to track down why these files exist.

**Comment by dibarbet** [comment]
https://github.com/dotnet/roslyn/blame/master/src/Compilers/CSharp/Test/Syntax/Parsing/ParserRegressionTests.cs#L112

contains a binary character (\v) after a in 'a  ='
var test = @"int?[] ///  a �  = new int? 

Is this there on purpose?  Should it be there?  Can we remove it?
cc @dotnet/roslyn-compiler @jcouv 
cc @dpugh

The editor made a change to throw an exception on binary characters in VS master.  If this is there by mistake we can probably remove it, but if it is there on purpose we might need to re-think a bit.

**Comment by dpugh** [comment]
Note also that VS -- unlike the code snippet below -- doesn't do anything to display a \v (it just looks like a space).


  1.
Is C# is supposed to treat \v like a space, then we should probably change the editor to accept it (this is a trivial change).
  2.
If we accept the character should the editor be doing anything to display odd characters like it (and other non-printable characters) or continue to let them silently lurk?
  3.
It probably makes sense to modify the C# code below to make the character explicit (e.g. test = @"int?[] /// a " + '\v' + @" ....) since I doubt anyone knew there was something other than a space there.


________________________________

**Comment by davidwengier** [comment]
Looks like the same stack I got opening CPS in #37363 

I will see if I can find a \v in that file.

**Comment by gafter** [comment]
There is nothing wrong with "binary" data in a string.  See https://github.com/dotnet/csharplang/blob/master/spec/lexical-structure.md#string-literals

There is nothing wrong with "binary" data in a comment.  See https://github.com/dotnet/csharplang/blob/master/spec/lexical-structure.md#comments

**Comment by sharwell** [comment]
Based on the comment from @gafter, it appears that the core editor is at fault here and Roslyn is behaving as expected.

**Comment by sharwell** [comment]
Duplicate of #37363

**Comment by dpugh** [comment]
How should we fix this on the editor side? Restoring the old behavior is trivial but I’m not sure the experience of having otherwise invisible binary characters in strings or comments is the best user experience.


  1.  Should the editor be doing anything to make sure invisible binary characters are rendered as something?
  2.  Should the editor be doing anything to reject “binary” files (e.g. opening a .dll as a text file) automatically or should we leave it entirely up to the user to react appropriately?

**Comment by CyrusNajmabadi** [comment]
>   1.  Should the editor be doing anything to make sure invisible binary characters are rendered as something?

This seems reasonable.  It's not uncommon to see many editors/tools just show this as something like: �

**Comment by tmat** [comment]
Notepad2:
![image](https://user-images.githubusercontent.com/41759/61739357-1e0a9400-ad41-11e9-9742-a7da627def78.png)

**Comment by sharwell** [comment]
> Should the editor be doing anything to make sure invisible binary characters are rendered as something?

It could, but it doesn't seem absolutely necessary.

> Should the editor be doing anything to reject “binary” files (e.g. opening a .dll as a text file) automatically or should we leave it entirely up to the user to react appropriately?

The editor should not be making assumptions about what individual languages consider to be valid content of text files. The language service is responsible for reporting invalid character sequences via the parser and error list integration.

**Comment by jinujoseph** [comment]
Keeping this one open as it has more information than 37363

**Comment by jinujoseph** [comment]
Tracked at [EditorSide](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/951481)

**Comment by jcouv** [comment]
Should we temporarily remove the test causing problem while this is getting fixed in editor? We can revert once fixed.

**Comment by sharwell** [comment]
@jcouv It shouldn't be necessary. The regression doesn't appear in any public builds.

**Comment by dibarbet** [comment]
Resolved by the editor.  Also verified that the latest int preview is working.
