### ISSUE TITLE
IDE0019 'use pattern matching' duplicates preprocessor

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#37398]
**Version Used**: 
Visual Studio 16.1.6

**Steps to Reproduce**:
```csharp
        public static void M(object o)
        {

#if DEBUG
            Console.WriteLine("in debug");
#endif

            string s = o as string;
            if (s != null)
            {

            }
        }
```
**Expected Behavior**:
Code fix to:
```csharp
        public static void M(object o)
        {

#if DEBUG
            Console.WriteLine("in debug");
#endif

            if (o is string s)
            {

            }
        }
```
**Actual Behavior**:
![image](https://user-images.githubusercontent.com/5644458/61632657-f4f5ef00-acbf-11e9-8d86-6ca98f91d138.png)

**Comment by xtqqczze** [comment]
Confirmed:
https://github.com/PowerShell/PowerShell/blob/d67cd7c80042f6614f062763a8897c1fe92ecf7e/src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Complex.cs#L244

**Comment by mrlacey** [comment]
Another example:

![image](https://user-images.githubusercontent.com/189547/112990970-8ccb0200-915e-11eb-8496-ac8948c0ec1a.png)
