### ISSUE TITLE
DeclarationNameCompletionProvider should suggest names for nullable types

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/roslyn#37392]
**Version Used**: 
16.2 P4

**Steps to Reproduce**:

```csharp
public class Class1
{
  public void Method()
  {
    TestStruct? $$
  }
}

public struct TestStruct { }
```

**Expected Behavior**:
For this code variable name should be suggested, e.g. 'testStruct'.

**Actual Behavior**:
No suggestions.

Problem is that `TestStruct?` is considered as ConditionalExpression, not as VariableDeclaration (see [here](https://sharplab.io/#v2:C4LghgzsA0AmIGoA+ABAzAAhQJgwYQBtIIBGAWACgBvSjLTFAFgwFkBTYACwHtYAKAJS0MNCnToAVNlADKwAE4BXAMbAA/BmEBfSjoqV0GKEtUYpshSuAiMWoA==)).
It only becomes VariableDeclaration after variable name is added, which is too late for DeclarationNameCompletionProvider.

Added couple of failing tests for this issue, you can find them [here](https://github.com/Dreamescaper/roslyn/commit/248107d000477431ef5efb7a4070426e11ba8f48).
(Originally planned to fix the issue myself, but I'm not familiar with parsing functionality)

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Any recollection if we already have helpers that do the parse tree reinterpretation that's at issue here? I'm assuming "no" but these sorts of special helpers are tremendously hard to find if you don't know where they already are.

**Comment by CyrusNajmabadi** [comment]
I believe hte answer is "no".  This will just need to be special cased.

**Comment by CyrusNajmabadi** [comment]
This does work here:

![image](https://user-images.githubusercontent.com/4564579/152653105-7caf044f-9b88-40f4-a92f-5858983353d3.png)
