### ISSUE TITLE
Can't view all fields in constructor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37406]
I have a constructor that takes 50 parameters. When creating a &quot;new&quot; object in vb.net, intellisense is only showing approximately 38 parameters and once I get to the 39th or so parameter, it no longer shows a suggestion (it will still show the list, but won't show any more suggestions).

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/574987/cant-view-all-fields-in-constructor.html
VSTS ticketId: 896040_
_These are the original issue comments:_

Visual Studio Feedback System on 5/20/2019, 08:19 PM (62 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

![image](https://user-images.githubusercontent.com/7817401/61656268-47f68480-ac75-11e9-9bbf-5ae4b6fc1eed.png)

**Comment by CyrusNajmabadi** [comment]
We're not likely to change anything here.  recommendation would be to switch this to a record.
