### ISSUE TITLE
Consider adjusting breakpoint spans for await foreach and using declarations

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#37402]
A breakpoint span that corresponds to an initial sequence point of an `await foreach` statement and `await using` and `using` declarations does not currently cover `await` or `using` keywords. When a breakpoint is attempted to be placed on one of these keywords in the IDE it gets placed on the following part of the foreach statement or the variable declaration. These behaviors are in sync between the compiler and the IDE, so functionally there is no issue. However, it feels odd that the breakpoint does not cover the keywords as we include the modifiers in the breakpoint span in other variable declaring constructs, like a field declaration.

Async foreach:
![image](https://user-images.githubusercontent.com/41759/61648973-65bbed80-ac65-11e9-80fa-4fe2a982fe0b.png)

Using declaration:
![image](https://user-images.githubusercontent.com/41759/61649116-aae01f80-ac65-11e9-9b72-09f131882f6e.png)

![image](https://user-images.githubusercontent.com/41759/61649068-90a64180-ac65-11e9-9054-72728b30ddd2.png)

![image](https://user-images.githubusercontent.com/41759/61649049-8ab06080-ac65-11e9-9466-d10d9af9ba1b.png)

Field declaration:
![image](https://user-images.githubusercontent.com/41759/61649644-b849d980-ac66-11e9-9184-014cb5ffe0bc.png)

![image](https://user-images.githubusercontent.com/41759/61649832-11197200-ac67-11e9-921b-bb5ee808296e.png)

**Comment by jcouv** [comment]
Fixed in 16.4p1
