### ISSUE TITLE
Copying solution folder then opening sln => wrong source files opened on startup

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37400]
Every morning I copy my solution folder then rename it.  For example folder .. \Solution_07_18_2019 gets copied to .. \Solution_07_19_2019 (no source control, etc. - I'm the only developer).  Then I launch Visual Studio and open the new copy by browsing to Solution_07_19_2019\...\Solution.sln.  The project opens fine, and Visual Studio automatically reopens/loads the source files I had open when I last closed the Solution (yesterday) - but it loads them from the old location!  So I have to remember to close them all or I will be editing the old versions (the clue I forgot is when intellisense starts acting funny in the source file).  For example if I do File/Save As it shows the old location .. \Solution_07_18_2019\.. \SourceFile.cs.  Simply closing all the open documents then double-clicking on them in the Solution Explorer to reopen the correct ones works fine.  I actually put a &quot;close all documents&quot; tool-bar button on my tool-bar...

I would suggest not opening the &quot;last-open&quot; documents at all if the sln file is not where it was previously?  Or using relative paths?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/653069/copying-solution-folder-then-opening-sln-wrong-sou.html
VSTS ticketId: 950068_
_These are the original issue comments:_

Visual Studio Feedback System on 7/22/2019, 05:43 AM (2 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by vatsalyaagrawal** [comment]
Repros in 16.3.P1
