### ISSUE TITLE
'Find all references' breaks when assigning via deconstruction

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#37404]
**Version Used**: Visual Studio 16.1.6

I wanted to see a list of all writes to parameter `a`, so I right-clicked the write to `a` that was in front of me:

```cs
class C
{
    void M(int a, int b)
    {
        // Find all references of the parameter `a` by right-clicking the first reference to it
        // in the following line (on the left-hand side of the assignment):
        (a, b) = Adjust(a, b);
    }

    (int a, int b) Adjust(int a, int b)
    {
        a++;
        b++;
        return (a, b);
    }

    void AVeryUnrelatedMethod()
    {
        var x = (a: 3, b: 4);
        Console.WriteLine(x.a);
    }
}
```

The result should have been the same as if I had right-clicked any other reference to the parameter `a`:

![image](https://user-images.githubusercontent.com/8040367/61653637-babd2b00-ac88-11e9-8515-a3be6fc32f38.png)

Instead, it returned all references to `(int a, int b).a` which is not at all the same thing as the parameter `a` which is referenced in the syntax that I clicked. It even dug into other projects:

![image](https://user-images.githubusercontent.com/8040367/61653541-8ea1aa00-ac88-11e9-9566-db998553ae13.png)

**Comment by CyrusNajmabadi** [comment]
I believe there is a tracking issue for findrefs/rename for tuple args.  @sharwell do you know where it is?

**Comment by sharwell** [comment]
@gafter @agocke is the left hand side of a deconstruction considered a tuple value?

**Comment by agocke** [comment]
cc @jcouv

**Comment by jcouv** [comment]
Here's the general issue for tuples, which I believe is the root cause for this issue as well: https://github.com/dotnet/roslyn/issues/20115
When selecting `([|a|], b)`, we want to highlight both usages of `a`, and `.a` and `.Item1` on that tuple type.

**Comment by jnm2** [comment]
Looks like this issue is a direct duplicate of https://github.com/dotnet/roslyn/issues/32982.
