### ISSUE TITLE
Cannot build latest Roslyn

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#37411]
**Version Used**: master as of earlier today, VS 16.20 preview 4

**Steps to Reproduce**: 
cannot build roslyn. I've tried building in VS, as well as shutting down VS, deleting .vs folder, running Restore.cmd, running build.cmd, but it fails.

The error message is:

```
error CS1617: Invalid option '8.0' for /langversion. Use '/langversion:?' to list supported values.
```

**Comment by agocke** [comment]
hmm that definitely seems weird. Can you share a build log or print the full csc command line? I want to make sure we're using the right compiler.

**Comment by YairHalberstadt** [comment]
The compiler is `Microsoft (R) Visual C# Compiler version 2.8.0.62830 (e595ee27)`

The build log printed by Visual Studio on diagnostic is available here: https://gist.github.com/YairHalberstadt/19844c72d23d8fac2c7161eee3a80ce3

please let me know if there's anything else you want.

**Comment by YairHalberstadt** [comment]
I deleted the branch and then pulled it again from origin, and everything seems to work, so closing this.
