### ISSUE TITLE
Visual Basic call hierarchy incorrectly thinks setting function return value is a recursive call

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37429]
In Visual Basic (VB.NET) if you have a function Foo, then you can set the return value by assigning it to the Function name. &quot;Foo = result&quot;
However if you ask Visual Studio to View Call Hierarchy on the function Foo, then it incorrectly thinks there is a recursive call when setting the return result. See screenshot.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/559257/visual-basic-call-hierarchy-incorrectly-thinks-set.html
VSTS ticketId: 888358_
_These are the original issue comments:_

Visual Studio Feedback System on 5/6/2019, 06:57 PM (77 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

![image](https://user-images.githubusercontent.com/7817401/61736953-0d0b5400-ad3c-11e9-92dc-823d6164714a.png)

**Comment by vatsalyaagrawal** [comment]
Ack. Looks like a bug. Taking it off design review.

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to change these experiences.
