### ISSUE TITLE
Wrap array initializer expressions.

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#37428]
Before:
```cs
var xs = new[] [|{ 1, 2, 3, 4 }|];
```

After:
```cs
var xs = new[]
{
    1,
    2, 
    3,
    4,
};
```

Would be nice if there was a refactoring `Wrap every expression` similar to `Wrap every argument`

**Comment by CyrusNajmabadi** [comment]
👍 We can also have things like "Wrap long" here to match our other features.  This should not be hard to provide fwiw.

**Comment by tokarzkj** [comment]
I would be interested in working on this if no one else has grabbed it.

**Comment by CyrusNajmabadi** [comment]
go ahead @tokarzkj ! :)
