### ISSUE TITLE
Test harness for region analysis has some strange behavior.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#37421]
From PR: https://github.com/dotnet/roslyn/pull/37395 and @gafter:

> OK, I think I understand why that test behaves the way it does. Other APIs will display bad behavior too. Please file an issue for it and notate the unexpected test with that bug number. Tag me in the bug and I will fix it.

The unexpected test is LocalFuncCapture8 (which has also been updated to link to this issue).

**Comment by gafter** [comment]
Likely a symptom of https://github.com/dotnet/roslyn/issues/37427

**Comment by gafter** [comment]
I believe this is now fixed in https://github.com/dotnet/roslyn/pull/37450

Please reopen if that is not the case.

**Comment by CyrusNajmabadi** [comment]
Thanks @gafter @agocke !
