### ISSUE TITLE
`csharp_indent_labels = flush_left` shouldn't affect indent of comment after label

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#37422]
**Version Used**: 
VS2019 16.2Preview4 or dotnet-format 3.0.4
Compiler version: '3.2.0-beta4-19359-03 (15b43b33)'. Language version: latest.

**Steps to Reproduce**:

1. Format the below code with `csharp_indent_labels = flush_left`

**Expected Behavior**:
flush_left:
```csharp
        public void M()
        {
//comment1
label:
            //comment2
            Console.WriteLine("test");
        }
```
Indent of the comment after label should not be affected, as it does for `csharp_indent_labels = one_less_than_current`(94c8fc41a4e5e3c7b0f1ccb4150eee004467e0fb).

one_less_than_current:
```csharp
        public void M()
        {
        //comment1
        label:
            //comment2
            Console.WriteLine("test");
        }
```

**Actual Behavior**:
flush_left:
```csharp
        public void M()
        {
//comment1
label:
//comment2
            Console.WriteLine("test");
        }
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack fo feedback.
