### ISSUE TITLE
Region analysis gives incorrect results in the presence of local functions

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#37427]
Region analysis gives incorrect results in the presence of local functions.  The implementation does not properly track the start and end of the region, resulting in incorrect results.

See also https://github.com/dotnet/roslyn/issues/37421 https://github.com/dotnet/roslyn/issues/19497

/cc @CyrusNajmabadi @agocke 

``` c#
        [Fact, WorkItem(37427, "https://github.com/dotnet/roslyn/issues/37427")]
        public void RegionWithLocalFunctions()
        {
            var analysisResults = CompileAndAnalyzeDataFlowStatements(@"
class A
{
    static void M(int p)
    {
        int i, j;
        i = 1;
        /*<bind>*/
        int L1() => 1;
        int k;
        j = i;
        int L2() => 2;
        /*</bind>*/
        k = j;
    }
}
");
            var dataFlowAnalysisResults = analysisResults;
            Assert.True(dataFlowAnalysisResults.Succeeded);
            Assert.Equal("k", GetSymbolNamesJoined(dataFlowAnalysisResults.VariablesDeclared));
            // should be "j"
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.AlwaysAssigned));
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.Captured));
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.CapturedInside));
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.CapturedOutside));
            // should be "i"
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.DataFlowsIn));
            // should be "j"
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.DataFlowsOut));
            // should be "i"
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.ReadInside));
            // should be "j"
            Assert.Equal("i, j", GetSymbolNamesJoined(dataFlowAnalysisResults.ReadOutside));
            // should be "j"
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.WrittenInside));
            // should be "p, i, k"
            Assert.Equal("p, i, j, k", GetSymbolNamesJoined(dataFlowAnalysisResults.WrittenOutside));
        }
```

**Comment by agocke** [comment]
Dup of https://github.com/dotnet/roslyn/issues/14214

This is because local functions are unable to track unassignments at the moment.

**Comment by CyrusNajmabadi** [comment]
Note: this is  *currently* not an issue that seems to have any impact on IDE features.  i.e. we haven't been bitten by this *yet*.  So there's no pressure from that end to fix this.  If that ever changes, i will let you know :)

**Comment by agocke** [comment]
Oh, it does affect current features, notably extract method, because `DataFlowsOut` is wrong. It's just complicated to fix and I haven't prioritized it.

**Comment by gafter** [comment]
> This is because local functions are unable to track unassignments at the moment.

I don't think so.  In this example the local functions are trivial and would have no impact on that.  I think this is because local functions are not analyzed in the order in which they appear in the enclosing block, confusing region analysis about where the regions starts and ends.

**Comment by CyrusNajmabadi** [comment]
> Oh, it does affect current features, notably extract method, because DataFlowsOut is wrong. It's just complicated to fix and I haven't prioritized it.

Oh, fair enough.  I hadn't realized that.  Thanks for letting me know! :)

**Comment by agocke** [comment]
Ah, yes, I guess there are two bugs here, region analysis is also wrong.
