### ISSUE TITLE
Quick actions and refactorins suggest to delete unity methods that aren't called

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37432]
Quick actions and refactorins suggest to delete unity methods that aren't called, such as &quot;Awake&quot;,&quot;OnTriggerEnter&quot;,&quot;Update&quot; and etc

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/520876/quick-actions-and-refactorins-suggest-to-delete-un.html
VSTS ticketId: 842165_
_These are the original issue comments:_

Visual Studio Feedback System on 4/8/2019, 03:45 AM (106 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by mavasani** [comment]
We added diagnostic suppressor API when addressing https://github.com/dotnet/roslyn/issues/30172. You need to raise a feature request on unity to write a suppressor for these diagnostics. Tagging @jbevain
