### ISSUE TITLE
Quick Actions not applying within Document/Project/Solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37435]
On being offered a Quick Action (xUnit2000 to be specific) clicking any of Document, Project or Solution does not apply the change as expected. The Quick Action will only work on a single instance.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/546859/quick-actions-not-applying-within-documentprojects.html
VSTS ticketId: 855884_
_These are the original issue comments:_

Visual Studio Feedback System on 4/26/2019, 00:53 AM (88 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by mavasani** [comment]
This seems like an issue with the 3rd party xunit code fixer. Can you please report an issue at https://github.com/xunit/xunit/issues?
