### ISSUE TITLE
Intellisense not showing when named arguments are inserted

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37436]
Intellisense works as normal, apart from the case of what appears to be a new feature in VS2019 - sometimes when calling a constructor or a function, a parameter has the argument name prepended to it by the editor. When this happens, hovering over the function name/constuctor does not make the normal intellisense pop-up appear.

In both the attached images, the cursor is hovering over _TestFunction()_; PrintScreen just doesn't capture it.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/552569/intellisense-not-showing-when-named-arguments-are.html
VSTS ticketId: 860170_
_These are the original issue comments:_

Visual Studio Feedback System on 5/1/2019, 09:57 PM (82 days ago): We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

_These are the original issue solutions:_
(no solutions)

```
    class SimpleClass {
        public SimpleClass(string i) { }
    }

    class Program {
        static void Main()
        {
            SimpleClass c4 = new SimpleClass(i: "t");
            SimpleClass c41 = new SimpleClass("t");
        }
    }
```

**Comment by vatsalyaagrawal** [comment]
Repros in 16.3

**Comment by sharwell** [comment]
I was not able to reproduce this issue. In the sample code above, Quick Info worked properly for both constructor invocations.
