### ISSUE TITLE
MetadataAsSource document construction is not cancellable

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#3744]
Split from internal bug 1193614.

1. Make a class with, say, [4000 methods](https://gist.github.com/dpoeschl/1fff529f6f7fb9da5291). 
2. Compile it into some assembly, ```Test.dll```
3. Make a Class Library that references ```Test.dll```
4. Add a call to ```ClassLibrary1.Class1.M000()```
5. Go To Definition (F12) on ```M000```

It will take a *long* time to navigate, and cancelling the wait dialog does not cancel the operation or unblock the UI.

**Comment by Pilchie** [comment]
@rchande  - you've been looking at a bunch of Metadata as source perf lately. You might as well add cancel support at the same time.

**Comment by rchande** [comment]
Overall, MAS is cancellable. Unfortunately, the particular codepath it takes through the code generator doesn't propagate CancellationToken.

**Comment by Pilchie** [comment]
Didn't you just merge a PR to fix address this?

**Comment by Pilchie** [comment]
Yes, fixed by #4844.
