### ISSUE TITLE
PublicAPI.Unshipped.txt API files should be moved to PublicAPI.Shipped.txt

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#37443]
Now that we're past the C# 8 preview period and have shipped some new APIs, we should move the "Unshipped" API file to the "Shipped" file so we have a record of what APIs we shipped.

/cc @jcouv @agocke

**Comment by jcouv** [comment]
I think this should already part of @dotnet/roslyn-infrastructure plans (we don't have to do this for the compiler file specially). Let's confirm

**Comment by jasonmalinowski** [comment]
Hmm, at this point we'd be doing this for 16.2 GA since that's now shipped. Do you have anything else in 16.3 though that needs to be tracked *now* since you're "shipping earlier" from the perspective of a lockdown?

**Comment by 333fred** [comment]
This was fixed in https://github.com/dotnet/roslyn/pull/38594.
