### ISSUE TITLE
Add "fix namespaces" action that applies to all files in a Solution Explorer node

### ISSUE THREAD

**Issue by dagood** [dotnet/roslyn#37453]
This was mentioned in https://github.com/dotnet/roslyn/issues/14341#issuecomment-489984793, and I'm filing a new issue to raise it as its own request. It was initially not implemented due to performance issues, however it comes up often for me. I use ReSharper to get it done.

Scenarios where I commonly use this feature:

1. I have ten or so C# files I need to copy from one GitHub repository to another. I copy and paste the files into the file system where I want them. Now I want to fix the namespaces to fit the target.
   * Not covered by https://github.com/dotnet/roslyn/issues/37243 because I'm not moving the files within one Visual Studio context.

2. I have a bunch of files I’ve inherited where some classes are in proper namespaces, some are in the wrong namespace, and some lack namespaces completely.
   * Not covered by https://github.com/dotnet/roslyn/issues/37243 because there's no clear way to trigger the action when no files are being moved. (https://github.com/dotnet/roslyn/issues/37243 focuses on *keeping* namespaces correct rather than *correcting* namespaces.)

Note that in the scenarios I personally encounter, I don't need Visual Studio to tell me when the namespace doesn't match--I know when I need/want to apply this action.

Expected behavior:

1. I right-click on a solution explorer node and select the "fix namespaces" ("adjust namespaces") action.
2. (Optional) I get prompted to provide any clarifying info, and see a list of files that will be changed.
    1. I click OK.
4. The namespaces within that node are adjusted and known references to them are changed to match.

/cc @mikadumont

**Comment by jinujoseph** [comment]
cc @genlu

**Comment by mikadumont** [comment]
cc @ryzngard

**Comment by ryzngard** [comment]
@genlu @mikadumont is this handled by work for analyzer?

**Comment by AmarjeetBanwait** [comment]
It will be good if the similar option will be provided on project level and folder level also.

**Comment by dagood** [comment]
> It will be good if the similar option will be provided on project level and folder level also.

I agree, I would not consider this issue completed unless this is the case. Having to go through 10 (first scenario) or a bunch (second scenario) of files and individually click on each of them would mean I'd still use ReSharper for this. This is what I'm driving at when I say "right-click on a solution explorer node" in the expected behavior.

> is this handled by work for analyzer?

I'd be interested to hear what might handle this. I'm happy to read through another issue to see if its solution applies here and add more details to the description if it doesn't seem like it to me. (My main focus being the UX--can it replace my ReSharper usage--rather than how it's implemented.)

**Comment by mikadumont** [comment]
@ryzngard The analyzer work will cover diagnostic in the error list with a fix all code fix across a project or solution. But we will need to create a UI gesture in Solution Explorer for this.

**Comment by ryzngard** [comment]
Also make sure we include if a folder is renamed in solution explorer. From https://twitter.com/sarathi4ever/status/1276646523283976193?s=20

**Comment by drmcclelland** [comment]
I would love to have this feature!  Quite often I find myself in the same situations that @dagood mentioned.

**Comment by mikadumont** [comment]
Proposal:

1. A right click menu option to `Sync Namespace` within the Solution Explorer on a given C# file, folder (that contains C# files), project, and solution:

![image](https://user-images.githubusercontent.com/46729679/108292990-61113100-7149-11eb-9443-8cda866d38a4.png)

2. Selecting the `Sync Namespace` action will open a dialog that displays files that have inconsistent namespaces that are pre selected by default - this allows you to deselect certain files that you may not want to apply the fix to or view the files that will be changed.

![image](https://user-images.githubusercontent.com/46729679/108294630-0f69a600-714b-11eb-9678-5d11950b9e8c.png)

3. Selecting `OK` will apply the `Sync Namespace` code fix. 

@ryzngard

**Comment by dagood** [comment]
> projects/solutions

Having folder granularity rather than only project/solution can be useful. Adding a bit to my first scenario a bit to highlight:

> 1. I have ten or so C# files I need to copy from one GitHub repository to another. I copy and paste the files into the file system where I want them. Now I want to fix the namespaces to fit the target. **There are other files in the target project that already have mismatched namespaces, and I don't want to fix them right now: I want to avoid unrelated noise in my upcoming PR with the new files.**

I'll readily admit this probably isn't a widespread problem. 😄 A project *should* have consistently correct namespaces, maintainers *should* have enough time to work on/accept a PR that fixes up longstanding namespace issues, and the project *should* have enough test coverage that fixing up namespaces is not a significant concern. I just want to show a reason being able to apply this fix on an arbitrary solution explorer node is useful.

If my most granular option is to apply the fix at a project level, I can probably revert the unwanted changes in Git, and be fine with that, personally.

> large chunks of code in a single pass

https://github.com/dotnet/roslyn/issues/14341#issuecomment-490171278 mentioned perf concerns about this. Have those been resolved?

**Comment by ryzngard** [comment]
The analyzer was added https://github.com/dotnet/roslyn/pull/49990  @drewnoakes 

The analysis part is cheap, so perf concerns have been addressed there. Fixing can still be expensive but that will be true no matter how we surface that. 

We think that adding a right click menu would be an additional help

**Comment by drewnoakes** [comment]
> Having folder granularity rather than only project/solution can be useful

This is true for many other code fixes. Adding support for "fix in folder" and "fix in folder and subfolders" to batch fixing would be of general use for existing and future analyzers.

> We think that adding a right click menu would be an additional help

I don't doubt that it would see use.

Every new menu item should start with [minus 100 points](https://docs.microsoft.com/en-us/archive/blogs/ericgu/minus-100-points). Would this menu item only be visible when invoking it would result in a change being made?

Why only add a menu item for this feature? There are dozens of code fixes that could be launched from Solution Explorer that are not currently available as menu items. A more general "clean up this chunk of code" feature that spans multiple code fixes, with controls to slice by diagnostic, diagnostic category, severity, etc would be more powerful and avoid this specialisation.

**Comment by jmarolf** [comment]
I don't think I would use this feature without the right click menu. I need to be able to incrementally 'rationalize' structure in a folder-based way. If there are multiple namespace issues that are out of sync I need to be able to do incremental refactorings.

**Comment by ryzngard** [comment]
Also keep in mind we have had explicit asks for a right click menu here. I don't think we should block adding it on a general effort to make "code cleanup" (or something similar) better and to fill this need. We can definitely continue to improve the menus in a general sense or adding folder support for code fixes. 

+ @mikadumont for visibility on this feedback

**Comment by TzvetomirTodorov** [comment]
I love this idea. I'm currently dealing with a situation where I have to make a namespace change for a class that was referenced using a partial namespace (not-fully qualified). This new class comes from a NuGet package and so now I have over 500 areas in my solution between over hundreds of projects (that is another problem that we are trying to fix) that I have to individually re-import the proper fully qualified NuGet namespace.

Again, this feature would most likely have a ton of performance issues at the scale I am doing this at and realistically it is unsafe to rely on that many changes going through accurately without spot checking.

I am eager and excited to see what your team comes up with. Cheers!

**Comment by ryzngard** [comment]
@TzvetomirTodorov this is interesting. In general we think of this applying as a rule to fix namespace ruling, not imports. In your case, the imported namespace is something we consider by "add missing usings" because in the namespace change for nuget you are now missing the correct using. 

What NuGet packages are you using that change namespace often? I'd love to hear more about this. I don't think that scenario is covered by this issue so we may need to open a new one.

**Comment by TzvetomirTodorov** [comment]
@ryzngard Absolutely! Wow, thanks for the swift response! 
So I have classes that were referenced in the solution that were later moved in to their own respected - internal NuGet package.

So my work flow is the following:
1. Remove the class from the Solution.
2. Identify missing import cases.
3. Now we want the class from the NuGet package instead --> Install NuGet to each project that requires it.
4. Click thorough 500+ error missing import messages in my console identify the old import --> change it to use my NuGet instead.

I hope that answers any questions you may have. Again, thank you so much for getting back to me so quickly. 

Still excited to see how your team tackles this challenge if they find the need to.
Appreciate everything you guys do and the crazy amounts of time your product saves me, thank you!

**Comment by JoeRobich** [comment]
Closing as this feature has been implemented and is available on Solutions nodes and C# project nodes. It will automatically fix up namespaces for all the files within the scope that it is invoked from.

**Comment by dagood** [comment]
> available on Solutions nodes and C# project nodes.

This seems to be missing the folder-level granularity that I and a few others think would be useful:

https://github.com/dotnet/roslyn/issues/37453#issuecomment-794748821

> > Having folder granularity rather than only project/solution can be useful
> 
> This is true for many other code fixes. Adding support for "fix in folder" and "fix in folder and subfolders" to batch fixing would be of general use for existing and future analyzers.

https://github.com/dotnet/roslyn/issues/37453#issuecomment-794756740

> I need to be able to incrementally 'rationalize' structure in a folder-based way. If there are multiple namespace issues that are out of sync I need to be able to do incremental refactorings.

Are there plans to add this?

**Comment by nadcraker** [comment]
I'm trying to decipher the tags and labels, my apologies. But is this feature in VS 2019? Or VS 2022? I have both installed and don't see this context menu option. Is it coming in a future release?

**Comment by dagood** [comment]
> > available on Solutions nodes and C# project nodes.
> 
> This seems to be missing the folder-level granularity [...]

I've filed https://github.com/dotnet/roslyn/issues/55886 to discuss/track this.

**Comment by ryzngard** [comment]
> This feature doesn't seem to work at all for me, am I missing something?
> 
> Im using VS 2022 Version 17.2.4
> 
> I have a solution with multiple projects (I only want to "fix" one, but the context menu only works on the solution)
> 
> I have multiple files which either don't have a namespace at all or folders which contain files which have different / wrong namespaces.
> 
> But when I press the button sync it says "No namespace needed updating" and does nothing.
> 
> I thought this feature would offer me to add the namespace if it doesn't exist or "fix" them if multiple files (in the same folder) have different namespaces?

Do you have a sample repro sln we can use? Or more information on your project?
