### ISSUE TITLE
Boxing a TypedReference produces an undiagnosable error

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/roslyn#3746]
This is similar to issue #3593 - create a blank Windows Universal app in VS and put this method and field in it:

    public static object rrr;

    public static T Read<T>() where T : new()
    {
        T result = new T();
        var refresult = __makeref(result);
        rrr = refresult;
        return result;
    }

An attempt to build the app results in CSC : error CS7038: Failed to emit module 'TestEmptyApp'. I would expect the compiler to tell me not to box a TypedReference.

**Comment by VSadov** [comment]
Boxing is one of the operations that are not allowed on a TypedReference.
