### ISSUE TITLE
SyntaxFactory.MethodDeclaration bug

### ISSUE THREAD

**Issue by sunkin351** [dotnet/roslyn#37467]
**Version Used**: 
v3.1.0 Microsoft.CodeAnalysis.CSharp

**Steps to Reproduce**:
Use `SyntaxFactory.MethodDeclaration(SyntaxList<AttributeListSyntax>, SyntaxTokenList, TypeSyntax, ExplicitInterfaceSpecifierSyntax, SyntaxToken, TypeParameterListSyntax, ParameterListSyntax, SyntaxList<TypeParameterConstraintClauseSyntax>, BlockSyntax, SyntaxToken)` overload

**Expected Behavior**:
Semicolon SyntaxToken passed to wrapped method

**Actual Behavior**:
Semicolon SyntaxToken replaced with `default(SyntaxToken)`

Checked IL in downloaded nugget package to verify issue.

**Comment by 333fred** [comment]
https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Syntax/MethodDeclarationSyntax.cs#L37

We're not passing a parameter along.
