### ISSUE TITLE
Incorrect spilling of stackalloc in async method

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#37461]
**Version Used**: 
![image](https://user-images.githubusercontent.com/41759/61834392-a3b73e00-ae2c-11e9-8899-a6cfec62e2b4.png)

**Steps to Reproduce**:

```C#
using System;
using System.Threading.Tasks;

public class P
{
    static object F1() => 1;
    static object F2() => 1;
    static int G(object obj, Span<int> span) => span.Length;

    static async Task Async1(Object obj, int i) { await Task.Delay(1); }

    static async Task Main()
    {
        await Async1(F1(), G(F2(), stackalloc int[] { 1, 2, 3 }));
    }
}
```

**Actual**

The program compiles and throws 

> System.TypeLoadException: 'A ByRef-like type cannot be used as the type for an instance field in a non-ByRef-like type.'

at runtime since the lowering of stackalloc in await expression spills `Span<T>` to a state machine field.

**Expected**

Compiler error.

**Comment by gafter** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/37711
