### ISSUE TITLE
Not getting Rename file to

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#37469]
In one sln:
![image](https://user-images.githubusercontent.com/1640096/61863513-0a416800-aed0-11e9-8e70-a2651e2bc0b5.png)

In another sln it works:
![image](https://user-images.githubusercontent.com/1640096/61863598-365ce900-aed0-11e9-85c7-ba482462d272.png)

Both are identical with:

```cs
namespace N
{
    public static partial class C1
    {
        public static class C2
        {
        }
    }
}
```

In a file named `WrongName.cs`

I could not narrow down a repro, tried restarting VS etc but no dice.

**Comment by CyrusNajmabadi** [comment]
I believe this may be a CPS limitation.

**Comment by JohanLarsson** [comment]
What is CPS?

**Comment by jmarolf** [comment]
project system silliness. @dpoeschl 	I thought this was fixed on the project system side.  Are their still issues?

**Comment by dpoeschl** [comment]
@jmarolf http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs,393

```C#
internal override bool CanRenameFilesDuringCodeActions(CodeAnalysis.Project project)
            => !IsCPSProject(project);
```

I believe the Project System is fixed to support it, but this check stops it from working. We _should_ be able to remove that check (and add an integration test?) now.

**Comment by penenkel** [comment]
May be a duplicate of #24560.

**Comment by jmarolf** [comment]
@ryzngard considering inline rename works in CPS I assume this will as well?

**Comment by Felix-Dev** [comment]
I still have no [Rename file to] quick action available in Visual Studio 16.4 for .NET Core 3.1 projects (works fine for .NET Framework and UWP projects). Any updates on when this issue will be resolved?

**Comment by quetzalcoatl** [comment]
@Felix-Dev see issue 24560, it's probably the oldest copy

**Comment by sharwell** [comment]
Duplicate of #24560
