### ISSUE TITLE
Verify that _modelToDetector does not hold objects forever

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#37465]
https://github.com/dotnet/roslyn/blob/4c171beb0ea8e18e020c1a75bac8e0229e1b4fd5/src/Workspaces/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexPatternDetector.cs#L74

`_modelToDetector` is a conditional weak table, where the values in the table have a strong reference to the key. @stephentoub will this pattern prevent the values in the table from ever getting collected?

**Comment by CyrusNajmabadi** [comment]
@sharwell 

> adding a key/value pair to the table does not ensure that the key will persist, even if it can be reached directly from a value stored in the table (for example, if the table contains one key, A, with a value V1, and a second key, B, with a value P2 that contains a reference to A). Instead, ConditionalWeakTable<TKey,TValue> automatically removes the key/value entry as soon as no other references to a key exist outside the table.

From: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2?view=netframework-4.8

**Comment by sharwell** [comment]
Thanks, I'm guessing the issue I observed is simply that the GC hadn't collected these objects yet.
