### ISSUE TITLE
Adding #warning in this code causes Intellisense errors to appear

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37479]
Adding the #warning line to this code has produced Intellisense errors, although the code still builds as expected.

IDE1008	'TwoItemTrayRobotStopOutput' does not contain a constructor that takes that many arguments.
IDE1008	'RowaConveyorPackRelease' does not contain a constructor that takes that many arguments.

```
this.robotStopOutputs = stopsToRobotIDs.ToDictionary(
                x =&gt; x.Key,
                x =&gt;
                {
                    TwoItemTrayCycle.Stops stop = x.Key;
                    int robotID = x.Value;

#warning HoldAtRobot function will be needed
                    return new TwoItemTrayRobotStopOutput(
                        stop,
                        robotID,
                        database,
                        output,
                        new RowaConveyorPackRelease(
                            rowaConveyor.Robots[robotID]. TransportSystems[TwoItemTrayRowaConveyor.TransportSystem1Name],
                            rowaConveyor.Robots[robotID]. TransportSystems[TwoItemTrayRowaConveyor.TransportSystem2Name]),
                        trayJobManager,
                        databaseConnection =&gt; new RobotArmTwoItemTrayCycleRepository(databaseConnection),
                        () =&gt; false,
                        this. ReleaseFromRobotStop,
                        errorHelper);
                })
                . ToImmutableDictionary();
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/564413/adding-warning-in-this-code-causes-intellisense-er.html
VSTS ticketId: 891274_
_These are the original issue comments:_

Visual Studio Feedback System on 5/12/2019, 10:50 PM (73 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Could not repro this.
