### ISSUE TITLE
Incorrect IDE0004 in iterator

### ISSUE THREAD

**Issue by impworks** [dotnet/roslyn#37473]
**Version Used**: 
VS 15.9.11.

**Steps to Reproduce**:

```
public class Foo
{
    public IEnumerable<object> Bar()
    {
        yield return ("test", (decimal?)1.23);
    }
}
```

**Expected Behavior**:
No suggestions.

**Actual Behavior**:
Roslyn suggests a fix:

![image](https://user-images.githubusercontent.com/604496/61874604-754f6680-aef1-11e9-9431-59a199c752c2.png)

This fix breaks the program's semantics, since the actual returned value's type changes from `ValueTuple<string, Nullable<decimal>>` to `ValueTuple<string, double>`.

**Comment by canton7** [comment]
Related: #33143
