### ISSUE TITLE
SourcePropertySymbol.IsExplicitInterfaceImplementation should not need to reconstitute the source tree

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#37476]
**Version Used**: 16.2 Preview 4

:link: https://developercommunity.visualstudio.com/content/problem/651516/refactoring-tools-randomly-take-a-long-time-to-pro.html

**Expected Behavior**:

Calls to `SourcePropertySymbol.IsExplicitInterfaceImplementation` should return without accessing `CSharpSyntaxNode`.

**Actual Behavior**:

The property accesses the syntax tree, which can force the recreation of the entire tree if it is not currently in memory (more than 36% of the allocations seen in the linked feedback ticket).

**Comment by AlekseyTs** [comment]
The information should come from syntax initially, but it could be cached on a symbol or in a declaration table.

**Comment by RikkiGibson** [comment]
It looks like the fix was merged in #37836. Is that correct?

**Comment by CyrusNajmabadi** [comment]
@RikkiGibson Yes.
