### ISSUE TITLE
cannot launch visual studio 15.9 .  StreamJsonRpc.removetInvocation exception 

### ISSUE THREAD

**Issue by BinduMK** [dotnet/roslyn#37470]
**Version Used**:  2017 15.9

**Steps to Reproduce**:

1. Installed Visual Studio 2017 15.9
2. Tried to launch

**Expected Behavior**: Open VS

**Actual Behavior**: Getting exception on  StreamJsonRpc

I tried to uninstall/reinstall/repair VS so many times but nothing worked. I am stuck and cannot open any of my projects. Please help. Very urgent
![Capture](https://user-images.githubusercontent.com/53298276/61865817-8b5d2700-aef1-11e9-97c7-d5a42bd4555c.JPG)

**Comment by vatsalyaagrawal** [comment]
Please report this issue using the instructions provided @ https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019
