### ISSUE TITLE
VB.NET compiler and intellisense give conflicting information when using operand of type Object in a Select statement

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37480]
I have legacy VB.NET code. There is DataRow associated with an SQL Server table that has a column called LOCATION which is an Integer datatype.

The code uses the Item indexer with the String argument and a return type of Object. e.g. row(&quot;LOCATION&quot;)

If that expression is used for the Select statement, then the compiler will generate &quot;warning BC42036: Operands of type Object used in expressions for 'Select', 'Case' statements; runtime errors could occur.&quot;

If  you attempt to placate the compiler by using a cast (CInt, CType, DirectCast, etc) say: Select Case CInt(row(&quot;LOCATION&quot;)), then the code editor (intellisense I assume) says that the cast is redundant. See screenshot line 661 (and other examples at 638, 641)
Can't have it both ways.
One of these (compiler or intellisense) is incorrect (probably intellisense).

Please fix.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/560936/vbnet-compiler-and-intellisense-give-conflicting-i.html
VSTS ticketId: 889112_
_These are the original issue comments:_

Visual Studio Feedback System on 5/8/2019, 01:29 AM (78 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
