### ISSUE TITLE
IDE0060 Does Not Recognize All Event Handlers in VB

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37483]
When I connect an event handler in XAML or by using an AddHandler statement (meaning that the method has an appropriate signature, but has the same syntax as any other method not used as a handler), Visual Studio 2019 Community's Code Style gives me IDE0060 messages (Remove unused parameter 'e', Remove unused parameter 'sender', etc.). I recognize that methods used as event handlers have the same format &amp; syntax as other methods (and that it is, although probably not good programming practice, possible to not use them for the purpose of handling events), but I think that it would be nice if this feature of Code Style could be improved to help identify event handlers in the following ways:

1. Search XAML to help identify the event handlers
2. Assume (unless otherwise specified in a possible Code Style setting that you may end up adding) that all methods that have a signature matching the signature of an event handler

When the Messages section of the Error List is overflowing with suggestions that would break my code, it is a feature hardly worth using.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/544162/ide0060-does-not-recognize-all-event-handlers-in-v.html
VSTS ticketId: 854706_
_These are the original issue comments:_

Visual Studio Feedback System on 4/23/2019, 07:08 PM (92 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by mavasani** [comment]
This is by design. We do special case methods whose signature matches regular event handlers, see [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Shared/Extensions/IMethodSymbolExtensions.cs,369), but not others. Additionally, the diagnostic also gives recommendation on how to explicitly mark discard parameters which are not used but needed for signature/compat reasons to avoid IDE0060 for such parameters:

```
Avoid unused paramereters in your code. If the parameter cannot be removed, then change its name so it starts with an underscore and is optionally followed by an integer, such as '_', '_1', '_2', etc. These are treated as special discard symbol names.
```

![image](https://user-images.githubusercontent.com/10605811/63169712-60e02480-bfec-11e9-97ca-22869fa116c9.png)

**Comment by onovotny** [comment]
I would urge you to reconsider this. I disagree very strongly with this. Roslyn should *never* have a false positive on unused code when removing it will create a compile-time error. Attributes/pragmas aren't enough. Also, ReSharper's parser does not suffer this limitation.

**Comment by mavasani** [comment]
@onovotny What would be your proposal to avoid this? How would you change the below bail out logic?

```
        /// <summary>
        /// Returns true for void returning methods with two parameters, where
        /// the first parameter is of <see cref="object"/> type and the second
        /// parameter inherits from or equals <see cref="EventArgs"/> type.
        /// </summary>
        public static bool HasEventHandlerSignature(this IMethodSymbol method, INamedTypeSymbol eventArgsType)
            => eventArgsType != null &&
               method.Parameters.Length == 2 &&
               method.Parameters[0].Type.SpecialType == SpecialType.System_Object &&
               method.Parameters[1].Type.InheritsFromOrEquals(eventArgsType);
```

**Comment by onovotny** [comment]
I'm not a compiler person, but I would not expect this needs special handling for an event handler. Rather, I'd expect it to understand the method signatures from the XAML/or generated code (in memory if needed).

**Comment by riverar** [comment]
Agree, this should be marked "feature request" and re-opened. The current experience is sub-par.

**Comment by mavasani** [comment]
That would cause this analyzer’s analysis scope to increase to whole compilation, which is not feasible for live analysis- each key stroke would need whole compilation to be analyzed to refresh the diagnostic.

**Comment by riverar** [comment]
Fair.

Perhaps this is a case of an analyzer that's trying to provide whole compilation guidance, without the necessary context to do so. It also seems to have a bunch of undocumented constraints (as shown in your code snippet above). Maybe it's to rethink/disable this analyzer? Searching around on the Internet, it seems to be a common headache too.

**Comment by onovotny** [comment]
I do know that ReSharper does this without error in a live manner. So it can be done :) I don't know how.

**Comment by mavasani** [comment]
Re-opening and tagging for design review so it can be discussed at next IDE design meeting.

**Comment by riverar** [comment]
Thanks @mavasani!

**Comment by mavasani** [comment]
Investigating bit further there are couple of issues here:

1. Unused parameters flagged for methods used as delegates in generated code from xaml files. I have a simple fix to address it by allowing the analyzer to analyze generated code, sending a PR soon.
2. The generated .g.cs file corresponding to the xaml code does not get auto-updated when editing code or adding or updating any xaml designer controls. One needs to explicitly build the project to regenerate these generated files. This leads to incorrect unused parameter/member diagnostics for new handlers added via the designer, until the user does an explicit built. I will a separate follow-up issue to track this.

**Comment by mavasani** [comment]
Filed https://github.com/dotnet/roslyn/issues/38192 for the second issue: XAML code behind file (.g.i.cs) not auto-updated when editing the xaml file in IDE.

**Comment by palenshus** [comment]
I tried the suggested workaround of renaming the variable to _, but now I get an `SA1313: Parameter '_' should begin with lower-case letter` warning. Seems like I'm caught between a rock and a hard place

**Comment by CyrusNajmabadi** [comment]
@palenshus   SA1313 is not part of Roslyn.  Sounds like an issue to take up with them.  Thanks!

**Comment by palenshus** [comment]
I found https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2599 and added to it, for anyone else coming here for the same issue...
