### ISSUE TITLE
Code style changes not applied until VS2019 is restarted

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37484]
When the user makes changes to Code Style formatting, auto-format does not respect the changes until VS2019 is restarted.

1. Open Visual Studio 2019
2. Go into Options &gt; Text Editor &gt; C# &gt; Code Style &gt; Formatting &gt; New Lines
3. Make some changes to the New Lines settings
4. Click OK to confirm the changes and close the settings
5. Open a class file
6. Edit &gt; Advanced &gt; Format Document
7. Observe that the new formatting settings are not applied. VS2019 continues to use the previous settings
8. Close VS2019 and open it again
9. Open the same C# class file as in step 5
10. Edit &gt; Advanced &gt; Format Document
11. Observe that the new formatting settings from step 3 are now applied.

Users should not have to restart Visual Studio for code style changes to take effect.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/543905/code-style-changes-not-applied-until-vs2019-is-res.html
VSTS ticketId: 854325_
_These are the original issue comments:_

Visual Studio Feedback System on 4/23/2019, 08:29 PM (92 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
@chborl can you see if you can repro this with latest build

**Comment by jinujoseph** [comment]
Validated and no repro in 16.4.Preview2
