### ISSUE TITLE
Question: How do I use roslyn for code formatting?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/roslyn#37494]
![image](https://user-images.githubusercontent.com/16236903/61930359-100e7a80-afb0-11e9-867b-a6ab0960d931.png)
This code doesn't work. The workspace is null.  How do I get current workspace?

**Comment by NMSAzulX** [comment]
### Code:

```C#
var source =
           @"class A
{private struct S { 
}
}";

            SyntaxTree tree = CSharpSyntaxTree.ParseText(source);
            CompilationUnitSyntax root = tree.GetCompilationUnitRoot();


            var container = tree.GetText().Container;
            var workspace = Workspace.GetWorkspaceRegistration(container);


            var temp = Formatter.Format(root, workspace.Workspace);
            Console.WriteLine(root.ToString());
            Console.WriteLine(tree.ToString());
            Console.WriteLine(temp.ToString());
            Console.ReadKey();

```

**Comment by sharwell** [comment]
There is no workspace unless you create one. :smile: The Visual Studio integration creates a workspace for Roslyn to use inside Visual Studio. The [dotnet-format](https://github.com/dotnet/format) tool creates its own `MSBuildWorkspace`. Other standalone tools typically create either an `MSBuildWorkspace` (when loading a solution from disk) or an `AdhocWorkspace` (when constructing a temporary solution in memory).

Note that these operations cannot be used from an analyzer (`DiagnosticAnalyzer`). The workspace APIs are not available during command line compilation scenarios, so the failure would occur even earlier when it tried to load the types.

**Comment by NMSAzulX** [comment]
@sharwell  **Thank you very much!** I have modify my code like this:

```C#

//using Microsoft.CodeAnalysis.CSharp.Workspaces

_workSpace = new AdhocWorkspace();
_workSpace.AddSolution(
          SolutionInfo.Create(SolutionId.CreateNewId("formatter"), 
          VersionStamp.Default)
);

var formatter = Formatter.Format(Tree.GetCompilationUnitRoot(), _workSpace);

```

###   It works!  But there are still some code that cannot be formatted, such as：

![image](https://user-images.githubusercontent.com/16236903/61990179-06e3e300-b06e-11e9-8aab-17f623bf47e8.png)

### Will this be resolved after the package upgrade?

**Comment by CyrusNajmabadi** [comment]
>It works! But there are still some code that cannot be formatted, 

What do you mean by "cannot be formatted"?

If you try to format the same code in the VS editor do you see different behavior?  If so, can you specify the different results you get formatting in VS versus formatting by directly calling this API?

**Comment by NMSAzulX** [comment]
@CyrusNajmabadi  The same with VS.  I just want to know, is this feature synchronized with VS?

**Comment by CyrusNajmabadi** [comment]
>  I just want to know, is this feature synchronized with VS?

Yes.  It's the same engine powering both.

**Comment by NMSAzulX** [comment]
@CyrusNajmabadi Thank you, I get it.

**Comment by edwin-alvarez** [comment]
did you tried
            return CSharpSyntaxTree.ParseText(yourstringcode).GetRoot().NormalizeWhitespace().SyntaxTree.GetText().ToString();

**Comment by kunalspathak** [comment]
That works. Thanks @edwin-alvarez !

```c#
return CSharpSyntaxTree.ParseText(yourstringcode).GetRoot().NormalizeWhitespace().SyntaxTree.GetText().ToString();
```

**Comment by NMSAzulX** [comment]
@edwin-alvarez @kunalspathak Thanks. I tested it and the result was better than AdhocWorkspace Formart. I can still see some minor problems.
```c#
string code = @"public class A{
    public string A{get;set;}
public string B{get;set;}

public string C{get;set;}

public void  Test( ){NormalTestModel result = new NormalTestModel();return result;int i=0 ; var t=new{Name=""""};Console.WriteLine( ""aa"");}
}";
```

Result: 

```c#
public class A
{
    public string A { get; set; }

    public string B { get; set; }

    public string C { get; set; }

    public void Test()
    {
        NormalTestModel result = new NormalTestModel();
        return result;
        int i = 0;
        var t = new
        {
            Name = ""
        }

        ;
        Console.WriteLine("aa");
    }
}
```

**Comment by edwin-alvarez** [comment]
@NMSAzulX . yeap, I also noticed #regions are aligned a bit weird, but the code I suggested is a good start :)

**Comment by NMSAzulX** [comment]
@edwin-alvarez  Thank you. I like this format very much and I will use it in my project. I roughly monitored its memory usage and execution time. Compared with using AdhocWorkspace, this method reduces about 520ms time and 15 megabytes of memory.
