### ISSUE TITLE
Add accessibility modifiers analyzer on interfaces

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#37514]
I found a disabled block in CSharpAddAccessibilityModifiersDiagnosticAnalyzer.

https://github.com/dotnet/roslyn/blob/7075d221e6d4fedf6f08e13c0dcaf39c256bc0eb/src/Features/CSharp/Portable/AddAccessibilityModifiers/CSharpAddAccessibilityModifiersDiagnosticAnalyzer.cs#L55

```cs
#if false
            // Add this once we have the language version for C# that supports accessibility
            // modifiers on interface methods.
            if (option.Value == AccessibilityModifiersRequired.Always &&
                member.IsKind(SyntaxKind.InterfaceDeclaration, out typeDeclaration))
            {
                // Only recurse into an interface if the user wants accessibility modifiers on 
                ProcessTypeDeclaration(context, generator, option, typeDeclaration);
            }
#endif
```

It's possible this code should be enabled/modified now that we have DIMs. /cc @AlekseyTs and @CyrusNajmabadi.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
