### ISSUE TITLE
Indicate mutable members in editor.

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#37517]
Not sure how to render it best but it is useful info. I'm thinking maybe make the last char of the identifier of a mutable member in some distinct different colour. That may not work well for single char local variable names though. FSharp has had this for a while.

**Comment by CyrusNajmabadi** [comment]
@JohanLarsson can you show the picture from f#?

**Comment by JohanLarsson** [comment]
@ReedCopsey can you help us out with a screenie?

**Comment by JohanLarsson** [comment]
An alternative could be to animate opacity/visibility for mutables so that they flicker like broken fluorescent lamps :)

**Comment by jnm2** [comment]
I would like an option that changes the look of usages at or after a possible reassignment has occurred, but not before that point.

**Comment by jnm2** [comment]
Screenshot of Roslyn code that I stole from @alrz, demonstrating a ReSharper style option:

![image](https://user-images.githubusercontent.com/8040367/67901996-8c2fd580-fb3e-11e9-8d78-992e6fa70d28.png)
