### ISSUE TITLE
Move analyzers to separate repo

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#3752]
We have a number of analyzers projects in [dotnet/roslyn](https://github.com/dotnet/roslyn) that should be on their own release schedules, have their own version numbers, and target the Roslyn 1.0 API and binaries instead of the latest sources in `master`. These projects should be moved to their own repo.

- [ ] Analyzer samples (src/Samples/*/Analyzers)
- [ ] Async analyzers (src/Samples/CSharp/AsyncPackage)
- [ ] AnalyzerPowerPack
- [ ] Microsoft.CodeAnalysis.Analyzers
- [ ] DeclarePublicAPI analyzer
- [ ] Analyzers specifically made for the Roslyn project (?)
- [ ] System.Runtime.Analyzers (?)
- [ ] System.Runtime.InteropServices.Analyzers (?)

Owned by @tmeschter and @tannergooding.
FYI @ManishJayaswal @kuhlenh.

**Comment by tmeschter** [comment]
@ManishJayaswal @srivatsn @mavasani @tannergooding @shyamnamboodiripad @heejaechang @jmarolf Are there any other analyzers that should be moved out to the new repo?

I'm not sure if it makes sense to move the Roslyn-specific analyzers, or the re-implemented FxCop analyzers. I could move them over for the time being.

**Comment by AdamSpeight2008** [comment]
I think it would soon be a good time to separate the different concerns out into their own Repos.
Looking at the structure of the src, I see at least 4 . `Roslyn`, `Compilers`, `IDE`, `Interactive`.

**Roslyn**
This repo is to build the entire roslyn infrastructure
```
dotnet/roslyn
  + build
  + Sample
```

**Compiler**
This repo is build and test the compiler infrastructure only, each language having it's own repo.
```
dotnet/roslyn/compiler
  / CSharp
  / VisualBasic
  / Common+Shared
```

**IDE**
This one is repo is to build and test the IDE / Visual Studio based aspects of Roslyn
```
dotnet/roslyn/IDE+VisualStudio
  + VisualStudio
    + EditorFeatures
```

**Interactive**
This repo is to build and test the aspects of the interactive features.
```
dotnet/roslyn/Interactive+Scripting
  + Interactive
    + InteractiveWindow
  + Scripting
```

It would allow for the people testing new features or fixing bugs, to have quicker build and test times. As they not having build the entire infrastructure each time.

**Comment by AdamSpeight2008** [comment]
Possibly a fifth for `Analyser+Diagnostics`.

**Comment by paul1956** [comment]
I would love to see samples separated since right now I can't get them to build without changes and at least for some of the VB samples getting them to work against the current bits. I opened separate about issues with sample error details.

Sent from my iPhone
I apologize for any typos Siri might have made.
(503) 803-6077

**Comment by tmeschter** [comment]
@paul1956 Are you referring to analyzer samples specifically, or the samples solution in general?

**Comment by tmeschter** [comment]
@AdamSpeight2008 That's a much broader proposal than we are going to tackle with this issue, so I'm not going to address it here.

The primary goal here is to create a home for analyzers the Roslyn team owns but are not part of Roslyn per se.

**Comment by AdamSpeight2008** [comment]
@tmeschter (#3756)

**Comment by paul1956** [comment]
The VB samples https://github.com/dotnet/roslyn/tree/master/src/Samples/VisualBasic, they seem to have conflicting dependencies and even when that is fixed the Code Refactoring ones crash after the light bulb is shown and before the sample gets control back. Details in issue #3710. Just opening https://github.com/dotnet/roslyn/tree/master/src/Samples with Visual Studio 2015 RC gives 1 Error and 273 warnings.

**Comment by srivatsn** [comment]
This is now done.
