### ISSUE TITLE
Intellisense for using static adds an import rather than a full qualification

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#37523]
**Version Used**: VS 16.3 preview 1

**Steps to Reproduce**:

![usingStatic](https://user-images.githubusercontent.com/29174528/62006252-19c1ea80-b136-11e9-814d-cd33a63ecd22.gif)

Make sure "Show Items From Unimported Namespaces" is switched on in `Tools->options->Text Editor->C#->Intellisense`

at the top of a file start typing `using static <SomeType>`
When intellisense shows up for `<SomeType>` press enter.

**Expected Behavior**:

The file now shows 
```csharp
using static <SomeNamespace>.<SomeType>
```

**Actual Behavior**:

The file now shows 
```csharp
using <SomeNamespace>;
using <SomeType>;
```

**Comment by CyrusNajmabadi** [comment]
@genlu Did you just fix this?  Or were you fixing some other issue?

**Comment by genlu** [comment]
Yeah, this should be fixed by https://github.com/dotnet/roslyn/pull/37290, which isn't merged yet.
