### ISSUE TITLE
Recursive Intellisense - similar to search in file manager

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37548]
<p>I think this can be a very useful feature, especially for developers plunging into an unknown codebase.</p> <p>I work on a project with deeply nested classes. Suppose I need to find a property called TemperatureLimit. I type the name of the master parent object, then . Temp... Nothing shows up. TemperatureLimit is actually 5 classes down. Now I have to stop my workflow and start searching in the app (or testing different classes in intellisense using trial and error).  I spent  hours on this once (over 100s of properties) in a new to me app.</p> <p></p><p>I think a tree should be built and guidance should be given if there is a match in any composed class. The text editor should automatically expand the path to the property, and handle multiple similar selections. Essentially it is still working the same way as 1995s Visual Basic 5.0! Lets leverage our Multi-core PCs to save time!</p> <p></p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/564637/recursive-intellisense-similar-to-search-in-file-m.html
VSTS ticketId: 891368_
_These are the original issue comments:_

Jane Wu [MSFT] on 5/13/2019, 02:13 AM (77 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
We do offer intellisense for types outside of hte existing set of imports now.
