### ISSUE TITLE
Order properties alphabetically inside a class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37549]
<p>Can we add an refactoring options where we can order properties alphabetically? Might be a luxury but it can help us understand the class much better.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/567287/order-properties-alphabetically-inside-a-class.html
VSTS ticketId: 892423_
_These are the original issue comments:_

Jane Wu [MSFT] on 5/15/2019, 01:08 AM (75 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
