### ISSUE TITLE
IntelliSense: Exclude current file when including

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37554]
IntelliSense is suggesting the current file when typing an #include statement, which is not useful.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/600638/intellisense-exclude-current-file-when-including.html
VSTS ticketId: 915779_
_These are the original issue comments:_

Jane Wu [MSFT] on 6/11/2019, 00:01 AM (48 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
C# doesn't have `include` statements.  I think this is an issue being reported against the C++ team.  @jinujoseph can you move?

**Comment by jinujoseph** [comment]
routing to C++ team
