### ISSUE TITLE
include naming convention fix ups in code clean up

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37551]
<p>Naming convention rules are being specified in my editor config. For example private fields start with a _. When this rule is violated I get a little light bulb suggestion to fix it for me, great. However there is no option to include this fix in the code clean up profile. It would be a great help if it was</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/580345/include-naming-convention-fix-ups-in-code-clean-up.html
VSTS ticketId: 897571_
_These are the original issue comments:_

Jane Wu [MSFT] on 5/24/2019, 03:44 AM (66 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment]
Related to #14983

**Comment by endasil** [comment]
So, more than a year has passed and this is not implemented yet?

**Comment by CyrusNajmabadi** [comment]
@endasil Correct.  It is on our backlog.

**Comment by HughWarrington** [comment]
Can this even be incorporated into the same workflow? Unlike the other code cleanups, these renames can fail or at least require manual intervention, due to the potential for illegal or clashing identifiers to be produced.

**Comment by CyrusNajmabadi** [comment]
Closing out due to high computation complexity cost.  We are unlikely to do this unless someone can propose a way for it to be done in a cost effective manner.
