### ISSUE TITLE
Quick Action Using Suggestions Should Prefer Local Code

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#37557]
[Original developer community ticket](https://developercommunity.visualstudio.com/content/idea/641744/quick-action-using-suggestions-should-prefer-local.html)

When I do a quick action on something that needs a `using` statement, IMHO, it should prefer my source code over external references.

Example:

![image](https://user-images.githubusercontent.com/8293542/62092333-9e416580-b229-11e9-9a5c-b9d83fe1b55d.png)
but in my source code I have an ILogger that is not showing:
![image](https://user-images.githubusercontent.com/8293542/62092347-ac8f8180-b229-11e9-96a4-04ecb97ab921.png)

I'm assuming it is stopping at three.

**Comment by CyrusNajmabadi** [comment]
Yup.  It's stopping at 3.

**Comment by spottedmahn** [comment]
Would the Roslyn maintainers be open to changing this?  Specifically preferring "my namespaces" over external ones?

When I say "my namespaces", I mean if I'm in code in `Nop.Web.Framework` it would sort the top 3 by `Nop.*` first?

How is the order established now?  🤔

If yes, would you able to point me in the direction of a starting point of where this code is in Roslyn?  Thanks!

**Comment by CyrusNajmabadi** [comment]
I'd personally be fine with it.  Relevant code starts here (where we have the Max defined): 
https://github.com/dotnet/roslyn/blob/553503d9962e184a40fd7dfec4e764c698cb6c1e/src/Features/Core/Portable/AddImport/AbstractAddImportCodeFixProvider.cs#L14

This eventually gets to the 'meat' of searching here: https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs#L129

This will eventually bottom out into a place where we collect and sort the results:  https://github.com/dotnet/roslyn/blob/553503d9962e184a40fd7dfec4e764c698cb6c1e/src/Features/Core/Portable/AddImport/SymbolReferenceFinder.cs#L155

You'll likely want to add some smarts here that, all other things being equal, a source symbol is preferred to a metadata symbol.

I can go into more detail later if you need it.  You're also welcome to come to the dotnet/roslyn channel in gitter to try to get 'live' help.

**Comment by spottedmahn** [comment]
Your guidance is awesome 👏, thanks @CyrusNajmabadi 😊

**Comment by spottedmahn** [comment]
Is there any way to "take this issue over" (assign me as the author)?  When I go to my GitHub issues and filter for me as the author it doesn't show up.  I had to spend a few minutes trying to track this issue down...

**Comment by kendrahavens** [comment]
I'm not sure if we can reassign author of issues on GitHub. Sorry for the inconvenience! I believe making you the assignee is the only option, which may not be what you want.
@sharwell if you know a solution.

**Comment by spottedmahn** [comment]
>I'm not sure if we can reassign author of issues on GitHub

I kinda figured 😢

**Comment by spottedmahn** [comment]
Hi @CyrusNajmabadi - I did some review the code that you pointed me to but I'm not seeing any unit tests around them.  Am I missing them?

Thanks again for pointing me in the right direction!

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
