### ISSUE TITLE
Endless loop in Diagnostics.CompilationWithAnalyzers.GetAnalyzerSemanticDiagnosticsCoreAsync for partial class

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#37567]
**Version Used**: 
VS2019 16.3.0 Preview 1.0 + debug builds of roslyn(master-vs-deps 2320fb7331f83f687fa092a562162b083339612f)

Seems that not happen with the native build of roslyn in VS2019 16.3.0Preview1.0(roslyn 7d47461d2ddd32defbc51c2cf0e75a3fef16c3d7)

**Steps to Reproduce**:
Feel free to close this if only an newer version of VS2019 is needed.

1. Partial class with 3 files needed.
Test.A.cs
```csharp
using System;
using System.Collections.Generic;
using System.Text;

namespace ConsoleApp8
{
    public partial class Test
    {
        int val1 = 1, val2 = 2;
        public void TestA()
        {
            TestB();
        }
    }
}
```
Test.B.cs
```csharp
using System;
using System.Collections.Generic;
using System.Text;

namespace ConsoleApp8
{
    public partial class Test
    {
        public void TestB()
        {
            int val1x = this.val1, val2x = this.val2;
            if (val1x > 0)
            {
                _ = "Do some thing";
            }
            if (val2x > 0)
            {
                _ = "Do some thing";
            }
        }
    }
}
```
Test.C.cs
```csharp
using System;
using System.Collections.Generic;
using System.Text;

namespace ConsoleApp8
{
    public partial class Test
    {
        public void Noop()
        {
        }
    }
}
```

2. Debug `RoslynDeployment`, and open the csproj;
3. Open `Test.B.cs`, wait some seconds, and set an bp at `processPartialSymbolLocationsAsync`, and see it keeps call itself, and each file wait the another two files.
It may also throw a huge number of OperationCanceledException when canceled.

**Expected Behavior**:
The method should finish in a short time.

**Actual Behavior**:
`GetAnalyzerSemanticDiagnosticsCoreAsync`(firstfile) call `processPartialSymbolLocationsAsync` and then call itself with another file.
And `GetAnalyzerSemanticDiagnosticsCoreAsync`(anotherfile) call `processPartialSymbolLocationsAsync` and then call itself with the first file.
...
And that loop forever.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/37623 in `release/dev16.3-preview2` branch. Fix should reach master with regular code flow.
