### ISSUE TITLE
GetDeclarationsInSpan should be public (again)

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#3757]
I own a Roslyn-based code generator that needs to look at all declarations in a source file to determine what code to emit. I was previously using `GetDeclarationsInSpan` for this purpose but recent builds of Roslyn have removed it (or made it internal).

How should I get all declarations for the document? If there is not a good story for this, please consider making this method public again.

**Comment by gafter** [comment]
The story is to get all syntax nodes of the syntax kinds that you want. That is unfortunately not what the API did.

**Comment by AArnott** [comment]
I don't understand @gafter's comment. What is the recommendation here for the scenario of wanting to collect all symbol declarations?

**Comment by gafter** [comment]
Enumerate the nodes of each syntax tree, and filter based on the node's kind. Collect all of the nodes of the specific kinds you are interested in.

An alternative is to use Compilation.WithEventQueue, force the compilation to complete, and pick out the events of interest from the resulting queue. This does not give events for local variable declarations, parameters, range variables, etc.

**Comment by gafter** [comment]
By the way, `GetDeclarationsInSpan` is likely to go away. It is/was a temporary measure while the IDE analyzer driver is being ported to the "one true" analyzer driver.
