### ISSUE TITLE
Proposal: NameOf to have optional parameters.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#3759]
**Proposal: NameOf to have optional parameters.**

Currently.
`nameof(Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider)` = `"CodeFixProvider"`
(See #3708)

To fix this I propose that we should extend **NameOf** with optional parameters. ` , NameOfOptions:=   )`

**NameOfOption Enum**
```vb
Enum NameOfOption As Integer

  [default] = 0
  fullname  = 1

End Enum
```
**Api signature**
``` vb
NameOf(  obj As Object, Optional NameOfOptions As NameOfOption = Nothing ) As String
```

**Example**
```
nameof(Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider, NameOfOptions:= NameOfOption.FullName )
```
This would then provide the fully-qualified name.

It provides a compile-time solution, to what (I believe) requires the use of reflection, or explicitly stating the full name as a string literal. Hence introducing a potential bug if it changes namespace or name.

Does not break existing usage because the parameter is optional.

**Comment by svick** [comment]
In what situations would this be useful?

**Comment by AdamSpeight2008** [comment]
@svick  See #3708.

**Comment by leppie** [comment]
`nameof` is a compile time construct, it has no API.

A better solution would be to use pragmas to control the output/options.

**Comment by paulomorgado** [comment]
That has been largely discussed on Codeplex.

It was even discussed `FullNameOf`.

**Comment by hishamco** [comment]
@svick this may useful in ``Exception``` when the argument is property path, have a look to this https://github.com/aspnet/WebSockets/commit/208fa4af366e23b51f2b943f709e00b6d48eec22#diff-2f20d3473af8bc60eee727dd88bbb804R595

**Comment by Eilon** [comment]
The parameters to argument exceptions are never "property paths" - they are *parameter names*. Passing in `foo.Bar.Baz` to an `ArgumentException` is *invalid*.

**Comment by whoisj** [comment]
What is wrong with `$"The name is {nameof(value)} and its type is {typeof(value)}, and the type's full name is {typeof(value).FullName}."`?

**Comment by hishamco** [comment]
@Eilon that's exactly what I mean ```foo.bar.baz``` :smile:

**Comment by Eilon** [comment]
@whoisj that's exactly what I recommend people to use.

**Comment by whoisj** [comment]
@Eilon I know. My comment was towards the original post. :smirk:

**Comment by hishamco** [comment]
I don't think so that will applicable for ```value.Length``` where ```value``` is ```String```

**Comment by whoisj** [comment]
> I don't think so that will applicable for value.Length where value is String

What won't be?

Given void 'MyFunc(string value)'

* `nameof(value) == "value"`
* `typeof(value) == System.String`
* `nameof(value.Length) == "Length"`
* `typeof(value.Length) == System.Int32`

**Comment by hishamco** [comment]
@whoisj our intend to display something like ```foo.Bar.Baz``` using ```nameof``` which is an implementation limitation :(

**Comment by whoisj** [comment]
@hishamco then I go back to my original statement: what is wrong with `$"{nameof(foo)}.{nameof(foo.Bar)}.{nameof(foo.Bar.Baz)}"` ?

**Comment by hishamco** [comment]
Looks good trick :smile:

**Comment by svick** [comment]
@AdamSpeight2008 So this is just a performance optimization of `typeof(CodeFixProvider).FullName`? That doesn't sounds like it would be worth inventing new syntax to me.

**Comment by whoisj** [comment]
> @AdamSpeight2008 So this is just a performance optimization of typeof(CodeFixProvider).FullName? That doesn't sounds like it would be worth inventing new syntax to me.

I said the same thing, they're not looking for `Type.FullName`, they're looking for the texted used in the parameter validation. Example:

```
if (foo.Bar.Baz == null) throw new NullArgumentException(nameof(foo.Bar.Baz));
```

They want to see "foo.Bar.Baz" returned by the `nameof` macro, but they're only getting "Baz".

**Comment by leppie** [comment]
I agree with @svick . Also some syntax sugar for `typeof(Foo).Fullname` cannot be resolved reliably at compile-time, so there is no optimization to be had.

**Comment by AdamSpeight2008** [comment]
@leppie 
> cannot be resolved reliably at compile-time?

How? Doesn't the compiler currently do type-checking at compile-time, which suggests to me the the fully qualified name is also available..

**Comment by leppie** [comment]
@AdamSpeight2008 typeof only loads the type token as determined at compile time, fullname would be constant string. Now imagine some AOP process changing something, etc. If something bad happened, peverify will say the type token is now invalid, but with a string, all bets are off. Perhaps this will never happen, but who knows?

**Comment by gafter** [comment]
Regardless of whether we would ever provide support for getting a fully qualified name (seems unlikely), we would not do it in the way requested here.
