### ISSUE TITLE
Master branch intermittently fails to build in 16.3.0-p1.0, empty error list, buggy build output

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#37601]
This happens occasionally across reboots of VS and I don't know what it correlates with. Note the status bar and the error count in the error list:

![image](https://user-images.githubusercontent.com/8040367/62172658-08790980-b301-11e9-896a-f7038ec91d74.png)

The build output summary says `Build: 152 succeeded, 1 failed, 17 up-to-date, 0 skipped`, but no line before it mentions a failure:
https://pastebin.com/raw/R06g7bfK

@sharwell, @jasonmalinowski at Cyrus' request

Help > About > Info:

<details>

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.3.0 Preview 1.0
VisualStudio.16.Preview/16.3.0-pre.1.0+29123.89
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA632
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.3.34.53219
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.34.53219
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.34.53219
Azure App Service Tools v3.0.0

C# Tools   3.3.0-beta1-19360-03+7d47461d2ddd32defbc51c2cf0e75a3fef16c3d7
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.9.1.7781
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ReviewsToolWindow Extension   1.0
ReviewsToolWindow Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61906.28070
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10627.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.0-beta1-19360-03+7d47461d2ddd32defbc51c2cf0e75a3fef16c3d7
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19321.6+5289eb027336eb4c1ea70eaff246f42ca5584b4d
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

</details>

**Comment by jinujoseph** [comment]
@ryzngard

**Comment by jnm2** [comment]
[Normal-verbosity log.txt](https://github.com/dotnet/roslyn/files/3449297/Normal-verbosity.log.txt) just in case it helps

**Comment by jnm2** [comment]
Here are two of the failing binlogs where the build summary was `========== Build: 21 succeeded, 20 failed, 129 up-to-date, 0 skipped ==========` but none of the build output before it showed a failure. (GitHub doesn't like unzipped things)

[Microsoft.CodeAnalysis.LanguageServer.Protocol.UnitTests_Debug_AnyCPU_Build_2019-07-30T20_56_34.4442135-04_00.binlog.zip](https://github.com/dotnet/roslyn/files/3449349/Microsoft.CodeAnalysis.LanguageServer.Protocol.UnitTests_Debug_AnyCPU_Build_2019-07-30T20_56_34.4442135-04_00.binlog.zip)
[Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.UnitTests_Debug_AnyCPU_Build_2019-07-30T20_56_34.5272135-04_00.binlog.zip](https://github.com/dotnet/roslyn/files/3449350/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.UnitTests_Debug_AnyCPU_Build_2019-07-30T20_56_34.5272135-04_00.binlog.zip)

**Comment by jasonmalinowski** [comment]
Also tagging @dotnet/project-system if they have any ideas.

**Comment by ryzngard** [comment]
@jnm2 afaict this isn't happening anymore. I tested a few times in 16.3 and wasn't able to reproduce. Let me know if you still hit issues like this and we can reopen.
