### ISSUE TITLE
Publish 1.0 version of Roslyn nuget packages to nuget.org

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#3761]

**Comment by aelij** [comment]
Seems like the packages have been published. Hurray!

You may want to update their release notes, which currently say "Preview of Microsoft .NET Compiler Platform (Roslyn)" and the license link on NuGet, which points to a pre-release license.

**Comment by jmarolf** [comment]
https://www.nuget.org/packages/Microsoft.CodeAnalysis/
