### ISSUE TITLE
Ability to get 'Go to all' results to new window

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#37617]
I was using Ctrl+T 'Go to all' to find methods whose name ended in `OrNullable`. There were quite a few and as I navigated to each one, I had to continually redo the Ctrl+T and retype or paste and try to avoid going to one I had seen before.

It would be nice if there was a button that would open a window just like Find All References or Find Results that would stay open until I close it.

**Comment by sharwell** [comment]
@olegtk would this be editor?

**Comment by gundermanc** [comment]
Yes, this sounds like a VS platform enhancement. @jnm2 can you please file a Developer Community request? We generally take our feature requests through there for better transparency.

**Comment by jnm2** [comment]
Done: https://developercommunity.visualstudio.com/idea/672372/ability-to-get-go-to-all-results-to-new-window.html

Should this issue be closed?
