### ISSUE TITLE
Unloading large c# solutions are slow again

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37616]
This used to be heavily improved and fast but something has happened with later versions which has made it slow again.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/668659/unloading-large-c-solutions-are-slow-again.html
VSTS ticketId: 957603_
_These are the original issue comments:_

Visual Studio Feedback System on 7/30/2019, 09:40 PM (12 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I've noticed this too.  Note: i don't even know why this needs to do any work.  We're closing the solution.  After files are saved (or not), there's nothing roslyn needs to do at all.

**Comment by jasonmalinowski** [comment]
So when the solution is being closed, the project system closes it project-at-a-time. When one gets removed, that causes us to convert any project references back to metadata references for the projects that haven't been closed yet. If we knew that all the projects were going away then yes we'd be in the optimal case but that's not how it works today.

**Comment by CyrusNajmabadi** [comment]
>  If we knew that all the projects were going away then yes we'd be in the optimal case but that's not how it works today.

Doesn't VS broadcast that this is happening?

> When one gets removed, that causes us to convert any project references back to metadata references for the projects that haven't been closed yet.

Can we do that conversion asynchronously?  That way all that work can be canceled once things actually get removed?

@davkean is tehre something the project system can do to help roslyn out here?

**Comment by jasonmalinowski** [comment]
> Doesn't VS broadcast that this is happening?

VS broadcasts it, but I don't know that just because a solution is being closed that all the projects are going to go away within that timeframe either due to other asynchrony or that somebody might have made a project for something else that isn't really part of the solution. Even then, this being slow would also imply that unloading projects isn't as fast as it could be either.

The work is only expensive by accident though; I suspect we can just fix the inefficiencies directly. I did work to make the solution _open_ case much faster; I didn't do the close case because it's a bit tricker, and well, priorities. :smile: I don't think the project system needs to give us something here.

**Comment by CyrusNajmabadi** [comment]
I guess i don't understand why *any* work is being done.  :)   User said "quit vs".  That should basically only deal with dirty files (and honestly, a modern app just closes even with dirty files, allowing the user to deal with that next time around).  And then the app should literally just 'exit'.  I have no idea why the project system or roslyn is even getting involved.  Do we do any computation on exit that is actually necessary or benefits the user in some way?

**Comment by CyrusNajmabadi** [comment]
Oh sorry.  To be clear: i'm talking about VS-exit, not just the case of solution-unload.  Having the latter be better would be nice (in the cases where i need to reload roslyn).  However, the former is also pretty terrible.

**Comment by davkean** [comment]
We should probably have fast paths for the cases on VS exit vs. solution unload. We don't today.

**Comment by jasonmalinowski** [comment]
Yeah, I recall "let's just save files and TerminateProcess" being discussed as an optimization for VS2010...so that's not new. In any case, that's fairly off topic for this bug in that there's specific optimizations we believe we can make that have other benefits too.

**Comment by jasonmalinowski** [comment]
@sharwell has been looking at improvements here, so moving over to him.

**Comment by sharwell** [comment]
Yes, my pull request for updating the project dependency tracker will fix this issue.
