### ISSUE TITLE
VB Winforms project Form event doesn’t generated correctly when add the Form event from form.vb code page

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/roslyn#37621]
* .NET Core Version: 3.0.100-preview8-013587 from Master branch
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
All Form events have the same issue when add Form events by this way.

**Actual behavior:** 
A not defined type NullableAttribute added in Form1_Load event, it caused the project cannot be built successfully.  
![Actual](https://user-images.githubusercontent.com/45864985/62122366-18402000-b2f8-11e9-89ea-f1b20100d67c.png)

**Expected behavior:**
There Form1_Load event should be generated correctly.   
![Expected](https://user-images.githubusercontent.com/45864985/62122380-1fffc480-b2f8-11e9-9e58-f7f7eaecabd2.png)

**Minimal repro:**
1.	Install the .NET Core 3.0 SDK from https://github.com/dotnet/core-sdk for Master branch.
2.	Create a template of VB Winforms .NET Core app in VS.
3.	Open From1.vb file, select the **(Form1 Events)** in the second comboBox of the top, and select the **Load** in the third comboBox.
![Steps2](https://user-images.githubusercontent.com/45864985/62122327-0199c900-b2f8-11e9-9d5f-95f116b0ca83.png)

**Comment by jasonmalinowski** [comment]
@sharwell being contributor in both was able to do it. Thanks Sam.
