### ISSUE TITLE
Refactoring to generate InvalidEnumArgumentException

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#37654]
This is typically:

```cs
if (!Enum.IsDefined(typeof(Foo), foo))
    throw new InvalidEnumArgumentException(nameof(foo), (int)foo, typeof(Foo));
```

It probably shouldn't be offered on flags enums.

**Comment by ryzngard** [comment]
Design Review: It's generally believed that this pattern is not ideal. `Enum.IsDefined` is expensive in framework. May have been improved in dotnet core. Would need guidance from dotnet team to consider, likely would not take as a refactoring.
