### ISSUE TITLE
Incorrect code generation for using declarations with object initializers?

### ISSUE THREAD

**Issue by KrisVandermotten** [dotnet/roslyn#37655]
**Version Used**: Visual Studio 2019 Version 16.2.0

**Steps to Reproduce**:

Consider the following code:

    using System;

    internal sealed class Disposable : IDisposable
    {
        public string Property { get; set; }
        public void Dispose() { }
    }

    internal static class Program
    {
        using var disposable = new Disposable
        {
            Property = args[2]
        };
    }

Compile the code using

    <Project Sdk="Microsoft.NET.Sdk">

      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <LangVersion>8.0</LangVersion>
      </PropertyGroup>

    </Project>

**Actual Behavior**:

In Debug mode, the Main method is compiled to

	.method private hidebysig static 
		void Main (
			string[] args
		) cil managed 
	{
		.maxstack 4
		.entrypoint
		.locals init (
			[0] class Disposable
		)

		IL_0000: nop
		IL_0001: newobj instance void Disposable::.ctor()
		IL_0006: dup
		IL_0007: ldarg.0
		IL_0008: ldc.i4.2
		IL_0009: ldelem.ref
		IL_000a: callvirt instance void Disposable::set_Property(string)
		IL_000f: nop
		IL_0010: stloc.0
		.try
		{
			IL_0011: leave.s IL_001e
		}
		finally
		{
			IL_0013: ldloc.0
			IL_0014: brfalse.s IL_001d

			IL_0016: ldloc.0
			IL_0017: callvirt instance void [System.Runtime]System.IDisposable::Dispose()
			IL_001c: nop

			IL_001d: endfinally
		}

		IL_001e: ret
	}

This code has a problem, as the Dispose method on the newly constructed object will never be called in the event that `args[2]` (or the assignment to the property) throws.

The code is lowered to something along the lines of

    var temp = new Disposable();

    temp.Property = args[2];

    using (var disposable = temp)
    {
    }

I believe it should be lowered to the equivalent of

    using (var temp = new Disposable())
    {
        temp.Property = args[2];

        var disposable = temp;
    }

I do understand that the currently generated code is very similar to what is generated for the following:

    using (new Disposable
    {
        Property = args[2]
    })
    {
    }

This code has the same problem. However, modifying the generated code for a using statement would introduce breaking changes. We still have the opportunity to generate better code for using declarations.

Notice also that IDE0017 is offered on

    private static void Main(string[] args)
    {
        using var disposable = new Disposable();

        disposable.Property = args[2];
    }

Many developers will assume that this code is equivalent to the code with the object initializer, especially since Visual Studio offers a code fix to convert this code to the code using an object initializer.

If you feel the generated code is as intended, then I suggest IDE0017 is not offered on using declarations.

**Comment by gafter** [comment]
This behavior is required by specification.  See https://github.com/dotnet/csharplang/blob/master/spec/statements.md#the-using-statement for the old form of the try statement.  The spec for the new form is similar.

**Comment by KrisVandermotten** [comment]
@gafter That's what I feared, however I was under the impression that the spec for the new form was not finalized.

That being said, if it is, can we at least not offer IDE0017 on using declarations?

**Comment by CyrusNajmabadi** [comment]
@KrisVandermotten Please file another issue for that.

**Comment by KrisVandermotten** [comment]
@CyrusNajmabadi New issue #37675 created.
