### ISSUE TITLE
Completion doesn't appear for expression statements above variable declaration statements

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#37659]
**Version Used**: 
3.3.0-beta2-19375-02

**Steps to Reproduce**:

```cs
public class C
{
    public void M(string s)
    {
        s. // no completion
        var o = new object;
    }
}
```

**Expected Behavior**:
Completion list after `s.`

**Actual Behavior**:
No completion list

- Changing `var o` to `object o` seems to fix it in this particular scenario
- Changing `s.` to `_ = s.` seems to fix it

/cc @333fred @jasonmalinowski @ivanbasov

**edit**: this works in public preview with version 3.3.0-beta1-19360-03

**Comment by ivanbasov** [comment]
@RikkiGibson I could not reproduce it with .net core 3.0.0 which is public available.

1. Could you please share the sample solution?
2. The latest avaiable verison here https://dotnet.microsoft.com/download/dotnet-core/3.0 is 3.0.0-preview. Please share the download location for 3.3.0
3. I can assume that language services may failed to load in the solution when you tried the completion. Then, no completion could be provided at all. Is it the case?

**Comment by CyrusNajmabadi** [comment]
This normally happens due to an ambiguity in parsing.  Specifically `s.var` is parsed as a type.  That said, we have explicit logic in completion to handle this very common case.

**Comment by RikkiGibson** [comment]
We found that the completion list would not show up in my environment for these two cases:

```cs
s. // no completion
var o = new object();
```

```cs
s. // no completion
Object o = new object();
```

```cs
s. // shows completion
object o = new object();
```

Looking at the syntax trees produced, the one that shows completion parses `s.` as an incomplete MemberAccessExpressionSyntax while the others parse `s.var` and `s.Object` as QualifiedNameSyntax.

This seems to support a hypothesis that the logic that checks for whether a qualified name should be treated like an incomplete member access has a regression.

For some reason, we're not able to reproduce the issue on Ivan's machine yet, but we were able to reproduce on Fred's machine.

**Comment by CyrusNajmabadi** [comment]
Can we not replace fred's computer with ivan's?

**Comment by ivanbasov** [comment]
The difference between computer is with the option `Enable nullable reference analysis IDE Features`. The bug can be reproduced with the settings ON and there is no issue when the setting is OFF.

The semantic model interprets the code different way depending on the option.
Here https://github.com/dotnet/roslyn/blob/ae4d2e799f69868e707d381451d3f55769f24c67/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs#L737
we get for `s` after typing dot
- BoundParameter if the option is OFF
-BoundTypeExpresison if the option is ON.
Need help by the @dotnet/roslyn-compiler

**Comment by ivanbasov** [comment]
@333fred could you please take a look?

**Comment by 333fred** [comment]
@ivanbasov what's calling the AttributeSyntax overload of GetSpeculativeSymbolInfo? Can you give me example arguments? I'm mostly oof today and Monday, so I may not be able to look at this before Tuesday afternoon.

**Comment by ivanbasov** [comment]
Sorry @333fred !
I pointed to a wrong line. The right one is https://github.com/dotnet/roslyn/blob/ae4d2e799f69868e707d381451d3f55769f24c67/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs#L707

This one is called with `IdentifierName s` and `bindingOption = BindAsExpression`.

Please let me know if you need more info.
