### ISSUE TITLE
XML documentation tooltips should include hyperlinks for <see> tags, <exception> tags, etc.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37657]
For instance I have this XML doc:

```
/// &lt;summary&gt;
/// A comma delimited list of flags from the &lt;see cref=&quot;DeleteReferralFlags&quot;/&gt; enumeration.
/// &lt;/summary&gt;
string Flags { get; }
```

When I hover over a reference to the Flags property, DeleteReferralFlags appears in blue, but it would be nice if it were a hyperlink to the documentation on that enum.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/662082/xml-documentation-tooltips-should-include-hyperlin.html
VSTS ticketId: 952756_
_These are the original issue comments:_

Jane Wu [MSFT] on 7/25/2019, 09:51 PM (6 days ago): <markdown><p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>
</markdown>

**Comment by sharwell** [comment]
This was fixed by #35667 for the upcoming 16.3 release. 👍
