### ISSUE TITLE
Bad refactoring -- convert to LINQ

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37661]
My code snippet that compiles fine as is, is:

```cs
			int SumDurations = PatternDurations.Sum(p =&gt; Convert.ToInt32(p.Duration));
			var Rates = new List&lt;(int div, int rate)&gt; { (24, 4), (12, 8), (6, 16) };
			foreach (var item in Rates) {
				int quot = Math.DivRem(SumDurations, item.div, out int rem);
				if (rem == 0) {
					SetTimeSignature(quot, item.rate);
					return quot;
				}
			}
```

When I apply Convert to LINQ to the foreach loop, I get red squigglies as follows (using bold for squigglies), and it fails to compile with the message: CS8130	Cannot infer the type of implicitly-typed deconstruction variable 'item'. and ditto for quot and rem.	G:\LRS\$Dev\C#\$Tony\RhythmAndClues\Interpreter.cs. This problem occurs on VS2019, 16.0.1
 
```cs
			foreach (var (**item**, **quot**) in from item in Rates
										 let quot = Math.DivRem(SumDurations, item.div, out int rem)
										 where **rem** == 0
										 select (item, quot)) {
				SetTimeSignature(quot, item.rate);
				return quot;
			}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/540726/bad-refactoring-convert-to-linq.html
VSTS ticketId: 852120_
_These are the original issue comments:_

Visual Studio Feedback System on 4/22/2019, 01:42 AM (101 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
