### ISSUE TITLE
Generate type is not offered in top-level statements

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#3766]
`Unknown u = null;`

VS should offer to generate a type called "Unknown".

**Comment by amcasey** [comment]
Part of #3754.

**Comment by amcasey** [comment]
It does seem to work in non-top level statements in script files.

**Comment by CyrusNajmabadi** [comment]
This seems to work now.  Closing out:

![image](https://user-images.githubusercontent.com/4564579/198708281-ef9dd199-9abf-4d08-bda6-7145ed198046.png)
