### ISSUE TITLE
Quickwatch evaluation of a tuple in a test results in a NullReferenceException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37662]
Create a DLL project, full net framework, and add a unit test project to the solution. In the DLL project, add the following types

```    
public enum MuhEnum
{
    Whatever
}
public class MuhClass
{
    public List&lt;(string, MuhEnum, Exception)&gt; Items = new List&lt;(string, MuhEnum, Exception)&gt;();
    public MuhClass()
    {
        Items.Add((&quot;Why am I null when quickwatching?&quot;, MuhEnum.Whatever, null));
    }
}
```
You can clearly see that Items[0]. Item1 is not null nor will it ever be null unless explicitly set as null. Now, add the following unit test

```
[TestMethod]
public void TestMethod1()
{
    var target = new MuhClass();
    Assert.IsTrue(target. Items[0]. Item1.Contains(&quot;quickwatch&quot;), &quot;Debug this test, quickwatch Target and try to evaluate target. Items[0]. Item1.Length&quot;);
}
```
Debug this test's Assert. It will evaluate to true, but if you quickwatch ```target. Items[0]. Item1``` it will be reported as being null. Attempting to use it in the quickwatch, such as ```target. Items[0]. Item1.Length``` results in an NRE.

I haven't tested to see if this exact type of tuple is the magic sauce needed but I have repro'd it outside of where I discovered it.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/539009/quickwatch-evaluation-of-a-tuple-in-a-test-results.html
VSTS ticketId: 850494_
_These are the original issue comments:_

Visual Studio Feedback System on 4/18/2019, 08:20 PM (104 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by WillSullivan** [comment]
This was my bug report. Ping me if you have questions.

**Comment by gafter** [comment]
Dup of https://github.com/dotnet/coreclr/issues/25519
