### ISSUE TITLE
Feature request: Type hint when `var` is used

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/roslyn#37676]
I've found out this extension that shows what the actual type when `var` is used: https://marketplace.visualstudio.com/items?itemName=AlexanderGayko.VarAdorner
![image](https://user-images.githubusercontent.com/42944058/62374221-6f532880-b576-11e9-9f3f-e14493439a8b.png)

It's pretty neat, and would be a great addition if similar features can be implemented in the Visual Studio!

**Comment by mikadumont** [comment]
Design meeting notes: We will not implement it yet because we think it will be more discoverable as an extension rather than having it off by default.
