### ISSUE TITLE
BasicEditAndContinue Integration Tests Failing

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#37689]
A recent update to the preview version of Visual Studio that is used for integration tests has caused Basic EnC tests to consistently fail.

- [x] Make integration tests not required for PRs
- [x] Add skips for these tests and flow through
- [x] Make integration tests required for PRs
- [ ] Unskip these tests when a fix is in place.

**Comment by CyrusNajmabadi** [comment]
Amazing!
