### ISSUE TITLE
Allow user to set opacity for fading in text editor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37682]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/idea/659234/allow-user-to-set-opacity-for-fading-in-text-edito.html)._

---
When fading unused usings and private methods, allow the user to customise level of opacity used to fade the text to improve readability.

---
#### Fiona Niu[MSFT] on 7/24/2019, 00:48 AM: 

We have converted this feedback item from problem to idea. This change was done to better reflect the feedback's nature. It will allow other developers to easily find it and engage on it.
#### Jane Wu [MSFT] on 7/25/2019, 02:16 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by sharwell** [comment]
@olegtk This is handled by the platform right?

**Comment by olegtk** [comment]
No, it's controlled by Roslyn's UnnecessaryCodeFormatDefinition: https://github.com/dotnet/roslyn/blob/f8a02232b4ed96ad35e6fdee20d313c44964aaac/src/EditorFeatures/Core.Wpf/Diagnostics/UnnecessaryCodeFormatDefinition.cs#L26

**Comment by CyrusNajmabadi** [comment]
Diagnostic fading is now handled by LSP client.  Any roslyn code on this will go away with the switch to turn LSP on fully.
