### ISSUE TITLE
Support Nullable reference syntax in 7.X

### ISSUE THREAD

**Issue by davidhunter22** [dotnet/roslyn#37708]
I would love to switch on and use the new nullable reference stuff in 8.0. However 8.0 is not production yet and it will be a while before we switch to it even when it is. So I was wondering if it possible to at least accept and ignore the syntax in a 7.X compiler. That way  I can add all the "?" annotations to the code and get the checking benefit right now when using 8.0 but quietly ignore them when compiling production.
So this is not a request for a full back port just a switch to accept and completely ignore the syntax which I assume is simpler.

**Comment by PathogenDavid** [comment]
>However 8.0 is not production yet

From [Building C# 8.0](https://devblogs.microsoft.com/dotnet/building-c-8-0/):

> The current plan is that C# 8.0 will ship at the same time as .NET Core 3.0.

As far as I'm aware that's still the plan. .NET Core is slated to launch during [.NET Conf 2019](https://www.dotnetconf.net/), which is happening this September 23-25.

> and it will be a while before we switch to it even when it is.

Why are you so eager to start adopting nullability annotations but you're hesitant to adopt new language versions?

**Comment by davidhunter22** [comment]
I hadn't realized C# 8 was that imminent.
I am eager to use nullability annotations as my experiments with them uncovered a couple of bugs in our code and I suspect will find more. 
I'm not hesitant to adopt the new language version I am keen to do so, unfortunately in a commercial setting I am not able to do so unilaterally and as in many companies these changes often take months.

**Comment by PathogenDavid** [comment]
Yup, [Microsoft will even support you if you use Preview 7 in production](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-7/#user-content-go-live).

**Comment by gafter** [comment]
If you use the "experimental" language version in the most recent previews, you can use the C# 8 features.  But no, we are not going to change the C# 7.x languages now.
