### ISSUE TITLE
Improve diagnostics when the project is not restored yet

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#37717]
When a solution is opened in VS that is not restored yet, there can be hundreds of errors on missing built-in types. This can also happen when a sdk is missing so a mere restore won't resolve errors either. 

In this state, navigation on user-code does work but there will be so many IDE squiggles that make it hard to even browse/read the code. Could we improve experience by not emitting all the errors when a design-time build is not possible at the moment?

**Comment by CyrusNajmabadi** [comment]
Tagging @heejaechang @mavasani @jinujoseph I would def also like this as well.  Note: it used to be a lot worse and i haven't noticed it as much.  But it def still happens occasionally and is pretty unpleasant.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/66569.
