### ISSUE TITLE
different forms of double.MaxValue/MinValue might be recognised as out of range

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/roslyn#37719]
**Version Used**: 
Using Microsoft.Scripting.CSharp.Scripting package, version 3.3.0-beta2-19376-02(fc001df5)
**Steps to Reproduce**:

1. Copy the values returned from double.MaxValue/MinValue.ToString (which by default is "R"), which is printed as (+/-)1.79769313486232E+308 on .NET Core 3.0 P7.
2. Try to use the value as a floating point literal in codes

**Expected Behavior**:
Should compile fine.

**Actual Behavior**:
Fails to compile with the error CS0594 "Floating-point constant is outside the range of type 'double'".

The [System.Double source](https://github.com/dotnet/coreclr/blob/86d56cee7311dcf07e4ec3149c364da40c25ba87/src/System.Private.CoreLib/shared/System/Double.cs#L35) uses (+/-)1.7976931348623157E+308 instead. Feeding the value from ToString to Parse straight away (`double.Parse(double.MaxValue.ToString())`) seems to work fine without exceptions, which makes me believe the CoreLib should be IEEE compliant.... but @tannergooding probably knows better there. :smile:

**Comment by CyrusNajmabadi** [comment]
> Fails to compile with the error CS0594 "Floating-point constant is outside the range of type 'double'".

This makes sense to me.  The value is too large.  I think you need to use the `G17` format specifier.  That will give you the right value that can be used in a C# program.  Note that the docs are clear on this:

![image](https://user-images.githubusercontent.com/4564579/62431354-c32b5200-b6db-11e9-91e9-de23a284c0ce.png)

**Comment by Gnbrkm41** [comment]
Turns out to be some local issues, my bad 🤦‍♂️

**Comment by tannergooding** [comment]
> Turns out to be some local issues, my bad

I was about to say, this looks like the .NET Framework and pre 3.0 value returned by `double.ToString()`. The default of `double.ToString()` is also not `R`, but `G`. On older versions of the framework, `G` defaults to `G15`. On new versions of the framework (.NET Core 3.0 and later), it defaults to an equivalent of 'R' (but 'G' is still passed in under the covers).

I had done a brief blog on this here: https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/

**Comment by tannergooding** [comment]
(One of the bugs called out in the blog post, also covers `double.MinValue` and `double.MaxValue` not roundtripping by default on older versions of the framework).

**Comment by Gnbrkm41** [comment]
Good to know, sorry for the ping!
