### ISSUE TITLE
How can I get IdentifierNameSyntax from VariableDeclarationSyntax?

### ISSUE THREAD

**Issue by ndung** [dotnet/roslyn#3772]
Hi, I have question. How can I get IdentifierNameSyntax from VariableDeclarationSyntax? Because I want to get the Type from field declaration... Thank you.

**Comment by hvanbakel** [comment]
You will need to call `GetTypeInfo` on your semantic model to get the type of (given node is of type `FieldDeclarationSyntax'):
node.Declaration.Type

**Comment by ndung** [comment]
Thanks @hvanbakel
