### ISSUE TITLE
XML documentation feature: Embeding <see href=""/> link into VS doc hint window

### ISSUE THREAD

**Issue by sunkin351** [dotnet/roslyn#37720]
I wish to have the ability to embed a link in (what others are telling me to call) the "parameter info box" that shows you the summary of the XML documentation when you hover over a Type or type member. I want to embed a link to the official documentation of a class or member that's clickable from the hint window.

An example:
```cs
/// <summary>
/// My Function. <see href="http://www.example.com/path/to/documentation.xml">See this documentation</see>
/// </summary>
public static void MyFunction()
{
}
```

If this isn't possible, please explain why. ^^ It would be awesome to have this.
Edit: This is an IDE feature request btw

**Comment by CyrusNajmabadi** [comment]
Strange.  This works just fine for me:

![image](https://user-images.githubusercontent.com/4564579/62440899-ef0ffd00-b706-11e9-9587-83c3f052ea4a.png)

**Comment by sunkin351** [comment]
How do you keep the window from disappearing? I can't seem to interact with it.

**Comment by sharwell** [comment]
@sunkin351 This was added for the upcoming 16.3 release, and will ship for the first time in 16.3 Preview 2. Cyrus is using an unpublished preview release that he built from source.

**Comment by sharwell** [comment]
Duplicate of #37657
