### ISSUE TITLE
ErrorLogger converts relative paths to incorrect URIs

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#37737]
> Looking at it in the debugger, the problem is that [this code](https://github.com/dotnet/roslyn/blob/548db2b498394680f4384a5c59125037312f1a56/src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs#L143) in Roslyn creates a System.Uri for the path, and URIs have different path normalization rules than paths (intentionally—see dotnet/corefx#31524).

> That transforms the legal path

> `S:\VS\src\vset\Agile\TestPlatform\sdk\ObjectModel\cs\\..\DataCollectorSettings.cs`

> into

> `file:///S:/VS/src/vset/Agile/TestPlatform/sdk/ObjectModel/cs/DataCollectorSettings.cs`

> which is also legal, but doesn’t point to the same place.

**Comment by rainersigwald** [comment]
The input path has to have an empty path segment; the original was:

```
S:\VS\src\vset\Agile\TestPlatform\sdk\ObjectModel\cs\\..\DataCollectorSettings.cs
```

The double slash is important. I believe URI handles `\..` fine.

**Comment by agocke** [comment]
Yeah, looks like that was being treated as an escape by GitHub, which is likely the problem in the ErrorLogger itself.
