### ISSUE TITLE
VS2017 Debugging - Use the legacy C# and VB Expression Evaluators - Deprecated

### ISSUE THREAD

**Issue by alphonseg** [dotnet/roslyn#37759]
**Version Used**: VS 2017 15.9.14

**Steps to Reproduce**:
With Use the legacy C# and VB Expression Evaluators, unchecked
1. `Dim strTest as String = <someobjectValue> & vbcrlf & <someotherobjectvalue>`
2. Debug and set breakpoint on next line.
3. In Immediate window type `?strTest`.
**Expected Behavior**: Display `"firstvalue secondvalue"`

**Actual Behavior**: Displays `"firstvalue" & vbcrlf & "secondvalue"`

It is necessary to have the expected behavior for many debugging reasons.
Either have the new version display properly or leave in the legacy option.

**Comment by tmat** [comment]
Why is it necessary?

**Comment by alphonseg** [comment]
While debugging, it is sometimes necessary to evaluate the content of a variable - in order to debug.
This is common. One thing in particular, when working with databases, string together parameters for a stored procedure, which can sometimes be quite long. Evaluate in in the Immediate window, then copy the value to SQL Server Management Studio and run (and/or debug) the proc there, using the same exact values that the app was supplying. SSMS can't evaluate "firstvalue" & vbcrlf & "secondvalue".

**Comment by alphonseg** [comment]
Sorry, my first time posting here and accidently closed it.

**Comment by tmat** [comment]
Why wouldn't you use `<someobjectValue> & " " & <someotherobjectvalue>` instead of `vbcrlf` though?

**Comment by alphonseg** [comment]
Like everything else, it depends. Maybe it's a string will be presented to a user, added to a memo, email, etc. In the case of SQL parameters, makes it easier to read. There are lots of reasons. However, I can't think of one reason why anyone would want to see the construct. It is also common sense, If the value of an object is asked for, that is what should be provided - the value - not the internals.

**Comment by alphonseg** [comment]
Like everything else, it depends. Maybe it's a string will be presented to a user, added to a memo, email, etc. In the case of SQL parameters, makes it easier to read. There are lots of reasons. However, I can't think of one reason why anyone would want to see the construct. It is also common sense, If the value of an object is asked for, that is what should be provided - the value - not the internals.

**Comment by tmat** [comment]
> Like everything else, it depends

Indeed. But you as the author of the expression know how you want the string to be presented. The debugger does not know what are you gonna do with the output.

>  I can't think of one reason why anyone would want to see the construct

When you're debugging an issue with code that outputs incorrect white space into a string you'd want to see the exact kind of white space that is actually present in the string, so printing line break as a space would be confusing in that case. You wouldn't know if the original string contained the line break or not.

**Comment by alphonseg** [comment]
We could go around forever. Obviously, there are always different needs. Because of that, why not let the developer display it the way needed at the time?

**Comment by tmat** [comment]
How should we determine "the way they needed"?

**Comment by alphonseg** [comment]
There are the 2 methods that we have discussed. All I'm saying is to leave (or provide in some other way), the option to decide which we want to use. The expression evaluator is deprecated. Either don't deprecate it or provide a new setting to output strings the old way.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and movement here.
