### ISSUE TITLE
Implement an analyzer to remove unused references

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#37769]
IDE task which is a part of https://github.com/dotnet/roslyn/issues/6763

The analyzer depends on 
 - the compiler API (https://github.com/dotnet/roslyn/issues/37768) for unused references
 - the file generated by MS Build which will provide dependencies between references and packages and point which 'unused' references are actually transitively used.
 - the project-system API (for the analyzer fixer)

The analyzer should report which references are actually could be removed. The fixer should allow removing them.

**Comment by ivanbasov** [comment]
Blocked by https://github.com/dotnet/roslyn/issues/37768

**Comment by Youssef1313** [comment]
This is implemented now. I think it could be closed.

**Comment by CyrusNajmabadi** [comment]
@JoeRobich good to close?
