### ISSUE TITLE
Warning diagnostics escalated to errors doesn't block emitting the output

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#37779]
**Version Used**: Version 16.3.0 Preview 3.0 [29205.144.master], Roslyn part is 3.3.0-beta2-19401-05+8ed56b826700926009731ca4d3de0a4e4e652969

**Steps to Reproduce**:

1. Create a new .NET Core console application.
2. Update the contents of Main to have:
```c#
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            return;

            Console.WriteLine("Hello World!");
        }
```
This is to produce a warning (unreachable code).
3. Add an .editorconfig and add `dotnet_diagnostic.CS0162.severity = error` to it so it applies to the file.
4. Build. In the build output, you see a build error. (Note: it may not reflect in the IDE due to feature flag concerns at the moment.)
5. Build a second time.

**Expected Behavior**: the second build still shows an error.
**Actual Behavior**: the second build just says "succeeded".

This is happening because the first build, despite emitting an error, is still outputting it's output binary. Thus, the second build sees "everything up to date" and simply builds successfully.

**Comment by jasonmalinowski** [comment]
FYI to @agocke since I mentioned this to him.

**Comment by jasonmalinowski** [comment]
I will also confess I have not tried to make this an entirely minimal repro: it's possible this also works without .editorconfig involved if you raise a warning to an error other ways.

**Comment by agocke** [comment]
Looks like this doesn't have anything to do with editorconfig, I think it's a bug introduced from the diagnostic suppression work. @mavasani We'd like to take this for servicing, so a fix ASAP would be great
