### ISSUE TITLE
Parent type constraints aren't checked on members referencing an inner class declared on a base type

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#37773]
Related to #37320 and #32536

The general scenario shown below will not report constraint violation errors:

```cs
class A
{
    public class B { }
}

class C<T> : A where T : class { }

class Test
{
    // in post-binding checks the type is seen as `A.B` so there's nothing to error about
    C<int>.B f;
}
```

This is true for types used in:
- properties, fields, and events
- method parameters and returns
- base clauses

and likely other places.

However, the impact in practice is minimal because this bug doesn't cause the compiler to actually emit constructed types which violate constraints. In the scenario above, the emitted type of the field `Test.f` will be `A.B`.

**Comment by RikkiGibson** [comment]
In the 16.4 branch this also applies to pointers to managed types used as type arguments, e.g. `C<object*>.B` in the example above will not report a ManagedAddr error when used in a type member, but will report an error when used as a local variable type.

**Comment by gafter** [comment]
👍 for documenting this issue that we won't fix.  We could fix it by adding a queue of such things to be checked later, but the benefit of doing so is minimal.
