### ISSUE TITLE
Roslyn Project Reflection

### ISSUE THREAD

**Issue by shaggygi** [dotnet/roslyn#3777]
No, I'm not speaking on code reflection.  I think it would be a good idea for the team to provide some insight on things related to this project.  Below are a few topics to possibly share.

1. Working on open-source projects.  Roslyn is a very good example where MS has embraced the open community.  What were some of the obstacles?  What were some of the positives? What would you do and/or planning to do differently going forward?
2. How does the v1 get wrapped into VS 2015 RTM?  I see there are a few lingering issues for v1 release.  What is the process for finalizing a milestone?
3. What are the next big features to work on for vNext Roslyn?  How can we get early previews into VS 2015 (once RTMs)?
4. Other thoughts?

Give yourselves a pat on the back.  It is truly a great accomplishment for your work on this first release :)

**Comment by gafter** [comment]
@shaggygi Thanks for the kind words. If you've got a podcast you'd like to arrange an interview on, we can probably offer someone.

**Comment by shaggygi** [comment]
Thanks @gafter.  I'll pass around and see if it is possible.  I also noticed @DustinCampbell was on .NET Rocks recently.  http://www.dotnetrocks.com/default.aspx?showNum=1185  Good stuff!
