### ISSUE TITLE
Completion does not check for type constraints when is called for extension methods

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#37780]
```cs
    public static class Ext 
    {
        public static void DoSmt<T>(this T thing, string s) where T : class, I
        { 
        }
    }

    public interface I 
    {
        void A();
    }


    public class Class1
    {
        public void M(string s)
        {
            this.$$
        }
    }
```

Start typing at $$

**Expected**
DoSmt does not appear in the completion list

**Actual**
DoSmt appears in the completion list

**Comment by davkean** [comment]
This is a regression from 16.2.

**Comment by ivanbasov** [comment]
@333fred it looks like MethodSymbol.ReduceExtension methoddoes not reduce the method in the example for the given type but it should.

Please take a look. This is a bad regression. We should fix it soon. As in the previous case, I have a test scenario, I can add to a fix from the compiler side.

**Comment by 333fred** [comment]
@jaredpar can you assign someone to take a look at this?

**Comment by ivanbasov** [comment]
A unit test to be fixed is here: https://github.com/dotnet/roslyn/pull/37800
Please let me know if I shuld skip it and merge or just add to a PR with the fix.

**Comment by jaredpar** [comment]
@gafter can you take a look at this?

**Comment by gafter** [comment]
@jaredpar Out of the office this week.  I can look next week.
@agocke this looks like it may be a result of https://github.com/dotnet/roslyn/pull/37022.  Do you agree?

**Comment by agocke** [comment]
I agree that this is probably downstream of that change, but I think that change was correct. If we need the behavior of constraint checking, we should probably find some other way to do that aside from checking constraints while reducing extension methods.

**Comment by jasonmalinowski** [comment]
@agocke It's an API breaking change no matter what.

**Comment by agocke** [comment]
@jasonmalinowski The API was writing checks its implementation couldn't cash

**Comment by CyrusNajmabadi** [comment]
> @jasonmalinowski The API was writing checks its implementation couldn't cash

Fair.  but a solution is needed.  This public entrypoint *was* literally added for thsi use case.  i.e. when we were starting roslyn we needed extension method completion and we def needed constraint checking for it (it's something we had in the native days through awful awful hacks).  From that, this method was born.   It was precisely created so completion could call it to figure out if it could show an extension method.  And yes, it's terrible we didn't have a test for that to help catch this  :)

In terms of a potential solution, can we add a `ReduceExtensionMethod` method to `Compilation` or add an overload of `ReduceExtensionMethod` that takes a `Compilation` to get this working again?  We can obsolete the old one and push people to use the newer one that can actually do this work.

Thoughts?

**Comment by jasonmalinowski** [comment]
> We can obsolete the old one and push people to use the newer one that can actually do this work.

That still may involve making the obsolete method preserve the behavior, as otherwise this is an API breaking change and we'd at least need to do the appropriate review. I'm guessing that process wasn't already done...

**Comment by agocke** [comment]
The problem here is that constraint checking requires a source Compilation, and ReduceExtensionMethod doesn't necessarily have one. I think it would be fine to add a new API to do constraint checking that requires a Compilation.

Restoring the old behavior is basically impossible -- the result in C# 8 is a crash.

**Comment by gafter** [comment]
My plan is to deprecate the old method (with a warning) but keep it working, frozen at the 7.3 language version.  I will make the version of the method in `SemanticModel` work correctly.

**Comment by CyrusNajmabadi** [comment]
@gafter thanks, that seems reasonable :)

**Comment by gafter** [comment]
Better yet, we'll check at the 8.0 version.  That way it will suggest the method, and if you use it you might be prompted to upgrade your language version.  A better experience I think.
