### ISSUE TITLE
How to implement logging in custom rules created

### ISSUE THREAD

**Issue by naveenkumarmca** [dotnet/roslyn#37788]
I have to implement logging in the custom rules plugin developed for C#  . Default log I have attached here.
I have tried following 2
Console.WriteLine("Initialize method is started");
Trace.WriteLine("Initialize method is started");
But there did not come up on logs/console.

We need to add some more details in log. How to implement ? Can you please help on this .
Thanks in advance.
![image](https://user-images.githubusercontent.com/42217814/62622206-6928c780-b93b-11e9-9b71-cda46617067e.png)

**Comment by gafter** [comment]
I don't think this has anything to do with Roslyn.
