### ISSUE TITLE
class diagram show as collection association not working for IList<T> and T is in the same project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37796]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/679870/class-diagram-show-as-collection-association-not-w.html)._

---
I have two classes, one A and one B, B has an A property and A has a list of B, like above

``` C#

public class A
{
 public virtual IList<B> B {get;set;}
}


public class B
{
public virtual A A {get;set;}
}

```

If I go to class diagram ans add those two classes, and press Show as collection association in B property on A class, it returns this error

---------------------------
Microsoft Visual Studio
---------------------------
Cannot show as association because 'System.Collections.Generic.IList&lt;MC.AspNetCore.Workflow.Model.Passo.Passo&gt;' cannot be found.

Try one of the following:

- Ensure that 'System.Collections.Generic.IList&lt;B&gt;' is an existing type.

- If 'System.Collections.Generic.IList&lt;B&gt;' is defined outside your project, ensure you have placed the correct references in Solution Explorer.
---------------------------
OK   Help   
---------------------------

---
#### Visual Studio Feedback System on 8/7/2019, 04:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jklaus** [comment]
I just experienced this issue out of the blue, it had been working fine in the past.  I killed VS, its working fine again now that restarted.  I'm guessing something went wrong while loading the .cd

**Comment by kenichi-kobayashi** [comment]
The same phenomenon occurs in Visual Studio 2019 16.11.1.
Restarting Visual Studio does not resolve the issue.

**Comment by CyrusNajmabadi** [comment]
Not sure why this is assigned to roslyn.  Class diagram is not owned by us afaik.  @jinujoseph  do you know who owns this VS component?

**Comment by jinujoseph** [comment]
reopened the DC ticket and routed to right team

**Comment by lukewis** [comment]
The DC issue was closed as "low priority" and I'm not able to click the "No, this is blocking my work" button.  @jinujoseph - anything you can do to help?

**Comment by CyrusNajmabadi** [comment]
@lukewis The owning team has chosen not to take up this work.  Sorry!

**Comment by mrtn-t** [comment]
Hi, this bug persist for more than four years now. Will it EVER be fixed?

**Comment by CyrusNajmabadi** [comment]
> Hi, this bug persist for more than four years now. Will it EVER be fixed?

@mrtn-t as stated above. This is *not* our team or feature. Please use VS feedback to report if you are having problems with this feature.
