### ISSUE TITLE
Switch to MIT license

### ISSUE THREAD

**Issue by kryptine** [dotnet/roslyn#37797]
I suggest that Roslyn's license should be changed to a MIT license. This would [alleviate legal problems for developers](https://github.com/dotnet/fsharp/issues/1727) and be consistent with the rest of .NET Core.

**Comment by tmat** [comment]
@richlander

**Comment by tannergooding** [comment]
CC. @jaredpar, @ManishJayaswal

**Comment by Kryptos-FR** [comment]
Did you ask a lawyer before making that change?

The point of Apache license is to make sure there are not issues with potential patents. MIT doesn't have such provision.

**Comment by jaredpar** [comment]
Yes this was approved by legal.

**Comment by Kryptos-FR** [comment]
@jaredpar thanks for the precision. Would be nice to mention it in similar issues in the future, so that people don't have to ask.
