### ISSUE TITLE
C# intellisense suggesting invalid generic methods

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37794]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/679722/c-intellisense-suggesting-invalid-generic-methods.html)._

---
Intellisense shows method &quot;DoSomething&quot; as a suggestion for variables that don't match the generic type constraint of the method.

Code below, type `d.` and see &quot;DoSomething&quot; show up in the suggested list:

```
using System;

namespace broke
{
    public class SomeClass
    {
    }

    public static class SomeTypeExtensions
    {
        public static void DoSomething<TType>(this TType type) where TType : SomeClass
        {
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            IDisposable d;
        }
    }
}
```

---
#### Visual Studio Feedback System on 8/7/2019, 03:23 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/7/2019, 10:16 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

![image](https://user-images.githubusercontent.com/7817401/62643751-850d7880-b8fd-11e9-9020-801a8a4db65e.png)

**Comment by ivanbasov** [comment]
dupe pf https://github.com/dotnet/roslyn/issues/37780
