### ISSUE TITLE
Find All References does not find all references

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37793]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/679669/find-all-references-does-not-find-all-references.html)._

---
Performing a Find All References skips over overridden implementation and does not report that in the find results. From the image, the NotifyTestRecordsChangedAsync API is used in 4 places from the code lens indicators which is correct but I dont see the find results matching. This is from the VSUniTesting repo - https://devdiv.visualstudio.com/DevDiv/_git/VSUnitTesting.

---
#### Visual Studio Feedback System on 8/6/2019, 11:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

![image](https://user-images.githubusercontent.com/7817401/62643443-d5380b00-b8fc-11e9-93fc-33902d1c644b.png)

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  note the project has changed so much i can't even find the code mentioned above.  however, testing shows the expected behavior with overrides.
