### ISSUE TITLE
Permit breakpoints in the switch expression.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#37805]
In support of https://github.com/dotnet/roslyn/issues/22016 please make the compiler generate the necessary sequence points so that we can set breakpoints in the when clause and expression part of a switch expression.  This would require promoting the temps to long-lived temps.

**Comment by CyrusNajmabadi** [comment]
Yes please.  I just hit this today trying to debug code that i wrote in a very switch-expression heavy fashion.  :)

**Comment by gafter** [comment]
Addressed in https://github.com/dotnet/roslyn/pull/42711
