### ISSUE TITLE
Avoid emitting NullableAttribute when unecessary

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#37808]
```
#nullable enable 
public class C
{
    public void Foo(string arg1, string arg2) { }
    public void Bar(string arg1, string arg2) { }
}
```
We shouldn't need to emit both `NullableContext(1)` and `Nullable(0)` for this simple class, but we are today. @cston, do you know if there's a reason we're doing this?

**Comment by cston** [comment]
The `[Nullable(0)]` attribute on the class represents the annotations of the base class, `object`.

**Comment by jcouv** [comment]
Ah, sounds like we can't omit it then. Close?
