### ISSUE TITLE
Nullable reference types disabled by <auto-generated> comment

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn#37829]
**Version Used**: 3.2.0-beta4-19359-03+15b43b33901c88f68ef43f8314b5a2457716780d (16.2.1)

**Steps to Reproduce**:

test file:
```cs
// <auto-generated>
public class Test { public string? field; }
```
command:
```
csc.exe /nullable:enable /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\mscorlib.dll" /out:Test.dll /target:library /langversion:8.0 test.cs
```

**Expected Behavior**:
no warnings

**Actual Behavior**:
```
test.cs(2,34,2,35): warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
```

Workarounds:
 - remove <auto-generated> comment
-  explicit #enable nullable

Wasted a lot of time trying to understand why it wasn't working. In the end found out it is due to auto-generated comment we add by T4 template. And no, we need this comment.

**Comment by sharwell** [comment]
This was an intentional design decision. Code generators prior to the introduction of Nullable Reference Types did not account for Nullable Reference Types. Those code generators must be updated to account for the new feature, and at the same time are expected to start emitting `#nullable enable` in the generated code to indicate that the update is complete.

**Comment by MaceWindu** [comment]
As I can understand it is probably expected behavior to support legacy codegerators. What I would like to see here is that compiler generates adequate warning message so it will be clear why it doesn't work and how to fix it.

**Comment by CyrusNajmabadi** [comment]
> What I would like to see here is that compiler generates adequate warning message so it will be clear why it doesn't work and how to fix it.

Doesn't it?  From your 'actual':

>test.cs(2,34,2,35): warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.

It reads to me like it's saying that you should put it in a `#nullable` to support this.  Thanks!

**Comment by MaceWindu** [comment]
Not really. I see that I enabled nullable types for whole project, didn't put any `#nullable disable` and it still tells me that I'm not in nullable context. 
How could I guess that some comments work as #nullable directives. I would probably think that I misconfigured something or hit a bug as it is pretty new feature and it would be expected to hit bug or misconfigure it (especially taking into account that configuration options changes several times for last couple of years)

**Comment by CyrusNajmabadi** [comment]
> and it still tells me that I'm not in nullable context.

Right.  But you said: `and how to fix it.`.  I was pointing out thta it seems to indicate how to fix things.

That said, i think it would be ok to have a custom message saying "Nullable support was disabled due to auto-generated code detection.  Add an explicit #nullable directive to explicitly enable for this file."

**Comment by MaceWindu** [comment]
Ahh, yep, agree. Message like that will be enought I think. User just need to be properly informed that it auto-generated context it doesn't work as usual.

**Comment by RikkiGibson** [comment]
I agree that this is confusing and it would be reasonable to add a different warning for use of the nullable annotation when we detect that nullable is disabled due to the presence of `/// <auto-generated>` or a similar comment.

**Comment by RikkiGibson** [comment]
There will be a new warning message for this scenario in 16.4 which should make this problem easier for generator authors to figure out.
