### ISSUE TITLE
How to get "InternalsVisibleTo" attribute work when compiling a solution via Roslyn?

### ISSUE THREAD

**Issue by pdeligia** [dotnet/roslyn#3782]
Hi, I have a question. So I am developing a Roslyn-based frontend compiler that parses a C# solution, performs rewriting on the syntax trees to desugar some constructs of my DSL, and then uses the Roslyn APIs to compile and emit executables/dlls. This last part is done very simply like this (some details omitted for clarity):

```C#
var compilation = project.GetCompilationAsync().Result;

var compilationOptions = new CSharpCompilationOptions(outputKind,
  compilation.Options.ModuleName, compilation.Options.MainTypeName,
  compilation.Options.ScriptClassName, null,
  compilation.Options.OptimizationLevel, compilation.Options.CheckOverflow, 
  false, compilation.Options.CryptoKeyContainer, 
  compilation.Options.CryptoKeyFile, compilation.Options.CryptoPublicKey, 
  compilation.Options.DelaySign, Platform.AnyCpu, 
  compilation.Options.GeneralDiagnosticOption, 
  compilation.Options.WarningLevel,
  compilation.Options.SpecificDiagnosticOptions,
  compilation.Options.ConcurrentBuild, 
  compilation.Options.XmlReferenceResolver,
  compilation.Options.SourceReferenceResolver,
  compilation.Options.MetadataReferenceResolver,
  compilation.Options.AssemblyIdentityComparer,
  compilation.Options.StrongNameProvider);

var targetCompilation = CSharpCompilation.Create(assemblyFileName,
  compilation.SyntaxTrees, compilation.References,
  compilationOptions);

EmitResult emitResult = null;
using (var outputFile = new FileStream(fileName, FileMode.Create, FileAccess.Write))
{
  emitResult = targetCompilation.Emit(outputFile);
  if (emitResult.Success)
  {
    return fileName;
  }
}
```

So everything works perfectly fine, until I tried to compile a solution where a project A declares some internal classes/fields, and then uses the `[assembly: InternalsVisibleTo("...")]` attribute (in the AssemblyInfo.cs file) to give visibility of these internals to another project B.

Directly compiling using visual studio works perfectly fine and allows B to see these internal declarations of A. However, when I try to compile through my tool using the Roslyn APIs, it is like the InternalsVisibleTo attribute is completely ignored, and I am getting back errors, such as:

`error CS0122: ... is inaccessible due to its protection level`

Which means the `InternalsVisibleTo` was not picked up. I tried both with unsigned and signed projects.

I was expecting that Roslyn would automatically pick this up from the parsed project info (because I passed the project compilation options), but I am now wondering if I have to add some other information manually?

I have looked around but I cannot find a similar question or an answer, unless I am missing something. I am also not sure if this is a Roslyn bug or not. I can give some more information if required. Thanks!

**Comment by gafter** [comment]
We do not have enough information about your tool to diagnose it.

**Comment by calum74** [comment]
I have the same problem actually. We have two assemblies, e.g. `ICSharpCode.NRefactory.CSharp.Refactoring` and `ICSharpCode.NRefactory.CSharp`, where `ICSharpCode.NRefactory.CSharp.Refactoring` references `ICSharpCode.NRefactory.CSharp`. In `ICSharpCode.NRefactory.CSharp`, we have an internal `class VariableReferenceNode`, which is used in `ICSharpCode.NRefactory.CSharp.Refactoring`. This would normally give `CS0122`, because `VariableReferenceNode` is not visible.

Rather than make `VariableReferenceNode` public, the authors of `ICSharpCode.NRefactory.CSharp` decided to expose it using [AssemblyInfo.cs](https://github.com/icsharpcode/NRefactory/blob/master/ICSharpCode.NRefactory.CSharp/Properties/AssemblyInfo.cs), as follows:
```
[assembly: InternalsVisibleTo("ICSharpCode.NRefactory.CSharp.Refactoring, PublicKey=00240000048000009400000006020000002400005253413100040000010001004dcf3979c4e902efa4dd2163a039701ed5822e6f1134d77737296abbb97bf0803083cfb2117b4f5446a217782f5c7c634f9fe1fc60b4c11d62c5b3d33545036706296d31903ddcf750875db38a8ac379512f51620bb948c94d0831125fbc5fe63707cbb93f48c1459c4d1749eb7ac5e681a2f0d6d7c60fa527a3c0b8f92b02bf")]
```
Unfortunately, my compilation contains lots of errors of the kind 
```
C:\dev\projects\monodevelop\main\external\nrefactory\ICSharpCode.NRefactory.CSharp.Refactoring\CodeIssues\Synced\CodeQuality\PossibleMultipleEnumerationIssue.cs(244,12): error CS0122: 'VariableReferenceNode' is inaccessible due to its protection level
```
Calls to `GetSymbolInfo()` fail with `CandidateReason.Inaccessible`. Either

- It's a bug because `InternalsVisibleTo` should be handled, or
- I didn't set up compilation options and references correctly.

However, Roslyn `csc.exe` clearly copes with this, so something at some point picks up the `InternalsVisibleTo` attribute in `ICSharpCode.NRefactory.CSharp`.

This is reproducible by analysing the project (https://github.com/icsharpcode/NRefactory/tree/master/ICSharpCode.NRefactory.CSharp.Refactoring).

**Comment by calum74** [comment]
Looking at https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/CommandLine/CSharpCompiler.cs#L131-L140, I see that `csc.exe` adds extra compilation options such as `WithMetadataReferenceResolver`, `WithAssemblyIdentityComparer` and `WithStrongNameProvider`. Are these required for the successful operation of `InternalsVisibleTo` ?

**Comment by calum74** [comment]
I think the answer is to ensure that a `StrongNameProvider` is supplied in the compilation options. Removing the `StrongNameProvider` [here](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/CommandLine/CSharpCompiler.cs#L138) reproduces the problem. I will see if this resolves my problem, then report back.

**Comment by calum74** [comment]
Yep, works. For me the issue is resolved. My guess is that the OP needs to supply a properly configured `StrongNameProvider`.

I needed to add the `WithStrongNameProvider` call as shown below.
```
var compilation = CSharpCompilation.Create(
    commandLineArguments.CompilationName,
    syntaxTrees,
    references,
    commandLineArguments.CompilationOptions.
		WithAssemblyIdentityComparer(DesktopAssemblyIdentityComparer.Default).
		WithStrongNameProvider(new DesktopStrongNameProvider(commandLineArguments.KeyFileSearchPaths))
    );
```

**Comment by pdeligia** [comment]
Thanks @calum74 ! This makes sense and should work indeed.
@gafter there is nothing tool-specific to this question, it is just about using a `CSharpCompilation` API, please see @calum74 answer.
