### ISSUE TITLE
Can't extract expression in switch expression branch.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#37824]
I had the following code:

```c#
            var result = children.Select(child => child switch
            {
                Choice c => ProcessChildren(c.Children, " | ").Parenthesize(),
                Sequence s => ProcessChildren(s.Children, " ").Parenthesize(),
                _ => ProcessField((Field)child),
            }).Where(p => p.Text.Length > 0);
```

I wanted to extract the `ProcessChildren(c.Children, " | ").Parenthesize()` part.

Unfortunately, extract method pulled out the entire switch-expression.

**Comment by ryzngard** [comment]
@CyrusNajmabadi do you remember more context on this? I tried to make a min repro but wasn't able to reproduce: 

```csharp
public object M()
{
    var x = new int[] {5};
    return x.Select(y => y switch
    {
        < 0 => [|long.Parse(ProcessNumber(y * -1))|], // <-- extract between [| |]
        _ => long.Parse(ProcessNumber(y))
    });
}

private string ProcessNumber(int v) => string.Empty;
```

**Comment by CyrusNajmabadi** [comment]
I think it didn't work, but we fixed it.  But it still make not work in a 'when' clause.  can you check/fix that?

**Comment by ryzngard** [comment]
Confirmed when clause doesn't work, but we have a separate issue for that: #24136
