### ISSUE TITLE
<Shift + Enter> should commit all pending brace completion sessions

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#3783]
Shift+Enter should commit all pending brace completion sessions and insert a semi-colon if necessary before starting a new line:

Type: Console.WriteLine(3.ToString(

Then Shift+Enter, and you should end up with: Console.WriteLine(3.ToString()); with the caret on the next line, indented.

@Pilchie Is this still a supported feature?

**Comment by Pilchie** [comment]
Yes!

**Comment by balajikris** [comment]
@basoundr - could you elaborate on the repro steps a bit? I tried a similar case and it worked for me.

**Comment by basoundr** [comment]
@balajikris  The feature works as expected and I was mistaken about the working of the feature.

**Comment by balajikris** [comment]
chatted offline with @basoundr. It works as expected.
