### ISSUE TITLE
Underline comparing a value of non-nullable type to null

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37848]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/483193/underline-comparing-a-value-of-non-nullable-type-t.html)._

---
<p>In the following expression, Visual Studio correctly underlines the expression as it is always false:</p><pre>int number = 10;
if (number == null) // Expression is underlined, it is always false
{
  // ...
}</pre><p>However, this does not work for all types not allowing nulls:</p><pre>DateTime dateTime = new DateTime();
if (dateTime == null) // Expression is NOT underlined, it is always false
{
  // ...
}</pre><p>While assigning <strong>null</strong> to <em>number</em> or <em>dateTime</em> is invalid, detection of expressions which always evaluate to <strong>false</strong> works for <i>number</i> only.</p>

---
#### Jane Wu [MSFT] on 3/11/2019, 03:20 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by gafter** [comment]
Dup of https://github.com/dotnet/roslyn/issues/30196
