### ISSUE TITLE
F12 on `using` should navigate to object's `Dispose( )` method

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37842]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/416821/f12-on-using-should-navigate-to-objects-dispose-me.html)._

---
<p>It would be really helpful if I could F12 or CTRL+CLICK on the `using` keyword to navigate to the disposable resource's `Dispose( )` method. It would definitely be appreciated when the `Dispose( )` method is inherited.</p><pre>using(var disposableObject = new DisposableObject())
{ 
//...
}
</pre>

---
#### Jane Wu [MSFT] on 12/28/2018, 10:05 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by ryzngard** [comment]
Design Review: Improvements to FAR would be accepted to allow this behavior. @sharwell can you link a good example of similar PR?

**Comment by sharwell** [comment]
A great example of a similar situation is #23394 / #23049
