### ISSUE TITLE
`new SomeStruct(` should show user-defined overloads first in completion

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#37843]
See the scenario below:

```cs
public readonly struct SomeStruct
{
    /// <summary>TODO: insert useful documentation</summary>
    public SomeStruct(int prop1, string prop2)
    {
        Prop1 = prop1;
        Prop2 = prop2;
    }

    public int Prop1 { get; }
    public string Prop2 { get; }

    static void Test()
    {
        var s = new SomeStruct( // typing...
    }
}
```

### Expected behavior:
A completion list of 2 constructors appears, with the user-defined constructor `SomeStruct(int, string)` coming first

### Actual behavior:
A completion list of 2 constructors appears, with the synthesized parameterless constructor `SomeStruct()` coming first

I believe that a user-defined constructor is more likely to be useful than the synthesized parameterless one and therefore should be shown first. I also believe that I could be totally missing something that makes it so it should continue to work the way it does today :)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback
