### ISSUE TITLE
Be smarter when the type inferrer infers nullability around error cases

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#37852]
If the type inferrer infers that a type is nullable due to context, it'll return either a nullable value type or a nullable reference type, and in either case generate a type syntax that has a ?. If it's a nullable reference type, we'll remove the ? in the simplification pass if you're not in a `#nullable enable` case.

If the type being inferrered is an _error_ type, the syntax we generate will be bound by the compiler as a value type, so the simplification pass will think it's valid always. This was addressed by simply having the type inferrer not stick a null with the error type case. But we could be smarter: we could instead still infer it to be nullable but when generating the syntax annotate the ? saying "this was a guess". If you're in a `#nullable enable` case we keep the guess (since it's valid no matter struct or class), but in the `#nullable disable` case drop it under the guess you want to be a class.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We should drive this with actual examples where some feature does a poor job and the right fix is at hte typeinferrer level.
