### ISSUE TITLE
Using the editor dropdown to navigate to Visual Basic event handler is painful

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37854]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/550338/using-the-editor-dropdown-to-navigate-to-visual-ba.html)._

---
<p>I have a VB.net project with windows forms.</p><p>If I am in code view for the form and try to navigate to a button's (say btnOK) Click handler using the text editor's dropdown lists, I have to:</p><ol><li>(Optional?) Using the left-most dropdown pick the module(?). In most of my situations, there is only a single item and I skip this step.</li><li>Using the middle dropdown, I have to scroll to find the right button. Why is this list structured like this with classes, the class's events and then the class's members which support events?!?</li><li>Then I have to go to the right-most dropdown and find the 'Click' event. Why does it show all of the possible events? Why if you accidentally click the wrong event would you want it to create the event handler method?</li></ol><p>If I want to navigate back to a regular method on the form, I have to:</p><ol><li>Select the form from the middle drop down</li><li>Select the method from the right-most dropdown. This is an extra unnecessary step if all of the class's methods were in the one list (the right-most).</li></ol><p>I spend 99% of my time maintaining existing code and browsing rather than creating new code. The design of a C# project's dropdown organisation is vastly superior for this purpose:</p><ol><li>Select Namespace</li><li>Select class</li><li>Select method.</li></ol><p>Is there an option to have C# style navigation instead of the VB.NET way? If not, please provide one it would be a very nice productivity improvement.</p><p>Thanks!</p>

---
#### Jane Wu [MSFT] on 4/30/2019, 02:24 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
#### Cameron Miller on 5/2/2019, 10:13 PM: 

<p>Hi I also found that I can't navigate to directly to a control's declaration using the dropdown navigation (e.g. Friend WithEvents cmdEscape As ButtonRounded). This may be a bug?</p>

**Comment by sharwell** [comment]
🔗 This issue is a subset of experience requested in #36812.

**Comment by shemmy01** [comment]
I have a similiar problem. The middle dropdown is displaying all the controls of the form but will always select the events of the form and ignors any selection of another control. Selecting events for a contol can be done from the desingner panel thru properties.

**Comment by sharwell** [comment]
Hi @shemmy01,

That is a separate issue which we are tracking here:
https://developercommunity.visualstudio.com/t/Version-16100-release-editor-problem/1432877

Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing as this is not an area we are investing in.
