### ISSUE TITLE
Opening a _very_ large file causes Visual Studio to crash

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37860]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/421417/devenv-unknown-hard-error-ctorchararraystartlength.html)._

---
When working with big code files the IDE frequently crashes with Unknown Hard Error. See attached screenshot.

The stacktrace in the event log shows CtorCharArrayStartLength as the failure point. See attached full stacktrace for more info.
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CtorCharArrayStartLength(Char[] value, Int32 startIndex, Int32 length)

I created a repro to simulate the problem. Open the attached code file, notice that the call to the EndsWith method has a start parenthesis but is not closed. Add and remove the close parenthesis character a few times to trigger the crash.

---
#### Visual Studio Feedback System on 6/24/2019, 00:44 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Sam Harwell [MSFT] on 8/8/2019, 03:58 PM: 

<p>Thank you for providing feedback, and we’re sorry to hear it’s not behaving as you expect. Based on your description so far, it sounds like you are experiencing a problem which is historically hard to diagnose and resolve using the normal “steps to reproduce”. We created a set of instructions for providing additional information which will help us track down the true source of the problems.</p>
<p>Based on the information provided so far, the most likely scenario to follow is for “Crashes”. Please take a look at the following document to provide the feedback most relevant for the problems you would like to see fixed: <a target='_blank' href="https://github.com/dotnet/roslyn/wiki/Reporting-Visual-Studio-crashes-and-performance-issues#crashes">https://github.com/dotnet/roslyn/wiki/Reporting-Visual-Studio-crashes-and-performance-issues#crashes</a></p>

#### bugreporter5367 on 8/8/2019, 05:16 PM: 

@sharwell How is it hard to diagnose? I attached a code sample with repro steps to crash the IDE. VS 16.2 is even easier, just opening the file causes an immediate crash. What more would you like me to provide?

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
The attached file cannot be opened in Visual Studio 2019 version 16.2 without causing the IDE to crash:

[Repro.zip](https://github.com/dotnet/roslyn/files/3484560/Repro.zip)

**Comment by CyrusNajmabadi** [comment]
Closing out.  The file has a string literal with 500,000 lines in it.  Infinite scaling in every dimension it not a goal of roslyn.  There are limits as imposed by basic stuff like ability to allocate and whatnot.  We fix thigns up when code constructs are realistic and reasonable.  We don't fix things when teh user is trying to overwhelm reasonable limits, and could easily change their code to workaround the problem.
