### ISSUE TITLE
[C# Feature Request] Show FlagAttribute and datatype of enums on hover

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/roslyn#37861]
**Version Used**: 
Visual Studio Community 2019 Preview
Version 16.3.0 Preview 1.0

**Steps to Reproduce**:

1.  Create a file with a `enum`
2.  Add the `[Flags]` attribute to the `enum`
3.  (optional) Add a datatype to the `enum`
4. Hover over the name of the `enum`

```csharp
/// <summary>
/// My beautiful enum
/// </summary>
[Flags]
public enum MyEnum : byte
{ }
```

**Expected Behavior**:
On hover
``` 
(symbol) [Flags] enum MyEnum : byte
My beautiful enum
```

**Actual Behavior**:
On hover
```
(symbol) enum MyEnum
My beautiful enum
```

**Current workaround**:
Add FlagAttribute and datatype to the XML documentation
```csharp
/// <summary>
/// My beautiful enum
/// (enum used <see cref="FlagsAttribute"/>, datatype: <see cref="byte"/>)
/// </summary>
[Flags]
public enum MyEnum : byte
{ }
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
