### ISSUE TITLE
#nullable enable produces IMethodSymbols with no containing type, crashes IDE

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#37879]
**Version Used**: 

**Steps to Reproduce**:

1. Create a new console application.
2. Add this code inside of Program. (I have tried to reduce this to a smaller repro but have been unsuccessful):
```
public void A<T>(T t) where T:class
{
    var c = new F<T>[] { }.Select(v => new { Value = v.Item }).ToArray();
}

private class F<T>
{
    public F(T oldItem) => Item = oldItem;
    public T Item { get; }
}
```
3. Remove the `using System.Linq` at the top of the file. The "Select" should get a red squiggle.
4. Mouse over the Select method, observe no quick info.
5. Add a `#nullable enable` to the top of the file. Observe the Select now turns brown because it's binding to a method. (Which method? Who knows!)
6. Mouse over the Select again.

**Expected Behavior**: we don't get quick info
**Actual Behavior**: it crashes, because this bound to a method symbol that has no ContainingType which our code doesn't expect.

**Comment by jasonmalinowski** [comment]
@333fred @jcouv Is it expected to encounter IMethodSymbols with a null ContainingType? Even if yes, is it expected that the #nullable enable is changing the compiler binding behavior in this case?

If we need to harden the IDE to this we can do so, but this seems pretty funky.

**Comment by 333fred** [comment]
Note: the crash is in the OOP process, which VS displays via a gold bar. Shortly after the InvalidOperationException, a second gold bar prompting VS restart is displayed.
![image](https://user-images.githubusercontent.com/2371880/62982167-391c7100-bde0-11e9-9eed-aa13c8100d37.png)
