### ISSUE TITLE
New [SuppressMessage] in source option not shown in Error List

### ISSUE THREAD

**Issue by Gav-Brown** [dotnet/roslyn#37902]
**Version Used**: 

Visual Studio 2019 v16.2.1

**Steps to Reproduce**:

1. Trigger a code analysis rule
2. Right click on entry in Error List
3. View `Suppress` menu entries

**Expected Behaviour**:

New suppress `in Source (attribute)` option is available and adds `[SuppressMessage]` attribute to source code. As per right click menu from Light Bulb quick action:

![LightBulb](https://user-images.githubusercontent.com/36932614/62837387-b8863500-bc66-11e9-92c7-2bf45c3c3cc1.png)

**Actual Behaviour**:

Option is missing.

![ErrorList](https://user-images.githubusercontent.com/36932614/62837398-d81d5d80-bc66-11e9-88b9-49cfe68b56a1.png)

This should be added for completeness, ease of discovery, and to avoid confusion.

**Comment by Gav-Brown** [comment]
Missing from work done for #17218

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
