### ISSUE TITLE
Confused about TupleElementNames for tuples with more than 8 elements

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#37904]
Consider the following tuple-typed field:

```c#
(int A1, int A2, int A3, int A4, int A5, int A6, int A7, int A8, (int x, int y) A9) F;
```

[When you compile it](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMACAwgWAFADe+GJGAFAJYB2MGAggIwA0G1tdaLb9AzFzfQAs/dgFYR9AGwS6AdhkAOFpQEAPCQE8AlPQCcOgGIBufAF8gA=), the generated code is:

```c#
[TupleElementNames(new[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", null, null, "x", "y" })]
private ValueTuple<int, int, int, int, int, int, int, ValueTuple<int, ValueTuple<int, int>>> F;
```

Notice that the generated `[TupleElementNames]` contains two extra `null`s, one for each tuple element in the `TRest` tuple. But these `null`s don't correspond to any tuple elements in the original source, so to me, this behavior seems to be wrong.

On the other hand, as far as I can tell, this does not cause any observable problems (because whenever compilation produces these extra `null`s, metadata decoding expects them to be there) and "fixing" this would cause compatibility issues. Because of that, maybe the best option to do here is to document this quirky behavior?

What do you think?

This issue was originally noticed by @pauldotnet in https://github.com/dotnet/csharplang/issues/1906#issuecomment-466275495.

**Comment by jcouv** [comment]
The serialization seems correct. Each `ValueTuple` has its names serialized. In this case there are three `ValueTuple`s: one with `A1`..`A9`, one with two `null`s, and one with `x` and `y`.

**Comment by svick** [comment]
@jcouv That logic only works if you count members of the second `ValueTuple` (i.e. `int` and `ValueTuple<int, int>`) also as members of the first `ValueTuple` (because the first VT has only 8 type parameters, `T1`…`T7` and `TRest`, but 9 names). And when you count them for the first VT, you give them names, while when you count them for the second VT, their names are always `null`.

I still don't think this is the natural way to do it.

**Comment by canton7** [comment]
I think a clearer example would be:

    { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", null}
    (int A1, int A2, int A3, int A4, int A5, int A6, int A7, int A8) 

and 

    { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", null, null}
    (int A1, int A2, int A3, int A4, int A5, int A6, int A7, int A8, int A9) 

and 

    { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", null, null, null}
    (int A1, int A2, int A3, int A4, int A5, int A6, int A7, int A8, int A9, int A10) 

[The docs](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.tupleelementnamesattribute.transformnames?view=netframework-4.8#System_Runtime_CompilerServices_TupleElementNamesAttribute_TransformNames) say:

> Specifies, in a pre-order depth-first traversal of a type's construction, which value tuple elements are meant to carry element names.

but I don't think it's clear from the docs why we get more and more `nulls` at the end.

**Comment by jcouv** [comment]
Each `ValueTuple` gets visited, and its element names get serialized.
You could have `ValueTuple<(int a, int b)>` or `ValueTuple<T1, .., T7, (int a, int b)>` and so on. This explains why the `ValueTuple` in a `TRest` still needs to store element names (two `null`s in the original example).

**Comment by svick** [comment]
@jcouv That example with tuple with names in `TRest` clarifies it for me. Thank you for the explanation.
