### ISSUE TITLE
IDictionary indexer gives spurious CS8625 nullability warning

### ISSUE THREAD

**Issue by bgrainger** [dotnet/roslyn#37901]
**Version Used**: dotnet 3.0.100-preview7-012821

**Steps to Reproduce**:

Compile the following code with `<Nullable>enable</Nullable>`:

```csharp
IDictionary dictionary = new Dictionary<string, string>();
dictionary["test"] = null;
```

Full example at https://github.com/bgrainger/NullableTest/blob/master/IDictionaryIndexer.cs

**Expected Behavior**:

No warnings.

As per https://docs.microsoft.com/en-us/dotnet/api/system.collections.idictionary?view=netframework-4.8:

> The value can be null and does not have to be unique.

At https://github.com/dotnet/corefx/blob/b129f7657a1b93ce9cf577d769d9d03c862e2338/src/Common/src/CoreLib/System/Collections/IDictionary.cs#L18 the indexer property is denoted as `object?`.

**Actual Behavior**:

warning CS8625: Cannot convert null literal to non-nullable reference type.

**Comment by svick** [comment]
When I decompile the reference assembly that contains `IDictionary` (C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.0.0-preview7-27912-14\ref\netcoreapp3.0\System.Runtime.dll), I see this:

```c#
[Nullable(2)]
object this[object key] { [return: Nullable(2)] get; [param: Nullable(2), DisallowNull] set; }
```

I think the `[DisallowNull]` attribute means the compiler is behaving correctly. Though I don't understand how the attribute got there (it's not in the [source code for the reference assembly](https://github.com/dotnet/corefx/blob/b129f76/src/System.Runtime/ref/System.Runtime.cs#L3875)), or why would it be there.

**Comment by RikkiGibson** [comment]
I can't repro this with 3.0.0-preview8.

In addition I see the following decompiled signature for `System.Collections.IDictionary.this[object key]` in `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.0.0-preview8-28373-17\ref\netcoreapp3.0\System.Runtime.dll`
```cs
[Nullable(2)]
object this[object key]
{
	[return: Nullable(2)]
	get;
	[param: Nullable(2)]
	set;
}
```

**Comment by bgrainger** [comment]
> I can't repro this with 3.0.0-preview8.

Neither can I.
