### ISSUE TITLE
Roslyn incorrectly handles optional parameters when processing [NotNullIfNotNull] annotation

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#37903]
Similar to https://github.com/dotnet/roslyn/issues/37832

**Version Used**: 

```cs
Branch master (10 Aug 2019)
Latest commit c21548 by dotnet-automerge-bot:
Merge pull request #37896 from dotnet/merges/release/dev16.3-preview2-to-master

Merge release/dev16.3-preview2 to master
```

**Steps to Reproduce**:

Compile the following code:
```cs
#nullable enable
using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
public class C {
    [return: NotNullIfNotNull("p")]
    public string? M1(string? p = "defualt") => p;
    
    [return: NotNullIfNotNull("p")]
    public string? M2([Optional, DefaultParameterValue("defualtParameterValue")] string? p) => p;
    
    [return: NotNullIfNotNull("p")]
    public string? M3([CallerMemberName] string? p = null) => p;
    
    void Test()
    {
        var s1 = M1();
        s1.ToString();
        
        var s2 = M2();
        s2.ToString();
        
        var s3 = M3();
        s3.ToString();
    }
}
```

**Expected Behavior**:
No warnings. Roslyn will handle every invocation and insert a non-nullable argument for each of them. According to the called members' signatures non-nullable argument results in a non-nullable return value.

**Actual Behavior**:
```
    warning CS8602: Dereference of a possibly null reference.
    warning CS8602: Dereference of a possibly null reference.
    warning CS8602: Dereference of a possibly null reference.
```
Warnings reported for `s1.ToString()`, `s2.ToString()` and `s3.ToString()`.

**Comment by RikkiGibson** [comment]
@jcouv is there an API for getting the "effective" arguments to a method which can resolve stuff like 'params' and default values?

**Comment by jcouv** [comment]
@RikkiGibson I don't think there is. If there is a way to factor some of that out, that'd be great.

**Comment by RikkiGibson** [comment]
The LocalRewriter does some fairly complex stuff to translate BoundCalls and other nodes which take arguments (e.g. IndexerAccess) with reordered argument labels, omitted optional arguments, etc. into the "emit-friendly" form. Some of this logic is shared with IOperation. Until you do this you don't have the full picture on what arguments are *really* getting passed to the method/indexer/..callable thing.

It feels like there should be API in a layer that's appropriate to be called by users in LocalRewriter, IOperation, and flow analysis which can BuildArgumentsInEvaluationOrder (this is the method exposed to IOperation, perhaps what it's doing is essentially what flow analysis needs too).

Alternatively, nullable analysis can just reimplement the subset of this that it finds necessary.
- check for and use the parameterSymbol.ExplicitDefaultConstantValue
- check for presence of CallerMemberNameAttribute to decide if the compiler will use the constant value in syntax or replace it with something else.
- handle OptionalAttribute and DefaultParameterValueAttribute

What do you think @agocke @333fred @jcouv?

**Comment by 333fred** [comment]
+1 from me. It's bugged me that ioperation depends on the local rewriter there, a separate API sounds like a good idea.
