### ISSUE TITLE
Unicode escape in the middle of a define causes compile error CS1024

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/roslyn#37919]
We had an internal report of this scenario. We would like to know if this is an unsupported scenario of if there is a bug in the encoding logic that should recognize this character.

```cs
#de\u0066ine endf
using System;

class Program
{
    static void Main()
    {
        #if endf
            Console.WriteLine("Worked!");
        #endif
    }
}
```

The command that was originally used to repro this issue was:

> `csc.exe /out:Program.exe /t:exe /define:amd64 Program.cs`

But we were also able to reproduce this build error with a .NET Core 3.0 project and building directly with Visual Studio. The error we get in VS is:

> `CS1024: Preprocessor directive expected`

@jaredpar mentioned he tried different code pages: 1200, 1201, 65000, etc., but they all produce the same error.

**Comment by jaredpar** [comment]
This behavior is "By Design". From the spec:

> A Unicode character escape sequence represents a Unicode character. Unicode character escape sequences are processed in identifiers (§2.4.2), character literals (§2.4.4.4), and regular string literals (§2.4.4.5). A Unicode character escape is not processed in any other location (for example, to form an operator, punctuator, or keyword).

This is a keyword position and hence explicitly not supported.
