### ISSUE TITLE
CompletionItem.InlineDescription should be public

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/roslyn#37926]
Currently in `CompletionItem` class property `InlineDescription` is internal.
However,  factory method `Create` with `inlineDescription` is public.

That doesn't make much sense, right?

I have VS extension that uses inline description, and corresponding public factory method, but I cannot even test it properly - I have to use reflection for this purpose.

**Comment by ivanbasov** [comment]
@Dreamescaper the request seems to be correct. Do you want to contribute with a PR fixing it?

**Comment by CyrusNajmabadi** [comment]
Yes.  This makes sense.  It was added originally as something internal for regex completion.  But at this point, it seems like it can be made public.

**Comment by Dreamescaper** [comment]
@ivanbasov 
Sure, will create PR a bit later.
