### ISSUE TITLE
Exception thrown when navigating to implementation from interface

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37923]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/688992/exception-thrown-when-navigating-to-implementation.html)._

---
Suppose I have the following interface in IFoo.cs
```
public interface IFoo
{
  void Bar();
}
```

and suppose I have the following class in Baz.cs
```
public class Baz : IFoo
{
  public void Bar() {}
}
```
Given that my text cursor is on `Bar()` in the `IFoo` interface, when I right click and go to the implementation or when I press Ctrl + F12, I am sent to the function implementation in the `Baz` class but am also presented with a pop up saying , &quot;Exception has been thrown by the target of an invocation.&quot;

I don't expect that pop up to show.

---
#### Visual Studio Feedback System on 8/12/2019, 00:51 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Can't repro this, and we ahven't heard about this issue in the meantime.  Clsoing out.
