### ISSUE TITLE
Preview Changes should not use StringDifferenceTypes.Word

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#3792]
The #2139 [PR - made preview dialog window to use a bit more expansive diff mode ](https://github.com/dotnet/roslyn/pull/2139) introduced the diff change to show [word changes](https://github.com/dotnet/roslyn/pull/2139#discussion_r33724774). This has resulted in a broken experience for Change Signature - Preview change.  Possibly more features.

![image](https://cloud.githubusercontent.com/assets/10550513/8465173/a4e6e4d2-1ffc-11e5-8223-b8e19e947581.png)

You can see the drop down list of the word changes in the document Module1.vb. Instead we want to see each entry representing a single reference change or a definition change.

The repro code:

```VB
Public Class CLass2
    Sub Main()
        $$M3("", 3)
    End Sub

    Public Sub M3(v2 As String, v1 As Integer)
        Throw New NotImplementedException()
    End Sub
End Class
```
Press Ctrl + R + O(Don't use the light bulb feature. This bug will not repro because of the internal bug 977290). This openes up the change signature dialog box. Make some change, for eg, rearrange the parameters. Enable the Show Preview changes checkbox and press 'OK'

Linking #2098 on @heejaechang's request

**Comment by heejaechang** [comment]
@basoundr @dpoeschl hmmm.. in this case, regardless whether we have better syntax differ for presentation or not, using contextless differ probably won't give better result.

it looks like we need some kind of options or callback to preview to customize how to diff (not for view, but for checkbox) two sources for different features.

**Comment by dpoeschl** [comment]
Yeah. It wasn't perfect with Line diffing either, but it looked less ridiculous than this. :smile: Even a simple option to go back to line diffing would fix Change Signature, but we may need something larger than that in the general case (as you suggest).

**Comment by Pilchie** [comment]
Ah, this was the issue I was thinking about when looking at #4059.

**Comment by dpoeschl** [comment]
@heejaechang Is there a good use-case for having Word diffing instead of Line Diffing other than the TS example in internal bug 1037274 (in the old DB)? I've piped through an option but I'm wondering if we should really just switch back to Line diffing completely.

**Comment by dpoeschl** [comment]
@heejaechang Ping. I'm considering just changing back to Line diffs (instead of piping an option through)...

**Comment by heejaechang** [comment]
@dpoeschl if my memory is correct, complaints were that, when a person applied a code action and open a preview, edits there are not separated per logical unit but sometimes merged to one.

**Comment by heejaechang** [comment]
@dpoeschl I can't find exact example, but theoretically example would be

1. a person did rename
2. rename happened multiple times on a line
3. user open a preview window to unselect one of rename of the multiple renames
4. user can't do that because we show whole line as changed rather than each rename happened.

**Comment by dpoeschl** [comment]
Okay, thanks. I think the current implementation causes worse problems than what it was trying to solve, so I propose we roll back to Line diffs for 1.1 and then add a proper Preview Changes experience for this, where individual fixes can override the default behavior by providing spans (not just a simple "I want line diffs" versus "I want word diffs" thing) in a later milestone (this is how VS2013 and prior worked, @rchande looked at it a while back)

**Comment by heejaechang** [comment]
@dpoeschl I am +1 

but about what you said "by providing spans", with our pattern of features passing around forked solution through multiple pipe lines (ex, code action + formatting + later some other transformation), I am not sure whether that is even possible.

I think only way to solve this is us having Syntax Differ which we can control where it separates each changes.

**Comment by heejaechang** [comment]
@dpoeschl by the way, I am not saying the diffing thing must built into preview service itself, preview service itself could accept spans, but I dont think it is that easy for feature to track those spans manually which need something that return those span from two solution I believe.

**Comment by rchande** [comment]
@dpoeschl @heejaechang I found that trying to pass in spans was extremely difficult (and not feasible from a third party perspective) for the reasons HeeJae mentions. However, I wonder if we could accomplish this with annotations. There would be two annotations: one for original nodes being modified, and one for newly inserted nodes, as well as an optional mapping from an original document annotation to a new document annotation. However, I can imagine the heuristics required to make good diffs (ie, an expression marked for replacement with two subexpressions marked for replacement with only the subexpression changed) as complicated as syntax diffing.
