### ISSUE TITLE
Add support for document specific analyzer options

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#3798]
This work is needed for analyzers that need host independent, but project specific options, either from the msbuild project file or separate options file. For example, threading the TargetFrameworkMoniker from project file down to the analyzer, to determine whether or not analyzer should be executed for the target platform.

The current thinking about the work involved here is to:
- [ ] Investigate moving the `OptionSet` infrastructure down to the compiler layer so that analyzers can talk about options the same way that the rest of roslyn does (see #7059)
- [ ] Plumbing work needed to thread these options through the language service\compilers to the analyzer APIs.
- [ ] #5641: Once we have these options at the workspace level, we will need to rerun analyzer when options change

As these investigations evolve, we should update this story with issue ids.

**Comment by sharwell** [comment]
This is important for DotNetAnalyzers/StyleCopAnalyzers#1481 (forced to comment so GitHub will show updates under my "Participating" tab).

**Comment by ruant** [comment]
@Pilchie Is this still `In Progress`?

**Comment by Pilchie** [comment]
@agocke and others are currently working on it.  @jinujoseph for more status.

**Comment by masters3d** [comment]
Is there an update to this? Could somebody point me to the equivalent of https://www.jetbrains.com/help/resharper/Refactorings__Adjust_Namespaces.html ?

**Comment by Joe4evr** [comment]
Update on this? I need #4464 for my generic constraints analyzers so I can inform users of my `[SelfType]` to move to the implementation by dotnet/csharplang#6000 when their project targets .NET7 or above.

**Comment by mavasani** [comment]
This work has already been done by allowing MSBuild properties to be threaded to the analyzers and source-generators via editorconfig options. Please see documentation at https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md#consume-msbuild-properties-and-metadata
