### ISSUE TITLE
Property on Generic type class with class? constract not analysed correctly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37987]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/683735/property-on-generic-type-class-with-class-constrac.html)._

---
In the below example the Data property is underlined saying 

"Non-nullable property 'Data' is uninitialized."

```cs
public class ApiResponse<T>
        where T : class?
{
    public T Data { get; set; }
}

```

---
#### Visual Studio Feedback System on 8/9/2019, 02:33 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by RikkiGibson** [comment]
@cston I think this is actually by-design, because the type argument to `ApiResponse` may still be a non-nullable reference type even when a `class?` constraint is specified.

**Comment by cston** [comment]
As @RikkiGibson mentioned, the warning is by design because `T` may be a nullable reference type.
