### ISSUE TITLE
CSharpCompilation treats var on dynamic property differently on dnx451 vs dnxcore50

### ISSUE THREAD

**Issue by lajones** [dotnet/roslyn#3799]
I have a .cs file which is produced from a Razor Template. The .cs file produced has a class which inherits from a base class on which there is a dynamic property, Model. In the Execute() method of this class I have:

```
        public override void Execute()
        {
           var myCount = Model.Count;
           if (myCount > 0)
           {
               // do something
           }
        }
```

The Model property is set to an object with a public int Count property on it before the Execute() method is called.

I create a CSharpSyntaxTree from the text in the .cs file. Then I call CSharpCompilation.Create() passing in the syntax tree and relevant references. Then I call compilation.Emit() on the CSharpCompilation object created.

On dnx451 this works fine. On dnxcore50 it works only if I change the var local variable definition to an int. When I left it as var on dnxcore50 I got:

error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.Binder.BinaryOperation'

pointing to the `if (myCount > 0)` line.

I have a VS solution which shows this problem on request.

**Comment by jaredpar** [comment]
Can you give us some more details here?  In particular the set of references that you are using?

I'm not quite clear how the dnx451 and dnxcore50 comes into play here.  Could you elaborate a bit?

**Comment by jaredpar** [comment]
Looking closer this appears to be a known issue.  That particular error indicates that a reference to Microsoft.CSharp.dll is missing from the compilation.  It has much of the mechanics used to implement `dynamic`.  Adding a reference to that DLL will fix the issue.
