### ISSUE TITLE
Refactoring to add [DebuggerDisplay("{GetDebuggerDisplay(),nq}")]

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#37990]
Would you accept a refactoring on the header of a type containing an overridden ToString to add `[DebuggerDisplay("{ToString(),nq}")]` and `using System.Diagnostics;`?

I'm typing this all the time without intellisense because of the rare namespace.

The `nq` specifier means "no quotes" and it prevents the custom instance being surrounded with curlies and displayed as `{value}`. This is rarely something I want, whether it's `{0}` or `{C:\some\file.txt}` or `{Some(42)}` and `{None}`.

I'd happily send a PR your way if this sounds good to you.

**Comment by CyrusNajmabadi** [comment]
I think this sounds nice.  but @dotnet/roslyn-ide @sharwell on bar check if it would be accepted in roslyn itself.

**Comment by jnm2** [comment]
This is also @jaredpar's preferred pattern from https://blogs.msdn.microsoft.com/jaredpar/2011/03/18/debuggerdisplay-attribute-best-practices/.

**Comment by CyrusNajmabadi** [comment]
> This is also @jaredpar's preferred pattern

Oh... i retract my support then.

**Comment by jaredpar** [comment]
That is a decade ago @jaredpar preference. He was a bit weird. 😄 

I actually have never dug into why the Roslyn repository structured their `DebuggerDisplay` this way. Those who did it were painfully aware of the problems that lead me to writing that particular blog post (had to listen to me rant in person). I'd be interested in knowing if there was a specific reason this was done (other than maybe to annoy decade ago @jaredpar).

**Comment by dibarbet** [comment]
Design review outcome -
@jnm2 would a debugger option to just omit the curly braces satisfy your request?

Otherwise, we would accept a PR that would create a refactoring to generate a new method/property (e.g. GetDebuggerDisplay) and adds the proper attribute.   We wanted to check with @jaredpar - what is the current recommended form to use for a debugger display (and should it use a property / method).

**Comment by jaredpar** [comment]
> what is the current recommended form to use for a debugger display (and should it use a property / method

I'd defer to @tmat suggestion here as he is the expert in this area space and owns much of the surrounding product code.

**Comment by tmat** [comment]
Adding `[DebuggerDisplay("{ToString(),nq}")]` is unnecessary if the class already overrides `ToString`. The EE uses `ToString` if `DebuggerDisplay` is not present.

The reason why you would add `DebuggerDisplay` is when you want it to be different from `ToString`. In that case the recommended pattern is to add a private method `GetDebuggerDisplay()` and `[DebuggerDisplay("{GetDebuggerDisplay(),nq}")]` attribute. The method is preferred over a property since properties are auto-evaluated and displayed in the object view, so an extra property would unnecessarily clutter the view.

**Comment by jnm2** [comment]
@that Isn't it true that the `,nq` part is *not* what the EE does by default when ToString is overridden? That part is the motivation for this issue.

**Comment by sharwell** [comment]
@jnm2 There are two parts to the design review outcome:

1. If all you are looking for is the `,nq` behavior, would it be sufficient to provide an IDE-wide debugger option to _not_ surround the implicit evaluation results with braces?
2. For users that still want debugger-specific display, we would accept a pull request to call `GetDebuggerDisplay()`, and at the same time create that method if it does not already exist (the default implementation could simply return the result of calling `ToString()`).

**Comment by tmat** [comment]
>  provide an IDE-wide debugger option to not surround the implicit evaluation results with braces?

I don't think we want to add yet another debugger option. I'm not sure why we decided to wrap the result of `ToString` in curly braces, but presumably it is to denote the fact that it's a result of `ToString` function, not a true value of the object.

> This is rarely something I want, whether it's `{0}` or `{C:\some\file.txt}` or `{Some(42)}` and `{None}`.

@jnm2 Why are the curlies an issue?

> For users that still want debugger-specific display, we would accept a pull request to call `GetDebuggerDisplay()`, and at the same time create that method if it does not already exist (the default implementation could simply return the result of calling `ToString()`).

I like this proposal.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/38090

**Comment by jvmap** [comment]
As an outsider, I don't understand what was solved or changed with this issue or #38090.
I found this thread while researching how to get rid of some unwanted curly braces in my `DebuggerDisplay` output.
It looks like writing a private `GetDebuggerDisplay` method with the correct formatting would be right approach.

**Comment by CyrusNajmabadi** [comment]
@jvmap Not sure what is unclear here.  The refactoring speeds up writing a common pattern that is somewhat annoying to write out by hand.  

> It looks like writing a private GetDebuggerDisplay method with the correct formatting would be right approach.

That seems reasonable.  This refactoring is letting the debugger know that it should call that private method on your behalf in the debuffer.

**Comment by jvmap** [comment]
@CyrusNajmabadi Thanks, I thinks it clicks now. Looks like this is about this feature:

<img width="1330" height="659" alt="Image" src="https://github.com/user-attachments/assets/e8966c42-aae4-4010-bba5-433963dbeae7" />

I think my mind was overcomplicating the original request for a "refactoring on the header of a type". Believing the OP wanted to refactor the compiler 😊
