### ISSUE TITLE
Disable 'Ok' in Extract Interface Dialog

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#3800]
![image](https://cloud.githubusercontent.com/assets/10550513/8466847/f89ebd66-200b-11e5-8c57-127ee512dd6a.png)

During Extract Interface, if there are no items selected to be extracted then we need to disable 'OK' button instead of showing another dialog box "You must select at least one member.", like above.

**Comment by dpoeschl** [comment]
Removing milestone to trigger triage.

**Comment by ndung** [comment]
Hi @basoundr, Can I introduce this feature (extract interface) in my own codefix provider? If yes, how can I use the API? Thanks

**Comment by dpoeschl** [comment]
@ndung The [extract interface service](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/ExtractInterface/AbstractExtractInterfaceService.cs,7e40f2aa944992d0,references) and its UI are currently internal. Would you be interested in using the UI as part of your codefix, or would you want to tell the API which members you'd like to generate an interface for?

**Comment by ndung** [comment]
Hi @dpoeschl sorry for the late reply, I was on holiday. Yes, I would be interested in using the UI as part of my codefix, if it is possible. If the built-in UI is not possible, using the API is also okay. Thanks.

**Comment by soon** [comment]
I am going to grab this issue, but I have some questions. Looking through the [ExtractInterfaceDialogViewModel.cs](https://github.com/dotnet/roslyn/blob/0382e3e3fc543fc483090bff3ab1eaae39dfb4d9/src/VisualStudio/Core/Def/Implementation/ExtractInterface/ExtractInterfaceDialogViewModel.cs#L59) I noticed, that there are another error checks along with *"You must select at least one member."*, such as *"Illegal characters in path."* or *"File name must have the "{0}" extension."*. Should they also block the *"OK"* button? Or, maybe, there is no reason for blocking the button at all?

**Comment by Pilchie** [comment]
I always go back and for on things like this.  On the one hand, it's nice to be all contextual, and block off the buttons when you know they can't work.  On the other hand, leaving it enabled with a good error message can teach the user *why* it can't work, whereas they may be confused about why the button is disabled.

I guess that's why modern websites have the little validation markers beside fields, but I can't imagine adding those to this dialog...

**Comment by Eyas** [comment]
Perhaps a text block next to the button displaying the error message if disabled? Or just ''wontfix''ing this, as I agree the messages are helpful.

**Comment by Pilchie** [comment]
Deal, let's just Won't Fix until/unless reconsider a general move toward including validation messages in a lot more places.
