### ISSUE TITLE
Cannot use scaffolding in IDE with using declarations

### ISSUE THREAD

**Issue by jessicah** [dotnet/roslyn#38003]
**Version Used**: Visual Studio 2019 16.3.0 Preview 2.0

**Steps to Reproduce**:

1. A function with `using DisposbleType x = new DisposableType()`
2. Try to scaffold something, e.g. an ASP.NET Core View with EF Core

**Expected Behavior**: View is successfully scaffolded

**Actual Behavior**: Error: 'Could not get the reflection type for DbContext : Example.Models.myDbContext'

Changing the using declaration to a using statement makes the error go away.

**Comment by vatsalyaagrawal** [comment]
Please provide more information about issue to help us understand this better. If possible please share sample code.

**Comment by jessicah** [comment]
```
{
	var message = new MimeMessage();

	using (var client = new SmtpClient())
	{
		await client.ConnectAsync("smtp.fastmail.com", 465, true).ContinueWith(async _ =>
		{
			await client.AuthenticateAsync("boltraceteam@boltrace.team", "yxb9l3cesn2rknga");
		}).ContinueWith(async _ =>
		{
			await client.SendAsync(message);
		}).ContinueWith(async _ =>
		{
			await client.DisconnectAsync(true);
		});
	}

	return View();
}
```

If replace the line `using (var client = new SmtpClient())` with `using var client = new SmtpClient();` then scaffolding fails to create views.

E.g. a function like:
```
public async Task<IActionResult> PendingRequests()
{
	var pendingMembers = await _context.Member.Where(member => member.Joined == false).ToListAsync();

	return View(pendingMembers);
}
```
will fail to scaffold the view with the using declaration in the other method, but will succeed if changed back to a using statement.

When have multiple nesting levels of using statements, it's much cleaner to use using declarations instead, e.g.
```
using Stream stream = await httpClient.GetStreamAsync(url);
using StreamReader streamReader = new StreamReader(stream);
using JsonReader reader = new JsonTextReader(streamReader);
```

**Comment by jessicah** [comment]
This is an issue with scaffolding, doesn't that use Roslyn? Examples compile fine, just not with scaffolding.

**Comment by jessicah** [comment]
Also, C# 8 doesn't require any nesting at all with using declarations.

**Comment by svick** [comment]
I believe this is a duplicate of https://github.com/aspnet/Scaffolding/issues/1055: if you use a C# 8.0 feature in your code (`using` declaration in this issue, `switch` expression in the linked issue), and then try to use ASP.NET Core Scaffolding, you get the error "Could not get the reflection type for DbContext".

**Comment by jessicah** [comment]
@svick yes, this does appear to be an exact duplicate of https://github.com/aspnet/Scaffolding/issues/1055, just with using declarations instead. I'll follow that one.
