### ISSUE TITLE
CA2235 complains that int and string fields are not serializable.

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#3801]
This code gives CA2235 on the declaration of `n`.
````
[Serializable]
class Foo : ISerializable
{
    int n;
}
````
Also, if you accept the fix to put the `[NotSerialized]` attribute on `n`, the diagnostic doesn't go away, and it will let you add another `[NotSerialized]` attribute.

The same thing happens with a `string` field.

**Comment by hvanbakel** [comment]
Just looked this problem up, error is in
roslyn/src/Diagnostics/FxCop/Core/Usage/SerializationRulesDiagnosticAnalyzer.cs

Below code is incorrect, should check for valuetypes.
```
            private bool IsSerializable(ITypeSymbol namedTypeSymbol)
            {
                return namedTypeSymbol.GetAttributes().Any(a => a.AttributeClass == _serializableAttributeTypeSymbol);
            }
```

**Comment by jmarolf** [comment]
This has been fixed by https://github.com/dotnet/roslyn-analyzers/pull/261

**Comment by jmarolf** [comment]
@lgolding can you verify this please?

**Comment by lgolding** [comment]
@jmarolf Verified!
