### ISSUE TITLE
Refactoring to populate property initializer

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#38011]
```cs
new User
{
  $
}
```
Trigger on cursor `$` ->
```cs

new User
{
  FirstName = ,
  LastName = ,
}
```

**Comment by alrz** [comment]
Same for method calls would also be useful with long list of parameters. (user should probably prompted to select overload, if any)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lacak of feedback.
