### ISSUE TITLE
Editor for comments in C# code or any kind of code that Visual Studio handles

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38028]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/691325/editor-for-comments-in-c-code-or-any-kind-of-code.html)._

---
It would be time to have a small revamp of the comments in C# code or why not any code for which we can add HTML including images, formming text with colors etc... A comment like in OneNote which is a small editor we can format the text and then the box disapears after you finish your comment.  That would be very productive.

Of course OneNote is somewhat limited but it's a good start !

### You see even here I can make text BIG but OneNote is a better example LOL!

---
#### Jane Wu [MSFT] on 8/13/2019, 02:54 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
