### ISSUE TITLE
using alt+enter refactor code, scope:Project translation is missing 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38032]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/524119/using-altenter-refactor-code-scopeproject-translat.html)._

---
using alt+enter refactor code, scope:Project translation is missing

---
#### Visual Studio Feedback System on 4/9/2019, 11:36 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by vatsalyaagrawal** [comment]
@tmeschter please help with identifying the label that is not localized.

**Comment by tmeschter** [comment]
Not clear. I suggest asking the original customer for further information.
