### ISSUE TITLE
Roslyn loses information about default value being assigned to a struct in case there are multiple casts

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#38030]
**Version Used**: 

```
Branch master (13 Aug 2019)
Latest commit a08336 by David:
Merge pull request #37916 from dibarbet/partial_load_str

Update partial load dialog string to better match task center.
```

**Steps to Reproduce**:

Compile and run the following code:
```cs
#nullable enable
struct S
{
  string field;
    
  public S(string s) => field = s;
    
  static void Main()
  {
    S s = (S) (S) default;
    s.field.ToString(); // no warning
  }
}
```

**Expected Behavior**:
`warning CS8602: Dereference of a possibly null reference.` for `s.field.ToString()`

**Actual Behavior**:
No warnings. The program crashes at runtime with a `NullReferenceException`

**Comment by RikkiGibson** [comment]
Interestingly, the warning starts to appear again when `default` is changed to `default(S)`. It makes me wonder if the behavior will change at all after the target-typed default change goes in.
