### ISSUE TITLE
IntelliSense Return vs. RetrieveVirtualItemEventArgs

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38035]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/684599/intellisense-return-vs-retrievevirtualitemeventarg.html)._

---
<p>Hello, <br><br>since some time there is a class &quot;RetrieveVirtualItemEventArgs&quot;. <br>But the problem: every time I try to write &quot;Return&quot; by &quot;ret&quot; and then Tab (like it was LONG time) IntelliSense has this &quot;RetrieveVirtualItemEventArgs&quot; and uses this. </p> <p>After some uses of &quot;Return&quot; in the IntelliSense it suggest also &quot;Return&quot; now on, but after a new program start the &quot;RetrieveVirtualItemEventArgs&quot; is the top suggestion.</p> <p>In the fact that Return is written WAY more often in general, and also some other words/commands. It would be nice to get an option or menu where you can config the default top suggestions for IntelliSense. <br>Like so:<br>There is a menu entry for the IntelliSense with a listbox, where you can enter the default top suggestions for the IntelliSense, which the IntelliSence can use for the first appearance of a situation, where no current session information about the last usages of any suggestions. <br>This would be great to be able to config the own IDE environment in this way, to get a better user experience. <br><br>Sincerely yours<br>Kay </p>

---
### Original Comments
(no comments)

**Comment by sharwell** [comment]
Proposal: before falling back to an alphabetical ordering for selection, prefer to match an in-scope name (e.g. a keyword) before matching an out-of-scope name (e.g. a name from an unimported namespace).

**Comment by mavasani** [comment]
Design meeting review:
- Make sure the proposed behavior is not already implemented 
- If not, then needs more info from customer

**Comment by mavasani** [comment]
@jinujoseph @sharwell who should be assigned this issue for investigation?

**Comment by CyrusNajmabadi** [comment]
Not repro:

![image](https://user-images.githubusercontent.com/4564579/199300699-d651cf6d-ddd6-4ed5-b03a-4e4cbc15863e.png)
