### ISSUE TITLE
Qualifying static member suppresses refactoring suggestions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38031]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/679110/qualifying-static-member-suppresses-refactoring-su.html)._

---
This code with qualification of defaultInstance produces no refactoring or static analysis suggestion:

```
        public class TrayJob
        {
            private static TrayJob defaultInstance = new TrayJob();
            internal static TrayJob Default =&gt; TrayJob.defaultInstance;
```

However, when the qualification is removed there is an IDE044 Make field readonly, I believe from Code Analysis, and refactoring suggestions &quot;Use auto property&quot; and &quot;Make field readonly&quot;.

```
        public class TrayJob
        {
            private static TrayJob defaultInstance = new TrayJob();
            internal static TrayJob Default =&gt; defaultInstance;

```

---
#### Visual Studio Feedback System on 8/7/2019, 11:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Doesn't repro for me:

![image](https://user-images.githubusercontent.com/4564579/218613181-519ac859-ac93-4844-ad2a-e952630aee30.png)
