### ISSUE TITLE
Wrong intellisense for dynamic variable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38034]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/521077/wrong-intellisense-for-dynamic-variable.html)._

---
The picture says it all. Intellisense shows that a member name does not exist on a dynamic variable -- which is pretty much impossible given what dynamic variables are all about.

---
#### Steve on 4/7/2019, 00:27 PM: 

Further information, the wrong intellisense message comes and goes along with a correct intellisense for a subsequent line. The subsequent line is "targetNode.NotifyReplacedAll()" and the intellisense message for that line is on "NotifyReplacedAll", intellisense says "The name 'NotifyReplacedAll' does not exist in the current context". If I comment out this line then the incorrect intellisense on the earlier line (on the dynamic method call) disappears. In other words, it looks like the wrong intellisense message on the dynamic method call is being copied from a correct intellisense message on a subsequent line. 
#### Steve on 4/7/2019, 00:37 PM: 

"Subsequent' in the above does not mean immediately following. There are some intervening correct lines. 
#### Visual Studio Feedback System on 4/8/2019, 02:32 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
There is no picture provided afaict (here or in the original feedback ticket).
