### ISSUE TITLE
intellisense creates a new method after selecting existing method in file and pressing tab

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38033]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/523578/intellisense-creates-a-new-method-after-selecting.html)._

---
I'm trying to wire up an event on variablesGridView.

I type `variablesGridView.ShowingEditor +=` and then press `Alt + Right Arrow` to bring up intellisense.

Intellisense shows available methods, I select `variablesGridView_ShowingEditor` (already exists within file) and then press `Tab`.

Expected:
Should wire up event to existing method, i.e. `variablesGridView.ShowingEditor += variablesGridView_ShowingEditor;`

Actual:
New method with differing capitalisation is created, i.e. 
```
variablesGridView.ShowingEditor += VariablesGridView_ShowingEditor;

private void VariablesGridView_ShowingEditor(object sender, CancelEventArgs e)
{
    throw new NotImplementedException();
}
```

---
#### Visual Studio Feedback System on 4/8/2019, 09:37 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
By design.  There's a tooltip up saying to hit tab to complete out eventhookup completion.  Can press `esc` to get out of htat.  Haven't heard about this from anyone else, so the existing interaction model seems fine to keep.
