### ISSUE TITLE
Feature gaps between ruleset and .editorconfig 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#38042]
1. **[Low Priority] Diagnostics with Location.None cannot be configured with .editorconfig** - This issue is low priority given no location diagnostics are rare, and the ones in FxCop analyzers package already have a [workardound](https://github.com/dotnet/roslyn-analyzers/pull/2866) in place to avoid this issue.

2. **[[Fixed](https://github.com/dotnet/roslyn/pull/38792)] Analyzers reporting diagnostics with a source location which are disabled by default cannot be enabled with editorconfig or from command line options**. Note: vast majority of security analyzers contributed by C&E are disabled by default, and they have different SDL rulesets to explicitly turn on different combination of security rules. 

3. **[[Mitigated](https://github.com/dotnet/roslyn/pull/38793)] Individual diagnostic analyzers in an analyzer package cannot be completely disabled in .editorconfig.** A ruleset entry with value “None” or /nowarn would disable the analyzer completely ensuring no analyzer callbacks, while an editorconfig dotnet_diagnostic severity = none entry only ensures diagnostics are filtered out, but analyzer still executes. This scenario is important when user wants to disable a specific bad performance analyzer in an analyzer package, without completely uninstalling the package.

4. Rulesets allow project level diagnostic configuration, and it always applies to the entire compilation regardless of source file locations – such a configuration is a strict requirement for security analyzers. **Editorconfig does not allow project level configuration, which might be problematic, especially when generated files or linked files are involved.**

5. With rulesets, users can conditionally select which ruleset to use based on MSBuild evaluations. For example, they can have different rulesets between debug and release configurations or one ruleset per target framework in multitargeting project or have different rulesets between shipping and non-shipping projects. Additionally, rulesets can be consumed from directories outside the project or solution directory. **Editorconfig does not allow specifying explicit configuration files, they are always implicitly chosen based on file name and directory structure by project system's auto discovery**

**Comment by ryzngard** [comment]
4 above is also tracked as an issue in the editorconfig repo https://github.com/editorconfig/editorconfig/issues/408

**Comment by mavasani** [comment]
All of these gaps are now addressed with [Global AnalyzerConfig](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/configuration-files#global-analyzerconfig) files.

**Comment by JimBobSquarePants** [comment]
The editor experience for Global AnalyzerConfig is still lacking in comparison to ruleset files. With a ruleset I can pick from a selection via the UI. With AnalyzerConfig I have to manually edit the file.

**Comment by mavasani** [comment]
This should ideally be fixed with the new editorconfig UX written by @jmarolf. Jon, did we test it on global analyzer config files as well? If not, can we open a tracking work item for it?

**Comment by jmarolf** [comment]
I'll check that this is fixed in the UI
