### ISSUE TITLE
Quick Info for extension methods should reveal nullable receiver type

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#38047]
**Version Used**: 16.3 Preview 2

**Steps to Reproduce**:

```csharp
static class Extensions {
  public static string AsString(this object? data) => data?.ToString() ?? "";
}

class Example {
  void Method(object? value) {
    value.AsString(); // ← Hover over AsString
  }
}
```

1. Use the above code
2. Hover over the call to `AsString`

**Expected Behavior**:

> (extension) string object?.AsString()

**Actual Behavior**:

> (extension) string object.AsString()

**Comment by jasonmalinowski** [comment]
Works with https://github.com/dotnet/roslyn/pull/40030, this likely was fixed by the compiler's work or was fixed earlier.
