### ISSUE TITLE
provide a way for users to run vsix analyzers on build

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#38051]
some users want to run analyzers and see all issues before invoking fix all for the issues to understand/predict impacts before running fix all.

nuget analyzers work great for this scenario. since you can build to force run them. problem is vsix analyzers including built-in IDE analyzers. since the only way for users to see all issues is turning on full solution analysis and wait for them to run full-analysis.

the catch is our full solution analysis is not built for throughput but as low priority background work. what I mean by that is to reduce the impact on GC and VS UX, it runs on a  lower priority process with plenty of yield to VS to never interfere with VS operations. 

to mitigate this, users can explicitly build to force run analyzers for throughput. VBCSCompiler will run these analyzers for throughput. you can see that VBCSCompiler basically overtake all resources on the machine (100% CPU and IO) since it puts the priority on throughput than VS responsiveness.

but unfortunately, vsix analyzers won't participate in VBCSCompiler. leaving no choice for users to force run those.

we should provide a way to do so. it doesn't need to be VBCSCompiler but a way to force run those for throughput like how we do that for fix all. but to show issues to users.

**Comment by heejaechang** [comment]
tagging @stephentoub

**Comment by stephentoub** [comment]
Thanks

**Comment by sharwell** [comment]
I'm opposed to the introduction of a "feature" that runs the VSIX analyzers _on build_, as it will mislead users into thinking they are part of the build in a way that can impact the build outcome. These analyzers are not part of a build.

I would be in favor of allowing them to run to completion on demand, e.g. by creating a new command to trigger their execution with progress reporting.

**Comment by ryzngard** [comment]
Design Review: We agree that running VSIX analyzers on a build by default. We would be willing to accept a proposal to adjust the "Run Code Analysis" feature to handle this analysis on demand. @mavasani can you follow up with a concrete proposal?

**Comment by mavasani** [comment]
Also requested on developer community [here](https://developercommunity.visualstudio.com/content/problem/784334/code-analysis-on-solution-only-shows-naming-violat.html) for viewing all naming violations on the solution.

**Comment by mavasani** [comment]
Proposal:
1. Re-purpose "Run Code Analysis" on Project/Solution commands to force complete live analyzer execution of all analyzers for the project (all NuGet analyzer packages installed + VSIX analyzers, including IDE code style analyzers). This will be the new behavior for all managed projects (csproj based + SDK style)
2. Do not add a new "Run Legacy Code Analysis" for executing legacy code analysis. Instead, allow users to start Visual Studio with an environment variable, say `EnableLegacyCodeAnalysis = true`, to switch "Run Code Analysis" commands back to running legacy FxCop for 16.x releases. We anyways plan to deprecate legacy FxCop in 17.0 VS release.

PRs:
1. https://github.com/dotnet/roslyn/pull/39596
2. https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/211392
