### ISSUE TITLE
IDE0060 doesn't consider nameof to be a use

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#38050]
**Version Used**: 
3.3.0-beta3-19413-06+ac06df1bffb7b7fd0e5bf63cc91921af76b21e03

**Steps to Reproduce**:
```C#
private static void ValidateStartIndexAndLength_Throw(int startIndex, int length) =>
    throw new ArgumentOutOfRangeException(startIndex < 0 ? nameof(startIndex) : nameof(length));
```

**Expected Behavior**:
No warnings.

**Actual Behavior**:
IDE0060 triggers "Remove unused parameter 'length'"

Is that by-design?

**Comment by mavasani** [comment]
Yes, the analyzer flags parameters without any value reads. Seems this might be a good case for an explicit source suppression.

**Comment by sharwell** [comment]
@stephentoub We mark intentionally unused parameters with a discard:

```csharp
// not used by this method
_ = startIndex;
```

**Comment by stephentoub** [comment]
>  We mark intentionally unused parameters with a discard

Sure. The question here is whether this is actually "unused". It's true that the parameter is never read from, but it is used in source. One could make a similar argument about a discard, as the generated IL won't contain a read, even in Debug.

It just strikes me as a strange that nameof isn't considered "use" for the purpose of this rule. My mental model is whether the method would continue compiling if the argument were removed (the method itself, not the program), and in this case, it certainly would not.

(I will probably just change the source to delete the parameter and use a normal string instead.)

**Comment by mavasani** [comment]
@stephentoub The idea is to help users avoid unnecessary computation or unintentional functional bugs by flagging unused value computation, which could likely happen here at every callsite. For example, assume if it needed some expensive computation for argument value passed to such a parameter. You can achieve the nameof functionality by instead defining a constant field or local.

**Comment by mavasani** [comment]
We can certainly improve the messaging here. We also flag parameters which are immediately overwritten in the callee and for both these cases the current message is confusing. It should probably say that the initial value assigned to the parameter from the call site is never used.

**Comment by mavasani** [comment]
@gewarren Do you have a suggestion on messaging for this case?

**Comment by gewarren** [comment]
@mavasani Just to clarify, are we trying to improve the wording of "Remove unused parameter 'length'"?

**Comment by mavasani** [comment]
Yes, that is correct. We want to convey that the runtime value passed to parameter length from the caller is never used, hence the parameter can be removed.

**Comment by gewarren** [comment]
Perhaps:

The parameter 'length' or the value that's value passed to it is not used; this parameter can be removed.

 Remove parameter 'length': it or the value that's passed to it is not used.

**Comment by mavasani** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/813311/fehler-in-codeanalyse-unbenutzter-parameter.html

**Comment by mavasani** [comment]
Reported at https://developercommunity.visualstudio.com/content/problem/866572/editor-zeigt-unbenutzten-methodenparameter-an-der.html
