### ISSUE TITLE
MissingAnalyzerReference error

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#3805]
Most errors reported from the compiler / IDE have ids that look like 'AB1234'. However looks like we have some errors such as the one mentioned in the title of this issue (not sure if this is being produced from core compiler or IDE) with camel cased errors ids. We should change this id to provide a consistent experience.

![capture](https://cloud.githubusercontent.com/assets/10579684/8467786/f9a29262-2017-11e5-9cf9-29efec357922.PNG)

**Comment by heejaechang** [comment]
duplicated #3794
