### ISSUE TITLE
IDE0057 incorrectly handles substrings on String itself

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#38055]
**Version Used**: 
3.3.0-beta3-19413-06+ac06df1bffb7b7fd0e5bf63cc91921af76b21e03

**Steps to Reproduce**:
This is a super corner-case only relevant to a few people in the world, so I'll understand if you want to close it.  Just opening the issue in case.

The definition of System.String itself uses its own Substring in a few places, e.g.
```C#
splitStrings[arrIndex++] = Substring(currIndex, sepList[i] - currIndex);
```
IDE0057 fires here, and transforms it into:
```C#
splitStrings[arrIndex++] = Substring[currIndex..sepList[i]];
```
which doesn't compile.  It should have been transformed instead into:
```C#
splitStrings[arrIndex++] = this[currIndex..sepList[i]];
```
which works fine.

**Comment by CyrusNajmabadi** [comment]
i definitely did not consider this case :)
