### ISSUE TITLE
VS 16.1.6 - Collection Initializer Comment Bug

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38065]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/696534/vs-1616-collection-initializer-comment-bug.html)._

---
Autocomplete interferes when I try to type a space then a comment on a collection initializer line.
e.g. I'm expecting to get ```[new Version(1, 1)] = new Version(2, 3, 4, 0), /```
but instead I get ```[new Version(1, 1)] = new Version(2, 3, 4, 0), Version/```

Here is a code sample:
```csharp
using System;
using System.Collections.Generic;

namespace Collection_Initializer_Comment_Bug
{
    public static class C
    {
        public static readonly Dictionary<Version, Version> TestDictionary = new Dictionary<Version, Version>
        {
            [new Version(1, 0)] = new Version(1, 2, 3, 0), // Test comment
            [new Version(1, 1)] = new Version(2, 3, 4, 0),
        };
    }
}
```

See attached screenshot.

---
#### Visual Studio Feedback System on 8/15/2019, 07:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ivanbasov** [comment]
Reproduced. Interesting issue: 
1. `/` is a commit character.
2. When typing space in the collection initializer, there is a completion session to add a new element (`Version` in the example)
3. When we press `/` with the active completion session, we commit the active completion item.

**Comment by miloush** [comment]
Yes, the question is is there a valid scenario where typing Version was desired here rather than [ ... which I assume is a commit character too.

**Comment by ivanbasov** [comment]
Thank you, @miloush !

I think we should implement something like this:
* if the completion trigger is space (user may or may not want to trigger completion with it)
and 
* if the commit character is not Enter, Tab or space
and 
* if the committing item does not start with the commit character
then
cancel the commit.

@sharwell and @CyrusNajmabadi , what do you think?

**Comment by miloush** [comment]
That doesn't seem to be a very consistent experience to me. I was trying to suggest that perhaps there shouldn't be anything at all in the autocompletion list when typing a dictionary initializer.

**Comment by miloush** [comment]
Unless the idea here is to correct this for all collection initializers, not just dictionary, in which case I don't think the existing behaviour should be changed because the autocompletion is a valid entry:

```C#
const int Value = 4;
List<int> = new List<int>
{
    Value,|
}
```

You should be able to type a space and slash and get `Value/` if you wanted to write e.g.
```
    Value, Value / 2, Value / 4
```

**Comment by CyrusNajmabadi** [comment]
Doesn't repro.  After the space i get:

![image](https://user-images.githubusercontent.com/4564579/218613891-26199a97-bcaf-4a12-8929-e5bf72522597.png)

Then after teh `/` i get:

![image](https://user-images.githubusercontent.com/4564579/218613914-7c1b25c8-e9dc-4af5-ae6a-d2afc00da334.png)

Which all seems to be working as expected.
