### ISSUE TITLE
SymbolKey loses nullability information

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#38061]
When using `ISymbol.GetSymbolKey()` if the symbol is an `ITypeSymbol` the nullability information is lost.  Possibly related to #30326

**Comment by CyrusNajmabadi** [comment]
Closing out.  This is by design.  Symbolkey very much is intended to have a metadata/binary-view of things.  Nullability isn't relevant there.  If it needed, the feature-lvel code needs to handle that.
