### ISSUE TITLE
Generated Equals(T) method has pointless [AllowNull] when T is a value type

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#38069]
**Version Used**: Visual Studio 16.2.2

Generate equality members for:

```cs
struct Foo
{
    public int Bar { get; }
}
```

Result:

```cs
    public bool Equals([AllowNull] Foo other)
    {
        return Bar == other.Bar;
    }
```

Expected behavior: `[AllowNull]` should not be added for value types.

**Comment by sharwell** [comment]
The generated method should only have `[AllowNull]` when the parameter is a generic type parameter which is not constrained to be a reference type.
