### ISSUE TITLE
Expose  CSharpSyntaxFactsService.Instance

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#38078]
It contains useful helpers for third party analyzers.

**Comment by CyrusNajmabadi** [comment]
What helpers would you like to see exposed?

**Comment by JohanLarsson** [comment]
Oh, you are right, did not look close at it. Most of the methods does not look terribly useful.
- `CSharpSyntaxFactsService.IsInStaticContext()`
- `CSharpSemanticFactsService.IsInExpressionTree`

^ are two I find myself reimplementing over and over. Maybe better with separate issues for things I want exposed.

Above is not a complete list, have to scan through it some time.

**Comment by jmarolf** [comment]
>Maybe better with separate issues for things I want exposed.

This sounds like a good approach. [ISyntaxFactsService.cs](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/LanguageServices/SyntaxFactsService/ISyntaxFactsService.cs) is just a set of helpers and has not been designed as a public API. If there is a function you find yourself needing then we should try and find a way to provide it, but I don't think exposing SyntaxFacts is the corrrect approach.

**Comment by sharwell** [comment]
> ISyntaxFactsService.cs is just a set of helpers and has not been designed as a public API. If there is a function you find yourself needing then we should try and find a way to provide it

This is a very good statement on the current implementation. @JohanLarsson I'm going to close _this_ issue as Won't Fix, but if you find yourself in need of specific features from this service please do open a more specific issue. 👍
