### ISSUE TITLE
IDE0016 is crashing on System.Private.CoreLib

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#38081]
**Version Used**: 
3.3.0-beta3-19413-06+ac06df1bffb7b7fd0e5bf63cc91921af76b21e03

**Steps to Reproduce**:
Open System.Private.CoreLib in dotnet/coreclr and run IDE0016's fix all.
```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax'.
  Source=Microsoft.CodeAnalysis.CSharp.Workspaces
  StackTrace:
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.ThrowExpression(SyntaxNode expression) in /_/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs:line 3251
```
![image](https://user-images.githubusercontent.com/2642209/63218783-af96d700-c130-11e9-908a-bd2b910c8af2.png)

It appears to be while processing ArrayList.cs:
![image](https://user-images.githubusercontent.com/2642209/63218792-14523180-c131-11e9-958d-902644d86e3b.png)

And it appears to be very confused, with the `assignmentValue` being for the attribute in the DebugView at the end of the file:
![image](https://user-images.githubusercontent.com/2642209/63218799-38157780-c131-11e9-8df2-9022e5be7156.png)

**Comment by huoyaoyuan** [comment]
I cannot reproduce this now.
Line triggered: ArrayList.cs L2696
Version used: VS 16.8 P3.2
The codefix functions well now.

**Comment by stephentoub** [comment]
Closing under the assumption it's been fixed in the last year. Thanks.
