### ISSUE TITLE
LSP strips `applicableToSpan` for CodeRefactorings / CodeFixes

### ISSUE THREAD

**Issue by petrroll** [dotnet/roslyn#38097]
As part of an attempt to make refactorings more discoverable #35525 we've enabled refactorings to report their `applicableToSpan` to [CodeRefactoringService](https://github.com/dotnet/roslyn/pull/37941/files#diff-b320a36be29b9923d16fc29409d901e2R132) and further to `SuggestedActionsSource` where it's used to order them (within each other & w.r.t. to CodeFixes (from analyzers) depending on distance from "current selection/caret location".

The issue is that LSP currently doesn't transport that information & so we [discard it](https://github.com/dotnet/roslyn/pull/37941/files#diff-902163083c57dbeff4aa50a0ee091870R43) before sending and then don't have the information on [receiving end](https://github.com/dotnet/roslyn/blob/release/dev16.4-preview1/src/Tools/ExternalAccess/LiveShare/CodeActions/RoslynCodeActionProvider.cs#L75).

It is worth noting that this issue hasn't been created by the abovementioned change (#37941) to Refactorings but merely amplified. Even before this change the `applicableToSpan` of CodeFixes that - in normal situation comes from diagnostics - has been stripped within LSP due to the fact that CodeFixes were treated the same way as refactorings (CodeAction in LSP language).

The impact of this issue is inconsistent ordering between local and remote (LSP) experience. Especially, the LSP experience will have static non-current-selection informed ordering that might be very inconvenient, especially if we go further in the direction of offering more - better ordered - refactorings.

**Comment by petrroll** [comment]
Semi-related (?create separate issue). Right now there's special logic for handling Refactorings & CodeFixes in the `SuggestedActionsSource`. When no-selection is made all refactorings [get low priority](https://github.com/dotnet/roslyn/blob/a79c03e509607e6616269e72d5c370f4c240c42c/src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs#L219). 

Due to the fact that LSP merges everything into essentially refactorings this priority change doesn't have the same effect if the source of CodeActions is from LSP.

**Comment by petrroll** [comment]
Potentially another issue will surface with Diagnostics severity info being lost. #38271 proposes using it to boosting CodeFixes from diagnostics that have > hidden severity (i.e. those for warnings should be higher). Since the link between diagnostics & codefix is lost within LSP (all is transferred as RefactoringCodeSuggestion) the boost to Priority either needs to happen on server side or the information needs to be communicated back to client.

Another idea: Might want to move to ordering solely on server side (LSP will order, client will just present the results).

**Comment by CyrusNajmabadi** [comment]
@AmadeusW does LSP support passing this information along?
