### ISSUE TITLE
Expose IsInStaticContext

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#38098]
The need comes up every now and then in third party analyzers.

Preferable via a static mehtod and not via some service locator. Maybe it can be added to `SyntaxFacts`?

**Comment by CyrusNajmabadi** [comment]
Could you clarify the semantics you want this to have, and give examples of use cases you would use this for?

**Comment by JohanLarsson** [comment]
I usually implement it like:
```
if (syntaxNode.IsInstaticContext())
{
    ...
}
```

It answers the question if `this` is available at the current position.

One common use case is when generating `nameof(this.Member)` and figuring out if the member access should be qualified.

**Comment by JohanLarsson** [comment]
Also I should not spec the semantics as there is a method with that name already. Expose it and document it as is. Exposing a method with the same name doing something different would be confusing inside Roslyn.

**Comment by CyrusNajmabadi** [comment]
> Also I should not spec the semantics as there is a method with that name already. Expose it and document it as is. 

The problem is that htat locks into those semantics, and these helpers *do* change. i.e. they're generally written for a couple of features, and if the needs of those features change, then we change the helpers.  Documenting this as "this is the helper that answers this specific question for this specific feature" isn't really great.  And being locked into supporting something and not changing it is also worrying.

**Comment by JohanLarsson** [comment]
Ok, maybe a new signature then. `CanUse(SyntaxNode location, ScopeKind.ThisExpression)` and answer the question if `this` can be used.

**Comment by CyrusNajmabadi** [comment]
> I would not have expected IsInStaticContext to change much but I have not really read what the Roslyn implementation does, assumed from the name.

Many many helpers change over time.  The reason being precisely that they're just helpers for a few features.  

This one is also somewhat strange.  For example, you might think it means `can i access "this" here`.  Others may think it means `can i only access static members here?`.  The latter interpretation would be what people might intuit, but it's actually *not* what it does.  For example, there are some cases where even if you are "in a static context" you can still access "instance members".

**Comment by CyrusNajmabadi** [comment]
> Ok, maybe a new signature then. CanUse(SyntaxNode location, ScopeKind.ThisExpression) and answer the question if this can be used.

Easiest way to answer that currently would be to use the completion API and see if `this` is offered.  Then, you're basically getting the answer to the best of our knowledge about if it's ok.  Indeed, if i look at the impl for how we determine that, we don't use `IsInstaticContext` at all ourselves.

**Comment by JohanLarsson** [comment]
Ok, closing this then, no biggie.
